LLVM: include/llvm-c/blake3.h File Reference
blake3.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct llvm_blake3_chunk_state
struct llvm_blake3_hasher
Macros
#define LLVM_BLAKE3_VERSION_STRING "1.3.1"
#define LLVM_BLAKE3_KEY_LEN 32
#define LLVM_BLAKE3_OUT_LEN 32
#define LLVM_BLAKE3_BLOCK_LEN 64
#define LLVM_BLAKE3_CHUNK_LEN 1024
#define LLVM_BLAKE3_MAX_DEPTH 54
Functions
const char * llvm_blake3_version (void)
void llvm_blake3_hasher_init (llvm_blake3_hasher *self)
void llvm_blake3_hasher_init_keyed (llvm_blake3_hasher *self, const uint8_t key[LLVM_BLAKE3_KEY_LEN])
void llvm_blake3_hasher_init_derive_key (llvm_blake3_hasher *self, const char *context)
void llvm_blake3_hasher_init_derive_key_raw (llvm_blake3_hasher *self, const void *context, size_t context_len)
void llvm_blake3_hasher_update (llvm_blake3_hasher *self, const void *input, size_t input_len)
void llvm_blake3_hasher_finalize (const llvm_blake3_hasher *self, uint8_t *out, size_t out_len)
void llvm_blake3_hasher_finalize_seek (const llvm_blake3_hasher *self, uint64_t seek, uint8_t *out, size_t out_len)
void llvm_blake3_hasher_reset (llvm_blake3_hasher *self)
Macro Definition Documentation
LLVM_BLAKE3_BLOCK_LEN
#define LLVM_BLAKE3_BLOCK_LEN 64
Definition at line 30 of file blake3.h.
LLVM_BLAKE3_CHUNK_LEN
#define LLVM_BLAKE3_CHUNK_LEN 1024
Definition at line 31 of file blake3.h.
LLVM_BLAKE3_KEY_LEN
#define LLVM_BLAKE3_KEY_LEN 32
Definition at line 28 of file blake3.h.
LLVM_BLAKE3_MAX_DEPTH
#define LLVM_BLAKE3_MAX_DEPTH 54
Definition at line 32 of file blake3.h.
LLVM_BLAKE3_OUT_LEN
#define LLVM_BLAKE3_OUT_LEN 32
Definition at line 29 of file blake3.h.
LLVM_BLAKE3_VERSION_STRING
#define LLVM_BLAKE3_VERSION_STRING "1.3.1"
Definition at line 27 of file blake3.h.
Function Documentation
llvm_blake3_hasher_finalize()
void llvm_blake3_hasher_finalize (const llvm_blake3_hasher * self, uint8_t * out, size_t out_len)
Referenced by llvm::BLAKE3::final(), and llvm::BLAKE3::final().
llvm_blake3_hasher_finalize_seek()
void llvm_blake3_hasher_finalize_seek (const llvm_blake3_hasher * self, uint64_t seek, uint8_t * out, size_t out_len)
llvm_blake3_hasher_init()
void llvm_blake3_hasher_init (llvm_blake3_hasher * self)
Referenced by llvm::BLAKE3::init().
llvm_blake3_hasher_init_derive_key()
void llvm_blake3_hasher_init_derive_key (llvm_blake3_hasher * self, const char * context)
llvm_blake3_hasher_init_derive_key_raw()
void llvm_blake3_hasher_init_derive_key_raw (llvm_blake3_hasher * self, const void * context, size_t context_len)
llvm_blake3_hasher_init_keyed()
void llvm_blake3_hasher_init_keyed (llvm_blake3_hasher * self, const uint8_t key[LLVM_BLAKE3_KEY_LEN])
llvm_blake3_hasher_reset()
void llvm_blake3_hasher_reset (llvm_blake3_hasher * self)
llvm_blake3_hasher_update()
void llvm_blake3_hasher_update (llvm_blake3_hasher * self, const void * input, size_t input_len)
Referenced by llvm::BLAKE3::update(), and llvm::BLAKE3::update().
llvm_blake3_version()
const char * llvm_blake3_version (void)
Definition at line 15 of file blake3.c.
References BLAKE3_VERSION_STRING.