LLVM: llvm::AliasSet Class Reference
llvm::AliasSet Class Reference
#include "llvm/Analysis/AliasSetTracker.h"
Public Types
using iterator = SmallVectorImpl<MemoryLocation>::const_iterator
using PointerVector = SmallVector<const Value *, 8>
Retrieve the pointer values for the memory locations in this alias set.
Public Member Functions
AliasSet (const AliasSet &)=delete
AliasSet & operator= (const AliasSet &)=delete
bool isRef () const
Accessors...
bool isMod () const
bool isMustAlias () const
bool isMayAlias () const
bool isForwardingAliasSet () const
Return true if this alias set should be ignored as part of the AliasSetTracker object.
void mergeSetIn (AliasSet &AS, AliasSetTracker &AST, BatchAAResults &BatchAA)
Merge the specified alias set into this alias set.
iterator begin () const
iterator end () const
unsigned size () const
PointerVector getPointers () const
void print (raw_ostream &OS) const
void dump () const
AliasResult aliasesMemoryLocation (const MemoryLocation &MemLoc, BatchAAResults &AA) const
If the specified memory location "may" (or must) alias one of the members in the set return the appropriate AliasResult.
ModRefInfo aliasesUnknownInst (const Instruction *Inst, BatchAAResults &AA) const
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< AliasSet, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< AliasSet, Options... >::type >, ilist_detail::compute_node_options< AliasSet, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< AliasSet, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< AliasSet, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< AliasSet, Options... >::type::parent_ty *Parent)
Friends
class AliasSetTracker
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< AliasSet, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< AliasSet, Options... >::type >
ilist_node_impl ()=default
Detailed Description
Definition at line 48 of file AliasSetTracker.h.
Member Typedef Documentation
iterator
using llvm::AliasSet::iterator = SmallVectorImpl<MemoryLocation>::const_iterator
Definition at line 120 of file AliasSetTracker.h.
PointerVector
using llvm::AliasSet::PointerVector = SmallVector<const Value *, 8>
Retrieve the pointer values for the memory locations in this alias set.
The order matches that of the memory locations, but duplicate pointer values are omitted.
Definition at line 129 of file AliasSetTracker.h.
Constructor & Destructor Documentation
AliasSet()
llvm::AliasSet::AliasSet (const AliasSet &) delete
Member Function Documentation
aliasesMemoryLocation()
AliasResult AliasSet::aliasesMemoryLocation (const MemoryLocation & MemLoc, BatchAAResults & AA) const
If the specified memory location "may" (or must) alias one of the members in the set return the appropriate AliasResult.
aliasesMemoryLocation - If the specified memory location "may" (or must) alias one of the members in the set return the appropriate AliasResult.
Otherwise return NoAlias.
Definition at line 154 of file AliasSetTracker.cpp.
References llvm::BatchAAResults::alias(), llvm::BatchAAResults::getModRefInfo(), llvm::isModOrRefSet(), llvm::AliasResult::MayAlias, and llvm::AliasResult::NoAlias.
aliasesUnknownInst()
ModRefInfo AliasSet::aliasesUnknownInst (const Instruction * Inst, BatchAAResults & AA) const
Definition at line 174 of file AliasSetTracker.cpp.
References llvm::dyn_cast(), llvm::BatchAAResults::getModRefInfo(), llvm::isModAndRefSet(), llvm::isModOrRefSet(), llvm::Instruction::mayReadOrWriteMemory(), llvm::ModRef, and llvm::NoModRef.
begin()
iterator llvm::AliasSet::begin () const inline
Definition at line 121 of file AliasSetTracker.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
dump()
LLVM_DUMP_METHOD void AliasSet::dump () const
Definition at line 565 of file AliasSetTracker.cpp.
References llvm::dbgs(), and print().
end()
iterator llvm::AliasSet::end () const inline
Definition at line 122 of file AliasSetTracker.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
getPointers()
AliasSet::PointerVector AliasSet::getPointers () const
Definition at line 203 of file AliasSetTracker.cpp.
References llvm::SetVector< T, Vector, Set, N >::insert(), llvm::MemoryLocation::Ptr, and llvm::SetVector< T, Vector, Set, N >::takeVector().
isForwardingAliasSet()
bool llvm::AliasSet::isForwardingAliasSet () const inline
Return true if this alias set should be ignored as part of the AliasSetTracker object.
Definition at line 113 of file AliasSetTracker.h.
isMayAlias()
bool llvm::AliasSet::isMayAlias () const inline
Definition at line 109 of file AliasSetTracker.h.
isMod()
bool llvm::AliasSet::isMod () const inline
Definition at line 107 of file AliasSetTracker.h.
isMustAlias()
bool llvm::AliasSet::isMustAlias () const inline
Definition at line 108 of file AliasSetTracker.h.
isRef()
bool llvm::AliasSet::isRef () const inline
Accessors...
Definition at line 106 of file AliasSetTracker.h.
mergeSetIn()
void AliasSet::mergeSetIn (AliasSet & AS, AliasSetTracker & AST, BatchAAResults & BatchAA)
Merge the specified alias set into this alias set.
mergeSetIn - Merge the specified alias set into this alias set.
Definition at line 44 of file AliasSetTracker.cpp.
References llvm::any_of(), llvm::append_range(), assert(), and std::swap().
operator=()
AliasSet & llvm::AliasSet::operator= (const AliasSet &) delete
print()
void AliasSet::print (raw_ostream & OS) const
Definition at line 513 of file AliasSetTracker.cpp.
References llvm::LocationSize::afterPointer(), llvm::LocationSize::beforeOrAfterPointer(), I, llvm_unreachable, OS, llvm::Value::printAsOperand(), llvm::MemoryLocation::Ptr, and llvm::MemoryLocation::Size.
Referenced by dump(), llvm::operator<<(), and llvm::AliasSetTracker::print().
size()
unsigned llvm::AliasSet::size () const inline
Definition at line 124 of file AliasSetTracker.h.
References llvm::SmallVectorBase< Size_T >::size().
Friends And Related Symbol Documentation
AliasSetTracker
friend class AliasSetTracker friend
Definition at line 49 of file AliasSetTracker.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasSetTracker.h
lib/Analysis/AliasSetTracker.cpp