LLVM: llvm::sandboxir::PassRegistry Class Reference
llvm::sandboxir::PassRegistry Class Reference
Owns the passes and provides an API to get a pass by its name.
#include "llvm/SandboxIR/PassManager.h"
Public Member Functions
PassRegistry ()=default
Pass & registerPass (std::unique_ptr< Pass > &&PassPtr)
Registers PassPtr and takes ownership.
Pass * getPassByName (StringRef Name) const
\Returns the pass with name Name, or null if not registered.
FunctionPassManager & parseAndCreatePassPipeline (StringRef Pipeline)
Creates a pass pipeline and returns the first pass manager.
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Attributes
static constexpr const char PassDelimToken = ','
Detailed Description
Owns the passes and provides an API to get a pass by its name.
Definition at line 77 of file PassManager.h.
Constructor & Destructor Documentation
PassRegistry()
llvm::sandboxir::PassRegistry::PassRegistry () default
Member Function Documentation
dump()
void PassRegistry::dump () const
Definition at line 55 of file PassManager.cpp.
References llvm::dbgs(), and print().
getPassByName()
Pass * llvm::sandboxir::PassRegistry::getPassByName (StringRef Name) const inline
\Returns the pass with name Name, or null if not registered.
Definition at line 92 of file PassManager.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and Name.
Referenced by parseAndCreatePassPipeline().
parseAndCreatePassPipeline()
FunctionPassManager & PassRegistry::parseAndCreatePassPipeline (StringRef Pipeline)
Creates a pass pipeline and returns the first pass manager.
Definition at line 24 of file PassManager.cpp.
References llvm::CallingConv::C, llvm::enumerate(), llvm::errs(), getPassByName(), PassDelimToken, PassName, and registerPass().
Referenced by llvm::SandboxVectorizerPass::runImpl().
print()
void llvm::sandboxir::PassRegistry::print (raw_ostream & OS) const inline
Definition at line 100 of file PassManager.h.
References OS, and Passes.
Referenced by dump().
registerPass()
Pass & llvm::sandboxir::PassRegistry::registerPass (std::unique_ptr< Pass > && PassPtr) inline
Registers PassPtr and takes ownership.
Definition at line 85 of file PassManager.h.
References Passes.
Referenced by parseAndCreatePassPipeline(), and llvm::SandboxVectorizerPass::runImpl().
Member Data Documentation
PassDelimToken
const char llvm::sandboxir::PassRegistry::PassDelimToken = ',' static constexpr
Definition at line 82 of file PassManager.h.
Referenced by parseAndCreatePassPipeline().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/PassManager.h
lib/SandboxIR/PassManager.cpp