LLVM: llvm::sandboxir::Utils Class Reference
llvm::sandboxir::Utils Class Reference
#include "llvm/SandboxIR/Utils.h"
Static Public Member Functions
static Type * getExpectedType (const Value *V)
\Returns the expected type of Value V.
static Value * getExpectedValue (const Instruction *I)
\Returns the expected Value for this instruction.
static unsigned getNumBits (Value *V, const DataLayout &DL)
\Returns the number of bits required to represent the operands or return value of V in DL.
static std::optional< llvm::MemoryLocation > memoryLocationGetOrNone (const Instruction *I)
Equivalent to MemoryLocation::getOrNone(I).
template<typename LoadOrStoreT >
static std::optional< int > getPointerDiffInBytes (LoadOrStoreT *I0, LoadOrStoreT *I1, ScalarEvolution &SE, const DataLayout &DL)
\Returns the gap between the memory locations accessed by I0 and I1 in bytes.
template<typename LoadOrStoreT >
static bool atLowerAddress (LoadOrStoreT *I0, LoadOrStoreT *I1, ScalarEvolution &SE, const DataLayout &DL)
\Returns true if I0 accesses a memory location lower than I1.
Detailed Description
Definition at line 24 of file Utils.h.
Member Function Documentation
atLowerAddress()
template<typename LoadOrStoreT > static bool llvm::sandboxir::Utils::atLowerAddress (LoadOrStoreT * I0, LoadOrStoreT * I1, ScalarEvolution & SE, const DataLayout & DL) inline static
\Returns true if I0 accesses a memory location lower than I1.
Returns false if the difference cannot be determined, if the memory locations are equal, or if I1 accesses a memory location greater than I0.
Definition at line 89 of file Utils.h.
References DL, and getPointerDiffInBytes().
getExpectedType()
static Type * llvm::sandboxir::Utils::getExpectedType (const Value * V) inline static
\Returns the expected type of Value V.
For most Values this is equivalent to getType, but for stores returns the stored type, rather than void, and for ReturnInsts returns the returned type.
Definition at line 29 of file Utils.h.
References llvm::dyn_cast(), getExpectedValue(), llvm::sandboxir::Value::getType(), and I.
Referenced by getNumBits().
getExpectedValue()
static Value * llvm::sandboxir::Utils::getExpectedValue (const Instruction * I) inline static
\Returns the expected Value for this instruction.
For most instructions, this is the instruction itself, but for stores returns the stored operand, and for ReturnInstructions returns the returned value.
Definition at line 44 of file Utils.h.
References llvm::dyn_cast(), and I.
Referenced by getExpectedType().
getNumBits()
static unsigned llvm::sandboxir::Utils::getNumBits (Value * V, const DataLayout & DL) inline static
\Returns the number of bits required to represent the operands or return value of V in DL.
Definition at line 54 of file Utils.h.
References DL, and getExpectedType().
getPointerDiffInBytes()
template<typename LoadOrStoreT > static std::optional< int > llvm::sandboxir::Utils::getPointerDiffInBytes (LoadOrStoreT * I0, LoadOrStoreT * I1, ScalarEvolution & SE, const DataLayout & DL) inline static
\Returns the gap between the memory locations accessed by I0 and I1 in bytes.
Definition at line 69 of file Utils.h.
References DL, llvm::ScalarEvolution::getContext(), llvm::Type::getInt8Ty(), llvm::getPointersDiff(), and llvm::getUnderlyingObject().
Referenced by atLowerAddress().
memoryLocationGetOrNone()
static std::optional< llvm::MemoryLocation > llvm::sandboxir::Utils::memoryLocationGetOrNone (const Instruction * I) inline static
Equivalent to MemoryLocation::getOrNone(I).
Definition at line 61 of file Utils.h.
References llvm::cast(), llvm::MemoryLocation::getOrNone(), and I.
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Utils.h