LLVM: llvm::RecordKeeper Class Reference
llvm::RecordKeeper Class Reference
#include "llvm/TableGen/Record.h"
Public Member Functions
RecordKeeper ()
~RecordKeeper ()
detail::RecordKeeperImpl & getImpl ()
Return the internal implementation of the RecordKeeper.
const std::string getInputFilename () const
Get the main TableGen input file's name.
const RecordMap & getClasses () const
Get the map of classes.
const RecordMap & getDefs () const
Get the map of records (defs).
const GlobalMap & getGlobals () const
Get the map of global variables.
Record * getClass (StringRef Name) const
Get the class with the specified name.
Record * getDef (StringRef Name) const
Get the concrete record with the specified name.
Init * getGlobal (StringRef Name) const
Get the Init value of the specified global variable.
void saveInputFilename (std::string Filename)
void addClass (std::unique_ptr< Record > R)
void addDef (std::unique_ptr< Record > R)
void addExtraGlobal (StringRef Name, Init *I)
Init * getNewAnonymousName ()
GetNewAnonymousName - Generate a unique anonymous name that can be used as an identifier.
void startPhaseTiming ()
Start phase timing; called if the –time-phases option is specified.
void startTimer (StringRef Name) const
Start timing a phase. Automatically stops any previous phase timer.
void stopTimer ()
Stop timing a phase.
void startBackendTimer (StringRef Name)
Start timing the overall backend.
void stopBackendTimer ()
Stop timing the overall backend.
void stopPhaseTiming ()
Stop phase timing and print the report.
ArrayRef< const Record * > getAllDerivedDefinitions (StringRef ClassName) const
Get all the concrete records that inherit from the one specified class.
const std::vector< Record * > & getAllDerivedDefinitions (StringRef ClassName)
std::vector< const Record * > getAllDerivedDefinitions (ArrayRef< StringRef > ClassNames) const
Get all the concrete records that inherit from all the specified classes.
std::vector< Record * > getAllDerivedDefinitions (ArrayRef< StringRef > ClassNames)
ArrayRef< const Record * > getAllDerivedDefinitionsIfDefined (StringRef ClassName) const
Get all the concrete records that inherit from specified class, if the class is defined.
const std::vector< Record * > & getAllDerivedDefinitionsIfDefined (StringRef ClassName)
void dump () const
void dumpAllocationStats (raw_ostream &OS) const
Detailed Description
Definition at line 1965 of file Record.h.
Constructor & Destructor Documentation
RecordKeeper()
RecordKeeper::RecordKeeper ()
Definition at line 3228 of file Record.cpp.
~RecordKeeper()
RecordKeeper::~RecordKeeper () default
Member Function Documentation
addClass()
void llvm::RecordKeeper::addClass (std::unique_ptr< Record > R) inline
Definition at line 2012 of file Record.h.
References assert().
addDef()
void llvm::RecordKeeper::addDef (std::unique_ptr< Record > R) inline
Definition at line 2019 of file Record.h.
References assert().
addExtraGlobal()
void llvm::RecordKeeper::addExtraGlobal (StringRef Name, Init * I) inline
Definition at line 2026 of file Record.h.
References assert(), getDef(), I, and Name.
dump()
LLVM_DUMP_METHOD void RecordKeeper::dump () const
Definition at line 3233 of file Record.cpp.
References llvm::errs().
dumpAllocationStats()
void RecordKeeper::dumpAllocationStats (raw_ostream & OS) const
Definition at line 3373 of file Record.cpp.
References OS.
getAllDerivedDefinitions() [1/4]
std::vector< Record * > RecordKeeper::getAllDerivedDefinitions (ArrayRef< StringRef > ClassNames)
Definition at line 3357 of file Record.cpp.
getAllDerivedDefinitions() [2/4]
std::vector< const Record * > RecordKeeper::getAllDerivedDefinitions (ArrayRef< StringRef > ClassNames) const
Get all the concrete records that inherit from all the specified classes.
The classes must be defined.
Definition at line 3352 of file Record.cpp.
getAllDerivedDefinitions() [3/4]
const std::vector< Record * > & RecordKeeper::getAllDerivedDefinitions (StringRef ClassName)
Definition at line 3346 of file Record.cpp.
getAllDerivedDefinitions() [4/4]
ArrayRef< const Record * > RecordKeeper::getAllDerivedDefinitions (StringRef ClassName) const
Get all the concrete records that inherit from the one specified class.
The class must be defined.
Definition at line 3340 of file Record.cpp.
Referenced by llvm::DirectiveLanguage::getAssociations(), llvm::DirectiveLanguage::getCategories(), llvm::DirectiveLanguage::getClauses(), and llvm::DirectiveLanguage::getDirectives().
getAllDerivedDefinitionsIfDefined() [1/2]
const std::vector< Record * > & RecordKeeper::getAllDerivedDefinitionsIfDefined (StringRef ClassName)
Definition at line 3368 of file Record.cpp.
getAllDerivedDefinitionsIfDefined() [2/2]
ArrayRef< const Record * > RecordKeeper::getAllDerivedDefinitionsIfDefined (StringRef ClassName) const
Get all the concrete records that inherit from specified class, if the class is defined.
Returns an empty vector if the class is not defined.
Definition at line 3362 of file Record.cpp.
getClass()
Record * llvm::RecordKeeper::getClass (StringRef Name) const inline
Get the class with the specified name.
Definition at line 1989 of file Record.h.
References I, and Name.
getClasses()
const RecordMap & llvm::RecordKeeper::getClasses () const inline
Get the map of classes.
Definition at line 1980 of file Record.h.
Referenced by llvm::operator<<().
getDef()
Record * llvm::RecordKeeper::getDef (StringRef Name) const inline
Get the concrete record with the specified name.
Definition at line 1995 of file Record.h.
References I, and Name.
Referenced by addExtraGlobal(), llvm::ExistsOpInit::Fold(), llvm::UnOpInit::Fold(), and getGlobal().
getDefs()
const RecordMap & llvm::RecordKeeper::getDefs () const inline
Get the map of records (defs).
Definition at line 1983 of file Record.h.
Referenced by llvm::operator<<().
getGlobal()
Init * llvm::RecordKeeper::getGlobal (StringRef Name) const inline
Get the Init value of the specified global variable.
Definition at line 2001 of file Record.h.
References getDef(), and Name.
getGlobals()
const GlobalMap & llvm::RecordKeeper::getGlobals () const inline
Get the map of global variables.
Definition at line 1986 of file Record.h.
getImpl()
detail::RecordKeeperImpl & llvm::RecordKeeper::getImpl () inline
Return the internal implementation of the RecordKeeper.
Definition at line 1974 of file Record.h.
Referenced by llvm::AnonymousNameInit::get(), llvm::ArgumentInit::get(), llvm::BitInit::get(), llvm::BitRecTy::get(), llvm::BitsInit::get(), llvm::BitsRecTy::get(), llvm::DagRecTy::get(), llvm::ExistsOpInit::get(), llvm::IntInit::get(), llvm::IntRecTy::get(), llvm::IsAOpInit::get(), llvm::ListInit::get(), llvm::RecordRecTy::get(), llvm::StringInit::get(), llvm::StringRecTy::get(), llvm::UnsetInit::get(), llvm::Record::getDefInit(), llvm::RecTy::getListTy(), getNewAnonymousName(), and llvm::Record::getNewUID().
getInputFilename()
const std::string llvm::RecordKeeper::getInputFilename () const inline
Get the main TableGen input file's name.
Definition at line 1977 of file Record.h.
getNewAnonymousName()
Init * RecordKeeper::getNewAnonymousName ()
GetNewAnonymousName - Generate a unique anonymous name that can be used as an identifier.
Definition at line 3249 of file Record.cpp.
References llvm::AnonymousNameInit::get(), and getImpl().
saveInputFilename()
void llvm::RecordKeeper::saveInputFilename (std::string Filename) inline
Definition at line 2008 of file Record.h.
startBackendTimer()
void RecordKeeper::startBackendTimer (StringRef Name)
Start timing the overall backend.
If the backend itself starts a timer, then this timer is cleared.
Definition at line 3278 of file Record.cpp.
References Name, and startTimer().
startPhaseTiming()
void llvm::RecordKeeper::startPhaseTiming () inline
Start phase timing; called if the –time-phases option is specified.
Definition at line 2036 of file Record.h.
startTimer()
void RecordKeeper::startTimer (StringRef Name) const
Start timing a phase. Automatically stops any previous phase timer.
Definition at line 3256 of file Record.cpp.
References llvm::Timer::clear(), llvm::Timer::isRunning(), Name, llvm::Timer::startTimer(), and llvm::Timer::stopTimer().
Referenced by startBackendTimer().
stopBackendTimer()
void RecordKeeper::stopBackendTimer ()
Stop timing the overall backend.
Definition at line 3285 of file Record.cpp.
References stopTimer().
stopPhaseTiming()
void llvm::RecordKeeper::stopPhaseTiming () inline
Stop phase timing and print the report.
Definition at line 2054 of file Record.h.
stopTimer()
void RecordKeeper::stopTimer ()
Stop timing a phase.
Definition at line 3271 of file Record.cpp.
References assert(), and llvm::Timer::stopTimer().
Referenced by stopBackendTimer().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp