LLVM: llvm::CrashRecoveryContextCleanup Class Reference
llvm::CrashRecoveryContextCleanup Class Reference abstract
Abstract base class of cleanup handlers.
#include "llvm/Support/CrashRecoveryContext.h"
Public Member Functions
virtual ~CrashRecoveryContextCleanup ()
virtual void recoverResources ()=0
CrashRecoveryContext * getContext () const
Public Attributes
bool cleanupFired = false
Protected Member Functions
CrashRecoveryContextCleanup (CrashRecoveryContext *context)
Protected Attributes
CrashRecoveryContext * context = nullptr
Friends
class CrashRecoveryContext
Detailed Description
Abstract base class of cleanup handlers.
Derived classes override method recoverResources, which makes actual work on resource recovery.
Cleanup handlers are stored in a double list, which is owned and managed by a crash recovery context.
Definition at line 127 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContextCleanup()
llvm::CrashRecoveryContextCleanup::CrashRecoveryContextCleanup (CrashRecoveryContext * context) inline protected
Definition at line 130 of file CrashRecoveryContext.h.
~CrashRecoveryContextCleanup()
CrashRecoveryContextCleanup::~CrashRecoveryContextCleanup () virtual default
Member Function Documentation
getContext()
CrashRecoveryContext * llvm::CrashRecoveryContextCleanup::getContext () const inline
Definition at line 139 of file CrashRecoveryContext.h.
References context.
Referenced by llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::CrashRecoveryContextCleanupRegistrar(), and llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::unregister().
recoverResources()
virtual void llvm::CrashRecoveryContextCleanup::recoverResources () pure virtual
Implemented in llvm::CrashRecoveryContextDeleteCleanup< T >, llvm::CrashRecoveryContextDestructorCleanup< T >, and llvm::CrashRecoveryContextReleaseRefCleanup< T >.
Referenced by llvm::CrashRecoveryContext::~CrashRecoveryContext().
Friends And Related Symbol Documentation
CrashRecoveryContext
friend class CrashRecoveryContext friend
Definition at line 144 of file CrashRecoveryContext.h.
Member Data Documentation
cleanupFired
bool llvm::CrashRecoveryContextCleanup::cleanupFired = false
Definition at line 134 of file CrashRecoveryContext.h.
Referenced by llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::unregister(), and llvm::CrashRecoveryContext::~CrashRecoveryContext().
context
CrashRecoveryContext* llvm::CrashRecoveryContextCleanup::context = nullptr protected
Definition at line 129 of file CrashRecoveryContext.h.
Referenced by llvm::CrashRecoveryContextCleanupBase< Derived, T >::create(), and getContext().
The documentation for this class was generated from the following files:
include/llvm/Support/CrashRecoveryContext.h
lib/Support/CrashRecoveryContext.cpp