LLVM: llvm::ilist_base< EnableSentinelTracking, ParentTy > Class Template Reference
llvm::ilist_base< EnableSentinelTracking, ParentTy > Class Template Reference
Implementations of list algorithms using ilist_node_base.
#include "llvm/ADT/ilist_base.h"
Public Types
using node_base_type = ilist_node_base<EnableSentinelTracking, ParentTy>
Static Public Member Functions
static void insertBeforeImpl (node_base_type &Next, node_base_type &N)
static void removeImpl (node_base_type &N)
static void removeRangeImpl (node_base_type &First, node_base_type &Last)
static void transferBeforeImpl (node_base_type &Next, node_base_type &First, node_base_type &Last)
template<class T >
static void insertBefore (T &Next, T &N)
template<class T >
static void remove (T &N)
template<class T >
static void removeRange (T &First, T &Last)
template<class T >
static void transferBefore (T &Next, T &First, T &Last)
Detailed Description
template<bool EnableSentinelTracking, class ParentTy>
class llvm::ilist_base< EnableSentinelTracking, ParentTy >
Implementations of list algorithms using ilist_node_base.
Definition at line 19 of file ilist_node_options.h.
Member Typedef Documentation
node_base_type
template<bool EnableSentinelTracking, class ParentTy > using llvm::ilist_base< EnableSentinelTracking, ParentTy >::node_base_type = ilist_node_base<EnableSentinelTracking, ParentTy>
Definition at line 20 of file ilist_base.h.
Member Function Documentation
insertBefore()
template<bool EnableSentinelTracking, class ParentTy > template<class T > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::insertBefore (T & Next, T & N) inline static
Definition at line 76 of file ilist_base.h.
References llvm::ilist_base< EnableSentinelTracking, ParentTy >::insertBeforeImpl(), N, and llvm::Next.
insertBeforeImpl()
template<bool EnableSentinelTracking, class ParentTy > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::insertBeforeImpl (node_base_type & Next, node_base_type & N) inline static
Definition at line 22 of file ilist_base.h.
References N, and llvm::Next.
Referenced by llvm::ilist_base< EnableSentinelTracking, ParentTy >::insertBefore().
remove()
template<bool EnableSentinelTracking, class ParentTy > template<class T > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::remove (T & N) inline static
Definition at line 80 of file ilist_base.h.
References N, and llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeImpl().
removeImpl()
template<bool EnableSentinelTracking, class ParentTy > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeImpl (node_base_type & N) inline static
Definition at line 30 of file ilist_base.h.
References N, and llvm::Next.
Referenced by llvm::ilist_base< EnableSentinelTracking, ParentTy >::remove().
removeRange()
template<bool EnableSentinelTracking, class ParentTy > template<class T > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeRange (T & First, T & Last) inline static
Definition at line 81 of file ilist_base.h.
References llvm::First, llvm::Last, and llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeRangeImpl().
removeRangeImpl()
template<bool EnableSentinelTracking, class ParentTy > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeRangeImpl (node_base_type & First, node_base_type & Last) inline static
Definition at line 41 of file ilist_base.h.
References llvm::First, and llvm::Last.
Referenced by llvm::ilist_base< EnableSentinelTracking, ParentTy >::removeRange().
transferBefore()
template<bool EnableSentinelTracking, class ParentTy > template<class T > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::transferBefore (T & Next, T & First, T & Last) inline static
Definition at line 85 of file ilist_base.h.
References llvm::First, llvm::Last, llvm::Next, and llvm::ilist_base< EnableSentinelTracking, ParentTy >::transferBeforeImpl().
transferBeforeImpl()
template<bool EnableSentinelTracking, class ParentTy > static void llvm::ilist_base< EnableSentinelTracking, ParentTy >::transferBeforeImpl (node_base_type & Next, node_base_type & First, node_base_type & Last) inline static
Definition at line 52 of file ilist_base.h.
References assert(), llvm::First, llvm::Last, and llvm::Next.
Referenced by llvm::ilist_base< EnableSentinelTracking, ParentTy >::transferBefore().
The documentation for this class was generated from the following files:
include/llvm/ADT/ilist_base.h
include/llvm/ADT/ilist_node_options.h