LLVM: llvm::sandboxir::SwitchRemoveCase Class Reference
llvm::sandboxir::SwitchRemoveCase Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
SwitchRemoveCase (SwitchInst *Switch, ConstantInt *Val, BasicBlock *Dest)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 316 of file Tracker.h.
Constructor & Destructor Documentation
SwitchRemoveCase()
llvm::sandboxir::SwitchRemoveCase::SwitchRemoveCase (SwitchInst * Switch, ConstantInt * Val, BasicBlock * Dest) inline
Definition at line 322 of file Tracker.h.
Member Function Documentation
accept()
void llvm::sandboxir::SwitchRemoveCase::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 325 of file Tracker.h.
dump() [1/2]
void SwitchRemoveCase::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 176 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::SwitchRemoveCase::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 327 of file Tracker.h.
References OS.
revert()
void SwitchRemoveCase::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 173 of file Tracker.cpp.
References llvm::sandboxir::SwitchInst::addCase().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp