LLVM: llvm::TargetTransformInfoImplBase Class Reference
llvm::TargetTransformInfoImplBase Class Reference
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include "llvm/Analysis/TargetTransformInfoImpl.h"
Public Member Functions
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
unsigned getInliningThresholdMultiplier () const
unsigned getInliningCostBenefitAnalysisSavingsMultiplier () const
unsigned getInliningCostBenefitAnalysisProfitableMultiplier () const
unsigned adjustInliningThreshold (const CallBase *CB) const
unsigned getCallerAllocaCost (const CallBase *CB, const AllocaInst *AI) const
int getInlinerVectorBonusPercent () const
InstructionCost getMemcpyCost (const Instruction *I) const
uint64_t getMaxMemIntrinsicInlineSizeThreshold () const
BranchProbability getPredictableBranchThreshold () const
InstructionCost getBranchMispredictPenalty () const
bool hasBranchDivergence (const Function *F=nullptr) const
bool isSourceOfDivergence (const Value *V) const
bool isAlwaysUniform (const Value *V) const
bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
bool addrspacesMayAlias (unsigned AS0, unsigned AS1) const
unsigned getFlatAddressSpace () const
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned, unsigned) const
bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
unsigned getAssumedAddrSpace (const Value *V) const
bool isSingleThreaded () const
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F) const
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
bool preferPredicateOverEpilogue (TailFoldingInfo *TFI) const
TailFoldingStyle getPreferredTailFoldingStyle (bool IVUpdateMayOverflow=true) const
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &, OptimizationRemarkEmitter *) const
void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
bool isLegalAddImmediate (int64_t Imm) const
bool isLegalAddScalableImmediate (int64_t Imm) const
bool isLegalICmpImmediate (int64_t Imm) const
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr, int64_t ScalableOffset=0) const
bool isLSRCostLess (const TTI::LSRCost &C1, const TTI::LSRCost &C2) const
bool isNumRegsMajorCostOfLSR () const
bool shouldDropLSRSolutionIfLessProfitable () const
bool isProfitableLSRChainElement (Instruction *I) const
bool canMacroFuseCmp () const
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
bool isLegalMaskedStore (Type *DataType, Align Alignment) const
bool isLegalMaskedLoad (Type *DataType, Align Alignment) const
bool isLegalNTStore (Type *DataType, Align Alignment) const
bool isLegalNTLoad (Type *DataType, Align Alignment) const
bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const
bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
bool isLegalMaskedCompressStore (Type *DataType, Align Alignment) const
bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
bool isLegalMaskedExpandLoad (Type *DataType, Align Alignment) const
bool isLegalStridedLoadStore (Type *DataType, Align Alignment) const
bool isLegalMaskedVectorHistogram (Type *AddrType, Type *DataType) const
bool enableOrderedReductions () const
bool hasDivRemOp (Type *DataType, bool IsSigned) const
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
bool prefersVectorizedAddressing () const
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
bool LSRWithInstrQueries () const
bool isTruncateFree (Type *Ty1, Type *Ty2) const
bool isProfitableToHoist (Instruction *I) const
bool useAA () const
bool isTypeLegal (Type *Ty) const
unsigned getRegUsageForType (Type *Ty) const
bool shouldBuildLookupTables () const
bool shouldBuildLookupTablesForConstant (Constant *C) const
bool shouldBuildRelLookupTables () const
bool useColdCCForColdCall (Function &F) const
bool isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
bool supportsEfficientVectorElementLoadStore () const
bool supportsTailCalls () const
bool enableAggressiveInterleaving (bool LoopHasReductions) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableSelectOptimize () const
bool shouldTreatInstructionLikeSelect (const Instruction *I)
bool enableInterleavedAccessVectorization () const
bool enableMaskedInterleavedAccessVectorization () const
bool isFPVectorizationPotentiallyUnsafe () const
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
bool haveFastSqrt (Type *Ty) const
bool isExpensiveToSpeculativelyExecute (const Instruction *I)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
InstructionCost getFPOpCost (Type *Ty) const
InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
bool preferToKeepConstantsAttached (const Instruction &Inst, const Function &Fn) const
unsigned getNumberOfRegisters (unsigned ClassID) const
bool hasConditionalLoadStoreForType (Type *Ty) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getMinVectorRegisterBitWidth () const
std::optional< unsigned > getMaxVScale () const
std::optional< unsigned > getVScaleForTuning () const
bool isVScaleKnownToBeAPowerOfTwo () const
bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
unsigned getStoreMinimumVF (unsigned VF, Type *, Type *) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
unsigned getCacheLineSize () const
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
std::optional< unsigned > getMinPageSize () const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
unsigned getMaxPrefetchIterationsAhead () const
bool enableWritePrefetching () const
bool shouldPrefetchAddressSpace (unsigned AS) const
unsigned getMaxInterleaveFactor (ElementCount VF) const
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
InstructionCost getAltInstrCost (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask, TTI::TargetCostKind CostKind) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Ty, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index) const
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info, TTI::OperandValueInfo Op2Info, const Instruction *I) const
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Op0, Value *Op1) const
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const
unsigned getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction *I) const
InstructionCost getVPMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
InstructionCost getStridedMemoryOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
unsigned getNumberOfParts (Type *Tp) const
InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
InstructionCost getArithmeticReductionCost (unsigned, VectorType *, std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const
InstructionCost getMinMaxReductionCost (Intrinsic::ID IID, VectorType *, FastMathFlags, TTI::TargetCostKind) const
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const
InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) const
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
unsigned getInlineCallPenalty (const Function *F, const CallBase &Call, unsigned DefaultCallPenalty) const
bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Types) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
bool isElementTypeLegalForScalableVector (Type *Ty) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool preferFixedOverScalableIfEqualCost () const
bool preferInLoopReduction (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferPredicatedReductionSelect (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferEpilogueVectorization () const
bool shouldExpandReduction (const IntrinsicInst *II) const
TTI::ReductionShuffle getPreferredExpandedReductionShuffle (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
unsigned getMinTripCountTailFoldingThreshold () const
bool supportsScalableVectors () const
bool enableScalableVectorization () const
bool hasActiveVectorLength (unsigned Opcode, Type *DataType, Align Alignment) const
TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
bool hasArmWideBranch (bool) const
unsigned getMaxNumArgs () const
Protected Types
typedef TargetTransformInfo TTI
Protected Member Functions
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes
const DataLayout & DL
Detailed Description
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 34 of file TargetTransformInfoImpl.h.
Member Typedef Documentation
TTI
TargetTransformInfo llvm::TargetTransformInfoImplBase::TTI protected
Definition at line 37 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
TargetTransformInfoImplBase() [1/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const DataLayout & DL) inline explicit protected
Definition at line 41 of file TargetTransformInfoImpl.h.
TargetTransformInfoImplBase() [2/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const TargetTransformInfoImplBase & Arg) default
TargetTransformInfoImplBase() [3/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (TargetTransformInfoImplBase && Arg) inline
Definition at line 46 of file TargetTransformInfoImpl.h.
Member Function Documentation
addrspacesMayAlias()
bool llvm::TargetTransformInfoImplBase::addrspacesMayAlias (unsigned AS0, unsigned AS1) const inline
Definition at line 114 of file TargetTransformInfoImpl.h.
adjustInliningThreshold()
unsigned llvm::TargetTransformInfoImplBase::adjustInliningThreshold (const CallBase * CB) const inline
Definition at line 77 of file TargetTransformInfoImpl.h.
allowsMisalignedMemoryAccesses()
bool llvm::TargetTransformInfoImplBase::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned * Fast) const inline
Definition at line 424 of file TargetTransformInfoImpl.h.
areInlineCompatible()
bool llvm::TargetTransformInfoImplBase::areInlineCompatible (const Function * Caller, const Function * Callee) const inline
Definition at line 869 of file TargetTransformInfoImpl.h.
areTypesABICompatible()
bool llvm::TargetTransformInfoImplBase::areTypesABICompatible (const Function * Caller, const Function * Callee, const ArrayRef< Type * > & Types) const inline
Definition at line 882 of file TargetTransformInfoImpl.h.
Referenced by llvm::AArch64TTIImpl::areTypesABICompatible(), llvm::PPCTTIImpl::areTypesABICompatible(), and llvm::X86TTIImpl::areTypesABICompatible().
canHaveNonUndefGlobalInitializerInAddressSpace()
bool llvm::TargetTransformInfoImplBase::canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const inline
Definition at line 126 of file TargetTransformInfoImpl.h.
canMacroFuseCmp()
bool llvm::TargetTransformInfoImplBase::canMacroFuseCmp () const inline
Definition at line 257 of file TargetTransformInfoImpl.h.
canSaveCmp()
bool llvm::TargetTransformInfoImplBase::canSaveCmp (Loop * L, BranchInst ** BI, ScalarEvolution * SE, LoopInfo * LI, DominatorTree * DT, AssumptionCache * AC, TargetLibraryInfo * LibInfo) const inline
Definition at line 259 of file TargetTransformInfoImpl.h.
collectFlatAddressOperands()
bool llvm::TargetTransformInfoImplBase::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline
Definition at line 120 of file TargetTransformInfoImpl.h.
enableAggressiveInterleaving()
bool llvm::TargetTransformInfoImplBase::enableAggressiveInterleaving (bool LoopHasReductions) const inline
Definition at line 398 of file TargetTransformInfoImpl.h.
enableInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableInterleavedAccessVectorization () const inline
Definition at line 418 of file TargetTransformInfoImpl.h.
enableMaskedInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableMaskedInterleavedAccessVectorization () const inline
Definition at line 420 of file TargetTransformInfoImpl.h.
enableMemCmpExpansion()
TTI::MemCmpExpansionOptions llvm::TargetTransformInfoImplBase::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const inline
Definition at line 402 of file TargetTransformInfoImpl.h.
enableOrderedReductions()
bool llvm::TargetTransformInfoImplBase::enableOrderedReductions () const inline
Definition at line 334 of file TargetTransformInfoImpl.h.
enableScalableVectorization()
bool llvm::TargetTransformInfoImplBase::enableScalableVectorization () const inline
Definition at line 964 of file TargetTransformInfoImpl.h.
enableSelectOptimize()
bool llvm::TargetTransformInfoImplBase::enableSelectOptimize () const inline
Definition at line 407 of file TargetTransformInfoImpl.h.
enableWritePrefetching()
bool llvm::TargetTransformInfoImplBase::enableWritePrefetching () const inline
Definition at line 551 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedGather()
bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedGather (VectorType * DataType, Align Alignment) const inline
Definition at line 304 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedScatter()
bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedScatter (VectorType * DataType, Align Alignment) const inline
Definition at line 308 of file TargetTransformInfoImpl.h.
getAddressComputationCost()
InstructionCost llvm::TargetTransformInfoImplBase::getAddressComputationCost (Type * Tp, ScalarEvolution * , const SCEV *) const inline
Definition at line 797 of file TargetTransformInfoImpl.h.
getAltInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getAltInstrCost (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask, TTI::TargetCostKind CostKind) const inline
Definition at line 597 of file TargetTransformInfoImpl.h.
References llvm::InstructionCost::getInvalid().
getArithmeticInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction * CxtI = nullptr) const inline
Definition at line 556 of file TargetTransformInfoImpl.h.
References llvm::any_of(), CostKind, llvm::dyn_cast(), II, llvm::TargetTransformInfo::TCC_Expensive, llvm::TargetTransformInfo::TCC_Free, and llvm::TargetTransformInfo::TCK_Latency.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::getPointersChainCost().
getArithmeticReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticReductionCost (unsigned , VectorType * , std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const inline
Definition at line 802 of file TargetTransformInfoImpl.h.
getAssumedAddrSpace()
unsigned llvm::TargetTransformInfoImplBase::getAssumedAddrSpace (const Value * V) const inline
Definition at line 130 of file TargetTransformInfoImpl.h.
getAtomicMemIntrinsicMaxElementSize()
unsigned llvm::TargetTransformInfoImplBase::getAtomicMemIntrinsicMaxElementSize () const inline
Definition at line 835 of file TargetTransformInfoImpl.h.
getBranchMispredictPenalty()
InstructionCost llvm::TargetTransformInfoImplBase::getBranchMispredictPenalty () const inline
Definition at line 102 of file TargetTransformInfoImpl.h.
getCacheAssociativity()
std::optional< unsigned > llvm::TargetTransformInfoImplBase::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 531 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
Referenced by llvm::BasicTTIImplBase< T >::getCacheAssociativity().
getCacheLineSize()
unsigned llvm::TargetTransformInfoImplBase::getCacheLineSize () const inline
Definition at line 518 of file TargetTransformInfoImpl.h.
getCacheSize()
std::optional< unsigned > llvm::TargetTransformInfoImplBase::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 520 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCallerAllocaCost()
unsigned llvm::TargetTransformInfoImplBase::getCallerAllocaCost (const CallBase * CB, const AllocaInst * AI) const inline
Definition at line 78 of file TargetTransformInfoImpl.h.
getCallInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline
Definition at line 788 of file TargetTransformInfoImpl.h.
getCastInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I) const inline
Definition at line 613 of file TargetTransformInfoImpl.h.
References DL, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::DataLayout::isLegalInteger(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by llvm::BasicTTIImplBase< T >::getCastInstrCost().
getCFInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline
Definition at line 657 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by llvm::BasicTTIImplBase< T >::getCFInstrCost().
getCmpSelInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info, TTI::OperandValueInfo Op2Info, const Instruction * I) const inline
Definition at line 666 of file TargetTransformInfoImpl.h.
getConstantStrideStep()
const SCEVConstant * llvm::TargetTransformInfoImplBase::getConstantStrideStep (ScalarEvolution * SE, const SCEV * Ptr) const inline protected
Definition at line 1043 of file TargetTransformInfoImpl.h.
References llvm::cast(), llvm::dyn_cast(), llvm::SCEVAddRecExpr::getStepRecurrence(), isStridedAccess(), and Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and isConstantStridedAccessLessThan().
getCostOfKeepingLiveOverCall()
InstructionCost llvm::TargetTransformInfoImplBase::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const inline
Definition at line 827 of file TargetTransformInfoImpl.h.
getDataLayout()
const DataLayout & llvm::TargetTransformInfoImplBase::getDataLayout () const inline
Definition at line 48 of file TargetTransformInfoImpl.h.
References DL.
Referenced by adjustInliningThresholdUsingCallee(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters(), llvm::HexagonTTIImpl::getInstructionCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCostInst(), and llvm::RISCVTTIImpl::getMemoryOpCost().
getEstimatedNumberOfCaseClusters()
unsigned llvm::TargetTransformInfoImplBase::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JTSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) const inline
Definition at line 62 of file TargetTransformInfoImpl.h.
getExtendedReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type * ResTy, VectorType * Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const inline
Definition at line 814 of file TargetTransformInfoImpl.h.
getExtractWithExtendCost()
InstructionCost llvm::TargetTransformInfoImplBase::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index) const inline
Definition at line 651 of file TargetTransformInfoImpl.h.
getFlatAddressSpace()
unsigned llvm::TargetTransformInfoImplBase::getFlatAddressSpace () const inline
Definition at line 118 of file TargetTransformInfoImpl.h.
getFPOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getFPOpCost (Type * Ty) const inline
Definition at line 440 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
getGatherScatterOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline
Definition at line 715 of file TargetTransformInfoImpl.h.
getGEPCost()
InstructionCost llvm::TargetTransformInfoImplBase::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands, Type * AccessType, TTI::TargetCostKind CostKind) const inline
Definition at line 50 of file TargetTransformInfoImpl.h.
References llvm::isa(), Operands, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
getGISelRematGlobalCost()
unsigned llvm::TargetTransformInfoImplBase::getGISelRematGlobalCost () const inline
Definition at line 958 of file TargetTransformInfoImpl.h.
getInlineCallPenalty()
unsigned llvm::TargetTransformInfoImplBase::getInlineCallPenalty (const Function * F, const CallBase & Call, unsigned DefaultCallPenalty) const inline
Definition at line 877 of file TargetTransformInfoImpl.h.
getInlinerVectorBonusPercent()
int llvm::TargetTransformInfoImplBase::getInlinerVectorBonusPercent () const inline
Definition at line 82 of file TargetTransformInfoImpl.h.
getInliningCostBenefitAnalysisProfitableMultiplier()
unsigned llvm::TargetTransformInfoImplBase::getInliningCostBenefitAnalysisProfitableMultiplier () const inline
Definition at line 74 of file TargetTransformInfoImpl.h.
getInliningCostBenefitAnalysisSavingsMultiplier()
unsigned llvm::TargetTransformInfoImplBase::getInliningCostBenefitAnalysisSavingsMultiplier () const inline
Definition at line 73 of file TargetTransformInfoImpl.h.
getInliningThresholdMultiplier()
unsigned llvm::TargetTransformInfoImplBase::getInliningThresholdMultiplier () const inline
Definition at line 72 of file TargetTransformInfoImpl.h.
getInterleavedMemoryOpCost()
unsigned llvm::TargetTransformInfoImplBase::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const inline
Definition at line 731 of file TargetTransformInfoImpl.h.
getIntImmCodeSizeCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) const inline
Definition at line 444 of file TargetTransformInfoImpl.h.
getIntImmCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 449 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::PPCTTIImpl::getIntImmCost().
getIntImmCostInst()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr) const inline
Definition at line 454 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostInst().
getIntImmCostIntrin()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 461 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostIntrin().
getIntrinsicInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const inline
Definition at line 738 of file TargetTransformInfoImpl.h.
References llvm::IntrinsicCostAttributes::getID(), and llvm::InstructionCost::getInvalid().
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost().
getLoadStoreVecRegBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getLoadStoreVecRegBitWidth (unsigned AddrSpace) const inline
Definition at line 900 of file TargetTransformInfoImpl.h.
getLoadVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 923 of file TargetTransformInfoImpl.h.
getMaskedMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const inline
Definition at line 709 of file TargetTransformInfoImpl.h.
getMaximumVF()
unsigned llvm::TargetTransformInfoImplBase::getMaximumVF (unsigned ElemWidth, unsigned Opcode) const inline
Definition at line 509 of file TargetTransformInfoImpl.h.
getMaxInterleaveFactor()
unsigned llvm::TargetTransformInfoImplBase::getMaxInterleaveFactor (ElementCount VF) const inline
Definition at line 554 of file TargetTransformInfoImpl.h.
getMaxMemIntrinsicInlineSizeThreshold()
uint64_t llvm::TargetTransformInfoImplBase::getMaxMemIntrinsicInlineSizeThreshold () const inline
Definition at line 88 of file TargetTransformInfoImpl.h.
getMaxNumArgs()
unsigned llvm::TargetTransformInfoImplBase::getMaxNumArgs () const inline
Definition at line 980 of file TargetTransformInfoImpl.h.
getMaxPrefetchIterationsAhead()
unsigned llvm::TargetTransformInfoImplBase::getMaxPrefetchIterationsAhead () const inline
Definition at line 550 of file TargetTransformInfoImpl.h.
getMaxVScale()
std::optional< unsigned > llvm::TargetTransformInfoImplBase::getMaxVScale () const inline
Definition at line 496 of file TargetTransformInfoImpl.h.
getMemcpyCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMemcpyCost (const Instruction * I) const inline
Definition at line 84 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Expensive.
getMemcpyLoopLoweringType()
Type * llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType (LLVMContext & Context, Value * Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const inline
Definition at line 850 of file TargetTransformInfoImpl.h.
References llvm::Type::getInt8Ty(), and llvm::Type::getIntNTy().
getMemcpyLoopResidualLoweringType()
void llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > & OpsOut, LLVMContext & Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const inline
Definition at line 858 of file TargetTransformInfoImpl.h.
References llvm::Type::getIntNTy(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType().
getMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction * I) const inline
Definition at line 694 of file TargetTransformInfoImpl.h.
getMinimumVF()
ElementCount llvm::TargetTransformInfoImplBase::getMinimumVF (unsigned ElemWidth, bool IsScalable) const inline
Definition at line 505 of file TargetTransformInfoImpl.h.
References llvm::ElementCount::get().
getMinMaxReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMinMaxReductionCost (Intrinsic::ID IID, VectorType * , FastMathFlags , TTI::TargetCostKind) const inline
Definition at line 808 of file TargetTransformInfoImpl.h.
getMinPageSize()
std::optional< unsigned > llvm::TargetTransformInfoImplBase::getMinPageSize () const inline
Definition at line 542 of file TargetTransformInfoImpl.h.
getMinPrefetchStride()
unsigned llvm::TargetTransformInfoImplBase::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline
Definition at line 545 of file TargetTransformInfoImpl.h.
getMinTripCountTailFoldingThreshold()
unsigned llvm::TargetTransformInfoImplBase::getMinTripCountTailFoldingThreshold () const inline
Definition at line 960 of file TargetTransformInfoImpl.h.
getMinVectorRegisterBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getMinVectorRegisterBitWidth () const inline
Definition at line 494 of file TargetTransformInfoImpl.h.
getMulAccReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMulAccReductionCost (bool IsUnsigned, Type * ResTy, VectorType * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 821 of file TargetTransformInfoImpl.h.
getNumberOfParts()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfParts (Type * Tp) const inline
Definition at line 795 of file TargetTransformInfoImpl.h.
getNumberOfRegisters()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfRegisters (unsigned ClassID) const inline
Definition at line 472 of file TargetTransformInfoImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getNumberOfRegisters().
getOperandsScalarizationOverhead()
InstructionCost llvm::TargetTransformInfoImplBase::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline
Definition at line 388 of file TargetTransformInfoImpl.h.
getOrCreateResultFromMemIntrinsic()
Value * llvm::TargetTransformInfoImplBase::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType) const inline
Definition at line 844 of file TargetTransformInfoImpl.h.
getPeelingPreferences()
void llvm::TargetTransformInfoImplBase::getPeelingPreferences (Loop * , ScalarEvolution & , TTI::PeelingPreferences &) const inline
Definition at line 226 of file TargetTransformInfoImpl.h.
getPopcntSupport()
TTI::PopcntSupportKind llvm::TargetTransformInfoImplBase::getPopcntSupport (unsigned IntTyWidthInBit) const inline
Definition at line 430 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::PSK_Software.
getPredicatedAddrSpace()
std::pair< const Value *, unsigned > llvm::TargetTransformInfoImplBase::getPredicatedAddrSpace (const Value * V) const inline
Definition at line 135 of file TargetTransformInfoImpl.h.
getPredictableBranchThreshold()
BranchProbability llvm::TargetTransformInfoImplBase::getPredictableBranchThreshold () const inline
Definition at line 98 of file TargetTransformInfoImpl.h.
getPreferredAddressingMode()
TTI::AddressingModeKind llvm::TargetTransformInfoImplBase::getPreferredAddressingMode (const Loop * L, ScalarEvolution * SE) const inline
Definition at line 266 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::AMK_None.
getPreferredExpandedReductionShuffle()
TTI::ReductionShuffle llvm::TargetTransformInfoImplBase::getPreferredExpandedReductionShuffle (const IntrinsicInst * II) const inline
Definition at line 954 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::SplitHalf.
getPreferredTailFoldingStyle()
TailFoldingStyle llvm::TargetTransformInfoImplBase::getPreferredTailFoldingStyle (bool IVUpdateMayOverflow = true) const inline
Definition at line 198 of file TargetTransformInfoImpl.h.
References llvm::DataWithoutLaneMask.
Referenced by llvm::BasicTTIImplBase< T >::getPreferredTailFoldingStyle().
getPrefetchDistance()
unsigned llvm::TargetTransformInfoImplBase::getPrefetchDistance () const inline
Definition at line 544 of file TargetTransformInfoImpl.h.
getRegisterBitWidth()
TypeSize llvm::TargetTransformInfoImplBase::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const inline
Definition at line 490 of file TargetTransformInfoImpl.h.
References llvm::TypeSize::getFixed().
Referenced by llvm::LoongArchTTIImpl::getRegisterBitWidth().
getRegisterClassForType()
unsigned llvm::TargetTransformInfoImplBase::getRegisterClassForType (bool Vector, Type * Ty = nullptr) const inline
Definition at line 475 of file TargetTransformInfoImpl.h.
References llvm::Vector.
getRegisterClassName()
const char * llvm::TargetTransformInfoImplBase::getRegisterClassName (unsigned ClassID) const inline
Definition at line 479 of file TargetTransformInfoImpl.h.
getRegUsageForType()
unsigned llvm::TargetTransformInfoImplBase::getRegUsageForType (Type * Ty) const inline
Definition at line 366 of file TargetTransformInfoImpl.h.
getReplicationShuffleCost()
unsigned llvm::TargetTransformInfoImplBase::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind) inline
Definition at line 688 of file TargetTransformInfoImpl.h.
getScalarizationOverhead()
InstructionCost llvm::TargetTransformInfoImplBase::getScalarizationOverhead (VectorType * Ty, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const inline
Definition at line 380 of file TargetTransformInfoImpl.h.
getScalingFactorCost()
InstructionCost llvm::TargetTransformInfoImplBase::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const inline
Definition at line 344 of file TargetTransformInfoImpl.h.
References llvm::StackOffset::getFixed(), llvm::StackOffset::getScalable(), and isLegalAddressingMode().
getShuffleCost()
InstructionCost llvm::TargetTransformInfoImplBase::getShuffleCost (TTI::ShuffleKind Kind, VectorType * Ty, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const inline
Definition at line 604 of file TargetTransformInfoImpl.h.
getStoreMinimumVF()
unsigned llvm::TargetTransformInfoImplBase::getStoreMinimumVF (unsigned VF, Type * , Type *) const inline
Definition at line 510 of file TargetTransformInfoImpl.h.
getStoreVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 929 of file TargetTransformInfoImpl.h.
getStridedMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getStridedMemoryOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline
Definition at line 723 of file TargetTransformInfoImpl.h.
References llvm::InstructionCost::getInvalid().
getTgtMemIntrinsic()
bool llvm::TargetTransformInfoImplBase::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) const inline
Definition at line 831 of file TargetTransformInfoImpl.h.
getUnrollingPreferences()
void llvm::TargetTransformInfoImplBase::getUnrollingPreferences (Loop * , ScalarEvolution & , TTI::UnrollingPreferences & , OptimizationRemarkEmitter *) const inline
Definition at line 222 of file TargetTransformInfoImpl.h.
getVectorInstrCost() [1/2]
InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline
Definition at line 682 of file TargetTransformInfoImpl.h.
getVectorInstrCost() [2/2]
InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Op0, Value * Op1) const inline
Definition at line 675 of file TargetTransformInfoImpl.h.
getVPLegalizationStrategy()
TargetTransformInfo::VPLegalization llvm::TargetTransformInfoImplBase::getVPLegalizationStrategy (const VPIntrinsic & PI) const inline
Definition at line 972 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::VPLegalization::Convert, and llvm::TargetTransformInfo::VPLegalization::Discard.
getVPMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getVPMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction * I) const inline
Definition at line 702 of file TargetTransformInfoImpl.h.
Referenced by llvm::PPCTTIImpl::getVPMemoryOpCost().
getVScaleForTuning()
std::optional< unsigned > llvm::TargetTransformInfoImplBase::getVScaleForTuning () const inline
Definition at line 497 of file TargetTransformInfoImpl.h.
hasActiveVectorLength()
bool llvm::TargetTransformInfoImplBase::hasActiveVectorLength (unsigned Opcode, Type * DataType, Align Alignment) const inline
Definition at line 966 of file TargetTransformInfoImpl.h.
hasArmWideBranch()
bool llvm::TargetTransformInfoImplBase::hasArmWideBranch (bool) const inline
Definition at line 978 of file TargetTransformInfoImpl.h.
hasBranchDivergence()
bool llvm::TargetTransformInfoImplBase::hasBranchDivergence (const Function * F = nullptr) const inline
Definition at line 104 of file TargetTransformInfoImpl.h.
hasConditionalLoadStoreForType()
bool llvm::TargetTransformInfoImplBase::hasConditionalLoadStoreForType (Type * Ty) const inline
Definition at line 473 of file TargetTransformInfoImpl.h.
hasDivRemOp()
bool llvm::TargetTransformInfoImplBase::hasDivRemOp (Type * DataType, bool IsSigned) const inline
Definition at line 336 of file TargetTransformInfoImpl.h.
hasVolatileVariant()
bool llvm::TargetTransformInfoImplBase::hasVolatileVariant (Instruction * I, unsigned AddrSpace) const inline
Definition at line 338 of file TargetTransformInfoImpl.h.
haveFastSqrt()
bool llvm::TargetTransformInfoImplBase::haveFastSqrt (Type * Ty) const inline
Definition at line 434 of file TargetTransformInfoImpl.h.
instCombineIntrinsic()
std::optional< Instruction * > llvm::TargetTransformInfoImplBase::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const inline
Definition at line 202 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::instCombineIntrinsic().
isAlwaysUniform()
bool llvm::TargetTransformInfoImplBase::isAlwaysUniform (const Value * V) const inline
Definition at line 108 of file TargetTransformInfoImpl.h.
isConstantStridedAccessLessThan()
bool llvm::TargetTransformInfoImplBase::isConstantStridedAccessLessThan (ScalarEvolution * SE, const SCEV * Ptr, int64_t MergeDistance) const inline protected
Definition at line 1051 of file TargetTransformInfoImpl.h.
References llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), getConstantStrideStep(), llvm::APInt::getSExtValue(), and Ptr.
Referenced by llvm::AArch64TTIImpl::getAddressComputationCost(), and llvm::ARMTTIImpl::getAddressComputationCost().
isElementTypeLegalForScalableVector()
bool llvm::TargetTransformInfoImplBase::isElementTypeLegalForScalableVector (Type * Ty) const inline
Definition at line 921 of file TargetTransformInfoImpl.h.
isExpensiveToSpeculativelyExecute()
bool llvm::TargetTransformInfoImplBase::isExpensiveToSpeculativelyExecute (const Instruction * I) inline
Definition at line 436 of file TargetTransformInfoImpl.h.
Referenced by llvm::X86TTIImpl::isExpensiveToSpeculativelyExecute().
isFCmpOrdCheaperThanFCmpZero()
bool llvm::TargetTransformInfoImplBase::isFCmpOrdCheaperThanFCmpZero (Type * Ty) const inline
Definition at line 438 of file TargetTransformInfoImpl.h.
isFPVectorizationPotentiallyUnsafe()
bool llvm::TargetTransformInfoImplBase::isFPVectorizationPotentiallyUnsafe () const inline
Definition at line 422 of file TargetTransformInfoImpl.h.
isHardwareLoopProfitable()
bool llvm::TargetTransformInfoImplBase::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) const inline
Definition at line 189 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::isHardwareLoopProfitable().
isIndexedLoadLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 890 of file TargetTransformInfoImpl.h.
isIndexedStoreLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 895 of file TargetTransformInfoImpl.h.
isLegalAddImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalAddImmediate (int64_t Imm) const inline
Definition at line 229 of file TargetTransformInfoImpl.h.
isLegalAddressingMode()
bool llvm::TargetTransformInfoImplBase::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr, int64_t ScalableOffset = 0) const inline
Definition at line 235 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), and getScalingFactorCost().
isLegalAddScalableImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalAddScalableImmediate (int64_t Imm) const inline
Definition at line 231 of file TargetTransformInfoImpl.h.
isLegalAltInstr()
bool llvm::TargetTransformInfoImplBase::isLegalAltInstr (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask) const inline
Definition at line 317 of file TargetTransformInfoImpl.h.
isLegalBroadcastLoad()
bool llvm::TargetTransformInfoImplBase::isLegalBroadcastLoad (Type * ElementTy, ElementCount NumElements) const inline
Definition at line 292 of file TargetTransformInfoImpl.h.
isLegalICmpImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalICmpImmediate (int64_t Imm) const inline
Definition at line 233 of file TargetTransformInfoImpl.h.
isLegalMaskedCompressStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedCompressStore (Type * DataType, Align Alignment) const inline
Definition at line 313 of file TargetTransformInfoImpl.h.
isLegalMaskedExpandLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedExpandLoad (Type * DataType, Align Alignment) const inline
Definition at line 322 of file TargetTransformInfoImpl.h.
isLegalMaskedGather()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedGather (Type * DataType, Align Alignment) const inline
Definition at line 300 of file TargetTransformInfoImpl.h.
isLegalMaskedLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedLoad (Type * DataType, Align Alignment) const inline
Definition at line 274 of file TargetTransformInfoImpl.h.
isLegalMaskedScatter()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedScatter (Type * DataType, Align Alignment) const inline
Definition at line 296 of file TargetTransformInfoImpl.h.
isLegalMaskedStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedStore (Type * DataType, Align Alignment) const inline
Definition at line 270 of file TargetTransformInfoImpl.h.
isLegalMaskedVectorHistogram()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedVectorHistogram (Type * AddrType, Type * DataType) const inline
Definition at line 330 of file TargetTransformInfoImpl.h.
isLegalNTLoad()
bool llvm::TargetTransformInfoImplBase::isLegalNTLoad (Type * DataType, Align Alignment) const inline
Definition at line 285 of file TargetTransformInfoImpl.h.
References llvm::DataSize, DL, llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTLoad().
isLegalNTStore()
bool llvm::TargetTransformInfoImplBase::isLegalNTStore (Type * DataType, Align Alignment) const inline
Definition at line 278 of file TargetTransformInfoImpl.h.
References llvm::DataSize, DL, llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTStoreLoad().
isLegalStridedLoadStore()
bool llvm::TargetTransformInfoImplBase::isLegalStridedLoadStore (Type * DataType, Align Alignment) const inline
Definition at line 326 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoad()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoad (LoadInst * LI) const inline
Definition at line 902 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoadChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline
Definition at line 906 of file TargetTransformInfoImpl.h.
isLegalToVectorizeReduction()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeReduction (const RecurrenceDescriptor & RdxDesc, ElementCount VF) const inline
Definition at line 916 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStore()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStore (StoreInst * SI) const inline
Definition at line 904 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStoreChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline
Definition at line 911 of file TargetTransformInfoImpl.h.
isLoweredToCall()
bool llvm::TargetTransformInfoImplBase::isLoweredToCall (const Function * F) const inline
Definition at line 144 of file TargetTransformInfoImpl.h.
References assert(), F, and Name.
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::BasicTTIImplBase< T >::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::WebAssemblyTTIImpl::getUnrollingPreferences(), and llvm::ARMTTIImpl::isLoweredToCall().
isLSRCostLess()
bool llvm::TargetTransformInfoImplBase::isLSRCostLess (const TTI::LSRCost & C1, const TTI::LSRCost & C2) const inline
Definition at line 244 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by llvm::AArch64TTIImpl::isLSRCostLess(), llvm::BasicTTIImplBase< T >::isLSRCostLess(), and llvm::PPCTTIImpl::isLSRCostLess().
isNoopAddrSpaceCast()
bool llvm::TargetTransformInfoImplBase::isNoopAddrSpaceCast (unsigned , unsigned) const inline
Definition at line 125 of file TargetTransformInfoImpl.h.
isNumRegsMajorCostOfLSR()
bool llvm::TargetTransformInfoImplBase::isNumRegsMajorCostOfLSR () const inline
Definition at line 251 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::isNumRegsMajorCostOfLSR().
isProfitableLSRChainElement()
bool llvm::TargetTransformInfoImplBase::isProfitableLSRChainElement (Instruction * I) const inline
Definition at line 255 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::isProfitableLSRChainElement().
isProfitableToHoist()
bool llvm::TargetTransformInfoImplBase::isProfitableToHoist (Instruction * I) const inline
Definition at line 360 of file TargetTransformInfoImpl.h.
isSingleThreaded()
bool llvm::TargetTransformInfoImplBase::isSingleThreaded () const inline
Definition at line 132 of file TargetTransformInfoImpl.h.
isSourceOfDivergence()
bool llvm::TargetTransformInfoImplBase::isSourceOfDivergence (const Value * V) const inline
Definition at line 106 of file TargetTransformInfoImpl.h.
isStridedAccess()
bool llvm::TargetTransformInfoImplBase::isStridedAccess (const SCEV * Ptr) const inline protected
Definition at line 1039 of file TargetTransformInfoImpl.h.
References llvm::isa(), and Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and getConstantStrideStep().
isTargetIntrinsicTriviallyScalarizable()
bool llvm::TargetTransformInfoImplBase::isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const inline
Definition at line 376 of file TargetTransformInfoImpl.h.
isTruncateFree()
bool llvm::TargetTransformInfoImplBase::isTruncateFree (Type * Ty1, Type * Ty2) const inline
Definition at line 358 of file TargetTransformInfoImpl.h.
isTypeLegal()
bool llvm::TargetTransformInfoImplBase::isTypeLegal (Type * Ty) const inline
Definition at line 364 of file TargetTransformInfoImpl.h.
isValidAddrSpaceCast()
bool llvm::TargetTransformInfoImplBase::isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const inline
Definition at line 110 of file TargetTransformInfoImpl.h.
isVScaleKnownToBeAPowerOfTwo()
bool llvm::TargetTransformInfoImplBase::isVScaleKnownToBeAPowerOfTwo () const inline
Definition at line 498 of file TargetTransformInfoImpl.h.
LSRWithInstrQueries()
bool llvm::TargetTransformInfoImplBase::LSRWithInstrQueries () const inline
Definition at line 356 of file TargetTransformInfoImpl.h.
minRequiredElementSize()
unsigned llvm::TargetTransformInfoImplBase::minRequiredElementSize (const Value * Val, bool & isSigned) const inline protected
Definition at line 985 of file TargetTransformInfoImpl.h.
References llvm::cast(), llvm::dyn_cast(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isa(), and isSigned().
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost().
preferEpilogueVectorization()
bool llvm::TargetTransformInfoImplBase::preferEpilogueVectorization () const inline
Definition at line 947 of file TargetTransformInfoImpl.h.
preferFixedOverScalableIfEqualCost()
bool llvm::TargetTransformInfoImplBase::preferFixedOverScalableIfEqualCost () const inline
Definition at line 935 of file TargetTransformInfoImpl.h.
preferInLoopReduction()
bool llvm::TargetTransformInfoImplBase::preferInLoopReduction (unsigned Opcode, Type * Ty, TTI::ReductionFlags Flags) const inline
Definition at line 937 of file TargetTransformInfoImpl.h.
preferPredicatedReductionSelect()
bool llvm::TargetTransformInfoImplBase::preferPredicatedReductionSelect (unsigned Opcode, Type * Ty, TTI::ReductionFlags Flags) const inline
Definition at line 942 of file TargetTransformInfoImpl.h.
preferPredicateOverEpilogue()
bool llvm::TargetTransformInfoImplBase::preferPredicateOverEpilogue (TailFoldingInfo * TFI) const inline
Definition at line 195 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::preferPredicateOverEpilogue().
prefersVectorizedAddressing()
bool llvm::TargetTransformInfoImplBase::prefersVectorizedAddressing () const inline
Definition at line 342 of file TargetTransformInfoImpl.h.
preferToKeepConstantsAttached()
bool llvm::TargetTransformInfoImplBase::preferToKeepConstantsAttached (const Instruction & Inst, const Function & Fn) const inline
Definition at line 467 of file TargetTransformInfoImpl.h.
rewriteIntrinsicWithAddressSpace()
Value * llvm::TargetTransformInfoImplBase::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline
Definition at line 139 of file TargetTransformInfoImpl.h.
shouldBuildLookupTables()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTables () const inline
Definition at line 368 of file TargetTransformInfoImpl.h.
shouldBuildLookupTablesForConstant()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTablesForConstant (Constant * C) const inline
Definition at line 370 of file TargetTransformInfoImpl.h.
shouldBuildRelLookupTables()
bool llvm::TargetTransformInfoImplBase::shouldBuildRelLookupTables () const inline
Definition at line 372 of file TargetTransformInfoImpl.h.
shouldConsiderAddressTypePromotion()
bool llvm::TargetTransformInfoImplBase::shouldConsiderAddressTypePromotion (const Instruction & I, bool & AllowPromotionWithoutCommonHeader) const inline
Definition at line 512 of file TargetTransformInfoImpl.h.
shouldDropLSRSolutionIfLessProfitable()
bool llvm::TargetTransformInfoImplBase::shouldDropLSRSolutionIfLessProfitable () const inline
Definition at line 253 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::shouldDropLSRSolutionIfLessProfitable().
shouldExpandReduction()
bool llvm::TargetTransformInfoImplBase::shouldExpandReduction (const IntrinsicInst * II) const inline
Definition at line 951 of file TargetTransformInfoImpl.h.
shouldMaximizeVectorBandwidth()
bool llvm::TargetTransformInfoImplBase::shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const inline
Definition at line 501 of file TargetTransformInfoImpl.h.
shouldPrefetchAddressSpace()
bool llvm::TargetTransformInfoImplBase::shouldPrefetchAddressSpace (unsigned AS) const inline
Definition at line 552 of file TargetTransformInfoImpl.h.
shouldTreatInstructionLikeSelect()
bool llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect (const Instruction * I) inline
Definition at line 409 of file TargetTransformInfoImpl.h.
References I, llvm::isa(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::AArch64TTIImpl::shouldTreatInstructionLikeSelect().
simplifyDemandedUseBitsIntrinsic()
std::optional< Value * > llvm::TargetTransformInfoImplBase::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const inline
Definition at line 208 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::simplifyDemandedUseBitsIntrinsic().
simplifyDemandedVectorEltsIntrinsic()
std::optional< Value * > llvm::TargetTransformInfoImplBase::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const inline
Definition at line 214 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::simplifyDemandedVectorEltsIntrinsic().
supportsEfficientVectorElementLoadStore()
bool llvm::TargetTransformInfoImplBase::supportsEfficientVectorElementLoadStore () const inline
Definition at line 394 of file TargetTransformInfoImpl.h.
supportsScalableVectors()
bool llvm::TargetTransformInfoImplBase::supportsScalableVectors () const inline
Definition at line 962 of file TargetTransformInfoImpl.h.
supportsTailCalls()
bool llvm::TargetTransformInfoImplBase::supportsTailCalls () const inline
Definition at line 396 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::supportsTailCallFor().
useAA()
bool llvm::TargetTransformInfoImplBase::useAA () const inline
Definition at line 362 of file TargetTransformInfoImpl.h.
useColdCCForColdCall()
bool llvm::TargetTransformInfoImplBase::useColdCCForColdCall (Function & F) const inline
Definition at line 374 of file TargetTransformInfoImpl.h.
Member Data Documentation
DL
const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 39 of file TargetTransformInfoImpl.h.
Referenced by getCastInstrCost(), getDataLayout(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), isLegalNTLoad(), and isLegalNTStore().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetTransformInfoImpl.h