LLVM: llvm::sandboxir::ShuffleVectorSetMask Class Reference
llvm::sandboxir::ShuffleVectorSetMask Class Reference final
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
ShuffleVectorSetMask (ShuffleVectorInst *SVI)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 375 of file Tracker.h.
Constructor & Destructor Documentation
ShuffleVectorSetMask()
ShuffleVectorSetMask::ShuffleVectorSetMask (ShuffleVectorInst * SVI)
Definition at line 237 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::ShuffleVectorSetMask::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 382 of file Tracker.h.
dump() [1/2]
void ShuffleVectorSetMask::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 245 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::ShuffleVectorSetMask::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 384 of file Tracker.h.
References OS.
revert()
void ShuffleVectorSetMask::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 240 of file Tracker.cpp.
References llvm::sandboxir::ShuffleVectorInst::setShuffleMask().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp