LLVM: llvm::SmallSet< T, N, C > Class Template Reference
llvm::SmallSet< T, N, C > Class Template Reference
SmallSet - This maintains a set of unique values, optimizing for the case when the set is small (less than N).
#include "llvm/ADT/SmallSet.h"
Public Types
using key_type = T
using size_type = size_t
using value_type = T
using const_iterator = SmallSetIterator<T, N, C>
Public Member Functions
SmallSet ()=default
SmallSet (const SmallSet &)=default
SmallSet (SmallSet &&)=default
template<typename IterT >
SmallSet (IterT Begin, IterT End)
template<typename RangeT >
SmallSet (const iterator_range< RangeT > &R)
SmallSet (std::initializer_list< T > L)
SmallSet & operator= (const SmallSet &)=default
SmallSet & operator= (SmallSet &&)=default
bool empty () const
size_type size () const
size_type count (const T &V) const
count - Return 1 if the element is in the set, 0 otherwise.
std::pair< const_iterator, bool > insert (const T &V)
insert - Insert an element into the set if it isn't already there.
std::pair< const_iterator, bool > insert (T &&V)
template<typename IterT >
void insert (IterT I, IterT E)
bool erase (const T &V)
void clear ()
const_iterator begin () const
const_iterator end () const
bool contains (const T &V) const
Check if the SmallSet contains the given element.
Detailed Description
template<typename T, unsigned N, typename C = std::less<T>>
class llvm::SmallSet< T, N, C >
SmallSet - This maintains a set of unique values, optimizing for the case when the set is small (less than N).
In this case, the set can be maintained with no mallocs. If the set gets large, we expand to using an std::set to maintain reasonable lookup times.
Definition at line 132 of file SmallSet.h.
Member Typedef Documentation
const_iterator
template<typename T , unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::const_iterator = SmallSetIterator<T, N, C>
Definition at line 148 of file SmallSet.h.
key_type
template<typename T , unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::key_type = T
Definition at line 145 of file SmallSet.h.
size_type
template<typename T , unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::size_type = size_t
Definition at line 146 of file SmallSet.h.
value_type
template<typename T , unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::value_type = T
Definition at line 147 of file SmallSet.h.
Constructor & Destructor Documentation
SmallSet() [1/6]
template<typename T , unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet () default
SmallSet() [2/6]
template<typename T , unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (const SmallSet< T, N, C > &) default
SmallSet() [3/6]
template<typename T , unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (SmallSet< T, N, C > &&) default
SmallSet() [4/6]
template<typename T , unsigned N, typename C = std::less<T>> template<typename IterT > llvm::SmallSet< T, N, C >::SmallSet (IterT Begin, IterT End) inline
Definition at line 154 of file SmallSet.h.
References End, and llvm::SmallSet< T, N, C >::insert().
SmallSet() [5/6]
template<typename T , unsigned N, typename C = std::less<T>> template<typename RangeT > llvm::SmallSet< T, N, C >::SmallSet (const iterator_range< RangeT > & R) inline explicit
Definition at line 159 of file SmallSet.h.
References llvm::SmallSet< T, N, C >::insert().
SmallSet() [6/6]
template<typename T , unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (std::initializer_list< T > L) inline
Definition at line 163 of file SmallSet.h.
References llvm::SmallSet< T, N, C >::insert().
Member Function Documentation
begin()
template<typename T , unsigned N, typename C = std::less<T>> const_iterator llvm::SmallSet< T, N, C >::begin () const inline
Definition at line 209 of file SmallSet.h.
References llvm::Vector.
Referenced by interpretValues().
clear()
template<typename T , unsigned N, typename C = std::less<T>> void llvm::SmallSet< T, N, C >::clear () inline
Definition at line 204 of file SmallSet.h.
References llvm::Vector.
Referenced by llvm::HexagonSubtarget::adjustSchedDependency(), llvm::HexagonHazardRecognizer::AdvanceCycle(), llvm::SPIRV::RequirementHandler::clear(), findConsecutiveLoad(), ReduceLoopStrength(), and llvm::HexagonHazardRecognizer::Reset().
contains()
template<typename T , unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::contains (const T & V) const inline
Check if the SmallSet contains the given element.
Definition at line 222 of file SmallSet.h.
References llvm::Vector.
Referenced by llvm::SPIRVSubtarget::canUseExtension(), llvm::SPIRVSubtarget::canUseExtInstSet(), clobberRegEntries(), llvm::SmallSet< T, N, C >::count(), foldConstantsIntoIntrinsics(), and llvm::SMSchedule::normalizeNonPipelinedInstructions().
count()
template<typename T , unsigned N, typename C = std::less<T>> size_type llvm::SmallSet< T, N, C >::count (const T & V) const inline
count - Return 1 if the element is in the set, 0 otherwise.
Definition at line 175 of file SmallSet.h.
References llvm::SmallSet< T, N, C >::contains().
Referenced by addHints(), llvm::ARMBaseInstrInfo::canCauseFpMLxStall(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::Instruction::dropUnknownNonDebugMetadata(), emitSelectPseudo(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::finalizeBundle(), findConsecutiveLoad(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), getUniqueCaseValue(), hoistAndMergeSGPRInits(), llvm::WindowScheduler::initialize(), IsSafeAndProfitableToMove(), lowerStatepointMetaArgs(), MaySpeculate(), ProcessSourceNode(), programUndefinedIfUndefOrPoison(), llvm::MachineBasicBlock::SplitCriticalEdge(), and verifyCTRBranch().
empty()
template<typename T , unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::empty () const inline nodiscard
Definition at line 168 of file SmallSet.h.
References llvm::Vector.
Referenced by llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), IsValueFullyAvailableInBlock(), and llvm::ShuffleBlockStrategy::mutate().
end()
template<typename T , unsigned N, typename C = std::less<T>> const_iterator llvm::SmallSet< T, N, C >::end () const inline
Definition at line 215 of file SmallSet.h.
References llvm::Vector.
Referenced by interpretValues().
erase()
template<typename T , unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::erase (const T & V) inline
Definition at line 193 of file SmallSet.h.
References I, and llvm::Vector.
Referenced by llvm::finalizeBundle(), and IsValueFullyAvailableInBlock().
insert() [1/3]
template<typename T , unsigned N, typename C = std::less<T>> std::pair< const_iterator, bool > llvm::SmallSet< T, N, C >::insert (const T & V) inline
insert - Insert an element into the set if it isn't already there.
Returns a pair. The first value of it is an iterator to the inserted element or the existing element in the set. The second value is true if the element is inserted (it was not in the set before).
Definition at line 181 of file SmallSet.h.
Referenced by addConstantsToTrack(), llvm::SPIRV::RequirementHandler::addExtension(), llvm::SPIRV::RequirementHandler::addExtensions(), addHints(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), AntiDepEdges(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdatesPermissive(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), AssignProtectedObjSet(), AvoidCapabilitiesSet::AvoidCapabilitiesSet(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::changeToUnreachable(), CheckForLiveRegDef(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), clobberRegEntries(), llvm::JumpThreadingPass::cloneInstructions(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), combineShuffleOfScalars(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::ConstantFoldTerminator(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ARMBaseInstrInfo::copyPhysReg(), despeculateCountZeros(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), emitSelectPseudo(), llvm::finalizeBundle(), findConsecutiveLoad(), llvm::DWARFDie::findRecursively(), llvm::R600InstrInfo::fitsConstReadLimitations(), foldURemOfLoopIncrement(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), getUniqueCaseValue(), handleNormalInst(), hasAllNBitUsers(), hasAllNBitUsers(), hoistAndMergeSGPRInits(), llvm::WindowScheduler::initialize(), llvm::SmallSet< T, N, C >::insert(), llvm::MemorySSAUpdater::insertDef(), interpretValues(), llvm::AMDGPU::isClobberedInFunction(), isLoadCombineCandidate(), IsSafeAndProfitableToMove(), isSignExtendedW(), isSignExtendedW(), IsValueFullyAvailableInBlock(), liesBetween(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), llvm::mustExecuteUBIfPoisonOnPathTo(), llvm::ShuffleBlockStrategy::mutate(), llvm::PointerMayBeCaptured(), ProcessSourceNode(), programUndefinedIfUndefOrPoison(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::MachineDominatorTree::recordSplitCriticalEdge(), replaceAllUsesWith(), llvm::SmallSet< T, N, C >::SmallSet(), llvm::SmallSet< T, N, C >::SmallSet(), llvm::SmallSet< T, N, C >::SmallSet(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::InstCombinerImpl::tryToSinkInstructionDbgValues(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), unique_unsorted(), verifyCTRBranch(), and llvm::VirtRegAuxInfo::weightCalcHelper().
insert() [2/3]
template<typename T , unsigned N, typename C = std::less<T>> template<typename IterT > void llvm::SmallSet< T, N, C >::insert (IterT I, IterT E) inline
Definition at line 188 of file SmallSet.h.
References E, I, and llvm::SmallSet< T, N, C >::insert().
insert() [3/3]
template<typename T , unsigned N, typename C = std::less<T>> std::pair< const_iterator, bool > llvm::SmallSet< T, N, C >::insert (T && V) inline
Definition at line 183 of file SmallSet.h.
operator=() [1/2]
template<typename T , unsigned N, typename C = std::less<T>> SmallSet & llvm::SmallSet< T, N, C >::operator= (const SmallSet< T, N, C > &) default
operator=() [2/2]
template<typename T , unsigned N, typename C = std::less<T>> SmallSet & llvm::SmallSet< T, N, C >::operator= (SmallSet< T, N, C > &&) default
size()
template<typename T , unsigned N, typename C = std::less<T>> size_type llvm::SmallSet< T, N, C >::size () const inline
Definition at line 170 of file SmallSet.h.
References llvm::Vector.
Referenced by llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::changeToUnreachable(), llvm::ConstantFoldTerminator(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::R600InstrInfo::fitsConstReadLimitations(), IsSafeAndProfitableToMove(), and llvm::PointerMayBeCaptured().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallSet.h