LLVM: llvm::dxil::ResourceInfo Class Reference
llvm::dxil::ResourceInfo Class Reference
#include "llvm/Analysis/DXILResource.h"
Classes
struct FeedbackInfo
struct MSInfo
struct ResourceBinding
struct StructInfo
struct TypedInfo
struct UAVInfo
Public Member Functions
ResourceInfo (dxil::ResourceClass RC, dxil::ResourceKind Kind, Value *Symbol, StringRef Name)
bool isUAV () const
bool isCBuffer () const
bool isSampler () const
bool isStruct () const
bool isTyped () const
bool isFeedback () const
bool isMultiSample () const
void bind (uint32_t RecordID, uint32_t Space, uint32_t LowerBound, uint32_t Size)
const ResourceBinding & getBinding () const
void setUAV (bool GloballyCoherent, bool HasCounter, bool IsROV)
const UAVInfo & getUAV () const
void setCBuffer (uint32_t Size)
void setSampler (dxil::SamplerType Ty)
void setStruct (uint32_t Stride, MaybeAlign Alignment)
void setTyped (dxil::ElementType ElementTy, uint32_t ElementCount)
const TypedInfo & getTyped () const
void setFeedback (dxil::SamplerFeedbackType Type)
void setMultiSample (uint32_t Count)
const MSInfo & getMultiSample () const
StringRef getName () const
dxil::ResourceClass getResourceClass () const
dxil::ResourceKind getResourceKind () const
bool operator== (const ResourceInfo &RHS) const
bool operator!= (const ResourceInfo &RHS) const
bool operator< (const ResourceInfo &RHS) const
MDTuple * getAsMetadata (LLVMContext &Ctx) const
std::pair< uint32_t, uint32_t > getAnnotateProps () const
void print (raw_ostream &OS) const
Static Public Member Functions
static ResourceInfo SRV (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, dxil::ResourceKind Kind)
static ResourceInfo RawBuffer (Value *Symbol, StringRef Name)
static ResourceInfo StructuredBuffer (Value *Symbol, StringRef Name, uint32_t Stride, MaybeAlign Alignment)
static ResourceInfo Texture2DMS (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount)
static ResourceInfo Texture2DMSArray (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount)
static ResourceInfo UAV (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, bool GloballyCoherent, bool IsROV, dxil::ResourceKind Kind)
static ResourceInfo RWRawBuffer (Value *Symbol, StringRef Name, bool GloballyCoherent, bool IsROV)
static ResourceInfo RWStructuredBuffer (Value *Symbol, StringRef Name, uint32_t Stride, MaybeAlign Alignment, bool GloballyCoherent, bool IsROV, bool HasCounter)
static ResourceInfo RWTexture2DMS (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount, bool GloballyCoherent)
static ResourceInfo RWTexture2DMSArray (Value *Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount, bool GloballyCoherent)
static ResourceInfo FeedbackTexture2D (Value *Symbol, StringRef Name, dxil::SamplerFeedbackType FeedbackTy)
static ResourceInfo FeedbackTexture2DArray (Value *Symbol, StringRef Name, dxil::SamplerFeedbackType FeedbackTy)
static ResourceInfo CBuffer (Value *Symbol, StringRef Name, uint32_t Size)
static ResourceInfo Sampler (Value *Symbol, StringRef Name, dxil::SamplerType SamplerTy)
Detailed Description
Definition at line 27 of file DXILResource.h.
Constructor & Destructor Documentation
ResourceInfo()
llvm::dxil::ResourceInfo::ResourceInfo (dxil::ResourceClass RC, dxil::ResourceKind Kind, Value * Symbol, StringRef Name) inline
Definition at line 140 of file DXILResource.h.
Member Function Documentation
bind()
void llvm::dxil::ResourceInfo::bind (uint32_t RecordID, uint32_t Space, uint32_t LowerBound, uint32_t Size) inline
Definition at line 153 of file DXILResource.h.
References Size.
Referenced by llvm::DXILResourceMap::DXILResourceMap().
CBuffer()
ResourceInfo ResourceInfo::CBuffer (Value * Symbol, StringRef Name, uint32_t Size) static
Definition at line 320 of file DXILResource.cpp.
References llvm::dxil::CBuffer, setCBuffer(), and Size.
FeedbackTexture2D()
ResourceInfo ResourceInfo::FeedbackTexture2D (Value * Symbol, StringRef Name, dxil::SamplerFeedbackType FeedbackTy) static
Definition at line 301 of file DXILResource.cpp.
References llvm::dxil::FeedbackTexture2D, setFeedback(), setUAV(), and llvm::dxil::UAV.
FeedbackTexture2DArray()
ResourceInfo ResourceInfo::FeedbackTexture2DArray (Value * Symbol, StringRef Name, dxil::SamplerFeedbackType FeedbackTy) static
Definition at line 311 of file DXILResource.cpp.
References llvm::dxil::FeedbackTexture2DArray, setFeedback(), setUAV(), and llvm::dxil::UAV.
getAnnotateProps()
std::pair< uint32_t, uint32_t > ResourceInfo::getAnnotateProps () const
Definition at line 439 of file DXILResource.cpp.
References llvm::dxil::ResourceInfo::StructInfo::AlignLog2, CBufferSize, llvm::dxil::Comparison, llvm::dxil::ResourceInfo::MSInfo::Count, llvm::dxil::ResourceInfo::TypedInfo::ElementCount, llvm::dxil::ResourceInfo::TypedInfo::ElementTy, Feedback, llvm::dxil::ResourceInfo::UAVInfo::GloballyCoherent, llvm::dxil::ResourceInfo::UAVInfo::HasCounter, isCBuffer(), isFeedback(), isMultiSample(), llvm::dxil::ResourceInfo::UAVInfo::IsROV, isSampler(), isStruct(), isTyped(), isUAV(), SamplerTy, llvm::dxil::ResourceInfo::StructInfo::Stride, Struct, llvm::to_underlying(), llvm::dxil::ResourceInfo::FeedbackInfo::Type, Typed, and UAVFlags.
getAsMetadata()
MDTuple * ResourceInfo::getAsMetadata (LLVMContext & Ctx) const
Definition at line 377 of file DXILResource.cpp.
References CBufferSize, llvm::dxil::ResourceInfo::MSInfo::Count, llvm::dxil::ResourceInfo::TypedInfo::ElementTy, llvm::dxil::ElementType, llvm::SmallVectorBase< Size_T >::empty(), Feedback, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ValueAsMetadata::get(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Constant::getIntegerValue(), llvm::dxil::ResourceInfo::UAVInfo::GloballyCoherent, llvm::dxil::ResourceInfo::UAVInfo::HasCounter, isCBuffer(), isFeedback(), isMultiSample(), llvm::dxil::ResourceInfo::UAVInfo::IsROV, isSampler(), isStruct(), isTyped(), isUAV(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::dxil::SamplerFeedbackKind, SamplerTy, llvm::dxil::ResourceInfo::StructInfo::Stride, Struct, llvm::dxil::StructuredBufferStride, llvm::to_underlying(), llvm::dxil::ResourceInfo::FeedbackInfo::Type, Typed, and UAVFlags.
getBinding()
const ResourceBinding & llvm::dxil::ResourceInfo::getBinding () const inline
Definition at line 160 of file DXILResource.h.
Referenced by llvm::DXILResourceMap::DXILResourceMap().
getMultiSample()
const MSInfo & llvm::dxil::ResourceInfo::getMultiSample () const inline
Definition at line 198 of file DXILResource.h.
References assert(), and isMultiSample().
getName()
StringRef llvm::dxil::ResourceInfo::getName () const inline
Definition at line 203 of file DXILResource.h.
getResourceClass()
dxil::ResourceClass llvm::dxil::ResourceInfo::getResourceClass () const inline
Definition at line 204 of file DXILResource.h.
getResourceKind()
dxil::ResourceKind llvm::dxil::ResourceInfo::getResourceKind () const inline
Definition at line 205 of file DXILResource.h.
getTyped()
const TypedInfo & llvm::dxil::ResourceInfo::getTyped () const inline
Definition at line 186 of file DXILResource.h.
References assert(), isTyped(), and Typed.
Referenced by getFormatName().
getUAV()
const UAVInfo & llvm::dxil::ResourceInfo::getUAV () const inline
Definition at line 167 of file DXILResource.h.
References assert(), isUAV(), and UAVFlags.
isCBuffer()
bool ResourceInfo::isCBuffer () const
Definition at line 153 of file DXILResource.cpp.
References llvm::dxil::CBuffer.
Referenced by llvm::DXILResourceMap::DXILResourceMap(), getAnnotateProps(), getAsMetadata(), getFormatName(), operator<(), operator==(), print(), and setCBuffer().
isFeedback()
bool ResourceInfo::isFeedback () const
Definition at line 190 of file DXILResource.cpp.
References llvm::dxil::FeedbackTexture2D, and llvm::dxil::FeedbackTexture2DArray.
Referenced by getAnnotateProps(), getAsMetadata(), operator<(), operator==(), print(), and setFeedback().
isMultiSample()
bool ResourceInfo::isMultiSample () const
Definition at line 195 of file DXILResource.cpp.
References llvm::dxil::Texture2DMS, and llvm::dxil::Texture2DMSArray.
Referenced by getAnnotateProps(), getAsMetadata(), getMultiSample(), operator<(), operator==(), print(), setMultiSample(), SRV(), and UAV().
isSampler()
bool ResourceInfo::isSampler () const
Definition at line 155 of file DXILResource.cpp.
References llvm::dxil::Sampler.
Referenced by llvm::DXILResourceMap::DXILResourceMap(), getAnnotateProps(), getAsMetadata(), getFormatName(), operator<(), operator==(), and print().
isStruct()
bool ResourceInfo::isStruct () const
Definition at line 157 of file DXILResource.cpp.
References llvm::dxil::StructuredBuffer.
Referenced by getAnnotateProps(), getAsMetadata(), getFormatName(), operator<(), operator==(), print(), setStruct(), SRV(), and UAV().
isTyped()
bool ResourceInfo::isTyped () const
Definition at line 161 of file DXILResource.cpp.
References llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by getAnnotateProps(), getAsMetadata(), getFormatName(), getTyped(), operator<(), operator==(), print(), setTyped(), SRV(), and UAV().
isUAV()
bool ResourceInfo::isUAV () const
Definition at line 151 of file DXILResource.cpp.
References llvm::dxil::UAV.
Referenced by llvm::DXILResourceMap::DXILResourceMap(), getAnnotateProps(), getAsMetadata(), getUAV(), operator<(), operator==(), print(), and setUAV().
operator!=()
bool llvm::dxil::ResourceInfo::operator!= (const ResourceInfo & RHS) const inline
Definition at line 208 of file DXILResource.h.
References RHS.
operator<()
bool ResourceInfo::operator< (const ResourceInfo & RHS) const
Definition at line 355 of file DXILResource.cpp.
References CBufferSize, Feedback, isCBuffer(), isFeedback(), isMultiSample(), isSampler(), isStruct(), isTyped(), isUAV(), SamplerTy, Struct, Typed, and UAVFlags.
operator==()
bool ResourceInfo::operator== (const ResourceInfo & RHS) const
Definition at line 334 of file DXILResource.cpp.
References CBufferSize, Feedback, isCBuffer(), isFeedback(), isMultiSample(), isSampler(), isStruct(), isTyped(), isUAV(), SamplerTy, Struct, Typed, and UAVFlags.
print()
void ResourceInfo::print (raw_ostream & OS) const
Definition at line 481 of file DXILResource.cpp.
References llvm::dxil::ResourceInfo::StructInfo::AlignLog2, CBufferSize, llvm::dxil::ResourceInfo::MSInfo::Count, llvm::dxil::ResourceInfo::TypedInfo::ElementCount, llvm::dxil::ResourceInfo::TypedInfo::ElementTy, Feedback, getElementTypeName(), getResourceClassName(), getResourceKindName(), getSamplerFeedbackTypeName(), getSamplerTypeName(), llvm::dxil::ResourceInfo::UAVInfo::GloballyCoherent, llvm::dxil::ResourceInfo::UAVInfo::HasCounter, isCBuffer(), isFeedback(), isMultiSample(), llvm::dxil::ResourceInfo::UAVInfo::IsROV, isSampler(), isStruct(), isTyped(), isUAV(), OS, SamplerTy, llvm::dxil::ResourceInfo::StructInfo::Stride, Struct, llvm::dxil::ResourceInfo::FeedbackInfo::Type, Typed, and UAVFlags.
RawBuffer()
ResourceInfo ResourceInfo::RawBuffer (Value * Symbol, StringRef Name) static
Definition at line 210 of file DXILResource.cpp.
References llvm::dxil::RawBuffer, and llvm::dxil::SRV.
RWRawBuffer()
ResourceInfo ResourceInfo::RWRawBuffer (Value * Symbol, StringRef Name, bool GloballyCoherent, bool IsROV) static
Definition at line 257 of file DXILResource.cpp.
References llvm::dxil::RawBuffer, setUAV(), and llvm::dxil::UAV.
RWStructuredBuffer()
ResourceInfo ResourceInfo::RWStructuredBuffer (Value * Symbol, StringRef Name, uint32_t Stride, MaybeAlign Alignment, bool GloballyCoherent, bool IsROV, bool HasCounter) static
Definition at line 264 of file DXILResource.cpp.
References setStruct(), setUAV(), llvm::dxil::StructuredBuffer, and llvm::dxil::UAV.
RWTexture2DMS()
ResourceInfo ResourceInfo::RWTexture2DMS (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount, bool GloballyCoherent) static
Definition at line 276 of file DXILResource.cpp.
References setMultiSample(), setTyped(), setUAV(), llvm::dxil::Texture2DMS, and llvm::dxil::UAV.
RWTexture2DMSArray()
ResourceInfo ResourceInfo::RWTexture2DMSArray (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount, bool GloballyCoherent) static
Definition at line 288 of file DXILResource.cpp.
References setMultiSample(), setTyped(), setUAV(), llvm::dxil::Texture2DMSArray, and llvm::dxil::UAV.
Sampler()
ResourceInfo ResourceInfo::Sampler (Value * Symbol, StringRef Name, dxil::SamplerType SamplerTy) static
Definition at line 327 of file DXILResource.cpp.
References llvm::dxil::Sampler, SamplerTy, and setSampler().
setCBuffer()
void llvm::dxil::ResourceInfo::setCBuffer (uint32_t Size) inline
Definition at line 171 of file DXILResource.h.
References assert(), CBufferSize, isCBuffer(), and Size.
Referenced by CBuffer().
setFeedback()
void llvm::dxil::ResourceInfo::setFeedback (dxil::SamplerFeedbackType Type) inline
Definition at line 190 of file DXILResource.h.
References assert(), Feedback, isFeedback(), llvm::dxil::ResourceInfo::FeedbackInfo::Type, and Type.
Referenced by FeedbackTexture2D(), and FeedbackTexture2DArray().
setMultiSample()
void llvm::dxil::ResourceInfo::setMultiSample (uint32_t Count) inline
Definition at line 194 of file DXILResource.h.
References assert(), llvm::Count, and isMultiSample().
Referenced by RWTexture2DMS(), RWTexture2DMSArray(), Texture2DMS(), and Texture2DMSArray().
setSampler()
void llvm::dxil::ResourceInfo::setSampler (dxil::SamplerType Ty) inline
Definition at line 175 of file DXILResource.h.
References SamplerTy.
Referenced by Sampler().
setStruct()
void llvm::dxil::ResourceInfo::setStruct (uint32_t Stride, MaybeAlign Alignment) inline
Definition at line 176 of file DXILResource.h.
References llvm::dxil::ResourceInfo::StructInfo::AlignLog2, assert(), isStruct(), llvm::Log2(), llvm::dxil::ResourceInfo::StructInfo::Stride, and Struct.
Referenced by RWStructuredBuffer(), and StructuredBuffer().
setTyped()
void llvm::dxil::ResourceInfo::setTyped (dxil::ElementType ElementTy, uint32_t ElementCount) inline
Definition at line 181 of file DXILResource.h.
References assert(), llvm::dxil::ResourceInfo::TypedInfo::ElementCount, llvm::dxil::ResourceInfo::TypedInfo::ElementTy, isTyped(), and Typed.
Referenced by RWTexture2DMS(), RWTexture2DMSArray(), SRV(), Texture2DMS(), Texture2DMSArray(), and UAV().
setUAV()
void llvm::dxil::ResourceInfo::setUAV (bool GloballyCoherent, bool HasCounter, bool IsROV) inline
Definition at line 161 of file DXILResource.h.
References assert(), llvm::dxil::ResourceInfo::UAVInfo::GloballyCoherent, llvm::dxil::ResourceInfo::UAVInfo::HasCounter, llvm::dxil::ResourceInfo::UAVInfo::IsROV, isUAV(), and UAVFlags.
Referenced by FeedbackTexture2D(), FeedbackTexture2DArray(), RWRawBuffer(), RWStructuredBuffer(), RWTexture2DMS(), RWTexture2DMSArray(), and UAV().
SRV()
ResourceInfo ResourceInfo::SRV (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, dxil::ResourceKind Kind) static
Definition at line 200 of file DXILResource.cpp.
References assert(), isMultiSample(), isStruct(), isTyped(), setTyped(), and llvm::dxil::SRV.
StructuredBuffer()
ResourceInfo ResourceInfo::StructuredBuffer (Value * Symbol, StringRef Name, uint32_t Stride, MaybeAlign Alignment) static
Definition at line 215 of file DXILResource.cpp.
References setStruct(), llvm::dxil::SRV, and llvm::dxil::StructuredBuffer.
Texture2DMS()
ResourceInfo ResourceInfo::Texture2DMS (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount) static
Definition at line 224 of file DXILResource.cpp.
References setMultiSample(), setTyped(), llvm::dxil::SRV, and llvm::dxil::Texture2DMS.
Texture2DMSArray()
ResourceInfo ResourceInfo::Texture2DMSArray (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, uint32_t SampleCount) static
Definition at line 234 of file DXILResource.cpp.
References setMultiSample(), setTyped(), llvm::dxil::SRV, and llvm::dxil::Texture2DMSArray.
UAV()
ResourceInfo ResourceInfo::UAV (Value * Symbol, StringRef Name, dxil::ElementType ElementTy, uint32_t ElementCount, bool GloballyCoherent, bool IsROV, dxil::ResourceKind Kind) static
Definition at line 245 of file DXILResource.cpp.
References assert(), isMultiSample(), isStruct(), isTyped(), setTyped(), setUAV(), and llvm::dxil::UAV.
Member Data Documentation
CBufferSize
uint32_t llvm::dxil::ResourceInfo::CBufferSize
Definition at line 126 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), operator<(), operator==(), print(), and setCBuffer().
Feedback
FeedbackInfo llvm::dxil::ResourceInfo::Feedback
Definition at line 134 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), operator<(), operator==(), print(), and setFeedback().
SamplerTy
dxil::SamplerType llvm::dxil::ResourceInfo::SamplerTy
Definition at line 127 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), operator<(), operator==(), print(), Sampler(), and setSampler().
Struct
StructInfo llvm::dxil::ResourceInfo::Struct
Definition at line 132 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), operator<(), operator==(), print(), and setStruct().
Typed
TypedInfo llvm::dxil::ResourceInfo::Typed
Definition at line 133 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), getTyped(), operator<(), operator==(), print(), and setTyped().
UAVFlags
UAVInfo llvm::dxil::ResourceInfo::UAVFlags
Definition at line 125 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), getUAV(), operator<(), operator==(), print(), and setUAV().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp