LLVM: PredicatorStrategy Class Reference
PredicatorStrategy Class Reference
Public Member Functions
PredicatorStrategy (const TargetInstrInfo *TII)
bool canPredicateInstr (const MachineInstr &I) override
void predicateBlock (MachineBasicBlock *MBB, ArrayRef< MachineOperand > Cond, bool Reverse) override
~PredicatorStrategy () override=default
Detailed Description
Definition at line 1097 of file EarlyIfConversion.cpp.
Constructor & Destructor Documentation
PredicatorStrategy()
PredicatorStrategy::PredicatorStrategy (const TargetInstrInfo * TII) inline
Definition at line 1101 of file EarlyIfConversion.cpp.
~PredicatorStrategy()
PredicatorStrategy::~PredicatorStrategy () override default
Member Function Documentation
canPredicateInstr()
bool PredicatorStrategy::canPredicateInstr (const MachineInstr & I) inline override
Definition at line 1103 of file EarlyIfConversion.cpp.
References llvm::dbgs(), I, llvm::HexagonInstrInfo::isPredicable(), llvm::HexagonInstrInfo::isPredicated(), LLVM_DEBUG, and TII.
predicateBlock()
void PredicatorStrategy::predicateBlock (MachineBasicBlock * MBB, ArrayRef< MachineOperand > Cond, bool Reverse) inline override
Definition at line 1118 of file EarlyIfConversion.cpp.
References assert(), llvm::MachineBasicBlock::begin(), Cond, llvm::MachineBasicBlock::getFirstTerminator(), I, MBB, llvm::HexagonInstrInfo::PredicateInstruction(), llvm::Reverse, llvm::HexagonInstrInfo::reverseBranchCondition(), and TII.
The documentation for this class was generated from the following file:
lib/CodeGen/EarlyIfConversion.cpp