LLVM: llvm::sandboxir::Interval< T > Class Template Reference
llvm::sandboxir::Interval< T > Class Template Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Interval.h"
Public Types
using iterator = IntervalIterator<T, Interval>
using const_iterator = IntervalIterator<const T, const Interval>
Public Member Functions
Interval ()
Interval (T *From, T *To)
Interval (ArrayRef< T * > Elems)
bool empty () const
bool contains (T *I) const
T * top () const
T * bottom () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool operator== (const Interval &Other) const
Equality.
bool operator!= (const Interval &Other) const
Inequality.
bool disjoint (const Interval &Other) const
\Returns true if this and Other have nothing in common.
Interval intersection (const Interval &Other) const
\Returns the intersection between this and Other.
SmallVector< Interval, 2 > operator- (const Interval &Other)
Difference operation. This returns up to two intervals.
Detailed Description
template<typename T>
class llvm::sandboxir::Interval< T >
Definition at line 75 of file Interval.h.
Member Typedef Documentation
const_iterator
template<typename T > using llvm::sandboxir::Interval< T >::const_iterator = IntervalIterator<const T, const Interval>
Definition at line 112 of file Interval.h.
iterator
template<typename T > using llvm::sandboxir::Interval< T >::iterator = IntervalIterator<T, Interval>
Definition at line 111 of file Interval.h.
Constructor & Destructor Documentation
Interval() [1/3]
template<typename T > llvm::sandboxir::Interval< T >::Interval () inline
Definition at line 80 of file Interval.h.
References From.
Referenced by llvm::sandboxir::Interval< T >::intersection(), and llvm::sandboxir::Interval< T >::operator-().
Interval() [2/3]
template<typename T > llvm::sandboxir::Interval< T >::Interval (T * From, T * To) inline
Definition at line 81 of file Interval.h.
References assert(), and From.
Interval() [3/3]
template<typename T > llvm::sandboxir::Interval< T >::Interval (ArrayRef< T * > Elems) inline
Definition at line 85 of file Interval.h.
References assert(), llvm::drop_begin(), llvm::ArrayRef< T >::empty(), From, and I.
Member Function Documentation
begin() [1/2]
template<typename T > iterator llvm::sandboxir::Interval< T >::begin () inline
Definition at line 113 of file Interval.h.
References From.
begin() [2/2]
template<typename T > const_iterator llvm::sandboxir::Interval< T >::begin () const inline
Definition at line 117 of file Interval.h.
References From.
bottom()
template<typename T > T * llvm::sandboxir::Interval< T >::bottom () const inline
Definition at line 109 of file Interval.h.
Referenced by llvm::sandboxir::DependencyGraph::extend().
contains()
template<typename T > bool llvm::sandboxir::Interval< T >::contains (T * I) const inline
Definition at line 102 of file Interval.h.
References llvm::sandboxir::Interval< T >::empty(), From, and I.
disjoint()
template<typename T > bool llvm::sandboxir::Interval< T >::disjoint (const Interval< T > & Other) const inline
\Returns true if this and Other have nothing in common.
Definition at line 128 of file Interval.h.
References llvm::sandboxir::Interval< T >::empty(), From, and llvm::Other.
Referenced by llvm::sandboxir::Interval< T >::operator-().
empty()
template<typename T > bool llvm::sandboxir::Interval< T >::empty () const inline
Definition at line 96 of file Interval.h.
References assert(), and From.
Referenced by llvm::sandboxir::Interval< T >::contains(), llvm::sandboxir::Interval< T >::disjoint(), and llvm::sandboxir::Interval< T >::intersection().
end() [1/2]
template<typename T > iterator llvm::sandboxir::Interval< T >::end () inline
Definition at line 114 of file Interval.h.
end() [2/2]
template<typename T > const_iterator llvm::sandboxir::Interval< T >::end () const inline
Definition at line 118 of file Interval.h.
intersection()
template<typename T > Interval llvm::sandboxir::Interval< T >::intersection (const Interval< T > & Other) const inline
\Returns the intersection between this and Other.
Definition at line 140 of file Interval.h.
References llvm::sandboxir::Interval< T >::empty(), From, llvm::sandboxir::Interval< T >::Interval(), and llvm::Other.
Referenced by llvm::sandboxir::Interval< T >::operator-().
operator!=()
template<typename T > bool llvm::sandboxir::Interval< T >::operator!= (const Interval< T > & Other) const inline
Inequality.
Definition at line 126 of file Interval.h.
References llvm::Other.
operator-()
template<typename T > SmallVector< Interval, 2 > llvm::sandboxir::Interval< T >::operator- (const Interval< T > & Other) inline
Difference operation. This returns up to two intervals.
Definition at line 162 of file Interval.h.
References llvm::sandboxir::Interval< T >::disjoint(), From, llvm::sandboxir::Interval< T >::intersection(), llvm::sandboxir::Interval< T >::Interval(), and llvm::Other.
operator==()
template<typename T > bool llvm::sandboxir::Interval< T >::operator== (const Interval< T > & Other) const inline
Equality.
Definition at line 122 of file Interval.h.
References From, and llvm::Other.
top()
template<typename T > T * llvm::sandboxir::Interval< T >::top () const inline
Definition at line 108 of file Interval.h.
References From.
Referenced by llvm::sandboxir::DependencyGraph::extend().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Interval.h