LLVM: llvm::jitlink::JITLinkerBase Class Reference
llvm::jitlink::JITLinkerBase Class Reference abstract
Base class for a JIT linker.
#include "ExecutionEngine/JITLink/JITLinkGeneric.h"
Public Member Functions
JITLinkerBase (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration Passes)
virtual ~JITLinkerBase ()
Protected Types
using InFlightAlloc = JITLinkMemoryManager::InFlightAlloc
using AllocResult = Expected<std::unique_ptr<InFlightAlloc>>
using FinalizeResult = Expected<JITLinkMemoryManager::FinalizedAlloc>
Protected Member Functions
LinkGraph & getGraph ()
bool shouldAddDefaultTargetPasses (const Triple &TT)
PassConfiguration & getPassConfig ()
void linkPhase1 (std::unique_ptr< JITLinkerBase > Self)
void linkPhase2 (std::unique_ptr< JITLinkerBase > Self, AllocResult AR)
void linkPhase3 (std::unique_ptr< JITLinkerBase > Self, Expected< AsyncLookupResult > LookupResult)
void linkPhase4 (std::unique_ptr< JITLinkerBase > Self, FinalizeResult FR)
Detailed Description
Base class for a JIT linker.
A JITLinkerBase instance links one object file into an ongoing JIT session. Symbol resolution and finalization operations are pluggable, and called using continuation passing (passing a continuation for the remaining linker work) to allow them to be performed asynchronously.
Definition at line 29 of file JITLinkGeneric.h.
Member Typedef Documentation
AllocResult
using llvm::jitlink::JITLinkerBase::AllocResult = Expected<std::unique_ptr<InFlightAlloc>> protected
Definition at line 42 of file JITLinkGeneric.h.
FinalizeResult
using llvm::jitlink::JITLinkerBase::FinalizeResult = Expected<JITLinkMemoryManager::FinalizedAlloc> protected
Definition at line 43 of file JITLinkGeneric.h.
InFlightAlloc
using llvm::jitlink::JITLinkerBase::InFlightAlloc = JITLinkMemoryManager::InFlightAlloc protected
Definition at line 41 of file JITLinkGeneric.h.
Constructor & Destructor Documentation
JITLinkerBase()
llvm::jitlink::JITLinkerBase::JITLinkerBase (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration Passes) inline
Definition at line 31 of file JITLinkGeneric.h.
References assert(), G, and Passes.
~JITLinkerBase()
llvm::jitlink::JITLinkerBase::~JITLinkerBase () virtual default
Member Function Documentation
getGraph()
LinkGraph & llvm::jitlink::JITLinkerBase::getGraph () inline protected
Definition at line 46 of file JITLinkGeneric.h.
Referenced by llvm::jitlink::ELFJITLinker_x86_64::ELFJITLinker_x86_64().
getPassConfig()
PassConfiguration & llvm::jitlink::JITLinkerBase::getPassConfig () inline protected
Definition at line 59 of file JITLinkGeneric.h.
Referenced by llvm::jitlink::ELFJITLinker_i386::ELFJITLinker_i386(), llvm::jitlink::ELFJITLinker_ppc64< Endianness >::ELFJITLinker_ppc64(), llvm::jitlink::ELFJITLinker_riscv::ELFJITLinker_riscv(), and llvm::jitlink::ELFJITLinker_x86_64::ELFJITLinker_x86_64().
linkPhase1()
void llvm::jitlink::JITLinkerBase::linkPhase1 (std::unique_ptr< JITLinkerBase > Self) protected
Definition at line 25 of file JITLinkGeneric.cpp.
References llvm::all_of(), llvm::dbgs(), linkPhase2(), LLVM_DEBUG, llvm::jitlink::PassConfiguration::PostPrunePasses, llvm::jitlink::PassConfiguration::PrePrunePasses, and llvm::jitlink::prune().
linkPhase2()
void llvm::jitlink::JITLinkerBase::linkPhase2 (std::unique_ptr< JITLinkerBase > Self, AllocResult AR) protected
Definition at line 70 of file JITLinkGeneric.cpp.
References llvm::jitlink::createLookupContinuation(), llvm::dbgs(), LLVM_DEBUG, llvm::jitlink::PassConfiguration::PostAllocationPasses, and llvm::Expected< T >::takeError().
Referenced by linkPhase1().
linkPhase3()
void llvm::jitlink::JITLinkerBase::linkPhase3 (std::unique_ptr< JITLinkerBase > Self, Expected< AsyncLookupResult > LookupResult) protected
Definition at line 134 of file JITLinkGeneric.cpp.
References llvm::dbgs(), linkPhase4(), LLVM_DEBUG, llvm::jitlink::PassConfiguration::PostFixupPasses, llvm::jitlink::PassConfiguration::PreFixupPasses, and llvm::Expected< T >::takeError().
linkPhase4()
void llvm::jitlink::JITLinkerBase::linkPhase4 (std::unique_ptr< JITLinkerBase > Self, FinalizeResult FR) protected
Definition at line 189 of file JITLinkGeneric.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::Expected< T >::takeError().
Referenced by linkPhase3().
shouldAddDefaultTargetPasses()
bool llvm::jitlink::JITLinkerBase::shouldAddDefaultTargetPasses (const Triple & TT) inline protected
Definition at line 51 of file JITLinkGeneric.h.
Referenced by llvm::jitlink::ELFJITLinker_x86_64::ELFJITLinker_x86_64().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/JITLinkGeneric.h
lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp