LLVM: llvm::ConstantFPRange Class Reference
llvm::ConstantFPRange Class Reference
This class represents a range of floating-point values.
#include "llvm/IR/ConstantFPRange.h"
Public Member Functions
ConstantFPRange (const APFloat &Value)
Initialize a range to hold the single specified value.
ConstantFPRange (APFloat LowerVal, APFloat UpperVal, bool MayBeQNaN, bool MayBeSNaN)
Initialize a range of values explicitly.
bool fcmp (FCmpInst::Predicate Pred, const ConstantFPRange &Other) const
Does the predicate Pred hold between ranges this and Other? NOTE: false does not mean that inverse predicate holds!
const APFloat & getLower () const
Return the lower value for this range.
const APFloat & getUpper () const
Return the upper value for this range.
bool containsNaN () const
bool containsQNaN () const
bool containsSNaN () const
const fltSemantics & getSemantics () const
Get the semantics of this ConstantFPRange.
bool isFullSet () const
Return true if this set contains all of the elements possible for this data-type.
bool isEmptySet () const
Return true if this set contains no members.
bool contains (const APFloat &Val) const
Return true if the specified value is in the set.
bool contains (const ConstantFPRange &CR) const
Return true if the other range is a subset of this one.
const APFloat * getSingleElement () const
If this set contains a single element, return it, otherwise return null.
bool isSingleElement () const
Return true if this set contains exactly one member.
std::optional< bool > getSignBit () const
Return true if the sign bit of all values in this range is 1.
bool operator== (const ConstantFPRange &CR) const
Return true if this range is equal to another range.
bool operator!= (const ConstantFPRange &CR) const
Return true if this range is not equal to another range.
FPClassTest classify () const
Return the FPClassTest which will return true for the value.
void print (raw_ostream &OS) const
Print out the bounds to a stream.
void dump () const
Allow printing from a debugger easily.
ConstantFPRange intersectWith (const ConstantFPRange &CR) const
Return the range that results from the intersection of this range with another range.
ConstantFPRange unionWith (const ConstantFPRange &CR) const
Return the range that results from the union of this range with another range.
Static Public Member Functions
static ConstantFPRange getEmpty (const fltSemantics &Sem)
Create empty constant range with the given semantics.
static ConstantFPRange getFull (const fltSemantics &Sem)
Create full constant range with the given semantics.
static ConstantFPRange getFinite (const fltSemantics &Sem)
Helper for (-inf, inf) to represent all finite values.
static ConstantFPRange getNonNaN (APFloat LowerVal, APFloat UpperVal)
Create a range which doesn't contain NaNs.
static ConstantFPRange getMayBeNaN (APFloat LowerVal, APFloat UpperVal)
Create a range which may contain NaNs.
static ConstantFPRange getNaNOnly (const fltSemantics &Sem, bool MayBeQNaN, bool MayBeSNaN)
Create a range which only contains NaNs.
static ConstantFPRange makeAllowedFCmpRegion (FCmpInst::Predicate Pred, const ConstantFPRange &Other)
Produce the smallest range such that all values that may satisfy the given predicate with any value contained within Other is contained in the returned range.
static ConstantFPRange makeSatisfyingFCmpRegion (FCmpInst::Predicate Pred, const ConstantFPRange &Other)
Produce the largest range such that all values in the returned range satisfy the given predicate with all values contained within Other.
static ConstantFPRange makeExactFCmpRegion (FCmpInst::Predicate Pred, const APFloat &Other)
Produce the exact range such that all values in the returned range satisfy the given predicate with any value contained within Other.
Detailed Description
This class represents a range of floating-point values.
Definition at line 36 of file ConstantFPRange.h.
Constructor & Destructor Documentation
ConstantFPRange() [1/2]
ConstantFPRange::ConstantFPRange (const APFloat & Value) explicit
Initialize a range to hold the single specified value.
Definition at line 45 of file ConstantFPRange.cpp.
ConstantFPRange() [2/2]
ConstantFPRange::ConstantFPRange (APFloat LowerVal, APFloat UpperVal, bool MayBeQNaN, bool MayBeSNaN)
Initialize a range of values explicitly.
Note: If LowerVal is greater than UpperVal, please use the canonical form [Inf, -Inf].
Definition at line 83 of file ConstantFPRange.cpp.
References assert(), llvm::APFloat::getSemantics(), and isNonCanonicalEmptySet().
Member Function Documentation
classify()
FPClassTest ConstantFPRange::classify () const
Return the FPClassTest which will return true for the value.
Definition at line 182 of file ConstantFPRange.cpp.
References assert(), llvm::APFloat::classify(), llvm::fcNone, llvm::fcQNan, llvm::fcSNan, and I.
contains() [1/2]
bool ConstantFPRange::contains (const APFloat & Val) const
Return true if the specified value is in the set.
Definition at line 140 of file ConstantFPRange.cpp.
References assert(), llvm::APFloatBase::cmpGreaterThan, llvm::APFloat::getSemantics(), getSemantics(), llvm::APFloat::isNaN(), llvm::APFloat::isSignaling(), and strictCompare().
Referenced by fcmp().
contains() [2/2]
bool ConstantFPRange::contains (const ConstantFPRange & CR) const
Return true if the other range is a subset of this one.
Definition at line 150 of file ConstantFPRange.cpp.
References assert(), llvm::APFloatBase::cmpGreaterThan, getSemantics(), and strictCompare().
containsNaN()
bool llvm::ConstantFPRange::containsNaN () const inline
Definition at line 139 of file ConstantFPRange.h.
containsQNaN()
bool llvm::ConstantFPRange::containsQNaN () const inline
Definition at line 140 of file ConstantFPRange.h.
containsSNaN()
bool llvm::ConstantFPRange::containsSNaN () const inline
Definition at line 141 of file ConstantFPRange.h.
dump()
LLVM_DUMP_METHOD void ConstantFPRange::dump () const
Allow printing from a debugger easily.
Definition at line 222 of file ConstantFPRange.cpp.
References llvm::dbgs(), and print().
fcmp()
bool ConstantFPRange::fcmp (FCmpInst::Predicate Pred, const ConstantFPRange & Other) const
Does the predicate Pred hold between ranges this and Other? NOTE: false does not mean that inverse predicate holds!
Definition at line 125 of file ConstantFPRange.cpp.
References contains(), makeSatisfyingFCmpRegion(), and llvm::Other.
getEmpty()
static ConstantFPRange llvm::ConstantFPRange::getEmpty (const fltSemantics & Sem) inline static
Create empty constant range with the given semantics.
Definition at line 69 of file ConstantFPRange.h.
getFinite()
ConstantFPRange ConstantFPRange::getFinite (const fltSemantics & Sem) static
Helper for (-inf, inf) to represent all finite values.
Definition at line 93 of file ConstantFPRange.cpp.
References llvm::APFloat::getLargest().
getFull()
static ConstantFPRange llvm::ConstantFPRange::getFull (const fltSemantics & Sem) inline static
Create full constant range with the given semantics.
Definition at line 74 of file ConstantFPRange.h.
getLower()
const APFloat & llvm::ConstantFPRange::getLower () const inline
Return the lower value for this range.
Definition at line 134 of file ConstantFPRange.h.
getMayBeNaN()
static ConstantFPRange llvm::ConstantFPRange::getMayBeNaN (APFloat LowerVal, APFloat UpperVal) inline static
Create a range which may contain NaNs.
Definition at line 88 of file ConstantFPRange.h.
getNaNOnly()
ConstantFPRange ConstantFPRange::getNaNOnly (const fltSemantics & Sem, bool MayBeQNaN, bool MayBeSNaN) static
Create a range which only contains NaNs.
Definition at line 99 of file ConstantFPRange.cpp.
References llvm::APFloat::getInf().
getNonNaN()
static ConstantFPRange llvm::ConstantFPRange::getNonNaN (APFloat LowerVal, APFloat UpperVal) inline static
Create a range which doesn't contain NaNs.
Definition at line 82 of file ConstantFPRange.h.
getSemantics()
const fltSemantics & llvm::ConstantFPRange::getSemantics () const inline
Get the semantics of this ConstantFPRange.
Definition at line 144 of file ConstantFPRange.h.
Referenced by contains(), contains(), intersectWith(), and unionWith().
getSignBit()
std::optional< bool > ConstantFPRange::getSignBit () const
Return true if the sign bit of all values in this range is 1.
Return false if the sign bit of all values in this range is 0. Otherwise, return std::nullopt.
Definition at line 170 of file ConstantFPRange.cpp.
References llvm::APFloat::isNegative().
getSingleElement()
const APFloat * ConstantFPRange::getSingleElement () const
If this set contains a single element, return it, otherwise return null.
Definition at line 164 of file ConstantFPRange.cpp.
References llvm::APFloat::bitwiseIsEqual().
getUpper()
const APFloat & llvm::ConstantFPRange::getUpper () const inline
Return the upper value for this range.
Definition at line 137 of file ConstantFPRange.h.
References llvm::Upper.
intersectWith()
ConstantFPRange ConstantFPRange::intersectWith (const ConstantFPRange & CR) const
Return the range that results from the intersection of this range with another range.
Definition at line 226 of file ConstantFPRange.cpp.
References assert(), canonicalizeRange(), getSemantics(), llvm::maxnum(), and llvm::minnum().
isEmptySet()
bool ConstantFPRange::isEmptySet () const
Return true if this set contains no members.
Definition at line 135 of file ConstantFPRange.cpp.
References llvm::APFloat::isNegInfinity(), and llvm::APFloat::isPosInfinity().
Referenced by print().
isFullSet()
bool ConstantFPRange::isFullSet () const
Return true if this set contains all of the elements possible for this data-type.
Definition at line 130 of file ConstantFPRange.cpp.
References llvm::APFloat::isNegInfinity(), and llvm::APFloat::isPosInfinity().
Referenced by print().
isSingleElement()
bool llvm::ConstantFPRange::isSingleElement () const inline
Return true if this set contains exactly one member.
Definition at line 163 of file ConstantFPRange.h.
makeAllowedFCmpRegion()
ConstantFPRange ConstantFPRange::makeAllowedFCmpRegion (FCmpInst::Predicate Pred, const ConstantFPRange & Other) static
Produce the smallest range such that all values that may satisfy the given predicate with any value contained within Other is contained in the returned range.
Formally, this returns a superset of 'union over all y in Other . { x : fcmp op x y is true }'. If the exact answer is not representable as a ConstantFPRange, the return value will be a proper superset of the above.
Example: Pred = ole and Other = float [2, 5] returns Result = [-inf, 5]
Definition at line 107 of file ConstantFPRange.cpp.
References llvm::Other.
Referenced by makeExactFCmpRegion().
makeExactFCmpRegion()
ConstantFPRange ConstantFPRange::makeExactFCmpRegion (FCmpInst::Predicate Pred, const APFloat & Other) static
Produce the exact range such that all values in the returned range satisfy the given predicate with any value contained within Other.
Formally, this returns the exact answer when the superset of 'union over all y in Other is exactly same as the subset of intersection over all y in Other. { x : fcmp op x y is true}'.
Example: Pred = olt and Other = float 3 returns [-inf, 3)
Definition at line 120 of file ConstantFPRange.cpp.
References makeAllowedFCmpRegion(), and llvm::Other.
makeSatisfyingFCmpRegion()
ConstantFPRange ConstantFPRange::makeSatisfyingFCmpRegion (FCmpInst::Predicate Pred, const ConstantFPRange & Other) static
Produce the largest range such that all values in the returned range satisfy the given predicate with all values contained within Other.
Formally, this returns a subset of 'intersection over all y in Other . { x : fcmp op x y is true }'. If the exact answer is not representable as a ConstantFPRange, the return value will be a proper subset of the above.
Example: Pred = ole and Other = float [2, 5] returns [-inf, 2]
Definition at line 114 of file ConstantFPRange.cpp.
References llvm::Other.
Referenced by fcmp().
operator!=()
bool llvm::ConstantFPRange::operator!= (const ConstantFPRange & CR) const inline
Return true if this range is not equal to another range.
Definition at line 173 of file ConstantFPRange.h.
References operator==().
operator==()
bool ConstantFPRange::operator== (const ConstantFPRange & CR) const
Return true if this range is equal to another range.
Definition at line 176 of file ConstantFPRange.cpp.
References llvm::APFloat::bitwiseIsEqual().
print()
void ConstantFPRange::print (raw_ostream & OS) const
Print out the bounds to a stream.
Definition at line 198 of file ConstantFPRange.cpp.
References isEmptySet(), isFullSet(), and OS.
Referenced by dump(), and llvm::operator<<().
unionWith()
ConstantFPRange ConstantFPRange::unionWith (const ConstantFPRange & CR) const
Return the range that results from the union of this range with another range.
The resultant range is guaranteed to include the elements of both sets, but may contain more.
Definition at line 236 of file ConstantFPRange.cpp.
References assert(), getSemantics(), llvm::maxnum(), and llvm::minnum().
The documentation for this class was generated from the following files:
include/llvm/IR/ConstantFPRange.h
lib/IR/ConstantFPRange.cpp