LLVM: llvm::sandboxir::DependencyGraph Class Reference
llvm::sandboxir::DependencyGraph Class Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Public Member Functions
DependencyGraph ()
DGNode * getNode (Instruction *I) const
DGNode * getOrCreateNode (Instruction *I)
Interval< Instruction > extend (ArrayRef< Instruction * > Instrs)
Build/extend the dependency graph such that it includes Instrs.
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 69 of file DependencyGraph.h.
Constructor & Destructor Documentation
DependencyGraph()
llvm::sandboxir::DependencyGraph::DependencyGraph () inline
Definition at line 74 of file DependencyGraph.h.
Member Function Documentation
dump()
void DependencyGraph::dump () const
Definition at line 66 of file DependencyGraph.cpp.
References llvm::dbgs(), and print().
extend()
Interval< Instruction > DependencyGraph::extend (ArrayRef< Instruction * > Instrs)
Build/extend the dependency graph such that it includes Instrs.
Returns the interval spanning Instrs.
Definition at line 34 of file DependencyGraph.cpp.
References llvm::sandboxir::Interval< T >::bottom(), llvm::ArrayRef< T >::empty(), llvm::sandboxir::Instruction::getNextNode(), getOrCreateNode(), I, N, and llvm::sandboxir::Interval< T >::top().
getNode()
DGNode * llvm::sandboxir::DependencyGraph::getNode (Instruction * I) const inline
Definition at line 76 of file DependencyGraph.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
getOrCreateNode()
DGNode * llvm::sandboxir::DependencyGraph::getOrCreateNode (Instruction * I) inline
Definition at line 80 of file DependencyGraph.h.
References I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by extend().
print()
void DependencyGraph::print (raw_ostream & OS) const
Definition at line 52 of file DependencyGraph.cpp.
References llvm::sandboxir::Instruction::comesBefore(), llvm::sandboxir::DGNode::getInstruction(), N, OS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::sort().
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp