LLVM: llvm::VPUser Class Reference
llvm::VPUser Class Reference
This class augments VPValue with operands which provide the inverse def-use edges from VPValue's users to their defs.
#include "Transforms/Vectorize/VPlanValue.h"
Public Types
enum class VPUserID { Recipe , LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Member Functions
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstLaneUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Protected Member Functions
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Detailed Description
This class augments VPValue with operands which provide the inverse def-use edges from VPValue's users to their defs.
Definition at line 200 of file VPlanValue.h.
Member Typedef Documentation
const_operand_iterator
SmallVectorImpl<VPValue*>::const_iterator llvm::VPUser::const_operand_iterator
Definition at line 262 of file VPlanValue.h.
const_operand_range
iterator_range<const_operand_iterator> llvm::VPUser::const_operand_range
Definition at line 264 of file VPlanValue.h.
operand_iterator
SmallVectorImpl<VPValue*>::iterator llvm::VPUser::operand_iterator
Definition at line 261 of file VPlanValue.h.
operand_range
iterator_range<operand_iterator> llvm::VPUser::operand_range
Definition at line 263 of file VPlanValue.h.
Member Enumeration Documentation
VPUserID
enum class llvm::VPUser::VPUserID strong
Subclass identifier (for isa/dyn_cast).
Enumerator
Recipe
LiveOut
Definition at line 203 of file VPlanValue.h.
Constructor & Destructor Documentation
VPUser() [1/5]
llvm::VPUser::VPUser (ArrayRef< VPValue * > Operands, VPUserID ID) inline protected
Definition at line 219 of file VPlanValue.h.
References addOperand(), and Operands.
VPUser() [2/5]
llvm::VPUser::VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID) inline protected
Definition at line 224 of file VPlanValue.h.
References Operands.
VPUser() [3/5]
template<typename IterT > llvm::VPUser::VPUser (iterator_range< IterT > Operands, VPUserID ID) inline protected
Definition at line 228 of file VPlanValue.h.
References addOperand(), and Operands.
VPUser() [4/5]
llvm::VPUser::VPUser () delete
VPUser() [5/5]
llvm::VPUser::VPUser (const VPUser &) delete
~VPUser()
virtual llvm::VPUser::~VPUser () inline virtual
Definition at line 237 of file VPlanValue.h.
References operands().
Member Function Documentation
addOperand()
void llvm::VPUser::addOperand (VPValue * Operand) inline
Definition at line 244 of file VPlanValue.h.
References llvm::VPValue::addUser(), and Operands.
Referenced by llvm::VPWidenPHIRecipe::addIncoming(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPWidenMemoryRecipe::setMask(), llvm::VPReductionRecipe::VPReductionRecipe(), VPUser(), VPUser(), and llvm::VPWidenPHIRecipe::VPWidenPHIRecipe().
getNumOperands()
unsigned llvm::VPUser::getNumOperands () const inline
Definition at line 249 of file VPlanValue.h.
References Operands.
Referenced by llvm::VPWidenCallRecipe::arg_operands(), llvm::VPWidenCallRecipe::arg_operands(), llvm::VPActiveLaneMaskPHIRecipe::clone(), llvm::VPWidenCallRecipe::computeCost(), llvm::VPIRInstruction::execute(), llvm::VPWidenEVLRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::VPWidenCallRecipe::getCalledScalarFunction(), llvm::VPReductionRecipe::getCondOp(), llvm::VPWidenEVLRecipe::getEVL(), llvm::VPWidenEVLRecipe::getEVL(), llvm::VPWidenIntOrFpInductionRecipe::getLastUnrolledPartOperand(), llvm::VPBranchOnMaskRecipe::getMask(), llvm::VPHistogramRecipe::getMask(), llvm::VPInterleaveRecipe::getMask(), llvm::VPReplicateRecipe::getMask(), llvm::VPWidenMemoryRecipe::getMask(), llvm::VPBlendRecipe::getNumIncomingValues(), llvm::VPInterleaveRecipe::getNumStoreOperands(), llvm::VPWidenIntOrFpInductionRecipe::getSplatVFValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPInterleaveRecipe::getStoredValues(), llvm::VPBlendRecipe::isNormalized(), llvm::VPVectorPointerRecipe::onlyFirstPartUsed(), llvm::VPIRInstruction::print(), llvm::VPReplicateRecipe::print(), llvm::VPWidenGEPRecipe::print(), llvm::VPWidenPHIRecipe::print(), llvm::VPWidenPointerInductionRecipe::print(), and llvm::VPRecipeWithIRFlags::printFlags().
getOperand()
VPValue * llvm::VPUser::getOperand (unsigned N) const inline
Definition at line 250 of file VPlanValue.h.
References assert(), N, and Operands.
Referenced by llvm::VPActiveLaneMaskPHIRecipe::clone(), llvm::VPBranchOnMaskRecipe::clone(), llvm::VPCanonicalIVPHIRecipe::clone(), llvm::VPDerivedIVRecipe::clone(), llvm::VPFirstOrderRecurrencePHIRecipe::clone(), llvm::VPPredInstPHIRecipe::clone(), llvm::VPReductionPHIRecipe::clone(), llvm::VPScalarCastRecipe::clone(), llvm::VPScalarIVStepsRecipe::clone(), llvm::VPVectorPointerRecipe::clone(), llvm::VPWidenCanonicalIVRecipe::clone(), llvm::VPWidenCastRecipe::clone(), llvm::VPWidenPointerInductionRecipe::clone(), llvm::VPHistogramRecipe::computeCost(), llvm::VPWidenCallRecipe::computeCost(), llvm::VPWidenRecipe::computeCost(), createAndCollectMergePhiForReduction(), llvm::VPActiveLaneMaskPHIRecipe::execute(), llvm::VPDerivedIVRecipe::execute(), llvm::VPEVLBasedIVPHIRecipe::execute(), llvm::VPHistogramRecipe::execute(), llvm::VPIRInstruction::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPScalarIVStepsRecipe::execute(), llvm::VPVectorPointerRecipe::execute(), llvm::VPWidenCanonicalIVRecipe::execute(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenEVLRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenPHIRecipe::execute(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::VPWidenSelectRecipe::execute(), llvm::VPLiveOut::fixPhi(), llvm::VPInterleaveRecipe::getAddr(), llvm::VPWidenMemoryRecipe::getAddr(), llvm::VPHeaderPHIRecipe::getBackedgeValue(), llvm::VPWidenCallRecipe::getCalledScalarFunction(), llvm::VPReductionRecipe::getChainOp(), llvm::VPWidenSelectRecipe::getCond(), llvm::VPReductionRecipe::getCondOp(), llvm::VPReductionEVLRecipe::getEVL(), llvm::VPWidenEVLRecipe::getEVL(), llvm::VPWidenEVLRecipe::getEVL(), llvm::VPWidenLoadEVLRecipe::getEVL(), llvm::VPWidenStoreEVLRecipe::getEVL(), llvm::VPWidenPointerInductionRecipe::getFirstUnrolledPartOperand(), llvm::VPBlendRecipe::getIncomingValue(), llvm::VPWidenPHIRecipe::getIncomingValue(), llvm::VPWidenIntOrFpInductionRecipe::getLastUnrolledPartOperand(), llvm::VPBlendRecipe::getMask(), llvm::VPBranchOnMaskRecipe::getMask(), llvm::VPHistogramRecipe::getMask(), llvm::VPInterleaveRecipe::getMask(), llvm::VPReplicateRecipe::getMask(), llvm::VPWidenMemoryRecipe::getMask(), llvm::VPWidenIntOrFpInductionRecipe::getSplatVFValue(), llvm::VPDerivedIVRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPDerivedIVRecipe::getStepValue(), llvm::VPScalarIVStepsRecipe::getStepValue(), llvm::VPWidenIntOrFpInductionRecipe::getStepValue(), llvm::VPWidenIntOrFpInductionRecipe::getStepValue(), llvm::VPWidenStoreEVLRecipe::getStoredValue(), llvm::VPWidenStoreRecipe::getStoredValue(), llvm::VPReductionRecipe::getVecOp(), llvm::VPWidenIntOrFpInductionRecipe::getVFValue(), llvm::VPWidenIntOrFpInductionRecipe::getVFValue(), llvm::VPDerivedIVRecipe::print(), llvm::VPHistogramRecipe::print(), llvm::VPInterleaveRecipe::print(), llvm::VPLiveOut::print(), llvm::VPWidenPointerInductionRecipe::print(), and llvm::VPWidenSelectRecipe::print().
getVPUserID()
VPUserID llvm::VPUser::getVPUserID () const inline
Definition at line 242 of file VPlanValue.h.
onlyFirstLaneUsed()
virtual bool llvm::VPUser::onlyFirstLaneUsed (const VPValue * Op) const inline virtual
Returns true if the VPUser only uses the first lane of operand Op.
Conservatively returns false.
Reimplemented in llvm::VPBlendRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPInstruction, llvm::VPInterleaveRecipe, llvm::VPReductionEVLRecipe, llvm::VPReplicateRecipe, llvm::VPScalarCastRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenEVLRecipe, llvm::VPWidenLoadEVLRecipe, llvm::VPWidenLoadRecipe, llvm::VPWidenStoreEVLRecipe, and llvm::VPWidenStoreRecipe.
Definition at line 285 of file VPlanValue.h.
References assert(), llvm::is_contained(), and operands().
Referenced by usesScalars().
onlyFirstPartUsed()
virtual bool llvm::VPUser::onlyFirstPartUsed (const VPValue * Op) const inline virtual
Returns true if the VPUser only uses the first part of operand Op.
Conservatively returns false.
Reimplemented in llvm::VPCanonicalIVPHIRecipe, llvm::VPInstruction, llvm::VPLiveOut, and llvm::VPVectorPointerRecipe.
Definition at line 293 of file VPlanValue.h.
References assert(), llvm::is_contained(), and operands().
op_begin() [1/2]
operand_iterator llvm::VPUser::op_begin () inline
Definition at line 266 of file VPlanValue.h.
References Operands.
Referenced by llvm::VPWidenCallRecipe::arg_operands(), llvm::VPWidenCallRecipe::arg_operands(), createReplicateRegion(), llvm::VPInterleaveRecipe::getStoredValues(), operands(), operands(), and llvm::VPReplicateRecipe::print().
op_begin() [2/2]
const_operand_iterator llvm::VPUser::op_begin () const inline
Definition at line 267 of file VPlanValue.h.
References Operands.
op_end() [1/2]
operand_iterator llvm::VPUser::op_end () inline
Definition at line 268 of file VPlanValue.h.
References Operands.
Referenced by createReplicateRegion(), operands(), and operands().
op_end() [2/2]
const_operand_iterator llvm::VPUser::op_end () const inline
Definition at line 269 of file VPlanValue.h.
References Operands.
operands() [1/2]
operand_range llvm::VPUser::operands () inline
Definition at line 270 of file VPlanValue.h.
References op_begin(), and op_end().
Referenced by llvm::VPBlendRecipe::clone(), llvm::VPHistogramRecipe::clone(), llvm::VPInstruction::clone(), llvm::VPIRInstruction::clone(), llvm::VPReplicateRecipe::clone(), llvm::VPWidenCallRecipe::clone(), llvm::VPWidenGEPRecipe::clone(), llvm::VPWidenRecipe::clone(), llvm::VPWidenSelectRecipe::clone(), llvm::collectEphemeralRecipesForVPlan(), llvm::VPWidenCallRecipe::computeCost(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::VPUnrollPartAccessor< 1 >::getUnrollPart(), llvm::VPBlendRecipe::onlyFirstLaneUsed(), llvm::VPCanonicalIVPHIRecipe::onlyFirstLaneUsed(), llvm::VPDerivedIVRecipe::onlyFirstLaneUsed(), llvm::VPEVLBasedIVPHIRecipe::onlyFirstLaneUsed(), llvm::VPInstruction::onlyFirstLaneUsed(), llvm::VPInterleaveRecipe::onlyFirstLaneUsed(), llvm::VPReductionEVLRecipe::onlyFirstLaneUsed(), llvm::VPReplicateRecipe::onlyFirstLaneUsed(), llvm::VPScalarCastRecipe::onlyFirstLaneUsed(), llvm::VPScalarIVStepsRecipe::onlyFirstLaneUsed(), onlyFirstLaneUsed(), llvm::VPVectorPointerRecipe::onlyFirstLaneUsed(), llvm::VPWidenEVLRecipe::onlyFirstLaneUsed(), llvm::VPWidenLoadEVLRecipe::onlyFirstLaneUsed(), llvm::VPWidenLoadRecipe::onlyFirstLaneUsed(), llvm::VPWidenStoreEVLRecipe::onlyFirstLaneUsed(), llvm::VPWidenStoreRecipe::onlyFirstLaneUsed(), llvm::VPCanonicalIVPHIRecipe::onlyFirstPartUsed(), llvm::VPInstruction::onlyFirstPartUsed(), onlyFirstPartUsed(), llvm::VPVectorPointerRecipe::onlyFirstPartUsed(), llvm::InnerLoopVectorizer::scalarizeInstruction(), sinkScalarOperands(), llvm::VPBranchOnMaskRecipe::usesScalars(), llvm::VPIRInstruction::usesScalars(), llvm::VPLiveOut::usesScalars(), llvm::VPPredInstPHIRecipe::usesScalars(), llvm::VPReplicateRecipe::usesScalars(), usesScalars(), and ~VPUser().
operands() [2/2]
const_operand_range llvm::VPUser::operands () const inline
Definition at line 271 of file VPlanValue.h.
References op_begin(), and op_end().
operator=()
VPUser & llvm::VPUser::operator= (const VPUser &) delete
printOperands()
void VPUser::printOperands (raw_ostream & O, VPSlotTracker & SlotTracker) const protected
Print the operands to O.
Definition at line 1493 of file VPlan.cpp.
References llvm::interleaveComma().
Referenced by llvm::VPActiveLaneMaskPHIRecipe::print(), llvm::VPCanonicalIVPHIRecipe::print(), llvm::VPEVLBasedIVPHIRecipe::print(), llvm::VPFirstOrderRecurrencePHIRecipe::print(), llvm::VPInstruction::print(), llvm::VPIRInstruction::print(), llvm::VPPredInstPHIRecipe::print(), llvm::VPReductionPHIRecipe::print(), llvm::VPReplicateRecipe::print(), llvm::VPScalarCastRecipe::print(), llvm::VPScalarIVStepsRecipe::print(), llvm::VPVectorPointerRecipe::print(), llvm::VPWidenCanonicalIVRecipe::print(), llvm::VPWidenCastRecipe::print(), llvm::VPWidenEVLRecipe::print(), llvm::VPWidenGEPRecipe::print(), llvm::VPWidenLoadEVLRecipe::print(), llvm::VPWidenLoadRecipe::print(), llvm::VPWidenPHIRecipe::print(), llvm::VPWidenRecipe::print(), llvm::VPWidenStoreEVLRecipe::print(), and llvm::VPWidenStoreRecipe::print().
setOperand()
void llvm::VPUser::setOperand (unsigned I, VPValue * New) inline
Definition at line 255 of file VPlanValue.h.
References I, and Operands.
Referenced by addLiveOutsForFirstOrderRecurrences(), createReplicateRegion(), and llvm::VPHeaderPHIRecipe::setStartValue().
usesScalars()
virtual bool llvm::VPUser::usesScalars (const VPValue * Op) const inline virtual
Returns true if the VPUser uses scalars of operand Op.
Conservatively returns if only first (scalar) lane is used, as default.
Reimplemented in llvm::VPBranchOnMaskRecipe, llvm::VPIRInstruction, llvm::VPLiveOut, llvm::VPPredInstPHIRecipe, and llvm::VPReplicateRecipe.
Definition at line 277 of file VPlanValue.h.
References assert(), llvm::is_contained(), onlyFirstLaneUsed(), and operands().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp