LLVM: llvm::sandboxir::CatchSwitchAddHandler Class Reference
llvm::sandboxir::CatchSwitchAddHandler Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
CatchSwitchAddHandler (CatchSwitchInst *CSI)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 284 of file Tracker.h.
Constructor & Destructor Documentation
CatchSwitchAddHandler()
CatchSwitchAddHandler::CatchSwitchAddHandler (CatchSwitchInst * CSI)
Definition at line 163 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::CatchSwitchAddHandler::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 291 of file Tracker.h.
dump() [1/2]
LLVM_DUMP_METHOD void llvm::sandboxir::CatchSwitchAddHandler::dump () const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 294 of file Tracker.h.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::CatchSwitchAddHandler::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 293 of file Tracker.h.
References OS.
revert()
void CatchSwitchAddHandler::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 166 of file Tracker.cpp.
References llvm::cast(), and llvm::sandboxir::Value::Val.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp