LLVM: llvm::jitlink::TableManager< TableManagerImplT > Class Template Reference
llvm::jitlink::TableManager< TableManagerImplT > Class Template Reference
A CRTP base for tables that are built on demand, e.g.
#include "llvm/ExecutionEngine/JITLink/TableManager.h"
Public Member Functions
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Detailed Description
template<typename TableManagerImplT>
class llvm::jitlink::TableManager< TableManagerImplT >
A CRTP base for tables that are built on demand, e.g.
Global Offset Tables and Procedure Linkage Tables. The getEntyrForTarget function returns the table entry corresponding to the given target, calling down to the implementation class to build an entry if one does not already exist.
Definition at line 27 of file TableManager.h.
Member Function Documentation
getEntryForTarget()
template<typename TableManagerImplT > Symbol & llvm::jitlink::TableManager< TableManagerImplT >::getEntryForTarget (LinkGraph & G, Symbol & Target) inline
Return the constructed entry.
Use parameter G to construct the entry for target symbol
Definition at line 32 of file TableManager.h.
References assert(), llvm::dbgs(), DEBUG_WITH_TYPE, G, and llvm::Target::getName().
Referenced by llvm::jitlink::aarch64::PLTTableManager::createEntry(), llvm::jitlink::i386::PLTTableManager::createEntry(), llvm::jitlink::loongarch::PLTTableManager::createEntry(), and llvm::jitlink::x86_64::PLTTableManager::createEntry().
registerPreExistingEntry()
template<typename TableManagerImplT > bool llvm::jitlink::TableManager< TableManagerImplT >::registerPreExistingEntry (Symbol & Target, Symbol & Entry) inline
Register a pre-existing entry.
Objects may include pre-existing table entries (e.g. for GOTs). This method can be used to register those entries so that they will not be duplicated by createEntry the first time that getEntryForTarget is called.
Definition at line 61 of file TableManager.h.
References assert(), and llvm::Target::getName().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/TableManager.h