LLVM: llvm::sandboxir::DGNode Class Reference
llvm::sandboxir::DGNode Class Reference
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Public Member Functions
DGNode (Instruction *I)
Instruction * getInstruction () const
void addMemPred (DGNode *PredN)
iterator_range< DenseSet< DGNode * >::const_iterator > memPreds () const
\Returns all memory dependency predecessors.
bool hasMemPred (DGNode *N) const
\Returns true if there is a memory dependency N->this.
bool isMem () const
\Returns true if this may read/write memory, or if it has some ordering constraints, like with stacksave/stackrestore and alloca/inalloca.
void print (raw_ostream &OS, bool PrintDeps=true) const
LLVM_DUMP_METHOD void dump () const
Friends
raw_ostream & operator<< (DGNode &N, raw_ostream &OS)
Detailed Description
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
Definition at line 34 of file DependencyGraph.h.
Constructor & Destructor Documentation
DGNode()
llvm::sandboxir::DGNode::DGNode (Instruction * I) inline
Definition at line 43 of file DependencyGraph.h.
References llvm::cast(), I, and llvm::isa().
Member Function Documentation
addMemPred()
void llvm::sandboxir::DGNode::addMemPred (DGNode * PredN) inline
Definition at line 49 of file DependencyGraph.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
dump()
void DGNode::dump () const
Definition at line 28 of file DependencyGraph.cpp.
References llvm::dbgs(), and print().
getInstruction()
Instruction * llvm::sandboxir::DGNode::getInstruction () const inline
Definition at line 48 of file DependencyGraph.h.
References I.
Referenced by llvm::sandboxir::DependencyGraph::print().
hasMemPred()
bool llvm::sandboxir::DGNode::hasMemPred (DGNode * N) const inline
\Returns true if there is a memory dependency N->this.
Definition at line 55 of file DependencyGraph.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), and N.
isMem()
bool llvm::sandboxir::DGNode::isMem () const inline
\Returns true if this may read/write memory, or if it has some ordering constraints, like with stacksave/stackrestore and alloca/inalloca.
Definition at line 58 of file DependencyGraph.h.
memPreds()
iterator_range< DenseSet< DGNode * >::const_iterator > llvm::sandboxir::DGNode::memPreds () const inline
\Returns all memory dependency predecessors.
Definition at line 51 of file DependencyGraph.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
print()
void DGNode::print (raw_ostream & OS, bool PrintDeps = true) const
Definition at line 15 of file DependencyGraph.cpp.
References llvm::sandboxir::Instruction::dumpOS(), and OS.
Referenced by dump().
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (DGNode & N, raw_ostream & OS) friend
Definition at line 61 of file DependencyGraph.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp