LLVM: llvm::RISCVSubtarget Class Reference
llvm::RISCVSubtarget Class Reference
#include "Target/RISCV/RISCVSubtarget.h"
Public Types
enum RISCVProcFamilyEnum : uint8_t { Others , SiFive7 , VentanaVeyron }
Public Member Functions
RISCVSubtarget (const Triple &TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, unsigned RVVVectorBitsMin, unsigned RVVVectorLMULMax, const TargetMachine &TM)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
const RISCVFrameLowering * getFrameLowering () const override
const RISCVInstrInfo * getInstrInfo () const override
const RISCVRegisterInfo * getRegisterInfo () const override
const RISCVTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool enableMachineScheduler () const override
bool enablePostRAScheduler () const override
Align getPrefFunctionAlignment () const
Align getPrefLoopAlignment () const
RISCVProcFamilyEnum getProcFamily () const
Returns RISC-V processor family.
bool hasStdExtCOrZca () const
bool hasStdExtCOrZcd () const
bool hasStdExtCOrZcfOrZce () const
bool hasStdExtZvl () const
bool hasStdExtFOrZfinx () const
bool hasStdExtDOrZdinx () const
bool hasStdExtZfhOrZhinx () const
bool hasStdExtZfhminOrZhinxmin () const
bool hasHalfFPLoadStoreMove () const
bool hasConditionalMoveFusion () const
bool is64Bit () const
MVT getXLenVT () const
unsigned getXLen () const
unsigned getFLen () const
unsigned getELen () const
unsigned getRealMinVLen () const
unsigned getRealMaxVLen () const
std::optional< unsigned > getRealVLen () const
template<typename Quantity >
Quantity expandVScale (Quantity X) const
If the ElementCount or TypeSize X is scalable and VScale (VLEN) is exactly known, returns X converted to a fixed quantity.
RISCVABI::ABI getTargetABI () const
bool isSoftFPABI () const
bool isRegisterReservedByUser (Register i) const
bool hasVInstructions () const
bool hasVInstructionsI64 () const
bool hasVInstructionsF16Minimal () const
bool hasVInstructionsF16 () const
bool hasVInstructionsBF16Minimal () const
bool hasVInstructionsF32 () const
bool hasVInstructionsF64 () const
bool hasVInstructionsAnyF () const
bool hasVInstructionsFullMultiply () const
unsigned getMaxInterleaveFactor () const
unsigned getDLenFactor () const
const CallLowering * getCallLowering () const override
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RISCVRegisterBankInfo * getRegBankInfo () const override
bool isTargetAndroid () const
bool isTargetFuchsia () const
bool useConstantPoolForLargeInts () const
unsigned getMaxBuildIntsCost () const
unsigned getMaxLMULForFixedLengthVectors () const
bool useRVVForFixedLengthVectors () const
bool enableSubRegLiveness () const override
void getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation > > &Mutations) const override
bool useAA () const override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
unsigned getCacheLineSize () const override
unsigned getPrefetchDistance () const override
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override
unsigned getMaxPrefetchIterationsAhead () const override
unsigned getMinimumJumpTableEntries () const
unsigned getTailDupAggressiveThreshold () const
Protected Member Functions
unsigned getMaxRVVVectorSizeInBits () const
unsigned getMinRVVVectorSizeInBits () const
Protected Attributes
std::unique_ptr< CallLowering > CallLoweringInfo
std::unique_ptr< InstructionSelector > InstSelector
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RISCVRegisterBankInfo > RegBankInfo
Detailed Description
Definition at line 62 of file RISCVSubtarget.h.
Member Enumeration Documentation
RISCVProcFamilyEnum
enum llvm::RISCVSubtarget::RISCVProcFamilyEnum : uint8_t
Enumerator
Others
SiFive7
VentanaVeyron
Definition at line 65 of file RISCVSubtarget.h.
Constructor & Destructor Documentation
RISCVSubtarget()
RISCVSubtarget::RISCVSubtarget (const Triple & TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, unsigned RVVVectorBitsMin, unsigned RVVVectorLMULMax, const TargetMachine & TM)
Definition at line 90 of file RISCVSubtarget.cpp.
Member Function Documentation
enableMachineScheduler()
bool llvm::RISCVSubtarget::enableMachineScheduler () const inline override
Definition at line 125 of file RISCVSubtarget.h.
enablePostRAScheduler()
bool llvm::RISCVSubtarget::enablePostRAScheduler () const inline override
Definition at line 127 of file RISCVSubtarget.h.
enableSubRegLiveness()
bool RISCVSubtarget::enableSubRegLiveness () const override
Definition at line 186 of file RISCVSubtarget.cpp.
expandVScale()
template<typename Quantity > Quantity llvm::RISCVSubtarget::expandVScale (Quantity X) const inline
If the ElementCount or TypeSize X is scalable and VScale (VLEN) is exactly known, returns X converted to a fixed quantity.
Otherwise returns X unmodified.
Definition at line 207 of file RISCVSubtarget.h.
References getRealVLen(), llvm::RISCV::RVVBitsPerBlock, and X.
Referenced by llvm::RISCVDAGToDAGISel::Select().
getCacheLineSize()
unsigned llvm::RISCVSubtarget::getCacheLineSize () const inline override
Definition at line 288 of file RISCVSubtarget.h.
getCallLowering()
const CallLowering * RISCVSubtarget::getCallLowering () const override
Definition at line 101 of file RISCVSubtarget.cpp.
References CallLoweringInfo, and getTargetLowering().
getDLenFactor()
unsigned llvm::RISCVSubtarget::getDLenFactor () const inline
Definition at line 243 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::getLMULCost().
getELen()
unsigned llvm::RISCVSubtarget::getELen () const inline
Definition at line 184 of file RISCVSubtarget.h.
References assert(), hasVInstructions(), and hasVInstructionsI64().
Referenced by combineBinOpOfExtractToReduceTree(), llvm::RISCVTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), getContainerForFixedLengthVector(), llvm::RISCVTTIImpl::getExtendedReductionCost(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::RISCVTargetLowering::getOptimalMemOpType(), llvm::RISCVTTIImpl::getShuffleCost(), getWideningInterleave(), isDeinterleaveShuffle(), isInterleaveShuffle(), lowerBuildVectorOfConstants(), lowerBuildVectorViaPacking(), lowerGetVectorLength(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
getFLen()
unsigned llvm::RISCVSubtarget::getFLen () const inline
Definition at line 175 of file RISCVSubtarget.h.
Referenced by lowerBUILD_VECTOR().
getFrameLowering()
const RISCVFrameLowering * llvm::RISCVSubtarget::getFrameLowering () const inline override
Definition at line 112 of file RISCVSubtarget.h.
getInstrInfo()
const RISCVInstrInfo * llvm::RISCVSubtarget::getInstrInfo () const inline override
Definition at line 115 of file RISCVSubtarget.h.
Referenced by emitFROUND(), EmitLoweredCascadedSelect(), llvm::RISCVFrameLowering::emitPrologue(), emitSelectPseudo(), llvm::RISCVCallLowering::lowerCall(), lowerRISCVVMachineInstrToMCInst(), llvm::RISCVRegisterInfo::lowerVRELOAD(), and llvm::RISCVRegisterInfo::lowerVSPILL().
getInstructionSelector()
InstructionSelector * RISCVSubtarget::getInstructionSelector () const override
Definition at line 107 of file RISCVSubtarget.cpp.
References llvm::createRISCVInstructionSelector(), getRegBankInfo(), llvm::TargetLoweringBase::getTargetMachine(), and InstSelector.
getLegalizerInfo()
const LegalizerInfo * RISCVSubtarget::getLegalizerInfo () const override
Definition at line 116 of file RISCVSubtarget.cpp.
getMaxBuildIntsCost()
unsigned RISCVSubtarget::getMaxBuildIntsCost () const
Definition at line 132 of file RISCVSubtarget.cpp.
References RISCVMaxBuildIntsCost.
Referenced by lowerConstant(), and llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm().
getMaxInterleaveFactor()
unsigned llvm::RISCVSubtarget::getMaxInterleaveFactor () const inline
Definition at line 237 of file RISCVSubtarget.h.
References hasVInstructions().
getMaxLMULForFixedLengthVectors()
unsigned RISCVSubtarget::getMaxLMULForFixedLengthVectors () const
Definition at line 172 of file RISCVSubtarget.cpp.
References assert(), llvm::bit_floor(), llvm::has_single_bit(), hasVInstructions(), and RVVVectorLMULMax.
Referenced by useRVVForFixedLengthVectorVT().
getMaxPrefetchIterationsAhead()
unsigned llvm::RISCVSubtarget::getMaxPrefetchIterationsAhead () const inline override
Definition at line 300 of file RISCVSubtarget.h.
getMaxRVVVectorSizeInBits()
unsigned RISCVSubtarget::getMaxRVVVectorSizeInBits () const protected
Definition at line 143 of file RISCVSubtarget.cpp.
References assert(), hasVInstructions(), and llvm::report_fatal_error().
Referenced by getRealMaxVLen().
getMinimumJumpTableEntries()
unsigned RISCVSubtarget::getMinimumJumpTableEntries () const
Definition at line 197 of file RISCVSubtarget.cpp.
References llvm::RISCVTuneInfoTable::RISCVTuneInfo::MinimumJumpTableEntries, and RISCVMinimumJumpTableEntries.
getMinPrefetchStride()
unsigned llvm::RISCVSubtarget::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline override
Definition at line 294 of file RISCVSubtarget.h.
getMinRVVVectorSizeInBits()
unsigned RISCVSubtarget::getMinRVVVectorSizeInBits () const protected
Definition at line 156 of file RISCVSubtarget.cpp.
References assert(), hasVInstructions(), and llvm::report_fatal_error().
Referenced by getRealMinVLen(), and useRVVForFixedLengthVectors().
getPostRAMutations()
void RISCVSubtarget::getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation > > & Mutations) const override
Definition at line 188 of file RISCVSubtarget.cpp.
References llvm::createMacroFusionDAGMutation().
getPrefetchDistance()
unsigned llvm::RISCVSubtarget::getPrefetchDistance () const inline override
Definition at line 291 of file RISCVSubtarget.h.
getPrefFunctionAlignment()
Align llvm::RISCVSubtarget::getPrefFunctionAlignment () const inline
Definition at line 129 of file RISCVSubtarget.h.
References Align.
Referenced by llvm::RISCVTargetLowering::RISCVTargetLowering().
getPrefLoopAlignment()
Align llvm::RISCVSubtarget::getPrefLoopAlignment () const inline
Definition at line 132 of file RISCVSubtarget.h.
References Align.
Referenced by llvm::RISCVTargetLowering::RISCVTargetLowering().
getProcFamily()
RISCVProcFamilyEnum llvm::RISCVSubtarget::getProcFamily () const inline
Returns RISC-V processor family.
Avoid this function! CPU specifics should be kept local to this class and preferably modeled with SubtargetFeatures or properties in initializeProperties().
Definition at line 140 of file RISCVSubtarget.h.
getRealMaxVLen()
unsigned llvm::RISCVSubtarget::getRealMaxVLen () const inline
Definition at line 192 of file RISCVSubtarget.h.
References getMaxRVVVectorSizeInBits().
Referenced by llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeVLMAXBounds(), llvm::RISCVTTIImpl::getMaxVScale(), getRealVLen(), and llvm::RISCVTTIImpl::getShuffleCost().
getRealMinVLen()
unsigned llvm::RISCVSubtarget::getRealMinVLen () const inline
Definition at line 188 of file RISCVSubtarget.h.
References getMinRVVVectorSizeInBits().
Referenced by llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeVLMAXBounds(), getContainerForFixedLengthVector(), llvm::RISCVTargetLowering::getLMULCost(), llvm::RISCVTargetLowering::getOptimalMemOpType(), getRealVLen(), llvm::RISCVTTIImpl::getRegisterBitWidth(), llvm::RISCVTTIImpl::getRegUsageForType(), llvm::RISCVTTIImpl::getShuffleCost(), getSmallestVTForIndex(), llvm::RISCVTTIImpl::getVScaleForTuning(), llvm::RISCVTargetLowering::isExtractSubvectorCheap(), isValidEGW(), llvm::RISCVTargetLowering::isVScaleKnownToBeAPowerOfTwo(), lowerBuildVectorOfConstants(), llvm::RISCVTargetLowering::LowerOperation(), lowerVECTOR_SHUFFLE(), and useRVVForFixedLengthVectorVT().
getRealVLen()
std::optional< unsigned > llvm::RISCVSubtarget::getRealVLen () const inline
Definition at line 197 of file RISCVSubtarget.h.
References getRealMaxVLen(), and getRealMinVLen().
Referenced by expandVScale(), llvm::RISCVTTIImpl::getVectorInstrCost(), lowerBUILD_VECTOR(), lowerShuffleViaVRegSplitting(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), and llvm::RISCVDAGToDAGISel::selectVSETVLI().
getRegBankInfo()
const RISCVRegisterBankInfo * RISCVSubtarget::getRegBankInfo () const override
Definition at line 122 of file RISCVSubtarget.cpp.
References RegBankInfo.
Referenced by getInstructionSelector(), and llvm::RISCVCallLowering::lowerCall().
getRegisterInfo()
const RISCVRegisterInfo * llvm::RISCVSubtarget::getRegisterInfo () const inline override
Definition at line 116 of file RISCVSubtarget.h.
Referenced by llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysRegVector(), llvm::RISCVFrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVTargetLowering::getRegisterByName(), llvm::RISCVFrameLowering::hasBP(), isConvertibleToVMV_V_V(), llvm::RISCVTargetLowering::LowerCall(), llvm::RISCVCallLowering::lowerCall(), lowerRISCVVMachineInstrToMCInst(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and llvm::RISCVDAGToDAGISel::Select().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::RISCVSubtarget::getSelectionDAGInfo () const inline override
Definition at line 122 of file RISCVSubtarget.h.
getTailDupAggressiveThreshold()
unsigned llvm::RISCVSubtarget::getTailDupAggressiveThreshold () const inline
Definition at line 306 of file RISCVSubtarget.h.
Referenced by llvm::RISCVInstrInfo::getTailDuplicateSize().
getTargetABI()
RISCVABI::ABI llvm::RISCVSubtarget::getTargetABI () const inline
Definition at line 215 of file RISCVSubtarget.h.
Referenced by llvm::CC_RISCV(), llvm::CC_RISCV_FastCC(), CC_RISCVAssign2XLen(), llvm::RISCVTargetLowering::LowerFormalArguments(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
getTargetLowering()
const RISCVTargetLowering * llvm::RISCVSubtarget::getTargetLowering () const inline override
Definition at line 119 of file RISCVSubtarget.h.
Referenced by llvm::CC_RISCV(), llvm::CC_RISCV_FastCC(), getCallLowering(), isLegalBitRotate(), lowerBitreverseShuffle(), and llvm::RISCVDAGToDAGISel::Select().
getXLen()
unsigned llvm::RISCVSubtarget::getXLen () const inline
Definition at line 172 of file RISCVSubtarget.h.
References is64Bit().
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), llvm::CC_RISCV(), llvm::CC_RISCV_FastCC(), combineSelectAndUse(), llvm::RISCVTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::RISCVTargetLowering::decomposeMulByConstant(), llvm::RISCVTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getRegisterBitWidth(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::RISCVDAGToDAGISel::hasAllNBitUsers(), llvm::RISCVInstrInfo::isBranchOffsetInRange(), llvm::RISCVTargetLowering::isFPImmLegal(), llvm::RISCVTargetLowering::isMulAddWithConstProfitable(), lowerBuildVectorOfConstants(), lowerBuildVectorViaPacking(), llvm::RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(), lowerFABSorFNEG(), lowerFCOPYSIGN(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedStore(), llvm::RISCVTargetLowering::lowerInterleaveIntrinsicToStore(), performBITREVERSECombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RISCVDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::selectShiftMaskXLen(), llvm::RISCVDAGToDAGISel::selectSHXADDOp(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::RISCVTargetLowering::shouldExtendTypeInLibCall(), transformAddImmMulImm(), and transformAddShlImm().
getXLenVT()
MVT llvm::RISCVSubtarget::getXLenVT () const inline
Definition at line 169 of file RISCVSubtarget.h.
References is64Bit().
Referenced by llvm::RISCVDAGToDAGISel::addVectorLoadStoreOperands(), llvm::CC_RISCV(), llvm::CC_RISCV_FastCC(), combine_CC(), combineSubShiftToOrcB(), llvm::RISCVTargetLowering::computeVLMax(), convertFromScalableVector(), expandMul(), getDefaultScalableVLOps(), getDefaultVLOps(), getDeinterleaveViaVNSRL(), getVSlidedown(), getVSlideup(), getWideningInterleave(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), lowerBUILD_VECTOR(), lowerBuildVectorOfConstants(), lowerBuildVectorViaDominantValues(), lowerBuildVectorViaPacking(), llvm::RISCVTargetLowering::LowerCall(), lowerCttzElts(), lowerFABSorFNEG(), lowerFCOPYSIGN(), lowerFMAXIMUM_FMINIMUM(), llvm::RISCVTargetLowering::LowerFormalArguments(), lowerFP_TO_INT_SAT(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerGetVectorLength(), llvm::RISCVTargetLowering::LowerOperation(), lowerReductionSeq(), lowerScalarInsert(), lowerScalarSplat(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsVSlide1(), lowerVECTOR_SHUFFLEAsVSlidedown(), lowerVECTOR_SHUFFLEAsVSlideup(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), matchSplatAsGather(), performCONCAT_VECTORSCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performSRACombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), promoteVCIXScalar(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RISCVDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::SelectAddrFrameIndex(), llvm::RISCVDAGToDAGISel::SelectFrameAddrRegImm(), llvm::RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::RISCVDAGToDAGISel::selectRVVSimm5(), llvm::RISCVDAGToDAGISel::selectScalarFPAsInt(), llvm::RISCVDAGToDAGISel::selectSF_VC_X_SE(), llvm::RISCVDAGToDAGISel::selectVLSEGFF(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), selectVSplatImmHelper(), and tryMemPairCombine().
hasConditionalMoveFusion()
bool llvm::RISCVSubtarget::hasConditionalMoveFusion () const inline
Definition at line 162 of file RISCVSubtarget.h.
References hasStdExtCOrZca().
Referenced by combineSelectAndUse(), combineSelectToBinOp(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::RISCVTargetLowering::PerformDAGCombine(), and performSELECTCombine().
hasHalfFPLoadStoreMove()
bool llvm::RISCVSubtarget::hasHalfFPLoadStoreMove () const inline
Definition at line 158 of file RISCVSubtarget.h.
hasStdExtCOrZca()
bool llvm::RISCVSubtarget::hasStdExtCOrZca () const inline
Definition at line 146 of file RISCVSubtarget.h.
Referenced by estimateFunctionSizeInBytes(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getNop(), hasConditionalMoveFusion(), isCompressibleLoad(), isCompressibleStore(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasStdExtCOrZcd()
bool llvm::RISCVSubtarget::hasStdExtCOrZcd () const inline
Definition at line 147 of file RISCVSubtarget.h.
Referenced by isCompressibleLoad(), and isCompressibleStore().
hasStdExtCOrZcfOrZce()
bool llvm::RISCVSubtarget::hasStdExtCOrZcfOrZce () const inline
Definition at line 148 of file RISCVSubtarget.h.
Referenced by isCompressibleLoad(), and isCompressibleStore().
hasStdExtDOrZdinx()
bool llvm::RISCVSubtarget::hasStdExtDOrZdinx () const inline
Definition at line 153 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::RISCVTargetLowering::isFPImmLegal(), llvm::RISCVTargetLowering::LowerFormalArguments(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasStdExtFOrZfinx()
bool llvm::RISCVSubtarget::hasStdExtFOrZfinx () const inline
Definition at line 152 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::getNumRegistersForCallingConv(), llvm::RISCVTargetLowering::getRegisterTypeForCallingConv(), llvm::RISCVTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::RISCVTargetLowering::isFPImmLegal(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVTargetLowering::ReplaceNodeResults(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasStdExtZfhminOrZhinxmin()
bool llvm::RISCVSubtarget::hasStdExtZfhminOrZhinxmin () const inline
Definition at line 155 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::getNumRegistersForCallingConv(), llvm::RISCVTargetLowering::getRegisterTypeForCallingConv(), llvm::RISCVTargetLowering::isFPImmLegal(), llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVTargetLowering::ReplaceNodeResults(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasStdExtZfhOrZhinx()
bool llvm::RISCVSubtarget::hasStdExtZfhOrZhinx () const inline
Definition at line 154 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::isFMAFasterThanFMulAndFAdd(), lowerFP_TO_INT(), lowerFP_TO_INT_SAT(), lowerINT_TO_FP(), llvm::RISCVTargetLowering::ReplaceNodeResults(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasStdExtZvl()
bool llvm::RISCVSubtarget::hasStdExtZvl () const inline
Definition at line 151 of file RISCVSubtarget.h.
hasVInstructions()
bool llvm::RISCVSubtarget::hasVInstructions () const inline
Definition at line 227 of file RISCVSubtarget.h.
Referenced by llvm::RISCVCallLowering::canLowerReturn(), llvm::RISCVTargetLowering::canSplatOperand(), combineBinOpOfExtractToReduceTree(), llvm::RISCVTTIImpl::getCastInstrCost(), getELen(), llvm::RISCVTTIImpl::getIntrinsicInstrCost(), getMaxInterleaveFactor(), getMaxLMULForFixedLengthVectors(), getMaxRVVVectorSizeInBits(), llvm::RISCVTTIImpl::getMaxVScale(), getMinRVVVectorSizeInBits(), llvm::RISCVTargetLowering::getOptimalMemOpType(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::RISCVTTIImpl::getRegisterBitWidth(), llvm::RISCVTTIImpl::getRegUsageForType(), getScavSlotsNumForRVV(), llvm::RISCVTargetLowering::getSetCCResultType(), llvm::RISCVTTIImpl::getVScaleForTuning(), llvm::RISCVTTIImpl::hasActiveVectorLength(), llvm::RISCVTargetLowering::isLegalAddressingMode(), llvm::RISCVTargetLowering::isLegalStridedLoadStore(), isSupportedArgumentType(), isSupportedReturnType(), llvm::RISCVTargetLowering::isTruncateFree(), lowerVectorIntrinsicScalars(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RISCVDAGToDAGISel::selectSF_VC_X_SE(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), llvm::RISCVTargetLowering::shouldExpandCttzElements(), llvm::RISCVTargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::RISCVTargetLowering::shouldSinkOperands(), and useRVVForFixedLengthVectors().
hasVInstructionsAnyF()
bool llvm::RISCVSubtarget::hasVInstructionsAnyF () const inline
Definition at line 235 of file RISCVSubtarget.h.
References hasVInstructionsF32().
hasVInstructionsBF16Minimal()
bool llvm::RISCVSubtarget::hasVInstructionsBF16Minimal () const inline
Definition at line 231 of file RISCVSubtarget.h.
Referenced by isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
hasVInstructionsF16()
bool llvm::RISCVSubtarget::hasVInstructionsF16 () const inline
Definition at line 230 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTTIImpl::getCastInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getRegUsageForType(), llvm::RISCVTargetLowering::isFMAFasterThanFMulAndFAdd(), isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), isPromotedOpNeedingSplit(), llvm::RISCVTargetLowering::LowerOperation(), and llvm::RISCVTargetLowering::RISCVTargetLowering().
hasVInstructionsF16Minimal()
bool llvm::RISCVSubtarget::hasVInstructionsF16Minimal () const inline
Definition at line 229 of file RISCVSubtarget.h.
Referenced by isPromotedOpNeedingSplit(), llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
hasVInstructionsF32()
bool llvm::RISCVSubtarget::hasVInstructionsF32 () const inline
Definition at line 232 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTTIImpl::getCmpSelInstrCost(), hasVInstructionsAnyF(), isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
hasVInstructionsF64()
bool llvm::RISCVSubtarget::hasVInstructionsF64 () const inline
Definition at line 233 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTTIImpl::getCmpSelInstrCost(), isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
hasVInstructionsFullMultiply()
bool llvm::RISCVSubtarget::hasVInstructionsFullMultiply () const inline
Definition at line 236 of file RISCVSubtarget.h.
hasVInstructionsI64()
bool llvm::RISCVSubtarget::hasVInstructionsI64 () const inline
Definition at line 228 of file RISCVSubtarget.h.
Referenced by getELen(), isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
is64Bit()
bool llvm::RISCVSubtarget::is64Bit () const inline
Definition at line 168 of file RISCVSubtarget.h.
Referenced by llvm::RISCVInstrInfo::canFoldIntoAddrMode(), llvm::CC_RISCV_FastCC(), llvm::CC_RISCV_GHC(), emitFROUND(), llvm::RISCVTargetLowering::EmitInstrWithCustomInserter(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), llvm::RISCVTargetLowering::getJumpTableEncoding(), getPACKOpcode(), llvm::RISCVTTIImpl::getPopcntSupport(), llvm::RISCVTargetLowering::getPostIndexedAddressParts(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), getXLen(), getXLenVT(), llvm::RISCVTargetLowering::isCheapToSpeculateCtlz(), llvm::RISCVTargetLowering::isCheapToSpeculateCttz(), isCompressibleLoad(), isCompressibleStore(), isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::RISCVTargetLowering::isSExtCheaperThanZExt(), llvm::RISCVTargetLowering::isTruncateFree(), lowerBuildVectorOfConstants(), llvm::RISCVTargetLowering::LowerCustomJumpTableEntry(), llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVInstrInfo::movImm(), performANDCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performSETCCCombine(), performTRUNCATECombine(), performXORCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RISCVDAGToDAGISel::Select(), selectConstantAddr(), llvm::RISCVDAGToDAGISel::selectScalarFPAsInt(), llvm::RISCVDAGToDAGISel::selectVLXSEG(), llvm::RISCVDAGToDAGISel::selectVSXSEG(), llvm::RISCVTargetLowering::shouldSignExtendTypeInLibCall(), llvm::RISCVTargetLowering::shouldTransformSignedTruncationCheck(), llvm::RISCVTargetLowering::signExtendConstant(), and llvm::RISCVInstrInfo::verifyInstruction().
isRegisterReservedByUser()
bool llvm::RISCVSubtarget::isRegisterReservedByUser (Register i) const inline
Definition at line 221 of file RISCVSubtarget.h.
References assert().
Referenced by llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVTargetLowering::getRegisterByName(), llvm::RISCVTargetLowering::LowerCall(), and llvm::RISCVTargetLowering::LowerReturn().
isSoftFPABI()
bool llvm::RISCVSubtarget::isSoftFPABI () const inline
Definition at line 216 of file RISCVSubtarget.h.
References llvm::RISCVABI::ABI_ILP32, llvm::RISCVABI::ABI_ILP32E, and llvm::RISCVABI::ABI_LP64.
Referenced by llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and llvm::RISCVTargetLowering::shouldExtendTypeInLibCall().
isTargetAndroid()
bool llvm::RISCVSubtarget::isTargetAndroid () const inline
Definition at line 269 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::getIRStackGuard().
isTargetFuchsia()
bool llvm::RISCVSubtarget::isTargetFuchsia () const inline
Definition at line 270 of file RISCVSubtarget.h.
Referenced by llvm::RISCVTargetLowering::getIRStackGuard().
ParseSubtargetFeatures()
void llvm::RISCVSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
useAA()
bool RISCVSubtarget::useAA () const override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
Definition at line 195 of file RISCVSubtarget.cpp.
References UseAA.
useConstantPoolForLargeInts()
bool RISCVSubtarget::useConstantPoolForLargeInts () const
Definition at line 128 of file RISCVSubtarget.cpp.
References RISCVDisableUsingConstantPoolForLargeInts.
Referenced by lowerConstant().
useRVVForFixedLengthVectors()
bool RISCVSubtarget::useRVVForFixedLengthVectors () const
Definition at line 181 of file RISCVSubtarget.cpp.
References getMinRVVVectorSizeInBits(), hasVInstructions(), and llvm::RISCV::RVVBitsPerBlock.
Referenced by llvm::RISCVTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getExtendedReductionCost(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::RISCVTTIImpl::getRegisterBitWidth(), llvm::RISCVTTIImpl::getRegUsageForType(), llvm::RISCVTargetLowering::getSetCCResultType(), llvm::RISCVTargetLowering::isLegalInterleavedAccessType(), llvm::RISCVTargetLowering::isLegalStridedLoadStore(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::RISCVTargetLowering(), and useRVVForFixedLengthVectorVT().
Member Data Documentation
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::RISCVSubtarget::CallLoweringInfo mutable protected
Definition at line 251 of file RISCVSubtarget.h.
Referenced by getCallLowering().
InstSelector
std::unique_ptr<InstructionSelector> llvm::RISCVSubtarget::InstSelector mutable protected
Definition at line 252 of file RISCVSubtarget.h.
Referenced by getInstructionSelector().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::RISCVSubtarget::Legalizer mutable protected
Definition at line 253 of file RISCVSubtarget.h.
RegBankInfo
std::unique_ptr<RISCVRegisterBankInfo> llvm::RISCVSubtarget::RegBankInfo mutable protected
Definition at line 254 of file RISCVSubtarget.h.
Referenced by getRegBankInfo().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVSubtarget.h
lib/Target/RISCV/RISCVSubtarget.cpp