LLVM: llvm::SPIRVDuplicatesTrackerBase< KeyTy > Class Template Reference
llvm::SPIRVDuplicatesTrackerBase< KeyTy > Class Template Reference
#include "Target/SPIRV/SPIRVDuplicatesTracker.h"
Public Types
using StorageTy = MapVector<KeyTy, SPIRV::DTSortableEntry>
Public Member Functions
void add (KeyTy V, const MachineFunction *MF, Register R)
Register find (KeyTy V, const MachineFunction *MF) const
const StorageTy & getAllUses () const
Friends
class SPIRVGeneralDuplicatesTracker
Detailed Description
template<typename KeyTy>
class llvm::SPIRVDuplicatesTrackerBase< KeyTy >
Definition at line 136 of file SPIRVDuplicatesTracker.h.
Member Typedef Documentation
StorageTy
template<typename KeyTy > using llvm::SPIRVDuplicatesTrackerBase< KeyTy >::StorageTy = MapVector<KeyTy, SPIRV::DTSortableEntry>
Definition at line 141 of file SPIRVDuplicatesTracker.h.
Member Function Documentation
add()
template<typename KeyTy > void llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add (KeyTy V, const MachineFunction * MF, Register R) inline
Definition at line 147 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find(), and isValid().
Referenced by llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::SPIRVGeneralDuplicatesTracker::add(), and llvm::SPIRVGeneralDuplicatesTracker::add().
find()
template<typename KeyTy > Register llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find (KeyTy V, const MachineFunction * MF) const inline
Definition at line 165 of file SPIRVDuplicatesTracker.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), and Register.
Referenced by llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add(), llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::SPIRVGeneralDuplicatesTracker::find(), and llvm::SPIRVGeneralDuplicatesTracker::find().
getAllUses()
template<typename KeyTy > const StorageTy & llvm::SPIRVDuplicatesTrackerBase< KeyTy >::getAllUses () const inline
Definition at line 176 of file SPIRVDuplicatesTracker.h.
Friends And Related Symbol Documentation
SPIRVGeneralDuplicatesTracker
template<typename KeyTy > friend class SPIRVGeneralDuplicatesTracker friend
Definition at line 185 of file SPIRVDuplicatesTracker.h.
The documentation for this class was generated from the following file:
lib/Target/SPIRV/SPIRVDuplicatesTracker.h