LLVM: lib/CGData/CodeGenData.cpp File Reference
CodeGenData.cpp File Reference
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/CGData/CodeGenDataReader.h"
#include "llvm/CGData/OutlinedHashTreeRecord.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/WithColor.h"
#include "llvm/CGData/CodeGenData.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::IndexedCGData
namespace llvm::cgdata
Macros
#define DEBUG_TYPE "cg-data"
#define CG_DATA_SECT_ENTRY(Kind, SectNameCommon, SectNameCoff, Prefix)
#define CG_DATA_SIMPLE_QUOTE(x)
#define CG_DATA_QUOTE(x)
#define CG_DATA_DEFINED
#define CG_DATA_OUTLINE_COMMON __llvm_outline
#define CG_DATA_OUTLINE_COFF ".loutline"
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
#define CG_DATA_INDEX_VERSION 1
#define CG_DATA_SECT_ENTRY(Kind, SectNameCommon, SectNameCoff, Prefix)
#define CG_DATA_SIMPLE_QUOTE(x)
#define CG_DATA_QUOTE(x)
#define CG_DATA_DEFINED
#define CG_DATA_OUTLINE_COMMON __llvm_outline
#define CG_DATA_OUTLINE_COFF ".loutline"
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
#define CG_DATA_INDEX_VERSION 1
#define CG_DATA_SECT_ENTRY(Kind, SectNameCommon, SectNameCoff, Prefix)
#define CG_DATA_SIMPLE_QUOTE(x)
#define CG_DATA_QUOTE(x)
#define CG_DATA_DEFINED
#define CG_DATA_OUTLINE_COMMON __llvm_outline
#define CG_DATA_OUTLINE_COFF ".loutline"
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
#define CG_DATA_INDEX_VERSION 1
Functions
static std::string getCGDataErrString (cgdata_error Err, const std::string &ErrMsg="")
std::string llvm::getCodeGenDataSectionName (CGDataSectKind CGSK, Triple::ObjectFormatType OF, bool AddSegmentInfo=true)
void llvm::cgdata::warn (Twine Message, std::string Whence="", std::string Hint="")
void llvm::cgdata::warn (Error E, StringRef Whence="")
Variables
cl::opt< bool > CodeGenDataGenerate ("codegen-data-generate", cl::init(false), cl::Hidden, cl::desc("Emit CodeGen Data into custom sections"))
cl::opt< std::string > CodeGenDataUsePath ("codegen-data-use-path", cl::init(""), cl::Hidden, cl::desc("File path to where .cgdata file is read"))
Macro Definition Documentation
CG_DATA_DEFINED [1/3]
#define CG_DATA_DEFINED
CG_DATA_DEFINED [2/3]
#define CG_DATA_DEFINED
CG_DATA_DEFINED [3/3]
#define CG_DATA_DEFINED
CG_DATA_INDEX_VERSION [1/3]
#define CG_DATA_INDEX_VERSION 1
CG_DATA_INDEX_VERSION [2/3]
#define CG_DATA_INDEX_VERSION 1
CG_DATA_INDEX_VERSION [3/3]
#define CG_DATA_INDEX_VERSION 1
CG_DATA_OUTLINE_COFF [1/3]
#define CG_DATA_OUTLINE_COFF ".loutline"
CG_DATA_OUTLINE_COFF [2/3]
#define CG_DATA_OUTLINE_COFF ".loutline"
CG_DATA_OUTLINE_COFF [3/3]
#define CG_DATA_OUTLINE_COFF ".loutline"
CG_DATA_OUTLINE_COMMON [1/3]
#define CG_DATA_OUTLINE_COMMON __llvm_outline
CG_DATA_OUTLINE_COMMON [2/3]
#define CG_DATA_OUTLINE_COMMON __llvm_outline
CG_DATA_OUTLINE_COMMON [3/3]
#define CG_DATA_OUTLINE_COMMON __llvm_outline
CG_DATA_QUOTE [1/3]
#define CG_DATA_QUOTE (x)
Value:
CG_DATA_SIMPLE_QUOTE(x)
CG_DATA_QUOTE [2/3]
#define CG_DATA_QUOTE (x)
Value:
CG_DATA_SIMPLE_QUOTE(x)
CG_DATA_QUOTE [3/3]
#define CG_DATA_QUOTE (x)
Value:
CG_DATA_SIMPLE_QUOTE(x)
CG_DATA_SECT_ENTRY [1/3]
#define CG_DATA_SECT_ENTRY (Kind, SectNameCommon, SectNameCoff, Prefix)
Value:
  SectNameCommon,
CG_DATA_SECT_ENTRY [2/3]
#define CG_DATA_SECT_ENTRY (Kind, SectNameCommon, SectNameCoff, Prefix)
Value:
  SectNameCoff,
CG_DATA_SECT_ENTRY [3/3]
#define CG_DATA_SECT_ENTRY (Kind, SectNameCommon, SectNameCoff, Prefix)
Value:
Prefix,
CG_DATA_SECT_NAME [1/3]
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
CG_DATA_SECT_NAME [2/3]
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
CG_DATA_SECT_NAME [3/3]
#define CG_DATA_SECT_NAME CG_DATA_QUOTE(CG_DATA_OUTLINE_COMMON)
CG_DATA_SIMPLE_QUOTE [1/3]
#define CG_DATA_SIMPLE_QUOTE (x)
Value:
#x
CG_DATA_SIMPLE_QUOTE [2/3]
#define CG_DATA_SIMPLE_QUOTE (x)
Value:
#x
CG_DATA_SIMPLE_QUOTE [3/3]
#define CG_DATA_SIMPLE_QUOTE (x)
Value:
#x
DEBUG_TYPE
#define DEBUG_TYPE "cg-data"
Definition at line 22 of file CodeGenData.cpp.
Function Documentation
getCGDataErrString()
static std::string getCGDataErrString (cgdata_error Err, const std::string & ErrMsg = "") static
Definition at line 34 of file CodeGenData.cpp.
References OS.
Referenced by llvm::CGDataError::message().
Variable Documentation
CodeGenDataGenerate
cl::opt< bool > CodeGenDataGenerate("codegen-data-generate", cl::init(false), cl::Hidden, cl::desc("Emit CodeGen Data into custom sections")) ("codegen-data-generate" , cl::init(false) , cl::Hidden , cl::desc("Emit CodeGen Data into custom sections"))
Referenced by llvm::CodeGenData::getInstance().
CodeGenDataUsePath
cl::opt< std::string > CodeGenDataUsePath("codegen-data-use-path", cl::init(""), cl::Hidden, cl::desc("File path to where .cgdata file is read")) ("codegen-data-use-path" , cl::init("") , cl::Hidden , cl::desc("File path to where .cgdata file is read"))
Referenced by llvm::CodeGenData::getInstance().