LLVM: lib/Analysis/CostModel.cpp File Reference
CostModel.cpp File Reference
#include "llvm/Analysis/CostModel.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/IR/IntrinsicInst.h"
Macros
#define CM_NAME "cost-model"
#define DEBUG_TYPE CM_NAME
Variables
static cl::opt< TargetTransformInfo::TargetCostKind > CostKind ("cost-kind", cl::desc("Target cost kind"), cl::init(TargetTransformInfo::TCK_RecipThroughput), cl::values(clEnumValN(TargetTransformInfo::TCK_RecipThroughput, "throughput", "Reciprocal throughput"), clEnumValN(TargetTransformInfo::TCK_Latency, "latency", "Instruction latency"), clEnumValN(TargetTransformInfo::TCK_CodeSize, "code-size", "Code size"), clEnumValN(TargetTransformInfo::TCK_SizeAndLatency, "size-latency", "Code size and latency")))
static cl::opt< bool > TypeBasedIntrinsicCost ("type-based-intrinsic-cost", cl::desc("Calculate intrinsics cost based only on argument types"), cl::init(false))
Macro Definition Documentation
CM_NAME
#define CM_NAME "cost-model"
Definition at line 47 of file CostModel.cpp.
DEBUG_TYPE
#define DEBUG_TYPE CM_NAME
Definition at line 48 of file CostModel.cpp.
Variable Documentation
CostKind
cl::opt< TargetTransformInfo::TargetCostKind > CostKind("cost-kind", cl::desc("Target cost kind"), cl::init(TargetTransformInfo::TCK_RecipThroughput), cl::values(clEnumValN(TargetTransformInfo::TCK_RecipThroughput, "throughput", "Reciprocal throughput"), clEnumValN(TargetTransformInfo::TCK_Latency, "latency", "Instruction latency"), clEnumValN(TargetTransformInfo::TCK_CodeSize, "code-size", "Code size"), clEnumValN(TargetTransformInfo::TCK_SizeAndLatency, "size-latency", "Code size and latency"))) ("cost-kind" , cl::desc("Target cost kind") , cl::init(TargetTransformInfo::TCK_RecipThroughput) , cl::values(clEnumValN(TargetTransformInfo::TCK_RecipThroughput, "throughput", "Reciprocal throughput"), clEnumValN(TargetTransformInfo::TCK_Latency, "latency", "Instruction latency"), clEnumValN(TargetTransformInfo::TCK_CodeSize, "code-size", "Code size"), clEnumValN(TargetTransformInfo::TCK_SizeAndLatency, "size-latency", "Code size and latency"))) static
Referenced by analyzeLoopUnrollCost(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::VPWidenCallRecipe::computeCost(), llvm::VPWidenLoadEVLRecipe::computeCost(), llvm::VPWidenMemoryRecipe::computeCost(), llvm::VPWidenRecipe::computeCost(), llvm::VPWidenStoreEVLRecipe::computeCost(), costAndCollectOperands(), findBestNonTrivialUnswitchCandidate(), llvm::foldBranchToCommonDest(), llvm::TargetTransformInfo::getAltInstrCost(), llvm::TargetTransformInfo::Model< T >::getAltInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::NVPTXTTIImpl::getArithmeticInstrCost(), llvm::PPCTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::TargetTransformInfo::Model< T >::getArithmeticInstrCost(), llvm::TargetTransformInfoImplBase::getArithmeticInstrCost(), llvm::WebAssemblyTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::ARMTTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getArithmeticReductionCost(), llvm::GCNTTIImpl::getArithmeticReductionCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::TargetTransformInfo::getArithmeticReductionCost(), llvm::TargetTransformInfo::Model< T >::getArithmeticReductionCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCostSVE(), llvm::HexagonTTIImpl::getCallInstrCost(), llvm::TargetTransformInfo::getCallInstrCost(), llvm::TargetTransformInfo::Model< T >::getCallInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), llvm::PPCTTIImpl::getCastInstrCost(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::TargetTransformInfo::Model< T >::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCFInstrCost(), llvm::ARMTTIImpl::getCFInstrCost(), llvm::BasicTTIImplBase< T >::getCFInstrCost(), llvm::GCNTTIImpl::getCFInstrCost(), llvm::PPCTTIImpl::getCFInstrCost(), llvm::R600TTIImpl::getCFInstrCost(), llvm::RISCVTTIImpl::getCFInstrCost(), llvm::TargetTransformInfo::getCFInstrCost(), llvm::TargetTransformInfo::Model< T >::getCFInstrCost(), llvm::TargetTransformInfoImplBase::getCFInstrCost(), llvm::X86TTIImpl::getCFInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::PPCTTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm::TargetTransformInfo::Model< T >::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCostOfKeepingLiveOverCall(), llvm::RISCVTTIImpl::getCostOfKeepingLiveOverCall(), llvm::LoopVectorizationCostModel::getDivRemSpeculationCost(), llvm::ARMTTIImpl::getExtendedReductionCost(), llvm::BasicTTIImplBase< T >::getExtendedReductionCost(), llvm::RISCVTTIImpl::getExtendedReductionCost(), llvm::TargetTransformInfo::getExtendedReductionCost(), llvm::TargetTransformInfo::Model< T >::getExtendedReductionCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::BasicTTIImplBase< T >::getExtractWithExtendCost(), llvm::AArch64TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::BasicTTIImplBase< T >::getGatherScatterOpCost(), llvm::HexagonTTIImpl::getGatherScatterOpCost(), llvm::RISCVTTIImpl::getGatherScatterOpCost(), llvm::TargetTransformInfo::getGatherScatterOpCost(), llvm::TargetTransformInfo::Model< T >::getGatherScatterOpCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::BasicTTIImplBase< T >::getGEPCost(), llvm::TargetTransformInfo::getGEPCost(), llvm::TargetTransformInfo::Model< T >::getGEPCost(), getGEPCosts(), llvm::HexagonTTIImpl::getInstructionCost(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::PPCTTIImpl::getInstructionCost(), llvm::TargetTransformInfo::getInstructionCost(), llvm::TargetTransformInfo::getInstructionCost(), llvm::TargetTransformInfo::Model< T >::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::HexagonTTIImpl::getInterleavedMemoryOpCost(), llvm::PPCTTIImpl::getInterleavedMemoryOpCost(), llvm::RISCVTTIImpl::getInterleavedMemoryOpCost(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), llvm::TargetTransformInfo::getInterleavedMemoryOpCost(), llvm::TargetTransformInfo::Model< T >::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::PPCTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::TargetTransformInfo::getIntImmCost(), llvm::TargetTransformInfo::Model< T >::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::ARMTTIImpl::getIntImmCostInst(), llvm::LanaiTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::TargetTransformInfo::getIntImmCostInst(), llvm::TargetTransformInfo::Model< T >::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::LanaiTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::TargetTransformInfo::getIntImmCostIntrin(), llvm::TargetTransformInfo::Model< T >::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), llvm::HexagonTTIImpl::getIntrinsicInstrCost(), llvm::PPCTTIImpl::getIntrinsicInstrCost(), llvm::RISCVTTIImpl::getIntrinsicInstrCost(), llvm::SystemZTTIImpl::getIntrinsicInstrCost(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), llvm::TargetTransformInfo::Model< T >::getIntrinsicInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::AArch64TTIImpl::getMaskedMemoryOpCost(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMaskedMemoryOpCost(), llvm::HexagonTTIImpl::getMaskedMemoryOpCost(), llvm::RISCVTTIImpl::getMaskedMemoryOpCost(), llvm::TargetTransformInfo::getMaskedMemoryOpCost(), llvm::TargetTransformInfo::Model< T >::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::RISCVTTIImpl::getMemoryOpCost(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::TargetTransformInfo::getMemoryOpCost(), llvm::TargetTransformInfo::Model< T >::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::AArch64TTIImpl::getMinMaxReductionCost(), llvm::ARMTTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< T >::getMinMaxReductionCost(), llvm::GCNTTIImpl::getMinMaxReductionCost(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::TargetTransformInfo::getMinMaxReductionCost(), llvm::TargetTransformInfo::Model< T >::getMinMaxReductionCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::ARMTTIImpl::getMulAccReductionCost(), llvm::BasicTTIImplBase< T >::getMulAccReductionCost(), llvm::TargetTransformInfo::getMulAccReductionCost(), llvm::TargetTransformInfo::Model< T >::getMulAccReductionCost(), llvm::ARMSubtarget::getMVEVectorCostFactor(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::TargetTransformInfo::getOperandsScalarizationOverhead(), llvm::TargetTransformInfo::Model< T >::getOperandsScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getOrderedReductionCost(), llvm::RISCVTTIImpl::getPointersChainCost(), llvm::TargetTransformInfo::getPointersChainCost(), llvm::TargetTransformInfo::Model< T >::getPointersChainCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getPointersChainCost(), llvm::X86TTIImpl::getPointersChainCost(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), llvm::BasicTTIImplBase< T >::getReplicationShuffleCost(), llvm::TargetTransformInfo::getReplicationShuffleCost(), llvm::TargetTransformInfo::Model< T >::getReplicationShuffleCost(), llvm::X86TTIImpl::getReplicationShuffleCost(), llvm::AArch64TTIImpl::getScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::RISCVTTIImpl::getScalarizationOverhead(), llvm::TargetTransformInfo::getScalarizationOverhead(), llvm::TargetTransformInfo::Model< T >::getScalarizationOverhead(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::GCNTTIImpl::getShuffleCost(), llvm::RISCVTTIImpl::getShuffleCost(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::TargetTransformInfo::getShuffleCost(), llvm::TargetTransformInfo::Model< T >::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::getSpliceCost(), llvm::RISCVTTIImpl::getStoreImmCost(), llvm::BasicTTIImplBase< T >::getStridedMemoryOpCost(), llvm::RISCVTTIImpl::getStridedMemoryOpCost(), llvm::TargetTransformInfo::getStridedMemoryOpCost(), llvm::TargetTransformInfo::Model< T >::getStridedMemoryOpCost(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::BasicTTIImplBase< T >::getTreeReductionCost(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), llvm::GCNTTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::R600TTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::TargetTransformInfo::Model< T >::getVectorInstrCost(), llvm::TargetTransformInfo::Model< T >::getVectorInstrCost(), llvm::WebAssemblyTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::PPCTTIImpl::getVPMemoryOpCost(), llvm::TargetTransformInfo::Model< T >::getVPMemoryOpCost(), llvm::CostModelPrinterPass::run(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), llvm::slpvectorizer::BoUpSLP::transformNodes(), and validateAndCostRequiredSelects().
TypeBasedIntrinsicCost
cl::opt< bool > TypeBasedIntrinsicCost("type-based-intrinsic-cost", cl::desc("Calculate intrinsics cost based only on argument types"), cl::init(false)) ("type-based-intrinsic-cost" , cl::desc("Calculate intrinsics cost based only on argument types") , cl::init(false)) static
Referenced by llvm::CostModelPrinterPass::run().