LLVM: lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp File Reference
DwarfCompileUnit.cpp File Reference
#include "DwarfCompileUnit.h"
#include "AddressPool.h"
#include "DwarfExpression.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/DIE.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <iterator>
#include <optional>
#include <string>
#include <utility>
Functions
static bool AddLinkageNamesToDeclCallOriginsForTuning (const DwarfDebug *DD)
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug *DW)
static SmallVector< const DIVariable *, 2 > dependencies (DbgVariable *Var)
Return all DIVariables that appear in count: expressions.
static SmallVector< DbgVariable *, 8 > sortLocalVars (SmallVectorImpl< DbgVariable * > &Input)
Sort local variables so that variables appearing inside of helper expressions come first.
Variables
cl::opt< cl::boolOrDefault > AddLinkageNamesToDeclCallOrigins ("add-linkage-names-to-declaration-call-origins", cl::Hidden, cl::desc("Add DW_AT_linkage_name to function declaration DIEs " "referenced by DW_AT_call_origin attributes. Enabled by default " "for -gsce debugger tuning."))
Query value using AddLinkageNamesToDeclCallOriginsForTuning.
Function Documentation
AddLinkageNamesToDeclCallOriginsForTuning()
static bool AddLinkageNamesToDeclCallOriginsForTuning (const DwarfDebug * DD) static
Definition at line 53 of file DwarfCompileUnit.cpp.
References AddLinkageNamesToDeclCallOrigins, and llvm::DwarfDebug::tuneForSCE().
Referenced by llvm::DwarfCompileUnit::constructCallSiteEntryDIE().
dependencies()
static SmallVector< const DIVariable *, 2 > dependencies (DbgVariable * Var) static
Return all DIVariables that appear in count: expressions.
Definition at line 997 of file DwarfCompileUnit.cpp.
References llvm::Count, llvm::dyn_cast(), llvm::dyn_cast_if_present(), and llvm::DbgVariable::getType().
Referenced by sortLocalVars().
GetCompileUnitType()
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug * DW) static
Definition at line 60 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::getDwarfVersion().
sortLocalVars()
static SmallVector< DbgVariable *, 8 > sortLocalVars (SmallVectorImpl< DbgVariable * > & Input) static
Sort local variables so that variables appearing inside of helper expressions come first.
Definition at line 1043 of file DwarfCompileUnit.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), dependencies(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
Referenced by llvm::DwarfCompileUnit::createAndAddScopeChildren().
Variable Documentation
AddLinkageNamesToDeclCallOrigins
cl::opt< cl::boolOrDefault > AddLinkageNamesToDeclCallOrigins("add-linkage-names-to-declaration-call-origins", cl::Hidden, cl::desc("Add DW_AT_linkage_name to function declaration DIEs " "referenced by DW_AT_call_origin attributes. Enabled by default " "for -gsce debugger tuning.")) ("add-linkage-names-to-declaration-call-origins" , cl::Hidden , cl::desc("Add DW_AT_linkage_name to function declaration DIEs " "referenced by DW_AT_call_origin attributes. Enabled by default " "for -gsce debugger tuning."))
Query value using AddLinkageNamesToDeclCallOriginsForTuning.
Referenced by AddLinkageNamesToDeclCallOriginsForTuning().