LLVM: lib/CodeGen/AsmPrinter/ErlangGCPrinter.cpp File Reference
ErlangGCPrinter.cpp File Reference
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/IR/BuiltinGCs.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Variables
static GCMetadataPrinterRegistry::Add< ErlangGCPrinter > X ("erlang", "erlang-compatible garbage collector")
Variable Documentation
X
GCMetadataPrinterRegistry::Add< ErlangGCPrinter > X("erlang", "erlang-compatible garbage collector") ("erlang" , "erlang-compatible garbage collector") static
Examples
/root/llvm-project/llvm/include/llvm/Transforms/Utils/Local.h.
Referenced by llvm::abs(), llvm::detail::abs(), llvm::AbsoluteDifference(), llvm::ConstantRange::add(), llvm::cl::parser< DataType >::addLiteralOption(), llvm::AddOverflow(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::ScheduleDAGTopologicalSort::AddPredQueued(), llvm::AllocatorList< T, AllocatorT >::AllocatorList(), annotateNonNullAndDereferenceable(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::CombinerHelper::applyXorOfAndWithSameReg(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), buildVRegToDbgValueMap(), canAlwaysEvaluateInType(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), canonicalizeSaturatedAdd(), llvm::capacity_in_bytes(), llvm::capacity_in_bytes(), llvm::capacity_in_bytes(), llvm::SwitchCG::SwitchLowering::caseClusterRank(), CheckAndCreateOffsetAdd(), checkForNegativeOperand(), clusterSortPtrAccesses(), collectBitParts(), combineAddOrSubToADCOrSBB(), combineAddOrSubToADCOrSBB(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndShuffleNot(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMADConstOne(), combineMulSelectConstOne(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineSubABS(), combineUADDO_CARRYDiamond(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), combineVWADDSUBWSelect(), combineX86SubCmpForFlags(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::ScaledNumber< DigitsT >::compare(), CompareSCEVComplexity(), llvm::ComputeEditDistance(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash(), llvm::DefaultFoldingSetTrait< T >::ComputeHash(), llvm::FoldingSetTrait< SCEV >::ComputeHash(), llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash(), llvm::FoldingSetTrait< SDVTListNode >::ComputeHash(), ComputeNumSignBitsImpl(), llvm::codeview::consume(), llvm::Trace::contains(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), createAArch64MCInstrInfo(), createAArch64MCRegisterInfo(), createAMDGPUMCInstrInfo(), createAMDGPUMCRegisterInfo(), createARCMCInstrInfo(), createARCMCRegisterInfo(), createARMMCInstrInfo(), createARMMCRegisterInfo(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::createAVRMCInstrInfo(), createAVRMCRegisterInfo(), createBPFMCInstrInfo(), createBPFMCRegisterInfo(), llvm::createGCNMCRegisterInfo(), llvm::createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createLanaiMCInstrInfo(), createLanaiMCRegisterInfo(), createLoongArchMCInstrInfo(), createLoongArchMCRegisterInfo(), createM68kMCInstrInfo(), createM68kMCRegisterInfo(), createMCInstrInfo(), createMCRegisterInfo(), createMipsMCInstrInfo(), createMipsMCRegisterInfo(), createMSP430MCInstrInfo(), createMSP430MCRegisterInfo(), createNodeForSelectViaUMinSeq(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createPPCMCInstrInfo(), createPPCMCRegisterInfo(), llvm::createR600MCInstrInfo(), createRISCVMCInstrInfo(), createRISCVMCRegisterInfo(), createSparcMCInstrInfo(), createSparcMCRegisterInfo(), createSPIRVMCInstrInfo(), createSPIRVMCRegisterInfo(), createSystemZMCInstrInfo(), createSystemZMCRegisterInfo(), createVEMCInstrInfo(), createVEMCRegisterInfo(), createX86MCInstrInfo(), createX86MCRegisterInfo(), createXCoreMCInstrInfo(), createXCoreMCRegisterInfo(), createXtensaMCInstrInfo(), createXtensaMCRegisterInfo(), llvm::DebugValueUser::DebugValueUser(), llvm::DebugValueUser::DebugValueUser(), decomposeBitTestICmp(), llvm::decomposeBitTestICmp(), llvm::DIEValue::DIEValue(), dropRedundantMaskingOfLeftShiftInput(), llvm::dynamicAPIntFromInt64(), llvm::MCDwarfFrameEmitter::Emit(), emitOrXorXorTree(), emitTransformedIndex(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals(), llvm::DefaultFoldingSetTrait< T >::Equals(), llvm::FoldingSetTrait< SCEV >::Equals(), llvm::FoldingSetTrait< SCEVPredicate >::Equals(), llvm::FoldingSetTrait< SDVTListNode >::Equals(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), expandAbs(), expandAnyOrAllIntrinsic(), expandAtan2Intrinsic(), expandClampIntrinsic(), expandExpIntrinsic(), llvm::TargetLowering::expandFunnelShift(), expandLengthIntrinsic(), expandLerpIntrinsic(), expandLog(), expandLog10(), expandLog2(), expandLogIntrinsic(), expandMul(), expandNormalizeIntrinsic(), expandPowIntrinsic(), expandSignIntrinsic(), expandStepIntrinsic(), expandUDivOrURem(), expandVPFunnelShift(), llvm::RISCVSubtarget::expandVScale(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), llvm::LiveRange::find(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), findGCD(), FindInOperandList(), llvm::findValuesAffectedByCondition(), finishAdjustingBasicBlocksAndLandingPads(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldAndToUsubsat(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldBitOrderCrossLogicOp(), foldBitwiseLogicWithIntrinsics(), foldBoxMultiply(), foldCastShuffle(), foldClampRangeOfTwo(), foldComplexAndOrPatterns(), foldCopySignIdioms(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldCtpop(), foldCttzCtlz(), foldExtendedSignBitTest(), foldFabsWithFcmpZero(), foldFCmpFSubIntoFCmp(), foldFDivConstantDividend(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), llvm::InstCombinerImpl::foldItoFPtoI(), foldLoadsRecursive(), foldLogicCastConstant(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldMinMaxSharedOp(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNotXor(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldPowiReassoc(), foldSelectBinOpIdentity(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), foldSelectICmpLshrAshr(), foldSelectOfConstantsUsingSra(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), foldSelectWithBinaryOp(), foldSelectZeroOrMul(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldShuffledIntrinsicOperands(), foldShuffleOfConcatUndefs(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldSqrtWithFcmpZero(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), foldTruncInsEltPair(), foldTruncShuffle(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::FmtAlign::format(), llvm::format_provider< T, std::enable_if_t< support::detail::use_char_formatter< T >::value > >::format(), llvm::PMDataManager::freePass(), llvm::frexp(), genConstMult(), genShXAddAddShift(), llvm::APSInt::get(), llvm::get_hashable_data(), llvm::ScalarEvolution::getAddExpr(), llvm::Trace::getBlockIndex(), llvm::IndexedInstrProfReader::getFunctionBitmap(), llvm::DenseMapInfo< ImmutableList< T >, void >::getHashValue(), getHashValueImpl(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), getKnownBitsFromAndXorOr(), getKnownSign(), getKnownSignOrZero(), getLimitedPrecisionExp2(), llvm::objcopy::elf::IHexRecord::getLine(), getMad(), getMad(), llvm::TargetLowering::getNegatedExpression(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::APSInt::getUnsigned(), llvm::SDNode::getVTList(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::HandleSDNode::HandleSDNode(), handleValVerMetadata(), llvm::TargetLoweringBase::hasAndNot(), llvm::HexagonTargetLowering::hasBitTest(), llvm::RISCVTargetLowering::hasBitTest(), llvm::X86TargetLowering::hasBitTest(), llvm::detail::hash_value(), llvm::hash_value(), hoistInsEltConst(), INITIALIZE_PASS(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::int64fromDynamicAPInt(), llvm::isa_and_nonnull(), llvm::isa_and_present(), llvm::isCheckForZeroAndMulWithOverflow(), isDivZero(), isEqualImpl(), llvm::X86MCExpr::isEqualTo(), llvm::HexagonBlockRanges::IndexType::isInstr(), llvm::isKernelFunction(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonZeroFromOperator(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), llvm::slpvectorizer::BoUpSLP::isLoadCombineCandidate(), isMaskOrZero(), isMatchingReloc(), isNonZeroAdd(), isNonZeroMul(), isNonZeroSub(), isOrXorXorTree(), isSimpleCastedPHI(), llvm::isSplatValue(), isTruePredicate(), llvm::detail::lcm(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafe(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF32(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF64(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), LLVMInitializeAArch64AsmParser(), LLVMInitializeAArch64AsmPrinter(), LLVMInitializeAArch64Target(), LLVMInitializeAArch64TargetInfo(), LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTarget(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCAsmPrinter(), LLVMInitializeARCTarget(), LLVMInitializeARCTargetInfo(), LLVMInitializeARCTargetMC(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRAsmParser(), LLVMInitializeAVRAsmPrinter(), llvm::LLVMInitializeAVRTarget(), LLVMInitializeAVRTargetInfo(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFAsmParser(), LLVMInitializeBPFAsmPrinter(), LLVMInitializeBPFTarget(), LLVMInitializeBPFTargetInfo(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYAsmParser(), LLVMInitializeCSKYAsmPrinter(), LLVMInitializeCSKYTarget(), LLVMInitializeCSKYTargetInfo(), LLVMInitializeDirectXAsmPrinter(), LLVMInitializeDirectXTarget(), LLVMInitializeDirectXTargetInfo(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonAsmParser(), LLVMInitializeHexagonAsmPrinter(), LLVMInitializeHexagonTarget(), LLVMInitializeHexagonTargetInfo(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiAsmPrinter(), LLVMInitializeLanaiTargetInfo(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchAsmParser(), LLVMInitializeLoongArchAsmPrinter(), LLVMInitializeLoongArchTarget(), LLVMInitializeLoongArchTargetInfo(), LLVMInitializeM68kAsmParser(), LLVMInitializeM68kAsmPrinter(), LLVMInitializeM68kTarget(), LLVMInitializeM68kTargetInfo(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430AsmParser(), LLVMInitializeMSP430AsmPrinter(), LLVMInitializeMSP430Target(), LLVMInitializeMSP430TargetInfo(), LLVMInitializeNVPTXAsmPrinter(), LLVMInitializeNVPTXTarget(), LLVMInitializeNVPTXTargetInfo(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetInfo(), LLVMInitializeRISCVAsmParser(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcAsmPrinter(), LLVMInitializeSparcTarget(), LLVMInitializeSparcTargetInfo(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVAsmPrinter(), LLVMInitializeSPIRVTarget(), LLVMInitializeSPIRVTargetInfo(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZAsmParser(), LLVMInitializeSystemZAsmPrinter(), LLVMInitializeSystemZTarget(), LLVMInitializeSystemZTargetInfo(), LLVMInitializeVEAsmPrinter(), LLVMInitializeVETarget(), LLVMInitializeVETargetInfo(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyAsmParser(), LLVMInitializeWebAssemblyAsmPrinter(), LLVMInitializeWebAssemblyTarget(), LLVMInitializeWebAssemblyTargetInfo(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86AsmParser(), LLVMInitializeX86AsmPrinter(), LLVMInitializeX86Target(), LLVMInitializeX86TargetInfo(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreAsmPrinter(), LLVMInitializeXCoreTarget(), LLVMInitializeXCoreTargetInfo(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaAsmParser(), LLVMInitializeXtensaTargetInfo(), LowerADDSAT_SUBSAT(), lowerAddSubToHorizontalOp(), LowerCTTZ(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), LowerFLDEXP(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), lowerFPToIntToFP(), llvm::AMDGPUTargetLowering::LowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::LegalizerHelper::lowerIntrinsicRound(), LowerPARITY(), LowerSDIV_v4i8(), llvm::VETargetLowering::lowerToVVP(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_UnOp(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapVectorN(), MatchBinaryOp(), matchBinaryOp(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCommuteShift(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchIntPart(), matchLogicBlend(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchSubAddSameReg(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), mergeEltWithShuffle(), MinOptional(), moveAddAfterMinMax(), llvm::MulOverflow(), narrowExtractedVectorBinOp(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), llvm::neg(), llvm::bfi_detail::BlockMass::operator!=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator!=(), llvm::DebugValueUser::operator!=(), llvm::DIExpression::expr_op_iterator::operator!=(), llvm::DIFile::ChecksumInfo< T >::operator!=(), llvm::DITypeRefArray::iterator::operator!=(), llvm::DwarfStringPoolEntryRef::operator!=(), llvm::OnDiskChainedHashTable< Info >::iterator::operator!=(), llvm::ScaledNumber< DigitsT >::operator!=(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator!=(), llvm::TrackingMDRef::operator!=(), llvm::TypedMDOperandIterator< T >::operator!=(), llvm::TypedTrackingMDRef< T >::operator!=(), llvm::ScaledNumber< DigitsT >::operator*=(), llvm::bfi_detail::BlockMass::operator+=(), llvm::ScaledNumber< DigitsT >::operator+=(), llvm::bfi_detail::BlockMass::operator-=(), llvm::ScaledNumber< DigitsT >::operator-=(), llvm::ScaledNumber< DigitsT >::operator/=(), llvm::bfi_detail::BlockMass::operator<(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<(), llvm::ScaledNumber< DigitsT >::operator<(), llvm::bfi_detail::operator<<(), llvm::detail::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::bfi_detail::BlockMass::operator<=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<=(), llvm::ScaledNumber< DigitsT >::operator<=(), llvm::AllocatorList< T, AllocatorT >::operator=(), llvm::AllocatorList< T, AllocatorT >::operator=(), llvm::DebugValueUser::operator=(), llvm::DebugValueUser::operator=(), llvm::DIEValue::operator=(), llvm::DynamicAPInt::operator=(), llvm::iplist< T, Options >::operator=(), llvm::iplist_impl< IntrusiveListT, TraitsT >::operator=(), llvm::simple_ilist< T, Options >::operator=(), llvm::TrackingMDRef::operator=(), llvm::TrackingMDRef::operator=(), llvm::TypedTrackingMDRef< T >::operator=(), llvm::TypedTrackingMDRef< T >::operator=(), llvm::bfi_detail::BlockMass::operator==(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator==(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::ConstantPtrAuthKeyType::operator==(), llvm::DebugValueUser::operator==(), llvm::DIExpression::expr_op_iterator::operator==(), llvm::DIFile::ChecksumInfo< T >::operator==(), llvm::DITypeRefArray::iterator::operator==(), llvm::DwarfStringPoolEntryRef::operator==(), llvm::InlineAsmKeyType::operator==(), llvm::IntrusiveBackList< T >::const_iterator::operator==(), llvm::IntrusiveBackList< T >::iterator::operator==(), llvm::OnDiskChainedHashTable< Info >::iterator::operator==(), llvm::ScaledNumber< DigitsT >::operator==(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator==(), llvm::TrackingMDRef::operator==(), llvm::TypedMDOperandIterator< T >::operator==(), llvm::TypedTrackingMDRef< T >::operator==(), llvm::bfi_detail::BlockMass::operator>(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>(), llvm::ScaledNumber< DigitsT >::operator>(), llvm::bfi_detail::BlockMass::operator>=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>=(), llvm::ScaledNumber< DigitsT >::operator>=(), operator|=(), OptimizeAndOrXor(), optimizeBranch(), optimizeDivRem(), optimizeIncrementingWhile(), optimizeSymmetricCall(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::object::DirectX::PSVRuntimeInfo::parse(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), PerformExtractEltCombine(), performMulCombine(), PerformPREDICATE_CASTCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), performSubAddMULCombine(), PerformSubCSINCCombine(), performUzpCombine(), processAbsIntrinsic(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile(), llvm::DefaultFoldingSetTrait< T >::Profile(), llvm::DefaultFoldingSetTrait< T >::Profile(), llvm::FoldingSetTrait< SCEV >::Profile(), llvm::FoldingSetTrait< SCEVPredicate >::Profile(), llvm::FoldingSetTrait< SDVTListNode >::Profile(), llvm::FoldingSetTrait< T * >::Profile(), llvm::FoldingSetTrait< T, std::enable_if_t< std::is_enum< T >::value > >::Profile(), llvm::ImutProfileInfo< T >::Profile(), llvm::ImutProfileInfo< bool >::Profile(), llvm::ImutProfileInfo< T * >::Profile(), llvm::ImutProfileInteger< T >::Profile(), pushAddIntoCmovOfConsts(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), ReconstructTruncateFromBuildVector(), relocKindName(), llvm::SetVector< T, Vector, Set, N >::remove(), ReplaceAddWithADDP(), rotl64(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::SaturatingAdd(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), scalarizeBinOpOfSplats(), llvm::detail::scalbn(), llvm::scalbn(), llvm::RISCVDAGToDAGISel::Select(), llvm::cl::ExpansionContext::setCurrentDir(), llvm::cl::ExpansionContext::setMarkEOLs(), llvm::cl::ExpansionContext::setRelativeNames(), llvm::cl::ExpansionContext::setSearchDirs(), llvm::cl::ExpansionContext::setVFS(), llvm::AArch64TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLoweringBase::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLowering::ShrinkDemandedOp(), llvm::SignExtend32(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::simple_ilist< T, Options >::simple_ilist(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmps(), simplifyAndOrOfICmpsWithCtpop(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyCastInst(), simplifyCmpSelOfMaxMin(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFNegInst(), llvm::SelectionDAG::simplifyFPBinop(), simplifyFSubInst(), simplifyICmpOfBools(), simplifyICmpWithConstant(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLogicOfAddSub(), llvm::simplifyLoopAfterUnroll(), simplifyLShrInst(), simplifyMulInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmps(), simplifyRecipe(), simplifySelectBitTest(), simplifySelectInst(), simplifySelectWithICmpCond(), llvm::SelectionDAG::simplifyShift(), simplifyShift(), simplifyShlInst(), simplifySRemInst(), simplifySubInst(), simplifySwitchOnSelectUsingRanges(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), simplifyXorInst(), sinkMinMaxInBB(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), strongerOrdering(), llvm::ConstantRange::sub(), llvm::SubOverflow(), llvm::simple_ilist< T, Options >::swap(), takeLog2(), toHexStr(), toOctal(), llvm::objcopy::elf::SRecord::toString(), llvm::TrackingMDRef::TrackingMDRef(), translateExtract(), TruncIfPossible(), TryDistrubutionADDVecReduce(), tryLowerToSLI(), trySimplifyICmpWithAdds(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFRem(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), wrap(), and llvm::MCSection::~MCSection().