LLVM: llvm::cgdata Namespace Reference
llvm::cgdata Namespace Reference
Functions
bool hasOutlinedHashTree ()
const OutlinedHashTree * getOutlinedHashTree ()
bool emitCGData ()
void publishOutlinedHashTree (std::unique_ptr< OutlinedHashTree > HashTree)
void warn (Error E, StringRef Whence="")
void warn (Twine Message, std::string Whence="", std::string Hint="")
Function Documentation
emitCGData()
bool llvm::cgdata::emitCGData () inline
Definition at line 160 of file CodeGenData.h.
References llvm::CodeGenData::emitCGData(), and llvm::CodeGenData::getInstance().
getOutlinedHashTree()
const OutlinedHashTree * llvm::cgdata::getOutlinedHashTree () inline
Definition at line 156 of file CodeGenData.h.
References llvm::CodeGenData::getInstance(), and llvm::CodeGenData::getOutlinedHashTree().
Referenced by getMatchedEntries().
hasOutlinedHashTree()
bool llvm::cgdata::hasOutlinedHashTree () inline
Definition at line 152 of file CodeGenData.h.
References llvm::CodeGenData::getInstance(), and llvm::CodeGenData::hasOutlinedHashTree().
Referenced by getMatchedEntries().
publishOutlinedHashTree()
void llvm::cgdata::publishOutlinedHashTree (std::unique_ptr< OutlinedHashTree > HashTree) inline
Definition at line 163 of file CodeGenData.h.
References llvm::CodeGenData::getInstance(), and llvm::CodeGenData::publishOutlinedHashTree().
warn() [1/2]
void llvm::cgdata::warn (Error E, StringRef Whence = "")
Definition at line 210 of file CodeGenData.cpp.
References llvm::handleAllErrors(), llvm::CGDataError::message(), llvm::StringRef::str(), and warn().
Referenced by llvm::CodeGenData::getInstance(), and warn().
warn() [2/2]
void llvm::cgdata::warn (Twine Message, std::string Whence = "", std::string Hint = "")
Definition at line 201 of file CodeGenData.cpp.
References llvm::errs(), llvm::WithColor::note(), and llvm::WithColor::warning().