LLVM: llvm::sandboxir Namespace Reference
llvm::sandboxir Namespace Reference
Classes
class AddrSpaceCastInst
class AllocaInst
class Argument
Argument of a sandboxir::Function.
class ArrayType
class AtomicCmpXchgInst
class AtomicRMWInst
class BinaryOperator
class BitCastInst
class BlockAddress
class BottomUpVec
class BranchInst
class CallBase
class CallBrInst
class CallInst
class CastInst
class CastInstImpl
class CatchPadInst
class CatchReturnInst
class CatchSwitchAddHandler
class CatchSwitchInst
class CleanupPadInst
class CleanupReturnInst
class CmpInst
class CmpSwapOperands
class Constant
class ConstantAggregate
Base class for aggregate constants (with operands).
class ConstantAggregateZero
class ConstantArray
class ConstantExpr
class ConstantFP
class ConstantInt
class ConstantPointerNull
class ConstantPtrAuth
class ConstantStruct
class ConstantTokenNone
class ConstantVector
class Context
class CreateAndInsertInst
class DependencyGraph
class DGNode
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
class DSOLocalEquivalent
class EraseFromParent
class ExtractElementInst
class ExtractValueInst
class FCmpInst
class FenceInst
class FixedVectorType
class FPExtInst
class FPToSIInst
class FPToUIInst
class FPTruncInst
class FreezeInst
class FuncletPadInst
class Function
class FunctionPass
A pass that runs on a sandbox::Function.
class FunctionPassManager
class FunctionType
class GenericSetter
This class can be used for tracking most instruction setters.
class GenericSetterWithIdx
Similar to GenericSetter but the setters/getters have an index as their first argument.
class GetElementPtrInst
class GlobalAlias
class GlobalIFunc
class GlobalObject
class GlobalValue
class GlobalVariable
class GlobalWithNodeAPI
Provides API functions, like getIterator() and getReverseIterator() to GlobalIFunc, Function, GlobalVariable and GlobalAlias.
class ICmpInst
class InsertElementInst
class InsertIntoBB
class InsertValueInst
class Instruction
A sandboxir::User with operands, opcode and linked with previous/next instructions in an instruction list.
class IntegerType
Class to represent integer types.
class Interval
class IntervalIterator
A simple iterator for iterating the interval.
class IntToPtrInst
class InvokeInst
class IRChangeBase
The base class for IR Change classes.
class LandingPadInst
class LegalityAnalysis
Performs the legality analysis and returns a LegalityResult object.
class LegalityResult
The legality outcome is represented by a class rather than an enum class because in some cases the legality checks are expensive and look for a particular instruction that can be passed along to the vectorizer to avoid repeating the same expensive computation.
class LoadInst
class Module
In SandboxIR the Module is mainly used to access the list of global objects.
class MoveInstr
class NoCFIValue
class OpaqueInst
An LLLVM Instruction that has no SandboxIR equivalent class gets mapped to an OpaqueInstr.
class OperandUseIterator
Iterator for the Use edges of a User's operands.
class Pass
The base class of a Sandbox IR Pass.
class PassManager
Base class.
class PassRegistry
Owns the passes and provides an API to get a pass by its name.
class PHIAddIncoming
class PHINode
class PHIRemoveIncoming
class PointerType
class PoisonValue
class PossiblyDisjointInst
An or instruction, which can be marked as "disjoint", indicating that the inputs don't have a 1 in the same bit position.
class PossiblyNonNegInst
Instruction that can have a nneg flag (zext/uitofp).
class PtrToIntInst
class Region
The main job of the Region is to point to new instructions generated by vectorization passes.
class RemoveFromParent
class ResumeInst
class ReturnInst
class ScalableVectorType
class SelectInst
class SExtInst
class ShuffleVectorInst
class ShuffleVectorSetMask
class SingleLLVMInstructionImpl
Instructions that contain a single LLVM Instruction can inherit from this.
class SIToFPInst
class StoreInst
class StructType
class SwitchAddCase
class SwitchInst
class SwitchRemoveCase
class Tracker
The tracker collects all the change objects and implements the main API for saving / reverting / accepting.
class TruncInst
class Type
Just like llvm::Type these are immutable, unique, never get freed and can only be created via static factory methods.
class UIToFPInst
class UnaryInstruction
An abstract class, parent of unary instructions.
class UnaryOperator
class UndefValue
class UnreachableInst
class Use
Represents a Def-use/Use-def edge in SandboxIR.
class User
A sandboxir::User has operands.
class UserUseIterator
Iterator for the Use edges of a Value's users.
class UseSet
Tracks the change of the source Value of a sandboxir::Use.
class UseSwap
Tracks swapping a Use with another Use.
class Utils
class VAArgInst
class Value
A SandboxIR Value has users. This is the base class.
class VectorType
class Widen
class ZExtInst
Typedefs
using iterator = BBIterator
Enumerations
enum class LegalityResultID { Widen }
Functions
BasicBlock (llvm::BasicBlock *BB, Context &SBCtx)
~BasicBlock ()=default
static bool classof (const Value *From)
For isa/dyn_cast.
Function * getParent () const
iterator begin () const
iterator end () const
std::reverse_iterator< iterator > rbegin () const
std::reverse_iterator< iterator > rend () const
Context & getContext () const
Instruction * getTerminator () const
bool empty () const
Instruction & front () const
Instruction & back () const
void verify () const final
void dumpOS (raw_ostream &OS) const final
static llvm::Instruction::CastOps getLLVMCastOp (Instruction::Opcode Opc)
static llvm::Instruction::UnaryOps getLLVMUnaryOp (Instruction::Opcode Opc)
\Returns the LLVM opcode that corresponds to Opc.
static llvm::Instruction::BinaryOps getLLVMBinaryOp (Instruction::Opcode Opc)
\Returns the LLVM opcode that corresponds to Opc.
static llvm::SmallVector< Value *, 4 > collectSeeds (BasicBlock &BB)
static SmallVector< Value *, 4 > getOperand (ArrayRef< Value * > Bndl, unsigned OpIdx)
Typedef Documentation
iterator
using llvm::sandboxir::iterator = BBIterator
Definition at line 86 of file BasicBlock.h.
Enumeration Type Documentation
LegalityResultID
enum class llvm::sandboxir::LegalityResultID strong
Enumerator
Widen
Definition at line 22 of file Legality.h.
Function Documentation
back()
Instruction & llvm::sandboxir::back () const
BasicBlock()
llvm::sandboxir::BasicBlock (llvm::BasicBlock * BB, Context & SBCtx)
Definition at line 74 of file BasicBlock.h.
begin()
iterator llvm::sandboxir::begin () const
Referenced by empty(), llvm::sandboxir::Instruction::getPrevNode(), and rend().
classof()
static bool llvm::sandboxir::classof (const Value * From) static
For isa/dyn_cast.
Definition at line 82 of file BasicBlock.h.
References From.
collectSeeds()
static llvm::SmallVector< Value *, 4 > llvm::sandboxir::collectSeeds (BasicBlock & BB) static
Definition at line 19 of file BottomUpVec.cpp.
References llvm::dyn_cast(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::sandboxir::BottomUpVec::runOnFunction().
dumpOS()
void llvm::sandboxir::dumpOS (raw_ostream & OS) const final
empty()
bool llvm::sandboxir::empty () const
Definition at line 100 of file BasicBlock.h.
References begin(), and end().
Referenced by llvm::sandboxir::Instruction::eraseFromParent().
end()
iterator llvm::sandboxir::end () const
Definition at line 88 of file BasicBlock.h.
References llvm::cast().
Referenced by empty(), llvm::sandboxir::Instruction::getNextNode(), and rbegin().
front()
Instruction & llvm::sandboxir::front () const
getContext()
Context & llvm::sandboxir::getContext () const
Definition at line 98 of file BasicBlock.h.
Referenced by llvm::sandboxir::Constant::getParent(), and llvm::sandboxir::ConstantStruct::getTypeForElements().
getLLVMBinaryOp()
static llvm::Instruction::BinaryOps llvm::sandboxir::getLLVMBinaryOp (Instruction::Opcode Opc) static
\Returns the LLVM opcode that corresponds to Opc.
Definition at line 1408 of file Instruction.cpp.
References llvm_unreachable, and llvm::sandboxir::Instruction::Opc.
Referenced by llvm::sandboxir::BinaryOperator::create().
getLLVMCastOp()
static llvm::Instruction::CastOps llvm::sandboxir::getLLVMCastOp (Instruction::Opcode Opc) static
Definition at line 1170 of file Instruction.cpp.
References llvm::sandboxir::Instruction::Opc.
Referenced by llvm::sandboxir::CastInst::create().
getLLVMUnaryOp()
static llvm::Instruction::UnaryOps llvm::sandboxir::getLLVMUnaryOp (Instruction::Opcode Opc) static
\Returns the LLVM opcode that corresponds to Opc.
Definition at line 1205 of file Instruction.cpp.
Referenced by llvm::sandboxir::UnaryOperator::create().
getOperand()
static SmallVector< Value *, 4 > llvm::sandboxir::getOperand (ArrayRef< Value * > Bndl, unsigned OpIdx) static
Definition at line 27 of file BottomUpVec.cpp.
References llvm::cast(), and Operands.
Referenced by llvm::sandboxir::ExtractValueInst::getAggregateOperand(), llvm::sandboxir::ExtractValueInst::getAggregateOperand(), llvm::sandboxir::InsertValueInst::getAggregateOperand(), llvm::sandboxir::InsertValueInst::getAggregateOperand(), llvm::sandboxir::CallBase::getArgOperand(), llvm::sandboxir::SelectInst::getCondition(), llvm::sandboxir::SelectInst::getCondition(), llvm::sandboxir::SelectInst::getFalseValue(), llvm::sandboxir::SelectInst::getFalseValue(), llvm::sandboxir::ExtractElementInst::getIndexOperand(), llvm::sandboxir::ExtractElementInst::getIndexOperand(), llvm::sandboxir::InsertValueInst::getInsertedValueOperand(), llvm::sandboxir::InsertValueInst::getInsertedValueOperand(), llvm::sandboxir::AddrSpaceCastInst::getPointerOperand(), llvm::sandboxir::CatchSwitchInst::getSuccessor(), llvm::sandboxir::SelectInst::getTrueValue(), llvm::sandboxir::SelectInst::getTrueValue(), llvm::sandboxir::ExtractElementInst::getVectorOperand(), and llvm::sandboxir::ExtractElementInst::getVectorOperand().
getParent()
Function * llvm::sandboxir::getParent () const
getTerminator()
Instruction * llvm::sandboxir::getTerminator () const
rbegin()
std::reverse_iterator< iterator > llvm::sandboxir::rbegin () const
Definition at line 92 of file BasicBlock.h.
References end().
rend()
std::reverse_iterator< iterator > llvm::sandboxir::rend () const
Definition at line 95 of file BasicBlock.h.
References begin().
verify()
void llvm::sandboxir::verify () const final
~BasicBlock()
llvm::sandboxir::~BasicBlock () default