LLVM: llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t > Struct Template Reference
llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t > Struct Template Reference
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
VPScalarIVSteps_match (Op0_t Op0, Op1_t Op1)
bool match (const VPValue *V) const
bool match (const VPRecipeBase *R) const
Public Attributes
Op0_t Op0
Op1_t Op1
Detailed Description
template<typename Op0_t, typename Op1_t>
struct llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >
Definition at line 331 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
VPScalarIVSteps_match()
template<typename Op0_t , typename Op1_t > llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::VPScalarIVSteps_match (Op0_t Op0, Op1_t Op1) inline
Definition at line 335 of file VPlanPatternMatch.h.
Member Function Documentation
match() [1/2]
template<typename Op0_t , typename Op1_t > bool llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match (const VPRecipeBase * R) const inline
Definition at line 342 of file VPlanPatternMatch.h.
References assert(), llvm::isa(), llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::Op0, and llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::Op1.
match() [2/2]
template<typename Op0_t , typename Op1_t > bool llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match (const VPValue * V) const inline
Definition at line 337 of file VPlanPatternMatch.h.
References llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match().
Referenced by llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match().
Member Data Documentation
Op0
template<typename Op0_t , typename Op1_t > Op0_t llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::Op0
Definition at line 332 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match().
Op1
template<typename Op0_t , typename Op1_t > Op1_t llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::Op1
Definition at line 333 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::VPScalarIVSteps_match< Op0_t, Op1_t >::match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h