LLVM: llvm::VPlanTransforms Struct Reference
llvm::VPlanTransforms Struct Reference
#include "Transforms/Vectorize/VPlanTransforms.h"
Static Public Member Functions
static void VPInstructionsToVPRecipes (VPlanPtr &Plan, function_ref< const InductionDescriptor *(PHINode *)> GetIntOrFpInductionDescriptor, ScalarEvolution &SE, const TargetLibraryInfo &TLI)
Replaces the VPInstructions in Plan with corresponding widen recipes.
static bool adjustFixedOrderRecurrences (VPlan &Plan, VPBuilder &Builder)
Sink users of fixed-order recurrences after the recipe defining their previous value.
static void clearReductionWrapFlags (VPlan &Plan)
Clear NSW/NUW flags from reduction instructions if necessary.
static void unrollByUF (VPlan &Plan, unsigned UF, LLVMContext &Ctx)
Explicitly unroll Plan by UF.
static void optimizeForVFAndUF (VPlan &Plan, ElementCount BestVF, unsigned BestUF, PredicatedScalarEvolution &PSE)
Optimize Plan based on BestVF and BestUF.
static void optimize (VPlan &Plan)
Apply VPlan-to-VPlan optimizations to Plan, including induction recipe optimizations, dead recipe removal, replicate region optimizations and block merging.
static void createAndOptimizeReplicateRegions (VPlan &Plan)
Wrap predicated VPReplicateRecipes with a mask operand in an if-then region block and remove the mask operand.
static void addActiveLaneMask (VPlan &Plan, bool UseActiveLaneMaskForControlFlow, bool DataAndControlFlowWithoutRuntimeCheck)
Replace (ICMP_ULE, wide canonical IV, backedge-taken-count) checks with an (active-lane-mask recipe, wide canonical IV, trip-count).
static void truncateToMinimalBitwidths (VPlan &Plan, const MapVector< Instruction *, uint64_t > &MinBWs)
Insert truncates and extends for any truncated recipe.
static void dropPoisonGeneratingRecipes (VPlan &Plan, function_ref< bool(BasicBlock *)> BlockNeedsPredication)
Drop poison flags from recipes that may generate a poison value that is used after vectorization, even when their operands are not poison.
static bool tryAddExplicitVectorLength (VPlan &Plan)
Add a VPEVLBasedIVPHIRecipe and related recipes to Plan and replaces all uses except the canonical IV increment of VPCanonicalIVPHIRecipe with a VPEVLBasedIVPHIRecipe.
static void createInterleaveGroups (const SmallPtrSetImpl< const InterleaveGroup< Instruction > * > &InterleaveGroups, VPRecipeBuilder &RecipeBuilder, bool ScalarEpilogueAllowed)
static void removeDeadRecipes (VPlan &Plan)
Remove dead recipes from Plan.
Detailed Description
Definition at line 30 of file VPlanTransforms.h.
Member Function Documentation
addActiveLaneMask()
void VPlanTransforms::addActiveLaneMask (VPlan & Plan, bool UseActiveLaneMaskForControlFlow, bool DataAndControlFlowWithoutRuntimeCheck) static
Replace (ICMP_ULE, wide canonical IV, backedge-taken-count) checks with an (active-lane-mask recipe, wide canonical IV, trip-count).
If UseActiveLaneMaskForControlFlow is true, introduce an VPActiveLaneMaskPHIRecipe. If DataAndControlFlowWithoutRuntimeCheck is true, no minimum-iteration runtime check will be created (during skeleton creation) and instead it is handled using active-lane-mask. DataAndControlFlowWithoutRuntimeCheck implies UseActiveLaneMaskForControlFlow.
Definition at line 1319 of file VPlanTransforms.cpp.
References llvm::VPInstruction::ActiveLaneMask, addVPLaneMaskPhiAndUpdateExitBranch(), assert(), B, llvm::cast(), collectAllHeaderMasks(), llvm::DataAndControlFlowWithoutRuntimeCheck, llvm::find_if(), llvm::VPlan::getCanonicalIV(), llvm::VPBuilder::getToInsertAfter(), llvm::VPlan::getTripCount(), llvm::VPValue::replaceAllUsesWith(), and llvm::VPValue::users().
adjustFixedOrderRecurrences()
bool VPlanTransforms::adjustFixedOrderRecurrences (VPlan & Plan, VPBuilder & Builder) static
Sink users of fixed-order recurrences after the recipe defining their previous value.
Then introduce FirstOrderRecurrenceSplice VPInstructions to combine the value from the recurrence phis and previous values. The current implementation assumes all users can be sunk after the previous value, which is enforced by earlier legality checks.
Returns
true if all users of fixed-order recurrences could be re-arranged as needed or false if it is not possible. In the latter case, Plan is not valid.
Definition at line 774 of file VPlanTransforms.cpp.
References assert(), llvm::cast(), llvm::VPBuilder::createNaryOp(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::VPInstruction::FirstOrderRecurrenceSplice, llvm::VPRegionBlock::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::VPRecipeBase::getParent(), llvm::VPlan::getVectorLoopRegion(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::VPBasicBlock::phis(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::VPBuilder::setInsertPoint(), and sinkRecurrenceUsersAfterPrevious().
clearReductionWrapFlags()
void VPlanTransforms::clearReductionWrapFlags (VPlan & Plan) static
Clear NSW/NUW flags from reduction instructions if necessary.
Definition at line 833 of file VPlanTransforms.cpp.
References llvm::Add, collectUsersRecursively(), llvm::dyn_cast(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::VPlan::getVectorLoopRegion(), llvm::Mul, and llvm::VPBasicBlock::phis().
createAndOptimizeReplicateRegions()
void VPlanTransforms::createAndOptimizeReplicateRegions (VPlan & Plan) static
Wrap predicated VPReplicateRecipes with a mask operand in an if-then region block and remove the mask operand.
Optimize the created regions by iteratively sinking scalar operands into the region, followed by merging regions until no improvements are remaining.
Definition at line 407 of file VPlanTransforms.cpp.
References addReplicateRegions(), mergeBlocksIntoPredecessors(), mergeReplicateRegionsIntoSuccessors(), and sinkScalarOperands().
Referenced by optimize().
createInterleaveGroups()
void VPlanTransforms::createInterleaveGroups (const SmallPtrSetImpl< const InterleaveGroup< Instruction > * > & InterleaveGroups, VPRecipeBuilder & RecipeBuilder, bool ScalarEpilogueAllowed) static
Definition at line 1592 of file VPlanTransforms.cpp.
References llvm::cast(), llvm::dyn_cast_or_null(), llvm::VPRecipeBase::eraseFromParent(), llvm::VPRecipeBuilder::getRecipe(), llvm::VPDef::getVPSingleValue(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::VPValue::replaceAllUsesWith().
dropPoisonGeneratingRecipes()
void VPlanTransforms::dropPoisonGeneratingRecipes (VPlan & Plan, function_ref< bool(BasicBlock *)> BlockNeedsPredication) static
Drop poison flags from recipes that may generate a poison value that is used after vectorization, even when their operands are not poison.
Those recipes meet the following conditions:
Contribute to the address computation of a recipe generating a widen memory load/store (VPWidenMemoryInstructionRecipe or VPInterleaveRecipe).
Such a widen memory load/store has at least one underlying Instruction that is in a basic block that needs predication and after vectorization the generated instruction won't be predicated. Uses BlockNeedsPredication to check if a block needs predicating. TODO: Replace BlockNeedsPredication callback with retrieving info from VPlan directly.
Definition at line 1495 of file VPlanTransforms.cpp.
References A, assert(), B, llvm::VPBlockUtils::blocksOnly(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::SmallVectorBase< Size_T >::empty(), llvm::VPlan::getEntry(), llvm::InterleaveGroup< InstTy >::getMember(), llvm::InterleaveGroup< InstTy >::getNumMembers(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::VPValue::getUnderlyingValue(), llvm::VPDef::getVPSingleValue(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::PatternMatch::match(), llvm::VPUser::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::vp_depth_first_deep().
optimize()
void VPlanTransforms::optimize (VPlan & Plan) static
Apply VPlan-to-VPlan optimizations to Plan, including induction recipe optimizations, dead recipe removal, replicate region optimizations and block merging.
Definition at line 1155 of file VPlanTransforms.cpp.
References createAndOptimizeReplicateRegions(), legalizeAndOptimizeInductions(), licm, mergeBlocksIntoPredecessors(), removeDeadRecipes(), removeRedundantCanonicalIVs(), removeRedundantExpandSCEVRecipes(), removeRedundantInductionCasts(), and simplifyRecipes().
Referenced by llvm::LoopVectorizationPlanner::buildVPlans().
optimizeForVFAndUF()
void VPlanTransforms::optimizeForVFAndUF (VPlan & Plan, ElementCount BestVF, unsigned BestUF, PredicatedScalarEvolution & PSE) static
Optimize Plan based on BestVF and BestUF.
This may restrict the resulting plan to BestVF and BestUF.
Definition at line 668 of file VPlanTransforms.cpp.
References llvm::VPBasicBlock::appendRecipe(), assert(), llvm::VPBasicBlock::back(), llvm::VPInstruction::BranchOnCond, llvm::CallingConv::C, llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getElementCount(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::VPlan::getOrAddLiveIn(), llvm::vputils::getSCEVExprForVPValue(), llvm::PredicatedScalarEvolution::getSE(), llvm::VPlan::getTripCount(), llvm::ConstantInt::getTrue(), llvm::SCEV::getType(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::hasUF(), llvm::VPlan::hasVF(), llvm::CmpInst::ICMP_ULE, llvm::isa(), llvm::ScalarEvolution::isKnownPredicate(), llvm::SCEV::isZero(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::match(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::multiplyCoefficientBy(), recursivelyDeleteDeadRecipes(), llvm::VPlan::setUF(), and llvm::VPlan::setVF().
Referenced by llvm::LoopVectorizationPlanner::executePlan().
removeDeadRecipes()
void VPlanTransforms::removeDeadRecipes (VPlan & Plan) static
Remove dead recipes from Plan.
Definition at line 513 of file VPlanTransforms.cpp.
References llvm::VPBlockUtils::blocksOnly(), llvm::VPlan::getEntry(), isDeadRecipe(), llvm::make_early_inc_range(), and llvm::reverse().
Referenced by optimize(), and unrollByUF().
truncateToMinimalBitwidths()
void VPlanTransforms::truncateToMinimalBitwidths (VPlan & Plan, const MapVector< Instruction *, uint64_t > & MinBWs) static
Insert truncates and extends for any truncated recipe.
Redundant casts will be folded later.
Definition at line 1021 of file VPlanTransforms.cpp.
References llvm::all_of(), llvm::VPBasicBlock::appendRecipe(), assert(), llvm::VPBlockUtils::blocksOnly(), llvm::cast_or_null(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::contains(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::IntegerType::get(), llvm::VPlan::getCanonicalIV(), llvm::Type::getContext(), llvm::VPlan::getEntry(), llvm::Type::getScalarSizeInBits(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::VPValue::getUnderlyingValue(), llvm::VPlan::getVectorLoopRegion(), llvm::VPTypeAnalysis::inferScalarType(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::VPRecipeBase::insertBefore(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), llvm::make_early_inc_range(), llvm::PatternMatch::match(), llvm::VPValue::replaceAllUsesWith(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size(), and llvm::vp_depth_first_deep().
tryAddExplicitVectorLength()
bool VPlanTransforms::tryAddExplicitVectorLength (VPlan & Plan) static
Add a VPEVLBasedIVPHIRecipe and related recipes to Plan and replaces all uses except the canonical IV increment of VPCanonicalIVPHIRecipe with a VPEVLBasedIVPHIRecipe.
VPCanonicalIVPHIRecipe is only used to control the loop after this transformation.
Returns
true if the transformation succeeds, or false if it doesn't.
VPCanonicalIVPHIRecipe is used only for loop iterations counting after this transformation.
The function uses the following definitions: StartV is the canonical induction start value.
The function adds the following recipes:
vector.ph: ...
vector.body: ... EVLPhi = EXPLICIT-VECTOR-LENGTH-BASED-IV-PHI [ StartV, vector.ph ], [ NextEVLIV, vector.body ] AVL = sub original TC, EVLPhi VPEVL = EXPLICIT-VECTOR-LENGTH AVL ... NextEVLIV = add IVSize (cast i32 VPEVVL to IVSize), EVLPhi ...
Definition at line 1432 of file VPlanTransforms.cpp.
References llvm::any_of(), llvm::cast(), llvm::dwarf_linker::DebugLoc, llvm::VPInstruction::ExplicitVectorLength, llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getTripCount(), llvm::VPlan::getVectorLoopRegion(), llvm::VPRecipeBase::insertBefore(), llvm::VPlan::setUF(), and transformRecipestoEVLRecipes().
unrollByUF()
void VPlanTransforms::unrollByUF (VPlan & Plan, unsigned UF, LLVMContext & Ctx) static
Explicitly unroll Plan by UF.
Definition at line 396 of file VPlanUnroll.cpp.
References _, assert(), llvm::VPBlockUtils::blocksOnly(), llvm::VPInstruction::CanonicalIVIncrementForPart, Cleanup, llvm::dyn_cast(), llvm::VPlan::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getLiveOuts(), llvm::VPlan::getPreheader(), llvm::VPlan::getVectorLoopRegion(), H, llvm::isa(), llvm::make_early_inc_range(), llvm::make_scope_exit(), llvm::VPBasicBlock::phis(), removeDeadRecipes(), llvm::VPlan::setUF(), and llvm::vp_depth_first_deep().
Referenced by llvm::LoopVectorizationPlanner::executePlan().
VPInstructionsToVPRecipes()
void VPlanTransforms::VPInstructionsToVPRecipes (VPlanPtr & Plan, function_ref< const InductionDescriptor *(PHINode *)> GetIntOrFpInductionDescriptor, ScalarEvolution & SE, const TargetLibraryInfo & TLI) static
Replaces the VPInstructions in Plan with corresponding widen recipes.
Definition at line 34 of file VPlanTransforms.cpp.
References assert(), llvm::VPBlockUtils::blocksOnly(), llvm::cast(), llvm::dyn_cast(), GEP, llvm::VPDef::getNumDefinedValues(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::VPValue::getUnderlyingValue(), llvm::getVectorIntrinsicIDForCall(), llvm::VPDef::getVPSingleValue(), II, llvm::VPRecipeBase::insertBefore(), llvm::isa(), llvm::make_early_inc_range(), llvm::make_range(), llvm::User::operands(), and llvm::VPValue::replaceAllUsesWith().
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlanTransforms.h
lib/Transforms/Vectorize/VPlanTransforms.cpp
lib/Transforms/Vectorize/VPlanUnroll.cpp