LLVM: lib/Transforms/Vectorize/VPlanTransforms.cpp File Reference
VPlanTransforms.cpp File Reference
This file implements a set of utility VPlan to VPlan transformations.
#include "VPlanTransforms.h"
#include "VPRecipeBuilder.h"
#include "VPlan.h"
#include "VPlanAnalysis.h"
#include "VPlanCFG.h"
#include "VPlanDominatorTree.h"
#include "VPlanPatternMatch.h"
#include "VPlanUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PatternMatch.h"
Functions
static bool sinkScalarOperands (VPlan &Plan)
VPValue * getPredicatedMask (VPRegionBlock *R)
If R is a region with a VPBranchOnMaskRecipe in the entry block, return the mask.
static VPBasicBlock * getPredicatedThenBlock (VPRegionBlock *R)
If R is a triangle region, return the 'then' block of the triangle.
static bool mergeReplicateRegionsIntoSuccessors (VPlan &Plan)
static VPRegionBlock * createReplicateRegion (VPReplicateRecipe *PredRecipe, VPlan &Plan)
static void addReplicateRegions (VPlan &Plan)
static bool mergeBlocksIntoPredecessors (VPlan &Plan)
Remove redundant VPBasicBlocks by merging them into their predecessor if the predecessor has a single successor.
static void removeRedundantInductionCasts (VPlan &Plan)
Remove redundant casts of inductions.
static void removeRedundantCanonicalIVs (VPlan &Plan)
Try to replace VPWidenCanonicalIVRecipes with a widened canonical IV recipe, if it exists.
static bool isDeadRecipe (VPRecipeBase &R)
Returns true if R is dead and can be removed.
static VPScalarIVStepsRecipe * createScalarIVSteps (VPlan &Plan, InductionDescriptor::InductionKind Kind, Instruction::BinaryOps InductionOpcode, FPMathOperator *FPBinOp, Instruction *TruncI, VPValue *StartV, VPValue *Step, VPBuilder &Builder)
static void legalizeAndOptimizeInductions (VPlan &Plan)
Legalize VPWidenPointerInductionRecipe, by replacing it with a PtrAdd (IndStart, ScalarIVSteps (0, Step)) if only its scalar values are used, as VPWidenPointerInductionRecipe will generate vectors only.
static void removeRedundantExpandSCEVRecipes (VPlan &Plan)
Remove redundant EpxandSCEVRecipes in Plan's entry block by replacing them with already existing recipes expanding the same SCEV expression.
static void recursivelyDeleteDeadRecipes (VPValue *V)
static bool sinkRecurrenceUsersAfterPrevious (VPFirstOrderRecurrencePHIRecipe *FOR, VPRecipeBase *Previous, VPDominatorTree &VPDT)
Sink users of FOR after the recipe defining the previous value Previous of the recurrence.
static SmallVector< VPUser * > collectUsersRecursively (VPValue *V)
static void simplifyRecipe (VPRecipeBase &R, VPTypeAnalysis &TypeInfo)
Try to simplify recipe R.
static void licm (VPlan &Plan)
Move loop-invariant recipes out of the vector loop region in Plan.
static void simplifyRecipes (VPlan &Plan)
Try to simplify the recipes in Plan.
static VPActiveLaneMaskPHIRecipe * addVPLaneMaskPhiAndUpdateExitBranch (VPlan &Plan, bool DataAndControlFlowWithoutRuntimeCheck)
static SmallVector< VPValue * > collectAllHeaderMasks (VPlan &Plan)
Collect all VPValues representing a header mask through the (ICMP_ULE, WideCanonicalIV, backedge-taken-count) pattern.
static void transformRecipestoEVLRecipes (VPlan &Plan, VPValue &EVL)
Replace recipes with their EVL variants.
Detailed Description
This file implements a set of utility VPlan to VPlan transformations.
Definition in file VPlanTransforms.cpp.
Function Documentation
addReplicateRegions()
static void addReplicateRegions (VPlan & Plan) static
Definition at line 344 of file VPlanTransforms.cpp.
References llvm::VPBlockUtils::blocksOnly(), llvm::VPBlockUtils::connectBlocks(), createReplicateRegion(), llvm::VPBlockUtils::disconnectBlocks(), llvm::dyn_cast(), llvm::VPlan::getEntry(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::VPBlockBase::getParent(), llvm::Value::hasName(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::setName(), llvm::VPBasicBlock::splitAt(), llvm::SplitBlock(), and llvm::vp_depth_first_deep().
Referenced by llvm::VPlanTransforms::createAndOptimizeReplicateRegions().
addVPLaneMaskPhiAndUpdateExitBranch()
static VPActiveLaneMaskPHIRecipe * addVPLaneMaskPhiAndUpdateExitBranch (VPlan & Plan, bool DataAndControlFlowWithoutRuntimeCheck) static
Definition at line 1203 of file VPlanTransforms.cpp.
References llvm::VPInstruction::ActiveLaneMask, llvm::VPUser::addOperand(), llvm::VPInstruction::BranchOnCond, llvm::VPInstruction::CalculateTripCountMinusVF, llvm::VPInstruction::CanonicalIVIncrementForPart, llvm::cast(), llvm::DataAndControlFlowWithoutRuntimeCheck, llvm::dwarf_linker::DebugLoc, DL, llvm::VPRecipeBase::eraseFromParent(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::VPBlockBase::getSinglePredecessor(), llvm::VPBasicBlock::getTerminator(), llvm::VPlan::getTripCount(), and llvm::VPlan::getVectorLoopRegion().
Referenced by llvm::VPlanTransforms::addActiveLaneMask().
collectAllHeaderMasks()
static SmallVector< VPValue * > collectAllHeaderMasks (VPlan & Plan) static
Collect all VPValues representing a header mask through the (ICMP_ULE, WideCanonicalIV, backedge-taken-count) pattern.
TODO: Introduce explicit recipe for header-mask instead of searching for the header-mask pattern manually.
Definition at line 1278 of file VPlanTransforms.cpp.
References assert(), llvm::cast(), llvm::count_if(), llvm::dyn_cast(), llvm::iterator_range< IteratorT >::end(), llvm::find_if(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getVectorLoopRegion(), llvm::vputils::isHeaderMask(), llvm::VPBasicBlock::phis(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::VPValue::users().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), and transformRecipestoEVLRecipes().
collectUsersRecursively()
static SmallVector< VPUser * > collectUsersRecursively (VPValue * V) static
Definition at line 821 of file VPlanTransforms.cpp.
References llvm::VPDef::definedValues(), llvm::dyn_cast(), I, llvm::isa(), and Users.
Referenced by llvm::VPlanTransforms::clearReductionWrapFlags(), and transformRecipestoEVLRecipes().
createReplicateRegion()
static VPRegionBlock * createReplicateRegion (VPReplicateRecipe * PredRecipe, VPlan & Plan) static
Definition at line 308 of file VPlanTransforms.cpp.
References assert(), llvm::VPBlockUtils::connectBlocks(), llvm::VPRecipeBase::eraseFromParent(), llvm::VPReplicateRecipe::getMask(), llvm::VPValue::getNumUsers(), llvm::VPSingleDefRecipe::getUnderlyingInstr(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPReplicateRecipe::isUniform(), llvm::make_range(), llvm::VPUser::op_begin(), llvm::VPUser::op_end(), llvm::VPValue::replaceAllUsesWith(), and llvm::VPUser::setOperand().
Referenced by addReplicateRegions().
createScalarIVSteps()
static VPScalarIVStepsRecipe * createScalarIVSteps (VPlan & Plan, InductionDescriptor::InductionKind Kind, Instruction::BinaryOps InductionOpcode, FPMathOperator * FPBinOp, Instruction * TruncI, VPValue * StartV, VPValue * Step, VPBuilder & Builder) static
Definition at line 528 of file VPlanTransforms.cpp.
References assert(), llvm::cast(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::Type::getScalarSizeInBits(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::VPBlockBase::getSingleHierarchicalPredecessor(), llvm::Value::getType(), llvm::VPlan::getVectorLoopRegion(), llvm::VPTypeAnalysis::inferScalarType(), llvm::VPCanonicalIVPHIRecipe::isCanonical(), and llvm::Type::isIntegerTy().
Referenced by legalizeAndOptimizeInductions().
getPredicatedMask()
VPValue * getPredicatedMask (VPRegionBlock * R)
If R is a region with a VPBranchOnMaskRecipe in the entry block, return the mask.
Definition at line 189 of file VPlanTransforms.cpp.
References llvm::cast(), llvm::dyn_cast(), and llvm::isa().
Referenced by mergeReplicateRegionsIntoSuccessors().
getPredicatedThenBlock()
static VPBasicBlock * getPredicatedThenBlock (VPRegionBlock * R) static
If R is a triangle region, return the 'then' block of the triangle.
Definition at line 199 of file VPlanTransforms.cpp.
References llvm::cast(), and llvm::dyn_cast().
Referenced by mergeReplicateRegionsIntoSuccessors().
isDeadRecipe()
static bool isDeadRecipe (VPRecipeBase & R) static
Returns true if R is dead and can be removed.
Definition at line 494 of file VPlanTransforms.cpp.
References llvm::all_of(), llvm::dyn_cast(), llvm::PatternMatch::m_Intrinsic(), and llvm::PatternMatch::match().
Referenced by recursivelyDeleteDeadRecipes(), and llvm::VPlanTransforms::removeDeadRecipes().
legalizeAndOptimizeInductions()
static void legalizeAndOptimizeInductions (VPlan & Plan) static
Legalize VPWidenPointerInductionRecipe, by replacing it with a PtrAdd (IndStart, ScalarIVSteps (0, Step)) if only its scalar values are used, as VPWidenPointerInductionRecipe will generate vectors only.
If some users require vectors while other require scalars, the scalar uses need to extract the scalars from the generated vectors (Note that this is different to how int/fp inductions are handled). Also optimize VPWidenIntOrFpInductionRecipe, if any of its users needs scalar values, by providing them scalar steps built on the canonical scalar IV and update the original IV's users. This is an optional optimization to reduce the needs of vector extracts.
Definition at line 576 of file VPlanTransforms.cpp.
References createScalarIVSteps(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::VPRecipeBase::getDebugLoc(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::ElementCount::getFixed(), llvm::VPlan::getOrAddLiveIn(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::hasScalableVF(), llvm::VPlan::hasVF(), llvm::InductionDescriptor::IK_IntInduction, llvm::none_of(), llvm::VPBasicBlock::phis(), llvm::VPValue::replaceAllUsesWith(), and ToRemove.
Referenced by llvm::VPlanTransforms::optimize().
licm()
static void licm (VPlan & Plan) static
Move loop-invariant recipes out of the vector loop region in Plan.
Definition at line 974 of file VPlanTransforms.cpp.
References llvm::any_of(), llvm::VPBlockUtils::blocksOnly(), llvm::cast(), llvm::dyn_cast(), llvm::VPBasicBlock::end(), llvm::VPRegionBlock::getEntry(), llvm::VPBlockBase::getSinglePredecessor(), llvm::VPlan::getVectorLoopRegion(), llvm::make_early_inc_range(), and llvm::vp_depth_first_shallow().
mergeBlocksIntoPredecessors()
static bool mergeBlocksIntoPredecessors (VPlan & Plan) static
Remove redundant VPBasicBlocks by merging them into their predecessor if the predecessor has a single successor.
Definition at line 374 of file VPlanTransforms.cpp.
References llvm::VPBlockUtils::blocksOnly(), llvm::cast(), llvm::cast_or_null(), llvm::VPBlockUtils::connectBlocks(), llvm::VPBlockUtils::disconnectBlocks(), llvm::dyn_cast_or_null(), llvm::SmallVectorBase< Size_T >::empty(), llvm::VPBasicBlock::end(), llvm::VPlan::getEntry(), llvm::make_early_inc_range(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::to_vector(), and llvm::vp_depth_first_deep().
mergeReplicateRegionsIntoSuccessors()
static bool mergeReplicateRegionsIntoSuccessors (VPlan & Plan) static
Definition at line 221 of file VPlanTransforms.cpp.
References assert(), llvm::VPBlockUtils::blocksOnly(), llvm::cast(), llvm::VPBlockUtils::connectBlocks(), llvm::SetVector< T, Vector, Set, N >::contains(), llvm::VPBlockUtils::disconnectBlocks(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::SetVector< T, Vector, Set, N >::empty(), llvm::VPlan::getEntry(), llvm::VPBasicBlock::getFirstNonPhi(), getPredicatedMask(), getPredicatedThenBlock(), llvm::VPBlockBase::getSingleSuccessor(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::make_early_inc_range(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::VPValue::replaceUsesWithIf(), llvm::reverse(), and llvm::vp_depth_first_deep().
Referenced by llvm::VPlanTransforms::createAndOptimizeReplicateRegions().
recursivelyDeleteDeadRecipes()
static void recursivelyDeleteDeadRecipes (VPValue * V) static
Definition at line 649 of file VPlanTransforms.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorBase< Size_T >::empty(), llvm::VPValue::getDefiningRecipe(), llvm::SmallPtrSetImpl< PtrType >::insert(), isDeadRecipe(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::VPlanTransforms::optimizeForVFAndUF(), simplifyRecipe(), and transformRecipestoEVLRecipes().
removeRedundantCanonicalIVs()
static void removeRedundantCanonicalIVs (VPlan & Plan) static
Try to replace VPWidenCanonicalIVRecipes with a widened canonical IV recipe, if it exists.
Definition at line 458 of file VPlanTransforms.cpp.
References llvm::any_of(), llvm::dyn_cast(), llvm::VPRecipeBase::eraseFromParent(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getVectorLoopRegion(), llvm::vputils::onlyFirstLaneUsed(), llvm::VPBasicBlock::phis(), llvm::VPValue::replaceAllUsesWith(), and llvm::VPValue::users().
Referenced by llvm::VPlanTransforms::optimize().
removeRedundantExpandSCEVRecipes()
static void removeRedundantExpandSCEVRecipes (VPlan & Plan) static
Remove redundant EpxandSCEVRecipes in Plan's entry block by replacing them with already existing recipes expanding the same SCEV expression.
Definition at line 632 of file VPlanTransforms.cpp.
References llvm::dyn_cast(), llvm::VPlan::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and llvm::make_early_inc_range().
Referenced by llvm::VPlanTransforms::optimize().
removeRedundantInductionCasts()
static void removeRedundantInductionCasts (VPlan & Plan) static
Remove redundant casts of inductions.
Such redundant casts are casts of induction variables that can be ignored, because we already proved that the casted phi is equal to the uncasted phi in the vectorized loop. There is no need to vectorize the cast - the same value can be used for both the phi and casts in the vector loop.
Definition at line 425 of file VPlanTransforms.cpp.
References llvm::dyn_cast(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getVectorLoopRegion(), IV, llvm::VPBasicBlock::phis(), llvm::VPValue::replaceAllUsesWith(), llvm::reverse(), and llvm::VPValue::users().
Referenced by llvm::VPlanTransforms::optimize().
simplifyRecipe()
static void simplifyRecipe (VPRecipeBase & R, VPTypeAnalysis & TypeInfo) static
Try to simplify recipe R.
Definition at line 852 of file VPlanTransforms.cpp.
References A, assert(), llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::cast(), llvm::dyn_cast(), llvm::Type::getScalarSizeInBits(), I, llvm::VPTypeAnalysis::inferScalarType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), recursivelyDeleteDeadRecipes(), llvm::VPValue::replaceAllUsesWith(), llvm::SmallPtrSetImplBase::size(), X, and Y.
Referenced by simplifyRecipes().
simplifyRecipes()
static void simplifyRecipes (VPlan & Plan) static
Try to simplify the recipes in Plan.
Definition at line 1009 of file VPlanTransforms.cpp.
References llvm::VPBlockUtils::blocksOnly(), llvm::VPlan::getCanonicalIV(), llvm::VPlan::getEntry(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::make_early_inc_range(), and simplifyRecipe().
Referenced by llvm::VPlanTransforms::optimize().
sinkRecurrenceUsersAfterPrevious()
static bool sinkRecurrenceUsersAfterPrevious (VPFirstOrderRecurrencePHIRecipe * FOR, VPRecipeBase * Previous, VPDominatorTree & VPDT) static
Sink users of FOR after the recipe defining the previous value Previous of the recurrence.
Returns
true if all users of FOR could be re-arranged as needed or false if it is not possible.
Definition at line 719 of file VPlanTransforms.cpp.
References A, assert(), B, llvm::dyn_cast(), llvm::VPDef::getNumDefinedValues(), llvm::VPDef::getVPSingleValue(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::VPDominatorTree::properlyDominates(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), llvm::sort(), and llvm::VPValue::users().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences().
sinkScalarOperands()
static bool sinkScalarOperands (VPlan & Plan) static
Definition at line 109 of file VPlanTransforms.cpp.
References llvm::all_of(), llvm::VPBlockUtils::blocksOnly(), llvm::cast(), Changed, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::VPlan::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getSingleSuccessor(), llvm::VPBlockBase::getSuccessors(), llvm::VPSingleDefRecipe::getUnderlyingInstr(), llvm::VPlan::hasScalarVFOnly(), I, llvm::SetVector< T, Vector, Set, N >::insert(), llvm::isa(), llvm::VPRecipeBase::mayHaveSideEffects(), llvm::VPRecipeBase::mayReadOrWriteMemory(), llvm::VPRecipeBase::moveBefore(), llvm::VPUser::operands(), llvm::VPValue::replaceUsesWithIf(), llvm::SetVector< T, Vector, Set, N >::size(), llvm::SmallVectorBase< Size_T >::size(), llvm::VPValue::users(), and llvm::vp_depth_first_deep().
Referenced by llvm::VPlanTransforms::createAndOptimizeReplicateRegions().
transformRecipestoEVLRecipes()
static void transformRecipestoEVLRecipes (VPlan & Plan, VPValue & EVL) static
Replace recipes with their EVL variants.
Definition at line 1353 of file VPlanTransforms.cpp.
References assert(), llvm::TypeSwitch< T, ResultT >::Case(), collectAllHeaderMasks(), collectUsersRecursively(), llvm::Default, llvm::dyn_cast(), llvm::VPWidenMemoryRecipe::getMask(), llvm::VPDef::getNumDefinedValues(), llvm::VPDef::getVPSingleValue(), llvm::VPRecipeBase::insertBefore(), llvm::isa(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isUnaryOp(), recursivelyDeleteDeadRecipes(), and llvm::VPValue::replaceAllUsesWith().
Referenced by llvm::VPlanTransforms::tryAddExplicitVectorLength().