clang: lib/AST/APValue.cpp File Reference
APValue.cpp File Reference
#include "clang/AST/APValue.h"
#include "Linkage.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Type.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct clang::APValue::LV
struct clang::APValue::MemberPointerData
Namespaces
namespace clang
Functions
bool clang::operator== (const APValue::LValueBase &LHS, const APValue::LValueBase &RHS)
llvm::hash_code clang::hash_value (const APValue::LValueBase &Base)
static void profileIntValue (llvm::FoldingSetNodeID &ID, const llvm::APInt &V)
Profile the value of an APInt, excluding its bit-width.
static double GetApproxValue (const llvm::APFloat &F)
static bool TryPrintAsStringLiteral (raw_ostream &Out, const PrintingPolicy &Policy, const ArrayType *ATy, ArrayRef< APValue > Inits)
MutableArrayRef< APValue::LValuePathEntry > setLValueUninit (APValue::LValueBase B, const CharUnits &O, unsigned Size, bool OnePastTheEnd, bool IsNullPtr)
Function Documentation
GetApproxValue()
static double GetApproxValue (const llvm::APFloat & F) static
Definition at line 620 of file APValue.cpp.
References V.
Referenced by clang::APValue::printPretty(), and clang::TextNodeDumper::Visit().
profileIntValue()
static void profileIntValue (llvm::FoldingSetNodeID & ID, const llvm::APInt & V) static
Profile the value of an APInt, excluding its bit-width.
Definition at line 472 of file APValue.cpp.
References N, and V.
Referenced by clang::APValue::Profile().
setLValueUninit()
MutableArrayRef< APValue::LValuePathEntry > setLValueUninit (APValue::LValueBase B, const CharUnits & O, unsigned Size, bool OnePastTheEnd, bool IsNullPtr)
TryPrintAsStringLiteral()
static bool TryPrintAsStringLiteral (raw_ostream & Out, const PrintingPolicy & Policy, const ArrayType * ATy, ArrayRef< APValue > Inits) static
Definition at line 628 of file APValue.cpp.
References clang::PrintingPolicy::EntireContentsOfLargeArray, clang::escapeCStyle(), clang::ArrayType::getElementType(), clang::Type::isAnyCharacterType(), clang::isASCII(), clang::Type::isChar16Type(), clang::Type::isChar32Type(), clang::Type::isChar8Type(), clang::isPrintable(), and clang::Type::isWideCharType().
Referenced by clang::APValue::printPretty().