clang: lib/StaticAnalyzer/Core/CheckerManager.cpp File Reference
CheckerManager.cpp File Reference
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/Stmt.h"
#include "clang/Analysis/ProgramPoint.h"
#include "clang/Basic/JsonSupport.h"
#include "clang/Basic/LLVM.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include <cassert>
#include <vector>
Functions
template<typename CHECK_CTX >
static void expandGraphWithCheckers (CHECK_CTX checkCtx, ExplodedNodeSet &Dst, const ExplodedNodeSet &Src)
Function Documentation
expandGraphWithCheckers()
template<typename CHECK_CTX > static void expandGraphWithCheckers (CHECK_CTX checkCtx, ExplodedNodeSet & Dst, const ExplodedNodeSet & Src) static
Definition at line 111 of file CheckerManager.cpp.
References clang::ento::ExplodedNodeSet::clear(), clang::ento::ExplodedNodeSet::empty(), clang::ento::NodeBuilderContext::Eng, and clang::ento::ExplodedNodeSet::insert().
Referenced by clang::ento::CheckerManager::runCheckersForBeginFunction(), clang::ento::CheckerManager::runCheckersForBind(), clang::ento::CheckerManager::runCheckersForBranchCondition(), clang::ento::CheckerManager::runCheckersForCallEvent(), clang::ento::CheckerManager::runCheckersForDeadSymbols(), clang::ento::CheckerManager::runCheckersForLocation(), clang::ento::CheckerManager::runCheckersForNewAllocator(), clang::ento::CheckerManager::runCheckersForObjCMessage(), and clang::ento::CheckerManager::runCheckersForStmt().