clang: lib/StaticAnalyzer/Checkers/CheckSecuritySyntaxOnly.cpp File Reference
CheckSecuritySyntaxOnly.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define REGISTER_CHECKER(name)
Functions
static bool isArc4RandomAvailable (const ASTContext &Ctx)
static const DeclRefExpr * getIncrementedVar (const Expr *expr, const VarDecl *x, const VarDecl *y)
Macro Definition Documentation
REGISTER_CHECKER
#define REGISTER_CHECKER (name)
Value:
  void ento::register##name(CheckerManager &mgr) {                             \
    SecuritySyntaxChecker *checker = mgr.getChecker<SecuritySyntaxChecker>();  \
    checker->filter.check_##name = true;                                       \
    checker->filter.checkName_##name = mgr.getCurrentCheckerName();            \
  }                                                                            \
                                                                               \
  bool ento::shouldRegister##name(const CheckerManager &mgr) { return true; }
Definition at line 1082 of file CheckSecuritySyntaxOnly.cpp.
Function Documentation
getIncrementedVar()
static const DeclRefExpr * getIncrementedVar (const Expr * expr, const VarDecl * x, const VarDecl * y) static
Definition at line 229 of file CheckSecuritySyntaxOnly.cpp.
References clang::ast_matchers::expr, getIncrementedVar(), and clang::Expr::IgnoreParenCasts().
Referenced by getIncrementedVar().
isArc4RandomAvailable()
static bool isArc4RandomAvailable (const ASTContext & Ctx) static
Definition at line 27 of file CheckSecuritySyntaxOnly.cpp.
References clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().