clang: clang::ento::retaincountchecker::RetainCountChecker Class Reference
clang::ento::retaincountchecker::RetainCountChecker Class Reference
#include "/root/llvm-project/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h"
Public Member Functions
RetainCountChecker ()
RetainSummaryManager & getSummaryManager (ASTContext &Ctx) const
RetainSummaryManager & getSummaryManager (CheckerContext &C) const
void printState (raw_ostream &Out, ProgramStateRef State, const char *NL, const char *Sep) const override
See CheckerManager::runCheckersForPrintState.
void checkBind (SVal loc, SVal val, const Stmt *S, CheckerContext &C) const
void checkPostStmt (const BlockExpr *BE, CheckerContext &C) const
void checkPostStmt (const CastExpr *CE, CheckerContext &C) const
void checkPostStmt (const ObjCArrayLiteral *AL, CheckerContext &C) const
void checkPostStmt (const ObjCDictionaryLiteral *DL, CheckerContext &C) const
void checkPostStmt (const ObjCBoxedExpr *BE, CheckerContext &C) const
void checkPostStmt (const ObjCIvarRefExpr *IRE, CheckerContext &C) const
void checkPostCall (const CallEvent &Call, CheckerContext &C) const
void checkSummary (const RetainSummary &Summ, const CallEvent &Call, CheckerContext &C) const
void processSummaryOfInlined (const RetainSummary &Summ, const CallEvent &Call, CheckerContext &C) const
bool evalCall (const CallEvent &Call, CheckerContext &C) const
ProgramStateRef evalAssume (ProgramStateRef state, SVal Cond, bool Assumption) const
ProgramStateRef checkRegionChanges (ProgramStateRef state, const InvalidatedSymbols *invalidated, ArrayRef< const MemRegion * > ExplicitRegions, ArrayRef< const MemRegion * > Regions, const LocationContext *LCtx, const CallEvent *Call) const
ExplodedNode * checkReturnWithRetEffect (const ReturnStmt *S, CheckerContext &C, ExplodedNode *Pred, RetEffect RE, RefVal X, SymbolRef Sym, ProgramStateRef state) const
void checkDeadSymbols (SymbolReaper &SymReaper, CheckerContext &C) const
void checkBeginFunction (CheckerContext &C) const
void checkEndFunction (const ReturnStmt *RS, CheckerContext &C) const
ProgramStateRef updateSymbol (ProgramStateRef state, SymbolRef sym, RefVal V, ArgEffect E, RefVal::Kind &hasErr, CheckerContext &C) const
const RefCountBug & errorKindToBugKind (RefVal::Kind ErrorKind, SymbolRef Sym) const
void processNonLeakError (ProgramStateRef St, SourceRange ErrorRange, RefVal::Kind ErrorKind, SymbolRef Sym, CheckerContext &C) const
void processObjCLiterals (CheckerContext &C, const Expr *Ex) const
ProgramStateRef handleSymbolDeath (ProgramStateRef state, SymbolRef sid, RefVal V, SmallVectorImpl< SymbolRef > &Leaked) const
ProgramStateRef handleAutoreleaseCounts (ProgramStateRef state, ExplodedNode *Pred, const ProgramPointTag *Tag, CheckerContext &Ctx, SymbolRef Sym, RefVal V, const ReturnStmt *S=nullptr) const
ExplodedNode * processLeaks (ProgramStateRef state, SmallVectorImpl< SymbolRef > &Leaked, CheckerContext &Ctx, ExplodedNode *Pred=nullptr) const
Public Member Functions inherited from clang::ento::CheckerBase
StringRef getTagDescription () const override
CheckerNameRef getCheckerName () const
Public Member Functions inherited from clang::ProgramPointTag
ProgramPointTag (void *tagKind=nullptr)
virtual ~ProgramPointTag ()
const void * getTagKind () const
Used to implement 'isKind' in subclasses.
Static Public Member Functions
static const CheckerProgramPointTag & getDeallocSentTag ()
static const CheckerProgramPointTag & getCastFailTag ()
Static Public Member Functions inherited from clang::ento::Checker< check::Bind, check::DeadSymbols, check::BeginFunction, check::EndFunction, check::PostStmt< BlockExpr >, check::PostStmt< CastExpr >, check::PostStmt< ObjCArrayLiteral >, check::PostStmt< ObjCDictionaryLiteral >, check::PostStmt< ObjCBoxedExpr >, check::PostStmt< ObjCIvarRefExpr >, check::PostCall, check::RegionChanges, eval::Assume, eval::Call >
static void _register (CHECKER *checker, CheckerManager &mgr)
Static Public Member Functions inherited from clang::ento::check::Bind
template<typename CHECKER >
static void _register (CHECKER *checker, CheckerManager &mgr)
Public Attributes
std::unique_ptr< RefCountBug > UseAfterRelease
std::unique_ptr< RefCountBug > ReleaseNotOwned
std::unique_ptr< RefCountBug > DeallocNotOwned
std::unique_ptr< RefCountBug > FreeNotOwned
std::unique_ptr< RefCountBug > OverAutorelease
std::unique_ptr< RefCountBug > ReturnNotOwnedForOwned
std::unique_ptr< RefCountBug > LeakWithinFunction
std::unique_ptr< RefCountBug > LeakAtReturn
std::unique_ptr< RetainSummaryManager > Summaries
bool TrackObjCAndCFObjects = false
Track Objective-C and CoreFoundation objects.
bool TrackOSObjects = false
Track sublcasses of OSObject.
bool TrackNSCFStartParam = false
Track initial parameters (for the entry point) for NS/CF objects.
Static Public Attributes
static std::unique_ptr< CheckerProgramPointTag > DeallocSentTag
static std::unique_ptr< CheckerProgramPointTag > CastFailTag
Detailed Description
Definition at line 238 of file RetainCountChecker.h.
Constructor & Destructor Documentation
RetainCountChecker()
clang::ento::retaincountchecker::RetainCountChecker::RetainCountChecker () inline
Definition at line 278 of file RetainCountChecker.h.
Member Function Documentation
checkBeginFunction()
void RetainCountChecker::checkBeginFunction (CheckerContext & C) const
Definition at line 1332 of file RetainCountChecker.cpp.
References clang::ento::CheckerContext::addTransition(), clang::C, clang::ento::CF, clang::ento::DecRef, clang::AnyCall::forDecl(), clang::ento::Generalized, clang::ento::RetainSummary::getArgEffects(), clang::LocationContext::getDecl(), clang::ento::ArgEffect::getKind(), clang::ento::CheckerContext::getLocationContext(), clang::ento::ArgEffect::getObjKind(), clang::ento::CheckerContext::getState(), clang::ento::RetainSummaryManager::getSummary(), getSummaryManager(), clang::ento::CheckerContext::inTopFrame(), clang::ento::RetainSummaryManager::isTrustedReferenceCountImplementation(), clang::ento::retaincountchecker::RefVal::makeNotOwned(), clang::ento::retaincountchecker::RefVal::makeOwned(), clang::ento::ObjC, clang::ento::OS, setRefBinding(), and TrackNSCFStartParam.
checkBind()
void RetainCountChecker::checkBind (SVal loc, SVal val, const Stmt * S, CheckerContext & C) const
Definition at line 1138 of file RetainCountChecker.cpp.
References clang::C, clang::ento::SVal::getAsRegion(), and shouldEscapeRegion().
checkDeadSymbols()
void RetainCountChecker::checkDeadSymbols (SymbolReaper & SymReaper, CheckerContext & C) const
Definition at line 1410 of file RetainCountChecker.cpp.
References clang::C, clang::ento::retaincountchecker::getRefBinding(), handleAutoreleaseCounts(), handleSymbolDeath(), clang::ento::SymbolReaper::isDead(), processLeaks(), and V.
checkEndFunction()
void RetainCountChecker::checkEndFunction (const ReturnStmt * RS, CheckerContext & C) const
Definition at line 1368 of file RetainCountChecker.cpp.
References clang::ento::ExplodedNode::getLocationContext(), clang::ento::ExplodedNode::getState(), handleAutoreleaseCounts(), handleSymbolDeath(), and processLeaks().
checkPostCall()
void RetainCountChecker::checkPostCall (const CallEvent & Call, CheckerContext & C) const
Definition at line 363 of file RetainCountChecker.cpp.
References clang::C, checkSummary(), clang::ento::SVal::getAsLocSymbol(), clang::ento::retaincountchecker::getRefBinding(), getSummary(), getSummaryManager(), processSummaryOfInlined(), and Summaries.
checkPostStmt() [1/6]
void RetainCountChecker::checkPostStmt (const BlockExpr * BE, CheckerContext & C) const
Definition at line 146 of file RetainCountChecker.cpp.
References clang::C, clang::cast(), clang::BlockExpr::getBlockDecl(), clang::ento::BlockDataRegion::referenced_vars_iterator::getCapturedRegion(), clang::ento::VarRegion::getDecl(), clang::ento::SubRegion::getSuperRegion(), clang::ento::MemRegionManager::getVarRegion(), and clang::BlockDecl::hasCaptures().
checkPostStmt() [2/6]
void RetainCountChecker::checkPostStmt (const CastExpr * CE, CheckerContext & C) const
Definition at line 182 of file RetainCountChecker.cpp.
References clang::C, clang::ento::CF, clang::ento::DecRefBridgedTransferred, clang::ObjCBridgedCastExpr::getBridgeKind(), clang::ento::retaincountchecker::getRefBinding(), clang::Expr::getType(), clang::ento::IncRef, clang::Type::isObjCObjectPointerType(), clang::OBC_Bridge, clang::OBC_BridgeRetained, clang::OBC_BridgeTransfer, clang::ento::ObjC, updateSymbol(), and clang::ento::ArgEffect::withKind().
checkPostStmt() [3/6]
void RetainCountChecker::checkPostStmt (const ObjCArrayLiteral * AL, CheckerContext & C) const
Definition at line 259 of file RetainCountChecker.cpp.
References clang::C, and processObjCLiterals().
checkPostStmt() [4/6]
void RetainCountChecker::checkPostStmt (const ObjCBoxedExpr * BE, CheckerContext & C) const
Definition at line 271 of file RetainCountChecker.cpp.
References clang::C, clang::ento::SVal::getAsSymbol(), clang::ento::ExplodedNode::getState(), clang::ento::ExplodedNode::getSVal(), clang::Expr::getType(), clang::ento::retaincountchecker::RefVal::makeNotOwned(), clang::ento::ObjC, and setRefBinding().
checkPostStmt() [5/6]
void RetainCountChecker::checkPostStmt (const ObjCDictionaryLiteral * DL, CheckerContext & C) const
Definition at line 265 of file RetainCountChecker.cpp.
References clang::C, and processObjCLiterals().
checkPostStmt() [6/6]
void RetainCountChecker::checkPostStmt (const ObjCIvarRefExpr * IRE, CheckerContext & C) const
Definition at line 285 of file RetainCountChecker.cpp.
References clang::C, clang::ento::CF, clang::ento::SymExpr::getOriginRegion(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::SymExpr::getType(), clang::ento::coreFoundation::isCFObjectRef(), clang::ento::ConditionTruthVal::isConstrainedTrue(), clang::ento::ConstraintManager::isNull(), clang::Type::isObjCRetainableType(), clang::ento::retaincountchecker::isSynthesizedAccessor(), clang::ento::retaincountchecker::RefVal::makeNotOwned(), clang::ento::retaincountchecker::RefVal::None, clang::ento::ObjC, setRefBinding(), and clang::ento::retaincountchecker::RefVal::withIvarAccess().
checkRegionChanges()
ProgramStateRef RetainCountChecker::checkRegionChanges (ProgramStateRef state, const InvalidatedSymbols * invalidated, ArrayRef< const MemRegion * > ExplicitRegions, ArrayRef< const MemRegion * > Regions, const LocationContext * LCtx, const CallEvent * Call) const
Definition at line 1184 of file RetainCountChecker.cpp.
References clang::ento::MemRegion::getAs(), removeRefBinding(), and clang::ento::MemRegion::StripCasts().
checkReturnWithRetEffect()
ExplodedNode * RetainCountChecker::checkReturnWithRetEffect (const ReturnStmt * S, CheckerContext & C, ExplodedNode * Pred, RetEffect RE, RefVal X, SymbolRef Sym, ProgramStateRef state) const
Definition at line 1067 of file RetainCountChecker.cpp.
References clang::ento::retaincountchecker::RefVal::AccessedDirectly, clang::C, clang::ento::retaincountchecker::RefVal::ErrorLeakReturned, clang::ento::retaincountchecker::RefVal::ErrorReturnedNotOwned, clang::ento::RetEffect::getKind(), clang::ento::RetEffect::isOwned(), LeakAtReturn, N, clang::ento::retaincountchecker::RefVal::None, clang::ento::RetEffect::NoRet, clang::ento::retaincountchecker::RefVal::ReturnedOwned, ReturnNotOwnedForOwned, setRefBinding(), and X().
checkSummary()
void RetainCountChecker::checkSummary (const RetainSummary & Summ, const CallEvent & Call, CheckerContext & C) const
Definition at line 605 of file RetainCountChecker.cpp.
References clang::C, clang::ento::Dealloc, clang::ento::RetainSummary::getArg(), clang::ento::CallEvent::getArgSourceRange(), clang::ento::CallEvent::getArgSVal(), clang::ento::SVal::getAsSymbol(), getDeallocSentTag(), clang::ento::ArgEffect::getKind(), clang::ento::RetEffect::getKind(), clang::ento::CallEvent::getNumArgs(), clang::ento::RetainSummaryManager::getObjAllocRetEffect(), clang::ento::CallEvent::getOriginExpr(), clang::ento::RetainSummary::getReceiverEffect(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::CallEvent::getResultType(), clang::ento::RetainSummary::getRetEffect(), GetReturnType(), clang::ento::CallEvent::getReturnValue(), getSummaryManager(), clang::ento::RetainSummary::getThisEffect(), clang::ento::RetEffect::MakeNoRet(), clang::ento::RetEffect::notOwned(), clang::ento::OS, clang::ento::RetEffect::OwnedWhenTrackedReceiver, processNonLeakError(), refValFromRetEffect(), setRefBinding(), shouldEscapeOSArgumentOnCall(), clang::ento::StopTrackingHard, updateOutParameters(), updateSymbol(), and V.
Referenced by checkPostCall().
errorKindToBugKind()
const RefCountBug & RetainCountChecker::errorKindToBugKind (RefVal::Kind ErrorKind, SymbolRef Sym) const
Definition at line 843 of file RetainCountChecker.cpp.
References DeallocNotOwned, clang::ento::retaincountchecker::RefVal::ErrorDeallocNotOwned, clang::ento::retaincountchecker::RefVal::ErrorReleaseNotOwned, clang::ento::retaincountchecker::RefVal::ErrorUseAfterRelease, FreeNotOwned, clang::Type::getPointeeCXXRecordDecl(), clang::ento::SymExpr::getType(), ReleaseNotOwned, and UseAfterRelease.
Referenced by processNonLeakError().
evalAssume()
ProgramStateRef RetainCountChecker::evalAssume (ProgramStateRef state, SVal Cond, bool Assumption) const
Definition at line 1151 of file RetainCountChecker.cpp.
References clang::ento::ConditionTruthVal::isConstrainedTrue().
evalCall()
bool RetainCountChecker::evalCall (const CallEvent & Call, CheckerContext & C) const
Definition at line 889 of file RetainCountChecker.cpp.
References clang::C, clang::ento::RetainSummaryManager::canEval(), clang::ento::SValBuilder::conjureSymbolVal(), clang::ento::SVal::getAs(), getCastFailTag(), getSummaryManager(), clang::QualType::isNull(), and clang::ento::SVal::isUnknown().
getCastFailTag()
static const CheckerProgramPointTag & clang::ento::retaincountchecker::RetainCountChecker::getCastFailTag () inline static
Definition at line 367 of file RetainCountChecker.h.
References CastFailTag.
Referenced by evalCall(), and clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
getDeallocSentTag()
static const CheckerProgramPointTag & clang::ento::retaincountchecker::RetainCountChecker::getDeallocSentTag () inline static
Definition at line 363 of file RetainCountChecker.h.
References DeallocSentTag.
Referenced by checkSummary(), and clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
getSummaryManager() [1/2]
RetainSummaryManager & clang::ento::retaincountchecker::RetainCountChecker::getSummaryManager (ASTContext & Ctx) const inline
Definition at line 280 of file RetainCountChecker.h.
References Summaries, TrackObjCAndCFObjects, and TrackOSObjects.
Referenced by checkBeginFunction(), checkPostCall(), checkSummary(), evalCall(), and getSummaryManager().
getSummaryManager() [2/2]
RetainSummaryManager & clang::ento::retaincountchecker::RetainCountChecker::getSummaryManager (CheckerContext & C) const inline
Definition at line 287 of file RetainCountChecker.h.
References clang::C, and getSummaryManager().
handleAutoreleaseCounts()
ProgramStateRef RetainCountChecker::handleAutoreleaseCounts (ProgramStateRef state, ExplodedNode * Pred, const ProgramPointTag * Tag, CheckerContext & Ctx, SymbolRef Sym, RefVal V, const ReturnStmt * S = nullptr) const
Definition at line 1208 of file RetainCountChecker.cpp.
References clang::ento::retaincountchecker::RefVal::AccessedDirectly, clang::ento::CheckerContext::emitReport(), clang::ento::retaincountchecker::RefVal::ErrorOverAutorelease, clang::ento::CheckerContext::generateSink(), clang::ento::CheckerContext::getASTContext(), clang::ASTContext::getLangOpts(), N, clang::ento::retaincountchecker::RefVal::None, clang::ento::retaincountchecker::RefVal::NotOwned, OverAutorelease, clang::ento::retaincountchecker::RefVal::ReturnedNotOwned, clang::ento::retaincountchecker::RefVal::ReturnedOwned, setRefBinding(), and V.
Referenced by checkDeadSymbols(), and checkEndFunction().
handleSymbolDeath()
ProgramStateRef RetainCountChecker::handleSymbolDeath (ProgramStateRef state, SymbolRef sid, RefVal V, SmallVectorImpl< SymbolRef > & Leaked) const
Definition at line 1286 of file RetainCountChecker.cpp.
References clang::ento::retaincountchecker::RefVal::ErrorLeak, clang::ento::retaincountchecker::RefVal::None, removeRefBinding(), setRefBinding(), and V.
Referenced by checkDeadSymbols(), and checkEndFunction().
printState()
void RetainCountChecker::printState (raw_ostream & Out, ProgramStateRef State, const char * NL, const char * Sep) const override virtual
See CheckerManager::runCheckersForPrintState.
Reimplemented from clang::ento::CheckerBase.
Definition at line 1456 of file RetainCountChecker.cpp.
processLeaks()
ExplodedNode * RetainCountChecker::processLeaks (ProgramStateRef state, SmallVectorImpl< SymbolRef > & Leaked, CheckerContext & Ctx, ExplodedNode * Pred = nullptr) const
Definition at line 1314 of file RetainCountChecker.cpp.
References clang::ento::CheckerContext::addTransition(), clang::ento::CheckerContext::emitReport(), clang::ento::CheckerContext::getASTContext(), clang::ASTContext::getLangOpts(), LeakAtReturn, LeakWithinFunction, and N.
Referenced by checkDeadSymbols(), and checkEndFunction().
processNonLeakError()
void RetainCountChecker::processNonLeakError (ProgramStateRef St, SourceRange ErrorRange, RefVal::Kind ErrorKind, SymbolRef Sym, CheckerContext & C) const
Definition at line 859 of file RetainCountChecker.cpp.
References clang::C, errorKindToBugKind(), clang::ento::retaincountchecker::getRefBinding(), N, and clang::ento::retaincountchecker::RefVal::None.
Referenced by checkSummary(), and processObjCLiterals().
processObjCLiterals()
void RetainCountChecker::processObjCLiterals (CheckerContext & C, const Expr * Ex) const
Definition at line 229 of file RetainCountChecker.cpp.
References clang::C, clang::Stmt::children(), clang::ento::ExplodedNode::getLocationContext(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::ExplodedNode::getSVal(), clang::Expr::getType(), clang::ento::retaincountchecker::RefVal::makeNotOwned(), clang::ento::MayEscape, clang::ento::ObjC, processNonLeakError(), setRefBinding(), updateSymbol(), and V.
Referenced by checkPostStmt(), and checkPostStmt().
processSummaryOfInlined()
void RetainCountChecker::processSummaryOfInlined (const RetainSummary & Summ, const CallEvent & Call, CheckerContext & C) const
Definition at line 448 of file RetainCountChecker.cpp.
References clang::C, clang::ento::RetainSummary::getArg(), clang::ento::CallEvent::getArgSVal(), clang::ento::SVal::getAsSymbol(), clang::ento::ArgEffect::getKind(), clang::ento::RetEffect::getKind(), clang::ento::CallEvent::getNumArgs(), clang::ento::RetainSummary::getReceiverEffect(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::RetainSummary::getRetEffect(), clang::ento::CallEvent::getReturnValue(), clang::ento::RetEffect::NoRetHard, removeRefBinding(), shouldEscapeOSArgumentOnCall(), clang::ento::StopTrackingHard, and V.
Referenced by checkPostCall().
updateSymbol()
ProgramStateRef RetainCountChecker::updateSymbol (ProgramStateRef state, SymbolRef sym, RefVal V, ArgEffect E, RefVal::Kind & hasErr, CheckerContext & C) const
Definition at line 711 of file RetainCountChecker.cpp.
References clang::ento::retaincountchecker::RefVal::AccessedDirectly, clang::ento::Autorelease, bool, clang::C, clang::ento::Dealloc, clang::ento::DecRef, clang::ento::DecRefAndStopTrackingHard, clang::ento::DecRefBridgedTransferred, clang::ento::DoNothing, clang::ento::retaincountchecker::RefVal::ErrorDeallocNotOwned, clang::ento::retaincountchecker::RefVal::ErrorReleaseNotOwned, clang::ento::retaincountchecker::RefVal::ErrorUseAfterRelease, clang::ento::ArgEffect::getKind(), clang::ento::ArgEffect::getObjKind(), clang::ento::IncRef, clang::ento::MayEscape, clang::ento::retaincountchecker::RefVal::NotOwned, clang::ento::ObjC, clang::ento::retaincountchecker::RefVal::Owned, clang::ento::retaincountchecker::RefVal::Released, removeRefBinding(), clang::ento::RetainedOutParameter, clang::ento::RetainedOutParameterOnNonZero, clang::ento::RetainedOutParameterOnZero, setRefBinding(), clang::ento::StopTracking, clang::ento::StopTrackingHard, clang::ento::UnretainedOutParameter, V, and clang::ento::ArgEffect::withKind().
Referenced by checkPostStmt(), checkSummary(), and processObjCLiterals().
Member Data Documentation
CastFailTag
std::unique_ptr< CheckerProgramPointTag > RetainCountChecker::CastFailTag static
Definition at line 267 of file RetainCountChecker.h.
Referenced by getCastFailTag().
DeallocNotOwned
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::DeallocNotOwned
Definition at line 257 of file RetainCountChecker.h.
Referenced by errorKindToBugKind().
DeallocSentTag
std::unique_ptr< CheckerProgramPointTag > RetainCountChecker::DeallocSentTag static
Definition at line 266 of file RetainCountChecker.h.
Referenced by getDeallocSentTag().
FreeNotOwned
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::FreeNotOwned
Definition at line 258 of file RetainCountChecker.h.
Referenced by errorKindToBugKind().
LeakAtReturn
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::LeakAtReturn
Definition at line 262 of file RetainCountChecker.h.
Referenced by checkReturnWithRetEffect(), and processLeaks().
LeakWithinFunction
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::LeakWithinFunction
Definition at line 261 of file RetainCountChecker.h.
Referenced by processLeaks().
OverAutorelease
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::OverAutorelease
Definition at line 259 of file RetainCountChecker.h.
Referenced by handleAutoreleaseCounts().
ReleaseNotOwned
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::ReleaseNotOwned
Definition at line 256 of file RetainCountChecker.h.
Referenced by errorKindToBugKind().
ReturnNotOwnedForOwned
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::ReturnNotOwnedForOwned
Definition at line 260 of file RetainCountChecker.h.
Referenced by checkReturnWithRetEffect().
Summaries
std::unique_ptr<RetainSummaryManager> clang::ento::retaincountchecker::RetainCountChecker::Summaries mutable
Definition at line 264 of file RetainCountChecker.h.
Referenced by checkPostCall(), and getSummaryManager().
TrackNSCFStartParam
bool clang::ento::retaincountchecker::RetainCountChecker::TrackNSCFStartParam = false
Track initial parameters (for the entry point) for NS/CF objects.
Definition at line 276 of file RetainCountChecker.h.
Referenced by checkBeginFunction().
TrackObjCAndCFObjects
bool clang::ento::retaincountchecker::RetainCountChecker::TrackObjCAndCFObjects = false
Track Objective-C and CoreFoundation objects.
Definition at line 270 of file RetainCountChecker.h.
Referenced by getSummaryManager().
TrackOSObjects
bool clang::ento::retaincountchecker::RetainCountChecker::TrackOSObjects = false
Track sublcasses of OSObject.
Definition at line 273 of file RetainCountChecker.h.
Referenced by getSummaryManager().
UseAfterRelease
std::unique_ptr<RefCountBug> clang::ento::retaincountchecker::RetainCountChecker::UseAfterRelease
Definition at line 255 of file RetainCountChecker.h.
Referenced by errorKindToBugKind().
The documentation for this class was generated from the following files:
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp