clang: clang::BlockInvocationContext Class Reference
clang::BlockInvocationContext Class Reference
It represents a block invocation (based on BlockCall).
#include "clang/Analysis/AnalysisDeclContext.h"
Public Member Functions
~BlockInvocationContext () override=default
const BlockDecl * getBlockDecl () const
const void * getData () const
void Profile (llvm::FoldingSetNodeID &ID) override
Public Member Functions inherited from clang::LocationContext
virtual ~LocationContext ()
ContextKind getKind () const
int64_t getID () const
LLVM_ATTRIBUTE_RETURNS_NONNULL AnalysisDeclContext * getAnalysisDeclContext () const
const LocationContext * getParent () const
It might return null.
bool isParentOf (const LocationContext *LC) const
const Decl * getDecl () const
CFG * getCFG () const
template<typename T >
T * getAnalysis () const
const ParentMap & getParentMap () const
const ImplicitParamDecl * getSelfDecl () const
const StackFrameContext * getStackFrame () const
virtual bool inTopFrame () const
LLVM_DUMP_METHOD void dumpStack (raw_ostream &Out) const
Prints out the call stack.
void printJson (raw_ostream &Out, const char *NL="\n", unsigned int Space=0, bool IsDot=false, std::function< void(const LocationContext *)> printMoreInfoPerContext=[](const LocationContext *) {}) const
Prints out the call stack in json format.
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, AnalysisDeclContext *ADC, const LocationContext *ParentLC, const BlockDecl *BD, const void *Data)
static bool classof (const LocationContext *LC)
Static Public Member Functions inherited from clang::LocationContext
static void ProfileCommon (llvm::FoldingSetNodeID &ID, ContextKind ck, AnalysisDeclContext *ctx, const LocationContext *parent, const void *data)
Friends
class LocationContextManager
Additional Inherited Members
Public Types inherited from clang::LocationContext
enum ContextKind { StackFrame , Block }
Protected Member Functions inherited from clang::LocationContext
LocationContext (ContextKind k, AnalysisDeclContext *ctx, const LocationContext *parent, int64_t ID)
Detailed Description
It represents a block invocation (based on BlockCall).
Definition at line 353 of file AnalysisDeclContext.h.
Constructor & Destructor Documentation
~BlockInvocationContext()
clang::BlockInvocationContext::~BlockInvocationContext () override default
Member Function Documentation
classof()
static bool clang::BlockInvocationContext::classof (const LocationContext * LC) inline static
Definition at line 382 of file AnalysisDeclContext.h.
References clang::LocationContext::Block, and clang::LocationContext::getKind().
getBlockDecl()
const BlockDecl * clang::BlockInvocationContext::getBlockDecl () const inline
Definition at line 369 of file AnalysisDeclContext.h.
getData()
const void * clang::BlockInvocationContext::getData () const inline
Definition at line 371 of file AnalysisDeclContext.h.
Profile() [1/2]
void BlockInvocationContext::Profile (llvm::FoldingSetNodeID & ID) override virtual
Implements clang::LocationContext.
Definition at line 420 of file AnalysisDeclContext.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::LocationContext::getParent(), and Profile().
Referenced by clang::LocationContextManager::getBlockInvocationContext(), and Profile().
Profile() [2/2]
static void clang::BlockInvocationContext::Profile (llvm::FoldingSetNodeID & ID, AnalysisDeclContext * ADC, const LocationContext * ParentLC, const BlockDecl * BD, const void * Data) inline static
Definition at line 375 of file AnalysisDeclContext.h.
References clang::LocationContext::Block, and clang::LocationContext::ProfileCommon().
Friends And Related Symbol Documentation
LocationContextManager
friend class LocationContextManager friend
Definition at line 354 of file AnalysisDeclContext.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/AnalysisDeclContext.h
lib/Analysis/AnalysisDeclContext.cpp