clang: clang::threadSafety::til::SApply Class Reference
clang::threadSafety::til::SApply Class Reference
Apply a self-argument to a self-applicable function.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
SApply (SExpr *Sf, SExpr *A=nullptr)
SApply (SApply &A, SExpr *Sf, SExpr *Ar=nullptr)
SExpr * sfun ()
const SExpr * sfun () const
SExpr * arg ()
const SExpr * arg () const
bool isDelegation () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const SApply *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Apply a self-argument to a self-applicable function.
Definition at line 874 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
SApply() [1/2]
clang::threadSafety::til::SApply::SApply (SExpr * Sf, SExpr * A = nullptr) inline
Definition at line 876 of file ThreadSafetyTIL.h.
SApply() [2/2]
clang::threadSafety::til::SApply::SApply (SApply & A, SExpr * Sf, SExpr * Ar = nullptr) inline
Definition at line 877 of file ThreadSafetyTIL.h.
Member Function Documentation
arg() [1/2]
SExpr * clang::threadSafety::til::SApply::arg () inline
Definition at line 885 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply().
arg() [2/2]
const SExpr * clang::threadSafety::til::SApply::arg () const inline
Definition at line 886 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::SApply::classof (const SExpr * E) inline static
Definition at line 880 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::SApply::compare (const SApply * E, C & Cmp) const inline
Definition at line 899 of file ThreadSafetyTIL.h.
References arg(), and sfun().
isDelegation()
bool clang::threadSafety::til::SApply::isDelegation () const inline
Definition at line 888 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply().
sfun() [1/2]
SExpr * clang::threadSafety::til::SApply::sfun () inline
Definition at line 882 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply().
sfun() [2/2]
const SExpr * clang::threadSafety::til::SApply::sfun () const inline
Definition at line 883 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::SApply::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 891 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h