clang: clang::threadSafety::CapabilityExpr Class Reference
clang::threadSafety::CapabilityExpr Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyCommon.h"
Public Member Functions
CapabilityExpr ()
CapabilityExpr (const til::SExpr *E, StringRef Kind, bool Neg)
template<typename T >
CapabilityExpr (const til::SExpr *, T, bool)=delete
const til::SExpr * sexpr () const
StringRef getKind () const
bool negative () const
CapabilityExpr operator! () const
bool equals (const CapabilityExpr &other) const
bool matches (const CapabilityExpr &other) const
bool matchesUniv (const CapabilityExpr &CapE) const
bool partiallyMatches (const CapabilityExpr &other) const
const ValueDecl * valueDecl () const
std::string toString () const
bool shouldIgnore () const
bool isInvalid () const
bool isUniversal () const
Detailed Description
Definition at line 271 of file ThreadSafetyCommon.h.
Constructor & Destructor Documentation
CapabilityExpr() [1/3]
clang::threadSafety::CapabilityExpr::CapabilityExpr () inline
Definition at line 280 of file ThreadSafetyCommon.h.
Referenced by operator!().
CapabilityExpr() [2/3]
clang::threadSafety::CapabilityExpr::CapabilityExpr (const til::SExpr * E, StringRef Kind, bool Neg) inline
Definition at line 281 of file ThreadSafetyCommon.h.
CapabilityExpr() [3/3]
template<typename T > clang::threadSafety::CapabilityExpr::CapabilityExpr (const til::SExpr * , T , bool) delete
Member Function Documentation
equals()
bool clang::threadSafety::CapabilityExpr::equals (const CapabilityExpr & other) const inline
Definition at line 295 of file ThreadSafetyCommon.h.
References clang::threadSafety::sx::equals(), negative(), and sexpr().
getKind()
StringRef clang::threadSafety::CapabilityExpr::getKind () const inline
Definition at line 288 of file ThreadSafetyCommon.h.
isInvalid()
bool clang::threadSafety::CapabilityExpr::isInvalid () const inline
Definition at line 332 of file ThreadSafetyCommon.h.
References clang::isa(), and sexpr().
isUniversal()
bool clang::threadSafety::CapabilityExpr::isUniversal () const inline
Definition at line 334 of file ThreadSafetyCommon.h.
References clang::isa(), and sexpr().
Referenced by matchesUniv().
matches()
bool clang::threadSafety::CapabilityExpr::matches (const CapabilityExpr & other) const inline
Definition at line 300 of file ThreadSafetyCommon.h.
References clang::threadSafety::sx::matches(), negative(), and sexpr().
Referenced by matchesUniv().
matchesUniv()
bool clang::threadSafety::CapabilityExpr::matchesUniv (const CapabilityExpr & CapE) const inline
Definition at line 305 of file ThreadSafetyCommon.h.
References isUniversal(), and matches().
negative()
bool clang::threadSafety::CapabilityExpr::negative () const inline
Definition at line 289 of file ThreadSafetyCommon.h.
Referenced by equals(), matches(), partiallyMatches(), toString(), and valueDecl().
operator!()
CapabilityExpr clang::threadSafety::CapabilityExpr::operator! () const inline
Definition at line 291 of file ThreadSafetyCommon.h.
References CapabilityExpr().
partiallyMatches()
bool clang::threadSafety::CapabilityExpr::partiallyMatches (const CapabilityExpr & other) const inline
Definition at line 309 of file ThreadSafetyCommon.h.
References negative(), clang::threadSafety::sx::partiallyMatches(), and sexpr().
sexpr()
const til::SExpr * clang::threadSafety::CapabilityExpr::sexpr () const inline
Definition at line 287 of file ThreadSafetyCommon.h.
Referenced by equals(), isInvalid(), isUniversal(), matches(), partiallyMatches(), shouldIgnore(), toString(), and valueDecl().
shouldIgnore()
bool clang::threadSafety::CapabilityExpr::shouldIgnore () const inline
Definition at line 330 of file ThreadSafetyCommon.h.
References sexpr().
toString()
std::string clang::threadSafety::CapabilityExpr::toString () const inline
Definition at line 324 of file ThreadSafetyCommon.h.
References negative(), sexpr(), and clang::threadSafety::sx::toString().
valueDecl()
const ValueDecl * clang::threadSafety::CapabilityExpr::valueDecl () const inline
Definition at line 314 of file ThreadSafetyCommon.h.
References negative(), P, and sexpr().
Referenced by clang::threadSafety::BeforeSet::insertAttrExprs().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyCommon.h