clang: clang::serialization::ReadMethodPoolVisitor Class Reference
clang::serialization::ReadMethodPoolVisitor Class Reference
Public Member Functions
ReadMethodPoolVisitor (ASTReader &Reader, Selector Sel, unsigned PriorGeneration)
bool operator() (ModuleFile &M)
ArrayRef< ObjCMethodDecl * > getInstanceMethods () const
Retrieve the instance methods found by this visitor.
ArrayRef< ObjCMethodDecl * > getFactoryMethods () const
Retrieve the instance methods found by this visitor.
unsigned getInstanceBits () const
unsigned getFactoryBits () const
bool instanceHasMoreThanOneDecl () const
bool factoryHasMoreThanOneDecl () const
Detailed Description
Definition at line 8196 of file ASTReader.cpp.
Constructor & Destructor Documentation
ReadMethodPoolVisitor()
clang::serialization::ReadMethodPoolVisitor::ReadMethodPoolVisitor (ASTReader & Reader, Selector Sel, unsigned PriorGeneration) inline
Definition at line 8208 of file ASTReader.cpp.
Member Function Documentation
factoryHasMoreThanOneDecl()
bool clang::serialization::ReadMethodPoolVisitor::factoryHasMoreThanOneDecl () const inline
Definition at line 8266 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
getFactoryBits()
unsigned clang::serialization::ReadMethodPoolVisitor::getFactoryBits () const inline
Definition at line 8260 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
getFactoryMethods()
ArrayRef< ObjCMethodDecl * > clang::serialization::ReadMethodPoolVisitor::getFactoryMethods () const inline
Retrieve the instance methods found by this visitor.
Definition at line 8255 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
getInstanceBits()
unsigned clang::serialization::ReadMethodPoolVisitor::getInstanceBits () const inline
Definition at line 8259 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
getInstanceMethods()
ArrayRef< ObjCMethodDecl * > clang::serialization::ReadMethodPoolVisitor::getInstanceMethods () const inline
Retrieve the instance methods found by this visitor.
Definition at line 8250 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
instanceHasMoreThanOneDecl()
bool clang::serialization::ReadMethodPoolVisitor::instanceHasMoreThanOneDecl () const inline
Definition at line 8262 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadMethodPool().
operator()()
bool clang::serialization::ReadMethodPoolVisitor::operator() (ModuleFile & M) inline
Definition at line 8212 of file ASTReader.cpp.
References clang::serialization::reader::ASTSelectorLookupTrait::data_type::Factory, clang::serialization::reader::ASTSelectorLookupTrait::data_type::FactoryBits, clang::serialization::reader::ASTSelectorLookupTrait::data_type::FactoryHasMoreThanOneDecl, clang::serialization::ModuleFile::Generation, clang::serialization::reader::ASTSelectorLookupTrait::data_type::ID, clang::serialization::reader::ASTSelectorLookupTrait::data_type::Instance, clang::serialization::reader::ASTSelectorLookupTrait::data_type::InstanceBits, clang::serialization::reader::ASTSelectorLookupTrait::data_type::InstanceHasMoreThanOneDecl, clang::serialization::ModuleFile::SelectorLookupTable, and clang::ASTDeserializationListener::SelectorRead().
The documentation for this class was generated from the following file:
lib/Serialization/ASTReader.cpp