clang: clang::StmtIteratorBase Class Reference
clang::StmtIteratorBase Class Reference
#include "clang/AST/StmtIterator.h"
Protected Types
enum { StmtMode = 0x0 , SizeOfTypeVAMode = 0x1 , DeclGroupMode = 0x2 , Flags = 0x3 }
Protected Member Functions
StmtIteratorBase (Stmt **s)
StmtIteratorBase (const VariableArrayType *t)
StmtIteratorBase (Decl **dgi, Decl **dge)
StmtIteratorBase ()
bool inDeclGroup () const
bool inSizeOfTypeVA () const
bool inStmt () const
const VariableArrayType * getVAPtr () const
void setVAPtr (const VariableArrayType *P)
void NextDecl (bool ImmediateAdvance=true)
bool HandleDecl (Decl *D)
void NextVA ()
Stmt *& GetDeclExpr () const
Protected Attributes
union {
Stmt ** stmt
Decl ** DGI
};
uintptr_t RawVAPtr = 0
Decl ** DGE
Detailed Description
Definition at line 27 of file StmtIterator.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
StmtMode
SizeOfTypeVAMode
DeclGroupMode
Flags
Definition at line 29 of file StmtIterator.h.
Constructor & Destructor Documentation
StmtIteratorBase() [1/4]
clang::StmtIteratorBase::StmtIteratorBase (Stmt ** s) inline protected
Definition at line 43 of file StmtIterator.h.
StmtIteratorBase() [2/4]
StmtIteratorBase::StmtIteratorBase (const VariableArrayType * t) protected
Definition at line 104 of file StmtIterator.cpp.
References RawVAPtr.
StmtIteratorBase() [3/4]
StmtIteratorBase::StmtIteratorBase (Decl ** dgi, Decl ** dge) protected
Definition at line 99 of file StmtIterator.cpp.
References NextDecl().
StmtIteratorBase() [4/4]
clang::StmtIteratorBase::StmtIteratorBase () inline protected
Definition at line 46 of file StmtIterator.h.
Member Function Documentation
GetDeclExpr()
Stmt *& StmtIteratorBase::GetDeclExpr () const protected
Definition at line 109 of file StmtIterator.cpp.
References clang::cast(), DGI, clang::VarDecl::getInitAddress(), getVAPtr(), and inDeclGroup().
Referenced by clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator*().
getVAPtr()
const VariableArrayType * clang::StmtIteratorBase::getVAPtr () const inline protected
Definition at line 60 of file StmtIterator.h.
References RawVAPtr.
Referenced by GetDeclExpr(), NextDecl(), NextVA(), and clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator++().
HandleDecl()
bool StmtIteratorBase::HandleDecl (Decl * D) protected
Definition at line 74 of file StmtIterator.cpp.
References FindVA(), and setVAPtr().
Referenced by NextDecl().
inDeclGroup()
bool clang::StmtIteratorBase::inDeclGroup () const inline protected
Definition at line 48 of file StmtIterator.h.
References DeclGroupMode, Flags, and RawVAPtr.
Referenced by GetDeclExpr(), NextDecl(), NextVA(), and setVAPtr().
inSizeOfTypeVA()
bool clang::StmtIteratorBase::inSizeOfTypeVA () const inline protected
Definition at line 52 of file StmtIterator.h.
References Flags, RawVAPtr, and SizeOfTypeVAMode.
Referenced by NextVA(), and setVAPtr().
inStmt()
bool clang::StmtIteratorBase::inStmt () const inline protected
Definition at line 56 of file StmtIterator.h.
References Flags, RawVAPtr, and StmtMode.
Referenced by clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator*(), and clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator++().
NextDecl()
void StmtIteratorBase::NextDecl (bool ImmediateAdvance = true) protected
Definition at line 60 of file StmtIterator.cpp.
References DGE, DGI, getVAPtr(), HandleDecl(), inDeclGroup(), and RawVAPtr.
Referenced by NextVA(), clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator++(), and StmtIteratorBase().
NextVA()
void StmtIteratorBase::NextVA () protected
Definition at line 37 of file StmtIterator.cpp.
References DGI, FindVA(), clang::ArrayType::getElementType(), clang::QualType::getTypePtr(), getVAPtr(), inDeclGroup(), inSizeOfTypeVA(), NextDecl(), RawVAPtr, and setVAPtr().
Referenced by clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator++().
setVAPtr()
void clang::StmtIteratorBase::setVAPtr (const VariableArrayType * P) inline protected
Definition at line 64 of file StmtIterator.h.
References Flags, inDeclGroup(), inSizeOfTypeVA(), P, and RawVAPtr.
Referenced by HandleDecl(), and NextVA().
Member Data Documentation
[union]
union { ... } clang::StmtIteratorBase
DGE
Decl** clang::StmtIteratorBase::DGE protected
Definition at line 41 of file StmtIterator.h.
Referenced by NextDecl().
DGI
Decl** clang::StmtIteratorBase::DGI
Definition at line 38 of file StmtIterator.h.
Referenced by GetDeclExpr(), NextDecl(), and NextVA().
RawVAPtr
uintptr_t clang::StmtIteratorBase::RawVAPtr = 0 protected
Definition at line 40 of file StmtIterator.h.
Referenced by getVAPtr(), inDeclGroup(), inSizeOfTypeVA(), inStmt(), NextDecl(), NextVA(), setVAPtr(), and StmtIteratorBase().
stmt
Stmt** clang::StmtIteratorBase::stmt
Definition at line 37 of file StmtIterator.h.
Referenced by clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator*(), and clang::StmtIteratorImpl< DERIVED, REFERENCE >::operator++().
The documentation for this class was generated from the following files:
include/clang/AST/StmtIterator.h
lib/AST/StmtIterator.cpp