clang: clang::threadSafety::lexpr::LExpr Class Reference
clang::threadSafety::lexpr::LExpr Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyLogical.h"
Public Types
enum Opcode { Terminal , And , Or , Not }
Public Member Functions
Opcode kind () const
bool implies (const LExpr *RHS) const
Logical implication.
Protected Member Functions
LExpr (Opcode Kind)
Detailed Description
Definition at line 21 of file ThreadSafetyLogical.h.
Member Enumeration Documentation
Opcode
enum clang::threadSafety::lexpr::LExpr::Opcode
Enumerator
Terminal
And
Or
Not
Definition at line 23 of file ThreadSafetyLogical.h.
Constructor & Destructor Documentation
LExpr()
clang::threadSafety::lexpr::LExpr::LExpr (Opcode Kind) inline protected
Definition at line 36 of file ThreadSafetyLogical.h.
Member Function Documentation
implies()
bool clang::threadSafety::lexpr::LExpr::implies (const LExpr * RHS) const inline
Logical implication.
Returns true if the LExpr implies RHS, i.e. if the LExpr holds, then RHS must hold. For example, (A & B) implies A.
Definition at line 98 of file ThreadSafetyLogical.h.
References clang::threadSafety::lexpr::implies().
kind()
Opcode clang::threadSafety::lexpr::LExpr::kind () const inline
Definition at line 29 of file ThreadSafetyLogical.h.
Referenced by clang::threadSafety::lexpr::And::classof(), clang::threadSafety::lexpr::Not::classof(), clang::threadSafety::lexpr::Or::classof(), clang::threadSafety::lexpr::Terminal::classof(), and implies().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyLogical.h