clang: clang::comments::TextTokenRetokenizer Class Reference
clang::comments::TextTokenRetokenizer Class Reference
Re-lexes a sequence of tok::text tokens.
Public Member Functions
TextTokenRetokenizer (llvm::BumpPtrAllocator &Allocator, Parser &P)
bool lexWord (Token &Tok)
Extract a word – sequence of non-whitespace characters.
bool lexDelimitedSeq (Token &Tok, char OpenDelim, char CloseDelim)
void putBackLeftoverTokens ()
Put back tokens that we didn't consume.
Detailed Description
Re-lexes a sequence of tok::text tokens.
Definition at line 30 of file CommentParser.cpp.
Constructor & Destructor Documentation
TextTokenRetokenizer()
clang::comments::TextTokenRetokenizer::TextTokenRetokenizer (llvm::BumpPtrAllocator & Allocator, Parser & P) inline
Definition at line 146 of file CommentParser.cpp.
References P.
Member Function Documentation
lexDelimitedSeq()
bool clang::comments::TextTokenRetokenizer::lexDelimitedSeq (Token & Tok, char OpenDelim, char CloseDelim) inline
Definition at line 186 of file CommentParser.cpp.
References clang::C, memcpy(), Text, and Tok.
Referenced by clang::comments::Parser::parseParamCommandArgs().
lexWord()
bool clang::comments::TextTokenRetokenizer::lexWord (Token & Tok) inline
Extract a word – sequence of non-whitespace characters.
Definition at line 153 of file CommentParser.cpp.
References clang::C, clang::isWhitespace(), memcpy(), Text, and Tok.
Referenced by clang::comments::Parser::parseCommandArgs(), clang::comments::Parser::parseParamCommandArgs(), and clang::comments::Parser::parseTParamCommandArgs().
putBackLeftoverTokens()
void clang::comments::TextTokenRetokenizer::putBackLeftoverTokens () inline
Put back tokens that we didn't consume.
Definition at line 233 of file CommentParser.cpp.
References P.
Referenced by clang::comments::Parser::parseBlockCommand(), and clang::comments::Parser::parseInlineCommand().
The documentation for this class was generated from the following file:
lib/AST/CommentParser.cpp