clang: clang::Sema::GlobalMethodPool Class Reference
clang::Sema::GlobalMethodPool Class Reference
#include "clang/Sema/Sema.h"
Public Types
using Lists = std::pair<ObjCMethodList, ObjCMethodList>
using iterator = llvm::DenseMap<Selector, Lists>::iterator
Public Member Functions
iterator begin ()
iterator end ()
iterator find (Selector Sel)
std::pair< iterator, bool > insert (std::pair< Selector, Lists > &&Val)
int count (Selector Sel) const
bool empty () const
Detailed Description
Definition at line 1473 of file Sema.h.
Member Typedef Documentation
iterator
using clang::Sema::GlobalMethodPool::iterator = llvm::DenseMap<Selector, Lists>::iterator
Definition at line 1476 of file Sema.h.
Lists
using clang::Sema::GlobalMethodPool::Lists = std::pair<ObjCMethodList, ObjCMethodList>
Definition at line 1475 of file Sema.h.
Member Function Documentation
begin()
iterator clang::Sema::GlobalMethodPool::begin () inline
Definition at line 1477 of file Sema.h.
Referenced by AddClassMessageCompletions(), DiagnoseMismatchedSelectors(), and clang::Sema::SelectorsForTypoCorrection().
count()
int clang::Sema::GlobalMethodPool::count (Selector Sel) const inline
Definition at line 1483 of file Sema.h.
Referenced by AddClassMessageCompletions().
empty()
bool clang::Sema::GlobalMethodPool::empty () const inline
Definition at line 1484 of file Sema.h.
end()
iterator clang::Sema::GlobalMethodPool::end () inline
Definition at line 1478 of file Sema.h.
Referenced by AddClassMessageCompletions(), clang::Sema::AreMultipleMethodsInGlobalPool(), clang::Sema::CheckObjCMethodOverrides(), clang::Sema::CollectMultipleMethodsInGlobalPool(), DiagnoseMismatchedSelectors(), LookupDirectMethodInGlobalPool(), clang::Sema::LookupImplementedMethodInGlobalPool(), moveMethodToBackOfGlobalList(), and clang::Sema::SelectorsForTypoCorrection().
find()
iterator clang::Sema::GlobalMethodPool::find (Selector Sel) inline
Definition at line 1479 of file Sema.h.
Referenced by clang::Sema::AreMultipleMethodsInGlobalPool(), clang::Sema::CheckObjCMethodOverrides(), clang::Sema::CollectMultipleMethodsInGlobalPool(), LookupDirectMethodInGlobalPool(), clang::Sema::LookupImplementedMethodInGlobalPool(), and moveMethodToBackOfGlobalList().
insert()
std::pair< iterator, bool > clang::Sema::GlobalMethodPool::insert (std::pair< Selector, Lists > && Val) inline
Definition at line 1480 of file Sema.h.
Referenced by clang::ASTReader::ReadMethodPool().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h