clang: clang::TemplateParameterList Class Reference
clang::TemplateParameterList Class Reference final
Stores a list of template parameters for a TemplateDecl and its derived classes.
#include "clang/AST/DeclTemplate.h"
Public Types
using iterator = NamedDecl **
Iterates through the template parameters in this list.
using const_iterator = NamedDecl * const *
Iterates through the template parameters in this list.
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
unsigned size () const
ArrayRef< NamedDecl * > asArray ()
ArrayRef< const NamedDecl * > asArray () const
NamedDecl * getParam (unsigned Idx)
const NamedDecl * getParam (unsigned Idx) const
unsigned getMinRequiredArguments () const
Returns the minimum number of arguments needed to form a template specialization.
unsigned getDepth () const
Get the depth of this template parameter list in the set of template parameter lists.
bool containsUnexpandedParameterPack () const
Determine whether this template parameter list contains an unexpanded parameter pack.
bool hasParameterPack () const
Determine whether this template parameter list contains a parameter pack.
Expr * getRequiresClause ()
The constraint-expression of the associated requires-clause.
const Expr * getRequiresClause () const
The constraint-expression of the associated requires-clause.
void getAssociatedConstraints (llvm::SmallVectorImpl< const Expr * > &AC) const
All associated constraints derived from this template parameter list, including the requires clause and any constraints derived from constrained-parameters.
bool hasAssociatedConstraints () const
SourceLocation getTemplateLoc () const
SourceLocation getLAngleLoc () const
SourceLocation getRAngleLoc () const
SourceRange getSourceRange () const LLVM_READONLY
void print (raw_ostream &Out, const ASTContext &Context, bool OmitTemplateKW=false) const
void print (raw_ostream &Out, const ASTContext &Context, const PrintingPolicy &Policy, bool OmitTemplateKW=false) const
Static Public Member Functions
static TemplateParameterList * Create (const ASTContext &C, SourceLocation TemplateLoc, SourceLocation LAngleLoc, ArrayRef< NamedDecl * > Params, SourceLocation RAngleLoc, Expr *RequiresClause)
static bool shouldIncludeTypeForArgument (const PrintingPolicy &Policy, const TemplateParameterList *TPL, unsigned Idx)
Public Attributes
friend TrailingObjects
Protected Member Functions
TemplateParameterList (const ASTContext &C, SourceLocation TemplateLoc, SourceLocation LAngleLoc, ArrayRef< NamedDecl * > Params, SourceLocation RAngleLoc, Expr *RequiresClause)
size_t numTrailingObjects (OverloadToken< NamedDecl * >) const
size_t numTrailingObjects (OverloadToken< Expr * >) const
Friends
template<size_t N, bool HasRequiresClause>
class FixedSizeTemplateParameterListStorage
Detailed Description
Stores a list of template parameters for a TemplateDecl and its derived classes.
Definition at line 70 of file DeclTemplate.h.
Member Typedef Documentation
const_iterator
using clang::TemplateParameterList::const_iterator = NamedDecl * const *
Iterates through the template parameters in this list.
Definition at line 123 of file DeclTemplate.h.
iterator
using clang::TemplateParameterList::iterator = NamedDecl **
Iterates through the template parameters in this list.
Definition at line 120 of file DeclTemplate.h.
Constructor & Destructor Documentation
TemplateParameterList()
clang::TemplateParameterList::TemplateParameterList (const ASTContext & C, SourceLocation TemplateLoc, SourceLocation LAngleLoc, ArrayRef< NamedDecl * > Params, SourceLocation RAngleLoc, Expr * RequiresClause) protected
Member Function Documentation
asArray() [1/2]
ArrayRef< NamedDecl * > clang::TemplateParameterList::asArray () inline
Definition at line 132 of file DeclTemplate.h.
References begin(), and end().
Referenced by clang::ODRHash::AddTemplateParameterList(), argMatchesTemplateParams(), createTemplateSignatureString(), hasParameterPack(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
asArray() [2/2]
ArrayRef< const NamedDecl * > clang::TemplateParameterList::asArray () const inline
Definition at line 135 of file DeclTemplate.h.
References begin(), and size().
begin() [1/2]
iterator clang::TemplateParameterList::begin () inline
Definition at line 125 of file DeclTemplate.h.
Referenced by AddTemplateParameterChunks(), asArray(), asArray(), clang::Sema::CheckTemplateArgumentList(), clang::Sema::CheckTemplateParameterList(), end(), end(), clang::for(), getParam(), getParam(), substituteParameterMappings(), and clang::Sema::TemplateParameterListsAreEqual().
begin() [2/2]
const_iterator clang::TemplateParameterList::begin () const inline
Definition at line 126 of file DeclTemplate.h.
containsUnexpandedParameterPack()
bool clang::TemplateParameterList::containsUnexpandedParameterPack () const
Determine whether this template parameter list contains an unexpanded parameter pack.
Referenced by clang::concepts::ExprRequirement::ReturnTypeRequirement::containsUnexpandedParameterPack(), and clang::TemplateTemplateParmDecl::isPackExpansion().
Create()
static TemplateParameterList * clang::TemplateParameterList::Create (const ASTContext & C, SourceLocation TemplateLoc, SourceLocation LAngleLoc, ArrayRef< NamedDecl * > Params, SourceLocation RAngleLoc, Expr * RequiresClause) static
Referenced by clang::Sema::ActOnCompoundRequirement(), clang::Sema::ActOnTemplateParameterList(), createMakeIntegerSeqParameterList(), createTypePackElementParameterList(), clang::ASTNodeImporter::import(), clang::Sema::MatchTemplateParametersToScopeSpecifier(), clang::ASTRecordReader::readTemplateParameterList(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
end() [1/2]
iterator clang::TemplateParameterList::end () inline
Definition at line 127 of file DeclTemplate.h.
References begin().
Referenced by AddTemplateParameterChunks(), asArray(), clang::Sema::CheckTemplateArgumentList(), clang::Sema::CheckTemplateParameterList(), clang::for(), and clang::Sema::TemplateParameterListsAreEqual().
end() [2/2]
const_iterator clang::TemplateParameterList::end () const inline
Definition at line 128 of file DeclTemplate.h.
References begin().
getAssociatedConstraints()
void clang::TemplateParameterList::getAssociatedConstraints (llvm::SmallVectorImpl< const Expr * > & AC) const
All associated constraints derived from this template parameter list, including the requires clause and any constraints derived from constrained-parameters.
The constraints in the resulting list are to be treated as if in a conjunction ("and").
Referenced by clang::Sema::CheckTemplateTemplateArgument(), clang::ClassTemplatePartialSpecializationDecl::getAssociatedConstraints(), clang::TemplateDecl::getAssociatedConstraints(), and clang::VarTemplatePartialSpecializationDecl::getAssociatedConstraints().
getDepth()
unsigned clang::TemplateParameterList::getDepth () const
Get the depth of this template parameter list in the set of template parameter lists.
The first template parameter list in a declaration will have depth 0, the second template parameter list will have depth 1, etc.
Referenced by clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::BuildExprRequirement(), checkTemplatePartialSpecialization(), hasDeducibleTemplateParameters(), isAtLeastAsSpecializedAs(), isSameAsPrimaryTemplate(), clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs(), clang::Sema::MarkDeducedTemplateParameters(), and printTo().
getLAngleLoc()
SourceLocation clang::TemplateParameterList::getLAngleLoc () const inline
Definition at line 195 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), clang::Sema::ActOnTemplateTemplateParameter(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::ASTNodeImporter::import(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getMinRequiredArguments()
unsigned clang::TemplateParameterList::getMinRequiredArguments () const
Returns the minimum number of arguments needed to form a template specialization.
This may be fewer than the number of template parameters, if some of the parameters have default arguments or if there is a parameter pack.
Referenced by clang::Sema::BuildTypeConstraint(), clang::Sema::isStdInitializerList(), and LookupStdInitializerList().
getParam() [1/2]
NamedDecl * clang::TemplateParameterList::getParam (unsigned Idx) inline
Definition at line 139 of file DeclTemplate.h.
References begin(), and size().
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::comments::Sema::actOnTParamCommandParamNameArg(), argMatchesTemplateParams(), clang::Sema::BuildExprRequirement(), checkCUDADeviceBuiltinSurfaceClassTemplate(), checkCUDADeviceBuiltinTextureClassTemplate(), clang::Sema::CheckDeductionGuideTemplate(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckTemplatePartialSpecializationArgs(), checkTupleLikeDecomposition(), clang::PredefinedExpr::ComputeName(), ConvertDeducedTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DiagnoseUnexpandedParameterPacks(), FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), clang::CodeCompleteConsumer::OverloadCandidate::getParamDecl(), clang::comments::TParamCommandComment::getParamName(), clang::CodeCompleteConsumer::OverloadCandidate::getParamType(), clang::Sema::getTemplateArgumentBindingsText(), handleSYCLKernelAttr(), clang::FunctionTemplateDecl::isAbbreviated(), isSameAsPrimaryTemplate(), clang::ASTContext::isSameTemplateParameterList(), clang::Sema::isStdInitializerList(), IsStructurallyEquivalent(), clang::Sema::LookupLiteralOperator(), LookupStdInitializerList(), noteNonDeducibleParameters(), printTo(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement(), clang::Sema::SubstituteExplicitTemplateArguments(), and clang::ASTNodeImporter::VisitFunctionTemplateDecl().
getParam() [2/2]
const NamedDecl * clang::TemplateParameterList::getParam (unsigned Idx) const inline
Definition at line 143 of file DeclTemplate.h.
References begin(), and size().
getRAngleLoc()
SourceLocation clang::TemplateParameterList::getRAngleLoc () const inline
Definition at line 196 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), clang::Sema::ActOnTemplateTemplateParameter(), clang::Sema::ActOnVariableDeclarator(), clang::ASTRecordWriter::AddTemplateParameterList(), DiagnoseTemplateParameterListArityMismatch(), clang::ASTNodeImporter::import(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getRequiresClause() [1/2]
Expr * clang::TemplateParameterList::getRequiresClause () inline
The constraint-expression of the associated requires-clause.
Definition at line 175 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::ASTNodeImporter::import(), clang::ASTContext::isSameTemplateParameterList(), ProfileTemplateParameterList(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::Sema::TemplateParameterListsAreEqual(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getRequiresClause() [2/2]
const Expr * clang::TemplateParameterList::getRequiresClause () const inline
The constraint-expression of the associated requires-clause.
Definition at line 180 of file DeclTemplate.h.
getSourceRange()
SourceRange clang::TemplateParameterList::getSourceRange () const inline
Definition at line 198 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckTemplateArgumentList(), clang::Sema::CheckTemplateDeclScope(), and diagnoseMissingArgument().
getTemplateLoc()
SourceLocation clang::TemplateParameterList::getTemplateLoc () const inline
Definition at line 194 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::Sema::CheckTemplateDeclScope(), DiagnoseTemplateParameterListArityMismatch(), clang::ASTNodeImporter::import(), IsStructurallyEquivalent(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::Sema::TemplateParameterListsAreEqual(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
hasAssociatedConstraints()
bool clang::TemplateParameterList::hasAssociatedConstraints () const
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnVarTemplateSpecialization(), clang::ClassTemplatePartialSpecializationDecl::hasAssociatedConstraints(), clang::TemplateDecl::hasAssociatedConstraints(), and clang::VarTemplatePartialSpecializationDecl::hasAssociatedConstraints().
hasParameterPack()
bool clang::TemplateParameterList::hasParameterPack () const inline
Determine whether this template parameter list contains a parameter pack.
Definition at line 167 of file DeclTemplate.h.
References asArray(), and P.
Referenced by argMatchesTemplateParams().
numTrailingObjects() [1/2]
size_t clang::TemplateParameterList::numTrailingObjects (OverloadToken< Expr * >) const inline protected
Definition at line 103 of file DeclTemplate.h.
numTrailingObjects() [2/2]
size_t clang::TemplateParameterList::numTrailingObjects (OverloadToken< NamedDecl * >) const inline protected
Definition at line 99 of file DeclTemplate.h.
print() [1/2]
void clang::TemplateParameterList::print (raw_ostream & Out, const ASTContext & Context, bool OmitTemplateKW = false) const
print() [2/2]
void clang::TemplateParameterList::print (raw_ostream & Out, const ASTContext & Context, const PrintingPolicy & Policy, bool OmitTemplateKW = false) const
shouldIncludeTypeForArgument()
static bool clang::TemplateParameterList::shouldIncludeTypeForArgument (const PrintingPolicy & Policy, const TemplateParameterList * TPL, unsigned Idx) static
Referenced by clang::PredefinedExpr::ComputeName(), and clang::Sema::getTemplateArgumentBindingsText().
size()
unsigned clang::TemplateParameterList::size () const inline
Definition at line 130 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::ActOnTemplateTemplateParameter(), clang::comments::Sema::actOnTParamCommandParamNameArg(), clang::Sema::ActOnVariableDeclarator(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::ODRHash::AddTemplateParameterList(), argMatchesTemplateParams(), asArray(), clang::Sema::CheckClassTemplate(), checkCUDADeviceBuiltinSurfaceClassTemplate(), checkCUDADeviceBuiltinTextureClassTemplate(), clang::Sema::CheckDeductionGuideTemplate(), checkLiteralOperatorTemplateParameterList(), checkTemplatePartialSpecialization(), clang::Sema::CheckTemplatePartialSpecializationArgs(), checkTupleLikeDecomposition(), clang::PredefinedExpr::ComputeName(), ConvertDeducedTemplateArguments(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), DependsOnTemplateParameters(), DiagnoseTemplateParameterListArityMismatch(), DiagnoseUnexpandedParameterPacks(), clang::Sema::FindInstantiatedDecl(), FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), clang::ASTContext::getInjectedTemplateArgs(), clang::FunctionTemplateDecl::getInjectedTemplateArgs(), getParam(), getParam(), clang::Sema::getTemplateArgumentBindingsText(), handleSYCLKernelAttr(), hasDeducibleTemplateParameters(), clang::ASTNodeImporter::import(), clang::FunctionTemplateDecl::isAbbreviated(), isAtLeastAsSpecializedAs(), isSameAsPrimaryTemplate(), clang::ASTContext::isSameTemplateParameterList(), IsStructurallyEquivalent(), clang::Sema::LookupLiteralOperator(), clang::Sema::MarkDeducedTemplateParameters(), printTo(), ProfileTemplateParameterList(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), ResolveOverloadForDeduction(), clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement(), clang::Sema::SubstituteExplicitTemplateArguments(), substituteParameterMappings(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::Sema::TemplateParameterListsAreEqual(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ASTNodeImporter::VisitFunctionTemplateDecl().
Friends And Related Symbol Documentation
FixedSizeTemplateParameterListStorage
template<size_t N, bool HasRequiresClause> friend class FixedSizeTemplateParameterListStorage friend
Definition at line 109 of file DeclTemplate.h.
Member Data Documentation
TrailingObjects
friend clang::TemplateParameterList::TrailingObjects
Definition at line 110 of file DeclTemplate.h.
The documentation for this class was generated from the following file:
include/clang/AST/DeclTemplate.h