clang: clang::consumed::ConsumedStmtVisitor Class Reference
clang::consumed::ConsumedStmtVisitor Class Reference
Public Member Functions
void checkCallability (const PropagationInfo &PInfo, const FunctionDecl *FunDecl, SourceLocation BlameLoc)
bool handleCall (const CallExpr *Call, const Expr *ObjArg, const FunctionDecl *FunD)
void VisitBinaryOperator (const BinaryOperator *BinOp)
void VisitCallExpr (const CallExpr *Call)
void VisitCastExpr (const CastExpr *Cast)
void VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *Temp)
void VisitCXXConstructExpr (const CXXConstructExpr *Call)
void VisitCXXMemberCallExpr (const CXXMemberCallExpr *Call)
void VisitCXXOperatorCallExpr (const CXXOperatorCallExpr *Call)
void VisitDeclRefExpr (const DeclRefExpr *DeclRef)
void VisitDeclStmt (const DeclStmt *DelcS)
void VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *Temp)
void VisitMemberExpr (const MemberExpr *MExpr)
void VisitParmVarDecl (const ParmVarDecl *Param)
void VisitReturnStmt (const ReturnStmt *Ret)
void VisitUnaryOperator (const UnaryOperator *UOp)
void VisitVarDecl (const VarDecl *Var)
ConsumedStmtVisitor (ConsumedAnalyzer &Analyzer, ConsumedStateMap *StateMap)
PropagationInfo getInfo (const Expr *StmtNode) const
void reset (ConsumedStateMap *NewStateMap)
Public Member Functions inherited from clang::StmtVisitorBase< llvm::make_const_ptr, ConsumedStmtVisitor, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< llvm::make_const_ptr, ConsumedStmtVisitor, void, ParamTys... >
ParamTys P
Detailed Description
Definition at line 459 of file Consumed.cpp.
Constructor & Destructor Documentation
ConsumedStmtVisitor()
clang::consumed::ConsumedStmtVisitor::ConsumedStmtVisitor (ConsumedAnalyzer & Analyzer, ConsumedStateMap * StateMap) inline
Definition at line 516 of file Consumed.cpp.
Member Function Documentation
checkCallability()
void ConsumedStmtVisitor::checkCallability (const PropagationInfo & PInfo, const FunctionDecl * FunDecl, SourceLocation BlameLoc)
Definition at line 579 of file Consumed.cpp.
References clang::consumed::CS_None, clang::consumed::PropagationInfo::getAsState(), clang::Decl::getAttr(), clang::NamedDecl::getNameAsString(), clang::consumed::ConsumedStateMap::getState(), clang::consumed::PropagationInfo::getVar(), isCallableInState(), clang::consumed::PropagationInfo::isTest(), clang::consumed::PropagationInfo::isVar(), stateToString(), clang::consumed::ConsumedAnalyzer::WarningsHandler, clang::consumed::ConsumedWarningsHandlerBase::warnUseInInvalidState(), and clang::consumed::ConsumedWarningsHandlerBase::warnUseOfTempInInvalidState().
Referenced by handleCall(), and clang::consumed::ConsumedAnalyzer::run().
getInfo()
PropagationInfo clang::consumed::ConsumedStmtVisitor::getInfo (const Expr * StmtNode) const inline
Definition at line 519 of file Consumed.cpp.
handleCall()
bool ConsumedStmtVisitor::handleCall (const CallExpr * Call, const Expr * ObjArg, const FunctionDecl * FunD)
Definition at line 611 of file Consumed.cpp.
References checkCallability(), clang::consumed::CS_Consumed, clang::consumed::CS_Unknown, clang::consumed::PropagationInfo::getAsState(), clang::Decl::getAttr(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::Type::getPointeeType(), clang::consumed::PropagationInfo::getTmp(), clang::consumed::PropagationInfo::getVar(), clang::QualType::isConstQualified(), isConsumableType(), isPointerOrRef(), isRValueRef(), isSetOnReadPtrType(), isTestingFunction(), clang::consumed::PropagationInfo::isTmp(), clang::consumed::PropagationInfo::isVar(), mapParamTypestateAttrState(), mapReturnTypestateAttrState(), mapSetTypestateAttrState(), Offset, clang::consumed::ConsumedStateMap::setState(), setStateForVarOrTmp(), stateToString(), testsFor(), clang::consumed::ConsumedAnalyzer::WarningsHandler, and clang::consumed::ConsumedWarningsHandlerBase::warnParamTypestateMismatch().
Referenced by VisitCallExpr(), VisitCXXMemberCallExpr(), and VisitCXXOperatorCallExpr().
reset()
void clang::consumed::ConsumedStmtVisitor::reset (ConsumedStateMap * NewStateMap) inline
Definition at line 528 of file Consumed.cpp.
Referenced by clang::consumed::ConsumedAnalyzer::run().
VisitBinaryOperator()
void ConsumedStmtVisitor::VisitBinaryOperator (const BinaryOperator * BinOp)
Definition at line 701 of file Consumed.cpp.
References clang::consumed::CS_None, clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), and clang::BinaryOperator::getRHS().
VisitCallExpr()
void ConsumedStmtVisitor::VisitCallExpr (const CallExpr * Call)
Definition at line 740 of file Consumed.cpp.
References clang::consumed::CS_Consumed, and handleCall().
VisitCastExpr()
void ConsumedStmtVisitor::VisitCastExpr (const CastExpr * Cast)
Definition at line 756 of file Consumed.cpp.
VisitCXXBindTemporaryExpr()
void ConsumedStmtVisitor::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * Temp)
Definition at line 760 of file Consumed.cpp.
References clang::CXXBindTemporaryExpr::getSubExpr(), and clang::consumed::ConsumedStateMap::setState().
VisitCXXConstructExpr()
void ConsumedStmtVisitor::VisitCXXConstructExpr (const CXXConstructExpr * Call)
Definition at line 771 of file Consumed.cpp.
References clang::consumed::CS_Consumed, clang::consumed::CS_None, clang::consumed::CS_Unknown, isConsumableType(), isSetOnReadPtrType(), mapConsumableAttrState(), and mapReturnTypestateAttrState().
VisitCXXMemberCallExpr()
void ConsumedStmtVisitor::VisitCXXMemberCallExpr (const CXXMemberCallExpr * Call)
Definition at line 802 of file Consumed.cpp.
References handleCall().
VisitCXXOperatorCallExpr()
void ConsumedStmtVisitor::VisitCXXOperatorCallExpr (const CXXOperatorCallExpr * Call)
Definition at line 812 of file Consumed.cpp.
References handleCall().
VisitDeclRefExpr()
void ConsumedStmtVisitor::VisitDeclRefExpr (const DeclRefExpr * DeclRef)
Definition at line 832 of file Consumed.cpp.
References clang::consumed::CS_None, clang::DeclRefExpr::getDecl(), and clang::consumed::ConsumedStateMap::getState().
VisitDeclStmt()
void ConsumedStmtVisitor::VisitDeclStmt (const DeclStmt * DelcS)
Definition at line 838 of file Consumed.cpp.
References clang::DeclStmt::decls(), clang::DeclStmt::getSingleDecl(), clang::DeclStmt::isSingleDecl(), and VisitVarDecl().
VisitMaterializeTemporaryExpr()
void ConsumedStmtVisitor::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * Temp)
Definition at line 848 of file Consumed.cpp.
References clang::MaterializeTemporaryExpr::getSubExpr().
VisitMemberExpr()
void ConsumedStmtVisitor::VisitMemberExpr (const MemberExpr * MExpr)
Definition at line 853 of file Consumed.cpp.
References clang::MemberExpr::getBase().
VisitParmVarDecl()
void ConsumedStmtVisitor::VisitParmVarDecl (const ParmVarDecl * Param)
Definition at line 857 of file Consumed.cpp.
References clang::consumed::CS_None, clang::consumed::CS_Unknown, clang::Type::getPointeeType(), isConsumableType(), clang::Type::isReferenceType(), isRValueRef(), mapConsumableAttrState(), mapParamTypestateAttrState(), and clang::consumed::ConsumedStateMap::setState().
Referenced by clang::consumed::ConsumedAnalyzer::run().
VisitReturnStmt()
void ConsumedStmtVisitor::VisitReturnStmt (const ReturnStmt * Ret)
Definition at line 876 of file Consumed.cpp.
References clang::consumed::ConsumedStateMap::checkParamsForReturnTypestate(), clang::consumed::CS_None, clang::consumed::ConsumedAnalyzer::getExpectedReturnState(), Ret(), stateToString(), clang::consumed::ConsumedAnalyzer::WarningsHandler, and clang::consumed::ConsumedWarningsHandlerBase::warnReturnTypestateMismatch().
VisitUnaryOperator()
void ConsumedStmtVisitor::VisitUnaryOperator (const UnaryOperator * UOp)
Definition at line 896 of file Consumed.cpp.
References clang::UnaryOperator::getOpcode(), and clang::UnaryOperator::getSubExpr().
VisitVarDecl()
void ConsumedStmtVisitor::VisitVarDecl (const VarDecl * Var)
Definition at line 916 of file Consumed.cpp.
References clang::consumed::CS_None, clang::consumed::CS_Unknown, clang::consumed::PropagationInfo::getAsState(), clang::VarDecl::getInit(), clang::ValueDecl::getType(), clang::VarDecl::hasInit(), clang::Expr::IgnoreImplicit(), isConsumableType(), and clang::consumed::ConsumedStateMap::setState().
Referenced by VisitDeclStmt().
The documentation for this class was generated from the following file:
lib/Analysis/Consumed.cpp