clang: clang::threadSafety::til::Let Class Reference
clang::threadSafety::til::Let Class Reference
A let-expression, e.g.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Let (Variable *Vd, SExpr *Bd)
Let (const Let &L, Variable *Vd, SExpr *Bd)
Variable * variableDecl ()
const Variable * variableDecl () const
SExpr * body ()
const SExpr * body () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Let *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
A let-expression, e.g.
let x=t; u. This is a pseduo-term; it will be lowered to instructions in a CFG.
Definition at line 1857 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Let() [1/2]
clang::threadSafety::til::Let::Let (Variable * Vd, SExpr * Bd) inline
Definition at line 1859 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::Variable::setKind(), and clang::threadSafety::til::Variable::VK_Let.
Let() [2/2]
clang::threadSafety::til::Let::Let (const Let & L, Variable * Vd, SExpr * Bd) inline
Definition at line 1863 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::Variable::setKind(), and clang::threadSafety::til::Variable::VK_Let.
Member Function Documentation
body() [1/2]
SExpr * clang::threadSafety::til::Let::body () inline
Definition at line 1872 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet().
body() [2/2]
const SExpr * clang::threadSafety::til::Let::body () const inline
Definition at line 1873 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Let::classof (const SExpr * E) inline static
Definition at line 1867 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Let::compare (const Let * E, C & Cmp) const inline
Definition at line 1887 of file ThreadSafetyTIL.h.
References body(), clang::threadSafety::til::Variable::definition(), and variableDecl().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Let::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1876 of file ThreadSafetyTIL.h.
References clang::VarDecl::Definition, and clang::threadSafety::til::Variable::traverse().
variableDecl() [1/2]
Variable * clang::threadSafety::til::Let::variableDecl () inline
Definition at line 1869 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet().
variableDecl() [2/2]
const Variable * clang::threadSafety::til::Let::variableDecl () const inline
Definition at line 1870 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h