clang: clang::Sema::FullExprArg Class Reference
clang::Sema::FullExprArg Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
FullExprArg ()
FullExprArg (Sema &actions)
ExprResult release ()
Expr * get () const
Expr * operator-> ()
Friends
class Sema
Detailed Description
Definition at line 4853 of file Sema.h.
Constructor & Destructor Documentation
FullExprArg() [1/2]
clang::Sema::FullExprArg::FullExprArg () inline
Definition at line 4855 of file Sema.h.
FullExprArg() [2/2]
clang::Sema::FullExprArg::FullExprArg (Sema & actions) inline
Definition at line 4856 of file Sema.h.
Member Function Documentation
get()
Expr * clang::Sema::FullExprArg::get () const inline
Definition at line 4862 of file Sema.h.
Referenced by clang::Sema::ActOnForStmt(), clang::Sema::ActOnOpenMPDeviceClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPFilterClause(), clang::Sema::ActOnOpenMPFinalClause(), clang::Sema::ActOnOpenMPIfClause(), clang::Sema::ActOnOpenMPNocontextClause(), clang::Sema::ActOnOpenMPNovariantsClause(), clang::Sema::ActOnOpenMPNumTeamsClause(), clang::Sema::ActOnOpenMPNumThreadsClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPThreadLimitClause(), clang::Sema::BuildCoreturnStmt(), and isNonNegativeIntegerValue().
operator->()
Expr * clang::Sema::FullExprArg::operator-> () inline
Definition at line 4864 of file Sema.h.
release()
ExprResult clang::Sema::FullExprArg::release () inline
Definition at line 4858 of file Sema.h.
Referenced by clang::Sema::ActOnForStmt().
Friends And Related Symbol Documentation
Sema
friend class Sema friend
Definition at line 4871 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h