clang: clang::ento::retaincountchecker::RefCountReportVisitor Class Reference
clang::ento::retaincountchecker::RefCountReportVisitor Class Reference
Public Member Functions
RefCountReportVisitor (SymbolRef sym)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR) override
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
Protected Attributes
SymbolRef Sym
Additional Inherited Members
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
Definition at line 312 of file RetainCountDiagnostics.cpp.
Constructor & Destructor Documentation
RefCountReportVisitor()
clang::ento::retaincountchecker::RefCountReportVisitor::RefCountReportVisitor (SymbolRef sym) inline
Definition at line 317 of file RetainCountDiagnostics.cpp.
Member Function Documentation
getEndPath()
PathDiagnosticPieceRef RefCountReportVisitor::getEndPath (BugReporterContext & BRC, const ExplodedNode * N, PathSensitiveBugReport & BR) override virtual
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
NOTE that this function can be implemented on at most one used visitor, and otherwise it crahes at runtime.
Reimplemented from clang::ento::BugReporterVisitor.
Reimplemented in clang::ento::retaincountchecker::RefLeakReportVisitor.
Definition at line 751 of file RetainCountDiagnostics.cpp.
References clang::ento::BugReporterVisitor::getDefaultEndPath(), and clang::ento::PathSensitiveBugReport::markInteresting().
Profile()
void clang::ento::retaincountchecker::RefCountReportVisitor::Profile (llvm::FoldingSetNodeID & ID) const inline override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 319 of file RetainCountDiagnostics.cpp.
References Sym.
VisitNode()
PathDiagnosticPieceRef RefCountReportVisitor::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 453 of file RetainCountDiagnostics.cpp.
References annotateConsumedSummaryMismatch(), annotateStartParameter(), clang::ento::PathDiagnosticLocation::create(), clang::ento::retaincountchecker::RefCountBug::DeallocNotOwned, clang::ento::retaincountchecker::RefCountBug::FreeNotOwned, generateDiagnosticsForCallLike(), clang::ento::BugReport::getBugType(), clang::ento::retaincountchecker::RefCountBug::getBugType(), clang::ento::ProgramStateManager::getCallEventManager(), clang::StackFrameContext::getCallSite(), clang::ento::retaincountchecker::RetainCountChecker::getCastFailTag(), clang::ento::retaincountchecker::RetainCountChecker::getDeallocSentTag(), clang::ento::ExplodedNode::getFirstPred(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::BugReporterContext::getSourceManager(), clang::LocationContext::getStackFrame(), clang::ento::ExplodedNode::getState(), clang::ento::BugReporterContext::getStateManager(), clang::ento::retaincountchecker::RefVal::isNotOwned(), isNumericLiteralExpression(), clang::ento::retaincountchecker::RefVal::isOwned(), clang::ento::retaincountchecker::isSynthesizedAccessor(), N, P, shouldGenerateNote(), and SM.
Member Data Documentation
Sym
SymbolRef clang::ento::retaincountchecker::RefCountReportVisitor::Sym protected
Definition at line 314 of file RetainCountDiagnostics.cpp.
Referenced by Profile().
The documentation for this class was generated from the following file:
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountDiagnostics.cpp