clang: clang::ento::AnalysisManager Class Reference
clang::ento::AnalysisManager Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
Public Member Functions
AnalysisManager (ASTContext &ctx, Preprocessor &PP, const PathDiagnosticConsumers &Consumers, StoreManagerCreator storemgr, ConstraintManagerCreator constraintmgr, CheckerManager *checkerMgr, AnalyzerOptions &Options, CodeInjector *injector=nullptr)
~AnalysisManager () override
void ClearContexts ()
AnalysisDeclContextManager & getAnalysisDeclContextManager ()
Preprocessor & getPreprocessor () override
StoreManagerCreator getStoreManagerCreator ()
AnalyzerOptions & getAnalyzerOptions () override
ConstraintManagerCreator getConstraintManagerCreator ()
CheckerManager * getCheckerManager () const
ASTContext & getASTContext () override
SourceManager & getSourceManager () override
const LangOptions & getLangOpts () const
ArrayRef< PathDiagnosticConsumer * > getPathDiagnosticConsumers () override
void FlushDiagnostics ()
bool shouldVisualize () const
bool shouldInlineCall () const
CFG * getCFG (Decl const *D)
template<typename T >
T * getAnalysis (Decl const *D)
ParentMap & getParentMap (Decl const *D)
AnalysisDeclContext * getAnalysisDeclContext (const Decl *D)
bool isInCodeFile (SourceLocation SL)
Public Member Functions inherited from clang::ento::BugReporterData
virtual ~BugReporterData ()=default
Static Public Member Functions
static bool isInCodeFile (SourceLocation SL, const SourceManager &SM)
Public Attributes
AnalyzerOptions & options
Detailed Description
Definition at line 31 of file AnalysisManager.h.
Constructor & Destructor Documentation
AnalysisManager()
AnalysisManager::AnalysisManager (ASTContext & ctx, Preprocessor & PP, const PathDiagnosticConsumers & Consumers, StoreManagerCreator storemgr, ConstraintManagerCreator constraintmgr, CheckerManager * checkerMgr, AnalyzerOptions & Options, CodeInjector * injector = nullptr)
Definition at line 16 of file AnalysisManager.cpp.
References clang::AnalysisDeclContextManager::getCFGBuildOptions().
~AnalysisManager()
AnalysisManager::~AnalysisManager () override
Definition at line 51 of file AnalysisManager.cpp.
References FlushDiagnostics().
Member Function Documentation
ClearContexts()
void clang::ento::AnalysisManager::ClearContexts () inline
Definition at line 58 of file AnalysisManager.h.
References clang::AnalysisDeclContextManager::clear().
FlushDiagnostics()
void AnalysisManager::FlushDiagnostics ()
Definition at line 59 of file AnalysisManager.cpp.
Referenced by ~AnalysisManager().
getAnalysis()
template<typename T > T * clang::ento::AnalysisManager::getAnalysis (Decl const * D) inline
Definition at line 113 of file AnalysisManager.h.
References clang::AnalysisDeclContext::getAnalysis(), and clang::AnalysisDeclContextManager::getContext().
getAnalysisDeclContext()
AnalysisDeclContext * clang::ento::AnalysisManager::getAnalysisDeclContext (const Decl * D) inline
Definition at line 121 of file AnalysisManager.h.
References clang::AnalysisDeclContextManager::getContext().
Referenced by emitDiagnostics(), emitDiagnostics(), makeLocation(), and REGISTER_MAP_WITH_PROGRAMSTATE().
getAnalysisDeclContextManager()
AnalysisDeclContextManager & clang::ento::AnalysisManager::getAnalysisDeclContextManager () inline
Definition at line 62 of file AnalysisManager.h.
Referenced by clang::ento::ExprEngine::getAnalysisDeclContextManager().
getAnalyzerOptions()
AnalyzerOptions & clang::ento::AnalysisManager::getAnalyzerOptions () inline override virtual
Implements clang::ento::BugReporterData.
Definition at line 72 of file AnalysisManager.h.
References options.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::updateObjectsUnderConstruction(), clang::ento::ExprEngine::VisitCXXDeleteExpr(), and clang::ento::ExprEngine::VisitCXXNewExpr().
getASTContext()
ASTContext & clang::ento::AnalysisManager::getASTContext () inline override virtual
Implements clang::ento::BugReporterData.
Definition at line 82 of file AnalysisManager.h.
Referenced by checkTempObjectsInNoPool(), checkTempObjectsInSamePool(), clang::ento::ExprEngine::getContext(), getSourceManager(), isInCodeFile(), makeLocation(), and clang::ento::ExprEngine::processCFGBlockEntrance().
getCFG()
CFG * clang::ento::AnalysisManager::getCFG (Decl const * D) inline
Definition at line 108 of file AnalysisManager.h.
References clang::AnalysisDeclContext::getCFG(), and clang::AnalysisDeclContextManager::getContext().
getCheckerManager()
CheckerManager * clang::ento::AnalysisManager::getCheckerManager () const inline
Definition at line 80 of file AnalysisManager.h.
Referenced by clang::ento::ExprEngine::getCheckerManager().
getConstraintManagerCreator()
ConstraintManagerCreator clang::ento::AnalysisManager::getConstraintManagerCreator () inline
Definition at line 76 of file AnalysisManager.h.
getLangOpts()
const LangOptions & clang::ento::AnalysisManager::getLangOpts () const inline
Definition at line 90 of file AnalysisManager.h.
Referenced by clang::ento::ExprEngine::VisitArraySubscriptExpr().
getParentMap()
ParentMap & clang::ento::AnalysisManager::getParentMap (Decl const * D) inline
Definition at line 117 of file AnalysisManager.h.
References clang::AnalysisDeclContextManager::getContext(), and clang::AnalysisDeclContext::getParentMap().
getPathDiagnosticConsumers()
ArrayRef< PathDiagnosticConsumer * > clang::ento::AnalysisManager::getPathDiagnosticConsumers () inline override virtual
Implements clang::ento::BugReporterData.
Definition at line 94 of file AnalysisManager.h.
getPreprocessor()
Preprocessor & clang::ento::AnalysisManager::getPreprocessor () inline override virtual
Implements clang::ento::BugReporterData.
Definition at line 66 of file AnalysisManager.h.
getSourceManager()
SourceManager & clang::ento::AnalysisManager::getSourceManager () inline override virtual
Implements clang::ento::BugReporterData.
Definition at line 86 of file AnalysisManager.h.
References getASTContext(), and clang::ASTContext::getSourceManager().
getStoreManagerCreator()
StoreManagerCreator clang::ento::AnalysisManager::getStoreManagerCreator () inline
Definition at line 68 of file AnalysisManager.h.
isInCodeFile() [1/2]
bool clang::ento::AnalysisManager::isInCodeFile (SourceLocation SL) inline
Definition at line 150 of file AnalysisManager.h.
References getASTContext(), clang::ASTContext::getSourceManager(), isInCodeFile(), and SM.
isInCodeFile() [2/2]
static bool clang::ento::AnalysisManager::isInCodeFile (SourceLocation SL, const SourceManager & SM) inline static
Definition at line 125 of file AnalysisManager.h.
References clang::SourceLocation::isValid(), and SM.
Referenced by clang::ento::ObjCMethodCall::canBeOverridenInSubclass(), getFirstStackedCallToHeaderFile(), and isInCodeFile().
shouldInlineCall()
bool clang::ento::AnalysisManager::shouldInlineCall () const inline
Definition at line 104 of file AnalysisManager.h.
References clang::AnalyzerOptions::getIPAMode(), clang::IPAK_None, and options.
shouldVisualize()
bool clang::ento::AnalysisManager::shouldVisualize () const inline
Definition at line 100 of file AnalysisManager.h.
References options, and clang::AnalyzerOptions::visualizeExplodedGraphWithGraphViz.
Member Data Documentation
options
AnalyzerOptions& clang::ento::AnalysisManager::options
Definition at line 47 of file AnalysisManager.h.
Referenced by clang::ento::ExprEngine::defaultEvalCall(), clang::ento::CoreEngine::ExecuteWorkList(), getAnalyzerOptions(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessLoopExit(), clang::ento::ExprEngine::ProcessNewAllocator(), REGISTER_MAP_WITH_PROGRAMSTATE(), shouldInlineCall(), shouldRemoveDeadBindings(), shouldVisualize(), clang::ento::ExprEngine::Visit(), clang::ento::ExprEngine::VisitCast(), and clang::ento::ExprEngine::VisitCommonDeclRefExpr().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h
lib/StaticAnalyzer/Core/AnalysisManager.cpp