clang: clang::FrontendAction Class Reference
clang::FrontendAction Class Reference abstract
Abstract base class for actions which can be performed by the frontend.
#include "clang/Frontend/FrontendAction.h"
Public Member Functions
FrontendAction ()
virtual ~FrontendAction ()
Compiler Instance Access
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
Current File Information
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
Supported Modes
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual bool usesPreprocessorOnly () const =0
Does this action only use the preprocessor?
virtual TranslationUnitKind getTranslationUnitKind ()
For AST-based actions, the kind of translation unit we're handling.
virtual bool hasPCHSupport () const
Does this action support use with PCH?
virtual bool hasASTFileSupport () const
Does this action support use with AST files?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
Public Action Interface
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Protected Member Functions
Implementation Action Interface
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile)=0
Create the AST consumer object for this action, if supported.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool BeginSourceFileAction (CompilerInstance &CI)
Callback at the start of processing a single input.
virtual void ExecuteAction ()=0
Callback to run the program action, using the initialized compiler instance.
virtual void EndSourceFileAction ()
Callback at the end of processing a single input.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Friends
class ASTMergeAction
class WrapperFrontendAction
Detailed Description
Abstract base class for actions which can be performed by the frontend.
Definition at line 36 of file FrontendAction.h.
Constructor & Destructor Documentation
FrontendAction()
FrontendAction::FrontendAction ()
Definition at line 135 of file FrontendAction.cpp.
~FrontendAction()
FrontendAction::~FrontendAction () virtual
Definition at line 137 of file FrontendAction.cpp.
Member Function Documentation
BeginInvocation()
virtual bool clang::FrontendAction::BeginInvocation (CompilerInstance & CI) inline protected virtual
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
Returns
True on success; on failure BeginSourceFileAction(), ExecuteAction() and EndSourceFileAction() will not be called.
Reimplemented in clang::arcmt::CheckAction, clang::arcmt::MigrateAction, clang::arcmt::MigrateSourceAction, clang::arcmt::ModifyAction, clang::arcmt::ObjCMigrateAction, clang::DumpModuleInfoAction, clang::FixItRecompile, and clang::WrapperFrontendAction.
Definition at line 79 of file FrontendAction.h.
Referenced by BeginSourceFile().
BeginSourceFile()
bool FrontendAction::BeginSourceFile (CompilerInstance & CI, const FrontendInputFile & Input)
Prepare the action for processing the input file Input.
This is run after the options and frontend have been initialized, but prior to executing any per-file processing.
Parameters
CI - The compiler instance this action is being run from. The action may store and use this object up until the matching EndSourceFile action.
Input - The input filename and kind. Some input kinds are handled specially, for example AST inputs, since the AST file itself contains several objects which would normally be owned by the CompilerInstance. When processing AST input files, these objects should generally not be initialized in the CompilerInstance – they will automatically be shared with the AST file in between BeginSourceFile() and EndSourceFile().
Returns
True on success; on failure the compilation of this file should be aborted and neither Execute() nor EndSourceFile() should be called.
Definition at line 567 of file FrontendAction.cpp.
References clang::PreprocessorOptions::AllowPCHWithCompilerErrors, BeginInvocation(), clang::DiagnosticConsumer::BeginSourceFile(), BeginSourceFileAction(), clang::SrcMgr::C_System, clang::SrcMgr::C_User, clang::PreprocessorOptions::ChainedIncludes, clang::CompilerInstance::clearOutputFiles(), clang::LangOptions::CMK_ModuleMap, clang::LangOptions::CMK_None, clang::CompilerInstance::createASTContext(), clang::CompilerInstance::createASTReader(), clang::createChainedIncludesSource(), clang::SourceManager::createFileID(), clang::CompilerInstance::createFileManager(), clang::CompilerInstance::createPCHExternalASTSource(), clang::CompilerInstance::createPreprocessor(), clang::CompilerInstance::createSourceManager(), clang::LangOptions::CurrentModule, clang::PreprocessorOptions::DeserializedPCHDeclsToErrorOn, clang::PreprocessorOptions::DisablePCHOrModuleValidation, clang::PreprocessorOptions::DumpDeserializedPCHDecls, clang::DiagnosticConsumer::EndSourceFile(), clang::File, Filename, clang::ModuleMap::finishModuleDeclarationScope(), clang::CompilerInstance::getASTContext(), clang::CompilerInstance::getASTReader(), clang::Preprocessor::getBuiltinInfo(), clang::CompilerInstance::getCodeGenOpts(), getCurrentFileOrBufferName(), clang::CompilerInstance::getDiagnosticClient(), clang::CompilerInstance::getDiagnostics(), clang::FileManager::getDirectory(), clang::ASTContext::getExternalSource(), clang::FileManager::getFile(), clang::FrontendInputFile::getFile(), clang::CompilerInstance::getFileManager(), clang::CompilerInstance::getFileSystemOpts(), clang::InputKind::getFormat(), clang::CompilerInstance::getFrontendOpts(), clang::Preprocessor::getHeaderSearchInfo(), clang::CompilerInstance::getHeaderSearchOpts(), clang::InputKind::getHeaderUnitKind(), clang::Preprocessor::getIdentifierTable(), getInputBufferForModule(), clang::FrontendInputFile::getKind(), clang::CompilerInstance::getLangOpts(), clang::Preprocessor::getLangOpts(), clang::InputKind::getLanguage(), clang::ASTReader::getModuleManager(), clang::HeaderSearch::getModuleMap(), clang::FileEntry::getName(), clang::FileManager::getOptionalDirectoryRef(), clang::CompilerInstance::getPCHContainerReader(), clang::CompilerInstance::getPreprocessor(), clang::CompilerInstance::getPreprocessorOpts(), clang::serialization::ModuleManager::getPrimaryModule(), clang::CompilerInstance::getSourceManager(), clang::CompilerInstance::getSpecificModuleCachePath(), clang::CompilerInstance::getTargetOpts(), getTranslationUnitKind(), clang::FileManager::getVirtualFileSystem(), clang::CompilerInstance::hasASTConsumer(), clang::CompilerInstance::hasASTContext(), hasASTFileSupport(), clang::CompilerInstance::hasFileManager(), hasIRSupport(), hasPCHSupport(), clang::CompilerInstance::hasPreprocessor(), clang::CompilerInstance::hasSourceManager(), clang::InputKind::HeaderUnit_Abs, clang::InputKind::HeaderUnit_System, clang::PreprocessorOptions::ImplicitPCHInclude, clang::Builtin::Context::initializeBuiltins(), clang::SourceManager::initializeForReplay(), clang::CompilerInstance::InitializeSourceManager(), clang::ASTReader::isAcceptableASTFile(), clang::FrontendInputFile::isEmpty(), clang::InputKind::isHeaderUnit(), isModelParsingAction(), clang::FrontendInputFile::isPreprocessed(), clang::InputKind::isPreprocessed(), clang::FrontendInputFile::isSystem(), clang::LLVM_IR, clang::ASTUnit::LoadEverything, clang::ASTUnit::LoadFromASTFile(), clang::CompilerInstance::loadModuleFile(), clang::HeaderSearch::loadModuleMapFile(), loadModuleMapForModuleBuild(), clang::ASTUnit::LoadPreprocessorOnly, clang::HeaderSearch::LookupFile(), clang::FrontendOptions::ModuleFiles, clang::InputKind::ModuleMap, clang::FrontendOptions::ModuleMapFiles, clang::LangOptions::ModuleName, clang::FrontendOptions::ModulesEmbedAllFiles, clang::FrontendOptions::ModulesEmbedFiles, clang::FrontendOptions::OverrideRecordLayoutsFile, clang::InputKind::Precompiled, prepareToBuildModule(), clang::Module::PresumedModuleMapFile, ReadOriginalFileName(), clang::DiagnosticsEngine::Report(), clang::SourceManager::setAllFilesAreTransient(), clang::CompilerInstance::setASTConsumer(), clang::CompilerInstance::setASTContext(), clang::ASTContext::setASTMutationListener(), clang::CompilerInstance::setASTReader(), setCompilerInstance(), setCurrentInput(), clang::ASTContext::setExternalSource(), clang::SourceManager::setFileIsTransient(), clang::CompilerInstance::setFileManager(), clang::CompilerInstance::setPreprocessor(), clang::Preprocessor::setSkipMainFilePreamble(), clang::CompilerInstance::setSourceManager(), usesPreprocessorOnly(), clang::ASTReader::visitTopLevelModuleMaps(), and clang::InputKind::withHeaderUnit().
Referenced by clang::CompilerInstance::ExecuteAction(), and clang::ASTUnit::LoadFromCompilerInvocationAction().
BeginSourceFileAction()
virtual bool clang::FrontendAction::BeginSourceFileAction (CompilerInstance & CI) inline protected virtual
Callback at the start of processing a single input.
Returns
True on success; on failure ExecutionAction() and EndSourceFileAction() will not be called.
Reimplemented in clang::ASTMergeAction, clang::FixItAction, clang::GeneratePCHAction, clang::RewriteIncludesAction, and clang::WrapperFrontendAction.
Definition at line 85 of file FrontendAction.h.
Referenced by BeginSourceFile().
CreateASTConsumer()
virtual std::unique_ptr< ASTConsumer > clang::FrontendAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) protected pure virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Implemented in clang::arcmt::MigrateSourceAction, clang::arcmt::ObjCMigrateAction, clang::ASTDeclListAction, clang::ASTDumpAction, clang::ASTMergeAction, clang::ASTPrintAction, clang::ASTViewAction, clang::CodeGenAction, clang::DumpModuleInfoAction, clang::ento::AnalysisAction, clang::ento::ParseModelFileAction, clang::ExtractAPIAction, clang::FixItAction, clang::GenerateInterfaceStubsAction, clang::GenerateModuleAction, clang::GeneratePCHAction, clang::HTMLPrintAction, clang::PluginASTAction, clang::PreprocessorFrontendAction, clang::PrintDependencyDirectivesSourceMinimizerAction, clang::PrintPreambleAction, clang::RewriteObjCAction, clang::SyntaxOnlyAction, clang::TemplightDumpAction, clang::VerifyPCHAction, and clang::WrapperFrontendAction.
EndSourceFile()
void FrontendAction::EndSourceFile () virtual
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Reimplemented in clang::IncrementalAction, and clang::WrapperFrontendAction.
Definition at line 1059 of file FrontendAction.cpp.
References clang::CompilerInstance::clearOutputFiles(), clang::LangOptions::CMK_None, clang::FrontendOptions::DisableFree, clang::DiagnosticConsumer::EndSourceFile(), clang::Preprocessor::EndSourceFile(), EndSourceFileAction(), getCompilerInstance(), getCurrentFileOrBufferName(), clang::CompilerInstance::getDiagnosticClient(), clang::CompilerInstance::getFrontendOpts(), clang::Preprocessor::getHeaderSearchInfo(), clang::Preprocessor::getIdentifierTable(), clang::CompilerInstance::getLangOpts(), clang::CompilerInstance::getPreprocessor(), clang::CompilerInstance::getSourceManager(), clang::CompilerInstance::hasPreprocessor(), isCurrentFileAST(), clang::HeaderSearch::PrintStats(), clang::IdentifierTable::PrintStats(), clang::Preprocessor::PrintStats(), clang::SourceManager::PrintStats(), clang::CompilerInstance::resetAndLeakASTContext(), clang::CompilerInstance::resetAndLeakFileManager(), clang::CompilerInstance::resetAndLeakPreprocessor(), clang::CompilerInstance::resetAndLeakSema(), clang::CompilerInstance::resetAndLeakSourceManager(), clang::CompilerInstance::setASTConsumer(), clang::CompilerInstance::setASTContext(), setCompilerInstance(), setCurrentInput(), clang::CompilerInstance::setFileManager(), clang::CompilerInstance::setPreprocessor(), clang::CompilerInstance::setSema(), clang::CompilerInstance::setSourceManager(), shouldEraseOutputFiles(), clang::FrontendOptions::ShowStats, and clang::CompilerInstance::takeASTConsumer().
Referenced by clang::CompilerInstance::ExecuteAction(), and clang::ASTUnit::LoadFromCompilerInvocationAction().
EndSourceFileAction()
virtual void clang::FrontendAction::EndSourceFileAction () inline protected virtual
Callback at the end of processing a single input.
This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented in clang::ASTMergeAction, clang::CodeGenAction, clang::FixItAction, and clang::WrapperFrontendAction.
Definition at line 100 of file FrontendAction.h.
Referenced by EndSourceFile().
Execute()
llvm::Error FrontendAction::Execute ()
Set the source manager's main input file, and run the action.
Definition at line 1030 of file FrontendAction.cpp.
References ExecuteAction(), getCompilerInstance(), clang::CompilerInstance::getFileManager(), clang::CompilerInstance::getFrontendTimer(), clang::Preprocessor::getHeaderSearchInfo(), clang::HeaderSearch::getModuleCachePath(), clang::CompilerInstance::getPCHContainerReader(), clang::CompilerInstance::getPreprocessor(), clang::CompilerInstance::hasFileManager(), clang::CompilerInstance::hasFrontendTimer(), clang::CompilerInstance::hasPreprocessor(), clang::CompilerInstance::shouldBuildGlobalModuleIndex(), and clang::GlobalModuleIndex::writeIndex().
Referenced by clang::CompilerInstance::ExecuteAction(), and clang::ASTUnit::LoadFromCompilerInvocationAction().
ExecuteAction()
virtual void clang::FrontendAction::ExecuteAction () protected pure virtual
Callback to run the program action, using the initialized compiler instance.
This is guaranteed to only be called between BeginSourceFileAction() and EndSourceFileAction().
Implemented in ASTSrcLocGenerationAction, clang::ASTFrontendAction, clang::ASTMergeAction, clang::CodeGenAction, clang::DumpModuleInfoAction, clang::DumpRawTokensAction, clang::DumpTokensAction, clang::IncrementalAction, clang::PreprocessOnlyAction, clang::PrintDependencyDirectivesSourceMinimizerAction, clang::PrintPreambleAction, clang::PrintPreprocessedAction, clang::RewriteIncludesAction, clang::RewriteMacrosAction, clang::RewriteTestAction, clang::TemplightDumpAction, clang::VerifyPCHAction, and clang::WrapperFrontendAction.
Referenced by Execute().
getCompilerInstance()
CompilerInstance & clang::FrontendAction::getCompilerInstance () const inline
Definition at line 119 of file FrontendAction.h.
Referenced by clang::FixItAction::BeginSourceFileAction(), EndSourceFile(), clang::CodeGenAction::EndSourceFileAction(), Execute(), ASTSrcLocGenerationAction::ExecuteAction(), clang::ASTFrontendAction::ExecuteAction(), clang::ASTMergeAction::ExecuteAction(), clang::CodeGenAction::ExecuteAction(), clang::DumpModuleInfoAction::ExecuteAction(), clang::DumpRawTokensAction::ExecuteAction(), clang::DumpTokensAction::ExecuteAction(), clang::IncrementalAction::ExecuteAction(), clang::PreprocessOnlyAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), clang::PrintPreambleAction::ExecuteAction(), clang::PrintPreprocessedAction::ExecuteAction(), clang::RewriteIncludesAction::ExecuteAction(), clang::RewriteMacrosAction::ExecuteAction(), clang::RewriteTestAction::ExecuteAction(), clang::TemplightDumpAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), getCurrentModule(), shouldEraseOutputFiles(), clang::GenerateModuleAction::shouldEraseOutputFiles(), and clang::GeneratePCHAction::shouldEraseOutputFiles().
getCurrentASTUnit()
ASTUnit & clang::FrontendAction::getCurrentASTUnit () const inline
Definition at line 156 of file FrontendAction.h.
Referenced by clang::DumpModuleInfoAction::ExecuteAction().
getCurrentFile()
StringRef clang::FrontendAction::getCurrentFile () const inline
Definition at line 139 of file FrontendAction.h.
References clang::FrontendInputFile::getFile(), and clang::FrontendInputFile::isEmpty().
Referenced by clang::DumpModuleInfoAction::ExecuteAction(), clang::PrintPreambleAction::ExecuteAction(), and clang::VerifyPCHAction::ExecuteAction().
getCurrentFileKind()
InputKind clang::FrontendAction::getCurrentFileKind () const inline
Definition at line 151 of file FrontendAction.h.
References clang::FrontendInputFile::getKind(), and clang::FrontendInputFile::isEmpty().
Referenced by clang::CodeGenAction::ExecuteAction(), and clang::PrintPreambleAction::ExecuteAction().
getCurrentFileOrBufferName()
StringRef clang::FrontendAction::getCurrentFileOrBufferName () const inline
Definition at line 144 of file FrontendAction.h.
References clang::FrontendInputFile::getBuffer(), clang::FrontendInputFile::getFile(), clang::FrontendInputFile::isEmpty(), and clang::FrontendInputFile::isFile().
Referenced by BeginSourceFile(), clang::RewriteIncludesAction::BeginSourceFileAction(), EndSourceFile(), clang::CodeGenAction::ExecuteAction(), clang::PrintPreprocessedAction::ExecuteAction(), clang::RewriteMacrosAction::ExecuteAction(), and clang::RewriteTestAction::ExecuteAction().
getCurrentInput()
const FrontendInputFile & clang::FrontendAction::getCurrentInput () const inline
Definition at line 135 of file FrontendAction.h.
Referenced by clang::arcmt::CheckAction::BeginInvocation(), clang::arcmt::MigrateAction::BeginInvocation(), clang::arcmt::ModifyAction::BeginInvocation(), clang::ASTMergeAction::BeginSourceFileAction(), clang::RewriteIncludesAction::BeginSourceFileAction(), clang::WrapperFrontendAction::BeginSourceFileAction(), and clang::PrintPreprocessedAction::ExecuteAction().
getCurrentModule()
Module * FrontendAction::getCurrentModule () const
Definition at line 145 of file FrontendAction.cpp.
References clang::LangOptions::CurrentModule, getCompilerInstance(), clang::Preprocessor::getHeaderSearchInfo(), clang::CompilerInstance::getLangOpts(), clang::CompilerInstance::getPreprocessor(), and clang::HeaderSearch::lookupModule().
Referenced by clang::RewriteIncludesAction::BeginSourceFileAction(), and clang::PrintPreprocessedAction::ExecuteAction().
getTranslationUnitKind()
virtual TranslationUnitKind clang::FrontendAction::getTranslationUnitKind () inline virtual
For AST-based actions, the kind of translation unit we're handling.
Reimplemented in clang::ASTMergeAction, clang::GenerateInterfaceStubsAction, clang::GenerateModuleAction, clang::GeneratePCHAction, clang::IncrementalAction, and clang::WrapperFrontendAction.
Definition at line 188 of file FrontendAction.h.
References clang::TU_Complete.
Referenced by BeginSourceFile(), clang::ASTFrontendAction::ExecuteAction(), and clang::ASTUnit::LoadFromCompilerInvocationAction().
hasASTFileSupport()
virtual bool clang::FrontendAction::hasASTFileSupport () const inline virtual
Does this action support use with AST files?
Reimplemented in clang::ASTMergeAction, clang::DumpModuleInfoAction, clang::FixItAction, clang::GenerateInterfaceStubsAction, clang::GenerateModuleAction, clang::GeneratePCHAction, and clang::WrapperFrontendAction.
Definition at line 194 of file FrontendAction.h.
Referenced by BeginSourceFile().
hasCodeCompletionSupport()
virtual bool clang::FrontendAction::hasCodeCompletionSupport () const inline virtual
Does this action support use with code completion?
Reimplemented in clang::ASTMergeAction, clang::DumpModuleInfoAction, clang::SyntaxOnlyAction, clang::VerifyPCHAction, and clang::WrapperFrontendAction.
Definition at line 200 of file FrontendAction.h.
Referenced by clang::ASTFrontendAction::ExecuteAction().
hasIRSupport()
virtual bool clang::FrontendAction::hasIRSupport () const inline virtual
Does this action support use with IR files?
Reimplemented in clang::CodeGenAction, clang::DumpModuleInfoAction, and clang::WrapperFrontendAction.
Definition at line 197 of file FrontendAction.h.
Referenced by BeginSourceFile(), and clang::getCodeGen().
hasPCHSupport()
virtual bool clang::FrontendAction::hasPCHSupport () const inline virtual
Does this action support use with PCH?
Reimplemented in clang::ASTMergeAction, clang::DumpModuleInfoAction, clang::PrintPreprocessedAction, and clang::WrapperFrontendAction.
Definition at line 191 of file FrontendAction.h.
Referenced by BeginSourceFile().
isCurrentFileAST()
bool clang::FrontendAction::isCurrentFileAST () const inline
Definition at line 130 of file FrontendAction.h.
References clang::FrontendInputFile::isEmpty().
Referenced by EndSourceFile(), and clang::DumpModuleInfoAction::ExecuteAction().
isModelParsingAction()
virtual bool clang::FrontendAction::isModelParsingAction () const inline virtual
Is this action invoked on a model file?
Model files are incomplete translation units that relies on type information from another translation unit. Check ParseModelFileAction for details.
Reimplemented in clang::ento::ParseModelFileAction.
Definition at line 179 of file FrontendAction.h.
Referenced by BeginSourceFile(), and clang::CompilerInstance::ExecuteAction().
PrepareToExecute()
bool clang::FrontendAction::PrepareToExecute (CompilerInstance & CI) inline
Prepare the action to execute on the given compiler instance.
Definition at line 207 of file FrontendAction.h.
References PrepareToExecuteAction().
Referenced by clang::CompilerInstance::ExecuteAction().
PrepareToExecuteAction()
virtual bool clang::FrontendAction::PrepareToExecuteAction (CompilerInstance & CI) inline protected virtual
Prepare to execute the action on the given CompilerInstance.
This is called before executing the action on any inputs, and can modify the configuration as needed (including adjusting the input list).
Reimplemented in clang::WrapperFrontendAction.
Definition at line 55 of file FrontendAction.h.
Referenced by PrepareToExecute().
setCompilerInstance()
void clang::FrontendAction::setCompilerInstance (CompilerInstance * Value) inline
Definition at line 124 of file FrontendAction.h.
Referenced by BeginSourceFile(), and EndSourceFile().
setCurrentInput()
void FrontendAction::setCurrentInput (const FrontendInputFile & CurrentInput, std::unique_ptr< ASTUnit > AST = nullptr)
Definition at line 139 of file FrontendAction.cpp.
Referenced by BeginSourceFile(), clang::WrapperFrontendAction::BeginSourceFileAction(), and EndSourceFile().
shouldEraseOutputFiles()
bool FrontendAction::shouldEraseOutputFiles () protected virtual
Callback at the end of processing a single input, to determine if the output files should be erased or not.
By default it returns true if a compiler error occurred. This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented in clang::GenerateModuleAction, clang::GeneratePCHAction, and clang::WrapperFrontendAction.
Definition at line 1117 of file FrontendAction.cpp.
References getCompilerInstance(), clang::CompilerInstance::getDiagnostics(), and clang::DiagnosticsEngine::hasErrorOccurred().
Referenced by EndSourceFile(), clang::GenerateModuleAction::shouldEraseOutputFiles(), and clang::GeneratePCHAction::shouldEraseOutputFiles().
takeCurrentASTUnit()
std::unique_ptr< ASTUnit > clang::FrontendAction::takeCurrentASTUnit () inline
Definition at line 163 of file FrontendAction.h.
Referenced by clang::ASTMergeAction::BeginSourceFileAction().
usesPreprocessorOnly()
virtual bool clang::FrontendAction::usesPreprocessorOnly () const pure virtual
Does this action only use the preprocessor?
If so no AST context will be created and this action will be invalid with AST file inputs.
Implemented in clang::ASTFrontendAction, clang::ASTMergeAction, clang::DumpCompilerOptionsAction, clang::InitOnlyAction, clang::PreprocessorFrontendAction, clang::PrintDependencyDirectivesSourceMinimizerAction, clang::PrintPreambleAction, clang::ReadPCHAndPreprocessAction, and clang::WrapperFrontendAction.
Referenced by BeginSourceFile().
Friends And Related Symbol Documentation
ASTMergeAction
friend class ASTMergeAction friend
Definition at line 40 of file FrontendAction.h.
WrapperFrontendAction
friend class WrapperFrontendAction friend
Definition at line 41 of file FrontendAction.h.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendAction.h
lib/Frontend/FrontendAction.cpp