clang: clang::driver::MultilibSet Class Reference
clang::driver::MultilibSet Class Reference
#include "clang/Driver/Multilib.h"
Public Types
using multilib_list = std::vector<Multilib>
using iterator = multilib_list::iterator
using const_iterator = multilib_list::const_iterator
using IncludeDirsFunc
using FilterCallback = llvm::function_ref<bool(const Multilib &)>
Public Member Functions
MultilibSet ()=default
MultilibSet & Maybe (const Multilib &M)
Add an optional Multilib segment.
MultilibSet & Either (const Multilib &M1, const Multilib &M2)
Add a set of mutually incompatible Multilib segments.
MultilibSet & Either (const Multilib &M1, const Multilib &M2, const Multilib &M3)
MultilibSet & Either (const Multilib &M1, const Multilib &M2, const Multilib &M3, const Multilib &M4)
MultilibSet & Either (const Multilib &M1, const Multilib &M2, const Multilib &M3, const Multilib &M4, const Multilib &M5)
MultilibSet & Either (ArrayRef< Multilib > Ms)
MultilibSet & FilterOut (FilterCallback F)
Filter out some subset of the Multilibs using a user defined callback.
MultilibSet & FilterOut (const char *Regex)
Filter out those Multilibs whose gccSuffix matches the given expression.
void push_back (const Multilib &M)
Add a completed Multilib to the set.
void combineWith (const MultilibSet &MS)
Union this set of multilibs with another.
void clear ()
Remove all of the multilibs from the set.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool select (const Multilib::flags_list &Flags, Multilib &M) const
Pick the best multilib in the set,.
unsigned size () const
LLVM_DUMP_METHOD void dump () const
void print (raw_ostream &OS) const
MultilibSet & setIncludeDirsCallback (IncludeDirsFunc F)
const IncludeDirsFunc & includeDirsCallback () const
MultilibSet & setFilePathsCallback (IncludeDirsFunc F)
const IncludeDirsFunc & filePathsCallback () const
Detailed Description
Definition at line 114 of file Multilib.h.
Member Typedef Documentation
const_iterator
using clang::driver::MultilibSet::const_iterator = multilib_list::const_iterator
Definition at line 118 of file Multilib.h.
FilterCallback
using clang::driver::MultilibSet::FilterCallback = llvm::function_ref<bool(const Multilib &)>
Definition at line 121 of file Multilib.h.
IncludeDirsFunc
using clang::driver::MultilibSet::IncludeDirsFunc
Initial value:
      std::function<std::vector<std::string>(const Multilib &M)>
Definition at line 119 of file Multilib.h.
iterator
using clang::driver::MultilibSet::iterator = multilib_list::iterator
Definition at line 117 of file Multilib.h.
multilib_list
using clang::driver::MultilibSet::multilib_list = std::vector<Multilib>
Definition at line 116 of file Multilib.h.
Constructor & Destructor Documentation
MultilibSet()
clang::driver::MultilibSet::MultilibSet () default
Member Function Documentation
begin() [1/2]
iterator clang::driver::MultilibSet::begin () inline
Definition at line 160 of file Multilib.h.
Referenced by combineWith().
begin() [2/2]
const_iterator clang::driver::MultilibSet::begin () const inline
Definition at line 161 of file Multilib.h.
clear()
void clang::driver::MultilibSet::clear () inline
Remove all of the multilibs from the set.
Definition at line 158 of file Multilib.h.
combineWith()
void MultilibSet::combineWith (const MultilibSet & MS)
Union this set of multilibs with another.
Definition at line 234 of file Multilib.cpp.
References begin(), and end().
dump()
LLVM_DUMP_METHOD void MultilibSet::dump () const
Definition at line 284 of file Multilib.cpp.
References print().
Either() [1/5]
MultilibSet & MultilibSet::Either (ArrayRef< Multilib > Ms)
Definition at line 191 of file Multilib.cpp.
References compose(), and clang::driver::Multilib::isValid().
Either() [2/5]
MultilibSet & MultilibSet::Either (const Multilib & M1, const Multilib & M2)
Add a set of mutually incompatible Multilib segments.
Definition at line 152 of file Multilib.cpp.
References Either().
Referenced by Either(), Either(), Either(), Either(), findAndroidArmMultilibs(), findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), findMipsMtiMultilibs(), findMipsMuslMultilibs(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), findRISCVMultilibs(), and Maybe().
Either() [3/5]
MultilibSet & MultilibSet::Either (const Multilib & M1, const Multilib & M2, const Multilib & M3)
Definition at line 156 of file Multilib.cpp.
References Either().
Either() [4/5]
MultilibSet & MultilibSet::Either (const Multilib & M1, const Multilib & M2, const Multilib & M3, const Multilib & M4)
Definition at line 161 of file Multilib.cpp.
References Either().
Either() [5/5]
MultilibSet & MultilibSet::Either (const Multilib & M1, const Multilib & M2, const Multilib & M3, const Multilib & M4, const Multilib & M5)
Definition at line 166 of file Multilib.cpp.
References Either().
end() [1/2]
iterator clang::driver::MultilibSet::end () inline
Definition at line 163 of file Multilib.h.
Referenced by combineWith().
end() [2/2]
const_iterator clang::driver::MultilibSet::end () const inline
Definition at line 164 of file Multilib.h.
filePathsCallback()
const IncludeDirsFunc & clang::driver::MultilibSet::filePathsCallback () const inline
Definition at line 186 of file Multilib.h.
Referenced by clang::driver::toolchains::Generic_GCC::AddMultilibPaths(), addMultilibsFilePaths(), addMultilibsFilePaths(), and clang::driver::toolchains::Fuchsia::Fuchsia().
FilterOut() [1/2]
MultilibSet & MultilibSet::FilterOut (const char * Regex)
Filter out those Multilibs whose gccSuffix matches the given expression.
Definition at line 217 of file Multilib.cpp.
References clang::Error, and clang::driver::Multilib::gccSuffix().
FilterOut() [2/2]
MultilibSet & MultilibSet::FilterOut (FilterCallback F)
Filter out some subset of the Multilibs using a user defined callback.
Definition at line 212 of file Multilib.cpp.
Referenced by findAndroidArmMultilibs(), findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), findMipsMtiMultilibs(), findRISCVBareMetalMultilibs(), and clang::driver::toolchains::Fuchsia::Fuchsia().
includeDirsCallback()
const IncludeDirsFunc & clang::driver::MultilibSet::includeDirsCallback () const inline
Definition at line 179 of file Multilib.h.
Referenced by clang::driver::toolchains::MipsLLVMToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), clang::driver::toolchains::MipsLLVMToolChain::addLibCxxIncludePaths(), and clang::driver::toolchains::Generic_GCC::AddMultilibIncludeArgs().
Maybe()
MultilibSet & MultilibSet::Maybe (const Multilib & M)
Add an optional Multilib segment.
Definition at line 142 of file Multilib.cpp.
References Either(), and clang::driver::Multilib::flags().
Referenced by findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), and findMipsMtiMultilibs().
print()
void MultilibSet::print (raw_ostream & OS) const
Definition at line 288 of file Multilib.cpp.
Referenced by dump(), and clang::driver::operator<<().
push_back()
void MultilibSet::push_back (const Multilib & M)
Add a completed Multilib to the set.
Definition at line 232 of file Multilib.cpp.
Referenced by clang::driver::toolchains::Fuchsia::Fuchsia().
select()
bool MultilibSet::select (const Multilib::flags_list & Flags, Multilib & M) const
Pick the best multilib in the set,.
Returns
false if none are compatible
Definition at line 244 of file Multilib.cpp.
References b, clang::driver::Multilib::flags(), isFlagEnabled(), and clang::driver::Multilib::priority().
Referenced by findAndroidArmMultilibs(), findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsMuslMultilibs(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), and clang::driver::toolchains::Fuchsia::Fuchsia().
setFilePathsCallback()
MultilibSet & clang::driver::MultilibSet::setFilePathsCallback (IncludeDirsFunc F) inline
Definition at line 181 of file Multilib.h.
Referenced by findRISCVBareMetalMultilibs(), and clang::driver::toolchains::Fuchsia::Fuchsia().
setIncludeDirsCallback()
MultilibSet & clang::driver::MultilibSet::setIncludeDirsCallback (IncludeDirsFunc F) inline
Definition at line 174 of file Multilib.h.
Referenced by findMipsCsMultilibs(), findMipsImgMultilibs(), findMipsMtiMultilibs(), and findMipsMuslMultilibs().
size()
unsigned clang::driver::MultilibSet::size () const inline
Definition at line 169 of file Multilib.h.
Referenced by findMipsCsMultilibs().
The documentation for this class was generated from the following files:
include/clang/Driver/Multilib.h
lib/Driver/Multilib.cpp