clang: clang::ObjCAtTryStmt Class Reference
clang::ObjCAtTryStmt Class Reference final
Represents Objective-C's @try ... @catch ... @finally statement.
#include "clang/AST/StmtObjC.h"
Public Types
using catch_stmt_iterator = CastIterator<ObjCAtCatchStmt>
using const_catch_stmt_iterator = ConstCastIterator<ObjCAtCatchStmt>
using catch_range = llvm::iterator_range<catch_stmt_iterator>
using catch_const_range = llvm::iterator_range<const_catch_stmt_iterator>
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
SourceLocation getAtTryLoc () const
Retrieve the location of the @ in the @try.
void setAtTryLoc (SourceLocation Loc)
const Stmt * getTryBody () const
Retrieve the @try body.
Stmt * getTryBody ()
void setTryBody (Stmt *S)
unsigned getNumCatchStmts () const
Retrieve the number of @catch statements in this try-catch-finally block.
const ObjCAtCatchStmt * getCatchStmt (unsigned I) const
Retrieve a @catch statement.
ObjCAtCatchStmt * getCatchStmt (unsigned I)
Retrieve a @catch statement.
void setCatchStmt (unsigned I, ObjCAtCatchStmt *S)
Set a particular catch statement.
const ObjCAtFinallyStmt * getFinallyStmt () const
Retrieve the @finally statement, if any.
ObjCAtFinallyStmt * getFinallyStmt ()
void setFinallyStmt (Stmt *S)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
catch_stmt_iterator catch_stmts_begin ()
catch_stmt_iterator catch_stmts_end ()
catch_range catch_stmts ()
const_catch_stmt_iterator catch_stmts_begin () const
const_catch_stmt_iterator catch_stmts_end () const
catch_const_range catch_stmts () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static ObjCAtTryStmt * Create (const ASTContext &Context, SourceLocation atTryLoc, Stmt *atTryStmt, Stmt **CatchStmts, unsigned NumCatchStmts, Stmt *atFinallyStmt)
static ObjCAtTryStmt * CreateEmpty (const ASTContext &Context, unsigned NumCatchStmts, bool HasFinally)
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
Represents Objective-C's @try ... @catch ... @finally statement.
Definition at line 165 of file StmtObjC.h.
Member Typedef Documentation
catch_const_range
using clang::ObjCAtTryStmt::catch_const_range = llvm::iterator_range<const_catch_stmt_iterator>
Definition at line 275 of file StmtObjC.h.
catch_range
using clang::ObjCAtTryStmt::catch_range = llvm::iterator_range<catch_stmt_iterator>
Definition at line 274 of file StmtObjC.h.
catch_stmt_iterator
using clang::ObjCAtTryStmt::catch_stmt_iterator = CastIterator<ObjCAtCatchStmt>
Definition at line 272 of file StmtObjC.h.
const_catch_stmt_iterator
using clang::ObjCAtTryStmt::const_catch_stmt_iterator = ConstCastIterator<ObjCAtCatchStmt>
Definition at line 273 of file StmtObjC.h.
Member Function Documentation
catch_stmts() [1/2]
catch_range clang::ObjCAtTryStmt::catch_stmts () inline
Definition at line 281 of file StmtObjC.h.
References catch_stmts_begin(), and catch_stmts_end().
catch_stmts() [2/2]
catch_const_range clang::ObjCAtTryStmt::catch_stmts () const inline
Definition at line 289 of file StmtObjC.h.
References catch_stmts_begin(), and catch_stmts_end().
catch_stmts_begin() [1/2]
catch_stmt_iterator clang::ObjCAtTryStmt::catch_stmts_begin () inline
Definition at line 277 of file StmtObjC.h.
Referenced by catch_stmts(), catch_stmts(), catch_stmts_end(), and catch_stmts_end().
catch_stmts_begin() [2/2]
const_catch_stmt_iterator clang::ObjCAtTryStmt::catch_stmts_begin () const inline
Definition at line 285 of file StmtObjC.h.
catch_stmts_end() [1/2]
catch_stmt_iterator clang::ObjCAtTryStmt::catch_stmts_end () inline
Definition at line 278 of file StmtObjC.h.
References catch_stmts_begin().
Referenced by catch_stmts(), and catch_stmts().
catch_stmts_end() [2/2]
const_catch_stmt_iterator clang::ObjCAtTryStmt::catch_stmts_end () const inline
Definition at line 286 of file StmtObjC.h.
References catch_stmts_begin().
children() [1/2]
child_range clang::ObjCAtTryStmt::children () inline
Definition at line 263 of file StmtObjC.h.
Referenced by children().
children() [2/2]
const_child_range clang::ObjCAtTryStmt::children () const inline
Definition at line 268 of file StmtObjC.h.
References children().
classof()
static bool clang::ObjCAtTryStmt::classof (const Stmt * T) inline static
Definition at line 259 of file StmtObjC.h.
Create()
ObjCAtTryStmt * ObjCAtTryStmt::Create (const ASTContext & Context, SourceLocation atTryLoc, Stmt * atTryStmt, Stmt ** CatchStmts, unsigned NumCatchStmts, Stmt * atFinallyStmt) static
Definition at line 45 of file StmtObjC.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::Sema::ActOnObjCAtTryStmt(), and clang::ASTNodeImporter::VisitObjCAtTryStmt().
CreateEmpty()
ObjCAtTryStmt * ObjCAtTryStmt::CreateEmpty (const ASTContext & Context, unsigned NumCatchStmts, bool HasFinally) static
Definition at line 56 of file StmtObjC.cpp.
References clang::ASTContext::Allocate().
getAtTryLoc()
SourceLocation clang::ObjCAtTryStmt::getAtTryLoc () const inline
Retrieve the location of the @ in the @try.
Definition at line 208 of file StmtObjC.h.
getBeginLoc()
SourceLocation clang::ObjCAtTryStmt::getBeginLoc () const inline
Definition at line 256 of file StmtObjC.h.
getCatchStmt() [1/2]
ObjCAtCatchStmt * clang::ObjCAtTryStmt::getCatchStmt (unsigned I) inline
Retrieve a @catch statement.
Definition at line 227 of file StmtObjC.h.
getCatchStmt() [2/2]
const ObjCAtCatchStmt * clang::ObjCAtTryStmt::getCatchStmt (unsigned I) const inline
Retrieve a @catch statement.
Definition at line 221 of file StmtObjC.h.
Referenced by getEndLoc().
getEndLoc()
SourceLocation ObjCAtTryStmt::getEndLoc () const
Definition at line 64 of file StmtObjC.cpp.
References getCatchStmt(), clang::ObjCAtCatchStmt::getEndLoc(), clang::ObjCAtFinallyStmt::getEndLoc(), clang::Stmt::getEndLoc(), getFinallyStmt(), and getTryBody().
getFinallyStmt() [1/2]
ObjCAtFinallyStmt * clang::ObjCAtTryStmt::getFinallyStmt () inline
Definition at line 245 of file StmtObjC.h.
getFinallyStmt() [2/2]
const ObjCAtFinallyStmt * clang::ObjCAtTryStmt::getFinallyStmt () const inline
Retrieve the @finally statement, if any.
Definition at line 239 of file StmtObjC.h.
Referenced by getEndLoc().
getNumCatchStmts()
unsigned clang::ObjCAtTryStmt::getNumCatchStmts () const inline
Retrieve the number of @catch statements in this try-catch-finally block.
Definition at line 218 of file StmtObjC.h.
getTryBody() [1/2]
Stmt * clang::ObjCAtTryStmt::getTryBody () inline
Definition at line 213 of file StmtObjC.h.
getTryBody() [2/2]
const Stmt * clang::ObjCAtTryStmt::getTryBody () const inline
Retrieve the @try body.
Definition at line 212 of file StmtObjC.h.
Referenced by getEndLoc().
setAtTryLoc()
void clang::ObjCAtTryStmt::setAtTryLoc (SourceLocation Loc) inline
Definition at line 209 of file StmtObjC.h.
setCatchStmt()
void clang::ObjCAtTryStmt::setCatchStmt (unsigned I, ObjCAtCatchStmt * S) inline
Set a particular catch statement.
Definition at line 233 of file StmtObjC.h.
setFinallyStmt()
void clang::ObjCAtTryStmt::setFinallyStmt (Stmt * S) inline
Definition at line 251 of file StmtObjC.h.
setTryBody()
void clang::ObjCAtTryStmt::setTryBody (Stmt * S) inline
Definition at line 214 of file StmtObjC.h.
The documentation for this class was generated from the following files:
include/clang/AST/StmtObjC.h
lib/AST/StmtObjC.cpp