clang: clang::CodeGen::SwiftABIInfo Class Reference
clang::CodeGen::SwiftABIInfo Class Reference abstract
A refining implementation of ABIInfo for targets that support swiftcall.
#include "/root/llvm-project/clang/lib/CodeGen/ABIInfo.h"
Public Member Functions
SwiftABIInfo (CodeGen::CodeGenTypes &cgt)
bool supportsSwift () const final
virtual bool shouldPassIndirectlyForSwift (ArrayRef< llvm::Type * > types, bool asReturnValue) const =0
virtual bool isLegalVectorTypeForSwift (CharUnits totalSize, llvm::Type *eltTy, unsigned elts) const
virtual bool isSwiftErrorInRegister () const =0
Public Member Functions inherited from clang::CodeGen::ABIInfo
ABIInfo (CodeGen::CodeGenTypes &cgt)
virtual ~ABIInfo ()
virtual bool allowBFloatArgsAndRet () const
CodeGen::CGCXXABI & getCXXABI () const
ASTContext & getContext () const
llvm::LLVMContext & getVMContext () const
const llvm::DataLayout & getDataLayout () const
const TargetInfo & getTarget () const
const CodeGenOptions & getCodeGenOpts () const
llvm::CallingConv::ID getRuntimeCC () const
Return the calling convention to use for system runtime functions.
virtual void computeInfo (CodeGen::CGFunctionInfo &FI) const =0
virtual CodeGen::Address EmitVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const =0
EmitVAArg - Emit the target dependent code to load a value of.
bool isAndroid () const
virtual CodeGen::Address EmitMSVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const
Emit the target dependent code to load a value of.
virtual bool isHomogeneousAggregateBaseType (QualType Ty) const
virtual bool isHomogeneousAggregateSmallEnough (const Type *Base, uint64_t Members) const
virtual bool isZeroLengthBitfieldPermittedInHomogeneousAggregate () const
bool isHomogeneousAggregate (QualType Ty, const Type *&Base, uint64_t &Members) const
isHomogeneousAggregate - Return true if a type is an ELFv2 homogeneous aggregate.
bool isPromotableIntegerTypeForABI (QualType Ty) const
CodeGen::ABIArgInfo getNaturalAlignIndirect (QualType Ty, bool ByVal=true, bool Realign=false, llvm::Type *Padding=nullptr) const
A convenience method to return an indirect ABIArgInfo with an expected alignment equal to the ABI alignment of the given type.
CodeGen::ABIArgInfo getNaturalAlignIndirectInReg (QualType Ty, bool Realign=false) const
Static Public Member Functions
static bool classof (const ABIInfo *info)
Additional Inherited Members
Public Attributes inherited from clang::CodeGen::ABIInfo
CodeGen::CodeGenTypes & CGT
Protected Attributes inherited from clang::CodeGen::ABIInfo
llvm::CallingConv::ID RuntimeCC
Detailed Description
A refining implementation of ABIInfo for targets that support swiftcall.
If we find ourselves wanting multiple such refinements, they'll probably be independent refinements, and we should probably find another way to do it than simple inheritance.
Definition at line 126 of file ABIInfo.h.
Constructor & Destructor Documentation
SwiftABIInfo()
clang::CodeGen::SwiftABIInfo::SwiftABIInfo (CodeGen::CodeGenTypes & cgt) inline
Definition at line 128 of file ABIInfo.h.
Member Function Documentation
classof()
static bool clang::CodeGen::SwiftABIInfo::classof (const ABIInfo * info) inline static
Definition at line 141 of file ABIInfo.h.
References clang::CodeGen::ABIInfo::supportsSwift().
isLegalVectorTypeForSwift()
bool SwiftABIInfo::isLegalVectorTypeForSwift (CharUnits totalSize, llvm::Type * eltTy, unsigned elts) const virtual
Definition at line 154 of file TargetInfo.cpp.
References clang::CharUnits::getQuantity().
Referenced by clang::CodeGen::swiftcall::isLegalVectorType().
isSwiftErrorInRegister()
virtual bool clang::CodeGen::SwiftABIInfo::isSwiftErrorInRegister () const pure virtual
Referenced by clang::CodeGen::swiftcall::isSwiftErrorLoweredInRegister().
shouldPassIndirectlyForSwift()
virtual bool clang::CodeGen::SwiftABIInfo::shouldPassIndirectlyForSwift (ArrayRef< llvm::Type * > types, bool asReturnValue) const pure virtual
Referenced by clang::CodeGen::swiftcall::shouldPassIndirectly(), and clang::CodeGen::swiftcall::SwiftAggLowering::shouldPassIndirectly().
supportsSwift()
bool clang::CodeGen::SwiftABIInfo::supportsSwift () const inline final virtual
Reimplemented from clang::CodeGen::ABIInfo.
Definition at line 130 of file ABIInfo.h.
The documentation for this class was generated from the following files:
lib/CodeGen/ABIInfo.h
lib/CodeGen/TargetInfo.cpp