clang: clang::CapturedStmt Class Reference
clang::CapturedStmt Class Reference
This captures a statement into a function.
#include "clang/AST/Stmt.h"
Classes
class Capture
Describes the capture of either a variable, or 'this', or variable-length array type.
Public Types
enum VariableCaptureKind { VCK_This , VCK_ByRef , VCK_ByCopy , VCK_VLAType }
The different capture forms: by 'this', by reference, capture for variable-length array type etc.
using capture_iterator = Capture *
An iterator that walks over the captures.
using const_capture_iterator = const Capture *
using capture_range = llvm::iterator_range<capture_iterator>
using capture_const_range = llvm::iterator_range<const_capture_iterator>
using capture_init_iterator = Expr **
Iterator that walks over the capture initialization arguments.
using capture_init_range = llvm::iterator_range<capture_init_iterator>
using const_capture_init_iterator = Expr *const *
Const iterator that walks over the capture initialization arguments.
using const_capture_init_range
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
Stmt * getCapturedStmt ()
Retrieve the statement being captured.
const Stmt * getCapturedStmt () const
CapturedDecl * getCapturedDecl ()
Retrieve the outlined function declaration.
const CapturedDecl * getCapturedDecl () const
void setCapturedDecl (CapturedDecl *D)
Set the outlined function declaration.
CapturedRegionKind getCapturedRegionKind () const
Retrieve the captured region kind.
void setCapturedRegionKind (CapturedRegionKind Kind)
Set the captured region kind.
const RecordDecl * getCapturedRecordDecl () const
Retrieve the record declaration for captured variables.
void setCapturedRecordDecl (RecordDecl *D)
Set the record declaration for captured variables.
bool capturesVariable (const VarDecl *Var) const
True if this variable has been captured.
capture_range captures ()
capture_const_range captures () const
capture_iterator capture_begin ()
Retrieve an iterator pointing to the first capture.
const_capture_iterator capture_begin () const
capture_iterator capture_end () const
Retrieve an iterator pointing past the end of the sequence of captures.
unsigned capture_size () const
Retrieve the number of captures, including 'this'.
capture_init_range capture_inits ()
const_capture_init_range capture_inits () const
capture_init_iterator capture_init_begin ()
Retrieve the first initialization argument.
const_capture_init_iterator capture_init_begin () const
capture_init_iterator capture_init_end ()
Retrieve the iterator pointing one past the last initialization argument.
const_capture_init_iterator capture_init_end () const
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceRange getSourceRange () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CapturedStmt * Create (const ASTContext &Context, Stmt *S, CapturedRegionKind Kind, ArrayRef< Capture > Captures, ArrayRef< Expr * > CaptureInits, CapturedDecl *CD, RecordDecl *RD)
static CapturedStmt * CreateDeserialized (const ASTContext &Context, unsigned NumCaptures)
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
This captures a statement into a function.
For example, the following pragma annotated compound statement can be represented as a CapturedStmt, and this compound statement is the body of an anonymous outlined function.
#pragma omp parallel
{
  compute();
}
Definition at line 3532 of file Stmt.h.
Member Typedef Documentation
capture_const_range
using clang::CapturedStmt::capture_const_range = llvm::iterator_range<const_capture_iterator>
Definition at line 3665 of file Stmt.h.
capture_init_iterator
using clang::CapturedStmt::capture_init_iterator = Expr **
Iterator that walks over the capture initialization arguments.
Definition at line 3688 of file Stmt.h.
capture_init_range
using clang::CapturedStmt::capture_init_range = llvm::iterator_range<capture_init_iterator>
Definition at line 3689 of file Stmt.h.
capture_iterator
using clang::CapturedStmt::capture_iterator = Capture *
An iterator that walks over the captures.
Definition at line 3662 of file Stmt.h.
capture_range
using clang::CapturedStmt::capture_range = llvm::iterator_range<capture_iterator>
Definition at line 3664 of file Stmt.h.
const_capture_init_iterator
using clang::CapturedStmt::const_capture_init_iterator = Expr *const *
Const iterator that walks over the capture initialization arguments.
Definition at line 3693 of file Stmt.h.
const_capture_init_range
using clang::CapturedStmt::const_capture_init_range
Initial value:
      llvm::iterator_range<const_capture_init_iterator>
Definition at line 3694 of file Stmt.h.
const_capture_iterator
using clang::CapturedStmt::const_capture_iterator = const Capture *
Definition at line 3663 of file Stmt.h.
Member Enumeration Documentation
VariableCaptureKind
enum clang::CapturedStmt::VariableCaptureKind
The different capture forms: by 'this', by reference, capture for variable-length array type etc.
Enumerator
VCK_This
VCK_ByRef
VCK_ByCopy
VCK_VLAType
Definition at line 3536 of file Stmt.h.
Member Function Documentation
capture_begin() [1/2]
capture_iterator clang::CapturedStmt::capture_begin () inline
Retrieve an iterator pointing to the first capture.
Definition at line 3675 of file Stmt.h.
Referenced by captures(), captures(), and clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
capture_begin() [2/2]
const_capture_iterator clang::CapturedStmt::capture_begin () const inline
Definition at line 3676 of file Stmt.h.
capture_end()
capture_iterator clang::CapturedStmt::capture_end () const inline
Retrieve an iterator pointing past the end of the sequence of captures.
Definition at line 3680 of file Stmt.h.
Referenced by captures(), captures(), and clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
capture_init_begin() [1/2]
capture_init_iterator clang::CapturedStmt::capture_init_begin () inline
Retrieve the first initialization argument.
Definition at line 3706 of file Stmt.h.
Referenced by capture_init_end(), capture_init_end(), capture_inits(), and capture_inits().
capture_init_begin() [2/2]
const_capture_init_iterator clang::CapturedStmt::capture_init_begin () const inline
Definition at line 3710 of file Stmt.h.
capture_init_end() [1/2]
capture_init_iterator clang::CapturedStmt::capture_init_end () inline
Retrieve the iterator pointing one past the last initialization argument.
Definition at line 3716 of file Stmt.h.
References capture_init_begin().
Referenced by capture_inits(), and capture_inits().
capture_init_end() [2/2]
const_capture_init_iterator clang::CapturedStmt::capture_init_end () const inline
Definition at line 3720 of file Stmt.h.
References capture_init_begin().
capture_inits() [1/2]
capture_init_range clang::CapturedStmt::capture_inits () inline
Definition at line 3697 of file Stmt.h.
References capture_init_begin(), and capture_init_end().
capture_inits() [2/2]
const_capture_init_range clang::CapturedStmt::capture_inits () const inline
Definition at line 3701 of file Stmt.h.
References capture_init_begin(), and capture_init_end().
capture_size()
unsigned clang::CapturedStmt::capture_size () const inline
Retrieve the number of captures, including 'this'.
Definition at line 3685 of file Stmt.h.
captures() [1/2]
capture_range clang::CapturedStmt::captures () inline
Definition at line 3667 of file Stmt.h.
References capture_begin(), and capture_end().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), capturesVariable(), and emitOutlinedFunctionPrologue().
captures() [2/2]
capture_const_range clang::CapturedStmt::captures () const inline
Definition at line 3670 of file Stmt.h.
References capture_begin(), and capture_end().
capturesVariable()
bool CapturedStmt::capturesVariable (const VarDecl * Var) const
True if this variable has been captured.
Definition at line 1423 of file Stmt.cpp.
References captures(), and clang::VarDecl::getCanonicalDecl().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), and clang::CapturedStmt::Capture::getCapturedVar().
children() [1/2]
Stmt::child_range CapturedStmt::children ()
Definition at line 1390 of file Stmt.cpp.
Referenced by isSupportedByOpenMPIRBuilder().
children() [2/2]
Stmt::const_child_range CapturedStmt::children () const
Definition at line 1395 of file Stmt.cpp.
classof()
static bool clang::CapturedStmt::classof (const Stmt * T) inline static
Definition at line 3736 of file Stmt.h.
Create()
CapturedStmt * CapturedStmt::Create (const ASTContext & Context, Stmt * S, CapturedRegionKind Kind, ArrayRef< Capture > Captures, ArrayRef< Expr * > CaptureInits, CapturedDecl * CD, RecordDecl * RD) static
Definition at line 1349 of file Stmt.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::Sema::ActOnCapturedRegionEnd().
CreateDeserialized()
CapturedStmt * CapturedStmt::CreateDeserialized (const ASTContext & Context, unsigned NumCaptures) static
Definition at line 1377 of file Stmt.cpp.
References clang::ASTContext::Allocate().
getBeginLoc()
SourceLocation clang::CapturedStmt::getBeginLoc () const inline
Definition at line 3724 of file Stmt.h.
References clang::Stmt::getBeginLoc(), and getCapturedStmt().
Referenced by emitOutlinedFunctionPrologue().
getCapturedDecl() [1/2]
CapturedDecl * CapturedStmt::getCapturedDecl ()
Retrieve the outlined function declaration.
Definition at line 1399 of file Stmt.cpp.
Referenced by clang::Sema::ActOnOpenMPDistributeParallelForDirective(), clang::Sema::ActOnOpenMPDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPDistributeSimdDirective(), clang::Sema::ActOnOpenMPGenericLoopDirective(), clang::Sema::ActOnOpenMPParallelDirective(), clang::Sema::ActOnOpenMPParallelForDirective(), clang::Sema::ActOnOpenMPParallelForSimdDirective(), clang::Sema::ActOnOpenMPParallelGenericLoopDirective(), clang::Sema::ActOnOpenMPParallelMaskedDirective(), clang::Sema::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPParallelMasterDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPTargetDirective(), clang::Sema::ActOnOpenMPTargetEnterDataDirective(), clang::Sema::ActOnOpenMPTargetExitDataDirective(), clang::Sema::ActOnOpenMPTargetParallelDirective(), clang::Sema::ActOnOpenMPTargetParallelForDirective(), clang::Sema::ActOnOpenMPTargetParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::Sema::ActOnOpenMPTargetSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::Sema::ActOnOpenMPTargetUpdateDirective(), clang::Sema::ActOnOpenMPTaskDirective(), clang::Sema::ActOnOpenMPTeamsDirective(), clang::Sema::ActOnOpenMPTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTeamsGenericLoopDirective(), emitCommonOMPParallelDirective(), emitCommonOMPTeamsDirective(), and emitOutlinedFunctionPrologue().
getCapturedDecl() [2/2]
const CapturedDecl * CapturedStmt::getCapturedDecl () const
Definition at line 1403 of file Stmt.cpp.
getCapturedRecordDecl()
const RecordDecl * clang::CapturedStmt::getCapturedRecordDecl () const inline
Retrieve the record declaration for captured variables.
Definition at line 3650 of file Stmt.h.
Referenced by emitOutlinedFunctionPrologue(), and clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
getCapturedRegionKind()
CapturedRegionKind CapturedStmt::getCapturedRegionKind () const
Retrieve the captured region kind.
Definition at line 1414 of file Stmt.cpp.
getCapturedStmt() [1/2]
Stmt * clang::CapturedStmt::getCapturedStmt () inline
Retrieve the statement being captured.
Definition at line 3633 of file Stmt.h.
Referenced by clang::Sema::ActOnCapturedRegionEnd(), clang::Sema::ActOnOpenMPDistributeParallelForDirective(), clang::Sema::ActOnOpenMPDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPDistributeSimdDirective(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPParallelGenericLoopDirective(), clang::Sema::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPParallelSectionsDirective(), clang::Sema::ActOnOpenMPSectionsDirective(), clang::Sema::ActOnOpenMPTargetDirective(), clang::Sema::ActOnOpenMPTargetEnterDataDirective(), clang::Sema::ActOnOpenMPTargetExitDataDirective(), clang::Sema::ActOnOpenMPTargetParallelDirective(), clang::Sema::ActOnOpenMPTargetParallelForDirective(), clang::Sema::ActOnOpenMPTargetParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::Sema::ActOnOpenMPTargetSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::Sema::ActOnOpenMPTargetUpdateDirective(), clang::Sema::ActOnOpenMPTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTeamsGenericLoopDirective(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsForTargetDirective(), emitTargetParallelRegion(), emitTargetTeamsRegion(), getBeginLoc(), getEndLoc(), getNestedDistributeDirective(), clang::CodeGen::CGOpenMPRuntime::getNumTeamsExprForTargetDirective(), getNumThreads(), and getSourceRange().
getCapturedStmt() [2/2]
const Stmt * clang::CapturedStmt::getCapturedStmt () const inline
Definition at line 3634 of file Stmt.h.
getEndLoc()
SourceLocation clang::CapturedStmt::getEndLoc () const inline
Definition at line 3728 of file Stmt.h.
References getCapturedStmt(), and clang::Stmt::getEndLoc().
getSourceRange()
SourceRange clang::CapturedStmt::getSourceRange () const inline
Definition at line 3732 of file Stmt.h.
References getCapturedStmt(), and clang::Stmt::getSourceRange().
setCapturedDecl()
void CapturedStmt::setCapturedDecl (CapturedDecl * D)
Set the outlined function declaration.
Definition at line 1408 of file Stmt.cpp.
setCapturedRecordDecl()
void clang::CapturedStmt::setCapturedRecordDecl (RecordDecl * D) inline
Set the record declaration for captured variables.
Definition at line 3653 of file Stmt.h.
setCapturedRegionKind()
void CapturedStmt::setCapturedRegionKind (CapturedRegionKind Kind)
Set the captured region kind.
Definition at line 1419 of file Stmt.cpp.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 3621 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp