clang: clang::tooling::RecursiveSymbolVisitor< T > Class Template Reference
clang::tooling::RecursiveSymbolVisitor< T > Class Template Reference
Traverses the AST and visits the occurrence of each named symbol in the given nodes.
#include "clang/Tooling/Refactoring/RecursiveSymbolVisitor.h"
Public Member Functions
RecursiveSymbolVisitor (const SourceManager &SM, const LangOptions &LangOpts)
bool visitSymbolOccurrence (const NamedDecl *ND, ArrayRef< SourceRange > NameRanges)
bool VisitNamedDecl (const NamedDecl *D)
bool VisitCXXConstructorDecl (const CXXConstructorDecl *CD)
bool VisitDeclRefExpr (const DeclRefExpr *Expr)
bool VisitMemberExpr (const MemberExpr *Expr)
bool VisitOffsetOfExpr (const OffsetOfExpr *S)
bool VisitTypeLoc (const TypeLoc Loc)
bool VisitTypedefTypeLoc (TypedefTypeLoc TL)
bool TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
bool VisitDesignatedInitExpr (const DesignatedInitExpr *E)
Public Member Functions inherited from clang::RecursiveASTVisitor< RecursiveSymbolVisitor< T > >
RecursiveSymbolVisitor< T > & getDerived ()
Return a reference to the derived class.
bool shouldVisitTemplateInstantiations () const
Return whether this visitor should recurse into template instantiations.
bool shouldWalkTypesOfTypeLocs () const
Return whether this visitor should recurse into the types of TypeLocs.
bool shouldVisitImplicitCode () const
Return whether this visitor should recurse into implicit code, e.g., implicit constructors and destructors.
bool shouldVisitLambdaBody () const
Return whether this visitor should recurse into lambda body.
bool shouldTraversePostOrder () const
Return whether this visitor should traverse post-order.
bool TraverseAST (ASTContext &AST)
Recursively visits an entire AST, starting from the TranslationUnitDecl.
bool TraverseStmt (Stmt *S, DataRecursionQueue *Queue=nullptr)
Recursively visit a statement or expression, by dispatching to Traverse*() based on the argument's dynamic type.
bool dataTraverseStmtPre (Stmt *S)
Invoked before visiting a statement or expression via data recursion.
bool dataTraverseStmtPost (Stmt *S)
Invoked after visiting a statement or expression via data recursion.
bool TraverseType (QualType T)
Recursively visit a type, by dispatching to Traverse*Type() based on the argument's getTypeClass() property.
bool TraverseTypeLoc (TypeLoc TL)
Recursively visit a type with location, by dispatching to Traverse*TypeLoc() based on the argument type's getTypeClass() property.
bool TraverseAttr (Attr *At)
Recursively visit an attribute, by dispatching to Traverse*Attr() based on the argument's dynamic type.
bool TraverseDecl (Decl *D)
Recursively visit a declaration, by dispatching to Traverse*Decl() based on the argument's dynamic type.
bool TraverseNestedNameSpecifier (NestedNameSpecifier *NNS)
Recursively visit a C++ nested-name-specifier.
bool TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Recursively visit a C++ nested-name-specifier with location information.
bool TraverseDeclarationNameInfo (DeclarationNameInfo NameInfo)
Recursively visit a name with its location information.
bool TraverseTemplateName (TemplateName Template)
Recursively visit a template name and dispatch to the appropriate method.
bool TraverseTemplateArgument (const TemplateArgument &Arg)
Recursively visit a template argument and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArgumentLoc (const TemplateArgumentLoc &ArgLoc)
Recursively visit a template argument location and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArguments (const TemplateArgument *Args, unsigned NumArgs)
Recursively visit a set of template arguments.
bool TraverseCXXBaseSpecifier (const CXXBaseSpecifier &Base)
Recursively visit a base specifier.
bool TraverseConstructorInitializer (CXXCtorInitializer *Init)
Recursively visit a constructor initializer.
bool TraverseLambdaCapture (LambdaExpr *LE, const LambdaCapture *C, Expr *Init)
Recursively visit a lambda capture.
bool TraverseSynOrSemInitListExpr (InitListExpr *S, DataRecursionQueue *Queue=nullptr)
Recursively visit the syntactic or semantic form of an initialization list.
bool TraverseObjCProtocolLoc (ObjCProtocolLoc ProtocolLoc)
Recursively visit an Objective-C protocol reference with location information.
bool VisitAttr (Attr *A)
Stmt::child_range getStmtChildren (Stmt *S)
bool WalkUpFromStmt (Stmt *S)
bool VisitStmt (Stmt *S)
bool WalkUpFromType (Type *T)
bool VisitType (Type *T)
bool WalkUpFromTypeLoc (TypeLoc TL)
bool VisitTypeLoc (TypeLoc TL)
bool WalkUpFromQualifiedTypeLoc (QualifiedTypeLoc TL)
bool VisitQualifiedTypeLoc (QualifiedTypeLoc TL)
bool WalkUpFromUnqualTypeLoc (UnqualTypeLoc TL)
bool VisitUnqualTypeLoc (UnqualTypeLoc TL)
bool WalkUpFromDecl (Decl *D)
bool VisitDecl (Decl *D)
bool canIgnoreChildDeclWhileTraversingDeclContext (const Decl *Child)
bool TraverseTypeConstraint (const TypeConstraint *C)
bool TraverseConceptRequirement (concepts::Requirement *R)
bool TraverseConceptTypeRequirement (concepts::TypeRequirement *R)
bool TraverseConceptExprRequirement (concepts::ExprRequirement *R)
bool TraverseConceptNestedRequirement (concepts::NestedRequirement *R)
bool dataTraverseNode (Stmt *S, DataRecursionQueue *Queue)
Additional Inherited Members
Public Types inherited from clang::RecursiveASTVisitor< RecursiveSymbolVisitor< T > >
typedef SmallVectorImpl< llvm::PointerIntPair< Stmt *, 1, bool > > DataRecursionQueue
A queue used for performing data recursion over statements.
Detailed Description
template<typename T>
class clang::tooling::RecursiveSymbolVisitor< T >
Traverses the AST and visits the occurrence of each named symbol in the given nodes.
Definition at line 28 of file RecursiveSymbolVisitor.h.
Constructor & Destructor Documentation
RecursiveSymbolVisitor()
template<typename T > clang::tooling::RecursiveSymbolVisitor< T >::RecursiveSymbolVisitor (const SourceManager & SM, const LangOptions & LangOpts) inline
Definition at line 33 of file RecursiveSymbolVisitor.h.
References SM.
Member Function Documentation
TraverseNestedNameSpecifierLoc()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS) inline
Definition at line 114 of file RecursiveSymbolVisitor.h.
References clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifierLoc::getLocalBeginLoc(), clang::NestedNameSpecifierLoc::getLocalEndLoc(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), and clang::RecursiveASTVisitor< RecursiveSymbolVisitor< T > >::TraverseNestedNameSpecifierLoc().
VisitCXXConstructorDecl()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitCXXConstructorDecl (const CXXConstructorDecl * CD) inline
Definition at line 47 of file RecursiveSymbolVisitor.h.
References clang::Lexer::getLocForEndOfToken(), clang::Initializer, and clang::CXXConstructorDecl::inits().
VisitDeclRefExpr()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitDeclRefExpr (const DeclRefExpr * Expr) inline
Definition at line 64 of file RecursiveSymbolVisitor.h.
VisitDesignatedInitExpr()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitDesignatedInitExpr (const DesignatedInitExpr * E) inline
Definition at line 125 of file RecursiveSymbolVisitor.h.
References clang::DesignatedInitExpr::designators().
VisitMemberExpr()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitMemberExpr (const MemberExpr * Expr) inline
Definition at line 68 of file RecursiveSymbolVisitor.h.
VisitNamedDecl()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitNamedDecl (const NamedDecl * D) inline
Definition at line 43 of file RecursiveSymbolVisitor.h.
References clang::Decl::getLocation(), clang::isa(), and true.
VisitOffsetOfExpr()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitOffsetOfExpr (const OffsetOfExpr * S) inline
Definition at line 72 of file RecursiveSymbolVisitor.h.
References clang::OffsetOfNode::Field, clang::OffsetOfNode::getEndLoc(), clang::OffsetOfNode::getField(), and clang::OffsetOfNode::getKind().
visitSymbolOccurrence()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::visitSymbolOccurrence (const NamedDecl * ND, ArrayRef< SourceRange > NameRanges) inline
Definition at line 36 of file RecursiveSymbolVisitor.h.
VisitTypedefTypeLoc()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitTypedefTypeLoc (TypedefTypeLoc TL) inline
Definition at line 108 of file RecursiveSymbolVisitor.h.
References clang::TypeLoc::getBeginLoc(), clang::Lexer::getLocForEndOfToken(), and clang::TypedefTypeLoc::getTypedefNameDecl().
VisitTypeLoc()
template<typename T > bool clang::tooling::RecursiveSymbolVisitor< T >::VisitTypeLoc (const TypeLoc Loc) inline
Definition at line 86 of file RecursiveSymbolVisitor.h.
References clang::TypeLoc::getBeginLoc(), clang::Lexer::getLocForEndOfToken(), clang::TypeLoc::getType(), and clang::TypeLoc::getTypePtr().
The documentation for this class was generated from the following file:
include/clang/Tooling/Refactoring/RecursiveSymbolVisitor.h