clang: clang::ReturnStmt Class Reference
clang::ReturnStmt Class Reference final
ReturnStmt - This represents a return, optionally of an expression: return; return 4;.
#include "clang/AST/Stmt.h"
Public Member Functions
Expr * getRetValue ()
const Expr * getRetValue () const
void setRetValue (Expr *E)
const VarDecl * getNRVOCandidate () const
Retrieve the variable that might be used for the named return value optimization.
void setNRVOCandidate (const VarDecl *Var)
Set the variable that might be used for the named return value optimization.
SourceLocation getReturnLoc () const
void setReturnLoc (SourceLocation L)
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static ReturnStmt * Create (const ASTContext &Ctx, SourceLocation RL, Expr *E, const VarDecl *NRVOCandidate)
Create a return statement.
static ReturnStmt * CreateEmpty (const ASTContext &Ctx, bool HasNRVOCandidate)
Create an empty return statement, optionally with storage for an NRVO candidate.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
ReturnStmt - This represents a return, optionally of an expression: return; return 4;.
Note that GCC allows return with no argument in a function declared to return a value, and it allows returning a value in functions declared to return void. We explicitly model this in the AST, which means you can't depend on the return type of the function and the presence of an argument.
Definition at line 2792 of file Stmt.h.
Member Function Documentation
children() [1/2]
child_range clang::ReturnStmt::children () inline
Definition at line 2861 of file Stmt.h.
children() [2/2]
const_child_range clang::ReturnStmt::children () const inline
Definition at line 2867 of file Stmt.h.
classof()
static bool clang::ReturnStmt::classof (const Stmt * T) inline static
Definition at line 2856 of file Stmt.h.
Create()
ReturnStmt * ReturnStmt::Create (const ASTContext & Ctx, SourceLocation RL, Expr * E, const VarDecl * NRVOCandidate) static
Create a return statement.
Definition at line 1201 of file Stmt.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::BuildReturnStmt(), and clang::ASTNodeImporter::VisitReturnStmt().
CreateEmpty()
ReturnStmt * ReturnStmt::CreateEmpty (const ASTContext & Ctx, bool HasNRVOCandidate) static
Create an empty return statement, optionally with storage for an NRVO candidate.
Definition at line 1209 of file Stmt.cpp.
References clang::ASTContext::Allocate().
getBeginLoc()
SourceLocation clang::ReturnStmt::getBeginLoc () const inline
Definition at line 2851 of file Stmt.h.
References getReturnLoc().
Referenced by clang::Sema::deduceClosureReturnType().
getEndLoc()
SourceLocation clang::ReturnStmt::getEndLoc () const inline
Definition at line 2852 of file Stmt.h.
References clang::Stmt::getEndLoc(), and getReturnLoc().
getNRVOCandidate()
const VarDecl * clang::ReturnStmt::getNRVOCandidate () const inline
Retrieve the variable that might be used for the named return value optimization.
The optimization itself can only be performed if the variable is also marked as an NRVO object.
Definition at line 2834 of file Stmt.h.
getReturnLoc()
SourceLocation clang::ReturnStmt::getReturnLoc () const inline
Definition at line 2848 of file Stmt.h.
References clang::Stmt::ReturnStmtBits.
Referenced by getBeginLoc(), and getEndLoc().
getRetValue() [1/2]
Expr * clang::ReturnStmt::getRetValue () inline
Definition at line 2825 of file Stmt.h.
Referenced by adjustBlockReturnsToEnum(), clang::Sema::checkAndRewriteMustTailAttr(), clang::Sema::deduceClosureReturnType(), findEnumForBlockReturn(), isIdenticalStmt(), and clang::ento::ExprEngine::VisitReturnStmt().
getRetValue() [2/2]
const Expr * clang::ReturnStmt::getRetValue () const inline
Definition at line 2826 of file Stmt.h.
setNRVOCandidate()
void clang::ReturnStmt::setNRVOCandidate (const VarDecl * Var) inline
Set the variable that might be used for the named return value optimization.
The return statement must have storage for it, which is the case if and only if hasNRVOCandidate() is true.
Definition at line 2842 of file Stmt.h.
Referenced by clang::Sema::computeNRVO().
setReturnLoc()
void clang::ReturnStmt::setReturnLoc (SourceLocation L) inline
Definition at line 2849 of file Stmt.h.
References clang::Stmt::ReturnStmtBits.
setRetValue()
void clang::ReturnStmt::setRetValue (Expr * E) inline
Definition at line 2827 of file Stmt.h.
Referenced by adjustBlockReturnsToEnum(), and clang::Sema::checkAndRewriteMustTailAttr().
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp