clang: clang::WhileStmt Class Reference
clang::WhileStmt Class Reference final
WhileStmt - This represents a 'while' stmt.
#include "clang/AST/Stmt.h"
Public Member Functions
bool hasVarStorage () const
True if this WhileStmt has storage for a condition variable.
Expr * getCond ()
const Expr * getCond () const
void setCond (Expr *Cond)
Stmt * getBody ()
const Stmt * getBody () const
void setBody (Stmt *Body)
VarDecl * getConditionVariable ()
Retrieve the variable declared in this "while" statement, if any.
const VarDecl * getConditionVariable () const
void setConditionVariable (const ASTContext &Ctx, VarDecl *V)
Set the condition variable of this while statement.
DeclStmt * getConditionVariableDeclStmt ()
If this WhileStmt has a condition variable, return the faux DeclStmt associated with the creation of that condition variable.
const DeclStmt * getConditionVariableDeclStmt () const
SourceLocation getWhileLoc () const
void setWhileLoc (SourceLocation L)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation L)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation L)
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static WhileStmt * Create (const ASTContext &Ctx, VarDecl *Var, Expr *Cond, Stmt *Body, SourceLocation WL, SourceLocation LParenLoc, SourceLocation RParenLoc)
Create a while statement.
static WhileStmt * CreateEmpty (const ASTContext &Ctx, bool HasVar)
Create an empty while statement optionally with storage for a condition variable.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
WhileStmt - This represents a 'while' stmt.
Definition at line 2373 of file Stmt.h.
Member Function Documentation
children() [1/2]
child_range clang::WhileStmt::children () inline
Definition at line 2496 of file Stmt.h.
children() [2/2]
const_child_range clang::WhileStmt::children () const inline
Definition at line 2502 of file Stmt.h.
classof()
static bool clang::WhileStmt::classof (const Stmt * T) inline static
Definition at line 2491 of file Stmt.h.
Create()
WhileStmt * WhileStmt::Create (const ASTContext & Ctx, VarDecl * Var, Expr * Cond, Stmt * Body, SourceLocation WL, SourceLocation LParenLoc, SourceLocation RParenLoc) static
Create a while statement.
Definition at line 1140 of file Stmt.cpp.
References clang::ASTContext::Allocate(), and clang::Cond.
Referenced by clang::Sema::ActOnWhileStmt(), and clang::ASTNodeImporter::VisitWhileStmt().
CreateEmpty()
WhileStmt * WhileStmt::CreateEmpty (const ASTContext & Ctx, bool HasVar) static
Create an empty while statement optionally with storage for a condition variable.
Definition at line 1151 of file Stmt.cpp.
References clang::ASTContext::Allocate().
getBeginLoc()
SourceLocation clang::WhileStmt::getBeginLoc () const inline
Definition at line 2486 of file Stmt.h.
References getWhileLoc().
getBody() [1/2]
Stmt * clang::WhileStmt::getBody () inline
Definition at line 2438 of file Stmt.h.
Referenced by EvaluateStmt(), getEndLoc(), and isIdenticalStmt().
getBody() [2/2]
const Stmt * clang::WhileStmt::getBody () const inline
Definition at line 2439 of file Stmt.h.
getCond() [1/2]
Expr * clang::WhileStmt::getCond () inline
Definition at line 2426 of file Stmt.h.
Referenced by EvaluateStmt(), and isIdenticalStmt().
getCond() [2/2]
const Expr * clang::WhileStmt::getCond () const inline
Definition at line 2430 of file Stmt.h.
getConditionVariable() [1/2]
VarDecl * WhileStmt::getConditionVariable ()
Retrieve the variable declared in this "while" statement, if any.
In the following example, "x" is the condition variable.
while (int x = random()) {
  // ...
}
Definition at line 1158 of file Stmt.cpp.
References clang::cast(), and getConditionVariableDeclStmt().
Referenced by EvaluateStmt(), and getConditionVariable().
getConditionVariable() [2/2]
const VarDecl * clang::WhileStmt::getConditionVariable () const inline
Definition at line 2456 of file Stmt.h.
References getConditionVariable().
getConditionVariableDeclStmt() [1/2]
DeclStmt * clang::WhileStmt::getConditionVariableDeclStmt () inline
If this WhileStmt has a condition variable, return the faux DeclStmt associated with the creation of that condition variable.
Definition at line 2466 of file Stmt.h.
References hasVarStorage().
Referenced by getConditionVariable().
getConditionVariableDeclStmt() [2/2]
const DeclStmt * clang::WhileStmt::getConditionVariableDeclStmt () const inline
Definition at line 2472 of file Stmt.h.
References hasVarStorage().
getEndLoc()
SourceLocation clang::WhileStmt::getEndLoc () const inline
Definition at line 2487 of file Stmt.h.
References getBody(), and clang::Stmt::getEndLoc().
getLParenLoc()
SourceLocation clang::WhileStmt::getLParenLoc () const inline
Definition at line 2481 of file Stmt.h.
getRParenLoc()
SourceLocation clang::WhileStmt::getRParenLoc () const inline
Definition at line 2483 of file Stmt.h.
getWhileLoc()
SourceLocation clang::WhileStmt::getWhileLoc () const inline
Definition at line 2478 of file Stmt.h.
References clang::Stmt::WhileStmtBits.
Referenced by getBeginLoc().
hasVarStorage()
bool clang::WhileStmt::hasVarStorage () const inline
True if this WhileStmt has storage for a condition variable.
Definition at line 2424 of file Stmt.h.
References clang::Stmt::WhileStmtBits.
Referenced by getConditionVariableDeclStmt(), getConditionVariableDeclStmt(), setConditionVariable(), and clang::JSONNodeDumper::VisitWhileStmt().
setBody()
void clang::WhileStmt::setBody (Stmt * Body) inline
Definition at line 2443 of file Stmt.h.
setCond()
void clang::WhileStmt::setCond (Expr * Cond) inline
Definition at line 2434 of file Stmt.h.
References clang::Cond.
setConditionVariable()
void WhileStmt::setConditionVariable (const ASTContext & Ctx, VarDecl * V)
Set the condition variable of this while statement.
The while statement must have storage for it.
Definition at line 1165 of file Stmt.cpp.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), hasVarStorage(), and V.
setLParenLoc()
void clang::WhileStmt::setLParenLoc (SourceLocation L) inline
Definition at line 2482 of file Stmt.h.
setRParenLoc()
void clang::WhileStmt::setRParenLoc (SourceLocation L) inline
Definition at line 2484 of file Stmt.h.
setWhileLoc()
void clang::WhileStmt::setWhileLoc (SourceLocation L) inline
Definition at line 2479 of file Stmt.h.
References clang::Stmt::WhileStmtBits.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp