clang: clang::ento::DynamicCastInfo Class Reference
clang::ento::DynamicCastInfo Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicCastInfo.h"
Public Types
enum CastResult { Success , Failure }
Public Member Functions
DynamicCastInfo (QualType from, QualType to, CastResult resultKind)
QualType from () const
QualType to () const
bool equals (QualType from, QualType to) const
bool succeeds () const
bool fails () const
bool operator== (const DynamicCastInfo &RHS) const
bool operator< (const DynamicCastInfo &RHS) const
void Profile (llvm::FoldingSetNodeID &ID) const
Detailed Description
Definition at line 17 of file DynamicCastInfo.h.
Member Enumeration Documentation
CastResult
enum clang::ento::DynamicCastInfo::CastResult
Enumerator
Success
Failure
Definition at line 19 of file DynamicCastInfo.h.
Constructor & Destructor Documentation
DynamicCastInfo()
clang::ento::DynamicCastInfo::DynamicCastInfo (QualType from, QualType to, CastResult resultKind) inline
Definition at line 21 of file DynamicCastInfo.h.
Member Function Documentation
equals()
bool clang::ento::DynamicCastInfo::equals (QualType from, QualType to) const inline
Definition at line 27 of file DynamicCastInfo.h.
References from(), and to().
fails()
bool clang::ento::DynamicCastInfo::fails () const inline
Definition at line 32 of file DynamicCastInfo.h.
References Failure.
Referenced by isInfeasibleCast().
from()
QualType clang::ento::DynamicCastInfo::from () const inline
Definition at line 24 of file DynamicCastInfo.h.
Referenced by equals().
operator<()
bool clang::ento::DynamicCastInfo::operator< (const DynamicCastInfo & RHS) const inline
Definition at line 37 of file DynamicCastInfo.h.
operator==()
bool clang::ento::DynamicCastInfo::operator== (const DynamicCastInfo & RHS) const inline
Definition at line 34 of file DynamicCastInfo.h.
Profile()
void clang::ento::DynamicCastInfo::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 41 of file DynamicCastInfo.h.
succeeds()
bool clang::ento::DynamicCastInfo::succeeds () const inline
Definition at line 31 of file DynamicCastInfo.h.
References Success.
Referenced by addCastTransition(), addInstanceOfTransition(), and isInfeasibleCast().
to()
QualType clang::ento::DynamicCastInfo::to () const inline
Definition at line 25 of file DynamicCastInfo.h.
Referenced by equals(), and getNoteTag().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/DynamicCastInfo.h