clang: clang::ASTStmtReader Class Reference
clang::ASTStmtReader Class Reference
Public Member Functions
ASTStmtReader (ASTRecordReader &Record, llvm::BitstreamCursor &Cursor)
void ReadTemplateKWAndArgsInfo (ASTTemplateKWAndArgsInfo &Args, TemplateArgumentLoc *ArgsLocArray, unsigned NumTemplateArgs)
Read and initialize a ExplicitTemplateArgumentList structure.
void ReadExplicitTemplateArgumentList (ASTTemplateArgumentListInfo &ArgList, unsigned NumTemplateArgs)
Read and initialize a ExplicitTemplateArgumentList structure.
void VisitStmt (Stmt *S)
Public Member Functions inherited from clang::StmtVisitorBase< std::add_pointer, ASTStmtReader, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Static Public Attributes
static const unsigned NumStmtFields = 0
The number of record fields required for the Stmt class itself.
static const unsigned NumExprFields = NumStmtFields + 4
The number of record fields required for the Expr class itself.
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< std::add_pointer, ASTStmtReader, void, ParamTys... >
ParamTys P
Detailed Description
Definition at line 71 of file ASTReaderStmt.cpp.
Constructor & Destructor Documentation
ASTStmtReader()
clang::ASTStmtReader::ASTStmtReader (ASTRecordReader & Record, llvm::BitstreamCursor & Cursor) inline
Definition at line 101 of file ASTReaderStmt.cpp.
Member Function Documentation
ReadExplicitTemplateArgumentList()
void clang::ASTStmtReader::ReadExplicitTemplateArgumentList (ASTTemplateArgumentListInfo & ArgList, unsigned NumTemplateArgs)
Read and initialize a ExplicitTemplateArgumentList structure.
ReadTemplateKWAndArgsInfo()
void ASTStmtReader::ReadTemplateKWAndArgsInfo (ASTTemplateKWAndArgsInfo & Args, TemplateArgumentLoc * ArgsLocArray, unsigned NumTemplateArgs)
Read and initialize a ExplicitTemplateArgumentList structure.
Definition at line 129 of file ASTReaderStmt.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::ASTTemplateKWAndArgsInfo::initializeFrom(), clang::ASTRecordReader::readTemplateArgumentLoc(), clang::TemplateArgumentListInfo::setLAngleLoc(), and clang::TemplateArgumentListInfo::setRAngleLoc().
VisitStmt()
void ASTStmtReader::VisitStmt (Stmt * S)
Definition at line 141 of file ASTReaderStmt.cpp.
References clang::ASTRecordReader::getIdx(), and NumStmtFields.
Member Data Documentation
NumExprFields
const unsigned clang::ASTStmtReader::NumExprFields = NumStmtFields + 4 static
The number of record fields required for the Expr class itself.
Definition at line 110 of file ASTReaderStmt.cpp.
NumStmtFields
const unsigned clang::ASTStmtReader::NumStmtFields = 0 static
The number of record fields required for the Stmt class itself.
Definition at line 106 of file ASTReaderStmt.cpp.
Referenced by VisitStmt().
The documentation for this class was generated from the following file:
lib/Serialization/ASTReaderStmt.cpp