clang: clang::LabelStmt Class Reference
clang::LabelStmt Class Reference
LabelStmt - Represents a label, which has a substatement.
#include "clang/AST/Stmt.h"
Public Member Functions
LabelStmt (SourceLocation IL, LabelDecl *D, Stmt *substmt)
Build a label statement.
LabelStmt (EmptyShell Empty)
Build an empty label statement.
SourceLocation getIdentLoc () const
void setIdentLoc (SourceLocation L)
LabelDecl * getDecl () const
void setDecl (LabelDecl *D)
const char * getName () const
Stmt * getSubStmt ()
const Stmt * getSubStmt () const
void setSubStmt (Stmt *SS)
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
bool isSideEntry () const
void setSideEntry (bool SE)
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
LabelStmt - Represents a label, which has a substatement.
For example: foo: return;
Definition at line 1831 of file Stmt.h.
Constructor & Destructor Documentation
LabelStmt() [1/2]
clang::LabelStmt::LabelStmt (SourceLocation IL, LabelDecl * D, Stmt * substmt) inline
Build a label statement.
Definition at line 1838 of file Stmt.h.
References setIdentLoc().
LabelStmt() [2/2]
clang::LabelStmt::LabelStmt (EmptyShell Empty) inline explicit
Build an empty label statement.
Definition at line 1844 of file Stmt.h.
Member Function Documentation
children() [1/2]
child_range clang::LabelStmt::children () inline
Definition at line 1861 of file Stmt.h.
children() [2/2]
const_child_range clang::LabelStmt::children () const inline
Definition at line 1863 of file Stmt.h.
classof()
static bool clang::LabelStmt::classof (const Stmt * T) inline static
Definition at line 1867 of file Stmt.h.
getBeginLoc()
SourceLocation clang::LabelStmt::getBeginLoc () const inline
Definition at line 1858 of file Stmt.h.
References getIdentLoc().
Referenced by DiagnoseSwitchLabelsFallthrough().
getDecl()
LabelDecl * clang::LabelStmt::getDecl () const inline
Definition at line 1849 of file Stmt.h.
Referenced by getName(), and clang::JSONNodeDumper::VisitLabelStmt().
getEndLoc()
SourceLocation clang::LabelStmt::getEndLoc () const inline
Definition at line 1859 of file Stmt.h.
References clang::Stmt::getEndLoc().
getIdentLoc()
SourceLocation clang::LabelStmt::getIdentLoc () const inline
Definition at line 1846 of file Stmt.h.
References clang::Stmt::LabelStmtBits.
Referenced by getBeginLoc().
getName()
const char * LabelStmt::getName () const
Definition at line 419 of file Stmt.cpp.
References getDecl(), clang::NamedDecl::getIdentifier(), and clang::IdentifierInfo::getNameStart().
Referenced by print_block(), and clang::JSONNodeDumper::VisitLabelStmt().
getSubStmt() [1/2]
Stmt * clang::LabelStmt::getSubStmt () inline
Definition at line 1853 of file Stmt.h.
getSubStmt() [2/2]
const Stmt * clang::LabelStmt::getSubStmt () const inline
Definition at line 1855 of file Stmt.h.
isSideEntry()
bool clang::LabelStmt::isSideEntry () const inline
Definition at line 1870 of file Stmt.h.
Referenced by clang::JSONNodeDumper::VisitLabelStmt().
setDecl()
void clang::LabelStmt::setDecl (LabelDecl * D) inline
Definition at line 1850 of file Stmt.h.
setIdentLoc()
void clang::LabelStmt::setIdentLoc (SourceLocation L) inline
Definition at line 1847 of file Stmt.h.
References clang::Stmt::LabelStmtBits.
Referenced by LabelStmt().
setSideEntry()
void clang::LabelStmt::setSideEntry (bool SE) inline
Definition at line 1871 of file Stmt.h.
setSubStmt()
void clang::LabelStmt::setSubStmt (Stmt * SS) inline
Definition at line 1856 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp