clang: clang::ClassTemplateDecl Class Reference
clang::ClassTemplateDecl Class Reference
Declaration of a class template.
#include "clang/AST/DeclTemplate.h"
Classes
struct Common
Data that is common to all of the declarations of a given class template.
Public Types
using spec_iterator = SpecIterator<ClassTemplateSpecializationDecl>
using spec_range = llvm::iterator_range<spec_iterator>
Public Types inherited from clang::RedeclarableTemplateDecl
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Types inherited from clang::Redeclarable< RedeclarableTemplateDecl >
using redecl_range
Public Member Functions
void LoadLazySpecializations () const
Load any lazily-loaded specializations from the external source.
CXXRecordDecl * getTemplatedDecl () const
Get the underlying class declarations of the template.
bool isThisDeclarationADefinition () const
Returns whether this template declaration defines the primary class pattern.
ClassTemplateSpecializationDecl * findSpecialization (ArrayRef< TemplateArgument > Args, void *&InsertPos)
Return the specialization with the provided arguments if it exists, otherwise return the insertion point.
void AddSpecialization (ClassTemplateSpecializationDecl *D, void *InsertPos)
Insert the specified specialization knowing that it is not already in.
ClassTemplateDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const ClassTemplateDecl * getCanonicalDecl () const
ClassTemplateDecl * getPreviousDecl ()
Retrieve the previous declaration of this class template, or nullptr if no such declaration exists.
const ClassTemplateDecl * getPreviousDecl () const
ClassTemplateDecl * getMostRecentDecl ()
const ClassTemplateDecl * getMostRecentDecl () const
ClassTemplateDecl * getInstantiatedFromMemberTemplate () const
ClassTemplatePartialSpecializationDecl * findPartialSpecialization (ArrayRef< TemplateArgument > Args, TemplateParameterList *TPL, void *&InsertPos)
Return the partial specialization with the provided arguments if it exists, otherwise return the insertion point.
void AddPartialSpecialization (ClassTemplatePartialSpecializationDecl *D, void *InsertPos)
Insert the specified partial specialization knowing that it is not already in.
void getPartialSpecializations (SmallVectorImpl< ClassTemplatePartialSpecializationDecl * > &PS) const
Retrieve the partial specializations as an ordered list.
ClassTemplatePartialSpecializationDecl * findPartialSpecialization (QualType T)
Find a class template partial specialization with the given type T.
ClassTemplatePartialSpecializationDecl * findPartialSpecInstantiatedFromMember (ClassTemplatePartialSpecializationDecl *D)
Find a class template partial specialization which was instantiated from the given member partial specialization.
QualType getInjectedClassNameSpecialization ()
Retrieve the template specialization type of the injected-class-name for this class template.
spec_range specializations () const
spec_iterator spec_begin () const
spec_iterator spec_end () const
Public Member Functions inherited from clang::RedeclarableTemplateDecl
RedeclarableTemplateDecl * getCanonicalDecl () override
Retrieves the canonical declaration of this template.
const RedeclarableTemplateDecl * getCanonicalDecl () const
bool isMemberSpecialization () const
Determines whether this template was a specialization of a member template.
void setMemberSpecialization ()
Note that this member template is a specialization.
RedeclarableTemplateDecl * getInstantiatedFromMemberTemplate () const
Retrieve the member template from which this template was instantiated, or nullptr if this template was not instantiated from a member template.
void setInstantiatedFromMemberTemplate (RedeclarableTemplateDecl *TD)
Public Member Functions inherited from clang::TemplateDecl
TemplateParameterList * getTemplateParameters () const
Get the list of template parameters.
void getAssociatedConstraints (llvm::SmallVectorImpl< const Expr * > &AC) const
Get the total constraint-expression associated with this template, including constraint-expressions derived from the requires-clause, trailing requires-clause (for functions and methods) and constrained template parameters.
bool hasAssociatedConstraints () const
NamedDecl * getTemplatedDecl () const
Get the underlying, templated declaration.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
void init (NamedDecl *templatedDecl, TemplateParameterList *templateParams)
Initialize the underlying templated declaration and template parameters.
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &os) const
Pretty-print the unqualified name of this declaration.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getQualifiedNameAsString () const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
Optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isDiscardedInGlobalModuleFragment () const
FIXME: Implement discarding declarations actually in global module fragment.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl ()
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
Public Member Functions inherited from clang::Redeclarable< RedeclarableTemplateDecl >
Redeclarable (const ASTContext &Ctx)
RedeclarableTemplateDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const RedeclarableTemplateDecl * getPreviousDecl () const
RedeclarableTemplateDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const RedeclarableTemplateDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
RedeclarableTemplateDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const RedeclarableTemplateDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (RedeclarableTemplateDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static ClassTemplateDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation L, DeclarationName Name, TemplateParameterList *Params, NamedDecl *Decl)
Create a class template node.
static ClassTemplateDecl * CreateDeserialized (ASTContext &C, unsigned ID)
Create an empty class template node.
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::RedeclarableTemplateDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::TemplateDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Protected Member Functions
llvm::FoldingSetVector< ClassTemplateSpecializationDecl > & getSpecializations () const
Retrieve the set of specializations of this class template.
llvm::FoldingSetVector< ClassTemplatePartialSpecializationDecl > & getPartialSpecializations () const
Retrieve the set of partial specializations of this class template.
ClassTemplateDecl (ASTContext &C, DeclContext *DC, SourceLocation L, DeclarationName Name, TemplateParameterList *Params, NamedDecl *Decl)
CommonBase * newCommon (ASTContext &C) const override
Common * getCommonPtr () const
Protected Member Functions inherited from clang::RedeclarableTemplateDecl
void loadLazySpecializationsImpl () const
template<class EntryType , typename ... ProfileArguments>
SpecEntryTraits< EntryType >::DeclType * findSpecializationImpl (llvm::FoldingSetVector< EntryType > &Specs, void *&InsertPos, ProfileArguments &&...ProfileArgs)
template<class Derived , class EntryType >
void addSpecializationImpl (llvm::FoldingSetVector< EntryType > &Specs, EntryType *Entry, void *InsertPos)
CommonBase * getCommonPtr () const
Retrieves the "common" pointer shared by all (re-)declarations of the same template.
RedeclarableTemplateDecl (Kind DK, ASTContext &C, DeclContext *DC, SourceLocation L, DeclarationName Name, TemplateParameterList *Params, NamedDecl *Decl)
Protected Member Functions inherited from clang::TemplateDecl
TemplateDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName Name, TemplateParameterList *Params, NamedDecl *Decl)
TemplateDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName Name, TemplateParameterList *Params)
void setTemplateParameters (TemplateParameterList *TParams)
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::Redeclarable< RedeclarableTemplateDecl >
RedeclarableTemplateDecl * getNextRedeclaration () const
Friends
class ASTDeclReader
class ASTDeclWriter
Additional Inherited Members
Static Protected Member Functions inherited from clang::RedeclarableTemplateDecl
template<typename EntryType >
static SpecIterator< EntryType > makeSpecIterator (llvm::FoldingSetVector< EntryType > &Specs, bool isEnd)
Static Protected Member Functions inherited from clang::Redeclarable< RedeclarableTemplateDecl >
static DeclLink PreviousDeclLink (RedeclarableTemplateDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::RedeclarableTemplateDecl
CommonBase * Common = nullptr
Pointer to the common data shared by all declarations of this template.
Protected Attributes inherited from clang::TemplateDecl
NamedDecl * TemplatedDecl
TemplateParameterList * TemplateParams
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::Redeclarable< RedeclarableTemplateDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
RedeclarableTemplateDecl * First
Detailed Description
Declaration of a class template.
Definition at line 2273 of file DeclTemplate.h.
Member Typedef Documentation
spec_iterator
using clang::ClassTemplateDecl::spec_iterator = SpecIterator<ClassTemplateSpecializationDecl>
Definition at line 2437 of file DeclTemplate.h.
spec_range
using clang::ClassTemplateDecl::spec_range = llvm::iterator_range<spec_iterator>
Definition at line 2438 of file DeclTemplate.h.
Constructor & Destructor Documentation
ClassTemplateDecl()
clang::ClassTemplateDecl::ClassTemplateDecl (ASTContext & C, DeclContext * DC, SourceLocation L, DeclarationName Name, TemplateParameterList * Params, NamedDecl * Decl) inline protected
Definition at line 2302 of file DeclTemplate.h.
Referenced by Create(), and CreateDeserialized().
Member Function Documentation
AddPartialSpecialization()
void ClassTemplateDecl::AddPartialSpecialization (ClassTemplatePartialSpecializationDecl * D, void * InsertPos)
Insert the specified partial specialization knowing that it is not already in.
InsertPos must be obtained from findPartialSpecialization.
Definition at line 550 of file DeclTemplate.cpp.
References clang::Decl::getASTMutationListener(), getPartialSpecializations(), and clang::Decl::isCanonicalDecl().
Referenced by clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), and clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
AddSpecialization()
void ClassTemplateDecl::AddSpecialization (ClassTemplateSpecializationDecl * D, void * InsertPos)
Insert the specified specialization knowing that it is not already in.
InsertPos must be obtained from findSpecialization.
Definition at line 497 of file DeclTemplate.cpp.
References clang::RedeclarableTemplateDecl::addSpecializationImpl(), and getSpecializations().
Referenced by clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
classof()
static bool clang::ClassTemplateDecl::classof (const Decl * D) inline static
Definition at line 2453 of file DeclTemplate.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::ClassTemplateDecl::classofKind (Kind K) inline static
Definition at line 2454 of file DeclTemplate.h.
Referenced by classof().
Create()
ClassTemplateDecl * ClassTemplateDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation L, DeclarationName Name, TemplateParameterList * Params, NamedDecl * Decl) static
Create a class template node.
Definition at line 450 of file DeclTemplate.cpp.
References AdoptTemplateParameterList(), clang::C, ClassTemplateDecl(), and clang::Invalid.
Referenced by clang::Sema::CheckClassTemplate().
CreateDeserialized()
ClassTemplateDecl * ClassTemplateDecl::CreateDeserialized (ASTContext & C, unsigned ID) static
Create an empty class template node.
Definition at line 462 of file DeclTemplate.cpp.
References clang::C, and ClassTemplateDecl().
findPartialSpecialization() [1/2]
ClassTemplatePartialSpecializationDecl * ClassTemplateDecl::findPartialSpecialization (ArrayRef< TemplateArgument > Args, TemplateParameterList * TPL, void *& InsertPos)
Return the partial specialization with the provided arguments if it exists, otherwise return the insertion point.
Definition at line 503 of file DeclTemplate.cpp.
References clang::RedeclarableTemplateDecl::findSpecializationImpl(), and getPartialSpecializations().
Referenced by clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), and clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
findPartialSpecialization() [2/2]
ClassTemplatePartialSpecializationDecl * ClassTemplateDecl::findPartialSpecialization (QualType T)
Find a class template partial specialization with the given type T.
Parameters
T a dependent type that names a specialization of this class template.
Returns
the class template partial specialization that exactly matches the type T, or nullptr if no such partial specialization exists.
Definition at line 577 of file DeclTemplate.cpp.
References clang::Decl::getASTContext(), getPartialSpecializations(), clang::ASTContext::hasSameType(), and P.
findPartialSpecInstantiatedFromMember()
ClassTemplatePartialSpecializationDecl * ClassTemplateDecl::findPartialSpecInstantiatedFromMember (ClassTemplatePartialSpecializationDecl * D)
Find a class template partial specialization which was instantiated from the given member partial specialization.
Parameters
D a member class template partial specialization.
Returns
the class template partial specialization which was instantiated from the given member partial specialization, or nullptr if no such partial specialization exists.
Definition at line 589 of file DeclTemplate.cpp.
References clang::CXXRecordDecl::getCanonicalDecl(), getPartialSpecializations(), and P.
findSpecialization()
ClassTemplateSpecializationDecl * ClassTemplateDecl::findSpecialization (ArrayRef< TemplateArgument > Args, void *& InsertPos)
Return the specialization with the provided arguments if it exists, otherwise return the insertion point.
Definition at line 492 of file DeclTemplate.cpp.
References clang::RedeclarableTemplateDecl::findSpecializationImpl(), and getSpecializations().
Referenced by clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
getCanonicalDecl() [1/2]
const ClassTemplateDecl * clang::ClassTemplateDecl::getCanonicalDecl () const inline
Definition at line 2354 of file DeclTemplate.h.
References clang::cast(), and clang::RedeclarableTemplateDecl::getCanonicalDecl().
getCanonicalDecl() [2/2]
ClassTemplateDecl * clang::ClassTemplateDecl::getCanonicalDecl () inline override virtual
Retrieves the "canonical" declaration of the given declaration.
Reimplemented from clang::Decl.
Definition at line 2350 of file DeclTemplate.h.
References clang::cast(), and clang::RedeclarableTemplateDecl::getCanonicalDecl().
Referenced by isInstantiationOf(), clang::Sema::isStdInitializerList(), MatchesFriend(), and clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl().
getCommonPtr()
Common * clang::ClassTemplateDecl::getCommonPtr () const inline protected
Definition at line 2309 of file DeclTemplate.h.
References clang::RedeclarableTemplateDecl::getCommonPtr().
Referenced by getInjectedClassNameSpecialization(), getPartialSpecializations(), and getSpecializations().
getInjectedClassNameSpecialization()
QualType ClassTemplateDecl::getInjectedClassNameSpecialization ()
Retrieve the template specialization type of the injected-class-name for this class template.
The injected-class-name for a class template X is X<template-args>, where template-args is formed from the template arguments that correspond to the template parameters of X. For example:
template<typename T, int N>
struct array {
  typedef array this_type; // "array" is equivalent to "array<T, N>"
};
Definition at line 601 of file DeclTemplate.cpp.
References clang::Decl::getASTContext(), getCommonPtr(), clang::ASTContext::getInjectedTemplateArgs(), clang::TemplateDecl::getTemplateParameters(), clang::ASTContext::getTemplateSpecializationType(), clang::ClassTemplateDecl::Common::InjectedClassNameType, and clang::QualType::isNull().
Referenced by clang::Sema::CheckClassTemplate(), clang::Sema::isMoreSpecializedThanPrimary(), clang::ASTDeclReader::VisitClassTemplateDecl(), and clang::ASTNodeImporter::VisitRecordDecl().
getInstantiatedFromMemberTemplate()
ClassTemplateDecl * clang::ClassTemplateDecl::getInstantiatedFromMemberTemplate () const inline
Definition at line 2379 of file DeclTemplate.h.
References clang::RedeclarableTemplateDecl::getInstantiatedFromMemberTemplate().
Referenced by clang::Sema::CheckClassTemplate(), and getPatternForClassTemplateSpecialization().
getMostRecentDecl() [1/2]
ClassTemplateDecl * clang::ClassTemplateDecl::getMostRecentDecl () inline
Definition at line 2371 of file DeclTemplate.h.
References clang::cast(), and getMostRecentDecl().
Referenced by clang::Sema::CheckClassTemplate(), getMostRecentDecl(), getMostRecentDecl(), and clang::ASTNodeImporter::VisitClassTemplateDecl().
getMostRecentDecl() [2/2]
const ClassTemplateDecl * clang::ClassTemplateDecl::getMostRecentDecl () const inline
Definition at line 2375 of file DeclTemplate.h.
References getMostRecentDecl().
getPartialSpecializations() [1/2]
llvm::FoldingSetVector< ClassTemplatePartialSpecializationDecl > & ClassTemplateDecl::getPartialSpecializations () const protected
Retrieve the set of partial specializations of this class template.
Definition at line 479 of file DeclTemplate.cpp.
References getCommonPtr(), LoadLazySpecializations(), and clang::ClassTemplateDecl::Common::PartialSpecializations.
Referenced by AddPartialSpecialization(), findPartialSpecialization(), findPartialSpecialization(), findPartialSpecInstantiatedFromMember(), getPartialSpecializations(), getPatternForClassTemplateSpecialization(), and clang::Sema::usesPartialOrExplicitSpecialization().
getPartialSpecializations() [2/2]
void ClassTemplateDecl::getPartialSpecializations (SmallVectorImpl< ClassTemplatePartialSpecializationDecl * > & PS) const
Retrieve the partial specializations as an ordered list.
Definition at line 566 of file DeclTemplate.cpp.
References getPartialSpecializations(), and P.
getPreviousDecl() [1/2]
ClassTemplateDecl * clang::ClassTemplateDecl::getPreviousDecl () inline
Retrieve the previous declaration of this class template, or nullptr if no such declaration exists.
Definition at line 2361 of file DeclTemplate.h.
References getPreviousDecl().
Referenced by getPreviousDecl(), and getPreviousDecl().
getPreviousDecl() [2/2]
const ClassTemplateDecl * clang::ClassTemplateDecl::getPreviousDecl () const inline
Definition at line 2365 of file DeclTemplate.h.
References getPreviousDecl().
getSpecializations()
llvm::FoldingSetVector< ClassTemplateSpecializationDecl > & ClassTemplateDecl::getSpecializations () const protected
Retrieve the set of specializations of this class template.
Definition at line 473 of file DeclTemplate.cpp.
References getCommonPtr(), LoadLazySpecializations(), and clang::ClassTemplateDecl::Common::Specializations.
Referenced by AddSpecialization(), findSpecialization(), spec_begin(), and spec_end().
getTemplatedDecl()
CXXRecordDecl * clang::ClassTemplateDecl::getTemplatedDecl () const inline
Get the underlying class declarations of the template.
Definition at line 2321 of file DeclTemplate.h.
References clang::TemplateDecl::TemplatedDecl.
Referenced by clang::Sema::CheckClassTemplate(), getPatternForClassTemplateSpecialization(), clang::Sema::isStdInitializerList(), IsStructurallyEquivalent(), isThisDeclarationADefinition(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), clang::ASTDeclReader::VisitClassTemplateDecl(), and clang::ASTNodeImporter::VisitClassTemplateDecl().
isThisDeclarationADefinition()
bool clang::ClassTemplateDecl::isThisDeclarationADefinition () const inline
Returns whether this template declaration defines the primary class pattern.
Definition at line 2327 of file DeclTemplate.h.
References getTemplatedDecl(), and clang::TagDecl::isThisDeclarationADefinition().
Referenced by clang::ASTNodeImporter::VisitClassTemplateDecl().
LoadLazySpecializations()
void ClassTemplateDecl::LoadLazySpecializations () const
Load any lazily-loaded specializations from the external source.
Definition at line 468 of file DeclTemplate.cpp.
References clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl().
Referenced by getPartialSpecializations(), and getSpecializations().
newCommon()
RedeclarableTemplateDecl::CommonBase * ClassTemplateDecl::newCommon (ASTContext & C) const override protected virtual
Implements clang::RedeclarableTemplateDecl.
Definition at line 485 of file DeclTemplate.cpp.
References clang::C.
spec_begin()
spec_iterator clang::ClassTemplateDecl::spec_begin () const inline
Definition at line 2444 of file DeclTemplate.h.
References getSpecializations(), and clang::RedeclarableTemplateDecl::makeSpecIterator().
Referenced by specializations().
spec_end()
spec_iterator clang::ClassTemplateDecl::spec_end () const inline
Definition at line 2448 of file DeclTemplate.h.
References getSpecializations(), and clang::RedeclarableTemplateDecl::makeSpecIterator().
Referenced by specializations().
specializations()
spec_range clang::ClassTemplateDecl::specializations () const inline
Definition at line 2440 of file DeclTemplate.h.
References spec_begin(), and spec_end().
Friends And Related Symbol Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 2314 of file DeclTemplate.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 2315 of file DeclTemplate.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclTemplate.h
lib/AST/DeclTemplate.cpp