clang: clang::ASTDeserializationListener Class Reference
clang::ASTDeserializationListener Class Reference
#include "clang/Serialization/ASTDeserializationListener.h"
Public Member Functions
virtual ~ASTDeserializationListener ()
virtual void ReaderInitialized (ASTReader *Reader)
The ASTReader was initialized.
virtual void IdentifierRead (serialization::IdentID ID, IdentifierInfo *II)
An identifier was deserialized from the AST file.
virtual void MacroRead (serialization::MacroID ID, MacroInfo *MI)
A macro was read from the AST file.
virtual void TypeRead (serialization::TypeIdx Idx, QualType T)
A type was deserialized from the AST file.
virtual void DeclRead (serialization::DeclID ID, const Decl *D)
A decl was deserialized from the AST file.
virtual void SelectorRead (serialization::SelectorID iD, Selector Sel)
A selector was read from the AST file.
virtual void MacroDefinitionRead (serialization::PreprocessedEntityID, MacroDefinitionRecord *MD)
A macro definition was read from the AST file.
virtual void ModuleRead (serialization::SubmoduleID ID, Module *Mod)
A module definition was read from the AST file.
virtual void ModuleImportRead (serialization::SubmoduleID ID, SourceLocation ImportLoc)
A module import was read from the AST file.
Detailed Description
Definition at line 30 of file ASTDeserializationListener.h.
Constructor & Destructor Documentation
~ASTDeserializationListener()
ASTDeserializationListener::~ASTDeserializationListener () virtual
Definition at line 23 of file ASTCommon.cpp.
Member Function Documentation
DeclRead()
virtual void clang::ASTDeserializationListener::DeclRead (serialization::DeclID ID, const Decl * D) inline virtual
A decl was deserialized from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 47 of file ASTDeserializationListener.h.
IdentifierRead()
virtual void clang::ASTDeserializationListener::IdentifierRead (serialization::IdentID ID, IdentifierInfo * II) inline virtual
An identifier was deserialized from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 38 of file ASTDeserializationListener.h.
Referenced by clang::ASTReader::DecodeIdentifierInfo(), and clang::ASTReader::SetIdentifierInfo().
MacroDefinitionRead()
virtual void clang::ASTDeserializationListener::MacroDefinitionRead (serialization::PreprocessedEntityID , MacroDefinitionRecord * MD) inline virtual
A macro definition was read from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 51 of file ASTDeserializationListener.h.
MacroRead()
virtual void clang::ASTDeserializationListener::MacroRead (serialization::MacroID ID, MacroInfo * MI) inline virtual
A macro was read from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 41 of file ASTDeserializationListener.h.
Referenced by clang::ASTReader::getMacro().
ModuleImportRead()
virtual void clang::ASTDeserializationListener::ModuleImportRead (serialization::SubmoduleID ID, SourceLocation ImportLoc) inline virtual
A module import was read from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 56 of file ASTDeserializationListener.h.
ModuleRead()
virtual void clang::ASTDeserializationListener::ModuleRead (serialization::SubmoduleID ID, Module * Mod) inline virtual
A module definition was read from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 54 of file ASTDeserializationListener.h.
ReaderInitialized()
virtual void clang::ASTDeserializationListener::ReaderInitialized (ASTReader * Reader) inline virtual
The ASTReader was initialized.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 35 of file ASTDeserializationListener.h.
SelectorRead()
virtual void clang::ASTDeserializationListener::SelectorRead (serialization::SelectorID iD, Selector Sel) inline virtual
A selector was read from the AST file.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 49 of file ASTDeserializationListener.h.
Referenced by clang::ASTReader::DecodeSelector(), and clang::serialization::ReadMethodPoolVisitor::operator()().
TypeRead()
virtual void clang::ASTDeserializationListener::TypeRead (serialization::TypeIdx Idx, QualType T) inline virtual
A type was deserialized from the AST file.
The ID here has the qualifier bits already removed, and T is guaranteed to be locally unqualified.
Reimplemented in clang::MultiplexASTDeserializationListener.
Definition at line 45 of file ASTDeserializationListener.h.
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTDeserializationListener.h
lib/Serialization/ASTCommon.cpp