clang: clang::VTTVTable Class Reference
clang::VTTVTable Class Reference
#include "clang/AST/VTTBuilder.h"
Public Member Functions
VTTVTable ()=default
VTTVTable (const CXXRecordDecl *Base, CharUnits BaseOffset, bool BaseIsVirtual)
VTTVTable (BaseSubobject Base, bool BaseIsVirtual)
const CXXRecordDecl * getBase () const
CharUnits getBaseOffset () const
bool isVirtual () const
BaseSubobject getBaseSubobject () const
Detailed Description
Definition at line 32 of file VTTBuilder.h.
Constructor & Destructor Documentation
VTTVTable() [1/3]
clang::VTTVTable::VTTVTable () default
VTTVTable() [2/3]
clang::VTTVTable::VTTVTable (const CXXRecordDecl * Base, CharUnits BaseOffset, bool BaseIsVirtual) inline
Definition at line 38 of file VTTBuilder.h.
VTTVTable() [3/3]
clang::VTTVTable::VTTVTable (BaseSubobject Base, bool BaseIsVirtual) inline
Definition at line 40 of file VTTBuilder.h.
Member Function Documentation
getBase()
const CXXRecordDecl * clang::VTTVTable::getBase () const inline
Definition at line 44 of file VTTBuilder.h.
Referenced by clang::CodeGen::CodeGenVTables::EmitVTTDefinition(), GetAddrOfVTTVTable(), and getBaseSubobject().
getBaseOffset()
CharUnits clang::VTTVTable::getBaseOffset () const inline
Definition at line 48 of file VTTBuilder.h.
Referenced by GetAddrOfVTTVTable(), and getBaseSubobject().
getBaseSubobject()
BaseSubobject clang::VTTVTable::getBaseSubobject () const inline
Definition at line 56 of file VTTBuilder.h.
References getBase(), and getBaseOffset().
Referenced by GetAddrOfVTTVTable().
isVirtual()
bool clang::VTTVTable::isVirtual () const inline
Definition at line 52 of file VTTBuilder.h.
Referenced by GetAddrOfVTTVTable().
The documentation for this class was generated from the following file:
include/clang/AST/VTTBuilder.h