clang: clang::DesignatedInitExpr::Designator Class Reference
clang::DesignatedInitExpr::Designator Class Reference
Represents a single C99 designator.
#include "clang/AST/Expr.h"
Public Member Functions
Designator ()
Designator (const IdentifierInfo *FieldName, SourceLocation DotLoc, SourceLocation FieldLoc)
Initializes a field designator.
Designator (unsigned Index, SourceLocation LBracketLoc, SourceLocation RBracketLoc)
Initializes an array designator.
Designator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc)
Initializes a GNU array-range designator.
bool isFieldDesignator () const
bool isArrayDesignator () const
bool isArrayRangeDesignator () const
IdentifierInfo * getFieldName () const
FieldDecl * getField () const
void setField (FieldDecl *FD)
SourceLocation getDotLoc () const
SourceLocation getFieldLoc () const
SourceLocation getLBracketLoc () const
SourceLocation getRBracketLoc () const
SourceLocation getEllipsisLoc () const
unsigned getFirstExprIndex () const
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceRange getSourceRange () const LLVM_READONLY
Friends
class DesignatedInitExpr
Detailed Description
Represents a single C99 designator.
Todo
This class is infuriatingly similar to clang::Designator, but minor differences (storing indices vs. storing pointers) keep us from reusing it. Try harder, later, to rectify these differences.
Definition at line 5104 of file Expr.h.
Constructor & Destructor Documentation
Designator() [1/4]
clang::DesignatedInitExpr::Designator::Designator () inline
Definition at line 5121 of file Expr.h.
Designator() [2/4]
clang::DesignatedInitExpr::Designator::Designator (const IdentifierInfo * FieldName, SourceLocation DotLoc, SourceLocation FieldLoc) inline
Initializes a field designator.
Definition at line 5124 of file Expr.h.
References clang::DesignatedInitExpr::FieldDesignator::DotLoc, Field, clang::DesignatedInitExpr::FieldDesignator::FieldLoc, and clang::DesignatedInitExpr::FieldDesignator::NameOrField.
Designator() [3/4]
clang::DesignatedInitExpr::Designator::Designator (unsigned Index, SourceLocation LBracketLoc, SourceLocation RBracketLoc) inline
Initializes an array designator.
Definition at line 5134 of file Expr.h.
References ArrayOrRange, clang::DesignatedInitExpr::ArrayOrRangeDesignator::EllipsisLoc, clang::DesignatedInitExpr::ArrayOrRangeDesignator::Index, clang::DesignatedInitExpr::ArrayOrRangeDesignator::LBracketLoc, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::RBracketLoc.
Designator() [4/4]
clang::DesignatedInitExpr::Designator::Designator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc) inline
Initializes a GNU array-range designator.
Definition at line 5145 of file Expr.h.
References ArrayOrRange, clang::DesignatedInitExpr::ArrayOrRangeDesignator::EllipsisLoc, clang::DesignatedInitExpr::ArrayOrRangeDesignator::Index, clang::DesignatedInitExpr::ArrayOrRangeDesignator::LBracketLoc, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::RBracketLoc.
Member Function Documentation
getBeginLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getBeginLoc () const inline
Definition at line 5208 of file Expr.h.
References getDotLoc(), getFieldLoc(), getLBracketLoc(), and clang::SourceLocation::isInvalid().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange(), and getSourceRange().
getDotLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getDotLoc () const inline
Definition at line 5174 of file Expr.h.
References clang::DesignatedInitExpr::FieldDesignator::DotLoc, and Field.
Referenced by ExpandAnonymousFieldDesignator(), getBeginLoc(), and clang::ASTNodeImporter::import().
getEllipsisLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getEllipsisLoc () const inline
Definition at line 5196 of file Expr.h.
References ArrayOrRange, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::EllipsisLoc.
Referenced by clang::ASTNodeImporter::import().
getEndLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getEndLoc () const inline
Definition at line 5214 of file Expr.h.
References getFieldLoc(), and getRBracketLoc().
Referenced by getSourceRange().
getField()
FieldDecl * clang::DesignatedInitExpr::Designator::getField () const inline
Definition at line 5161 of file Expr.h.
References Field, and clang::DesignatedInitExpr::FieldDesignator::NameOrField.
Referenced by getFieldName().
getFieldLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getFieldLoc () const inline
Definition at line 5179 of file Expr.h.
References Field, and clang::DesignatedInitExpr::FieldDesignator::FieldLoc.
Referenced by ExpandAnonymousFieldDesignator(), getBeginLoc(), getEndLoc(), and clang::ASTNodeImporter::import().
getFieldName()
IdentifierInfo * DesignatedInitExpr::Designator::getFieldName () const
Definition at line 4308 of file Expr.cpp.
References Field, getField(), clang::NamedDecl::getIdentifier(), and clang::DesignatedInitExpr::FieldDesignator::NameOrField.
Referenced by clang::ASTNodeImporter::import().
getFirstExprIndex()
unsigned clang::DesignatedInitExpr::Designator::getFirstExprIndex () const inline
Definition at line 5202 of file Expr.h.
References ArrayOrRange, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::Index.
Referenced by clang::ASTNodeImporter::import().
getLBracketLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getLBracketLoc () const inline
Definition at line 5184 of file Expr.h.
References ArrayOrRange, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::LBracketLoc.
Referenced by getBeginLoc(), and clang::ASTNodeImporter::import().
getRBracketLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getRBracketLoc () const inline
Definition at line 5190 of file Expr.h.
References ArrayOrRange, and clang::DesignatedInitExpr::ArrayOrRangeDesignator::RBracketLoc.
Referenced by getEndLoc(), and clang::ASTNodeImporter::import().
getSourceRange()
SourceRange clang::DesignatedInitExpr::Designator::getSourceRange () const inline
Definition at line 5217 of file Expr.h.
References getBeginLoc(), and getEndLoc().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange().
isArrayDesignator()
bool clang::DesignatedInitExpr::Designator::isArrayDesignator () const inline
Definition at line 5156 of file Expr.h.
Referenced by clang::ASTNodeImporter::import().
isArrayRangeDesignator()
bool clang::DesignatedInitExpr::Designator::isArrayRangeDesignator () const inline
Definition at line 5157 of file Expr.h.
Referenced by clang::ASTNodeImporter::import().
isFieldDesignator()
bool clang::DesignatedInitExpr::Designator::isFieldDesignator () const inline
Definition at line 5155 of file Expr.h.
Referenced by clang::ASTNodeImporter::import().
setField()
void clang::DesignatedInitExpr::Designator::setField (FieldDecl * FD) inline
Definition at line 5169 of file Expr.h.
References Field, and clang::DesignatedInitExpr::FieldDesignator::NameOrField.
Friends And Related Symbol Documentation
DesignatedInitExpr
friend class DesignatedInitExpr friend
Definition at line 5118 of file Expr.h.
Member Data Documentation
ArrayOrRange
struct ArrayOrRangeDesignator clang::DesignatedInitExpr::Designator::ArrayOrRange
An array or GNU array-range designator, e.g., "[9]" or "[10..15]".
Definition at line 5116 of file Expr.h.
Referenced by Designator(), Designator(), clang::DesignatedInitExpr::getArrayIndex(), clang::DesignatedInitExpr::getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeStart(), getEllipsisLoc(), getFirstExprIndex(), getLBracketLoc(), and getRBracketLoc().
Field
struct FieldDesignator clang::DesignatedInitExpr::Designator::Field
A field designator, e.g., ".x".
Definition at line 5114 of file Expr.h.
Referenced by Designator(), getDotLoc(), getField(), getFieldLoc(), getFieldName(), and setField().
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp