clang: clang::consumed::PropagationInfo Class Reference
clang::consumed::PropagationInfo Class Reference
Public Member Functions
PropagationInfo ()=default
PropagationInfo (const VarTestResult &VarTest)
PropagationInfo (const VarDecl *Var, ConsumedState TestsFor)
PropagationInfo (const BinaryOperator *Source, EffectiveOp EOp, const VarTestResult &LTest, const VarTestResult &RTest)
PropagationInfo (const BinaryOperator *Source, EffectiveOp EOp, const VarDecl *LVar, ConsumedState LTestsFor, const VarDecl *RVar, ConsumedState RTestsFor)
PropagationInfo (ConsumedState State)
PropagationInfo (const VarDecl *Var)
PropagationInfo (const CXXBindTemporaryExpr *Tmp)
const ConsumedState & getState () const
const VarTestResult & getVarTest () const
const VarTestResult & getLTest () const
const VarTestResult & getRTest () const
const VarDecl * getVar () const
const CXXBindTemporaryExpr * getTmp () const
ConsumedState getAsState (const ConsumedStateMap *StateMap) const
EffectiveOp testEffectiveOp () const
const BinaryOperator * testSourceNode () const
bool isValid () const
bool isState () const
bool isVarTest () const
bool isBinTest () const
bool isVar () const
bool isTmp () const
bool isTest () const
bool isPointerToValue () const
PropagationInfo invertTest () const
Detailed Description
Definition at line 293 of file Consumed.cpp.
Constructor & Destructor Documentation
PropagationInfo() [1/8]
clang::consumed::PropagationInfo::PropagationInfo () default
Referenced by invertTest().
PropagationInfo() [2/8]
clang::consumed::PropagationInfo::PropagationInfo (const VarTestResult & VarTest) inline
Definition at line 320 of file Consumed.cpp.
PropagationInfo() [3/8]
clang::consumed::PropagationInfo::PropagationInfo (const VarDecl * Var, ConsumedState TestsFor) inline
Definition at line 323 of file Consumed.cpp.
References Var, and VarTest.
PropagationInfo() [4/8]
clang::consumed::PropagationInfo::PropagationInfo (const BinaryOperator * Source, EffectiveOp EOp, const VarTestResult & LTest, const VarTestResult & RTest) inline
Definition at line 329 of file Consumed.cpp.
References BinTest.
PropagationInfo() [5/8]
clang::consumed::PropagationInfo::PropagationInfo (const BinaryOperator * Source, EffectiveOp EOp, const VarDecl * LVar, ConsumedState LTestsFor, const VarDecl * RVar, ConsumedState RTestsFor) inline
Definition at line 338 of file Consumed.cpp.
References BinTest.
PropagationInfo() [6/8]
clang::consumed::PropagationInfo::PropagationInfo (ConsumedState State) inline
Definition at line 350 of file Consumed.cpp.
PropagationInfo() [7/8]
clang::consumed::PropagationInfo::PropagationInfo (const VarDecl * Var) inline
Definition at line 352 of file Consumed.cpp.
PropagationInfo() [8/8]
clang::consumed::PropagationInfo::PropagationInfo (const CXXBindTemporaryExpr * Tmp) inline
Definition at line 353 of file Consumed.cpp.
Member Function Documentation
getAsState()
ConsumedState clang::consumed::PropagationInfo::getAsState (const ConsumedStateMap * StateMap) const inline
Definition at line 386 of file Consumed.cpp.
References clang::consumed::CS_None, clang::consumed::ConsumedStateMap::getState(), isState(), isTmp(), isVar(), State, Tmp, and Var.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability(), clang::consumed::ConsumedStmtVisitor::handleCall(), and clang::consumed::ConsumedStmtVisitor::VisitVarDecl().
getLTest()
const VarTestResult & clang::consumed::PropagationInfo::getLTest () const inline
Definition at line 366 of file Consumed.cpp.
References BinTest.
Referenced by splitVarStateForIfBinOp().
getRTest()
const VarTestResult & clang::consumed::PropagationInfo::getRTest () const inline
Definition at line 371 of file Consumed.cpp.
References BinTest.
Referenced by splitVarStateForIfBinOp().
getState()
const ConsumedState & clang::consumed::PropagationInfo::getState () const inline
Definition at line 356 of file Consumed.cpp.
References State.
getTmp()
const CXXBindTemporaryExpr * clang::consumed::PropagationInfo::getTmp () const inline
Definition at line 381 of file Consumed.cpp.
References Tmp.
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), and setStateForVarOrTmp().
getVar()
const VarDecl * clang::consumed::PropagationInfo::getVar () const inline
Definition at line 376 of file Consumed.cpp.
References Var.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability(), clang::consumed::ConsumedStmtVisitor::handleCall(), and setStateForVarOrTmp().
getVarTest()
const VarTestResult & clang::consumed::PropagationInfo::getVarTest () const inline
Definition at line 361 of file Consumed.cpp.
References VarTest.
invertTest()
PropagationInfo clang::consumed::PropagationInfo::invertTest () const inline
Definition at line 424 of file Consumed.cpp.
References BinTest, clang::consumed::EO_And, clang::consumed::EO_Or, invertConsumedUnconsumed(), PropagationInfo(), and VarTest.
isBinTest()
bool clang::consumed::PropagationInfo::isBinTest () const inline
Definition at line 412 of file Consumed.cpp.
isPointerToValue()
bool clang::consumed::PropagationInfo::isPointerToValue () const inline
Definition at line 420 of file Consumed.cpp.
isState()
bool clang::consumed::PropagationInfo::isState () const inline
Definition at line 410 of file Consumed.cpp.
Referenced by getAsState().
isTest()
bool clang::consumed::PropagationInfo::isTest () const inline
Definition at line 416 of file Consumed.cpp.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability().
isTmp()
bool clang::consumed::PropagationInfo::isTmp () const inline
Definition at line 414 of file Consumed.cpp.
Referenced by getAsState(), clang::consumed::ConsumedStmtVisitor::handleCall(), and setStateForVarOrTmp().
isValid()
bool clang::consumed::PropagationInfo::isValid () const inline
Definition at line 409 of file Consumed.cpp.
isVar()
bool clang::consumed::PropagationInfo::isVar () const inline
Definition at line 413 of file Consumed.cpp.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability(), getAsState(), clang::consumed::ConsumedStmtVisitor::handleCall(), and setStateForVarOrTmp().
isVarTest()
bool clang::consumed::PropagationInfo::isVarTest () const inline
Definition at line 411 of file Consumed.cpp.
testEffectiveOp()
EffectiveOp clang::consumed::PropagationInfo::testEffectiveOp () const inline
Definition at line 399 of file Consumed.cpp.
References BinTest.
Referenced by splitVarStateForIfBinOp().
testSourceNode()
const BinaryOperator * clang::consumed::PropagationInfo::testSourceNode () const inline
Definition at line 404 of file Consumed.cpp.
References BinTest.
Member Data Documentation
BinTest
BinTestTy clang::consumed::PropagationInfo::BinTest
Definition at line 315 of file Consumed.cpp.
Referenced by getLTest(), getRTest(), invertTest(), PropagationInfo(), PropagationInfo(), testEffectiveOp(), and testSourceNode().
State
ConsumedState clang::consumed::PropagationInfo::State
Definition at line 311 of file Consumed.cpp.
Referenced by getAsState(), and getState().
Tmp
const CXXBindTemporaryExpr* clang::consumed::PropagationInfo::Tmp
Definition at line 314 of file Consumed.cpp.
Referenced by getAsState(), and getTmp().
Var
const VarDecl* clang::consumed::PropagationInfo::Var
Definition at line 313 of file Consumed.cpp.
Referenced by getAsState(), getVar(), and PropagationInfo().
VarTest
VarTestResult clang::consumed::PropagationInfo::VarTest
Definition at line 312 of file Consumed.cpp.
Referenced by getVarTest(), invertTest(), and PropagationInfo().
The documentation for this class was generated from the following file:
lib/Analysis/Consumed.cpp