clang: clang::ento::RegionAndSymbolInvalidationTraits Class Reference
clang::ento::RegionAndSymbolInvalidationTraits Class Reference
Information about invalidation for a particular region/symbol.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Types
enum InvalidationKinds { TK_PreserveContents = 0x1 , TK_SuppressEscape = 0x2 , TK_DoNotInvalidateSuperRegion = 0x4 , TK_EntireMemSpace = 0x8 }
Describes different invalidation traits.
Public Member Functions
void setTrait (SymbolRef Sym, InvalidationKinds IK)
void setTrait (const MemRegion *MR, InvalidationKinds IK)
bool hasTrait (SymbolRef Sym, InvalidationKinds IK) const
bool hasTrait (const MemRegion *MR, InvalidationKinds IK) const
Detailed Description
Information about invalidation for a particular region/symbol.
Definition at line 1558 of file MemRegion.h.
Member Enumeration Documentation
InvalidationKinds
enum clang::ento::RegionAndSymbolInvalidationTraits::InvalidationKinds
Describes different invalidation traits.
Enumerator
TK_PreserveContents
Tells that a region's contents is not changed.
TK_SuppressEscape
Suppress pointer-escaping of a region.
TK_DoNotInvalidateSuperRegion
TK_EntireMemSpace
When applied to a MemSpaceRegion, indicates the entire memory space should be invalidated.
Definition at line 1571 of file MemRegion.h.
Member Function Documentation
hasTrait() [1/2]
bool RegionAndSymbolInvalidationTraits::hasTrait (const MemRegion * MR, InvalidationKinds IK) const
Definition at line 1740 of file MemRegion.cpp.
References hasTrait().
hasTrait() [2/2]
bool RegionAndSymbolInvalidationTraits::hasTrait (SymbolRef Sym, InvalidationKinds IK) const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1731 of file MemRegion.cpp.
Referenced by hasTrait().
setTrait() [1/2]
void RegionAndSymbolInvalidationTraits::setTrait (const MemRegion * MR, InvalidationKinds IK)
Definition at line 1722 of file MemRegion.cpp.
References setTrait().
setTrait() [2/2]
void RegionAndSymbolInvalidationTraits::setTrait (SymbolRef Sym, InvalidationKinds IK)
Definition at line 1717 of file MemRegion.cpp.
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::AnyCXXConstructorCall::getExtraInvalidatedValues(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), clang::ento::ObjCMethodCall::getExtraInvalidatedValues(), clang::ento::getWidenedLoopState(), clang::ento::CallEvent::invalidateRegions(), and setTrait().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp