clang: clang::CXXBaseSpecifier Class Reference
clang::CXXBaseSpecifier Class Reference
Represents a base class of a C++ class.
#include "clang/AST/DeclCXX.h"
Public Member Functions
CXXBaseSpecifier ()=default
CXXBaseSpecifier (SourceRange R, bool V, bool BC, AccessSpecifier A, TypeSourceInfo *TInfo, SourceLocation EllipsisLoc)
SourceRange getSourceRange () const LLVM_READONLY
Retrieves the source range that contains the entire base specifier.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getBaseTypeLoc () const LLVM_READONLY
Get the location at which the base class type was written.
bool isVirtual () const
Determines whether the base class is a virtual base class (or not).
bool isBaseOfClass () const
Determine whether this base class is a base of a class declared with the 'class' keyword (vs.
bool isPackExpansion () const
Determine whether this base specifier is a pack expansion.
bool getInheritConstructors () const
Determine whether this base class's constructors get inherited.
void setInheritConstructors (bool Inherit=true)
Set that this base class's constructors should be inherited.
SourceLocation getEllipsisLoc () const
For a pack expansion, determine the location of the ellipsis.
AccessSpecifier getAccessSpecifier () const
Returns the access specifier for this base specifier.
AccessSpecifier getAccessSpecifierAsWritten () const
Retrieves the access specifier as written in the source code (which may mean that no access specifier was explicitly written).
QualType getType () const
Retrieves the type of the base class.
TypeSourceInfo * getTypeSourceInfo () const
Retrieves the type and source location of the base class.
Detailed Description
Represents a base class of a C++ class.
Each CXXBaseSpecifier represents a single, direct base class (or struct) of a C++ class (or struct). It specifies the type of that base class, whether it is a virtual or non-virtual base, and what level of access (public, protected, private) is used for the derivation. For example:
class A { };
class B { };
class C : public virtual A, protected B { };
In this code, C will have two CXXBaseSpecifiers, one for "public virtual A" and the other for "protected B".
Definition at line 146 of file DeclCXX.h.
Constructor & Destructor Documentation
CXXBaseSpecifier() [1/2]
clang::CXXBaseSpecifier::CXXBaseSpecifier () default
CXXBaseSpecifier() [2/2]
clang::CXXBaseSpecifier::CXXBaseSpecifier (SourceRange R, bool V, bool BC, AccessSpecifier A, TypeSourceInfo * TInfo, SourceLocation EllipsisLoc) inline
Definition at line 183 of file DeclCXX.h.
Member Function Documentation
getAccessSpecifier()
AccessSpecifier clang::CXXBaseSpecifier::getAccessSpecifier () const inline
Returns the access specifier for this base specifier.
This is the actual base specifier as used for semantic analysis, so the result can never be AS_none. To retrieve the access specifier as written in the source code, use getAccessSpecifierAsWritten().
Definition at line 226 of file DeclCXX.h.
References clang::AS_none, clang::AS_private, and clang::AS_public.
Referenced by clang::Sema::AttachBaseSpecifiers(), and DiagnoseAccessPath().
getAccessSpecifierAsWritten()
AccessSpecifier clang::CXXBaseSpecifier::getAccessSpecifierAsWritten () const inline
Retrieves the access specifier as written in the source code (which may mean that no access specifier was explicitly written).
Use getAccessSpecifier() to retrieve the access specifier for use in semantic analysis.
Definition at line 238 of file DeclCXX.h.
Referenced by DiagnoseAccessPath(), and clang::ASTImporter::Import().
getBaseTypeLoc()
SourceLocation clang::CXXBaseSpecifier::getBaseTypeLoc () const inline
Get the location at which the base class type was written.
Definition at line 194 of file DeclCXX.h.
References clang::TypeLoc::getBeginLoc(), and clang::TypeSourceInfo::getTypeLoc().
getBeginLoc()
SourceLocation clang::CXXBaseSpecifier::getBeginLoc () const inline
Definition at line 190 of file DeclCXX.h.
Referenced by clang::Sema::AttachBaseSpecifiers(), clang::Sema::BuildMemInitializer(), checkMoveAssignmentForRepeatedMove(), getNonCLikeKindForAnonymousStruct(), IsStructurallyEquivalent(), and clang::Sema::SpecialMemberIsTrivial().
getEllipsisLoc()
SourceLocation clang::CXXBaseSpecifier::getEllipsisLoc () const inline
For a pack expansion, determine the location of the ellipsis.
Definition at line 217 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import().
getEndLoc()
SourceLocation clang::CXXBaseSpecifier::getEndLoc () const inline
Definition at line 191 of file DeclCXX.h.
Referenced by getNonCLikeKindForAnonymousStruct().
getInheritConstructors()
bool clang::CXXBaseSpecifier::getInheritConstructors () const inline
Determine whether this base class's constructors get inherited.
Definition at line 209 of file DeclCXX.h.
getSourceRange()
SourceRange clang::CXXBaseSpecifier::getSourceRange () const inline
Retrieves the source range that contains the entire base specifier.
Definition at line 189 of file DeclCXX.h.
Referenced by clang::Sema::BuildMemInitializer(), checkMoveAssignmentForRepeatedMove(), DiagnoseAccessPath(), clang::ASTImporter::Import(), and IsStructurallyEquivalent().
getType()
QualType clang::CXXBaseSpecifier::getType () const inline
Retrieves the type of the base class.
This type will always be an unqualified class type.
Definition at line 245 of file DeclCXX.h.
References clang::TypeSourceInfo::getType(), and clang::QualType::getUnqualifiedType().
Referenced by clang::Sema::AttachBaseSpecifiers(), BuildImplicitBaseInitializer(), clang::Sema::BuildMemInitializer(), clang::Sema::CheckConstructorAccess(), checkMoveAssignmentForRepeatedMove(), clang::InitializationSequence::Diagnose(), clang::ento::ProgramState::getLValue(), HandleConstructorCall(), IsStructurallyEquivalent(), LeastDerivedClassWithSameLayout(), clang::Sema::LookupQualifiedName(), print_elem(), clang::APValue::printPretty(), and usesMultipleInheritanceModel().
getTypeSourceInfo()
TypeSourceInfo * clang::CXXBaseSpecifier::getTypeSourceInfo () const inline
Retrieves the type and source location of the base class.
Definition at line 250 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import().
isBaseOfClass()
bool clang::CXXBaseSpecifier::isBaseOfClass () const inline
Determine whether this base class is a base of a class declared with the 'class' keyword (vs.
one declared with the 'struct' keyword).
Definition at line 203 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import().
isPackExpansion()
bool clang::CXXBaseSpecifier::isPackExpansion () const inline
Determine whether this base specifier is a pack expansion.
Definition at line 206 of file DeclCXX.h.
References clang::SourceLocation::isValid().
isVirtual()
bool clang::CXXBaseSpecifier::isVirtual () const inline
Determines whether the base class is a virtual base class (or not).
Definition at line 199 of file DeclCXX.h.
Referenced by clang::Sema::BuildBaseInitializer(), BuildImplicitBaseInitializer(), checkMoveAssignmentForRepeatedMove(), FindBaseInitializer(), clang::ento::ProgramState::getLValue(), getOffsetOfFullPath(), HandleConstructorCall(), clang::ASTImporter::Import(), PerformConstructorInitialization(), and clang::Sema::SpecialMemberIsTrivial().
setInheritConstructors()
void clang::CXXBaseSpecifier::setInheritConstructors (bool Inherit = true) inline
Set that this base class's constructors should be inherited.
Definition at line 212 of file DeclCXX.h.
The documentation for this class was generated from the following file:
include/clang/AST/DeclCXX.h