clang: clang::LookupResult Class Reference
clang::LookupResult Class Reference
Represents the results of name lookup.
#include "clang/Sema/Lookup.h"
Classes
class Filter
A class for iterating through a result set and possibly filtering out results.
Public Types
enum LookupResultKind {
NotFound = 0 , NotFoundInCurrentInstantiation , Found , FoundOverloaded ,
FoundUnresolvedValue , Ambiguous
}
enum AmbiguityKind { AmbiguousBaseSubobjectTypes , AmbiguousBaseSubobjects , AmbiguousReference , AmbiguousTagHiding }
enum TemporaryToken { Temporary }
A little identifier for flagging temporary lookup results.
using iterator = UnresolvedSetImpl::iterator
Public Member Functions
LookupResult (Sema &SemaRef, const DeclarationNameInfo &NameInfo, Sema::LookupNameKind LookupKind, Sema::RedeclarationKind Redecl=Sema::NotForRedeclaration)
LookupResult (Sema &SemaRef, DeclarationName Name, SourceLocation NameLoc, Sema::LookupNameKind LookupKind, Sema::RedeclarationKind Redecl=Sema::NotForRedeclaration)
LookupResult (TemporaryToken _, const LookupResult &Other)
Creates a temporary lookup result, initializing its core data using the information from another result.
LookupResult (const LookupResult &)=delete
LookupResult & operator= (const LookupResult &)=delete
LookupResult (LookupResult &&Other)
LookupResult & operator= (LookupResult &&Other)
~LookupResult ()
const DeclarationNameInfo & getLookupNameInfo () const
Gets the name info to look up.
void setLookupNameInfo (const DeclarationNameInfo &NameInfo)
Sets the name info to look up.
DeclarationName getLookupName () const
Gets the name to look up.
void setLookupName (DeclarationName Name)
Sets the name to look up.
Sema::LookupNameKind getLookupKind () const
Gets the kind of lookup to perform.
bool isForRedeclaration () const
True if this lookup is just looking for an existing declaration.
bool isForExternalRedeclaration () const
True if this lookup is just looking for an existing declaration to link against a declaration with external linkage.
Sema::RedeclarationKind redeclarationKind () const
void setAllowHidden (bool AH)
Specify whether hidden declarations are visible, e.g., for recovery reasons.
bool isHiddenDeclarationVisible (NamedDecl *ND) const
Determine whether this lookup is permitted to see hidden declarations, such as those in modules that have not yet been imported.
void setHideTags (bool Hide)
Sets whether tag declarations should be hidden by non-tag declarations during resolution.
void setTemplateNameLookup (bool TemplateName)
Sets whether this is a template-name lookup.
bool isTemplateNameLookup () const
bool isAmbiguous () const
bool isSingleResult () const
Determines if this names a single result which is not an unresolved value using decl.
bool isOverloadedResult () const
Determines if the results are overloaded.
bool isUnresolvableResult () const
LookupResultKind getResultKind () const
AmbiguityKind getAmbiguityKind () const
const UnresolvedSetImpl & asUnresolvedSet () const
iterator begin () const
iterator end () const
bool empty () const
Return true if no decls were found.
CXXBasePaths * getBasePaths () const
Return the base paths structure that's associated with these results, or null if none is.
NamedDecl * getAcceptableDecl (NamedDecl *D) const
Retrieve the accepted (re)declaration of the given declaration, if there is one.
unsigned getIdentifierNamespace () const
Returns the identifier namespace mask for this lookup.
bool isClassLookup () const
Returns whether these results arose from performing a lookup into a class.
CXXRecordDecl * getNamingClass () const
Returns the 'naming class' for this lookup, i.e.
void setNamingClass (CXXRecordDecl *Record)
Sets the 'naming class' for this lookup.
QualType getBaseObjectType () const
Returns the base object type associated with this lookup; important for [class.protected].
void setBaseObjectType (QualType T)
Sets the base object type for this lookup.
void addDecl (NamedDecl *D)
Add a declaration to these results with its natural access.
void addDecl (NamedDecl *D, AccessSpecifier AS)
Add a declaration to these results with the given access.
void addAllDecls (const LookupResult &Other)
Add all the declarations from another set of lookup results.
bool wasNotFoundInCurrentInstantiation () const
Determine whether no result was found because we could not search into dependent base classes of the current instantiation.
void setNotFoundInCurrentInstantiation ()
Note that while no result was found in the current instantiation, there were dependent base classes that could not be searched.
bool isShadowed () const
Determine whether the lookup result was shadowed by some other declaration that lookup ignored.
void setShadowed ()
Note that we found and ignored a declaration while performing lookup.
void resolveKind ()
Resolves the result kind of the lookup, possibly hiding decls.
void resolveKindAfterFilter ()
Re-resolves the result kind of the lookup after a set of removals has been performed.
template<class DeclClass >
DeclClass * getAsSingle () const
NamedDecl * getFoundDecl () const
Fetch the unique decl found by this lookup.
NamedDecl * getRepresentativeDecl () const
Fetches a representative decl. Useful for lazy diagnostics.
bool isSingleTagDecl () const
Asks if the result is a single tag decl.
void setAmbiguousBaseSubobjectTypes (CXXBasePaths &P)
Make these results show that the name was found in base classes of different types.
void setAmbiguousBaseSubobjects (CXXBasePaths &P)
Make these results show that the name was found in distinct base classes of the same type.
void setAmbiguousQualifiedTagHiding ()
Make these results show that the name was found in different contexts and a tag decl was hidden by an ordinary decl in a different context.
LLVM_ATTRIBUTE_REINITIALIZES void clear ()
Clears out any current state.
void clear (Sema::LookupNameKind Kind)
Clears out any current state and re-initializes for a different kind of lookup.
void setRedeclarationKind (Sema::RedeclarationKind RK)
Change this lookup's redeclaration kind.
void dump ()
void print (raw_ostream &)
void suppressDiagnostics ()
Suppress the diagnostics that would normally fire because of this lookup.
bool isSuppressingDiagnostics () const
Determines whether this lookup is suppressing diagnostics.
void setContextRange (SourceRange SR)
Sets a 'context' source range.
SourceRange getContextRange () const
Gets the source range of the context of this name; for C++ qualified lookups, this is the source range of the scope specifier.
SourceLocation getNameLoc () const
Gets the location of the identifier.
Sema & getSema () const
Get the Sema object that this lookup result is searching with.
Filter makeFilter ()
Create a filter for this result set.
void setFindLocalExtern (bool FindLocalExtern)
Static Public Member Functions
static bool isVisible (Sema &SemaRef, NamedDecl *D)
Determine whether the given declaration is visible to the program.
static bool isReachable (Sema &SemaRef, NamedDecl *D)
static bool isAcceptable (Sema &SemaRef, NamedDecl *D, Sema::AcceptableKind Kind)
static bool isAvailableForLookup (Sema &SemaRef, NamedDecl *ND)
Determine whether this lookup is permitted to see the declaration.
Detailed Description
Represents the results of name lookup.
An instance of the LookupResult class captures the results of a single name lookup, which can return no result (nothing found), a single declaration, a set of overloaded functions, or an ambiguity. Use the getKind() method to determine which of these results occurred for a given lookup.
Definition at line 46 of file Lookup.h.
Member Typedef Documentation
iterator
using clang::LookupResult::iterator = UnresolvedSetImpl::iterator
Definition at line 143 of file Lookup.h.
Member Enumeration Documentation
AmbiguityKind
enum clang::LookupResult::AmbiguityKind
Enumerator
AmbiguousBaseSubobjectTypes
Name lookup results in an ambiguity because multiple entities that meet the lookup criteria were found in subobjects of different types.
For example:
struct A { void f(int); }
struct B { void f(double); }
struct C : A, B { };
void test(C c) {
  c.f(0); // error: A::f and B::f come from subobjects of different
          // types. overload resolution is not performed.
}
AmbiguousBaseSubobjects
Name lookup results in an ambiguity because multiple nonstatic entities that meet the lookup criteria were found in different subobjects of the same type.
For example:
struct A { int x; };
struct B : A { };
struct C : A { };
struct D : B, C { };
int test(D d) {
  return d.x; // error: 'x' is found in two A subobjects (of B and C)
}
AmbiguousReference
Name lookup results in an ambiguity because multiple definitions of entity that meet the lookup criteria were found in different declaration contexts.
namespace A {
  int i;
  namespace B { int i; }
  int test() {
    using namespace B;
    return i; // error 'i' is found in namespace A and A::B
   }
}
AmbiguousTagHiding
Name lookup results in an ambiguity because an entity with a tag name was hidden by an entity with an ordinary name from a different context.
namespace A { struct Foo {}; }
namespace B { void Foo(); }
namespace C {
  using namespace A;
  using namespace B;
}
void test() {
  C::Foo(); // error: tag 'A::Foo' is hidden by an object in a
            // different namespace
}
Definition at line 76 of file Lookup.h.
LookupResultKind
enum clang::LookupResult::LookupResultKind
Enumerator
NotFound
No entity found met the criteria.
NotFoundInCurrentInstantiation
No entity found met the criteria within the current instantiation,, but there were dependent base classes of the current instantiation that could not be searched.
Found
Name lookup found a single declaration that met the criteria.
getFoundDecl() will return this declaration.
FoundOverloaded
Name lookup found a set of overloaded functions that met the criteria.
FoundUnresolvedValue
Name lookup found an unresolvable value declaration and cannot yet complete.
This only happens in C++ dependent contexts with dependent using declarations.
Ambiguous
Name lookup results in an ambiguity; use getAmbiguityKind to figure out what kind of ambiguity we have.
Definition at line 48 of file Lookup.h.
TemporaryToken
enum clang::LookupResult::TemporaryToken
A little identifier for flagging temporary lookup results.
Enumerator
Temporary
Definition at line 139 of file Lookup.h.
Constructor & Destructor Documentation
LookupResult() [1/5]
clang::LookupResult::LookupResult (Sema & SemaRef, const DeclarationNameInfo & NameInfo, Sema::LookupNameKind LookupKind, Sema::RedeclarationKind Redecl = Sema::NotForRedeclaration) inline
Definition at line 145 of file Lookup.h.
LookupResult() [2/5]
clang::LookupResult::LookupResult (Sema & SemaRef, DeclarationName Name, SourceLocation NameLoc, Sema::LookupNameKind LookupKind, Sema::RedeclarationKind Redecl = Sema::NotForRedeclaration) inline
Definition at line 158 of file Lookup.h.
LookupResult() [3/5]
clang::LookupResult::LookupResult (TemporaryToken _, const LookupResult & Other) inline
Creates a temporary lookup result, initializing its core data using the information from another result.
Diagnostics are always disabled.
Definition at line 171 of file Lookup.h.
LookupResult() [4/5]
clang::LookupResult::LookupResult (const LookupResult &) delete
LookupResult() [5/5]
clang::LookupResult::LookupResult (LookupResult && Other) inline
Definition at line 183 of file Lookup.h.
~LookupResult()
clang::LookupResult::~LookupResult () inline
Definition at line 227 of file Lookup.h.
Member Function Documentation
addAllDecls()
void clang::LookupResult::addAllDecls (const LookupResult & Other) inline
Add all the declarations from another set of lookup results.
Definition at line 465 of file Lookup.h.
References clang::UnresolvedSetImpl::begin(), clang::UnresolvedSetImpl::end(), and Found.
Referenced by clang::Sema::CheckOverload(), and LookupQualifiedNameInUsingDirectives().
addDecl() [1/2]
void clang::LookupResult::addDecl (NamedDecl * D) inline
Add a declaration to these results with its natural access.
Does not test the acceptance criteria.
Definition at line 452 of file Lookup.h.
References addDecl(), and clang::Decl::getAccess().
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnUsingDirective(), clang::Sema::ActOnVarTemplateSpecialization(), addDecl(), attemptRecovery(), clang::Sema::BuildCXXNestedNameSpecifier(), BuildImplicitMemberInitializer(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckImplicitSpecialMemberDeclaration(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), InsertOCLBuiltinDeclarationsFromTable(), clang::Sema::LookupBuiltin(), LookupDirect(), clang::Sema::LookupInSuper(), clang::Sema::LookupName(), LookupPotentialTypoResult(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupTemplateName(), clang::TreeTransform< Derived >::RebuildMemberExpr(), clang::TreeTransform< Derived >::TransformOverloadExprDecls(), and TryNamespaceTypoCorrection().
addDecl() [2/2]
void clang::LookupResult::addDecl (NamedDecl * D, AccessSpecifier AS) inline
Add a declaration to these results with the given access.
Does not test the acceptance criteria.
Definition at line 458 of file Lookup.h.
References Found.
asUnresolvedSet()
const UnresolvedSetImpl & clang::LookupResult::asUnresolvedSet () const inline
Definition at line 331 of file Lookup.h.
Referenced by clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildOperatorCoawaitLookupExpr(), and clang::Sema::ProduceCallSignatureHelp().
begin()
iterator clang::LookupResult::begin () const inline
Definition at line 335 of file Lookup.h.
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::AddMemberOperatorCandidates(), clang::Sema::AddOverloadedCallCandidates(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), BuildRecoveryCallExpr(), buildSingleCopyAssignRecursively(), clang::Sema::BuildTemplateIdExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckLookupAccess(), clang::Sema::CheckOverload(), clang::Sema::CheckQualifiedMemberReference(), clang::Sema::CheckUsingDeclRedeclaration(), ClassifyImplicitMemberAccess(), CXXRecordMembersNamed(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::DiagnoseDependentMemberLookup(), DiagnoseInvalidRedeclaration(), clang::Sema::FindAllocationFunctions(), getFoundDecl(), getRepresentativeDecl(), clang::Sema::hasAnyAcceptableTemplateNames(), HasNoThrowOperator(), isResultTypeOrTemplate(), clang::Sema::isTemplateName(), clang::Sema::lookupCoroutineTraits(), clang::Sema::LookupLiteralOperator(), clang::Sema::LookupOverloadedOperatorName(), print(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), and resolveDeallocationOverload().
clear() [1/2]
LLVM_ATTRIBUTE_REINITIALIZES void clang::LookupResult::clear () inline
Clears out any current state.
Definition at line 580 of file Lookup.h.
References NotFound.
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnUsingDirective(), clang::Sema::BuildCXXNestedNameSpecifier(), buildDeclareReductionRef(), clang::Sema::BuildMemInitializer(), BuildRecoveryCallExpr(), buildUserDefinedMapperRef(), clear(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), clang::Sema::FindAllocationFunctions(), LookupPotentialTypoResult(), LookupQualifiedNameInUsingDirectives(), clang::Sema::LookupTemplateName(), resolveAllocationOverload(), clang::TreeTransform< Derived >::TransformOverloadExprDecls(), and TryNamespaceTypoCorrection().
clear() [2/2]
void clang::LookupResult::clear (Sema::LookupNameKind Kind) inline
Clears out any current state and re-initializes for a different kind of lookup.
Definition at line 591 of file Lookup.h.
References clear().
dump()
LLVM_DUMP_METHOD void LookupResult::dump ()
Definition at line 674 of file SemaLookup.cpp.
References clang::Decl::dump(), clang::DeclarationName::getAsString(), and getLookupName().
Referenced by clang::Sema::ActOnPragmaDump().
empty()
bool clang::LookupResult::empty () const inline
Return true if no decls were found.
Definition at line 339 of file Lookup.h.
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnPragmaUnused(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnUsingDirective(), clang::Sema::BuildCXXNestedNameSpecifier(), buildDeclareReductionRef(), clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemInitializer(), BuildNonArrayForRange(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), BuildRecoveryCallExpr(), clang::Sema::BuildUsingDeclaration(), ClassifyImplicitMemberAccess(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseInvalidRedeclaration(), DiagnoseTwoPhaseLookup(), doesUsualArrayDeleteWantSize(), emitReplacement(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindDeallocationFunction(), getTupleLikeElementType(), clang::Sema::isDeductionGuideName(), clang::Sema::isTemplateName(), isTupleLike(), clang::Sema::LookupInObjCMethod(), clang::Sema::LookupInSuper(), clang::Sema::LookupIvarInObjCMethod(), LookupMemberExprInRecord(), LookupPotentialTypoResult(), LookupQualifiedNameInUsingDirectives(), clang::Sema::LookupTemplateName(), clang::MultiplexExternalSemaSource::LookupUnqualified(), and resolveBuiltinNewDeleteOverload().
end()
iterator clang::LookupResult::end () const inline
Definition at line 336 of file Lookup.h.
Referenced by clang::Sema::AddMemberOperatorCandidates(), clang::Sema::AddOverloadedCallCandidates(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildOverloadedArrowExpr(), buildSingleCopyAssignRecursively(), clang::Sema::BuildTemplateIdExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckLookupAccess(), clang::Sema::CheckOverload(), clang::Sema::CheckQualifiedMemberReference(), clang::Sema::CheckUsingDeclRedeclaration(), CXXRecordMembersNamed(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), DiagnoseInvalidRedeclaration(), clang::Sema::FindAllocationFunctions(), clang::Sema::hasAnyAcceptableTemplateNames(), HasNoThrowOperator(), isResultTypeOrTemplate(), clang::Sema::isTemplateName(), clang::Sema::LookupLiteralOperator(), clang::Sema::LookupOverloadedOperatorName(), print(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), and resolveDeallocationOverload().
getAcceptableDecl()
NamedDecl * clang::LookupResult::getAcceptableDecl (NamedDecl * D) const inline
Retrieve the accepted (re)declaration of the given declaration, if there is one.
Definition at line 385 of file Lookup.h.
References getSema(), isAvailableForLookup(), isHiddenDeclarationVisible(), and clang::Decl::isInIdentifierNamespace().
Referenced by clang::Sema::CheckImplicitSpecialMemberDeclaration(), LookupDirect(), clang::Sema::LookupName(), and clang::Sema::LookupQualifiedName().
getAmbiguityKind()
AmbiguityKind clang::LookupResult::getAmbiguityKind () const inline
Definition at line 326 of file Lookup.h.
References isAmbiguous().
getAsSingle()
template<class DeclClass > DeclClass * clang::LookupResult::getAsSingle () const inline
Definition at line 533 of file Lookup.h.
References Found, getFoundDecl(), and getResultKind().
Referenced by clang::Sema::ActOnCXXTypeid(), clang::Sema::ActOnEnumConstant(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnPragmaUnused(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnUsingDirective(), clang::Sema::BuildBuiltinCallExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), buildMemcpyForAssignmentOp(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckOverload(), clang::Sema::CheckUsingDeclQualifier(), getTupleLikeElementType(), clang::Sema::isDeductionGuideName(), clang::Sema::isNonTypeNestedNameSpecifier(), clang::Sema::isTagName(), isTagTypeWithMissingTag(), clang::Sema::lookupCoroutineTraits(), clang::Sema::lookupOpenMPDeclareTargetName(), lookupPromiseType(), clang::Sema::LookupSingleName(), LookupStdSourceLocationImpl(), and clang::Sema::MergeTypedefNameDecl().
getBaseObjectType()
QualType clang::LookupResult::getBaseObjectType () const inline
Returns the base object type associated with this lookup; important for [class.protected].
Most lookups do not have an associated base object.
Definition at line 441 of file Lookup.h.
Referenced by clang::Sema::CheckLookupAccess().
getBasePaths()
CXXBasePaths * clang::LookupResult::getBasePaths () const inline
Return the base paths structure that's associated with these results, or null if none is.
Definition at line 343 of file Lookup.h.
getContextRange()
SourceRange clang::LookupResult::getContextRange () const inline
Gets the source range of the context of this name; for C++ qualified lookups, this is the source range of the scope specifier.
Definition at line 626 of file Lookup.h.
getFoundDecl()
NamedDecl * clang::LookupResult::getFoundDecl () const inline
Fetch the unique decl found by this lookup.
Asserts that one was found.
This is intended for users who have examined the result kind and are certain that there is only one result.
Definition at line 543 of file Lookup.h.
References begin(), Found, and getResultKind().
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnSizeofParameterPackExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildUsingDeclaration(), CheckObjCBridgeCFCast(), CheckObjCBridgeNSCast(), clang::Sema::checkObjCBridgeRelatedComponents(), emitReplacement(), clang::Sema::FindFirstQualifierInScope(), getAsSingle(), clang::Sema::getShadowedDeclaration(), clang::Sema::getShadowedDeclaration(), clang::Sema::getShadowedDeclaration(), isSingleTagDecl(), clang::Sema::LookupInlineAsmField(), clang::Sema::LookupInlineAsmVarDeclField(), clang::Sema::LookupIvarInObjCMethod(), LookupPotentialTypoResult(), clang::Sema::LookupTemplateName(), and ShouldLookupResultBeMultiVersionOverload().
getIdentifierNamespace()
unsigned clang::LookupResult::getIdentifierNamespace () const inline
Returns the identifier namespace mask for this lookup.
Definition at line 403 of file Lookup.h.
Referenced by clang::Sema::LookupQualifiedName().
getLookupKind()
Sema::LookupNameKind clang::LookupResult::getLookupKind () const inline
Gets the kind of lookup to perform.
Definition at line 253 of file Lookup.h.
Referenced by clang::Sema::ActOnSizeofParameterPackExpr(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckOverload(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseInvalidRedeclaration(), clang::Sema::LookupBuiltin(), clang::Sema::LookupInSuper(), LookupMemberExprInRecord(), clang::Sema::LookupName(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupTemplateName(), clang::Sema::resolveAssumedTemplateNameAsType(), resolveKind(), and TryNamespaceTypoCorrection().
getLookupName()
DeclarationName clang::LookupResult::getLookupName () const inline
Gets the name to look up.
Definition at line 243 of file Lookup.h.
References clang::DeclarationNameInfo::getName().
Referenced by clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::CheckShadow(), clang::Sema::DiagnoseDependentMemberLookup(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), dump(), clang::Sema::LookupBuiltin(), LookupDirect(), clang::Sema::LookupLiteralOperator(), LookupMemberExpr(), LookupMemberExprInRecord(), clang::Sema::LookupName(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupTemplateName(), resolveAllocationOverload(), clang::Sema::resolveAssumedTemplateNameAsType(), and resolveBuiltinNewDeleteOverload().
getLookupNameInfo()
const DeclarationNameInfo & clang::LookupResult::getLookupNameInfo () const inline
Gets the name info to look up.
Definition at line 233 of file Lookup.h.
Referenced by clang::Sema::ActOnSizeofParameterPackExpr(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildPossibleImplicitMemberExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckQualifiedMemberReference(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseInvalidRedeclaration(), clang::Sema::LookupInSuper(), LookupMemberExpr(), LookupMemberExprInRecord(), clang::Sema::LookupTemplateName(), clang::Sema::resolveAssumedTemplateNameAsType(), and TryNamespaceTypoCorrection().
getNameLoc()
SourceLocation clang::LookupResult::getNameLoc () const inline
Gets the location of the identifier.
This isn't always defined: sometimes we're doing lookups on synthesized names.
Definition at line 632 of file Lookup.h.
References clang::DeclarationNameInfo::getLoc().
Referenced by clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildPossibleImplicitMemberExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::CheckLookupAccess(), clang::Sema::CheckShadow(), clang::Sema::DiagnoseDependentMemberLookup(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), InsertOCLBuiltinDeclarationsFromTable(), clang::Sema::LookupBuiltin(), LookupDirect(), clang::Sema::LookupInObjCMethod(), clang::Sema::LookupIvarInObjCMethod(), clang::Sema::LookupLiteralOperator(), LookupMemberExpr(), LookupMemberExprInRecord(), clang::Sema::LookupTemplateName(), resolveAllocationOverload(), clang::Sema::resolveAssumedTemplateNameAsType(), resolveBuiltinNewDeleteOverload(), resolveKind(), and shouldWarnIfShadowedDecl().
getNamingClass()
CXXRecordDecl * clang::LookupResult::getNamingClass () const inline
Returns the 'naming class' for this lookup, i.e.
the class which was looked into to find these results.
C++0x [class.access.base]p5: The access to a member is affected by the class in which the member is named. This naming class is the class in which the member name was looked up and found. [Note: this class can be explicit, e.g., when a qualified-id is used, or implicit, e.g., when a class member access operator (5.2.5) is used (including cases where an implicit "this->" is added). If both a class member access operator and a qualified-id are used to name the member (as in p->T::m), the class naming the member is the class named by the nested-name-specifier of the qualified-id (that is, T). – end note ]
This is set by the lookup routines when they find results in a class.
Definition at line 429 of file Lookup.h.
Referenced by clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::CheckLookupAccess(), ClassifyImplicitMemberAccess(), clang::Sema::DiagnoseDependentMemberLookup(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindDeallocationFunction(), resolveAllocationOverload(), and resolveBuiltinNewDeleteOverload().
getRepresentativeDecl()
NamedDecl * clang::LookupResult::getRepresentativeDecl () const inline
Fetches a representative decl. Useful for lazy diagnostics.
Definition at line 550 of file Lookup.h.
References begin().
Referenced by clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnStartNamespaceDef(), clang::Sema::ActOnUsingDirective(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildPossibleImplicitMemberExpr(), buildUserDefinedMapperRef(), CheckAnonMemberRedeclaration(), clang::Sema::CheckQualifiedMemberReference(), clang::Sema::DiagnoseDependentMemberLookup(), getTupleLikeElementType(), clang::Sema::LookupTemplateName(), and clang::Sema::MergeTypedefNameDecl().
getResultKind()
LookupResultKind clang::LookupResult::getResultKind () const inline
Definition at line 321 of file Lookup.h.
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnSizeofParameterPackExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::CheckMicrosoftIfExistsSymbol(), getAsSingle(), getFoundDecl(), isAmbiguous(), isOverloadedResult(), isSingleResult(), isSingleTagDecl(), clang::Sema::isTagName(), isUnresolvableResult(), clang::Sema::LookupLiteralOperator(), and shouldWarnIfShadowedDecl().
getSema()
Sema & clang::LookupResult::getSema () const inline
Get the Sema object that this lookup result is searching with.
Definition at line 638 of file Lookup.h.
Referenced by getAcceptableDecl(), isResultTypeOrTemplate(), LookupDirect(), LookupMemberExprInRecord(), and resolveKind().
isAcceptable()
static bool clang::LookupResult::isAcceptable (Sema & SemaRef, NamedDecl * D, Sema::AcceptableKind Kind) inline static
Definition at line 353 of file Lookup.h.
References isReachable(), isVisible(), and clang::Sema::Visible.
isAmbiguous()
bool clang::LookupResult::isAmbiguous () const inline
Definition at line 301 of file Lookup.h.
References Ambiguous, and getResultKind().
Referenced by clang::Sema::ActOnIdExpression(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnTemplateName(), clang::Sema::ActOnUsingDirective(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemInitializer(), BuildNonArrayForRange(), clang::Sema::BuildOperatorCoawaitLookupExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), BuildRecoveryCallExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildUsingDeclaration(), checkTupleLikeDecomposition(), DiagnoseInvalidRedeclaration(), doesUsualArrayDeleteWantSize(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindDeallocationFunction(), clang::Sema::FindFirstQualifierInScope(), getAmbiguityKind(), clang::Sema::isDeductionGuideName(), clang::Sema::isTemplateName(), clang::Sema::lookupOpenMPDeclareTargetName(), clang::Sema::LookupOverloadedOperatorName(), lookupStdTypeTraitMember(), clang::Sema::LookupTemplateName(), print(), and resolveBuiltinNewDeleteOverload().
isAvailableForLookup()
bool LookupResult::isAvailableForLookup (Sema & SemaRef, NamedDecl * ND) static
Determine whether this lookup is permitted to see the declaration.
Note that a reachable but not visible declaration inhabiting a namespace is not allowed to be seen during name lookup.
For example:
// m.cppm
export module m;
struct reachable { int v; }
export auto func() { return reachable{43}; }
// Use.cpp
import m;
auto Use() {
  // Not valid. We couldn't see reachable here.
  // So isAvailableForLookup would return false when we look
  up 'reachable' here.
  // return reachable(43).v;
  // Valid. The field name 'v' is allowed during name lookup.
  // So isAvailableForLookup would return true when we look up 'v' here.
  return func().v;
}
Definition at line 2096 of file SemaLookup.cpp.
References clang::DeclarationName::getCXXDeductionGuideTemplate(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Sema::hasReachableDefinition(), clang::DeclContext::isFileContext(), and isVisible().
Referenced by findAcceptableDecl(), and getAcceptableDecl().
isClassLookup()
bool clang::LookupResult::isClassLookup () const inline
Returns whether these results arose from performing a lookup into a class.
Definition at line 409 of file Lookup.h.
Referenced by resolveAllocationOverload().
isForExternalRedeclaration()
bool clang::LookupResult::isForExternalRedeclaration () const inline
True if this lookup is just looking for an existing declaration to link against a declaration with external linkage.
Definition at line 264 of file Lookup.h.
Referenced by isHiddenDeclarationVisible().
isForRedeclaration()
bool clang::LookupResult::isForRedeclaration () const inline
True if this lookup is just looking for an existing declaration.
Definition at line 258 of file Lookup.h.
Referenced by clang::Sema::LookupBuiltin(), LookupDirect(), and clang::Sema::LookupQualifiedName().
isHiddenDeclarationVisible()
bool clang::LookupResult::isHiddenDeclarationVisible (NamedDecl * ND) const inline
Determine whether this lookup is permitted to see hidden declarations, such as those in modules that have not yet been imported.
Definition at line 281 of file Lookup.h.
References clang::NamedDecl::isExternallyDeclarable(), and isForExternalRedeclaration().
Referenced by getAcceptableDecl().
isOverloadedResult()
bool clang::LookupResult::isOverloadedResult () const inline
Determines if the results are overloaded.
Definition at line 313 of file Lookup.h.
References FoundOverloaded, and getResultKind().
Referenced by clang::Sema::ActOnIdExpression(), attemptRecovery(), clang::Sema::BuildDeclarationNameExpr(), and clang::Sema::BuildMemberReferenceExpr().
isReachable()
bool LookupResult::isReachable (Sema & SemaRef, NamedDecl * D) static
Definition at line 2089 of file SemaLookup.cpp.
References clang::Decl::isUnconditionallyVisible(), and clang::Sema::Reachable.
Referenced by isAcceptable().
isShadowed()
bool clang::LookupResult::isShadowed () const inline
Determine whether the lookup result was shadowed by some other declaration that lookup ignored.
Definition at line 485 of file Lookup.h.
isSingleResult()
bool clang::LookupResult::isSingleResult () const inline
Determines if this names a single result which is not an unresolved value using decl.
If so, it is safe to call getFoundDecl().
Definition at line 308 of file Lookup.h.
References Found, and getResultKind().
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartNamespaceDef(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildMemberReferenceExpr(), emitReplacement(), clang::Sema::FindFirstQualifierInScope(), clang::Sema::LookupInlineAsmField(), clang::Sema::LookupIvarInObjCMethod(), clang::Sema::lookupOpenMPDeclareTargetName(), LookupPotentialTypoResult(), clang::Sema::LookupTemplateName(), and ShouldLookupResultBeMultiVersionOverload().
isSingleTagDecl()
bool clang::LookupResult::isSingleTagDecl () const inline
Asks if the result is a single tag decl.
Definition at line 556 of file Lookup.h.
References Found, getFoundDecl(), getResultKind(), and clang::isa().
Referenced by LookupQualifiedNameInUsingDirectives().
isSuppressingDiagnostics()
bool clang::LookupResult::isSuppressingDiagnostics () const inline
Determines whether this lookup is suppressing diagnostics.
Definition at line 614 of file Lookup.h.
Referenced by clang::Sema::LookupTemplateName().
isTemplateNameLookup()
bool clang::LookupResult::isTemplateNameLookup () const inline
Definition at line 299 of file Lookup.h.
Referenced by clang::Sema::LookupQualifiedName().
isUnresolvableResult()
bool clang::LookupResult::isUnresolvableResult () const inline
Definition at line 317 of file Lookup.h.
References FoundUnresolvedValue, and getResultKind().
Referenced by clang::Sema::ActOnIdExpression(), attemptRecovery(), clang::Sema::BuildMemberReferenceExpr(), and ClassifyImplicitMemberAccess().
isVisible()
bool LookupResult::isVisible (Sema & SemaRef, NamedDecl * D) static
Determine whether the given declaration is visible to the program.
Definition at line 2079 of file SemaLookup.cpp.
References clang::Decl::isUnconditionallyVisible(), and clang::Sema::Visible.
Referenced by checkCorrectionVisibility(), findAcceptableDecl(), clang::TypoCorrectionConsumer::FoundDecl(), isAcceptable(), isAvailableForLookup(), and clang::Sema::MergeCXXFunctionDecl().
makeFilter()
Filter clang::LookupResult::makeFilter () inline
Create a filter for this result set.
Definition at line 708 of file Lookup.h.
Referenced by clang::Sema::ActOnOpenMPDeclareMapperDirective(), clang::Sema::ActOnOpenMPDeclareReductionDirectiveStart(), buildSingleCopyAssignRecursively(), clang::Sema::FilterAcceptableTemplateNames(), clang::Sema::FilterLookupForScope(), clang::Sema::FindAllocationFunctions(), clang::Sema::LookupLiteralOperator(), and RemoveUsingDecls().
operator=() [1/2]
LookupResult & clang::LookupResult::operator= (const LookupResult &) delete
operator=() [2/2]
LookupResult & clang::LookupResult::operator= (LookupResult && Other) inline
Definition at line 203 of file Lookup.h.
print()
void LookupResult::print (raw_ostream & Out)
Definition at line 663 of file SemaLookup.cpp.
References begin(), end(), and isAmbiguous().
redeclarationKind()
Sema::RedeclarationKind clang::LookupResult::redeclarationKind () const inline
Definition at line 268 of file Lookup.h.
References clang::Sema::ForExternalRedeclaration, clang::Sema::ForVisibleRedeclaration, and clang::Sema::NotForRedeclaration.
Referenced by LookupMemberExprInRecord().
resolveKind()
void LookupResult::resolveKind ()
Resolves the result kind of the lookup, possibly hiding decls.
Resolves the result kind of this lookup.
This should be called in any environment where lookup might generate multiple lookup results.
Definition at line 480 of file SemaLookup.cpp.
References Ambiguous, AmbiguousReference, canHideTag(), clang::cast(), clang::Sema::Context, clang::Sema::diagnoseEquivalentInternalLinkageDeclarations(), Found, FoundOverloaded, FoundUnresolvedValue, clang::Decl::getCanonicalDecl(), clang::ASTContext::getCanonicalType(), getContextForScopeMatching(), getLookupKind(), getNameLoc(), getSema(), clang::ASTContext::getTypeDeclType(), clang::NamedDecl::getUnderlyingDecl(), clang::Decl::isInvalidDecl(), isPreferredLookupResult(), N, NotFound, and NotFoundInCurrentInstantiation.
Referenced by clang::Sema::ActOnUsingDirective(), BuildImplicitMemberInitializer(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckImplicitSpecialMemberDeclaration(), CppNamespaceLookup(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), InsertOCLBuiltinDeclarationsFromTable(), clang::Sema::LookupInSuper(), clang::Sema::LookupName(), LookupPotentialTypoResult(), clang::Sema::LookupQualifiedName(), LookupQualifiedNameInUsingDirectives(), clang::TreeTransform< Derived >::RebuildMemberExpr(), resolveKindAfterFilter(), setAmbiguousBaseSubobjects(), setAmbiguousBaseSubobjectTypes(), and clang::TreeTransform< Derived >::TransformOverloadExprDecls().
resolveKindAfterFilter()
void clang::LookupResult::resolveKindAfterFilter () inline
Re-resolves the result kind of the lookup after a set of removals has been performed.
Definition at line 500 of file Lookup.h.
References Ambiguous, Found, NotFound, NotFoundInCurrentInstantiation, and resolveKind().
setAllowHidden()
void clang::LookupResult::setAllowHidden (bool AH) inline
Specify whether hidden declarations are visible, e.g., for recovery reasons.
Definition at line 275 of file Lookup.h.
Referenced by LookupPotentialTypoResult().
setAmbiguousBaseSubobjects()
void LookupResult::setAmbiguousBaseSubobjects (CXXBasePaths & P)
Make these results show that the name was found in distinct base classes of the same type.
The given paths object is copied and invalidated.
Definition at line 647 of file SemaLookup.cpp.
References AmbiguousBaseSubobjects, P, resolveKind(), and clang::CXXBasePaths::swap().
Referenced by clang::Sema::LookupQualifiedName().
setAmbiguousBaseSubobjectTypes()
void LookupResult::setAmbiguousBaseSubobjectTypes (CXXBasePaths & P)
Make these results show that the name was found in base classes of different types.
The given paths object is copied and invalidated.
Definition at line 655 of file SemaLookup.cpp.
References AmbiguousBaseSubobjectTypes, P, resolveKind(), and clang::CXXBasePaths::swap().
Referenced by clang::Sema::LookupQualifiedName().
setAmbiguousQualifiedTagHiding()
void clang::LookupResult::setAmbiguousQualifiedTagHiding () inline
Make these results show that the name was found in different contexts and a tag decl was hidden by an ordinary decl in a different context.
Definition at line 575 of file Lookup.h.
References AmbiguousTagHiding.
Referenced by LookupQualifiedNameInUsingDirectives().
setBaseObjectType()
void clang::LookupResult::setBaseObjectType (QualType T) inline
Sets the base object type for this lookup.
Definition at line 446 of file Lookup.h.
Referenced by clang::Sema::BuildMemberReferenceExpr(), and clang::Sema::BuildUsingDeclaration().
setContextRange()
void clang::LookupResult::setContextRange (SourceRange SR) inline
Sets a 'context' source range.
Definition at line 619 of file Lookup.h.
Referenced by clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::isNonTypeNestedNameSpecifier(), and clang::Sema::LookupParsedName().
setFindLocalExtern()
void clang::LookupResult::setFindLocalExtern (bool FindLocalExtern) inline
Definition at line 712 of file Lookup.h.
References clang::Decl::IDNS_LocalExtern.
setHideTags()
void clang::LookupResult::setHideTags (bool Hide) inline
Sets whether tag declarations should be hidden by non-tag declarations during resolution.
The default is true.
Definition at line 288 of file Lookup.h.
Referenced by clang::Sema::ActOnPragmaDump(), and clang::Sema::BuildUsingDeclaration().
setLookupName()
void clang::LookupResult::setLookupName (DeclarationName Name) inline
Sets the name to look up.
Definition at line 248 of file Lookup.h.
References clang::DeclarationNameInfo::setName().
Referenced by attemptRecovery(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildMemInitializer(), clang::Sema::DiagnoseEmptyLookup(), LookupPotentialTypoResult(), clang::Sema::LookupTemplateName(), and resolveAllocationOverload().
setLookupNameInfo()
void clang::LookupResult::setLookupNameInfo (const DeclarationNameInfo & NameInfo) inline
Sets the name info to look up.
Definition at line 238 of file Lookup.h.
setNamingClass()
void clang::LookupResult::setNamingClass (CXXRecordDecl * Record) inline
Sets the 'naming class' for this lookup.
Definition at line 434 of file Lookup.h.
Referenced by attemptRecovery(), clang::Sema::DiagnoseEmptyLookup(), clang::Sema::LookupInSuper(), and clang::Sema::LookupQualifiedName().
setNotFoundInCurrentInstantiation()
void clang::LookupResult::setNotFoundInCurrentInstantiation () inline
Note that while no result was found in the current instantiation, there were dependent base classes that could not be searched.
Definition at line 478 of file Lookup.h.
References NotFound, and NotFoundInCurrentInstantiation.
Referenced by clang::Sema::LookupParsedName(), and clang::Sema::LookupQualifiedName().
setRedeclarationKind()
void clang::LookupResult::setRedeclarationKind (Sema::RedeclarationKind RK) inline
Change this lookup's redeclaration kind.
Definition at line 598 of file Lookup.h.
References clang::Sema::ForExternalRedeclaration, and clang::Sema::NotForRedeclaration.
setShadowed()
void clang::LookupResult::setShadowed () inline
Note that we found and ignored a declaration while performing lookup.
Definition at line 489 of file Lookup.h.
Referenced by clang::Sema::LookupName().
setTemplateNameLookup()
void clang::LookupResult::setTemplateNameLookup (bool TemplateName) inline
Sets whether this is a template-name lookup.
For template-name lookups, injected-class-names are treated as naming a template rather than a template specialization.
Definition at line 295 of file Lookup.h.
Referenced by clang::Sema::LookupTemplateName().
suppressDiagnostics()
void clang::LookupResult::suppressDiagnostics () inline
Suppress the diagnostics that would normally fire because of this lookup.
This happens during (e.g.) redeclaration lookups.
Definition at line 609 of file Lookup.h.
Referenced by clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnPragmaDump(), clang::Sema::AddMemberOperatorCandidates(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildOverloadedArrowExpr(), BuildRecoveryCallExpr(), clang::Sema::BuildTemplateIdExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckImplicitSpecialMemberDeclaration(), clang::Sema::CheckMicrosoftIfExistsSymbol(), CXXRecordMembersNamed(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), doesUsualArrayDeleteWantSize(), emitReplacement(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindDeallocationFunction(), getTupleLikeElementType(), HasNoThrowOperator(), clang::Sema::isDeductionGuideName(), clang::Sema::isNonTypeNestedNameSpecifier(), clang::Sema::isTagName(), clang::Sema::isTemplateName(), clang::Sema::lookupCoroutineTraits(), lookupMember(), clang::Sema::lookupOpenMPDeclareTargetName(), LookupPotentialTypoResult(), clang::Sema::ProduceCallSignatureHelp(), resolveBuiltinNewDeleteOverload(), and clang::TypoCorrectionConsumer::TypoCorrectionConsumer().
wasNotFoundInCurrentInstantiation()
bool clang::LookupResult::wasNotFoundInCurrentInstantiation () const inline
Determine whether no result was found because we could not search into dependent base classes of the current instantiation.
Definition at line 472 of file Lookup.h.
References NotFoundInCurrentInstantiation.
Referenced by clang::Sema::LookupTemplateName().
The documentation for this class was generated from the following files:
include/clang/Sema/Lookup.h
lib/Sema/SemaLookup.cpp