clang: clang::threadSafety::CopyOnWriteVector< T > Class Template Reference
clang::threadSafety::CopyOnWriteVector< T > Class Template Reference
#include "clang/Analysis/Analyses/ThreadSafetyUtil.h"
Public Types
using const_iterator = typename std::vector<T>::const_iterator
Public Member Functions
CopyOnWriteVector ()=default
CopyOnWriteVector (CopyOnWriteVector &&V)
CopyOnWriteVector & operator= (CopyOnWriteVector &&V)
CopyOnWriteVector (const CopyOnWriteVector &)=delete
CopyOnWriteVector & operator= (const CopyOnWriteVector &)=delete
~CopyOnWriteVector ()
bool valid () const
bool writable () const
void init ()
void destroy ()
void makeWritable ()
CopyOnWriteVector clone ()
const std::vector< T > & elements () const
const_iterator begin () const
const_iterator end () const
const T & operator[] (unsigned i) const
unsigned size () const
bool sameAs (const CopyOnWriteVector &V) const
void clear ()
void push_back (const T &Elem)
T & elem (unsigned i)
void downsize (unsigned i)
Detailed Description
template<typename T>
class clang::threadSafety::CopyOnWriteVector< T >
Definition at line 235 of file ThreadSafetyUtil.h.
Member Typedef Documentation
const_iterator
template<typename T > using clang::threadSafety::CopyOnWriteVector< T >::const_iterator = typename std::vector<T>::const_iterator
Definition at line 301 of file ThreadSafetyUtil.h.
Constructor & Destructor Documentation
CopyOnWriteVector() [1/3]
template<typename T > clang::threadSafety::CopyOnWriteVector< T >::CopyOnWriteVector () default
Referenced by clang::threadSafety::CopyOnWriteVector< T >::clone().
CopyOnWriteVector() [2/3]
template<typename T > clang::threadSafety::CopyOnWriteVector< T >::CopyOnWriteVector (CopyOnWriteVector< T > && V) inline
Definition at line 247 of file ThreadSafetyUtil.h.
References V.
CopyOnWriteVector() [3/3]
template<typename T > clang::threadSafety::CopyOnWriteVector< T >::CopyOnWriteVector (const CopyOnWriteVector< T > &) delete
~CopyOnWriteVector()
template<typename T > clang::threadSafety::CopyOnWriteVector< T >::~CopyOnWriteVector () inline
Definition at line 260 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::destroy().
Member Function Documentation
begin()
template<typename T > const_iterator clang::threadSafety::CopyOnWriteVector< T >::begin () const inline
Definition at line 305 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::elements().
clear()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::clear () inline
Definition at line 316 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::writable().
clone()
template<typename T > CopyOnWriteVector clang::threadSafety::CopyOnWriteVector< T >::clone () inline
Definition at line 299 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::CopyOnWriteVector().
destroy()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::destroy () inline
Definition at line 276 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::CopyOnWriteVector< T >::operator=(), and clang::threadSafety::CopyOnWriteVector< T >::~CopyOnWriteVector().
downsize()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::downsize (unsigned i) inline
Definition at line 335 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::writable().
elem()
template<typename T > T & clang::threadSafety::CopyOnWriteVector< T >::elem (unsigned i) inline
Definition at line 329 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::writable().
elements()
template<typename T > const std::vector< T > & clang::threadSafety::CopyOnWriteVector< T >::elements () const inline
Definition at line 303 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::CopyOnWriteVector< T >::begin(), clang::threadSafety::CopyOnWriteVector< T >::end(), clang::threadSafety::CopyOnWriteVector< T >::operator[](), and clang::threadSafety::CopyOnWriteVector< T >::size().
end()
template<typename T > const_iterator clang::threadSafety::CopyOnWriteVector< T >::end () const inline
Definition at line 306 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::elements().
init()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::init () inline
Definition at line 269 of file ThreadSafetyUtil.h.
makeWritable()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::makeWritable () inline
Definition at line 287 of file ThreadSafetyUtil.h.
operator=() [1/2]
template<typename T > CopyOnWriteVector & clang::threadSafety::CopyOnWriteVector< T >::operator= (const CopyOnWriteVector< T > &) delete
operator=() [2/2]
template<typename T > CopyOnWriteVector & clang::threadSafety::CopyOnWriteVector< T >::operator= (CopyOnWriteVector< T > && V) inline
Definition at line 249 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::destroy(), and V.
operator[]()
template<typename T > const T & clang::threadSafety::CopyOnWriteVector< T >::operator[] (unsigned i) const inline
Definition at line 308 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::elements().
push_back()
template<typename T > void clang::threadSafety::CopyOnWriteVector< T >::push_back (const T & Elem) inline
Definition at line 322 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::writable().
sameAs()
template<typename T > bool clang::threadSafety::CopyOnWriteVector< T >::sameAs (const CopyOnWriteVector< T > & V) const inline
Definition at line 313 of file ThreadSafetyUtil.h.
References V.
size()
template<typename T > unsigned clang::threadSafety::CopyOnWriteVector< T >::size () const inline
Definition at line 310 of file ThreadSafetyUtil.h.
References clang::threadSafety::CopyOnWriteVector< T >::elements().
valid()
template<typename T > bool clang::threadSafety::CopyOnWriteVector< T >::valid () const inline
Definition at line 263 of file ThreadSafetyUtil.h.
writable()
template<typename T > bool clang::threadSafety::CopyOnWriteVector< T >::writable () const inline
Definition at line 266 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::CopyOnWriteVector< T >::clear(), clang::threadSafety::CopyOnWriteVector< T >::downsize(), clang::threadSafety::CopyOnWriteVector< T >::elem(), and clang::threadSafety::CopyOnWriteVector< T >::push_back().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyUtil.h