clang: clang::LambdaExpr Class Reference
clang::LambdaExpr Class Reference final
A C++ lambda expression, which produces a function object (of unspecified type) that can be invoked later.
#include "clang/AST/ExprCXX.h"
Public Types
using capture_iterator = const LambdaCapture *
An iterator that walks over the captures of the lambda, both implicit and explicit.
using capture_range = llvm::iterator_range<capture_iterator>
An iterator over a range of lambda captures.
using capture_init_iterator = Expr **
Iterator that walks over the capture initialization arguments.
using const_capture_init_iterator = Expr *const *
Const iterator that walks over the capture initialization arguments.
Public Types inherited from clang::Expr
enum LValueClassification {
LV_Valid , LV_NotObjectType , LV_IncompleteVoidType , LV_DuplicateVectorComponents ,
LV_InvalidExpression , LV_InvalidMessageExpression , LV_MemberFunction , LV_SubObjCPropertySetting ,
LV_ClassTemporary , LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid , MLV_NotObjectType , MLV_IncompleteVoidType , MLV_DuplicateVectorComponents ,
MLV_InvalidExpression , MLV_LValueCast , MLV_IncompleteType , MLV_ConstQualified ,
MLV_ConstQualifiedField , MLV_ConstAddrSpace , MLV_ArrayType , MLV_NoSetterProperty ,
MLV_MemberFunction , MLV_SubObjCPropertySetting , MLV_InvalidMessageExpression , MLV_ClassTemporary ,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects , SE_AllowUndefinedBehavior , SE_AllowSideEffects }
enum class ConstantExprKind { Normal , NonClassTemplateArgument , ClassTemplateArgument , ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0 , NPCK_ZeroExpression , NPCK_ZeroLiteral , NPCK_CXX11_nullptr ,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0 , NPC_ValueDependentIsNull , NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
LambdaCaptureDefault getCaptureDefault () const
Determine the default capture kind for this lambda.
SourceLocation getCaptureDefaultLoc () const
Retrieve the location of this lambda's capture-default, if any.
bool isInitCapture (const LambdaCapture *Capture) const
Determine whether one of this lambda's captures is an init-capture.
capture_range captures () const
Retrieve this lambda's captures.
capture_iterator capture_begin () const
Retrieve an iterator pointing to the first lambda capture.
capture_iterator capture_end () const
Retrieve an iterator pointing past the end of the sequence of lambda captures.
unsigned capture_size () const
Determine the number of captures in this lambda.
capture_range explicit_captures () const
Retrieve this lambda's explicit captures.
capture_iterator explicit_capture_begin () const
Retrieve an iterator pointing to the first explicit lambda capture.
capture_iterator explicit_capture_end () const
Retrieve an iterator pointing past the end of the sequence of explicit lambda captures.
capture_range implicit_captures () const
Retrieve this lambda's implicit captures.
capture_iterator implicit_capture_begin () const
Retrieve an iterator pointing to the first implicit lambda capture.
capture_iterator implicit_capture_end () const
Retrieve an iterator pointing past the end of the sequence of implicit lambda captures.
llvm::iterator_range< capture_init_iterator > capture_inits ()
Retrieve the initialization expressions for this lambda's captures.
llvm::iterator_range< const_capture_init_iterator > capture_inits () const
Retrieve the initialization expressions for this lambda's captures.
capture_init_iterator capture_init_begin ()
Retrieve the first initialization argument for this lambda expression (which initializes the first capture field).
const_capture_init_iterator capture_init_begin () const
Retrieve the first initialization argument for this lambda expression (which initializes the first capture field).
capture_init_iterator capture_init_end ()
Retrieve the iterator pointing one past the last initialization argument for this lambda expression.
const_capture_init_iterator capture_init_end () const
Retrieve the iterator pointing one past the last initialization argument for this lambda expression.
SourceRange getIntroducerRange () const
Retrieve the source range covering the lambda introducer, which contains the explicit capture list surrounded by square brackets ([...]).
CXXRecordDecl * getLambdaClass () const
Retrieve the class that corresponds to the lambda.
CXXMethodDecl * getCallOperator () const
Retrieve the function call operator associated with this lambda expression.
FunctionTemplateDecl * getDependentCallOperator () const
Retrieve the function template call operator associated with this lambda expression.
TemplateParameterList * getTemplateParameterList () const
If this is a generic lambda expression, retrieve the template parameter list associated with it, or else return null.
ArrayRef< NamedDecl * > getExplicitTemplateParameters () const
Get the template parameters were explicitly specified (as opposed to being invented by use of an auto parameter).
Expr * getTrailingRequiresClause () const
Get the trailing requires clause, if any.
bool isGenericLambda () const
Whether this is a generic lambda.
Stmt * getBody () const
Retrieve the body of the lambda.
const CompoundStmt * getCompoundStmtBody () const
Retrieve the CompoundStmt representing the body of the lambda.
CompoundStmt * getCompoundStmtBody ()
bool isMutable () const
Determine whether the lambda is mutable, meaning that any captures values can be modified.
bool hasExplicitParameters () const
Determine whether this lambda has an explicit parameter list vs.
bool hasExplicitResultType () const
Whether this lambda had its result type explicitly specified.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
Includes the captures and the body of the lambda.
const_child_range children () const
Public Member Functions inherited from clang::Expr
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
Optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr, bool isEvaluated=true) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisble AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parenthese and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static LambdaExpr * Create (const ASTContext &C, CXXRecordDecl *Class, SourceRange IntroducerRange, LambdaCaptureDefault CaptureDefault, SourceLocation CaptureDefaultLoc, bool ExplicitParams, bool ExplicitResultType, ArrayRef< Expr * > CaptureInits, SourceLocation ClosingBrace, bool ContainsUnexpandedParameterPack)
Construct a new lambda expression.
static LambdaExpr * CreateDeserialized (const ASTContext &C, unsigned NumCaptures)
Construct a new lambda expression that will be deserialized from an external source.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Expr
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluted - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Public Attributes
friend TrailingObjects
Public Attributes inherited from clang::Stmt
Friends
class ASTStmtReader
class ASTStmtWriter
Additional Inherited Members
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Expr
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
A C++ lambda expression, which produces a function object (of unspecified type) that can be invoked later.
Example:
void low_pass_filter(std::vector<double> &values, double cutoff) {
  values.erase(std::remove_if(values.begin(), values.end(),
                              [=](double value) { return value > cutoff; });
}
C++11 lambda expressions can capture local variables, either by copying the values of those local variables at the time the function object is constructed (not when it is called!) or by holding a reference to the local variable. These captures can occur either implicitly or can be written explicitly between the square brackets ([...]) that start the lambda expression.
C++1y introduces a new form of "capture" called an init-capture that includes an initializing expression (rather than capturing a variable), and which can never occur implicitly.
Definition at line 1865 of file ExprCXX.h.
Member Typedef Documentation
capture_init_iterator
using clang::LambdaExpr::capture_init_iterator = Expr **
Iterator that walks over the capture initialization arguments.
Definition at line 1973 of file ExprCXX.h.
capture_iterator
using clang::LambdaExpr::capture_iterator = const LambdaCapture *
An iterator that walks over the captures of the lambda, both implicit and explicit.
Definition at line 1931 of file ExprCXX.h.
capture_range
using clang::LambdaExpr::capture_range = llvm::iterator_range<capture_iterator>
An iterator over a range of lambda captures.
Definition at line 1934 of file ExprCXX.h.
const_capture_init_iterator
using clang::LambdaExpr::const_capture_init_iterator = Expr *const *
Const iterator that walks over the capture initialization arguments.
FIXME: This interface is prone to being used incorrectly.
Definition at line 1978 of file ExprCXX.h.
Member Function Documentation
capture_begin()
LambdaExpr::capture_iterator LambdaExpr::capture_begin () const
Retrieve an iterator pointing to the first lambda capture.
Definition at line 1218 of file ExprCXX.cpp.
References getLambdaClass().
Referenced by capture_end(), captures(), explicit_capture_begin(), and clang::TreeTransform< Derived >::SkipLambdaBody().
capture_end()
LambdaExpr::capture_iterator LambdaExpr::capture_end () const
Retrieve an iterator pointing past the end of the sequence of lambda captures.
Definition at line 1222 of file ExprCXX.cpp.
References capture_begin(), and capture_size().
Referenced by captures(), implicit_capture_end(), and clang::TreeTransform< Derived >::SkipLambdaBody().
capture_init_begin() [1/2]
capture_init_iterator clang::LambdaExpr::capture_init_begin () inline
Retrieve the first initialization argument for this lambda expression (which initializes the first capture field).
Definition at line 1992 of file ExprCXX.h.
Referenced by clang::Sema::canThrow(), capture_init_end(), capture_init_end(), capture_inits(), and capture_inits().
capture_init_begin() [2/2]
const_capture_init_iterator clang::LambdaExpr::capture_init_begin () const inline
Retrieve the first initialization argument for this lambda expression (which initializes the first capture field).
Definition at line 1998 of file ExprCXX.h.
capture_init_end() [1/2]
capture_init_iterator clang::LambdaExpr::capture_init_end () inline
Retrieve the iterator pointing one past the last initialization argument for this lambda expression.
Definition at line 2004 of file ExprCXX.h.
References capture_init_begin(), and capture_size().
Referenced by clang::Sema::canThrow(), capture_inits(), and capture_inits().
capture_init_end() [2/2]
const_capture_init_iterator clang::LambdaExpr::capture_init_end () const inline
Retrieve the iterator pointing one past the last initialization argument for this lambda expression.
Definition at line 2010 of file ExprCXX.h.
References capture_init_begin(), and capture_size().
capture_inits() [1/2]
llvm::iterator_range< capture_init_iterator > clang::LambdaExpr::capture_inits () inline
Retrieve the initialization expressions for this lambda's captures.
Definition at line 1981 of file ExprCXX.h.
References capture_init_begin(), and capture_init_end().
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
capture_inits() [2/2]
llvm::iterator_range< const_capture_init_iterator > clang::LambdaExpr::capture_inits () const inline
Retrieve the initialization expressions for this lambda's captures.
Definition at line 1986 of file ExprCXX.h.
References capture_init_begin(), and capture_init_end().
capture_size()
unsigned clang::LambdaExpr::capture_size () const inline
Determine the number of captures in this lambda.
Definition at line 1947 of file ExprCXX.h.
References clang::Stmt::LambdaExprBits.
Referenced by capture_end(), capture_init_end(), capture_init_end(), children(), children(), getBody(), and clang::ASTNodeImporter::VisitLambdaExpr().
captures()
LambdaExpr::capture_range LambdaExpr::captures () const
Retrieve this lambda's captures.
Definition at line 1226 of file ExprCXX.cpp.
References capture_begin(), and capture_end().
children() [1/2]
LambdaExpr::child_range LambdaExpr::children ()
Includes the captures and the body of the lambda.
Definition at line 1286 of file ExprCXX.cpp.
References capture_size().
children() [2/2]
LambdaExpr::const_child_range LambdaExpr::children () const
Definition at line 1291 of file ExprCXX.cpp.
References capture_size().
classof()
static bool clang::LambdaExpr::classof (const Stmt * T) inline static
Definition at line 2076 of file ExprCXX.h.
Create()
LambdaExpr * LambdaExpr::Create (const ASTContext & C, CXXRecordDecl * Class, SourceRange IntroducerRange, LambdaCaptureDefault CaptureDefault, SourceLocation CaptureDefaultLoc, bool ExplicitParams, bool ExplicitResultType, ArrayRef< Expr * > CaptureInits, SourceLocation ClosingBrace, bool ContainsUnexpandedParameterPack) static
Construct a new lambda expression.
Definition at line 1167 of file ExprCXX.cpp.
References clang::ASTContext::Allocate(), clang::ASTContext::getTypeDeclType(), and clang::LambdaExpr.
Referenced by clang::Sema::BuildLambdaExpr(), and clang::ASTNodeImporter::VisitLambdaExpr().
CreateDeserialized()
LambdaExpr * LambdaExpr::CreateDeserialized (const ASTContext & C, unsigned NumCaptures) static
Construct a new lambda expression that will be deserialized from an external source.
Definition at line 1187 of file ExprCXX.cpp.
References clang::C, and clang::LambdaExpr.
explicit_capture_begin()
LambdaExpr::capture_iterator LambdaExpr::explicit_capture_begin () const
Retrieve an iterator pointing to the first explicit lambda capture.
Definition at line 1230 of file ExprCXX.cpp.
References capture_begin().
Referenced by explicit_captures().
explicit_capture_end()
LambdaExpr::capture_iterator LambdaExpr::explicit_capture_end () const
Retrieve an iterator pointing past the end of the sequence of explicit lambda captures.
Definition at line 1234 of file ExprCXX.cpp.
References getLambdaClass().
Referenced by explicit_captures(), and implicit_capture_begin().
explicit_captures()
LambdaExpr::capture_range LambdaExpr::explicit_captures () const
Retrieve this lambda's explicit captures.
Definition at line 1240 of file ExprCXX.cpp.
References explicit_capture_begin(), and explicit_capture_end().
getBeginLoc()
SourceLocation clang::LambdaExpr::getBeginLoc () const inline
Definition at line 2080 of file ExprCXX.h.
getBody()
Stmt * LambdaExpr::getBody () const
Retrieve the body of the lambda.
This will be most of the time a CompoundStmt, but can also be CoroutineBodyStmt wrapping a CompoundStmt. Note that unlike functions, lambda-expressions cannot have a function-try-block.
Definition at line 1201 of file ExprCXX.cpp.
References capture_size().
Referenced by getCompoundStmtBody().
getCallOperator()
CXXMethodDecl * LambdaExpr::getCallOperator () const
Retrieve the function call operator associated with this lambda expression.
Definition at line 1260 of file ExprCXX.cpp.
References getLambdaClass().
Referenced by getTrailingRequiresClause(), isInitCapture(), isMutable(), and clang::ASTNodeImporter::VisitLambdaExpr().
getCaptureDefault()
LambdaCaptureDefault clang::LambdaExpr::getCaptureDefault () const inline
Determine the default capture kind for this lambda.
Definition at line 1919 of file ExprCXX.h.
References clang::Stmt::LambdaExprBits.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
getCaptureDefaultLoc()
SourceLocation clang::LambdaExpr::getCaptureDefaultLoc () const inline
Retrieve the location of this lambda's capture-default, if any.
Definition at line 1924 of file ExprCXX.h.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
getCompoundStmtBody() [1/2]
CompoundStmt * clang::LambdaExpr::getCompoundStmtBody () inline
Definition at line 2058 of file ExprCXX.h.
getCompoundStmtBody() [2/2]
const CompoundStmt * LambdaExpr::getCompoundStmtBody () const
Retrieve the CompoundStmt representing the body of the lambda.
This is a convenience function for callers who do not need to handle node(s) which may wrap a CompoundStmt.
Definition at line 1206 of file ExprCXX.cpp.
References clang::cast(), and getBody().
getDependentCallOperator()
FunctionTemplateDecl * LambdaExpr::getDependentCallOperator () const
Retrieve the function template call operator associated with this lambda expression.
Definition at line 1265 of file ExprCXX.cpp.
References getLambdaClass().
getEndLoc()
SourceLocation clang::LambdaExpr::getEndLoc () const inline
Definition at line 2084 of file ExprCXX.h.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
getExplicitTemplateParameters()
ArrayRef< NamedDecl * > LambdaExpr::getExplicitTemplateParameters () const
Get the template parameters were explicitly specified (as opposed to being invented by use of an auto parameter).
Definition at line 1275 of file ExprCXX.cpp.
References getLambdaClass().
getIntroducerRange()
SourceRange clang::LambdaExpr::getIntroducerRange () const inline
Retrieve the source range covering the lambda introducer, which contains the explicit capture list surrounded by square brackets ([...]).
Definition at line 2017 of file ExprCXX.h.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
getLambdaClass()
CXXRecordDecl * LambdaExpr::getLambdaClass () const
Retrieve the class that corresponds to the lambda.
This is the "closure type" (C++1y [expr.prim.lambda]), and stores the captures in its fields and provides the various operations permitted on a lambda (copying, calling).
Definition at line 1256 of file ExprCXX.cpp.
References clang::Type::getAsCXXRecordDecl(), and clang::Expr::getType().
Referenced by capture_begin(), explicit_capture_end(), getCallOperator(), getDependentCallOperator(), getExplicitTemplateParameters(), getTemplateParameterList(), and clang::ASTNodeImporter::VisitLambdaExpr().
getTemplateParameterList()
TemplateParameterList * LambdaExpr::getTemplateParameterList () const
If this is a generic lambda expression, retrieve the template parameter list associated with it, or else return null.
Definition at line 1270 of file ExprCXX.cpp.
References getLambdaClass().
Referenced by isGenericLambda().
getTrailingRequiresClause()
Expr * LambdaExpr::getTrailingRequiresClause () const
Get the trailing requires clause, if any.
Definition at line 1280 of file ExprCXX.cpp.
References getCallOperator(), and clang::DeclaratorDecl::getTrailingRequiresClause().
hasExplicitParameters()
bool clang::LambdaExpr::hasExplicitParameters () const inline
Determine whether this lambda has an explicit parameter list vs.
an implicit (empty) parameter list.
Definition at line 2069 of file ExprCXX.h.
References clang::Stmt::LambdaExprBits.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
hasExplicitResultType()
bool clang::LambdaExpr::hasExplicitResultType () const inline
Whether this lambda had its result type explicitly specified.
Definition at line 2072 of file ExprCXX.h.
References clang::Stmt::LambdaExprBits.
Referenced by clang::ASTNodeImporter::VisitLambdaExpr().
implicit_capture_begin()
LambdaExpr::capture_iterator LambdaExpr::implicit_capture_begin () const
Retrieve an iterator pointing to the first implicit lambda capture.
Definition at line 1244 of file ExprCXX.cpp.
References explicit_capture_end().
Referenced by implicit_captures().
implicit_capture_end()
LambdaExpr::capture_iterator LambdaExpr::implicit_capture_end () const
Retrieve an iterator pointing past the end of the sequence of implicit lambda captures.
Definition at line 1248 of file ExprCXX.cpp.
References capture_end().
Referenced by implicit_captures().
implicit_captures()
LambdaExpr::capture_range LambdaExpr::implicit_captures () const
Retrieve this lambda's implicit captures.
Definition at line 1252 of file ExprCXX.cpp.
References implicit_capture_begin(), and implicit_capture_end().
isGenericLambda()
bool clang::LambdaExpr::isGenericLambda () const inline
Whether this is a generic lambda.
Definition at line 2046 of file ExprCXX.h.
References getTemplateParameterList().
isInitCapture()
bool LambdaExpr::isInitCapture (const LambdaCapture * Capture) const
Determine whether one of this lambda's captures is an init-capture.
Definition at line 1213 of file ExprCXX.cpp.
References clang::C, getCallOperator(), and clang::Decl::getDeclContext().
Referenced by clang::TreeTransform< Derived >::SkipLambdaBody().
isMutable()
bool LambdaExpr::isMutable () const
Determine whether the lambda is mutable, meaning that any captures values can be modified.
Definition at line 1284 of file ExprCXX.cpp.
References getCallOperator(), and clang::CXXMethodDecl::isConst().
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 1901 of file ExprCXX.h.
ASTStmtWriter
friend class ASTStmtWriter friend
Definition at line 1902 of file ExprCXX.h.
Member Data Documentation
TrailingObjects
friend clang::LambdaExpr::TrailingObjects
Definition at line 1903 of file ExprCXX.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExprCXX.h
lib/AST/ExprCXX.cpp