clang: clang::PrintPreprocessedAction Class Reference
clang::PrintPreprocessedAction Class Reference
#include "clang/Frontend/FrontendActions.h"
Protected Member Functions
void ExecuteAction () override
Callback to run the program action, using the initialized compiler instance.
bool hasPCHSupport () const override
Does this action support use with PCH?
Protected Member Functions inherited from clang::PreprocessorFrontendAction
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Provide a default implementation which returns aborts; this method should never be called by FrontendAction clients.
Protected Member Functions inherited from clang::FrontendAction
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool BeginSourceFileAction (CompilerInstance &CI)
Callback at the start of processing a single input.
virtual void EndSourceFileAction ()
Callback at the end of processing a single input.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Additional Inherited Members
Public Member Functions inherited from clang::PreprocessorFrontendAction
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual TranslationUnitKind getTranslationUnitKind ()
For AST-based actions, the kind of translation unit we're handling.
virtual bool hasASTFileSupport () const
Does this action support use with AST files?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Detailed Description
Definition at line 306 of file FrontendActions.h.
Member Function Documentation
ExecuteAction()
void PrintPreprocessedAction::ExecuteAction () override protected virtual
Callback to run the program action, using the initialized compiler instance.
This is guaranteed to only be called between BeginSourceFileAction() and EndSourceFileAction().
Implements clang::FrontendAction.
Definition at line 1006 of file FrontendActions.cpp.
References clang::CompilerInstance::createDefaultOutputFile(), clang::DoPrintPreprocessedInput(), clang::FrontendAction::getCompilerInstance(), clang::FrontendAction::getCurrentFileOrBufferName(), clang::FrontendAction::getCurrentInput(), clang::FrontendAction::getCurrentModule(), clang::CompilerInstance::getPreprocessor(), clang::CompilerInstance::getPreprocessorOutputOpts(), clang::CompilerInstance::getSourceManager(), clang::InputKind::ModuleMap, clang::Module::print(), and SM.
hasPCHSupport()
bool clang::PrintPreprocessedAction::hasPCHSupport () const inline override protected virtual
Does this action support use with PCH?
Reimplemented from clang::FrontendAction.
Definition at line 310 of file FrontendActions.h.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendActions.h
lib/Frontend/FrontendActions.cpp