clang: clang::dataflow::TransferVisitor Class Reference
clang::dataflow::TransferVisitor Class Reference
Public Member Functions
TransferVisitor (const StmtToEnvMap &StmtToEnv, Environment &Env, TransferOptions Options)
void VisitBinaryOperator (const BinaryOperator *S)
void VisitDeclRefExpr (const DeclRefExpr *S)
void VisitDeclStmt (const DeclStmt *S)
void VisitImplicitCastExpr (const ImplicitCastExpr *S)
void VisitUnaryOperator (const UnaryOperator *S)
void VisitCXXThisExpr (const CXXThisExpr *S)
void VisitMemberExpr (const MemberExpr *S)
void VisitCXXDefaultInitExpr (const CXXDefaultInitExpr *S)
void VisitCXXConstructExpr (const CXXConstructExpr *S)
void VisitCXXOperatorCallExpr (const CXXOperatorCallExpr *S)
void VisitCXXFunctionalCastExpr (const CXXFunctionalCastExpr *S)
void VisitCXXTemporaryObjectExpr (const CXXTemporaryObjectExpr *S)
void VisitCallExpr (const CallExpr *S)
void VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *S)
void VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *S)
void VisitCXXStaticCastExpr (const CXXStaticCastExpr *S)
void VisitConditionalOperator (const ConditionalOperator *S)
void VisitInitListExpr (const InitListExpr *S)
void VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr *S)
void VisitParenExpr (const ParenExpr *S)
void VisitExprWithCleanups (const ExprWithCleanups *S)
Public Member Functions inherited from clang::StmtVisitorBase< llvm::make_const_ptr, TransferVisitor, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< llvm::make_const_ptr, TransferVisitor, void, ParamTys... >
ParamTys P
Detailed Description
Definition at line 49 of file Transfer.cpp.
Constructor & Destructor Documentation
TransferVisitor()
clang::dataflow::TransferVisitor::TransferVisitor (const StmtToEnvMap & StmtToEnv, Environment & Env, TransferOptions Options) inline
Definition at line 51 of file Transfer.cpp.
Member Function Documentation
VisitBinaryOperator()
void clang::dataflow::TransferVisitor::VisitBinaryOperator (const BinaryOperator * S) inline
Definition at line 55 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::evaluateBooleanEquality(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::makeAnd(), clang::dataflow::Environment::makeNot(), clang::dataflow::Environment::makeOr(), clang::dataflow::None, clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCallExpr()
void clang::dataflow::TransferVisitor::VisitCallExpr (const CallExpr * S) inline
Definition at line 483 of file Transfer.cpp.
References clang::dataflow::ControlFlowContext::build(), clang::dataflow::TransferOptions::ContextSensitive, clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, clang::dataflow::Environment::pushCall(), clang::dataflow::Reference, clang::dataflow::runDataflowAnalysis(), and clang::dataflow::Environment::setStorageLocation().
VisitConditionalOperator()
void clang::dataflow::TransferVisitor::VisitConditionalOperator (const ConditionalOperator * S) inline
Definition at line 576 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::createValue(), clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCXXBindTemporaryExpr()
void clang::dataflow::TransferVisitor::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * S) inline
Definition at line 552 of file Transfer.cpp.
References clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, and clang::dataflow::Environment::setStorageLocation().
VisitCXXBoolLiteralExpr()
void clang::dataflow::TransferVisitor::VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr * S) inline
Definition at line 613 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getBoolLiteralValue(), clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCXXConstructExpr()
void clang::dataflow::TransferVisitor::VisitCXXConstructExpr (const CXXConstructExpr * S) inline
Definition at line 400 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::createValue(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCXXDefaultInitExpr()
void clang::dataflow::TransferVisitor::VisitCXXDefaultInitExpr (const CXXDefaultInitExpr * S) inline
Definition at line 383 of file Transfer.cpp.
References clang::cast(), clang::dataflow::Environment::getThisPointeeStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::None, and clang::dataflow::Environment::setValue().
VisitCXXFunctionalCastExpr()
void clang::dataflow::TransferVisitor::VisitCXXFunctionalCastExpr (const CXXFunctionalCastExpr * S) inline
Definition at line 463 of file Transfer.cpp.
References clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, and clang::dataflow::Environment::setStorageLocation().
VisitCXXOperatorCallExpr()
void clang::dataflow::TransferVisitor::VisitCXXOperatorCallExpr (const CXXOperatorCallExpr * S) inline
Definition at line 430 of file Transfer.cpp.
References clang::dataflow::Environment::getStorageLocation(), clang::Expr::getType(), clang::Type::getUnqualifiedDesugaredType(), clang::dataflow::Environment::getValue(), clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCXXStaticCastExpr()
void clang::dataflow::TransferVisitor::VisitCXXStaticCastExpr (const CXXStaticCastExpr * S) inline
Definition at line 563 of file Transfer.cpp.
References clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, and clang::dataflow::Environment::setStorageLocation().
VisitCXXTemporaryObjectExpr()
void clang::dataflow::TransferVisitor::VisitCXXTemporaryObjectExpr (const CXXTemporaryObjectExpr * S) inline
Definition at line 476 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::createValue(), clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitCXXThisExpr()
void clang::dataflow::TransferVisitor::VisitCXXThisExpr (const CXXThisExpr * S) inline
Definition at line 322 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getThisPointeeStorageLocation(), clang::dataflow::Environment::setStorageLocation(), clang::dataflow::Environment::setValue(), and clang::dataflow::Environment::takeOwnership().
VisitDeclRefExpr()
void clang::dataflow::TransferVisitor::VisitDeclRefExpr (const DeclRefExpr * S) inline
Definition at line 111 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, clang::dataflow::Environment::setStorageLocation(), clang::dataflow::Environment::setValue(), and clang::dataflow::Environment::takeOwnership().
Referenced by VisitDeclStmt().
VisitDeclStmt()
void clang::dataflow::TransferVisitor::VisitDeclStmt (const DeclStmt * S) inline
Definition at line 127 of file Transfer.cpp.
References clang::cast(), clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::createValue(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::None, clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), clang::dataflow::Environment::setValue(), clang::dataflow::Environment::takeOwnership(), VisitDeclRefExpr(), and VisitMemberExpr().
VisitExprWithCleanups()
void clang::dataflow::TransferVisitor::VisitExprWithCleanups (const ExprWithCleanups * S) inline
Definition at line 628 of file Transfer.cpp.
References clang::StmtVisitorBase< llvm::make_const_ptr, TransferVisitor, void, ParamTys... >::Visit().
VisitImplicitCastExpr()
void clang::dataflow::TransferVisitor::VisitImplicitCastExpr (const ImplicitCastExpr * S) inline
Definition at line 203 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getOrCreateNullPointerValue(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::makeAtomicBoolValue(), clang::dataflow::None, clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitInitListExpr()
void clang::dataflow::TransferVisitor::VisitInitListExpr (const InitListExpr * S) inline
Definition at line 586 of file Transfer.cpp.
References clang::cast(), clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::createValue(), clang::RecordDecl::fields(), clang::Type::getAsRecordDecl(), clang::dataflow::Environment::getValue(), clang::Type::isStructureOrClassType(), clang::dataflow::None, clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
VisitMaterializeTemporaryExpr()
void clang::dataflow::TransferVisitor::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * S) inline
Definition at line 541 of file Transfer.cpp.
References clang::dataflow::Environment::getStorageLocation(), clang::dataflow::None, and clang::dataflow::Environment::setStorageLocation().
VisitMemberExpr()
void clang::dataflow::TransferVisitor::VisitMemberExpr (const MemberExpr * S) inline
Definition at line 335 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getStorageLocation(), clang::Member, clang::dataflow::None, clang::dataflow::ReferenceThenPointer, clang::dataflow::Environment::setStorageLocation(), clang::dataflow::Environment::setValue(), and clang::dataflow::Environment::takeOwnership().
Referenced by VisitDeclStmt().
VisitParenExpr()
void clang::dataflow::TransferVisitor::VisitParenExpr (const ParenExpr * S) inline
Definition at line 619 of file Transfer.cpp.
References clang::StmtVisitorBase< llvm::make_const_ptr, TransferVisitor, void, ParamTys... >::Visit().
VisitUnaryOperator()
void clang::dataflow::TransferVisitor::VisitUnaryOperator (const UnaryOperator * S) inline
Definition at line 272 of file Transfer.cpp.
References clang::dataflow::Environment::createStorageLocation(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::makeNot(), clang::dataflow::None, clang::dataflow::Reference, clang::dataflow::Environment::setStorageLocation(), clang::dataflow::Environment::setValue(), and clang::dataflow::Environment::takeOwnership().
The documentation for this class was generated from the following file:
lib/Analysis/FlowSensitive/Transfer.cpp