clang: clang::OMPVarListClause< T > Class Template Reference
clang::OMPVarListClause< T > Class Template Reference
This represents clauses with the list of variables like 'private', 'firstprivate', 'copyin', 'shared', or 'reduction' clauses in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Types
using varlist_iterator = MutableArrayRef<Expr *>::iterator
using varlist_const_iterator = ArrayRef<const Expr *>::iterator
using varlist_range = llvm::iterator_range<varlist_iterator>
using varlist_const_range = llvm::iterator_range<varlist_const_iterator>
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_iterator varlist_end ()
varlist_const_iterator varlist_begin () const
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Protected Member Functions
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Friends
class OMPClauseReader
Additional Inherited Members
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Detailed Description
template<class T>
class clang::OMPVarListClause< T >
This represents clauses with the list of variables like 'private', 'firstprivate', 'copyin', 'shared', or 'reduction' clauses in the '#pragma omp ...' directives.
Definition at line 192 of file OpenMPClause.h.
Member Typedef Documentation
varlist_const_iterator
template<class T > using clang::OMPVarListClause< T >::varlist_const_iterator = ArrayRef<const Expr *>::iterator
Definition at line 229 of file OpenMPClause.h.
varlist_const_range
template<class T > using clang::OMPVarListClause< T >::varlist_const_range = llvm::iterator_range<varlist_const_iterator>
Definition at line 231 of file OpenMPClause.h.
varlist_iterator
template<class T > using clang::OMPVarListClause< T >::varlist_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 228 of file OpenMPClause.h.
varlist_range
template<class T > using clang::OMPVarListClause< T >::varlist_range = llvm::iterator_range<varlist_iterator>
Definition at line 230 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPVarListClause()
template<class T > clang::OMPVarListClause< T >::OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N) inline protected
Build a clause with N variables.
Parameters
K Kind of the clause.
StartLoc Starting location of the clause (the clause keyword).
LParenLoc Location of '('.
EndLoc Ending location of the clause.
N Number of the variables in the clause.
Definition at line 209 of file OpenMPClause.h.
Member Function Documentation
getLParenLoc()
template<class T > SourceLocation clang::OMPVarListClause< T >::getLParenLoc () const inline
Returns the location of '('.
Definition at line 252 of file OpenMPClause.h.
Referenced by clang::Sema::ActOnOpenMPFlushDirective().
getVarRefs() [1/2]
template<class T > MutableArrayRef< Expr * > clang::OMPVarListClause< T >::getVarRefs () inline protected
Fetches list of variables associated with this clause.
Definition at line 214 of file OpenMPClause.h.
Referenced by clang::OMPVarListClause< T >::varlist_begin(), clang::OMPVarListClause< T >::varlist_begin(), clang::OMPVarListClause< T >::varlist_end(), and clang::OMPVarListClause< T >::varlist_end().
getVarRefs() [2/2]
template<class T > ArrayRef< const Expr * > clang::OMPVarListClause< T >::getVarRefs () const inline
Fetches list of all variables in the clause.
Definition at line 255 of file OpenMPClause.h.
setLParenLoc()
template<class T > void clang::OMPVarListClause< T >::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 249 of file OpenMPClause.h.
setVarRefs()
template<class T > void clang::OMPVarListClause< T >::setVarRefs (ArrayRef< Expr * > VL) inline protected
Sets the list of variables for this clause.
Definition at line 220 of file OpenMPClause.h.
Referenced by clang::OMPAlignedClause::Create(), clang::OMPAllocateClause::Create(), clang::OMPCopyinClause::Create(), clang::OMPCopyprivateClause::Create(), clang::OMPExclusiveClause::Create(), clang::OMPFirstprivateClause::Create(), clang::OMPFlushClause::Create(), clang::OMPFromClause::Create(), clang::OMPHasDeviceAddrClause::Create(), clang::OMPInclusiveClause::Create(), clang::OMPInReductionClause::Create(), clang::OMPIsDevicePtrClause::Create(), clang::OMPLastprivateClause::Create(), clang::OMPLinearClause::Create(), clang::OMPMapClause::Create(), clang::OMPNontemporalClause::Create(), clang::OMPPrivateClause::Create(), clang::OMPReductionClause::Create(), clang::OMPSharedClause::Create(), clang::OMPTaskReductionClause::Create(), clang::OMPToClause::Create(), clang::OMPUseDeviceAddrClause::Create(), and clang::OMPUseDevicePtrClause::Create().
varlist_begin() [1/2]
template<class T > varlist_iterator clang::OMPVarListClause< T >::varlist_begin () inline
Definition at line 243 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::getVarRefs().
Referenced by clang::OMPVarListClause< T >::varlists(), and clang::OMPVarListClause< T >::varlists().
varlist_begin() [2/2]
template<class T > varlist_const_iterator clang::OMPVarListClause< T >::varlist_begin () const inline
Definition at line 245 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::getVarRefs().
varlist_empty()
template<class T > bool clang::OMPVarListClause< T >::varlist_empty () const inline
Definition at line 234 of file OpenMPClause.h.
varlist_end() [1/2]
template<class T > varlist_iterator clang::OMPVarListClause< T >::varlist_end () inline
Definition at line 244 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::getVarRefs().
Referenced by clang::OMPVarListClause< T >::varlists(), and clang::OMPVarListClause< T >::varlists().
varlist_end() [2/2]
template<class T > varlist_const_iterator clang::OMPVarListClause< T >::varlist_end () const inline
Definition at line 246 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::getVarRefs().
varlist_size()
template<class T > unsigned clang::OMPVarListClause< T >::varlist_size () const inline
Definition at line 233 of file OpenMPClause.h.
varlists() [1/2]
template<class T > varlist_range clang::OMPVarListClause< T >::varlists () inline
Definition at line 236 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::varlist_begin(), and clang::OMPVarListClause< T >::varlist_end().
varlists() [2/2]
template<class T > varlist_const_range clang::OMPVarListClause< T >::varlists () const inline
Definition at line 239 of file OpenMPClause.h.
References clang::OMPVarListClause< T >::varlist_begin(), and clang::OMPVarListClause< T >::varlist_end().
Friends And Related Symbol Documentation
OMPClauseReader
template<class T > friend class OMPClauseReader friend
Definition at line 193 of file OpenMPClause.h.
The documentation for this class was generated from the following file:
include/clang/AST/OpenMPClause.h