clang: clang::CanProxyBase< T > Class Template Reference
clang::CanProxyBase< T > Class Template Reference
Base class of all canonical proxy types, which is responsible for storing the underlying canonical type and providing basic conversions.
#include "clang/AST/CanonicalType.h"
Public Member Functions
const T * getTypePtr () const
Retrieve the pointer to the underlying Type.
operator const T * () const
Implicit conversion to the underlying pointer.
template<typename U >
CanProxy< U > getAs () const
Try to convert the given canonical type to a specific structural type.
const CanProxyAdaptor< T > * operator-> () const
Retrieve the proxy-adaptor type.
Protected Attributes
CanQual< T > Stored
Detailed Description
template<typename T>
class clang::CanProxyBase< T >
Base class of all canonical proxy types, which is responsible for storing the underlying canonical type and providing basic conversions.
Definition at line 239 of file CanonicalType.h.
Member Function Documentation
getAs()
template<typename T > template<typename U > CanProxy< U > clang::CanProxyBase< T >::getAs () const inline
Try to convert the given canonical type to a specific structural type.
Definition at line 258 of file CanonicalType.h.
References clang::CanProxyBase< T >::getAs().
Referenced by clang::CanProxyBase< T >::getAs(), and clang::CanQual< typename >::getNonReferenceType().
getTypePtr()
template<typename T > const T * clang::CanProxyBase< T >::getTypePtr () const inline
Retrieve the pointer to the underlying Type.
Definition at line 245 of file CanonicalType.h.
References clang::CanQual< typename >::getTypePtr(), and clang::CanProxyBase< T >::Stored.
Referenced by clang::CanProxyAdaptor< FunctionProtoType >::LLVM_CLANG_CANPROXY_SIMPLE_ACCESSOR(), clang::CanProxyAdaptor< FunctionProtoType >::param_type_begin(), and clang::CanProxyAdaptor< FunctionProtoType >::param_type_end().
operator const T *()
template<typename T > clang::CanProxyBase< T >::operator const T * () const inline
Implicit conversion to the underlying pointer.
Also provides the ability to use canonical type proxies in a Boolean
if (CanQual<PointerType> Ptr = T->getAs<PointerType>()) { ... }
Definition at line 254 of file CanonicalType.h.
operator->()
template<typename T > const CanProxyAdaptor< T > * clang::CanProxyBase< T >::operator-> () const inline
Retrieve the proxy-adaptor type.
This arrow operator is used when CanProxyAdaptor has been specialized for the given type T. In that case, we reference members of the CanProxyAdaptor specialization. Otherwise, this operator will be hidden by the arrow operator in the primary CanProxyAdaptor template.
Definition at line 323 of file CanonicalType.h.
Member Data Documentation
Stored
template<typename T > CanQual<T> clang::CanProxyBase< T >::Stored protected
Definition at line 241 of file CanonicalType.h.
Referenced by clang::CanProxy< T >::CanProxy(), clang::CanQual< typename >::castAs(), clang::CanQual< typename >::getAs(), clang::CanProxyBase< T >::getTypePtr(), clang::CanQual< typename >::getUnqualifiedType(), and clang::CanProxy< T >::operator CanQual< T >().
The documentation for this class was generated from the following file:
include/clang/AST/CanonicalType.h