clang: clang::CodeGen::InstrProfStats Class Reference
clang::CodeGen::InstrProfStats Class Reference
This class records statistics on instrumentation based profiling.
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenModule.h"
Public Member Functions
InstrProfStats ()
void addVisited (bool MainFile)
Record that we've visited a function and whether or not that function was in the main source file.
void addMissing (bool MainFile)
Record that a function we've visited has no profile data.
void addMismatched (bool MainFile)
Record that a function we've visited has mismatched profile data.
bool hasDiagnostics ()
Whether or not the stats we've gathered indicate any potential problems.
void reportDiagnostics (DiagnosticsEngine &Diags, StringRef MainFile)
Report potential problems we've found to Diags.
Detailed Description
This class records statistics on instrumentation based profiling.
Definition at line 214 of file CodeGenModule.h.
Constructor & Destructor Documentation
InstrProfStats()
clang::CodeGen::InstrProfStats::InstrProfStats () inline
Definition at line 222 of file CodeGenModule.h.
Member Function Documentation
addMismatched()
void clang::CodeGen::InstrProfStats::addMismatched (bool MainFile) inline
Record that a function we've visited has mismatched profile data.
Definition at line 239 of file CodeGenModule.h.
addMissing()
void clang::CodeGen::InstrProfStats::addMissing (bool MainFile) inline
Record that a function we've visited has no profile data.
Definition at line 233 of file CodeGenModule.h.
addVisited()
void clang::CodeGen::InstrProfStats::addVisited (bool MainFile) inline
Record that we've visited a function and whether or not that function was in the main source file.
Definition at line 227 of file CodeGenModule.h.
hasDiagnostics()
bool clang::CodeGen::InstrProfStats::hasDiagnostics () inline
Whether or not the stats we've gathered indicate any potential problems.
Definition at line 241 of file CodeGenModule.h.
Referenced by clang::CodeGen::CodeGenModule::Release(), and reportDiagnostics().
reportDiagnostics()
void InstrProfStats::reportDiagnostics (DiagnosticsEngine & Diags, StringRef MainFile)
Report potential problems we've found to Diags.
Definition at line 463 of file CodeGenModule.cpp.
References hasDiagnostics(), and clang::DiagnosticsEngine::Report().
Referenced by clang::CodeGen::CodeGenModule::Release().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenModule.h
lib/CodeGen/CodeGenModule.cpp