clang: clang::CodeGen::CodeGenFunction::ParamValue Class Reference
clang::CodeGen::CodeGenFunction::ParamValue Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
bool isIndirect () const
llvm::Value * getAnyValue () const
llvm::Value * getDirectValue () const
Address getIndirectAddress () const
Static Public Member Functions
static ParamValue forDirect (llvm::Value *value)
static ParamValue forIndirect (Address addr)
Detailed Description
Definition at line 3139 of file CodeGenFunction.h.
Member Function Documentation
forDirect()
static ParamValue clang::CodeGen::CodeGenFunction::ParamValue::forDirect (llvm::Value * value) inline static
Definition at line 3146 of file CodeGenFunction.h.
forIndirect()
static ParamValue clang::CodeGen::CodeGenFunction::ParamValue::forIndirect (Address addr) inline static
Definition at line 3149 of file CodeGenFunction.h.
References clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::CharUnits::getQuantity(), and clang::CharUnits::isZero().
getAnyValue()
llvm::Value * clang::CodeGen::CodeGenFunction::ParamValue::getAnyValue () const inline
Definition at line 3156 of file CodeGenFunction.h.
getDirectValue()
llvm::Value * clang::CodeGen::CodeGenFunction::ParamValue::getDirectValue () const inline
Definition at line 3158 of file CodeGenFunction.h.
References isIndirect().
getIndirectAddress()
Address clang::CodeGen::CodeGenFunction::ParamValue::getIndirectAddress () const inline
Definition at line 3163 of file CodeGenFunction.h.
References clang::CharUnits::fromQuantity(), and isIndirect().
isIndirect()
bool clang::CodeGen::CodeGenFunction::ParamValue::isIndirect () const inline
Definition at line 3155 of file CodeGenFunction.h.
Referenced by getDirectValue(), and getIndirectAddress().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h