clang: clang::MSAsmStmt Class Reference
clang::MSAsmStmt Class Reference
This represents a Microsoft inline-assembly statement extension.
#include "clang/AST/Stmt.h"
Public Member Functions
MSAsmStmt (const ASTContext &C, SourceLocation asmloc, SourceLocation lbraceloc, bool issimple, bool isvolatile, ArrayRef< Token > asmtoks, unsigned numoutputs, unsigned numinputs, ArrayRef< StringRef > constraints, ArrayRef< Expr * > exprs, StringRef asmstr, ArrayRef< StringRef > clobbers, SourceLocation endloc)
MSAsmStmt (EmptyShell Empty)
Build an empty MS-style inline-assembly statement.
SourceLocation getLBraceLoc () const
void setLBraceLoc (SourceLocation L)
SourceLocation getEndLoc () const
void setEndLoc (SourceLocation L)
bool hasBraces () const
unsigned getNumAsmToks ()
Token * getAsmToks ()
StringRef getAsmString () const
std::string generateAsmString (const ASTContext &C) const
Assemble final IR asm string.
StringRef getOutputConstraint (unsigned i) const
Expr * getOutputExpr (unsigned i)
const Expr * getOutputExpr (unsigned i) const
StringRef getInputConstraint (unsigned i) const
Expr * getInputExpr (unsigned i)
void setInputExpr (unsigned i, Expr *E)
const Expr * getInputExpr (unsigned i) const
ArrayRef< StringRef > getAllConstraints () const
ArrayRef< StringRef > getClobbers () const
ArrayRef< Expr * > getAllExprs () const
StringRef getClobber (unsigned i) const
SourceLocation getBeginLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::AsmStmt
AsmStmt (StmtClass SC, EmptyShell Empty)
Build an empty inline-assembly statement.
SourceLocation getAsmLoc () const
void setAsmLoc (SourceLocation L)
bool isSimple () const
void setSimple (bool V)
bool isVolatile () const
void setVolatile (bool V)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
std::string generateAsmString (const ASTContext &C) const
Assemble final IR asm string.
unsigned getNumOutputs () const
StringRef getOutputConstraint (unsigned i) const
getOutputConstraint - Return the constraint string for the specified output operand.
bool isOutputPlusConstraint (unsigned i) const
isOutputPlusConstraint - Return true if the specified output constraint is a "+" constraint (which is both an input and an output) or false if it is an "=" constraint (just an output).
const Expr * getOutputExpr (unsigned i) const
unsigned getNumPlusOperands () const
getNumPlusOperands - Return the number of output operands that have a "+" constraint.
unsigned getNumInputs () const
StringRef getInputConstraint (unsigned i) const
getInputConstraint - Return the specified input constraint.
const Expr * getInputExpr (unsigned i) const
unsigned getNumClobbers () const
StringRef getClobber (unsigned i) const
inputs_iterator begin_inputs ()
inputs_iterator end_inputs ()
inputs_range inputs ()
const_inputs_iterator begin_inputs () const
const_inputs_iterator end_inputs () const
inputs_const_range inputs () const
outputs_iterator begin_outputs ()
outputs_iterator end_outputs ()
outputs_range outputs ()
const_outputs_iterator begin_outputs () const
const_outputs_iterator end_outputs () const
outputs_const_range outputs () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::AsmStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
Additional Inherited Members
Public Types inherited from clang::AsmStmt
using inputs_iterator = ExprIterator
using const_inputs_iterator = ConstExprIterator
using inputs_range = llvm::iterator_range<inputs_iterator>
using inputs_const_range = llvm::iterator_range<const_inputs_iterator>
using outputs_iterator = ExprIterator
using const_outputs_iterator = ConstExprIterator
using outputs_range = llvm::iterator_range<outputs_iterator>
using outputs_const_range = llvm::iterator_range<const_outputs_iterator>
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::AsmStmt
AsmStmt (StmtClass SC, SourceLocation asmloc, bool issimple, bool isvolatile, unsigned numoutputs, unsigned numinputs, unsigned numclobbers)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::AsmStmt
SourceLocation AsmLoc
bool IsSimple
True if the assembly statement does not have any input or output operands.
bool IsVolatile
If true, treat this inline assembly as having side effects.
unsigned NumOutputs
unsigned NumInputs
unsigned NumClobbers
Stmt ** Exprs = nullptr
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
This represents a Microsoft inline-assembly statement extension.
Definition at line 3257 of file Stmt.h.
Constructor & Destructor Documentation
MSAsmStmt() [1/2]
MSAsmStmt::MSAsmStmt (const ASTContext & C, SourceLocation asmloc, SourceLocation lbraceloc, bool issimple, bool isvolatile, ArrayRef< Token > asmtoks, unsigned numoutputs, unsigned numinputs, ArrayRef< StringRef > constraints, ArrayRef< Expr * > exprs, StringRef asmstr, ArrayRef< StringRef > clobbers, SourceLocation endloc)
Definition at line 871 of file Stmt.cpp.
References clang::C.
MSAsmStmt() [2/2]
clang::MSAsmStmt::MSAsmStmt (EmptyShell Empty) inline explicit
Build an empty MS-style inline-assembly statement.
Definition at line 3278 of file Stmt.h.
Member Function Documentation
children() [1/2]
child_range clang::MSAsmStmt::children () inline
Definition at line 3352 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
children() [2/2]
const_child_range clang::MSAsmStmt::children () const inline
Definition at line 3356 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
classof()
static bool clang::MSAsmStmt::classof (const Stmt * T) inline static
Definition at line 3348 of file Stmt.h.
generateAsmString()
std::string MSAsmStmt::generateAsmString (const ASTContext & C) const
Assemble final IR asm string.
Assemble final IR asm string (MS-style).
Definition at line 804 of file Stmt.cpp.
getAllConstraints()
ArrayRef< StringRef > clang::MSAsmStmt::getAllConstraints () const inline
Definition at line 3325 of file Stmt.h.
References clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
getAllExprs()
ArrayRef< Expr * > clang::MSAsmStmt::getAllExprs () const inline
Definition at line 3333 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
getAsmString()
StringRef clang::MSAsmStmt::getAsmString () const inline
Definition at line 3291 of file Stmt.h.
getAsmToks()
Token * clang::MSAsmStmt::getAsmToks () inline
Definition at line 3288 of file Stmt.h.
getBeginLoc()
SourceLocation clang::MSAsmStmt::getBeginLoc () const inline
Definition at line 3346 of file Stmt.h.
References clang::AsmStmt::AsmLoc.
getClobber()
StringRef clang::MSAsmStmt::getClobber (unsigned i) const inline
Definition at line 3338 of file Stmt.h.
References getClobbers().
getClobbers()
ArrayRef< StringRef > clang::MSAsmStmt::getClobbers () const inline
Definition at line 3329 of file Stmt.h.
References clang::AsmStmt::NumClobbers.
Referenced by getClobber().
getEndLoc()
SourceLocation clang::MSAsmStmt::getEndLoc () const inline
Definition at line 3282 of file Stmt.h.
getInputConstraint()
StringRef clang::MSAsmStmt::getInputConstraint (unsigned i) const inline
Definition at line 3311 of file Stmt.h.
References clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
getInputExpr() [1/2]
Expr * MSAsmStmt::getInputExpr (unsigned i)
Definition at line 833 of file Stmt.cpp.
References clang::cast(), clang::AsmStmt::Exprs, and clang::AsmStmt::NumOutputs.
Referenced by getInputExpr().
getInputExpr() [2/2]
const Expr * clang::MSAsmStmt::getInputExpr (unsigned i) const inline
Definition at line 3319 of file Stmt.h.
References getInputExpr().
getLBraceLoc()
SourceLocation clang::MSAsmStmt::getLBraceLoc () const inline
Definition at line 3280 of file Stmt.h.
getNumAsmToks()
unsigned clang::MSAsmStmt::getNumAsmToks () inline
Definition at line 3287 of file Stmt.h.
getOutputConstraint()
StringRef clang::MSAsmStmt::getOutputConstraint (unsigned i) const inline
Definition at line 3298 of file Stmt.h.
References clang::AsmStmt::NumOutputs.
getOutputExpr() [1/2]
Expr * MSAsmStmt::getOutputExpr (unsigned i)
Definition at line 829 of file Stmt.cpp.
References clang::cast(), and clang::AsmStmt::Exprs.
Referenced by getOutputExpr().
getOutputExpr() [2/2]
const Expr * clang::MSAsmStmt::getOutputExpr (unsigned i) const inline
Definition at line 3305 of file Stmt.h.
References getOutputExpr().
hasBraces()
bool clang::MSAsmStmt::hasBraces () const inline
Definition at line 3285 of file Stmt.h.
References clang::SourceLocation::isValid().
setEndLoc()
void clang::MSAsmStmt::setEndLoc (SourceLocation L) inline
Definition at line 3283 of file Stmt.h.
setInputExpr()
void MSAsmStmt::setInputExpr (unsigned i, Expr * E)
Definition at line 837 of file Stmt.cpp.
References clang::AsmStmt::Exprs, and clang::AsmStmt::NumOutputs.
setLBraceLoc()
void clang::MSAsmStmt::setLBraceLoc (SourceLocation L) inline
Definition at line 3281 of file Stmt.h.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 3258 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp