clang: clang::ast_matchers::dynamic::Parser Class Reference
clang::ast_matchers::dynamic::Parser Class Reference
Matcher expression parser.
#include "clang/ASTMatchers/Dynamic/Parser.h"
Classes
class CodeTokenizer
Simple tokenizer for the parser.
class RegistrySema
Sema implementation that uses the matcher registry to process the tokens.
struct ScopedContextEntry
class Sema
Interface to connect the parser with the registry and more.
struct TokenInfo
Simple structure to hold information for one token from the parser.
Public Types
using NamedValueMap = llvm::StringMap<VariantValue>
Static Public Member Functions
static llvm::Optional< DynTypedMatcher > parseMatcherExpression (StringRef &MatcherCode, Sema *S, const NamedValueMap *NamedValues, Diagnostics *Error)
Parse a matcher expression.
static llvm::Optional< DynTypedMatcher > parseMatcherExpression (StringRef &MatcherCode, Sema *S, Diagnostics *Error)
static llvm::Optional< DynTypedMatcher > parseMatcherExpression (StringRef &MatcherCode, Diagnostics *Error)
static bool parseExpression (StringRef &Code, Sema *S, const NamedValueMap *NamedValues, VariantValue *Value, Diagnostics *Error)
Parse an expression.
static bool parseExpression (StringRef &Code, Sema *S, VariantValue *Value, Diagnostics *Error)
static bool parseExpression (StringRef &Code, VariantValue *Value, Diagnostics *Error)
static std::vector< MatcherCompletion > completeExpression (StringRef &Code, unsigned CompletionOffset, Sema *S, const NamedValueMap *NamedValues)
Complete an expression at the given offset.
static std::vector< MatcherCompletion > completeExpression (StringRef &Code, unsigned CompletionOffset, Sema *S)
static std::vector< MatcherCompletion > completeExpression (StringRef &Code, unsigned CompletionOffset)
Detailed Description
Matcher expression parser.
Definition at line 55 of file Parser.h.
Member Typedef Documentation
NamedValueMap
using clang::ast_matchers::dynamic::Parser::NamedValueMap = llvm::StringMap<VariantValue>
Definition at line 166 of file Parser.h.
Member Function Documentation
completeExpression() [1/3]
static std::vector< MatcherCompletion > clang::ast_matchers::dynamic::Parser::completeExpression (StringRef & Code, unsigned CompletionOffset) inline static
Definition at line 238 of file Parser.h.
References completeExpression().
completeExpression() [2/3]
static std::vector< MatcherCompletion > clang::ast_matchers::dynamic::Parser::completeExpression (StringRef & Code, unsigned CompletionOffset, Sema * S) inline static
Definition at line 234 of file Parser.h.
References completeExpression().
completeExpression() [3/3]
std::vector< MatcherCompletion > clang::ast_matchers::dynamic::Parser::completeExpression (StringRef & Code, unsigned CompletionOffset, Sema * S, const NamedValueMap * NamedValues) static
Complete an expression at the given offset.
Parameters
S The Sema instance that will help the parser construct the matchers. If null, it uses the default registry.
NamedValues A map of precomputed named values. This provides the dictionary for the <NamedValue> rule of the grammar. If null, it is ignored.
Returns
The list of completions, which may be empty if there are no available completions or if an error occurred.
Definition at line 888 of file Parser.cpp.
References clang::Error, and P.
Referenced by completeExpression(), and completeExpression().
parseExpression() [1/3]
bool clang::ast_matchers::dynamic::Parser::parseExpression (StringRef & Code, Sema * S, const NamedValueMap * NamedValues, VariantValue * Value, Diagnostics * Error) static
Parse an expression.
Parses any expression supported by this parser. In general, the parseMatcherExpression function is a better approach to get a matcher object.
Parameters
S The Sema instance that will help the parser construct the matchers. If null, it uses the default registry.
NamedValues A map of precomputed named values. This provides the dictionary for the <NamedValue> rule of the grammar. If null, it is ignored.
Definition at line 872 of file Parser.cpp.
Referenced by parseExpression(), and parseExpression().
parseExpression() [2/3]
static bool clang::ast_matchers::dynamic::Parser::parseExpression (StringRef & Code, Sema * S, VariantValue * Value, Diagnostics * Error) inline static
Definition at line 210 of file Parser.h.
References parseExpression().
parseExpression() [3/3]
static bool clang::ast_matchers::dynamic::Parser::parseExpression (StringRef & Code, VariantValue * Value, Diagnostics * Error) inline static
Definition at line 214 of file Parser.h.
References parseExpression().
parseMatcherExpression() [1/3]
static llvm::Optional< DynTypedMatcher > clang::ast_matchers::dynamic::Parser::parseMatcherExpression (StringRef & MatcherCode, Diagnostics * Error) inline static
Definition at line 191 of file Parser.h.
References parseMatcherExpression().
parseMatcherExpression() [2/3]
llvm::Optional< DynTypedMatcher > clang::ast_matchers::dynamic::Parser::parseMatcherExpression (StringRef & MatcherCode, Sema * S, const NamedValueMap * NamedValues, Diagnostics * Error) static
Parse a matcher expression.
Parameters
MatcherCode The matcher expression to parse.
S The Sema instance that will help the parser construct the matchers. If null, it uses the default registry.
NamedValues A map of precomputed named values. This provides the dictionary for the <NamedValue> rule of the grammar. If null, it is ignored.
Returns
The matcher object constructed by the processor, or an empty Optional if an error occurred. In that case, Error will contain a description of the error. The caller takes ownership of the DynTypedMatcher object returned.
Definition at line 908 of file Parser.cpp.
References clang::Result.
Referenced by parseMatcherExpression(), and parseMatcherExpression().
parseMatcherExpression() [3/3]
static llvm::Optional< DynTypedMatcher > clang::ast_matchers::dynamic::Parser::parseMatcherExpression (StringRef & MatcherCode, Sema * S, Diagnostics * Error) inline static
Definition at line 187 of file Parser.h.
References parseMatcherExpression().
The documentation for this class was generated from the following files:
include/clang/ASTMatchers/Dynamic/Parser.h
lib/ASTMatchers/Dynamic/Parser.cpp