clang: clang::ParsedAttributesView Class Reference
clang::ParsedAttributesView Class Reference
#include "clang/Sema/ParsedAttr.h"
Classes
struct const_iterator
struct iterator
Public Member Functions
bool empty () const
SizeType size () const
ParsedAttr & operator[] (SizeType pos)
const ParsedAttr & operator[] (SizeType pos) const
void addAtEnd (ParsedAttr *newAttr)
void remove (ParsedAttr *ToBeRemoved)
void clearListOnly ()
void addAll (iterator B, iterator E)
void addAll (const_iterator B, const_iterator E)
void addAllAtEnd (iterator B, iterator E)
void addAllAtEnd (const_iterator B, const_iterator E)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
ParsedAttr & front ()
const ParsedAttr & front () const
ParsedAttr & back ()
const ParsedAttr & back () const
bool hasAttribute (ParsedAttr::Kind K) const
Static Public Member Functions
static const ParsedAttributesView & none ()
Public Attributes
SourceRange Range
Detailed Description
Definition at line 909 of file ParsedAttr.h.
Member Function Documentation
addAll() [1/2]
void clang::ParsedAttributesView::addAll (const_iterator B, const_iterator E) inline
Definition at line 962 of file ParsedAttr.h.
addAll() [2/2]
void clang::ParsedAttributesView::addAll (iterator B, iterator E) inline
Definition at line 958 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), and clang::ParsedAttributes::takeAllFrom().
addAllAtEnd() [1/2]
void clang::ParsedAttributesView::addAllAtEnd (const_iterator B, const_iterator E) inline
Definition at line 970 of file ParsedAttr.h.
addAllAtEnd() [2/2]
void clang::ParsedAttributesView::addAllAtEnd (iterator B, iterator E) inline
Definition at line 966 of file ParsedAttr.h.
addAtEnd()
void clang::ParsedAttributesView::addAtEnd (ParsedAttr * newAttr) inline
Definition at line 926 of file ParsedAttr.h.
Referenced by addContextSensitiveTypeNullability(), clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNewPropertyAttr(), clang::ParsedAttributes::addNewTypeAttr(), clang::ParsedAttributes::addNewTypeTagForDatatype(), clang::Sema::AddPragmaAttributes(), ConvertDeclSpecToType(), GetFullTypeForDeclarator(), moveAttrFromListToList(), clang::Sema::ProcessDeclAttributes(), takeDeclAttributes(), clang::ParsedAttributes::takeOneFrom(), and transferARCOwnershipToDeclaratorChunk().
back() [1/2]
ParsedAttr & clang::ParsedAttributesView::back () inline
Definition at line 987 of file ParsedAttr.h.
References empty().
back() [2/2]
const ParsedAttr & clang::ParsedAttributesView::back () const inline
Definition at line 991 of file ParsedAttr.h.
References empty().
begin() [1/2]
iterator clang::ParsedAttributesView::begin () inline
Definition at line 974 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), clang::Sema::ProcessDeclAttributeList(), and clang::ParsedAttributes::takeAllFrom().
begin() [2/2]
const_iterator clang::ParsedAttributesView::begin () const inline
Definition at line 975 of file ParsedAttr.h.
clearListOnly()
void clang::ParsedAttributesView::clearListOnly () inline
Definition at line 937 of file ParsedAttr.h.
Referenced by clang::ParsedAttributes::clear(), and clang::ParsedAttributes::takeAllFrom().
empty()
bool clang::ParsedAttributesView::empty () const inline
Definition at line 921 of file ParsedAttr.h.
Referenced by clang::Sema::ActOnTag(), back(), back(), clang::Sema::BuildAnonymousStructOrUnion(), front(), front(), clang::DeclSpec::hasAttributes(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ProcessDeclAttributeList(), clang::Sema::ProcessDeclAttributes(), processTypeAttrs(), and takeDeclAttributes().
end() [1/2]
iterator clang::ParsedAttributesView::end () inline
Definition at line 976 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), getMSPropertyAttr(), and clang::ParsedAttributes::takeAllFrom().
end() [2/2]
const_iterator clang::ParsedAttributesView::end () const inline
Definition at line 977 of file ParsedAttr.h.
front() [1/2]
ParsedAttr & clang::ParsedAttributesView::front () inline
Definition at line 979 of file ParsedAttr.h.
References empty().
front() [2/2]
const ParsedAttr & clang::ParsedAttributesView::front () const inline
Definition at line 983 of file ParsedAttr.h.
References empty().
hasAttribute()
bool clang::ParsedAttributesView::hasAttribute (ParsedAttr::Kind K) const inline
Definition at line 996 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind().
Referenced by clang::Sema::ActOnUsingDeclaration(), GetFullTypeForDeclarator(), hasParsedAttr(), and transferARCOwnershipToDeclaratorChunk().
none()
static const ParsedAttributesView & clang::ParsedAttributesView::none () inline static
Definition at line 916 of file ParsedAttr.h.
Referenced by clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::ActOnFinishKNRParamDeclarations(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildMicrosoftCAnonymousStruct(), clang::Sema::ImplicitlyDefineFunction(), and clang::Parser::ParseTypeName().
operator[]() [1/2]
ParsedAttr & clang::ParsedAttributesView::operator[] (SizeType pos) inline
Definition at line 923 of file ParsedAttr.h.
operator[]() [2/2]
const ParsedAttr & clang::ParsedAttributesView::operator[] (SizeType pos) const inline
Definition at line 924 of file ParsedAttr.h.
remove()
void clang::ParsedAttributesView::remove (ParsedAttr * ToBeRemoved) inline
Definition at line 931 of file ParsedAttr.h.
Referenced by checkOmittedBlockReturnType(), distributeFunctionTypeAttrFromDeclarator(), distributeObjCPointerTypeAttrFromDeclarator(), moveAttrFromListToList(), takeDeclAttributes(), and clang::ParsedAttributes::takeOneFrom().
size()
SizeType clang::ParsedAttributesView::size () const inline
Definition at line 922 of file ParsedAttr.h.
Referenced by clang::DeclaratorChunk::getFunction(), and clang::DeclaratorChunk::FunctionTypeInfo::hasMethodTypeQualifiers().
Member Data Documentation
Range
SourceRange clang::ParsedAttributesView::Range
Definition at line 914 of file ParsedAttr.h.
Referenced by clang::Sema::ActOnAttributedStmt(), clang::Sema::ActOnCXXForRangeIdentifier(), clang::ParsedAttributes::clear(), clang::Sema::ProcessStmtAttributes(), clang::takeAndConcatenateAttrs(), and clang::Declarator::takeAttributes().
The documentation for this class was generated from the following file:
include/clang/Sema/ParsedAttr.h