clang: clang::CaseStmt Class Reference
clang::CaseStmt Class Reference final
CaseStmt - Represent a case statement.
#include "clang/AST/Stmt.h"
Public Member Functions
bool caseStmtIsGNURange () const
True if this case statement is of the form case LHS ... RHS, which is a GNU extension.
SourceLocation getCaseLoc () const
void setCaseLoc (SourceLocation L)
SourceLocation getEllipsisLoc () const
Get the location of the ... in a case statement of the form LHS ... RHS.
void setEllipsisLoc (SourceLocation L)
Set the location of the ... in a case statement of the form LHS ... RHS.
Expr * getLHS ()
const Expr * getLHS () const
void setLHS (Expr *Val)
Expr * getRHS ()
const Expr * getRHS () const
void setRHS (Expr *Val)
Stmt * getSubStmt ()
const Stmt * getSubStmt () const
void setSubStmt (Stmt *S)
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::SwitchCase
const SwitchCase * getNextSwitchCase () const
SwitchCase * getNextSwitchCase ()
void setNextSwitchCase (SwitchCase *SC)
SourceLocation getKeywordLoc () const
void setKeywordLoc (SourceLocation L)
SourceLocation getColonLoc () const
void setColonLoc (SourceLocation L)
Stmt * getSubStmt ()
const Stmt * getSubStmt () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CaseStmt * Create (const ASTContext &Ctx, Expr *lhs, Expr *rhs, SourceLocation caseLoc, SourceLocation ellipsisLoc, SourceLocation colonLoc)
Build a case statement.
static CaseStmt * CreateEmpty (const ASTContext &Ctx, bool CaseStmtIsGNURange)
Build an empty case statement.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::SwitchCase
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::SwitchCase
SwitchCase (StmtClass SC, SourceLocation KWLoc, SourceLocation ColonLoc)
SwitchCase (StmtClass SC, EmptyShell)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::SwitchCase
SourceLocation ColonLoc
The location of the ":".
SwitchCase * NextSwitchCase = nullptr
A pointer to the following CaseStmt or DefaultStmt class, used by SwitchStmt.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
CaseStmt - Represent a case statement.
It can optionally be a GNU case statement of the form LHS ... RHS representing a range of cases.
Definition at line 1599 of file Stmt.h.
Member Function Documentation
caseStmtIsGNURange()
bool clang::CaseStmt::caseStmtIsGNURange () const inline
True if this case statement is of the form case LHS ... RHS, which is a GNU extension.
In this case the RHS can be obtained with getRHS() and the location of the ellipsis can be obtained with getEllipsisLoc().
Definition at line 1668 of file Stmt.h.
References clang::Stmt::SwitchCaseBits.
Referenced by getEllipsisLoc(), getRHS(), getRHS(), setEllipsisLoc(), setRHS(), and clang::JSONNodeDumper::VisitCaseStmt().
children() [1/2]
child_range clang::CaseStmt::children () inline
Definition at line 1742 of file Stmt.h.
children() [2/2]
const_child_range clang::CaseStmt::children () const inline
Definition at line 1748 of file Stmt.h.
classof()
static bool clang::CaseStmt::classof (const Stmt * T) inline static
Definition at line 1737 of file Stmt.h.
Create()
CaseStmt * CaseStmt::Create (const ASTContext & Ctx, Expr * lhs, Expr * rhs, SourceLocation caseLoc, SourceLocation ellipsisLoc, SourceLocation colonLoc) static
Build a case statement.
Definition at line 1217 of file Stmt.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::Sema::ActOnCaseStmt(), and clang::ASTNodeImporter::VisitCaseStmt().
CreateEmpty()
CaseStmt * CaseStmt::CreateEmpty (const ASTContext & Ctx, bool CaseStmtIsGNURange) static
Build an empty case statement.
Definition at line 1228 of file Stmt.cpp.
References clang::ASTContext::Allocate().
getBeginLoc()
SourceLocation clang::CaseStmt::getBeginLoc () const inline
Definition at line 1727 of file Stmt.h.
References clang::SwitchCase::getKeywordLoc().
getCaseLoc()
SourceLocation clang::CaseStmt::getCaseLoc () const inline
Definition at line 1670 of file Stmt.h.
References clang::SwitchCase::getKeywordLoc().
getEllipsisLoc()
SourceLocation clang::CaseStmt::getEllipsisLoc () const inline
Get the location of the ... in a case statement of the form LHS ... RHS.
Definition at line 1674 of file Stmt.h.
References caseStmtIsGNURange().
getEndLoc()
SourceLocation clang::CaseStmt::getEndLoc () const inline
Definition at line 1728 of file Stmt.h.
References clang::Stmt::getEndLoc(), and getSubStmt().
getLHS() [1/2]
Expr * clang::CaseStmt::getLHS () inline
Definition at line 1688 of file Stmt.h.
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::CodeCompleteCase(), EvaluateSwitch(), FindCaseStatementsForValue(), clang::ento::ExprEngine::processSwitch(), and shouldAddCase().
getLHS() [2/2]
const Expr * clang::CaseStmt::getLHS () const inline
Definition at line 1692 of file Stmt.h.
getRHS() [1/2]
Expr * clang::CaseStmt::getRHS () inline
Definition at line 1700 of file Stmt.h.
References caseStmtIsGNURange().
Referenced by clang::Sema::ActOnFinishSwitchStmt(), EvaluateSwitch(), FindCaseStatementsForValue(), clang::ento::ExprEngine::processSwitch(), and shouldAddCase().
getRHS() [2/2]
const Expr * clang::CaseStmt::getRHS () const inline
Definition at line 1706 of file Stmt.h.
References caseStmtIsGNURange().
getSubStmt() [1/2]
Stmt * clang::CaseStmt::getSubStmt () inline
Definition at line 1718 of file Stmt.h.
Referenced by getEndLoc().
getSubStmt() [2/2]
const Stmt * clang::CaseStmt::getSubStmt () const inline
Definition at line 1719 of file Stmt.h.
setCaseLoc()
void clang::CaseStmt::setCaseLoc (SourceLocation L) inline
Definition at line 1671 of file Stmt.h.
References clang::SwitchCase::setKeywordLoc().
setEllipsisLoc()
void clang::CaseStmt::setEllipsisLoc (SourceLocation L) inline
Set the location of the ... in a case statement of the form LHS ... RHS.
Assert that this case statement is of this form.
Definition at line 1681 of file Stmt.h.
References caseStmtIsGNURange().
setLHS()
void clang::CaseStmt::setLHS (Expr * Val) inline
Definition at line 1696 of file Stmt.h.
setRHS()
void clang::CaseStmt::setRHS (Expr * Val) inline
Definition at line 1712 of file Stmt.h.
References caseStmtIsGNURange().
setSubStmt()
void clang::CaseStmt::setSubStmt (Stmt * S) inline
Definition at line 1723 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp