clang: clang::TypeLocBuilder Class Reference
clang::TypeLocBuilder Class Reference
#include "/root/llvm-project/clang/lib/Sema/TypeLocBuilder.h"
Public Member Functions
TypeLocBuilder ()
~TypeLocBuilder ()
void reserve (size_t Requested)
Ensures that this buffer has at least as much capacity as described.
void pushFullCopy (TypeLoc L)
Pushes a copy of the given TypeLoc onto this builder.
TypeSpecTypeLoc pushTypeSpec (QualType T)
Pushes space for a typespec TypeLoc.
void clear ()
Resets this builder to the newly-initialized state.
void TypeWasModifiedSafely (QualType T)
Tell the TypeLocBuilder that the type it is storing has been modified in some safe way that doesn't affect type-location information.
template<class TyLocType >
TyLocType push (QualType T)
Pushes space for a new TypeLoc of the given type.
TypeSourceInfo * getTypeSourceInfo (ASTContext &Context, QualType T)
Creates a TypeSourceInfo for the given type.
TypeLoc getTypeLocInContext (ASTContext &Context, QualType T)
Copies the type-location information to the given AST context and returns a TypeLoc referring into the AST context.
Detailed Description
Definition at line 22 of file TypeLocBuilder.h.
Constructor & Destructor Documentation
TypeLocBuilder()
clang::TypeLocBuilder::TypeLocBuilder () inline
Definition at line 46 of file TypeLocBuilder.h.
~TypeLocBuilder()
clang::TypeLocBuilder::~TypeLocBuilder () inline
Definition at line 50 of file TypeLocBuilder.h.
Member Function Documentation
clear()
void clang::TypeLocBuilder::clear () inline
Resets this builder to the newly-initialized state.
Definition at line 75 of file TypeLocBuilder.h.
getTypeLocInContext()
TypeLoc clang::TypeLocBuilder::getTypeLocInContext (ASTContext & Context, QualType T) inline
Copies the type-location information to the given AST context and returns a TypeLoc referring into the AST context.
Definition at line 114 of file TypeLocBuilder.h.
References memcpy().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), and clang::Sema::BuildCXXNestedNameSpecifier().
getTypeSourceInfo()
TypeSourceInfo * clang::TypeLocBuilder::getTypeSourceInfo (ASTContext & Context, QualType T) inline
Creates a TypeSourceInfo for the given type.
Definition at line 101 of file TypeLocBuilder.h.
References clang::TypeLoc::getOpaqueData(), clang::TypeSourceInfo::getTypeLoc(), and memcpy().
Referenced by clang::Sema::ActOnDependentTag(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::buildLambdaInitCaptureInitialization(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckTemplateTypeArgument(), GetFullTypeForDeclarator(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::Sema::SubstFunctionDeclType(), clang::Sema::SubstType(), clang::TreeTransform< Derived >::TransformType(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
push()
template<class TyLocType > TyLocType clang::TypeLocBuilder::push (QualType T) inline
Pushes space for a new TypeLoc of the given type.
Invalidates any TypeLocs previously retrieved from this builder.
Definition at line 93 of file TypeLocBuilder.h.
References clang::TypeLoc::castAs().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnDependentTag(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::buildLambdaInitCaptureInitialization(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckTemplateTypeArgument(), GetFullTypeForDeclarator(), clang::Sema::InstantiateFunctionDefinition(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), clang::TreeTransform< Derived >::TransformReferenceType(), and clang::TransformTypeSpecType().
pushFullCopy()
void TypeLocBuilder::pushFullCopy (TypeLoc L)
Pushes a copy of the given TypeLoc onto this builder.
The builder must be empty for this to work.
Definition at line 18 of file TypeLocBuilder.cpp.
References clang::TypeLoc::getFullDataSize(), clang::TypeLoc::getNextTypeLoc(), clang::TypeLoc::getTypeLocClass(), and reserve().
Referenced by clang::Sema::actOnObjCTypeParam(), clang::Sema::CheckPackExpansion(), GetFullTypeForDeclarator(), clang::Sema::getTemplateArgumentPackExpansionPattern(), and clang::Sema::SubstType().
pushTypeSpec()
TypeSpecTypeLoc clang::TypeLocBuilder::pushTypeSpec (QualType T) inline
Pushes space for a typespec TypeLoc.
Invalidates any TypeLocs previously retrieved from this builder.
Definition at line 68 of file TypeLocBuilder.h.
References clang::TypeLoc::castAs(), clang::TypeSpecTypeLoc::LocalDataAlignment, and clang::TypeSpecTypeLoc::LocalDataSize.
Referenced by clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::ClassifyName(), and clang::Sema::getTypeName().
reserve()
void clang::TypeLocBuilder::reserve (size_t Requested) inline
Ensures that this buffer has at least as much capacity as described.
Definition at line 56 of file TypeLocBuilder.h.
Referenced by pushFullCopy(), clang::Sema::SubstFunctionDeclType(), clang::Sema::SubstType(), clang::TreeTransform< Derived >::TransformType(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
TypeWasModifiedSafely()
void clang::TypeLocBuilder::TypeWasModifiedSafely (QualType T) inline
Tell the TypeLocBuilder that the type it is storing has been modified in some safe way that doesn't affect type-location information.
Definition at line 85 of file TypeLocBuilder.h.
Referenced by clang::TreeTransform< Derived >::TransformReferenceType(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
The documentation for this class was generated from the following files:
lib/Sema/TypeLocBuilder.h
lib/Sema/TypeLocBuilder.cpp