clang: clang::TemplateArgumentListInfo Class Reference
clang::TemplateArgumentListInfo Class Reference
A convenient class for passing around template argument information.
#include "clang/AST/TemplateBase.h"
Public Member Functions
TemplateArgumentListInfo ()=default
TemplateArgumentListInfo (SourceLocation LAngleLoc, SourceLocation RAngleLoc)
void * operator new (size_t bytes, ASTContext &C)=delete
SourceLocation getLAngleLoc () const
SourceLocation getRAngleLoc () const
void setLAngleLoc (SourceLocation Loc)
void setRAngleLoc (SourceLocation Loc)
unsigned size () const
const TemplateArgumentLoc * getArgumentArray () const
llvm::ArrayRef< TemplateArgumentLoc > arguments () const
const TemplateArgumentLoc & operator[] (unsigned I) const
TemplateArgumentLoc & operator[] (unsigned I)
void addArgument (const TemplateArgumentLoc &Loc)
Detailed Description
A convenient class for passing around template argument information.
Designed to be passed by reference.
Definition at line 563 of file TemplateBase.h.
Constructor & Destructor Documentation
TemplateArgumentListInfo() [1/2]
clang::TemplateArgumentListInfo::TemplateArgumentListInfo () default
TemplateArgumentListInfo() [2/2]
clang::TemplateArgumentListInfo::TemplateArgumentListInfo (SourceLocation LAngleLoc, SourceLocation RAngleLoc) inline
Definition at line 571 of file TemplateBase.h.
Member Function Documentation
addArgument()
void clang::TemplateArgumentListInfo::addArgument (const TemplateArgumentLoc & Loc) inline
Definition at line 603 of file TemplateBase.h.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnStringLiteral(), clang::Sema::BuildStdInitializerList(), checkBuiltinTemplateIdType(), CheckDeducedPlaceholderConstraints(), clang::Sema::CheckTemplateArgumentList(), checkTupleLikeDecomposition(), clang::ASTTemplateKWAndArgsInfo::copyInto(), clang::Sema::FindInstantiatedDecl(), formImmediatelyDeclaredConstraint(), getTupleLikeElementType(), clang::ASTNodeImporter::ImportTemplateArgumentListInfo(), clang::Sema::InstantiateVariableDefinition(), InventTemplateParameter(), clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs(), isTupleLike(), lookupCoroutineHandleType(), lookupPromiseType(), clang::ASTRecordReader::readASTTemplateArgumentListInfo(), clang::ASTStmtReader::ReadTemplateKWAndArgsInfo(), clang::TreeTransform< Derived >::TransformTemplateArguments(), clang::Sema::translateTemplateArguments(), and clang::ASTDeclReader::VisitFunctionDecl().
arguments()
llvm::ArrayRef< TemplateArgumentLoc > clang::TemplateArgumentListInfo::arguments () const inline
Definition at line 591 of file TemplateBase.h.
Referenced by clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnFunctionDeclarator(), clang::TemplateSpecializationType::anyDependentTemplateArguments(), clang::Sema::BuildTypeConstraint(), ConvertDeclSpecToType(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTNodeImporter::ImportTemplateArgumentListInfo(), InventTemplateParameter(), printTemplateArgs(), clang::printTemplateArgumentList(), and substituteParameterMappings().
getArgumentArray()
const TemplateArgumentLoc * clang::TemplateArgumentListInfo::getArgumentArray () const inline
Definition at line 587 of file TemplateBase.h.
getLAngleLoc()
SourceLocation clang::TemplateArgumentListInfo::getLAngleLoc () const inline
Definition at line 579 of file TemplateBase.h.
Referenced by clang::Sema::AttachTypeConstraint(), clang::ASTContext::getTemplateSpecializationTypeInfo(), clang::ASTNodeImporter::ImportTemplateArgumentListInfo(), clang::ASTTemplateKWAndArgsInfo::initializeFrom(), and clang::ASTTemplateKWAndArgsInfo::initializeFrom().
getRAngleLoc()
SourceLocation clang::TemplateArgumentListInfo::getRAngleLoc () const inline
Definition at line 580 of file TemplateBase.h.
Referenced by clang::Sema::AttachTypeConstraint(), clang::Sema::CheckConceptTemplateId(), clang::Sema::CheckTemplateArgumentList(), clang::ASTContext::getTemplateSpecializationTypeInfo(), clang::ASTNodeImporter::ImportTemplateArgumentListInfo(), clang::ASTTemplateKWAndArgsInfo::initializeFrom(), and clang::ASTTemplateKWAndArgsInfo::initializeFrom().
operator new()
void * clang::TemplateArgumentListInfo::operator new (size_t bytes, ASTContext & C) delete
operator[]() [1/2]
TemplateArgumentLoc & clang::TemplateArgumentListInfo::operator[] (unsigned I) inline
Definition at line 599 of file TemplateBase.h.
operator[]() [2/2]
const TemplateArgumentLoc & clang::TemplateArgumentListInfo::operator[] (unsigned I) const inline
Definition at line 595 of file TemplateBase.h.
setLAngleLoc()
void clang::TemplateArgumentListInfo::setLAngleLoc (SourceLocation Loc) inline
Definition at line 582 of file TemplateBase.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), ConvertDeclSpecToType(), clang::ASTTemplateKWAndArgsInfo::copyInto(), clang::Sema::DecomposeUnqualifiedId(), formImmediatelyDeclaredConstraint(), clang::Sema::InstantiateVariableDefinition(), clang::ASTStmtReader::ReadTemplateKWAndArgsInfo(), clang::Sema::SubstTypeConstraint(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitVarTemplateSpecializationDecl().
setRAngleLoc()
void clang::TemplateArgumentListInfo::setRAngleLoc (SourceLocation Loc) inline
Definition at line 583 of file TemplateBase.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), ConvertDeclSpecToType(), clang::ASTTemplateKWAndArgsInfo::copyInto(), clang::Sema::DecomposeUnqualifiedId(), formImmediatelyDeclaredConstraint(), clang::Sema::InstantiateVariableDefinition(), clang::ASTStmtReader::ReadTemplateKWAndArgsInfo(), clang::Sema::SubstTypeConstraint(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitVarTemplateSpecializationDecl().
size()
unsigned clang::TemplateArgumentListInfo::size () const inline
Definition at line 585 of file TemplateBase.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTypenameType(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckTemplateArgumentList(), clang::CXXDependentScopeMemberExpr::Create(), clang::DeclRefExpr::Create(), clang::DependentFunctionTemplateSpecializationInfo::Create(), clang::DependentScopeDeclRefExpr::Create(), clang::MemberExpr::Create(), clang::UnresolvedLookupExpr::Create(), clang::UnresolvedMemberExpr::Create(), clang::Sema::DiagnoseEmptyLookup(), FinishTemplateArgumentDeduction(), clang::ASTContext::getDependentTemplateSpecializationType(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTTemplateKWAndArgsInfo::initializeFrom(), clang::ASTTemplateKWAndArgsInfo::initializeFrom(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::Sema::SubstituteExplicitTemplateArguments(), substituteParameterMappings(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
The documentation for this class was generated from the following file:
include/clang/AST/TemplateBase.h