clang: clang::Designation Class Reference
clang::Designation Class Reference
Designation - Represent a full designation, which is a sequence of designators.
#include "clang/Sema/Designator.h"
Public Member Functions
void AddDesignator (Designator D)
AddDesignator - Add a designator to the end of this list.
bool empty () const
unsigned getNumDesignators () const
const Designator & getDesignator (unsigned Idx) const
void ClearExprs (Sema &Actions)
ClearExprs - Null out any expression references, which prevents them from being 'delete'd later.
void FreeExprs (Sema &Actions)
FreeExprs - Release any unclaimed memory for the expressions in this designation.
Detailed Description
Designation - Represent a full designation, which is a sequence of designators.
This class is mostly a helper for InitListDesignations.
Definition at line 185 of file Designator.h.
Member Function Documentation
AddDesignator()
void clang::Designation::AddDesignator (Designator D) inline
AddDesignator - Add a designator to the end of this list.
Definition at line 191 of file Designator.h.
ClearExprs()
void clang::Designation::ClearExprs (Sema & Actions) inline
ClearExprs - Null out any expression references, which prevents them from being 'delete'd later.
Definition at line 205 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer().
empty()
bool clang::Designation::empty () const inline
Definition at line 195 of file Designator.h.
FreeExprs()
void clang::Designation::FreeExprs (Sema & Actions) inline
FreeExprs - Release any unclaimed memory for the expressions in this designation.
Definition at line 209 of file Designator.h.
getDesignator()
const Designator & clang::Designation::getDesignator (unsigned Idx) const inline
Definition at line 198 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), CheckArrayDesignatorSyntax(), and getDesignatedType().
getNumDesignators()
unsigned clang::Designation::getNumDesignators () const inline
Definition at line 197 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), CheckArrayDesignatorSyntax(), and getDesignatedType().
The documentation for this class was generated from the following file:
include/clang/Sema/Designator.h