clang: clang::CodeGen::LoopInfo Class Reference
clang::CodeGen::LoopInfo Class Reference
Information used when generating a structured loop.
#include "/root/llvm-project/clang/lib/CodeGen/CGLoopInfo.h"
Public Member Functions
LoopInfo (llvm::BasicBlock *Header, const LoopAttributes &Attrs, const llvm::DebugLoc &StartLoc, const llvm::DebugLoc &EndLoc, LoopInfo *Parent)
Construct a new LoopInfo for the loop with entry Header.
llvm::MDNode * getLoopID () const
Get the loop id metadata for this loop.
llvm::BasicBlock * getHeader () const
Get the header block of this loop.
const LoopAttributes & getAttributes () const
Get the set of attributes active for this loop.
llvm::MDNode * getAccessGroup () const
Return this loop's access group or nullptr if it does not have one.
void finish ()
Create the loop's metadata.
Detailed Description
Information used when generating a structured loop.
Definition at line 87 of file CGLoopInfo.h.
Constructor & Destructor Documentation
LoopInfo()
LoopInfo::LoopInfo (llvm::BasicBlock * Header, const LoopAttributes & Attrs, const llvm::DebugLoc & StartLoc, const llvm::DebugLoc & EndLoc, LoopInfo * Parent)
Construct a new LoopInfo for the loop with entry Header.
Definition at line 474 of file CGLoopInfo.cpp.
References clang::CodeGen::LoopAttributes::IsParallel.
Member Function Documentation
finish()
void LoopInfo::finish ()
Create the loop's metadata.
Must be called after its nested loops have been processed.
Definition at line 502 of file CGLoopInfo.cpp.
References clang::CodeGen::LoopAttributes::Disable, clang::CodeGen::LoopAttributes::DistributeEnable, clang::CodeGen::LoopAttributes::Enable, clang::CodeGen::LoopAttributes::Full, clang::CodeGen::LoopAttributes::InterleaveCount, clang::CodeGen::LoopAttributes::IsParallel, clang::CodeGen::LoopAttributes::PipelineDisabled, clang::CodeGen::LoopAttributes::PipelineInitiationInterval, clang::CodeGen::LoopAttributes::UnrollAndJamCount, clang::CodeGen::LoopAttributes::UnrollAndJamEnable, clang::CodeGen::LoopAttributes::UnrollCount, clang::CodeGen::LoopAttributes::UnrollEnable, clang::CodeGen::LoopAttributes::Unspecified, clang::CodeGen::LoopAttributes::VectorizeEnable, clang::CodeGen::LoopAttributes::VectorizePredicateEnable, clang::CodeGen::LoopAttributes::VectorizeScalable, and clang::CodeGen::LoopAttributes::VectorizeWidth.
getAccessGroup()
llvm::MDNode * clang::CodeGen::LoopInfo::getAccessGroup () const inline
Return this loop's access group or nullptr if it does not have one.
Definition at line 104 of file CGLoopInfo.h.
getAttributes()
const LoopAttributes & clang::CodeGen::LoopInfo::getAttributes () const inline
Get the set of attributes active for this loop.
Definition at line 101 of file CGLoopInfo.h.
Referenced by clang::CodeGen::LoopInfoStack::getCurLoopParallel().
getHeader()
llvm::BasicBlock * clang::CodeGen::LoopInfo::getHeader () const inline
Get the header block of this loop.
Definition at line 98 of file CGLoopInfo.h.
Referenced by clang::CodeGen::LoopInfoStack::InsertHelper().
getLoopID()
llvm::MDNode * clang::CodeGen::LoopInfo::getLoopID () const inline
Get the loop id metadata for this loop.
Definition at line 95 of file CGLoopInfo.h.
Referenced by clang::CodeGen::LoopInfoStack::getCurLoopID(), and clang::CodeGen::LoopInfoStack::InsertHelper().
The documentation for this class was generated from the following files:
lib/CodeGen/CGLoopInfo.h
lib/CodeGen/CGLoopInfo.cpp