clang: clang::ento::bugreporter::Tracker Class Reference
clang::ento::bugreporter::Tracker Class Reference
A generalized component for tracking expressions, values, and stores.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Classes
struct Result
Describes a tracking result with the most basic information of what was actually done (or not done).
Public Member Functions
virtual ~Tracker ()=default
PathSensitiveBugReport & getReport ()
virtual Result track (const Expr *E, const ExplodedNode *N, TrackingOptions Opts={})
Track expression value back to its point of origin.
virtual Result track (SVal V, const MemRegion *R, TrackingOptions Opts={}, const StackFrameContext *Origin=nullptr)
Track how the value got stored into the given region and where it came from.
virtual PathDiagnosticPieceRef handle (StoreInfo SI, BugReporterContext &BRC, TrackingOptions Opts)
Handle the store operation and produce the note.
void addHighPriorityHandler (ExpressionHandlerPtr SH)
Add custom expression handler with the highest priority.
void addLowPriorityHandler (ExpressionHandlerPtr SH)
Add custom expression handler with the lowest priority.
void addHighPriorityHandler (StoreHandlerPtr SH)
Add custom store handler with the highest priority.
void addLowPriorityHandler (StoreHandlerPtr SH)
Add custom store handler with the lowest priority.
template<class HandlerType , class... Args>
void addHighPriorityHandler (Args &&... ConstructorArgs)
Add custom expression/store handler with the highest priority.
template<class HandlerType , class... Args>
void addLowPriorityHandler (Args &&... ConstructorArgs)
Add custom expression/store handler with the lowest priority.
Static Public Member Functions
static TrackerRef create (PathSensitiveBugReport &Report)
Protected Member Functions
Tracker (PathSensitiveBugReport &Report)
Detailed Description
A generalized component for tracking expressions, values, and stores.
Tracker aimes at providing a sensible set of default behaviors that can be used by any checker, while providing mechanisms to hook into any part of the tracking process and insert checker-specific logic.
Definition at line 166 of file BugReporterVisitors.h.
Constructor & Destructor Documentation
Tracker()
Tracker::Tracker (PathSensitiveBugReport & Report) protected
Parameters
Report The bug report to which visitors should be attached.
Definition at line 2430 of file BugReporterVisitors.cpp.
References addHighPriorityHandler(), and addLowPriorityHandler().
Referenced by create().
~Tracker()
virtual clang::ento::bugreporter::Tracker::~Tracker () virtual default
Member Function Documentation
addHighPriorityHandler() [1/3]
template<class HandlerType , class... Args> void clang::ento::bugreporter::Tracker::addHighPriorityHandler (Args &&... ConstructorArgs) inline
Add custom expression/store handler with the highest priority.
See other overloads for explanation.
Definition at line 276 of file BugReporterVisitors.h.
References addHighPriorityHandler().
addHighPriorityHandler() [2/3]
void clang::ento::bugreporter::Tracker::addHighPriorityHandler (ExpressionHandlerPtr SH) inline
Add custom expression handler with the highest priority.
It means that it will be asked for handling first, and can prevent other handlers from running if decides to interrupt.
Definition at line 244 of file BugReporterVisitors.h.
Referenced by addHighPriorityHandler(), and Tracker().
addHighPriorityHandler() [3/3]
void clang::ento::bugreporter::Tracker::addHighPriorityHandler (StoreHandlerPtr SH) inline
Add custom store handler with the highest priority.
It means that it will be asked for handling first, and will prevent other handlers from running if it produces non-null note.
Definition at line 260 of file BugReporterVisitors.h.
addLowPriorityHandler() [1/3]
template<class HandlerType , class... Args> void clang::ento::bugreporter::Tracker::addLowPriorityHandler (Args &&... ConstructorArgs) inline
Add custom expression/store handler with the lowest priority.
See other overloads for explanation.
Definition at line 285 of file BugReporterVisitors.h.
References addLowPriorityHandler().
addLowPriorityHandler() [2/3]
void clang::ento::bugreporter::Tracker::addLowPriorityHandler (ExpressionHandlerPtr SH) inline
Add custom expression handler with the lowest priority.
It means that it will be asked for handling last, and other handlers can prevent it from running if any of them decides to interrupt.
Definition at line 252 of file BugReporterVisitors.h.
Referenced by addLowPriorityHandler(), and Tracker().
addLowPriorityHandler() [3/3]
void clang::ento::bugreporter::Tracker::addLowPriorityHandler (StoreHandlerPtr SH) inline
Add custom store handler with the lowest priority.
It means that it will be asked for handling last, only if all other handlers failed to produce the note.
Definition at line 268 of file BugReporterVisitors.h.
create()
static TrackerRef clang::ento::bugreporter::Tracker::create (PathSensitiveBugReport & Report) inline static
Definition at line 182 of file BugReporterVisitors.h.
References Tracker().
Referenced by clang::ento::bugreporter::trackExpressionValue(), and clang::ento::bugreporter::trackStoredValue().
getReport()
PathSensitiveBugReport & clang::ento::bugreporter::Tracker::getReport () inline
Definition at line 186 of file BugReporterVisitors.h.
handle()
PathDiagnosticPieceRef Tracker::handle (StoreInfo SI, BugReporterContext & BRC, TrackingOptions Opts) virtual
Handle the store operation and produce the note.
Parameters
SI The information fully describing the store.
Opts Tracking options specifying how we got to it.
NOTE: this method is designed for sub-trackers and visitors.
Definition at line 2477 of file BugReporterVisitors.cpp.
References clang::Result.
track() [1/2]
Tracker::Result Tracker::track (const Expr * E, const ExplodedNode * N, TrackingOptions Opts = {}) virtual
Track expression value back to its point of origin.
Parameters
E The expression value which we are tracking
N A node "downstream" from the evaluation of the statement.
Opts Tracking options specifying how we want to track the value.
Definition at line 2443 of file BugReporterVisitors.cpp.
References clang::ento::bugreporter::Tracker::Result::combineWith(), findNodeForExpression(), N, peelOffOuterExpr(), and clang::ento::bugreporter::Tracker::Result::WasInterrupted.
track() [2/2]
Tracker::Result Tracker::track (SVal V, const MemRegion * R, TrackingOptions Opts = {}, const StackFrameContext * Origin = nullptr) virtual
Track how the value got stored into the given region and where it came from.
Parameters
V We're searching for the store where R received this value.
R The region we're tracking.
Opts Tracking options specifying how we want to track the value.
Origin Only adds notes when the last store happened in a different stackframe to this one. Disregarded if the tracking kind is thorough. This is useful, because for non-tracked regions, notes about changes to its value in a nested stackframe could be pruned, and this visitor can prevent that without polluting the bugpath too much.
Definition at line 2468 of file BugReporterVisitors.cpp.
References clang::ento::PathSensitiveBugReport::addVisitor(), and V.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp