clang: clang::ClangDiagnosticHandler Class Reference
clang::ClangDiagnosticHandler Class Reference final
Public Member Functions
ClangDiagnosticHandler (const CodeGenOptions &CGOpts, BackendConsumer *BCon)
bool handleDiagnostics (const DiagnosticInfo &DI) override
bool isAnalysisRemarkEnabled (StringRef PassName) const override
bool isMissedOptRemarkEnabled (StringRef PassName) const override
bool isPassedOptRemarkEnabled (StringRef PassName) const override
bool isAnyRemarkEnabled () const override
Detailed Description
Definition at line 59 of file CodeGenAction.cpp.
Constructor & Destructor Documentation
ClangDiagnosticHandler()
clang::ClangDiagnosticHandler::ClangDiagnosticHandler (const CodeGenOptions & CGOpts, BackendConsumer * BCon) inline
Definition at line 61 of file CodeGenAction.cpp.
Member Function Documentation
handleDiagnostics()
bool ClangDiagnosticHandler::handleDiagnostics (const DiagnosticInfo & DI) override
Definition at line 462 of file CodeGenAction.cpp.
References clang::BackendConsumer::DiagnosticHandlerImpl().
isAnalysisRemarkEnabled()
bool clang::ClangDiagnosticHandler::isAnalysisRemarkEnabled (StringRef PassName) const inline override
Definition at line 66 of file CodeGenAction.cpp.
References clang::CodeGenOptions::OptimizationRemarkAnalysis, and clang::CodeGenOptions::OptRemark::patternMatches().
isAnyRemarkEnabled()
bool clang::ClangDiagnosticHandler::isAnyRemarkEnabled () const inline override
Definition at line 76 of file CodeGenAction.cpp.
References clang::CodeGenOptions::OptRemark::hasValidPattern(), clang::CodeGenOptions::OptimizationRemark, clang::CodeGenOptions::OptimizationRemarkAnalysis, and clang::CodeGenOptions::OptimizationRemarkMissed.
isMissedOptRemarkEnabled()
bool clang::ClangDiagnosticHandler::isMissedOptRemarkEnabled (StringRef PassName) const inline override
Definition at line 69 of file CodeGenAction.cpp.
References clang::CodeGenOptions::OptimizationRemarkMissed, and clang::CodeGenOptions::OptRemark::patternMatches().
isPassedOptRemarkEnabled()
bool clang::ClangDiagnosticHandler::isPassedOptRemarkEnabled (StringRef PassName) const inline override
Definition at line 72 of file CodeGenAction.cpp.
References clang::CodeGenOptions::OptimizationRemark, and clang::CodeGenOptions::OptRemark::patternMatches().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenAction.cpp