clang: clang::ento::BinarySymExpr Class Reference
clang::ento::BinarySymExpr Class Reference
Represents a symbolic expression involving a binary operator.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
QualType getType () const override
BinaryOperator::Opcode getOpcode () const
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
virtual void dumpToStream (raw_ostream &os) const
virtual void Profile (llvm::FoldingSetNodeID &profile)=0
symbol_iterator symbol_begin () const
virtual unsigned computeComplexity () const =0
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Static Public Member Functions
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymExpr
static symbol_iterator symbol_end ()
Protected Member Functions
BinarySymExpr (Kind k, BinaryOperator::Opcode op, QualType t)
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Static Protected Member Functions
static unsigned computeOperandComplexity (const SymExpr *Value)
static unsigned computeOperandComplexity (const llvm::APSInt &Value)
static const llvm::APSInt * getPointer (const llvm::APSInt &Value)
static const SymExpr * getPointer (const SymExpr *Value)
static void dumpToStreamImpl (raw_ostream &os, const SymExpr *Value)
static void dumpToStreamImpl (raw_ostream &os, const llvm::APSInt &Value)
static void dumpToStreamImpl (raw_ostream &os, BinaryOperator::Opcode op)
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
Represents a symbolic expression involving a binary operator.
Definition at line 377 of file SymbolManager.h.
Constructor & Destructor Documentation
BinarySymExpr()
clang::ento::BinarySymExpr::BinarySymExpr (Kind k, BinaryOperator::Opcode op, QualType t) inline protected
Definition at line 382 of file SymbolManager.h.
References classof(), clang::ento::Loc::isLocType(), and clang::ento::SymExpr::isValidTypeForSymbol().
Member Function Documentation
classof()
static bool clang::ento::BinarySymExpr::classof (const SymExpr * SE) inline static
Definition at line 399 of file SymbolManager.h.
References clang::ento::SymExpr::getKind().
Referenced by BinarySymExpr().
computeOperandComplexity() [1/2]
static unsigned clang::ento::BinarySymExpr::computeOperandComplexity (const llvm::APSInt & Value) inline static protected
Definition at line 408 of file SymbolManager.h.
computeOperandComplexity() [2/2]
static unsigned clang::ento::BinarySymExpr::computeOperandComplexity (const SymExpr * Value) inline static protected
Definition at line 405 of file SymbolManager.h.
Referenced by clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::computeComplexity().
dumpToStreamImpl() [1/3]
void BinarySymExpr::dumpToStreamImpl (raw_ostream & os, BinaryOperator::Opcode op) static protected
Definition at line 62 of file SymbolManager.cpp.
References clang::BinaryOperator::getOpcodeStr(), and clang::ento::OS.
dumpToStreamImpl() [2/3]
void BinarySymExpr::dumpToStreamImpl (raw_ostream & os, const llvm::APSInt & Value) static protected
Definition at line 52 of file SymbolManager.cpp.
References clang::ento::OS.
dumpToStreamImpl() [3/3]
void BinarySymExpr::dumpToStreamImpl (raw_ostream & os, const SymExpr * Value) static protected
Definition at line 46 of file SymbolManager.cpp.
References clang::ento::SymExpr::dumpToStream(), and clang::ento::OS.
Referenced by clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::dumpToStream().
getOpcode()
BinaryOperator::Opcode clang::ento::BinarySymExpr::getOpcode () const inline
Definition at line 396 of file SymbolManager.h.
Referenced by clang::ento::RangedConstraintManager::assumeSym(), clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::dumpToStream(), clang::ento::SMTConv::getSymBinExpr(), and clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile().
getPointer() [1/2]
static const llvm::APSInt * clang::ento::BinarySymExpr::getPointer (const llvm::APSInt & Value) inline static protected
Definition at line 412 of file SymbolManager.h.
Referenced by clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::BinarySymExprImpl(), and clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile().
getPointer() [2/2]
static const SymExpr * clang::ento::BinarySymExpr::getPointer (const SymExpr * Value) inline static protected
Definition at line 415 of file SymbolManager.h.
getType()
QualType clang::ento::BinarySymExpr::getType () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 394 of file SymbolManager.h.
Referenced by clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp