clang: clang::Parser Class Reference
clang::Parser Class Reference
Parser - This implements a parser for the C family of languages.
#include "clang/Parse/Parser.h"
Classes
struct ConditionDeclarationOrInitStatementState
class MultiParseScope
Introduces zero or more scopes for parsing.
class ObjCTypeParamListScope
Class to handle popping type parameters when leaving the scope.
class ParseScope
ParseScope - Introduces a new scope for parsing.
struct ReenterClassScopeRAII
Utility to re-enter a class scope while parsing its late-parsed components.
struct ReenterTemplateScopeRAII
Utility to re-enter a possibly-templated scope while parsing its late-parsed components.
class UnannotatedTentativeParsingAction
A tentative parsing action that can also revert token annotations.
Public Types
enum SkipUntilFlags { StopAtSemi = 1 << 0 , StopBeforeMatch = 1 << 1 , StopAtCodeCompletion = 1 << 2 }
Control flags for SkipUntil functions.
enum TypeCastState { NotTypeCast = 0 , MaybeTypeCast , IsTypeCast }
TypeCastState - State whether an expression is or may be a type cast.
typedef OpaquePtr< DeclGroupRef > DeclGroupPtrTy
typedef OpaquePtr< TemplateName > TemplateTy
typedef SmallVector< TemplateParameterList *, 4 > TemplateParameterLists
typedef Sema::FullExprArg FullExprArg
Public Member Functions
Parser (Preprocessor &PP, Sema &Actions, bool SkipFunctionBodies)
~Parser () override
const LangOptions & getLangOpts () const
const TargetInfo & getTargetInfo () const
Preprocessor & getPreprocessor () const
Sema & getActions () const
AttributeFactory & getAttrFactory ()
const Token & getCurToken () const
Scope * getCurScope () const
void incrementMSManglingNumber () const
ObjCContainerDecl * getObjCDeclContext () const
void Initialize ()
Initialize - Warm up the parser.
bool ParseFirstTopLevelDecl (DeclGroupPtrTy &Result, Sema::ModuleImportState &ImportState)
Parse the first top-level declaration in a translation unit.
bool ParseTopLevelDecl (DeclGroupPtrTy &Result, Sema::ModuleImportState &ImportState)
ParseTopLevelDecl - Parse one top-level declaration.
bool ParseTopLevelDecl ()
SourceLocation ConsumeToken ()
ConsumeToken - Consume the current 'peek token' and lex the next one.
bool TryConsumeToken (tok::TokenKind Expected)
bool TryConsumeToken (tok::TokenKind Expected, SourceLocation &Loc)
SourceLocation ConsumeAnyToken (bool ConsumeCodeCompletionTok=false)
ConsumeAnyToken - Dispatch to the right Consume* method based on the current token type.
SourceLocation getEndOfPreviousToken ()
IdentifierInfo * getNullabilityKeyword (NullabilityKind nullability)
Retrieve the underscored keyword (_Nonnull, _Nullable) that corresponds to the given nullability kind.
const Token & NextToken ()
NextToken - This peeks ahead one token and returns it without consuming it.
bool TryAnnotateTypeOrScopeToken ()
TryAnnotateTypeOrScopeToken - If the current token position is on a typename (possibly qualified in C++) or a C++ scope specifier not followed by a typename, TryAnnotateTypeOrScopeToken will replace one or more tokens with a single annotation token representing the typename or C++ scope respectively.
bool TryAnnotateTypeOrScopeTokenAfterScopeSpec (CXXScopeSpec &SS, bool IsNewScope)
Try to annotate a type or scope token, having already parsed an optional scope specifier.
bool TryAnnotateCXXScopeToken (bool EnteringContext=false)
TryAnnotateScopeToken - Like TryAnnotateTypeOrScopeToken but only annotates C++ scope specifiers and template-ids.
bool MightBeCXXScopeToken ()
bool TryAnnotateOptionalCXXScopeToken (bool EnteringContext=false)
void EnterScope (unsigned ScopeFlags)
EnterScope - Start a new scope.
void ExitScope ()
ExitScope - Pop a scope off the scope stack.
unsigned ReenterTemplateScopes (MultiParseScope &S, Decl *D)
Re-enter the template scopes for a declaration that might be a template.
DiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID)
DiagnosticBuilder Diag (const Token &Tok, unsigned DiagID)
DiagnosticBuilder Diag (unsigned DiagID)
bool SkipUntil (tok::TokenKind T, SkipUntilFlags Flags=static_cast< SkipUntilFlags >(0))
SkipUntil - Read tokens until we get to the specified token, then consume it (unless StopBeforeMatch is specified).
bool SkipUntil (tok::TokenKind T1, tok::TokenKind T2, SkipUntilFlags Flags=static_cast< SkipUntilFlags >(0))
bool SkipUntil (tok::TokenKind T1, tok::TokenKind T2, tok::TokenKind T3, SkipUntilFlags Flags=static_cast< SkipUntilFlags >(0))
bool SkipUntil (ArrayRef< tok::TokenKind > Toks, SkipUntilFlags Flags=static_cast< SkipUntilFlags >(0))
SkipUntil - Read tokens until we get to the specified token, then consume it (unless no flag StopBeforeMatch).
void SkipMalformedDecl ()
SkipMalformedDecl - Read tokens until we get to some likely good stopping point for skipping past a simple-declaration.
ExprResult ParseExpression (TypeCastState isTypeCast=NotTypeCast)
Simple precedence-based parser for binary/ternary operators.
ExprResult ParseConstantExpressionInExprEvalContext (TypeCastState isTypeCast=NotTypeCast)
ExprResult ParseConstantExpression (TypeCastState isTypeCast=NotTypeCast)
ExprResult ParseCaseExpression (SourceLocation CaseLoc)
ExprResult ParseConstraintExpression ()
Parse a constraint-expression.
ExprResult ParseConstraintLogicalAndExpression (bool IsTrailingRequiresClause)
Parse a constraint-logical-and-expression.
ExprResult ParseConstraintLogicalOrExpression (bool IsTrailingRequiresClause)
Parse a constraint-logical-or-expression.
ExprResult ParseAssignmentExpression (TypeCastState isTypeCast=NotTypeCast)
Parse an expr that doesn't include (top-level) commas.
ExprResult ParseMSAsmIdentifier (llvm::SmallVectorImpl< Token > &LineToks, unsigned &NumLineToksConsumed, bool IsUnevaluated)
Parse an identifier in an MS-style inline assembly block.
ExprResult ParseStringLiteralExpression (bool AllowUserDefinedLiteral=false)
TypeResult ParseTypeName (SourceRange *Range=nullptr, DeclaratorContext Context=DeclaratorContext::TypeName, AccessSpecifier AS=AS_none, Decl **OwnedType=nullptr, ParsedAttributes *Attrs=nullptr)
ParseTypeName type-name: [C99 6.7.6] specifier-qualifier-list abstract-declarator[opt].
ExprResult ParseOpenMPParensExpr (StringRef ClauseName, SourceLocation &RLoc, bool IsAddressOfOperand=false)
Parses simple expression in parens for single-expression clauses of OpenMP constructs.
bool ParseOpenMPReservedLocator (OpenMPClauseKind Kind, Sema::OpenMPVarListDataTy &Data, const LangOptions &LangOpts)
Parses a reserved locator like 'omp_all_memory'.
bool ParseOpenMPVarList (OpenMPDirectiveKind DKind, OpenMPClauseKind Kind, SmallVectorImpl< Expr * > &Vars, Sema::OpenMPVarListDataTy &Data)
Parses clauses with list.
bool ParseUnqualifiedId (CXXScopeSpec &SS, ParsedType ObjectType, bool ObjectHadErrors, bool EnteringContext, bool AllowDestructorName, bool AllowConstructorName, bool AllowDeductionGuide, SourceLocation *TemplateKWLoc, UnqualifiedId &Result)
Parse a C++ unqualified-id (or a C identifier), which describes the name of an entity.
bool parseMapperModifier (Sema::OpenMPVarListDataTy &Data)
Parses the mapper modifier in map, to, and from clauses.
bool parseMapTypeModifiers (Sema::OpenMPVarListDataTy &Data)
Parses map-type-modifiers in map clause.
Public Member Functions inherited from clang::CodeCompletionHandler
virtual ~CodeCompletionHandler ()
Static Public Member Functions
static TypeResult getTypeAnnotation (const Token &Tok)
getTypeAnnotation - Read a parsed type out of an annotation token.
Public Attributes
SourceLocation MisleadingIndentationElseLoc
The location of the first statement inside an else that might have a missleading indentation.
Friends
class ColonProtectionRAIIObject
class ParsingOpenMPDirectiveRAII
class InMessageExpressionRAIIObject
class PoisonSEHIdentifiersRAIIObject
class ObjCDeclContextSwitch
class ParenBraceBracketBalancer
class BalancedDelimiterTracker
constexpr SkipUntilFlags operator| (SkipUntilFlags L, SkipUntilFlags R)
Detailed Description
Parser - This implements a parser for the C family of languages.
After parsing units of the grammar, productions are invoked to handle whatever has been read.
Definition at line 60 of file Parser.h.
Member Typedef Documentation
DeclGroupPtrTy
OpaquePtr<DeclGroupRef> clang::Parser::DeclGroupPtrTy
Definition at line 459 of file Parser.h.
FullExprArg
Sema::FullExprArg clang::Parser::FullExprArg
Definition at line 464 of file Parser.h.
TemplateParameterLists
SmallVector<TemplateParameterList *, 4> clang::Parser::TemplateParameterLists
Definition at line 462 of file Parser.h.
TemplateTy
OpaquePtr<TemplateName> clang::Parser::TemplateTy
Definition at line 460 of file Parser.h.
Member Enumeration Documentation
SkipUntilFlags
enum clang::Parser::SkipUntilFlags
Control flags for SkipUntil functions.
Enumerator
StopAtSemi
Stop skipping at semicolon.
StopBeforeMatch
Stop skipping at specified token, but don't skip the token itself.
StopAtCodeCompletion
Stop at code completion.
Definition at line 1198 of file Parser.h.
TypeCastState
enum clang::Parser::TypeCastState
TypeCastState - State whether an expression is or may be a type cast.
Enumerator
NotTypeCast
MaybeTypeCast
IsTypeCast
Definition at line 1746 of file Parser.h.
Constructor & Destructor Documentation
Parser()
Parser::Parser (Preprocessor & PP, Sema & Actions, bool SkipFunctionBodies)
Definition at line 51 of file Parser.cpp.
References clang::Preprocessor::addCommentHandler(), clang::Preprocessor::isCodeCompletionEnabled(), clang::Preprocessor::setCodeCompletionHandler(), clang::Token::setKind(), and clang::Token::startToken().
~Parser()
Parser::~Parser () override
Definition at line 454 of file Parser.cpp.
References clang::Preprocessor::clearCodeCompletionHandler(), getCurScope(), and clang::Preprocessor::removeCommentHandler().
Member Function Documentation
ConsumeAnyToken()
SourceLocation clang::Parser::ConsumeAnyToken (bool ConsumeCodeCompletionTok = false) inline
ConsumeAnyToken - Dispatch to the right Consume* method based on the current token type.
This should only be used in cases where the type of the token really isn't known, e.g. in error recovery.
Definition at line 519 of file Parser.h.
References ConsumeToken(), and Tok.
Referenced by SkipMalformedDecl(), and SkipUntil().
ConsumeToken()
SourceLocation clang::Parser::ConsumeToken () inline
ConsumeToken - Consume the current 'peek token' and lex the next one.
This does not work with special tokens: string literals, code completion, annotation tokens and balanced tokens must be handled using the specific consume methods. Returns the location of the consumed token.
Definition at line 491 of file Parser.h.
References clang::Preprocessor::Lex(), and Tok.
Referenced by ConsumeAnyToken(), Initialize(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), ParseConstraintLogicalAndExpression(), ParseConstraintLogicalOrExpression(), parseMapperModifier(), parseMapTypeModifiers(), ParseOpenMPReservedLocator(), ParseOpenMPVarList(), ParseTopLevelDecl(), ParseUnqualifiedId(), SkipMalformedDecl(), SkipUntil(), TryAnnotateTypeOrScopeToken(), and TryAnnotateTypeOrScopeTokenAfterScopeSpec().
Diag() [1/3]
DiagnosticBuilder Parser::Diag (const Token & Tok, unsigned DiagID)
Definition at line 77 of file Parser.cpp.
References Diag(), clang::Token::getLocation(), and Tok.
Diag() [2/3]
DiagnosticBuilder Parser::Diag (SourceLocation Loc, unsigned DiagID)
Definition at line 73 of file Parser.cpp.
References clang::DiagnosticsEngine::Report().
Referenced by Diag(), Diag(), diagnoseExpectedAttributeSubjectSubRule(), diagnoseUnknownAttributeSubjectSubRule(), ParseConstraintLogicalAndExpression(), ParseFirstTopLevelDecl(), parseMapperModifier(), parseMapTypeModifiers(), ParseOpenMPReservedLocator(), ParseOpenMPVarList(), ParseUnqualifiedId(), and TryAnnotateTypeOrScopeToken().
Diag() [3/3]
DiagnosticBuilder clang::Parser::Diag (unsigned DiagID) inline
Definition at line 1186 of file Parser.h.
References Diag(), and Tok.
EnterScope()
void Parser::EnterScope (unsigned ScopeFlags)
EnterScope - Start a new scope.
Definition at line 404 of file Parser.cpp.
References getCurScope(), clang::Scope::Init(), and N.
Referenced by clang::Parser::MultiParseScope::Enter(), Initialize(), ParseOpenMPVarList(), and clang::Parser::ParseScope::ParseScope().
ExitScope()
void Parser::ExitScope ()
ExitScope - Pop a scope off the scope stack.
Definition at line 415 of file Parser.cpp.
References clang::Sema::ActOnPopScope(), getCurScope(), clang::Token::getLocation(), and clang::Scope::getParent().
Referenced by clang::Parser::MultiParseScope::Exit(), clang::Parser::ParseScope::Exit(), and ParseOpenMPVarList().
getActions()
Sema & clang::Parser::getActions () const inline
Definition at line 444 of file Parser.h.
getAttrFactory()
AttributeFactory & clang::Parser::getAttrFactory () inline
Definition at line 445 of file Parser.h.
getCurScope()
Scope * clang::Parser::getCurScope () const inline
Definition at line 448 of file Parser.h.
References clang::Sema::getCurScope().
Referenced by EnterScope(), ExitScope(), Initialize(), ParseAssignmentExpression(), ParseConstraintLogicalAndExpression(), ParseConstraintLogicalOrExpression(), ParseTypeName(), ParseUnqualifiedId(), TryAnnotateTypeOrScopeToken(), TryAnnotateTypeOrScopeTokenAfterScopeSpec(), and ~Parser().
getCurToken()
const Token & clang::Parser::getCurToken () const inline
Definition at line 447 of file Parser.h.
References Tok.
Referenced by parseMapTypeModifiers().
getEndOfPreviousToken()
SourceLocation clang::Parser::getEndOfPreviousToken () inline
Definition at line 537 of file Parser.h.
References clang::Preprocessor::getLocForEndOfToken().
getLangOpts()
const LangOptions & clang::Parser::getLangOpts () const inline
Definition at line 441 of file Parser.h.
References clang::Preprocessor::getLangOpts().
Referenced by Initialize(), ParseFirstTopLevelDecl(), parseMapperModifier(), parseMapTypeModifiers(), ParseOpenMPVarList(), ParseTopLevelDecl(), ParseUnqualifiedId(), TryAnnotateCXXScopeToken(), TryAnnotateTypeOrScopeToken(), and TryAnnotateTypeOrScopeTokenAfterScopeSpec().
getNullabilityKeyword()
IdentifierInfo * clang::Parser::getNullabilityKeyword (NullabilityKind nullability) inline
Retrieve the underscored keyword (_Nonnull, _Nullable) that corresponds to the given nullability kind.
Definition at line 543 of file Parser.h.
References clang::Sema::getNullabilityKeyword().
getObjCDeclContext()
ObjCContainerDecl * clang::Parser::getObjCDeclContext () const inline
Definition at line 453 of file Parser.h.
References clang::Sema::getObjCDeclContext().
getPreprocessor()
Preprocessor & clang::Parser::getPreprocessor () const inline
Definition at line 443 of file Parser.h.
getTargetInfo()
const TargetInfo & clang::Parser::getTargetInfo () const inline
Definition at line 442 of file Parser.h.
References clang::Preprocessor::getTargetInfo().
getTypeAnnotation()
static TypeResult clang::Parser::getTypeAnnotation (const Token & Tok) inline static
getTypeAnnotation - Read a parsed type out of an annotation token.
Definition at line 813 of file Parser.h.
References clang::OpaquePtr< QualType >::getFromOpaquePtr(), Tok, and clang::TypeError().
incrementMSManglingNumber()
void clang::Parser::incrementMSManglingNumber () const inline
Definition at line 449 of file Parser.h.
References clang::Sema::incrementMSManglingNumber().
Initialize()
void Parser::Initialize ()
Initialize - Warm up the parser.
Definition at line 474 of file Parser.cpp.
References clang::Sema::ActOnTranslationUnitScope(), ConsumeToken(), clang::Scope::DeclScope, EnterScope(), clang::IdentifierTable::get(), getCurScope(), clang::Preprocessor::getIdentifierInfo(), clang::Preprocessor::getIdentifierTable(), getLangOpts(), clang::Sema::Initialize(), clang::ObjC, and clang::Preprocessor::SetPoisonReason().
MightBeCXXScopeToken()
bool clang::Parser::MightBeCXXScopeToken () inline
Definition at line 862 of file Parser.h.
References is(), NextToken(), and Tok.
Referenced by TryAnnotateCXXScopeToken(), and TryAnnotateOptionalCXXScopeToken().
NextToken()
const Token & clang::Parser::NextToken () inline
NextToken - This peeks ahead one token and returns it without consuming it.
Definition at line 808 of file Parser.h.
References clang::Preprocessor::LookAhead().
Referenced by MightBeCXXScopeToken(), ParseConstraintLogicalAndExpression(), ParseOpenMPVarList(), ParseTopLevelDecl(), ParseUnqualifiedId(), SkipMalformedDecl(), TryAnnotateTypeOrScopeToken(), and TryAnnotateTypeOrScopeTokenAfterScopeSpec().
ParseAssignmentExpression()
ExprResult Parser::ParseAssignmentExpression (TypeCastState isTypeCast = NotTypeCast)
Parse an expr that doesn't include (top-level) commas.
Definition at line 160 of file ParseExpr.cpp.
References clang::prec::Assignment, clang::Sema::CodeCompleteExpression(), clang::ExprError(), clang::PreferredTypeBuilder::get(), getCurScope(), clang::Token::getLocation(), and clang::Token::is().
Referenced by ParseExpression(), and ParseOpenMPVarList().
ParseCaseExpression()
ExprResult Parser::ParseCaseExpression (SourceLocation CaseLoc)
Definition at line 221 of file ParseExpr.cpp.
References clang::Sema::ActOnCaseExpr(), clang::prec::Conditional, clang::Sema::ConstantEvaluated, and NotTypeCast.
ParseConstantExpression()
ExprResult Parser::ParseConstantExpression (TypeCastState isTypeCast = NotTypeCast)
Definition at line 211 of file ParseExpr.cpp.
References clang::Sema::ConstantEvaluated, and ParseConstantExpressionInExprEvalContext().
ParseConstantExpressionInExprEvalContext()
ExprResult Parser::ParseConstantExpressionInExprEvalContext (TypeCastState isTypeCast = NotTypeCast)
Definition at line 201 of file ParseExpr.cpp.
References clang::Sema::ActOnConstantExpression(), clang::prec::Conditional, clang::Sema::ConstantEvaluated, and clang::Sema::ExprEvalContexts.
Referenced by ParseConstantExpression().
ParseConstraintExpression()
ExprResult Parser::ParseConstraintExpression ()
Parse a constraint-expression.
///       constraint-expression: C++2a[temp.constr.decl]p1
///         logical-or-expression
///
Definition at line 235 of file ParseExpr.cpp.
References clang::Sema::CheckConstraintExpression(), clang::Sema::CorrectDelayedTyposInExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::prec::LogicalOr, and clang::Sema::Unevaluated.
ParseConstraintLogicalAndExpression()
ExprResult Parser::ParseConstraintLogicalAndExpression (bool IsTrailingRequiresClause)
Parse a constraint-logical-and-expression.
///       C++2a[temp.constr.decl]p1
///       constraint-logical-and-expression:
///         primary-expression
///         constraint-logical-and-expression '&&' primary-expression
///
///
Definition at line 257 of file ParseExpr.cpp.
References clang::Sema::ActOnBinOp(), clang::Sema::CheckConstraintExpression(), ConsumeToken(), clang::Sema::CorrectDelayedTyposInExpr(), clang::FixItHint::CreateInsertion(), Diag(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::getBinOpPrecedence(), getCurScope(), clang::Stmt::getEndLoc(), clang::Expr::getExprLoc(), clang::Token::getKind(), clang::Preprocessor::getLocForEndOfToken(), clang::Stmt::getSourceRange(), clang::prec::InclusiveOr, clang::Token::is(), is(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Token::isOneOf(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::prec::LogicalAnd, NextToken(), clang::Note, NotTypeCast, and clang::Sema::Unevaluated.
Referenced by ParseConstraintLogicalOrExpression().
ParseConstraintLogicalOrExpression()
ExprResult Parser::ParseConstraintLogicalOrExpression (bool IsTrailingRequiresClause)
Parse a constraint-logical-or-expression.
///       C++2a[temp.constr.decl]p1
///       constraint-logical-or-expression:
///         constraint-logical-and-expression
///         constraint-logical-or-expression '||'
///             constraint-logical-and-expression
///
///
Definition at line 349 of file ParseExpr.cpp.
References clang::Sema::ActOnBinOp(), ConsumeToken(), clang::Sema::CorrectDelayedTyposInExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), getCurScope(), clang::Token::is(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), and ParseConstraintLogicalAndExpression().
ParseExpression()
ExprResult Parser::ParseExpression (TypeCastState isTypeCast = NotTypeCast)
Simple precedence-based parser for binary/ternary operators.
Note: we diverge from the C99 grammar when parsing the assignment-expression production. C99 specifies that the LHS of an assignment operator should be parsed as a unary-expression, but consistency dictates that it be a conditional-expession. In practice, the important thing here is that the LHS of an assignment has to be an l-value, which productions between unary-expression and conditional-expression don't produce. Because we want consistency, we parse the LHS as a conditional-expression, then check for l-value-ness in semantic analysis stages.
///       pm-expression: [C++ 5.5]
///         cast-expression
///         pm-expression '.*' cast-expression
///         pm-expression '->*' cast-expression
///
///       multiplicative-expression: [C99 6.5.5]
///     Note: in C++, apply pm-expression instead of cast-expression
///         cast-expression
///         multiplicative-expression '*' cast-expression
///         multiplicative-expression '/' cast-expression
///         multiplicative-expression '%' cast-expression
///
///       additive-expression: [C99 6.5.6]
///         multiplicative-expression
///         additive-expression '+' multiplicative-expression
///         additive-expression '-' multiplicative-expression
///
///       shift-expression: [C99 6.5.7]
///         additive-expression
///         shift-expression '<<' additive-expression
///         shift-expression '>>' additive-expression
///
///       compare-expression: [C++20 expr.spaceship]
///         shift-expression
///         compare-expression '<=>' shift-expression
///
///       relational-expression: [C99 6.5.8]
///         compare-expression
///         relational-expression '<' compare-expression
///         relational-expression '>' compare-expression
///         relational-expression '<=' compare-expression
///         relational-expression '>=' compare-expression
///
///       equality-expression: [C99 6.5.9]
///         relational-expression
///         equality-expression '==' relational-expression
///         equality-expression '!=' relational-expression
///
///       AND-expression: [C99 6.5.10]
///         equality-expression
///         AND-expression '&' equality-expression
///
///       exclusive-OR-expression: [C99 6.5.11]
///         AND-expression
///         exclusive-OR-expression '^' AND-expression
///
///       inclusive-OR-expression: [C99 6.5.12]
///         exclusive-OR-expression
///         inclusive-OR-expression '|' exclusive-OR-expression
///
///       logical-AND-expression: [C99 6.5.13]
///         inclusive-OR-expression
///         logical-AND-expression '&&' inclusive-OR-expression
///
///       logical-OR-expression: [C99 6.5.14]
///         logical-AND-expression
///         logical-OR-expression '||' logical-AND-expression
///
///       conditional-expression: [C99 6.5.15]
///         logical-OR-expression
///         logical-OR-expression '?' expression ':' conditional-expression
/// [GNU]   logical-OR-expression '?' ':' conditional-expression
/// [C++] the third operand is an assignment-expression
///
///       assignment-expression: [C99 6.5.16]
///         conditional-expression
///         unary-expression assignment-operator assignment-expression
/// [C++]   throw-expression [C++ 15]
///
///       assignment-operator: one of
///         = *= /= %= += -= <<= >>= &= ^= |=
///
///       expression: [C99 6.5.17]
///         assignment-expression ...[opt]
///         expression ',' assignment-expression ...[opt]
///
Definition at line 123 of file ParseExpr.cpp.
References clang::prec::Comma, and ParseAssignmentExpression().
ParseFirstTopLevelDecl()
bool Parser::ParseFirstTopLevelDecl (DeclGroupPtrTy & Result, Sema::ModuleImportState & ImportState)
Parse the first top-level declaration in a translation unit.
translation-unit: [C] external-declaration [C] translation-unit external-declaration [C++] top-level-declaration-seq[opt] [C++20] global-module-fragment[opt] module-declaration top-level-declaration-seq[opt] private-module-fragment[opt]
Note that in C, it is an error if there is no first declaration.
Definition at line 584 of file Parser.cpp.
References clang::Sema::ActOnStartOfTranslationUnit(), clang::CPlusPlus, Diag(), clang::Sema::FirstDecl, clang::Sema::getASTContext(), clang::ASTContext::getExternalSource(), getLangOpts(), ParseTopLevelDecl(), and clang::Result.
parseMapperModifier()
bool Parser::parseMapperModifier (Sema::OpenMPVarListDataTy & Data)
Parses the mapper modifier in map, to, and from clauses.
Parse the mapper modifier in map, to, and from clauses.
Definition at line 3926 of file ParseOpenMP.cpp.
References ConsumeToken(), clang::CPlusPlus, clang::ASTContext::DeclarationNames, Diag(), clang::Sema::getASTContext(), clang::Token::getIdentifierInfo(), getLangOpts(), clang::Token::getLocation(), clang::Token::isNot(), clang::Sema::OpenMPVarListDataTy::ReductionOrMapperId, clang::Sema::OpenMPVarListDataTy::ReductionOrMapperIdScopeSpec, SkipUntil(), StopBeforeMatch, and Tok.
Referenced by parseMapTypeModifiers(), and ParseOpenMPVarList().
parseMapTypeModifiers()
bool Parser::parseMapTypeModifiers (Sema::OpenMPVarListDataTy & Data)
Parses map-type-modifiers in map clause.
Parse map-type-modifiers in map clause.
map([ [map-type-modifier[,] [map-type-modifier[,] ...] map-type : ] list) where, map-type-modifier ::= always | close | mapper(mapper-identifier)
map([ [map-type-modifier[,] [map-type-modifier[,] ...] map-type : ] list) where, map-type-modifier ::= always | close | mapper(mapper-identifier) | present
Definition at line 3958 of file ParseOpenMP.cpp.
References ConsumeToken(), Diag(), getCurToken(), getLangOpts(), clang::Token::getLocation(), clang::Token::is(), is(), isMapModifier(), isNot(), clang::Preprocessor::LookAhead(), clang::Sema::OpenMPVarListDataTy::MapTypeModifiers, clang::Sema::OpenMPVarListDataTy::MapTypeModifiersLoc, parseMapperModifier(), and Tok.
Referenced by ParseOpenMPVarList().
ParseMSAsmIdentifier()
ExprResult Parser::ParseMSAsmIdentifier (llvm::SmallVectorImpl< Token > & LineToks, unsigned & NumLineToksConsumed, bool IsUnevaluated)
Parse an identifier in an MS-style inline assembly block.
Definition at line 200 of file ParseStmtAsm.cpp.
References clang::CPlusPlus, clang::Token::getIdentifierInfo(), clang::Token::getLocation(), Id, clang::Invalid, clang::Token::is(), clang::Token::isNot(), clang::Token::setKind(), clang::Token::startToken(), and Tok.
ParseOpenMPParensExpr()
ExprResult Parser::ParseOpenMPParensExpr (StringRef ClauseName, SourceLocation & RLoc, bool IsAddressOfOperand = false)
Parses simple expression in parens for single-expression clauses of OpenMP constructs.
Parameters
RLoc Returned location of right paren.
Definition at line 3380 of file ParseOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::prec::Conditional, clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Token::getLocation(), NotTypeCast, and Tok.
ParseOpenMPReservedLocator()
bool Parser::ParseOpenMPReservedLocator (OpenMPClauseKind Kind, Sema::OpenMPVarListDataTy & Data, const LangOptions & LangOpts)
Parses a reserved locator like 'omp_all_memory'.
Definition at line 4133 of file ParseOpenMP.cpp.
References ConsumeToken(), Diag(), clang::Sema::OpenMPVarListDataTy::ExtraModifier, clang::Token::getIdentifierInfo(), clang::Token::is(), clang::IdentifierInfo::isStr(), and Tok.
Referenced by ParseOpenMPVarList().
ParseOpenMPVarList()
bool Parser::ParseOpenMPVarList (OpenMPDirectiveKind DKind, OpenMPClauseKind Kind, SmallVectorImpl< Expr * > & Vars, Sema::OpenMPVarListDataTy & Data)
Parses clauses with list.
Definition at line 4161 of file ParseOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::OpenMPVarListDataTy::ColonLoc, clang::BalancedDelimiterTracker::consumeClose(), clang::BalancedDelimiterTracker::consumeOpen(), ConsumeToken(), clang::Sema::CorrectDelayedTyposInExpr(), clang::CPlusPlus, clang::Scope::DeclScope, clang::Sema::OpenMPVarListDataTy::DepModOrTailExpr, Diag(), EnterScope(), ExitScope(), clang::Sema::OpenMPVarListDataTy::ExtraModifier, clang::Sema::OpenMPVarListDataTy::ExtraModifierLoc, clang::ActionResult< PtrTy, CompressInvalid >::get(), getLangOpts(), clang::Token::getLocation(), clang::Sema::GetNameFromUnqualifiedId(), clang::getOpenMPSimpleClauseType(), clang::Preprocessor::getSpelling(), clang::Token::is(), is(), clang::Sema::OpenMPVarListDataTy::IsMapTypeImplicit, clang::Token::isNot(), clang::isOpenMPDistributeDirective(), clang::isOpenMPTaskLoopDirective(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::Preprocessor::LookAhead(), clang::Sema::OpenMPVarListDataTy::MotionModifiers, clang::Sema::OpenMPVarListDataTy::MotionModifiersLoc, NextToken(), clang::OMPC_ADJUST_ARGS_unknown, clang::OMPC_DEPEND_unknown, clang::OMPC_LASTPRIVATE_unknown, clang::OMPC_MAP_unknown, clang::OMPC_MOTION_MODIFIER_unknown, clang::OMPC_REDUCTION_unknown, clang::Scope::OpenMPDirectiveScope, ParseAssignmentExpression(), parseMapperModifier(), parseMapType(), parseMapTypeModifiers(), ParseOpenMPReservedLocator(), ParseReductionId(), clang::Sema::OpenMPVarListDataTy::ReductionOrMapperId, clang::Sema::OpenMPVarListDataTy::ReductionOrMapperIdScopeSpec, clang::Sema::OpenMPVarListDataTy::RLoc, SkipUntil(), StopBeforeMatch, and Tok.
ParseStringLiteralExpression()
ExprResult clang::Parser::ParseStringLiteralExpression (bool AllowUserDefinedLiteral = false)
ParseTopLevelDecl() [1/2]
bool clang::Parser::ParseTopLevelDecl () inline
Definition at line 480 of file Parser.h.
References clang::Sema::NotACXX20Module, ParseTopLevelDecl(), and clang::Result.
Referenced by ParseFirstTopLevelDecl(), and ParseTopLevelDecl().
ParseTopLevelDecl() [2/2]
bool Parser::ParseTopLevelDecl (DeclGroupPtrTy & Result, Sema::ModuleImportState & ImportState)
ParseTopLevelDecl - Parse one top-level declaration.
ParseTopLevelDecl - Parse one top-level declaration, return whatever the action tells us to.
Returns true if the EOF was encountered.
This returns true if the EOF was encountered.
top-level-declaration: declaration [C++20] module-import-declaration
Definition at line 611 of file Parser.cpp.
References clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnModuleBegin(), clang::Sema::ActOnModuleEnd(), clang::Sema::ActOnModuleImport(), clang::Sema::ActOnModuleInclude(), ConsumeToken(), clang::Sema::ConvertDeclToDeclGroup(), clang::Preprocessor::Diag(), clang::Sema::FirstDecl, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Token::getAnnotationValue(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), getKind(), getLangOpts(), clang::Token::getLocation(), clang::Preprocessor::getMaxTokens(), clang::Preprocessor::getMaxTokensOverrideLoc(), clang::Preprocessor::getTokenCount(), clang::Sema::ImportAllowed, clang::Sema::ImportFinished, clang::Token::is(), clang::Module::isHeaderUnit(), clang::Preprocessor::isIncrementalProcessingEnabled(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), isNot(), clang::SourceLocation::isValid(), NextToken(), clang::Sema::NotACXX20Module, clang::Result, and clang::Sema::SetLateTemplateParser().
ParseTypeName()
TypeResult Parser::ParseTypeName (SourceRange * Range = nullptr, DeclaratorContext Context = DeclaratorContext::TypeName, AccessSpecifier AS = AS_none, Decl ** OwnedType = nullptr, ParsedAttributes * Attrs = nullptr)
ParseTypeName type-name: [C99 6.7.6] specifier-qualifier-list abstract-declarator[opt].
Called type-id in C++.
Definition at line 44 of file ParseDecl.cpp.
References clang::Sema::ActOnTypeName(), clang::DeclSpec::addAttributes(), getCurScope(), clang::DeclSpec::getRepAsDecl(), clang::Declarator::getSourceRange(), clang::Declarator::isInvalidType(), clang::DeclSpec::isTypeSpecOwned(), and clang::ParsedAttributesView::none().
ParseUnqualifiedId()
bool Parser::ParseUnqualifiedId (CXXScopeSpec & SS, ParsedType ObjectType, bool ObjectHadErrors, bool EnteringContext, bool AllowDestructorName, bool AllowConstructorName, bool AllowDeductionGuide, SourceLocation * TemplateKWLoc, UnqualifiedId & Result)
Parse a C++ unqualified-id (or a C identifier), which describes the name of an entity.
      unqualified-id: [C++ expr.prim.general]
        identifier
        operator-function-id
        conversion-function-id
[C++0x] literal-operator-id [TODO]
        ~ class-name
        template-id
Parameters
SS The nested-name-specifier that preceded this unqualified-id. If non-empty, then we are parsing the unqualified-id of a qualified-id.
ObjectType if this unqualified-id occurs within a member access expression, the type of the base object whose member is being accessed.
ObjectHadErrors if this unqualified-id occurs within a member access expression, indicates whether the original subexpressions had any errors. When true, diagnostics for missing 'template' keyword will be supressed.
EnteringContext whether we are entering the scope of the nested-name-specifier.
AllowDestructorName whether we allow parsing of a destructor name.
AllowConstructorName whether we allow parsing a constructor name.
AllowDeductionGuide whether we allow parsing a deduction guide name.
Result on a successful parse, contains the parsed unqualified-id.
Returns
true if parsing fails, false otherwise.
Definition at line 2794 of file ParseExprCXX.cpp.
References clang::Sema::ActOnTemplateName(), clang::CXXScopeSpec::clear(), ConsumeToken(), clang::CPlusPlus, clang::CPlusPlus17, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), Diag(), clang::Sema::getConstructorName(), getCurScope(), clang::Sema::getDestructorName(), clang::Sema::getDestructorTypeForDecltype(), clang::Token::getIdentifierInfo(), getLangOpts(), clang::Token::getLocation(), Id, clang::IK_LiteralOperatorId, clang::IK_OperatorFunctionId, clang::Token::is(), is(), clang::Sema::isCurrentClassName(), clang::Sema::isDeductionGuideName(), clang::CXXScopeSpec::isEmpty(), clang::TemplateIdAnnotation::isInvalid(), clang::Token::isNot(), clang::CXXScopeSpec::isNotEmpty(), clang::CXXScopeSpec::isSet(), clang::SourceLocation::isValid(), clang::TemplateIdAnnotation::LAngleLoc, clang::TemplateIdAnnotation::Name, NextToken(), clang::TemplateIdAnnotation::RAngleLoc, clang::Result, clang::Sema::ShouldEnterDeclaratorScope(), clang::TemplateIdAnnotation::TemplateKWLoc, clang::TemplateIdAnnotation::TemplateNameLoc, and clang::TNK_Non_template.
ReenterTemplateScopes()
unsigned Parser::ReenterTemplateScopes (MultiParseScope & S, Decl * D)
Re-enter the template scopes for a declaration that might be a template.
Re-enter a possible template scope, creating as many template parameter scopes as necessary.
Returns
The number of template parameter scopes entered.
Definition at line 29 of file ParseTemplate.cpp.
References clang::Sema::ActOnReenterTemplateScope(), clang::Sema::getCurScope(), and clang::Scope::TemplateParamScope.
SkipMalformedDecl()
void Parser::SkipMalformedDecl ()
SkipMalformedDecl - Read tokens until we get to some likely good stopping point for skipping past a simple-declaration.
Skip until we reach something which seems like a sensible place to pick up parsing after a malformed declaration.
This will sometimes stop sooner than SkipUntil(tok::r_brace) would, but will never stop later.
Definition at line 1951 of file ParseDecl.cpp.
References ConsumeAnyToken(), ConsumeToken(), clang::Token::getKind(), is(), clang::Token::isAtStartOfLine(), clang::Token::isOneOf(), NextToken(), SkipUntil(), and TryConsumeToken().
SkipUntil() [1/4]
bool Parser::SkipUntil (ArrayRef< tok::TokenKind > Toks, SkipUntilFlags Flags = static_cast<SkipUntilFlags>(0))
SkipUntil - Read tokens until we get to the specified token, then consume it (unless no flag StopBeforeMatch).
Because we cannot guarantee that the token will ever occur, this skips to the next token, or to some likely good stopping point. If StopAtSemi is true, skipping will stop at a ';' character.
If SkipUntil finds the specified token, it returns true, otherwise it returns false.
Definition at line 278 of file Parser.cpp.
References ConsumeAnyToken(), ConsumeToken(), clang::Token::getKind(), HasFlagsSet(), clang::Token::is(), clang::Token::isNot(), SkipUntil(), StopAtCodeCompletion, StopAtSemi, and StopBeforeMatch.
SkipUntil() [2/4]
bool clang::Parser::SkipUntil (tok::TokenKind T, SkipUntilFlags Flags = static_cast<SkipUntilFlags>(0)) inline
SkipUntil - Read tokens until we get to the specified token, then consume it (unless StopBeforeMatch is specified).
Because we cannot guarantee that the token will ever occur, this skips to the next token, or to some likely good stopping point. If Flags has StopAtSemi flag, skipping will stop at a ';' character. Balances (), [], and {} delimiter tokens while skipping.
If SkipUntil finds the specified token, it returns true, otherwise it returns false.
Definition at line 1220 of file Parser.h.
References SkipUntil().
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), parseMapperModifier(), ParseOpenMPVarList(), SkipMalformedDecl(), SkipUntil(), SkipUntil(), SkipUntil(), and SkipUntil().
SkipUntil() [3/4]
bool clang::Parser::SkipUntil (tok::TokenKind T1, tok::TokenKind T2, SkipUntilFlags Flags = static_cast<SkipUntilFlags>(0)) inline
Definition at line 1224 of file Parser.h.
References SkipUntil().
SkipUntil() [4/4]
bool clang::Parser::SkipUntil (tok::TokenKind T1, tok::TokenKind T2, tok::TokenKind T3, SkipUntilFlags Flags = static_cast<SkipUntilFlags>(0)) inline
Definition at line 1229 of file Parser.h.
References SkipUntil().
TryAnnotateCXXScopeToken()
bool Parser::TryAnnotateCXXScopeToken (bool EnteringContext = false)
TryAnnotateScopeToken - Like TryAnnotateTypeOrScopeToken but only annotates C++ scope specifiers and template-ids.
This returns true if there was an error that could not be recovered from.
Note that this routine emits an error if you call it with ::new or ::delete as the current tokens, so only call it in contexts where these are invalid.
Definition at line 2131 of file Parser.cpp.
References clang::CPlusPlus, getLangOpts(), clang::CXXScopeSpec::isEmpty(), and MightBeCXXScopeToken().
Referenced by TryAnnotateOptionalCXXScopeToken().
TryAnnotateOptionalCXXScopeToken()
bool clang::Parser::TryAnnotateOptionalCXXScopeToken (bool EnteringContext = false) inline
Definition at line 868 of file Parser.h.
References MightBeCXXScopeToken(), and TryAnnotateCXXScopeToken().
TryAnnotateTypeOrScopeToken()
bool Parser::TryAnnotateTypeOrScopeToken ()
TryAnnotateTypeOrScopeToken - If the current token position is on a typename (possibly qualified in C++) or a C++ scope specifier not followed by a typename, TryAnnotateTypeOrScopeToken will replace one or more tokens with a single annotation token representing the typename or C++ scope respectively.
This simplifies handling of C++ scope specifiers and allows efficient backtracking without the need to re-parse and resolve nested-names and typenames. It will mainly be called when we expect to treat identifiers as typenames (if they are typenames). For example, in C we do not expect identifiers inside expressions to be treated as typenames so it will not be called for expressions in C. The benefit for C/ObjC is that a typename will be annotated and Actions.getTypeName will not be needed to be called again (e.g. getTypeName will not be called twice, once to check whether we have a declaration specifier, and another one to get the actual type inside ParseDeclarationSpecifiers).
This returns true if an error occurred.
Note that this routine emits an error if you call it with ::new or ::delete as the current tokens, so only call it in contexts where these are invalid.
Definition at line 1902 of file Parser.cpp.
References clang::Sema::ActOnTypenameType(), clang::Preprocessor::AnnotateCachedTokens(), ConsumeToken(), clang::CPlusPlus, Diag(), clang::Preprocessor::EnterToken(), clang::Token::getAnnotationRange(), getCurScope(), clang::Token::getIdentifierInfo(), getLangOpts(), clang::Token::getLastLoc(), clang::Token::getLocation(), clang::CXXScopeSpec::getRange(), clang::TemplateIdAnnotation::getTemplateArgs(), clang::Token::is(), is(), clang::Token::isAnnotation(), clang::Token::isEditorPlaceholder(), clang::CXXScopeSpec::isEmpty(), clang::TemplateIdAnnotation::isInvalid(), clang::TemplateIdAnnotation::LAngleLoc, clang::Preprocessor::Lex(), clang::TemplateIdAnnotation::mightBeType(), clang::TemplateIdAnnotation::Name, NextToken(), clang::TemplateIdAnnotation::NumArgs, clang::TemplateIdAnnotation::RAngleLoc, clang::Result, clang::Token::setAnnotationEndLoc(), clang::Token::setKind(), clang::Token::setLocation(), clang::TemplateIdAnnotation::Template, clang::TemplateIdAnnotation::TemplateKWLoc, clang::TemplateIdAnnotation::TemplateNameLoc, TryAnnotateTypeOrScopeToken(), TryAnnotateTypeOrScopeTokenAfterScopeSpec(), and clang::TypeError().
Referenced by TryAnnotateTypeOrScopeToken().
TryAnnotateTypeOrScopeTokenAfterScopeSpec()
bool Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec (CXXScopeSpec & SS, bool IsNewScope)
Try to annotate a type or scope token, having already parsed an optional scope specifier.
IsNewScope should be true unless the scope specifier was extracted from an existing tok::annot_cxxscope annotation.
An Objective-C object type followed by '<' is a specialization of a parameterized class type or a protocol-qualified type.
Definition at line 2017 of file Parser.cpp.
References clang::Preprocessor::AnnotateCachedTokens(), ConsumeToken(), clang::CPlusPlus, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::OpaquePtr< PtrTy >::get(), clang::CXXScopeSpec::getBeginLoc(), getCurScope(), clang::Token::getIdentifierInfo(), getLangOpts(), clang::Token::getLocation(), clang::Sema::getTypeName(), clang::Token::is(), is(), clang::CXXScopeSpec::isEmpty(), clang::CXXScopeSpec::isNotEmpty(), clang::Type::isObjCObjectPointerType(), clang::Type::isObjCObjectType(), clang::Sema::isTemplateName(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::TemplateIdAnnotation::Kind, NextToken(), clang::ObjC, clang::Token::setAnnotationEndLoc(), clang::Token::setKind(), clang::Token::setLocation(), clang::TNK_Type_template, and clang::TNK_Undeclared_template.
Referenced by TryAnnotateTypeOrScopeToken().
TryConsumeToken() [1/2]
bool clang::Parser::TryConsumeToken (tok::TokenKind Expected) inline
Definition at line 499 of file Parser.h.
References clang::Preprocessor::Lex(), and Tok.
Referenced by SkipMalformedDecl(), and TryConsumeToken().
TryConsumeToken() [2/2]
bool clang::Parser::TryConsumeToken (tok::TokenKind Expected, SourceLocation & Loc) inline
Definition at line 509 of file Parser.h.
References TryConsumeToken().
Friends And Related Symbol Documentation
BalancedDelimiterTracker
friend class BalancedDelimiterTracker friend
Definition at line 67 of file Parser.h.
ColonProtectionRAIIObject
friend class ColonProtectionRAIIObject friend
Definition at line 61 of file Parser.h.
InMessageExpressionRAIIObject
friend class InMessageExpressionRAIIObject friend
Definition at line 63 of file Parser.h.
ObjCDeclContextSwitch
friend class ObjCDeclContextSwitch friend
Definition at line 65 of file Parser.h.
operator|
SkipUntilFlags operator| (SkipUntilFlags L, SkipUntilFlags R) friend
Definition at line 1205 of file Parser.h.
ParenBraceBracketBalancer
friend class ParenBraceBracketBalancer friend
Definition at line 66 of file Parser.h.
ParsingOpenMPDirectiveRAII
friend class ParsingOpenMPDirectiveRAII friend
Definition at line 62 of file Parser.h.
PoisonSEHIdentifiersRAIIObject
friend class PoisonSEHIdentifiersRAIIObject friend
Definition at line 64 of file Parser.h.
Member Data Documentation
MisleadingIndentationElseLoc
SourceLocation clang::Parser::MisleadingIndentationElseLoc
The location of the first statement inside an else that might have a missleading indentation.
If there is no MisleadingIndentationChecker on an else active, this location is invalid.
Definition at line 1244 of file Parser.h.
The documentation for this class was generated from the following files:
include/clang/Parse/Parser.h
lib/Parse/ParseCXXInlineMethods.cpp
lib/Parse/ParseDecl.cpp
lib/Parse/ParseDeclCXX.cpp
lib/Parse/ParseExpr.cpp
lib/Parse/ParseExprCXX.cpp
lib/Parse/ParseHLSL.cpp
lib/Parse/ParseInit.cpp
lib/Parse/ParseObjc.cpp
lib/Parse/ParseOpenMP.cpp
lib/Parse/ParsePragma.cpp
lib/Parse/Parser.cpp
lib/Parse/ParseStmt.cpp
lib/Parse/ParseStmtAsm.cpp
lib/Parse/ParseTemplate.cpp
lib/Parse/ParseTentative.cpp