clang: clang::ento::PointerToMemberData Class Reference
clang::ento::PointerToMemberData Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h"
Public Types
using iterator = llvm::ImmutableList<const CXXBaseSpecifier *>::iterator
Public Member Functions
PointerToMemberData (const NamedDecl *D, llvm::ImmutableList< const CXXBaseSpecifier * > L)
iterator begin () const
iterator end () const
void Profile (llvm::FoldingSetNodeID &ID)
const NamedDecl * getDeclaratorDecl () const
It might return null.
llvm::ImmutableList< const CXXBaseSpecifier * > getCXXBaseList () const
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const NamedDecl *D, llvm::ImmutableList< const CXXBaseSpecifier * > L)
Detailed Description
Definition at line 86 of file BasicValueFactory.h.
Member Typedef Documentation
iterator
using clang::ento::PointerToMemberData::iterator = llvm::ImmutableList<const CXXBaseSpecifier *>::iterator
Definition at line 95 of file BasicValueFactory.h.
Constructor & Destructor Documentation
PointerToMemberData()
clang::ento::PointerToMemberData::PointerToMemberData (const NamedDecl * D, llvm::ImmutableList< const CXXBaseSpecifier * > L) inline
Definition at line 91 of file BasicValueFactory.h.
Member Function Documentation
begin()
iterator clang::ento::PointerToMemberData::begin () const inline
Definition at line 97 of file BasicValueFactory.h.
end()
iterator clang::ento::PointerToMemberData::end () const inline
Definition at line 98 of file BasicValueFactory.h.
getCXXBaseList()
llvm::ImmutableList< const CXXBaseSpecifier * > clang::ento::PointerToMemberData::getCXXBaseList () const inline
Definition at line 108 of file BasicValueFactory.h.
Referenced by clang::ento::BasicValueFactory::accumCXXBase().
getDeclaratorDecl()
const NamedDecl * clang::ento::PointerToMemberData::getDeclaratorDecl () const inline
It might return null.
Definition at line 106 of file BasicValueFactory.h.
Referenced by clang::ento::BasicValueFactory::accumCXXBase().
Profile() [1/2]
void clang::ento::PointerToMemberData::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 103 of file BasicValueFactory.h.
References Profile().
Referenced by Profile().
Profile() [2/2]
void PointerToMemberData::Profile (llvm::FoldingSetNodeID & ID, const NamedDecl * D, llvm::ImmutableList< const CXXBaseSpecifier * > L) static
Definition at line 45 of file BasicValueFactory.cpp.
Referenced by clang::ento::BasicValueFactory::getPointerToMemberData().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h
lib/StaticAnalyzer/Core/BasicValueFactory.cpp