clang: AttrImporter Class Reference
AttrImporter Class Reference
Public Member Functions
AttrImporter (ASTImporter &I)
template<class T >
AttrArgImporter< T > importArg (const T &From)
template<typename T >
AttrArgArrayImporter< T > importArrayArg (const llvm::iterator_range< T * > &From, unsigned ArraySize)
template<typename T , typename... Arg>
void importAttr (const T *FromAttr, Arg &&...ImportedArg)
void cloneAttr (const Attr *FromAttr)
llvm::Expected< Attr * > getResult () &&
Detailed Description
Definition at line 8580 of file ASTImporter.cpp.
Constructor & Destructor Documentation
AttrImporter()
AttrImporter::AttrImporter (ASTImporter & I) inline
Definition at line 8587 of file ASTImporter.cpp.
Member Function Documentation
cloneAttr()
void AttrImporter::cloneAttr (const Attr * FromAttr) inline
Definition at line 8647 of file ASTImporter.cpp.
References clang::Attr::clone(), clang::AttributeCommonInfo::getRange(), clang::ASTImporter::getToContext(), clang::ASTNodeImporter::importChecked(), and clang::AttributeCommonInfo::setRange().
Referenced by clang::ASTImporter::Import().
getResult()
llvm::Expected< Attr * > AttrImporter::getResult () && inline
Definition at line 8659 of file ASTImporter.cpp.
importArg()
template<class T > AttrArgImporter< T > AttrImporter::importArg (const T & From) inline
Definition at line 8592 of file ASTImporter.cpp.
Referenced by clang::ASTImporter::Import().
importArrayArg()
template<typename T > AttrArgArrayImporter< T > AttrImporter::importArrayArg (const llvm::iterator_range< T * > & From, unsigned ArraySize) inline
Definition at line 8600 of file ASTImporter.cpp.
Referenced by clang::ASTImporter::Import().
importAttr()
template<typename T , typename... Arg> void AttrImporter::importAttr (const T * FromAttr, Arg &&... ImportedArg) inline
Definition at line 8614 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), clang::ASTNodeImporter::importChecked(), clang::Attr::setImplicit(), and clang::Attr::setPackExpansion().
Referenced by clang::ASTImporter::Import().
The documentation for this class was generated from the following file:
lib/AST/ASTImporter.cpp