clang: clang::sema::DelayedDiagnostic Class Reference
clang::sema::DelayedDiagnostic Class Reference
A diagnostic message which has been conditionally emitted pending the complete parsing of the current declaration.
#include "clang/Sema/DelayedDiagnostic.h"
Public Types
enum DDKind : unsigned char { Availability , Access , ForbiddenType }
Public Member Functions
void Destroy ()
AccessedEntity & getAccessData ()
const AccessedEntity & getAccessData () const
const NamedDecl * getAvailabilityReferringDecl () const
const NamedDecl * getAvailabilityOffendingDecl () const
StringRef getAvailabilityMessage () const
ArrayRef< SourceLocation > getAvailabilitySelectorLocs () const
AvailabilityResult getAvailabilityResult () const
unsigned getForbiddenTypeDiagnostic () const
The diagnostic ID to emit.
unsigned getForbiddenTypeArgument () const
QualType getForbiddenTypeOperand () const
const ObjCInterfaceDecl * getUnknownObjCClass () const
const ObjCPropertyDecl * getObjCProperty () const
bool getObjCPropertyAccess () const
Static Public Member Functions
static DelayedDiagnostic makeAvailability (AvailabilityResult AR, ArrayRef< SourceLocation > Locs, const NamedDecl *ReferringDecl, const NamedDecl *OffendingDecl, const ObjCInterfaceDecl *UnknownObjCClass, const ObjCPropertyDecl *ObjCProperty, StringRef Msg, bool ObjCPropertyAccess)
static DelayedDiagnostic makeAccess (SourceLocation Loc, const AccessedEntity &Entity)
static DelayedDiagnostic makeForbiddenType (SourceLocation loc, unsigned diagnostic, QualType type, unsigned argument)
Public Attributes
DDKind Kind
bool Triggered
SourceLocation Loc
Detailed Description
A diagnostic message which has been conditionally emitted pending the complete parsing of the current declaration.
Definition at line 124 of file DelayedDiagnostic.h.
Member Enumeration Documentation
DDKind
enum clang::sema::DelayedDiagnostic::DDKind : unsigned char
Enumerator
Availability
Access
ForbiddenType
Definition at line 126 of file DelayedDiagnostic.h.
Member Function Documentation
Destroy()
void DelayedDiagnostic::Destroy ()
Definition at line 59 of file DelayedDiagnostic.cpp.
References Access, Availability, AvailabilityData, ForbiddenType, and getAccessData().
getAccessData() [1/2]
AccessedEntity & clang::sema::DelayedDiagnostic::getAccessData () inline
Definition at line 168 of file DelayedDiagnostic.h.
References Access, and AccessData.
Referenced by Destroy(), clang::Sema::HandleDelayedAccessCheck(), and makeAccess().
getAccessData() [2/2]
const AccessedEntity & clang::sema::DelayedDiagnostic::getAccessData () const inline
Definition at line 172 of file DelayedDiagnostic.h.
References Access, and AccessData.
getAvailabilityMessage()
StringRef clang::sema::DelayedDiagnostic::getAvailabilityMessage () const inline
Definition at line 186 of file DelayedDiagnostic.h.
References Availability, and AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getAvailabilityOffendingDecl()
const NamedDecl * clang::sema::DelayedDiagnostic::getAvailabilityOffendingDecl () const inline
Definition at line 182 of file DelayedDiagnostic.h.
References AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getAvailabilityReferringDecl()
const NamedDecl * clang::sema::DelayedDiagnostic::getAvailabilityReferringDecl () const inline
Definition at line 177 of file DelayedDiagnostic.h.
References Availability, and AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getAvailabilityResult()
AvailabilityResult clang::sema::DelayedDiagnostic::getAvailabilityResult () const inline
Definition at line 197 of file DelayedDiagnostic.h.
References Availability, and AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getAvailabilitySelectorLocs()
ArrayRef< SourceLocation > clang::sema::DelayedDiagnostic::getAvailabilitySelectorLocs () const inline
Definition at line 191 of file DelayedDiagnostic.h.
References Availability, and AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getForbiddenTypeArgument()
unsigned clang::sema::DelayedDiagnostic::getForbiddenTypeArgument () const inline
Definition at line 211 of file DelayedDiagnostic.h.
References ForbiddenType, and ForbiddenTypeData.
Referenced by handleDelayedForbiddenType().
getForbiddenTypeDiagnostic()
unsigned clang::sema::DelayedDiagnostic::getForbiddenTypeDiagnostic () const inline
The diagnostic ID to emit.
Used like so: Diag(diag.Loc, diag.getForbiddenTypeDiagnostic()) << diag.getForbiddenTypeOperand() << diag.getForbiddenTypeArgument();
Definition at line 206 of file DelayedDiagnostic.h.
References ForbiddenType, and ForbiddenTypeData.
Referenced by handleDelayedForbiddenType(), and isForbiddenTypeAllowed().
getForbiddenTypeOperand()
QualType clang::sema::DelayedDiagnostic::getForbiddenTypeOperand () const inline
Definition at line 216 of file DelayedDiagnostic.h.
References ForbiddenType, ForbiddenTypeData, and clang::QualType::getFromOpaquePtr().
Referenced by handleDelayedForbiddenType().
getObjCProperty()
const ObjCPropertyDecl * clang::sema::DelayedDiagnostic::getObjCProperty () const inline
Definition at line 225 of file DelayedDiagnostic.h.
References AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
getObjCPropertyAccess()
bool clang::sema::DelayedDiagnostic::getObjCPropertyAccess () const inline
Definition at line 229 of file DelayedDiagnostic.h.
References AvailabilityData.
getUnknownObjCClass()
const ObjCInterfaceDecl * clang::sema::DelayedDiagnostic::getUnknownObjCClass () const inline
Definition at line 221 of file DelayedDiagnostic.h.
References AvailabilityData.
Referenced by clang::Sema::handleDelayedAvailabilityCheck().
makeAccess()
static DelayedDiagnostic clang::sema::DelayedDiagnostic::makeAccess (SourceLocation Loc, const AccessedEntity & Entity) inline static
Definition at line 144 of file DelayedDiagnostic.h.
References Access, getAccessData(), Kind, Loc, and Triggered.
Referenced by CheckAccess().
makeAvailability()
DelayedDiagnostic DelayedDiagnostic::makeAvailability (AvailabilityResult AR, ArrayRef< SourceLocation > Locs, const NamedDecl * ReferringDecl, const NamedDecl * OffendingDecl, const ObjCInterfaceDecl * UnknownObjCClass, const ObjCPropertyDecl * ObjCProperty, StringRef Msg, bool ObjCPropertyAccess) static
Definition at line 24 of file DelayedDiagnostic.cpp.
References Availability, AvailabilityData, Kind, Loc, memcpy(), and Triggered.
Referenced by EmitAvailabilityWarning().
makeForbiddenType()
static DelayedDiagnostic clang::sema::DelayedDiagnostic::makeForbiddenType (SourceLocation loc, unsigned diagnostic, QualType type, unsigned argument) inline static
Definition at line 154 of file DelayedDiagnostic.h.
References ForbiddenType, ForbiddenTypeData, Kind, Loc, and Triggered.
Referenced by clang::Sema::CheckParameter(), handleObjCOwnershipTypeAttr(), and inferARCLifetimeForPointee().
Member Data Documentation
AccessData
char clang::sema::DelayedDiagnostic::AccessData[sizeof(AccessedEntity)]
Access control.
Definition at line 258 of file DelayedDiagnostic.h.
Referenced by getAccessData(), and getAccessData().
AvailabilityData
struct AD clang::sema::DelayedDiagnostic::AvailabilityData
Definition at line 254 of file DelayedDiagnostic.h.
Referenced by Destroy(), getAvailabilityMessage(), getAvailabilityOffendingDecl(), getAvailabilityReferringDecl(), getAvailabilityResult(), getAvailabilitySelectorLocs(), getObjCProperty(), getObjCPropertyAccess(), getUnknownObjCClass(), and makeAvailability().
ForbiddenTypeData
struct FTD clang::sema::DelayedDiagnostic::ForbiddenTypeData
Definition at line 255 of file DelayedDiagnostic.h.
Referenced by getForbiddenTypeArgument(), getForbiddenTypeDiagnostic(), getForbiddenTypeOperand(), and makeForbiddenType().
Kind
DDKind clang::sema::DelayedDiagnostic::Kind
Definition at line 128 of file DelayedDiagnostic.h.
Referenced by clang::Sema::handleDelayedAvailabilityCheck(), makeAccess(), makeAvailability(), makeForbiddenType(), and clang::Sema::PopParsingDeclaration().
Loc
SourceLocation clang::sema::DelayedDiagnostic::Loc
Definition at line 131 of file DelayedDiagnostic.h.
Referenced by clang::Sema::HandleDelayedAccessCheck(), handleDelayedForbiddenType(), makeAccess(), makeAvailability(), and makeForbiddenType().
Triggered
bool clang::sema::DelayedDiagnostic::Triggered
Definition at line 129 of file DelayedDiagnostic.h.
Referenced by clang::Sema::HandleDelayedAccessCheck(), clang::Sema::handleDelayedAvailabilityCheck(), handleDelayedForbiddenType(), makeAccess(), makeAvailability(), makeForbiddenType(), and clang::Sema::PopParsingDeclaration().
The documentation for this class was generated from the following files:
include/clang/Sema/DelayedDiagnostic.h
lib/Sema/DelayedDiagnostic.cpp