clang: clang::DeclListNode::iterator Class Reference
clang::DeclListNode::iterator Class Reference
#include "clang/AST/DeclBase.h"
Public Types
using difference_type = ptrdiff_t
using value_type = NamedDecl*
using pointer = void
using reference = value_type
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator ()=default
reference operator* () const
void operator-> () const
bool operator== (const iterator &X) const
bool operator!= (const iterator &X) const
iterator & operator++ ()
iterator operator++ (int)
iterator end ()
Friends
class DeclContextLookupResult
class StoredDeclsList
Detailed Description
Definition at line 1275 of file DeclBase.h.
Member Typedef Documentation
difference_type
using clang::DeclListNode::iterator::difference_type = ptrdiff_t
Definition at line 1282 of file DeclBase.h.
iterator_category
using clang::DeclListNode::iterator::iterator_category = std::forward_iterator_tag
Definition at line 1286 of file DeclBase.h.
pointer
using clang::DeclListNode::iterator::pointer = void
Definition at line 1284 of file DeclBase.h.
reference
using clang::DeclListNode::iterator::reference = value_type
Definition at line 1285 of file DeclBase.h.
value_type
using clang::DeclListNode::iterator::value_type = NamedDecl*
Definition at line 1283 of file DeclBase.h.
Constructor & Destructor Documentation
iterator()
clang::DeclListNode::iterator::iterator () default
Referenced by end().
Member Function Documentation
end()
iterator clang::DeclListNode::iterator::end () inline
Definition at line 1314 of file DeclBase.h.
References iterator().
Referenced by findOrdinaryMember(), and clang::Sema::LookupQualifiedName().
operator!=()
bool clang::DeclListNode::iterator::operator!= (const iterator & X) const inline
Definition at line 1298 of file DeclBase.h.
References X().
operator*()
reference clang::DeclListNode::iterator::operator* () const inline
Definition at line 1290 of file DeclBase.h.
operator++() [1/2]
iterator & clang::DeclListNode::iterator::operator++ () inline
Definition at line 1299 of file DeclBase.h.
operator++() [2/2]
iterator clang::DeclListNode::iterator::operator++ (int) inline
Definition at line 1308 of file DeclBase.h.
operator->()
void clang::DeclListNode::iterator::operator-> () const inline
Definition at line 1296 of file DeclBase.h.
operator==()
bool clang::DeclListNode::iterator::operator== (const iterator & X) const inline
Definition at line 1297 of file DeclBase.h.
References X().
Friends And Related Symbol Documentation
DeclContextLookupResult
friend class DeclContextLookupResult friend
Definition at line 1276 of file DeclBase.h.
StoredDeclsList
friend class StoredDeclsList friend
Definition at line 1277 of file DeclBase.h.
The documentation for this class was generated from the following file:
include/clang/AST/DeclBase.h