clang: clang::TokenLexer Class Reference
clang::TokenLexer Class Reference
TokenLexer - This implements a lexer that returns tokens from a macro body or token stream instead of lexing from a character buffer.
#include "clang/Lex/TokenLexer.h"
Public Member Functions
TokenLexer (Token &Tok, SourceLocation ILEnd, MacroInfo *MI, MacroArgs *ActualArgs, Preprocessor &pp)
Create a TokenLexer for the specified macro with the specified actual arguments.
TokenLexer (const Token *TokArray, unsigned NumToks, bool DisableExpansion, bool ownsTokens, bool isReinject, Preprocessor &pp)
Create a TokenLexer for the specified token stream.
TokenLexer (const TokenLexer &)=delete
TokenLexer & operator= (const TokenLexer &)=delete
~TokenLexer ()
void Init (Token &Tok, SourceLocation ELEnd, MacroInfo *MI, MacroArgs *Actuals)
Initialize this TokenLexer to expand from the specified macro with the specified argument information.
void Init (const Token *TokArray, unsigned NumToks, bool DisableMacroExpansion, bool OwnsTokens, bool IsReinject)
Initialize this TokenLexer with the specified token stream.
unsigned isNextTokenLParen () const
If the next token lexed will pop this macro off the expansion stack, return 2.
bool Lex (Token &Tok)
Lex and return a token from this macro stream.
bool isParsingPreprocessorDirective () const
isParsingPreprocessorDirective - Return true if we are in the middle of a preprocessor directive.
Friends
class Preprocessor
Detailed Description
TokenLexer - This implements a lexer that returns tokens from a macro body or token stream instead of lexing from a character buffer.
This is used for macro expansion and _Pragma handling, for example.
Definition at line 30 of file TokenLexer.h.
Constructor & Destructor Documentation
TokenLexer() [1/3]
clang::TokenLexer::TokenLexer (Token & Tok, SourceLocation ILEnd, MacroInfo * MI, MacroArgs * ActualArgs, Preprocessor & pp) inline
Create a TokenLexer for the specified macro with the specified actual arguments.
Note that this ctor takes ownership of the ActualArgs pointer. ILEnd specifies the location of the ')' for a function-like macro or the identifier for an object-like macro.
Definition at line 108 of file TokenLexer.h.
References Init(), and Tok.
TokenLexer() [2/3]
clang::TokenLexer::TokenLexer (const Token * TokArray, unsigned NumToks, bool DisableExpansion, bool ownsTokens, bool isReinject, Preprocessor & pp) inline
Create a TokenLexer for the specified token stream.
If 'OwnsTokens' is specified, this takes ownership of the tokens and delete[]'s them when the token lexer is empty.
Definition at line 117 of file TokenLexer.h.
References Init().
TokenLexer() [3/3]
clang::TokenLexer::TokenLexer (const TokenLexer &) delete
~TokenLexer()
clang::TokenLexer::~TokenLexer () inline
Definition at line 125 of file TokenLexer.h.
Member Function Documentation
Init() [1/2]
void TokenLexer::Init (const Token * TokArray, unsigned NumToks, bool disableMacroExpansion, bool ownsTokens, bool isReinject)
Initialize this TokenLexer with the specified token stream.
Create a TokenLexer for the specified token stream.
This does not take ownership of the specified token vector.
DisableExpansion is true when macro expansion of tokens lexed from this stream should be disabled.
This does not take ownership of the specified token vector.
Definition at line 94 of file TokenLexer.cpp.
References clang::Token::hasLeadingSpace(), and clang::Token::isAtStartOfLine().
Init() [2/2]
void TokenLexer::Init (Token & Tok, SourceLocation ELEnd, MacroInfo * MI, MacroArgs * Actuals)
Initialize this TokenLexer to expand from the specified macro with the specified argument information.
Create a TokenLexer for the specified macro with the specified actual arguments.
Note that this ctor takes ownership of the ActualArgs pointer. ILEnd specifies the location of the ')' for a function-like macro or the identifier for an object-like macro.
Note that this ctor takes ownership of the ActualArgs pointer.
Definition at line 38 of file TokenLexer.cpp.
References clang::MacroInfo::DisableMacro(), clang::MacroInfo::getDefinitionLength(), clang::Token::getLocation(), clang::MacroInfo::getNumParams(), clang::Preprocessor::getSourceManager(), clang::Token::hasLeadingSpace(), is(), clang::Token::isAtStartOfLine(), clang::MacroInfo::isFunctionLike(), clang::SourceLocation::isValid(), SM, Tok, clang::MacroInfo::tokens_begin(), and clang::MacroInfo::tokens_end().
Referenced by TokenLexer(), and TokenLexer().
isNextTokenLParen()
unsigned TokenLexer::isNextTokenLParen () const
If the next token lexed will pop this macro off the expansion stack, return 2.
isNextTokenLParen - If the next token lexed will pop this macro off the expansion stack, return 2.
If the next unexpanded token is a '(', return 1, otherwise return 0.
Definition at line 926 of file TokenLexer.cpp.
References clang::Token::is().
isParsingPreprocessorDirective()
bool TokenLexer::isParsingPreprocessorDirective () const
isParsingPreprocessorDirective - Return true if we are in the middle of a preprocessor directive.
Definition at line 935 of file TokenLexer.cpp.
References clang::Token::is().
Lex()
bool TokenLexer::Lex (Token & Tok)
Lex and return a token from this macro stream.
Lex - Lex and return a token from this macro stream.
Definition at line 621 of file TokenLexer.cpp.
References clang::Token::getIdentifierInfo(), clang::Preprocessor::getLangOpts(), clang::Token::getLength(), clang::Token::getLocation(), clang::Preprocessor::getSourceManager(), clang::IdentifierInfo::getTokenID(), clang::Preprocessor::HandleEndOfTokenLexer(), clang::Preprocessor::HandleIdentifier(), clang::Preprocessor::HandlePoisonedIdentifier(), clang::Token::is(), is(), clang::Token::isAnnotation(), clang::IdentifierInfo::isHandleIdentifierCase(), clang::IdentifierInfo::isPoisoned(), clang::Token::IsReinjected, clang::SourceLocation::isValid(), isWideStringLiteralFromMacro(), clang::Token::LeadingEmptyMacro, clang::Token::LeadingSpace, clang::Token::setFlag(), clang::Token::setFlagValue(), clang::Token::setKind(), clang::Token::setLocation(), SM, clang::Token::StartOfLine, clang::Token::startToken(), and Tok.
operator=()
TokenLexer & clang::TokenLexer::operator= (const TokenLexer &) delete
Friends And Related Symbol Documentation
Preprocessor
friend class Preprocessor friend
Definition at line 31 of file TokenLexer.h.
The documentation for this class was generated from the following files:
include/clang/Lex/TokenLexer.h
lib/Lex/TokenLexer.cpp