clang: clang::threadSafety::til::SCFG Class Reference
clang::threadSafety::til::SCFG Class Reference
An SCFG is a control-flow graph.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Types
using BlockArray = SimpleArray<BasicBlock *>
using iterator = BlockArray::iterator
using const_iterator = BlockArray::const_iterator
Public Member Functions
SCFG (MemRegionRef A, unsigned Nblocks)
Arena (Cfg.Arena)
Blocks (std::move(Ba))
bool valid () const
Return true if this CFG is valid.
bool normal () const
Return true if this CFG has been normalized.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
const BasicBlock * entry () const
BasicBlock * entry ()
const BasicBlock * exit () const
BasicBlock * exit ()
size_t numBlocks () const
Return the number of blocks in the CFG.
unsigned numInstructions ()
Return the total number of instructions in the CFG.
void add (BasicBlock *BB)
void setEntry (BasicBlock *BB)
void setExit (BasicBlock *BB)
void computeNormalForm ()
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const SCFG *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Public Attributes
: SExpr(COP_SCFG)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
An SCFG is a control-flow graph.
It consists of a set of basic blocks, each of which terminates in a branch to another basic block. There is one entry point, and one exit point.
Definition at line 1688 of file ThreadSafetyTIL.h.
Member Typedef Documentation
BlockArray
using clang::threadSafety::til::SCFG::BlockArray = SimpleArray<BasicBlock *>
Definition at line 1690 of file ThreadSafetyTIL.h.
const_iterator
using clang::threadSafety::til::SCFG::const_iterator = BlockArray::const_iterator
Definition at line 1692 of file ThreadSafetyTIL.h.
iterator
using clang::threadSafety::til::SCFG::iterator = BlockArray::iterator
Definition at line 1691 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
SCFG()
clang::threadSafety::til::SCFG::SCFG (MemRegionRef A, unsigned Nblocks) inline
Definition at line 1694 of file ThreadSafetyTIL.h.
Member Function Documentation
add()
void clang::threadSafety::til::SCFG::add (BasicBlock * BB) inline
Definition at line 1743 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::push_back(), and clang::threadSafety::til::SimpleArray< T >::reserveCheck().
Arena()
clang::threadSafety::til::SCFG::Arena (Cfg. Arena)
begin() [1/2]
iterator clang::threadSafety::til::SCFG::begin () inline
Definition at line 1720 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::begin().
begin() [2/2]
const_iterator clang::threadSafety::til::SCFG::begin () const inline
Definition at line 1723 of file ThreadSafetyTIL.h.
References cbegin().
Blocks()
clang::threadSafety::til::SCFG::Blocks (std::move(Ba)) inline
Definition at line 1706 of file ThreadSafetyTIL.h.
cbegin()
const_iterator clang::threadSafety::til::SCFG::cbegin () const inline
Definition at line 1726 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::cbegin().
Referenced by begin().
cend()
const_iterator clang::threadSafety::til::SCFG::cend () const inline
Definition at line 1727 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::cend().
Referenced by end().
classof()
static bool clang::threadSafety::til::SCFG::classof (const SExpr * E) inline static
Definition at line 1710 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::SCFG::compare (const SCFG * E, C & Cmp) const inline
Definition at line 1768 of file ThreadSafetyTIL.h.
computeNormalForm()
void SCFG::computeNormalForm ()
Definition at line 290 of file ThreadSafetyTIL.cpp.
References clang::threadSafety::til::SExpr::Block, computeNodeID(), and computeNodeSize().
end() [1/2]
iterator clang::threadSafety::til::SCFG::end () inline
Definition at line 1721 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::end().
end() [2/2]
const_iterator clang::threadSafety::til::SCFG::end () const inline
Definition at line 1724 of file ThreadSafetyTIL.h.
References cend().
entry() [1/2]
BasicBlock * clang::threadSafety::til::SCFG::entry () inline
Definition at line 1730 of file ThreadSafetyTIL.h.
entry() [2/2]
const BasicBlock * clang::threadSafety::til::SCFG::entry () const inline
Definition at line 1729 of file ThreadSafetyTIL.h.
exit() [1/2]
BasicBlock * clang::threadSafety::til::SCFG::exit () inline
Definition at line 1732 of file ThreadSafetyTIL.h.
exit() [2/2]
const BasicBlock * clang::threadSafety::til::SCFG::exit () const inline
Definition at line 1731 of file ThreadSafetyTIL.h.
normal()
bool clang::threadSafety::til::SCFG::normal () const inline
Return true if this CFG has been normalized.
After normalization, blocks are in topological order, and block and instruction IDs have been assigned.
Definition at line 1718 of file ThreadSafetyTIL.h.
numBlocks()
size_t clang::threadSafety::til::SCFG::numBlocks () const inline
Return the number of blocks in the CFG.
Block::blockID() will return a number less than numBlocks();
Definition at line 1736 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::size().
numInstructions()
unsigned clang::threadSafety::til::SCFG::numInstructions () inline
Return the total number of instructions in the CFG.
This is useful for building instruction side-tables; A call to SExpr::id() will return a number less than numInstructions().
Definition at line 1741 of file ThreadSafetyTIL.h.
setEntry()
void clang::threadSafety::til::SCFG::setEntry (BasicBlock * BB) inline
Definition at line 1750 of file ThreadSafetyTIL.h.
setExit()
void clang::threadSafety::til::SCFG::setExit (BasicBlock * BB) inline
Definition at line 1751 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::SCFG::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1756 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::size().
valid()
bool clang::threadSafety::til::SCFG::valid () const inline
Return true if this CFG is valid.
Definition at line 1713 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::size().
Member Data Documentation
__pad0__
clang::threadSafety::til::SCFG::__pad0__
Definition at line 1694 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h
lib/Analysis/ThreadSafetyTIL.cpp