clang: clang::driver::CudaInstallationDetector Class Reference
clang::driver::CudaInstallationDetector Class Reference
A class to find a viable CUDA installation.
#include "/root/llvm-project/clang/lib/Driver/ToolChains/Cuda.h"
Public Member Functions
CudaInstallationDetector (const Driver &D, const llvm::Triple &HostTriple, const llvm::opt::ArgList &Args)
void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
void CheckCudaVersionSupportsArch (CudaArch Arch) const
Emit an error if Version does not support the given Arch.
bool isValid () const
Check whether we detected a valid Cuda install.
void print (raw_ostream &OS) const
Print information about the detected CUDA installation.
CudaVersion version () const
Get the detected Cuda install's version.
StringRef getInstallPath () const
Get the detected Cuda installation path.
StringRef getBinPath () const
Get the detected path to Cuda's bin directory.
StringRef getIncludePath () const
Get the detected Cuda Include path.
StringRef getLibPath () const
Get the detected Cuda library path.
StringRef getLibDevicePath () const
Get the detected Cuda device library path.
std::string getLibDeviceFile (StringRef Gpu) const
Get libdevice file for given architecture.
void WarnIfUnsupportedVersion ()
Detailed Description
A class to find a viable CUDA installation.
Definition at line 28 of file Cuda.h.
Constructor & Destructor Documentation
CudaInstallationDetector()
CudaInstallationDetector::CudaInstallationDetector (const Driver & D, const llvm::Triple & HostTriple, const llvm::opt::ArgList & Args)
Definition at line 116 of file Cuda.cpp.
References clang::CUDA_70, clang::CUDA_80, clang::CUDA_90, clang::CudaArchToString(), clang::driver::Driver::getVFS(), clang::driver::Distro::IsDebian(), clang::IsNVIDIAGpuArch(), clang::driver::Distro::IsUbuntu(), clang::LAST, clang::NEW, clang::SM_30, clang::driver::Driver::SysRoot, and clang::UNKNOWN.
Member Function Documentation
AddCudaIncludeArgs()
void CudaInstallationDetector::AddCudaIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const
Definition at line 284 of file Cuda.cpp.
References clang::driver::Driver::Diag(), isValid(), P, and clang::driver::Driver::ResourceDir.
Referenced by clang::driver::toolchains::CudaToolChain::AddCudaIncludeArgs(), clang::driver::toolchains::Darwin::AddCudaIncludeArgs(), clang::driver::toolchains::FreeBSD::AddCudaIncludeArgs(), clang::driver::toolchains::Linux::AddCudaIncludeArgs(), and clang::driver::toolchains::MSVCToolChain::AddCudaIncludeArgs().
CheckCudaVersionSupportsArch()
void CudaInstallationDetector::CheckCudaVersionSupportsArch (CudaArch Arch) const
Emit an error if Version does not support the given Arch.
If either Version or Arch is unknown, does not emit an error. Emits at most one error per Arch.
Definition at line 308 of file Cuda.cpp.
References clang::CudaArchToString(), clang::CudaVersionToString(), clang::driver::Driver::Diag(), int, clang::MaxVersionForCudaArch(), clang::MinVersionForCudaArch(), and clang::UNKNOWN.
Referenced by clang::driver::toolchains::CudaToolChain::AddCudaIncludeArgs().
getBinPath()
StringRef clang::driver::CudaInstallationDetector::getBinPath () const inline
Get the detected path to Cuda's bin directory.
Definition at line 70 of file Cuda.h.
getIncludePath()
StringRef clang::driver::CudaInstallationDetector::getIncludePath () const inline
Get the detected Cuda Include path.
Definition at line 72 of file Cuda.h.
Referenced by clang::driver::toolchains::CudaToolChain::AddClangSystemIncludeArgs().
getInstallPath()
StringRef clang::driver::CudaInstallationDetector::getInstallPath () const inline
Get the detected Cuda installation path.
Definition at line 68 of file Cuda.h.
Referenced by clang::driver::tools::LinkerWrapper::ConstructJob().
getLibDeviceFile()
std::string clang::driver::CudaInstallationDetector::getLibDeviceFile (StringRef Gpu) const inline
Get libdevice file for given architecture.
Definition at line 78 of file Cuda.h.
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions().
getLibDevicePath()
StringRef clang::driver::CudaInstallationDetector::getLibDevicePath () const inline
Get the detected Cuda device library path.
Definition at line 76 of file Cuda.h.
getLibPath()
StringRef clang::driver::CudaInstallationDetector::getLibPath () const inline
Get the detected Cuda library path.
Definition at line 74 of file Cuda.h.
isValid()
bool clang::driver::CudaInstallationDetector::isValid () const inline
Check whether we detected a valid Cuda install.
Definition at line 58 of file Cuda.h.
Referenced by clang::driver::toolchains::CudaToolChain::AddClangSystemIncludeArgs(), AddCudaIncludeArgs(), clang::driver::tools::LinkerWrapper::ConstructJob(), clang::driver::toolchains::CudaToolChain::CudaToolChain(), and print().
print()
void CudaInstallationDetector::print (raw_ostream & OS) const
Print information about the detected CUDA installation.
Definition at line 325 of file Cuda.cpp.
References clang::CudaVersionToString(), and isValid().
Referenced by clang::driver::toolchains::Darwin::printVerboseInfo(), clang::driver::toolchains::Generic_GCC::printVerboseInfo(), and clang::driver::toolchains::MSVCToolChain::printVerboseInfo().
version()
CudaVersion clang::driver::CudaInstallationDetector::version () const inline
Get the detected Cuda install's version.
Definition at line 63 of file Cuda.h.
References clang::NEW, and clang::PARTIALLY_SUPPORTED.
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), and clang::driver::tools::NVPTX::getNVPTXTargetFeatures().
WarnIfUnsupportedVersion()
void CudaInstallationDetector::WarnIfUnsupportedVersion ()
Definition at line 102 of file Cuda.cpp.
References clang::CudaVersionToString(), clang::driver::Driver::Diag(), clang::FULLY_SUPPORTED, and clang::PARTIALLY_SUPPORTED.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Cuda.h
lib/Driver/ToolChains/Cuda.cpp