clang: clang::tooling::ASTSrcLocProcessor Class Reference
clang::tooling::ASTSrcLocProcessor Class Reference
#include "/root/llvm-project/clang/lib/Tooling/DumpTool/ASTSrcLocProcessor.h"
Public Member Functions
ASTSrcLocProcessor (StringRef JsonPath)
std::unique_ptr< ASTConsumer > createASTConsumer (CompilerInstance &Compiler, StringRef File)
void generate ()
void generateEmpty ()
Public Member Functions inherited from clang::ast_matchers::MatchFinder::MatchCallback
virtual ~MatchCallback ()
virtual void onStartOfTranslationUnit ()
Called at the start of each translation unit.
virtual void onEndOfTranslationUnit ()
Called at the end of each translation unit.
virtual StringRef getID () const
An id used to group the matchers.
Detailed Description
Definition at line 25 of file ASTSrcLocProcessor.h.
Constructor & Destructor Documentation
ASTSrcLocProcessor()
ASTSrcLocProcessor::ASTSrcLocProcessor (StringRef JsonPath) explicit
Definition at line 19 of file ASTSrcLocProcessor.cpp.
References clang::ast_matchers::cxxRecordDecl, clang::ast_matchers::hasAnyName, clang::ast_matchers::namedDecl, and clang::ast_matchers::optionally.
Member Function Documentation
createASTConsumer()
std::unique_ptr< clang::ASTConsumer > ASTSrcLocProcessor::createASTConsumer (clang::CompilerInstance & Compiler, StringRef File)
Definition at line 47 of file ASTSrcLocProcessor.cpp.
Referenced by ASTSrcLocGenerationAction::CreateASTConsumer().
generate()
void ASTSrcLocProcessor::generate ()
Definition at line 135 of file ASTSrcLocProcessor.cpp.
References toJSON(), and WriteJSON().
Referenced by ASTSrcLocGenerationAction::ExecuteAction().
generateEmpty()
void ASTSrcLocProcessor::generateEmpty ()
Definition at line 140 of file ASTSrcLocProcessor.cpp.
References WriteJSON().
Referenced by ASTSrcLocGenerationAction::ExecuteAction().
The documentation for this class was generated from the following files:
lib/Tooling/DumpTool/ASTSrcLocProcessor.h
lib/Tooling/DumpTool/ASTSrcLocProcessor.cpp