clang: clang::SwitchStmt Class Reference
clang::SwitchStmt Class Reference final
SwitchStmt - This represents a 'switch' stmt.
#include "clang/AST/Stmt.h"
Public Member Functions
bool hasInitStorage () const
True if this SwitchStmt has storage for an init statement.
bool hasVarStorage () const
True if this SwitchStmt has storage for a condition variable.
Expr * getCond ()
const Expr * getCond () const
void setCond (Expr *Cond)
Stmt * getBody ()
const Stmt * getBody () const
void setBody (Stmt *Body)
Stmt * getInit ()
const Stmt * getInit () const
void setInit (Stmt *Init)
VarDecl * getConditionVariable ()
Retrieve the variable declared in this "switch" statement, if any.
const VarDecl * getConditionVariable () const
void setConditionVariable (const ASTContext &Ctx, VarDecl *VD)
Set the condition variable in this switch statement.
DeclStmt * getConditionVariableDeclStmt ()
If this SwitchStmt has a condition variable, return the faux DeclStmt associated with the creation of that condition variable.
const DeclStmt * getConditionVariableDeclStmt () const
SwitchCase * getSwitchCaseList ()
const SwitchCase * getSwitchCaseList () const
void setSwitchCaseList (SwitchCase *SC)
SourceLocation getSwitchLoc () const
void setSwitchLoc (SourceLocation L)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
void setBody (Stmt *S, SourceLocation SL)
void addSwitchCase (SwitchCase *SC)
void setAllEnumCasesCovered ()
Set a flag in the SwitchStmt indicating that if the 'switch (X)' is a switch over an enum value then all cases have been explicitly covered.
bool isAllEnumCasesCovered () const
Returns true if the SwitchStmt is a switch of an enum value and all cases have been explicitly covered.
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static SwitchStmt * Create (const ASTContext &Ctx, Stmt *Init, VarDecl *Var, Expr *Cond, SourceLocation LParenLoc, SourceLocation RParenLoc)
Create a switch statement.
static SwitchStmt * CreateEmpty (const ASTContext &Ctx, bool HasInit, bool HasVar)
Create an empty switch statement optionally with storage for an init expression and a condition variable.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
SwitchStmt - This represents a 'switch' stmt.
Definition at line 2182 of file Stmt.h.
Member Function Documentation
addSwitchCase()
void clang::SwitchStmt::addSwitchCase (SwitchCase * SC) inline
Definition at line 2331 of file Stmt.h.
References clang::SwitchCase::getNextSwitchCase(), and clang::SwitchCase::setNextSwitchCase().
children() [1/2]
child_range clang::SwitchStmt::children () inline
Definition at line 2355 of file Stmt.h.
children() [2/2]
const_child_range clang::SwitchStmt::children () const inline
Definition at line 2361 of file Stmt.h.
classof()
static bool clang::SwitchStmt::classof (const Stmt * T) inline static
Definition at line 2367 of file Stmt.h.
Create()
SwitchStmt * SwitchStmt::Create (const ASTContext & Ctx, Stmt * Init, VarDecl * Var, Expr * Cond, SourceLocation LParenLoc, SourceLocation RParenLoc) static
Create a switch statement.
Definition at line 1078 of file Stmt.cpp.
References clang::ASTContext::Allocate(), and clang::Cond.
Referenced by clang::Sema::ActOnStartOfSwitchStmt(), and clang::ASTNodeImporter::VisitSwitchStmt().
CreateEmpty()
SwitchStmt * SwitchStmt::CreateEmpty (const ASTContext & Ctx, bool HasInit, bool HasVar) static
Create an empty switch statement optionally with storage for an init expression and a condition variable.
Definition at line 1089 of file Stmt.cpp.
References clang::ASTContext::Allocate().
getBeginLoc()
SourceLocation clang::SwitchStmt::getBeginLoc () const inline
Definition at line 2348 of file Stmt.h.
References getSwitchLoc().
getBody() [1/2]
Stmt * clang::SwitchStmt::getBody () inline
Definition at line 2258 of file Stmt.h.
Referenced by EvaluateSwitch(), and getEndLoc().
getBody() [2/2]
const Stmt * clang::SwitchStmt::getBody () const inline
Definition at line 2259 of file Stmt.h.
getCond() [1/2]
Expr * clang::SwitchStmt::getCond () inline
Definition at line 2246 of file Stmt.h.
Referenced by clang::Sema::ActOnFinishSwitchStmt(), EvaluateSwitch(), getEndLoc(), and clang::ento::ExprEngine::processSwitch().
getCond() [2/2]
const Expr * clang::SwitchStmt::getCond () const inline
Definition at line 2250 of file Stmt.h.
getConditionVariable() [1/2]
VarDecl * SwitchStmt::getConditionVariable ()
Retrieve the variable declared in this "switch" statement, if any.
In the following example, "x" is the condition variable.
switch (int x = foo()) {
  case 0: break;
  // ...
}
Definition at line 1097 of file Stmt.cpp.
References clang::cast(), and getConditionVariableDeclStmt().
Referenced by EvaluateSwitch(), and getConditionVariable().
getConditionVariable() [2/2]
const VarDecl * clang::SwitchStmt::getConditionVariable () const inline
Definition at line 2293 of file Stmt.h.
References getConditionVariable().
getConditionVariableDeclStmt() [1/2]
DeclStmt * clang::SwitchStmt::getConditionVariableDeclStmt () inline
If this SwitchStmt has a condition variable, return the faux DeclStmt associated with the creation of that condition variable.
Definition at line 2303 of file Stmt.h.
References hasVarStorage().
Referenced by getConditionVariable().
getConditionVariableDeclStmt() [2/2]
const DeclStmt * clang::SwitchStmt::getConditionVariableDeclStmt () const inline
Definition at line 2309 of file Stmt.h.
References hasVarStorage().
getEndLoc()
SourceLocation clang::SwitchStmt::getEndLoc () const inline
Definition at line 2349 of file Stmt.h.
References getBody(), getCond(), clang::Stmt::getEndLoc(), and getEndLoc().
Referenced by getEndLoc().
getInit() [1/2]
Stmt * clang::SwitchStmt::getInit () inline
Definition at line 2267 of file Stmt.h.
References hasInitStorage().
Referenced by EvaluateSwitch().
getInit() [2/2]
const Stmt * clang::SwitchStmt::getInit () const inline
Definition at line 2272 of file Stmt.h.
References hasInitStorage().
getLParenLoc()
SourceLocation clang::SwitchStmt::getLParenLoc () const inline
Definition at line 2321 of file Stmt.h.
getRParenLoc()
SourceLocation clang::SwitchStmt::getRParenLoc () const inline
Definition at line 2323 of file Stmt.h.
getSwitchCaseList() [1/2]
SwitchCase * clang::SwitchStmt::getSwitchCaseList () inline
Definition at line 2315 of file Stmt.h.
Referenced by clang::Sema::ActOnFinishSwitchStmt(), and EvaluateSwitch().
getSwitchCaseList() [2/2]
const SwitchCase * clang::SwitchStmt::getSwitchCaseList () const inline
Definition at line 2316 of file Stmt.h.
getSwitchLoc()
SourceLocation clang::SwitchStmt::getSwitchLoc () const inline
Definition at line 2319 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by getBeginLoc().
hasInitStorage()
bool clang::SwitchStmt::hasInitStorage () const inline
True if this SwitchStmt has storage for an init statement.
Definition at line 2241 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by getInit(), getInit(), setInit(), and clang::JSONNodeDumper::VisitSwitchStmt().
hasVarStorage()
bool clang::SwitchStmt::hasVarStorage () const inline
True if this SwitchStmt has storage for a condition variable.
Definition at line 2244 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by getConditionVariableDeclStmt(), getConditionVariableDeclStmt(), setConditionVariable(), and clang::JSONNodeDumper::VisitSwitchStmt().
isAllEnumCasesCovered()
bool clang::SwitchStmt::isAllEnumCasesCovered () const inline
Returns true if the SwitchStmt is a switch of an enum value and all cases have been explicitly covered.
Definition at line 2344 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by clang::ento::ExprEngine::processSwitch().
setAllEnumCasesCovered()
void clang::SwitchStmt::setAllEnumCasesCovered () inline
Set a flag in the SwitchStmt indicating that if the 'switch (X)' is a switch over an enum value then all cases have been explicitly covered.
Definition at line 2340 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by clang::Sema::ActOnFinishSwitchStmt().
setBody() [1/2]
void clang::SwitchStmt::setBody (Stmt * Body) inline
Definition at line 2263 of file Stmt.h.
Referenced by clang::Sema::ActOnFinishSwitchStmt(), and setBody().
setBody() [2/2]
void clang::SwitchStmt::setBody (Stmt * S, SourceLocation SL) inline
Definition at line 2326 of file Stmt.h.
References setBody(), and setSwitchLoc().
setCond()
void clang::SwitchStmt::setCond (Expr * Cond) inline
Definition at line 2254 of file Stmt.h.
References clang::Cond.
setConditionVariable()
void SwitchStmt::setConditionVariable (const ASTContext & Ctx, VarDecl * VD)
Set the condition variable in this switch statement.
The switch statement must have storage for it.
Definition at line 1104 of file Stmt.cpp.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), hasVarStorage(), and V.
setInit()
void clang::SwitchStmt::setInit (Stmt * Init) inline
Definition at line 2277 of file Stmt.h.
References hasInitStorage().
setLParenLoc()
void clang::SwitchStmt::setLParenLoc (SourceLocation Loc) inline
Definition at line 2322 of file Stmt.h.
setRParenLoc()
void clang::SwitchStmt::setRParenLoc (SourceLocation Loc) inline
Definition at line 2324 of file Stmt.h.
setSwitchCaseList()
void clang::SwitchStmt::setSwitchCaseList (SwitchCase * SC) inline
Definition at line 2317 of file Stmt.h.
setSwitchLoc()
void clang::SwitchStmt::setSwitchLoc (SourceLocation L) inline
Definition at line 2320 of file Stmt.h.
References clang::Stmt::SwitchStmtBits.
Referenced by setBody().
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp