clang: clang::OpaquePtr< PtrTy > Class Template Reference
clang::OpaquePtr< PtrTy > Class Template Reference
Wrapper for void* pointer.
#include "clang/Sema/Ownership.h"
Public Member Functions
OpaquePtr (std::nullptr_t=nullptr)
template<typename PointeeT >
PointeeT * getPtrTo () const
Returns plain pointer to the entity pointed by this wrapper.
template<typename PtrT >
PtrT getPtrAs () const
Returns pointer converted to the specified type.
PtrTy get () const
void set (PtrTy P)
operator bool () const
void * getAsOpaquePtr () const
Static Public Member Functions
static OpaquePtr make (PtrTy P)
static OpaquePtr getFromOpaquePtr (void *P)
Detailed Description
template<class PtrTy>
class clang::OpaquePtr< PtrTy >
Wrapper for void* pointer.
Template Parameters
PtrTy Either a pointer type like 'T*' or a type that behaves like a pointer.
This is a very simple POD type that wraps a pointer that the Parser doesn't know about but that Sema or another client does. The PtrTy template argument is used to make sure that "Decl" pointers are not compatible with "Type" pointers for example.
Definition at line 50 of file Ownership.h.
Constructor & Destructor Documentation
OpaquePtr()
template<class PtrTy > clang::OpaquePtr< PtrTy >::OpaquePtr (std::nullptr_t = nullptr) inline
Definition at line 58 of file Ownership.h.
Member Function Documentation
get()
template<class PtrTy > PtrTy clang::OpaquePtr< PtrTy >::get () const inline
Definition at line 80 of file Ownership.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnDeclStmt(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnForEachDeclStmt(), clang::Sema::ActOnOpenMPDeclareMapperType(), clang::Sema::ActOnOpenMPDeclareReductionDirectiveEnd(), clang::Sema::ActOnOpenMPDeclareReductionType(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnPackExpansion(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTemplateName(), clang::Sema::ActOnTemplateTypeArgument(), clang::Sema::ActOnTypenameType(), clang::Sema::ActOnUndeclaredTypeTemplateName(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::BuildTypeConstraint(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CodeCompleteObjCForCollection(), clang::Sema::containsUnexpandedParameterPacks(), CreateNewFunctionDecl(), clang::Sema::DiagnoseUnknownTypeName(), findOMPAlloctraitT(), findOMPDependT(), findOMPEventHandleT(), clang::OpaquePtr< PtrTy >::getPtrAs(), clang::OpaquePtr< PtrTy >::getPtrTo(), clang::Sema::GetTypeFromParser(), clang::Sema::getTypeName(), InventTemplateParameter(), clang::Declarator::isDeclarationOfFunction(), clang::Sema::isTemplateName(), clang::ParseAST(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ProduceTemplateArgumentSignatureHelp(), clang::TreeTransform< Derived >::RebuildTemplateName(), clang::TreeTransform< Derived >::RebuildTemplateName(), translateTemplateArgument(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
getAsOpaquePtr()
template<class PtrTy > void * clang::OpaquePtr< PtrTy >::getAsOpaquePtr () const inline
Definition at line 90 of file Ownership.h.
Referenced by clang::Sema::BuildCXXForRangeStmt(), clang::Sema::CodeCompleteObjCForCollection(), findOMPAlloctraitT(), findOMPDependT(), and findOMPEventHandleT().
getFromOpaquePtr()
template<class PtrTy > static OpaquePtr clang::OpaquePtr< PtrTy >::getFromOpaquePtr (void * P) inline static
Definition at line 91 of file Ownership.h.
References P.
Referenced by clang::UnionOpaquePtr< T >::get(), and llvm::PointerLikeTypeTraits< clang::OpaquePtr< T > >::getFromVoidPointer().
getPtrAs()
template<class PtrTy > template<typename PtrT > PtrT clang::OpaquePtr< PtrTy >::getPtrAs () const inline
Returns pointer converted to the specified type.
Template Parameters
PtrT Result pointer type. There must be implicit conversion from PtrTy to PtrT.
In contrast to getPtrTo, this method allows the return type to be a smart pointer.
Definition at line 76 of file Ownership.h.
References clang::OpaquePtr< PtrTy >::get().
getPtrTo()
template<class PtrTy > template<typename PointeeT > PointeeT * clang::OpaquePtr< PtrTy >::getPtrTo () const inline
Returns plain pointer to the entity pointed by this wrapper.
Template Parameters
PointeeT Type of pointed entity.
It is identical to getPtrAs<PointeeT*>.
Definition at line 66 of file Ownership.h.
References clang::OpaquePtr< PtrTy >::get().
make()
template<class PtrTy > static OpaquePtr clang::OpaquePtr< PtrTy >::make (PtrTy P) inline static
Definition at line 60 of file Ownership.h.
References P, and clang::OpaquePtr< PtrTy >::set().
Referenced by clang::Sema::ActOnOpenMPDeclareMapperDirective(), clang::Sema::ActOnOpenMPDeclareReductionDirectiveStart(), clang::Sema::BuildDeclaratorGroup(), and clang::Sema::ConvertDeclToDeclGroup().
operator bool()
template<class PtrTy > clang::OpaquePtr< PtrTy >::operator bool () const inline explicit
Definition at line 88 of file Ownership.h.
set()
template<class PtrTy > void clang::OpaquePtr< PtrTy >::set (PtrTy P) inline
Definition at line 84 of file Ownership.h.
References P.
Referenced by clang::OpaquePtr< PtrTy >::make().
The documentation for this class was generated from the following file:
include/clang/Sema/Ownership.h