clang: clang::LocationContext Class Reference
clang::LocationContext Class Reference abstract
It wraps the AnalysisDeclContext to represent both the call stack with the help of StackFrameContext and inside the function calls the BlockInvocationContext.
#include "clang/Analysis/AnalysisDeclContext.h"
Public Types
enum ContextKind { StackFrame , Block }
Public Member Functions
virtual ~LocationContext ()
ContextKind getKind () const
int64_t getID () const
LLVM_ATTRIBUTE_RETURNS_NONNULL AnalysisDeclContext * getAnalysisDeclContext () const
const LocationContext * getParent () const
It might return null.
bool isParentOf (const LocationContext *LC) const
const Decl * getDecl () const
CFG * getCFG () const
template<typename T >
T * getAnalysis () const
const ParentMap & getParentMap () const
const ImplicitParamDecl * getSelfDecl () const
const StackFrameContext * getStackFrame () const
virtual bool inTopFrame () const
virtual void Profile (llvm::FoldingSetNodeID &ID)=0
LLVM_DUMP_METHOD void dumpStack (raw_ostream &Out) const
Prints out the call stack.
void printJson (raw_ostream &Out, const char *NL="\n", unsigned int Space=0, bool IsDot=false, std::function< void(const LocationContext *)> printMoreInfoPerContext=[](const LocationContext *) {}) const
Prints out the call stack in json format.
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static void ProfileCommon (llvm::FoldingSetNodeID &ID, ContextKind ck, AnalysisDeclContext *ctx, const LocationContext *parent, const void *data)
Protected Member Functions
LocationContext (ContextKind k, AnalysisDeclContext *ctx, const LocationContext *parent, int64_t ID)
Detailed Description
It wraps the AnalysisDeclContext to represent both the call stack with the help of StackFrameContext and inside the function calls the BlockInvocationContext.
It is needed for context sensitive analysis to model entering, leaving or inlining function calls.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 215 of file AnalysisDeclContext.h.
Member Enumeration Documentation
ContextKind
enum clang::LocationContext::ContextKind
Enumerator
StackFrame
Block
Definition at line 217 of file AnalysisDeclContext.h.
Constructor & Destructor Documentation
LocationContext()
clang::LocationContext::LocationContext (ContextKind k, AnalysisDeclContext * ctx, const LocationContext * parent, int64_t ID) inline protected
Definition at line 230 of file AnalysisDeclContext.h.
References Parent.
~LocationContext()
LocationContext::~LocationContext () virtual default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void LocationContext::dump () const
Definition at line 584 of file AnalysisDeclContext.cpp.
References printJson().
dumpStack()
void LocationContext::dumpStack (raw_ostream & Out) const
Prints out the call stack.
Parameters
Out The out stream.
Definition at line 497 of file AnalysisDeclContext.cpp.
References Block, getAnalysisDeclContext(), clang::AnalysisDeclContext::getASTContext(), getDecl(), clang::AnalysisDeclContext::getFunctionName(), clang::ASTContext::getLangOpts(), getParent(), clang::ASTContext::getSourceManager(), printLocation(), SM, StackFrame, and clang::PrintingPolicy::TerseOutput.
Referenced by clang::ento::PrettyStackTraceLocationContext::print().
getAnalysis()
template<typename T > T * clang::LocationContext::getAnalysis () const inline
Definition at line 255 of file AnalysisDeclContext.h.
References clang::AnalysisDeclContext::getAnalysis().
Referenced by clang::ento::ExplodedNode::getAnalysis().
getAnalysisDeclContext()
LLVM_ATTRIBUTE_RETURNS_NONNULL AnalysisDeclContext * clang::LocationContext::getAnalysisDeclContext () const inline
Definition at line 244 of file AnalysisDeclContext.h.
Referenced by clang::ento::SValBuilder::conjureSymbolVal(), dumpStack(), findTopAutosynthesizedParentContext(), clang::ento::SValBuilder::getBlockPointer(), clang::ento::CallEvent::getCalleeAnalysisDeclContext(), clang::ento::CallEvent::getCalleeStackFrame(), clang::ento::ExplodedNode::getCFGBlock(), clang::ento::CheckerContext::getCurrentAnalysisDeclContext(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), getLocationForCaller(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::ento::ExplodedNode::getStmtForDiagnostics(), clang::ento::getWidenedLoopState(), clang::ento::retaincountchecker::isSynthesizedAccessor(), printIndicesOfElementsToConstructJson(), printJson(), clang::ProgramPoint::printJson(), printObjectsUnderConstructionJson(), clang::ento::ExprEngine::processCallExit(), clang::BlockInvocationContext::Profile(), clang::StackFrameContext::Profile(), clang::ento::ExprEngine::removeDeadOnEndOfFunction(), clang::ento::PathDiagnosticCallPiece::setCallee(), shouldRemoveDeadBindings(), and clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode().
getCFG()
CFG * clang::LocationContext::getCFG () const inline
Definition at line 253 of file AnalysisDeclContext.h.
References clang::AnalysisDeclContext::getCFG().
Referenced by clang::ento::CoreEngine::ExecuteWorkList(), clang::FunctionExitPoint::getBlock(), clang::ento::ExplodedNode::getCFG(), clang::CallEnter::getEntry(), and clang::ento::PathSensitiveBugReport::getStmt().
getDecl()
const Decl * clang::LocationContext::getDecl () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 251 of file AnalysisDeclContext.h.
References clang::AnalysisDeclContext::getDecl().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), checkInvariantViolation(), checkSelfIvarsForInvariantViolation(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::PathDiagnosticCallPiece::construct(), clang::ento::PathDiagnosticLocation::createDeclBegin(), clang::ento::PathDiagnosticLocation::createDeclEnd(), dumpStack(), clang::ento::SymbolConjured::dumpToStream(), clang::ento::CoreEngine::ExecuteWorkList(), clang::ento::CallEventManager::getCaller(), clang::ento::ExplodedNode::getCodeDecl(), clang::ento::MemRegionManager::getCXXThisRegion(), clang::ento::ParamVarRegion::getDecl(), clang::ento::PathSensitiveBugReport::getDeclWithIssue(), getEnclosingStmtLocation(), clang::ento::AnyCXXConstructorCall::getInitialStackFrameContents(), clang::ento::AnyFunctionCall::getInitialStackFrameContents(), clang::ento::BlockCall::getInitialStackFrameContents(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ento::ExprEngine::getInitialState(), clang::ento::MemRegionManager::getVarRegion(), clang::ento::getWidenedLoopState(), clang::ento::isCapturedByReference(), isInMIGCall(), clang::ento::retaincountchecker::isSynthesizedAccessor(), printJson(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::ento::PathDiagnosticCallPiece::setCallee(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::SValExplainer::VisitParamVarRegion(), wasDifferentDeclUsedForInlining(), and willObjectBeAnalyzedLater().
getID()
int64_t clang::LocationContext::getID () const inline
Definition at line 241 of file AnalysisDeclContext.h.
Referenced by clang::ento::SymbolConjured::dumpToStream().
getKind()
ContextKind clang::LocationContext::getKind () const inline
Definition at line 239 of file AnalysisDeclContext.h.
Referenced by clang::BlockInvocationContext::classof(), and clang::StackFrameContext::classof().
getParent()
const LocationContext * clang::LocationContext::getParent () const inline
It might return null.
Definition at line 247 of file AnalysisDeclContext.h.
References Parent.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), dumpStack(), clang::ento::LikelyFalsePositiveSuppressionBRVisitor::finalizeVisitor(), findTopAutosynthesizedParentContext(), getCalleeNode(), clang::ento::CallEventManager::getCaller(), clang::ento::MemRegionManager::getCXXThisRegion(), clang::ento::CXXInheritedConstructorCall::getInheritingStackFrame(), clang::ento::ExprEngine::getInitialState(), getStackFrame(), getStackOrCaptureRegionForDeclContext(), clang::StackFrameContext::inTopFrame(), isInMIGCall(), isParentOf(), clang::ento::Environment::printJson(), printJson(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processEndOfFunction(), clang::BlockInvocationContext::Profile(), clang::StackFrameContext::Profile(), clang::ento::ExprEngine::removeDead(), clang::ento::ExprEngine::updateObjectsUnderConstruction(), and willObjectBeAnalyzedLater().
getParentMap()
const ParentMap & clang::LocationContext::getParentMap () const inline
Definition at line 257 of file AnalysisDeclContext.h.
References clang::AnalysisDeclContext::getParentMap().
Referenced by addContextEdges(), getEnclosingStmtLocation(), clang::ento::ObjCMethodCall::getMessageKind(), clang::ento::ExplodedNode::getParentMap(), and optimizeEdges().
getSelfDecl()
const ImplicitParamDecl * clang::LocationContext::getSelfDecl () const inline
Returns
The ImplicitParamDecl associated with self if this AnalysisDeclContext wraps an ObjCMethodDecl or nullptr otherwise.
Definition at line 260 of file AnalysisDeclContext.h.
References clang::AnalysisDeclContext::getSelfDecl().
Referenced by checkSelfIvarsForInvariantViolation(), and clang::ento::ProgramState::getSelfSVal().
getStackFrame()
const StackFrameContext * LocationContext::getStackFrame () const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 463 of file AnalysisDeclContext.cpp.
References getParent().
Referenced by clang::ento::NodeBuilderContext::blockCount(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::MemRegionManager::getAllocaRegion(), GetAllocationSite(), clang::ento::MemRegionManager::getBlockDataRegion(), getCalleeNode(), clang::ento::CallEventManager::getCaller(), clang::ento::MemRegionManager::getCompoundLiteralRegion(), clang::ento::MemRegionManager::getCXXTempObjectRegion(), clang::ento::MemRegionManager::getCXXThisRegion(), clang::ento::PathSensitiveBugReport::getDeclWithIssue(), clang::ento::CXXInheritedConstructorCall::getInheritingStackFrame(), clang::ento::ExprEngine::getInitialState(), getMatchingCallExitEnd(), clang::ento::ExprEngine::getObjectUnderConstruction(), clang::ento::MemRegionManager::getParamVarRegion(), clang::ProgramPoint::getStackFrame(), clang::ento::MemRegionManager::getVarRegion(), clang::ento::getWidenedLoopState(), inTopFrame(), isInitializationOfVar(), isInMIGCall(), clang::ento::SymbolReaper::isLive(), parameterTypeFromSVal(), clang::ento::Environment::printJson(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::processEndOfFunction(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::ento::ExprEngine::removeDead(), clang::ento::ExprEngine::updateObjectsUnderConstruction(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), and clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
inTopFrame()
bool LocationContext::inTopFrame () const virtual
Returns
Whether the current LocationContext has no caller context.
Reimplemented in clang::StackFrameContext.
Definition at line 473 of file AnalysisDeclContext.cpp.
References getStackFrame(), and clang::StackFrameContext::inTopFrame().
Referenced by clang::ento::MemRegionManager::getCXXThisRegion(), clang::ento::CheckerContext::inTopFrame(), and clang::ento::ExprEngine::processEndOfFunction().
isParentOf()
bool LocationContext::isParentOf (const LocationContext * LC) const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 477 of file AnalysisDeclContext.cpp.
References getParent(), and Parent.
Referenced by GetAllocationSite(), clang::ento::SymbolReaper::isLive(), isVarAnInterestingCondition(), and clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode().
printJson()
void LocationContext::printJson (raw_ostream & Out, const char * NL = "\n", unsigned int Space = 0, bool IsDot = false, std::function< void(const LocationContext *)> printMoreInfoPerContext = [](const LocationContext *) {}) const
Prints out the call stack in json format.
Parameters
Out The out stream.
NL The newline.
Space The space count for indentation.
IsDot Whether the output format is dot.
printMoreInfoPerContext A callback to print more information for each context, for example:
[&](const LocationContext *LC) { LC->dump(); }
Definition at line 532 of file AnalysisDeclContext.cpp.
References Block, getAnalysisDeclContext(), clang::AnalysisDeclContext::getASTContext(), getDecl(), clang::ASTContext::getLangOpts(), getParent(), clang::ASTContext::getSourceManager(), clang::printSourceLocationAsJson(), SM, StackFrame, and clang::PrintingPolicy::TerseOutput.
Referenced by dump(), clang::ento::Environment::printJson(), and clang::ento::ExprEngine::printJson().
Profile()
virtual void clang::LocationContext::Profile (llvm::FoldingSetNodeID & ID) pure virtual
Implemented in clang::BlockInvocationContext, and clang::StackFrameContext.
ProfileCommon()
void LocationContext::ProfileCommon (llvm::FoldingSetNodeID & ID, ContextKind ck, AnalysisDeclContext * ctx, const LocationContext * parent, const void * data) static
Definition at line 404 of file AnalysisDeclContext.cpp.
Referenced by clang::BlockInvocationContext::Profile(), and clang::StackFrameContext::Profile().
The documentation for this class was generated from the following files:
include/clang/Analysis/AnalysisDeclContext.h
lib/Analysis/AnalysisDeclContext.cpp