clang: clang::threadSafety::til::Field Class Reference
clang::threadSafety::til::Field Class Reference
A typed, writable location in memory.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Field (SExpr *R, SExpr *B)
Field (const Field &C, SExpr *R, SExpr *B)
SExpr * range ()
const SExpr * range () const
SExpr * body ()
const SExpr * body () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Field *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
A typed, writable location in memory.
Definition at line 800 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Field() [1/2]
clang::threadSafety::til::Field::Field (SExpr * R, SExpr * B) inline
Definition at line 802 of file ThreadSafetyTIL.h.
Field() [2/2]
clang::threadSafety::til::Field::Field (const Field & C, SExpr * R, SExpr * B) inline
Definition at line 803 of file ThreadSafetyTIL.h.
Member Function Documentation
body() [1/2]
SExpr * clang::threadSafety::til::Field::body () inline
Definition at line 811 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printField().
body() [2/2]
const SExpr * clang::threadSafety::til::Field::body () const inline
Definition at line 812 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Field::classof (const SExpr * E) inline static
Definition at line 806 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Field::compare (const Field * E, C & Cmp) const inline
Definition at line 822 of file ThreadSafetyTIL.h.
References body(), and range().
range() [1/2]
SExpr * clang::threadSafety::til::Field::range () inline
Definition at line 808 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printField().
range() [2/2]
const SExpr * clang::threadSafety::til::Field::range () const inline
Definition at line 809 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Field::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 815 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h