clang: clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData > Class Template Reference
clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData > Class Template Reference
A base class for.
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getSigilLoc () const
void setSigilLoc (SourceLocation Loc)
TypeLoc getPointeeLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
PointerLikeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
template<class Derived, class TypeClass, class LocalData = PointerLikeLocInfo>
class clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >
A base class for.
Definition at line 1229 of file TypeLoc.h.
Member Function Documentation
getInnerType()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> QualType clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getInnerType () const inline
Definition at line 1252 of file TypeLoc.h.
References clang::Type::getPointeeType(), and clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >::getTypePtr().
getLocalSourceRange()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> SourceRange clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getLocalSourceRange () const inline
Definition at line 1244 of file TypeLoc.h.
References clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getSigilLoc().
getPointeeLoc()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> TypeLoc clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getPointeeLoc () const inline
Definition at line 1240 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >::getInnerTypeLoc().
Referenced by FixInvalidVariablyModifiedTypeLoc(), and clang::TreeTransform< Derived >::TransformReferenceType().
getSigilLoc()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> SourceLocation clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getSigilLoc () const inline
Definition at line 1232 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >::getLocalData(), and clang::PointerLikeLocInfo::StarLoc.
Referenced by clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getLocalSourceRange(), and clang::TreeTransform< Derived >::TransformReferenceType().
initializeLocal()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> void clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 1248 of file TypeLoc.h.
References clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::setSigilLoc().
setSigilLoc()
template<class Derived , class TypeClass , class LocalData = PointerLikeLocInfo> void clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::setSigilLoc (SourceLocation Loc) inline
Definition at line 1236 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >::getLocalData(), and clang::PointerLikeLocInfo::StarLoc.
Referenced by clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::initializeLocal(), and clang::TreeTransform< Derived >::TransformReferenceType().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h