clang: clang::CodeGen::CodeGenFunction::FinallyInfo Class Reference
clang::CodeGen::CodeGenFunction::FinallyInfo Class Reference
A class controlling the emission of a finally block.
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
void enter (CodeGenFunction &CGF, const Stmt *Finally, llvm::FunctionCallee beginCatchFn, llvm::FunctionCallee endCatchFn, llvm::FunctionCallee rethrowFn)
Enters a finally block for an implementation using zero-cost exceptions.
void exit (CodeGenFunction &CGF)
Detailed Description
A class controlling the emission of a finally block.
Definition at line 736 of file CodeGenFunction.h.
Member Function Documentation
enter()
void CodeGenFunction::FinallyInfo::enter (CodeGenFunction & CGF, const Stmt * body, llvm::FunctionCallee beginCatchFn, llvm::FunctionCallee endCatchFn, llvm::FunctionCallee rethrowFn)
Enters a finally block for an implementation using zero-cost exceptions.
This is mostly general, but hard-codes some language/ABI-specific behavior in the catch-all sections.
Definition at line 1416 of file CGException.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateFlagStore(), clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::getJumpDestInCurrentScope(), clang::CodeGen::CodeGenFunction::getUnreachableBlock(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::NormalCleanup, clang::CodeGen::EHScopeStack::pushCatch(), and clang::CodeGen::EHCatchScope::setCatchAllHandler().
Referenced by clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt().
exit()
void CodeGenFunction::FinallyInfo::exit (CodeGenFunction & CGF)
Definition at line 1469 of file CGException.cpp.
References clang::CodeGen::EHScopeStack::begin(), clang::CodeGen::EHCatchScope::Handler::Block, clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CGBuilderTy::CreateAlignedStore(), clang::CodeGen::CGBuilderTy::CreateFlagStore(), clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitBranchThroughCleanup(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenFunction::getExceptionFromSlot(), clang::CodeGen::EHCatchScope::getHandler(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenFunction::popCatchScope(), and clang::CodeGen::CodeGenFunction::PopCleanupBlock().
Referenced by clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenFunction.h
lib/CodeGen/CGException.cpp