clang: clang::BumpVector< T > Class Template Reference
clang::BumpVector< T > Class Template Reference
#include "clang/Analysis/Support/BumpVector.h"
Public Types
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = std::reverse_iterator<iterator>
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
BumpVector (BumpVectorContext &C, unsigned N)
~BumpVector ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_type size () const
reference operator[] (unsigned idx)
const_reference operator[] (unsigned idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void pop_back ()
T pop_back_val ()
void clear ()
pointer data ()
data - Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
data - Return a pointer to the vector's buffer, even if empty().
void push_back (const_reference Elt, BumpVectorContext &C)
iterator insert (iterator I, size_t Cnt, const_reference E, BumpVectorContext &C)
insert - Insert some number of copies of element into a position.
void reserve (BumpVectorContext &C, unsigned N)
size_t capacity () const
capacity - Return the total number of elements in the currently allocated buffer.
Detailed Description
template<typename T>
class clang::BumpVector< T >
Definition at line 59 of file BumpVector.h.
Member Typedef Documentation
const_iterator
template<typename T > using clang::BumpVector< T >::const_iterator = const T *
Definition at line 81 of file BumpVector.h.
const_pointer
template<typename T > using clang::BumpVector< T >::const_pointer = const T *
Definition at line 89 of file BumpVector.h.
const_reference
template<typename T > using clang::BumpVector< T >::const_reference = const T &
Definition at line 87 of file BumpVector.h.
const_reverse_iterator
template<typename T > using clang::BumpVector< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 83 of file BumpVector.h.
difference_type
template<typename T > using clang::BumpVector< T >::difference_type = ptrdiff_t
Definition at line 78 of file BumpVector.h.
iterator
template<typename T > using clang::BumpVector< T >::iterator = T *
Definition at line 80 of file BumpVector.h.
pointer
template<typename T > using clang::BumpVector< T >::pointer = T *
Definition at line 88 of file BumpVector.h.
reference
template<typename T > using clang::BumpVector< T >::reference = T &
Definition at line 86 of file BumpVector.h.
reverse_iterator
template<typename T > using clang::BumpVector< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 84 of file BumpVector.h.
size_type
template<typename T > using clang::BumpVector< T >::size_type = size_t
Definition at line 77 of file BumpVector.h.
value_type
template<typename T > using clang::BumpVector< T >::value_type = T
Definition at line 79 of file BumpVector.h.
Constructor & Destructor Documentation
BumpVector()
template<typename T > clang::BumpVector< T >::BumpVector (BumpVectorContext & C, unsigned N) inline explicit
Definition at line 66 of file BumpVector.h.
References clang::C, N, and clang::BumpVector< T >::reserve().
~BumpVector()
template<typename T > clang::BumpVector< T >::~BumpVector () inline
Definition at line 70 of file BumpVector.h.
References Begin.
Member Function Documentation
back() [1/2]
template<typename T > reference clang::BumpVector< T >::back () inline
Definition at line 124 of file BumpVector.h.
References clang::BumpVector< T >::end().
Referenced by clang::CFG::back(), and clang::BumpVector< T >::pop_back_val().
back() [2/2]
template<typename T > const_reference clang::BumpVector< T >::back () const inline
Definition at line 127 of file BumpVector.h.
References clang::BumpVector< T >::end().
begin() [1/2]
template<typename T > iterator clang::BumpVector< T >::begin () inline
Definition at line 92 of file BumpVector.h.
References Begin.
Referenced by clang::CFG::begin(), clang::CFG::begin(), clang::BumpVector< T >::front(), clang::BumpVector< T >::front(), clang::CFG::nodes_begin(), clang::CFG::nodes_begin(), clang::BumpVector< T >::rend(), and clang::BumpVector< T >::rend().
begin() [2/2]
template<typename T > const_iterator clang::BumpVector< T >::begin () const inline
Definition at line 93 of file BumpVector.h.
References Begin.
capacity()
template<typename T > size_t clang::BumpVector< T >::capacity () const inline
capacity - Return the total number of elements in the currently allocated buffer.
Definition at line 195 of file BumpVector.h.
References Begin.
clear()
template<typename T > void clang::BumpVector< T >::clear () inline
Definition at line 142 of file BumpVector.h.
References Begin.
data() [1/2]
template<typename T > pointer clang::BumpVector< T >::data () inline
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 150 of file BumpVector.h.
References Begin.
data() [2/2]
template<typename T > const_pointer clang::BumpVector< T >::data () const inline
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 155 of file BumpVector.h.
References Begin.
empty()
template<typename T > bool clang::BumpVector< T >::empty () const inline
Definition at line 105 of file BumpVector.h.
References Begin.
end() [1/2]
template<typename T > iterator clang::BumpVector< T >::end () inline
Definition at line 94 of file BumpVector.h.
Referenced by clang::BumpVector< T >::back(), clang::BumpVector< T >::back(), clang::CFG::end(), clang::CFG::end(), clang::CFG::nodes_end(), clang::CFG::nodes_end(), clang::BumpVector< T >::rbegin(), and clang::BumpVector< T >::rbegin().
end() [2/2]
template<typename T > const_iterator clang::BumpVector< T >::end () const inline
Definition at line 95 of file BumpVector.h.
front() [1/2]
template<typename T > reference clang::BumpVector< T >::front () inline
Definition at line 117 of file BumpVector.h.
References clang::BumpVector< T >::begin().
Referenced by clang::CFG::front().
front() [2/2]
template<typename T > const_reference clang::BumpVector< T >::front () const inline
Definition at line 120 of file BumpVector.h.
References clang::BumpVector< T >::begin().
insert()
template<typename T > iterator clang::BumpVector< T >::insert (iterator I, size_t Cnt, const_reference E, BumpVectorContext & C) inline
insert - Insert some number of copies of element into a position.
Return iterator to position after last inserted copy.
Definition at line 172 of file BumpVector.h.
References Begin, clang::C, and clang::BumpVector< T >::size().
operator[]() [1/2]
template<typename T > reference clang::BumpVector< T >::operator[] (unsigned idx) inline
Definition at line 108 of file BumpVector.h.
References Begin.
operator[]() [2/2]
template<typename T > const_reference clang::BumpVector< T >::operator[] (unsigned idx) const inline
Definition at line 112 of file BumpVector.h.
References Begin.
pop_back()
template<typename T > void clang::BumpVector< T >::pop_back () inline
Definition at line 131 of file BumpVector.h.
Referenced by clang::BumpVector< T >::pop_back_val().
pop_back_val()
template<typename T > T clang::BumpVector< T >::pop_back_val () inline
Definition at line 136 of file BumpVector.h.
References clang::BumpVector< T >::back(), clang::BumpVector< T >::pop_back(), and clang::Result.
push_back()
template<typename T > void clang::BumpVector< T >::push_back (const_reference Elt, BumpVectorContext & C) inline
Definition at line 159 of file BumpVector.h.
References clang::C.
Referenced by clang::CFGBlock::addSuccessor(), and LazyInitializeReferencedDecls().
rbegin() [1/2]
template<typename T > reverse_iterator clang::BumpVector< T >::rbegin () inline
Definition at line 98 of file BumpVector.h.
References clang::BumpVector< T >::end().
Referenced by clang::CFG::rbegin(), and clang::CFG::rbegin().
rbegin() [2/2]
template<typename T > const_reverse_iterator clang::BumpVector< T >::rbegin () const inline
Definition at line 99 of file BumpVector.h.
References clang::BumpVector< T >::end().
rend() [1/2]
template<typename T > reverse_iterator clang::BumpVector< T >::rend () inline
Definition at line 100 of file BumpVector.h.
References clang::BumpVector< T >::begin().
Referenced by clang::CFG::rend(), and clang::CFG::rend().
rend() [2/2]
template<typename T > const_reverse_iterator clang::BumpVector< T >::rend () const inline
Definition at line 101 of file BumpVector.h.
References clang::BumpVector< T >::begin().
reserve()
template<typename T > void clang::BumpVector< T >::reserve (BumpVectorContext & C, unsigned N) inline
Definition at line 188 of file BumpVector.h.
References Begin, clang::C, and N.
Referenced by clang::BumpVector< T >::BumpVector().
size()
template<typename T > size_type clang::BumpVector< T >::size () const inline
Definition at line 106 of file BumpVector.h.
References Begin.
Referenced by clang::BumpVector< T >::insert().
The documentation for this class was generated from the following file:
include/clang/Analysis/Support/BumpVector.h