clang: clang::extractapi::DeclarationFragmentsBuilder Class Reference
clang::extractapi::DeclarationFragmentsBuilder Class Reference
A factory class to build DeclarationFragments for different kinds of Decl.
#include "clang/ExtractAPI/DeclarationFragments.h"
Static Public Member Functions
static DeclarationFragments getFragmentsForVar (const VarDecl *)
Build DeclarationFragments for a variable declaration VarDecl.
static DeclarationFragments getFragmentsForFunction (const FunctionDecl *)
Build DeclarationFragments for a function declaration FunctionDecl.
static DeclarationFragments getFragmentsForEnumConstant (const EnumConstantDecl *)
Build DeclarationFragments for an enum constant declaration EnumConstantDecl.
static DeclarationFragments getFragmentsForEnum (const EnumDecl *)
Build DeclarationFragments for an enum declaration EnumDecl.
static DeclarationFragments getFragmentsForField (const FieldDecl *)
Build DeclarationFragments for a field declaration FieldDecl.
static DeclarationFragments getFragmentsForStruct (const RecordDecl *)
Build DeclarationFragments for a struct record declaration RecordDecl.
static DeclarationFragments getFragmentsForObjCCategory (const ObjCCategoryDecl *)
Build DeclarationFragments for an Objective-C category declaration ObjCCategoryDecl.
static DeclarationFragments getFragmentsForObjCInterface (const ObjCInterfaceDecl *)
Build DeclarationFragments for an Objective-C interface declaration ObjCInterfaceDecl.
static DeclarationFragments getFragmentsForObjCMethod (const ObjCMethodDecl *)
Build DeclarationFragments for an Objective-C method declaration ObjCMethodDecl.
static DeclarationFragments getFragmentsForObjCProperty (const ObjCPropertyDecl *)
Build DeclarationFragments for an Objective-C property declaration ObjCPropertyDecl.
static DeclarationFragments getFragmentsForObjCProtocol (const ObjCProtocolDecl *)
Build DeclarationFragments for an Objective-C protocol declaration ObjCProtocolDecl.
static DeclarationFragments getFragmentsForMacro (StringRef Name, const MacroDirective *MD)
Build DeclarationFragments for a macro.
static DeclarationFragments getFragmentsForTypedef (const TypedefNameDecl *Decl)
Build DeclarationFragments for a typedef TypedefNameDecl.
static DeclarationFragments getSubHeading (const NamedDecl *)
Build sub-heading fragments for a NamedDecl.
static DeclarationFragments getSubHeading (const ObjCMethodDecl *)
Build sub-heading fragments for an Objective-C method.
static DeclarationFragments getSubHeadingForMacro (StringRef Name)
Build a sub-heading for macro Name.
template<typename FunctionT >
static FunctionSignature getFunctionSignature (const FunctionT *)
Build FunctionSignature for a function-like declaration FunctionT like FunctionDecl or ObjCMethodDecl.
Detailed Description
A factory class to build DeclarationFragments for different kinds of Decl.
Definition at line 185 of file DeclarationFragments.h.
Member Function Documentation
getFragmentsForEnum()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForEnum (const EnumDecl * EnumDecl) static
Build DeclarationFragments for an enum declaration EnumDecl.
Definition at line 454 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), getFragmentsForTypedef(), clang::EnumDecl::getIntegerType(), clang::NamedDecl::getName(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::QualType::isNull(), clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForEnumConstant()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForEnumConstant (const EnumConstantDecl * EnumConstDecl) static
Build DeclarationFragments for an enum constant declaration EnumConstantDecl.
Definition at line 446 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::NamedDecl::getName(), and clang::extractapi::DeclarationFragments::Identifier.
getFragmentsForField()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForField (const FieldDecl * Field) static
Build DeclarationFragments for a field declaration FieldDecl.
Definition at line 476 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), and clang::extractapi::DeclarationFragments::Identifier.
getFragmentsForFunction()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForFunction (const FunctionDecl * Func) static
Build DeclarationFragments for a function declaration FunctionDecl.
Definition at line 404 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::NamedDecl::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::FunctionDecl::getReturnType(), clang::FunctionDecl::getStorageClass(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::SC_Auto, clang::SC_Extern, clang::SC_None, clang::SC_PrivateExtern, clang::SC_Register, clang::SC_Static, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForMacro()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForMacro (StringRef Name, const MacroDirective * MD) static
Build DeclarationFragments for a macro.
Parameters
Name name of the macro.
MD the associated MacroDirective.
Definition at line 499 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::MacroDirective::getMacroInfo(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::InternalParam, clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForObjCCategory()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCCategory (const ObjCCategoryDecl * Category) static
Build DeclarationFragments for an Objective-C category declaration ObjCCategoryDecl.
Definition at line 529 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), Category, clang::index::generateUSRForDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForObjCInterface()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCInterface (const ObjCInterfaceDecl * Interface) static
Build DeclarationFragments for an Objective-C interface declaration ObjCInterfaceDecl.
Definition at line 548 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::index::generateUSRForDecl(), clang::NamedDecl::getName(), clang::ObjCInterfaceDecl::getSuperClass(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForObjCMethod()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCMethod (const ObjCMethodDecl * Method) static
Build DeclarationFragments for an Objective-C method declaration ObjCMethodDecl.
Definition at line 569 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForObjCProperty()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCProperty (const ObjCPropertyDecl * Property) static
Build DeclarationFragments for an Objective-C property declaration ObjCPropertyDecl.
Definition at line 613 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::First, clang::getNullabilitySpelling(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_class, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_direct, clang::ObjCPropertyAttribute::kind_getter, clang::ObjCPropertyAttribute::kind_noattr, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_null_resettable, clang::ObjCPropertyAttribute::kind_nullability, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, clang::ObjCPropertyAttribute::kind_weak, clang::AttributedType::stripOuterNullability(), clang::extractapi::DeclarationFragments::Text, and clang::Unspecified.
getFragmentsForObjCProtocol()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCProtocol (const ObjCProtocolDecl * Protocol) static
Build DeclarationFragments for an Objective-C protocol declaration ObjCProtocolDecl.
Definition at line 700 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::index::generateUSRForDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForStruct()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForStruct (const RecordDecl * Record) static
Build DeclarationFragments for a struct record declaration RecordDecl.
Definition at line 485 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), getFragmentsForTypedef(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Keyword.
getFragmentsForTypedef()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForTypedef (const TypedefNameDecl * Decl) static
Build DeclarationFragments for a typedef TypedefNameDecl.
Definition at line 729 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Keyword.
Referenced by getFragmentsForEnum(), and getFragmentsForStruct().
getFragmentsForVar()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForVar (const VarDecl * Var) static
Build DeclarationFragments for a variable declaration VarDecl.
Definition at line 353 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::NamedDecl::getName(), clang::VarDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::TypeSourceInfo::getType(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTContext::getUnqualifiedObjCPointerType(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, and clang::SC_None.
getFunctionSignature()
template<typename FunctionT > template FunctionSignature DeclarationFragmentsBuilder::getFunctionSignature (const FunctionT *) static
Build FunctionSignature for a function-like declaration FunctionT like FunctionDecl or ObjCMethodDecl.
The logic and implementation of building a signature for a FunctionDecl and an ObjCMethodDecl are exactly the same, but they do not share a common base. This template helps reuse the code.
Definition at line 745 of file DeclarationFragments.cpp.
References clang::extractapi::FunctionSignature::addParameter(), clang::extractapi::DeclarationFragments::append(), and clang::extractapi::FunctionSignature::setReturnType().
getSubHeading() [1/2]
DeclarationFragments DeclarationFragmentsBuilder::getSubHeading (const NamedDecl * Decl) static
Build sub-heading fragments for a NamedDecl.
Definition at line 771 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), and clang::extractapi::DeclarationFragments::Identifier.
getSubHeading() [2/2]
DeclarationFragments DeclarationFragmentsBuilder::getSubHeading (const ObjCMethodDecl * Method) static
Build sub-heading fragments for an Objective-C method.
Definition at line 782 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Text.
getSubHeadingForMacro()
DeclarationFragments DeclarationFragmentsBuilder::getSubHeadingForMacro (StringRef Name) static
Build a sub-heading for macro Name.
Definition at line 795 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), and clang::extractapi::DeclarationFragments::Identifier.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/DeclarationFragments.h
lib/ExtractAPI/DeclarationFragments.cpp