clang: clang::CXXCtorInitializer Class Reference
clang::CXXCtorInitializer Class Reference final
Represents a C++ base or member initializer.
#include "clang/AST/DeclCXX.h"
Public Member Functions
CXXCtorInitializer (ASTContext &Context, TypeSourceInfo *TInfo, bool IsVirtual, SourceLocation L, Expr *Init, SourceLocation R, SourceLocation EllipsisLoc)
Creates a new base-class initializer.
CXXCtorInitializer (ASTContext &Context, FieldDecl *Member, SourceLocation MemberLoc, SourceLocation L, Expr *Init, SourceLocation R)
Creates a new member initializer.
CXXCtorInitializer (ASTContext &Context, IndirectFieldDecl *Member, SourceLocation MemberLoc, SourceLocation L, Expr *Init, SourceLocation R)
Creates a new anonymous field initializer.
CXXCtorInitializer (ASTContext &Context, TypeSourceInfo *TInfo, SourceLocation L, Expr *Init, SourceLocation R)
Creates a new delegating initializer.
int64_t getID (const ASTContext &Context) const
bool isBaseInitializer () const
Determine whether this initializer is initializing a base class.
bool isMemberInitializer () const
Determine whether this initializer is initializing a non-static data member.
bool isAnyMemberInitializer () const
bool isIndirectMemberInitializer () const
bool isInClassMemberInitializer () const
Determine whether this initializer is an implicit initializer generated for a field with an initializer defined on the member declaration.
bool isDelegatingInitializer () const
Determine whether this initializer is creating a delegating constructor.
bool isPackExpansion () const
Determine whether this initializer is a pack expansion.
SourceLocation getEllipsisLoc () const
TypeLoc getBaseClassLoc () const
If this is a base class initializer, returns the type of the base class with location information.
const Type * getBaseClass () const
If this is a base class initializer, returns the type of the base class.
bool isBaseVirtual () const
Returns whether the base is virtual or not.
TypeSourceInfo * getTypeSourceInfo () const
Returns the declarator information for a base class or delegating initializer.
FieldDecl * getMember () const
If this is a member initializer, returns the declaration of the non-static data member being initialized.
FieldDecl * getAnyMember () const
IndirectFieldDecl * getIndirectMember () const
SourceLocation getMemberLocation () const
SourceLocation getSourceLocation () const
Determine the source location of the initializer.
SourceRange getSourceRange () const LLVM_READONLY
Determine the source range covering the entire initializer.
bool isWritten () const
Determine whether this initializer is explicitly written in the source code.
int getSourceOrder () const
Return the source position of the initializer, counting from 0.
void setSourceOrder (int Pos)
Set the source order of this initializer.
SourceLocation getLParenLoc () const
SourceLocation getRParenLoc () const
Expr * getInit () const
Get the initializer.
Detailed Description
Represents a C++ base or member initializer.
This is part of a constructor initializer that initializes one non-static member variable or one base class. For example, in the following, both 'A(a)' and 'f(3.14159)' are member initializers:
class A { };
class B : public A {
  float f;
public:
  B(A& a) : A(a), f(3.14159) { }
};
Definition at line 2205 of file DeclCXX.h.
Constructor & Destructor Documentation
CXXCtorInitializer() [1/4]
CXXCtorInitializer::CXXCtorInitializer (ASTContext & Context, TypeSourceInfo * TInfo, bool IsVirtual, SourceLocation L, Expr * Init, SourceLocation R, SourceLocation EllipsisLoc) explicit
Creates a new base-class initializer.
Definition at line 2509 of file DeclCXX.cpp.
CXXCtorInitializer() [2/4]
CXXCtorInitializer::CXXCtorInitializer (ASTContext & Context, FieldDecl * Member, SourceLocation MemberLoc, SourceLocation L, Expr * Init, SourceLocation R) explicit
Creates a new member initializer.
Definition at line 2518 of file DeclCXX.cpp.
CXXCtorInitializer() [3/4]
CXXCtorInitializer::CXXCtorInitializer (ASTContext & Context, IndirectFieldDecl * Member, SourceLocation MemberLoc, SourceLocation L, Expr * Init, SourceLocation R) explicit
Creates a new anonymous field initializer.
Definition at line 2526 of file DeclCXX.cpp.
CXXCtorInitializer() [4/4]
CXXCtorInitializer::CXXCtorInitializer (ASTContext & Context, TypeSourceInfo * TInfo, SourceLocation L, Expr * Init, SourceLocation R) explicit
Creates a new delegating initializer.
Definition at line 2535 of file DeclCXX.cpp.
Member Function Documentation
getAnyMember()
FieldDecl * clang::CXXCtorInitializer::getAnyMember () const inline
Definition at line 2348 of file DeclCXX.h.
References isIndirectMemberInitializer(), and isMemberInitializer().
Referenced by EmitLValueForAnyFieldInitialization(), EmitMemberInitializer(), getSourceLocation(), getSourceRange(), and print_initializer().
getBaseClass()
const Type * CXXCtorInitializer::getBaseClass () const
If this is a base class initializer, returns the type of the base class.
Otherwise, returns null.
Definition at line 2554 of file DeclCXX.cpp.
References getType(), and isBaseInitializer().
Referenced by EmitBaseInitializer(), isInitializerOfDynamicClass(), and print_initializer().
getBaseClassLoc()
TypeLoc CXXCtorInitializer::getBaseClassLoc () const
If this is a base class initializer, returns the type of the base class with location information.
Otherwise, returns an NULL type location.
Definition at line 2547 of file DeclCXX.cpp.
References isBaseInitializer().
getEllipsisLoc()
SourceLocation clang::CXXCtorInitializer::getEllipsisLoc () const inline
Definition at line 2312 of file DeclCXX.h.
References isPackExpansion().
Referenced by clang::ASTImporter::Import().
getID()
int64_t CXXCtorInitializer::getID (const ASTContext & Context) const
Returns
Unique reproducible object identifier.
Definition at line 2542 of file DeclCXX.cpp.
References clang::ASTContext::getAllocator().
getIndirectMember()
IndirectFieldDecl * clang::CXXCtorInitializer::getIndirectMember () const inline
Definition at line 2356 of file DeclCXX.h.
References isIndirectMemberInitializer().
Referenced by EmitLValueForAnyFieldInitialization(), clang::ASTImporter::Import(), and clang::ento::ExprEngine::ProcessInitializer().
getInit()
Expr * clang::CXXCtorInitializer::getInit () const inline
Get the initializer.
Definition at line 2404 of file DeclCXX.h.
Referenced by AllTrivialInitializers(), EmitBaseInitializer(), EmitMemberInitializer(), clang::ConstructorInitializerConstructionContext::getArrayInitLoop(), clang::ASTImporter::Import(), print_initializer(), and clang::ento::ExprEngine::ProcessInitializer().
getLParenLoc()
SourceLocation clang::CXXCtorInitializer::getLParenLoc () const inline
Definition at line 2400 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import().
getMember()
FieldDecl * clang::CXXCtorInitializer::getMember () const inline
If this is a member initializer, returns the declaration of the non-static data member being initialized.
Otherwise, returns null.
Definition at line 2342 of file DeclCXX.h.
References isMemberInitializer().
Referenced by clang::ASTImporter::Import(), and clang::ento::ExprEngine::ProcessInitializer().
getMemberLocation()
SourceLocation clang::CXXCtorInitializer::getMemberLocation () const inline
Definition at line 2362 of file DeclCXX.h.
Referenced by getSourceLocation(), and clang::ASTImporter::Import().
getRParenLoc()
SourceLocation clang::CXXCtorInitializer::getRParenLoc () const inline
Definition at line 2401 of file DeclCXX.h.
Referenced by getSourceRange(), and clang::ASTImporter::Import().
getSourceLocation()
SourceLocation CXXCtorInitializer::getSourceLocation () const
Determine the source location of the initializer.
Definition at line 2561 of file DeclCXX.cpp.
References getAnyMember(), clang::Decl::getLocation(), getMemberLocation(), isAnyMemberInitializer(), and isInClassMemberInitializer().
Referenced by DiagnoseBaseOrMemInitializerOrder(), EmitMemberInitializer(), getSourceRange(), and clang::ento::ExprEngine::ProcessInitializer().
getSourceOrder()
int clang::CXXCtorInitializer::getSourceOrder () const inline
Return the source position of the initializer, counting from 0.
If the initializer was implicit, -1 is returned.
Definition at line 2378 of file DeclCXX.h.
getSourceRange()
SourceRange CXXCtorInitializer::getSourceRange () const
Determine the source range covering the entire initializer.
Definition at line 2574 of file DeclCXX.cpp.
References getAnyMember(), clang::FieldDecl::getInClassInitializer(), getRParenLoc(), getSourceLocation(), and isInClassMemberInitializer().
Referenced by DiagnoseBaseOrMemInitializerOrder().
getTypeSourceInfo()
TypeSourceInfo * clang::CXXCtorInitializer::getTypeSourceInfo () const inline
Returns the declarator information for a base class or delegating initializer.
Definition at line 2336 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import(), and print_initializer().
isAnyMemberInitializer()
bool clang::CXXCtorInitializer::isAnyMemberInitializer () const inline
Definition at line 2282 of file DeclCXX.h.
References isIndirectMemberInitializer(), and isMemberInitializer().
Referenced by EmitMemberInitializer(), getSourceLocation(), and clang::ento::ExprEngine::ProcessInitializer().
isBaseInitializer()
bool clang::CXXCtorInitializer::isBaseInitializer () const inline
Determine whether this initializer is initializing a base class.
Definition at line 2274 of file DeclCXX.h.
Referenced by EmitBaseInitializer(), getBaseClass(), getBaseClassLoc(), clang::ASTImporter::Import(), isBaseVirtual(), isPackExpansion(), print_initializer(), and clang::ento::ExprEngine::ProcessInitializer().
isBaseVirtual()
bool clang::CXXCtorInitializer::isBaseVirtual () const inline
Returns whether the base is virtual or not.
Definition at line 2328 of file DeclCXX.h.
References isBaseInitializer().
Referenced by EmitBaseInitializer(), and clang::ASTImporter::Import().
isDelegatingInitializer()
bool clang::CXXCtorInitializer::isDelegatingInitializer () const inline
Determine whether this initializer is creating a delegating constructor.
Definition at line 2302 of file DeclCXX.h.
Referenced by clang::ASTImporter::Import(), clang::CXXConstructorDecl::isDelegatingConstructor(), print_initializer(), and clang::ento::ExprEngine::ProcessInitializer().
isInClassMemberInitializer()
bool clang::CXXCtorInitializer::isInClassMemberInitializer () const inline
Determine whether this initializer is an implicit initializer generated for a field with an initializer defined on the member declaration.
In-class member initializers (also known as "non-static data member initializations", NSDMIs) were introduced in C++11.
Definition at line 2296 of file DeclCXX.h.
Referenced by getSourceLocation(), and getSourceRange().
isIndirectMemberInitializer()
bool clang::CXXCtorInitializer::isIndirectMemberInitializer () const inline
Definition at line 2286 of file DeclCXX.h.
Referenced by EmitLValueForAnyFieldInitialization(), getAnyMember(), getIndirectMember(), clang::ASTImporter::Import(), isAnyMemberInitializer(), and clang::ento::ExprEngine::ProcessInitializer().
isMemberInitializer()
bool clang::CXXCtorInitializer::isMemberInitializer () const inline
Determine whether this initializer is initializing a non-static data member.
Definition at line 2280 of file DeclCXX.h.
Referenced by getAnyMember(), getMember(), clang::ASTImporter::Import(), and isAnyMemberInitializer().
isPackExpansion()
bool clang::CXXCtorInitializer::isPackExpansion () const inline
Determine whether this initializer is a pack expansion.
Definition at line 2307 of file DeclCXX.h.
References isBaseInitializer(), and clang::SourceLocation::isValid().
Referenced by getEllipsisLoc(), and clang::ASTImporter::Import().
isWritten()
bool clang::CXXCtorInitializer::isWritten () const inline
Determine whether this initializer is explicitly written in the source code.
Definition at line 2374 of file DeclCXX.h.
Referenced by clang::diff::isSpecializedNodeExcluded().
setSourceOrder()
void clang::CXXCtorInitializer::setSourceOrder (int Pos) inline
Set the source order of this initializer.
This can only be called once for each initializer; it cannot be called on an initializer having a positive number of (implicit) array indices.
This assumes that the initializer was written in the source code, and ensures that isWritten() returns true.
Definition at line 2389 of file DeclCXX.h.
Referenced by clang::ASTRecordReader::readCXXCtorInitializers().
The documentation for this class was generated from the following files:
include/clang/AST/DeclCXX.h
lib/AST/DeclCXX.cpp