clang: clang::dataflow::ChromiumCheckModel Class Reference
clang::dataflow::ChromiumCheckModel Class Reference
Models the behavior of Chromium's CHECK, DCHECK, etc.
#include "clang/Analysis/FlowSensitive/Models/ChromiumCheckModel.h"
Public Member Functions
ChromiumCheckModel ()=default
bool transfer (const Stmt *Stmt, Environment &Env) override
Return value indicates whether the model processed the Stmt.
Public Member Functions inherited from clang::dataflow::DataflowModel
Public Member Functions inherited from clang::dataflow::Environment::ValueModel
virtual ~ValueModel ()=default
virtual bool compareEquivalent (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2)
Returns true if and only if Val1 is equivalent to Val2.
virtual bool merge (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2, Value &MergedVal, Environment &MergedEnv)
Modifies MergedVal to approximate both Val1 and Val2.
Detailed Description
Models the behavior of Chromium's CHECK, DCHECK, etc.
macros, so that code after a call to *CHECK can rely on the condition being true.
Definition at line 26 of file ChromiumCheckModel.h.
Constructor & Destructor Documentation
ChromiumCheckModel()
clang::dataflow::ChromiumCheckModel::ChromiumCheckModel () default
Member Function Documentation
transfer()
bool clang::dataflow::ChromiumCheckModel::transfer (const Stmt * Stmt, Environment & Env) override virtual
Return value indicates whether the model processed the Stmt.
Implements clang::dataflow::DataflowModel.
Definition at line 53 of file ChromiumCheckModel.cpp.
References clang::dataflow::Environment::addToFlowCondition(), clang::dataflow::Environment::getBoolLiteralValue(), and clang::dataflow::isCheckLikeMethod().
The documentation for this class was generated from the following files:
include/clang/Analysis/FlowSensitive/Models/ChromiumCheckModel.h
lib/Analysis/FlowSensitive/Models/ChromiumCheckModel.cpp