clang: clang::Sema::DefaultedFunctionKind Class Reference
clang::Sema::DefaultedFunctionKind Class Reference
For a defaulted function, the kind of defaulted function that it is.
#include "clang/Sema/Sema.h"
Public Member Functions
DefaultedFunctionKind ()
DefaultedFunctionKind (CXXSpecialMember CSM)
DefaultedFunctionKind (DefaultedComparisonKind Comp)
bool isSpecialMember () const
bool isComparison () const
operator bool () const
CXXSpecialMember asSpecialMember () const
DefaultedComparisonKind asComparison () const
unsigned getDiagnosticIndex () const
Get the index of this function kind for use in diagnostics.
Detailed Description
For a defaulted function, the kind of defaulted function that it is.
Definition at line 3305 of file Sema.h.
Constructor & Destructor Documentation
DefaultedFunctionKind() [1/3]
clang::Sema::DefaultedFunctionKind::DefaultedFunctionKind () inline
Definition at line 3310 of file Sema.h.
DefaultedFunctionKind() [2/3]
clang::Sema::DefaultedFunctionKind::DefaultedFunctionKind (CXXSpecialMember CSM) inline
Definition at line 3313 of file Sema.h.
DefaultedFunctionKind() [3/3]
clang::Sema::DefaultedFunctionKind::DefaultedFunctionKind (DefaultedComparisonKind Comp) inline
Definition at line 3315 of file Sema.h.
Member Function Documentation
asComparison()
DefaultedComparisonKind clang::Sema::DefaultedFunctionKind::asComparison () const inline
Definition at line 3328 of file Sema.h.
Referenced by clang::Sema::CheckCompletedCXXClass(), clang::Sema::CheckExplicitlyDefaultedFunction(), DefineDefaultedFunction(), clang::Sema::DiagnoseDeletedDefaultedFunction(), clang::Sema::getDefaultedComparisonKind(), clang::Sema::PrintInstantiationStack(), and clang::Sema::SetDeclDefaulted().
asSpecialMember()
CXXSpecialMember clang::Sema::DefaultedFunctionKind::asSpecialMember () const inline
Definition at line 3327 of file Sema.h.
Referenced by clang::Sema::CheckExplicitlyDefaultedFunction(), clang::Sema::CreateOverloadedBinOp(), DefineDefaultedFunction(), clang::Sema::DiagnoseDeletedDefaultedFunction(), clang::Sema::getSpecialMember(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::PrintInstantiationStack(), and clang::Sema::SetDeclDefaulted().
getDiagnosticIndex()
unsigned clang::Sema::DefaultedFunctionKind::getDiagnosticIndex () const inline
Get the index of this function kind for use in diagnostics.
Definition at line 3331 of file Sema.h.
References clang::Sema::CXXDestructor, clang::Sema::CXXInvalid, and clang::Sema::None.
isComparison()
bool clang::Sema::DefaultedFunctionKind::isComparison () const inline
Definition at line 3319 of file Sema.h.
References clang::Sema::None.
Referenced by clang::Sema::CheckExplicitlyDefaultedFunction(), clang::Sema::CreateOverloadedBinOp(), DefineDefaultedFunction(), operator bool(), clang::Sema::PrintInstantiationStack(), and clang::Sema::SetDeclDefaulted().
isSpecialMember()
bool clang::Sema::DefaultedFunctionKind::isSpecialMember () const inline
Definition at line 3318 of file Sema.h.
References clang::Sema::CXXInvalid.
Referenced by clang::Sema::CheckExplicitlyDefaultedFunction(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::DiagnoseDeletedDefaultedFunction(), operator bool(), and clang::Sema::PrintInstantiationStack().
operator bool()
clang::Sema::DefaultedFunctionKind::operator bool () const inline explicit
Definition at line 3323 of file Sema.h.
References isComparison(), and isSpecialMember().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h