clang: clang::Diagnostic Class Reference
clang::Diagnostic Class Reference
A little helper class (which is basically a smart pointer that forwards info from DiagnosticsEngine) that allows clients to enquire about the currently in-flight diagnostic.
#include "clang/Basic/Diagnostic.h"
Public Member Functions
Diagnostic (const DiagnosticsEngine *DO)
Diagnostic (const DiagnosticsEngine *DO, StringRef storedDiagMessage)
const DiagnosticsEngine * getDiags () const
unsigned getID () const
const SourceLocation & getLocation () const
bool hasSourceManager () const
SourceManager & getSourceManager () const
unsigned getNumArgs () const
DiagnosticsEngine::ArgumentKind getArgKind (unsigned Idx) const
Return the kind of the specified index.
const std::string & getArgStdStr (unsigned Idx) const
Return the provided argument string specified by Idx.
const char * getArgCStr (unsigned Idx) const
Return the specified C string argument.
int64_t getArgSInt (unsigned Idx) const
Return the specified signed integer argument.
uint64_t getArgUInt (unsigned Idx) const
Return the specified unsigned integer argument.
const IdentifierInfo * getArgIdentifier (unsigned Idx) const
Return the specified IdentifierInfo argument.
uint64_t getRawArg (unsigned Idx) const
Return the specified non-string argument in an opaque form.
unsigned getNumRanges () const
Return the number of source ranges associated with this diagnostic.
const CharSourceRange & getRange (unsigned Idx) const
ArrayRef< CharSourceRange > getRanges () const
Return an array reference for this diagnostic's ranges.
unsigned getNumFixItHints () const
const FixItHint & getFixItHint (unsigned Idx) const
ArrayRef< FixItHint > getFixItHints () const
void FormatDiagnostic (SmallVectorImpl< char > &OutStr) const
Format this diagnostic into a string, substituting the formal arguments into the %0 slots.
void FormatDiagnostic (const char *DiagStr, const char *DiagEnd, SmallVectorImpl< char > &OutStr) const
Format the given format-string into the output buffer using the arguments stored in this diagnostic.
Detailed Description
A little helper class (which is basically a smart pointer that forwards info from DiagnosticsEngine) that allows clients to enquire about the currently in-flight diagnostic.
Definition at line 1561 of file Diagnostic.h.
Constructor & Destructor Documentation
Diagnostic() [1/2]
clang::Diagnostic::Diagnostic (const DiagnosticsEngine * DO) inline explicit
Definition at line 1566 of file Diagnostic.h.
Diagnostic() [2/2]
clang::Diagnostic::Diagnostic (const DiagnosticsEngine * DO, StringRef storedDiagMessage) inline
Definition at line 1567 of file Diagnostic.h.
Member Function Documentation
FormatDiagnostic() [1/2]
void Diagnostic::FormatDiagnostic (const char * DiagStr, const char * DiagEnd, SmallVectorImpl< char > & OutStr) const
Format the given format-string into the output buffer using the arguments stored in this diagnostic.
FormattedArgs - Keep track of all of the arguments formatted by ConvertArgToString and pass them into subsequent calls to ConvertArgToString, allowing the implementation to avoid redundancies in obvious cases.
QualTypeVals - Pass a vector of arrays so that QualType names can be compared to see if more information is needed to be printed.
Definition at line 851 of file Diagnostic.cpp.
References clang::DiagnosticsEngine::ak_addrspace, clang::DiagnosticsEngine::ak_attr, clang::DiagnosticsEngine::ak_c_string, clang::DiagnosticsEngine::ak_declarationname, clang::DiagnosticsEngine::ak_declcontext, clang::DiagnosticsEngine::ak_identifierinfo, clang::DiagnosticsEngine::ak_nameddecl, clang::DiagnosticsEngine::ak_nestednamespec, clang::DiagnosticsEngine::ak_qual, clang::DiagnosticsEngine::ak_qualtype, clang::DiagnosticsEngine::ak_qualtype_pair, clang::DiagnosticsEngine::ak_sint, clang::DiagnosticsEngine::ak_std_string, clang::DiagnosticsEngine::ak_tokenkind, clang::DiagnosticsEngine::ak_uint, clang::TemplateDiffTypes::ElideType, clang::TemplateDiffTypes::FromType, clang::tok::getKeywordSpelling(), clang::IdentifierInfo::getName(), clang::tok::getPunctuatorSpelling(), getTokenDescForDiagnostic(), clang::tok::getTokenName(), HandleIntegerSModifier(), HandleOrdinalModifier(), HandlePluralModifier(), HandleSelectModifier(), clang::isDigit(), clang::isPunctuation(), ModifierIs(), clang::Pipe, clang::TemplateDiffTypes::PrintFromType, clang::TemplateDiffTypes::PrintTree, pushEscapedString(), ScanFormat(), clang::TemplateDiffTypes::ShowColors, clang::TemplateDiffTypes::TemplateDiffUsed, clang::TemplateDiffTypes::ToType, and Tree.
FormatDiagnostic() [2/2]
void Diagnostic::FormatDiagnostic (SmallVectorImpl< char > & OutStr) const
Format this diagnostic into a string, substituting the formal arguments into the %0 slots.
FormatDiagnostic - Format this diagnostic into a string, substituting the formal arguments into the %0 slots.
The result is appended onto the OutStr array.
The result is appended onto the Str array.
Definition at line 794 of file Diagnostic.cpp.
References Diag().
Referenced by clang::PartialDiagnostic::EmitToString(), clang::format::FatalDiagnosticConsumer::HandleDiagnostic(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::TextDiagnosticBuffer::HandleDiagnostic(), clang::TextDiagnosticPrinter::HandleDiagnostic(), HandlePluralModifier(), HandleSelectModifier(), and clang::StoredDiagnostic::StoredDiagnostic().
getArgCStr()
const char * clang::Diagnostic::getArgCStr (unsigned Idx) const inline
Return the specified C string argument.
Precondition
getArgKind(Idx) == DiagnosticsEngine::ak_c_string
Definition at line 1600 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_c_string, clang::DiagnosticStorage::DiagArgumentsVal, and getArgKind().
getArgIdentifier()
const IdentifierInfo * clang::Diagnostic::getArgIdentifier (unsigned Idx) const inline
Return the specified IdentifierInfo argument.
Precondition
getArgKind(Idx) == DiagnosticsEngine::ak_identifierinfo
Definition at line 1625 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_identifierinfo, clang::DiagnosticStorage::DiagArgumentsVal, and getArgKind().
getArgKind()
DiagnosticsEngine::ArgumentKind clang::Diagnostic::getArgKind (unsigned Idx) const inline
Return the kind of the specified index.
Based on the kind of argument, the accessors below can be used to get the value.
Precondition
Idx < getNumArgs()
Definition at line 1584 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagArgumentsKind, and getNumArgs().
Referenced by getArgCStr(), getArgIdentifier(), getArgSInt(), getArgStdStr(), getArgUInt(), and getRawArg().
getArgSInt()
int64_t clang::Diagnostic::getArgSInt (unsigned Idx) const inline
Return the specified signed integer argument.
Precondition
getArgKind(Idx) == DiagnosticsEngine::ak_sint
Definition at line 1609 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_sint, clang::DiagnosticStorage::DiagArgumentsVal, and getArgKind().
getArgStdStr()
const std::string & clang::Diagnostic::getArgStdStr (unsigned Idx) const inline
Return the provided argument string specified by Idx.
Precondition
getArgKind(Idx) == DiagnosticsEngine::ak_std_string
Definition at line 1592 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_std_string, clang::DiagnosticStorage::DiagArgumentsStr, and getArgKind().
getArgUInt()
uint64_t clang::Diagnostic::getArgUInt (unsigned Idx) const inline
Return the specified unsigned integer argument.
Precondition
getArgKind(Idx) == DiagnosticsEngine::ak_uint
Definition at line 1617 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_uint, clang::DiagnosticStorage::DiagArgumentsVal, and getArgKind().
getDiags()
const DiagnosticsEngine * clang::Diagnostic::getDiags () const inline
Definition at line 1570 of file Diagnostic.h.
Referenced by printDiagnosticOptions().
getFixItHint()
const FixItHint & clang::Diagnostic::getFixItHint (unsigned Idx) const inline
Definition at line 1660 of file Diagnostic.h.
References clang::DiagnosticStorage::FixItHints, and getNumFixItHints().
Referenced by clang::FixItRewriter::HandleDiagnostic(), and clang::PartialDiagnostic::PartialDiagnostic().
getFixItHints()
ArrayRef< FixItHint > clang::Diagnostic::getFixItHints () const inline
Definition at line 1665 of file Diagnostic.h.
References clang::DiagnosticStorage::FixItHints.
Referenced by clang::TextDiagnosticPrinter::HandleDiagnostic(), and clang::StoredDiagnostic::StoredDiagnostic().
getID()
unsigned clang::Diagnostic::getID () const inline
Definition at line 1571 of file Diagnostic.h.
Referenced by clang::DiagnosticsEngine::EmitCurrentDiagnostic(), clang::LogDiagnosticPrinter::HandleDiagnostic(), and printDiagnosticOptions().
getLocation()
const SourceLocation & clang::Diagnostic::getLocation () const inline
Definition at line 1572 of file Diagnostic.h.
Referenced by clang::DiagnosticsEngine::EmitCurrentDiagnostic(), clang::Sema::EmitCurrentDiagnostic(), clang::FixItRewriter::HandleDiagnostic(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::TextDiagnosticBuffer::HandleDiagnostic(), clang::TextDiagnosticPrinter::HandleDiagnostic(), clang::VerifyDiagnosticConsumer::HandleDiagnostic(), isInMainFile(), and clang::StoredDiagnostic::StoredDiagnostic().
getNumArgs()
unsigned clang::Diagnostic::getNumArgs () const inline
Definition at line 1576 of file Diagnostic.h.
References clang::DiagnosticStorage::NumDiagArgs.
Referenced by getArgKind(), and clang::PartialDiagnostic::PartialDiagnostic().
getNumFixItHints()
unsigned clang::Diagnostic::getNumFixItHints () const inline
Definition at line 1656 of file Diagnostic.h.
References clang::DiagnosticStorage::FixItHints.
Referenced by getFixItHint(), clang::FixItRewriter::HandleDiagnostic(), and clang::PartialDiagnostic::PartialDiagnostic().
getNumRanges()
unsigned clang::Diagnostic::getNumRanges () const inline
Return the number of source ranges associated with this diagnostic.
Definition at line 1641 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagRanges.
Referenced by getRange(), and clang::PartialDiagnostic::PartialDiagnostic().
getRange()
const CharSourceRange & clang::Diagnostic::getRange (unsigned Idx) const inline
Precondition
Idx < getNumRanges()
Definition at line 1646 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagRanges, and getNumRanges().
Referenced by clang::PartialDiagnostic::PartialDiagnostic().
getRanges()
ArrayRef< CharSourceRange > clang::Diagnostic::getRanges () const inline
Return an array reference for this diagnostic's ranges.
Definition at line 1652 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagRanges.
Referenced by clang::TextDiagnosticPrinter::HandleDiagnostic(), and clang::StoredDiagnostic::StoredDiagnostic().
getRawArg()
uint64_t clang::Diagnostic::getRawArg (unsigned Idx) const inline
Return the specified non-string argument in an opaque form.
Precondition
getArgKind(Idx) != DiagnosticsEngine::ak_std_string
Definition at line 1634 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_std_string, clang::DiagnosticStorage::DiagArgumentsVal, and getArgKind().
getSourceManager()
SourceManager & clang::Diagnostic::getSourceManager () const inline
Definition at line 1574 of file Diagnostic.h.
References clang::DiagnosticsEngine::getSourceManager().
Referenced by clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::TextDiagnosticPrinter::HandleDiagnostic(), clang::VerifyDiagnosticConsumer::HandleDiagnostic(), isInMainFile(), and clang::StoredDiagnostic::StoredDiagnostic().
hasSourceManager()
bool clang::Diagnostic::hasSourceManager () const inline
Definition at line 1573 of file Diagnostic.h.
References clang::DiagnosticsEngine::hasSourceManager().
Referenced by clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::TextDiagnosticPrinter::HandleDiagnostic(), clang::VerifyDiagnosticConsumer::HandleDiagnostic(), isInMainFile(), and clang::StoredDiagnostic::StoredDiagnostic().
The documentation for this class was generated from the following files:
include/clang/Basic/Diagnostic.h
lib/Basic/Diagnostic.cpp