clang: StoreSiteFinder Class Reference
StoreSiteFinder Class Reference final
Finds last store into the given region, which is different from a given symbolic value.
Public Member Functions
StoreSiteFinder (bugreporter::TrackerRef ParentTracker, KnownSVal V, const MemRegion *R, TrackingOptions Options, const StackFrameContext *OriginSFC=nullptr)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
Public Member Functions inherited from clang::ento::bugreporter::TrackingBugReporterVisitor
TrackingBugReporterVisitor (TrackerRef ParentTracker)
Tracker & getParentTracker ()
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
virtual PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR)
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Additional Inherited Members
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
Finds last store into the given region, which is different from a given symbolic value.
Definition at line 1198 of file BugReporterVisitors.cpp.
Constructor & Destructor Documentation
StoreSiteFinder()
StoreSiteFinder::StoreSiteFinder (bugreporter::TrackerRef ParentTracker, KnownSVal V, const MemRegion * R, TrackingOptions Options, const StackFrameContext * OriginSFC = nullptr) inline
Parameters
V We're searching for the store where R received this value.
R The region we're tracking.
Options Tracking behavior options.
OriginSFC Only adds notes when the last store happened in a different stackframe to this one. Disregarded if the tracking kind is thorough. This is useful, because for non-tracked regions, notes about changes to its value in a nested stackframe could be pruned, and this visitor can prevent that without polluting the bugpath too much.
Definition at line 1217 of file BugReporterVisitors.cpp.
Member Function Documentation
Profile()
void StoreSiteFinder::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 1232 of file BugReporterVisitors.cpp.
References V.
VisitNode()
PathDiagnosticPieceRef StoreSiteFinder::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 1413 of file BugReporterVisitors.cpp.
References clang::ento::bugreporter::StoreInfo::Assignment, clang::ento::bugreporter::StoreInfo::BlockCapture, clang::ento::bugreporter::StoreInfo::CallArgument, clang::cast(), clang::ento::bugreporter::StoreInfo::Dest, clang::ProgramPoint::getAs(), clang::ento::CallEventManager::getCaller(), clang::ento::ProgramStateManager::getCallEventManager(), clang::ento::ExplodedNode::getFirstPred(), clang::ento::ExplodedNode::getLocation(), clang::ento::ExplodedNode::getLocationAs(), getLocationRegionIfReference(), clang::ento::StoreManager::FindUniqueBinding::getRegion(), clang::ento::ExplodedNode::getStackFrame(), clang::ento::ExplodedNode::getState(), clang::ento::BugReporterContext::getStateManager(), clang::ento::ProgramStateManager::getStoreManager(), clang::ento::ExplodedNode::getSVal(), hasVisibleUpdate(), clang::Expr::IgnoreParenCasts(), clang::ento::bugreporter::StoreInfo::Initialization, isInitializationOfVar(), clang::ento::ProgramStateManager::iterBindings(), N, P, SM, clang::ento::bugreporter::StoreInfo::StoreKind, clang::ento::bugreporter::StoreInfo::StoreSite, and V.
The documentation for this class was generated from the following file:
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp