clang: clang::driver::tools::XCore::Assembler Class Reference
clang::driver::tools::XCore::Assembler Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/XCore.h"
Public Member Functions
Assembler (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
XCore Tools.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 23 of file XCore.h.
Constructor & Destructor Documentation
Assembler()
clang::driver::tools::XCore::Assembler::Assembler (const ToolChain & TC) inline
Definition at line 25 of file XCore.h.
Member Function Documentation
ConstructJob()
void tools::XCore::Assembler::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
XCore Tools.
Implements clang::driver::Tool.
Definition at line 25 of file XCore.cpp.
References clang::C, clang::driver::tools::claimNoWarnArgs(), clang::driver::InputInfo::getFilename(), clang::driver::Tool::getToolChain(), and clang::driver::ResponseFileSupport::None().
hasIntegratedCPP()
bool clang::driver::tools::XCore::Assembler::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 27 of file XCore.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/XCore.h
lib/Driver/ToolChains/XCore.cpp