clang: clang::threadSafety::til::EqualsComparator Class Reference
clang::threadSafety::til::EqualsComparator Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyTraverse.h"
Public Types
using CType = bool
Public Member Functions
CType trueResult ()
bool notTrue (CType ct)
bool compareIntegers (unsigned i, unsigned j)
bool compareStrings (StringRef s, StringRef r)
bool comparePointers (const void *P, const void *Q)
bool compare (const SExpr *E1, const SExpr *E2)
void enterScope (const Variable *V1, const Variable *V2)
void leaveScope ()
bool compareVariableRefs (const Variable *V1, const Variable *V2)
Public Member Functions inherited from clang::threadSafety::til::Comparator< EqualsComparator >
bool compareByCase (const SExpr *E1, const SExpr *E2)
Static Public Member Functions
static bool compareExprs (const SExpr *E1, const SExpr *E2)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::Comparator< EqualsComparator >
EqualsComparator * self ()
Detailed Description
Definition at line 327 of file ThreadSafetyTraverse.h.
Member Typedef Documentation
CType
using clang::threadSafety::til::EqualsComparator::CType = bool
Definition at line 332 of file ThreadSafetyTraverse.h.
Member Function Documentation
compare()
bool clang::threadSafety::til::EqualsComparator::compare (const SExpr * E1, const SExpr * E2) inline
Definition at line 341 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Comparator< EqualsComparator >::compareByCase(), and clang::threadSafety::til::SExpr::opcode().
Referenced by compareExprs().
compareExprs()
static bool clang::threadSafety::til::EqualsComparator::compareExprs (const SExpr * E1, const SExpr * E2) inline static
Definition at line 355 of file ThreadSafetyTraverse.h.
References compare(), and clang::ast_matchers::Eq.
Referenced by clang::threadSafety::sx::equals().
compareIntegers()
bool clang::threadSafety::til::EqualsComparator::compareIntegers (unsigned i, unsigned j) inline
Definition at line 337 of file ThreadSafetyTraverse.h.
comparePointers()
bool clang::threadSafety::til::EqualsComparator::comparePointers (const void * P, const void * Q) inline
Definition at line 339 of file ThreadSafetyTraverse.h.
References P.
compareStrings()
bool clang::threadSafety::til::EqualsComparator::compareStrings (StringRef s, StringRef r) inline
Definition at line 338 of file ThreadSafetyTraverse.h.
References s.
compareVariableRefs()
bool clang::threadSafety::til::EqualsComparator::compareVariableRefs (const Variable * V1, const Variable * V2) inline
Definition at line 351 of file ThreadSafetyTraverse.h.
enterScope()
void clang::threadSafety::til::EqualsComparator::enterScope (const Variable * V1, const Variable * V2) inline
Definition at line 348 of file ThreadSafetyTraverse.h.
leaveScope()
void clang::threadSafety::til::EqualsComparator::leaveScope () inline
Definition at line 349 of file ThreadSafetyTraverse.h.
notTrue()
bool clang::threadSafety::til::EqualsComparator::notTrue (CType ct) inline
Definition at line 335 of file ThreadSafetyTraverse.h.
trueResult()
CType clang::threadSafety::til::EqualsComparator::trueResult () inline
Definition at line 334 of file ThreadSafetyTraverse.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTraverse.h