clang: clang::VirtSpecifiers Class Reference
clang::VirtSpecifiers Class Reference
Represents a C++11 virt-specifier-seq.
#include "clang/Sema/DeclSpec.h"
Public Types
enum Specifier {
VS_None = 0 , VS_Override = 1 , VS_Final = 2 , VS_Sealed = 4 ,
VS_GNU_Final = 8 , VS_Abstract = 16
}
Public Member Functions
VirtSpecifiers ()
bool SetSpecifier (Specifier VS, SourceLocation Loc, const char *&PrevSpec)
bool isUnset () const
bool isOverrideSpecified () const
SourceLocation getOverrideLoc () const
bool isFinalSpecified () const
bool isFinalSpelledSealed () const
SourceLocation getFinalLoc () const
SourceLocation getAbstractLoc () const
void clear ()
SourceLocation getFirstLocation () const
SourceLocation getLastLocation () const
Specifier getLastSpecifier () const
Static Public Member Functions
static const char * getSpecifierName (Specifier VS)
Detailed Description
Represents a C++11 virt-specifier-seq.
Definition at line 2658 of file DeclSpec.h.
Member Enumeration Documentation
Specifier
enum clang::VirtSpecifiers::Specifier
Enumerator
VS_None
VS_Override
VS_Final
VS_Sealed
VS_GNU_Final
VS_Abstract
Definition at line 2660 of file DeclSpec.h.
Constructor & Destructor Documentation
VirtSpecifiers()
clang::VirtSpecifiers::VirtSpecifiers () inline
Definition at line 2670 of file DeclSpec.h.
Member Function Documentation
clear()
void clang::VirtSpecifiers::clear () inline
Definition at line 2685 of file DeclSpec.h.
getAbstractLoc()
SourceLocation clang::VirtSpecifiers::getAbstractLoc () const inline
Definition at line 2683 of file DeclSpec.h.
getFinalLoc()
SourceLocation clang::VirtSpecifiers::getFinalLoc () const inline
Definition at line 2682 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
getFirstLocation()
SourceLocation clang::VirtSpecifiers::getFirstLocation () const inline
Definition at line 2689 of file DeclSpec.h.
getLastLocation()
SourceLocation clang::VirtSpecifiers::getLastLocation () const inline
Definition at line 2690 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
getLastSpecifier()
Specifier clang::VirtSpecifiers::getLastSpecifier () const inline
Definition at line 2691 of file DeclSpec.h.
getOverrideLoc()
SourceLocation clang::VirtSpecifiers::getOverrideLoc () const inline
Definition at line 2678 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
getSpecifierName()
const char * VirtSpecifiers::getSpecifierName (Specifier VS) static
Definition at line 1492 of file DeclSpec.cpp.
References VS_Abstract, VS_Final, VS_GNU_Final, VS_Override, and VS_Sealed.
Referenced by SetSpecifier().
isFinalSpecified()
bool clang::VirtSpecifiers::isFinalSpecified () const inline
Definition at line 2680 of file DeclSpec.h.
References VS_Final, VS_GNU_Final, and VS_Sealed.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), and clang::Sema::CodeCompleteFunctionQualifiers().
isFinalSpelledSealed()
bool clang::VirtSpecifiers::isFinalSpelledSealed () const inline
Definition at line 2681 of file DeclSpec.h.
References VS_Sealed.
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
isOverrideSpecified()
bool clang::VirtSpecifiers::isOverrideSpecified () const inline
Definition at line 2677 of file DeclSpec.h.
References VS_Override.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), and clang::Sema::CodeCompleteFunctionQualifiers().
isUnset()
bool clang::VirtSpecifiers::isUnset () const inline
Definition at line 2675 of file DeclSpec.h.
SetSpecifier()
bool VirtSpecifiers::SetSpecifier (Specifier VS, SourceLocation Loc, const char *& PrevSpec)
Definition at line 1466 of file DeclSpec.cpp.
References getSpecifierName(), clang::SourceLocation::isValid(), VS_Abstract, VS_Final, VS_GNU_Final, VS_Override, and VS_Sealed.
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp