clang: clang::api_notes::ParamInfo Class Reference
clang::api_notes::ParamInfo Class Reference
Describes a function or method parameter.
#include "clang/APINotes/Types.h"
Public Member Functions
ParamInfo ()
llvm::Optional< bool > isNoEscape () const
void setNoEscape (llvm::Optional< bool > Value)
llvm::Optional< RetainCountConventionKind > getRetainCountConvention () const
void setRetainCountConvention (llvm::Optional< RetainCountConventionKind > Value)
ParamInfo & operator|= (const ParamInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::VariableInfo
VariableInfo ()
llvm::Optional< NullabilityKind > getNullability () const
void setNullabilityAudited (NullabilityKind kind)
const std::string & getType () const
void setType (const std::string &type)
VariableInfo & operator|= (const VariableInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Friends
bool operator== (const ParamInfo &LHS, const ParamInfo &RHS)
Additional Inherited Members
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Detailed Description
Describes a function or method parameter.
Definition at line 410 of file Types.h.
Constructor & Destructor Documentation
ParamInfo()
clang::api_notes::ParamInfo::ParamInfo () inline
Definition at line 423 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::ParamInfo::dump (llvm::raw_ostream & OS) const
Definition at line 64 of file APINotesTypes.cpp.
References clang::api_notes::VariableInfo::dump().
getRetainCountConvention()
llvm::Optional< RetainCountConventionKind > clang::api_notes::ParamInfo::getRetainCountConvention () const inline
Definition at line 436 of file Types.h.
Referenced by setRetainCountConvention().
isNoEscape()
llvm::Optional< bool > clang::api_notes::ParamInfo::isNoEscape () const inline
Definition at line 426 of file Types.h.
operator|=()
ParamInfo & clang::api_notes::ParamInfo::operator|= (const ParamInfo & RHS) inline
Definition at line 447 of file Types.h.
setNoEscape()
void clang::api_notes::ParamInfo::setNoEscape (llvm::Optional< bool > Value) inline
Definition at line 431 of file Types.h.
setRetainCountConvention()
void clang::api_notes::ParamInfo::setRetainCountConvention (llvm::Optional< RetainCountConventionKind > Value) inline
Definition at line 442 of file Types.h.
References getRetainCountConvention().
Friends And Related Symbol Documentation
operator==
bool operator== (const ParamInfo & LHS, const ParamInfo & RHS) friend
Definition at line 466 of file Types.h.
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp