clang: clang::SwitchCase Class Reference
clang::SwitchCase Class Reference
#include "clang/AST/Stmt.h"
Public Member Functions
const SwitchCase * getNextSwitchCase () const
SwitchCase * getNextSwitchCase ()
void setNextSwitchCase (SwitchCase *SC)
SourceLocation getKeywordLoc () const
void setKeywordLoc (SourceLocation L)
SourceLocation getColonLoc () const
void setColonLoc (SourceLocation L)
Stmt * getSubStmt ()
const Stmt * getSubStmt () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const LLVM_READONLY
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Protected Member Functions
SwitchCase (StmtClass SC, SourceLocation KWLoc, SourceLocation ColonLoc)
SwitchCase (StmtClass SC, EmptyShell)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes
SourceLocation ColonLoc
The location of the ":".
SwitchCase * NextSwitchCase = nullptr
A pointer to the following CaseStmt or DefaultStmt class, used by SwitchStmt.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Detailed Description
Definition at line 1554 of file Stmt.h.
Constructor & Destructor Documentation
SwitchCase() [1/2]
clang::SwitchCase::SwitchCase (StmtClass SC, SourceLocation KWLoc, SourceLocation ColonLoc) inline protected
Definition at line 1566 of file Stmt.h.
References setKeywordLoc().
SwitchCase() [2/2]
clang::SwitchCase::SwitchCase (StmtClass SC, EmptyShell) inline protected
Definition at line 1571 of file Stmt.h.
Member Function Documentation
classof()
static bool clang::SwitchCase::classof (const Stmt * T) inline static
Definition at line 1591 of file Stmt.h.
getBeginLoc()
SourceLocation clang::SwitchCase::getBeginLoc () const inline
Definition at line 1588 of file Stmt.h.
References getKeywordLoc().
Referenced by EvaluateSwitch().
getColonLoc()
SourceLocation clang::SwitchCase::getColonLoc () const inline
Definition at line 1580 of file Stmt.h.
References ColonLoc.
getEndLoc()
SourceLocation clang::SwitchCase::getEndLoc () const inline
Definition at line 1790 of file Stmt.h.
getKeywordLoc()
SourceLocation clang::SwitchCase::getKeywordLoc () const inline
Definition at line 1578 of file Stmt.h.
References clang::Stmt::SwitchCaseBits.
Referenced by clang::CaseStmt::getBeginLoc(), clang::DefaultStmt::getBeginLoc(), getBeginLoc(), clang::CaseStmt::getCaseLoc(), and clang::DefaultStmt::getDefaultLoc().
getNextSwitchCase() [1/2]
SwitchCase * clang::SwitchCase::getNextSwitchCase () inline
Definition at line 1575 of file Stmt.h.
References NextSwitchCase.
getNextSwitchCase() [2/2]
const SwitchCase * clang::SwitchCase::getNextSwitchCase () const inline
Definition at line 1574 of file Stmt.h.
References NextSwitchCase.
Referenced by clang::SwitchStmt::addSwitchCase(), clang::Sema::CodeCompleteCase(), EvaluateSwitch(), and FindCaseStatementsForValue().
getSubStmt() [1/2]
Stmt * clang::SwitchCase::getSubStmt () inline
Definition at line 1798 of file Stmt.h.
Referenced by getSubStmt().
getSubStmt() [2/2]
const Stmt * clang::SwitchCase::getSubStmt () const inline
Definition at line 1584 of file Stmt.h.
References getSubStmt().
setColonLoc()
void clang::SwitchCase::setColonLoc (SourceLocation L) inline
Definition at line 1581 of file Stmt.h.
References ColonLoc.
setKeywordLoc()
void clang::SwitchCase::setKeywordLoc (SourceLocation L) inline
Definition at line 1579 of file Stmt.h.
References clang::Stmt::SwitchCaseBits.
Referenced by clang::CaseStmt::setCaseLoc(), clang::DefaultStmt::setDefaultLoc(), and SwitchCase().
setNextSwitchCase()
void clang::SwitchCase::setNextSwitchCase (SwitchCase * SC) inline
Definition at line 1576 of file Stmt.h.
References NextSwitchCase.
Referenced by clang::SwitchStmt::addSwitchCase(), and clang::ASTNodeImporter::VisitSwitchStmt().
Member Data Documentation
ColonLoc
SourceLocation clang::SwitchCase::ColonLoc protected
The location of the ":".
Definition at line 1557 of file Stmt.h.
Referenced by getColonLoc(), and setColonLoc().
NextSwitchCase
SwitchCase* clang::SwitchCase::NextSwitchCase = nullptr protected
A pointer to the following CaseStmt or DefaultStmt class, used by SwitchStmt.
Definition at line 1564 of file Stmt.h.
Referenced by getNextSwitchCase(), getNextSwitchCase(), and setNextSwitchCase().
The documentation for this class was generated from the following file:
include/clang/AST/Stmt.h