clang: clang::ento::Range Class Reference
clang::ento::Range Class Reference
A Range represents the closed range [from, to].
#include "clang/StaticAnalyzer/Core/PathSensitive/RangedConstraintManager.h"
Public Member Functions
Range (const llvm::APSInt &From, const llvm::APSInt &To)
Range (const llvm::APSInt &Point)
bool Includes (const llvm::APSInt &Point) const
const llvm::APSInt & From () const
const llvm::APSInt & To () const
const llvm::APSInt * getConcreteValue () const
void Profile (llvm::FoldingSetNodeID &ID) const
void dump (raw_ostream &OS) const
void dump () const
bool operator< (const Range &RHS) const
bool operator== (const Range &RHS) const
bool operator!= (const Range &RHS) const
Detailed Description
A Range represents the closed range [from, to].
The caller must guarantee that from <= to. Note that Range is immutable, so as not to subvert RangeSet's immutability.
Definition at line 29 of file RangedConstraintManager.h.
Constructor & Destructor Documentation
Range() [1/2]
clang::ento::Range::Range (const llvm::APSInt & From, const llvm::APSInt & To) inline
Definition at line 31 of file RangedConstraintManager.h.
References From(), and To().
Referenced by clang::ento::PathDiagnosticLocation::operator==().
Range() [2/2]
clang::ento::Range::Range (const llvm::APSInt & Point) inline
Definition at line 35 of file RangedConstraintManager.h.
Member Function Documentation
dump() [1/2]
LLVM_DUMP_METHOD void Range::dump () const
Definition at line 866 of file RangeConstraintManager.cpp.
References clang::ento::RangeSet::dump().
dump() [2/2]
LLVM_DUMP_METHOD void Range::dump (raw_ostream & OS) const
Definition at line 863 of file RangeConstraintManager.cpp.
References clang::ento::OS, and toString().
Referenced by clang::ento::RangeSet::dump().
From()
const llvm::APSInt & clang::ento::Range::From () const inline
Definition at line 40 of file RangedConstraintManager.h.
Referenced by getConcreteValue(), Includes(), operator<(), Profile(), and Range().
getConcreteValue()
const llvm::APSInt * clang::ento::Range::getConcreteValue () const inline
Definition at line 42 of file RangedConstraintManager.h.
References From(), and To().
Includes()
bool clang::ento::Range::Includes (const llvm::APSInt & Point) const inline
Definition at line 37 of file RangedConstraintManager.h.
References From(), and To().
operator!=()
bool clang::ento::Range::operator!= (const Range & RHS) const inline
Definition at line 58 of file RangedConstraintManager.h.
References operator==().
operator<()
bool clang::ento::Range::operator< (const Range & RHS) const inline
Definition at line 55 of file RangedConstraintManager.h.
References From().
operator==()
bool clang::ento::Range::operator== (const Range & RHS) const inline
Definition at line 57 of file RangedConstraintManager.h.
Referenced by operator!=().
Profile()
void clang::ento::Range::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 46 of file RangedConstraintManager.h.
References From(), and To().
To()
const llvm::APSInt & clang::ento::Range::To () const inline
Definition at line 41 of file RangedConstraintManager.h.
Referenced by getConcreteValue(), Includes(), Profile(), and Range().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/RangedConstraintManager.h
lib/StaticAnalyzer/Core/RangeConstraintManager.cpp