clang: clang::threadSafety::til::Call Class Reference
clang::threadSafety::til::Call Class Reference
Call a function (after all arguments have been applied).
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Call (SExpr *T, const CallExpr *Ce=nullptr)
Call (const Call &C, SExpr *T)
SExpr * target ()
const SExpr * target () const
const CallExpr * clangCallExpr () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Call *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Call a function (after all arguments have been applied).
Definition at line 965 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Call() [1/2]
clang::threadSafety::til::Call::Call (SExpr * T, const CallExpr * Ce = nullptr) inline
Definition at line 967 of file ThreadSafetyTIL.h.
Call() [2/2]
clang::threadSafety::til::Call::Call (const Call & C, SExpr * T) inline
Definition at line 969 of file ThreadSafetyTIL.h.
Member Function Documentation
clangCallExpr()
const CallExpr * clang::threadSafety::til::Call::clangCallExpr () const inline
Definition at line 976 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Call::classof (const SExpr * E) inline static
Definition at line 971 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Call::compare (const Call * E, C & Cmp) const inline
Definition at line 985 of file ThreadSafetyTIL.h.
References target().
target() [1/2]
SExpr * clang::threadSafety::til::Call::target () inline
Definition at line 973 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCall().
target() [2/2]
const SExpr * clang::threadSafety::til::Call::target () const inline
Definition at line 974 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Call::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 979 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h