clang: clang::StmtPoint Class Reference
clang::StmtPoint Class Reference
#include "clang/Analysis/ProgramPoint.h"
Public Member Functions
StmtPoint (const Stmt *S, const void *p2, Kind k, const LocationContext *L, const ProgramPointTag *tag)
const Stmt * getStmt () const
template<typename T >
const T * getStmtAs () const
Public Member Functions inherited from clang::ProgramPoint
ProgramPoint withTag (const ProgramPointTag *tag) const
Create a new ProgramPoint object that is the same as the original except for using the specified tag value.
template<typename T >
T castAs () const
Convert to the specified ProgramPoint type, asserting that this ProgramPoint is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified ProgramPoint type, returning None if this ProgramPoint is not of the desired type.
Kind getKind () const
bool isPurgeKind ()
Is this a program point corresponding to purge/removal of dead symbols and bindings.
const ProgramPointTag * getTag () const
const LocationContext * getLocationContext () const
const StackFrameContext * getStackFrame () const
unsigned getHashValue () const
bool operator== (const ProgramPoint &RHS) const
bool operator!= (const ProgramPoint &RHS) const
void Profile (llvm::FoldingSetNodeID &ID) const
void printJson (llvm::raw_ostream &Out, const char *NL="\n") const
LLVM_DUMP_METHOD void dump () const
Protected Member Functions
StmtPoint ()=default
Protected Member Functions inherited from clang::ProgramPoint
ProgramPoint ()=default
ProgramPoint (const void *P, Kind k, const LocationContext *l, const ProgramPointTag *tag=nullptr)
ProgramPoint (const void *P1, const void *P2, Kind k, const LocationContext *l, const ProgramPointTag *tag=nullptr)
const void * getData1 () const
const void * getData2 () const
void setData2 (const void *d)
Friends
class ProgramPoint
Additional Inherited Members
Public Types inherited from clang::ProgramPoint
enum Kind {
BlockEdgeKind , BlockEntranceKind , BlockExitKind , PreStmtKind ,
PreStmtPurgeDeadSymbolsKind , PostStmtPurgeDeadSymbolsKind , PostStmtKind , PreLoadKind ,
PostLoadKind , PreStoreKind , PostStoreKind , PostConditionKind ,
PostLValueKind , PostAllocatorCallKind , MinPostStmtKind = PostStmtKind , MaxPostStmtKind = PostAllocatorCallKind ,
PostInitializerKind , CallEnterKind , CallExitBeginKind , CallExitEndKind ,
FunctionExitKind , PreImplicitCallKind , PostImplicitCallKind , MinImplicitCallKind = PreImplicitCallKind ,
MaxImplicitCallKind = PostImplicitCallKind , LoopExitKind , EpsilonKind
}
Static Public Member Functions inherited from clang::ProgramPoint
static ProgramPoint getProgramPoint (const Stmt *S, ProgramPoint::Kind K, const LocationContext *LC, const ProgramPointTag *tag)
Detailed Description
Definition at line 270 of file ProgramPoint.h.
Constructor & Destructor Documentation
StmtPoint() [1/2]
clang::StmtPoint::StmtPoint (const Stmt * S, const void * p2, Kind k, const LocationContext * L, const ProgramPointTag * tag) inline
Definition at line 272 of file ProgramPoint.h.
StmtPoint() [2/2]
clang::StmtPoint::StmtPoint () protected default
Member Function Documentation
getStmt()
const Stmt * clang::StmtPoint::getStmt () const inline
Definition at line 278 of file ProgramPoint.h.
References clang::ProgramPoint::getData1().
Referenced by clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), getStmtAs(), and showBRDiagnostics().
getStmtAs()
template<typename T > const T * clang::StmtPoint::getStmtAs () const inline
Definition at line 281 of file ProgramPoint.h.
References getStmt().
Friends And Related Symbol Documentation
ProgramPoint
friend class ProgramPoint friend
Definition at line 286 of file ProgramPoint.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/ProgramPoint.h