clang: clang::ento::UndefOrNullArgVisitor Class Reference
clang::ento::UndefOrNullArgVisitor Class Reference final
When a region containing undefined value or '0' value is passed as an argument in a call, marks the call as interesting.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Public Member Functions
UndefOrNullArgVisitor (const MemRegion *InR)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
virtual PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR)
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Additional Inherited Members
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
When a region containing undefined value or '0' value is passed as an argument in a call, marks the call as interesting.
As a result, BugReporter will not prune the path through the function even if the region's contents are not modified/accessed by the call.
Definition at line 546 of file BugReporterVisitors.h.
Constructor & Destructor Documentation
UndefOrNullArgVisitor()
clang::ento::UndefOrNullArgVisitor::UndefOrNullArgVisitor (const MemRegion * InR) inline
Definition at line 551 of file BugReporterVisitors.h.
Member Function Documentation
Profile()
void clang::ento::UndefOrNullArgVisitor::Profile (llvm::FoldingSetNodeID & ID) const inline override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 553 of file BugReporterVisitors.h.
VisitNode()
PathDiagnosticPieceRef UndefOrNullArgVisitor::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 3193 of file BugReporterVisitors.cpp.
References clang::ProgramPoint::getAs(), clang::ento::CallEventManager::getCaller(), clang::ento::ProgramStateManager::getCallEventManager(), clang::ento::BugReporterContext::getStateManager(), clang::ento::MemRegion::isSubRegionOf(), clang::ento::SVal::isUndef(), clang::ento::SVal::isZeroConstant(), clang::ento::PathSensitiveBugReport::markInteresting(), N, and clang::ento::MemRegion::StripCasts().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp