clang: clang::dataflow::UncheckedOptionalAccessModel Class Reference
clang::dataflow::UncheckedOptionalAccessModel Class Reference
Dataflow analysis that models whether optionals hold values or not.
#include "clang/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.h"
Public Member Functions
UncheckedOptionalAccessModel (ASTContext &AstContext, UncheckedOptionalAccessModelOptions Options={})
void transfer (const Stmt *Stmt, NoopLattice &State, Environment &Env)
bool compareEquivalent (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2) override
Returns true if and only if Val1 is equivalent to Val2.
bool merge (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2, Value &MergedVal, Environment &MergedEnv) override
Modifies MergedVal to approximate both Val1 and Val2.
Public Member Functions inherited from clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, NoopLattice >
DataflowAnalysis (ASTContext &Context)
DataflowAnalysis (ASTContext &Context, bool ApplyBuiltinTransfer)
Deprecated. Use the DataflowAnalysisOptions constructor instead.
DataflowAnalysis (ASTContext &Context, DataflowAnalysisOptions Options)
ASTContext & getASTContext () final
Returns the ASTContext that is used by the analysis.
TypeErasedLattice typeErasedInitialElement () final
Returns a type-erased lattice element that models the initial state of a basic block.
LatticeJoinEffect joinTypeErased (TypeErasedLattice &E1, const TypeErasedLattice &E2) final
Joins two type-erased lattice elements by computing their least upper bound.
bool isEqualTypeErased (const TypeErasedLattice &E1, const TypeErasedLattice &E2) final
Returns true if and only if the two given type-erased lattice elements are equal.
void transferTypeErased (const Stmt *Stmt, TypeErasedLattice &E, Environment &Env) final
Applies the analysis transfer function for a given statement and type-erased lattice element.
Public Member Functions inherited from clang::dataflow::TypeErasedDataflowAnalysis
TypeErasedDataflowAnalysis ()
TypeErasedDataflowAnalysis (bool ApplyBuiltinTransfer)
Deprecated. Use the DataflowAnalysisOptions constructor instead.
TypeErasedDataflowAnalysis (DataflowAnalysisOptions Options)
virtual ~TypeErasedDataflowAnalysis ()
bool applyBuiltinTransfer () const
Determines whether to apply the built-in transfer functions, which model the heap and stack in the Environment.
TransferOptions builtinTransferOptions () const
Returns the options to be passed to the built-in transfer functions.
Public Member Functions inherited from clang::dataflow::Environment::ValueModel
virtual ~ValueModel ()=default
Static Public Member Functions
static ast_matchers::DeclarationMatcher optionalClassDecl ()
Returns a matcher for the optional classes covered by this model.
static NoopLattice initialElement ()
Additional Inherited Members
Public Types inherited from clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, NoopLattice >
using Lattice
Bounded join-semilattice that is used in the analysis.
Detailed Description
Dataflow analysis that models whether optionals hold values or not.
Models the std::optional, absl::optional, and base::Optional types.
Definition at line 44 of file UncheckedOptionalAccessModel.h.
Constructor & Destructor Documentation
UncheckedOptionalAccessModel()
clang::dataflow::UncheckedOptionalAccessModel::UncheckedOptionalAccessModel (ASTContext & AstContext, UncheckedOptionalAccessModelOptions Options = {})
Definition at line 706 of file UncheckedOptionalAccessModel.cpp.
Member Function Documentation
compareEquivalent()
bool clang::dataflow::UncheckedOptionalAccessModel::compareEquivalent (QualType Type, const Value & Val1, const Environment & Env1, const Value & Val2, const Environment & Env2) override virtual
Returns true if and only if Val1 is equivalent to Val2.
Requirements:
Val1 and Val2 must be distinct.
Val1 and Val2 must model values of type Type.
Val1 and Val2 must be assigned to the same storage location in Env1 and Env2 respectively.
Reimplemented from clang::dataflow::Environment::ValueModel.
Definition at line 717 of file UncheckedOptionalAccessModel.cpp.
initialElement()
static NoopLattice clang::dataflow::UncheckedOptionalAccessModel::initialElement () inline static
Definition at line 53 of file UncheckedOptionalAccessModel.h.
merge()
bool clang::dataflow::UncheckedOptionalAccessModel::merge (QualType Type, const Value & Val1, const Environment & Env1, const Value & Val2, const Environment & Env2, Value & MergedVal, Environment & MergedEnv) override virtual
Modifies MergedVal to approximate both Val1 and Val2.
This could be a strict lattice join or a more general widening operation.
If this function returns true, MergedVal will be assigned to a storage location of type Type in MergedEnv.
Env1 and Env2 can be used to query child values and path condition implications of Val1 and Val2 respectively.
Requirements:
Val1 and Val2 must be distinct.
Val1, Val2, and MergedVal must model values of type Type.
Val1 and Val2 must be assigned to the same storage location in Env1 and Env2 respectively.
Reimplemented from clang::dataflow::Environment::ValueModel.
Definition at line 725 of file UncheckedOptionalAccessModel.cpp.
References clang::dataflow::Environment::addToFlowCondition(), clang::dataflow::Environment::makeAtomicBoolValue(), and clang::dataflow::Environment::makeNot().
optionalClassDecl()
ast_matchers::DeclarationMatcher clang::dataflow::UncheckedOptionalAccessModel::optionalClassDecl () static
Returns a matcher for the optional classes covered by this model.
Definition at line 702 of file UncheckedOptionalAccessModel.cpp.
transfer()
void clang::dataflow::UncheckedOptionalAccessModel::transfer (const Stmt * Stmt, NoopLattice & State, Environment & Env)
Definition at line 711 of file UncheckedOptionalAccessModel.cpp.
References clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, NoopLattice >::getASTContext().
The documentation for this class was generated from the following files:
include/clang/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.h
lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp