clang: clang::CodeGen::CGBuilderTy Class Reference
clang::CodeGen::CGBuilderTy Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/CGBuilder.h"
Public Member Functions
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::LLVMContext &C)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::LLVMContext &C, const llvm::ConstantFolder &F, const CGBuilderInserterTy &Inserter)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::Instruction *I)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::BasicBlock *BB)
llvm::ConstantInt * getSize (CharUnits N)
llvm::ConstantInt * getSize (uint64_t N)
llvm::LoadInst * CreateLoad (Address Addr, const llvm::Twine &Name="")
llvm::LoadInst * CreateLoad (Address Addr, const char *Name)
llvm::LoadInst * CreateLoad (Address Addr, bool IsVolatile, const llvm::Twine &Name="")
llvm::LoadInst * CreateAlignedLoad (llvm::Type *Ty, llvm::Value *Addr, CharUnits Align, const llvm::Twine &Name="")
llvm::StoreInst * CreateStore (llvm::Value *Val, Address Addr, bool IsVolatile=false)
llvm::StoreInst * CreateAlignedStore (llvm::Value *Val, llvm::Value *Addr, CharUnits Align, bool IsVolatile=false)
llvm::StoreInst * CreateDefaultAlignedStore (llvm::Value *Val, llvm::Value *Addr, bool IsVolatile=false)
llvm::LoadInst * CreateFlagLoad (llvm::Value *Addr, const llvm::Twine &Name="")
Emit a load from an i1 flag variable.
llvm::StoreInst * CreateFlagStore (bool Value, llvm::Value *Addr)
Emit a store to an i1 flag variable.
llvm::AtomicCmpXchgInst * CreateAtomicCmpXchg (llvm::Value *Ptr, llvm::Value *Cmp, llvm::Value *New, llvm::AtomicOrdering SuccessOrdering, llvm::AtomicOrdering FailureOrdering, llvm::SyncScope::ID SSID=llvm::SyncScope::System)
llvm::AtomicRMWInst * CreateAtomicRMW (llvm::AtomicRMWInst::BinOp Op, llvm::Value *Ptr, llvm::Value *Val, llvm::AtomicOrdering Ordering, llvm::SyncScope::ID SSID=llvm::SyncScope::System)
Address CreateAddrSpaceCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Address CreateElementBitCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Cast the element type of the given address to a different type, preserving information like the alignment and address space.
Address CreatePointerBitCastOrAddrSpaceCast (Address Addr, llvm::Type *Ty, llvm::Type *ElementTy, const llvm::Twine &Name="")
Address CreateStructGEP (Address Addr, unsigned Index, const llvm::Twine &Name="")
Address CreateConstArrayGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = [n x T]* ... produce name = getelementptr inbounds addr, i64 0, i64 index where i64 is actually the target word size.
Address CreateConstInBoundsGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = T* ... produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Address CreateConstGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = T* ... produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Address CreateGEP (Address Addr, llvm::Value *Index, const llvm::Twine &Name="")
Address CreateConstInBoundsByteGEP (Address Addr, CharUnits Offset, const llvm::Twine &Name="")
Given a pointer to i8, adjust it by a given constant offset.
Address CreateConstByteGEP (Address Addr, CharUnits Offset, const llvm::Twine &Name="")
Address CreateConstInBoundsGEP2_32 (Address Addr, unsigned Idx0, unsigned Idx1, const llvm::Twine &Name="")
llvm::CallInst * CreateMemCpy (Address Dest, Address Src, llvm::Value *Size, bool IsVolatile=false)
llvm::CallInst * CreateMemCpy (Address Dest, Address Src, uint64_t Size, bool IsVolatile=false)
llvm::CallInst * CreateMemCpyInline (Address Dest, Address Src, uint64_t Size)
llvm::CallInst * CreateMemMove (Address Dest, Address Src, llvm::Value *Size, bool IsVolatile=false)
llvm::CallInst * CreateMemSet (Address Dest, llvm::Value *Value, llvm::Value *Size, bool IsVolatile=false)
llvm::CallInst * CreateMemSetInline (Address Dest, llvm::Value *Value, uint64_t Size)
Address CreatePreserveStructAccessIndex (Address Addr, unsigned Index, unsigned FieldIndex, llvm::MDNode *DbgInfo)
Address CreateLaunderInvariantGroup (Address Addr)
Detailed Description
Definition at line 45 of file CGBuilder.h.
Constructor & Destructor Documentation
CGBuilderTy() [1/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::LLVMContext & C) inline
Definition at line 51 of file CGBuilder.h.
CGBuilderTy() [2/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::LLVMContext & C, const llvm::ConstantFolder & F, const CGBuilderInserterTy & Inserter) inline
Definition at line 53 of file CGBuilder.h.
CGBuilderTy() [3/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::Instruction * I) inline
Definition at line 57 of file CGBuilder.h.
CGBuilderTy() [4/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::BasicBlock * BB) inline
Definition at line 59 of file CGBuilder.h.
Member Function Documentation
CreateAddrSpaceCast()
Address clang::CodeGen::CGBuilderTy::CreateAddrSpaceCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Definition at line 158 of file CGBuilder.h.
References CreateAddrSpaceCast(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and clang::CodeGen::Address::withPointer().
Referenced by CreateAddrSpaceCast().
CreateAlignedLoad()
llvm::LoadInst * clang::CodeGen::CGBuilderTy::CreateAlignedLoad (llvm::Type * Ty, llvm::Value * Addr, CharUnits Align, const llvm::Twine & Name = "") inline
Definition at line 89 of file CGBuilder.h.
References CreateAlignedLoad(), and clang::CharUnits::getAsAlign().
Referenced by BuildAppleKextVirtualCall(), CreateAlignedLoad(), CreateFlagLoad(), CreateLoad(), CreateLoad(), CreateLoad(), createPlaceholderSlot(), EmitISOVolatileLoad(), performTypeAdjustment(), and clang::CodeGen::DominatingLLVMValue::restore().
CreateAlignedStore()
llvm::StoreInst * clang::CodeGen::CGBuilderTy::CreateAlignedStore (llvm::Value * Val, llvm::Value * Addr, CharUnits Align, bool IsVolatile = false) inline
Definition at line 106 of file CGBuilder.h.
References CreateAlignedStore(), and clang::CharUnits::getAsAlign().
Referenced by CreateAlignedStore(), CreateFlagStore(), CreateStore(), EmitISOVolatileStore(), and clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
CreateAtomicCmpXchg()
llvm::AtomicCmpXchgInst * clang::CodeGen::CGBuilderTy::CreateAtomicCmpXchg (llvm::Value * Ptr, llvm::Value * Cmp, llvm::Value * New, llvm::AtomicOrdering SuccessOrdering, llvm::AtomicOrdering FailureOrdering, llvm::SyncScope::ID SSID = llvm::SyncScope::System) inline
Definition at line 138 of file CGBuilder.h.
Referenced by emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicCmpXchgForMSIntrin(), and MakeAtomicCmpXchgValue().
CreateAtomicRMW()
llvm::AtomicRMWInst * clang::CodeGen::CGBuilderTy::CreateAtomicRMW (llvm::AtomicRMWInst::BinOp Op, llvm::Value * Ptr, llvm::Value * Val, llvm::AtomicOrdering Ordering, llvm::SyncScope::ID SSID = llvm::SyncScope::System) inline
Definition at line 150 of file CGBuilder.h.
Referenced by EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), EmitAtomicOp(), EmitBinaryAtomicPost(), EmitBitTestIntrinsic(), emitOMPAtomicRMW(), and MakeBinaryAtomicValue().
CreateConstArrayGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstArrayGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = [n x T]* ... produce name = getelementptr inbounds addr, i64 0, i64 index where i64 is actually the target word size.
This API assumes that drilling into an array like this is always an inbounds operation.
Definition at line 213 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::cast(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::getPointer().
Referenced by emitAddrOfVarFromArray(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossOrdered(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitNonContiguousDescriptor(), emitOffloadingArrays(), emitOMPArraySectionBase(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), and clang::CodeGen::CGOpenMPRuntime::emitSingleRegion().
CreateConstByteGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstByteGEP (Address Addr, CharUnits Offset, const llvm::Twine & Name = "") inline
Definition at line 285 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), CreateGEP(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), getSize(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and Offset.
CreateConstGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = T* ... produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Definition at line 249 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), CreateGEP(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and getSize().
Referenced by emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), and shuffleAndStore().
CreateConstInBoundsByteGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP (Address Addr, CharUnits Offset, const llvm::Twine & Name = "") inline
Given a pointer to i8, adjust it by a given constant offset.
Definition at line 277 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), getSize(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and Offset.
Referenced by complexTempStructure(), emitAddressAtOffset(), emitAddrOfZeroSizeField(), EmitNullBaseClassInitialization(), emitVoidPtrDirectVAArg(), performTypeAdjustment(), and clang::CodeGen::CGCXXABI::ReadArrayCookie().
CreateConstInBoundsGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = T* ... produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Definition at line 232 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and getSize().
CreateConstInBoundsGEP2_32()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32 (Address Addr, unsigned Idx0, unsigned Idx1, const llvm::Twine & Name = "") inline
Definition at line 295 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::cast(), CreateConstInBoundsGEP2_32(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::CodeGen::Address::getType(), and Offset.
Referenced by CreateConstInBoundsGEP2_32(), emitNonContiguousDescriptor(), emitOffloadingArrays(), and emitOffloadingArraysArgument().
CreateDefaultAlignedStore()
llvm::StoreInst * clang::CodeGen::CGBuilderTy::CreateDefaultAlignedStore (llvm::Value * Val, llvm::Value * Addr, bool IsVolatile = false) inline
Definition at line 114 of file CGBuilder.h.
CreateElementBitCast()
Address clang::CodeGen::CGBuilderTy::CreateElementBitCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Cast the element type of the given address to a different type, preserving information like the alignment and address space.
Definition at line 168 of file CGBuilder.h.
References clang::CodeGen::Address::getAddressSpace(), clang::CodeGen::Address::getAlignment(), and clang::CodeGen::Address::getPointer().
Referenced by callSpecialFunction(), CheckAggExprForMemSetUse(), complexTempStructure(), CreateCoercedLoad(), CreateCoercedStore(), emitAddressAtOffset(), emitAddrOfZeroSizeField(), emitARCLoadOperation(), clang::CodeGen::ReductionCodeGen::emitCleanups(), emitInterWarpCopyFunction(), EmitNullBaseClassInitialization(), EmitOMPAggregateInit(), emitOMPArraySectionBase(), emitReduceCombFunction(), emitReduceInitFunction(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), emitVoidPtrDirectVAArg(), generateByrefCopyHelper(), generateByrefDisposeHelper(), loadToBegin(), MaybeConvertMatrixAddress(), performTypeAdjustment(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), and tryEmitARCCopyWeakInit().
CreateFlagLoad()
llvm::LoadInst * clang::CodeGen::CGBuilderTy::CreateFlagLoad (llvm::Value * Addr, const llvm::Twine & Name = "") inline
Emit a load from an i1 flag variable.
Definition at line 121 of file CGBuilder.h.
References CreateAlignedLoad(), and clang::CharUnits::One().
CreateFlagStore()
llvm::StoreInst * clang::CodeGen::CGBuilderTy::CreateFlagStore (bool Value, llvm::Value * Addr) inline
Emit a store to an i1 flag variable.
Definition at line 129 of file CGBuilder.h.
References CreateAlignedStore(), and clang::CharUnits::One().
Referenced by clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), and clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
CreateGEP()
Address clang::CodeGen::CGBuilderTy::CreateGEP (Address Addr, llvm::Value * Index, const llvm::Twine & Name = "") inline
Definition at line 264 of file CGBuilder.h.
References clang::CharUnits::alignmentOfArrayElement(), CreateGEP(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::getPointer().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), CreateConstByteGEP(), CreateConstGEP(), CreateGEP(), emitArraySubscriptGEP(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), emitInterWarpCopyFunction(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitPointerArithmetic(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper(), and EmitX86_64VAArgFromMemory().
CreateLaunderInvariantGroup()
Address clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup (Address Addr) inline
Definition at line 371 of file CGBuilder.h.
References CreateLaunderInvariantGroup(), clang::CodeGen::Address::getPointer(), and clang::CodeGen::Address::withPointer().
Referenced by CreateLaunderInvariantGroup().
CreateLoad() [1/3]
llvm::LoadInst * clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, bool IsVolatile, const llvm::Twine & Name = "") inline
Definition at line 81 of file CGBuilder.h.
References CreateAlignedLoad(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::getPointer().
CreateLoad() [2/3]
llvm::LoadInst * clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, const char * Name) inline
Definition at line 75 of file CGBuilder.h.
References CreateAlignedLoad(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::getPointer().
CreateLoad() [3/3]
llvm::LoadInst * clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, const llvm::Twine & Name = "") inline
Definition at line 71 of file CGBuilder.h.
References CreateAlignedLoad(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::getPointer().
Referenced by complexTempStructure(), CreateCoercedLoad(), emitAddrOfVarFromArray(), emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicOp(), EmitBitTestIntrinsic(), EmitCleanup(), emitCopyprivateCopyFunction(), emitDistributeParallelForDistributeInnerBoundParams(), EmitMemberInitializer(), emitOMPArraySectionBase(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), emitTlsGuardCheck(), emitVoidPtrDirectVAArg(), emitVoidPtrVAArg(), emitWriteback(), EmitX86_64VAArgFromMemory(), generateByrefCopyHelper(), generateByrefDisposeHelper(), clang::CodeGen::CGCXXABI::loadIncomingCXXThis(), and performTypeAdjustment().
CreateMemCpy() [1/2]
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemCpy (Address Dest, Address Src, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 312 of file CGBuilder.h.
References CreateMemCpy(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CreateCoercedLoad(), CreateCoercedStore(), CreateMemCpy(), CreateMemCpy(), EmitNullBaseClassInitialization(), and emitOffloadingArrays().
CreateMemCpy() [2/2]
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemCpy (Address Dest, Address Src, uint64_t Size, bool IsVolatile = false) inline
Definition at line 318 of file CGBuilder.h.
References CreateMemCpy(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
CreateMemCpyInline()
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemCpyInline (Address Dest, Address Src, uint64_t Size) inline
Definition at line 326 of file CGBuilder.h.
References CreateMemCpyInline(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CreateMemCpyInline().
CreateMemMove()
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemMove (Address Dest, Address Src, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 333 of file CGBuilder.h.
References CreateMemMove(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CreateMemMove().
CreateMemSet()
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemSet (Address Dest, llvm::Value * Value, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 341 of file CGBuilder.h.
References CreateMemSet(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CheckAggExprForMemSetUse(), CreateMemSet(), EmitNullBaseClassInitialization(), and initializeAlloca().
CreateMemSetInline()
llvm::CallInst * clang::CodeGen::CGBuilderTy::CreateMemSetInline (Address Dest, llvm::Value * Value, uint64_t Size) inline
Definition at line 348 of file CGBuilder.h.
References CreateMemSetInline(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CreateMemSetInline().
CreatePointerBitCastOrAddrSpaceCast()
Address clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast (Address Addr, llvm::Type * Ty, llvm::Type * ElementTy, const llvm::Twine & Name = "") inline
Definition at line 176 of file CGBuilder.h.
References CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::Address::getAlignment(), and clang::CodeGen::Address::getPointer().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), castToBase(), castValueToType(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), CreateCoercedStore(), CreatePointerBitCastOrAddrSpaceCast(), emitCopyprivateCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitNonContiguousDescriptor(), emitOffloadingArrays(), clang::CodeGen::CGOpenMPRuntimeGPU::emitOutlinedFunctionCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), emitPrivatesInit(), emitProxyTaskFunction(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitUsesAllocatorsInit(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), and shuffleAndStore().
CreatePreserveStructAccessIndex()
Address clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex (Address Addr, unsigned Index, unsigned FieldIndex, llvm::MDNode * DbgInfo) inline
Definition at line 356 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::cast(), CreatePreserveStructAccessIndex(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and Offset.
Referenced by CreatePreserveStructAccessIndex(), and emitPreserveStructAccess().
CreateStore()
llvm::StoreInst * clang::CodeGen::CGBuilderTy::CreateStore (llvm::Value * Val, Address Addr, bool IsVolatile = false) inline
Definition at line 99 of file CGBuilder.h.
References CreateAlignedStore(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by castToBase(), CreateCoercedStore(), emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicOp(), EmitBitTestIntrinsic(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), emitGlobalToListReduceFunction(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), emitListToGlobalReduceFunction(), emitNonContiguousDescriptor(), emitOffloadingArrays(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), EmitSystemZIntrinsicWithCC(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), emitVoidPtrDirectVAArg(), emitWasmCatchPadBlock(), emitWritebackArg(), EmitX86_64VAArgFromMemory(), InitCatchParam(), clang::CodeGen::DominatingLLVMValue::save(), SetupCleanupBlockActivation(), and clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr().
CreateStructGEP()
Address clang::CodeGen::CGBuilderTy::CreateStructGEP (Address Addr, unsigned Index, const llvm::Twine & Name = "") inline
Definition at line 192 of file CGBuilder.h.
References clang::CharUnits::alignmentAtOffset(), clang::cast(), CreateStructGEP(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and Offset.
Referenced by CreateStructGEP(), emitAddrOfFieldStorage(), EmitX86_64VAArgFromMemory(), and EnterStructPointerForCoercedAccess().
getSize() [1/2]
llvm::ConstantInt * clang::CodeGen::CGBuilderTy::getSize (CharUnits N) inline
Definition at line 62 of file CGBuilder.h.
References N, and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by CreateConstByteGEP(), CreateConstGEP(), CreateConstInBoundsByteGEP(), and CreateConstInBoundsGEP().
getSize() [2/2]
llvm::ConstantInt * clang::CodeGen::CGBuilderTy::getSize (uint64_t N) inline
Definition at line 65 of file CGBuilder.h.
References N, and clang::CodeGen::CodeGenTypeCache::SizeTy.
The documentation for this class was generated from the following file:
lib/CodeGen/CGBuilder.h