clang: clang::ObjCProtocolQualifiers< T > Class Template Reference
clang::ObjCProtocolQualifiers< T > Class Template Reference
This class wraps the list of protocol qualifiers.
#include "clang/AST/Type.h"
Public Types
using qual_iterator = ObjCProtocolDecl * const *
using qual_range = llvm::iterator_range<qual_iterator>
Public Member Functions
qual_range quals () const
qual_iterator qual_begin () const
qual_iterator qual_end () const
bool qual_empty () const
unsigned getNumProtocols () const
Return the number of qualifying protocols in this type, or 0 if there are none.
ObjCProtocolDecl * getProtocol (unsigned I) const
Fetch a protocol by index.
ArrayRef< ObjCProtocolDecl * > getProtocols () const
Retrieve all of the protocol qualifiers.
Protected Member Functions
ObjCProtocolQualifiers ()=default
ObjCProtocolDecl *const * getProtocolStorage () const
ObjCProtocolDecl ** getProtocolStorage ()
void setNumProtocols (unsigned N)
void initialize (ArrayRef< ObjCProtocolDecl * > protocols)
Detailed Description
template<class T>
class clang::ObjCProtocolQualifiers< T >
This class wraps the list of protocol qualifiers.
For types that can take ObjC protocol qualifers, they can subclass this class.
Definition at line 5821 of file Type.h.
Member Typedef Documentation
qual_iterator
template<class T > using clang::ObjCProtocolQualifiers< T >::qual_iterator = ObjCProtocolDecl * const *
Definition at line 5847 of file Type.h.
qual_range
template<class T > using clang::ObjCProtocolQualifiers< T >::qual_range = llvm::iterator_range<qual_iterator>
Definition at line 5848 of file Type.h.
Constructor & Destructor Documentation
ObjCProtocolQualifiers()
template<class T > clang::ObjCProtocolQualifiers< T >::ObjCProtocolQualifiers () protected default
Member Function Documentation
getNumProtocols()
template<class T > unsigned clang::ObjCProtocolQualifiers< T >::getNumProtocols () const inline
Return the number of qualifying protocols in this type, or 0 if there are none.
Definition at line 5858 of file Type.h.
Referenced by clang::ASTContext::canAssignObjCInterfaces(), clang::ObjCObjectPointerType::getNumProtocols(), clang::ObjCObjectTypeLoc::getNumProtocols(), clang::ObjCTypeParamTypeLoc::getNumProtocols(), clang::ObjCProtocolQualifiers< T >::getProtocol(), clang::ObjCProtocolQualifiers< T >::getProtocols(), clang::ObjCProtocolQualifiers< T >::initialize(), clang::ObjCProtocolQualifiers< T >::qual_empty(), and clang::ObjCProtocolQualifiers< T >::qual_end().
getProtocol()
template<class T > ObjCProtocolDecl * clang::ObjCProtocolQualifiers< T >::getProtocol (unsigned I) const inline
Fetch a protocol by index.
Definition at line 5863 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
Referenced by clang::ObjCObjectPointerType::getProtocol().
getProtocols()
template<class T > ArrayRef< ObjCProtocolDecl * > clang::ObjCProtocolQualifiers< T >::getProtocols () const inline
Retrieve all of the protocol qualifiers.
Definition at line 5869 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
getProtocolStorage() [1/2]
template<class T > ObjCProtocolDecl ** clang::ObjCProtocolQualifiers< T >::getProtocolStorage () inline protected
Definition at line 5829 of file Type.h.
getProtocolStorage() [2/2]
template<class T > ObjCProtocolDecl *const * clang::ObjCProtocolQualifiers< T >::getProtocolStorage () const inline protected
Definition at line 5825 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getProtocolStorage().
Referenced by clang::ObjCProtocolQualifiers< T >::getProtocolStorage(), clang::ObjCProtocolQualifiers< T >::initialize(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
initialize()
template<class T > void clang::ObjCProtocolQualifiers< T >::initialize (ArrayRef< ObjCProtocolDecl * > protocols) inline protected
Definition at line 5837 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), clang::ObjCProtocolQualifiers< T >::getProtocolStorage(), memcpy(), and clang::ObjCProtocolQualifiers< T >::setNumProtocols().
qual_begin()
template<class T > qual_iterator clang::ObjCProtocolQualifiers< T >::qual_begin () const inline
Definition at line 5851 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getProtocolStorage().
Referenced by clang::ASTContext::applyObjCProtocolQualifiers(), clang::ObjCObjectTypeLoc::getProtocol(), clang::ObjCProtocolQualifiers< T >::getProtocol(), clang::ObjCTypeParamTypeLoc::getProtocol(), clang::ObjCProtocolQualifiers< T >::getProtocols(), clang::ObjCObjectPointerType::qual_begin(), clang::ObjCProtocolQualifiers< T >::qual_end(), and clang::ObjCProtocolQualifiers< T >::quals().
qual_empty()
template<class T > bool clang::ObjCProtocolQualifiers< T >::qual_empty () const inline
Definition at line 5854 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols().
Referenced by clang::Sema::CheckObjCForCollectionOperand(), and clang::ObjCObjectPointerType::qual_empty().
qual_end()
template<class T > qual_iterator clang::ObjCProtocolQualifiers< T >::qual_end () const inline
Definition at line 5852 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
Referenced by clang::ASTContext::applyObjCProtocolQualifiers(), clang::ObjCObjectPointerType::qual_end(), and clang::ObjCProtocolQualifiers< T >::quals().
quals()
template<class T > qual_range clang::ObjCProtocolQualifiers< T >::quals () const inline
Definition at line 5850 of file Type.h.
References clang::ObjCProtocolQualifiers< T >::qual_begin(), and clang::ObjCProtocolQualifiers< T >::qual_end().
Referenced by clang::ASTContext::canAssignObjCInterfaces(), getIntersectionOfProtocols(), and clang::Sema::LookupMethodInObjectType().
setNumProtocols()
template<class T > void clang::ObjCProtocolQualifiers< T >::setNumProtocols (unsigned N) inline protected
Definition at line 5833 of file Type.h.
References N.
Referenced by clang::ObjCProtocolQualifiers< T >::initialize().
The documentation for this class was generated from the following file:
include/clang/AST/Type.h