clang: clang::Sema::DelayedDiagnostics Class Reference
clang::Sema::DelayedDiagnostics Class Reference
A class which encapsulates the logic for delaying diagnostics during parsing and other processing.
#include "clang/Sema/Sema.h"
Public Member Functions
DelayedDiagnostics ()
void add (const sema::DelayedDiagnostic &diag)
Adds a delayed diagnostic.
bool shouldDelayDiagnostics ()
Determines whether diagnostics should be delayed.
sema::DelayedDiagnosticPool * getCurrentPool () const
Returns the current delayed-diagnostics pool.
DelayedDiagnosticsState push (sema::DelayedDiagnosticPool &pool)
Enter a new scope.
void popWithoutEmitting (DelayedDiagnosticsState state)
Leave a delayed-diagnostic state that was previously pushed.
DelayedDiagnosticsState pushUndelayed ()
Enter a new scope where access and deprecation diagnostics are not delayed.
void popUndelayed (DelayedDiagnosticsState state)
Undo a previous pushUndelayed().
Detailed Description
A class which encapsulates the logic for delaying diagnostics during parsing and other processing.
Definition at line 939 of file Sema.h.
Constructor & Destructor Documentation
DelayedDiagnostics()
clang::Sema::DelayedDiagnostics::DelayedDiagnostics () inline
Definition at line 945 of file Sema.h.
Member Function Documentation
add()
void clang::Sema::DelayedDiagnostics::add (const sema::DelayedDiagnostic & diag) inline
Adds a delayed diagnostic.
Add a diagnostic to the current delay pool.
Definition at line 325 of file DelayedDiagnostic.h.
References clang::sema::DelayedDiagnosticPool::add(), and shouldDelayDiagnostics().
Referenced by CheckAccess(), clang::Sema::CheckParameter(), EmitAvailabilityWarning(), handleObjCOwnershipTypeAttr(), and inferARCLifetimeForPointee().
getCurrentPool()
sema::DelayedDiagnosticPool * clang::Sema::DelayedDiagnostics::getCurrentPool () const inline
Returns the current delayed-diagnostics pool.
Definition at line 954 of file Sema.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::PopParsingDeclaration(), and clang::Sema::redelayDiagnostics().
popUndelayed()
void clang::Sema::DelayedDiagnostics::popUndelayed (DelayedDiagnosticsState state) inline
Undo a previous pushUndelayed().
Definition at line 984 of file Sema.h.
Referenced by clang::Sema::PopParsingClass().
popWithoutEmitting()
void clang::Sema::DelayedDiagnostics::popWithoutEmitting (DelayedDiagnosticsState state) inline
Leave a delayed-diagnostic state that was previously pushed.
Do not emit any of the diagnostics. This is performed as part of the bookkeeping of popping a pool "properly".
Definition at line 970 of file Sema.h.
Referenced by clang::Sema::PopParsingDeclaration().
push()
DelayedDiagnosticsState clang::Sema::DelayedDiagnostics::push (sema::DelayedDiagnosticPool & pool) inline
Enter a new scope.
Access and deprecation diagnostics will be collected in this pool.
Definition at line 960 of file Sema.h.
Referenced by clang::Sema::PushParsingDeclaration().
pushUndelayed()
DelayedDiagnosticsState clang::Sema::DelayedDiagnostics::pushUndelayed () inline
Enter a new scope where access and deprecation diagnostics are not delayed.
Definition at line 976 of file Sema.h.
Referenced by clang::Sema::PushParsingClass().
shouldDelayDiagnostics()
bool clang::Sema::DelayedDiagnostics::shouldDelayDiagnostics () inline
Determines whether diagnostics should be delayed.
Definition at line 951 of file Sema.h.
Referenced by add(), CheckAccess(), clang::Sema::CheckParameter(), EmitAvailabilityWarning(), handleObjCOwnershipTypeAttr(), and inferARCLifetimeForPointee().
The documentation for this class was generated from the following files:
include/clang/Sema/Sema.h
include/clang/Sema/DelayedDiagnostic.h