clang: clang::QualifiersAndAtomic Class Reference
clang::QualifiersAndAtomic Class Reference
#include "clang/AST/Type.h"
Public Member Functions
QualifiersAndAtomic ()
QualifiersAndAtomic (Qualifiers Quals, bool HasAtomic)
operator Qualifiers () const
bool hasVolatile () const
bool hasConst () const
bool hasRestrict () const
bool hasAtomic () const
void addVolatile ()
void addConst ()
void addRestrict ()
void addAtomic ()
void removeVolatile ()
void removeConst ()
void removeRestrict ()
void removeAtomic ()
QualifiersAndAtomic withVolatile ()
QualifiersAndAtomic withConst ()
QualifiersAndAtomic withRestrict ()
QualifiersAndAtomic withAtomic ()
QualifiersAndAtomic & operator+= (Qualifiers RHS)
Detailed Description
Definition at line 627 of file Type.h.
Constructor & Destructor Documentation
QualifiersAndAtomic() [1/2]
clang::QualifiersAndAtomic::QualifiersAndAtomic () inline
Definition at line 632 of file Type.h.
QualifiersAndAtomic() [2/2]
clang::QualifiersAndAtomic::QualifiersAndAtomic (Qualifiers Quals, bool HasAtomic) inline
Definition at line 633 of file Type.h.
Member Function Documentation
addAtomic()
void clang::QualifiersAndAtomic::addAtomic () inline
Definition at line 646 of file Type.h.
Referenced by clang::Sema::AddBuiltinOperatorCandidates().
addConst()
void clang::QualifiersAndAtomic::addConst () inline
Definition at line 644 of file Type.h.
References clang::Qualifiers::addConst().
Referenced by clang::Sema::AddBuiltinOperatorCandidates().
addRestrict()
void clang::QualifiersAndAtomic::addRestrict () inline
Definition at line 645 of file Type.h.
References clang::Qualifiers::addRestrict().
addVolatile()
void clang::QualifiersAndAtomic::addVolatile () inline
Definition at line 643 of file Type.h.
References clang::Qualifiers::addVolatile().
hasAtomic()
bool clang::QualifiersAndAtomic::hasAtomic () const inline
Definition at line 641 of file Type.h.
Referenced by makeQualifiedLValueReferenceType().
hasConst()
bool clang::QualifiersAndAtomic::hasConst () const inline
Definition at line 639 of file Type.h.
References clang::Qualifiers::hasConst().
hasRestrict()
bool clang::QualifiersAndAtomic::hasRestrict () const inline
Definition at line 640 of file Type.h.
References clang::Qualifiers::hasRestrict().
hasVolatile()
bool clang::QualifiersAndAtomic::hasVolatile () const inline
Definition at line 638 of file Type.h.
References clang::Qualifiers::hasVolatile().
Referenced by forAllQualifierCombinationsImpl(), and makeQualifiedLValueReferenceType().
operator Qualifiers()
clang::QualifiersAndAtomic::operator Qualifiers () const inline
Definition at line 636 of file Type.h.
operator+=()
QualifiersAndAtomic & clang::QualifiersAndAtomic::operator+= (Qualifiers RHS) inline
Definition at line 662 of file Type.h.
removeAtomic()
void clang::QualifiersAndAtomic::removeAtomic () inline
Definition at line 651 of file Type.h.
removeConst()
void clang::QualifiersAndAtomic::removeConst () inline
Definition at line 649 of file Type.h.
References clang::Qualifiers::removeConst().
removeRestrict()
void clang::QualifiersAndAtomic::removeRestrict () inline
Definition at line 650 of file Type.h.
References clang::Qualifiers::removeRestrict().
removeVolatile()
void clang::QualifiersAndAtomic::removeVolatile () inline
Definition at line 648 of file Type.h.
References clang::Qualifiers::removeVolatile().
withAtomic()
QualifiersAndAtomic clang::QualifiersAndAtomic::withAtomic () inline
Definition at line 660 of file Type.h.
Referenced by forAllQualifierCombinationsImpl().
withConst()
QualifiersAndAtomic clang::QualifiersAndAtomic::withConst () inline
Definition at line 656 of file Type.h.
References clang::Qualifiers::withConst().
withRestrict()
QualifiersAndAtomic clang::QualifiersAndAtomic::withRestrict () inline
Definition at line 657 of file Type.h.
References clang::Qualifiers::withRestrict().
withVolatile()
QualifiersAndAtomic clang::QualifiersAndAtomic::withVolatile () inline
Definition at line 653 of file Type.h.
References clang::Qualifiers::withVolatile().
Referenced by forAllQualifierCombinationsImpl().
The documentation for this class was generated from the following file:
include/clang/AST/Type.h