clang: clang::concepts::Requirement Class Reference
clang::concepts::Requirement Class Reference
A static requirement that can be used in a requires-expression to check properties of types and expression.
#include "clang/AST/ExprConcepts.h"
Classes
struct SubstitutionDiagnostic
Public Types
enum RequirementKind { RK_Type , RK_Simple , RK_Compound , RK_Nested }
Public Member Functions
Requirement (RequirementKind Kind, bool IsDependent, bool ContainsUnexpandedParameterPack, bool IsSatisfied=true)
RequirementKind getKind () const
bool isSatisfied () const
void setSatisfied (bool IsSatisfied)
void setDependent (bool IsDependent)
bool isDependent () const
void setContainsUnexpandedParameterPack (bool Contains)
bool containsUnexpandedParameterPack () const
Detailed Description
A static requirement that can be used in a requires-expression to check properties of types and expression.
Definition at line 151 of file ExprConcepts.h.
Member Enumeration Documentation
RequirementKind
enum clang::concepts::Requirement::RequirementKind
Enumerator
RK_Type
RK_Simple
RK_Compound
RK_Nested
Definition at line 155 of file ExprConcepts.h.
Constructor & Destructor Documentation
Requirement()
clang::concepts::Requirement::Requirement (RequirementKind Kind, bool IsDependent, bool ContainsUnexpandedParameterPack, bool IsSatisfied = true) inline
Definition at line 172 of file ExprConcepts.h.
Member Function Documentation
containsUnexpandedParameterPack()
bool clang::concepts::Requirement::containsUnexpandedParameterPack () const inline
Definition at line 198 of file ExprConcepts.h.
Referenced by clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
getKind()
RequirementKind clang::concepts::Requirement::getKind () const inline
Definition at line 178 of file ExprConcepts.h.
Referenced by clang::concepts::ExprRequirement::classof(), clang::concepts::NestedRequirement::classof(), clang::concepts::TypeRequirement::classof(), clang::concepts::ExprRequirement::isCompound(), clang::concepts::ExprRequirement::isSimple(), clang::RecursiveASTVisitor< Derived >::TraverseConceptRequirement(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
isDependent()
bool clang::concepts::Requirement::isDependent () const inline
Definition at line 193 of file ExprConcepts.h.
Referenced by clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
isSatisfied()
bool clang::concepts::Requirement::isSatisfied () const inline
Definition at line 180 of file ExprConcepts.h.
Referenced by diagnoseUnsatisfiedRequirement(), diagnoseUnsatisfiedRequirement(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
setContainsUnexpandedParameterPack()
void clang::concepts::Requirement::setContainsUnexpandedParameterPack (bool Contains) inline
Definition at line 195 of file ExprConcepts.h.
setDependent()
void clang::concepts::Requirement::setDependent (bool IsDependent) inline
Definition at line 192 of file ExprConcepts.h.
setSatisfied()
void clang::concepts::Requirement::setSatisfied (bool IsSatisfied) inline
Definition at line 186 of file ExprConcepts.h.
The documentation for this class was generated from the following file:
include/clang/AST/ExprConcepts.h