clang: clang::format::Environment Class Reference
clang::format::Environment Class Reference
#include "/root/llvm-project/clang/lib/Format/TokenAnalyzer.h"
Public Member Functions
Environment (StringRef Code, StringRef FileName, unsigned FirstStartColumn=0, unsigned NextStartColumn=0, unsigned LastStartColumn=0)
FileID getFileID () const
const SourceManager & getSourceManager () const
ArrayRef< CharSourceRange > getCharRanges () const
unsigned getFirstStartColumn () const
unsigned getNextStartColumn () const
unsigned getLastStartColumn () const
Static Public Member Functions
static std::unique_ptr< Environment > make (StringRef Code, StringRef FileName, ArrayRef< tooling::Range > Ranges, unsigned FirstStartColumn=0, unsigned NextStartColumn=0, unsigned LastStartColumn=0)
Detailed Description
Definition at line 37 of file TokenAnalyzer.h.
Constructor & Destructor Documentation
Environment()
clang::format::Environment::Environment (StringRef Code, StringRef FileName, unsigned FirstStartColumn = 0, unsigned NextStartColumn = 0, unsigned LastStartColumn = 0)
Definition at line 79 of file TokenAnalyzer.cpp.
Member Function Documentation
getCharRanges()
ArrayRef< CharSourceRange > clang::format::Environment::getCharRanges () const inline
Definition at line 51 of file TokenAnalyzer.h.
getFileID()
FileID clang::format::Environment::getFileID () const inline
Definition at line 47 of file TokenAnalyzer.h.
Referenced by clang::format::TokenAnalyzer::process().
getFirstStartColumn()
unsigned clang::format::Environment::getFirstStartColumn () const inline
Definition at line 55 of file TokenAnalyzer.h.
Referenced by clang::format::TokenAnalyzer::process().
getLastStartColumn()
unsigned clang::format::Environment::getLastStartColumn () const inline
Definition at line 63 of file TokenAnalyzer.h.
getNextStartColumn()
unsigned clang::format::Environment::getNextStartColumn () const inline
Definition at line 59 of file TokenAnalyzer.h.
getSourceManager()
const SourceManager & clang::format::Environment::getSourceManager () const inline
Definition at line 49 of file TokenAnalyzer.h.
Referenced by clang::format::JavaScriptImportSorter::analyze(), clang::format::LeftRightQualifierAlignmentFixer::analyze(), clang::format::NamespaceEndCommentsFixer::analyze(), clang::format::UsingDeclarationsSorter::analyze(), and clang::format::TokenAnalyzer::process().
make()
std::unique_ptr< Environment > clang::format::Environment::make (StringRef Code, StringRef FileName, ArrayRef< tooling::Range > Ranges, unsigned FirstStartColumn = 0, unsigned NextStartColumn = 0, unsigned LastStartColumn = 0) static
Definition at line 59 of file TokenAnalyzer.cpp.
References clang::format::FatalDiagnosticConsumer::fatalError(), clang::CharSourceRange::getCharRange(), and clang::SourceLocation::getLocWithOffset().
Referenced by clang::format::QualifierAlignmentFixer::analyze(), clang::format::cleanup(), clang::format::fixNamespaceEndComments(), clang::format::internal::reformat(), clang::format::separateDefinitionBlocks(), clang::format::sortJavaScriptImports(), and clang::format::sortUsingDeclarations().
The documentation for this class was generated from the following files:
lib/Format/TokenAnalyzer.h
lib/Format/TokenAnalyzer.cpp