clang: clang::GlobalModuleIndex Class Reference
clang::GlobalModuleIndex Class Reference
A global index for a set of module files, providing information about the identifiers within those module files.
#include "clang/Serialization/GlobalModuleIndex.h"
Public Types
typedef llvm::SmallPtrSet< ModuleFile *, 4 > HitSet
A set of module files in which we found a result.
Public Member Functions
~GlobalModuleIndex ()
IdentifierIterator * createIdentifierIterator () const
Returns an iterator for identifiers stored in the index table.
void getKnownModules (llvm::SmallVectorImpl< ModuleFile * > &ModuleFiles)
Retrieve the set of modules that have up-to-date indexes.
void getModuleDependencies (ModuleFile *File, llvm::SmallVectorImpl< ModuleFile * > &Dependencies)
Retrieve the set of module files on which the given module file directly depends.
bool lookupIdentifier (llvm::StringRef Name, HitSet &Hits)
Look for all of the module files with information about the given identifier, e.g., a global function, variable, or type with that name.
bool loadedModuleFile (ModuleFile *File)
Note that the given module file has been loaded.
void printStats ()
Print statistics to standard error.
void dump ()
Print debugging view to standard error.
Static Public Member Functions
static std::pair< GlobalModuleIndex *, llvm::Error > readIndex (llvm::StringRef Path)
Read a global index file for the given directory.
static llvm::Error writeIndex (FileManager &FileMgr, const PCHContainerReader &PCHContainerRdr, llvm::StringRef Path)
Write a global index into the given.
Detailed Description
A global index for a set of module files, providing information about the identifiers within those module files.
The global index is an aid for name lookup into modules, offering a central place where one can look for identifiers determine which module files contain any information about that identifier. This allows the client to restrict the search to only those module files known to have a information about that identifier, improving performance. Moreover, the global module index may know about module files that have not been imported, and can be queried to determine which modules the current translation could or should load to fix a problem.
Definition at line 54 of file GlobalModuleIndex.h.
Member Typedef Documentation
HitSet
llvm::SmallPtrSet<ModuleFile *, 4> clang::GlobalModuleIndex::HitSet
A set of module files in which we found a result.
Definition at line 151 of file GlobalModuleIndex.h.
Constructor & Destructor Documentation
~GlobalModuleIndex()
GlobalModuleIndex::~GlobalModuleIndex ()
Definition at line 248 of file GlobalModuleIndex.cpp.
Member Function Documentation
createIdentifierIterator()
IdentifierIterator * GlobalModuleIndex::createIdentifierIterator () const
Returns an iterator for identifiers stored in the index table.
The caller accepts ownership of the returned object.
Definition at line 945 of file GlobalModuleIndex.cpp.
dump()
LLVM_DUMP_METHOD void GlobalModuleIndex::dump ()
Print debugging view to standard error.
Definition at line 374 of file GlobalModuleIndex.cpp.
getKnownModules()
void GlobalModuleIndex::getKnownModules (llvm::SmallVectorImpl< ModuleFile * > & ModuleFiles)
Retrieve the set of modules that have up-to-date indexes.
Parameters
ModuleFiles Will be populated with the set of module files that have been indexed.
Definition at line 285 of file GlobalModuleIndex.cpp.
References clang::File, and N.
getModuleDependencies()
void GlobalModuleIndex::getModuleDependencies (ModuleFile * File, llvm::SmallVectorImpl< ModuleFile * > & Dependencies)
Retrieve the set of module files on which the given module file directly depends.
Definition at line 293 of file GlobalModuleIndex.cpp.
References clang::File, and N.
loadedModuleFile()
bool GlobalModuleIndex::loadedModuleFile (ModuleFile * File)
Note that the given module file has been loaded.
Returns
false if the global module index has information about this module file, and true otherwise.
Definition at line 337 of file GlobalModuleIndex.cpp.
References clang::File.
Referenced by clang::serialization::ModuleManager::moduleFileAccepted(), and clang::serialization::ModuleManager::setGlobalIndex().
lookupIdentifier()
bool GlobalModuleIndex::lookupIdentifier (llvm::StringRef Name, HitSet & Hits)
Look for all of the module files with information about the given identifier, e.g., a global function, variable, or type with that name.
Parameters
Name The identifier to look for.
Hits Will be populated with the set of module files that have information about this name.
Returns
true if the identifier is known to the index, false otherwise.
Definition at line 311 of file GlobalModuleIndex.cpp.
References clang::File, and N.
Referenced by clang::CompilerInstance::lookupMissingImports().
printStats()
void GlobalModuleIndex::printStats ()
Print statistics to standard error.
Definition at line 364 of file GlobalModuleIndex.cpp.
readIndex()
std::pair< GlobalModuleIndex *, llvm::Error > GlobalModuleIndex::readIndex (llvm::StringRef Path) static
Read a global index file for the given directory.
Parameters
Path The path to the specific module cache where the module files for the intended configuration reside.
Returns
A pair containing the global module index (if it exists) and the error.
The main bitstream cursor for the main block.
Definition at line 253 of file GlobalModuleIndex.cpp.
References clang::C, and IndexFileName.
Referenced by clang::ASTReader::loadGlobalIndex().
writeIndex()
llvm::Error GlobalModuleIndex::writeIndex (FileManager & FileMgr, const PCHContainerReader & PCHContainerRdr, llvm::StringRef Path) static
Write a global index into the given.
Parameters
FileMgr The file manager to use to load module files.
PCHContainerRdr - The PCHContainerOperations to use for loading and creating modules.
Path The path to the directory containing module files, into which the global index will be written.
Definition at line 852 of file GlobalModuleIndex.cpp.
References clang::FileManager::getFile(), and IndexFileName.
Referenced by clang::FrontendAction::Execute(), and clang::CompilerInstance::loadGlobalModuleIndex().
The documentation for this class was generated from the following files:
include/clang/Serialization/GlobalModuleIndex.h
lib/Serialization/GlobalModuleIndex.cpp