clang: clang::BodyFarm Class Reference
clang::BodyFarm Class Reference
#include "clang/Analysis/BodyFarm.h"
Public Member Functions
BodyFarm (ASTContext &C, CodeInjector *injector)
Stmt * getBody (const FunctionDecl *D)
Factory method for creating bodies for ordinary functions.
Stmt * getBody (const ObjCMethodDecl *D)
Factory method for creating bodies for Objective-C properties.
BodyFarm (const BodyFarm &other)=delete
Remove copy constructor to avoid accidental copying.
Detailed Description
Definition at line 30 of file BodyFarm.h.
Constructor & Destructor Documentation
BodyFarm() [1/2]
clang::BodyFarm::BodyFarm (ASTContext & C, CodeInjector * injector) inline
Definition at line 32 of file BodyFarm.h.
BodyFarm() [2/2]
clang::BodyFarm::BodyFarm (const BodyFarm & other) delete
Remove copy constructor to avoid accidental copying.
Member Function Documentation
getBody() [1/2]
Stmt * BodyFarm::getBody (const FunctionDecl * D)
Factory method for creating bodies for ordinary functions.
Definition at line 699 of file BodyFarm.cpp.
References clang::C, create_call_once(), create_dispatch_once(), create_dispatch_sync(), create_OSAtomicCompareAndSwap(), create_std_move_forward(), clang::FunctionDecl::getBuiltinID(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::NamedDecl::getName(), and clang::DeclContext::isStdNamespace().
Referenced by clang::AnalysisDeclContext::getBody().
getBody() [2/2]
Stmt * BodyFarm::getBody (const ObjCMethodDecl * D)
Factory method for creating bodies for Objective-C properties.
Definition at line 863 of file BodyFarm.cpp.
References clang::C, createObjCPropertyGetter(), clang::ObjCMethodDecl::getCanonicalDecl(), clang::ObjCMethodDecl::getClassInterface(), clang::DeclContext::getParent(), clang::ObjCMethodDecl::getSelector(), clang::Decl::isImplicit(), clang::ObjCMethodDecl::isPropertyAccessor(), clang::ObjCInterfaceDecl::known_extensions(), and clang::ObjCMethodDecl::param_size().
The documentation for this class was generated from the following files:
include/clang/Analysis/BodyFarm.h
lib/Analysis/BodyFarm.cpp