clang: clang::CompoundStmt Class Reference
clang::CompoundStmt Class Reference final
CompoundStmt - This represents a group of statements like { stmt stmt }.
#include "clang/AST/Stmt.h"
Public Types
using body_iterator = Stmt **
using body_range = llvm::iterator_range<body_iterator>
using const_body_iterator = Stmt *const *
using body_const_range = llvm::iterator_range<const_body_iterator>
using reverse_body_iterator = std::reverse_iterator<body_iterator>
using const_reverse_body_iterator
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
CompoundStmt (SourceLocation Loc)
bool body_empty () const
unsigned size () const
bool hasStoredFPFeatures () const
FPOptionsOverride getStoredFPFeatures () const
Get FPOptionsOverride from trailing storage.
body_range body ()
body_iterator body_begin ()
body_iterator body_end ()
Stmt * body_front ()
Stmt * body_back ()
body_const_range body () const
const_body_iterator body_begin () const
const_body_iterator body_end () const
const Stmt * body_front () const
const Stmt * body_back () const
reverse_body_iterator body_rbegin ()
reverse_body_iterator body_rend ()
const_reverse_body_iterator body_rbegin () const
const_reverse_body_iterator body_rend () const
Stmt * getStmtExprResult ()
const Stmt * getStmtExprResult () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
SourceLocation getLBracLoc () const
SourceLocation getRBracLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CompoundStmt * Create (const ASTContext &C, ArrayRef< Stmt * > Stmts, FPOptionsOverride FPFeatures, SourceLocation LB, SourceLocation RB)
static CompoundStmt * CreateEmpty (const ASTContext &C, unsigned NumStmts, bool HasFPFeatures)
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
CompoundStmt - This represents a group of statements like { stmt stmt }.
Definition at line 1406 of file Stmt.h.
Member Typedef Documentation
body_const_range
using clang::CompoundStmt::body_const_range = llvm::iterator_range<const_body_iterator>
Definition at line 1474 of file Stmt.h.
body_iterator
using clang::CompoundStmt::body_iterator = Stmt **
Definition at line 1461 of file Stmt.h.
body_range
using clang::CompoundStmt::body_range = llvm::iterator_range<body_iterator>
Definition at line 1462 of file Stmt.h.
const_body_iterator
using clang::CompoundStmt::const_body_iterator = Stmt *const *
Definition at line 1473 of file Stmt.h.
const_reverse_body_iterator
using clang::CompoundStmt::const_reverse_body_iterator
Initial value:
      std::reverse_iterator<const_body_iterator>
Definition at line 1504 of file Stmt.h.
reverse_body_iterator
using clang::CompoundStmt::reverse_body_iterator = std::reverse_iterator<body_iterator>
Definition at line 1494 of file Stmt.h.
Constructor & Destructor Documentation
CompoundStmt()
clang::CompoundStmt::CompoundStmt (SourceLocation Loc) inline explicit
Definition at line 1440 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Member Function Documentation
body() [1/2]
body_range clang::CompoundStmt::body () inline
Definition at line 1464 of file Stmt.h.
References body_begin(), and body_end().
Referenced by CheckConstexprFunctionStmt(), EvaluateStmt(), getStmtExprResult(), isBodyEmpty(), and isCapturedBy().
body() [2/2]
body_const_range clang::CompoundStmt::body () const inline
Definition at line 1476 of file Stmt.h.
References body_begin(), and body_end().
body_back() [1/2]
Stmt * clang::CompoundStmt::body_back () inline
Definition at line 1469 of file Stmt.h.
References body_begin(), body_empty(), and size().
Referenced by getStmtExprResult(), and clang::Expr::isUnusedResultAWarning().
body_back() [2/2]
const Stmt * clang::CompoundStmt::body_back () const inline
Definition at line 1490 of file Stmt.h.
References body_begin(), body_empty(), and size().
body_begin() [1/2]
body_iterator clang::CompoundStmt::body_begin () inline
Definition at line 1465 of file Stmt.h.
Referenced by body(), body(), body_back(), body_back(), body_end(), body_end(), body_front(), body_front(), body_rend(), body_rend(), children(), children(), and isIdenticalStmt().
body_begin() [2/2]
const_body_iterator clang::CompoundStmt::body_begin () const inline
Definition at line 1480 of file Stmt.h.
body_empty()
bool clang::CompoundStmt::body_empty () const inline
Definition at line 1450 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by body_back(), body_back(), body_front(), body_front(), clang::Sema::BuildStmtExpr(), and clang::Expr::isUnusedResultAWarning().
body_end() [1/2]
body_iterator clang::CompoundStmt::body_end () inline
Definition at line 1466 of file Stmt.h.
References body_begin(), and size().
Referenced by body(), body(), body_rbegin(), body_rbegin(), children(), children(), and isIdenticalStmt().
body_end() [2/2]
const_body_iterator clang::CompoundStmt::body_end () const inline
Definition at line 1484 of file Stmt.h.
References body_begin(), and size().
body_front() [1/2]
Stmt * clang::CompoundStmt::body_front () inline
Definition at line 1467 of file Stmt.h.
References body_begin(), and body_empty().
body_front() [2/2]
const Stmt * clang::CompoundStmt::body_front () const inline
Definition at line 1486 of file Stmt.h.
References body_begin(), and body_empty().
body_rbegin() [1/2]
reverse_body_iterator clang::CompoundStmt::body_rbegin () inline
Definition at line 1496 of file Stmt.h.
References body_end().
Referenced by print_elem().
body_rbegin() [2/2]
const_reverse_body_iterator clang::CompoundStmt::body_rbegin () const inline
Definition at line 1507 of file Stmt.h.
References body_end().
body_rend() [1/2]
reverse_body_iterator clang::CompoundStmt::body_rend () inline
Definition at line 1500 of file Stmt.h.
References body_begin().
body_rend() [2/2]
const_reverse_body_iterator clang::CompoundStmt::body_rend () const inline
Definition at line 1511 of file Stmt.h.
References body_begin().
children() [1/2]
child_range clang::CompoundStmt::children () inline
Definition at line 1546 of file Stmt.h.
References body_begin(), and body_end().
children() [2/2]
const_child_range clang::CompoundStmt::children () const inline
Definition at line 1548 of file Stmt.h.
References body_begin(), and body_end().
classof()
static bool clang::CompoundStmt::classof (const Stmt * T) inline static
Definition at line 1541 of file Stmt.h.
Create()
CompoundStmt * CompoundStmt::Create (const ASTContext & C, ArrayRef< Stmt * > Stmts, FPOptionsOverride FPFeatures, SourceLocation LB, SourceLocation RB) static
Definition at line 381 of file Stmt.cpp.
References clang::C, and clang::FPOptionsOverride::requiresTrailingStorage().
Referenced by clang::Sema::ActOnCompoundStmt(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), emitSuspendExpression(), clang::Sema::MaybeCreateStmtWithCleanups(), and clang::ASTNodeImporter::VisitCompoundStmt().
CreateEmpty()
CompoundStmt * CompoundStmt::CreateEmpty (const ASTContext & C, unsigned NumStmts, bool HasFPFeatures) static
Definition at line 391 of file Stmt.cpp.
References clang::C, and clang::Stmt::CompoundStmtBits.
getBeginLoc()
SourceLocation clang::CompoundStmt::getBeginLoc () const inline
Definition at line 1535 of file Stmt.h.
Referenced by clang::Sema::ActOnOpenMPUnrollDirective().
getEndLoc()
SourceLocation clang::CompoundStmt::getEndLoc () const inline
Definition at line 1536 of file Stmt.h.
Referenced by clang::ObjCAtSynchronizedStmt::getEndLoc(), and clang::SEHExceptStmt::getEndLoc().
getLBracLoc()
SourceLocation clang::CompoundStmt::getLBracLoc () const inline
Definition at line 1538 of file Stmt.h.
Referenced by clang::ento::PathDiagnosticLocation::createBeginBrace().
getRBracLoc()
SourceLocation clang::CompoundStmt::getRBracLoc () const inline
Definition at line 1539 of file Stmt.h.
Referenced by clang::ento::PathDiagnosticLocation::createEndBrace().
getStmtExprResult() [1/2]
Stmt * clang::CompoundStmt::getStmtExprResult () inline
Definition at line 1523 of file Stmt.h.
References body(), and body_back().
Referenced by clang::Sema::BuildStmtExpr(), clang::computeDependence(), and getStmtExprResult().
getStmtExprResult() [2/2]
const Stmt * clang::CompoundStmt::getStmtExprResult () const inline
Definition at line 1531 of file Stmt.h.
References getStmtExprResult().
getStoredFPFeatures()
FPOptionsOverride clang::CompoundStmt::getStoredFPFeatures () const inline
Get FPOptionsOverride from trailing storage.
Definition at line 1456 of file Stmt.h.
References hasStoredFPFeatures().
hasStoredFPFeatures()
bool clang::CompoundStmt::hasStoredFPFeatures () const inline
Definition at line 1453 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by getStoredFPFeatures().
size()
unsigned clang::CompoundStmt::size () const inline
Definition at line 1451 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by body_back(), body_back(), body_end(), body_end(), and isIdenticalStmt().
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 1409 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp