clang: clang::RISCV::RVVType Class Reference
clang::RISCV::RVVType Class Reference
#include "clang/Support/RISCVVIntrinsicUtils.h"
Public Member Functions
RVVType ()
RVVType (BasicType BT, int Log2LMUL, const PrototypeDescriptor &Profile)
const std::string & getBuiltinStr () const
const std::string & getClangBuiltinStr () const
const std::string & getTypeStr () const
const std::string & getShortStr ()
bool isValid () const
bool isScalar () const
bool isVector () const
bool isVector (unsigned Width) const
bool isFloat () const
bool isSignedInteger () const
bool isFloatVector (unsigned Width) const
bool isFloat (unsigned Width) const
bool isConstant () const
bool isPointer () const
unsigned getElementBitwidth () const
ScalarTypeKind getScalarType () const
VScaleVal getScale () const
Static Public Member Functions
static llvm::Optional< RVVTypes > computeTypes (BasicType BT, int Log2LMUL, unsigned NF, llvm::ArrayRef< PrototypeDescriptor > Prototype)
Compute output and input types by applying different config (basic type and LMUL with type transformers).
static llvm::Optional< RVVTypePtr > computeType (BasicType BT, int Log2LMUL, PrototypeDescriptor Proto)
Detailed Description
Definition at line 172 of file RISCVVIntrinsicUtils.h.
Constructor & Destructor Documentation
RVVType() [1/2]
clang::RISCV::RVVType::RVVType () inline
Definition at line 193 of file RISCVVIntrinsicUtils.h.
RVVType() [2/2]
clang::RISCV::RVVType::RVVType (BasicType BT, int Log2LMUL, const PrototypeDescriptor & Profile)
Definition at line 76 of file RISCVVIntrinsicUtils.cpp.
References isVector().
Member Function Documentation
computeType()
Optional< RVVTypePtr > clang::RISCV::RVVType::computeType (BasicType BT, int Log2LMUL, PrototypeDescriptor Proto) static
Definition at line 819 of file RISCVVIntrinsicUtils.cpp.
References clang::RISCV::computeRVVTypeHashValue().
Referenced by computeTypes(), and clang::RISCV::RVVIntrinsic::getSuffixStr().
computeTypes()
Optional< RVVTypes > clang::RISCV::RVVType::computeTypes (BasicType BT, int Log2LMUL, unsigned NF, llvm::ArrayRef< PrototypeDescriptor > Prototype) static
Compute output and input types by applying different config (basic type and LMUL with type transformers).
It also record result of type in legal or illegal set to avoid compute the same config again. The result maybe have illegal RVVType.
Definition at line 789 of file RISCVVIntrinsicUtils.cpp.
References computeType(), and clang::Prototype.
getBuiltinStr()
const std::string & clang::RISCV::RVVType::getBuiltinStr () const inline
Definition at line 198 of file RISCVVIntrinsicUtils.h.
Referenced by clang::RISCV::RVVIntrinsic::getBuiltinTypeStr().
getClangBuiltinStr()
const std::string & clang::RISCV::RVVType::getClangBuiltinStr () const inline
Definition at line 202 of file RISCVVIntrinsicUtils.h.
getElementBitwidth()
unsigned clang::RISCV::RVVType::getElementBitwidth () const inline
Definition at line 235 of file RISCVVIntrinsicUtils.h.
getScalarType()
ScalarTypeKind clang::RISCV::RVVType::getScalarType () const inline
Definition at line 237 of file RISCVVIntrinsicUtils.h.
getScale()
VScaleVal clang::RISCV::RVVType::getScale () const inline
Definition at line 238 of file RISCVVIntrinsicUtils.h.
getShortStr()
const std::string & clang::RISCV::RVVType::getShortStr () inline
Definition at line 209 of file RISCVVIntrinsicUtils.h.
getTypeStr()
const std::string & clang::RISCV::RVVType::getTypeStr () const inline
Definition at line 206 of file RISCVVIntrinsicUtils.h.
isConstant()
bool clang::RISCV::RVVType::isConstant () const inline
Definition at line 233 of file RISCVVIntrinsicUtils.h.
isFloat() [1/2]
bool clang::RISCV::RVVType::isFloat () const inline
Definition at line 223 of file RISCVVIntrinsicUtils.h.
References clang::RISCV::Float.
Referenced by isFloat(), and isFloatVector().
isFloat() [2/2]
bool clang::RISCV::RVVType::isFloat (unsigned Width) const inline
Definition at line 230 of file RISCVVIntrinsicUtils.h.
References isFloat().
isFloatVector()
bool clang::RISCV::RVVType::isFloatVector (unsigned Width) const inline
Definition at line 227 of file RISCVVIntrinsicUtils.h.
References isFloat(), and isVector().
isPointer()
bool clang::RISCV::RVVType::isPointer () const inline
Definition at line 234 of file RISCVVIntrinsicUtils.h.
isScalar()
bool clang::RISCV::RVVType::isScalar () const inline
Definition at line 218 of file RISCVVIntrinsicUtils.h.
isSignedInteger()
bool clang::RISCV::RVVType::isSignedInteger () const inline
Definition at line 224 of file RISCVVIntrinsicUtils.h.
References clang::RISCV::SignedInteger.
isValid()
bool clang::RISCV::RVVType::isValid () const inline
Definition at line 217 of file RISCVVIntrinsicUtils.h.
isVector() [1/2]
bool clang::RISCV::RVVType::isVector () const inline
Definition at line 219 of file RISCVVIntrinsicUtils.h.
Referenced by isFloatVector(), isVector(), and RVVType().
isVector() [2/2]
bool clang::RISCV::RVVType::isVector (unsigned Width) const inline
Definition at line 220 of file RISCVVIntrinsicUtils.h.
References isVector().
The documentation for this class was generated from the following files:
include/clang/Support/RISCVVIntrinsicUtils.h
lib/Support/RISCVVIntrinsicUtils.cpp