clang: clang::ast_matchers::MatchFinder Class Reference
clang::ast_matchers::MatchFinder Class Reference
A class to allow finding matches over the Clang AST.
#include "clang/ASTMatchers/ASTMatchFinder.h"
Classes
class MatchCallback
Called when the Match registered for it was successfully found in the AST.
struct MatchersByType
For each Matcher<> a MatchCallback that will be called when it matches.
struct MatchFinderOptions
struct MatchResult
Contains all information for a given match.
class ParsingDoneTestCallback
Called when parsing is finished. Intended for testing only.
Public Member Functions
MatchFinder (MatchFinderOptions Options=MatchFinderOptions())
~MatchFinder ()
bool addDynamicMatcher (const internal::DynTypedMatcher &NodeMatch, MatchCallback *Action)
Adds a matcher to execute when running over the AST.
std::unique_ptr< clang::ASTConsumer > newASTConsumer ()
Creates a clang ASTConsumer that finds all matches.
void matchAST (ASTContext &Context)
Finds all matches in the given AST.
void registerTestCallbackAfterParsing (ParsingDoneTestCallback *ParsingDone)
Registers a callback to notify the end of parsing.
void addMatcher (const DeclarationMatcher &NodeMatch, MatchCallback *Action)
Adds a matcher to execute when running over the AST.
void addMatcher (const TypeMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const StatementMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const NestedNameSpecifierMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const NestedNameSpecifierLocMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const TypeLocMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const CXXCtorInitializerMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const TemplateArgumentLocMatcher &NodeMatch, MatchCallback *Action)
void addMatcher (const AttrMatcher &NodeMatch, MatchCallback *Action)
template<typename T >
void match (const T &Node, ASTContext &Context)
Calls the registered callbacks on all matches on the given Node.
void match (const clang::DynTypedNode &Node, ASTContext &Context)
Detailed Description
A class to allow finding matches over the Clang AST.
After creation, you can add multiple matchers to the MatchFinder via calls to addMatcher(...).
Once all matchers are added, newASTConsumer() returns an ASTConsumer that will trigger the callbacks specified via addMatcher(...) when a match is found.
The order of matches is guaranteed to be equivalent to doing a pre-order traversal on the AST, and applying the matchers in the order in which they were added to the MatchFinder.
See ASTMatchers.h for more information about how to create matchers.
Not intended to be subclassed.
Definition at line 68 of file ASTMatchFinder.h.
Constructor & Destructor Documentation
MatchFinder()
clang::ast_matchers::MatchFinder::MatchFinder (MatchFinderOptions Options = MatchFinderOptions())
Definition at line 1558 of file ASTMatchFinder.cpp.
~MatchFinder()
clang::ast_matchers::MatchFinder::~MatchFinder ()
Definition at line 1561 of file ASTMatchFinder.cpp.
Member Function Documentation
addDynamicMatcher()
bool clang::ast_matchers::MatchFinder::addDynamicMatcher (const internal::DynTypedMatcher & NodeMatch, MatchCallback * Action)
Adds a matcher to execute when running over the AST.
This is similar to addMatcher(), but it uses the dynamic interface. It is more flexible, but the lost type information enables a caller to pass a matcher that cannot match anything.
Returns
true if the matcher is a valid top-level matcher, false otherwise.
Definition at line 1629 of file ASTMatchFinder.cpp.
References addMatcher().
Referenced by clang::tooling::ASTMatchRefactorer::addDynamicMatcher(), and clang::tooling::Transformer::registerMatchers().
addMatcher() [1/9]
void clang::ast_matchers::MatchFinder::addMatcher (const AttrMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1623 of file ASTMatchFinder.cpp.
addMatcher() [2/9]
void clang::ast_matchers::MatchFinder::addMatcher (const CXXCtorInitializerMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1611 of file ASTMatchFinder.cpp.
addMatcher() [3/9]
void clang::ast_matchers::MatchFinder::addMatcher (const DeclarationMatcher & NodeMatch, MatchCallback * Action)
Adds a matcher to execute when running over the AST.
Calls 'Action' with the BoundNodes on every match. Adding more than one 'NodeMatch' allows finding different matches in a single pass over the AST.
Does not take ownership of 'Action'.
Definition at line 1563 of file ASTMatchFinder.cpp.
References clang::ast_matchers::MatchFinder::MatchCallback::getCheckTraversalKind(), and clang::ast_matchers::traverse().
Referenced by addDynamicMatcher(), and clang::tooling::ASTMatchRefactorer::addMatcher().
addMatcher() [4/9]
void clang::ast_matchers::MatchFinder::addMatcher (const NestedNameSpecifierLocMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1599 of file ASTMatchFinder.cpp.
addMatcher() [5/9]
void clang::ast_matchers::MatchFinder::addMatcher (const NestedNameSpecifierMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1593 of file ASTMatchFinder.cpp.
addMatcher() [6/9]
void clang::ast_matchers::MatchFinder::addMatcher (const StatementMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1581 of file ASTMatchFinder.cpp.
References clang::ast_matchers::MatchFinder::MatchCallback::getCheckTraversalKind(), and clang::ast_matchers::traverse().
addMatcher() [7/9]
void clang::ast_matchers::MatchFinder::addMatcher (const TemplateArgumentLocMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1617 of file ASTMatchFinder.cpp.
addMatcher() [8/9]
void clang::ast_matchers::MatchFinder::addMatcher (const TypeLocMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1605 of file ASTMatchFinder.cpp.
addMatcher() [9/9]
void clang::ast_matchers::MatchFinder::addMatcher (const TypeMatcher & NodeMatch, MatchCallback * Action)
Definition at line 1575 of file ASTMatchFinder.cpp.
match() [1/2]
void clang::ast_matchers::MatchFinder::match (const clang::DynTypedNode & Node, ASTContext & Context)
Definition at line 1666 of file ASTMatchFinder.cpp.
References Node.
match() [2/2]
template<typename T > void clang::ast_matchers::MatchFinder::match (const T & Node, ASTContext & Context) inline
Calls the registered callbacks on all matches on the given Node.
Note that there can be multiple matches on a single node, for example when using decl(forEachDescendant(stmt())).
Definition at line 193 of file ASTMatchFinder.h.
References clang::DynTypedNode::create(), match(), and Node.
Referenced by match().
matchAST()
void clang::ast_matchers::MatchFinder::matchAST (ASTContext & Context)
Finds all matches in the given AST.
Definition at line 1672 of file ASTMatchFinder.cpp.
Referenced by clang::tooling::RefactoringASTConsumer::HandleTranslationUnit().
newASTConsumer()
std::unique_ptr< ASTConsumer > clang::ast_matchers::MatchFinder::newASTConsumer ()
Creates a clang ASTConsumer that finds all matches.
Definition at line 1662 of file ASTMatchFinder.cpp.
registerTestCallbackAfterParsing()
void clang::ast_matchers::MatchFinder::registerTestCallbackAfterParsing (MatchFinder::ParsingDoneTestCallback * NewParsingDone)
Registers a callback to notify the end of parsing.
The provided closure is called after parsing is done, before the AST is traversed. Useful for benchmarking. Each call to FindAll(...) will call the closure once.
Definition at line 1681 of file ASTMatchFinder.cpp.
The documentation for this class was generated from the following files:
include/clang/ASTMatchers/ASTMatchFinder.h
lib/ASTMatchers/ASTMatchFinder.cpp