clang: clang::UnqualifiedId Class Reference
clang::UnqualifiedId Class Reference
Represents a C++ unqualified-id that has been parsed.
#include "clang/Sema/DeclSpec.h"
Classes
struct OFI
Public Member Functions
UnqualifiedId ()
void clear ()
Clear out this unqualified-id, setting it to default (invalid) state.
bool isValid () const
Determine whether this unqualified-id refers to a valid name.
bool isInvalid () const
Determine whether this unqualified-id refers to an invalid name.
UnqualifiedIdKind getKind () const
Determine what kind of name we have.
void setIdentifier (const IdentifierInfo *Id, SourceLocation IdLoc)
Specify that this unqualified-id was parsed as an identifier.
void setOperatorFunctionId (SourceLocation OperatorLoc, OverloadedOperatorKind Op, SourceLocation SymbolLocations[3])
Specify that this unqualified-id was parsed as an operator-function-id.
void setConversionFunctionId (SourceLocation OperatorLoc, ParsedType Ty, SourceLocation EndLoc)
Specify that this unqualified-id was parsed as a conversion-function-id.
void setLiteralOperatorId (const IdentifierInfo *Id, SourceLocation OpLoc, SourceLocation IdLoc)
Specific that this unqualified-id was parsed as a literal-operator-id.
void setConstructorName (ParsedType ClassType, SourceLocation ClassNameLoc, SourceLocation EndLoc)
Specify that this unqualified-id was parsed as a constructor name.
void setConstructorTemplateId (TemplateIdAnnotation *TemplateId)
Specify that this unqualified-id was parsed as a template-id that names a constructor.
void setDestructorName (SourceLocation TildeLoc, ParsedType ClassType, SourceLocation EndLoc)
Specify that this unqualified-id was parsed as a destructor name.
void setTemplateId (TemplateIdAnnotation *TemplateId)
Specify that this unqualified-id was parsed as a template-id.
void setDeductionGuideName (ParsedTemplateTy Template, SourceLocation TemplateLoc)
Specify that this unqualified-id was parsed as a template-name for a deduction-guide.
void setImplicitSelfParam (const IdentifierInfo *Id)
Specify that this unqualified-id is an implicit 'self' parameter.
SourceRange getSourceRange () const LLVM_READONLY
Return the source range that covers this unqualified-id.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
Public Attributes
UnqualifiedIdKind Kind
Describes the kind of unqualified-id parsed.
union {
IdentifierInfo * Identifier
When Kind == IK_Identifier, the parsed identifier, or when Kind == IK_UserLiteralId, the identifier suffix.
struct OFI OperatorFunctionId
When Kind == IK_OperatorFunctionId, the overloaded operator that we parsed.
UnionParsedType ConversionFunctionId
When Kind == IK_ConversionFunctionId, the type that the conversion function names.
UnionParsedType ConstructorName
When Kind == IK_ConstructorName, the class-name of the type whose constructor is being referenced.
UnionParsedType DestructorName
When Kind == IK_DestructorName, the type referred to by the class-name.
UnionParsedTemplateTy TemplateName
When Kind == IK_DeductionGuideName, the parsed template-name.
TemplateIdAnnotation * TemplateId
When Kind == IK_TemplateId or IK_ConstructorTemplateId, the template-id annotation that contains the template name and template arguments.
};
Anonymous union that holds extra data associated with the parsed unqualified-id.
SourceLocation StartLocation
The location of the first token that describes this unqualified-id, which will be the location of the identifier, "operator" keyword, tilde (for a destructor), or the template name of a template-id.
SourceLocation EndLocation
The location of the last token that describes this unqualified-id.
Detailed Description
Represents a C++ unqualified-id that has been parsed.
Definition at line 951 of file DeclSpec.h.
Constructor & Destructor Documentation
UnqualifiedId()
clang::UnqualifiedId::UnqualifiedId () inline
Definition at line 1014 of file DeclSpec.h.
Member Function Documentation
clear()
void clang::UnqualifiedId::clear () inline
Clear out this unqualified-id, setting it to default (invalid) state.
Definition at line 1019 of file DeclSpec.h.
References EndLocation, Identifier, clang::IK_Identifier, and StartLocation.
getBeginLoc()
SourceLocation clang::UnqualifiedId::getBeginLoc () const inline
Definition at line 1163 of file DeclSpec.h.
References StartLocation.
Referenced by clang::Sema::CheckDeductionGuideDeclarator().
getEndLoc()
SourceLocation clang::UnqualifiedId::getEndLoc () const inline
Definition at line 1164 of file DeclSpec.h.
References EndLocation.
getKind()
UnqualifiedIdKind clang::UnqualifiedId::getKind () const inline
Determine what kind of name we have.
Definition at line 1033 of file DeclSpec.h.
References Kind.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckFunctionOrTemplateParamDeclarator(), diagnoseRedundantReturnTypeQualifiers(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), and clang::Declarator::isCtorOrDtor().
getSourceRange()
SourceRange clang::UnqualifiedId::getSourceRange () const inline
Return the source range that covers this unqualified-id.
Definition at line 1160 of file DeclSpec.h.
References EndLocation, and StartLocation.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::CheckConversionDeclarator(), and GetDeclSpecTypeForDeclarator().
isInvalid()
bool clang::UnqualifiedId::isInvalid () const inline
Determine whether this unqualified-id refers to an invalid name.
Definition at line 1030 of file DeclSpec.h.
References isValid().
isValid()
bool clang::UnqualifiedId::isValid () const inline
Determine whether this unqualified-id refers to a valid name.
Definition at line 1027 of file DeclSpec.h.
References clang::SourceLocation::isValid(), and StartLocation.
Referenced by isInvalid(), and setOperatorFunctionId().
setConstructorName()
void clang::UnqualifiedId::setConstructorName (ParsedType ClassType, SourceLocation ClassNameLoc, SourceLocation EndLoc) inline
Specify that this unqualified-id was parsed as a constructor name.
Parameters
ClassType the class type referred to by the constructor name.
ClassNameLoc the location of the class name.
EndLoc the location of the last token that makes up the type name.
Definition at line 1098 of file DeclSpec.h.
References ConstructorName, EndLocation, clang::IK_ConstructorName, and StartLocation.
setConstructorTemplateId()
void UnqualifiedId::setConstructorTemplateId (TemplateIdAnnotation * TemplateId)
Specify that this unqualified-id was parsed as a template-id that names a constructor.
Parameters
TemplateId the template-id annotation that describes the parsed template-id. This UnqualifiedId instance will take ownership of the TemplateId and will free it on destruction.
Definition at line 42 of file DeclSpec.cpp.
References EndLocation, clang::IK_ConstructorTemplateId, clang::TemplateIdAnnotation::isInvalid(), clang::TemplateIdAnnotation::RAngleLoc, StartLocation, TemplateId, and clang::TemplateIdAnnotation::TemplateNameLoc.
setConversionFunctionId()
void clang::UnqualifiedId::setConversionFunctionId (SourceLocation OperatorLoc, ParsedType Ty, SourceLocation EndLoc) inline
Specify that this unqualified-id was parsed as a conversion-function-id.
Parameters
OperatorLoc the location of the 'operator' keyword.
Ty the type to which this conversion function is converting.
EndLoc the location of the last token that makes up the type name.
Definition at line 1066 of file DeclSpec.h.
References ConversionFunctionId, EndLocation, clang::IK_ConversionFunctionId, and StartLocation.
setDeductionGuideName()
void clang::UnqualifiedId::setDeductionGuideName (ParsedTemplateTy Template, SourceLocation TemplateLoc) inline
Specify that this unqualified-id was parsed as a template-name for a deduction-guide.
Parameters
Template The parsed template-name.
TemplateLoc The location of the parsed template-name.
Definition at line 1142 of file DeclSpec.h.
References EndLocation, clang::IK_DeductionGuideName, and StartLocation.
setDestructorName()
void clang::UnqualifiedId::setDestructorName (SourceLocation TildeLoc, ParsedType ClassType, SourceLocation EndLoc) inline
Specify that this unqualified-id was parsed as a destructor name.
Parameters
TildeLoc the location of the '~' that introduces the destructor name.
ClassType the name of the class referred to by the destructor name.
Definition at line 1121 of file DeclSpec.h.
References DestructorName, EndLocation, clang::IK_DestructorName, and StartLocation.
setIdentifier()
void clang::UnqualifiedId::setIdentifier (const IdentifierInfo * Id, SourceLocation IdLoc) inline
Specify that this unqualified-id was parsed as an identifier.
Parameters
Id the parsed identifier.
IdLoc the location of the parsed identifier.
Definition at line 1039 of file DeclSpec.h.
References EndLocation, Id, Identifier, clang::IK_Identifier, and StartLocation.
Referenced by clang::Sema::CodeCompleteObjCSuperMessage().
setImplicitSelfParam()
void clang::UnqualifiedId::setImplicitSelfParam (const IdentifierInfo * Id) inline
Specify that this unqualified-id is an implicit 'self' parameter.
Parameters
Id the identifier.
Definition at line 1153 of file DeclSpec.h.
References EndLocation, Id, Identifier, clang::IK_ImplicitSelfParam, and StartLocation.
Referenced by clang::Sema::BuildIvarRefExpr().
setLiteralOperatorId()
void clang::UnqualifiedId::setLiteralOperatorId (const IdentifierInfo * Id, SourceLocation OpLoc, SourceLocation IdLoc) inline
Specific that this unqualified-id was parsed as a literal-operator-id.
Parameters
Id the parsed identifier.
OpLoc the location of the 'operator' keyword.
IdLoc the location of the identifier.
Definition at line 1083 of file DeclSpec.h.
References EndLocation, Id, Identifier, clang::IK_LiteralOperatorId, and StartLocation.
setOperatorFunctionId()
void UnqualifiedId::setOperatorFunctionId (SourceLocation OperatorLoc, OverloadedOperatorKind Op, SourceLocation SymbolLocations[3])
Specify that this unqualified-id was parsed as an operator-function-id.
Parameters
OperatorLoc the location of the 'operator' keyword.
Op the overloaded operator.
SymbolLocations the locations of the individual operator symbols in the operator.
Definition at line 1450 of file DeclSpec.cpp.
References EndLocation, clang::IK_OperatorFunctionId, isValid(), clang::UnqualifiedId::OFI::Operator, OperatorFunctionId, StartLocation, and clang::UnqualifiedId::OFI::SymbolLocations.
Referenced by ParseReductionId().
setTemplateId()
void UnqualifiedId::setTemplateId (TemplateIdAnnotation * TemplateId)
Specify that this unqualified-id was parsed as a template-id.
Parameters
TemplateId the template-id annotation that describes the parsed template-id. This UnqualifiedId instance will take ownership of the TemplateId and will free it on destruction.
Definition at line 31 of file DeclSpec.cpp.
References EndLocation, clang::IK_TemplateId, clang::TemplateIdAnnotation::isInvalid(), clang::TemplateIdAnnotation::RAngleLoc, StartLocation, TemplateId, and clang::TemplateIdAnnotation::TemplateNameLoc.
Member Data Documentation
[union]
union { ... } clang::UnqualifiedId
Anonymous union that holds extra data associated with the parsed unqualified-id.
ConstructorName
UnionParsedType clang::UnqualifiedId::ConstructorName
When Kind == IK_ConstructorName, the class-name of the type whose constructor is being referenced.
Definition at line 991 of file DeclSpec.h.
Referenced by setConstructorName().
ConversionFunctionId
UnionParsedType clang::UnqualifiedId::ConversionFunctionId
When Kind == IK_ConversionFunctionId, the type that the conversion function names.
Definition at line 987 of file DeclSpec.h.
Referenced by clang::Sema::CheckConversionDeclarator(), GetDeclSpecTypeForDeclarator(), and setConversionFunctionId().
DestructorName
UnionParsedType clang::UnqualifiedId::DestructorName
When Kind == IK_DestructorName, the type referred to by the class-name.
Definition at line 995 of file DeclSpec.h.
Referenced by clang::Sema::CheckDestructorDeclarator(), and setDestructorName().
EndLocation
SourceLocation clang::UnqualifiedId::EndLocation
The location of the last token that describes this unqualified-id.
Definition at line 1012 of file DeclSpec.h.
Referenced by clear(), getEndLoc(), getMissingDeclaratorIdLoc(), getSourceRange(), setConstructorName(), setConstructorTemplateId(), setConversionFunctionId(), clang::Declarator::setDecompositionBindings(), setDeductionGuideName(), setDestructorName(), setIdentifier(), setImplicitSelfParam(), setLiteralOperatorId(), setOperatorFunctionId(), and setTemplateId().
Identifier
IdentifierInfo* clang::UnqualifiedId::Identifier
When Kind == IK_Identifier, the parsed identifier, or when Kind == IK_UserLiteralId, the identifier suffix.
Definition at line 979 of file DeclSpec.h.
Referenced by clang::Sema::ActOnPseudoDestructorExpr(), clear(), setIdentifier(), setImplicitSelfParam(), and setLiteralOperatorId().
Kind
UnqualifiedIdKind clang::UnqualifiedId::Kind
Describes the kind of unqualified-id parsed.
Definition at line 958 of file DeclSpec.h.
Referenced by clang::Sema::ActOnTypedefDeclarator(), getKind(), and clang::Declarator::isStaticMember().
OperatorFunctionId
struct OFI clang::UnqualifiedId::OperatorFunctionId
When Kind == IK_OperatorFunctionId, the overloaded operator that we parsed.
Definition at line 983 of file DeclSpec.h.
Referenced by setOperatorFunctionId().
StartLocation
SourceLocation clang::UnqualifiedId::StartLocation
The location of the first token that describes this unqualified-id, which will be the location of the identifier, "operator" keyword, tilde (for a destructor), or the template name of a template-id.
Definition at line 1009 of file DeclSpec.h.
Referenced by clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnTypedefDeclarator(), clear(), getBeginLoc(), getMissingDeclaratorIdLoc(), getSourceRange(), isValid(), setConstructorName(), setConstructorTemplateId(), setConversionFunctionId(), setDeductionGuideName(), setDestructorName(), setIdentifier(), setImplicitSelfParam(), setLiteralOperatorId(), setOperatorFunctionId(), and setTemplateId().
TemplateId
TemplateIdAnnotation* clang::UnqualifiedId::TemplateId
When Kind == IK_TemplateId or IK_ConstructorTemplateId, the template-id annotation that contains the template name and template arguments.
Definition at line 1003 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), setConstructorTemplateId(), and setTemplateId().
TemplateName
UnionParsedTemplateTy clang::UnqualifiedId::TemplateName
When Kind == IK_DeductionGuideName, the parsed template-name.
Definition at line 998 of file DeclSpec.h.
Referenced by clang::Sema::CheckDeductionGuideDeclarator().
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp