clang: clang::ento::CheckerContext Class Reference
clang::ento::CheckerContext Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
Public Member Functions
CheckerContext (NodeBuilder &builder, ExprEngine &eng, ExplodedNode *pred, const ProgramPoint &loc, bool wasInlined=false)
AnalysisManager & getAnalysisManager ()
ConstraintManager & getConstraintManager ()
StoreManager & getStoreManager ()
ExplodedNode * getPredecessor ()
Returns the previous node in the exploded graph, which includes the state of the program before the checker ran.
const ProgramStateRef & getState () const
bool isDifferent ()
Check if the checker changed the state of the execution; ex: added a new transition or a bug report.
unsigned blockCount () const
Returns the number of times the current block has been visited along the analyzed path.
ASTContext & getASTContext ()
const ASTContext & getASTContext () const
const LangOptions & getLangOpts () const
const LocationContext * getLocationContext () const
const StackFrameContext * getStackFrame () const
bool inTopFrame () const
Return true if the current LocationContext has no caller context.
BugReporter & getBugReporter ()
const SourceManager & getSourceManager ()
Preprocessor & getPreprocessor ()
SValBuilder & getSValBuilder ()
SymbolManager & getSymbolManager ()
ProgramStateManager & getStateManager ()
AnalysisDeclContext * getCurrentAnalysisDeclContext () const
unsigned getBlockID () const
Get the blockID.
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
bool isGreaterOrEqual (const Expr *E, unsigned long long Val)
Returns true if the value of E is greater than or equal to Val under unsigned comparison.
bool isNegative (const Expr *E)
Returns true if the value of E is negative.
ExplodedNode * addTransition (ProgramStateRef State=nullptr, const ProgramPointTag *Tag=nullptr)
Generates a new transition in the program state graph (ExplodedGraph).
ExplodedNode * addTransition (ProgramStateRef State, ExplodedNode *Pred, const ProgramPointTag *Tag=nullptr)
Generates a new transition with the given predecessor.
ExplodedNode * generateSink (ProgramStateRef State, ExplodedNode *Pred, const ProgramPointTag *Tag=nullptr)
Generate a sink node.
void addSink (ProgramStateRef State=nullptr, const ProgramPointTag *Tag=nullptr)
Add a sink node to the current path of execution, halting analysis.
ExplodedNode * generateErrorNode (ProgramStateRef State=nullptr, const ProgramPointTag *Tag=nullptr)
Generate a transition to a node that will be used to report an error.
ExplodedNode * generateNonFatalErrorNode (ProgramStateRef State=nullptr, const ProgramPointTag *Tag=nullptr)
Generate a transition to a node that will be used to report an error.
ExplodedNode * generateNonFatalErrorNode (ProgramStateRef State, ExplodedNode *Pred, const ProgramPointTag *Tag=nullptr)
Generate a transition to a node that will be used to report an error.
void emitReport (std::unique_ptr< BugReport > R)
Emit the diagnostics report.
LLVM_ATTRIBUTE_RETURNS_NONNULL const NoteTag * getNoteTag (NoteTag::Callback &&Cb, bool IsPrunable=false)
Produce a program point tag that displays an additional path note to the user.
const NoteTag * getNoteTag (std::function< std::string(PathSensitiveBugReport &)> &&Cb, bool IsPrunable=false)
A shorthand version of getNoteTag that doesn't require you to accept the 'BugReporterContext' argument when you don't need it.
const NoteTag * getNoteTag (std::function< std::string()> &&Cb, bool IsPrunable=false)
A shorthand version of getNoteTag that doesn't require you to accept the arguments when you don't need it.
const NoteTag * getNoteTag (StringRef Note, bool IsPrunable=false)
A shorthand version of getNoteTag that accepts a plain note.
const NoteTag * getNoteTag (std::function< void(PathSensitiveBugReport &BR, llvm::raw_ostream &OS)> &&Cb, bool IsPrunable=false)
A shorthand version of getNoteTag that accepts a lambda with stream for note.
StringRef getDeclDescription (const Decl *D)
Returns the word that should be used to refer to the declaration in the report.
const FunctionDecl * getCalleeDecl (const CallExpr *CE) const
Get the declaration of the called function (path-sensitive).
StringRef getCalleeName (const FunctionDecl *FunDecl) const
Get the name of the called function (path-sensitive).
const IdentifierInfo * getCalleeIdentifier (const CallExpr *CE) const
Get the identifier of the called function (path-sensitive).
StringRef getCalleeName (const CallExpr *CE) const
Get the name of the called function (path-sensitive).
StringRef getMacroNameOrSpelling (SourceLocation &Loc)
Depending on wither the location corresponds to a macro, return either the macro name or the token spelling.
Static Public Member Functions
static const MemRegion * getLocationRegionIfPostStore (const ExplodedNode *N)
If the given node corresponds to a PostStore program point, retrieve the location region as it was uttered in the code.
static bool isCLibraryFunction (const FunctionDecl *FD, StringRef Name=StringRef())
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
Public Attributes
const bool wasInlined
If we are post visiting a call, this flag will be set if the call was inlined.
Detailed Description
Definition at line 23 of file CheckerContext.h.
Constructor & Destructor Documentation
CheckerContext()
clang::ento::CheckerContext::CheckerContext (NodeBuilder & builder, ExprEngine & eng, ExplodedNode * pred, const ProgramPoint & loc, bool wasInlined = false) inline
Definition at line 40 of file CheckerContext.h.
References clang::ento::ExplodedNode::getState().
Member Function Documentation
addSink()
void clang::ento::CheckerContext::addSink (ProgramStateRef State = nullptr, const ProgramPointTag * Tag = nullptr) inline
Add a sink node to the current path of execution, halting analysis.
Definition at line 194 of file CheckerContext.h.
References addTransition(), generateSink(), getPredecessor(), and getState().
addTransition() [1/2]
ExplodedNode * clang::ento::CheckerContext::addTransition (ProgramStateRef State, ExplodedNode * Pred, const ProgramPointTag * Tag = nullptr) inline
Generates a new transition with the given predecessor.
Allows checkers to generate a chain of nodes.
Parameters
State The state of the generated node.
Pred The transition will be generated from the specified Pred node to the newly generated node.
Tag The tag to uniquely identify the creation site.
Definition at line 180 of file CheckerContext.h.
addTransition() [2/2]
ExplodedNode * clang::ento::CheckerContext::addTransition (ProgramStateRef State = nullptr, const ProgramPointTag * Tag = nullptr) inline
Generates a new transition in the program state graph (ExplodedGraph).
Uses the default CheckerContext predecessor node.
Parameters
State The state of the generated node. If not specified, the state will not be changed, but the new node will have the checker's tag.
Tag The tag is used to uniquely identify the creation site. If no tag is specified, a default tag, unique to the given checker, will be used. Tags are used to prevent states generated at different sites from caching out.
Definition at line 168 of file CheckerContext.h.
References getState().
Referenced by addSink(), clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::mpi::MPIChecker::checkMissingWaits(), clang::ento::mpi::MPIChecker::checkUnmatchedWaits(), generateNonFatalErrorNode(), generateNonFatalErrorNode(), and clang::ento::retaincountchecker::RetainCountChecker::processLeaks().
blockCount()
unsigned clang::ento::CheckerContext::blockCount () const inline
Returns the number of times the current block has been visited along the analyzed path.
Definition at line 79 of file CheckerContext.h.
References clang::ento::NodeBuilderContext::blockCount(), and clang::ento::NodeBuilder::getContext().
emitReport()
void clang::ento::CheckerContext::emitReport (std::unique_ptr< BugReport > R) inline
Emit the diagnostics report.
Definition at line 244 of file CheckerContext.h.
References clang::ento::BugReporter::emitReport(), and clang::ento::ExprEngine::getBugReporter().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::handleAutoreleaseCounts(), and clang::ento::retaincountchecker::RetainCountChecker::processLeaks().
generateErrorNode()
ExplodedNode * clang::ento::CheckerContext::generateErrorNode (ProgramStateRef State = nullptr, const ProgramPointTag * Tag = nullptr) inline
Generate a transition to a node that will be used to report an error.
This node will be a sink. That is, it will stop exploration of the given path.
Parameters
State The state of the generated node.
Tag The tag to uniquely identify the creation site. If null, the default tag for the checker will be used.
Definition at line 208 of file CheckerContext.h.
References generateSink(), and clang::ProgramPoint::getTag().
generateNonFatalErrorNode() [1/2]
ExplodedNode * clang::ento::CheckerContext::generateNonFatalErrorNode (ProgramStateRef State, ExplodedNode * Pred, const ProgramPointTag * Tag = nullptr) inline
Generate a transition to a node that will be used to report an error.
This node will not be a sink. That is, exploration will continue along this path.
Parameters
State The state of the generated node.
Pred The transition will be generated from the specified Pred node to the newly generated node.
Tag The tag to uniquely identify the creation site. If null, the default tag for the checker will be used.
Definition at line 237 of file CheckerContext.h.
References addTransition(), and clang::ProgramPoint::getTag().
generateNonFatalErrorNode() [2/2]
ExplodedNode * clang::ento::CheckerContext::generateNonFatalErrorNode (ProgramStateRef State = nullptr, const ProgramPointTag * Tag = nullptr) inline
Generate a transition to a node that will be used to report an error.
This node will not be a sink. That is, exploration will continue along this path.
Parameters
State The state of the generated node.
Tag The tag to uniquely identify the creation site. If null, the default tag for the checker will be used.
Definition at line 222 of file CheckerContext.h.
References addTransition(), and clang::ProgramPoint::getTag().
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::mpi::MPIChecker::checkMissingWaits(), and clang::ento::mpi::MPIChecker::checkUnmatchedWaits().
generateSink()
ExplodedNode * clang::ento::CheckerContext::generateSink (ProgramStateRef State, ExplodedNode * Pred, const ProgramPointTag * Tag = nullptr) inline
Generate a sink node.
Generating a sink stops exploration of the given path. To create a sink node for the purpose of reporting an error, checkers should use generateErrorNode() instead.
Definition at line 188 of file CheckerContext.h.
References getState().
Referenced by addSink(), generateErrorNode(), and clang::ento::retaincountchecker::RetainCountChecker::handleAutoreleaseCounts().
getAnalysisManager()
AnalysisManager & clang::ento::CheckerContext::getAnalysisManager () inline
Definition at line 55 of file CheckerContext.h.
References clang::ento::ExprEngine::getAnalysisManager().
getASTContext() [1/2]
ASTContext & clang::ento::CheckerContext::getASTContext () inline
Definition at line 83 of file CheckerContext.h.
References clang::ento::ExprEngine::getContext().
Referenced by clang::ento::mpi::MPIChecker::dynamicInit(), clang::ento::retaincountchecker::RetainCountChecker::handleAutoreleaseCounts(), isGreaterOrEqual(), and clang::ento::retaincountchecker::RetainCountChecker::processLeaks().
getASTContext() [2/2]
const ASTContext & clang::ento::CheckerContext::getASTContext () const inline
Definition at line 87 of file CheckerContext.h.
References clang::ento::ExprEngine::getContext().
getBlockID()
unsigned clang::ento::CheckerContext::getBlockID () const inline
Get the blockID.
Definition at line 131 of file CheckerContext.h.
References clang::ento::NodeBuilderContext::getBlock(), clang::CFGBlock::getBlockID(), and clang::ento::NodeBuilder::getContext().
getBugReporter()
BugReporter & clang::ento::CheckerContext::getBugReporter () inline
Definition at line 104 of file CheckerContext.h.
References clang::ento::ExprEngine::getBugReporter().
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::mpi::MPIChecker::checkMissingWaits(), clang::ento::mpi::MPIChecker::checkUnmatchedWaits(), getPreprocessor(), and getSourceManager().
getCalleeDecl()
const FunctionDecl * CheckerContext::getCalleeDecl (const CallExpr * CE) const
Get the declaration of the called function (path-sensitive).
Definition at line 21 of file CheckerContext.cpp.
References clang::ento::SVal::getAsFunctionDecl(), clang::CallExpr::getCallee(), clang::CallExpr::getDirectCallee(), and clang::ento::ExplodedNode::getSVal().
Referenced by getCalleeIdentifier(), and getCalleeName().
getCalleeIdentifier()
const IdentifierInfo * clang::ento::CheckerContext::getCalleeIdentifier (const CallExpr * CE) const inline
Get the identifier of the called function (path-sensitive).
Definition at line 338 of file CheckerContext.h.
References getCalleeDecl(), and clang::NamedDecl::getIdentifier().
getCalleeName() [1/2]
StringRef clang::ento::CheckerContext::getCalleeName (const CallExpr * CE) const inline
Get the name of the called function (path-sensitive).
Definition at line 347 of file CheckerContext.h.
References getCalleeDecl(), and getCalleeName().
getCalleeName() [2/2]
StringRef CheckerContext::getCalleeName (const FunctionDecl * FunDecl) const
Get the name of the called function (path-sensitive).
Definition at line 31 of file CheckerContext.cpp.
References clang::NamedDecl::getIdentifier(), and clang::IdentifierInfo::getName().
Referenced by getCalleeName().
getConstraintManager()
ConstraintManager & clang::ento::CheckerContext::getConstraintManager () inline
Definition at line 59 of file CheckerContext.h.
References clang::ento::ExprEngine::getConstraintManager().
getCurrentAnalysisDeclContext()
AnalysisDeclContext * clang::ento::CheckerContext::getCurrentAnalysisDeclContext () const inline
Definition at line 126 of file CheckerContext.h.
References clang::LocationContext::getAnalysisDeclContext(), and clang::ento::ExplodedNode::getLocationContext().
getDeclDescription()
StringRef CheckerContext::getDeclDescription (const Decl * D)
Returns the word that should be used to refer to the declaration in the report.
Definition at line 40 of file CheckerContext.cpp.
getLangOpts()
const LangOptions & clang::ento::CheckerContext::getLangOpts () const inline
Definition at line 89 of file CheckerContext.h.
References clang::ento::ExprEngine::getContext(), and clang::ASTContext::getLangOpts().
Referenced by getMacroNameOrSpelling().
getLocationContext()
const LocationContext * clang::ento::CheckerContext::getLocationContext () const inline
Definition at line 93 of file CheckerContext.h.
References clang::ento::ExplodedNode::getLocationContext().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), and inTopFrame().
getLocationRegionIfPostStore()
static const MemRegion * clang::ento::CheckerContext::getLocationRegionIfPostStore (const ExplodedNode * N) inline static
If the given node corresponds to a PostStore program point, retrieve the location region as it was uttered in the code.
This utility can be useful for generating extensive diagnostics, for example, for finding variables that the given symbol was assigned to.
Definition at line 140 of file CheckerContext.h.
References clang::ProgramPoint::getAs(), and N.
getMacroNameOrSpelling()
StringRef CheckerContext::getMacroNameOrSpelling (SourceLocation & Loc)
Depending on wither the location corresponds to a macro, return either the macro name or the token spelling.
This could be useful when checkers' logic depends on whether a function is called with a given macro argument. For example: s = socket(AF_INET,..) If AF_INET is a macro, the result should be treated as a source of taint.
See also
clang::Lexer::getSpelling(), clang::Lexer::getImmediateMacroName().
Definition at line 116 of file CheckerContext.cpp.
References clang::Lexer::getImmediateMacroName(), getLangOpts(), getSourceManager(), and clang::Lexer::getSpelling().
getNoteTag() [1/5]
LLVM_ATTRIBUTE_RETURNS_NONNULL const NoteTag * clang::ento::CheckerContext::getNoteTag (NoteTag::Callback && Cb, bool IsPrunable = false) inline
Produce a program point tag that displays an additional path note to the user.
This is a lightweight alternative to the BugReporterVisitor mechanism: instead of visiting the bug report node-by-node to restore the sequence of events that led to discovering a bug, you can add notes as you add your transitions.
Parameters
Cb Callback with 'BugReporterContext &, BugReport &' parameters.
IsPrunable Whether the note is prunable. It allows BugReporter to omit the note from the report if it would make the displayed bug path significantly shorter.
Definition at line 260 of file CheckerContext.h.
References clang::ento::ExprEngine::getDataTags(), and clang::ento::DataTag::Factory::make().
Referenced by getNoteTag(), getNoteTag(), getNoteTag(), and getNoteTag().
getNoteTag() [2/5]
const NoteTag * clang::ento::CheckerContext::getNoteTag (std::function< std::string()> && Cb, bool IsPrunable = false) inline
A shorthand version of getNoteTag that doesn't require you to accept the arguments when you don't need it.
Parameters
Cb Callback without parameters.
IsPrunable Whether the note is prunable. It allows BugReporter to omit the note from the report if it would make the displayed bug path significantly shorter.
Definition at line 287 of file CheckerContext.h.
References getNoteTag().
getNoteTag() [3/5]
const NoteTag * clang::ento::CheckerContext::getNoteTag (std::function< std::string(PathSensitiveBugReport &)> && Cb, bool IsPrunable = false) inline
A shorthand version of getNoteTag that doesn't require you to accept the 'BugReporterContext' argument when you don't need it.
Parameters
Cb Callback only with 'BugReport &' parameter.
IsPrunable Whether the note is prunable. It allows BugReporter to omit the note from the report if it would make the displayed bug path significantly shorter.
Definition at line 272 of file CheckerContext.h.
References getNoteTag().
getNoteTag() [4/5]
const NoteTag * clang::ento::CheckerContext::getNoteTag (std::function< void(PathSensitiveBugReport &BR, llvm::raw_ostream &OS)> && Cb, bool IsPrunable = false) inline
A shorthand version of getNoteTag that accepts a lambda with stream for note.
Parameters
Cb Callback with 'BugReport &' and 'llvm::raw_ostream &'.
IsPrunable Whether the note is prunable. It allows BugReporter to omit the note from the report if it would make the displayed bug path significantly shorter.
Definition at line 314 of file CheckerContext.h.
References getNoteTag(), and clang::ento::OS.
getNoteTag() [5/5]
const NoteTag * clang::ento::CheckerContext::getNoteTag (StringRef Note, bool IsPrunable = false) inline
A shorthand version of getNoteTag that accepts a plain note.
Parameters
Note The note.
IsPrunable Whether the note is prunable. It allows BugReporter to omit the note from the report if it would make the displayed bug path significantly shorter.
Definition at line 300 of file CheckerContext.h.
References getNoteTag(), and clang::Note.
getPredecessor()
ExplodedNode * clang::ento::CheckerContext::getPredecessor () inline
Returns the previous node in the exploded graph, which includes the state of the program before the checker ran.
Note, checkers should not retain the node in their state since the nodes might get invalidated.
Definition at line 70 of file CheckerContext.h.
Referenced by addSink().
getPreprocessor()
Preprocessor & clang::ento::CheckerContext::getPreprocessor () inline
Definition at line 112 of file CheckerContext.h.
References getBugReporter(), and clang::ento::BugReporter::getPreprocessor().
getSourceManager()
const SourceManager & clang::ento::CheckerContext::getSourceManager () inline
Definition at line 108 of file CheckerContext.h.
References getBugReporter(), and clang::ento::BugReporter::getSourceManager().
Referenced by getMacroNameOrSpelling().
getStackFrame()
const StackFrameContext * clang::ento::CheckerContext::getStackFrame () const inline
Definition at line 97 of file CheckerContext.h.
References clang::ento::ExplodedNode::getStackFrame().
getState()
const ProgramStateRef & clang::ento::CheckerContext::getState () const inline
Definition at line 71 of file CheckerContext.h.
References clang::ento::ExplodedNode::getState().
Referenced by addSink(), addTransition(), clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::mpi::MPIChecker::checkMissingWaits(), clang::ento::mpi::MPIChecker::checkUnmatchedWaits(), generateSink(), isGreaterOrEqual(), and isNegative().
getStateManager()
ProgramStateManager & clang::ento::CheckerContext::getStateManager () inline
Definition at line 122 of file CheckerContext.h.
References clang::ento::ExprEngine::getStateManager().
getStoreManager()
StoreManager & clang::ento::CheckerContext::getStoreManager () inline
Definition at line 63 of file CheckerContext.h.
References clang::ento::ExprEngine::getStoreManager().
getSVal()
SVal clang::ento::CheckerContext::getSVal (const Stmt * S) const inline
Get the value of arbitrary expressions at this point in the path.
Definition at line 148 of file CheckerContext.h.
References clang::ento::ExplodedNode::getSVal().
Referenced by isGreaterOrEqual(), and isNegative().
getSValBuilder()
SValBuilder & clang::ento::CheckerContext::getSValBuilder () inline
Definition at line 114 of file CheckerContext.h.
References clang::ento::ExprEngine::getSValBuilder().
Referenced by getSymbolManager(), isGreaterOrEqual(), and isNegative().
getSymbolManager()
SymbolManager & clang::ento::CheckerContext::getSymbolManager () inline
Definition at line 118 of file CheckerContext.h.
References getSValBuilder(), and clang::ento::SValBuilder::getSymbolManager().
inTopFrame()
bool clang::ento::CheckerContext::inTopFrame () const inline
Return true if the current LocationContext has no caller context.
Definition at line 102 of file CheckerContext.h.
References getLocationContext(), and clang::LocationContext::inTopFrame().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction().
isCLibraryFunction()
bool CheckerContext::isCLibraryFunction (const FunctionDecl * FD, StringRef Name = StringRef()) static
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
If a name is provided, the function must additionally match the given name.
Note that this deliberately excludes C++ library functions in the std namespace, but will include C library functions accessed through the std namespace. This also does not check if the function is declared as 'extern "C"', or if it uses C++ name mangling.
Definition at line 48 of file CheckerContext.cpp.
References clang::ASTContext::BuiltinInfo, clang::Decl::getASTContext(), clang::FunctionDecl::getBuiltinID(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::Builtin::Context::getName(), clang::IdentifierInfo::getName(), clang::DeclContext::getRedeclContext(), clang::NamedDecl::isExternallyVisible(), clang::FunctionDecl::isInlined(), and clang::DeclContext::isTranslationUnit().
Referenced by clang::ento::CallEvent::isGlobalCFunction().
isDifferent()
bool clang::ento::CheckerContext::isDifferent () inline
Check if the checker changed the state of the execution; ex: added a new transition or a bug report.
Definition at line 75 of file CheckerContext.h.
isGreaterOrEqual()
bool CheckerContext::isGreaterOrEqual (const Expr * E, unsigned long long Val)
Returns true if the value of E is greater than or equal to Val under unsigned comparison.
Definition at line 147 of file CheckerContext.cpp.
References evalComparison(), getASTContext(), getState(), getSVal(), getSValBuilder(), clang::ento::SValBuilder::makeIntVal(), and V.
isNegative()
bool CheckerContext::isNegative (const Expr * E)
Returns true if the value of E is negative.
Definition at line 152 of file CheckerContext.cpp.
References evalComparison(), getState(), getSVal(), getSValBuilder(), clang::ento::SValBuilder::makeIntVal(), and V.
Member Data Documentation
wasInlined
const bool clang::ento::CheckerContext::wasInlined
If we are post visiting a call, this flag will be set if the call was inlined.
In all other cases it will be false.
Definition at line 38 of file CheckerContext.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h
lib/StaticAnalyzer/Core/CheckerContext.cpp