clang: clang::ADLResult Class Reference
clang::ADLResult Class Reference
A class for storing results from argument-dependent lookup.
#include "clang/Sema/Lookup.h"
Public Types
using iterator
Public Member Functions
void insert (NamedDecl *D)
Adds a new ADL candidate to this map.
void erase (NamedDecl *D)
Removes any data associated with a given decl.
iterator begin ()
iterator end ()
Detailed Description
A class for storing results from argument-dependent lookup.
Definition at line 823 of file Lookup.h.
Member Typedef Documentation
iterator
using clang::ADLResult::iterator
Initial value:
      llvm::mapped_iterator<decltype(Decls)::iterator, select_second>
Definition at line 843 of file Lookup.h.
Member Function Documentation
begin()
iterator clang::ADLResult::begin () inline
Definition at line 846 of file Lookup.h.
Referenced by clang::Sema::AddArgumentDependentLookupCandidates().
end()
iterator clang::ADLResult::end () inline
Definition at line 847 of file Lookup.h.
Referenced by clang::Sema::AddArgumentDependentLookupCandidates().
erase()
void clang::ADLResult::erase (NamedDecl * D) inline
Removes any data associated with a given decl.
Definition at line 839 of file Lookup.h.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::AddArgumentDependentLookupCandidates().
insert()
void ADLResult::insert (NamedDecl * D)
Adds a new ADL candidate to this map.
Definition at line 3784 of file SemaLookup.cpp.
References clang::cast(), clang::Decl::getAsFunction(), and clang::Decl::getCanonicalDecl().
The documentation for this class was generated from the following files:
include/clang/Sema/Lookup.h
lib/Sema/SemaLookup.cpp