clang: clang::TemplateArgumentList Class Reference
clang::TemplateArgumentList Class Reference final
A template argument list.
#include "clang/AST/DeclTemplate.h"
Public Types
enum OnStackType { OnStack }
Type used to indicate that the template argument list itself is a stack object.
Public Member Functions
TemplateArgumentList (const TemplateArgumentList &)=delete
TemplateArgumentList & operator= (const TemplateArgumentList &)=delete
TemplateArgumentList (OnStackType, ArrayRef< TemplateArgument > Args)
Construct a new, temporary template argument list on the stack.
TemplateArgumentList (const TemplateArgumentList *Other)
Produces a shallow copy of the given template argument list.
const TemplateArgument & get (unsigned Idx) const
Retrieve the template argument at a given index.
const TemplateArgument & operator[] (unsigned Idx) const
Retrieve the template argument at a given index.
ArrayRef< TemplateArgument > asArray () const
Produce this as an array ref.
unsigned size () const
Retrieve the number of template arguments in this template argument list.
const TemplateArgument * data () const
Retrieve a pointer to the template argument list.
Static Public Member Functions
static TemplateArgumentList * CreateCopy (ASTContext &Context, ArrayRef< TemplateArgument > Args)
Create a new template argument list that copies the given set of template arguments.
Public Attributes
friend TrailingObjects
Detailed Description
A template argument list.
Definition at line 238 of file DeclTemplate.h.
Member Enumeration Documentation
OnStackType
enum clang::TemplateArgumentList::OnStackType
Type used to indicate that the template argument list itself is a stack object.
It does not own its template arguments.
Enumerator
OnStack
Definition at line 259 of file DeclTemplate.h.
Constructor & Destructor Documentation
TemplateArgumentList() [1/3]
clang::TemplateArgumentList::TemplateArgumentList (const TemplateArgumentList &) delete
TemplateArgumentList() [2/3]
clang::TemplateArgumentList::TemplateArgumentList (OnStackType , ArrayRef< TemplateArgument > Args) inline explicit
Construct a new, temporary template argument list on the stack.
The template argument list does not own the template arguments provided.
Definition at line 270 of file DeclTemplate.h.
TemplateArgumentList() [3/3]
clang::TemplateArgumentList::TemplateArgumentList (const TemplateArgumentList * Other) inline explicit
Produces a shallow copy of the given template argument list.
This operation assumes that the input argument list outlives it. This takes the list as a pointer to avoid looking like a copy constructor, since this really really isn't safe to use that way.
Definition at line 279 of file DeclTemplate.h.
Member Function Documentation
asArray()
ArrayRef< TemplateArgument > clang::TemplateArgumentList::asArray () const inline
Produce this as an array ref.
Definition at line 292 of file DeclTemplate.h.
References data(), and size().
Referenced by DeduceTemplateArguments(), clang::Sema::getMoreSpecializedPartialSpecialization(), clang::ClassTemplateSpecializationDecl::getNameForDiagnostic(), clang::FunctionDecl::getNameForDiagnostic(), clang::VarTemplateSpecializationDecl::getNameForDiagnostic(), clang::RedeclarableTemplateDecl::SpecEntryTraits< FunctionTemplateSpecializationInfo >::getTemplateArgs(), getUuidAttrOfType(), clang::Sema::InstantiateFunctionDeclaration(), clang::Sema::InstantiateVariableDefinition(), clang::Sema::isMoreSpecializedThanPrimary(), clang::Sema::MarkUsedTemplateParameters(), clang::NamedDecl::printNestedNameSpecifier(), clang::ClassTemplateSpecializationDecl::Profile(), clang::FunctionTemplateSpecializationInfo::Profile(), and clang::VarTemplateSpecializationDecl::Profile().
CreateCopy()
TemplateArgumentList * TemplateArgumentList::CreateCopy (ASTContext & Context, ArrayRef< TemplateArgument > Args) static
Create a new template argument list that copies the given set of template arguments.
Definition at line 873 of file DeclTemplate.cpp.
References clang::ASTContext::Allocate().
Referenced by CheckDeducedArgumentConstraints(), ConvertDeducedTemplateArguments(), clang::Sema::FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), clang::ASTNodeImporter::ImportTemplateInformation(), instantiateOMPDeclareVariantAttr(), clang::Sema::SubstituteExplicitTemplateArguments(), clang::ASTDeclReader::UpdateDecl(), clang::ASTDeclReader::VisitClassTemplateSpecializationDeclImpl(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ASTDeclReader::VisitVarTemplateSpecializationDeclImpl().
data()
const TemplateArgument * clang::TemplateArgumentList::data () const inline
Retrieve a pointer to the template argument list.
Definition at line 301 of file DeclTemplate.h.
Referenced by clang::MultiLevelTemplateArgumentList::addOuterTemplateArguments(), asArray(), get(), clang::Sema::getTemplateArgumentBindingsText(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
get()
const TemplateArgument & clang::TemplateArgumentList::get (unsigned Idx) const inline
Retrieve the template argument at a given index.
Definition at line 283 of file DeclTemplate.h.
References data().
Referenced by addInstanceOfTransition(), clang::ASTRecordWriter::AddTemplateArgumentList(), clang::PredefinedExpr::ComputeName(), operator[](), and clang::Sema::SubstituteExplicitTemplateArguments().
operator=()
TemplateArgumentList & clang::TemplateArgumentList::operator= (const TemplateArgumentList &) delete
operator[]()
const TemplateArgument & clang::TemplateArgumentList::operator[] (unsigned Idx) const inline
Retrieve the template argument at a given index.
Definition at line 289 of file DeclTemplate.h.
References get().
size()
unsigned clang::TemplateArgumentList::size () const inline
Retrieve the number of template arguments in this template argument list.
Definition at line 298 of file DeclTemplate.h.
Referenced by addAssociatedClassesAndNamespaces(), clang::MultiLevelTemplateArgumentList::addOuterTemplateArguments(), clang::ASTRecordWriter::AddTemplateArgumentList(), asArray(), clang::PredefinedExpr::ComputeName(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList(), clang::TypeName::getFullyQualifiedTemplateType(), clang::Sema::getTemplateArgumentBindingsText(), clang::Sema::MarkUsedTemplateParameters(), clang::sema::TemplateDeductionInfo::setExplicitArgs(), clang::Sema::SubstituteExplicitTemplateArguments(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
Member Data Documentation
TrailingObjects
friend clang::TemplateArgumentList::TrailingObjects
Definition at line 252 of file DeclTemplate.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclTemplate.h
lib/AST/DeclTemplate.cpp