clang: DefaultStoreHandler Class Reference
DefaultStoreHandler Class Reference final
Public Member Functions
PathDiagnosticPieceRef handle (StoreInfo SI, BugReporterContext &BRC, TrackingOptions Opts) override
Handle the given store and produce the node.
StoreHandler (Tracker &ParentTracker)
Public Member Functions inherited from clang::ento::bugreporter::StoreHandler
StoreHandler (Tracker &ParentTracker)
virtual ~StoreHandler ()
Tracker & getParentTracker ()
Additional Inherited Members
Protected Member Functions inherited from clang::ento::bugreporter::StoreHandler
PathDiagnosticPieceRef constructNote (StoreInfo SI, BugReporterContext &BRC, StringRef NodeText)
Detailed Description
Definition at line 2061 of file BugReporterVisitors.cpp.
Member Function Documentation
handle()
PathDiagnosticPieceRef DefaultStoreHandler::handle (StoreInfo SI, BugReporterContext & BRC, TrackingOptions Opts) inline override virtual
Handle the given store and produce the node.
Parameters
SI The information fully describing the store.
Opts Tracking options specifying how we are tracking the value.
Returns
the produced note, null if the handler doesn't support this kind of stores.
Implements clang::ento::bugreporter::StoreHandler.
Definition at line 2065 of file BugReporterVisitors.cpp.
References clang::ento::bugreporter::StoreInfo::Assignment, clang::ento::bugreporter::StoreInfo::BlockCapture, clang::ento::bugreporter::StoreInfo::CallArgument, clang::ento::bugreporter::StoreInfo::Initialization, clang::ento::bugreporter::TrackingOptions::Kind, clang::ento::OS, showBRDefaultDiagnostics(), showBRDiagnostics(), showBRParamDiagnostics(), clang::ento::bugreporter::StoreInfo::StoreKind, and WillBeUsedForACondition.
StoreHandler()
clang::ento::bugreporter::StoreHandler::StoreHandler (Tracker & ParentTracker) inline
Definition at line 320 of file BugReporterVisitors.h.
The documentation for this class was generated from the following file:
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp