clang: clang::UncommonTemplateNameStorage Class Reference
clang::UncommonTemplateNameStorage Class Reference
Implementation class used to describe either a set of overloaded template names or an already-substituted template template parameter pack.
#include "clang/AST/TemplateName.h"
Classes
struct BitsTag
Public Member Functions
unsigned size () const
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Protected Types
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions
UncommonTemplateNameStorage (Kind kind, unsigned size)
Protected Attributes
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
Implementation class used to describe either a set of overloaded template names or an already-substituted template template parameter pack.
Definition at line 47 of file TemplateName.h.
Member Enumeration Documentation
Kind
enum clang::UncommonTemplateNameStorage::Kind protected
Enumerator
Overloaded
Assumed
SubstTemplateTemplateParm
SubstTemplateTemplateParmPack
Definition at line 49 of file TemplateName.h.
Constructor & Destructor Documentation
UncommonTemplateNameStorage()
clang::UncommonTemplateNameStorage::UncommonTemplateNameStorage (Kind kind, unsigned size) inline protected
Definition at line 70 of file TemplateName.h.
References size().
Member Function Documentation
getAsAssumedTemplateName()
AssumedTemplateStorage * clang::UncommonTemplateNameStorage::getAsAssumedTemplateName () inline
Definition at line 84 of file TemplateName.h.
References Assumed.
Referenced by clang::TemplateName::getAsAssumedTemplateName(), and clang::TemplateName::getKind().
getAsOverloadedStorage()
OverloadedTemplateStorage * clang::UncommonTemplateNameStorage::getAsOverloadedStorage () inline
Definition at line 78 of file TemplateName.h.
References Overloaded.
Referenced by clang::TemplateName::getAsOverloadedTemplate(), and clang::TemplateName::getKind().
getAsSubstTemplateTemplateParm()
SubstTemplateTemplateParmStorage * clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParm () inline
Definition at line 90 of file TemplateName.h.
References SubstTemplateTemplateParm.
Referenced by clang::TemplateName::getAsSubstTemplateTemplateParm(), and clang::TemplateName::getKind().
getAsSubstTemplateTemplateParmPack()
SubstTemplateTemplateParmPackStorage * clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParmPack () inline
Definition at line 96 of file TemplateName.h.
References SubstTemplateTemplateParmPack.
Referenced by clang::TemplateName::getAsSubstTemplateTemplateParmPack().
size()
unsigned clang::UncommonTemplateNameStorage::size () const inline
Definition at line 76 of file TemplateName.h.
Referenced by clang::OverloadedTemplateStorage::end(), clang::SubstTemplateTemplateParmPackStorage::getArgumentPack(), and UncommonTemplateNameStorage().
Member Data Documentation
[union]
union { ... } clang::UncommonTemplateNameStorage
Bits
struct BitsTag clang::UncommonTemplateNameStorage::Bits
Definition at line 66 of file TemplateName.h.
PointerAlignment
void* clang::UncommonTemplateNameStorage::PointerAlignment
Definition at line 67 of file TemplateName.h.
The documentation for this class was generated from the following file:
include/clang/AST/TemplateName.h