clang: clang::Redeclarable< decl_type > Class Template Reference
clang::Redeclarable< decl_type > Class Template Reference
Provides common interface for the Decls that can be redeclared.
#include "clang/AST/Redeclarable.h"
Classes
class DeclLink
class redecl_iterator
Iterates through all the redeclarations of the same decl.
Public Types
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Member Functions
Redeclarable (const ASTContext &Ctx)
decl_type * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const decl_type * getPreviousDecl () const
decl_type * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const decl_type * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
decl_type * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const decl_type * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (decl_type *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Protected Member Functions
decl_type * getNextRedeclaration () const
Static Protected Member Functions
static DeclLink PreviousDeclLink (decl_type *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes
DeclLink RedeclLink
Points to the next redeclaration in the chain.
decl_type * First
Friends
class ASTDeclReader
class ASTDeclWriter
class IncrementalParser
Detailed Description
template<typename decl_type>
class clang::Redeclarable< decl_type >
Provides common interface for the Decls that can be redeclared.
Definition at line 84 of file Redeclarable.h.
Member Typedef Documentation
redecl_range
template<typename decl_type > using clang::Redeclarable< decl_type >::redecl_range = llvm::iterator_range<redecl_iterator>
Definition at line 292 of file Redeclarable.h.
Constructor & Destructor Documentation
Redeclarable()
template<typename decl_type > clang::Redeclarable< decl_type >::Redeclarable (const ASTContext & Ctx) inline
Definition at line 198 of file Redeclarable.h.
Member Function Documentation
getFirstDecl() [1/2]
template<typename decl_type > decl_type * clang::Redeclarable< decl_type >::getFirstDecl () inline
Return the first declaration of this declaration or itself if this is the only declaration.
Definition at line 216 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::First.
Referenced by clang::ASTContext::addCopyConstructorForExceptionObject(), clang::Sema::BuildVarTemplateInstantiation(), clang::IncrementalParser::CleanUpPTU(), clang::computeDependence(), DiagnoseFailedExplicitSpec(), DiagnoseNamespaceInlineMismatch(), clang::Sema::FinalizeDeclaration(), clang::getCanonicalForwardRedeclChain(), clang::ASTContext::getCopyConstructorForExceptionObject(), clang::ASTContext::getInlineVariableDefinitionKind(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::Sema::InstantiateVariableDefinition(), clang::Sema::InstantiateVariableInitializer(), clang::Sema::isEmptyCudaConstructor(), clang::Sema::isEmptyCudaDestructor(), clang::ASTContext::isMSStaticDataMemberInlineDefinition(), clang::Sema::MarkUnusedFileScopedDecl(), clang::Sema::MaybeSuggestAddingStaticToDecl(), clang::Sema::MergeFunctionDecl(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclReader::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::ASTDeclWriter::VisitRedeclarable(), clang::ASTDeclWriter::VisitTypedefDecl(), and clang::ASTDeclWriter::VisitVarDecl().
getFirstDecl() [2/2]
template<typename decl_type > const decl_type * clang::Redeclarable< decl_type >::getFirstDecl () const inline
Return the first declaration of this declaration or itself if this is the only declaration.
Definition at line 220 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::First.
getMostRecentDecl() [1/2]
template<typename decl_type > decl_type * clang::Redeclarable< decl_type >::getMostRecentDecl () inline
Returns the most recent (re)declaration of this declaration.
Definition at line 226 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::getFirstDecl().
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::ASTContext::adjustDeducedFunctionResultType(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::Sema::finalizeOpenMPDelayedAnalysis(), clang::ASTContext::forEachMultiversionedFunctionVersion(), clang::CodeGen::CGCXXABI::isEmittedWithConstantInitializer(), clang::Sema::MarkFunctionReferenced(), clang::Sema::MergeCompatibleFunctionDecls(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::MergeVarDecl(), clang::Sema::MergeVarDeclTypes(), clang::Sema::PerformPendingInstantiations(), ShouldRemoveFromUnused(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ASTNodeImporter::VisitFunctionTemplateDecl(), clang::ASTDeclWriter::VisitTypedefDecl(), clang::ASTDeclWriter::VisitVarDecl(), clang::ASTNodeImporter::VisitVarDecl(), and clang::ASTNodeImporter::VisitVarTemplateDecl().
getMostRecentDecl() [2/2]
template<typename decl_type > const decl_type * clang::Redeclarable< decl_type >::getMostRecentDecl () const inline
Returns the most recent (re)declaration of this declaration.
Definition at line 231 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::getFirstDecl().
getNextRedeclaration()
template<typename decl_type > decl_type * clang::Redeclarable< decl_type >::getNextRedeclaration () const inline protected
Definition at line 189 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::DeclLink::getPrevious(), and clang::Redeclarable< decl_type >::RedeclLink.
Referenced by clang::Redeclarable< decl_type >::getPreviousDecl().
getPreviousDecl() [1/2]
template<typename decl_type > decl_type * clang::Redeclarable< decl_type >::getPreviousDecl () inline
Return the previous declaration of this declaration or NULL if this is the first declaration.
Definition at line 204 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::getNextRedeclaration(), clang::Redeclarable< decl_type >::DeclLink::isFirst(), and clang::Redeclarable< decl_type >::RedeclLink.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::ASTContext::adjustDeducedFunctionResultType(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::Sema::BuildVariableInstantiation(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::DeduceVariableDeclarationType(), clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition(), dumpPreviousDeclImpl(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::RedeclarableTemplateDecl::getCommonPtr(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::ObjCInterfaceDecl::getTypeParamList(), clang::FunctionDecl::isMSExternInline(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::MergeVarDeclTypes(), OnlyHasInlineBuiltinDeclaration(), PreviousDeclsHaveMultiVersionAttribute(), redeclForcesDefMSVC(), clang::Sema::SetDeclDeleted(), ShouldWarnAboutMissingPrototype(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeImporter::VisitFunctionTemplateDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitRedeclarable(), clang::ASTNodeImporter::VisitVarTemplateDecl(), and clang::ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl().
getPreviousDecl() [2/2]
template<typename decl_type > const decl_type * clang::Redeclarable< decl_type >::getPreviousDecl () const inline
Definition at line 209 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::getPreviousDecl().
isFirstDecl()
template<typename decl_type > bool clang::Redeclarable< decl_type >::isFirstDecl () const inline
True if this is the first declaration in its redeclaration chain.
Definition at line 223 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::DeclLink::isFirst(), and clang::Redeclarable< decl_type >::RedeclLink.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::ASTDeclReader::mergeRedeclarable(), clang::ASTDeclWriter::VisitClassTemplateDecl(), clang::ASTDeclWriter::VisitFunctionTemplateDecl(), clang::ASTDeclWriter::VisitRedeclarableTemplateDecl(), and clang::ASTDeclWriter::VisitVarTemplateDecl().
LatestDeclLink()
template<typename decl_type > static DeclLink clang::Redeclarable< decl_type >::LatestDeclLink (const ASTContext & Ctx) inline static protected
Definition at line 170 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::DeclLink::LatestLink.
PreviousDeclLink()
template<typename decl_type > static DeclLink clang::Redeclarable< decl_type >::PreviousDeclLink (decl_type * D) inline static protected
Definition at line 166 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::DeclLink::PreviousLink.
Referenced by clang::ASTDeclReader::mergeRedeclarable(), and clang::ASTDeclReader::VisitRedeclarable().
redecls()
template<typename decl_type > redecl_range clang::Redeclarable< decl_type >::redecls () const inline
Returns an iterator range for all the redeclarations of the same decl.
It will iterate at least once (when this decl is the only one).
Definition at line 296 of file Redeclarable.h.
Referenced by CheckTargetCausesMultiVersioning(), clang::VarDecl::getDefinition(), clang::ASTContext::getInlineVariableDefinitionKind(), hasAnyExplicitStorageClass(), clang::VarDecl::hasDefinition(), clang::Sema::InheritedConstructorInfo::InheritedConstructorInfo(), clang::Sema::isAcceptableTagRedeclaration(), clang::Sema::MarkFunctionReferenced(), clang::Sema::MergeFunctionDecl(), clang::Redeclarable< decl_type >::redecls_begin(), clang::Redeclarable< decl_type >::redecls_end(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), and clang::Sema::UpdateExceptionSpec().
redecls_begin()
template<typename decl_type > redecl_iterator clang::Redeclarable< decl_type >::redecls_begin () const inline
Definition at line 302 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::redecls().
redecls_end()
template<typename decl_type > redecl_iterator clang::Redeclarable< decl_type >::redecls_end () const inline
Definition at line 303 of file Redeclarable.h.
References clang::Redeclarable< decl_type >::redecls().
Referenced by clang::Sema::MergeFunctionDecl().
setPreviousDecl()
template<typename decl_type > void clang::Redeclarable< decl_type >::setPreviousDecl (decl_type * PrevDecl)
Set the previous declaration.
If PrevDecl is NULL, set this as the first and only declaration.
Definition at line 4674 of file Decl.h.
References clang::First, clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_Tag, and clang::Decl::IDNS_Type.
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::ASTContext::addTranslationUnitDecl(), clang::Sema::BuildUsingShadowDecl(), clang::Sema::CheckClassTemplate(), clang::Sema::MergeTypedefNameDecl(), clang::Sema::MergeVarDecl(), clang::ASTNodeImporter::VisitClassTemplateDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ASTNodeImporter::VisitFunctionTemplateDecl(), clang::ASTNodeImporter::VisitVarDecl(), and clang::ASTNodeImporter::VisitVarTemplateDecl().
Friends And Related Symbol Documentation
ASTDeclReader
template<typename decl_type > friend class ASTDeclReader friend
Definition at line 194 of file Redeclarable.h.
ASTDeclWriter
template<typename decl_type > friend class ASTDeclWriter friend
Definition at line 195 of file Redeclarable.h.
IncrementalParser
template<typename decl_type > friend class IncrementalParser friend
Definition at line 196 of file Redeclarable.h.
Member Data Documentation
First
template<typename decl_type > decl_type* clang::Redeclarable< decl_type >::First protected
Definition at line 187 of file Redeclarable.h.
Referenced by clang::ASTDeclReader::attachPreviousDeclImpl(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::ASTDeclReader::mergeRedeclarable(), and clang::ASTDeclReader::VisitRedeclarable().
RedeclLink
template<typename decl_type > DeclLink clang::Redeclarable< decl_type >::RedeclLink protected
Points to the next redeclaration in the chain.
If isFirst() is false, this is a link to the previous declaration of this same Decl. If isFirst() is true, this is the first declaration and Link points to the latest declaration. For example:
#1 int f(int x, int y = 1); // <pointer to #3, true> #2 int f(int x = 0, int y); // <pointer to #1, false> #3 int f(int x, int y) { return x + y; } // <pointer to #2, false>
If there is only one declaration, it is <pointer to self, true>
Definition at line 185 of file Redeclarable.h.
Referenced by clang::ASTDeclReader::attachLatestDeclImpl(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::ASTDeclReader::getMostRecentDeclImpl(), clang::Redeclarable< decl_type >::getNextRedeclaration(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::Redeclarable< decl_type >::isFirstDecl(), clang::ASTDeclReader::markIncompleteDeclChainImpl(), clang::ASTDeclReader::mergeRedeclarable(), and clang::ASTDeclReader::VisitRedeclarable().
The documentation for this class was generated from the following files:
include/clang/AST/Redeclarable.h
include/clang/AST/Decl.h