clang: clang::DeclarationNameLoc Class Reference
clang::DeclarationNameLoc Class Reference
DeclarationNameLoc - Additional source/type location info for a declaration name.
#include "clang/AST/DeclarationName.h"
Public Member Functions
DeclarationNameLoc (DeclarationName Name)
DeclarationNameLoc ()
TypeSourceInfo * getNamedTypeInfo () const
Returns the source type info.
SourceLocation getCXXOperatorNameBeginLoc () const
Return the beginning location of the getCXXOperatorNameRange() range.
SourceLocation getCXXOperatorNameEndLoc () const
Return the end location of the getCXXOperatorNameRange() range.
SourceRange getCXXOperatorNameRange () const
Return the range of the operator name (without the operator keyword).
SourceLocation getCXXLiteralOperatorNameLoc () const
Return the location of the literal operator name (without the operator keyword).
Static Public Member Functions
static DeclarationNameLoc makeNamedTypeLoc (TypeSourceInfo *TInfo)
Construct location information for a constructor, destructor or conversion operator.
static DeclarationNameLoc makeCXXOperatorNameLoc (SourceLocation BeginLoc, SourceLocation EndLoc)
Construct location information for a non-literal C++ operator.
static DeclarationNameLoc makeCXXOperatorNameLoc (SourceRange Range)
Construct location information for a non-literal C++ operator.
static DeclarationNameLoc makeCXXLiteralOperatorNameLoc (SourceLocation Loc)
Construct location information for a literal C++ operator.
Detailed Description
DeclarationNameLoc - Additional source/type location info for a declaration name.
Needs a DeclarationName in order to be interpreted correctly.
Definition at line 659 of file DeclarationName.h.
Constructor & Destructor Documentation
DeclarationNameLoc() [1/2]
DeclarationNameLoc::DeclarationNameLoc (DeclarationName Name)
Definition at line 387 of file DeclarationName.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::Identifier, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
DeclarationNameLoc() [2/2]
clang::DeclarationNameLoc::DeclarationNameLoc () inline
Definition at line 705 of file DeclarationName.h.
References memset().
Member Function Documentation
getCXXLiteralOperatorNameLoc()
SourceLocation clang::DeclarationNameLoc::getCXXLiteralOperatorNameLoc () const inline
Return the location of the literal operator name (without the operator keyword).
Assumes that the object stores location information of a literal operator.
Definition at line 732 of file DeclarationName.h.
Referenced by clang::ASTRecordWriter::AddDeclarationNameLoc(), and clang::DeclarationNameInfo::getCXXLiteralOperatorNameLoc().
getCXXOperatorNameBeginLoc()
SourceLocation clang::DeclarationNameLoc::getCXXOperatorNameBeginLoc () const inline
Return the beginning location of the getCXXOperatorNameRange() range.
Definition at line 712 of file DeclarationName.h.
Referenced by clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr().
getCXXOperatorNameEndLoc()
SourceLocation clang::DeclarationNameLoc::getCXXOperatorNameEndLoc () const inline
Return the end location of the getCXXOperatorNameRange() range.
Definition at line 717 of file DeclarationName.h.
Referenced by clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr().
getCXXOperatorNameRange()
SourceRange clang::DeclarationNameLoc::getCXXOperatorNameRange () const inline
Return the range of the operator name (without the operator keyword).
Assumes that the object stores location information of a (non-literal) operator.
Definition at line 724 of file DeclarationName.h.
Referenced by clang::ASTRecordWriter::AddDeclarationNameLoc(), and clang::DeclarationNameInfo::getCXXOperatorNameRange().
getNamedTypeInfo()
TypeSourceInfo * clang::DeclarationNameLoc::getNamedTypeInfo () const inline
Returns the source type info.
Assumes that the object stores location information of a constructor, destructor or conversion operator.
Definition at line 709 of file DeclarationName.h.
Referenced by clang::ASTRecordWriter::AddDeclarationNameLoc(), clang::DeclarationNameInfo::containsUnexpandedParameterPack(), clang::DeclarationNameInfo::getNamedTypeInfo(), clang::DeclarationNameInfo::isInstantiationDependent(), and clang::DeclarationNameInfo::printName().
makeCXXLiteralOperatorNameLoc()
static DeclarationNameLoc clang::DeclarationNameLoc::makeCXXLiteralOperatorNameLoc (SourceLocation Loc) inline static
Construct location information for a literal C++ operator.
Definition at line 758 of file DeclarationName.h.
Referenced by clang::ASTRecordReader::readDeclarationNameLoc().
makeCXXOperatorNameLoc() [1/2]
static DeclarationNameLoc clang::DeclarationNameLoc::makeCXXOperatorNameLoc (SourceLocation BeginLoc, SourceLocation EndLoc) inline static
Construct location information for a non-literal C++ operator.
Definition at line 745 of file DeclarationName.h.
Referenced by clang::ASTContext::getNameForTemplate(), clang::ASTRecordReader::readDeclarationNameLoc(), and clang::Sema::startLambdaDefinition().
makeCXXOperatorNameLoc() [2/2]
static DeclarationNameLoc clang::DeclarationNameLoc::makeCXXOperatorNameLoc (SourceRange Range) inline static
Construct location information for a non-literal C++ operator.
Definition at line 751 of file DeclarationName.h.
makeNamedTypeLoc()
static DeclarationNameLoc clang::DeclarationNameLoc::makeNamedTypeLoc (TypeSourceInfo * TInfo) inline static
Construct location information for a constructor, destructor or conversion operator.
Definition at line 738 of file DeclarationName.h.
Referenced by addBlockPointerConversion(), addFunctionPointerConversion(), and clang::ASTRecordReader::readDeclarationNameLoc().
Member Data Documentation
CXXLiteralOperatorName
struct CXXLitOpName clang::DeclarationNameLoc::CXXLiteralOperatorName
Definition at line 688 of file DeclarationName.h.
CXXOperatorName
struct CXXOpName clang::DeclarationNameLoc::CXXOperatorName
Definition at line 687 of file DeclarationName.h.
NamedType
struct NT clang::DeclarationNameLoc::NamedType
Definition at line 686 of file DeclarationName.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclarationName.h
lib/AST/DeclarationName.cpp