clang: clang::CanQual< typename > Class Template Reference
clang::CanQual< typename > Class Template Reference
Represents a canonical, potentially-qualified type.
#include "clang/AST/CanonicalType.h"
Public Member Functions
CanQual ()=default
Constructs a NULL canonical type.
template<typename U >
CanQual (const CanQual< U > &Other, std::enable_if_t< std::is_base_of< T, U >::value, int >=0)
Converting constructor that permits implicit upcasting of canonical type pointers.
const T * getTypePtr () const
Retrieve the underlying type pointer, which refers to a canonical type.
const T * getTypePtrOrNull () const
Retrieve the underlying type pointer, which refers to a canonical type, or nullptr.
operator QualType () const
Implicit conversion to a qualified type.
operator bool () const
Implicit conversion to bool.
bool isNull () const
SplitQualType split () const
template<typename U >
CanProxy< U > getAs () const
Retrieve a canonical type pointer with a different static type, upcasting or downcasting as needed.
template<typename U >
CanProxy< U > castAs () const
CanProxy< T > operator-> () const
Overloaded arrow operator that produces a canonical type proxy.
Qualifiers getQualifiers () const
Retrieve all qualifiers.
unsigned getCVRQualifiers () const
Retrieve the const/volatile/restrict qualifiers.
bool hasQualifiers () const
Determines whether this type has any qualifiers.
bool isConstQualified () const
bool isVolatileQualified () const
bool isRestrictQualified () const
bool isCanonicalAsParam () const
Determines if this canonical type is furthermore canonical as a parameter.
CanQual< T > getUnqualifiedType () const
Retrieve the unqualified form of this type.
QualType withConst () const
Retrieves a version of this type with const applied.
bool isMoreQualifiedThan (CanQual< T > Other) const
Determines whether this canonical type is more qualified than the Other canonical type.
bool isAtLeastAsQualifiedAs (CanQual< T > Other) const
Determines whether this canonical type is at least as qualified as the Other canonical type.
CanQual< Type > getNonReferenceType () const
If the canonical type is a reference type, returns the type that it refers to; otherwise, returns the type itself.
void * getAsOpaquePtr () const
Retrieve the internal representation of this canonical type.
void dump () const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static CanQual< T > getFromOpaquePtr (void *Ptr)
Construct a canonical type from its internal representation.
static CanQual< T > CreateUnsafe (QualType Other)
Builds a canonical type from a QualType.
Detailed Description
template<typename>
class clang::CanQual< typename >
Represents a canonical, potentially-qualified type.
The CanQual template is a lightweight smart pointer that provides access to the canonical representation of a type, where all typedefs and other syntactic sugar has been eliminated. A CanQualType may also have various qualifiers (const, volatile, restrict) attached to it.
The template type parameter T is one of the Type classes (PointerType, BuiltinType, etc.). The type stored within CanQual<T> will be of that type (or some subclass of that type). The typedef CanQualType is just a shorthand for CanQual<Type>.
An instance of CanQual<T> can be implicitly converted to a CanQual when T is derived from U, which essentially provides an implicit upcast. For example, CanQual<LValueReferenceType> can be converted to CanQual<ReferenceType>. Note that any CanQual type can be implicitly converted to a QualType, but the reverse operation requires a call to ASTContext::getCanonicalType().
Definition at line 32 of file CodeGenTypes.h.
Constructor & Destructor Documentation
CanQual() [1/2]
template<typename > clang::CanQual< typename >::CanQual () default
Constructs a NULL canonical type.
CanQual() [2/2]
template<typename > template<typename U > clang::CanQual< typename >::CanQual (const CanQual< U > & Other, std::enable_if_t< std::is_base_of< T, U >::value, int > = 0)
Converting constructor that permits implicit upcasting of canonical type pointers.
Member Function Documentation
castAs()
template<typename T > template<typename U > CanProxy< U > clang::CanQual< T >::castAs () const
Definition at line 668 of file CanonicalType.h.
References clang::CanQual< typename >::CreateUnsafe(), clang::CanQual< typename >::getTypePtr(), clang::CanQual< typename >::isNull(), and clang::CanProxyBase< T >::Stored.
Referenced by clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), emitReduceInitFunction(), and clang::Sema::IsFunctionConversion().
CreateUnsafe()
template<typename T > CanQual< T > clang::CanQual< T >::CreateUnsafe (QualType Other) static
Builds a canonical type from a QualType.
This routine is inherently unsafe, because it requires the user to ensure that the given type is a canonical type with the correct
Definition at line 642 of file CanonicalType.h.
References clang::QualType::getTypePtr(), clang::QualType::isCanonical(), clang::QualType::isNull(), and clang::Result.
Referenced by clang::CanQual< typename >::castAs(), clang::CanQual< typename >::getAs(), and clang::CanQual< typename >::getUnqualifiedType().
dump()
template<typename > void clang::CanQual< typename >::dump () const inline
Definition at line 194 of file CanonicalType.h.
getAs()
template<typename T > template<typename U > CanProxy< U > clang::CanQual< T >::getAs () const
Retrieve a canonical type pointer with a different static type, upcasting or downcasting as needed.
The getAs() function is typically used to try to downcast to a more specific (canonical) type in the type system. For example:
void f(CanQual<Type> T) {
  if (CanQual<PointerType> Ptr = T->getAs<PointerType>()) {
    // look at Ptr's pointee type
  }
}
Returns
A proxy pointer to the same type, but with the specified static type (U). If the dynamic type is not the specified static type or a derived class thereof, a NULL canonical type.
Definition at line 653 of file CanonicalType.h.
References clang::CanQual< typename >::CreateUnsafe(), clang::CanQual< typename >::getTypePtr(), clang::CanQual< typename >::isNull(), and clang::CanProxyBase< T >::Stored.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCXXMethodDeclaration(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodType(), clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(), CheckOperatorNewDeleteTypes(), DiagnoseBadConversion(), GetFormalType(), IsModifiable(), MatchesFriend(), MightInstantiateTo(), setCUDAKernelCallingConvention(), and TryStaticDowncast().
getAsOpaquePtr()
template<typename > void * clang::CanQual< typename >::getAsOpaquePtr () const inline
Retrieve the internal representation of this canonical type.
Definition at line 182 of file CanonicalType.h.
Referenced by clang::DeclarationNameTable::getCXXConstructorName(), clang::DeclarationNameTable::getCXXConversionFunctionName(), clang::DeclarationNameTable::getCXXDestructorName(), llvm::DenseMapInfo< clang::CanQualType >::getHashValue(), and clang::CanQual< typename >::Profile().
getCVRQualifiers()
template<typename > unsigned clang::CanQual< typename >::getCVRQualifiers () const inline
Retrieve the const/volatile/restrict qualifiers.
Definition at line 132 of file CanonicalType.h.
Referenced by clang::CXXConstructorDecl::isCopyOrMoveConstructor().
getFromOpaquePtr()
template<typename T > CanQual< T > clang::CanQual< T >::getFromOpaquePtr (void * Ptr) static
Construct a canonical type from its internal representation.
Definition at line 633 of file CanonicalType.h.
References clang::QualType::getFromOpaquePtr(), and clang::Result.
Referenced by llvm::PointerLikeTypeTraits< clang::CanQual< T > >::getFromVoidPointer().
getNonReferenceType()
template<typename T > CanQual< Type > clang::CanQual< T >::getNonReferenceType () const inline
If the canonical type is a reference type, returns the type that it refers to; otherwise, returns the type itself.
Definition at line 625 of file CanonicalType.h.
References clang::CanProxyBase< T >::getAs().
Referenced by clang::ConversionFixItGenerator::compareTypesSimple().
getQualifiers()
template<typename > Qualifiers clang::CanQual< typename >::getQualifiers () const inline
Retrieve all qualifiers.
Definition at line 129 of file CanonicalType.h.
Referenced by clang::Sema::BuildFieldReferenceExpr(), DiagnoseBadConversion(), clang::ASTContext::getCanonicalFunctionResultType(), clang::ASTContext::InitBuiltinTypes(), InitCatchParam(), IsModifiable(), LookupMemberExpr(), and MightInstantiateTo().
getTypePtr()
template<typename > const T * clang::CanQual< typename >::getTypePtr () const inline
Retrieve the underlying type pointer, which refers to a canonical type.
The underlying pointer must not be nullptr.
Definition at line 83 of file CanonicalType.h.
References clang::cast().
Referenced by clang::Sema::ActOnTag(), appendParameterTypes(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), clang::CanQual< typename >::castAs(), CheckImplicitConversion(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::RequiredArgs::forPrototype(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::CanQual< typename >::getAs(), clang::CodeGen::CodeGenTBAA::getBaseTypeInfo(), clang::ASTContext::getIntegerTypeOrder(), GetKeyForBase(), llvm::simplify_type< ::clang::CanQual< T > >::getSimplifiedValue(), clang::CodeGen::CodeGenTBAA::getTBAAStructInfo(), clang::CodeGen::CodeGenTBAA::getTypeInfo(), clang::CanProxyBase< T >::getTypePtr(), clang::ASTContext::hasSameUnqualifiedType(), IsImplicitBoolFloatConversion(), and matchTypes().
getTypePtrOrNull()
template<typename > const T * clang::CanQual< typename >::getTypePtrOrNull () const inline
Retrieve the underlying type pointer, which refers to a canonical type, or nullptr.
Definition at line 87 of file CanonicalType.h.
getUnqualifiedType()
template<typename T > CanQual< T > clang::CanQual< T >::getUnqualifiedType () const inline
Retrieve the unqualified form of this type.
Definition at line 620 of file CanonicalType.h.
References clang::CanQual< typename >::CreateUnsafe(), and clang::CanProxyBase< T >::Stored.
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::AddConversionCandidate(), clang::CodeGen::CodeGenTypes::arrangeFreeFunctionType(), arrangeLLVMFunctionInfo(), clang::Sema::AttachBaseSpecifiers(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckConstructor(), clang::Sema::CheckDerivedToBaseConversion(), clang::CheckEquivalentExceptionSpecImpl(), clang::Sema::CheckObjCARCUnavailableWeakConversion(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckSubtractionOperands(), clang::ConversionFixItGenerator::compareTypesSimple(), DiagnoseBadConversion(), clang::Sema::DiagnosePropertyAccessorMismatch(), clang::Sema::ExtractUnqualifiedFunctionType(), findDirectBaseWithType(), clang::ASTContext::getCanonicalFunctionResultType(), clang::DeclarationNameTable::getCXXConstructorName(), clang::DeclarationNameTable::getCXXDestructorName(), clang::ento::MemRegionManager::getElementRegion(), GetReturnType(), clang::ASTContext::InitBuiltinTypes(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::CXXConstructorDecl::isSpecializationCopyingObject(), IsStringInit(), matchTypes(), clang::ASTContext::mergeFunctionTypes(), NoteIndirectBases(), OpenCLArithmeticConversions(), TryStaticDowncast(), TryUserDefinedConversion(), and clang::Sema::UsualArithmeticConversions().
hasQualifiers()
template<typename > bool clang::CanQual< typename >::hasQualifiers () const inline
Determines whether this type has any qualifiers.
Definition at line 135 of file CanonicalType.h.
isAtLeastAsQualifiedAs()
template<typename > bool clang::CanQual< typename >::isAtLeastAsQualifiedAs (CanQual< T > Other) const inline
Determines whether this canonical type is at least as qualified as the Other canonical type.
Definition at line 173 of file CanonicalType.h.
Referenced by clang::ConversionFixItGenerator::compareTypesSimple(), DiagnoseBadConversion(), and TryStaticDowncast().
isCanonicalAsParam()
template<typename > bool clang::CanQual< typename >::isCanonicalAsParam () const inline
Determines if this canonical type is furthermore canonical as a parameter.
The parameter-canonicalization process decays arrays to pointers and drops top-level qualifiers.
Definition at line 152 of file CanonicalType.h.
isConstQualified()
template<typename > bool clang::CanQual< typename >::isConstQualified () const inline
Definition at line 137 of file CanonicalType.h.
Referenced by IsModifiable(), and clang::cross_tu::shouldImport().
isMoreQualifiedThan()
template<typename > bool clang::CanQual< typename >::isMoreQualifiedThan (CanQual< T > Other) const inline
Determines whether this canonical type is more qualified than the Other canonical type.
Definition at line 167 of file CanonicalType.h.
isNull()
template<typename > bool clang::CanQual< typename >::isNull () const inline
Definition at line 97 of file CanonicalType.h.
Referenced by clang::CanQual< typename >::castAs(), clang::CanQual< typename >::getAs(), clang::ASTContext::InitBuiltinTypes(), and clang::CanQual< typename >::operator bool().
isRestrictQualified()
template<typename > bool clang::CanQual< typename >::isRestrictQualified () const inline
Definition at line 145 of file CanonicalType.h.
isVolatileQualified()
template<typename > bool clang::CanQual< typename >::isVolatileQualified () const inline
Definition at line 141 of file CanonicalType.h.
Referenced by AddBuiltinAssignmentOperatorCandidates(), and clang::Expr::isUnusedResultAWarning().
operator bool()
template<typename > clang::CanQual< typename >::operator bool () const inline explicit
Implicit conversion to bool.
Definition at line 95 of file CanonicalType.h.
References clang::CanQual< typename >::isNull().
operator QualType()
template<typename > clang::CanQual< typename >::operator QualType () const inline
Implicit conversion to a qualified type.
Definition at line 92 of file CanonicalType.h.
operator->()
template<typename T > CanProxy< T > clang::CanQual< T >::operator-> () const
Overloaded arrow operator that produces a canonical type proxy.
Definition at line 677 of file CanonicalType.h.
Profile()
template<typename > void clang::CanQual< typename >::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 196 of file CanonicalType.h.
References clang::CanQual< typename >::getAsOpaquePtr().
Referenced by clang::CodeGen::CGFunctionInfo::Profile(), and clang::CodeGen::CGFunctionInfo::Profile().
split()
template<typename > SplitQualType clang::CanQual< typename >::split () const inline
Definition at line 101 of file CanonicalType.h.
Referenced by clang::ASTContext::getConstantArrayType(), clang::ASTContext::getDependentSizedArrayType(), clang::ASTContext::getIncompleteArrayType(), and clang::ASTContext::getVariableArrayType().
withConst()
template<typename > QualType clang::CanQual< typename >::withConst () const inline
Retrieves a version of this type with const applied.
Note that this does not always yield a canonical type.
Definition at line 161 of file CanonicalType.h.
References clang::QualType::withConst().
Referenced by clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnOpenMPRegionStart(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildPredefinedExpr(), clang::SYCLUniqueStableNameExpr::Create(), clang::SYCLUniqueStableNameExpr::CreateEmpty(), clang::ASTContext::getCFConstantStringDecl(), and LookupStdSourceLocationImpl().
The documentation for this class was generated from the following files:
include/clang/AST/CanonicalType.h
include/clang/AST/DeclarationName.h
include/clang/AST/Type.h
lib/CodeGen/CodeGenTypes.h