clang: clang::ConstructorInitializerConstructionContext Class Reference
clang::ConstructorInitializerConstructionContext Class Reference
#include "clang/Analysis/ConstructionContext.h"
Public Member Functions
const CXXCtorInitializer * getCXXCtorInitializer () const
const ArrayInitLoopExpr * getArrayInitLoop () const override
Public Member Functions inherited from clang::ConstructionContext
Kind getKind () const
virtual ~ConstructionContext ()=default
Static Public Member Functions
static bool classof (const ConstructionContext *CC)
Static Public Member Functions inherited from clang::ConstructionContext
static const ConstructionContext * createFromLayers (BumpVectorContext &C, const ConstructionContextLayer *TopLayer)
Consume the construction context layer, together with its parent layers, and wrap it up into a complete construction context.
Protected Member Functions
ConstructorInitializerConstructionContext (ConstructionContext::Kind K, const CXXCtorInitializer *I)
Protected Member Functions inherited from clang::ConstructionContext
ConstructionContext (Kind K)
Additional Inherited Members
Public Types inherited from clang::ConstructionContext
enum Kind {
SimpleVariableKind , CXX17ElidedCopyVariableKind , VARIABLE_BEGIN = SimpleVariableKind , VARIABLE_END = CXX17ElidedCopyVariableKind ,
SimpleConstructorInitializerKind , CXX17ElidedCopyConstructorInitializerKind , INITIALIZER_BEGIN = SimpleConstructorInitializerKind , INITIALIZER_END = CXX17ElidedCopyConstructorInitializerKind ,
NewAllocatedObjectKind , SimpleTemporaryObjectKind , ElidedTemporaryObjectKind , TEMPORARY_BEGIN = SimpleTemporaryObjectKind ,
TEMPORARY_END = ElidedTemporaryObjectKind , SimpleReturnedValueKind , CXX17ElidedCopyReturnedValueKind , RETURNED_VALUE_BEGIN = SimpleReturnedValueKind ,
RETURNED_VALUE_END = CXX17ElidedCopyReturnedValueKind , ArgumentKind , LambdaCaptureKind
}
Protected Attributes inherited from clang::ConstructionContext
Kind K
Detailed Description
Definition at line 388 of file ConstructionContext.h.
Constructor & Destructor Documentation
ConstructorInitializerConstructionContext()
clang::ConstructorInitializerConstructionContext::ConstructorInitializerConstructionContext (ConstructionContext::Kind K, const CXXCtorInitializer * I) inline explicit protected
Definition at line 392 of file ConstructionContext.h.
References classof().
Member Function Documentation
classof()
static bool clang::ConstructorInitializerConstructionContext::classof (const ConstructionContext * CC) inline static
Definition at line 406 of file ConstructionContext.h.
References clang::ConstructionContext::getKind(), clang::ConstructionContext::INITIALIZER_BEGIN, and clang::ConstructionContext::INITIALIZER_END.
Referenced by ConstructorInitializerConstructionContext().
getArrayInitLoop()
const ArrayInitLoopExpr * clang::ConstructorInitializerConstructionContext::getArrayInitLoop () const inline override virtual
Reimplemented from clang::ConstructionContext.
Definition at line 402 of file ConstructionContext.h.
References clang::CXXCtorInitializer::getInit().
getCXXCtorInitializer()
const CXXCtorInitializer * clang::ConstructorInitializerConstructionContext::getCXXCtorInitializer () const inline
Definition at line 400 of file ConstructionContext.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/ConstructionContext.h