clang: clang::format::NamespaceEndCommentsFixer Class Reference
clang::format::NamespaceEndCommentsFixer Class Reference
#include "/root/llvm-project/clang/lib/Format/NamespaceEndCommentsFixer.h"
Public Member Functions
NamespaceEndCommentsFixer (const Environment &Env, const FormatStyle &Style)
std::pair< tooling::Replacements, unsigned > analyze (TokenAnnotator &Annotator, SmallVectorImpl< AnnotatedLine * > &AnnotatedLines, FormatTokenLexer &Tokens) override
Public Member Functions inherited from clang::format::TokenAnalyzer
TokenAnalyzer (const Environment &Env, const FormatStyle &Style)
std::pair< tooling::Replacements, unsigned > process ()
Public Member Functions inherited from clang::format::UnwrappedLineConsumer
virtual ~UnwrappedLineConsumer ()
Additional Inherited Members
Protected Member Functions inherited from clang::format::TokenAnalyzer
void consumeUnwrappedLine (const UnwrappedLine &TheLine) override
void finishRun () override
Protected Attributes inherited from clang::format::TokenAnalyzer
FormatStyle Style
const Environment & Env
AffectedRangeManager AffectedRangeMgr
SmallVector< SmallVector< UnwrappedLine, 16 >, 2 > UnwrappedLines
encoding::Encoding Encoding
Detailed Description
Definition at line 33 of file NamespaceEndCommentsFixer.h.
Constructor & Destructor Documentation
NamespaceEndCommentsFixer()
clang::format::NamespaceEndCommentsFixer::NamespaceEndCommentsFixer (const Environment & Env, const FormatStyle & Style)
Definition at line 277 of file NamespaceEndCommentsFixer.cpp.
Member Function Documentation
analyze()
std::pair< tooling::Replacements, unsigned > clang::format::NamespaceEndCommentsFixer::analyze (TokenAnnotator & Annotator, SmallVectorImpl< AnnotatedLine * > & AnnotatedLines, FormatTokenLexer & Tokens) override virtual
Implements clang::format::TokenAnalyzer.
Definition at line 281 of file NamespaceEndCommentsFixer.cpp.
References clang::format::TokenAnalyzer::AffectedRangeMgr, clang::format::AffectedRangeManager::computeAffectedLines(), clang::format::TokenAnalyzer::Env, clang::format::FormatToken::Finalized, clang::First, clang::format::AnnotatedLine::First, clang::format::getNamespaceToken(), clang::format::getNamespaceTokenText(), clang::format::Environment::getSourceManager(), clang::format::FormatToken::is(), clang::format::FormatToken::isNot(), clang::format::AnnotatedLine::MatchingOpeningBlockLineIndex, clang::format::FormatToken::NewlinesBefore, clang::format::FormatToken::Next, SIZE_MAX, Tok, and clang::format::FormatToken::TokenText.
The documentation for this class was generated from the following files:
lib/Format/NamespaceEndCommentsFixer.h
lib/Format/NamespaceEndCommentsFixer.cpp