clang: clang::Mergeable< decl_type > Class Template Reference
clang::Mergeable< decl_type > Class Template Reference
Provides common interface for the Decls that cannot be redeclared, but can be merged if the same declaration is brought in from multiple modules.
#include "clang/AST/Redeclarable.h"
Public Member Functions
Mergeable ()=default
decl_type * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const decl_type * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
Returns true if this is the first declaration.
Detailed Description
template<typename decl_type>
class clang::Mergeable< decl_type >
Provides common interface for the Decls that cannot be redeclared, but can be merged if the same declaration is brought in from multiple modules.
Definition at line 314 of file Redeclarable.h.
Constructor & Destructor Documentation
Mergeable()
template<typename decl_type > clang::Mergeable< decl_type >::Mergeable () default
Member Function Documentation
getFirstDecl() [1/2]
template<typename decl_type > decl_type * clang::Mergeable< decl_type >::getFirstDecl () inline
Return the first declaration of this declaration or itself if this is the only declaration.
Definition at line 320 of file Redeclarable.h.
References clang::cast(), and clang::getPrimaryMergedDecl().
Referenced by dumpPreviousDeclImpl(), and clang::Mergeable< decl_type >::isFirstDecl().
getFirstDecl() [2/2]
template<typename decl_type > const decl_type * clang::Mergeable< decl_type >::getFirstDecl () const inline
Return the first declaration of this declaration or itself if this is the only declaration.
Definition at line 329 of file Redeclarable.h.
References clang::cast(), and clang::getPrimaryMergedDecl().
isFirstDecl()
template<typename decl_type > bool clang::Mergeable< decl_type >::isFirstDecl () const inline
Returns true if this is the first declaration.
Definition at line 337 of file Redeclarable.h.
References clang::Mergeable< decl_type >::getFirstDecl().
The documentation for this class was generated from the following file:
include/clang/AST/Redeclarable.h