clang: clang::driver::tools::ClangAs Class Reference
clang::driver::tools::ClangAs Class Reference
Clang integrated assembler tool.
#include "/root/llvm-project/clang/lib/Driver/ToolChains/Clang.h"
Public Member Functions
ClangAs (const ToolChain &TC)
void AddMIPSTargetArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
void AddX86TargetArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
void AddRISCVTargetArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
bool hasGoodDiagnostics () const override
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
bool hasIntegratedAssembler () const override
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Clang integrated assembler tool.
Definition at line 122 of file Clang.h.
Constructor & Destructor Documentation
ClangAs()
clang::driver::tools::ClangAs::ClangAs (const ToolChain & TC) inline
Definition at line 124 of file Clang.h.
Member Function Documentation
AddMIPSTargetArgs()
void ClangAs::AddMIPSTargetArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
Definition at line 7815 of file Clang.cpp.
References clang::driver::tools::mips::getMipsCPUAndABI(), clang::driver::Tool::getToolChain(), and clang::driver::ToolChain::getTriple().
Referenced by ConstructJob().
AddRISCVTargetArgs()
void ClangAs::AddRISCVTargetArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
Definition at line 7843 of file Clang.cpp.
References clang::driver::tools::riscv::getRISCVABI(), clang::driver::Tool::getToolChain(), and clang::driver::ToolChain::getTriple().
Referenced by ConstructJob().
AddX86TargetArgs()
void ClangAs::AddX86TargetArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
Definition at line 7826 of file Clang.cpp.
References clang::driver::tools::addX86AlignBranchArgs(), clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and clang::driver::Tool::getToolChain().
Referenced by ConstructJob().
ConstructJob()
void ClangAs::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 7852 of file Clang.cpp.
References addDebugCompDirArg(), addDebugObjectName(), addDebugPrefixMapArg(), AddMIPSTargetArgs(), AddRISCVTargetArgs(), AddX86TargetArgs(), clang::driver::ResponseFileSupport::AtFileUTF8(), clang::C, clang::driver::Driver::CC1Main, clang::driver::Driver::CCGenDiagnostics, clang::driver::tools::claimNoWarnArgs(), CollectArgsForIntegratedAssembler(), clang::codegenoptions::DebugInfoConstructor, DwarfVersionNum(), EscapeSpacesAndBackslashes(), clang::driver::tools::Clang::getBaseInputName(), clang::getClangFullVersion(), clang::driver::Driver::getClangProgramPath(), clang::driver::tools::getCPUName(), clang::driver::tools::getDebugFissionKind(), clang::driver::ToolChain::GetDefaultDwarfVersion(), clang::driver::ToolChain::getDriver(), getDwarfNArg(), clang::driver::ToolChain::getEffectiveTriple(), clang::driver::InputInfo::getFilename(), getTargetFeatures(), clang::driver::ToolChain::getTargetVariantTriple(), clang::driver::Tool::getToolChain(), clang::driver::ToolChain::getTriple(), clang::driver::Action::getType(), handleAMDGPUCodeObjectVersionOptions(), clang::driver::Action::InputClass, clang::driver::InputInfo::isFilename(), clang::codegenoptions::NoDebugInfo, clang::driver::tools::ParseDebugDefaultVersion(), clang::driver::tools::ParsePICArgs(), RelocationModelName(), RenderDebugEnablingArgs(), RenderDebugInfoCompressionArgs(), renderDwarfFormat(), clang::driver::tools::Split, and clang::driver::tools::SplitDebugName().
hasGoodDiagnostics()
bool clang::driver::tools::ClangAs::hasGoodDiagnostics () const inline override virtual
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
Reimplemented from clang::driver::Tool.
Definition at line 132 of file Clang.h.
hasIntegratedAssembler()
bool clang::driver::tools::ClangAs::hasIntegratedAssembler () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 133 of file Clang.h.
hasIntegratedCPP()
bool clang::driver::tools::ClangAs::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 134 of file Clang.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Clang.h
lib/Driver/ToolChains/Clang.cpp