clang: clang::OMPDependClause Class Reference
clang::OMPDependClause Class Reference final
This represents implicit clause 'depend' for the '#pragma omp task' directive.
#include "clang/AST/OpenMPClause.h"
Classes
struct DependDataTy
Public Member Functions
OpenMPDependClauseKind getDependencyKind () const
Get dependency type.
SourceLocation getDependencyLoc () const
Get dependency type location.
SourceLocation getColonLoc () const
Get colon location.
SourceLocation getOmpAllMemoryLoc () const
Get 'omp_all_memory' location.
Expr * getModifier ()
Return optional depend modifier.
const Expr * getModifier () const
unsigned getNumLoops () const
Get number of loops associated with the clause.
void setLoopData (unsigned NumLoop, Expr *Cnt)
Set the loop data for the depend clauses with 'sink|source' kind of dependency.
Expr * getLoopData (unsigned NumLoop)
Get the loop data.
const Expr * getLoopData (unsigned NumLoop) const
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPDependClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPDependClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, DependDataTy Data, Expr *DepModifier, ArrayRef< Expr * > VL, unsigned NumLoops)
Creates clause with a list of variables VL.
static OMPDependClause * CreateEmpty (const ASTContext &C, unsigned N, unsigned NumLoops)
Creates an empty clause with N variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPVarListClause< OMPDependClause >
using varlist_iterator
using varlist_const_iterator
using varlist_range
using varlist_const_range
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Protected Member Functions inherited from clang::OMPVarListClause< OMPDependClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents implicit clause 'depend' for the '#pragma omp task' directive.
#pragma omp task depend(in:a,b)
In this example directive '#pragma omp task' with clause 'depend' with the variables 'a' and 'b' with dependency 'in'.
Definition at line 4742 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPDependClause::children () inline
Definition at line 4866 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPDependClause >::varlist_begin(), and clang::OMPVarListClause< OMPDependClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPDependClause::children () const inline
Definition at line 4871 of file OpenMPClause.h.
References Children, and children().
classof()
static bool clang::OMPDependClause::classof (const OMPClause * T) inline static
Definition at line 4883 of file OpenMPClause.h.
Create()
OMPDependClause * OMPDependClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, DependDataTy Data, Expr * DepModifier, ArrayRef< Expr * > VL, unsigned NumLoops) static
Creates clause with a list of variables VL.
Parameters
C AST context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Data Dependency type and source locations.
VL List of references to the variables.
NumLoops Number of loops that is associated with this depend clause.
Definition at line 1041 of file OpenMPClause.cpp.
References clang::C, clang::OMPDependClause::DependDataTy::ColonLoc, clang::OMPDependClause::DependDataTy::DepKind, clang::OMPDependClause::DependDataTy::DepLoc, and clang::OMPDependClause::DependDataTy::OmpAllMemoryLoc.
Referenced by clang::Sema::ActOnOpenMPDependClause().
CreateEmpty()
OMPDependClause * OMPDependClause::CreateEmpty (const ASTContext & C, unsigned N, unsigned NumLoops) static
Creates an empty clause with N variables.
Parameters
C AST context.
N The number of variables.
NumLoops Number of loops that is associated with this depend clause.
Definition at line 1061 of file OpenMPClause.cpp.
References clang::C, and N.
Referenced by clang::OMPClauseReader::readClause().
getColonLoc()
SourceLocation clang::OMPDependClause::getColonLoc () const inline
Get colon location.
Definition at line 4844 of file OpenMPClause.h.
References clang::OMPDependClause::DependDataTy::ColonLoc.
getDependencyKind()
OpenMPDependClauseKind clang::OMPDependClause::getDependencyKind () const inline
Get dependency type.
Definition at line 4838 of file OpenMPClause.h.
References clang::OMPDependClause::DependDataTy::DepKind.
Referenced by getLoopData(), getLoopData(), and setLoopData().
getDependencyLoc()
SourceLocation clang::OMPDependClause::getDependencyLoc () const inline
Get dependency type location.
Definition at line 4841 of file OpenMPClause.h.
References clang::OMPDependClause::DependDataTy::DepLoc.
getLoopData() [1/2]
Expr * OMPDependClause::getLoopData (unsigned NumLoop)
Get the loop data.
Definition at line 1079 of file OpenMPClause.cpp.
References getDependencyKind(), and clang::OMPVarListClause< OMPDependClause >::getVarRefs().
getLoopData() [2/2]
const Expr * OMPDependClause::getLoopData (unsigned NumLoop) const
Definition at line 1089 of file OpenMPClause.cpp.
References getDependencyKind(), and clang::OMPVarListClause< OMPDependClause >::getVarRefs().
getModifier() [1/2]
Expr * OMPDependClause::getModifier ()
Return optional depend modifier.
Definition at line 1102 of file OpenMPClause.cpp.
References clang::OMPVarListClause< OMPDependClause >::getVarRefs().
Referenced by getModifier().
getModifier() [2/2]
const Expr * clang::OMPDependClause::getModifier () const inline
Definition at line 4851 of file OpenMPClause.h.
References getModifier().
getNumLoops()
unsigned clang::OMPDependClause::getNumLoops () const inline
Get number of loops associated with the clause.
Definition at line 4856 of file OpenMPClause.h.
getOmpAllMemoryLoc()
SourceLocation clang::OMPDependClause::getOmpAllMemoryLoc () const inline
Get 'omp_all_memory' location.
Definition at line 4847 of file OpenMPClause.h.
References clang::OMPDependClause::DependDataTy::OmpAllMemoryLoc.
setLoopData()
void OMPDependClause::setLoopData (unsigned NumLoop, Expr * Cnt)
Set the loop data for the depend clauses with 'sink|source' kind of dependency.
Definition at line 1069 of file OpenMPClause.cpp.
References getDependencyKind(), and clang::OMPVarListClause< OMPDependClause >::getVarRefs().
used_children() [1/2]
child_range clang::OMPDependClause::used_children () inline
Definition at line 4876 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPDependClause::used_children () const inline
Definition at line 4879 of file OpenMPClause.h.
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 4745 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp