clang: clang::ASTNodeKind Class Reference
clang::ASTNodeKind Class Reference
Kind identifier.
#include "clang/AST/ASTTypeTraits.h"
Classes
struct DenseMapInfo
Hooks for using ASTNodeKind as a key in a DenseMap.
Public Member Functions
ASTNodeKind ()
Empty identifier. It matches nothing.
bool isSame (ASTNodeKind Other) const
Returns true if this and Other represent the same kind.
bool isNone () const
Returns true only for the default ASTNodeKind()
bool isBaseOf (ASTNodeKind Other, unsigned *Distance=nullptr) const
Returns true if this is a base kind of (or same as) Other.
StringRef asStringRef () const
String representation of the kind.
bool operator< (const ASTNodeKind &Other) const
Strict weak ordering for ASTNodeKind.
ASTNodeKind getCladeKind () const
bool hasPointerIdentity () const
Check if the given ASTNodeKind identifies a type that offers pointer identity.
Static Public Member Functions
template<class T >
static ASTNodeKind getFromNodeKind ()
Construct an identifier for T.
static ASTNodeKind getMostDerivedType (ASTNodeKind Kind1, ASTNodeKind Kind2)
Return the most derived type between Kind1 and Kind2.
static ASTNodeKind getMostDerivedCommonAncestor (ASTNodeKind Kind1, ASTNodeKind Kind2)
Return the most derived common ancestor between Kind1 and Kind2.
static ASTNodeKind getFromNode (const Decl &D)
static ASTNodeKind getFromNode (const Stmt &S)
static ASTNodeKind getFromNode (const Type &T)
static ASTNodeKind getFromNode (const TypeLoc &T)
static ASTNodeKind getFromNode (const LambdaCapture &L)
static ASTNodeKind getFromNode (const OMPClause &C)
static ASTNodeKind getFromNode (const Attr &A)
Detailed Description
Kind identifier.
It can be constructed from any node kind and allows for runtime type hierarchy checks. Use getFromNodeKind<T>() to construct them.
Definition at line 51 of file ASTTypeTraits.h.
Constructor & Destructor Documentation
ASTNodeKind()
clang::ASTNodeKind::ASTNodeKind () inline
Empty identifier. It matches nothing.
Definition at line 54 of file ASTTypeTraits.h.
Referenced by clang::ASTNodeKind::DenseMapInfo::getEmptyKey(), getFromNodeKind(), getMostDerivedCommonAncestor(), getMostDerivedType(), and clang::ASTNodeKind::DenseMapInfo::getTombstoneKey().
Member Function Documentation
asStringRef()
StringRef ASTNodeKind::asStringRef () const
String representation of the kind.
Definition at line 87 of file ASTTypeTraits.cpp.
Referenced by clang::ast_matchers::dynamic::ArgKind::asString(), clang::DynTypedNode::dump(), clang::ast_matchers::dynamic::VariantValue::getTypeAsString(), clang::operator<<(), clang::DynTypedNode::print(), and clang::transformer::detail::rewriteDescendants().
getCladeKind()
ASTNodeKind ASTNodeKind::getCladeKind () const
Definition at line 76 of file ASTTypeTraits.cpp.
Referenced by clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor::buildMatcherCtor().
getFromNode() [1/7]
ASTNodeKind ASTNodeKind::getFromNode (const Attr & A) static
Definition at line 161 of file ASTTypeTraits.cpp.
References clang::Attr::getKind().
getFromNode() [2/7]
ASTNodeKind ASTNodeKind::getFromNode (const Decl & D) static
Construct an identifier for the dynamic type of the node
Definition at line 105 of file ASTTypeTraits.cpp.
References clang::Decl::getKind().
getFromNode() [3/7]
static ASTNodeKind clang::ASTNodeKind::getFromNode (const LambdaCapture & L) static
getFromNode() [4/7]
ASTNodeKind ASTNodeKind::getFromNode (const OMPClause & C) static
Definition at line 147 of file ASTTypeTraits.cpp.
References clang::C.
getFromNode() [5/7]
ASTNodeKind ASTNodeKind::getFromNode (const Stmt & S) static
Definition at line 115 of file ASTTypeTraits.cpp.
References clang::Stmt::NoStmtClass.
getFromNode() [6/7]
ASTNodeKind ASTNodeKind::getFromNode (const Type & T) static
Definition at line 126 of file ASTTypeTraits.cpp.
getFromNode() [7/7]
ASTNodeKind ASTNodeKind::getFromNode (const TypeLoc & T) static
Definition at line 136 of file ASTTypeTraits.cpp.
getFromNodeKind()
template<class T > static ASTNodeKind clang::ASTNodeKind::getFromNodeKind () inline static
Construct an identifier for T.
Definition at line 58 of file ASTTypeTraits.h.
References ASTNodeKind().
Referenced by clang::ast_matchers::dynamic::internal::BuildReturnTypeVector< ast_matchers::internal::BindableMatcher< T > >::build(), clang::ast_matchers::dynamic::internal::BuildReturnTypeVector< ast_matchers::internal::Matcher< T > >::build(), clang::ast_matchers::dynamic::internal::buildReturnTypeVectorFromTypeList(), clang::ast_matchers::dynamic::Registry::getAcceptedCompletionTypes(), clang::DynTypedNode::DenseMapInfo::getHashValue(), clang::ast_matchers::dynamic::internal::ArgTypeTraits< ast_matchers::internal::Matcher< T > >::getKind(), clang::ast_matchers::dynamic::VariantMatcher::getTypedMatcher(), clang::ast_matchers::dynamic::VariantMatcher::hasTypedMatcher(), clang::ast_matchers::dynamic::internal::makeMatcherAutoMarshall(), clang::DynTypedNode::operator<(), and clang::DynTypedNode::operator==().
getMostDerivedCommonAncestor()
ASTNodeKind ASTNodeKind::getMostDerivedCommonAncestor (ASTNodeKind Kind1, ASTNodeKind Kind2) static
Return the most derived common ancestor between Kind1 and Kind2.
Return ASTNodeKind() if they are not related.
Definition at line 96 of file ASTTypeTraits.cpp.
References ASTNodeKind(), isBaseOf(), and Parent.
getMostDerivedType()
ASTNodeKind ASTNodeKind::getMostDerivedType (ASTNodeKind Kind1, ASTNodeKind Kind2) static
Return the most derived type between Kind1 and Kind2.
Return ASTNodeKind() if they are not related.
Definition at line 89 of file ASTTypeTraits.cpp.
References ASTNodeKind(), and isBaseOf().
hasPointerIdentity()
bool clang::ASTNodeKind::hasPointerIdentity () const inline
Check if the given ASTNodeKind identifies a type that offers pointer identity.
This is useful for the fast path in DynTypedNode.
Definition at line 124 of file ASTTypeTraits.h.
Referenced by clang::DynTypedNode::getMemoizationData(), and clang::ParentMapContext::ParentMap::getParents().
isBaseOf()
bool ASTNodeKind::isBaseOf (ASTNodeKind Other, unsigned * Distance = nullptr) const
Returns true if this is a base kind of (or same as) Other.
Parameters
Distance If non-null, used to return the distance between this and Other in the class hierarchy.
Definition at line 59 of file ASTTypeTraits.cpp.
References isBaseOf().
Referenced by getMostDerivedCommonAncestor(), getMostDerivedType(), isBaseOf(), and clang::ast_matchers::dynamic::ArgKind::isConvertibleTo().
isNone()
bool clang::ASTNodeKind::isNone () const inline
Returns true only for the default ASTNodeKind()
Definition at line 79 of file ASTTypeTraits.h.
isSame()
bool clang::ASTNodeKind::isSame (ASTNodeKind Other) const inline
Returns true if this and Other represent the same kind.
Definition at line 74 of file ASTTypeTraits.h.
Referenced by clang::diff::ComparisonOptions::isMatchingAllowed(), clang::DynTypedNode::operator<(), and clang::DynTypedNode::operator==().
operator<()
bool clang::ASTNodeKind::operator< (const ASTNodeKind & Other) const inline
Strict weak ordering for ASTNodeKind.
Definition at line 90 of file ASTTypeTraits.h.
The documentation for this class was generated from the following files:
include/clang/AST/ASTTypeTraits.h
lib/AST/ASTTypeTraits.cpp