clang: clang::CodeGen::CodeGenFunction::AutoVarEmission Class Reference
clang::CodeGen::CodeGenFunction::AutoVarEmission Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
bool useLifetimeMarkers () const
llvm::Value * getSizeForLifetimeMarkers () const
Address getAllocatedAddress () const
Returns the raw, allocated address, which is not necessarily the address of the object itself.
Address getOriginalAllocatedAddress () const
Returns the address for the original alloca instruction.
Address getObjectAddress (CodeGenFunction &CGF) const
Returns the address of the object within this declaration.
Static Public Member Functions
static AutoVarEmission invalid ()
Friends
class CodeGenFunction
Detailed Description
Definition at line 3051 of file CodeGenFunction.h.
Member Function Documentation
getAllocatedAddress()
Address clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress () const inline
Returns the raw, allocated address, which is not necessarily the address of the object itself.
It is casted to default address space for address space agnostic languages.
Definition at line 3105 of file CodeGenFunction.h.
getObjectAddress()
Address clang::CodeGen::CodeGenFunction::AutoVarEmission::getObjectAddress (CodeGenFunction & CGF) const inline
Returns the address of the object within this declaration.
Note that this does not chase the forwarding pointer for __block decls.
Definition at line 3115 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::emitBlockByrefAddress().
getOriginalAllocatedAddress()
Address clang::CodeGen::CodeGenFunction::AutoVarEmission::getOriginalAllocatedAddress () const inline
Returns the address for the original alloca instruction.
Definition at line 3110 of file CodeGenFunction.h.
getSizeForLifetimeMarkers()
llvm::Value * clang::CodeGen::CodeGenFunction::AutoVarEmission::getSizeForLifetimeMarkers () const inline
Definition at line 3097 of file CodeGenFunction.h.
References useLifetimeMarkers().
invalid()
static AutoVarEmission clang::CodeGen::CodeGenFunction::AutoVarEmission::invalid () inline static
Definition at line 3092 of file CodeGenFunction.h.
References clang::Invalid.
useLifetimeMarkers()
bool clang::CodeGen::CodeGenFunction::AutoVarEmission::useLifetimeMarkers () const inline
Definition at line 3094 of file CodeGenFunction.h.
Referenced by getSizeForLifetimeMarkers().
Friends And Related Symbol Documentation
CodeGenFunction
friend class CodeGenFunction friend
Definition at line 3052 of file CodeGenFunction.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h