clang: clang::SrcMgr::SLocEntry Class Reference
clang::SrcMgr::SLocEntry Class Reference
This is a discriminated union of FileInfo and ExpansionInfo.
#include "clang/Basic/SourceManager.h"
Public Member Functions
SLocEntry ()
SourceLocation::UIntTy getOffset () const
bool isExpansion () const
bool isFile () const
const FileInfo & getFile () const
const ExpansionInfo & getExpansion () const
Static Public Member Functions
static SLocEntry get (SourceLocation::UIntTy Offset, const FileInfo &FI)
static SLocEntry get (SourceLocation::UIntTy Offset, const ExpansionInfo &Expansion)
Detailed Description
This is a discriminated union of FileInfo and ExpansionInfo.
SourceManager keeps an array of these objects, and they are uniquely identified by the FileID datatype.
Definition at line 468 of file SourceManager.h.
Constructor & Destructor Documentation
SLocEntry()
clang::SrcMgr::SLocEntry::SLocEntry () inline
Definition at line 478 of file SourceManager.h.
Member Function Documentation
get() [1/2]
static SLocEntry clang::SrcMgr::SLocEntry::get (SourceLocation::UIntTy Offset, const ExpansionInfo & Expansion) inline static
Definition at line 504 of file SourceManager.h.
References Expansion, and Offset.
get() [2/2]
static SLocEntry clang::SrcMgr::SLocEntry::get (SourceLocation::UIntTy Offset, const FileInfo & FI) inline static
Definition at line 495 of file SourceManager.h.
References File, and Offset.
getExpansion()
const ExpansionInfo & clang::SrcMgr::SLocEntry::getExpansion () const inline
Definition at line 490 of file SourceManager.h.
References Expansion, and isExpansion().
Referenced by EvaluateDefined(), clang::SourceManager::getDecomposedIncludedLoc(), clang::SourceManager::getImmediateExpansionRange(), clang::Lexer::getImmediateMacroName(), clang::SourceManager::getImmediateSpellingLoc(), clang::ASTImporter::Import(), clang::SourceManager::isAtEndOfImmediateMacroExpansion(), clang::SourceManager::isAtStartOfImmediateMacroExpansion(), isFunctionMacroExpansion(), clang::SourceManager::isMacroArgExpansion(), clang::SourceManager::isMacroBodyExpansion(), and clang::Lexer::makeFileCharRange().
getFile()
const FileInfo & clang::SrcMgr::SLocEntry::getFile () const inline
Definition at line 485 of file SourceManager.h.
References File, and isFile().
Referenced by clang::SourceManager::AddLineNote(), clang::SourceManager::getCharacterData(), clang::SourceManager::getDecomposedIncludedLoc(), clang::SourceManager::getFileCharacteristic(), clang::SourceManager::getFileEntryForSLocEntry(), clang::SourceManager::getLineNumber(), getNullabilityCompletenessCheckFileID(), clang::SourceManager::getPresumedLoc(), clang::ASTImporter::Import(), clang::index::IndexingContext::importedModule(), clang::SourceManager::isInMainFile(), clang::SourceManager::translateFile(), and clang::SourceManager::translateLineCol().
getOffset()
SourceLocation::UIntTy clang::SrcMgr::SLocEntry::getOffset () const inline
Definition at line 480 of file SourceManager.h.
Referenced by clang::SourceManager::getFileIDSize(), clang::SourceManager::isInFileID(), and clang::SourceManager::translateLineCol().
isExpansion()
bool clang::SrcMgr::SLocEntry::isExpansion () const inline
Definition at line 482 of file SourceManager.h.
Referenced by clang::SourceManager::getDecomposedIncludedLoc(), getExpansion(), clang::ASTImporter::Import(), clang::SourceManager::isAtEndOfImmediateMacroExpansion(), clang::SourceManager::isAtStartOfImmediateMacroExpansion(), and isFile().
isFile()
bool clang::SrcMgr::SLocEntry::isFile () const inline
Definition at line 483 of file SourceManager.h.
References isExpansion().
Referenced by clang::SourceManager::AddLineNote(), clang::SourceManager::getCharacterData(), getFile(), clang::SourceManager::getLineNumber(), getNullabilityCompletenessCheckFileID(), clang::SourceManager::getPresumedLoc(), clang::index::IndexingContext::importedModule(), clang::SourceManager::translateFile(), and clang::SourceManager::translateLineCol().
Member Data Documentation
Expansion
ExpansionInfo clang::SrcMgr::SLocEntry::Expansion
Definition at line 474 of file SourceManager.h.
Referenced by get(), and getExpansion().
File
FileInfo clang::SrcMgr::SLocEntry::File
Definition at line 473 of file SourceManager.h.
Referenced by get(), and getFile().
The documentation for this class was generated from the following file:
include/clang/Basic/SourceManager.h