clang: clang::sema::AnalysisBasedWarnings Class Reference
clang::sema::AnalysisBasedWarnings Class Reference
#include "clang/Sema/AnalysisBasedWarnings.h"
Classes
class InterProceduralData
InterProceduralData aims to be a storage of whatever data should be passed between analyses of different functions.
class Policy
Public Member Functions
AnalysisBasedWarnings (Sema &s)
~AnalysisBasedWarnings ()
void IssueWarnings (Policy P, FunctionScopeInfo *fscope, const Decl *D, QualType BlockType)
Policy getDefaultPolicy ()
void PrintStats () const
Detailed Description
Definition at line 31 of file AnalysisBasedWarnings.h.
Constructor & Destructor Documentation
AnalysisBasedWarnings()
sema::AnalysisBasedWarnings::AnalysisBasedWarnings (Sema & s)
Definition at line 2175 of file AnalysisBasedWarnings.cpp.
References clang::Sema::getDiagnostics(), and isEnabled().
~AnalysisBasedWarnings()
sema::AnalysisBasedWarnings::~AnalysisBasedWarnings () default
Member Function Documentation
getDefaultPolicy()
Policy clang::sema::AnalysisBasedWarnings::getDefaultPolicy () inline
Definition at line 98 of file AnalysisBasedWarnings.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), and clang::Sema::ActOnFinishFunctionBody().
IssueWarnings()
void clang::sema::AnalysisBasedWarnings::IssueWarnings (Policy P, sema::FunctionScopeInfo * fscope, const Decl * D, QualType BlockType)
Definition at line 2205 of file AnalysisBasedWarnings.cpp.
References clang::CFG::BuildOptions::AddCXXDefaultInitExprInCtors, clang::CFG::BuildOptions::AddCXXNewAllocator, clang::CFG::BuildOptions::AddEHEdges, clang::CFG::BuildOptions::AddImplicitDtors, clang::CFG::BuildOptions::AddInitializers, clang::CFG::BuildOptions::AddTemporaryDtors, clang::cast(), clang::checkCalledOnceParameters(), CheckFallThroughForBody(), checkRecursiveFunction(), checkThrowInNonThrowingFunc(), CheckUnreachable(), clang::Sema::CollectStats, clang::Sema::Diag(), diagnoseRepeatedUseOfWeak(), DiagnoseSwitchLabelsFallthrough(), flushDiagnostics(), clang::Decl::getBeginLoc(), clang::AnalysisDeclContext::getBlockForRegisteredExpression(), clang::Decl::getBody(), clang::AnalysisDeclContext::getCFG(), clang::AnalysisDeclContext::getCFGBuildOptions(), clang::AnalysisDeclContext::getCFGReachablityAnalysis(), clang::AnalysisDeclContext::getDecl(), clang::Sema::getDiagnostics(), clang::Decl::getEndLoc(), clang::CFG::getEntry(), clang::DiagnosticsEngine::getIgnoreAllWarnings(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::AnalysisDeclContext::getParentMap(), clang::DiagnosticsEngine::getSuppressSystemWarnings(), clang::sema::FunctionScopeInfo::HasFallthroughStmt, clang::Sema::hasUncompilableErrorOccurred(), clang::isa(), clang::AnalysisDeclContext::isCFGBuilt(), clang::sema::FunctionScopeInfo::isCoroutine(), clang::DiagnosticsEngine::isIgnored(), clang::SourceManager::isInSystemHeader(), isNoexcept(), clang::CFGReverseBlockReachabilityAnalysis::isReachable(), clang::isTemplateInstantiation(), clang::UninitVariablesAnalysisStats::NumBlockVisits, clang::UninitVariablesAnalysisStats::NumVariablesAnalyzed, clang::CFG::BuildOptions::Observer, P, clang::sema::FunctionScopeInfo::PossiblyUnreachableDiags, clang::CFG::BuildOptions::PruneTriviallyFalseEdges, clang::AnalysisDeclContext::registerForcedBlockExpression(), clang::consumed::ConsumedAnalyzer::run(), clang::threadSafety::runThreadSafetyAnalysis(), clang::runUninitializedVariablesAnalysis(), clang::CFG::BuildOptions::setAllAlwaysAdd(), clang::CFG::BuildOptions::setAlwaysAdd(), clang::Sema::SourceMgr, and clang::Sema::ThreadSafetyDeclCache.
Referenced by clang::Sema::PopFunctionScopeInfo().
PrintStats()
void clang::sema::AnalysisBasedWarnings::PrintStats () const
Definition at line 2454 of file AnalysisBasedWarnings.cpp.
Referenced by clang::Sema::PrintStats().
The documentation for this class was generated from the following files:
include/clang/Sema/AnalysisBasedWarnings.h
lib/Sema/AnalysisBasedWarnings.cpp