clang: clang::edit::EditsReceiver Class Reference
clang::edit::EditsReceiver Class Reference abstract
#include "clang/Edit/EditsReceiver.h"
Public Member Functions
virtual ~EditsReceiver ()=default
virtual void insert (SourceLocation loc, StringRef text)=0
virtual void replace (CharSourceRange range, StringRef text)=0
virtual void remove (CharSourceRange range)
By default it calls replace with an empty string.
Detailed Description
Definition at line 19 of file EditsReceiver.h.
Constructor & Destructor Documentation
~EditsReceiver()
virtual clang::edit::EditsReceiver::~EditsReceiver () virtual default
Member Function Documentation
insert()
virtual void clang::edit::EditsReceiver::insert (SourceLocation loc, StringRef text) pure virtual
Referenced by applyRewrite().
remove()
void EditsReceiver::remove (CharSourceRange range) virtual
By default it calls replace with an empty string.
Definition at line 30 of file EditedSource.cpp.
References replace().
Referenced by applyRewrite().
replace()
virtual void clang::edit::EditsReceiver::replace (CharSourceRange range, StringRef text) pure virtual
Referenced by applyRewrite(), and remove().
The documentation for this class was generated from the following files:
include/clang/Edit/EditsReceiver.h
lib/Edit/EditedSource.cpp