clang: clang::CompilerInvocationValueBase Class Reference
clang::CompilerInvocationValueBase Class Reference
The base class of CompilerInvocation with value semantics.
#include "clang/Frontend/CompilerInvocation.h"
Public Member Functions
MigratorOptions & getMigratorOpts ()
const MigratorOptions & getMigratorOpts () const
CodeGenOptions & getCodeGenOpts ()
const CodeGenOptions & getCodeGenOpts () const
DependencyOutputOptions & getDependencyOutputOpts ()
const DependencyOutputOptions & getDependencyOutputOpts () const
FileSystemOptions & getFileSystemOpts ()
const FileSystemOptions & getFileSystemOpts () const
FrontendOptions & getFrontendOpts ()
const FrontendOptions & getFrontendOpts () const
PreprocessorOutputOptions & getPreprocessorOutputOpts ()
const PreprocessorOutputOptions & getPreprocessorOutputOpts () const
Protected Attributes
MigratorOptions MigratorOpts
CodeGenOptions CodeGenOpts
Options controlling IRgen and the backend.
DependencyOutputOptions DependencyOutputOpts
Options controlling dependency output.
FileSystemOptions FileSystemOpts
Options controlling file system operations.
FrontendOptions FrontendOpts
Options controlling the frontend itself.
PreprocessorOutputOptions PreprocessorOutputOpts
Options controlling preprocessed output.
Detailed Description
The base class of CompilerInvocation with value semantics.
Definition at line 136 of file CompilerInvocation.h.
Member Function Documentation
getCodeGenOpts() [1/2]
CodeGenOptions & clang::CompilerInvocationValueBase::getCodeGenOpts () inline
Definition at line 159 of file CompilerInvocation.h.
References CodeGenOpts.
Referenced by FixupInvocation(), clang::CompilerInvocation::getModuleHash(), and clang::tooling::newInvocation().
getCodeGenOpts() [2/2]
const CodeGenOptions & clang::CompilerInvocationValueBase::getCodeGenOpts () const inline
Definition at line 160 of file CompilerInvocation.h.
References CodeGenOpts.
getDependencyOutputOpts() [1/2]
DependencyOutputOptions & clang::CompilerInvocationValueBase::getDependencyOutputOpts () inline
Definition at line 162 of file CompilerInvocation.h.
References DependencyOutputOpts.
Referenced by clang::tooling::dependencies::ModuleDeps::getCanonicalCommandLine().
getDependencyOutputOpts() [2/2]
const DependencyOutputOptions & clang::CompilerInvocationValueBase::getDependencyOutputOpts () const inline
Definition at line 166 of file CompilerInvocation.h.
References DependencyOutputOpts.
getFileSystemOpts() [1/2]
FileSystemOptions & clang::CompilerInvocationValueBase::getFileSystemOpts () inline
Definition at line 170 of file CompilerInvocation.h.
References FileSystemOpts.
Referenced by createInvocationForMigration().
getFileSystemOpts() [2/2]
const FileSystemOptions & clang::CompilerInvocationValueBase::getFileSystemOpts () const inline
Definition at line 172 of file CompilerInvocation.h.
References FileSystemOpts.
getFrontendOpts() [1/2]
FrontendOptions & clang::CompilerInvocationValueBase::getFrontendOpts () inline
Definition at line 176 of file CompilerInvocation.h.
References FrontendOpts.
Referenced by applyTransforms(), compileModuleAndReadAST(), FixupInvocation(), clang::tooling::dependencies::ModuleDeps::getCanonicalCommandLine(), clang::CompilerInvocation::getModuleHash(), and clang::tooling::newInvocation().
getFrontendOpts() [2/2]
const FrontendOptions & clang::CompilerInvocationValueBase::getFrontendOpts () const inline
Definition at line 177 of file CompilerInvocation.h.
References FrontendOpts.
getMigratorOpts() [1/2]
MigratorOptions & clang::CompilerInvocationValueBase::getMigratorOpts () inline
Definition at line 156 of file CompilerInvocation.h.
References MigratorOpts.
Referenced by applyTransforms(), and clang::arcmt::checkForManualIssues().
getMigratorOpts() [2/2]
const MigratorOptions & clang::CompilerInvocationValueBase::getMigratorOpts () const inline
Definition at line 157 of file CompilerInvocation.h.
References MigratorOpts.
getPreprocessorOutputOpts() [1/2]
PreprocessorOutputOptions & clang::CompilerInvocationValueBase::getPreprocessorOutputOpts () inline
Definition at line 179 of file CompilerInvocation.h.
References PreprocessorOutputOpts.
getPreprocessorOutputOpts() [2/2]
const PreprocessorOutputOptions & clang::CompilerInvocationValueBase::getPreprocessorOutputOpts () const inline
Definition at line 183 of file CompilerInvocation.h.
References PreprocessorOutputOpts.
Member Data Documentation
CodeGenOpts
CodeGenOptions clang::CompilerInvocationValueBase::CodeGenOpts protected
Options controlling IRgen and the backend.
Definition at line 141 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getCodeGenOpts(), and getCodeGenOpts().
DependencyOutputOpts
DependencyOutputOptions clang::CompilerInvocationValueBase::DependencyOutputOpts protected
Options controlling dependency output.
Definition at line 144 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getDependencyOutputOpts(), and getDependencyOutputOpts().
FileSystemOpts
FileSystemOptions clang::CompilerInvocationValueBase::FileSystemOpts protected
Options controlling file system operations.
Definition at line 147 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getFileSystemOpts(), and getFileSystemOpts().
FrontendOpts
FrontendOptions clang::CompilerInvocationValueBase::FrontendOpts protected
Options controlling the frontend itself.
Definition at line 150 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getFrontendOpts(), and getFrontendOpts().
MigratorOpts
MigratorOptions clang::CompilerInvocationValueBase::MigratorOpts protected
Definition at line 138 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getMigratorOpts(), and getMigratorOpts().
PreprocessorOutputOpts
PreprocessorOutputOptions clang::CompilerInvocationValueBase::PreprocessorOutputOpts protected
Options controlling preprocessed output.
Definition at line 153 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::generateCC1CommandLine(), getPreprocessorOutputOpts(), and getPreprocessorOutputOpts().
The documentation for this class was generated from the following file:
include/clang/Frontend/CompilerInvocation.h