clang: clang::RopePieceBTreeIterator Class Reference
clang::RopePieceBTreeIterator Class Reference
RopePieceBTreeIterator - This class provides read-only forward iteration over bytes that are in a RopePieceBTree.
#include "clang/Rewrite/Core/RewriteRope.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = const char
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
RopePieceBTreeIterator ()=default
RopePieceBTreeIterator (const void *N)
char operator* () const
bool operator== (const RopePieceBTreeIterator &RHS) const
bool operator!= (const RopePieceBTreeIterator &RHS) const
RopePieceBTreeIterator & operator++ ()
RopePieceBTreeIterator operator++ (int)
llvm::StringRef piece () const
void MoveToNextPiece ()
Detailed Description
RopePieceBTreeIterator - This class provides read-only forward iteration over bytes that are in a RopePieceBTree.
This first iterates over bytes in a RopePiece, then iterates over RopePiece's in a RopePieceBTreeLeaf, then iterates over RopePieceBTreeLeaf's in a RopePieceBTree.
Definition at line 86 of file RewriteRope.h.
Member Typedef Documentation
difference_type
using clang::RopePieceBTreeIterator::difference_type = std::ptrdiff_t
Definition at line 100 of file RewriteRope.h.
iterator_category
using clang::RopePieceBTreeIterator::iterator_category = std::forward_iterator_tag
Definition at line 98 of file RewriteRope.h.
pointer
using clang::RopePieceBTreeIterator::pointer = value_type *
Definition at line 101 of file RewriteRope.h.
reference
using clang::RopePieceBTreeIterator::reference = value_type &
Definition at line 102 of file RewriteRope.h.
value_type
using clang::RopePieceBTreeIterator::value_type = const char
Definition at line 99 of file RewriteRope.h.
Constructor & Destructor Documentation
RopePieceBTreeIterator() [1/2]
clang::RopePieceBTreeIterator::RopePieceBTreeIterator () default
RopePieceBTreeIterator() [2/2]
RopePieceBTreeIterator::RopePieceBTreeIterator (const void * N)
Definition at line 672 of file RewriteRope.cpp.
References clang::cast(), getCN(), and N.
Member Function Documentation
MoveToNextPiece()
void RopePieceBTreeIterator::MoveToNextPiece ()
Definition at line 694 of file RewriteRope.cpp.
References getCN().
Referenced by operator++(), and clang::RewriteBuffer::write().
operator!=()
bool clang::RopePieceBTreeIterator::operator!= (const RopePieceBTreeIterator & RHS) const inline
Definition at line 114 of file RewriteRope.h.
References operator==().
operator*()
char clang::RopePieceBTreeIterator::operator* () const inline
Definition at line 107 of file RewriteRope.h.
operator++() [1/2]
RopePieceBTreeIterator & clang::RopePieceBTreeIterator::operator++ () inline
Definition at line 118 of file RewriteRope.h.
References MoveToNextPiece(), and clang::RopePiece::size().
operator++() [2/2]
RopePieceBTreeIterator clang::RopePieceBTreeIterator::operator++ (int) inline
Definition at line 126 of file RewriteRope.h.
operator==()
bool clang::RopePieceBTreeIterator::operator== (const RopePieceBTreeIterator & RHS) const inline
Definition at line 111 of file RewriteRope.h.
Referenced by operator!=().
piece()
llvm::StringRef clang::RopePieceBTreeIterator::piece () const inline
Definition at line 130 of file RewriteRope.h.
References clang::RopePiece::size().
The documentation for this class was generated from the following files:
include/clang/Rewrite/Core/RewriteRope.h
lib/Rewrite/RewriteRope.cpp