clang: clang::comments::BlockCommandComment Class Reference
clang::comments::BlockCommandComment Class Reference
A command that has zero or more word-like arguments (number of word-like arguments depends on command name) and a paragraph as an argument (e.
#include "clang/AST/Comment.h"
Public Member Functions
BlockCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
child_iterator child_begin () const
child_iterator child_end () const
unsigned getCommandID () const
StringRef getCommandName (const CommandTraits &Traits) const
SourceLocation getCommandNameBeginLoc () const
SourceRange getCommandNameRange (const CommandTraits &Traits) const
unsigned getNumArgs () const
StringRef getArgText (unsigned Idx) const
SourceRange getArgRange (unsigned Idx) const
void setArgs (ArrayRef< Argument > A)
ParagraphComment * getParagraph () const LLVM_READONLY
bool hasNonWhitespaceParagraph () const
void setParagraph (ParagraphComment *PC)
CommandMarkerKind getCommandMarker () const LLVM_READONLY
Public Member Functions inherited from clang::comments::Comment
Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
CommentKind getCommentKind () const
const char * getCommentKindName () const
void dump () const
void dumpColor () const
void dump (raw_ostream &OS, const ASTContext &Context) const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const LLVM_READONLY
child_iterator child_begin () const
child_iterator child_end () const
unsigned child_count () const
Static Public Member Functions
static bool classof (const Comment *C)
Static Public Member Functions inherited from clang::comments::BlockContentComment
static bool classof (const Comment *C)
Protected Member Functions
BlockCommandComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Protected Member Functions inherited from clang::comments::BlockContentComment
BlockContentComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
Protected Member Functions inherited from clang::comments::Comment
void setSourceRange (SourceRange SR)
void setLocation (SourceLocation L)
Protected Attributes
ArrayRef< Argument > Args
Word-like arguments.
ParagraphComment * Paragraph
Paragraph argument.
Protected Attributes inherited from clang::comments::Comment
SourceLocation Loc
Preferred location to show caret.
SourceRange Range
Source range of this AST node.
union {
CommentBitfields CommentBits
InlineContentCommentBitfields InlineContentCommentBits
TextCommentBitfields TextCommentBits
InlineCommandCommentBitfields InlineCommandCommentBits
HTMLTagCommentBitfields HTMLTagCommentBits
HTMLStartTagCommentBitfields HTMLStartTagCommentBits
ParagraphCommentBitfields ParagraphCommentBits
BlockCommandCommentBitfields BlockCommandCommentBits
ParamCommandCommentBitfields ParamCommandCommentBits
};
Additional Inherited Members
Public Types inherited from clang::comments::Comment
enum CommentKind { NoCommentKind = 0 }
typedef Comment *const * child_iterator
Public Attributes inherited from clang::comments::Comment
Protected Types inherited from clang::comments::Comment
enum { NumCommentBits = 8 }
enum { NumInlineContentCommentBits = NumCommentBits + 1 }
enum { NumTextCommentBits = NumInlineContentCommentBits + 2 }
enum { NumInlineCommandCommentBits }
enum { NumHTMLTagCommentBits = NumInlineContentCommentBits + 1 }
enum { NumHTMLStartTagCommentBits = NumHTMLTagCommentBits + 1 }
enum { NumParagraphCommentBits = NumCommentBits + 2 }
enum { NumBlockCommandCommentBits }
enum { NumParamCommandCommentBits = NumBlockCommandCommentBits + 3 }
Detailed Description
A command that has zero or more word-like arguments (number of word-like arguments depends on command name) and a paragraph as an argument (e.
g., \brief).
Definition at line 588 of file Comment.h.
Constructor & Destructor Documentation
BlockCommandComment() [1/2]
clang::comments::BlockCommandComment::BlockCommandComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker) inline protected
Definition at line 596 of file Comment.h.
References clang::comments::Comment::BlockCommandCommentBits, getCommandNameBeginLoc(), and clang::comments::Comment::setLocation().
BlockCommandComment() [2/2]
clang::comments::BlockCommandComment::BlockCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker) inline
Definition at line 609 of file Comment.h.
References clang::comments::Comment::BlockCommandCommentBits, getCommandNameBeginLoc(), and clang::comments::Comment::setLocation().
Member Function Documentation
child_begin()
child_iterator clang::comments::BlockCommandComment::child_begin () const inline
Definition at line 625 of file Comment.h.
References Paragraph.
child_end()
child_iterator clang::comments::BlockCommandComment::child_end () const inline
Definition at line 629 of file Comment.h.
References Paragraph.
classof()
static bool clang::comments::BlockCommandComment::classof (const Comment * C) inline static
Definition at line 620 of file Comment.h.
References clang::C.
getArgRange()
SourceRange clang::comments::BlockCommandComment::getArgRange (unsigned Idx) const inline
Definition at line 659 of file Comment.h.
References Args.
getArgText()
StringRef clang::comments::BlockCommandComment::getArgText (unsigned Idx) const inline
Definition at line 655 of file Comment.h.
References Args.
getCommandID()
unsigned clang::comments::BlockCommandComment::getCommandID () const inline
Definition at line 633 of file Comment.h.
References clang::comments::Comment::BlockCommandCommentBits.
Referenced by getCommandName().
getCommandMarker()
CommandMarkerKind clang::comments::BlockCommandComment::getCommandMarker () const inline
Definition at line 687 of file Comment.h.
References clang::comments::Comment::BlockCommandCommentBits.
getCommandName()
StringRef clang::comments::BlockCommandComment::getCommandName (const CommandTraits & Traits) const inline
Definition at line 637 of file Comment.h.
References getCommandID(), clang::comments::CommandTraits::getCommandInfo(), and clang::comments::CommandInfo::Name.
Referenced by getCommandNameRange().
getCommandNameBeginLoc()
SourceLocation clang::comments::BlockCommandComment::getCommandNameBeginLoc () const inline
Definition at line 641 of file Comment.h.
References clang::comments::Comment::getBeginLoc(), and clang::SourceLocation::getLocWithOffset().
Referenced by BlockCommandComment(), BlockCommandComment(), and getCommandNameRange().
getCommandNameRange()
SourceRange clang::comments::BlockCommandComment::getCommandNameRange (const CommandTraits & Traits) const inline
Definition at line 645 of file Comment.h.
References clang::comments::Comment::getBeginLoc(), getCommandName(), and getCommandNameBeginLoc().
Referenced by clang::comments::Sema::actOnParamCommandStart(), and clang::comments::Sema::actOnTParamCommandStart().
getNumArgs()
unsigned clang::comments::BlockCommandComment::getNumArgs () const inline
Definition at line 651 of file Comment.h.
References Args.
Referenced by clang::comments::Sema::actOnParamCommandParamNameArg(), clang::comments::Sema::actOnTParamCommandParamNameArg(), clang::comments::ParamCommandComment::hasParamName(), and clang::comments::TParamCommandComment::hasParamName().
getParagraph()
ParagraphComment * clang::comments::BlockCommandComment::getParagraph () const inline
Definition at line 672 of file Comment.h.
References Paragraph.
hasNonWhitespaceParagraph()
bool clang::comments::BlockCommandComment::hasNonWhitespaceParagraph () const inline
Definition at line 676 of file Comment.h.
References clang::comments::ParagraphComment::isWhitespace(), and Paragraph.
setArgs()
void clang::comments::BlockCommandComment::setArgs (ArrayRef< Argument > A) inline
Definition at line 663 of file Comment.h.
References Args, clang::comments::Comment::getBeginLoc(), clang::SourceLocation::isValid(), and clang::comments::Comment::setSourceRange().
Referenced by clang::comments::Sema::actOnBlockCommandArgs(), clang::comments::Sema::actOnParamCommandParamNameArg(), and clang::comments::Sema::actOnTParamCommandParamNameArg().
setParagraph()
void clang::comments::BlockCommandComment::setParagraph (ParagraphComment * PC) inline
Definition at line 680 of file Comment.h.
References clang::comments::Comment::getBeginLoc(), clang::comments::Comment::getEndLoc(), clang::SourceLocation::isValid(), Paragraph, and clang::comments::Comment::setSourceRange().
Referenced by clang::comments::Sema::actOnBlockCommandFinish(), clang::comments::Sema::actOnParamCommandFinish(), and clang::comments::Sema::actOnTParamCommandFinish().
Member Data Documentation
Args
ArrayRef<Argument> clang::comments::BlockCommandComment::Args protected
Word-like arguments.
Definition at line 591 of file Comment.h.
Referenced by getArgRange(), getArgText(), getNumArgs(), clang::comments::ParamCommandComment::getParamNameAsWritten(), clang::comments::TParamCommandComment::getParamNameAsWritten(), clang::comments::ParamCommandComment::getParamNameRange(), clang::comments::TParamCommandComment::getParamNameRange(), and setArgs().
Paragraph
ParagraphComment* clang::comments::BlockCommandComment::Paragraph protected
Paragraph argument.
Definition at line 594 of file Comment.h.
Referenced by child_begin(), child_end(), getParagraph(), hasNonWhitespaceParagraph(), and setParagraph().
The documentation for this class was generated from the following file:
include/clang/AST/Comment.h