clang: clang::ento::LazyCompoundValData Class Reference
clang::ento::LazyCompoundValData Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h"
Public Member Functions
LazyCompoundValData (const StoreRef &st, const TypedValueRegion *r)
const void * getStore () const
It might return null.
LLVM_ATTRIBUTE_RETURNS_NONNULL const TypedValueRegion * getRegion () const
void Profile (llvm::FoldingSetNodeID &ID)
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const StoreRef &store, const TypedValueRegion *region)
Detailed Description
Definition at line 62 of file BasicValueFactory.h.
Constructor & Destructor Documentation
LazyCompoundValData()
clang::ento::LazyCompoundValData::LazyCompoundValData (const StoreRef & st, const TypedValueRegion * r) inline
Definition at line 67 of file BasicValueFactory.h.
References clang::ento::TypedValueRegion::getValueType(), and clang::ento::NonLoc::isCompoundType().
Member Function Documentation
getRegion()
LLVM_ATTRIBUTE_RETURNS_NONNULL const TypedValueRegion * clang::ento::LazyCompoundValData::getRegion () const inline
Definition at line 77 of file BasicValueFactory.h.
getStore()
const void * clang::ento::LazyCompoundValData::getStore () const inline
It might return null.
Definition at line 74 of file BasicValueFactory.h.
References clang::ento::StoreRef::getStore().
Profile() [1/2]
void clang::ento::LazyCompoundValData::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 83 of file BasicValueFactory.h.
References Profile().
Referenced by Profile().
Profile() [2/2]
void LazyCompoundValData::Profile (llvm::FoldingSetNodeID & ID, const StoreRef & store, const TypedValueRegion * region) static
Definition at line 38 of file BasicValueFactory.cpp.
References clang::ento::StoreRef::getStore().
Referenced by clang::ento::BasicValueFactory::getLazyCompoundValData().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h
lib/StaticAnalyzer/Core/BasicValueFactory.cpp