clang: clang::driver::toolchains::CrossWindowsToolChain Class Reference
clang::driver::toolchains::CrossWindowsToolChain Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/CrossWindows.h"
Public Member Functions
CrossWindowsToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
bool IsIntegratedAssemblerDefault () const override
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const override
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const override
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
Public Member Functions inherited from clang::driver::toolchains::Generic_GCC
Generic_GCC (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~Generic_GCC () override
void printVerboseInfo (raw_ostream &OS) const override
Dispatch to the specific toolchain for verbose printing.
bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const override
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
bool IsIntegratedAssemblerDefault () const override
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const Multilib & getMultilib () const
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
virtual llvm::opt::DerivedArgList * TranslateOpenMPTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs) const
TranslateOpenMPTargetArgs - Create a new derived argument list for that contains the OpenMP target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val.
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual bool isCrossCompiling () const
Returns true if the toolchain is targeting a non-native architecture.
virtual bool HasNativeLLVMSupport () const
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool IsIntegratedBackendDefault () const
IsIntegratedBackendDefault - Does this tool chain enable -fintegrated-objemitter by default.
virtual bool IsIntegratedBackendSupported () const
IsIntegratedBackendSupported - Does this tool chain support -fintegrated-objemitter.
virtual bool IsNonIntegratedBackendSupported () const
IsNonIntegratedBackendSupported - Does this tool chain support -fno-integrated-objemitter.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool IsMathErrnoDefault () const
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual RuntimeLibType GetDefaultRuntimeLibType () const
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
virtual CXXStdlibType GetDefaultCXXStdlibType () const
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
path_list getRuntimePaths () const
path_list getStdlibPaths () const
std::string getArchSpecificLibPath () const
virtual StringRef getOSLibName () const
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual bool SupportsProfiling () const
SupportsProfiling - Does this tool chain support -pg.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual std::string GetGlobalDebugPathRemapping () const
Add an additional -fdebug-prefix-map entry.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const
Add options that need to be passed to cc1 for this target.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
virtual void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific CUDA includes.
virtual void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific HIP includes.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getHIPDeviceLibs (const llvm::opt::ArgList &Args) const
Get paths of HIP device libraries.
virtual void AddHIPRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the system specific linker arguments to use for the given HIP runtime library type.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
virtual Optional< llvm::Triple > getTargetVariantTriple () const
Protected Member Functions
Tool * buildLinker () const override
Tool * buildAssembler () const override
Protected Member Functions inherited from clang::driver::toolchains::Generic_GCC
Tool * getTool (Action::ActionClass AC) const override
Tool * buildAssembler () const override
Tool * buildLinker () const override
bool isTarget64Bit () const
Check whether the target triple's architecture is 64-bits.
bool isTarget32Bit () const
Check whether the target triple's architecture is 32-bits.
void PushPPaths (ToolChain::path_list &PPaths)
void AddMultilibPaths (const Driver &D, const std::string &SysRoot, const std::string &OSLibDir, const std::string &MultiarchTriple, path_list &Paths)
void AddMultiarchPaths (const Driver &D, const std::string &SysRoot, const std::string &OSLibDir, path_list &Paths)
void AddMultilibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
virtual void addLibCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
virtual void addLibStdCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
bool addGCCLibStdCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, StringRef DebianMultiarch) const
bool addLibStdCXXIncludePaths (Twine IncludeDir, StringRef Triple, Twine IncludeSuffix, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, bool DetectDebian=false) const
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildStaticLibTool () const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
Additional Inherited Members
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx , CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT , RLT_Libgcc }
enum UnwindLibType { UNW_None , UNW_CompilerRT , UNW_Libgcc }
enum RTTIMode { RM_Enabled , RM_Disabled }
enum FileType { FT_Object , FT_Static , FT_Shared }
using path_list = SmallVector<std::string, 16>
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
static std::string concat (StringRef Path, const Twine &A, const Twine &B="", const Twine &C="", const Twine &D="")
Protected Attributes inherited from clang::driver::toolchains::Generic_GCC
GCCInstallationDetector GCCInstallation
CudaInstallationDetector CudaInstallation
RocmInstallationDetector RocmInstallation
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
Multilib SelectedMultilib
Detailed Description
Definition at line 52 of file CrossWindows.h.
Constructor & Destructor Documentation
CrossWindowsToolChain()
CrossWindowsToolChain::CrossWindowsToolChain (const Driver & D, const llvm::Triple & T, const llvm::opt::ArgList & Args)
Definition at line 211 of file CrossWindows.cpp.
Member Function Documentation
AddClangCXXStdlibIncludeArgs()
void CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 260 of file CrossWindows.cpp.
References clang::driver::ToolChain::addSystemInclude(), clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::GetCXXStdlibType(), clang::driver::ToolChain::getDriver(), and clang::driver::Driver::SysRoot.
AddClangSystemIncludeArgs()
void CrossWindowsToolChain::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented from clang::driver::ToolChain.
Definition at line 234 of file CrossWindows.cpp.
References clang::driver::ToolChain::addExternCSystemInclude(), clang::driver::ToolChain::addSystemInclude(), clang::driver::ToolChain::getDriver(), P, clang::driver::Driver::ResourceDir, and clang::driver::Driver::SysRoot.
AddCXXStdlibLibArgs()
void CrossWindowsToolChain::AddCXXStdlibLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 273 of file CrossWindows.cpp.
References clang::driver::ToolChain::CST_Libcxx, and clang::driver::ToolChain::GetCXXStdlibType().
buildAssembler()
Tool * CrossWindowsToolChain::buildAssembler () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 295 of file CrossWindows.cpp.
buildLinker()
Tool * CrossWindowsToolChain::buildLinker () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 291 of file CrossWindows.cpp.
GetDefaultStackProtectorLevel()
LangOptions::StackProtectorMode clang::driver::toolchains::CrossWindowsToolChain::GetDefaultStackProtectorLevel (bool KernelOrKext) const inline override virtual
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
Reimplemented from clang::driver::ToolChain.
Definition at line 64 of file CrossWindows.h.
getSupportedSanitizers()
clang::SanitizerMask CrossWindowsToolChain::getSupportedSanitizers () const override virtual
Return sanitizers which are available in this toolchain.
Reimplemented from clang::driver::ToolChain.
Definition at line 283 of file CrossWindows.cpp.
References clang::driver::ToolChain::getSupportedSanitizers().
IsIntegratedAssemblerDefault()
bool clang::driver::toolchains::CrossWindowsToolChain::IsIntegratedAssemblerDefault () const inline override virtual
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 57 of file CrossWindows.h.
isPICDefault()
bool CrossWindowsToolChain::isPICDefault () const override virtual
Test whether this toolchain defaults to PIC.
Implements clang::driver::ToolChain.
Definition at line 222 of file CrossWindows.cpp.
References clang::driver::ToolChain::getArch().
isPICDefaultForced()
bool CrossWindowsToolChain::isPICDefaultForced () const override virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault(const llvm::opt::ArgList &Args) are used exclusively.
Implements clang::driver::ToolChain.
Definition at line 230 of file CrossWindows.cpp.
References clang::driver::ToolChain::getArch().
isPIEDefault()
bool CrossWindowsToolChain::isPIEDefault (const llvm::opt::ArgList & Args) const override virtual
Test whether this toolchain defaults to PIE.
Implements clang::driver::ToolChain.
Definition at line 226 of file CrossWindows.cpp.
References clang::driver::ToolChain::getArch().
IsUnwindTablesDefault()
bool CrossWindowsToolChain::IsUnwindTablesDefault (const llvm::opt::ArgList & Args) const override virtual
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 216 of file CrossWindows.cpp.
References clang::driver::ToolChain::getArch().
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/CrossWindows.h
lib/Driver/ToolChains/CrossWindows.cpp