clang: lib/CodeGen/TargetInfo.cpp File Reference
TargetInfo.cpp File Reference
#include "TargetInfo.h"
#include "ABIInfo.h"
#include "CGBlocks.h"
#include "CGCXXABI.h"
#include "CGValue.h"
#include "CodeGenFunction.h"
#include "clang/AST/Attr.h"
#include "clang/AST/RecordLayout.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/DiagnosticFrontend.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "clang/CodeGen/SwiftCallingConv.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Namespaces
namespace clang
namespace clang::CodeGen
Functions
static ABIArgInfo coerceToIntArray (QualType Ty, ASTContext &Context, llvm::LLVMContext &LLVMContext)
static void AssignToArrayRange (CodeGen::CGBuilderTy &Builder, llvm::Value *Array, llvm::Value *Value, unsigned FirstIndex, unsigned LastIndex)
static bool isAggregateTypeForABI (QualType T)
static llvm::Type * getVAListElementType (CodeGenFunction &CGF)
static bool occupiesMoreThan (CodeGenTypes &cgt, ArrayRef< llvm::Type * > scalarTypes, unsigned maxAllRegisters)
Does the given lowering require more than the given number of registers when expanded?
static CGCXXABI::RecordArgABI getRecordArgABI (const RecordType *RT, CGCXXABI &CXXABI)
static CGCXXABI::RecordArgABI getRecordArgABI (QualType T, CGCXXABI &CXXABI)
static bool classifyReturnType (const CGCXXABI &CXXABI, CGFunctionInfo &FI, const ABIInfo &Info)
static QualType useFirstFieldIfTransparentUnion (QualType Ty)
Pass transparent unions as if they were the type of the first element.
static llvm::Value * emitRoundPointerUpToAlignment (CodeGenFunction &CGF, llvm::Value *Ptr, CharUnits Align)
static Address emitVoidPtrDirectVAArg (CodeGenFunction &CGF, Address VAListAddr, llvm::Type *DirectTy, CharUnits DirectSize, CharUnits DirectAlign, CharUnits SlotSize, bool AllowHigherAlign)
Emit va_arg for a platform using the common void* representation, where arguments are simply emitted in an array of slots on the stack.
static Address emitVoidPtrVAArg (CodeGenFunction &CGF, Address VAListAddr, QualType ValueTy, bool IsIndirect, TypeInfoChars ValueInfo, CharUnits SlotSizeAndAlign, bool AllowHigherAlign)
Emit va_arg for a platform using the common void* representation, where arguments are simply emitted in an array of slots on the stack.
static Address complexTempStructure (CodeGenFunction &CGF, Address VAListAddr, QualType Ty, CharUnits SlotSize, CharUnits EltSize, const ComplexType *CTy)
static Address emitMergePHI (CodeGenFunction &CGF, Address Addr1, llvm::BasicBlock *Block1, Address Addr2, llvm::BasicBlock *Block2, const llvm::Twine &Name="")
static bool isEmptyRecord (ASTContext &Context, QualType T, bool AllowArrays)
isEmptyRecord - Return true iff a structure contains only empty fields.
static bool isEmptyField (ASTContext &Context, const FieldDecl *FD, bool AllowArrays)
isEmptyField - Return true iff a the field is "empty", that is it is an unnamed bit-field or an (array of) empty record(s).
static const Type * isSingleElementStruct (QualType T, ASTContext &Context)
isSingleElementStruct - Determine if a structure is a "single element struct", i.e.
static void rewriteInputConstraintReferences (unsigned FirstIn, unsigned NumNewOuts, std::string &AsmString)
Rewrite input constraint references after adding some output constraints.
static bool is32Or64BitBasicType (QualType Ty, ASTContext &Context)
static bool addFieldSizes (ASTContext &Context, const RecordDecl *RD, uint64_t &Size)
static bool addBaseAndFieldSizes (ASTContext &Context, const CXXRecordDecl *RD, uint64_t &Size)
static bool isSIMDVectorType (ASTContext &Context, QualType Ty)
static bool isRecordWithSIMDVectorType (ASTContext &Context, QualType Ty)
static bool isArgInAlloca (const ABIArgInfo &Info)
static void addX86InterruptAttrs (const FunctionDecl *FD, llvm::GlobalValue *GV, CodeGen::CodeGenModule &CGM)
static bool BitsContainNoUserData (QualType Ty, unsigned StartBit, unsigned EndBit, ASTContext &Context)
BitsContainNoUserData - Return true if the specified [start,end) bit range is known to either be off the end of the specified type or being in alignment padding.
static llvm::Type * getFPTypeAtOffset (llvm::Type *IRType, unsigned IROffset, const llvm::DataLayout &TD)
getFPTypeAtOffset - Return a floating point type at the specified offset.
static llvm::Type * GetX86_64ByValArgumentPair (llvm::Type *Lo, llvm::Type *Hi, const llvm::DataLayout &TD)
GetX86_64ByValArgumentPair - Given a high and low type that can ideally be used as elements of a two register pair to pass or return, return a first class aggregate to represent them.
static Address EmitX86_64VAArgFromMemory (CodeGenFunction &CGF, Address VAListAddr, QualType Ty)
static bool PPC_initDwarfEHRegSizeTable (CodeGen::CodeGenFunction &CGF, llvm::Value *Address, bool Is64Bit, bool IsAIX)
static bool isIntegerLikeType (QualType Ty, ASTContext &Context, llvm::LLVMContext &VMContext)
static bool HexagonAdjustRegsLeft (uint64_t Size, unsigned *RegsLeft)
static bool requiresAMDGPUProtectedVisibility (const Decl *D, llvm::GlobalValue *GV)
static bool getTypeString (SmallStringEnc &Enc, const Decl *D, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC)
The XCore ABI includes a type information section that communicates symbol type information to the linker.
void clang::CodeGen::computeSPIRKernelABIInfo (CodeGenModule &CGM, CGFunctionInfo &FI)
static bool appendType (SmallStringEnc &Enc, QualType QType, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC)
Handles the type's qualifier before dispatching a call to handle specific type encodings.
static bool extractFieldType (SmallVectorImpl< FieldEncoding > &FE, const RecordDecl *RD, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC)
Helper function for appendRecordType().
static bool appendRecordType (SmallStringEnc &Enc, const RecordType *RT, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC, const IdentifierInfo *ID)
Appends structure and union types to Enc and adds encoding to cache.
static bool appendEnumType (SmallStringEnc &Enc, const EnumType *ET, TypeStringCache &TSC, const IdentifierInfo *ID)
Appends enum types to Enc and adds the encoding to the cache.
static void appendQualifier (SmallStringEnc &Enc, QualType QT)
Appends type's qualifier to Enc.
static bool appendBuiltinType (SmallStringEnc &Enc, const BuiltinType *BT)
Appends built-in types to Enc.
static bool appendPointerType (SmallStringEnc &Enc, const PointerType *PT, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC)
Appends a pointer encoding to Enc before calling appendType for the pointee.
static bool appendArrayType (SmallStringEnc &Enc, QualType QT, const ArrayType *AT, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC, StringRef NoSizeEnc)
Appends array encoding to Enc before calling appendType for the element.
static bool appendFunctionType (SmallStringEnc &Enc, const FunctionType *FT, const CodeGen::CodeGenModule &CGM, TypeStringCache &TSC)
Appends a function encoding to Enc, calling appendType for the return type and the arguments.
Function Documentation
addBaseAndFieldSizes()
static bool addBaseAndFieldSizes (ASTContext & Context, const CXXRecordDecl * RD, uint64_t & Size) static
Definition at line 1461 of file TargetInfo.cpp.
References addBaseAndFieldSizes(), addFieldSizes(), and clang::CXXRecordDecl::bases().
Referenced by addBaseAndFieldSizes().
addFieldSizes()
static bool addFieldSizes (ASTContext & Context, const RecordDecl * RD, uint64_t & Size) static
Definition at line 1441 of file TargetInfo.cpp.
References clang::RecordDecl::fields(), clang::ASTContext::getTypeSize(), and is32Or64BitBasicType().
Referenced by addBaseAndFieldSizes().
addX86InterruptAttrs()
static void addX86InterruptAttrs (const FunctionDecl * FD, llvm::GlobalValue * GV, CodeGen::CodeGenModule & CGM) static
Definition at line 2159 of file TargetInfo.cpp.
References clang::cast(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), and clang::Decl::hasAttr().
appendArrayType()
static bool appendArrayType (SmallStringEnc & Enc, QualType QT, const ArrayType * AT, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC, StringRef NoSizeEnc) static
Appends array encoding to Enc before calling appendType for the element.
Definition at line 10723 of file TargetInfo.cpp.
References appendQualifier(), appendType(), clang::ArrayType::getElementType(), clang::ArrayType::getSizeModifier(), and clang::ArrayType::Normal.
Referenced by appendType(), and getTypeString().
appendBuiltinType()
static bool appendBuiltinType (SmallStringEnc & Enc, const BuiltinType * BT) static
Appends built-in types to Enc.
Definition at line 10653 of file TargetInfo.cpp.
References clang::BuiltinType::getKind().
Referenced by appendType().
appendEnumType()
static bool appendEnumType (SmallStringEnc & Enc, const EnumType * ET, TypeStringCache & TSC, const IdentifierInfo * ID) static
Appends enum types to Enc and adds the encoding to the cache.
Definition at line 10595 of file TargetInfo.cpp.
References clang::EnumType::getDecl(), and clang::EnumDecl::getDefinition().
Referenced by appendType().
appendFunctionType()
static bool appendFunctionType (SmallStringEnc & Enc, const FunctionType * FT, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC) static
Appends a function encoding to Enc, calling appendType for the return type and the arguments.
Definition at line 10745 of file TargetInfo.cpp.
References appendType(), clang::Type::getAs(), and clang::FunctionType::getReturnType().
Referenced by appendType().
appendPointerType()
static bool appendPointerType (SmallStringEnc & Enc, const PointerType * PT, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC) static
Appends a pointer encoding to Enc before calling appendType for the pointee.
Definition at line 10712 of file TargetInfo.cpp.
References appendType(), and clang::PointerType::getPointeeType().
Referenced by appendType().
appendQualifier()
static void appendQualifier (SmallStringEnc & Enc, QualType QT) static
Appends type's qualifier to Enc.
This is done prior to appending the type's encoding.
Definition at line 10639 of file TargetInfo.cpp.
References clang::QualType::isConstQualified(), clang::QualType::isRestrictQualified(), and clang::QualType::isVolatileQualified().
Referenced by appendArrayType(), and appendType().
appendRecordType()
static bool appendRecordType (SmallStringEnc & Enc, const RecordType * RT, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC, const IdentifierInfo * ID) static
Appends structure and union types to Enc and adds encoding to cache.
Recursively calls appendType (via extractFieldType) for each field. Union types have their fields ordered according to the ABI.
Definition at line 10543 of file TargetInfo.cpp.
References extractFieldType(), clang::RecordDecl::field_empty(), clang::RecordType::getDecl(), clang::RecordDecl::getDefinition(), and clang::Type::isUnionType().
Referenced by appendType().
appendType()
static bool appendType (SmallStringEnc & Enc, QualType QType, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC) static
Handles the type's qualifier before dispatching a call to handle specific type encodings.
Definition at line 10779 of file TargetInfo.cpp.
References appendArrayType(), appendBuiltinType(), appendEnumType(), appendFunctionType(), appendPointerType(), appendQualifier(), appendRecordType(), clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::Type::getAsStructureType(), clang::Type::getAsUnionType(), clang::QualType::getBaseTypeIdentifier(), and clang::QualType::getCanonicalType().
Referenced by appendArrayType(), appendFunctionType(), appendPointerType(), extractFieldType(), and getTypeString().
AssignToArrayRange()
static void AssignToArrayRange (CodeGen::CGBuilderTy & Builder, llvm::Value * Array, llvm::Value * Value, unsigned FirstIndex, unsigned LastIndex) static
Definition at line 68 of file TargetInfo.cpp.
References clang::CharUnits::One().
Referenced by PPC_initDwarfEHRegSizeTable().
BitsContainNoUserData()
static bool BitsContainNoUserData (QualType Ty, unsigned StartBit, unsigned EndBit, ASTContext & Context) static
BitsContainNoUserData - Return true if the specified [start,end) bit range is known to either be off the end of the specified type or being in alignment padding.
The user type specified is known to be at most 128 bits in size, and have passed through X86_64ABIInfo::classify with a successful classification that put one of the two halves in the INTEGER class.
It is conservatively correct to return false.
Definition at line 3355 of file TargetInfo.cpp.
References BitsContainNoUserData(), clang::cast(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::Type::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::RecordType::getDecl(), clang::ASTRecordLayout::getFieldOffset(), clang::ASTContext::getTypeSize(), and clang::ASTContext::toBits().
Referenced by BitsContainNoUserData().
classifyReturnType()
static bool classifyReturnType (const CGCXXABI & CXXABI, CGFunctionInfo & FI, const ABIInfo & Info) static
Definition at line 181 of file TargetInfo.cpp.
References clang::Type::getAs(), clang::CodeGen::ABIInfo::getNaturalAlignIndirect(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), and clang::CodeGen::CGFunctionInfo::getReturnType().
coerceToIntArray()
static ABIArgInfo coerceToIntArray (QualType Ty, ASTContext & Context, llvm::LLVMContext & LLVMContext) static
Definition at line 57 of file TargetInfo.cpp.
References clang::CodeGen::ABIArgInfo::getDirect(), clang::ASTContext::getTypeAlign(), and clang::ASTContext::getTypeSize().
complexTempStructure()
static Address complexTempStructure (CodeGenFunction & CGF, Address VAListAddr, QualType Ty, CharUnits SlotSize, CharUnits EltSize, const ComplexType * CTy) static
Definition at line 404 of file TargetInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CodeGenFunction::EmitStoreOfComplex(), emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::ComplexType::getElementType(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
emitMergePHI()
static Address emitMergePHI (CodeGenFunction & CGF, Address Addr1, llvm::BasicBlock * Block1, Address Addr2, llvm::BasicBlock * Block2, const llvm::Twine & Name = "") static
Definition at line 434 of file TargetInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and clang::CodeGen::Address::getType().
emitRoundPointerUpToAlignment()
static llvm::Value * emitRoundPointerUpToAlignment (CodeGenFunction & CGF, llvm::Value * Ptr, CharUnits Align) static
Definition at line 290 of file TargetInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CharUnits::getQuantity(), and clang::CodeGen::CodeGenTypeCache::IntPtrTy.
Referenced by emitVoidPtrDirectVAArg(), and EmitX86_64VAArgFromMemory().
emitVoidPtrDirectVAArg()
static Address emitVoidPtrDirectVAArg (CodeGenFunction & CGF, Address VAListAddr, llvm::Type * DirectTy, CharUnits DirectSize, CharUnits DirectAlign, CharUnits SlotSize, bool AllowHigherAlign) static
Emit va_arg for a platform using the common void* representation, where arguments are simply emitted in an array of slots on the stack.
This version implements the core direct-value passing rules.
Parameters
SlotSize - The size and alignment of a stack slot. Each argument will be allocated to a multiple of this number of slots, and all the slots will be aligned to this value.
AllowHigherAlign - The slot alignment is not a cap; an argument type with an alignment greater than the slot size will be emitted on a higher-alignment address, potentially leaving one or more empty slots behind as padding. If this is false, the returned address might be less-aligned than DirectAlign.
Definition at line 320 of file TargetInfo.cpp.
References clang::CharUnits::alignTo(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), emitRoundPointerUpToAlignment(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CodeGen::Address::invalid().
Referenced by complexTempStructure(), and emitVoidPtrVAArg().
emitVoidPtrVAArg()
static Address emitVoidPtrVAArg (CodeGenFunction & CGF, Address VAListAddr, QualType ValueTy, bool IsIndirect, TypeInfoChars ValueInfo, CharUnits SlotSizeAndAlign, bool AllowHigherAlign) static
Emit va_arg for a platform using the common void* representation, where arguments are simply emitted in an array of slots on the stack.
Parameters
IsIndirect - Values of this type are passed indirectly.
ValueInfo - The size and alignment of this type, generally computed with getContext().getTypeInfoInChars(ValueTy).
SlotSizeAndAlign - The size and alignment of a stack slot. Each argument will be allocated to a multiple of this number of slots, and all the slots will be aligned to this value.
AllowHigherAlign - The slot alignment is not a cap; an argument type with an alignment greater than the slot size will be emitted on a higher-alignment address, potentially leaving one or more empty slots behind as padding.
Definition at line 373 of file TargetInfo.cpp.
References clang::TypeInfoChars::Align, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateLoad(), emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenTypeCache::getPointerSize(), and clang::TypeInfoChars::Width.
EmitX86_64VAArgFromMemory()
static Address EmitX86_64VAArgFromMemory (CodeGenFunction & CGF, Address VAListAddr, QualType Ty) static
Definition at line 4038 of file TargetInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateGEP(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), emitRoundPointerUpToAlignment(), clang::CharUnits::fromQuantity(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getTypeAlignInChars(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8Ty, and Offset.
extractFieldType()
static bool extractFieldType (SmallVectorImpl< FieldEncoding > & FE, const RecordDecl * RD, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC) static
Helper function for appendRecordType().
Builds a SmallVector containing the encoded field types in declaration order.
Definition at line 10515 of file TargetInfo.cpp.
References appendType(), clang::RecordDecl::fields(), and clang::CodeGen::CodeGenModule::getContext().
Referenced by appendRecordType().
getFPTypeAtOffset()
static llvm::Type * getFPTypeAtOffset (llvm::Type * IRType, unsigned IROffset, const llvm::DataLayout & TD) static
getFPTypeAtOffset - Return a floating point type at the specified offset.
Definition at line 3433 of file TargetInfo.cpp.
References getFPTypeAtOffset().
Referenced by getFPTypeAtOffset().
getRecordArgABI() [1/2]
static CGCXXABI::RecordArgABI getRecordArgABI (const RecordType * RT, CGCXXABI & CXXABI) static
Definition at line 162 of file TargetInfo.cpp.
References clang::RecordDecl::canPassInRegisters(), clang::RecordType::getDecl(), clang::CodeGen::CGCXXABI::RAA_Default, and clang::CodeGen::CGCXXABI::RAA_Indirect.
Referenced by getRecordArgABI().
getRecordArgABI() [2/2]
static CGCXXABI::RecordArgABI getRecordArgABI (QualType T, CGCXXABI & CXXABI) static
Definition at line 173 of file TargetInfo.cpp.
References clang::Type::getAs(), getRecordArgABI(), and clang::CodeGen::CGCXXABI::RAA_Default.
getTypeString()
static bool getTypeString (SmallStringEnc & Enc, const Decl * D, const CodeGen::CodeGenModule & CGM, TypeStringCache & TSC) static
The XCore ABI includes a type information section that communicates symbol type information to the linker.
The linker uses this information to verify safety/correctness of things such as array bound and pointers et al. The ABI only requires C (and XC) language modules to emit TypeStrings. This type information (TypeString) is emitted into meta data for all global symbols: definitions, declarations, functions & variables.
The TypeString carries type, qualifier, name, size & value details. Please see 'Tools Development Guide' section 2.16.2 for format details: https://www.xmos.com/download/public/Tools-Development-Guide%28X9114A%29.pdf The output is tested by test/CodeGen/xcore-stringtype.c.
Definition at line 10813 of file TargetInfo.cpp.
References appendArrayType(), appendType(), clang::CLanguageLinkage, clang::Type::getAsArrayTypeUnsafe(), clang::QualType::getCanonicalType(), clang::FunctionDecl::getLanguageLinkage(), clang::VarDecl::getLanguageLinkage(), and clang::ValueDecl::getType().
getVAListElementType()
static llvm::Type * getVAListElementType (CodeGenFunction & CGF) static
Definition at line 104 of file TargetInfo.cpp.
References clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::ASTContext::getBuiltinVaListType(), clang::CodeGen::CodeGenFunction::getContext(), and clang::Type::getPointeeType().
GetX86_64ByValArgumentPair()
static llvm::Type * GetX86_64ByValArgumentPair (llvm::Type * Lo, llvm::Type * Hi, const llvm::DataLayout & TD) static
GetX86_64ByValArgumentPair - Given a high and low type that can ideally be used as elements of a two register pair to pass or return, return a first class aggregate to represent them.
For example, if the low part of a by-value argument should be passed as i32* and the high part as float, return {i32*, float}.
Definition at line 3591 of file TargetInfo.cpp.
References clang::Result.
HexagonAdjustRegsLeft()
static bool HexagonAdjustRegsLeft (uint64_t Size, unsigned * RegsLeft) static
Definition at line 8572 of file TargetInfo.cpp.
is32Or64BitBasicType()
static bool is32Or64BitBasicType (QualType Ty, ASTContext & Context) static
Definition at line 1425 of file TargetInfo.cpp.
References clang::Type::getAs(), clang::ASTContext::getTypeSize(), clang::Type::hasPointerRepresentation(), clang::Type::isBlockPointerType(), and clang::Type::isEnumeralType().
Referenced by addFieldSizes().
isAggregateTypeForABI()
static bool isAggregateTypeForABI (QualType T) static
Definition at line 81 of file TargetInfo.cpp.
Referenced by isSingleElementStruct().
isArgInAlloca()
static bool isArgInAlloca (const ABIArgInfo & Info) static
Definition at line 2050 of file TargetInfo.cpp.
References clang::CodeGen::ABIArgInfo::CoerceAndExpand, clang::CodeGen::ABIArgInfo::Direct, clang::CodeGen::ABIArgInfo::Expand, clang::CodeGen::ABIArgInfo::Extend, clang::CodeGen::ABIArgInfo::getInReg(), clang::CodeGen::ABIArgInfo::getKind(), clang::CodeGen::ABIArgInfo::Ignore, clang::CodeGen::ABIArgInfo::InAlloca, clang::CodeGen::ABIArgInfo::Indirect, and clang::CodeGen::ABIArgInfo::IndirectAliased.
isEmptyField()
static bool isEmptyField (ASTContext & Context, const FieldDecl * FD, bool AllowArrays) static
isEmptyField - Return true iff a the field is "empty", that is it is an unnamed bit-field or an (array of) empty record(s).
Definition at line 542 of file TargetInfo.cpp.
References clang::Type::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::RecordType::getDecl(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), isEmptyRecord(), and clang::FieldDecl::isUnnamedBitfield().
Referenced by isEmptyRecord(), and isSingleElementStruct().
isEmptyRecord()
static bool isEmptyRecord (ASTContext & Context, QualType T, bool AllowArrays) static
isEmptyRecord - Return true iff a structure contains only empty fields.
Note that a structure with a flexible array member is not considered empty.
Definition at line 586 of file TargetInfo.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), clang::RecordType::getDecl(), clang::RecordDecl::hasFlexibleArrayMember(), isEmptyField(), and isEmptyRecord().
Referenced by isEmptyField(), isEmptyRecord(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), and isSingleElementStruct().
isIntegerLikeType()
static bool isIntegerLikeType (QualType Ty, ASTContext & Context, llvm::LLVMContext & VMContext) static
Definition at line 6727 of file TargetInfo.cpp.
References clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::Type::getAs(), clang::ASTContext::getASTRecordLayout(), clang::RecordType::getDecl(), clang::ASTRecordLayout::getFieldOffset(), clang::ValueDecl::getType(), clang::ASTContext::getTypeSize(), clang::RecordDecl::hasFlexibleArrayMember(), clang::FieldDecl::isBitField(), isIntegerLikeType(), clang::Type::isPointerType(), clang::Type::isRealFloatingType(), clang::TagDecl::isUnion(), and clang::Type::isVectorType().
Referenced by isIntegerLikeType().
isRecordWithSIMDVectorType()
static bool isRecordWithSIMDVectorType (ASTContext & Context, QualType Ty) static
Definition at line 1619 of file TargetInfo.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), clang::RecordType::getDecl(), isRecordWithSIMDVectorType(), and isSIMDVectorType().
Referenced by isRecordWithSIMDVectorType().
isSIMDVectorType()
static bool isSIMDVectorType (ASTContext & Context, QualType Ty) static
Definition at line 1615 of file TargetInfo.cpp.
References clang::Type::getAs(), and clang::ASTContext::getTypeSize().
Referenced by isRecordWithSIMDVectorType().
isSingleElementStruct()
static const Type * isSingleElementStruct (QualType T, ASTContext & Context) static
isSingleElementStruct - Determine if a structure is a "single element struct", i.e.
it has exactly one non-empty field or exactly one field which is itself a single element struct. Structures with flexible array members are never considered single element structs.
Returns
The field declaration for the single non-empty field, if it exists.
Definition at line 614 of file TargetInfo.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::RecordType::getDecl(), clang::QualType::getTypePtr(), clang::ASTContext::getTypeSize(), clang::RecordDecl::hasFlexibleArrayMember(), isAggregateTypeForABI(), isEmptyField(), isEmptyRecord(), and isSingleElementStruct().
Referenced by isSingleElementStruct().
occupiesMoreThan()
static bool occupiesMoreThan (CodeGenTypes & cgt, ArrayRef< llvm::Type * > scalarTypes, unsigned maxAllRegisters) static
Does the given lowering require more than the given number of registers when expanded?
This is intended to be the basis of a reasonable basic implementation of should{Pass,Return}IndirectlyForSwift.
For most targets, a limit of four total registers is reasonable; this limits the amount of code required in order to move around the value in case it wasn't produced immediately prior to the call by the caller (or wasn't produced in exactly the right registers) or isn't used immediately within the callee. But some targets may need to further limit the register count due to an inability to support that many return registers.
Definition at line 135 of file TargetInfo.cpp.
References clang::TargetInfo::getPointerWidth(), and clang::CodeGen::CodeGenTypes::getTarget().
PPC_initDwarfEHRegSizeTable()
static bool PPC_initDwarfEHRegSizeTable (CodeGen::CodeGenFunction & CGF, llvm::Value * Address, bool Is64Bit, bool IsAIX) static
Definition at line 4480 of file TargetInfo.cpp.
References AssignToArrayRange(), clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenTypeCache::Int8Ty.
requiresAMDGPUProtectedVisibility()
static bool requiresAMDGPUProtectedVisibility (const Decl * D, llvm::GlobalValue * GV) static
Definition at line 9340 of file TargetInfo.cpp.
References clang::cast(), clang::Decl::hasAttr(), and clang::isa().
rewriteInputConstraintReferences()
static void rewriteInputConstraintReferences (unsigned FirstIn, unsigned NumNewOuts, std::string & AsmString) static
Rewrite input constraint references after adding some output constraints.
In the case where there is one output and one input and we add one output, we need to replace all operand references greater than or equal to 1: mov $0, $1 mov eax, $1 The result will be: mov $0, $2 mov eax, $2
Definition at line 1299 of file TargetInfo.cpp.
useFirstFieldIfTransparentUnion()
static QualType useFirstFieldIfTransparentUnion (QualType Ty) static
Pass transparent unions as if they were the type of the first element.
Sema should ensure that all elements of the union have the same "machine type".
Definition at line 197 of file TargetInfo.cpp.
References clang::RecordDecl::field_begin(), clang::RecordDecl::field_empty(), clang::Type::getAsUnionType(), and clang::Decl::hasAttr().