clang: lib/Driver/ToolChains/CommonArgs.cpp File Reference
CommonArgs.cpp File Reference
#include "CommonArgs.h"
#include "Arch/AArch64.h"
#include "Arch/ARM.h"
#include "Arch/M68k.h"
#include "Arch/Mips.h"
#include "Arch/PPC.h"
#include "Arch/Sparc.h"
#include "Arch/SystemZ.h"
#include "Arch/VE.h"
#include "Arch/X86.h"
#include "HIPAMD.h"
#include "Hexagon.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/Version.h"
#include "clang/Config/config.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "clang/Driver/ToolChain.h"
#include "clang/Driver/Util.h"
#include "clang/Driver/XRayArgs.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/YAMLParser.h"
Enumerations
enum class LibGccType { UnspecifiedLibGcc , StaticLibGcc , SharedLibGcc }
Functions
static void renderRpassOptions (const ArgList &Args, ArgStringList &CmdArgs)
static void renderRemarksOptions (const ArgList &Args, ArgStringList &CmdArgs, const llvm::Triple &Triple, const InputInfo &Input, const InputInfo &Output)
static void renderRemarksHotnessOptions (const ArgList &Args, ArgStringList &CmdArgs)
static std::string getAMDGPUTargetGPU (const llvm::Triple &T, const ArgList &Args)
Get the (LLVM) name of the AMDGPU gpu we are targeting.
static std::string getLanaiTargetCPU (const ArgList &Args)
static StringRef getWebAssemblyTargetCPU (const ArgList &Args)
Get the (LLVM) name of the WebAssembly cpu we are targeting.
static void addSanitizerRuntime (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs, StringRef Sanitizer, bool IsShared, bool IsWhole)
static bool addSanitizerDynamicList (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs, StringRef Sanitizer)
static void collectSanitizerRuntimes (const ToolChain &TC, const ArgList &Args, SmallVectorImpl< StringRef > &SharedRuntimes, SmallVectorImpl< StringRef > &StaticRuntimes, SmallVectorImpl< StringRef > &NonWholeStaticRuntimes, SmallVectorImpl< StringRef > &HelperStaticRuntimes, SmallVectorImpl< StringRef > &RequiredSymbols)
static LibGccType getLibGccType (const ToolChain &TC, const Driver &D, const ArgList &Args)
static void AddUnwindLibrary (const ToolChain &TC, const Driver &D, ArgStringList &CmdArgs, const ArgList &Args)
static void AddLibgcc (const ToolChain &TC, const Driver &D, ArgStringList &CmdArgs, const ArgList &Args)
static llvm::opt::Arg * getAMDGPUCodeObjectArgument (const Driver &D, const llvm::opt::ArgList &Args)
Enumeration Type Documentation
LibGccType
enum class LibGccType strong
Enumerator
UnspecifiedLibGcc
StaticLibGcc
SharedLibGcc
Definition at line 1478 of file CommonArgs.cpp.
Function Documentation
AddLibgcc()
static void AddLibgcc (const ToolChain & TC, const Driver & D, ArgStringList & CmdArgs, const ArgList & Args) static
Definition at line 1557 of file CommonArgs.cpp.
References AddUnwindLibrary(), clang::driver::Driver::CCCIsCXX(), getLibGccType(), SharedLibGcc, StaticLibGcc, and UnspecifiedLibGcc.
addSanitizerDynamicList()
static bool addSanitizerDynamicList (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs, StringRef Sanitizer) static
Definition at line 796 of file CommonArgs.cpp.
References clang::driver::ToolChain::getCompilerRT(), and clang::driver::ToolChain::getTriple().
addSanitizerRuntime()
static void addSanitizerRuntime (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs, StringRef Sanitizer, bool IsShared, bool IsWhole) static
Definition at line 779 of file CommonArgs.cpp.
References clang::driver::tools::addArchSpecificRPath(), clang::driver::ToolChain::FT_Shared, clang::driver::ToolChain::FT_Static, and clang::driver::ToolChain::getCompilerRTArgString().
AddUnwindLibrary()
static void AddUnwindLibrary (const ToolChain & TC, const Driver & D, ArgStringList & CmdArgs, const ArgList & Args) static
Definition at line 1505 of file CommonArgs.cpp.
References clang::driver::Driver::CCCIsCXX(), clang::driver::tools::getAsNeededOption(), getLibGccType(), clang::driver::ToolChain::getTriple(), clang::driver::ToolChain::GetUnwindLibType(), SharedLibGcc, StaticLibGcc, UnspecifiedLibGcc, clang::driver::ToolChain::UNW_CompilerRT, clang::driver::ToolChain::UNW_Libgcc, and clang::driver::ToolChain::UNW_None.
Referenced by AddLibgcc().
collectSanitizerRuntimes()
static void collectSanitizerRuntimes (const ToolChain & TC, const ArgList & Args, SmallVectorImpl< StringRef > & SharedRuntimes, SmallVectorImpl< StringRef > & StaticRuntimes, SmallVectorImpl< StringRef > & NonWholeStaticRuntimes, SmallVectorImpl< StringRef > & HelperStaticRuntimes, SmallVectorImpl< StringRef > & RequiredSymbols) static
Definition at line 856 of file CommonArgs.cpp.
References clang::driver::ToolChain::getSanitizerArgs(), clang::driver::ToolChain::getTriple(), clang::driver::SanitizerArgs::linkCXXRuntimes(), clang::driver::SanitizerArgs::linkRuntimes(), clang::driver::SanitizerArgs::needsAsanRt(), clang::driver::SanitizerArgs::needsCfiDiagRt(), clang::driver::SanitizerArgs::needsCfiRt(), clang::driver::SanitizerArgs::needsDfsanRt(), clang::driver::SanitizerArgs::needsHwasanAliasesRt(), clang::driver::SanitizerArgs::needsHwasanRt(), clang::driver::SanitizerArgs::needsLsanRt(), clang::driver::SanitizerArgs::needsMemProfRt(), clang::driver::SanitizerArgs::needsMsanRt(), clang::driver::SanitizerArgs::needsSafeStackRt(), clang::driver::SanitizerArgs::needsScudoRt(), clang::driver::SanitizerArgs::needsSharedRt(), clang::driver::SanitizerArgs::needsStatsRt(), clang::driver::SanitizerArgs::needsTsanRt(), clang::driver::SanitizerArgs::needsUbsanRt(), and clang::driver::SanitizerArgs::requiresMinimalRuntime().
getAMDGPUCodeObjectArgument()
static llvm::opt::Arg * getAMDGPUCodeObjectArgument (const Driver & D, const llvm::opt::ArgList & Args) static
Definition at line 1978 of file CommonArgs.cpp.
Referenced by clang::driver::tools::checkAMDGPUCodeObjectVersion(), clang::driver::tools::getAMDGPUCodeObjectVersion(), and clang::driver::tools::haveAMDGPUCodeObjectVersionArgument().
getAMDGPUTargetGPU()
static std::string getAMDGPUTargetGPU (const llvm::Triple & T, const ArgList & Args) static
Get the (LLVM) name of the AMDGPU gpu we are targeting.
Definition at line 309 of file CommonArgs.cpp.
References clang::getProcessorFromTargetID().
getLanaiTargetCPU()
static std::string getLanaiTargetCPU (const ArgList & Args) static
Definition at line 326 of file CommonArgs.cpp.
getLibGccType()
static LibGccType getLibGccType (const ToolChain & TC, const Driver & D, const ArgList & Args) static
Definition at line 1480 of file CommonArgs.cpp.
References clang::driver::ToolChain::getTriple(), SharedLibGcc, StaticLibGcc, and UnspecifiedLibGcc.
Referenced by AddLibgcc(), and AddUnwindLibrary().
getWebAssemblyTargetCPU()
static StringRef getWebAssemblyTargetCPU (const ArgList & Args) static
Get the (LLVM) name of the WebAssembly cpu we are targeting.
Definition at line 334 of file CommonArgs.cpp.
renderRemarksHotnessOptions()
static void renderRemarksHotnessOptions (const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 111 of file CommonArgs.cpp.
renderRemarksOptions()
static void renderRemarksOptions (const ArgList & Args, ArgStringList & CmdArgs, const llvm::Triple & Triple, const InputInfo & Input, const InputInfo & Output) static
Definition at line 81 of file CommonArgs.cpp.
References clang::driver::InputInfo::getFilename(), and clang::driver::InputInfo::isFilename().
renderRpassOptions()
static void renderRpassOptions (const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 67 of file CommonArgs.cpp.