clang: lib/Frontend/CompilerInvocation.cpp File Reference
CompilerInvocation.cpp File Reference
#include "clang/Frontend/CompilerInvocation.h"
#include "TestModuleFileExtension.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/CommentOptions.h"
#include "clang/Basic/DebugInfoOptions.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticDriver.h"
#include "clang/Basic/DiagnosticOptions.h"
#include "clang/Basic/FileSystemOptions.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/LangStandard.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/Sanitizers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/TargetOptions.h"
#include "clang/Basic/Version.h"
#include "clang/Basic/Visibility.h"
#include "clang/Basic/XRayInstr.h"
#include "clang/Config/config.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Frontend/CommandLineSourceLoc.h"
#include "clang/Frontend/DependencyOutputOptions.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/FrontendOptions.h"
#include "clang/Frontend/FrontendPluginRegistry.h"
#include "clang/Frontend/MigratorOptions.h"
#include "clang/Frontend/PreprocessorOutputOptions.h"
#include "clang/Frontend/TextDiagnosticBuffer.h"
#include "clang/Frontend/Utils.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Sema/CodeCompleteOptions.h"
#include "clang/Serialization/ASTBitCodes.h"
#include "clang/Serialization/ModuleFileExtension.h"
#include "clang/StaticAnalyzer/Core/AnalyzerOptions.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/CachedHashString.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/FloatingPointMode.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/Linker/Linker.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/OptSpecifier.h"
#include "llvm/Option/OptTable.h"
#include "llvm/Option/Option.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Remarks/HotnessThresholdParser.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/HashBuilder.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/VersionTuple.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <atomic>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <fstream>
#include <memory>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include "clang/Driver/Options.inc"
#include "clang/StaticAnalyzer/Core/Analyses.def"
#include "clang/StaticAnalyzer/Core/AnalyzerOptions.def"
#include "clang/Basic/LangStandards.def"
#include "clang/Basic/LangOptions.def"
#include "clang/Basic/DiagnosticOptions.def"
Macros
#define SIMPLE_ENUM_VALUE_TABLE
#define PARSE_OPTION_WITH_MARSHALLING(ARGS, DIAGS, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
#define GENERATE_OPTION_WITH_MARSHALLING(ARGS, STRING_ALLOCATOR, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
#define ANALYZER_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define ANALYSIS_CONSTRAINTS(NAME, CMDFLAG, DESC, CREATFN)
#define ANALYSIS_DIAGNOSTICS(NAME, CMDFLAG, DESC, CREATFN)
#define ANALYSIS_PURGE(NAME, CMDFLAG, DESC)
#define ANALYSIS_INLINING_MODE(NAME, CMDFLAG, DESC)
#define ANALYZER_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define ANALYSIS_CONSTRAINTS(NAME, CMDFLAG, DESC, CREATFN)
#define ANALYSIS_DIAGNOSTICS(NAME, CMDFLAG, DESC, CREATFN)
#define ANALYSIS_PURGE(NAME, CMDFLAG, DESC)
#define ANALYSIS_INLINING_MODE(NAME, CMDFLAG, DESC)
#define ANALYZER_OPTION(TYPE, NAME, CMDFLAG, DESC, DEFAULT_VAL)
#define ANALYZER_OPTION_DEPENDS_ON_USER_MODE(...)
#define ANALYZER_OPTION(...)
#define ANALYZER_OPTION_DEPENDS_ON_USER_MODE(TYPE, NAME, CMDFLAG, DESC, SHALLOW_VAL, DEEP_VAL)
#define CODEGEN_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define CODEGEN_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define FILE_SYSTEM_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define FILE_SYSTEM_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define MIGRATOR_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define MIGRATOR_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define DIAG_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define DIAG_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define FRONTEND_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define FRONTEND_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define HEADER_SEARCH_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define HEADER_SEARCH_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define LANG_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define LANGSTANDARD(id, name, lang, desc, features)
#define LANGSTANDARD_ALIAS(id, alias)
#define LANGSTANDARD_ALIAS_DEPR(id, alias)
#define LANGSTANDARD(id, name, lang, desc, features)
#define LANGSTANDARD_ALIAS(id, alias)
#define LANGSTANDARD_ALIAS_DEPR(id, alias)
#define LANG_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define PREPROCESSOR_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define PREPROCESSOR_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define TARGET_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define TARGET_OPTION_WITH_MARSHALLING(PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
#define LANGOPT(Name, Bits, Default, Description)
#define ENUM_LANGOPT(Name, Type, Bits, Default, Description)
#define BENIGN_LANGOPT(Name, Bits, Default, Description)
#define BENIGN_ENUM_LANGOPT(Name, Type, Bits, Default, Description)
#define DIAGOPT(Name, Bits, Default)
#define ENUM_DIAGOPT(Name, Type, Bits, Default)
Typedefs
using ParseFn
using GenerateFn
Functions
Expected< Optional< uint64_t > > parseToleranceOption (StringRef Arg)
static llvm::Optional< bool > normalizeSimpleFlag (OptSpecifier Opt, unsigned TableIndex, const ArgList &Args, DiagnosticsEngine &Diags)
static Optional< bool > normalizeSimpleNegativeFlag (OptSpecifier Opt, unsigned, const ArgList &Args, DiagnosticsEngine &)
static void denormalizeSimpleFlag (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator, Option::OptionClass, unsigned,...)
The tblgen-erated code passes in a fifth parameter of an arbitrary type, but denormalizeSimpleFlags never looks at it.
template<typename T >
static constexpr bool is_uint64_t_convertible ()
template<typename T , std::enable_if_t<!is_uint64_t_convertible< T >(), bool > = false>
static auto makeFlagToValueNormalizer (T Value)
static auto makeBooleanOptionNormalizer (bool Value, bool OtherValue, OptSpecifier OtherOpt)
static auto makeBooleanOptionDenormalizer (bool Value)
static void denormalizeStringImpl (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned, const Twine &Value)
template<typename T >
static void denormalizeString (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, T Value)
static Optional< SimpleEnumValue > findValueTableByName (const SimpleEnumValueTable &Table, StringRef Name)
static Optional< SimpleEnumValue > findValueTableByValue (const SimpleEnumValueTable &Table, unsigned Value)
static llvm::Optional< unsigned > normalizeSimpleEnum (OptSpecifier Opt, unsigned TableIndex, const ArgList &Args, DiagnosticsEngine &Diags)
static void denormalizeSimpleEnumImpl (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, unsigned Value)
template<typename T >
static void denormalizeSimpleEnum (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, T Value)
static Optional< std::string > normalizeString (OptSpecifier Opt, int TableIndex, const ArgList &Args, DiagnosticsEngine &Diags)
template<typename IntTy >
static Optional< IntTy > normalizeStringIntegral (OptSpecifier Opt, int, const ArgList &Args, DiagnosticsEngine &Diags)
static Optional< std::vector< std::string > > normalizeStringVector (OptSpecifier Opt, int, const ArgList &Args, DiagnosticsEngine &)
static void denormalizeStringVector (SmallVectorImpl< const char * > &Args, const char *Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, const std::vector< std::string > &Values)
static Optional< std::string > normalizeTriple (OptSpecifier Opt, int TableIndex, const ArgList &Args, DiagnosticsEngine &Diags)
template<typename T , typename U >
static T mergeForwardValue (T KeyPath, U Value)
template<typename T , typename U >
static T mergeMaskValue (T KeyPath, U Value)
template<typename T >
static T extractForwardValue (T KeyPath)
template<typename T , typename U , U Value>
static T extractMaskValue (T KeyPath)
static StringRef GetInputKindName (InputKind IK)
Get language name for given input kind.
static bool FixupInvocation (CompilerInvocation &Invocation, DiagnosticsEngine &Diags, const ArgList &Args, InputKind IK)
static unsigned getOptimizationLevel (ArgList &Args, InputKind IK, DiagnosticsEngine &Diags)
static unsigned getOptimizationLevelSize (ArgList &Args)
static void GenerateArg (SmallVectorImpl< const char * > &Args, llvm::opt::OptSpecifier OptSpecifier, CompilerInvocation::StringAllocator SA)
static void GenerateArg (SmallVectorImpl< const char * > &Args, llvm::opt::OptSpecifier OptSpecifier, const Twine &Value, CompilerInvocation::StringAllocator SA)
static bool RoundTrip (ParseFn Parse, GenerateFn Generate, CompilerInvocation &RealInvocation, CompilerInvocation &DummyInvocation, ArrayRef< const char * > CommandLineArgs, DiagnosticsEngine &Diags, const char *Argv0)
static void addDiagnosticArgs (ArgList &Args, OptSpecifier Group, OptSpecifier GroupWithValue, std::vector< std::string > &Diagnostics)
static void parseAnalyzerConfigs (AnalyzerOptions &AnOpts, DiagnosticsEngine *Diags)
static void getAllNoBuiltinFuncValues (ArgList &Args, std::vector< std::string > &Funcs)
static void GenerateAnalyzerArgs (AnalyzerOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseAnalyzerArgs (AnalyzerOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags)
static StringRef getStringOption (AnalyzerOptions::ConfigTable &Config, StringRef OptionName, StringRef DefaultVal)
static void initOption (AnalyzerOptions::ConfigTable &Config, DiagnosticsEngine *Diags, StringRef &OptionField, StringRef Name, StringRef DefaultVal)
static void initOption (AnalyzerOptions::ConfigTable &Config, DiagnosticsEngine *Diags, bool &OptionField, StringRef Name, bool DefaultVal)
static void initOption (AnalyzerOptions::ConfigTable &Config, DiagnosticsEngine *Diags, unsigned &OptionField, StringRef Name, unsigned DefaultVal)
static void GenerateOptimizationRemark (SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA, OptSpecifier OptEQ, StringRef Name, const CodeGenOptions::OptRemark &Remark)
Generate a remark argument. This is an inverse of ParseOptimizationRemark.
static CodeGenOptions::OptRemark ParseOptimizationRemark (DiagnosticsEngine &Diags, ArgList &Args, OptSpecifier OptEQ, StringRef Name)
Parse a remark command line argument.
static bool parseDiagnosticLevelMask (StringRef FlagName, const std::vector< std::string > &Levels, DiagnosticsEngine &Diags, DiagnosticLevelMask &M)
static void parseSanitizerKinds (StringRef FlagName, const std::vector< std::string > &Sanitizers, DiagnosticsEngine &Diags, SanitizerSet &S)
static SmallVector< StringRef, 4 > serializeSanitizerKinds (SanitizerSet S)
static void parseXRayInstrumentationBundle (StringRef FlagName, StringRef Bundle, ArgList &Args, DiagnosticsEngine &D, XRayInstrSet &S)
static std::string serializeXRayInstrumentationBundle (const XRayInstrSet &S)
static void setPGOUseInstrumentor (CodeGenOptions &Opts, const Twine &ProfileName)
static void GenerateDependencyOutputArgs (const DependencyOutputOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseDependencyOutputArgs (DependencyOutputOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags, frontend::ActionKind Action, bool ShowLineMarkers)
static bool parseShowColorsArgs (const ArgList &Args, bool DefaultColor)
static bool checkVerifyPrefixes (const std::vector< std::string > &VerifyPrefixes, DiagnosticsEngine &Diags)
static void GenerateFileSystemArgs (const FileSystemOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseFileSystemArgs (FileSystemOptions &Opts, const ArgList &Args, DiagnosticsEngine &Diags)
static void GenerateMigratorArgs (const MigratorOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseMigratorArgs (MigratorOptions &Opts, const ArgList &Args, DiagnosticsEngine &Diags)
static bool parseTestModuleFileExtensionArg (StringRef Arg, std::string &BlockName, unsigned &MajorVersion, unsigned &MinorVersion, bool &Hashed, std::string &UserInfo)
Parse the argument to the -ftest-module-file-extension command-line argument.
static const auto & getFrontendActionTable ()
Return a table that associates command line option specifiers with the frontend action.
static Optional< frontend::ActionKind > getFrontendAction (OptSpecifier &Opt)
Maps command line option to frontend action.
static Optional< OptSpecifier > getProgramActionOpt (frontend::ActionKind ProgramAction)
Maps frontend action to command line option.
static void GenerateFrontendArgs (const FrontendOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA, bool IsHeader)
static bool ParseFrontendArgs (FrontendOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags, bool &IsHeaderFile)
static void GenerateHeaderSearchArgs (HeaderSearchOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseHeaderSearchArgs (HeaderSearchOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags, const std::string &WorkingDir)
static bool IsInputCompatibleWithStandard (InputKind IK, const LangStandard &S)
Check if input file kind and language standard are compatible.
static bool isStrictlyPreprocessorAction (frontend::ActionKind Action)
static void GeneratePreprocessorArgs (PreprocessorOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA, const LangOptions &LangOpts, const FrontendOptions &FrontendOpts, const CodeGenOptions &CodeGenOpts)
static bool ParsePreprocessorArgs (PreprocessorOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags, frontend::ActionKind Action, const FrontendOptions &FrontendOpts)
static void GeneratePreprocessorOutputArgs (const PreprocessorOutputOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA, frontend::ActionKind Action)
static bool ParsePreprocessorOutputArgs (PreprocessorOutputOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags, frontend::ActionKind Action)
static void GenerateTargetArgs (const TargetOptions &Opts, SmallVectorImpl< const char * > &Args, CompilerInvocation::StringAllocator SA)
static bool ParseTargetArgs (TargetOptions &Opts, ArgList &Args, DiagnosticsEngine &Diags)
Macro Definition Documentation
ANALYSIS_CONSTRAINTS [1/2]
#define ANALYSIS_CONSTRAINTS (NAME, CMDFLAG, DESC, CREATFN)
Value:
  case NAME##Model:                                                            \
    GenerateArg(Args, OPT_analyzer_constraints, CMDFLAG, SA);                  \
    break;
ANALYSIS_CONSTRAINTS [2/2]
#define ANALYSIS_CONSTRAINTS (NAME, CMDFLAG, DESC, CREATFN)
Value:
      .Case(CMDFLAG, NAME##Model)
ANALYSIS_DIAGNOSTICS [1/2]
#define ANALYSIS_DIAGNOSTICS (NAME, CMDFLAG, DESC, CREATFN)
Value:
  case PD_##NAME:                                                              \
    GenerateArg(Args, OPT_analyzer_output, CMDFLAG, SA);                       \
    break;
ANALYSIS_DIAGNOSTICS [2/2]
#define ANALYSIS_DIAGNOSTICS (NAME, CMDFLAG, DESC, CREATFN)
Value:
      .Case(CMDFLAG, PD_##NAME)
ANALYSIS_INLINING_MODE [1/2]
#define ANALYSIS_INLINING_MODE (NAME, CMDFLAG, DESC)
Value:
  case NAME:                                                                   \
    GenerateArg(Args, OPT_analyzer_inlining_mode, CMDFLAG, SA);                \
    break;
ANALYSIS_INLINING_MODE [2/2]
#define ANALYSIS_INLINING_MODE (NAME, CMDFLAG, DESC)
Value:
      .Case(CMDFLAG, NAME)
ANALYSIS_PURGE [1/2]
#define ANALYSIS_PURGE (NAME, CMDFLAG, DESC)
Value:
  case NAME:                                                                   \
    GenerateArg(Args, OPT_analyzer_purge, CMDFLAG, SA);                        \
    break;
ANALYSIS_PURGE [2/2]
#define ANALYSIS_PURGE (NAME, CMDFLAG, DESC)
Value:
      .Case(CMDFLAG, NAME)
ANALYZER_OPTION [1/2]
#define ANALYZER_OPTION (...)
ANALYZER_OPTION [2/2]
#define ANALYZER_OPTION (TYPE, NAME, CMDFLAG, DESC, DEFAULT_VAL)
Value:
  initOption(AnOpts.Config, Diags, AnOpts.NAME, CMDFLAG, DEFAULT_VAL);
ANALYZER_OPTION_DEPENDS_ON_USER_MODE [1/2]
#define ANALYZER_OPTION_DEPENDS_ON_USER_MODE (...)
ANALYZER_OPTION_DEPENDS_ON_USER_MODE [2/2]
#define ANALYZER_OPTION_DEPENDS_ON_USER_MODE (TYPE, NAME, CMDFLAG, DESC, SHALLOW_VAL, DEEP_VAL)
Value:
  initOption(AnOpts.Config, Diags, AnOpts.NAME, CMDFLAG,                       \
             InShallowMode ? SHALLOW_VAL : DEEP_VAL);
ANALYZER_OPTION_WITH_MARSHALLING [1/2]
#define ANALYZER_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
ANALYZER_OPTION_WITH_MARSHALLING [2/2]
#define ANALYZER_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
BENIGN_ENUM_LANGOPT
#define BENIGN_ENUM_LANGOPT (Name, Type, Bits, Default, Description)
BENIGN_LANGOPT
#define BENIGN_LANGOPT (Name, Bits, Default, Description)
CODEGEN_OPTION_WITH_MARSHALLING [1/2]
#define CODEGEN_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
CODEGEN_OPTION_WITH_MARSHALLING [2/2]
#define CODEGEN_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING [1/2]
#define DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING [2/2]
#define DEPENDENCY_OUTPUT_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
DIAG_OPTION_WITH_MARSHALLING [1/2]
#define DIAG_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
DIAG_OPTION_WITH_MARSHALLING [2/2]
#define DIAG_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, *Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
DIAGOPT
#define DIAGOPT (Name, Bits, Default)
Value:
HBuilder.add(diagOpts.Name);
ENUM_DIAGOPT
#define ENUM_DIAGOPT (Name, Type, Bits, Default)
Value:
  HBuilder.add(diagOpts.get##Name());
ENUM_LANGOPT
#define ENUM_LANGOPT (Name, Type, Bits, Default, Description)
Value:
  HBuilder.add(static_cast<unsigned>(LangOpts->get##Name()));
FILE_SYSTEM_OPTION_WITH_MARSHALLING [1/2]
#define FILE_SYSTEM_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
FILE_SYSTEM_OPTION_WITH_MARSHALLING [2/2]
#define FILE_SYSTEM_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
FRONTEND_OPTION_WITH_MARSHALLING [1/2]
#define FRONTEND_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
FRONTEND_OPTION_WITH_MARSHALLING [2/2]
#define FRONTEND_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
GENERATE_OPTION_WITH_MARSHALLING
#define GENERATE_OPTION_WITH_MARSHALLING (ARGS, STRING_ALLOCATOR, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
Value:
  if ((FLAGS)&options::CC1Option) {                                            \
    [&](const auto &Extracted) {                                               \
      if (ALWAYS_EMIT ||                                                       \
          (Extracted !=                                                        \
           static_cast<decltype(KEYPATH)>((IMPLIED_CHECK) ? (IMPLIED_VALUE)    \
                                                          : (DEFAULT_VALUE)))) \
        DENORMALIZER(ARGS, SPELLING, STRING_ALLOCATOR, Option::KIND##Class,    \
                     TABLE_INDEX, Extracted);                                  \
    }(EXTRACTOR(KEYPATH));                                                     \
  }
Definition at line 441 of file CompilerInvocation.cpp.
HEADER_SEARCH_OPTION_WITH_MARSHALLING [1/2]
#define HEADER_SEARCH_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
HEADER_SEARCH_OPTION_WITH_MARSHALLING [2/2]
#define HEADER_SEARCH_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
LANG_OPTION_WITH_MARSHALLING [1/2]
#define LANG_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
LANG_OPTION_WITH_MARSHALLING [2/2]
#define LANG_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
LANGOPT
#define LANGOPT (Name, Bits, Default, Description)
Value:
HBuilder.add(LangOpts->Name);
LANGSTANDARD [1/2]
#define LANGSTANDARD (id, name, lang, desc, features)
LANGSTANDARD [2/2]
#define LANGSTANDARD (id, name, lang, desc, features)
LANGSTANDARD_ALIAS [1/2]
#define LANGSTANDARD_ALIAS (id, alias)
Value:
          if (KindValue == LangStandard::lang_##id) ++NumAliases;
LANGSTANDARD_ALIAS [2/2]
#define LANGSTANDARD_ALIAS (id, alias)
Value:
          if (KindValue == LangStandard::lang_##id) Diag << alias;
LANGSTANDARD_ALIAS_DEPR [1/2]
#define LANGSTANDARD_ALIAS_DEPR (id, alias)
LANGSTANDARD_ALIAS_DEPR [2/2]
#define LANGSTANDARD_ALIAS_DEPR (id, alias)
MIGRATOR_OPTION_WITH_MARSHALLING [1/2]
#define MIGRATOR_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
MIGRATOR_OPTION_WITH_MARSHALLING [2/2]
#define MIGRATOR_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
PARSE_OPTION_WITH_MARSHALLING
#define PARSE_OPTION_WITH_MARSHALLING (ARGS, DIAGS, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
Value:
  if ((FLAGS)&options::CC1Option) {                                            \
    KEYPATH = MERGER(KEYPATH, DEFAULT_VALUE);                                  \
    if (IMPLIED_CHECK)                                                         \
      KEYPATH = MERGER(KEYPATH, IMPLIED_VALUE);                                \
    if (SHOULD_PARSE)                                                          \
      if (auto MaybeValue = NORMALIZER(OPT_##ID, TABLE_INDEX, ARGS, DIAGS))    \
        KEYPATH =                                                              \
            MERGER(KEYPATH, static_cast<decltype(KEYPATH)>(*MaybeValue));      \
  }
Definition at line 426 of file CompilerInvocation.cpp.
PREPROCESSOR_OPTION_WITH_MARSHALLING [1/2]
#define PREPROCESSOR_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
PREPROCESSOR_OPTION_WITH_MARSHALLING [2/2]
#define PREPROCESSOR_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING [1/2]
#define PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING [2/2]
#define PREPROCESSOR_OUTPUT_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
SIMPLE_ENUM_VALUE_TABLE
#define SIMPLE_ENUM_VALUE_TABLE
Definition at line 167 of file CompilerInvocation.cpp.
TARGET_OPTION_WITH_MARSHALLING [1/2]
#define TARGET_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  GENERATE_OPTION_WITH_MARSHALLING(                                            \
      Args, SA, KIND, FLAGS, SPELLING, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE,    \
      IMPLIED_CHECK, IMPLIED_VALUE, DENORMALIZER, EXTRACTOR, TABLE_INDEX)
TARGET_OPTION_WITH_MARSHALLING [2/2]
#define TARGET_OPTION_WITH_MARSHALLING (PREFIX_TYPE, NAME, ID, KIND, GROUP, ALIAS, ALIASARGS, FLAGS, PARAM, HELPTEXT, METAVAR, VALUES, SPELLING, SHOULD_PARSE, ALWAYS_EMIT, KEYPATH, DEFAULT_VALUE, IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, DENORMALIZER, MERGER, EXTRACTOR, TABLE_INDEX)
Value:
  PARSE_OPTION_WITH_MARSHALLING(                                               \
      Args, Diags, ID, FLAGS, PARAM, SHOULD_PARSE, KEYPATH, DEFAULT_VALUE,     \
      IMPLIED_CHECK, IMPLIED_VALUE, NORMALIZER, MERGER, TABLE_INDEX)
Typedef Documentation
GenerateFn
using GenerateFn
Initial value:
 llvm::function_ref<void(
    CompilerInvocation &, SmallVectorImpl<const char *> &,
    CompilerInvocation::StringAllocator)>
Definition at line 636 of file CompilerInvocation.cpp.
ParseFn
using ParseFn
Initial value:
    llvm::function_ref<bool(CompilerInvocation &, ArrayRef<const char *>,
                            DiagnosticsEngine &, const char *)>
Definition at line 631 of file CompilerInvocation.cpp.
Function Documentation
addDiagnosticArgs()
static void addDiagnosticArgs (ArgList & Args, OptSpecifier Group, OptSpecifier GroupWithValue, std::vector< std::string > & Diagnostics) static
Definition at line 770 of file CompilerInvocation.cpp.
checkVerifyPrefixes()
static bool checkVerifyPrefixes (const std::vector< std::string > & VerifyPrefixes, DiagnosticsEngine & Diags) static
Definition at line 2183 of file CompilerInvocation.cpp.
References clang::C, clang::isAlphanumeric(), clang::isLetter(), and clang::DiagnosticsEngine::Report().
denormalizeSimpleEnum()
template<typename T > static void denormalizeSimpleEnum (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, T Value) static
Definition at line 327 of file CompilerInvocation.cpp.
References denormalizeSimpleEnumImpl().
denormalizeSimpleEnumImpl()
static void denormalizeSimpleEnumImpl (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, unsigned Value) static
Definition at line 310 of file CompilerInvocation.cpp.
References denormalizeString(), and findValueTableByValue().
Referenced by denormalizeSimpleEnum().
denormalizeSimpleFlag()
static void denormalizeSimpleFlag (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator , Option::OptionClass , unsigned , ...) static
The tblgen-erated code passes in a fifth parameter of an arbitrary type, but denormalizeSimpleFlags never looks at it.
Avoid bloating compile-time with unnecessary template instantiations and just ignore it with a variadic argument.
Definition at line 192 of file CompilerInvocation.cpp.
Referenced by GenerateArg().
denormalizeString()
template<typename T > static void denormalizeString (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, T Value) static
Definition at line 266 of file CompilerInvocation.cpp.
References denormalizeStringImpl().
Referenced by denormalizeSimpleEnumImpl(), denormalizeStringVector(), GenerateArg(), and GenerateFrontendArgs().
denormalizeStringImpl()
static void denormalizeStringImpl (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned , const Twine & Value) static
Definition at line 242 of file CompilerInvocation.cpp.
Referenced by denormalizeString().
denormalizeStringVector()
static void denormalizeStringVector (SmallVectorImpl< const char * > & Args, const char * Spelling, CompilerInvocation::StringAllocator SA, Option::OptionClass OptClass, unsigned TableIndex, const std::vector< std::string > & Values) static
Definition at line 367 of file CompilerInvocation.cpp.
References denormalizeString().
extractForwardValue()
template<typename T > static T extractForwardValue (T KeyPath) static
Definition at line 417 of file CompilerInvocation.cpp.
extractMaskValue()
template<typename T , typename U , U Value> static T extractMaskValue (T KeyPath) static
Definition at line 422 of file CompilerInvocation.cpp.
findValueTableByName()
static Optional< SimpleEnumValue > findValueTableByName (const SimpleEnumValueTable & Table, StringRef Name) static
Definition at line 273 of file CompilerInvocation.cpp.
References clang::None.
Referenced by normalizeSimpleEnum().
findValueTableByValue()
static Optional< SimpleEnumValue > findValueTableByValue (const SimpleEnumValueTable & Table, unsigned Value) static
Definition at line 282 of file CompilerInvocation.cpp.
References clang::None.
Referenced by denormalizeSimpleEnumImpl().
FixupInvocation()
static bool FixupInvocation (CompilerInvocation & Invocation, DiagnosticsEngine & Diags, const ArgList & Args, InputKind IK) static
Definition at line 458 of file CompilerInvocation.cpp.
References clang::CodeGenOptions::CodeModel, clang::TargetOptions::CodeModel, clang::LangOptions::CurrentModule, clang::LangOptions::DCC_FastCall, clang::LangOptions::DCC_RegCall, clang::LangOptions::DCC_StdCall, clang::LangOptions::DCC_VectorCall, clang::FrontendOptions::DisableFree, clang::FrontendOptions::GenerateGlobalModuleIndex, clang::CompilerInvocationValueBase::getCodeGenOpts(), clang::CompilerInvocationValueBase::getFrontendOpts(), GetInputKindName(), clang::CompilerInvocationRefBase::getLangOpts(), clang::DiagnosticsEngine::getNumErrors(), clang::LangOptions::getOpenCLCompatibleVersion(), clang::LangOptions::getOpenCLVersionString(), clang::CompilerInvocationRefBase::getTargetOpts(), clang::CodeGenOptions::hasSanitizeCoverage(), clang::LangOptions::ModuleName, clang::LangOptions::None, clang::DiagnosticsEngine::Report(), clang::LangOptions::SanitizeCoverage, clang::FrontendOptions::ShowStats, clang::TargetOptions::Triple, and clang::FrontendOptions::UseGlobalModuleIndex.
GenerateAnalyzerArgs()
static void GenerateAnalyzerArgs (AnalyzerOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 803 of file CompilerInvocation.cpp.
References clang::AnalyzerOptions::AnalysisConstraintsOpt, clang::AnalyzerOptions::AnalysisDiagOpt, clang::AnalyzerOptions::AnalysisPurgeOpt, clang::C, clang::AnalyzerOptions::CheckersAndPackages, clang::AnalyzerOptions::Config, GenerateArg(), clang::AnalyzerOptions::InliningMode, and parseAnalyzerConfigs().
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateArg() [1/2]
static void GenerateArg (SmallVectorImpl< const char * > & Args, llvm::opt::OptSpecifier OptSpecifier, CompilerInvocation::StringAllocator SA) static
Definition at line 613 of file CompilerInvocation.cpp.
References denormalizeSimpleFlag(), and clang::driver::getDriverOptTable().
Referenced by GenerateAnalyzerArgs(), GenerateDependencyOutputArgs(), GenerateFrontendArgs(), GenerateHeaderSearchArgs(), GenerateOptimizationRemark(), GeneratePreprocessorArgs(), GeneratePreprocessorOutputArgs(), and GenerateTargetArgs().
GenerateArg() [2/2]
static void GenerateArg (SmallVectorImpl< const char * > & Args, llvm::opt::OptSpecifier OptSpecifier, const Twine & Value, CompilerInvocation::StringAllocator SA) static
Definition at line 621 of file CompilerInvocation.cpp.
References denormalizeString(), and clang::driver::getDriverOptTable().
GenerateDependencyOutputArgs()
static void GenerateDependencyOutputArgs (const DependencyOutputOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 2048 of file CompilerInvocation.cpp.
References clang::EDK_DepFileEntry, clang::EDK_ModuleFile, clang::EDK_ProfileList, clang::EDK_SanitizeIgnorelist, clang::DependencyOutputOptions::ExtraDeps, GenerateArg(), clang::None, and clang::DependencyOutputOptions::ShowIncludesDest.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateFileSystemArgs()
static void GenerateFileSystemArgs (const FileSystemOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 2201 of file CompilerInvocation.cpp.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateFrontendArgs()
static void GenerateFrontendArgs (const FrontendOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA, bool IsHeader) static
Definition at line 2517 of file CompilerInvocation.cpp.
References clang::FrontendOptions::ActionName, clang::ADOF_Default, clang::ADOF_JSON, clang::Asm, clang::frontend::ASTDump, clang::FrontendOptions::ASTDumpAll, clang::FrontendOptions::ASTDumpDecls, clang::FrontendOptions::ASTDumpFormat, clang::FrontendOptions::AuxTargetCPU, clang::FrontendOptions::AuxTargetFeatures, clang::C, clang::FrontendOptions::CodeCompletionAt, clang::CUDA, clang::CXX, clang::FrontendOptions::DashX, denormalizeString(), clang::ParsedSourceLocation::FileName, clang::frontend::FixIt, clang::FrontendOptions::FixItSuffix, GenerateArg(), clang::driver::getDriverOptTable(), clang::InputKind::getFormat(), clang::InputKind::getHeaderUnitKind(), clang::InputKind::getLanguage(), getProgramActionOpt(), clang::InputKind::HeaderUnit_Abs, clang::InputKind::HeaderUnit_None, clang::InputKind::HeaderUnit_System, clang::InputKind::HeaderUnit_User, clang::HIP, clang::HLSL, clang::FrontendOptions::Inputs, clang::InputKind::isPreprocessed(), clang::LLVM_IR, clang::FrontendOptions::ModuleFileExtensions, clang::FrontendOptions::ModuleFiles, clang::InputKind::ModuleMap, clang::ObjC, clang::ObjCXX, clang::OpenCL, clang::OpenCLCXX, clang::frontend::PluginAction, clang::FrontendOptions::PluginArgs, clang::FrontendOptions::Plugins, clang::InputKind::Precompiled, clang::FrontendOptions::ProgramAction, clang::RenderScript, clang::ParsedSourceLocation::ToString(), and clang::Unknown.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateHeaderSearchArgs()
static void GenerateHeaderSearchArgs (HeaderSearchOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 2953 of file CompilerInvocation.cpp.
References clang::frontend::After, clang::frontend::Angled, clang::frontend::CSystem, clang::frontend::CXXSystem, clang::frontend::ExternCSystem, clang::File, GenerateArg(), clang::HeaderSearchOptions::Entry::Group, clang::HeaderSearchOptions::Entry::IgnoreSysRoot, clang::frontend::IndexHeaderMap, clang::HeaderSearchOptions::Entry::IsFramework, clang::HeaderSearchOptions::ModuleCachePath, clang::HeaderSearchOptions::ModulesIgnoreMacros, clang::None, clang::frontend::ObjCSystem, clang::frontend::ObjCXXSystem, P, clang::HeaderSearchOptions::PrebuiltModuleFiles, clang::HeaderSearchOptions::PrebuiltModulePaths, clang::frontend::Quoted, clang::frontend::System, clang::HeaderSearchOptions::SystemHeaderPrefixes, clang::HeaderSearchOptions::UseLibcxx, clang::HeaderSearchOptions::UserEntries, and clang::HeaderSearchOptions::VFSOverlayFiles.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateMigratorArgs()
static void GenerateMigratorArgs (const MigratorOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 2238 of file CompilerInvocation.cpp.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateOptimizationRemark()
static void GenerateOptimizationRemark (SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA, OptSpecifier OptEQ, StringRef Name, const CodeGenOptions::OptRemark & Remark) static
Generate a remark argument. This is an inverse of ParseOptimizationRemark.
Definition at line 1162 of file CompilerInvocation.cpp.
References GenerateArg(), clang::Remark, clang::CodeGenOptions::RK_Disabled, and clang::CodeGenOptions::RK_Enabled.
GeneratePreprocessorArgs()
static void GeneratePreprocessorArgs (PreprocessorOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA, const LangOptions & LangOpts, const FrontendOptions & FrontendOpts, const CodeGenOptions & CodeGenOpts) static
Definition at line 4159 of file CompilerInvocation.cpp.
References clang::PreprocessorOptions::ChainedIncludes, clang::PreprocessorOptions::DeserializedPCHDeclsToErrorOn, GenerateArg(), clang::PreprocessorOptions::Includes, clang::PreprocessorOptions::Macros, clang::PreprocessorOptions::PCHWithHdrStop, clang::PreprocessorOptions::PCHWithHdrStopCreate, clang::PreprocessorOptions::PrecompiledPreambleBytes, and clang::PreprocessorOptions::RemappedFiles.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GeneratePreprocessorOutputArgs()
static void GeneratePreprocessorOutputArgs (const PreprocessorOutputOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA, frontend::ActionKind Action) static
Definition at line 4318 of file CompilerInvocation.cpp.
References clang::PreprocessorOutputOptions::DirectivesOnly, GenerateArg(), isStrictlyPreprocessorAction(), clang::PreprocessorOutputOptions::ShowCPP, and clang::PreprocessorOutputOptions::ShowMacros.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
GenerateTargetArgs()
static void GenerateTargetArgs (const TargetOptions & Opts, SmallVectorImpl< const char * > & Args, CompilerInvocation::StringAllocator SA) static
Definition at line 4368 of file CompilerInvocation.cpp.
References clang::TargetOptions::DarwinTargetVariantSDKVersion, GenerateArg(), and clang::TargetOptions::SDKVersion.
Referenced by clang::CompilerInvocation::generateCC1CommandLine().
getAllNoBuiltinFuncValues()
static void getAllNoBuiltinFuncValues (ArgList & Args, std::vector< std::string > & Funcs) static
Definition at line 796 of file CompilerInvocation.cpp.
References clang::Builtin::Context::isBuiltinFunc().
getFrontendAction()
static Optional< frontend::ActionKind > getFrontendAction (OptSpecifier & Opt) static
Maps command line option to frontend action.
Definition at line 2499 of file CompilerInvocation.cpp.
References getFrontendActionTable(), and clang::None.
Referenced by ParseFrontendArgs().
getFrontendActionTable()
static const auto & getFrontendActionTable () static
Return a table that associates command line option specifiers with the frontend action.
Note: The pair {frontend::PluginAction, OPT_plugin} is intentionally missing, as this case is handled separately from other frontend options.
Definition at line 2444 of file CompilerInvocation.cpp.
References clang::frontend::ASTDeclList, clang::frontend::ASTDump, clang::frontend::ASTPrint, clang::frontend::ASTView, clang::frontend::DumpCompilerOptions, clang::frontend::DumpRawTokens, clang::frontend::DumpTokens, clang::frontend::EmitAssembly, clang::frontend::EmitBC, clang::frontend::EmitCodeGenOnly, clang::frontend::EmitHTML, clang::frontend::EmitLLVM, clang::frontend::EmitLLVMOnly, clang::frontend::EmitObj, clang::frontend::ExtractAPI, clang::frontend::FixIt, clang::frontend::GenerateHeaderModule, clang::frontend::GenerateHeaderUnit, clang::frontend::GenerateInterfaceStubs, clang::frontend::GenerateModule, clang::frontend::GenerateModuleInterface, clang::frontend::GeneratePCH, clang::frontend::InitOnly, clang::frontend::MigrateSource, clang::frontend::ModuleFileInfo, clang::frontend::ParseSyntaxOnly, clang::frontend::PrintDependencyDirectivesSourceMinimizerOutput, clang::frontend::PrintPreamble, clang::frontend::PrintPreprocessedInput, clang::frontend::RewriteMacros, clang::frontend::RewriteObjC, clang::frontend::RewriteTest, clang::frontend::RunAnalysis, clang::frontend::RunPreprocessorOnly, clang::frontend::TemplightDump, and clang::frontend::VerifyPCH.
Referenced by getFrontendAction(), and getProgramActionOpt().
GetInputKindName()
static StringRef GetInputKindName (InputKind IK) static
Get language name for given input kind.
Definition at line 3260 of file CompilerInvocation.cpp.
References clang::Asm, clang::C, clang::CUDA, clang::CXX, clang::InputKind::getLanguage(), clang::HIP, clang::HLSL, clang::LLVM_IR, clang::ObjC, clang::ObjCXX, clang::OpenCL, clang::OpenCLCXX, clang::RenderScript, and clang::Unknown.
Referenced by FixupInvocation().
getOptimizationLevel()
static unsigned getOptimizationLevel (ArgList & Args, InputKind IK, DiagnosticsEngine & Diags) static
Definition at line 567 of file CompilerInvocation.cpp.
References clang::InputKind::getLanguage(), clang::getLastArgIntValue(), clang::OpenCL, and clang::OpenCLCXX.
getOptimizationLevelSize()
static unsigned getOptimizationLevelSize (ArgList & Args) static
Definition at line 597 of file CompilerInvocation.cpp.
getProgramActionOpt()
static Optional< OptSpecifier > getProgramActionOpt (frontend::ActionKind ProgramAction) static
Maps frontend action to command line option.
Definition at line 2509 of file CompilerInvocation.cpp.
References getFrontendActionTable(), and clang::None.
Referenced by GenerateFrontendArgs().
getStringOption()
static StringRef getStringOption (AnalyzerOptions::ConfigTable & Config, StringRef OptionName, StringRef DefaultVal) static
Definition at line 1046 of file CompilerInvocation.cpp.
Referenced by initOption(), initOption(), and initOption().
initOption() [1/3]
static void initOption (AnalyzerOptions::ConfigTable & Config, DiagnosticsEngine * Diags, bool & OptionField, StringRef Name, bool DefaultVal) static
Definition at line 1061 of file CompilerInvocation.cpp.
References getStringOption(), and clang::DiagnosticsEngine::Report().
initOption() [2/3]
static void initOption (AnalyzerOptions::ConfigTable & Config, DiagnosticsEngine * Diags, StringRef & OptionField, StringRef Name, StringRef DefaultVal) static
Definition at line 1051 of file CompilerInvocation.cpp.
References getStringOption().
initOption() [3/3]
static void initOption (AnalyzerOptions::ConfigTable & Config, DiagnosticsEngine * Diags, unsigned & OptionField, StringRef Name, unsigned DefaultVal) static
Definition at line 1080 of file CompilerInvocation.cpp.
References getStringOption(), and clang::DiagnosticsEngine::Report().
is_uint64_t_convertible()
template<typename T > static constexpr bool is_uint64_t_convertible () static constexpr
Definition at line 199 of file CompilerInvocation.cpp.
IsInputCompatibleWithStandard()
static bool IsInputCompatibleWithStandard (InputKind IK, const LangStandard & S) static
Check if input file kind and language standard are compatible.
Definition at line 3215 of file CompilerInvocation.cpp.
References clang::Asm, clang::C, clang::CUDA, clang::CXX, clang::InputKind::getLanguage(), clang::HIP, clang::HLSL, clang::LLVM_IR, clang::ObjC, clang::ObjCXX, clang::OpenCL, clang::OpenCLCXX, clang::RenderScript, and clang::Unknown.
isStrictlyPreprocessorAction()
static bool isStrictlyPreprocessorAction (frontend::ActionKind Action) static
Definition at line 4113 of file CompilerInvocation.cpp.
References clang::frontend::ASTDeclList, clang::frontend::ASTDump, clang::frontend::ASTPrint, clang::frontend::ASTView, clang::frontend::DumpCompilerOptions, clang::frontend::DumpRawTokens, clang::frontend::DumpTokens, clang::frontend::EmitAssembly, clang::frontend::EmitBC, clang::frontend::EmitCodeGenOnly, clang::frontend::EmitHTML, clang::frontend::EmitLLVM, clang::frontend::EmitLLVMOnly, clang::frontend::EmitObj, clang::frontend::ExtractAPI, clang::frontend::FixIt, clang::frontend::GenerateHeaderModule, clang::frontend::GenerateHeaderUnit, clang::frontend::GenerateInterfaceStubs, clang::frontend::GenerateModule, clang::frontend::GenerateModuleInterface, clang::frontend::GeneratePCH, clang::frontend::InitOnly, clang::frontend::MigrateSource, clang::frontend::ModuleFileInfo, clang::frontend::ParseSyntaxOnly, clang::frontend::PluginAction, clang::frontend::PrintDependencyDirectivesSourceMinimizerOutput, clang::frontend::PrintPreamble, clang::frontend::PrintPreprocessedInput, clang::frontend::RewriteMacros, clang::frontend::RewriteObjC, clang::frontend::RewriteTest, clang::frontend::RunAnalysis, clang::frontend::RunPreprocessorOnly, clang::frontend::TemplightDump, and clang::frontend::VerifyPCH.
Referenced by GeneratePreprocessorOutputArgs(), ParsePreprocessorArgs(), and ParsePreprocessorOutputArgs().
makeBooleanOptionDenormalizer()
static auto makeBooleanOptionDenormalizer (bool Value) static
Definition at line 233 of file CompilerInvocation.cpp.
makeBooleanOptionNormalizer()
static auto makeBooleanOptionNormalizer (bool Value, bool OtherValue, OptSpecifier OtherOpt) static
Definition at line 221 of file CompilerInvocation.cpp.
References clang::None.
makeFlagToValueNormalizer()
template<typename T , std::enable_if_t<!is_uint64_t_convertible< T >(), bool > = false> static auto makeFlagToValueNormalizer (T Value) static
Definition at line 206 of file CompilerInvocation.cpp.
References clang::None.
mergeForwardValue()
template<typename T , typename U > static T mergeForwardValue (T KeyPath, U Value) static
Definition at line 409 of file CompilerInvocation.cpp.
mergeMaskValue()
template<typename T , typename U > static T mergeMaskValue (T KeyPath, U Value) static
Definition at line 413 of file CompilerInvocation.cpp.
normalizeSimpleEnum()
static llvm::Optional< unsigned > normalizeSimpleEnum (OptSpecifier Opt, unsigned TableIndex, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 290 of file CompilerInvocation.cpp.
References findValueTableByName(), clang::None, and clang::DiagnosticsEngine::Report().
normalizeSimpleFlag()
static llvm::Optional< bool > normalizeSimpleFlag (OptSpecifier Opt, unsigned TableIndex, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 171 of file CompilerInvocation.cpp.
References clang::None.
normalizeSimpleNegativeFlag()
static Optional< bool > normalizeSimpleNegativeFlag (OptSpecifier Opt, unsigned , const ArgList & Args, DiagnosticsEngine &) static
Definition at line 180 of file CompilerInvocation.cpp.
References clang::None.
normalizeString()
static Optional< std::string > normalizeString (OptSpecifier Opt, int TableIndex, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 336 of file CompilerInvocation.cpp.
References clang::None.
normalizeStringIntegral()
template<typename IntTy > static Optional< IntTy > normalizeStringIntegral (OptSpecifier Opt, int , const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 346 of file CompilerInvocation.cpp.
References clang::None, and clang::DiagnosticsEngine::Report().
normalizeStringVector()
static Optional< std::vector< std::string > > normalizeStringVector (OptSpecifier Opt, int , const ArgList & Args, DiagnosticsEngine &) static
Definition at line 362 of file CompilerInvocation.cpp.
normalizeTriple()
static Optional< std::string > normalizeTriple (OptSpecifier Opt, int TableIndex, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 399 of file CompilerInvocation.cpp.
References clang::None.
ParseAnalyzerArgs()
static bool ParseAnalyzerArgs (AnalyzerOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 889 of file CompilerInvocation.cpp.
References clang::AnalyzerOptions::AnalysisConstraintsOpt, clang::AnalyzerOptions::AnalysisDiagOpt, clang::AnalyzerOptions::AnalysisPurgeOpt, clang::AnalyzerOptions::CheckersAndPackages, clang::AnalyzerOptions::Config, clang::AnalyzerOptions::FullCompilerInvocation, clang::DiagnosticsEngine::getNumErrors(), clang::AnalyzerOptions::InliningMode, clang::AnalyzerOptions::isUnknownAnalyzerConfig(), clang::NUM_ANALYSIS_DIAG_CLIENTS, clang::NumConstraints, clang::NumInliningModes, clang::NumPurgeModes, parseAnalyzerConfigs(), clang::DiagnosticsEngine::Report(), and clang::AnalyzerOptions::ShouldEmitErrorsOnInvalidConfigValue.
parseAnalyzerConfigs()
static void parseAnalyzerConfigs (AnalyzerOptions & AnOpts, DiagnosticsEngine * Diags) static
Definition at line 1093 of file CompilerInvocation.cpp.
References clang::AnalyzerOptions::getRegisteredCheckers(), clang::AnalyzerOptions::getRegisteredPackages(), clang::DiagnosticsEngine::Report(), and clang::AnalyzerOptions::SilencedCheckersAndPackages.
Referenced by GenerateAnalyzerArgs(), and ParseAnalyzerArgs().
ParseDependencyOutputArgs()
static bool ParseDependencyOutputArgs (DependencyOutputOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags, frontend::ActionKind Action, bool ShowLineMarkers) static
Definition at line 2086 of file CompilerInvocation.cpp.
References clang::EDK_DepFileEntry, clang::EDK_ModuleFile, clang::EDK_ProfileList, clang::EDK_SanitizeIgnorelist, clang::DependencyOutputOptions::ExtraDeps, Filename, clang::DiagnosticsEngine::getNumErrors(), clang::DependencyOutputOptions::IncludeSystemHeaders, clang::None, clang::frontend::PrintPreprocessedInput, clang::DependencyOutputOptions::ShowIncludesDest, clang::Stderr, and clang::Stdout.
parseDiagnosticLevelMask()
static bool parseDiagnosticLevelMask (StringRef FlagName, const std::vector< std::string > & Levels, DiagnosticsEngine & Diags, DiagnosticLevelMask & M) static
Definition at line 1230 of file CompilerInvocation.cpp.
References clang::Error, clang::None, clang::Note, clang::Remark, clang::DiagnosticsEngine::Report(), and clang::Warning.
ParseFileSystemArgs()
static bool ParseFileSystemArgs (FileSystemOptions & Opts, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 2218 of file CompilerInvocation.cpp.
References clang::DiagnosticsEngine::getNumErrors().
ParseFrontendArgs()
static bool ParseFrontendArgs (FrontendOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags, bool & IsHeaderFile) static
Definition at line 2692 of file CompilerInvocation.cpp.
References clang::FrontendOptions::ActionName, clang::ADOF_Default, clang::ADOF_JSON, clang::FrontendOptions::ARCMT_None, clang::FrontendOptions::ARCMTAction, clang::Asm, clang::frontend::ASTDump, clang::FrontendOptions::ASTDumpAll, clang::FrontendOptions::ASTDumpDecls, clang::FrontendOptions::ASTDumpFormat, clang::FrontendOptions::AuxTargetCPU, clang::FrontendOptions::AuxTargetFeatures, clang::C, clang::FrontendOptions::CodeCompletionAt, clang::CUDA, clang::CXX, clang::FrontendOptions::DashX, clang::ParsedSourceLocation::FileName, clang::frontend::FixIt, clang::FrontendOptions::FixItSuffix, clang::ParsedSourceLocation::FromString(), clang::frontend::GenerateInterfaceStubs, clang::frontend::GenerateModule, clang::InputKind::getFormat(), getFrontendAction(), clang::InputKind::getHeader(), clang::InputKind::getHeaderUnitKind(), clang::FrontendOptions::getInputKindForExtension(), clang::DiagnosticsEngine::getNumErrors(), clang::InputKind::getPreprocessed(), clang::InputKind::HeaderUnit_Abs, clang::InputKind::HeaderUnit_None, clang::InputKind::HeaderUnit_System, clang::InputKind::HeaderUnit_User, clang::HIP, clang::HLSL, clang::FrontendOptions::Inputs, clang::FrontendOptions::IsSystemModule, clang::InputKind::isUnknown(), clang::LLVM_IR, clang::FrontendOptions::ModuleFileExtensions, clang::FrontendOptions::ModuleFiles, clang::InputKind::ModuleMap, clang::ObjC, clang::FrontendOptions::ObjCMT_None, clang::FrontendOptions::ObjCMTAction, clang::ObjCXX, clang::OpenCL, clang::OpenCLCXX, clang::frontend::ParseSyntaxOnly, parseTestModuleFileExtensionArg(), clang::frontend::PluginAction, clang::FrontendOptions::PluginArgs, clang::FrontendOptions::Plugins, clang::InputKind::Precompiled, clang::FrontendOptions::ProgramAction, clang::RenderScript, clang::DiagnosticsEngine::Report(), clang::InputKind::Source, clang::Unknown, clang::InputKind::withFormat(), and clang::InputKind::withHeaderUnit().
ParseHeaderSearchArgs()
static bool ParseHeaderSearchArgs (HeaderSearchOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags, const std::string & WorkingDir) static
Definition at line 3079 of file CompilerInvocation.cpp.
References clang::HeaderSearchOptions::AddPath(), clang::HeaderSearchOptions::AddPrebuiltModulePath(), clang::HeaderSearchOptions::AddSystemHeaderPrefix(), clang::HeaderSearchOptions::AddVFSOverlayFile(), clang::frontend::After, clang::frontend::Angled, clang::frontend::CSystem, clang::frontend::CXXSystem, clang::frontend::ExternCSystem, clang::DiagnosticsEngine::getNumErrors(), clang::frontend::IndexHeaderMap, clang::HeaderSearchOptions::ModuleCachePath, clang::HeaderSearchOptions::ModulesIgnoreMacros, clang::frontend::ObjCSystem, clang::frontend::ObjCXXSystem, P, clang::HeaderSearchOptions::PrebuiltModuleFiles, clang::frontend::Quoted, clang::HeaderSearchOptions::Sysroot, clang::frontend::System, and clang::HeaderSearchOptions::UseLibcxx.
ParseMigratorArgs()
static bool ParseMigratorArgs (MigratorOptions & Opts, const ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 2254 of file CompilerInvocation.cpp.
References clang::DiagnosticsEngine::getNumErrors().
ParseOptimizationRemark()
static CodeGenOptions::OptRemark ParseOptimizationRemark (DiagnosticsEngine & Diags, ArgList & Args, OptSpecifier OptEQ, StringRef Name) static
Parse a remark command line argument.
It may be missing, disabled/enabled by '-R[no-]group' or specified with a regular expression by '-Rgroup=regexp'. On top of that, it can be disabled/enabled globally by '-R[no-]everything'.
Definition at line 1179 of file CompilerInvocation.cpp.
References clang::DiagnosticsEngine::Report(), clang::Result, clang::CodeGenOptions::RK_Disabled, clang::CodeGenOptions::RK_DisabledEverything, clang::CodeGenOptions::RK_Enabled, clang::CodeGenOptions::RK_EnabledEverything, and clang::CodeGenOptions::RK_WithPattern.
ParsePreprocessorArgs()
static bool ParsePreprocessorArgs (PreprocessorOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags, frontend::ActionKind Action, const FrontendOptions & FrontendOpts) static
Definition at line 4231 of file CompilerInvocation.cpp.
References clang::PreprocessorOptions::addMacroDef(), clang::PreprocessorOptions::addMacroUndef(), clang::PreprocessorOptions::addRemappedFile(), clang::PreprocessorOptions::ChainedIncludes, clang::PreprocessorOptions::DeserializedPCHDeclsToErrorOn, clang::DiagnosticsEngine::getNumErrors(), clang::PreprocessorOptions::Includes, isStrictlyPreprocessorAction(), clang::PreprocessorOptions::LexEditorPlaceholders, clang::PreprocessorOptions::PCHWithHdrStop, clang::PreprocessorOptions::PrecompiledPreambleBytes, and clang::DiagnosticsEngine::Report().
ParsePreprocessorOutputArgs()
static bool ParsePreprocessorOutputArgs (PreprocessorOutputOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags, frontend::ActionKind Action) static
Definition at line 4343 of file CompilerInvocation.cpp.
References clang::PreprocessorOutputOptions::DirectivesOnly, clang::DiagnosticsEngine::getNumErrors(), isStrictlyPreprocessorAction(), clang::PreprocessorOutputOptions::ShowCPP, and clang::PreprocessorOutputOptions::ShowMacros.
parseSanitizerKinds()
static void parseSanitizerKinds (StringRef FlagName, const std::vector< std::string > & Sanitizers, DiagnosticsEngine & Diags, SanitizerSet & S) static
Definition at line 1252 of file CompilerInvocation.cpp.
References clang::parseSanitizerValue(), and clang::DiagnosticsEngine::Report().
parseShowColorsArgs()
static bool parseShowColorsArgs (const ArgList & Args, bool DefaultColor) static
Definition at line 2152 of file CompilerInvocation.cpp.
ParseTargetArgs()
static bool ParseTargetArgs (TargetOptions & Opts, ArgList & Args, DiagnosticsEngine & Diags) static
Definition at line 4391 of file CompilerInvocation.cpp.
References clang::TargetOptions::DarwinTargetVariantSDKVersion, clang::DiagnosticsEngine::getNumErrors(), clang::DiagnosticsEngine::Report(), and clang::TargetOptions::SDKVersion.
parseTestModuleFileExtensionArg()
static bool parseTestModuleFileExtensionArg (StringRef Arg, std::string & BlockName, unsigned & MajorVersion, unsigned & MinorVersion, bool & Hashed, std::string & UserInfo) static
Parse the argument to the -ftest-module-file-extension command-line argument.
Returns
true on error, false on success.
Definition at line 2420 of file CompilerInvocation.cpp.
Referenced by ParseFrontendArgs().
parseToleranceOption()
Expected< Optional< uint64_t > > parseToleranceOption (StringRef Arg) inline
Definition at line 116 of file CompilerInvocation.cpp.
parseXRayInstrumentationBundle()
static void parseXRayInstrumentationBundle (StringRef FlagName, StringRef Bundle, ArgList & Args, DiagnosticsEngine & D, XRayInstrSet & S) static
Definition at line 1270 of file CompilerInvocation.cpp.
References clang::XRayInstrKind::All, clang::XRayInstrKind::None, clang::parseXRayInstrValue(), and clang::DiagnosticsEngine::Report().
RoundTrip()
static bool RoundTrip (ParseFn Parse, GenerateFn Generate, CompilerInvocation & RealInvocation, CompilerInvocation & DummyInvocation, ArrayRef< const char * > CommandLineArgs, DiagnosticsEngine & Diags, const char * Argv0) static
Definition at line 647 of file CompilerInvocation.cpp.
References clang::Equal, clang::DiagnosticsEngine::getNumWarnings(), clang::DiagnosticsEngine::Report(), and clang::DiagnosticsEngine::setClient().
Referenced by clang::CompilerInvocation::CreateFromArgs().
serializeSanitizerKinds()
static SmallVector< StringRef, 4 > serializeSanitizerKinds (SanitizerSet S) static
Definition at line 1264 of file CompilerInvocation.cpp.
References clang::serializeSanitizerSet().
serializeXRayInstrumentationBundle()
static std::string serializeXRayInstrumentationBundle (const XRayInstrSet & S) static
Definition at line 1289 of file CompilerInvocation.cpp.
References clang::serializeXRayInstrValue().
setPGOUseInstrumentor()
static void setPGOUseInstrumentor (CodeGenOptions & Opts, const Twine & ProfileName) static
Definition at line 1299 of file CompilerInvocation.cpp.
References clang::CodeGenOptions::ProfileClangInstr, clang::CodeGenOptions::ProfileCSIRInstr, and clang::CodeGenOptions::ProfileIRInstr.