clang: lib/AST/DeclTemplate.cpp File Reference
DeclTemplate.cpp File Reference
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <utility>
Namespaces
namespace clang
Functions
static bool AdoptTemplateParameterList (TemplateParameterList *Params, DeclContext *Owner)
void * clang::allocateDefaultArgStorageChain (const ASTContext &C)
static void ProfileTemplateParameterList (ASTContext &C, llvm::FoldingSetNodeID &ID, const TemplateParameterList *TPL)
static TemplateParameterList * createMakeIntegerSeqParameterList (const ASTContext &C, DeclContext *DC)
static TemplateParameterList * createTypePackElementParameterList (const ASTContext &C, DeclContext *DC)
static TemplateParameterList * createBuiltinTemplateParameterList (const ASTContext &C, DeclContext *DC, BuiltinTemplateKind BTK)
Function Documentation
AdoptTemplateParameterList()
static bool AdoptTemplateParameterList (TemplateParameterList * Params, DeclContext * Owner) static
Definition at line 169 of file DeclTemplate.cpp.
References AdoptTemplateParameterList(), clang::Invalid, and P.
Referenced by AdoptTemplateParameterList(), clang::ClassTemplateDecl::Create(), clang::ConceptDecl::Create(), clang::FunctionTemplateDecl::Create(), clang::TypeAliasTemplateDecl::Create(), and clang::VarTemplateDecl::Create().
createBuiltinTemplateParameterList()
static TemplateParameterList * createBuiltinTemplateParameterList (const ASTContext & C, DeclContext * DC, BuiltinTemplateKind BTK) static
Definition at line 1464 of file DeclTemplate.cpp.
References clang::BTK__make_integer_seq, clang::BTK__type_pack_element, clang::C, createMakeIntegerSeqParameterList(), and createTypePackElementParameterList().
createMakeIntegerSeqParameterList()
static TemplateParameterList * createMakeIntegerSeqParameterList (const ASTContext & C, DeclContext * DC) static
Definition at line 1394 of file DeclTemplate.cpp.
References clang::C, clang::NonTypeTemplateParmDecl::Create(), clang::TemplateParameterList::Create(), clang::TemplateTemplateParmDecl::Create(), clang::TemplateTypeParmDecl::Create(), clang::TypeSourceInfo::getType(), N, and P.
Referenced by createBuiltinTemplateParameterList().
createTypePackElementParameterList()
static TemplateParameterList * createTypePackElementParameterList (const ASTContext & C, DeclContext * DC) static
Definition at line 1443 of file DeclTemplate.cpp.
References clang::C, clang::NonTypeTemplateParmDecl::Create(), clang::TemplateParameterList::Create(), clang::TemplateTypeParmDecl::Create(), and clang::TypeSourceInfo::getType().
Referenced by createBuiltinTemplateParameterList().
ProfileTemplateParameterList()
static void ProfileTemplateParameterList (ASTContext & C, llvm::FoldingSetNodeID & ID, const TemplateParameterList * TPL) static
Definition at line 510 of file DeclTemplate.cpp.
References clang::C, clang::cast(), clang::TemplateParameterList::getRequiresClause(), clang::Stmt::Profile(), ProfileTemplateParameterList(), and clang::TemplateParameterList::size().
Referenced by clang::ClassTemplatePartialSpecializationDecl::Profile(), clang::VarTemplatePartialSpecializationDecl::Profile(), and ProfileTemplateParameterList().