clang: lib/Lex/DependencyDirectivesScanner.cpp File Reference
DependencyDirectivesScanner.cpp File Reference
This is the interface for scanning header and source files to get the minimum necessary preprocessor directives for evaluating includes.
#include "clang/Lex/DependencyDirectivesScanner.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
Functions
static void skipOverSpaces (const char *&First, const char *const End)
static LLVM_NODISCARD bool isRawStringLiteral (const char *First, const char *Current)
static void skipRawString (const char *&First, const char *const End)
static unsigned isEOL (const char *First, const char *const End)
static void skipString (const char *&First, const char *const End)
static unsigned skipNewline (const char *&First, const char *End)
static bool wasLineContinuation (const char *First, unsigned EOLLen)
static void skipToNewlineRaw (const char *&First, const char *const End)
static void skipLineComment (const char *&First, const char *const End)
static void skipBlockComment (const char *&First, const char *const End)
static bool isQuoteCppDigitSeparator (const char *const Start, const char *const Cur, const char *const End)
static void skipLine (const char *&First, const char *const End)
static void skipDirective (StringRef Name, const char *&First, const char *const End)
static void skipWhitespace (const char *&First, const char *const End)
static bool isStartOfRelevantLine (char First)
static void skipUTF8ByteOrderMark (const char *&First, const char *const End)
Detailed Description
This is the interface for scanning header and source files to get the minimum necessary preprocessor directives for evaluating includes.
It reduces the source down to #define, #include, #import, @import, and any conditional preprocessor logic that contains one of those.
Definition in file DependencyDirectivesScanner.cpp.
Function Documentation
isEOL()
static unsigned isEOL (const char * First, const char *const End) static
Definition at line 248 of file DependencyDirectivesScanner.cpp.
References clang::First, and clang::isVerticalWhitespace().
Referenced by skipNewline(), skipString(), and skipToNewlineRaw().
isQuoteCppDigitSeparator()
static bool isQuoteCppDigitSeparator (const char *const Start, const char *const Cur, const char *const End) static
Returns
True if the current single quotation mark character is a C++ 14 digit separator.
Definition at line 345 of file DependencyDirectivesScanner.cpp.
References clang::isAsciiIdentifierContinue(), and clang::isPreprocessingNumberBody().
Referenced by skipLine().
isRawStringLiteral()
static LLVM_NODISCARD bool isRawStringLiteral (const char * First, const char * Current) static
Definition at line 180 of file DependencyDirectivesScanner.cpp.
References clang::First, and clang::isAsciiIdentifierContinue().
Referenced by skipLine().
isStartOfRelevantLine()
static bool isStartOfRelevantLine (char First) static
Definition at line 687 of file DependencyDirectivesScanner.cpp.
References clang::First.
skipBlockComment()
static void skipBlockComment (const char *& First, const char *const End) static
Definition at line 330 of file DependencyDirectivesScanner.cpp.
References clang::First.
Referenced by skipLine(), and skipWhitespace().
skipDirective()
static void skipDirective (StringRef Name, const char *& First, const char *const End) static
Definition at line 419 of file DependencyDirectivesScanner.cpp.
References clang::Default, clang::First, skipLine(), and skipToNewlineRaw().
skipLine()
static void skipLine (const char *& First, const char *const End) static
Definition at line 367 of file DependencyDirectivesScanner.cpp.
References clang::First, isQuoteCppDigitSeparator(), isRawStringLiteral(), clang::isVerticalWhitespace(), skipBlockComment(), skipLineComment(), skipNewline(), skipRawString(), skipString(), and wasLineContinuation().
Referenced by skipDirective().
skipLineComment()
static void skipLineComment (const char *& First, const char *const End) static
Definition at line 324 of file DependencyDirectivesScanner.cpp.
References clang::First, and skipToNewlineRaw().
Referenced by skipLine(), and skipWhitespace().
skipNewline()
static unsigned skipNewline (const char *& First, const char * End) static
Definition at line 287 of file DependencyDirectivesScanner.cpp.
References clang::First, isEOL(), and clang::isVerticalWhitespace().
Referenced by skipLine(), and skipWhitespace().
skipOverSpaces()
static void skipOverSpaces (const char *& First, const char *const End) static
Definition at line 175 of file DependencyDirectivesScanner.cpp.
References clang::First, and clang::isHorizontalWhitespace().
Referenced by skipString(), and skipWhitespace().
skipRawString()
static void skipRawString (const char *& First, const char *const End) static
Definition at line 205 of file DependencyDirectivesScanner.cpp.
References clang::First, and clang::Last.
Referenced by skipLine().
skipString()
static void skipString (const char *& First, const char *const End) static
Definition at line 257 of file DependencyDirectivesScanner.cpp.
References clang::First, isEOL(), clang::isVerticalWhitespace(), clang::isWhitespace(), and skipOverSpaces().
Referenced by skipLine().
skipToNewlineRaw()
static void skipToNewlineRaw (const char *& First, const char *const End) static
Definition at line 301 of file DependencyDirectivesScanner.cpp.
References clang::First, and isEOL().
Referenced by skipDirective(), and skipLineComment().
skipUTF8ByteOrderMark()
static void skipUTF8ByteOrderMark (const char *& First, const char *const End) static
Definition at line 787 of file DependencyDirectivesScanner.cpp.
References clang::First.
skipWhitespace()
static void skipWhitespace (const char *& First, const char *const End) static
Definition at line 431 of file DependencyDirectivesScanner.cpp.
References clang::First, clang::isVerticalWhitespace(), skipBlockComment(), skipLineComment(), skipNewline(), and skipOverSpaces().
wasLineContinuation()
static bool wasLineContinuation (const char * First, unsigned EOLLen) static
Definition at line 297 of file DependencyDirectivesScanner.cpp.
References clang::First, and int.
Referenced by skipLine().