clang: lib/Driver/ToolChains/Hexagon.cpp File Reference
Hexagon.cpp File Reference
#include "Hexagon.h"
#include "CommonArgs.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
Functions
static StringRef getDefaultHvxLength (StringRef HvxVer)
static void handleHVXWarnings (const Driver &D, const ArgList &Args)
static void handleHVXTargetFeatures (const Driver &D, const ArgList &Args, std::vector< StringRef > &Features, StringRef Cpu, bool &HasHVX)
static void constructHexagonLinkArgs (Compilation &C, const JobAction &JA, const toolchains::HexagonToolChain &HTC, const InputInfo &Output, const InputInfoList &Inputs, const ArgList &Args, ArgStringList &CmdArgs, const char *LinkingOutput)
Function Documentation
constructHexagonLinkArgs()
static void constructHexagonLinkArgs (Compilation & C, const JobAction & JA, const toolchains::HexagonToolChain & HTC, const InputInfo & Output, const InputInfoList & Inputs, const ArgList & Args, ArgStringList & CmdArgs, const char * LinkingOutput) static
Definition at line 277 of file Hexagon.cpp.
References clang::driver::toolchains::HexagonToolChain::AddCXXStdlibLibArgs(), clang::driver::tools::AddLinkerInputs(), clang::driver::tools::addSanitizerRuntimes(), clang::driver::tools::addXRayRuntime(), clang::driver::Driver::CCCIsCXX(), clang::driver::toolchains::Linux::ExtraOpts, clang::driver::ToolChain::getDriver(), clang::driver::InputInfo::getFilename(), clang::driver::ToolChain::GetFilePath(), clang::driver::ToolChain::getFilePaths(), clang::driver::toolchains::HexagonToolChain::getHexagonTargetDir(), clang::driver::ToolChain::GetLinkerPath(), clang::driver::toolchains::HexagonToolChain::getSmallDataThreshold(), clang::driver::toolchains::HexagonToolChain::GetTargetCPUVersion(), clang::driver::ToolChain::getTriple(), clang::driver::Driver::InstalledDir, IsStatic, clang::driver::tools::linkSanitizerRuntimeDeps(), clang::driver::tools::linkXRayRuntimeDeps(), P, clang::driver::Driver::PrefixDirs, clang::driver::ToolChain::ShouldLinkCXXStdlib(), and clang::driver::Driver::SysRoot.
Referenced by clang::driver::tools::hexagon::Linker::ConstructJob().
getDefaultHvxLength()
static StringRef getDefaultHvxLength (StringRef HvxVer) static
Definition at line 29 of file Hexagon.cpp.
Referenced by handleHVXTargetFeatures().
handleHVXTargetFeatures()
static void handleHVXTargetFeatures (const Driver & D, const ArgList & Args, std::vector< StringRef > & Features, StringRef Cpu, bool & HasHVX) static
Definition at line 48 of file Hexagon.cpp.
References clang::driver::Driver::Diag(), getDefaultHvxLength(), handleHVXWarnings(), and clang::None.
handleHVXWarnings()
static void handleHVXWarnings (const Driver & D, const ArgList & Args) static
Definition at line 37 of file Hexagon.cpp.
References clang::driver::Driver::Diag().
Referenced by handleHVXTargetFeatures().