clang: lib/Driver/ToolChains/Arch/ARM.cpp File Reference
ARM.cpp File Reference
#include "ARM.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/ARMTargetParser.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/Host.h"
Functions
static void getARMHWDivFeatures (const Driver &D, const Arg *A, const ArgList &Args, StringRef HWDiv, std::vector< StringRef > &Features)
static unsigned getARMFPUFeatures (const Driver &D, const Arg *A, const ArgList &Args, StringRef FPU, std::vector< StringRef > &Features)
static bool DecodeARMFeatures (const Driver &D, StringRef text, StringRef CPU, llvm::ARM::ArchKind ArchKind, std::vector< StringRef > &Features, unsigned &ArgFPUID)
static void DecodeARMFeaturesFromCPU (const Driver &D, StringRef CPU, std::vector< StringRef > &Features)
static void checkARMArchName (const Driver &D, const Arg *A, const ArgList &Args, llvm::StringRef ArchName, llvm::StringRef CPUName, std::vector< StringRef > &Features, const llvm::Triple &Triple, unsigned &ArgFPUID)
static void checkARMCPUName (const Driver &D, const Arg *A, const ArgList &Args, llvm::StringRef CPUName, llvm::StringRef ArchName, std::vector< StringRef > &Features, const llvm::Triple &Triple, unsigned &ArgFPUID)
static bool hasIntegerMVE (const std::vector< StringRef > &F)
Function Documentation
checkARMArchName()
static void checkARMArchName (const Driver & D, const Arg * A, const ArgList & Args, llvm::StringRef ArchName, llvm::StringRef CPUName, std::vector< StringRef > & Features, const llvm::Triple & Triple, unsigned & ArgFPUID) static
Definition at line 113 of file ARM.cpp.
References DecodeARMFeatures(), clang::driver::Driver::Diag(), clang::driver::tools::arm::getARMArch(), and clang::driver::tools::Split.
checkARMCPUName()
static void checkARMCPUName (const Driver & D, const Arg * A, const ArgList & Args, llvm::StringRef CPUName, llvm::StringRef ArchName, std::vector< StringRef > & Features, const llvm::Triple & Triple, unsigned & ArgFPUID) static
Definition at line 129 of file ARM.cpp.
References DecodeARMFeatures(), clang::driver::Driver::Diag(), clang::driver::tools::arm::getARMTargetCPU(), clang::driver::tools::arm::getLLVMArchKindForARM(), and clang::driver::tools::Split.
DecodeARMFeatures()
static bool DecodeARMFeatures (const Driver & D, StringRef text, StringRef CPU, llvm::ARM::ArchKind ArchKind, std::vector< StringRef > & Features, unsigned & ArgFPUID) static
Definition at line 86 of file ARM.cpp.
References clang::driver::tools::Split.
Referenced by checkARMArchName(), and checkARMCPUName().
DecodeARMFeaturesFromCPU()
static void DecodeARMFeaturesFromCPU (const Driver & D, StringRef CPU, std::vector< StringRef > & Features) static
Definition at line 100 of file ARM.cpp.
getARMFPUFeatures()
static unsigned getARMFPUFeatures (const Driver & D, const Arg * A, const ArgList & Args, StringRef FPU, std::vector< StringRef > & Features) static
Definition at line 76 of file ARM.cpp.
References clang::driver::Driver::Diag().
getARMHWDivFeatures()
static void getARMHWDivFeatures (const Driver & D, const Arg * A, const ArgList & Args, StringRef HWDiv, std::vector< StringRef > & Features) static
Definition at line 67 of file ARM.cpp.
References clang::driver::Driver::Diag().
hasIntegerMVE()
static bool hasIntegerMVE (const std::vector< StringRef > & F) static
Definition at line 432 of file ARM.cpp.