clang: lib/StaticAnalyzer/Checkers/DynamicTypeChecker.cpp File Reference
DynamicTypeChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicType.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
Functions
static bool hasDefinition (const ObjCObjectPointerType *ObjPtr)
Function Documentation
hasDefinition()
static bool hasDefinition (const ObjCObjectPointerType * ObjPtr) static
Definition at line 145 of file DynamicTypeChecker.cpp.
References clang::ObjCObjectPointerType::getInterfaceDecl().
Referenced by clang::TagDecl::completeDefinition(), and clang::Sema::HandleDeclarator().