clang: lib/StaticAnalyzer/Core/ExprEngineObjC.cpp File Reference
ExprEngineObjC.cpp File Reference
#include "clang/AST/StmtObjC.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
Functions
static void populateObjCForDestinationSet (ExplodedNodeSet &dstLocation, SValBuilder &svalBuilder, const ObjCForCollectionStmt *S, const Stmt *elem, SVal elementV, SymbolManager &SymMgr, const NodeBuilderContext *currBldrCtx, StmtNodeBuilder &Bldr, bool hasElements)
Generate a node in Bldr for an iteration statement using ObjC for-loop iterator.
Function Documentation
populateObjCForDestinationSet()
static void populateObjCForDestinationSet (ExplodedNodeSet & dstLocation, SValBuilder & svalBuilder, const ObjCForCollectionStmt * S, const Stmt * elem, SVal elementV, SymbolManager & SymMgr, const NodeBuilderContext * currBldrCtx, StmtNodeBuilder & Bldr, bool hasElements) static
Generate a node in Bldr for an iteration statement using ObjC for-loop iterator.
Definition at line 46 of file ExprEngineObjC.cpp.
References clang::ento::NodeBuilderContext::blockCount(), clang::ento::SymbolManager::conjureSymbol(), clang::ento::StmtNodeBuilder::generateNode(), clang::ento::SVal::getAs(), clang::ento::Loc::isLocType(), clang::ento::SValBuilder::makeIntVal(), clang::ento::SValBuilder::makeLoc(), clang::ento::ExprEngine::setWhetherHasMoreIteration(), and V.
Referenced by clang::ento::ExprEngine::VisitObjCForCollectionStmt().