clang: lib/AST/Interp/Interp.cpp File Reference
Interp.cpp File Reference
#include "Interp.h"
#include <limits>
#include <vector>
#include "Function.h"
#include "InterpFrame.h"
#include "InterpStack.h"
#include "Opcode.h"
#include "PrimType.h"
#include "Program.h"
#include "State.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "llvm/ADT/APSInt.h"
#include "Opcodes.inc"
Namespaces
namespace clang
namespace clang::interp
Macros
#define GET_INTERP
Functions
template<PrimType Name, class T = typename PrimConv<Name>::T>
static bool Ret (InterpState &S, CodePtr &PC, APValue &Result)
static bool RetVoid (InterpState &S, CodePtr &PC, APValue &Result)
static bool RetValue (InterpState &S, CodePtr &Pt, APValue &Result)
static bool Jmp (InterpState &S, CodePtr &PC, int32_t Offset)
static bool Jt (InterpState &S, CodePtr &PC, int32_t Offset)
static bool Jf (InterpState &S, CodePtr &PC, int32_t Offset)
static bool CheckInitialized (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
static bool CheckActive (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
static bool CheckTemporary (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
static bool CheckGlobal (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
bool clang::interp::CheckExtern (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if the variable has externally defined storage.
bool clang::interp::CheckArray (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if the array is offsetable.
bool clang::interp::CheckLive (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
Checks if a pointer is live and accessible.
bool clang::interp::CheckNull (InterpState &S, CodePtr OpPC, const Pointer &Ptr, CheckSubobjectKind CSK)
Checks if a pointer is null.
bool clang::interp::CheckRange (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
Checks if a pointer is in range.
bool clang::interp::CheckRange (InterpState &S, CodePtr OpPC, const Pointer &Ptr, CheckSubobjectKind CSK)
Checks if a field from which a pointer is going to be derived is valid.
bool clang::interp::CheckConst (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a pointer points to const storage.
bool clang::interp::CheckMutable (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a pointer points to a mutable field.
bool clang::interp::CheckLoad (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be loaded from a block.
bool clang::interp::CheckStore (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be stored in a block.
bool clang::interp::CheckInvoke (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a method can be invoked on an object.
bool clang::interp::CheckInit (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be initialized.
bool clang::interp::CheckCallable (InterpState &S, CodePtr OpPC, Function *F)
Checks if a method can be called.
bool clang::interp::CheckThis (InterpState &S, CodePtr OpPC, const Pointer &This)
Checks the 'this' pointer.
bool clang::interp::CheckPure (InterpState &S, CodePtr OpPC, const CXXMethodDecl *MD)
Checks if a method is pure virtual.
bool clang::interp::Interpret (InterpState &S, APValue &Result)
Interpreter entry point.
Macro Definition Documentation
GET_INTERP
#define GET_INTERP
Function Documentation
CheckActive()
static bool CheckActive (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK) static
Definition at line 112 of file Interp.cpp.
References clang::interp::Pointer::getBase(), clang::interp::Pointer::getField(), clang::interp::Record::getField(), clang::interp::Record::getNumFields(), clang::interp::Pointer::isActive(), clang::interp::Record::isUnion(), N, and clang::interp::Record::Field::Offset.
Referenced by clang::interp::CheckLoad().
CheckGlobal()
static bool CheckGlobal (InterpState & S, CodePtr OpPC, const Pointer & Ptr) static
Definition at line 164 of file Interp.cpp.
References clang::interp::Pointer::getDeclID(), and clang::interp::Pointer::isStatic().
Referenced by clang::interp::CheckStore().
CheckInitialized()
static bool CheckInitialized (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK) static
Definition at line 101 of file Interp.cpp.
References clang::interp::Pointer::isInitialized().
Referenced by clang::interp::CheckLoad().
CheckTemporary()
static bool CheckTemporary (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK) static
Definition at line 144 of file Interp.cpp.
References clang::interp::Pointer::getDeclDesc(), clang::interp::Pointer::getDeclID(), clang::interp::Pointer::getDeclLoc(), clang::interp::Descriptor::getType(), clang::QualType::isConstQualified(), and clang::interp::Pointer::isStaticTemporary().
Referenced by clang::interp::CheckLoad().
Jf()
static bool Jf (InterpState & S, CodePtr & PC, int32_t Offset) static
Definition at line 94 of file Interp.cpp.
References Offset.
Jmp()
static bool Jmp (InterpState & S, CodePtr & PC, int32_t Offset) static
Definition at line 82 of file Interp.cpp.
References Offset.
Jt()
static bool Jt (InterpState & S, CodePtr & PC, int32_t Offset) static
Definition at line 87 of file Interp.cpp.
References Offset.
Ret()
template<PrimType Name, class T = typename PrimConv<Name>::T> static bool Ret (InterpState & S, CodePtr & PC, APValue & Result) static
Definition at line 34 of file Interp.cpp.
References clang::Result, Ret(), and clang::interp::ReturnValue().
Referenced by adjustColumnPos(), adjustColumnPos(), clang::SarifDocumentWriter::appendResult(), clang::WrapperFrontendAction::BeginSourceFileAction(), checkFoundationAPI(), collectStrongDependencies(), collectWeakDependencies(), createCopyAssignmentDefinitionData(), createCopyConstructorDefinitionData(), createDefaultConstructorDefinitionData(), createDestructorDefinitionData(), createLocation(), createLocation(), createMoveAssignmentDefinitionData(), createMoveConstructorDefinitionData(), CreateNewFunctionDecl(), clang::SarifDocumentWriter::createRule(), createRule(), clang::CodeGen::CodeGenModule::CreateRuntimeVariable(), didPreviousFreeFail(), clang::Sema::ExtractUnqualifiedFunctionType(), fileNameToURI(), fileNameToURI(), llvm::IDFCalculatorDetail::ChildrenGetterTy< clang::CFGBlock, IsPostDom >::get(), clang::getAllPossibleAMDGPUTargetIDFeatures(), clang::getAllPossibleTargetIDFeatures(), clang::AnalyzerOptions::getCheckerIntegerOption(), clang::ento::BugType::getCheckerName(), clang::tooling::dependencies::FullDependencies::getCommandLine(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::tooling::IncludeCategoryManager::getIncludePriority(), clang::cross_tu::CrossTranslationUnitContext::getLookupName(), getOutermostFuncOrBlockContext(), clang::tooling::IncludeCategoryManager::getSortIncludePriority(), HandleConstructorCall(), HandleDestructionImpl(), HandleFunctionCall(), clang::TreeTransform< Derived >::RebuildExprRequirement(), clang::TreeTransform< Derived >::RebuildExprRequirement(), Ret(), and clang::consumed::ConsumedStmtVisitor::VisitReturnStmt().
RetValue()
static bool RetValue (InterpState & S, CodePtr & Pt, APValue & Result) static
Definition at line 74 of file Interp.cpp.
RetVoid()
static bool RetVoid (InterpState & S, CodePtr & PC, APValue & Result) static
Definition at line 56 of file Interp.cpp.