clang: lib/Sema/JumpDiagnostics.cpp File Reference
JumpDiagnostics.cpp File Reference
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtObjC.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/BitVector.h"
Macros
#define CHECK_PERMISSIVE(x)
Typedefs
typedef std::pair< unsigned, unsigned > ScopePair
Functions
static ScopePair GetDiagForGotoScopeDecl (Sema &S, const Decl *D)
GetDiagForGotoScopeDecl - If this decl induces a new goto scope, return a diagnostic that should be emitted if control goes over it.
static bool IsMicrosoftJumpWarning (unsigned JumpDiag, unsigned InDiagNote)
Return true if a particular error+note combination must be downgraded to a warning in Microsoft mode.
static bool IsCXX98CompatWarning (Sema &S, unsigned InDiagNote)
Return true if a particular note should be downgraded to a compatibility warning in C++11 mode.
static void DiagnoseIndirectOrAsmJumpStmt (Sema &S, Stmt *Jump, LabelDecl *Target, bool &Diagnosed)
Produce primary diagnostic for an indirect jump statement.
Macro Definition Documentation
CHECK_PERMISSIVE
#define CHECK_PERMISSIVE (x)
Value:
(assert(Permissive || !(x)), (Permissive && (x)))
Definition at line 104 of file JumpDiagnostics.cpp.
Typedef Documentation
ScopePair
typedef std::pair<unsigned,unsigned> ScopePair
Definition at line 140 of file JumpDiagnostics.cpp.
Function Documentation
DiagnoseIndirectOrAsmJumpStmt()
static void DiagnoseIndirectOrAsmJumpStmt (Sema & S, Stmt * Jump, LabelDecl * Target, bool & Diagnosed) static
Produce primary diagnostic for an indirect jump statement.
Definition at line 856 of file JumpDiagnostics.cpp.
References clang::Sema::Diag(), clang::Stmt::getBeginLoc(), and clang::isa().
GetDiagForGotoScopeDecl()
static ScopePair GetDiagForGotoScopeDecl (Sema & S, const Decl * D) static
GetDiagForGotoScopeDecl - If this decl induces a new goto scope, return a diagnostic that should be emitted if control goes over it.
If not, return 0.
Definition at line 144 of file JumpDiagnostics.cpp.
References clang::VarDecl::CallInit, clang::Sema::Context, clang::QualType::DK_cxx_destructor, clang::QualType::DK_none, clang::QualType::DK_nontrivial_c_struct, clang::QualType::DK_objc_strong_lifetime, clang::QualType::DK_objc_weak_lifetime, clang::ASTContext::getLangOpts(), clang::CXXMethodDecl::getParent(), clang::CXXConstructorDecl::isDefaultConstructor(), clang::CXXRecordDecl::isPOD(), and clang::FunctionDecl::isTrivial().
IsCXX98CompatWarning()
static bool IsCXX98CompatWarning (Sema & S, unsigned InDiagNote) static
Return true if a particular note should be downgraded to a compatibility warning in C++11 mode.
Definition at line 850 of file JumpDiagnostics.cpp.
References clang::Sema::getLangOpts().
IsMicrosoftJumpWarning()
static bool IsMicrosoftJumpWarning (unsigned JumpDiag, unsigned InDiagNote) static
Return true if a particular error+note combination must be downgraded to a warning in Microsoft mode.
Definition at line 842 of file JumpDiagnostics.cpp.