clang: clang::randstruct Namespace Reference
clang::randstruct Namespace Reference
Functions
bool randomizeStructureLayout (const ASTContext &Context, RecordDecl *RD, llvm::SmallVectorImpl< Decl * > &FinalOrdering)
Function Documentation
randomizeStructureLayout()
bool clang::randstruct::randomizeStructureLayout (const ASTContext & Context, RecordDecl * RD, llvm::SmallVectorImpl< Decl * > & FinalOrdering)
Definition at line 175 of file Randstruct.cpp.
References clang::DeclContext::decls(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getNameAsString(), clang::RecordDecl::hasFlexibleArrayMember(), randomizeStructureLayout(), and clang::LangOptions::RandstructSeed.
Referenced by clang::Sema::ActOnFields(), and randomizeStructureLayout().