clang: clang::driver::tools::sparc Namespace Reference
clang::driver::tools::sparc Namespace Reference
Enumerations
enum class FloatABI { Invalid , Soft , Hard }
Functions
FloatABI getSparcFloatABI (const Driver &D, const llvm::opt::ArgList &Args)
std::string getSparcTargetCPU (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
void getSparcTargetFeatures (const Driver &D, const llvm::opt::ArgList &Args, std::vector< llvm::StringRef > &Features)
const char * getSparcAsmModeForCPU (llvm::StringRef Name, const llvm::Triple &Triple)
Enumeration Type Documentation
FloatABI
enum class clang::driver::tools::sparc::FloatABI strong
Enumerator
Invalid
Soft
Hard
Definition at line 23 of file Sparc.h.
Function Documentation
getSparcAsmModeForCPU()
const char * clang::driver::tools::sparc::getSparcAsmModeForCPU (llvm::StringRef Name, const llvm::Triple & Triple)
Referenced by clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
getSparcFloatABI()
FloatABI clang::driver::tools::sparc::getSparcFloatABI (const Driver & D, const llvm::opt::ArgList & Args)
getSparcTargetCPU()
std::string clang::driver::tools::sparc::getSparcTargetCPU (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
getSparcTargetFeatures()
void clang::driver::tools::sparc::getSparcTargetFeatures (const Driver & D, const llvm::opt::ArgList & Args, std::vector< llvm::StringRef > & Features)
Referenced by getTargetFeatures().