clang: llvm Namespace Reference
llvm Namespace Reference
YAML serialization mapping.
Namespaces
namespace cl
namespace IDFCalculatorDetail
namespace json
namespace opt
namespace optional_detail
namespace orc
namespace vfs
namespace yaml
Classes
class ArrayRef
struct cast_convert_val< ::clang::DeclContext, FromTy *, FromTy * >
struct cast_convert_val< ::clang::DeclContext, FromTy, FromTy >
Implement cast_convert_val for Decl -> DeclContext conversions.
struct cast_convert_val< const ::clang::DeclContext, FromTy *, FromTy * >
struct cast_convert_val< const ::clang::DeclContext, FromTy, FromTy >
struct cast_convert_val< ToTy, ::clang::DeclContext *, ::clang::DeclContext * >
struct cast_convert_val< ToTy, ::clang::DeclContext, ::clang::DeclContext >
struct cast_convert_val< ToTy, const ::clang::DeclContext *, const ::clang::DeclContext * >
struct cast_convert_val< ToTy, const ::clang::DeclContext, const ::clang::DeclContext >
cast<T>(DeclContext*)
struct CastInfo< To, From, std::enable_if_t< std::is_base_of<::clang::ento::SVal, From >::value > >
struct DenseMapInfo< CatchHandlerType >
struct DenseMapInfo< clang::APValue::LValueBase >
struct DenseMapInfo< clang::ASTNodeKind >
struct DenseMapInfo< clang::BaseSubobject >
struct DenseMapInfo< clang::CallGraphNode::CallRecord >
struct DenseMapInfo< clang::CanonicalDeclPtr< decl_type > >
struct DenseMapInfo< clang::CanQualType >
struct DenseMapInfo< clang::CharUnits >
struct DenseMapInfo< clang::CodeGen::TBAAAccessInfo >
struct DenseMapInfo< clang::DeclarationName >
Define DenseMapInfo so that DeclarationNames can be used as keys in DenseMap and DenseSets.
struct DenseMapInfo< clang::DirectoryEntryRef >
Specialisation of DenseMapInfo for DirectoryEntryRef.
struct DenseMapInfo< clang::DynTypedNode >
struct DenseMapInfo< clang::FileEntryRef >
Specialisation of DenseMapInfo for FileEntryRef.
struct DenseMapInfo< clang::FileID, void >
Define DenseMapInfo so that FileID's can be used as keys in DenseMap and DenseSets.
struct DenseMapInfo< clang::GlobalDecl >
struct DenseMapInfo< clang::NestedNameSpecifierLoc >
struct DenseMapInfo< clang::ProgramPoint >
struct DenseMapInfo< clang::QualType >
struct DenseMapInfo< clang::Selector >
Define DenseMapInfo so that Selectors can be used as keys in DenseMap and DenseSets.
struct DenseMapInfo< clang::Sema::FunctionDeclAndLoc >
struct DenseMapInfo< clang::serialization::DeclarationNameKey >
struct DenseMapInfo< clang::SourceLocation, void >
Define DenseMapInfo so that SourceLocation's can be used as keys in DenseMap and DenseSet.
struct DenseMapInfo< clang::tok::PPKeywordKind >
struct DenseMapInfo< clang::tooling::stdlib::Header >
struct DenseMapInfo< clang::tooling::stdlib::Symbol >
struct DenseMapInfo< DecompositionDeclName >
struct DenseMapInfo< EditEntry >
struct DenseMapInfo< ObjCSummaryKey >
struct DenseMapInfo< ObjectUnderConstruction >
struct DenseMapInfo< PrivateMethodKey >
class DenseSet
struct DOTGraphTraits< const CallGraph * >
struct DOTGraphTraits< const CFG * >
struct DOTGraphTraits< const Stmt * >
struct DOTGraphTraits< ExplodedGraph * >
struct DOTGraphTraits< ModuleManager >
class Expected
struct FoldingSetTrait
struct FoldingSetTrait< AllocKind >
struct FoldingSetTrait< ArgEffect >
struct FoldingSetTrait< clang::SourceLocation, void >
struct FoldingSetTrait< ObjectState >
struct FoldingSetTrait< RetEffect >
struct FoldingSetTrait< SValData >
struct FoldingSetTrait< SValPair >
struct GraphTraits< ::clang::CFG * >
struct GraphTraits< ::clang::CFGBlock * >
struct GraphTraits< clang::CallGraph * >
struct GraphTraits< clang::CallGraphNode * >
struct GraphTraits< clang::CFGDomTree * >
struct GraphTraits< clang::DomTreeNode * >
DominatorTree GraphTraits specialization so the DominatorTree can be iterable by generic graph iterators.
struct GraphTraits< clang::ento::ExplodedGraph * >
struct GraphTraits< clang::Stmt * >
struct GraphTraits< const ::clang::CFG * >
struct GraphTraits< const ::clang::CFGBlock * >
struct GraphTraits< const clang::CallGraph * >
struct GraphTraits< const clang::CallGraphNode * >
struct GraphTraits< const clang::Stmt * >
struct GraphTraits< Inverse< ::clang::CFG * > >
struct GraphTraits< Inverse< ::clang::CFGBlock * > >
struct GraphTraits< Inverse< const ::clang::CFG * > >
struct GraphTraits< Inverse< const ::clang::CFGBlock * > >
struct GraphTraits< ModuleManager >
class IntrusiveRefCntPtr
struct IntrusiveRefCntPtrInfo
struct IntrusiveRefCntPtrInfo< const clang::ento::ProgramState >
struct isa_impl< To, ::clang::DeclContext >
isa<T>(DeclContext*)
class MutableArrayRef
class Optional
class OwningArrayRef
struct PointerLikeTypeTraits
struct PointerLikeTypeTraits< ::clang::CodeGen::ConstantInitBuilderBase * >
struct PointerLikeTypeTraits< ::clang::CodeGen::ConstantInitFuture >
struct PointerLikeTypeTraits< ::clang::ExtQuals * >
struct PointerLikeTypeTraits< ::clang::Type * >
struct PointerLikeTypeTraits< clang::CanonicalDeclPtr< decl_type > >
struct PointerLikeTypeTraits< clang::CanQual< T > >
struct PointerLikeTypeTraits< clang::DeclarationName >
struct PointerLikeTypeTraits< clang::DeclGroupRef >
struct PointerLikeTypeTraits< clang::DynamicAllocLValue >
struct PointerLikeTypeTraits< clang::Expr * >
struct PointerLikeTypeTraits< clang::IdentifierInfo * >
struct PointerLikeTypeTraits< clang::LazyGenerationalUpdatePtr< Owner, T, Update > >
Specialize PointerLikeTypeTraits to allow LazyGenerationalUpdatePtr to be placed into a PointerUnion.
struct PointerLikeTypeTraits< clang::OpaquePtr< T > >
struct PointerLikeTypeTraits< clang::QualType >
struct PointerLikeTypeTraits< clang::Selector >
struct PointerLikeTypeTraits< clang::TemplateName >
The clang::TemplateName class is effectively a pointer.
struct PointerLikeTypeTraits< clang::TypeInfoLValue >
struct PointerLikeTypeTraits< const clang::IdentifierInfo * >
struct PointerLikeTypeTraits<::clang::NamedDecl * >
class RefCountedBase
struct SaveAndRestore
struct simplify_type< ::clang::CanQual< T > >
Implement simplify_type for CanQual<T>, so that we can dyn_cast from CanQual<T> to a specific Type class.
struct simplify_type< ::clang::CFGTerminator >
Implement simplify_type for CFGTerminator, so that we can dyn_cast from CFGTerminator to a specific Stmt class.
struct simplify_type< ::clang::QualType >
Implement simplify_type for QualType, so that we can dyn_cast from QualType to a specific Type class.
struct simplify_type< clang::ento::CallEventRef< T > >
class SmallPtrSet
class SmallSetVector
class SmallString
class SmallVector
class SmallVectorImpl
Functions
template<typename T >
bool isDenseMapKeyEmpty (T V)
template<typename T >
bool isDenseMapKeyTombstone (T V)
template<typename T >
Optional< bool > areDenseMapKeysEqualSpecialValues (T LHS, T RHS)
static raw_ostream & operator<< (raw_ostream &Out, BindingKey K)
Variables
cl::opt< bool > DebugInfoCorrelate
Detailed Description
YAML serialization mapping.
Function Documentation
areDenseMapKeysEqualSpecialValues()
template<typename T > Optional< bool > llvm::areDenseMapKeysEqualSpecialValues (T LHS, T RHS)
Definition at line 88 of file ItaniumCXXABI.cpp.
References isDenseMapKeyEmpty(), isDenseMapKeyTombstone(), and clang::None.
Referenced by llvm::DenseMapInfo< DecompositionDeclName >::isEqual().
isDenseMapKeyEmpty()
template<typename T > bool llvm::isDenseMapKeyEmpty (T V)
Definition at line 78 of file ItaniumCXXABI.cpp.
References V.
Referenced by areDenseMapKeysEqualSpecialValues().
isDenseMapKeyTombstone()
template<typename T > bool llvm::isDenseMapKeyTombstone (T V)
Definition at line 82 of file ItaniumCXXABI.cpp.
References V.
Referenced by areDenseMapKeysEqualSpecialValues().
operator<<()
static raw_ostream & llvm::operator<< (raw_ostream & Out, BindingKey K) inline static
Definition at line 124 of file RegionStore.cpp.
Variable Documentation
DebugInfoCorrelate
cl::opt<bool> llvm::DebugInfoCorrelate extern