clang: clang::driver::tools::amdgpu Namespace Reference
clang::driver::tools::amdgpu Namespace Reference
Classes
class Linker
Functions
void getAMDGPUTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< StringRef > &Features)
Function Documentation
getAMDGPUTargetFeatures()
void clang::driver::tools::amdgpu::getAMDGPUTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< StringRef > & Features)
Definition at line 544 of file AMDGPU.cpp.
References clang::getAllPossibleTargetIDFeatures(), clang::driver::tools::handleTargetFeaturesGroup(), and clang::parseTargetID().
Referenced by getTargetFeatures().