clang: clang::ento::cocoa Namespace Reference
clang::ento::cocoa Namespace Reference
Functions
bool isRefType (QualType RetTy, StringRef Prefix, StringRef Name=StringRef())
bool isCocoaObjectRef (QualType T)
Function Documentation
isCocoaObjectRef()
bool clang::ento::cocoa::isCocoaObjectRef (QualType T)
Definition at line 65 of file CocoaConventions.cpp.
References clang::Type::getAs(), clang::ObjCObjectPointerType::getInterfaceDecl(), clang::ObjCObjectPointerType::isObjCClassType(), clang::ObjCObjectPointerType::isObjCIdType(), clang::Type::isObjCObjectPointerType(), clang::ObjCObjectPointerType::isObjCQualifiedClassType(), and clang::ObjCObjectPointerType::isObjCQualifiedIdType().
isRefType()
bool clang::ento::cocoa::isRefType (QualType RetTy, StringRef Prefix, StringRef Name = StringRef())
Definition at line 24 of file CocoaConventions.cpp.
References clang::Type::castAs(), clang::Type::getAs(), clang::PointerType::getPointeeType(), clang::QualType::getUnqualifiedType(), and clang::Type::isVoidType().
Referenced by clang::ento::RetainSummaryManager::canEval(), clang::ento::coreFoundation::isCFObjectRef(), isDiskArbitrationAPIRefType(), and clang::arcmt::trans::isPlusOne().