clang: clang::driver::tools::csky Namespace Reference
clang::driver::tools::csky Namespace Reference
Enumerations
enum class FloatABI { Invalid , Soft , SoftFP , Hard }
Functions
FloatABI getCSKYFloatABI (const Driver &D, const llvm::opt::ArgList &Args)
void getCSKYTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, std::vector< llvm::StringRef > &Features)
llvm::Optional< llvm::StringRef > getCSKYArchName (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
Enumeration Type Documentation
FloatABI
enum class clang::driver::tools::csky::FloatABI strong
Enumerator
Invalid
Soft
SoftFP
Hard
Definition at line 24 of file CSKY.h.
Function Documentation
getCSKYArchName()
llvm::Optional< llvm::StringRef > clang::driver::tools::csky::getCSKYArchName (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by findCSKYMultilibs().
getCSKYFloatABI()
FloatABI clang::driver::tools::csky::getCSKYFloatABI (const Driver & D, const llvm::opt::ArgList & Args)
Referenced by findCSKYMultilibs().
getCSKYTargetFeatures()
void clang::driver::tools::csky::getCSKYTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, std::vector< llvm::StringRef > & Features)
Referenced by getTargetFeatures().