clang: clang::driver::tools Namespace Reference
clang::driver::tools Namespace Reference
Namespaces
namespace aarch64
namespace aix
aix – Directly call system default assembler and linker.
namespace AMDGCN
namespace amdgpu
namespace ananas
ananas – Directly call GNU Binutils assembler and linker
namespace arm
namespace AVR
namespace baremetal
namespace cloudabi
cloudabi – Directly call GNU Binutils linker
namespace CrossWindows
namespace CSKY
namespace csky
namespace darwin
namespace dragonfly
dragonfly – Directly call GNU Binutils assembler and linker
namespace freebsd
freebsd – Directly call GNU Binutils assembler and linker
namespace fuchsia
namespace gcc
gcc - Generic GCC tool implementations.
namespace gnutools
Directly call GNU Binutils' assembler and linker.
namespace hexagon
namespace HIP
namespace HIPSPV
namespace ifstool
namespace m68k
namespace MinGW
MinGW – Directly call GNU Binutils assembler and linker.
namespace minix
minix – Directly call GNU Binutils assembler and linker
namespace mips
namespace msp430
namespace Myriad
The Myriad toolchain uses tools that are in two different namespaces.
namespace nacltools
namespace netbsd
netbsd – Directly call GNU Binutils assembler and linker
namespace NVPTX
namespace openbsd
openbsd – Directly call GNU Binutils assembler and linker
namespace ppc
namespace PScpu
namespace RISCV
namespace riscv
namespace SHAVE
SHAVE tools – Directly call moviCompile and moviAsm.
namespace solaris
solaris – Directly call Solaris assembler and linker
namespace sparc
namespace SPIRV
namespace systemz
namespace ve
namespace visualstudio
Visual studio tools.
namespace wasm
namespace x86
namespace XCore
Classes
class Clang
Clang compiler tool.
class ClangAs
Clang integrated assembler tool.
class Flang
Flang compiler tool.
class LinkerWrapper
Linker wrapper tool.
class OffloadBundler
Offload bundler tool.
class OffloadPackager
Offload binary tool.
class OffloadWrapper
Offload wrapper tool.
Enumerations
enum class DwarfFissionKind { None , Split , Single }
Functions
DwarfFissionKind getDebugFissionKind (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::Arg *&Arg)
void addPathIfExists (const Driver &D, const Twine &Path, ToolChain::path_list &Paths)
void AddLinkerInputs (const ToolChain &TC, const InputInfoList &Inputs, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const JobAction &JA)
void addLinkerCompressDebugSectionsOption (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void claimNoWarnArgs (const llvm::opt::ArgList &Args)
bool addSanitizerRuntimes (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void linkSanitizerRuntimeDeps (const ToolChain &TC, llvm::opt::ArgStringList &CmdArgs)
bool addXRayRuntime (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void linkXRayRuntimeDeps (const ToolChain &TC, llvm::opt::ArgStringList &CmdArgs)
void AddRunTimeLibs (const ToolChain &TC, const Driver &D, llvm::opt::ArgStringList &CmdArgs, const llvm::opt::ArgList &Args)
void AddStaticDeviceLibsLinking (Compilation &C, const Tool &T, const JobAction &JA, const InputInfoList &Inputs, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
void AddStaticDeviceLibsPostLinking (const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
void AddStaticDeviceLibs (Compilation *C, const Tool *T, const JobAction *JA, const InputInfoList *Inputs, const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
bool SDLSearch (const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, SmallVector< std::string, 8 > LibraryPaths, std::string Lib, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
SDLSearch: Search for Static Device Library The search for SDL bitcode files is consistent with how static host libraries are discovered.
bool GetSDLFromOffloadArchive (Compilation &C, const Driver &D, const Tool &T, const JobAction &JA, const InputInfoList &Inputs, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, SmallVector< std::string, 8 > LibraryPaths, StringRef Lib, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Search if a user provided archive file lib<libname>.a exists in any of the library paths.
const char * SplitDebugName (const JobAction &JA, const llvm::opt::ArgList &Args, const InputInfo &Input, const InputInfo &Output)
void SplitDebugInfo (const ToolChain &TC, Compilation &C, const Tool &T, const JobAction &JA, const llvm::opt::ArgList &Args, const InputInfo &Output, const char *OutFile)
void addLTOOptions (const ToolChain &ToolChain, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const InputInfo &Output, const InputInfo &Input, bool IsThinLTO)
std::tuple< llvm::Reloc::Model, unsigned, bool > ParsePICArgs (const ToolChain &ToolChain, const llvm::opt::ArgList &Args)
unsigned ParseFunctionAlignment (const ToolChain &TC, const llvm::opt::ArgList &Args)
unsigned ParseDebugDefaultVersion (const ToolChain &TC, const llvm::opt::ArgList &Args)
void AddAssemblerKPIC (const ToolChain &ToolChain, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addOpenMPRuntimeSpecificRPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addArchSpecificRPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addOpenMPRuntimeLibraryPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
bool addOpenMPRuntime (llvm::opt::ArgStringList &CmdArgs, const ToolChain &TC, const llvm::opt::ArgList &Args, bool ForceStaticHostRuntime=false, bool IsOffloadingHost=false, bool GompNeedsRT=false)
Returns true, if an OpenMP runtime has been added.
void addFortranRuntimeLibs (const ToolChain &TC, llvm::opt::ArgStringList &CmdArgs)
Adds Fortran runtime libraries to CmdArgs.
void addFortranRuntimeLibraryPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
Adds the path for the Fortran runtime libraries to CmdArgs.
void addHIPRuntimeLibArgs (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
const char * getAsNeededOption (const ToolChain &TC, bool as_needed)
llvm::opt::Arg * getLastProfileUseArg (const llvm::opt::ArgList &Args)
llvm::opt::Arg * getLastProfileSampleUseArg (const llvm::opt::ArgList &Args)
bool isObjCAutoRefCount (const llvm::opt::ArgList &Args)
llvm::StringRef getLTOParallelism (const llvm::opt::ArgList &Args, const Driver &D)
bool areOptimizationsEnabled (const llvm::opt::ArgList &Args)
bool isUseSeparateSections (const llvm::Triple &Triple)
void addDirectoryList (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const char *ArgName, const char *EnvVar)
EnvVar is split by system delimiter for environment variables.
void AddTargetFeature (const llvm::opt::ArgList &Args, std::vector< StringRef > &Features, llvm::opt::OptSpecifier OnOpt, llvm::opt::OptSpecifier OffOpt, StringRef FeatureName)
std::string getCPUName (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &T, bool FromAs=false)
void handleTargetFeaturesGroup (const llvm::opt::ArgList &Args, std::vector< StringRef > &Features, llvm::opt::OptSpecifier Group)
Iterate Args and convert -mxxx to +xxx and -mno-xxx to -xxx and append it to Features.
SmallVector< StringRef > unifyTargetFeatures (ArrayRef< StringRef > Features)
If there are multiple +xxx or -xxx features, keep the last one.
SmallString< 128 > getStatsFileName (const llvm::opt::ArgList &Args, const InputInfo &Output, const InputInfo &Input, const Driver &D)
Handles the -save-stats option and returns the filename to save statistics to.
void addMultilibFlag (bool Enabled, const char *const Flag, Multilib::flags_list &Flags)
Flag must be a flag accepted by the driver with its leading '-' removed,
void addX86AlignBranchArgs (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool IsLTO)
void checkAMDGPUCodeObjectVersion (const Driver &D, const llvm::opt::ArgList &Args)
unsigned getAMDGPUCodeObjectVersion (const Driver &D, const llvm::opt::ArgList &Args)
bool haveAMDGPUCodeObjectVersionArgument (const Driver &D, const llvm::opt::ArgList &Args)
void addMachineOutlinerArgs (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const llvm::Triple &Triple, bool IsLTO)
void addOpenMPDeviceRTL (const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, StringRef BitcodeSuffix, const llvm::Triple &Triple)
Enumeration Type Documentation
DwarfFissionKind
enum class clang::driver::tools::DwarfFissionKind strong
Enumerator
None
Split
Single
Definition at line 201 of file Clang.h.
Function Documentation
addArchSpecificRPath()
void clang::driver::tools::addArchSpecificRPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by clang::driver::toolchains::VEToolChain::AddCXXStdlibLibArgs(), and addSanitizerRuntime().
AddAssemblerKPIC()
void clang::driver::tools::AddAssemblerKPIC (const ToolChain & ToolChain, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
addDirectoryList()
void clang::driver::tools::addDirectoryList (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const char * ArgName, const char * EnvVar)
EnvVar is split by system delimiter for environment variables.
If ArgName is "-I", "-L", or an empty string, each entry from EnvVar is prefixed by ArgName then added to Args. Otherwise, for each entry of EnvVar, ArgName is added to Args first, then the entry itself is added.
Referenced by clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs(), and clang::driver::toolchains::HIPSPVToolChain::getHIPDeviceLibs().
addFortranRuntimeLibraryPath()
void clang::driver::tools::addFortranRuntimeLibraryPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Adds the path for the Fortran runtime libraries to CmdArgs.
Referenced by clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), and clang::driver::tools::visualstudio::Linker::ConstructJob().
addFortranRuntimeLibs()
void clang::driver::tools::addFortranRuntimeLibs (const ToolChain & TC, llvm::opt::ArgStringList & CmdArgs)
Adds Fortran runtime libraries to CmdArgs.
Definition at line 744 of file CommonArgs.cpp.
References clang::driver::ToolChain::getTriple().
Referenced by clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), and clang::driver::tools::visualstudio::Linker::ConstructJob().
addHIPRuntimeLibArgs()
void clang::driver::tools::addHIPRuntimeLibArgs (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Definition at line 2133 of file CommonArgs.cpp.
References clang::driver::ToolChain::AddHIPRuntimeLibArgs().
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob(), and clang::driver::tools::visualstudio::Linker::ConstructJob().
addLinkerCompressDebugSectionsOption()
void clang::driver::tools::addLinkerCompressDebugSectionsOption (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Definition at line 278 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and V.
Referenced by clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), and clang::driver::tools::gnutools::Linker::ConstructJob().
AddLinkerInputs()
void clang::driver::tools::AddLinkerInputs (const ToolChain & TC, const InputInfoList & Inputs, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const JobAction & JA)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::ananas::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::Linker::ConstructJob(), clang::driver::tools::cloudabi::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::minix::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::Myriad::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::XCore::Linker::ConstructJob().
addLTOOptions()
void clang::driver::tools::addLTOOptions (const ToolChain & ToolChain, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const InputInfo & Output, const InputInfo & Input, bool IsThinLTO)
Referenced by clang::driver::tools::ananas::Linker::ConstructJob(), clang::driver::tools::cloudabi::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), and clang::driver::tools::gnutools::Linker::ConstructJob().
addMachineOutlinerArgs()
void clang::driver::tools::addMachineOutlinerArgs (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const llvm::Triple & Triple, bool IsLTO)
Definition at line 2035 of file CommonArgs.cpp.
References clang::driver::Driver::Diag().
Referenced by clang::driver::tools::Clang::ConstructJob().
addMultilibFlag()
void clang::driver::tools::addMultilibFlag (bool Enabled, const char *const Flag, Multilib::flags_list & Flags)
Flag must be a flag accepted by the driver with its leading '-' removed,
Definition at line 1625 of file CommonArgs.cpp.
Referenced by findAndroidArmMultilibs(), findBiarchMultilibs(), findCSKYMultilibs(), findMSP430Multilibs(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), findRISCVMultilibs(), and clang::driver::toolchains::Fuchsia::Fuchsia().
addOpenMPDeviceRTL()
void clang::driver::tools::addOpenMPDeviceRTL (const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, StringRef BitcodeSuffix, const llvm::Triple & Triple)
Definition at line 2068 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), and clang::driver::Driver::Dir.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::addClangTargetOptions(), and clang::driver::toolchains::CudaToolChain::addClangTargetOptions().
addOpenMPRuntime()
bool clang::driver::tools::addOpenMPRuntime (llvm::opt::ArgStringList & CmdArgs, const ToolChain & TC, const llvm::opt::ArgList & Args, bool ForceStaticHostRuntime = false, bool IsOffloadingHost = false, bool GompNeedsRT = false)
Returns true, if an OpenMP runtime has been added.
Referenced by clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
addOpenMPRuntimeLibraryPath()
void clang::driver::tools::addOpenMPRuntimeLibraryPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
addOpenMPRuntimeSpecificRPath()
void clang::driver::tools::addOpenMPRuntimeSpecificRPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
addPathIfExists()
void clang::driver::tools::addPathIfExists (const Driver & D, const Twine & Path, ToolChain::path_list & Paths)
Definition at line 123 of file CommonArgs.cpp.
References clang::driver::Driver::getVFS().
Referenced by addMultilibsFilePaths(), addMultilibsFilePaths(), clang::driver::toolchains::MSP430ToolChain::MSP430ToolChain(), and clang::driver::toolchains::Solaris::Solaris().
AddRunTimeLibs()
void clang::driver::tools::AddRunTimeLibs (const ToolChain & TC, const Driver & D, llvm::opt::ArgStringList & CmdArgs, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), and clang::driver::tools::wasm::Linker::ConstructJob().
addSanitizerRuntimes()
bool clang::driver::tools::addSanitizerRuntimes (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::Myriad::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
AddStaticDeviceLibs()
void clang::driver::tools::AddStaticDeviceLibs (Compilation * C, const Tool * T, const JobAction * JA, const InputInfoList * Inputs, const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Definition at line 1922 of file CommonArgs.cpp.
References clang::C, clang::driver::Driver::Dir, GetSDLFromOffloadArchive(), and SDLSearch().
Referenced by AddStaticDeviceLibsLinking(), and AddStaticDeviceLibsPostLinking().
AddStaticDeviceLibsLinking()
void clang::driver::tools::AddStaticDeviceLibsLinking (Compilation & C, const Tool & T, const JobAction & JA, const InputInfoList & Inputs, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Definition at line 1875 of file CommonArgs.cpp.
References AddStaticDeviceLibs(), and clang::C.
Referenced by clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob().
AddStaticDeviceLibsPostLinking()
void clang::driver::tools::AddStaticDeviceLibsPostLinking (const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Definition at line 1888 of file CommonArgs.cpp.
References AddStaticDeviceLibs().
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions().
AddTargetFeature()
void clang::driver::tools::AddTargetFeature (const llvm::opt::ArgList & Args, std::vector< StringRef > & Features, llvm::opt::OptSpecifier OnOpt, llvm::opt::OptSpecifier OffOpt, StringRef FeatureName)
addX86AlignBranchArgs()
void clang::driver::tools::addX86AlignBranchArgs (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, bool IsLTO)
Referenced by clang::driver::tools::ClangAs::AddX86TargetArgs().
addXRayRuntime()
bool clang::driver::tools::addXRayRuntime (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
areOptimizationsEnabled()
bool clang::driver::tools::areOptimizationsEnabled (const llvm::opt::ArgList & Args)
Referenced by useFramePointerForTargetByDefault().
checkAMDGPUCodeObjectVersion()
void clang::driver::tools::checkAMDGPUCodeObjectVersion (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 1986 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), and getAMDGPUCodeObjectArgument().
claimNoWarnArgs()
void clang::driver::tools::claimNoWarnArgs (const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::ananas::Assembler::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::CrossWindows::Assembler::ConstructJob(), clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::MinGW::Assembler::ConstructJob(), clang::driver::tools::minix::Assembler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), clang::driver::tools::solaris::Assembler::ConstructJob(), clang::driver::tools::SPIRV::Translator::ConstructJob(), and clang::driver::tools::XCore::Assembler::ConstructJob().
getAMDGPUCodeObjectVersion()
unsigned clang::driver::tools::getAMDGPUCodeObjectVersion (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 2013 of file CommonArgs.cpp.
References getAMDGPUCodeObjectArgument().
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames(), and handleAMDGPUCodeObjectVersionOptions().
getAsNeededOption()
const char * clang::driver::tools::getAsNeededOption (const ToolChain & TC, bool as_needed)
Definition at line 811 of file CommonArgs.cpp.
References clang::driver::ToolChain::getTriple().
Referenced by AddUnwindLibrary(), and clang::driver::tools::solaris::Linker::ConstructJob().
getCPUName()
std::string clang::driver::tools::getCPUName (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & T, bool FromAs = false)
Referenced by clang::driver::toolchains::AVRToolChain::AVRToolChain(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
getDebugFissionKind()
DwarfFissionKind clang::driver::tools::getDebugFissionKind (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::Arg *& Arg)
Referenced by clang::driver::tools::ClangAs::ConstructJob(), and renderDebugOptions().
getLastProfileSampleUseArg()
llvm::opt::Arg * clang::driver::tools::getLastProfileSampleUseArg (const llvm::opt::ArgList & Args)
Referenced by addPGOAndCoverageFlags(), and clang::driver::tools::Clang::ConstructJob().
getLastProfileUseArg()
llvm::opt::Arg * clang::driver::tools::getLastProfileUseArg (const llvm::opt::ArgList & Args)
Referenced by addPGOAndCoverageFlags(), and renderRemarksOptions().
getLTOParallelism()
llvm::StringRef clang::driver::tools::getLTOParallelism (const llvm::opt::ArgList & Args, const Driver & D)
Referenced by clang::driver::tools::darwin::Linker::ConstructJob().
GetSDLFromOffloadArchive()
bool clang::driver::tools::GetSDLFromOffloadArchive (Compilation & C, const Driver & D, const Tool & T, const JobAction & JA, const InputInfoList & Inputs, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, SmallVector< std::string, 8 > LibraryPaths, StringRef Lib, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Search if a user provided archive file lib<libname>.a exists in any of the library paths.
If so, add a new command to clang-offload-bundler to unbundle this archive and create a temporary device specific archive. Name of this SDL is passed to the llvm-link (for amdgcn) or to the clang-nvlink-wrapper (for nvptx) commands by the driver.
Definition at line 1781 of file CommonArgs.cpp.
References clang::driver::ResponseFileSupport::AtFileCurCP(), clang::C, clang::driver::Action::getOffloadingDeviceKind(), clang::driver::Action::GetOffloadKindName(), clang::driver::Driver::getTargetTriple(), clang::driver::Driver::GetTemporaryPath(), and clang::Target.
Referenced by AddStaticDeviceLibs().
getStatsFileName()
SmallString< 128 > clang::driver::tools::getStatsFileName (const llvm::opt::ArgList & Args, const InputInfo & Output, const InputInfo & Input, const Driver & D)
Handles the -save-stats option and returns the filename to save statistics to.
Definition at line 1601 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), clang::driver::InputInfo::getBaseInput(), clang::driver::InputInfo::getFilename(), and clang::driver::InputInfo::isFilename().
Referenced by clang::driver::tools::Clang::ConstructJob(), and clang::driver::tools::darwin::Linker::ConstructJob().
handleTargetFeaturesGroup()
void clang::driver::tools::handleTargetFeaturesGroup (const llvm::opt::ArgList & Args, std::vector< StringRef > & Features, llvm::opt::OptSpecifier Group)
Iterate Args and convert -mxxx to +xxx and -mno-xxx to -xxx and append it to Features.
Note: Since Features may contain default values before calling this function, or may be appended with entries to override arguments, entries in Features are not unique.
Referenced by clang::driver::tools::amdgpu::getAMDGPUTargetFeatures(), and getWebAssemblyTargetFeatures().
haveAMDGPUCodeObjectVersionArgument()
bool clang::driver::tools::haveAMDGPUCodeObjectVersionArgument (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 2030 of file CommonArgs.cpp.
References getAMDGPUCodeObjectArgument().
Referenced by handleAMDGPUCodeObjectVersionOptions().
isObjCAutoRefCount()
bool clang::driver::tools::isObjCAutoRefCount (const llvm::opt::ArgList & Args)
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), isObjCRuntimeLinked(), and RenderObjCOptions().
isUseSeparateSections()
bool clang::driver::tools::isUseSeparateSections (const llvm::Triple & Triple)
Definition at line 479 of file CommonArgs.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob().
linkSanitizerRuntimeDeps()
void clang::driver::tools::linkSanitizerRuntimeDeps (const ToolChain & TC, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::Myriad::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
linkXRayRuntimeDeps()
void clang::driver::tools::linkXRayRuntimeDeps (const ToolChain & TC, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
ParseDebugDefaultVersion()
unsigned clang::driver::tools::ParseDebugDefaultVersion (const ToolChain & TC, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::ClangAs::ConstructJob(), and renderDebugOptions().
ParseFunctionAlignment()
unsigned clang::driver::tools::ParseFunctionAlignment (const ToolChain & TC, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::Clang::ConstructJob().
ParsePICArgs()
std::tuple< llvm::Reloc::Model, unsigned, bool > clang::driver::tools::ParsePICArgs (const ToolChain & ToolChain, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), and clang::driver::tools::gnutools::Assembler::ConstructJob().
SDLSearch()
bool clang::driver::tools::SDLSearch (const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, SmallVector< std::string, 8 > LibraryPaths, std::string Lib, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
SDLSearch: Search for Static Device Library The search for SDL bitcode files is consistent with how static host libraries are discovered.
That is, the -l option triggers a search for files in a set of directories called the LINKPATH. The host library search procedure looks for a specific filename in the LINKPATH. The filename for a host library is lib<libname>.a or lib<libname>.so. For SDLs, there is an ordered-set of filenames that are searched. We call this ordered-set of filenames as SEARCH-ORDER. Since an SDL can either be device-type specific, architecture specific, or generic across all architectures, a naming convention and search order is used where the file name embeds the architecture name <arch-name> (nvptx or amdgcn) and the GPU device type <device-name> such as sm_30 and gfx906. <device-name> is absent in case of device-independent SDLs. To reduce congestion in host library directories, the search first looks for files in the “libdevice” subdirectory. SDLs that are bc files begin with the prefix “lib”.
Machine-code SDLs can also be managed as an archive (*.a file). The convention has been to use the prefix “lib”. To avoid confusion with host archive libraries, we use prefix "libbc-" for the bitcode SDL archives.
Definition at line 1700 of file CommonArgs.cpp.
Referenced by AddStaticDeviceLibs().
SplitDebugInfo()
void clang::driver::tools::SplitDebugInfo (const ToolChain & TC, Compilation & C, const Tool & T, const JobAction & JA, const llvm::opt::ArgList & Args, const InputInfo & Output, const char * OutFile)
Referenced by clang::driver::tools::gnutools::Assembler::ConstructJob(), and clang::driver::tools::MinGW::Assembler::ConstructJob().
SplitDebugName()
const char * clang::driver::tools::SplitDebugName (const JobAction & JA, const llvm::opt::ArgList & Args, const InputInfo & Input, const InputInfo & Output)
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), and clang::driver::tools::MinGW::Assembler::ConstructJob().
unifyTargetFeatures()
SmallVector< StringRef > clang::driver::tools::unifyTargetFeatures (ArrayRef< StringRef > Features)
If there are multiple +xxx or -xxx features, keep the last one.
Definition at line 148 of file CommonArgs.cpp.
Referenced by getTargetFeatures().