clang: clang::driver::tools::riscv Namespace Reference
clang::driver::tools::riscv Namespace Reference
Functions
void getRISCVTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< llvm::StringRef > &Features)
StringRef getRISCVABI (const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
StringRef getRISCVArch (const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
Function Documentation
getRISCVABI()
StringRef clang::driver::tools::riscv::getRISCVABI (const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by clang::driver::tools::ClangAs::AddRISCVTargetArgs(), clang::driver::tools::gnutools::Assembler::ConstructJob(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), findRISCVMultilibs(), clang::driver::toolchains::Linux::getDynamicLinker(), and clang::driver::toolchains::Linux::Linux().
getRISCVArch()
StringRef clang::driver::tools::riscv::getRISCVArch (const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Definition at line 229 of file RISCV.cpp.
Referenced by clang::driver::tools::gnutools::Assembler::ConstructJob(), findRISCVBareMetalMultilibs(), and findRISCVMultilibs().
getRISCVTargetFeatures()
void clang::driver::tools::riscv::getRISCVTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< llvm::StringRef > & Features)
Referenced by getTargetFeatures().