clang: lib/Sema/ParsedAttr.cpp File Reference
ParsedAttr.cpp File Reference
#include "clang/Sema/ParsedAttr.h"
#include "clang/AST/ASTContext.h"
#include "clang/Basic/AttrSubjectMatchRules.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ManagedStatic.h"
#include <cassert>
#include <cstddef>
#include <utility>
#include "clang/Sema/AttrParsedAttrImpl.inc"
Functions
static size_t getFreeListIndexForSize (size_t size)
static unsigned getNumAttributeArgs (const ParsedAttr &AL)
template<typename Compare >
static bool checkAttributeNumArgsImpl (Sema &S, const ParsedAttr &AL, unsigned Num, unsigned Diag, Compare Comp)
Function Documentation
checkAttributeNumArgsImpl()
template<typename Compare > static bool checkAttributeNumArgsImpl (Sema & S, const ParsedAttr & AL, unsigned Num, unsigned Diag, Compare Comp) static
Definition at line 276 of file ParsedAttr.cpp.
References clang::Sema::Diag(), Diag(), clang::AttributeCommonInfo::getLoc(), and getNumAttributeArgs().
Referenced by clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), and clang::ParsedAttr::checkExactlyNumArgs().
getFreeListIndexForSize()
static size_t getFreeListIndexForSize (size_t size) static
Definition at line 60 of file ParsedAttr.cpp.
getNumAttributeArgs()
static unsigned getNumAttributeArgs (const ParsedAttr & AL) static
Definition at line 270 of file ParsedAttr.cpp.
References clang::ParsedAttr::getNumArgs(), and clang::ParsedAttr::hasParsedType().
Referenced by checkAttributeNumArgsImpl(), and handleCPUSpecificAttr().