clang: lib/Tooling/Transformer/RangeSelector.cpp File Reference
RangeSelector.cpp File Reference
#include "clang/Tooling/Transformer/RangeSelector.h"
#include "clang/AST/Expr.h"
#include "clang/AST/TypeLoc.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Lex/Lexer.h"
#include "clang/Tooling/Transformer/SourceCode.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include <string>
#include <utility>
#include <vector>
Typedefs
using MatchResult = MatchFinder::MatchResult
Functions
static Error invalidArgumentError (Twine Message)
static Error typeError (StringRef ID, const ASTNodeKind &Kind)
static Error typeError (StringRef ID, const ASTNodeKind &Kind, Twine ExpectedType)
static Error missingPropertyError (StringRef ID, Twine Description, StringRef Property)
static Expected< DynTypedNode > getNode (const ast_matchers::BoundNodes &Nodes, StringRef ID)
static SourceLocation findPreviousTokenStart (SourceLocation Start, const SourceManager &SM, const LangOptions &LangOpts)
static SourceLocation findPreviousTokenKind (SourceLocation Start, const SourceManager &SM, const LangOptions &LangOpts, tok::TokenKind TK)
static SourceLocation findOpenParen (const CallExpr &E, const SourceManager &SM, const LangOptions &LangOpts)
Typedef Documentation
MatchResult
typedef MatchFinder::MatchResult MatchResult = MatchFinder::MatchResult
Definition at line 30 of file RangeSelector.cpp.
Function Documentation
findOpenParen()
static SourceLocation findOpenParen (const CallExpr & E, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 99 of file RangeSelector.cpp.
References findPreviousTokenKind(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::CallExpr::getNumArgs(), clang::CallExpr::getRParenLoc(), and SM.
findPreviousTokenKind()
static SourceLocation findPreviousTokenKind (SourceLocation Start, const SourceManager & SM, const LangOptions & LangOpts, tok::TokenKind TK) static
Definition at line 79 of file RangeSelector.cpp.
References findPreviousTokenStart(), clang::Lexer::getRawToken(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), and SM.
Referenced by findOpenParen().
findPreviousTokenStart()
static SourceLocation findPreviousTokenStart (SourceLocation Start, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 64 of file RangeSelector.cpp.
References clang::Lexer::GetBeginningOfToken(), clang::SourceLocation::getLocWithOffset(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), and SM.
Referenced by findPreviousTokenKind().
getNode()
static Expected< DynTypedNode > getNode (const ast_matchers::BoundNodes & Nodes, StringRef ID) static
Definition at line 54 of file RangeSelector.cpp.
References invalidArgumentError(), and Nodes.
Referenced by clang::transformer::member(), clang::transformer::name(), clang::transformer::node(), and clang::transformer::statement().
invalidArgumentError()
static Error invalidArgumentError (Twine Message) static
Definition at line 32 of file RangeSelector.cpp.
Referenced by clang::transformer::after(), clang::transformer::enclose(), getNode(), missingPropertyError(), typeError(), and typeError().
missingPropertyError()
static Error missingPropertyError (StringRef ID, Twine Description, StringRef Property) static
Definition at line 48 of file RangeSelector.cpp.
References invalidArgumentError().
Referenced by clang::transformer::name().
typeError() [1/2]
static Error typeError (StringRef ID, const ASTNodeKind & Kind) static
Definition at line 36 of file RangeSelector.cpp.
References invalidArgumentError().
Referenced by clang::transformer::member(), and clang::transformer::name().
typeError() [2/2]
static Error typeError (StringRef ID, const ASTNodeKind & Kind, Twine ExpectedType) static
Definition at line 41 of file RangeSelector.cpp.
References invalidArgumentError().