clang: lib/AST/RecordLayoutBuilder.cpp File Reference
RecordLayoutBuilder.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/VTableBuilder.h"
#include "clang/AST/RecordLayout.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
Functions
static uint64_t roundUpSizeToCharAlignment (uint64_t Size, const ASTContext &Context)
static bool isAIXLayout (const ASTContext &Context)
static unsigned getPaddingDiagFromTagKind (TagTypeKind Tag)
Get diagnostic select index for tag kind for field padding diagnostic message.
static const CXXMethodDecl * computeKeyFunction (ASTContext &Context, const CXXRecordDecl *RD)
static bool mustSkipTailPadding (TargetCXXABI ABI, const CXXRecordDecl *RD)
Does the target C++ ABI require us to skip over the tail-padding of the given class (considering it as a base class) when allocating objects?
static bool isMsLayout (const ASTContext &Context)
static bool recordUsesEBO (const RecordDecl *RD)
static bool RequiresVtordisp (const llvm::SmallPtrSetImpl< const CXXRecordDecl * > &BasesWithOverriddenMethods, const CXXRecordDecl *RD)
static uint64_t getFieldOffset (const ASTContext &C, const FieldDecl *FD)
static void PrintOffset (raw_ostream &OS, CharUnits Offset, unsigned IndentLevel)
static void PrintBitFieldOffset (raw_ostream &OS, CharUnits Offset, unsigned Begin, unsigned Width, unsigned IndentLevel)
static void PrintIndentNoOffset (raw_ostream &OS, unsigned IndentLevel)
static void DumpRecordLayout (raw_ostream &OS, const RecordDecl *RD, const ASTContext &C, CharUnits Offset, unsigned IndentLevel, const char *Description, bool PrintSizeInfo, bool IncludeVirtualBases)
Function Documentation
computeKeyFunction()
static const CXXMethodDecl * computeKeyFunction (ASTContext & Context, const CXXRecordDecl * RD) static
Definition at line 2301 of file RecordLayoutBuilder.cpp.
References clang::TargetCXXABI::canKeyFunctionBeInline(), clang::TargetInfo::getCXXABI(), clang::ASTContext::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::CXXRecordDecl::getTemplateSpecializationKind(), clang::Decl::hasAttr(), clang::TargetInfo::hasPS4DLLImportExport(), clang::NamedDecl::isExternallyVisible(), clang::FunctionDecl::isInlineSpecified(), clang::CXXRecordDecl::isPolymorphic(), clang::CXXRecordDecl::methods(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, and clang::TSK_ImplicitInstantiation.
Referenced by clang::ASTContext::getCurrentKeyFunction().
DumpRecordLayout()
static void DumpRecordLayout (raw_ostream & OS, const RecordDecl * RD, const ASTContext & C, CharUnits Offset, unsigned IndentLevel, const char * Description, bool PrintSizeInfo, bool IncludeVirtualBases) static
Definition at line 3534 of file RecordLayoutBuilder.cpp.
References Begin, clang::C, DumpRecordLayout(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::CharUnits::fromQuantity(), clang::ASTRecordLayout::getAlignment(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getDataSize(), clang::RecordType::getDecl(), clang::ASTRecordLayout::getFieldOffset(), clang::ASTRecordLayout::getNonVirtualAlignment(), clang::ASTRecordLayout::getNonVirtualSize(), clang::ASTRecordLayout::getPreferredAlignment(), clang::ASTRecordLayout::getPreferredNVAlignment(), clang::ASTRecordLayout::getPrimaryBase(), clang::CharUnits::getQuantity(), clang::ASTRecordLayout::getSize(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::ASTRecordLayout::getVBaseOffsetsMap(), clang::ASTRecordLayout::getVBPtrOffset(), clang::ASTRecordLayout::hasOwnVBPtr(), clang::ASTRecordLayout::hasOwnVFPtr(), IndentLevel, isMsLayout(), Offset, PrintBitFieldOffset(), PrintIndentNoOffset(), and PrintOffset().
Referenced by clang::ASTContext::DumpRecordLayout(), DumpRecordLayout(), and clang::ASTContext::getASTRecordLayout().
getFieldOffset()
static uint64_t getFieldOffset (const ASTContext & C, const FieldDecl * FD) static
Definition at line 3403 of file RecordLayoutBuilder.cpp.
References clang::C, clang::FieldDecl::getFieldIndex(), clang::ASTRecordLayout::getFieldOffset(), and clang::FieldDecl::getParent().
Referenced by clang::ASTContext::getFieldOffset().
getPaddingDiagFromTagKind()
static unsigned getPaddingDiagFromTagKind (TagTypeKind Tag) static
Get diagnostic select index for tag kind for field padding diagnostic message.
WARNING: Indexes apply to particular diagnostics only!
Returns
diagnostic select index.
Definition at line 2250 of file RecordLayoutBuilder.cpp.
References clang::TTK_Class, clang::TTK_Interface, and clang::TTK_Struct.
isAIXLayout()
static bool isAIXLayout (const ASTContext & Context) static
Definition at line 1533 of file RecordLayoutBuilder.cpp.
References clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
isMsLayout()
static bool isMsLayout (const ASTContext & Context) static
Definition at line 2429 of file RecordLayoutBuilder.cpp.
References clang::TargetInfo::getCXXABI(), clang::ASTContext::getTargetInfo(), and clang::TargetCXXABI::isMicrosoft().
Referenced by clang::ASTContext::DumpRecordLayout(), DumpRecordLayout(), and clang::ASTContext::getASTRecordLayout().
mustSkipTailPadding()
static bool mustSkipTailPadding (TargetCXXABI ABI, const CXXRecordDecl * RD) static
Does the target C++ ABI require us to skip over the tail-padding of the given class (considering it as a base class) when allocating objects?
Definition at line 2390 of file RecordLayoutBuilder.cpp.
References clang::TargetCXXABI::AlwaysUseTailPadding, clang::TargetCXXABI::getTailPaddingUseRules(), clang::CXXRecordDecl::isCXX11StandardLayout(), clang::CXXRecordDecl::isPOD(), clang::CXXRecordDecl::isTrivial(), clang::TargetCXXABI::UseTailPaddingUnlessPOD03, and clang::TargetCXXABI::UseTailPaddingUnlessPOD11.
Referenced by clang::ASTContext::getASTRecordLayout().
PrintBitFieldOffset()
static void PrintBitFieldOffset (raw_ostream & OS, CharUnits Offset, unsigned Begin, unsigned Width, unsigned IndentLevel) static
Definition at line 3511 of file RecordLayoutBuilder.cpp.
References Begin, IndentLevel, and Offset.
Referenced by DumpRecordLayout().
PrintIndentNoOffset()
static void PrintIndentNoOffset (raw_ostream & OS, unsigned IndentLevel) static
Definition at line 3529 of file RecordLayoutBuilder.cpp.
References IndentLevel.
Referenced by DumpRecordLayout().
PrintOffset()
static void PrintOffset (raw_ostream & OS, CharUnits Offset, unsigned IndentLevel) static
Definition at line 3505 of file RecordLayoutBuilder.cpp.
References IndentLevel, and Offset.
Referenced by DumpRecordLayout().
recordUsesEBO()
static bool recordUsesEBO (const RecordDecl * RD) static
Definition at line 2876 of file RecordLayoutBuilder.cpp.
References clang::Decl::getAttr(), clang::Decl::hasAttr(), and clang::LangOptions::MSVC2015.
RequiresVtordisp()
static bool RequiresVtordisp (const llvm::SmallPtrSetImpl< const CXXRecordDecl * > & BasesWithOverriddenMethods, const CXXRecordDecl * RD) static
Definition at line 3180 of file RecordLayoutBuilder.cpp.
References clang::CXXRecordDecl::bases(), and RequiresVtordisp().
Referenced by RequiresVtordisp().
roundUpSizeToCharAlignment()
static uint64_t roundUpSizeToCharAlignment (uint64_t Size, const ASTContext & Context) static
Definition at line 1461 of file RecordLayoutBuilder.cpp.
References clang::TargetInfo::getCharAlign(), and clang::ASTContext::getTargetInfo().