clang: lib/StaticAnalyzer/Checkers/ReturnUndefChecker.cpp File Reference
ReturnUndefChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
Functions
static void emitBug (CheckerContext &C, BuiltinBug &BT, const Expr *RetE, const Expr *TrackingE=nullptr)
Function Documentation
emitBug()
static void emitBug (CheckerContext & C, BuiltinBug & BT, const Expr * RetE, const Expr * TrackingE = nullptr) static
Definition at line 80 of file ReturnUndefChecker.cpp.
References clang::C, clang::ento::BuiltinBug::getDescription(), clang::Stmt::getSourceRange(), N, and clang::ento::bugreporter::trackExpressionValue().