clang: lib/StaticAnalyzer/Core/SarifDiagnostics.cpp File Reference
SarifDiagnostics.cpp File Reference
#include "clang/Analysis/MacroExpansionContext.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/Version.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/StaticAnalyzer/Core/PathDiagnosticConsumers.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/Path.h"
#include "clang/StaticAnalyzer/Checkers/Checkers.inc"
Macros
#define GET_CHECKERS
#define CHECKER(FULLNAME, CLASS, HELPTEXT, DOC_URI, IS_HIDDEN)
#define GET_CHECKERS
#define CHECKER(FULLNAME, CLASS, HELPTEXT, DOC_URI, IS_HIDDEN)
Enumerations
enum class Importance { Important , Essential , Unimportant }
Functions
static StringRef getFileName (const FileEntry &FE)
static std::string percentEncodeURICharacter (char C)
static std::string fileNameToURI (StringRef Filename)
static json::Object createArtifactLocation (const FileEntry &FE)
static json::Object createArtifact (const FileEntry &FE)
static json::Object createArtifactLocation (const FileEntry &FE, json::Array &Artifacts)
static unsigned int adjustColumnPos (const SourceManager &SM, SourceLocation Loc, unsigned int TokenLen=0)
static json::Object createTextRegion (const LangOptions &LO, SourceRange R, const SourceManager &SM)
static json::Object createPhysicalLocation (const LangOptions &LO, SourceRange R, const FileEntry &FE, const SourceManager &SMgr, json::Array &Artifacts)
static StringRef importanceToStr (Importance I)
static json::Object createThreadFlowLocation (json::Object &&Location, Importance I)
static json::Object createMessage (StringRef Text)
static json::Object createLocation (json::Object &&PhysicalLocation, StringRef Message="")
static Importance calculateImportance (const PathDiagnosticPiece &Piece)
static json::Object createThreadFlow (const LangOptions &LO, const PathPieces &Pieces, json::Array &Artifacts)
static json::Object createCodeFlow (const LangOptions &LO, const PathPieces &Pieces, json::Array &Artifacts)
static json::Object createResult (const LangOptions &LO, const PathDiagnostic &Diag, json::Array &Artifacts, const StringMap< unsigned > &RuleMapping)
static StringRef getRuleDescription (StringRef CheckName)
static StringRef getRuleHelpURIStr (StringRef CheckName)
static json::Object createRule (const PathDiagnostic &Diag)
static json::Array createRules (std::vector< const PathDiagnostic * > &Diags, StringMap< unsigned > &RuleMapping)
static json::Object createTool (std::vector< const PathDiagnostic * > &Diags, StringMap< unsigned > &RuleMapping)
static json::Object createRun (const LangOptions &LO, std::vector< const PathDiagnostic * > &Diags)
Macro Definition Documentation
CHECKER [1/2]
#define CHECKER (FULLNAME, CLASS, HELPTEXT, DOC_URI, IS_HIDDEN)
Value:
  .Case(FULLNAME, HELPTEXT)
CHECKER [2/2]
#define CHECKER (FULLNAME, CLASS, HELPTEXT, DOC_URI, IS_HIDDEN)
Value:
  .Case(FULLNAME, DOC_URI)
GET_CHECKERS [1/2]
#define GET_CHECKERS
GET_CHECKERS [2/2]
#define GET_CHECKERS
Enumeration Type Documentation
Importance
enum class Importance strong
Enumerator
Important
Essential
Unimportant
Definition at line 207 of file SarifDiagnostics.cpp.
Function Documentation
adjustColumnPos()
static unsigned int adjustColumnPos (const SourceManager & SM, SourceLocation Loc, unsigned int TokenLen = 0) static
Definition at line 156 of file SarifDiagnostics.cpp.
References Ret(), and SM.
Referenced by createTextRegion().
calculateImportance()
static Importance calculateImportance (const PathDiagnosticPiece & Piece) static
Definition at line 239 of file SarifDiagnostics.cpp.
References clang::ento::PathDiagnosticPiece::Call, clang::ento::PathDiagnosticPiece::ControlFlow, Essential, clang::ento::PathDiagnosticPiece::Event, clang::ento::PathDiagnosticPiece::getKind(), clang::ento::PathDiagnosticPiece::getTagStr(), Important, clang::ento::PathDiagnosticPiece::Macro, clang::ento::PathDiagnosticPiece::Note, clang::ento::PathDiagnosticPiece::PopUp, and Unimportant.
Referenced by createThreadFlow().
createArtifact()
static json::Object createArtifact (const FileEntry & FE) static
Definition at line 124 of file SarifDiagnostics.cpp.
References createArtifactLocation(), and clang::FileEntry::getSize().
Referenced by createArtifactLocation().
createArtifactLocation() [1/2]
static json::Object createArtifactLocation (const FileEntry & FE) static
Definition at line 120 of file SarifDiagnostics.cpp.
References fileNameToURI(), and getFileName().
Referenced by createArtifact(), and createPhysicalLocation().
createArtifactLocation() [2/2]
static json::Object createArtifactLocation (const FileEntry & FE, json::Array & Artifacts) static
Definition at line 131 of file SarifDiagnostics.cpp.
References createArtifact(), clang::File, fileNameToURI(), and getFileName().
createCodeFlow()
static json::Object createCodeFlow (const LangOptions & LO, const PathPieces & Pieces, json::Array & Artifacts) static
Definition at line 274 of file SarifDiagnostics.cpp.
References createThreadFlow().
Referenced by createResult().
createLocation()
static json::Object createLocation (json::Object && PhysicalLocation, StringRef Message = "") static
Definition at line 231 of file SarifDiagnostics.cpp.
References createMessage(), and Ret().
Referenced by createResult(), and createThreadFlow().
createMessage()
static json::Object createMessage (StringRef Text) static
Definition at line 227 of file SarifDiagnostics.cpp.
References Text.
Referenced by createLocation(), createResult(), and createRule().
createPhysicalLocation()
static json::Object createPhysicalLocation (const LangOptions & LO, SourceRange R, const FileEntry & FE, const SourceManager & SMgr, json::Array & Artifacts) static
Definition at line 198 of file SarifDiagnostics.cpp.
References createArtifactLocation(), and createTextRegion().
Referenced by createResult(), and createThreadFlow().
createResult()
static json::Object createResult (const LangOptions & LO, const PathDiagnostic & Diag, json::Array & Artifacts, const StringMap< unsigned > & RuleMapping) static
Definition at line 281 of file SarifDiagnostics.cpp.
References createCodeFlow(), createLocation(), createMessage(), createPhysicalLocation(), and Diag().
Referenced by createRun().
createRule()
static json::Object createRule (const PathDiagnostic & Diag) static
Definition at line 325 of file SarifDiagnostics.cpp.
References createMessage(), Diag(), getRuleDescription(), getRuleHelpURIStr(), and Ret().
Referenced by createRules().
createRules()
static json::Array createRules (std::vector< const PathDiagnostic * > & Diags, StringMap< unsigned > & RuleMapping) static
Definition at line 339 of file SarifDiagnostics.cpp.
References createRule(), and P.
Referenced by createTool().
createRun()
static json::Object createRun (const LangOptions & LO, std::vector< const PathDiagnostic * > & Diags) static
Definition at line 366 of file SarifDiagnostics.cpp.
References createResult(), and createTool().
createTextRegion()
static json::Object createTextRegion (const LangOptions & LO, SourceRange R, const SourceManager & SM) static
Definition at line 181 of file SarifDiagnostics.cpp.
References adjustColumnPos(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::Lexer::MeasureTokenLength(), and SM.
Referenced by createPhysicalLocation().
createThreadFlow()
static json::Object createThreadFlow (const LangOptions & LO, const PathPieces & Pieces, json::Array & Artifacts) static
Definition at line 256 of file SarifDiagnostics.cpp.
References calculateImportance(), createLocation(), createPhysicalLocation(), createThreadFlowLocation(), and P.
Referenced by createCodeFlow().
createThreadFlowLocation()
static json::Object createThreadFlowLocation (json::Object && Location, Importance I) static
Definition at line 221 of file SarifDiagnostics.cpp.
References importanceToStr().
Referenced by createThreadFlow().
createTool()
static json::Object createTool (std::vector< const PathDiagnostic * > & Diags, StringMap< unsigned > & RuleMapping) static
Definition at line 356 of file SarifDiagnostics.cpp.
References createRules(), and clang::getClangFullVersion().
Referenced by createRun().
fileNameToURI()
static std::string fileNameToURI (StringRef Filename) static
Definition at line 83 of file SarifDiagnostics.cpp.
References clang::C, Filename, percentEncodeURICharacter(), and Ret().
Referenced by createArtifactLocation(), and createArtifactLocation().
getFileName()
static StringRef getFileName (const FileEntry & FE) static
Definition at line 64 of file SarifDiagnostics.cpp.
References Filename, clang::FileEntry::getName(), and clang::FileEntry::tryGetRealPathName().
Referenced by createArtifactLocation(), and createArtifactLocation().
getRuleDescription()
static StringRef getRuleDescription (StringRef CheckName) static
Definition at line 303 of file SarifDiagnostics.cpp.
Referenced by createRule().
getRuleHelpURIStr()
static StringRef getRuleHelpURIStr (StringRef CheckName) static
Definition at line 314 of file SarifDiagnostics.cpp.
Referenced by createRule().
importanceToStr()
static StringRef importanceToStr (Importance I) static
Definition at line 209 of file SarifDiagnostics.cpp.
References Essential, Important, and Unimportant.
Referenced by createThreadFlowLocation().
percentEncodeURICharacter()
static std::string percentEncodeURICharacter (char C) static
Definition at line 71 of file SarifDiagnostics.cpp.
References clang::C.
Referenced by fileNameToURI().