clang: lib/Sema/ScopeInfo.cpp File Reference
ScopeInfo.cpp File Reference
#include "clang/Sema/ScopeInfo.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
Functions
static const NamedDecl * getBestPropertyDecl (const ObjCPropertyRefExpr *PropE)
Function Documentation
getBestPropertyDecl()
static const NamedDecl * getBestPropertyDecl (const ObjCPropertyRefExpr * PropE) static
Definition at line 61 of file ScopeInfo.cpp.
References clang::ObjCPropertyRefExpr::getExplicitProperty(), clang::ObjCPropertyRefExpr::getImplicitPropertyGetter(), and clang::ObjCPropertyRefExpr::isExplicitProperty().