clang: lib/Sema/SemaModule.cpp File Reference
SemaModule.cpp File Reference
#include "clang/AST/ASTConsumer.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/SemaInternal.h"
Functions
static void checkModuleImportContext (Sema &S, Module *M, SourceLocation ImportLoc, DeclContext *DC, bool FromInclude=false)
static std::string stringFromPath (ModuleIdPath Path)
static const ExportDecl * getEnclosingExportDecl (const Decl *D)
Determine whether D is lexically within an export-declaration.
static bool checkExportedDeclContext (Sema &S, DeclContext *DC, SourceLocation BlockStart)
Check that it's valid to export all the declarations in DC.
static llvm::Optional< UnnamedDeclKind > getUnnamedDeclKind (Decl *D)
unsigned getUnnamedDeclDiag (UnnamedDeclKind UDK, bool InBlock)
static void diagExportedUnnamedDecl (Sema &S, UnnamedDeclKind UDK, Decl *D, SourceLocation BlockStart)
static bool checkExportedDecl (Sema &S, Decl *D, SourceLocation BlockStart)
Check that it's valid to export D.
Function Documentation
checkExportedDecl()
static bool checkExportedDecl (Sema & S, Decl * D, SourceLocation BlockStart) static
Check that it's valid to export D.
Definition at line 838 of file SemaModule.cpp.
References bool, checkExportedDeclContext(), clang::Sema::Diag(), diagExportedUnnamedDecl(), clang::NamedDecl::getFormalLinkage(), clang::NamedDecl::getUnderlyingDecl(), getUnnamedDeclKind(), clang::InternalLinkage, clang::SourceLocation::isValid(), and clang::ModuleLinkage.
Referenced by clang::Sema::ActOnFinishExportDecl(), and checkExportedDeclContext().
checkExportedDeclContext()
static bool checkExportedDeclContext (Sema & S, DeclContext * DC, SourceLocation BlockStart) static
Check that it's valid to export all the declarations in DC.
Definition at line 888 of file SemaModule.cpp.
References checkExportedDecl(), and clang::DeclContext::decls().
Referenced by checkExportedDecl().
checkModuleImportContext()
static void checkModuleImportContext (Sema & S, Module * M, SourceLocation ImportLoc, DeclContext * DC, bool FromInclude = false) static
Definition at line 22 of file SemaModule.cpp.
References clang::Sema::Diag(), clang::Module::getFullModuleName(), clang::DeclContext::getParent(), clang::Module::IsExternC, clang::SourceLocation::isInvalid(), clang::Sema::isModuleVisible(), clang::SourceLocation::isValid(), clang::LinkageSpecDecl::lang_c, and clang::LinkageSpecDecl::lang_cxx.
Referenced by clang::Sema::ActOnModuleBegin(), clang::Sema::ActOnModuleImport(), and clang::Sema::ActOnModuleInclude().
diagExportedUnnamedDecl()
static void diagExportedUnnamedDecl (Sema & S, UnnamedDeclKind UDK, Decl * D, SourceLocation BlockStart) static
Definition at line 829 of file SemaModule.cpp.
References clang::Sema::Diag(), clang::Decl::getLocation(), getUnnamedDeclDiag(), and clang::SourceLocation::isValid().
Referenced by clang::Sema::ActOnFinishExportDecl(), and checkExportedDecl().
getEnclosingExportDecl()
static const ExportDecl * getEnclosingExportDecl (const Decl * D) static
Determine whether D is lexically within an export-declaration.
Definition at line 479 of file SemaModule.cpp.
References clang::Decl::getLexicalDeclContext(), and clang::DeclContext::getLexicalParent().
Referenced by clang::Sema::ActOnModuleImport(), and clang::Sema::ActOnStartExportDecl().
getUnnamedDeclDiag()
unsigned getUnnamedDeclDiag (UnnamedDeclKind UDK, bool InBlock)
Definition at line 802 of file SemaModule.cpp.
Referenced by diagExportedUnnamedDecl().
getUnnamedDeclKind()
static llvm::Optional< UnnamedDeclKind > getUnnamedDeclKind (Decl * D) static
Definition at line 789 of file SemaModule.cpp.
Referenced by checkExportedDecl().
stringFromPath()
static std::string stringFromPath (ModuleIdPath Path) static
Definition at line 61 of file SemaModule.cpp.
Referenced by clang::Sema::ActOnModuleDecl(), and clang::Sema::ActOnModuleImport().