clang: lib/Sema/SemaCodeComplete.cpp File Reference
SemaCodeComplete.cpp File Reference
#include "clang/AST/ASTConcept.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/QualTypeNames.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Type.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/CodeCompleteConsumer.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/Designator.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/ParsedAttr.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <list>
#include <map>
#include <string>
#include <vector>
#include "clang/Basic/OperatorKinds.def"
Classes
class ResultBuilder::ShadowMapEntry::iterator
class ResultBuilder::ShadowMapEntry::iterator::pointer
struct clang::Sema::CodeCompleteExpressionData
Macros
#define OVERLOADED_OPERATOR(Name, Spelling, Token, Unary, Binary, MemberOnly)
#define OVERLOADED_OPERATOR_MULTI(Name, Spelling, Unary, Binary, MemberOnly)
#define OVERLOADED_OPERATOR(Name, Spelling, Token, Unary, Binary, MemberOnly)
#define OBJC_AT_KEYWORD_NAME(NeedAt, Keyword)
Macro that optionally prepends an "@" to the string literal passed in via Keyword, depending on whether NeedAt is true or false.
Typedefs
typedef llvm::SmallPtrSet< IdentifierInfo *, 16 > AddedPropertiesSet
The set of properties that have already been added, referenced by property name.
typedef CodeCompleteConsumer::OverloadCandidate ResultCandidate
typedef llvm::SmallPtrSet< Selector, 16 > VisitedSelectorSet
A set of selectors, which is used to avoid introducing multiple completions with the same selector into the result set.
typedef llvm::DenseMap< Selector, llvm::PointerIntPair< ObjCMethodDecl *, 1, bool > > KnownMethodsMap
Enumerations
enum class OverloadCompare { BothViable , Dominates , Dominated }
enum ObjCMethodKind { MK_Any , MK_ZeroArgSelector , MK_OneArgSelector }
Describes the kind of Objective-C method that we want to find via code completion.
Functions
static QualType getDesignatedType (QualType BaseType, const Designation &Desig)
static QualType getPreferredTypeOfBinaryRHS (Sema &S, Expr *LHS, tok::TokenKind Op)
static QualType getPreferredTypeOfUnaryArg (Sema &S, QualType ContextType, tok::TokenKind Op)
Get preferred type for an argument of an unary expression.
static NestedNameSpecifier * getRequiredQualification (ASTContext &Context, const DeclContext *CurContext, const DeclContext *TargetContext)
Compute the qualification required to get from the current context (CurContext) to the target context (TargetContext).
static bool shouldIgnoreDueToReservedName (const NamedDecl *ND, Sema &SemaRef)
static DeclContext::lookup_result getConstructors (ASTContext &Context, const CXXRecordDecl *Record)
static bool isConstructor (const Decl *ND)
static void setInBaseClass (ResultBuilder::Result &R)
static OverloadCompare compareOverloads (const CXXMethodDecl &Candidate, const CXXMethodDecl &Incumbent, const Qualifiers &ObjectQuals, ExprValueKind ObjectKind)
static bool isObjCReceiverType (ASTContext &C, QualType T)
static void AddTypeSpecifierResults (const LangOptions &LangOpts, ResultBuilder &Results)
Add type specifiers for the current language as keyword results.
static void AddStorageSpecifiers (Sema::ParserCompletionContext CCC, const LangOptions &LangOpts, ResultBuilder &Results)
static void AddFunctionSpecifiers (Sema::ParserCompletionContext CCC, const LangOptions &LangOpts, ResultBuilder &Results)
static void AddObjCExpressionResults (ResultBuilder &Results, bool NeedAt)
static void AddObjCStatementResults (ResultBuilder &Results, bool NeedAt)
static void AddObjCVisibilityResults (const LangOptions &LangOpts, ResultBuilder &Results, bool NeedAt)
static void AddObjCImplementationResults (const LangOptions &LangOpts, ResultBuilder &Results, bool NeedAt)
static void AddObjCInterfaceResults (const LangOptions &LangOpts, ResultBuilder &Results, bool NeedAt)
static void AddObjCTopLevelResults (ResultBuilder &Results, bool NeedAt)
static void AddTypedefResult (ResultBuilder &Results)
static void AddUsingAliasResult (CodeCompletionBuilder &Builder, ResultBuilder &Results)
static bool WantTypesInContext (Sema::ParserCompletionContext CCC, const LangOptions &LangOpts)
static PrintingPolicy getCompletionPrintingPolicy (const ASTContext &Context, const Preprocessor &PP)
static PrintingPolicy getCompletionPrintingPolicy (Sema &S)
Retrieve a printing policy suitable for code completion.
static const char * GetCompletionTypeString (QualType T, ASTContext &Context, const PrintingPolicy &Policy, CodeCompletionAllocator &Allocator)
Retrieve the string representation of the given type as a string that has the appropriate lifetime for code completion.
static void addThisCompletion (Sema &S, ResultBuilder &Results)
Add a completion for "this", if we're in a member function.
static void AddStaticAssertResult (CodeCompletionBuilder &Builder, ResultBuilder &Results, const LangOptions &LangOpts)
static void AddOverrideResults (ResultBuilder &Results, const CodeCompletionContext &CCContext, CodeCompletionBuilder &Builder)
static void AddOrdinaryNameResults (Sema::ParserCompletionContext CCC, Scope *S, Sema &SemaRef, ResultBuilder &Results)
Add language constructs that show up for "ordinary" names.
static void AddResultTypeChunk (ASTContext &Context, const PrintingPolicy &Policy, const NamedDecl *ND, QualType BaseType, CodeCompletionBuilder &Result)
If the given declaration has an associated type, add it as a result type chunk.
static void MaybeAddSentinel (Preprocessor &PP, const NamedDecl *FunctionOrMethod, CodeCompletionBuilder &Result)
static std::string formatObjCParamQualifiers (unsigned ObjCQuals, QualType &Type)
static void findTypeLocationForBlockDecl (const TypeSourceInfo *TSInfo, FunctionTypeLoc &Block, FunctionProtoTypeLoc &BlockProto, bool SuppressBlock=false)
Tries to find the most appropriate type location for an Objective-C block placeholder.
static std::string formatBlockPlaceholder (const PrintingPolicy &Policy, const NamedDecl *BlockDecl, FunctionTypeLoc &Block, FunctionProtoTypeLoc &BlockProto, bool SuppressBlockName, bool SuppressBlock, Optional< ArrayRef< QualType > > ObjCSubsts)
Returns a placeholder string that corresponds to an Objective-C block declaration.
static std::string FormatFunctionParameter (const PrintingPolicy &Policy, const DeclaratorDecl *Param, bool SuppressName=false, bool SuppressBlock=false, Optional< ArrayRef< QualType > > ObjCSubsts=None)
static std::string GetDefaultValueString (const ParmVarDecl *Param, const SourceManager &SM, const LangOptions &LangOpts)
static void AddFunctionParameterChunks (Preprocessor &PP, const PrintingPolicy &Policy, const FunctionDecl *Function, CodeCompletionBuilder &Result, unsigned Start=0, bool InOptional=false)
Add function parameter chunks to the given code completion string.
static void AddTemplateParameterChunks (ASTContext &Context, const PrintingPolicy &Policy, const TemplateDecl *Template, CodeCompletionBuilder &Result, unsigned MaxParameters=0, unsigned Start=0, bool InDefaultArg=false)
Add template parameter chunks to the given code completion string.
static void AddQualifierToCompletionString (CodeCompletionBuilder &Result, NestedNameSpecifier *Qualifier, bool QualifierIsInformative, ASTContext &Context, const PrintingPolicy &Policy)
Add a qualifier to the given code-completion string, if the provided nested-name-specifier is non-NULL.
static void AddFunctionTypeQualsToCompletionString (CodeCompletionBuilder &Result, const FunctionDecl *Function)
static void AddTypedNameChunk (ASTContext &Context, const PrintingPolicy &Policy, const NamedDecl *ND, CodeCompletionBuilder &Result)
Add the name of the given declaration.
static void printOverrideString (const CodeCompletionString &CCS, std::string &BeforeName, std::string &NameAndSignature)
static const NamedDecl * extractFunctorCallOperator (const NamedDecl *ND)
static void AddOverloadAggregateChunks (const RecordDecl *RD, const PrintingPolicy &Policy, CodeCompletionBuilder &Result, unsigned CurrentArg)
static void AddOverloadParameterChunks (ASTContext &Context, const PrintingPolicy &Policy, const FunctionDecl *Function, const FunctionProtoType *Prototype, FunctionProtoTypeLoc PrototypeLoc, CodeCompletionBuilder &Result, unsigned CurrentArg, unsigned Start=0, bool InOptional=false)
Add function overload parameter chunks to the given code completion string.
static std::string formatTemplateParameterPlaceholder (const NamedDecl *Param, bool &Optional, const PrintingPolicy &Policy)
static std::string templateResultType (const TemplateDecl *TD, const PrintingPolicy &Policy)
static CodeCompletionString * createTemplateSignatureString (const TemplateDecl *TD, CodeCompletionBuilder &Builder, unsigned CurrentArg, const PrintingPolicy &Policy)
static void AddMacroResults (Preprocessor &PP, ResultBuilder &Results, bool LoadExternal, bool IncludeUndefined, bool TargetTypeIsPointer=false)
static void AddPrettyFunctionResults (const LangOptions &LangOpts, ResultBuilder &Results)
static void HandleCodeCompleteResults (Sema *S, CodeCompleteConsumer *CodeCompleter, CodeCompletionContext Context, CodeCompletionResult *Results, unsigned NumResults)
static CodeCompletionContext mapCodeCompletionContext (Sema &S, Sema::ParserCompletionContext PCC)
static void MaybeAddOverrideCalls (Sema &S, DeclContext *InContext, ResultBuilder &Results)
If we're in a C++ virtual member function, add completion results that invoke the functions we override, since it's common to invoke the overridden function as well as adding new functionality.
static void AddClassMessageCompletions (Sema &SemaRef, Scope *S, ParsedType Receiver, ArrayRef< IdentifierInfo * > SelIdents, bool AtArgumentExpression, bool IsSuper, ResultBuilder &Results)
static const char * underscoreAttrScope (llvm::StringRef Scope)
static const char * noUnderscoreAttrScope (llvm::StringRef Scope)
static void AddEnumerators (ResultBuilder &Results, ASTContext &Context, EnumDecl *Enum, DeclContext *CurContext, const CoveredEnumerators &Enumerators)
static const FunctionProtoType * TryDeconstructFunctionLike (QualType T)
Try to find a corresponding FunctionProtoType for function-like types (e.g.
static void AddLambdaCompletion (ResultBuilder &Results, llvm::ArrayRef< QualType > Parameters, const LangOptions &LangOpts)
Adds a pattern completion for a lambda expression with the specified parameter types and placeholders for parameter names.
static ObjCContainerDecl * getContainerDef (ObjCContainerDecl *Container)
Retrieve the container definition, if any?
static void AddObjCBlockCall (ASTContext &Context, const PrintingPolicy &Policy, CodeCompletionBuilder &Builder, const NamedDecl *BD, const FunctionTypeLoc &BlockLoc, const FunctionProtoTypeLoc &BlockProtoLoc)
Adds a block invocation code completion result for the given block declaration BD.
static void AddObjCProperties (const CodeCompletionContext &CCContext, ObjCContainerDecl *Container, bool AllowCategories, bool AllowNullaryMethods, DeclContext *CurContext, AddedPropertiesSet &AddedProperties, ResultBuilder &Results, bool IsBaseExprStatement=false, bool IsClassProperty=false, bool InOriginalClass=true)
static void AddRecordMembersCompletionResults (Sema &SemaRef, ResultBuilder &Results, Scope *S, QualType BaseType, ExprValueKind BaseKind, RecordDecl *RD, Optional< FixItHint > AccessOpFixIt)
static RecordDecl * getAsRecordDecl (const QualType BaseType)
static void AddTypeQualifierResults (DeclSpec &DS, ResultBuilder &Results, const LangOptions &LangOpts)
static bool anyNullArguments (ArrayRef< Expr * > Args)
static void mergeCandidatesWithResults (Sema &SemaRef, SmallVectorImpl< ResultCandidate > &Results, OverloadCandidateSet &CandidateSet, SourceLocation Loc, size_t ArgSize)
static QualType getParamType (Sema &SemaRef, ArrayRef< ResultCandidate > Candidates, unsigned N)
Get the type of the Nth parameter from a given set of overload candidates.
static QualType ProduceSignatureHelp (Sema &SemaRef, MutableArrayRef< ResultCandidate > Candidates, unsigned CurrentArg, SourceLocation OpenParLoc, bool Braced)
static FunctionProtoTypeLoc GetPrototypeLoc (Expr *Fn)
static llvm::Optional< unsigned > getNextAggregateIndexAfterDesignatedInit (const ResultCandidate &Aggregate, ArrayRef< Expr * > Args)
static bool argMatchesTemplateParams (const ParsedTemplateArgument &Arg, unsigned Index, const TemplateParameterList &Params)
static bool isNamespaceScope (Scope *S)
Determine whether this scope denotes a namespace.
static bool ObjCPropertyFlagConflicts (unsigned Attributes, unsigned NewFlag)
Determine whether the addition of the given flag to an Objective-C property's attributes will cause a conflict.
static bool isAcceptableObjCSelector (Selector Sel, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, bool AllowSameLength=true)
static bool isAcceptableObjCMethod (ObjCMethodDecl *Method, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, bool AllowSameLength=true)
static void AddObjCMethods (ObjCContainerDecl *Container, bool WantInstanceMethods, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, DeclContext *CurContext, VisitedSelectorSet &Selectors, bool AllowSameLength, ResultBuilder &Results, bool InOriginalClass=true, bool IsRootClass=false)
Add all of the Objective-C methods in the given Objective-C container to the set of results.
static ObjCInterfaceDecl * GetAssumedMessageSendExprType (Expr *E)
When we have an expression with type "id", we may assume that it has some more-specific class type based on knowledge of common uses of Objective-C.
static ObjCMethodDecl * AddSuperSendCompletion (Sema &S, bool NeedSuperKeyword, ArrayRef< IdentifierInfo * > SelIdents, ResultBuilder &Results)
static QualType getPreferredArgumentTypeForMessageSend (ResultBuilder &Results, unsigned NumSelIdents)
Given a set of code-completion results for the argument of a message send, determine the preferred type (if any) for that argument expression.
static void AddProtocolResults (DeclContext *Ctx, DeclContext *CurContext, bool OnlyForwardDeclarations, ResultBuilder &Results)
Add all of the protocol declarations that we find in the given (translation unit) context.
static void AddInterfaceResults (DeclContext *Ctx, DeclContext *CurContext, bool OnlyForwardDeclarations, bool OnlyUnimplemented, ResultBuilder &Results)
Add all of the Objective-C interface declarations that we find in the given (translation unit) context.
static void FindImplementableMethods (ASTContext &Context, ObjCContainerDecl *Container, Optional< bool > WantInstanceMethods, QualType ReturnType, KnownMethodsMap &KnownMethods, bool InOriginalClass=true)
Find all of the methods that reside in the given container (and its superclasses, protocols, etc.) that meet the given criteria.
static void AddObjCPassingTypeChunk (QualType Type, unsigned ObjCDeclQuals, ASTContext &Context, const PrintingPolicy &Policy, CodeCompletionBuilder &Builder)
Add the parenthesized return or parameter type chunk to a code completion string.
static bool InheritsFromClassNamed (ObjCInterfaceDecl *Class, StringRef Name)
Determine whether the given class is or inherits from a class by the given name.
static void AddObjCKeyValueCompletions (ObjCPropertyDecl *Property, bool IsInstanceMethod, QualType ReturnType, ASTContext &Context, VisitedSelectorSet &KnownSelectors, ResultBuilder &Results)
Add code completions for Objective-C Key-Value Coding (KVC) and Key-Value Observing (KVO).
Macro Definition Documentation
OBJC_AT_KEYWORD_NAME
#define OBJC_AT_KEYWORD_NAME (NeedAt, Keyword)
Value:
((NeedAt) ? "@" Keyword : Keyword)
Macro that optionally prepends an "@" to the string literal passed in via Keyword, depending on whether NeedAt is true or false.
Definition at line 6993 of file SemaCodeComplete.cpp.
Referenced by AddObjCExpressionResults(), AddObjCImplementationResults(), AddObjCInterfaceResults(), AddObjCStatementResults(), AddObjCTopLevelResults(), and AddObjCVisibilityResults().
OVERLOADED_OPERATOR [1/2]
#define OVERLOADED_OPERATOR (Name, Spelling, Token, Unary, Binary, MemberOnly)
Value:
  case OO_##Name:                                                              \
    OperatorName = "operator" Spelling;                                        \
    break;
OVERLOADED_OPERATOR [2/2]
#define OVERLOADED_OPERATOR (Name, Spelling, Token, Unary, Binary, MemberOnly)
Value:
  if (OO_##Name != OO_Conditional)                                             \
    Results.AddResult(Result(Spelling));
OVERLOADED_OPERATOR_MULTI
#define OVERLOADED_OPERATOR_MULTI (Name, Spelling, Unary, Binary, MemberOnly)
Typedef Documentation
AddedPropertiesSet
typedef llvm::SmallPtrSet<IdentifierInfo *, 16> AddedPropertiesSet
The set of properties that have already been added, referenced by property name.
Definition at line 4809 of file SemaCodeComplete.cpp.
KnownMethodsMap
typedef llvm::DenseMap<Selector, llvm::PointerIntPair<ObjCMethodDecl *, 1, bool> > KnownMethodsMap
Definition at line 8664 of file SemaCodeComplete.cpp.
ResultCandidate
typedef CodeCompleteConsumer::OverloadCandidate ResultCandidate
Definition at line 5930 of file SemaCodeComplete.cpp.
VisitedSelectorSet
typedef llvm::SmallPtrSet<Selector, 16> VisitedSelectorSet
A set of selectors, which is used to avoid introducing multiple completions with the same selector into the result set.
Definition at line 7409 of file SemaCodeComplete.cpp.
Enumeration Type Documentation
ObjCMethodKind
enum ObjCMethodKind
Describes the kind of Objective-C method that we want to find via code completion.
Enumerator
MK_Any
Any kind of method, provided it means other specified criteria.
MK_ZeroArgSelector
Zero-argument (unary) selector.
MK_OneArgSelector
One-argument selector.
Definition at line 7367 of file SemaCodeComplete.cpp.
OverloadCompare
enum class OverloadCompare strong
Enumerator
BothViable
Dominates
Dominated
Definition at line 1212 of file SemaCodeComplete.cpp.
Function Documentation
AddClassMessageCompletions()
static void AddClassMessageCompletions (Sema & SemaRef, Scope * S, ParsedType Receiver, ArrayRef< IdentifierInfo * > SelIdents, bool AtArgumentExpression, bool IsSuper, ResultBuilder & Results) static
Definition at line 7971 of file SemaCodeComplete.cpp.
References AddObjCMethods(), AddSuperSendCompletion(), clang::Sema::GlobalMethodPool::begin(), clang::Sema::GlobalMethodPool::count(), clang::Sema::CurContext, clang::Sema::GlobalMethodPool::end(), clang::Type::getAs(), clang::Sema::getCurMethodDecl(), clang::ExternalASTSource::GetExternalSelector(), clang::Sema::getExternalSource(), clang::ExternalASTSource::GetNumExternalSelectors(), clang::Sema::GetTypeFromParser(), isAcceptableObjCMethod(), clang::Selector::isNull(), clang::Sema::MethodPool, MK_Any, N, clang::Sema::ReadMethodPool(), and clang::Result.
Referenced by clang::Sema::CodeCompleteDeclSpec(), and clang::Sema::CodeCompleteObjCClassMessage().
AddEnumerators()
static void AddEnumerators (ResultBuilder & Results, ASTContext & Context, EnumDecl * Enum, DeclContext * CurContext, const CoveredEnumerators & Enumerators) static
Definition at line 4630 of file SemaCodeComplete.cpp.
References clang::CCP_EnumInCase, Enum, clang::ASTContext::getLangOpts(), and getRequiredQualification().
Referenced by clang::Sema::CodeCompleteCase(), and clang::Sema::CodeCompleteExpression().
AddFunctionParameterChunks()
static void AddFunctionParameterChunks (Preprocessor & PP, const PrintingPolicy & Policy, const FunctionDecl * Function, CodeCompletionBuilder & Result, unsigned Start = 0, bool InOptional = false) static
Add function parameter chunks to the given code completion string.
Definition at line 3006 of file SemaCodeComplete.cpp.
References clang::CodeCompletionBuilder::AddChunk(), AddFunctionParameterChunks(), clang::CodeCompletionString::CK_Comma, FormatFunctionParameter(), GetDefaultValueString(), clang::Preprocessor::getLangOpts(), clang::Preprocessor::getSourceManager(), MaybeAddSentinel(), N, P, clang::Result, and clang::CodeCompletionBuilder::TakeString().
Referenced by AddFunctionParameterChunks(), clang::Sema::CodeCompleteConstructorInitializer(), and clang::CodeCompletionResult::createCodeCompletionStringForDecl().
AddFunctionSpecifiers()
static void AddFunctionSpecifiers (Sema::ParserCompletionContext CCC, const LangOptions & LangOpts, ResultBuilder & Results) static
Definition at line 1797 of file SemaCodeComplete.cpp.
References clang::Sema::PCC_Class, clang::Sema::PCC_Condition, clang::Sema::PCC_Expression, clang::Sema::PCC_ForInit, clang::Sema::PCC_LocalDeclarationSpecifiers, clang::Sema::PCC_MemberTemplate, clang::Sema::PCC_Namespace, clang::Sema::PCC_ObjCImplementation, clang::Sema::PCC_ObjCInstanceVariableList, clang::Sema::PCC_ObjCInterface, clang::Sema::PCC_ParenthesizedExpression, clang::Sema::PCC_RecoveryInFunction, clang::Sema::PCC_Statement, clang::Sema::PCC_Template, clang::Sema::PCC_Type, and clang::Result.
Referenced by AddOrdinaryNameResults().
AddFunctionTypeQualsToCompletionString()
static void AddFunctionTypeQualsToCompletionString (CodeCompletionBuilder & Result, const FunctionDecl * Function) static
Definition at line 3163 of file SemaCodeComplete.cpp.
References clang::Result.
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForDecl().
AddInterfaceResults()
static void AddInterfaceResults (DeclContext * Ctx, DeclContext * CurContext, bool OnlyForwardDeclarations, bool OnlyUnimplemented, ResultBuilder & Results) static
Add all of the Objective-C interface declarations that we find in the given (translation unit) context.
Definition at line 8377 of file SemaCodeComplete.cpp.
References clang::DeclContext::decls(), and clang::Result.
Referenced by clang::Sema::CodeCompleteObjCImplementationDecl(), clang::Sema::CodeCompleteObjCInterfaceDecl(), and clang::Sema::CodeCompleteObjCSuperclass().
AddLambdaCompletion()
static void AddLambdaCompletion (ResultBuilder & Results, llvm::ArrayRef< QualType > Parameters, const LangOptions & LangOpts) static
Adds a pattern completion for a lambda expression with the specified parameter types and placeholders for parameter names.
Definition at line 4675 of file SemaCodeComplete.cpp.
References clang::CodeCompletionBuilder::AddChunk(), clang::CodeCompletionBuilder::AddPlaceholderChunk(), clang::CodeCompletionBuilder::AddTextChunk(), clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftBrace, clang::CodeCompletionString::CK_LeftBracket, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightBrace, clang::CodeCompletionString::CK_RightBracket, clang::CodeCompletionString::CK_RightParen, clang::CodeCompletionAllocator::CopyString(), clang::First, clang::CodeCompletionBuilder::getAllocator(), clang::Parameter, and clang::CodeCompletionBuilder::TakeString().
Referenced by clang::Sema::CodeCompleteExpression().
AddMacroResults()
static void AddMacroResults (Preprocessor & PP, ResultBuilder & Results, bool LoadExternal, bool IncludeUndefined, bool TargetTypeIsPointer = false) static
Definition at line 4075 of file SemaCodeComplete.cpp.
References clang::Preprocessor::getLangOpts(), clang::Preprocessor::getMacroDefinition(), clang::getMacroUsagePriority(), clang::MacroInfo::isUsedForHeaderGuard(), clang::Preprocessor::macro_begin(), clang::Preprocessor::macro_end(), and clang::Result.
Referenced by clang::Sema::CodeCompleteAfterIf(), clang::Sema::CodeCompleteCase(), clang::Sema::CodeCompleteExpression(), clang::Sema::CodeCompleteObjCMessageReceiver(), clang::Sema::CodeCompleteObjCPassingType(), clang::Sema::CodeCompleteOrdinaryName(), clang::Sema::CodeCompletePreprocessorExpression(), and clang::Sema::GatherGlobalCodeCompletions().
AddObjCBlockCall()
static void AddObjCBlockCall (ASTContext & Context, const PrintingPolicy & Policy, CodeCompletionBuilder & Builder, const NamedDecl * BD, const FunctionTypeLoc & BlockLoc, const FunctionProtoTypeLoc & BlockProtoLoc) static
Adds a block invocation code completion result for the given block declaration BD.
Definition at line 4831 of file SemaCodeComplete.cpp.
References AddTypedNameChunk(), clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, FormatFunctionParameter(), GetCompletionTypeString(), clang::FunctionTypeLoc::getNumParams(), clang::FunctionTypeLoc::getParam(), clang::FunctionTypeLoc::getReturnLoc(), clang::TypeLoc::getType(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::FunctionProtoType::isVariadic(), and N.
Referenced by AddObjCProperties().
AddObjCExpressionResults()
static void AddObjCExpressionResults (ResultBuilder & Results, bool NeedAt) static
Definition at line 7104 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_Colon, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightBrace, clang::CodeCompletionString::CK_RightBracket, clang::CodeCompletionString::CK_RightParen, OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), clang::Sema::CodeCompleteObjCAtExpression(), and clang::Sema::CodeCompleteObjCAtStatement().
AddObjCImplementationResults()
static void AddObjCImplementationResults (const LangOptions & LangOpts, ResultBuilder & Results, bool NeedAt) static
Definition at line 6995 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_HorizontalSpace, OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteObjCAtDirective().
AddObjCInterfaceResults()
static void AddObjCInterfaceResults (const LangOptions & LangOpts, ResultBuilder & Results, bool NeedAt) static
Definition at line 7018 of file SemaCodeComplete.cpp.
References OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteObjCAtDirective().
AddObjCKeyValueCompletions()
static void AddObjCKeyValueCompletions (ObjCPropertyDecl * Property, bool IsInstanceMethod, QualType ReturnType, ASTContext & Context, VisitedSelectorSet & KnownSelectors, ResultBuilder & Results) static
Add code completions for Objective-C Key-Value Coding (KVC) and Key-Value Observing (KVO).
Definition at line 8783 of file SemaCodeComplete.cpp.
References AddObjCPassingTypeChunk(), clang::Type::castAs(), clang::CCD_ProbablyNotObjCCollection, clang::CCP_CodePattern, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, CXCursor_ObjCClassMethodDecl, CXCursor_ObjCInstanceMethodDecl, clang::IdentifierTable::get(), getCompletionPrintingPolicy(), GetCompletionTypeString(), clang::ObjCObjectPointerType::getInterfaceDecl(), clang::IdentifierInfo::getLength(), clang::IdentifierInfo::getName(), clang::NamedDecl::getName(), clang::QualType::getNonReferenceType(), clang::SelectorTable::getNullarySelector(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::hasSameUnqualifiedType(), clang::ASTContext::Idents, InheritsFromClassNamed(), clang::Type::isBooleanType(), clang::Type::isIntegerType(), clang::QualType::isNull(), clang::Type::isObjCObjectPointerType(), clang::Type::isVoidType(), clang::Result, clang::ASTContext::Selectors, and clang::toUppercase().
Referenced by clang::Sema::CodeCompleteObjCMethodDecl().
AddObjCMethods()
static void AddObjCMethods (ObjCContainerDecl * Container, bool WantInstanceMethods, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, DeclContext * CurContext, VisitedSelectorSet & Selectors, bool AllowSameLength, ResultBuilder & Results, bool InOriginalClass = true, bool IsRootClass = false) static
Add all of the Objective-C methods in the given Objective-C container to the set of results.
The container will be a class, protocol, category, or implementation of any of the above. This mether will recurse to include methods from the superclasses of classes along with their categories, protocols, and implementations.
Parameters
Container the container in which we'll look to find methods.
WantInstanceMethods Whether to add instance methods (only); if false, this routine will add factory methods (only).
CurContext the context in which we're performing the lookup that finds methods.
AllowSameLength Whether we allow a method to be added to the list when it has the same number of parameters as we have selector identifiers.
Results the structure into which we'll add results.
Definition at line 7431 of file SemaCodeComplete.cpp.
References AddObjCMethods(), clang::ObjCList< T >::begin(), clang::ObjCList< T >::end(), getContainerDef(), clang::ObjCInterfaceDecl::getImplementation(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCInterfaceDecl::hasDefinition(), isAcceptableObjCMethod(), clang::ObjCInterfaceDecl::known_categories(), MK_Any, clang::ObjCInterfaceDecl::protocols(), clang::Result, and setInBaseClass().
Referenced by AddClassMessageCompletions(), AddObjCMethods(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCPropertyGetter(), and clang::Sema::CodeCompleteObjCPropertySetter().
AddObjCPassingTypeChunk()
static void AddObjCPassingTypeChunk (QualType Type, unsigned ObjCDeclQuals, ASTContext & Context, const PrintingPolicy & Policy, CodeCompletionBuilder & Builder) static
Add the parenthesized return or parameter type chunk to a code completion string.
Definition at line 8756 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, formatObjCParamQualifiers(), and GetCompletionTypeString().
Referenced by AddObjCKeyValueCompletions(), and clang::Sema::CodeCompleteObjCMethodDecl().
AddObjCProperties()
static void AddObjCProperties (const CodeCompletionContext & CCContext, ObjCContainerDecl * Container, bool AllowCategories, bool AllowNullaryMethods, DeclContext * CurContext, AddedPropertiesSet & AddedProperties, ResultBuilder & Results, bool IsBaseExprStatement = false, bool IsClassProperty = false, bool InOriginalClass = true) static
Definition at line 4868 of file SemaCodeComplete.cpp.
References AddObjCBlockCall(), AddObjCProperties(), AddResultTypeChunk(), Category, clang::CCD_BlockPropertySetter, clang::CCD_MethodAsProperty, clang::CCP_MemberDeclaration, clang::CodeCompletionString::CK_Equal, findTypeLocationForBlockDecl(), formatBlockPlaceholder(), clang::CodeCompletionContext::getBaseType(), getCompletionPrintingPolicy(), getContainerDef(), clang::FunctionType::getReturnType(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::Type::isVoidType(), P, clang::Result, and setInBaseClass().
Referenced by AddObjCProperties(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteObjCClassPropertyRefExpr(), and clang::Sema::CodeCompleteObjCPropertyDefinition().
AddObjCStatementResults()
static void AddObjCStatementResults (ResultBuilder & Results, bool NeedAt) static
Definition at line 7169 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftBrace, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightBrace, clang::CodeCompletionString::CK_RightParen, OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteObjCAtStatement().
AddObjCTopLevelResults()
static void AddObjCTopLevelResults (ResultBuilder & Results, bool NeedAt) static
Definition at line 7037 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_HorizontalSpace, OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteObjCAtDirective().
AddObjCVisibilityResults()
static void AddObjCVisibilityResults (const LangOptions & LangOpts, ResultBuilder & Results, bool NeedAt) static
Definition at line 7215 of file SemaCodeComplete.cpp.
References OBJC_AT_KEYWORD_NAME, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteObjCAtVisibility().
AddOrdinaryNameResults()
static void AddOrdinaryNameResults (Sema::ParserCompletionContext CCC, Scope * S, Sema & SemaRef, ResultBuilder & Results) static
Add language constructs that show up for "ordinary" names.
while (condition) { statements }
Definition at line 2037 of file SemaCodeComplete.cpp.
References AddFunctionSpecifiers(), AddObjCExpressionResults(), AddObjCImplementationResults(), AddObjCInterfaceResults(), AddObjCStatementResults(), AddObjCTopLevelResults(), AddObjCVisibilityResults(), AddOverrideResults(), AddStaticAssertResult(), AddStorageSpecifiers(), addThisCompletion(), AddTypedefResult(), AddTypeSpecifierResults(), AddUsingAliasResult(), clang::CodeCompletionContext::CCC_ClassStructUnion, clang::CodeCompletionString::CK_Colon, clang::CodeCompletionString::CK_Equal, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftAngle, clang::CodeCompletionString::CK_LeftBrace, clang::CodeCompletionString::CK_LeftBracket, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightAngle, clang::CodeCompletionString::CK_RightBrace, clang::CodeCompletionString::CK_RightBracket, clang::CodeCompletionString::CK_RightParen, clang::CodeCompletionString::CK_SemiColon, clang::CodeCompletionString::CK_VerticalSpace, clang::Sema::CurContext, clang::Sema::getCurBlock(), clang::Sema::getCurFunction(), clang::Sema::getCurMethodDecl(), clang::Sema::getLangOpts(), clang::Type::isBooleanType(), clang::DeclContext::isDependentContext(), clang::Preprocessor::isMacroDefined(), clang::Type::isMemberPointerType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::Type::isVoidType(), clang::Sema::PCC_Class, clang::Sema::PCC_Condition, clang::Sema::PCC_Expression, clang::Sema::PCC_ForInit, clang::Sema::PCC_LocalDeclarationSpecifiers, clang::Sema::PCC_MemberTemplate, clang::Sema::PCC_Namespace, clang::Sema::PCC_ObjCImplementation, clang::Sema::PCC_ObjCInstanceVariableList, clang::Sema::PCC_ObjCInterface, clang::Sema::PCC_ParenthesizedExpression, clang::Sema::PCC_RecoveryInFunction, clang::Sema::PCC_Statement, clang::Sema::PCC_Template, clang::Sema::PCC_Type, clang::Sema::PP, clang::Result, clang::sema::CapturingScopeInfo::ReturnType, clang::CodeCompletionResult::RK_Keyword, clang::sema::FunctionScopeInfo::SwitchStack, and WantTypesInContext().
Referenced by clang::Sema::CodeCompleteAfterIf(), clang::Sema::CodeCompleteExpression(), clang::Sema::CodeCompleteObjCPassingType(), and clang::Sema::CodeCompleteOrdinaryName().
AddOverloadAggregateChunks()
static void AddOverloadAggregateChunks (const RecordDecl * RD, const PrintingPolicy & Policy, CodeCompletionBuilder & Result, unsigned CurrentArg) static
Definition at line 3699 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_Comma, clang::RecordDecl::fields(), FormatFunctionParameter(), and clang::Result.
Referenced by clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString().
AddOverloadParameterChunks()
static void AddOverloadParameterChunks (ASTContext & Context, const PrintingPolicy & Policy, const FunctionDecl * Function, const FunctionProtoType * Prototype, FunctionProtoTypeLoc PrototypeLoc, CodeCompletionBuilder & Result, unsigned CurrentArg, unsigned Start = 0, bool InOptional = false) static
Add function overload parameter chunks to the given code completion string.
Definition at line 3726 of file SemaCodeComplete.cpp.
References clang::CodeCompletionBuilder::AddChunk(), clang::CodeCompletionBuilder::AddCurrentParameterChunk(), AddOverloadParameterChunks(), clang::CodeCompletionBuilder::AddPlaceholderChunk(), clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_CurrentParameter, FormatFunctionParameter(), GetDefaultValueString(), clang::ASTContext::getLangOpts(), clang::FunctionTypeLoc::getParam(), clang::ASTContext::getSourceManager(), P, clang::Prototype, clang::Result, and clang::CodeCompletionBuilder::TakeString().
Referenced by AddOverloadParameterChunks(), and clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString().
AddOverrideResults()
static void AddOverrideResults (ResultBuilder & Results, const CodeCompletionContext & CCContext, CodeCompletionBuilder & Builder) static
Definition at line 1982 of file SemaCodeComplete.cpp.
References clang::CCP_CodePattern, clang::CodeCompletionResult::createCodeCompletionStringForOverride(), clang::Sema::CurContext, clang::Sema::getASTContext(), getCompletionPrintingPolicy(), clang::Sema::getPreprocessor(), and clang::Sema::IsOverload().
Referenced by AddOrdinaryNameResults().
AddPrettyFunctionResults()
static void AddPrettyFunctionResults (const LangOptions & LangOpts, ResultBuilder & Results) static
Definition at line 4101 of file SemaCodeComplete.cpp.
References clang::CCP_Constant, and clang::Result.
Referenced by clang::Sema::CodeCompleteAfterIf(), clang::Sema::CodeCompleteExpression(), and clang::Sema::CodeCompleteOrdinaryName().
AddProtocolResults()
static void AddProtocolResults (DeclContext * Ctx, DeclContext * CurContext, bool OnlyForwardDeclarations, ResultBuilder & Results) static
Add all of the protocol declarations that we find in the given (translation unit) context.
Definition at line 8314 of file SemaCodeComplete.cpp.
References clang::DeclContext::decls(), and clang::Result.
Referenced by clang::Sema::CodeCompleteObjCProtocolDecl(), and clang::Sema::CodeCompleteObjCProtocolReferences().
AddQualifierToCompletionString()
static void AddQualifierToCompletionString (CodeCompletionBuilder & Result, NestedNameSpecifier * Qualifier, bool QualifierIsInformative, ASTContext & Context, const PrintingPolicy & Policy) static
Add a qualifier to the given code-completion string, if the provided nested-name-specifier is non-NULL.
Definition at line 3143 of file SemaCodeComplete.cpp.
References clang::Result.
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForDecl().
AddRecordMembersCompletionResults()
static void AddRecordMembersCompletionResults (Sema & SemaRef, ResultBuilder & Results, Scope * S, QualType BaseType, ExprValueKind BaseKind, RecordDecl * RD, Optional< FixItHint > AccessOpFixIt) static
Definition at line 5048 of file SemaCodeComplete.cpp.
References clang::Sema::CodeCompleter, clang::Sema::getLangOpts(), clang::CodeCompleteConsumer::includeGlobals(), clang::DeclContext::isDependentContext(), clang::CodeCompleteConsumer::loadExternal(), clang::Sema::LookupMemberName, and clang::Sema::LookupVisibleDecls().
Referenced by clang::Sema::CodeCompleteMemberReferenceExpr().
AddResultTypeChunk()
static void AddResultTypeChunk (ASTContext & Context, const PrintingPolicy & Policy, const NamedDecl * ND, QualType BaseType, CodeCompletionBuilder & Result) static
If the given declaration has an associated type, add it as a result type chunk.
Definition at line 2670 of file SemaCodeComplete.cpp.
References clang::ASTContext::DependentTy, clang::Decl::getAsFunction(), GetCompletionTypeString(), clang::TypeName::getFullyQualifiedType(), clang::ASTContext::getTypeDeclType(), clang::ASTContext::hasSameType(), isConstructor(), and clang::Result.
Referenced by AddObjCProperties(), AddSuperSendCompletion(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), and clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString().
AddStaticAssertResult()
static void AddStaticAssertResult (CodeCompletionBuilder & Builder, ResultBuilder & Results, const LangOptions & LangOpts) static
Definition at line 1966 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, and clang::CodeCompletionString::CK_SemiColon.
Referenced by AddOrdinaryNameResults().
AddStorageSpecifiers()
static void AddStorageSpecifiers (Sema::ParserCompletionContext CCC, const LangOptions & LangOpts, ResultBuilder & Results) static
Definition at line 1771 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, and clang::Result.
Referenced by AddOrdinaryNameResults().
AddSuperSendCompletion()
static ObjCMethodDecl * AddSuperSendCompletion (Sema & S, bool NeedSuperKeyword, ArrayRef< IdentifierInfo * > SelIdents, ResultBuilder & Results) static
Parameters
S The semantic analysis object.
NeedSuperKeyword Whether we need to prefix this completion with the "super" keyword. Otherwise, we just need to provide the arguments.
SelIdents The identifiers in the selector that have already been provided as arguments for a send to "super".
Results The set of results to augment.
Returns
the Objective-C method declaration that would be invoked by this "super" completion. If NULL, no completion was added.
Definition at line 7739 of file SemaCodeComplete.cpp.
References AddResultTypeChunk(), clang::CCP_SuperCompletion, clang::CodeCompletionString::CK_HorizontalSpace, clang::Sema::Context, clang::ObjCMethodDecl::getClassInterface(), getCompletionPrintingPolicy(), clang::Sema::getCurMethodDecl(), clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::ObjCMethodDecl::getSelector(), clang::ASTContext::hasSameUnqualifiedType(), clang::ObjCMethodDecl::isInstanceMethod(), clang::Selector::isUnarySelector(), clang::ObjCMethodDecl::isVariadic(), N, clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), and clang::ObjCMethodDecl::param_size().
Referenced by AddClassMessageCompletions(), clang::Sema::CodeCompleteObjCInstanceMessage(), and clang::Sema::CodeCompleteObjCMessageReceiver().
AddTemplateParameterChunks()
static void AddTemplateParameterChunks (ASTContext & Context, const PrintingPolicy & Policy, const TemplateDecl * Template, CodeCompletionBuilder & Result, unsigned MaxParameters = 0, unsigned Start = 0, bool InDefaultArg = false) static
Add template parameter chunks to the given code completion string.
Definition at line 3060 of file SemaCodeComplete.cpp.
References clang::CodeCompletionBuilder::AddChunk(), AddTemplateParameterChunks(), clang::TemplateParameterList::begin(), clang::cast(), clang::CodeCompletionString::CK_Comma, clang::IdentifierInfo::deuglifiedName(), clang::TemplateParameterList::end(), clang::Decl::getCanonicalDecl(), clang::NamedDecl::getIdentifier(), clang::TemplateDecl::getTemplateParameters(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), P, clang::Result, and clang::CodeCompletionBuilder::TakeString().
Referenced by AddTemplateParameterChunks(), AddTypedNameChunk(), and clang::CodeCompletionResult::createCodeCompletionStringForDecl().
addThisCompletion()
static void addThisCompletion (Sema & S, ResultBuilder & Results) static
Add a completion for "this", if we're in a member function.
Definition at line 1952 of file SemaCodeComplete.cpp.
References clang::Sema::Context, getCompletionPrintingPolicy(), GetCompletionTypeString(), clang::Sema::getCurrentThisType(), and clang::QualType::isNull().
Referenced by AddOrdinaryNameResults(), clang::Sema::CodeCompleteLambdaIntroducer(), and clang::Sema::CodeCompleteObjCMessageReceiver().
AddTypedefResult()
static void AddTypedefResult (ResultBuilder & Results) static
Definition at line 1843 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_HorizontalSpace, and clang::CodeCompletionString::CK_SemiColon.
Referenced by AddOrdinaryNameResults().
AddTypedNameChunk()
static void AddTypedNameChunk (ASTContext & Context, const PrintingPolicy & Policy, const NamedDecl * ND, CodeCompletionBuilder & Result) static
Add the name of the given declaration.
Definition at line 3199 of file SemaCodeComplete.cpp.
References AddTemplateParameterChunks(), clang::cast(), clang::CodeCompletionString::CK_LeftAngle, clang::CodeCompletionString::CK_RightAngle, clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::Type::getAs(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getNameAsString(), clang::DeclarationName::Identifier, clang::NUM_OVERLOADED_OPERATORS, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::OO_None, and clang::Result.
Referenced by AddObjCBlockCall(), and clang::CodeCompletionResult::createCodeCompletionStringForDecl().
AddTypeQualifierResults()
static void AddTypeQualifierResults (DeclSpec & DS, ResultBuilder & Results, const LangOptions & LangOpts) static
Definition at line 5795 of file SemaCodeComplete.cpp.
References clang::DeclSpec::getTypeQualifiers(), clang::DeclSpec::TQ_atomic, clang::DeclSpec::TQ_const, clang::DeclSpec::TQ_restrict, clang::DeclSpec::TQ_unaligned, and clang::DeclSpec::TQ_volatile.
Referenced by clang::Sema::CodeCompleteFunctionQualifiers(), and clang::Sema::CodeCompleteTypeQualifiers().
AddTypeSpecifierResults()
static void AddTypeSpecifierResults (const LangOptions & LangOpts, ResultBuilder & Results) static
Add type specifiers for the current language as keyword results.
Definition at line 1691 of file SemaCodeComplete.cpp.
References clang::CCD_bool_in_ObjC, clang::CCP_Type, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, and clang::Result.
Referenced by AddOrdinaryNameResults(), and clang::Sema::CodeCompleteOperatorName().
AddUsingAliasResult()
static void AddUsingAliasResult (CodeCompletionBuilder & Builder, ResultBuilder & Results) static
Definition at line 1856 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_Equal, clang::CodeCompletionString::CK_HorizontalSpace, and clang::CodeCompletionString::CK_SemiColon.
Referenced by AddOrdinaryNameResults().
anyNullArguments()
static bool anyNullArguments (ArrayRef< Expr * > Args) static
Definition at line 5919 of file SemaCodeComplete.cpp.
Referenced by clang::Sema::ProduceCallSignatureHelp().
argMatchesTemplateParams()
static bool argMatchesTemplateParams (const ParsedTemplateArgument & Arg, unsigned Index, const TemplateParameterList & Params) static
Definition at line 6308 of file SemaCodeComplete.cpp.
References clang::TemplateParameterList::asArray(), clang::ParsedTemplateArgument::getKind(), clang::TemplateParameterList::getParam(), clang::TemplateParameterList::hasParameterPack(), clang::ParsedTemplateArgument::NonType, clang::TemplateParameterList::size(), clang::ParsedTemplateArgument::Template, and clang::ParsedTemplateArgument::Type.
Referenced by clang::Sema::ProduceTemplateArgumentSignatureHelp().
compareOverloads()
static OverloadCompare compareOverloads (const CXXMethodDecl & Candidate, const CXXMethodDecl & Incumbent, const Qualifiers & ObjectQuals, ExprValueKind ObjectKind) static
Definition at line 1217 of file SemaCodeComplete.cpp.
References BothViable, clang::Qualifiers::compatiblyIncludes(), Dominated, Dominates, clang::Decl::getDeclContext(), clang::CXXMethodDecl::getMethodQualifiers(), clang::FunctionDecl::getMinRequiredArguments(), clang::FunctionDecl::getNumParams(), clang::CXXMethodDecl::getRefQualifier(), clang::FunctionDecl::isVariadic(), clang::FunctionDecl::parameters(), clang::RQ_RValue, clang::Decl::specific_attrs(), and clang::VK_XValue.
createTemplateSignatureString()
static CodeCompletionString * createTemplateSignatureString (const TemplateDecl * TD, CodeCompletionBuilder & Builder, unsigned CurrentArg, const PrintingPolicy & Policy) static
Definition at line 3832 of file SemaCodeComplete.cpp.
References clang::TemplateParameterList::asArray(), clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_CurrentParameter, clang::CodeCompletionString::CK_LeftAngle, clang::CodeCompletionString::CK_Placeholder, clang::CodeCompletionString::CK_RightAngle, formatTemplateParameterPlaceholder(), clang::NamedDecl::getNameAsString(), clang::TemplateDecl::getTemplateParameters(), clang::CodeCompletionBuilder::TakeString(), and templateResultType().
Referenced by clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString().
extractFunctorCallOperator()
static const NamedDecl * extractFunctorCallOperator (const NamedDecl * ND) static
Definition at line 3423 of file SemaCodeComplete.cpp.
References clang::RecordDecl::isLambda().
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForDecl().
FindImplementableMethods()
static void FindImplementableMethods (ASTContext & Context, ObjCContainerDecl * Container, Optional< bool > WantInstanceMethods, QualType ReturnType, KnownMethodsMap & KnownMethods, bool InOriginalClass = true) static
Find all of the methods that reside in the given container (and its superclasses, protocols, etc.) that meet the given criteria.
Insert those methods into the map of known methods, indexed by selector so they can be easily found.
Definition at line 8670 of file SemaCodeComplete.cpp.
References clang::ObjCList< T >::begin(), Category, clang::ObjCList< T >::end(), FindImplementableMethods(), clang::ASTContext::hasSameUnqualifiedType(), and clang::QualType::isNull().
Referenced by clang::Sema::CodeCompleteObjCMethodDecl(), and FindImplementableMethods().
findTypeLocationForBlockDecl()
static void findTypeLocationForBlockDecl (const TypeSourceInfo * TSInfo, FunctionTypeLoc & Block, FunctionProtoTypeLoc & BlockProto, bool SuppressBlock = false) static
Tries to find the most appropriate type location for an Objective-C block placeholder.
This function ignores things like typedefs and qualifiers in order to present the most relevant and accurate block placeholders in code completion results.
Definition at line 2776 of file SemaCodeComplete.cpp.
References clang::Block, clang::TypeLoc::getAs(), clang::TypeSourceInfo::getTypeLoc(), clang::TypeLoc::getUnqualifiedLoc(), and clang::TypeLoc::IgnoreParens().
Referenced by AddObjCProperties(), and FormatFunctionParameter().
formatBlockPlaceholder()
static std::string formatBlockPlaceholder (const PrintingPolicy & Policy, const NamedDecl * BlockDecl, FunctionTypeLoc & Block, FunctionProtoTypeLoc & BlockProto, bool SuppressBlockName, bool SuppressBlock, Optional< ArrayRef< QualType > > ObjCSubsts) static
Returns a placeholder string that corresponds to an Objective-C block declaration.
Parameters
BlockDecl A declaration with an Objective-C block type.
Block The most relevant type location for that block type.
SuppressBlockName Determines whether or not the name of the block declaration is included in the resulting string.
Definition at line 2920 of file SemaCodeComplete.cpp.
References clang::Block, FormatFunctionParameter(), clang::QualType::getAsStringInternal(), clang::Decl::getASTContext(), clang::FunctionTypeLoc::getNumParams(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::QualType::getTypePtr(), clang::FunctionProtoType::isVariadic(), clang::Type::isVoidType(), N, clang::Result, and clang::QualType::substObjCTypeArgs().
Referenced by AddObjCProperties(), and FormatFunctionParameter().
FormatFunctionParameter()
static std::string FormatFunctionParameter (const PrintingPolicy & Policy, const DeclaratorDecl * Param, bool SuppressName = false, bool SuppressBlock = false, Optional< ArrayRef< QualType > > ObjCSubsts = None) static
Definition at line 2825 of file SemaCodeComplete.cpp.
References clang::Block, findTypeLocationForBlockDecl(), formatBlockPlaceholder(), formatObjCParamQualifiers(), clang::isa(), clang::Decl::OBJC_TQ_None, clang::Parameter, and clang::Result.
Referenced by AddFunctionParameterChunks(), AddObjCBlockCall(), AddOverloadAggregateChunks(), AddOverloadParameterChunks(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), and formatBlockPlaceholder().
formatObjCParamQualifiers()
static std::string formatObjCParamQualifiers (unsigned ObjCQuals, QualType & Type) static
Definition at line 2731 of file SemaCodeComplete.cpp.
References clang::NonNull, clang::Nullable, clang::NullableResult, clang::Decl::OBJC_TQ_Bycopy, clang::Decl::OBJC_TQ_Byref, clang::Decl::OBJC_TQ_CSNullability, clang::Decl::OBJC_TQ_In, clang::Decl::OBJC_TQ_Inout, clang::Decl::OBJC_TQ_Oneway, clang::Decl::OBJC_TQ_Out, clang::Result, clang::AttributedType::stripOuterNullability(), and clang::Unspecified.
Referenced by AddObjCPassingTypeChunk(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), and FormatFunctionParameter().
formatTemplateParameterPlaceholder()
static std::string formatTemplateParameterPlaceholder (const NamedDecl * Param, bool & Optional, const PrintingPolicy & Policy) static
Definition at line 3800 of file SemaCodeComplete.cpp.
References clang::Result.
Referenced by createTemplateSignatureString().
getAsRecordDecl()
static RecordDecl * getAsRecordDecl (const QualType BaseType) static
Definition at line 5089 of file SemaCodeComplete.cpp.
References clang::TSK_Undeclared.
Referenced by clang::Sema::CodeCompleteDesignator(), clang::Sema::CodeCompleteMemberReferenceExpr(), getDesignatedType(), clang::QualType::hasNonTrivialToPrimitiveCopyCUnion(), clang::QualType::hasNonTrivialToPrimitiveDefaultInitializeCUnion(), and clang::QualType::hasNonTrivialToPrimitiveDestructCUnion().
GetAssumedMessageSendExprType()
static ObjCInterfaceDecl * GetAssumedMessageSendExprType (Expr * E) static
When we have an expression with type "id", we may assume that it has some more-specific class type based on knowledge of common uses of Objective-C.
This routine returns that class type, or NULL if no better result could be determined.
Definition at line 7655 of file SemaCodeComplete.cpp.
References clang::ObjCMessageExpr::Class, clang::Type::getAs(), clang::Selector::getIdentifierInfoForSlot(), clang::ObjCInterfaceDecl::getSuperClass(), Id, clang::ObjCMessageExpr::Instance, clang::Selector::isNull(), clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
Referenced by clang::Sema::CodeCompleteObjCInstanceMessage().
getCompletionPrintingPolicy() [1/2]
static PrintingPolicy getCompletionPrintingPolicy (const ASTContext & Context, const Preprocessor & PP) static
Definition at line 1897 of file SemaCodeComplete.cpp.
References clang::PrintingPolicy::AnonymousTagLocations, clang::PrintingPolicy::CleanUglifiedParameters, clang::Sema::getPrintingPolicy(), clang::PrintingPolicy::SuppressScope, clang::PrintingPolicy::SuppressStrongLifetime, and clang::PrintingPolicy::SuppressUnwrittenScope.
Referenced by AddObjCKeyValueCompletions(), AddObjCProperties(), AddOverrideResults(), AddSuperSendCompletion(), addThisCompletion(), clang::Sema::CodeCompleteConstructorInitializer(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCPropertySynthesizeIvar(), clang::CodeCompletionResult::CreateCodeCompletionString(), clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString(), getCompletionPrintingPolicy(), and MaybeAddOverrideCalls().
getCompletionPrintingPolicy() [2/2]
static PrintingPolicy getCompletionPrintingPolicy (Sema & S) static
Retrieve a printing policy suitable for code completion.
Definition at line 1909 of file SemaCodeComplete.cpp.
References clang::Sema::Context, getCompletionPrintingPolicy(), and clang::Sema::PP.
GetCompletionTypeString()
static const char * GetCompletionTypeString (QualType T, ASTContext & Context, const PrintingPolicy & Policy, CodeCompletionAllocator & Allocator) static
Retrieve the string representation of the given type as a string that has the appropriate lifetime for code completion.
This routine provides a fast path where we provide constant strings for common type names.
Definition at line 1918 of file SemaCodeComplete.cpp.
References clang::Result, clang::TTK_Class, clang::TTK_Enum, clang::TTK_Interface, clang::TTK_Struct, and clang::TTK_Union.
Referenced by AddObjCBlockCall(), AddObjCKeyValueCompletions(), AddObjCPassingTypeChunk(), AddResultTypeChunk(), addThisCompletion(), and clang::Sema::CodeCompleteObjCPropertySynthesizeIvar().
getConstructors()
static DeclContext::lookup_result getConstructors (ASTContext & Context, const CXXRecordDecl * Record) static
Definition at line 1042 of file SemaCodeComplete.cpp.
References clang::ASTContext::DeclarationNames, clang::ASTContext::getCanonicalType(), clang::DeclarationNameTable::getCXXConstructorName(), and clang::ASTContext::getTypeDeclType().
Referenced by clang::Sema::CodeCompleteConstructorInitializer().
getContainerDef()
static ObjCContainerDecl * getContainerDef (ObjCContainerDecl * Container) static
Retrieve the container definition, if any?
Definition at line 4812 of file SemaCodeComplete.cpp.
Referenced by AddObjCMethods(), AddObjCProperties(), and clang::Sema::CodeCompleteObjCPropertyDefinition().
GetDefaultValueString()
static std::string GetDefaultValueString (const ParmVarDecl * Param, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 2974 of file SemaCodeComplete.cpp.
References clang::Lexer::getSourceText(), clang::CharSourceRange::getTokenRange(), clang::Invalid, clang::CharSourceRange::isInvalid(), and SM.
Referenced by AddFunctionParameterChunks(), and AddOverloadParameterChunks().
getDesignatedType()
static QualType getDesignatedType (QualType BaseType, const Designation & Desig) static
Definition at line 6362 of file SemaCodeComplete.cpp.
References clang::Type::getAsArrayTypeUnsafe(), getAsRecordDecl(), clang::Designation::getDesignator(), clang::ArrayType::getElementType(), clang::Designation::getNumDesignators(), and clang::Member.
Referenced by clang::Sema::CodeCompleteDesignator(), and clang::PreferredTypeBuilder::enterDesignatedInitializer().
getNextAggregateIndexAfterDesignatedInit()
static llvm::Optional< unsigned > getNextAggregateIndexAfterDesignatedInit (const ResultCandidate & Aggregate, ArrayRef< Expr * > Args) static
Definition at line 6162 of file SemaCodeComplete.cpp.
References clang::CodeCompleteConsumer::OverloadCandidate::CK_Aggregate, clang::RecordDecl::fields(), clang::CodeCompleteConsumer::OverloadCandidate::getAggregate(), clang::CodeCompleteConsumer::OverloadCandidate::getKind(), clang::CodeCompleteConsumer::OverloadCandidate::getNumParams(), clang::CodeCompleteConsumer::OverloadCandidate::getParamDecl(), and clang::Invalid.
Referenced by clang::Sema::ProduceConstructorSignatureHelp().
getParamType()
static QualType getParamType (Sema & SemaRef, ArrayRef< ResultCandidate > Candidates, unsigned N) static
Get the type of the Nth parameter from a given set of overload candidates.
Definition at line 5965 of file SemaCodeComplete.cpp.
References clang::Sema::Context, clang::QualType::getNonReferenceType(), clang::ASTContext::hasSameUnqualifiedType(), clang::QualType::isNull(), and N.
Referenced by clang::CanProxyAdaptor< FunctionProtoType >::LLVM_CLANG_CANPROXY_SIMPLE_ACCESSOR(), and ProduceSignatureHelp().
getPreferredArgumentTypeForMessageSend()
static QualType getPreferredArgumentTypeForMessageSend (ResultBuilder & Results, unsigned NumSelIdents) static
Given a set of code-completion results for the argument of a message send, determine the preferred type (if any) for that argument expression.
Definition at line 7939 of file SemaCodeComplete.cpp.
References clang::cast(), clang::CCP_Unlikely, clang::ASTContext::hasSameUnqualifiedType(), clang::QualType::isNull(), N, and clang::Result.
Referenced by clang::Sema::CodeCompleteObjCClassMessage(), and clang::Sema::CodeCompleteObjCInstanceMessage().
getPreferredTypeOfBinaryRHS()
static QualType getPreferredTypeOfBinaryRHS (Sema & S, Expr * LHS, tok::TokenKind Op) static
Definition at line 446 of file SemaCodeComplete.cpp.
References clang::ASTContext::BoolTy, clang::Sema::getASTContext(), clang::ASTContext::getPointerDiffType(), clang::Expr::getType(), clang::ASTContext::IntTy, clang::Type::isIntegralOrEnumerationType(), and clang::Type::isPointerType().
Referenced by clang::PreferredTypeBuilder::enterBinary().
getPreferredTypeOfUnaryArg()
static QualType getPreferredTypeOfUnaryArg (Sema & S, QualType ContextType, tok::TokenKind Op) static
Get preferred type for an argument of an unary expression.
ContextType is preferred type of the whole unary expression.
Definition at line 525 of file SemaCodeComplete.cpp.
References clang::ASTContext::BoolTy, ContextType, clang::Sema::getASTContext(), clang::ASTContext::getPointerType(), and clang::ASTContext::IntTy.
Referenced by clang::PreferredTypeBuilder::enterUnary().
GetPrototypeLoc()
static FunctionProtoTypeLoc GetPrototypeLoc (Expr * Fn) static
Definition at line 6006 of file SemaCodeComplete.cpp.
References clang::Type::getAs(), clang::Expr::getType(), clang::QualType::getTypePtr(), P, and clang::Target.
Referenced by clang::Sema::ProduceCallSignatureHelp().
getRequiredQualification()
static NestedNameSpecifier * getRequiredQualification (ASTContext & Context, const DeclContext * CurContext, const DeclContext * TargetContext) static
Compute the qualification required to get from the current context (CurContext) to the target context (TargetContext).
Parameters
Context the AST context in which the qualification will be used.
CurContext the context where an entity is being named, which is typically based on the current scope.
TargetContext the context in which the named entity actually resides.
Returns
a nested name specifier that refers into the target context, or NULL if no qualification is needed.
Definition at line 711 of file SemaCodeComplete.cpp.
References clang::NestedNameSpecifier::Create(), clang::DeclContext::Encloses(), clang::ASTContext::getTypeDeclType(), clang::QualType::getTypePtr(), Parent, and clang::Result.
Referenced by AddEnumerators(), and MaybeAddOverrideCalls().
HandleCodeCompleteResults()
static void HandleCodeCompleteResults (Sema * S, CodeCompleteConsumer * CodeCompleter, CodeCompletionContext Context, CodeCompletionResult * Results, unsigned NumResults) static
Definition at line 4114 of file SemaCodeComplete.cpp.
References clang::CodeCompleteConsumer::ProcessCodeCompleteResults().
Referenced by clang::Sema::CodeCompleteAfterFunctionEquals(), clang::Sema::CodeCompleteAfterIf(), clang::Sema::CodeCompleteAttribute(), clang::Sema::CodeCompleteAvailabilityPlatformName(), clang::Sema::CodeCompleteCase(), clang::Sema::CodeCompleteConstructorInitializer(), clang::Sema::CodeCompleteDeclSpec(), clang::Sema::CodeCompleteDesignator(), clang::Sema::CodeCompleteExpression(), clang::Sema::CodeCompleteFunctionQualifiers(), clang::Sema::CodeCompleteIncludedFile(), clang::Sema::CodeCompleteLambdaIntroducer(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteModuleImport(), clang::Sema::CodeCompleteNamespaceAliasDecl(), clang::Sema::CodeCompleteNamespaceDecl(), clang::Sema::CodeCompleteNaturalLanguage(), clang::Sema::CodeCompleteObjCAtDirective(), clang::Sema::CodeCompleteObjCAtExpression(), clang::Sema::CodeCompleteObjCAtStatement(), clang::Sema::CodeCompleteObjCAtVisibility(), clang::Sema::CodeCompleteObjCClassMessage(), clang::Sema::CodeCompleteObjCClassPropertyRefExpr(), clang::Sema::CodeCompleteObjCImplementationCategory(), clang::Sema::CodeCompleteObjCImplementationDecl(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCInterfaceCategory(), clang::Sema::CodeCompleteObjCInterfaceDecl(), clang::Sema::CodeCompleteObjCMessageReceiver(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCMethodDeclSelector(), clang::Sema::CodeCompleteObjCPassingType(), clang::Sema::CodeCompleteObjCPropertyDefinition(), clang::Sema::CodeCompleteObjCPropertyFlags(), clang::Sema::CodeCompleteObjCPropertyGetter(), clang::Sema::CodeCompleteObjCPropertySetter(), clang::Sema::CodeCompleteObjCPropertySynthesizeIvar(), clang::Sema::CodeCompleteObjCProtocolDecl(), clang::Sema::CodeCompleteObjCProtocolReferences(), clang::Sema::CodeCompleteObjCSelector(), clang::Sema::CodeCompleteObjCSuperclass(), clang::Sema::CodeCompleteOperatorName(), clang::Sema::CodeCompleteOrdinaryName(), clang::Sema::CodeCompletePreprocessorDirective(), clang::Sema::CodeCompletePreprocessorExpression(), clang::Sema::CodeCompletePreprocessorMacroName(), clang::Sema::CodeCompleteQualifiedId(), clang::Sema::CodeCompleteTag(), clang::Sema::CodeCompleteTypeQualifiers(), clang::Sema::CodeCompleteUsing(), and clang::Sema::CodeCompleteUsingDirective().
InheritsFromClassNamed()
static bool InheritsFromClassNamed (ObjCInterfaceDecl * Class, StringRef Name) static
Determine whether the given class is or inherits from a class by the given name.
Definition at line 8771 of file SemaCodeComplete.cpp.
References InheritsFromClassNamed().
Referenced by AddObjCKeyValueCompletions(), and InheritsFromClassNamed().
isAcceptableObjCMethod()
static bool isAcceptableObjCMethod (ObjCMethodDecl * Method, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, bool AllowSameLength = true) static
Definition at line 7399 of file SemaCodeComplete.cpp.
References isAcceptableObjCSelector().
Referenced by AddClassMessageCompletions(), AddObjCMethods(), clang::Sema::CodeCompleteObjCInstanceMessage(), and clang::Sema::CodeCompleteObjCMethodDeclSelector().
isAcceptableObjCSelector()
static bool isAcceptableObjCSelector (Selector Sel, ObjCMethodKind WantKind, ArrayRef< IdentifierInfo * > SelIdents, bool AllowSameLength = true) static
Definition at line 7373 of file SemaCodeComplete.cpp.
References clang::Selector::getIdentifierInfoForSlot(), clang::Selector::getNumArgs(), clang::Selector::isUnarySelector(), MK_Any, MK_OneArgSelector, and MK_ZeroArgSelector.
Referenced by clang::Sema::CodeCompleteObjCSelector(), and isAcceptableObjCMethod().
isConstructor()
static bool isConstructor (const Decl * ND) static
Definition at line 1080 of file SemaCodeComplete.cpp.
References clang::isa().
Referenced by AddResultTypeChunk().
isNamespaceScope()
static bool isNamespaceScope (Scope * S) static
Determine whether this scope denotes a namespace.
Definition at line 6894 of file SemaCodeComplete.cpp.
References clang::DeclContext::isFileContext().
Referenced by clang::Sema::CodeCompleteLambdaIntroducer().
isObjCReceiverType()
static bool isObjCReceiverType (ASTContext & C, QualType T) static
Definition at line 1535 of file SemaCodeComplete.cpp.
References clang::C, and getKind().
mapCodeCompletionContext()
static CodeCompletionContext mapCodeCompletionContext (Sema & S, Sema::ParserCompletionContext PCC) static
Definition at line 4124 of file SemaCodeComplete.cpp.
References clang::ASTContext::BoolTy, clang::CodeCompletionContext::CCC_ClassStructUnion, clang::CodeCompletionContext::CCC_Expression, clang::CodeCompletionContext::CCC_ObjCImplementation, clang::CodeCompletionContext::CCC_ObjCInterface, clang::CodeCompletionContext::CCC_ObjCIvarList, clang::CodeCompletionContext::CCC_Other, clang::CodeCompletionContext::CCC_ParenthesizedExpression, clang::CodeCompletionContext::CCC_Recovery, clang::CodeCompletionContext::CCC_Statement, clang::CodeCompletionContext::CCC_TopLevel, clang::CodeCompletionContext::CCC_Type, clang::Sema::CurContext, clang::Sema::getASTContext(), clang::Sema::getLangOpts(), clang::DeclContext::isFileContext(), clang::DeclContext::isRecord(), clang::Sema::PCC_Class, clang::Sema::PCC_Condition, clang::Sema::PCC_Expression, clang::Sema::PCC_ForInit, clang::Sema::PCC_LocalDeclarationSpecifiers, clang::Sema::PCC_MemberTemplate, clang::Sema::PCC_Namespace, clang::Sema::PCC_ObjCImplementation, clang::Sema::PCC_ObjCInstanceVariableList, clang::Sema::PCC_ObjCInterface, clang::Sema::PCC_ParenthesizedExpression, clang::Sema::PCC_RecoveryInFunction, clang::Sema::PCC_Statement, clang::Sema::PCC_Template, and clang::Sema::PCC_Type.
Referenced by clang::Sema::CodeCompleteAfterIf(), and clang::Sema::CodeCompleteOrdinaryName().
MaybeAddOverrideCalls()
static void MaybeAddOverrideCalls (Sema & S, DeclContext * InContext, ResultBuilder & Results) static
If we're in a C++ virtual member function, add completion results that invoke the functions we override, since it's common to invoke the overridden function as well as adding new functionality.
Parameters
S The semantic analysis object for which we are generating results.
InContext This context in which the nested-name-specifier preceding the code-completion point
Definition at line 4189 of file SemaCodeComplete.cpp.
References clang::CCP_SuperCompletion, clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_RightParen, clang::Sema::Context, clang::Sema::CurContext, CXAvailability_Available, CXCursor_CXXMethod, clang::DeclContext::Equals(), getCompletionPrintingPolicy(), clang::DeclContext::getParent(), getRequiredQualification(), clang::CXXMethodDecl::overridden_methods(), P, and clang::NestedNameSpecifier::print().
Referenced by clang::Sema::CodeCompleteOrdinaryName(), and clang::Sema::CodeCompleteQualifiedId().
MaybeAddSentinel()
static void MaybeAddSentinel (Preprocessor & PP, const NamedDecl * FunctionOrMethod, CodeCompletionBuilder & Result) static
Definition at line 2717 of file SemaCodeComplete.cpp.
References clang::Decl::getAttr(), clang::Preprocessor::getLangOpts(), clang::Preprocessor::isMacroDefined(), and clang::Result.
Referenced by AddFunctionParameterChunks(), and clang::CodeCompletionResult::createCodeCompletionStringForDecl().
mergeCandidatesWithResults()
static void mergeCandidatesWithResults (Sema & SemaRef, SmallVectorImpl< ResultCandidate > & Results, OverloadCandidateSet & CandidateSet, SourceLocation Loc, size_t ArgSize) static
Definition at line 5932 of file SemaCodeComplete.cpp.
References clang::OverloadCandidateSet::getKind(), clang::isBetterOverloadCandidate(), clang::shouldEnforceArgLimit(), and X().
Referenced by clang::Sema::ProduceCallSignatureHelp(), and clang::Sema::ProduceConstructorSignatureHelp().
noUnderscoreAttrScope()
static const char * noUnderscoreAttrScope (llvm::StringRef Scope) static
Definition at line 4465 of file SemaCodeComplete.cpp.
Referenced by clang::Sema::CodeCompleteAttribute().
ObjCPropertyFlagConflicts()
static bool ObjCPropertyFlagConflicts (unsigned Attributes, unsigned NewFlag) static
Determine whether the addition of the given flag to an Objective-C property's attributes will cause a conflict.
Definition at line 7261 of file SemaCodeComplete.cpp.
References clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, and clang::ObjCPropertyAttribute::kind_weak.
Referenced by clang::Sema::CodeCompleteObjCPropertyFlags().
printOverrideString()
static void printOverrideString (const CodeCompletionString & CCS, std::string & BeforeName, std::string & NameAndSignature) static
Definition at line 3382 of file SemaCodeComplete.cpp.
References clang::CodeCompletionString::CK_Optional, clang::CodeCompletionString::CK_TypedText, and printOverrideString().
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForOverride(), and printOverrideString().
ProduceSignatureHelp()
static QualType ProduceSignatureHelp (Sema & SemaRef, MutableArrayRef< ResultCandidate > Candidates, unsigned CurrentArg, SourceLocation OpenParLoc, bool Braced) static
Definition at line 5991 of file SemaCodeComplete.cpp.
References clang::Sema::CodeCompleter, getParamType(), clang::Sema::getPreprocessor(), clang::Preprocessor::isCodeCompletionReached(), and clang::CodeCompleteConsumer::ProcessOverloadCandidates().
Referenced by clang::Sema::ProduceCallSignatureHelp(), clang::Sema::ProduceConstructorSignatureHelp(), and clang::Sema::ProduceTemplateArgumentSignatureHelp().
setInBaseClass()
static void setInBaseClass (ResultBuilder::Result & R) static
Definition at line 1207 of file SemaCodeComplete.cpp.
References clang::CCD_InBaseClass, clang::CodeCompletionResult::InBaseClass, and clang::CodeCompletionResult::Priority.
Referenced by AddObjCMethods(), AddObjCProperties(), and clang::Sema::CodeCompleteObjCMethodDecl().
shouldIgnoreDueToReservedName()
static bool shouldIgnoreDueToReservedName (const NamedDecl * ND, Sema & SemaRef) static
Definition at line 744 of file SemaCodeComplete.cpp.
References clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::SourceManager::getSpellingLoc(), clang::SourceManager::isInSystemHeader(), clang::SourceLocation::isInvalid(), clang::NamedDecl::isReserved(), clang::isReservedInAllContexts(), clang::Sema::SourceMgr, and clang::StartsWithDoubleUnderscore.
templateResultType()
static std::string templateResultType (const TemplateDecl * TD, const PrintingPolicy & Policy) static
Definition at line 3815 of file SemaCodeComplete.cpp.
Referenced by createTemplateSignatureString().
TryDeconstructFunctionLike()
static const FunctionProtoType * TryDeconstructFunctionLike (QualType T) static
Try to find a corresponding FunctionProtoType for function-like types (e.g.
function pointers, std::function, etc).
Definition at line 4654 of file SemaCodeComplete.cpp.
References clang::Type::getAs(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getKind(), clang::Specialization, and clang::TemplateArgument::Type.
Referenced by clang::Sema::CodeCompleteExpression().
underscoreAttrScope()
static const char * underscoreAttrScope (llvm::StringRef Scope) static
Definition at line 4457 of file SemaCodeComplete.cpp.
Referenced by clang::Sema::CodeCompleteAttribute().
WantTypesInContext()
static bool WantTypesInContext (Sema::ParserCompletionContext CCC, const LangOptions & LangOpts) static
Definition at line 1867 of file SemaCodeComplete.cpp.
References clang::Sema::PCC_Class, clang::Sema::PCC_Condition, clang::Sema::PCC_Expression, clang::Sema::PCC_ForInit, clang::Sema::PCC_LocalDeclarationSpecifiers, clang::Sema::PCC_MemberTemplate, clang::Sema::PCC_Namespace, clang::Sema::PCC_ObjCImplementation, clang::Sema::PCC_ObjCInstanceVariableList, clang::Sema::PCC_ObjCInterface, clang::Sema::PCC_ParenthesizedExpression, clang::Sema::PCC_RecoveryInFunction, clang::Sema::PCC_Statement, clang::Sema::PCC_Template, and clang::Sema::PCC_Type.
Referenced by AddOrdinaryNameResults(), clang::Sema::CodeCompleteExpression(), and clang::Sema::CodeCompleteOrdinaryName().