clang: lib/Sema/SemaPseudoObject.cpp File Reference
SemaPseudoObject.cpp File Reference
#include "clang/Sema/SemaInternal.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/ScopeInfo.h"
#include "llvm/ADT/SmallString.h"
Functions
static ObjCMethodDecl * LookupMethodInReceiverType (Sema &S, Selector sel, const ObjCPropertyRefExpr *PRE)
Look up a method in the receiver type of an Objective-C property reference.
static void CheckKeyForObjCARCConversion (Sema &S, QualType ContainerT, Expr *Key)
CheckKeyForObjCARCConversion - This routine suggests bridge casting of CF objects used as dictionary subscript key objects.
static Expr * stripOpaqueValuesFromPseudoObjectRef (Sema &S, Expr *E)
Given a pseudo-object reference, rebuild it without the opaque values.
Function Documentation
CheckKeyForObjCARCConversion()
static void CheckKeyForObjCARCConversion (Sema & S, QualType ContainerT, Expr * Key) static
CheckKeyForObjCARCConversion - This routine suggests bridge casting of CF objects used as dictionary subscript key objects.
Definition at line 1118 of file SemaPseudoObject.cpp.
References clang::Sema::CCK_ImplicitConversion, clang::Sema::CheckObjCConversion(), clang::Sema::Context, clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::Stmt::getSourceRange(), clang::ASTContext::Idents, clang::QualType::isNull(), clang::Sema::LookupMethodInObjectType(), clang::ObjCMethodDecl::parameters(), and clang::ASTContext::Selectors.
LookupMethodInReceiverType()
static ObjCMethodDecl * LookupMethodInReceiverType (Sema & S, Selector sel, const ObjCPropertyRefExpr * PRE) static
Look up a method in the receiver type of an Objective-C property reference.
Definition at line 547 of file SemaPseudoObject.cpp.
References clang::cast(), clang::Type::castAs(), clang::Sema::Context, clang::Sema::CurContext, clang::Type::getAs(), clang::ObjCPropertyRefExpr::getBase(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCPropertyRefExpr::getClassReceiver(), clang::DeclContext::getNonClosureAncestor(), clang::ASTContext::getObjCInterfaceType(), clang::ObjCObjectPointerType::getPointeeType(), clang::ObjCPropertyRefExpr::getSuperReceiverType(), clang::Expr::getType(), clang::ObjCPropertyRefExpr::isClassReceiver(), clang::ObjCObjectPointerType::isObjCClassType(), clang::ObjCPropertyRefExpr::isObjectReceiver(), clang::Sema::isSelfExpr(), clang::ObjCPropertyRefExpr::isSuperReceiver(), and clang::Sema::LookupMethodInObjectType().
stripOpaqueValuesFromPseudoObjectRef()
static Expr * stripOpaqueValuesFromPseudoObjectRef (Sema & S, Expr * E) static
Given a pseudo-object reference, rebuild it without the opaque values.
Basically, undo the behavior of rebuildAndCaptureObject. This should never operate in-place.
Definition at line 1624 of file SemaPseudoObject.cpp.
References clang::cast().
Referenced by clang::Sema::recreateSyntacticForm().