clang: lib/Sema/SemaAttr.cpp File Reference
SemaAttr.cpp File Reference
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Expr.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Basic/AttrSubMatchRulesList.inc"
Macros
#define ATTR_MATCH_RULE(Value, Spelling, IsAbstract)
#define ATTR_MATCH_SUB_RULE(Value, Spelling, IsAbstract, Parent, IsNegated)
#define ATTR_MATCH_RULE(Value, Spelling, IsAbstract)
#define ATTR_MATCH_SUB_RULE(Value, Spelling, IsAbstract, Parent, IsNegated)
Typedefs
typedef std::vector< std::pair< unsigned, SourceLocation > > VisStack
Enumerations
enum : unsigned { NoVisibility = ~0U }
Functions
template<typename Attribute >
static void addGslOwnerPointerAttributeIfNotExisting (ASTContext &Context, CXXRecordDecl *Record)
static void PushPragmaVisibility (Sema &S, unsigned type, SourceLocation loc)
template<typename Ty >
static bool checkCommonAttributeFeatures (Sema &S, const Ty *Node, const ParsedAttr &A, bool SkipArgCountCheck)
Macro Definition Documentation
ATTR_MATCH_RULE [1/2]
#define ATTR_MATCH_RULE (Value, Spelling, IsAbstract)
ATTR_MATCH_RULE [2/2]
#define ATTR_MATCH_RULE (Value, Spelling, IsAbstract)
ATTR_MATCH_SUB_RULE [1/2]
#define ATTR_MATCH_SUB_RULE (Value, Spelling, IsAbstract, Parent, IsNegated)
Value:
  case Value:                                                                  \
    return Parent;
ATTR_MATCH_SUB_RULE [2/2]
#define ATTR_MATCH_SUB_RULE (Value, Spelling, IsAbstract, Parent, IsNegated)
Value:
  case Value:                                                                  \
    return IsNegated;
Typedef Documentation
VisStack
typedef std::vector<std::pair<unsigned, SourceLocation> > VisStack
Definition at line 1222 of file SemaAttr.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
NoVisibility
Definition at line 1223 of file SemaAttr.cpp.
Function Documentation
addGslOwnerPointerAttributeIfNotExisting()
template<typename Attribute > static void addGslOwnerPointerAttributeIfNotExisting (ASTContext & Context, CXXRecordDecl * Record) static
Definition at line 99 of file SemaAttr.cpp.
References clang::Sema::Context.
Referenced by clang::Sema::inferGslOwnerPointerAttribute(), and clang::Sema::inferGslPointerAttribute().
checkCommonAttributeFeatures()
template<typename Ty > static bool checkCommonAttributeFeatures (Sema & S, const Ty * Node, const ParsedAttr & A, bool SkipArgCountCheck) static
Definition at line 1396 of file SemaAttr.cpp.
References clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), clang::Sema::CheckAttrTarget(), clang::ParsedAttr::checkExactlyNumArgs(), clang::ParsedAttr::diagnoseAppertainsTo(), clang::ParsedAttr::diagnoseLangOpts(), clang::ParsedAttr::diagnoseMutualExclusion(), clang::ParsedAttr::getKind(), clang::ParsedAttr::getMaxArgs(), clang::ParsedAttr::getMinArgs(), clang::ParsedAttr::hasCustomParsing(), clang::ParsedAttr::hasVariadicArg(), Node, and clang::AttributeCommonInfo::UnknownAttribute.
PushPragmaVisibility()
static void PushPragmaVisibility (Sema & S, unsigned type, SourceLocation loc) static
Definition at line 1250 of file SemaAttr.cpp.
References clang::Sema::VisContext.
Referenced by clang::Sema::ActOnPragmaVisibility(), and clang::Sema::PushNamespaceVisibilityAttr().