clang: clang::tooling::dependencies::ModuleDeps Struct Reference
clang::tooling::dependencies::ModuleDeps Struct Reference
#include "clang/Tooling/DependencyScanning/ModuleDepCollector.h"
Public Member Functions
std::vector< std::string > getCanonicalCommandLine (llvm::function_ref< std::string(const ModuleID &, ModuleOutputKind)> LookupModuleOutput) const
Gets the canonical command line suitable for passing to clang.
std::vector< std::string > getCanonicalCommandLineWithoutModulePaths () const
Gets the canonical command line suitable for passing to clang, excluding "-fmodule-file=" and "-o" arguments.
Public Attributes
ModuleID ID
The identifier of the module.
bool IsSystem
Whether this is a "system" module.
std::string ClangModuleMapFile
The path to the modulemap file which defines this module.
std::string ImplicitModulePCMPath
The path to where an implicit build would put the PCM for this module.
llvm::StringSet FileDeps
A collection of absolute paths to files that this module directly depends on, not including transitive dependencies.
std::vector< std::string > ModuleMapFileDeps
A collection of absolute paths to module map files that this module needs to know about.
std::vector< PrebuiltModuleDep > PrebuiltModuleDeps
A collection of prebuilt modular dependencies this module directly depends on, not including transitive dependencies.
std::vector< ModuleID > ClangModuleDeps
A list of module identifiers this module directly depends on, not including transitive dependencies.
bool ImportedByMainFile = false
bool HadDependencyFile = false
Whether the TU had a dependency file.
bool HadSerializedDiagnostics = false
Whether the TU had serialized diagnostics.
CompilerInvocation BuildInvocation
Compiler invocation that can be used to build this module (without paths).
Detailed Description
Definition at line 81 of file ModuleDepCollector.h.
Member Function Documentation
getCanonicalCommandLine()
std::vector< std::string > ModuleDeps::getCanonicalCommandLine (llvm::function_ref< std::string(const ModuleID &, ModuleOutputKind)> LookupModuleOutput) const
Gets the canonical command line suitable for passing to clang.
Parameters
LookupModuleOutput This function is called to fill in "-fmodule-file=", "-o" and other output arguments.
Definition at line 124 of file ModuleDepCollector.cpp.
References BuildInvocation, ClangModuleDeps, ClangModuleMapFile, clang::FrontendOptions::DashX, clang::tooling::dependencies::DependencyFile, clang::tooling::dependencies::DependencyTargets, clang::DiagnosticOptions::DiagnosticSerializationFile, clang::tooling::dependencies::DiagnosticSerializationFile, clang::CompilerInvocationValueBase::getDependencyOutputOpts(), clang::CompilerInvocationRefBase::getDiagnosticOpts(), clang::CompilerInvocationValueBase::getFrontendOpts(), clang::InputKind::getLanguage(), HadDependencyFile, HadSerializedDiagnostics, clang::FrontendOptions::Inputs, clang::tooling::dependencies::ModuleFile, clang::FrontendOptions::ModuleFiles, clang::InputKind::ModuleMap, clang::DependencyOutputOptions::OutputFile, clang::FrontendOptions::OutputFile, clang::quoteMakeTarget(), serializeCompilerInvocation(), splitString(), clang::Target, and clang::DependencyOutputOptions::Targets.
getCanonicalCommandLineWithoutModulePaths()
std::vector< std::string > ModuleDeps::getCanonicalCommandLineWithoutModulePaths () const
Gets the canonical command line suitable for passing to clang, excluding "-fmodule-file=" and "-o" arguments.
Definition at line 160 of file ModuleDepCollector.cpp.
References BuildInvocation, and serializeCompilerInvocation().
Member Data Documentation
BuildInvocation
CompilerInvocation clang::tooling::dependencies::ModuleDeps::BuildInvocation
Compiler invocation that can be used to build this module (without paths).
Definition at line 129 of file ModuleDepCollector.h.
Referenced by getCanonicalCommandLine(), and getCanonicalCommandLineWithoutModulePaths().
ClangModuleDeps
std::vector<ModuleID> clang::tooling::dependencies::ModuleDeps::ClangModuleDeps
A list of module identifiers this module directly depends on, not including transitive dependencies.
This may include modules with a different context hash when it can be determined that the differences are benign for this compilation.
Definition at line 114 of file ModuleDepCollector.h.
Referenced by getCanonicalCommandLine().
ClangModuleMapFile
std::string clang::tooling::dependencies::ModuleDeps::ClangModuleMapFile
The path to the modulemap file which defines this module.
This can be used to explicitly build this module. This file will additionally appear in FileDeps as a dependency.
Definition at line 92 of file ModuleDepCollector.h.
Referenced by getCanonicalCommandLine().
FileDeps
llvm::StringSet clang::tooling::dependencies::ModuleDeps::FileDeps
A collection of absolute paths to files that this module directly depends on, not including transitive dependencies.
Definition at line 99 of file ModuleDepCollector.h.
HadDependencyFile
bool clang::tooling::dependencies::ModuleDeps::HadDependencyFile = false
Whether the TU had a dependency file.
The path in BuildInvocation is cleared to avoid leaking the specific path from the TU into the module.
Definition at line 122 of file ModuleDepCollector.h.
Referenced by getCanonicalCommandLine().
HadSerializedDiagnostics
bool clang::tooling::dependencies::ModuleDeps::HadSerializedDiagnostics = false
Whether the TU had serialized diagnostics.
The path in BuildInvocation is cleared to avoid leaking the specific path from the TU into the module.
Definition at line 126 of file ModuleDepCollector.h.
Referenced by getCanonicalCommandLine().
ID
ModuleID clang::tooling::dependencies::ModuleDeps::ID
The identifier of the module.
Definition at line 83 of file ModuleDepCollector.h.
Referenced by clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
ImplicitModulePCMPath
std::string clang::tooling::dependencies::ModuleDeps::ImplicitModulePCMPath
The path to where an implicit build would put the PCM for this module.
Definition at line 95 of file ModuleDepCollector.h.
ImportedByMainFile
bool clang::tooling::dependencies::ModuleDeps::ImportedByMainFile = false
Definition at line 118 of file ModuleDepCollector.h.
Referenced by clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
IsSystem
bool clang::tooling::dependencies::ModuleDeps::IsSystem
Whether this is a "system" module.
Definition at line 86 of file ModuleDepCollector.h.
ModuleMapFileDeps
std::vector<std::string> clang::tooling::dependencies::ModuleDeps::ModuleMapFileDeps
A collection of absolute paths to module map files that this module needs to know about.
Definition at line 103 of file ModuleDepCollector.h.
PrebuiltModuleDeps
std::vector<PrebuiltModuleDep> clang::tooling::dependencies::ModuleDeps::PrebuiltModuleDeps
A collection of prebuilt modular dependencies this module directly depends on, not including transitive dependencies.
Definition at line 107 of file ModuleDepCollector.h.
The documentation for this struct was generated from the following files:
include/clang/Tooling/DependencyScanning/ModuleDepCollector.h
lib/Tooling/DependencyScanning/ModuleDepCollector.cpp