clang: clang::XRayInstrSet Struct Reference
clang::XRayInstrSet Struct Reference
#include "clang/Basic/XRayInstr.h"
Public Member Functions
bool has (XRayInstrMask K) const
bool hasOneOf (XRayInstrMask K) const
void set (XRayInstrMask K, bool Value)
void clear (XRayInstrMask K=XRayInstrKind::All)
bool empty () const
bool full () const
Public Attributes
XRayInstrMask Mask = 0
Detailed Description
Definition at line 47 of file XRayInstr.h.
Member Function Documentation
clear()
void clang::XRayInstrSet::clear (XRayInstrMask K = XRayInstrKind::All) inline
Definition at line 59 of file XRayInstr.h.
References Mask.
Referenced by clang::driver::XRayArgs::XRayArgs().
empty()
bool clang::XRayInstrSet::empty () const inline
Definition at line 61 of file XRayInstr.h.
References Mask.
Referenced by clang::driver::XRayArgs::addArgs().
full()
bool clang::XRayInstrSet::full () const inline
Definition at line 63 of file XRayInstr.h.
References clang::XRayInstrKind::All, and Mask.
Referenced by clang::driver::XRayArgs::addArgs().
has()
bool clang::XRayInstrSet::has (XRayInstrMask K) const inline
Definition at line 48 of file XRayInstr.h.
References Mask.
Referenced by clang::driver::XRayArgs::addArgs(), and clang::serializeXRayInstrValue().
hasOneOf()
bool clang::XRayInstrSet::hasOneOf (XRayInstrMask K) const inline
Definition at line 53 of file XRayInstr.h.
References Mask.
set()
void clang::XRayInstrSet::set (XRayInstrMask K, bool Value) inline
Definition at line 55 of file XRayInstr.h.
References Mask.
Member Data Documentation
Mask
XRayInstrMask clang::XRayInstrSet::Mask = 0
Definition at line 65 of file XRayInstr.h.
Referenced by clear(), empty(), full(), has(), hasOneOf(), clang::serializeXRayInstrValue(), set(), and clang::driver::XRayArgs::XRayArgs().
The documentation for this struct was generated from the following file:
include/clang/Basic/XRayInstr.h