clang: clang::FilenamePatternConstraint Struct Reference
clang::FilenamePatternConstraint Struct Reference
#include "clang/Analysis/CloneDetection.h"
Public Member Functions
FilenamePatternConstraint (StringRef IgnoredFilesPattern)
bool isAutoGenerated (const CloneDetector::CloneGroup &Group)
void constrain (std::vector< CloneDetector::CloneGroup > &CloneGroups)
Public Attributes
StringRef IgnoredFilesPattern
std::shared_ptr< llvm::Regex > IgnoredFilesRegex
Detailed Description
Definition at line 322 of file CloneDetection.h.
Constructor & Destructor Documentation
FilenamePatternConstraint()
clang::FilenamePatternConstraint::FilenamePatternConstraint (StringRef IgnoredFilesPattern) inline
Definition at line 326 of file CloneDetection.h.
References IgnoredFilesPattern, and IgnoredFilesRegex.
Member Function Documentation
constrain()
void clang::FilenamePatternConstraint::constrain (std::vector< CloneDetector::CloneGroup > & CloneGroups) inline
Definition at line 334 of file CloneDetection.h.
References clang::CloneConstraint::filterGroups(), and isAutoGenerated().
isAutoGenerated()
bool FilenamePatternConstraint::isAutoGenerated (const CloneDetector::CloneGroup & Group)
Definition at line 154 of file CloneDetection.cpp.
References Filename, clang::Sema::getASTContext(), clang::ASTContext::getSourceManager(), IgnoredFilesPattern, IgnoredFilesRegex, and SM.
Referenced by constrain().
Member Data Documentation
IgnoredFilesPattern
StringRef clang::FilenamePatternConstraint::IgnoredFilesPattern
Definition at line 323 of file CloneDetection.h.
Referenced by FilenamePatternConstraint(), and isAutoGenerated().
IgnoredFilesRegex
std::shared_ptr<llvm::Regex> clang::FilenamePatternConstraint::IgnoredFilesRegex
Definition at line 324 of file CloneDetection.h.
Referenced by FilenamePatternConstraint(), and isAutoGenerated().
The documentation for this struct was generated from the following files:
include/clang/Analysis/CloneDetection.h
lib/Analysis/CloneDetection.cpp