clang: clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers Struct Reference
clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers Struct Reference
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Classes
class InlinedRegionBodyRAII
RAII for preserving necessary info during inlined region body codegen.
class OMPAllocateCleanupTy
Cleanup action for allocate support.
class OutlinedRegionBodyRAII
RAII for preserving necessary info during Outlined region body codegen.
Public Types
using InsertPointTy = llvm::OpenMPIRBuilder::InsertPointTy
Public Member Functions
OMPBuilderCBHelpers ()=delete
OMPBuilderCBHelpers (const OMPBuilderCBHelpers &)=delete
OMPBuilderCBHelpers & operator= (const OMPBuilderCBHelpers &)=delete
Static Public Member Functions
static Address getAddrOfThreadPrivate (CodeGenFunction &CGF, const VarDecl *VD, Address VDAddr, SourceLocation Loc)
Returns address of the threadprivate variable for the current thread.
static Address getAddressOfLocalVariable (CodeGenFunction &CGF, const VarDecl *VD)
Gets the OpenMP-specific address of the local variable /p VD.
static std::string getNameWithSeparators (ArrayRef< StringRef > Parts, StringRef FirstSeparator=".", StringRef Separator=".")
Get the platform-specific name separator.
static void FinalizeOMPRegion (CodeGenFunction &CGF, InsertPointTy IP)
Emit the Finalization for an OMP region.
static void EmitOMPInlinedRegionBody (CodeGenFunction &CGF, const Stmt *RegionBodyStmt, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Twine RegionName)
Emit the body of an OMP region.
static void EmitCaptureStmt (CodeGenFunction &CGF, InsertPointTy CodeGenIP, llvm::BasicBlock &FiniBB, llvm::Function *Fn, ArrayRef< llvm::Value * > Args)
static void EmitOMPOutlinedRegionBody (CodeGenFunction &CGF, const Stmt *RegionBodyStmt, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Twine RegionName)
Emit the body of an OMP region that will be outlined in OpenMPIRBuilder::finalize().
Detailed Description
Definition at line 1728 of file CodeGenFunction.h.
Member Typedef Documentation
InsertPointTy
using clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::InsertPointTy = llvm::OpenMPIRBuilder::InsertPointTy
Definition at line 1734 of file CodeGenFunction.h.
Constructor & Destructor Documentation
OMPBuilderCBHelpers() [1/2]
clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OMPBuilderCBHelpers () delete
OMPBuilderCBHelpers() [2/2]
clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OMPBuilderCBHelpers (const OMPBuilderCBHelpers &) delete
Member Function Documentation
EmitCaptureStmt()
static void clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::EmitCaptureStmt (CodeGenFunction & CGF, InsertPointTy CodeGenIP, llvm::BasicBlock & FiniBB, llvm::Function * Fn, ArrayRef< llvm::Value * > Args) inline static
Definition at line 1808 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), and clang::CodeGen::CodeGenFunction::EmitRuntimeCall().
EmitOMPInlinedRegionBody()
void CodeGenFunction::OMPBuilderCBHelpers::EmitOMPInlinedRegionBody (CodeGenFunction & CGF, const Stmt * RegionBodyStmt, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Twine RegionName) static
Emit the body of an OMP region.
Parameters
CGF The Codegen function this belongs to
RegionBodyStmt The body statement for the OpenMP region being generated
AllocaIP Where to insert alloca instructions
CodeGenIP Where to insert the region code
RegionName Name to be used for new blocks
Definition at line 1681 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenFunction::EmitStmt().
EmitOMPOutlinedRegionBody()
void CodeGenFunction::OMPBuilderCBHelpers::EmitOMPOutlinedRegionBody (CodeGenFunction & CGF, const Stmt * RegionBodyStmt, InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Twine RegionName) static
Emit the body of an OMP region that will be outlined in OpenMPIRBuilder::finalize().
Parameters
CGF The Codegen function this belongs to
RegionBodyStmt The body statement for the OpenMP region being generated
AllocaIP Where to insert alloca instructions
CodeGenIP Where to insert the region code
RegionName Name to be used for new blocks
Definition at line 1698 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenFunction::EmitStmt().
FinalizeOMPRegion()
static void clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::FinalizeOMPRegion (CodeGenFunction & CGF, InsertPointTy IP) inline static
Emit the Finalization for an OMP region.
Parameters
CGF The Codegen function this belongs to
IP Insertion point for generating the finalization code.
Definition at line 1779 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitBranchThroughCleanup(), and clang::CodeGen::CodeGenFunction::getJumpDestInCurrentScope().
getAddressOfLocalVariable()
Address CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable (CodeGenFunction & CGF, const VarDecl * VD) static
Gets the OpenMP-specific address of the local variable /p VD.
Definition at line 1596 of file CGStmtOpenMP.cpp.
References clang::CharUnits::alignTo(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CharUnits::fromQuantity(), clang::Decl::getAttr(), clang::VarDecl::getCanonicalDecl(), clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getDeclAlign(), clang::NamedDecl::getName(), getNameWithSeparators(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::ASTContext::getPointerType(), clang::CodeGen::CodeGenModule::getSize(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypeSize(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::Address::invalid(), isAllocatableDecl(), clang::Type::isVariablyModifiedType(), clang::CodeGen::NormalAndEHCleanup, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
getAddrOfThreadPrivate()
Address CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate (CodeGenFunction & CGF, const VarDecl * VD, Address VDAddr, SourceLocation Loc) static
Returns address of the threadprivate variable for the current thread.
This Also create any necessary OMP runtime calls.
Parameters
VD VarDecl for Threadprivate variable.
VDAddr Address of the Vardecl
Loc The location where the barrier directive was encountered
Definition at line 1646 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getMangledName(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getSize(), clang::ASTContext::getTargetInfo(), clang::CodeGen::CodeGenModule::GetTargetTypeStoreSize(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::TargetInfo::isTLSSupported().
Referenced by EmitThreadPrivateVarDeclLValue().
getNameWithSeparators()
std::string CodeGenFunction::OMPBuilderCBHelpers::getNameWithSeparators (ArrayRef< StringRef > Parts, StringRef FirstSeparator = ".", StringRef Separator = ".") static
Get the platform-specific name separator.
Parameters
Parts different parts of the final name that needs separation
FirstSeparator First separator used between the initial two parts of the name.
Separator separator used between all of the rest consecutinve parts of the name
Definition at line 1669 of file CGStmtOpenMP.cpp.
Referenced by getAddressOfLocalVariable().
operator=()
OMPBuilderCBHelpers & clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::operator= (const OMPBuilderCBHelpers &) delete
The documentation for this struct was generated from the following files:
lib/CodeGen/CodeGenFunction.h
lib/CodeGen/CGStmtOpenMP.cpp