clang: clang::serialization::PPEntityOffset Struct Reference
clang::serialization::PPEntityOffset Struct Reference
Source range/offset of a preprocessed entity.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
PPEntityOffset (SourceRange R, uint32_t BitOffset)
SourceLocation getBegin () const
SourceLocation getEnd () const
Public Attributes
SourceLocation::UIntTy Begin
Raw source location of beginning of range.
SourceLocation::UIntTy End
Raw source location of end of range.
uint32_t BitOffset
Offset in the AST file relative to ModuleFile::MacroOffsetsBase.
Detailed Description
Source range/offset of a preprocessed entity.
Definition at line 177 of file ASTBitCodes.h.
Constructor & Destructor Documentation
PPEntityOffset()
clang::serialization::PPEntityOffset::PPEntityOffset (SourceRange R, uint32_t BitOffset) inline
Definition at line 187 of file ASTBitCodes.h.
Member Function Documentation
getBegin()
SourceLocation clang::serialization::PPEntityOffset::getBegin () const inline
Definition at line 191 of file ASTBitCodes.h.
References Begin, and clang::SourceLocation::getFromRawEncoding().
Referenced by clang::ASTReader::isPreprocessedEntityInFileID(), and clang::ASTReader::ReadPreprocessedEntity().
getEnd()
SourceLocation clang::serialization::PPEntityOffset::getEnd () const inline
Definition at line 195 of file ASTBitCodes.h.
References End, and clang::SourceLocation::getFromRawEncoding().
Referenced by clang::ASTReader::ReadPreprocessedEntity().
Member Data Documentation
Begin
SourceLocation::UIntTy clang::serialization::PPEntityOffset::Begin
Raw source location of beginning of range.
Definition at line 179 of file ASTBitCodes.h.
Referenced by getBegin().
BitOffset
uint32_t clang::serialization::PPEntityOffset::BitOffset
Offset in the AST file relative to ModuleFile::MacroOffsetsBase.
Definition at line 185 of file ASTBitCodes.h.
Referenced by clang::ASTReader::ReadPreprocessedEntity().
End
SourceLocation::UIntTy clang::serialization::PPEntityOffset::End
Raw source location of end of range.
Definition at line 182 of file ASTBitCodes.h.
Referenced by getEnd().
The documentation for this struct was generated from the following file:
include/clang/Serialization/ASTBitCodes.h