clang: clang::AmbiguousConversionSequence Struct Reference
clang::AmbiguousConversionSequence Struct Reference
Represents an ambiguous user-defined conversion sequence.
#include "clang/Sema/Overload.h"
Public Types
using ConversionSet
using iterator = ConversionSet::iterator
using const_iterator = ConversionSet::const_iterator
Public Member Functions
QualType getFromType () const
QualType getToType () const
void setFromType (QualType T)
void setToType (QualType T)
ConversionSet & conversions ()
const ConversionSet & conversions () const
void addConversion (NamedDecl *Found, FunctionDecl *D)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void construct ()
void destruct ()
void copyFrom (const AmbiguousConversionSequence &)
Public Attributes
void * FromTypePtr
void * ToTypePtr
char Buffer [sizeof(ConversionSet)]
Detailed Description
Represents an ambiguous user-defined conversion sequence.
Definition at line 418 of file Overload.h.
Member Typedef Documentation
const_iterator
using clang::AmbiguousConversionSequence::const_iterator = ConversionSet::const_iterator
Definition at line 454 of file Overload.h.
ConversionSet
using clang::AmbiguousConversionSequence::ConversionSet
Initial value:
        SmallVector<std::pair<NamedDecl *, FunctionDecl *>, 4>
Definition at line 419 of file Overload.h.
iterator
using clang::AmbiguousConversionSequence::iterator = ConversionSet::iterator
Definition at line 449 of file Overload.h.
Member Function Documentation
addConversion()
void clang::AmbiguousConversionSequence::addConversion (NamedDecl * Found, FunctionDecl * D) inline
Definition at line 445 of file Overload.h.
References conversions().
Referenced by FindConversionForRefInit(), and TryUserDefinedConversion().
begin() [1/2]
iterator clang::AmbiguousConversionSequence::begin () inline
Definition at line 451 of file Overload.h.
References conversions().
begin() [2/2]
const_iterator clang::AmbiguousConversionSequence::begin () const inline
Definition at line 456 of file Overload.h.
References conversions().
construct()
void AmbiguousConversionSequence::construct ()
Definition at line 568 of file SemaOverload.cpp.
References conversions().
Referenced by clang::ImplicitConversionSequence::setAmbiguous().
conversions() [1/2]
ConversionSet & clang::AmbiguousConversionSequence::conversions () inline
Definition at line 437 of file Overload.h.
References Buffer.
Referenced by addConversion(), begin(), begin(), construct(), copyFrom(), destruct(), end(), and end().
conversions() [2/2]
const ConversionSet & clang::AmbiguousConversionSequence::conversions () const inline
Definition at line 441 of file Overload.h.
References Buffer.
copyFrom()
void AmbiguousConversionSequence::copyFrom (const AmbiguousConversionSequence & O)
Definition at line 577 of file SemaOverload.cpp.
References conversions(), FromTypePtr, and ToTypePtr.
Referenced by clang::ImplicitConversionSequence::ImplicitConversionSequence().
destruct()
void AmbiguousConversionSequence::destruct ()
Definition at line 572 of file SemaOverload.cpp.
References conversions().
end() [1/2]
iterator clang::AmbiguousConversionSequence::end () inline
Definition at line 452 of file Overload.h.
References conversions().
end() [2/2]
const_iterator clang::AmbiguousConversionSequence::end () const inline
Definition at line 457 of file Overload.h.
References conversions().
getFromType()
QualType clang::AmbiguousConversionSequence::getFromType () const inline
Definition at line 426 of file Overload.h.
References FromTypePtr, and clang::QualType::getFromOpaquePtr().
getToType()
QualType clang::AmbiguousConversionSequence::getToType () const inline
Definition at line 430 of file Overload.h.
References clang::QualType::getFromOpaquePtr(), and ToTypePtr.
setFromType()
void clang::AmbiguousConversionSequence::setFromType (QualType T) inline
Definition at line 434 of file Overload.h.
References FromTypePtr.
Referenced by TryUserDefinedConversion().
setToType()
void clang::AmbiguousConversionSequence::setToType (QualType T) inline
Definition at line 435 of file Overload.h.
References ToTypePtr.
Referenced by TryUserDefinedConversion().
Member Data Documentation
Buffer
char clang::AmbiguousConversionSequence::Buffer[sizeof(ConversionSet)]
Definition at line 424 of file Overload.h.
Referenced by conversions(), and conversions().
FromTypePtr
void* clang::AmbiguousConversionSequence::FromTypePtr
Definition at line 422 of file Overload.h.
Referenced by copyFrom(), getFromType(), and setFromType().
ToTypePtr
void* clang::AmbiguousConversionSequence::ToTypePtr
Definition at line 423 of file Overload.h.
Referenced by copyFrom(), getToType(), and setToType().
The documentation for this struct was generated from the following files:
include/clang/Sema/Overload.h
lib/Sema/SemaOverload.cpp