clang: clang::LazyGenerationalUpdatePtr< Owner, T, Update > Struct Template Reference
clang::LazyGenerationalUpdatePtr< Owner, T, Update > Struct Template Reference
A lazy value (of type T) that is within an AST node of type Owner, where the value might change in later generations of the external AST source.
#include "clang/AST/ExternalASTSource.h"
Classes
struct LazyData
A cache of the value of this pointer, in the most recent generation in which we queried it.
Public Types
enum NotUpdatedTag { NotUpdated }
Create a pointer that is not potentially updated by later generations of the external AST source.
using ValueType = llvm::PointerUnion<T, LazyData*>
Public Member Functions
LazyGenerationalUpdatePtr (ValueType V)
LazyGenerationalUpdatePtr (const ASTContext &Ctx, T Value=T())
LazyGenerationalUpdatePtr (NotUpdatedTag, T Value=T())
void markIncomplete ()
Forcibly set this pointer (which must be lazy) as needing updates.
void set (T NewValue)
Set the value of this pointer, in the current generation.
void setNotUpdated (T NewValue)
Set the value of this pointer, for this and all future generations.
T get (Owner O)
Get the value of this pointer, updating its owner if necessary.
T getNotUpdated () const
Get the most recently computed value of this pointer without updating it.
void * getOpaqueValue ()
Static Public Member Functions
static ValueType makeValue (const ASTContext &Ctx, T Value)
Create the representation of a LazyGenerationalUpdatePtr.
static LazyGenerationalUpdatePtr getFromOpaqueValue (void *Ptr)
Public Attributes
ValueType Value
Detailed Description
template<typename Owner, typename T, void(ExternalASTSource::*)(Owner) Update>
struct clang::LazyGenerationalUpdatePtr< Owner, T, Update >
A lazy value (of type T) that is within an AST node of type Owner, where the value might change in later generations of the external AST source.
Definition at line 388 of file ExternalASTSource.h.
Member Typedef Documentation
ValueType
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> using clang::LazyGenerationalUpdatePtr< Owner, T, Update >::ValueType = llvm::PointerUnion<T, LazyData*>
Definition at line 401 of file ExternalASTSource.h.
Member Enumeration Documentation
NotUpdatedTag
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> enum clang::LazyGenerationalUpdatePtr::NotUpdatedTag
Create a pointer that is not potentially updated by later generations of the external AST source.
Enumerator
NotUpdated
Definition at line 415 of file ExternalASTSource.h.
Constructor & Destructor Documentation
LazyGenerationalUpdatePtr() [1/3]
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> clang::LazyGenerationalUpdatePtr< Owner, T, Update >::LazyGenerationalUpdatePtr (ValueType V) inline
Definition at line 404 of file ExternalASTSource.h.
Referenced by clang::LazyGenerationalUpdatePtr< Owner, T, Update >::getFromOpaqueValue().
LazyGenerationalUpdatePtr() [2/3]
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> clang::LazyGenerationalUpdatePtr< Owner, T, Update >::LazyGenerationalUpdatePtr (const ASTContext & Ctx, T Value = T()) inline explicit
Definition at line 410 of file ExternalASTSource.h.
LazyGenerationalUpdatePtr() [3/3]
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> clang::LazyGenerationalUpdatePtr< Owner, T, Update >::LazyGenerationalUpdatePtr (NotUpdatedTag , T Value = T()) inline
Definition at line 416 of file ExternalASTSource.h.
Member Function Documentation
get()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> T clang::LazyGenerationalUpdatePtr< Owner, T, Update >::get (Owner O) inline
Get the value of this pointer, updating its owner if necessary.
Definition at line 437 of file ExternalASTSource.h.
References clang::LazyGenerationalUpdatePtr< Owner, T, Update >::get().
Referenced by clang::LazyGenerationalUpdatePtr< Owner, T, Update >::get(), clang::LazyGenerationalUpdatePtr< Owner, T, Update >::getNotUpdated(), clang::Redeclarable< decl_type >::DeclLink::getPrevious(), and clang::LazyGenerationalUpdatePtr< Owner, T, Update >::markIncomplete().
getFromOpaqueValue()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> static LazyGenerationalUpdatePtr clang::LazyGenerationalUpdatePtr< Owner, T, Update >::getFromOpaqueValue (void * Ptr) inline static
Definition at line 456 of file ExternalASTSource.h.
References clang::LazyGenerationalUpdatePtr< Owner, T, Update >::LazyGenerationalUpdatePtr().
getNotUpdated()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> T clang::LazyGenerationalUpdatePtr< Owner, T, Update >::getNotUpdated () const inline
Get the most recently computed value of this pointer without updating it.
Definition at line 449 of file ExternalASTSource.h.
References clang::LazyGenerationalUpdatePtr< Owner, T, Update >::get().
getOpaqueValue()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> void * clang::LazyGenerationalUpdatePtr< Owner, T, Update >::getOpaqueValue () inline
Definition at line 455 of file ExternalASTSource.h.
makeValue()
template<typename Owner , typename T , void(clang::ExternalASTSource::*)(Owner) Update> template clang::LazyGenerationalUpdatePtr< constDecl *, Decl *,&ExternalASTSource::CompleteRedeclChain >::ValueType clang::LazyGenerationalUpdatePtr< Owner, T, Update >::makeValue (const ASTContext & Ctx, T Value) static
Create the representation of a LazyGenerationalUpdatePtr.
Definition at line 3433 of file ASTContext.h.
References clang::ASTContext::getExternalSource().
markIncomplete()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> void clang::LazyGenerationalUpdatePtr< Owner, T, Update >::markIncomplete () inline
Forcibly set this pointer (which must be lazy) as needing updates.
Definition at line 420 of file ExternalASTSource.h.
References clang::LazyGenerationalUpdatePtr< Owner, T, Update >::get().
set()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> void clang::LazyGenerationalUpdatePtr< Owner, T, Update >::set (T NewValue) inline
Set the value of this pointer, in the current generation.
Definition at line 425 of file ExternalASTSource.h.
Referenced by clang::Redeclarable< decl_type >::DeclLink::setLatest().
setNotUpdated()
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> void clang::LazyGenerationalUpdatePtr< Owner, T, Update >::setNotUpdated (T NewValue) inline
Set the value of this pointer, for this and all future generations.
Definition at line 434 of file ExternalASTSource.h.
Member Data Documentation
Value
template<typename Owner , typename T , void(ExternalASTSource::*)(Owner) Update> ValueType clang::LazyGenerationalUpdatePtr< Owner, T, Update >::Value
Definition at line 402 of file ExternalASTSource.h.
The documentation for this struct was generated from the following files:
include/clang/AST/ExternalASTSource.h
include/clang/AST/ASTContext.h
lib/AST/ASTContext.cpp