clang: clang::Sema::PragmaStack< ValueType > Struct Template Reference
clang::Sema::PragmaStack< ValueType > Struct Template Reference
#include "clang/Sema/Sema.h"
Classes
struct Slot
Public Member Functions
void Act (SourceLocation PragmaLocation, PragmaMsStackAction Action, llvm::StringRef StackSlotLabel, ValueType Value)
void SentinelAction (PragmaMsStackAction Action, StringRef Label)
PragmaStack (const ValueType &Default)
bool hasValue () const
void Act (SourceLocation PragmaLocation, PragmaMsStackAction Action, llvm::StringRef StackSlotLabel, AlignPackInfo Value)
Public Attributes
SmallVector< Slot, 2 > Stack
ValueType DefaultValue
ValueType CurrentValue
SourceLocation CurrentPragmaLocation
Detailed Description
template<typename ValueType>
struct clang::Sema::PragmaStack< ValueType >
Definition at line 589 of file Sema.h.
Constructor & Destructor Documentation
PragmaStack()
template<typename ValueType > clang::Sema::PragmaStack< ValueType >::PragmaStack (const ValueType & Default) inline explicit
Definition at line 658 of file Sema.h.
Member Function Documentation
Act() [1/2]
void clang::Sema::PragmaStack< Sema::AlignPackInfo >::Act (SourceLocation PragmaLocation, PragmaMsStackAction Action, llvm::StringRef StackSlotLabel, AlignPackInfo Value)
Act() [2/2]
template<typename ValueType > void clang::Sema::PragmaStack< ValueType >::Act (SourceLocation PragmaLocation, PragmaMsStackAction Action, llvm::StringRef StackSlotLabel, ValueType Value) inline
Definition at line 602 of file Sema.h.
References clang::Sema::PragmaStack< ValueType >::CurrentPragmaLocation, clang::Sema::PragmaStack< ValueType >::CurrentValue, clang::Sema::PragmaStack< ValueType >::DefaultValue, clang::Sema::PSK_Pop, clang::Sema::PSK_Push, clang::Sema::PSK_Reset, clang::Sema::PSK_Set, clang::Sema::PragmaStack< ValueType >::Stack, and clang::Sema::PragmaStack< ValueType >::Slot::StackSlotLabel.
Referenced by clang::Sema::ActOnPragmaMSVtorDisp(), and clang::Sema::PragmaStack< ValueType >::SentinelAction().
hasValue()
template<typename ValueType > bool clang::Sema::PragmaStack< ValueType >::hasValue () const inline
Definition at line 661 of file Sema.h.
References clang::Sema::PragmaStack< ValueType >::CurrentValue, and clang::Sema::PragmaStack< ValueType >::DefaultValue.
SentinelAction()
template<typename ValueType > void clang::Sema::PragmaStack< ValueType >::SentinelAction (PragmaMsStackAction Action, StringRef Label) inline
Definition at line 651 of file Sema.h.
References clang::Sema::PragmaStack< ValueType >::Act(), clang::Sema::PragmaStack< ValueType >::CurrentPragmaLocation, clang::Sema::PragmaStack< ValueType >::CurrentValue, Label, clang::Sema::PSK_Pop, and clang::Sema::PSK_Push.
Referenced by clang::Sema::PragmaStackSentinelRAII::PragmaStackSentinelRAII(), and clang::Sema::PragmaStackSentinelRAII::~PragmaStackSentinelRAII().
Member Data Documentation
CurrentPragmaLocation
template<typename ValueType > SourceLocation clang::Sema::PragmaStack< ValueType >::CurrentPragmaLocation
Definition at line 666 of file Sema.h.
Referenced by clang::Sema::PragmaStack< ValueType >::Act(), and clang::Sema::PragmaStack< ValueType >::SentinelAction().
CurrentValue
template<typename ValueType > ValueType clang::Sema::PragmaStack< ValueType >::CurrentValue
Definition at line 665 of file Sema.h.
Referenced by clang::Sema::PragmaStack< ValueType >::Act(), clang::Sema::AddMsStructLayoutForRecord(), clang::Sema::PragmaStack< ValueType >::hasValue(), and clang::Sema::PragmaStack< ValueType >::SentinelAction().
DefaultValue
template<typename ValueType > ValueType clang::Sema::PragmaStack< ValueType >::DefaultValue
Definition at line 664 of file Sema.h.
Referenced by clang::Sema::PragmaStack< ValueType >::Act(), and clang::Sema::PragmaStack< ValueType >::hasValue().
Stack
template<typename ValueType > SmallVector<Slot, 2> clang::Sema::PragmaStack< ValueType >::Stack
Definition at line 663 of file Sema.h.
Referenced by clang::Sema::PragmaStack< ValueType >::Act(), and clang::Sema::ActOnPragmaMSVtorDisp().
The documentation for this struct was generated from the following file:
include/clang/Sema/Sema.h