clang: llvm::DOTGraphTraits< ExplodedGraph * > Struct Reference
llvm::DOTGraphTraits< ExplodedGraph * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
Static Public Member Functions
static bool nodeHasBugReport (const ExplodedNode *N)
static bool traverseHiddenNodes (const ExplodedNode *N, llvm::function_ref< void(const ExplodedNode *)> PreCallback, llvm::function_ref< void(const ExplodedNode *)> PostCallback, llvm::function_ref< bool(const ExplodedNode *)> Stop)
PreCallback: callback before break.
static bool isNodeHidden (const ExplodedNode *N, const ExplodedGraph *G)
static std::string getNodeLabel (const ExplodedNode *N, ExplodedGraph *G)
Detailed Description
Definition at line 3459 of file ExprEngine.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< ExplodedGraph * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 3460 of file ExprEngine.cpp.
Member Function Documentation
getNodeLabel()
static std::string llvm::DOTGraphTraits< ExplodedGraph * >::getNodeLabel (const ExplodedNode * N, ExplodedGraph * G) inline static
Definition at line 3510 of file ExprEngine.cpp.
References clang::ento::ExplodedNode::getID(), clang::ento::ExplodedNode::getLocation(), clang::ProgramPoint::getTag(), clang::ento::ExplodedNode::isSink(), N, and clang::ProgramPoint::printJson().
isNodeHidden()
static bool llvm::DOTGraphTraits< ExplodedGraph * >::isNodeHidden (const ExplodedNode * N, const ExplodedGraph * G) inline static
Definition at line 3506 of file ExprEngine.cpp.
References N.
nodeHasBugReport()
static bool llvm::DOTGraphTraits< ExplodedGraph * >::nodeHasBugReport (const ExplodedNode * N) inline static
Definition at line 3462 of file ExprEngine.cpp.
References clang::ento::BugReporter::EQClasses_begin(), clang::ento::BugReporter::EQClasses_end(), clang::ento::ExprEngine::getBugReporter(), clang::ento::ExplodedNode::getLocation(), clang::ento::ExplodedNode::getState(), and N.
traverseHiddenNodes()
static bool llvm::DOTGraphTraits< ExplodedGraph * >::traverseHiddenNodes (const ExplodedNode * N, llvm::function_ref< void(const ExplodedNode *)> PreCallback, llvm::function_ref< void(const ExplodedNode *)> PostCallback, llvm::function_ref< bool(const ExplodedNode *)> Stop) inline static
PreCallback: callback before break.
PostCallback: callback after break. Stop: stop iteration if returns true
Returns
Whether Stop ever returned true.
Definition at line 3487 of file ExprEngine.cpp.
References N.
The documentation for this struct was generated from the following file:
lib/StaticAnalyzer/Core/ExprEngine.cpp