clang: clang::DestructedTypeVisitor< Derived, RetTy > Struct Template Reference
clang::DestructedTypeVisitor< Derived, RetTy > Struct Template Reference
#include "clang/AST/NonTrivialTypeVisitor.h"
Public Member Functions
template<class... Ts>
RetTy visit (QualType FT, Ts &&... Args)
template<class... Ts>
RetTy visitWithKind (QualType::DestructionKind DK, QualType FT, Ts &&... Args)
Derived & asDerived ()
Detailed Description
template<class Derived, class RetTy = void>
struct clang::DestructedTypeVisitor< Derived, RetTy >
Definition at line 21 of file NonTrivialTypeVisitor.h.
Member Function Documentation
asDerived()
template<class Derived , class RetTy = void> Derived & clang::DestructedTypeVisitor< Derived, RetTy >::asDerived () inline
Definition at line 46 of file NonTrivialTypeVisitor.h.
Referenced by clang::DestructedTypeVisitor< Derived, RetTy >::visit(), and clang::DestructedTypeVisitor< Derived, RetTy >::visitWithKind().
visit()
template<class Derived , class RetTy = void> template<class... Ts> RetTy clang::DestructedTypeVisitor< Derived, RetTy >::visit (QualType FT, Ts &&... Args) inline
Definition at line 22 of file NonTrivialTypeVisitor.h.
References clang::DestructedTypeVisitor< Derived, RetTy >::asDerived(), and clang::QualType::isDestructedType().
visitWithKind()
template<class Derived , class RetTy = void> template<class... Ts> RetTy clang::DestructedTypeVisitor< Derived, RetTy >::visitWithKind (QualType::DestructionKind DK, QualType FT, Ts &&... Args) inline
Definition at line 28 of file NonTrivialTypeVisitor.h.
References clang::DestructedTypeVisitor< Derived, RetTy >::asDerived(), clang::QualType::DK_cxx_destructor, clang::QualType::DK_none, clang::QualType::DK_nontrivial_c_struct, clang::QualType::DK_objc_strong_lifetime, and clang::QualType::DK_objc_weak_lifetime.
The documentation for this struct was generated from the following file:
include/clang/AST/NonTrivialTypeVisitor.h