clang: MatchParents< T, U > Struct Template Reference
MatchParents< T, U > Struct Template Reference
Static Public Member Functions
static std::tuple< bool, DynTypedNodeList, const T *, const U *... > match (const DynTypedNodeList &NodeList, ParentMapContext::ParentMap *ParentMap)
Detailed Description
template<typename T, typename... U>
struct MatchParents< T, U >
Definition at line 278 of file ParentMapContext.cpp.
Member Function Documentation
match()
template<typename T , typename... U> static std::tuple< bool, DynTypedNodeList, const T *, const U *... > MatchParents< T, U >::match (const DynTypedNodeList & NodeList, ParentMapContext::ParentMap * ParentMap) inline static
Definition at line 280 of file ParentMapContext.cpp.
References MatchParents< T, U >::match(), and tuple_pop_front().
Referenced by MatchParents< T, U >::match(), and matchParents().
The documentation for this struct was generated from the following file:
lib/AST/ParentMapContext.cpp