clang: clang::UnionOpaquePtr< T > Struct Template Reference
clang::UnionOpaquePtr< T > Struct Template Reference
UnionOpaquePtr - A version of OpaquePtr suitable for membership in a union.
#include "clang/Sema/Ownership.h"
Public Member Functions
OpaquePtr< T > get () const
operator OpaquePtr< T > () const
UnionOpaquePtr & operator= (OpaquePtr< T > P)
Static Public Member Functions
static UnionOpaquePtr make (OpaquePtr< T > P)
Public Attributes
void * Ptr
Detailed Description
template<class T>
struct clang::UnionOpaquePtr< T >
UnionOpaquePtr - A version of OpaquePtr suitable for membership in a union.
Definition at line 96 of file Ownership.h.
Member Function Documentation
get()
template<class T > OpaquePtr< T > clang::UnionOpaquePtr< T >::get () const inline
Definition at line 104 of file Ownership.h.
References clang::OpaquePtr< PtrTy >::getFromOpaquePtr(), and clang::UnionOpaquePtr< T >::Ptr.
Referenced by clang::Sema::CheckDeductionGuideDeclarator(), and clang::UnionOpaquePtr< QualType >::operator OpaquePtr< QualType >().
make()
template<class T > static UnionOpaquePtr clang::UnionOpaquePtr< T >::make (OpaquePtr< T > P) inline static
Definition at line 99 of file Ownership.h.
References P.
operator OpaquePtr< T >()
template<class T > clang::UnionOpaquePtr< T >::operator OpaquePtr< T > () const inline
Definition at line 105 of file Ownership.h.
operator=()
template<class T > UnionOpaquePtr & clang::UnionOpaquePtr< T >::operator= (OpaquePtr< T > P) inline
Definition at line 107 of file Ownership.h.
References P, and clang::UnionOpaquePtr< T >::Ptr.
Member Data Documentation
Ptr
template<class T > void* clang::UnionOpaquePtr< T >::Ptr
Definition at line 97 of file Ownership.h.
Referenced by clang::UnionOpaquePtr< T >::get(), and clang::UnionOpaquePtr< T >::operator=().
The documentation for this struct was generated from the following file:
include/clang/Sema/Ownership.h