clang: clang::CodeGenOptions::OptRemark Struct Reference
clang::CodeGenOptions::OptRemark Struct Reference
Optimization remark with an optional regular expression pattern.
#include "clang/Basic/CodeGenOptions.h"
Public Member Functions
OptRemark ()
By default, optimization remark is missing.
bool hasValidPattern () const
Returns true iff the optimization remark holds a valid regular expression.
bool patternMatches (StringRef String) const
Matches the given string against the regex, if there is some.
Public Attributes
RemarkKind Kind
std::string Pattern
std::shared_ptr< llvm::Regex > Regex
Detailed Description
Optimization remark with an optional regular expression pattern.
Definition at line 308 of file CodeGenOptions.h.
Constructor & Destructor Documentation
OptRemark()
clang::CodeGenOptions::OptRemark::OptRemark () inline
By default, optimization remark is missing.
Definition at line 314 of file CodeGenOptions.h.
Member Function Documentation
hasValidPattern()
bool clang::CodeGenOptions::OptRemark::hasValidPattern () const inline
Returns true iff the optimization remark holds a valid regular expression.
Definition at line 318 of file CodeGenOptions.h.
Referenced by clang::ClangDiagnosticHandler::isAnyRemarkEnabled(), and patternMatches().
patternMatches()
bool clang::CodeGenOptions::OptRemark::patternMatches (StringRef String) const inline
Matches the given string against the regex, if there is some.
Definition at line 321 of file CodeGenOptions.h.
References hasValidPattern().
Referenced by clang::ClangDiagnosticHandler::isAnalysisRemarkEnabled(), clang::ClangDiagnosticHandler::isMissedOptRemarkEnabled(), clang::ClangDiagnosticHandler::isPassedOptRemarkEnabled(), clang::BackendConsumer::OptimizationRemarkHandler(), clang::BackendConsumer::OptimizationRemarkHandler(), and clang::BackendConsumer::OptimizationRemarkHandler().
Member Data Documentation
Kind
RemarkKind clang::CodeGenOptions::OptRemark::Kind
Definition at line 309 of file CodeGenOptions.h.
Pattern
std::string clang::CodeGenOptions::OptRemark::Pattern
Definition at line 310 of file CodeGenOptions.h.
Regex
std::shared_ptr<llvm::Regex> clang::CodeGenOptions::OptRemark::Regex
Definition at line 311 of file CodeGenOptions.h.
The documentation for this struct was generated from the following file:
include/clang/Basic/CodeGenOptions.h