clang: lib/CodeGen/SwiftCallingConv.cpp File Reference
SwiftCallingConv.cpp File Reference
#include "clang/CodeGen/SwiftCallingConv.h"
#include "ABIInfo.h"
#include "CodeGenModule.h"
#include "TargetInfo.h"
#include "clang/Basic/TargetInfo.h"
Functions
static const SwiftABIInfo & getSwiftABIInfo (CodeGenModule &CGM)
static bool isPowerOf2 (unsigned n)
static llvm::Type * getCommonType (llvm::Type *first, llvm::Type *second)
Given two types with the same size, try to find a common type.
static CharUnits getTypeStoreSize (CodeGenModule &CGM, llvm::Type *type)
static CharUnits getTypeAllocSize (CodeGenModule &CGM, llvm::Type *type)
static CharUnits getOffsetAtStartOfUnit (CharUnits offset, CharUnits unitSize)
Given a power-of-two unit size, return the offset of the aligned unit of that size which contains the given offset.
static bool areBytesInSameUnit (CharUnits first, CharUnits second, CharUnits chunkSize)
static bool isMergeableEntryType (llvm::Type *type)
static ABIArgInfo classifyExpandedType (SwiftAggLowering &lowering, bool forReturn, CharUnits alignmentForIndirect)
static ABIArgInfo classifyType (CodeGenModule &CGM, CanQualType type, bool forReturn)
Function Documentation
areBytesInSameUnit()
static bool areBytesInSameUnit (CharUnits first, CharUnits second, CharUnits chunkSize) static
Definition at line 428 of file SwiftCallingConv.cpp.
References getOffsetAtStartOfUnit().
classifyExpandedType()
static ABIArgInfo classifyExpandedType (SwiftAggLowering & lowering, bool forReturn, CharUnits alignmentForIndirect) static
Definition at line 803 of file SwiftCallingConv.cpp.
References clang::CodeGen::swiftcall::SwiftAggLowering::empty(), clang::CodeGen::ABIArgInfo::getCoerceAndExpand(), clang::CodeGen::swiftcall::SwiftAggLowering::getCoerceAndExpandTypes(), clang::CodeGen::ABIArgInfo::getIgnore(), clang::CodeGen::ABIArgInfo::getIndirect(), and clang::CodeGen::swiftcall::SwiftAggLowering::shouldPassIndirectly().
Referenced by classifyType().
classifyType()
static ABIArgInfo classifyType (CodeGenModule & CGM, CanQualType type, bool forReturn) static
Definition at line 816 of file SwiftCallingConv.cpp.
References clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), classifyExpandedType(), clang::CodeGen::swiftcall::SwiftAggLowering::finish(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::ABIArgInfo::getDirect(), clang::CodeGen::ABIArgInfo::getExpand(), clang::CodeGen::ABIArgInfo::getIgnore(), clang::CodeGen::ABIArgInfo::getIndirect(), clang::ASTContext::getTypeAlignInChars(), clang::CodeGen::swiftcall::mustPassRecordIndirectly(), clang::ast_matchers::recordType, and clang::CharUnits::Zero().
Referenced by clang::CodeGen::swiftcall::classifyArgumentType(), and clang::CodeGen::swiftcall::classifyReturnType().
getCommonType()
static llvm::Type * getCommonType (llvm::Type * first, llvm::Type * second) static
Given two types with the same size, try to find a common type.
Definition at line 32 of file SwiftCallingConv.cpp.
References getCommonType().
Referenced by getCommonType().
getOffsetAtStartOfUnit()
static CharUnits getOffsetAtStartOfUnit (CharUnits offset, CharUnits unitSize) static
Given a power-of-two unit size, return the offset of the aligned unit of that size which contains the given offset.
In other words, round down to the nearest multiple of the unit size.
Definition at line 422 of file SwiftCallingConv.cpp.
References clang::CharUnits::fromQuantity(), clang::CharUnits::getQuantity(), and isPowerOf2().
Referenced by areBytesInSameUnit(), and clang::CodeGen::swiftcall::SwiftAggLowering::finish().
getSwiftABIInfo()
static const SwiftABIInfo & getSwiftABIInfo (CodeGenModule & CGM) static
Definition at line 23 of file SwiftCallingConv.cpp.
References clang::cast(), clang::CodeGen::TargetCodeGenInfo::getABIInfo(), and clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
Referenced by clang::CodeGen::swiftcall::isLegalVectorType(), clang::CodeGen::swiftcall::isSwiftErrorLoweredInRegister(), clang::CodeGen::swiftcall::shouldPassIndirectly(), and clang::CodeGen::swiftcall::SwiftAggLowering::shouldPassIndirectly().
getTypeAllocSize()
static CharUnits getTypeAllocSize (CodeGenModule & CGM, llvm::Type * type) static
Definition at line 60 of file SwiftCallingConv.cpp.
References clang::CharUnits::fromQuantity(), and clang::CodeGen::CodeGenModule::getDataLayout().
Referenced by clang::CodeGen::swiftcall::SwiftAggLowering::getCoerceAndExpandTypes().
getTypeStoreSize()
static CharUnits getTypeStoreSize (CodeGenModule & CGM, llvm::Type * type) static
Definition at line 56 of file SwiftCallingConv.cpp.
References clang::CharUnits::fromQuantity(), and clang::CodeGen::CodeGenModule::getDataLayout().
Referenced by clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), and clang::CodeGen::swiftcall::getNaturalAlignment().
isMergeableEntryType()
static bool isMergeableEntryType (llvm::Type * type) static
Definition at line 434 of file SwiftCallingConv.cpp.
isPowerOf2()
static bool isPowerOf2 (unsigned n) static
Definition at line 27 of file SwiftCallingConv.cpp.
Referenced by clang::CodeGen::swiftcall::getNaturalAlignment(), getOffsetAtStartOfUnit(), clang::CodeGen::swiftcall::legalizeVectorType(), and clang::CodeGen::swiftcall::splitLegalVectorType().