clang: lib/ARCMigrate/Transforms.cpp File Reference
Transforms.cpp File Reference
#include "Transforms.h"
#include "Internals.h"
#include "clang/ARCMigrate/ARCMT.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Analysis/DomainSpecific/CocoaConventions.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Sema.h"
Functions
static void GCRewriteFinalize (MigrationPass &pass)
static void traverseAST (MigrationPass &pass)
static void independentTransforms (MigrationPass &pass)
Function Documentation
GCRewriteFinalize()
static void GCRewriteFinalize (MigrationPass & pass) static
Definition at line 516 of file Transforms.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::DeclContext::decls_begin(), clang::DeclContext::decls_end(), clang::IdentifierTable::get(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::ASTContext::getLangOpts(), clang::SelectorTable::getNullarySelector(), clang::ASTContext::getSourceManager(), clang::ObjCMethodDecl::getSourceRange(), clang::Lexer::getSourceText(), clang::CharSourceRange::getTokenRange(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTContext::Idents, clang::arcmt::TransformActions::insert(), clang::arcmt::TransformActions::insertAfterToken(), clang::Invalid, clang::ASTContext::Selectors, SM, and clang::arcmt::MigrationPass::TA.
Referenced by clang::arcmt::getAllTransformations().
independentTransforms()
static void independentTransforms (MigrationPass & pass) static
Definition at line 570 of file Transforms.cpp.
References clang::arcmt::trans::checkAPIUses(), clang::arcmt::trans::makeAssignARCSafe(), clang::arcmt::trans::removeRetainReleaseDeallocFinalize(), clang::arcmt::trans::removeZeroOutPropsInDeallocFinalize(), clang::arcmt::trans::rewriteAutoreleasePool(), clang::arcmt::trans::rewriteUnbridgedCasts(), clang::arcmt::trans::rewriteUnusedInitDelegate(), and traverseAST().
Referenced by clang::arcmt::getAllTransformations().
traverseAST()
static void traverseAST (MigrationPass & pass) static
Definition at line 556 of file Transforms.cpp.
References clang::arcmt::trans::MigrationContext::addTraverser(), clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), clang::arcmt::MigrationPass::isGCMigration(), and clang::arcmt::trans::MigrationContext::traverse().
Referenced by independentTransforms().