clang: lib/StaticAnalyzer/Checkers/UninitializedObject/UninitializedPointee.cpp File Reference
UninitializedPointee.cpp File Reference
#include "UninitializedObject.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicType.h"
Classes
struct DereferenceInfo
Functions
static llvm::Optional< DereferenceInfo > dereference (ProgramStateRef State, const FieldRegion *FR)
Dereferences FR and returns with the pointee's region, and whether it needs to be casted back to it's location type.
static bool isVoidPointer (QualType T)
Returns whether T can be (transitively) dereferenced to a void pointer type (void*, void**, ...).
Function Documentation
dereference()
static llvm::Optional< DereferenceInfo > dereference (ProgramStateRef State, const FieldRegion * FR) static
Dereferences FR and returns with the pointee's region, and whether it needs to be casted back to it's location type.
If for whatever reason dereferencing fails, returns with None.
Definition at line 220 of file UninitializedPointee.cpp.
References clang::ento::MemRegion::getAs(), clang::ento::FieldRegion::getDecl(), clang::ento::TypedValueRegion::getLocationType(), clang::Type::getPointeeType(), clang::ento::SubRegion::getSuperRegion(), clang::ValueDecl::getType(), clang::isa(), clang::ento::isDereferencableType(), isVoidPointer(), clang::None, and V.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::VisitCastExpr().
isVoidPointer()
static bool isVoidPointer (QualType T) static
Returns whether T can be (transitively) dereferenced to a void pointer type (void*, void**, ...).
Definition at line 273 of file UninitializedPointee.cpp.
Referenced by dereference().