clang: lib/Frontend/VerifyDiagnosticConsumer.cpp File Reference
VerifyDiagnosticConsumer.cpp File Reference
#include "clang/Frontend/VerifyDiagnosticConsumer.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticOptions.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/TextDiagnosticBuffer.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/Token.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <iterator>
#include <memory>
#include <string>
#include <utility>
#include <vector>
Classes
class clang::VerifyDiagnosticConsumer::MarkerTracker
Typedefs
using Directive = VerifyDiagnosticConsumer::Directive
using DirectiveList = VerifyDiagnosticConsumer::DirectiveList
using ExpectedData = VerifyDiagnosticConsumer::ExpectedData
using DiagList = TextDiagnosticBuffer::DiagList
using const_diag_iterator = TextDiagnosticBuffer::const_iterator
Functions
static bool ParseDirective (StringRef S, ExpectedData *ED, SourceManager &SM, Preprocessor *PP, SourceLocation Pos, VerifyDiagnosticConsumer::DirectiveStatus &Status, VerifyDiagnosticConsumer::MarkerTracker &Markers)
ParseDirective - Go through the comment and see if it indicates expected diagnostics.
static bool findDirectives (SourceManager &SM, FileID FID, const LangOptions &LangOpts)
Lex the specified source file to determine whether it contains any expected-* directives.
static unsigned PrintUnexpected (DiagnosticsEngine &Diags, SourceManager *SourceMgr, const_diag_iterator diag_begin, const_diag_iterator diag_end, const char *Kind)
Takes a list of diagnostics that have been generated but not matched by an expected-* directive and produces a diagnostic to the user from this.
static unsigned PrintExpected (DiagnosticsEngine &Diags, SourceManager &SourceMgr, std::vector< Directive * > &DL, const char *Kind)
Takes a list of diagnostics that were expected to have been generated but were not and produces a diagnostic to the user from this.
static bool IsFromSameFile (SourceManager &SM, SourceLocation DirectiveLoc, SourceLocation DiagnosticLoc)
Determine whether two source locations come from the same file.
static unsigned CheckLists (DiagnosticsEngine &Diags, SourceManager &SourceMgr, const char *Label, DirectiveList &Left, const_diag_iterator d2_begin, const_diag_iterator d2_end, bool IgnoreUnexpected)
CheckLists - Compare expected to seen diagnostic lists and return the the difference between them.
static unsigned CheckResults (DiagnosticsEngine &Diags, SourceManager &SourceMgr, const TextDiagnosticBuffer &Buffer, ExpectedData &ED)
CheckResults - This compares the expected results to those that were actually reported.
Typedef Documentation
const_diag_iterator
using const_diag_iterator = TextDiagnosticBuffer::const_iterator
Definition at line 84 of file VerifyDiagnosticConsumer.cpp.
DiagList
using DiagList = TextDiagnosticBuffer::DiagList
Definition at line 83 of file VerifyDiagnosticConsumer.cpp.
Directive
using Directive = VerifyDiagnosticConsumer::Directive
Definition at line 49 of file VerifyDiagnosticConsumer.cpp.
DirectiveList
using DirectiveList = VerifyDiagnosticConsumer::DirectiveList
Definition at line 50 of file VerifyDiagnosticConsumer.cpp.
ExpectedData
using ExpectedData = VerifyDiagnosticConsumer::ExpectedData
Definition at line 51 of file VerifyDiagnosticConsumer.cpp.
Function Documentation
CheckLists()
static unsigned CheckLists (DiagnosticsEngine & Diags, SourceManager & SourceMgr, const char * Label, DirectiveList & Left, const_diag_iterator d2_begin, const_diag_iterator d2_end, bool IgnoreUnexpected) static
CheckLists - Compare expected to seen diagnostic lists and return the the difference between them.
Definition at line 933 of file VerifyDiagnosticConsumer.cpp.
References clang::VerifyDiagnosticConsumer::Directive::DiagnosticLoc, IsFromSameFile(), clang::SourceLocation::isInvalid(), Label, clang::VerifyDiagnosticConsumer::Directive::match(), clang::VerifyDiagnosticConsumer::Directive::MatchAnyFileAndLine, clang::VerifyDiagnosticConsumer::Directive::MatchAnyLine, clang::VerifyDiagnosticConsumer::Directive::Max, clang::VerifyDiagnosticConsumer::Directive::Min, PrintExpected(), and PrintUnexpected().
Referenced by CheckResults().
CheckResults()
static unsigned CheckResults (DiagnosticsEngine & Diags, SourceManager & SourceMgr, const TextDiagnosticBuffer & Buffer, ExpectedData & ED) static
CheckResults - This compares the expected results to those that were actually reported.
It emits any discrepencies. Return "true" if there were problems. Return "false" otherwise.
Definition at line 983 of file VerifyDiagnosticConsumer.cpp.
References CheckLists(), clang::TextDiagnosticBuffer::err_begin(), clang::TextDiagnosticBuffer::err_end(), clang::Error, clang::VerifyDiagnosticConsumer::ExpectedData::Errors, clang::DiagnosticsEngine::getDiagnosticOptions(), clang::Note, clang::TextDiagnosticBuffer::note_begin(), clang::TextDiagnosticBuffer::note_end(), clang::VerifyDiagnosticConsumer::ExpectedData::Notes, clang::Remark, clang::TextDiagnosticBuffer::remark_begin(), clang::TextDiagnosticBuffer::remark_end(), clang::VerifyDiagnosticConsumer::ExpectedData::Remarks, clang::TextDiagnosticBuffer::warn_begin(), clang::TextDiagnosticBuffer::warn_end(), clang::Warning, and clang::VerifyDiagnosticConsumer::ExpectedData::Warnings.
findDirectives()
static bool findDirectives (SourceManager & SM, FileID FID, const LangOptions & LangOpts) static
Lex the specified source file to determine whether it contains any expected-* directives.
As a Lexer is used rather than a full-blown Preprocessor, directives inside skipped if blocks will still be found.
Returns
true if any directives were found.
Definition at line 820 of file VerifyDiagnosticConsumer.cpp.
References clang::Token::getLocation(), clang::Lexer::getSpelling(), clang::VerifyDiagnosticConsumer::HasNoDirectives, clang::Token::is(), clang::FileID::isInvalid(), clang::Token::isNot(), clang::Lexer::LexFromRawLexer(), ParseDirective(), clang::Lexer::SetCommentRetentionState(), clang::Token::setKind(), SM, and Tok.
Referenced by clang::VerifyDiagnosticConsumer::UpdateParsedFileStatus().
IsFromSameFile()
static bool IsFromSameFile (SourceManager & SM, SourceLocation DirectiveLoc, SourceLocation DiagnosticLoc) static
Determine whether two source locations come from the same file.
Definition at line 916 of file VerifyDiagnosticConsumer.cpp.
References clang::SourceLocation::isMacroID(), and SM.
Referenced by CheckLists().
ParseDirective()
static bool ParseDirective (StringRef S, ExpectedData * ED, SourceManager & SM, Preprocessor * PP, SourceLocation Pos, VerifyDiagnosticConsumer::DirectiveStatus & Status, VerifyDiagnosticConsumer::MarkerTracker & Markers) static
ParseDirective - Go through the comment and see if it indicates expected diagnostics.
If so, then put them in the appropriate directive list.
Returns true if any valid directives were found.
Definition at line 403 of file VerifyDiagnosticConsumer.cpp.
References clang::VerifyDiagnosticConsumer::MarkerTracker::addDirective(), clang::VerifyDiagnosticConsumer::MarkerTracker::addMarker(), clang::SrcMgr::C_User, clang::VerifyDiagnosticConsumer::ExpectedData::Errors, clang::File, Filename, clang::DiagnosticsEngine::getDiagnosticOptions(), clang::Preprocessor::getDiagnostics(), clang::SourceLocation::getLocWithOffset(), clang::VerifyDiagnosticConsumer::HasExpectedNoDiagnostics, clang::VerifyDiagnosticConsumer::HasOtherExpectedDirectives, clang::Invalid, clang::FileID::isInvalid(), clang::SourceLocation::isInvalid(), clang::Preprocessor::LookupFile(), clang::VerifyDiagnosticConsumer::Directive::MaxCount, NoDiag(), clang::VerifyDiagnosticConsumer::ExpectedData::Notes, clang::VerifyDiagnosticConsumer::ExpectedData::Remarks, clang::DiagnosticsEngine::Report(), SM, clang::DiagnosticOptions::VerifyPrefixes, and clang::VerifyDiagnosticConsumer::ExpectedData::Warnings.
Referenced by findDirectives(), and clang::VerifyDiagnosticConsumer::HandleComment().
PrintExpected()
static unsigned PrintExpected (DiagnosticsEngine & Diags, SourceManager & SourceMgr, std::vector< Directive * > & DL, const char * Kind) static
Takes a list of diagnostics that were expected to have been generated but were not and produces a diagnostic to the user from this.
Definition at line 886 of file VerifyDiagnosticConsumer.cpp.
References clang::DiagnosticsEngine::Report(), and clang::DiagnosticBuilder::setForceEmit().
Referenced by CheckLists().
PrintUnexpected()
static unsigned PrintUnexpected (DiagnosticsEngine & Diags, SourceManager * SourceMgr, const_diag_iterator diag_begin, const_diag_iterator diag_end, const char * Kind) static
Takes a list of diagnostics that have been generated but not matched by an expected-* directive and produces a diagnostic to the user from this.
Definition at line 858 of file VerifyDiagnosticConsumer.cpp.
References clang::File, clang::DiagnosticsEngine::Report(), and clang::DiagnosticBuilder::setForceEmit().
Referenced by CheckLists().