clang: lib/Headers/arm_acle.h File Reference
arm_acle.h File Reference
#include <stdint.h>
Macros
#define __dmb(i)
#define __dsb(i)
#define __isb(i)
#define __pld(addr)
#define __pldx(access_kind, cache_level, retention_policy, addr)
#define __pli(addr)
#define __plix(cache_level, retention_policy, addr)
#define __arm_rsr(sysreg)
#define __arm_rsr64(sysreg)
#define __arm_rsr128(sysreg)
#define __arm_rsrp(sysreg)
#define __arm_rsrf(sysreg)
#define __arm_rsrf64(sysreg)
#define __arm_wsr(sysreg, v)
#define __arm_wsr64(sysreg, v)
#define __arm_wsr128(sysreg, v)
#define __arm_wsrp(sysreg, v)
#define __arm_wsrf(sysreg, v)
#define __arm_wsrf64(sysreg, v)
Functions
static __inline__ void __attribute__ ((__always_inline__, __nodebug__)) __wfi(void)
while (__builtin_arm_strex(__x, __p))
if (__y==0) return __x
return (__x > > __y)|(__x<<(32 - __y))
Variables
static __inline__ uint32_t volatile uint32_t * __p
do v = __builtin_arm_ldrex(__p)
static __inline__ uint32_t uint32_t __y
Macro Definition Documentation
__arm_rsr
#define __arm_rsr (sysreg)
Value:
__builtin_arm_rsr(sysreg)
Definition at line 717 of file arm_acle.h.
__arm_rsr128
#define __arm_rsr128 (sysreg)
Value:
__builtin_arm_rsr128(sysreg)
Definition at line 719 of file arm_acle.h.
__arm_rsr64
#define __arm_rsr64 (sysreg)
Value:
__builtin_arm_rsr64(sysreg)
Definition at line 718 of file arm_acle.h.
__arm_rsrf
#define __arm_rsrf (sysreg)
Value:
__builtin_bit_cast(float, __arm_rsr(sysreg))
Definition at line 721 of file arm_acle.h.
__arm_rsrf64
#define __arm_rsrf64 (sysreg)
Value:
__builtin_bit_cast(double, __arm_rsr64(sysreg))
Definition at line 722 of file arm_acle.h.
__arm_rsrp
#define __arm_rsrp (sysreg)
Value:
__builtin_arm_rsrp(sysreg)
Definition at line 720 of file arm_acle.h.
__arm_wsr
#define __arm_wsr (sysreg, v)
Value:
__builtin_arm_wsr(sysreg, v)
Definition at line 723 of file arm_acle.h.
__arm_wsr128
#define __arm_wsr128 (sysreg, v)
Value:
__builtin_arm_wsr128(sysreg, v)
Definition at line 725 of file arm_acle.h.
__arm_wsr64
#define __arm_wsr64 (sysreg, v)
Value:
__builtin_arm_wsr64(sysreg, v)
Definition at line 724 of file arm_acle.h.
__arm_wsrf
#define __arm_wsrf (sysreg, v)
Value:
__arm_wsr(sysreg, __builtin_bit_cast(uint32_t, v))
Definition at line 727 of file arm_acle.h.
__arm_wsrf64
#define __arm_wsrf64 (sysreg, v)
Value:
__arm_wsr64(sysreg, __builtin_bit_cast(uint64_t, v))
Definition at line 728 of file arm_acle.h.
__arm_wsrp
#define __arm_wsrp (sysreg, v)
Value:
__builtin_arm_wsrp(sysreg, v)
Definition at line 726 of file arm_acle.h.
__dmb
#define __dmb (i)
Value:
__builtin_arm_dmb(i)
Definition at line 26 of file arm_acle.h.
__dsb
#define __dsb (i)
Value:
__builtin_arm_dsb(i)
Definition at line 29 of file arm_acle.h.
__isb
#define __isb (i)
Value:
__builtin_arm_isb(i)
Definition at line 32 of file arm_acle.h.
__pld
#define __pld (addr)
Value:
__pldx(0, 0, 0, addr)
Definition at line 83 of file arm_acle.h.
__pldx
#define __pldx (access_kind, cache_level, retention_policy, addr)
Value:
  __builtin_arm_prefetch(addr, access_kind, cache_level, retention_policy, 1)
Definition at line 89 of file arm_acle.h.
__pli
#define __pli (addr)
Value:
__plix(0, 0, addr)
Definition at line 94 of file arm_acle.h.
__plix
#define __plix (cache_level, retention_policy, addr)
Value:
  __builtin_arm_prefetch(addr, 0, cache_level, retention_policy, 0)
Definition at line 100 of file arm_acle.h.
Function Documentation
__attribute__()
static __inline__ void __attribute__ ((__always_inline__, __nodebug__)) static
Definition at line 38 of file arm_acle.h.
if()
if (__y = =0)
Referenced by clang::targets::DarwinTargetInfo< Target >::DarwinTargetInfo(), and clang::targets::PPC64TargetInfo::PPC64TargetInfo().
return()
return (__x , __y)
while()
while (__builtin_arm_strex(__x, __p))
Referenced by getAcquireSite().
Variable Documentation
__p
__inline__ uint32_t volatile uint32_t* __p
Initial value:
{
  uint32_t v
Definition at line 73 of file arm_acle.h.
__y
__inline__ unsigned long uint32_t __y
Initial value:
{
  __y %= 32
Definition at line 115 of file arm_acle.h.
v
return v = __builtin_arm_ldrex(__p)
Definition at line 76 of file arm_acle.h.
Referenced by addPGOAndCoverageFlags(), bytes(), bytes(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::serialization::UnsafeQualTypeDenseMapInfo::getHashValue(), getLowBit(), clang::ento::BasicValueFactory::getMaxValue(), clang::ento::BasicValueFactory::getMinValue(), clang::ento::SymbolManager::getSymIntExpr(), clang::format::hash_combine(), isAlwaysUninit(), isUninitialized(), clang::CodeGen::CGBlockInfo::Capture::makeConstant(), clang::CodeGen::CGBlockInfo::Capture::makeIndex(), clang::OptionalDiagnostic::operator<<(), renderDebugOptions(), and clang::TemplateArgument::setIsDefaulted().