clang: lib/AST/MicrosoftCXXABI.cpp File Reference
MicrosoftCXXABI.cpp File Reference
#include "CXXABI.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/MangleNumberingContext.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/Type.h"
#include "clang/Basic/TargetInfo.h"
Functions
static bool usesMultipleInheritanceModel (const CXXRecordDecl *RD)
static std::pair< unsigned, unsigned > getMSMemberPointerSlots (const MemberPointerType *MPT)
Function Documentation
getMSMemberPointerSlots()
static std::pair< unsigned, unsigned > getMSMemberPointerSlots (const MemberPointerType * MPT) static
Definition at line 282 of file MicrosoftCXXABI.cpp.
References clang::MemberPointerType::getMostRecentCXXRecordDecl(), clang::CXXRecordDecl::getMSInheritanceModel(), clang::inheritanceModelHasNVOffsetField(), clang::inheritanceModelHasVBPtrOffsetField(), clang::inheritanceModelHasVBTableOffsetField(), and clang::MemberPointerType::isMemberFunctionPointer().
usesMultipleInheritanceModel()
static bool usesMultipleInheritanceModel (const CXXRecordDecl * RD) static
Definition at line 210 of file MicrosoftCXXABI.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getNumBases(), clang::CXXBaseSpecifier::getType(), and clang::CXXRecordDecl::isPolymorphic().
Referenced by clang::CXXRecordDecl::calculateInheritanceModel().