clang: lib/Tooling/DumpTool/ASTSrcLocProcessor.cpp File Reference
ASTSrcLocProcessor.cpp File Reference
#include "ASTSrcLocProcessor.h"
#include "clang/Frontend/CompilerInstance.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
llvm::json::Object toJSON (llvm::StringMap< std::vector< StringRef > > const &Obj)
llvm::json::Object toJSON (llvm::StringMap< std::string > const &Obj)
llvm::json::Object toJSON (ClassData const &Obj)
llvm::json::Object toJSON (llvm::StringMap< ClassData > const &Obj)
void WriteJSON (StringRef JsonPath, llvm::json::Object &&ClassInheritance, llvm::json::Object &&ClassesInClade, llvm::json::Object &&ClassEntries)
std::vector< std::string > CaptureMethods (std::string TypeString, const clang::CXXRecordDecl *ASTClass, const MatchFinder::MatchResult &Result)
Function Documentation
CaptureMethods()
std::vector< std::string > CaptureMethods (std::string TypeString, const clang::CXXRecordDecl * ASTClass, const MatchFinder::MatchResult & Result)
Definition at line 143 of file ASTSrcLocProcessor.cpp.
References clang::ast_matchers::cxxMethodDecl, clang::ast_matchers::cxxRecordDecl, clang::ast_matchers::findAll(), clang::NamedDecl::getName(), clang::ast_matchers::hasAnyName, clang::ast_matchers::hasName(), clang::ast_matchers::match(), Node, clang::ast_matchers::optionally, and clang::Result.
toJSON() [1/4]
llvm::json::Object toJSON (ClassData const & Obj)
Definition at line 72 of file ASTSrcLocProcessor.cpp.
References clang::tooling::ClassData::ASTClassLocations, clang::tooling::ClassData::ASTClassRanges, clang::tooling::ClassData::DeclNameInfos, clang::tooling::ClassData::NestedNameLocs, clang::tooling::ClassData::TemplateParms, clang::tooling::ClassData::TypeLocs, and clang::tooling::ClassData::TypeSourceInfos.
toJSON() [2/4]
llvm::json::Object toJSON (llvm::StringMap< ClassData > const & Obj)
Definition at line 92 of file ASTSrcLocProcessor.cpp.
References toJSON().
toJSON() [3/4]
llvm::json::Object toJSON (llvm::StringMap< std::string > const & Obj)
Definition at line 62 of file ASTSrcLocProcessor.cpp.
toJSON() [4/4]
llvm::json::Object toJSON (llvm::StringMap< std::vector< StringRef > > const & Obj)
Definition at line 52 of file ASTSrcLocProcessor.cpp.
Referenced by clang::tooling::ASTSrcLocProcessor::generate(), and toJSON().
WriteJSON()
void WriteJSON (StringRef JsonPath, llvm::json::Object && ClassInheritance, llvm::json::Object && ClassesInClade, llvm::json::Object && ClassEntries)
Definition at line 101 of file ASTSrcLocProcessor.cpp.
Referenced by clang::tooling::ASTSrcLocProcessor::generate(), and clang::tooling::ASTSrcLocProcessor::generateEmpty().