clang: lib/Headers/avx512ifmaintrin.h File Reference
avx512ifmaintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma"), __min_vector_width__(512)))
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_madd52hi_epu64 (__m512i __X, __m512i __Y, __m512i __Z)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_madd52hi_epu64 (__m512i __W, __mmask8 __M, __m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_madd52hi_epu64 (__mmask8 __M, __m512i __X, __m512i __Y, __m512i __Z)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_madd52lo_epu64 (__m512i __X, __m512i __Y, __m512i __Z)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_madd52lo_epu64 (__m512i __W, __mmask8 __M, __m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_madd52lo_epu64 (__mmask8 __M, __m512i __X, __m512i __Y, __m512i __Z)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma"), __min_vector_width__(512)))
Definition at line 18 of file avx512ifmaintrin.h.
Function Documentation
_mm512_madd52hi_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_madd52hi_epu64 (__m512i __X, __m512i __Y, __m512i __Z) static
Definition at line 21 of file avx512ifmaintrin.h.
References __Y.
Referenced by _mm512_mask_madd52hi_epu64(), and _mm512_maskz_madd52hi_epu64().
_mm512_madd52lo_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_madd52lo_epu64 (__m512i __X, __m512i __Y, __m512i __Z) static
Definition at line 44 of file avx512ifmaintrin.h.
References __Y.
Referenced by _mm512_mask_madd52lo_epu64(), and _mm512_maskz_madd52lo_epu64().
_mm512_mask_madd52hi_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_madd52hi_epu64 (__m512i __W, __mmask8 __M, __m512i __X, __m512i __Y) static
Definition at line 28 of file avx512ifmaintrin.h.
References __Y, and _mm512_madd52hi_epu64().
_mm512_mask_madd52lo_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_madd52lo_epu64 (__m512i __W, __mmask8 __M, __m512i __X, __m512i __Y) static
Definition at line 51 of file avx512ifmaintrin.h.
References __Y, and _mm512_madd52lo_epu64().
_mm512_maskz_madd52hi_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_madd52hi_epu64 (__mmask8 __M, __m512i __X, __m512i __Y, __m512i __Z) static
Definition at line 36 of file avx512ifmaintrin.h.
References __Y, _mm512_madd52hi_epu64(), and _mm512_setzero_si512().
_mm512_maskz_madd52lo_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_madd52lo_epu64 (__mmask8 __M, __m512i __X, __m512i __Y, __m512i __Z) static
Definition at line 59 of file avx512ifmaintrin.h.
References __Y, _mm512_madd52lo_epu64(), and _mm512_setzero_si512().