clang: lib/Basic/Targets/AArch64.cpp File Reference
AArch64.cpp File Reference
#include "AArch64.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/TargetParser/ARMTargetParserCommon.h"
#include <optional>
#include "clang/Basic/BuiltinsNEON.def"
#include "clang/Basic/BuiltinsSVE.def"
#include "clang/Basic/BuiltinsSME.def"
#include "clang/Basic/BuiltinsAArch64.def"
Macros
#define BUILTIN(ID, TYPE, ATTRS)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define BUILTIN(ID, TYPE, ATTRS)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define BUILTIN(ID, TYPE, ATTRS)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define BUILTIN(ID, TYPE, ATTRS)
#define LANGBUILTIN(ID, TYPE, ATTRS, LANG)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define TARGET_HEADER_BUILTIN(ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
Functions
static unsigned matchAsmCCConstraint (const char *Name)
Variables
static constexpr Builtin::Info BuiltinInfo []
Macro Definition Documentation
BUILTIN [1/4]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
BUILTIN [2/4]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
BUILTIN [3/4]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
BUILTIN [4/4]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
LANGBUILTIN
#define LANGBUILTIN (ID, TYPE, ATTRS, LANG)
Value:
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, LANG},
TARGET_BUILTIN [1/4]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
TARGET_BUILTIN [2/4]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
TARGET_BUILTIN [3/4]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
TARGET_BUILTIN [4/4]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
TARGET_HEADER_BUILTIN
#define TARGET_HEADER_BUILTIN (ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::HEADER, LANGS},
Function Documentation
matchAsmCCConstraint()
static unsigned matchAsmCCConstraint (const char * Name) static
Definition at line 1222 of file AArch64.cpp.
Referenced by clang::targets::AArch64TargetInfo::convertConstraint(), clang::targets::X86TargetInfo::convertConstraint(), clang::targets::AArch64TargetInfo::validateAsmConstraint(), and clang::targets::X86TargetInfo::validateAsmConstraint().
Variable Documentation
BuiltinInfo
Builtin::Info BuiltinInfo[] static constexpr
Initial value:
= {
#define BUILTIN(ID, TYPE, ATTRS)                                               \
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)                               \
#define BUILTIN(ID, TYPE, ATTRS)                                               \
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)                               \
#define BUILTIN(ID, TYPE, ATTRS)                                               \
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)                               \
#define BUILTIN(ID, TYPE, ATTRS)                                               \
#define LANGBUILTIN(ID, TYPE, ATTRS, LANG)                                     \
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)                               \
#define TARGET_HEADER_BUILTIN(ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)         \
}
Definition at line 27 of file AArch64.cpp.