clang: lib/Basic/Targets/AVR.cpp File Reference
AVR.cpp File Reference
#include "AVR.h"
#include "clang/Basic/MacroBuilder.h"
#include "llvm/ADT/StringSwitch.h"
Classes
struct clang::targets::MCUInfo
Information about a specific microcontroller.
Namespaces
namespace clang
namespace clang::targets
Functions
static bool ArchHasELPM (StringRef Arch)
static bool ArchHasELPMX (StringRef Arch)
static bool ArchHasMOVW (StringRef Arch)
static bool ArchHasLPMX (StringRef Arch)
static bool ArchHasMUL (StringRef Arch)
static bool ArchHasJMPCALL (StringRef Arch)
static bool ArchHas3BytePC (StringRef Arch)
Variables
static MCUInfo clang::targets::AVRMcus []
Function Documentation
ArchHas3BytePC()
static bool ArchHas3BytePC (StringRef Arch) static
Definition at line 391 of file AVR.cpp.
Referenced by clang::targets::AVRTargetInfo::getTargetDefines(), and clang::targets::AVRTargetInfo::handleAsmEscapedChar().
ArchHasELPM()
static bool ArchHasELPM (StringRef Arch) static
Definition at line 352 of file AVR.cpp.
Referenced by clang::targets::AVRTargetInfo::getTargetDefines().
ArchHasELPMX()
static bool ArchHasELPMX (StringRef Arch) static
Definition at line 359 of file AVR.cpp.
Referenced by clang::targets::AVRTargetInfo::getTargetDefines().
ArchHasJMPCALL()
static bool ArchHasJMPCALL (StringRef Arch) static
Definition at line 384 of file AVR.cpp.
Referenced by clang::targets::AVRTargetInfo::getTargetDefines(), and clang::targets::AVRTargetInfo::handleAsmEscapedChar().
ArchHasLPMX()
static bool ArchHasLPMX (StringRef Arch) static
Definition at line 373 of file AVR.cpp.
References ArchHasMOVW().
Referenced by clang::targets::AVRTargetInfo::getTargetDefines().
ArchHasMOVW()
static bool ArchHasMOVW (StringRef Arch) static
Definition at line 366 of file AVR.cpp.
Referenced by ArchHasLPMX(), and clang::targets::AVRTargetInfo::getTargetDefines().
ArchHasMUL()
static bool ArchHasMUL (StringRef Arch) static
Definition at line 377 of file AVR.cpp.
Referenced by clang::targets::AVRTargetInfo::getTargetDefines().