clang: lib/Analysis/BodyFarm.cpp File Reference
BodyFarm.cpp File Reference
#include "clang/Analysis/BodyFarm.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/Decl.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/Analysis/CodeInjector.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/OperatorKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Debug.h"
#include <optional>
Macros
#define DEBUG_TYPE "body-farm"
Typedefs
typedef Stmt *(* FunctionFarmer) (ASTContext &C, const FunctionDecl *D)
Functions
static bool isDispatchBlock (QualType Ty)
static CallExpr * create_call_once_funcptr_call (ASTContext &C, ASTMaker M, const ParmVarDecl *Callback, ArrayRef< Expr * > CallArgs)
static CallExpr * create_call_once_lambda_call (ASTContext &C, ASTMaker M, const ParmVarDecl *Callback, CXXRecordDecl *CallbackDecl, ArrayRef< Expr * > CallArgs)
static Stmt * create_std_move_forward (ASTContext &C, const FunctionDecl *D)
Create a fake body for 'std::move' or 'std::forward'.
static Stmt * create_call_once (ASTContext &C, const FunctionDecl *D)
Create a fake body for std::call_once.
static Stmt * create_dispatch_once (ASTContext &C, const FunctionDecl *D)
Create a fake body for dispatch_once.
static Stmt * create_dispatch_sync (ASTContext &C, const FunctionDecl *D)
Create a fake body for dispatch_sync.
static Stmt * create_OSAtomicCompareAndSwap (ASTContext &C, const FunctionDecl *D)
static const ObjCIvarDecl * findBackingIvar (const ObjCPropertyDecl *Prop)
static Stmt * createObjCPropertyGetter (ASTContext &Ctx, const ObjCMethodDecl *MD)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "body-farm"
Definition at line 29 of file BodyFarm.cpp.
Typedef Documentation
FunctionFarmer
typedef Stmt *(* FunctionFarmer) (ASTContext &C, const FunctionDecl *D)
Definition at line 259 of file BodyFarm.cpp.
Function Documentation
create_call_once()
static Stmt * create_call_once (ASTContext & C, const FunctionDecl * D) static
Create a fake body for std::call_once.
Emulates the following function body:
typedef struct once_flag_s {
  unsigned long __state = 0;
} once_flag;
template<class Callable>
void call_once(once_flag& o, Callable func) {
  if (!o.__state) {
    func();
  }
  o.__state = 1;
}
Definition at line 346 of file BodyFarm.cpp.
References clang::C, clang::IfStmt::Create(), clang::UnaryOperator::Create(), create_call_once_funcptr_call(), create_call_once_lambda_call(), clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::Type::getAsRecordDecl(), clang::QualType::getCanonicalType(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::QualType::getNonReferenceType(), clang::FunctionDecl::getNumParams(), clang::FunctionProtoType::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::FunctionProtoType::getParamType(), clang::Type::getPointeeType(), clang::ValueDecl::getType(), clang::CXXRecordDecl::isLambda(), clang::QualType::isNull(), clang::Type::isReferenceType(), clang::OK_Ordinary, clang::FunctionDecl::param_size(), and clang::VK_PRValue.
Referenced by clang::BodyFarm::getBody().
create_call_once_funcptr_call()
static CallExpr * create_call_once_funcptr_call (ASTContext & C, ASTMaker M, const ParmVarDecl * Callback, ArrayRef< Expr * > CallArgs) static
Definition at line 261 of file BodyFarm.cpp.
References clang::C, clang::CallExpr::Create(), clang::QualType::getNonReferenceType(), clang::Type::isLValueReferenceType(), clang::Type::isRValueReferenceType(), and clang::VK_PRValue.
Referenced by create_call_once().
create_call_once_lambda_call()
static CallExpr * create_call_once_lambda_call (ASTContext & C, ASTMaker M, const ParmVarDecl * Callback, CXXRecordDecl * CallbackDecl, ArrayRef< Expr * > CallArgs) static
Definition at line 287 of file BodyFarm.cpp.
References clang::C, clang::CXXOperatorCallExpr::Create(), clang::DeclRefExpr::Create(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::ValueDecl::getType(), clang::CXXRecordDecl::isLambda(), clang::VK_LValue, and clang::VK_PRValue.
Referenced by create_call_once().
create_dispatch_once()
static Stmt * create_dispatch_once (ASTContext & C, const FunctionDecl * D) static
Create a fake body for dispatch_once.
Definition at line 508 of file BodyFarm.cpp.
References clang::Block, clang::C, clang::CallExpr::Create(), clang::IfStmt::Create(), clang::UnaryOperator::Create(), clang::Type::getAs(), clang::FunctionDecl::getParamDecl(), clang::PointerType::getPointeeType(), clang::ValueDecl::getType(), isDispatchBlock(), clang::Type::isIntegerType(), clang::OK_Ordinary, clang::FunctionDecl::param_size(), and clang::VK_PRValue.
Referenced by clang::BodyFarm::getBody().
create_dispatch_sync()
static Stmt * create_dispatch_sync (ASTContext & C, const FunctionDecl * D) static
Create a fake body for dispatch_sync.
Definition at line 592 of file BodyFarm.cpp.
References clang::C, clang::CallExpr::Create(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), isDispatchBlock(), clang::FunctionDecl::param_size(), and clang::VK_PRValue.
Referenced by clang::BodyFarm::getBody().
create_OSAtomicCompareAndSwap()
static Stmt * create_OSAtomicCompareAndSwap (ASTContext & C, const FunctionDecl * D) static
Construct the If.
Definition at line 618 of file BodyFarm.cpp.
References clang::C, clang::IfStmt::Create(), clang::Type::getAs(), clang::FunctionDecl::getParamDecl(), clang::PointerType::getPointeeType(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), clang::Type::isBooleanType(), clang::Type::isIntegralType(), and clang::FunctionDecl::param_size().
Referenced by clang::BodyFarm::getBody().
create_std_move_forward()
static Stmt * create_std_move_forward (ASTContext & C, const FunctionDecl * D) static
Create a fake body for 'std::move' or 'std::forward'.
This is just:
return static_cast<return_type>(param);
Definition at line 320 of file BodyFarm.cpp.
References clang::C, clang::Type::castAs(), clang::FunctionDecl::getParamDecl(), and clang::ValueDecl::getType().
Referenced by clang::BodyFarm::getBody().
createObjCPropertyGetter()
static Stmt * createObjCPropertyGetter (ASTContext & Ctx, const ObjCMethodDecl * MD) static
Definition at line 785 of file BodyFarm.cpp.
References findBackingIvar(), clang::ObjCMethodDecl::findPropertyDecl(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCIvarDecl::getContainingInterface(), clang::ObjCInterfaceDecl::getImplementation(), clang::QualType::getNonReferenceType(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyDecl::getPropertyIvarDecl(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::getSelfDecl(), clang::ObjCPropertyDecl::getType(), clang::ValueDecl::getType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isObjCLifetimeType(), clang::Type::isReferenceType(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::QualType::isTriviallyCopyableType(), clang::ObjCPropertyAttribute::kind_weak, and clang::ObjCImplDecl::property_impls().
Referenced by clang::BodyFarm::getBody().
findBackingIvar()
static const ObjCIvarDecl * findBackingIvar (const ObjCPropertyDecl * Prop) static
Definition at line 746 of file BodyFarm.cpp.
References clang::cast(), clang::ObjCInterfaceDecl::FindPropertyVisibleInPrimaryClass(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::ObjCPropertyDecl::getPropertyIvarDecl(), clang::ObjCPropertyDecl::getQueryKind(), and clang::ObjCPropertyDecl::isReadOnly().
Referenced by createObjCPropertyGetter().
isDispatchBlock()
static bool isDispatchBlock (QualType Ty) static
Definition at line 37 of file BodyFarm.cpp.
References clang::Type::getAs(), clang::FunctionProtoType::getNumParams(), clang::BlockPointerType::getPointeeType(), clang::FunctionType::getReturnType(), and clang::Type::isVoidType().
Referenced by create_dispatch_once(), and create_dispatch_sync().