clang: lib/Tooling/Syntax/BuildTree.cpp File Reference
BuildTree.cpp File Reference
#include "clang/Tooling/Syntax/BuildTree.h"
#include "clang/AST/ASTFwd.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/IgnoreExpr.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/TypeLocVisitor.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Tooling/Syntax/Nodes.h"
#include "clang/Tooling/Syntax/TokenBufferTokenManager.h"
#include "clang/Tooling/Syntax/Tokens.h"
#include "clang/Tooling/Syntax/Tree.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <cstddef>
#include <map>
Functions
static Expr * IgnoreImplicitConstructorSingleStep (Expr *E)
static Expr * IgnoreCXXFunctionalCastExprWrappingConstructor (Expr *E)
static Expr * IgnoreImplicit (Expr *E)
static LLVM_ATTRIBUTE_UNUSED bool isImplicitExpr (Expr *E)
static CallExpr::arg_range dropDefaultArgs (CallExpr::arg_range Args)
static syntax::NodeKind getOperatorNodeKind (const CXXOperatorCallExpr &E)
static SourceLocation getQualifiedNameStart (NamedDecl *D)
Get the start of the qualified name.
if (!Range.getBegin().isValid())
Gets the range of the initializer inside an init-declarator C++ [dcl.decl].
Builder foldNode (Builder.getRange(Range), N, nullptr)
Builder markChild (N, syntax::NodeRole::ListElement)
if (!Builder.isResponsibleForCreatingDeclaration(D))
Builder foldList (DeclarationRange, DL, nullptr)
Builder markChild (DL, syntax::NodeRole::Declarators)
Builder foldNode (DeclarationRange, new(allocator()) syntax::SimpleDeclaration, D)
syntax::TrailingReturnType * buildTrailingReturn (FunctionProtoTypeLoc L)
Returns the range of the built node.
void foldExplicitTemplateInstantiation (ArrayRef< syntax::Token > Range, const syntax::Token *ExternKW, const syntax::Token *TemplateKW, syntax::SimpleDeclaration *InnerDeclaration, Decl *From)
syntax::TemplateDeclaration * foldTemplateDeclaration (ArrayRef< syntax::Token > Range, const syntax::Token *TemplateKW, ArrayRef< syntax::Token > TemplatedDeclaration, Decl *From)
llvm::BumpPtrAllocator & allocator ()
A small helper to save some typing.
Variables
auto * N = new (allocator()) syntax::SimpleDeclarator
else
auto DeclarationRange = Builder.getDeclarationRange(D)
return true
syntax::TreeBuilder & Builder
const ASTContext & Context
Function Documentation
allocator()
llvm::BumpPtrAllocator & allocator ()
A small helper to save some typing.
Definition at line 1677 of file BuildTree.cpp.
Referenced by buildTrailingReturn(), foldExplicitTemplateInstantiation(), foldTemplateDeclaration(), and if().
buildTrailingReturn()
syntax::TrailingReturnType * buildTrailingReturn (FunctionProtoTypeLoc L)
Returns the range of the built node.
Definition at line 1624 of file BuildTree.cpp.
References allocator(), clang::FunctionTypeLoc::getReturnLoc(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), and clang::FunctionProtoType::hasTrailingReturn().
dropDefaultArgs()
static CallExpr::arg_range dropDefaultArgs (CallExpr::arg_range Args) static
Definition at line 158 of file BuildTree.cpp.
References clang::isa().
foldExplicitTemplateInstantiation()
void foldExplicitTemplateInstantiation (ArrayRef< syntax::Token > Range, const syntax::Token * ExternKW, const syntax::Token * TemplateKW, syntax::SimpleDeclaration * InnerDeclaration, Decl * From)
Definition at line 1651 of file BuildTree.cpp.
References allocator(), and clang::syntax::Token::kind().
foldList()
Builder foldList (DeclarationRange , DL , nullptr)
foldNode() [1/2]
Builder foldNode (Builder. getRangeRange, N , nullptr)
foldNode() [2/2]
Builder foldNode (DeclarationRange , new(allocator()) syntax::SimpleDeclaration , D)
foldTemplateDeclaration()
syntax::TemplateDeclaration * foldTemplateDeclaration (ArrayRef< syntax::Token > Range, const syntax::Token * TemplateKW, ArrayRef< syntax::Token > TemplatedDeclaration, Decl * From)
Definition at line 1664 of file BuildTree.cpp.
References allocator(), clang::syntax::Token::kind(), and N.
getOperatorNodeKind()
static syntax::NodeKind getOperatorNodeKind (const CXXOperatorCallExpr & E) static
Definition at line 164 of file BuildTree.cpp.
References clang::CallExpr::getNumArgs(), clang::CXXOperatorCallExpr::getOperator(), clang::NUM_OVERLOADED_OPERATORS, and clang::OO_None.
getQualifiedNameStart()
static SourceLocation getQualifiedNameStart (NamedDecl * D) static
Get the start of the qualified name.
In the examples below it gives the location of the ^: int ^a; int *^a; int ^a::S::f(){}
Definition at line 250 of file BuildTree.cpp.
References clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), and clang::DeclarationName::isIdentifier().
if() [1/2]
if (!Builder. isResponsibleForCreatingDeclarationD)
Definition at line 1605 of file BuildTree.cpp.
if() [2/2]
if (!Range. getBegin).isValid()
Gets the range of the initializer inside an init-declarator C++ [dcl.decl].
int a; -> range of `, /int *a = nullptr-> range of= nullptr. /int a{}-> range of{}. /int a()-> range of()`. static SourceRange getInitializerRange(Decl *D) { if (auto *V = dyn_cast<VarDecl>(D)) { auto *I = V->getInit(); Initializers in range-based-for are not part of the declarator if (I && !V->isCXXForRangeDecl()) return I->getSourceRange(); }
return SourceRange(); }
/ Gets the range of declarator as defined by the C++ grammar. E.g. / int a; -> range of a, / int *a; -> range of *a, / int a[10]; -> range of a[10], / int a[1][2][3]; -> range of a[1][2][3], / int *a = nullptr -> range of *a = nullptr. / int S::f(){} -> range of S::f(). / FIXME: Name must be a source range. static SourceRange getDeclaratorRange(const SourceManager &SM, TypeLoc T, SourceLocation Name, SourceRange Initializer) { SourceLocation Start = GetStartLoc().Visit(T); SourceLocation End = T.getEndLoc(); if (Name.isValid()) { if (Start.isInvalid()) Start = Name; End of TypeLoc could be invalid if the type is invalid, fallback to the NameLoc. if (End.isInvalid() || SM.isBeforeInTranslationUnit(End, Name)) End = Name; } if (Initializer.isValid()) { auto InitializerEnd = Initializer.getEnd(); assert(SM.isBeforeInTranslationUnit(End, InitializerEnd) || End == InitializerEnd); End = InitializerEnd; } return SourceRange(Start, End); }
namespace { / All AST hierarchy roots that can be represented as pointers. using ASTPtr = llvm::PointerUnion<Stmt *, Decl *>; / Maintains a mapping from AST to syntax tree nodes. This class will get more / complicated as we support more kinds of AST nodes, e.g. TypeLocs. / FIXME: expose this as public API. class ASTToSyntaxMapping { public: void add(ASTPtr From, syntax::Tree *To) { assert(To != nullptr); assert(!From.isNull());
bool Added = Nodes.insert({From, To}).second; (void)Added; assert(Added && "mapping added twice"); }
void add(NestedNameSpecifierLoc From, syntax::Tree *To) { assert(To != nullptr); assert(From.hasQualifier());
bool Added = NNSNodes.insert({From, To}).second; (void)Added; assert(Added && "mapping added twice"); }
syntax::Tree *find(ASTPtr P) const { return Nodes.lookup(P); }
syntax::Tree *find(NestedNameSpecifierLoc P) const { return NNSNodes.lookup(P); }
private: llvm::DenseMap<ASTPtr, syntax::Tree *> Nodes; llvm::DenseMap<NestedNameSpecifierLoc, syntax::Tree *> NNSNodes; }; } // namespace
/ A helper class for constructing the syntax tree while traversing a clang / AST. / / At each point of the traversal we maintain a list of pending nodes. / Initially all tokens are added as pending nodes. When processing a clang AST / node, the clients need to: / - create a corresponding syntax node, / - assign roles to all pending child nodes with 'markChild' and / 'markChildToken', / - replace the child nodes with the new syntax node in the pending list / with 'foldNode'. / / Note that all children are expected to be processed when building a node. / / Call finalize() to finish building the tree and consume the root node. class syntax::TreeBuilder { public: TreeBuilder(syntax::Arena &Arena, TokenBufferTokenManager& TBTM) : Arena(Arena), TBTM(TBTM), Pending(Arena, TBTM.tokenBuffer()) { for (const auto &T : TBTM.tokenBuffer().expandedTokens()) LocationToToken.insert({T.location(), &T}); }
llvm::BumpPtrAllocator &allocator() { return Arena.getAllocator(); } const SourceManager &sourceManager() const { return TBTM.sourceManager(); }
/ Populate children for New node, assuming it covers tokens from / Range. void foldNode(ArrayRef<syntax::Token> Range, syntax::Tree *New, ASTPtr From) { assert(New); Pending.foldChildren(TBTM.tokenBuffer(), Range, New); if (From) Mapping.add(From, New); }
void foldNode(ArrayRef<syntax::Token> Range, syntax::Tree *New, TypeLoc L) { FIXME: add mapping for TypeLocs foldNode(Range, New, nullptr); }
void foldNode(llvm::ArrayRef<syntax::Token> Range, syntax::Tree *New, NestedNameSpecifierLoc From) { assert(New); Pending.foldChildren(TBTM.tokenBuffer(), Range, New); if (From) Mapping.add(From, New); }
/ Populate children for New list, assuming it covers tokens from a / subrange of SuperRange. void foldList(ArrayRef<syntax::Token> SuperRange, syntax::List *New, ASTPtr From) { assert(New); auto ListRange = Pending.shrinkToFitList(SuperRange); Pending.foldChildren(TBTM.tokenBuffer(), ListRange, New); if (From) Mapping.add(From, New); }
/ Notifies that we should not consume trailing semicolon when computing / token range of D. void noticeDeclWithoutSemicolon(Decl *D);
/ Mark the Child node with a corresponding Role. All marked children / should be consumed by foldNode. / When called on expressions (clang::Expr is derived from clang::Stmt), / wraps expressions into expression statement. void markStmtChild(Stmt *Child, NodeRole Role); / Should be called for expressions in non-statement position to avoid / wrapping into expression statement. void markExprChild(Expr *Child, NodeRole Role); / Set role for a token starting at Loc. void markChildToken(SourceLocation Loc, NodeRole R); / Set role for T. void markChildToken(const syntax::Token *T, NodeRole R);
/ Set role for N. void markChild(syntax::Node *N, NodeRole R); / Set role for the syntax node matching N. void markChild(ASTPtr N, NodeRole R); / Set role for the syntax node matching N. void markChild(NestedNameSpecifierLoc N, NodeRole R);
/ Finish building the tree and consume the root node. syntax::TranslationUnit *finalize() && { auto Tokens = TBTM.tokenBuffer().expandedTokens(); assert(!Tokens.empty()); assert(Tokens.back().kind() == tok::eof);
Build the root of the tree, consuming all the children. Pending.foldChildren(TBTM.tokenBuffer(), Tokens.drop_back(), new (Arena.getAllocator()) syntax::TranslationUnit);
auto *TU = cast<syntax::TranslationUnit>(std::move(Pending).finalize()); TU->assertInvariantsRecursive(); return TU; }
/ Finds a token starting at L. The token must exist if L is valid. const syntax::Token *findToken(SourceLocation L) const;
/ Finds the syntax tokens corresponding to the SourceRange. ArrayRef<syntax::Token> getRange(SourceRange Range) const { assert(Range.isValid()); return getRange(Range.getBegin(), Range.getEnd()); }
/ Finds the syntax tokens corresponding to the passed source locations. / First is the start position of the first token and Last is the start / position of the last token. ArrayRef<syntax::Token> getRange(SourceLocation First, SourceLocation Last) const { assert(First.isValid()); assert(Last.isValid()); assert(First == Last || TBTM.sourceManager().isBeforeInTranslationUnit(First, Last)); return llvm::ArrayRef(findToken(First), std::next(findToken(Last))); }
ArrayRef<syntax::Token> getTemplateRange(const ClassTemplateSpecializationDecl *D) const { auto Tokens = getRange(D->getSourceRange()); return maybeAppendSemicolon(Tokens, D); }
/ Returns true if D is the last declarator in a chain and is thus / reponsible for creating SimpleDeclaration for the whole chain. bool isResponsibleForCreatingDeclaration(const Decl *D) const { assert((isa<DeclaratorDecl, TypedefNameDecl>(D)) && "only DeclaratorDecl and TypedefNameDecl are supported.");
const Decl *Next = D->getNextDeclInContext();
There's no next sibling, this one is responsible. if (Next == nullptr) { return true; }
Next sibling is not the same type, this one is responsible. if (D->getKind() != Next->getKind()) { return true; } Next sibling doesn't begin at the same loc, it must be a different declaration, so this declarator is responsible. if (Next->getBeginLoc() != D->getBeginLoc()) { return true; }
NextT is a member of the same declaration, and we need the last member to create declaration. This one is not responsible. return false; }
ArrayRef<syntax::Token> getDeclarationRange(Decl *D) { ArrayRef<syntax::Token> Tokens; We want to drop the template parameters for specializations. if (const auto *S = dyn_cast<TagDecl>(D)) Tokens = getRange(S->TypeDecl::getBeginLoc(), S->getEndLoc()); else Tokens = getRange(D->getSourceRange()); return maybeAppendSemicolon(Tokens, D); }
ArrayRef<syntax::Token> getExprRange(const Expr *E) const { return getRange(E->getSourceRange()); }
/ Find the adjusted range for the statement, consuming the trailing / semicolon when needed. ArrayRef<syntax::Token> getStmtRange(const Stmt *S) const { auto Tokens = getRange(S->getSourceRange()); if (isa<CompoundStmt>(S)) return Tokens;
Some statements miss a trailing semicolon, e.g. 'return', 'continue' and all statements that end with those. Consume this semicolon here. if (Tokens.back().kind() == tok::semi) return Tokens; return withTrailingSemicolon(Tokens); }
private: ArrayRef<syntax::Token> maybeAppendSemicolon(ArrayRef<syntax::Token> Tokens, const Decl *D) const { if (isa<NamespaceDecl>(D)) return Tokens; if (DeclsWithoutSemicolons.count(D)) return Tokens; FIXME: do not consume trailing semicolon on function definitions. Most declarations own a semicolon in syntax trees, but not in clang AST. return withTrailingSemicolon(Tokens); }
ArrayRef<syntax::Token> withTrailingSemicolon(ArrayRef<syntax::Token> Tokens) const { assert(!Tokens.empty()); assert(Tokens.back().kind() != tok::eof); We never consume 'eof', so looking at the next token is ok. if (Tokens.back().kind() != tok::semi && Tokens.end()->kind() == tok::semi) return llvm::ArrayRef(Tokens.begin(), Tokens.end() + 1); return Tokens; }
void setRole(syntax::Node *N, NodeRole R) { assert(N->getRole() == NodeRole::Detached); N->setRole(R); }
/ A collection of trees covering the input tokens. / When created, each tree corresponds to a single token in the file. / Clients call 'foldChildren' to attach one or more subtrees to a parent / node and update the list of trees accordingly. / / Ensures that added nodes properly nest and cover the whole token stream. struct Forest { Forest(syntax::Arena &A, const syntax::TokenBuffer &TB) { assert(!TB.expandedTokens().empty()); assert(TB.expandedTokens().back().kind() == tok::eof); Create all leaf nodes. Note that we do not have 'eof' in the tree. for (const auto &T : TB.expandedTokens().drop_back()) { auto *L = new (A.getAllocator()) syntax::Leaf(reinterpret_cast<TokenManager::Key>(&T)); L->Original = true; L->CanModify = TB.spelledForExpanded(T).has_value(); Trees.insert(Trees.end(), {&T, L}); } }
void assignRole(ArrayRef<syntax::Token> Range, syntax::NodeRole Role) { assert(!Range.empty()); auto It = Trees.lower_bound(Range.begin()); assert(It != Trees.end() && "no node found"); assert(It->first == Range.begin() && "no child with the specified range"); assert((std::next(It) == Trees.end() || std::next(It)->first == Range.end()) && "no child with the specified range"); assert(It->second->getRole() == NodeRole::Detached && "re-assigning role for a child"); It->second->setRole(Role); }
/ Shrink Range to a subrange that only contains tokens of a list. / List elements and delimiters should already have correct roles. ArrayRef<syntax::Token> shrinkToFitList(ArrayRef<syntax::Token> Range) { auto BeginChildren = Trees.lower_bound(Range.begin()); assert((BeginChildren == Trees.end() || BeginChildren->first == Range.begin()) && "Range crosses boundaries of existing subtrees");
auto EndChildren = Trees.lower_bound(Range.end()); assert((EndChildren == Trees.end() || EndChildren->first == Range.end()) && "Range crosses boundaries of existing subtrees");
auto BelongsToList = [](decltype(Trees)::value_type KV) { auto Role = KV.second->getRole(); return Role == syntax::NodeRole::ListElement || Role == syntax::NodeRole::ListDelimiter; };
auto BeginListChildren = std::find_if(BeginChildren, EndChildren, BelongsToList);
auto EndListChildren = std::find_if_not(BeginListChildren, EndChildren, BelongsToList);
return ArrayRef<syntax::Token>(BeginListChildren->first, EndListChildren->first); }
/ Add Node to the forest and attach child nodes based on Tokens. void foldChildren(const syntax::TokenBuffer &TB, ArrayRef<syntax::Token> Tokens, syntax::Tree *Node) { Attach children to Node. assert(Node->getFirstChild() == nullptr && "node already has children");
auto *FirstToken = Tokens.begin(); auto BeginChildren = Trees.lower_bound(FirstToken);
assert((BeginChildren == Trees.end() || BeginChildren->first == FirstToken) && "fold crosses boundaries of existing subtrees"); auto EndChildren = Trees.lower_bound(Tokens.end()); assert((EndChildren == Trees.end() || EndChildren->first == Tokens.end()) && "fold crosses boundaries of existing subtrees");
for (auto It = BeginChildren; It != EndChildren; ++It) { auto *C = It->second; if (C->getRole() == NodeRole::Detached) C->setRole(NodeRole::Unknown); Node->appendChildLowLevel(C); }
Mark that this node came from the AST and is backed by the source code. Node->Original = true; Node->CanModify = TB.spelledForExpanded(Tokens).has_value();
Trees.erase(BeginChildren, EndChildren); Trees.insert({FirstToken, Node}); }
EXPECTS: all tokens were consumed and are owned by a single root node. syntax::Node *finalize() && { assert(Trees.size() == 1); auto *Root = Trees.begin()->second; Trees = {}; return Root; }
std::string str(const syntax::TokenBufferTokenManager &STM) const { std::string R; for (auto It = Trees.begin(); It != Trees.end(); ++It) { unsigned CoveredTokens = It != Trees.end() ? (std::next(It)->first - It->first) : STM.tokenBuffer().expandedTokens().end() - It->first;
R += std::string(formatv("- '{0}' covers '{1}'+{2} tokens\n", It->second->getKind(), It->first->text(STM.sourceManager()), CoveredTokens)); R += It->second->dump(STM); } return R; }
private: / Maps from the start token to a subtree starting at that token. / Keys in the map are pointers into the array of expanded tokens, so / pointer order corresponds to the order of preprocessor tokens. std::map<const syntax::Token *, syntax::Node *> Trees; };
/ For debugging purposes. std::string str() { return Pending.str(TBTM); }
syntax::Arena &Arena; TokenBufferTokenManager& TBTM; / To quickly find tokens by their start location. llvm::DenseMap<SourceLocation, const syntax::Token *> LocationToToken; Forest Pending; llvm::DenseSet<Decl *> DeclsWithoutSemicolons; ASTToSyntaxMapping Mapping; };
namespace { class BuildTreeVisitor : public RecursiveASTVisitor<BuildTreeVisitor> { public: explicit BuildTreeVisitor(ASTContext &Context, syntax::TreeBuilder &Builder) : Builder(Builder), Context(Context) {}
bool shouldTraversePostOrder() const { return true; }
bool WalkUpFromDeclaratorDecl(DeclaratorDecl *DD) { return processDeclaratorAndDeclaration(DD); }
bool WalkUpFromTypedefNameDecl(TypedefNameDecl *TD) { return processDeclaratorAndDeclaration(TD); }
bool VisitDecl(Decl *D) { assert(!D->isImplicit()); Builder.foldNode(Builder.getDeclarationRange(D), new (allocator()) syntax::UnknownDeclaration(), D); return true; }
RAV does not call WalkUpFrom* on explicit instantiations, so we have to override Traverse. FIXME: make RAV call WalkUpFrom* instead. bool TraverseClassTemplateSpecializationDecl(ClassTemplateSpecializationDecl *C) { if (!RecursiveASTVisitor::TraverseClassTemplateSpecializationDecl(C)) return false; if (C->isExplicitSpecialization()) return true; // we are only interested in explicit instantiations. auto *Declaration = cast<syntax::SimpleDeclaration>(handleFreeStandingTagDecl(C)); foldExplicitTemplateInstantiation(Builder.getTemplateRange(C), Builder.findToken(C->getExternLoc()), Builder.findToken(C->getTemplateKeywordLoc()), Declaration, C); return true; }
bool WalkUpFromTemplateDecl(TemplateDecl *S) { foldTemplateDeclaration(Builder.getDeclarationRange(S), Builder.findToken(S->getTemplateParameters()->getTemplateLoc()), Builder.getDeclarationRange(S->getTemplatedDecl()), S); return true; }
bool WalkUpFromTagDecl(TagDecl *C) { FIXME: build the ClassSpecifier node. if (!C->isFreeStanding()) { assert(C->getNumTemplateParameterLists() == 0); return true; } handleFreeStandingTagDecl(C); return true; }
syntax::Declaration *handleFreeStandingTagDecl(TagDecl *C) { assert(C->isFreeStanding()); Class is a declaration specifier and needs a spanning declaration node. auto DeclarationRange = Builder.getDeclarationRange(C); syntax::Declaration *Result = new (allocator()) syntax::SimpleDeclaration; Builder.foldNode(DeclarationRange, Result, nullptr);
Build TemplateDeclaration nodes if we had template parameters. auto ConsumeTemplateParameters = [&](const TemplateParameterList &L) { const auto *TemplateKW = Builder.findToken(L.getTemplateLoc()); auto R = llvm::ArrayRef(TemplateKW, DeclarationRange.end()); Result = foldTemplateDeclaration(R, TemplateKW, DeclarationRange, nullptr); DeclarationRange = R; }; if (auto *S = dyn_cast<ClassTemplatePartialSpecializationDecl>(C)) ConsumeTemplateParameters(*S->getTemplateParameters()); for (unsigned I = C->getNumTemplateParameterLists(); 0 < I; –I) ConsumeTemplateParameters(*C->getTemplateParameterList(I - 1)); return Result; }
bool WalkUpFromTranslationUnitDecl(TranslationUnitDecl *TU) { We do not want to call VisitDecl(), the declaration for translation unit is built by finalize(). return true; }
bool WalkUpFromCompoundStmt(CompoundStmt *S) { using NodeRole = syntax::NodeRole;
Builder.markChildToken(S->getLBracLoc(), NodeRole::OpenParen); for (auto *Child : S->body()) Builder.markStmtChild(Child, NodeRole::Statement); Builder.markChildToken(S->getRBracLoc(), NodeRole::CloseParen);
Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::CompoundStatement, S); return true; }
Some statements are not yet handled by syntax trees. bool WalkUpFromStmt(Stmt *S) { Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::UnknownStatement, S); return true; }
bool TraverseIfStmt(IfStmt *S) { bool Result = [&, this]() { if (S->getInit() && !TraverseStmt(S->getInit())) { return false; } In cases where the condition is an initialized declaration in a statement, we want to preserve the declaration and ignore the implicit condition expression in the syntax tree. if (S->hasVarStorage()) { if (!TraverseStmt(S->getConditionVariableDeclStmt())) return false; } else if (S->getCond() && !TraverseStmt(S->getCond())) return false;
if (S->getThen() && !TraverseStmt(S->getThen())) return false; if (S->getElse() && !TraverseStmt(S->getElse())) return false; return true; }(); WalkUpFromIfStmt(S); return Result; }
bool TraverseCXXForRangeStmt(CXXForRangeStmt *S) { We override to traverse range initializer as VarDecl. RAV traverses it as a statement, we produce invalid node kinds in that case. FIXME: should do this in RAV instead? bool Result = [&, this]() { if (S->getInit() && !TraverseStmt(S->getInit())) return false; if (S->getLoopVariable() && !TraverseDecl(S->getLoopVariable())) return false; if (S->getRangeInit() && !TraverseStmt(S->getRangeInit())) return false; if (S->getBody() && !TraverseStmt(S->getBody())) return false; return true; }(); WalkUpFromCXXForRangeStmt(S); return Result; }
bool TraverseStmt(Stmt *S) { if (auto *DS = dyn_cast_or_null<DeclStmt>(S)) { We want to consume the semicolon, make sure SimpleDeclaration does not. for (auto *D : DS->decls()) Builder.noticeDeclWithoutSemicolon(D); } else if (auto *E = dyn_cast_or_null<Expr>(S)) { return RecursiveASTVisitor::TraverseStmt(IgnoreImplicit(E)); } return RecursiveASTVisitor::TraverseStmt(S); }
bool TraverseOpaqueValueExpr(OpaqueValueExpr *VE) { OpaqueValue doesn't correspond to concrete syntax, ignore it. return true; }
Some expressions are not yet handled by syntax trees. bool WalkUpFromExpr(Expr *E) { assert(!isImplicitExpr(E) && "should be handled by TraverseStmt"); Builder.foldNode(Builder.getExprRange(E), new (allocator()) syntax::UnknownExpression, E); return true; }
bool TraverseUserDefinedLiteral(UserDefinedLiteral *S) { The semantic AST node UserDefinedLiteral (UDL) may have one child node referencing the location of the UDL suffix (_w in 1.2_w). The UDL suffix location does not point to the beginning of a token, so we can't represent the UDL suffix as a separate syntax tree node.
return WalkUpFromUserDefinedLiteral(S);
}
syntax::UserDefinedLiteralExpression * buildUserDefinedLiteral(UserDefinedLiteral *S) { switch (S->getLiteralOperatorKind()) { case UserDefinedLiteral::LOK_Integer: return new (allocator()) syntax::IntegerUserDefinedLiteralExpression; case UserDefinedLiteral::LOK_Floating: return new (allocator()) syntax::FloatUserDefinedLiteralExpression; case UserDefinedLiteral::LOK_Character: return new (allocator()) syntax::CharUserDefinedLiteralExpression; case UserDefinedLiteral::LOK_String: return new (allocator()) syntax::StringUserDefinedLiteralExpression; case UserDefinedLiteral::LOK_Raw: case UserDefinedLiteral::LOK_Template: For raw literal operator and numeric literal operator template we cannot get the type of the operand in the semantic AST. We get this information from the token. As integer and floating point have the same token kind, we run NumericLiteralParser again to distinguish them. auto TokLoc = S->getBeginLoc(); auto TokSpelling = Builder.findToken(TokLoc)->text(Context.getSourceManager()); auto Literal = NumericLiteralParser(TokSpelling, TokLoc, Context.getSourceManager(), Context.getLangOpts(), Context.getTargetInfo(), Context.getDiagnostics()); if (Literal.isIntegerLiteral()) return new (allocator()) syntax::IntegerUserDefinedLiteralExpression; else { assert(Literal.isFloatingLiteral()); return new (allocator()) syntax::FloatUserDefinedLiteralExpression; } } llvm_unreachable("Unknown literal operator kind."); }
bool WalkUpFromUserDefinedLiteral(UserDefinedLiteral *S) { Builder.markChildToken(S->getBeginLoc(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), buildUserDefinedLiteral(S), S); return true; }
FIXME: Fix NestedNameSpecifierLoc::getLocalSourceRange for the DependentTemplateSpecializationType case. / Given a nested-name-specifier return the range for the last name / specifier. / / e.g. std::T::template X<U>:: => template X<U>:: SourceRange getLocalSourceRange(const NestedNameSpecifierLoc &NNSLoc) { auto SR = NNSLoc.getLocalSourceRange();
The method NestedNameSpecifierLoc::getLocalSourceRange should return the desired SourceRange, but there is a corner case. For a DependentTemplateSpecializationType this method returns its qualifiers as well, in other words in the example above this method returns T::template X<U>:: instead of only template X<U>:: if (auto TL = NNSLoc.getTypeLoc()) { if (auto DependentTL = TL.getAs<DependentTemplateSpecializationTypeLoc>()) { The 'template' keyword is always present in dependent template specializations. Except in the case of incorrect code TODO: Treat the case of incorrect code. SR.setBegin(DependentTL.getTemplateKeywordLoc()); } }
return SR; }
syntax::NodeKind getNameSpecifierKind(const NestedNameSpecifier &NNS) { switch (NNS.getKind()) { case NestedNameSpecifier::Global: return syntax::NodeKind::GlobalNameSpecifier; case NestedNameSpecifier::Namespace: case NestedNameSpecifier::NamespaceAlias: case NestedNameSpecifier::Identifier: return syntax::NodeKind::IdentifierNameSpecifier; case NestedNameSpecifier::TypeSpecWithTemplate: return syntax::NodeKind::SimpleTemplateNameSpecifier; case NestedNameSpecifier::TypeSpec: { const auto *NNSType = NNS.getAsType(); assert(NNSType); if (isa<DecltypeType>(NNSType)) return syntax::NodeKind::DecltypeNameSpecifier; if (isa<TemplateSpecializationType, DependentTemplateSpecializationType>(NNSType)) return syntax::NodeKind::SimpleTemplateNameSpecifier; return syntax::NodeKind::IdentifierNameSpecifier; } default: FIXME: Support Microsoft's __super llvm::report_fatal_error("We don't yet support the __super specifier", true); } }
syntax::NameSpecifier * buildNameSpecifier(const NestedNameSpecifierLoc &NNSLoc) { assert(NNSLoc.hasQualifier()); auto NameSpecifierTokens = Builder.getRange(getLocalSourceRange(NNSLoc)).drop_back(); switch (getNameSpecifierKind(NNSLoc.getNestedNameSpecifier())) { case syntax::NodeKind::GlobalNameSpecifier: return new (allocator()) syntax::GlobalNameSpecifier; case syntax::NodeKind::IdentifierNameSpecifier: { assert(NameSpecifierTokens.size() == 1); Builder.markChildToken(NameSpecifierTokens.begin(), syntax::NodeRole::Unknown); auto *NS = new (allocator()) syntax::IdentifierNameSpecifier; Builder.foldNode(NameSpecifierTokens, NS, nullptr); return NS; } case syntax::NodeKind::SimpleTemplateNameSpecifier: { TODO: Build SimpleTemplateNameSpecifier children and implement accessors to them. Be aware, we cannot do that simply by calling TraverseTypeLoc, some TypeLocs have inside them the previous name specifier and we want to treat them independently. auto *NS = new (allocator()) syntax::SimpleTemplateNameSpecifier; Builder.foldNode(NameSpecifierTokens, NS, nullptr); return NS; } case syntax::NodeKind::DecltypeNameSpecifier: { const auto TL = NNSLoc.getTypeLoc().castAs<DecltypeTypeLoc>(); if (!RecursiveASTVisitor::TraverseDecltypeTypeLoc(TL)) return nullptr; auto *NS = new (allocator()) syntax::DecltypeNameSpecifier; TODO: Implement accessor to DecltypeNameSpecifier inner DecltypeTypeLoc. For that add mapping from TypeLoc to `syntaxNode` then: Builder.markChild(TypeLoc, syntax::NodeRole); Builder.foldNode(NameSpecifierTokens, NS, nullptr); return NS; } default: llvm_unreachable("getChildKind() does not return this value"); } }
To build syntax tree nodes for NestedNameSpecifierLoc we override Traverse instead of WalkUpFrom because we want to traverse the children ourselves and build a list instead of a nested tree of name specifier prefixes. bool TraverseNestedNameSpecifierLoc(NestedNameSpecifierLoc QualifierLoc) { if (!QualifierLoc) return true; for (auto It = QualifierLoc; It; It = It.getPrefix()) { auto *NS = buildNameSpecifier(It); if (!NS) return false; Builder.markChild(NS, syntax::NodeRole::ListElement); Builder.markChildToken(It.getEndLoc(), syntax::NodeRole::ListDelimiter); } Builder.foldNode(Builder.getRange(QualifierLoc.getSourceRange()), new (allocator()) syntax::NestedNameSpecifier, QualifierLoc); return true; }
syntax::IdExpression *buildIdExpression(NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKeywordLoc, SourceRange UnqualifiedIdLoc, ASTPtr From) { if (QualifierLoc) { Builder.markChild(QualifierLoc, syntax::NodeRole::Qualifier); if (TemplateKeywordLoc.isValid()) Builder.markChildToken(TemplateKeywordLoc, syntax::NodeRole::TemplateKeyword); }
auto *TheUnqualifiedId = new (allocator()) syntax::UnqualifiedId; Builder.foldNode(Builder.getRange(UnqualifiedIdLoc), TheUnqualifiedId, nullptr); Builder.markChild(TheUnqualifiedId, syntax::NodeRole::UnqualifiedId);
auto IdExpressionBeginLoc = QualifierLoc ? QualifierLoc.getBeginLoc() : UnqualifiedIdLoc.getBegin();
auto *TheIdExpression = new (allocator()) syntax::IdExpression; Builder.foldNode(Builder.getRange(IdExpressionBeginLoc, UnqualifiedIdLoc.getEnd()), TheIdExpression, From);
return TheIdExpression; }
bool WalkUpFromMemberExpr(MemberExpr *S) { For MemberExpr with implicit this-> we generate a simple id-expression syntax node, beacuse an implicit member-expression is syntactically undistinguishable from an id-expression if (S->isImplicitAccess()) { buildIdExpression(S->getQualifierLoc(), S->getTemplateKeywordLoc(), SourceRange(S->getMemberLoc(), S->getEndLoc()), S); return true; }
auto *TheIdExpression = buildIdExpression(S->getQualifierLoc(), S->getTemplateKeywordLoc(), SourceRange(S->getMemberLoc(), S->getEndLoc()), nullptr);
Builder.markChild(TheIdExpression, syntax::NodeRole::Member);
Builder.markExprChild(S->getBase(), syntax::NodeRole::Object); Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::AccessToken);
Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::MemberExpression, S); return true; }
bool WalkUpFromDeclRefExpr(DeclRefExpr *S) { buildIdExpression(S->getQualifierLoc(), S->getTemplateKeywordLoc(), SourceRange(S->getLocation(), S->getEndLoc()), S);
return true; }
Same logic as DeclRefExpr. bool WalkUpFromDependentScopeDeclRefExpr(DependentScopeDeclRefExpr *S) { buildIdExpression(S->getQualifierLoc(), S->getTemplateKeywordLoc(), SourceRange(S->getLocation(), S->getEndLoc()), S);
return true; }
bool WalkUpFromCXXThisExpr(CXXThisExpr *S) { if (!S->isImplicit()) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::IntroducerKeyword); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::ThisExpression, S); } return true; }
bool WalkUpFromParenExpr(ParenExpr *S) { Builder.markChildToken(S->getLParen(), syntax::NodeRole::OpenParen); Builder.markExprChild(S->getSubExpr(), syntax::NodeRole::SubExpression); Builder.markChildToken(S->getRParen(), syntax::NodeRole::CloseParen); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::ParenExpression, S); return true; }
bool WalkUpFromIntegerLiteral(IntegerLiteral *S) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::IntegerLiteralExpression, S); return true; }
bool WalkUpFromCharacterLiteral(CharacterLiteral *S) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::CharacterLiteralExpression, S); return true; }
bool WalkUpFromFloatingLiteral(FloatingLiteral *S) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::FloatingLiteralExpression, S); return true; }
bool WalkUpFromStringLiteral(StringLiteral *S) { Builder.markChildToken(S->getBeginLoc(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::StringLiteralExpression, S); return true; }
bool WalkUpFromCXXBoolLiteralExpr(CXXBoolLiteralExpr *S) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::BoolLiteralExpression, S); return true; }
bool WalkUpFromCXXNullPtrLiteralExpr(CXXNullPtrLiteralExpr *S) { Builder.markChildToken(S->getLocation(), syntax::NodeRole::LiteralToken); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::CxxNullPtrExpression, S); return true; }
bool WalkUpFromUnaryOperator(UnaryOperator *S) { Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::OperatorToken); Builder.markExprChild(S->getSubExpr(), syntax::NodeRole::Operand);
if (S->isPostfix()) Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::PostfixUnaryOperatorExpression, S); else Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::PrefixUnaryOperatorExpression, S);
return true; }
bool WalkUpFromBinaryOperator(BinaryOperator *S) { Builder.markExprChild(S->getLHS(), syntax::NodeRole::LeftHandSide); Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::OperatorToken); Builder.markExprChild(S->getRHS(), syntax::NodeRole::RightHandSide); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::BinaryOperatorExpression, S); return true; }
/ Builds CallArguments syntax node from arguments that appear in source / code, i.e. not default arguments. syntax::CallArguments * buildCallArguments(CallExpr::arg_range ArgsAndDefaultArgs) { auto Args = dropDefaultArgs(ArgsAndDefaultArgs); for (auto *Arg : Args) { Builder.markExprChild(Arg, syntax::NodeRole::ListElement); const auto *DelimiterToken = std::next(Builder.findToken(Arg->getEndLoc())); if (DelimiterToken->kind() == clang::tok::TokenKind::comma) Builder.markChildToken(DelimiterToken, syntax::NodeRole::ListDelimiter); }
auto *Arguments = new (allocator()) syntax::CallArguments; if (!Args.empty()) Builder.foldNode(Builder.getRange((*Args.begin())->getBeginLoc(), (*(Args.end() - 1))->getEndLoc()), Arguments, nullptr);
return Arguments; }
bool WalkUpFromCallExpr(CallExpr *S) { Builder.markExprChild(S->getCallee(), syntax::NodeRole::Callee);
const auto *LParenToken = std::next(Builder.findToken(S->getCallee()->getEndLoc())); FIXME: Assert that LParenToken is indeed a l_paren once we have fixed the test on decltype desctructors. if (LParenToken->kind() == clang::tok::l_paren) Builder.markChildToken(LParenToken, syntax::NodeRole::OpenParen);
Builder.markChild(buildCallArguments(S->arguments()), syntax::NodeRole::Arguments);
Builder.markChildToken(S->getRParenLoc(), syntax::NodeRole::CloseParen);
Builder.foldNode(Builder.getRange(S->getSourceRange()), new (allocator()) syntax::CallExpression, S); return true; }
bool WalkUpFromCXXConstructExpr(CXXConstructExpr *S) { Ignore the implicit calls to default constructors. if ((S->getNumArgs() == 0 || isa<CXXDefaultArgExpr>(S->getArg(0))) && S->getParenOrBraceRange().isInvalid()) return true; return RecursiveASTVisitor::WalkUpFromCXXConstructExpr(S); }
bool TraverseCXXOperatorCallExpr(CXXOperatorCallExpr *S) { To construct a syntax tree of the same shape for calls to built-in and user-defined operators, ignore the DeclRefExpr that refers to the operator and treat it as a simple token. Do that by traversing arguments instead of children. for (auto *child : S->arguments()) { A postfix unary operator is declared as taking two operands. The second operand is used to distinguish from its prefix counterpart. In the semantic AST this "phantom" operand is represented as a IntegerLiteral with invalid SourceLocation. We skip visiting this operand because it does not correspond to anything written in source code. if (child->getSourceRange().isInvalid()) { assert(getOperatorNodeKind(*S) == syntax::NodeKind::PostfixUnaryOperatorExpression); continue; } if (!TraverseStmt(child)) return false; } return WalkUpFromCXXOperatorCallExpr(S); }
bool WalkUpFromCXXOperatorCallExpr(CXXOperatorCallExpr *S) { switch (getOperatorNodeKind(*S)) { case syntax::NodeKind::BinaryOperatorExpression: Builder.markExprChild(S->getArg(0), syntax::NodeRole::LeftHandSide); Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::OperatorToken); Builder.markExprChild(S->getArg(1), syntax::NodeRole::RightHandSide); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::BinaryOperatorExpression, S); return true; case syntax::NodeKind::PrefixUnaryOperatorExpression: Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::OperatorToken); Builder.markExprChild(S->getArg(0), syntax::NodeRole::Operand); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::PrefixUnaryOperatorExpression, S); return true; case syntax::NodeKind::PostfixUnaryOperatorExpression: Builder.markChildToken(S->getOperatorLoc(), syntax::NodeRole::OperatorToken); Builder.markExprChild(S->getArg(0), syntax::NodeRole::Operand); Builder.foldNode(Builder.getExprRange(S), new (allocator()) syntax::PostfixUnaryOperatorExpression, S); return true; case syntax::NodeKind::CallExpression: { Builder.markExprChild(S->getArg(0), syntax::NodeRole::Callee);
const auto *LParenToken = std::next(Builder.findToken(S->getArg(0)->getEndLoc())); FIXME: Assert that LParenToken is indeed a l_paren once we have fixed the test on decltype desctructors. if (LParenToken->kind() == clang::tok::l_paren) Builder.markChildToken(LParenToken, syntax::NodeRole::OpenParen);
Builder.markChild(buildCallArguments(CallExpr::arg_range(S->arg_begin() + 1, S->arg_end())), syntax::NodeRole::Arguments);
Builder.markChildToken(S->getRParenLoc(), syntax::NodeRole::CloseParen);
Builder.foldNode(Builder.getRange(S->getSourceRange()), new (allocator()) syntax::CallExpression, S); return true; } case syntax::NodeKind::UnknownExpression: return WalkUpFromExpr(S); default: llvm_unreachable("getOperatorNodeKind() does not return this value"); } }
bool WalkUpFromCXXDefaultArgExpr(CXXDefaultArgExpr *S) { return true; }
bool WalkUpFromNamespaceDecl(NamespaceDecl *S) { auto Tokens = Builder.getDeclarationRange(S); if (Tokens.front().kind() == tok::coloncolon) { Handle nested namespace definitions. Those start at '::' token, e.g. namespace a^b {} FIXME: build corresponding nodes for the name of this namespace. return true; } Builder.foldNode(Tokens, new (allocator()) syntax::NamespaceDefinition, S); return true; }
FIXME: Deleting the TraverseParenTypeLoc override doesn't change test results. Find test coverage or remove it. bool TraverseParenTypeLoc(ParenTypeLoc L) { We reverse order of traversal to get the proper syntax structure. if (!WalkUpFromParenTypeLoc(L)) return false; return TraverseTypeLoc(L.getInnerLoc()); }
bool WalkUpFromParenTypeLoc(ParenTypeLoc L) { Builder.markChildToken(L.getLParenLoc(), syntax::NodeRole::OpenParen); Builder.markChildToken(L.getRParenLoc(), syntax::NodeRole::CloseParen); Builder.foldNode(Builder.getRange(L.getLParenLoc(), L.getRParenLoc()), new (allocator()) syntax::ParenDeclarator, L); return true; }
Declarator chunks, they are produced by type locs and some clang::Decls. bool WalkUpFromArrayTypeLoc(ArrayTypeLoc L) { Builder.markChildToken(L.getLBracketLoc(), syntax::NodeRole::OpenParen); Builder.markExprChild(L.getSizeExpr(), syntax::NodeRole::Size); Builder.markChildToken(L.getRBracketLoc(), syntax::NodeRole::CloseParen); Builder.foldNode(Builder.getRange(L.getLBracketLoc(), L.getRBracketLoc()), new (allocator()) syntax::ArraySubscript, L); return true; }
syntax::ParameterDeclarationList * buildParameterDeclarationList(ArrayRef<ParmVarDecl *> Params) { for (auto *P : Params) { Builder.markChild(P, syntax::NodeRole::ListElement); const auto *DelimiterToken = std::next(Builder.findToken(P->getEndLoc())); if (DelimiterToken->kind() == clang::tok::TokenKind::comma) Builder.markChildToken(DelimiterToken, syntax::NodeRole::ListDelimiter); } auto *Parameters = new (allocator()) syntax::ParameterDeclarationList; if (!Params.empty()) Builder.foldNode(Builder.getRange(Params.front()->getBeginLoc(), Params.back()->getEndLoc()), Parameters, nullptr); return Parameters; }
bool WalkUpFromFunctionTypeLoc(FunctionTypeLoc L) { Builder.markChildToken(L.getLParenLoc(), syntax::NodeRole::OpenParen);
Builder.markChild(buildParameterDeclarationList(L.getParams()), syntax::NodeRole::Parameters);
Builder.markChildToken(L.getRParenLoc(), syntax::NodeRole::CloseParen); Builder.foldNode(Builder.getRange(L.getLParenLoc(), L.getEndLoc()), new (allocator()) syntax::ParametersAndQualifiers, L); return true; }
bool WalkUpFromFunctionProtoTypeLoc(FunctionProtoTypeLoc L) { if (!L.getTypePtr()->hasTrailingReturn()) return WalkUpFromFunctionTypeLoc(L);
auto *TrailingReturnTokens = buildTrailingReturn(L); Finish building the node for parameters. Builder.markChild(TrailingReturnTokens, syntax::NodeRole::TrailingReturn); return WalkUpFromFunctionTypeLoc(L); }
bool TraverseMemberPointerTypeLoc(MemberPointerTypeLoc L) { In the source code "void (Y::*mp)()" MemberPointerTypeLoc corresponds to "Y::*" but it points to a ParenTypeLoc that corresponds to "(Y::*mp)" We thus reverse the order of traversal to get the proper syntax structure. if (!WalkUpFromMemberPointerTypeLoc(L)) return false; return TraverseTypeLoc(L.getPointeeLoc()); }
bool WalkUpFromMemberPointerTypeLoc(MemberPointerTypeLoc L) { auto SR = L.getLocalSourceRange(); Builder.foldNode(Builder.getRange(SR), new (allocator()) syntax::MemberPointer, L); return true; }
The code below is very regular, it could even be generated with some preprocessor magic. We merely assign roles to the corresponding children and fold resulting nodes. bool WalkUpFromDeclStmt(DeclStmt *S) { Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::DeclarationStatement, S); return true; }
bool WalkUpFromNullStmt(NullStmt *S) { Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::EmptyStatement, S); return true; }
bool WalkUpFromSwitchStmt(SwitchStmt *S) { Builder.markChildToken(S->getSwitchLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markStmtChild(S->getBody(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::SwitchStatement, S); return true; }
bool WalkUpFromCaseStmt(CaseStmt *S) { Builder.markChildToken(S->getKeywordLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markExprChild(S->getLHS(), syntax::NodeRole::CaseValue); Builder.markStmtChild(S->getSubStmt(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::CaseStatement, S); return true; }
bool WalkUpFromDefaultStmt(DefaultStmt *S) { Builder.markChildToken(S->getKeywordLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markStmtChild(S->getSubStmt(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::DefaultStatement, S); return true; }
bool WalkUpFromIfStmt(IfStmt *S) { Builder.markChildToken(S->getIfLoc(), syntax::NodeRole::IntroducerKeyword); Stmt *ConditionStatement = S->getCond(); if (S->hasVarStorage()) ConditionStatement = S->getConditionVariableDeclStmt(); Builder.markStmtChild(ConditionStatement, syntax::NodeRole::Condition); Builder.markStmtChild(S->getThen(), syntax::NodeRole::ThenStatement); Builder.markChildToken(S->getElseLoc(), syntax::NodeRole::ElseKeyword); Builder.markStmtChild(S->getElse(), syntax::NodeRole::ElseStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::IfStatement, S); return true; }
bool WalkUpFromForStmt(ForStmt *S) { Builder.markChildToken(S->getForLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markStmtChild(S->getBody(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::ForStatement, S); return true; }
bool WalkUpFromWhileStmt(WhileStmt *S) { Builder.markChildToken(S->getWhileLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markStmtChild(S->getBody(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::WhileStatement, S); return true; }
bool WalkUpFromContinueStmt(ContinueStmt *S) { Builder.markChildToken(S->getContinueLoc(), syntax::NodeRole::IntroducerKeyword); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::ContinueStatement, S); return true; }
bool WalkUpFromBreakStmt(BreakStmt *S) { Builder.markChildToken(S->getBreakLoc(), syntax::NodeRole::IntroducerKeyword); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::BreakStatement, S); return true; }
bool WalkUpFromReturnStmt(ReturnStmt *S) { Builder.markChildToken(S->getReturnLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markExprChild(S->getRetValue(), syntax::NodeRole::ReturnValue); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::ReturnStatement, S); return true; }
bool WalkUpFromCXXForRangeStmt(CXXForRangeStmt *S) { Builder.markChildToken(S->getForLoc(), syntax::NodeRole::IntroducerKeyword); Builder.markStmtChild(S->getBody(), syntax::NodeRole::BodyStatement); Builder.foldNode(Builder.getStmtRange(S), new (allocator()) syntax::RangeBasedForStatement, S); return true; }
bool WalkUpFromEmptyDecl(EmptyDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::EmptyDeclaration, S); return true; }
bool WalkUpFromStaticAssertDecl(StaticAssertDecl *S) { Builder.markExprChild(S->getAssertExpr(), syntax::NodeRole::Condition); Builder.markExprChild(S->getMessage(), syntax::NodeRole::Message); Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::StaticAssertDeclaration, S); return true; }
bool WalkUpFromLinkageSpecDecl(LinkageSpecDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::LinkageSpecificationDeclaration, S); return true; }
bool WalkUpFromNamespaceAliasDecl(NamespaceAliasDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::NamespaceAliasDefinition, S); return true; }
bool WalkUpFromUsingDirectiveDecl(UsingDirectiveDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::UsingNamespaceDirective, S); return true; }
bool WalkUpFromUsingDecl(UsingDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::UsingDeclaration, S); return true; }
bool WalkUpFromUnresolvedUsingValueDecl(UnresolvedUsingValueDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::UsingDeclaration, S); return true; }
bool WalkUpFromUnresolvedUsingTypenameDecl(UnresolvedUsingTypenameDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::UsingDeclaration, S); return true; }
bool WalkUpFromTypeAliasDecl(TypeAliasDecl *S) { Builder.foldNode(Builder.getDeclarationRange(S), new (allocator()) syntax::TypeAliasDeclaration, S); return true; }
private: / Folds SimpleDeclarator node (if present) and in case this is the last / declarator in the chain it also folds SimpleDeclaration node. template <class T> bool processDeclaratorAndDeclaration(T *D) { auto Range = getDeclaratorRange(Builder.sourceManager(), D->getTypeSourceInfo()->getTypeLoc(), getQualifiedNameStart(D), getInitializerRange(D));
There doesn't have to be a declarator (e.g. void foo(int) only has
Definition at line 1593 of file BuildTree.cpp.
References allocator().
IgnoreCXXFunctionalCastExprWrappingConstructor()
static Expr * IgnoreCXXFunctionalCastExprWrappingConstructor (Expr * E) static
Definition at line 72 of file BuildTree.cpp.
Referenced by IgnoreImplicit().
IgnoreImplicit()
static Expr * IgnoreImplicit (Expr * E) static
Definition at line 80 of file BuildTree.cpp.
References IgnoreCXXFunctionalCastExprWrappingConstructor(), clang::IgnoreExprNodes(), IgnoreImplicitConstructorSingleStep(), and clang::IgnoreImplicitSingleStep().
Referenced by isImplicitExpr().
IgnoreImplicitConstructorSingleStep()
static Expr * IgnoreImplicitConstructorSingleStep (Expr * E) static
Definition at line 53 of file BuildTree.cpp.
References clang::C.
Referenced by IgnoreImplicit(), and clang::Expr::IgnoreUnlessSpelledInSource().
isImplicitExpr()
static LLVM_ATTRIBUTE_UNUSED bool isImplicitExpr (Expr * E) static
Definition at line 87 of file BuildTree.cpp.
References IgnoreImplicit().
markChild() [1/2]
Builder markChild (DL , syntax::NodeRole::Declarators)
markChild() [2/2]
Builder markChild (N , syntax::NodeRole::ListElement)
Variable Documentation
Builder
syntax::TreeBuilder& Builder
Definition at line 1679 of file BuildTree.cpp.
Referenced by clang::syntax::buildSyntaxTree().
Context
const ASTContext& Context
Definition at line 1680 of file BuildTree.cpp.
Referenced by clang::syntax::buildSyntaxTree().
DeclarationRange
auto DeclarationRange = Builder.getDeclarationRange(D)
Definition at line 1613 of file BuildTree.cpp.
else
else
Initial value:
{
      auto *DL = new (allocator()) syntax::DeclaratorList
Definition at line 1611 of file BuildTree.cpp.
N
auto* N = new (allocator()) syntax::SimpleDeclarator
Definition at line 1601 of file BuildTree.cpp.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecltypeExpression(), clang::Sema::ActOnFields(), clang::Sema::ActOnModuleImport(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnStringLiteral(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), clang::Sema::ActOnTypeTrait(), clang::Sema::ActOnVarTemplateSpecialization(), clang::ento::ExplodedNodeSet::Add(), addAssociatedClassesAndNamespaces(), clang::Sema::AddBuiltinCandidate(), clang::Sema::AddBuiltinOperatorCandidates(), AddClassMessageCompletions(), clang::ento::FalsePositiveRefutationBRVisitor::addConstraints(), clang::ASTRecordWriter::AddCXXDefinitionData(), AddFunctionParameterChunks(), addFunctionPointerConversion(), clang::diff::SyntaxTree::Impl::addNode(), clang::ento::NodeBuilder::addNodes(), AddObjCBlockCall(), clang::StoredDeclsList::addOrReplaceDecl(), AddSuperSendCompletion(), clang::Sema::AddSurrogateCandidate(), clang::TemplateDeclInstantiator::adjustForRewrite(), clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), advance(), clang::interp::InitMap::allocate(), alreadyExecutedAtLeastOneLoopIteration(), clang::GCCAsmStmt::AnalyzeAsmString(), annotateConsumedSummaryMismatch(), annotateStartParameter(), clang::APValue::APValue(), clang::APValue::APValue(), clang::APValue::APValue(), clang::syntax::Node::assertInvariantsRecursive(), assumeCondition(), clang::ast_matchers::AST_MATCHER_P(), clang::ast_matchers::AST_MATCHER_P(), clang::ast_matchers::AST_MATCHER_P(), clang::ast_matchers::AST_MATCHER_P(), clang::ast_matchers::AST_MATCHER_P2(), clang::ast_matchers::AST_MATCHER_P2(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::ASTVector< T >::ASTVector(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildLambdaExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::transformer::detail::buildMatchers(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildTypeTrait(), clang::BumpVector< T >::BumpVector(), callSpecialFunction(), CastToDerivedClass(), clang::CFGDominatorTreeImpl< IsPostDom >::changeImmediateDominator(), CheckActive(), checkBuiltinTemplateIdType(), clang::Sema::CheckCompleteVariableDeclaration(), CheckConstexprFunctionBody(), checkCUDADeviceBuiltinSurfaceClassTemplate(), checkCUDADeviceBuiltinTextureClassTemplate(), CheckEvaluationResult(), clang::Sema::checkIllFormedTrivialABIStruct(), checkInvariantViolation(), clang::Sema::CheckNonDependentConversions(), checkObjCArrayLiteral(), checkObjCDictionaryLiteral(), checkOpenMPLoop(), checkPreprocessorOptions(), clang::ento::retaincountchecker::RetainCountChecker::checkReturnWithRetEffect(), clang::Sema::CheckTemplatePartialSpecializationArgs(), clang::Sema::checkThisInStaticMemberFunctionAttributes(), clang::Sema::CheckTypeTraitArity(), clang::Sema::CheckVarTemplateId(), llvm::GraphTraits< ::clang::CFGBlock * >::child_begin(), llvm::GraphTraits< clang::CallGraphNode * >::child_begin(), llvm::GraphTraits< clang::DomTreeNode * >::child_begin(), llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_begin(), llvm::GraphTraits< clang::Stmt * >::child_begin(), llvm::GraphTraits< const ::clang::CFGBlock * >::child_begin(), llvm::GraphTraits< const clang::CallGraphNode * >::child_begin(), llvm::GraphTraits< const clang::Stmt * >::child_begin(), llvm::GraphTraits< Inverse< ::clang::CFGBlock * > >::child_begin(), llvm::GraphTraits< Inverse< const ::clang::CFGBlock * > >::child_begin(), llvm::GraphTraits< ::clang::CFGBlock * >::child_end(), llvm::GraphTraits< clang::CallGraphNode * >::child_end(), llvm::GraphTraits< clang::DomTreeNode * >::child_end(), llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_end(), llvm::GraphTraits< clang::Stmt * >::child_end(), llvm::GraphTraits< const ::clang::CFGBlock * >::child_end(), llvm::GraphTraits< const clang::CallGraphNode * >::child_end(), llvm::GraphTraits< const clang::Stmt * >::child_end(), llvm::GraphTraits< Inverse< ::clang::CFGBlock * > >::child_end(), llvm::GraphTraits< Inverse< const ::clang::CFGBlock * > >::child_end(), clang::syntax::TokenBufferTokenManager::classof(), clang::CodeGen::EHCatchScope::clearHandlerBlocks(), clang::Sema::CodeCompleteExpression(), clang::Sema::CodeCompleteModuleImport(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCMethodDeclSelector(), clang::Sema::CodeCompleteObjCSelector(), collectMacroDefinitions(), collectViableConversionCandidates(), clang::DeclarationName::compare(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::serialization::ComputeHash(), computeNodeID(), computeNodeSize(), constructDebugPieceForTrackedCondition(), clang::Sema::containsUnexpandedParameterPacks(), ConvertDeducedTemplateArguments(), CopyObject(), clang::FunctionDecl::Create(), clang::MSPropertyDecl::Create(), clang::OMPDeclareMapperDecl::CreateDeserialized(), clang::OMPRequiresDecl::CreateDeserialized(), clang::OMPThreadPrivateDecl::CreateDeserialized(), clang::OMPAffinityClause::CreateEmpty(), clang::OMPAllocateClause::CreateEmpty(), clang::OMPCopyinClause::CreateEmpty(), clang::OMPCopyprivateClause::CreateEmpty(), clang::OMPDependClause::CreateEmpty(), clang::OMPDoacrossClause::CreateEmpty(), clang::OMPExclusiveClause::CreateEmpty(), clang::OMPFirstprivateClause::CreateEmpty(), clang::OMPFlushClause::CreateEmpty(), clang::OMPInclusiveClause::CreateEmpty(), clang::OMPInitClause::CreateEmpty(), clang::OMPInReductionClause::CreateEmpty(), clang::OMPLastprivateClause::CreateEmpty(), clang::OMPNontemporalClause::CreateEmpty(), clang::OMPPrivateClause::CreateEmpty(), clang::OMPReductionClause::CreateEmpty(), clang::OMPSharedClause::CreateEmpty(), clang::OMPTaskReductionClause::CreateEmpty(), clang::OMPUsesAllocatorsClause::CreateEmpty(), OMPTargetDataDirective::CreateEmpty(), OMPTargetEnterDataDirective::CreateEmpty(), OMPTargetExitDataDirective::CreateEmpty(), clang::interp::Program::createGlobalString(), createMakeIntegerSeqParameterList(), clang::CXXConstructExpr::CXXConstructExpr(), clang::ASTContext::DeallocateDeclListNode(), clang::syntax::deepCopyExpandingMacros(), clang::DEF_TRAVERSE_TYPELOC(), clang::interp::InterpFrame::describe(), diagnoseAmbiguousConversion(), diagnoseAutoModuleImport(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::diagnoseMissingImport(), clang::Sema::DiagnoseMultipleMethodInGlobalPool(), clang::Sema::DiagnoseUnexpandedParameterPacks(), DiagnoseUnexpandedParameterPacks(), clang::Sema::DiagnoseUseOfUnimplementedSelectors(), clang::interp::Function::dump(), clang::LayoutOverrideSource::dump(), clang::serialization::ModuleFile::dump(), clang::ento::ExprEngine::DumpGraph(), clang::syntax::Node::dumpTokens(), clang::DynTypedNodeList::DynTypedNodeList(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), emitBug(), clang::CodeGen::ReductionCodeGen::emitCleanups(), EmitGEPOffsetInBytes(), clang::CodeGen::ReductionCodeGen::emitInitialization(), emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), clang::CodeGen::ReductionCodeGen::emitSharedOrigLValue(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), clang::ento::WorkList::enqueue(), clang::ento::WorkList::enqueue(), clang::ento::CoreEngine::enqueueStmtNode(), EnterNewDeleteCleanup(), clang::Parser::EnterScope(), clang::ento::ExplodedNodeSet::erase(), EvaluateBooleanTypeTrait(), clang::ASTMergeAction::ExecuteAction(), clang::DumpModuleInfoAction::ExecuteAction(), clang::LocalInstantiationScope::Exit(), expandStringLiteral(), clang::ento::ExplodedNodeSet::ExplodedNodeSet(), clang::Sema::FinalizeVarWithDestructor(), clang::ento::LikelyFalsePositiveSuppressionBRVisitor::finalizeVisitor(), clang::Sema::FindAllocationFunctions(), FindDesignatorMismatch(), findExecutedLines(), clang::ASTReader::FindExternalLexicalDecls(), clang::Sema::findInheritingConstructor(), findNodeForExpression(), clang::transformer::detail::findSelectedCase(), findSubobject(), clang::Sema::FinishTemplateArgumentDeduction(), foldTemplateDeclaration(), clang::format::forEachToken(), formatBlockPlaceholder(), formatModuleId(), clang::ento::NodeBuilder::generateNodeImpl(), clang::ento::NodeBuilderWithSinks::generateSink(), clang::SrcMgr::LineOffsetMapping::get(), llvm::IDFCalculatorDetail::ChildrenGetterTy< clang::CFGBlock, IsPostDom >::get(), clang::CodeGen::CodeGenTBAA::getAccessTagInfo(), getAcquireSite(), GetAllocationSite(), getArgumentValueString(), clang::CodeGen::ReductionCodeGen::getBaseDecl(), clang::CodeGen::CodeGenTBAA::getBaseTypeInfo(), getCalleeNode(), clang::ento::PathSensitiveBugReport::getCallStackMessage(), getConcreteIntegerValue(), clang::DiagnosticsEngine::getCustomDiagID(), clang::diff::SyntaxTree::Impl::getDeclValue(), clang::ento::PathSensitiveBugReport::getDeclWithIssue(), getDenomExpr(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), clang::driver::tools::getDwarfVersion(), llvm::GraphTraits< clang::DomTreeNode * >::getEntryNode(), clang::Module::getExportedModules(), clang::FriendDecl::getFriendTypeTemplateParameterList(), clang::DeclarationName::getFromOpaqueInteger(), clang::DeclarationName::getFromOpaquePtr(), GetFullTypeForDeclarator(), clang::NumericLiteralParser::GetIntegerValue(), clang::ento::CheckerContext::getLocationRegionIfPostStore(), getLocationRegionIfReference(), clang::Sema::getLookupModules(), clang::ento::ProgramState::getLValue(), getMatchingCallExitEnd(), clang::ASTContext::getMemberPointerPathAdjustment(), clang::ento::StackHintGeneratorForSymbol::getMessage(), clang::GlobalModuleIndex::getModuleDependencies(), clang::ento::ExplodedNode::getNextStmtForDiagnostics(), clang::ento::NilReceiverBRVisitor::getNilReceiver(), llvm::DOTGraphTraits< ExplodedGraph * >::getNodeLabel(), clang::diff::SyntaxTree::getNodeValue(), clang::diff::SyntaxTree::Impl::getNodeValue(), clang::Sema::getNumArgumentsInExpansion(), getNumDisplayWidth(), clang::CodeGen::ReductionCodeGen::getOrigLValue(), clang::CodeCompleteConsumer::OverloadCandidate::getParamDecl(), clang::CodeCompleteConsumer::OverloadCandidate::getParamType(), getParamType(), getPatternForClassTemplateSpecialization(), getPreferredArgumentTypeForMessageSend(), clang::ento::ExplodedNode::getPreviousStmtForDiagnostics(), clang::Sema::getPrintable(), clang::CodeGen::ReductionCodeGen::getPrivateType(), clang::CodeGen::ReductionCodeGen::getRefExpr(), GetRuntimeFunctionDecl(), clang::CodeGen::ReductionCodeGen::getSharedLValue(), clang::ShuffleVectorExpr::getShuffleMaskIdx(), clang::CodeGen::CGBuilderTy::getSize(), clang::CodeGen::CGBuilderTy::getSize(), clang::CodeGen::EHCatchScope::getSizeForNumHandlers(), clang::CodeGen::ReductionCodeGen::getSizes(), clang::diff::SyntaxTree::getSourceRangeOffsets(), getStmtBeforeCond(), clang::diff::getSubtreePostorder(), getSValForVar(), clang::CodeGen::CodeGenTBAA::getTBAAStructInfo(), clang::Sema::getTemplateArgumentBindingsText(), clang::getTemplateParamsRange(), clang::CodeGen::CodeGenTBAA::getTypeInfo(), clang::ento::retaincountchecker::RetainCountChecker::handleAutoreleaseCounts(), handleCapabilityAttr(), HandleMemberPointerAccess(), HandleOperatorDeleteCall(), HandleOperatorNewCall(), clang::ento::ExprEngine::handleUOExtension(), clang::HeaderSearch::hasModuleMap(), clang::dataflow::hasOptionalClassName(), clang::diff::SyntaxTree::Impl::Impl(), clang::diff::SyntaxTree::Impl::Impl(), clang::ASTImporter::Import(), inheritDefaultTemplateArguments(), clang::SourceManager::initializeForReplay(), clang::Sema::InstantiateFunctionDefinition(), isAtLeastAsSpecializedAs(), clang::ento::isCapturedByReference(), clang::dataflow::isCheckLikeMethod(), IsEquivalentExceptionSpec(), clang::Declarator::isFunctionDeclaratorAFunctionDeclaration(), isInitializationOfVar(), isInterestingExpr(), clang::CharUnits::isMultipleOf(), clang::diff::isNodeExcluded(), llvm::DOTGraphTraits< ExplodedGraph * >::isNodeHidden(), isNullPointerValueTemplateArgument(), clang::ParsedAttr::isParamExpr(), clang::ento::isPossiblyEscaped(), isPreferredLookupResult(), isReferenceCountingPointerDestructor(), isSameAsPrimaryTemplate(), clang::ASTContext::isSameTemplateParameterList(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), isSubstitutedType(), clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs(), clang::Module::isUnimportable(), clang::driver::MultilibBuilder::isValid(), isValidStructGUID(), isVarAnInterestingCondition(), isZeroInitialized(), clang::Sema::LoadExternalVTableUses(), clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl(), clang::CompilerInstance::loadModule(), clang::Preprocessor::LookAhead(), clang::GlobalModuleIndex::lookupIdentifier(), clang::ento::madeNewBranch(), clang::Sema::MarkDeducedTemplateParameters(), clang::Sema::MarkUsedTemplateParameters(), MarkUsedTemplateParameters(), clang::transformer::name(), clang::CodeGen::ReductionCodeGen::needCleanups(), nextPathEntryRange(), llvm::DOTGraphTraits< ExplodedGraph * >::nodeHasBugReport(), llvm::GraphTraits< clang::CFGDomTree * >::nodes_begin(), llvm::GraphTraits< clang::DomTreeNode * >::nodes_begin(), llvm::GraphTraits< clang::CFGDomTree * >::nodes_end(), llvm::GraphTraits< clang::DomTreeNode * >::nodes_end(), NoteFunctionCandidate(), noteNonDeducibleParameters(), clang::CharUnits::operator%(), clang::tooling::stdlib::Recognizer::operator()(), clang::CharUnits::operator*(), clang::CharUnits::operator*=(), clang::CXXRecordDecl::friend_iterator::operator+(), clang::DeclContext::ddiag_iterator::operator+(), clang::CXXRecordDecl::friend_iterator::operator+=(), clang::DeclContext::ddiag_iterator::operator+=(), clang::CharUnits::operator/(), clang::CharUnits::operator/=(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::ASTRecordReader::operator[](), clang::ASTRecordWriter::operator[](), clang::DynTypedNodeList::operator[](), clang::DependencyFileGenerator::outputDependencyFile(), clang::StringLiteral::outputString(), clang::DiagnosticsEngine::overloadCandidatesShown(), clang::PartialDiagnostic::PartialDiagnostic(), clang::ento::ConditionBRVisitor::patternMatch(), peelOffOuterExpr(), llvm::GraphTraits< clang::ento::ExplodedGraph * >::predecessorOfTrivial(), clang::CodeGen::CGCXXABI::AddedStructorArgCounts::prefix(), clang::CallGraph::print(), clang::Module::print(), clang::FunctionProtoType::printExceptionSpecification(), clang::APValue::printPretty(), clang::ento::ConditionBRVisitor::printValue(), clang::ento::ExprEngine::processCallExit(), clang::ento::retaincountchecker::RetainCountChecker::processLeaks(), clang::ento::retaincountchecker::RetainCountChecker::processNonLeakError(), clang::APValue::Profile(), profileIntValue(), clang::ASTRecordWriter::push_back(), clang::CodeGen::EHScopeStack::pushCleanupWithExtra(), clang::ASTReader::ReadAST(), clang::ASTReader::readASTFileControlBlock(), clang::OMPClauseReader::readClause(), clang::ASTReader::ReadDelegatingConstructors(), clang::ASTReader::ReadExtVectorDecls(), clang::serialization::reader::ASTSelectorLookupTrait::ReadKey(), clang::ASTReader::ReadKnownNamespaces(), clang::ASTReader::ReadLateParsedTemplates(), clang::ASTReader::ReadMismatchingDeleteExpressions(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), clang::ASTReader::ReadPendingInstantiations(), clang::ASTReader::ReadTentativeDefinitions(), clang::ASTReader::ReadUndefinedButUsed(), clang::ASTReader::ReadUnusedFileScopedDecls(), clang::ASTReader::ReadUnusedLocalTypedefNameCandidates(), clang::ASTReader::ReadUsedVTables(), clang::ASTReader::ReadWeakUndeclaredIdentifiers(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::ento::retaincountchecker::RefLeakReport::RefLeakReport(), REGISTER_MAP_WITH_PROGRAMSTATE(), clang::syntax::MutationsImpl::remove(), removeRedundantMsgs(), removeUnneededCalls(), clang::ASTUnresolvedSet::reserve(), clang::ASTVector< T >::reserve(), clang::BumpVector< T >::reserve(), clang::LazyASTUnresolvedSet::reserve(), clang::threadSafety::til::SimpleArray< T >::reserveCheck(), clang::ASTVector< T >::resize(), clang::LookupResult::resolveKind(), clang::ASTReader::resolvePendingMacro(), clang::Preprocessor::RevertCachedTokens(), clang::RopePieceBTreeIterator::RopePieceBTreeIterator(), sanitizeFilenameAsIdentifier(), clang::ast_matchers::selectFirst(), clang::syntax::FactoryImpl::setCanModify(), clang::CXXRecordDecl::setCaptures(), clang::targets::M68kTargetInfo::setCPU(), clang::NamedDecl::setDeclName(), clang::ASTReader::SetGloballyVisibleDecls(), clang::DeclarationNameInfo::setName(), clang::Sema::SetParamDefaultArgument(), clang::TargetInfo::ConstraintInfo::setTiedOperand(), setUsedBits(), clang::APValue::setVector(), clang::ASTRecordReader::skipInts(), clang::Sema::SubstituteExplicitTemplateArguments(), substituteParameterMappings(), substituteParameterMappings(), clang::TemplateDeclInstantiator::SubstTemplateParams(), clang::CodeGen::CGCXXABI::AddedStructorArgCounts::suffix(), clang::ento::SuppressInlineDefensiveChecksVisitor::SuppressInlineDefensiveChecksVisitor(), clang::ento::NodeBuilder::takeNodes(), clang::ento::bugreporter::Tracker::track(), clang::SourceManager::translateFile(), llvm::DOTGraphTraits< ExplodedGraph * >::traverseHiddenNodes(), clang::ParentMapContext::traverseIgnored(), clang::RecursiveASTVisitor< Derived >::TraverseStmt(), clang::ento::ExplodedGraph::trim(), clang::UnresolvedSetImpl::truncate(), clang::Sema::tryCaptureVariable(), clang::Interpreter::Undo(), clang::Sema::usesPartialOrExplicitSpecialization(), clang::CodeGen::ReductionCodeGen::usesReductionInitializer(), clang::targets::AMDGPUTargetInfo::validateAsmConstraint(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ento::ExprEngine::Visit(), clang::serialization::ModuleManager::visit(), clang::interp::ByteCodeExprGen< Emitter >::visitArrayInitializer(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ConditionBRVisitor::VisitConditionVariable(), clang::ento::ExprEngine::VisitCXXDestructor(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ASTNodeImporter::VisitDesignatedInitExpr(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ento::ExprEngine::VisitGuardedExpr(), clang::ASTDeclReader::VisitImportDecl(), clang::ASTDeclWriter::VisitImportDecl(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ASTNodeImporter::VisitIndirectFieldDecl(), clang::ASTReader::visitInputFiles(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr(), visitLifetimeBoundArguments(), visitLocalsRetainedByInitializer(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ento::ConditionBRVisitor::VisitNode(), clang::ento::FalsePositiveRefutationBRVisitor::VisitNode(), clang::ento::NilReceiverBRVisitor::VisitNode(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::TagVisitor::VisitNode(), clang::ento::TrackConstraintBRVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), clang::ento::ConditionBRVisitor::VisitNodeImpl(), clang::ASTDeclReader::VisitNonTypeTemplateParmDecl(), clang::ASTDeclWriter::VisitNonTypeTemplateParmDecl(), clang::ASTNodeImporter::VisitOffsetOfExpr(), clang::JSONNodeDumper::VisitPackExpansionType(), clang::TextNodeDumper::VisitPackExpansionType(), clang::ASTDeclReader::VisitRedeclarable(), clang::ASTDeclReader::VisitTemplateTemplateParmDecl(), clang::ASTDeclWriter::VisitTemplateTemplateParmDecl(), clang::ento::ConditionBRVisitor::VisitTerminator(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr(), clang::ento::ExprEngine::VisitUnaryOperator(), and wasRegionOfInterestModifiedAt().
true
return true
Definition at line 1620 of file BuildTree.cpp.