clang: lib/StaticAnalyzer/Checkers/CastValueChecker.cpp File Reference
CastValueChecker.cpp File Reference
#include "clang/AST/DeclTemplate.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicType.h"
#include <optional>
#include <utility>
Functions
static bool isInfeasibleCast (const DynamicCastInfo *CastInfo, bool CastSucceeds)
static const NoteTag * getNoteTag (CheckerContext &C, const DynamicCastInfo *CastInfo, QualType CastToTy, const Expr *Object, bool CastSucceeds, bool IsKnownCast)
static const NoteTag * getNoteTag (CheckerContext &C, SmallVector< QualType, 4 > CastToTyVec, const Expr *Object, bool IsKnownCast)
static QualType alignReferenceTypes (QualType toAlign, QualType alignTowards, ASTContext &ACtx)
static void addCastTransition (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C, bool IsNonNullParam, bool IsNonNullReturn, bool IsCheckedCast=false)
static void addInstanceOfTransition (const CallEvent &Call, DefinedOrUnknownSVal DV, ProgramStateRef State, CheckerContext &C, bool IsInstanceOf)
static void evalNonNullParamNonNullReturn (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C, bool IsCheckedCast=false)
static void evalNonNullParamNullReturn (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C)
static void evalNullParamNullReturn (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C)
static void evalZeroParamNonNullReturn (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C, bool IsCheckedCast=false)
static void evalZeroParamNullReturn (const CallEvent &Call, DefinedOrUnknownSVal DV, CheckerContext &C)
Function Documentation
addCastTransition()
static void addCastTransition (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C, bool IsNonNullParam, bool IsNonNullReturn, bool IsCheckedCast = false) static
Definition at line 198 of file CastValueChecker.cpp.
References alignReferenceTypes(), clang::C, clang::cast(), clang::ento::SVal::getAsRegion(), clang::ento::getDynamicCastInfo(), getNoteTag(), isInfeasibleCast(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::ento::setDynamicTypeAndCastInfo(), clang::ento::DynamicCastInfo::succeeds(), and V.
Referenced by evalNonNullParamNonNullReturn(), evalNonNullParamNullReturn(), evalZeroParamNonNullReturn(), and evalZeroParamNullReturn().
addInstanceOfTransition()
static void addInstanceOfTransition (const CallEvent & Call, DefinedOrUnknownSVal DV, ProgramStateRef State, CheckerContext & C, bool IsInstanceOf) static
Definition at line 259 of file CastValueChecker.cpp.
References alignReferenceTypes(), clang::C, clang::ento::SVal::castAs(), clang::TemplateArgumentList::get(), clang::ento::SVal::getAsRegion(), clang::TemplateArgument::getAsType(), clang::ento::getDynamicCastInfo(), clang::TemplateArgument::getKind(), getNoteTag(), clang::FunctionDecl::getTemplateSpecializationArgs(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::ento::setDynamicTypeAndCastInfo(), clang::ento::DynamicCastInfo::succeeds(), and clang::TemplateArgument::Type.
alignReferenceTypes()
static QualType alignReferenceTypes (QualType toAlign, QualType alignTowards, ASTContext & ACtx) static
Definition at line 184 of file CastValueChecker.cpp.
References clang::QualType::addConst(), clang::ASTContext::getLValueReferenceType(), clang::ASTContext::getRValueReferenceType(), clang::QualType::isConstQualified(), clang::Type::isLValueReferenceType(), and clang::Type::isRValueReferenceType().
Referenced by addCastTransition(), and addInstanceOfTransition().
evalNonNullParamNonNullReturn()
static void evalNonNullParamNonNullReturn (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C, bool IsCheckedCast = false) static
Definition at line 341 of file CastValueChecker.cpp.
References addCastTransition(), and clang::C.
evalNonNullParamNullReturn()
static void evalNonNullParamNullReturn (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C) static
Definition at line 349 of file CastValueChecker.cpp.
References addCastTransition(), and clang::C.
evalNullParamNullReturn()
static void evalNullParamNullReturn (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C) static
Definition at line 356 of file CastValueChecker.cpp.
References clang::C.
evalZeroParamNonNullReturn()
static void evalZeroParamNonNullReturn (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C, bool IsCheckedCast = false) static
Definition at line 400 of file CastValueChecker.cpp.
References addCastTransition(), and clang::C.
evalZeroParamNullReturn()
static void evalZeroParamNullReturn (const CallEvent & Call, DefinedOrUnknownSVal DV, CheckerContext & C) static
Definition at line 408 of file CastValueChecker.cpp.
References addCastTransition(), and clang::C.
getNoteTag() [1/2]
static const NoteTag * getNoteTag (CheckerContext & C, const DynamicCastInfo * CastInfo, QualType CastToTy, const Expr * Object, bool CastSucceeds, bool IsKnownCast) static
Definition at line 105 of file CastValueChecker.cpp.
References clang::C, clang::Type::getAsCXXRecordDecl(), clang::QualType::getAsString(), clang::NamedDecl::getNameAsString(), and clang::ento::DynamicCastInfo::to().
Referenced by addCastTransition(), and addInstanceOfTransition().
getNoteTag() [2/2]
static const NoteTag * getNoteTag (CheckerContext & C, SmallVector< QualType, 4 > CastToTyVec, const Expr * Object, bool IsKnownCast) static
Definition at line 139 of file CastValueChecker.cpp.
References clang::C, and clang::First.
isInfeasibleCast()
static bool isInfeasibleCast (const DynamicCastInfo * CastInfo, bool CastSucceeds) static
Definition at line 97 of file CastValueChecker.cpp.
References clang::ento::DynamicCastInfo::fails(), and clang::ento::DynamicCastInfo::succeeds().
Referenced by addCastTransition().