clang: lib/Analysis/CFG.cpp File Reference
CFG.cpp File Reference
#include "clang/Analysis/CFG.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclGroup.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtObjC.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/Type.h"
#include "clang/Analysis/ConstructionContext.h"
#include "clang/Analysis/Support/BumpVector.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/JsonSupport.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
Classes
struct llvm::DOTGraphTraits< const CFG * >
Namespaces
namespace llvm
YAML serialization mapping.
Functions
static SourceLocation GetEndLoc (Decl *D)
static bool IsIntegerLiteralConstantExpr (const Expr *E)
Returns true on constant values based around a single IntegerLiteral.
static const Expr * tryTransformToIntOrEnumConstant (const Expr *E)
Helper for tryNormalizeBinaryOperator.
static std::tuple< const Expr *, BinaryOperatorKind, const Expr * > tryNormalizeBinaryOperator (const BinaryOperator *B)
Tries to interpret a binary operator into Expr Op NumExpr form, if NumExpr is an integer literal or an enum constant.
static bool areExprTypesCompatible (const Expr *E1, const Expr *E2)
For an expression x == Foo && x == Bar, this determines whether the Foo and Bar are either of the same enumeration type, or both integer literals.
static TryResult bothKnownTrue (TryResult R1, TryResult R2)
static const VariableArrayType * FindVA (const Type *t)
static QualType getReferenceInitTemporaryType (const Expr *Init, bool *FoundMTE=nullptr)
Retrieve the type of the temporary object whose lifetime was extended by a local reference with the given initializer.
static bool isFallthroughStatement (const AttributedStmt *A)
static bool CanThrow (Expr *E, ASTContext &Ctx)
static bool shouldAddCase (bool &switchExclusivelyCovered, const Expr::EvalResult *switchCond, const CaseStmt *CS, ASTContext &Ctx)
static void print_initializer (raw_ostream &OS, StmtPrinterHelper &Helper, const CXXCtorInitializer *I)
static void print_construction_context (raw_ostream &OS, StmtPrinterHelper &Helper, const ConstructionContext *CC)
static void print_elem (raw_ostream &OS, StmtPrinterHelper &Helper, const CFGElement &E)
static void print_block (raw_ostream &OS, const CFG *cfg, const CFGBlock &B, StmtPrinterHelper &Helper, bool print_edges, bool ShowColors)
static bool isImmediateSinkBlock (const CFGBlock *Blk)
Variables
static StmtPrinterHelper * GraphHelper
Function Documentation
areExprTypesCompatible()
static bool areExprTypesCompatible (const Expr * E1, const Expr * E2) static
For an expression x == Foo && x == Bar, this determines whether the Foo and Bar are either of the same enumeration type, or both integer literals.
It's an error to pass this arguments that are not either IntegerLiterals or DeclRefExprs (that have decls of type EnumConstantDecl)
Definition at line 148 of file CFG.cpp.
References clang::cast().
bothKnownTrue()
static TryResult bothKnownTrue (TryResult R1, TryResult R2) static
Definition at line 423 of file CFG.cpp.
CanThrow()
static bool CanThrow (Expr * E, ASTContext & Ctx) static
Definition at line 2646 of file CFG.cpp.
References clang::Type::getAs(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::Type::isBlockPointerType(), clang::Type::isFunctionPointerType(), and clang::isUnresolvedExceptionSpec().
Referenced by clang::Sema::BuildCXXNoexceptExpr(), pushCaptureCleanup(), clang::ASTContext::setBlockVarCopyInit(), and clang::BlockVarCopyInit::setExprAndFlag().
FindVA()
static const VariableArrayType * FindVA (const Type * t) static
Definition at line 1383 of file CFG.cpp.
Referenced by clang::StmtIteratorBase::HandleDecl(), and clang::StmtIteratorBase::NextVA().
GetEndLoc()
static SourceLocation GetEndLoc (Decl * D) static
Definition at line 66 of file CFG.cpp.
References clang::Decl::getLocation().
getReferenceInitTemporaryType()
static QualType getReferenceInitTemporaryType (const Expr * Init, bool * FoundMTE = nullptr) static
Retrieve the type of the temporary object whose lifetime was extended by a local reference with the given initializer.
Definition at line 1739 of file CFG.cpp.
Referenced by clang::CFGImplicitDtor::getDestructorDecl(), and print_elem().
isFallthroughStatement()
static bool isFallthroughStatement (const AttributedStmt * A) static
Definition at line 2438 of file CFG.cpp.
References clang::AttributedStmt::getAttrs(), clang::AttributedStmt::getSubStmt(), and clang::hasSpecificAttr().
isImmediateSinkBlock()
static bool isImmediateSinkBlock (const CFGBlock * Blk) static
Definition at line 6137 of file CFG.cpp.
References clang::CFGElement::getAs(), and clang::CFGBlock::hasNoReturnElement().
Referenced by clang::CFGBlock::isInevitablySinking().
IsIntegerLiteralConstantExpr()
static bool IsIntegerLiteralConstantExpr (const Expr * E) static
Returns true on constant values based around a single IntegerLiteral.
Allow for use of parentheses, integer casts, and negative signs. FIXME: it would be good to unify this function with getIntegerLiteralSubexpressionValue at some point given the similarity between the functions.
Definition at line 79 of file CFG.cpp.
References clang::Expr::IgnoreParens(), and clang::isa().
Referenced by tryTransformToIntOrEnumConstant().
print_block()
static void print_block (raw_ostream & OS, const CFG * cfg, const CFGBlock & B, StmtPrinterHelper & Helper, bool print_edges, bool ShowColors) static
Definition at line 5879 of file CFG.cpp.
References clang::CFGBlock::begin(), clang::C, clang::CFGBlock::end(), clang::CFGBlock::getBlockID(), clang::CFG::getEntry(), clang::CXXCatchStmt::getExceptionDecl(), clang::CFG::getExit(), clang::SEHExceptStmt::getFilterExpr(), clang::CFG::getIndirectGotoBlock(), clang::CFGBlock::getLabel(), clang::LabelStmt::getName(), clang::CFGBlock::getTerminator(), clang::CFGBlock::hasNoReturnElement(), clang::CFGTerminator::isValid(), clang::CFGBlock::Label, clang::CFGBlock::pred_begin(), clang::CFGBlock::pred_empty(), clang::CFGBlock::pred_end(), clang::CFGBlock::pred_size(), print_elem(), clang::Stmt::printPretty(), ShowColors, clang::CFGBlock::succ_begin(), clang::CFGBlock::succ_empty(), clang::CFGBlock::succ_end(), and clang::CFGBlock::succ_size().
Referenced by llvm::DOTGraphTraits< const CFG * >::getNodeLabel(), clang::CFG::print(), and clang::CFGBlock::print().
print_construction_context()
static void print_construction_context (raw_ostream & OS, StmtPrinterHelper & Helper, const ConstructionContext * CC) static
Definition at line 5634 of file CFG.cpp.
References clang::ConstructionContext::ArgumentKind, clang::cast(), clang::ConstructionContext::CXX17ElidedCopyConstructorInitializerKind, clang::ConstructionContext::CXX17ElidedCopyReturnedValueKind, clang::ConstructionContext::CXX17ElidedCopyVariableKind, clang::ConstructionContext::ElidedTemporaryObjectKind, clang::ConstructionContext::getKind(), clang::ConstructionContext::LambdaCaptureKind, clang::ConstructionContext::NewAllocatedObjectKind, print_initializer(), clang::ConstructionContext::SimpleConstructorInitializerKind, clang::ConstructionContext::SimpleReturnedValueKind, clang::ConstructionContext::SimpleTemporaryObjectKind, and clang::ConstructionContext::SimpleVariableKind.
Referenced by print_elem().
print_elem()
static void print_elem (raw_ostream & OS, StmtPrinterHelper & Helper, const CFGElement & E) static
Definition at line 5728 of file CFG.cpp.
References clang::CFGElement::AutomaticObjectDtor, clang::CFGElement::BaseDtor, clang::CompoundStmt::body_rbegin(), clang::CFGElement::castAs(), Children, clang::CFGElement::Constructor, clang::CFGElement::CXXRecordTypedCall, clang::CFGElement::DeleteDtor, clang::CFGNewAllocator::getAllocatorExpr(), clang::CXXDeleteExpr::getArgument(), clang::CFGElement::getAs(), clang::Type::getAsCXXRecordDecl(), clang::Type::getBaseElementTypeUnsafe(), clang::CFGDeleteDtor::getCXXRecordDecl(), clang::CFGDeleteDtor::getDeleteExpr(), clang::CFGInitializer::getInitializer(), clang::CFGElement::getKind(), clang::NamedDecl::getName(), clang::BinaryOperator::getOpcode(), clang::NamedDecl::getQualifiedNameAsString(), getReferenceInitTemporaryType(), clang::BinaryOperator::getRHS(), clang::CFGStmt::getStmt(), clang::Stmt::getStmtClassName(), clang::StmtExpr::getSubStmt(), clang::CXXBaseSpecifier::getType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::CFGAutomaticObjDtor::getVarDecl(), clang::CFGLifetimeEnds::getVarDecl(), clang::CFGScopeBegin::getVarDecl(), clang::CFGScopeEnd::getVarDecl(), clang::CFGElement::Initializer, clang::CFGElement::LifetimeEnds, clang::CFGElement::LoopExit, clang::CFGElement::MemberDtor, clang::CFGElement::NewAllocator, clang::QualType::print(), print_construction_context(), print_initializer(), clang::CFGElement::ScopeBegin, clang::CFGElement::ScopeEnd, clang::CFGElement::Statement, and clang::CFGElement::TemporaryDtor.
Referenced by clang::CFGElement::dumpToStream(), and print_block().
print_initializer()
static void print_initializer (raw_ostream & OS, StmtPrinterHelper & Helper, const CXXCtorInitializer * I) static
Definition at line 5613 of file CFG.cpp.
References clang::CXXCtorInitializer::getAnyMember(), clang::Type::getAsCXXRecordDecl(), clang::CXXCtorInitializer::getBaseClass(), clang::CXXCtorInitializer::getInit(), clang::NamedDecl::getName(), clang::TypeSourceInfo::getType(), clang::CXXCtorInitializer::getTypeSourceInfo(), clang::CXXCtorInitializer::isBaseInitializer(), and clang::CXXCtorInitializer::isDelegatingInitializer().
Referenced by print_construction_context(), and print_elem().
shouldAddCase()
static bool shouldAddCase (bool & switchExclusivelyCovered, const Expr::EvalResult * switchCond, const CaseStmt * CS, ASTContext & Ctx) static
Definition at line 4405 of file CFG.cpp.
References clang::Expr::EvaluateKnownConstInt(), clang::APValue::getInt(), clang::CaseStmt::getLHS(), clang::CaseStmt::getRHS(), clang::APValue::isInt(), and clang::Expr::EvalResult::Val.
tryNormalizeBinaryOperator()
static std::tuple< const Expr *, BinaryOperatorKind, const Expr * > tryNormalizeBinaryOperator (const BinaryOperator * B) static
Tries to interpret a binary operator into Expr Op NumExpr form, if NumExpr is an integer literal or an enum constant.
If this fails, at least one of the returned DeclRefExpr or Expr will be null.
Definition at line 118 of file CFG.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), and tryTransformToIntOrEnumConstant().
tryTransformToIntOrEnumConstant()
static const Expr * tryTransformToIntOrEnumConstant (const Expr * E) static
Helper for tryNormalizeBinaryOperator.
Attempts to extract an IntegerLiteral constant expression or EnumConstantDecl from the given Expr. If it fails, returns nullptr.
Definition at line 103 of file CFG.cpp.
References clang::Expr::IgnoreParenImpCasts(), clang::Expr::IgnoreParens(), clang::isa(), and IsIntegerLiteralConstantExpr().
Referenced by tryNormalizeBinaryOperator().
Variable Documentation
GraphHelper
StmtPrinterHelper* GraphHelper static
Definition at line 6293 of file CFG.cpp.
Referenced by llvm::DOTGraphTraits< const CFG * >::getNodeLabel(), and clang::CFG::viewCFG().