clang: lib/Analysis/CFGStmtMap.cpp File Reference
CFGStmtMap.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "clang/AST/ParentMap.h"
#include "clang/Analysis/CFG.h"
#include "clang/Analysis/CFGStmtMap.h"
#include <optional>
Typedefs
typedef llvm::DenseMap< const Stmt *, CFGBlock * > SMap
Functions
static SMap * AsMap (void *m)
static void Accumulate (SMap &SM, CFGBlock *B)
Typedef Documentation
SMap
typedef llvm::DenseMap<const Stmt*, CFGBlock*> SMap
Definition at line 22 of file CFGStmtMap.cpp.
Function Documentation
Accumulate()
static void Accumulate (SMap & SM, CFGBlock * B) static
Definition at line 49 of file CFGStmtMap.cpp.
References clang::CFGBlock::begin(), clang::CFGBlock::end(), clang::CFGElement::getAs(), clang::CFGBlock::getLabel(), clang::CFGBlock::getTerminatorStmt(), Label, and SM.
Referenced by clang::CFGStmtMap::Build().
AsMap()
static SMap * AsMap (void * m) static
Definition at line 23 of file CFGStmtMap.cpp.
Referenced by clang::CFGStmtMap::getBlock(), and clang::CFGStmtMap::~CFGStmtMap().