clang: lib/CodeGen/CGBuiltin.cpp File Reference
CGBuiltin.cpp File Reference
#include "ABIInfo.h"
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGObjCRuntime.h"
#include "CGOpenCLRuntime.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "PatternInit.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/OSLog.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/FloatingPointMode.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IntrinsicsBPF.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/IR/IntrinsicsLoongArch.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/IR/IntrinsicsR600.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/IR/IntrinsicsVE.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/TargetParser/X86TargetParser.h"
#include <optional>
#include <sstream>
#include "clang/Basic/arm_sve_builtin_cg.inc"
#include "clang/Basic/BuiltinsAArch64NeonSVEBridge_cg.def"
#include "clang/Basic/arm_sme_builtin_cg.inc"
#include "clang/Basic/arm_mve_builtin_cg.inc"
#include "clang/Basic/arm_cde_builtin_cg.inc"
#include "llvm/TargetParser/X86TargetParser.def"
#include "clang/Basic/BuiltinsPPC.def"
#include "clang/Basic/BuiltinsHexagonMapCustomDep.def"
#include "clang/Basic/riscv_vector_builtin_cg.inc"
#include "clang/Basic/riscv_sifive_vector_builtin_cg.inc"
Macros
#define MUTATE_LDBL(func)
#define NEONMAP0(NameBase)
#define NEONMAP1(NameBase, LLVMIntrinsic, TypeModifier)
#define NEONMAP2(NameBase, LLVMIntrinsic, AltLLVMIntrinsic, TypeModifier)
#define SVEMAP1(NameBase, LLVMIntrinsic, TypeModifier)
#define SVEMAP2(NameBase, TypeModifier)
#define GET_SVE_LLVM_INTRINSIC_MAP
#define SMEMAP1(NameBase, LLVMIntrinsic, TypeModifier)
#define SMEMAP2(NameBase, TypeModifier)
#define GET_SME_LLVM_INTRINSIC_MAP
#define X86_VENDOR(ENUM, STRING)
#define X86_CPU_TYPE_ALIAS(ENUM, ALIAS)
#define X86_CPU_TYPE(ENUM, STR)
#define X86_CPU_SUBTYPE_ALIAS(ENUM, ALIAS)
#define X86_CPU_SUBTYPE(ENUM, STR)
#define INTRINSIC_X86_XSAVE_ID(NAME)
#define CUSTOM_BUILTIN(Name, Intr, Types, Accumulate, Feature)
#define CUSTOM_BUILTIN(Name, Intr, Types, Acc, Feature)
#define INTRINSIC_WITH_CC(NAME)
#define MMA_INTR(geom_op_type, layout)
#define MMA_LDST(n, geom_op_type)
#define MMA_VARIANTS(geom, type)
#define MMA_SATF_VARIANTS(geom, type)
#define MMA_VARIANTS_I4(geom, type)
#define MMA_VARIANTS_B1_XOR(geom, type)
#define MMA_VARIANTS_B1_AND(geom, type)
#define CUSTOM_BUILTIN_MAPPING(x, s)
Enumerations
enum class CodeGenFunction::MSVCIntrin {
_BitScanForward , _BitScanReverse , _InterlockedAnd , _InterlockedDecrement ,
_InterlockedExchange , _InterlockedExchangeAdd , _InterlockedExchangeSub , _InterlockedIncrement ,
_InterlockedOr , _InterlockedXor , _InterlockedExchangeAdd_acq , _InterlockedExchangeAdd_rel ,
_InterlockedExchangeAdd_nf , _InterlockedExchange_acq , _InterlockedExchange_rel , _InterlockedExchange_nf ,
_InterlockedCompareExchange_acq , _InterlockedCompareExchange_rel , _InterlockedCompareExchange_nf , _InterlockedCompareExchange128 ,
_InterlockedCompareExchange128_acq , _InterlockedCompareExchange128_rel , _InterlockedCompareExchange128_nf , _InterlockedOr_acq ,
_InterlockedOr_rel , _InterlockedOr_nf , _InterlockedXor_acq , _InterlockedXor_rel ,
_InterlockedXor_nf , _InterlockedAnd_acq , _InterlockedAnd_rel , _InterlockedAnd_nf ,
_InterlockedIncrement_acq , _InterlockedIncrement_rel , _InterlockedIncrement_nf , _InterlockedDecrement_acq ,
_InterlockedDecrement_rel , _InterlockedDecrement_nf , __fastfail
}
enum {
AddRetType = (1 << 0) , Add1ArgType = (1 << 1) , Add2ArgTypes = (1 << 2) , VectorizeRetType = (1 << 3) ,
VectorizeArgTypes = (1 << 4) , InventFloatType = (1 << 5) , UnsignedAlts = (1 << 6) , Use64BitVectors = (1 << 7) ,
Use128BitVectors = (1 << 8) , Vectorize1ArgType = Add1ArgType | VectorizeArgTypes , VectorRet = AddRetType | VectorizeRetType , VectorRetGetArgs01 ,
FpCmpzModifiers
}
enum SpecialRegisterAccessKind { NormalRead , VolatileRead , Write }
Functions
static void initializeAlloca (CodeGenFunction &CGF, AllocaInst *AI, Value *Size, Align AlignmentInBytes)
static Value * EmitToInt (CodeGenFunction &CGF, llvm::Value *V, QualType T, llvm::IntegerType *IntType)
Emit the conversions required to turn the given value into an integer of the given size.
static Value * EmitFromInt (CodeGenFunction &CGF, llvm::Value *V, QualType T, llvm::Type *ResultType)
static llvm::Value * CheckAtomicAlignment (CodeGenFunction &CGF, const CallExpr *E)
static Value * MakeBinaryAtomicValue (CodeGenFunction &CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr *E, AtomicOrdering Ordering=AtomicOrdering::SequentiallyConsistent)
Utility to insert an atomic instruction based on Intrinsic::ID and the expression node.
static Value * EmitNontemporalStore (CodeGenFunction &CGF, const CallExpr *E)
static Value * EmitNontemporalLoad (CodeGenFunction &CGF, const CallExpr *E)
static RValue EmitBinaryAtomic (CodeGenFunction &CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr *E)
static RValue EmitBinaryAtomicPost (CodeGenFunction &CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr *E, Instruction::BinaryOps Op, bool Invert=false)
Utility to insert an atomic instruction based Intrinsic::ID and the expression node, where the return value is the result of the operation.
static Value * MakeAtomicCmpXchgValue (CodeGenFunction &CGF, const CallExpr *E, bool ReturnBool)
Utility to insert an atomic cmpxchg instruction.
static Value * EmitAtomicCmpXchgForMSIntrin (CodeGenFunction &CGF, const CallExpr *E, AtomicOrdering SuccessOrdering=AtomicOrdering::SequentiallyConsistent)
This function should be invoked to emit atomic cmpxchg for Microsoft's _InterlockedCompareExchange* intrinsics which have the following signature: T _InterlockedCompareExchange(T volatile *Destination, T Exchange, T Comparand);.
static Value * EmitAtomicCmpXchg128ForMSIntrin (CodeGenFunction &CGF, const CallExpr *E, AtomicOrdering SuccessOrdering)
static Value * EmitAtomicIncrementValue (CodeGenFunction &CGF, const CallExpr *E, AtomicOrdering Ordering=AtomicOrdering::SequentiallyConsistent)
static Value * EmitAtomicDecrementValue (CodeGenFunction &CGF, const CallExpr *E, AtomicOrdering Ordering=AtomicOrdering::SequentiallyConsistent)
static Value * EmitISOVolatileLoad (CodeGenFunction &CGF, const CallExpr *E)
static Value * EmitISOVolatileStore (CodeGenFunction &CGF, const CallExpr *E)
static Value * emitUnaryMaybeConstrainedFPBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID)
static Value * emitBinaryMaybeConstrainedFPBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID)
static Value * emitBinaryExpMaybeConstrainedFPBuiltin (CodeGenFunction &CGF, const CallExpr *E, llvm::Intrinsic::ID IntrinsicID, llvm::Intrinsic::ID ConstrainedIntrinsicID)
static Value * emitTernaryMaybeConstrainedFPBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID)
static Value * emitCallMaybeConstrainedFPBuiltin (CodeGenFunction &CGF, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID, llvm::Type *Ty, ArrayRef< Value * > Args)
static Value * emitUnaryBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID, llvm::StringRef Name="")
static Value * emitBinaryBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID)
static Value * emitTernaryBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID)
static Value * emitFPIntBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID)
static Value * emitMaybeConstrainedFPToIntRoundBuiltin (CodeGenFunction &CGF, const CallExpr *E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID)
static Value * emitFrexpBuiltin (CodeGenFunction &CGF, const CallExpr *E, llvm::Intrinsic::ID IntrinsicID)
static Value * EmitFAbs (CodeGenFunction &CGF, Value *V)
EmitFAbs - Emit a call to @llvm.fabs().
static Value * EmitSignBit (CodeGenFunction &CGF, Value *V)
Emit the computation of the sign bit for a floating point value.
static RValue emitLibraryCall (CodeGenFunction &CGF, const FunctionDecl *FD, const CallExpr *E, llvm::Constant *calleeValue)
static llvm::Value * EmitOverflowIntrinsic (CodeGenFunction &CGF, const llvm::Intrinsic::ID IntrinsicID, llvm::Value *X, llvm::Value *Y, llvm::Value *&Carry)
Emit a call to llvm.
static Value * emitRangedBuiltin (CodeGenFunction &CGF, unsigned IntrinsicID, int low, int high)
static WidthAndSignedness getIntegerWidthAndSignedness (const clang::ASTContext &context, const clang::QualType Type)
static struct WidthAndSignedness EncompassingIntegerType (ArrayRef< struct WidthAndSignedness > Types)
static bool areBOSTypesCompatible (int From, int To)
Checks if using the result of __builtin_object_size(p, From) in place of __builtin_object_size(p, To) is correct.
static llvm::Value * getDefaultBuiltinObjectSizeResult (unsigned Type, llvm::IntegerType *ResType)
static char bitActionToX86BTCode (BitTest::ActionKind A)
static llvm::Value * EmitX86BitTestIntrinsic (CodeGenFunction &CGF, BitTest BT, const CallExpr *E, Value *BitBase, Value *BitPos)
static llvm::AtomicOrdering getBitTestAtomicOrdering (BitTest::InterlockingKind I)
static llvm::Value * EmitBitTestIntrinsic (CodeGenFunction &CGF, unsigned BuiltinID, const CallExpr *E)
Emit a _bittest* intrinsic.
static llvm::Value * emitPPCLoadReserveIntrinsic (CodeGenFunction &CGF, unsigned BuiltinID, const CallExpr *E)
static RValue EmitMSVCRTSetJmp (CodeGenFunction &CGF, MSVCSetJmpKind SJKind, const CallExpr *E)
MSVC handles setjmp a bit differently on different platforms.
static std::optional< CodeGenFunction::MSVCIntrin > translateArmToMsvcIntrin (unsigned BuiltinID)
static std::optional< CodeGenFunction::MSVCIntrin > translateAarch64ToMsvcIntrin (unsigned BuiltinID)
static std::optional< CodeGenFunction::MSVCIntrin > translateX86ToMsvcIntrin (unsigned BuiltinID)
static CanQualType getOSLogArgType (ASTContext &C, int Size)
Get the argument type for arguments to os_log_helper.
static bool isSpecialUnsignedMultiplySignedResult (unsigned BuiltinID, WidthAndSignedness Op1Info, WidthAndSignedness Op2Info, WidthAndSignedness ResultInfo)
static RValue EmitCheckedUnsignedMultiplySignedResult (CodeGenFunction &CGF, const clang::Expr *Op1, WidthAndSignedness Op1Info, const clang::Expr *Op2, WidthAndSignedness Op2Info, const clang::Expr *ResultArg, QualType ResultQTy, WidthAndSignedness ResultInfo)
static bool isSpecialMixedSignMultiply (unsigned BuiltinID, WidthAndSignedness Op1Info, WidthAndSignedness Op2Info, WidthAndSignedness ResultInfo)
Determine if a binop is a checked mixed-sign multiply we can specialize.
static RValue EmitCheckedMixedSignMultiply (CodeGenFunction &CGF, const clang::Expr *Op1, WidthAndSignedness Op1Info, const clang::Expr *Op2, WidthAndSignedness Op2Info, const clang::Expr *ResultArg, QualType ResultQTy, WidthAndSignedness ResultInfo)
Emit a checked mixed-sign multiply.
static bool TypeRequiresBuiltinLaunderImp (const ASTContext &Ctx, QualType Ty, llvm::SmallPtrSetImpl< const Decl * > &Seen)
static bool TypeRequiresBuiltinLaunder (CodeGenModule &CGM, QualType Ty)
Determine if the specified type requires laundering by checking if it is a dynamic class type or contains a subobject which is a dynamic class type.
static unsigned mutateLongDoubleBuiltin (unsigned BuiltinID)
static Value * tryUseTestFPKind (CodeGenFunction &CGF, unsigned BuiltinID, Value *V)
static Value * EmitTargetArchBuiltinExpr (CodeGenFunction *CGF, unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
static llvm::FixedVectorType * GetNeonType (CodeGenFunction *CGF, NeonTypeFlags TypeFlags, bool HasLegalHalfType=true, bool V1Ty=false, bool AllowBFloatArgsAndRet=true)
static llvm::VectorType * GetFloatNeonType (CodeGenFunction *CGF, NeonTypeFlags IntTypeFlags)
static const ARMVectorIntrinsicInfo * findARMVectorIntrinsicInMap (ArrayRef< ARMVectorIntrinsicInfo > IntrinsicMap, unsigned BuiltinID, bool &MapProvenSorted)
static Value * EmitCommonNeonSISDBuiltinExpr (CodeGenFunction &CGF, const ARMVectorIntrinsicInfo &SISDInfo, SmallVectorImpl< Value * > &Ops, const CallExpr *E)
static Value * packTBLDVectorList (CodeGenFunction &CGF, ArrayRef< Value * > Ops, Value *ExtOp, Value *IndexOp, llvm::Type *ResTy, unsigned IntID, const char *Name)
static Value * EmitSpecialRegisterBuiltin (CodeGenFunction &CGF, const CallExpr *E, llvm::Type *RegisterType, llvm::Type *ValueType, SpecialRegisterAccessKind AccessKind, StringRef SysReg="")
static bool HasExtraNeonArgument (unsigned BuiltinID)
Return true if BuiltinID is an overloaded Neon intrinsic with an extra argument that specifies the vector type.
template<typename Integer >
static Integer GetIntegerConstantValue (const Expr *E, ASTContext &Context)
static llvm::Value * SignOrZeroExtend (CGBuilderTy &Builder, llvm::Value *V, llvm::Type *T, bool Unsigned)
static llvm::Value * MVEImmediateShr (CGBuilderTy &Builder, llvm::Value *V, uint32_t Shift, bool Unsigned)
static llvm::Value * ARMMVEVectorSplat (CGBuilderTy &Builder, llvm::Value *V)
static llvm::Value * ARMMVEVectorReinterpret (CGBuilderTy &Builder, CodeGenFunction *CGF, llvm::Value *V, llvm::Type *DestType)
static llvm::Value * VectorUnzip (CGBuilderTy &Builder, llvm::Value *V, bool Odd)
static llvm::Value * VectorZip (CGBuilderTy &Builder, llvm::Value *V0, llvm::Value *V1)
template<unsigned HighBit, unsigned OtherBits>
static llvm::Value * ARMMVEConstantSplat (CGBuilderTy &Builder, llvm::Type *VT)
static llvm::Value * ARMMVEVectorElementReverse (CGBuilderTy &Builder, llvm::Value *V, unsigned ReverseWidth)
static Value * EmitAArch64TblBuiltinExpr (CodeGenFunction &CGF, unsigned BuiltinID, const CallExpr *E, SmallVectorImpl< Value * > &Ops, llvm::Triple::ArchType Arch)
static llvm::ScalableVectorType * getSVEVectorForElementType (llvm::Type *EltTy)
static void InsertExplicitZeroOperand (CGBuilderTy &Builder, llvm::Type *Ty, SmallVectorImpl< Value * > &Ops)
static void InsertExplicitUndefOperand (CGBuilderTy &Builder, llvm::Type *Ty, SmallVectorImpl< Value * > &Ops)
static Value * getMaskVecValue (CodeGenFunction &CGF, Value *Mask, unsigned NumElts)
static Value * EmitX86MaskedStore (CodeGenFunction &CGF, ArrayRef< Value * > Ops, Align Alignment)
static Value * EmitX86MaskedLoad (CodeGenFunction &CGF, ArrayRef< Value * > Ops, Align Alignment)
static Value * EmitX86ExpandLoad (CodeGenFunction &CGF, ArrayRef< Value * > Ops)
static Value * EmitX86CompressExpand (CodeGenFunction &CGF, ArrayRef< Value * > Ops, bool IsCompress)
static Value * EmitX86CompressStore (CodeGenFunction &CGF, ArrayRef< Value * > Ops)
static Value * EmitX86MaskLogic (CodeGenFunction &CGF, Instruction::BinaryOps Opc, ArrayRef< Value * > Ops, bool InvertLHS=false)
static Value * EmitX86FunnelShift (CodeGenFunction &CGF, Value *Op0, Value *Op1, Value *Amt, bool IsRight)
static Value * EmitX86vpcom (CodeGenFunction &CGF, ArrayRef< Value * > Ops, bool IsSigned)
static Value * EmitX86Select (CodeGenFunction &CGF, Value *Mask, Value *Op0, Value *Op1)
static Value * EmitX86ScalarSelect (CodeGenFunction &CGF, Value *Mask, Value *Op0, Value *Op1)
static Value * EmitX86MaskedCompareResult (CodeGenFunction &CGF, Value *Cmp, unsigned NumElts, Value *MaskIn)
static Value * EmitX86MaskedCompare (CodeGenFunction &CGF, unsigned CC, bool Signed, ArrayRef< Value * > Ops)
static Value * EmitX86ConvertToMask (CodeGenFunction &CGF, Value *In)
static Value * EmitX86ConvertIntToFp (CodeGenFunction &CGF, const CallExpr *E, ArrayRef< Value * > Ops, bool IsSigned)
static Value * EmitX86FMAExpr (CodeGenFunction &CGF, const CallExpr *E, ArrayRef< Value * > Ops, unsigned BuiltinID, bool IsAddSub)
static Value * EmitScalarFMAExpr (CodeGenFunction &CGF, const CallExpr *E, MutableArrayRef< Value * > Ops, Value *Upper, bool ZeroMask=false, unsigned PTIdx=0, bool NegAcc=false)
static Value * EmitX86Muldq (CodeGenFunction &CGF, bool IsSigned, ArrayRef< Value * > Ops)
static Value * EmitX86Ternlog (CodeGenFunction &CGF, bool ZeroMask, ArrayRef< Value * > Ops)
static Value * EmitX86SExtMask (CodeGenFunction &CGF, Value *Op, llvm::Type *DstTy)
static Value * EmitX86CvtF16ToFloatExpr (CodeGenFunction &CGF, ArrayRef< Value * > Ops, llvm::Type *DstTy)
static Value * EmitSystemZIntrinsicWithCC (CodeGenFunction &CGF, unsigned IntrinsicID, const CallExpr *E)
Handle a SystemZ function in which the final argument is a pointer to an int that receives the post-instruction CC value.
static std::pair< Intrinsic::ID, unsigned > getIntrinsicForHexagonNonClangBuiltin (unsigned BuiltinID)
Variables
static const ARMVectorIntrinsicInfo ARMSIMDIntrinsicMap []
static const ARMVectorIntrinsicInfo AArch64SIMDIntrinsicMap []
static const ARMVectorIntrinsicInfo AArch64SISDIntrinsicMap []
static const std::pair< unsigned, unsigned > NEONEquivalentIntrinsicMap []
static const ARMVectorIntrinsicInfo AArch64SVEIntrinsicMap []
static const ARMVectorIntrinsicInfo AArch64SMEIntrinsicMap []
static bool NEONSIMDIntrinsicsProvenSorted = false
static bool AArch64SIMDIntrinsicsProvenSorted = false
static bool AArch64SISDIntrinsicsProvenSorted = false
static bool AArch64SVEIntrinsicsProvenSorted = false
static bool AArch64SMEIntrinsicsProvenSorted = false
constexpr unsigned SVEBitsPerBlock = 128
Macro Definition Documentation
CUSTOM_BUILTIN [1/2]
#define CUSTOM_BUILTIN (Name, Intr, Types, Acc, Feature)
Value:
    case PPC::BI__builtin_##Name: \
      ID = Intrinsic::ppc_##Intr; \
      Accumulate = Acc; \
      break;
CUSTOM_BUILTIN [2/2]
#define CUSTOM_BUILTIN (Name, Intr, Types, Accumulate, Feature)
Value:
  case PPC::BI__builtin_##Name:
CUSTOM_BUILTIN_MAPPING
#define CUSTOM_BUILTIN_MAPPING (x, s)
Value:
  { Hexagon::BI__builtin_HEXAGON_##x, Intrinsic::hexagon_##x, s },
Referenced by getIntrinsicForHexagonNonClangBuiltin().
GET_SME_LLVM_INTRINSIC_MAP
#define GET_SME_LLVM_INTRINSIC_MAP
GET_SVE_LLVM_INTRINSIC_MAP
#define GET_SVE_LLVM_INTRINSIC_MAP
INTRINSIC_WITH_CC
#define INTRINSIC_WITH_CC (NAME)
Value:
    case SystemZ::BI__builtin_##NAME: \
      return EmitSystemZIntrinsicWithCC(*this, Intrinsic::NAME, E)
INTRINSIC_X86_XSAVE_ID
#define INTRINSIC_X86_XSAVE_ID (NAME)
Value:
    case X86::BI__builtin_ia32_##NAME: \
      ID = Intrinsic::x86_##NAME; \
      break
MMA_INTR
#define MMA_INTR (geom_op_type, layout)
Value:
  Intrinsic::nvvm_wmma_##geom_op_type##_##layout##_stride
Definition at line 18097 of file CGBuiltin.cpp.
MMA_LDST
#define MMA_LDST (n, geom_op_type)
Value:
  { n, MMA_INTR(geom_op_type, col), MMA_INTR(geom_op_type, row) }
Definition at line 18099 of file CGBuiltin.cpp.
MMA_SATF_VARIANTS
#define MMA_SATF_VARIANTS (geom, type)
Value:
      MMA_VARIANTS(geom, type),                                     \
      Intrinsic::nvvm_wmma_##geom##_mma_row_row_##type##_satfinite, \
      Intrinsic::nvvm_wmma_##geom##_mma_row_col_##type##_satfinite, \
      Intrinsic::nvvm_wmma_##geom##_mma_col_row_##type##_satfinite, \
      Intrinsic::nvvm_wmma_##geom##_mma_col_col_##type##_satfinite
MMA_VARIANTS
#define MMA_VARIANTS (geom, type)
Value:
      Intrinsic::nvvm_wmma_##geom##_mma_row_row_##type,             \
      Intrinsic::nvvm_wmma_##geom##_mma_row_col_##type,             \
      Intrinsic::nvvm_wmma_##geom##_mma_col_row_##type,             \
      Intrinsic::nvvm_wmma_##geom##_mma_col_col_##type
MMA_VARIANTS_B1_AND
#define MMA_VARIANTS_B1_AND (geom, type)
Value:
      0, \
      Intrinsic::nvvm_wmma_##geom##_mma_and_popc_row_col_##type,             \
      0, \
      0, \
      0, \
      0, \
      0, \
      0
MMA_VARIANTS_B1_XOR
#define MMA_VARIANTS_B1_XOR (geom, type)
Value:
      0, \
      Intrinsic::nvvm_wmma_##geom##_mma_xor_popc_row_col_##type,             \
      0, \
      0, \
      0, \
      0, \
      0, \
      0
MMA_VARIANTS_I4
#define MMA_VARIANTS_I4 (geom, type)
Value:
      0, \
      Intrinsic::nvvm_wmma_##geom##_mma_row_col_##type,             \
      0, \
      0, \
      0, \
      Intrinsic::nvvm_wmma_##geom##_mma_row_col_##type##_satfinite, \
      0, \
      0
MUTATE_LDBL
#define MUTATE_LDBL (func)
Value:
  case Builtin::BI__builtin_##func##l: \
    return Builtin::BI__builtin_##func##f128;
Referenced by mutateLongDoubleBuiltin().
NEONMAP0
#define NEONMAP0 (NameBase)
Value:
  { #NameBase, NEON::BI__builtin_neon_ ## NameBase, 0, 0, 0 }
Definition at line 5778 of file CGBuiltin.cpp.
NEONMAP1
#define NEONMAP1 (NameBase, LLVMIntrinsic, TypeModifier)
Value:
  { #NameBase, NEON:: BI__builtin_neon_ ## NameBase, \
      Intrinsic::LLVMIntrinsic, 0, TypeModifier }
Definition at line 5781 of file CGBuiltin.cpp.
NEONMAP2
#define NEONMAP2 (NameBase, LLVMIntrinsic, AltLLVMIntrinsic, TypeModifier)
Value:
  { #NameBase, NEON:: BI__builtin_neon_ ## NameBase, \
      Intrinsic::LLVMIntrinsic, Intrinsic::AltLLVMIntrinsic, \
      TypeModifier }
Definition at line 5785 of file CGBuiltin.cpp.
SMEMAP1
#define SMEMAP1 (NameBase, LLVMIntrinsic, TypeModifier)
Value:
  {                                                                            \
    #NameBase, SME::BI__builtin_sme_##NameBase, Intrinsic::LLVMIntrinsic, 0,   \
        TypeModifier                                                           \
  }
Definition at line 6794 of file CGBuiltin.cpp.
SMEMAP2
#define SMEMAP2 (NameBase, TypeModifier)
Value:
  { #NameBase, SME::BI__builtin_sme_##NameBase, 0, 0, TypeModifier }
Definition at line 6800 of file CGBuiltin.cpp.
SVEMAP1
#define SVEMAP1 (NameBase, LLVMIntrinsic, TypeModifier)
Value:
  {                                                                            \
    #NameBase, SVE::BI__builtin_sve_##NameBase, Intrinsic::LLVMIntrinsic, 0,   \
        TypeModifier                                                           \
  }
Definition at line 6776 of file CGBuiltin.cpp.
SVEMAP2
#define SVEMAP2 (NameBase, TypeModifier)
Value:
  { #NameBase, SVE::BI__builtin_sve_##NameBase, 0, 0, TypeModifier }
Definition at line 6782 of file CGBuiltin.cpp.
X86_CPU_SUBTYPE
#define X86_CPU_SUBTYPE (ENUM, STR)
Value:
  .Case(STR, {2u, static_cast<unsigned>(llvm::X86::ENUM)})
X86_CPU_SUBTYPE_ALIAS
#define X86_CPU_SUBTYPE_ALIAS (ENUM, ALIAS)
Value:
  .Case(ALIAS, {2u, static_cast<unsigned>(llvm::X86::ENUM)})
X86_CPU_TYPE
#define X86_CPU_TYPE (ENUM, STR)
Value:
  .Case(STR, {1u, static_cast<unsigned>(llvm::X86::ENUM)})
X86_CPU_TYPE_ALIAS
#define X86_CPU_TYPE_ALIAS (ENUM, ALIAS)
Value:
  .Case(ALIAS, {1u, static_cast<unsigned>(llvm::X86::ENUM)})
X86_VENDOR
#define X86_VENDOR (ENUM, STRING)
Value:
  .Case(STRING, {0u, static_cast<unsigned>(llvm::X86::ENUM)})
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AddRetType
Add1ArgType
Add2ArgTypes
VectorizeRetType
VectorizeArgTypes
InventFloatType
UnsignedAlts
Use64BitVectors
Use128BitVectors
Vectorize1ArgType
VectorRet
VectorRetGetArgs01
FpCmpzModifiers
Definition at line 5739 of file CGBuiltin.cpp.
MSVCIntrin
enum class CodeGenFunction::MSVCIntrin strong
Enumerator
_BitScanForward
_BitScanReverse
_InterlockedAnd
_InterlockedDecrement
_InterlockedExchange
_InterlockedExchangeAdd
_InterlockedExchangeSub
_InterlockedIncrement
_InterlockedOr
_InterlockedXor
_InterlockedExchangeAdd_acq
_InterlockedExchangeAdd_rel
_InterlockedExchangeAdd_nf
_InterlockedExchange_acq
_InterlockedExchange_rel
_InterlockedExchange_nf
_InterlockedCompareExchange_acq
_InterlockedCompareExchange_rel
_InterlockedCompareExchange_nf
_InterlockedCompareExchange128
_InterlockedCompareExchange128_acq
_InterlockedCompareExchange128_rel
_InterlockedCompareExchange128_nf
_InterlockedOr_acq
_InterlockedOr_rel
_InterlockedOr_nf
_InterlockedXor_acq
_InterlockedXor_rel
_InterlockedXor_nf
_InterlockedAnd_acq
_InterlockedAnd_rel
_InterlockedAnd_nf
_InterlockedIncrement_acq
_InterlockedIncrement_rel
_InterlockedIncrement_nf
_InterlockedDecrement_acq
_InterlockedDecrement_rel
_InterlockedDecrement_nf
__fastfail
Definition at line 1199 of file CGBuiltin.cpp.
SpecialRegisterAccessKind
enum SpecialRegisterAccessKind
Enumerator
NormalRead
VolatileRead
Write
Definition at line 7744 of file CGBuiltin.cpp.
Function Documentation
areBOSTypesCompatible()
static bool areBOSTypesCompatible (int From, int To) static
Checks if using the result of __builtin_object_size(p, From) in place of __builtin_object_size(p, To) is correct.
Definition at line 814 of file CGBuiltin.cpp.
ARMMVEConstantSplat()
template<unsigned HighBit, unsigned OtherBits> static llvm::Value * ARMMVEConstantSplat (CGBuilderTy & Builder, llvm::Type * VT) static
Definition at line 8651 of file CGBuiltin.cpp.
References ARMMVEVectorSplat(), and clang::cast().
ARMMVEVectorElementReverse()
static llvm::Value * ARMMVEVectorElementReverse (CGBuilderTy & Builder, llvm::Value * V, unsigned ReverseWidth) static
Definition at line 8663 of file CGBuiltin.cpp.
References V.
ARMMVEVectorReinterpret()
static llvm::Value * ARMMVEVectorReinterpret (CGBuilderTy & Builder, CodeGenFunction * CGF, llvm::Value * V, llvm::Type * DestType) static
Definition at line 8599 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenFunction::getTarget(), clang::TargetInfo::isBigEndian(), and V.
ARMMVEVectorSplat()
static llvm::Value * ARMMVEVectorSplat (CGBuilderTy & Builder, llvm::Value * V) static
Definition at line 8591 of file CGBuiltin.cpp.
References V.
Referenced by ARMMVEConstantSplat().
bitActionToX86BTCode()
static char bitActionToX86BTCode (BitTest::ActionKind A) static
Definition at line 957 of file CGBuiltin.cpp.
Referenced by EmitX86BitTestIntrinsic().
CheckAtomicAlignment()
static llvm::Value * CheckAtomicAlignment (CodeGenFunction & CGF, const CallExpr * E) static
Definition at line 190 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::Address::getAlignment(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getDiags(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::CharUnits::getQuantity(), clang::ASTContext::getTypeSizeInChars(), clang::DiagnosticsEngine::Report(), and clang::ASTContext::VoidPtrTy.
Referenced by EmitBinaryAtomicPost(), MakeAtomicCmpXchgValue(), and MakeBinaryAtomicValue().
EmitAArch64TblBuiltinExpr()
static Value * EmitAArch64TblBuiltinExpr (CodeGenFunction & CGF, unsigned BuiltinID, const CallExpr * E, SmallVectorImpl< Value * > & Ops, llvm::Triple::ArchType Arch) static
Definition at line 8789 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitNeonCall(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::Expr::getIntegerConstantExpr(), clang::CodeGen::CodeGenModule::getIntrinsic(), GetNeonType(), clang::CallExpr::getNumArgs(), packTBLDVectorList(), clang::Result, and s.
EmitAtomicCmpXchg128ForMSIntrin()
static Value * EmitAtomicCmpXchg128ForMSIntrin (CodeGenFunction & CGF, const CallExpr * E, AtomicOrdering SuccessOrdering) static
Definition at line 396 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateAtomicCmpXchg(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::CallExpr::getNumArgs(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::ASTContext::toCharUnitsFromBits().
EmitAtomicCmpXchgForMSIntrin()
static Value * EmitAtomicCmpXchgForMSIntrin (CodeGenFunction & CGF, const CallExpr * E, AtomicOrdering SuccessOrdering = AtomicOrdering::SequentiallyConsistent) static
This function should be invoked to emit atomic cmpxchg for Microsoft's _InterlockedCompareExchange* intrinsics which have the following signature: T _InterlockedCompareExchange(T volatile *Destination, T Exchange, T Comparand);.
Whereas the llvm 'cmpxchg' instruction has the following syntax: cmpxchg *Destination, Comparand, Exchange. So we need to swap Comparand and Exchange when invoking CreateAtomicCmpXchg. That is the reason we could not use the above utility function MakeAtomicCmpXchgValue since it expects the arguments to be already swapped.
Definition at line 358 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateAtomicCmpXchg(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isPointerType(), and clang::Result.
EmitAtomicDecrementValue()
static Value * EmitAtomicDecrementValue (CodeGenFunction & CGF, const CallExpr * E, AtomicOrdering Ordering = AtomicOrdering::SequentiallyConsistent) static
Definition at line 461 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::Expr::getType(), clang::Type::isPointerType(), and clang::Result.
EmitAtomicIncrementValue()
static Value * EmitAtomicIncrementValue (CodeGenFunction & CGF, const CallExpr * E, AtomicOrdering Ordering = AtomicOrdering::SequentiallyConsistent) static
Definition at line 448 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::Expr::getType(), clang::Type::isPointerType(), and clang::Result.
EmitBinaryAtomic()
static RValue EmitBinaryAtomic (CodeGenFunction & CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr * E) static
Definition at line 260 of file CGBuiltin.cpp.
References clang::CodeGen::RValue::get(), and MakeBinaryAtomicValue().
EmitBinaryAtomicPost()
static RValue EmitBinaryAtomicPost (CodeGenFunction & CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr * E, Instruction::BinaryOps Op, bool Invert = false) static
Utility to insert an atomic instruction based Intrinsic::ID and the expression node, where the return value is the result of the operation.
Definition at line 269 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, CheckAtomicAlignment(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), EmitFromInt(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), EmitToInt(), clang::CodeGen::RValue::get(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isPointerType(), and clang::Result.
emitBinaryBuiltin()
static Value * emitBinaryBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID) static
Definition at line 603 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
emitBinaryExpMaybeConstrainedFPBuiltin()
static Value * emitBinaryExpMaybeConstrainedFPBuiltin (CodeGenFunction & CGF, const CallExpr * E, llvm::Intrinsic::ID IntrinsicID, llvm::Intrinsic::ID ConstrainedIntrinsicID) static
Definition at line 535 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
emitBinaryMaybeConstrainedFPBuiltin()
static Value * emitBinaryMaybeConstrainedFPBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID) static
Definition at line 518 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitBitTestIntrinsic()
static llvm::Value * EmitBitTestIntrinsic (CodeGenFunction & CGF, unsigned BuiltinID, const CallExpr * E) static
Emit a _bittest* intrinsic.
These intrinsics take a pointer to an array of bits and a bit position and read and optionally modify the bit at that position. The position index can be arbitrarily large, i.e. it can be larger than 31 or 63, so we need an indexed load in the general case.
Definition at line 1019 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), EmitX86BitTestIntrinsic(), clang::CallExpr::getArg(), getBitTestAtomicOrdering(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenFunction::getTarget(), clang::TargetInfo::getTriple(), clang::Value::getType(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CharUnits::One().
emitCallMaybeConstrainedFPBuiltin()
static Value * emitCallMaybeConstrainedFPBuiltin (CodeGenFunction & CGF, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID, llvm::Type * Ty, ArrayRef< Value * > Args) static
Definition at line 574 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitCheckedMixedSignMultiply()
static RValue EmitCheckedMixedSignMultiply (CodeGenFunction & CGF, const clang::Expr * Op1, WidthAndSignedness Op1Info, const clang::Expr * Op2, WidthAndSignedness Op2Info, const clang::Expr * ResultArg, QualType ResultQTy, WidthAndSignedness ResultInfo) static
Emit a checked mixed-sign multiply.
This is a cheaper specialization of the generic checked-binop irgen.
Definition at line 2033 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateStore(), EmitOverflowIntrinsic(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitToMemory(), clang::CodeGen::RValue::get(), clang::CodeGen::Address::getElementType(), clang::Type::getPointeeType(), clang::Expr::getType(), isSpecialMixedSignMultiply(), clang::QualType::isVolatileQualified(), clang::Result, clang::Signed, and clang::Unsigned.
EmitCheckedUnsignedMultiplySignedResult()
static RValue EmitCheckedUnsignedMultiplySignedResult (CodeGenFunction & CGF, const clang::Expr * Op1, WidthAndSignedness Op1Info, const clang::Expr * Op2, WidthAndSignedness Op2Info, const clang::Expr * ResultArg, QualType ResultQTy, WidthAndSignedness ResultInfo) static
Definition at line 1987 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateStore(), EmitOverflowIntrinsic(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitToMemory(), clang::CodeGen::RValue::get(), clang::Type::getPointeeType(), clang::Expr::getType(), isSpecialUnsignedMultiplySignedResult(), clang::QualType::isVolatileQualified(), and clang::Result.
EmitCommonNeonSISDBuiltinExpr()
static Value * EmitCommonNeonSISDBuiltinExpr (CodeGenFunction & CGF, const ARMVectorIntrinsicInfo & SISDInfo, SmallVectorImpl< Value * > & Ops, const CallExpr * E) static
Definition at line 6877 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::EmitNeonCall(), clang::CallExpr::getArg(), clang::Expr::getType(), getType(), clang::CodeGen::CodeGenFunction::LookupNeonLLVMIntrinsic(), clang::Result, s, and clang::CodeGen::CodeGenTypeCache::SizeTy.
EmitFAbs()
static Value * EmitFAbs (CodeGenFunction & CGF, Value * V) static
EmitFAbs - Emit a call to @llvm.fabs().
Definition at line 675 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), and V.
emitFPIntBuiltin()
static Value * emitFPIntBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID) static
Definition at line 626 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
emitFrexpBuiltin()
static Value * emitFrexpBuiltin (CodeGenFunction & CGF, const CallExpr * E, llvm::Intrinsic::ID IntrinsicID) static
Definition at line 656 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::Type::getPointeeType(), clang::Expr::getType(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
EmitFromInt()
static Value * EmitFromInt (CodeGenFunction & CGF, llvm::Value * V, QualType T, llvm::Type * ResultType) static
Definition at line 179 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitFromMemory(), and V.
Referenced by EmitBinaryAtomicPost(), MakeAtomicCmpXchgValue(), and MakeBinaryAtomicValue().
EmitISOVolatileLoad()
static Value * EmitISOVolatileLoad (CodeGenFunction & CGF, const CallExpr * E) static
Definition at line 475 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::Type::getPointeeType(), clang::CharUnits::getQuantity(), clang::Expr::getType(), and clang::ASTContext::getTypeSizeInChars().
EmitISOVolatileStore()
static Value * EmitISOVolatileStore (CodeGenFunction & CGF, const CallExpr * E) static
Definition at line 487 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateAlignedStore(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::Type::getPointeeType(), clang::Expr::getType(), and clang::ASTContext::getTypeSizeInChars().
emitLibraryCall()
static RValue emitLibraryCall (CodeGenFunction & CGF, const FunctionDecl * FD, const CallExpr * E, llvm::Constant * calleeValue) static
Definition at line 713 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CGCallee::forDirect(), clang::CallExpr::getCallee(), and clang::Expr::getType().
emitMaybeConstrainedFPToIntRoundBuiltin()
static Value * emitMaybeConstrainedFPToIntRoundBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID) static
Definition at line 638 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::Expr::getType().
EmitMSVCRTSetJmp()
static RValue EmitMSVCRTSetJmp (CodeGenFunction & CGF, MSVCSetJmpKind SJKind, const CallExpr * E) static
MSVC handles setjmp a bit differently on different platforms.
On every architecture except 32-bit x86, the frame address is passed. On x86, extra parameters can be passed as variadic arguments, but we always pass none.
Definition at line 1157 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenTypeCache::AllocaInt8PtrTy, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitRuntimeCallOrInvoke(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::RValue::get(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::CodeGen::CodeGenFunction::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and clang::CodeGen::CodeGenTypeCache::IntTy.
EmitNontemporalLoad()
static Value * EmitNontemporalLoad (CodeGenFunction & CGF, const CallExpr * E) static
Definition at line 252 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::Expr::getExprLoc(), clang::Expr::getType(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
EmitNontemporalStore()
static Value * EmitNontemporalStore (CodeGenFunction & CGF, const CallExpr * E) static
Definition at line 237 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitToMemory(), clang::CallExpr::getArg(), clang::CodeGen::Address::getType(), clang::Expr::getType(), clang::Value::getType(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
EmitOverflowIntrinsic()
static llvm::Value * EmitOverflowIntrinsic (CodeGenFunction & CGF, const llvm::Intrinsic::ID IntrinsicID, llvm::Value * X, llvm::Value * Y, llvm::Value *& Carry) static
Emit a call to llvm.
{sadd,uadd,ssub,usub,smul,umul}.with.overflow.* depending on IntrinsicID.
CGF The current codegen function.
IntrinsicID The ID for the Intrinsic we wish to generate.
X The first argument to the llvm.*.with.overflow.*.
Y The second argument to the llvm.*.with.overflow.*.
Carry The carry returned by the llvm.*.with.overflow.*.
Returns
The result (i.e. sum/product) returned by the intrinsic.
Definition at line 728 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), and X.
Referenced by EmitCheckedMixedSignMultiply(), and EmitCheckedUnsignedMultiplySignedResult().
emitPPCLoadReserveIntrinsic()
static llvm::Value * emitPPCLoadReserveIntrinsic (CodeGenFunction & CGF, unsigned BuiltinID, const CallExpr * E) static
Definition at line 1096 of file CGBuiltin.cpp.
References clang::Asm, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::TargetInfo::getClobbers(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::CodeGen::CodeGenFunction::getTarget(), clang::CodeGen::CodeGenTypeCache::Int16Ty, clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int64Ty, and clang::CodeGen::CodeGenTypeCache::Int8Ty.
emitRangedBuiltin()
static Value * emitRangedBuiltin (CodeGenFunction & CGF, unsigned IntrinsicID, int low, int high) static
Definition at line 743 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::CodeGen::CodeGenFunction::getLLVMContext().
EmitScalarFMAExpr()
static Value * EmitScalarFMAExpr (CodeGenFunction & CGF, const CallExpr * E, MutableArrayRef< Value * > Ops, Value * Upper, bool ZeroMask = false, unsigned PTIdx = 0, bool NegAcc = false) static
Definition at line 13095 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, EmitX86ScalarSelect(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::Value::getType(), and getType().
EmitSignBit()
static Value * EmitSignBit (CodeGenFunction & CGF, Value * V) static
Emit the computation of the sign bit for a floating point value.
Returns the i1 sign bit value.
Definition at line 684 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenFunction::getTarget(), clang::TargetInfo::isBigEndian(), and V.
EmitSpecialRegisterBuiltin()
static Value * EmitSpecialRegisterBuiltin (CodeGenFunction & CGF, const CallExpr * E, llvm::Type * RegisterType, llvm::Type * ValueType, SpecialRegisterAccessKind AccessKind, StringRef SysReg = "") static
Definition at line 7753 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Expr::IgnoreParenCasts(), NormalRead, VolatileRead, and Write.
EmitSystemZIntrinsicWithCC()
static Value * EmitSystemZIntrinsicWithCC (CodeGenFunction & CGF, unsigned IntrinsicID, const CallExpr * E) static
Handle a SystemZ function in which the final argument is a pointer to an int that receives the post-instruction CC value.
At the LLVM level this is represented as a function that returns a {result, cc} pair.
Definition at line 17696 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::CallExpr::getNumArgs().
EmitTargetArchBuiltinExpr()
static Value * EmitTargetArchBuiltinExpr (CodeGenFunction * CGF, unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch) static
Definition at line 5550 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::EmitAArch64BuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitAMDGPUBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitARMBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitBPFBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitHexagonBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitLoongArchBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitNVPTXBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitPPCBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitRISCVBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitSystemZBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitWebAssemblyBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitX86BuiltinExpr().
emitTernaryBuiltin()
static Value * emitTernaryBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID) static
Definition at line 614 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
emitTernaryMaybeConstrainedFPBuiltin()
static Value * emitTernaryMaybeConstrainedFPBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID) static
Definition at line 555 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitToInt()
static Value * EmitToInt (CodeGenFunction & CGF, llvm::Value * V, QualType T, llvm::IntegerType * IntType) static
Emit the conversions required to turn the given value into an integer of the given size.
Definition at line 168 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitToMemory(), and V.
Referenced by EmitBinaryAtomicPost(), MakeAtomicCmpXchgValue(), and MakeBinaryAtomicValue().
emitUnaryBuiltin()
static Value * emitUnaryBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID, llvm::StringRef Name = "") static
Definition at line 593 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
emitUnaryMaybeConstrainedFPBuiltin()
static Value * emitUnaryMaybeConstrainedFPBuiltin (CodeGenFunction & CGF, const CallExpr * E, unsigned IntrinsicID, unsigned ConstrainedIntrinsicID) static
Definition at line 501 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CallExpr::getArg(), and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitX86BitTestIntrinsic()
static llvm::Value * EmitX86BitTestIntrinsic (CodeGenFunction & CGF, BitTest BT, const CallExpr * E, Value * BitBase, Value * BitPos) static
Definition at line 967 of file CGBuiltin.cpp.
References clang::Asm, bitActionToX86BTCode(), clang::CodeGen::CodeGenFunction::Builder, clang::CallExpr::getArg(), clang::TargetInfo::getClobbers(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::CodeGen::CodeGenFunction::getTarget(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), and clang::CodeGen::CodeGenTypeCache::Int8Ty.
Referenced by EmitBitTestIntrinsic().
EmitX86CompressExpand()
static Value * EmitX86CompressExpand (CodeGenFunction & CGF, ArrayRef< Value * > Ops, bool IsCompress) static
Definition at line 12757 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), getMaskVecValue(), and getType().
EmitX86CompressStore()
static Value * EmitX86CompressStore (CodeGenFunction & CGF, ArrayRef< Value * > Ops) static
Definition at line 12770 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), getMaskVecValue(), and getType().
EmitX86ConvertIntToFp()
static Value * EmitX86ConvertIntToFp (CodeGenFunction & CGF, const CallExpr * E, ArrayRef< Value * > Ops, bool IsSigned) static
Definition at line 12949 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, EmitX86Select(), and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitX86ConvertToMask()
static Value * EmitX86ConvertToMask (CodeGenFunction & CGF, Value * In) static
Definition at line 12944 of file CGBuiltin.cpp.
References EmitX86MaskedCompare(), and clang::Value::getType().
EmitX86CvtF16ToFloatExpr()
static Value * EmitX86CvtF16ToFloatExpr (CodeGenFunction & CGF, ArrayRef< Value * > Ops, llvm::Type * DstTy) static
Definition at line 13225 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, EmitX86Select(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenFunction::getLLVMContext(), and clang::Value::getType().
EmitX86ExpandLoad()
static Value * EmitX86ExpandLoad (CodeGenFunction & CGF, ArrayRef< Value * > Ops) static
Definition at line 12740 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), getMaskVecValue(), and getType().
EmitX86FMAExpr()
static Value * EmitX86FMAExpr (CodeGenFunction & CGF, const CallExpr * E, ArrayRef< Value * > Ops, unsigned BuiltinID, bool IsAddSub) static
Definition at line 12970 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::CGM, EmitX86Select(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::Value::getType(), and getType().
EmitX86FunnelShift()
static Value * EmitX86FunnelShift (CodeGenFunction & CGF, Value * Op0, Value * Op1, Value * Amt, bool IsRight) static
Definition at line 12800 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::Value::getType().
EmitX86MaskedCompare()
static Value * EmitX86MaskedCompare (CodeGenFunction & CGF, unsigned CC, bool Signed, ArrayRef< Value * > Ops) static
Definition at line 12909 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), EmitX86MaskedCompareResult(), getType(), and clang::Signed.
Referenced by EmitX86ConvertToMask().
EmitX86MaskedCompareResult()
static Value * EmitX86MaskedCompareResult (CodeGenFunction & CGF, Value * Cmp, unsigned NumElts, Value * MaskIn) static
Definition at line 12886 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::getLLVMContext(), and getMaskVecValue().
Referenced by EmitX86MaskedCompare().
EmitX86MaskedLoad()
static Value * EmitX86MaskedLoad (CodeGenFunction & CGF, ArrayRef< Value * > Ops, Align Alignment) static
Definition at line 12727 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and getMaskVecValue().
EmitX86MaskedStore()
static Value * EmitX86MaskedStore (CodeGenFunction & CGF, ArrayRef< Value * > Ops, Align Alignment) static
Definition at line 12714 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, getMaskVecValue(), and getType().
EmitX86MaskLogic()
static Value * EmitX86MaskLogic (CodeGenFunction & CGF, Instruction::BinaryOps Opc, ArrayRef< Value * > Ops, bool InvertLHS = false) static
Definition at line 12786 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and getMaskVecValue().
EmitX86Muldq()
static Value * EmitX86Muldq (CodeGenFunction & CGF, bool IsSigned, ArrayRef< Value * > Ops) static
Definition at line 13153 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenTypeCache::Int64Ty.
EmitX86ScalarSelect()
static Value * EmitX86ScalarSelect (CodeGenFunction & CGF, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 12872 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, and clang::Value::getType().
Referenced by EmitScalarFMAExpr().
EmitX86Select()
static Value * EmitX86Select (CodeGenFunction & CGF, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 12858 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, getMaskVecValue(), and clang::Value::getType().
Referenced by EmitX86ConvertIntToFp(), EmitX86CvtF16ToFloatExpr(), EmitX86FMAExpr(), and EmitX86Ternlog().
EmitX86SExtMask()
static Value * EmitX86SExtMask (CodeGenFunction & CGF, Value * Op, llvm::Type * DstTy) static
Definition at line 13210 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), and getMaskVecValue().
EmitX86Ternlog()
static Value * EmitX86Ternlog (CodeGenFunction & CGF, bool ZeroMask, ArrayRef< Value * > Ops) static
Definition at line 13182 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, EmitX86Select(), and clang::CodeGen::CodeGenModule::getIntrinsic().
EmitX86vpcom()
static Value * EmitX86vpcom (CodeGenFunction & CGF, ArrayRef< Value * > Ops, bool IsSigned) static
Definition at line 12818 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), and clang::Value::getType().
EncompassingIntegerType()
static struct WidthAndSignedness EncompassingIntegerType (ArrayRef< struct WidthAndSignedness > Types) static
Definition at line 778 of file CGBuiltin.cpp.
References clang::Signed.
findARMVectorIntrinsicInMap()
static const ARMVectorIntrinsicInfo * findARMVectorIntrinsicInMap (ArrayRef< ARMVectorIntrinsicInfo > IntrinsicMap, unsigned BuiltinID, bool & MapProvenSorted) static
Definition at line 6819 of file CGBuiltin.cpp.
getBitTestAtomicOrdering()
static llvm::AtomicOrdering getBitTestAtomicOrdering (BitTest::InterlockingKind I) static
Definition at line 1004 of file CGBuiltin.cpp.
Referenced by EmitBitTestIntrinsic().
getDefaultBuiltinObjectSizeResult()
static llvm::Value * getDefaultBuiltinObjectSizeResult (unsigned Type, llvm::IntegerType * ResType) static
Definition at line 822 of file CGBuiltin.cpp.
GetFloatNeonType()
static llvm::VectorType * GetFloatNeonType (CodeGenFunction * CGF, NeonTypeFlags IntTypeFlags) static
Definition at line 5654 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenTypeCache::DoubleTy, clang::CodeGen::CodeGenTypeCache::FloatTy, clang::NeonTypeFlags::getEltType(), clang::CodeGen::CodeGenTypeCache::HalfTy, clang::NeonTypeFlags::Int16, clang::NeonTypeFlags::Int32, clang::NeonTypeFlags::Int64, and clang::NeonTypeFlags::isQuad().
GetIntegerConstantValue()
template<typename Integer > static Integer GetIntegerConstantValue (const Expr * E, ASTContext & Context) static
Definition at line 8558 of file CGBuiltin.cpp.
References clang::Expr::getIntegerConstantExpr().
getIntegerWidthAndSignedness()
static WidthAndSignedness getIntegerWidthAndSignedness (const clang::ASTContext & context, const clang::QualType Type) static
Definition at line 764 of file CGBuiltin.cpp.
References clang::ASTContext::getIntWidth(), clang::ASTContext::getTypeInfo(), clang::Type::isBitIntType(), clang::Type::isBooleanType(), clang::Type::isIntegerType(), clang::Type::isSignedIntegerType(), clang::Signed, and clang::TypeInfo::Width.
getIntrinsicForHexagonNonClangBuiltin()
static std::pair< Intrinsic::ID, unsigned > getIntrinsicForHexagonNonClangBuiltin (unsigned BuiltinID) static
Definition at line 19936 of file CGBuiltin.cpp.
References CUSTOM_BUILTIN_MAPPING.
getMaskVecValue()
static Value * getMaskVecValue (CodeGenFunction & CGF, Value * Mask, unsigned NumElts) static
Definition at line 12694 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::Value::getType().
Referenced by EmitX86CompressExpand(), EmitX86CompressStore(), EmitX86ExpandLoad(), EmitX86MaskedCompareResult(), EmitX86MaskedLoad(), EmitX86MaskedStore(), EmitX86MaskLogic(), EmitX86Select(), and EmitX86SExtMask().
GetNeonType()
static llvm::FixedVectorType * GetNeonType (CodeGenFunction * CGF, NeonTypeFlags TypeFlags, bool HasLegalHalfType = true, bool V1Ty = false, bool AllowBFloatArgsAndRet = true) static
Definition at line 5613 of file CGBuiltin.cpp.
References clang::NeonTypeFlags::BFloat16, clang::CodeGen::CodeGenTypeCache::BFloatTy, clang::CodeGen::CodeGenTypeCache::DoubleTy, clang::NeonTypeFlags::Float16, clang::NeonTypeFlags::Float32, clang::NeonTypeFlags::Float64, clang::CodeGen::CodeGenTypeCache::FloatTy, clang::NeonTypeFlags::getEltType(), clang::CodeGen::CodeGenTypeCache::HalfTy, clang::NeonTypeFlags::Int16, clang::CodeGen::CodeGenTypeCache::Int16Ty, clang::NeonTypeFlags::Int32, clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::NeonTypeFlags::Int64, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::NeonTypeFlags::Int8, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::NeonTypeFlags::isQuad(), clang::NeonTypeFlags::Poly128, clang::NeonTypeFlags::Poly16, clang::NeonTypeFlags::Poly64, and clang::NeonTypeFlags::Poly8.
Referenced by EmitAArch64TblBuiltinExpr().
getOSLogArgType()
static CanQualType getOSLogArgType (ASTContext & C, int Size) static
Get the argument type for arguments to os_log_helper.
Definition at line 1786 of file CGBuiltin.cpp.
References clang::C, and clang::QualType::getCanonicalType().
getSVEVectorForElementType()
static llvm::ScalableVectorType * getSVEVectorForElementType (llvm::Type * EltTy) static
Definition at line 9075 of file CGBuiltin.cpp.
References SVEBitsPerBlock.
HasExtraNeonArgument()
static bool HasExtraNeonArgument (unsigned BuiltinID) static
Return true if BuiltinID is an overloaded Neon intrinsic with an extra argument that specifies the vector type.
Definition at line 7821 of file CGBuiltin.cpp.
initializeAlloca()
static void initializeAlloca (CodeGenFunction & CGF, AllocaInst * AI, Value * Size, Align AlignmentInBytes) static
Definition at line 68 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::initializationPatternFor(), and clang::CodeGen::CodeGenModule::stopAutoInit().
InsertExplicitUndefOperand()
static void InsertExplicitUndefOperand (CGBuilderTy & Builder, llvm::Type * Ty, SmallVectorImpl< Value * > & Ops) static
Definition at line 9554 of file CGBuiltin.cpp.
InsertExplicitZeroOperand()
static void InsertExplicitZeroOperand (CGBuilderTy & Builder, llvm::Type * Ty, SmallVectorImpl< Value * > & Ops) static
Definition at line 9548 of file CGBuiltin.cpp.
isSpecialMixedSignMultiply()
static bool isSpecialMixedSignMultiply (unsigned BuiltinID, WidthAndSignedness Op1Info, WidthAndSignedness Op2Info, WidthAndSignedness ResultInfo) static
Determine if a binop is a checked mixed-sign multiply we can specialize.
Definition at line 2021 of file CGBuiltin.cpp.
Referenced by EmitCheckedMixedSignMultiply().
isSpecialUnsignedMultiplySignedResult()
static bool isSpecialUnsignedMultiplySignedResult (unsigned BuiltinID, WidthAndSignedness Op1Info, WidthAndSignedness Op2Info, WidthAndSignedness ResultInfo) static
Definition at line 1979 of file CGBuiltin.cpp.
Referenced by EmitCheckedUnsignedMultiplySignedResult().
MakeAtomicCmpXchgValue()
static Value * MakeAtomicCmpXchgValue (CodeGenFunction & CGF, const CallExpr * E, bool ReturnBool) static
Utility to insert an atomic cmpxchg instruction.
Parameters
CGF The current codegen function.
E Builtin call expression to convert to cmpxchg. arg0 - address to operate on arg1 - value to compare with arg2 - new value
ReturnBool Specifies whether to return success flag of cmpxchg result or the old value.
Returns
result of cmpxchg, according to ReturnBool
Note: In order to lower Microsoft's _InterlockedCompareExchange* intrinsics invoke the function EmitAtomicCmpXchgForMSIntrin.
Definition at line 316 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, CheckAtomicAlignment(), clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CGBuilderTy::CreateAtomicCmpXchg(), EmitFromInt(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), EmitToInt(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::Expr::getType(), clang::Value::getType(), and clang::ASTContext::getTypeSize().
MakeBinaryAtomicValue()
static Value * MakeBinaryAtomicValue (CodeGenFunction & CGF, llvm::AtomicRMWInst::BinOp Kind, const CallExpr * E, AtomicOrdering Ordering = AtomicOrdering::SequentiallyConsistent) static
Utility to insert an atomic instruction based on Intrinsic::ID and the expression node.
Definition at line 207 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, CheckAtomicAlignment(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), EmitFromInt(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), EmitToInt(), clang::CallExpr::getArg(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isPointerType(), and clang::Result.
Referenced by EmitBinaryAtomic().
mutateLongDoubleBuiltin()
static unsigned mutateLongDoubleBuiltin (unsigned BuiltinID) static
Definition at line 2172 of file CGBuiltin.cpp.
References acos, acosh, asin, asinh, atan, atan2, atanh, cbrt, ceil, copysign, cos, cosh, erf, erfc, exp, exp2, expm1, fabs, fdim, floor, fma, fmax, fmin, fmod, frexp, hypot, ilogb, ldexp, lgamma, llrint, llround, log, log10, log1p, log2, logb, lrint, lround, modf(), MUTATE_LDBL, nan(), nearbyint, nextafter, nexttoward, pow, remainder, remquo, rint, round, scalbln, scalbn, sin, sinh, sqrt, tan, tanh, tgamma, and trunc.
MVEImmediateShr()
static llvm::Value * MVEImmediateShr (CGBuilderTy & Builder, llvm::Value * V, uint32_t Shift, bool Unsigned) static
Definition at line 8569 of file CGBuiltin.cpp.
References clang::cast(), clang::Unsigned, and V.
packTBLDVectorList()
static Value * packTBLDVectorList (CodeGenFunction & CGF, ArrayRef< Value * > Ops, Value * ExtOp, Value * IndexOp, llvm::Type * ResTy, unsigned IntID, const char * Name) static
Definition at line 7671 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitNeonCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), and getType().
Referenced by EmitAArch64TblBuiltinExpr().
SignOrZeroExtend()
static llvm::Value * SignOrZeroExtend (CGBuilderTy & Builder, llvm::Value * V, llvm::Type * T, bool Unsigned) static
Definition at line 8562 of file CGBuiltin.cpp.
References clang::Unsigned, and V.
translateAarch64ToMsvcIntrin()
static std::optional< CodeGenFunction::MSVCIntrin > translateAarch64ToMsvcIntrin (unsigned BuiltinID) static
Definition at line 1388 of file CGBuiltin.cpp.
translateArmToMsvcIntrin()
static std::optional< CodeGenFunction::MSVCIntrin > translateArmToMsvcIntrin (unsigned BuiltinID) static
Definition at line 1242 of file CGBuiltin.cpp.
translateX86ToMsvcIntrin()
static std::optional< CodeGenFunction::MSVCIntrin > translateX86ToMsvcIntrin (unsigned BuiltinID) static
Definition at line 1542 of file CGBuiltin.cpp.
tryUseTestFPKind()
static Value * tryUseTestFPKind (CodeGenFunction & CGF, unsigned BuiltinID, Value * V) static
Definition at line 2243 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::getTargetHooks(), clang::Result, clang::CodeGen::TargetCodeGenInfo::testFPKind(), and V.
TypeRequiresBuiltinLaunder()
static bool TypeRequiresBuiltinLaunder (CodeGenModule & CGM, QualType Ty) static
Determine if the specified type requires laundering by checking if it is a dynamic class type or contains a subobject which is a dynamic class type.
Definition at line 2149 of file CGBuiltin.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), and TypeRequiresBuiltinLaunderImp().
TypeRequiresBuiltinLaunderImp()
static bool TypeRequiresBuiltinLaunderImp (const ASTContext & Ctx, QualType Ty, llvm::SmallPtrSetImpl< const Decl * > & Seen) static
Definition at line 2121 of file CGBuiltin.cpp.
References clang::ASTContext::getAsArrayType(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getBaseElementType(), and TypeRequiresBuiltinLaunderImp().
Referenced by TypeRequiresBuiltinLaunder(), and TypeRequiresBuiltinLaunderImp().
VectorUnzip()
static llvm::Value * VectorUnzip (CGBuilderTy & Builder, llvm::Value * V, bool Odd) static
Definition at line 8625 of file CGBuiltin.cpp.
References clang::cast(), and V.
VectorZip()
static llvm::Value * VectorZip (CGBuilderTy & Builder, llvm::Value * V0, llvm::Value * V1) static
Definition at line 8636 of file CGBuiltin.cpp.
References clang::cast().
Variable Documentation
AArch64SIMDIntrinsicMap
const ARMVectorIntrinsicInfo AArch64SIMDIntrinsicMap[] static
Definition at line 6109 of file CGBuiltin.cpp.
AArch64SIMDIntrinsicsProvenSorted
bool AArch64SIMDIntrinsicsProvenSorted = false static
Definition at line 6813 of file CGBuiltin.cpp.
AArch64SISDIntrinsicMap
const ARMVectorIntrinsicInfo AArch64SISDIntrinsicMap[] static
Definition at line 6376 of file CGBuiltin.cpp.
AArch64SISDIntrinsicsProvenSorted
bool AArch64SISDIntrinsicsProvenSorted = false static
Definition at line 6814 of file CGBuiltin.cpp.
AArch64SMEIntrinsicMap
const ARMVectorIntrinsicInfo AArch64SMEIntrinsicMap[] static
Initial value:
= {
#define GET_SME_LLVM_INTRINSIC_MAP
}
Definition at line 6802 of file CGBuiltin.cpp.
AArch64SMEIntrinsicsProvenSorted
bool AArch64SMEIntrinsicsProvenSorted = false static
Definition at line 6816 of file CGBuiltin.cpp.
AArch64SVEIntrinsicMap
const ARMVectorIntrinsicInfo AArch64SVEIntrinsicMap[] static
Initial value:
= {
#define GET_SVE_LLVM_INTRINSIC_MAP
}
Definition at line 6784 of file CGBuiltin.cpp.
AArch64SVEIntrinsicsProvenSorted
bool AArch64SVEIntrinsicsProvenSorted = false static
Definition at line 6815 of file CGBuiltin.cpp.
ARMSIMDIntrinsicMap
const ARMVectorIntrinsicInfo ARMSIMDIntrinsicMap[] static
Definition at line 5790 of file CGBuiltin.cpp.
NEONEquivalentIntrinsicMap
const std::pair<unsigned, unsigned> NEONEquivalentIntrinsicMap[] static
Definition at line 6616 of file CGBuiltin.cpp.
NEONSIMDIntrinsicsProvenSorted
bool NEONSIMDIntrinsicsProvenSorted = false static
Definition at line 6811 of file CGBuiltin.cpp.
SVEBitsPerBlock
unsigned SVEBitsPerBlock = 128 constexpr
Definition at line 9073 of file CGBuiltin.cpp.
Referenced by getSVEVectorForElementType().