clang: lib/CodeGen/CGCall.cpp File Reference
CGCall.cpp File Reference
#include "CGCall.h"
#include "ABIInfo.h"
#include "ABIInfoImpl.h"
#include "CGBlocks.h"
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "TargetInfo.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "clang/CodeGen/SwiftCallingConv.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Assumptions.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/Transforms/Utils/Local.h"
#include <optional>
Namespaces
namespace clang
namespace clang::CodeGen
Functions
static CanQual< FunctionProtoType > GetFormalType (const CXXMethodDecl *MD)
Returns the canonical formal type of the given C++ method.
static CanQualType GetReturnType (QualType RetTy)
Returns the "extra-canonicalized" return type, which discards qualifiers on the return type.
static void addExtParameterInfosForCall (llvm::SmallVectorImpl< FunctionProtoType::ExtParameterInfo > &paramInfos, const FunctionProtoType *proto, unsigned prefixArgs, unsigned totalArgs)
static void appendParameterTypes (const CodeGenTypes &CGT, SmallVectorImpl< CanQualType > &prefix, SmallVectorImpl< FunctionProtoType::ExtParameterInfo > &paramInfos, CanQual< FunctionProtoType > FPT)
Adds the formal parameters in FPT to the given prefix.
static const CGFunctionInfo & arrangeLLVMFunctionInfo (CodeGenTypes &CGT, bool instanceMethod, SmallVectorImpl< CanQualType > &prefix, CanQual< FunctionProtoType > FTP)
Arrange the LLVM function layout for a value of the given function type, on top of any implicit parameters already stored.
static CallingConv getCallingConventionForDecl (const ObjCMethodDecl *D, bool IsWindows)
static void setCUDAKernelCallingConvention (CanQualType &FTy, CodeGenModule &CGM, const FunctionDecl *FD)
Set calling convention for CUDA/HIP kernel.
static SmallVector< CanQualType, 16 > getArgTypesForCall (ASTContext &ctx, const CallArgList &args)
static SmallVector< CanQualType, 16 > getArgTypesForDeclaration (ASTContext &ctx, const FunctionArgList &args)
static llvm::SmallVector< FunctionProtoType::ExtParameterInfo, 16 > getExtParameterInfosForCall (const FunctionProtoType *proto, unsigned prefixArgs, unsigned totalArgs)
static const CGFunctionInfo & arrangeFreeFunctionLikeCall (CodeGenTypes &CGT, CodeGenModule &CGM, const CallArgList &args, const FunctionType *fnType, unsigned numExtraRequiredArgs, bool chainCall)
Arrange a call as unto a free function, except possibly with an additional number of formal parameters considered required.
void clang::CodeGen::computeSPIRKernelABIInfo (CodeGenModule &CGM, CGFunctionInfo &FI)
static std::unique_ptr< TypeExpansion > getTypeExpansion (QualType Ty, const ASTContext &Context)
static int getExpansionSize (QualType Ty, const ASTContext &Context)
static void forConstantArrayExpansion (CodeGenFunction &CGF, ConstantArrayExpansion *CAE, Address BaseAddr, llvm::function_ref< void(Address)> Fn)
static Address CreateTempAllocaForCoercion (CodeGenFunction &CGF, llvm::Type *Ty, CharUnits MinAlign, const Twine &Name="tmp")
Create a temporary allocation for the purposes of coercion.
static Address EnterStructPointerForCoercedAccess (Address SrcPtr, llvm::StructType *SrcSTy, uint64_t DstSize, CodeGenFunction &CGF)
EnterStructPointerForCoercedAccess - Given a struct pointer that we are accessing some number of bytes out of it, try to gep into the struct to get at its inner goodness.
static llvm::Value * CoerceIntOrPtrToIntOrPtr (llvm::Value *Val, llvm::Type *Ty, CodeGenFunction &CGF)
CoerceIntOrPtrToIntOrPtr - Convert a value Val to the specific Ty where both are either integers or pointers.
static llvm::Value * CreateCoercedLoad (Address Src, llvm::Type *Ty, CodeGenFunction &CGF)
CreateCoercedLoad - Create a load from.
static void CreateCoercedStore (llvm::Value *Src, Address Dst, bool DstIsVolatile, CodeGenFunction &CGF)
CreateCoercedStore - Create a store to.
static Address emitAddressAtOffset (CodeGenFunction &CGF, Address addr, const ABIArgInfo &info)
static void AddAttributesFromFunctionProtoType (ASTContext &Ctx, llvm::AttrBuilder &FuncAttrs, const FunctionProtoType *FPT)
static void AddAttributesFromAssumes (llvm::AttrBuilder &FuncAttrs, const Decl *Callee)
static bool HasStrictReturn (const CodeGenModule &Module, QualType RetTy, const Decl *TargetDecl)
static void addDenormalModeAttrs (llvm::DenormalMode FPDenormalMode, llvm::DenormalMode FP32DenormalMode, llvm::AttrBuilder &FuncAttrs)
Add denormal-fp-math and denormal-fp-math-f32 as appropriate for the requested denormal behavior, accounting for the overriding behavior of the -f32 case.
static void addMergableDefaultFunctionAttributes (const CodeGenOptions &CodeGenOpts, llvm::AttrBuilder &FuncAttrs)
Add default attributes to a function, which have merge semantics under -mlink-builtin-bitcode and should not simply overwrite any existing attributes in the linked library.
static void getTrivialDefaultFunctionAttributes (StringRef Name, bool HasOptnone, const CodeGenOptions &CodeGenOpts, const LangOptions &LangOpts, bool AttrOnCallSite, llvm::AttrBuilder &FuncAttrs)
static void mergeDefaultFunctionDefinitionAttributes (llvm::Function &F, const CodeGenOptions CodeGenOpts, const LangOptions &LangOpts, const TargetOptions &TargetOpts, bool WillInternalize)
Adds attributes to F according to our CodeGenOpts and LangOpts, as though we had emitted it ourselves.
static void addNoBuiltinAttributes (llvm::AttrBuilder &FuncAttrs, const LangOptions &LangOpts, const NoBuiltinAttr *NBA=nullptr)
static bool DetermineNoUndef (QualType QTy, CodeGenTypes &Types, const llvm::DataLayout &DL, const ABIArgInfo &AI, bool CheckCoerce=true)
static bool IsArgumentMaybeUndef (const Decl *TargetDecl, unsigned NumRequiredArgs, unsigned ArgNo)
Check if the argument of a function has maybe_undef attribute.
static bool canApplyNoFPClass (const ABIArgInfo &AI, QualType ParamType, bool IsReturn)
Test if it's legal to apply nofpclass for the given parameter type and it's lowered IR type.
static llvm::FPClassTest getNoFPClassTestMask (const LangOptions &LangOpts)
Return the nofpclass mask that can be applied to floating-point parameters.
static llvm::Value * emitArgumentDemotion (CodeGenFunction &CGF, const VarDecl *var, llvm::Value *value)
An argument came in as a promoted argument; demote it back to its declared type.
static const NonNullAttr * getNonNullAttr (const Decl *FD, const ParmVarDecl *PVD, QualType ArgType, unsigned ArgNo)
Returns the attribute (either parameter attribute, or function attribute), which declares argument ArgNo to be non-null.
static void eraseUnusedBitCasts (llvm::Instruction *insn)
static llvm::Value * tryEmitFusedAutoreleaseOfResult (CodeGenFunction &CGF, llvm::Value *result)
Try to emit a fused autorelease of a return result.
static llvm::Value * tryRemoveRetainOfSelf (CodeGenFunction &CGF, llvm::Value *result)
If this is a +1 of the value of an immutable 'self', remove it.
static llvm::Value * emitAutoreleaseOfResult (CodeGenFunction &CGF, llvm::Value *result)
Emit an ARC autorelease of the result of a function.
static llvm::StoreInst * findDominatingStoreToReturnValue (CodeGenFunction &CGF)
Heuristically search for a dominating store to the return-value slot.
static void setBitRange (SmallVectorImpl< uint64_t > &Bits, int BitOffset, int BitWidth, int CharWidth)
static void setBitRange (SmallVectorImpl< uint64_t > &Bits, int StorageOffset, int StorageSize, int BitOffset, int BitWidth, int CharWidth, bool BigEndian)
static void setUsedBits (CodeGenModule &, QualType, int, SmallVectorImpl< uint64_t > &)
static void setUsedBits (CodeGenModule &CGM, const RecordType *RTy, int Offset, SmallVectorImpl< uint64_t > &Bits)
static void setUsedBits (CodeGenModule &CGM, const ConstantArrayType *ATy, int Offset, SmallVectorImpl< uint64_t > &Bits)
static uint64_t buildMultiCharMask (const SmallVectorImpl< uint64_t > &Bits, int Pos, int Size, int CharWidth, bool BigEndian)
static bool isInAllocaArgument (CGCXXABI &ABI, QualType type)
static AggValueSlot createPlaceholderSlot (CodeGenFunction &CGF, QualType Ty)
static bool isProvablyNull (llvm::Value *addr)
static void emitWriteback (CodeGenFunction &CGF, const CallArgList::Writeback &writeback)
Emit the actual writing-back of a writeback.
static void emitWritebacks (CodeGenFunction &CGF, const CallArgList &args)
static void deactivateArgCleanupsBeforeCall (CodeGenFunction &CGF, const CallArgList &CallArgs)
static const Expr * maybeGetUnaryAddrOfOperand (const Expr *E)
static void emitWritebackArg (CodeGenFunction &CGF, CallArgList &args, const ObjCIndirectCopyRestoreExpr *CRE)
Emit an argument that's being passed call-by-writeback.
static bool hasInAllocaArgs (CodeGenModule &CGM, CallingConv ExplicitCC, ArrayRef< QualType > ArgTypes)
static bool isObjCMethodWithTypeParams (const ObjCMethodDecl *method)
static unsigned getMaxVectorWidth (const llvm::Type *Ty)
Function Documentation
AddAttributesFromAssumes()
static void AddAttributesFromAssumes (llvm::AttrBuilder & FuncAttrs, const Decl * Callee) static
Definition at line 1767 of file CGCall.cpp.
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
AddAttributesFromFunctionProtoType()
static void AddAttributesFromFunctionProtoType (ASTContext & Ctx, llvm::AttrBuilder & FuncAttrs, const FunctionProtoType * FPT) static
Definition at line 1756 of file CGCall.cpp.
References clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionProtoType::isNothrow(), and clang::isUnresolvedExceptionSpec().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
addDenormalModeAttrs()
static void addDenormalModeAttrs (llvm::DenormalMode FPDenormalMode, llvm::DenormalMode FP32DenormalMode, llvm::AttrBuilder & FuncAttrs) static
Add denormal-fp-math and denormal-fp-math-f32 as appropriate for the requested denormal behavior, accounting for the overriding behavior of the -f32 case.
Definition at line 1829 of file CGCall.cpp.
Referenced by addMergableDefaultFunctionAttributes(), and mergeDefaultFunctionDefinitionAttributes().
addExtParameterInfosForCall()
static void addExtParameterInfosForCall (llvm::SmallVectorImpl< FunctionProtoType::ExtParameterInfo > & paramInfos, const FunctionProtoType * proto, unsigned prefixArgs, unsigned totalArgs) static
Definition at line 120 of file CGCall.cpp.
References clang::FunctionProtoType::getExtParameterInfos(), clang::FunctionProtoType::getNumParams(), and clang::FunctionProtoType::hasExtParameterInfos().
Referenced by appendParameterTypes(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), arrangeFreeFunctionLikeCall(), and getExtParameterInfosForCall().
addMergableDefaultFunctionAttributes()
static void addMergableDefaultFunctionAttributes (const CodeGenOptions & CodeGenOpts, llvm::AttrBuilder & FuncAttrs) static
Add default attributes to a function, which have merge semantics under -mlink-builtin-bitcode and should not simply overwrite any existing attributes in the linked library.
Definition at line 1843 of file CGCall.cpp.
References addDenormalModeAttrs(), clang::CodeGenOptions::FP32DenormalMode, and clang::CodeGenOptions::FPDenormalMode.
addNoBuiltinAttributes()
static void addNoBuiltinAttributes (llvm::AttrBuilder & FuncAttrs, const LangOptions & LangOpts, const NoBuiltinAttr * NBA = nullptr) static
Definition at line 2111 of file CGCall.cpp.
References clang::LangOptions::NoBuiltinFuncs.
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
appendParameterTypes()
static void appendParameterTypes (const CodeGenTypes & CGT, SmallVectorImpl< CanQualType > & prefix, SmallVectorImpl< FunctionProtoType::ExtParameterInfo > & paramInfos, CanQual< FunctionProtoType > FPT) static
Adds the formal parameters in FPT to the given prefix.
If any parameter in FPT has pass_object_size attrs, then we'll add parameters for those, too.
Definition at line 150 of file CGCall.cpp.
References addExtParameterInfosForCall(), clang::CodeGen::CodeGenTypes::getContext(), clang::ASTContext::getSizeType(), and clang::CanQual< typename >::getTypePtr().
Referenced by clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), and arrangeLLVMFunctionInfo().
arrangeFreeFunctionLikeCall()
static const CGFunctionInfo & arrangeFreeFunctionLikeCall (CodeGenTypes & CGT, CodeGenModule & CGM, const CallArgList & args, const FunctionType * fnType, unsigned numExtraRequiredArgs, bool chainCall) static
Arrange a call as unto a free function, except possibly with an additional number of formal parameters considered required.
Definition at line 577 of file CGCall.cpp.
References addExtParameterInfosForCall(), clang::CodeGen::RequiredArgs::All, clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::ASTContext::getCanonicalParamType(), clang::CodeGen::CodeGenTypes::getContext(), clang::FunctionType::getExtInfo(), GetReturnType(), clang::FunctionType::getReturnType(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::CodeGen::IsChainCall, clang::CodeGen::TargetCodeGenInfo::isNoProtoCallVariadic(), and clang::CodeGen::None.
Referenced by clang::CodeGen::CodeGenTypes::arrangeBlockFunctionCall(), and clang::CodeGen::CodeGenTypes::arrangeFreeFunctionCall().
arrangeLLVMFunctionInfo()
static const CGFunctionInfo & arrangeLLVMFunctionInfo (CodeGenTypes & CGT, bool instanceMethod, SmallVectorImpl< CanQualType > & prefix, CanQual< FunctionProtoType > FTP) static
Arrange the LLVM function layout for a value of the given function type, on top of any implicit parameters already stored.
Definition at line 183 of file CGCall.cpp.
References appendParameterTypes(), clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::CanQual< typename >::getUnqualifiedType(), clang::CodeGen::IsInstanceMethod, and clang::CodeGen::None.
buildMultiCharMask()
static uint64_t buildMultiCharMask (const SmallVectorImpl< uint64_t > & Bits, int Pos, int Size, int CharWidth, bool BigEndian) static
Definition at line 3633 of file CGCall.cpp.
References P.
canApplyNoFPClass()
static bool canApplyNoFPClass (const ABIArgInfo & AI, QualType ParamType, bool IsReturn) static
Test if it's legal to apply nofpclass for the given parameter type and it's lowered IR type.
Definition at line 2219 of file CGCall.cpp.
References clang::CodeGen::ABIArgInfo::getCanBeFlattened(), clang::CodeGen::ABIArgInfo::getCoerceToType(), and clang::Type::hasFloatingRepresentation().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
CoerceIntOrPtrToIntOrPtr()
static llvm::Value * CoerceIntOrPtrToIntOrPtr (llvm::Value * Val, llvm::Type * Ty, CodeGenFunction & CGF) static
CoerceIntOrPtrToIntOrPtr - Convert a value Val to the specific Ty where both are either integers or pointers.
This does a truncation of the value if it is too large or a zero extension if it is too small.
This behaves as if the value were coerced through memory, so on big-endian targets the high bits are preserved in a truncation, while little-endian targets preserve the low bits.
Definition at line 1200 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getDataLayout(), and clang::CodeGen::CodeGenTypeCache::IntPtrTy.
Referenced by CreateCoercedLoad(), and CreateCoercedStore().
CreateCoercedLoad()
static llvm::Value * CreateCoercedLoad (Address Src, llvm::Type * Ty, CodeGenFunction & CGF) static
CreateCoercedLoad - Create a load from.
SrcPtr interpreted as a pointer to an object of type
Ty, known to be aligned to
SrcAlign bytes.
This safely handles the case when the src type is smaller than the destination type; in this situation the values of bits which not present in the src are undefined.
Definition at line 1254 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, CoerceIntOrPtrToIntOrPtr(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), CreateTempAllocaForCoercion(), EnterStructPointerForCoercedAccess(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getName(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, and clang::CodeGen::Address::withElementType().
CreateCoercedStore()
static void CreateCoercedStore (llvm::Value * Src, Address Dst, bool DstIsVolatile, CodeGenFunction & CGF) static
CreateCoercedStore - Create a store to.
DstPtr from
Src, where the source and destination may have different types. The destination is known to be aligned to
DstAlign bytes.
This safely handles the case when the src type is larger than the destination type; the upper bits of the src will be lost.
Definition at line 1356 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, CoerceIntOrPtrToIntOrPtr(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), CreateTempAllocaForCoercion(), clang::CodeGen::CodeGenFunction::EmitAggregateStore(), EnterStructPointerForCoercedAccess(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, and clang::CodeGen::Address::withElementType().
createPlaceholderSlot()
static AggValueSlot createPlaceholderSlot (CodeGenFunction & CGF, QualType Ty) static
Definition at line 3961 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::AggValueSlot::forAddr(), clang::CharUnits::fromQuantity(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::QualType::getQualifiers(), clang::CodeGen::AggValueSlot::IsNotAliased, and clang::CodeGen::AggValueSlot::IsNotDestructed.
CreateTempAllocaForCoercion()
static Address CreateTempAllocaForCoercion (CodeGenFunction & CGF, llvm::Type * Ty, CharUnits MinAlign, const Twine & Name = "tmp") static
Create a temporary allocation for the purposes of coercion.
Definition at line 1149 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CharUnits::fromQuantity(), and clang::CodeGen::CodeGenModule::getDataLayout().
Referenced by CreateCoercedLoad(), and CreateCoercedStore().
deactivateArgCleanupsBeforeCall()
static void deactivateArgCleanupsBeforeCall (CodeGenFunction & CGF, const CallArgList & CallArgs) static
Definition at line 4108 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::DeactivateCleanupBlock(), and clang::CodeGen::CallArgList::getCleanupsToDeactivate().
DetermineNoUndef()
static bool DetermineNoUndef (QualType QTy, CodeGenTypes & Types, const llvm::DataLayout & DL, const ABIArgInfo & AI, bool CheckCoerce = true) static
Definition at line 2147 of file CGCall.cpp.
References clang::CodeGen::ABIArgInfo::canHaveCoerceToType(), Complex, DetermineNoUndef(), clang::CodeGen::ABIArgInfo::Extend, clang::CodeGen::ABIArgInfo::getCoerceToType(), clang::CodeGen::ABIArgInfo::getKind(), clang::CodeGen::ABIArgInfo::Indirect, clang::Type::isBitIntType(), clang::Type::isMemberPointerType(), clang::Type::isNullPtrType(), clang::Type::isReferenceType(), and clang::Type::isScalarType().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList(), and DetermineNoUndef().
emitAddressAtOffset()
static Address emitAddressAtOffset (CodeGenFunction & CGF, Address addr, const ABIArgInfo & info) static
Definition at line 1420 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CharUnits::fromQuantity(), clang::CodeGen::ABIArgInfo::getCoerceToType(), clang::CodeGen::ABIArgInfo::getDirectOffset(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CodeGen::Address::withElementType().
emitArgumentDemotion()
static llvm::Value * emitArgumentDemotion (CodeGenFunction & CGF, const VarDecl * var, llvm::Value * value) static
An argument came in as a promoted argument; demote it back to its declared type.
Definition at line 2810 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertType(), and clang::ValueDecl::getType().
emitAutoreleaseOfResult()
static llvm::Value * emitAutoreleaseOfResult (CodeGenFunction & CGF, llvm::Value * result) static
Emit an ARC autorelease of the result of a function.
Returns
the value to actually return from the function
Definition at line 3433 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::EmitARCAutoreleaseReturnValue(), clang::CodeGen::CodeGenFunction::shouldUseFusedARCCalls(), tryEmitFusedAutoreleaseOfResult(), and tryRemoveRetainOfSelf().
emitWriteback()
static void emitWriteback (CodeGenFunction & CGF, const CallArgList::Writeback & writeback) static
Emit the actual writing-back of a writeback.
Definition at line 4036 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::EmitARCIntrinsicUse(), clang::CodeGen::CodeGenFunction::EmitARCRelease(), clang::CodeGen::CodeGenFunction::EmitARCRetainNonBlock(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), isProvablyNull(), clang::Qualifiers::OCL_Strong, clang::CodeGen::CallArgList::Writeback::Source, clang::CodeGen::CallArgList::Writeback::Temporary, and clang::CodeGen::CallArgList::Writeback::ToUse.
Referenced by emitWritebacks().
emitWritebackArg()
static void emitWritebackArg (CodeGenFunction & CGF, CallArgList & args, const ObjCIndirectCopyRestoreExpr * CRE) static
Emit an argument that's being passed call-by-writeback.
That is, we are passing the address of an __autoreleased temporary; it might be copy-initialized with the current value of the given address, but it will definitely be copied out of after the call.
Definition at line 4130 of file CGCall.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CallArgList::addWriteback(), clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::Type::getPointeeType(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::RValue::getScalarVal(), clang::ObjCIndirectCopyRestoreExpr::getSubExpr(), clang::Expr::getType(), isProvablyNull(), clang::CodeGen::RValue::isScalar(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), maybeGetUnaryAddrOfOperand(), clang::Qualifiers::OCL_Strong, and clang::ObjCIndirectCopyRestoreExpr::shouldCopy().
emitWritebacks()
static void emitWritebacks (CodeGenFunction & CGF, const CallArgList & args) static
Definition at line 4102 of file CGCall.cpp.
References emitWriteback(), and clang::CodeGen::CallArgList::writebacks().
EnterStructPointerForCoercedAccess()
static Address EnterStructPointerForCoercedAccess (Address SrcPtr, llvm::StructType * SrcSTy, uint64_t DstSize, CodeGenFunction & CGF) static
EnterStructPointerForCoercedAccess - Given a struct pointer that we are accessing some number of bytes out of it, try to gep into the struct to get at its inner goodness.
Dive as deep as possible without entering an element with an in-memory size smaller than DstSize.
Definition at line 1164 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateStructGEP(), EnterStructPointerForCoercedAccess(), clang::CodeGen::CodeGenModule::getDataLayout(), and clang::CodeGen::Address::getElementType().
Referenced by CreateCoercedLoad(), CreateCoercedStore(), and EnterStructPointerForCoercedAccess().
eraseUnusedBitCasts()
static void eraseUnusedBitCasts (llvm::Instruction * insn) static
Definition at line 3294 of file CGCall.cpp.
References clang::cast().
Referenced by tryRemoveRetainOfSelf().
findDominatingStoreToReturnValue()
static llvm::StoreInst * findDominatingStoreToReturnValue (CodeGenFunction & CGF) static
Heuristically search for a dominating store to the return-value slot.
Definition at line 3451 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and clang::CodeGen::CodeGenFunction::ReturnValue.
forConstantArrayExpansion()
static void forConstantArrayExpansion (CodeGenFunction & CGF, ConstantArrayExpansion * CAE, Address BaseAddr, llvm::function_ref< void(Address)> Fn) static
Definition at line 1022 of file CGCall.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and clang::ASTContext::getTypeSizeInChars().
getArgTypesForCall()
static SmallVector< CanQualType, 16 > getArgTypesForCall (ASTContext & ctx, const CallArgList & args) static
Definition at line 371 of file CGCall.cpp.
References clang::ASTContext::getCanonicalParamType().
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall(), and clang::CodeGen::CodeGenTypes::arrangeUnprototypedObjCMessageSend().
getArgTypesForDeclaration()
static SmallVector< CanQualType, 16 > getArgTypesForDeclaration (ASTContext & ctx, const FunctionArgList & args) static
Definition at line 379 of file CGCall.cpp.
References clang::ASTContext::getCanonicalParamType().
Referenced by clang::CodeGen::CodeGenTypes::arrangeBlockFunctionDeclaration(), and clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration().
getCallingConventionForDecl()
static CallingConv getCallingConventionForDecl (const ObjCMethodDecl * D, bool IsWindows) static
Definition at line 207 of file CGCall.cpp.
References clang::CC_AAPCS, clang::CC_AAPCS_VFP, clang::CC_AArch64SVEPCS, clang::CC_AArch64VectorCall, clang::CC_AMDGPUKernelCall, clang::CC_C, clang::CC_IntelOclBicc, clang::CC_PreserveAll, clang::CC_PreserveMost, clang::CC_Win64, clang::CC_X86_64SysV, clang::CC_X86FastCall, clang::CC_X86Pascal, clang::CC_X86RegCall, clang::CC_X86StdCall, clang::CC_X86ThisCall, clang::CC_X86VectorCall, clang::Decl::getAttr(), and clang::Decl::hasAttr().
Referenced by clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature().
getExpansionSize()
static int getExpansionSize (QualType Ty, const ASTContext & Context) static
Definition at line 980 of file CGCall.cpp.
References getExpansionSize(), and getTypeExpansion().
Referenced by getExpansionSize().
getExtParameterInfosForCall()
static llvm::SmallVector< FunctionProtoType::ExtParameterInfo, 16 > getExtParameterInfosForCall (const FunctionProtoType * proto, unsigned prefixArgs, unsigned totalArgs) static
Definition at line 387 of file CGCall.cpp.
References addExtParameterInfosForCall(), and clang::FunctionProtoType::hasExtParameterInfos().
Referenced by clang::CodeGen::CodeGenTypes::arrangeBlockFunctionDeclaration(), and clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall().
GetFormalType()
static CanQual< FunctionProtoType > GetFormalType (const CXXMethodDecl * MD) static
Returns the canonical formal type of the given C++ method.
Definition at line 96 of file CGCall.cpp.
References clang::CanQual< typename >::getAs(), clang::Type::getCanonicalTypeUnqualified(), and clang::ValueDecl::getType().
Referenced by clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodDeclaration(), clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), clang::CodeGen::CodeGenTypes::arrangeMSCtorClosure(), and clang::CodeGen::CodeGenTypes::arrangeUnprototypedMustTailThunk().
getMaxVectorWidth()
static unsigned getMaxVectorWidth (const llvm::Type * Ty) static
Definition at line 4892 of file CGCall.cpp.
References getMaxVectorWidth().
Referenced by getMaxVectorWidth().
getNoFPClassTestMask()
static llvm::FPClassTest getNoFPClassTestMask (const LangOptions & LangOpts) static
Return the nofpclass mask that can be applied to floating-point parameters.
Definition at line 2241 of file CGCall.cpp.
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
getNonNullAttr()
static const NonNullAttr * getNonNullAttr (const Decl * FD, const ParmVarDecl * PVD, QualType ArgType, unsigned ArgNo) static
Returns the attribute (either parameter attribute, or function attribute), which declares argument ArgNo to be non-null.
Definition at line 2830 of file CGCall.cpp.
References clang::Decl::getAttr(), and clang::Decl::specific_attrs().
GetReturnType()
static CanQualType GetReturnType (QualType RetTy) static
Returns the "extra-canonicalized" return type, which discards qualifiers on the return type.
Codegen doesn't care about them, and it makes ABI code a little easier to be able to assume that all parameter and return types are top-level unqualified.
Definition at line 105 of file CGCall.cpp.
References clang::Type::getCanonicalTypeUnqualified(), and clang::CanQual< typename >::getUnqualifiedType().
Referenced by clang::CodeGen::CodeGenTypes::arrangeBlockFunctionDeclaration(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall(), arrangeFreeFunctionLikeCall(), clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), clang::CodeGen::CodeGenTypes::arrangeUnprototypedObjCMessageSend(), clang::Sema::BuildTypeTrait(), and clang::ento::retaincountchecker::RetainCountChecker::checkSummary().
getTrivialDefaultFunctionAttributes()
static void getTrivialDefaultFunctionAttributes (StringRef Name, bool HasOptnone, const CodeGenOptions & CodeGenOpts, const LangOptions & LangOpts, bool AttrOnCallSite, llvm::AttrBuilder & FuncAttrs) static
Definition at line 1849 of file CGCall.cpp.
References clang::LangOptions::assumeFunctionsAreConvergent(), clang::CodeGenOptions::DefaultFunctionAttrs, clang::LangOptions::FPE_Ignore, clang::LangOptions::getDefaultExceptionMode(), clang::CodeGenOptions::getFramePointerKindName(), clang::LangOptions::isNoBuiltinFunc(), clang::CodeGenOptions::PreferVectorWidth, clang::CodeGenOptions::Reciprocals, and clang::CodeGenOptions::TrapFuncName.
Referenced by mergeDefaultFunctionDefinitionAttributes().
getTypeExpansion()
static std::unique_ptr< TypeExpansion > getTypeExpansion (QualType Ty, const ASTContext & Context) static
Definition at line 926 of file CGCall.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getTypeSizeInChars(), clang::RecordDecl::hasFlexibleArrayMember(), clang::TagDecl::isUnion(), and clang::CharUnits::Zero().
Referenced by clang::CodeGen::CodeGenTypes::getExpandedTypes(), and getExpansionSize().
hasInAllocaArgs()
static bool hasInAllocaArgs (CodeGenModule & CGM, CallingConv ExplicitCC, ArrayRef< QualType > ArgTypes) static
Definition at line 4326 of file CGCall.cpp.
References clang::CC_Swift, clang::CC_SwiftAsync, clang::CodeGen::CodeGenModule::getCXXABI(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getTarget(), isInAllocaArgument(), and clang::TargetCXXABI::isMicrosoft().
HasStrictReturn()
static bool HasStrictReturn (const CodeGenModule & Module, QualType RetTy, const Decl * TargetDecl) static
Definition at line 1794 of file CGCall.cpp.
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList().
IsArgumentMaybeUndef()
static bool IsArgumentMaybeUndef (const Decl * TargetDecl, unsigned NumRequiredArgs, unsigned ArgNo) static
Check if the argument of a function has maybe_undef attribute.
Definition at line 2197 of file CGCall.cpp.
isInAllocaArgument()
static bool isInAllocaArgument (CGCXXABI & ABI, QualType type) static
Definition at line 3956 of file CGCall.cpp.
References clang::CodeGen::CGCXXABI::getRecordArgABI(), and clang::CodeGen::CGCXXABI::RAA_DirectInMemory.
Referenced by hasInAllocaArgs().
isObjCMethodWithTypeParams()
static bool isObjCMethodWithTypeParams (const ObjCMethodDecl * method) static
Definition at line 4344 of file CGCall.cpp.
References clang::Decl::getDeclContext().
isProvablyNull()
static bool isProvablyNull (llvm::Value * addr) static
Definition at line 4031 of file CGCall.cpp.
References clang::isa().
Referenced by emitWriteback(), and emitWritebackArg().
maybeGetUnaryAddrOfOperand()
static const Expr * maybeGetUnaryAddrOfOperand (const Expr * E) static
Definition at line 4119 of file CGCall.cpp.
References clang::Expr::IgnoreParens().
Referenced by emitWritebackArg().
mergeDefaultFunctionDefinitionAttributes()
static void mergeDefaultFunctionDefinitionAttributes (llvm::Function & F, const CodeGenOptions CodeGenOpts, const LangOptions & LangOpts, const TargetOptions & TargetOpts, bool WillInternalize) static
Adds attributes to F according to our CodeGenOpts and LangOpts, as though we had emitted it ourselves.
We remove any attributes on F that conflict with the attributes we add here.
Definition at line 1998 of file CGCall.cpp.
References addDenormalModeAttrs(), clang::TargetOptions::CPU, clang::CodeGenOptions::FP32DenormalMode, clang::CodeGenOptions::FPDenormalMode, getTrivialDefaultFunctionAttributes(), and clang::TargetOptions::TuneCPU.
Referenced by clang::CodeGen::CodeGenModule::mergeDefaultFunctionDefinitionAttributes(), and clang::CodeGen::mergeDefaultFunctionDefinitionAttributes().
setBitRange() [1/2]
static void setBitRange (SmallVectorImpl< uint64_t > & Bits, int BitOffset, int BitWidth, int CharWidth) static
Definition at line 3512 of file CGCall.cpp.
References Used.
Referenced by setBitRange(), and setUsedBits().
setBitRange() [2/2]
static void setBitRange (SmallVectorImpl< uint64_t > & Bits, int StorageOffset, int StorageSize, int BitOffset, int BitWidth, int CharWidth, bool BigEndian) static
Definition at line 3543 of file CGCall.cpp.
References setBitRange(), and V.
setCUDAKernelCallingConvention()
static void setCUDAKernelCallingConvention (CanQualType & FTy, CodeGenModule & CGM, const FunctionDecl * FD) static
Set calling convention for CUDA/HIP kernel.
Definition at line 279 of file CGCall.cpp.
References clang::CanQual< typename >::getAs(), clang::Type::getCanonicalTypeUnqualified(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::Decl::hasAttr(), and clang::CodeGen::TargetCodeGenInfo::setCUDAKernelCallingConvention().
Referenced by clang::CodeGen::CodeGenTypes::arrangeCXXMethodDeclaration(), and clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration().
setUsedBits() [1/3]
static void setUsedBits (CodeGenModule & CGM, QualType QTy, int Offset, SmallVectorImpl< uint64_t > & Bits) static
Definition at line 3616 of file CGCall.cpp.
References clang::Type::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getCharWidth(), clang::CodeGen::CodeGenModule::getContext(), clang::CharUnits::getQuantity(), clang::ASTContext::getTypeSizeInChars(), Offset, and setUsedBits().
Referenced by setUsedBits(), setUsedBits(), and setUsedBits().
setUsedBits() [2/3]
static void setUsedBits (CodeGenModule & CGM, const ConstantArrayType * ATy, int Offset, SmallVectorImpl< uint64_t > & Bits) static
Definition at line 3597 of file CGCall.cpp.
References clang::ASTContext::getBaseElementType(), clang::ASTContext::getConstantArrayElementCount(), clang::CodeGen::CodeGenModule::getContext(), clang::CharUnits::getQuantity(), clang::ASTContext::getTypeSizeInChars(), N, Offset, and setUsedBits().
setUsedBits() [3/3]
static void setUsedBits (CodeGenModule & CGM, const RecordType * RTy, int Offset, SmallVectorImpl< uint64_t > & Bits) static
Definition at line 3565 of file CGCall.cpp.
References clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CGRecordLayout::getBitFieldInfo(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::ASTContext::getCharWidth(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::RecordDecl::getDefinition(), clang::ASTRecordLayout::getFieldOffset(), clang::CharUnits::getQuantity(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::FieldDecl::isBitField(), clang::Type::isIncompleteArrayType(), clang::FieldDecl::isUnnamedBitfield(), clang::FieldDecl::isZeroLengthBitField(), clang::CodeGen::CGBitFieldInfo::Offset, Offset, setBitRange(), setUsedBits(), clang::CodeGen::CGBitFieldInfo::Size, clang::CodeGen::CGBitFieldInfo::StorageOffset, and clang::CodeGen::CGBitFieldInfo::StorageSize.
tryEmitFusedAutoreleaseOfResult()
static llvm::Value * tryEmitFusedAutoreleaseOfResult (CodeGenFunction & CGF, llvm::Value * result) static
Try to emit a fused autorelease of a return result.
Definition at line 3306 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleaseReturnValue(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::ObjCEntrypoints::objc_retain, clang::CodeGen::ObjCEntrypoints::objc_retainAutoreleasedReturnValue, and clang::CodeGen::ObjCEntrypoints::retainAutoreleasedReturnValueMarker.
Referenced by emitAutoreleaseOfResult().
tryRemoveRetainOfSelf()
static llvm::Value * tryRemoveRetainOfSelf (CodeGenFunction & CGF, llvm::Value * result) static
If this is a +1 of the value of an immutable 'self', remove it.
Definition at line 3394 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCodeDecl, eraseUnusedBitCasts(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::Address::getPointer(), clang::ObjCMethodDecl::getSelfDecl(), clang::ValueDecl::getType(), clang::QualType::isConstQualified(), and clang::CodeGen::ObjCEntrypoints::objc_retain.
Referenced by emitAutoreleaseOfResult().