clang: lib/CodeGen/CGCoroutine.cpp File Reference
CGCoroutine.cpp File Reference
#include "CGCleanup.h"
#include "CodeGenFunction.h"
#include "llvm/ADT/ScopeExit.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtVisitor.h"
Classes
struct clang::CodeGen::CGCoroData
Functions
static void createCoroData (CodeGenFunction &CGF, CodeGenFunction::CGCoroInfo &CurCoro, llvm::CallInst *CoroId, CallExpr const *CoroIdExpr=nullptr)
static SmallString< 32 > buildSuspendPrefixStr (CGCoroData &Coro, AwaitKind Kind)
static bool memberCallExpressionCanThrow (const Expr *E)
static LValueOrRValue emitSuspendExpression (CodeGenFunction &CGF, CGCoroData &Coro, CoroutineSuspendExpr const &S, AwaitKind Kind, AggValueSlot aggSlot, bool ignoreResult, bool forLValue)
static QualType getCoroutineSuspendExprReturnType (const ASTContext &Ctx, const CoroutineSuspendExpr *E)
static SmallVector< llvm::OperandBundleDef, 1 > getBundlesForCoroEnd (CodeGenFunction &CGF)
static void emitBodyAndFallthrough (CodeGenFunction &CGF, const CoroutineBodyStmt &S, Stmt *Body)
Function Documentation
buildSuspendPrefixStr()
static SmallString< 32 > buildSuspendPrefixStr (CGCoroData & Coro, AwaitKind Kind) static
Definition at line 112 of file CGCoroutine.cpp.
References clang::CodeGen::CGCoroData::AwaitNum, clang::No, and clang::CodeGen::CGCoroData::YieldNum.
Referenced by emitSuspendExpression().
createCoroData()
static void createCoroData (CodeGenFunction & CGF, CodeGenFunction::CGCoroInfo & CurCoro, llvm::CallInst * CoroId, CallExpr const * CoroIdExpr = nullptr) static
Definition at line 89 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, and clang::CodeGen::CodeGenModule::Error().
emitBodyAndFallthrough()
static void emitBodyAndFallthrough (CodeGenFunction & CGF, const CoroutineBodyStmt & S, Stmt * Body) static
Definition at line 587 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenFunction::EmitStmt().
emitSuspendExpression()
static LValueOrRValue emitSuspendExpression (CodeGenFunction & CGF, CGCoroData & Coro, CoroutineSuspendExpr const & S, AwaitKind Kind, AggValueSlot aggSlot, bool ignoreResult, bool forLValue) static
Definition at line 175 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind(), clang::CodeGen::CodeGenFunction::Builder, buildSuspendPrefixStr(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGCoroData::CleanupJD, clang::CompoundStmt::Create(), clang::CXXTryStmt::Create(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CodeGen::CodeGenFunction::CurCoro, clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), clang::CodeGen::CodeGenFunction::EmitBranchThroughCleanup(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EnterCXXTryStmt(), clang::CodeGen::CGCoroData::ExceptionHandler, clang::CodeGen::CodeGenFunction::ExitCXXTryStmt(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenFunction::CGCoroInfo::InSuspendBlock, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, memberCallExpressionCanThrow(), clang::CodeGen::CGCoroData::ResumeEHVar, clang::CodeGen::CGCoroData::SuspendBB, and clang::Switch.
getBundlesForCoroEnd()
static SmallVector< llvm::OperandBundleDef, 1 > getBundlesForCoroEnd (CodeGenFunction & CGF) static
Definition at line 385 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::CurrentFuncletPad.
getCoroutineSuspendExprReturnType()
static QualType getCoroutineSuspendExprReturnType (const ASTContext & Ctx, const CoroutineSuspendExpr * E) static
Definition at line 292 of file CGCoroutine.cpp.
References clang::cast(), and clang::CoroutineSuspendExpr::getResumeExpr().
memberCallExpressionCanThrow()
static bool memberCallExpressionCanThrow (const Expr * E) static
Definition at line 132 of file CGCoroutine.cpp.
References clang::CT_Cannot, and clang::isNoexceptExceptionSpec().
Referenced by emitSuspendExpression().