clang: lib/CodeGen/CGExpr.cpp File Reference
CGExpr.cpp File Reference
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGCall.h"
#include "CGCleanup.h"
#include "CGDebugInfo.h"
#include "CGObjCRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/NSAPI.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/Passes/OptimizationLevel.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/xxhash.h"
#include "llvm/Transforms/Utils/SanitizerStats.h"
#include <optional>
#include <string>
Macros
#define SANITIZER_CHECK(Enum, Name, Version)
Enumerations
enum ConstantEmissionKind { CEK_None , CEK_AsReferenceOnly , CEK_AsValueOrReference , CEK_AsValueOnly }
Can we constant-emit a load of a reference to a variable of the given type? This is different from predicates like Decl::mightBeUsableInConstantExpressions because we do want it to apply in situations that don't necessarily satisfy the language's rules for this (e.g.
Functions
static void pushTemporaryCleanup (CodeGenFunction &CGF, const MaterializeTemporaryExpr *M, const Expr *E, Address ReferenceTemporary)
static Address createReferenceTemporary (CodeGenFunction &CGF, const MaterializeTemporaryExpr *M, const Expr *Inner, Address *Alloca=nullptr)
static bool isAAPCS (const TargetInfo &TargetInfo)
Helper method to check if the underlying ABI is AAPCS.
static llvm::Value * emitHash16Bytes (CGBuilderTy &Builder, llvm::Value *Low, llvm::Value *High)
Emit the hash_16_bytes function from include/llvm/ADT/Hashing.h.
static llvm::Value * getArrayIndexingBound (CodeGenFunction &CGF, const Expr *Base, QualType &IndexedType, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel)
If Base is known to point to the start of an array, return the length of that array.
static Address EmitPointerWithAlignment (const Expr *E, LValueBaseInfo *BaseInfo, TBAAAccessInfo *TBAAInfo, KnownNonNull_t IsKnownNonNull, CodeGenFunction &CGF)
static bool isConstantEmittableObjectType (QualType type)
Given an object of the given canonical type, can we safely copy a value out of it based on its initializer?
static ConstantEmissionKind checkVarTypeForConstantEmission (QualType type)
static DeclRefExpr * tryToConvertMemberExprToDeclRefExpr (CodeGenFunction &CGF, const MemberExpr *ME)
static bool hasBooleanRepresentation (QualType Ty)
static bool getRangeForType (CodeGenFunction &CGF, QualType Ty, llvm::APInt &Min, llvm::APInt &End, bool StrictEnums, bool IsBool)
static Address MaybeConvertMatrixAddress (Address Addr, CodeGenFunction &CGF, bool IsVector=true)
static void EmitStoreOfMatrixScalar (llvm::Value *value, LValue lvalue, bool isInit, CodeGenFunction &CGF)
static RValue EmitLoadOfMatrixLValue (LValue LV, SourceLocation Loc, CodeGenFunction &CGF)
static void setObjCGCLValueClass (const ASTContext &Ctx, const Expr *E, LValue &LV, bool IsMemberAccess=false)
static llvm::Value * EmitBitCastOfLValueToProperType (CodeGenFunction &CGF, llvm::Value *V, llvm::Type *IRType, StringRef Name=StringRef())
static LValue EmitThreadPrivateVarDeclLValue (CodeGenFunction &CGF, const VarDecl *VD, QualType T, Address Addr, llvm::Type *RealVarTy, SourceLocation Loc)
static Address emitDeclTargetVarDeclLValue (CodeGenFunction &CGF, const VarDecl *VD, QualType T)
static LValue EmitGlobalVarDeclLValue (CodeGenFunction &CGF, const Expr *E, const VarDecl *VD)
static llvm::Constant * EmitFunctionDeclPointer (CodeGenModule &CGM, GlobalDecl GD)
static LValue EmitFunctionDeclLValue (CodeGenFunction &CGF, const Expr *E, GlobalDecl GD)
static LValue EmitCapturedFieldLValue (CodeGenFunction &CGF, const FieldDecl *FD, llvm::Value *ThisValue)
static LValue EmitGlobalNamedRegister (const VarDecl *VD, CodeGenModule &CGM)
Named Registers are named metadata pointing to the register name which will be read from/written to as an argument to the intrinsic @llvm.read/write_register.
static bool canEmitSpuriousReferenceToVariable (CodeGenFunction &CGF, const DeclRefExpr *E, const VarDecl *VD)
Determine whether we can emit a reference to VD from the current context, despite not necessarily having seen an odr-use of the variable in this context.
static CheckRecoverableKind getRecoverableKind (SanitizerMask Kind)
static void emitCheckHandlerCall (CodeGenFunction &CGF, llvm::FunctionType *FnType, ArrayRef< llvm::Value * > FnArgs, SanitizerHandler CheckHandler, CheckRecoverableKind RecoverKind, bool IsFatal, llvm::BasicBlock *ContBB)
static const Expr * isSimpleArrayDecayOperand (const Expr *E)
isSimpleArrayDecayOperand - If the specified expr is a simple decay from an array to pointer, return the array subexpression.
static llvm::Value * emitArraySubscriptGEP (CodeGenFunction &CGF, llvm::Type *elemType, llvm::Value *ptr, ArrayRef< llvm::Value * > indices, bool inbounds, bool signedIndices, SourceLocation loc, const llvm::Twine &name="arrayidx")
static CharUnits getArrayElementAlign (CharUnits arrayAlign, llvm::Value *idx, CharUnits eltSize)
static QualType getFixedSizeElementType (const ASTContext &ctx, const VariableArrayType *vla)
static bool IsPreserveAIArrayBase (CodeGenFunction &CGF, const Expr *ArrayBase)
Given an array base, check whether its member access belongs to a record with preserve_access_index attribute or not.
static Address emitArraySubscriptGEP (CodeGenFunction &CGF, Address addr, ArrayRef< llvm::Value * > indices, QualType eltType, bool inbounds, bool signedIndices, SourceLocation loc, QualType *arrayType=nullptr, const Expr *Base=nullptr, const llvm::Twine &name="arrayidx")
static Address emitOMPArraySectionBase (CodeGenFunction &CGF, const Expr *Base, LValueBaseInfo &BaseInfo, TBAAAccessInfo &TBAAInfo, QualType BaseTy, QualType ElTy, bool IsLowerBound)
static Address emitAddrOfZeroSizeField (CodeGenFunction &CGF, Address Base, const FieldDecl *Field)
Get the address of a zero-sized field within a record.
static Address emitAddrOfFieldStorage (CodeGenFunction &CGF, Address base, const FieldDecl *field)
Drill down to the storage of a field without walking into reference types.
static Address emitPreserveStructAccess (CodeGenFunction &CGF, LValue base, Address addr, const FieldDecl *field)
static bool hasAnyVptr (const QualType Type, const ASTContext &Context)
static std::optional< LValue > EmitLValueOrThrowExpression (CodeGenFunction &CGF, const Expr *Operand)
Emit the operand of a glvalue conditional operator.
static bool OnlyHasInlineBuiltinDeclaration (const FunctionDecl *FD)
static CGCallee EmitDirectCallee (CodeGenFunction &CGF, GlobalDecl GD)
static LValueOrRValue emitPseudoObjectExpr (CodeGenFunction &CGF, const PseudoObjectExpr *E, bool forLValue, AggValueSlot slot)
Variables
const SanitizerHandlerInfo SanitizerHandlers []
Macro Definition Documentation
SANITIZER_CHECK
#define SANITIZER_CHECK (Enum, Name, Version)
Value:
{#Name, Version},
Enumeration Type Documentation
ConstantEmissionKind
enum ConstantEmissionKind
Can we constant-emit a load of a reference to a variable of the given type? This is different from predicates like Decl::mightBeUsableInConstantExpressions because we do want it to apply in situations that don't necessarily satisfy the language's rules for this (e.g.
C++'s ODR-use rules). For example, we want to able to do this with const float variables even if those variables aren't marked 'constexpr'.
Enumerator
CEK_None
CEK_AsReferenceOnly
CEK_AsValueOrReference
CEK_AsValueOnly
Definition at line 1474 of file CGExpr.cpp.
Function Documentation
canEmitSpuriousReferenceToVariable()
static bool canEmitSpuriousReferenceToVariable (CodeGenFunction & CGF, const DeclRefExpr * E, const VarDecl * VD) static
Determine whether we can emit a reference to VD from the current context, despite not necessarily having seen an odr-use of the variable in this context.
Definition at line 2693 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCodeDecl, clang::CodeGen::CodeGenFunction::getContext(), clang::Decl::getDeclContext(), clang::VarDecl::getDefinition(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMLinkageVarDefinition(), clang::VarDecl::hasLocalStorage(), and clang::DeclRefExpr::refersToEnclosingVariableOrCapture().
checkVarTypeForConstantEmission()
static ConstantEmissionKind checkVarTypeForConstantEmission (QualType type) static
Definition at line 1480 of file CGExpr.cpp.
References CEK_AsReferenceOnly, CEK_AsValueOnly, CEK_AsValueOrReference, CEK_None, and isConstantEmittableObjectType().
createReferenceTemporary()
static Address createReferenceTemporary (CodeGenFunction & CGF, const MaterializeTemporaryExpr * M, const Expr * Inner, Address * Alloca = nullptr) static
Definition at line 380 of file CGExpr.cpp.
References clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::Default, clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::GetGlobalConstantAddressSpace(), clang::CodeGen::CodeGenModule::getModule(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::ASTContext::getTargetAddressSpace(), clang::CodeGen::CodeGenFunction::getTargetHooks(), clang::ASTContext::getTypeAlignInChars(), clang::Type::isArrayType(), clang::Type::isRecordType(), clang::CodeGen::CodeGenModule::isTypeConstant(), clang::SD_Automatic, clang::SD_Dynamic, clang::SD_FullExpression, clang::SD_Static, and clang::SD_Thread.
emitAddrOfFieldStorage()
static Address emitAddrOfFieldStorage (CodeGenFunction & CGF, Address base, const FieldDecl * field) static
Drill down to the storage of a field without walking into reference types.
The resulting address doesn't necessarily have the right type.
Definition at line 4315 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateStructGEP(), emitAddrOfZeroSizeField(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::NamedDecl::getName(), clang::FieldDecl::getParent(), clang::CodeGen::CodeGenModule::getTypes(), and clang::FieldDecl::isZeroSize().
emitAddrOfZeroSizeField()
static Address emitAddrOfZeroSizeField (CodeGenFunction & CGF, Address Base, const FieldDecl * Field) static
Get the address of a zero-sized field within a record.
The resulting address doesn't necessarily have the right type.
Definition at line 4301 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getFieldOffset(), clang::CodeGen::CodeGenTypeCache::Int8Ty, Offset, and clang::ASTContext::toCharUnitsFromBits().
Referenced by emitAddrOfFieldStorage().
emitArraySubscriptGEP() [1/2]
static Address emitArraySubscriptGEP (CodeGenFunction & CGF, Address addr, ArrayRef< llvm::Value * > indices, QualType eltType, bool inbounds, bool signedIndices, SourceLocation loc, QualType * arrayType = nullptr, const Expr * Base = nullptr, const llvm::Twine & name = "arrayidx") static
Definition at line 3745 of file CGExpr.cpp.
References clang::ast_matchers::arrayType, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), emitArraySubscriptGEP(), clang::CodeGen::Address::getAlignment(), getArrayElementAlign(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::CodeGen::Address::getElementType(), getFixedSizeElementType(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::CodeGen::Address::getPointer(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenFunction::IsInPreservedAIRegion, and IsPreserveAIArrayBase().
emitArraySubscriptGEP() [2/2]
static llvm::Value * emitArraySubscriptGEP (CodeGenFunction & CGF, llvm::Type * elemType, llvm::Value * ptr, ArrayRef< llvm::Value * > indices, bool inbounds, bool signedIndices, SourceLocation loc, const llvm::Twine & name = "arrayidx") static
Definition at line 3668 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateGEP(), clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP(), and clang::CodeGen::CodeGenFunction::NotSubtraction.
Referenced by emitArraySubscriptGEP().
EmitBitCastOfLValueToProperType()
static llvm::Value * EmitBitCastOfLValueToProperType (CodeGenFunction & CGF, llvm::Value * V, llvm::Type * IRType, StringRef Name = StringRef()) static
Definition at line 2496 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), and V.
Referenced by EmitGlobalVarDeclLValue().
EmitCapturedFieldLValue()
static LValue EmitCapturedFieldLValue (CodeGenFunction & CGF, const FieldDecl * FD, llvm::Value * ThisValue) static
Definition at line 2655 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::getContext(), clang::FieldDecl::getParent(), clang::ASTContext::getTagDeclType(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
emitCheckHandlerCall()
static void emitCheckHandlerCall (CodeGenFunction & CGF, llvm::FunctionType * FnType, ArrayRef< llvm::Value * > FnArgs, SanitizerHandler CheckHandler, CheckRecoverableKind RecoverKind, bool IsFatal, llvm::BasicBlock * ContBB) static
Definition at line 3233 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenFunction::getLLVMContext(), and SanitizerHandlers.
emitDeclTargetVarDeclLValue()
static Address emitDeclTargetVarDeclLValue (CodeGenFunction & CGF, const VarDecl * VD, QualType T) static
Definition at line 2517 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), clang::CodeGen::CGOpenMPRuntime::hasRequiresUnifiedSharedMemory(), and clang::CodeGen::Address::invalid().
Referenced by EmitGlobalVarDeclLValue().
EmitDirectCallee()
static CGCallee EmitDirectCallee (CodeGenFunction & CGF, GlobalDecl GD) static
Definition at line 5029 of file CGExpr.cpp.
References clang::ASTContext::BuiltinInfo, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurFn, EmitFunctionDeclPointer(), clang::CodeGen::CGCallee::forBuiltin(), clang::CodeGen::CGCallee::forDirect(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCUDARuntime(), clang::GlobalDecl::getDecl(), clang::CodeGen::CGCUDARuntime::getKernelStub(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getMangledName(), clang::NamedDecl::getName(), clang::Decl::hasAttr(), clang::Builtin::Context::isPredefinedLibFunction(), and OnlyHasInlineBuiltinDeclaration().
EmitFunctionDeclLValue()
static LValue EmitFunctionDeclLValue (CodeGenFunction & CGF, const Expr * E, GlobalDecl GD) static
Definition at line 2646 of file CGExpr.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Decl, EmitFunctionDeclPointer(), clang::CodeGen::CodeGenFunction::getContext(), clang::GlobalDecl::getDecl(), clang::ASTContext::getDeclAlign(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and V.
EmitFunctionDeclPointer()
static llvm::Constant * EmitFunctionDeclPointer (CodeGenModule & CGM, GlobalDecl GD) static
Definition at line 2621 of file CGExpr.cpp.
References clang::cast(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getContext(), clang::GlobalDecl::getDecl(), clang::ASTContext::getFunctionNoProtoType(), clang::CodeGen::ConstantAddress::getPointer(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenModule::GetWeakRefReference(), clang::Decl::hasAttr(), clang::FunctionDecl::hasPrototype(), and V.
Referenced by EmitDirectCallee(), and EmitFunctionDeclLValue().
EmitGlobalNamedRegister()
static LValue EmitGlobalNamedRegister (const VarDecl * VD, CodeGenModule & CGM) static
Named Registers are named metadata pointing to the register name which will be read from/written to as an argument to the intrinsic @llvm.read/write_register.
So far, only the name is being passed down, but other options such as register type, allocation type or even optimization options could be passed down via the metadata node.
Definition at line 2668 of file CGExpr.cpp.
References clang::Asm, clang::Decl::getAttr(), clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getDeclAlign(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), clang::ValueDecl::getType(), and clang::CodeGen::LValue::MakeGlobalReg().
EmitGlobalVarDeclLValue()
static LValue EmitGlobalVarDeclLValue (CodeGenFunction & CGF, const Expr * E, const VarDecl * VD) static
Definition at line 2581 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::Decl, EmitBitCastOfLValueToProperType(), emitDeclTargetVarDeclLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue(), clang::CodeGen::CGCXXABI::EmitThreadLocalVarDeclLValue(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalVar(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::ASTContext::getDeclAlign(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::VarDecl::getTLSKind(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::Decl::hasAttr(), clang::Type::isReferenceType(), clang::CodeGen::Address::isValid(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), setObjCGCLValueClass(), clang::VarDecl::TLS_Dynamic, clang::VarDecl::TLS_None, clang::CodeGen::CGCXXABI::usesThreadWrapperFunction(), and V.
emitHash16Bytes()
static llvm::Value * emitHash16Bytes (CGBuilderTy & Builder, llvm::Value * Low, llvm::Value * High) static
Emit the hash_16_bytes function from include/llvm/ADT/Hashing.h.
Definition at line 640 of file CGExpr.cpp.
EmitLoadOfMatrixLValue()
static RValue EmitLoadOfMatrixLValue (LValue LV, SourceLocation Loc, CodeGenFunction & CGF) static
Definition at line 1928 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::RValue::get(), and MaybeConvertMatrixAddress().
EmitLValueOrThrowExpression()
static std::optional< LValue > EmitLValueOrThrowExpression (CodeGenFunction & CGF, const Expr * Operand) static
Emit the operand of a glvalue conditional operator.
This is either a glvalue or a (possibly-parenthesized) throw-expression. If this is a throw, no LValue is returned and the current block has been terminated.
Definition at line 4587 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitCXXThrowExpr(), and clang::CodeGen::CodeGenFunction::EmitLValue().
emitOMPArraySectionBase()
static Address emitOMPArraySectionBase (CodeGenFunction & CGF, const Expr * Base, LValueBaseInfo & BaseInfo, TBAAAccessInfo & TBAAInfo, QualType BaseTy, QualType ElTy, bool IsLowerBound) static
Definition at line 3965 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::Type::isArrayType(), clang::Type::isVariableArrayType(), clang::CodeGen::CodeGenModule::mergeTBAAInfoForCast(), and clang::CodeGen::Address::withElementType().
EmitPointerWithAlignment()
static Address EmitPointerWithAlignment (const Expr * E, LValueBaseInfo * BaseInfo, TBAAAccessInfo * TBAAInfo, KnownNonNull_t IsKnownNonNull, CodeGenFunction & CGF) static
Definition at line 1033 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CFITCK_UnrelatedCast, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateAddrSpaceCast(), clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), clang::CodeGen::LValueBaseInfo::getAlignmentSource(), clang::Type::getAs(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getNaturalPointeeTypeAlignment(), clang::Type::getPointeeType(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), clang::CodeGen::Address::getType(), clang::Expr::getType(), clang::SanitizerSet::has(), clang::Expr::IgnoreParens(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), clang::CodeGen::CodeGenModule::mergeTBAAInfoForCast(), clang::CodeGen::CodeGenFunction::SanOpts, clang::CodeGen::CodeGenFunction::ShouldNullCheckClassCastValue(), and clang::CodeGen::Address::withElementType().
emitPreserveStructAccess()
static Address emitPreserveStructAccess (CodeGenFunction & CGF, LValue base, Address addr, const FieldDecl * field) static
Definition at line 4328 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::CodeGen::CodeGenFunction::getDebugInfoFIndex(), clang::FieldDecl::getFieldIndex(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::Decl::getLocation(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::FieldDecl::getParent(), and clang::CodeGen::CodeGenModule::getTypes().
emitPseudoObjectExpr()
static LValueOrRValue emitPseudoObjectExpr (CodeGenFunction & CGF, const PseudoObjectExpr * E, bool forLValue, AggValueSlot slot) static
Definition at line 5632 of file CGExpr.cpp.
References clang::CodeGen::AggValueSlot::asRValue(), clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitAggExpr(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::AggValueSlot::getAddress(), clang::PseudoObjectExpr::getResultExpr(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenFunction::hasAggregateEvaluationKind(), clang::Expr::isPRValue(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::PseudoObjectExpr::semantics_begin(), and clang::PseudoObjectExpr::semantics_end().
EmitStoreOfMatrixScalar()
static void EmitStoreOfMatrixScalar (llvm::Value * value, LValue lvalue, bool isInit, CodeGenFunction & CGF) static
Definition at line 1849 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), and MaybeConvertMatrixAddress().
EmitThreadPrivateVarDeclLValue()
static LValue EmitThreadPrivateVarDeclLValue (CodeGenFunction & CGF, const VarDecl * VD, QualType T, Address Addr, llvm::Type * RealVarTy, SourceLocation Loc) static
Definition at line 2503 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Decl, clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and clang::CodeGen::Address::withElementType().
Referenced by EmitGlobalVarDeclLValue().
getArrayElementAlign()
static CharUnits getArrayElementAlign (CharUnits arrayAlign, llvm::Value * idx, CharUnits eltSize) static
Definition at line 3685 of file CGExpr.cpp.
References clang::CharUnits::alignmentAtOffset(), and clang::CharUnits::alignmentOfArrayElement().
Referenced by emitArraySubscriptGEP().
getArrayIndexingBound()
static llvm::Value * getArrayIndexingBound (CodeGenFunction & CGF, const Expr * Base, QualType & IndexedType, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel) static
If Base is known to point to the start of an array, return the length of that array.
Return 0 if the length cannot be determined.
Definition at line 915 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::Type::castAsArrayTypeUnsafe(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getVLASize(), clang::CodeGen::CodeGenFunction::LoadPassedObjectSize(), and clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts.
getFixedSizeElementType()
static QualType getFixedSizeElementType (const ASTContext & ctx, const VariableArrayType * vla) static
Definition at line 3700 of file CGExpr.cpp.
References clang::ASTContext::getAsVariableArrayType(), and clang::ArrayType::getElementType().
Referenced by emitArraySubscriptGEP().
getRangeForType()
static bool getRangeForType (CodeGenFunction & CGF, QualType Ty, llvm::APInt & Min, llvm::APInt & End, bool StrictEnums, bool IsBool) static
Definition at line 1633 of file CGExpr.cpp.
References clang::Type::getAs(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::ASTContext::getTypeSize(), and clang::EnumDecl::getValueRange().
getRecoverableKind()
static CheckRecoverableKind getRecoverableKind (SanitizerMask Kind) static
Definition at line 3210 of file CGExpr.cpp.
hasAnyVptr()
static bool hasAnyVptr (const QualType Type, const ASTContext & Context) static
Definition at line 4341 of file CGExpr.cpp.
References clang::CXXRecordDecl::bases(), clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), hasAnyVptr(), and clang::CXXRecordDecl::isDynamicClass().
Referenced by hasAnyVptr().
hasBooleanRepresentation()
static bool hasBooleanRepresentation (QualType Ty) static
Definition at line 1620 of file CGExpr.cpp.
References clang::Type::getAs(), hasBooleanRepresentation(), and clang::Type::isBooleanType().
Referenced by hasBooleanRepresentation().
isAAPCS()
static bool isAAPCS (const TargetInfo & TargetInfo) static
Helper method to check if the underlying ABI is AAPCS.
Definition at line 427 of file CGExpr.cpp.
References clang::TargetInfo::getABI().
isConstantEmittableObjectType()
static bool isConstantEmittableObjectType (QualType type) static
Given an object of the given canonical type, can we safely copy a value out of it based on its initializer?
Definition at line 1449 of file CGExpr.cpp.
References clang::Qualifiers::hasConst(), clang::CXXRecordDecl::hasMutableFields(), clang::Qualifiers::hasVolatile(), and clang::CXXRecordDecl::isTrivial().
Referenced by checkVarTypeForConstantEmission().
IsPreserveAIArrayBase()
static bool IsPreserveAIArrayBase (CodeGenFunction & CGF, const Expr * ArrayBase) static
Given an array base, check whether its member access belongs to a record with preserve_access_index attribute or not.
Definition at line 3711 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::MemberExpr::getMemberDecl(), clang::PointerType::getPointeeType(), clang::Type::getUnqualifiedDesugaredType(), clang::Decl::hasAttr(), clang::Type::hasAttr(), and clang::Expr::IgnoreImpCasts().
Referenced by emitArraySubscriptGEP().
isSimpleArrayDecayOperand()
static const Expr * isSimpleArrayDecayOperand (const Expr * E) static
isSimpleArrayDecayOperand - If the specified expr is a simple decay from an array to pointer, return the array subexpression.
Definition at line 3654 of file CGExpr.cpp.
References clang::FullExpr::getSubExpr(), clang::Expr::getType(), and clang::Type::isVariableArrayType().
MaybeConvertMatrixAddress()
static Address MaybeConvertMatrixAddress (Address Addr, CodeGenFunction & CGF, bool IsVector = true) static
Definition at line 1825 of file CGExpr.cpp.
References clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::withElementType().
Referenced by EmitLoadOfMatrixLValue(), and EmitStoreOfMatrixScalar().
OnlyHasInlineBuiltinDeclaration()
static bool OnlyHasInlineBuiltinDeclaration (const FunctionDecl * FD) static
Definition at line 5022 of file CGExpr.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl().
Referenced by EmitDirectCallee().
pushTemporaryCleanup()
static void pushTemporaryCleanup (CodeGenFunction & CGF, const MaterializeTemporaryExpr * M, const Expr * E, Address ReferenceTemporary) static
Definition at line 264 of file CGExpr.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::destroyARCStrongImprecise, clang::CodeGen::CodeGenFunction::destroyARCStrongPrecise, clang::CodeGen::CodeGenFunction::destroyARCWeak, clang::CodeGen::CodeGenFunction::destroyCXXObject, clang::Dtor_Complete, clang::CodeGen::EHCleanup, clang::CodeGen::CodeGenFunction::generateDestroyHelper(), clang::CodeGen::CodeGenModule::getAddrAndTypeOfCXXStructor(), clang::CodeGen::CodeGenFunction::getARCCleanupKind(), clang::Type::getAs(), clang::Type::getBaseElementTypeUnsafe(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::MaterializeTemporaryExpr::getExtendingDecl(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::QualType::getObjCLifetime(), clang::CodeGen::Address::getPointer(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::Expr::getType(), clang::Decl::hasAttr(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::isa(), clang::Type::isArrayType(), clang::CodeGen::NormalAndEHCleanup, clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, clang::CodeGen::CodeGenFunction::pushDestroy(), clang::CodeGen::CodeGenFunction::pushLifetimeExtendedDestroy(), clang::CodeGen::CGCXXABI::registerGlobalDtor(), clang::SD_Automatic, clang::SD_Dynamic, clang::SD_FullExpression, clang::SD_Static, and clang::SD_Thread.
setObjCGCLValueClass()
static void setObjCGCLValueClass (const ASTContext & Ctx, const Expr * E, LValue & LV, bool IsMemberAccess = false) static
Definition at line 2398 of file CGExpr.cpp.
References clang::cast(), clang::Type::castAs(), clang::ASTContext::getLangOpts(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Type::isPointerType(), clang::Type::isRecordType(), clang::LangOptions::NonGC, setObjCGCLValueClass(), and clang::VarDecl::TLS_None.
Referenced by EmitGlobalVarDeclLValue(), and setObjCGCLValueClass().
tryToConvertMemberExprToDeclRefExpr()
static DeclRefExpr * tryToConvertMemberExprToDeclRefExpr (CodeGenFunction & CGF, const MemberExpr * ME) static
Definition at line 1584 of file CGExpr.cpp.
References clang::DeclRefExpr::Create(), clang::CodeGen::CodeGenFunction::getContext(), clang::MemberExpr::getExprLoc(), clang::MemberExpr::getMemberDecl(), clang::Expr::getType(), clang::Expr::getValueKind(), and clang::MemberExpr::isNonOdrUse().
Variable Documentation
SanitizerHandlers
const SanitizerHandlerInfo SanitizerHandlers[]
Initial value:
= {
#define SANITIZER_CHECK(Enum, Name, Version)
    LIST_SANITIZER_CHECKS
}
Definition at line 3227 of file CGExpr.cpp.
Referenced by emitCheckHandlerCall().