clang: lib/CodeGen/CGHLSLRuntime.cpp File Reference
CGHLSLRuntime.cpp File Reference
#include "CGHLSLRuntime.h"
#include "CGDebugInfo.h"
#include "CodeGenModule.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/TargetOptions.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static llvm::hlsl::ResourceKind castResourceShapeToResourceKind (HLSLResourceAttr::ResourceKind RK)
static Value * buildVectorInput (IRBuilder<> &B, Function *F, llvm::Type *Ty)
static void gatherFunctions (SmallVectorImpl< Function * > &Fns, llvm::Module &M, bool CtorOrDtor)
Function Documentation
buildVectorInput()
static Value * buildVectorInput (IRBuilder<> & B, Function * F, llvm::Type * Ty) static
Definition at line 328 of file CGHLSLRuntime.cpp.
References clang::Result.
Referenced by clang::CodeGen::CGHLSLRuntime::emitInputSemantic().
castResourceShapeToResourceKind()
static llvm::hlsl::ResourceKind castResourceShapeToResourceKind (HLSLResourceAttr::ResourceKind RK) static
Definition at line 227 of file CGHLSLRuntime.cpp.
Referenced by clang::CodeGen::CGHLSLRuntime::annotateHLSLResource().
gatherFunctions()
static void gatherFunctions (SmallVectorImpl< Function * > & Fns, llvm::Module & M, bool CtorOrDtor) static
Definition at line 400 of file CGHLSLRuntime.cpp.
References clang::cast().
Referenced by clang::CodeGen::CGHLSLRuntime::generateGlobalCtorDtorCalls().