clang: lib/CodeGen/CGStmtOpenMP.cpp File Reference
CGStmtOpenMP.cpp File Reference
#include "CGCleanup.h"
#include "CGOpenMPRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/PrettyStackTrace.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/Frontend/OpenMP/OMPConstants.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/AtomicOrdering.h"
#include <optional>
Typedefs
using EmittedClosureTy = std::pair<llvm::Function *, llvm::Value *>
Functions
static const VarDecl * getBaseDecl (const Expr *Ref)
static void emitCommonOMPTargetDirective (CodeGenFunction &CGF, const OMPExecutableDirective &S, const RegionCodeGenTy &CodeGen)
static Address castValueFromUintptr (CodeGenFunction &CGF, SourceLocation Loc, QualType DstType, StringRef Name, LValue AddrLV)
static QualType getCanonicalParamType (ASTContext &C, QualType T)
static llvm::Function * emitOutlinedFunctionPrologue (CodeGenFunction &CGF, FunctionArgList &Args, llvm::MapVector< const Decl *, std::pair< const VarDecl *, Address > > &LocalAddrs, llvm::DenseMap< const Decl *, std::pair< const Expr *, llvm::Value * > > &VLASizes, llvm::Value *&CXXThisValue, const FunctionOptions &FO)
static void emitPostUpdateForReductionClause (CodeGenFunction &CGF, const OMPExecutableDirective &D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen)
static void checkForLastprivateConditionalUpdate (CodeGenFunction &CGF, const OMPExecutableDirective &S)
static void emitCommonOMPParallelDirective (CodeGenFunction &CGF, const OMPExecutableDirective &S, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen, const CodeGenBoundParametersTy &CodeGenBoundParameters)
static bool isAllocatableDecl (const VarDecl *VD)
static void emitEmptyBoundParameters (CodeGenFunction &, const OMPExecutableDirective &, llvm::SmallVectorImpl< llvm::Value * > &)
static void emitOMPCopyinClause (CodeGenFunction &CGF, const OMPExecutableDirective &S)
static void emitBody (CodeGenFunction &CGF, const Stmt *S, const Stmt *NextLoop, int MaxLevel, int Level=0)
static EmittedClosureTy emitCapturedStmtFunc (CodeGenFunction &ParentCGF, const CapturedStmt *S)
Emit a captured statement and return the function as well as its captured closure context.
static llvm::CallInst * emitCapturedStmtCall (CodeGenFunction &ParentCGF, EmittedClosureTy Cap, llvm::ArrayRef< llvm::Value * > Args)
Emit a call to a previously captured closure.
static void emitAlignedClause (CodeGenFunction &CGF, const OMPExecutableDirective &D)
static void emitPreCond (CodeGenFunction &CGF, const OMPLoopDirective &S, const Expr *Cond, llvm::BasicBlock *TrueBlock, llvm::BasicBlock *FalseBlock, uint64_t TrueCount)
static void emitSimdlenSafelenClause (CodeGenFunction &CGF, const OMPExecutableDirective &D)
static void emitOMPLoopBodyWithStopPoint (CodeGenFunction &CGF, const OMPLoopDirective &S, CodeGenFunction::JumpDest LoopExit)
static LValue EmitOMPHelperVar (CodeGenFunction &CGF, const DeclRefExpr *Helper)
Emit a helper variable and return corresponding lvalue.
static void emitCommonSimdLoop (CodeGenFunction &CGF, const OMPLoopDirective &S, const RegionCodeGenTy &SimdInitGen, const RegionCodeGenTy &BodyCodeGen)
static void emitOMPSimdRegion (CodeGenFunction &CGF, const OMPLoopDirective &S, PrePostActionTy &Action)
static bool isSupportedByOpenMPIRBuilder (const OMPSimdDirective &S)
static llvm::MapVector< llvm::Value *, llvm::Value * > GetAlignedMapping (const OMPSimdDirective &S, CodeGenFunction &CGF)
static void emitEmptyOrdered (CodeGenFunction &, SourceLocation Loc, const unsigned IVSize, const bool IVSigned)
static std::pair< LValue, LValue > emitDistributeParallelForInnerBounds (CodeGenFunction &CGF, const OMPExecutableDirective &S)
static std::pair< llvm::Value *, llvm::Value * > emitDistributeParallelForDispatchBounds (CodeGenFunction &CGF, const OMPExecutableDirective &S, Address LB, Address UB)
if the 'for' loop has a dispatch schedule (e.g.
static void emitDistributeParallelForDistributeInnerBoundParams (CodeGenFunction &CGF, const OMPExecutableDirective &S, llvm::SmallVectorImpl< llvm::Value * > &CapturedVars)
static void emitInnerParallelForWhenCombined (CodeGenFunction &CGF, const OMPLoopDirective &S, CodeGenFunction::JumpDest LoopExit)
static std::pair< LValue, LValue > emitForLoopBounds (CodeGenFunction &CGF, const OMPExecutableDirective &S)
The following two functions generate expressions for the loop lower and upper bounds in case of static and dynamic (dispatch) schedule of the associated 'for' or 'distribute' loop.
static std::pair< llvm::Value *, llvm::Value * > emitDispatchForLoopBounds (CodeGenFunction &CGF, const OMPExecutableDirective &S, Address LB, Address UB)
When dealing with dispatch schedules (e.g.
static void emitScanBasedDirectiveDecls (CodeGenFunction &CGF, const OMPLoopDirective &S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen)
Emits internal temp array declarations for the directive with inscan reductions.
static void emitScanBasedDirectiveFinals (CodeGenFunction &CGF, const OMPLoopDirective &S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen)
Copies final inscan reductions values to the original variables.
static void emitScanBasedDirective (CodeGenFunction &CGF, const OMPLoopDirective &S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen, llvm::function_ref< void(CodeGenFunction &)> FirstGen, llvm::function_ref< void(CodeGenFunction &)> SecondGen)
Emits the code for the directive with inscan reductions.
static bool emitWorksharingDirective (CodeGenFunction &CGF, const OMPLoopDirective &S, bool HasCancel)
static bool isSupportedByOpenMPIRBuilder (const OMPForDirective &S)
static llvm::omp::ScheduleKind convertClauseKindToSchedKind (OpenMPScheduleClauseKind ScheduleClauseKind)
static LValue createSectionLVal (CodeGenFunction &CGF, QualType Ty, const Twine &Name, llvm::Value *Init=nullptr)
static void emitMaster (CodeGenFunction &CGF, const OMPExecutableDirective &S)
static void emitMasked (CodeGenFunction &CGF, const OMPExecutableDirective &S)
static void buildDependences (const OMPExecutableDirective &S, OMPTaskDataTy &Data)
static ImplicitParamDecl * createImplicitFirstprivateForType (ASTContext &C, OMPTaskDataTy &Data, QualType Ty, CapturedDecl *CD, SourceLocation Loc)
bool isSupportedByOpenMPIRBuilder (const OMPTaskgroupDirective &T)
static llvm::Function * emitOutlinedOrderedFunction (CodeGenModule &CGM, const CapturedStmt *S, SourceLocation Loc)
template<typename T >
static void emitRestoreIP (CodeGenFunction &CGF, const T *C, llvm::OpenMPIRBuilder::InsertPointTy AllocaIP, llvm::OpenMPIRBuilder &OMPBuilder)
static llvm::Value * convertToScalarValue (CodeGenFunction &CGF, RValue Val, QualType SrcType, QualType DestType, SourceLocation Loc)
static CodeGenFunction::ComplexPairTy convertToComplexValue (CodeGenFunction &CGF, RValue Val, QualType SrcType, QualType DestType, SourceLocation Loc)
static void emitSimpleAtomicStore (CodeGenFunction &CGF, llvm::AtomicOrdering AO, LValue LVal, RValue RVal)
static RValue emitSimpleAtomicLoad (CodeGenFunction &CGF, llvm::AtomicOrdering AO, LValue LVal, SourceLocation Loc)
static void emitOMPAtomicReadExpr (CodeGenFunction &CGF, llvm::AtomicOrdering AO, const Expr *X, const Expr *V, SourceLocation Loc)
static void emitOMPAtomicWriteExpr (CodeGenFunction &CGF, llvm::AtomicOrdering AO, const Expr *X, const Expr *E, SourceLocation Loc)
static std::pair< bool, RValue > emitOMPAtomicRMW (CodeGenFunction &CGF, LValue X, RValue Update, BinaryOperatorKind BO, llvm::AtomicOrdering AO, bool IsXLHSInRHSPart)
static void emitOMPAtomicUpdateExpr (CodeGenFunction &CGF, llvm::AtomicOrdering AO, const Expr *X, const Expr *E, const Expr *UE, bool IsXLHSInRHSPart, SourceLocation Loc)
static RValue convertToType (CodeGenFunction &CGF, RValue Value, QualType SourceType, QualType ResType, SourceLocation Loc)
static void emitOMPAtomicCaptureExpr (CodeGenFunction &CGF, llvm::AtomicOrdering AO, bool IsPostfixUpdate, const Expr *V, const Expr *X, const Expr *E, const Expr *UE, bool IsXLHSInRHSPart, SourceLocation Loc)
static void emitOMPAtomicCompareExpr (CodeGenFunction &CGF, llvm::AtomicOrdering AO, const Expr *X, const Expr *V, const Expr *R, const Expr *E, const Expr *D, const Expr *CE, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly, SourceLocation Loc)
static void emitOMPAtomicExpr (CodeGenFunction &CGF, OpenMPClauseKind Kind, llvm::AtomicOrdering AO, bool IsPostfixUpdate, const Expr *X, const Expr *V, const Expr *R, const Expr *E, const Expr *UE, const Expr *D, const Expr *CE, bool IsXLHSInRHSPart, bool IsFailOnly, SourceLocation Loc)
static void emitTargetRegion (CodeGenFunction &CGF, const OMPTargetDirective &S, PrePostActionTy &Action)
static void emitCommonOMPTeamsDirective (CodeGenFunction &CGF, const OMPExecutableDirective &S, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen)
static void emitTargetTeamsRegion (CodeGenFunction &CGF, PrePostActionTy &Action, const OMPTargetTeamsDirective &S)
static void emitTargetTeamsDistributeRegion (CodeGenFunction &CGF, PrePostActionTy &Action, const OMPTargetTeamsDistributeDirective &S)
static void emitTargetTeamsDistributeSimdRegion (CodeGenFunction &CGF, PrePostActionTy &Action, const OMPTargetTeamsDistributeSimdDirective &S)
static void emitTargetTeamsDistributeParallelForRegion (CodeGenFunction &CGF, const OMPTargetTeamsDistributeParallelForDirective &S, PrePostActionTy &Action)
static void emitTargetTeamsDistributeParallelForSimdRegion (CodeGenFunction &CGF, const OMPTargetTeamsDistributeParallelForSimdDirective &S, PrePostActionTy &Action)
static void emitTargetParallelRegion (CodeGenFunction &CGF, const OMPTargetParallelDirective &S, PrePostActionTy &Action)
static void emitTargetParallelForRegion (CodeGenFunction &CGF, const OMPTargetParallelForDirective &S, PrePostActionTy &Action)
static void emitTargetParallelForSimdRegion (CodeGenFunction &CGF, const OMPTargetParallelForSimdDirective &S, PrePostActionTy &Action)
static void mapParam (CodeGenFunction &CGF, const DeclRefExpr *Helper, const ImplicitParamDecl *PVD, CodeGenFunction::OMPPrivateScope &Privates)
Emit a helper variable and return corresponding lvalue.
static void emitTargetTeamsGenericLoopRegion (CodeGenFunction &CGF, const OMPTargetTeamsGenericLoopDirective &S, PrePostActionTy &Action)
static void emitTargetParallelGenericLoopRegion (CodeGenFunction &CGF, const OMPTargetParallelGenericLoopDirective &S, PrePostActionTy &Action)
Typedef Documentation
EmittedClosureTy
using EmittedClosureTy = std::pair<llvm::Function *, llvm::Value *>
Definition at line 1953 of file CGStmtOpenMP.cpp.
Function Documentation
buildDependences()
static void buildDependences (const OMPExecutableDirective & S, OMPTaskDataTy & Data) static
Definition at line 4578 of file CGStmtOpenMP.cpp.
References clang::C, Data, and clang::CodeGen::OMPTaskDataTy::DependData::DepExprs.
castValueFromUintptr()
static Address castValueFromUintptr (CodeGenFunction & CGF, SourceLocation Loc, QualType DstType, StringRef Name, LValue AddrLV) static
Definition at line 372 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getPointerType(), clang::ASTContext::getUIntPtrType(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
Referenced by emitOutlinedFunctionPrologue().
checkForLastprivateConditionalUpdate()
static void checkForLastprivateConditionalUpdate (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 1484 of file CGStmtOpenMP.cpp.
References clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::CodeGen::CodeGenFunction::getLangOpts(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
convertClauseKindToSchedKind()
static llvm::omp::ScheduleKind convertClauseKindToSchedKind (OpenMPScheduleClauseKind ScheduleClauseKind) static
Definition at line 3878 of file CGStmtOpenMP.cpp.
References clang::OMPC_SCHEDULE_unknown.
convertToComplexValue()
static CodeGenFunction::ComplexPairTy convertToComplexValue (CodeGenFunction & CGF, RValue Val, QualType SrcType, QualType DestType, SourceLocation Loc) static
Definition at line 5973 of file CGStmtOpenMP.cpp.
References clang::Type::castAs(), clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::RValue::getComplexVal(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::RValue::isComplex(), clang::CodeGen::RValue::isScalar(), and clang::CodeGen::TEK_Complex.
Referenced by convertToType().
convertToScalarValue()
static llvm::Value * convertToScalarValue (CodeGenFunction & CGF, RValue Val, QualType SrcType, QualType DestType, SourceLocation Loc) static
Definition at line 5960 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::EmitComplexToScalarConversion(), clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::RValue::getComplexVal(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenFunction::hasScalarEvaluationKind(), clang::CodeGen::RValue::isAggregate(), and clang::CodeGen::RValue::isScalar().
Referenced by convertToType().
convertToType()
static RValue convertToType (CodeGenFunction & CGF, RValue Value, QualType SourceType, QualType ResType, SourceLocation Loc) static
Definition at line 6284 of file CGStmtOpenMP.cpp.
References convertToComplexValue(), convertToScalarValue(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getComplex(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by emitOMPAtomicCaptureExpr().
createImplicitFirstprivateForType()
static ImplicitParamDecl * createImplicitFirstprivateForType (ASTContext & C, OMPTaskDataTy & Data, QualType Ty, CapturedDecl * CD, SourceLocation Loc) static
Definition at line 4990 of file CGStmtOpenMP.cpp.
References clang::C, clang::VarDecl::CInit, clang::DeclRefExpr::Create(), clang::ImplicitCastExpr::Create(), clang::ImplicitParamDecl::Create(), Data, clang::ImplicitParamDecl::Other, clang::VK_LValue, and clang::VK_PRValue.
createSectionLVal()
static LValue createSectionLVal (CodeGenFunction & CGF, QualType Ty, const Twine & Name, llvm::Value * Init = nullptr) static
Definition at line 3971 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::RValue::get(), and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
emitAlignedClause()
static void emitAlignedClause (CodeGenFunction & CGF, const OMPExecutableDirective & D) static
Definition at line 2221 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::emitAlignmentAssumption(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::ASTContext::getOpenMPDefaultSimdAlign(), clang::Type::getPointeeType(), clang::CharUnits::getQuantity(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::HaveInsertPoint(), and clang::ASTContext::toCharUnitsFromBits().
Referenced by emitOMPSimdRegion().
emitBody()
static void emitBody (CodeGenFunction & CGF, const Stmt * S, const Stmt * NextLoop, int MaxLevel, int Level = 0) static
Definition at line 1846 of file CGStmtOpenMP.cpp.
References clang::cast(), emitBody(), clang::CodeGen::CodeGenFunction::EmitStmt(), clang::CodeGen::CodeGenFunction::getContext(), and clang::ASTContext::getSourceManager().
Referenced by emitBody().
emitCapturedStmtCall()
static llvm::CallInst * emitCapturedStmtCall (CodeGenFunction & ParentCGF, EmittedClosureTy Cap, llvm::ArrayRef< llvm::Value * > Args) static
Emit a call to a previously captured closure.
Definition at line 1971 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenFunction::ParentCGF.
emitCapturedStmtFunc()
static EmittedClosureTy emitCapturedStmtFunc (CodeGenFunction & ParentCGF, const CapturedStmt * S) static
Emit a captured statement and return the function as well as its captured closure context.
Definition at line 1957 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::GenerateCapturedStmtFunction(), clang::CodeGen::CodeGenFunction::InitCapturedStruct(), and clang::CodeGen::CodeGenFunction::ParentCGF.
emitCommonOMPParallelDirective()
static void emitCommonOMPParallelDirective (CodeGenFunction & CGF, const OMPExecutableDirective & S, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy & CodeGen, const CodeGenBoundParametersTy & CodeGenBoundParameters) static
Definition at line 1540 of file CGStmtOpenMP.cpp.
References clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitNumThreadsClause(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntime::emitParallelOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitProcBindClause(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::GenerateOpenMPCapturedVars(), clang::CapturedStmt::getCapturedDecl(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CapturedDecl::param_begin().
Referenced by emitInnerParallelForWhenCombined(), emitTargetParallelForRegion(), emitTargetParallelForSimdRegion(), emitTargetParallelGenericLoopRegion(), and emitTargetParallelRegion().
emitCommonOMPTargetDirective()
static void emitCommonOMPTargetDirective (CodeGenFunction & CGF, const OMPExecutableDirective & S, const RegionCodeGenTy & CodeGen) static
Definition at line 6578 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConstantFoldsToSimpleInteger(), clang::Ctor_Complete, clang::CodeGen::CodeGenFunction::CurFuncDecl, clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalRAII::disable(), clang::Dtor_Complete, clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitStmt(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunction(), clang::DiagnosticsEngine::Error, clang::DiagnosticsEngine::getCustomDiagID(), clang::CodeGen::CodeGenModule::getDiags(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getMangledName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::isOpenMPTargetExecutionDirective(), clang::OMPC_DEVICE_unknown, clang::LangOptions::OMPTargetTriples, and clang::DiagnosticsEngine::Report().
emitCommonOMPTeamsDirective()
static void emitCommonOMPTeamsDirective (CodeGenFunction & CGF, const OMPExecutableDirective & S, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy & CodeGen) static
Definition at line 6701 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), clang::CodeGen::CGOpenMPRuntime::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntime::emitTeamsOutlinedFunction(), clang::CodeGen::CodeGenFunction::GenerateOpenMPCapturedVars(), clang::CapturedStmt::getCapturedDecl(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CapturedDecl::param_begin().
Referenced by emitTargetTeamsDistributeParallelForRegion(), emitTargetTeamsDistributeParallelForSimdRegion(), emitTargetTeamsDistributeRegion(), emitTargetTeamsDistributeSimdRegion(), emitTargetTeamsGenericLoopRegion(), and emitTargetTeamsRegion().
emitCommonSimdLoop()
static void emitCommonSimdLoop (CodeGenFunction & CGF, const OMPLoopDirective & S, const RegionCodeGenTy & SimdInitGen, const RegionCodeGenTy & BodyCodeGen) static
Definition at line 2475 of file CGStmtOpenMP.cpp.
References clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitIfClause(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::isOpenMPSimdDirective(), clang::CodeGen::CodeGenFunction::LoopStack, and clang::CodeGen::LoopInfoStack::setVectorizeEnable().
Referenced by emitOMPSimdRegion().
emitDispatchForLoopBounds()
static std::pair< llvm::Value *, llvm::Value * > emitDispatchForLoopBounds (CodeGenFunction & CGF, const OMPExecutableDirective & S, Address LB, Address UB) static
When dealing with dispatch schedules (e.g.
dynamic, guided) we do not consider the lower and upper bound expressions generated by the worksharing loop support, but we use 0 and the iteration space size as constants
Definition at line 3526 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::getContext(), clang::Expr::getType(), and clang::ASTContext::getTypeSize().
Referenced by emitTargetParallelForRegion(), emitTargetParallelForSimdRegion(), emitTargetParallelGenericLoopRegion(), and emitWorksharingDirective().
emitDistributeParallelForDispatchBounds()
static std::pair< llvm::Value *, llvm::Value * > emitDistributeParallelForDispatchBounds (CodeGenFunction & CGF, const OMPExecutableDirective & S, Address LB, Address UB) static
if the 'for' loop has a dispatch schedule (e.g.
dynamic, guided) then we need to use the LB and UB expressions generated by the worksharing code generation support, whereas in non combined situations we would just emit 0 and the LastIteration expression This function is necessary due to the difference of the LB and UB types for the RT emission routines for 'for_static_init' and 'for_dispatch_init'
Definition at line 3137 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), and clang::Expr::getType().
Referenced by emitInnerParallelForWhenCombined().
emitDistributeParallelForDistributeInnerBoundParams()
static void emitDistributeParallelForDistributeInnerBoundParams (CodeGenFunction & CGF, const OMPExecutableDirective & S, llvm::SmallVectorImpl< llvm::Value * > & CapturedVars) static
Definition at line 3154 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::EmitLValue(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by emitInnerParallelForWhenCombined().
emitDistributeParallelForInnerBounds()
static std::pair< LValue, LValue > emitDistributeParallelForInnerBounds (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 3094 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValue(), EmitOMPHelperVar(), clang::CodeGen::CodeGenFunction::EmitScalarConversion(), and clang::CodeGen::CodeGenFunction::EmitStoreOfScalar().
Referenced by emitInnerParallelForWhenCombined().
emitEmptyBoundParameters()
static void emitEmptyBoundParameters (CodeGenFunction & , const OMPExecutableDirective & , llvm::SmallVectorImpl< llvm::Value * > &) static
Definition at line 1594 of file CGStmtOpenMP.cpp.
Referenced by emitTargetParallelForRegion(), emitTargetParallelForSimdRegion(), emitTargetParallelGenericLoopRegion(), and emitTargetParallelRegion().
emitEmptyOrdered()
static void emitEmptyOrdered (CodeGenFunction & , SourceLocation Loc, const unsigned IVSize, const bool IVSigned) static
Definition at line 3030 of file CGStmtOpenMP.cpp.
emitForLoopBounds()
static std::pair< LValue, LValue > emitForLoopBounds (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
The following two functions generate expressions for the loop lower and upper bounds in case of static and dynamic (dispatch) schedule of the associated 'for' or 'distribute' loop.
Definition at line 3512 of file CGStmtOpenMP.cpp.
References clang::cast(), and EmitOMPHelperVar().
Referenced by emitTargetParallelForRegion(), emitTargetParallelForSimdRegion(), emitTargetParallelGenericLoopRegion(), and emitWorksharingDirective().
emitInnerParallelForWhenCombined()
static void emitInnerParallelForWhenCombined (CodeGenFunction & CGF, const OMPLoopDirective & S, CodeGenFunction::JumpDest LoopExit) static
Definition at line 3174 of file CGStmtOpenMP.cpp.
References emitCommonOMPParallelDirective(), emitDistributeParallelForDispatchBounds(), emitDistributeParallelForDistributeInnerBoundParams(), emitDistributeParallelForInnerBounds(), clang::CodeGen::CodeGenFunction::EmitOMPWorksharingLoop(), and clang::isOpenMPSimdDirective().
Referenced by emitTargetTeamsDistributeParallelForRegion(), emitTargetTeamsDistributeParallelForSimdRegion(), and emitTargetTeamsGenericLoopRegion().
emitMasked()
static void emitMasked (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 4303 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitMaskedRegion(), clang::CodeGen::CodeGenFunction::EmitStmt(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitMaster()
static void emitMaster (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 4267 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitMasterRegion(), clang::CodeGen::CodeGenFunction::EmitStmt(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitOMPAtomicCaptureExpr()
static void emitOMPAtomicCaptureExpr (CodeGenFunction & CGF, llvm::AtomicOrdering AO, bool IsPostfixUpdate, const Expr * V, const Expr * X, const Expr * E, const Expr * UE, bool IsXLHSInRHSPart, SourceLocation Loc) static
Definition at line 6301 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), convertToType(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitOMPAtomicSimpleUpdateExpr(), clang::CodeGen::CodeGenFunction::emitOMPSimpleStore(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::Expr::getType(), clang::Expr::IgnoreImpCasts(), clang::IsPostfixUpdate, clang::IsXLHSInRHSPart, V, and X.
Referenced by emitOMPAtomicExpr().
emitOMPAtomicCompareExpr()
static void emitOMPAtomicCompareExpr (CodeGenFunction & CGF, llvm::AtomicOrdering AO, const Expr * X, const Expr * V, const Expr * R, const Expr * E, const Expr * D, const Expr * CE, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly, SourceLocation Loc) static
Definition at line 6408 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::Expr::getType(), clang::Type::hasSignedIntegerRepresentation(), clang::Expr::IgnoreImplicitAsWritten(), clang::IsFailOnly, clang::IsPostfixUpdate, clang::QualType::isVolatileQualified(), V, and X.
Referenced by emitOMPAtomicExpr().
emitOMPAtomicExpr()
static void emitOMPAtomicExpr (CodeGenFunction & CGF, OpenMPClauseKind Kind, llvm::AtomicOrdering AO, bool IsPostfixUpdate, const Expr * X, const Expr * V, const Expr * R, const Expr * E, const Expr * UE, const Expr * D, const Expr * CE, bool IsXLHSInRHSPart, bool IsFailOnly, SourceLocation Loc) static
Definition at line 6484 of file CGStmtOpenMP.cpp.
References emitOMPAtomicCaptureExpr(), emitOMPAtomicCompareExpr(), emitOMPAtomicReadExpr(), emitOMPAtomicUpdateExpr(), emitOMPAtomicWriteExpr(), clang::IsFailOnly, clang::IsPostfixUpdate, clang::IsXLHSInRHSPart, V, and X.
emitOMPAtomicReadExpr()
static void emitOMPAtomicReadExpr (CodeGenFunction & CGF, llvm::AtomicOrdering AO, const Expr * X, const Expr * V, SourceLocation Loc) static
Definition at line 6035 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::emitOMPSimpleStore(), emitSimpleAtomicLoad(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), V, and X.
Referenced by emitOMPAtomicExpr().
emitOMPAtomicRMW()
static std::pair< bool, RValue > emitOMPAtomicRMW (CodeGenFunction & CGF, LValue X, RValue Update, BinaryOperatorKind BO, llvm::AtomicOrdering AO, bool IsXLHSInRHSPart) static
Definition at line 6093 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::ASTContext::getTargetInfo(), clang::ASTContext::getTypeSize(), clang::TargetInfo::hasBuiltinAtomic(), clang::IsXLHSInRHSPart, clang::ASTContext::toBits(), and X.
emitOMPAtomicUpdateExpr()
static void emitOMPAtomicUpdateExpr (CodeGenFunction & CGF, llvm::AtomicOrdering AO, const Expr * X, const Expr * E, const Expr * UE, bool IsXLHSInRHSPart, SourceLocation Loc) static
Definition at line 6236 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitOMPAtomicSimpleUpdateExpr(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::Expr::IgnoreImpCasts(), clang::IsXLHSInRHSPart, and X.
Referenced by emitOMPAtomicExpr().
emitOMPAtomicWriteExpr()
static void emitOMPAtomicWriteExpr (CodeGenFunction & CGF, llvm::AtomicOrdering AO, const Expr * X, const Expr * E, SourceLocation Loc) static
Definition at line 6066 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CodeGenFunction::EmitLValue(), emitSimpleAtomicStore(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and X.
Referenced by emitOMPAtomicExpr().
emitOMPCopyinClause()
static void emitOMPCopyinClause (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 1598 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), clang::CodeGen::CodeGenFunction::EmitOMPCopyinClause(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
EmitOMPHelperVar()
static LValue EmitOMPHelperVar (CodeGenFunction & CGF, const DeclRefExpr * Helper) static
Emit a helper variable and return corresponding lvalue.
Definition at line 2468 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitVarDecl(), and clang::DeclRefExpr::getDecl().
Referenced by emitDistributeParallelForInnerBounds(), emitForLoopBounds(), and emitOMPSimdRegion().
emitOMPLoopBodyWithStopPoint()
static void emitOMPLoopBodyWithStopPoint (CodeGenFunction & CGF, const OMPLoopDirective & S, CodeGenFunction::JumpDest LoopExit) static
Definition at line 2460 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::EmitOMPLoopBody(), and clang::CodeGen::CodeGenFunction::EmitStopPoint().
Referenced by emitTargetTeamsDistributeRegion(), and emitTargetTeamsDistributeSimdRegion().
emitOMPSimdRegion()
static void emitOMPSimdRegion (CodeGenFunction & CGF, const OMPLoopDirective & S, PrePostActionTy & Action) static
Definition at line 2511 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConstantFoldsToSimpleInteger(), clang::CodeGen::CodeGenFunction::createBasicBlock(), emitAlignedClause(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitBranch(), emitCommonSimdLoop(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitLValue(), EmitOMPHelperVar(), clang::CodeGen::CodeGenFunction::EmitOMPInnerLoop(), clang::CodeGen::CodeGenFunction::EmitOMPLastprivateClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPLastprivateClauseInit(), clang::CodeGen::CodeGenFunction::EmitOMPLinearClause(), clang::CodeGen::CodeGenFunction::EmitOMPLinearClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPLinearClauseInit(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateLoopCounters(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), clang::CodeGen::CodeGenFunction::EmitOMPSimdFinal(), clang::CodeGen::CodeGenFunction::EmitOMPSimdInit(), emitPostUpdateForReductionClause(), emitPreCond(), clang::CodeGen::CodeGenFunction::EmitVarDecl(), clang::CodeGen::PrePostActionTy::Enter(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenFunction::getProfileCount(), clang::CodeGen::CodeGenFunction::incrementProfileCounter(), clang::isOpenMPDistributeDirective(), clang::isOpenMPSimdDirective(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTaskLoopDirective(), and clang::isOpenMPWorksharingDirective().
emitOutlinedFunctionPrologue()
static llvm::Function * emitOutlinedFunctionPrologue (CodeGenFunction & CGF, FunctionArgList & Args, llvm::MapVector< const Decl *, std::pair< const VarDecl *, Address > > & LocalAddrs, llvm::DenseMap< const Decl *, std::pair< const Expr *, llvm::Value * > > & VLASizes, llvm::Value *& CXXThisValue, const FunctionOptions & FO) static
Definition at line 425 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CapturedStmt::captures(), castValueFromUintptr(), clang::CodeGen::CodeGenFunction::CGM, clang::FunctionDecl::Create(), clang::ImplicitParamDecl::Create(), clang::ParmVarDecl::Create(), clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::RecordDecl::fields(), clang::IdentifierTable::get(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CapturedStmt::getBeginLoc(), clang::DeclaratorDecl::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::CapturedDecl::getBody(), getCanonicalParamType(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedRecordDecl(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), clang::CapturedDecl::getContextParamPosition(), clang::ASTContext::getDeclAlign(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::ASTContext::getFunctionType(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CGOpenMPRuntime::getParameterAddress(), clang::VariableArrayType::getSizeExpr(), clang::VarDecl::getTLSKind(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::CodeGen::Address::getType(), clang::ValueDecl::getType(), getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::getUIntPtrType(), clang::Decl::hasBody(), clang::ASTContext::Idents, clang::CodeGen::Address::invalid(), clang::CapturedDecl::isNothrow(), clang::Type::isPointerType(), clang::Type::isVariablyModifiedType(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::ImplicitParamDecl::Other, clang::CapturedDecl::param_begin(), clang::CapturedDecl::param_end(), clang::SC_None, clang::SC_Static, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::ImplicitParamDecl::ThreadPrivateVar, clang::VarDecl::TLS_None, clang::CodeGen::CGOpenMPRuntime::translateParameter(), clang::ASTContext::VoidTy, and clang::CodeGen::Address::withAlignment().
emitOutlinedOrderedFunction()
static llvm::Function * emitOutlinedOrderedFunction (CodeGenModule & CGM, const CapturedStmt * S, SourceLocation Loc) static
Definition at line 5836 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CapturedStmtInfo, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenFunction::GenerateOpenMPCapturedStmtFunction().
emitPostUpdateForReductionClause()
static void emitPostUpdateForReductionClause (CodeGenFunction & CGF, const OMPExecutableDirective & D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen) static
Definition at line 1448 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::Cond, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), and clang::CodeGen::CodeGenFunction::HaveInsertPoint().
Referenced by emitOMPSimdRegion(), emitTargetParallelRegion(), emitTargetTeamsDistributeParallelForRegion(), emitTargetTeamsDistributeParallelForSimdRegion(), emitTargetTeamsDistributeRegion(), emitTargetTeamsDistributeSimdRegion(), emitTargetTeamsGenericLoopRegion(), and emitTargetTeamsRegion().
emitPreCond()
static void emitPreCond (CodeGenFunction & CGF, const OMPLoopDirective & S, const Expr * Cond, llvm::BasicBlock * TrueBlock, llvm::BasicBlock * FalseBlock, uint64_t TrueCount) static
Definition at line 2298 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::Cond, clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateLoopCounters(), clang::QualType::getNonReferenceType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::HaveInsertPoint(), and clang::Type::isRecordType().
Referenced by emitOMPSimdRegion().
emitRestoreIP()
template<typename T > static void emitRestoreIP (CodeGenFunction & CGF, const T * C, llvm::OpenMPIRBuilder::InsertPointTy AllocaIP, llvm::OpenMPIRBuilder & OMPBuilder) static
Definition at line 5848 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenModule::getContext(), clang::Expr::getExprLoc(), clang::ASTContext::getIntTypeForBitwidth(), clang::Expr::getType(), and clang::CodeGen::CodeGenTypeCache::Int64Ty.
emitScanBasedDirective()
static void emitScanBasedDirective (CodeGenFunction & CGF, const OMPLoopDirective & S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen, llvm::function_ref< void(CodeGenFunction &)> FirstGen, llvm::function_ref< void(CodeGenFunction &)> SecondGen) static
Emits the code for the directive with inscan reductions.
The code is the following:
#pragma omp ...
for (i: 0..<num_iters>) {
  <input phase>;
  buffer[i] = red;
}
#pragma omp master // in parallel region
for (int k = 0; k != ceil(log2(num_iters)); ++k)
for (size cnt = last_iter; cnt >= pow(2, k); --k)
  buffer[i] op= buffer[i-pow(2,k)];
#pragma omp barrier // in parallel region
#pragma omp ...
for (0..<num_iters>) {
  red = InclusiveScan ? buffer[i] : buffer[i-1];
  <scan phase>;
}
Definition at line 3660 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::ApplyDebugLocation::CreateDefaultArtificial(), clang::CodeGen::RValue::get(), clang::CodeGen::Address::invalid(), clang::isOpenMPParallelDirective(), Next, clang::CodeGen::CodeGenFunction::OMPFirstScanLoop, and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by emitWorksharingDirective().
emitScanBasedDirectiveDecls()
static void emitScanBasedDirectiveDecls (CodeGenFunction & CGF, const OMPLoopDirective & S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen) static
Emits internal temp array declarations for the directive with inscan reductions.
The code is the following:
size num_iters = <num_iters>;
<type> buffer[num_iters];
Definition at line 3543 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitSharedOrigLValue(), clang::CodeGen::CodeGenFunction::EmitVarDecl(), clang::CodeGen::RValue::get(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by emitWorksharingDirective().
emitScanBasedDirectiveFinals()
static void emitScanBasedDirectiveFinals (CodeGenFunction & CGF, const OMPLoopDirective & S, llvm::function_ref< llvm::Value *(CodeGenFunction &)> NumIteratorsGen) static
Copies final inscan reductions values to the original variables.
The code is the following:
<orig_var> = buffer[num_iters-1];
Definition at line 3595 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitOMPCopy(), clang::CodeGen::RValue::get(), clang::Expr::getType(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by emitWorksharingDirective().
emitSimdlenSafelenClause()
static void emitSimdlenSafelenClause (CodeGenFunction & CGF, const OMPExecutableDirective & D) static
Definition at line 2370 of file CGStmtOpenMP.cpp.
References clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenFunction::HaveInsertPoint(), clang::CodeGen::AggValueSlot::ignored(), clang::CodeGen::CodeGenFunction::LoopStack, clang::CodeGen::LoopInfoStack::setParallel(), and clang::CodeGen::LoopInfoStack::setVectorizeWidth().
emitSimpleAtomicLoad()
static RValue emitSimpleAtomicLoad (CodeGenFunction & CGF, llvm::AtomicOrdering AO, LValue LVal, SourceLocation Loc) static
Definition at line 6007 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::EmitAtomicLoad(), and clang::CodeGen::CodeGenFunction::EmitLoadOfLValue().
Referenced by emitOMPAtomicReadExpr().
emitSimpleAtomicStore()
static void emitSimpleAtomicStore (CodeGenFunction & CGF, llvm::AtomicOrdering AO, LValue LVal, RValue RVal) static
Definition at line 5999 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::EmitAtomicStore(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughGlobalRegLValue().
Referenced by emitOMPAtomicWriteExpr().
emitTargetParallelForRegion()
static void emitTargetParallelForRegion (CodeGenFunction & CGF, const OMPTargetParallelForDirective & S, PrePostActionTy & Action) static
Definition at line 7481 of file CGStmtOpenMP.cpp.
References emitCommonOMPParallelDirective(), emitDispatchForLoopBounds(), emitEmptyBoundParameters(), emitForLoopBounds(), clang::CodeGen::CodeGenFunction::EmitOMPWorksharingLoop(), and clang::CodeGen::PrePostActionTy::Enter().
emitTargetParallelForSimdRegion()
static void emitTargetParallelForSimdRegion (CodeGenFunction & CGF, const OMPTargetParallelForSimdDirective & S, PrePostActionTy & Action) static
Definition at line 7522 of file CGStmtOpenMP.cpp.
References emitCommonOMPParallelDirective(), emitDispatchForLoopBounds(), emitEmptyBoundParameters(), emitForLoopBounds(), clang::CodeGen::CodeGenFunction::EmitOMPWorksharingLoop(), and clang::CodeGen::PrePostActionTy::Enter().
emitTargetParallelGenericLoopRegion()
static void emitTargetParallelGenericLoopRegion (CodeGenFunction & CGF, const OMPTargetParallelGenericLoopDirective & S, PrePostActionTy & Action) static
Definition at line 7949 of file CGStmtOpenMP.cpp.
References emitCommonOMPParallelDirective(), emitDispatchForLoopBounds(), emitEmptyBoundParameters(), emitForLoopBounds(), clang::CodeGen::CodeGenFunction::EmitOMPWorksharingLoop(), and clang::CodeGen::PrePostActionTy::Enter().
emitTargetParallelRegion()
static void emitTargetParallelRegion (CodeGenFunction & CGF, const OMPTargetParallelDirective & S, PrePostActionTy & Action) static
Definition at line 7434 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPParallelDirective(), emitEmptyBoundParameters(), clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::CodeGenFunction::EmitStmt(), clang::CodeGen::PrePostActionTy::Enter(), clang::CapturedStmt::getCapturedStmt(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::isOpenMPTargetExecutionDirective().
emitTargetRegion()
static void emitTargetRegion (CodeGenFunction & CGF, const OMPTargetDirective & S, PrePostActionTy & Action) static
Definition at line 6666 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateClause(), clang::CodeGen::CodeGenFunction::EmitStmt(), clang::CodeGen::CodeGenFunction::EnsureInsertPoint(), clang::CodeGen::PrePostActionTy::Enter(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::isOpenMPTargetExecutionDirective().
emitTargetTeamsDistributeParallelForRegion()
static void emitTargetTeamsDistributeParallelForRegion (CodeGenFunction & CGF, const OMPTargetTeamsDistributeParallelForDirective & S, PrePostActionTy & Action) static
Definition at line 7027 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), emitInnerParallelForWhenCombined(), clang::CodeGen::CodeGenFunction::EmitOMPDistributeLoop(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::PrePostActionTy::Enter(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitTargetTeamsDistributeParallelForSimdRegion()
static void emitTargetTeamsDistributeParallelForSimdRegion (CodeGenFunction & CGF, const OMPTargetTeamsDistributeParallelForSimdDirective & S, PrePostActionTy & Action) static
Definition at line 7078 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), emitInnerParallelForWhenCombined(), clang::CodeGen::CodeGenFunction::EmitOMPDistributeLoop(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::PrePostActionTy::Enter(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitTargetTeamsDistributeRegion()
static void emitTargetTeamsDistributeRegion (CodeGenFunction & CGF, PrePostActionTy & Action, const OMPTargetTeamsDistributeDirective & S) static
Definition at line 6790 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), clang::CodeGen::CodeGenFunction::EmitOMPDistributeLoop(), emitOMPLoopBodyWithStopPoint(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::PrePostActionTy::Enter(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitTargetTeamsDistributeSimdRegion()
static void emitTargetTeamsDistributeSimdRegion (CodeGenFunction & CGF, PrePostActionTy & Action, const OMPTargetTeamsDistributeSimdDirective & S) static
Definition at line 6835 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), clang::CodeGen::CodeGenFunction::EmitOMPDistributeLoop(), emitOMPLoopBodyWithStopPoint(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::PrePostActionTy::Enter(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitTargetTeamsGenericLoopRegion()
static void emitTargetTeamsGenericLoopRegion (CodeGenFunction & CGF, const OMPTargetTeamsGenericLoopDirective & S, PrePostActionTy & Action) static
Definition at line 7894 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), emitInnerParallelForWhenCombined(), clang::CodeGen::CodeGenFunction::EmitOMPDistributeLoop(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::PrePostActionTy::Enter(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
emitTargetTeamsRegion()
static void emitTargetTeamsRegion (CodeGenFunction & CGF, PrePostActionTy & Action, const OMPTargetTeamsDirective & S) static
Definition at line 6745 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CodeGenFunction::CGM, emitCommonOMPTeamsDirective(), clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPPrivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseFinal(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitPostUpdateForReductionClause(), clang::CodeGen::CodeGenFunction::EmitStmt(), clang::CodeGen::PrePostActionTy::Enter(), clang::CapturedStmt::getCapturedStmt(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::isOpenMPTargetExecutionDirective().
emitWorksharingDirective()
static bool emitWorksharingDirective (CodeGenFunction & CGF, const OMPLoopDirective & S, bool HasCancel) static
Definition at line 3801 of file CGStmtOpenMP.cpp.
References clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), emitDispatchForLoopBounds(), emitForLoopBounds(), clang::CodeGen::CodeGenFunction::EmitOMPWorksharingLoop(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), emitScanBasedDirective(), emitScanBasedDirectiveDecls(), emitScanBasedDirectiveFinals(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::isOpenMPParallelDirective().
GetAlignedMapping()
static llvm::MapVector< llvm::Value *, llvm::Value * > GetAlignedMapping (const OMPSimdDirective & S, CodeGenFunction & CGF) static
Definition at line 2639 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getOpenMPDefaultSimdAlign(), clang::Type::getPointeeType(), clang::CharUnits::getQuantity(), clang::Expr::getType(), and clang::ASTContext::toCharUnitsFromBits().
getBaseDecl()
static const VarDecl * getBaseDecl (const Expr * Ref) static
Definition at line 7222 of file CGStmtOpenMP.cpp.
References clang::cast(), and clang::Expr::IgnoreParenImpCasts().
getCanonicalParamType()
static QualType getCanonicalParamType (ASTContext & C, QualType T) static
Definition at line 385 of file CGStmtOpenMP.cpp.
References clang::C, clang::Type::getAsArrayTypeUnsafe(), and getCanonicalParamType().
Referenced by emitOutlinedFunctionPrologue(), and getCanonicalParamType().
isAllocatableDecl()
static bool isAllocatableDecl (const VarDecl * VD) static
Definition at line 1583 of file CGStmtOpenMP.cpp.
References clang::Decl::getAttr(), clang::VarDecl::getCanonicalDecl(), and clang::Decl::hasAttr().
isSupportedByOpenMPIRBuilder() [1/3]
static bool isSupportedByOpenMPIRBuilder (const OMPForDirective & S) static
Definition at line 3847 of file CGStmtOpenMP.cpp.
References clang::C, clang::OMPC_SCHEDULE_MODIFIER_unknown, and clang::OMPC_SCHEDULE_unknown.
isSupportedByOpenMPIRBuilder() [2/3]
static bool isSupportedByOpenMPIRBuilder (const OMPSimdDirective & S) static
Definition at line 2607 of file CGStmtOpenMP.cpp.
References clang::C, clang::CapturedStmt::children(), and clang::Stmt::children().
isSupportedByOpenMPIRBuilder() [3/3]
bool isSupportedByOpenMPIRBuilder (const OMPTaskgroupDirective & T)
Definition at line 5305 of file CGStmtOpenMP.cpp.
mapParam()
static void mapParam (CodeGenFunction & CGF, const DeclRefExpr * Helper, const ImplicitParamDecl * PVD, CodeGenFunction::OMPPrivateScope & Privates) static
Emit a helper variable and return corresponding lvalue.
Definition at line 7561 of file CGStmtOpenMP.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), and clang::DeclRefExpr::getDecl().