clang: clang::ento::StackHintGeneratorForSymbol Class Reference
clang::ento::StackHintGeneratorForSymbol Class Reference
Constructs a Stack hint for the given symbol.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Member Functions
StackHintGeneratorForSymbol (SymbolRef S, StringRef M)
~StackHintGeneratorForSymbol () override=default
std::string getMessage (const ExplodedNode *N) override
Search the call expression for the symbol Sym and dispatch the 'getMessageForX()' methods to construct a specific message.
virtual std::string getMessageForArg (const Expr *ArgE, unsigned ArgIndex)
Produces the message of the following form: 'Msg via Nth parameter'.
virtual std::string getMessageForReturn (const CallExpr *CallExpr)
virtual std::string getMessageForSymbolNotFound ()
Public Member Functions inherited from clang::ento::StackHintGenerator
virtual ~StackHintGenerator ()=0
Detailed Description
Constructs a Stack hint for the given symbol.
The class knows how to construct the stack hint message based on traversing the CallExpr associated with the call and checking if the given symbol is returned or is one of the arguments. The hint can be customized by redefining 'getMessageForX()' methods.
Definition at line 91 of file BugReporter.h.
Constructor & Destructor Documentation
StackHintGeneratorForSymbol()
clang::ento::StackHintGeneratorForSymbol::StackHintGeneratorForSymbol (SymbolRef S, StringRef M) inline
Definition at line 97 of file BugReporter.h.
~StackHintGeneratorForSymbol()
clang::ento::StackHintGeneratorForSymbol::~StackHintGeneratorForSymbol () override default
Member Function Documentation
getMessage()
std::string StackHintGeneratorForSymbol::getMessage (const ExplodedNode * N) override virtual
Search the call expression for the symbol Sym and dispatch the 'getMessageForX()' methods to construct a specific message.
Implements clang::ento::StackHintGenerator.
Definition at line 285 of file BugReporter.cpp.
References clang::ento::SVal::getAs(), clang::ento::SVal::getAsLocSymbol(), clang::CallExitEnd::getCalleeContext(), clang::StackFrameContext::getCallSite(), getMessageForArg(), getMessageForReturn(), getMessageForSymbolNotFound(), N, and P.
getMessageForArg()
std::string StackHintGeneratorForSymbol::getMessageForArg (const Expr * ArgE, unsigned ArgIndex) virtual
Produces the message of the following form: 'Msg via Nth parameter'.
Definition at line 331 of file BugReporter.cpp.
Referenced by getMessage().
getMessageForReturn()
virtual std::string clang::ento::StackHintGeneratorForSymbol::getMessageForReturn (const CallExpr * CallExpr) inline virtual
Definition at line 108 of file BugReporter.h.
Referenced by getMessage().
getMessageForSymbolNotFound()
virtual std::string clang::ento::StackHintGeneratorForSymbol::getMessageForSymbolNotFound () inline virtual
Definition at line 112 of file BugReporter.h.
Referenced by getMessage().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
lib/StaticAnalyzer/Core/BugReporter.cpp