clang: clang::threadSafety::til::Apply Class Reference
clang::threadSafety::til::Apply Class Reference
Apply an argument to a function.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Apply (SExpr *F, SExpr *A)
Apply (const Apply &A, SExpr *F, SExpr *Ar)
SExpr * fun ()
const SExpr * fun () const
SExpr * arg ()
const SExpr * arg () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Apply *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Apply an argument to a function.
Note that this does not actually call the function. Functions are curried, so this returns a closure in which the first parameter has been applied. Once all parameters have been applied, Call can be used to invoke the function.
Definition at line 848 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Apply() [1/2]
clang::threadSafety::til::Apply::Apply (SExpr * F, SExpr * A) inline
Definition at line 850 of file ThreadSafetyTIL.h.
Apply() [2/2]
clang::threadSafety::til::Apply::Apply (const Apply & A, SExpr * F, SExpr * Ar) inline
Definition at line 851 of file ThreadSafetyTIL.h.
Member Function Documentation
arg() [1/2]
SExpr * clang::threadSafety::til::Apply::arg () inline
Definition at line 859 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply().
arg() [2/2]
const SExpr * clang::threadSafety::til::Apply::arg () const inline
Definition at line 860 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Apply::classof (const SExpr * E) inline static
Definition at line 854 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Apply::compare (const Apply * E, C & Cmp) const inline
Definition at line 870 of file ThreadSafetyTIL.h.
References arg(), and fun().
fun() [1/2]
SExpr * clang::threadSafety::til::Apply::fun () inline
Definition at line 856 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply().
fun() [2/2]
const SExpr * clang::threadSafety::til::Apply::fun () const inline
Definition at line 857 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Apply::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 863 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h