clang: clang::serialization::DeclarationNameKey Class Reference
clang::serialization::DeclarationNameKey Class Reference
AST file AST constants
A key used when looking up entities by DeclarationName.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
DeclarationNameKey ()=default
DeclarationNameKey (DeclarationName Name)
DeclarationNameKey (NameKind Kind, uint64_t Data)
NameKind getKind () const
IdentifierInfo * getIdentifier () const
Selector getSelector () const
OverloadedOperatorKind getOperatorKind () const
unsigned getHash () const
Compute a fingerprint of this key for use in on-disk hash table.
Friends
bool operator== (const DeclarationNameKey &A, const DeclarationNameKey &B)
Detailed Description
A key used when looking up entities by DeclarationName.
Different DeclarationNames are mapped to different keys, but the same key can occasionally represent multiple names (for names that contain types, in particular).
Definition at line 2120 of file ASTBitCodes.h.
Constructor & Destructor Documentation
DeclarationNameKey() [1/3]
clang::serialization::DeclarationNameKey::DeclarationNameKey () default
DeclarationNameKey() [2/3]
DeclarationNameKey::DeclarationNameKey (DeclarationName Name)
Definition at line 1081 of file ASTReader.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::Identifier, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
DeclarationNameKey() [3/3]
clang::serialization::DeclarationNameKey::DeclarationNameKey (NameKind Kind, uint64_t Data) inline
Definition at line 2129 of file ASTBitCodes.h.
References Data.
Member Function Documentation
getHash()
unsigned DeclarationNameKey::getHash () const
Compute a fingerprint of this key for use in on-disk hash table.
Definition at line 1111 of file ASTReader.cpp.
References clang::serialization::ComputeHash(), clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, Data, getName(), clang::DeclarationName::Identifier, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
Referenced by clang::serialization::reader::ASTDeclContextNameLookupTrait::ComputeHash(), and llvm::DenseMapInfo< clang::serialization::DeclarationNameKey >::getHashValue().
getIdentifier()
IdentifierInfo * clang::serialization::DeclarationNameKey::getIdentifier () const inline
Definition at line 2133 of file ASTBitCodes.h.
References clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXLiteralOperatorName, Data, and clang::DeclarationName::Identifier.
getKind()
NameKind clang::serialization::DeclarationNameKey::getKind () const inline
Definition at line 2131 of file ASTBitCodes.h.
getOperatorKind()
OverloadedOperatorKind clang::serialization::DeclarationNameKey::getOperatorKind () const inline
Definition at line 2147 of file ASTBitCodes.h.
References clang::DeclarationName::CXXOperatorName, and Data.
getSelector()
Selector clang::serialization::DeclarationNameKey::getSelector () const inline
Definition at line 2140 of file ASTBitCodes.h.
References Data, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
Friends And Related Symbol Documentation
operator==
bool operator== (const DeclarationNameKey & A, const DeclarationNameKey & B) friend
Definition at line 2155 of file ASTBitCodes.h.
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTBitCodes.h
lib/Serialization/ASTReader.cpp