clang: DerefSimplePtrArithFixableGadget Class Reference
DerefSimplePtrArithFixableGadget Class Reference
Public Member Functions
DerefSimplePtrArithFixableGadget (const MatchFinder::MatchResult &Result)
virtual std::optional< FixItList > getFixits (const Strategy &s) const final
virtual const Stmt * getBaseStmt () const final
virtual DeclUseList getClaimedVarUseSites () const final
Static Public Member Functions
static Matcher matcher ()
Detailed Description
Definition at line 950 of file UnsafeBufferUsage.cpp.
Constructor & Destructor Documentation
DerefSimplePtrArithFixableGadget()
DerefSimplePtrArithFixableGadget::DerefSimplePtrArithFixableGadget (const MatchFinder::MatchResult & Result) inline
Definition at line 962 of file UnsafeBufferUsage.cpp.
References Offset.
Member Function Documentation
getBaseStmt()
virtual const Stmt * DerefSimplePtrArithFixableGadget::getBaseStmt () const inline final virtual
Definition at line 991 of file UnsafeBufferUsage.cpp.
getClaimedVarUseSites()
virtual DeclUseList DerefSimplePtrArithFixableGadget::getClaimedVarUseSites () const inline final virtual
Definition at line 993 of file UnsafeBufferUsage.cpp.
getFixits()
std::optional< FixItList > DerefSimplePtrArithFixableGadget::getFixits (const Strategy & s) const final virtual
Definition at line 1434 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::CreateRemoval(), clang::FixItHint::CreateReplacement(), clang::Decl::getASTContext(), clang::Stmt::getBeginLoc(), clang::CharSourceRange::getCharRange(), clang::DeclRefExpr::getDecl(), clang::ASTContext::getLangOpts(), getPastLoc(), clang::ASTContext::getSourceManager(), Offset, s, and SM.
matcher()
static Matcher DerefSimplePtrArithFixableGadget::matcher () inline static
Definition at line 970 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::anyOf, clang::ast_matchers::binaryOperator, clang::ast_matchers::declRefExpr, clang::ast_matchers::expr, clang::ast_matchers::hasPointerType(), clang::ast_matchers::integerLiteral, clang::ast_matchers::isInUnspecifiedLvalueContext(), clang::ast_matchers::unaryOperator, and clang::ast_matchers::varDecl.
The documentation for this class was generated from the following file:
lib/Analysis/UnsafeBufferUsage.cpp