clang: clang::tooling::ClangTool Class Reference
clang::tooling::ClangTool Class Reference
Utility to run a FrontendAction over a set of files.
#include "clang/Tooling/Tooling.h"
Public Member Functions
ClangTool (const CompilationDatabase &Compilations, ArrayRef< std::string > SourcePaths, std::shared_ptr< PCHContainerOperations > PCHContainerOps=std::make_shared< PCHContainerOperations >(), IntrusiveRefCntPtr< llvm::vfs::FileSystem > BaseFS=llvm::vfs::getRealFileSystem(), IntrusiveRefCntPtr< FileManager > Files=nullptr)
Constructs a clang tool to run over a list of files.
~ClangTool ()
void setDiagnosticConsumer (DiagnosticConsumer *DiagConsumer)
Set a DiagnosticConsumer to use during parsing.
void mapVirtualFile (StringRef FilePath, StringRef Content)
Map a virtual file to be used while running the tool.
void appendArgumentsAdjuster (ArgumentsAdjuster Adjuster)
Append a command line arguments adjuster to the adjuster chain.
void clearArgumentsAdjusters ()
Clear the command line arguments adjuster chain.
int run (ToolAction *Action)
Runs an action over all files specified in the command line.
int buildASTs (std::vector< std::unique_ptr< ASTUnit > > &ASTs)
Create an AST for each file specified in the command line and append them to ASTs.
void setPrintErrorMessage (bool PrintErrorMessage)
Sets whether an error message should be printed out if an action fails.
FileManager & getFiles ()
Returns the file manager used in the tool.
llvm::ArrayRef< std::string > getSourcePaths () const
Detailed Description
Utility to run a FrontendAction over a set of files.
This class is written to be usable for command line utilities. By default the class uses ClangSyntaxOnlyAdjuster to modify command line arguments before the arguments are used to run a frontend action. One could install an additional command line arguments adjuster by calling the appendArgumentsAdjuster() method.
Definition at line 308 of file Tooling.h.
Constructor & Destructor Documentation
ClangTool()
ClangTool::ClangTool (const CompilationDatabase & Compilations, ArrayRef< std::string > SourcePaths, std::shared_ptr< PCHContainerOperations > PCHContainerOps = std::make_shared<PCHContainerOperations>(), IntrusiveRefCntPtr< llvm::vfs::FileSystem > BaseFS = llvm::vfs::getRealFileSystem(), IntrusiveRefCntPtr< FileManager > Files = nullptr)
Constructs a clang tool to run over a list of files.
Parameters
Compilations The CompilationDatabase which contains the compile command lines for the given source paths.
SourcePaths The source files to run over. If a source files is not found in Compilations, it is skipped.
PCHContainerOps The PCHContainerOperations for loading and creating clang modules.
BaseFS VFS used for all underlying file accesses when running the tool.
Files The file manager to use for underlying file operations when running the tool.
Definition at line 466 of file Tooling.cpp.
References appendArgumentsAdjuster(), clang::tooling::getClangStripDependencyFileAdjuster(), clang::tooling::getClangStripOutputAdjuster(), and clang::tooling::getClangSyntaxOnlyAdjuster().
~ClangTool()
ClangTool::~ClangTool () default
Member Function Documentation
appendArgumentsAdjuster()
void ClangTool::appendArgumentsAdjuster (ArgumentsAdjuster Adjuster)
Append a command line arguments adjuster to the adjuster chain.
Parameters
Adjuster An argument adjuster, which will be run on the output of previous argument adjusters.
Definition at line 491 of file Tooling.cpp.
References clang::tooling::combineAdjusters().
Referenced by ClangTool(), clang::tooling::AllTUsToolExecutor::execute(), and clang::tooling::StandaloneToolExecutor::execute().
buildASTs()
int ClangTool::buildASTs (std::vector< std::unique_ptr< ASTUnit > > & ASTs)
Create an AST for each file specified in the command line and append them to ASTs.
Definition at line 658 of file Tooling.cpp.
References run().
clearArgumentsAdjusters()
void ClangTool::clearArgumentsAdjusters ()
Clear the command line arguments adjuster chain.
Definition at line 495 of file Tooling.cpp.
Referenced by clang::tooling::StandaloneToolExecutor::StandaloneToolExecutor(), and clang::tooling::StandaloneToolExecutor::StandaloneToolExecutor().
getFiles()
FileManager & clang::tooling::ClangTool::getFiles () inline
Returns the file manager used in the tool.
The file manager is shared between all translation units.
Definition at line 371 of file Tooling.h.
Referenced by clang::tooling::StandaloneToolExecutor::getFiles(), and clang::tooling::RefactoringTool::runAndSave().
getSourcePaths()
llvm::ArrayRef< std::string > clang::tooling::ClangTool::getSourcePaths () const inline
Definition at line 373 of file Tooling.h.
Referenced by clang::tooling::StandaloneToolExecutor::getSourcePaths().
mapVirtualFile()
void ClangTool::mapVirtualFile (StringRef FilePath, StringRef Content)
Map a virtual file to be used while running the tool.
Parameters
FilePath The path at which the content will be mapped.
Content A null terminated buffer of the file's content.
Definition at line 487 of file Tooling.cpp.
Referenced by clang::tooling::StandaloneToolExecutor::mapVirtualFile().
run()
int ClangTool::run (ToolAction * Action)
Runs an action over all files specified in the command line.
Parameters
Action Tool action.
Returns
0 on success; 1 if any error occurred; 2 if there is no error but some files are skipped due to missing compile commands.
Definition at line 512 of file Tooling.cpp.
References clang::tooling::CompileCommand::CommandLine, clang::tooling::CompileCommand::Directory, clang::File, clang::tooling::CompileCommand::Filename, clang::tooling::getAbsolutePath(), clang::tooling::CompilationDatabase::getCompileCommands(), and injectResourceDir().
Referenced by buildASTs(), clang::tooling::StandaloneToolExecutor::execute(), and clang::tooling::RefactoringTool::runAndSave().
setDiagnosticConsumer()
void clang::tooling::ClangTool::setDiagnosticConsumer (DiagnosticConsumer * DiagConsumer) inline
Set a DiagnosticConsumer to use during parsing.
Definition at line 333 of file Tooling.h.
Referenced by clang::tooling::StandaloneToolExecutor::setDiagnosticConsumer().
setPrintErrorMessage()
void ClangTool::setPrintErrorMessage (bool PrintErrorMessage)
Sets whether an error message should be printed out if an action fails.
By default, if an action fails, a message is printed out to stderr.
Definition at line 663 of file Tooling.cpp.
The documentation for this class was generated from the following files:
include/clang/Tooling/Tooling.h
lib/Tooling/Tooling.cpp