clang: clang::format::UnwrappedLineFormatter Class Reference
clang::format::UnwrappedLineFormatter Class Reference
#include "/root/llvm-project/clang/lib/Format/UnwrappedLineFormatter.h"
Public Member Functions
UnwrappedLineFormatter (ContinuationIndenter *Indenter, WhitespaceManager *Whitespaces, const FormatStyle &Style, const AdditionalKeywords &Keywords, const SourceManager &SourceMgr, FormattingAttemptStatus *Status)
unsigned format (const SmallVectorImpl< AnnotatedLine * > &Lines, bool DryRun=false, int AdditionalIndent=0, bool FixBadIndentation=false, unsigned FirstStartColumn=0, unsigned NextStartColumn=0, unsigned LastStartColumn=0)
Format the current block and return the penalty.
Detailed Description
Definition at line 28 of file UnwrappedLineFormatter.h.
Constructor & Destructor Documentation
UnwrappedLineFormatter()
clang::format::UnwrappedLineFormatter::UnwrappedLineFormatter (ContinuationIndenter * Indenter, WhitespaceManager * Whitespaces, const FormatStyle & Style, const AdditionalKeywords & Keywords, const SourceManager & SourceMgr, FormattingAttemptStatus * Status) inline
Definition at line 30 of file UnwrappedLineFormatter.h.
References Indenter.
Member Function Documentation
format()
unsigned clang::format::UnwrappedLineFormatter::format (const SmallVectorImpl< AnnotatedLine * > & Lines, bool DryRun = false, int AdditionalIndent = 0, bool FixBadIndentation = false, unsigned FirstStartColumn = 0, unsigned NextStartColumn = 0, unsigned LastStartColumn = 0)
Format the current block and return the penalty.
Definition at line 1305 of file UnwrappedLineFormatter.cpp.
References clang::format::AnnotatedLine::Affected, clang::format::AnnotatedLine::ChildrenAffected, clang::format::AnnotatedLine::ContainsMacroCall, clang::format::AnnotatedLine::First, format(), clang::Token::getLocation(), Indenter, clang::format::AnnotatedLine::InPPDirective, clang::format::FormatToken::is(), clang::format::FormatToken::IsFirst, clang::format::AnnotatedLine::Last, clang::format::AnnotatedLine::LeadingEmptyLinesAffected, clang::format::AnnotatedLine::Level, clang::format::LT_ImportStatement, clang::format::LT_Invalid, clang::format::FormatToken::NewlinesBefore, clang::format::FormatToken::Next, clang::format::FormatToken::OriginalColumn, clang::format::AnnotatedLine::startsWith(), clang::format::FormatToken::Tok, Tok, clang::format::FormatToken::TotalLength, clang::format::AnnotatedLine::Type, and UINT_MAX.
Referenced by format().
The documentation for this class was generated from the following files:
lib/Format/UnwrappedLineFormatter.h
lib/Format/UnwrappedLineFormatter.cpp