clang: clang::OverloadedTemplateStorage Class Reference
clang::OverloadedTemplateStorage Class Reference
A structure for storing the information associated with an overloaded template name.
#include "clang/AST/TemplateName.h"
Public Types
using iterator = NamedDecl *const *
Public Member Functions
unsigned size () const
iterator begin () const
iterator end () const
llvm::ArrayRef< NamedDecl * > decls () const
Public Member Functions inherited from clang::UncommonTemplateNameStorage
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Friends
class ASTContext
Additional Inherited Members
Public Attributes inherited from clang::UncommonTemplateNameStorage
Protected Types inherited from clang::UncommonTemplateNameStorage
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions inherited from clang::UncommonTemplateNameStorage
UncommonTemplateNameStorage (Kind Kind, unsigned Index, unsigned Data)
Protected Attributes inherited from clang::UncommonTemplateNameStorage
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
A structure for storing the information associated with an overloaded template name.
Definition at line 108 of file TemplateName.h.
Member Typedef Documentation
iterator
using clang::OverloadedTemplateStorage::iterator = NamedDecl *const *
Definition at line 124 of file TemplateName.h.
Member Function Documentation
begin()
iterator clang::OverloadedTemplateStorage::begin () const inline
Definition at line 126 of file TemplateName.h.
References getStorage().
Referenced by decls(), clang::ASTContext::getNameForTemplate(), IsStructurallyEquivalent(), and clang::TemplateName::print().
decls()
llvm::ArrayRef< NamedDecl * > clang::OverloadedTemplateStorage::decls () const inline
Definition at line 129 of file TemplateName.h.
References begin(), and end().
end()
iterator clang::OverloadedTemplateStorage::end () const inline
Definition at line 127 of file TemplateName.h.
References getStorage().
Referenced by decls(), and IsStructurallyEquivalent().
size()
unsigned clang::OverloadedTemplateStorage::size () const inline
Definition at line 122 of file TemplateName.h.
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 109 of file TemplateName.h.
The documentation for this class was generated from the following file:
include/clang/AST/TemplateName.h