clang: clang::interp::Program Class Reference
clang::interp::Program Class Reference final
The program contains and links the bytecode for all functions.
#include "/root/llvm-project/clang/lib/AST/Interp/Program.h"
Classes
class DeclScope
Context to manage declaration lifetimes.
Public Member Functions
Program (Context &Ctx)
~Program ()
unsigned getOrCreateNativePointer (const void *Ptr)
Marshals a native pointer to an ID for embedding in bytecode.
const void * getNativePointer (unsigned Idx)
Returns the value of a marshalled native pointer.
unsigned createGlobalString (const StringLiteral *S)
Emits a string literal among global data.
Pointer getPtrGlobal (unsigned Idx)
Returns a pointer to a global.
Block * getGlobal (unsigned Idx)
Returns the value of a global.
std::optional< unsigned > getGlobal (const ValueDecl *VD)
Finds a global's index.
std::optional< unsigned > getOrCreateGlobal (const ValueDecl *VD, const Expr *Init=nullptr)
Returns or creates a global an creates an index to it.
std::optional< unsigned > getOrCreateDummy (const ParmVarDecl *PD)
Returns or creates a dummy value for parameters.
std::optional< unsigned > createGlobal (const ValueDecl *VD, const Expr *E)
Creates a global and returns its index.
std::optional< unsigned > createGlobal (const Expr *E)
Creates a global from a lifetime-extended temporary.
template<typename... Ts>
Function * createFunction (const FunctionDecl *Def, Ts &&... Args)
Creates a new function from a code range.
template<typename... Ts>
Function * createFunction (Ts &&... Args)
Creates an anonymous function.
Function * getFunction (const FunctionDecl *F)
Returns a function.
Record * getOrCreateRecord (const RecordDecl *RD)
Returns a record or creates one if it does not exist.
Descriptor * createDescriptor (const DeclTy &D, PrimType Type, Descriptor::MetadataSize MDSize=std::nullopt, bool IsConst=false, bool IsTemporary=false, bool IsMutable=false)
Creates a descriptor for a primitive type.
Descriptor * createDescriptor (const DeclTy &D, const Type *Ty, Descriptor::MetadataSize MDSize=std::nullopt, bool IsConst=false, bool IsTemporary=false, bool IsMutable=false, const Expr *Init=nullptr)
Creates a descriptor for a composite type.
std::optional< unsigned > getCurrentDecl () const
Returns the current declaration ID.
void dump () const
Dumps the disassembled bytecode to llvm::errs().
void dump (llvm::raw_ostream &OS) const
Friends
class DeclScope
Detailed Description
The program contains and links the bytecode for all functions.
Definition at line 40 of file Program.h.
Constructor & Destructor Documentation
Program()
clang::interp::Program::Program (Context & Ctx) inline
Definition at line 42 of file Program.h.
~Program()
clang::interp::Program::~Program () inline
Definition at line 44 of file Program.h.
Member Function Documentation
createDescriptor() [1/2]
Descriptor * Program::createDescriptor (const DeclTy & D, const Type * Ty, Descriptor::MetadataSize MDSize = std::nullopt, bool IsConst = false, bool IsTemporary = false, bool IsMutable = false, const Expr * Init = nullptr)
Creates a descriptor for a composite type.
Definition at line 310 of file Program.cpp.
References clang::interp::Context::classify(), createDescriptor(), clang::interp::Descriptor::getAllocSize(), clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), getOrCreateRecord(), clang::QualType::getTypePtr(), and clang::interp::primSize().
createDescriptor() [2/2]
Descriptor * clang::interp::Program::createDescriptor (const DeclTy & D, PrimType Type, Descriptor::MetadataSize MDSize = std::nullopt, bool IsConst = false, bool IsTemporary = false, bool IsMutable = false) inline
Creates a descriptor for a primitive type.
Definition at line 117 of file Program.h.
Referenced by clang::interp::ByteCodeEmitter::compileFunc(), createDescriptor(), and getOrCreateRecord().
createFunction() [1/2]
template<typename... Ts> Function * clang::interp::Program::createFunction (const FunctionDecl * Def, Ts &&... Args) inline
Creates a new function from a code range.
Definition at line 96 of file Program.h.
References clang::FunctionDecl::getCanonicalDecl().
Referenced by clang::interp::ByteCodeEmitter::compileFunc().
createFunction() [2/2]
template<typename... Ts> Function * clang::interp::Program::createFunction (Ts &&... Args) inline
Creates an anonymous function.
Definition at line 104 of file Program.h.
createGlobal() [1/2]
std::optional< unsigned > Program::createGlobal (const Expr * E)
Creates a global from a lifetime-extended temporary.
Definition at line 179 of file Program.cpp.
References createGlobal(), and clang::Expr::getType().
createGlobal() [2/2]
std::optional< unsigned > Program::createGlobal (const ValueDecl * VD, const Expr * E)
Creates a global and returns its index.
Definition at line 160 of file Program.cpp.
References createGlobal(), getGlobal(), clang::ValueDecl::getType(), IsStatic, P, and clang::interp::Context::shouldBeGloballyIndexed().
Referenced by createGlobal(), createGlobal(), getOrCreateDummy(), and getOrCreateGlobal().
createGlobalString()
unsigned Program::createGlobalString (const StringLiteral * S)
Emits a string literal among global data.
Definition at line 37 of file Program.cpp.
References clang::interp::Pointer::atIndex(), clang::interp::Descriptor::getAllocSize(), clang::interp::Context::getCharBit(), N, clang::interp::Pointer::narrow(), clang::interp::PT_Sint8, clang::interp::PT_Uint16, and clang::interp::PT_Uint32.
dump() [1/2]
LLVM_DUMP_METHOD void Program::dump () const
Dumps the disassembled bytecode to llvm::errs().
Definition at line 62 of file Disasm.cpp.
References dump().
dump() [2/2]
LLVM_DUMP_METHOD void Program::dump (llvm::raw_ostream & OS) const
Definition at line 64 of file Disasm.cpp.
getCurrentDecl()
std::optional< unsigned > clang::interp::Program::getCurrentDecl () const inline
Returns the current declaration ID.
Definition at line 144 of file Program.h.
getFunction()
Function * Program::getFunction (const FunctionDecl * F)
Returns a function.
Definition at line 211 of file Program.cpp.
References clang::FunctionDecl::getCanonicalDecl().
Referenced by clang::interp::ByteCodeEmitter::compileFunc().
getGlobal() [1/2]
std::optional< unsigned > Program::getGlobal (const ValueDecl * VD)
Finds a global's index.
Definition at line 105 of file Program.cpp.
References P.
getGlobal() [2/2]
Block * clang::interp::Program::getGlobal (unsigned Idx) inline
Returns the value of a global.
Definition at line 73 of file Program.h.
Referenced by createGlobal(), and getOrCreateGlobal().
getNativePointer()
const void * Program::getNativePointer (unsigned Idx)
Returns the value of a marshalled native pointer.
Definition at line 33 of file Program.cpp.
getOrCreateDummy()
std::optional< unsigned > Program::getOrCreateDummy (const ParmVarDecl * PD)
Returns or creates a dummy value for parameters.
Definition at line 141 of file Program.cpp.
References clang::Type::castAs(), createGlobal(), clang::interp::Context::getASTContext(), clang::ValueDecl::getType(), and clang::ArrayType::Normal.
getOrCreateGlobal()
std::optional< unsigned > Program::getOrCreateGlobal (const ValueDecl * VD, const Expr * Init = nullptr)
Returns or creates a global an creates an index to it.
Definition at line 129 of file Program.cpp.
References createGlobal(), and getGlobal().
getOrCreateNativePointer()
unsigned Program::getOrCreateNativePointer (const void * Ptr)
Marshals a native pointer to an ID for embedding in bytecode.
Definition at line 22 of file Program.cpp.
getOrCreateRecord()
Record * Program::getOrCreateRecord (const RecordDecl * RD)
Returns a record or creates one if it does not exist.
Definition at line 218 of file Program.cpp.
References clang::interp::align(), clang::interp::Context::classify(), createDescriptor(), clang::RecordDecl::fields(), clang::interp::Descriptor::getAllocSize(), clang::RecordDecl::getDefinition(), getOrCreateRecord(), clang::interp::Record::getSize(), clang::QualType::getTypePtr(), and clang::QualType::isConstQualified().
Referenced by clang::interp::ByteCodeEmitter::compileFunc(), createDescriptor(), and getOrCreateRecord().
getPtrGlobal()
Pointer Program::getPtrGlobal (unsigned Idx)
Returns a pointer to a global.
Definition at line 100 of file Program.cpp.
References Pointer.
Friends And Related Symbol Documentation
DeclScope
friend class DeclScope friend
Definition at line 151 of file Program.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/Program.h
lib/AST/Interp/Disasm.cpp
lib/AST/Interp/Program.cpp