clang: clang::OMPXDynCGroupMemClause Class Reference
clang::OMPXDynCGroupMemClause Class Reference
This represents 'ompx_dyn_cgroup_mem' clause in the '#pragma omp target ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPXDynCGroupMemClause (Expr *Size, Stmt *HelperSize, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'ompx_dyn_cgroup_mem' clause.
OMPXDynCGroupMemClause ()
Build an empty clause.
Expr * getSize ()
Return the size expression.
Expr * getSize () const
Return the size expression.
Public Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >
OMPOneStmtClause (Stmt *S, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPOneStmtClause ()
T * getStmtAs () const
Return the associated statement, potentially casted to T.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >
using child_iterator
using const_child_iterator
using child_range
using const_child_range
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Static Public Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Protected Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >
void setStmt (Stmt *S)
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'ompx_dyn_cgroup_mem' clause in the '#pragma omp target ...' directive.
#pragma omp target [...] ompx_dyn_cgroup_mem(N)
Definition at line 9013 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPXDynCGroupMemClause() [1/2]
clang::OMPXDynCGroupMemClause::OMPXDynCGroupMemClause (Expr * Size, Stmt * HelperSize, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build 'ompx_dyn_cgroup_mem' clause.
Parameters
Size Size expression.
HelperSize Helper Size expression
CaptureRegion Innermost OpenMP region where expressions in this
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 9030 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPXDynCGroupMemClause() [2/2]
clang::OMPXDynCGroupMemClause::OMPXDynCGroupMemClause () inline
Build an empty clause.
Definition at line 9040 of file OpenMPClause.h.
Member Function Documentation
getSize() [1/2]
Expr * clang::OMPXDynCGroupMemClause::getSize () inline
Return the size expression.
Definition at line 9043 of file OpenMPClause.h.
References clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >::getStmtAs().
getSize() [2/2]
Expr * clang::OMPXDynCGroupMemClause::getSize () const inline
Return the size expression.
Definition at line 9046 of file OpenMPClause.h.
References clang::OMPOneStmtClause< llvm::omp::OMPC_ompx_dyn_cgroup_mem, OMPClause >::getStmtAs().
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 9016 of file OpenMPClause.h.
The documentation for this class was generated from the following file:
include/clang/AST/OpenMPClause.h