clang: clang::driver::SanitizerArgs Class Reference
clang::driver::SanitizerArgs Class Reference
#include "clang/Driver/SanitizerArgs.h"
Public Member Functions
SanitizerArgs (const ToolChain &TC, const llvm::opt::ArgList &Args, bool DiagnoseErrors=true)
Parses the sanitizer arguments from an argument list.
bool needsSharedRt () const
bool needsMemProfRt () const
bool needsAsanRt () const
bool needsHwasanRt () const
bool needsHwasanAliasesRt () const
bool needsTsanRt () const
bool needsMsanRt () const
bool needsFuzzer () const
bool needsLsanRt () const
bool needsFuzzerInterceptors () const
bool needsUbsanRt () const
bool requiresMinimalRuntime () const
bool needsDfsanRt () const
bool needsSafeStackRt () const
bool needsCfiRt () const
bool needsCfiDiagRt () const
bool needsStatsRt () const
bool needsScudoRt () const
bool hasMemTag () const
bool hasMemtagHeap () const
bool hasMemtagStack () const
bool hasMemtagGlobals () const
const std::string & getMemtagMode () const
bool hasShadowCallStack () const
bool requiresPIE () const
bool needsUnwindTables () const
bool needsLTO () const
bool linkRuntimes () const
bool linkCXXRuntimes () const
bool hasCrossDsoCfi () const
bool hasAnySanitizer () const
void addArgs (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, types::ID InputType) const
Detailed Description
Definition at line 24 of file SanitizerArgs.h.
Constructor & Destructor Documentation
SanitizerArgs()
SanitizerArgs::SanitizerArgs (const ToolChain & TC, const llvm::opt::ArgList & Args, bool DiagnoseErrors = true)
Parses the sanitizer arguments from an argument list.
Definition at line 318 of file SanitizerArgs.cpp.
References addDefaultIgnorelists(), AlwaysRecoverable, clang::AsanDetectStackUseAfterReturnModeFromString(), clang::AsanDtorKindFromString(), clang::driver::Driver::CCCIsCXX(), CompatibleWithMinimalRuntime, Coverage8bitCounters, CoverageBB, CoverageControlFlow, CoverageEdge, CoverageFunc, CoverageIndirCall, CoverageInline8bitCounters, CoverageInlineBoolFlag, CoveragePCTable, CoverageStackDepth, CoverageTraceBB, CoverageTraceCmp, CoverageTraceLoads, CoverageTracePC, CoverageTracePCGuard, CoverageTraceStores, clang::Default, describeSanitizeArg(), clang::driver::Driver::Diag(), clang::expandSanitizerGroups(), clang::driver::ToolChain::getDefaultSanitizers(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getRTTIArg(), clang::driver::ToolChain::getRTTIMode(), clang::driver::ToolChain::getSupportedSanitizers(), clang::driver::ToolChain::getTriple(), isExecuteOnlyTarget(), clang::driver::Driver::isUsingLTO(), lastArgumentForMask(), clang::SanitizerSet::Mask, NeedsLTO, NeedsUbsanCxxRt, NotAllowedWithExecuteOnly, NotAllowedWithMinimalRuntime, NotAllowedWithTrap, parseArgValues(), parseBinaryMetadataFeatures(), parseCoverageFeatures(), parseSanitizeTrapArgs(), parseSpecialCaseListArg(), RecoverableByDefault, clang::driver::ToolChain::RM_Disabled, setGroupBits(), SupportsCoverage, toString(), and Unrecoverable.
Member Function Documentation
addArgs()
void SanitizerArgs::addArgs (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, types::ID InputType) const
Definition at line 1124 of file SanitizerArgs.cpp.
References addIncludeLinkerOption(), addSpecialCaseListOpt(), clang::AsanDetectStackUseAfterReturnModeToString(), clang::AsanDtorKindToString(), BinaryMetadataAtomics, BinaryMetadataCovered, BinaryMetadataUAR, CFIClasses, Coverage8bitCounters, CoverageBB, CoverageControlFlow, CoverageEdge, CoverageFunc, CoverageIndirCall, CoverageInline8bitCounters, CoverageInlineBoolFlag, CoverageNoPrune, CoveragePCTable, CoverageStackDepth, CoverageTraceBB, CoverageTraceCmp, CoverageTraceDiv, CoverageTraceGep, CoverageTraceLoads, CoverageTracePC, CoverageTracePCGuard, CoverageTraceStores, clang::driver::Driver::Diag(), clang::SanitizerSet::empty(), clang::driver::ToolChain::getCompilerRTBasename(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getTriple(), clang::SanitizerSet::has(), clang::SanitizerSet::hasOneOf(), hasTargetFeatureMTE(), clang::driver::types::isCXX(), lastArgumentForMask(), clang::SanitizerSet::Mask, needsStatsRt(), needsUbsanRt(), and toString().
getMemtagMode()
const std::string & clang::driver::SanitizerArgs::getMemtagMode () const inline
Definition at line 118 of file SanitizerArgs.h.
hasAnySanitizer()
bool clang::driver::SanitizerArgs::hasAnySanitizer () const inline
Definition at line 133 of file SanitizerArgs.h.
References clang::SanitizerSet::empty().
Referenced by clang::driver::toolchains::NetBSD::addClangTargetOptions().
hasCrossDsoCfi()
bool clang::driver::SanitizerArgs::hasCrossDsoCfi () const inline
Definition at line 132 of file SanitizerArgs.h.
hasMemTag()
bool clang::driver::SanitizerArgs::hasMemTag () const inline
Definition at line 106 of file SanitizerArgs.h.
References hasMemtagGlobals(), hasMemtagHeap(), and hasMemtagStack().
hasMemtagGlobals()
bool clang::driver::SanitizerArgs::hasMemtagGlobals () const inline
Definition at line 115 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by hasMemTag().
hasMemtagHeap()
bool clang::driver::SanitizerArgs::hasMemtagHeap () const inline
Definition at line 109 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by hasMemTag().
hasMemtagStack()
bool clang::driver::SanitizerArgs::hasMemtagStack () const inline
Definition at line 112 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by hasMemTag().
hasShadowCallStack()
bool clang::driver::SanitizerArgs::hasShadowCallStack () const inline
Definition at line 123 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
linkCXXRuntimes()
bool clang::driver::SanitizerArgs::linkCXXRuntimes () const inline
Definition at line 131 of file SanitizerArgs.h.
Referenced by collectSanitizerRuntimes().
linkRuntimes()
bool clang::driver::SanitizerArgs::linkRuntimes () const inline
Definition at line 130 of file SanitizerArgs.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), and collectSanitizerRuntimes().
needsAsanRt()
bool clang::driver::SanitizerArgs::needsAsanRt () const inline
Definition at line 81 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::toolchains::PS4CPU::addSanitizerArgs(), clang::driver::toolchains::PS5CPU::addSanitizerArgs(), collectSanitizerRuntimes(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), needsFuzzerInterceptors(), and needsUbsanRt().
needsCfiDiagRt()
bool SanitizerArgs::needsCfiDiagRt () const
Definition at line 301 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask.
Referenced by collectSanitizerRuntimes(), and needsUbsanRt().
needsCfiRt()
bool SanitizerArgs::needsCfiRt () const
Definition at line 296 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask.
Referenced by collectSanitizerRuntimes().
needsDfsanRt()
bool clang::driver::SanitizerArgs::needsDfsanRt () const inline
Definition at line 99 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by collectSanitizerRuntimes(), and needsUbsanRt().
needsFuzzer()
bool clang::driver::SanitizerArgs::needsFuzzer () const inline
Definition at line 90 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), and needsFuzzerInterceptors().
needsFuzzerInterceptors()
bool SanitizerArgs::needsFuzzerInterceptors () const
Definition at line 281 of file SanitizerArgs.cpp.
References needsAsanRt(), needsFuzzer(), needsMsanRt(), and needsTsanRt().
needsHwasanAliasesRt()
bool clang::driver::SanitizerArgs::needsHwasanAliasesRt () const inline
Definition at line 85 of file SanitizerArgs.h.
References needsHwasanRt().
Referenced by collectSanitizerRuntimes().
needsHwasanRt()
bool clang::driver::SanitizerArgs::needsHwasanRt () const inline
Definition at line 82 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by collectSanitizerRuntimes(), clang::driver::tools::fuchsia::Linker::ConstructJob(), needsHwasanAliasesRt(), and needsUbsanRt().
needsLsanRt()
bool clang::driver::SanitizerArgs::needsLsanRt () const inline
Definition at line 91 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), collectSanitizerRuntimes(), and needsUbsanRt().
needsLTO()
bool SanitizerArgs::needsLTO () const
Definition at line 314 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask, and NeedsLTO.
needsMemProfRt()
bool clang::driver::SanitizerArgs::needsMemProfRt () const inline
Definition at line 80 of file SanitizerArgs.h.
Referenced by collectSanitizerRuntimes().
needsMsanRt()
bool clang::driver::SanitizerArgs::needsMsanRt () const inline
Definition at line 89 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by collectSanitizerRuntimes(), needsFuzzerInterceptors(), and needsUbsanRt().
needsSafeStackRt()
bool clang::driver::SanitizerArgs::needsSafeStackRt () const inline
Definition at line 100 of file SanitizerArgs.h.
Referenced by collectSanitizerRuntimes().
needsScudoRt()
bool clang::driver::SanitizerArgs::needsScudoRt () const inline
Definition at line 104 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by collectSanitizerRuntimes(), and needsUbsanRt().
needsSharedRt()
bool clang::driver::SanitizerArgs::needsSharedRt () const inline
Definition at line 78 of file SanitizerArgs.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), collectSanitizerRuntimes(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
needsStatsRt()
bool clang::driver::SanitizerArgs::needsStatsRt () const inline
Definition at line 103 of file SanitizerArgs.h.
Referenced by addArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), collectSanitizerRuntimes(), and clang::driver::tools::solaris::Linker::ConstructJob().
needsTsanRt()
bool clang::driver::SanitizerArgs::needsTsanRt () const inline
Definition at line 88 of file SanitizerArgs.h.
References clang::SanitizerSet::has().
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), addPGOAndCoverageFlags(), clang::driver::toolchains::PS5CPU::addSanitizerArgs(), collectSanitizerRuntimes(), clang::driver::tools::fuchsia::Linker::ConstructJob(), needsFuzzerInterceptors(), and needsUbsanRt().
needsUbsanRt()
bool SanitizerArgs::needsUbsanRt () const
Definition at line 285 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask, needsAsanRt(), needsCfiDiagRt(), needsDfsanRt(), needsHwasanRt(), needsLsanRt(), needsMsanRt(), needsScudoRt(), needsTsanRt(), NeedsUbsanRt, and requiresMinimalRuntime().
Referenced by addArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::toolchains::PS4CPU::addSanitizerArgs(), clang::driver::toolchains::PS5CPU::addSanitizerArgs(), collectSanitizerRuntimes(), and clang::driver::tools::solaris::Linker::ConstructJob().
needsUnwindTables()
bool SanitizerArgs::needsUnwindTables () const
Definition at line 310 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask, and NeedsUnwindTables.
requiresMinimalRuntime()
bool clang::driver::SanitizerArgs::requiresMinimalRuntime () const inline
Definition at line 98 of file SanitizerArgs.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), collectSanitizerRuntimes(), clang::driver::tools::solaris::Linker::ConstructJob(), and needsUbsanRt().
requiresPIE()
bool SanitizerArgs::requiresPIE () const
Definition at line 306 of file SanitizerArgs.cpp.
References clang::SanitizerSet::Mask, and RequiresPIE.
Referenced by clang::driver::toolchains::FreeBSD::isPIEDefault(), and clang::driver::toolchains::Linux::isPIEDefault().
The documentation for this class was generated from the following files:
include/clang/Driver/SanitizerArgs.h
lib/Driver/SanitizerArgs.cpp