clang: clang::ArrayTypeLoc Class Reference
clang::ArrayTypeLoc Class Reference
Wrapper for source info for arrays.
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getLBracketLoc () const
void setLBracketLoc (SourceLocation Loc)
SourceLocation getRBracketLoc () const
void setRBracketLoc (SourceLocation Loc)
SourceRange getBracketsRange () const
Expr * getSizeExpr () const
void setSizeExpr (Expr *Size)
TypeLoc getElementLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (ArrayTypeLoc other)
TypeLoc getNextTypeLoc () const
const ArrayType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
ArrayLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Wrapper for source info for arrays.
Definition at line 1521 of file TypeLoc.h.
Member Function Documentation
getBracketsRange()
SourceRange clang::ArrayTypeLoc::getBracketsRange () const inline
Definition at line 1542 of file TypeLoc.h.
References getLBracketLoc(), and getRBracketLoc().
getElementLoc()
TypeLoc clang::ArrayTypeLoc::getElementLoc () const inline
Definition at line 1554 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getInnerTypeLoc().
Referenced by FixInvalidVariablyModifiedTypeLoc().
getInnerType()
QualType clang::ArrayTypeLoc::getInnerType () const inline
Definition at line 1568 of file TypeLoc.h.
References clang::ArrayType::getElementType(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getTypePtr().
getLBracketLoc()
SourceLocation clang::ArrayTypeLoc::getLBracketLoc () const inline
Definition at line 1526 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::LBracketLoc.
Referenced by FixInvalidVariablyModifiedTypeLoc(), getBracketsRange(), and getLocalSourceRange().
getLocalSourceRange()
SourceRange clang::ArrayTypeLoc::getLocalSourceRange () const inline
Definition at line 1558 of file TypeLoc.h.
References getLBracketLoc(), and getRBracketLoc().
getRBracketLoc()
SourceLocation clang::ArrayTypeLoc::getRBracketLoc () const inline
Definition at line 1534 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::RBracketLoc.
Referenced by FixInvalidVariablyModifiedTypeLoc(), getBracketsRange(), and getLocalSourceRange().
getSizeExpr()
Expr * clang::ArrayTypeLoc::getSizeExpr () const inline
Definition at line 1546 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::Size.
Referenced by FixInvalidVariablyModifiedTypeLoc(), and clang::DependentSizedArrayTypeLoc::initializeLocal().
initializeLocal()
void clang::ArrayTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 1562 of file TypeLoc.h.
References setLBracketLoc(), setRBracketLoc(), and setSizeExpr().
Referenced by clang::DependentSizedArrayTypeLoc::initializeLocal().
setLBracketLoc()
void clang::ArrayTypeLoc::setLBracketLoc (SourceLocation Loc) inline
Definition at line 1530 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::LBracketLoc.
Referenced by initializeLocal(), and clang::TypeLocReader::VisitArrayTypeLoc().
setRBracketLoc()
void clang::ArrayTypeLoc::setRBracketLoc (SourceLocation Loc) inline
Definition at line 1538 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::RBracketLoc.
Referenced by initializeLocal(), and clang::TypeLocReader::VisitArrayTypeLoc().
setSizeExpr()
void clang::ArrayTypeLoc::setSizeExpr (Expr * Size) inline
Definition at line 1550 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ArrayTypeLoc, ArrayType, ArrayLocInfo >::getLocalData(), and clang::ArrayLocInfo::Size.
Referenced by initializeLocal(), clang::DependentSizedArrayTypeLoc::initializeLocal(), and clang::TypeLocReader::VisitArrayTypeLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h