clang: clang::TextTreeStructure Class Reference
clang::TextTreeStructure Class Reference
#include "clang/AST/TextNodeDumper.h"
Public Member Functions
template<typename Fn >
void AddChild (Fn DoAddChild)
Add a child of the current node. Calls DoAddChild without arguments.
template<typename Fn >
void AddChild (StringRef Label, Fn DoAddChild)
Add a child of the current node with an optional label.
TextTreeStructure (raw_ostream &OS, bool ShowColors)
Detailed Description
Definition at line 33 of file TextNodeDumper.h.
Constructor & Destructor Documentation
TextTreeStructure()
clang::TextTreeStructure::TextTreeStructure (raw_ostream & OS, bool ShowColors) inline
Definition at line 123 of file TextNodeDumper.h.
References ShowColors.
Member Function Documentation
AddChild() [1/2]
template<typename Fn > void clang::TextTreeStructure::AddChild (Fn DoAddChild) inline
Add a child of the current node. Calls DoAddChild without arguments.
Definition at line 51 of file TextNodeDumper.h.
References AddChild().
Referenced by AddChild(), clang::TextNodeDumper::dumpCleanupObject(), clang::TextNodeDumper::dumpDeclRef(), clang::ASTDumper::dumpInvalidDeclContext(), clang::ASTDumper::dumpLookups(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::VisitConstantExpr(), clang::TextNodeDumper::VisitConstructorUsingShadowDecl(), clang::TextNodeDumper::VisitCXXRecordDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::TextNodeDumper::VisitOMPRequiresDecl(), and clang::TextNodeDumper::VisitVarDecl().
AddChild() [2/2]
template<typename Fn > void clang::TextTreeStructure::AddChild (StringRef Label, Fn DoAddChild) inline
Add a child of the current node with an optional label.
Calls DoAddChild without arguments.
Definition at line 57 of file TextNodeDumper.h.
References clang::IndentColor, Label, and ShowColors.
The documentation for this class was generated from the following file:
include/clang/AST/TextNodeDumper.h