clang: clang::interp::EvalEmitter Class Reference
clang::interp::EvalEmitter Class Reference abstract
An emitter which evaluates opcodes as they are emitted.
#include "/root/llvm-project/clang/lib/AST/Interp/EvalEmitter.h"
Public Types
using LabelTy = uint32_t
using AddrTy = uintptr_t
using Local = Scope::Local
Public Member Functions
llvm::Expected< bool > interpretExpr (const Expr *E)
llvm::Expected< bool > interpretDecl (const VarDecl *VD)
Public Member Functions inherited from clang::interp::SourceMapper
virtual ~SourceMapper ()
const Expr * getExpr (const Function *F, CodePtr PC) const
Returns the expression if an opcode belongs to one, null otherwise.
SourceLocation getLocation (const Function *F, CodePtr PC) const
Returns the location from which an opcode originates.
Protected Member Functions
EvalEmitter (Context &Ctx, Program &P, State &Parent, InterpStack &Stk, APValue &Result)
virtual ~EvalEmitter ()
void emitLabel (LabelTy Label)
Define a label.
LabelTy getLabel ()
Create a label.
virtual bool visitExpr (const Expr *E)=0
Methods implemented by the compiler.
virtual bool visitDecl (const VarDecl *VD)=0
bool bail (const Stmt *S)
bool bail (const Decl *D)
bool bail (const SourceLocation &Loc)
bool jumpTrue (const LabelTy &Label)
Emits jumps.
bool jumpFalse (const LabelTy &Label)
bool jump (const LabelTy &Label)
bool fallthrough (const LabelTy &Label)
Local createLocal (Descriptor *D)
Callback for registering a local.
SourceInfo getSource (const Function *F, CodePtr PC) const override
Returns the source location of the current opcode.
Protected Attributes
llvm::DenseMap< const ParmVarDecl *, unsigned > Params
Parameter indices.
llvm::DenseMap< const ValueDecl *, std::pair< unsigned, bool > > LambdaCaptures
Lambda captures.
unsigned LambdaThisCapture
llvm::SmallVector< SmallVector< Local, 8 >, 2 > Descriptors
Local descriptors.
Detailed Description
An emitter which evaluates opcodes as they are emitted.
Definition at line 35 of file EvalEmitter.h.
Member Typedef Documentation
AddrTy
using clang::interp::EvalEmitter::AddrTy = uintptr_t
Definition at line 38 of file EvalEmitter.h.
LabelTy
using clang::interp::EvalEmitter::LabelTy = uint32_t
Definition at line 37 of file EvalEmitter.h.
Local
using clang::interp::EvalEmitter::Local = Scope::Local
Definition at line 39 of file EvalEmitter.h.
Constructor & Destructor Documentation
EvalEmitter()
EvalEmitter::EvalEmitter (Context & Ctx, Program & P, State & Parent, InterpStack & Stk, APValue & Result) protected
Definition at line 22 of file EvalEmitter.cpp.
References clang::interp::InterpState::Current.
~EvalEmitter()
virtual clang::interp::EvalEmitter::~EvalEmitter () inline protected virtual
Definition at line 48 of file EvalEmitter.h.
Member Function Documentation
bail() [1/3]
bool clang::interp::EvalEmitter::bail (const Decl * D) inline protected
Definition at line 60 of file EvalEmitter.h.
References bail(), and clang::Decl::getBeginLoc().
Referenced by bail().
bail() [2/3]
bool EvalEmitter::bail (const SourceLocation & Loc) protected
Definition at line 74 of file EvalEmitter.cpp.
bail() [3/3]
bool clang::interp::EvalEmitter::bail (const Stmt * S) inline protected
Definition at line 59 of file EvalEmitter.h.
References bail().
Referenced by bail().
createLocal()
Scope::Local EvalEmitter::createLocal (Descriptor * D) protected
Callback for registering a local.
Definition at line 52 of file EvalEmitter.cpp.
References clang::Block, clang::interp::InlineDescriptor::Desc, clang::interp::Descriptor::getAllocSize(), clang::interp::InlineDescriptor::IsActive, clang::interp::InlineDescriptor::IsBase, clang::interp::InlineDescriptor::IsConst, clang::interp::InlineDescriptor::IsFieldMutable, clang::interp::InlineDescriptor::IsInitialized, and clang::interp::InlineDescriptor::Offset.
emitLabel()
void EvalEmitter::emitLabel (LabelTy Label) protected
Define a label.
Definition at line 46 of file EvalEmitter.cpp.
References Label.
fallthrough()
bool EvalEmitter::fallthrough (const LabelTy & Label) protected
Definition at line 102 of file EvalEmitter.cpp.
References Label.
getLabel()
EvalEmitter::LabelTy EvalEmitter::getLabel () protected
Create a label.
Definition at line 50 of file EvalEmitter.cpp.
getSource()
SourceInfo clang::interp::EvalEmitter::getSource (const Function * F, CodePtr PC) const inline override protected virtual
Returns the source location of the current opcode.
Implements clang::interp::SourceMapper.
Definition at line 73 of file EvalEmitter.h.
References clang::interp::Function::getSource(), and clang::interp::Function::hasBody().
interpretDecl()
llvm::Expected< bool > EvalEmitter::interpretDecl (const VarDecl * VD)
Definition at line 38 of file EvalEmitter.cpp.
References visitDecl().
interpretExpr()
llvm::Expected< bool > EvalEmitter::interpretExpr (const Expr * E)
Definition at line 30 of file EvalEmitter.cpp.
References visitExpr().
jump()
bool EvalEmitter::jump (const LabelTy & Label) protected
Definition at line 96 of file EvalEmitter.cpp.
References Label.
jumpFalse()
bool EvalEmitter::jumpFalse (const LabelTy & Label) protected
Definition at line 88 of file EvalEmitter.cpp.
References Label, clang::interp::InterpStack::pop(), and clang::interp::InterpState::Stk.
jumpTrue()
bool EvalEmitter::jumpTrue (const LabelTy & Label) protected
Emits jumps.
Definition at line 80 of file EvalEmitter.cpp.
References Label, clang::interp::InterpStack::pop(), and clang::interp::InterpState::Stk.
visitDecl()
virtual bool clang::interp::EvalEmitter::visitDecl (const VarDecl * VD) protected pure virtual
Referenced by interpretDecl().
visitExpr()
virtual bool clang::interp::EvalEmitter::visitExpr (const Expr * E) protected pure virtual
Methods implemented by the compiler.
Referenced by interpretExpr().
Member Data Documentation
Descriptors
llvm::SmallVector<SmallVector<Local, 8>, 2> clang::interp::EvalEmitter::Descriptors protected
Local descriptors.
Definition at line 84 of file EvalEmitter.h.
LambdaCaptures
llvm::DenseMap<const ValueDecl *, std::pair<unsigned, bool> > clang::interp::EvalEmitter::LambdaCaptures protected
Lambda captures.
Map from Decl* to [Offset, IsReference] pair.
Definition at line 81 of file EvalEmitter.h.
LambdaThisCapture
unsigned clang::interp::EvalEmitter::LambdaThisCapture protected
Definition at line 82 of file EvalEmitter.h.
Params
llvm::DenseMap<const ParmVarDecl *, unsigned> clang::interp::EvalEmitter::Params protected
Parameter indices.
Definition at line 78 of file EvalEmitter.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/EvalEmitter.h
lib/AST/Interp/EvalEmitter.cpp