clang: clang::CodeGen::PrePostActionTy Class Reference
clang::CodeGen::PrePostActionTy Class Reference
A basic class for pre|post-action for advanced codegen sequence for OpenMP region.
#include "/root/llvm-project/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
PrePostActionTy ()
virtual void Enter (CodeGenFunction &CGF)
virtual void Exit (CodeGenFunction &CGF)
virtual ~PrePostActionTy ()
Detailed Description
A basic class for pre|post-action for advanced codegen sequence for OpenMP region.
Definition at line 58 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
PrePostActionTy()
clang::CodeGen::PrePostActionTy::PrePostActionTy () inline explicit
Definition at line 60 of file CGOpenMPRuntime.h.
~PrePostActionTy()
virtual clang::CodeGen::PrePostActionTy::~PrePostActionTy () inline virtual
Definition at line 63 of file CGOpenMPRuntime.h.
Member Function Documentation
Enter()
virtual void clang::CodeGen::PrePostActionTy::Enter (CodeGenFunction & CGF) inline virtual
Definition at line 61 of file CGOpenMPRuntime.h.
Referenced by emitOMPSimdRegion(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), emitTargetParallelForRegion(), emitTargetParallelForSimdRegion(), emitTargetParallelGenericLoopRegion(), emitTargetParallelRegion(), emitTargetRegion(), emitTargetTeamsDistributeParallelForRegion(), emitTargetTeamsDistributeParallelForSimdRegion(), emitTargetTeamsDistributeRegion(), emitTargetTeamsDistributeSimdRegion(), emitTargetTeamsGenericLoopRegion(), and emitTargetTeamsRegion().
Exit()
virtual void clang::CodeGen::PrePostActionTy::Exit (CodeGenFunction & CGF) inline virtual
Definition at line 62 of file CGOpenMPRuntime.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGOpenMPRuntime.h