clang: clang::RISCV::Policy Class Reference
clang::RISCV::Policy Class Reference
#include "clang/Support/RISCVVIntrinsicUtils.h"
Public Types
enum PolicyType { Undisturbed , Agnostic }
Public Member Functions
Policy ()=default
Policy (PolicyType TailPolicy)
Policy (PolicyType TailPolicy, PolicyType MaskPolicy)
bool isTAMAPolicy () const
bool isTAMUPolicy () const
bool isTUMAPolicy () const
bool isTUMUPolicy () const
bool isTAPolicy () const
bool isTUPolicy () const
bool isMAPolicy () const
bool isMUPolicy () const
bool operator== (const Policy &Other) const
bool operator!= (const Policy &Other) const
bool operator< (const Policy &Other) const
Detailed Description
Definition at line 102 of file RISCVVIntrinsicUtils.h.
Member Enumeration Documentation
PolicyType
enum clang::RISCV::Policy::PolicyType
Enumerator
Undisturbed
Agnostic
Definition at line 104 of file RISCVVIntrinsicUtils.h.
Constructor & Destructor Documentation
Policy() [1/3]
clang::RISCV::Policy::Policy () default
Policy() [2/3]
clang::RISCV::Policy::Policy (PolicyType TailPolicy) inline
Definition at line 117 of file RISCVVIntrinsicUtils.h.
Policy() [3/3]
clang::RISCV::Policy::Policy (PolicyType TailPolicy, PolicyType MaskPolicy) inline
Definition at line 118 of file RISCVVIntrinsicUtils.h.
Member Function Documentation
isMAPolicy()
bool clang::RISCV::Policy::isMAPolicy () const inline
Definition at line 141 of file RISCVVIntrinsicUtils.h.
References Agnostic.
isMUPolicy()
bool clang::RISCV::Policy::isMUPolicy () const inline
Definition at line 143 of file RISCVVIntrinsicUtils.h.
References Undisturbed.
isTAMAPolicy()
bool clang::RISCV::Policy::isTAMAPolicy () const inline
Definition at line 121 of file RISCVVIntrinsicUtils.h.
References Agnostic.
Referenced by clang::RISCV::RVVIntrinsic::computeBuiltinTypes(), clang::RISCV::RVVIntrinsic::getPolicyAttrsBits(), and clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
isTAMUPolicy()
bool clang::RISCV::Policy::isTAMUPolicy () const inline
Definition at line 125 of file RISCVVIntrinsicUtils.h.
References Agnostic, and Undisturbed.
Referenced by clang::RISCV::RVVIntrinsic::getPolicyAttrsBits(), and clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
isTAPolicy()
bool clang::RISCV::Policy::isTAPolicy () const inline
Definition at line 137 of file RISCVVIntrinsicUtils.h.
References Agnostic.
Referenced by clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
isTUMAPolicy()
bool clang::RISCV::Policy::isTUMAPolicy () const inline
Definition at line 129 of file RISCVVIntrinsicUtils.h.
References Agnostic, and Undisturbed.
Referenced by clang::RISCV::RVVIntrinsic::getPolicyAttrsBits(), and clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
isTUMUPolicy()
bool clang::RISCV::Policy::isTUMUPolicy () const inline
Definition at line 133 of file RISCVVIntrinsicUtils.h.
References Undisturbed.
Referenced by clang::RISCV::RVVIntrinsic::getPolicyAttrsBits(), and clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
isTUPolicy()
bool clang::RISCV::Policy::isTUPolicy () const inline
Definition at line 139 of file RISCVVIntrinsicUtils.h.
References Undisturbed.
Referenced by clang::RISCV::RVVIntrinsic::computeBuiltinTypes(), and clang::RISCV::RVVIntrinsic::updateNamesAndPolicy().
operator!=()
bool clang::RISCV::Policy::operator!= (const Policy & Other) const inline
Definition at line 149 of file RISCVVIntrinsicUtils.h.
operator<()
bool clang::RISCV::Policy::operator< (const Policy & Other) const inline
Definition at line 151 of file RISCVVIntrinsicUtils.h.
operator==()
bool clang::RISCV::Policy::operator== (const Policy & Other) const inline
Definition at line 145 of file RISCVVIntrinsicUtils.h.
The documentation for this class was generated from the following file:
include/clang/Support/RISCVVIntrinsicUtils.h