clang: clang::CXXFieldCollector Class Reference
clang::CXXFieldCollector Class Reference
CXXFieldCollector - Used to keep track of CXXFieldDecls during parsing of C++ classes.
#include "clang/Sema/CXXFieldCollector.h"
Public Member Functions
void StartClass ()
StartClass - Called by Sema::ActOnStartCXXClassDef.
void Add (FieldDecl *D)
Add - Called by Sema::ActOnCXXMemberDeclarator.
size_t getCurNumFields () const
getCurNumField - The number of fields added to the currently parsed class.
FieldDecl ** getCurFields ()
getCurFields - Pointer to array of fields added to the currently parsed class.
void FinishClass ()
FinishClass - Called by Sema::ActOnFinishCXXClassDef.
Detailed Description
CXXFieldCollector - Used to keep track of CXXFieldDecls during parsing of C++ classes.
Definition at line 25 of file CXXFieldCollector.h.
Member Function Documentation
Add()
void clang::CXXFieldCollector::Add (FieldDecl * D) inline
Add - Called by Sema::ActOnCXXMemberDeclarator.
Definition at line 55 of file CXXFieldCollector.h.
FinishClass()
void clang::CXXFieldCollector::FinishClass () inline
FinishClass - Called by Sema::ActOnFinishCXXClassDef.
Definition at line 71 of file CXXFieldCollector.h.
References getCurNumFields().
getCurFields()
FieldDecl ** clang::CXXFieldCollector::getCurFields () inline
getCurFields - Pointer to array of fields added to the currently parsed class.
Definition at line 68 of file CXXFieldCollector.h.
References getCurNumFields().
getCurNumFields()
size_t clang::CXXFieldCollector::getCurNumFields () const inline
getCurNumField - The number of fields added to the currently parsed class.
Definition at line 61 of file CXXFieldCollector.h.
Referenced by FinishClass(), and getCurFields().
StartClass()
void clang::CXXFieldCollector::StartClass () inline
StartClass - Called by Sema::ActOnStartCXXClassDef.
Definition at line 52 of file CXXFieldCollector.h.
The documentation for this class was generated from the following file:
include/clang/Sema/CXXFieldCollector.h