clang: clang::ASTMergeAction Class Reference
clang::ASTMergeAction Class Reference
Frontend action adaptor that merges ASTs together.
#include "clang/Frontend/FrontendActions.h"
Public Member Functions
ASTMergeAction (std::unique_ptr< FrontendAction > AdaptedAction, ArrayRef< std::string > ASTFiles)
~ASTMergeAction () override
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
TranslationUnitKind getTranslationUnitKind () override
For AST-based actions, the kind of translation unit we're handling.
bool hasPCHSupport () const override
Does this action support use with PCH?
bool hasASTFileSupport () const override
Does this action support use with AST files?
bool hasCodeCompletionSupport () const override
Does this action support use with code completion?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual bool hasIRSupport () const
Does this action support use with IR files?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Protected Member Functions
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
bool BeginSourceFileAction (CompilerInstance &CI) override
Callback at the start of processing a single input.
void ExecuteAction () override
Callback to run the program action, using the initialized compiler instance.
void EndSourceFileAction () override
Callback at the end of processing a single input.
Protected Member Functions inherited from clang::FrontendAction
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Detailed Description
Frontend action adaptor that merges ASTs together.
This action takes an existing AST file and "merges" it into the AST context, producing a merged context. This action is an action adaptor, which forwards most of its calls to another action that will consume the merged context.
Definition at line 226 of file FrontendActions.h.
Constructor & Destructor Documentation
ASTMergeAction()
ASTMergeAction::ASTMergeAction (std::unique_ptr< FrontendAction > AdaptedAction, ArrayRef< std::string > ASTFiles)
Definition at line 87 of file ASTMerge.cpp.
~ASTMergeAction()
ASTMergeAction::~ASTMergeAction () override
Definition at line 93 of file ASTMerge.cpp.
Member Function Documentation
BeginSourceFileAction()
bool ASTMergeAction::BeginSourceFileAction (CompilerInstance & CI) override protected virtual
Callback at the start of processing a single input.
Returns
True on success; on failure ExecutionAction() and EndSourceFileAction() will not be called.
Reimplemented from clang::FrontendAction.
Definition at line 24 of file ASTMerge.cpp.
References clang::FrontendAction::getCurrentInput(), and clang::FrontendAction::takeCurrentASTUnit().
CreateASTConsumer()
std::unique_ptr< ASTConsumer > ASTMergeAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) override protected virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Implements clang::FrontendAction.
Definition at line 20 of file ASTMerge.cpp.
EndSourceFileAction()
void ASTMergeAction::EndSourceFileAction () override protected virtual
Callback at the end of processing a single input.
This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented from clang::FrontendAction.
Definition at line 83 of file ASTMerge.cpp.
ExecuteAction()
void ASTMergeAction::ExecuteAction () override protected virtual
Callback to run the program action, using the initialized compiler instance.
This is guaranteed to only be called between BeginSourceFileAction() and EndSourceFileAction().
Implements clang::FrontendAction.
Definition at line 33 of file ASTMerge.cpp.
References clang::DiagnosticConsumer::BeginSourceFile(), clang::DeclContext::decls(), clang::DiagnosticConsumer::EndSourceFile(), clang::FormatASTNodeDiagnosticArgument(), clang::CompilerInstance::getASTConsumer(), clang::CompilerInstance::getASTContext(), clang::TranslationUnitDecl::getASTContext(), clang::DiagnosticsEngine::getClient(), clang::FrontendAction::getCompilerInstance(), clang::DiagnosticsEngine::getDiagnosticIDs(), clang::CompilerInstance::getDiagnosticOpts(), clang::CompilerInstance::getDiagnostics(), clang::CompilerInstance::getFileManager(), clang::CompilerInstance::getFileSystemOpts(), clang::CompilerInstance::getHeaderSearchOptsPtr(), clang::ASTContext::getLangOpts(), clang::CompilerInstance::getPCHContainerReader(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTConsumer::HandleTopLevelDecl(), clang::ASTImporter::Import(), clang::ASTUnit::LoadEverything, clang::ASTUnit::LoadFromASTFile(), N, and clang::DiagnosticsEngine::SetArgToStringFn().
getTranslationUnitKind()
TranslationUnitKind ASTMergeAction::getTranslationUnitKind () override virtual
For AST-based actions, the kind of translation unit we're handling.
Reimplemented from clang::FrontendAction.
Definition at line 100 of file ASTMerge.cpp.
hasASTFileSupport()
bool ASTMergeAction::hasASTFileSupport () const override virtual
Does this action support use with AST files?
Reimplemented from clang::FrontendAction.
Definition at line 108 of file ASTMerge.cpp.
hasCodeCompletionSupport()
bool ASTMergeAction::hasCodeCompletionSupport () const override virtual
Does this action support use with code completion?
Reimplemented from clang::FrontendAction.
Definition at line 112 of file ASTMerge.cpp.
hasPCHSupport()
bool ASTMergeAction::hasPCHSupport () const override virtual
Does this action support use with PCH?
Reimplemented from clang::FrontendAction.
Definition at line 104 of file ASTMerge.cpp.
usesPreprocessorOnly()
bool ASTMergeAction::usesPreprocessorOnly () const override virtual
Does this action only use the preprocessor?
If so no AST context will be created and this action will be invalid with AST file inputs.
Implements clang::FrontendAction.
Definition at line 96 of file ASTMerge.cpp.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendActions.h
lib/Frontend/ASTMerge.cpp