clang: clang::CodeGen::CGOpenCLRuntime Class Reference
clang::CodeGen::CGOpenCLRuntime Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/CGOpenCLRuntime.h"
Classes
struct EnqueuedBlockInfo
Structure for enqueued block information.
Public Member Functions
CGOpenCLRuntime (CodeGenModule &CGM)
virtual ~CGOpenCLRuntime ()
virtual void EmitWorkGroupLocalVarDecl (CodeGenFunction &CGF, const VarDecl &D)
Emit the IR required for a work-group-local variable declaration, and add an entry to CGF's LocalDeclMap for D.
virtual llvm::Type * convertOpenCLSpecificType (const Type *T)
virtual llvm::Type * getPipeType (const PipeType *T)
llvm::Type * getSamplerType (const Type *T)
virtual llvm::Value * getPipeElemSize (const Expr *PipeArg)
virtual llvm::Value * getPipeElemAlign (const Expr *PipeArg)
llvm::PointerType * getGenericVoidPointerType ()
EnqueuedBlockInfo emitOpenCLEnqueuedBlock (CodeGenFunction &CGF, const Expr *E)
void recordBlockInfo (const BlockExpr *E, llvm::Function *InvokeF, llvm::Value *Block, llvm::Type *BlockTy)
Record invoke function and block literal emitted during normal codegen for a block expression.
llvm::Function * getInvokeFunction (const Expr *E)
Protected Member Functions
virtual llvm::Type * getPipeType (const PipeType *T, StringRef Name, llvm::Type *&PipeTy)
llvm::PointerType * getPointerType (const Type *T, StringRef Name)
Protected Attributes
CodeGenModule & CGM
llvm::Type * PipeROTy
llvm::Type * PipeWOTy
llvm::Type * SamplerTy
llvm::StringMap< llvm::PointerType * > CachedTys
llvm::DenseMap< const Expr *, EnqueuedBlockInfo > EnqueuedBlockMap
Maps block expression to block information.
Detailed Description
Definition at line 36 of file CGOpenCLRuntime.h.
Constructor & Destructor Documentation
CGOpenCLRuntime()
clang::CodeGen::CGOpenCLRuntime::CGOpenCLRuntime (CodeGenModule & CGM) inline
Definition at line 59 of file CGOpenCLRuntime.h.
~CGOpenCLRuntime()
CGOpenCLRuntime::~CGOpenCLRuntime () virtual
Definition at line 26 of file CGOpenCLRuntime.cpp.
Member Function Documentation
convertOpenCLSpecificType()
llvm::Type * CGOpenCLRuntime::convertOpenCLSpecificType (const Type * T) virtual
Definition at line 33 of file CGOpenCLRuntime.cpp.
References CGM, getKind(), clang::CodeGen::TargetCodeGenInfo::getOpenCLType(), getPointerType(), getSamplerType(), and clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
Referenced by clang::CodeGen::CodeGenTypes::ConvertType().
emitOpenCLEnqueuedBlock()
CGOpenCLRuntime::EnqueuedBlockInfo CGOpenCLRuntime::emitOpenCLEnqueuedBlock (CodeGenFunction & CGF, const Expr * E)
Returns
enqueued block information for enqueued block.
Definition at line 178 of file CGOpenCLRuntime.cpp.
References clang::Block, clang::CodeGen::TargetCodeGenInfo::createEnqueuedBlockKernel(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), EnqueuedBlockMap, getBlockExpr(), and clang::CodeGen::CodeGenFunction::getTargetHooks().
EmitWorkGroupLocalVarDecl()
void CGOpenCLRuntime::EmitWorkGroupLocalVarDecl (CodeGenFunction & CGF, const VarDecl & D) virtual
Emit the IR required for a work-group-local variable declaration, and add an entry to CGF's LocalDeclMap for D.
The base class does this using CodeGenFunction::EmitStaticVarDecl to emit an internal global for D.
Definition at line 28 of file CGOpenCLRuntime.cpp.
References clang::CodeGen::CodeGenFunction::EmitStaticVarDecl().
getGenericVoidPointerType()
llvm::PointerType * CGOpenCLRuntime::getGenericVoidPointerType ()
Returns
__generic void* type.
Definition at line 135 of file CGOpenCLRuntime.cpp.
References CGM, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getTargetAddressSpace(), and clang::opencl_generic.
Referenced by clang::CodeGen::CodeGenModule::getGenericBlockLiteralType(), and initializeForBlockHeader().
getInvokeFunction()
llvm::Function * CGOpenCLRuntime::getInvokeFunction (const Expr * E)
Returns
LLVM block invoke function emitted for an expression derived from the block expression.
Definition at line 173 of file CGOpenCLRuntime.cpp.
References EnqueuedBlockMap, and getBlockExpr().
getPipeElemAlign()
llvm::Value * CGOpenCLRuntime::getPipeElemAlign (const Expr * PipeArg) virtual
Definition at line 125 of file CGOpenCLRuntime.cpp.
References clang::Type::castAs(), CGM, clang::CodeGen::CodeGenModule::getContext(), clang::PipeType::getElementType(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CharUnits::getQuantity(), clang::Expr::getType(), and clang::ASTContext::getTypeAlignInChars().
getPipeElemSize()
llvm::Value * CGOpenCLRuntime::getPipeElemSize (const Expr * PipeArg) virtual
Definition at line 115 of file CGOpenCLRuntime.cpp.
References clang::Type::castAs(), CGM, clang::CodeGen::CodeGenModule::getContext(), clang::PipeType::getElementType(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CharUnits::getQuantity(), clang::Expr::getType(), and clang::ASTContext::getTypeSizeInChars().
getPipeType() [1/2]
llvm::Type * CGOpenCLRuntime::getPipeType (const PipeType * T) virtual
Definition at line 80 of file CGOpenCLRuntime.cpp.
References CGM, clang::CodeGen::TargetCodeGenInfo::getOpenCLType(), getPipeType(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), PipeROTy, and PipeWOTy.
getPipeType() [2/2]
llvm::Type * CGOpenCLRuntime::getPipeType (const PipeType * T, StringRef Name, llvm::Type *& PipeTy) protected virtual
Definition at line 90 of file CGOpenCLRuntime.cpp.
References CGM, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getOpenCLTypeAddrSpace(), and clang::ASTContext::getTargetAddressSpace().
Referenced by clang::CodeGen::CodeGenTypes::ConvertType(), and getPipeType().
getPointerType()
llvm::PointerType * CGOpenCLRuntime::getPointerType (const Type * T, StringRef Name) protected
Definition at line 65 of file CGOpenCLRuntime.cpp.
References CachedTys, CGM, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getOpenCLTypeAddrSpace(), and clang::ASTContext::getTargetAddressSpace().
Referenced by convertOpenCLSpecificType().
getSamplerType()
llvm::Type * CGOpenCLRuntime::getSamplerType (const Type * T)
Definition at line 100 of file CGOpenCLRuntime.cpp.
References CGM, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::TargetCodeGenInfo::getOpenCLType(), clang::ASTContext::getOpenCLTypeAddrSpace(), clang::ASTContext::getTargetAddressSpace(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::CanQual< typename >::getTypePtr(), clang::ASTContext::OCLSamplerTy, and SamplerTy.
Referenced by convertOpenCLSpecificType(), and clang::CodeGen::CodeGenModule::createOpenCLIntToSamplerConversion().
recordBlockInfo()
void CGOpenCLRuntime::recordBlockInfo (const BlockExpr * E, llvm::Function * InvokeF, llvm::Value * Block, llvm::Type * BlockTy)
Record invoke function and block literal emitted during normal codegen for a block expression.
Record emitted llvm invoke function and llvm block literal for the corresponding block expression.
The information is used by emitOpenCLEnqueuedBlock to emit wrapper kernel.
Parameters
InvokeF invoke function emitted for the block expression.
Block block literal emitted for the block expression.
Definition at line 161 of file CGOpenCLRuntime.cpp.
References clang::Block, and EnqueuedBlockMap.
Referenced by buildGlobalBlock().
Member Data Documentation
CachedTys
llvm::StringMap<llvm::PointerType *> clang::CodeGen::CGOpenCLRuntime::CachedTys protected
Definition at line 42 of file CGOpenCLRuntime.h.
Referenced by getPointerType().
CGM
CodeGenModule& clang::CodeGen::CGOpenCLRuntime::CGM protected
Definition at line 38 of file CGOpenCLRuntime.h.
Referenced by convertOpenCLSpecificType(), getGenericVoidPointerType(), getPipeElemAlign(), getPipeElemSize(), getPipeType(), getPipeType(), getPointerType(), and getSamplerType().
EnqueuedBlockMap
llvm::DenseMap<const Expr *, EnqueuedBlockInfo> clang::CodeGen::CGOpenCLRuntime::EnqueuedBlockMap protected
Maps block expression to block information.
Definition at line 52 of file CGOpenCLRuntime.h.
Referenced by emitOpenCLEnqueuedBlock(), getInvokeFunction(), and recordBlockInfo().
PipeROTy
llvm::Type* clang::CodeGen::CGOpenCLRuntime::PipeROTy protected
Definition at line 39 of file CGOpenCLRuntime.h.
Referenced by getPipeType().
PipeWOTy
llvm::Type* clang::CodeGen::CGOpenCLRuntime::PipeWOTy protected
Definition at line 40 of file CGOpenCLRuntime.h.
Referenced by getPipeType().
SamplerTy
llvm::Type* clang::CodeGen::CGOpenCLRuntime::SamplerTy protected
Definition at line 41 of file CGOpenCLRuntime.h.
Referenced by getSamplerType().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenCLRuntime.h
lib/CodeGen/CGOpenCLRuntime.cpp