clang: clang::OMPClauseMappableExprCommon Class Reference
clang::OMPClauseMappableExprCommon Class Reference
Struct that defines common infrastructure to handle mappable expressions used in OpenMP clauses.
#include "clang/AST/OpenMPClause.h"
Classes
class MappableComponent
Class that represents a component of a mappable expression.
Public Types
using MappableExprComponentList = SmallVector<MappableComponent, 8>
using MappableExprComponentListRef = ArrayRef<MappableComponent>
using MappableExprComponentLists = SmallVector<MappableExprComponentList, 8>
using MappableExprComponentListsRef = ArrayRef<MappableExprComponentList>
Static Protected Member Functions
static unsigned getComponentsTotalNumber (MappableExprComponentListsRef ComponentLists)
static unsigned getUniqueDeclarationsTotalNumber (ArrayRef< const ValueDecl * > Declarations)
Detailed Description
Struct that defines common infrastructure to handle mappable expressions used in OpenMP clauses.
Definition at line 5087 of file OpenMPClause.h.
Member Typedef Documentation
MappableExprComponentList
using clang::OMPClauseMappableExprCommon::MappableExprComponentList = SmallVector<MappableComponent, 8>
Definition at line 5132 of file OpenMPClause.h.
MappableExprComponentListRef
using clang::OMPClauseMappableExprCommon::MappableExprComponentListRef = ArrayRef<MappableComponent>
Definition at line 5133 of file OpenMPClause.h.
MappableExprComponentLists
using clang::OMPClauseMappableExprCommon::MappableExprComponentLists = SmallVector<MappableExprComponentList, 8>
Definition at line 5138 of file OpenMPClause.h.
MappableExprComponentListsRef
using clang::OMPClauseMappableExprCommon::MappableExprComponentListsRef = ArrayRef<MappableExprComponentList>
Definition at line 5139 of file OpenMPClause.h.
Member Function Documentation
getComponentsTotalNumber()
unsigned OMPClauseMappableExprCommon::getComponentsTotalNumber (MappableExprComponentListsRef ComponentLists) static protected
Definition at line 1113 of file OpenMPClause.cpp.
References clang::C.
Referenced by clang::OMPFromClause::Create(), clang::OMPHasDeviceAddrClause::Create(), clang::OMPIsDevicePtrClause::Create(), clang::OMPMapClause::Create(), clang::OMPToClause::Create(), clang::OMPUseDeviceAddrClause::Create(), clang::OMPUseDevicePtrClause::Create(), and clang::OMPMappableExprListClause< T >::setClauseInfo().
getUniqueDeclarationsTotalNumber()
unsigned OMPClauseMappableExprCommon::getUniqueDeclarationsTotalNumber (ArrayRef< const ValueDecl * > Declarations) static protected
Definition at line 1121 of file OpenMPClause.cpp.
References clang::cast().
Referenced by clang::OMPFromClause::Create(), clang::OMPHasDeviceAddrClause::Create(), clang::OMPIsDevicePtrClause::Create(), clang::OMPMapClause::Create(), clang::OMPToClause::Create(), clang::OMPUseDeviceAddrClause::Create(), clang::OMPUseDevicePtrClause::Create(), and clang::OMPMappableExprListClause< T >::setClauseInfo().
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp