clang: clang::driver::tools::darwin::Linker Class Reference
clang::driver::tools::darwin::Linker Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/Darwin.h"
Public Member Functions
Linker (const ToolChain &TC)
bool hasIntegratedCPP () const override
bool isLinkJob () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::tools::darwin::MachOTool
MachOTool (const char *Name, const char *ShortName, const ToolChain &TC)
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Additional Inherited Members
Protected Member Functions inherited from clang::driver::tools::darwin::MachOTool
void AddMachOArch (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
const toolchains::MachO & getMachOToolChain () const
Detailed Description
Definition at line 63 of file Darwin.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::darwin::Linker::Linker (const ToolChain & TC) inline
Definition at line 71 of file Darwin.h.
Member Function Documentation
ConstructJob()
void darwin::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Hack(tm) to ignore linking errors when we are doing ARC migration.
Implements clang::driver::Tool.
Definition at line 564 of file Darwin.cpp.
References clang::driver::tools::addFortranRuntimeLibraryPath(), clang::driver::tools::addFortranRuntimeLibs(), clang::driver::tools::AddLinkerInputs(), clang::driver::tools::addOpenMPRuntime(), AppendPlatformPrefix(), clang::driver::ResponseFileSupport::AtFileUTF8(), clang::C, checkRemarksOptions(), Cmd, clang::driver::InputInfo::getFilename(), clang::driver::tools::getLTOParallelism(), clang::driver::tools::getStatsFileName(), clang::driver::InputInfo::getType(), isObjCRuntimeLinked(), clang::driver::ResponseFileSupport::None(), P, renderRemarksOptions(), clang::driver::ResponseFileSupport::RF_FileList, and clang::driver::willEmitRemarks().
hasIntegratedCPP()
bool clang::driver::tools::darwin::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 73 of file Darwin.h.
isLinkJob()
bool clang::driver::tools::darwin::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 74 of file Darwin.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Darwin.h
lib/Driver/ToolChains/Darwin.cpp