clang: clang::ento::CallEventManager Class Reference
clang::ento::CallEventManager Class Reference
Manages the lifetime of CallEvent objects.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
CallEventManager (llvm::BumpPtrAllocator &alloc)
CallEventRef getCaller (const StackFrameContext *CalleeCtx, ProgramStateRef State)
Gets an outside caller given a callee context.
CallEventRef getCall (const Stmt *S, ProgramStateRef State, const LocationContext *LC, CFGBlock::ConstCFGElementRef ElemRef)
Gets a call event for a function call, Objective-C method call, a 'new', or a 'delete' call.
CallEventRef getSimpleCall (const CallExpr *E, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< ObjCMethodCall > getObjCMethodCall (const ObjCMessageExpr *E, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< CXXConstructorCall > getCXXConstructorCall (const CXXConstructExpr *E, const MemRegion *Target, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< CXXInheritedConstructorCall > getCXXInheritedConstructorCall (const CXXInheritedCtorInitExpr *E, const MemRegion *Target, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< CXXDestructorCall > getCXXDestructorCall (const CXXDestructorDecl *DD, const Stmt *Trigger, const MemRegion *Target, bool IsBase, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< CXXAllocatorCall > getCXXAllocatorCall (const CXXNewExpr *E, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CallEventRef< CXXDeallocatorCall > getCXXDeallocatorCall (const CXXDeleteExpr *E, ProgramStateRef State, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
Friends
class CallEvent
Detailed Description
Manages the lifetime of CallEvent objects.
CallEventManager provides a way to create arbitrary CallEvents "on the stack" as if they were value objects by keeping a cache of CallEvent-sized memory blocks. The CallEvents created by CallEventManager are only valid for the lifetime of the OwnedCallEvent that holds them; right now these objects cannot be copied and ownership cannot be transferred.
Definition at line 1282 of file CallEvent.h.
Constructor & Destructor Documentation
CallEventManager()
clang::ento::CallEventManager::CallEventManager (llvm::BumpPtrAllocator & alloc) inline
Definition at line 1336 of file CallEvent.h.
Member Function Documentation
getCall()
CallEventRef CallEventManager::getCall (const Stmt * S, ProgramStateRef State, const LocationContext * LC, CFGBlock::ConstCFGElementRef ElemRef)
Gets a call event for a function call, Objective-C method call, a 'new', or a 'delete' call.
Definition at line 1457 of file CallEvent.cpp.
References getCXXAllocatorCall(), getCXXDeallocatorCall(), getObjCMethodCall(), and getSimpleCall().
Referenced by generateDiagnosticsForCallLike(), and getCaller().
getCaller()
CallEventRef CallEventManager::getCaller (const StackFrameContext * CalleeCtx, ProgramStateRef State)
Gets an outside caller given a callee context.
Definition at line 1400 of file CallEvent.cpp.
References clang::cast(), clang::CFGElement::getAs(), clang::ento::SVal::getAsRegion(), getCall(), clang::StackFrameContext::getCallSite(), clang::StackFrameContext::getCallSiteBlock(), getCXXConstructorCall(), getCXXDestructorCall(), getCXXInheritedConstructorCall(), clang::ento::SValBuilder::getCXXThis(), clang::LocationContext::getDecl(), clang::StackFrameContext::getIndex(), clang::LocationContext::getParent(), clang::LocationContext::getStackFrame(), clang::ento::SValBuilder::getStateManager(), and clang::ento::ProgramStateManager::getSValBuilder().
Referenced by annotateConsumedSummaryMismatch(), clang::ento::ExprEngine::processCallExit(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), and clang::ento::UndefOrNullArgVisitor::VisitNode().
getCXXAllocatorCall()
CallEventRef< CXXAllocatorCall > clang::ento::CallEventManager::getCXXAllocatorCall (const CXXNewExpr * E, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1384 of file CallEvent.h.
Referenced by getCall(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), and clang::ento::ExprEngine::VisitCXXNewExpr().
getCXXConstructorCall()
CallEventRef< CXXConstructorCall > clang::ento::CallEventManager::getCXXConstructorCall (const CXXConstructExpr * E, const MemRegion * Target, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1360 of file CallEvent.h.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), and getCaller().
getCXXDeallocatorCall()
CallEventRef< CXXDeallocatorCall > clang::ento::CallEventManager::getCXXDeallocatorCall (const CXXDeleteExpr * E, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1391 of file CallEvent.h.
Referenced by getCall(), and clang::ento::ExprEngine::VisitCXXDeleteExpr().
getCXXDestructorCall()
CallEventRef< CXXDestructorCall > clang::ento::CallEventManager::getCXXDestructorCall (const CXXDestructorDecl * DD, const Stmt * Trigger, const MemRegion * Target, bool IsBase, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1375 of file CallEvent.h.
Referenced by getCaller(), and clang::ento::ExprEngine::VisitCXXDestructor().
getCXXInheritedConstructorCall()
CallEventRef< CXXInheritedConstructorCall > clang::ento::CallEventManager::getCXXInheritedConstructorCall (const CXXInheritedCtorInitExpr * E, const MemRegion * Target, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1367 of file CallEvent.h.
Referenced by getCaller().
getObjCMethodCall()
CallEventRef< ObjCMethodCall > clang::ento::CallEventManager::getObjCMethodCall (const ObjCMessageExpr * E, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline
Definition at line 1353 of file CallEvent.h.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), generateDiagnosticsForCallLike(), getCall(), and clang::ento::ExprEngine::VisitObjCMessage().
getSimpleCall()
CallEventRef CallEventManager::getSimpleCall (const CallExpr * E, ProgramStateRef State, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef)
Definition at line 1378 of file CallEvent.cpp.
References clang::CallExpr::getCallee(), clang::Expr::getType(), and clang::Type::isBlockPointerType().
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), getCall(), and clang::ento::ExprEngine::VisitCallExpr().
Friends And Related Symbol Documentation
CallEvent
friend class CallEvent friend
Definition at line 1283 of file CallEvent.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp