clang: clang::driver::MultilibSetBuilder Class Reference
clang::driver::MultilibSetBuilder Class Reference
This class can be used to create a MultilibSet, and contains helper functions to add combinations of multilibs before creating a MultilibSet instance with makeMultilibSet().
#include "clang/Driver/MultilibBuilder.h"
Public Types
using multilib_list = std::vector<MultilibBuilder>
Public Member Functions
MultilibSetBuilder ()=default
MultilibSetBuilder & Maybe (const MultilibBuilder &M)
Add an optional Multilib segment.
MultilibSetBuilder & Either (const MultilibBuilder &M1, const MultilibBuilder &M2)
Add a set of mutually incompatible Multilib segments.
MultilibSetBuilder & Either (const MultilibBuilder &M1, const MultilibBuilder &M2, const MultilibBuilder &M3)
MultilibSetBuilder & Either (const MultilibBuilder &M1, const MultilibBuilder &M2, const MultilibBuilder &M3, const MultilibBuilder &M4)
MultilibSetBuilder & Either (const MultilibBuilder &M1, const MultilibBuilder &M2, const MultilibBuilder &M3, const MultilibBuilder &M4, const MultilibBuilder &M5)
MultilibSetBuilder & Either (ArrayRef< MultilibBuilder > Ms)
MultilibSetBuilder & FilterOut (const char *Regex)
Filter out those Multilibs whose gccSuffix matches the given expression.
MultilibSet makeMultilibSet () const
Detailed Description
This class can be used to create a MultilibSet, and contains helper functions to add combinations of multilibs before creating a MultilibSet instance with makeMultilibSet().
Definition at line 96 of file MultilibBuilder.h.
Member Typedef Documentation
multilib_list
using clang::driver::MultilibSetBuilder::multilib_list = std::vector<MultilibBuilder>
Definition at line 98 of file MultilibBuilder.h.
Constructor & Destructor Documentation
MultilibSetBuilder()
clang::driver::MultilibSetBuilder::MultilibSetBuilder () default
Member Function Documentation
Either() [1/5]
MultilibSetBuilder & MultilibSetBuilder::Either (ArrayRef< MultilibBuilder > Ms)
Definition at line 155 of file MultilibBuilder.cpp.
References compose(), and clang::driver::MultilibBuilder::isValid().
Either() [2/5]
MultilibSetBuilder & MultilibSetBuilder::Either (const MultilibBuilder & M1, const MultilibBuilder & M2)
Add a set of mutually incompatible Multilib segments.
Definition at line 108 of file MultilibBuilder.cpp.
References Either().
Referenced by Either(), Either(), Either(), Either(), findAndroidArmMultilibs(), findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), findMipsMtiMultilibs(), findMipsMuslMultilibs(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), findRISCVMultilibs(), and Maybe().
Either() [3/5]
MultilibSetBuilder & MultilibSetBuilder::Either (const MultilibBuilder & M1, const MultilibBuilder & M2, const MultilibBuilder & M3)
Definition at line 113 of file MultilibBuilder.cpp.
References Either().
Either() [4/5]
MultilibSetBuilder & MultilibSetBuilder::Either (const MultilibBuilder & M1, const MultilibBuilder & M2, const MultilibBuilder & M3, const MultilibBuilder & M4)
Definition at line 119 of file MultilibBuilder.cpp.
References Either().
Either() [5/5]
MultilibSetBuilder & MultilibSetBuilder::Either (const MultilibBuilder & M1, const MultilibBuilder & M2, const MultilibBuilder & M3, const MultilibBuilder & M4, const MultilibBuilder & M5)
Definition at line 126 of file MultilibBuilder.cpp.
References Either().
FilterOut()
MultilibSetBuilder & MultilibSetBuilder::FilterOut (const char * Regex)
Filter out those Multilibs whose gccSuffix matches the given expression.
Definition at line 176 of file MultilibBuilder.cpp.
References clang::Error, and clang::driver::MultilibBuilder::gccSuffix().
Referenced by findMipsCsMultilibs(), findMipsMtiMultilibs(), and findRISCVMultilibs().
makeMultilibSet()
MultilibSet MultilibSetBuilder::makeMultilibSet () const
Definition at line 191 of file MultilibBuilder.cpp.
References clang::Result.
Referenced by findAndroidArmMultilibs(), findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), findMipsMtiMultilibs(), findMipsMuslMultilibs(), findRISCVBareMetalMultilibs(), and findRISCVMultilibs().
Maybe()
MultilibSetBuilder & MultilibSetBuilder::Maybe (const MultilibBuilder & M)
Add an optional Multilib segment.
Definition at line 98 of file MultilibBuilder.cpp.
References Either(), clang::driver::MultilibBuilder::flag(), and clang::driver::MultilibBuilder::flags().
Referenced by findCSKYMultilibs(), findMipsAndroidMultilibs(), findMipsCsMultilibs(), findMipsImgMultilibs(), and findMipsMtiMultilibs().
The documentation for this class was generated from the following files:
include/clang/Driver/MultilibBuilder.h
lib/Driver/MultilibBuilder.cpp