clang: clang::OMPDeviceClause Class Reference
clang::OMPDeviceClause Class Reference
This represents 'device' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr *E, Stmt *HelperE, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Build 'device' clause.
OMPDeviceClause ()
Build an empty clause.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getDevice ()
Return device number.
Expr * getDevice () const
Return device number.
OpenMPDeviceClauseModifier getModifier () const
Gets modifier.
SourceLocation getModifierLoc () const
Gets modifier location.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'device' clause in the '#pragma omp ...' directive.
#pragma omp target device(a)
In this example directive '#pragma omp target' has clause 'device' with single expression 'a'.
Definition at line 4938 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPDeviceClause() [1/2]
clang::OMPDeviceClause::OMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr * E, Stmt * HelperE, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc) inline
Build 'device' clause.
Parameters
Modifier Clause modifier.
E Expression associated with this clause.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
ModifierLoc Modifier location.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 4975 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPDeviceClause() [2/2]
clang::OMPDeviceClause::OMPDeviceClause () inline
Build an empty clause.
Definition at line 4986 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPDeviceClause::children () inline
Definition at line 5008 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPDeviceClause::children () const inline
Definition at line 5010 of file OpenMPClause.h.
classof()
static bool clang::OMPDeviceClause::classof (const OMPClause * T) inline static
Definition at line 5021 of file OpenMPClause.h.
getDevice() [1/2]
Expr * clang::OMPDeviceClause::getDevice () inline
Return device number.
Definition at line 4997 of file OpenMPClause.h.
References clang::cast().
getDevice() [2/2]
Expr * clang::OMPDeviceClause::getDevice () const inline
Return device number.
Definition at line 5000 of file OpenMPClause.h.
References clang::cast().
getLParenLoc()
SourceLocation clang::OMPDeviceClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 4994 of file OpenMPClause.h.
getModifier()
OpenMPDeviceClauseModifier clang::OMPDeviceClause::getModifier () const inline
Gets modifier.
Definition at line 5003 of file OpenMPClause.h.
getModifierLoc()
SourceLocation clang::OMPDeviceClause::getModifierLoc () const inline
Gets modifier location.
Definition at line 5006 of file OpenMPClause.h.
setLParenLoc()
void clang::OMPDeviceClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 4991 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPDeviceClause::used_children () inline
Definition at line 5014 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPDeviceClause::used_children () const inline
Definition at line 5017 of file OpenMPClause.h.
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 4939 of file OpenMPClause.h.
The documentation for this class was generated from the following file:
include/clang/AST/OpenMPClause.h