clang: clang::extractapi::APISetVisitor< Derived > Class Template Reference
clang::extractapi::APISetVisitor< Derived > Class Template Reference
The base interface of visitors for API information.
#include "clang/ExtractAPI/Serialization/SerializerBase.h"
Public Member Functions
void traverseAPISet ()
void traverseGlobalFunctionRecords ()
void traverseGlobalVariableRecords ()
void traverseEnumRecords ()
void traverseStructRecords ()
void traverseObjCInterfaces ()
void traverseObjCProtocols ()
void traverseMacroDefinitionRecords ()
void traverseTypedefRecords ()
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitStructRecord (const StructRecord &Record)
Visit a struct record.
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
APISetVisitor ()=delete
APISetVisitor (const APISetVisitor &)=delete
APISetVisitor (APISetVisitor &&)=delete
APISetVisitor & operator= (const APISetVisitor &)=delete
APISetVisitor & operator= (APISetVisitor &&)=delete
Protected Member Functions
APISetVisitor (const APISet &API)
~APISetVisitor ()=default
Derived * getDerived ()
Protected Attributes
const APISet & API
Detailed Description
template<typename Derived>
class clang::extractapi::APISetVisitor< Derived >
The base interface of visitors for API information.
Definition at line 23 of file SerializerBase.h.
Constructor & Destructor Documentation
APISetVisitor() [1/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor () delete
APISetVisitor() [2/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (const APISetVisitor< Derived > &) delete
APISetVisitor() [3/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (APISetVisitor< Derived > &&) delete
APISetVisitor() [4/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (const APISet & API) inline protected
Definition at line 115 of file SerializerBase.h.
~APISetVisitor()
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::~APISetVisitor () protected default
Member Function Documentation
getDerived()
template<typename Derived > Derived * clang::extractapi::APISetVisitor< Derived >::getDerived () inline protected
Definition at line 118 of file SerializerBase.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseAPISet(), clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords(), clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols(), clang::extractapi::APISetVisitor< Derived >::traverseStructRecords(), and clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords().
operator=() [1/2]
template<typename Derived > APISetVisitor & clang::extractapi::APISetVisitor< Derived >::operator= (APISetVisitor< Derived > &&) delete
operator=() [2/2]
template<typename Derived > APISetVisitor & clang::extractapi::APISetVisitor< Derived >::operator= (const APISetVisitor< Derived > &) delete
traverseAPISet()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseAPISet () inline
Definition at line 25 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseEnumRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords () inline
Definition at line 53 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, Enum, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getEnums().
traverseGlobalFunctionRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords () inline
Definition at line 43 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalFunctions().
traverseGlobalVariableRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords () inline
Definition at line 48 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalVariables().
traverseMacroDefinitionRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords () inline
Definition at line 73 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getMacros().
traverseObjCInterfaces()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces () inline
Definition at line 63 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getObjCInterfaces().
traverseObjCProtocols()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols () inline
Definition at line 68 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getObjCProtocols().
traverseStructRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseStructRecords () inline
Definition at line 58 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getStructs().
traverseTypedefRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords () inline
Definition at line 78 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getTypedefs().
visitEnumRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitEnumRecord (const EnumRecord & Record) inline
Visit an enum record.
Definition at line 90 of file SerializerBase.h.
visitGlobalFunctionRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalFunctionRecord (const GlobalFunctionRecord & Record) inline
Visit a global function record.
Definition at line 84 of file SerializerBase.h.
visitGlobalVariableRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalVariableRecord (const GlobalVariableRecord & Record) inline
Visit a global variable record.
Definition at line 87 of file SerializerBase.h.
visitMacroDefinitionRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitMacroDefinitionRecord (const MacroDefinitionRecord & Record) inline
Visit a macro definition record.
Definition at line 99 of file SerializerBase.h.
visitObjCContainerRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitObjCContainerRecord (const ObjCContainerRecord & Record) inline
Visit an Objective-C container record.
Definition at line 96 of file SerializerBase.h.
visitStructRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitStructRecord (const StructRecord & Record) inline
Visit a struct record.
Definition at line 93 of file SerializerBase.h.
visitTypedefRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitTypedefRecord (const TypedefRecord & Record) inline
Visit a typedef record.
Definition at line 102 of file SerializerBase.h.
Member Data Documentation
API
template<typename Derived > const APISet& clang::extractapi::APISetVisitor< Derived >::API protected
Definition at line 105 of file SerializerBase.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords(), clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols(), clang::extractapi::APISetVisitor< Derived >::traverseStructRecords(), and clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords().
The documentation for this class was generated from the following file:
include/clang/ExtractAPI/Serialization/SerializerBase.h