clang: clang::dataflow::Environment Class Reference
clang::dataflow::Environment Class Reference
Holds the state of the program (store and heap) at a given program point.
#include "clang/Analysis/FlowSensitive/DataflowEnvironment.h"
Classes
class ValueModel
Supplements Environment with non-standard comparison and join operations.
Public Member Functions
Environment (DataflowAnalysisContext &DACtx)
Creates an environment that uses DACtx to store objects that encompass the state of a program.
Environment & operator= (const Environment &Other)=delete
Environment (Environment &&Other)=default
Environment & operator= (Environment &&Other)=default
Environment (DataflowAnalysisContext &DACtx, const DeclContext &DeclCtx)
Creates an environment that uses DACtx to store objects that encompass the state of a program.
Environment fork () const
Returns a new environment that is a copy of this one.
Environment pushCall (const CallExpr *Call) const
Creates and returns an environment to use for an inline analysis of the callee.
Environment pushCall (const CXXConstructExpr *Call) const
void popCall (const CallExpr *Call, const Environment &CalleeEnv)
Moves gathered information back into this from a CalleeEnv created via pushCall.
void popCall (const CXXConstructExpr *Call, const Environment &CalleeEnv)
bool equivalentTo (const Environment &Other, Environment::ValueModel &Model) const
Returns true if and only if the environment is equivalent to Other, i.e the two environments:
LatticeJoinEffect widen (const Environment &PrevEnv, Environment::ValueModel &Model)
Widens the environment point-wise, using PrevEnv as needed to inform the approximation.
StorageLocation & createStorageLocation (QualType Type)
Creates a storage location appropriate for Type.
StorageLocation & createStorageLocation (const VarDecl &D)
Creates a storage location for D.
StorageLocation & createStorageLocation (const Expr &E)
Creates a storage location for E.
void setStorageLocation (const ValueDecl &D, StorageLocation &Loc)
Assigns Loc as the storage location of D in the environment.
StorageLocation * getStorageLocation (const ValueDecl &D) const
Returns the storage location assigned to D in the environment, or null if D isn't assigned a storage location in the environment.
void setStorageLocation (const Expr &E, StorageLocation &Loc)
Assigns Loc as the storage location of E in the environment.
void setStorageLocationStrict (const Expr &E, StorageLocation &Loc)
Assigns Loc as the storage location of the glvalue E in the environment.
StorageLocation * getStorageLocation (const Expr &E, SkipPast SP) const
Returns the storage location assigned to E in the environment, applying the SP policy for skipping past indirections, or null if E isn't assigned a storage location in the environment.
StorageLocation * getStorageLocationStrict (const Expr &E) const
Returns the storage location assigned to the glvalue E in the environment, or null if E isn't assigned a storage location in the environment.
AggregateStorageLocation * getThisPointeeStorageLocation () const
Returns the storage location assigned to the this pointee in the environment or null if the this pointee has no assigned storage location in the environment.
AggregateStorageLocation & getResultObjectLocation (const Expr &RecordPRValue)
Returns the location of the result object for a record-type prvalue.
Value * getReturnValue () const
Returns the return value of the current function.
StorageLocation * getReturnStorageLocation () const
Returns the storage location for the reference returned by the current function.
void setReturnValue (Value *Val)
Sets the return value of the current function.
void setReturnStorageLocation (StorageLocation *Loc)
Sets the storage location for the reference returned by the current function.
PointerValue & getOrCreateNullPointerValue (QualType PointeeType)
Returns a pointer value that represents a null pointer.
Value * createValue (QualType Type)
Creates a value appropriate for Type, if Type is supported, otherwise returns null.
StorageLocation & createObject (QualType Ty, const Expr *InitExpr=nullptr)
Creates an object (i.e.
StorageLocation & createObject (const VarDecl &D)
Creates an object for the variable declaration D.
StorageLocation & createObject (const VarDecl &D, const Expr *InitExpr)
Creates an object for the variable declaration D.
void setValue (const StorageLocation &Loc, Value &Val)
Assigns Val as the value of Loc in the environment.
void clearValue (const StorageLocation &Loc)
Clears any association between Loc and a value in the environment.
void setValueStrict (const Expr &E, Value &Val)
Assigns Val as the value of the prvalue E in the environment.
Value * getValue (const StorageLocation &Loc) const
Returns the value assigned to Loc in the environment or null if Loc isn't assigned a value in the environment.
Value * getValue (const ValueDecl &D) const
Equivalent to getValue(getStorageLocation(D, SP), SkipPast::None) if D is assigned a storage location in the environment, otherwise returns null.
Value * getValue (const Expr &E, SkipPast SP) const
Equivalent to getValue(getStorageLocation(E, SP), SkipPast::None) if E is assigned a storage location in the environment, otherwise returns null.
Value * getValueStrict (const Expr &E) const
Returns the Value assigned to the prvalue E in the environment, or null if E isn't assigned a value in the environment.
template<typename T , typename... Args>
std::enable_if_t< std::is_base_of< Value, T >::value, T & > create (Args &&...args)
Creates a T (some subclass of Value), forwarding args to the constructor, and returns a reference to it.
IntegerValue & getIntLiteralValue (llvm::APInt Value) const
Returns a symbolic integer value that models an integer literal equal to Value
AtomicBoolValue & getBoolLiteralValue (bool Value) const
Returns a symbolic boolean value that models a boolean literal equal to Value
BoolValue & makeAtomicBoolValue () const
Returns an atomic boolean value.
BoolValue & makeTopBoolValue () const
Returns a unique instance of boolean Top.
BoolValue & makeAnd (BoolValue &LHS, BoolValue &RHS) const
Returns a boolean value that represents the conjunction of LHS and RHS.
BoolValue & makeOr (BoolValue &LHS, BoolValue &RHS) const
Returns a boolean value that represents the disjunction of LHS and RHS.
BoolValue & makeNot (BoolValue &Val) const
Returns a boolean value that represents the negation of Val.
BoolValue & makeImplication (BoolValue &LHS, BoolValue &RHS) const
Returns a boolean value represents LHS => RHS.
BoolValue & makeIff (BoolValue &LHS, BoolValue &RHS) const
Returns a boolean value represents LHS <=> RHS.
Atom getFlowConditionToken () const
Returns a boolean variable that identifies the flow condition (FC).
void addToFlowCondition (const Formula &)
Record a fact that must be true if this point in the program is reached.
bool flowConditionImplies (const Formula &) const
Returns true if the formula is always true when this point is reached.
const DeclContext * getDeclCtx () const
Returns the DeclContext of the block being analysed, if any.
const FunctionDecl * getCurrentFunc () const
Returns the function currently being analyzed, or null if the code being analyzed isn't part of a function.
bool canDescend (unsigned MaxDepth, const DeclContext *Callee) const
Returns whether this Environment can be extended to analyze the given Callee (i.e.
DataflowAnalysisContext & getDataflowAnalysisContext () const
Returns the DataflowAnalysisContext used by the environment.
Arena & arena () const
LLVM_DUMP_METHOD void dump () const
LLVM_DUMP_METHOD void dump (raw_ostream &OS) const
Static Public Member Functions
static Environment join (const Environment &EnvA, const Environment &EnvB, Environment::ValueModel &Model)
Joins two environments by taking the intersection of storage locations and values that are stored in them.
Detailed Description
Holds the state of the program (store and heap) at a given program point.
WARNING: Symbolic values that are created by the environment for static local and global variables are not currently invalidated on function calls. This is unsound and should be taken into account when designing dataflow analyses.
Definition at line 66 of file DataflowEnvironment.h.
Constructor & Destructor Documentation
Environment() [1/3]
clang::dataflow::Environment::Environment (DataflowAnalysisContext & DACtx) explicit
Creates an environment that uses DACtx to store objects that encompass the state of a program.
Definition at line 293 of file DataflowEnvironment.cpp.
Environment() [2/3]
clang::dataflow::Environment::Environment (Environment && Other) default
Environment() [3/3]
clang::dataflow::Environment::Environment (DataflowAnalysisContext & DACtx, const DeclContext & DeclCtx)
Creates an environment that uses DACtx to store objects that encompass the state of a program.
If DeclCtx is a function, initializes the environment with symbolic representations of the function parameters.
If DeclCtx is a non-static member function, initializes the environment with a symbolic representation of the this pointee.
Definition at line 303 of file DataflowEnvironment.cpp.
References clang::cast(), createObject(), createValue(), clang::FunctionDecl::getBody(), clang::FunctionDecl::parameters(), Parent, and setStorageLocation().
Member Function Documentation
addToFlowCondition()
void clang::dataflow::Environment::addToFlowCondition (const Formula & Val)
Record a fact that must be true if this point in the program is reached.
Definition at line 914 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::addFlowConditionConstraint().
Referenced by clang::dataflow::UncheckedOptionalAccessModel::merge(), and clang::dataflow::mergeDistinctValues().
arena()
Arena & clang::dataflow::Environment::arena () const inline
Definition at line 638 of file DataflowEnvironment.h.
References clang::dataflow::DataflowAnalysisContext::arena().
Referenced by create(), getBoolLiteralValue(), getIntLiteralValue(), makeAnd(), makeAtomicBoolValue(), makeIff(), makeImplication(), makeNot(), makeOr(), makeTopBoolValue(), clang::dataflow::UncheckedOptionalAccessModel::merge(), and clang::dataflow::mergeDistinctValues().
canDescend()
bool clang::dataflow::Environment::canDescend (unsigned MaxDepth, const DeclContext * Callee) const
Returns whether this Environment can be extended to analyze the given Callee (i.e.
if pushCall can be used), with recursion disallowed and a given MaxDepth.
Definition at line 334 of file DataflowEnvironment.cpp.
clearValue()
void clang::dataflow::Environment::clearValue (const StorageLocation & Loc) inline
Clears any association between Loc and a value in the environment.
Definition at line 464 of file DataflowEnvironment.h.
create()
template<typename T , typename... Args> std::enable_if_t< std::is_base_of< Value, T >::value, T & > clang::dataflow::Environment::create (Args &&... args) inline
Creates a T (some subclass of Value), forwarding args to the constructor, and returns a reference to it.
The analysis context takes ownership of the created object. The object will be destroyed when the analysis context is destroyed.
Definition at line 527 of file DataflowEnvironment.h.
References arena(), and clang::dataflow::Arena::create().
Referenced by clang::dataflow::mergeDistinctValues(), clang::dataflow::refreshStructValue(), and clang::dataflow::refreshStructValue().
createObject() [1/3]
StorageLocation & clang::dataflow::Environment::createObject (const VarDecl & D) inline
Creates an object for the variable declaration D.
If D has an initializer and this initializer is associated with a value, initializes the object with this value. Otherwise, initializes the object with a value created using createValue(). Uses the storage location returned by DataflowAnalysisContext::getStableStorageLocation(D).
Definition at line 447 of file DataflowEnvironment.h.
References clang::VarDecl::getInit(), and clang::ValueDecl::getType().
createObject() [2/3]
StorageLocation & clang::dataflow::Environment::createObject (const VarDecl & D, const Expr * InitExpr) inline
Creates an object for the variable declaration D.
If InitExpr is non-null and has a value associated with it, initializes the object with this value. Otherwise, initializes the object with a value created using createValue(). Uses the storage location returned by DataflowAnalysisContext::getStableStorageLocation(D).
Definition at line 456 of file DataflowEnvironment.h.
References clang::ValueDecl::getType().
createObject() [3/3]
StorageLocation & clang::dataflow::Environment::createObject (QualType Ty, const Expr * InitExpr = nullptr) inline
Creates an object (i.e.
a storage location with an associated value) of type Ty. If InitExpr is non-null and has a value associated with it, initializes the object with this value. Otherwise, initializes the object with a value created using createValue().
Definition at line 438 of file DataflowEnvironment.h.
Referenced by Environment().
createStorageLocation() [1/3]
StorageLocation & clang::dataflow::Environment::createStorageLocation (const Expr & E)
Creates a storage location for E.
Does not assign the returned storage location to E in the environment. Does not assign a value to the returned storage location in the environment.
Definition at line 605 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::getStableStorageLocation().
createStorageLocation() [2/3]
StorageLocation & clang::dataflow::Environment::createStorageLocation (const VarDecl & D)
Creates a storage location for D.
Does not assign the returned storage location to D in the environment. Does not assign a value to the returned storage location in the environment.
Definition at line 598 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::getStableStorageLocation().
createStorageLocation() [3/3]
StorageLocation & clang::dataflow::Environment::createStorageLocation (QualType Type)
Creates a storage location appropriate for Type.
Does not assign a value to the returned storage location in the environment.
Requirements:
Type must not be null.
Definition at line 594 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::createStorageLocation().
Referenced by setValueStrict().
createValue()
Value * clang::dataflow::Environment::createValue (QualType Type)
Creates a value appropriate for Type, if Type is supported, otherwise returns null.
If Type is a pointer or reference type, creates all the necessary storage locations and values for indirections until it finds a non-pointer/non-reference type.
If Type is a class, struct, or union type, calls setValue() to associate the StructValue with its storage location (StructValue::getAggregateLoc()).
If Type is one of the following types, this function will always return a non-null pointer:
bool
Any integer type
Any class, struct, or union type
Requirements:
Type must not be null.
Definition at line 747 of file DataflowEnvironment.cpp.
References clang::dataflow::MaxCompositeValueSize, and Visited.
Referenced by Environment(), clang::dataflow::mergeDistinctValues(), and clang::dataflow::refreshStructValue().
dump() [1/2]
void clang::dataflow::Environment::dump () const
Definition at line 942 of file DataflowEnvironment.cpp.
References dump().
Referenced by dump(), and clang::dataflow::runTypeErasedDataflowAnalysis().
dump() [2/2]
void clang::dataflow::Environment::dump (raw_ostream & OS) const
Definition at line 922 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::dumpFlowCondition(), and V.
equivalentTo()
bool clang::dataflow::Environment::equivalentTo (const Environment & Other, Environment::ValueModel & Model) const
Returns true if and only if the environment is equivalent to Other, i.e the two environments:
have the same mappings from declarations to storage locations,
have the same mappings from expressions to storage locations,
have the same or equivalent (according to Model) values assigned to the same storage locations.
Requirements:
Other and this must use the same DataflowAnalysisContext.
Definition at line 423 of file DataflowEnvironment.cpp.
References clang::dataflow::areEquivalentValues(), clang::dataflow::compareDistinctValues(), and clang::dataflow::StorageLocation::getType().
flowConditionImplies()
bool clang::dataflow::Environment::flowConditionImplies (const Formula & Val) const
Returns true if the formula is always true when this point is reached.
Returns false if the formula may be false, or if the flow condition isn't sufficiently precise to prove that it is true.
Definition at line 918 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::flowConditionImplies().
fork()
Environment clang::dataflow::Environment::fork () const
Returns a new environment that is a copy of this one.
The state of the program is initially the same, but can be mutated without affecting the original.
However the original should not be further mutated, as this may interfere with the fork. (In practice, values are stored independently, but the forked flow condition references the original).
Definition at line 297 of file DataflowEnvironment.cpp.
References clang::Copy, and clang::dataflow::DataflowAnalysisContext::forkFlowCondition().
Referenced by clang::dataflow::TypeErasedDataflowAnalysisState::fork(), and clang::dataflow::runTypeErasedDataflowAnalysis().
getBoolLiteralValue()
AtomicBoolValue & clang::dataflow::Environment::getBoolLiteralValue (bool Value) const inline
Returns a symbolic boolean value that models a boolean literal equal to Value
Definition at line 539 of file DataflowEnvironment.h.
References arena(), and clang::cast().
Referenced by clang::dataflow::evaluateBooleanEquality().
getCurrentFunc()
const FunctionDecl * clang::dataflow::Environment::getCurrentFunc () const inline
Returns the function currently being analyzed, or null if the code being analyzed isn't part of a function.
Definition at line 626 of file DataflowEnvironment.h.
References getDeclCtx().
Referenced by getReturnStorageLocation(), getReturnValue(), setReturnStorageLocation(), and setReturnValue().
getDataflowAnalysisContext()
DataflowAnalysisContext & clang::dataflow::Environment::getDataflowAnalysisContext () const inline
Returns the DataflowAnalysisContext used by the environment.
Definition at line 636 of file DataflowEnvironment.h.
Referenced by clang::dataflow::unpackValue().
getDeclCtx()
const DeclContext * clang::dataflow::Environment::getDeclCtx () const inline
Returns the DeclContext of the block being analysed, if any.
Otherwise, returns null.
Definition at line 622 of file DataflowEnvironment.h.
Referenced by getCurrentFunc().
getFlowConditionToken()
Atom clang::dataflow::Environment::getFlowConditionToken () const inline
Returns a boolean variable that identifies the flow condition (FC).
The flow condition is a set of facts that are necessarily true when the program reaches the current point, expressed as boolean formulas. The flow condition token is equivalent to the AND of these facts.
These may e.g. constrain the value of certain variables. A pointer variable may have a consistent modeled PointerValue throughout, but at a given point the Environment may tell us that the value must be non-null.
The FC is necessary but not sufficient for this point to be reachable. In particular, where the FC token appears in flow conditions of successor environments, it means "point X may have been reached", not "point X was reached".
Definition at line 610 of file DataflowEnvironment.h.
Referenced by clang::dataflow::mergeDistinctValues().
getIntLiteralValue()
IntegerValue & clang::dataflow::Environment::getIntLiteralValue (llvm::APInt Value) const inline
Returns a symbolic integer value that models an integer literal equal to Value
Definition at line 533 of file DataflowEnvironment.h.
References arena(), and clang::dataflow::Arena::makeIntLiteral().
getOrCreateNullPointerValue()
PointerValue & clang::dataflow::Environment::getOrCreateNullPointerValue (QualType PointeeType)
Returns a pointer value that represents a null pointer.
Calls with PointeeType that are canonically equivalent will return the same result.
Definition at line 686 of file DataflowEnvironment.cpp.
References clang::dataflow::DataflowAnalysisContext::getOrCreateNullPointerValue().
getResultObjectLocation()
AggregateStorageLocation & clang::dataflow::Environment::getResultObjectLocation (const Expr & RecordPRValue)
Returns the location of the result object for a record-type prvalue.
In C++, prvalues of record type serve only a limited purpose: They can only be used to initialize a result object (e.g. a variable or a temporary). This function returns the location of that result object.
When creating a prvalue of record type, we already need the storage location of the result object to pass in this, even though prvalues are otherwise not associated with storage locations.
FIXME: Currently, this simply returns a stable storage location for E, but this doesn't do the right thing in scenarios like the following:
MyClass c = some_condition()? MyClass(foo) : MyClass(bar);
Here, MyClass(foo) and MyClass(bar) will have two different storage locations, when in fact their storage locations should be the same. Eventually, we want to propagate storage locations from result objects down to the prvalues that initialize them, similar to the way that this is done in Clang's CodeGen.
Requirements: E must be a prvalue of record type.
Definition at line 673 of file DataflowEnvironment.cpp.
References clang::cast(), clang::dataflow::DataflowAnalysisContext::getStableStorageLocation(), getStorageLocation(), clang::Expr::getType(), clang::Expr::isPRValue(), clang::Type::isRecordType(), clang::dataflow::None, and setStorageLocation().
getReturnStorageLocation()
StorageLocation * clang::dataflow::Environment::getReturnStorageLocation () const inline
Returns the storage location for the reference returned by the current function.
This can be null if function doesn't return a single consistent reference.
Requirements: The current function must have a reference return type.
Definition at line 381 of file DataflowEnvironment.h.
References getCurrentFunc().
getReturnValue()
Value * clang::dataflow::Environment::getReturnValue () const inline
Returns the return value of the current function.
This can be null if:
The function has a void return type
No return value could be determined for the function, for example because it calls a function without a body.
Requirements: The current function must have a non-reference return type.
Definition at line 369 of file DataflowEnvironment.h.
References getCurrentFunc().
getStorageLocation() [1/2]
StorageLocation * clang::dataflow::Environment::getStorageLocation (const Expr & E, SkipPast SP) const
Returns the storage location assigned to E in the environment, applying the SP policy for skipping past indirections, or null if E isn't assigned a storage location in the environment.
This function is deprecated; prefer getStorageLocationStrict(). For details, see https://discourse.llvm.org/t/70086.
Definition at line 646 of file DataflowEnvironment.cpp.
References clang::dataflow::ignoreCFGOmittedNodes().
getStorageLocation() [2/2]
StorageLocation * clang::dataflow::Environment::getStorageLocation (const ValueDecl & D) const
Returns the storage location assigned to D in the environment, or null if D isn't assigned a storage location in the environment.
Note that if D has reference type, the storage location that is returned refers directly to the referenced object, not a ReferenceValue.
Definition at line 618 of file DataflowEnvironment.cpp.
References getValue().
Referenced by clang::dataflow::getBaseObjectLocation(), clang::dataflow::getImplicitObjectLocation(), getResultObjectLocation(), getStorageLocationStrict(), getValue(), getValue(), pushCall(), and setValueStrict().
getStorageLocationStrict()
StorageLocation * clang::dataflow::Environment::getStorageLocationStrict (const Expr & E) const
Returns the storage location assigned to the glvalue E in the environment, or null if E isn't assigned a storage location in the environment.
If the storage location for E is associated with a ReferenceValue RefVal, returns RefVal.getReferentLoc() instead.
This function is the preferred alternative to getStorageLocation(const Expr &, SkipPast). Once the migration to strict handling of value categories is complete (see https://discourse.llvm.org/t/70086), getStorageLocation() will be removed and this function will be renamed to getStorageLocation().
Requirements: E must be a glvalue or a BuiltinType::BuiltinFn
Definition at line 653 of file DataflowEnvironment.cpp.
References getStorageLocation(), clang::Expr::getType(), getValue(), clang::Expr::isGLValue(), clang::Type::isSpecificBuiltinType(), and clang::dataflow::None.
Referenced by clang::dataflow::builtinTransferInitializer(), clang::dataflow::maybeUnpackLValueExpr(), clang::dataflow::propagateStorageLocation(), and clang::dataflow::refreshStructValue().
getThisPointeeStorageLocation()
AggregateStorageLocation * clang::dataflow::Environment::getThisPointeeStorageLocation () const
Returns the storage location assigned to the this pointee in the environment or null if the this pointee has no assigned storage location in the environment.
Definition at line 668 of file DataflowEnvironment.cpp.
Referenced by clang::dataflow::builtinTransferInitializer().
getValue() [1/3]
Value * clang::dataflow::Environment::getValue (const Expr & E, SkipPast SP) const
Equivalent to getValue(getStorageLocation(E, SP), SkipPast::None) if E is assigned a storage location in the environment, otherwise returns null.
This function is deprecated; prefer getValueStrict(). For details, see https://discourse.llvm.org/t/70086.
Definition at line 731 of file DataflowEnvironment.cpp.
References getStorageLocation(), and getValue().
getValue() [2/3]
Value * clang::dataflow::Environment::getValue (const StorageLocation & Loc) const
Returns the value assigned to Loc in the environment or null if Loc isn't assigned a value in the environment.
Definition at line 720 of file DataflowEnvironment.cpp.
Referenced by clang::dataflow::getBaseObjectLocation(), clang::dataflow::getImplicitObjectLocation(), getStorageLocation(), getStorageLocationStrict(), getValue(), getValue(), getValueStrict(), clang::dataflow::maybeUnpackLValueExpr(), popCall(), clang::dataflow::recordsEqual(), and setStorageLocation().
getValue() [3/3]
Value * clang::dataflow::Environment::getValue (const ValueDecl & D) const
Equivalent to getValue(getStorageLocation(D, SP), SkipPast::None) if D is assigned a storage location in the environment, otherwise returns null.
Definition at line 724 of file DataflowEnvironment.cpp.
References getStorageLocation(), and getValue().
getValueStrict()
Value * clang::dataflow::Environment::getValueStrict (const Expr & E) const
Returns the Value assigned to the prvalue E in the environment, or null if E isn't assigned a value in the environment.
This function is the preferred alternative to getValue(const Expr &, SkipPast). Once the migration to strict handling of value categories is complete (see https://discourse.llvm.org/t/70086), getValue() will be removed and this function will be renamed to getValue().
Requirements:
E must be a prvalue
Definition at line 738 of file DataflowEnvironment.cpp.
References getValue(), clang::Expr::isPRValue(), and clang::dataflow::None.
Referenced by clang::dataflow::builtinTransferInitializer(), clang::dataflow::evaluateBooleanEquality(), clang::dataflow::propagateValue(), clang::dataflow::refreshStructValue(), and setValueStrict().
join()
Environment clang::dataflow::Environment::join (const Environment & EnvA, const Environment & EnvB, Environment::ValueModel & Model) static
Joins two environments by taking the intersection of storage locations and values that are stored in them.
Distinct values that are assigned to the same storage locations in EnvA and EnvB are merged using Model.
Requirements:
EnvA and EnvB must use the same DataflowAnalysisContext.
Definition at line 516 of file DataflowEnvironment.cpp.
References clang::dataflow::areEquivalentValues(), clang::dataflow::StorageLocation::getType(), clang::dataflow::intersectDenseMaps(), clang::dataflow::DataflowAnalysisContext::joinFlowConditions(), and clang::dataflow::mergeDistinctValues().
makeAnd()
BoolValue & clang::dataflow::Environment::makeAnd (BoolValue & LHS, BoolValue & RHS) const inline
Returns a boolean value that represents the conjunction of LHS and RHS.
Subsequent calls with the same arguments, regardless of their order, will return the same result. If the given boolean values represent the same value, the result will be the value itself.
Definition at line 558 of file DataflowEnvironment.h.
References arena(), clang::dataflow::BoolValue::formula(), makeAnd(), and clang::dataflow::Arena::makeBoolValue().
Referenced by makeAnd().
makeAtomicBoolValue()
BoolValue & clang::dataflow::Environment::makeAtomicBoolValue () const inline
Returns an atomic boolean value.
Definition at line 545 of file DataflowEnvironment.h.
References arena(), and clang::dataflow::Arena::makeAtomValue().
Referenced by clang::dataflow::evaluateBooleanEquality(), and clang::dataflow::UncheckedOptionalAccessModel::merge().
makeIff()
BoolValue & clang::dataflow::Environment::makeIff (BoolValue & LHS, BoolValue & RHS) const inline
Returns a boolean value represents LHS <=> RHS.
Subsequent calls with the same arguments, regardless of their order, will return the same result. If the given boolean values represent the same value, the result will be a value that represents the true boolean literal.
Definition at line 591 of file DataflowEnvironment.h.
References arena(), clang::dataflow::BoolValue::formula(), and clang::dataflow::Arena::makeBoolValue().
Referenced by clang::dataflow::evaluateBooleanEquality().
makeImplication()
BoolValue & clang::dataflow::Environment::makeImplication (BoolValue & LHS, BoolValue & RHS) const inline
Returns a boolean value represents LHS => RHS.
Subsequent calls with the same arguments, will return the same result. If the given boolean values represent the same value, the result will be a value that represents the true boolean literal.
Definition at line 582 of file DataflowEnvironment.h.
References arena(), clang::dataflow::BoolValue::formula(), and clang::dataflow::Arena::makeBoolValue().
makeNot()
BoolValue & clang::dataflow::Environment::makeNot (BoolValue & Val) const inline
Returns a boolean value that represents the negation of Val.
Subsequent calls with the same argument will return the same result.
Definition at line 574 of file DataflowEnvironment.h.
References arena(), clang::dataflow::BoolValue::formula(), clang::dataflow::Arena::makeBoolValue(), and makeNot().
Referenced by makeNot().
makeOr()
BoolValue & clang::dataflow::Environment::makeOr (BoolValue & LHS, BoolValue & RHS) const inline
Returns a boolean value that represents the disjunction of LHS and RHS.
Subsequent calls with the same arguments, regardless of their order, will return the same result. If the given boolean values represent the same value, the result will be the value itself.
Definition at line 567 of file DataflowEnvironment.h.
References arena(), clang::dataflow::BoolValue::formula(), clang::dataflow::Arena::makeBoolValue(), and makeOr().
Referenced by makeOr().
makeTopBoolValue()
BoolValue & clang::dataflow::Environment::makeTopBoolValue () const inline
Returns a unique instance of boolean Top.
Definition at line 550 of file DataflowEnvironment.h.
References arena(), and clang::dataflow::Arena::makeTopValue().
Referenced by clang::dataflow::UncheckedOptionalAccessModel::widen(), and clang::dataflow::widenDistinctValues().
operator=() [1/2]
Environment & clang::dataflow::Environment::operator= (const Environment & Other) delete
operator=() [2/2]
Environment & clang::dataflow::Environment::operator= (Environment && Other) default
popCall() [1/2]
void clang::dataflow::Environment::popCall (const CallExpr * Call, const Environment & CalleeEnv)
Moves gathered information back into this from a CalleeEnv created via pushCall.
Definition at line 392 of file DataflowEnvironment.cpp.
References setStorageLocationStrict(), and setValueStrict().
popCall() [2/2]
void clang::dataflow::Environment::popCall (const CXXConstructExpr * Call, const Environment & CalleeEnv)
Definition at line 412 of file DataflowEnvironment.cpp.
References getValue(), and setValueStrict().
pushCall() [1/2]
Environment clang::dataflow::Environment::pushCall (const CallExpr * Call) const
Creates and returns an environment to use for an inline analysis of the callee.
Uses the storage location from each argument in the Call as the storage location for the corresponding parameter in the callee.
Requirements:
The callee of Call must be a FunctionDecl.
The body of the callee must not reference globals.
The arguments of Call must map 1:1 to the callee's parameters.
Definition at line 339 of file DataflowEnvironment.cpp.
References clang::cast(), Env, getStorageLocation(), and clang::dataflow::Reference.
pushCall() [2/2]
Environment clang::dataflow::Environment::pushCall (const CXXConstructExpr * Call) const
Definition at line 358 of file DataflowEnvironment.cpp.
References Env.
setReturnStorageLocation()
void clang::dataflow::Environment::setReturnStorageLocation (StorageLocation * Loc) inline
Sets the storage location for the reference returned by the current function.
Requirements: The current function must have a reference return type.
Definition at line 402 of file DataflowEnvironment.h.
References getCurrentFunc().
setReturnValue()
void clang::dataflow::Environment::setReturnValue (Value * Val) inline
Sets the return value of the current function.
Requirements: The current function must have a non-reference return type.
Definition at line 391 of file DataflowEnvironment.h.
References getCurrentFunc().
setStorageLocation() [1/2]
void clang::dataflow::Environment::setStorageLocation (const Expr & E, StorageLocation & Loc)
Assigns Loc as the storage location of E in the environment.
This function is deprecated; prefer setStorageLocationStrict(). For details, see https://discourse.llvm.org/t/70086.
Requirements:
E must not be assigned a storage location in the environment.
Definition at line 630 of file DataflowEnvironment.cpp.
References clang::dataflow::ignoreCFGOmittedNodes().
setStorageLocation() [2/2]
void clang::dataflow::Environment::setStorageLocation (const ValueDecl & D, StorageLocation & Loc)
Assigns Loc as the storage location of D in the environment.
Requirements:
D must not already have a storage location in the environment.
If D has reference type, Loc must refer directly to the referenced object (if any), not to a ReferenceValue, and it is not permitted to later change Loc to refer to a ReferenceValue.
Definition at line 612 of file DataflowEnvironment.cpp.
References getValue().
Referenced by Environment(), getResultObjectLocation(), setStorageLocationStrict(), and setValueStrict().
setStorageLocationStrict()
void clang::dataflow::Environment::setStorageLocationStrict (const Expr & E, StorageLocation & Loc)
Assigns Loc as the storage location of the glvalue E in the environment.
This function is the preferred alternative to setStorageLocation(const Expr &, StorageLocation &). Once the migration to strict handling of value categories is complete (see https://discourse.llvm.org/t/70086), setStorageLocation() will be removed and this function will be renamed to setStorageLocation().
Requirements:
E must not be assigned a storage location in the environment. E must be a glvalue or a BuiltinType::BuiltinFn
Definition at line 636 of file DataflowEnvironment.cpp.
References clang::Expr::getType(), clang::Expr::isGLValue(), clang::Type::isSpecificBuiltinType(), and setStorageLocation().
Referenced by popCall(), clang::dataflow::propagateStorageLocation(), and clang::dataflow::refreshStructValue().
setValue()
void clang::dataflow::Environment::setValue (const StorageLocation & Loc, Value & Val)
Assigns Val as the value of Loc in the environment.
Definition at line 690 of file DataflowEnvironment.cpp.
Referenced by clang::dataflow::builtinTransferInitializer(), clang::dataflow::maybeUnpackLValueExpr(), clang::dataflow::refreshStructValue(), clang::dataflow::refreshStructValue(), and setValueStrict().
setValueStrict()
void clang::dataflow::Environment::setValueStrict (const Expr & E, Value & Val)
Assigns Val as the value of the prvalue E in the environment.
If E is not yet associated with a storage location, associates it with a newly created storage location. In any case, associates the storage location of E with Val.
Once the migration to strict handling of value categories is complete (see https://discourse.llvm.org/t/70086), this function will be renamed to setValue(). At this point, prvalue expressions will be associated directly with Values, and the legacy behavior of associating prvalue expressions with storage locations (as described above) will be eliminated.
Requirements:
E must be a prvalue Val must not be a ReferenceValue If Val is a StructValue, its AggregateStorageLocation must be the same as that of any StructValue that has already been associated with E. This is to guarantee that the result object initialized by a prvalue StructValue has a durable storage location.
Definition at line 697 of file DataflowEnvironment.cpp.
References createStorageLocation(), getStorageLocation(), getValueStrict(), clang::Expr::isPRValue(), clang::dataflow::None, setStorageLocation(), and setValue().
Referenced by popCall(), popCall(), clang::dataflow::propagateValue(), and clang::dataflow::refreshStructValue().
widen()
LatticeJoinEffect clang::dataflow::Environment::widen (const Environment & PrevEnv, Environment::ValueModel & Model)
Widens the environment point-wise, using PrevEnv as needed to inform the approximation.
Requirements:
PrevEnv must be the immediate previous version of the environment. PrevEnv and this must use the same DataflowAnalysisContext.
Definition at line 464 of file DataflowEnvironment.cpp.
References clang::dataflow::areEquivalentValues(), clang::dataflow::Changed, clang::dataflow::StorageLocation::getType(), clang::dataflow::Unchanged, and clang::dataflow::widenDistinctValues().
Referenced by clang::dataflow::runTypeErasedDataflowAnalysis().
The documentation for this class was generated from the following files:
include/clang/Analysis/FlowSensitive/DataflowEnvironment.h
lib/Analysis/FlowSensitive/DataflowEnvironment.cpp