clang: clang::dataflow::BoolValue Class Reference
clang::dataflow::BoolValue Class Reference
Models a boolean.
#include "clang/Analysis/FlowSensitive/Value.h"
Public Member Functions
BoolValue (Kind ValueKind, const Formula &F)
const Formula & formula () const
Public Member Functions inherited from clang::dataflow::Value
Value (Kind ValKind)
Value (const Value &)=delete
Value & operator= (const Value &)=delete
virtual ~Value ()=default
Kind getKind () const
Value * getProperty (llvm::StringRef Name) const
Returns the value of the synthetic property with the given Name or null if the property isn't assigned a value.
void setProperty (llvm::StringRef Name, Value &Val)
Assigns Val as the value of the synthetic property with the given Name.
llvm::iterator_range< llvm::StringMap< Value * >::const_iterator > properties () const
Static Public Member Functions
static bool classof (const Value *Val)
Additional Inherited Members
Public Types inherited from clang::dataflow::Value
enum class Kind {
Integer , Reference , Pointer , Struct ,
TopBool , AtomicBool , FormulaBool
}
Detailed Description
Models a boolean.
Definition at line 93 of file Value.h.
Constructor & Destructor Documentation
BoolValue()
clang::dataflow::BoolValue::BoolValue (Kind ValueKind, const Formula & F) inline explicit
Definition at line 97 of file Value.h.
Member Function Documentation
classof()
static bool clang::dataflow::BoolValue::classof (const Value * Val) inline static
Definition at line 100 of file Value.h.
References clang::dataflow::Value::AtomicBool, clang::dataflow::Value::FormulaBool, clang::dataflow::Value::getKind(), and clang::dataflow::Value::TopBool.
formula()
const Formula & clang::dataflow::BoolValue::formula () const inline
Definition at line 106 of file Value.h.
Referenced by clang::dataflow::AtomicBoolValue::getAtom(), clang::dataflow::TopBoolValue::getAtom(), clang::dataflow::Environment::makeAnd(), clang::dataflow::Environment::makeIff(), clang::dataflow::Environment::makeImplication(), clang::dataflow::Environment::makeNot(), and clang::dataflow::Environment::makeOr().
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/Value.h