clang: clang::ODRHash Class Reference
clang::ODRHash Class Reference
#include "clang/AST/ODRHash.h"
Public Member Functions
ODRHash ()
void AddCXXRecordDecl (const CXXRecordDecl *Record)
void AddRecordDecl (const RecordDecl *Record)
void AddObjCInterfaceDecl (const ObjCInterfaceDecl *Record)
void AddFunctionDecl (const FunctionDecl *Function, bool SkipBody=false)
void AddEnumDecl (const EnumDecl *Enum)
void AddObjCProtocolDecl (const ObjCProtocolDecl *P)
void AddSubDecl (const Decl *D)
void clear ()
unsigned CalculateHash ()
void AddDecl (const Decl *D)
void AddType (const Type *T)
void AddQualType (QualType T)
void AddStmt (const Stmt *S)
void AddIdentifierInfo (const IdentifierInfo *II)
void AddNestedNameSpecifier (const NestedNameSpecifier *NNS)
void AddTemplateName (TemplateName Name)
void AddDeclarationName (DeclarationName Name, bool TreatAsDecl=false)
void AddTemplateArgument (TemplateArgument TA)
void AddTemplateParameterList (const TemplateParameterList *TPL)
void AddBoolean (bool value)
Static Public Member Functions
static bool isSubDeclToBeProcessed (const Decl *D, const DeclContext *Parent)
Detailed Description
Definition at line 41 of file ODRHash.h.
Constructor & Destructor Documentation
ODRHash()
clang::ODRHash::ODRHash () inline
Definition at line 52 of file ODRHash.h.
Member Function Documentation
AddBoolean()
void ODRHash::AddBoolean (bool value)
Definition at line 1286 of file ODRHash.cpp.
Referenced by AddCXXRecordDecl(), AddDecl(), AddDeclarationName(), AddEnumDecl(), AddFunctionDecl(), AddNestedNameSpecifier(), AddObjCInterfaceDecl(), and AddQualType().
AddCXXRecordDecl()
void ODRHash::AddCXXRecordDecl (const CXXRecordDecl * Record)
Definition at line 555 of file ODRHash.cpp.
References AddBoolean(), AddDecl(), AddQualType(), AddSubDecl(), AddTemplateParameterList(), clang::DeclContext::getParent(), clang::TemplateDecl::getTemplateParameters(), and isSubDeclToBeProcessed().
Referenced by clang::CXXRecordDecl::getODRHash().
AddDecl()
void ODRHash::AddDecl (const Decl * D)
Definition at line 783 of file ODRHash.cpp.
References AddBoolean(), AddDeclarationName(), AddTemplateArgument(), clang::Decl::getCanonicalDecl(), clang::NamedDecl::getDeclName(), clang::Decl::getKind(), and clang::Specialization.
Referenced by AddCXXRecordDecl(), AddFunctionDecl(), AddNestedNameSpecifier(), AddObjCInterfaceDecl(), AddObjCProtocolDecl(), AddRecordDecl(), AddTemplateArgument(), and AddTemplateName().
AddDeclarationName()
void ODRHash::AddDeclarationName (DeclarationName Name, bool TreatAsDecl = false)
Definition at line 34 of file ODRHash.cpp.
References AddBoolean().
Referenced by AddDecl(), AddEnumDecl(), AddObjCInterfaceDecl(), and AddObjCProtocolDecl().
AddEnumDecl()
void ODRHash::AddEnumDecl (const EnumDecl * Enum)
Definition at line 730 of file ODRHash.cpp.
References AddBoolean(), AddDeclarationName(), AddQualType(), AddSubDecl(), Enum, and isSubDeclToBeProcessed().
Referenced by clang::EnumDecl::getODRHash().
AddFunctionDecl()
void ODRHash::AddFunctionDecl (const FunctionDecl * Function, bool SkipBody = false)
Definition at line 647 of file ODRHash.cpp.
References AddBoolean(), AddDecl(), AddQualType(), AddStmt(), AddSubDecl(), AddTemplateArgument(), clang::DeclContext::getLexicalParent(), clang::DeclContext::getParent(), clang::DeclContext::isFileContext(), and isSubDeclToBeProcessed().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), and clang::FunctionDecl::getODRHash().
AddIdentifierInfo()
void ODRHash::AddIdentifierInfo (const IdentifierInfo * II)
Definition at line 29 of file ODRHash.cpp.
References clang::IdentifierInfo::getName().
Referenced by AddNestedNameSpecifier().
AddNestedNameSpecifier()
void ODRHash::AddNestedNameSpecifier (const NestedNameSpecifier * NNS)
Definition at line 112 of file ODRHash.cpp.
References AddBoolean(), AddDecl(), AddIdentifierInfo(), AddNestedNameSpecifier(), AddType(), clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getKind(), clang::NestedNameSpecifier::getPrefix(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by AddNestedNameSpecifier().
AddObjCInterfaceDecl()
void ODRHash::AddObjCInterfaceDecl (const ObjCInterfaceDecl * Record)
Definition at line 620 of file ODRHash.cpp.
References AddBoolean(), AddDecl(), AddDeclarationName(), AddSubDecl(), clang::DeclContext::decls(), clang::ObjCInterfaceDecl::getReferencedProtocols(), clang::ObjCInterfaceDecl::getSuperClass(), isSubDeclToBeProcessed(), clang::ObjCInterfaceDecl::protocols(), and clang::ObjCListBase::size().
Referenced by clang::ObjCInterfaceDecl::getODRHash().
AddObjCProtocolDecl()
void ODRHash::AddObjCProtocolDecl (const ObjCProtocolDecl * P)
Definition at line 758 of file ODRHash.cpp.
References AddDecl(), AddDeclarationName(), AddSubDecl(), isSubDeclToBeProcessed(), and P.
Referenced by clang::ObjCProtocolDecl::getODRHash().
AddQualType()
void ODRHash::AddQualType (QualType T)
Definition at line 1277 of file ODRHash.cpp.
References AddBoolean(), AddType(), clang::Qualifiers::getAsOpaqueValue(), clang::SplitQualType::Quals, and clang::SplitQualType::Ty.
Referenced by AddCXXRecordDecl(), AddEnumDecl(), AddFunctionDecl(), AddTemplateArgument(), and computeODRHash().
AddRecordDecl()
void ODRHash::AddRecordDecl (const RecordDecl * Record)
Definition at line 602 of file ODRHash.cpp.
References AddDecl(), AddSubDecl(), and isSubDeclToBeProcessed().
Referenced by clang::RecordDecl::getODRHash().
AddStmt()
void ODRHash::AddStmt (const Stmt * S)
Definition at line 24 of file ODRHash.cpp.
Referenced by AddFunctionDecl(), AddTemplateArgument(), computeODRHash(), and clang::ExplicitSpecifier::isEquivalent().
AddSubDecl()
void ODRHash::AddSubDecl (const Decl * D)
Definition at line 549 of file ODRHash.cpp.
Referenced by AddCXXRecordDecl(), AddEnumDecl(), AddFunctionDecl(), AddObjCInterfaceDecl(), AddObjCProtocolDecl(), AddRecordDecl(), AddTemplateParameterList(), and computeODRHash().
AddTemplateArgument()
void ODRHash::AddTemplateArgument (TemplateArgument TA)
Definition at line 161 of file ODRHash.cpp.
References AddDecl(), AddQualType(), AddStmt(), AddTemplateArgument(), AddTemplateName(), clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::pack_size(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
Referenced by AddDecl(), AddFunctionDecl(), AddTemplateArgument(), and computeODRHash().
AddTemplateName()
void ODRHash::AddTemplateName (TemplateName Name)
Definition at line 141 of file ODRHash.cpp.
References AddDecl(), clang::TemplateName::AssumedTemplate, clang::TemplateName::DependentTemplate, clang::TemplateName::OverloadedTemplate, clang::TemplateName::QualifiedTemplate, clang::TemplateName::SubstTemplateTemplateParm, clang::TemplateName::SubstTemplateTemplateParmPack, clang::TemplateName::Template, and clang::TemplateName::UsingTemplate.
Referenced by AddTemplateArgument().
AddTemplateParameterList()
void ODRHash::AddTemplateParameterList (const TemplateParameterList * TPL)
Definition at line 199 of file ODRHash.cpp.
References AddSubDecl(), clang::TemplateParameterList::asArray(), and clang::TemplateParameterList::size().
Referenced by AddCXXRecordDecl(), and clang::ODRDiagsEmitter::diagnoseMismatch().
AddType()
void ODRHash::AddType (const Type * T)
Definition at line 1272 of file ODRHash.cpp.
Referenced by AddNestedNameSpecifier(), and AddQualType().
CalculateHash()
unsigned ODRHash::CalculateHash ()
Definition at line 214 of file ODRHash.cpp.
References CHAR_BIT, and remainder.
Referenced by computeODRHash(), computeODRHash(), computeODRHash(), computeODRHash(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CXXRecordDecl::getODRHash(), clang::EnumDecl::getODRHash(), clang::FunctionDecl::getODRHash(), clang::ObjCInterfaceDecl::getODRHash(), clang::ObjCProtocolDecl::getODRHash(), clang::RecordDecl::getODRHash(), and clang::ExplicitSpecifier::isEquivalent().
clear()
void ODRHash::clear ()
Definition at line 208 of file ODRHash.cpp.
isSubDeclToBeProcessed()
bool ODRHash::isSubDeclToBeProcessed (const Decl * D, const DeclContext * Parent) static
Definition at line 523 of file ODRHash.cpp.
References clang::Decl::getDeclContext(), clang::Decl::getKind(), clang::Decl::isImplicit(), and Parent.
Referenced by AddCXXRecordDecl(), AddEnumDecl(), AddFunctionDecl(), AddObjCInterfaceDecl(), AddObjCProtocolDecl(), AddRecordDecl(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), and clang::ODRDiagsEmitter::diagnoseMismatch().
The documentation for this class was generated from the following files:
include/clang/AST/ODRHash.h
lib/AST/ODRHash.cpp