clang: clang::Declarator Class Reference
clang::Declarator Class Reference
Information about one declarator, including the parsed type information and the identifier.
#include "clang/Sema/DeclSpec.h"
Public Types
typedef SmallVectorImpl< DeclaratorChunk >::const_iterator type_object_iterator
typedef llvm::iterator_range< type_object_iterator > type_object_range
Public Member Functions
Declarator (const DeclSpec &DS, const ParsedAttributesView &DeclarationAttrs, DeclaratorContext C)
DS and DeclarationAttrs must outlive the Declarator.
~Declarator ()
const DeclSpec & getDeclSpec () const
getDeclSpec - Return the declaration-specifier that this declarator was declared with.
DeclSpec & getMutableDeclSpec ()
getMutableDeclSpec - Return a non-const version of the DeclSpec.
AttributePool & getAttributePool () const
const CXXScopeSpec & getCXXScopeSpec () const
getCXXScopeSpec - Return the C++ scope specifier (global scope or nested-name-specifier) that is part of the declarator-id.
CXXScopeSpec & getCXXScopeSpec ()
UnqualifiedId & getName ()
Retrieve the name specified by this declarator.
const DecompositionDeclarator & getDecompositionDeclarator () const
DeclaratorContext getContext () const
bool isPrototypeContext () const
SourceRange getSourceRange () const LLVM_READONLY
Get the source range that spans this declarator.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void SetSourceRange (SourceRange R)
void SetRangeBegin (SourceLocation Loc)
SetRangeBegin - Set the start of the source range to Loc, unless it's invalid.
void SetRangeEnd (SourceLocation Loc)
SetRangeEnd - Set the end of the source range to Loc, unless it's invalid.
void ExtendWithDeclSpec (const DeclSpec &DS)
ExtendWithDeclSpec - Extend the declarator source range to include the given declspec, unless its location is invalid.
void clear ()
Reset the contents of this Declarator.
bool mayOmitIdentifier () const
mayOmitIdentifier - Return true if the identifier is either optional or not allowed.
bool mayHaveIdentifier () const
mayHaveIdentifier - Return true if the identifier is either optional or required.
bool mayHaveDecompositionDeclarator () const
Return true if the context permits a C++17 decomposition declarator.
bool mayBeFollowedByCXXDirectInit () const
mayBeFollowedByCXXDirectInit - Return true if the declarator can be followed by a C++ direct initializer, e.g.
bool isPastIdentifier () const
isPastIdentifier - Return true if we have parsed beyond the point where the name would appear.
bool hasName () const
hasName - Whether this declarator has a name, which might be an identifier (accessible via getIdentifier()) or some kind of special C++ name (constructor, destructor, etc.), or a structured binding (which is not exactly a name, but occupies the same position).
bool isDecompositionDeclarator () const
Return whether this declarator is a decomposition declarator.
IdentifierInfo * getIdentifier () const
SourceLocation getIdentifierLoc () const
void SetIdentifier (IdentifierInfo *Id, SourceLocation IdLoc)
Set the name of this declarator to be the given identifier.
void setDecompositionBindings (SourceLocation LSquareLoc, ArrayRef< DecompositionDeclarator::Binding > Bindings, SourceLocation RSquareLoc)
Set the decomposition bindings for this declarator.
void AddTypeInfo (const DeclaratorChunk &TI, ParsedAttributes &&attrs, SourceLocation EndLoc)
AddTypeInfo - Add a chunk to this declarator.
void AddTypeInfo (const DeclaratorChunk &TI, SourceLocation EndLoc)
AddTypeInfo - Add a chunk to this declarator.
void AddInnermostTypeInfo (const DeclaratorChunk &TI)
Add a new innermost chunk to this declarator.
unsigned getNumTypeObjects () const
Return the number of types applied to this declarator.
const DeclaratorChunk & getTypeObject (unsigned i) const
Return the specified TypeInfo from this declarator.
DeclaratorChunk & getTypeObject (unsigned i)
type_object_range type_objects () const
Returns the range of type objects, from the identifier outwards.
void DropFirstTypeObject ()
const DeclaratorChunk * getInnermostNonParenChunk () const
Return the innermost (closest to the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
const DeclaratorChunk * getOutermostNonParenChunk () const
Return the outermost (furthest from the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
bool isArrayOfUnknownBound () const
isArrayOfUnknownBound - This method returns true if the declarator is a declarator for an array of unknown bound (looking through parentheses).
bool isFunctionDeclarator (unsigned &idx) const
isFunctionDeclarator - This method returns true if the declarator is a function declarator (looking through parentheses).
bool isFunctionDeclarator () const
isFunctionDeclarator - Once this declarator is fully parsed and formed, this method returns true if the identifier is a function declarator (looking through parentheses).
DeclaratorChunk::FunctionTypeInfo & getFunctionTypeInfo ()
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
const DeclaratorChunk::FunctionTypeInfo & getFunctionTypeInfo () const
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
bool isDeclarationOfFunction () const
Determine whether the declaration that will be produced from this declaration will be a function.
bool isFunctionDeclarationContext () const
Return true if this declaration appears in a context where a function declarator would be a function declaration.
bool isExpressionContext () const
Determine whether this declaration appears in a context where an expression could appear.
bool isFunctionDeclaratorAFunctionDeclaration () const
Return true if a function declarator at this position would be a function declaration.
bool hasTrailingReturnType () const
Determine whether a trailing return type was written (at any level) within this declarator.
ParsedType getTrailingReturnType () const
Get the trailing return type appearing (at any level) within this declarator.
void setTrailingRequiresClause (Expr *TRC)
Sets a trailing requires clause for this declarator.
Expr * getTrailingRequiresClause ()
Sets a trailing requires clause for this declarator.
bool hasTrailingRequiresClause () const
Determine whether a trailing requires clause was written in this declarator.
void setTemplateParameterLists (ArrayRef< TemplateParameterList * > TPLs)
Sets the template parameter lists that preceded the declarator.
ArrayRef< TemplateParameterList * > getTemplateParameterLists () const
The template parameter lists that preceded the declarator.
void setInventedTemplateParameterList (TemplateParameterList *Invented)
Sets the template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters.
TemplateParameterList * getInventedTemplateParameterList () const
The template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters, if there were any such parameters.
void takeAttributes (ParsedAttributes &attrs)
takeAttributes - Takes attributes from the given parsed-attributes set and add them to this declarator.
const ParsedAttributes & getAttributes () const
ParsedAttributes & getAttributes ()
const ParsedAttributesView & getDeclarationAttributes () const
bool hasAttributes () const
hasAttributes - do we contain any attributes?
void setAsmLabel (Expr *E)
Expr * getAsmLabel () const
void setExtension (bool Val=true)
bool getExtension () const
void setObjCIvar (bool Val=true)
bool isObjCIvar () const
void setObjCWeakProperty (bool Val=true)
bool isObjCWeakProperty () const
void setInvalidType (bool Val=true)
bool isInvalidType () const
void setGroupingParens (bool flag)
bool hasGroupingParens () const
bool isFirstDeclarator () const
SourceLocation getCommaLoc () const
void setCommaLoc (SourceLocation CL)
bool hasEllipsis () const
SourceLocation getEllipsisLoc () const
void setEllipsisLoc (SourceLocation EL)
void setFunctionDefinitionKind (FunctionDefinitionKind Val)
bool isFunctionDefinition () const
FunctionDefinitionKind getFunctionDefinitionKind () const
void setHasInitializer (bool Val=true)
bool hasInitializer () const
bool isFirstDeclarationOfMember ()
Returns true if this declares a real member and not a friend.
bool isStaticMember ()
Returns true if this declares a static member.
bool isCtorOrDtor ()
Returns true if this declares a constructor or a destructor.
void setRedeclaration (bool Val)
bool isRedeclaration () const
Friends
struct DeclaratorChunk
Detailed Description
Information about one declarator, including the parsed type information and the identifier.
When the declarator is fully formed, this is turned into the appropriate Decl object.
Declarators come in two types: normal declarators and abstract declarators. Abstract declarators are used when parsing types, and don't have an identifier. Normal declarators do have ID's.
Instances of this class should be a transient object that lives on the stack, not objects that are allocated in large quantities on the heap.
Definition at line 1850 of file DeclSpec.h.
Member Typedef Documentation
type_object_iterator
SmallVectorImpl<DeclaratorChunk>::const_iterator clang::Declarator::type_object_iterator
Definition at line 2329 of file DeclSpec.h.
type_object_range
llvm::iterator_range<type_object_iterator> clang::Declarator::type_object_range
Definition at line 2330 of file DeclSpec.h.
Constructor & Destructor Documentation
Declarator()
clang::Declarator::Declarator (const DeclSpec & DS, const ParsedAttributesView & DeclarationAttrs, DeclaratorContext C) inline
DS and DeclarationAttrs must outlive the Declarator.
In particular, take care not to pass temporary objects for these parameters.
DeclarationAttrs contains [[]] attributes from the attribute-specifier-seq at the beginning of a declaration, which appertain to the declared entity itself. Attributes with other syntax (e.g. GNU) should not be placed in this attribute list; if they occur at the beginning of a declaration, they apply to the DeclSpec and should be attached to that instead.
Here is an example of an attribute associated with a declaration:
[[deprecated]] int x, y;
This attribute appertains to all of the entities declared in the declaration, i.e. x and y in this case.
Definition at line 1961 of file DeclSpec.h.
References clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::AttributeCommonInfo::isStandardAttributeSyntax().
~Declarator()
clang::Declarator::~Declarator () inline
Definition at line 1981 of file DeclSpec.h.
References clear().
Member Function Documentation
AddInnermostTypeInfo()
void clang::Declarator::AddInnermostTypeInfo (const DeclaratorChunk & TI) inline
Add a new innermost chunk to this declarator.
Definition at line 2311 of file DeclSpec.h.
Referenced by maybeSynthesizeBlockSignature().
AddTypeInfo() [1/2]
void clang::Declarator::AddTypeInfo (const DeclaratorChunk & TI, ParsedAttributes && attrs, SourceLocation EndLoc) inline
AddTypeInfo - Add a chunk to this declarator.
Also extend the range to EndLoc, which should be the last token of the chunk. This function takes attrs by R-Value reference because it takes ownership of those attributes from the parameter.
Definition at line 2291 of file DeclSpec.h.
References getAttributePool(), clang::SourceLocation::isInvalid(), SetRangeEnd(), and clang::AttributePool::takeAllFrom().
Referenced by clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), and clang::Sema::ImplicitlyDefineFunction().
AddTypeInfo() [2/2]
void clang::Declarator::AddTypeInfo (const DeclaratorChunk & TI, SourceLocation EndLoc) inline
AddTypeInfo - Add a chunk to this declarator.
Also extend the range to EndLoc, which should be the last token of the chunk.
Definition at line 2303 of file DeclSpec.h.
References clang::SourceLocation::isInvalid(), and SetRangeEnd().
clear()
void clang::Declarator::clear () inline
Reset the contents of this Declarator.
Definition at line 2049 of file DeclSpec.h.
References clang::CXXScopeSpec::clear(), clang::DecompositionDeclarator::clear(), clang::ParsedAttributes::clear(), and clang::DeclSpec::getSourceRange().
Referenced by clang::ParsingDeclarator::clear(), and ~Declarator().
DropFirstTypeObject()
void clang::Declarator::DropFirstTypeObject () inline
Definition at line 2337 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew().
ExtendWithDeclSpec()
void clang::Declarator::ExtendWithDeclSpec (const DeclSpec & DS) inline
ExtendWithDeclSpec - Extend the declarator source range to include the given declspec, unless its location is invalid.
Adopts the range start if the current range start is invalid.
Definition at line 2040 of file DeclSpec.h.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::DeclSpec::getSourceRange(), and clang::SourceLocation::isInvalid().
getAsmLabel()
Expr * clang::Declarator::getAsmLabel () const inline
Definition at line 2624 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), and clang::Sema::ActOnVariableDeclarator().
getAttributePool()
AttributePool & clang::Declarator::getAttributePool () const inline
Definition at line 1995 of file DeclSpec.h.
References clang::ParsedAttributes::getPool().
Referenced by addContextSensitiveTypeNullability(), AddTypeInfo(), takeDeclAttributes(), and transferARCOwnershipToDeclaratorChunk().
getAttributes() [1/2]
ParsedAttributes & clang::Declarator::getAttributes () inline
Definition at line 2606 of file DeclSpec.h.
getAttributes() [2/2]
const ParsedAttributes & clang::Declarator::getAttributes () const inline
Definition at line 2605 of file DeclSpec.h.
Referenced by clang::Sema::checkUnusedDeclAttributes(), distributeFunctionTypeAttrFromDeclarator(), distributeObjCPointerTypeAttrFromDeclarator(), GetFullTypeForDeclarator(), hasAttributes(), hasParsedAttr(), clang::Sema::ProcessDeclAttributes(), and takeDeclAttributes().
getBeginLoc()
SourceLocation clang::Declarator::getBeginLoc () const inline
Definition at line 2022 of file DeclSpec.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnVariableDeclarator(), CreateNewFunctionDecl(), GetFullTypeForDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), clang::Sema::isDeclaratorFunctionLike(), clang::Sema::isLibstdcxxEagerExceptionSpecHack(), maybeSynthesizeBlockSignature(), clang::Sema::ParseTypedefDecl(), and warnAboutRedundantParens().
getCommaLoc()
SourceLocation clang::Declarator::getCommaLoc () const inline
Definition at line 2644 of file DeclSpec.h.
Referenced by warnAboutAmbiguousFunction().
getContext()
DeclaratorContext clang::Declarator::getContext () const inline
Definition at line 2011 of file DeclSpec.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnTypeName(), clang::Sema::CodeCompleteFunctionQualifiers(), ConvertDeclSpecToType(), getCCForDeclaratorChunk(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), isFirstDeclarationOfMember(), isOmittedBlockReturnType(), isStaticMember(), warnAboutAmbiguousFunction(), and warnAboutRedundantParens().
getCXXScopeSpec() [1/2]
CXXScopeSpec & clang::Declarator::getCXXScopeSpec () inline
Definition at line 2002 of file DeclSpec.h.
getCXXScopeSpec() [2/2]
const CXXScopeSpec & clang::Declarator::getCXXScopeSpec () const inline
getCXXScopeSpec - Return the C++ scope specifier (global scope or nested-name-specifier) that is part of the declarator-id.
Definition at line 2001 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckFunctionOrTemplateParamDeclarator(), DiagnoseInvalidRedeclaration(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::isDeclaratorFunctionLike(), SetNestedNameSpecifier(), and warnAboutRedundantParens().
getDeclarationAttributes()
const ParsedAttributesView & clang::Declarator::getDeclarationAttributes () const inline
Definition at line 2608 of file DeclSpec.h.
Referenced by clang::Sema::checkUnusedDeclAttributes(), ConvertDeclSpecToType(), GetFullTypeForDeclarator(), hasAttributes(), hasParsedAttr(), clang::Sema::ProcessDeclAttributes(), and takeDeclAttributes().
getDeclSpec()
const DeclSpec & clang::Declarator::getDeclSpec () const inline
getDeclSpec - Return the declaration-specifier that this declarator was declared with.
Definition at line 1986 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXConditionDeclaration(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckFieldDecl(), checkOmittedBlockReturnType(), clang::Sema::checkUnusedDeclAttributes(), clang::Sema::containsUnexpandedParameterPacks(), CreateNewFunctionDecl(), diagnoseRedundantReturnTypeQualifiers(), getCCForDeclaratorChunk(), clang::ParsingDeclarator::getDeclSpec(), clang::ParsingFieldDeclarator::getDeclSpec(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getFunctionStorageClass(), getLambdaType(), GetTypeSourceInfoForDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), hasAttributes(), hasParsedAttr(), InventTemplateParameter(), clang::Sema::isDeclaratorFunctionLike(), isFirstDeclarationOfMember(), isFunctionDeclarationContext(), isOmittedBlockReturnType(), isStaticMember(), mayBeFollowedByCXXDirectInit(), clang::Sema::ParseTypedefDecl(), clang::Sema::ProcessDeclAttributes(), takeDeclAttributes(), warnAboutAmbiguousFunction(), and warnAboutRedundantParens().
getDecompositionDeclarator()
const DecompositionDeclarator & clang::Declarator::getDecompositionDeclarator () const inline
Definition at line 2007 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnVariableDeclarator(), and clang::Sema::HandleField().
getEllipsisLoc()
SourceLocation clang::Declarator::getEllipsisLoc () const inline
Definition at line 2648 of file DeclSpec.h.
Referenced by clang::Sema::ActOnNonTypeTemplateParameter(), GetFullTypeForDeclarator(), GetTypeSourceInfoForDeclarator(), and InventTemplateParameter().
getEndLoc()
SourceLocation clang::Declarator::getEndLoc () const inline
Definition at line 2023 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), CreateNewFunctionDecl(), and warnAboutRedundantParens().
getExtension()
bool clang::Declarator::getExtension () const inline
Definition at line 2627 of file DeclSpec.h.
getFunctionDefinitionKind()
FunctionDefinitionKind clang::Declarator::getFunctionDefinitionKind () const inline
Definition at line 2659 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), GetFullTypeForDeclarator(), isFunctionDefinition(), and warnAboutAmbiguousFunction().
getFunctionTypeInfo() [1/2]
DeclaratorChunk::FunctionTypeInfo & clang::Declarator::getFunctionTypeInfo () inline
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
Definition at line 2409 of file DeclSpec.h.
References isFunctionDeclarator().
Referenced by clang::Sema::ActOnFinishKNRParamDeclarations(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnStartTrailingRequiresClause(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), checkMethodTypeQualifiers(), clang::Sema::CodeCompleteAfterFunctionEquals(), CreateNewFunctionDecl(), DiagnoseInvalidRedeclaration(), getFunctionTypeInfo(), getLambdaType(), and maybeSynthesizeBlockSignature().
getFunctionTypeInfo() [2/2]
const DeclaratorChunk::FunctionTypeInfo & clang::Declarator::getFunctionTypeInfo () const inline
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
Definition at line 2418 of file DeclSpec.h.
References getFunctionTypeInfo().
getIdentifier()
IdentifierInfo * clang::Declarator::getIdentifier () const inline
Definition at line 2268 of file DeclSpec.h.
References clang::IK_Identifier.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnTypeName(), clang::Sema::CreatePropertyDecl(), GetFullTypeForDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), clang::Sema::HandlePropertyInClassExtension(), InventTemplateParameter(), clang::Sema::isDeclaratorFunctionLike(), clang::Sema::isLibstdcxxEagerExceptionSpecHack(), clang::Sema::ParseTypedefDecl(), warnAboutAmbiguousFunction(), and warnAboutRedundantParens().
getIdentifierLoc()
SourceLocation clang::Declarator::getIdentifierLoc () const inline
Definition at line 2274 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckFunctionOrTemplateParamDeclarator(), ConvertDeclSpecToType(), CreateNewFunctionDecl(), clang::Sema::CreatePropertyDecl(), DiagnoseInvalidRedeclaration(), diagnoseRedundantReturnTypeQualifiers(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), InventTemplateParameter(), clang::Sema::ParseTypedefDecl(), RebuildDeclaratorInCurrentInstantiation(), and warnAboutAmbiguousFunction().
getInnermostNonParenChunk()
const DeclaratorChunk * clang::Declarator::getInnermostNonParenChunk () const inline
Return the innermost (closest to the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
Definition at line 2346 of file DeclSpec.h.
Referenced by GetFullTypeForDeclarator(), and isArrayOfUnknownBound().
getInventedTemplateParameterList()
TemplateParameterList * clang::Declarator::getInventedTemplateParameterList () const inline
The template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters, if there were any such parameters.
Definition at line 2585 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator().
getMutableDeclSpec()
DeclSpec & clang::Declarator::getMutableDeclSpec () inline
getMutableDeclSpec - Return a non-const version of the DeclSpec.
This should be used with extreme care: declspecs can often be shared between multiple declarators, so mutating the DeclSpec affects all of the Declarators. This should only be done when the declspec is known to not be shared or when in error recovery etc.
Definition at line 1993 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), addContextSensitiveTypeNullability(), clang::Sema::CheckDeductionGuideDeclarator(), checkOmittedBlockReturnType(), ConvertDeclSpecToType(), CreateNewFunctionDecl(), distributeObjCPointerTypeAttrFromDeclarator(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getFunctionStorageClass(), RebuildDeclaratorInCurrentInstantiation(), and takeDeclAttributes().
getName()
UnqualifiedId & clang::Declarator::getName () inline
Retrieve the name specified by this declarator.
Definition at line 2005 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckFunctionOrTemplateParamDeclarator(), clang::Sema::CodeCompleteAfterFunctionEquals(), diagnoseRedundantReturnTypeQualifiers(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getMissingDeclaratorIdLoc(), clang::Sema::GetNameForDeclarator(), clang::Sema::HandleDeclarator(), isCtorOrDtor(), and isStaticMember().
getNumTypeObjects()
unsigned clang::Declarator::getNumTypeObjects () const inline
Return the number of types applied to this declarator.
Definition at line 2316 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnStartOfLambdaDefinition(), addContextSensitiveTypeNullability(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::checkUnusedDeclAttributes(), classifyPointerDeclarator(), clang::Sema::containsUnexpandedParameterPacks(), diagnoseRedundantReturnTypeQualifiers(), distributeFunctionTypeAttrToInnermost(), distributeObjCPointerTypeAttrFromDeclarator(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getLambdaType(), GetTypeSourceInfoForDeclarator(), handleObjCOwnershipTypeAttr(), hasAttributes(), hasParsedAttr(), inferARCWriteback(), isFunctionDeclaratorAFunctionDeclaration(), isOmittedBlockReturnType(), isPipeDeclarator(), maybeMovePastReturnType(), maybeSynthesizeBlockSignature(), clang::Sema::ProcessDeclAttributes(), RebuildDeclaratorInCurrentInstantiation(), takeDeclAttributes(), transferARCOwnership(), and warnAboutRedundantParens().
getOutermostNonParenChunk()
const DeclaratorChunk * clang::Declarator::getOutermostNonParenChunk () const inline
Return the outermost (furthest from the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
Definition at line 2357 of file DeclSpec.h.
getSourceRange()
SourceRange clang::Declarator::getSourceRange () const inline
Get the source range that spans this declarator.
Definition at line 2021 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXConditionDeclaration(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::CheckDeductionGuideDeclarator(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), and clang::Parser::ParseTypeName().
getTemplateParameterLists()
ArrayRef< TemplateParameterList * > clang::Declarator::getTemplateParameterLists () const inline
The template parameter lists that preceded the declarator.
Definition at line 2571 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), and clang::Sema::ActOnStartFunctionDeclarationDeclarator().
getTrailingRequiresClause()
Expr * clang::Declarator::getTrailingRequiresClause () inline
Sets a trailing requires clause for this declarator.
Definition at line 2555 of file DeclSpec.h.
Referenced by clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::containsUnexpandedParameterPacks(), and CreateNewFunctionDecl().
getTrailingReturnType()
ParsedType clang::Declarator::getTrailingReturnType () const inline
Get the trailing return type appearing (at any level) within this declarator.
Definition at line 2539 of file DeclSpec.h.
References clang::DeclaratorChunk::Function, and type_objects().
Referenced by GetDeclSpecTypeForDeclarator().
getTypeObject() [1/2]
DeclaratorChunk & clang::Declarator::getTypeObject (unsigned i) inline
Definition at line 2324 of file DeclSpec.h.
getTypeObject() [2/2]
const DeclaratorChunk & clang::Declarator::getTypeObject (unsigned i) const inline
Return the specified TypeInfo from this declarator.
TypeInfo #0 is closest to the identifier.
Definition at line 2320 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfLambdaDefinition(), addContextSensitiveTypeNullability(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::checkUnusedDeclAttributes(), classifyPointerDeclarator(), clang::Sema::containsUnexpandedParameterPacks(), diagnoseRedundantReturnTypeQualifiers(), distributeFunctionTypeAttr(), distributeFunctionTypeAttrToInnermost(), distributeNullabilityTypeAttr(), distributeObjCPointerTypeAttr(), distributeObjCPointerTypeAttrFromDeclarator(), getCCForDeclaratorChunk(), GetFullTypeForDeclarator(), GetTypeSourceInfoForDeclarator(), hasAttributes(), hasOuterPointerLikeChunk(), hasParsedAttr(), inferARCWriteback(), isFunctionDeclaratorAFunctionDeclaration(), isOmittedBlockReturnType(), isPipeDeclarator(), maybeMovePastReturnType(), clang::Sema::ProcessDeclAttributes(), RebuildDeclaratorInCurrentInstantiation(), takeDeclAttributes(), transferARCOwnership(), transferARCOwnershipToDeclaratorChunk(), and warnAboutRedundantParens().
hasAttributes()
bool clang::Declarator::hasAttributes () const inline
hasAttributes - do we contain any attributes?
Definition at line 2613 of file DeclSpec.h.
References getAttributes(), getDeclarationAttributes(), getDeclSpec(), getNumTypeObjects(), getTypeObject(), and hasAttributes().
Referenced by hasAttributes().
hasEllipsis()
bool clang::Declarator::hasEllipsis () const inline
Definition at line 2647 of file DeclSpec.h.
References clang::SourceLocation::isValid().
Referenced by clang::Sema::ActOnNonTypeTemplateParameter(), GetFullTypeForDeclarator(), and InventTemplateParameter().
hasGroupingParens()
bool clang::Declarator::hasGroupingParens () const inline
Definition at line 2641 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDecompositionDeclarator(), and mayBeFollowedByCXXDirectInit().
hasInitializer()
bool clang::Declarator::hasInitializer () const inline
Definition at line 2664 of file DeclSpec.h.
Referenced by clang::Sema::ActOnVariableDeclarator().
hasName()
bool clang::Declarator::hasName () const inline
hasName - Whether this declarator has a name, which might be an identifier (accessible via getIdentifier()) or some kind of special C++ name (constructor, destructor, etc.), or a structured binding (which is not exactly a name, but occupies the same position).
Definition at line 2258 of file DeclSpec.h.
References clang::IK_Identifier, and isDecompositionDeclarator().
Referenced by setDecompositionBindings().
hasTrailingRequiresClause()
bool clang::Declarator::hasTrailingRequiresClause () const inline
Determine whether a trailing requires clause was written in this declarator.
Definition at line 2561 of file DeclSpec.h.
hasTrailingReturnType()
bool clang::Declarator::hasTrailingReturnType () const inline
Determine whether a trailing return type was written (at any level) within this declarator.
Definition at line 2530 of file DeclSpec.h.
References clang::DeclaratorChunk::Function, and type_objects().
Referenced by GetDeclSpecTypeForDeclarator().
isArrayOfUnknownBound()
bool clang::Declarator::isArrayOfUnknownBound () const inline
isArrayOfUnknownBound - This method returns true if the declarator is a declarator for an array of unknown bound (looking through parentheses).
Definition at line 2368 of file DeclSpec.h.
References clang::DeclaratorChunk::Arr, clang::DeclaratorChunk::Array, getInnermostNonParenChunk(), clang::DeclaratorChunk::Kind, and clang::DeclaratorChunk::ArrayTypeInfo::NumElts.
isCtorOrDtor()
bool Declarator::isCtorOrDtor ()
Returns true if this declares a constructor or a destructor.
Definition at line 423 of file DeclSpec.cpp.
References clang::UnqualifiedId::getKind(), getKind(), getName(), clang::IK_ConstructorName, and clang::IK_DestructorName.
Referenced by clang::Sema::ActOnFunctionDeclarator(), and clang::Sema::CodeCompleteFunctionQualifiers().
isDeclarationOfFunction()
bool Declarator::isDeclarationOfFunction () const
Determine whether the declaration that will be produced from this declaration will be a function.
A declaration can declare a function even if the declarator itself isn't a function declarator, if the type specifier refers to a function type. This routine checks for both cases.
Definition at line 325 of file DeclSpec.cpp.
References clang::DeclaratorChunk::Array, clang::DeclaratorChunk::BlockPointer, clang::DeclaratorChunk::Function, clang::OpaquePtr< PtrTy >::get(), clang::DeclSpec::getRepAsExpr(), clang::DeclSpec::getRepAsType(), clang::DeclSpec::getTypeSpecType(), clang::Type::isFunctionType(), clang::QualType::isNull(), clang::DeclaratorChunk::MemberPointer, clang::DeclaratorChunk::Paren, clang::DeclaratorChunk::Pipe, clang::DeclaratorChunk::Pointer, clang::DeclaratorChunk::Reference, clang::TST_Accum, clang::TST_atomic, clang::TST_auto, clang::TST_auto_type, clang::TST_BFloat16, clang::TST_bitint, clang::TST_bool, clang::TST_char, clang::TST_char16, clang::TST_char32, clang::TST_char8, clang::TST_class, clang::TST_decimal128, clang::TST_decimal32, clang::TST_decimal64, clang::TST_decltype, clang::TST_decltype_auto, clang::TST_double, clang::TST_enum, clang::TST_error, clang::TST_float, clang::TST_float128, clang::TST_Float16, clang::TST_Fract, clang::TST_half, clang::TST_ibm128, clang::TST_int, clang::TST_int128, clang::TST_interface, clang::TST_struct, clang::TST_typename, clang::TST_typeof_unqualExpr, clang::TST_typeof_unqualType, clang::TST_typeofExpr, clang::TST_typeofType, clang::TST_union, clang::TST_unknown_anytype, clang::TST_unspecified, clang::TST_void, and clang::TST_wchar.
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
isDecompositionDeclarator()
bool clang::Declarator::isDecompositionDeclarator () const inline
Return whether this declarator is a decomposition declarator.
Definition at line 2264 of file DeclSpec.h.
References clang::DecompositionDeclarator::isSet().
Referenced by clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::HandleField(), and hasName().
isExpressionContext()
bool clang::Declarator::isExpressionContext () const inline
Determine whether this declaration appears in a context where an expression could appear.
Definition at line 2474 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
Referenced by warnAboutRedundantParens().
isFirstDeclarationOfMember()
bool clang::Declarator::isFirstDeclarationOfMember () inline
Returns true if this declares a real member and not a friend.
Definition at line 2667 of file DeclSpec.h.
References getContext(), getDeclSpec(), clang::DeclSpec::isFriendSpecified(), and clang::Member.
Referenced by clang::Sema::ActOnFunctionDeclarator(), and getCCForDeclaratorChunk().
isFirstDeclarator()
bool clang::Declarator::isFirstDeclarator () const inline
Definition at line 2643 of file DeclSpec.h.
References clang::SourceLocation::isValid().
Referenced by warnAboutAmbiguousFunction(), and warnAboutRedundantParens().
isFunctionDeclarationContext()
bool clang::Declarator::isFunctionDeclarationContext () const inline
Return true if this declaration appears in a context where a function declarator would be a function declaration.
Definition at line 2432 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, getDeclSpec(), clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::DeclSpec::SCS_typedef, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
Referenced by clang::Sema::CheckExtraCXXDefaultArguments(), GetFullTypeForDeclarator(), and isFunctionDeclaratorAFunctionDeclaration().
isFunctionDeclarator() [1/2]
bool clang::Declarator::isFunctionDeclarator () const inline
isFunctionDeclarator - Once this declarator is fully parsed and formed, this method returns true if the identifier is a function declarator (looking through parentheses).
Definition at line 2402 of file DeclSpec.h.
References isFunctionDeclarator().
Referenced by getFunctionTypeInfo(), and isFunctionDeclarator().
isFunctionDeclarator() [2/2]
bool clang::Declarator::isFunctionDeclarator (unsigned & idx) const inline
isFunctionDeclarator - This method returns true if the declarator is a function declarator (looking through parentheses).
If true is returned, then the reference type parameter idx is assigned with the index of the declaration chunk.
Definition at line 2378 of file DeclSpec.h.
References clang::DeclaratorChunk::Array, clang::DeclaratorChunk::BlockPointer, clang::DeclaratorChunk::Function, clang::DeclaratorChunk::MemberPointer, clang::DeclaratorChunk::Paren, clang::DeclaratorChunk::Pipe, clang::DeclaratorChunk::Pointer, and clang::DeclaratorChunk::Reference.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnStartTrailingRequiresClause(), clang::Sema::CodeCompleteAfterFunctionEquals(), CreateNewFunctionDecl(), getCCForDeclaratorChunk(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), maybeSynthesizeBlockSignature(), and warnAboutAmbiguousFunction().
isFunctionDeclaratorAFunctionDeclaration()
bool clang::Declarator::isFunctionDeclaratorAFunctionDeclaration () const inline
Return true if a function declarator at this position would be a function declaration.
Definition at line 2517 of file DeclSpec.h.
References getNumTypeObjects(), getTypeObject(), isFunctionDeclarationContext(), N, and clang::DeclaratorChunk::Paren.
isFunctionDefinition()
bool clang::Declarator::isFunctionDefinition () const inline
Definition at line 2655 of file DeclSpec.h.
References clang::Declaration, and getFunctionDefinitionKind().
Referenced by clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), and DiagnoseInvalidRedeclaration().
isInvalidType()
bool clang::Declarator::isInvalidType () const inline
Definition at line 2636 of file DeclSpec.h.
References clang::DeclSpec::getTypeSpecType(), and clang::DeclSpec::TST_error.
Referenced by clang::Sema::ActOnBuiltinBitCastExpr(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnCXXNamedCast(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnOpenMPDeclareMapperVarDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypeName(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckFieldDecl(), checkMethodTypeQualifiers(), CreateNewFunctionDecl(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::ParseTypedefDecl(), clang::Parser::ParseTypeName(), and warnAboutRedundantParens().
isObjCIvar()
bool clang::Declarator::isObjCIvar () const inline
Definition at line 2630 of file DeclSpec.h.
isObjCWeakProperty()
bool clang::Declarator::isObjCWeakProperty () const inline
Definition at line 2633 of file DeclSpec.h.
isPastIdentifier()
bool clang::Declarator::isPastIdentifier () const inline
isPastIdentifier - Return true if we have parsed beyond the point where the name would appear.
(This may happen even if we haven't actually parsed a name, perhaps because this context doesn't require one.)
Definition at line 2252 of file DeclSpec.h.
isPrototypeContext()
bool clang::Declarator::isPrototypeContext () const inline
Definition at line 2013 of file DeclSpec.h.
References clang::LambdaExprParameter, clang::ObjCParameter, clang::ObjCResult, and clang::Prototype.
Referenced by GetFullTypeForDeclarator(), and clang::Sema::GetTypeForDeclarator().
isRedeclaration()
bool clang::Declarator::isRedeclaration () const inline
Definition at line 2681 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), and DiagnoseInvalidRedeclaration().
isStaticMember()
bool Declarator::isStaticMember ()
Returns true if this declares a static member.
This cannot be called on a declarator outside of a MemberContext because we won't know until redeclaration time if the decl is static.
Definition at line 415 of file DeclSpec.cpp.
References getContext(), getDeclSpec(), clang::UnqualifiedId::getKind(), getName(), clang::DeclSpec::getStorageClassSpec(), clang::IK_OperatorFunctionId, clang::CXXMethodDecl::isStaticOverloadedOperator(), clang::Member, and clang::DeclSpec::SCS_static.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::CodeCompleteFunctionQualifiers(), and getCCForDeclaratorChunk().
mayBeFollowedByCXXDirectInit()
bool clang::Declarator::mayBeFollowedByCXXDirectInit () const inline
mayBeFollowedByCXXDirectInit - Return true if the declarator can be followed by a C++ direct initializer, e.g.
"int x(1);".
Definition at line 2194 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, getDeclSpec(), hasGroupingParens(), clang::IK_Identifier, clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::DeclSpec::SCS_extern, clang::DeclSpec::SCS_typedef, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
mayHaveDecompositionDeclarator()
bool clang::Declarator::mayHaveDecompositionDeclarator () const inline
Return true if the context permits a C++17 decomposition declarator.
Definition at line 2149 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
Referenced by clang::Sema::ActOnDecompositionDeclarator().
mayHaveIdentifier()
bool clang::Declarator::mayHaveIdentifier () const inline
mayHaveIdentifier - Return true if the identifier is either optional or required.
This is true for normal declarators and prototypes, but not typenames.
Definition at line 2111 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
mayOmitIdentifier()
bool clang::Declarator::mayOmitIdentifier () const inline
mayOmitIdentifier - Return true if the identifier is either optional or not allowed.
This is true for typenames, prototypes, and template parameter lists.
Definition at line 2071 of file DeclSpec.h.
References clang::AliasDecl, clang::AliasTemplate, clang::Association, clang::Block, clang::BlockLiteral, clang::Condition, clang::ConversionId, clang::CXXCatch, clang::CXXNew, clang::File, clang::ForInit, clang::FunctionalCast, clang::KNRTypeList, clang::LambdaExpr, clang::LambdaExprParameter, clang::Member, clang::ObjCCatch, clang::ObjCParameter, clang::ObjCResult, clang::Prototype, clang::RequiresExpr, clang::SelectionInit, clang::TemplateArg, clang::TemplateParam, clang::TemplateTypeArg, clang::TrailingReturn, clang::TrailingReturnVar, and clang::TypeName.
setAsmLabel()
void clang::Declarator::setAsmLabel (Expr * E) inline
Definition at line 2623 of file DeclSpec.h.
setCommaLoc()
void clang::Declarator::setCommaLoc (SourceLocation CL) inline
Definition at line 2645 of file DeclSpec.h.
setDecompositionBindings()
void Declarator::setDecompositionBindings (SourceLocation LSquareLoc, ArrayRef< DecompositionDeclarator::Binding > Bindings, SourceLocation RSquareLoc)
Set the decomposition bindings for this declarator.
Definition at line 294 of file DeclSpec.cpp.
References clang::UnqualifiedId::EndLocation, hasName(), InlineBindings, clang::SourceRange::setEnd(), and SetIdentifier().
setEllipsisLoc()
void clang::Declarator::setEllipsisLoc (SourceLocation EL) inline
Definition at line 2649 of file DeclSpec.h.
Referenced by GetFullTypeForDeclarator().
setExtension()
void clang::Declarator::setExtension (bool Val = true) inline
Definition at line 2626 of file DeclSpec.h.
setFunctionDefinitionKind()
void clang::Declarator::setFunctionDefinitionKind (FunctionDefinitionKind Val) inline
Definition at line 2651 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDeclarator(), clang::Sema::ActOnStartOfFunctionDef(), and clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope().
setGroupingParens()
void clang::Declarator::setGroupingParens (bool flag) inline
Definition at line 2640 of file DeclSpec.h.
setHasInitializer()
void clang::Declarator::setHasInitializer (bool Val = true) inline
Definition at line 2663 of file DeclSpec.h.
SetIdentifier()
void clang::Declarator::SetIdentifier (IdentifierInfo * Id, SourceLocation IdLoc) inline
Set the name of this declarator to be the given identifier.
Definition at line 2277 of file DeclSpec.h.
References Id.
Referenced by clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFinishKNRParamDeclarations(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), DiagnoseInvalidRedeclaration(), clang::Sema::ImplicitlyDefineFunction(), and setDecompositionBindings().
setInvalidType()
void clang::Declarator::setInvalidType (bool Val = true) inline
Definition at line 2635 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), checkIsValidOpenCLKernelParameter(), checkMethodTypeQualifiers(), ConvertDeclSpecToType(), CreateNewFunctionDecl(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getFunctionStorageClass(), clang::Sema::HandleDeclarator(), clang::Sema::HandleField(), and clang::Sema::HandleMSProperty().
setInventedTemplateParameterList()
void clang::Declarator::setInventedTemplateParameterList (TemplateParameterList * Invented) inline
Sets the template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters.
Definition at line 2578 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator().
setObjCIvar()
void clang::Declarator::setObjCIvar (bool Val = true) inline
Definition at line 2629 of file DeclSpec.h.
setObjCWeakProperty()
void clang::Declarator::setObjCWeakProperty (bool Val = true) inline
Definition at line 2632 of file DeclSpec.h.
Referenced by clang::Sema::ActOnProperty().
SetRangeBegin()
void clang::Declarator::SetRangeBegin (SourceLocation Loc) inline
SetRangeBegin - Set the start of the source range to Loc, unless it's invalid.
Definition at line 2028 of file DeclSpec.h.
SetRangeEnd()
void clang::Declarator::SetRangeEnd (SourceLocation Loc) inline
SetRangeEnd - Set the end of the source range to Loc, unless it's invalid.
Definition at line 2033 of file DeclSpec.h.
Referenced by AddTypeInfo(), AddTypeInfo(), setTrailingRequiresClause(), and takeAttributes().
setRedeclaration()
void clang::Declarator::setRedeclaration (bool Val) inline
Definition at line 2680 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), and DiagnoseInvalidRedeclaration().
SetSourceRange()
void clang::Declarator::SetSourceRange (SourceRange R) inline
Definition at line 2025 of file DeclSpec.h.
setTemplateParameterLists()
void clang::Declarator::setTemplateParameterLists (ArrayRef< TemplateParameterList * > TPLs) inline
Sets the template parameter lists that preceded the declarator.
Definition at line 2566 of file DeclSpec.h.
setTrailingRequiresClause()
void clang::Declarator::setTrailingRequiresClause (Expr * TRC) inline
Sets a trailing requires clause for this declarator.
Definition at line 2548 of file DeclSpec.h.
References clang::Stmt::getEndLoc(), and SetRangeEnd().
takeAttributes()
void clang::Declarator::takeAttributes (ParsedAttributes & attrs) inline
takeAttributes - Takes attributes from the given parsed-attributes set and add them to this declarator.
These examples both add 3 attributes to "var": short int var attribute((aligned(16),common,deprecated)); short int x, attribute((aligned(16)) var attribute((common,deprecated));
Also extends the range of the declarator.
Definition at line 2598 of file DeclSpec.h.
References clang::SourceRange::getEnd(), clang::SourceLocation::isValid(), clang::ParsedAttributesView::Range, SetRangeEnd(), and clang::ParsedAttributes::takeAllFrom().
Referenced by clang::Sema::ActOnCXXForRangeIdentifier().
type_objects()
type_object_range clang::Declarator::type_objects () const inline
Returns the range of type objects, from the identifier outwards.
Definition at line 2333 of file DeclSpec.h.
Referenced by clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), GetFullTypeForDeclarator(), getTrailingReturnType(), hasTrailingReturnType(), and warnAboutRedundantParens().
Friends And Related Symbol Documentation
DeclaratorChunk
friend struct DeclaratorChunk friend
Definition at line 1942 of file DeclSpec.h.
Member Data Documentation
InlineBindings
DecompositionDeclarator::Binding clang::Declarator::InlineBindings[16]
Definition at line 1929 of file DeclSpec.h.
Referenced by setDecompositionBindings().
InlineParams
DeclaratorChunk::ParamInfo clang::Declarator::InlineParams[16]
InlineParams - This is a local array used for the first function decl chunk to avoid going to the heap for the common case when we have one function chunk in the declarator.
Definition at line 1928 of file DeclSpec.h.
Referenced by clang::DeclaratorChunk::getFunction().
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp