clang: clang::interp::FunctionPointer Class Reference
clang::interp::FunctionPointer Class Reference final
#include "/root/llvm-project/clang/lib/AST/Interp/FunctionPointer.h"
Public Member Functions
FunctionPointer ()
FunctionPointer (const Function *Func)
const Function * getFunction () const
APValue toAPValue () const
void print (llvm::raw_ostream &OS) const
std::string toDiagnosticString (const ASTContext &Ctx) const
ComparisonCategoryResult compare (const FunctionPointer &RHS) const
Detailed Description
Definition at line 20 of file FunctionPointer.h.
Constructor & Destructor Documentation
FunctionPointer() [1/2]
clang::interp::FunctionPointer::FunctionPointer () inline
Definition at line 25 of file FunctionPointer.h.
FunctionPointer() [2/2]
clang::interp::FunctionPointer::FunctionPointer (const Function * Func) inline
Definition at line 26 of file FunctionPointer.h.
Member Function Documentation
compare()
ComparisonCategoryResult clang::interp::FunctionPointer::compare (const FunctionPointer & RHS) const inline
Definition at line 55 of file FunctionPointer.h.
References clang::Equal, and clang::Unordered.
Referenced by clang::interp::CmpHelperEQ< FunctionPointer >().
getFunction()
const Function * clang::interp::FunctionPointer::getFunction () const inline
Definition at line 28 of file FunctionPointer.h.
Referenced by clang::interp::CallPtr().
print()
void clang::interp::FunctionPointer::print (llvm::raw_ostream & OS) const inline
Definition at line 39 of file FunctionPointer.h.
References clang::interp::Function::getName().
Referenced by clang::interp::operator<<().
toAPValue()
APValue clang::interp::FunctionPointer::toAPValue () const inline
Definition at line 30 of file FunctionPointer.h.
References clang::interp::Function::getDecl(), and clang::CharUnits::Zero().
Referenced by toDiagnosticString().
toDiagnosticString()
std::string clang::interp::FunctionPointer::toDiagnosticString (const ASTContext & Ctx) const inline
Definition at line 48 of file FunctionPointer.h.
References clang::APValue::getAsString(), clang::interp::Function::getDecl(), clang::ValueDecl::getType(), and toAPValue().
Referenced by clang::interp::CmpHelper< FunctionPointer >().
The documentation for this class was generated from the following file:
lib/AST/Interp/FunctionPointer.h