clang: clang::AutoTypeLoc Class Reference
clang::AutoTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
AutoTypeKeyword getAutoKeyword () const
bool isDecltypeAuto () const
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
bool isConstrained () const
const NestedNameSpecifierLoc & getNestedNameSpecifierLoc () const
void setNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
SourceLocation getTemplateKWLoc () const
void setTemplateKWLoc (SourceLocation Loc)
SourceLocation getConceptNameLoc () const
void setConceptNameLoc (SourceLocation Loc)
NamedDecl * getFoundDecl () const
void setFoundDecl (NamedDecl *D)
ConceptDecl * getNamedConcept () const
DeclarationNameInfo getConceptNameInfo () const
bool hasExplicitTemplateArgs () const
SourceLocation getLAngleLoc () const
void setLAngleLoc (SourceLocation Loc)
SourceLocation getRAngleLoc () const
void setRAngleLoc (SourceLocation Loc)
unsigned getNumArgs () const
void setArgLocInfo (unsigned i, TemplateArgumentLocInfo AI)
TemplateArgumentLocInfo getArgLocInfo (unsigned i) const
TemplateArgumentLoc getArgLoc (unsigned i) const
SourceRange getLocalSourceRange () const
void copy (AutoTypeLoc Loc)
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
Public Member Functions inherited from clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (AutoTypeLoc other)
TypeLoc getNextTypeLoc () const
const AutoType * getTypePtr () const
Public Member Functions inherited from clang::InheritingConcreteTypeLoc< TypeSpecTypeLoc, DeducedTypeLoc, DeducedType >
const DeducedType * getTypePtr () const
Public Member Functions inherited from clang::TypeSpecTypeLoc
SourceLocation getNameLoc () const
void setNameLoc (SourceLocation Loc)
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, TypeSpecTypeLoc, Type, TypeSpecLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (TypeSpecTypeLoc other)
TypeLoc getNextTypeLoc () const
const Type * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeSpecTypeLoc
enum { LocalDataSize = sizeof(TypeSpecLocInfo) , LocalDataAlignment = alignof(TypeSpecLocInfo) }
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
AutoTypeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, TypeSpecTypeLoc, Type, TypeSpecLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
TypeSpecLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Definition at line 2120 of file TypeLoc.h.
Member Function Documentation
copy()
void clang::AutoTypeLoc::copy (AutoTypeLoc Loc) inline
Definition at line 2223 of file TypeLoc.h.
References Data, clang::TypeLoc::getFullDataSize(), and memcpy().
getArgLoc()
TemplateArgumentLoc clang::AutoTypeLoc::getArgLoc (unsigned i) const inline
Definition at line 2208 of file TypeLoc.h.
References getArgLocInfo(), and clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by InventTemplateParameter().
getArgLocInfo()
TemplateArgumentLocInfo clang::AutoTypeLoc::getArgLocInfo (unsigned i) const inline
Definition at line 2204 of file TypeLoc.h.
Referenced by getArgLoc().
getAutoKeyword()
AutoTypeKeyword clang::AutoTypeLoc::getAutoKeyword () const inline
Definition at line 2126 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by clang::Sema::AttachTypeConstraint().
getConceptNameInfo()
DeclarationNameInfo AutoTypeLoc::getConceptNameInfo () const
Definition at line 624 of file TypeLoc.cpp.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and getNamedConcept().
Referenced by clang::Sema::AttachTypeConstraint(), and InventTemplateParameter().
getConceptNameLoc()
SourceLocation clang::AutoTypeLoc::getConceptNameLoc () const inline
Definition at line 2154 of file TypeLoc.h.
References clang::AutoTypeLocInfo::ConceptNameLoc, and clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData().
Referenced by getLocalSourceRange().
getExtraLocalDataAlignment()
unsigned clang::AutoTypeLoc::getExtraLocalDataAlignment () const inline
Definition at line 2235 of file TypeLoc.h.
getExtraLocalDataSize()
unsigned clang::AutoTypeLoc::getExtraLocalDataSize () const inline
Definition at line 2231 of file TypeLoc.h.
References getNumArgs().
getFoundDecl()
NamedDecl * clang::AutoTypeLoc::getFoundDecl () const inline
Definition at line 2162 of file TypeLoc.h.
References clang::AutoTypeLocInfo::FoundDecl, and clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData().
getLAngleLoc()
SourceLocation clang::AutoTypeLoc::getLAngleLoc () const inline
Definition at line 2180 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::LAngleLoc.
Referenced by clang::Sema::AttachTypeConstraint(), and InventTemplateParameter().
getLocalSourceRange()
SourceRange clang::AutoTypeLoc::getLocalSourceRange () const inline
Definition at line 2213 of file TypeLoc.h.
References clang::NestedNameSpecifierLoc::getBeginLoc(), getConceptNameLoc(), clang::TypeSpecTypeLoc::getNameLoc(), getNestedNameSpecifierLoc(), getRParenLoc(), getTemplateKWLoc(), isConstrained(), isDecltypeAuto(), and clang::SourceLocation::isValid().
getNamedConcept()
ConceptDecl * clang::AutoTypeLoc::getNamedConcept () const inline
Definition at line 2170 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by clang::Sema::AttachTypeConstraint(), getConceptNameInfo(), and InventTemplateParameter().
getNestedNameSpecifierLoc()
const NestedNameSpecifierLoc & clang::AutoTypeLoc::getNestedNameSpecifierLoc () const inline
Definition at line 2138 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::NestedNameSpec.
Referenced by clang::Sema::AttachTypeConstraint(), getLocalSourceRange(), and InventTemplateParameter().
getNumArgs()
unsigned clang::AutoTypeLoc::getNumArgs () const inline
Definition at line 2196 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by getExtraLocalDataSize(), and InventTemplateParameter().
getRAngleLoc()
SourceLocation clang::AutoTypeLoc::getRAngleLoc () const inline
Definition at line 2188 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::RAngleLoc.
Referenced by clang::Sema::AttachTypeConstraint(), and InventTemplateParameter().
getRParenLoc()
SourceLocation clang::AutoTypeLoc::getRParenLoc () const inline
Definition at line 2131 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::RParenLoc.
Referenced by getLocalSourceRange().
getTemplateKWLoc()
SourceLocation clang::AutoTypeLoc::getTemplateKWLoc () const inline
Definition at line 2146 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::TemplateKWLoc.
Referenced by getLocalSourceRange().
hasExplicitTemplateArgs()
bool clang::AutoTypeLoc::hasExplicitTemplateArgs () const inline
Definition at line 2176 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), clang::SourceLocation::isValid(), and clang::AutoTypeLocInfo::LAngleLoc.
Referenced by InventTemplateParameter().
initializeLocal()
void AutoTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc)
Definition at line 629 of file TypeLoc.cpp.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr(), clang::TemplateSpecializationTypeLoc::initializeArgLocs(), setConceptNameLoc(), setFoundDecl(), setLAngleLoc(), clang::TypeSpecTypeLoc::setNameLoc(), setNestedNameSpecifierLoc(), setRAngleLoc(), setRParenLoc(), and setTemplateKWLoc().
isConstrained()
bool clang::AutoTypeLoc::isConstrained () const inline
Definition at line 2134 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by getLocalSourceRange().
isDecltypeAuto()
bool clang::AutoTypeLoc::isDecltypeAuto () const inline
Definition at line 2130 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getTypePtr().
Referenced by getLocalSourceRange().
setArgLocInfo()
void clang::AutoTypeLoc::setArgLocInfo (unsigned i, TemplateArgumentLocInfo AI) inline
Definition at line 2200 of file TypeLoc.h.
setConceptNameLoc()
void clang::AutoTypeLoc::setConceptNameLoc (SourceLocation Loc) inline
Definition at line 2158 of file TypeLoc.h.
References clang::AutoTypeLocInfo::ConceptNameLoc, and clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData().
Referenced by initializeLocal().
setFoundDecl()
void clang::AutoTypeLoc::setFoundDecl (NamedDecl * D) inline
Definition at line 2166 of file TypeLoc.h.
References clang::AutoTypeLocInfo::FoundDecl, and clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData().
Referenced by initializeLocal().
setLAngleLoc()
void clang::AutoTypeLoc::setLAngleLoc (SourceLocation Loc) inline
Definition at line 2184 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::LAngleLoc.
Referenced by initializeLocal().
setNestedNameSpecifierLoc()
void clang::AutoTypeLoc::setNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS) inline
Definition at line 2142 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::NestedNameSpec.
Referenced by initializeLocal().
setRAngleLoc()
void clang::AutoTypeLoc::setRAngleLoc (SourceLocation Loc) inline
Definition at line 2192 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::RAngleLoc.
Referenced by initializeLocal().
setRParenLoc()
void clang::AutoTypeLoc::setRParenLoc (SourceLocation Loc) inline
Definition at line 2132 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::RParenLoc.
Referenced by initializeLocal().
setTemplateKWLoc()
void clang::AutoTypeLoc::setTemplateKWLoc (SourceLocation Loc) inline
Definition at line 2150 of file TypeLoc.h.
References clang::ConcreteTypeLoc< DeducedTypeLoc, AutoTypeLoc, AutoType, AutoTypeLocInfo >::getLocalData(), and clang::AutoTypeLocInfo::TemplateKWLoc.
Referenced by initializeLocal().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp