clang: clang::ASTConsumer Class Reference
clang::ASTConsumer Class Reference
ASTConsumer - This is an abstract interface that should be implemented by clients that read ASTs.
#include "clang/AST/ASTConsumer.h"
Public Member Functions
ASTConsumer ()=default
virtual ~ASTConsumer ()
virtual void Initialize (ASTContext &Context)
Initialize - This is called to initialize the consumer, providing the ASTContext.
virtual bool HandleTopLevelDecl (DeclGroupRef D)
HandleTopLevelDecl - Handle the specified top-level declaration.
virtual void HandleInlineFunctionDefinition (FunctionDecl *D)
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
virtual void HandleInterestingDecl (DeclGroupRef D)
HandleInterestingDecl - Handle the specified interesting declaration.
virtual void HandleTranslationUnit (ASTContext &Ctx)
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
virtual void HandleTagDeclDefinition (TagDecl *D)
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
virtual void HandleTagDeclRequiredDefinition (const TagDecl *D)
This callback is invoked the first time each TagDecl is required to be complete.
virtual void HandleCXXImplicitFunctionInstantiation (FunctionDecl *D)
Invoked when a function is implicitly instantiated.
virtual void HandleTopLevelDeclInObjCContainer (DeclGroupRef D)
Handle the specified top-level declaration that occurred inside and ObjC container.
virtual void HandleImplicitImportDecl (ImportDecl *D)
Handle an ImportDecl that was implicitly created due to an inclusion directive.
virtual void CompleteTentativeDefinition (VarDecl *D)
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
virtual void CompleteExternalDeclaration (VarDecl *D)
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
virtual void AssignInheritanceModel (CXXRecordDecl *RD)
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
virtual void HandleCXXStaticMemberVarInstantiation (VarDecl *D)
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
virtual void HandleVTable (CXXRecordDecl *RD)
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
virtual ASTMutationListener * GetASTMutationListener ()
If the consumer is interested in entities getting modified after their initial creation, it should return a pointer to an ASTMutationListener here.
virtual ASTDeserializationListener * GetASTDeserializationListener ()
If the consumer is interested in entities being deserialized from AST files, it should return a pointer to a ASTDeserializationListener here.
virtual void PrintStats ()
PrintStats - If desired, print any statistics.
virtual bool shouldSkipFunctionBody (Decl *D)
This callback is called for each function if the Parser was initialized with SkipFunctionBodies set to true.
Friends
class SemaConsumer
Detailed Description
ASTConsumer - This is an abstract interface that should be implemented by clients that read ASTs.
This abstraction layer allows the client to be independent of the AST producer (e.g. parser vs AST dump file reader, etc).
Definition at line 33 of file ASTConsumer.h.
Constructor & Destructor Documentation
ASTConsumer()
clang::ASTConsumer::ASTConsumer () default
~ASTConsumer()
virtual clang::ASTConsumer::~ASTConsumer () inline virtual
Definition at line 43 of file ASTConsumer.h.
Member Function Documentation
AssignInheritanceModel()
virtual void clang::ASTConsumer::AssignInheritanceModel (CXXRecordDecl * RD) inline virtual
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 112 of file ASTConsumer.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), assignInheritanceModel(), handleMSInheritanceAttr(), and mergeDeclAttribute().
CompleteExternalDeclaration()
virtual void clang::ASTConsumer::CompleteExternalDeclaration (VarDecl * D) inline virtual
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 108 of file ASTConsumer.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
CompleteTentativeDefinition()
virtual void clang::ASTConsumer::CompleteTentativeDefinition (VarDecl * D) inline virtual
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
The variable declaration itself will be a tentative definition. If it had an incomplete array type, its type will have already been changed to an array of size 1. However, the declaration remains a tentative definition and has not been modified by the introduction of an implicit zero initializer.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 103 of file ASTConsumer.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
GetASTDeserializationListener()
virtual ASTDeserializationListener * clang::ASTConsumer::GetASTDeserializationListener () inline virtual
If the consumer is interested in entities being deserialized from AST files, it should return a pointer to a ASTDeserializationListener here.
Reimplemented in clang::IncrementalASTConsumer, clang::MultiplexConsumer, and clang::PCHGenerator.
Definition at line 132 of file ASTConsumer.h.
GetASTMutationListener()
virtual ASTMutationListener * clang::ASTConsumer::GetASTMutationListener () inline virtual
If the consumer is interested in entities getting modified after their initial creation, it should return a pointer to an ASTMutationListener here.
Reimplemented in clang::IncrementalASTConsumer, clang::MultiplexConsumer, and clang::PCHGenerator.
Definition at line 128 of file ASTConsumer.h.
Referenced by clang::Sema::getASTMutationListener().
HandleCXXImplicitFunctionInstantiation()
virtual void clang::ASTConsumer::HandleCXXImplicitFunctionInstantiation (FunctionDecl * D) inline virtual
Invoked when a function is implicitly instantiated.
Note that at this point it does not have a body, its body is instantiated at the end of the translation unit and passed to HandleTopLevelDecl.
Reimplemented in clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 82 of file ASTConsumer.h.
Referenced by clang::Sema::MarkFunctionReferenced().
HandleCXXStaticMemberVarInstantiation()
virtual void clang::ASTConsumer::HandleCXXStaticMemberVarInstantiation (VarDecl * D) inline virtual
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 116 of file ASTConsumer.h.
Referenced by clang::Sema::InstantiateVariableDefinition().
HandleImplicitImportDecl()
void ASTConsumer::HandleImplicitImportDecl (ImportDecl * D) virtual
Handle an ImportDecl that was implicitly created due to an inclusion directive.
The default implementation passes it to HandleTopLevelDecl.
Reimplemented in clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 28 of file ASTConsumer.cpp.
References HandleTopLevelDecl().
Referenced by clang::Sema::BuildModuleInclude(), and clang::Sema::createImplicitModuleImportForErrorRecovery().
HandleInlineFunctionDefinition()
virtual void clang::ASTConsumer::HandleInlineFunctionDefinition (FunctionDecl * D) inline virtual
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 57 of file ASTConsumer.h.
Referenced by clang::Sema::ActOnFinishInlineFunctionDef().
HandleInterestingDecl()
void ASTConsumer::HandleInterestingDecl (DeclGroupRef D) virtual
HandleInterestingDecl - Handle the specified interesting declaration.
This is called by the AST reader when deserializing things that might interest the consumer. The default implementation forwards to HandleTopLevelDecl.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 22 of file ASTConsumer.cpp.
References HandleTopLevelDecl().
Referenced by PassObjCImplDeclToConsumer().
HandleTagDeclDefinition()
virtual void clang::ASTConsumer::HandleTagDeclDefinition (TagDecl * D) inline virtual
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
struct, union, enum, class) is completed. This allows the client to hack on the type, which can occur at any point in the file (because these can be defined in declspecs).
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 72 of file ASTConsumer.h.
Referenced by clang::Sema::ActOnTagFinishDefinition().
HandleTagDeclRequiredDefinition()
virtual void clang::ASTConsumer::HandleTagDeclRequiredDefinition (const TagDecl * D) inline virtual
This callback is invoked the first time each TagDecl is required to be complete.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 76 of file ASTConsumer.h.
Referenced by clang::Sema::RequireCompleteType().
HandleTopLevelDecl()
bool ASTConsumer::HandleTopLevelDecl (DeclGroupRef D) virtual
HandleTopLevelDecl - Handle the specified top-level declaration.
This is called by the parser to process every top-level Decl*.
Returns
true to continue parsing, or false to abort parsing.
Reimplemented in clang::BackendConsumer, clang::ento::ModelConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 18 of file ASTConsumer.cpp.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnPragmaDetectMismatch(), clang::Sema::ActOnPragmaMSComment(), clang::ASTMergeAction::ExecuteAction(), HandleImplicitImportDecl(), HandleInterestingDecl(), clang::Sema::InstantiateFunctionDefinition(), clang::ParseAST(), and ReferenceDllExportedMembers().
HandleTopLevelDeclInObjCContainer()
void ASTConsumer::HandleTopLevelDeclInObjCContainer (DeclGroupRef D) virtual
Handle the specified top-level declaration that occurred inside and ObjC container.
The default implementation ignored them.
Reimplemented in clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 26 of file ASTConsumer.cpp.
Referenced by clang::Sema::ActOnAtEnd().
HandleTranslationUnit()
virtual void clang::ASTConsumer::HandleTranslationUnit (ASTContext & Ctx) inline virtual
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, clang::MultiplexConsumer, clang::PCHGenerator, clang::tooling::RefactoringASTConsumer, clang::tooling::RenamingASTConsumer, and clang::tooling::USRSymbolRenamer.
Definition at line 66 of file ASTConsumer.h.
Referenced by clang::ParseAST().
HandleVTable()
virtual void clang::ASTConsumer::HandleVTable (CXXRecordDecl * RD) inline virtual
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
Parameters
RD The class whose vtable was used.
Reimplemented in clang::BackendConsumer, clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 123 of file ASTConsumer.h.
Initialize()
virtual void clang::ASTConsumer::Initialize (ASTContext & Context) inline virtual
Initialize - This is called to initialize the consumer, providing the ASTContext.
Reimplemented in clang::BackendConsumer, and clang::MultiplexConsumer.
Definition at line 47 of file ASTConsumer.h.
Referenced by clang::IncrementalParser::IncrementalParser(), clang::CompilerInstance::setASTConsumer(), and clang::CompilerInstance::setASTContext().
PrintStats()
virtual void clang::ASTConsumer::PrintStats () inline virtual
PrintStats - If desired, print any statistics.
Reimplemented in clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 137 of file ASTConsumer.h.
Referenced by clang::ParseAST().
shouldSkipFunctionBody()
virtual bool clang::ASTConsumer::shouldSkipFunctionBody (Decl * D) inline virtual
This callback is called for each function if the Parser was initialized with SkipFunctionBodies set to true.
Returns
true if the function's body should be skipped. The function body may be parsed anyway if it is needed (for instance, if it contains the code completion point or is constexpr).
Reimplemented in clang::IncrementalASTConsumer, and clang::MultiplexConsumer.
Definition at line 145 of file ASTConsumer.h.
Referenced by clang::Sema::canSkipFunctionBody().
Friends And Related Symbol Documentation
SemaConsumer
friend class SemaConsumer friend
Definition at line 38 of file ASTConsumer.h.
The documentation for this class was generated from the following files:
include/clang/AST/ASTConsumer.h
lib/AST/ASTConsumer.cpp