clang: clang::ento::RegionOffset Class Reference
clang::ento::RegionOffset Class Reference
Represent a region's offset within the top level base region.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
RegionOffset ()=default
RegionOffset (const MemRegion *r, int64_t off)
const MemRegion * getRegion () const
It might return null.
bool hasSymbolicOffset () const
int64_t getOffset () const
bool isValid () const
Static Public Attributes
static const int64_t Symbolic = std::numeric_limits<int64_t>::max()
Detailed Description
Represent a region's offset within the top level base region.
Definition at line 63 of file MemRegion.h.
Constructor & Destructor Documentation
RegionOffset() [1/2]
clang::ento::RegionOffset::RegionOffset () default
RegionOffset() [2/2]
clang::ento::RegionOffset::RegionOffset (const MemRegion * r, int64_t off) inline
Definition at line 76 of file MemRegion.h.
References Offset.
Member Function Documentation
getOffset()
int64_t clang::ento::RegionOffset::getOffset () const inline
Definition at line 83 of file MemRegion.h.
References hasSymbolicOffset(), and Offset.
getRegion()
const MemRegion * clang::ento::RegionOffset::getRegion () const inline
It might return null.
Definition at line 79 of file MemRegion.h.
hasSymbolicOffset()
bool clang::ento::RegionOffset::hasSymbolicOffset () const inline
Definition at line 81 of file MemRegion.h.
References Offset, and Symbolic.
Referenced by getOffset().
isValid()
bool clang::ento::RegionOffset::isValid () const inline
Definition at line 88 of file MemRegion.h.
Member Data Documentation
Symbolic
const int64_t clang::ento::RegionOffset::Symbolic = std::numeric_limits<int64_t>::max() static
Definition at line 73 of file MemRegion.h.
Referenced by calculateOffset(), and hasSymbolicOffset().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h