clang: clang::extractapi::SymbolGraphSerializer Class Reference
clang::extractapi::SymbolGraphSerializer Class Reference
The visitor that organizes API information in the Symbol Graph format.
#include "clang/ExtractAPI/Serialization/SymbolGraphSerializer.h"
Public Types
enum RelationshipKind { MemberOf , InheritsFrom , ConformsTo }
The kind of a relationship between two symbols.
Public Member Functions
Object serialize ()
Serialize the APIs in APISet in the Symbol Graph format.
void serialize (raw_ostream &os)
Wrap serialize(void) and write out the serialized JSON object to os.
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitStructRecord (const StructRecord &Record)
Visit a struct record.
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
void serializeSingleRecord (const APIRecord *Record)
Serialize a single record.
SymbolGraphSerializer (const APISet &API, const APIIgnoresList &IgnoresList, SymbolGraphSerializerOption Options={}, bool ShouldRecurse=true)
Public Member Functions inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
void traverseAPISet ()
void traverseGlobalFunctionRecords ()
void traverseGlobalVariableRecords ()
void traverseEnumRecords ()
void traverseStructRecords ()
void traverseObjCInterfaces ()
void traverseObjCProtocols ()
void traverseMacroDefinitionRecords ()
void traverseTypedefRecords ()
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitStructRecord (const StructRecord &Record)
Visit a struct record.
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
APISetVisitor ()=delete
APISetVisitor (const APISetVisitor &)=delete
APISetVisitor (APISetVisitor &&)=delete
APISetVisitor & operator= (const APISetVisitor &)=delete
APISetVisitor & operator= (APISetVisitor &&)=delete
Static Public Member Functions
static std::optional< Object > serializeSingleSymbolSGF (StringRef USR, const APISet &API)
Serialize a single symbol SGF.
static StringRef getRelationshipString (RelationshipKind Kind)
Get the string representation of the relationship kind.
Protected Attributes
const APIIgnoresList & IgnoresList
The list of symbols to ignore.
SymbolGraphSerializerOption Options
Protected Attributes inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
const APISet & API
Additional Inherited Members
Protected Member Functions inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
APISetVisitor (const APISet &API)
~APISetVisitor ()=default
SymbolGraphSerializer * getDerived ()
Detailed Description
The visitor that organizes API information in the Symbol Graph format.
The Symbol Graph format (https://github.com/apple/swift-docc-symbolkit) models an API set as a directed graph, where nodes are symbol declarations, and edges are relationships between the connected symbols.
Definition at line 45 of file SymbolGraphSerializer.h.
Member Enumeration Documentation
RelationshipKind
enum clang::extractapi::SymbolGraphSerializer::RelationshipKind
The kind of a relationship between two symbols.
Enumerator
MemberOf
The source symbol is a member of the target symbol.
For example enum constants are members of the enum, class/instance methods are members of the class, etc.
InheritsFrom
The source symbol is inherited from the target symbol.
ConformsTo
The source symbol conforms to the target symbol.
For example Objective-C protocol conformances.
Definition at line 78 of file SymbolGraphSerializer.h.
Constructor & Destructor Documentation
SymbolGraphSerializer()
clang::extractapi::SymbolGraphSerializer::SymbolGraphSerializer (const APISet & API, const APIIgnoresList & IgnoresList, SymbolGraphSerializerOption Options = {}, bool ShouldRecurse = true) inline
Definition at line 175 of file SymbolGraphSerializer.h.
Member Function Documentation
getRelationshipString()
StringRef SymbolGraphSerializer::getRelationshipString (RelationshipKind Kind) static
Get the string representation of the relationship kind.
Definition at line 641 of file SymbolGraphSerializer.cpp.
References ConformsTo, InheritsFrom, and MemberOf.
serialize() [1/2]
Object SymbolGraphSerializer::serialize (void)
Serialize the APIs in APISet in the Symbol Graph format.
Returns
a JSON object that contains the root of the formatted Symbol Graph.
Definition at line 807 of file SymbolGraphSerializer.cpp.
References clang::extractapi::APISetVisitor< SymbolGraphSerializer >::traverseAPISet().
Referenced by clang::ExtractAPIActionBase::ImplEndSourceFileAction(), and serialize().
serialize() [2/2]
void SymbolGraphSerializer::serialize (raw_ostream & os)
Wrap serialize(void) and write out the serialized JSON object to os.
Definition at line 823 of file SymbolGraphSerializer.cpp.
References clang::extractapi::SymbolGraphSerializerOption::Compact, Options, and serialize().
serializeSingleRecord()
void SymbolGraphSerializer::serializeSingleRecord (const APIRecord * Record)
Serialize a single record.
Definition at line 748 of file SymbolGraphSerializer.cpp.
References MemberOf, clang::extractapi::APIRecord::RK_Enum, clang::extractapi::APIRecord::RK_GlobalFunction, clang::extractapi::APIRecord::RK_GlobalVariable, clang::extractapi::APIRecord::RK_MacroDefinition, clang::extractapi::APIRecord::RK_ObjCInterface, clang::extractapi::APIRecord::RK_ObjCProtocol, clang::extractapi::APIRecord::RK_Struct, clang::extractapi::APIRecord::RK_Typedef, clang::extractapi::APIRecord::RK_Unknown, visitEnumRecord(), visitGlobalFunctionRecord(), visitGlobalVariableRecord(), visitMacroDefinitionRecord(), visitObjCContainerRecord(), visitStructRecord(), and visitTypedefRecord().
Referenced by serializeSingleSymbolSGF().
serializeSingleSymbolSGF()
std::optional< Object > SymbolGraphSerializer::serializeSingleSymbolSGF (StringRef USR, const APISet & API) static
Serialize a single symbol SGF.
This is primarily used for libclang.
Returns
an optional JSON Object representing the payload that libclang expects for providing symbol information for a single symbol. If this is not a known symbol returns std::nullopt.
Definition at line 832 of file SymbolGraphSerializer.cpp.
References clang::extractapi::APISetVisitor< SymbolGraphSerializer >::API, clang::extractapi::APISet::findRecordForUSR(), clang::PresumedLoc::getFilename(), clang::extractapi::APISet::getLanguage(), getLanguageName(), clang::extractapi::APIRecord::IsFromSystemHeader, clang::extractapi::APIRecord::Location, clang::extractapi::APISet::ProductName, serializeSingleRecord(), and clang::extractapi::APIRecord::USR.
visitEnumRecord()
void SymbolGraphSerializer::visitEnumRecord (const EnumRecord & Record)
Visit an enum record.
Definition at line 683 of file SymbolGraphSerializer.cpp.
References Enum.
Referenced by serializeSingleRecord().
visitGlobalFunctionRecord()
void SymbolGraphSerializer::visitGlobalFunctionRecord (const GlobalFunctionRecord & Record)
Visit a global function record.
Definition at line 665 of file SymbolGraphSerializer.cpp.
Referenced by serializeSingleRecord().
visitGlobalVariableRecord()
void SymbolGraphSerializer::visitGlobalVariableRecord (const GlobalVariableRecord & Record)
Visit a global variable record.
Definition at line 674 of file SymbolGraphSerializer.cpp.
Referenced by serializeSingleRecord().
visitMacroDefinitionRecord()
void SymbolGraphSerializer::visitMacroDefinitionRecord (const MacroDefinitionRecord & Record)
Visit a macro definition record.
Definition at line 738 of file SymbolGraphSerializer.cpp.
Referenced by serializeSingleRecord().
visitObjCContainerRecord()
void SymbolGraphSerializer::visitObjCContainerRecord (const ObjCContainerRecord & Record)
Visit an Objective-C container record.
Definition at line 701 of file SymbolGraphSerializer.cpp.
References Category, ConformsTo, and InheritsFrom.
Referenced by serializeSingleRecord().
visitStructRecord()
void SymbolGraphSerializer::visitStructRecord (const StructRecord & Record)
Visit a struct record.
Definition at line 692 of file SymbolGraphSerializer.cpp.
Referenced by serializeSingleRecord().
visitTypedefRecord()
void SymbolGraphSerializer::visitTypedefRecord (const TypedefRecord & Record)
Visit a typedef record.
Definition at line 788 of file SymbolGraphSerializer.cpp.
Referenced by serializeSingleRecord().
Member Data Documentation
IgnoresList
const APIIgnoresList& clang::extractapi::SymbolGraphSerializer::IgnoresList protected
The list of symbols to ignore.
Note: This should be consulted before emitting a symbol.
Definition at line 146 of file SymbolGraphSerializer.h.
Options
SymbolGraphSerializerOption clang::extractapi::SymbolGraphSerializer::Options protected
Definition at line 148 of file SymbolGraphSerializer.h.
Referenced by serialize().
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/Serialization/SymbolGraphSerializer.h
lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp