clang: clang::UsedDeclVisitor< Derived > Class Template Reference
clang::UsedDeclVisitor< Derived > Class Template Reference
#include "/root/llvm-project/clang/lib/Sema/UsedDeclVisitor.h"
Public Types
typedef EvaluatedExprVisitor< Derived > Inherited
Public Member Functions
UsedDeclVisitor (Sema &S)
Derived & asImpl ()
void VisitDeclRefExpr (DeclRefExpr *E)
void VisitMemberExpr (MemberExpr *E)
void VisitCapturedStmt (CapturedStmt *Node)
void VisitCXXBindTemporaryExpr (CXXBindTemporaryExpr *E)
void VisitCXXNewExpr (CXXNewExpr *E)
void VisitCXXDeleteExpr (CXXDeleteExpr *E)
void VisitCXXConstructExpr (CXXConstructExpr *E)
void VisitCXXDefaultArgExpr (CXXDefaultArgExpr *E)
void VisitCXXDefaultInitExpr (CXXDefaultInitExpr *E)
void VisitInitListExpr (InitListExpr *ILE)
void visitUsedDecl (SourceLocation Loc, Decl *D)
Public Member Functions inherited from clang::EvaluatedExprVisitor< Derived >
EvaluatedExprVisitor (const ASTContext &Context)
Public Member Functions inherited from clang::EvaluatedExprVisitorBase< std::add_pointer, Derived >
bool shouldVisitDiscardedStmt () const
EvaluatedExprVisitorBase (const ASTContext &Context)
void VisitDeclRefExpr (PTR(DeclRefExpr) E)
void VisitOffsetOfExpr (PTR(OffsetOfExpr) E)
void VisitUnaryExprOrTypeTraitExpr (PTR(UnaryExprOrTypeTraitExpr) E)
void VisitExpressionTraitExpr (PTR(ExpressionTraitExpr) E)
void VisitBlockExpr (PTR(BlockExpr) E)
void VisitCXXUuidofExpr (PTR(CXXUuidofExpr) E)
void VisitCXXNoexceptExpr (PTR(CXXNoexceptExpr) E)
void VisitMemberExpr (PTR(MemberExpr) E)
void VisitChooseExpr (PTR(ChooseExpr) E)
void VisitGenericSelectionExpr (PTR(GenericSelectionExpr) E)
void VisitDesignatedInitExpr (PTR(DesignatedInitExpr) E)
void VisitCXXTypeidExpr (PTR(CXXTypeidExpr) E)
void VisitCallExpr (PTR(CallExpr) CE)
void VisitLambdaExpr (PTR(LambdaExpr) LE)
void VisitStmt (PTR(Stmt) S)
The basis case walks all of the children of the statement or expression, assuming they are all potentially evaluated.
void VisitIfStmt (PTR(IfStmt) If)
Derived & getDerived ()
Public Member Functions inherited from clang::StmtVisitorBase< std::add_pointer, Derived, void >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Protected Attributes
Sema & S
Protected Attributes inherited from clang::EvaluatedExprVisitorBase< std::add_pointer, Derived >
const ASTContext & Context
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< std::add_pointer, Derived, void >
ParamTys P
Detailed Description
template<class Derived>
class clang::UsedDeclVisitor< Derived >
Definition at line 21 of file UsedDeclVisitor.h.
Member Typedef Documentation
Inherited
template<class Derived > EvaluatedExprVisitor<Derived> clang::UsedDeclVisitor< Derived >::Inherited
Definition at line 26 of file UsedDeclVisitor.h.
Constructor & Destructor Documentation
UsedDeclVisitor()
template<class Derived > clang::UsedDeclVisitor< Derived >::UsedDeclVisitor (Sema & S) inline
Definition at line 28 of file UsedDeclVisitor.h.
Member Function Documentation
asImpl()
template<class Derived > Derived & clang::UsedDeclVisitor< Derived >::asImpl () inline
Definition at line 30 of file UsedDeclVisitor.h.
Referenced by clang::UsedDeclVisitor< Derived >::VisitCapturedStmt(), clang::UsedDeclVisitor< Derived >::VisitCXXBindTemporaryExpr(), clang::UsedDeclVisitor< Derived >::VisitCXXConstructExpr(), clang::UsedDeclVisitor< Derived >::VisitCXXDefaultArgExpr(), clang::UsedDeclVisitor< Derived >::VisitCXXDefaultInitExpr(), clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr(), clang::UsedDeclVisitor< Derived >::VisitCXXNewExpr(), clang::UsedDeclVisitor< Derived >::VisitDeclRefExpr(), clang::UsedDeclVisitor< Derived >::VisitInitListExpr(), clang::UsedDeclVisitor< Derived >::VisitMemberExpr(), and clang::UsedDeclVisitor< Derived >::visitUsedDecl().
VisitCapturedStmt()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCapturedStmt (CapturedStmt * Node) inline
Definition at line 47 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), and Node.
VisitCXXBindTemporaryExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXBindTemporaryExpr (CXXBindTemporaryExpr * E) inline
Definition at line 52 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::CXXBindTemporaryExpr::getBeginLoc(), clang::CXXTemporary::getDestructor(), clang::CXXBindTemporaryExpr::getSubExpr(), and clang::CXXBindTemporaryExpr::getTemporary().
VisitCXXConstructExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXConstructExpr (CXXConstructExpr * E) inline
Definition at line 83 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::CXXConstructExpr::getBeginLoc(), clang::CXXConstructExpr::getConstructor(), and clang::CXXConstructorDecl::inits().
VisitCXXDefaultArgExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXDefaultArgExpr (CXXDefaultArgExpr * E) inline
Definition at line 93 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), and clang::CXXDefaultArgExpr::getExpr().
VisitCXXDefaultInitExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXDefaultInitExpr (CXXDefaultInitExpr * E) inline
Definition at line 98 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), and clang::CXXDefaultInitExpr::getExpr().
VisitCXXDeleteExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr (CXXDeleteExpr * E) inline
Definition at line 67 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::cast(), clang::Sema::Context, clang::Type::getAs(), clang::ASTContext::getBaseElementType(), clang::CXXDeleteExpr::getBeginLoc(), clang::CXXDeleteExpr::getDestroyedType(), clang::CXXDeleteExpr::getOperatorDelete(), clang::QualType::isNull(), clang::Sema::LookupDestructor(), and clang::UsedDeclVisitor< Derived >::S.
VisitCXXNewExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitCXXNewExpr (CXXNewExpr * E) inline
Definition at line 59 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::CXXNewExpr::getBeginLoc(), clang::CXXNewExpr::getOperatorDelete(), and clang::CXXNewExpr::getOperatorNew().
VisitDeclRefExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitDeclRefExpr (DeclRefExpr * E) inline
Definition at line 32 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::DeclRefExpr::getDecl(), and clang::DeclRefExpr::getLocation().
VisitInitListExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitInitListExpr (InitListExpr * ILE) inline
Definition at line 103 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::InitListExpr::getArrayFiller(), and clang::InitListExpr::hasArrayFiller().
VisitMemberExpr()
template<class Derived > void clang::UsedDeclVisitor< Derived >::VisitMemberExpr (MemberExpr * E) inline
Definition at line 39 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), clang::MemberExpr::getBase(), clang::MemberExpr::getMemberDecl(), and clang::MemberExpr::getMemberLoc().
visitUsedDecl()
template<class Derived > void clang::UsedDeclVisitor< Derived >::visitUsedDecl (SourceLocation Loc, Decl * D) inline
Definition at line 109 of file UsedDeclVisitor.h.
References clang::UsedDeclVisitor< Derived >::asImpl(), and clang::UsedDeclVisitor< Derived >::S.
Member Data Documentation
S
template<class Derived > Sema& clang::UsedDeclVisitor< Derived >::S protected
Definition at line 23 of file UsedDeclVisitor.h.
Referenced by clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr(), and clang::UsedDeclVisitor< Derived >::visitUsedDecl().
The documentation for this class was generated from the following file:
lib/Sema/UsedDeclVisitor.h