clang: clang::TypeInfoLValue Class Reference
clang::TypeInfoLValue Class Reference
Symbolic representation of typeid(T) for some type T.
#include "clang/AST/APValue.h"
Public Member Functions
TypeInfoLValue ()
TypeInfoLValue (const Type *T)
The identity of a type_info object depends on the canonical unqualified type only.
const Type * getType () const
operator bool () const
void * getOpaqueValue ()
void print (llvm::raw_ostream &Out, const PrintingPolicy &Policy) const
Static Public Member Functions
static TypeInfoLValue getFromOpaqueValue (void *Value)
Detailed Description
Symbolic representation of typeid(T) for some type T.
Definition at line 44 of file APValue.h.
Constructor & Destructor Documentation
TypeInfoLValue() [1/2]
clang::TypeInfoLValue::TypeInfoLValue () inline
Definition at line 48 of file APValue.h.
TypeInfoLValue() [2/2]
TypeInfoLValue::TypeInfoLValue (const Type * T) explicit
The identity of a type_info object depends on the canonical unqualified type only.
Definition at line 27 of file APValue.cpp.
Member Function Documentation
getFromOpaqueValue()
static TypeInfoLValue clang::TypeInfoLValue::getFromOpaqueValue (void * Value) inline static
Definition at line 55 of file APValue.h.
References V.
Referenced by llvm::PointerLikeTypeTraits< clang::TypeInfoLValue >::getFromVoidPointer().
getOpaqueValue()
void * clang::TypeInfoLValue::getOpaqueValue () inline
Definition at line 54 of file APValue.h.
getType()
const Type * clang::TypeInfoLValue::getType () const inline
Definition at line 51 of file APValue.h.
Referenced by clang::ASTNodeImporter::ImportAPValue(), and print().
operator bool()
clang::TypeInfoLValue::operator bool () const inline explicit
Definition at line 52 of file APValue.h.
print()
void TypeInfoLValue::print (llvm::raw_ostream & Out, const PrintingPolicy & Policy) const
Definition at line 30 of file APValue.cpp.
References getType(), and clang::QualType::print().
The documentation for this class was generated from the following files:
include/clang/AST/APValue.h
lib/AST/APValue.cpp