clang: clang::ConstructionContext Class Reference
clang::ConstructionContext Class Reference
ConstructionContext's subclasses describe different ways of constructing an object in C++.
#include "clang/Analysis/ConstructionContext.h"
Public Types
enum Kind {
SimpleVariableKind , CXX17ElidedCopyVariableKind , VARIABLE_BEGIN = SimpleVariableKind , VARIABLE_END = CXX17ElidedCopyVariableKind ,
SimpleConstructorInitializerKind , CXX17ElidedCopyConstructorInitializerKind , INITIALIZER_BEGIN = SimpleConstructorInitializerKind , INITIALIZER_END = CXX17ElidedCopyConstructorInitializerKind ,
NewAllocatedObjectKind , SimpleTemporaryObjectKind , ElidedTemporaryObjectKind , TEMPORARY_BEGIN = SimpleTemporaryObjectKind ,
TEMPORARY_END = ElidedTemporaryObjectKind , SimpleReturnedValueKind , CXX17ElidedCopyReturnedValueKind , RETURNED_VALUE_BEGIN = SimpleReturnedValueKind ,
RETURNED_VALUE_END = CXX17ElidedCopyReturnedValueKind , ArgumentKind , LambdaCaptureKind
}
Public Member Functions
Kind getKind () const
virtual const ArrayInitLoopExpr * getArrayInitLoop () const
virtual ~ConstructionContext ()=default
Static Public Member Functions
static const ConstructionContext * createFromLayers (BumpVectorContext &C, const ConstructionContextLayer *TopLayer)
Consume the construction context layer, together with its parent layers, and wrap it up into a complete construction context.
Protected Member Functions
ConstructionContext (Kind K)
Protected Attributes
Kind K
Detailed Description
ConstructionContext's subclasses describe different ways of constructing an object in C++.
The context re-captures the essential parent AST nodes of the CXXConstructExpr it is assigned to and presents these nodes through easy-to-understand accessor methods.
Definition at line 243 of file ConstructionContext.h.
Member Enumeration Documentation
Kind
enum clang::ConstructionContext::Kind
Enumerator
SimpleVariableKind
CXX17ElidedCopyVariableKind
VARIABLE_BEGIN
VARIABLE_END
SimpleConstructorInitializerKind
CXX17ElidedCopyConstructorInitializerKind
INITIALIZER_BEGIN
INITIALIZER_END
NewAllocatedObjectKind
SimpleTemporaryObjectKind
ElidedTemporaryObjectKind
TEMPORARY_BEGIN
TEMPORARY_END
SimpleReturnedValueKind
CXX17ElidedCopyReturnedValueKind
RETURNED_VALUE_BEGIN
RETURNED_VALUE_END
ArgumentKind
LambdaCaptureKind
Definition at line 245 of file ConstructionContext.h.
Constructor & Destructor Documentation
ConstructionContext()
clang::ConstructionContext::ConstructionContext (Kind K) inline explicit protected
Definition at line 272 of file ConstructionContext.h.
~ConstructionContext()
virtual clang::ConstructionContext::~ConstructionContext () virtual default
Member Function Documentation
createFromLayers()
const ConstructionContext * ConstructionContext::createFromLayers (BumpVectorContext & C, const ConstructionContextLayer * TopLayer) static
Consume the construction context layer, together with its parent layers, and wrap it up into a complete construction context.
May return null if layers do not form any supported construction context.
Definition at line 170 of file ConstructionContext.cpp.
References clang::ConstructionContextItem::ArgumentKind, clang::C, clang::cast(), clang::ConstructionContextItem::ElidableConstructorKind, clang::ConstructionContextItem::ElidedDestructorKind, clang::Type::getAsCXXRecordDecl(), clang::QualType::getCanonicalType(), clang::ConstructionContextItem::getCXXCtorInitializer(), clang::ConstructionContextItem::getIndex(), clang::ConstructionContextLayer::getItem(), clang::ConstructionContextItem::getKind(), clang::ConstructionContextLayer::getParent(), clang::ConstructionContextItem::getStmt(), clang::Expr::getType(), clang::CXXRecordDecl::hasNonTrivialDestructor(), clang::ConstructionContextItem::InitializerKind, clang::ConstructionContextLayer::isLast(), clang::ConstructionContextItem::LambdaCaptureKind, clang::ConstructionContextItem::MaterializationKind, clang::ConstructionContextItem::NewAllocatorKind, clang::ConstructionContextItem::ReturnKind, clang::ConstructionContextItem::TemporaryDestructorKind, and clang::ConstructionContextItem::VariableKind.
getArrayInitLoop()
virtual const ArrayInitLoopExpr * clang::ConstructionContext::getArrayInitLoop () const inline virtual
Reimplemented in clang::ConstructorInitializerConstructionContext, clang::LambdaCaptureConstructionContext, and clang::VariableConstructionContext.
Definition at line 309 of file ConstructionContext.h.
getKind()
Kind clang::ConstructionContext::getKind () const inline
Definition at line 307 of file ConstructionContext.h.
References K.
Referenced by clang::ArgumentConstructionContext::classof(), clang::ConstructorInitializerConstructionContext::classof(), clang::CXX17ElidedCopyConstructorInitializerConstructionContext::classof(), clang::CXX17ElidedCopyReturnedValueConstructionContext::classof(), clang::CXX17ElidedCopyVariableConstructionContext::classof(), clang::ElidedTemporaryObjectConstructionContext::classof(), clang::LambdaCaptureConstructionContext::classof(), clang::NewAllocatedObjectConstructionContext::classof(), clang::ReturnedValueConstructionContext::classof(), clang::SimpleConstructorInitializerConstructionContext::classof(), clang::SimpleReturnedValueConstructionContext::classof(), clang::SimpleTemporaryObjectConstructionContext::classof(), clang::SimpleVariableConstructionContext::classof(), clang::TemporaryObjectConstructionContext::classof(), clang::VariableConstructionContext::classof(), clang::ento::ExprEngine::computeObjectUnderConstruction(), print_construction_context(), and clang::ento::ExprEngine::updateObjectsUnderConstruction().
Member Data Documentation
K
Kind clang::ConstructionContext::K protected
Definition at line 268 of file ConstructionContext.h.
Referenced by getKind().
The documentation for this class was generated from the following files:
include/clang/Analysis/ConstructionContext.h
lib/Analysis/ConstructionContext.cpp