clang: clang::OMPIfClause Class Reference
clang::OMPIfClause Class Reference
This represents 'if' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPIfClause (OpenMPDirectiveKind NameModifier, Expr *Cond, Stmt *HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Build 'if' clause with condition Cond.
OMPIfClause ()
Build an empty clause.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
SourceLocation getColonLoc () const
Return the location of ':'.
Expr * getCondition () const
Returns condition.
OpenMPDirectiveKind getNameModifier () const
Return directive name modifier associated with the clause.
SourceLocation getNameModifierLoc () const
Return the location of directive name modifier.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'if' clause in the '#pragma omp ...' directive.
#pragma omp parallel if(parallel:a > 5)
In this example directive '#pragma omp parallel' has simple 'if' clause with condition 'a > 5' and directive name modifier 'parallel'.
Definition at line 527 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPIfClause() [1/2]
clang::OMPIfClause::OMPIfClause (OpenMPDirectiveKind NameModifier, Expr * Cond, Stmt * HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc) inline
Build 'if' clause with condition Cond.
Parameters
NameModifier [OpenMP 4.1] Directive name modifier of clause.
Cond Condition of the clause.
HelperCond Helper condition for the clause.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
NameModifierLoc Location of directive name modifier.
ColonLoc [OpenMP 4.1] Location of ':'.
EndLoc Ending location of the clause.
Definition at line 570 of file OpenMPClause.h.
References clang::Condition, and clang::OMPClauseWithPreInit::setPreInitStmt().
OMPIfClause() [2/2]
clang::OMPIfClause::OMPIfClause () inline
Build an empty clause.
Definition at line 582 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPIfClause::children () inline
Definition at line 604 of file OpenMPClause.h.
References clang::Condition.
children() [2/2]
const_child_range clang::OMPIfClause::children () const inline
Definition at line 606 of file OpenMPClause.h.
References clang::Condition.
classof()
static bool clang::OMPIfClause::classof (const OMPClause * T) inline static
Definition at line 616 of file OpenMPClause.h.
getColonLoc()
SourceLocation clang::OMPIfClause::getColonLoc () const inline
Return the location of ':'.
Definition at line 593 of file OpenMPClause.h.
getCondition()
Expr * clang::OMPIfClause::getCondition () const inline
Returns condition.
Definition at line 596 of file OpenMPClause.h.
References clang::Condition.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitNumThreadsForTargetDirective(), and getNumThreads().
getLParenLoc()
SourceLocation clang::OMPIfClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 590 of file OpenMPClause.h.
getNameModifier()
OpenMPDirectiveKind clang::OMPIfClause::getNameModifier () const inline
Return directive name modifier associated with the clause.
Definition at line 599 of file OpenMPClause.h.
getNameModifierLoc()
SourceLocation clang::OMPIfClause::getNameModifierLoc () const inline
Return the location of directive name modifier.
Definition at line 602 of file OpenMPClause.h.
setLParenLoc()
void clang::OMPIfClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 587 of file OpenMPClause.h.
used_children() [1/2]
OMPClause::child_range OMPIfClause::used_children ()
Definition at line 298 of file OpenMPClause.cpp.
References clang::C, getAddrOfExprAsWritten(), and clang::OMPClauseWithPreInit::getPreInitStmt().
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPIfClause::used_children () const inline
Definition at line 611 of file OpenMPClause.h.
References Children, and used_children().
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 528 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp