clang: clang::index::IndexingContext Class Reference
clang::index::IndexingContext Class Reference
#include "/root/llvm-project/clang/lib/Index/IndexingContext.h"
Public Member Functions
IndexingContext (IndexingOptions IndexOpts, IndexDataConsumer &DataConsumer)
const IndexingOptions & getIndexOpts () const
IndexDataConsumer & getDataConsumer ()
void setASTContext (ASTContext &ctx)
bool shouldIndex (const Decl *D)
const LangOptions & getLangOpts () const
bool shouldSuppressRefs () const
bool shouldIndexFunctionLocalSymbols () const
bool shouldIndexImplicitInstantiation () const
bool shouldIndexParametersInDeclarations () const
bool shouldIndexTemplateParameters () const
bool handleDecl (const Decl *D, SymbolRoleSet Roles=SymbolRoleSet(), ArrayRef< SymbolRelation > Relations=std::nullopt)
bool handleDecl (const Decl *D, SourceLocation Loc, SymbolRoleSet Roles=SymbolRoleSet(), ArrayRef< SymbolRelation > Relations=std::nullopt, const DeclContext *DC=nullptr)
bool handleReference (const NamedDecl *D, SourceLocation Loc, const NamedDecl *Parent, const DeclContext *DC, SymbolRoleSet Roles=SymbolRoleSet(), ArrayRef< SymbolRelation > Relations=std::nullopt, const Expr *RefE=nullptr, const Decl *RefD=nullptr)
void handleMacroDefined (const IdentifierInfo &Name, SourceLocation Loc, const MacroInfo &MI)
void handleMacroUndefined (const IdentifierInfo &Name, SourceLocation Loc, const MacroInfo &MI)
void handleMacroReference (const IdentifierInfo &Name, SourceLocation Loc, const MacroInfo &MD)
bool importedModule (const ImportDecl *ImportD)
bool indexDecl (const Decl *D)
void indexTagDecl (const TagDecl *D, ArrayRef< SymbolRelation > Relations=std::nullopt)
void indexTypeSourceInfo (TypeSourceInfo *TInfo, const NamedDecl *Parent, const DeclContext *DC=nullptr, bool isBase=false, bool isIBType=false)
void indexTypeLoc (TypeLoc TL, const NamedDecl *Parent, const DeclContext *DC=nullptr, bool isBase=false, bool isIBType=false)
void indexNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS, const NamedDecl *Parent, const DeclContext *DC=nullptr)
bool indexDeclContext (const DeclContext *DC)
void indexBody (const Stmt *S, const NamedDecl *Parent, const DeclContext *DC=nullptr)
bool indexTopLevelDecl (const Decl *D)
bool indexDeclGroupRef (DeclGroupRef DG)
Static Public Member Functions
static bool isTemplateImplicitInstantiation (const Decl *D)
Detailed Description
Definition at line 38 of file IndexingContext.h.
Constructor & Destructor Documentation
IndexingContext()
clang::index::IndexingContext::IndexingContext (IndexingOptions IndexOpts, IndexDataConsumer & DataConsumer) inline
Definition at line 44 of file IndexingContext.h.
Member Function Documentation
getDataConsumer()
IndexDataConsumer & clang::index::IndexingContext::getDataConsumer () inline
Definition at line 48 of file IndexingContext.h.
getIndexOpts()
const IndexingOptions & clang::index::IndexingContext::getIndexOpts () const inline
Definition at line 47 of file IndexingContext.h.
getLangOpts()
const LangOptions & IndexingContext::getLangOpts () const
Definition at line 32 of file IndexingContext.cpp.
References clang::ASTContext::getLangOpts().
handleDecl() [1/2]
bool IndexingContext::handleDecl (const Decl * D, SourceLocation Loc, SymbolRoleSet Roles = SymbolRoleSet(), ArrayRef< SymbolRelation > Relations = std::nullopt, const DeclContext * DC = nullptr)
Definition at line 58 of file IndexingContext.cpp.
References clang::cast(), and clang::Decl::getDeclContext().
handleDecl() [2/2]
bool IndexingContext::handleDecl (const Decl * D, SymbolRoleSet Roles = SymbolRoleSet(), ArrayRef< SymbolRelation > Relations = std::nullopt)
Definition at line 52 of file IndexingContext.cpp.
References clang::Decl::getLocation(), and handleDecl().
Referenced by handleDecl(), and indexTagDecl().
handleMacroDefined()
void IndexingContext::handleMacroDefined (const IdentifierInfo & Name, SourceLocation Loc, const MacroInfo & MI)
Definition at line 453 of file IndexingContext.cpp.
References clang::index::Definition, and clang::index::IndexDataConsumer::handleMacroOccurrence().
handleMacroReference()
void IndexingContext::handleMacroReference (const IdentifierInfo & Name, SourceLocation Loc, const MacroInfo & MD)
Definition at line 471 of file IndexingContext.cpp.
References clang::index::IndexDataConsumer::handleMacroOccurrence(), and clang::index::Reference.
handleMacroUndefined()
void IndexingContext::handleMacroUndefined (const IdentifierInfo & Name, SourceLocation Loc, const MacroInfo & MI)
Definition at line 462 of file IndexingContext.cpp.
References clang::index::IndexDataConsumer::handleMacroOccurrence(), and clang::index::Undefinition.
handleReference()
bool IndexingContext::handleReference (const NamedDecl * D, SourceLocation Loc, const NamedDecl * Parent, const DeclContext * DC, SymbolRoleSet Roles = SymbolRoleSet(), ArrayRef< SymbolRelation > Relations = std::nullopt, const Expr * RefE = nullptr, const Decl * RefD = nullptr)
Definition at line 74 of file IndexingContext.cpp.
References clang::index::isFunctionLocalSymbol(), Parent, shouldIndexFunctionLocalSymbols(), and shouldIndexTemplateParameters().
Referenced by indexNestedNameSpecifierLoc().
importedModule()
bool IndexingContext::importedModule (const ImportDecl * ImportD)
Definition at line 105 of file IndexingContext.cpp.
References clang::index::IndexingOptions::All, clang::SrcMgr::C_User, clang::index::Declaration, clang::index::IndexingOptions::DeclarationsOnly, clang::SrcMgr::SLocEntry::getFile(), clang::SrcMgr::FileInfo::getFileCharacteristic(), clang::ImportDecl::getIdentifierLocs(), clang::ImportDecl::getImportedModule(), clang::Decl::getLocation(), clang::ASTContext::getSourceManager(), clang::index::IndexDataConsumer::handleModuleOccurrence(), clang::index::Implicit, clang::Invalid, clang::SrcMgr::SLocEntry::isFile(), clang::Decl::isImplicit(), clang::FileID::isInvalid(), clang::Decl::isInvalidDecl(), clang::index::IndexingOptions::None, clang::Module::Parent, reportModuleReferences(), SM, and clang::index::IndexingOptions::SystemSymbolFilter.
indexBody()
void IndexingContext::indexBody (const Stmt * S, const NamedDecl * Parent, const DeclContext * DC = nullptr)
Definition at line 501 of file IndexBody.cpp.
References Parent.
indexDecl()
bool IndexingContext::indexDecl (const Decl * D)
Definition at line 775 of file IndexDecl.cpp.
References indexDeclContext(), clang::Decl::isImplicit(), isTemplateImplicitInstantiation(), and shouldIndexImplicitInstantiation().
Referenced by indexDeclContext(), and indexTopLevelDecl().
indexDeclContext()
bool IndexingContext::indexDeclContext (const DeclContext * DC)
Definition at line 793 of file IndexDecl.cpp.
References clang::DeclContext::decls(), and indexDecl().
Referenced by indexDecl(), and indexTagDecl().
indexDeclGroupRef()
bool IndexingContext::indexDeclGroupRef (DeclGroupRef DG)
Definition at line 813 of file IndexDecl.cpp.
References clang::DeclGroupRef::begin(), clang::DeclGroupRef::end(), and indexTopLevelDecl().
indexNestedNameSpecifierLoc()
void IndexingContext::indexNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS, const NamedDecl * Parent, const DeclContext * DC = nullptr)
Definition at line 269 of file IndexTypeSourceInfo.cpp.
References clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getKind(), clang::NestedNameSpecifierLoc::getLocalBeginLoc(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getPrefix(), clang::NestedNameSpecifierLoc::getTypeLoc(), clang::NestedNameSpecifier::Global, handleReference(), clang::NestedNameSpecifier::Identifier, indexNestedNameSpecifierLoc(), indexTypeLoc(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, Parent, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by indexNestedNameSpecifierLoc(), and indexTagDecl().
indexTagDecl()
void IndexingContext::indexTagDecl (const TagDecl * D, ArrayRef< SymbolRelation > Relations = std::nullopt)
Definition at line 304 of file IndexTypeSourceInfo.cpp.
References clang::TagDecl::getQualifierLoc(), handleDecl(), indexDeclContext(), indexNestedNameSpecifierLoc(), indexTypeSourceInfo(), clang::index::isFunctionLocalSymbol(), clang::TagDecl::isThisDeclarationADefinition(), shouldIndex(), and shouldIndexFunctionLocalSymbols().
indexTopLevelDecl()
bool IndexingContext::indexTopLevelDecl (const Decl * D)
Definition at line 800 of file IndexDecl.cpp.
References clang::Decl::getLocation(), indexDecl(), clang::SourceLocation::isInvalid(), and clang::index::IndexingOptions::ShouldTraverseDecl.
Referenced by indexDeclGroupRef(), clang::index::indexModuleFile(), clang::index::indexTopLevelDecls(), and topLevelDeclVisitor().
indexTypeLoc()
void IndexingContext::indexTypeLoc (TypeLoc TL, const NamedDecl * Parent, const DeclContext * DC = nullptr, bool isBase = false, bool isIBType = false)
Definition at line 256 of file IndexTypeSourceInfo.cpp.
References clang::TypeLoc::isNull(), and Parent.
Referenced by indexNestedNameSpecifierLoc(), and indexTypeSourceInfo().
indexTypeSourceInfo()
void IndexingContext::indexTypeSourceInfo (TypeSourceInfo * TInfo, const NamedDecl * Parent, const DeclContext * DC = nullptr, bool isBase = false, bool isIBType = false)
Definition at line 245 of file IndexTypeSourceInfo.cpp.
References clang::TypeSourceInfo::getTypeLoc(), indexTypeLoc(), clang::TypeLoc::isNull(), and Parent.
Referenced by indexTagDecl().
isTemplateImplicitInstantiation()
bool IndexingContext::isTemplateImplicitInstantiation (const Decl * D) static
Definition at line 149 of file IndexingContext.cpp.
References clang::Decl::getDeclContext(), clang::isa(), isTemplateImplicitInstantiation(), Parent, clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, clang::TSK_ExplicitSpecialization, clang::TSK_ImplicitInstantiation, and clang::TSK_Undeclared.
Referenced by indexDecl(), and isTemplateImplicitInstantiation().
setASTContext()
void clang::index::IndexingContext::setASTContext (ASTContext & ctx) inline
Definition at line 50 of file IndexingContext.h.
Referenced by clang::index::indexASTUnit(), clang::index::indexModuleFile(), and clang::index::indexTopLevelDecls().
shouldIndex()
bool IndexingContext::shouldIndex (const Decl * D)
Definition at line 28 of file IndexingContext.cpp.
References isGeneratedDecl().
Referenced by indexTagDecl().
shouldIndexFunctionLocalSymbols()
bool IndexingContext::shouldIndexFunctionLocalSymbols () const
Definition at line 36 of file IndexingContext.cpp.
References clang::index::IndexingOptions::IndexFunctionLocals.
Referenced by handleReference(), and indexTagDecl().
shouldIndexImplicitInstantiation()
bool IndexingContext::shouldIndexImplicitInstantiation () const
Definition at line 40 of file IndexingContext.cpp.
References clang::index::IndexingOptions::IndexImplicitInstantiation.
Referenced by indexDecl().
shouldIndexParametersInDeclarations()
bool IndexingContext::shouldIndexParametersInDeclarations () const
Definition at line 44 of file IndexingContext.cpp.
References clang::index::IndexingOptions::IndexParametersInDeclarations.
shouldIndexTemplateParameters()
bool IndexingContext::shouldIndexTemplateParameters () const
Definition at line 48 of file IndexingContext.cpp.
References clang::index::IndexingOptions::IndexTemplateParameters.
Referenced by handleReference().
shouldSuppressRefs()
bool clang::index::IndexingContext::shouldSuppressRefs () const inline
Definition at line 56 of file IndexingContext.h.
The documentation for this class was generated from the following files:
lib/Index/IndexingContext.h
lib/Index/IndexBody.cpp
lib/Index/IndexDecl.cpp
lib/Index/IndexingContext.cpp
lib/Index/IndexTypeSourceInfo.cpp