clang: clang::comments::TParamCommandComment Class Reference
clang::comments::TParamCommandComment Class Reference
Doxygen \tparam command, describes a template parameter.
#include "clang/AST/Comment.h"
Public Member Functions
TParamCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
bool hasParamName () const
StringRef getParamName (const FullComment *FC) const
StringRef getParamNameAsWritten () const
SourceRange getParamNameRange () const
bool isPositionValid () const LLVM_READONLY
unsigned getDepth () const
unsigned getIndex (unsigned Depth) const
void setPosition (ArrayRef< unsigned > NewPosition)
Public Member Functions inherited from clang::comments::BlockCommandComment
BlockCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
child_iterator child_begin () const
child_iterator child_end () const
unsigned getCommandID () const
StringRef getCommandName (const CommandTraits &Traits) const
SourceLocation getCommandNameBeginLoc () const
SourceRange getCommandNameRange (const CommandTraits &Traits) const
unsigned getNumArgs () const
StringRef getArgText (unsigned Idx) const
SourceRange getArgRange (unsigned Idx) const
void setArgs (ArrayRef< Argument > A)
ParagraphComment * getParagraph () const LLVM_READONLY
bool hasNonWhitespaceParagraph () const
void setParagraph (ParagraphComment *PC)
CommandMarkerKind getCommandMarker () const LLVM_READONLY
Public Member Functions inherited from clang::comments::Comment
Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
CommentKind getCommentKind () const
const char * getCommentKindName () const
void dump () const
void dumpColor () const
void dump (raw_ostream &OS, const ASTContext &Context) const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const LLVM_READONLY
child_iterator child_begin () const
child_iterator child_end () const
unsigned child_count () const
Static Public Member Functions
static bool classof (const Comment *C)
Static Public Member Functions inherited from clang::comments::BlockCommandComment
static bool classof (const Comment *C)
Static Public Member Functions inherited from clang::comments::BlockContentComment
static bool classof (const Comment *C)
Additional Inherited Members
Public Types inherited from clang::comments::Comment
enum CommentKind { NoCommentKind = 0 }
typedef Comment *const * child_iterator
Public Attributes inherited from clang::comments::Comment
Protected Types inherited from clang::comments::Comment
enum { NumCommentBits = 8 }
enum { NumInlineContentCommentBits = NumCommentBits + 1 }
enum { NumTextCommentBits = NumInlineContentCommentBits + 2 }
enum { NumInlineCommandCommentBits }
enum { NumHTMLTagCommentBits = NumInlineContentCommentBits + 1 }
enum { NumHTMLStartTagCommentBits = NumHTMLTagCommentBits + 1 }
enum { NumParagraphCommentBits = NumCommentBits + 2 }
enum { NumBlockCommandCommentBits }
enum { NumParamCommandCommentBits = NumBlockCommandCommentBits + 3 }
Protected Member Functions inherited from clang::comments::BlockCommandComment
BlockCommandComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Protected Member Functions inherited from clang::comments::BlockContentComment
BlockContentComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
Protected Member Functions inherited from clang::comments::Comment
void setSourceRange (SourceRange SR)
void setLocation (SourceLocation L)
Protected Attributes inherited from clang::comments::BlockCommandComment
ArrayRef< Argument > Args
Word-like arguments.
ParagraphComment * Paragraph
Paragraph argument.
Protected Attributes inherited from clang::comments::Comment
SourceLocation Loc
Preferred location to show caret.
SourceRange Range
Source range of this AST node.
union {
CommentBitfields CommentBits
InlineContentCommentBitfields InlineContentCommentBits
TextCommentBitfields TextCommentBits
InlineCommandCommentBitfields InlineCommandCommentBits
HTMLTagCommentBitfields HTMLTagCommentBits
HTMLStartTagCommentBitfields HTMLStartTagCommentBits
ParagraphCommentBitfields ParagraphCommentBits
BlockCommandCommentBitfields BlockCommandCommentBits
ParamCommandCommentBitfields ParamCommandCommentBits
};
Detailed Description
Doxygen \tparam command, describes a template parameter.
Definition at line 782 of file Comment.h.
Constructor & Destructor Documentation
TParamCommandComment()
clang::comments::TParamCommandComment::TParamCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker) inline
Definition at line 799 of file Comment.h.
Member Function Documentation
classof()
static bool clang::comments::TParamCommandComment::classof (const Comment * C) inline static
Definition at line 807 of file Comment.h.
References clang::C.
getDepth()
unsigned clang::comments::TParamCommandComment::getDepth () const inline
Definition at line 829 of file Comment.h.
References isPositionValid().
Referenced by getParamName().
getIndex()
unsigned clang::comments::TParamCommandComment::getIndex (unsigned Depth) const inline
Definition at line 834 of file Comment.h.
References isPositionValid().
Referenced by getParamName().
getParamName()
StringRef clang::comments::TParamCommandComment::getParamName (const FullComment * FC) const
Definition at line 371 of file Comment.cpp.
References clang::comments::FullComment::getDeclInfo(), getDepth(), getIndex(), clang::NamedDecl::getName(), clang::TemplateParameterList::getParam(), isPositionValid(), and clang::comments::DeclInfo::TemplateParameters.
getParamNameAsWritten()
StringRef clang::comments::TParamCommandComment::getParamNameAsWritten () const inline
Definition at line 817 of file Comment.h.
References clang::comments::BlockCommandComment::Args.
getParamNameRange()
SourceRange clang::comments::TParamCommandComment::getParamNameRange () const inline
Definition at line 821 of file Comment.h.
References clang::comments::BlockCommandComment::Args.
Referenced by clang::comments::Sema::actOnTParamCommandParamNameArg().
hasParamName()
bool clang::comments::TParamCommandComment::hasParamName () const inline
Definition at line 811 of file Comment.h.
References clang::comments::BlockCommandComment::getNumArgs().
isPositionValid()
bool clang::comments::TParamCommandComment::isPositionValid () const inline
Definition at line 825 of file Comment.h.
Referenced by getDepth(), getIndex(), getParamName(), and setPosition().
setPosition()
void clang::comments::TParamCommandComment::setPosition (ArrayRef< unsigned > NewPosition) inline
Definition at line 839 of file Comment.h.
References isPositionValid().
Referenced by clang::comments::Sema::actOnTParamCommandParamNameArg().
The documentation for this class was generated from the following files:
include/clang/AST/Comment.h
lib/AST/Comment.cpp