clang: clang::ASTDeclReader Class Reference
clang::ASTDeclReader Class Reference
Public Member Functions
ASTDeclReader (ASTReader &Reader, ASTRecordReader &Record, ASTReader::RecordLocation Loc, DeclID thisDeclID, SourceLocation ThisDeclLoc)
bool hasPendingBody () const
Determine whether this declaration has a pending body.
void ReadFunctionDefinition (FunctionDecl *FD)
void Visit (Decl *D)
void UpdateDecl (Decl *D, SmallVectorImpl< serialization::DeclID > &)
void VisitDecl (Decl *D)
void VisitPragmaCommentDecl (PragmaCommentDecl *D)
void VisitPragmaDetectMismatchDecl (PragmaDetectMismatchDecl *D)
void VisitTranslationUnitDecl (TranslationUnitDecl *TU)
void VisitNamedDecl (NamedDecl *ND)
void VisitLabelDecl (LabelDecl *LD)
void VisitNamespaceDecl (NamespaceDecl *D)
void VisitHLSLBufferDecl (HLSLBufferDecl *D)
void VisitUsingDirectiveDecl (UsingDirectiveDecl *D)
void VisitNamespaceAliasDecl (NamespaceAliasDecl *D)
void VisitTypeDecl (TypeDecl *TD)
RedeclarableResult VisitTypedefNameDecl (TypedefNameDecl *TD)
void VisitTypedefDecl (TypedefDecl *TD)
void VisitTypeAliasDecl (TypeAliasDecl *TD)
void VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl *D)
void VisitUnresolvedUsingIfExistsDecl (UnresolvedUsingIfExistsDecl *D)
RedeclarableResult VisitTagDecl (TagDecl *TD)
void VisitEnumDecl (EnumDecl *ED)
RedeclarableResult VisitRecordDeclImpl (RecordDecl *RD)
void VisitRecordDecl (RecordDecl *RD)
RedeclarableResult VisitCXXRecordDeclImpl (CXXRecordDecl *D)
void VisitCXXRecordDecl (CXXRecordDecl *D)
RedeclarableResult VisitClassTemplateSpecializationDeclImpl (ClassTemplateSpecializationDecl *D)
void VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl *D)
void VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl *D)
void VisitClassScopeFunctionSpecializationDecl (ClassScopeFunctionSpecializationDecl *D)
RedeclarableResult VisitVarTemplateSpecializationDeclImpl (VarTemplateSpecializationDecl *D)
TODO: Unify with ClassTemplateSpecializationDecl version? May require unifying ClassTemplate(Partial)SpecializationDecl and VarTemplate(Partial)SpecializationDecl with a new data structure Template(Partial)SpecializationDecl, and using Template(Partial)SpecializationDecl as input type.
void VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl *D)
void VisitVarTemplatePartialSpecializationDecl (VarTemplatePartialSpecializationDecl *D)
TODO: Unify with ClassTemplatePartialSpecializationDecl version? May require unifying ClassTemplate(Partial)SpecializationDecl and VarTemplate(Partial)SpecializationDecl with a new data structure Template(Partial)SpecializationDecl, and using Template(Partial)SpecializationDecl as input type.
void VisitTemplateTypeParmDecl (TemplateTypeParmDecl *D)
void VisitValueDecl (ValueDecl *VD)
void VisitEnumConstantDecl (EnumConstantDecl *ECD)
void VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl *D)
void VisitDeclaratorDecl (DeclaratorDecl *DD)
void VisitFunctionDecl (FunctionDecl *FD)
void VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl *GD)
void VisitCXXMethodDecl (CXXMethodDecl *D)
void VisitCXXConstructorDecl (CXXConstructorDecl *D)
void VisitCXXDestructorDecl (CXXDestructorDecl *D)
void VisitCXXConversionDecl (CXXConversionDecl *D)
void VisitFieldDecl (FieldDecl *FD)
void VisitMSPropertyDecl (MSPropertyDecl *FD)
void VisitMSGuidDecl (MSGuidDecl *D)
void VisitUnnamedGlobalConstantDecl (UnnamedGlobalConstantDecl *D)
void VisitTemplateParamObjectDecl (TemplateParamObjectDecl *D)
void VisitIndirectFieldDecl (IndirectFieldDecl *FD)
RedeclarableResult VisitVarDeclImpl (VarDecl *D)
void ReadVarDeclInit (VarDecl *VD)
void VisitVarDecl (VarDecl *VD)
void VisitImplicitParamDecl (ImplicitParamDecl *PD)
void VisitParmVarDecl (ParmVarDecl *PD)
void VisitDecompositionDecl (DecompositionDecl *DD)
void VisitBindingDecl (BindingDecl *BD)
void VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl *D)
void VisitTemplateDecl (TemplateDecl *D)
void VisitConceptDecl (ConceptDecl *D)
void VisitImplicitConceptSpecializationDecl (ImplicitConceptSpecializationDecl *D)
void VisitRequiresExprBodyDecl (RequiresExprBodyDecl *D)
RedeclarableResult VisitRedeclarableTemplateDecl (RedeclarableTemplateDecl *D)
void VisitClassTemplateDecl (ClassTemplateDecl *D)
void VisitBuiltinTemplateDecl (BuiltinTemplateDecl *D)
void VisitVarTemplateDecl (VarTemplateDecl *D)
TODO: Unify with ClassTemplateDecl version? May require unifying ClassTemplateDecl and VarTemplateDecl beyond TemplateDecl...
void VisitFunctionTemplateDecl (FunctionTemplateDecl *D)
void VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl *D)
void VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl *D)
void VisitUsingDecl (UsingDecl *D)
void VisitUsingEnumDecl (UsingEnumDecl *D)
void VisitUsingPackDecl (UsingPackDecl *D)
void VisitUsingShadowDecl (UsingShadowDecl *D)
void VisitConstructorUsingShadowDecl (ConstructorUsingShadowDecl *D)
void VisitLinkageSpecDecl (LinkageSpecDecl *D)
void VisitExportDecl (ExportDecl *D)
void VisitFileScopeAsmDecl (FileScopeAsmDecl *AD)
void VisitTopLevelStmtDecl (TopLevelStmtDecl *D)
void VisitImportDecl (ImportDecl *D)
void VisitAccessSpecDecl (AccessSpecDecl *D)
void VisitFriendDecl (FriendDecl *D)
void VisitFriendTemplateDecl (FriendTemplateDecl *D)
void VisitStaticAssertDecl (StaticAssertDecl *D)
void VisitBlockDecl (BlockDecl *BD)
void VisitCapturedDecl (CapturedDecl *CD)
void VisitEmptyDecl (EmptyDecl *D)
void VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl *D)
std::pair< uint64_t, uint64_t > VisitDeclContext (DeclContext *DC)
template<typename T >
RedeclarableResult VisitRedeclarable (Redeclarable< T > *D)
template<typename T >
void mergeRedeclarable (Redeclarable< T > *D, RedeclarableResult &Redecl)
Attempts to merge the given declaration (D) with another declaration of the same entity.
void mergeLambda (CXXRecordDecl *D, RedeclarableResult &Redecl, Decl *Context, unsigned Number)
Attempt to merge D with a previous declaration of the same lambda, which is found by its index within its context declaration, if it has one.
void mergeRedeclarableTemplate (RedeclarableTemplateDecl *D, RedeclarableResult &Redecl)
template<typename T >
void mergeRedeclarable (Redeclarable< T > *D, T *Existing, RedeclarableResult &Redecl)
Attempts to merge the given declaration (D) with another declaration of the same entity.
template<typename T >
void mergeMergeable (Mergeable< T > *D)
Attempts to merge the given declaration (D) with another declaration of the same entity, for the case where the entity is not actually redeclarable.
void mergeMergeable (LifetimeExtendedTemporaryDecl *D)
Attempts to merge LifetimeExtendedTemporaryDecl with identical class definitions from two different modules.
void mergeTemplatePattern (RedeclarableTemplateDecl *D, RedeclarableTemplateDecl *Existing, bool IsKeyDecl)
Merge together the pattern declarations from two template declarations.
ObjCTypeParamList * ReadObjCTypeParamList ()
void VisitObjCMethodDecl (ObjCMethodDecl *D)
void VisitObjCTypeParamDecl (ObjCTypeParamDecl *D)
void VisitObjCContainerDecl (ObjCContainerDecl *D)
void VisitObjCInterfaceDecl (ObjCInterfaceDecl *D)
void VisitObjCIvarDecl (ObjCIvarDecl *D)
void VisitObjCProtocolDecl (ObjCProtocolDecl *D)
void VisitObjCAtDefsFieldDecl (ObjCAtDefsFieldDecl *D)
void VisitObjCCategoryDecl (ObjCCategoryDecl *D)
void VisitObjCImplDecl (ObjCImplDecl *D)
void VisitObjCCategoryImplDecl (ObjCCategoryImplDecl *D)
void VisitObjCImplementationDecl (ObjCImplementationDecl *D)
void VisitObjCCompatibleAliasDecl (ObjCCompatibleAliasDecl *D)
void VisitObjCPropertyDecl (ObjCPropertyDecl *D)
void VisitObjCPropertyImplDecl (ObjCPropertyImplDecl *D)
void VisitOMPThreadPrivateDecl (OMPThreadPrivateDecl *D)
void VisitOMPAllocateDecl (OMPAllocateDecl *D)
void VisitOMPDeclareReductionDecl (OMPDeclareReductionDecl *D)
void VisitOMPDeclareMapperDecl (OMPDeclareMapperDecl *D)
void VisitOMPRequiresDecl (OMPRequiresDecl *D)
void VisitOMPCapturedExprDecl (OMPCapturedExprDecl *D)
template<>
void attachPreviousDeclImpl (ASTReader &Reader, Redeclarable< VarDecl > *D, Decl *Previous, Decl *Canon)
template<>
void attachPreviousDeclImpl (ASTReader &Reader, Redeclarable< FunctionDecl > *D, Decl *Previous, Decl *Canon)
Public Member Functions inherited from clang::declvisitor::Base< std::add_pointer, ASTDeclReader, void >
void Visit (PTR(Decl) D)
void VisitDecl (PTR(Decl) D)
Static Public Member Functions
template<typename T >
static void AddLazySpecializations (T *D, SmallVectorImpl< serialization::DeclID > &IDs)
template<typename DeclT >
static Decl * getMostRecentDeclImpl (Redeclarable< DeclT > *D)
static Decl * getMostRecentDeclImpl (...)
static Decl * getMostRecentDecl (Decl *D)
static void mergeInheritableAttributes (ASTReader &Reader, Decl *D, Decl *Previous)
template<typename DeclT >
static void attachPreviousDeclImpl (ASTReader &Reader, Redeclarable< DeclT > *D, Decl *Previous, Decl *Canon)
static void attachPreviousDeclImpl (ASTReader &Reader,...)
static void attachPreviousDecl (ASTReader &Reader, Decl *D, Decl *Previous, Decl *Canon)
template<typename DeclT >
static void attachLatestDeclImpl (Redeclarable< DeclT > *D, Decl *Latest)
static void attachLatestDeclImpl (...)
static void attachLatestDecl (Decl *D, Decl *latest)
template<typename DeclT >
static void markIncompleteDeclChainImpl (Redeclarable< DeclT > *D)
static void markIncompleteDeclChainImpl (...)
static void setNextObjCCategory (ObjCCategoryDecl *Cat, ObjCCategoryDecl *Next)
Detailed Description
Definition at line 82 of file ASTReaderDecl.cpp.
Constructor & Destructor Documentation
ASTDeclReader()
clang::ASTDeclReader::ASTDeclReader (ASTReader & Reader, ASTRecordReader & Record, ASTReader::RecordLocation Loc, DeclID thisDeclID, SourceLocation ThisDeclLoc) inline
Definition at line 261 of file ASTReaderDecl.cpp.
Member Function Documentation
AddLazySpecializations()
template<typename T > static void clang::ASTDeclReader::AddLazySpecializations (T * D, SmallVectorImpl< serialization::DeclID > & IDs) inline static
Definition at line 268 of file ASTReaderDecl.cpp.
References clang::C, and clang::Result.
Referenced by VisitClassTemplateDecl(), VisitFunctionTemplateDecl(), and VisitVarTemplateDecl().
attachLatestDecl()
void ASTDeclReader::attachLatestDecl (Decl * D, Decl * latest) static
Definition at line 3704 of file ASTReaderDecl.cpp.
References clang::Decl::getKind().
attachLatestDeclImpl() [1/2]
void ASTDeclReader::attachLatestDeclImpl (...) static
Definition at line 3700 of file ASTReaderDecl.cpp.
attachLatestDeclImpl() [2/2]
template<typename DeclT > void ASTDeclReader::attachLatestDeclImpl (Redeclarable< DeclT > * D, Decl * Latest) static
Definition at line 3696 of file ASTReaderDecl.cpp.
References clang::Redeclarable< decl_type >::RedeclLink, and clang::Redeclarable< decl_type >::DeclLink::setLatest().
attachPreviousDecl()
void ASTDeclReader::attachPreviousDecl (ASTReader & Reader, Decl * D, Decl * Previous, Decl * Canon) static
Definition at line 3660 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::Decl::getKind(), clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_Tag, clang::Decl::IDNS_Type, inheritDefaultTemplateArguments(), mergeInheritableAttributes(), and Previous.
attachPreviousDeclImpl() [1/4]
template<typename DeclT > void ASTDeclReader::attachPreviousDeclImpl (ASTReader & Reader, Redeclarable< DeclT > * D, Decl * Previous, Decl * Canon) static
Definition at line 3530 of file ASTReaderDecl.cpp.
References clang::cast(), clang::Redeclarable< decl_type >::First, Previous, clang::Redeclarable< decl_type >::RedeclLink, and clang::Redeclarable< decl_type >::DeclLink::setPrevious().
attachPreviousDeclImpl() [2/4]
template<> void clang::ASTDeclReader::attachPreviousDeclImpl (ASTReader & Reader, Redeclarable< FunctionDecl > * D, Decl * Previous, Decl * Canon)
Definition at line 3568 of file ASTReaderDecl.cpp.
References clang::cast(), clang::Type::getAs(), clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionType::getReturnType(), clang::isUndeducedReturnType(), clang::isUnresolvedExceptionSpec(), and Previous.
attachPreviousDeclImpl() [3/4]
template<> void clang::ASTDeclReader::attachPreviousDeclImpl (ASTReader & Reader, Redeclarable< VarDecl > * D, Decl * Previous, Decl * Canon)
Definition at line 3540 of file ASTReaderDecl.cpp.
References clang::cast(), clang::VarDecl::Definition, clang::Redeclarable< decl_type >::First, clang::Redeclarable< decl_type >::getPreviousDecl(), clang::ASTReader::mergeDefinitionVisibility(), Previous, clang::Redeclarable< decl_type >::RedeclLink, and clang::Redeclarable< decl_type >::DeclLink::setPrevious().
attachPreviousDeclImpl() [4/4]
void ASTDeclReader::attachPreviousDeclImpl (ASTReader & Reader, ...) static
Definition at line 3623 of file ASTReaderDecl.cpp.
getMostRecentDecl()
Decl * ASTDeclReader::getMostRecentDecl (Decl * D) static
Definition at line 3492 of file ASTReaderDecl.cpp.
References clang::Decl::getKind().
getMostRecentDeclImpl() [1/2]
Decl * ASTDeclReader::getMostRecentDeclImpl (...) static
Definition at line 3488 of file ASTReaderDecl.cpp.
getMostRecentDeclImpl() [2/2]
template<typename DeclT > Decl * ASTDeclReader::getMostRecentDeclImpl (Redeclarable< DeclT > * D) static
Definition at line 3484 of file ASTReaderDecl.cpp.
References clang::Redeclarable< decl_type >::DeclLink::getLatestNotUpdated(), and clang::Redeclarable< decl_type >::RedeclLink.
hasPendingBody()
bool clang::ASTDeclReader::hasPendingBody () const inline
Determine whether this declaration has a pending body.
Definition at line 317 of file ASTReaderDecl.cpp.
markIncompleteDeclChainImpl() [1/2]
void ASTDeclReader::markIncompleteDeclChainImpl (...) static
Definition at line 3722 of file ASTReaderDecl.cpp.
markIncompleteDeclChainImpl() [2/2]
template<typename DeclT > void ASTDeclReader::markIncompleteDeclChainImpl (Redeclarable< DeclT > * D) static
Definition at line 3718 of file ASTReaderDecl.cpp.
References clang::Redeclarable< decl_type >::DeclLink::markIncomplete(), and clang::Redeclarable< decl_type >::RedeclLink.
mergeInheritableAttributes()
void ASTDeclReader::mergeInheritableAttributes (ASTReader & Reader, Decl * D, Decl * Previous) static
Definition at line 3509 of file ASTReaderDecl.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Attr::clone(), clang::ASTReader::getContext(), clang::Decl::hasAttr(), Previous, and clang::InheritableAttr::setInherited().
Referenced by attachPreviousDecl().
mergeLambda()
void ASTDeclReader::mergeLambda (CXXRecordDecl * D, RedeclarableResult & Redecl, Decl * Context, unsigned IndexInContext)
Attempt to merge D with a previous declaration of the same lambda, which is found by its index within its context declaration, if it has one.
We can't look up lambdas in their enclosing lexical or semantic context in general, because for lambdas in variables, both of those might be a namespace or the translation unit.
Definition at line 2820 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::Redeclarable< decl_type >::isFirstDecl(), and mergeRedeclarable().
Referenced by VisitCXXRecordDeclImpl().
mergeMergeable() [1/2]
void ASTDeclReader::mergeMergeable (LifetimeExtendedTemporaryDecl * D)
Attempts to merge LifetimeExtendedTemporaryDecl with identical class definitions from two different modules.
Definition at line 2960 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::LifetimeExtendedTemporaryDecl::getExtendingDecl(), clang::ASTContext::getLangOpts(), clang::LifetimeExtendedTemporaryDecl::getManglingNumber(), and clang::ASTContext::setPrimaryMergedDecl().
mergeMergeable() [2/2]
template<typename T > void ASTDeclReader::mergeMergeable (Mergeable< T > * D)
Attempts to merge the given declaration (D) with another declaration of the same entity, for the case where the entity is not actually redeclarable.
This happens, for instance, when merging the fields of identical class definitions from two different modules.
Definition at line 2982 of file ASTReaderDecl.cpp.
References allowODRLikeMergeInC(), clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), and clang::ASTContext::setPrimaryMergedDecl().
Referenced by VisitConceptDecl(), VisitEnumConstantDecl(), VisitFieldDecl(), VisitIndirectFieldDecl(), VisitLifetimeExtendedTemporaryDecl(), VisitUnresolvedUsingTypenameDecl(), VisitUnresolvedUsingValueDecl(), VisitUsingDecl(), VisitUsingEnumDecl(), and VisitUsingPackDecl().
mergeRedeclarable() [1/2]
template<typename T > void ASTDeclReader::mergeRedeclarable (Redeclarable< T > * D, RedeclarableResult & Redecl)
Attempts to merge the given declaration (D) with another declaration of the same entity.
Definition at line 2794 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::Redeclarable< decl_type >::isFirstDecl(), and mergeRedeclarable().
Referenced by mergeLambda(), mergeRedeclarable(), mergeRedeclarableTemplate(), mergeTemplatePattern(), VisitClassTemplateSpecializationDeclImpl(), VisitCXXRecordDeclImpl(), VisitFunctionDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCInterfaceDecl(), VisitObjCProtocolDecl(), VisitTagDecl(), VisitTypeAliasDecl(), VisitTypedefDecl(), VisitUsingShadowDecl(), VisitVarDeclImpl(), and VisitVarTemplateSpecializationDeclImpl().
mergeRedeclarable() [2/2]
template<typename T > void ASTDeclReader::mergeRedeclarable (Redeclarable< T > * D, T * Existing, RedeclarableResult & Redecl)
Attempts to merge the given declaration (D) with another declaration of the same entity.
Definition at line 2911 of file ASTReaderDecl.cpp.
References assert_cast(), clang::Redeclarable< decl_type >::First, clang::CXXRecordDecl::getCanonicalDecl(), mergeTemplatePattern(), clang::Redeclarable< decl_type >::PreviousDeclLink(), and clang::Redeclarable< decl_type >::RedeclLink.
mergeRedeclarableTemplate()
void ASTDeclReader::mergeRedeclarableTemplate (RedeclarableTemplateDecl * D, RedeclarableResult & Redecl)
Definition at line 2849 of file ASTReaderDecl.cpp.
References clang::RedeclarableTemplateDecl::Common, clang::RedeclarableTemplateDecl::getCanonicalDecl(), and mergeRedeclarable().
Referenced by VisitClassTemplateDecl(), VisitFunctionDecl(), VisitTypeAliasTemplateDecl(), and VisitVarTemplateDecl().
mergeTemplatePattern()
void ASTDeclReader::mergeTemplatePattern (RedeclarableTemplateDecl * D, RedeclarableTemplateDecl * Existing, bool IsKeyDecl)
Merge together the pattern declarations from two template declarations.
Definition at line 2868 of file ASTReaderDecl.cpp.
References clang::cast(), clang::TemplateDecl::getTemplatedDecl(), mergeRedeclarable(), and clang::Result.
Referenced by mergeRedeclarable().
ReadFunctionDefinition()
void ASTDeclReader::ReadFunctionDefinition (FunctionDecl * FD)
Definition at line 532 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::serialization::ModuleFile::Kind, and clang::ASTRecordReader::readInt().
Referenced by UpdateDecl(), and Visit().
ReadObjCTypeParamList()
ObjCTypeParamList * ASTDeclReader::ReadObjCTypeParamList ()
Definition at line 1204 of file ASTReaderDecl.cpp.
References clang::ObjCTypeParamList::create(), clang::ASTReader::getContext(), and clang::ASTRecordReader::readInt().
Referenced by VisitObjCCategoryDecl(), and VisitObjCInterfaceDecl().
ReadVarDeclInit()
void ASTDeclReader::ReadVarDeclInit (VarDecl * VD)
Definition at line 1669 of file ASTReaderDecl.cpp.
References clang::ASTContext::addDestruction(), clang::VarDecl::ensureEvaluatedStmt(), clang::EvaluatedStmt::Evaluated, clang::ASTReader::getContext(), clang::EvaluatedStmt::HasConstantDestruction, clang::EvaluatedStmt::HasConstantInitialization, clang::APValue::needsCleanup(), clang::ASTRecordReader::readInt(), clang::EvaluatedStmt::Value, and clang::EvaluatedStmt::WasEvaluated.
Referenced by UpdateDecl(), and Visit().
setNextObjCCategory()
static void clang::ASTDeclReader::setNextObjCCategory (ObjCCategoryDecl * Cat, ObjCCategoryDecl * Next) inline static
Definition at line 324 of file ASTReaderDecl.cpp.
References Next.
UpdateDecl()
void ASTDeclReader::UpdateDecl (Decl * D, SmallVectorImpl< serialization::DeclID > & PendingLazySpecializationIDs)
Definition at line 4417 of file ASTReaderDecl.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::TemplateArgumentList::CreateCopy(), clang::First, forAllLaterRedecls(), clang::CXXRecordDecl::getCanonicalDecl(), clang::Decl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::ASTContext::getFunctionType(), clang::CXXRecordDecl::getMemberSpecializationInfo(), clang::ASTReader::getSubmodule(), clang::Decl::hasAttrs(), clang::isUnresolvedExceptionSpec(), clang::Decl::markUsed(), clang::ASTContext::mergeDefinitionIntoModule(), ReadFunctionDefinition(), ReadVarDeclInit(), clang::RecordDecl::setArgPassingRestrictions(), clang::TagDecl::setBraceRange(), clang::FunctionDecl::setImplicitlyInline(), clang::Decl::setLocation(), clang::TypeDecl::setLocStart(), clang::ASTContext::setManglingNumber(), clang::RecordDecl::setParamDestroyedInCallee(), clang::ASTContext::setStaticLocalNumber(), clang::TagDecl::setTagKind(), clang::serialization::UPD_ADDED_ATTR_TO_RECORD, clang::serialization::UPD_CXX_ADDED_ANONYMOUS_NAMESPACE, clang::serialization::UPD_CXX_ADDED_FUNCTION_DEFINITION, clang::serialization::UPD_CXX_ADDED_IMPLICIT_MEMBER, clang::serialization::UPD_CXX_ADDED_TEMPLATE_SPECIALIZATION, clang::serialization::UPD_CXX_ADDED_VAR_DEFINITION, clang::serialization::UPD_CXX_DEDUCED_RETURN_TYPE, clang::serialization::UPD_CXX_INSTANTIATED_CLASS_DEFINITION, clang::serialization::UPD_CXX_INSTANTIATED_DEFAULT_ARGUMENT, clang::serialization::UPD_CXX_INSTANTIATED_DEFAULT_MEMBER_INITIALIZER, clang::serialization::UPD_CXX_POINT_OF_INSTANTIATION, clang::serialization::UPD_CXX_RESOLVED_DTOR_DELETE, clang::serialization::UPD_CXX_RESOLVED_EXCEPTION_SPEC, clang::serialization::UPD_DECL_EXPORTED, clang::serialization::UPD_DECL_MARKED_OPENMP_ALLOCATE, clang::serialization::UPD_DECL_MARKED_OPENMP_DECLARETARGET, clang::serialization::UPD_DECL_MARKED_OPENMP_THREADPRIVATE, clang::serialization::UPD_DECL_MARKED_USED, clang::serialization::UPD_MANGLING_NUMBER, and clang::serialization::UPD_STATIC_LOCAL_NUMBER.
Visit()
void ASTDeclReader::Visit (Decl * D)
Definition at line 548 of file ASTReaderDecl.cpp.
References clang::cast(), clang::Decl::getCanonicalDecl(), clang::ASTReader::GetDecl(), clang::ASTReader::GetType(), clang::QualType::getTypePtrOrNull(), ReadFunctionDefinition(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTypeLoc(), ReadVarDeclInit(), and clang::declvisitor::Base< std::add_pointer, ImplClass, void >::Visit().
VisitAccessSpecDecl()
void ASTDeclReader::VisitAccessSpecDecl (AccessSpecDecl * D)
Definition at line 2299 of file ASTReaderDecl.cpp.
References clang::AccessSpecDecl::setColonLoc(), and VisitDecl().
VisitBindingDecl()
void ASTDeclReader::VisitBindingDecl (BindingDecl * BD)
Definition at line 1723 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExpr(), and VisitValueDecl().
VisitBlockDecl()
void ASTDeclReader::VisitBlockDecl (BlockDecl * BD)
Definition at line 1739 of file ASTReaderDecl.cpp.
References clang::ast_matchers::decl, clang::ASTReader::getContext(), clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readStmt(), clang::BlockDecl::setBlockMissingReturnType(), clang::BlockDecl::setBody(), clang::BlockDecl::setCanAvoidCopyToHeap(), clang::BlockDecl::setCaptures(), clang::BlockDecl::setDoesNotEscape(), clang::BlockDecl::setIsConversionFromLambda(), clang::BlockDecl::setIsVariadic(), clang::BlockDecl::setParams(), clang::BlockDecl::setSignatureAsWritten(), and VisitDecl().
VisitBuiltinTemplateDecl()
void ASTDeclReader::VisitBuiltinTemplateDecl (BuiltinTemplateDecl * D)
Definition at line 2412 of file ASTReaderDecl.cpp.
VisitCapturedDecl()
void ASTDeclReader::VisitCapturedDecl (CapturedDecl * CD)
Definition at line 1772 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::CapturedDecl::setContextParam(), clang::CapturedDecl::setNothrow(), clang::CapturedDecl::setParam(), and VisitDecl().
VisitClassScopeFunctionSpecializationDecl()
void ASTDeclReader::VisitClassScopeFunctionSpecializationDecl (ClassScopeFunctionSpecializationDecl * D)
Definition at line 2523 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readASTTemplateArgumentListInfo(), clang::ASTRecordReader::readInt(), and VisitDecl().
VisitClassTemplateDecl()
void ASTDeclReader::VisitClassTemplateDecl (ClassTemplateDecl * D)
Definition at line 2391 of file ASTReaderDecl.cpp.
References AddLazySpecializations(), clang::ASTReader::getContext(), clang::ClassTemplateDecl::getInjectedClassNameSpecialization(), clang::ASTContext::getInjectedClassNameType(), clang::ClassTemplateDecl::getTemplatedDecl(), mergeRedeclarableTemplate(), and VisitRedeclarableTemplateDecl().
VisitClassTemplatePartialSpecializationDecl()
void ASTDeclReader::VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl * D)
Definition at line 2505 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readASTTemplateArgumentListInfo(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateParameterList(), and VisitClassTemplateSpecializationDeclImpl().
VisitClassTemplateSpecializationDecl()
void clang::ASTDeclReader::VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl * D) inline
Definition at line 354 of file ASTReaderDecl.cpp.
References VisitClassTemplateSpecializationDeclImpl().
VisitClassTemplateSpecializationDeclImpl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitClassTemplateSpecializationDeclImpl (ClassTemplateSpecializationDecl * D)
Definition at line 2433 of file ASTReaderDecl.cpp.
References clang::C, clang::cast(), clang::TemplateArgumentList::CreateCopy(), clang::ASTReader::getContext(), clang::Decl::isCanonicalDecl(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateArgumentList(), and VisitCXXRecordDeclImpl().
Referenced by VisitClassTemplatePartialSpecializationDecl(), and VisitClassTemplateSpecializationDecl().
VisitConceptDecl()
void ASTDeclReader::VisitConceptDecl (ConceptDecl * D)
Definition at line 2340 of file ASTReaderDecl.cpp.
References clang::ConceptDecl::ConstraintExpr, mergeMergeable(), clang::ASTRecordReader::readExpr(), and VisitTemplateDecl().
VisitConstructorUsingShadowDecl()
void ASTDeclReader::VisitConstructorUsingShadowDecl (ConstructorUsingShadowDecl * D)
Definition at line 1898 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), and VisitUsingShadowDecl().
VisitCXXConstructorDecl()
void ASTDeclReader::VisitCXXConstructorDecl (CXXConstructorDecl * D)
Definition at line 2256 of file ASTReaderDecl.cpp.
References clang::CXXConstructorDecl::isInheritingConstructor(), clang::ASTRecordReader::readExplicitSpec(), clang::CXXConstructorDecl::setExplicitSpecifier(), and VisitCXXMethodDecl().
VisitCXXConversionDecl()
void ASTDeclReader::VisitCXXConversionDecl (CXXConversionDecl * D)
Definition at line 2284 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExplicitSpec(), clang::CXXConversionDecl::setExplicitSpecifier(), and VisitCXXMethodDecl().
VisitCXXDeductionGuideDecl()
void ASTDeclReader::VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl * GD)
Definition at line 2230 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExplicitSpec(), clang::ASTRecordReader::readInt(), clang::CXXDeductionGuideDecl::setDeductionCandidateKind(), and VisitFunctionDecl().
VisitCXXDestructorDecl()
void ASTDeclReader::VisitCXXDestructorDecl (CXXDestructorDecl * D)
Definition at line 2270 of file ASTReaderDecl.cpp.
References clang::CXXDestructorDecl::getCanonicalDecl(), clang::ASTRecordReader::readExpr(), and VisitCXXMethodDecl().
VisitCXXMethodDecl()
void ASTDeclReader::VisitCXXMethodDecl (CXXMethodDecl * D)
Definition at line 2238 of file ASTReaderDecl.cpp.
References clang::ASTContext::addOverriddenMethod(), clang::CXXMethodDecl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::Decl::isCanonicalDecl(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::skipInts(), and VisitFunctionDecl().
Referenced by VisitCXXConstructorDecl(), VisitCXXConversionDecl(), and VisitCXXDestructorDecl().
VisitCXXRecordDecl()
void clang::ASTDeclReader::VisitCXXRecordDecl (CXXRecordDecl * D) inline
Definition at line 350 of file ASTReaderDecl.cpp.
References VisitCXXRecordDeclImpl().
VisitCXXRecordDeclImpl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitCXXRecordDeclImpl (CXXRecordDecl * D)
Definition at line 2153 of file ASTReaderDecl.cpp.
References clang::C, clang::CXXRecordDecl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::TagDecl::isCompleteDefinition(), mergeLambda(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), clang::MemberSpecializationInfo::setPointOfInstantiation(), and VisitRecordDeclImpl().
Referenced by VisitClassTemplateSpecializationDeclImpl(), and VisitCXXRecordDecl().
VisitDecl()
void ASTDeclReader::VisitDecl (Decl * D)
Definition at line 586 of file ASTReaderDecl.cpp.
References clang::Module::AllVisible, clang::Decl::FromASTFile, clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::ASTReader::getSubmodule(), clang::ASTContext::getTranslationUnitDecl(), clang::Decl::isTemplateParameter(), clang::Decl::isTemplateParameterPack(), clang::Decl::ModulePrivate, clang::Decl::ReachableWhenImported, clang::ASTRecordReader::readAttributes(), clang::ASTRecordReader::readInt(), clang::Decl::setAccess(), clang::Decl::setDeclContext(), clang::Decl::setImplicit(), clang::Decl::setLocation(), clang::Decl::setModuleOwnershipKind(), clang::Decl::setOwningModuleID(), clang::Decl::setReferenced(), clang::Decl::setTopLevelDeclInObjCContainer(), clang::Decl::setVisibleDespiteOwningModule(), clang::Decl::Unowned, clang::Decl::Visible, and clang::Decl::VisibleWhenImported.
Referenced by VisitAccessSpecDecl(), VisitBlockDecl(), VisitCapturedDecl(), VisitClassScopeFunctionSpecializationDecl(), VisitEmptyDecl(), VisitExportDecl(), VisitFileScopeAsmDecl(), VisitFriendDecl(), VisitFriendTemplateDecl(), VisitImplicitConceptSpecializationDecl(), VisitImportDecl(), VisitLifetimeExtendedTemporaryDecl(), VisitLinkageSpecDecl(), VisitNamedDecl(), VisitObjCPropertyImplDecl(), VisitOMPAllocateDecl(), VisitOMPRequiresDecl(), VisitOMPThreadPrivateDecl(), VisitPragmaCommentDecl(), VisitPragmaDetectMismatchDecl(), VisitStaticAssertDecl(), and VisitTopLevelStmtDecl().
VisitDeclaratorDecl()
void ASTDeclReader::VisitDeclaratorDecl (DeclaratorDecl * DD)
Definition at line 903 of file ASTReaderDecl.cpp.
References clang::ASTContext::CreateTypeSourceInfo(), clang::ASTReader::getContext(), clang::QualType::isNull(), clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readQualifierInfo(), clang::ASTRecordReader::readType(), clang::DeclaratorDecl::setInnerLocStart(), clang::DeclaratorDecl::setTypeSourceInfo(), and VisitValueDecl().
Referenced by VisitFieldDecl(), VisitFunctionDecl(), VisitMSPropertyDecl(), VisitNonTypeTemplateParmDecl(), and VisitVarDeclImpl().
VisitDeclContext()
std::pair< uint64_t, uint64_t > ASTDeclReader::VisitDeclContext (DeclContext * DC)
Definition at line 2725 of file ASTReaderDecl.cpp.
Referenced by VisitHLSLBufferDecl().
VisitDecompositionDecl()
void ASTDeclReader::VisitDecompositionDecl (DecompositionDecl * DD)
Definition at line 1714 of file ASTReaderDecl.cpp.
References VisitVarDecl().
VisitEmptyDecl()
void ASTDeclReader::VisitEmptyDecl (EmptyDecl * D)
Definition at line 2707 of file ASTReaderDecl.cpp.
References VisitDecl().
VisitEnumConstantDecl()
void ASTDeclReader::VisitEnumConstantDecl (EnumConstantDecl * ECD)
Definition at line 895 of file ASTReaderDecl.cpp.
References mergeMergeable(), clang::serialization::DataStreamBasicReader< Impl >::readAPSInt(), clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::EnumConstantDecl::setInitExpr(), clang::EnumConstantDecl::setInitVal(), and VisitValueDecl().
VisitEnumDecl()
void ASTDeclReader::VisitEnumDecl (EnumDecl * ED)
Definition at line 784 of file ASTReaderDecl.cpp.
References clang::TagDecl::demoteThisDefinitionToDeclaration(), clang::EnumDecl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::EnumDecl::getMemberSpecializationInfo(), clang::EnumDecl::getODRHash(), clang::TagDecl::isCompleteDefinition(), merged_redecls(), clang::ASTReader::mergeDefinitionVisibility(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::EnumDecl::setFixed(), clang::EnumDecl::setIntegerType(), clang::EnumDecl::setIntegerTypeSourceInfo(), clang::MemberSpecializationInfo::setPointOfInstantiation(), clang::EnumDecl::setPromotionType(), clang::EnumDecl::setScoped(), clang::EnumDecl::setScopedUsingClassTag(), and VisitTagDecl().
VisitExportDecl()
void ASTDeclReader::VisitExportDecl (ExportDecl * D)
Definition at line 1792 of file ASTReaderDecl.cpp.
References VisitDecl().
VisitFieldDecl()
void ASTDeclReader::VisitFieldDecl (FieldDecl * FD)
Definition at line 1513 of file ASTReaderDecl.cpp.
References clang::FieldDecl::CapturedVLAType, clang::cast(), clang::ASTReader::getContext(), clang::NamedDecl::getDeclName(), clang::QualType::getTypePtr(), mergeMergeable(), clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::FieldDecl::setBitWidth(), clang::ASTContext::setInstantiatedFromUnnamedFieldDecl(), and VisitDeclaratorDecl().
Referenced by VisitObjCAtDefsFieldDecl(), and VisitObjCIvarDecl().
VisitFileScopeAsmDecl()
void ASTDeclReader::VisitFileScopeAsmDecl (FileScopeAsmDecl * AD)
Definition at line 1728 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExpr(), clang::FileScopeAsmDecl::setAsmString(), clang::FileScopeAsmDecl::setRParenLoc(), and VisitDecl().
VisitFriendDecl()
void ASTDeclReader::VisitFriendDecl (FriendDecl * D)
Definition at line 2304 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateParameterList(), and VisitDecl().
VisitFriendTemplateDecl()
void ASTDeclReader::VisitFriendTemplateDecl (FriendTemplateDecl * D)
Definition at line 2318 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateParameterList(), and VisitDecl().
VisitFunctionDecl()
void ASTDeclReader::VisitFunctionDecl (FunctionDecl * FD)
Definition at line 918 of file ASTReaderDecl.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::UnresolvedSetImpl::addDecl(), clang::C, clang::Type::castAs(), clang::FunctionDecl::DefaultedFunctionInfo::Create(), clang::FunctionTemplateSpecializationInfo::Create(), clang::TemplateArgumentList::CreateCopy(), clang::Type::getContainedAutoType(), clang::ASTReader::getContext(), clang::NamedDecl::getDeclName(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::FunctionTemplateSpecializationInfo::getFunction(), clang::ASTContext::getLangOpts(), clang::FunctionDecl::getMemberSpecializationInfo(), clang::FunctionType::getReturnType(), clang::FunctionTemplateSpecializationInfo::getTemplate(), clang::FunctionDecl::getTemplatedKind(), clang::FunctionDecl::getTemplateSpecializationInfo(), clang::ASTReader::GetType(), clang::TypeSourceInfo::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::Decl::isCanonicalDecl(), clang::FunctionDecl::isDefaulted(), clang::DeclAccessPair::make(), mergeRedeclarable(), mergeRedeclarableTemplate(), clang::FunctionTemplateSpecializationInfo::Profile(), clang::ASTRecordReader::readDeclarationNameLoc(), clang::ASTRecordReader::readDeclAs(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateArgumentList(), clang::ASTRecordReader::readTemplateArgumentLoc(), clang::Decl::setCachedLinkage(), clang::FunctionDecl::setConstexprKind(), clang::FunctionDecl::setDefaulted(), clang::FunctionDecl::setDefaultedFunctionInfo(), clang::FunctionDecl::setDefaultLoc(), clang::FunctionDecl::setDeletedAsWritten(), clang::FunctionDecl::setDependentTemplateSpecialization(), clang::FunctionDecl::setDescribedFunctionTemplate(), clang::FunctionDecl::setExplicitlyDefaulted(), clang::FunctionDecl::setFriendConstraintRefersToEnclosingTemplate(), clang::FunctionDecl::setHasImplicitReturnZero(), clang::FunctionDecl::setHasInheritedPrototype(), clang::FunctionDecl::setHasSkippedBody(), clang::FunctionDecl::setHasWrittenPrototype(), clang::FunctionDecl::setImplicitlyInline(), clang::FunctionDecl::setIneligibleOrNotSelected(), clang::FunctionDecl::setInlineSpecified(), clang::FunctionDecl::setInstantiatedFromDecl(), clang::FunctionDecl::setIsMultiVersion(), clang::TemplateArgumentListInfo::setLAngleLoc(), clang::FunctionDecl::setLateTemplateParsed(), clang::MemberSpecializationInfo::setPointOfInstantiation(), clang::FunctionDecl::setPure(), clang::TemplateArgumentListInfo::setRAngleLoc(), clang::FunctionDecl::setStorageClass(), clang::FunctionDecl::setTrivial(), clang::FunctionDecl::setTrivialForCall(), clang::ValueDecl::setType(), clang::FunctionDecl::setUsesSEHTry(), clang::FunctionDecl::setVirtualAsWritten(), clang::FunctionTemplateDecl::Common::Specializations, clang::FunctionDecl::TK_DependentFunctionTemplateSpecialization, clang::FunctionDecl::TK_DependentNonTemplate, clang::FunctionDecl::TK_FunctionTemplate, clang::FunctionDecl::TK_FunctionTemplateSpecialization, clang::FunctionDecl::TK_MemberSpecialization, clang::FunctionDecl::TK_NonTemplate, VisitDeclaratorDecl(), and VisitRedeclarable().
Referenced by VisitCXXDeductionGuideDecl(), and VisitCXXMethodDecl().
VisitFunctionTemplateDecl()
void ASTDeclReader::VisitFunctionTemplateDecl (FunctionTemplateDecl * D)
Definition at line 2531 of file ASTReaderDecl.cpp.
References AddLazySpecializations(), and VisitRedeclarableTemplateDecl().
VisitHLSLBufferDecl()
void ASTDeclReader::VisitHLSLBufferDecl (HLSLBufferDecl * D)
Definition at line 1835 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readBool(), VisitDeclContext(), and VisitNamedDecl().
VisitImplicitConceptSpecializationDecl()
void ASTDeclReader::VisitImplicitConceptSpecializationDecl (ImplicitConceptSpecializationDecl * D)
Definition at line 2346 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readTemplateArgument(), clang::ImplicitConceptSpecializationDecl::setTemplateArguments(), and VisitDecl().
VisitImplicitParamDecl()
void ASTDeclReader::VisitImplicitParamDecl (ImplicitParamDecl * PD)
Definition at line 1688 of file ASTReaderDecl.cpp.
References VisitVarDecl().
VisitImportDecl()
void ASTDeclReader::VisitImportDecl (ImportDecl * D)
Definition at line 2289 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::back(), N, clang::ASTRecordReader::readInt(), clang::ASTRecordReader::skipInts(), and VisitDecl().
VisitIndirectFieldDecl()
void ASTDeclReader::VisitIndirectFieldDecl (IndirectFieldDecl * FD)
Definition at line 1573 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), mergeMergeable(), clang::ASTRecordReader::readInt(), and VisitValueDecl().
VisitLabelDecl()
void ASTDeclReader::VisitLabelDecl (LabelDecl * LD)
Definition at line 1797 of file ASTReaderDecl.cpp.
References clang::LabelDecl::setLocStart(), and VisitNamedDecl().
VisitLifetimeExtendedTemporaryDecl()
void ASTDeclReader::VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl * D)
Definition at line 2711 of file ASTReaderDecl.cpp.
References clang::ASTContext::addDestruction(), clang::Decl::getASTContext(), mergeMergeable(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readStmt(), and VisitDecl().
VisitLinkageSpecDecl()
void ASTDeclReader::VisitLinkageSpecDecl (LinkageSpecDecl * D)
Definition at line 1785 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::LinkageSpecDecl::setExternLoc(), clang::LinkageSpecDecl::setLanguage(), clang::LinkageSpecDecl::setRBraceLoc(), and VisitDecl().
VisitMSGuidDecl()
void ASTDeclReader::VisitMSGuidDecl (MSGuidDecl * D)
Definition at line 1538 of file ASTReaderDecl.cpp.
References clang::C, clang::Decl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::MSGuidDeclParts::Part1, clang::MSGuidDeclParts::Part2, clang::MSGuidDeclParts::Part3, clang::MSGuidDeclParts::Part4And5, clang::ASTRecordReader::readInt(), clang::ASTContext::setPrimaryMergedDecl(), and VisitValueDecl().
VisitMSPropertyDecl()
void ASTDeclReader::VisitMSPropertyDecl (MSPropertyDecl * FD)
Definition at line 1532 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readIdentifier(), and VisitDeclaratorDecl().
VisitNamedDecl()
void ASTDeclReader::VisitNamedDecl (NamedDecl * ND)
Definition at line 704 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::NamedDecl::setDeclName(), and VisitDecl().
Referenced by VisitHLSLBufferDecl(), VisitLabelDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCCompatibleAliasDecl(), VisitObjCContainerDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitTemplateDecl(), VisitTypeDecl(), VisitUnresolvedUsingIfExistsDecl(), VisitUsingDecl(), VisitUsingDirectiveDecl(), VisitUsingEnumDecl(), VisitUsingPackDecl(), VisitUsingShadowDecl(), and VisitValueDecl().
VisitNamespaceAliasDecl()
void ASTDeclReader::VisitNamespaceAliasDecl (NamespaceAliasDecl * D)
Definition at line 1844 of file ASTReaderDecl.cpp.
References mergeRedeclarable(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), VisitNamedDecl(), and VisitRedeclarable().
VisitNamespaceDecl()
void ASTDeclReader::VisitNamespaceDecl (NamespaceDecl * D)
Definition at line 1802 of file ASTReaderDecl.cpp.
References clang::cast(), clang::ASTReader::GetDecl(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::ASTRecordReader::isModule(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), clang::NamespaceDecl::setAnonymousNamespace(), clang::NamespaceDecl::setInline(), clang::NamespaceDecl::setNested(), VisitNamedDecl(), and VisitRedeclarable().
VisitNonTypeTemplateParmDecl()
void ASTDeclReader::VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl * D)
Definition at line 2653 of file ASTReaderDecl.cpp.
References clang::NonTypeTemplateParmDecl::getNumExpansionTypes(), clang::NonTypeTemplateParmDecl::hasPlaceholderTypeConstraint(), clang::NonTypeTemplateParmDecl::isExpandedParameterPack(), N, clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::NonTypeTemplateParmDecl::setDefaultArgument(), clang::NonTypeTemplateParmDecl::setDepth(), clang::NonTypeTemplateParmDecl::setPlaceholderTypeConstraint(), clang::NonTypeTemplateParmDecl::setPosition(), and VisitDeclaratorDecl().
VisitObjCAtDefsFieldDecl()
void ASTDeclReader::VisitObjCAtDefsFieldDecl (ObjCAtDefsFieldDecl * D)
Definition at line 1414 of file ASTReaderDecl.cpp.
References VisitFieldDecl().
VisitObjCCategoryDecl()
void ASTDeclReader::VisitObjCCategoryDecl (ObjCCategoryDecl * D)
category.
Definition at line 1418 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ObjCCategoryDecl::IsClassExtension(), clang::ObjCInterfaceDecl::mergeClassExtensionProtocolList(), clang::ASTRecordReader::readInt(), ReadObjCTypeParamList(), clang::ObjCCategoryDecl::setCategoryNameLoc(), clang::ObjCCategoryDecl::setIvarLBraceLoc(), clang::ObjCCategoryDecl::setIvarRBraceLoc(), clang::ObjCCategoryDecl::setProtocolList(), and VisitObjCContainerDecl().
VisitObjCCategoryImplDecl()
void ASTDeclReader::VisitObjCCategoryImplDecl (ObjCCategoryImplDecl * D)
Definition at line 1483 of file ASTReaderDecl.cpp.
References VisitObjCImplDecl().
VisitObjCCompatibleAliasDecl()
void ASTDeclReader::VisitObjCCompatibleAliasDecl (ObjCCompatibleAliasDecl * D)
Definition at line 1450 of file ASTReaderDecl.cpp.
References clang::ObjCCompatibleAliasDecl::setClassInterface(), and VisitNamedDecl().
VisitObjCContainerDecl()
void ASTDeclReader::VisitObjCContainerDecl (ObjCContainerDecl * D)
Definition at line 1198 of file ASTReaderDecl.cpp.
References clang::ObjCContainerDecl::setAtEndRange(), clang::ObjCContainerDecl::setAtStartLoc(), and VisitNamedDecl().
Referenced by VisitObjCCategoryDecl(), VisitObjCImplDecl(), VisitObjCInterfaceDecl(), and VisitObjCProtocolDecl().
VisitObjCImplDecl()
void ASTDeclReader::VisitObjCImplDecl (ObjCImplDecl * D)
Definition at line 1478 of file ASTReaderDecl.cpp.
References clang::ObjCImplDecl::setClassInterface(), and VisitObjCContainerDecl().
Referenced by VisitObjCCategoryImplDecl(), and VisitObjCImplementationDecl().
VisitObjCImplementationDecl()
void ASTDeclReader::VisitObjCImplementationDecl (ObjCImplementationDecl * D)
Definition at line 1488 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::ObjCImplementationDecl::setHasDestructors(), clang::ObjCImplementationDecl::setHasNonZeroConstructors(), clang::ObjCImplementationDecl::setIvarLBraceLoc(), clang::ObjCImplementationDecl::setIvarRBraceLoc(), clang::ObjCImplementationDecl::setSuperClass(), and VisitObjCImplDecl().
VisitObjCInterfaceDecl()
void ASTDeclReader::VisitObjCInterfaceDecl (ObjCInterfaceDecl * D)
Definition at line 1274 of file ASTReaderDecl.cpp.
References clang::ObjCInterfaceDecl::getCanonicalDecl(), clang::ASTRecordReader::getGlobalTypeID(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), ReadObjCTypeParamList(), VisitObjCContainerDecl(), and VisitRedeclarable().
VisitObjCIvarDecl()
void ASTDeclReader::VisitObjCIvarDecl (ObjCIvarDecl * D)
Definition at line 1311 of file ASTReaderDecl.cpp.
References clang::ASTReader::Diag(), clang::ObjCInterfaceDecl::getCanonicalDecl(), clang::ObjCIvarDecl::getContainingInterface(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::Decl::isInvalidDecl(), clang::ObjCInterfaceDecl::lookupInstanceVariable(), clang::ASTRecordReader::readInt(), clang::ObjCIvarDecl::setAccessControl(), clang::ObjCIvarDecl::setNextIvar(), clang::ObjCIvarDecl::setSynthesize(), and VisitFieldDecl().
VisitObjCMethodDecl()
void ASTDeclReader::VisitObjCMethodDecl (ObjCMethodDecl * D)
Definition at line 1143 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ObjCMethodDecl::hasRedeclaration(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::ObjCMethodDecl::setCmdDecl(), clang::ObjCMethodDecl::setDeclImplementation(), clang::ObjCMethodDecl::setDefined(), clang::ObjCMethodDecl::setHasRedeclaration(), clang::ObjCMethodDecl::setHasSkippedBody(), clang::ObjCMethodDecl::setInstanceMethod(), clang::ObjCMethodDecl::setIsRedeclaration(), clang::ObjCMethodDecl::setObjCDeclQualifier(), clang::ASTContext::setObjCMethodRedeclaration(), clang::ObjCMethodDecl::setOverriding(), clang::ObjCMethodDecl::setPropertyAccessor(), clang::ObjCMethodDecl::setRelatedResultType(), clang::ObjCMethodDecl::setReturnType(), clang::ObjCMethodDecl::setReturnTypeSourceInfo(), clang::ObjCMethodDecl::setSelfDecl(), clang::ObjCMethodDecl::setSynthesizedAccessorStub(), clang::ObjCMethodDecl::setVariadic(), and VisitNamedDecl().
VisitObjCPropertyDecl()
void ASTDeclReader::VisitObjCPropertyDecl (ObjCPropertyDecl * D)
Definition at line 1455 of file ASTReaderDecl.cpp.
References clang::DeclarationName::getObjCSelector(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::ObjCPropertyDecl::setAtLoc(), clang::ObjCPropertyDecl::setGetterMethodDecl(), clang::ObjCPropertyDecl::setGetterName(), clang::ObjCPropertyDecl::setLParenLoc(), clang::ObjCPropertyDecl::setPropertyAttributes(), clang::ObjCPropertyDecl::setPropertyAttributesAsWritten(), clang::ObjCPropertyDecl::setPropertyImplementation(), clang::ObjCPropertyDecl::setPropertyIvarDecl(), clang::ObjCPropertyDecl::setSetterMethodDecl(), clang::ObjCPropertyDecl::setSetterName(), clang::ObjCPropertyDecl::setType(), and VisitNamedDecl().
VisitObjCPropertyImplDecl()
void ASTDeclReader::VisitObjCPropertyImplDecl (ObjCPropertyImplDecl * D)
Definition at line 1501 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExpr(), clang::ObjCPropertyImplDecl::setAtLoc(), clang::ObjCPropertyImplDecl::setGetterCXXConstructor(), clang::ObjCPropertyImplDecl::setGetterMethodDecl(), clang::ObjCPropertyImplDecl::setPropertyDecl(), clang::ObjCPropertyImplDecl::setSetterCXXAssignment(), clang::ObjCPropertyImplDecl::setSetterMethodDecl(), and VisitDecl().
VisitObjCProtocolDecl()
void ASTDeclReader::VisitObjCProtocolDecl (ObjCProtocolDecl * D)
Definition at line 1385 of file ASTReaderDecl.cpp.
References clang::ObjCProtocolDecl::getCanonicalDecl(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), VisitObjCContainerDecl(), and VisitRedeclarable().
VisitObjCTypeParamDecl()
void ASTDeclReader::VisitObjCTypeParamDecl (ObjCTypeParamDecl * D)
Definition at line 1189 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), and VisitTypedefNameDecl().
VisitOMPAllocateDecl()
void ASTDeclReader::VisitOMPAllocateDecl (OMPAllocateDecl * D)
Definition at line 3006 of file ASTReaderDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::ASTRecordReader::readOMPChildren(), and VisitDecl().
VisitOMPCapturedExprDecl()
void ASTDeclReader::VisitOMPCapturedExprDecl (OMPCapturedExprDecl * D)
Definition at line 3040 of file ASTReaderDecl.cpp.
References VisitVarDecl().
VisitOMPDeclareMapperDecl()
void ASTDeclReader::VisitOMPDeclareMapperDecl (OMPDeclareMapperDecl * D)
Definition at line 3033 of file ASTReaderDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::ASTRecordReader::readOMPChildren(), and VisitValueDecl().
VisitOMPDeclareReductionDecl()
void ASTDeclReader::VisitOMPDeclareReductionDecl (OMPDeclareReductionDecl * D)
Definition at line 3016 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::OMPDeclareReductionDecl::setCombiner(), clang::OMPDeclareReductionDecl::setCombinerData(), clang::OMPDeclareReductionDecl::setInitializer(), clang::OMPDeclareReductionDecl::setInitializerData(), clang::Decl::setLocation(), and VisitValueDecl().
VisitOMPRequiresDecl()
void ASTDeclReader::VisitOMPRequiresDecl (OMPRequiresDecl * D)
Definition at line 3011 of file ASTReaderDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::ASTRecordReader::readOMPChildren(), and VisitDecl().
VisitOMPThreadPrivateDecl()
void ASTDeclReader::VisitOMPThreadPrivateDecl (OMPThreadPrivateDecl * D)
Definition at line 3001 of file ASTReaderDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::ASTRecordReader::readOMPChildren(), and VisitDecl().
VisitParmVarDecl()
void ASTDeclReader::VisitParmVarDecl (ParmVarDecl * PD)
Definition at line 1692 of file ASTReaderDecl.cpp.
References clang::VarDecl::ParmVarDeclBits, clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ParmVarDecl::setObjCMethodScopeInfo(), clang::ParmVarDecl::setScopeInfo(), clang::ParmVarDecl::setUninstantiatedDefaultArg(), and VisitVarDecl().
VisitPragmaCommentDecl()
void ASTDeclReader::VisitPragmaCommentDecl (PragmaCommentDecl * D)
Definition at line 677 of file ASTReaderDecl.cpp.
References memcpy(), clang::ASTRecordReader::readInt(), clang::Decl::setLocation(), and VisitDecl().
VisitPragmaDetectMismatchDecl()
void ASTDeclReader::VisitPragmaDetectMismatchDecl (PragmaDetectMismatchDecl * D)
Definition at line 686 of file ASTReaderDecl.cpp.
References memcpy(), clang::Decl::setLocation(), and VisitDecl().
VisitRecordDecl()
void ASTDeclReader::VisitRecordDecl (RecordDecl * RD)
Definition at line 853 of file ASTReaderDecl.cpp.
References clang::TagDecl::demoteThisDefinitionToDeclaration(), clang::TagDecl::getCanonicalDecl(), clang::RecordDecl::getODRHash(), clang::TagDecl::isCompleteDefinition(), merged_redecls(), clang::ASTReader::mergeDefinitionVisibility(), clang::ASTRecordReader::readInt(), and VisitRecordDeclImpl().
VisitRecordDeclImpl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitRecordDeclImpl (RecordDecl * RD)
Definition at line 836 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::RecordDecl::setAnonymousStructOrUnion(), clang::RecordDecl::setArgPassingRestrictions(), clang::RecordDecl::setHasFlexibleArrayMember(), clang::RecordDecl::setHasNonTrivialToPrimitiveCopyCUnion(), clang::RecordDecl::setHasNonTrivialToPrimitiveDefaultInitializeCUnion(), clang::RecordDecl::setHasNonTrivialToPrimitiveDestructCUnion(), clang::RecordDecl::setHasObjectMember(), clang::RecordDecl::setHasVolatileMember(), clang::RecordDecl::setNonTrivialToPrimitiveCopy(), clang::RecordDecl::setNonTrivialToPrimitiveDefaultInitialize(), clang::RecordDecl::setNonTrivialToPrimitiveDestroy(), clang::RecordDecl::setParamDestroyedInCallee(), and VisitTagDecl().
Referenced by VisitCXXRecordDeclImpl(), and VisitRecordDecl().
VisitRedeclarable()
template<typename T > ASTDeclReader::RedeclarableResult ASTDeclReader::VisitRedeclarable (Redeclarable< T > * D)
Definition at line 2733 of file ASTReaderDecl.cpp.
References clang::Redeclarable< decl_type >::First, clang::ASTReader::GetDecl(), N, clang::Redeclarable< decl_type >::PreviousDeclLink(), clang::ASTRecordReader::readInt(), and clang::Redeclarable< decl_type >::RedeclLink.
Referenced by VisitFunctionDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCInterfaceDecl(), VisitObjCProtocolDecl(), VisitRedeclarableTemplateDecl(), VisitTagDecl(), VisitTypedefNameDecl(), VisitUsingShadowDecl(), and VisitVarDeclImpl().
VisitRedeclarableTemplateDecl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitRedeclarableTemplateDecl (RedeclarableTemplateDecl * D)
Definition at line 2361 of file ASTReaderDecl.cpp.
References clang::RedeclarableTemplateDecl::Common, clang::RedeclarableTemplateDecl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::Decl::getKind(), clang::RedeclarableTemplateDecl::newCommon(), clang::ASTRecordReader::readInt(), clang::RedeclarableTemplateDecl::setInstantiatedFromMemberTemplate(), clang::RedeclarableTemplateDecl::setMemberSpecialization(), VisitRedeclarable(), and VisitTemplateDecl().
Referenced by VisitClassTemplateDecl(), VisitFunctionTemplateDecl(), VisitTypeAliasTemplateDecl(), and VisitVarTemplateDecl().
VisitRequiresExprBodyDecl()
void ASTDeclReader::VisitRequiresExprBodyDecl (RequiresExprBodyDecl * D)
Definition at line 2357 of file ASTReaderDecl.cpp.
VisitStaticAssertDecl()
void ASTDeclReader::VisitStaticAssertDecl (StaticAssertDecl * D)
Definition at line 2699 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), and VisitDecl().
VisitTagDecl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitTagDecl (TagDecl * TD)
Definition at line 749 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), mergeRedeclarable(), clang::ASTRecordReader::readIdentifier(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readQualifierInfo(), clang::TagDecl::setBraceRange(), clang::TagDecl::setCompleteDefinition(), clang::TagDecl::setCompleteDefinitionRequired(), clang::TagDecl::setEmbeddedInDeclarator(), clang::TagDecl::setFreeStanding(), clang::TagDecl::setTagKind(), VisitRedeclarable(), and VisitTypeDecl().
Referenced by VisitEnumDecl(), and VisitRecordDeclImpl().
VisitTemplateDecl()
void ASTDeclReader::VisitTemplateDecl (TemplateDecl * D)
Definition at line 2332 of file ASTReaderDecl.cpp.
References clang::TemplateDecl::init(), clang::ASTRecordReader::readTemplateParameterList(), clang::TemplateDecl::TemplateParams, and VisitNamedDecl().
Referenced by VisitConceptDecl(), VisitRedeclarableTemplateDecl(), and VisitTemplateTemplateParmDecl().
VisitTemplateParamObjectDecl()
void ASTDeclReader::VisitTemplateParamObjectDecl (TemplateParamObjectDecl * D)
Definition at line 1562 of file ASTReaderDecl.cpp.
References clang::TemplateParamObjectDecl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::ASTContext::setPrimaryMergedDecl(), and VisitValueDecl().
VisitTemplateTemplateParmDecl()
void ASTDeclReader::VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl * D)
Definition at line 2675 of file ASTReaderDecl.cpp.
References Data, clang::ASTReader::getContext(), clang::TemplateTemplateParmDecl::getNumExpansionTemplateParameters(), clang::TemplateTemplateParmDecl::isExpandedParameterPack(), N, clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateArgumentLoc(), clang::ASTRecordReader::readTemplateParameterList(), clang::TemplateTemplateParmDecl::setDefaultArgument(), clang::TemplateTemplateParmDecl::setDepth(), clang::TemplateTemplateParmDecl::setPosition(), and VisitTemplateDecl().
VisitTemplateTypeParmDecl()
void ASTDeclReader::VisitTemplateTypeParmDecl (TemplateTypeParmDecl * D)
Definition at line 2630 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readASTTemplateArgumentListInfo(), clang::ASTRecordReader::readBool(), clang::ASTRecordReader::readDeclarationNameInfo(), clang::ASTRecordReader::readDeclAs(), clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), clang::TemplateTypeParmDecl::setDeclaredWithTypename(), clang::TemplateTypeParmDecl::setDefaultArgument(), clang::TemplateTypeParmDecl::setTypeConstraint(), and VisitTypeDecl().
VisitTopLevelStmtDecl()
void ASTDeclReader::VisitTopLevelStmtDecl (TopLevelStmtDecl * D)
Definition at line 1734 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readStmt(), and VisitDecl().
VisitTranslationUnitDecl()
void ASTDeclReader::VisitTranslationUnitDecl (TranslationUnitDecl * TU)
Definition at line 700 of file ASTReaderDecl.cpp.
VisitTypeAliasDecl()
void ASTDeclReader::VisitTypeAliasDecl (TypeAliasDecl * TD)
Definition at line 740 of file ASTReaderDecl.cpp.
References mergeRedeclarable(), clang::TypeAliasDecl::setDescribedAliasTemplate(), and VisitTypedefNameDecl().
VisitTypeAliasTemplateDecl()
void ASTDeclReader::VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl * D)
Definition at line 2694 of file ASTReaderDecl.cpp.
References mergeRedeclarableTemplate(), and VisitRedeclarableTemplateDecl().
VisitTypeDecl()
void ASTDeclReader::VisitTypeDecl (TypeDecl * TD)
Definition at line 710 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::getGlobalTypeID(), clang::ASTRecordReader::readInt(), clang::TypeDecl::setLocStart(), and VisitNamedDecl().
Referenced by VisitTagDecl(), VisitTemplateTypeParmDecl(), VisitTypedefNameDecl(), and VisitUnresolvedUsingTypenameDecl().
VisitTypedefDecl()
void ASTDeclReader::VisitTypedefDecl (TypedefDecl * TD)
Definition at line 735 of file ASTReaderDecl.cpp.
References mergeRedeclarable(), and VisitTypedefNameDecl().
VisitTypedefNameDecl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitTypedefNameDecl (TypedefNameDecl * TD)
Definition at line 718 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::TypedefNameDecl::setModedTypeSourceInfo(), clang::TypedefNameDecl::setTypeSourceInfo(), VisitRedeclarable(), and VisitTypeDecl().
Referenced by VisitObjCTypeParamDecl(), VisitTypeAliasDecl(), and VisitTypedefDecl().
VisitUnnamedGlobalConstantDecl()
void ASTDeclReader::VisitUnnamedGlobalConstantDecl (UnnamedGlobalConstantDecl * D)
Definition at line 1551 of file ASTReaderDecl.cpp.
References clang::Decl::getCanonicalDecl(), clang::ASTReader::getContext(), clang::ASTContext::setPrimaryMergedDecl(), and VisitValueDecl().
VisitUnresolvedUsingIfExistsDecl()
void ASTDeclReader::VisitUnresolvedUsingIfExistsDecl (UnresolvedUsingIfExistsDecl * D)
Definition at line 1933 of file ASTReaderDecl.cpp.
References VisitNamedDecl().
VisitUnresolvedUsingTypenameDecl()
void ASTDeclReader::VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl * D)
Definition at line 1924 of file ASTReaderDecl.cpp.
References mergeMergeable(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), and VisitTypeDecl().
VisitUnresolvedUsingValueDecl()
void ASTDeclReader::VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl * D)
Definition at line 1915 of file ASTReaderDecl.cpp.
References clang::NamedDecl::getDeclName(), mergeMergeable(), clang::ASTRecordReader::readDeclarationNameLoc(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), clang::UnresolvedUsingValueDecl::setUsingLoc(), and VisitValueDecl().
VisitUsingDecl()
void ASTDeclReader::VisitUsingDecl (UsingDecl * D)
Definition at line 1854 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::NamedDecl::getDeclName(), mergeMergeable(), clang::ASTRecordReader::readDeclarationNameLoc(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readNestedNameSpecifierLoc(), clang::ASTContext::setInstantiatedFromUsingDecl(), clang::UsingDecl::setTypename(), clang::UsingDecl::setUsingLoc(), and VisitNamedDecl().
VisitUsingDirectiveDecl()
void ASTDeclReader::VisitUsingDirectiveDecl (UsingDirectiveDecl * D)
Definition at line 1906 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readNestedNameSpecifierLoc(), and VisitNamedDecl().
VisitUsingEnumDecl()
void ASTDeclReader::VisitUsingEnumDecl (UsingEnumDecl * D)
Definition at line 1866 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), mergeMergeable(), clang::ASTRecordReader::readTypeSourceInfo(), clang::UsingEnumDecl::setEnumLoc(), clang::UsingEnumDecl::setEnumType(), clang::ASTContext::setInstantiatedFromUsingEnumDecl(), clang::UsingEnumDecl::setUsingLoc(), and VisitNamedDecl().
VisitUsingPackDecl()
void ASTDeclReader::VisitUsingPackDecl (UsingPackDecl * D)
Definition at line 1877 of file ASTReaderDecl.cpp.
References mergeMergeable(), and VisitNamedDecl().
VisitUsingShadowDecl()
void ASTDeclReader::VisitUsingShadowDecl (UsingShadowDecl * D)
Definition at line 1886 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), clang::ASTContext::setInstantiatedFromUsingShadowDecl(), VisitNamedDecl(), and VisitRedeclarable().
Referenced by VisitConstructorUsingShadowDecl().
VisitValueDecl()
void ASTDeclReader::VisitValueDecl (ValueDecl * VD)
Definition at line 884 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::getGlobalTypeID(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readType(), clang::ValueDecl::setType(), and VisitNamedDecl().
Referenced by VisitBindingDecl(), VisitDeclaratorDecl(), VisitEnumConstantDecl(), VisitIndirectFieldDecl(), VisitMSGuidDecl(), VisitOMPDeclareMapperDecl(), VisitOMPDeclareReductionDecl(), VisitTemplateParamObjectDecl(), VisitUnnamedGlobalConstantDecl(), and VisitUnresolvedUsingValueDecl().
VisitVarDecl()
void clang::ASTDeclReader::VisitVarDecl (VarDecl * VD) inline
Definition at line 391 of file ASTReaderDecl.cpp.
References VisitVarDeclImpl().
Referenced by VisitDecompositionDecl(), VisitImplicitParamDecl(), VisitOMPCapturedExprDecl(), and VisitParmVarDecl().
VisitVarDeclImpl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitVarDeclImpl (VarDecl * D)
Definition at line 1586 of file ASTReaderDecl.cpp.
References clang::ASTReader::getContext(), clang::ASTContext::getLangOpts(), clang::Decl::getLexicalDeclContext(), clang::VarDecl::getStorageClass(), clang::ASTReader::GetType(), clang::Decl::hasAttr(), clang::DeclContext::isFunctionOrMethod(), clang::serialization::ModuleFile::Kind, mergeRedeclarable(), clang::NoLinkage, clang::VarDecl::NonParmVarDeclBits, clang::ASTRecordReader::readExpr(), clang::ASTRecordReader::readInt(), clang::SC_Extern, clang::ASTContext::setBlockVarCopyInit(), clang::Decl::setCachedLinkage(), clang::VarDecl::setDescribedVarTemplate(), clang::ASTContext::setInstantiatedFromStaticDataMember(), clang::Decl::setLocalExternDecl(), clang::ValueDecl::setType(), clang::VarDecl::VarDeclBits, VisitDeclaratorDecl(), and VisitRedeclarable().
Referenced by VisitVarDecl(), and VisitVarTemplateSpecializationDeclImpl().
VisitVarTemplateDecl()
void ASTDeclReader::VisitVarTemplateDecl (VarTemplateDecl * D)
TODO: Unify with ClassTemplateDecl version? May require unifying ClassTemplateDecl and VarTemplateDecl beyond TemplateDecl...
Definition at line 2419 of file ASTReaderDecl.cpp.
References AddLazySpecializations(), mergeRedeclarableTemplate(), and VisitRedeclarableTemplateDecl().
VisitVarTemplatePartialSpecializationDecl()
void ASTDeclReader::VisitVarTemplatePartialSpecializationDecl (VarTemplatePartialSpecializationDecl * D)
TODO: Unify with ClassTemplatePartialSpecializationDecl version? May require unifying ClassTemplate(Partial)SpecializationDecl and VarTemplate(Partial)SpecializationDecl with a new data structure Template(Partial)SpecializationDecl, and using Template(Partial)SpecializationDecl as input type.
Definition at line 2614 of file ASTReaderDecl.cpp.
References clang::ASTRecordReader::readASTTemplateArgumentListInfo(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateParameterList(), and VisitVarTemplateSpecializationDeclImpl().
VisitVarTemplateSpecializationDecl()
void clang::ASTDeclReader::VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl * D) inline
Definition at line 366 of file ASTReaderDecl.cpp.
References VisitVarTemplateSpecializationDeclImpl().
VisitVarTemplateSpecializationDeclImpl()
ASTDeclReader::RedeclarableResult ASTDeclReader::VisitVarTemplateSpecializationDeclImpl (VarTemplateSpecializationDecl * D)
TODO: Unify with ClassTemplateSpecializationDecl version? May require unifying ClassTemplate(Partial)SpecializationDecl and VarTemplate(Partial)SpecializationDecl with a new data structure Template(Partial)SpecializationDecl, and using Template(Partial)SpecializationDecl as input type.
Definition at line 2548 of file ASTReaderDecl.cpp.
References clang::C, clang::cast(), clang::TemplateArgumentList::CreateCopy(), clang::ASTReader::getContext(), clang::Decl::isCanonicalDecl(), mergeRedeclarable(), clang::ASTRecordReader::readInt(), clang::ASTRecordReader::readTemplateArgumentList(), and VisitVarDeclImpl().
Referenced by VisitVarTemplatePartialSpecializationDecl(), and VisitVarTemplateSpecializationDecl().
The documentation for this class was generated from the following file:
lib/Serialization/ASTReaderDecl.cpp