clang: clang::api_notes::CommonTypeInfo Class Reference
clang::api_notes::CommonTypeInfo Class Reference
Describes API notes for types.
#include "clang/APINotes/Types.h"
Public Member Functions
CommonTypeInfo ()
const std::optional< std::string > & getSwiftBridge () const
void setSwiftBridge (const std::optional< std::string > &SwiftType)
void setSwiftBridge (const std::optional< llvm::StringRef > &SwiftType)
const std::optional< std::string > & getNSErrorDomain () const
void setNSErrorDomain (const std::optional< std::string > &Domain)
void setNSErrorDomain (const std::optional< llvm::StringRef > &Domain)
CommonTypeInfo & operator|= (const CommonTypeInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
std::optional< bool > isSwiftPrivate () const
void setSwiftPrivate (std::optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Friends
bool operator== (const CommonTypeInfo &LHS, const CommonTypeInfo &RHS)
Additional Inherited Members
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Detailed Description
Describes API notes for types.
Definition at line 130 of file Types.h.
Constructor & Destructor Documentation
CommonTypeInfo()
clang::api_notes::CommonTypeInfo::CommonTypeInfo () inline
Definition at line 140 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::CommonTypeInfo::dump (llvm::raw_ostream & OS) const
Definition at line 26 of file APINotesTypes.cpp.
References clang::api_notes::CommonEntityInfo::dump().
Referenced by clang::api_notes::ObjCContextInfo::dump(), clang::api_notes::TagInfo::dump(), and clang::api_notes::TypedefInfo::dump().
getNSErrorDomain()
const std::optional< std::string > & clang::api_notes::CommonTypeInfo::getNSErrorDomain () const inline
Definition at line 156 of file Types.h.
Referenced by operator|=().
getSwiftBridge()
const std::optional< std::string > & clang::api_notes::CommonTypeInfo::getSwiftBridge () const inline
Definition at line 142 of file Types.h.
Referenced by operator|=().
operator|=()
CommonTypeInfo & clang::api_notes::CommonTypeInfo::operator|= (const CommonTypeInfo & RHS) inline
Definition at line 171 of file Types.h.
References getNSErrorDomain(), getSwiftBridge(), setNSErrorDomain(), and setSwiftBridge().
setNSErrorDomain() [1/2]
void clang::api_notes::CommonTypeInfo::setNSErrorDomain (const std::optional< llvm::StringRef > & Domain) inline
Definition at line 164 of file Types.h.
References clang::Domain.
setNSErrorDomain() [2/2]
void clang::api_notes::CommonTypeInfo::setNSErrorDomain (const std::optional< std::string > & Domain) inline
Definition at line 160 of file Types.h.
References clang::Domain.
Referenced by operator|=().
setSwiftBridge() [1/2]
void clang::api_notes::CommonTypeInfo::setSwiftBridge (const std::optional< llvm::StringRef > & SwiftType) inline
Definition at line 150 of file Types.h.
setSwiftBridge() [2/2]
void clang::api_notes::CommonTypeInfo::setSwiftBridge (const std::optional< std::string > & SwiftType) inline
Definition at line 146 of file Types.h.
Referenced by operator|=().
Friends And Related Symbol Documentation
operator==
bool operator== (const CommonTypeInfo & LHS, const CommonTypeInfo & RHS) friend
Definition at line 186 of file Types.h.
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp