clang: clang::IncrementalAction Class Reference
clang::IncrementalAction Class Reference
A custom action enabling the incremental processing functionality.
Public Member Functions
IncrementalAction (CompilerInstance &CI, llvm::LLVMContext &LLVMCtx, llvm::Error &Err)
FrontendAction * getWrapped () const
TranslationUnitKind getTranslationUnitKind () override
For AST-based actions, the kind of translation unit we're handling.
void ExecuteAction () override
Callback to run the program action, using the initialized compiler instance.
void EndSourceFile () override
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
void FinalizeAction ()
Public Member Functions inherited from clang::WrapperFrontendAction
WrapperFrontendAction (std::unique_ptr< FrontendAction > WrappedAction)
Construct a WrapperFrontendAction from an existing action, taking ownership of it.
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
TranslationUnitKind getTranslationUnitKind () override
For AST-based actions, the kind of translation unit we're handling.
bool hasPCHSupport () const override
Does this action support use with PCH?
bool hasASTFileSupport () const override
Does this action support use with AST files?
bool hasIRSupport () const override
Does this action support use with IR files?
bool hasCodeCompletionSupport () const override
Does this action support use with code completion?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
Additional Inherited Members
Protected Member Functions inherited from clang::WrapperFrontendAction
bool PrepareToExecuteAction (CompilerInstance &CI) override
Prepare to execute the action on the given CompilerInstance.
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
bool BeginInvocation (CompilerInstance &CI) override
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
bool BeginSourceFileAction (CompilerInstance &CI) override
Callback at the start of processing a single input.
void ExecuteAction () override
Callback to run the program action, using the initialized compiler instance.
void EndSourceFile () override
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
void EndSourceFileAction () override
Callback at the end of processing a single input.
bool shouldEraseOutputFiles () override
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Protected Member Functions inherited from clang::FrontendAction
Protected Attributes inherited from clang::WrapperFrontendAction
std::unique_ptr< FrontendAction > WrappedAction
Detailed Description
A custom action enabling the incremental processing functionality.
The usual FrontendAction expects one call to ExecuteAction and once it sees a call to EndSourceFile it deletes some of the important objects such as Preprocessor and Sema assuming no further input will come.
IncrementalAction ensures it keep its underlying action's objects alive as long as the IncrementalParser needs them.
Definition at line 115 of file IncrementalParser.cpp.
Constructor & Destructor Documentation
IncrementalAction()
clang::IncrementalAction::IncrementalAction (CompilerInstance & CI, llvm::LLVMContext & LLVMCtx, llvm::Error & Err) inline
Definition at line 120 of file IncrementalParser.cpp.
References clang::frontend::ASTDump, clang::frontend::ASTPrint, clang::CreateFrontendAction(), clang::frontend::EmitAssembly, clang::frontend::EmitBC, clang::frontend::EmitLLVMOnly, clang::frontend::EmitObj, clang::CompilerInstance::getFrontendOpts(), clang::frontend::ParseSyntaxOnly, clang::frontend::PluginAction, clang::frontend::PrintPreprocessedInput, and clang::FrontendOptions::ProgramAction.
Member Function Documentation
EndSourceFile()
void clang::IncrementalAction::EndSourceFile () inline override virtual
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Reimplemented from clang::FrontendAction.
Definition at line 184 of file IncrementalParser.cpp.
References clang::WrapperFrontendAction::EndSourceFile(), and getWrapped().
Referenced by FinalizeAction().
ExecuteAction()
void clang::IncrementalAction::ExecuteAction () inline override virtual
Callback to run the program action, using the initialized compiler instance.
This is guaranteed to only be called between BeginSourceFileAction() and EndSourceFileAction().
Implements clang::FrontendAction.
Definition at line 160 of file IncrementalParser.cpp.
References clang::FrontendOptions::CodeCompletionAt, clang::CompilerInstance::createCodeCompletionConsumer(), clang::CompilerInstance::createSema(), clang::Preprocessor::EnterMainSourceFile(), clang::ParsedSourceLocation::FileName, clang::CompilerInstance::getCodeCompletionConsumer(), clang::FrontendAction::getCompilerInstance(), clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getPreprocessor(), getTranslationUnitKind(), clang::CompilerInstance::hasCodeCompletionConsumer(), clang::WrapperFrontendAction::hasCodeCompletionSupport(), clang::CompilerInstance::hasPreprocessor(), and clang::CompilerInstance::hasSema().
FinalizeAction()
void clang::IncrementalAction::FinalizeAction () inline
Definition at line 190 of file IncrementalParser.cpp.
References EndSourceFile().
getTranslationUnitKind()
TranslationUnitKind clang::IncrementalAction::getTranslationUnitKind () inline override virtual
For AST-based actions, the kind of translation unit we're handling.
Reimplemented from clang::FrontendAction.
Definition at line 157 of file IncrementalParser.cpp.
References clang::TU_Incremental.
Referenced by ExecuteAction().
getWrapped()
FrontendAction * clang::IncrementalAction::getWrapped () const inline
Definition at line 156 of file IncrementalParser.cpp.
References clang::WrapperFrontendAction::WrappedAction.
Referenced by EndSourceFile().
The documentation for this class was generated from the following file:
lib/Interpreter/IncrementalParser.cpp