clang: clang::DataflowWorklistBase< Comp, QueueSize > Class Template Reference
clang::DataflowWorklistBase< Comp, QueueSize > Class Template Reference
A worklist implementation where the enqueued blocks will be dequeued based on the order defined by 'Comp'.
#include "clang/Analysis/FlowSensitive/DataflowWorklist.h"
Public Member Functions
DataflowWorklistBase (const CFG &Cfg, PostOrderCFGView *POV, Comp C)
const PostOrderCFGView * getCFGView () const
void enqueueBlock (const CFGBlock *Block)
const CFGBlock * dequeue ()
Detailed Description
template<typename Comp, unsigned QueueSize>
class clang::DataflowWorklistBase< Comp, QueueSize >
A worklist implementation where the enqueued blocks will be dequeued based on the order defined by 'Comp'.
Definition at line 22 of file DataflowWorklist.h.
Constructor & Destructor Documentation
DataflowWorklistBase()
template<typename Comp , unsigned QueueSize> clang::DataflowWorklistBase< Comp, QueueSize >::DataflowWorklistBase (const CFG & Cfg, PostOrderCFGView * POV, Comp C) inline
Definition at line 30 of file DataflowWorklist.h.
Member Function Documentation
dequeue()
template<typename Comp , unsigned QueueSize> const CFGBlock * clang::DataflowWorklistBase< Comp, QueueSize >::dequeue () inline
Definition at line 42 of file DataflowWorklist.h.
References clang::CFGBlock::getBlockID().
Referenced by clang::LiveVariables::computeLiveness(), clang::dataflow::runTypeErasedDataflowAnalysis(), and clang::runUninitializedVariablesAnalysis().
enqueueBlock()
template<typename Comp , unsigned QueueSize> void clang::DataflowWorklistBase< Comp, QueueSize >::enqueueBlock (const CFGBlock * Block) inline
Definition at line 35 of file DataflowWorklist.h.
References clang::Block.
Referenced by clang::LiveVariables::computeLiveness().
getCFGView()
template<typename Comp , unsigned QueueSize> const PostOrderCFGView * clang::DataflowWorklistBase< Comp, QueueSize >::getCFGView () const inline
Definition at line 33 of file DataflowWorklist.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/DataflowWorklist.h