clang: clang::tooling::stdlib::Header Class Reference
clang::tooling::stdlib::Header Class Reference
#include "clang/Tooling/Inclusions/StandardLibrary.h"
Public Member Functions
llvm::StringRef name () const
Static Public Member Functions
static std::vector< Header > all (Lang L=Lang::CXX)
static std::optional< Header > named (llvm::StringRef Name, Lang Language=Lang::CXX)
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Header &H)
bool operator== (const Header &L, const Header &R)
Detailed Description
Definition at line 39 of file StandardLibrary.h.
Member Function Documentation
all()
std::vector< Header > clang::tooling::stdlib::Header::all (Lang L = Lang::CXX) static
Definition at line 159 of file StandardLibrary.cpp.
References clang::tooling::stdlib::ensureInitialized(), clang::tooling::stdlib::getMappingPerLang(), and clang::Result.
name()
llvm::StringRef clang::tooling::stdlib::Header::name () const
Definition at line 176 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang().
named()
std::optional< Header > clang::tooling::stdlib::Header::named (llvm::StringRef Name, Lang Language = Lang::CXX) static
Definition at line 168 of file StandardLibrary.cpp.
References clang::tooling::stdlib::ensureInitialized(), and clang::tooling::stdlib::getMappingPerLang().
Friends And Related Symbol Documentation
operator<<
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const Header & H) friend
Definition at line 46 of file StandardLibrary.h.
operator==
bool operator== (const Header & L, const Header & R) friend
Definition at line 58 of file StandardLibrary.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/Inclusions/StandardLibrary.h
lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp