clang: clang::BlockDecl Class Reference
clang::BlockDecl Class Reference
Represents a block literal declaration, which is like an unnamed FunctionDecl.
#include "clang/AST/Decl.h"
Classes
class Capture
A class which contains all the information about a particular captured value.
Public Types
using param_iterator = MutableArrayRef<ParmVarDecl *>::iterator
using param_const_iterator = ArrayRef<ParmVarDecl *>::const_iterator
using capture_const_iterator = ArrayRef<Capture>::const_iterator
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Types inherited from clang::DeclContext
using decl_range = llvm::iterator_range<decl_iterator>
using lookup_result = DeclContextLookupResult
using lookup_iterator = lookup_result::iterator
using lookups_range = llvm::iterator_range<all_lookups_iterator>
using udir_iterator_base
using udir_range = llvm::iterator_range<udir_iterator>
using ddiag_range = llvm::iterator_range<DeclContext::ddiag_iterator>
Public Member Functions
SourceLocation getCaretLocation () const
bool isVariadic () const
void setIsVariadic (bool value)
CompoundStmt * getCompoundBody () const
Stmt * getBody () const override
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
void setBody (CompoundStmt *B)
void setSignatureAsWritten (TypeSourceInfo *Sig)
TypeSourceInfo * getSignatureAsWritten () const
ArrayRef< ParmVarDecl * > parameters () const
MutableArrayRef< ParmVarDecl * > parameters ()
bool param_empty () const
param_iterator param_begin ()
param_iterator param_end ()
param_const_iterator param_begin () const
param_const_iterator param_end () const
size_t param_size () const
unsigned getNumParams () const
const ParmVarDecl * getParamDecl (unsigned i) const
ParmVarDecl * getParamDecl (unsigned i)
void setParams (ArrayRef< ParmVarDecl * > NewParamInfo)
bool hasCaptures () const
True if this block (or its nested blocks) captures anything of local storage from its enclosing scopes.
unsigned getNumCaptures () const
Returns the number of captured variables.
ArrayRef< Capture > captures () const
capture_const_iterator capture_begin () const
capture_const_iterator capture_end () const
bool capturesCXXThis () const
void setCapturesCXXThis (bool B=true)
bool blockMissingReturnType () const
void setBlockMissingReturnType (bool val=true)
bool isConversionFromLambda () const
void setIsConversionFromLambda (bool val=true)
bool doesNotEscape () const
void setDoesNotEscape (bool B=true)
bool canAvoidCopyToHeap () const
void setCanAvoidCopyToHeap (bool B=true)
bool capturesVariable (const VarDecl *var) const
void setCaptures (ASTContext &Context, ArrayRef< Capture > Captures, bool CapturesCXXThis)
unsigned getBlockManglingNumber () const
Decl * getBlockManglingContextDecl () const
void setBlockMangling (unsigned Number, Decl *Ctx)
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isDiscardedInGlobalModuleFragment () const
FIXME: Implement discarding declarations actually in global module fragment.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
virtual Decl * getCanonicalDecl ()
Retrieves the "canonical" declaration of the given declaration.
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Public Member Functions inherited from clang::DeclContext
~DeclContext ()
bool hasValidDeclKind () const
Decl::Kind getDeclKind () const
const char * getDeclKindName () const
DeclContext * getParent ()
getParent - Returns the containing DeclContext.
const DeclContext * getParent () const
DeclContext * getLexicalParent ()
getLexicalParent - Returns the containing lexical DeclContext.
const DeclContext * getLexicalParent () const
DeclContext * getLookupParent ()
Find the parent context of this context that will be used for unqualified name lookup.
const DeclContext * getLookupParent () const
ASTContext & getParentASTContext () const
bool isClosure () const
const BlockDecl * getInnermostBlockDecl () const
Return this DeclContext if it is a BlockDecl.
bool isObjCContainer () const
bool isFunctionOrMethod () const
bool isLookupContext () const
Test whether the context supports looking up names.
bool isFileContext () const
bool isTranslationUnit () const
bool isRecord () const
bool isNamespace () const
bool isStdNamespace () const
bool isInlineNamespace () const
bool isDependentContext () const
Determines whether this context is dependent on a template parameter.
bool isTransparentContext () const
isTransparentContext - Determines whether this context is a "transparent" context, meaning that the members declared in this context are semantically declared in the nearest enclosing non-transparent (opaque) context but are lexically declared in this context.
bool isExternCContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C linkage.
const LinkageSpecDecl * getExternCContext () const
Retrieve the nearest enclosing C linkage specification context.
bool isExternCXXContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C++ linkage.
bool Equals (const DeclContext *DC) const
Determine whether this declaration context is equivalent to the declaration context DC.
bool Encloses (const DeclContext *DC) const
Determine whether this declaration context encloses the declaration context DC.
Decl * getNonClosureAncestor ()
Find the nearest non-closure ancestor of this context, i.e.
const Decl * getNonClosureAncestor () const
DeclContext * getNonTransparentContext ()
const DeclContext * getNonTransparentContext () const
DeclContext * getPrimaryContext ()
getPrimaryContext - There may be many different declarations of the same entity (including forward declarations of classes, multiple definitions of namespaces, etc.), each with a different set of declarations.
const DeclContext * getPrimaryContext () const
DeclContext * getRedeclContext ()
getRedeclContext - Retrieve the context in which an entity conflicts with other entities of the same name, or where it is a redeclaration if the two entities are compatible.
const DeclContext * getRedeclContext () const
DeclContext * getEnclosingNamespaceContext ()
Retrieve the nearest enclosing namespace context.
const DeclContext * getEnclosingNamespaceContext () const
RecordDecl * getOuterLexicalRecordContext ()
Retrieve the outermost lexically enclosing record context.
const RecordDecl * getOuterLexicalRecordContext () const
bool InEnclosingNamespaceSetOf (const DeclContext *NS) const
Test if this context is part of the enclosing namespace set of the context NS, as defined in C++0x [namespace.def]p9.
void collectAllContexts (SmallVectorImpl< DeclContext * > &Contexts)
Collects all of the declaration contexts that are semantically connected to this declaration context.
decl_range decls () const
decls_begin/decls_end - Iterate over the declarations stored in this context.
decl_iterator decls_begin () const
decl_iterator decls_end () const
bool decls_empty () const
decl_range noload_decls () const
noload_decls_begin/end - Iterate over the declarations stored in this context that are currently loaded; don't attempt to retrieve anything from an external source.
decl_iterator noload_decls_begin () const
decl_iterator noload_decls_end () const
void addDecl (Decl *D)
Add the declaration D into this context.
void addDeclInternal (Decl *D)
Add the declaration D into this context, but suppress searches for external declarations with the same name.
void addHiddenDecl (Decl *D)
Add the declaration D to this context without modifying any lookup tables.
void removeDecl (Decl *D)
Removes a declaration from this context.
bool containsDecl (Decl *D) const
Checks whether a declaration is in this context.
bool containsDeclAndLoad (Decl *D) const
Checks whether a declaration is in this context.
lookup_result lookup (DeclarationName Name) const
lookup - Find the declarations (if any) with the given Name in this context.
lookup_result noload_lookup (DeclarationName Name)
Find the declarations with the given name that are visible within this context; don't attempt to retrieve anything from an external source.
void localUncachedLookup (DeclarationName Name, SmallVectorImpl< NamedDecl * > &Results)
A simplistic name lookup mechanism that performs name lookup into this declaration context without consulting the external source.
void makeDeclVisibleInContext (NamedDecl *D)
Makes a declaration visible within this context.
lookups_range lookups () const
lookups_range noload_lookups (bool PreserveInternalState) const
all_lookups_iterator lookups_begin () const
Iterators over all possible lookups within this context.
all_lookups_iterator lookups_end () const
all_lookups_iterator noload_lookups_begin () const
Iterators over all possible lookups within this context that are currently loaded; don't attempt to retrieve anything from an external source.
all_lookups_iterator noload_lookups_end () const
udir_range using_directives () const
Returns iterator range [First, Last) of UsingDirectiveDecls stored within this context.
ddiag_range ddiags () const
void setMustBuildLookupTable ()
Mark that there are external lexical declarations that we need to include in our lookup table (and that are not available as external visible lookups).
StoredDeclsMap * getLookupPtr () const
Retrieve the internal representation of the lookup structure.
StoredDeclsMap * buildLookup ()
Ensure the lookup structure is fully-built and return it.
bool hasExternalLexicalStorage () const
Whether this DeclContext has external storage containing additional declarations that are lexically in this context.
void setHasExternalLexicalStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations lexically in this context.
bool hasExternalVisibleStorage () const
Whether this DeclContext has external storage containing additional declarations that are visible in this context.
void setHasExternalVisibleStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations visible in this context.
bool isDeclInLexicalTraversal (const Decl *D) const
Determine whether the given declaration is stored in the list of declarations lexically within this context.
void setUseQualifiedLookup (bool use=true) const
bool shouldUseQualifiedLookup () const
void dumpAsDecl () const
void dumpAsDecl (const ASTContext *Ctx) const
void dumpDeclContext () const
void dumpLookups () const
void dumpLookups (llvm::raw_ostream &OS, bool DumpDecls=false, bool Deserialize=false) const
Static Public Member Functions
static BlockDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation L)
static BlockDecl * CreateDeserialized (ASTContext &C, unsigned ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const BlockDecl *D)
static BlockDecl * castFromDeclContext (const DeclContext *DC)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Static Public Member Functions inherited from clang::DeclContext
static bool classof (const Decl *D)
static bool classof (const DeclContext *D)
Protected Member Functions
BlockDecl (DeclContext *DC, SourceLocation CaretLoc)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
virtual Decl * getNextRedeclarationImpl ()
Returns the next redeclaration or itself if this is the only decl.
virtual Decl * getPreviousDeclImpl ()
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
virtual Decl * getMostRecentDeclImpl ()
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::DeclContext
DeclContext (Decl::Kind K)
Additional Inherited Members
Public Attributes inherited from clang::DeclContext
Static Protected Member Functions inherited from clang::DeclContext
static std::pair< Decl *, Decl * > BuildDeclChain (ArrayRef< Decl * > Decls, bool FieldsAlreadyLoaded)
Build up a chain of declarations.
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::DeclContext
union {
DeclContextBitfields DeclContextBits
TagDeclBitfields TagDeclBits
EnumDeclBitfields EnumDeclBits
RecordDeclBitfields RecordDeclBits
OMPDeclareReductionDeclBitfields OMPDeclareReductionDeclBits
FunctionDeclBitfields FunctionDeclBits
CXXConstructorDeclBitfields CXXConstructorDeclBits
ObjCMethodDeclBitfields ObjCMethodDeclBits
ObjCContainerDeclBitfields ObjCContainerDeclBits
LinkageSpecDeclBitfields LinkageSpecDeclBits
BlockDeclBitfields BlockDeclBits
};
This anonymous union stores the bits belonging to DeclContext and classes deriving from it.
Decl * FirstDecl = nullptr
FirstDecl - The first declaration stored within this declaration context.
Decl * LastDecl = nullptr
LastDecl - The last declaration stored within this declaration context.
Detailed Description
Represents a block literal declaration, which is like an unnamed FunctionDecl.
For example: ^{ statement-body } or ^(int arg1, float arg2){ statement-body }
Definition at line 4371 of file Decl.h.
Member Typedef Documentation
capture_const_iterator
using clang::BlockDecl::capture_const_iterator = ArrayRef<Capture>::const_iterator
Definition at line 4496 of file Decl.h.
param_const_iterator
using clang::BlockDecl::param_const_iterator = ArrayRef<ParmVarDecl *>::const_iterator
Definition at line 4466 of file Decl.h.
param_iterator
using clang::BlockDecl::param_iterator = MutableArrayRef<ParmVarDecl *>::iterator
Definition at line 4465 of file Decl.h.
Constructor & Destructor Documentation
BlockDecl()
BlockDecl::BlockDecl (DeclContext * DC, SourceLocation CaretLoc) protected
Definition at line 5041 of file Decl.cpp.
References setBlockMissingReturnType(), setCanAvoidCopyToHeap(), setCapturesCXXThis(), setDoesNotEscape(), setIsConversionFromLambda(), and setIsVariadic().
Referenced by Create(), and CreateDeserialized().
Member Function Documentation
blockMissingReturnType()
bool clang::BlockDecl::blockMissingReturnType () const inline
Definition at line 4506 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::ASTDeclWriter::VisitBlockDecl().
canAvoidCopyToHeap()
bool clang::BlockDecl::canAvoidCopyToHeap () const inline
Definition at line 4525 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::ASTDeclWriter::VisitBlockDecl().
capture_begin()
capture_const_iterator clang::BlockDecl::capture_begin () const inline
Definition at line 4500 of file Decl.h.
References captures().
Referenced by computeBlockInfo(), and clang::ento::ExprEngine::VisitBlockExpr().
capture_end()
capture_const_iterator clang::BlockDecl::capture_end () const inline
Definition at line 4501 of file Decl.h.
References captures().
Referenced by computeBlockInfo(), and clang::ento::ExprEngine::VisitBlockExpr().
captures()
ArrayRef< Capture > clang::BlockDecl::captures () const inline
Definition at line 4498 of file Decl.h.
Referenced by capture_begin(), capture_end(), capturesVariable(), computeBlockInfo(), isAccessedBy(), LazyInitializeReferencedDecls(), markEscapingByrefs(), clang::ASTDeclWriter::VisitBlockDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl().
capturesCXXThis()
bool clang::BlockDecl::capturesCXXThis () const inline
Definition at line 4503 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by computeBlockInfo(), hasCaptures(), clang::ASTDeclWriter::VisitBlockDecl(), clang::JSONNodeDumper::VisitBlockDecl(), and clang::TextNodeDumper::VisitBlockDecl().
capturesVariable()
bool BlockDecl::capturesVariable (const VarDecl * var) const
Definition at line 5075 of file Decl.cpp.
References captures().
Referenced by findCapturingExpr().
castFromDeclContext()
static BlockDecl * clang::BlockDecl::castFromDeclContext (const DeclContext * DC) inline static
Definition at line 4554 of file Decl.h.
castToDeclContext()
static DeclContext * clang::BlockDecl::castToDeclContext (const BlockDecl * D) inline static
Definition at line 4551 of file Decl.h.
classof()
static bool clang::BlockDecl::classof (const Decl * D) inline static
Definition at line 4549 of file Decl.h.
References classofKind().
classofKind()
static bool clang::BlockDecl::classofKind (Kind K) inline static
Definition at line 4550 of file Decl.h.
References clang::Block.
Referenced by classof().
Create()
BlockDecl * BlockDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation L) static
Definition at line 5231 of file Decl.cpp.
References BlockDecl(), and clang::C.
Referenced by clang::Sema::ActOnBlockStart(), and clang::Sema::BuildBlockForLambdaConversion().
CreateDeserialized()
BlockDecl * BlockDecl::CreateDeserialized (ASTContext & C, unsigned ID) static
Definition at line 5235 of file Decl.cpp.
References BlockDecl(), and clang::C.
doesNotEscape()
bool clang::BlockDecl::doesNotEscape () const inline
Definition at line 4522 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by computeBlockInfo(), diagnoseImplicitlyRetainedSelf(), markEscapingByrefs(), and clang::ASTDeclWriter::VisitBlockDecl().
getBlockManglingContextDecl()
Decl * clang::BlockDecl::getBlockManglingContextDecl () const inline
Definition at line 4539 of file Decl.h.
getBlockManglingNumber()
unsigned clang::BlockDecl::getBlockManglingNumber () const inline
Definition at line 4537 of file Decl.h.
getBody()
Stmt * clang::BlockDecl::getBody () const inline override virtual
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
Otherwise this method returns null.
Reimplemented from clang::Decl.
Definition at line 4450 of file Decl.h.
Referenced by findCapturingExpr(), clang::BlockExpr::getBody(), clang::BlockExpr::getBody(), LazyInitializeReferencedDecls(), clang::ASTDeclWriter::VisitBlockDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl().
getCaretLocation()
SourceLocation clang::BlockDecl::getCaretLocation () const inline
Definition at line 4444 of file Decl.h.
References clang::Decl::getLocation().
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::BlockExpr::getCaretLocation(), and markEscapingByrefs().
getCompoundBody()
CompoundStmt * clang::BlockDecl::getCompoundBody () const inline
Definition at line 4449 of file Decl.h.
getNumCaptures()
unsigned clang::BlockDecl::getNumCaptures () const inline
Returns the number of captured variables.
Does not include an entry for 'this'.
Definition at line 4494 of file Decl.h.
Referenced by clang::ASTDeclWriter::VisitBlockDecl().
getNumParams()
unsigned clang::BlockDecl::getNumParams () const inline
Definition at line 4475 of file Decl.h.
Referenced by getParamDecl(), getParamDecl(), parameters(), and parameters().
getParamDecl() [1/2]
ParmVarDecl * clang::BlockDecl::getParamDecl (unsigned i) inline
Definition at line 4481 of file Decl.h.
References getNumParams().
getParamDecl() [2/2]
const ParmVarDecl * clang::BlockDecl::getParamDecl (unsigned i) const inline
Definition at line 4477 of file Decl.h.
References getNumParams().
Referenced by checkOpenCLBlockArgs().
getSignatureAsWritten()
TypeSourceInfo * clang::BlockDecl::getSignatureAsWritten () const inline
Definition at line 4454 of file Decl.h.
Referenced by clang::ento::MemRegionManager::getVarRegion(), and clang::ASTDeclWriter::VisitBlockDecl().
getSourceRange()
SourceRange BlockDecl::getSourceRange () const override virtual
Source range that this declaration covers.
Reimplemented from clang::Decl.
Definition at line 5084 of file Decl.cpp.
References clang::Stmt::getEndLoc(), and clang::Decl::getLocation().
hasCaptures()
bool clang::BlockDecl::hasCaptures () const inline
True if this block (or its nested blocks) captures anything of local storage from its enclosing scopes.
Definition at line 4490 of file Decl.h.
References capturesCXXThis().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), computeBlockInfo(), and clang::ento::MemRegionManager::getBlockDataRegion().
isConversionFromLambda()
bool clang::BlockDecl::isConversionFromLambda () const inline
Definition at line 4514 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::ento::BlockCall::isConversionFromLambda(), and clang::ASTDeclWriter::VisitBlockDecl().
isVariadic()
bool clang::BlockDecl::isVariadic () const inline
Definition at line 4446 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::ASTDeclWriter::VisitBlockDecl(), clang::JSONNodeDumper::VisitBlockDecl(), and clang::TextNodeDumper::VisitBlockDecl().
param_begin() [1/2]
param_iterator clang::BlockDecl::param_begin () inline
Definition at line 4469 of file Decl.h.
References parameters().
param_begin() [2/2]
param_const_iterator clang::BlockDecl::param_begin () const inline
Definition at line 4471 of file Decl.h.
References parameters().
param_empty()
bool clang::BlockDecl::param_empty () const inline
Definition at line 4468 of file Decl.h.
References parameters().
param_end() [1/2]
param_iterator clang::BlockDecl::param_end () inline
Definition at line 4470 of file Decl.h.
References parameters().
param_end() [2/2]
param_const_iterator clang::BlockDecl::param_end () const inline
Definition at line 4472 of file Decl.h.
References parameters().
param_size()
size_t clang::BlockDecl::param_size () const inline
Definition at line 4473 of file Decl.h.
References parameters().
Referenced by clang::ASTDeclWriter::VisitBlockDecl().
parameters() [1/2]
MutableArrayRef< ParmVarDecl * > clang::BlockDecl::parameters () inline
Definition at line 4460 of file Decl.h.
References getNumParams().
parameters() [2/2]
ArrayRef< ParmVarDecl * > clang::BlockDecl::parameters () const inline
Definition at line 4457 of file Decl.h.
References getNumParams().
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBlockStmtExpr(), clang::ento::MemRegionManager::getVarRegion(), param_begin(), param_begin(), param_empty(), param_end(), param_end(), param_size(), clang::ento::BlockCall::parameters(), clang::ASTDeclWriter::VisitBlockDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl().
setBlockMangling()
void clang::BlockDecl::setBlockMangling (unsigned Number, Decl * Ctx) inline
Definition at line 4541 of file Decl.h.
setBlockMissingReturnType()
void clang::BlockDecl::setBlockMissingReturnType (bool val = true) inline
Definition at line 4510 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::Sema::ActOnBlockArguments(), BlockDecl(), and clang::ASTDeclReader::VisitBlockDecl().
setBody()
void clang::BlockDecl::setBody (CompoundStmt * B) inline
Definition at line 4451 of file Decl.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), and clang::ASTDeclReader::VisitBlockDecl().
setCanAvoidCopyToHeap()
void clang::BlockDecl::setCanAvoidCopyToHeap (bool B = true) inline
Definition at line 4528 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by BlockDecl(), and clang::ASTDeclReader::VisitBlockDecl().
setCaptures()
void BlockDecl::setCaptures (ASTContext & Context, ArrayRef< Capture > Captures, bool CapturesCXXThis)
Definition at line 5062 of file Decl.cpp.
References setCapturesCXXThis().
Referenced by clang::Sema::ActOnBlockStmtExpr(), and clang::ASTDeclReader::VisitBlockDecl().
setCapturesCXXThis()
void clang::BlockDecl::setCapturesCXXThis (bool B = true) inline
Definition at line 4504 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by BlockDecl(), and setCaptures().
setDoesNotEscape()
void clang::BlockDecl::setDoesNotEscape (bool B = true) inline
Definition at line 4523 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by BlockDecl(), and clang::ASTDeclReader::VisitBlockDecl().
setIsConversionFromLambda()
void clang::BlockDecl::setIsConversionFromLambda (bool val = true) inline
Definition at line 4518 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by BlockDecl(), and clang::ASTDeclReader::VisitBlockDecl().
setIsVariadic()
void clang::BlockDecl::setIsVariadic (bool value) inline
Definition at line 4447 of file Decl.h.
References clang::DeclContext::BlockDeclBits.
Referenced by clang::Sema::ActOnBlockArguments(), BlockDecl(), and clang::ASTDeclReader::VisitBlockDecl().
setParams()
void BlockDecl::setParams (ArrayRef< ParmVarDecl * > NewParamInfo)
Definition at line 5051 of file Decl.cpp.
References clang::Decl::getASTContext().
Referenced by clang::Sema::ActOnBlockArguments(), and clang::ASTDeclReader::VisitBlockDecl().
setSignatureAsWritten()
void clang::BlockDecl::setSignatureAsWritten (TypeSourceInfo * Sig) inline
Definition at line 4453 of file Decl.h.
Referenced by clang::Sema::ActOnBlockArguments(), and clang::ASTDeclReader::VisitBlockDecl().
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp