clang: clang::Sema::ExtParameterInfoBuilder Class Reference
clang::Sema::ExtParameterInfoBuilder Class Reference
A helper class for building up ExtParameterInfos.
#include "clang/Sema/Sema.h"
Public Member Functions
void set (unsigned index, FunctionProtoType::ExtParameterInfo info)
Set the ExtParameterInfo for the parameter at the given index,.
const FunctionProtoType::ExtParameterInfo * getPointerOrNull (unsigned numParams)
Return a pointer (suitable for setting in an ExtProtoInfo) to the ExtParameterInfo array we've built up.
Detailed Description
A helper class for building up ExtParameterInfos.
Definition at line 10037 of file Sema.h.
Member Function Documentation
getPointerOrNull()
const FunctionProtoType::ExtParameterInfo * clang::Sema::ExtParameterInfoBuilder::getPointerOrNull (unsigned numParams) inline
Return a pointer (suitable for setting in an ExtProtoInfo) to the ExtParameterInfo array we've built up.
Definition at line 10056 of file Sema.h.
Referenced by clang::Sema::SubstituteExplicitTemplateArguments(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
set()
void clang::Sema::ExtParameterInfoBuilder::set (unsigned index, FunctionProtoType::ExtParameterInfo info) inline
Set the ExtParameterInfo for the parameter at the given index,.
Definition at line 10044 of file Sema.h.
Referenced by clang::TreeTransform< Derived >::TransformFunctionTypeParams().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h