clang: clang::tooling::stdlib::Symbol Class Reference
clang::tooling::stdlib::Symbol Class Reference
#include "clang/Tooling/Inclusions/StandardLibrary.h"
Public Member Functions
llvm::StringRef scope () const
llvm::StringRef name () const
llvm::StringRef qualifiedName () const
std::optional< Header > header () const
llvm::SmallVector< Header > headers () const
Static Public Member Functions
static std::vector< Symbol > all (Lang L=Lang::CXX)
static std::optional< Symbol > named (llvm::StringRef Scope, llvm::StringRef Name, Lang Language=Lang::CXX)
Scope should have the trailing "::", for example: named("std::chrono::", "system_clock")
Friends
class Recognizer
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Symbol &S)
bool operator== (const Symbol &L, const Symbol &R)
Detailed Description
Definition at line 69 of file StandardLibrary.h.
Member Function Documentation
all()
std::vector< Symbol > clang::tooling::stdlib::Symbol::all (Lang L = Lang::CXX) static
Definition at line 180 of file StandardLibrary.cpp.
References clang::tooling::stdlib::ensureInitialized(), clang::tooling::stdlib::getMappingPerLang(), and clang::Result.
header()
std::optional< Header > clang::tooling::stdlib::Symbol::header () const
Definition at line 210 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang().
headers()
llvm::SmallVector< Header > clang::tooling::stdlib::Symbol::headers () const
Definition at line 216 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang(), and SymbolHeaderIDs.
name()
llvm::StringRef clang::tooling::stdlib::Symbol::name () const
Definition at line 192 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang().
named()
std::optional< Symbol > clang::tooling::stdlib::Symbol::named (llvm::StringRef Scope, llvm::StringRef Name, Lang Language = Lang::CXX) static
Scope should have the trailing "::", for example: named("std::chrono::", "system_clock")
Definition at line 198 of file StandardLibrary.cpp.
References clang::tooling::stdlib::ensureInitialized(), clang::tooling::stdlib::getMappingPerLang(), and NamespaceSymbols.
qualifiedName()
llvm::StringRef clang::tooling::stdlib::Symbol::qualifiedName () const
Definition at line 195 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang().
scope()
llvm::StringRef clang::tooling::stdlib::Symbol::scope () const
Definition at line 189 of file StandardLibrary.cpp.
References clang::tooling::stdlib::getMappingPerLang().
Friends And Related Symbol Documentation
operator<<
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const Symbol & S) friend
Definition at line 77 of file StandardLibrary.h.
operator==
bool operator== (const Symbol & L, const Symbol & R) friend
Definition at line 95 of file StandardLibrary.h.
Recognizer
friend class Recognizer friend
Definition at line 93 of file StandardLibrary.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/Inclusions/StandardLibrary.h
lib/Tooling/Inclusions/Stdlib/StandardLibrary.cpp