clang: clang::ParsedAttr Class Reference
clang::ParsedAttr Class Reference final
ParsedAttr - Represents a syntactic attribute.
#include "clang/Sema/ParsedAttr.h"
Public Member Functions
ParsedAttr (const ParsedAttr &)=delete
ParsedAttr (ParsedAttr &&)=delete
ParsedAttr & operator= (const ParsedAttr &)=delete
ParsedAttr & operator= (ParsedAttr &&)=delete
~ParsedAttr ()=delete
void operator delete (void *)=delete
bool hasParsedType () const
bool isDeclspecPropertyAttribute () const
Is this the Microsoft __declspec(property) attribute?
bool isInvalid () const
void setInvalid (bool b=true) const
bool hasProcessingCache () const
unsigned getProcessingCache () const
void setProcessingCache (unsigned value) const
bool isUsedAsTypeAttr () const
void setUsedAsTypeAttr (bool Used=true)
bool isPragmaClangAttribute () const
True if the attribute is specified using '#pragma clang attribute'.
void setIsPragmaClangAttribute ()
bool isPackExpansion () const
SourceLocation getEllipsisLoc () const
unsigned getNumArgs () const
getNumArgs - Return the number of actual arguments to this attribute.
ArgsUnion getArg (unsigned Arg) const
getArg - Return the specified argument.
bool isArgExpr (unsigned Arg) const
Expr * getArgAsExpr (unsigned Arg) const
bool isArgIdent (unsigned Arg) const
IdentifierLoc * getArgAsIdent (unsigned Arg) const
const AvailabilityChange & getAvailabilityIntroduced () const
const AvailabilityChange & getAvailabilityDeprecated () const
const AvailabilityChange & getAvailabilityObsoleted () const
SourceLocation getStrictLoc () const
SourceLocation getUnavailableLoc () const
const Expr * getMessageExpr () const
const Expr * getReplacementExpr () const
const ParsedType & getMatchingCType () const
bool getLayoutCompatible () const
bool getMustBeNull () const
const ParsedType & getTypeArg () const
IdentifierInfo * getPropertyDataGetter () const
IdentifierInfo * getPropertyDataSetter () const
void setMacroIdentifier (IdentifierInfo *MacroName, SourceLocation Loc)
Set the macro identifier info object that this parsed attribute was declared in if it was declared in a macro.
bool hasMacroIdentifier () const
Returns true if this attribute was declared in a macro.
IdentifierInfo * getMacroIdentifier () const
Return the macro identifier if this attribute was declared in a macro.
SourceLocation getMacroExpansionLoc () const
bool checkExactlyNumArgs (class Sema &S, unsigned Num) const
Check if the attribute has exactly as many args as Num.
bool checkAtLeastNumArgs (class Sema &S, unsigned Num) const
Check if the attribute has at least as many args as Num.
bool checkAtMostNumArgs (class Sema &S, unsigned Num) const
Check if the attribute has at most as many args as Num.
bool isTargetSpecificAttr () const
bool isTypeAttr () const
bool isStmtAttr () const
bool hasCustomParsing () const
bool acceptsExprPack () const
bool isParamExpr (size_t N) const
unsigned getMinArgs () const
unsigned getMaxArgs () const
unsigned getNumArgMembers () const
bool hasVariadicArg () const
void handleAttrWithDelayedArgs (Sema &S, Decl *D) const
bool diagnoseAppertainsTo (class Sema &S, const Decl *D) const
bool diagnoseAppertainsTo (class Sema &S, const Stmt *St) const
bool diagnoseMutualExclusion (class Sema &S, const Decl *D) const
bool diagnoseMutualExclusion (class Sema &S, const Stmt *St) const
bool appliesToDecl (const Decl *D, attr::SubjectMatchRule MatchRule) const
void getMatchRules (const LangOptions &LangOpts, SmallVectorImpl< std::pair< attr::SubjectMatchRule, bool > > &MatchRules) const
bool diagnoseLangOpts (class Sema &S) const
bool existsInTarget (const TargetInfo &Target) const
bool isKnownToGCC () const
bool isSupportedByPragmaAttribute () const
bool slidesFromDeclToDeclSpecLegacyBehavior () const
Returns whether a [[]] attribute, if specified ahead of a declaration, should be applied to the decl-specifier-seq instead (i.e.
unsigned getSemanticSpelling () const
If the parsed attribute has a semantic equivalent, and it would have a semantic Spelling enumeration (due to having semantically-distinct spelling variations), return the value of that semantic spelling.
LangAS asOpenCLLangAS () const
If this is an OpenCL address space attribute, returns its representation in LangAS, otherwise returns default address space.
LangAS asSYCLLangAS () const
If this is an OpenCL address space attribute, returns its SYCL representation in LangAS, otherwise returns default address space.
LangAS asHLSLLangAS () const
If this is an HLSL address space attribute, returns its representation in LangAS, otherwise returns default address space.
AttributeCommonInfo::Kind getKind () const
const ParsedAttrInfo & getInfo () const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Form FormUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Form FormUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Form FormUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Form FormUsed)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
Form getForm () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isClangScope () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isStandardAttributeSyntax () const
The attribute is spelled [[]] in either C or C++ mode, including standard attributes spelled with a keyword, like alignas.
bool isGNUAttribute () const
bool isKeywordAttribute () const
bool isRegularKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Friends
class AttributeFactory
class AttributePool
Additional Inherited Members
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU = 1 , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword ,
AS_HLSLSemantic , AS_Implicit
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
ParsedAttr - Represents a syntactic attribute.
For a GNU attribute, there are four forms of this construct:
1: attribute((const)). ParmName/Args/NumArgs will all be unused. 2: attribute((mode(byte))). ParmName used, Args/NumArgs unused. 3: attribute((format(printf, 1, 2))). ParmName/Args/NumArgs all used. 4: attribute((aligned(16))). ParmName is unused, Args/Num used.
Definition at line 119 of file ParsedAttr.h.
Constructor & Destructor Documentation
ParsedAttr() [1/2]
clang::ParsedAttr::ParsedAttr (const ParsedAttr &) delete
ParsedAttr() [2/2]
clang::ParsedAttr::ParsedAttr (ParsedAttr &&) delete
~ParsedAttr()
clang::ParsedAttr::~ParsedAttr () delete
Member Function Documentation
acceptsExprPack()
bool ParsedAttr::acceptsExprPack () const
Definition at line 243 of file ParsedAttr.cpp.
References clang::ParsedAttrInfo::AcceptsExprPack, and getInfo().
Referenced by MustDelayAttributeArguments().
appliesToDecl()
bool ParsedAttr::appliesToDecl (const Decl * D, attr::SubjectMatchRule MatchRule) const
Definition at line 168 of file ParsedAttr.cpp.
asHLSLLangAS()
LangAS clang::ParsedAttr::asHLSLLangAS () const inline
If this is an HLSL address space attribute, returns its representation in LangAS, otherwise returns default address space.
Definition at line 597 of file ParsedAttr.h.
References clang::Default, clang::AttributeCommonInfo::getParsedKind(), and clang::hlsl_groupshared.
asOpenCLLangAS()
LangAS clang::ParsedAttr::asOpenCLLangAS () const inline
If this is an OpenCL address space attribute, returns its representation in LangAS, otherwise returns default address space.
Definition at line 554 of file ParsedAttr.h.
References clang::Default, clang::AttributeCommonInfo::getParsedKind(), clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_global_device, clang::opencl_global_host, clang::opencl_local, and clang::opencl_private.
asSYCLLangAS()
LangAS clang::ParsedAttr::asSYCLLangAS () const inline
If this is an OpenCL address space attribute, returns its SYCL representation in LangAS, otherwise returns default address space.
Definition at line 577 of file ParsedAttr.h.
References clang::Default, getKind(), clang::sycl_global, clang::sycl_global_device, clang::sycl_global_host, clang::sycl_local, and clang::sycl_private.
checkAtLeastNumArgs()
bool ParsedAttr::checkAtLeastNumArgs (class Sema & S, unsigned Num) const
Check if the attribute has at least as many args as Num.
May output an error. Returns false if a diagnostic is produced.
Definition at line 286 of file ParsedAttr.cpp.
References checkAttributeNumArgsImpl().
Referenced by checkAcquireOrderAttrCommon(), checkCommonAttributeFeatures(), checkTryLockFunAttrCommon(), handleAbiTagAttr(), handleAllocSizeAttr(), handleAMDGPUWavesPerEUAttr(), handleCallableWhenAttr(), handleCPUSpecificAttr(), handleExternalSourceSymbolAttr(), handleLaunchBoundsAttr(), handleLocksExcludedAttr(), handleNoSanitizeAttr(), handleRequiresCapabilityAttr(), and handleSuppressAttr().
checkAtMostNumArgs()
bool ParsedAttr::checkAtMostNumArgs (class Sema & S, unsigned Num) const
Check if the attribute has at most as many args as Num.
May output an error. Returns false if a diagnostic is produced.
Definition at line 291 of file ParsedAttr.cpp.
References checkAttributeNumArgsImpl().
Referenced by checkCommonAttributeFeatures(), handleAllocSizeAttr(), handleAMDGPUWavesPerEUAttr(), handleDeprecatedAttr(), handleExternalSourceSymbolAttr(), handleLaunchBoundsAttr(), and handleRISCVInterruptAttr().
checkExactlyNumArgs()
bool ParsedAttr::checkExactlyNumArgs (class Sema & S, unsigned Num) const
Check if the attribute has exactly as many args as Num.
May output an error. Returns false if a diagnostic is produced.
Definition at line 281 of file ParsedAttr.cpp.
References checkAttributeNumArgsImpl().
Referenced by clang::Sema::CheckAttrNoArgs(), clang::Sema::CheckCallingConvAttr(), checkCommonAttributeFeatures(), clang::Sema::CheckRegparmAttr(), handleAvailabilityAttr(), handleAVRInterruptAttr(), handleAVRSignalAttr(), handleM68kInterruptAttr(), handleMSP430InterruptAttr(), handleSwiftAsyncAttr(), handleSwiftAsyncError(), handleSwiftNewType(), and handleTypeTagForDatatypeAttr().
diagnoseAppertainsTo() [1/2]
bool ParsedAttr::diagnoseAppertainsTo (class Sema & S, const Decl * D) const
Definition at line 156 of file ParsedAttr.cpp.
References clang::ParsedAttrInfo::diagAppertainsToDecl(), and getInfo().
Referenced by checkCommonAttributeFeatures().
diagnoseAppertainsTo() [2/2]
bool ParsedAttr::diagnoseAppertainsTo (class Sema & S, const Stmt * St) const
Definition at line 160 of file ParsedAttr.cpp.
References clang::ParsedAttrInfo::diagAppertainsToStmt(), and getInfo().
diagnoseLangOpts()
bool ParsedAttr::diagnoseLangOpts (class Sema & S) const
Definition at line 180 of file ParsedAttr.cpp.
References clang::Sema::Diag(), getInfo(), clang::Sema::getLangOpts(), and clang::AttributeCommonInfo::getLoc().
Referenced by checkCommonAttributeFeatures().
diagnoseMutualExclusion() [1/2]
bool ParsedAttr::diagnoseMutualExclusion (class Sema & S, const Decl * D) const
Definition at line 164 of file ParsedAttr.cpp.
References clang::ParsedAttrInfo::diagMutualExclusion(), and getInfo().
Referenced by checkCommonAttributeFeatures().
diagnoseMutualExclusion() [2/2]
bool clang::ParsedAttr::diagnoseMutualExclusion (class Sema & S, const Stmt * St) const inline
Definition at line 521 of file ParsedAttr.h.
existsInTarget()
bool ParsedAttr::existsInTarget (const TargetInfo & Target) const
Definition at line 195 of file ParsedAttr.cpp.
References clang::ParsedAttrInfo::existsInTarget(), and getInfo().
Referenced by clang::Sema::CheckAttrTarget(), ProcessDeclAttribute(), and ProcessStmtAttribute().
getArg()
ArgsUnion clang::ParsedAttr::getArg (unsigned Arg) const inline
getArg - Return the specified argument.
Definition at line 374 of file ParsedAttr.h.
Referenced by getArgAsExpr(), getArgAsIdent(), handleDiagnoseAsBuiltinAttr(), isArgExpr(), and isArgIdent().
getArgAsExpr()
Expr * clang::ParsedAttr::getArgAsExpr (unsigned Arg) const inline
Definition at line 383 of file ParsedAttr.h.
References getArg().
Referenced by checkAttrArgsAreCapabilityObjs(), checkFunctionConditionAttr(), clang::Sema::CheckRegparmAttr(), clang::Sema::checkStringLiteralArgumentAttr(), checkTryLockFunAttrCommon(), handleAlignedAttr(), handleAlignValueAttr(), handleAllocAlignAttr(), handleAllocSizeAttr(), handleAMDGPUFlatWorkGroupSizeAttr(), handleAMDGPUNumSGPRAttr(), handleAMDGPUNumVGPRAttr(), handleAMDGPUWavesPerEUAttr(), handleAnnotateAttr(), HandleAnnotateTypeAttr(), handleArgumentWithTypeTagAttr(), handleAssumeAlignedAttr(), handleCallbackAttr(), handleCleanupAttr(), handleConstructorAttr(), handleDeprecatedAttr(), handleDestructorAttr(), handleDiagnoseAsBuiltinAttr(), handleDiagnoseIfAttr(), handleExclusiveTrylockFunctionAttr(), handleExternalSourceSymbolAttr(), handleFormatArgAttr(), handleFormatAttr(), handleHLSLNumThreadsAttr(), handleInitPriorityAttr(), handleLaunchBoundsAttr(), handleLayoutVersion(), handleLoopHintAttr(), handleM68kInterruptAttr(), handleMinVectorWidthAttr(), handleMSP430InterruptAttr(), handleNonNullAttr(), handleNSErrorDomain(), handleOpenCLUnrollHint(), handleOwnershipAttr(), handlePassObjectSizeAttr(), handlePatchableFunctionEntryAttr(), handleSentinelAttr(), handleSharedTrylockFunctionAttr(), handleSubGroupSize(), handleSwiftAsyncAttr(), handleSwiftAsyncError(), handleTargetClonesAttr(), handleTryAcquireCapabilityAttr(), handleWorkGroupSize(), handleXRayLogArgsAttr(), and MustDelayAttributeArguments().
getArgAsIdent()
IdentifierLoc * clang::ParsedAttr::getArgAsIdent (unsigned Arg) const inline
Definition at line 391 of file ParsedAttr.h.
References getArg().
Referenced by clang::Sema::checkStringLiteralArgumentAttr(), handleArgumentWithTypeTagAttr(), handleArmBuiltinAliasAttr(), handleAvailabilityAttr(), handleBlocksAttr(), handleBuiltinAliasAttr(), handleCallableWhenAttr(), handleCallbackAttr(), handleCFGuardAttr(), handleConsumableAttr(), handleCPUSpecificAttr(), handleEnumExtensibilityAttr(), handleExternalSourceSymbolAttr(), handleFormatAttr(), handleHLSLResourceBindingAttr(), handleLoopHintAttr(), handleModeAttr(), handleObjCBridgeAttr(), handleObjCBridgeMutableAttr(), handleObjCBridgeRelatedAttr(), handleObjCMethodFamilyAttr(), handleOwnershipAttr(), handleParamTypestateAttr(), handleReturnTypestateAttr(), handleSetTypestateAttr(), handleSwiftAsyncAttr(), handleSwiftAsyncError(), handleSwiftError(), handleSwiftNewType(), handleTestTypestateAttr(), and handleTypeTagForDatatypeAttr().
getAvailabilityDeprecated()
const AvailabilityChange & clang::ParsedAttr::getAvailabilityDeprecated () const inline
Definition at line 401 of file ParsedAttr.h.
References clang::detail::AvailabilityData::Changes, clang::detail::DeprecatedSlot, and clang::AttributeCommonInfo::getParsedKind().
Referenced by handleAvailabilityAttr().
getAvailabilityIntroduced()
const AvailabilityChange & clang::ParsedAttr::getAvailabilityIntroduced () const inline
Definition at line 395 of file ParsedAttr.h.
References clang::detail::AvailabilityData::Changes, clang::AttributeCommonInfo::getParsedKind(), and clang::detail::IntroducedSlot.
Referenced by handleAvailabilityAttr().
getAvailabilityObsoleted()
const AvailabilityChange & clang::ParsedAttr::getAvailabilityObsoleted () const inline
Definition at line 407 of file ParsedAttr.h.
References clang::detail::AvailabilityData::Changes, clang::AttributeCommonInfo::getParsedKind(), and clang::detail::ObsoletedSlot.
Referenced by handleAvailabilityAttr().
getEllipsisLoc()
SourceLocation clang::ParsedAttr::getEllipsisLoc () const inline
Definition at line 368 of file ParsedAttr.h.
Referenced by handleAlignedAttr().
getInfo()
const ParsedAttrInfo & clang::ParsedAttr::getInfo () const inline
Definition at line 609 of file ParsedAttr.h.
Referenced by acceptsExprPack(), diagnoseAppertainsTo(), diagnoseAppertainsTo(), diagnoseLangOpts(), diagnoseMutualExclusion(), existsInTarget(), getMatchRules(), getMaxArgs(), getMinArgs(), getNumArgMembers(), getSemanticSpelling(), hasCustomParsing(), hasVariadicArg(), isKnownToGCC(), isParamExpr(), isStmtAttr(), isSupportedByPragmaAttribute(), isTargetSpecificAttr(), isTypeAttr(), and ProcessDeclAttribute().
getKind()
AttributeCommonInfo::Kind clang::ParsedAttr::getKind () const inline
Definition at line 606 of file ParsedAttr.h.
References clang::ParsedAttrInfo::AttrKind.
Referenced by asSYCLLangAS(), clang::Sema::CheckCallingConvAttr(), checkCommonAttributeFeatures(), handleCallConvAttr(), handleCapabilityAttr(), handleCPUSpecificAttr(), handleDestroyAttr(), handleDLLAttr(), handleGlobalAttr(), handleLifetimeCategoryAttr(), handleMSPointerTypeQualifierAttr(), HandleWebAssemblyFuncrefAttr(), handleXReturnsXRetainedAttr(), parsedAttrToRetainOwnershipKind(), ProcessDeclAttribute(), and ProcessStmtAttribute().
getLayoutCompatible()
bool clang::ParsedAttr::getLayoutCompatible () const inline
Definition at line 443 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind(), and clang::detail::TypeTagForDatatypeData::LayoutCompatible.
Referenced by handleTypeTagForDatatypeAttr().
getMacroExpansionLoc()
SourceLocation clang::ParsedAttr::getMacroExpansionLoc () const inline
Definition at line 487 of file ParsedAttr.h.
References hasMacroIdentifier().
getMacroIdentifier()
IdentifierInfo * clang::ParsedAttr::getMacroIdentifier () const inline
Return the macro identifier if this attribute was declared in a macro.
nullptr is returned if it was not declared in a macro.
Definition at line 485 of file ParsedAttr.h.
getMatchingCType()
const ParsedType & clang::ParsedAttr::getMatchingCType () const inline
Definition at line 437 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind(), and clang::detail::TypeTagForDatatypeData::MatchingCType.
Referenced by handleTypeTagForDatatypeAttr().
getMatchRules()
void ParsedAttr::getMatchRules (const LangOptions & LangOpts, SmallVectorImpl< std::pair< attr::SubjectMatchRule, bool > > & MatchRules) const
Definition at line 173 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::getPragmaAttributeMatchRules().
getMaxArgs()
unsigned ParsedAttr::getMaxArgs () const
Definition at line 144 of file ParsedAttr.cpp.
References getInfo(), getMinArgs(), and clang::ParsedAttrInfo::OptArgs.
Referenced by checkCommonAttributeFeatures().
getMessageExpr()
const Expr * clang::ParsedAttr::getMessageExpr () const inline
Definition at line 425 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind().
Referenced by handleAvailabilityAttr().
getMinArgs()
unsigned ParsedAttr::getMinArgs () const
Definition at line 142 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::NumArgs.
Referenced by checkCommonAttributeFeatures(), and getMaxArgs().
getMustBeNull()
bool clang::ParsedAttr::getMustBeNull () const inline
Definition at line 449 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind(), and clang::detail::TypeTagForDatatypeData::MustBeNull.
Referenced by handleTypeTagForDatatypeAttr().
getNumArgMembers()
unsigned ParsedAttr::getNumArgMembers () const
Definition at line 148 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::NumArgMembers.
Referenced by MustDelayAttributeArguments().
getNumArgs()
unsigned clang::ParsedAttr::getNumArgs () const inline
getNumArgs - Return the number of actual arguments to this attribute.
Definition at line 371 of file ParsedAttr.h.
Referenced by checkAttrArgsAreCapabilityObjs(), getNumAttributeArgs(), getNumAttributeArgs(), handleAbiTagAttr(), handleAlignedAttr(), handleAllocSizeAttr(), handleAMDGPUWavesPerEUAttr(), handleAnnotateAttr(), HandleAnnotateTypeAttr(), handleARMInterruptAttr(), handleAssumeAlignedAttr(), handleAttrWithMessage(), handleCallableWhenAttr(), handleCallbackAttr(), handleConstructorAttr(), handleDestructorAttr(), handleDiagnoseAsBuiltinAttr(), handleHLSLResourceBindingAttr(), handleIBOutletCollection(), handleLaunchBoundsAttr(), handleMipsInterruptAttr(), handleNoBuiltinAttr(), handleNonNullAttr(), handleNonNullAttrParameter(), handleNoSanitizeAttr(), handleOpenCLUnrollHint(), handleOwnershipAttr(), handlePatchableFunctionEntryAttr(), handleRISCVInterruptAttr(), handleSentinelAttr(), handleSuppressAttr(), handleSuppressAttr(), handleTargetClonesAttr(), handleWarnUnusedResult(), handleWeakRefAttr(), and MustDelayAttributeArguments().
getProcessingCache()
unsigned clang::ParsedAttr::getProcessingCache () const inline
Definition at line 349 of file ParsedAttr.h.
References hasProcessingCache().
Referenced by clang::Sema::CheckCallingConvAttr().
getPropertyDataGetter()
IdentifierInfo * clang::ParsedAttr::getPropertyDataGetter () const inline
Definition at line 460 of file ParsedAttr.h.
References clang::detail::PropertyData::GetterId, and isDeclspecPropertyAttribute().
Referenced by clang::Sema::HandleMSProperty().
getPropertyDataSetter()
IdentifierInfo * clang::ParsedAttr::getPropertyDataSetter () const inline
Definition at line 466 of file ParsedAttr.h.
References isDeclspecPropertyAttribute(), and clang::detail::PropertyData::SetterId.
Referenced by clang::Sema::HandleMSProperty().
getReplacementExpr()
const Expr * clang::ParsedAttr::getReplacementExpr () const inline
Definition at line 431 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind(), and clang::detail::AvailabilityData::Replacement.
Referenced by handleAvailabilityAttr().
getSemanticSpelling()
unsigned ParsedAttr::getSemanticSpelling () const
If the parsed attribute has a semantic equivalent, and it would have a semantic Spelling enumeration (due to having semantically-distinct spelling variations), return the value of that semantic spelling.
If the parsed attribute does not have a semantic equivalent, or would not have a Spelling enumeration, the value UINT_MAX is returned.
Definition at line 245 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::spellingIndexToSemanticSpelling().
Referenced by handleMSInheritanceAttr(), handleOpenCLAccessAttr(), and handleStandardNoReturnAttr().
getStrictLoc()
SourceLocation clang::ParsedAttr::getStrictLoc () const inline
Definition at line 413 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind(), and clang::detail::AvailabilityData::StrictLoc.
Referenced by handleAvailabilityAttr().
getTypeArg()
const ParsedType & clang::ParsedAttr::getTypeArg () const inline
Definition at line 455 of file ParsedAttr.h.
Referenced by handleAlignedAttr(), handleIBOutletCollection(), handleLifetimeCategoryAttr(), handlePreferredName(), and handleVecTypeHint().
getUnavailableLoc()
SourceLocation clang::ParsedAttr::getUnavailableLoc () const inline
Definition at line 419 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind().
Referenced by handleAvailabilityAttr().
handleAttrWithDelayedArgs()
void ParsedAttr::handleAttrWithDelayedArgs (Sema & S, Decl * D) const
Definition at line 261 of file ParsedAttr.cpp.
References handleAttrWithDelayedArgs().
Referenced by handleAttrWithDelayedArgs(), and ProcessDeclAttribute().
hasCustomParsing()
bool ParsedAttr::hasCustomParsing () const
Definition at line 152 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::HasCustomParsing.
Referenced by checkCommonAttributeFeatures().
hasMacroIdentifier()
bool clang::ParsedAttr::hasMacroIdentifier () const inline
Returns true if this attribute was declared in a macro.
Definition at line 481 of file ParsedAttr.h.
Referenced by getMacroExpansionLoc().
hasParsedType()
bool clang::ParsedAttr::hasParsedType () const inline
Definition at line 337 of file ParsedAttr.h.
Referenced by getNumAttributeArgs(), getNumAttributeArgs(), handleAlignedAttr(), handleIBOutletCollection(), handleLifetimeCategoryAttr(), and handleVecTypeHint().
hasProcessingCache()
bool clang::ParsedAttr::hasProcessingCache () const inline
Definition at line 347 of file ParsedAttr.h.
Referenced by clang::Sema::CheckCallingConvAttr(), and getProcessingCache().
hasVariadicArg()
bool ParsedAttr::hasVariadicArg () const
Definition at line 249 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::OptArgs.
Referenced by checkCommonAttributeFeatures(), and MustDelayAttributeArguments().
isArgExpr()
bool clang::ParsedAttr::isArgExpr (unsigned Arg) const inline
Definition at line 379 of file ParsedAttr.h.
References getArg().
Referenced by handleCallbackAttr(), handleDeprecatedAttr(), handleDiagnoseAsBuiltinAttr(), handleM68kInterruptAttr(), and handleMSP430InterruptAttr().
isArgIdent()
bool clang::ParsedAttr::isArgIdent (unsigned Arg) const inline
Definition at line 387 of file ParsedAttr.h.
References getArg().
Referenced by clang::Sema::checkStringLiteralArgumentAttr(), handleAnnotateAttr(), HandleAnnotateTypeAttr(), handleArgumentWithTypeTagAttr(), handleArmBuiltinAliasAttr(), handleBlocksAttr(), handleBuiltinAliasAttr(), handleCallableWhenAttr(), handleCallbackAttr(), handleCFGuardAttr(), handleConsumableAttr(), handleCPUSpecificAttr(), handleEnumExtensibilityAttr(), handleFormatAttr(), handleHLSLResourceBindingAttr(), handleModeAttr(), handleObjCBridgeAttr(), handleObjCBridgeMutableAttr(), handleObjCBridgeRelatedAttr(), handleObjCMethodFamilyAttr(), handleOwnershipAttr(), handleParamTypestateAttr(), handleReturnTypestateAttr(), handleSetTypestateAttr(), handleSwiftAsyncAttr(), handleSwiftNewType(), handleTestTypestateAttr(), and handleTypeTagForDatatypeAttr().
isDeclspecPropertyAttribute()
bool clang::ParsedAttr::isDeclspecPropertyAttribute () const inline
Is this the Microsoft __declspec(property) attribute?
Definition at line 340 of file ParsedAttr.h.
Referenced by clang::ParsedAttributesView::getMSPropertyAttr(), getPropertyDataGetter(), and getPropertyDataSetter().
isInvalid()
bool clang::ParsedAttr::isInvalid () const inline
Definition at line 344 of file ParsedAttr.h.
Referenced by clang::Sema::CheckCallingConvAttr(), clang::Sema::CheckRegparmAttr(), ProcessDeclAttribute(), and ProcessStmtAttribute().
isKnownToGCC()
bool ParsedAttr::isKnownToGCC () const
Definition at line 199 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::IsKnownToGCC.
isPackExpansion()
bool clang::ParsedAttr::isPackExpansion () const inline
Definition at line 367 of file ParsedAttr.h.
References clang::SourceLocation::isValid().
Referenced by handleAlignedAttr().
isParamExpr()
bool ParsedAttr::isParamExpr (size_t N) const
Definition at line 257 of file ParsedAttr.cpp.
References getInfo(), clang::ParsedAttrInfo::isParamExpr(), and N.
Referenced by MustDelayAttributeArguments().
isPragmaClangAttribute()
bool clang::ParsedAttr::isPragmaClangAttribute () const inline
True if the attribute is specified using '#pragma clang attribute'.
Definition at line 363 of file ParsedAttr.h.
Referenced by handleAvailabilityAttr().
isStmtAttr()
bool ParsedAttr::isStmtAttr () const
Definition at line 193 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::IsStmt.
Referenced by ProcessDeclAttribute().
isSupportedByPragmaAttribute()
bool ParsedAttr::isSupportedByPragmaAttribute () const
Definition at line 201 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::IsSupportedByPragmaAttribute.
isTargetSpecificAttr()
bool ParsedAttr::isTargetSpecificAttr () const
Definition at line 187 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::IsTargetSpecific.
isTypeAttr()
bool ParsedAttr::isTypeAttr () const
Definition at line 191 of file ParsedAttr.cpp.
References getInfo(), and clang::ParsedAttrInfo::IsType.
Referenced by ProcessDeclAttribute().
isUsedAsTypeAttr()
bool clang::ParsedAttr::isUsedAsTypeAttr () const inline
Definition at line 359 of file ParsedAttr.h.
Referenced by handleAcquireHandleAttr(), handleXReturnsXRetainedAttr(), and ProcessDeclAttribute().
operator delete()
void clang::ParsedAttr::operator delete (void *) delete
operator=() [1/2]
ParsedAttr & clang::ParsedAttr::operator= (const ParsedAttr &) delete
operator=() [2/2]
ParsedAttr & clang::ParsedAttr::operator= (ParsedAttr &&) delete
setInvalid()
void clang::ParsedAttr::setInvalid (bool b = true) const inline
Definition at line 345 of file ParsedAttr.h.
References b.
Referenced by clang::Sema::CheckAttrNoArgs(), clang::Sema::CheckAttrTarget(), clang::Sema::CheckCallingConvAttr(), clang::Sema::CheckRegparmAttr(), handleInitPriorityAttr(), and handleMinVectorWidthAttr().
setIsPragmaClangAttribute()
void clang::ParsedAttr::setIsPragmaClangAttribute () inline
Definition at line 365 of file ParsedAttr.h.
setMacroIdentifier()
void clang::ParsedAttr::setMacroIdentifier (IdentifierInfo * MacroName, SourceLocation Loc) inline
Set the macro identifier info object that this parsed attribute was declared in if it was declared in a macro.
Also set the expansion location of the macro.
Definition at line 475 of file ParsedAttr.h.
setProcessingCache()
void clang::ParsedAttr::setProcessingCache (unsigned value) const inline
Definition at line 354 of file ParsedAttr.h.
Referenced by clang::Sema::CheckCallingConvAttr().
setUsedAsTypeAttr()
void clang::ParsedAttr::setUsedAsTypeAttr (bool Used = true) inline
Definition at line 360 of file ParsedAttr.h.
References Used.
Referenced by createSimpleAttr().
slidesFromDeclToDeclSpecLegacyBehavior()
bool ParsedAttr::slidesFromDeclToDeclSpecLegacyBehavior () const
Returns whether a [[]] attribute, if specified ahead of a declaration, should be applied to the decl-specifier-seq instead (i.e.
whether it "slides" to the decl-specifier-seq).
By the standard, attributes specified before the declaration always appertain to the declaration, but historically we have allowed some of these attributes to slide to the decl-specifier-seq, so we need to keep supporting this behavior.
This may only be called if isStandardAttributeSyntax() returns true.
Definition at line 205 of file ParsedAttr.cpp.
References clang::AttributeCommonInfo::getParsedKind(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::AttributeCommonInfo::isStandardAttributeSyntax().
Referenced by ProcessDeclAttribute().
Friends And Related Symbol Documentation
AttributeFactory
friend class AttributeFactory friend
Definition at line 201 of file ParsedAttr.h.
AttributePool
friend class AttributePool friend
Definition at line 202 of file ParsedAttr.h.
The documentation for this class was generated from the following files:
include/clang/Sema/ParsedAttr.h
lib/Sema/ParsedAttr.cpp