clang: clang::interp::CodePtr Class Reference
clang::interp::CodePtr Class Reference final
Pointer into the code segment.
#include "/root/llvm-project/clang/lib/AST/Interp/Source.h"
Public Member Functions
CodePtr ()
CodePtr & operator+= (int32_t Offset)
int32_t operator- (const CodePtr &RHS) const
CodePtr operator- (size_t RHS) const
bool operator!= (const CodePtr &RHS) const
operator bool () const
template<typename T >
std::enable_if_t<!std::is_pointer< T >::value, T > read ()
Reads data and advances the pointer.
Friends
class Function
Detailed Description
Pointer into the code segment.
Definition at line 26 of file Source.h.
Constructor & Destructor Documentation
CodePtr()
clang::interp::CodePtr::CodePtr () inline
Definition at line 28 of file Source.h.
Referenced by operator-().
Member Function Documentation
operator bool()
clang::interp::CodePtr::operator bool () const inline
Definition at line 47 of file Source.h.
operator!=()
bool clang::interp::CodePtr::operator!= (const CodePtr & RHS) const inline
Definition at line 45 of file Source.h.
operator+=()
CodePtr & clang::interp::CodePtr::operator+= (int32_t Offset) inline
Definition at line 30 of file Source.h.
References Offset.
operator-() [1/2]
int32_t clang::interp::CodePtr::operator- (const CodePtr & RHS) const inline
Definition at line 35 of file Source.h.
operator-() [2/2]
CodePtr clang::interp::CodePtr::operator- (size_t RHS) const inline
Definition at line 40 of file Source.h.
References CodePtr().
read()
template<typename T > std::enable_if_t<!std::is_pointer< T >::value, T > clang::interp::CodePtr::read () inline
Reads data and advances the pointer.
Definition at line 50 of file Source.h.
References clang::interp::align(), and clang::interp::aligned().
Referenced by clang::interp::Interpret(), clang::interp::ReadArg(), and ReadArg().
Friends And Related Symbol Documentation
Function
friend class Function friend
Definition at line 59 of file Source.h.
The documentation for this class was generated from the following file:
lib/AST/Interp/Source.h