clang: clang::driver::tools::MinGW::Linker Class Reference
clang::driver::tools::MinGW::Linker Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/MinGW.h"
Public Member Functions
Linker (const ToolChain &TC)
bool hasIntegratedCPP () const override
bool isLinkJob () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 37 of file MinGW.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::MinGW::Linker::Linker (const ToolChain & TC) inline
Definition at line 39 of file MinGW.h.
Member Function Documentation
ConstructJob()
void tools::MinGW::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 96 of file MinGW.cpp.
References clang::driver::ToolChain::AddCXXStdlibLibArgs(), clang::driver::ToolChain::addFastMathRuntimeIfAvailable(), clang::driver::ToolChain::AddFilePathLibArgs(), clang::driver::tools::addFortranRuntimeLibraryPath(), clang::driver::tools::addFortranRuntimeLibs(), clang::driver::tools::AddLinkerInputs(), clang::driver::ToolChain::addProfileRTLibs(), clang::driver::ResponseFileSupport::AtFileUTF8(), clang::C, clang::driver::Driver::Diag(), clang::driver::ToolChain::FT_Shared, clang::driver::ToolChain::getArch(), clang::driver::ToolChain::getCompilerRTArgString(), clang::driver::ToolChain::getCompilerRTPath(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getEffectiveTriple(), clang::driver::InputInfo::getFilename(), clang::driver::ToolChain::GetFilePath(), clang::driver::ToolChain::getLibraryPaths(), clang::driver::ToolChain::GetLinkerPath(), clang::driver::Driver::getOpenMPRuntime(), clang::driver::ToolChain::getSanitizerArgs(), clang::driver::ToolChain::getVFS(), clang::driver::SanitizerArgs::needsAsanRt(), clang::driver::Driver::OMPRT_GOMP, clang::driver::Driver::OMPRT_IOMP5, clang::driver::Driver::OMPRT_OMP, clang::driver::Driver::OMPRT_Unknown, clang::driver::ToolChain::ShouldLinkCXXStdlib(), and clang::driver::Driver::SysRoot.
hasIntegratedCPP()
bool clang::driver::tools::MinGW::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 41 of file MinGW.h.
isLinkJob()
bool clang::driver::tools::MinGW::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 42 of file MinGW.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/MinGW.h
lib/Driver/ToolChains/MinGW.cpp