clang: clang::NamedDecl Class Reference
clang::NamedDecl Class Reference
This represents a decl that may have a name.
#include "clang/AST/Decl.h"
Public Types
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Member Functions
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &OS, const PrintingPolicy &Policy) const
Pretty-print the unqualified name of this declaration.
void printName (raw_ostream &OS) const
Calls printName() with the ASTContext printing policy from the decl.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getQualifiedNameAsString () const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
std::optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
virtual SourceRange getSourceRange () const LLVM_READONLY
Source range that this declaration covers.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isDiscardedInGlobalModuleFragment () const
FIXME: Implement discarding declarations actually in global module fragment.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
virtual Decl * getCanonicalDecl ()
Retrieves the "canonical" declaration of the given declaration.
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Static Public Member Functions
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Protected Member Functions
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
virtual Decl * getNextRedeclarationImpl ()
Returns the next redeclaration or itself if this is the only decl.
virtual Decl * getPreviousDeclImpl ()
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
virtual Decl * getMostRecentDeclImpl ()
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
ASTMutationListener * getASTMutationListener () const
Additional Inherited Members
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Detailed Description
This represents a decl that may have a name.
Many decls have names such as ObjCMethodDecl, but not @class, etc.
Note that not every NamedDecl is actually named (e.g., a struct might be anonymous), and not every name is an identifier.
Definition at line 247 of file Decl.h.
Member Enumeration Documentation
ExplicitVisibilityKind
enum clang::NamedDecl::ExplicitVisibilityKind
Kinds of explicit visibility.
Enumerator
VisibilityForType
Do an LV computation for, ultimately, a type.
Visibility may be restricted by type visibility settings and the visibility of template arguments.
VisibilityForValue
Do an LV computation for, ultimately, a non-type declaration.
Visibility may be restricted by value visibility settings and the visibility of template arguments.
Definition at line 424 of file Decl.h.
Constructor & Destructor Documentation
NamedDecl()
clang::NamedDecl::NamedDecl (Kind DK, DeclContext * DC, SourceLocation L, DeclarationName N) inline protected
Definition at line 259 of file Decl.h.
Member Function Documentation
classof()
static bool clang::NamedDecl::classof (const Decl * D) inline static
Definition at line 480 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::NamedDecl::classofKind (Kind K) inline static
Definition at line 481 of file Decl.h.
Referenced by classof(), and clang::tooling::stdlib::Recognizer::operator()().
declarationReplaces()
bool NamedDecl::declarationReplaces (NamedDecl * OldD, bool IsKnownNewer = true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
A declaration will replace another declaration if, for example, it is a redeclaration of the same variable or function, but not if it is a declaration of a different kind (function vs. class) or an overloaded function.
Parameters
IsKnownNewer true if this declaration is known to be newer than OldD (for instance, if this declaration is newly-created).
Definition at line 1811 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::Decl::getCanonicalDecl(), clang::ASTContext::getCanonicalNestedNameSpecifier(), clang::Decl::getDeclContext(), getDeclName(), clang::Decl::getKind(), clang::DeclContext::getRedeclContext(), clang::Decl::isCanonicalDecl(), clang::Decl::isFromASTFile(), isRedeclarable(), and clang::Decl::redecls().
Referenced by clang::StoredDeclsList::addOrReplaceDecl(), and clang::Sema::PushOnScopeChains().
getDeclName()
DeclarationName clang::NamedDecl::getDeclName () const inline
Get the actual, stored name of the declaration, which may be a special name.
Note that generally in diagnostics, the non-null NamedDecl* itself should be sent into the diagnostic instead of using the result of getDeclName().
A DeclarationName in a diagnostic will just be streamed to the output, which will directly result in a call to DeclarationName::print.
A NamedDecl* in a diagnostic will also ultimately result in a call to DeclarationName::print, but with two customisation points along the way (getNameForDiagnostic and printName). These are used to print the template arguments if any, and to provide a user-friendly name for some entities (such as unnamed variables and anonymous records).
Definition at line 313 of file Decl.h.
Referenced by clang::Sema::ActOnConceptDefinition(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFields(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnLabelStmt(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnNameClassifiedAsNonType(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnPopScope(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartCategoryImplementation(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::TypoCorrection::addCorrectionDecl(), clang::IdentifierResolver::AddDecl(), clang::ODRHash::AddDecl(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddKnownFunctionAttributesForReplaceableGlobalAllocationFunction(), clang::Sema::AddOverriddenMethods(), AddTypedNameChunk(), applyObjCTypeArgs(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCaptureInit(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildIvarRefExpr(), buildLambdaCaptureFixit(), clang::Sema::BuildUsingDeclaration(), clang::Sema::BuildUsingEnumDeclaration(), clang::Sema::BuildVariableInstantiation(), captureInLambda(), clang::Sema::CheckAddressOfOperand(), checkARCPropertyImpl(), CheckArityMismatch(), checkAtomicPropertyMismatch(), clang::Sema::CheckBaseSpecifier(), clang::Sema::CheckCallReturnType(), clang::Sema::CheckCompletedCXXClass(), CheckCompleteParameterTypesForMangler(), clang::Sema::CheckConceptRedefinition(), clang::Sema::checkCUDATargetOverload(), CheckDeclInExpr(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckIfOverriddenFunctionIsMarkedFinal(), clang::Sema::CheckImplicitSpecialMemberDeclaration(), clang::Sema::checkInitializerLifetime(), clang::Sema::CheckLiteralOperatorDeclaration(), CheckMethodOverrideParam(), CheckMethodOverrideReturn(), checkNewAttributesAfterDef(), clang::Sema::CheckNontrivialField(), CheckOperatorNewDeclaration(), CheckOperatorNewDeleteDeclarationScope(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverrideControl(), clang::Sema::CheckOverridingFunctionAttributes(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckShadow(), checkTypeParamListConsistency(), clang::Sema::CheckUsingShadowDecl(), clang::DeclarationName::compare(), CompleteNonViableCandidate(), clang::Sema::CompleteVarTemplateSpecializationDecl(), clang::ASTReader::completeVisibleDeclsMap(), clang::CodeGen::CodeGenTypes::ComputeRecordLayout(), clang::ASTImporterLookupTable::contains(), clang::Sema::ConvertArgumentsForCall(), clang::DeclRefExpr::Create(), clang::UsingEnumDecl::Create(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreatePropertyDecl(), clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString(), declarationReplaces(), clang::Sema::DeduceVariableDeclarationType(), clang::Sema::deduceVarTypeFromInitializer(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseAbsenceOfOverrideControl(), clang::Sema::DiagnoseAbstractType(), DiagnoseArityMismatch(), clang::Sema::DiagnoseAutoDeductionFailure(), DiagnoseBadAccess(), DiagnoseBadDeduction(), DiagnoseCStringFormatDirectiveInCFAPI(), DiagnoseDirectIsaAccess(), DiagnoseInvalidRedeclaration(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), DiagnoseObjCImplementedDeprecations(), clang::Sema::DiagnoseOwningPropertyGetterSynthesis(), clang::Sema::DiagnoseSentinelCalls(), diagnoseSubMismatchMethodParameters(), clang::Sema::diagnoseUnavailableAlignedAllocation(), DiagnoseUnimplementedAccessor(), DiagnoseUninitializedConstRefUse(), DiagnoseUninitializedUse(), clang::Sema::DiagnoseUninstantiableTemplate(), clang::Sema::DiagnoseUnusedButSetDecl(), clang::Sema::DiagnoseUseOfDecl(), diagnoseVarDeclTypeMismatch(), DiagnoseVariableSizedIvars(), DiagUninitUse(), DoEmitAvailabilityWarning(), clang::TextNodeDumper::dumpName(), clang::ento::FunctionCodeRegion::dumpToStream(), EmitDiagForCXXThrowInNonThrowingFunc(), clang::Sema::FinalizeVarWithDestructor(), clang::Sema::FindAllocationFunctions(), clang::ASTReader::FindExternalVisibleDeclsByName(), clang::Sema::FindHiddenVirtualMethods(), clang::Sema::findInheritingConstructor(), clang::Sema::FindInstantiatedDecl(), clang::ASTContext::forEachMultiversionedFunctionVersion(), clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), clang::CXXDeductionGuideDecl::getDeducedTemplate(), clang::Sema::getDefaultedFunctionKind(), clang::FunctionDecl::getLiteralIdentifier(), clang::MemberExpr::getMemberNameInfo(), clang::InitializedEntity::getName(), clang::ASTContext::getNameForTemplate(), clang::FunctionDecl::getNameInfo(), clang::UnresolvedUsingTypenameDecl::getNameInfo(), clang::UnresolvedUsingValueDecl::getNameInfo(), clang::UsingDecl::getNameInfo(), clang::FunctionDecl::getOverloadedOperator(), getQualifiedNameStart(), clang::ObjCMethodDecl::getSelector(), clang::Sema::getSelfAssignmentClassMemberCandidate(), clang::DeclaratorDecl::getSourceRange(), clang::TemplateTypeParmDecl::getSourceRange(), clang::Sema::HandleDeclarator(), clang::Sema::HandlePropertyInClassExtension(), hasConflictingOverload(), hasDefaultGetterName(), hasDefaultSetterName(), clang::TagDecl::hasNameForLinkage(), clang::dataflow::hasOptionalClassName(), hasWrittenStorageAttribute(), HelperToDiagnoseMismatchedMethodsInGlobalPool(), clang::Sema::HideUsingShadowDecl(), implicitObjectParamIsLifetimeBound(), clang::ASTNodeImporter::ImportDeclParts(), clang::ASTNodeImporter::ImportDeclParts(), clang::ASTNodeImporter::ImportDefinition(), clang::IdentifierResolver::iterator::incrementSlowCase(), clang::ASTReader::InitializeSema(), InjectAnonymousStructOrUnionMembers(), clang::IdentifierResolver::InsertDeclAfter(), clang::Sema::InstantiateMemInitializers(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::OverloadCandidateSet::OperatorRewriteInfo::isAcceptableCandidate(), clang::FieldDecl::isAnonymousStructOrUnion(), clang::LookupResult::isAvailableForLookup(), clang::dataflow::isCheckLikeMethod(), isCXXSharedPtrDtor(), isEnableIf(), clang::RecordDecl::isInjectedClassName(), isInstantiationOf(), clang::CXXMethodDecl::isLambdaStaticInvoker(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), clang::OverloadCandidateSet::OperatorRewriteInfo::isRewrittenOperator(), clang::ASTContext::isSameEntity(), clang::CXXMethodDecl::isStatic(), clang::ento::smartptr::isStdSmartPtr(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), clang::dataflow::isTopLevelNamespaceWithName(), clang::FieldDecl::isUnnamedBitfield(), clang::CXXMethodDecl::isUsualDeallocationFunction(), isVariableCapturable(), clang::Sema::LookupIvarInObjCMethod(), LookupMemberExpr(), MatchesFriend(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::MergeFunctionDecl(), clang::Sema::MergeTypedefNameDecl(), clang::Sema::MergeVarDecl(), MightInstantiateTo(), MightInstantiateTo(), clang::serialization::needsAnonymousDeclarationNumber(), clang::Sema::NoteAllFoundTemplates(), clang::Sema::ParseObjCSelectorExpression(), clang::DeclarationName::print(), clang::TagDecl::printName(), printNestedNameSpecifier(), printQualifiedName(), clang::Sema::PushOnScopeChains(), clang::TreeTransform< Derived >::RebuildObjCIvarRefExpr(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::IdentifierResolver::RemoveDecl(), ReportOverrides(), clang::Sema::SetDeclDefaulted(), clang::ASTContext::setInstantiatedFromUnnamedFieldDecl(), shouldBeHidden(), ShouldDiagnoseUnusedDecl(), clang::Sema::shouldSkipAnonEnumBody(), shouldSkipNamelessDecl(), clang::threadSafety::til::Project::slotName(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::Sema::SubstParmVarDecl(), SuggestInitializationFixit(), TryTypoCorrectionForCall(), clang::ASTImporterLookupTable::updateForced(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::ASTDeclReader::VisitFieldDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::ASTNodeImporter::VisitImplicitParamDecl(), clang::JSONNodeDumper::VisitMemberExpr(), clang::ASTDeclWriter::VisitNamedDecl(), clang::JSONNodeDumper::VisitNamedDecl(), clang::ASTNodeImporter::VisitNonTypeTemplateParmDecl(), clang::ASTNodeImporter::VisitObjCImplementationDecl(), clang::ASTDeclWriter::VisitObjCIvarDecl(), clang::ASTNodeImporter::VisitObjCPropertyImplDecl(), clang::ASTNodeImporter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::ASTNodeImporter::VisitRecordDecl(), clang::ASTNodeImporter::VisitTemplateTemplateParmDecl(), clang::ASTDeclWriter::VisitTypedefDecl(), clang::TextNodeDumper::VisitUnresolvedUsingTypenameDecl(), clang::ASTDeclReader::VisitUnresolvedUsingValueDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingValueDecl(), clang::TextNodeDumper::VisitUnresolvedUsingValueDecl(), clang::ASTDeclReader::VisitUsingDecl(), clang::ASTDeclWriter::VisitUsingDecl(), clang::TextNodeDumper::VisitUsingDecl(), clang::ASTDeclWriter::VisitVarDecl(), and clang::Sema::WarnExactTypedMethods().
getExplicitVisibility()
std::optional< Visibility > NamedDecl::getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
Definition at line 1265 of file Decl.cpp.
References getExplicitVisibilityAux().
Referenced by clang::Sema::AddPushedVisibilityAttribute(), and getExplicitVisibility().
getFormalLinkage()
Linkage NamedDecl::getFormalLinkage () const
Get the linkage from a semantic point of view.
Entities in anonymous namespaces are external (in c++98).
Definition at line 1160 of file Decl.cpp.
References clang::ExternalLinkage, clang::Decl::getCanonicalDecl(), clang::getFormalLinkage(), getLinkageInternal(), clang::InternalLinkage, isExportedFromModuleInterfaceUnit(), isInModulePurview(), and clang::ModuleLinkage.
Referenced by clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddOverloadCandidate(), clang::Sema::areMultiversionVariantFunctionsCompatible(), CheckExplicitInstantiation(), checkExportedDecl(), clang::Sema::CheckRedeclarationExported(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::Sema::checkVarDeclRedefinition(), diagnoseUseOfInternalDeclInInlineFunction(), getMultiversionLinkage(), and hasLinkage().
getIdentifier()
IdentifierInfo * clang::NamedDecl::getIdentifier () const inline
Get the identifier that names this declaration, if there is one.
This will return NULL if this declaration has no name (e.g., for an unnamed class) or if the name is a special name (C++ constructor, Objective-C selector, etc.).
Definition at line 268 of file Decl.h.
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnProperty(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartClassInterface(), clang::Sema::ActOnTag(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTypedefNameDecl(), clang::Sema::ActOnVariableDeclarator(), addFunctionPointerConversion(), clang::Sema::AddKnownFunctionAttributes(), clang::CodeGen::CodeGenTypes::addRecordTypeName(), clang::Sema::AddSectionMSAllocText(), AddTemplateParameterChunks(), clang::ento::AnyFunctionCall::argumentsMayEscape(), clang::Sema::BuildBlockForLambdaConversion(), buildCapture(), clang::Sema::BuildCaptureInit(), clang::ento::RetainSummaryManager::canEval(), checkForLiteralCreation(), checkFormatStringExpr(), clang::Sema::CheckImplementationIvars(), clang::Sema::CheckParameterPacksForExpansion(), CheckPropertyAgainstProtocol(), CheckProtocolMethodDefs(), CollectImmediateProperties(), createOverloadsForFixedParams(), clang::Sema::DeclApplyPragmaWeak(), clang::Sema::DefaultSynthesizeProperties(), describeClass(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ento::CXXLifetimeExtendedObjectRegion::dumpToStream(), clang::ento::NonParamVarRegion::dumpToStream(), clang::ento::ParamVarRegion::dumpToStream(), emitOutlinedFunctionPrologue(), findBackingIvar(), findCapturingExpr(), findProtocolsWithExplicitImpls(), clang::StructuralEquivalenceContext::findUntaggedStructOrUnionIndex(), fixParamWithSpan(), clang::ento::coreFoundation::followsCreateRule(), clang::TypoCorrectionConsumer::FoundDecl(), getAbsoluteValueFunctionKind(), clang::QualType::getBaseTypeIdentifier(), clang::BodyFarm::getBody(), clang::ento::CheckerContext::getCalleeIdentifier(), clang::ento::CheckerContext::getCalleeName(), getCalleeName(), clang::ObjCCategoryImplDecl::getCategoryDecl(), clang::Sema::getConstructorName(), clang::ObjCPropertyDecl::getDefaultSynthIvarName(), clang::TagDecl::getDefinition(), clang::DesignatedInitExpr::Designator::getFieldName(), clang::OffsetOfNode::getFieldName(), clang::ObjCImplementationDecl::getIdentifier(), getMangledNameImpl(), clang::FunctionDecl::getMemoryFunctionKind(), clang::LabelStmt::getName(), getName(), clang::Sema::GetNameFromUnqualifiedId(), getNestedNameSpecifierIdentifiers(), clang::Sema::getObjCInterfaceDecl(), clang::getPatternCompletionComment(), clang::Sema::getTemplateArgumentBindingsText(), getUnionInitName(), hasWrittenStorageAttribute(), InjectAnonymousStructOrUnionMembers(), InNamespace(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::NamespaceDecl::isAnonymousNamespace(), IsCFError(), isCFStringType(), clang::ObjCCategoryDecl::IsClassExtension(), clang::ento::CheckerContext::isCLibraryFunction(), clang::Sema::isCurrentClassName(), clang::Sema::isCurrentClassNameTypo(), IsDeclSourceLocationCurrent(), clang::TagTypeLoc::isDefinition(), clang::ento::iterator::isEmplaceCall(), clang::ento::iterator::isEraseAfterCall(), clang::ento::iterator::isEraseCall(), clang::ento::iterator::isInsertCall(), clang::FunctionDecl::isMSVCRTEntryPoint(), isNamed(), clang::Type::isNothrowT(), isNSStringType(), isNSStringType(), clang::Sema::isOpenMPCapturedDecl(), isReferenceCountingPointerDestructor(), isReserved(), IsStdFunction(), clang::Sema::isStdInitializerList(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), clang::NSAPI::isSubclassOfNSClass(), IsTemplateDeclCommonStructurallyEquivalent(), clang::ObjCInterfaceDecl::lookupInheritedClass(), clang::ObjCProtocolDecl::lookupProtocolNamed(), clang::MangleContext::mangleName(), clang::Sema::MergeTypedefNameDecl(), clang::Sema::MergeVarDecl(), clang::Sema::ProcessPragmaWeak(), clang::Sema::ProcessPropertyDecl(), PushProtocolProperties(), clang::TreeTransform< Derived >::RebuildObjCExceptionDecl(), ReferencesAnonymousEntity(), rewriteBuiltinFunctionDecl(), rewriteToNSEnumDecl(), rewriteToNSMacroDecl(), clang::ObjCImplDecl::setClassInterface(), clang::Sema::setTagNameForLinkagePurposes(), shouldTrackFirstArgument(), ShouldWarnAboutMissingPrototype(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter(), clang::ASTNodeImporter::VisitNamespaceAliasDecl(), clang::ASTNodeImporter::VisitObjCCategoryImplDecl(), clang::ASTDeclReader::VisitObjCIvarDecl(), and clang::ASTNodeImporter::VisitTemplateTypeParmDecl().
getLinkageAndVisibility()
LinkageInfo NamedDecl::getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
Definition at line 1181 of file Decl.cpp.
References clang::LinkageComputer::getDeclLinkageAndVisibility().
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfTemplateParamObject(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), getVisibility(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::CodeGen::CodeGenModule::setGlobalVisibility(), setLinkageForGV(), and clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
getLinkageInternal()
Linkage NamedDecl::getLinkageInternal () const
Determine what kind of linkage this entity has.
This is not the linkage as defined by the standard or the codegen notion of linkage. It is just an implementation detail that is used to compute those.
Definition at line 1150 of file Decl.cpp.
References clang::LVComputationKind::forLinkageOnly(), clang::LinkageInfo::getLinkage(), and clang::LinkageComputer::getLVForDecl().
Referenced by getFormalLinkage(), hasExternalFormalLinkage(), clang::ASTNodeImporter::hasSameVisibilityContextAndLinkage(), isExternallyVisible(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitVarDecl().
getMostRecentDecl() [1/2]
NamedDecl * clang::NamedDecl::getMostRecentDecl () inline
Definition at line 471 of file Decl.h.
References clang::cast(), and getMostRecentDecl().
Referenced by clang::Sema::ArgumentDependentLookup(), clang::Sema::CheckTemplateArgumentList(), compareDeclarations(), diagnoseMissingArgument(), DoEmitAvailabilityWarning(), getExplicitVisibilityAux(), getMostRecentDecl(), getMostRecentDecl(), clang::ValueDecl::isWeak(), ShouldRemoveFromUnused(), and clang::ASTDeclWriter::VisitNamespaceDecl().
getMostRecentDecl() [2/2]
const NamedDecl * clang::NamedDecl::getMostRecentDecl () const inline
Definition at line 474 of file Decl.h.
References getMostRecentDecl().
getName()
StringRef clang::NamedDecl::getName () const inline
Get the name of identifier for this declaration as a StringRef.
This requires that the declaration have a name and that it be a simple identifier.
Definition at line 274 of file Decl.h.
References getIdentifier(), and clang::IdentifierInfo::getName().
Referenced by clang::Sema::ActOnFunctionDeclarator(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::ActOnOpenMPUseDevicePtrClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnSuperScopeSpecifier(), AddObjCKeyValueCompletions(), clang::Sema::AddSectionMSAllocText(), buildLambdaCaptureFixit(), CaptureMethods(), clang::Sema::CheckAddressOfOperand(), clang::threadSafety::BeforeSet::checkBeforeAfter(), clang::Sema::CheckMSVCRTEntryPoint(), clang::PredefinedExpr::ComputeName(), clang::CodeGen::CodeGenModule::createUnnamedGlobalFrom(), clang::Sema::DefaultSynthesizeProperties(), DiagnoseBadDeduction(), clang::Sema::DiagnoseMisalignedMembers(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseUseOfDecl(), clang::ento::CXXBaseObjectRegion::dumpToStream(), clang::ento::CXXDerivedObjectRegion::dumpToStream(), emitAddrOfFieldStorage(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockDeclRefVariable(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), EmitDirectCallee(), clang::CodeGen::CGHLSLRuntime::emitEntryFunction(), clang::CodeGen::CGDebugInfo::EmitExternalVariable(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), clang::CodeGen::CGDebugInfo::EmitLabel(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), clang::CodeGen::CGDebugInfo::EmitNamespaceAlias(), clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper(), clang::Sema::EndOpenMPDSABlock(), clang::ento::LikelyFalsePositiveSuppressionBRVisitor::finalizeVisitor(), fixVarDeclWithSpan(), generateUniqueName(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::BodyFarm::getBody(), clang::ento::ModelInjector::getBody(), clang::ento::ModelInjector::getBody(), UPCPreIncrementGadget::getFixits(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnum(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnumConstant(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForFunction(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCInterface(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcAllocShared(), clang::GCCAsmStmt::getLabelName(), getObjCFStringFormattingFamily(), clang::ObjCInterfaceDecl::getObjCRuntimeNameAsString(), clang::ObjCProtocolDecl::getObjCRuntimeNameAsString(), clang::comments::TParamCommandComment::getParamName(), clang::CodeCompletionTUInfo::getParentName(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::extractapi::TypedefUnderlyingTypeResolver::getSymbolReferenceForType(), clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::getTypedefName(), clang::Sema::HandleExprPropertyRefExpr(), hasDefaultGetterName(), hasDefaultSetterName(), clang::dataflow::hasOptionalClassName(), clang::Sema::inferGslPointerAttribute(), clang::dataflow::isCheckLikeMethod(), IsClangAttr(), IsClangDecl(), IsClangStmt(), IsClangType(), isDefaultStdCall(), isDefinedInClangModule(), clang::CXXRecordDecl::isInterfaceLike(), clang::ento::iterator::isIterator(), clang::CXXMethodDecl::isLambdaStaticInvoker(), clang::FunctionDecl::isMSVCRTEntryPoint(), isSelfDecl(), IsSmallVector(), clang::ento::smartptr::isStdSmartPtr(), IsStdString(), IsStdVector(), clang::dataflow::isTopLevelNamespaceWithName(), clang::MangleContext::mangleObjCMethodName(), maybeAdjustInterfaceForSubscriptingCheck(), mergeDeclAttribute(), clang::operator<<(), clang::NestedNameSpecifier::print(), print_elem(), print_initializer(), clang::Sema::PrintInstantiationStack(), clang::APValue::printPretty(), clang::ento::FieldRegion::printPretty(), clang::ento::FieldRegion::printPrettyAsExpr(), clang::ento::NonParamVarRegion::printPrettyAsExpr(), clang::ento::ObjCIvarRegion::printPrettyAsExpr(), clang::ento::ParamVarRegion::printPrettyAsExpr(), ReplaceWithClasstype(), shouldTrackFirstArgument(), clang::threadSafety::til::Project::slotName(), clang::JSONNodeDumper::VisitAddrLabelExpr(), clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::VisitObjCCategoryDecl(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getNameAsString()
std::string clang::NamedDecl::getNameAsString () const inline
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
Creating this name requires expensive string manipulation, so it should be called only when performance doesn't matter. For simple declarations, getNameAsCString() should suffice.
Definition at line 290 of file Decl.h.
Referenced by AddTypedNameChunk(), clang::consumed::ConsumedStmtVisitor::checkCallability(), clang::Sema::CheckObjCBridgeRelatedConversions(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), createTemplateSignatureString(), findMetaClassAlloc(), clang::dataflow::AggregateStorageLocation::getChild(), clang::Sema::getDestructorName(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), getNoteTag(), clang::ASTContext::getObjCEncodingForPropertyDecl(), getStaticDeclName(), IsTemplateDeclCommonStructurallyEquivalent(), clang::randstruct::randomizeStructureLayout(), rewriteToObjCProperty(), clang::ento::SValExplainer::VisitFieldRegion(), clang::JSONNodeDumper::VisitMemberExpr(), clang::JSONNodeDumper::VisitNamedDecl(), clang::ento::SValExplainer::VisitObjCIvarRegion(), and clang::JSONNodeDumper::VisitUsingDecl().
getNameForDiagnostic()
void NamedDecl::getNameForDiagnostic (raw_ostream & OS, const PrintingPolicy & Policy, bool Qualified) const virtual
Appends a human-readable name for this declaration into the given stream.
This is the method invoked by Sema when displaying a NamedDecl in a diagnostic. It does not necessarily produce the same result as printName(); for example, class template specializations are printed with their template arguments.
Reimplemented in clang::ClassTemplateSpecializationDecl, clang::FunctionDecl, and clang::VarTemplateSpecializationDecl.
Definition at line 1787 of file Decl.cpp.
References printName(), printQualifiedName(), and clang::Qualified.
Referenced by annotateConsumedSummaryMismatch(), clang::FormatASTNodeDiagnosticArgument(), generateDiagnosticsForCallLike(), clang::ClassTemplateSpecializationDecl::getNameForDiagnostic(), clang::FunctionDecl::getNameForDiagnostic(), clang::VarTemplateSpecializationDecl::getNameForDiagnostic(), and clang::Sema::InstantiateClass().
getObjCFStringFormattingFamily()
ObjCStringFormatFamily NamedDecl::getObjCFStringFormattingFamily () const
Definition at line 1137 of file Decl.cpp.
References getName(), clang::SFF_CFString, and clang::SFF_None.
Referenced by DiagnoseCStringFormatDirectiveInCFAPI().
getQualifiedNameAsString()
std::string NamedDecl::getQualifiedNameAsString () const
Definition at line 1644 of file Decl.cpp.
References clang::Decl::getASTContext(), and printQualifiedName().
Referenced by DiagnosedUnqualifiedCallsToStdFunctions(), DiagnoseTwoPhaseLookup(), clang::ento::NonLoc::dumpToStream(), generateDiagnosticsForCallLike(), clang::interp::Function::getName(), clang::diff::SyntaxTree::Impl::getRelativeName(), IsMicrosoftUsingDeclarationAccessBug(), clang::RecordDecl::mayInsertExtraPadding(), print_elem(), clang::ProgramPoint::printJson(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject(), clang::ento::SValExplainer::VisitCXXBaseObjectRegion(), clang::ento::SValExplainer::VisitNonParamVarRegion(), and clang::ento::SValExplainer::VisitParamVarRegion().
getUnderlyingDecl() [1/2]
NamedDecl * clang::NamedDecl::getUnderlyingDecl () inline
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
Definition at line 457 of file Decl.h.
References clang::Decl::getKind().
Referenced by clang::Sema::ActOnNameClassifiedAsNonType(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::AddFunctionCandidates(), clang::Sema::AddNonMemberOperatorCandidates(), clang::Sema::BuildCXXNestedNameSpecifier(), canHideTag(), CheckAnonMemberRedeclaration(), clang::Sema::CheckClassTemplate(), clang::Sema::CheckCompletedCXXClass(), clang::Sema::CheckDependentFunctionTemplateSpecialization(), checkExportedDecl(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::ClassifyName(), CXXRecordMembersNamed(), clang::Sema::DiagnoseAmbiguousLookup(), clang::Sema::DiagnoseEmptyLookup(), diagnoseInstanceReference(), diagnoseNoViableConversion(), clang::CodeGen::CGDebugInfo::EmitUsingShadowDecl(), clang::Sema::FindAssociatedClassesAndNamespaces(), clang::Sema::getAsTemplateNameDecl(), clang::getConstructorInfo(), GetConversionType(), getDeclShowContexts(), clang::getDeclUsageType(), clang::Sema::getDestructorName(), clang::ASTContext::getOverloadedTemplateName(), clang::Sema::getTypeName(), getUnderlyingDecl(), clang::Sema::isAcceptableNestedNameSpecifier(), isPreferredLookupResult(), clang::Sema::LookupLiteralOperator(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupSpecialMember(), clang::Sema::LookupTemplateName(), noteOverloads(), clang::Sema::PerformContextualImplicitConversion(), recordConversion(), resolveAllocationOverload(), ResolveConstructorOverload(), clang::LookupResult::resolveKind(), ResolveOverloadForDeduction(), clang::FunctionCallFilterCCC::ValidateCandidate(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUsingShadowDecl().
getUnderlyingDecl() [2/2]
const NamedDecl * clang::NamedDecl::getUnderlyingDecl () const inline
Definition at line 467 of file Decl.h.
References getUnderlyingDecl().
getVisibility()
Visibility clang::NamedDecl::getVisibility () const inline
Determines the visibility of this entity.
Definition at line 416 of file Decl.h.
References getLinkageAndVisibility(), and clang::LinkageInfo::getVisibility().
Referenced by mergeDeclAttribute().
hasExternalFormalLinkage()
bool clang::NamedDecl::hasExternalFormalLinkage () const inline
True if this decl has external linkage.
Definition at line 401 of file Decl.h.
References getLinkageInternal(), and clang::isExternalFormalLinkage().
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::Decl::getOwningModuleForLinkage(), clang::Sema::isExternalWithNoLinkageType(), clang::Sema::MergeFunctionDecl(), clang::Sema::MergeVarDecl(), and clang::MangleContext::shouldMangleDeclName().
hasLinkage()
bool NamedDecl::hasLinkage () const
Determine whether this declaration has linkage.
Definition at line 1887 of file Decl.cpp.
References getFormalLinkage(), and clang::NoLinkage.
Referenced by clang::Sema::BuildVariableInstantiation(), clang::Sema::CheckCompleteVariableDeclaration(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::Sema::CheckVariableDeclarationType(), isOutOfScopePreviousDeclaration(), and clang::Sema::MergeVarDecl().
hasLinkageBeenComputed()
bool clang::NamedDecl::hasLinkageBeenComputed () const inline
True if something has required us to compute the linkage of this declaration.
Language features which can retroactively change linkage (like a typedef name for linkage purposes) may need to consider this, but hopefully only in transitory ways during parsing.
Definition at line 451 of file Decl.h.
References clang::Decl::hasCachedLinkage().
Referenced by clang::Sema::setTagNameForLinkagePurposes().
isCXXClassMember()
bool clang::NamedDecl::isCXXClassMember () const inline
Determine whether this declaration is a C++ class member.
Definition at line 369 of file Decl.h.
References clang::Decl::getDeclContext(), clang::DeclContext::getRedeclContext(), and clang::DeclContext::isRecord().
Referenced by clang::Sema::ActOnTag(), checkDLLAttributeRedeclaration(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::DiagnoseEmptyLookup(), isCXXInstanceMember(), clang::Sema::isQualifiedMemberAccess(), clang::Sema::MergeCXXFunctionDecl(), and clang::Sema::MergeFunctionDecl().
isCXXInstanceMember()
bool NamedDecl::isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
Definition at line 1905 of file Decl.cpp.
References clang::cast(), clang::Decl::getAsFunction(), and isCXXClassMember().
Referenced by clang::Sema::BuildMemberReferenceExpr(), and clang::Sema::CheckCallingConvAttr().
isExternallyDeclarable()
bool clang::NamedDecl::isExternallyDeclarable () const inline
Determine whether this declaration can be redeclared in a different translation unit.
Definition at line 411 of file Decl.h.
References clang::Decl::getOwningModuleForLinkage(), and isExternallyVisible().
Referenced by clang::LookupResult::isHiddenDeclarationVisible().
isExternallyVisible()
bool clang::NamedDecl::isExternallyVisible () const inline
Definition at line 405 of file Decl.h.
References getLinkageInternal(), and clang::isExternallyVisible().
Referenced by clang::Sema::ActOnFunctionDeclarator(), basicGVALinkageForFunction(), basicGVALinkageForVariable(), checkAttributesAfterMerging(), clang::Sema::CheckCompleteVariableDeclaration(), checkUndefinedButUsed(), computeKeyFunction(), clang::Sema::FinalizeDeclaration(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), getStaticDeclName(), clang::CodeGen::CodeGenModule::getVTableLinkage(), handleCmseNSEntryAttr(), clang::ento::CheckerContext::isCLibraryFunction(), isDefinedInClangModule(), isExternallyDeclarable(), MarkVarDeclODRUsed(), needsTypeIdentifier(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), clang::CodeGen::CodeGenModule::setDLLImportDLLExport(), ShouldRemoveFromUnused(), and ShouldWarnAboutMissingPrototype().
isLinkageValid()
bool NamedDecl::isLinkageValid () const
True if the computed linkage is valid.
Used for consistency checking. Should always return true.
Definition at line 1089 of file Decl.cpp.
References clang::LinkageComputer::computeLVForDecl(), clang::LVComputationKind::forLinkageOnly(), clang::Decl::getCachedLinkage(), clang::LinkageInfo::getLinkage(), and clang::Decl::hasCachedLinkage().
Referenced by clang::Sema::DeduceVariableDeclarationType(), and clang::TagDecl::setTypedefNameForAnonDecl().
isModulePrivate()
bool clang::Decl::isModulePrivate () const inline
Whether this declaration was marked as being private to the module in which it was defined.
Definition at line 625 of file DeclBase.h.
Referenced by clang::Sema::hasAcceptableDefinition(), clang::ASTDeclWriter::VisitEnumDecl(), clang::TextNodeDumper::VisitEnumDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::JSONNodeDumper::VisitFieldDecl(), clang::TextNodeDumper::VisitFieldDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitObjCIvarDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::TextNodeDumper::VisitRecordDecl(), clang::ASTDeclWriter::VisitTypedefDecl(), clang::TextNodeDumper::VisitTypedefDecl(), clang::ASTDeclWriter::VisitVarDecl(), clang::JSONNodeDumper::VisitVarDecl(), and clang::TextNodeDumper::VisitVarDecl().
isReserved()
ReservedIdentifierStatus NamedDecl::isReserved (const LangOptions & LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Definition at line 1100 of file Decl.cpp.
References clang::Decl::getDeclContext(), getIdentifier(), clang::DeclContext::getRedeclContext(), clang::VarDecl::isExternC(), clang::IdentifierInfo::isReserved(), clang::isReservedAtGlobalScope(), clang::isReservedInAllContexts(), clang::Decl::isTemplateParameter(), clang::DeclContext::isTranslationUnit(), clang::NotReserved, and clang::StartsWithUnderscoreAndIsExternC.
Referenced by clang::Sema::ActOnLabelStmt(), shouldIgnoreDueToReservedName(), and clang::Sema::warnOnReservedIdentifier().
printName() [1/2]
void NamedDecl::printName (raw_ostream & OS) const
Calls printName() with the ASTContext printing policy from the decl.
Definition at line 1640 of file Decl.cpp.
References clang::Decl::getASTContext(), and printName().
printName() [2/2]
void NamedDecl::printName (raw_ostream & OS, const PrintingPolicy & Policy) const virtual
Pretty-print the unqualified name of this declaration.
Can be overloaded by derived classes to provide a more user-friendly name when appropriate.
Reimplemented in clang::DecompositionDecl, and clang::TagDecl.
Definition at line 1636 of file Decl.cpp.
References clang::DeclarationName::print().
Referenced by getNameForDiagnostic(), clang::operator<<(), clang::Sema::PrintInstantiationStack(), printName(), printQualifiedName(), and clang::threadSafety::til::Project::slotName().
printNestedNameSpecifier() [1/2]
void NamedDecl::printNestedNameSpecifier (raw_ostream & OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
E.g. when printQualifiedName(D) prints "A::B::i", this function prints "A::B::".
Definition at line 1678 of file Decl.cpp.
References clang::Decl::getASTContext(), and printNestedNameSpecifier().
Referenced by printNestedNameSpecifier(), and printQualifiedName().
printNestedNameSpecifier() [2/2]
void NamedDecl::printNestedNameSpecifier (raw_ostream & OS, const PrintingPolicy & Policy) const
Definition at line 1682 of file Decl.cpp.
References clang::TemplateArgumentList::asArray(), clang::Decl::getDeclContext(), getDeclName(), clang::DeclContext::getParent(), clang::DeclContext::isFunctionOrMethod(), clang::DeclContext::isInlineNamespace(), clang::FunctionProtoType::isVariadic(), and P.
printQualifiedName() [1/2]
void NamedDecl::printQualifiedName (raw_ostream & OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
If the declaration is not a member of context which can be named (record, namespace), it will return the same result as printName().
Creating this name is expensive, so it should be called only when performance doesn't matter.
Definition at line 1651 of file Decl.cpp.
References clang::Decl::getASTContext(), and printQualifiedName().
Referenced by clang::CodeGen::CodeGenTypes::addRecordTypeName(), clang::Expr::EvaluateAsInitializer(), getNameForDiagnostic(), getQualifiedNameAsString(), clang::TemplateArgument::print(), printQualifiedName(), and clang::CodeGen::SanitizerMetadata::reportGlobal().
printQualifiedName() [2/2]
void NamedDecl::printQualifiedName (raw_ostream & OS, const PrintingPolicy & Policy) const
Definition at line 1655 of file Decl.cpp.
References clang::Decl::getDeclContext(), getDeclName(), isFunctionOrMethod(), P, printName(), and printNestedNameSpecifier().
setDeclName()
void clang::NamedDecl::setDeclName (DeclarationName N) inline
Set the name of this declaration.
Definition at line 316 of file Decl.h.
References N.
Referenced by clang::ASTDeclReader::VisitNamedDecl().
setModulePrivate()
void clang::Decl::setModulePrivate () inline
Specify that this declaration was marked as being private to the module in which it was defined.
Definition at line 664 of file DeclBase.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnTag(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckClassTemplate(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), and clang::Sema::ParseTypedefDecl().
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp