clang: clang::ento::CXXInheritedConstructorCall Class Reference
clang::ento::CXXInheritedConstructorCall Class Reference
Represents a call to a C++ inherited constructor.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
const CXXInheritedCtorInitExpr * getOriginExpr () const override
Returns the expression whose value will be the result of this call.
const CXXConstructorDecl * getDecl () const override
Returns the declaration of the function or method that will be called.
const StackFrameContext * getInheritingStackFrame () const
Obtain the stack frame of the inheriting constructor.
const CXXConstructExpr * getInheritingConstructor () const
Obtain the CXXConstructExpr for the sub-class that inherited the current constructor (possibly indirectly).
unsigned getNumArgs () const override
Returns the number of arguments (explicit and implicit).
const Expr * getArgExpr (unsigned Index) const override
Returns the expression associated with a given argument.
SVal getArgSVal (unsigned Index) const override
Returns the value of a given argument at the time of the call.
Kind getKind () const override
Returns the kind of call this is.
StringRef getKindAsString () const override
Public Member Functions inherited from clang::ento::AnyCXXConstructorCall
SVal getCXXThisVal () const
Returns the value of the implicit 'this' object.
Public Member Functions inherited from clang::ento::AnyFunctionCall
RuntimeDefinition getRuntimeDefinition () const override
Returns the definition of the function or method that will be called.
bool argumentsMayEscape () const override
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const override
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
ArrayRef< ParmVarDecl * > parameters () const override
Return call's formal parameters.
Public Member Functions inherited from clang::ento::CallEvent
CallEvent & operator= (const CallEvent &)=delete
virtual ~CallEvent ()=default
bool isForeign () const
void setForeign (bool B) const
const ProgramStateRef & getState () const
The state in which the call is being evaluated.
const LocationContext * getLocationContext () const
The context in which the call is being evaluated.
const CFGBlock::ConstCFGElementRef & getCFGElementRef () const
bool isInSystemHeader () const
Returns true if the callee is known to be from a system header.
virtual SourceRange getSourceRange () const
Returns a source range for the entire call, suitable for outputting in diagnostics.
virtual SourceRange getArgSourceRange (unsigned Index) const
Returns the source range for errors associated with this argument.
QualType getResultType () const
Returns the result type, adjusted for references.
SVal getReturnValue () const
Returns the return value of the call.
bool hasNonNullArgumentsWithType (bool(*Condition)(QualType)) const
Returns true if the type of any of the non-null arguments satisfies the condition.
bool hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
bool hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
bool isGlobalCFunction (StringRef SpecificName=StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
const IdentifierInfo * getCalleeIdentifier () const
Returns the name of the callee, if its name is a simple identifier.
ProgramPoint getProgramPoint (bool IsPreVisit=false, const ProgramPointTag *Tag=nullptr) const
Returns an appropriate ProgramPoint for this call.
ProgramStateRef invalidateRegions (unsigned BlockCount, ProgramStateRef Orig=nullptr) const
Returns a new state with all argument regions invalidated.
template<typename T >
CallEventRef< T > cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
CallEventRef cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
AnalysisDeclContext * getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
const StackFrameContext * getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
const ParamVarRegion * getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
bool isArgumentConstructedDirectly (unsigned Index) const
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
virtual std::optional< unsigned > getAdjustedParameterIndex (unsigned ASTArgumentIndex) const
Some calls have parameter numbering mismatched from argument numbering.
virtual unsigned getASTArgumentIndex (unsigned CallArgumentIndex) const
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
const ConstructionContext * getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
std::optional< SVal > getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
param_type_iterator param_type_begin () const
Returns an iterator over the types of the call's formal parameters.
param_type_iterator param_type_end () const
void dump (raw_ostream &Out) const
void dump () const
Static Public Member Functions
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::AnyCXXConstructorCall
static bool classof (const CallEvent *Call)
Static Public Member Functions inherited from clang::ento::AnyFunctionCall
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::CallEvent
static bool isCallStmt (const Stmt *S)
Returns true if this is a statement is a function or method call of some kind.
static QualType getDeclaredResultType (const Decl *D)
Returns the result type of a function or method declaration.
static bool isVariadic (const Decl *D)
Returns true if the given decl is known to be variadic.
Protected Member Functions
CXXInheritedConstructorCall (const CXXInheritedCtorInitExpr *CE, const MemRegion *Target, ProgramStateRef St, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
CXXInheritedConstructorCall (const CXXInheritedConstructorCall &Other)=default
void cloneTo (void *Dest) const override
Copies this CallEvent, with vtable intact, into a new block of memory.
Protected Member Functions inherited from clang::ento::AnyCXXConstructorCall
AnyCXXConstructorCall (const Expr *E, const MemRegion *Target, ProgramStateRef St, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
void getExtraInvalidatedValues (ValueList &Values, RegionAndSymbolInvalidationTraits *ETraits) const override
Used to specify non-argument regions that will be invalidated as a result of this call.
void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const override
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Protected Member Functions inherited from clang::ento::AnyFunctionCall
AnyFunctionCall (const Expr *E, ProgramStateRef St, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
AnyFunctionCall (const Decl *D, ProgramStateRef St, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
AnyFunctionCall (const AnyFunctionCall &Other)=default
Protected Member Functions inherited from clang::ento::CallEvent
CallEvent (const Expr *E, ProgramStateRef state, const LocationContext *lctx, CFGBlock::ConstCFGElementRef ElemRef)
CallEvent (const Decl *D, ProgramStateRef state, const LocationContext *lctx, CFGBlock::ConstCFGElementRef ElemRef)
CallEvent (const CallEvent &Original)
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
Friends
class CallEventManager
Additional Inherited Members
Public Types inherited from clang::ento::CallEvent
using Kind = CallEventKind
using FrameBindingTy = std::pair<SVal, SVal>
using BindingsTy = SmallVectorImpl<FrameBindingTy>
using param_type_iterator
Protected Types inherited from clang::ento::CallEvent
using ValueList = SmallVectorImpl<SVal>
Protected Attributes inherited from clang::ento::CallEvent
const void * Data
SourceLocation Location
Detailed Description
Represents a call to a C++ inherited constructor.
Example: class T : public S { using S::S; }; T(1); E.g., in:
struct X { X *p = this; ~X() {} }; struct A { A(X x) : b(x.p == &x) {} bool b; }; struct B : A { using A::A; }; B b = X{};
... b.b is initialized to true.
Definition at line 969 of file CallEvent.h.
Constructor & Destructor Documentation
CXXInheritedConstructorCall() [1/2]
clang::ento::CXXInheritedConstructorCall::CXXInheritedConstructorCall (const CXXInheritedCtorInitExpr * CE, const MemRegion * Target, ProgramStateRef St, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline protected
Definition at line 973 of file CallEvent.h.
Referenced by cloneTo().
CXXInheritedConstructorCall() [2/2]
clang::ento::CXXInheritedConstructorCall::CXXInheritedConstructorCall (const CXXInheritedConstructorCall & Other) protected default
Member Function Documentation
classof()
static bool clang::ento::CXXInheritedConstructorCall::classof (const CallEvent * CA) inline static
Definition at line 1025 of file CallEvent.h.
References clang::ento::CE_CXXInheritedConstructor, and clang::ento::CallEvent::getKind().
cloneTo()
void clang::ento::CXXInheritedConstructorCall::cloneTo (void * Dest) const inline override protected virtual
Copies this CallEvent, with vtable intact, into a new block of memory.
Implements clang::ento::CallEvent.
Definition at line 982 of file CallEvent.h.
References CXXInheritedConstructorCall().
getArgExpr()
const Expr * clang::ento::CXXInheritedConstructorCall::getArgExpr (unsigned Index) const inline override virtual
Returns the expression associated with a given argument.
May be null if this expression does not appear in the source.
Reimplemented from clang::ento::CallEvent.
Definition at line 1010 of file CallEvent.h.
References clang::CXXConstructExpr::getArg(), and getInheritingConstructor().
Referenced by getArgSVal().
getArgSVal()
SVal clang::ento::CXXInheritedConstructorCall::getArgSVal (unsigned Index) const inline override virtual
Returns the value of a given argument at the time of the call.
Reimplemented from clang::ento::CallEvent.
Definition at line 1014 of file CallEvent.h.
References getArgExpr(), getInheritingStackFrame(), and clang::ento::CallEvent::getState().
getDecl()
const CXXConstructorDecl * clang::ento::CXXInheritedConstructorCall::getDecl () const inline override virtual
Returns the declaration of the function or method that will be called.
May be null.
Reimplemented from clang::ento::AnyFunctionCall.
Definition at line 991 of file CallEvent.h.
References clang::CXXInheritedCtorInitExpr::getConstructor(), and getOriginExpr().
getInheritingConstructor()
const CXXConstructExpr * clang::ento::CXXInheritedConstructorCall::getInheritingConstructor () const inline
Obtain the CXXConstructExpr for the sub-class that inherited the current constructor (possibly indirectly).
It's the statement that contains argument expressions.
Definition at line 1002 of file CallEvent.h.
References clang::cast(), and getInheritingStackFrame().
Referenced by getArgExpr(), and getNumArgs().
getInheritingStackFrame()
const StackFrameContext * CXXInheritedConstructorCall::getInheritingStackFrame () const
Obtain the stack frame of the inheriting constructor.
Argument expressions can be found on the call site of that stack frame.
Definition at line 925 of file CallEvent.cpp.
References clang::StackFrameContext::getCallSite(), clang::ento::CallEvent::getLocationContext(), clang::LocationContext::getParent(), and clang::LocationContext::getStackFrame().
Referenced by getArgSVal(), and getInheritingConstructor().
getKind()
Kind clang::ento::CXXInheritedConstructorCall::getKind () const inline override virtual
Returns the kind of call this is.
Implements clang::ento::CallEvent.
Definition at line 1020 of file CallEvent.h.
References clang::ento::CE_CXXInheritedConstructor.
getKindAsString()
StringRef clang::ento::CXXInheritedConstructorCall::getKindAsString () const inline override virtual
Implements clang::ento::CallEvent.
Definition at line 1021 of file CallEvent.h.
getNumArgs()
unsigned clang::ento::CXXInheritedConstructorCall::getNumArgs () const inline override virtual
Returns the number of arguments (explicit and implicit).
Note that this may be greater than the number of parameters in the callee's declaration, and that it may include arguments not written in the source.
Implements clang::ento::CallEvent.
Definition at line 1006 of file CallEvent.h.
References getInheritingConstructor(), and clang::CXXConstructExpr::getNumArgs().
getOriginExpr()
const CXXInheritedCtorInitExpr * clang::ento::CXXInheritedConstructorCall::getOriginExpr () const inline override virtual
Returns the expression whose value will be the result of this call.
May be null.
Reimplemented from clang::ento::CallEvent.
Definition at line 987 of file CallEvent.h.
References clang::cast(), and clang::ento::CallEvent::getOriginExpr().
Referenced by getDecl().
Friends And Related Symbol Documentation
CallEventManager
friend class CallEventManager friend
Definition at line 970 of file CallEvent.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp