clang: clang::RopePieceBTree Class Reference
clang::RopePieceBTree Class Reference
#include "clang/Rewrite/Core/RewriteRope.h"
Public Types
using iterator = RopePieceBTreeIterator
Public Member Functions
RopePieceBTree ()
RopePieceBTree (const RopePieceBTree &RHS)
RopePieceBTree & operator= (const RopePieceBTree &)=delete
~RopePieceBTree ()
iterator begin () const
iterator end () const
unsigned size () const
unsigned empty () const
void clear ()
void insert (unsigned Offset, const RopePiece &R)
void erase (unsigned Offset, unsigned NumBytes)
Detailed Description
Definition at line 141 of file RewriteRope.h.
Member Typedef Documentation
iterator
using clang::RopePieceBTree::iterator = RopePieceBTreeIterator
Definition at line 150 of file RewriteRope.h.
Constructor & Destructor Documentation
RopePieceBTree() [1/2]
RopePieceBTree::RopePieceBTree ()
Definition at line 721 of file RewriteRope.cpp.
RopePieceBTree() [2/2]
RopePieceBTree::RopePieceBTree (const RopePieceBTree & RHS)
Definition at line 725 of file RewriteRope.cpp.
References empty().
~RopePieceBTree()
RopePieceBTree::~RopePieceBTree ()
Definition at line 730 of file RewriteRope.cpp.
References getRoot().
Member Function Documentation
begin()
iterator clang::RopePieceBTree::begin () const inline
Definition at line 152 of file RewriteRope.h.
Referenced by clang::RewriteRope::begin().
clear()
void RopePieceBTree::clear ()
Definition at line 738 of file RewriteRope.cpp.
References getRoot().
Referenced by clang::RewriteRope::clear().
empty()
unsigned clang::RopePieceBTree::empty () const inline
Definition at line 155 of file RewriteRope.h.
References size().
Referenced by RopePieceBTree().
end()
iterator clang::RopePieceBTree::end () const inline
Definition at line 153 of file RewriteRope.h.
Referenced by clang::RewriteRope::end().
erase()
void RopePieceBTree::erase (unsigned Offset, unsigned NumBytes)
Definition at line 757 of file RewriteRope.cpp.
References getRoot(), and Offset.
Referenced by clang::RewriteRope::erase().
insert()
void RopePieceBTree::insert (unsigned Offset, const RopePiece & R)
Definition at line 747 of file RewriteRope.cpp.
References getRoot(), and Offset.
Referenced by clang::RewriteRope::assign(), and clang::RewriteRope::insert().
operator=()
RopePieceBTree & clang::RopePieceBTree::operator= (const RopePieceBTree &) delete
size()
unsigned RopePieceBTree::size () const
Definition at line 734 of file RewriteRope.cpp.
References getRoot().
Referenced by empty(), and clang::RewriteRope::size().
The documentation for this class was generated from the following files:
include/clang/Rewrite/Core/RewriteRope.h
lib/Rewrite/RewriteRope.cpp