clang: clang::Type Class Reference
clang::Type Class Reference
The base class of the type hierarchy.
#include "clang/AST/Type.h"
Classes
class ArrayTypeBitfields
class AttributedTypeBitfields
class AutoTypeBitfields
class BuiltinTypeBitfields
class ConstantArrayTypeBitfields
class DependentTemplateSpecializationTypeBitfields
class ElaboratedTypeBitfields
class FunctionTypeBitfields
FunctionTypeBitfields store various bits belonging to FunctionProtoType.
class ObjCObjectTypeBitfields
class PackExpansionTypeBitfields
class ReferenceTypeBitfields
class SubstTemplateTypeParmPackTypeBitfields
class SubstTemplateTypeParmTypeBitfields
class TemplateSpecializationTypeBitfields
class TypedefBitfields
class TypeOfBitfields
class TypeWithKeywordBitfields
class UsingBitfields
class VectorTypeBitfields
Public Types
enum TypeClass
enum ScalarTypeKind {
STK_CPointer , STK_BlockPointer , STK_ObjCObjectPointer , STK_MemberPointer ,
STK_Bool , STK_Integral , STK_Floating , STK_IntegralComplex ,
STK_FloatingComplex , STK_FixedPoint
}
Public Member Functions
Type (const Type &)=delete
Type (Type &&)=delete
Type & operator= (const Type &)=delete
Type & operator= (Type &&)=delete
TypeClass getTypeClass () const
bool isFromAST () const
Whether this type comes from an AST file.
bool containsUnexpandedParameterPack () const
Whether this type is or contains an unexpanded parameter pack, used to support C++0x variadic templates.
bool isCanonicalUnqualified () const
Determines if this type would be canonical if it had no further qualification.
QualType getLocallyUnqualifiedSingleStepDesugaredType () const
Pull a single level of sugar off of this locally-unqualified type.
bool isSizelessType () const
As an extension, we classify types as one of "sized" or "sizeless"; every type is one or the other.
bool isSizelessBuiltinType () const
bool isSVESizelessBuiltinType () const
Returns true for SVE scalable vector types.
bool isRVVSizelessBuiltinType () const
Returns true for RVV scalable vector types.
bool isWebAssemblyExternrefType () const
Check if this is a WebAssembly Externref Type.
bool isWebAssemblyTableType () const
Returns true if this is a WebAssembly table type: either an array of reference types, or a pointer to a reference type (which can only be created by array to pointer decay).
bool isVLSTBuiltinType () const
Determines if this is a sizeless type supported by the 'arm_sve_vector_bits' type attribute, which can be applied to a single SVE vector or predicate, excluding tuple types such as svint32x4_t.
QualType getSveEltType (const ASTContext &Ctx) const
Returns the representative type for the element of an SVE builtin type.
bool isRVVVLSBuiltinType () const
Determines if this is a sizeless type supported by the 'riscv_rvv_vector_bits' type attribute, which can be applied to a single RVV vector or mask.
QualType getRVVEltType (const ASTContext &Ctx) const
Returns the representative type for the element of an RVV builtin type.
bool isIncompleteType (NamedDecl **Def=nullptr) const
Types are partitioned into 3 broad categories (C99 6.2.5p1): object types, function types, and incomplete types.
bool isIncompleteOrObjectType () const
Return true if this is an incomplete or object type, in other words, not a function type.
bool isObjectType () const
Determine whether this type is an object type.
bool isLiteralType (const ASTContext &Ctx) const
Return true if this is a literal type (C++11 [basic.types]p10)
bool isStructuralType () const
Determine if this type is a structural type, per C++20 [temp.param]p7.
bool isStandardLayoutType () const
Test if this type is a standard-layout type.
bool isBuiltinType () const
Helper methods to distinguish type categories.
bool isSpecificBuiltinType (unsigned K) const
Test for a particular builtin type.
bool isPlaceholderType () const
Test for a type which does not represent an actual type-system type but is instead used as a placeholder for various convenient purposes within Clang.
const BuiltinType * getAsPlaceholderType () const
bool isSpecificPlaceholderType (unsigned K) const
Test for a specific placeholder type.
bool isNonOverloadPlaceholderType () const
Test for a placeholder type other than Overload; see BuiltinType::isNonOverloadPlaceholderType.
bool isIntegerType () const
isIntegerType() does not include complex integers (a GCC extension).
bool isEnumeralType () const
bool isScopedEnumeralType () const
Determine whether this type is a scoped enumeration type.
bool isBooleanType () const
bool isCharType () const
bool isWideCharType () const
bool isChar8Type () const
bool isChar16Type () const
bool isChar32Type () const
bool isAnyCharacterType () const
Determine whether this type is any of the built-in character types.
bool isIntegralType (const ASTContext &Ctx) const
Determine whether this type is an integral type.
bool isIntegralOrEnumerationType () const
Determine whether this type is an integral or enumeration type.
bool isIntegralOrUnscopedEnumerationType () const
Determine whether this type is an integral or unscoped enumeration type.
bool isUnscopedEnumerationType () const
bool isRealFloatingType () const
Floating point categories.
bool isComplexType () const
isComplexType() does not include complex integers (a GCC extension).
bool isAnyComplexType () const
bool isFloatingType () const
bool isHalfType () const
bool isFloat16Type () const
bool isBFloat16Type () const
bool isFloat128Type () const
bool isIbm128Type () const
bool isRealType () const
bool isArithmeticType () const
bool isVoidType () const
bool isScalarType () const
bool isAggregateType () const
Determines whether the type is a C++ aggregate type or C aggregate or union type.
bool isFundamentalType () const
Tests whether the type is categorized as a fundamental type.
bool isCompoundType () const
Tests whether the type is categorized as a compound type.
bool isFunctionType () const
bool isFunctionNoProtoType () const
bool isFunctionProtoType () const
bool isPointerType () const
bool isAnyPointerType () const
bool isBlockPointerType () const
bool isVoidPointerType () const
bool isReferenceType () const
bool isLValueReferenceType () const
bool isRValueReferenceType () const
bool isObjectPointerType () const
bool isFunctionPointerType () const
bool isFunctionReferenceType () const
bool isMemberPointerType () const
bool isMemberFunctionPointerType () const
bool isMemberDataPointerType () const
bool isArrayType () const
bool isConstantArrayType () const
bool isIncompleteArrayType () const
bool isVariableArrayType () const
bool isDependentSizedArrayType () const
bool isRecordType () const
bool isClassType () const
bool isStructureType () const
bool isObjCBoxableRecordType () const
bool isInterfaceType () const
bool isStructureOrClassType () const
bool isUnionType () const
bool isComplexIntegerType () const
bool isVectorType () const
bool isExtVectorType () const
bool isExtVectorBoolType () const
bool isMatrixType () const
bool isConstantMatrixType () const
bool isDependentAddressSpaceType () const
bool isObjCObjectPointerType () const
bool isObjCRetainableType () const
bool isObjCLifetimeType () const
Returns true if objects of this type have lifetime semantics under ARC.
bool isObjCIndirectLifetimeType () const
bool isObjCNSObjectType () const
bool isObjCIndependentClassType () const
bool isObjCObjectType () const
bool isObjCQualifiedInterfaceType () const
bool isObjCQualifiedIdType () const
bool isObjCQualifiedClassType () const
bool isObjCObjectOrInterfaceType () const
bool isObjCIdType () const
bool isDecltypeType () const
bool isObjCInertUnsafeUnretainedType () const
Was this type written with the special inert-in-ARC __unsafe_unretained qualifier?
bool isObjCIdOrObjectKindOfType (const ASTContext &ctx, const ObjCObjectType *&bound) const
Whether the type is Objective-C 'id' or a __kindof type of an object type, e.g., __kindof NSView * or __kindof id <NSCopying>.
bool isObjCClassType () const
bool isObjCClassOrClassKindOfType () const
Whether the type is Objective-C 'Class' or a __kindof type of an Class type, e.g., __kindof Class <NSCopying>.
bool isBlockCompatibleObjCPointerType (ASTContext &ctx) const
bool isObjCSelType () const
bool isObjCBuiltinType () const
bool isObjCARCBridgableType () const
Determine whether the given type T is a "bridgable" Objective-C type, which is either an Objective-C object pointer type or an.
bool isCARCBridgableType () const
Determine whether the given type T is a "bridgeable" C type.
bool isTemplateTypeParmType () const
bool isNullPtrType () const
bool isNothrowT () const
bool isAlignValT () const
bool isStdByteType () const
bool isAtomicType () const
bool isUndeducedAutoType () const
bool isTypedefNameType () const
Determines whether this type is written as a typedef-name.
bool isImageType () const
bool isSamplerT () const
bool isEventT () const
bool isClkEventT () const
bool isQueueT () const
bool isReserveIDT () const
bool isOCLIntelSubgroupAVCType () const
bool isOCLExtOpaqueType () const
bool isPipeType () const
bool isBitIntType () const
bool isOpenCLSpecificType () const
bool isObjCARCImplicitlyUnretainedType () const
Determines if this type, which must satisfy isObjCLifetimeType(), is implicitly __unsafe_unretained rather than implicitly __strong.
bool isCUDADeviceBuiltinSurfaceType () const
Check if the type is the CUDA device builtin surface type.
bool isCUDADeviceBuiltinTextureType () const
Check if the type is the CUDA device builtin texture type.
bool isRVVType (unsigned ElementCount) const
bool isRVVType () const
bool isRVVType (unsigned Bitwidth, bool IsFloat) const
Qualifiers::ObjCLifetime getObjCARCImplicitLifetime () const
Return the implicit lifetime for this type, which must not be dependent.
ScalarTypeKind getScalarTypeKind () const
Given that this is a scalar type, classify it.
TypeDependence getDependence () const
bool containsErrors () const
Whether this type is an error type.
bool isDependentType () const
Whether this type is a dependent type, meaning that its definition somehow depends on a template parameter (C++ [temp.dep.type]).
bool isInstantiationDependentType () const
Determine whether this type is an instantiation-dependent type, meaning that the type involves a template parameter (even if the definition does not actually depend on the type substituted for that template parameter).
bool isUndeducedType () const
Determine whether this type is an undeduced type, meaning that it somehow involves a C++11 'auto' type or similar which has not yet been deduced.
bool isVariablyModifiedType () const
Whether this type is a variably-modified type (C99 6.7.5).
bool hasSizedVLAType () const
Whether this type involves a variable-length array type with a definite size.
bool hasUnnamedOrLocalType () const
Whether this type is or contains a local or unnamed type.
bool isOverloadableType () const
Determines whether this is a type for which one can define an overloaded operator.
bool isElaboratedTypeSpecifier () const
Determine wither this type is a C++ elaborated-type-specifier.
bool canDecayToPointerType () const
Determines whether this type can decay to a pointer type.
bool hasPointerRepresentation () const
Whether this type is represented natively as a pointer.
bool hasObjCPointerRepresentation () const
Whether this type can represent an objective pointer type for the purpose of GC'ability.
bool hasIntegerRepresentation () const
Determine whether this type has an integer representation of some sort, e.g., it is an integer type or a vector.
bool hasSignedIntegerRepresentation () const
Determine whether this type has an signed integer representation of some sort, e.g., it is an signed integer type or a vector.
bool hasUnsignedIntegerRepresentation () const
Determine whether this type has an unsigned integer representation of some sort, e.g., it is an unsigned integer type or a vector.
bool hasFloatingRepresentation () const
Determine whether this type has a floating-point representation of some sort, e.g., it is a floating-point type or a vector thereof.
const RecordType * getAsStructureType () const
const RecordType * getAsUnionType () const
NOTE: getAs*ArrayType are methods on ASTContext.
const ComplexType * getAsComplexIntegerType () const
const ObjCObjectType * getAsObjCInterfaceType () const
const ObjCObjectPointerType * getAsObjCInterfacePointerType () const
const ObjCObjectPointerType * getAsObjCQualifiedIdType () const
const ObjCObjectPointerType * getAsObjCQualifiedClassType () const
const ObjCObjectType * getAsObjCQualifiedInterfaceType () const
CXXRecordDecl * getAsCXXRecordDecl () const
Retrieves the CXXRecordDecl that this type refers to, either because the type is a RecordType or because it is the injected-class-name type of a class template or class template partial specialization.
RecordDecl * getAsRecordDecl () const
Retrieves the RecordDecl this type refers to.
TagDecl * getAsTagDecl () const
Retrieves the TagDecl that this type refers to, either because the type is a TagType or because it is the injected-class-name type of a class template or class template partial specialization.
const CXXRecordDecl * getPointeeCXXRecordDecl () const
If this is a pointer or reference to a RecordType, return the CXXRecordDecl that the type refers to.
DeducedType * getContainedDeducedType () const
Get the DeducedType whose type will be deduced for a variable with an initializer of this type.
AutoType * getContainedAutoType () const
Get the AutoType whose type will be deduced for a variable with an initializer of this type.
bool hasAutoForTrailingReturnType () const
Determine whether this type was written with a leading 'auto' corresponding to a trailing return type (possibly for a nested function type within a pointer to function type or similar).
template<typename T >
const T * getAs () const
Member-template getAs<specific type>'.
template<typename T >
const T * getAsAdjusted () const
Member-template getAsAdjusted<specific type>.
const ArrayType * getAsArrayTypeUnsafe () const
A variant of getAs<> for array types which silently discards qualifiers from the outermost type.
template<typename T >
const T * castAs () const
Member-template castAs<specific type>.
const ArrayType * castAsArrayTypeUnsafe () const
A variant of castAs<> for array type which silently discards qualifiers from the outermost type.
bool hasAttr (attr::Kind AK) const
Determine whether this type had the specified attribute applied to it (looking through top-level type sugar).
const Type * getBaseElementTypeUnsafe () const
Get the base element type of this type, potentially discarding type qualifiers.
const Type * getArrayElementTypeNoTypeQual () const
If this is an array type, return the element type of the array, potentially with type qualifiers missing.
const Type * getPointeeOrArrayElementType () const
If this is a pointer type, return the pointee type.
QualType getPointeeType () const
If this is a pointer, ObjC object pointer, or block pointer, this returns the respective pointee.
const Type * getUnqualifiedDesugaredType () const
Return the specified type with any "sugar" removed from the type, removing any typedefs, typeofs, etc., as well as any qualifiers.
bool isSignedIntegerType () const
Return true if this is an integer type that is signed, according to C99 6.2.5p4 [char, signed char, short, int, long..], or an enum decl which has a signed representation.
bool isUnsignedIntegerType () const
Return true if this is an integer type that is unsigned, according to C99 6.2.5p6 [which returns true for _Bool], or an enum decl which has an unsigned representation.
bool isSignedIntegerOrEnumerationType () const
Determines whether this is an integer type that is signed or an enumeration types whose underlying type is a signed integer type.
bool isUnsignedIntegerOrEnumerationType () const
Determines whether this is an integer type that is unsigned or an enumeration types whose underlying type is a unsigned integer type.
bool isFixedPointType () const
Return true if this is a fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
bool isFixedPointOrIntegerType () const
Return true if this is a fixed point or integer type.
bool isSaturatedFixedPointType () const
Return true if this is a saturated fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
bool isUnsaturatedFixedPointType () const
Return true if this is a saturated fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
bool isSignedFixedPointType () const
Return true if this is a fixed point type that is signed according to ISO/IEC JTC1 SC22 WG14 N1169.
bool isUnsignedFixedPointType () const
Return true if this is a fixed point type that is unsigned according to ISO/IEC JTC1 SC22 WG14 N1169.
bool isConstantSizeType () const
Return true if this is not a variable sized type, according to the rules of C99 6.7.5p3.
bool isSpecifierType () const
Returns true if this type can be represented by some set of type specifiers.
Linkage getLinkage () const
Determine the linkage of this type.
Visibility getVisibility () const
Determine the visibility of this type.
bool isVisibilityExplicit () const
Return true if the visibility was explicitly set is the code.
LinkageInfo getLinkageAndVisibility () const
Determine the linkage and visibility of this type.
bool isLinkageValid () const
True if the computed linkage is valid.
std::optional< NullabilityKind > getNullability () const
Determine the nullability of the given type.
bool canHaveNullability (bool ResultIfUnknown=true) const
Determine whether the given type can have a nullability specifier applied to it, i.e., if it is any kind of pointer type.
std::optional< ArrayRef< QualType > > getObjCSubstitutions (const DeclContext *dc) const
Retrieve the set of substitutions required when accessing a member of the Objective-C receiver type that is declared in the given context.
bool acceptsObjCTypeParams () const
Determines if this is an ObjC interface type that may accept type parameters.
const char * getTypeClassName () const
QualType getCanonicalTypeInternal () const
CanQualType getCanonicalTypeUnqualified () const
void dump () const
void dump (llvm::raw_ostream &OS, const ASTContext &Context) const
template<>
const TypedefType * getAs () const
This will check for a TypedefType by removing any existing sugar until it reaches a TypedefType or a non-sugared type.
template<>
const UsingType * getAs () const
template<>
const TemplateSpecializationType * getAs () const
This will check for a TemplateSpecializationType by removing any existing sugar until it reaches a TemplateSpecializationType or a non-sugared type.
template<>
const AttributedType * getAs () const
This will check for an AttributedType by removing any existing sugar until it reaches an AttributedType or a non-sugared type.
template<>
const TypedefType * getAs () const
template<>
const UsingType * getAs () const
template<>
const TemplateSpecializationType * getAs () const
template<>
const AttributedType * getAs () const
Protected Types
enum { NumTypeWithKeywordBits = 8 }
Protected Member Functions
Type (TypeClass tc, QualType canon, TypeDependence Dependence)
Type * this_ ()
void setDependence (TypeDependence D)
void addDependence (TypeDependence D)
Protected Attributes
union {
TypeBitfields TypeBits
ArrayTypeBitfields ArrayTypeBits
ConstantArrayTypeBitfields ConstantArrayTypeBits
AttributedTypeBitfields AttributedTypeBits
AutoTypeBitfields AutoTypeBits
TypeOfBitfields TypeOfBits
TypedefBitfields TypedefBits
UsingBitfields UsingBits
BuiltinTypeBitfields BuiltinTypeBits
FunctionTypeBitfields FunctionTypeBits
ObjCObjectTypeBitfields ObjCObjectTypeBits
ReferenceTypeBitfields ReferenceTypeBits
TypeWithKeywordBitfields TypeWithKeywordBits
ElaboratedTypeBitfields ElaboratedTypeBits
VectorTypeBitfields VectorTypeBits
SubstTemplateTypeParmTypeBitfields SubstTemplateTypeParmTypeBits
SubstTemplateTypeParmPackTypeBitfields SubstTemplateTypeParmPackTypeBits
TemplateSpecializationTypeBitfields TemplateSpecializationTypeBits
DependentTemplateSpecializationTypeBitfields DependentTemplateSpecializationTypeBits
PackExpansionTypeBitfields PackExpansionTypeBits
};
Friends
template<class T >
class TypePropertyCache
class ASTContext
class ASTReader
class ASTWriter
template<class T >
class serialization::AbstractTypeReader
template<class T >
class serialization::AbstractTypeWriter
Detailed Description
The base class of the type hierarchy.
A central concept with types is that each type always has a canonical type. A canonical type is the type with any typedef names stripped out of it or the types it references. For example, consider:
typedef int foo; typedef foo* bar; 'int *' 'foo *' 'bar'
There will be a Type object created for 'int'. Since int is canonical, its CanonicalType pointer points to itself. There is also a Type for 'foo' (a TypedefType). Its CanonicalType pointer points to the 'int' Type. Next there is a PointerType that represents 'int*', which, like 'int', is canonical. Finally, there is a PointerType type for 'foo*' whose canonical type is 'int*', and there is a TypedefType for 'bar', whose canonical type is also 'int*'.
Non-canonical types are useful for emitting diagnostics, without losing information about typedefs being used. Canonical types are useful for type comparisons (they allow by-pointer equality tests) and useful for reasoning about whether something has a particular form (e.g. is a function type), because they implicitly, recursively, strip all typedefs out of a type.
Types, once created, are immutable.
Definition at line 1577 of file Type.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NumTypeWithKeywordBits
Definition at line 1762 of file Type.h.
ScalarTypeKind
enum clang::Type::ScalarTypeKind
Enumerator
STK_CPointer
STK_BlockPointer
STK_ObjCObjectPointer
STK_MemberPointer
STK_Bool
STK_Integral
STK_Floating
STK_IntegralComplex
STK_FloatingComplex
STK_FixedPoint
Definition at line 2318 of file Type.h.
TypeClass
enum clang::Type::TypeClass
Definition at line 1579 of file Type.h.
Constructor & Destructor Documentation
Type() [1/3]
clang::Type::Type (TypeClass tc, QualType canon, TypeDependence Dependence) inline protected
Definition at line 1962 of file Type.h.
References clang::NoLinkage, and TypeBits.
Type() [2/3]
clang::Type::Type (const Type &) delete
Type() [3/3]
clang::Type::Type (Type &&) delete
Member Function Documentation
acceptsObjCTypeParams()
bool Type::acceptsObjCTypeParams () const
Determines if this is an ObjC interface type that may accept type parameters.
Definition at line 1635 of file Type.cpp.
References getAsObjCInterfaceType().
addDependence()
void clang::Type::addDependence (TypeDependence D) inline protected
Definition at line 1984 of file Type.h.
References getDependence(), and setDependence().
canDecayToPointerType()
bool clang::Type::canDecayToPointerType () const inline
Determines whether this type can decay to a pointer type.
Definition at line 7397 of file Type.h.
References isArrayType(), and isFunctionType().
Referenced by checkArithmeticNull(), clang::analyze_format_string::ArgType::matchesType(), and SemaBuiltinAlignment().
canHaveNullability()
bool Type::canHaveNullability (bool ResultIfUnknown = true) const
Determine whether the given type can have a nullability specifier applied to it, i.e., if it is any kind of pointer type.
Parameters
ResultIfUnknown The value to return if we don't yet know whether this type can have nullability because it is dependent.
Definition at line 4356 of file Type.cpp.
References getCanonicalTypeInternal().
Referenced by checkNullabilityTypeSpecifier(), and clang::Sema::getMessageSendResultType().
castAs()
template<typename T > const T * clang::Type::castAs () const
Member-template castAs<specific type>.
Look through sugar for the underlying instance of <specific type>.
This method has the same relationship to getAs<T> as cast<T> has to dyn_cast<T>; which is to say, the underlying type must have the intended type, and this method will never return null.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7527 of file Type.h.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnPropertyImplDecl(), addBlockPointerConversion(), clang::Sema::AddConversionCandidate(), addFunctionPointerConversions(), AddObjCKeyValueCompletions(), clang::Sema::adjustCCAndNoReturn(), clang::ASTContext::adjustDeducedFunctionResultType(), AdjustFunctionParmAndArgTypesForDeduction(), adjustFunctionTypeForInstantiation(), AnalyzeBitFieldAssignment(), clang::Sema::anyAltivecTypes(), applyObjCTypeArgs(), clang::ASTContext::areCommonBaseCompatible(), clang::ASTContext::areCompatibleVectorTypes(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildMemberReferenceExpr(), buildMemcpyForAssignmentOp(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildResolvedCallExpr(), buildTypeForLambdaCallOperator(), clang::Sema::BuildVectorLiteral(), checkArithmeticOnObjCPointer(), checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckBaseClassAccess(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), CheckCompleteParameterTypesForMangler(), checkConditionalObjectPointersCompatibility(), checkConditionalPointerCompatibility(), CheckConstexprParameterTypes(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), checkEnumArithmeticConversions(), clang::Sema::CheckEquivalentExceptionSpec(), CheckEvaluationResult(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckFunctionTemplateSpecialization(), CheckIncrementDecrementOperand(), clang::Sema::checkInitMethod(), checkIsValidOpenCLKernelParameter(), clang::Sema::CheckMain(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckMSVCRTEntryPoint(), checkObjCPointerTypesForAssignment(), checkOpenCLBlockArgs(), checkOpenCLEnqueueVariadicArgs(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverridingFunctionAttributes(), clang::Sema::CheckOverridingFunctionExceptionSpec(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckSizelessVectorConditionalTypes(), checkSizelessVectorShift(), clang::Sema::CheckSpecifiedExceptionType(), checkSwiftAsyncErrorBlock(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentIsCompatibleWithParameter(), clang::Sema::CheckTransparentUnionArgumentConstraints(), clang::Sema::CheckUnresolvedMemberAccess(), checkVAStartABI(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CheckVectorConditionalTypes(), commonEmitCXXMemberOrOperatorCall(), compareConversionFunctions(), CompareDerivedToBaseConversions(), clang::CodeGen::CGDebugInfo::completeClass(), completeFunctionType(), CompleteNonViableCandidate(), clang::CodeGen::CGDebugInfo::completeType(), convertHalfVecBinOp(), ConvertQualTypeToKind(), convertToComplexValue(), create_std_move_forward(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeduceReturnType(), DeduceTemplateSpecArguments(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitCopyConstructor(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DefineImplicitMoveConstructor(), clang::InitializationSequence::Diagnose(), DiagnoseArityMismatch(), clang::Sema::DiagnoseAssignmentResult(), DiagnoseCallingConvCast(), diagnoseListInit(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseSentinelCalls(), emitDestructorsFunction(), clang::CodeGen::CGCXXABI::EmitLoadOfMemberFunctionPointer(), emitPointerArithmetic(), emitProxyTaskFunction(), emitTaskDupFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), emitTaskPrivateMappingFunction(), emitWritebackArg(), EvalAndBitcastToAPInt(), EvaluateBuiltinClassifyType(), clang::Sema::EvaluateImplicitExceptionSpec(), evaluateLValueAsAllocSize(), clang::Sema::FindAllocationFunctions(), clang::Expr::findBoundMemberType(), clang::Sema::FindCompositeObjCPointerType(), FindConversionForRefInit(), FindDesignatorMismatch(), clang::Sema::findInheritingConstructor(), findMethodDecl(), findSubobject(), funcHasParameterSizeMangling(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::CXXNewExpr::getAllocatedType(), clang::QualType::getBaseTypeIdentifier(), clang::Expr::getBestDynamicClassType(), getCallingConvMangling(), clang::FunctionDecl::getCallResultType(), clang::CallExpr::getCallReturnType(), getConversionOpReturnTyAsFunction(), clang::CXXConversionDecl::getConversionType(), clang::ASTContext::getCorrespondingSaturatedType(), clang::ASTContext::getCorrespondingSignedFixedPointType(), getCXXRecord(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::TemplateTypeParmDecl::getDepth(), clang::ASTContext::getExtVectorType(), getFixedEnumPromtion(), clang::ASTContext::getFixedPointIBits(), clang::ASTContext::getFixedPointScale(), clang::Decl::getFunctionType(), clang::CodeGen::CodeGenTypes::GetFunctionTypeForVTable(), clang::ASTContext::getFunctionTypeWithExceptionSpec(), clang::TemplateTypeParmDecl::getIndex(), clang::CXXRecordDecl::getLambdaStaticInvoker(), clang::CodeGen::CGCXXABI::getMemberPointerAdjustment(), clang::CXXMethodDecl::getMethodQualifiers(), getMostInformativeDerivedClassImpl(), clang::UnresolvedMemberExpr::getNamingClass(), clang::OverloadCandidate::getNumParams(), clang::ASTContext::getObjCEncodingForBlock(), clang::ASTContext::getObjCGCAttrKind(), getObjCSubstitutions(), clang::ObjCObjectPointerType::getObjectType(), clang::interp::Program::getOrCreateDummy(), clang::TemplateArgument::getPackExpansionPattern(), clang::CodeGen::CGOpenCLRuntime::getPipeElemAlign(), clang::CodeGen::CGOpenCLRuntime::getPipeElemSize(), clang::ReferenceType::getPointeeType(), clang::CXXMethodDecl::getRefQualifier(), clang::FunctionDecl::getReturnType(), getRVVEltType(), clang::Sema::GetSignedSizelessVectorType(), clang::Sema::GetSignedVectorType(), getSveEltType(), clang::CastExpr::getTargetFieldForToUnionCast(), getUsualDeleteParams(), clang::AtomicExpr::getValueType(), HandleArmSveVectorBitsTypeAttr(), handleComplexFloatConversion(), handleFormatArgAttr(), handleFormatAttr(), clang::Sema::HandleFunctionTypeMismatch(), handleIntegerToComplexFloatConversion(), HandleOpenCLAccessAttr(), HandleRISCVRVVVectorBitsTypeAttr(), handleSentinelAttr(), handleSwiftAsyncAttr(), handleVectorVectorBinOp(), hasDeducedReturnType(), hasDefaultCXXMethodCC(), HasNoThrowOperator(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::Sema::InstantiateExceptionSpec(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), IsAcceptableNonMemberOperatorCandidate(), clang::CXXMethodDecl::isConst(), clang::Expr::isConstantInitializer(), clang::CXXConstructorDecl::isConvertingConstructor(), isDesignatorAtObjectEnd(), isIdiomaticBraceElisionEntity(), IsInitializerListConstructorConversion(), isNoexcept(), clang::Sema::isOpenMPCapturedByRef(), clang::TemplateTypeParmDecl::isParameterPack(), clang::Sema::IsPointerConversion(), clang::ento::cocoa::isRefType(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), isStdBuiltin(), IsStructurallyEquivalent(), IsUserDefinedConversion(), IsVoidStarType(), clang::CXXMethodDecl::isVolatile(), isZeroInitialized(), LookupMethodInReceiverType(), lookupPromiseType(), clang::Sema::LookupTemplateName(), makeTailCallIfSwiftAsync(), clang::MangleContext::mangleName(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::ASTContext::mergeObjCGCQualifiers(), clang::Sema::MergeTypedefNameDecl(), clang::ASTContext::mergeTypes(), clang::Sema::MergeVarDeclExceptionSpecs(), ObjCEncodingForEnumType(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PrepareScalarCast(), clang::Sema::prepareVectorSplat(), clang::APValue::printPretty(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), clang::Sema::ResolveExceptionSpec(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::SemaConvertVectorExpr(), SemaOpenCLBuiltinEnqueueKernel(), clang::ASTContext::setCFConstantStringType(), setObjCGCLValueClass(), SetValueDataBasedOnQualType(), clang::CXXNewExpr::shouldNullCheckAllocation(), shouldSkipNotingLambdaConversionDecl(), clang::Expr::skipRValueSubobjectAdjustments(), clang::ObjCObjectPointerType::stripObjCKindOfTypeAndQuals(), clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias(), tryEmitSpecializedAllocInit(), tryGCCVectorConvertAndSplat(), TryListConversion(), TryReferenceInit(), TryReferenceInitialization(), TryReferenceListInitialization(), TryRefInitWithConversionFunction(), TryStaticCast(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::ento::ExprEngine::VisitOffsetOfExpr().
castAsArrayTypeUnsafe()
const ArrayType * clang::Type::castAsArrayTypeUnsafe () const inline
A variant of castAs<> for array type which silently discards qualifiers from the outermost type.
Definition at line 7536 of file Type.h.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by CheckEvaluationResult(), FindDesignatorMismatch(), getArrayIndexingBound(), clang::QualType::getBaseTypeIdentifier(), getCoreType(), and clang::APValue::printPretty().
containsErrors()
bool clang::Type::containsErrors () const inline
Whether this type is an error type.
Definition at line 2339 of file Type.h.
References getDependence().
Referenced by clang::Sema::BuildReturnStmt(), clang::Sema::CheckFieldDecl(), and clang::Sema::MergeVarDeclTypes().
containsUnexpandedParameterPack()
bool clang::Type::containsUnexpandedParameterPack () const inline
Whether this type is or contains an unexpanded parameter pack, used to support C++0x variadic templates.
A type that contains a parameter pack shall be expanded by the ellipsis operator at some point. For example, the typedef in the following example contains an unexpanded parameter pack 'T':
template<typename ...T>
struct X {
  typedef T* pointer_types; // ill-formed; T is a parameter pack.
};
Note that this routine does not specify which
Definition at line 2017 of file Type.h.
References getDependence().
Referenced by buildDeclareReductionRef(), buildUserDefinedMapperRef(), clang::Sema::CheckBaseSpecifier(), clang::Sema::CheckPackExpansion(), clang::DeclarationNameInfo::containsUnexpandedParameterPack(), clang::Sema::containsUnexpandedParameterPacks(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::DiagnoseUnexpandedParameterPack(), getLambdaType(), clang::ASTContext::getPackExpansionType(), clang::ASTContext::getUnconstrainedType(), handleAlignedAttr(), clang::Sema::SubstParmVarDecl(), and clang::TreeTransform< Derived >::TransformFunctionTypeParams().
dump() [1/2]
LLVM_DUMP_METHOD void Type::dump () const
Definition at line 195 of file ASTDumper.cpp.
References clang::ExtQualsTypeCommonBase::QualType.
dump() [2/2]
LLVM_DUMP_METHOD void Type::dump (llvm::raw_ostream & OS, const ASTContext & Context) const
Definition at line 197 of file ASTDumper.cpp.
References clang::ExtQualsTypeCommonBase::QualType.
getArrayElementTypeNoTypeQual()
const Type * Type::getArrayElementTypeNoTypeQual () const
If this is an array type, return the element type of the array, potentially with type qualifiers missing.
getArrayElementTypeNoTypeQual - If this is an array type, return the element type of the array, potentially with type qualifiers missing.
This should never be used when type qualifiers are meaningful.
This method should never be used when type qualifiers are meaningful.
Definition at line 371 of file Type.cpp.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by clang::Sema::BuildExpressionFromDeclTemplateArgument(), checkNullabilityTypeSpecifier(), clang::Sema::deepTypeCheckForSYCLDevice(), and evenFlexibleArraySize().
getAs() [1/9]
template<typename T > const T * clang::Type::getAs () const
Member-template getAs<specific type>'.
Look through sugar for an instance of <specific type>. This scheme will eventually replace the specific getAsXXXX methods above.
There are some specializations of this member template listed immediately following this class.
Definition at line 7460 of file Type.h.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFields(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), actOnOMPReductionKindClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartCXXMemberReference(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddConversionCandidate(), clang::Sema::AddKnownFunctionAttributes(), clang::Sema::AddMemberOperatorCandidates(), clang::Sema::AddModeAttr(), AddTypedNameChunk(), AdjustFunctionParmAndArgTypesForDeduction(), AnalyzeBitFieldAssignment(), AnalyzeCompoundAssignment(), appendFunctionType(), appendType(), applyObjCTypeArgs(), clang::ASTContext::areComparableObjCPointerTypes(), clang::ASTContext::areCompatibleRVVTypes(), clang::ASTContext::areCompatibleSveTypes(), clang::ASTContext::areLaxCompatibleRVVTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), clang::Sema::areMatrixTypesOfTheSameDimension(), clang::Sema::areMultiversionVariantFunctionsCompatible(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::Sema::AttachBaseSpecifiers(), clang::ASTDeclReader::attachPreviousDeclImpl(), BitsContainNoUserData(), breakDownVectorType(), clang::Sema::BuildArrayType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildClassMessage(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildExpressionFromIntegralTemplateArgument(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildMemberExpr(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildQualifiedType(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorType(), clang::Sema::ImplicitExceptionSpecification::CalledDecl(), clang::arcmt::trans::canApplyWeak(), canAssignObjCObjectTypes(), clang::Sema::canCalleeThrow(), CanThrow(), clang::FunctionProtoType::canThrow(), clang::Sema::canThrow(), clang::canTypeidThrow(), captureInBlock(), captureInLambda(), CheckAggExprForMemSetUse(), checkArithmeticIncompletePointerType(), checkArithmeticOpPointerOperand(), CheckArrow(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompatibleReinterpretCast(), clang::Sema::CheckCompleteDecompositionDeclaration(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), clang::Sema::CheckConversionToObjCLiteral(), CheckCXX98CompatAccessibleCopy(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckDistantExceptionSpec(), checkEnumTypesInSwitchStmt(), clang::Sema::CheckEnumUnderlyingType(), clang::Sema::CheckEquivalentExceptionSpec(), CheckEvaluationResult(), clang::Sema::CheckExceptionSpecSubset(), CheckExtVectorComponent(), CheckFallThroughForBody(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckFloatComparison(), checkFormatStringExpr(), checkFoundationAPI(), checkFPMathBuiltinElementType(), CheckIdentityFieldAssignment(), clang::Sema::checkIllFormedTrivialABIStruct(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), checkIsValidOpenCLKernelParameter(), clang::Sema::CheckLiteralOperatorDeclaration(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckLValueToRValueConversionOperand(), clang::Sema::CheckMain(), checkMathBuiltinElementType(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), clang::Sema::CheckMemberPointerConversion(), clang::Sema::CheckMessageArgumentTypes(), CheckMethodOverrideParam(), CheckMethodOverrideReturn(), CheckNonNullArguments(), clang::Sema::CheckNontrivialField(), checkNullabilityTypeSpecifier(), clang::Sema::CheckObjCARCUnavailableWeakConversion(), checkObjCArrayLiteral(), checkObjCCollectionLiteralElement(), clang::Sema::CheckObjCConversion(), checkObjCDictionaryLiteral(), clang::Sema::CheckObjCForCollectionOperand(), checkObjCKindOfType(), checkOpenCLConditionVector(), checkOpenCLPipePacketType(), CheckOperatorNewDeleteTypes(), CheckOriginalCallArgDeduction(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckPointerToMemberOperands(), checkQualifiedFunction(), clang::Sema::CheckQualifiedFunctionForTypeId(), CheckRealImagOperand(), CheckRelatedResultTypeCompatibility(), clang::Sema::CheckShiftOperands(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorCompareOperands(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::CheckSubscriptingKind(), clang::Sema::CheckSubtractionOperands(), checkSwiftAsyncErrorBlock(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentIsCompatibleWithParameter(), checkTypedefTypeForCapability(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorLogicalOperands(), clang::Sema::CheckVectorOperands(), checkVectorResult(), checkVectorShift(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), PNaClABIInfo::classifyArgumentType(), ClassifyDiagnostic(), clang::CodeGen::classifyReturnType(), clang::CodeGen::DefaultABIInfo::classifyReturnType(), PNaClABIInfo::classifyReturnType(), classifyTypeForARCConversion(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteObjCSuperMessage(), CollectVRQualifiers(), CompareDerivedToBaseConversions(), CompareStandardConversionSequences(), CompleteNonViableCandidate(), clang::Sema::computeDeclContext(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), ConvertQualTypeToKind(), ConvertTypeToDiagnosticString(), convertVector(), create_call_once(), create_dispatch_once(), create_OSAtomicCompareAndSwap(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::interp::Program::createDescriptor(), CreateFunctionRefExpr(), clang::Sema::CreatePropertyDecl(), CXXRecordMembersNamed(), clang::Sema::DeclClonePragmaWeak(), clang::Sema::DeduceAutoType(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::DeduceReturnType(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateSpecArguments(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefineImplicitCopyAssignment(), clang::CodeGen::CGObjCRuntime::destroyCalleeDestroyedArguments(), clang::desugarForDiagnostic(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseAssignmentEnum(), diagnoseBadCast(), DiagnoseBadConversion(), DiagnoseBadTarget(), DiagnoseCastOfObjCSEL(), clang::ODRDiagsEmitter::diagnoseMismatch(), DiagnoseNarrowingInInitList(), clang::Sema::DiagnosePropertyAccessorMismatch(), DiagnoseRecursiveConstFields(), DiagnoseRecursiveConstFields(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseSentinelCalls(), diagnoseSubMismatchMethodParameters(), DiagnoseVariableSizedIvars(), doesUsualArrayDeleteWantSize(), doRewriteToUTF8StringBoxedExpressionHelper(), EmitCompare(), clang::CodeGen::ConstantEmitter::emitForMemory(), EmitFunctionDeclPointer(), EmitObjectDelete(), emitPointerArithmetic(), EmitPointerWithAlignment(), EncodeBitField(), EvaluateBinaryTypeTrait(), evenFlexibleArraySize(), extractPBaseFlags(), clang::Sema::ExtractUnqualifiedFunctionType(), FieldHasTrivialDestructorBody(), clang::Sema::FindCompositePointerType(), FindConversionForRefInit(), findEnumForBlockReturn(), clang::Sema::FindInstantiatedDecl(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), GeneralizeFunctionType(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getAbsoluteValueArgumentType(), clang::ento::BasicValueFactory::getAPSIntType(), getAsComplexIntegerType(), getAsObjCInterfacePointerType(), getAsObjCInterfaceType(), getAsObjCQualifiedClassType(), getAsObjCQualifiedIdType(), getAsObjCQualifiedInterfaceType(), GetAssumedMessageSendExprType(), getAsTagDecl(), GetBaseType(), clang::Expr::getBestDynamicClassType(), clang::CallExpr::getCallReturnType(), clang::ASTContext::getCommentForDecl(), getConversionOpReturnTyAsFunction(), getCXXRecord(), clang::ento::MemRegionManager::getCXXThisRegion(), clang::ento::CallEvent::getDeclaredResultType(), getDependentArraySubscriptType(), clang::FunctionDecl::getEllipsisLoc(), GetExprType(), GetFixedPointRank(), clang::VarDecl::getFlexibleArrayInitChars(), getFuchsiaHandleSymbols(), GetFullTypeForDeclarator(), clang::Sema::getFullyPackExpandedSize(), clang::TypeName::getFullyQualifiedNestedNameSpecifier(), clang::TypeName::getFullyQualifiedType(), clang::getFunctionExtInfo(), clang::CodeCompleteConsumer::OverloadCandidate::getFunctionType(), clang::CodeGen::CGDebugInfo::getFunctionType(), clang::Decl::getFunctionType(), clang::ASTContext::getFunctionTypeWithoutPtrSizes(), GetGCAttrTypeForType(), clang::ASTContext::getIntWidth(), clang::ASTContext::getLegacyIntegralTypeEncoding(), clang::StandardConversionSequence::getNarrowingKind(), clang::NSAPI::GetNSIntegralKind(), clang::NSAPI::getNSNumberFactoryMethodKind(), getNullability(), clang::ento::getNullabilityAnnotation(), GetNumNonZeroBytesInInit(), clang::FunctionDecl::getNumParams(), getObjCBridgeAttr(), clang::ASTContext::getObjCObjectType(), getObjCSubstitutions(), getPointeeCXXRecordDecl(), getPointeeType(), getPrettyTypeName(), clang::ASTContext::getPromotedIntegerType(), GetPrototypeLoc(), getRangeForType(), clang::ObjCMessageExpr::getReceiverInterface(), clang::interp::ByteCodeExprGen< Emitter >::getRecordTy(), getRecordType(), GetReturnType(), clang::extractapi::TypedefUnderlyingTypeResolver::getSymbolReferenceForType(), getTypeExpansion(), clang::ASTContext::getUnconstrainedType(), clang::GetUnderlyingFunction(), clang::extractapi::TypedefUnderlyingTypeResolver::getUnderlyingTypeDecl(), clang::Expr::getValueKindForType(), clang::ASTContext::getVectorType(), HandleBaseToDerivedCast(), handleFormatArgAttr(), handleFunctionTypeAttr(), clang::Sema::HandleFunctionTypeMismatch(), handleGlobalAttr(), HandleMemberPointerAccess(), handleObjCOwnershipTypeAttr(), HandleOpenCLAccessAttr(), clang::Sema::HandlePropertyInClassExtension(), clang::Sema::handlerCanCatch(), hasAttr(), clang::ASTNodeImporter::hasAutoReturnTypeDeclaredInside(), hasBooleanRepresentation(), clang::Sema::hasExplicitCallingConv(), HasExplicitOwnershipAttr(), clang::VarDecl::hasFlexibleArrayInit(), hasIsEqualMethod(), hasSizedVLAType(), hasTypedefNamed(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::Sema::IgnoredValueConversions(), clang::ASTNodeImporter::ImportFieldDeclDefinition(), clang::Sema::inferCUDATargetForImplicitSpecialMember(), clang::TemplateDeclInstantiator::InitFunctionInstantiation(), clang::ASTReader::InitializeContext(), clang::InitializationSequence::InitializeFrom(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), is32Or64BitBasicType(), IsAddressSpaceConversion(), isAlignValT(), isArithmeticArgumentPromotion(), isAtLeastAsSpecializedAs(), isBlockCompatibleObjCPointerType(), clang::Sema::IsBlockPointerConversion(), isBooleanType(), isCanonicalExceptionSpecification(), isCARCBridgableType(), IsCFError(), isCFStringType(), isClassType(), clang::ento::cocoa::isCocoaObjectRef(), clang::Sema::IsComplexPromotion(), clang::CXXMethodDecl::isCopyAssignmentOperator(), isCUDADeviceBuiltinSurfaceType(), isCUDADeviceBuiltinTextureType(), clang::QualType::isCXX11PODType(), clang::ParmVarDecl::isDestroyedInCallee(), isDispatchBlock(), clang::CodeGen::isEmptyField(), isErrorParameter(), clang::Sema::IsFloatingPointPromotion(), clang::CodeGen::CodeGenTypes::isFuncParamTypeConvertible(), clang::Sema::IsFunctionConversion(), isFunctionNoProtoType(), isFunctionPointerType(), isFunctionProtoType(), isFunctionReferenceType(), clang::arcmt::trans::MigrationContext::isGCOwnedNonObjC(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), clang::Sema::isInitListConstructor(), isIntegerLikeType(), clang::Sema::IsIntegralPromotion(), isInterfaceType(), isKnownNonNilCollectionType(), clang::Sema::isLaxVectorConversion(), isLiteralType(), isMemberDataPointerType(), isMemberFunctionPointerType(), clang::Sema::IsMemberPointerConversion(), IsNSError(), isNSStringType(), clang::BinaryOperator::isNullPointerArithmeticExtension(), clang::Expr::isNullPointerConstant(), isObjCBoxableRecordType(), isObjCClassOrClassKindOfType(), isObjCClassType(), isObjCIdOrObjectKindOfType(), isObjCIdType(), isObjCIndependentClassType(), isObjCIndirectLifetimeType(), isObjCNSObjectType(), clang::Sema::isObjCPointerConversion(), isObjCQualifiedClassType(), isObjCQualifiedIdType(), isObjCSelType(), clang::Sema::isObjCWritebackConversion(), isObjectPointerType(), clang::RecordDecl::isOrContainsUnion(), clang::NonTypeTemplateParmDecl::isPackExpansion(), isPermittedNeonBaseType(), clang::Sema::IsPointerConversion(), clang::StandardConversionSequence::isPointerConversionToVoidPointer(), isPointerToRecordType(), clang::CodeGen::ABIInfo::isPromotableIntegerTypeForABI(), clang::CodeGen::isRecordWithSIMDVectorType(), clang::QualType::isReferenceable(), clang::ento::cocoa::isRefType(), isRVVSizelessBuiltinType(), isRVVVLSBuiltinType(), IsSameCharType(), clang::ASTContext::isSameEntity(), clang::Sema::isSameOrCompatibleFunctionType(), isScopedEnumeralType(), clang::CodeGen::isSIMDVectorType(), clang::CodeGen::isSingleElementStruct(), isSizelessBuiltinType(), isSpecificBuiltinType(), IsStandardConversion(), isStandardLayoutType(), isStdByteType(), clang::Sema::isStdInitializerList(), IsStdString(), clang::Sema::IsStringLiteralToNonConstPointerConversion(), isStructureOrClassType(), isStructureType(), isSubstitutedType(), isSVESizelessBuiltinType(), isTemplateArgumentTemplateParameter(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTrivialType(), isTypedefNameType(), isTypeSubstitutable(), isUnionType(), IsUserDefinedConversion(), isValidBaseType(), isValidBPFPreserveEnumValueArg(), isValidBPFPreserveTypeInfoArg(), isValidSwiftErrorResultType(), isValidSwiftIndirectResultType(), isVarDeclStrongDefinition(), isVariableCapturable(), isVector(), isVLSTBuiltinType(), isVoidPointerType(), isWebAssemblyExternrefType(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), clang::FieldDecl::isZeroSize(), loadToBegin(), LookupDirect(), clang::Sema::LookupInlineAsmField(), clang::Sema::LookupInlineAsmVarDeclField(), LookupMemberExpr(), LookupMethodInReceiverType(), clang::Sema::LookupTemplateName(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkFunctionReferenced(), MarkUsedTemplateParameters(), clang::analyze_format_string::ArgType::matchesType(), maybeAdjustInterfaceForSubscriptingCheck(), clang::Sema::MaybeBindToTemporary(), clang::CodeGen::CodeGenModule::MayDropFunctionReturn(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::ASTContext::mergeTypes(), clang::Sema::MergeVarDeclExceptionSpecs(), clang::analyze_format_string::FormatSpecifier::namedTypeToLengthModifier(), needsConversionOfHalfVec(), NoteIndirectBases(), NoteSurrogateCandidate(), ObjCEnumerationCollection(), clang::ASTContext::ObjCObjectAdoptsQTypeProtocols(), OpenCLConvertScalarsToVectors(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::DeclarationName::print(), printCXXConstructorDestructorName(), clang::ento::ExprEngine::processSwitch(), clang::Sema::ProduceCallSignatureHelp(), PropertyMemoryAttribute(), pushTemporaryCleanup(), clang::ASTContext::QIdProtocolsAdoptObjCObjectProtocols(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), REGISTER_MAP_WITH_PROGRAMSTATE(), clang::ASTContext::removePtrSizeAddrSpace(), clang::Sema::RequireLiteralType(), clang::Sema::ResolveAddressOfOverloadedFunction(), clang::CodeGen::CodeGenModule::ReturnTypeUsesFP2Ret(), clang::CodeGen::CodeGenModule::ReturnTypeUsesFPRet(), rewriteToNumericBoxedExpression(), rewriteToObjCProperty(), SemaBuiltinDumpStruct(), SemaBuiltinOverflow(), clang::Sema::SetIvarInitializers(), setUsedBits(), SetValueDataBasedOnQualType(), shouldAddReversedEqEq(), ShouldDiagnoseUnusedDecl(), shouldNotPrintDirectly(), ShouldTryAgainWithRedefinitionType(), clang::Expr::skipRValueSubobjectAdjustments(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::SubstituteExplicitTemplateArguments(), threadSafetyCheckIsPointer(), TryAddressSpaceCast(), tryAtomicConversion(), TryClassUnification(), TryConstCast(), TryConstructorInitialization(), TryDeconstructFunctionLike(), clang::Sema::tryExprAsCall(), tryGCCVectorConvertAndSplat(), tryGetFunctionProtoType(), TryImplicitConversion(), TryListInitialization(), TryLValueToRValueCast(), TryObjectArgumentInitialization(), TryOrBuildParenListInitialization(), TryReferenceInit(), TryRefInitWithConversionFunction(), TryReinterpretCast(), TryStaticCast(), TryStaticMemberPointerUpcast(), TryStaticPointerDowncast(), TryStaticReferenceDowncast(), TryUserDefinedConversion(), TypeHasMayAlias(), TypeIsInnerPointer(), unsupportedTypeConversion(), clang::ASTContext::UnwrapSimilarTypes(), clang::QualType::UseExcessPrecision(), clang::Sema::UsualArithmeticConversions(), clang::FunctionCallFilterCCC::ValidateCandidate(), clang::Value::Value(), clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFriendDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::ASTNodeImporter::VisitRecordDecl(), clang::ento::SValExplainer::VisitSymbolicRegion(), and clang::serialization::DataStreamBasicWriter< Impl >::writeLValuePathSerializationHelper().
getAs() [2/9]
template<> const TypedefType * clang::Type::getAs () const
This will check for a TypedefType by removing any existing sugar until it reaches a TypedefType or a non-sugared type.
getAs() [3/9]
template<> const UsingType * clang::Type::getAs () const
getAs() [4/9]
template<> const TemplateSpecializationType * clang::Type::getAs () const
This will check for a TemplateSpecializationType by removing any existing sugar until it reaches a TemplateSpecializationType or a non-sugared type.
getAs() [5/9]
template<> const AttributedType * clang::Type::getAs () const
This will check for an AttributedType by removing any existing sugar until it reaches an AttributedType or a non-sugared type.
getAs() [6/9]
template<> const TypedefType * clang::Type::getAs () const
Definition at line 526 of file Type.cpp.
References getAsSugar().
getAs() [7/9]
template<> const UsingType * clang::Type::getAs () const
Definition at line 530 of file Type.cpp.
References getAsSugar().
getAs() [8/9]
template<> const TemplateSpecializationType * clang::Type::getAs () const
Definition at line 534 of file Type.cpp.
References getAsSugar().
getAs() [9/9]
template<> const AttributedType * clang::Type::getAs () const
Definition at line 538 of file Type.cpp.
References getAsSugar().
getAsAdjusted()
template<typename T > const T * clang::Type::getAsAdjusted () const
Member-template getAsAdjusted<specific type>.
Look through specific kinds of sugar (parens, attributes, etc) for an instance of <specific type>. This is used when you need to walk over sugar nodes that represent some kind of type adjustment from a type that was written as a <specific type> to another type that is still canonically a <specific type>.
Definition at line 7477 of file Type.h.
References P.
Referenced by clang::Sema::checkOpenMPDeclareVariantFunction(), and CreateNewFunctionDecl().
getAsArrayTypeUnsafe()
const ArrayType * clang::Type::getAsArrayTypeUnsafe () const inline
A variant of getAs<> for array types which silently discards qualifiers from the outermost type.
Definition at line 7513 of file Type.h.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnSourceLocExpr(), appendType(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildObjCEncodeExpression(), buildUserDefinedMapperRef(), clang::interp::CheckFieldsInitialized(), CheckStringInit(), classifyTypeForARCConversion(), clang::interp::Program::createDescriptor(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), clang::CodeGen::CGOpenMPRuntime::emitUsesAllocatorsInit(), clang::ASTContext::getBaseElementType(), getBaseElementTypeUnsafe(), getCanonicalParamType(), clang::ASTContext::getConstantArrayElementCount(), getDependentArraySubscriptType(), getDesignatedType(), getTypeString(), hasSizedVLAType(), isObjCLifetimeType(), clang::InitListExpr::isStringLiteralInit(), SemaBuiltinLaunder(), and clang::interp::ByteCodeExprGen< Emitter >::visitArrayInitializer().
getAsComplexIntegerType()
const ComplexType * Type::getAsComplexIntegerType () const
Definition at line 624 of file Type.cpp.
References Complex, and getAs().
Referenced by handleComplexIntConversion(), and isComplexIntegerType().
getAsCXXRecordDecl()
CXXRecordDecl * Type::getAsCXXRecordDecl () const
Retrieves the CXXRecordDecl that this type refers to, either because the type is a RecordType or because it is the injected-class-name type of a class template or class template partial specialization.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1799 of file Type.cpp.
References getAsTagDecl().
Referenced by clang::Sema::ActOnCXXTryBlock(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGHLSLRuntime::annotateHLSLResource(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildCXXConstructExpr(), BuildNonArrayForRange(), calculateOffset(), clang::interp::CallVirt(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), clang::canVarDeclThrow(), clang::Sema::CaptureHasSideEffects(), clang::Sema::CheckCompleteDecompositionDeclaration(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::CheckDestructor(), checkDestructorReference(), clang::CheckEquivalentExceptionSpecImpl(), checkForConsumableClass(), checkMoveAssignmentForRepeatedMove(), checkTrivialClassMembers(), checkTrivialSubobjectCall(), checkTupleLikeDecomposition(), CheckUnaryTypeTraitTypeCompleteness(), computeBlockInfo(), clang::CoroutineStmtBuilder::CoroutineStmtBuilder(), create_call_once(), clang::Sema::CreateBuiltinBinOp(), clang::ConstructionContext::createFromLayers(), clang::TypeName::createNestedNameSpecifierForScopeOf(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseReinterpretUpDownCast(), EmitDeclDestroy(), EmitDestroyingObjectDelete(), clang::CodeGen::CGOpenMPRuntime::emitTargetGlobalVariable(), clang::ento::StoreManager::evalBaseToDerived(), clang::Sema::FindAllocationFunctions(), findDeleteForPromise(), findSubobject(), clang::NestedNameSpecifier::getAsRecordDecl(), getBaseAlignmentAndOffsetFromPtr(), clang::ASTContext::getCommentForDecl(), getConstructedRegion(), getContainedDynamicClass(), getDerivedToBaseAlignmentAndOffset(), clang::CFGImplicitDtor::getDestructorDecl(), clang::Sema::getDestructorName(), getFieldsFromClassHierarchy(), clang::TypeName::getFullyQualifiedNestedNameSpecifier(), clang::LambdaExpr::getLambdaClass(), clang::ento::ProgramState::getLValue(), clang::CodeGen::CGCXXABI::getMemberPointerAdjustment(), clang::CodeGen::CodeGenModule::getMinimumObjectSize(), clang::MemberPointerType::getMostRecentCXXRecordDecl(), getNoteTag(), getOpenCLKernelParameterType(), clang::interp::Context::getOverridingFunction(), getPrettyTypeName(), clang::CXXMemberCallExpr::getRecordDecl(), clang::ento::BlockCall::getRuntimeDefinition(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), getUnionInitName(), HandleBaseToDerivedCast(), HandleLValueBase(), HandleLValueBasePath(), HandleMemberPointerAccess(), hasAnyVptr(), hasNonTrivialConstructorCall(), hasTrivialABIAttr(), clang::ComparisonCategoryInfo::ValueInfo::hasValidIntValue(), clang::Sema::inferGslPointerAttribute(), clang::Sema::isAbstractType(), clang::CXXDynamicCastExpr::isAlwaysNull(), isAutoCastType(), isConstNotMutableType(), isConsumableType(), clang::CFGCXXRecordTypedCall::isCXXRecordTypedCall(), clang::Sema::IsDerivedFrom(), clang::Sema::IsDerivedFrom(), clang::FunctionDecl::isDestroyingOperatorDelete(), isIncompleteType(), clang::ento::iterator::isIteratorType(), clang::ento::RetainSummaryManager::isKnownSmartPointer(), isNothrowT(), clang::Sema::isOpenMPPrivateDecl(), isOSObjectRelated(), isPointerToObject(), clang::CXXTypeidExpr::isPotentiallyEvaluated(), clang::FieldDecl::isPotentiallyOverlapping(), isRecordWithAttr(), isStdBasicOstream(), clang::ento::smartptr::isStdSmartPtr(), isStdSmartPtr(), isStructuralType(), clang::QualType::isTriviallyEqualityComparableType(), clang::CodeGen::CodeGenModule::isTypeConstant(), isValidBaseClass(), isValidSubjectOfOSAttribute(), clang::Sema::isValidVarArgType(), LeastDerivedClassWithSameLayout(), clang::ComparisonCategories::lookupInfoForType(), lookupPromiseType(), lookupStdTypeTraitMember(), mapConsumableAttrState(), PerformReturnAdjustment(), print_elem(), print_initializer(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::Sema::ProduceCallSignatureHelp(), recoverFromMSUnqualifiedLookup(), regionMatchesCXXRecordType(), clang::Sema::RequireStructuralType(), clang::CXXRecordDecl::setBases(), clang::Sema::tryCaptureOpenMPLambdas(), TryListInitialization(), TypeRequiresBuiltinLaunderImp(), usesMultipleInheritanceModel(), clang::ento::ExprEngine::VisitCXXDestructor(), visitLocalsRetainedByInitializer(), and warnAboutAmbiguousFunction().
getAsObjCInterfacePointerType()
const ObjCObjectPointerType * Type::getAsObjCInterfacePointerType () const
Definition at line 1776 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage(), CheckObjCBridgeCFCast(), CheckObjCBridgeNSCast(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::HandleExprPropertyRefExpr(), and clang::Sema::SelectorsForTypoCorrection().
getAsObjCInterfaceType()
const ObjCObjectType * Type::getAsObjCInterfaceType () const
Definition at line 1768 of file Type.cpp.
References getAs().
Referenced by acceptsObjCTypeParams(), and getBaseMessageSendResultType().
getAsObjCQualifiedClassType()
const ObjCObjectPointerType * Type::getAsObjCQualifiedClassType () const
Definition at line 1758 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage().
getAsObjCQualifiedIdType()
const ObjCObjectPointerType * Type::getAsObjCQualifiedIdType () const
Definition at line 1748 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage(), and clang::Sema::CodeCompleteObjCInstanceMessage().
getAsObjCQualifiedInterfaceType()
const ObjCObjectType * Type::getAsObjCQualifiedInterfaceType () const
Definition at line 1734 of file Type.cpp.
References getAs().
Referenced by isObjCQualifiedInterfaceType().
getAsPlaceholderType()
const BuiltinType * clang::Type::getAsPlaceholderType () const inline
Definition at line 7236 of file Type.h.
Referenced by clang::Sema::BuildBinOp(), clang::Sema::BuildUnaryOp(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckPlaceholderExpr(), checkPlaceholderForOverload(), clang::Sema::DefaultVariadicArgumentPromotion(), and isValidBPFPreserveFieldInfoArg().
getAsRecordDecl()
RecordDecl * Type::getAsRecordDecl () const
Retrieves the RecordDecl this type refers to.
Definition at line 1803 of file Type.cpp.
References getAsTagDecl().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList(), create_call_once(), clang::Sema::deepTypeCheckForSYCLDevice(), emitReadOnlyPlacementAttrWarning(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), getFieldsFromClassHierarchy(), clang::ASTNodeImporter::ImportFieldDeclDefinition(), isTrackedVar(), clang::QualType::isTriviallyRelocatableType(), clang::Sema::ProduceConstructorSignatureHelp(), SemaBuiltinDumpStruct(), and clang::ASTNodeImporter::VisitTypedefNameDecl().
getAsStructureType()
const RecordType * Type::getAsStructureType () const
Definition at line 647 of file Type.cpp.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by appendType(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::analyze_format_string::ArgType::matchesType(), and clang::Sema::ParsedFreeStandingDeclSpec().
getAsTagDecl()
TagDecl * Type::getAsTagDecl () const
Retrieves the TagDecl that this type refers to, either because the type is a TagType or because it is the injected-class-name type of a class template or class template partial specialization.
Definition at line 1807 of file Type.cpp.
References getAs().
Referenced by clang::Sema::ActOnTag(), clang::Sema::ActOnUsingEnumDeclaration(), clang::UsingEnumDecl::Create(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), emitDestructorsFunction(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitProxyTaskFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), emitTaskPrivateMappingFunction(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), getAsCXXRecordDecl(), getAsRecordDecl(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::UsingEnumDecl::getEnumDecl(), getUuidAttrOfType(), and TypeHasMayAlias().
getAsUnionType()
const RecordType * Type::getAsUnionType () const
NOTE: getAs*ArrayType are methods on ASTContext.
Definition at line 666 of file Type.cpp.
References clang::cast(), and getUnqualifiedDesugaredType().
Referenced by appendType(), CheckNonNullExpr(), clang::Sema::CheckTransparentUnionArgumentConstraints(), IsTransparentUnionStandardConversion(), clang::Sema::ParsedFreeStandingDeclSpec(), and clang::CodeGen::useFirstFieldIfTransparentUnion().
getBaseElementTypeUnsafe()
const Type * clang::Type::getBaseElementTypeUnsafe () const inline
Get the base element type of this type, potentially discarding type qualifiers.
This should never be used when type qualifiers are meaningful.
Definition at line 7410 of file Type.h.
References clang::ast_matchers::arrayType, getAsArrayTypeUnsafe(), and clang::ast_matchers::type.
Referenced by clang::Sema::BuildCXXConstructExpr(), clang::canVarDeclThrow(), clang::Sema::CaptureHasSideEffects(), clang::Sema::checkIllFormedTrivialABIStruct(), CheckUnaryTypeTraitTypeCompleteness(), clang::Sema::DiagnoseUnusedButSetDecl(), doesUsualArrayDeleteWantSize(), clang::CodeGen::CGOpenMPRuntime::emitTargetGlobalVariable(), getContainedDynamicClass(), getPointeeOrArrayElementType(), getUuidAttrOfType(), clang::ASTNodeImporter::ImportFieldDeclDefinition(), InitializationHasSideEffects(), clang::QualType::isCXX11PODType(), isLiteralType(), isStandardLayoutType(), clang::CodeGen::CGCXXABI::mayNeedDestruction(), print_elem(), and pushTemporaryCleanup().
getCanonicalTypeInternal()
QualType clang::Type::getCanonicalTypeInternal () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2625 of file Type.h.
Referenced by addAssociatedClassesAndNamespaces(), canHaveNullability(), checkOpenCLPipePacketType(), clang::Sema::CheckTemplateIdType(), DeduceTemplateArgumentsByTypeMatch(), clang::CodeGen::CodeGenTypes::DeriveThisType(), clang::TypePropertyCache< Private >::ensure(), clang::ASTContext::getCanonicalType(), getCanonicalTypeUnqualified(), getConstantArrayExtents(), getCurrentInstantiationOf(), clang::ASTContext::getObjCEncodingForBlock(), clang::ASTContext::getObjCEncodingForFunctionDecl(), clang::ASTContext::getObjCEncodingForMethodDecl(), clang::ASTContext::getObjCGCAttrKind(), clang::LocInfoType::getType(), clang::ASTContext::getUsingType(), isLinkageValid(), isLiteralType(), isObjCARCImplicitlyUnretainedType(), and isSameQualifier().
getCanonicalTypeUnqualified()
CanQualType clang::Type::getCanonicalTypeUnqualified () const inline
Definition at line 214 of file CanonicalType.h.
References clang::CanQual< Type >::CreateUnsafe(), and getCanonicalTypeInternal().
Referenced by adjustReturnValue(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodType(), clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(), clang::Sema::checkExceptionSpecification(), evaluateCDTSize(), findDirectBaseWithType(), GetFormalType(), GetReturnType(), clang::Sema::HandleFunctionTypeMismatch(), and setCUDAKernelCallingConvention().
getContainedAutoType()
AutoType * clang::Type::getContainedAutoType () const inline
Get the AutoType whose type will be deduced for a variable with an initializer of this type.
This looks through declarators like pointer types, but not through decltype or typedefs.
Definition at line 2450 of file Type.h.
References getContainedDeducedType().
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::BuildReturnStmt(), clang::NonTypeTemplateParmDecl::Create(), clang::Sema::DeduceAutoType(), clang::CodeGen::CGDebugInfo::EmitUsingDecl(), clang::ASTContext::getUnconstrainedType(), clang::NonTypeTemplateParmDecl::hasPlaceholderTypeConstraint(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::MergeFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
getContainedDeducedType()
DeducedType * Type::getContainedDeducedType () const
Get the DeducedType whose type will be deduced for a variable with an initializer of this type.
This looks through declarators like pointer types, but not through decltype or typedefs.
Definition at line 1928 of file Type.cpp.
Referenced by clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckTemplateArgument(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::deduceVarTypeFromInitializer(), getContainedAutoType(), isUndeducedType(), LookupDirect(), and clang::ASTDeclWriter::VisitVarDecl().
getDependence()
TypeDependence clang::Type::getDependence () const inline
Definition at line 2334 of file Type.h.
References TypeBits.
Referenced by addDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), containsErrors(), containsUnexpandedParameterPack(), isDependentType(), isInstantiationDependentType(), and isVariablyModifiedType().
getLinkage()
Linkage Type::getLinkage () const
Determine the linkage of this type.
Definition at line 4233 of file Type.cpp.
References clang::TypePropertyCache< Private >::ensure(), and TypeBits.
Referenced by checkUndefinedButUsed(), getTypeInfoLinkage(), and clang::Sema::isExternalWithNoLinkageType().
getLinkageAndVisibility()
LinkageInfo Type::getLinkageAndVisibility () const
Determine the linkage and visibility of this type.
Definition at line 4339 of file Type.cpp.
References clang::LinkageComputer::getTypeLinkageAndVisibility().
Referenced by getVisibility(), and isVisibilityExplicit().
getLocallyUnqualifiedSingleStepDesugaredType()
QualType Type::getLocallyUnqualifiedSingleStepDesugaredType () const
Pull a single level of sugar off of this locally-unqualified type.
Users should generally prefer SplitQualType::getSingleStepDesugaredType() or QualType::getSingleStepDesugaredType(const ASTContext&).
Definition at line 424 of file Type.cpp.
References getTypeClass().
Referenced by clang::SplitQualType::getSingleStepDesugaredType(), unwrapSugar(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::TextNodeDumper::Visit().
getNullability()
std::optional< NullabilityKind > Type::getNullability () const
Determine the nullability of the given type.
Note that nullability is only captured as sugar within the type system, not as part of the canonical type, so nullability will be lost by canonicalization and desugaring.
Definition at line 4343 of file Type.cpp.
References getAs(), and clang::ExtQualsTypeCommonBase::Type.
Referenced by clang::Sema::BuildObjCBoxedExpr(), CheckMethodOverrideParam(), CheckMethodOverrideReturn(), CheckNonNullExpr(), checkNullabilityTypeSpecifier(), clang::Sema::CheckObjCPropertyAttributes(), computeConditionalNullability(), clang::Sema::deduceClosureReturnType(), clang::Sema::diagnoseNullableToNonnullConversion(), clang::ASTContext::getArrayDecayedType(), clang::Sema::getMessageSendResultType(), clang::ASTContext::hasSameNullabilityTypeQualifier(), mergeParamDeclTypes(), and mergeTypeNullabilityForRedecl().
getObjCARCImplicitLifetime()
Qualifiers::ObjCLifetime Type::getObjCARCImplicitLifetime () const
Return the implicit lifetime for this type, which must not be dependent.
Definition at line 4547 of file Type.cpp.
References isObjCARCImplicitlyUnretainedType(), clang::Qualifiers::OCL_ExplicitNone, and clang::Qualifiers::OCL_Strong.
Referenced by clang::Sema::BuildCXXNew(), handleObjCPreciseLifetimeAttr(), and tryMakeVariablePseudoStrong().
getObjCSubstitutions()
std::optional< ArrayRef< QualType > > Type::getObjCSubstitutions (const DeclContext * dc) const
Retrieve the set of substitutions required when accessing a member of the Objective-C receiver type that is declared in the given context.
*this is the type of the object we're operating on, e.g., the receiver for a message send or the base of a property access, and is expected to be of some object or object pointer type.
Parameters
dc The declaration context for which we are building up a substitution mapping, which should be an Objective-C class, extension, category, or method within.
Returns
an array of type arguments that can be substituted for the type parameters of the given declaration context in any type described within that context, or an empty optional to indicate that no substitution is required.
Extract the class from the receiver object type.
Definition at line 1554 of file Type.cpp.
References castAs(), getAs(), clang::ObjCCategoryDecl::getClassInterface(), clang::ASTContext::getObjCObjectType(), clang::DeclContext::getParentASTContext(), clang::ObjCCategoryDecl::getTypeParamList(), clang::QualType::isNull(), and clang::ASTContext::ObjCBuiltinIdTy.
Referenced by clang::Sema::CheckMessageArgumentTypes(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), and clang::QualType::substObjCMemberType().
getPointeeCXXRecordDecl()
const CXXRecordDecl * Type::getPointeeCXXRecordDecl () const
If this is a pointer or reference to a RecordType, return the CXXRecordDecl that the type refers to.
If this is not a pointer or reference, or the type being pointed to does not refer to a CXXRecordDecl, returns NULL.
Definition at line 1784 of file Type.cpp.
References getAs(), and getPointeeType().
Referenced by adjustReturnValue(), DiagnoseReinterpretUpDownCast(), emitBadConversionNotes(), clang::ento::retaincountchecker::RetainCountChecker::errorKindToBugKind(), clang::SourceLocExpr::EvaluateInContext(), HandleDynamicCast(), isOSObjectPtr(), isSetOnReadPtrType(), clang::QualType::mayBeDynamicClass(), clang::QualType::mayBeNotDynamicClass(), regionMatchesCXXRecordType(), and shouldTrackFirstArgument().
getPointeeOrArrayElementType()
const Type * clang::Type::getPointeeOrArrayElementType () const inline
If this is a pointer type, return the pointee type.
If this is an array type, return the array element type. This should never be used when type qualifiers are meaningful.
Definition at line 7417 of file Type.h.
References getBaseElementTypeUnsafe(), getPointeeType(), clang::QualType::getTypePtr(), and clang::ast_matchers::type.
Referenced by clang::CodeGen::CGHLSLRuntime::annotateHLSLResource(), checkIsValidOpenCLKernelParameter(), clang::Sema::DiagnoseAssignmentResult(), getOpenCLKernelParameterType(), clang::InitializationSequence::Perform(), and SemaOpenCLBuiltinEnqueueKernel().
getPointeeType()
QualType Type::getPointeeType () const
If this is a pointer, ObjC object pointer, or block pointer, this returns the respective pointee.
Definition at line 631 of file Type.cpp.
References getAs(), and getPointeeType().
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPArrayShapingExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::AddConversionCandidate(), adjustCVQualifiersForCXXThisWithinLambda(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::ASTContext::AtomicUsesUnsupportedLibcall(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildCXXThisExpr(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildQualifiedType(), clang::Sema::BuildResolvedCallExpr(), BuildSimilarlyQualifiedPointerType(), clang::Sema::BuiltinRemovePointer(), clang::Sema::canCalleeThrow(), CanThrow(), clang::Sema::CaptureHasSideEffects(), captureInBlock(), captureInLambda(), clang::ento::StoreManager::castRegion(), castToBase(), checkArithmeticBinOpPointerOperands(), checkArithmeticIncompletePointerType(), checkArithmeticOpPointerOperand(), CheckArrow(), clang::Sema::CheckAssignmentConstraints(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompatibleReinterpretCast(), checkConditionalPointerCompatibility(), clang::Sema::CheckCXXThisCapture(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), CheckFallThroughForBody(), checkForConsumableClass(), CheckIndirectionOperand(), clang::Sema::CheckLiteralOperatorDeclaration(), checkMapConflicts(), checkMappableExpressionList(), CheckNonNullArguments(), checkNullabilityTypeSpecifier(), CheckObjCBridgeNSCast(), clang::Sema::CheckObjCConversion(), CheckOriginalCallArgDeduction(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckVirtualDtorCall(), ClassifyDiagnostic(), clang::Sema::CodeCompleteMemberReferenceExpr(), CollectVRQualifiers(), CompareStandardConversionSequences(), CompleteNonViableCandidate(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), create_call_once(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), decomposeTypeForEH(), clang::Sema::DeduceReturnType(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::deepTypeCheckForSYCLDevice(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), dereference(), diagnoseArithmeticOnTwoFunctionPointers(), clang::Sema::DiagnoseAssignmentResult(), diagnoseBadCast(), DiagnoseCastOfObjCSEL(), DiagnoseDivisionSizeofPointerOrArray(), diagnoseOpenCLTypes(), clang::Sema::DiagnoseSentinelCalls(), diagnoseStringPlusChar(), clang::Sema::DiagnoseSwiftName(), doRewriteToUTF8StringBoxedExpressionHelper(), emitAlignedClause(), EmitAtomicCmpXchgForMSIntrin(), emitBadConversionNotes(), EmitBinaryAtomicPost(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), emitFrexpBuiltin(), EmitISOVolatileLoad(), EmitISOVolatileStore(), emitPointerArithmetic(), EmitPointerWithAlignment(), emitWritebackArg(), clang::ento::StoreManager::evalBaseToDerived(), clang::ento::ExprEngine::evalCall(), EvaluateBuiltinStrLen(), clang::Expr::EvaluateCharRangeAsString(), clang::Sema::FindCompositePointerType(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), fixVarDeclWithSpan(), GeneralizeType(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getAArch64LS(), GetAlignedMapping(), getAlignmentAndOffsetFromBinAddOrSub(), getBaseAlignmentAndOffsetFromPtr(), clang::QualType::getBaseTypeIdentifier(), clang::Expr::getBestDynamicClassType(), clang::CallExpr::getCallReturnType(), getCoreType(), getCXXRecord(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), getFuchsiaHandleSymbols(), clang::TypeName::getFullyQualifiedType(), clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getInnerType(), clang::ento::StoreManager::getLValueElement(), clang::QualType::getNonLValueExprType(), clang::QualType::getNonReferenceType(), clang::OverloadCandidate::getNumParams(), getObjCBridgeAttr(), clang::ASTContext::getObjCGCQualType(), clang::CXXMemberCallExpr::getObjectType(), getOpenCLKernelParameterType(), getPointeeCXXRecordDecl(), getPointeeOrArrayElementType(), clang::ento::SymbolicRegion::getPointeeStaticType(), getPointeeType(), getPointeeTypeText(), getPresumedAlignmentOfPointer(), getPrettyTypeName(), clang::CXXMemberCallExpr::getRecordDecl(), getRecordType(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ASTContext::getTargetNullPointerValue(), clang::CodeGen::CGCXXABI::getThisAddress(), clang::GetUnderlyingFunction(), getUuidAttrOfType(), clang::CodeGen::getVAListElementType(), HandleBaseToDerivedCast(), clang::consumed::ConsumedStmtVisitor::handleCall(), handleCallbackAttr(), clang::Sema::HandleFunctionTypeMismatch(), HandleMemberPointerAccess(), handleMSPointerTypeQualifierAttr(), handleObjCOwnershipTypeAttr(), clang::Sema::handlerCanCatch(), HandleWebAssemblyFuncrefAttr(), handleXReturnsXRetainedAttr(), hasIsEqualMethod(), hasNonTrivialConstructorCall(), InitCatchParam(), clang::CXXDynamicCastExpr::isAlwaysNull(), clang::Sema::IsBlockPointerConversion(), isCARCBridgableType(), clang::CXXMethodDecl::isCopyAssignmentOperator(), isErrorParameter(), clang::arcmt::trans::MigrationContext::isGCOwnedNonObjC(), clang::Sema::isInitListConstructor(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::Expr::isNullPointerConstant(), clang::Sema::isObjCPointerConversion(), clang::Sema::isObjCWritebackConversion(), isOSObjectRelated(), clang::StandardConversionSequence::isPointerConversionToVoidPointer(), isPointerToConst(), isPointerToConst(), isPointerToConst(), isPointerToObject(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::Sema::IsStringLiteralToNonConstPointerConversion(), isSubstitutedType(), IsTypeModifiable(), isValidOSObjectOutParameter(), isValidSubjectOfOSAttribute(), isValidSwiftContextType(), isValidSwiftErrorResultType(), isValidSwiftIndirectResultType(), isVoidPointerToNonConst(), clang::AtomicExpr::isVolatile(), loadToBegin(), clang::Sema::LookupInlineAsmField(), MakeBinaryAtomicValue(), makeTailCallIfSwiftAsync(), clang::analyze_format_string::ArgType::matchesType(), clang::Sema::MergeVarDeclExceptionSpecs(), needsAmpersandOnTemplateArg(), NoteSurrogateCandidate(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PerformQualificationConversion(), PerformReturnAdjustment(), clang::Sema::PrepareScalarCast(), clang::APValue::printPretty(), processImplicitMapsWithDefaultMappers(), clang::Sema::ProduceCallSignatureHelp(), recoverFromMSUnqualifiedLookup(), clang::Sema::RefersToMemberWithReducedAlignment(), clang::ASTContext::removePtrSizeAddrSpace(), rewriteBuiltinFunctionDecl(), SemaBuiltinDumpStruct(), SemaBuiltinLaunder(), SemaBuiltinOverflow(), SemaOpenCLBuiltinEnqueueKernel(), shouldSkipNotingLambdaConversionDecl(), TryAddressSpaceCast(), clang::Sema::tryExprAsCall(), tryGetFunctionProtoType(), TryObjectArgumentInitialization(), TryRefInitWithConversionFunction(), TryReinterpretCast(), TryStaticCast(), TryToFixInvalidVariablyModifiedType(), unwrapCastAwayConstnessLevel(), clang::ASTContext::UnwrapSimilarTypes(), clang::FunctionCallFilterCCC::ValidateCandidate(), clang::ento::ExprEngine::VisitCXXNewExpr(), and clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl().
getRVVEltType()
QualType Type::getRVVEltType (const ASTContext & Ctx) const
Returns the representative type for the element of an RVV builtin type.
This is used to represent fixed-length RVV vectors created with the 'riscv_rvv_vector_bits' type attribute as VectorType.
Definition at line 2468 of file Type.cpp.
References castAs(), clang::ASTContext::BuiltinVectorTypeInfo::ElementType, clang::ASTContext::getBuiltinVectorTypeInfo(), and isRVVVLSBuiltinType().
Referenced by clang::ASTContext::areLaxCompatibleRVVTypes().
getScalarTypeKind()
Type::ScalarTypeKind Type::getScalarTypeKind () const
Given that this is a scalar type, classify it.
Definition at line 2213 of file Type.cpp.
References isBitIntType(), isScalarType(), STK_BlockPointer, STK_Bool, STK_CPointer, STK_FixedPoint, STK_Floating, STK_FloatingComplex, STK_Integral, STK_IntegralComplex, STK_MemberPointer, and STK_ObjCObjectPointer.
Referenced by matchTypes(), clang::Sema::PrepareScalarCast(), and clang::Sema::ScalarTypeToBooleanCastKind().
getSveEltType()
QualType Type::getSveEltType (const ASTContext & Ctx) const
Returns the representative type for the element of an SVE builtin type.
This is used to represent fixed-length SVE vectors created with the 'arm_sve_vector_bits' type attribute as VectorType.
Definition at line 2441 of file Type.cpp.
References castAs(), clang::ASTContext::BuiltinVectorTypeInfo::ElementType, clang::ASTContext::getBuiltinVectorTypeInfo(), clang::BuiltinType::getKind(), isVLSTBuiltinType(), and clang::ASTContext::UnsignedCharTy.
Referenced by clang::ASTContext::areCompatibleSveTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), CheckImplicitConversion(), clang::Sema::CheckSizelessVectorConditionalTypes(), checkSizelessVectorShift(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::GetSignedSizelessVectorType(), and HandleArmSveVectorBitsTypeAttr().
getTypeClass()
TypeClass clang::Type::getTypeClass () const inline
Definition at line 1997 of file Type.h.
References TypeBits.
Referenced by BuildSimilarlyQualifiedPointerType(), captureVariablyModifiedType(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::Sema::CreateParsedType(), clang::desugarForDiagnostic(), EvaluateBuiltinClassifyType(), getAsSugar(), clang::QualType::getBaseTypeIdentifier(), getCommonNonSugarTypeNode(), getCommonSugarTypeNode(), clang::Sema::getCopyElisionCandidate(), getLocallyUnqualifiedSingleStepDesugaredType(), clang::TypeLoc::getTypeLocClass(), clang::UnqualTypeLoc::getTypeLocClass(), getUnqualifiedDesugaredType(), clang::ASTContext::getVariableArrayDecayedType(), clang::QualType::isCXX98PODType(), isLayoutCompatible(), isSpecifierType(), IsStructurallyEquivalent(), isSubstitutedType(), clang::ASTContext::mergeTypes(), clang::ConstantMatrixType::Profile(), and clang::VectorType::Profile().
getTypeClassName()
const char * Type::getTypeClassName () const
Definition at line 3124 of file Type.cpp.
References TypeBits.
getUnqualifiedDesugaredType()
const Type * Type::getUnqualifiedDesugaredType () const
Return the specified type with any "sugar" removed from the type, removing any typedefs, typeofs, etc., as well as any qualifiers.
getUnqualifiedDesugaredType - Pull any qualifiers and syntactic sugar off the given type.
This should produce an object of the same dynamic type as the canonical type.
Definition at line 545 of file Type.cpp.
References getTypeClass().
Referenced by clang::Sema::ActOnFunctionDeclarator(), castAs(), castAsArrayTypeUnsafe(), getArrayElementTypeNoTypeQual(), getAs(), getAsArrayTypeUnsafe(), getAsStructureType(), getAsUnionType(), clang::ASTContext::getTargetNullPointerValue(), clang::ASTContext::getUnqualifiedArrayType(), handleCallbackAttr(), clang::ento::iterator::isIteratorType(), IsPreserveAIArrayBase(), isValidBPFPreserveEnumValueArg(), and isValidBPFPreserveTypeInfoArg().
getVisibility()
Visibility clang::Type::getVisibility () const inline
Determine the visibility of this type.
Definition at line 2571 of file Type.h.
References getLinkageAndVisibility(), and clang::LinkageInfo::getVisibility().
hasAttr()
bool Type::hasAttr (attr::Kind AK) const
Determine whether this type had the specified attribute applied to it (looking through top-level type sugar).
Definition at line 1816 of file Type.cpp.
References getAs().
Referenced by clang::Sema::ActOnEnumBody(), isObjCInertUnsafeUnretainedType(), IsPreserveAIArrayBase(), clang::Expr::isUnusedResultAWarning(), and IsVectorConversion().
hasAutoForTrailingReturnType()
bool Type::hasAutoForTrailingReturnType () const
Determine whether this type was written with a leading 'auto' corresponding to a trailing return type (possibly for a nested function type within a pointer to function type or similar).
Definition at line 1933 of file Type.cpp.
Referenced by clang::Sema::FinalizeDeclaratorGroup().
hasFloatingRepresentation()
bool Type::hasFloatingRepresentation () const
Determine whether this type has a floating-point representation of some sort, e.g., it is a floating-point type or a vector thereof.
Definition at line 2175 of file Type.cpp.
References isFloatingType().
Referenced by clang::Sema::ActOnParenExpr(), canApplyNoFPClass(), checkArithmeticOrEnumeralCompare(), checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckSizelessVectorCompareOperands(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CheckVectorLogicalOperands(), diagnoseTautologicalComparison(), EmitCompare(), and handleTransparentUnionAttr().
hasIntegerRepresentation()
bool Type::hasIntegerRepresentation () const
Determine whether this type has an integer representation of some sort, e.g., it is an integer type or a vector.
Definition at line 1938 of file Type.cpp.
References clang::cast(), and isIntegerType().
Referenced by clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), clang::Sema::CreateBuiltinUnaryOp(), and clang::Sema::SemaBuiltinShuffleVector().
hasObjCPointerRepresentation()
bool clang::Type::hasObjCPointerRepresentation () const inline
Whether this type can represent an objective pointer type for the purpose of GC'ability.
Definition at line 7406 of file Type.h.
References isObjCObjectPointerType().
hasPointerRepresentation()
bool clang::Type::hasPointerRepresentation () const inline
Whether this type is represented natively as a pointer.
This includes pointers, references, block pointers, and Objective-C interface, qualified id, and qualified interface types, as well as nullptr_t.
Definition at line 7401 of file Type.h.
References isBlockPointerType(), isNullPtrType(), isObjCObjectPointerType(), isPointerType(), and isReferenceType().
Referenced by EvaluateBuiltinStrLen(), EvaluatePointer(), handleSwiftError(), ignorePointerCastsAndParens(), is32Or64BitBasicType(), and isValidSwiftContextType().
hasSignedIntegerRepresentation()
bool Type::hasSignedIntegerRepresentation () const
Determine whether this type has an signed integer representation of some sort, e.g., it is an signed integer type or a vector.
Definition at line 2103 of file Type.cpp.
References isSignedIntegerOrEnumerationType().
Referenced by actOnOMPReductionKindClause(), AnalyzeComparison(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), castValueToType(), checkOpenMPLoop(), checkPointerTypesForAssignment(), EmitCompare(), emitOMPAtomicCompareExpr(), clang::CodeGen::ABIArgInfo::getExtend(), handleIntegerConversion(), and clang::analyze_format_string::ArgType::matchesType().
hasSizedVLAType()
bool Type::hasSizedVLAType () const
Whether this type involves a variable-length array type with a definite size.
Definition at line 4641 of file Type.cpp.
References getAs(), getAsArrayTypeUnsafe(), and isVariablyModifiedType().
hasUnnamedOrLocalType()
bool Type::hasUnnamedOrLocalType () const
Whether this type is or contains a local or unnamed type.
Definition at line 4238 of file Type.cpp.
References clang::TypePropertyCache< Private >::ensure(), and TypeBits.
Referenced by clang::Sema::CheckTemplateArgument(), and getPointeeTypeText().
hasUnsignedIntegerRepresentation()
bool Type::hasUnsignedIntegerRepresentation () const
Determine whether this type has an unsigned integer representation of some sort, e.g., it is an unsigned integer type or a vector.
Definition at line 2153 of file Type.cpp.
References clang::cast(), and isUnsignedIntegerOrEnumerationType().
Referenced by checkOpenMPLoop(), and DiagnoseBadShiftValues().
isAggregateType()
bool Type::isAggregateType () const
Determines whether the type is a C++ aggregate type or C aggregate or union type.
An aggregate type is an array or a class type (struct, union, or class) that has no user-declared constructors, no private or protected non-static data members, no base classes, and no virtual functions (C++ [dcl.init.aggr]p1). The notion of an aggregate type subsumes the notion of C aggregates (C99 6.2.5p21) because it also includes union types.
Definition at line 2255 of file Type.cpp.
References clang::isa().
Referenced by clang::Sema::AddInitializerToDecl(), TryListConversion(), and TryListInitialization().
isAlignValT()
bool Type::isAlignValT () const
Definition at line 2950 of file Type.cpp.
References getAs(), and clang::IdentifierInfo::isStr().
Referenced by clang::Sema::AddAllocAlignAttr(), getUsualDeleteParams(), and clang::FunctionDecl::isReplaceableGlobalAllocationFunction().
isAnyCharacterType()
bool Type::isAnyCharacterType () const
Determine whether this type is any of the built-in character types.
Definition at line 2042 of file Type.cpp.
Referenced by clang::Sema::CheckCompatibleReinterpretCast(), diagnoseStringPlusChar(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::UserDefinedLiteral::getLiteralOperatorKind(), clang::Sema::IsIntegralPromotion(), and TryPrintAsStringLiteral().
isAnyComplexType()
bool clang::Type::isAnyComplexType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7034 of file Type.h.
References clang::isa().
Referenced by actOnOMPReductionKindClause(), checkArithmeticOrEnumeralCompare(), CheckIncrementDecrementOperand(), clang::Sema::CreateBuiltinUnaryOp(), EvaluateComparisonBinaryOperator(), EvaluateComplex(), FindDesignatorMismatch(), findSubobject(), isLiteralType(), IsStandardConversion(), TryListInitialization(), and clang::ento::ExprEngine::VisitUnaryOperator().
isAnyPointerType()
bool clang::Type::isAnyPointerType () const inline
Definition at line 6940 of file Type.h.
References isObjCObjectPointerType(), and isPointerType().
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), AreTypesCompatible(), AuditedType(), clang::tooling::buildAccess(), CastsAwayConstness(), clang::Sema::CheckAdditionOperands(), checkArithmeticBinOpPointerOperands(), checkArithmeticIncompletePointerType(), checkArithmeticNull(), checkArithmeticOpPointerOperand(), clang::Sema::CheckCompareOperands(), checkConditionalNullPointer(), CheckLValueConstantExpression(), checkMapConflicts(), clang::Sema::CheckMSVCRTEntryPoint(), checkNullabilityTypeSpecifier(), CheckOriginalCallArgDeduction(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckSubtractionOperands(), computeConditionalNullability(), convertPointersToCompositeType(), clang::Sema::deepTypeCheckForSYCLDevice(), diagnoseArithmeticOnTwoFunctionPointers(), DiagnoseBadFunctionCast(), DiagnoseCastQual(), diagnosePointerIncompatibility(), diagnoseStringPlusChar(), clang::ento::SMTConv::doTypeConversion(), clang::Sema::FindCompositePointerType(), clang::ento::SMTConv::fromCast(), clang::ento::SMTConv::getBinExpr(), getFuchsiaHandleSymbols(), clang::ASTContext::getObjCGCAttrKind(), clang::ASTContext::getObjCGCQualType(), clang::CXXMemberCallExpr::getRecordDecl(), getVariableCategoryFromDecl(), clang::ento::SMTConv::getZeroExpr(), handleRestrictAttr(), clang::Sema::isOpenMPCapturedByRef(), clang::StandardConversionSequence::isPointerConversionToVoidPointer(), isPointerToConst(), isPointerToConst(), clang::ASTContext::isSentinelNullExpr(), IsStandardConversion(), clang::Sema::isValidPointerAttrType(), threadSafetyCheckIsPointer(), TryReinterpretCast(), and clang::FunctionCallFilterCCC::ValidateCandidate().
isArithmeticType()
bool Type::isArithmeticType () const
Definition at line 2198 of file Type.cpp.
References clang::isa(), and isBitIntType().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::CheckAdditionOperands(), checkArithmeticOrEnumeralCompare(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DiagnosePropertyAccessorMismatch(), clang::ento::SMTConv::doTypeConversion(), isFundamentalType(), IsStandardConversion(), IsVectorConversion(), tryGCCVectorConvertAndSplat(), and clang::Sema::UsualArithmeticConversions().
isArrayType()
bool clang::Type::isArrayType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7002 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPDeclareReductionType(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPIsDevicePtrClause(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), buildUserDefinedMapperRef(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorType(), clang::Sema::BuiltinDecay(), canDecayToPointerType(), captureInBlock(), CheckArrow(), clang::Sema::CheckConversionDeclarator(), clang::interp::CheckFieldsInitialized(), checkForArray(), checkIsValidOpenCLKernelParameter(), checkNullabilityTypeSpecifier(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), CheckUnaryTypeTraitTypeCompleteness(), clang::Sema::ConstantFoldAttrArgs(), clang::CXXBindTemporaryExpr::Create(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateGenericSelectionExpr(), createReferenceTemporary(), DecodeTypeFromStr(), clang::Sema::deduceOpenCLAddressSpace(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::deepTypeCheckForSYCLDevice(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAssignmentResult(), diagnoseTautologicalComparison(), clang::Sema::DiagnoseUnusedExprResult(), doRewriteToUTF8StringBoxedExpressionHelper(), emitOMPArraySectionBase(), emitPrivatesInit(), emitReadOnlyPlacementAttrWarning(), clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner(), Evaluate(), EvaluateArray(), EvaluateArrayNewConstructExpr(), EvaluateArrayNewInitList(), EvaluateBinaryTypeTrait(), EvaluateInPlace(), clang::Sema::FinalizeVarWithDestructor(), FindDesignatorMismatch(), findSubobject(), clang::QualType::getBaseTypeIdentifier(), clang::ASTContext::GetBuiltinType(), getCoreType(), getOpenCLKernelParameterType(), getUuidAttrOfType(), handleLifetimeCategoryAttr(), handleLValueToRValueConversion(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::ASTNodeImporter::ImportFieldDeclDefinition(), isCompoundType(), clang::Expr::isConstantInitializer(), IsStandardConversion(), clang::QualType::isTriviallyEqualityComparableType(), clang::Expr::isUnusedResultAWarning(), isZeroSized(), clang::Sema::MergeVarDeclTypes(), needsAmpersandOnTemplateArg(), clang::InitializationSequence::Perform(), pushTemporaryCleanup(), rebuildPotentialResultsAsNonOdrUsed(), SemaBuiltinAlignment(), setObjCGCLValueClass(), tryDiagnoseOverloadedCast(), TryOrBuildParenListInitialization(), TryReferenceInit(), TryReferenceInitializationCore(), clang::interp::ByteCodeExprGen< Emitter >::visitInitializer(), visitLocalsRetainedByInitializer(), and clang::ento::ExprEngine::VisitMemberExpr().
isAtomicType()
bool clang::Type::isAtomicType () const inline
Definition at line 7077 of file Type.h.
References clang::isa().
Referenced by AnalyzeAssignment(), AnalyzeCompoundAssignment(), AnalyzeImplicitConversions(), clang::Sema::BuildAtomicExpr(), CheckBoolLikeConversion(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), diagnoseRedundantReturnTypeQualifiers(), EvaluateAtomic(), getOpenCLKernelParameterType(), and clang::InitializationSequence::Perform().
isBFloat16Type()
bool clang::Type::isBFloat16Type () const inline
Definition at line 7267 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::CheckConditionalOperands(), clang::Sema::checkTypeSupport(), and IsStandardConversion().
isBitIntType()
bool clang::Type::isBitIntType () const inline
Definition at line 7160 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnMSAsmStmt(), clang::Sema::AddModeAttr(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildVectorType(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkTypeSupport(), DetermineNoUndef(), DiagnoseBadShiftValues(), clang::CodeGen::ConstantEmitter::emitForMemory(), clang::ASTContext::getExtVectorType(), getIntegerWidthAndSignedness(), getScalarTypeKind(), clang::ASTContext::getVectorType(), isArithmeticType(), isIntegerType(), isIntegralOrEnumerationType(), isIntegralOrUnscopedEnumerationType(), isIntegralType(), isRealType(), and isScalarType().
isBlockCompatibleObjCPointerType()
bool Type::isBlockCompatibleObjCPointerType (ASTContext & ctx) const
Definition at line 4514 of file Type.cpp.
References getAs(), clang::ASTContext::getNSCopyingName(), and clang::ASTContext::getNSObjectName().
Referenced by applyObjCTypeArgs(), clang::Sema::CheckAssignmentConstraints(), and clang::Sema::CheckCompareOperands().
isBlockPointerType()
bool clang::Type::isBlockPointerType () const inline
Definition at line 6944 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnObjCForCollectionStmt(), applyObjCTypeArgs(), AuditedType(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildArrayType(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCBridgedCast(), CanThrow(), clang::ento::StoreManager::castRegion(), CastsAwayConstness(), checkArithmeticNull(), clang::Sema::CheckAssignmentConstraints(), checkBlockType(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompleteVariableDeclaration(), checkConditionalBlockPointerCompatibility(), checkConditionalNullPointer(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CheckObjCPropertyAttributes(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSubscriptingKind(), compareConversionFunctions(), clang::Sema::ConvertArgumentsForCall(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::Sema::DefaultVariadicArgumentPromotion(), DiagnoseBadFunctionCast(), diagnoseObjCARCConversion(), diagnoseTautologicalComparison(), DiagnoseUninitializedUse(), clang::ento::SMTConv::doTypeConversion(), clang::ento::SMTConv::fromCast(), clang::Sema::GatherArgumentsForCall(), clang::ASTContext::getByrefLifetime(), GetFullTypeForDeclarator(), clang::Decl::getFunctionType(), GetGCAttrTypeForType(), clang::ASTContext::getObjCGCAttrKind(), clang::ObjCPropertyDecl::getSetterKind(), clang::ento::CallEventManager::getSimpleCall(), clang::Sema::getVariadicCallType(), clang::ento::SMTConv::getZeroExpr(), handleAnalyzerNoReturnAttr(), handleRestrictAttr(), handleSentinelAttr(), handleSwiftAsyncAttr(), hasPointerRepresentation(), is32Or64BitBasicType(), isBlockPointer(), isCallback(), clang::CXXConversionDecl::isLambdaToBlockPointerConversion(), isObjCARCBridgableType(), isObjCRetainableType(), clang::Sema::IsPointerConversion(), IsStandardConversion(), clang::Sema::isValidPointerAttrType(), isVariableCapturable(), clang::analyze_format_string::ArgType::matchesType(), clang::Sema::maybeExtendBlockObject(), clang::ASTContext::mergeTypes(), clang::Sema::PerformImplicitConversion(), rewriteToObjCProperty(), SemaBuiltinDumpStruct(), shouldEmitSeparateBlockRetain(), SuggestInitializationFixit(), TryReinterpretCast(), and TryStaticCast().
isBooleanType()
bool clang::Type::isBooleanType () const inline
Definition at line 7370 of file Type.h.
Referenced by clang::Sema::ActOnGCCAsmStmt(), AddObjCKeyValueCompletions(), AddOrdinaryNameResults(), AnalyzeBitFieldAssignment(), clang::ento::SMTConstraintManager::assumeSym(), buildCoawaitCalls(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorType(), ChangeIntegralSignedness(), checkArithmeticOrEnumeralThreeWayCompare(), CheckConvertedConstantConversions(), clang::Sema::CheckEnumConstant(), CheckImplicitConversion(), CheckIncrementDecrementOperand(), checkIntToPointerCast(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), clang::Sema::CheckSingleAssignmentConstraints(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), create_OSAtomicCompareAndSwap(), clang::Sema::CreateOverloadedBinOp(), DiagnoseBadFunctionCast(), clang::Sema::DiagnoseStaticAssertDetails(), ExprLooksBoolean(), clang::ento::SMTConv::fromCast(), getIntegerWidthAndSignedness(), getOpenCLKernelParameterType(), clang::ento::SMTConstraintManager::getSymVal(), clang::ento::SMTConv::getZeroExpr(), HandleIntToIntCast(), handleVecTypeHint(), hasBooleanRepresentation(), clang::InitializationSequence::InitializeFrom(), isBooleanType(), clang::Sema::IsIntegralPromotion(), isIntOrBool(), clang::Expr::isKnownToHaveBooleanValue(), IsStandardConversion(), clang::ento::SMTConv::mkSort(), clang::Sema::PerformImplicitConversion(), clang::Sema::prepareVectorSplat(), clang::APValue::printPretty(), clang::ento::ConditionBRVisitor::printValue(), rewriteToNumericBoxedExpression(), TryListInitialization(), TryReinterpretCast(), TryStaticCast(), and clang::Sema::VerifyBitField().
isBuiltinType()
bool clang::Type::isBuiltinType () const inline
Helper methods to distinguish type categories.
All type predicates operate on the canonical type, ignoring typedefs and qualifiers. Returns true if the type is a builtin type.
Definition at line 7022 of file Type.h.
References clang::isa().
Referenced by clang::Sema::BuildVectorType(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::ASTContext::getExtVectorType(), clang::ASTContext::getVectorType(), handleIBOutletCollection(), and isTypeSubstitutable().
isCanonicalUnqualified()
bool clang::Type::isCanonicalUnqualified () const inline
Determines if this type would be canonical if it had no further qualification.
Definition at line 2023 of file Type.h.
References clang::ExtQualsTypeCommonBase::QualType.
Referenced by areCompatMatrixTypes(), areCompatVectorTypes(), clang::Sema::getCopyElisionCandidate(), clang::ASTContext::getMemberPointerType(), clang::QualType::isCanonical(), and clang::FunctionProtoType::Profile().
isCARCBridgableType()
bool Type::isCARCBridgableType () const
Determine whether the given type T is a "bridgeable" C type.
Definition at line 4618 of file Type.cpp.
References getAs(), getPointeeType(), isRecordType(), isVoidType(), and Pointer.
Referenced by clang::Sema::BuildObjCBridgedCast().
isChar16Type()
bool Type::isChar16Type () const
Definition at line 2028 of file Type.cpp.
Referenced by clang::Sema::BuiltinChangeSignedness(), and TryPrintAsStringLiteral().
isChar32Type()
bool Type::isChar32Type () const
Definition at line 2034 of file Type.cpp.
Referenced by TryPrintAsStringLiteral().
isChar8Type()
bool Type::isChar8Type () const
Definition at line 2022 of file Type.cpp.
Referenced by IsStringInit(), and TryPrintAsStringLiteral().
isCharType()
bool Type::isCharType () const
Definition at line 2006 of file Type.cpp.
Referenced by clang::Sema::CheckLoopHintExpr(), checkParamIsIntegerType(), checkPointerTypesForAssignment(), DiagnoseDivisionSizeofPointerOrArray(), clang::analyze_printf::PrintfSpecifier::fixType(), handleFormatArgAttr(), handleFormatAttr(), clang::Sema::IsIntegralPromotion(), clang::BinaryOperator::isNullPointerArithmeticExtension(), and IsStringInit().
isClassType()
bool Type::isClassType () const
Definition at line 563 of file Type.cpp.
References getAs().
isClkEventT()
bool clang::Type::isClkEventT () const inline
Definition at line 7137 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::CheckCompareOperands(), diagnoseOpenCLTypes(), isOpenCLSpecificType(), and SemaOpenCLBuiltinEnqueueKernel().
isComplexIntegerType()
bool Type::isComplexIntegerType () const
Definition at line 613 of file Type.cpp.
References getAsComplexIntegerType().
Referenced by clang::ento::SMTConstraintManager::canReasonAbout(), clang::Sema::CreateBuiltinUnaryOp(), DiagnoseBadFunctionCast(), handleIntegerToComplexFloatConversion(), handleIntToFloatConversion(), and clang::Sema::UsualArithmeticConversions().
isComplexType()
bool Type::isComplexType () const
isComplexType() does not include complex integers (a GCC extension).
isComplexIntegerType() can be used to test for complex integers.
Definition at line 607 of file Type.cpp.
Referenced by clang::Sema::AddModeAttr(), clang::ento::SMTConstraintManager::canReasonAbout(), clang::Sema::CreateBuiltinUnaryOp(), DiagnoseBadFunctionCast(), handleIntegerToComplexFloatConversion(), clang::Sema::UsualArithmeticConversions(), and clang::Sema::UsualUnaryConversions().
isCompoundType()
bool clang::Type::isCompoundType () const inline
Tests whether the type is categorized as a compound type.
Returns
True for types specified in C++0x [basic.compound].
Definition at line 6910 of file Type.h.
References isArrayType(), isEnumeralType(), isFunctionType(), isMemberPointerType(), isPointerType(), isRecordType(), isReferenceType(), and isUnionType().
isConstantArrayType()
bool clang::Type::isConstantArrayType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7006 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::deduceVarTypeFromInitializer(), EquivalentArrayTypes(), isQualificationConversionStep(), and clang::Value::Value().
isConstantMatrixType()
bool clang::Type::isConstantMatrixType () const inline
Definition at line 7056 of file Type.h.
References clang::isa().
Referenced by clang::Sema::CheckAdditionOperands(), clang::Sema::CheckMultiplyDivideOperands(), and clang::Sema::CheckSubtractionOperands().
isConstantSizeType()
bool Type::isConstantSizeType () const
Return true if this is not a variable sized type, according to the rules of C99 6.7.5p3.
isConstantSizeType - Return true if this is not a variable sized type, according to the rules of C99 6.7.5p3.
It is not legal to call this on incomplete types.
It is not legal to call this on incomplete types or dependent types.
Definition at line 2269 of file Type.cpp.
References clang::isa(), isDependentType(), and isIncompleteType().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList(), getAlignmentAndOffsetFromBinAddOrSub(), clang::ASTContext::getConstantArrayType(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), and HandleSizeof().
isCUDADeviceBuiltinSurfaceType()
bool Type::isCUDADeviceBuiltinSurfaceType () const
Check if the type is the CUDA device builtin surface type.
Check if the specified type is the CUDA device builtin surface type.
Definition at line 4628 of file Type.cpp.
References getAs().
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), and clang::Sema::IdentifyCUDATarget().
isCUDADeviceBuiltinTextureType()
bool Type::isCUDADeviceBuiltinTextureType () const
Check if the type is the CUDA device builtin texture type.
Check if the specified type is the CUDA device builtin texture type.
Definition at line 4635 of file Type.cpp.
References getAs().
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), and clang::Sema::IdentifyCUDATarget().
isDecltypeType()
bool clang::Type::isDecltypeType () const inline
Definition at line 7119 of file Type.h.
References clang::isa().
isDependentAddressSpaceType()
bool clang::Type::isDependentAddressSpaceType () const inline
Definition at line 7060 of file Type.h.
References clang::isa().
isDependentSizedArrayType()
bool clang::Type::isDependentSizedArrayType () const inline
Definition at line 7018 of file Type.h.
References clang::isa().
Referenced by EquivalentArrayTypes().
isDependentType()
bool clang::Type::isDependentType () const inline
Whether this type is a dependent type, meaning that its definition somehow depends on a template parameter (C++ [temp.dep.type]).
Definition at line 2345 of file Type.h.
References getDependence().
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFields(), clang::Sema::ActOnFinishCXXInClassMemberInitializer(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnInitializerError(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnSEHExceptBlock(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnStartOfObjCMethodDef(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAllocAlignAttr(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddModeAttr(), applyObjCTypeArgs(), clang::Sema::AttachBaseSpecifiers(), clang::Sema::BuildAsTypeExpr(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCaptureField(), clang::Sema::BuildClassMessage(), buildCoawaitCalls(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::buildCoroutinePromise(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildCXXUuidof(), buildDeclareReductionRef(), clang::Sema::BuildExceptionDeclaration(), buildLambdaScopeReturnType(), clang::Sema::BuildMatrixType(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildReturnStmt(), buildUserDefinedMapperRef(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVariableInstantiation(), clang::Sema::BuildVectorType(), canCaptureVariableByCopy(), clang::Sema::canFullyTypeCheckRedeclaration(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), clang::Sema::canThrow(), captureInLambda(), checkAcquireOrderAttrCommon(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::CheckAllocatedType(), checkArithmeticIncompletePointerType(), clang::Sema::checkArrayElementAlignment(), checkBuiltinTemplateIdType(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCompleteDecompositionDeclaration(), CheckConstexprFunctionBody(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckEnumRedeclaration(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckNonDependentConversions(), clang::Sema::CheckNontrivialField(), clang::Sema::CheckOMPThreadPrivateDecl(), checkOpenMPIterationSpace(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverload(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverrideControl(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkTypeSupport(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::DeduceAutoType(), clang::Sema::deduceClosureReturnType(), DeduceFromInitializerList(), deduceOpenCLPointeeAddrSpace(), DeduceTemplateArgumentsByTypeMatch(), clang::DependentCoawaitExpr::DependentCoawaitExpr(), DiagnoseDivisionSizeofPointerOrArray(), clang::Sema::DiagnoseSizeOfParametersAndReturnValue(), clang::Sema::DiagnoseUnusedNestedTypedefs(), EvaluateBinaryTypeTrait(), EvaluateVarDecl(), findTemplateParameter(), clang::Expr::getBestDynamicClassType(), clang::CallExpr::getCallReturnType(), clang::ASTContext::getConstantArrayType(), clang::Sema::getCopyElisionCandidate(), clang::ento::CallEvent::getDeclaredResultType(), clang::Sema::getDestructorName(), clang::Sema::getDestructorTypeForDecltype(), clang::ASTContext::getExtVectorType(), getFieldsFromClassHierarchy(), getOpenCLKernelParameterType(), clang::ASTContext::getTypeSizeInCharsIfKnown(), handleObjCPreciseLifetimeAttr(), HandleSizeof(), clang::CoroutineBodyStmt::hasDependentPromiseType(), hasRepeatedBaseClass(), clang::InitializationSequence::InitializeFrom(), IsAcceptableNonMemberOperatorCandidate(), isConstantSizeType(), clang::QualType::isCXX11PODType(), clang::Sema::isIncompatibleTypedef(), isIncompleteType(), isLiteralType(), isOverloadableType(), isStandardLayoutType(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTriviallyEqualityComparableType(), clang::QualType::isTrivialType(), isValidSubjectOfCFAttribute(), isValidSubjectOfNSAttribute(), isValidSubjectOfNSReturnsRetainedAttribute(), isValidSubjectOfOSAttribute(), isValidSwiftContextType(), isValidSwiftErrorResultType(), isValidSwiftIndirectResultType(), clang::Sema::isValidVarArgType(), LookupDirect(), clang::Sema::LookupTemplateName(), MatchTemplateParameterKind(), clang::Sema::MergeVarDeclTypes(), clang::InitializationSequence::Perform(), clang::Sema::PerformObjectMemberConversion(), clang::TreeTransform< Derived >::RebuildQualifiedType(), clang::Sema::SemaConvertVectorExpr(), clang::CXXRecordDecl::setBases(), TryToFixInvalidVariablyModifiedType(), VariableCanNeverBeAConstantExpression(), clang::Sema::VerifyBitField(), and clang::TextNodeDumper::VisitVarDecl().
isElaboratedTypeSpecifier()
bool Type::isElaboratedTypeSpecifier () const
Determine wither this type is a C++ elaborated-type-specifier.
Definition at line 3109 of file Type.cpp.
isEnumeralType()
bool clang::Type::isEnumeralType () const inline
Definition at line 7030 of file Type.h.
References clang::isa().
Referenced by AnalyzeBitFieldAssignment(), clang::Sema::BuildCXXNew(), clang::Sema::BuildExpressionFromIntegralTemplateArgument(), checkArithmeticOrEnumeralCompare(), checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), CheckIncrementDecrementOperand(), checkIntToPointerCast(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSwitchCondition(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckVectorConditionalTypes(), DiagnoseBadFunctionCast(), clang::QualType::getBaseTypeIdentifier(), getFixedEnumPromtion(), HasEnumType(), is32Or64BitBasicType(), IsAcceptableNonMemberOperatorCandidate(), isCompoundType(), isFundamentalType(), clang::Sema::IsIntegralPromotion(), isNullPointerConstantForConversion(), isOverloadableType(), clang::ASTContext::isPromotableBitField(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::QualType::isTriviallyEqualityComparableType(), isValidSizelessVectorForConditionalCondition(), isValidVectorForConditionalCondition(), clang::Sema::PerformOpenMPImplicitIntegerConversion(), tryGCCVectorConvertAndSplat(), TryStaticCast(), and clang::Sema::VerifyIntegerConstantExpression().
isEventT()
bool clang::Type::isEventT () const inline
Definition at line 7133 of file Type.h.
References isSpecificBuiltinType().
Referenced by diagnoseOpenCLTypes(), getOpenCLKernelParameterType(), isOpenCLSpecificType(), IsStandardConversion(), clang::InitializationSequence::Perform(), and TryOCLZeroOpaqueTypeInitialization().
isExtVectorBoolType()
bool clang::Type::isExtVectorBoolType () const inline
Definition at line 7046 of file Type.h.
References clang::cast(), and isExtVectorType().
Referenced by clang::Sema::CheckVectorOperands(), checkVectorShift(), and clang::Sema::GetSignedVectorType().
isExtVectorType()
bool clang::Type::isExtVectorType () const inline
Definition at line 7042 of file Type.h.
References clang::isa().
Referenced by clang::Sema::areLaxCompatibleVectorTypes(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckExtVectorCast(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorOperands(), convertVector(), clang::Sema::CreateBuiltinUnaryOp(), handleVecTypeHint(), clang::InitializationSequence::InitializeFrom(), isExtVectorBoolType(), isValidVectorForConditionalCondition(), IsVectorConversion(), clang::InitializationSequence::Perform(), clang::Sema::prepareVectorSplat(), and TryReinterpretCast().
isFixedPointOrIntegerType()
bool clang::Type::isFixedPointOrIntegerType () const inline
Return true if this is a fixed point or integer type.
Definition at line 7307 of file Type.h.
References isFixedPointType(), and isIntegerType().
Referenced by clang::Sema::CheckShiftOperands(), and handleFixedPointConversion().
isFixedPointType()
bool clang::Type::isFixedPointType () const inline
Return true if this is a fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
Definition at line 7299 of file Type.h.
Referenced by clang::Sema::CreateBuiltinBinOp(), DiagnoseBadFunctionCast(), DiagnoseBadShiftValues(), EvaluateAsFixedPoint(), EvaluateComparisonBinaryOperator(), EvaluateFixedPoint(), EvaluateFixedPointOrInteger(), clang::ASTContext::getCorrespondingSaturatedType(), clang::ASTContext::getFixedPointIBits(), clang::ASTContext::getFixedPointMax(), clang::ASTContext::getFixedPointMin(), clang::ASTContext::getFixedPointScale(), clang::ASTContext::getFixedPointSemantics(), handleFixedPointConversion(), handleFloatConversion(), isFixedPointOrIntegerType(), isUnsaturatedFixedPointType(), isUnsignedFixedPointType(), and clang::Sema::UsualArithmeticConversions().
isFloat128Type()
bool clang::Type::isFloat128Type () const inline
Definition at line 7271 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::checkTypeSupport().
isFloat16Type()
bool clang::Type::isFloat16Type () const inline
Definition at line 7263 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::checkTypeSupport(), and IsStandardConversion().
isFloatingType()
bool Type::isFloatingType () const
Definition at line 2166 of file Type.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddModeAttr(), clang::Sema::BuildAtomicExpr(), checkCondition(), checkEnumArithmeticConversions(), CheckImplicitConversion(), clang::Sema::CheckLogicalOperands(), PNaClABIInfo::classifyArgumentType(), EmitAtomicOp(), getAArch64PBV(), clang::UserDefinedLiteral::getLiteralOperatorKind(), handleVectorVectorBinOp(), handleVecTypeHint(), hasFloatingRepresentation(), clang::Sema::prepareVectorSplat(), rewriteToNumberLiteral(), TryListInitialization(), unsupportedTypeConversion(), clang::Sema::UsualUnaryConversions(), clang::interp::ByteCodeExprGen< Emitter >::VisitBinaryOperator(), clang::interp::ByteCodeExprGen< Emitter >::VisitCompoundAssignOperator(), clang::interp::ByteCodeExprGen< Emitter >::VisitFloatCompoundAssignOperator(), and clang::ento::ExprEngine::VisitUnaryOperator().
isFromAST()
bool clang::Type::isFromAST () const inline
Whether this type comes from an AST file.
Definition at line 2000 of file Type.h.
References TypeBits.
isFunctionNoProtoType()
bool clang::Type::isFunctionNoProtoType () const inline
Definition at line 2181 of file Type.h.
References getAs().
Referenced by clang::Sema::ActOnFunctionDeclarator(), checkCastFunctionType(), clang::Sema::checkOpenMPDeclareVariantFunction(), and setPrototype().
isFunctionPointerType()
bool clang::Type::isFunctionPointerType () const inline
Definition at line 6970 of file Type.h.
References getAs().
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), CanThrow(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), checkPointerTypesForAssignment(), DiagnoseCallingConvCast(), diagnoseOpenCLTypes(), clang::Decl::getFunctionType(), getPointeeTypeText(), handleAnalyzerNoReturnAttr(), handleCallbackAttr(), handleSentinelAttr(), isCallback(), clang::Decl::isFunctionPointerType(), clang::QualType::isWebAssemblyFuncrefType(), maybeDiagnoseAssignmentToFunction(), ResolveOverloadForDeduction(), rewriteToObjCProperty(), SemaBuiltinAlignment(), SemaBuiltinDumpStruct(), SemaBuiltinLaunder(), TryConstCast(), and TryReinterpretCast().
isFunctionProtoType()
bool clang::Type::isFunctionProtoType () const inline
Definition at line 2182 of file Type.h.
References getAs().
Referenced by clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CreateBuiltin(), CreateNewFunctionDecl(), FindPossiblePrototype(), clang::FunctionType::getFastTypeQuals(), clang::MemberPointerType::isMemberDataPointer(), clang::MemberPointerType::isMemberFunctionPointer(), clang::Sema::MergeVarDeclExceptionSpecs(), clang::InitializationSequence::Perform(), and setPrototype().
isFunctionReferenceType()
bool clang::Type::isFunctionReferenceType () const inline
Definition at line 6977 of file Type.h.
References getAs().
Referenced by checkCastFunctionType(), diagnoseOpenCLTypes(), and clang::Decl::getFunctionType().
isFunctionType()
bool clang::Type::isFunctionType () const inline
Definition at line 6932 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFields(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPDeclareReductionType(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuiltinDecay(), clang::Sema::CallExprUnaryConversions(), canDecayToPointerType(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAllocatedType(), checkArithmeticBinOpPointerOperands(), checkArithmeticNull(), checkArithmeticOpPointerOperand(), CheckArrow(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckConversionDeclarator(), clang::Sema::checkOpenMPDeclareVariantFunction(), CheckOriginalCallArgDeduction(), clang::Sema::CheckPointerConversion(), checkPointerTypesForAssignment(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentIsCompatibleWithParameter(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), ClassifyBinaryOp(), clang::Sema::CompareReferenceRelationship(), clang::Sema::ConstantFoldAttrArgs(), clang::Sema::CreateBuiltinArraySubscriptExpr(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::DefaultFunctionArrayConversion(), determineEndOffset(), emitPointerArithmetic(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), EvaluateLValue(), FindConversionForRefInit(), clang::ASTContext::getObjCEncodingForBlock(), clang::ASTContext::getObjCEncodingForFunctionDecl(), clang::ASTContext::getObjCEncodingForMethodDecl(), HandleAddressSpaceTypeAttribute(), clang::Sema::HandleDeclarator(), HandleOperatorNewCall(), HandleSizeof(), clang::Sema::IgnoredValueConversions(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), isCompoundType(), clang::Declarator::isDeclarationOfFunction(), isIncompleteOrObjectType(), IsModifiable(), isObjectType(), clang::Sema::IsPointerConversion(), IsStandardConversion(), maybeDiagnoseAssignmentToFunction(), maybeSynthesizeBlockSignature(), clang::ASTContext::mergeObjCGCQualifiers(), clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate(), ResolveOverloadForDeduction(), SemaBuiltinDumpStruct(), SemaBuiltinLaunder(), TryReferenceInit(), TryReferenceInitializationCore(), TryRefInitWithConversionFunction(), and TryStaticCast().
isFundamentalType()
bool clang::Type::isFundamentalType () const inline
Tests whether the type is categorized as a fundamental type.
Returns
True for types specified in C++0x [basic.fundamental].
Definition at line 6899 of file Type.h.
References isArithmeticType(), isEnumeralType(), isNullPtrType(), and isVoidType().
isHalfType()
bool clang::Type::isHalfType () const inline
Definition at line 7258 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::BuildFunctionType(), clang::Sema::CheckAssignmentOperands(), checkIsValidOpenCLKernelParameter(), clang::Sema::CreateBuiltinUnaryOp(), diagnoseOpenCLTypes(), GetFullTypeForDeclarator(), getOpenCLKernelParameterType(), handleFloatConversion(), IsStandardConversion(), clang::Sema::PerformImplicitConversion(), and clang::Sema::UsualUnaryConversions().
isIbm128Type()
bool clang::Type::isIbm128Type () const inline
Definition at line 7275 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::checkTypeSupport().
isImageType()
bool clang::Type::isImageType () const inline
Definition at line 7149 of file Type.h.
Referenced by clang::Sema::BuildArrayType(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), diagnoseOpenCLTypes(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getOpenCLKernelParameterType(), HandleOpenCLAccessAttr(), and isOpenCLSpecificType().
isIncompleteArrayType()
bool clang::Type::isIncompleteArrayType () const inline
Definition at line 7010 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnUninitializedDecl(), CheckUnaryTypeTraitTypeCompleteness(), clang::computeDependence(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), DiagnoseRetainableFlexibleArrayMember(), DiagnoseVariableSizedIvars(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), clang::Sema::getCompletedType(), hasCompatibleArrayTypes(), isQualificationConversionStep(), clang::ASTContext::isSameEntity(), clang::Sema::MergeVarDeclTypes(), clang::InitializationSequence::Perform(), setUsedBits(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), and TryOrBuildParenListInitialization().
isIncompleteOrObjectType()
bool clang::Type::isIncompleteOrObjectType () const inline
Return true if this is an incomplete or object type, in other words, not a function type.
Definition at line 2090 of file Type.h.
References isFunctionType().
Referenced by clang::Sema::BuildQualifiedType(), checkConditionalObjectPointersCompatibility(), checkPointerTypesForAssignment(), clang::Sema::CheckTemplateArgument(), clang::Sema::IsPointerConversion(), and TryStaticCast().
isIncompleteType()
bool Type::isIncompleteType (NamedDecl ** Def = nullptr) const
Types are partitioned into 3 broad categories (C99 6.2.5p1): object types, function types, and incomplete types.
isIncompleteType - Return true if this is an incomplete type (C99 6.2.5p1)
Return true if this is an incomplete type. A type that can describe objects, but which lacks information needed to determine its size (e.g. void, or a fwd declared struct). Clients of this routine will need to determine if the size is actually required.
Def If non-null, and the type refers to some kind of declaration that can be completed (such as a C struct, C++ class, or Objective-C class), will be set to the declaration.
a type that can describe objects, but which lacks information needed to determine its size.
Definition at line 2279 of file Type.cpp.
References clang::cast(), Enum, getAsCXXRecordDecl(), clang::Decl::getASTContext(), clang::TargetInfo::getCXXABI(), clang::CXXRecordDecl::getMostRecentNonInjectedDecl(), clang::ASTContext::getTargetInfo(), clang::Decl::hasAttr(), clang::ObjCInterfaceDecl::hasDefinition(), clang::EnumDecl::isComplete(), clang::TagDecl::isCompleteDefinition(), isDependentType(), clang::TargetCXXABI::isMicrosoft(), and isVoidType().
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnOMPArrayShapingExpr(), clang::Sema::BuildCaptureField(), calculateOffset(), clang::ento::StoreManager::castRegion(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::checkArrayElementAlignment(), clang::Sema::CheckCallReturnType(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCompareOperands(), clang::Sema::checkDeclIsAllowedInOpenMPTarget(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckFunctionDeclaration(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), determineEndOffset(), clang::InitializationSequence::Diagnose(), DiagnoseBadConversion(), DiagnoseForRangeVariableCopies(), EvaluateComparisonBinaryOperator(), clang::CodeGen::CodeGenTBAA::getAccessInfo(), clang::ento::ElementRegion::getAsArrayOffset(), clang::ASTContext::getConstantArrayType(), clang::ASTContext::getDeclAlign(), getFieldsFromClassHierarchy(), clang::ento::MemRegionManager::getStaticSize(), clang::ASTContext::getTypeSizeInCharsIfKnown(), HandleOperatorNewCall(), handlePackedAttr(), handleTransparentUnionAttr(), isConstantSizeType(), clang::QualType::isCXX11PODType(), isLiteralType(), isOnePastTheEndOfCompleteObject(), isStandardLayoutType(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTriviallyEqualityComparableType(), clang::QualType::isTriviallyRelocatableType(), clang::Sema::isValidVarArgType(), isZeroSized(), clang::Sema::LookupTemplateName(), matchTypes(), TryToFixInvalidVariablyModifiedType(), and clang::ASTNodeImporter::VisitTypedefNameDecl().
isInstantiationDependentType()
bool clang::Type::isInstantiationDependentType () const inline
Determine whether this type is an instantiation-dependent type, meaning that the type involves a template parameter (even if the definition does not actually depend on the type substituted for that template parameter).
Definition at line 2353 of file Type.h.
References getDependence().
Referenced by clang::Sema::ActOnOpenMPCopyinClause(), buildDeclareReductionRef(), clang::Sema::BuildResolvedCallExpr(), buildUserDefinedMapperRef(), clang::Sema::CheckOMPThreadPrivateDecl(), clang::Sema::CheckTemplateArgument(), clang::computeDependence(), clang::computeDependence(), getCommonNonSugarTypeNode(), clang::Sema::HandleFunctionTypeMismatch(), handleGlobalAttr(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::DeclarationNameInfo::isInstantiationDependent(), and clang::Sema::SubstType().
isIntegerType()
bool clang::Type::isIntegerType () const inline
isIntegerType() does not include complex integers (a GCC extension).
isComplexIntegerType() can be used to test for complex integers.
Definition at line 7286 of file Type.h.
References isBitIntType(), clang::IsEnumDeclComplete(), and clang::IsEnumDeclScoped().
Referenced by clang::Sema::ActOnGCCAsmStmt(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCanonicalLoop(), clang::Sema::ActOnSEHExceptBlock(), AddObjCKeyValueCompletions(), clang::ASTContext::areLaxCompatibleRVVTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildVectorType(), castValueToType(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), CheckImplicitConversion(), CheckIncrementDecrementOperand(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), checkOpenCLConditionVector(), checkOpenCLEnqueueIntType(), checkOpenMPIterationSpace(), checkParamIsIntegerType(), checkPointerIntegerMismatch(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckSubtractionOperands(), clang::Sema::checkTypeSupport(), clang::Sema::CheckVectorOperands(), CheckWasmBuiltinArgIsInteger(), convertVector(), create_dispatch_once(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAssignmentEnum(), DiagnoseBadFunctionCast(), diagnoseStringPlusChar(), EvaluateFixedPointOrInteger(), expandStringLiteral(), extractStringLiteralCharacter(), getAArch64PBV(), clang::ASTContext::getFixedPointSemantics(), getIntegerWidthAndSignedness(), clang::UserDefinedLiteral::getLiteralOperatorKind(), getUsualDeleteParams(), handleIntegerToComplexFloatConversion(), handleIntToFloatConversion(), handleVectorVectorBinOp(), hasIntegerRepresentation(), isAcceptableMethodMismatch(), isFixedPointOrIntegerType(), clang::Sema::IsIntegralPromotion(), isIntOrBool(), isKnownToHaveUnsignedValue(), clang::BinaryOperator::isNullPointerArithmeticExtension(), isNullPointerConstantForConversion(), clang::InitListExpr::isStringLiteralInit(), mergeEnumWithInteger(), OpenCLArithmeticConversions(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), PromotionIsPotentiallyEligibleForImplicitIntegerConversionCheck(), SemaBuiltinAnnotation(), SemaBuiltinOverflow(), SemaBuiltinRWPipe(), SemaOpenCLBuiltinEnqueueKernel(), tryVectorConvertAndSplat(), and clang::interp::ByteCodeExprGen< Emitter >::VisitPointerArithBinOp().
isIntegralOrEnumerationType()
bool clang::Type::isIntegralOrEnumerationType () const inline
Determine whether this type is an integral or enumeration type.
Definition at line 7357 of file Type.h.
References isBitIntType(), and clang::IsEnumDeclComplete().
Referenced by clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddModeAttr(), BuildConvertedConstantExpression(), clang::Sema::CheckCaseExpression(), CheckICE(), clang::Sema::CheckMSVCRTEntryPoint(), clang::Sema::CheckSubscriptingKind(), clang::Sema::CheckSwitchCondition(), clang::Sema::CheckTemplateArgument(), conjureOffsetSymbolOnLocation(), DecodeTypeFromStr(), clang::ento::SMTConv::doTypeConversion(), EmitCompare(), EvaluateAsInt(), EvaluateComparisonBinaryOperator(), EvaluateIntegerOrLValue(), clang::Sema::FinalizeDeclaration(), clang::ento::SMTConv::fromCast(), getBuiltinAlignArguments(), clang::CodeGen::ABIArgInfo::getExtend(), getPreferredTypeOfBinaryRHS(), clang::CodeGen::ABIArgInfo::getSignExtend(), clang::ento::SMTConv::getZeroExpr(), clang::CodeGen::ABIArgInfo::getZeroExtend(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::ObjCSubscriptRefExpr::isArraySubscriptRefExpr(), clang::Expr::isKnownToHaveBooleanValue(), clang::Sema::isLaxVectorConversion(), clang::ASTContext::isMSStaticDataMemberInlineDefinition(), clang::Sema::prepareVectorSplat(), clang::ento::ConditionBRVisitor::printValue(), TryReinterpretCast(), TryStaticCast(), and clang::Sema::VerifyBitField().
isIntegralOrUnscopedEnumerationType()
bool Type::isIntegralOrUnscopedEnumerationType () const
Determine whether this type is an integral or unscoped enumeration type.
Definition at line 1988 of file Type.cpp.
References isBitIntType(), and isUnscopedEnumerationType().
Referenced by adjustBlockReturnsToEnum(), clang::Sema::BuildArrayType(), checkArraySize(), clang::Sema::CheckBitwiseOperands(), CheckConvertedConstantConversions(), clang::Sema::CreateOverloadedBinOp(), diagnoseStringPlusInt(), EvaluateCPlusPlus11IntegralConstantExpr(), getDependentArraySubscriptType(), clang::StandardConversionSequence::getNarrowingKind(), IsStandardConversion(), TryListInitialization(), clang::Sema::UsualUnaryConversions(), and clang::Sema::VerifyIntegerConstantExpression().
isIntegralType()
bool Type::isIntegralType (const ASTContext & Ctx) const
Determine whether this type is an integral type.
This routine determines whether the given type is an integral type per C++ [basic.fundamental]p7. Although the C standard does not define the term "integral type", it has a similar term "integer type", and in C++ the two terms are equivalent. However, C's "integer type" includes enumeration types, while C++'s "integer type" does not. The ASTContext parameter is used to determine whether we should be following the C or C++ rules when determining whether this type is an integral/integer type.
For cases where C permits "an integer type" and C++ permits "an integral type", use this routine.
For cases where C permits "an integer type" and C++ permits "an integral or enumeration type", use isIntegralOrEnumerationType() instead.
Parameters
Ctx The context in which this type occurs.
Returns
true if the type is considered an integral type, false otherwise.
Definition at line 1975 of file Type.cpp.
References clang::ASTContext::getLangOpts(), and isBitIntType().
Referenced by clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddAllocAlignAttr(), argTypeIsABIEquivalent(), checkBuiltinTemplateIdType(), checkIntToPointerCast(), clang::Sema::CheckObjCConversion(), checkSwiftAsyncErrorBlock(), clang::Sema::CheckVectorCast(), create_OSAtomicCompareAndSwap(), DiagnoseBinOpPrecedence(), clang::StandardConversionSequence::getNarrowingKind(), handleSwiftError(), handleVecTypeHint(), clang::Expr::IgnoreParenNoopCasts(), clang::Sema::IsIntegralPromotion(), IsStandardConversion(), isValidSizelessVectorForConditionalCondition(), isValidVectorForConditionalCondition(), tryGCCVectorConvertAndSplat(), TryReinterpretCast(), TryStaticCast(), and tryVectorConvertAndSplat().
isInterfaceType()
bool Type::isInterfaceType () const
Definition at line 581 of file Type.cpp.
References getAs().
isLinkageValid()
bool Type::isLinkageValid () const
True if the computed linkage is valid.
Used for consistency checking. Should always return true.
Definition at line 4320 of file Type.cpp.
References clang::LinkageComputer::computeTypeLinkageInfo(), getCanonicalTypeInternal(), clang::LinkageInfo::getLinkage(), and TypeBits.
isLiteralType()
bool Type::isLiteralType (const ASTContext & Ctx) const
Return true if this is a literal type (C++11 [basic.types]p10)
Definition at line 2772 of file Type.cpp.
References getAs(), getBaseElementTypeUnsafe(), getCanonicalTypeInternal(), clang::ASTContext::getLangOpts(), isAnyComplexType(), isDependentType(), isIncompleteType(), isReferenceType(), isScalarType(), isVariableArrayType(), isVectorType(), and isVoidType().
Referenced by clang::Sema::AddInitializerToDecl(), CheckLiteralType(), and clang::MaterializeTemporaryExpr::isUsableInConstantExpressions().
isLValueReferenceType()
bool clang::Type::isLValueReferenceType () const inline
Definition at line 6952 of file Type.h.
References clang::isa().
Referenced by alignReferenceTypes(), clang::Sema::CheckTemplateArgument(), checkTupleLikeDecomposition(), create_call_once_funcptr_call(), createPrivatesRecordDecl(), DeduceTemplateArgumentsByTypeMatch(), DiagnoseCastQual(), emitTaskPrivateMappingFunction(), FindConversionForRefInit(), clang::ento::ExprEngine::handleLValueBitCast(), implicitObjectParamIsLifetimeBound(), clang::CXXConstructorDecl::isCopyConstructor(), isRelevantAttr(), isStructuralType(), clang::InitializationSequence::Perform(), TryListConversion(), TryReferenceInitializationCore(), and TryRefInitWithConversionFunction().
isMatrixType()
bool clang::Type::isMatrixType () const inline
Definition at line 7052 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::areMatrixTypesOfTheSameDimension(), clang::Sema::CheckMatrixCast(), and TryStaticCast().
isMemberDataPointerType()
bool clang::Type::isMemberDataPointerType () const inline
Definition at line 6995 of file Type.h.
References getAs().
Referenced by EvaluateBuiltinClassifyType().
isMemberFunctionPointerType()
bool clang::Type::isMemberFunctionPointerType () const inline
Definition at line 6988 of file Type.h.
References getAs().
Referenced by clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), checkCastFunctionType(), diagnoseOpenCLTypes(), ResolveOverloadForDeduction(), and TryConstCast().
isMemberPointerType()
bool clang::Type::isMemberPointerType () const inline
Definition at line 6984 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnGCCAsmStmt(), AddOrdinaryNameResults(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), CastsAwayConstness(), checkArithmeticNull(), clang::Sema::CheckCompareOperands(), checkNullabilityTypeSpecifier(), CheckOriginalCallArgDeduction(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentPointerToMember(), CompareDerivedToBaseConversions(), convertPointersToCompositeType(), DeduceNullPtrTemplateArgument(), clang::Sema::DeduceTemplateArguments(), DetermineNoUndef(), EvaluateComparisonBinaryOperator(), EvaluateMemberPointer(), clang::Sema::FindCompositePointerType(), clang::Sema::HandleFunctionTypeMismatch(), handleMSPointerTypeQualifierAttr(), clang::Sema::handlerCanCatch(), isCompoundType(), IsStandardConversion(), needsAmpersandOnTemplateArg(), TryConstCast(), TryReinterpretCast(), and clang::Value::Value().
isNonOverloadPlaceholderType()
bool clang::Type::isNonOverloadPlaceholderType () const inline
Test for a placeholder type other than Overload; see BuiltinType::isNonOverloadPlaceholderType.
Definition at line 7248 of file Type.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnOMPArraySectionExpr(), and clang::Sema::checkPseudoObjectAssignment().
isNothrowT()
bool Type::isNothrowT () const
Definition at line 2941 of file Type.cpp.
References getAsCXXRecordDecl(), clang::NamedDecl::getIdentifier(), clang::Decl::isInStdNamespace(), and clang::IdentifierInfo::isStr().
Referenced by HandleOperatorNewCall(), and clang::FunctionDecl::isReplaceableGlobalAllocationFunction().
isNullPtrType()
bool clang::Type::isNullPtrType () const inline
Definition at line 7279 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), CheckConvertedConstantConversions(), clang::Sema::CheckMSVCRTEntryPoint(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), DetermineNoUndef(), DiagnoseNullConversion(), clang::Sema::diagnoseZeroToNullptrConversion(), clang::ento::SMTConv::doTypeConversion(), EvaluateComparisonBinaryOperator(), clang::Sema::FindCompositePointerType(), clang::ASTContext::getTargetNullPointerValue(), clang::Sema::handlerCanCatch(), hasPointerRepresentation(), clang::InitializationSequence::InitializeFrom(), isFundamentalType(), isNullPointerValueTemplateArgument(), clang::Sema::IsPointerConversion(), clang::ASTContext::isSentinelNullExpr(), clang::analyze_format_string::ArgType::matchesType(), TryContextuallyConvertToBool(), and TryReinterpretCast().
isObjCARCBridgableType()
bool Type::isObjCARCBridgableType () const
Determine whether the given type T is a "bridgable" Objective-C type, which is either an Objective-C object pointer type or an.
Definition at line 4613 of file Type.cpp.
References isBlockPointerType(), and isObjCObjectPointerType().
Referenced by clang::Sema::BuildObjCBridgedCast().
isObjCARCImplicitlyUnretainedType()
bool Type::isObjCARCImplicitlyUnretainedType () const
Determines if this type, which must satisfy isObjCLifetimeType(), is implicitly __unsafe_unretained rather than implicitly __strong.
Definition at line 4553 of file Type.cpp.
References getCanonicalTypeInternal(), clang::QualType::getTypePtr(), and isObjCLifetimeType().
Referenced by checkARCPropertyImpl(), clang::Sema::CheckObjCPropertyAttributes(), getObjCARCImplicitLifetime(), inferARCWriteback(), and clang::Sema::MaybeBindToTemporary().
isObjCBoxableRecordType()
bool Type::isObjCBoxableRecordType () const
Definition at line 575 of file Type.cpp.
References getAs().
isObjCBuiltinType()
bool clang::Type::isObjCBuiltinType () const inline
Definition at line 7115 of file Type.h.
References isObjCClassType(), isObjCIdType(), and isObjCSelType().
Referenced by AuditedType(), clang::ASTContext::canAssignObjCInterfacesInBlockPointer(), checkObjCPointerTypesForAssignment(), clang::Sema::FindCompositeObjCPointerType(), and clang::Sema::isObjCPointerConversion().
isObjCClassOrClassKindOfType()
bool Type::isObjCClassOrClassKindOfType () const
Whether the type is Objective-C 'Class' or a __kindof type of an Class type, e.g., __kindof Class <NSCopying>.
Unlike isObjCIdOrObjectKindOfType, there is no relevant bound here because Objective-C's type system cannot express "a class object for a subclass of NSFoo".
Definition at line 712 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage().
isObjCClassType()
bool clang::Type::isObjCClassType () const inline
Definition at line 7103 of file Type.h.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage(), clang::Sema::CheckAssignmentConstraints(), checkObjCPointerTypesForAssignment(), clang::Sema::CheckObjCPropertyAttributes(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::FindCompositeObjCPointerType(), findMethodDecl(), getBaseMessageSendResultType(), clang::Sema::getMessageSendResultType(), isObjCBuiltinType(), and clang::Sema::SelectorsForTypoCorrection().
isObjCIdOrObjectKindOfType()
bool Type::isObjCIdOrObjectKindOfType (const ASTContext & ctx, const ObjCObjectType *& bound) const
Whether the type is Objective-C 'id' or a __kindof type of an object type, e.g., __kindof NSView * or __kindof id <NSCopying>.
Parameters
bound Will be set to the bound on non-id subtype types, which will be (possibly specialized) Objective-C class type, or null for 'id.
Definition at line 686 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage().
isObjCIdType()
bool clang::Type::isObjCIdType () const inline
Definition at line 7097 of file Type.h.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage(), BuildSimilarlyQualifiedPointerType(), clang::ento::RetainSummaryManager::canEval(), clang::Sema::CheckAssignmentConstraints(), CheckObjCBridgeNSCast(), clang::Sema::CheckSubscriptingKind(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::FindCompositeObjCPointerType(), findMethodDecl(), clang::ObjCMethodDecl::getMethodFamily(), handleIBOutletCollection(), hasIsEqualMethod(), isObjCBuiltinType(), clang::ASTContext::mergeTypes(), and clang::Sema::SelectorsForTypoCorrection().
isObjCIndependentClassType()
bool Type::isObjCIndependentClassType () const
Definition at line 4578 of file Type.cpp.
References getAs(), and clang::ast_matchers::typedefType.
Referenced by clang::Sema::ActOnMethodDeclaration().
isObjCIndirectLifetimeType()
bool Type::isObjCIndirectLifetimeType () const
Definition at line 4590 of file Type.cpp.
References getAs(), and isObjCLifetimeType().
isObjCInertUnsafeUnretainedType()
bool clang::Type::isObjCInertUnsafeUnretainedType () const inline
Was this type written with the special inert-in-ARC __unsafe_unretained qualifier?
This approximates the answer to the following question: if this translation unit were compiled in ARC, would this type be qualified with __unsafe_unretained?
Definition at line 2236 of file Type.h.
References hasAttr().
isObjCLifetimeType()
bool Type::isObjCLifetimeType () const
Returns true if objects of this type have lifetime semantics under ARC.
Definition at line 4604 of file Type.cpp.
References getAsArrayTypeUnsafe(), and isObjCRetainableType().
Referenced by clang::Sema::BuildCXXNew(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckAllocatedType(), createObjCPropertyGetter(), DeduceTemplateArgumentsByTypeMatch(), DiagnoseRetainableFlexibleArrayMember(), handleObjCPreciseLifetimeAttr(), isObjCARCImplicitlyUnretainedType(), isObjCIndirectLifetimeType(), clang::Sema::isObjCWritebackConversion(), and clang::Sema::isValidVarArgType().
isObjCNSObjectType()
bool Type::isObjCNSObjectType () const
Definition at line 4572 of file Type.cpp.
References getAs(), and clang::ast_matchers::typedefType.
Referenced by clang::ASTContext::isObjCNSObjectType(), isObjCRetainableType(), and isValidSubjectOfNSAttribute().
isObjCObjectOrInterfaceType()
bool clang::Type::isObjCObjectOrInterfaceType () const inline
Definition at line 7072 of file Type.h.
References clang::isa().
Referenced by clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CompareReferenceRelationship(), and clang::Sema::LookupTemplateName().
isObjCObjectPointerType()
bool clang::Type::isObjCObjectPointerType () const inline
Definition at line 7064 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnFields(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCTypeParam(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddKnownFunctionAttributes(), AddObjCKeyValueCompletions(), adjustReturnValue(), AuditedType(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildObjCAtThrowStmt(), clang::ento::StoreManager::castRegion(), clang::Sema::CheckAdditionOperands(), checkArithmeticOnObjCPointer(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckFunctionDeclaration(), CheckIncrementDecrementOperand(), clang::Sema::CheckMessageArgumentTypes(), checkMethodFamilyMismatch(), checkNullabilityTypeSpecifier(), clang::Sema::CheckObjCARCUnavailableWeakConversion(), checkObjCPointerIntrospection(), clang::Sema::CheckObjCPropertyAttributes(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::DiagnoseAssignmentResult(), clang::ento::SMTConv::doTypeConversion(), emitBadConversionNotes(), EmitPointerWithAlignment(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), clang::CodeGen::CodeGenModule::GetAddrOfRTTIDescriptor(), clang::ASTContext::getByrefLifetime(), GetGCAttrTypeForType(), clang::ASTContext::getObjCGCAttrKind(), hasIsEqualMethod(), hasObjCPointerRepresentation(), hasPointerRepresentation(), isAnyPointerType(), clang::ento::cocoa::isCocoaObjectRef(), isObjCARCBridgableType(), isObjCPointer(), isObjCRetainableType(), clang::Sema::IsPointerConversion(), isValidSubjectOfNSAttribute(), clang::analyze_format_string::ArgType::matchesType(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), clang::Sema::MergeVarDeclTypes(), clang::ento::ConditionBRVisitor::patternMatch(), clang::Sema::PerformImplicitConversion(), clang::ento::ConditionBRVisitor::printValue(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::Sema::SelectorsForTypoCorrection(), clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(), TryConstCast(), tryEmitSpecializedAllocInit(), tryGenerateSpecializedMessageSend(), TryReinterpretCast(), TryStaticCast(), and validateBoxingMethod().
isObjCObjectType()
bool clang::Type::isObjCObjectType () const inline
Definition at line 7068 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::actOnObjCTypeParam(), CastsAwayConstness(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAssignmentOperands(), clang::Sema::checkVariadicArgument(), handleIBOutletCollection(), inferARCWriteback(), clang::Sema::isValidVarArgType(), transferARCOwnership(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
isObjCQualifiedClassType()
bool clang::Type::isObjCQualifiedClassType () const inline
Definition at line 7091 of file Type.h.
References getAs().
Referenced by clang::Sema::BuildInstanceMessage(), checkObjCPointerTypesForAssignment(), clang::Sema::CheckObjCPropertyAttributes(), clang::Sema::CodeCompleteObjCInstanceMessage(), getBaseMessageSendResultType(), and clang::Sema::SelectorsForTypoCorrection().
isObjCQualifiedIdType()
bool clang::Type::isObjCQualifiedIdType () const inline
Definition at line 7085 of file Type.h.
References getAs().
Referenced by BuildSimilarlyQualifiedPointerType(), checkObjCPointerTypesForAssignment(), clang::Sema::DiagnoseAssignmentResult(), clang::ASTContext::ObjCObjectAdoptsQTypeProtocols(), clang::ASTContext::QIdProtocolsAdoptObjCObjectProtocols(), and clang::Sema::SelectorsForTypoCorrection().
isObjCQualifiedInterfaceType()
bool Type::isObjCQualifiedInterfaceType () const
Definition at line 1744 of file Type.cpp.
References getAsObjCQualifiedInterfaceType().
isObjCRetainableType()
bool Type::isObjCRetainableType () const
Definition at line 4584 of file Type.cpp.
References isBlockPointerType(), isObjCNSObjectType(), and isObjCObjectPointerType().
Referenced by clang::Sema::ActOnPropertyImplDecl(), AdjustObjCObjectType(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildInstanceMessage(), clang::Sema::CheckObjCPropertyAttributes(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::Sema::checkUnsafeExprAssigns(), findWeakLValue(), clang::analyze_printf::PrintfSpecifier::fixType(), handleObjCOwnershipTypeAttr(), handleObjCReturnsInnerPointerAttr(), inferARCWriteback(), isObjCLifetimeType(), isValidSubjectOfNSReturnsRetainedAttribute(), clang::Sema::MaybeBindToTemporary(), MaybeProduceObjCObject(), transferARCOwnership(), transferARCOwnershipToDeclSpec(), and tryMakeVariablePseudoStrong().
isObjCSelType()
bool clang::Type::isObjCSelType () const inline
Definition at line 7109 of file Type.h.
References getAs().
Referenced by clang::ObjCMethodDecl::getMethodFamily(), isObjCBuiltinType(), and LookupMemberExpr().
isObjectPointerType()
bool clang::Type::isObjectPointerType () const inline
Definition at line 6960 of file Type.h.
References getAs().
isObjectType()
bool clang::Type::isObjectType () const inline
Determine whether this type is an object type.
Definition at line 2095 of file Type.h.
References isFunctionType(), isReferenceType(), and isVoidType().
Referenced by clang::CodeGen::CodeGenModule::ConstructAttributeList(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), clang::Sema::FindCompositePointerType(), clang::Sema::getNamedReturnInfo(), clang::Sema::handlerCanCatch(), clang::QualType::isReferenceable(), SemaBuiltinLaunder(), and clang::Value::Value().
isOCLExtOpaqueType()
bool clang::Type::isOCLExtOpaqueType () const inline
Definition at line 7178 of file Type.h.
Referenced by isOpenCLSpecificType().
isOCLIntelSubgroupAVCType()
bool clang::Type::isOCLIntelSubgroupAVCType () const inline
Definition at line 7170 of file Type.h.
Referenced by clang::InitializationSequence::Perform(), and TryOCLZeroOpaqueTypeInitialization().
isOpenCLSpecificType()
bool clang::Type::isOpenCLSpecificType () const inline
Definition at line 7185 of file Type.h.
References isClkEventT(), isEventT(), isImageType(), isOCLExtOpaqueType(), isPipeType(), isQueueT(), isReserveIDT(), and isSamplerT().
Referenced by getOpenCLKernelParameterType(), and isTypeSubstitutable().
isOverloadableType()
bool clang::Type::isOverloadableType () const inline
Determines whether this is a type for which one can define an overloaded operator.
Definition at line 7383 of file Type.h.
References isDependentType(), isEnumeralType(), and isRecordType().
Referenced by clang::Sema::BuildBinOp(), buildCounterUpdate(), clang::Sema::BuildUnaryOp(), checkOpenMPIterationSpace(), and clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr().
isPipeType()
bool clang::Type::isPipeType () const inline
Definition at line 7156 of file Type.h.
References clang::isa().
Referenced by clang::Sema::BuildArrayType(), checkOpenCLPipeArg(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), diagnoseOpenCLTypes(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), HandleOpenCLAccessAttr(), and isOpenCLSpecificType().
isPlaceholderType()
bool clang::Type::isPlaceholderType () const inline
Test for a type which does not represent an actual type-system type but is instead used as a placeholder for various convenient purposes within Clang.
All such types are BuiltinTypes.
Definition at line 7230 of file Type.h.
Referenced by CheckIncrementDecrementOperand(), DeduceTemplateArgumentsByTypeMatch(), and clang::Expr::hasPlaceholderType().
isPointerType()
bool clang::Type::isPointerType () const inline
Definition at line 6936 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnOMPArrayShapingExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPIsDevicePtrClause(), clang::Sema::ActOnOpenMPUseDevicePtrClause(), clang::Sema::ActOnVariableDeclarator(), addCastTransition(), clang::Sema::AddFunctionCandidates(), addInstanceOfTransition(), AddOrdinaryNameResults(), argTypeIsABIEquivalent(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildAtomicExpr(), buildCapture(), BuildCXXCastArgument(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXThisExpr(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildPseudoDestructorExpr(), clang::ento::RetainSummaryManager::canEval(), castToBase(), clang::Sema::CheckAdditionOperands(), checkArrayExpressionDoesNotReferToWholeSize(), CheckArrow(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckExtVectorCast(), CheckIncrementDecrementOperand(), checkIsValidOpenCLKernelParameter(), checkOpenMPIterationSpace(), checkPointerIntegerMismatch(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), clang::Sema::CheckTransparentUnionArgumentConstraints(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), ClassifyDiagnostic(), CompareDerivedToBaseConversions(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), convertPointersToCompositeType(), clang::Sema::CreateBuiltinUnaryOp(), clang::CStyleCastPtrExpr(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseDivisionSizeofPointerOrArray(), diagnoseObjCARCConversion(), diagnoseOpenCLTypes(), clang::Sema::DiagnoseSwiftName(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), EmitBinaryAtomicPost(), EmitCompare(), EmitDynamicCastToNull(), emitOutlinedFunctionPrologue(), emitParallelOrTeamsOutlinedFunction(), EmitPointerWithAlignment(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), clang::ento::ExprEngine::evalCall(), EvaluateComparisonBinaryOperator(), ExprLooksBoolean(), fixParamWithSpan(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), fixVariable(), GeneralizeType(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getAArch64LS(), getAArch64PBV(), clang::QualType::getBaseTypeIdentifier(), getBuiltinAlignArguments(), clang::CodeGen::CodeGenModule::GetConstantArrayFromStringLiteral(), getCoreType(), clang::dataflow::getImplicitObjectLocation(), clang::UserDefinedLiteral::getLiteralOperatorKind(), clang::OverloadCandidate::getNumParams(), getObjCBridgeAttr(), clang::ASTContext::getObjCGCAttrKind(), clang::CXXMemberCallExpr::getObjectType(), getOpenCLKernelParameterType(), getPointeeTypeText(), getPreferredTypeOfBinaryRHS(), getUuidAttrOfType(), handleAllocSizeAttr(), handleFormatArgAttr(), handleFormatAttr(), clang::Sema::HandleFunctionTypeMismatch(), handleMSAllocatorAttr(), handleObjCOwnershipTypeAttr(), handleObjCReturnsInnerPointerAttr(), clang::Sema::handlerCanCatch(), hasPointerRepresentation(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::CXXDynamicCastExpr::isAlwaysNull(), isAnyPointerType(), clang::ExtVectorElementExpr::isArrow(), isAutoCastType(), isCompoundType(), isConsumableType(), isIntegerLikeType(), clang::ento::iterator::isIteratorType(), isLibstdcxxPointerReturnFalseHack(), clang::CXXTypeidExpr::isMostDerived(), clang::BinaryOperator::isNullPointerArithmeticExtension(), clang::Expr::isOBJCGCCandidate(), clang::Sema::isObjCPointerConversion(), clang::Sema::isOpenMPCapturedByRef(), clang::Sema::IsPointerConversion(), isPointerOrRef(), IsTypeModifiable(), isValidSubjectOfCFAttribute(), IsVoidStarType(), loadToBegin(), MakeBinaryAtomicValue(), clang::analyze_format_string::ArgType::matchesType(), needsAmpersandOnTemplateArg(), clang::ento::ConditionBRVisitor::patternMatch(), peelOffPointerArithmetic(), clang::Sema::PerformImplicitConversion(), clang::ento::ConditionBRVisitor::printValue(), ResolveOverloadForDeduction(), SemaBuiltinAlignment(), SemaBuiltinCallWithStaticChain(), SemaBuiltinDumpStruct(), SemaBuiltinLaunder(), SemaOpenCLBuiltinEnqueueKernel(), setObjCGCLValueClass(), shouldTrackFirstArgument(), TryConstCast(), TryReinterpretCast(), TypeIsInnerPointer(), clang::Value::Value(), clang::interp::ByteCodeExprGen< Emitter >::VisitCompoundAssignOperator(), and clang::interp::ByteCodeExprGen< Emitter >::VisitPointerArithBinOp().
isQueueT()
bool clang::Type::isQueueT () const inline
Definition at line 7141 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::CheckCompareOperands(), clang::Sema::CheckSingleAssignmentConstraints(), isOpenCLSpecificType(), IsStandardConversion(), clang::InitializationSequence::Perform(), SemaOpenCLBuiltinEnqueueKernel(), and TryOCLZeroOpaqueTypeInitialization().
isRealFloatingType()
bool Type::isRealFloatingType () const
Floating point categories.
Definition at line 2183 of file Type.cpp.
Referenced by clang::Sema::ActOnGCCAsmStmt(), actOnOMPReductionKindClause(), clang::Sema::BuildVectorType(), clang::ento::SMTConstraintManager::canReasonAbout(), checkFPMathBuiltinElementType(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::checkTypeSupport(), DiagnoseBadFunctionCast(), clang::ento::SMTConv::doFloatTypeConversion(), clang::ento::SMTConv::doTypeConversion(), EvaluateComparisonBinaryOperator(), EvaluateFloat(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::ento::SMTConv::fromCast(), clang::ento::SMTConv::getBinExpr(), clang::StandardConversionSequence::getNarrowingKind(), clang::ento::SMTConv::getSymExpr(), clang::ento::SMTConstraintManager::getSymVal(), clang::ento::SMTConv::getZeroExpr(), handleFloatConversion(), handleIntegerToComplexFloatConversion(), isIntegerLikeType(), IsStandardConversion(), clang::ento::SMTConv::mkSort(), OpenCLArithmeticConversions(), clang::Sema::PerformImplicitConversion(), tryGCCVectorConvertAndSplat(), TryStaticCast(), tryVectorConvertAndSplat(), and clang::Sema::UsualArithmeticConversions().
isRealType()
bool Type::isRealType () const
Definition at line 2189 of file Type.cpp.
References isBitIntType().
Referenced by CheckIncrementDecrementOperand(), clang::Sema::CheckSizelessVectorOperands(), clang::Sema::CheckVectorOperands(), and rewriteToObjCProperty().
isRecordType()
bool clang::Type::isRecordType () const inline
Definition at line 7026 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnFinishFunctionBody(), actOnOMPReductionKindClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::AddInitializerToDecl(), clang::dataflow::AggregateStorageLocation::AggregateStorageLocation(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), BuildImplicitMemberInitializer(), buildMemcpyForAssignmentOp(), clang::Sema::BuildVAArgExpr(), clang::interp::CheckArrayInitialized(), CheckConditionalOperand(), clang::interp::CheckFieldsInitialized(), checkIsValidOpenCLKernelParameter(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckMemberPointerConversion(), CheckMoveOnConstruction(), CheckOriginalCallArgDeduction(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkVariadicArgument(), clang::Sema::CollectIvarsToConstructOrDestruct(), clang::CXXBindTemporaryExpr::Create(), clang::Sema::CreateGenericSelectionExpr(), createReferenceTemporary(), clang::dataflow::DataflowAnalysisContext::createStorageLocation(), clang::Sema::CXXCheckConditionalOperands(), DeduceTemplateArgumentsByTypeMatch(), clang::InitializationSequence::Diagnose(), DiagnoseRecursiveConstFields(), emitPreCond(), Evaluate(), evaluateCDTSize(), EvaluateInPlace(), EvaluateRecord(), EvaluateTemporary(), clang::Sema::FindAllocationFunctions(), FindConversionForRefInit(), findSubobject(), clang::QualType::getBaseTypeIdentifier(), clang::ASTContext::getByrefLifetime(), clang::Sema::getCopyElisionCandidate(), clang::CXXMethodDecl::getDevirtualizedMethod(), getFieldsFromClassHierarchy(), getOpenCLKernelParameterType(), clang::dataflow::Environment::getResultObjectLocation(), getSelfInitExpr(), clang::Sema::getTypeName(), clang::Sema::handlerCanCatch(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::ASTNodeImporter::ImportAPValue(), InitCatchParam(), clang::InitializationSequence::InitializeFrom(), IsAcceptableNonMemberOperatorCandidate(), clang::Sema::IsBlockPointerConversion(), isCARCBridgableType(), isCompoundType(), clang::Expr::isConstantInitializer(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), isOverloadableType(), clang::Sema::IsPointerConversion(), IsStandardConversion(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectMemberConversion(), clang::APValue::printPretty(), clang::dataflow::refreshStructValue(), ResolveOverloadedFunctionForReferenceBinding(), SemaBuiltinDumpStruct(), setObjCGCLValueClass(), clang::Expr::skipRValueSubobjectAdjustments(), TryConstCast(), TryDefaultInitialization(), tryDiagnoseOverloadedCast(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit(), TryListConversion(), TryListInitialization(), TryObjectArgumentInitialization(), TryReferenceInit(), TryReferenceInitializationCore(), TryStaticImplicitCast(), TryUserDefinedConversion(), clang::Value::Value(), clang::interp::ByteCodeExprGen< Emitter >::visitInitializer(), and warnAboutAmbiguousFunction().
isReferenceType()
bool clang::Type::isReferenceType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 6948 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnFunctionDeclarator(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPDeclareReductionType(), clang::Sema::ActOnUninitializedDecl(), addCastTransition(), clang::Sema::AddInitializerToDecl(), addInstanceOfTransition(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), buildCoawaitCalls(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), BuildImplicitMemberInitializer(), clang::canDynamicCastThrow(), captureInBlock(), captureInLambda(), CastsAwayConstness(), castToBase(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAllocatedType(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckFieldDecl(), CheckForReference(), CheckICE(), clang::Sema::checkInitializerLifetime(), CheckLValueConstantExpression(), clang::Sema::CheckOMPThreadPrivateDecl(), clang::Sema::CheckOpenMPLinearDecl(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), ClassifyDiagnostic(), ClassifyMemberExpr(), CompareQualificationConversions(), clang::Sema::CompareReferenceRelationship(), create_call_once(), createObjCPropertyGetter(), DeduceNonTypeTemplateArgument(), clang::Sema::DeduceTemplateArguments(), clang::Sema::deepTypeCheckForSYCLDevice(), DetermineNoUndef(), clang::InitializationSequence::Diagnose(), DiagnoseBadConversion(), DiagnoseDivisionSizeofPointerOrArray(), DiagnoseForRangeReferenceVariableCopies(), DiagnoseForRangeVariableCopies(), diagnoseListInit(), diagnoseOpenCLTypes(), clang::Sema::DiagnoseSwiftName(), DoMarkPotentialCapture(), clang::ento::SMTConv::doTypeConversion(), clang::CodeGen::CGDebugInfo::EmitDeclareOfAutoVariable(), EmitDeclInit(), EmitGlobalVarDeclLValue(), clang::ento::ExprEngine::evalCall(), clang::ento::SMTConv::fromCast(), getAArch64MTV(), getBaseAlignmentAndOffsetFromLValue(), clang::QualType::getBaseTypeIdentifier(), getCoreType(), clang::CFGImplicitDtor::getDestructorDecl(), getFuchsiaHandleSymbols(), clang::OverloadCandidate::getNumParams(), getOpenCLKernelParameterType(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), getUuidAttrOfType(), clang::ento::SMTConv::getZeroExpr(), handleLifetimeCategoryAttr(), handleMSAllocatorAttr(), handleObjCReturnsInnerPointerAttr(), handleSwiftError(), hasPointerRepresentation(), clang::Expr::HasSideEffects(), clang::InitializationSequence::InitializeFrom(), isAutoCastType(), clang::ento::isCapturedByReference(), isCapturingReferenceToHostVarInCUDADeviceLambda(), isCompoundType(), isConsumableType(), isLiteralType(), clang::CXXTypeidExpr::isMostDerived(), isObjectType(), clang::Sema::isOpenMPCapturedByRef(), isPointerOrRef(), clang::ento::isPossiblyEscaped(), clang::QualType::isReferenceable(), isRelevantAttr(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::CodeGen::CodeGenModule::isTypeConstant(), clang::Expr::isUnusedResultAWarning(), isValidBaseType(), loadToBegin(), maybeTailCall(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), PerformReturnAdjustment(), print(), clang::APValue::printPretty(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ReferenceType::ReferenceType(), clang::Sema::RefersToMemberWithReducedAlignment(), clang::dataflow::AggregateStorageLocation::setChild(), clang::Expr::setType(), clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr(), shouldTrackFirstArgument(), clang::dataflow::StorageLocation::StorageLocation(), clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter(), TryCopyInitialization(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit(), TryListConversion(), TryListInitialization(), TryOrBuildParenListInitialization(), TryReferenceInit(), TryStaticImplicitCast(), TryUserDefinedConversion(), unwrapCastAwayConstnessLevel(), clang::FunctionCallFilterCCC::ValidateCandidate(), clang::Value::Value(), clang::interp::ByteCodeExprGen< Emitter >::VisitDeclRefExpr(), visitLocalsRetainedByInitializer(), clang::interp::ByteCodeExprGen< Emitter >::VisitMemberExpr(), clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl(), warnAboutAmbiguousFunction(), and writeShouldKill().
isReserveIDT()
bool clang::Type::isReserveIDT () const inline
Definition at line 7145 of file Type.h.
References isSpecificBuiltinType().
Referenced by diagnoseOpenCLTypes(), getOpenCLKernelParameterType(), and isOpenCLSpecificType().
isRValueReferenceType()
bool clang::Type::isRValueReferenceType () const inline
Definition at line 6956 of file Type.h.
References clang::isa().
Referenced by clang::Sema::AddConversionCandidate(), alignReferenceTypes(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::CheckTemplateArgument(), create_call_once_funcptr_call(), DiagnoseForRangeReferenceVariableCopies(), FindConversionForRefInit(), clang::Sema::getNamedReturnInfo(), clang::ento::ExprEngine::handleLValueBitCast(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::CXXConstructorDecl::isMoveConstructor(), isRelevantAttr(), isRValueRef(), NoteFunctionCandidate(), RefersToRValueRef(), TryListConversion(), TryReferenceInit(), TryReferenceListInitialization(), TryStaticReferenceDowncast(), unwrapRValueReferenceIndirection(), and VerifyInitializationSequenceCXX98().
isRVVSizelessBuiltinType()
bool Type::isRVVSizelessBuiltinType () const
Returns true for RVV scalable vector types.
Definition at line 2402 of file Type.cpp.
References getAs().
Referenced by clang::ASTContext::areCompatibleRVVTypes(), clang::ASTContext::areLaxCompatibleRVVTypes(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckVectorOperands(), clang::Sema::isValidRVVBitcast(), and IsVectorConversion().
isRVVType() [1/3]
bool clang::Type::isRVVType () const inline
Definition at line 7190 of file Type.h.
isRVVType() [2/3]
bool clang::Type::isRVVType (unsigned Bitwidth, bool IsFloat) const inline
Definition at line 7208 of file Type.h.
isRVVType() [3/3]
bool clang::Type::isRVVType (unsigned ElementCount) const inline
Definition at line 7198 of file Type.h.
Referenced by clang::Sema::checkTypeSupport(), and isTrackedVar().
isRVVVLSBuiltinType()
bool Type::isRVVVLSBuiltinType () const
Determines if this is a sizeless type supported by the 'riscv_rvv_vector_bits' type attribute, which can be applied to a single RVV vector or mask.
Definition at line 2454 of file Type.cpp.
References getAs().
Referenced by clang::ASTContext::areCompatibleRVVTypes(), getRVVEltType(), getRVVTypeSize(), and HandleRISCVRVVVectorBitsTypeAttr().
isSamplerT()
bool clang::Type::isSamplerT () const inline
Definition at line 7129 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::BuildArrayType(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::deduceOpenCLAddressSpace(), deduceOpenCLPointeeAddrSpace(), diagnoseOpenCLTypes(), isOpenCLSpecificType(), IsStandardConversion(), clang::InitializationSequence::Perform(), and TryOCLSamplerInitialization().
isSaturatedFixedPointType()
bool clang::Type::isSaturatedFixedPointType () const inline
Return true if this is a saturated fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
This type can be signed or unsigned.
Definition at line 7311 of file Type.h.
Referenced by clang::ASTContext::getCorrespondingSaturatedType(), clang::ASTContext::getFixedPointSemantics(), handleFixedPointConversion(), and isUnsaturatedFixedPointType().
isScalarType()
bool clang::Type::isScalarType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7341 of file Type.h.
References clang::isa(), isBitIntType(), and clang::IsEnumDeclComplete().
Referenced by clang::Sema::ActOnFunctionDeclarator(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::areLaxCompatibleVectorTypes(), breakDownVectorType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildPseudoDestructorExpr(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), clang::Sema::CheckAssignmentConstraints(), checkCondition(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckVectorOperands(), clang::Sema::CreateBuiltinUnaryOp(), DetermineNoUndef(), getDerivedSymbolForBinding(), getScalarTypeKind(), getVariableCategoryFromDecl(), hasIsEqualMethod(), clang::QualType::isCXX11PODType(), isLiteralType(), clang::Sema::isOpenMPCapturedByRef(), isStandardLayoutType(), isStructuralType(), isTrackedVar(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTrivialType(), matchTypes(), TryListInitialization(), and updateOutParameters().
isScopedEnumeralType()
bool Type::isScopedEnumeralType () const
Determine whether this type is a scoped enumeration type.
Definition at line 618 of file Type.cpp.
References getAs().
isSignedFixedPointType()
bool clang::Type::isSignedFixedPointType () const inline
Return true if this is a fixed point type that is signed according to ISO/IEC JTC1 SC22 WG14 N1169.
This type can also be saturated.
Definition at line 7323 of file Type.h.
Referenced by clang::ASTContext::getFixedPointSemantics(), handleFixedPointConversion(), and isUnsignedFixedPointType().
isSignedIntegerOrEnumerationType()
bool Type::isSignedIntegerOrEnumerationType () const
Determines whether this is an integer type that is signed or an enumeration types whose underlying type is a signed integer type.
Definition at line 2084 of file Type.cpp.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnFinishSwitchStmt(), clang::ento::SMTConv::castAPSInt(), clang::Sema::CheckEnumConstant(), CheckICE(), clang::Sema::CheckTemplateArgument(), clang::Sema::DiagnoseAssignmentEnum(), clang::ento::SMTConv::doIntTypeConversion(), EmitIntegerSignChangeCheckHelper(), EmitIntegerTruncationCheckHelper(), emitPointerArithmetic(), clang::ento::SMTConv::fromCast(), clang::ento::SMTConv::getBinExpr(), clang::StandardConversionSequence::getNarrowingKind(), clang::ento::SMTConv::getRangeExpr(), clang::ento::SMTConstraintManager::getSymVal(), clang::ento::SMTConv::getZeroExpr(), HandleFloatToIntCast(), hasSignedIntegerRepresentation(), clang::CodeGen::CGBitFieldInfo::MakeInfo(), clang::ASTContext::MakeIntValue(), and tryRearrange().
isSignedIntegerType()
bool Type::isSignedIntegerType () const
Return true if this is an integer type that is signed, according to C99 6.2.5p4 [char, signed char, short, int, long..], or an enum decl which has a signed representation.
isSignedIntegerType - Return true if this is an integer type that is signed, according to C99 6.2.5p4 [char, signed char, short, int, long..], an enum decl which has a signed representation
Definition at line 2063 of file Type.cpp.
Referenced by clang::Sema::AddModeAttr(), AnalyzeBitFieldAssignment(), clang::Sema::CheckCompatibleReinterpretCast(), clang::InitializationSequence::Diagnose(), DiagnoseIntInBoolContext(), EmitAtomicOp(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::ASTContext::getFixedPointSemantics(), getIntegerWidthAndSignedness(), clang::ASTContext::getPromotedIntegerType(), clang::Sema::IsIntegralPromotion(), isKnownToHaveUnsignedValue(), clang::ASTContext::isPromotableBitField(), rewriteToNumericBoxedExpression(), clang::JSONNodeDumper::VisitIntegerLiteral(), and clang::ento::ExprEngine::VisitOffsetOfExpr().
isSizelessBuiltinType()
bool Type::isSizelessBuiltinType () const
Definition at line 2350 of file Type.cpp.
References getAs().
Referenced by clang::Sema::CheckConditionalOperands(), clang::Sema::CheckVectorOperands(), clang::Sema::GetSignedSizelessVectorType(), clang::QualType::isCXX11PODType(), isSizelessType(), clang::QualType::isTriviallyCopyableType(), and warnBracedScalarInit().
isSizelessType()
bool Type::isSizelessType () const
As an extension, we classify types as one of "sized" or "sizeless"; every type is one or the other.
Standard types are all sized; sizeless types are purely an extension.
Sizeless types contain data with no specified size, alignment, or layout.
Definition at line 2386 of file Type.cpp.
References isSizelessBuiltinType().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::CheckCXXThrowOperand(), and clang::Sema::CheckSpecifiedExceptionType().
isSpecificBuiltinType()
bool clang::Type::isSpecificBuiltinType (unsigned K) const inline
Test for a particular builtin type.
Definition at line 7223 of file Type.h.
References getAs().
Referenced by clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPMapClause(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVAArgExpr(), clang::ento::SMTConstraintManager::canReasonAbout(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::CheckOverloadedOperatorDeclaration(), CheckTautologicalComparison(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAssignmentResult(), clang::OverloadExpr::find(), clang::Sema::getCopyElisionCandidate(), clang::dataflow::Environment::getStorageLocationStrict(), isBFloat16Type(), isClkEventT(), isEventT(), isFloat128Type(), isFloat16Type(), isHalfType(), isIbm128Type(), IsImplicitBoolFloatConversion(), isNullPtrType(), isObjCSignedCharBool(), isQueueT(), isReserveIDT(), isSamplerT(), isSpecificPlaceholderType(), isTypeSubstitutable(), isVoidType(), processImplicitMapsWithDefaultMappers(), and clang::dataflow::Environment::setStorageLocationStrict().
isSpecificPlaceholderType()
bool clang::Type::isSpecificPlaceholderType (unsigned K) const inline
Test for a specific placeholder type.
Definition at line 7243 of file Type.h.
References clang::BuiltinType::isPlaceholderTypeKind(), and isSpecificBuiltinType().
Referenced by clang::CallExpr::getCallReturnType(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), and clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr().
isSpecifierType()
bool Type::isSpecifierType () const
Returns true if this type can be represented by some set of type specifiers.
Definition at line 2968 of file Type.cpp.
References Complex, Enum, and getTypeClass().
isStandardLayoutType()
bool Type::isStandardLayoutType () const
Test if this type is a standard-layout type.
(C++0x [basic.type]p9)
Definition at line 2853 of file Type.cpp.
References getAs(), getBaseElementTypeUnsafe(), isDependentType(), isIncompleteType(), isScalarType(), and isVectorType().
Referenced by isLayoutCompatible().
isStdByteType()
bool Type::isStdByteType () const
Definition at line 2959 of file Type.cpp.
References getAs(), and clang::IdentifierInfo::isStr().
isStructuralType()
bool Type::isStructuralType () const
Determine if this type is a structural type, per C++20 [temp.param]p7.
Definition at line 2837 of file Type.cpp.
References getAsCXXRecordDecl(), isLValueReferenceType(), isScalarType(), and isVectorType().
isStructureOrClassType()
bool Type::isStructureOrClassType () const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 587 of file Type.cpp.
References getAs(), clang::TagDecl::isClass(), clang::TagDecl::isInterface(), and clang::TagDecl::isStruct().
Referenced by clang::Sema::ActOnOpenMPDeclareMapperType(), buildUserDefinedMapperRef(), markEscapingByrefs(), and processImplicitMapsWithDefaultMappers().
isStructureType()
bool Type::isStructureType () const
Definition at line 569 of file Type.cpp.
References getAs().
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::CheckCompleteVariableDeclaration(), getFuchsiaHandleSymbols(), and clang::Sema::MergeTypedefNameDecl().
isSVESizelessBuiltinType()
bool Type::isSVESizelessBuiltinType () const
Returns true for SVE scalable vector types.
Definition at line 2388 of file Type.cpp.
References getAs().
Referenced by clang::ASTContext::areCompatibleSveTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::checkTypeSupport(), clang::Sema::CheckVectorOperands(), clang::Sema::isValidSveBitcast(), and IsVectorConversion().
isTemplateTypeParmType()
bool clang::Type::isTemplateTypeParmType () const inline
Definition at line 7219 of file Type.h.
References clang::isa().
isTypedefNameType()
bool clang::Type::isTypedefNameType () const inline
Determines whether this type is written as a typedef-name.
Definition at line 7388 of file Type.h.
References getAs().
Referenced by clang::extractapi::TypedefUnderlyingTypeResolver::getUnderlyingTypeDecl().
isUndeducedAutoType()
bool clang::Type::isUndeducedAutoType () const inline
Definition at line 7081 of file Type.h.
References clang::isa().
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison(), and deduceOpenCLPointeeAddrSpace().
isUndeducedType()
bool clang::Type::isUndeducedType () const inline
Determine whether this type is an undeduced type, meaning that it somehow involves a C++11 'auto' type or similar which has not yet been deduced.
Definition at line 7376 of file Type.h.
References getContainedDeducedType().
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnInitializerError(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::AddConversionCandidate(), clang::Sema::AddInitializerToDecl(), clang::Sema::areMultiversionVariantFunctionsCompatible(), clang::Sema::BuildVariableInstantiation(), clang::Sema::canDelayFunctionBody(), clang::Sema::checkArrayElementAlignment(), clang::Sema::CheckNonTypeTemplateParameterType(), completeFunctionType(), clang::Sema::deduceClosureReturnType(), clang::Sema::DeduceReturnType(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), GetTypeOfFunction(), hasDeducedReturnType(), clang::Sema::MergeVarDeclTypes(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), and TryToFixInvalidVariablyModifiedType().
isUnionType()
bool Type::isUnionType () const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 601 of file Type.cpp.
References getAs().
Referenced by clang::Sema::ActOnOpenMPDeclareMapperType(), buildUserDefinedMapperRef(), checkIsValidOpenCLKernelParameter(), checkMemberDecomposition(), EvaluateBuiltinClassifyType(), evaluateCDTSize(), isCompoundType(), and processImplicitMapsWithDefaultMappers().
isUnsaturatedFixedPointType()
bool clang::Type::isUnsaturatedFixedPointType () const inline
Return true if this is a saturated fixed point type according to ISO/IEC JTC1 SC22 WG14 N1169.
This type can be signed or unsigned.
Definition at line 7319 of file Type.h.
References isFixedPointType(), and isSaturatedFixedPointType().
isUnscopedEnumerationType()
bool Type::isUnscopedEnumerationType () const
Definition at line 1999 of file Type.cpp.
Referenced by checkEnumArithmeticConversions(), and isIntegralOrUnscopedEnumerationType().
isUnsignedFixedPointType()
bool clang::Type::isUnsignedFixedPointType () const inline
Return true if this is a fixed point type that is unsigned according to ISO/IEC JTC1 SC22 WG14 N1169.
This type can also be saturated.
Definition at line 7337 of file Type.h.
References isFixedPointType(), and isSignedFixedPointType().
Referenced by clang::ASTContext::getCorrespondingSignedFixedPointType(), and handleFixedPointConversion().
isUnsignedIntegerOrEnumerationType()
bool Type::isUnsignedIntegerOrEnumerationType () const
Determines whether this is an integer type that is unsigned or an enumeration types whose underlying type is a unsigned integer type.
Definition at line 2134 of file Type.cpp.
Referenced by clang::Sema::CheckTemplateArgument(), GetValueRange(), HandleIntToIntCast(), hasUnsignedIntegerRepresentation(), and clang::ento::SValBuilder::makeIntVal().
isUnsignedIntegerType()
bool Type::isUnsignedIntegerType () const
Return true if this is an integer type that is unsigned, according to C99 6.2.5p6 [which returns true for _Bool], or an enum decl which has an unsigned representation.
isUnsignedIntegerType - Return true if this is an integer type that is unsigned, according to C99 6.2.5p6 [which returns true for _Bool], an enum decl which has an unsigned representation
Definition at line 2113 of file Type.cpp.
Referenced by clang::Sema::ActOnStringLiteral(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckCompatibleReinterpretCast(), clang::Sema::DefaultArgumentPromotion(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), clang::ento::SValBuilder::evalIntegralCast(), expandStringLiteral(), extractStringLiteralCharacter(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::ASTContext::getIntegerTypeOrder(), clang::ASTContext::getPromotedIntegerType(), handleVectorUnaryOperator(), handleVectorVectorBinOp(), clang::Sema::IsIntegralPromotion(), and SemaBuiltinRWPipe().
isVariableArrayType()
bool clang::Type::isVariableArrayType () const inline
Definition at line 7014 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildCompoundLiteralExpr(), CheckICE(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), emitOMPArraySectionBase(), EquivalentArrayTypes(), isConstantSizeArrayWithMoreThanOneElement(), isLiteralType(), and isSimpleArrayDecayOperand().
isVariablyModifiedType()
bool clang::Type::isVariablyModifiedType () const inline
Whether this type is a variably-modified type (C99 6.7.5).
Definition at line 2363 of file Type.h.
References getDependence().
Referenced by clang::Sema::ActOnFunctionDeclarator(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::CheckAllocatedType(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), diagnoseArrayStarInParamType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), emitOutlinedFunctionPrologue(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::Sema::HandleExprEvaluationContextForTypeof(), hasSizedVLAType(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::Sema::isIncompatibleTypedef(), isVariableCapturable(), clang::Sema::SubstType(), clang::Sema::tryCaptureVariable(), and TryToFixInvalidVariablyModifiedType().
isVectorType()
bool clang::Type::isVectorType () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7038 of file Type.h.
References clang::isa().
Referenced by clang::Sema::ActOnCastExpr(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignedAttr(), clang::Sema::anyAltivecTypes(), clang::ASTContext::areCompatibleRVVTypes(), clang::ASTContext::areCompatibleSveTypes(), clang::ASTContext::areCompatibleVectorTypes(), clang::ASTContext::areLaxCompatibleRVVTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), clang::Sema::areLaxCompatibleVectorTypes(), clang::Sema::areVectorTypesSameSize(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildVectorLiteral(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckExtVectorCast(), CheckIncrementDecrementOperand(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckVectorCast(), clang::Sema::CheckVectorOperands(), checkVectorShift(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CXXCheckConditionalOperands(), EvaluateVector(), handleTransparentUnionAttr(), clang::Sema::InvalidLogicalVectorOperands(), clang::QualType::isCXX11PODType(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), isIntegerLikeType(), clang::Sema::isLaxVectorConversion(), isLiteralType(), clang::Sema::IsPointerConversion(), isStandardLayoutType(), isStructuralType(), isTrackedVar(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTrivialType(), clang::Sema::isValidRVVBitcast(), clang::Sema::isValidSveBitcast(), isValidVectorForConditionalCondition(), IsVectorConversion(), clang::Sema::LookupTemplateName(), OpenCLCheckVectorConditional(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::SemaConvertVectorExpr(), TryReinterpretCast(), clang::ento::ExprEngine::VisitArraySubscriptExpr(), and clang::ento::ExprEngine::VisitLogicalExpr().
isVisibilityExplicit()
bool clang::Type::isVisibilityExplicit () const inline
Return true if the visibility was explicitly set is the code.
Definition at line 2576 of file Type.h.
References getLinkageAndVisibility(), and clang::LinkageInfo::isVisibilityExplicit().
isVLSTBuiltinType()
bool Type::isVLSTBuiltinType () const
Determines if this is a sizeless type supported by the 'arm_sve_vector_bits' type attribute, which can be applied to a single SVE vector or predicate, excluding tuple types such as svint32x4_t.
Definition at line 2415 of file Type.cpp.
References getAs().
Referenced by clang::Sema::CheckAdditionOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckCompareOperands(), CheckImplicitConversion(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), getSveEltType(), getSVETypeSize(), HandleArmSveVectorBitsTypeAttr(), isValidSizelessVectorForConditionalCondition(), and tryGCCVectorConvertAndSplat().
isVoidPointerType()
bool Type::isVoidPointerType () const
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 595 of file Type.cpp.
References getAs().
Referenced by clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), checkConditionalBlockPointerCompatibility(), checkIntToPointerCast(), clang::ento::SMTConv::doTypeConversion(), EvaluateComparisonBinaryOperator(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), getExistingLazyBinding(), HandleDynamicCast(), clang::CXXDynamicCastExpr::isAlwaysNull(), clang::analyze_format_string::ArgType::matchesType(), maybeTailCall(), SemaBuiltinLaunder(), and TryReinterpretCast().
isVoidType()
bool clang::Type::isVoidType () const inline
Definition at line 7254 of file Type.h.
References isSpecificBuiltinType().
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnStartOfObjCMethodDef(), clang::CodeGen::CGDebugInfo::addHeapAllocSiteMetadata(), AddObjCKeyValueCompletions(), AddObjCProperties(), AddOrdinaryNameResults(), AnalyzeImplicitConversions(), buildCoawaitCalls(), clang::Sema::BuildCoreturnStmt(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildFunctionType(), buildLambdaScopeReturnType(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildReturnStmt(), checkArithmeticBinOpPointerOperands(), checkArithmeticOpPointerOperand(), clang::Sema::CheckCallReturnType(), CheckCommaOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompatibleReinterpretCast(), checkConditionalObjectPointersCompatibility(), clang::Sema::CheckConditionalOperands(), CheckConstantExpression(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::CheckFunctionDeclaration(), checkPointerTypesForAssignment(), clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTransparentUnionArgumentConstraints(), CheckUnaryTypeTraitTypeCompleteness(), ClassifyConditional(), clang::CodeGen::DefaultABIInfo::classifyReturnType(), PNaClABIInfo::classifyReturnType(), clang::interp::ByteCodeEmitter::compileFunc(), clang::CodeGen::CodeGenModule::ConstructAttributeList(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::deduceOpenCLAddressSpace(), DiagnoseBadFunctionCast(), DiagnoseCastOfObjCSEL(), clang::Sema::DiagnoseUnusedExprResult(), emitPointerArithmetic(), clang::ento::StoreManager::evalBaseToDerived(), clang::ento::ExprEngine::evalCall(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), evaluateCDTSize(), EvaluateLValue(), EvaluateVoid(), clang::Sema::FindCompositePointerType(), formatBlockPlaceholder(), generateDiagnosticsForCallLike(), getAArch64MTV(), GetExprRange(), GetFullTypeForDeclarator(), getNDSWDS(), getOpenCLKernelParameterType(), clang::ento::SMTConstraintManager::getSymVal(), handleGlobalAttr(), clang::Sema::handlerCanCatch(), HandleSizeof(), handleSwiftAsyncAttr(), handleSYCLKernelAttr(), handleWarnUnusedResult(), IgnoreCommaOperand(), clang::Sema::IgnoredValueConversions(), isCARCBridgableType(), isDispatchBlock(), isFundamentalType(), isIncompleteType(), isLiteralType(), clang::Expr::isNullPointerConstant(), isObjectType(), clang::Sema::IsPointerConversion(), clang::StandardConversionSequence::isPointerConversionToVoidPointer(), clang::ento::cocoa::isRefType(), isUnitTest(), clang::Expr::isUnusedResultAWarning(), clang::Sema::isValidVarArgType(), isVoidPointerToNonConst(), IsVoidStarType(), clang::analyze_format_string::ArgType::matchesType(), clang::APValue::printPretty(), clang::Sema::RequireLiteralType(), clang::consumed::ConsumedAnalyzer::run(), shouldBeModeledWithNoOp(), clang::Sema::SubstituteExplicitTemplateArguments(), clang::Sema::SubstParmVarDecl(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), tryGenerateSpecializedMessageSend(), TryStaticCast(), clang::interp::ByteCodeExprGen< Emitter >::VisitBuiltinCallExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr(), clang::interp::ByteCodeStmtGen< Emitter >::visitFunc(), and warnAboutAmbiguousFunction().
isWebAssemblyExternrefType()
bool Type::isWebAssemblyExternrefType () const
Check if this is a WebAssembly Externref Type.
Definition at line 2370 of file Type.cpp.
References getAs().
Referenced by clang::QualType::isWebAssemblyExternrefType().
isWebAssemblyTableType()
bool Type::isWebAssemblyTableType () const
Returns true if this is a WebAssembly table type: either an array of reference types, or a pointer to a reference type (which can only be created by array to pointer decay).
Definition at line 2376 of file Type.cpp.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildFunctionType(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CXXCheckConditionalOperands(), and diagnoseTautologicalComparison().
isWideCharType()
bool Type::isWideCharType () const
Definition at line 2015 of file Type.cpp.
Referenced by clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), and TryPrintAsStringLiteral().
operator=() [1/2]
Type & clang::Type::operator= (const Type &) delete
operator=() [2/2]
Type & clang::Type::operator= (Type &&) delete
setDependence()
void clang::Type::setDependence (TypeDependence D) inline protected
Definition at line 1980 of file Type.h.
References TypeBits.
Referenced by addDependence().
this_()
Type * clang::Type::this_ () inline protected
Definition at line 1978 of file Type.h.
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 1960 of file Type.h.
ASTReader
friend class ASTReader friend
Definition at line 1987 of file Type.h.
ASTWriter
friend class ASTWriter friend
Definition at line 1988 of file Type.h.
serialization::AbstractTypeReader
template<class T > friend class serialization::AbstractTypeReader friend
Definition at line 1989 of file Type.h.
serialization::AbstractTypeWriter
template<class T > friend class serialization::AbstractTypeWriter friend
Definition at line 1990 of file Type.h.
TypePropertyCache
template<class T > friend class TypePropertyCache friend
Definition at line 1952 of file Type.h.
Member Data Documentation
[union]
union { ... } clang::Type
ArrayTypeBits
ArrayTypeBitfields clang::Type::ArrayTypeBits
Definition at line 1929 of file Type.h.
Referenced by clang::ArrayType::ArrayType(), clang::ArrayType::getIndexTypeCVRQualifiers(), and clang::ArrayType::getSizeModifier().
AttributedTypeBits
AttributedTypeBitfields clang::Type::AttributedTypeBits
Definition at line 1931 of file Type.h.
AutoTypeBits
AutoTypeBitfields clang::Type::AutoTypeBits
Definition at line 1932 of file Type.h.
BuiltinTypeBits
BuiltinTypeBitfields clang::Type::BuiltinTypeBits
Definition at line 1936 of file Type.h.
Referenced by clang::BuiltinType::getKind().
ConstantArrayTypeBits
ConstantArrayTypeBitfields clang::Type::ConstantArrayTypeBits
Definition at line 1930 of file Type.h.
Referenced by clang::ConstantArrayType::getSizeExpr().
DependentTemplateSpecializationTypeBits
DependentTemplateSpecializationTypeBitfields clang::Type::DependentTemplateSpecializationTypeBits
Definition at line 1947 of file Type.h.
ElaboratedTypeBits
ElaboratedTypeBitfields clang::Type::ElaboratedTypeBits
Definition at line 1941 of file Type.h.
FunctionTypeBits
FunctionTypeBitfields clang::Type::FunctionTypeBits
Definition at line 1937 of file Type.h.
Referenced by clang::FunctionType::FunctionType(), clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionType::getExtInfo(), clang::FunctionType::getFastTypeQuals(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::getRefQualifier(), clang::FunctionProtoType::hasExtParameterInfos(), clang::FunctionProtoType::hasTrailingReturn(), and clang::FunctionProtoType::isVariadic().
ObjCObjectTypeBits
ObjCObjectTypeBitfields clang::Type::ObjCObjectTypeBits
Definition at line 1938 of file Type.h.
PackExpansionTypeBits
PackExpansionTypeBitfields clang::Type::PackExpansionTypeBits
Definition at line 1948 of file Type.h.
ReferenceTypeBits
ReferenceTypeBitfields clang::Type::ReferenceTypeBits
Definition at line 1939 of file Type.h.
Referenced by clang::ReferenceType::isInnerRef(), clang::ReferenceType::isSpelledAsLValue(), and clang::ReferenceType::ReferenceType().
SubstTemplateTypeParmPackTypeBits
SubstTemplateTypeParmPackTypeBitfields clang::Type::SubstTemplateTypeParmPackTypeBits
Definition at line 1944 of file Type.h.
SubstTemplateTypeParmTypeBits
SubstTemplateTypeParmTypeBitfields clang::Type::SubstTemplateTypeParmTypeBits
Definition at line 1943 of file Type.h.
TemplateSpecializationTypeBits
TemplateSpecializationTypeBitfields clang::Type::TemplateSpecializationTypeBits
Definition at line 1945 of file Type.h.
TypeBits
TypeBitfields clang::Type::TypeBits
Definition at line 1928 of file Type.h.
Referenced by clang::TypePropertyCache< Private >::ensure(), getDependence(), getLinkage(), getTypeClass(), getTypeClassName(), hasUnnamedOrLocalType(), isFromAST(), isLinkageValid(), setDependence(), and Type().
TypedefBits
TypedefBitfields clang::Type::TypedefBits
Definition at line 1934 of file Type.h.
Referenced by clang::TypedefType::typeMatchesDecl().
TypeOfBits
TypeOfBitfields clang::Type::TypeOfBits
Definition at line 1933 of file Type.h.
Referenced by clang::TypeOfExprType::desugar(), clang::TypeOfExprType::getKind(), and clang::TypeOfExprType::TypeOfExprType().
TypeWithKeywordBits
TypeWithKeywordBitfields clang::Type::TypeWithKeywordBits
Definition at line 1940 of file Type.h.
UsingBits
UsingBitfields clang::Type::UsingBits
Definition at line 1935 of file Type.h.
Referenced by clang::UsingType::typeMatchesDecl().
VectorTypeBits
VectorTypeBitfields clang::Type::VectorTypeBits
Definition at line 1942 of file Type.h.
Referenced by clang::VectorType::getNumElements(), clang::DependentVectorType::getVectorKind(), clang::VectorType::getVectorKind(), and clang::VectorType::VectorType().
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
include/clang/AST/CanonicalType.h
lib/AST/ASTDumper.cpp
lib/AST/Type.cpp