clang: clang::CXXTemporary Class Reference
clang::CXXTemporary Class Reference
Represents a C++ temporary.
#include "clang/AST/ExprCXX.h"
Public Member Functions
const CXXDestructorDecl * getDestructor () const
void setDestructor (const CXXDestructorDecl *Dtor)
Static Public Member Functions
static CXXTemporary * Create (const ASTContext &C, const CXXDestructorDecl *Destructor)
Detailed Description
Represents a C++ temporary.
Definition at line 1438 of file ExprCXX.h.
Member Function Documentation
Create()
CXXTemporary * CXXTemporary::Create (const ASTContext & C, const CXXDestructorDecl * Destructor) static
Definition at line 1042 of file ExprCXX.cpp.
References clang::C.
Referenced by clang::Sema::MaybeBindToTemporary(), clang::ASTReader::ReadCXXTemporary(), and clang::ASTNodeImporter::VisitCXXBindTemporaryExpr().
getDestructor()
const CXXDestructorDecl * clang::CXXTemporary::getDestructor () const inline
Definition at line 1449 of file ExprCXX.h.
Referenced by clang::ASTRecordWriter::AddCXXTemporary(), clang::CFGImplicitDtor::getDestructorDecl(), clang::JSONNodeDumper::VisitCXXBindTemporaryExpr(), and clang::UsedDeclVisitor< Derived >::VisitCXXBindTemporaryExpr().
setDestructor()
void clang::CXXTemporary::setDestructor (const CXXDestructorDecl * Dtor) inline
Definition at line 1451 of file ExprCXX.h.
Referenced by clang::Sema::ActOnDecltypeExpression().
The documentation for this class was generated from the following files:
include/clang/AST/ExprCXX.h
lib/AST/ExprCXX.cpp