clang: clang::UnresolvedSetIterator Class Reference
clang::UnresolvedSetIterator Class Reference
The iterator over UnresolvedSets.
#include "clang/AST/UnresolvedSet.h"
Public Member Functions
UnresolvedSetIterator ()
NamedDecl * getDecl () const
void setDecl (NamedDecl *ND) const
AccessSpecifier getAccess () const
void setAccess (AccessSpecifier AS)
const DeclAccessPair & getPair () const
NamedDecl * operator* () const
NamedDecl * operator-> () const
Friends
class ASTUnresolvedSet
class OverloadExpr
class UnresolvedSetImpl
Detailed Description
The iterator over UnresolvedSets.
Serves as both the const and non-const iterator.
Definition at line 32 of file UnresolvedSet.h.
Constructor & Destructor Documentation
UnresolvedSetIterator()
clang::UnresolvedSetIterator::UnresolvedSetIterator () inline
Definition at line 48 of file UnresolvedSet.h.
Member Function Documentation
getAccess()
AccessSpecifier clang::UnresolvedSetIterator::getAccess () const inline
Definition at line 52 of file UnresolvedSet.h.
getDecl()
NamedDecl * clang::UnresolvedSetIterator::getDecl () const inline
Definition at line 50 of file UnresolvedSet.h.
Referenced by CollectVisibleConversions(), and operator*().
getPair()
const DeclAccessPair & clang::UnresolvedSetIterator::getPair () const inline
Definition at line 54 of file UnresolvedSet.h.
Referenced by clang::Sema::BuildMemberReferenceExpr().
operator*()
NamedDecl * clang::UnresolvedSetIterator::operator* () const inline
Definition at line 56 of file UnresolvedSet.h.
References getDecl().
operator->()
NamedDecl * clang::UnresolvedSetIterator::operator-> () const inline
Definition at line 57 of file UnresolvedSet.h.
setAccess()
void clang::UnresolvedSetIterator::setAccess (AccessSpecifier AS) inline
Definition at line 53 of file UnresolvedSet.h.
setDecl()
void clang::UnresolvedSetIterator::setDecl (NamedDecl * ND) const inline
Definition at line 51 of file UnresolvedSet.h.
Friends And Related Symbol Documentation
ASTUnresolvedSet
friend class ASTUnresolvedSet friend
Definition at line 36 of file UnresolvedSet.h.
OverloadExpr
friend class OverloadExpr friend
Definition at line 37 of file UnresolvedSet.h.
UnresolvedSetImpl
friend class UnresolvedSetImpl friend
Definition at line 38 of file UnresolvedSet.h.
The documentation for this class was generated from the following file:
include/clang/AST/UnresolvedSet.h