clang: clang::OMPNovariantsClause Class Reference
clang::OMPNovariantsClause Class Reference final
This represents 'novariants' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPNovariantsClause (Expr *Cond, Stmt *HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'novariants' clause with condition Cond.
OMPNovariantsClause ()
Build an empty clause.
Expr * getCondition () const
Returns condition.
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >
OMPOneStmtClause (Stmt *S, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPOneStmtClause ()
T * getStmtAs () const
Return the associated statement, potentially casted to T.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >
using child_iterator
using const_child_iterator
using child_range
using const_child_range
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Static Public Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Protected Member Functions inherited from clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >
void setStmt (Stmt *S)
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'novariants' clause in the '#pragma omp ...' directive.
#pragma omp dispatch novariants(a > 5)
In this example directive '#pragma omp dispatch' has simple 'novariants' clause with condition 'a > 5'.
Definition at line 8102 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPNovariantsClause() [1/2]
clang::OMPNovariantsClause::OMPNovariantsClause (Expr * Cond, Stmt * HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build 'novariants' clause with condition Cond.
Parameters
Cond Condition of the clause.
HelperCond Helper condition for the construct.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 8120 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPNovariantsClause() [2/2]
clang::OMPNovariantsClause::OMPNovariantsClause () inline
Build an empty clause.
Definition at line 8130 of file OpenMPClause.h.
Member Function Documentation
getCondition()
Expr * clang::OMPNovariantsClause::getCondition () const inline
Returns condition.
Definition at line 8133 of file OpenMPClause.h.
References clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >::getStmtAs().
used_children() [1/2]
OMPClause::child_range OMPNovariantsClause::used_children ()
Definition at line 328 of file OpenMPClause.cpp.
References clang::C, clang::OMPOneStmtClause< llvm::omp::OMPC_novariants, OMPClause >::children(), getAddrOfExprAsWritten(), and clang::OMPClauseWithPreInit::getPreInitStmt().
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPNovariantsClause::used_children () const inline
Definition at line 8136 of file OpenMPClause.h.
References Children, and used_children().
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 8105 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp