clang: clang::OMPClauseWithPreInit Class Reference
clang::OMPClauseWithPreInit Class Reference
Class that handles pre-initialization statement for some clauses, like 'shedule', 'firstprivate' etc.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Protected Member Functions
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Friends
class OMPClauseReader
Detailed Description
Class that handles pre-initialization statement for some clauses, like 'shedule', 'firstprivate' etc.
Definition at line 195 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPClauseWithPreInit()
clang::OMPClauseWithPreInit::OMPClauseWithPreInit (const OMPClause * This) inline protected
Definition at line 205 of file OpenMPClause.h.
References get().
Member Function Documentation
get() [1/2]
const OMPClauseWithPreInit * OMPClauseWithPreInit::get (const OMPClause * C) static
Definition at line 64 of file OpenMPClause.cpp.
References clang::C.
get() [2/2]
OMPClauseWithPreInit * OMPClauseWithPreInit::get (OMPClause * C) static
Definition at line 59 of file OpenMPClause.cpp.
References clang::C, and get().
Referenced by clang::Sema::ActOnOpenMPRegionEnd(), get(), and OMPClauseWithPreInit().
getCaptureRegion()
OpenMPDirectiveKind clang::OMPClauseWithPreInit::getCaptureRegion () const inline
Get capture region for the stmt in the clause.
Definition at line 225 of file OpenMPClause.h.
getPreInitStmt() [1/2]
Stmt * clang::OMPClauseWithPreInit::getPreInitStmt () inline
Get pre-initialization statement for the clause.
Definition at line 222 of file OpenMPClause.h.
getPreInitStmt() [2/2]
const Stmt * clang::OMPClauseWithPreInit::getPreInitStmt () const inline
Get pre-initialization statement for the clause.
Definition at line 219 of file OpenMPClause.h.
Referenced by getNumThreads(), clang::OMPFinalClause::used_children(), clang::OMPGrainsizeClause::used_children(), clang::OMPIfClause::used_children(), clang::OMPNocontextClause::used_children(), clang::OMPNovariantsClause::used_children(), clang::OMPNumTasksClause::used_children(), and clang::OMPPriorityClause::used_children().
setPreInitStmt()
void clang::OMPClauseWithPreInit::setPreInitStmt (Stmt * S, OpenMPDirectiveKind ThisRegion = llvm::omp::OMPD_unknown) inline protected
Set pre-initialization statement for the clause.
Definition at line 211 of file OpenMPClause.h.
Referenced by clang::OMPDeviceClause::OMPDeviceClause(), clang::OMPDistScheduleClause::OMPDistScheduleClause(), clang::OMPFilterClause::OMPFilterClause(), clang::OMPFinalClause::OMPFinalClause(), clang::OMPGrainsizeClause::OMPGrainsizeClause(), clang::OMPIfClause::OMPIfClause(), clang::OMPNocontextClause::OMPNocontextClause(), clang::OMPNovariantsClause::OMPNovariantsClause(), clang::OMPNumTasksClause::OMPNumTasksClause(), clang::OMPNumTeamsClause::OMPNumTeamsClause(), clang::OMPNumThreadsClause::OMPNumThreadsClause(), clang::OMPPriorityClause::OMPPriorityClause(), clang::OMPScheduleClause::OMPScheduleClause(), clang::OMPThreadLimitClause::OMPThreadLimitClause(), and clang::OMPXDynCGroupMemClause::OMPXDynCGroupMemClause().
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 196 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp