clang: clang::ento::loc::MemRegionVal Class Reference
clang::ento::loc::MemRegionVal Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
Public Member Functions
MemRegionVal (const MemRegion *r)
const MemRegion * getRegion () const
Get the underlining region.
const MemRegion * stripCasts (bool StripBaseCasts=true) const
Get the underlining region and strip casts.
template<typename REGION >
const REGION * getRegionAs () const
bool operator== (const MemRegionVal &R) const
bool operator!= (const MemRegionVal &R) const
Public Member Functions inherited from clang::ento::Loc
void dumpToStream (raw_ostream &Out) const
Public Member Functions inherited from clang::ento::DefinedSVal
bool isUnknown () const =delete
bool isUnknownOrUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::DefinedOrUnknownSVal
bool isUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::SVal
SVal ()=default
template<typename T >
T castAs () const
Convert to the specified SVal type, asserting that this SVal is of the desired type.
template<typename T >
std::optional< T > getAs () const
Convert to the specified SVal type, returning std::nullopt if this SVal is not of the desired type.
unsigned getRawKind () const
BaseKind getBaseKind () const
unsigned getSubKind () const
void Profile (llvm::FoldingSetNodeID &ID) const
bool operator== (SVal R) const
bool operator!= (SVal R) const
bool isUnknown () const
bool isUndef () const
bool isUnknownOrUndef () const
bool isValid () const
bool isConstant () const
bool isConstant (int I) const
bool isZeroConstant () const
const FunctionDecl * getAsFunctionDecl () const
getAsFunctionDecl - If this SVal is a MemRegionVal and wraps a CodeTextRegion wrapping a FunctionDecl, return that FunctionDecl.
SymbolRef getAsLocSymbol (bool IncludeBaseRegions=false) const
If this SVal is a location and wraps a symbol, return that SymbolRef.
SymbolRef getLocSymbolInBase () const
Get the symbol in the SVal or its base region.
SymbolRef getAsSymbol (bool IncludeBaseRegions=false) const
If this SVal wraps a symbol return that SymbolRef.
const llvm::APSInt * getAsInteger () const
If this SVal is loc::ConcreteInt or nonloc::ConcreteInt, return a pointer to APSInt which is held in it.
const MemRegion * getAsRegion () const
void printJson (raw_ostream &Out, bool AddQuotes) const
printJson - Pretty-prints in JSON format.
void dumpToStream (raw_ostream &OS) const
void dump () const
llvm::iterator_range< SymExpr::symbol_iterator > symbols () const
QualType getType (const ASTContext &) const
Try to get a reasonable type for the given value.
Static Public Member Functions
static bool classof (SVal V)
static bool classof (Loc V)
Static Public Member Functions inherited from clang::ento::Loc
static bool isLocType (QualType T)
static bool classof (SVal V)
Static Public Member Functions inherited from clang::ento::DefinedSVal
static bool classof (SVal V)
Static Public Member Functions inherited from clang::ento::DefinedOrUnknownSVal
static bool classof (SVal V)
Additional Inherited Members
Public Types inherited from clang::ento::SVal
enum BaseKind
enum { BaseBits = 2 , BaseMask = 0b11 }
Protected Member Functions inherited from clang::ento::Loc
Loc (unsigned SubKind, const void *D)
Protected Member Functions inherited from clang::ento::DefinedSVal
DefinedSVal (const void *d, bool isLoc, unsigned ValKind)
Protected Member Functions inherited from clang::ento::DefinedOrUnknownSVal
DefinedOrUnknownSVal (const void *d, bool isLoc, unsigned ValKind)
DefinedOrUnknownSVal (BaseKind k, void *D=nullptr)
Protected Member Functions inherited from clang::ento::SVal
SVal (const void *d, bool isLoc, unsigned ValKind)
SVal (BaseKind k, const void *D=nullptr)
Protected Attributes inherited from clang::ento::SVal
const void * Data = nullptr
unsigned Kind = 0
The lowest 2 bits are a BaseKind (0 – 3).
Detailed Description
Definition at line 501 of file SVals.h.
Constructor & Destructor Documentation
MemRegionVal()
clang::ento::loc::MemRegionVal::MemRegionVal (const MemRegion * r) inline explicit
Definition at line 503 of file SVals.h.
Member Function Documentation
classof() [1/2]
static bool clang::ento::loc::MemRegionVal::classof (Loc V) inline static
Definition at line 532 of file SVals.h.
References V.
classof() [2/2]
static bool clang::ento::loc::MemRegionVal::classof (SVal V) inline static
Definition at line 528 of file SVals.h.
References V.
getRegion()
const MemRegion * clang::ento::loc::MemRegionVal::getRegion () const inline
Get the underlining region.
Definition at line 508 of file SVals.h.
References clang::ento::SVal::Data.
Referenced by getRegionAs(), operator!=(), operator==(), and stripCasts().
getRegionAs()
template<typename REGION > const REGION * clang::ento::loc::MemRegionVal::getRegionAs () const inline
Definition at line 516 of file SVals.h.
References getRegion().
operator!=()
bool clang::ento::loc::MemRegionVal::operator!= (const MemRegionVal & R) const inline
Definition at line 524 of file SVals.h.
References getRegion().
operator==()
bool clang::ento::loc::MemRegionVal::operator== (const MemRegionVal & R) const inline
Definition at line 520 of file SVals.h.
References getRegion().
stripCasts()
const MemRegion * loc::MemRegionVal::stripCasts (bool StripBaseCasts = true) const
Get the underlining region and strip casts.
Definition at line 192 of file SVals.cpp.
References getRegion(), and clang::ento::MemRegion::StripCasts().
Referenced by isSelfVar().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h
lib/StaticAnalyzer/Core/SVals.cpp