clang: clang::format::BreakableLineCommentSection Class Reference
clang::format::BreakableLineCommentSection Class Reference
#include "/root/llvm-project/clang/lib/Format/BreakableToken.h"
Public Member Functions
BreakableLineCommentSection (const FormatToken &Token, unsigned StartColumn, bool InPPDirective, encoding::Encoding Encoding, const FormatStyle &Style)
unsigned getRangeLength (unsigned LineIndex, unsigned Offset, StringRef::size_type Length, unsigned StartColumn) const override
Returns the number of columns required to format the text in the byte range [Offset, Offset + Length).
unsigned getContentStartColumn (unsigned LineIndex, bool Break) const override
Returns the column at which content in line LineIndex starts, assuming no reflow.
void insertBreak (unsigned LineIndex, unsigned TailOffset, Split Split, unsigned ContentIndent, WhitespaceManager &Whitespaces) const override
Emits the previously retrieved Split via Whitespaces.
Split getReflowSplit (unsigned LineIndex, const llvm::Regex &CommentPragmasRegex) const override
Returns a whitespace range (offset, length) of the content at LineIndex such that the content of that line is reflown to the end of the previous one.
void reflow (unsigned LineIndex, WhitespaceManager &Whitespaces) const override
Reflows the current line into the end of the previous one.
void adaptStartOfLine (unsigned LineIndex, WhitespaceManager &Whitespaces) const override
Replaces the whitespace between LineIndex-1 and LineIndex.
void updateNextToken (LineState &State) const override
Updates the next token of State to the next token after this one.
bool mayReflow (unsigned LineIndex, const llvm::Regex &CommentPragmasRegex) const override
Public Member Functions inherited from clang::format::BreakableComment
bool supportsReflow () const override
Returns whether the token supports reflowing text.
unsigned getLineCount () const override
Returns the number of lines in this token in the original code.
Split getSplit (unsigned LineIndex, unsigned TailOffset, unsigned ColumnLimit, unsigned ContentStartColumn, const llvm::Regex &CommentPragmasRegex) const override
Returns a range (offset, length) at which to break the line at LineIndex, if previously broken at TailOffset.
void compressWhitespace (unsigned LineIndex, unsigned TailOffset, Split Split, WhitespaceManager &Whitespaces) const override
Replaces the whitespace range described by Split with a single space.
Public Member Functions inherited from clang::format::BreakableToken
virtual ~BreakableToken ()
virtual unsigned getRemainingLength (unsigned LineIndex, unsigned Offset, unsigned StartColumn) const
Returns the number of columns required to format the text following the byte Offset in the line LineIndex, including potentially unbreakable sequences of tokens following after the end of the token.
virtual unsigned getContentIndent (unsigned LineIndex) const
Returns additional content indent required for the second line after the content at line LineIndex is broken.
unsigned getLengthAfterCompression (unsigned RemainingTokenColumns, Split Split) const
Returns the number of columns needed to format RemainingTokenColumns, assuming that Split is within the range measured by RemainingTokenColumns, and that the whitespace in Split is reduced to a single space.
virtual bool introducesBreakBeforeToken () const
Returns whether there will be a line break at the start of the token.
virtual Split getSplitAfterLastLine (unsigned TailOffset) const
Returns a whitespace range (offset, length) of the content at the last line that needs to be reformatted after the last line has been reformatted.
void replaceWhitespaceAfterLastLine (unsigned TailOffset, Split SplitAfterLastLine, WhitespaceManager &Whitespaces) const
Replaces the whitespace from SplitAfterLastLine on the last line after the last line has been formatted by performing a reformatting.
Additional Inherited Members
Public Types inherited from clang::format::BreakableToken
typedef std::pair< StringRef::size_type, unsigned > Split
Contains starting character index and length of split.
Protected Member Functions inherited from clang::format::BreakableComment
BreakableComment (const FormatToken &Token, unsigned StartColumn, bool InPPDirective, encoding::Encoding Encoding, const FormatStyle &Style)
Creates a breakable token for a comment.
const FormatToken & tokenAt (unsigned LineIndex) const
Protected Member Functions inherited from clang::format::BreakableToken
BreakableToken (const FormatToken &Tok, bool InPPDirective, encoding::Encoding Encoding, const FormatStyle &Style)
Protected Attributes inherited from clang::format::BreakableComment
SmallVector< StringRef, 16 > Lines
SmallVector< StringRef, 16 > Content
SmallVector< FormatToken *, 16 > Tokens
SmallVector< int, 16 > ContentColumn
unsigned StartColumn
StringRef ReflowPrefix = " "
Protected Attributes inherited from clang::format::BreakableToken
const FormatToken & Tok
const bool InPPDirective
const encoding::Encoding Encoding
const FormatStyle & Style
Detailed Description
Definition at line 436 of file BreakableToken.h.
Constructor & Destructor Documentation
BreakableLineCommentSection()
clang::format::BreakableLineCommentSection::BreakableLineCommentSection (const FormatToken & Token, unsigned StartColumn, bool InPPDirective, encoding::Encoding Encoding, const FormatStyle & Style)
Definition at line 749 of file BreakableToken.cpp.
References clang::format::Blanks, clang::format::encoding::columnWidth(), clang::format::encoding::columnWidthWithTabs(), clang::format::BreakableComment::Content, clang::format::BreakableComment::ContentColumn, clang::format::encoding::getCodePointNumBytes(), clang::format::getLineCommentIndentPrefix(), clang::format::FormatToken::is(), clang::isHorizontalWhitespace(), clang::isPunctuation(), clang::format::BreakableComment::Lines, clang::format::FormatToken::Next, clang::format::BreakableComment::StartColumn, clang::format::switchesFormatting(), clang::format::BreakableToken::Tok, clang::format::BreakableComment::Tokens, and TokenText.
Member Function Documentation
adaptStartOfLine()
void clang::format::BreakableLineCommentSection::adaptStartOfLine (unsigned LineIndex, WhitespaceManager & Whitespaces) const override virtual
Replaces the whitespace between LineIndex-1 and LineIndex.
Reimplemented from clang::format::BreakableToken.
Definition at line 990 of file BreakableToken.cpp.
References clang::format::BreakableComment::Content, clang::format::BreakableComment::ContentColumn, clang::format::BreakableComment::Lines, clang::format::BreakableComment::tokenAt(), and clang::format::BreakableComment::Tokens.
getContentStartColumn()
unsigned clang::format::BreakableLineCommentSection::getContentStartColumn (unsigned LineIndex, bool Break) const override virtual
Returns the column at which content in line LineIndex starts, assuming no reflow.
If Break is true, returns the column at which the line should start after the line break. If Break is false, returns the column at which the line itself will start.
Implements clang::format::BreakableToken.
Definition at line 907 of file BreakableToken.cpp.
References clang::format::BreakableComment::ContentColumn.
getRangeLength()
unsigned clang::format::BreakableLineCommentSection::getRangeLength (unsigned LineIndex, unsigned Offset, StringRef::size_type Length, unsigned StartColumn) const override virtual
Returns the number of columns required to format the text in the byte range [Offset, Offset + Length).
Offset is the byte offset from the start of the content of the line at LineIndex.
StartColumn is the column at which the text starts in the formatted file, needed to compute tab stops correctly.
Implements clang::format::BreakableToken.
Definition at line 898 of file BreakableToken.cpp.
References clang::format::encoding::columnWidthWithTabs(), clang::format::BreakableComment::Content, Offset, and clang::format::BreakableComment::StartColumn.
getReflowSplit()
BreakableComment::Split clang::format::BreakableLineCommentSection::getReflowSplit (unsigned LineIndex, const llvm::Regex & CommentPragmasRegex) const override virtual
Returns a whitespace range (offset, length) of the content at LineIndex such that the content of that line is reflown to the end of the previous one.
Returning (StringRef::npos, 0) indicates reflowing is not possible.
The range will include any whitespace preceding the specified line's content.
If the split is not contained within one token, for example when reflowing line comments, returns (0, <length>).
Reimplemented from clang::format::BreakableToken.
Definition at line 927 of file BreakableToken.cpp.
References clang::format::Blanks, clang::format::BreakableComment::Content, and mayReflow().
insertBreak()
void clang::format::BreakableLineCommentSection::insertBreak (unsigned LineIndex, unsigned TailOffset, Split Split, unsigned ContentIndent, WhitespaceManager & Whitespaces) const override virtual
Emits the previously retrieved Split via Whitespaces.
Implements clang::format::BreakableToken.
Definition at line 912 of file BreakableToken.cpp.
References clang::format::BreakableComment::Content, clang::format::BreakableComment::ContentColumn, clang::format::BreakableToken::InPPDirective, Text, clang::format::BreakableComment::tokenAt(), and clang::format::FormatToken::TokenText.
mayReflow()
bool clang::format::BreakableLineCommentSection::mayReflow (unsigned LineIndex, const llvm::Regex & CommentPragmasRegex) const override virtual
Implements clang::format::BreakableComment.
Definition at line 1036 of file BreakableToken.cpp.
References clang::format::BreakableComment::Content, clang::format::FormatToken::Finalized, clang::format::BreakableComment::Lines, clang::format::mayReflowContent(), clang::format::switchesFormatting(), clang::format::BreakableToken::Tok, and clang::format::BreakableComment::tokenAt().
Referenced by getReflowSplit().
reflow()
void clang::format::BreakableLineCommentSection::reflow (unsigned LineIndex, WhitespaceManager & Whitespaces) const override virtual
Reflows the current line into the end of the previous one.
Reimplemented from clang::format::BreakableToken.
Definition at line 941 of file BreakableToken.cpp.
References clang::format::BreakableComment::Content, clang::format::BreakableComment::Lines, Offset, clang::format::BreakableComment::ReflowPrefix, clang::format::BreakableComment::StartColumn, clang::format::BreakableComment::tokenAt(), clang::format::BreakableComment::Tokens, and clang::format::FormatToken::TokenText.
updateNextToken()
void clang::format::BreakableLineCommentSection::updateNextToken (LineState & State) const override virtual
Updates the next token of State to the next token after this one.
This can be used when this token manages a set of underlying tokens as a unit and is responsible for the formatting of the them.
Reimplemented from clang::format::BreakableToken.
Definition at line 1031 of file BreakableToken.cpp.
References clang::format::FormatToken::Next.
The documentation for this class was generated from the following files:
lib/Format/BreakableToken.h
lib/Format/BreakableToken.cpp