clang: clang::DeclGroup Class Reference
clang::DeclGroup Class Reference final
#include "clang/AST/DeclGroup.h"
Public Member Functions
unsigned size () const
Decl *& operator[] (unsigned i)
Decl *const & operator[] (unsigned i) const
Static Public Member Functions
static DeclGroup * Create (ASTContext &C, Decl **Decls, unsigned NumDecls)
Public Attributes
friend TrailingObjects
Detailed Description
Definition at line 25 of file DeclGroup.h.
Member Function Documentation
Create()
DeclGroup * DeclGroup::Create (ASTContext & C, Decl ** Decls, unsigned NumDecls) static
Definition at line 20 of file DeclGroup.cpp.
References clang::C.
Referenced by clang::DeclGroupRef::Create().
operator[]() [1/2]
Decl *& clang::DeclGroup::operator[] (unsigned i) inline
Definition at line 40 of file DeclGroup.h.
operator[]() [2/2]
Decl *const & clang::DeclGroup::operator[] (unsigned i) const inline
Definition at line 45 of file DeclGroup.h.
size()
unsigned clang::DeclGroup::size () const inline
Definition at line 38 of file DeclGroup.h.
Referenced by clang::DeclGroupRef::end(), and clang::DeclGroupRef::end().
Member Data Documentation
TrailingObjects
friend clang::DeclGroup::TrailingObjects
Definition at line 34 of file DeclGroup.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclGroup.h
lib/AST/DeclGroup.cpp