clang: clang::SimpleASTReaderListener Class Reference
clang::SimpleASTReaderListener Class Reference
ASTReaderListenter implementation to set SuggestedPredefines of ASTReader which is required to use a pch file.
#include "clang/Serialization/ASTReader.h"
Public Member Functions
SimpleASTReaderListener (Preprocessor &PP)
bool ReadPreprocessorOptions (const PreprocessorOptions &PPOpts, bool Complain, std::string &SuggestedPredefines) override
Receives the preprocessor options.
Public Member Functions inherited from clang::ASTReaderListener
virtual ~ASTReaderListener ()
virtual bool ReadFullVersionInformation (StringRef FullVersion)
Receives the full Clang version information.
virtual void ReadModuleName (StringRef ModuleName)
virtual void ReadModuleMapFile (StringRef ModuleMapPath)
virtual bool ReadLanguageOptions (const LangOptions &LangOpts, bool Complain, bool AllowCompatibleDifferences)
Receives the language options.
virtual bool ReadTargetOptions (const TargetOptions &TargetOpts, bool Complain, bool AllowCompatibleDifferences)
Receives the target options.
virtual bool ReadDiagnosticOptions (IntrusiveRefCntPtr< DiagnosticOptions > DiagOpts, bool Complain)
Receives the diagnostic options.
virtual bool ReadFileSystemOptions (const FileSystemOptions &FSOpts, bool Complain)
Receives the file system options.
virtual bool ReadHeaderSearchOptions (const HeaderSearchOptions &HSOpts, StringRef SpecificModuleCachePath, bool Complain)
Receives the header search options.
virtual bool ReadHeaderSearchPaths (const HeaderSearchOptions &HSOpts, bool Complain)
Receives the header search paths.
virtual void ReadCounter (const serialization::ModuleFile &M, unsigned Value)
Receives COUNTER value.
virtual void visitModuleFile (StringRef Filename, serialization::ModuleKind Kind)
This is called for each AST file loaded.
virtual bool needsInputFileVisitation ()
Returns true if this ASTReaderListener wants to receive the input files of the AST file via visitInputFile, false otherwise.
virtual bool needsSystemInputFileVisitation ()
Returns true if this ASTReaderListener wants to receive the system input files of the AST file via visitInputFile, false otherwise.
virtual bool visitInputFile (StringRef Filename, bool isSystem, bool isOverridden, bool isExplicitModule)
if needsInputFileVisitation returns true, this is called for each non-system input file of the AST File.
virtual bool needsImportVisitation () const
Returns true if this ASTReaderListener wants to receive the imports of the AST file via visitImport, false otherwise.
virtual void visitImport (StringRef ModuleName, StringRef Filename)
If needsImportVisitation returns true, this is called for each AST file imported by this AST file.
virtual void readModuleFileExtension (const ModuleFileExtensionMetadata &Metadata)
Indicates that a particular module file extension has been read.
Detailed Description
ASTReaderListenter implementation to set SuggestedPredefines of ASTReader which is required to use a pch file.
This is the replacement of PCHValidator or SimplePCHValidator when using a pch file without validating it.
Definition at line 322 of file ASTReader.h.
Constructor & Destructor Documentation
SimpleASTReaderListener()
clang::SimpleASTReaderListener::SimpleASTReaderListener (Preprocessor & PP) inline
Definition at line 326 of file ASTReader.h.
Member Function Documentation
ReadPreprocessorOptions()
bool SimpleASTReaderListener::ReadPreprocessorOptions (const PreprocessorOptions & PPOpts, bool Complain, std::string & SuggestedPredefines) override virtual
Receives the preprocessor options.
Parameters
SuggestedPredefines Can be filled in with the set of predefines that are suggested by the preprocessor options. Typically only used when loading a precompiled header.
Returns
true to indicate the preprocessor options are invalid, or false otherwise.
Reimplemented from clang::ASTReaderListener.
Definition at line 809 of file ASTReader.cpp.
References checkPreprocessorOptions(), clang::Preprocessor::getFileManager(), clang::Preprocessor::getLangOpts(), clang::Preprocessor::getPreprocessorOpts(), and OptionValidateNone.
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTReader.h
lib/Serialization/ASTReader.cpp