clang: clang::ento::ProgramStateManager Class Reference
clang::ento::ProgramStateManager Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
Public Member Functions
ProgramStateManager (ASTContext &Ctx, StoreManagerCreator CreateStoreManager, ConstraintManagerCreator CreateConstraintManager, llvm::BumpPtrAllocator &alloc, ExprEngine *expreng)
~ProgramStateManager ()
ProgramStateRef getInitialState (const LocationContext *InitLoc)
ASTContext & getContext ()
const ASTContext & getContext () const
BasicValueFactory & getBasicVals ()
SValBuilder & getSValBuilder ()
const SValBuilder & getSValBuilder () const
SymbolManager & getSymbolManager ()
const SymbolManager & getSymbolManager () const
llvm::BumpPtrAllocator & getAllocator ()
MemRegionManager & getRegionManager ()
const MemRegionManager & getRegionManager () const
CallEventManager & getCallEventManager ()
StoreManager & getStoreManager ()
ConstraintManager & getConstraintManager ()
ExprEngine & getOwningEngine ()
ProgramStateRef removeDeadBindingsFromEnvironmentAndStore (ProgramStateRef St, const StackFrameContext *LCtx, SymbolReaper &SymReaper)
SVal ArrayToPointer (Loc Array, QualType ElementTy)
ProgramStateRef addGDM (ProgramStateRef St, void *Key, void *Data)
ProgramStateRef removeGDM (ProgramStateRef state, void *Key)
void iterBindings (ProgramStateRef state, StoreManager::BindingsHandler &F)
ProgramStateRef getPersistentState (ProgramState &Impl)
ProgramStateRef getPersistentStateWithGDM (ProgramStateRef FromState, ProgramStateRef GDMState)
bool haveEqualConstraints (ProgramStateRef S1, ProgramStateRef S2) const
bool haveEqualEnvironments (ProgramStateRef S1, ProgramStateRef S2) const
bool haveEqualStores (ProgramStateRef S1, ProgramStateRef S2) const
template<typename T >
ProgramStateRef set (ProgramStateRef st, typename ProgramStateTrait< T >::data_type D)
template<typename T >
ProgramStateRef set (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::value_type V, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef add (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef remove (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef remove (ProgramStateRef st)
void * FindGDMContext (void *index, void *(*CreateContext)(llvm::BumpPtrAllocator &), void(*DeleteContext)(void *))
template<typename T >
ProgramStateTrait< T >::context_type get_context ()
Friends
class ProgramState
void ProgramStateRelease (const ProgramState *state)
Decrement the number of times this state is referenced.
Detailed Description
Definition at line 503 of file ProgramState.h.
Constructor & Destructor Documentation
ProgramStateManager()
ProgramStateManager::ProgramStateManager (ASTContext & Ctx, StoreManagerCreator CreateStoreManager, ConstraintManagerCreator CreateConstraintManager, llvm::BumpPtrAllocator & alloc, ExprEngine * expreng)
Definition at line 72 of file ProgramState.cpp.
~ProgramStateManager()
ProgramStateManager::~ProgramStateManager ()
Definition at line 85 of file ProgramState.cpp.
Member Function Documentation
add()
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::add (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 656 of file ProgramState.h.
References addGDM(), and clang::C.
Referenced by clang::ento::ProgramState::add().
addGDM()
ProgramStateRef ProgramStateManager::addGDM (ProgramStateRef St, void * Key, void * Data)
Definition at line 520 of file ProgramState.cpp.
References Data, and getPersistentState().
Referenced by add(), remove(), set(), and set().
ArrayToPointer()
SVal clang::ento::ProgramStateManager::ArrayToPointer (Loc Array, QualType ElementTy) inline
Definition at line 590 of file ProgramState.h.
FindGDMContext()
void * ProgramStateManager::FindGDMContext (void * index, void *(* CreateContext)(llvm::BumpPtrAllocator &), void(* DeleteContext)(void *))
Definition at line 507 of file ProgramState.cpp.
Referenced by get_context().
get_context()
template<typename T > ProgramStateTrait< T >::context_type clang::ento::ProgramStateManager::get_context () inline
Definition at line 682 of file ProgramState.h.
References FindGDMContext().
Referenced by clang::ento::ProgramState::get_context().
getAllocator()
llvm::BumpPtrAllocator & clang::ento::ProgramStateManager::getAllocator () inline
Definition at line 568 of file ProgramState.h.
getBasicVals()
BasicValueFactory & clang::ento::ProgramStateManager::getBasicVals () inline
Definition at line 549 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::getBasicVals(), and clang::ento::ProgramState::getBasicVals().
getCallEventManager()
CallEventManager & clang::ento::ProgramStateManager::getCallEventManager () inline
Definition at line 577 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCXXDeleteExpr(), clang::ento::ExprEngine::VisitCXXDestructor(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), and clang::ento::ExprEngine::VisitObjCMessage().
getConstraintManager()
ConstraintManager & clang::ento::ProgramStateManager::getConstraintManager () inline
Definition at line 580 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::getConstraintManager(), clang::ento::ProgramState::getConstraintManager(), and clang::ento::ProgramState::printJson().
getContext() [1/2]
ASTContext & clang::ento::ProgramStateManager::getContext () inline
Definition at line 546 of file ProgramState.h.
Referenced by clang::ento::StoreManager::castRegion(), and clang::ento::ProgramState::printJson().
getContext() [2/2]
const ASTContext & clang::ento::ProgramStateManager::getContext () const inline
Definition at line 547 of file ProgramState.h.
getInitialState()
ProgramStateRef ProgramStateManager::getInitialState (const LocationContext * InitLoc)
Definition at line 394 of file ProgramState.cpp.
References clang::ento::EnvironmentManager::getInitialEnvironment(), and getPersistentState().
Referenced by clang::ento::ExprEngine::getInitialState().
getOwningEngine()
ExprEngine & clang::ento::ProgramStateManager::getOwningEngine () inline
Definition at line 581 of file ProgramState.h.
Referenced by clang::ento::ProgramState::bindDefaultInitial(), clang::ento::ProgramState::bindDefaultZero(), clang::ento::ProgramState::bindLoc(), clang::ento::ProgramState::getAnalysisManager(), and clang::ento::ProgramState::printJson().
getPersistentState()
ProgramStateRef ProgramStateManager::getPersistentState (ProgramState & Impl)
Definition at line 411 of file ProgramState.cpp.
References ProgramState.
Referenced by addGDM(), clang::ento::ProgramState::BindExpr(), getInitialState(), getPersistentStateWithGDM(), removeDeadBindingsFromEnvironmentAndStore(), and removeGDM().
getPersistentStateWithGDM()
ProgramStateRef ProgramStateManager::getPersistentStateWithGDM (ProgramStateRef FromState, ProgramStateRef GDMState)
Definition at line 403 of file ProgramState.cpp.
References getPersistentState().
Referenced by clang::ento::ExprEngine::removeDead().
getRegionManager() [1/2]
MemRegionManager & clang::ento::ProgramStateManager::getRegionManager () inline
Definition at line 570 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getRegion().
getRegionManager() [2/2]
const MemRegionManager & clang::ento::ProgramStateManager::getRegionManager () const inline
Definition at line 573 of file ProgramState.h.
getStoreManager()
StoreManager & clang::ento::ProgramStateManager::getStoreManager () inline
Definition at line 579 of file ProgramState.h.
Referenced by evalComparison(), clang::ento::SValBuilder::getCastedMemRegionVal(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ExprEngine::getStoreManager(), clang::ento::ProgramState::printJson(), clang::ento::ProgramState::ProgramState(), clang::ento::ProgramState::ProgramState(), clang::ento::ExprEngine::VisitCast(), and clang::ento::ProgramState::~ProgramState().
getSValBuilder() [1/2]
SValBuilder & clang::ento::ProgramStateManager::getSValBuilder () inline
Definition at line 553 of file ProgramState.h.
Referenced by clang::ento::ProgramState::areEqual(), clang::ento::SimpleConstraintManager::assumeInternal(), clang::ento::iterator::assumeNoOverflow(), clang::ento::CreateRangeConstraintManager(), clang::ento::CreateZ3ConstraintManager(), doRearrangeUnchecked(), evalComparison(), clang::ento::CallEventManager::getCaller(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), isInRelation(), isWithinConstantOverflowBounds(), clang::ento::simplifyToSVal(), tryRearrange(), and wasRegionOfInterestModifiedAt().
getSValBuilder() [2/2]
const SValBuilder & clang::ento::ProgramStateManager::getSValBuilder () const inline
Definition at line 557 of file ProgramState.h.
getSymbolManager() [1/2]
SymbolManager & clang::ento::ProgramStateManager::getSymbolManager () inline
Definition at line 561 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getSymbolManager().
getSymbolManager() [2/2]
const SymbolManager & clang::ento::ProgramStateManager::getSymbolManager () const inline
Definition at line 564 of file ProgramState.h.
haveEqualConstraints()
bool clang::ento::ProgramStateManager::haveEqualConstraints (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 608 of file ProgramState.h.
Referenced by clang::ento::ConditionBRVisitor::VisitTrueTest().
haveEqualEnvironments()
bool clang::ento::ProgramStateManager::haveEqualEnvironments (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 612 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::removeDead().
haveEqualStores()
bool clang::ento::ProgramStateManager::haveEqualStores (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 616 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::removeDead().
iterBindings()
void clang::ento::ProgramStateManager::iterBindings (ProgramStateRef state, StoreManager::BindingsHandler & F) inline
Definition at line 600 of file ProgramState.h.
Referenced by GetAllocationSite(), and getAllVarBindingsForSymbol().
remove() [1/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::remove (ProgramStateRef st) inline
Definition at line 673 of file ProgramState.h.
References removeGDM().
remove() [2/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::remove (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 664 of file ProgramState.h.
References addGDM(), and clang::C.
Referenced by clang::ento::ProgramState::remove(), clang::ento::ProgramState::remove(), and clang::ento::ProgramState::remove().
removeDeadBindingsFromEnvironmentAndStore()
ProgramStateRef ProgramStateManager::removeDeadBindingsFromEnvironmentAndStore (ProgramStateRef St, const StackFrameContext * LCtx, SymbolReaper & SymReaper)
Definition at line 91 of file ProgramState.cpp.
References getPersistentState(), clang::ento::ProgramState::getStore(), clang::ento::EnvironmentManager::removeDeadBindings(), and clang::ento::SymbolReaper::setReapedStore().
Referenced by clang::ento::ExprEngine::removeDead().
removeGDM()
ProgramStateRef ProgramStateManager::removeGDM (ProgramStateRef state, void * Key)
Definition at line 532 of file ProgramState.cpp.
References getPersistentState().
Referenced by remove().
set() [1/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::set (ProgramStateRef st, typename ProgramStateTrait< T >::data_type D) inline
Definition at line 640 of file ProgramState.h.
References addGDM().
Referenced by clang::ento::ProgramState::set(), clang::ento::ProgramState::set(), and clang::ento::ProgramState::set().
set() [2/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::set (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::value_type V, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 646 of file ProgramState.h.
References addGDM(), clang::C, and V.
Friends And Related Symbol Documentation
ProgramState
friend class ProgramState friend
Definition at line 504 of file ProgramState.h.
Referenced by getPersistentState().
ProgramStateRelease
void ProgramStateRelease (const ProgramState * state) friend
Decrement the number of times this state is referenced.
Definition at line 35 of file ProgramState.cpp.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h
lib/StaticAnalyzer/Core/ProgramState.cpp