clang: clang::DeclSpec Class Reference
clang::DeclSpec Class Reference
Captures information about "declaration specifiers".
#include "clang/Sema/DeclSpec.h"
Public Types
enum SCS {
SCS_unspecified = 0 , SCS_typedef , SCS_extern , SCS_static ,
SCS_auto , SCS_register , SCS_private_extern , SCS_mutable
}
storage-class-specifier
enum TSC { TSC_unspecified , TSC_imaginary , TSC_complex }
enum TQ {
TQ_unspecified = 0 , TQ_const = 1 , TQ_restrict = 2 , TQ_volatile = 4 ,
TQ_unaligned = 8 , TQ_atomic = 16
}
enum ParsedSpecifiers {
PQ_None = 0 , PQ_StorageClassSpecifier = 1 , PQ_TypeSpecifier = 2 , PQ_TypeQualifier = 4 ,
PQ_FunctionSpecifier = 8
}
ParsedSpecifiers - Flags to query which specifiers were applied.
enum FriendSpecified : bool { No , Yes }
typedef ThreadStorageClassSpecifier TSCS
typedef TypeSpecifierType TST
Public Member Functions
DeclSpec (AttributeFactory &attrFactory)
SCS getStorageClassSpec () const
TSCS getThreadStorageClassSpec () const
bool isExternInLinkageSpec () const
void setExternInLinkageSpec (bool Value)
SourceLocation getStorageClassSpecLoc () const
SourceLocation getThreadStorageClassSpecLoc () const
void ClearStorageClassSpecs ()
void ClearTypeSpecType ()
TypeSpecifierWidth getTypeSpecWidth () const
TSC getTypeSpecComplex () const
TypeSpecifierSign getTypeSpecSign () const
TST getTypeSpecType () const
bool isTypeAltiVecVector () const
bool isTypeAltiVecPixel () const
bool isTypeAltiVecBool () const
bool isTypeSpecOwned () const
bool isTypeRep () const
bool isTypeSpecPipe () const
bool isTypeSpecSat () const
bool isConstrainedAuto () const
ParsedType getRepAsType () const
Decl * getRepAsDecl () const
Expr * getRepAsExpr () const
TemplateIdAnnotation * getRepAsTemplateId () const
CXXScopeSpec & getTypeSpecScope ()
const CXXScopeSpec & getTypeSpecScope () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getTypeSpecWidthLoc () const
SourceRange getTypeSpecWidthRange () const
SourceLocation getTypeSpecComplexLoc () const
SourceLocation getTypeSpecSignLoc () const
SourceLocation getTypeSpecTypeLoc () const
SourceLocation getAltiVecLoc () const
SourceLocation getTypeSpecSatLoc () const
SourceLocation getTypeSpecTypeNameLoc () const
SourceRange getTypeofParensRange () const
void setTypeArgumentRange (SourceRange range)
bool hasAutoTypeSpec () const
bool hasTagDefinition () const
unsigned getTypeQualifiers () const
getTypeQualifiers - Return a set of TQs.
SourceLocation getConstSpecLoc () const
SourceLocation getRestrictSpecLoc () const
SourceLocation getVolatileSpecLoc () const
SourceLocation getAtomicSpecLoc () const
SourceLocation getUnalignedSpecLoc () const
SourceLocation getPipeLoc () const
void ClearTypeQualifiers ()
Clear out all of the type qualifiers.
bool isInlineSpecified () const
SourceLocation getInlineSpecLoc () const
ExplicitSpecifier getExplicitSpecifier () const
bool isVirtualSpecified () const
SourceLocation getVirtualSpecLoc () const
bool hasExplicitSpecifier () const
SourceLocation getExplicitSpecLoc () const
SourceRange getExplicitSpecRange () const
bool isNoreturnSpecified () const
SourceLocation getNoreturnSpecLoc () const
void ClearFunctionSpecs ()
void forEachCVRUQualifier (llvm::function_ref< void(TQ, StringRef, SourceLocation)> Handle)
This method calls the passed in handler on each CVRU qual being set.
void forEachQualifier (llvm::function_ref< void(TQ, StringRef, SourceLocation)> Handle)
This method calls the passed in handler on each qual being set.
bool hasTypeSpecifier () const
Return true if any type-specifier has been found.
unsigned getParsedSpecifiers () const
Return a bitmask of which flavors of specifiers this DeclSpec includes.
bool isEmpty () const
isEmpty - Return true if this declaration specifier is completely empty: no tokens were parsed in the production of it.
void SetRangeStart (SourceLocation Loc)
void SetRangeEnd (SourceLocation Loc)
bool SetStorageClassSpec (Sema &S, SCS SC, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
These methods set the specified attribute of the DeclSpec and return false if there was no error.
bool SetStorageClassSpecThread (TSCS TSC, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetTypeSpecWidth (TypeSpecifierWidth W, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
These methods set the specified attribute of the DeclSpec, but return true and ignore the request if invalid (e.g.
bool SetTypeSpecComplex (TSC C, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetTypeSpecSign (TypeSpecifierSign S, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, ParsedType Rep, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, TypeResult Rep, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, Decl *Rep, bool Owned, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation TagKwLoc, SourceLocation TagNameLoc, const char *&PrevSpec, unsigned &DiagID, ParsedType Rep, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation TagKwLoc, SourceLocation TagNameLoc, const char *&PrevSpec, unsigned &DiagID, Decl *Rep, bool Owned, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, TemplateIdAnnotation *Rep, const PrintingPolicy &Policy)
bool SetTypeSpecType (TST T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, Expr *Rep, const PrintingPolicy &policy)
bool SetTypeAltiVecVector (bool isAltiVecVector, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetTypeAltiVecPixel (bool isAltiVecPixel, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetTypeAltiVecBool (bool isAltiVecBool, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetTypePipe (bool isPipe, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetBitIntType (SourceLocation KWLoc, Expr *BitWidth, const char *&PrevSpec, unsigned &DiagID, const PrintingPolicy &Policy)
bool SetTypeSpecSat (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetTypeSpecError ()
void UpdateDeclRep (Decl *Rep)
void UpdateTypeRep (ParsedType Rep)
void UpdateExprRep (Expr *Rep)
bool SetTypeQual (TQ T, SourceLocation Loc)
bool SetTypeQual (TQ T, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, const LangOptions &Lang)
bool setFunctionSpecInline (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool setFunctionSpecForceInline (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool setFunctionSpecVirtual (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool setFunctionSpecExplicit (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID, ExplicitSpecifier ExplicitSpec, SourceLocation CloseParenLoc)
bool setFunctionSpecNoreturn (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetFriendSpec (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool setModulePrivateSpec (SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
bool SetConstexprSpec (ConstexprSpecKind ConstexprKind, SourceLocation Loc, const char *&PrevSpec, unsigned &DiagID)
FriendSpecified isFriendSpecified () const
SourceLocation getFriendSpecLoc () const
bool isModulePrivateSpecified () const
SourceLocation getModulePrivateSpecLoc () const
ConstexprSpecKind getConstexprSpecifier () const
SourceLocation getConstexprSpecLoc () const
bool hasConstexprSpecifier () const
void ClearConstexprSpec ()
AttributePool & getAttributePool () const
void addAttributes (const ParsedAttributesView &AL)
Concatenates two attribute lists.
bool hasAttributes () const
ParsedAttributes & getAttributes ()
const ParsedAttributes & getAttributes () const
void takeAttributesFrom (ParsedAttributes &attrs)
void Finish (Sema &S, const PrintingPolicy &Policy)
Finish - This does final analysis of the declspec, issuing diagnostics for things like "_Imaginary" (lacking an FP type).
const WrittenBuiltinSpecs & getWrittenBuiltinSpecs () const
ObjCDeclSpec * getObjCQualifiers () const
void setObjCQualifiers (ObjCDeclSpec *quals)
bool isMissingDeclaratorOk ()
Checks if this DeclSpec can stand alone, without a Declarator.
Static Public Member Functions
static bool isDeclRep (TST T)
static bool isTransformTypeTrait (TST T)
static const char * getSpecifierName (DeclSpec::TST T, const PrintingPolicy &Policy)
Turn a type-specifier-type into a string like "_Bool" or "union".
static const char * getSpecifierName (DeclSpec::TQ Q)
static const char * getSpecifierName (TypeSpecifierSign S)
static const char * getSpecifierName (DeclSpec::TSC C)
static const char * getSpecifierName (TypeSpecifierWidth W)
static const char * getSpecifierName (DeclSpec::SCS S)
static const char * getSpecifierName (DeclSpec::TSCS S)
static const char * getSpecifierName (ConstexprSpecKind C)
Static Public Attributes
static const TSCS TSCS_unspecified = clang::TSCS_unspecified
static const TSCS TSCS___thread = clang::TSCS___thread
static const TSCS TSCS_thread_local = clang::TSCS_thread_local
static const TSCS TSCS__Thread_local = clang::TSCS__Thread_local
static const TST TST_unspecified = clang::TST_unspecified
static const TST TST_void = clang::TST_void
static const TST TST_char = clang::TST_char
static const TST TST_wchar = clang::TST_wchar
static const TST TST_char8 = clang::TST_char8
static const TST TST_char16 = clang::TST_char16
static const TST TST_char32 = clang::TST_char32
static const TST TST_int = clang::TST_int
static const TST TST_int128 = clang::TST_int128
static const TST TST_bitint = clang::TST_bitint
static const TST TST_half = clang::TST_half
static const TST TST_BFloat16 = clang::TST_BFloat16
static const TST TST_float = clang::TST_float
static const TST TST_double = clang::TST_double
static const TST TST_float16 = clang::TST_Float16
static const TST TST_accum = clang::TST_Accum
static const TST TST_fract = clang::TST_Fract
static const TST TST_float128 = clang::TST_float128
static const TST TST_ibm128 = clang::TST_ibm128
static const TST TST_bool = clang::TST_bool
static const TST TST_decimal32 = clang::TST_decimal32
static const TST TST_decimal64 = clang::TST_decimal64
static const TST TST_decimal128 = clang::TST_decimal128
static const TST TST_enum = clang::TST_enum
static const TST TST_union = clang::TST_union
static const TST TST_struct = clang::TST_struct
static const TST TST_interface = clang::TST_interface
static const TST TST_class = clang::TST_class
static const TST TST_typename = clang::TST_typename
static const TST TST_typeofType = clang::TST_typeofType
static const TST TST_typeofExpr = clang::TST_typeofExpr
static const TST TST_typeof_unqualType = clang::TST_typeof_unqualType
static const TST TST_typeof_unqualExpr = clang::TST_typeof_unqualExpr
static const TST TST_decltype = clang::TST_decltype
static const TST TST_decltype_auto = clang::TST_decltype_auto
static const TST TST_auto = clang::TST_auto
static const TST TST_auto_type = clang::TST_auto_type
static const TST TST_unknown_anytype = clang::TST_unknown_anytype
static const TST TST_atomic = clang::TST_atomic
static const TST TST_error = clang::TST_error
Detailed Description
Captures information about "declaration specifiers".
"Declaration specifiers" encompasses storage-class-specifiers, type-specifiers, type-qualifiers, and function-specifiers.
Definition at line 246 of file DeclSpec.h.
Member Typedef Documentation
TSCS
ThreadStorageClassSpecifier clang::DeclSpec::TSCS
Definition at line 263 of file DeclSpec.h.
TST
TypeSpecifierType clang::DeclSpec::TST
Definition at line 276 of file DeclSpec.h.
Member Enumeration Documentation
FriendSpecified
enum clang::DeclSpec::FriendSpecified : bool
Enumerator
No
Yes
Definition at line 347 of file DeclSpec.h.
ParsedSpecifiers
enum clang::DeclSpec::ParsedSpecifiers
ParsedSpecifiers - Flags to query which specifiers were applied.
This is returned by getParsedSpecifiers.
Enumerator
PQ_None
PQ_StorageClassSpecifier
PQ_TypeSpecifier
PQ_TypeQualifier
PQ_FunctionSpecifier
Definition at line 338 of file DeclSpec.h.
SCS
enum clang::DeclSpec::SCS
storage-class-specifier
Note
The order of these enumerators is important for diagnostics.
Enumerator
SCS_unspecified
SCS_typedef
SCS_extern
SCS_static
SCS_auto
SCS_register
SCS_private_extern
SCS_mutable
Definition at line 250 of file DeclSpec.h.
TQ
enum clang::DeclSpec::TQ
Enumerator
TQ_unspecified
TQ_const
TQ_restrict
TQ_volatile
TQ_unaligned
TQ_atomic
Definition at line 325 of file DeclSpec.h.
TSC
enum clang::DeclSpec::TSC
Enumerator
TSC_unspecified
TSC_imaginary
TSC_complex
Definition at line 269 of file DeclSpec.h.
Constructor & Destructor Documentation
DeclSpec()
clang::DeclSpec::DeclSpec (AttributeFactory & attrFactory) inline
Definition at line 457 of file DeclSpec.h.
Member Function Documentation
addAttributes()
void clang::DeclSpec::addAttributes (const ParsedAttributesView & AL) inline
Concatenates two attribute lists.
The GCC attribute syntax allows for the following:
short __attribute__((unused, deprecated))
int __attribute__((may_alias, aligned(16))) var;
This declares 4 attributes using 2 lists. The following syntax is also allowed and equivalent to the previous declaration.
short __attribute__((unused)) __attribute__((deprecated))
int __attribute__((may_alias)) __attribute__((aligned(16))) var;
Definition at line 828 of file DeclSpec.h.
References clang::ParsedAttributesView::addAll(), clang::ParsedAttributesView::begin(), and clang::ParsedAttributesView::end().
Referenced by clang::Parser::ParseTypeName().
ClearConstexprSpec()
void clang::DeclSpec::ClearConstexprSpec () inline
Definition at line 802 of file DeclSpec.h.
References clang::Unspecified.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), and CreateNewFunctionDecl().
ClearFunctionSpecs()
void clang::DeclSpec::ClearFunctionSpecs () inline
Definition at line 630 of file DeclSpec.h.
ClearStorageClassSpecs()
void clang::DeclSpec::ClearStorageClassSpecs () inline
Definition at line 489 of file DeclSpec.h.
References SCS_unspecified, and TSCS_unspecified.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), Finish(), and getFunctionStorageClass().
ClearTypeQualifiers()
void clang::DeclSpec::ClearTypeQualifiers () inline
Clear out all of the type qualifiers.
Definition at line 592 of file DeclSpec.h.
Referenced by clang::Sema::BuildAnonymousStructOrUnion(), and checkOmittedBlockReturnType().
ClearTypeSpecType()
void clang::DeclSpec::ClearTypeSpecType () inline
Definition at line 497 of file DeclSpec.h.
References TST_unspecified.
Finish()
void DeclSpec::Finish (Sema & S, const PrintingPolicy & Policy)
Finish - This does final analysis of the declspec, issuing diagnostics for things like "_Imaginary" (lacking an FP type).
Finish - This does final analysis of the declspec, rejecting things like "_Imaginary" (lacking an FP type).
After calling this method, DeclSpec is guaranteed self-consistent, even if an error occurred.
After calling this method, DeclSpec is guaranteed to be self-consistent, even if an error occurred.
Definition at line 1122 of file DeclSpec.cpp.
References ClearStorageClassSpecs(), clang::Consteval, clang::Constexpr, clang::Constinit, clang::Sema::Context, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), clang::Sema::Diag(), clang::SourceRange::getBegin(), getConstexprSpecifier(), getExplicitSpecLoc(), getExplicitSpecRange(), clang::Sema::getLangOpts(), clang::Sema::getLocForEndOfToken(), clang::Sema::getSourceManager(), getSpecifierName(), getStorageClassSpec(), getStorageClassSpecLoc(), clang::ASTContext::getTargetInfo(), getThreadStorageClassSpec(), getThreadStorageClassSpecLoc(), clang::TargetInfo::getTriple(), getTypeSpecComplexLoc(), getTypeSpecSign(), getTypeSpecWidth(), getVirtualSpecLoc(), hasExplicitSpecifier(), clang::TargetInfo::hasFeature(), int, clang::SourceManager::isBeforeInTranslationUnit(), isDeclRep(), isFriendSpecified(), clang::SourceLocation::isInvalid(), isVirtualSpecified(), clang::Long, clang::LongLong, SCS_auto, SCS_extern, SCS_private_extern, SCS_static, SCS_unspecified, clang::Short, TSC_unspecified, TSCS_unspecified, TST_accum, TST_auto, TST_bitint, TST_char, TST_char16, TST_char32, TST_char8, TST_decltype_auto, TST_double, TST_error, TST_float, TST_float128, TST_float16, TST_fract, TST_ibm128, TST_int, TST_int128, TST_unspecified, TST_wchar, clang::Unsigned, and clang::Unspecified.
forEachCVRUQualifier()
void DeclSpec::forEachCVRUQualifier (llvm::function_ref< void(TQ, StringRef, SourceLocation)> Handle)
This method calls the passed in handler on each CVRU qual being set.
Handle - a handler to be invoked.
Definition at line 428 of file DeclSpec.cpp.
References TQ_const, TQ_restrict, TQ_unaligned, and TQ_volatile.
Referenced by forEachQualifier(), and clang::DeclaratorChunk::getFunction().
forEachQualifier()
void DeclSpec::forEachQualifier (llvm::function_ref< void(TQ, StringRef, SourceLocation)> Handle)
This method calls the passed in handler on each qual being set.
Handle - a handler to be invoked.
Definition at line 440 of file DeclSpec.cpp.
References forEachCVRUQualifier().
Referenced by checkMethodTypeQualifiers(), and GetFullTypeForDeclarator().
getAltiVecLoc()
SourceLocation clang::DeclSpec::getAltiVecLoc () const inline
Definition at line 550 of file DeclSpec.h.
getAtomicSpecLoc()
SourceLocation clang::DeclSpec::getAtomicSpecLoc () const inline
Definition at line 587 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildQualifiedType(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckDestructorDeclarator(), diagnoseAndRemoveTypeQualifiers(), diagnoseRedundantReturnTypeQualifiers(), and clang::Sema::ParsedFreeStandingDeclSpec().
getAttributePool()
AttributePool & clang::DeclSpec::getAttributePool () const inline
Definition at line 807 of file DeclSpec.h.
References clang::ParsedAttributes::getPool().
Referenced by GetFullTypeForDeclarator(), clang::DeclaratorChunk::getFunction(), and takeDeclAttributes().
getAttributes() [1/2]
ParsedAttributes & clang::DeclSpec::getAttributes () inline
Definition at line 834 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), addContextSensitiveTypeNullability(), checkOmittedBlockReturnType(), clang::Sema::checkUnusedDeclAttributes(), ConvertDeclSpecToType(), distributeObjCPointerTypeAttrFromDeclarator(), getCCForDeclaratorChunk(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), clang::DeclaratorChunk::getFunction(), GetTypeSourceInfoForDeclarator(), clang::DeclaratorChunk::FunctionTypeInfo::hasMethodTypeQualifiers(), hasParsedAttr(), clang::Sema::ImplicitlyDefineFunction(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Parser::ParseTypeName(), clang::Sema::ProcessDeclAttributes(), and takeDeclAttributes().
getAttributes() [2/2]
const ParsedAttributes & clang::DeclSpec::getAttributes () const inline
Definition at line 835 of file DeclSpec.h.
getBeginLoc()
SourceLocation clang::DeclSpec::getBeginLoc () const inline
Definition at line 542 of file DeclSpec.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildMicrosoftCAnonymousStruct(), clang::Sema::CheckDeductionGuideDeclarator(), ConvertDeclSpecToType(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), and clang::Sema::ParsedFreeStandingDeclSpec().
getConstexprSpecifier()
ConstexprSpecKind clang::DeclSpec::getConstexprSpecifier () const inline
Definition at line 793 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnVariableDeclarator(), CreateNewFunctionDecl(), Finish(), GetFullTypeForDeclarator(), hasConstexprSpecifier(), clang::Sema::ParsedFreeStandingDeclSpec(), and SetConstexprSpec().
getConstexprSpecLoc()
SourceLocation clang::DeclSpec::getConstexprSpecLoc () const inline
Definition at line 797 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckMain(), CreateNewFunctionDecl(), and clang::Sema::ParsedFreeStandingDeclSpec().
getConstSpecLoc()
SourceLocation clang::DeclSpec::getConstSpecLoc () const inline
Definition at line 584 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckDestructorDeclarator(), ConvertDeclSpecToType(), diagnoseAndRemoveTypeQualifiers(), diagnoseRedundantReturnTypeQualifiers(), clang::DeclaratorChunk::FunctionTypeInfo::getConstQualifierLoc(), and clang::Sema::ParsedFreeStandingDeclSpec().
getEndLoc()
SourceLocation clang::DeclSpec::getEndLoc () const inline
Definition at line 543 of file DeclSpec.h.
Referenced by GetFullTypeForDeclarator().
getExplicitSpecifier()
ExplicitSpecifier clang::DeclSpec::getExplicitSpecifier () const inline
Definition at line 610 of file DeclSpec.h.
Referenced by CreateNewFunctionDecl().
getExplicitSpecLoc()
SourceLocation clang::DeclSpec::getExplicitSpecLoc () const inline
Definition at line 620 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckConversionDeclarator(), clang::Sema::DiagnoseFunctionSpecifiers(), and Finish().
getExplicitSpecRange()
SourceRange clang::DeclSpec::getExplicitSpecRange () const inline
Definition at line 621 of file DeclSpec.h.
References clang::ExplicitSpecifier::getExpr().
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::CheckConversionDeclarator(), and Finish().
getFriendSpecLoc()
SourceLocation clang::DeclSpec::getFriendSpecLoc () const inline
Definition at line 788 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendFunctionDecl(), and clang::Sema::ActOnFriendTypeDecl().
getInlineSpecLoc()
SourceLocation clang::DeclSpec::getInlineSpecLoc () const inline
Definition at line 606 of file DeclSpec.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::CheckMain(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), and clang::Sema::ParsedFreeStandingDeclSpec().
getModulePrivateSpecLoc()
SourceLocation clang::DeclSpec::getModulePrivateSpecLoc () const inline
Definition at line 791 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ParsedFreeStandingDeclSpec(), and clang::Sema::ParseTypedefDecl().
getNoreturnSpecLoc()
SourceLocation clang::DeclSpec::getNoreturnSpecLoc () const inline
Definition at line 628 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckMain(), and clang::Sema::DiagnoseFunctionSpecifiers().
getObjCQualifiers()
ObjCDeclSpec * clang::DeclSpec::getObjCQualifiers () const inline
Definition at line 850 of file DeclSpec.h.
getParsedSpecifiers()
unsigned DeclSpec::getParsedSpecifiers () const
Return a bitmask of which flavors of specifiers this DeclSpec includes.
getParsedSpecifiers - Return a bitmask of which flavors of specifiers this declaration specifier includes.
Definition at line 455 of file DeclSpec.cpp.
References hasExplicitSpecifier(), hasTypeSpecifier(), PQ_FunctionSpecifier, PQ_StorageClassSpecifier, PQ_TypeQualifier, PQ_TypeSpecifier, SCS_unspecified, TQ_unspecified, and TSCS_unspecified.
Referenced by clang::Sema::CodeCompleteDeclSpec(), GetDeclSpecTypeForDeclarator(), isEmpty(), and warnAboutRedundantParens().
getPipeLoc()
SourceLocation clang::DeclSpec::getPipeLoc () const inline
Definition at line 589 of file DeclSpec.h.
getRepAsDecl()
Decl * clang::DeclSpec::getRepAsDecl () const inline
Definition at line 525 of file DeclSpec.h.
References DeclRep, and isDeclRep().
Referenced by ConvertDeclSpecToType(), clang::Sema::FinalizeDeclaratorGroup(), GetDeclSpecTypeForDeclarator(), GetDiagnosticTypeSpecifierID(), GetFullTypeForDeclarator(), hasTagDefinition(), isMissingDeclaratorOk(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ParseTypedefDecl(), and clang::Parser::ParseTypeName().
getRepAsExpr()
Expr * clang::DeclSpec::getRepAsExpr () const inline
Definition at line 529 of file DeclSpec.h.
References ExprRep.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::BuildMemInitializer(), clang::Sema::containsUnexpandedParameterPacks(), ConvertDeclSpecToType(), clang::Sema::getDestructorTypeForDecltype(), clang::Declarator::isDeclarationOfFunction(), and RebuildDeclaratorInCurrentInstantiation().
getRepAsTemplateId()
TemplateIdAnnotation * clang::DeclSpec::getRepAsTemplateId () const inline
Definition at line 533 of file DeclSpec.h.
References TemplateIdRep.
Referenced by ConvertDeclSpecToType(), and InventTemplateParameter().
getRepAsType()
ParsedType clang::DeclSpec::getRepAsType () const inline
Definition at line 521 of file DeclSpec.h.
References isTypeRep(), and TypeRep.
Referenced by clang::Sema::CodeCompleteDeclSpec(), clang::Sema::containsUnexpandedParameterPacks(), ConvertDeclSpecToType(), CreateNewFunctionDecl(), clang::Declarator::isDeclarationOfFunction(), clang::Sema::ParsedFreeStandingDeclSpec(), and RebuildDeclaratorInCurrentInstantiation().
getRestrictSpecLoc()
SourceLocation clang::DeclSpec::getRestrictSpecLoc () const inline
Definition at line 585 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildQualifiedType(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckDestructorDeclarator(), diagnoseAndRemoveTypeQualifiers(), diagnoseRedundantReturnTypeQualifiers(), clang::DeclaratorChunk::FunctionTypeInfo::getRestrictQualifierLoc(), and clang::Sema::ParsedFreeStandingDeclSpec().
getSourceRange()
SourceRange clang::DeclSpec::getSourceRange () const inline
Definition at line 541 of file DeclSpec.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Declarator::clear(), ConvertDeclSpecToType(), clang::Declarator::ExtendWithDeclSpec(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), and clang::Sema::ParsedFreeStandingDeclSpec().
getSpecifierName() [1/8]
const char * DeclSpec::getSpecifierName (ConstexprSpecKind C) static
Definition at line 600 of file DeclSpec.cpp.
References clang::C, clang::Consteval, clang::Constexpr, clang::Constinit, and clang::Unspecified.
getSpecifierName() [2/8]
const char * DeclSpec::getSpecifierName (DeclSpec::SCS S) static
Definition at line 486 of file DeclSpec.cpp.
References SCS_auto, SCS_extern, SCS_mutable, SCS_private_extern, SCS_register, SCS_static, SCS_typedef, and SCS_unspecified.
getSpecifierName() [3/8]
const char * DeclSpec::getSpecifierName (DeclSpec::TQ Q) static
Definition at line 614 of file DeclSpec.cpp.
References TQ_atomic, TQ_const, TQ_restrict, TQ_unaligned, TQ_unspecified, and TQ_volatile.
getSpecifierName() [4/8]
const char * DeclSpec::getSpecifierName (DeclSpec::TSC C) static
Definition at line 524 of file DeclSpec.cpp.
References clang::C, TSC_complex, TSC_imaginary, and TSC_unspecified.
getSpecifierName() [5/8]
const char * DeclSpec::getSpecifierName (DeclSpec::TSCS S) static
Definition at line 500 of file DeclSpec.cpp.
References TSCS___thread, TSCS__Thread_local, TSCS_thread_local, and TSCS_unspecified.
getSpecifierName() [6/8]
const char * DeclSpec::getSpecifierName (DeclSpec::TST T, const PrintingPolicy & Policy) static
Turn a type-specifier-type into a string like "_Bool" or "union".
Definition at line 545 of file DeclSpec.cpp.
References clang::PrintingPolicy::Bool, clang::PrintingPolicy::MSWChar, TST_accum, TST_atomic, TST_auto, TST_auto_type, TST_BFloat16, TST_bitint, TST_bool, TST_char, TST_char16, TST_char32, TST_char8, TST_class, TST_decimal128, TST_decimal32, TST_decimal64, TST_decltype, TST_decltype_auto, TST_double, TST_enum, TST_error, TST_float, TST_float128, TST_float16, TST_fract, TST_half, TST_ibm128, TST_int, TST_int128, TST_interface, TST_struct, TST_typename, TST_typeof_unqualExpr, TST_typeof_unqualType, TST_typeofExpr, TST_typeofType, TST_union, TST_unknown_anytype, TST_unspecified, TST_void, and TST_wchar.
Referenced by clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), BadSpecifier(), ConvertDeclSpecToType(), diagnoseAndRemoveTypeQualifiers(), Finish(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), clang::Sema::ParsedFreeStandingDeclSpec(), SetBitIntType(), SetStorageClassSpec(), SetTypeAltiVecBool(), SetTypeAltiVecPixel(), SetTypeAltiVecVector(), SetTypePipe(), SetTypeSpecType(), SetTypeSpecType(), SetTypeSpecType(), and SetTypeSpecType().
getSpecifierName() [7/8]
const char * DeclSpec::getSpecifierName (TypeSpecifierSign S) static
Definition at line 533 of file DeclSpec.cpp.
References clang::Signed, clang::Unsigned, and clang::Unspecified.
getSpecifierName() [8/8]
const char * DeclSpec::getSpecifierName (TypeSpecifierWidth W) static
Definition at line 510 of file DeclSpec.cpp.
References clang::Long, clang::LongLong, clang::Short, and clang::Unspecified.
getStorageClassSpec()
SCS clang::DeclSpec::getStorageClassSpec () const inline
Definition at line 475 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXConditionDeclaration(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildAnonymousStructOrUnion(), ConvertDeclSpecToType(), Finish(), getCCForDeclaratorChunk(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), getFunctionStorageClass(), getLambdaType(), clang::Sema::HandleDeclarator(), clang::Declarator::isStaticMember(), clang::Sema::ParsedFreeStandingDeclSpec(), StorageClassSpecToVarDeclStorageClass(), and warnAboutAmbiguousFunction().
getStorageClassSpecLoc()
SourceLocation clang::DeclSpec::getStorageClassSpecLoc () const inline
Definition at line 484 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckMain(), Finish(), getFunctionStorageClass(), and clang::Sema::ParsedFreeStandingDeclSpec().
getThreadStorageClassSpec()
TSCS clang::DeclSpec::getThreadStorageClassSpec () const inline
Definition at line 476 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), Finish(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), and clang::Sema::ParsedFreeStandingDeclSpec().
getThreadStorageClassSpecLoc()
SourceLocation clang::DeclSpec::getThreadStorageClassSpecLoc () const inline
Definition at line 485 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), Finish(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), and clang::Sema::ParsedFreeStandingDeclSpec().
getTypeofParensRange()
SourceRange clang::DeclSpec::getTypeofParensRange () const inline
Definition at line 559 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), and clang::Sema::ActOnPseudoDestructorExpr().
getTypeQualifiers()
unsigned clang::DeclSpec::getTypeQualifiers () const inline
getTypeQualifiers - Return a set of TQs.
Definition at line 583 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFriendTypeDecl(), AddTypeQualifierResults(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), checkOmittedBlockReturnType(), ConvertDeclSpecToType(), diagnoseRedundantReturnTypeQualifiers(), GetFullTypeForDeclarator(), clang::DeclaratorChunk::getFunction(), clang::DeclaratorChunk::FunctionTypeInfo::hasMethodTypeQualifiers(), clang::Sema::ParsedFreeStandingDeclSpec(), and warnAboutRedundantParens().
getTypeSpecComplex()
TSC clang::DeclSpec::getTypeSpecComplex () const inline
Definition at line 507 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteDeclSpec(), ConvertDeclSpecToType(), and hasTypeSpecifier().
getTypeSpecComplexLoc()
SourceLocation clang::DeclSpec::getTypeSpecComplexLoc () const inline
Definition at line 547 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and Finish().
getTypeSpecSatLoc()
SourceLocation clang::DeclSpec::getTypeSpecSatLoc () const inline
Definition at line 551 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
getTypeSpecScope() [1/2]
CXXScopeSpec & clang::DeclSpec::getTypeSpecScope () inline
Definition at line 538 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), InventTemplateParameter(), and clang::Sema::ParsedFreeStandingDeclSpec().
getTypeSpecScope() [2/2]
const CXXScopeSpec & clang::DeclSpec::getTypeSpecScope () const inline
Definition at line 539 of file DeclSpec.h.
getTypeSpecSign()
TypeSpecifierSign clang::DeclSpec::getTypeSpecSign () const inline
Definition at line 508 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteDeclSpec(), ConvertDeclSpecToType(), Finish(), hasTypeSpecifier(), and SetTypeSpecSign().
getTypeSpecSignLoc()
SourceLocation clang::DeclSpec::getTypeSpecSignLoc () const inline
Definition at line 548 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
getTypeSpecType()
TST clang::DeclSpec::getTypeSpecType () const inline
Definition at line 511 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::BuildMemInitializer(), clang::Sema::CodeCompleteDeclSpec(), clang::Sema::containsUnexpandedParameterPacks(), ConvertDeclSpecToType(), clang::Sema::FinalizeDeclaratorGroup(), clang::Sema::getDestructorTypeForDecltype(), GetDiagnosticTypeSpecifierID(), GetFullTypeForDeclarator(), hasTypeSpecifier(), clang::Declarator::isDeclarationOfFunction(), clang::Declarator::isInvalidType(), isMissingDeclaratorOk(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ParseTypedefDecl(), and RebuildDeclaratorInCurrentInstantiation().
getTypeSpecTypeLoc()
SourceLocation clang::DeclSpec::getTypeSpecTypeLoc () const inline
Definition at line 549 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::BuildMemInitializer(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), ConvertDeclSpecToType(), CreateNewFunctionDecl(), GetDeclSpecTypeForDeclarator(), clang::Sema::getDestructorTypeForDecltype(), GetFullTypeForDeclarator(), InventTemplateParameter(), and RebuildDeclaratorInCurrentInstantiation().
getTypeSpecTypeNameLoc()
SourceLocation clang::DeclSpec::getTypeSpecTypeNameLoc () const inline
Definition at line 553 of file DeclSpec.h.
References isDeclRep(), and isTypeRep().
Referenced by ConvertDeclSpecToType().
getTypeSpecWidth()
TypeSpecifierWidth clang::DeclSpec::getTypeSpecWidth () const inline
Definition at line 504 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), hasTypeSpecifier(), and SetTypeSpecWidth().
getTypeSpecWidthLoc()
SourceLocation clang::DeclSpec::getTypeSpecWidthLoc () const inline
Definition at line 545 of file DeclSpec.h.
References clang::SourceRange::getBegin().
Referenced by ConvertDeclSpecToType().
getTypeSpecWidthRange()
SourceRange clang::DeclSpec::getTypeSpecWidthRange () const inline
Definition at line 546 of file DeclSpec.h.
getUnalignedSpecLoc()
SourceLocation clang::DeclSpec::getUnalignedSpecLoc () const inline
Definition at line 588 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), diagnoseRedundantReturnTypeQualifiers(), and clang::Sema::ParsedFreeStandingDeclSpec().
getVirtualSpecLoc()
SourceLocation clang::DeclSpec::getVirtualSpecLoc () const inline
Definition at line 615 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::DiagnoseFunctionSpecifiers(), and Finish().
getVolatileSpecLoc()
SourceLocation clang::DeclSpec::getVolatileSpecLoc () const inline
Definition at line 586 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFriendTypeDecl(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckDestructorDeclarator(), ConvertDeclSpecToType(), diagnoseAndRemoveTypeQualifiers(), diagnoseRedundantReturnTypeQualifiers(), and clang::DeclaratorChunk::FunctionTypeInfo::getVolatileQualifierLoc().
getWrittenBuiltinSpecs()
const WrittenBuiltinSpecs & clang::DeclSpec::getWrittenBuiltinSpecs () const inline
Definition at line 846 of file DeclSpec.h.
hasAttributes()
bool clang::DeclSpec::hasAttributes () const inline
Definition at line 832 of file DeclSpec.h.
References clang::ParsedAttributesView::empty().
hasAutoTypeSpec()
bool clang::DeclSpec::hasAutoTypeSpec () const inline
Definition at line 562 of file DeclSpec.h.
References TST_auto, TST_auto_type, and TST_decltype_auto.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::canDelayFunctionBody(), clang::Sema::FinalizeDeclaratorGroup(), and GetFullTypeForDeclarator().
hasConstexprSpecifier()
bool clang::DeclSpec::hasConstexprSpecifier () const inline
Definition at line 798 of file DeclSpec.h.
References getConstexprSpecifier(), and clang::Unspecified.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::canDelayFunctionBody(), and clang::Sema::ParsedFreeStandingDeclSpec().
hasExplicitSpecifier()
bool clang::DeclSpec::hasExplicitSpecifier () const inline
Definition at line 617 of file DeclSpec.h.
References clang::ExplicitSpecifier::isSpecified().
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckConversionDeclarator(), clang::Sema::DiagnoseFunctionSpecifiers(), Finish(), getParsedSpecifiers(), and setFunctionSpecExplicit().
hasTagDefinition()
bool DeclSpec::hasTagDefinition () const
Definition at line 446 of file DeclSpec.cpp.
References clang::cast(), and getRepAsDecl().
Referenced by GetFullTypeForDeclarator().
hasTypeSpecifier()
bool clang::DeclSpec::hasTypeSpecifier () const inline
Return true if any type-specifier has been found.
Definition at line 657 of file DeclSpec.h.
References getTypeSpecComplex(), getTypeSpecSign(), getTypeSpecType(), getTypeSpecWidth(), TSC_unspecified, TST_unspecified, and clang::Unspecified.
Referenced by clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), ConvertDeclSpecToType(), getParsedSpecifiers(), and isOmittedBlockReturnType().
isConstrainedAuto()
bool clang::DeclSpec::isConstrainedAuto () const inline
Definition at line 519 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
isDeclRep()
static bool clang::DeclSpec::isDeclRep (TST T) inline static
Definition at line 443 of file DeclSpec.h.
References TST_class, TST_enum, TST_interface, TST_struct, and TST_union.
Referenced by clang::Sema::FinalizeDeclaratorGroup(), Finish(), getRepAsDecl(), getTypeSpecTypeNameLoc(), isMissingDeclaratorOk(), SetTypeSpecType(), SetTypeSpecType(), and UpdateDeclRep().
isEmpty()
bool clang::DeclSpec::isEmpty () const inline
isEmpty - Return true if this declaration specifier is completely empty: no tokens were parsed in the production of it.
Definition at line 670 of file DeclSpec.h.
References getParsedSpecifiers(), and PQ_None.
isExternInLinkageSpec()
bool clang::DeclSpec::isExternInLinkageSpec () const inline
Definition at line 479 of file DeclSpec.h.
Referenced by getFunctionStorageClass(), clang::Sema::ParsedFreeStandingDeclSpec(), and StorageClassSpecToVarDeclStorageClass().
isFriendSpecified()
FriendSpecified clang::DeclSpec::isFriendSpecified () const inline
Definition at line 784 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::ActOnFunctionDeclarator(), CreateNewFunctionDecl(), Finish(), GetDeclSpecTypeForDeclarator(), GetFullTypeForDeclarator(), clang::Sema::HandleDeclarator(), clang::Sema::isDeclaratorFunctionLike(), clang::Declarator::isFirstDeclarationOfMember(), and clang::Sema::ParsedFreeStandingDeclSpec().
isInlineSpecified()
bool clang::DeclSpec::isInlineSpecified () const inline
Definition at line 603 of file DeclSpec.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnVariableDeclarator(), CreateNewFunctionDecl(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), and clang::Sema::ParsedFreeStandingDeclSpec().
isMissingDeclaratorOk()
bool DeclSpec::isMissingDeclaratorOk ()
Checks if this DeclSpec can stand alone, without a Declarator.
Only tag declspecs can stand alone.
Definition at line 1451 of file DeclSpec.cpp.
References getRepAsDecl(), getTypeSpecType(), isDeclRep(), and SCS_typedef.
Referenced by clang::Sema::ParsedFreeStandingDeclSpec().
isModulePrivateSpecified()
bool clang::DeclSpec::isModulePrivateSpecified () const inline
Definition at line 790 of file DeclSpec.h.
References clang::SourceLocation::isValid().
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ParseTypedefDecl(), and setModulePrivateSpec().
isNoreturnSpecified()
bool clang::DeclSpec::isNoreturnSpecified () const inline
Definition at line 627 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckMain(), and clang::Sema::DiagnoseFunctionSpecifiers().
isTransformTypeTrait()
static bool clang::DeclSpec::isTransformTypeTrait (TST T) inline static
Definition at line 448 of file DeclSpec.h.
isTypeAltiVecBool()
bool clang::DeclSpec::isTypeAltiVecBool () const inline
Definition at line 514 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
isTypeAltiVecPixel()
bool clang::DeclSpec::isTypeAltiVecPixel () const inline
Definition at line 513 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
isTypeAltiVecVector()
bool clang::DeclSpec::isTypeAltiVecVector () const inline
Definition at line 512 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteDeclSpec(), and ConvertDeclSpecToType().
isTypeRep()
bool clang::DeclSpec::isTypeRep () const inline
Definition at line 516 of file DeclSpec.h.
References isTypeRep().
Referenced by getRepAsType(), getTypeSpecTypeNameLoc(), isTypeRep(), SetTypeSpecType(), SetTypeSpecType(), and UpdateTypeRep().
isTypeSpecOwned()
bool clang::DeclSpec::isTypeSpecOwned () const inline
Definition at line 515 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), clang::Sema::FinalizeDeclaratorGroup(), GetDeclSpecTypeForDeclarator(), and clang::Parser::ParseTypeName().
isTypeSpecPipe()
bool clang::DeclSpec::isTypeSpecPipe () const inline
Definition at line 517 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
isTypeSpecSat()
bool clang::DeclSpec::isTypeSpecSat () const inline
Definition at line 518 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType().
isVirtualSpecified()
bool clang::DeclSpec::isVirtualSpecified () const inline
Definition at line 614 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::DiagnoseFunctionSpecifiers(), and Finish().
SetBitIntType()
bool DeclSpec::SetBitIntType (SourceLocation KWLoc, Expr * BitWidth, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 943 of file DeclSpec.cpp.
References ExprRep, getSpecifierName(), TST_bitint, TST_error, and TST_unspecified.
SetConstexprSpec()
bool DeclSpec::SetConstexprSpec (ConstexprSpecKind ConstexprKind, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1100 of file DeclSpec.cpp.
References BadSpecifier(), getConstexprSpecifier(), and clang::Unspecified.
Referenced by addConstevalToLambdaDeclSpecifier(), and addConstexprToLambdaDeclSpecifier().
setExternInLinkageSpec()
void clang::DeclSpec::setExternInLinkageSpec (bool Value) inline
Definition at line 480 of file DeclSpec.h.
SetFriendSpec()
bool DeclSpec::SetFriendSpec (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1070 of file DeclSpec.cpp.
setFunctionSpecExplicit()
bool DeclSpec::setFunctionSpecExplicit (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, ExplicitSpecifier ExplicitSpec, SourceLocation CloseParenLoc)
Definition at line 1036 of file DeclSpec.cpp.
References clang::ExplicitSpecifier::getExpr(), and hasExplicitSpecifier().
setFunctionSpecForceInline()
bool DeclSpec::setFunctionSpecForceInline (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1009 of file DeclSpec.cpp.
setFunctionSpecInline()
bool DeclSpec::setFunctionSpecInline (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 995 of file DeclSpec.cpp.
setFunctionSpecNoreturn()
bool DeclSpec::setFunctionSpecNoreturn (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1055 of file DeclSpec.cpp.
setFunctionSpecVirtual()
bool DeclSpec::setFunctionSpecVirtual (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1021 of file DeclSpec.cpp.
setModulePrivateSpec()
bool DeclSpec::setModulePrivateSpec (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 1088 of file DeclSpec.cpp.
References isModulePrivateSpecified().
setObjCQualifiers()
void clang::DeclSpec::setObjCQualifiers (ObjCDeclSpec * quals) inline
Definition at line 851 of file DeclSpec.h.
SetRangeEnd()
void clang::DeclSpec::SetRangeEnd (SourceLocation Loc) inline
Definition at line 675 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishKNRParamDeclarations(), and clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers().
SetRangeStart()
void clang::DeclSpec::SetRangeStart (SourceLocation Loc) inline
Definition at line 674 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishKNRParamDeclarations(), and clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers().
SetStorageClassSpec()
bool DeclSpec::SetStorageClassSpec (Sema & S, SCS SC, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
These methods set the specified attribute of the DeclSpec and return false if there was no error.
If an error occurs (for example, if we tried to set "auto" on a spec with "extern" already set), they return true and set PrevSpec and DiagID such that Diag(Loc, DiagID) << PrevSpec; will yield a useful result.
TODO: use a more general approach that still allows these diagnostics to be ignored when desired.
Definition at line 626 of file DeclSpec.cpp.
References BadSpecifier(), clang::Sema::getLangOpts(), clang::LangOptions::getOpenCLCompatibleVersion(), clang::Sema::getOpenCLOptions(), getSpecifierName(), clang::OpenCLOptions::isAvailableOption(), isInvalid(), SCS_auto, SCS_extern, SCS_private_extern, SCS_register, SCS_static, SCS_typedef, SCS_unspecified, SetTypeSpecType(), TST_auto, and TST_unspecified.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), addStaticToLambdaDeclSpecifier(), and clang::Sema::BuildAnonymousStructOrUnion().
SetStorageClassSpecThread()
bool DeclSpec::SetStorageClassSpecThread (TSCS TSC, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 688 of file DeclSpec.cpp.
References BadSpecifier(), and TSCS_unspecified.
SetTypeAltiVecBool()
bool DeclSpec::SetTypeAltiVecBool (bool isAltiVecBool, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 918 of file DeclSpec.cpp.
References getSpecifierName(), TST_error, and TST_unspecified.
SetTypeAltiVecPixel()
bool DeclSpec::SetTypeAltiVecPixel (bool isAltiVecPixel, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 901 of file DeclSpec.cpp.
References getSpecifierName(), TST_error, and TST_unspecified.
SetTypeAltiVecVector()
bool DeclSpec::SetTypeAltiVecVector (bool isAltiVecVector, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 869 of file DeclSpec.cpp.
References getSpecifierName(), TST_error, and TST_unspecified.
setTypeArgumentRange()
void clang::DeclSpec::setTypeArgumentRange (SourceRange range) inline
Definition at line 560 of file DeclSpec.h.
SetTypePipe()
bool DeclSpec::SetTypePipe (bool isPipe, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 884 of file DeclSpec.cpp.
References getSpecifierName(), clang::Pipe, TST_error, and TST_unspecified.
SetTypeQual() [1/2]
bool DeclSpec::SetTypeQual (TQ T, SourceLocation Loc)
Definition at line 980 of file DeclSpec.cpp.
References TQ_atomic, TQ_const, TQ_restrict, TQ_unaligned, TQ_unspecified, and TQ_volatile.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::DeclaratorChunk::getFunction(), getLambdaType(), and SetTypeQual().
SetTypeQual() [2/2]
bool DeclSpec::SetTypeQual (TQ T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const LangOptions & Lang)
Definition at line 964 of file DeclSpec.cpp.
References BadSpecifier(), and SetTypeQual().
SetTypeSpecComplex()
bool DeclSpec::SetTypeSpecComplex (TSC C, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 719 of file DeclSpec.cpp.
References BadSpecifier(), clang::C, and TSC_unspecified.
SetTypeSpecError()
bool DeclSpec::SetTypeSpecError ()
Definition at line 935 of file DeclSpec.cpp.
References TST_error.
Referenced by SetTypeSpecType().
SetTypeSpecSat()
bool DeclSpec::SetTypeSpecSat (SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 856 of file DeclSpec.cpp.
SetTypeSpecSign()
bool DeclSpec::SetTypeSpecSign (TypeSpecifierSign S, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID)
Definition at line 729 of file DeclSpec.cpp.
References BadSpecifier(), getTypeSpecSign(), and clang::Unspecified.
SetTypeSpecType() [1/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
Definition at line 832 of file DeclSpec.cpp.
References getSpecifierName(), isDeclRep(), isTypeRep(), TST_bool, TST_error, and TST_unspecified.
Referenced by clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::ActOnFinishKNRParamDeclarations(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ImplicitlyDefineFunction(), SetStorageClassSpec(), SetTypeSpecType(), SetTypeSpecType(), SetTypeSpecType(), and SetTypeSpecType().
SetTypeSpecType() [2/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, Decl * Rep, bool Owned, const PrintingPolicy & Policy)
Definition at line 791 of file DeclSpec.cpp.
References SetTypeSpecType().
SetTypeSpecType() [3/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, Expr * Rep, const PrintingPolicy & policy)
Definition at line 769 of file DeclSpec.cpp.
References ExprRep, getSpecifierName(), TST_error, and TST_unspecified.
SetTypeSpecType() [4/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, ParsedType Rep, const PrintingPolicy & Policy)
Definition at line 738 of file DeclSpec.cpp.
References SetTypeSpecType().
SetTypeSpecType() [5/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, TemplateIdAnnotation * Rep, const PrintingPolicy & Policy)
Definition at line 823 of file DeclSpec.cpp.
References SetTypeSpecType(), TemplateIdRep, TST_auto, and TST_decltype_auto.
SetTypeSpecType() [6/8]
bool clang::DeclSpec::SetTypeSpecType (TST T, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, TypeResult Rep, const PrintingPolicy & Policy) inline
Definition at line 704 of file DeclSpec.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), SetTypeSpecError(), and SetTypeSpecType().
SetTypeSpecType() [7/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation TagKwLoc, SourceLocation TagNameLoc, const char *& PrevSpec, unsigned & DiagID, Decl * Rep, bool Owned, const PrintingPolicy & Policy)
Definition at line 799 of file DeclSpec.cpp.
References DeclRep, getSpecifierName(), isDeclRep(), TST_error, and TST_unspecified.
SetTypeSpecType() [8/8]
bool DeclSpec::SetTypeSpecType (TST T, SourceLocation TagKwLoc, SourceLocation TagNameLoc, const char *& PrevSpec, unsigned & DiagID, ParsedType Rep, const PrintingPolicy & Policy)
Definition at line 746 of file DeclSpec.cpp.
References getSpecifierName(), isTypeRep(), TST_error, TST_unspecified, and TypeRep.
SetTypeSpecWidth()
bool DeclSpec::SetTypeSpecWidth (TypeSpecifierWidth W, SourceLocation Loc, const char *& PrevSpec, unsigned & DiagID, const PrintingPolicy & Policy)
These methods set the specified attribute of the DeclSpec, but return true and ignore the request if invalid (e.g.
"extern" then "auto" is specified).
Definition at line 702 of file DeclSpec.cpp.
References BadSpecifier(), getTypeSpecWidth(), clang::Long, clang::LongLong, clang::SourceRange::setBegin(), clang::SourceRange::setEnd(), and clang::Unspecified.
takeAttributesFrom()
void clang::DeclSpec::takeAttributesFrom (ParsedAttributes & attrs) inline
Definition at line 837 of file DeclSpec.h.
References clang::ParsedAttributes::takeAllFrom().
UpdateDeclRep()
void clang::DeclSpec::UpdateDeclRep (Decl * Rep) inline
Definition at line 747 of file DeclSpec.h.
References DeclRep, and isDeclRep().
UpdateExprRep()
void clang::DeclSpec::UpdateExprRep (Expr * Rep) inline
Definition at line 755 of file DeclSpec.h.
References ExprRep.
Referenced by RebuildDeclaratorInCurrentInstantiation().
UpdateTypeRep()
void clang::DeclSpec::UpdateTypeRep (ParsedType Rep) inline
Definition at line 751 of file DeclSpec.h.
References isTypeRep(), and TypeRep.
Referenced by RebuildDeclaratorInCurrentInstantiation().
Member Data Documentation
DeclRep
Decl* clang::DeclSpec::DeclRep
Definition at line 388 of file DeclSpec.h.
Referenced by getRepAsDecl(), SetTypeSpecType(), and UpdateDeclRep().
ExprRep
Expr* clang::DeclSpec::ExprRep
Definition at line 389 of file DeclSpec.h.
Referenced by getRepAsExpr(), SetBitIntType(), SetTypeSpecType(), and UpdateExprRep().
TemplateIdRep
TemplateIdAnnotation* clang::DeclSpec::TemplateIdRep
Definition at line 390 of file DeclSpec.h.
Referenced by getRepAsTemplateId(), and SetTypeSpecType().
TSCS___thread
const TSCS clang::DeclSpec::TSCS___thread = clang::TSCS___thread static
Definition at line 265 of file DeclSpec.h.
Referenced by getSpecifierName().
TSCS__Thread_local
const TSCS clang::DeclSpec::TSCS__Thread_local = clang::TSCS__Thread_local static
Definition at line 267 of file DeclSpec.h.
Referenced by getSpecifierName().
TSCS_thread_local
const TSCS clang::DeclSpec::TSCS_thread_local = clang::TSCS_thread_local static
Definition at line 266 of file DeclSpec.h.
Referenced by clang::Sema::ActOnVariableDeclarator(), and getSpecifierName().
TSCS_unspecified
const TSCS clang::DeclSpec::TSCS_unspecified = clang::TSCS_unspecified static
Definition at line 264 of file DeclSpec.h.
Referenced by ClearStorageClassSpecs(), Finish(), getParsedSpecifiers(), getSpecifierName(), and SetStorageClassSpecThread().
TST_accum
const TST clang::DeclSpec::TST_accum = clang::TST_Accum static
Definition at line 292 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_atomic
const TST clang::DeclSpec::TST_atomic = clang::TST_atomic static
Definition at line 318 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_auto
const TST clang::DeclSpec::TST_auto = clang::TST_auto static
Definition at line 315 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::ActOnDecompositionDeclarator(), ConvertDeclSpecToType(), Finish(), GetFullTypeForDeclarator(), getSpecifierName(), hasAutoTypeSpec(), SetStorageClassSpec(), and SetTypeSpecType().
TST_auto_type
const TST clang::DeclSpec::TST_auto_type = clang::TST_auto_type static
Definition at line 316 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and hasAutoTypeSpec().
TST_BFloat16
const TST clang::DeclSpec::TST_BFloat16 = clang::TST_BFloat16 static
Definition at line 288 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_bitint
const TST clang::DeclSpec::TST_bitint = clang::TST_bitint static
Definition at line 286 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), getSpecifierName(), and SetBitIntType().
TST_bool
const TST clang::DeclSpec::TST_bool = clang::TST_bool static
Definition at line 296 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and SetTypeSpecType().
TST_char
const TST clang::DeclSpec::TST_char = clang::TST_char static
Definition at line 279 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_char16
const TST clang::DeclSpec::TST_char16 = clang::TST_char16 static
Definition at line 282 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_char32
const TST clang::DeclSpec::TST_char32 = clang::TST_char32 static
Definition at line 283 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_char8
const TST clang::DeclSpec::TST_char8 = clang::TST_char8 static
Definition at line 281 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_class
const TST clang::DeclSpec::TST_class = clang::TST_class static
Definition at line 304 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteDeclSpec(), clang::Sema::CodeCompleteTag(), ConvertDeclSpecToType(), GetDiagnosticTypeSpecifierID(), getSpecifierName(), isDeclRep(), clang::Sema::isTagName(), and clang::Sema::ParsedFreeStandingDeclSpec().
TST_decimal128
const TST clang::DeclSpec::TST_decimal128 = clang::TST_decimal128 static
Definition at line 299 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_decimal32
const TST clang::DeclSpec::TST_decimal32 = clang::TST_decimal32 static
Definition at line 297 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_decimal64
const TST clang::DeclSpec::TST_decimal64 = clang::TST_decimal64 static
Definition at line 298 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_decltype
const TST clang::DeclSpec::TST_decltype = clang::TST_decltype static
Definition at line 310 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), ConvertDeclSpecToType(), clang::Sema::getDestructorTypeForDecltype(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_decltype_auto
const TST clang::DeclSpec::TST_decltype_auto = clang::TST_decltype_auto static
Definition at line 311 of file DeclSpec.h.
Referenced by clang::Sema::ActOnPseudoDestructorExpr(), ConvertDeclSpecToType(), Finish(), clang::Sema::getDestructorTypeForDecltype(), getSpecifierName(), hasAutoTypeSpec(), and SetTypeSpecType().
TST_double
const TST clang::DeclSpec::TST_double = clang::TST_double static
Definition at line 290 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_enum
const TST clang::DeclSpec::TST_enum = clang::TST_enum static
Definition at line 300 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteTag(), ConvertDeclSpecToType(), GetDiagnosticTypeSpecifierID(), getSpecifierName(), isDeclRep(), clang::Sema::isTagName(), and clang::Sema::ParsedFreeStandingDeclSpec().
TST_error
const TST clang::DeclSpec::TST_error = clang::TST_error static
Definition at line 322 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), ConvertDeclSpecToType(), Finish(), clang::Sema::getDestructorTypeForDecltype(), getSpecifierName(), clang::Declarator::isInvalidType(), clang::Sema::ParsedFreeStandingDeclSpec(), SetBitIntType(), SetTypeAltiVecBool(), SetTypeAltiVecPixel(), SetTypeAltiVecVector(), SetTypePipe(), SetTypeSpecError(), SetTypeSpecType(), SetTypeSpecType(), SetTypeSpecType(), and SetTypeSpecType().
TST_float
const TST clang::DeclSpec::TST_float = clang::TST_float static
Definition at line 289 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_float128
const TST clang::DeclSpec::TST_float128 = clang::TST_float128 static
Definition at line 294 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_float16
const TST clang::DeclSpec::TST_float16 = clang::TST_Float16 static
Definition at line 291 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_fract
const TST clang::DeclSpec::TST_fract = clang::TST_Fract static
Definition at line 293 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_half
const TST clang::DeclSpec::TST_half = clang::TST_half static
Definition at line 287 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_ibm128
const TST clang::DeclSpec::TST_ibm128 = clang::TST_ibm128 static
Definition at line 295 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_int
const TST clang::DeclSpec::TST_int = clang::TST_int static
Definition at line 284 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishKNRParamDeclarations(), ConvertDeclSpecToType(), Finish(), getSpecifierName(), and clang::Sema::ImplicitlyDefineFunction().
TST_int128
const TST clang::DeclSpec::TST_int128 = clang::TST_int128 static
Definition at line 285 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TST_interface
const TST clang::DeclSpec::TST_interface = clang::TST_interface static
Definition at line 303 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteTag(), ConvertDeclSpecToType(), GetDiagnosticTypeSpecifierID(), getSpecifierName(), isDeclRep(), clang::Sema::isTagName(), and clang::Sema::ParsedFreeStandingDeclSpec().
TST_struct
const TST clang::DeclSpec::TST_struct = clang::TST_struct static
Definition at line 302 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteDeclSpec(), clang::Sema::CodeCompleteTag(), ConvertDeclSpecToType(), GetDiagnosticTypeSpecifierID(), getSpecifierName(), isDeclRep(), clang::Sema::isTagName(), and clang::Sema::ParsedFreeStandingDeclSpec().
TST_typename
const TST clang::DeclSpec::TST_typename = clang::TST_typename static
Definition at line 305 of file DeclSpec.h.
Referenced by clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::CodeCompleteDeclSpec(), ConvertDeclSpecToType(), getSpecifierName(), clang::Sema::ParsedFreeStandingDeclSpec(), and RebuildDeclaratorInCurrentInstantiation().
TST_typeof_unqualExpr
const TST clang::DeclSpec::TST_typeof_unqualExpr = clang::TST_typeof_unqualExpr static
Definition at line 309 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_typeof_unqualType
const TST clang::DeclSpec::TST_typeof_unqualType = clang::TST_typeof_unqualType static
Definition at line 308 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_typeofExpr
const TST clang::DeclSpec::TST_typeofExpr = clang::TST_typeofExpr static
Definition at line 307 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_typeofType
const TST clang::DeclSpec::TST_typeofType = clang::TST_typeofType static
Definition at line 306 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), getSpecifierName(), and RebuildDeclaratorInCurrentInstantiation().
TST_union
const TST clang::DeclSpec::TST_union = clang::TST_union static
Definition at line 301 of file DeclSpec.h.
Referenced by clang::Sema::CodeCompleteTag(), ConvertDeclSpecToType(), GetDiagnosticTypeSpecifierID(), getSpecifierName(), isDeclRep(), clang::Sema::isTagName(), and clang::Sema::ParsedFreeStandingDeclSpec().
TST_unknown_anytype
const TST clang::DeclSpec::TST_unknown_anytype = clang::TST_unknown_anytype static
Definition at line 317 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_unspecified
const TST clang::DeclSpec::TST_unspecified = clang::TST_unspecified static
Definition at line 277 of file DeclSpec.h.
Referenced by ClearTypeSpecType(), ConvertDeclSpecToType(), Finish(), getSpecifierName(), hasTypeSpecifier(), clang::Sema::isTagName(), SetBitIntType(), SetStorageClassSpec(), SetTypeAltiVecBool(), SetTypeAltiVecPixel(), SetTypeAltiVecVector(), SetTypePipe(), SetTypeSpecType(), SetTypeSpecType(), SetTypeSpecType(), and SetTypeSpecType().
TST_void
const TST clang::DeclSpec::TST_void = clang::TST_void static
Definition at line 278 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), and getSpecifierName().
TST_wchar
const TST clang::DeclSpec::TST_wchar = clang::TST_wchar static
Definition at line 280 of file DeclSpec.h.
Referenced by ConvertDeclSpecToType(), Finish(), and getSpecifierName().
TypeRep
UnionParsedType clang::DeclSpec::TypeRep
Definition at line 387 of file DeclSpec.h.
Referenced by getRepAsType(), SetTypeSpecType(), and UpdateTypeRep().
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp