clang: clang::TreeTransform< Derived >::TemporaryBase Class Reference
clang::TreeTransform< Derived >::TemporaryBase Class Reference
RAII object that temporarily sets the base location and entity used for reporting diagnostics in types.
#include "/root/llvm-project/clang/lib/Sema/TreeTransform.h"
Public Member Functions
TemporaryBase (TreeTransform &Self, SourceLocation Location, DeclarationName Entity)
~TemporaryBase ()
Detailed Description
template<typename Derived>
class clang::TreeTransform< Derived >::TemporaryBase
RAII object that temporarily sets the base location and entity used for reporting diagnostics in types.
Definition at line 195 of file TreeTransform.h.
Constructor & Destructor Documentation
TemporaryBase()
template<typename Derived > clang::TreeTransform< Derived >::TemporaryBase::TemporaryBase (TreeTransform & Self, SourceLocation Location, DeclarationName Entity) inline
Definition at line 201 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getBaseEntity(), clang::TreeTransform< Derived >::getBaseLocation(), clang::TreeTransform< Derived >::getDerived(), and clang::SourceLocation::isValid().
~TemporaryBase()
template<typename Derived > clang::TreeTransform< Derived >::TemporaryBase::~TemporaryBase () inline
Definition at line 210 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getDerived().
The documentation for this class was generated from the following file:
lib/Sema/TreeTransform.h