clang: clang::OMPClauseReader Class Reference
clang::OMPClauseReader Class Reference
Public Member Functions
OMPClauseReader (ASTRecordReader &Record)
OMPClause * readClause ()
void VisitOMPClauseWithPreInit (OMPClauseWithPreInit *C)
void VisitOMPClauseWithPostUpdate (OMPClauseWithPostUpdate *C)
Public Member Functions inherited from clang::OMPClauseVisitorBase< OMPClauseReader, std::add_pointer_t, void >
void Visit (PTR(OMPClause) S)
void VisitOMPClause (PTR(OMPClause) Node)
Detailed Description
Definition at line 10038 of file ASTReader.cpp.
Constructor & Destructor Documentation
OMPClauseReader()
clang::OMPClauseReader::OMPClauseReader (ASTRecordReader & Record) inline
Definition at line 10043 of file ASTReader.cpp.
Member Function Documentation
readClause()
OMPClause * OMPClauseReader::readClause ()
Definition at line 10059 of file ASTReader.cpp.
References clang::C, clang::OMPAffinityClause::CreateEmpty(), clang::OMPAlignedClause::CreateEmpty(), clang::OMPAllocateClause::CreateEmpty(), clang::OMPBindClause::CreateEmpty(), clang::OMPCopyinClause::CreateEmpty(), clang::OMPCopyprivateClause::CreateEmpty(), clang::OMPDependClause::CreateEmpty(), clang::OMPDepobjClause::CreateEmpty(), clang::OMPDoacrossClause::CreateEmpty(), clang::OMPExclusiveClause::CreateEmpty(), clang::OMPFirstprivateClause::CreateEmpty(), clang::OMPFlushClause::CreateEmpty(), clang::OMPFromClause::CreateEmpty(), clang::OMPFullClause::CreateEmpty(), clang::OMPHasDeviceAddrClause::CreateEmpty(), clang::OMPInclusiveClause::CreateEmpty(), clang::OMPInitClause::CreateEmpty(), clang::OMPInReductionClause::CreateEmpty(), clang::OMPIsDevicePtrClause::CreateEmpty(), clang::OMPLastprivateClause::CreateEmpty(), clang::OMPLinearClause::CreateEmpty(), clang::OMPMapClause::CreateEmpty(), clang::OMPNontemporalClause::CreateEmpty(), clang::OMPOrderedClause::CreateEmpty(), clang::OMPPartialClause::CreateEmpty(), clang::OMPPrivateClause::CreateEmpty(), clang::OMPReductionClause::CreateEmpty(), clang::OMPSharedClause::CreateEmpty(), clang::OMPSizesClause::CreateEmpty(), clang::OMPTaskReductionClause::CreateEmpty(), clang::OMPToClause::CreateEmpty(), clang::OMPUpdateClause::CreateEmpty(), clang::OMPUseDeviceAddrClause::CreateEmpty(), clang::OMPUseDevicePtrClause::CreateEmpty(), clang::OMPUsesAllocatorsClause::CreateEmpty(), N, clang::OMPMappableExprListSizeTy::NumComponentLists, clang::OMPMappableExprListSizeTy::NumComponents, clang::OMPMappableExprListSizeTy::NumUniqueDeclarations, clang::OMPMappableExprListSizeTy::NumVars, and clang::OMPClauseVisitorBase< OMPClauseReader, std::add_pointer_t, void >::Visit().
Referenced by clang::ASTRecordReader::readOMPClause().
VisitOMPClauseWithPostUpdate()
void OMPClauseReader::VisitOMPClauseWithPostUpdate (OMPClauseWithPostUpdate * C)
Definition at line 10394 of file ASTReader.cpp.
References clang::C, and VisitOMPClauseWithPreInit().
VisitOMPClauseWithPreInit()
void OMPClauseReader::VisitOMPClauseWithPreInit (OMPClauseWithPreInit * C)
Definition at line 10389 of file ASTReader.cpp.
References clang::C.
Referenced by VisitOMPClauseWithPostUpdate().
The documentation for this class was generated from the following file:
lib/Serialization/ASTReader.cpp