clang: clang::CodeGen::CoverageMappingModuleGen Class Reference
clang::CodeGen::CoverageMappingModuleGen Class Reference
Organizes the cross-function state that is used while generating code coverage mapping data.
#include "/root/llvm-project/clang/lib/CodeGen/CoverageMappingGen.h"
Public Member Functions
CoverageMappingModuleGen (CodeGenModule &CGM, CoverageSourceInfo &SourceInfo)
CoverageSourceInfo & getSourceInfo () const
void addFunctionMappingRecord (llvm::GlobalVariable *FunctionName, StringRef FunctionNameValue, uint64_t FunctionHash, const std::string &CoverageMapping, bool IsUsed=true)
Add a function's coverage mapping record to the collection of the function mapping records.
void emit ()
Emit the coverage mapping data for a translation unit.
unsigned getFileID (const FileEntry *File)
Return the coverage mapping translation unit file id for the given file.
CodeGenModule & getCodeGenModule ()
Return an interface into CodeGenModule.
Static Public Member Functions
static CoverageSourceInfo * setUpCoverageCallbacks (Preprocessor &PP)
Detailed Description
Organizes the cross-function state that is used while generating code coverage mapping data.
Definition at line 96 of file CoverageMappingGen.h.
Constructor & Destructor Documentation
CoverageMappingModuleGen()
CoverageMappingModuleGen::CoverageMappingModuleGen (CodeGenModule & CGM, CoverageSourceInfo & SourceInfo)
Definition at line 1635 of file CoverageMappingGen.cpp.
Member Function Documentation
addFunctionMappingRecord()
void CoverageMappingModuleGen::addFunctionMappingRecord (llvm::GlobalVariable * FunctionName, StringRef FunctionNameValue, uint64_t FunctionHash, const std::string & CoverageMapping, bool IsUsed = true)
Add a function's coverage mapping record to the collection of the function mapping records.
Definition at line 1718 of file CoverageMappingGen.cpp.
References dump(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGen::CodeGenModule::getLLVMContext().
Referenced by clang::CodeGen::CodeGenPGO::emitEmptyCounterMapping().
emit()
void CoverageMappingModuleGen::emit ()
Emit the coverage mapping data for a translation unit.
Definition at line 1754 of file CoverageMappingGen.cpp.
References clang::CodeGen::CodeGenModule::addUsedGlobal(), getInstrProfSection(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::CodeGenModule::getModule().
getCodeGenModule()
CodeGenModule & clang::CodeGen::CoverageMappingModuleGen::getCodeGenModule () inline
Return an interface into CodeGenModule.
Definition at line 143 of file CoverageMappingGen.h.
getFileID()
unsigned CoverageMappingModuleGen::getFileID (const FileEntry * File)
Return the coverage mapping translation unit file id for the given file.
Definition at line 1826 of file CoverageMappingGen.cpp.
References clang::File.
getSourceInfo()
CoverageSourceInfo & clang::CodeGen::CoverageMappingModuleGen::getSourceInfo () const inline
Definition at line 123 of file CoverageMappingGen.h.
setUpCoverageCallbacks()
CoverageSourceInfo * CoverageMappingModuleGen::setUpCoverageCallbacks (Preprocessor & PP) static
Definition at line 50 of file CoverageMappingGen.cpp.
References clang::Preprocessor::addCommentHandler(), clang::Preprocessor::addPPCallbacks(), EmptyLineCommentCoverage(), clang::Token::getKind(), clang::Token::getLocation(), clang::Preprocessor::getSourceManager(), clang::CoverageSourceInfo::PrevTokLoc, clang::Preprocessor::setEmptylineHandler(), clang::Preprocessor::setPreprocessToken(), clang::Preprocessor::setTokenWatcher(), Tok, and clang::CoverageSourceInfo::updateNextTokLoc().
Referenced by clang::CodeGenAction::CreateASTConsumer().
The documentation for this class was generated from the following files:
lib/CodeGen/CoverageMappingGen.h
lib/CodeGen/CoverageMappingGen.cpp