clang: clang::ASTFrontendAction Class Reference
clang::ASTFrontendAction Class Reference
Abstract base class to use for AST consumer-based frontend actions.
#include "clang/Frontend/FrontendAction.h"
Public Member Functions
ASTFrontendAction ()
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual TranslationUnitKind getTranslationUnitKind ()
For AST-based actions, the kind of translation unit we're handling.
virtual bool hasPCHSupport () const
Does this action support use with PCH?
virtual bool hasASTFileSupport () const
Does this action support use with AST files?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Protected Member Functions
void ExecuteAction () override
Implement the ExecuteAction interface by running Sema on the already-initialized AST consumer.
Protected Member Functions inherited from clang::FrontendAction
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile)=0
Create the AST consumer object for this action, if supported.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool BeginSourceFileAction (CompilerInstance &CI)
Callback at the start of processing a single input.
virtual void EndSourceFileAction ()
Callback at the end of processing a single input.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Detailed Description
Abstract base class to use for AST consumer-based frontend actions.
Definition at line 243 of file FrontendAction.h.
Constructor & Destructor Documentation
ASTFrontendAction()
clang::ASTFrontendAction::ASTFrontendAction () inline
Definition at line 253 of file FrontendAction.h.
Member Function Documentation
ExecuteAction()
void ASTFrontendAction::ExecuteAction () override protected virtual
Implement the ExecuteAction interface by running Sema on the already-initialized AST consumer.
This will also take care of instantiating a code completion consumer if the user requested it and the action supports it.
Implements clang::FrontendAction.
Reimplemented in ASTSrcLocGenerationAction, clang::CodeGenAction, clang::DumpModuleInfoAction, clang::TemplightDumpAction, and clang::VerifyPCHAction.
Definition at line 1150 of file FrontendAction.cpp.
References clang::FrontendOptions::CodeCompletionAt, clang::CompilerInstance::createCodeCompletionConsumer(), clang::CompilerInstance::createSema(), clang::ParsedSourceLocation::FileName, clang::CompilerInstance::getCodeCompletionConsumer(), clang::FrontendAction::getCompilerInstance(), clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getSema(), clang::FrontendAction::getTranslationUnitKind(), clang::CompilerInstance::hasCodeCompletionConsumer(), clang::FrontendAction::hasCodeCompletionSupport(), clang::CompilerInstance::hasPreprocessor(), clang::CompilerInstance::hasSema(), clang::noteBottomOfStack(), clang::ParseAST(), clang::FrontendOptions::ShowStats, and clang::FrontendOptions::SkipFunctionBodies.
Referenced by ASTSrcLocGenerationAction::ExecuteAction(), clang::CodeGenAction::ExecuteAction(), and clang::TemplightDumpAction::ExecuteAction().
usesPreprocessorOnly()
bool clang::ASTFrontendAction::usesPreprocessorOnly () const inline override virtual
Does this action only use the preprocessor?
If so no AST context will be created and this action will be invalid with AST file inputs.
Implements clang::FrontendAction.
Definition at line 254 of file FrontendAction.h.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendAction.h
lib/Frontend/FrontendAction.cpp