clang: clang::extractapi::DeclarationFragments Class Reference
clang::extractapi::DeclarationFragments Class Reference
DeclarationFragments is a vector of tagged important parts of a symbol's declaration.
#include "clang/ExtractAPI/DeclarationFragments.h"
Classes
struct Fragment
Fragment holds information of a single fragment.
Public Types
enum class FragmentKind {
None , Keyword , Attribute , NumberLiteral ,
StringLiteral , Identifier , TypeIdentifier , GenericParameter ,
ExternalParam , InternalParam , Text
}
The kind of a fragment.
using FragmentIterator = std::vector<Fragment>::iterator
using ConstFragmentIterator = std::vector<Fragment>::const_iterator
Public Member Functions
DeclarationFragments ()=default
const std::vector< Fragment > & getFragments () const
FragmentIterator begin ()
FragmentIterator end ()
ConstFragmentIterator cbegin () const
ConstFragmentIterator cend () const
DeclarationFragments & insert (FragmentIterator It, StringRef Spelling, FragmentKind Kind, StringRef PreciseIdentifier="", const Decl *Declaration=nullptr)
DeclarationFragments & insert (FragmentIterator It, DeclarationFragments &&Other)
DeclarationFragments & append (StringRef Spelling, FragmentKind Kind, StringRef PreciseIdentifier="", const Decl *Declaration=nullptr)
Append a new Fragment to the end of the Fragments.
DeclarationFragments & append (DeclarationFragments &&Other)
Append another DeclarationFragments to the end.
DeclarationFragments & appendSpace ()
Append a text Fragment of a space character.
Static Public Member Functions
static StringRef getFragmentKindString (FragmentKind Kind)
Get the string description of a FragmentKind Kind.
static FragmentKind parseFragmentKindFromString (StringRef S)
Get the corresponding FragmentKind from string S.
Detailed Description
DeclarationFragments is a vector of tagged important parts of a symbol's declaration.
The fragments sequence can be joined to form spans of declaration text, with attached information useful for purposes like syntax-highlighting etc. For example:
const -> keyword    "const"
int   -> type       "int"
pi;   -> identifier "pi"
Definition at line 43 of file DeclarationFragments.h.
Member Typedef Documentation
ConstFragmentIterator
using clang::extractapi::DeclarationFragments::ConstFragmentIterator = std::vector<Fragment>::const_iterator
Definition at line 101 of file DeclarationFragments.h.
FragmentIterator
using clang::extractapi::DeclarationFragments::FragmentIterator = std::vector<Fragment>::iterator
Definition at line 100 of file DeclarationFragments.h.
Member Enumeration Documentation
FragmentKind
enum class clang::extractapi::DeclarationFragments::FragmentKind strong
The kind of a fragment.
Enumerator
None
Unknown fragment kind.
Keyword
Attribute
NumberLiteral
StringLiteral
Identifier
TypeIdentifier
Identifier that refers to a type in the context.
GenericParameter
Parameter that's used as generics in the context.
For example template parameters.
ExternalParam
External parameters in Objective-C methods.
For example, forKey in
- (void) setValue:(Value)value forKey(Key)key
InternalParam
Internal/local parameters in Objective-C methods.
For example, key in
- (void) setValue:(Value)value forKey(Key)key
Text
Definition at line 48 of file DeclarationFragments.h.
Constructor & Destructor Documentation
DeclarationFragments()
clang::extractapi::DeclarationFragments::DeclarationFragments () default
Member Function Documentation
append() [1/2]
DeclarationFragments & clang::extractapi::DeclarationFragments::append (DeclarationFragments && Other) inline
Append another DeclarationFragments to the end.
Note: Other is moved from and cannot be used after a call to this method.
Returns
a reference to the DeclarationFragments object itself after appending to chain up consecutive appends.
Definition at line 156 of file DeclarationFragments.h.
append() [2/2]
DeclarationFragments & clang::extractapi::DeclarationFragments::append (StringRef Spelling, FragmentKind Kind, StringRef PreciseIdentifier = "", const Decl * Declaration = nullptr) inline
Append a new Fragment to the end of the Fragments.
Returns
a reference to the DeclarationFragments object itself after appending to chain up consecutive appends.
Definition at line 135 of file DeclarationFragments.h.
References clang::Declaration, and Text.
Referenced by appendSpace(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnum(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnumConstant(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForField(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForFunction(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForMacro(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCCategory(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCInterface(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCMethod(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCProperty(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCProtocol(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForStruct(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForTypedef(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar(), clang::extractapi::DeclarationFragmentsBuilder::getFunctionSignature(), clang::extractapi::DeclarationFragmentsBuilder::getSubHeading(), clang::extractapi::DeclarationFragmentsBuilder::getSubHeading(), and clang::extractapi::DeclarationFragmentsBuilder::getSubHeadingForMacro().
appendSpace()
DeclarationFragments & DeclarationFragments::appendSpace ()
Append a text Fragment of a space character.
Returns
a reference to the DeclarationFragments object itself after appending to chain up consecutive appends.
Definition at line 22 of file DeclarationFragments.cpp.
References append(), clang::Last, and Text.
Referenced by clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnum(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForField(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForFunction(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForMacro(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCCategory(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCInterface(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCMethod(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCProperty(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCProtocol(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForStruct(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForTypedef(), and clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar().
begin()
FragmentIterator clang::extractapi::DeclarationFragments::begin () inline
Definition at line 105 of file DeclarationFragments.h.
cbegin()
ConstFragmentIterator clang::extractapi::DeclarationFragments::cbegin () const inline
Definition at line 109 of file DeclarationFragments.h.
cend()
ConstFragmentIterator clang::extractapi::DeclarationFragments::cend () const inline
Definition at line 111 of file DeclarationFragments.h.
end()
FragmentIterator clang::extractapi::DeclarationFragments::end () inline
Definition at line 107 of file DeclarationFragments.h.
getFragmentKindString()
StringRef DeclarationFragments::getFragmentKindString (DeclarationFragments::FragmentKind Kind) static
Get the string description of a FragmentKind Kind.
Definition at line 39 of file DeclarationFragments.cpp.
References Attribute, ExternalParam, GenericParameter, Identifier, InternalParam, Keyword, None, NumberLiteral, StringLiteral, Text, and TypeIdentifier.
getFragments()
const std::vector< Fragment > & clang::extractapi::DeclarationFragments::getFragments () const inline
Definition at line 103 of file DeclarationFragments.h.
Referenced by clang::extractapi::FunctionSignature::empty().
insert() [1/2]
DeclarationFragments & clang::extractapi::DeclarationFragments::insert (FragmentIterator It, DeclarationFragments && Other) inline
Definition at line 123 of file DeclarationFragments.h.
insert() [2/2]
DeclarationFragments & clang::extractapi::DeclarationFragments::insert (FragmentIterator It, StringRef Spelling, FragmentKind Kind, StringRef PreciseIdentifier = "", const Decl * Declaration = nullptr) inline
Definition at line 114 of file DeclarationFragments.h.
References clang::Declaration.
parseFragmentKindFromString()
DeclarationFragments::FragmentKind DeclarationFragments::parseFragmentKindFromString (StringRef S) static
Get the corresponding FragmentKind from string S.
Definition at line 70 of file DeclarationFragments.cpp.
References Attribute, ExternalParam, GenericParameter, Identifier, InternalParam, Keyword, None, NumberLiteral, StringLiteral, Text, and TypeIdentifier.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/DeclarationFragments.h
lib/ExtractAPI/DeclarationFragments.cpp