clang: clang::OffsetOfNode Class Reference
clang::OffsetOfNode Class Reference
Helper class for OffsetOfExpr.
#include "clang/AST/Expr.h"
Public Types
enum Kind { Array = 0x00 , Field = 0x01 , Identifier = 0x02 , Base = 0x03 }
The kind of offsetof node we have.
Public Member Functions
OffsetOfNode (SourceLocation LBracketLoc, unsigned Index, SourceLocation RBracketLoc)
Create an offsetof node that refers to an array element.
OffsetOfNode (SourceLocation DotLoc, FieldDecl *Field, SourceLocation NameLoc)
Create an offsetof node that refers to a field.
OffsetOfNode (SourceLocation DotLoc, IdentifierInfo *Name, SourceLocation NameLoc)
Create an offsetof node that refers to an identifier.
OffsetOfNode (const CXXBaseSpecifier *Base)
Create an offsetof node that refers into a C++ base class.
Kind getKind () const
Determine what kind of offsetof node this is.
unsigned getArrayExprIndex () const
For an array element node, returns the index into the array of expressions.
FieldDecl * getField () const
For a field offsetof node, returns the field.
IdentifierInfo * getFieldName () const
For a field or identifier offsetof node, returns the name of the field.
CXXBaseSpecifier * getBase () const
For a base class node, returns the base specifier.
SourceRange getSourceRange () const LLVM_READONLY
Retrieve the source range that covers this offsetof node.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
Detailed Description
Helper class for OffsetOfExpr.
Definition at line 2370 of file Expr.h.
Member Enumeration Documentation
Kind
enum clang::OffsetOfNode::Kind
The kind of offsetof node we have.
Enumerator
Array
An index into an array.
Field
A field.
Identifier
A field in a dependent type, known only by its name.
Base
An implicit indirection through a C++ base class, when the field found is in a base class.
Definition at line 2373 of file Expr.h.
Constructor & Destructor Documentation
OffsetOfNode() [1/4]
clang::OffsetOfNode::OffsetOfNode (SourceLocation LBracketLoc, unsigned Index, SourceLocation RBracketLoc) inline
Create an offsetof node that refers to an array element.
Definition at line 2404 of file Expr.h.
References Data.
OffsetOfNode() [2/4]
clang::OffsetOfNode::OffsetOfNode (SourceLocation DotLoc, FieldDecl * Field, SourceLocation NameLoc) inline
Create an offsetof node that refers to a field.
Definition at line 2409 of file Expr.h.
References Data.
OffsetOfNode() [3/4]
clang::OffsetOfNode::OffsetOfNode (SourceLocation DotLoc, IdentifierInfo * Name, SourceLocation NameLoc) inline
Create an offsetof node that refers to an identifier.
Definition at line 2414 of file Expr.h.
References Data.
OffsetOfNode() [4/4]
clang::OffsetOfNode::OffsetOfNode (const CXXBaseSpecifier * Base) inline explicit
Create an offsetof node that refers into a C++ base class.
Definition at line 2420 of file Expr.h.
References Data.
Member Function Documentation
getArrayExprIndex()
unsigned clang::OffsetOfNode::getArrayExprIndex () const inline
For an array element node, returns the index into the array of expressions.
Definition at line 2428 of file Expr.h.
References Data, and getKind().
Referenced by clang::ASTNodeImporter::VisitOffsetOfExpr().
getBase()
CXXBaseSpecifier * clang::OffsetOfNode::getBase () const inline
For a base class node, returns the base specifier.
Definition at line 2444 of file Expr.h.
References Data, and getKind().
Referenced by clang::ASTNodeImporter::VisitOffsetOfExpr().
getBeginLoc()
SourceLocation clang::OffsetOfNode::getBeginLoc () const inline
Definition at line 2456 of file Expr.h.
Referenced by clang::ASTNodeImporter::VisitOffsetOfExpr().
getEndLoc()
SourceLocation clang::OffsetOfNode::getEndLoc () const inline
Definition at line 2457 of file Expr.h.
Referenced by clang::ASTNodeImporter::VisitOffsetOfExpr(), and clang::tooling::RecursiveSymbolVisitor< T >::VisitOffsetOfExpr().
getField()
FieldDecl * clang::OffsetOfNode::getField () const inline
For a field offsetof node, returns the field.
Definition at line 2434 of file Expr.h.
References Data, Field, and getKind().
Referenced by getFieldName(), clang::ASTNodeImporter::VisitOffsetOfExpr(), and clang::tooling::RecursiveSymbolVisitor< T >::VisitOffsetOfExpr().
getFieldName()
IdentifierInfo * OffsetOfNode::getFieldName () const
For a field or identifier offsetof node, returns the name of the field.
Definition at line 1703 of file Expr.cpp.
References Field, getField(), clang::NamedDecl::getIdentifier(), getKind(), and Identifier.
Referenced by clang::ASTNodeImporter::VisitOffsetOfExpr().
getKind()
Kind clang::OffsetOfNode::getKind () const inline
Determine what kind of offsetof node this is.
Definition at line 2424 of file Expr.h.
References Data.
Referenced by getArrayExprIndex(), getBase(), getField(), getFieldName(), clang::ASTNodeImporter::VisitOffsetOfExpr(), and clang::tooling::RecursiveSymbolVisitor< T >::VisitOffsetOfExpr().
getSourceRange()
SourceRange clang::OffsetOfNode::getSourceRange () const inline
Retrieve the source range that covers this offsetof node.
For an array element node, the source range contains the locations of the square brackets. For a field or identifier node, the source range contains the location of the period (if there is one) and the identifier.
Definition at line 2455 of file Expr.h.
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp