clang: clang::diff::ZhangShashaMatcher Class Reference
clang::diff::ZhangShashaMatcher Class Reference
Implementation of Zhang and Shasha's Algorithm for tree edit distance.
Public Member Functions
ZhangShashaMatcher (const ASTDiff::Impl &DiffImpl, const SyntaxTree::Impl &T1, const SyntaxTree::Impl &T2, NodeId Id1, NodeId Id2)
std::vector< std::pair< NodeId, NodeId > > getMatchingNodes ()
Detailed Description
Implementation of Zhang and Shasha's Algorithm for tree edit distance.
Computes an optimal mapping between two trees using only insertion, deletion and update as edit actions (similar to the Levenshtein distance).
Definition at line 558 of file ASTDiff.cpp.
Constructor & Destructor Documentation
ZhangShashaMatcher()
clang::diff::ZhangShashaMatcher::ZhangShashaMatcher (const ASTDiff::Impl & DiffImpl, const SyntaxTree::Impl & T1, const SyntaxTree::Impl & T2, NodeId Id1, NodeId Id2) inline
Definition at line 565 of file ASTDiff.cpp.
References clang::diff::Subtree::getSize().
Member Function Documentation
getMatchingNodes()
std::vector< std::pair< NodeId, NodeId > > clang::diff::ZhangShashaMatcher::getMatchingNodes () inline
Definition at line 578 of file ASTDiff.cpp.
References clang::diff::Subtree::getIdInRoot(), clang::diff::Subtree::getLeftMostDescendant(), and clang::diff::Subtree::getSize().
The documentation for this class was generated from the following file:
lib/Tooling/ASTDiff/ASTDiff.cpp