clang: clang::Selector Class Reference
clang::Selector Class Reference
Smart pointer class that efficiently represents Objective-C method names.
#include "clang/Basic/IdentifierTable.h"
Public Member Functions
Selector ()=default
The default ctor should only be used when creating data structures that will contain selectors.
Selector (uintptr_t V)
bool operator== (Selector RHS) const
operator==/!= - Indicate whether the specified selectors are identical.
bool operator!= (Selector RHS) const
void * getAsOpaquePtr () const
bool isNull () const
Determine whether this is the empty selector.
bool isKeywordSelector () const
bool isUnarySelector () const
bool isKeywordSelector (ArrayRef< StringRef > Names) const
If this selector is the specific keyword selector described by Names.
bool isUnarySelector (StringRef Name) const
If this selector is the specific unary selector described by Name.
unsigned getNumArgs () const
IdentifierInfo * getIdentifierInfoForSlot (unsigned argIndex) const
Retrieve the identifier at a given position in the selector.
StringRef getNameForSlot (unsigned argIndex) const
Retrieve the name at a given position in the selector.
std::string getAsString () const
Derive the full selector name (e.g.
void print (llvm::raw_ostream &OS) const
Prints the full selector name (e.g. "foo:bar:").
void dump () const
ObjCMethodFamily getMethodFamily () const
Derive the conventional family of this method.
ObjCStringFormatFamily getStringFormatFamily () const
Static Public Member Functions
static Selector getEmptyMarker ()
static Selector getTombstoneMarker ()
static ObjCInstanceTypeFamily getInstTypeMethodFamily (Selector sel)
Friends
class Diagnostic
class SelectorTable
class DeclarationName
Detailed Description
Smart pointer class that efficiently represents Objective-C method names.
This class will either point to an IdentifierInfo or a MultiKeywordSelector (which is private). This enables us to optimize selectors that take no arguments and selectors that take 1 argument, which accounts for 78% of all selectors in Cocoa.h.
Definition at line 801 of file IdentifierTable.h.
Constructor & Destructor Documentation
Selector() [1/2]
clang::Selector::Selector () default
The default ctor should only be used when creating data structures that will contain selectors.
Selector() [2/2]
clang::Selector::Selector (uintptr_t V) inline explicit
Definition at line 856 of file IdentifierTable.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void Selector::dump () const
Definition at line 655 of file IdentifierTable.cpp.
References print().
getAsOpaquePtr()
void * clang::Selector::getAsOpaquePtr () const inline
Definition at line 866 of file IdentifierTable.h.
Referenced by clang::ASTWriter::getSelectorRef().
getAsString()
std::string Selector::getAsString () const
Derive the full selector name (e.g.
"foo:bar:") and return it as an std::string.
Definition at line 628 of file IdentifierTable.cpp.
References clang::IdentifierInfo::getName(), clang::MultiKeywordSelector::getName(), and getNumArgs().
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::ast_matchers::AST_MATCHER_P(), clang::Sema::CheckMessageArgumentTypes(), clang::ASTContext::getObjCEncodingForPropertyDecl(), clang::Sema::ParseObjCSelectorExpression(), print(), and clang::Sema::SelectorsForTypoCorrection().
getEmptyMarker()
static Selector clang::Selector::getEmptyMarker () inline static
Definition at line 933 of file IdentifierTable.h.
Referenced by llvm::DenseMapInfo< clang::Selector >::getEmptyKey().
getIdentifierInfoForSlot()
IdentifierInfo * Selector::getIdentifierInfoForSlot (unsigned argIndex) const
Retrieve the identifier at a given position in the selector.
Note that the identifier pointer returned may be NULL. Clients that only care about the text of the identifier string, and not the specific, uniqued identifier pointer, should use getNameForSlot(), which returns an empty string when the identifier pointer would be NULL.
Parameters
argIndex The index for which we want to retrieve the identifier. This index shall be less than getNumArgs() unless this is a keyword selector, in which case 0 is the only permissible value.
Returns
the uniqued identifier for this slot, or NULL if this slot has no corresponding identifier.
Definition at line 600 of file IdentifierTable.cpp.
References clang::MultiKeywordSelector::getIdentifierInfoForSlot().
Referenced by clang::ento::ObjCMethodCall::argumentsMayEscape(), clang::serialization::ComputeHash(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), GetAssumedMessageSendExprType(), getInstTypeMethodFamily(), getNameForSlot(), getStandardSelLoc(), clang::ASTImporter::Import(), isAcceptableObjCSelector(), and IsStructurallyEquivalent().
getInstTypeMethodFamily()
ObjCInstanceTypeFamily Selector::getInstTypeMethodFamily (Selector sel) static
Definition at line 714 of file IdentifierTable.cpp.
References getIdentifierInfoForSlot(), clang::IdentifierInfo::getName(), clang::OIT_Array, clang::OIT_Dictionary, clang::OIT_Init, clang::OIT_None, clang::OIT_ReturnsSelf, clang::OIT_Singleton, and startsWithWord().
getMethodFamily()
ObjCMethodFamily clang::Selector::getMethodFamily () const inline
Derive the conventional family of this method.
Definition at line 925 of file IdentifierTable.h.
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::BuildInstanceMessage(), clang::ObjCMessageExpr::getMethodFamily(), clang::ObjCMethodDecl::getMethodFamily(), clang::Sema::ParseObjCSelectorExpression(), and tryGenerateSpecializedMessageSend().
getNameForSlot()
StringRef Selector::getNameForSlot (unsigned argIndex) const
Retrieve the name at a given position in the selector.
Parameters
argIndex The index for which we want to retrieve the name. This index shall be less than getNumArgs() unless this is a keyword selector, in which case 0 is the only permissible value.
Returns
the name for this slot, which may be the empty string if no name was supplied.
Definition at line 611 of file IdentifierTable.cpp.
References getIdentifierInfoForSlot(), and clang::IdentifierInfo::getName().
Referenced by AddSuperSendCompletion(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCSelector(), clang::DeclarationName::compare(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::Sema::DiagnoseAssignmentAsCondition(), DoEmitAvailabilityWarning(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCMethod(), clang::SelectorTable::getPropertyNameFromSetterSelector(), hasDefaultGetterName(), hasDefaultSetterName(), isAcceptableMethodMismatch(), isKeywordSelector(), isSetterLikeSelector(), isUnarySelector(), isUnitTest(), rewriteToObjCProperty(), tryEmitSpecializedAllocInit(), and tryGenerateSpecializedMessageSend().
getNumArgs()
unsigned Selector::getNumArgs () const
Definition at line 589 of file IdentifierTable.cpp.
References clang::detail::DeclarationNameExtra::getNumArgs().
Referenced by clang::Sema::ActOnMethodDeclaration(), AddSuperSendCompletion(), clang::ento::ObjCMethodCall::argumentsMayEscape(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCSelector(), clang::DeclarationName::compare(), clang::serialization::ComputeHash(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), DoEmitAvailabilityWarning(), clang::ObjCMethodDecl::findPropertyDecl(), getAsString(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCMethod(), clang::ObjCSelectorExpr::getNumArgs(), clang::ObjCMessageExpr::getNumSelectorLocs(), clang::ObjCMethodDecl::getNumSelectorLocs(), getStandardSelLoc(), clang::ASTImporter::Import(), isAcceptableObjCSelector(), isKeywordSelector(), isSetterLikeSelector(), IsStructurallyEquivalent(), clang::ObjCMethodDecl::sel_param_end(), clang::Sema::SelectorsForTypoCorrection(), and tryGenerateSpecializedMessageSend().
getStringFormatFamily()
ObjCStringFormatFamily clang::Selector::getStringFormatFamily () const inline
Definition at line 929 of file IdentifierTable.h.
Referenced by DiagnoseCStringFormatDirectiveInObjCAPI().
getTombstoneMarker()
static Selector clang::Selector::getTombstoneMarker () inline static
Definition at line 937 of file IdentifierTable.h.
Referenced by llvm::DenseMapInfo< clang::Selector >::getTombstoneKey().
isKeywordSelector() [1/2]
bool clang::Selector::isKeywordSelector () const inline
Definition at line 874 of file IdentifierTable.h.
Referenced by tryGenerateSpecializedMessageSend().
isKeywordSelector() [2/2]
bool Selector::isKeywordSelector (ArrayRef< StringRef > Names) const
If this selector is the specific keyword selector described by Names.
Definition at line 574 of file IdentifierTable.cpp.
References getNameForSlot(), and getNumArgs().
isNull()
bool clang::Selector::isNull () const inline
Determine whether this is the empty selector.
Definition at line 871 of file IdentifierTable.h.
Referenced by clang::Sema::ActOnInstanceMessage(), AddClassMessageCompletions(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCMethodDeclSelector(), clang::Sema::CodeCompleteObjCSelector(), GetAssumedMessageSendExprType(), clang::MultiplexExternalSemaSource::GetExternalSelector(), clang::ASTImporter::Import(), and clang::lazyInitKeywordSelector().
isUnarySelector() [1/2]
bool clang::Selector::isUnarySelector () const inline
Definition at line 878 of file IdentifierTable.h.
Referenced by AddSuperSendCompletion(), clang::Sema::BuildInstanceMessage(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteObjCSelector(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::Sema::DiagnoseAssignmentAsCondition(), clang::ObjCMessageExpr::getNumSelectorLocs(), clang::ObjCMethodDecl::getNumSelectorLocs(), isAcceptableMethodMismatch(), isAcceptableObjCSelector(), isSetterLikeSelector(), isUnarySelector(), tryEmitSpecializedAllocInit(), and tryGenerateSpecializedMessageSend().
isUnarySelector() [2/2]
bool Selector::isUnarySelector (StringRef Name) const
If this selector is the specific unary selector described by Name.
Definition at line 585 of file IdentifierTable.cpp.
References getNameForSlot(), and isUnarySelector().
operator!=()
bool clang::Selector::operator!= (Selector RHS) const inline
Definition at line 862 of file IdentifierTable.h.
operator==()
bool clang::Selector::operator== (Selector RHS) const inline
operator==/!= - Indicate whether the specified selectors are identical.
Definition at line 859 of file IdentifierTable.h.
print()
void Selector::print (llvm::raw_ostream & OS) const
Prints the full selector name (e.g. "foo:bar:").
Definition at line 651 of file IdentifierTable.cpp.
References getAsString().
Referenced by CompareReturnTypes(), dump(), clang::MangleContext::mangleObjCMethodName(), clang::DeclarationName::print(), clang::JSONNodeDumper::VisitObjCMessageExpr(), and clang::JSONNodeDumper::VisitObjCSelectorExpr().
Friends And Related Symbol Documentation
DeclarationName
friend class DeclarationName friend
Definition at line 804 of file IdentifierTable.h.
Diagnostic
friend class Diagnostic friend
Definition at line 802 of file IdentifierTable.h.
SelectorTable
friend class SelectorTable friend
Definition at line 803 of file IdentifierTable.h.
The documentation for this class was generated from the following files:
include/clang/Basic/IdentifierTable.h
lib/Basic/IdentifierTable.cpp