clang: clang::CodeGen::CGHLSLRuntime Class Reference
clang::CodeGen::CGHLSLRuntime Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/CGHLSLRuntime.h"
Classes
struct Buffer
struct BufferResBinding
Public Member Functions
CGHLSLRuntime (CodeGenModule &CGM)
virtual ~CGHLSLRuntime ()
void annotateHLSLResource (const VarDecl *D, llvm::GlobalVariable *GV)
void generateGlobalCtorDtorCalls ()
void addBuffer (const HLSLBufferDecl *D)
void finishCodeGen ()
void setHLSLEntryAttributes (const FunctionDecl *FD, llvm::Function *Fn)
void emitEntryFunction (const FunctionDecl *FD, llvm::Function *Fn)
void setHLSLFunctionAttributes (llvm::Function *, const FunctionDecl *)
Protected Member Functions
llvm::Value * emitInputSemantic (llvm::IRBuilder<> &B, const ParmVarDecl &D, llvm::Type *Ty)
Protected Attributes
CodeGenModule & CGM
Detailed Description
Definition at line 49 of file CGHLSLRuntime.h.
Constructor & Destructor Documentation
CGHLSLRuntime()
clang::CodeGen::CGHLSLRuntime::CGHLSLRuntime (CodeGenModule & CGM) inline
Definition at line 77 of file CGHLSLRuntime.h.
~CGHLSLRuntime()
virtual clang::CodeGen::CGHLSLRuntime::~CGHLSLRuntime () inline virtual
Definition at line 78 of file CGHLSLRuntime.h.
Member Function Documentation
addBuffer()
void CGHLSLRuntime::addBuffer (const HLSLBufferDecl * D)
Definition at line 157 of file CGHLSLRuntime.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitTopLevelDecl().
annotateHLSLResource()
void CGHLSLRuntime::annotateHLSLResource (const VarDecl * D, llvm::GlobalVariable * GV)
Definition at line 276 of file CGHLSLRuntime.cpp.
References castResourceShapeToResourceKind(), clang::Type::getAsCXXRecordDecl(), clang::QualType::getAsString(), clang::Decl::getAttr(), clang::Type::getPointeeOrArrayElementType(), and clang::ValueDecl::getType().
emitEntryFunction()
void CGHLSLRuntime::emitEntryFunction (const FunctionDecl * FD, llvm::Function * Fn)
Definition at line 357 of file CGHLSLRuntime.cpp.
References CGM, emitInputSemantic(), clang::CodeGen::CodeGenModule::getModule(), clang::NamedDecl::getName(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), and setHLSLEntryAttributes().
emitInputSemantic()
llvm::Value * CGHLSLRuntime::emitInputSemantic (llvm::IRBuilder<> & B, const ParmVarDecl & D, llvm::Type * Ty) protected
Definition at line 340 of file CGHLSLRuntime.cpp.
References buildVectorInput(), CGM, clang::CodeGen::CodeGenModule::getIntrinsic(), clang::Decl::hasAttr(), and clang::Decl::hasAttrs().
Referenced by emitEntryFunction().
finishCodeGen()
void CGHLSLRuntime::finishCodeGen ()
Definition at line 162 of file CGHLSLRuntime.cpp.
References clang::CodeGen::CGHLSLRuntime::Buffer::Binding, CGM, generateGlobalCtorDtorCalls(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTargetOpts(), clang::CodeGen::CGHLSLRuntime::Buffer::IsCBuffer, and clang::CodeGen::CGHLSLRuntime::Buffer::Name.
Referenced by clang::CodeGen::CodeGenModule::Release().
generateGlobalCtorDtorCalls()
void CGHLSLRuntime::generateGlobalCtorDtorCalls ()
Definition at line 427 of file CGHLSLRuntime.cpp.
References CGM, gatherFunctions(), and clang::CodeGen::CodeGenModule::getModule().
Referenced by finishCodeGen().
setHLSLEntryAttributes()
void clang::CodeGen::CGHLSLRuntime::setHLSLEntryAttributes (const FunctionDecl * FD, llvm::Function * Fn)
Definition at line 312 of file CGHLSLRuntime.cpp.
References clang::Decl::getAttr().
Referenced by emitEntryFunction().
setHLSLFunctionAttributes()
void clang::CodeGen::CGHLSLRuntime::setHLSLFunctionAttributes (llvm::Function * , const FunctionDecl *)
Member Data Documentation
CGM
CodeGenModule& clang::CodeGen::CGHLSLRuntime::CGM protected
Definition at line 71 of file CGHLSLRuntime.h.
Referenced by emitEntryFunction(), emitInputSemantic(), finishCodeGen(), and generateGlobalCtorDtorCalls().
The documentation for this class was generated from the following files:
lib/CodeGen/CGHLSLRuntime.h
lib/CodeGen/CGHLSLRuntime.cpp