clang: clang::AttributePool Class Reference
clang::AttributePool Class Reference
#include "clang/Sema/ParsedAttr.h"
Public Member Functions
AttributePool (AttributeFactory &factory)
Create a new pool for a factory.
AttributePool (const AttributePool &)=delete
AttributePool & operator= (const AttributePool &)=delete
~AttributePool ()
AttributePool (AttributePool &&pool)=default
Move the given pool's allocations to this pool.
AttributePool & operator= (AttributePool &&pool)=delete
AttributeFactory & getFactory () const
void clear ()
void takeAllFrom (AttributePool &pool)
Take the given pool's allocations and add them to this pool.
ParsedAttr * create (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, ArgsUnion *args, unsigned numArgs, ParsedAttr::Form form, SourceLocation ellipsisLoc=SourceLocation())
ParsedAttr * create (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *Param, const AvailabilityChange &introduced, const AvailabilityChange &deprecated, const AvailabilityChange &obsoleted, SourceLocation unavailable, const Expr *MessageExpr, ParsedAttr::Form form, SourceLocation strict, const Expr *ReplacementExpr)
ParsedAttr * create (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *Param1, IdentifierLoc *Param2, IdentifierLoc *Param3, ParsedAttr::Form form)
ParsedAttr * createTypeTagForDatatype (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *argumentKind, ParsedType matchingCType, bool layoutCompatible, bool mustBeNull, ParsedAttr::Form form)
ParsedAttr * createTypeAttribute (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, ParsedType typeArg, ParsedAttr::Form formUsed, SourceLocation ellipsisLoc)
ParsedAttr * createPropertyAttribute (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierInfo *getterId, IdentifierInfo *setterId, ParsedAttr::Form formUsed)
Friends
class AttributeFactory
class ParsedAttributes
Detailed Description
Definition at line 672 of file ParsedAttr.h.
Constructor & Destructor Documentation
AttributePool() [1/3]
clang::AttributePool::AttributePool (AttributeFactory & factory) inline
Create a new pool for a factory.
Definition at line 697 of file ParsedAttr.h.
AttributePool() [2/3]
clang::AttributePool::AttributePool (const AttributePool &) delete
~AttributePool()
clang::AttributePool::~AttributePool () inline
Definition at line 704 of file ParsedAttr.h.
AttributePool() [3/3]
clang::AttributePool::AttributePool (AttributePool && pool) default
Move the given pool's allocations to this pool.
Member Function Documentation
clear()
void clang::AttributePool::clear () inline
Definition at line 715 of file ParsedAttr.h.
Referenced by clang::ParsedAttributes::clear().
create() [1/3]
ParsedAttr * clang::AttributePool::create (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, ArgsUnion * args, unsigned numArgs, ParsedAttr::Form form, SourceLocation ellipsisLoc = SourceLocation()) inline
Definition at line 726 of file ParsedAttr.h.
Referenced by clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNew(), and transferARCOwnershipToDeclaratorChunk().
create() [2/3]
ParsedAttr * clang::AttributePool::create (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * Param, const AvailabilityChange & introduced, const AvailabilityChange & deprecated, const AvailabilityChange & obsoleted, SourceLocation unavailable, const Expr * MessageExpr, ParsedAttr::Form form, SourceLocation strict, const Expr * ReplacementExpr) inline
Definition at line 744 of file ParsedAttr.h.
References clang::AttributeFactory::AvailabilityAllocSize.
create() [3/3]
ParsedAttr * clang::AttributePool::create (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * Param1, IdentifierLoc * Param2, IdentifierLoc * Param3, ParsedAttr::Form form) inline
Definition at line 758 of file ParsedAttr.h.
createPropertyAttribute()
ParsedAttr * clang::AttributePool::createPropertyAttribute (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierInfo * getterId, IdentifierInfo * setterId, ParsedAttr::Form formUsed) inline
Definition at line 797 of file ParsedAttr.h.
References clang::AttributeFactory::PropertyAllocSize.
Referenced by clang::ParsedAttributes::addNewPropertyAttr().
createTypeAttribute()
ParsedAttr * clang::AttributePool::createTypeAttribute (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, ParsedType typeArg, ParsedAttr::Form formUsed, SourceLocation ellipsisLoc) inline
Definition at line 782 of file ParsedAttr.h.
Referenced by clang::ParsedAttributes::addNewTypeAttr().
createTypeTagForDatatype()
ParsedAttr * clang::AttributePool::createTypeTagForDatatype (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * argumentKind, ParsedType matchingCType, bool layoutCompatible, bool mustBeNull, ParsedAttr::Form form) inline
Definition at line 771 of file ParsedAttr.h.
References clang::AttributeFactory::TypeTagForDatatypeAllocSize.
Referenced by clang::ParsedAttributes::addNewTypeTagForDatatype().
getFactory()
AttributeFactory & clang::AttributePool::getFactory () const inline
Definition at line 713 of file ParsedAttr.h.
Referenced by clang::Sema::ActOnCXXForRangeIdentifier().
operator=() [1/2]
AttributePool & clang::AttributePool::operator= (AttributePool && pool) delete
operator=() [2/2]
AttributePool & clang::AttributePool::operator= (const AttributePool &) delete
takeAllFrom()
void clang::AttributePool::takeAllFrom (AttributePool & pool) inline
Take the given pool's allocations and add them to this pool.
Definition at line 721 of file ParsedAttr.h.
Referenced by clang::Declarator::AddTypeInfo(), clang::DeclaratorChunk::getFunction(), clang::ParsedAttributes::takeAllFrom(), and takeDeclAttributes().
Friends And Related Symbol Documentation
AttributeFactory
friend class AttributeFactory friend
Definition at line 673 of file ParsedAttr.h.
ParsedAttributes
friend class ParsedAttributes friend
Definition at line 674 of file ParsedAttr.h.
The documentation for this class was generated from the following files:
include/clang/Sema/ParsedAttr.h
lib/Sema/ParsedAttr.cpp