clang: clang::TargetInfo Class Reference
clang::TargetInfo Class Reference abstract
Exposes information about the current target.
#include "clang/Basic/TargetInfo.h"
Classes
struct AddlRegName
struct BranchProtectionInfo
struct ConstraintInfo
struct GCCRegAlias
Public Types
enum BuiltinVaListKind {
CharPtrBuiltinVaList = 0 , VoidPtrBuiltinVaList , AArch64ABIBuiltinVaList , PNaClABIBuiltinVaList ,
PowerABIBuiltinVaList , X86_64ABIBuiltinVaList , AAPCSABIBuiltinVaList , SystemZBuiltinVaList ,
HexagonBuiltinVaList
}
The different kinds of __builtin_va_list types defined by the target implementation.
enum CallingConvCheckResult { CCCR_OK , CCCR_Warning , CCCR_Ignore , CCCR_Error }
enum CallingConvKind { CCK_Default , CCK_ClangABI4OrPS4 , CCK_MicrosoftWin64 }
Public Types inherited from clang::TransferrableTargetInfo
enum IntType {
NoInt = 0 , SignedChar , UnsignedChar , SignedShort ,
UnsignedShort , SignedInt , UnsignedInt , SignedLong ,
UnsignedLong , SignedLongLong , UnsignedLongLong
}
===-— Target Data Type Query Methods ----------------------------—===//
Public Member Functions
virtual ~TargetInfo ()
TargetOptions & getTargetOpts () const
Retrieve the target options.
IntType getSizeType () const
IntType getSignedSizeType () const
IntType getIntMaxType () const
IntType getUIntMaxType () const
IntType getPtrDiffType (LangAS AddrSpace) const
IntType getUnsignedPtrDiffType (LangAS AddrSpace) const
IntType getIntPtrType () const
IntType getUIntPtrType () const
IntType getWCharType () const
IntType getWIntType () const
IntType getChar16Type () const
IntType getChar32Type () const
IntType getInt64Type () const
IntType getUInt64Type () const
IntType getInt16Type () const
IntType getUInt16Type () const
IntType getSigAtomicType () const
IntType getProcessIDType () const
bool doUnsignedFixedPointTypesHavePadding () const
In the event this target uses the same number of fractional bits for its unsigned types as it does with its signed counterparts, there will be exactly one bit of padding.
unsigned getTypeWidth (IntType T) const
Return the width (in bits) of the specified integer type enum.
virtual IntType getIntTypeByWidth (unsigned BitWidth, bool IsSigned) const
Return integer type with specified width.
virtual IntType getLeastIntTypeByWidth (unsigned BitWidth, bool IsSigned) const
Return the smallest integer type with at least the specified width.
FloatModeKind getRealTypeByWidth (unsigned BitWidth, FloatModeKind ExplicitType) const
Return floating point type with specified width.
unsigned getTypeAlign (IntType T) const
Return the alignment (in bits) of the specified integer type enum.
uint64_t getPointerWidth (LangAS AddrSpace) const
Return the width of pointers on this target, for the specified address space.
uint64_t getPointerAlign (LangAS AddrSpace) const
virtual uint64_t getMaxPointerWidth () const
Return the maximum width of pointers on this target.
virtual uint64_t getNullPointerValue (LangAS AddrSpace) const
Get integer value for null pointer.
unsigned getBoolWidth () const
Return the size of '_Bool' and C++ 'bool' for this target, in bits.
unsigned getBoolAlign () const
Return the alignment of '_Bool' and C++ 'bool' for this target.
unsigned getCharWidth () const
unsigned getCharAlign () const
unsigned getShortWidth () const
Return the size of 'signed short' and 'unsigned short' for this target, in bits.
unsigned getShortAlign () const
Return the alignment of 'signed short' and 'unsigned short' for this target.
unsigned getIntWidth () const
getIntWidth/Align - Return the size of 'signed int' and 'unsigned int' for this target, in bits.
unsigned getIntAlign () const
unsigned getLongWidth () const
getLongWidth/Align - Return the size of 'signed long' and 'unsigned long' for this target, in bits.
unsigned getLongAlign () const
unsigned getLongLongWidth () const
getLongLongWidth/Align - Return the size of 'signed long long' and 'unsigned long long' for this target, in bits.
unsigned getLongLongAlign () const
unsigned getInt128Align () const
getInt128Align() - Returns the alignment of Int128.
unsigned getShortAccumWidth () const
getShortAccumWidth/Align - Return the size of 'signed short _Accum' and 'unsigned short _Accum' for this target, in bits.
unsigned getShortAccumAlign () const
unsigned getAccumWidth () const
getAccumWidth/Align - Return the size of 'signed _Accum' and 'unsigned _Accum' for this target, in bits.
unsigned getAccumAlign () const
unsigned getLongAccumWidth () const
getLongAccumWidth/Align - Return the size of 'signed long _Accum' and 'unsigned long _Accum' for this target, in bits.
unsigned getLongAccumAlign () const
unsigned getShortFractWidth () const
getShortFractWidth/Align - Return the size of 'signed short _Fract' and 'unsigned short _Fract' for this target, in bits.
unsigned getShortFractAlign () const
unsigned getFractWidth () const
getFractWidth/Align - Return the size of 'signed _Fract' and 'unsigned _Fract' for this target, in bits.
unsigned getFractAlign () const
unsigned getLongFractWidth () const
getLongFractWidth/Align - Return the size of 'signed long _Fract' and 'unsigned long _Fract' for this target, in bits.
unsigned getLongFractAlign () const
unsigned getShortAccumScale () const
getShortAccumScale/IBits - Return the number of fractional/integral bits in a 'signed short _Accum' type.
unsigned getShortAccumIBits () const
unsigned getAccumScale () const
getAccumScale/IBits - Return the number of fractional/integral bits in a 'signed _Accum' type.
unsigned getAccumIBits () const
unsigned getLongAccumScale () const
getLongAccumScale/IBits - Return the number of fractional/integral bits in a 'signed long _Accum' type.
unsigned getLongAccumIBits () const
unsigned getUnsignedShortAccumScale () const
getUnsignedShortAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned short _Accum' type.
unsigned getUnsignedShortAccumIBits () const
unsigned getUnsignedAccumScale () const
getUnsignedAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned _Accum' type.
unsigned getUnsignedAccumIBits () const
unsigned getUnsignedLongAccumScale () const
getUnsignedLongAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned long _Accum' type.
unsigned getUnsignedLongAccumIBits () const
unsigned getShortFractScale () const
getShortFractScale - Return the number of fractional bits in a 'signed short _Fract' type.
unsigned getFractScale () const
getFractScale - Return the number of fractional bits in a 'signed _Fract' type.
unsigned getLongFractScale () const
getLongFractScale - Return the number of fractional bits in a 'signed long _Fract' type.
unsigned getUnsignedShortFractScale () const
getUnsignedShortFractScale - Return the number of fractional bits in a 'unsigned short _Fract' type.
unsigned getUnsignedFractScale () const
getUnsignedFractScale - Return the number of fractional bits in a 'unsigned _Fract' type.
unsigned getUnsignedLongFractScale () const
getUnsignedLongFractScale - Return the number of fractional bits in a 'unsigned long _Fract' type.
virtual bool hasInt128Type () const
Determine whether the __int128 type is supported on this target.
virtual bool hasBitIntType () const
Determine whether the _BitInt type is supported on this target.
virtual size_t getMaxBitIntWidth () const
virtual bool hasLegalHalfType () const
Determine whether _Float16 is supported on this target.
virtual bool allowHalfArgsAndReturns () const
Whether half args and returns are supported.
virtual bool hasFloat128Type () const
Determine whether the __float128 type is supported on this target.
virtual bool hasFloat16Type () const
Determine whether the _Float16 type is supported on this target.
virtual bool hasBFloat16Type () const
Determine whether the _BFloat16 type is supported on this target.
virtual bool hasFullBFloat16Type () const
Determine whether the BFloat type is fully supported on this target, i.e arithemtic operations.
virtual bool hasIbm128Type () const
Determine whether the __ibm128 type is supported on this target.
virtual bool hasLongDoubleType () const
Determine whether the long double type is supported on this target.
virtual bool hasFPReturn () const
Determine whether return of a floating point value is supported on this target.
virtual bool hasStrictFP () const
Determine whether constrained floating point is supported on this target.
unsigned getSuitableAlign () const
Return the alignment that is the largest alignment ever used for any scalar/SIMD data type on the target machine you are compiling for (including types with an extended alignment requirement).
unsigned getDefaultAlignForAttributeAligned () const
Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
virtual unsigned getMinGlobalAlign (uint64_t) const
getMinGlobalAlign - Return the minimum alignment of a global variable, unless its alignment is explicitly reduced via attributes.
unsigned getNewAlign () const
Return the largest alignment for which a suitably-sized allocation with '::operator new(size_t)' is guaranteed to produce a correctly-aligned pointer.
unsigned getWCharWidth () const
getWCharWidth/Align - Return the size of 'wchar_t' for this target, in bits.
unsigned getWCharAlign () const
unsigned getChar16Width () const
getChar16Width/Align - Return the size of 'char16_t' for this target, in bits.
unsigned getChar16Align () const
unsigned getChar32Width () const
getChar32Width/Align - Return the size of 'char32_t' for this target, in bits.
unsigned getChar32Align () const
unsigned getHalfWidth () const
getHalfWidth/Align/Format - Return the size/align/format of 'half'.
unsigned getHalfAlign () const
const llvm::fltSemantics & getHalfFormat () const
unsigned getFloatWidth () const
getFloatWidth/Align/Format - Return the size/align/format of 'float'.
unsigned getFloatAlign () const
const llvm::fltSemantics & getFloatFormat () const
unsigned getBFloat16Width () const
getBFloat16Width/Align/Format - Return the size/align/format of '__bf16'.
unsigned getBFloat16Align () const
const llvm::fltSemantics & getBFloat16Format () const
unsigned getDoubleWidth () const
getDoubleWidth/Align/Format - Return the size/align/format of 'double'.
unsigned getDoubleAlign () const
const llvm::fltSemantics & getDoubleFormat () const
unsigned getLongDoubleWidth () const
getLongDoubleWidth/Align/Format - Return the size/align/format of 'long double'.
unsigned getLongDoubleAlign () const
const llvm::fltSemantics & getLongDoubleFormat () const
unsigned getFloat128Width () const
getFloat128Width/Align/Format - Return the size/align/format of '__float128'.
unsigned getFloat128Align () const
const llvm::fltSemantics & getFloat128Format () const
unsigned getIbm128Width () const
getIbm128Width/Align/Format - Return the size/align/format of '__ibm128'.
unsigned getIbm128Align () const
const llvm::fltSemantics & getIbm128Format () const
virtual const char * getLongDoubleMangling () const
Return the mangled code of long double.
virtual const char * getFloat128Mangling () const
Return the mangled code of __float128.
virtual const char * getIbm128Mangling () const
Return the mangled code of __ibm128.
virtual const char * getBFloat16Mangling () const
Return the mangled code of bfloat.
virtual LangOptions::FPEvalMethodKind getFPEvalMethod () const
Return the value for the C99 FLT_EVAL_METHOD macro.
virtual bool supportSourceEvalMethod () const
unsigned getLargeArrayMinWidth () const
unsigned getLargeArrayAlign () const
unsigned getMaxAtomicPromoteWidth () const
Return the maximum width lock-free atomic operation which will ever be supported for the given target.
unsigned getMaxAtomicInlineWidth () const
Return the maximum width lock-free atomic operation which can be inlined given the supported features of the given target.
virtual void setMaxAtomicWidth ()
Set the maximum inline or promote width lock-free atomic operation for the given target.
virtual bool hasBuiltinAtomic (uint64_t AtomicSizeInBits, uint64_t AlignmentInBits) const
Returns true if the given target supports lock-free atomic operations at the specified width and alignment.
unsigned getMaxVectorAlign () const
Return the maximum vector alignment supported for the given target.
unsigned getMaxOpenCLWorkGroupSize () const
virtual unsigned getExnObjectAlignment () const
Return the alignment (in bits) of the thrown exception object.
unsigned getIntMaxTWidth () const
Return the size of intmax_t and uintmax_t for this target, in bits.
virtual unsigned getUnwindWordWidth () const
virtual unsigned getRegisterWidth () const
Return the "preferred" register width on this target.
const char * getUserLabelPrefix () const
Returns the default value of the USER_LABEL_PREFIX macro, which is the prefix given to user symbols by default.
const char * getMCountName () const
Returns the name of the mcount instrumentation function.
bool useSignedCharForObjCBool () const
Check if the Objective-C built-in boolean type should be signed char.
void noSignedCharForObjCBool ()
bool useBitFieldTypeAlignment () const
Check whether the alignment of bit-field types is respected when laying out structures.
bool useZeroLengthBitfieldAlignment () const
Check whether zero length bitfields should force alignment of the next member.
bool useLeadingZeroLengthBitfield () const
Check whether zero length bitfield alignment is respected if they are leading members.
unsigned getZeroLengthBitfieldBoundary () const
Get the fixed alignment value in bits for a member that follows a zero length bitfield.
unsigned getMaxAlignedAttribute () const
Get the maximum alignment in bits for a static variable with aligned attribute.
bool useExplicitBitFieldAlignment () const
Check whether explicit bitfield alignment attributes should be.
bool hasAlignMac68kSupport () const
Check whether this target support '#pragma options align=mac68k'.
const char * getTypeConstantSuffix (IntType T) const
Return the constant suffix for the specified integer type enum.
bool useObjCFPRetForRealType (FloatModeKind T) const
Check whether the given real type should use the "fpret" flavor of Objective-C message passing on this target.
bool useObjCFP2RetForComplexLongDouble () const
Check whether _Complex long double should use the "fp2ret" flavor of Objective-C message passing on this target.
virtual bool useFP16ConversionIntrinsics () const
Check whether llvm intrinsics such as llvm.convert.to.fp16 should be used to convert to and from __fp16.
bool useAddressSpaceMapMangling () const
Specify if mangling based on address space map should be used or not for language specific address spaces.
virtual void getTargetDefines (const LangOptions &Opts, MacroBuilder &Builder) const =0
===-— Other target property query methods -----------------------—===//
virtual ArrayRef< Builtin::Info > getTargetBuiltins () const =0
Return information about target-specific builtins for the current primary target, and info about which builtins are non-portable across the current set of primary and secondary targets.
virtual std::optional< std::pair< unsigned, unsigned > > getVScaleRange (const LangOptions &LangOpts) const
Returns target-specific min and max values VScale_Range.
virtual bool isCLZForZeroUndef () const
The __builtin_clz* and __builtin_ctz* built-in functions are specified to have undefined results for zero inputs, but on targets that support these operations in a way that provides well-defined results for zero without loss of performance, it is a good idea to avoid optimizing based on that undef behavior.
virtual BuiltinVaListKind getBuiltinVaListKind () const =0
Returns the kind of __builtin_va_list type that should be used with this target.
bool hasBuiltinMSVaList () const
Returns whether or not type __builtin_ms_va_list type is available on this target.
bool isRenderScriptTarget () const
Returns true for RenderScript.
bool hasAArch64SVETypes () const
Returns whether or not the AArch64 SVE built-in types are available on this target.
bool hasRISCVVTypes () const
Returns whether or not the RISC-V V built-in types are available on this target.
bool allowAMDGPUUnsafeFPAtomics () const
Returns whether or not the AMDGPU unsafe floating point atomics are allowed.
uint32_t getARMCDECoprocMask () const
For ARM targets returns a mask defining which coprocessors are configured as Custom Datapath.
bool isValidClobber (StringRef Name) const
Returns whether the passed in string is a valid clobber in an inline asm statement.
virtual bool isValidGCCRegisterName (StringRef Name) const
Returns whether the passed in string is a valid register name according to GCC.
StringRef getNormalizedGCCRegisterName (StringRef Name, bool ReturnCanonical=false) const
Returns the "normalized" GCC register name.
virtual bool isSPRegName (StringRef) const
virtual StringRef getConstraintRegister (StringRef Constraint, StringRef Expression) const
Extracts a register from the passed constraint (if it is a single-register constraint) and the asm label expression related to a variable in the input or output list of an inline asm statement.
virtual bool validateGlobalRegisterVariable (StringRef RegName, unsigned RegSize, bool &HasSizeMismatch) const
Validate register name used for global register variables.
bool validateOutputConstraint (ConstraintInfo &Info) const
bool validateInputConstraint (MutableArrayRef< ConstraintInfo > OutputConstraints, ConstraintInfo &info) const
virtual bool validateOutputSize (const llvm::StringMap< bool > &FeatureMap, StringRef, unsigned) const
virtual bool validateInputSize (const llvm::StringMap< bool > &FeatureMap, StringRef, unsigned) const
virtual bool validateConstraintModifier (StringRef, char, unsigned, std::string &) const
virtual bool validateAsmConstraint (const char *&Name, TargetInfo::ConstraintInfo &info) const =0
bool resolveSymbolicName (const char *&Name, ArrayRef< ConstraintInfo > OutputConstraints, unsigned &Index) const
virtual std::string convertConstraint (const char *&Constraint) const
virtual std::optional< std::string > handleAsmEscapedChar (char C) const
Replace some escaped characters with another string based on target-specific rules.
virtual std::string_view getClobbers () const =0
Returns a string of target-specific clobbers, in LLVM format.
virtual bool isNan2008 () const
Returns true if NaN encoding is IEEE 754-2008.
const llvm::Triple & getTriple () const
Returns the target triple of the primary target.
virtual std::optional< std::string > getTargetID () const
Returns the target ID if supported.
const char * getDataLayoutString () const
virtual bool hasProtectedVisibility () const
Does this target support "protected" visibility?
virtual bool shouldDLLImportComdatSymbols () const
Does this target aim for semantic compatibility with Microsoft C++ code using dllimport/export attributes?
virtual bool hasPS4DLLImportExport () const
virtual void adjust (DiagnosticsEngine &Diags, LangOptions &Opts)
Set forced language options.
virtual void adjustTargetOptions (const CodeGenOptions &CGOpts, TargetOptions &TargetOpts) const
Adjust target options based on codegen options.
virtual bool initFeatureMap (llvm::StringMap< bool > &Features, DiagnosticsEngine &Diags, StringRef CPU, const std::vector< std::string > &FeatureVec) const
Initialize the map with the default set of target features for the CPU this should include all legal feature strings on the target.
virtual StringRef getABI () const
Get the ABI currently in use.
TargetCXXABI getCXXABI () const
Get the C++ ABI currently in use.
virtual bool setCPU (const std::string &Name)
Target the specified CPU.
virtual void fillValidCPUList (SmallVectorImpl< StringRef > &Values) const
Fill a SmallVectorImpl with the valid values to setCPU.
virtual void fillValidTuneCPUList (SmallVectorImpl< StringRef > &Values) const
Fill a SmallVectorImpl with the valid values for tuning CPU.
virtual bool isValidCPUName (StringRef Name) const
brief Determine whether this TargetInfo supports the given CPU name.
virtual bool isValidTuneCPUName (StringRef Name) const
brief Determine whether this TargetInfo supports the given CPU name for
virtual ParsedTargetAttr parseTargetAttr (StringRef Str) const
virtual bool supportsTargetAttributeTune () const
brief Determine whether this TargetInfo supports tune in target attribute.
virtual bool setABI (const std::string &Name)
Use the specified ABI.
virtual bool setFPMath (StringRef Name)
Use the specified unit for FP math.
virtual bool hasFeatureEnabled (const llvm::StringMap< bool > &Features, StringRef Name) const
Check if target has a given feature enabled.
virtual void setFeatureEnabled (llvm::StringMap< bool > &Features, StringRef Name, bool Enabled) const
Enable or disable a specific target feature; the feature name must be valid.
virtual bool isValidFeatureName (StringRef Feature) const
Determine whether this TargetInfo supports the given feature.
virtual bool doesFeatureAffectCodeGen (StringRef Feature) const
Returns true if feature has an impact on target code generation.
virtual StringRef getFeatureDependencies (StringRef Feature) const
For given feature return dependent ones.
virtual bool isBranchProtectionSupportedArch (StringRef Arch) const
Determine if the Architecture in this TargetInfo supports branch protection.
virtual bool validateBranchProtection (StringRef Spec, StringRef Arch, BranchProtectionInfo &BPI, StringRef &Err) const
Determine if this TargetInfo supports the given branch protection specification.
virtual bool handleTargetFeatures (std::vector< std::string > &Features, DiagnosticsEngine &Diags)
Perform initialization based on the user configured set of features (e.g., +sse4).
virtual bool hasFeature (StringRef Feature) const
Determine whether the given target has the given feature.
bool isReadOnlyFeature (StringRef Feature) const
Determine whether the given target feature is read only.
bool supportsMultiVersioning () const
Identify whether this target supports multiversioning of functions, which requires support for cpu_supports and cpu_is functionality.
bool supportsIFunc () const
Identify whether this target supports IFuncs.
virtual bool validateCpuSupports (StringRef Name) const
virtual unsigned multiVersionSortPriority (StringRef Name) const
virtual unsigned multiVersionFeatureCost () const
virtual bool validateCpuIs (StringRef Name) const
virtual bool validateCPUSpecificCPUDispatch (StringRef Name) const
virtual char CPUSpecificManglingCharacter (StringRef Name) const
virtual StringRef getCPUSpecificTuneName (StringRef Name) const
virtual void getCPUSpecificCPUDispatchFeatures (StringRef Name, llvm::SmallVectorImpl< StringRef > &Features) const
virtual std::optional< unsigned > getCPUCacheLineSize () const
unsigned getRegParmMax () const
bool isTLSSupported () const
Whether the target supports thread-local storage.
unsigned getMaxTLSAlign () const
Return the maximum alignment (in bits) of a TLS variable.
bool isVLASupported () const
Whether target supports variable-length arrays.
bool isSEHTrySupported () const
Whether the target supports SEH __try.
bool hasNoAsmVariants () const
Return true if {|} are normal characters in the asm string.
virtual int getEHDataRegisterNumber (unsigned RegNo) const
Return the register number that __builtin_eh_return_regno would return with the specified argument.
virtual const char * getStaticInitSectionSpecifier () const
Return the section to use for C++ static initialization functions.
const LangASMap & getAddressSpaceMap () const
unsigned getTargetAddressSpace (LangAS AS) const
virtual LangAS getOpenCLBuiltinAddressSpace (unsigned AS) const
Map from the address space field in builtin description strings to the language address space.
virtual LangAS getCUDABuiltinAddressSpace (unsigned AS) const
Map from the address space field in builtin description strings to the language address space.
virtual std::optional< LangAS > getConstantAddressSpace () const
Return an AST address space which can be used opportunistically for constant global memory.
virtual const llvm::omp::GV & getGridValue () const
StringRef getPlatformName () const
Retrieve the name of the platform as it is used in the availability attribute.
VersionTuple getPlatformMinVersion () const
Retrieve the minimum desired version of the platform, to which the program should be compiled.
bool isBigEndian () const
bool isLittleEndian () const
virtual bool supportsExtendIntArgs () const
Whether the option -fextend-arguments={32,64} is supported on the target.
virtual bool checkArithmeticFenceSupported () const
Controls if __arithmetic_fence is supported in the targeted backend.
virtual CallingConv getDefaultCallingConv () const
Gets the default calling convention for the given target and declaration context.
virtual CallingConvCheckResult checkCallingConvention (CallingConv CC) const
Determines whether a given calling convention is valid for the target.
virtual CallingConvKind getCallingConvKind (bool ClangABICompat4) const
virtual bool areDefaultedSMFStillPOD (const LangOptions &) const
Controls whether explicitly defaulted (= default) special member functions disqualify something from being POD-for-the-purposes-of-layout.
virtual bool hasSjLjLowering () const
Controls if __builtin_longjmp / __builtin_setjmp can be lowered to llvm.eh.sjlj.longjmp / llvm.eh.sjlj.setjmp.
virtual bool checkCFProtectionBranchSupported (DiagnosticsEngine &Diags) const
Check if the target supports CFProtection branch.
virtual bool checkCFProtectionReturnSupported (DiagnosticsEngine &Diags) const
Check if the target supports CFProtection return.
virtual bool allowsLargerPreferedTypeAlignment () const
Whether target allows to overalign ABI-specified preferred alignment.
virtual bool defaultsToAIXPowerAlignment () const
Whether target defaults to the power alignment rules of AIX.
virtual void setSupportedOpenCLOpts ()
Set supported OpenCL extensions and optional core features.
virtual void supportAllOpenCLOpts (bool V=true)
virtual void setCommandLineOpenCLOpts ()
Set supported OpenCL extensions as written on command line.
llvm::StringMap< bool > & getSupportedOpenCLOpts ()
Get supported OpenCL extensions and optional core features.
const llvm::StringMap< bool > & getSupportedOpenCLOpts () const
Get const supported OpenCL extensions and optional core features.
virtual LangAS getOpenCLTypeAddrSpace (OpenCLTypeKind TK) const
Get address space for OpenCL type.
virtual unsigned getVtblPtrAddressSpace () const
virtual std::optional< unsigned > getDWARFAddressSpace (unsigned AddressSpace) const
const llvm::VersionTuple & getSDKVersion () const
virtual bool validateTarget (DiagnosticsEngine &Diags) const
Check the target is valid after it is fully initialized.
virtual bool validateOpenCLTarget (const LangOptions &Opts, DiagnosticsEngine &Diags) const
Check that OpenCL target has valid options setting based on OpenCL version.
virtual void setAuxTarget (const TargetInfo *Aux)
virtual bool allowDebugInfoForExternalRef () const
Whether target allows debuginfo types for decl only variables/functions.
const llvm::Triple * getDarwinTargetVariantTriple () const
Returns the darwin target variant triple, the variant of the deployment target for which the code is being compiled.
const std::optional< VersionTuple > getDarwinTargetVariantSDKVersion () const
Returns the version of the darwin target variant SDK which was used during the compilation if one was specified, or an empty version otherwise.
virtual bool hasHIPImageSupport () const
Whether to support HIP image/texture API's.
Static Public Member Functions
static TargetInfo * CreateTargetInfo (DiagnosticsEngine &Diags, const std::shared_ptr< TargetOptions > &Opts)
Construct a target for the given options.
static IntType getCorrespondingUnsignedType (IntType T)
static bool isTypeSigned (IntType T)
Returns true if the type is signed; false otherwise.
static const char * getTypeName (IntType T)
Return the user string for the specified integer type enum.
static const char * getTypeFormatModifier (IntType T)
Return the printf format modifier for the specified integer type enum.
Protected Member Functions
TargetInfo (const llvm::Triple &T)
void resetDataLayout (StringRef DL, const char *UserLabelPrefix="")
void copyAuxTarget (const TargetInfo *Aux)
Copy type and layout related info.
virtual uint64_t getPointerWidthV (LangAS AddrSpace) const
virtual uint64_t getPointerAlignV (LangAS AddrSpace) const
virtual enum IntType getPtrDiffTypeV (LangAS AddrSpace) const
virtual ArrayRef< const char * > getGCCRegNames () const =0
virtual ArrayRef< GCCRegAlias > getGCCRegAliases () const =0
virtual ArrayRef< AddlRegName > getGCCAddlRegNames () const
Protected Attributes
bool BigEndian
bool TLSSupported
bool VLASupported
bool NoAsmVariants
bool HasLegalHalfType
bool HalfArgsAndReturns
bool HasFloat128
bool HasFloat16
bool HasBFloat16
bool HasFullBFloat16
bool HasIbm128
bool HasLongDouble
bool HasFPReturn
bool HasStrictFP
unsigned char MaxAtomicPromoteWidth
unsigned char MaxAtomicInlineWidth
std::string DataLayoutString
const char * UserLabelPrefix
const char * MCountName
unsigned char RegParmMax
unsigned char SSERegParmMax
TargetCXXABI TheCXXABI
const LangASMap * AddrSpaceMap
StringRef PlatformName
VersionTuple PlatformMinVersion
unsigned HasAlignMac68kSupport: 1
unsigned RealTypeUsesObjCFPRetMask: llvm::BitWidth<FloatModeKind>
unsigned ComplexLongDoubleUsesFP2Ret: 1
unsigned HasBuiltinMSVaList: 1
unsigned IsRenderScriptTarget: 1
unsigned HasAArch64SVETypes: 1
unsigned HasRISCVVTypes: 1
unsigned AllowAMDGPUUnsafeFPAtomics: 1
unsigned ARMCDECoprocMask: 8
unsigned MaxOpenCLWorkGroupSize
std::optional< unsigned > MaxBitIntWidth
std::optional< llvm::Triple > DarwinTargetVariantTriple
llvm::StringSet ReadOnlyFeatures
bool UseAddrSpaceMapMangling
Specify if mangling based on address space map should be used or not for language specific address spaces.
Protected Attributes inherited from clang::TransferrableTargetInfo
IntType SizeType
IntType IntMaxType
IntType PtrDiffType
IntType IntPtrType
IntType WCharType
IntType WIntType
IntType Char16Type
IntType Char32Type
IntType Int64Type
IntType Int16Type
IntType SigAtomicType
IntType ProcessIDType
unsigned UseSignedCharForObjCBool: 1
Whether Objective-C's built-in boolean type should be signed char.
unsigned UseBitFieldTypeAlignment: 1
Control whether the alignment of bit-field types is respected when laying out structures.
unsigned UseZeroLengthBitfieldAlignment: 1
Whether zero length bitfields (e.g., int : 0;) force alignment of the next bitfield.
unsigned UseLeadingZeroLengthBitfield: 1
Whether zero length bitfield alignment is respected if they are the leading members.
unsigned UseExplicitBitFieldAlignment: 1
Whether explicit bit field alignment attributes are honored.
unsigned ZeroLengthBitfieldBoundary
If non-zero, specifies a fixed alignment value for bitfields that follow zero length bitfield, regardless of the zero length bitfield type.
unsigned MaxAlignedAttribute
If non-zero, specifies a maximum alignment to truncate alignment specified in the aligned attribute of a static variable to this value.
Additional Inherited Members
Public Attributes inherited from clang::TransferrableTargetInfo
unsigned char PointerWidth
unsigned char PointerAlign
unsigned char BoolWidth
unsigned char BoolAlign
unsigned char IntWidth
unsigned char IntAlign
unsigned char HalfWidth
unsigned char HalfAlign
unsigned char BFloat16Width
unsigned char BFloat16Align
unsigned char FloatWidth
unsigned char FloatAlign
unsigned char DoubleWidth
unsigned char DoubleAlign
unsigned char LongDoubleWidth
unsigned char LongDoubleAlign
unsigned char Float128Align
unsigned char Ibm128Align
unsigned char LargeArrayMinWidth
unsigned char LargeArrayAlign
unsigned char LongWidth
unsigned char LongAlign
unsigned char LongLongWidth
unsigned char LongLongAlign
unsigned char Int128Align
unsigned char ShortAccumWidth
unsigned char ShortAccumAlign
unsigned char AccumWidth
unsigned char AccumAlign
unsigned char LongAccumWidth
unsigned char LongAccumAlign
unsigned char ShortFractWidth
unsigned char ShortFractAlign
unsigned char FractWidth
unsigned char FractAlign
unsigned char LongFractWidth
unsigned char LongFractAlign
bool PaddingOnUnsignedFixedPoint
unsigned char ShortAccumScale
unsigned char AccumScale
unsigned char LongAccumScale
unsigned char DefaultAlignForAttributeAligned
unsigned char MinGlobalAlign
unsigned short SuitableAlign
unsigned short NewAlign
unsigned MaxVectorAlign
unsigned MaxTLSAlign
const llvm::fltSemantics * HalfFormat
const llvm::fltSemantics * BFloat16Format
const llvm::fltSemantics * FloatFormat
const llvm::fltSemantics * DoubleFormat
const llvm::fltSemantics * LongDoubleFormat
const llvm::fltSemantics * Float128Format
const llvm::fltSemantics * Ibm128Format
Detailed Description
Exposes information about the current target.
Definition at line 206 of file TargetInfo.h.
Member Enumeration Documentation
BuiltinVaListKind
enum clang::TargetInfo::BuiltinVaListKind
The different kinds of __builtin_va_list types defined by the target implementation.
Enumerator
CharPtrBuiltinVaList
typedef char* __builtin_va_list;
VoidPtrBuiltinVaList
typedef void* __builtin_va_list;
AArch64ABIBuiltinVaList
__builtin_va_list as defined by the AArch64 ABI http://infocenter.arm.com/help/topic/com.arm.doc.ihi0055a/IHI0055A_aapcs64.pdf
PNaClABIBuiltinVaList
__builtin_va_list as defined by the PNaCl ABI: http://www.chromium.org/nativeclient/pnacl/bitcode-abi#TOC-Machine-Types
PowerABIBuiltinVaList
__builtin_va_list as defined by the Power ABI: https://www.power.org /resources/downloads/Power-Arch-32-bit-ABI-supp-1.0-Embedded.pdf
X86_64ABIBuiltinVaList
__builtin_va_list as defined by the x86-64 ABI: http://refspecs.linuxbase.org/elf/x86_64-abi-0.21.pdf
AAPCSABIBuiltinVaList
__builtin_va_list as defined by ARM AAPCS ABI http://infocenter.arm.com
SystemZBuiltinVaList
HexagonBuiltinVaList
Definition at line 297 of file TargetInfo.h.
CallingConvCheckResult
enum clang::TargetInfo::CallingConvCheckResult
Enumerator
CCCR_OK
CCCR_Warning
CCCR_Ignore
CCCR_Error
Definition at line 1583 of file TargetInfo.h.
CallingConvKind
enum clang::TargetInfo::CallingConvKind
Enumerator
CCK_Default
CCK_ClangABI4OrPS4
CCK_MicrosoftWin64
Definition at line 1603 of file TargetInfo.h.
Constructor & Destructor Documentation
TargetInfo()
TargetInfo::TargetInfo (const llvm::Triple & T) protected
Definition at line 54 of file TargetInfo.cpp.
References clang::TransferrableTargetInfo::AccumAlign, clang::TransferrableTargetInfo::AccumScale, clang::TransferrableTargetInfo::AccumWidth, AddrSpaceMap, AllowAMDGPUUnsafeFPAtomics, ARMCDECoprocMask, BigEndian, clang::TransferrableTargetInfo::BoolAlign, clang::TransferrableTargetInfo::BoolWidth, clang::TransferrableTargetInfo::Char16Type, clang::TransferrableTargetInfo::Char32Type, ComplexLongDoubleUsesFP2Ret, DefaultAddrSpaceMap, clang::TransferrableTargetInfo::DefaultAlignForAttributeAligned, clang::TransferrableTargetInfo::DoubleAlign, clang::TransferrableTargetInfo::DoubleFormat, clang::TransferrableTargetInfo::DoubleWidth, clang::TransferrableTargetInfo::Float128Align, clang::TransferrableTargetInfo::Float128Format, clang::TransferrableTargetInfo::FloatAlign, clang::TransferrableTargetInfo::FloatFormat, clang::TransferrableTargetInfo::FloatWidth, clang::TransferrableTargetInfo::FractAlign, clang::TransferrableTargetInfo::FractWidth, clang::TransferrableTargetInfo::HalfAlign, HalfArgsAndReturns, clang::TransferrableTargetInfo::HalfFormat, clang::TransferrableTargetInfo::HalfWidth, HasAArch64SVETypes, HasAlignMac68kSupport, HasBFloat16, HasBuiltinMSVaList, HasFloat128, HasFloat16, HasFPReturn, HasFullBFloat16, HasIbm128, HasLegalHalfType, HasLongDouble, HasRISCVVTypes, HasStrictFP, clang::TransferrableTargetInfo::Ibm128Align, clang::TransferrableTargetInfo::Ibm128Format, clang::if(), clang::TransferrableTargetInfo::Int128Align, clang::TransferrableTargetInfo::Int16Type, clang::TransferrableTargetInfo::Int64Type, clang::TransferrableTargetInfo::IntAlign, clang::TransferrableTargetInfo::IntMaxType, clang::TransferrableTargetInfo::IntPtrType, clang::TransferrableTargetInfo::IntWidth, IsRenderScriptTarget, clang::TransferrableTargetInfo::LargeArrayAlign, clang::TransferrableTargetInfo::LargeArrayMinWidth, clang::TransferrableTargetInfo::LongAccumAlign, clang::TransferrableTargetInfo::LongAccumScale, clang::TransferrableTargetInfo::LongAccumWidth, clang::TransferrableTargetInfo::LongAlign, clang::TransferrableTargetInfo::LongDoubleAlign, clang::TransferrableTargetInfo::LongDoubleFormat, clang::TransferrableTargetInfo::LongDoubleWidth, clang::TransferrableTargetInfo::LongFractAlign, clang::TransferrableTargetInfo::LongFractWidth, clang::TransferrableTargetInfo::LongLongAlign, clang::TransferrableTargetInfo::LongLongWidth, clang::TransferrableTargetInfo::LongWidth, clang::TransferrableTargetInfo::MaxAlignedAttribute, MaxAtomicInlineWidth, MaxAtomicPromoteWidth, MaxBitIntWidth, MaxOpenCLWorkGroupSize, clang::TransferrableTargetInfo::MaxTLSAlign, clang::TransferrableTargetInfo::MaxVectorAlign, MCountName, clang::TransferrableTargetInfo::MinGlobalAlign, clang::TransferrableTargetInfo::NewAlign, NoAsmVariants, clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint, PlatformMinVersion, PlatformName, clang::TransferrableTargetInfo::PointerAlign, clang::TransferrableTargetInfo::PointerWidth, clang::TransferrableTargetInfo::ProcessIDType, clang::TransferrableTargetInfo::PtrDiffType, RealTypeUsesObjCFPRetMask, RegParmMax, clang::TargetCXXABI::set(), clang::TransferrableTargetInfo::ShortAccumAlign, clang::TransferrableTargetInfo::ShortAccumScale, clang::TransferrableTargetInfo::ShortAccumWidth, clang::TransferrableTargetInfo::ShortFractAlign, clang::TransferrableTargetInfo::ShortFractWidth, clang::TransferrableTargetInfo::SigAtomicType, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, SSERegParmMax, clang::TransferrableTargetInfo::SuitableAlign, TheCXXABI, TLSSupported, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedShort, UseAddrSpaceMapMangling, clang::TransferrableTargetInfo::UseBitFieldTypeAlignment, clang::TransferrableTargetInfo::UseExplicitBitFieldAlignment, clang::TransferrableTargetInfo::UseLeadingZeroLengthBitfield, UserLabelPrefix, clang::TransferrableTargetInfo::UseSignedCharForObjCBool, clang::TransferrableTargetInfo::UseZeroLengthBitfieldAlignment, VLASupported, clang::TransferrableTargetInfo::WCharType, clang::TransferrableTargetInfo::WIntType, and clang::TransferrableTargetInfo::ZeroLengthBitfieldBoundary.
~TargetInfo()
TargetInfo::~TargetInfo () virtual
Definition at line 187 of file TargetInfo.cpp.
Member Function Documentation
adjust()
void TargetInfo::adjust (DiagnosticsEngine & Diags, LangOptions & Opts) virtual
Set forced language options.
adjust - Set forced language options.
Apply changes to the target information with respect to certain language options which change the target configuration and adjust the language based on the target options where applicable.
Reimplemented in clang::targets::AMDGPUTargetInfo, clang::targets::BaseSPIRTargetInfo, and clang::targets::PPCTargetInfo.
Definition at line 391 of file TargetInfo.cpp.
References AddrSpaceMap, checkArithmeticFenceSupported(), clang::TransferrableTargetInfo::DoubleAlign, clang::TransferrableTargetInfo::DoubleFormat, clang::TransferrableTargetInfo::DoubleWidth, FakeAddrSpaceMap, clang::TransferrableTargetInfo::FloatAlign, clang::TransferrableTargetInfo::FloatFormat, clang::TransferrableTargetInfo::FloatWidth, getCharWidth(), getMaxPointerWidth(), clang::LangOptions::getOpenCLCompatibleVersion(), getSupportedOpenCLOpts(), getTriple(), clang::TransferrableTargetInfo::HalfAlign, clang::TransferrableTargetInfo::HalfFormat, clang::TransferrableTargetInfo::HalfWidth, hasFeatureEnabled(), clang::TransferrableTargetInfo::Int64Type, clang::TransferrableTargetInfo::IntAlign, clang::TransferrableTargetInfo::IntMaxType, clang::TransferrableTargetInfo::IntPtrType, clang::TransferrableTargetInfo::IntWidth, clang::TransferrableTargetInfo::LongAlign, clang::TransferrableTargetInfo::LongDoubleAlign, clang::TransferrableTargetInfo::LongDoubleFormat, clang::TransferrableTargetInfo::LongDoubleWidth, clang::TransferrableTargetInfo::LongLongAlign, clang::TransferrableTargetInfo::LongLongWidth, clang::TransferrableTargetInfo::LongWidth, MaxBitIntWidth, clang::TransferrableTargetInfo::NewAlign, clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint, clang::TransferrableTargetInfo::PtrDiffType, clang::DiagnosticsEngine::Report(), clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedShort, clang::TransferrableTargetInfo::UseBitFieldTypeAlignment, and clang::TransferrableTargetInfo::WCharType.
Referenced by clang::targets::AMDGPUTargetInfo::adjust(), clang::targets::PPCTargetInfo::adjust(), clang::CompilerInstance::createPreprocessor(), and clang::CompilerInstance::createTarget().
adjustTargetOptions()
virtual void clang::TargetInfo::adjustTargetOptions (const CodeGenOptions & CGOpts, TargetOptions & TargetOpts) const inline virtual
Adjust target options based on codegen options.
Definition at line 1264 of file TargetInfo.h.
Referenced by clang::CompilerInstance::createTarget().
allowAMDGPUUnsafeFPAtomics()
bool clang::TargetInfo::allowAMDGPUUnsafeFPAtomics () const inline
Returns whether or not the AMDGPU unsafe floating point atomics are allowed.
Definition at line 996 of file TargetInfo.h.
References AllowAMDGPUUnsafeFPAtomics.
allowDebugInfoForExternalRef()
virtual bool clang::TargetInfo::allowDebugInfoForExternalRef () const inline virtual
Whether target allows debuginfo types for decl only variables/functions.
Reimplemented in clang::targets::BPFTargetInfo.
Definition at line 1712 of file TargetInfo.h.
Referenced by clang::Sema::ActOnUninitializedDecl().
allowHalfArgsAndReturns()
virtual bool clang::TargetInfo::allowHalfArgsAndReturns () const inline virtual
Whether half args and returns are supported.
Definition at line 652 of file TargetInfo.h.
References HalfArgsAndReturns.
Referenced by clang::Sema::BuildFunctionType(), clang::Sema::CheckFunctionReturnType(), and GetFullTypeForDeclarator().
allowsLargerPreferedTypeAlignment()
virtual bool clang::TargetInfo::allowsLargerPreferedTypeAlignment () const inline virtual
Whether target allows to overalign ABI-specified preferred alignment.
Reimplemented in clang::targets::CSKYTargetInfo, clang::targets::MCUX86_32TargetInfo, clang::targets::MSP430TargetInfo, clang::targets::VETargetInfo, and clang::targets::XCoreTargetInfo.
Definition at line 1634 of file TargetInfo.h.
areDefaultedSMFStillPOD()
bool TargetInfo::areDefaultedSMFStillPOD (const LangOptions & LangOpts) const virtual
Controls whether explicitly defaulted (= default) special member functions disqualify something from being POD-for-the-purposes-of-layout.
Historically, Clang didn't consider these acceptable for POD, but GCC does. So in newer Clang ABIs they are acceptable for POD to be compatible with GCC/Itanium ABI, and remains disqualifying for targets that need Clang backwards compatibility rather than GCC/Itanium ABI compatibility.
Reimplemented in clang::targets::AIXTargetInfo< PPC32TargetInfo >, clang::targets::AIXTargetInfo< PPC64TargetInfo >, clang::targets::DarwinTargetInfo< AArch64leTargetInfo >, clang::targets::DarwinTargetInfo< ARMleTargetInfo >, clang::targets::DarwinTargetInfo< X86_32TargetInfo >, and clang::targets::DarwinTargetInfo< X86_64TargetInfo >.
Definition at line 589 of file TargetInfo.cpp.
References clang::LangOptions::Ver15.
checkArithmeticFenceSupported()
virtual bool clang::TargetInfo::checkArithmeticFenceSupported () const inline virtual
Controls if __arithmetic_fence is supported in the targeted backend.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::SPIRTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1572 of file TargetInfo.h.
Referenced by adjust().
checkCallingConvention()
virtual CallingConvCheckResult clang::TargetInfo::checkCallingConvention (CallingConv CC) const inline virtual
Determines whether a given calling convention is valid for the target.
A calling convention can either be accepted, produce a warning and be substituted with the default calling convention, or (someday) produce an error (such as using thiscall on a non-instance function).
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::MCUX86_32TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PPC64TargetInfo, clang::targets::SystemZTargetInfo, clang::targets::VETargetInfo, clang::targets::WindowsARM64TargetInfo, clang::targets::WindowsARMTargetInfo, clang::targets::WindowsX86_64TargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1594 of file TargetInfo.h.
References clang::CC_C, CCCR_OK, and CCCR_Warning.
Referenced by clang::Sema::CheckCallingConvAttr(), and repeatForLambdaConversionFunctionCallingConvs().
checkCFProtectionBranchSupported()
bool TargetInfo::checkCFProtectionBranchSupported (DiagnosticsEngine & Diags) const virtual
Check if the target supports CFProtection branch.
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 195 of file TargetInfo.cpp.
References clang::DiagnosticsEngine::Report().
checkCFProtectionReturnSupported()
bool TargetInfo::checkCFProtectionReturnSupported (DiagnosticsEngine & Diags) const virtual
Check if the target supports CFProtection return.
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 201 of file TargetInfo.cpp.
References clang::DiagnosticsEngine::Report().
convertConstraint()
virtual std::string clang::TargetInfo::convertConstraint (const char *& Constraint) const inline virtual
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1181 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::convertConstraint(), clang::targets::LoongArchTargetInfo::convertConstraint(), and clang::targets::RISCVTargetInfo::convertConstraint().
copyAuxTarget()
void TargetInfo::copyAuxTarget (const TargetInfo * Aux) protected
Copy type and layout related info.
Definition at line 988 of file TargetInfo.cpp.
Referenced by clang::targets::AMDGPUTargetInfo::setAuxTarget().
CPUSpecificManglingCharacter()
virtual char clang::TargetInfo::CPUSpecificManglingCharacter (StringRef Name) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1447 of file TargetInfo.h.
CreateTargetInfo()
TargetInfo * TargetInfo::CreateTargetInfo (DiagnosticsEngine & Diags, const std::shared_ptr< TargetOptions > & Opts) static
Construct a target for the given options.
CreateTargetInfo - Return the target info object for the specified target options.
Parameters
Opts - The options to use to initialize the target. The target may modify the options to canonicalize the target feature information to match what the backend expects.
Definition at line 773 of file Targets.cpp.
References clang::targets::AllocateTarget(), and clang::DiagnosticsEngine::Report().
Referenced by clang::createChainedIncludesSource(), and clang::CompilerInstance::createTarget().
defaultsToAIXPowerAlignment()
virtual bool clang::TargetInfo::defaultsToAIXPowerAlignment () const inline virtual
Whether target defaults to the power alignment rules of AIX.
Reimplemented in clang::targets::AIXTargetInfo< PPC32TargetInfo >, and clang::targets::AIXTargetInfo< PPC64TargetInfo >.
Definition at line 1637 of file TargetInfo.h.
doesFeatureAffectCodeGen()
virtual bool clang::TargetInfo::doesFeatureAffectCodeGen (StringRef Feature) const inline virtual
Returns true if feature has an impact on target code generation.
Reimplemented in clang::targets::AArch64TargetInfo.
Definition at line 1351 of file TargetInfo.h.
Referenced by clang::Sema::checkTargetClonesAttrString().
doUnsignedFixedPointTypesHavePadding()
bool clang::TargetInfo::doUnsignedFixedPointTypesHavePadding () const inline
In the event this target uses the same number of fractional bits for its unsigned types as it does with its signed counterparts, there will be exactly one bit of padding.
Return true if unsigned fixed point types have padding for this target.
Definition at line 415 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
fillValidCPUList()
virtual void clang::TargetInfo::fillValidCPUList (SmallVectorImpl< StringRef > & Values) const inline virtual
Fill a SmallVectorImpl with the valid values to setCPU.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SparcV9TargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1291 of file TargetInfo.h.
Referenced by fillValidTuneCPUList().
fillValidTuneCPUList()
virtual void clang::TargetInfo::fillValidTuneCPUList (SmallVectorImpl< StringRef > & Values) const inline virtual
Fill a SmallVectorImpl with the valid values for tuning CPU.
Reimplemented in clang::targets::RISCVTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1294 of file TargetInfo.h.
References fillValidCPUList().
getABI()
virtual StringRef clang::TargetInfo::getABI () const inline virtual
Get the ABI currently in use.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::WebAssemblyTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1276 of file TargetInfo.h.
Referenced by isAAPCS().
getAccumAlign()
unsigned clang::TargetInfo::getAccumAlign () const inline
Definition at line 511 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumAlign.
getAccumIBits()
unsigned clang::TargetInfo::getAccumIBits () const inline
Definition at line 543 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumScale, and clang::TransferrableTargetInfo::AccumWidth.
Referenced by getUnsignedAccumIBits().
getAccumScale()
unsigned clang::TargetInfo::getAccumScale () const inline
getAccumScale/IBits - Return the number of fractional/integral bits in a 'signed _Accum' type.
Definition at line 542 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumScale.
getAccumWidth()
unsigned clang::TargetInfo::getAccumWidth () const inline
getAccumWidth/Align - Return the size of 'signed _Accum' and 'unsigned _Accum' for this target, in bits.
Definition at line 510 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumWidth.
getAddressSpaceMap()
const LangASMap & clang::TargetInfo::getAddressSpaceMap () const inline
Definition at line 1524 of file TargetInfo.h.
References AddrSpaceMap.
Referenced by getTargetAddressSpace().
getARMCDECoprocMask()
uint32_t clang::TargetInfo::getARMCDECoprocMask () const inline
For ARM targets returns a mask defining which coprocessors are configured as Custom Datapath.
Definition at line 1000 of file TargetInfo.h.
References ARMCDECoprocMask.
Referenced by clang::targets::ARMTargetInfo::getTargetDefines().
getBFloat16Align()
unsigned clang::TargetInfo::getBFloat16Align () const inline
Definition at line 733 of file TargetInfo.h.
References clang::TransferrableTargetInfo::BFloat16Align.
getBFloat16Format()
const llvm::fltSemantics & clang::TargetInfo::getBFloat16Format () const inline
Definition at line 734 of file TargetInfo.h.
References clang::TransferrableTargetInfo::BFloat16Format.
getBFloat16Mangling()
virtual const char * clang::TargetInfo::getBFloat16Mangling () const inline virtual
Return the mangled code of bfloat.
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::ARMTargetInfo.
Definition at line 775 of file TargetInfo.h.
getBFloat16Width()
unsigned clang::TargetInfo::getBFloat16Width () const inline
getBFloat16Width/Align/Format - Return the size/align/format of '__bf16'.
Definition at line 732 of file TargetInfo.h.
References clang::TransferrableTargetInfo::BFloat16Width.
getBoolAlign()
unsigned clang::TargetInfo::getBoolAlign () const inline
Return the alignment of '_Bool' and C++ 'bool' for this target.
Definition at line 472 of file TargetInfo.h.
References clang::TransferrableTargetInfo::BoolAlign.
getBoolWidth()
unsigned clang::TargetInfo::getBoolWidth () const inline
Return the size of '_Bool' and C++ 'bool' for this target, in bits.
Definition at line 469 of file TargetInfo.h.
References clang::TransferrableTargetInfo::BoolWidth.
Referenced by InitializePredefinedMacros().
getBuiltinVaListKind()
virtual BuiltinVaListKind clang::TargetInfo::getBuiltinVaListKind () const pure virtual
Returns the kind of __builtin_va_list type that should be used with this target.
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AIXPPC32TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DarwinAArch64TargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NaClMips32TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPC32TargetInfo, clang::targets::PPC64TargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::WindowsARM64TargetInfo, clang::targets::WindowsARMTargetInfo, clang::targets::WindowsX86_64TargetInfo, clang::targets::X86_32TargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by clang::Sema::BuildVAArgExpr().
getCallingConvKind()
TargetInfo::CallingConvKind TargetInfo::getCallingConvKind (bool ClangABICompat4) const virtual
Reimplemented in clang::targets::MicrosoftARM64TargetInfo, and clang::targets::MicrosoftX86_64TargetInfo.
Definition at line 582 of file TargetInfo.cpp.
References CCK_ClangABI4OrPS4, CCK_Default, getCXXABI(), and getTriple().
Referenced by clang::Sema::CheckCompletedCXXClass().
getChar16Align()
unsigned clang::TargetInfo::getChar16Align () const inline
Definition at line 714 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char16Type, and getTypeAlign().
getChar16Type()
IntType clang::TargetInfo::getChar16Type () const inline
Definition at line 381 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char16Type.
Referenced by InitializePredefinedMacros().
getChar16Width()
unsigned clang::TargetInfo::getChar16Width () const inline
getChar16Width/Align - Return the size of 'char16_t' for this target, in bits.
Definition at line 713 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char16Type, and getTypeWidth().
Referenced by EvaluateValue().
getChar32Align()
unsigned clang::TargetInfo::getChar32Align () const inline
Definition at line 719 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char32Type, and getTypeAlign().
getChar32Type()
IntType clang::TargetInfo::getChar32Type () const inline
Definition at line 382 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char32Type.
Referenced by InitializePredefinedMacros().
getChar32Width()
unsigned clang::TargetInfo::getChar32Width () const inline
getChar32Width/Align - Return the size of 'char32_t' for this target, in bits.
Definition at line 718 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Char32Type, and getTypeWidth().
Referenced by EvaluateValue().
getCharAlign()
unsigned clang::TargetInfo::getCharAlign () const inline
Definition at line 475 of file TargetInfo.h.
Referenced by clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), getTypeAlign(), and roundUpSizeToCharAlignment().
getCharWidth()
unsigned clang::TargetInfo::getCharWidth () const inline
Definition at line 474 of file TargetInfo.h.
Referenced by clang::Sema::ActOnEnumBody(), adjust(), clang::CharLiteralParser::CharLiteralParser(), DefineTypeSizeof(), EvaluateValue(), clang::interp::Context::getCharBit(), getIntTypeByWidth(), getLeastIntTypeByWidth(), getTypeConstantSuffix(), getTypeWidth(), hasBuiltinAtomic(), InitializePredefinedMacros(), InitializeStandardPredefinedMacros(), and parseModeAttrArg().
getClobbers()
virtual std::string_view clang::TargetInfo::getClobbers () const pure virtual
Returns a string of target-specific clobbers, in LLVM format.
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::X86TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by emitPPCLoadReserveIntrinsic(), and EmitX86BitTestIntrinsic().
getConstantAddressSpace()
virtual std::optional< LangAS > clang::TargetInfo::getConstantAddressSpace () const inline virtual
Return an AST address space which can be used opportunistically for constant global memory.
It must be possible to convert pointers into this address space to LangAS::Default. If no such address space exists, this may return std::nullopt, and such optimizations will be disabled.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1547 of file TargetInfo.h.
References clang::Default.
getConstraintRegister()
virtual StringRef clang::TargetInfo::getConstraintRegister (StringRef Constraint, StringRef Expression) const inline virtual
Extracts a register from the passed constraint (if it is a single-register constraint) and the asm label expression related to a variable in the input or output list of an inline asm statement.
This function is used by Sema in order to diagnose conflicts between the clobber list and the input/output lists.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARMTargetInfo, clang::targets::RISCVTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1030 of file TargetInfo.h.
getCorrespondingUnsignedType()
static IntType clang::TargetInfo::getCorrespondingUnsignedType (IntType T) inline static
Definition at line 394 of file TargetInfo.h.
References clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by getUInt16Type(), getUInt64Type(), getUIntMaxType(), getUIntPtrType(), and getUnsignedPtrDiffType().
getCPUCacheLineSize()
virtual std::optional< unsigned > clang::TargetInfo::getCPUCacheLineSize () const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1470 of file TargetInfo.h.
getCPUSpecificCPUDispatchFeatures()
virtual void clang::TargetInfo::getCPUSpecificCPUDispatchFeatures (StringRef Name, llvm::SmallVectorImpl< StringRef > & Features) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1462 of file TargetInfo.h.
getCPUSpecificTuneName()
virtual StringRef clang::TargetInfo::getCPUSpecificTuneName (StringRef Name) const inline virtual
Definition at line 1454 of file TargetInfo.h.
getCUDABuiltinAddressSpace()
virtual LangAS clang::TargetInfo::getCUDABuiltinAddressSpace (unsigned AS) const inline virtual
Map from the address space field in builtin description strings to the language address space.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1539 of file TargetInfo.h.
References clang::getLangASFromTargetAS().
Referenced by clang::ASTContext::getLangASForBuiltinAddressSpace().
getCXXABI()
TargetCXXABI clang::TargetInfo::getCXXABI () const inline
Get the C++ ABI currently in use.
Definition at line 1279 of file TargetInfo.h.
References TheCXXABI.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnPragmaMSSeg(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::AddInitializerToDecl(), clang::Sema::adjustMemberFunctionCC(), clang::CodeGen::CodeGenPGO::assignRegionCounters(), basicGVALinkageForFunction(), basicGVALinkageForVariable(), BuildAppleKextVirtualCall(), clang::Sema::BuildArrayType(), canEmitDelegateCallArgs(), clang::Sema::CheckAddressOfOperand(), checkAttributesAfterMerging(), clang::Sema::CheckBaseSpecifier(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckCompletedCXXClass(), clang::Sema::CheckCompleteDestructorVariant(), clang::Sema::CheckCXXThrowOperand(), checkForMultipleExportedDefaultConstructors(), computeKeyFunction(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefineUsedVTables(), clang::CodeGen::CGCXXABI::EmitCtorCompleteObjectHandler(), clang::Sema::FixOverloadedFunctionReference(), clang::ASTNameGenerator::Implementation::getAllManglings(), getCallingConvKind(), getCallingConvMangling(), getConstantArrayInfoInChars(), clang::ASTContext::getCXXABIKind(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), hasInAllocaArgs(), InitDeviceMC(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), clang::Sema::InstantiateFunctionDefinition(), clang::Type::isIncompleteType(), clang::FunctionDecl::isMSExternInline(), isMsLayout(), clang::ASTContext::isMSStaticDataMemberInlineDefinition(), isStdBuiltin(), isVarDeclStrongDefinition(), clang::CodeGen::CodeGenVTables::isVTableExternal(), clang::MangleContext::mangleName(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkFunctionReferenced(), clang::Sema::MarkVTableUsed(), clang::Sema::PerformImplicitConversion(), ReferenceDllExportedMembers(), shouldEmitVTableThunk(), TryReinterpretCast(), TryStaticMemberPointerUpcast(), and UseRelativeLayout().
getDarwinTargetVariantSDKVersion()
const std::optional< VersionTuple > clang::TargetInfo::getDarwinTargetVariantSDKVersion () const inline
Returns the version of the darwin target variant SDK which was used during the compilation if one was specified, or an empty version otherwise.
Definition at line 1722 of file TargetInfo.h.
References clang::TargetOptions::DarwinTargetVariantSDKVersion, and getTargetOpts().
getDarwinTargetVariantTriple()
const llvm::Triple * clang::TargetInfo::getDarwinTargetVariantTriple () const inline
Returns the darwin target variant triple, the variant of the deployment target for which the code is being compiled.
Definition at line 1716 of file TargetInfo.h.
References DarwinTargetVariantTriple.
Referenced by isTargetVariantEnvironment(), and isTargetVariantOS().
getDataLayoutString()
const char * clang::TargetInfo::getDataLayoutString () const inline
Definition at line 1213 of file TargetInfo.h.
References DataLayoutString.
Referenced by clang::CodeGenAction::ExecuteAction().
getDefaultAlignForAttributeAligned()
unsigned clang::TargetInfo::getDefaultAlignForAttributeAligned () const inline
Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
Definition at line 689 of file TargetInfo.h.
References clang::TransferrableTargetInfo::DefaultAlignForAttributeAligned.
Referenced by getExnObjectAlignment(), and clang::ASTContext::getTargetDefaultAlignForAttributeAligned().
getDefaultCallingConv()
virtual CallingConv clang::TargetInfo::getDefaultCallingConv () const inline virtual
Gets the default calling convention for the given target and declaration context.
Reimplemented in clang::targets::BaseSPIRTargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1576 of file TargetInfo.h.
References clang::CC_C.
getDoubleAlign()
unsigned clang::TargetInfo::getDoubleAlign () const inline
Definition at line 738 of file TargetInfo.h.
References clang::TransferrableTargetInfo::DoubleAlign.
getDoubleFormat()
const llvm::fltSemantics & clang::TargetInfo::getDoubleFormat () const inline
Definition at line 739 of file TargetInfo.h.
References clang::TransferrableTargetInfo::DoubleFormat.
Referenced by InitializePredefinedMacros().
getDoubleWidth()
unsigned clang::TargetInfo::getDoubleWidth () const inline
getDoubleWidth/Align/Format - Return the size/align/format of 'double'.
Definition at line 737 of file TargetInfo.h.
References clang::TransferrableTargetInfo::DoubleWidth.
Referenced by getRealTypeByWidth(), and InitializePredefinedMacros().
getDWARFAddressSpace()
virtual std::optional< unsigned > clang::TargetInfo::getDWARFAddressSpace (unsigned AddressSpace) const inline virtual
Returns
If a target requires an address within a target specific address space AddressSpace to be converted in order to be used, then return the corresponding target specific DWARF address space.
Otherwise return std::nullopt and no conversion will be emitted in the DWARF.
Reimplemented in clang::targets::AMDGPUTargetInfo, clang::targets::BaseSPIRTargetInfo, and clang::targets::NVPTXTargetInfo.
Definition at line 1688 of file TargetInfo.h.
getEHDataRegisterNumber()
virtual int clang::TargetInfo::getEHDataRegisterNumber (unsigned RegNo) const inline virtual
Return the register number that __builtin_eh_return_regno would return with the specified argument.
This corresponds with TargetLowering's getExceptionPointerRegister and getExceptionSelectorRegister in the backend.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARMTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::X86_32TargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::XCoreTargetInfo.
Definition at line 1515 of file TargetInfo.h.
getExnObjectAlignment()
virtual unsigned clang::TargetInfo::getExnObjectAlignment () const inline virtual
Return the alignment (in bits) of the thrown exception object.
This is only meaningful for targets that allocate C++ exceptions in a system runtime, such as those using the Itanium C++ ABI.
Reimplemented in clang::targets::DarwinTargetInfo< AArch64leTargetInfo >, clang::targets::DarwinTargetInfo< ARMleTargetInfo >, clang::targets::DarwinTargetInfo< X86_32TargetInfo >, and clang::targets::DarwinTargetInfo< X86_64TargetInfo >.
Definition at line 816 of file TargetInfo.h.
References getDefaultAlignForAttributeAligned().
getFeatureDependencies()
virtual StringRef clang::TargetInfo::getFeatureDependencies (StringRef Feature) const inline virtual
For given feature return dependent ones.
Reimplemented in clang::targets::AArch64TargetInfo.
Definition at line 1356 of file TargetInfo.h.
getFloat128Align()
unsigned clang::TargetInfo::getFloat128Align () const inline
Definition at line 752 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Float128Align.
getFloat128Format()
const llvm::fltSemantics & clang::TargetInfo::getFloat128Format () const inline
Definition at line 753 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Float128Format.
Referenced by clang::ASTContext::getFloatTypeSemantics().
getFloat128Mangling()
virtual const char * clang::TargetInfo::getFloat128Mangling () const inline virtual
Return the mangled code of __float128.
Reimplemented in clang::targets::PPCTargetInfo.
Definition at line 767 of file TargetInfo.h.
getFloat128Width()
unsigned clang::TargetInfo::getFloat128Width () const inline
getFloat128Width/Align/Format - Return the size/align/format of '__float128'.
Definition at line 751 of file TargetInfo.h.
getFloatAlign()
unsigned clang::TargetInfo::getFloatAlign () const inline
Definition at line 728 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FloatAlign.
getFloatFormat()
const llvm::fltSemantics & clang::TargetInfo::getFloatFormat () const inline
Definition at line 729 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FloatFormat.
Referenced by InitializePredefinedMacros().
getFloatWidth()
unsigned clang::TargetInfo::getFloatWidth () const inline
getFloatWidth/Align/Format - Return the size/align/format of 'float'.
Definition at line 727 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FloatWidth.
Referenced by getRealTypeByWidth(), and InitializePredefinedMacros().
getFPEvalMethod()
virtual LangOptions::FPEvalMethodKind clang::TargetInfo::getFPEvalMethod () const inline virtual
Return the value for the C99 FLT_EVAL_METHOD macro.
Reimplemented in clang::targets::AIXTargetInfo< PPC32TargetInfo >, clang::targets::AIXTargetInfo< PPC64TargetInfo >, clang::targets::NetBSDI386TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 778 of file TargetInfo.h.
References clang::LangOptions::FEM_Source.
getFractAlign()
unsigned clang::TargetInfo::getFractAlign () const inline
Definition at line 526 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FractAlign.
getFractScale()
unsigned clang::TargetInfo::getFractScale () const inline
getFractScale - Return the number of fractional bits in a 'signed _Fract' type.
Definition at line 590 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FractWidth.
Referenced by getUnsignedFractScale().
getFractWidth()
unsigned clang::TargetInfo::getFractWidth () const inline
getFractWidth/Align - Return the size of 'signed _Fract' and 'unsigned _Fract' for this target, in bits.
Definition at line 525 of file TargetInfo.h.
References clang::TransferrableTargetInfo::FractWidth.
getGCCAddlRegNames()
virtual ArrayRef< AddlRegName > clang::TargetInfo::getGCCAddlRegNames () const inline protected virtual
Reimplemented in clang::targets::AVRTargetInfo, clang::targets::PPCTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1745 of file TargetInfo.h.
Referenced by clang::targets::PPCTargetInfo::getGCCAddlRegNames(), getNormalizedGCCRegisterName(), and isValidGCCRegisterName().
getGCCRegAliases()
virtual ArrayRef< GCCRegAlias > clang::TargetInfo::getGCCRegAliases () const protected pure virtual
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::X86TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by getNormalizedGCCRegisterName(), and isValidGCCRegisterName().
getGCCRegNames()
virtual ArrayRef< const char * > clang::TargetInfo::getGCCRegNames () const protected pure virtual
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::X86TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by getNormalizedGCCRegisterName(), and isValidGCCRegisterName().
getGridValue()
virtual const llvm::omp::GV & clang::TargetInfo::getGridValue () const inline virtual
Reimplemented in clang::targets::AMDGPUTargetInfo, and clang::targets::NVPTXTargetInfo.
Definition at line 1553 of file TargetInfo.h.
Referenced by emitInterWarpCopyFunction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction(), getNVPTXLaneID(), and getNVPTXWarpID().
getHalfAlign()
unsigned clang::TargetInfo::getHalfAlign () const inline
Definition at line 723 of file TargetInfo.h.
References clang::TransferrableTargetInfo::HalfAlign.
getHalfFormat()
const llvm::fltSemantics & clang::TargetInfo::getHalfFormat () const inline
Definition at line 724 of file TargetInfo.h.
References clang::TransferrableTargetInfo::HalfFormat.
Referenced by InitializePredefinedMacros().
getHalfWidth()
unsigned clang::TargetInfo::getHalfWidth () const inline
getHalfWidth/Align/Format - Return the size/align/format of 'half'.
Definition at line 722 of file TargetInfo.h.
References clang::TransferrableTargetInfo::HalfWidth.
Referenced by getRealTypeByWidth().
getIbm128Align()
unsigned clang::TargetInfo::getIbm128Align () const inline
Definition at line 760 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Ibm128Align.
getIbm128Format()
const llvm::fltSemantics & clang::TargetInfo::getIbm128Format () const inline
Definition at line 761 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Ibm128Format.
getIbm128Mangling()
virtual const char * clang::TargetInfo::getIbm128Mangling () const inline virtual
Return the mangled code of __ibm128.
Reimplemented in clang::targets::PPCTargetInfo.
Definition at line 770 of file TargetInfo.h.
getIbm128Width()
unsigned clang::TargetInfo::getIbm128Width () const inline
getIbm128Width/Align/Format - Return the size/align/format of '__ibm128'.
Definition at line 759 of file TargetInfo.h.
getInt128Align()
unsigned clang::TargetInfo::getInt128Align () const inline
getInt128Align() - Returns the alignment of Int128.
Definition at line 501 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Int128Align.
getInt16Type()
IntType clang::TargetInfo::getInt16Type () const inline
Definition at line 387 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Int16Type.
Referenced by DefineExactWidthIntType().
getInt64Type()
IntType clang::TargetInfo::getInt64Type () const inline
Definition at line 383 of file TargetInfo.h.
References clang::TransferrableTargetInfo::Int64Type.
Referenced by DecodeTypeFromStr(), DefineExactWidthIntType(), and DefineExactWidthIntTypeSize().
getIntAlign()
unsigned clang::TargetInfo::getIntAlign () const inline
Definition at line 488 of file TargetInfo.h.
References clang::TransferrableTargetInfo::IntAlign.
Referenced by getTypeAlign().
getIntMaxTWidth()
unsigned clang::TargetInfo::getIntMaxTWidth () const inline
Return the size of intmax_t and uintmax_t for this target, in bits.
Definition at line 829 of file TargetInfo.h.
References getTypeWidth(), and clang::TransferrableTargetInfo::IntMaxType.
Referenced by clang::Sema::ActOnNumericConstant().
getIntMaxType()
IntType clang::TargetInfo::getIntMaxType () const inline
Definition at line 364 of file TargetInfo.h.
References clang::TransferrableTargetInfo::IntMaxType.
Referenced by InitializePredefinedMacros().
getIntPtrType()
IntType clang::TargetInfo::getIntPtrType () const inline
Definition at line 375 of file TargetInfo.h.
References clang::TransferrableTargetInfo::IntPtrType.
Referenced by InitializePredefinedMacros().
getIntTypeByWidth()
TargetInfo::IntType TargetInfo::getIntTypeByWidth (unsigned BitWidth, bool IsSigned) const virtual
Return integer type with specified width.
Reimplemented in clang::targets::AVRTargetInfo.
Definition at line 285 of file TargetInfo.cpp.
References getCharWidth(), getIntWidth(), getLongLongWidth(), getLongWidth(), getShortWidth(), clang::TransferrableTargetInfo::NoInt, clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DecodeTypeFromStr(), and clang::ASTContext::getIntTypeForBitwidth().
getIntWidth()
unsigned clang::TargetInfo::getIntWidth () const inline
getIntWidth/Align - Return the size of 'signed int' and 'unsigned int' for this target, in bits.
Definition at line 487 of file TargetInfo.h.
References clang::TransferrableTargetInfo::IntWidth.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnIntegerConstant(), clang::Sema::ActOnNumericConstant(), clang::Sema::BuildCXXNew(), clang::CharLiteralParser::CharLiteralParser(), clang::Sema::CheckEnumConstant(), clang::CodeGen::CodeGenModule::EmitMainVoidAlias(), EvaluateValue(), getIntTypeByWidth(), getLeastIntTypeByWidth(), clang::targets::MipsTargetInfo::getTargetDefines(), getTypeConstantSuffix(), getTypeWidth(), and InitializePredefinedMacros().
getLargeArrayAlign()
unsigned clang::TargetInfo::getLargeArrayAlign () const inline
Definition at line 787 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LargeArrayAlign.
getLargeArrayMinWidth()
unsigned clang::TargetInfo::getLargeArrayMinWidth () const inline
Definition at line 786 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LargeArrayMinWidth.
getLeastIntTypeByWidth()
TargetInfo::IntType TargetInfo::getLeastIntTypeByWidth (unsigned BitWidth, bool IsSigned) const virtual
Return the smallest integer type with at least the specified width.
Reimplemented in clang::targets::AVRTargetInfo, clang::targets::DarwinTargetInfo< AArch64leTargetInfo >, clang::targets::DarwinTargetInfo< ARMleTargetInfo >, clang::targets::DarwinTargetInfo< X86_32TargetInfo >, and clang::targets::DarwinTargetInfo< X86_64TargetInfo >.
Definition at line 300 of file TargetInfo.cpp.
References getCharWidth(), getIntWidth(), getLongLongWidth(), getLongWidth(), getShortWidth(), clang::TransferrableTargetInfo::NoInt, clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DefineFastIntType(), DefineLeastWidthIntType(), and clang::targets::DarwinTargetInfo< Target >::getLeastIntTypeByWidth().
getLongAccumAlign()
unsigned clang::TargetInfo::getLongAccumAlign () const inline
Definition at line 516 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAccumAlign.
getLongAccumIBits()
unsigned clang::TargetInfo::getLongAccumIBits () const inline
Definition at line 548 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAccumScale, and clang::TransferrableTargetInfo::LongAccumWidth.
Referenced by getUnsignedLongAccumIBits().
getLongAccumScale()
unsigned clang::TargetInfo::getLongAccumScale () const inline
getLongAccumScale/IBits - Return the number of fractional/integral bits in a 'signed long _Accum' type.
Definition at line 547 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAccumScale.
getLongAccumWidth()
unsigned clang::TargetInfo::getLongAccumWidth () const inline
getLongAccumWidth/Align - Return the size of 'signed long _Accum' and 'unsigned long _Accum' for this target, in bits.
Definition at line 515 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAccumWidth.
getLongAlign()
unsigned clang::TargetInfo::getLongAlign () const inline
Definition at line 493 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAlign.
Referenced by getTypeAlign().
getLongDoubleAlign()
unsigned clang::TargetInfo::getLongDoubleAlign () const inline
Definition at line 744 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongDoubleAlign.
getLongDoubleFormat()
const llvm::fltSemantics & clang::TargetInfo::getLongDoubleFormat () const inline
Definition at line 745 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongDoubleFormat.
Referenced by clang::Sema::BuildAtomicExpr(), clang::ento::SMTConstraintManager::canReasonAbout(), clang::ASTContext::getFloatTypeSemantics(), getRealTypeByWidth(), and InitializePredefinedMacros().
getLongDoubleMangling()
virtual const char * clang::TargetInfo::getLongDoubleMangling () const inline virtual
Return the mangled code of long double.
Reimplemented in clang::targets::PPCTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 764 of file TargetInfo.h.
getLongDoubleWidth()
unsigned clang::TargetInfo::getLongDoubleWidth () const inline
getLongDoubleWidth/Align/Format - Return the size/align/format of 'long double'.
Definition at line 743 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongDoubleWidth.
Referenced by InitializePredefinedMacros().
getLongFractAlign()
unsigned clang::TargetInfo::getLongFractAlign () const inline
Definition at line 531 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongFractAlign.
getLongFractScale()
unsigned clang::TargetInfo::getLongFractScale () const inline
getLongFractScale - Return the number of fractional bits in a 'signed long _Fract' type.
Definition at line 594 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongFractWidth.
Referenced by getUnsignedLongFractScale().
getLongFractWidth()
unsigned clang::TargetInfo::getLongFractWidth () const inline
getLongFractWidth/Align - Return the size of 'signed long _Fract' and 'unsigned long _Fract' for this target, in bits.
Definition at line 530 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongFractWidth.
getLongLongAlign()
unsigned clang::TargetInfo::getLongLongAlign () const inline
Definition at line 498 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongLongAlign.
Referenced by getTypeAlign().
getLongLongWidth()
unsigned clang::TargetInfo::getLongLongWidth () const inline
getLongLongWidth/Align - Return the size of 'signed long long' and 'unsigned long long' for this target, in bits.
Definition at line 497 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongLongWidth.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnNumericConstant(), getIntTypeByWidth(), getLeastIntTypeByWidth(), getTypeWidth(), and InitializePredefinedMacros().
getLongWidth()
unsigned clang::TargetInfo::getLongWidth () const inline
getLongWidth/Align - Return the size of 'signed long' and 'unsigned long' for this target, in bits.
Definition at line 492 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongWidth.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnNumericConstant(), DecodeTypeFromStr(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), getIntTypeByWidth(), getLeastIntTypeByWidth(), clang::targets::MipsTargetInfo::getTargetDefines(), getTypeWidth(), and InitializePredefinedMacros().
getMaxAlignedAttribute()
unsigned clang::TargetInfo::getMaxAlignedAttribute () const inline
Get the maximum alignment in bits for a static variable with aligned attribute.
Definition at line 895 of file TargetInfo.h.
References clang::TransferrableTargetInfo::MaxAlignedAttribute.
Referenced by clang::ASTContext::getDeclAlign().
getMaxAtomicInlineWidth()
unsigned clang::TargetInfo::getMaxAtomicInlineWidth () const inline
Return the maximum width lock-free atomic operation which can be inlined given the supported features of the given target.
Definition at line 794 of file TargetInfo.h.
References MaxAtomicInlineWidth.
Referenced by clang::ASTContext::AtomicUsesUnsupportedLibcall(), and hasBuiltinAtomic().
getMaxAtomicPromoteWidth()
unsigned clang::TargetInfo::getMaxAtomicPromoteWidth () const inline
Return the maximum width lock-free atomic operation which will ever be supported for the given target.
Definition at line 791 of file TargetInfo.h.
References MaxAtomicPromoteWidth.
getMaxBitIntWidth()
virtual size_t clang::TargetInfo::getMaxBitIntWidth () const inline virtual
Reimplemented in clang::targets::X86_32TargetInfo, and clang::targets::X86_64TargetInfo.
Definition at line 634 of file TargetInfo.h.
References MaxBitIntWidth.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::BuildBitIntType(), and InitializePredefinedMacros().
getMaxOpenCLWorkGroupSize()
unsigned clang::TargetInfo::getMaxOpenCLWorkGroupSize () const inline
Definition at line 811 of file TargetInfo.h.
References MaxOpenCLWorkGroupSize.
getMaxPointerWidth()
virtual uint64_t clang::TargetInfo::getMaxPointerWidth () const inline virtual
Return the maximum width of pointers on this target.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 460 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PointerWidth.
Referenced by adjust(), and clang::CodeGen::initializationPatternFor().
getMaxTLSAlign()
unsigned clang::TargetInfo::getMaxTLSAlign () const inline
Return the maximum alignment (in bits) of a TLS variable.
Gets the maximum alignment (in bits) of a TLS variable on this target. Returns zero if there is no such constraint.
Definition at line 1489 of file TargetInfo.h.
References clang::TransferrableTargetInfo::MaxTLSAlign.
Referenced by clang::Sema::AddAlignedAttr(), and clang::Sema::CheckThreadLocalForLargeAlignment().
getMaxVectorAlign()
unsigned clang::TargetInfo::getMaxVectorAlign () const inline
Return the maximum vector alignment supported for the given target.
Definition at line 809 of file TargetInfo.h.
References clang::TransferrableTargetInfo::MaxVectorAlign.
getMCountName()
const char * clang::TargetInfo::getMCountName () const inline
Returns the name of the mcount instrumentation function.
Definition at line 853 of file TargetInfo.h.
References MCountName.
getMinGlobalAlign()
virtual unsigned clang::TargetInfo::getMinGlobalAlign (uint64_t) const inline virtual
getMinGlobalAlign - Return the minimum alignment of a global variable, unless its alignment is explicitly reduced via attributes.
Reimplemented in clang::targets::CSKYTargetInfo, and clang::targets::MicrosoftARM64TargetInfo.
Definition at line 695 of file TargetInfo.h.
References clang::TransferrableTargetInfo::MinGlobalAlign.
Referenced by clang::targets::MicrosoftARM64TargetInfo::getMinGlobalAlign().
getNewAlign()
unsigned clang::TargetInfo::getNewAlign () const inline
Return the largest alignment for which a suitably-sized allocation with '::operator new(size_t)' is guaranteed to produce a correctly-aligned pointer.
Definition at line 702 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongDoubleAlign, clang::TransferrableTargetInfo::LongLongAlign, and clang::TransferrableTargetInfo::NewAlign.
Referenced by clang::Sema::BuildCXXNew(), hasNewExtendedAlignment(), and InitializeStandardPredefinedMacros().
getNormalizedGCCRegisterName()
StringRef TargetInfo::getNormalizedGCCRegisterName (StringRef Name, bool ReturnCanonical = false) const
Returns the "normalized" GCC register name.
ReturnCannonical true will return the register name without any additions such as "{}" or "%" in it's canonical form, for example: ReturnCanonical = true and Name = "rax", will return "ax".
Definition at line 673 of file TargetInfo.cpp.
References getGCCAddlRegNames(), getGCCRegAliases(), getGCCRegNames(), clang::isDigit(), isValidGCCRegisterName(), and removeGCCRegisterPrefix().
getNullPointerValue()
virtual uint64_t clang::TargetInfo::getNullPointerValue (LangAS AddrSpace) const inline virtual
Get integer value for null pointer.
Parameters
AddrSpace address space of pointee in source language.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 466 of file TargetInfo.h.
Referenced by clang::ASTContext::getTargetNullPointerValue().
getOpenCLBuiltinAddressSpace()
virtual LangAS clang::TargetInfo::getOpenCLBuiltinAddressSpace (unsigned AS) const inline virtual
Map from the address space field in builtin description strings to the language address space.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1533 of file TargetInfo.h.
References clang::getLangASFromTargetAS().
Referenced by clang::ASTContext::getLangASForBuiltinAddressSpace().
getOpenCLTypeAddrSpace()
LangAS TargetInfo::getOpenCLTypeAddrSpace (OpenCLTypeKind TK) const virtual
Get address space for OpenCL type.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 593 of file TargetInfo.cpp.
References clang::Default, clang::OCLTK_Image, clang::OCLTK_Pipe, clang::OCLTK_Sampler, clang::opencl_constant, and clang::opencl_global.
getPlatformMinVersion()
VersionTuple clang::TargetInfo::getPlatformMinVersion () const inline
Retrieve the minimum desired version of the platform, to which the program should be compiled.
Definition at line 1563 of file TargetInfo.h.
References PlatformMinVersion.
Referenced by CheckAvailability(), checkObjCMethodX86VectorTypes(), and DoEmitAvailabilityWarning().
getPlatformName()
StringRef clang::TargetInfo::getPlatformName () const inline
Retrieve the name of the platform as it is used in the availability attribute.
Definition at line 1559 of file TargetInfo.h.
References PlatformName.
Referenced by clang::Sema::ActOnObjCAvailabilityCheckExpr(), CheckAvailability(), DiagnoseObjCImplementedDeprecations(), DoEmitAvailabilityWarning(), getAttrForPlatform(), and clang::Decl::getVersionIntroduced().
getPointerAlign()
uint64_t clang::TargetInfo::getPointerAlign (LangAS AddrSpace) const inline
Definition at line 454 of file TargetInfo.h.
References clang::Default, getPointerAlignV(), and clang::TransferrableTargetInfo::PointerAlign.
Referenced by initializeForBlockHeader().
getPointerAlignV()
virtual uint64_t clang::TargetInfo::getPointerAlignV (LangAS AddrSpace) const inline protected virtual
Reimplemented in clang::targets::AMDGPUTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1737 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PointerAlign.
Referenced by getPointerAlign().
getPointerWidth()
uint64_t clang::TargetInfo::getPointerWidth (LangAS AddrSpace) const inline
Return the width of pointers on this target, for the specified address space.
Definition at line 450 of file TargetInfo.h.
References clang::Default, getPointerWidthV(), and clang::TransferrableTargetInfo::PointerWidth.
Referenced by clang::Sema::ActOnGNUNullExpr(), getConstantArrayInfoInChars(), clang::CodeGen::swiftcall::getMaximumVoluntaryIntegerSize(), GetNumNonZeroBytesInInit(), clang::targets::MipsTargetInfo::getTargetDefines(), getUnwindWordWidth(), clang::targets::MipsTargetInfo::getUnwindWordWidth(), handleMSPointerTypeQualifierAttr(), hasInt128Type(), initializeForBlockHeader(), InitializePredefinedMacros(), clang::MangleContext::mangleName(), clang::CodeGen::SwiftABIInfo::occupiesMoreThan(), and parseModeAttrArg().
getPointerWidthV()
virtual uint64_t clang::TargetInfo::getPointerWidthV (LangAS AddrSpace) const inline protected virtual
Reimplemented in clang::targets::AMDGPUTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1734 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PointerWidth.
Referenced by getPointerWidth().
getProcessIDType()
IntType clang::TargetInfo::getProcessIDType () const inline
Definition at line 392 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ProcessIDType.
getPtrDiffType()
IntType clang::TargetInfo::getPtrDiffType (LangAS AddrSpace) const inline
Definition at line 368 of file TargetInfo.h.
References clang::Default, getPtrDiffTypeV(), and clang::TransferrableTargetInfo::PtrDiffType.
Referenced by getUnsignedPtrDiffType(), and InitializePredefinedMacros().
getPtrDiffTypeV()
virtual enum IntType clang::TargetInfo::getPtrDiffTypeV (LangAS AddrSpace) const inline protected virtual
Definition at line 1740 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PtrDiffType.
Referenced by getPtrDiffType().
getRealTypeByWidth()
FloatModeKind TargetInfo::getRealTypeByWidth (unsigned BitWidth, FloatModeKind ExplicitType) const
Return floating point type with specified width.
On PPC, there are three possible types for 128-bit floating point: "PPC double-double", IEEE 754R quad precision, and "long double" (which under the covers is represented as one of those two). At this time, there is no support for an explicit "PPC double-double" type (i.e. __ibm128) so we only need to differentiate between "long double" and IEEE quad precision.
Definition at line 315 of file TargetInfo.cpp.
References clang::Double, clang::Float, clang::Float128, getDoubleWidth(), getFloatWidth(), getHalfWidth(), getLongDoubleFormat(), clang::Half, hasFloat128Type(), hasIbm128Type(), clang::Ibm128, clang::LongDouble, and clang::NoFloat.
Referenced by clang::ASTContext::getRealTypeForBitwidth().
getRegisterWidth()
virtual unsigned clang::TargetInfo::getRegisterWidth () const inline virtual
Return the "preferred" register width on this target.
Reimplemented in clang::targets::X86_64TargetInfo.
Definition at line 839 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PointerWidth.
Referenced by clang::targets::LoongArchTargetInfo::getTargetDefines(), and parseModeAttrArg().
getRegParmMax()
unsigned clang::TargetInfo::getRegParmMax () const inline
Definition at line 1475 of file TargetInfo.h.
References RegParmMax.
Referenced by clang::Sema::CheckRegparmAttr().
getSDKVersion()
const llvm::VersionTuple & clang::TargetInfo::getSDKVersion () const inline
Returns
The version of the SDK which was used during the compilation if one was specified, or an empty version otherwise.
Definition at line 1695 of file TargetInfo.h.
References getTargetOpts(), and clang::TargetOptions::SDKVersion.
Referenced by clang::Sema::getCudaConfigureFuncName().
getShortAccumAlign()
unsigned clang::TargetInfo::getShortAccumAlign () const inline
Definition at line 506 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortAccumAlign.
getShortAccumIBits()
unsigned clang::TargetInfo::getShortAccumIBits () const inline
Definition at line 536 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortAccumScale, and clang::TransferrableTargetInfo::ShortAccumWidth.
Referenced by getUnsignedShortAccumIBits().
getShortAccumScale()
unsigned clang::TargetInfo::getShortAccumScale () const inline
getShortAccumScale/IBits - Return the number of fractional/integral bits in a 'signed short _Accum' type.
Definition at line 535 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortAccumScale.
getShortAccumWidth()
unsigned clang::TargetInfo::getShortAccumWidth () const inline
getShortAccumWidth/Align - Return the size of 'signed short _Accum' and 'unsigned short _Accum' for this target, in bits.
Definition at line 505 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortAccumWidth.
getShortAlign()
unsigned clang::TargetInfo::getShortAlign () const inline
Return the alignment of 'signed short' and 'unsigned short' for this target.
Definition at line 483 of file TargetInfo.h.
Referenced by getTypeAlign().
getShortFractAlign()
unsigned clang::TargetInfo::getShortFractAlign () const inline
Definition at line 521 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortFractAlign.
getShortFractScale()
unsigned clang::TargetInfo::getShortFractScale () const inline
getShortFractScale - Return the number of fractional bits in a 'signed short _Fract' type.
Definition at line 586 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortFractWidth.
Referenced by getUnsignedShortFractScale().
getShortFractWidth()
unsigned clang::TargetInfo::getShortFractWidth () const inline
getShortFractWidth/Align - Return the size of 'signed short _Fract' and 'unsigned short _Fract' for this target, in bits.
Definition at line 520 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ShortFractWidth.
getShortWidth()
unsigned clang::TargetInfo::getShortWidth () const inline
Return the size of 'signed short' and 'unsigned short' for this target, in bits.
Definition at line 479 of file TargetInfo.h.
Referenced by clang::Sema::ActOnEnumBody(), getIntTypeByWidth(), getLeastIntTypeByWidth(), getTypeConstantSuffix(), getTypeWidth(), and InitializePredefinedMacros().
getSigAtomicType()
IntType clang::TargetInfo::getSigAtomicType () const inline
Definition at line 391 of file TargetInfo.h.
References clang::TransferrableTargetInfo::SigAtomicType.
Referenced by InitializePredefinedMacros().
getSignedSizeType()
IntType clang::TargetInfo::getSignedSizeType () const inline
Definition at line 350 of file TargetInfo.h.
References clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
getSizeType()
IntType clang::TargetInfo::getSizeType () const inline
Definition at line 349 of file TargetInfo.h.
References clang::TransferrableTargetInfo::SizeType.
Referenced by clang::Sema::ActOnNumericConstant(), InitializePredefinedMacros(), and InitializeStandardPredefinedMacros().
getStaticInitSectionSpecifier()
virtual const char * clang::TargetInfo::getStaticInitSectionSpecifier () const inline virtual
Return the section to use for C++ static initialization functions.
Reimplemented in clang::targets::DarwinTargetInfo< AArch64leTargetInfo >, clang::targets::DarwinTargetInfo< ARMleTargetInfo >, clang::targets::DarwinTargetInfo< X86_32TargetInfo >, clang::targets::DarwinTargetInfo< X86_64TargetInfo >, clang::targets::LinuxTargetInfo< X86_32TargetInfo >, clang::targets::LinuxTargetInfo< X86_64TargetInfo >, clang::targets::OHOSTargetInfo< X86_32TargetInfo >, and clang::targets::OHOSTargetInfo< X86_64TargetInfo >.
Definition at line 1520 of file TargetInfo.h.
getSuitableAlign()
unsigned clang::TargetInfo::getSuitableAlign () const inline
Return the alignment that is the largest alignment ever used for any scalar/SIMD data type on the target machine you are compiling for (including types with an extended alignment requirement).
Definition at line 685 of file TargetInfo.h.
References clang::TransferrableTargetInfo::SuitableAlign.
Referenced by InitializePredefinedMacros().
getSupportedOpenCLOpts() [1/2]
llvm::StringMap< bool > & clang::TargetInfo::getSupportedOpenCLOpts () inline
Get supported OpenCL extensions and optional core features.
Definition at line 1665 of file TargetInfo.h.
References getTargetOpts(), and clang::TargetOptions::OpenCLFeaturesMap.
Referenced by adjust(), clang::OpenCLOptions::diagnoseFeatureExtensionDifferences(), clang::OpenCLOptions::diagnoseUnsupportedFeatureDependencies(), clang::Sema::Initialize(), InitializeOpenCLFeatureTestMacros(), and validateOpenCLTarget().
getSupportedOpenCLOpts() [2/2]
const llvm::StringMap< bool > & clang::TargetInfo::getSupportedOpenCLOpts () const inline
Get const supported OpenCL extensions and optional core features.
Definition at line 1670 of file TargetInfo.h.
References getTargetOpts(), and clang::TargetOptions::OpenCLFeaturesMap.
getTargetAddressSpace()
unsigned clang::TargetInfo::getTargetAddressSpace (LangAS AS) const inline
Definition at line 1525 of file TargetInfo.h.
References getAddressSpaceMap(), clang::isTargetAddressSpace(), and clang::toTargetAddressSpace().
Referenced by clang::ASTContext::getTargetAddressSpace().
getTargetBuiltins()
virtual ArrayRef< Builtin::Info > clang::TargetInfo::getTargetBuiltins () const pure virtual
Return information about target-specific builtins for the current primary target, and info about which builtins are non-portable across the current set of primary and secondary targets.
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::X86_32TargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by clang::Builtin::Context::InitializeTarget().
getTargetDefines()
virtual void clang::TargetInfo::getTargetDefines (const LangOptions & Opts, MacroBuilder & Builder) const pure virtual
===-— Other target property query methods -----------------------—===//
Appends the target-specific #define values for this target set to the specified buffer.
Implemented in clang::targets::AArch64beTargetInfo, clang::targets::AArch64leTargetInfo, clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMbeTargetInfo, clang::targets::ARMleTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::CygwinARMTargetInfo, clang::targets::CygwinX86_32TargetInfo, clang::targets::CygwinX86_64TargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HaikuX86_32TargetInfo, clang::targets::HexagonTargetInfo, clang::targets::ItaniumWindowsARMleTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MCUX86_32TargetInfo, clang::targets::MicrosoftARM64TargetInfo, clang::targets::MicrosoftARMleTargetInfo, clang::targets::MicrosoftX86_32TargetInfo, clang::targets::MicrosoftX86_64TargetInfo, clang::targets::MinGWARMTargetInfo, clang::targets::MinGWX86_32TargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::OSTargetInfo< AArch64leTargetInfo >, clang::targets::OSTargetInfo< ARMleTargetInfo >, clang::targets::OSTargetInfo< PPC32TargetInfo >, clang::targets::OSTargetInfo< PPC64TargetInfo >, clang::targets::OSTargetInfo< X86_32TargetInfo >, clang::targets::OSTargetInfo< X86_64TargetInfo >, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RenderScript32TargetInfo, clang::targets::RenderScript64TargetInfo, clang::targets::RISCVTargetInfo, clang::targets::RTEMSX86_32TargetInfo, clang::targets::SparcTargetInfo, clang::targets::SparcV8TargetInfo, clang::targets::SparcV9TargetInfo, clang::targets::SPIR32TargetInfo, clang::targets::SPIR64TargetInfo, clang::targets::SPIRTargetInfo, clang::targets::SPIRV32TargetInfo, clang::targets::SPIRV64TargetInfo, clang::targets::SPIRVTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCELETargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::WebAssembly32TargetInfo, clang::targets::WebAssembly64TargetInfo, clang::targets::WebAssemblyTargetInfo, clang::targets::X86TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by clang::targets::ItaniumWindowsARMleTargetInfo::getTargetDefines(), clang::targets::MicrosoftARM64TargetInfo::getTargetDefines(), clang::targets::MicrosoftARMleTargetInfo::getTargetDefines(), clang::targets::MinGWARMTargetInfo::getTargetDefines(), and InitializePredefinedMacros().
getTargetID()
virtual std::optional< std::string > clang::TargetInfo::getTargetID () const inline virtual
Returns the target ID if supported.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1209 of file TargetInfo.h.
getTargetOpts()
TargetOptions & clang::TargetInfo::getTargetOpts () const inline
Retrieve the target options.
Definition at line 290 of file TargetInfo.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::CodeGen::CGHLSLRuntime::finishCodeGen(), getCudaArch(), getDarwinTargetVariantSDKVersion(), clang::ASTContext::getOpenMPDefaultSimdAlign(), getSDKVersion(), getSupportedOpenCLOpts(), getSupportedOpenCLOpts(), clang::targets::AArch64TargetInfo::getTargetDefines(), clang::targets::LoongArchTargetInfo::getTargetDefines(), clang::targets::RISCVTargetInfo::getTargetDefines(), clang::targets::X86TargetInfo::getTargetDefines(), hasInt128Type(), clang::IncrementalExecutor::IncrementalExecutor(), clang::PCHValidator::ReadTargetOptions(), and setCommandLineOpenCLOpts().
getTriple()
const llvm::Triple & clang::TargetInfo::getTriple () const inline
Returns the target triple of the primary target.
Definition at line 1204 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnTag(), clang::Sema::ActOnTagFinishDefinition(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignedAttr(), clang::Sema::AddKnownFunctionAttributes(), addLinkOptionsPostorder(), adjust(), clang::targets::AMDGPUTargetInfo::adjust(), clang::targets::PPCTargetInfo::adjust(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), AppendTargetClonesMangling(), clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), clang::ASTContext::AtomicUsesUnsupportedLibcall(), clang::Sema::BuildArrayType(), clang::Sema::BuildCXXThrow(), buildGlobalBlock(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVAArgExpr(), clang::arcmt::trans::canApplyWeak(), canPassInRegisters(), captureInLambda(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckBaseSpecifier(), CheckBuiltinTargetInSupported(), CheckBuiltinTargetNotInUnsupported(), clang::Sema::CheckCallingConvAttr(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckHLSLEntryPoint(), clang::Sema::CheckMain(), CheckMultiVersionFunction(), checkObjCMethodX86VectorTypes(), clang::Sema::CheckParameter(), clang::Sema::CheckSpecializationInstantiationRedecl(), clang::Sema::checkTargetClonesAttrString(), clang::Sema::checkTypeSupport(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckVariableDeclarationType(), checkVAStartABI(), clang::Sema::CheckVectorOperands(), clang::CodeGen::computeSPIRKernelABIInfo(), configureBlocksRuntimeObject(), clang::ExtractAPIAction::CreateASTConsumer(), clang::WrappingExtractAPIAction::CreateASTConsumer(), clang::CodeGen::CreateItaniumCXXABI(), clang::CompilerInstance::createTarget(), createTargetCodeGenInfo(), clang::targets::DarwinAArch64TargetInfo::DarwinAArch64TargetInfo(), clang::Sema::diagnoseUnavailableAlignedAllocation(), EmitBitTestIntrinsic(), clang::CodeGen::CGDebugInfo::EmitFunctionDecl(), emitGlobalDtorWithCXAAtExit(), emitIsPlatformVersionAtLeast(), EmitMSVCRTSetJmp(), clang::targets::AMDGPUTargetInfo::fillValidCPUList(), clang::targets::RISCVTargetInfo::fillValidCPUList(), clang::targets::X86TargetInfo::fillValidCPUList(), clang::targets::RISCVTargetInfo::fillValidTuneCPUList(), clang::DeclSpec::Finish(), funcHasParameterSizeMangling(), clang::CodeGen::EHPersonality::get(), clang::analyze_scanf::ScanfSpecifier::getArgType(), clang::FunctionDecl::getBuiltinID(), clang::targets::ARMTargetInfo::getBuiltinVaListKind(), getCallingConvKind(), getCallingConvMangling(), getCCForDeclaratorChunk(), getCodegenToUse(), getInstrProfSection(), clang::targets::AMDGPUTargetInfo::getTargetDefines(), clang::targets::ARMTargetInfo::getTargetDefines(), clang::targets::PPCTargetInfo::getTargetDefines(), clang::targets::RISCVTargetInfo::getTargetDefines(), clang::targets::SparcV8TargetInfo::getTargetDefines(), clang::targets::SparcV9TargetInfo::getTargetDefines(), clang::targets::X86TargetInfo::getTargetDefines(), getTypeInfoLinkage(), handleAliasAttr(), handleAnyX86InterruptAttr(), handleArmBuiltinAliasAttr(), handleAvailabilityAttr(), handleBuiltinAliasAttr(), handleHLSLNumThreadsAttr(), handleHLSLSV_DispatchThreadIDAttr(), handleHLSLSVGroupIndexAttr(), handleInterruptAttr(), handleNakedAttr(), HandleNeonVectorTypeAttr(), handlePackedAttr(), handleTargetClonesAttr(), clang::targets::RISCVTargetInfo::handleTargetFeatures(), handleTLSModelAttr(), handleWeakImportAttr(), clang::targets::LoongArchTargetInfo::hasFeature(), clang::targets::RISCVTargetInfo::hasFeature(), clang::targets::X86TargetInfo::hasFeature(), hasPS4DLLImportExport(), clang::IncrementalExecutor::IncrementalExecutor(), clang::targets::AMDGPUTargetInfo::initFeatureMap(), clang::targets::ARMTargetInfo::initFeatureMap(), clang::targets::LoongArchTargetInfo::initFeatureMap(), clang::targets::PPCTargetInfo::initFeatureMap(), clang::targets::RISCVTargetInfo::initFeatureMap(), clang::targets::X86TargetInfo::initFeatureMap(), clang::Sema::Initialize(), InitializePredefinedMacros(), InitializeStandardPredefinedMacros(), clang::Sema::InstantiateClassMembers(), isAIXLayout(), clang::CodeGen::ABIInfo::isAndroid(), isArc4RandomAvailable(), clang::targets::ARMTargetInfo::isBranchProtectionSupportedArch(), isDefaultStdCall(), clang::FunctionDecl::isMSVCRTEntryPoint(), clang::CodeGen::ABIInfo::isOHOSFamily(), isPermittedNeonBaseType(), isSEHTrySupported(), isTargetArch(), isTargetEnvironment(), isTargetOS(), isTargetVariantEnvironment(), isTargetVariantOS(), isTargetVendor(), isThreadWrapperReplaceable(), isTrivialForMSVC(), clang::targets::RISCVTargetInfo::isValidCPUName(), clang::Sema::isValidSectionSpecifier(), clang::targets::RISCVTargetInfo::isValidTuneCPUName(), clang::Sema::isValidVarArgType(), isVarDeclStrongDefinition(), IsVectorConversion(), clang::Preprocessor::processPathForFileMacro(), ReferenceDllExportedMembers(), clang::CodeGen::CodeGenModule::Release(), shouldDiagnoseAvailabilityByDefault(), shouldDLLImportComdatSymbols(), supportsIFunc(), supportsMultiVersioning(), and clang::targets::MipsTargetInfo::validateTarget().
getTypeAlign()
unsigned TargetInfo::getTypeAlign (IntType T) const
Return the alignment (in bits) of the specified integer type enum.
getTypeAlign - Return the alignment (in bits) of the specified integer type enum.
For example, SignedInt -> getIntAlign().
Definition at line 351 of file TargetInfo.cpp.
References getCharAlign(), getIntAlign(), getLongAlign(), getLongLongAlign(), getShortAlign(), clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by getChar16Align(), getChar32Align(), and getWCharAlign().
getTypeConstantSuffix()
const char * TargetInfo::getTypeConstantSuffix (IntType T) const
Return the constant suffix for the specified integer type enum.
getTypeConstantSuffix - Return the constant suffix for the specified integer type enum.
For example, SignedLong -> "L".
Definition at line 226 of file TargetInfo.cpp.
References getCharWidth(), getIntWidth(), getShortWidth(), clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DefineExactWidthIntType(), DefineTypeSize(), InitializePredefinedMacros(), and InitializeStandardPredefinedMacros().
getTypeFormatModifier()
const char * TargetInfo::getTypeFormatModifier (IntType T) static
Return the printf format modifier for the specified integer type enum.
getTypeFormatModifier - Return the printf format modifier for the specified integer type enum.
For example, SignedLong -> "l".
Definition at line 251 of file TargetInfo.cpp.
References clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DefineFmt().
getTypeName()
const char * TargetInfo::getTypeName (IntType T) static
Return the user string for the specified integer type enum.
getTypeName - Return the user string for the specified integer type enum.
For example, SignedShort -> "short".
Definition at line 208 of file TargetInfo.cpp.
References clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DefineType().
getTypeWidth()
unsigned TargetInfo::getTypeWidth (IntType T) const
Return the width (in bits) of the specified integer type enum.
getTypeWidth - Return the width (in bits) of the specified integer type enum.
For example, SignedInt -> getIntWidth().
Definition at line 269 of file TargetInfo.cpp.
References getCharWidth(), getIntWidth(), getLongLongWidth(), getLongWidth(), getShortWidth(), clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by clang::Sema::ActOnNumericConstant(), DefineExactWidthIntType(), DefineExactWidthIntTypeSize(), DefineTypeSize(), DefineTypeWidth(), getChar16Width(), getChar32Width(), getIntMaxTWidth(), getWCharWidth(), and InitializePredefinedMacros().
getUInt16Type()
IntType clang::TargetInfo::getUInt16Type () const inline
Definition at line 388 of file TargetInfo.h.
References getCorrespondingUnsignedType(), and clang::TransferrableTargetInfo::Int16Type.
Referenced by DefineExactWidthIntType().
getUInt64Type()
IntType clang::TargetInfo::getUInt64Type () const inline
Definition at line 384 of file TargetInfo.h.
References getCorrespondingUnsignedType(), and clang::TransferrableTargetInfo::Int64Type.
Referenced by DefineExactWidthIntType(), and DefineExactWidthIntTypeSize().
getUIntMaxType()
IntType clang::TargetInfo::getUIntMaxType () const inline
Definition at line 365 of file TargetInfo.h.
References getCorrespondingUnsignedType(), and clang::TransferrableTargetInfo::IntMaxType.
Referenced by InitializePredefinedMacros().
getUIntPtrType()
IntType clang::TargetInfo::getUIntPtrType () const inline
Definition at line 376 of file TargetInfo.h.
References getCorrespondingUnsignedType(), and clang::TransferrableTargetInfo::IntPtrType.
Referenced by InitializePredefinedMacros().
getUnsignedAccumIBits()
unsigned clang::TargetInfo::getUnsignedAccumIBits () const inline
Definition at line 568 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumWidth, getAccumIBits(), getUnsignedAccumScale(), and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
getUnsignedAccumScale()
unsigned clang::TargetInfo::getUnsignedAccumScale () const inline
getUnsignedAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned _Accum' type.
Definition at line 565 of file TargetInfo.h.
References clang::TransferrableTargetInfo::AccumScale, and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
Referenced by getUnsignedAccumIBits().
getUnsignedFractScale()
unsigned clang::TargetInfo::getUnsignedFractScale () const inline
getUnsignedFractScale - Return the number of fractional bits in a 'unsigned _Fract' type.
Definition at line 605 of file TargetInfo.h.
References getFractScale(), and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
getUnsignedLongAccumIBits()
unsigned clang::TargetInfo::getUnsignedLongAccumIBits () const inline
Definition at line 578 of file TargetInfo.h.
References getLongAccumIBits(), getUnsignedLongAccumScale(), clang::TransferrableTargetInfo::LongAccumWidth, and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
getUnsignedLongAccumScale()
unsigned clang::TargetInfo::getUnsignedLongAccumScale () const inline
getUnsignedLongAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned long _Accum' type.
Definition at line 575 of file TargetInfo.h.
References clang::TransferrableTargetInfo::LongAccumScale, and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
Referenced by getUnsignedLongAccumIBits().
getUnsignedLongFractScale()
unsigned clang::TargetInfo::getUnsignedLongFractScale () const inline
getUnsignedLongFractScale - Return the number of fractional bits in a 'unsigned long _Fract' type.
Definition at line 611 of file TargetInfo.h.
References getLongFractScale(), and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
getUnsignedPtrDiffType()
IntType clang::TargetInfo::getUnsignedPtrDiffType (LangAS AddrSpace) const inline
Definition at line 372 of file TargetInfo.h.
References getCorrespondingUnsignedType(), and getPtrDiffType().
getUnsignedShortAccumIBits()
unsigned clang::TargetInfo::getUnsignedShortAccumIBits () const inline
Definition at line 557 of file TargetInfo.h.
References getShortAccumIBits(), getUnsignedShortAccumScale(), clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint, and clang::TransferrableTargetInfo::ShortAccumWidth.
getUnsignedShortAccumScale()
unsigned clang::TargetInfo::getUnsignedShortAccumScale () const inline
getUnsignedShortAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned short _Accum' type.
Definition at line 554 of file TargetInfo.h.
References clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint, and clang::TransferrableTargetInfo::ShortAccumScale.
Referenced by getUnsignedShortAccumIBits().
getUnsignedShortFractScale()
unsigned clang::TargetInfo::getUnsignedShortFractScale () const inline
getUnsignedShortFractScale - Return the number of fractional bits in a 'unsigned short _Fract' type.
Definition at line 598 of file TargetInfo.h.
References getShortFractScale(), and clang::TransferrableTargetInfo::PaddingOnUnsignedFixedPoint.
getUnwindWordWidth()
virtual unsigned clang::TargetInfo::getUnwindWordWidth () const inline virtual
Reimplemented in clang::targets::MipsTargetInfo, and clang::targets::X86_64TargetInfo.
Definition at line 834 of file TargetInfo.h.
References clang::Default, and getPointerWidth().
Referenced by parseModeAttrArg().
getUserLabelPrefix()
const char * clang::TargetInfo::getUserLabelPrefix () const inline
Returns the default value of the USER_LABEL_PREFIX macro, which is the prefix given to user symbols by default.
On most platforms this is "", but it is "_" on some.
Definition at line 850 of file TargetInfo.h.
References UserLabelPrefix.
Referenced by InitializePredefinedMacros(), and clang::MangleContext::mangleName().
getVScaleRange()
virtual std::optional< std::pair< unsigned, unsigned > > clang::TargetInfo::getVScaleRange (const LangOptions & LangOpts) const inline virtual
Returns target-specific min and max values VScale_Range.
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::RISCVTargetInfo.
Definition at line 965 of file TargetInfo.h.
Referenced by getRVVTypeSize(), and HandleRISCVRVVVectorBitsTypeAttr().
getVtblPtrAddressSpace()
virtual unsigned clang::TargetInfo::getVtblPtrAddressSpace () const inline virtual
Returns
Target specific vtbl ptr address space.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1678 of file TargetInfo.h.
getWCharAlign()
unsigned clang::TargetInfo::getWCharAlign () const inline
Definition at line 709 of file TargetInfo.h.
References getTypeAlign(), and clang::TransferrableTargetInfo::WCharType.
getWCharType()
IntType clang::TargetInfo::getWCharType () const inline
Definition at line 379 of file TargetInfo.h.
References clang::TransferrableTargetInfo::WCharType.
Referenced by EvaluateValue(), and InitializePredefinedMacros().
getWCharWidth()
unsigned clang::TargetInfo::getWCharWidth () const inline
getWCharWidth/Align - Return the size of 'wchar_t' for this target, in bits.
Definition at line 708 of file TargetInfo.h.
References getTypeWidth(), and clang::TransferrableTargetInfo::WCharType.
Referenced by clang::CharLiteralParser::CharLiteralParser(), and EvaluateValue().
getWIntType()
IntType clang::TargetInfo::getWIntType () const inline
Definition at line 380 of file TargetInfo.h.
References clang::TransferrableTargetInfo::WIntType.
Referenced by InitializePredefinedMacros().
getZeroLengthBitfieldBoundary()
unsigned clang::TargetInfo::getZeroLengthBitfieldBoundary () const inline
Get the fixed alignment value in bits for a member that follows a zero length bitfield.
Definition at line 889 of file TargetInfo.h.
References clang::TransferrableTargetInfo::ZeroLengthBitfieldBoundary.
handleAsmEscapedChar()
virtual std::optional< std::string > clang::TargetInfo::handleAsmEscapedChar (char C) const inline virtual
Replace some escaped characters with another string based on target-specific rules.
Reimplemented in clang::targets::AVRTargetInfo, and clang::targets::M68kTargetInfo.
Definition at line 1190 of file TargetInfo.h.
Referenced by clang::GCCAsmStmt::AnalyzeAsmString().
handleTargetFeatures()
virtual bool clang::TargetInfo::handleTargetFeatures (std::vector< std::string > & Features, DiagnosticsEngine & Diags) inline virtual
Perform initialization based on the user configured set of features (e.g., +sse4).
The list is guaranteed to have at most one entry per feature.
The target may modify the features list, to change which options are passed onwards to the backend. FIXME: This part should be fixed so that we can change handleTargetFeatures to merely a TargetInfo initialization routine.
Returns
False on error.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DarwinI386TargetInfo, clang::targets::DarwinX86_64TargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1394 of file TargetInfo.h.
hasAArch64SVETypes()
bool clang::TargetInfo::hasAArch64SVETypes () const inline
Returns whether or not the AArch64 SVE built-in types are available on this target.
Definition at line 988 of file TargetInfo.h.
References HasAArch64SVETypes.
Referenced by clang::Sema::Initialize().
hasAlignMac68kSupport()
bool clang::TargetInfo::hasAlignMac68kSupport () const inline
Check whether this target support '#pragma options align=mac68k'.
Definition at line 904 of file TargetInfo.h.
References HasAlignMac68kSupport.
Referenced by clang::Sema::ActOnPragmaOptionsAlign().
hasBFloat16Type()
virtual bool clang::TargetInfo::hasBFloat16Type () const inline virtual
Determine whether the _BFloat16 type is supported on this target.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, and clang::targets::NVPTXTargetInfo.
Definition at line 661 of file TargetInfo.h.
References HasBFloat16, and HasFullBFloat16.
Referenced by clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), and clang::QualType::UseExcessPrecision().
hasBitIntType()
virtual bool clang::TargetInfo::hasBitIntType () const inline virtual
Determine whether the _BitInt type is supported on this target.
This limitation is put into place for ABI reasons. FIXME: _BitInt is a required type in C23, so there's not much utility in asking whether the target supported it or not; I think this should be removed once backends have been alerted to the type and have had the chance to do implementation work if needed.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcV8TargetInfo, clang::targets::SparcV9TargetInfo, clang::targets::SystemZTargetInfo, clang::targets::X86_32TargetInfo, clang::targets::X86_64TargetInfo, and clang::targets::XCoreTargetInfo.
Definition at line 628 of file TargetInfo.h.
Referenced by clang::Sema::checkTypeSupport(), and ConvertDeclSpecToType().
hasBuiltinAtomic()
virtual bool clang::TargetInfo::hasBuiltinAtomic (uint64_t AtomicSizeInBits, uint64_t AlignmentInBits) const inline virtual
Returns true if the given target supports lock-free atomic operations at the specified width and alignment.
Definition at line 800 of file TargetInfo.h.
References getCharWidth(), and getMaxAtomicInlineWidth().
Referenced by emitOMPAtomicRMW(), and getLockFreeValue().
hasBuiltinMSVaList()
bool clang::TargetInfo::hasBuiltinMSVaList () const inline
Returns whether or not type __builtin_ms_va_list type is available on this target.
Definition at line 981 of file TargetInfo.h.
References HasBuiltinMSVaList.
Referenced by clang::Sema::BuildVAArgExpr(), and clang::Sema::Initialize().
hasFeature()
virtual bool clang::TargetInfo::hasFeature (StringRef Feature) const inline virtual
Determine whether the given target has the given feature.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARMTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SPIRTargetInfo, clang::targets::SPIRVTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1400 of file TargetInfo.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::BuildResolvedCallExpr(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::DeclSpec::Finish(), getCudaArch(), HandleArmSveVectorBitsTypeAttr(), HandleNeonVectorTypeAttr(), HandleRISCVRVVVectorBitsTypeAttr(), handleTargetClonesAttr(), clang::Sema::Initialize(), and clang::CodeGen::CodeGenModule::Release().
hasFeatureEnabled()
virtual bool clang::TargetInfo::hasFeatureEnabled (const llvm::StringMap< bool > & Features, StringRef Name) const inline virtual
Check if target has a given feature enabled.
Definition at line 1331 of file TargetInfo.h.
Referenced by adjust(), clang::OpenCLOptions::diagnoseFeatureExtensionDifferences(), clang::OpenCLOptions::diagnoseUnsupportedFeatureDependencies(), InitializeOpenCLFeatureTestMacros(), validateOpenCLTarget(), and clang::targets::X86TargetInfo::validateOperandSize().
hasFloat128Type()
virtual bool clang::TargetInfo::hasFloat128Type () const inline virtual
Determine whether the __float128 type is supported on this target.
Definition at line 655 of file TargetInfo.h.
References HasFloat128.
Referenced by clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), getRealTypeByWidth(), and clang::targets::AMDGPUTargetInfo::setAuxTarget().
hasFloat16Type()
virtual bool clang::TargetInfo::hasFloat16Type () const inline virtual
Determine whether the _Float16 type is supported on this target.
Definition at line 658 of file TargetInfo.h.
References HasFloat16.
Referenced by clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), InitializePredefinedMacros(), and clang::QualType::UseExcessPrecision().
hasFPReturn()
virtual bool clang::TargetInfo::hasFPReturn () const inline virtual
Determine whether return of a floating point value is supported on this target.
Definition at line 677 of file TargetInfo.h.
References HasFPReturn.
Referenced by clang::Sema::checkTypeSupport().
hasFullBFloat16Type()
virtual bool clang::TargetInfo::hasFullBFloat16Type () const inline virtual
Determine whether the BFloat type is fully supported on this target, i.e arithemtic operations.
Definition at line 667 of file TargetInfo.h.
References HasFullBFloat16.
Referenced by clang::QualType::UseExcessPrecision().
hasHIPImageSupport()
virtual bool clang::TargetInfo::hasHIPImageSupport () const inline virtual
Whether to support HIP image/texture API's.
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1729 of file TargetInfo.h.
Referenced by InitializeStandardPredefinedMacros().
hasIbm128Type()
virtual bool clang::TargetInfo::hasIbm128Type () const inline virtual
Determine whether the __ibm128 type is supported on this target.
Definition at line 670 of file TargetInfo.h.
References HasIbm128.
Referenced by clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), and getRealTypeByWidth().
hasInt128Type()
virtual bool clang::TargetInfo::hasInt128Type () const inline virtual
Determine whether the __int128 type is supported on this target.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::MipsTargetInfo, and clang::targets::X86_64TargetInfo.
Definition at line 617 of file TargetInfo.h.
References clang::Default, clang::TargetOptions::ForceEnableInt128, getPointerWidth(), and getTargetOpts().
Referenced by ChangeIntegralSignedness(), clang::Sema::checkTypeSupport(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), ConvertDeclSpecToType(), clang::Sema::Initialize(), InitializePredefinedMacros(), and clang::CodeGen::swiftcall::isLegalIntegerType().
hasLegalHalfType()
virtual bool clang::TargetInfo::hasLegalHalfType () const inline virtual
Determine whether _Float16 is supported on this target.
Definition at line 649 of file TargetInfo.h.
References HasLegalHalfType.
Referenced by clang::QualType::UseExcessPrecision().
hasLongDoubleType()
virtual bool clang::TargetInfo::hasLongDoubleType () const inline virtual
Determine whether the long double type is supported on this target.
Definition at line 673 of file TargetInfo.h.
References HasLongDouble.
Referenced by clang::Sema::checkTypeSupport().
hasNoAsmVariants()
bool clang::TargetInfo::hasNoAsmVariants () const inline
Return true if {|} are normal characters in the asm string.
If this returns false (the default), then {abc|xyz} is syntax that says that when compiling for asm variant #0, "abc" should be generated, but when compiling for asm variant #1, "xyz" should be generated.
Definition at line 1507 of file TargetInfo.h.
References NoAsmVariants.
hasProtectedVisibility()
virtual bool clang::TargetInfo::hasProtectedVisibility () const inline virtual
Does this target support "protected" visibility?
Any target which dynamic libraries will naturally support something like "default" (meaning that the symbol is visible outside this shared object) and "hidden" (meaning that it isn't) visibilities, but "protected" is really an ELF-specific concept with weird semantics designed around the convenience of dynamic linker implementations. Which is not to suggest that there's consistent target-independent semantics for "default" visibility either; the entire thing is pretty badly mangled.
Reimplemented in clang::targets::DarwinTargetInfo< AArch64leTargetInfo >, clang::targets::DarwinTargetInfo< ARMleTargetInfo >, clang::targets::DarwinTargetInfo< X86_32TargetInfo >, clang::targets::DarwinTargetInfo< X86_64TargetInfo >, and clang::targets::Le64TargetInfo.
Definition at line 1238 of file TargetInfo.h.
Referenced by handleVisibilityAttr().
hasPS4DLLImportExport()
virtual bool clang::TargetInfo::hasPS4DLLImportExport () const inline virtual
Definition at line 1248 of file TargetInfo.h.
References getTriple().
Referenced by computeKeyFunction(), and ShouldUseExternalRTTIDescriptor().
hasRISCVVTypes()
bool clang::TargetInfo::hasRISCVVTypes () const inline
Returns whether or not the RISC-V V built-in types are available on this target.
Definition at line 992 of file TargetInfo.h.
References HasRISCVVTypes.
Referenced by clang::Sema::Initialize().
hasSjLjLowering()
virtual bool clang::TargetInfo::hasSjLjLowering () const inline virtual
Controls if __builtin_longjmp / __builtin_setjmp can be lowered to llvm.eh.sjlj.longjmp / llvm.eh.sjlj.setjmp.
Reimplemented in clang::targets::ARMTargetInfo, clang::targets::PPCTargetInfo, clang::targets::VETargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1621 of file TargetInfo.h.
hasStrictFP()
virtual bool clang::TargetInfo::hasStrictFP () const inline virtual
Determine whether constrained floating point is supported on this target.
Definition at line 680 of file TargetInfo.h.
References HasStrictFP.
initFeatureMap()
bool TargetInfo::initFeatureMap (llvm::StringMap< bool > & Features, DiagnosticsEngine & Diags, StringRef CPU, const std::vector< std::string > & FeatureVec) const virtual
Initialize the map with the default set of target features for the CPU this should include all legal feature strings on the target.
Returns
False on error (invalid features).
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 521 of file TargetInfo.cpp.
References clang::DiagnosticsEngine::Report(), and setFeatureEnabled().
Referenced by clang::targets::AArch64TargetInfo::initFeatureMap(), clang::targets::AMDGPUTargetInfo::initFeatureMap(), clang::targets::ARMTargetInfo::initFeatureMap(), clang::targets::HexagonTargetInfo::initFeatureMap(), clang::targets::LoongArchTargetInfo::initFeatureMap(), clang::targets::PPCTargetInfo::initFeatureMap(), clang::targets::RISCVTargetInfo::initFeatureMap(), and clang::targets::X86TargetInfo::initFeatureMap().
isBigEndian()
bool clang::TargetInfo::isBigEndian () const inline
Definition at line 1565 of file TargetInfo.h.
References BigEndian.
Referenced by ARMMVEVectorReinterpret(), EmitSignBit(), EvalAndBitcastToAPInt(), and InitializePredefinedMacros().
isBranchProtectionSupportedArch()
virtual bool clang::TargetInfo::isBranchProtectionSupportedArch (StringRef Arch) const inline virtual
Determine if the Architecture in this TargetInfo supports branch protection.
Reimplemented in clang::targets::ARMTargetInfo.
Definition at line 1370 of file TargetInfo.h.
isCLZForZeroUndef()
virtual bool clang::TargetInfo::isCLZForZeroUndef () const inline virtual
The __builtin_clz* and __builtin_ctz* built-in functions are specified to have undefined results for zero inputs, but on targets that support these operations in a way that provides well-defined results for zero without loss of performance, it is a good idea to avoid optimizing based on that undef behavior.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::MipsTargetInfo, and clang::targets::PPCTargetInfo.
Definition at line 973 of file TargetInfo.h.
isLittleEndian()
bool clang::TargetInfo::isLittleEndian () const inline
Definition at line 1566 of file TargetInfo.h.
References BigEndian.
Referenced by InitializeStandardPredefinedMacros().
isNan2008()
virtual bool clang::TargetInfo::isNan2008 () const inline virtual
Returns true if NaN encoding is IEEE 754-2008.
Only MIPS allows a different encoding.
Reimplemented in clang::targets::MipsTargetInfo.
Definition at line 1199 of file TargetInfo.h.
Referenced by TryEvaluateBuiltinNaN().
isReadOnlyFeature()
bool clang::TargetInfo::isReadOnlyFeature (StringRef Feature) const inline
Determine whether the given target feature is read only.
Definition at line 1405 of file TargetInfo.h.
References ReadOnlyFeatures.
isRenderScriptTarget()
bool clang::TargetInfo::isRenderScriptTarget () const inline
Returns true for RenderScript.
Definition at line 984 of file TargetInfo.h.
References IsRenderScriptTarget.
isSEHTrySupported()
bool clang::TargetInfo::isSEHTrySupported () const inline
Whether the target supports SEH __try.
Definition at line 1495 of file TargetInfo.h.
References getTriple().
Referenced by clang::Sema::ActOnSEHTryBlock().
isSPRegName()
virtual bool clang::TargetInfo::isSPRegName (StringRef) const inline virtual
Reimplemented in clang::targets::PPCTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1022 of file TargetInfo.h.
isTLSSupported()
bool clang::TargetInfo::isTLSSupported () const inline
Whether the target supports thread-local storage.
Definition at line 1481 of file TargetInfo.h.
References TLSSupported.
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::Sema::DiagnoseUseOfDecl(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), clang::CodeGen::CGOpenMPRuntime::getOrCreateThreadPrivateCache(), and handleDeclspecThreadAttr().
isTypeSigned()
bool TargetInfo::isTypeSigned (IntType T) static
Returns true if the type is signed; false otherwise.
isTypeSigned - Return whether an integer types is signed.
Returns true if the type is signed; false otherwise.
Definition at line 369 of file TargetInfo.cpp.
References clang::TransferrableTargetInfo::SignedChar, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SignedLongLong, clang::TransferrableTargetInfo::SignedShort, clang::TransferrableTargetInfo::UnsignedChar, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TransferrableTargetInfo::UnsignedLongLong, and clang::TransferrableTargetInfo::UnsignedShort.
Referenced by DefineExactWidthIntType(), DefineExactWidthIntTypeSize(), DefineFmt(), DefineTypeSize(), EvaluateValue(), clang::ASTContext::InitBuiltinTypes(), and InitializePredefinedMacros().
isValidClobber()
bool TargetInfo::isValidClobber (StringRef Name) const
Returns whether the passed in string is a valid clobber in an inline asm statement.
isValidClobber - Returns whether the passed in string is a valid clobber in an inline asm statement.
This is used by Sema.
Definition at line 620 of file TargetInfo.cpp.
References isValidGCCRegisterName().
Referenced by clang::Sema::ActOnGCCAsmStmt().
isValidCPUName()
virtual bool clang::TargetInfo::isValidCPUName (StringRef Name) const inline virtual
brief Determine whether this TargetInfo supports the given CPU name.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::MipsTargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SparcV9TargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1299 of file TargetInfo.h.
Referenced by clang::Sema::checkTargetAttr(), clang::Sema::checkTargetClonesAttrString(), and isValidTuneCPUName().
isValidFeatureName()
virtual bool clang::TargetInfo::isValidFeatureName (StringRef Feature) const inline virtual
Determine whether this TargetInfo supports the given feature.
Reimplemented in clang::targets::ARMTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1345 of file TargetInfo.h.
Referenced by CheckMultiVersionValue(), clang::Sema::checkTargetAttr(), and clang::Sema::checkTargetClonesAttrString().
isValidGCCRegisterName()
bool TargetInfo::isValidGCCRegisterName (StringRef Name) const virtual
Returns whether the passed in string is a valid register name according to GCC.
isValidGCCRegisterName - Returns whether the passed in string is a valid register name according to GCC.
This is used by Sema for inline asm statements.
Reimplemented in clang::targets::BPFTargetInfo.
Definition at line 628 of file TargetInfo.cpp.
References getGCCAddlRegNames(), getGCCRegAliases(), getGCCRegNames(), clang::isDigit(), and removeGCCRegisterPrefix().
Referenced by clang::Sema::ActOnVariableDeclarator(), getNormalizedGCCRegisterName(), and isValidClobber().
isValidTuneCPUName()
virtual bool clang::TargetInfo::isValidTuneCPUName (StringRef Name) const inline virtual
brief Determine whether this TargetInfo supports the given CPU name for
Reimplemented in clang::targets::RISCVTargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1305 of file TargetInfo.h.
References isValidCPUName().
isVLASupported()
bool clang::TargetInfo::isVLASupported () const inline
Whether target supports variable-length arrays.
Definition at line 1492 of file TargetInfo.h.
References VLASupported.
Referenced by actOnOMPReductionKindClause(), and clang::Sema::BuildArrayType().
multiVersionFeatureCost()
virtual unsigned clang::TargetInfo::multiVersionFeatureCost () const inline virtual
Reimplemented in clang::targets::AArch64TargetInfo.
Definition at line 1434 of file TargetInfo.h.
Referenced by TargetMVPriority().
multiVersionSortPriority()
virtual unsigned clang::TargetInfo::multiVersionSortPriority (StringRef Name) const inline virtual
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1428 of file TargetInfo.h.
Referenced by AppendTargetClonesMangling(), AppendTargetVersionMangling(), and TargetMVPriority().
noSignedCharForObjCBool()
void clang::TargetInfo::noSignedCharForObjCBool () inline
Definition at line 865 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseSignedCharForObjCBool.
Referenced by clang::CompilerInstance::ExecuteAction().
parseTargetAttr()
ParsedTargetAttr TargetInfo::parseTargetAttr (StringRef Str) const virtual
Reimplemented in clang::targets::AArch64TargetInfo.
Definition at line 537 of file TargetInfo.cpp.
Referenced by CheckMultiVersionAdditionalDecl(), CheckMultiVersionValue(), clang::Sema::checkTargetAttr(), and CheckTargetCausesMultiVersioning().
resetDataLayout()
void TargetInfo::resetDataLayout (StringRef DL, const char * UserLabelPrefix = "") protected
Definition at line 189 of file TargetInfo.cpp.
References DataLayoutString, and UserLabelPrefix.
Referenced by clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), clang::targets::CygwinARMTargetInfo::CygwinARMTargetInfo(), clang::targets::M68kTargetInfo::M68kTargetInfo(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), and clang::targets::WindowsARM64TargetInfo::setDataLayout().
resolveSymbolicName()
bool TargetInfo::resolveSymbolicName (const char *& Name, ArrayRef< ConstraintInfo > OutputConstraints, unsigned & Index) const
Definition at line 788 of file TargetInfo.cpp.
References getName().
Referenced by validateInputConstraint().
setABI()
virtual bool clang::TargetInfo::setABI (const std::string & Name) inline virtual
Use the specified ABI.
Returns
False on error (invalid ABI name).
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::ARMTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::LoongArch32TargetInfo, clang::targets::LoongArch64TargetInfo, clang::targets::MipsTargetInfo, clang::targets::PPC64TargetInfo, clang::targets::RISCV32TargetInfo, clang::targets::RISCV64TargetInfo, and clang::targets::WebAssemblyTargetInfo.
Definition at line 1319 of file TargetInfo.h.
setAuxTarget()
virtual void clang::TargetInfo::setAuxTarget (const TargetInfo * Aux) inline virtual
Reimplemented in clang::targets::AMDGPUTargetInfo.
Definition at line 1709 of file TargetInfo.h.
Referenced by clang::CompilerInstance::createTarget().
setCommandLineOpenCLOpts()
virtual void clang::TargetInfo::setCommandLineOpenCLOpts () inline virtual
Set supported OpenCL extensions as written on command line.
Definition at line 1649 of file TargetInfo.h.
References getTargetOpts(), clang::TargetOptions::OpenCLFeaturesMap, supportAllOpenCLOpts(), and V.
setCPU()
virtual bool clang::TargetInfo::setCPU (const std::string & Name) inline virtual
Target the specified CPU.
Returns
False on error (invalid CPU name).
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SparcV9TargetInfo, clang::targets::SystemZTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1286 of file TargetInfo.h.
setFeatureEnabled()
virtual void clang::TargetInfo::setFeatureEnabled (llvm::StringMap< bool > & Features, StringRef Name, bool Enabled) const inline virtual
Enable or disable a specific target feature; the feature name must be valid.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::BPFTargetInfo, clang::targets::PPCTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1338 of file TargetInfo.h.
Referenced by initFeatureMap().
setFPMath()
virtual bool clang::TargetInfo::setFPMath (StringRef Name) inline virtual
Use the specified unit for FP math.
Returns
False on error (invalid unit name).
Reimplemented in clang::targets::ARMTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1326 of file TargetInfo.h.
setMaxAtomicWidth()
virtual void clang::TargetInfo::setMaxAtomicWidth () inline virtual
Set the maximum inline or promote width lock-free atomic operation for the given target.
Reimplemented in clang::targets::LoongArch32TargetInfo, clang::targets::LoongArch64TargetInfo, clang::targets::PPC64TargetInfo, clang::targets::RISCV32TargetInfo, clang::targets::RISCV64TargetInfo, clang::targets::X86_32TargetInfo, and clang::targets::X86_64TargetInfo.
Definition at line 797 of file TargetInfo.h.
setSupportedOpenCLOpts()
virtual void clang::TargetInfo::setSupportedOpenCLOpts () inline virtual
Set supported OpenCL extensions and optional core features.
Reimplemented in clang::targets::AMDGPUTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::NVPTXTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1640 of file TargetInfo.h.
shouldDLLImportComdatSymbols()
virtual bool clang::TargetInfo::shouldDLLImportComdatSymbols () const inline virtual
Does this target aim for semantic compatibility with Microsoft C++ code using dllimport/export attributes?
Definition at line 1242 of file TargetInfo.h.
References getTriple().
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::checkClassLevelDLLAttribute(), checkDLLAttributeRedeclaration(), and handleDLLAttr().
supportAllOpenCLOpts()
virtual void clang::TargetInfo::supportAllOpenCLOpts (bool V = true) inline virtual
Definition at line 1642 of file TargetInfo.h.
Referenced by setCommandLineOpenCLOpts().
supportsExtendIntArgs()
virtual bool clang::TargetInfo::supportsExtendIntArgs () const inline virtual
Whether the option -fextend-arguments={32,64} is supported on the target.
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1569 of file TargetInfo.h.
Referenced by clang::Sema::DefaultArgumentPromotion().
supportsIFunc()
bool clang::TargetInfo::supportsIFunc () const inline
Identify whether this target supports IFuncs.
Definition at line 1416 of file TargetInfo.h.
References getTriple().
Referenced by AppendCPUSpecificCPUDispatchMangling().
supportsMultiVersioning()
bool clang::TargetInfo::supportsMultiVersioning () const inline
Identify whether this target supports multiversioning of functions, which requires support for cpu_supports and cpu_is functionality.
Definition at line 1411 of file TargetInfo.h.
References getTriple().
Referenced by CheckMultiVersionAdditionalRules().
supportSourceEvalMethod()
virtual bool clang::TargetInfo::supportSourceEvalMethod () const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 782 of file TargetInfo.h.
supportsTargetAttributeTune()
virtual bool clang::TargetInfo::supportsTargetAttributeTune () const inline virtual
brief Determine whether this TargetInfo supports tune in target attribute.
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1312 of file TargetInfo.h.
Referenced by clang::Sema::checkTargetAttr().
useAddressSpaceMapMangling()
bool clang::TargetInfo::useAddressSpaceMapMangling () const inline
Specify if mangling based on address space map should be used or not for language specific address spaces.
Definition at line 946 of file TargetInfo.h.
References UseAddrSpaceMapMangling.
Referenced by isAddrSpaceMapManglingEnabled().
useBitFieldTypeAlignment()
bool clang::TargetInfo::useBitFieldTypeAlignment () const inline
Check whether the alignment of bit-field types is respected when laying out structures.
Definition at line 871 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseBitFieldTypeAlignment.
useExplicitBitFieldAlignment()
bool clang::TargetInfo::useExplicitBitFieldAlignment () const inline
Check whether explicit bitfield alignment attributes should be.
Definition at line 899 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseExplicitBitFieldAlignment.
useFP16ConversionIntrinsics()
virtual bool clang::TargetInfo::useFP16ConversionIntrinsics () const inline virtual
Check whether llvm intrinsics such as llvm.convert.to.fp16 should be used to convert to and from __fp16.
FIXME: This function should be removed once all targets stop using the conversion intrinsics.
Reimplemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARMTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::RISCVTargetInfo, and clang::targets::X86TargetInfo.
Definition at line 940 of file TargetInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::ConvertType(), needsConversionOfHalfVec(), and clang::CodeGen::ConstantEmitter::tryEmitPrivate().
useLeadingZeroLengthBitfield()
bool clang::TargetInfo::useLeadingZeroLengthBitfield () const inline
Check whether zero length bitfield alignment is respected if they are leading members.
Definition at line 883 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseLeadingZeroLengthBitfield.
useObjCFP2RetForComplexLongDouble()
bool clang::TargetInfo::useObjCFP2RetForComplexLongDouble () const inline
Check whether _Complex long double should use the "fp2ret" flavor of Objective-C message passing on this target.
Definition at line 932 of file TargetInfo.h.
References ComplexLongDoubleUsesFP2Ret.
useObjCFPRetForRealType()
bool clang::TargetInfo::useObjCFPRetForRealType (FloatModeKind T) const inline
Check whether the given real type should use the "fpret" flavor of Objective-C message passing on this target.
Definition at line 926 of file TargetInfo.h.
References RealTypeUsesObjCFPRetMask.
useSignedCharForObjCBool()
bool clang::TargetInfo::useSignedCharForObjCBool () const inline
Check if the Objective-C built-in boolean type should be signed char.
Otherwise, if this returns false, the normal built-in boolean type should also be used for Objective-C.
Definition at line 862 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseSignedCharForObjCBool.
Referenced by InitializePredefinedMacros().
useZeroLengthBitfieldAlignment()
bool clang::TargetInfo::useZeroLengthBitfieldAlignment () const inline
Check whether zero length bitfields should force alignment of the next member.
Definition at line 877 of file TargetInfo.h.
References clang::TransferrableTargetInfo::UseZeroLengthBitfieldAlignment.
validateAsmConstraint()
virtual bool clang::TargetInfo::validateAsmConstraint (const char *& Name, TargetInfo::ConstraintInfo & info) const pure virtual
Implemented in clang::targets::AArch64TargetInfo, clang::targets::AMDGPUTargetInfo, clang::targets::ARCTargetInfo, clang::targets::ARMTargetInfo, clang::targets::AVRTargetInfo, clang::targets::BaseSPIRTargetInfo, clang::targets::BPFTargetInfo, clang::targets::CSKYTargetInfo, clang::targets::DirectXTargetInfo, clang::targets::HexagonTargetInfo, clang::targets::LanaiTargetInfo, clang::targets::Le64TargetInfo, clang::targets::LoongArchTargetInfo, clang::targets::M68kTargetInfo, clang::targets::MipsTargetInfo, clang::targets::MSP430TargetInfo, clang::targets::NVPTXTargetInfo, clang::targets::PNaClTargetInfo, clang::targets::PPCTargetInfo, clang::targets::RISCVTargetInfo, clang::targets::SparcTargetInfo, clang::targets::SystemZTargetInfo, clang::targets::TCETargetInfo, clang::targets::VETargetInfo, clang::targets::X86TargetInfo, and clang::targets::XCoreTargetInfo.
Referenced by validateInputConstraint(), and validateOutputConstraint().
validateBranchProtection()
virtual bool clang::TargetInfo::validateBranchProtection (StringRef Spec, StringRef Arch, BranchProtectionInfo & BPI, StringRef & Err) const inline virtual
Determine if this TargetInfo supports the given branch protection specification.
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::ARMTargetInfo.
Definition at line 1376 of file TargetInfo.h.
Referenced by clang::Sema::checkTargetAttr().
validateConstraintModifier()
virtual bool clang::TargetInfo::validateConstraintModifier (StringRef , char , unsigned , std::string &) const inline virtual
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::ARMTargetInfo.
Definition at line 1164 of file TargetInfo.h.
Referenced by clang::Sema::ActOnGCCAsmStmt().
validateCpuIs()
virtual bool clang::TargetInfo::validateCpuIs (StringRef Name) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1438 of file TargetInfo.h.
Referenced by CheckMultiVersionValue(), and SemaBuiltinCpuIs().
validateCPUSpecificCPUDispatch()
virtual bool clang::TargetInfo::validateCPUSpecificCPUDispatch (StringRef Name) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1442 of file TargetInfo.h.
Referenced by handleCPUSpecificAttr().
validateCpuSupports()
virtual bool clang::TargetInfo::validateCpuSupports (StringRef Name) const inline virtual
Reimplemented in clang::targets::AArch64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1424 of file TargetInfo.h.
Referenced by CheckMultiVersionValue(), clang::Sema::checkTargetClonesAttrString(), clang::Sema::checkTargetVersionAttr(), and SemaBuiltinCpuSupports().
validateGlobalRegisterVariable()
virtual bool clang::TargetInfo::validateGlobalRegisterVariable (StringRef RegName, unsigned RegSize, bool & HasSizeMismatch) const inline virtual
Validate register name used for global register variables.
This function returns true if the register passed in RegName can be used for global register variables on this target. In addition, it returns true in HasSizeMismatch if the size of the register doesn't match the variable size passed in RegSize.
Reimplemented in clang::targets::X86_64TargetInfo, and clang::targets::X86TargetInfo.
Definition at line 1138 of file TargetInfo.h.
validateInputConstraint()
bool TargetInfo::validateInputConstraint (MutableArrayRef< ConstraintInfo > OutputConstraints, ConstraintInfo & info) const
Definition at line 811 of file TargetInfo.cpp.
References clang::TargetInfo::ConstraintInfo::ConstraintStr, clang::TargetInfo::ConstraintInfo::getTiedOperand(), clang::TargetInfo::ConstraintInfo::hasTiedOperand(), resolveSymbolicName(), clang::TargetInfo::ConstraintInfo::setAllowsMemory(), clang::TargetInfo::ConstraintInfo::setAllowsRegister(), clang::TargetInfo::ConstraintInfo::setRequiresImmediate(), clang::TargetInfo::ConstraintInfo::setTiedOperand(), and validateAsmConstraint().
Referenced by clang::Sema::ActOnGCCAsmStmt().
validateInputSize()
virtual bool clang::TargetInfo::validateInputSize (const llvm::StringMap< bool > & FeatureMap, StringRef , unsigned) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1158 of file TargetInfo.h.
Referenced by clang::Sema::ActOnGCCAsmStmt().
validateOpenCLTarget()
bool TargetInfo::validateOpenCLTarget (const LangOptions & Opts, DiagnosticsEngine & Diags) const virtual
Check that OpenCL target has valid options setting based on OpenCL version.
validateOpenCLTarget - Check that OpenCL target has valid options setting based on OpenCL version.
Definition at line 859 of file Targets.cpp.
References clang::OpenCLOptions::diagnoseFeatureExtensionDifferences(), clang::OpenCLOptions::diagnoseUnsupportedFeatureDependencies(), clang::LangOptions::getOpenCLCompatibleVersion(), clang::LangOptions::getOpenCLVersionTuple(), getSupportedOpenCLOpts(), hasFeatureEnabled(), clang::OpenCLOptions::isOpenCLOptionCoreIn(), and clang::DiagnosticsEngine::Report().
validateOutputConstraint()
bool TargetInfo::validateOutputConstraint (ConstraintInfo & Info) const
Definition at line 714 of file TargetInfo.cpp.
References clang::TargetInfo::ConstraintInfo::allowsMemory(), clang::TargetInfo::ConstraintInfo::allowsRegister(), clang::TargetInfo::ConstraintInfo::earlyClobber(), clang::TargetInfo::ConstraintInfo::getConstraintStr(), clang::TargetInfo::ConstraintInfo::isReadWrite(), clang::TargetInfo::ConstraintInfo::setAllowsMemory(), clang::TargetInfo::ConstraintInfo::setAllowsRegister(), clang::TargetInfo::ConstraintInfo::setEarlyClobber(), clang::TargetInfo::ConstraintInfo::setIsReadWrite(), and validateAsmConstraint().
Referenced by clang::Sema::ActOnGCCAsmStmt().
validateOutputSize()
virtual bool clang::TargetInfo::validateOutputSize (const llvm::StringMap< bool > & FeatureMap, StringRef , unsigned) const inline virtual
Reimplemented in clang::targets::X86TargetInfo.
Definition at line 1152 of file TargetInfo.h.
Referenced by clang::Sema::ActOnGCCAsmStmt().
validateTarget()
virtual bool clang::TargetInfo::validateTarget (DiagnosticsEngine & Diags) const inline virtual
Check the target is valid after it is fully initialized.
Reimplemented in clang::targets::MipsTargetInfo.
Definition at line 1700 of file TargetInfo.h.
Member Data Documentation
AddrSpaceMap
const LangASMap* clang::TargetInfo::AddrSpaceMap protected
Definition at line 237 of file TargetInfo.h.
Referenced by adjust(), getAddressSpaceMap(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), clang::targets::AMDGPUTargetInfo::setAddressSpaceMap(), and TargetInfo().
AllowAMDGPUUnsafeFPAtomics
unsigned clang::TargetInfo::AllowAMDGPUUnsafeFPAtomics protected
Definition at line 254 of file TargetInfo.h.
Referenced by allowAMDGPUUnsafeFPAtomics(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), clang::targets::AMDGPUTargetInfo::getTargetDefines(), and TargetInfo().
ARMCDECoprocMask
unsigned clang::TargetInfo::ARMCDECoprocMask protected
Definition at line 256 of file TargetInfo.h.
Referenced by getARMCDECoprocMask(), clang::targets::ARMTargetInfo::handleTargetFeatures(), and TargetInfo().
BigEndian
bool clang::TargetInfo::BigEndian protected
Definition at line 213 of file TargetInfo.h.
Referenced by clang::targets::MipsTargetInfo::getTargetDefines(), isBigEndian(), isLittleEndian(), and TargetInfo().
ComplexLongDoubleUsesFP2Ret
unsigned clang::TargetInfo::ComplexLongDoubleUsesFP2Ret protected
Definition at line 244 of file TargetInfo.h.
Referenced by TargetInfo(), and useObjCFP2RetForComplexLongDouble().
DarwinTargetVariantTriple
std::optional<llvm::Triple> clang::TargetInfo::DarwinTargetVariantTriple protected
Definition at line 262 of file TargetInfo.h.
Referenced by getDarwinTargetVariantTriple().
DataLayoutString
std::string clang::TargetInfo::DataLayoutString protected
Definition at line 232 of file TargetInfo.h.
Referenced by getDataLayoutString(), and resetDataLayout().
HalfArgsAndReturns
bool clang::TargetInfo::HalfArgsAndReturns protected
Definition at line 219 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), allowHalfArgsAndReturns(), clang::targets::ARMTargetInfo::handleTargetFeatures(), and TargetInfo().
HasAArch64SVETypes
unsigned clang::TargetInfo::HasAArch64SVETypes protected
Definition at line 250 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), hasAArch64SVETypes(), and TargetInfo().
HasAlignMac68kSupport
unsigned clang::TargetInfo::HasAlignMac68kSupport protected
Definition at line 242 of file TargetInfo.h.
Referenced by clang::targets::DarwinARMTargetInfo::DarwinARMTargetInfo(), hasAlignMac68kSupport(), and TargetInfo().
HasBFloat16
bool clang::TargetInfo::HasBFloat16 protected
Definition at line 222 of file TargetInfo.h.
Referenced by clang::targets::ARMTargetInfo::getTargetDefines(), clang::targets::ARMTargetInfo::handleTargetFeatures(), clang::targets::X86TargetInfo::handleTargetFeatures(), hasBFloat16Type(), clang::targets::ARMTargetInfo::hasBFloat16Type(), and TargetInfo().
HasBuiltinMSVaList
unsigned clang::TargetInfo::HasBuiltinMSVaList protected
Definition at line 246 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), hasBuiltinMSVaList(), and TargetInfo().
HasFloat128
bool clang::TargetInfo::HasFloat128 protected
Definition at line 220 of file TargetInfo.h.
Referenced by clang::targets::PPCTargetInfo::getTargetDefines(), clang::targets::X86TargetInfo::getTargetDefines(), clang::targets::PPCTargetInfo::handleTargetFeatures(), clang::targets::PPCTargetInfo::hasFeature(), hasFloat128Type(), clang::targets::AMDGPUTargetInfo::setAuxTarget(), and TargetInfo().
HasFloat16
bool clang::TargetInfo::HasFloat16 protected
Definition at line 221 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), clang::targets::ARMTargetInfo::handleTargetFeatures(), clang::targets::HexagonTargetInfo::handleTargetFeatures(), clang::targets::X86TargetInfo::handleTargetFeatures(), hasFloat16Type(), clang::targets::RISCVTargetInfo::RISCVTargetInfo(), and TargetInfo().
HasFPReturn
bool clang::TargetInfo::HasFPReturn protected
Definition at line 228 of file TargetInfo.h.
Referenced by hasFPReturn(), and TargetInfo().
HasFullBFloat16
bool clang::TargetInfo::HasFullBFloat16 protected
Definition at line 223 of file TargetInfo.h.
Referenced by clang::targets::ARMTargetInfo::handleTargetFeatures(), clang::targets::X86TargetInfo::handleTargetFeatures(), hasBFloat16Type(), clang::targets::X86TargetInfo::hasFeature(), hasFullBFloat16Type(), and TargetInfo().
HasIbm128
bool clang::TargetInfo::HasIbm128 protected
Definition at line 226 of file TargetInfo.h.
Referenced by hasIbm128Type(), and TargetInfo().
HasLegalHalfType
bool clang::TargetInfo::HasLegalHalfType protected
Definition at line 217 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), clang::targets::ARMTargetInfo::getTargetDefines(), clang::targets::ARMTargetInfo::handleTargetFeatures(), clang::targets::HexagonTargetInfo::handleTargetFeatures(), clang::targets::RISCVTargetInfo::handleTargetFeatures(), clang::targets::X86TargetInfo::handleTargetFeatures(), hasLegalHalfType(), and TargetInfo().
HasLongDouble
bool clang::TargetInfo::HasLongDouble protected
Definition at line 227 of file TargetInfo.h.
Referenced by clang::targets::X86TargetInfo::handleTargetFeatures(), hasLongDoubleType(), and TargetInfo().
HasRISCVVTypes
unsigned clang::TargetInfo::HasRISCVVTypes protected
Definition at line 252 of file TargetInfo.h.
Referenced by hasRISCVVTypes(), clang::targets::RISCVTargetInfo::RISCVTargetInfo(), and TargetInfo().
HasStrictFP
bool clang::TargetInfo::HasStrictFP protected
Definition at line 229 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::PPCTargetInfo::handleTargetFeatures(), hasStrictFP(), clang::targets::RISCVTargetInfo::RISCVTargetInfo(), and TargetInfo().
IsRenderScriptTarget
unsigned clang::TargetInfo::IsRenderScriptTarget protected
Definition at line 248 of file TargetInfo.h.
Referenced by isRenderScriptTarget(), clang::targets::RenderScript32TargetInfo::RenderScript32TargetInfo(), clang::targets::RenderScript64TargetInfo::RenderScript64TargetInfo(), and TargetInfo().
MaxAtomicInlineWidth
unsigned char clang::TargetInfo::MaxAtomicInlineWidth protected
Definition at line 231 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::PPCTargetInfo::adjust(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), getMaxAtomicInlineWidth(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), and TargetInfo().
MaxAtomicPromoteWidth
unsigned char clang::TargetInfo::MaxAtomicPromoteWidth protected
Definition at line 231 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), getMaxAtomicPromoteWidth(), and TargetInfo().
MaxBitIntWidth
std::optional<unsigned> clang::TargetInfo::MaxBitIntWidth protected
Definition at line 260 of file TargetInfo.h.
Referenced by adjust(), getMaxBitIntWidth(), and TargetInfo().
MaxOpenCLWorkGroupSize
unsigned clang::TargetInfo::MaxOpenCLWorkGroupSize protected
Definition at line 258 of file TargetInfo.h.
Referenced by getMaxOpenCLWorkGroupSize(), and TargetInfo().
MCountName
const char* clang::TargetInfo::MCountName protected
Definition at line 234 of file TargetInfo.h.
Referenced by getMCountName(), clang::targets::RISCVTargetInfo::RISCVTargetInfo(), and TargetInfo().
NoAsmVariants
bool clang::TargetInfo::NoAsmVariants protected
Definition at line 216 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::ARMTargetInfo::ARMTargetInfo(), hasNoAsmVariants(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), and TargetInfo().
PlatformMinVersion
VersionTuple clang::TargetInfo::PlatformMinVersion mutable protected
Definition at line 240 of file TargetInfo.h.
Referenced by clang::targets::DarwinAArch64TargetInfo::getOSDefines(), clang::targets::DarwinARMTargetInfo::getOSDefines(), getPlatformMinVersion(), and TargetInfo().
PlatformName
StringRef clang::TargetInfo::PlatformName mutable protected
Definition at line 239 of file TargetInfo.h.
Referenced by clang::targets::DarwinAArch64TargetInfo::getOSDefines(), clang::targets::DarwinARMTargetInfo::getOSDefines(), getPlatformName(), and TargetInfo().
ReadOnlyFeatures
llvm::StringSet clang::TargetInfo::ReadOnlyFeatures protected
Definition at line 275 of file TargetInfo.h.
Referenced by clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), and isReadOnlyFeature().
RealTypeUsesObjCFPRetMask
unsigned clang::TargetInfo::RealTypeUsesObjCFPRetMask protected
Definition at line 243 of file TargetInfo.h.
Referenced by TargetInfo(), and useObjCFPRetForRealType().
RegParmMax
unsigned char clang::TargetInfo::RegParmMax protected
Definition at line 235 of file TargetInfo.h.
Referenced by getRegParmMax(), and TargetInfo().
SSERegParmMax
unsigned char clang::TargetInfo::SSERegParmMax protected
Definition at line 235 of file TargetInfo.h.
Referenced by TargetInfo().
TheCXXABI
TargetCXXABI clang::TargetInfo::TheCXXABI protected
Definition at line 236 of file TargetInfo.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::targets::DarwinAArch64TargetInfo::DarwinAArch64TargetInfo(), clang::targets::DarwinARMTargetInfo::DarwinARMTargetInfo(), getCXXABI(), clang::targets::ItaniumWindowsARMleTargetInfo::ItaniumWindowsARMleTargetInfo(), clang::targets::MicrosoftARM64TargetInfo::MicrosoftARM64TargetInfo(), clang::targets::MicrosoftARMleTargetInfo::MicrosoftARMleTargetInfo(), clang::targets::MinGWARM64TargetInfo::MinGWARM64TargetInfo(), clang::targets::MinGWARMTargetInfo::MinGWARMTargetInfo(), and TargetInfo().
TLSSupported
bool clang::TargetInfo::TLSSupported protected
Definition at line 214 of file TargetInfo.h.
Referenced by clang::targets::CygwinARMTargetInfo::CygwinARMTargetInfo(), isTLSSupported(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), and TargetInfo().
UseAddrSpaceMapMangling
bool clang::TargetInfo::UseAddrSpaceMapMangling protected
Specify if mangling based on address space map should be used or not for language specific address spaces.
Definition at line 346 of file TargetInfo.h.
Referenced by clang::targets::AMDGPUTargetInfo::AMDGPUTargetInfo(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), TargetInfo(), and useAddressSpaceMapMangling().
UserLabelPrefix
const char* clang::TargetInfo::UserLabelPrefix protected
Definition at line 233 of file TargetInfo.h.
Referenced by getUserLabelPrefix(), resetDataLayout(), and TargetInfo().
VLASupported
bool clang::TargetInfo::VLASupported protected
Definition at line 215 of file TargetInfo.h.
Referenced by isVLASupported(), clang::targets::NVPTXTargetInfo::NVPTXTargetInfo(), and TargetInfo().
The documentation for this class was generated from the following files:
include/clang/Basic/TargetInfo.h
lib/Basic/TargetInfo.cpp
lib/Basic/Targets.cpp