clang: clang::diff::ASTDiff::Impl Class Reference
clang::diff::ASTDiff::Impl Class Reference
Public Member Functions
Impl (SyntaxTree::Impl &T1, SyntaxTree::Impl &T2, const ComparisonOptions &Options)
void computeMapping ()
Matches nodes one-by-one based on their similarity.
void computeChangeKinds (Mapping &M)
NodeId getMapped (const std::unique_ptr< SyntaxTree::Impl > &Tree, NodeId Id) const
Public Attributes
SyntaxTree::Impl & T1
SyntaxTree::Impl & T2
Mapping TheMapping
Friends
class ZhangShashaMatcher
Detailed Description
Definition at line 58 of file ASTDiff.cpp.
Constructor & Destructor Documentation
Impl()
clang::diff::ASTDiff::Impl::Impl (SyntaxTree::Impl & T1, SyntaxTree::Impl & T2, const ComparisonOptions & Options)
Definition at line 902 of file ASTDiff.cpp.
References computeChangeKinds(), computeMapping(), and TheMapping.
Member Function Documentation
computeChangeKinds()
void clang::diff::ASTDiff::Impl::computeChangeKinds (Mapping & M)
Definition at line 916 of file ASTDiff.cpp.
References clang::diff::Node::Change, clang::diff::Delete, clang::diff::Insert, clang::diff::NodeId::isInvalid(), clang::diff::Move, clang::diff::Update, and clang::diff::UpdateMove.
Referenced by Impl().
computeMapping()
void clang::diff::ASTDiff::Impl::computeMapping ()
Matches nodes one-by-one based on their similarity.
Definition at line 909 of file ASTDiff.cpp.
Referenced by Impl().
getMapped()
NodeId clang::diff::ASTDiff::Impl::getMapped (const std::unique_ptr< SyntaxTree::Impl > & Tree, NodeId Id) const inline
Definition at line 72 of file ASTDiff.cpp.
References Id, T1, T2, TheMapping, and Tree.
Referenced by clang::diff::ASTDiff::getMapped().
Friends And Related Symbol Documentation
ZhangShashaMatcher
friend class ZhangShashaMatcher friend
Definition at line 109 of file ASTDiff.cpp.
Member Data Documentation
T1
SyntaxTree::Impl& clang::diff::ASTDiff::Impl::T1
Definition at line 60 of file ASTDiff.cpp.
Referenced by getMapped().
T2
SyntaxTree::Impl & clang::diff::ASTDiff::Impl::T2
Definition at line 60 of file ASTDiff.cpp.
Referenced by getMapped().
TheMapping
Mapping clang::diff::ASTDiff::Impl::TheMapping
Definition at line 61 of file ASTDiff.cpp.
Referenced by getMapped(), and Impl().
The documentation for this class was generated from the following file:
lib/Tooling/ASTDiff/ASTDiff.cpp