clang: clang::AttributeCommonInfo Class Reference
clang::AttributeCommonInfo Class Reference
#include "clang/Basic/AttributeCommonInfo.h"
Classes
class Form
Combines information about the source-code form of an attribute, including its syntax and spelling.
Public Types
enum Syntax {
AS_GNU = 1 , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword ,
AS_HLSLSemantic , AS_Implicit
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Form FormUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Form FormUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Form FormUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Form FormUsed)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
Form getForm () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isClangScope () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isStandardAttributeSyntax () const
The attribute is spelled [[]] in either C or C++ mode, including standard attributes spelled with a keyword, like alignas.
bool isGNUAttribute () const
bool isKeywordAttribute () const
bool isRegularKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Protected Member Functions
bool isAttributeSpellingListCalculated () const
Static Protected Attributes
static constexpr unsigned SpellingNotCalculated = 0xf
Friends
class clang::ASTRecordWriter
Detailed Description
Definition at line 23 of file AttributeCommonInfo.h.
Member Enumeration Documentation
Kind
enum clang::AttributeCommonInfo::Kind
Enumerator
NoSemaHandlerAttribute
IgnoredAttribute
UnknownAttribute
Definition at line 60 of file AttributeCommonInfo.h.
Syntax
enum clang::AttributeCommonInfo::Syntax
The style used to specify an attribute.
Enumerator
AS_GNU
attribute((...))
AS_CXX11
[[...]]
AS_C2x
[[...]]
AS_Declspec
__declspec(...)
AS_Microsoft
[uuid("...")] class Foo
AS_Keyword
__ptr16, alignas(...), etc.
AS_Pragma
#pragma ...
AS_ContextSensitiveKeyword
Context-sensitive version of a keyword attribute.
AS_HLSLSemantic
<vardecl> : <semantic>
AS_Implicit
The attibute has no source code manifestation and is only created implicitly.
Definition at line 26 of file AttributeCommonInfo.h.
Constructor & Destructor Documentation
AttributeCommonInfo() [1/6]
clang::AttributeCommonInfo::AttributeCommonInfo (const IdentifierInfo * AttrName, const IdentifierInfo * ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Form FormUsed) inline
Definition at line 130 of file AttributeCommonInfo.h.
References AS_GNU, and AS_Implicit.
AttributeCommonInfo() [2/6]
clang::AttributeCommonInfo::AttributeCommonInfo (const IdentifierInfo * AttrName, const IdentifierInfo * ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Form FormUsed) inline
Definition at line 143 of file AttributeCommonInfo.h.
AttributeCommonInfo() [3/6]
clang::AttributeCommonInfo::AttributeCommonInfo (const IdentifierInfo * AttrName, SourceRange AttrRange, Form FormUsed) inline
Definition at line 151 of file AttributeCommonInfo.h.
AttributeCommonInfo() [4/6]
clang::AttributeCommonInfo::AttributeCommonInfo (SourceRange AttrRange, Kind K, Form FormUsed) inline
Definition at line 156 of file AttributeCommonInfo.h.
AttributeCommonInfo() [5/6]
clang::AttributeCommonInfo::AttributeCommonInfo (AttributeCommonInfo &&) default
AttributeCommonInfo() [6/6]
clang::AttributeCommonInfo::AttributeCommonInfo (const AttributeCommonInfo &) default
Member Function Documentation
getAttributeSpellingListIndex()
unsigned clang::AttributeCommonInfo::getAttributeSpellingListIndex () const inline
Definition at line 211 of file AttributeCommonInfo.h.
References isAttributeSpellingListCalculated().
Referenced by clang::Attr::getSpellingListIndex(), and clang::Sema::mergeSectionAttr().
getAttrName()
const IdentifierInfo * clang::AttributeCommonInfo::getAttrName () const inline
Definition at line 169 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr(), getNormalizedFullName(), handleAlwaysInlineAttr(), handleArgumentWithTypeTagAttr(), handleEnforceTCBAttr(), handleNoSanitizeSpecificAttr(), HandleOpenCLAccessAttr(), handleOpenCLAccessAttr(), clang::operator<<(), and clang::operator<<().
getForm()
Form clang::AttributeCommonInfo::getForm () const inline
Definition at line 165 of file AttributeCommonInfo.h.
References getSyntax().
getLoc()
SourceLocation clang::AttributeCommonInfo::getLoc () const inline
Definition at line 170 of file AttributeCommonInfo.h.
References clang::SourceRange::getBegin().
Referenced by clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignValueAttr(), clang::Sema::AddAllocAlignAttr(), clang::Sema::AddAssumeAlignedAttr(), clang::Sema::AddModeAttr(), clang::Sema::AddParameterABIAttr(), attrNonNullArgCheck(), checkAcquireOrderAttrCommon(), checkAttrArgsAreCapabilityObjs(), checkAttributeNumArgsImpl(), checkAttrMutualExclusion(), clang::Sema::CheckAttrTarget(), clang::Sema::CheckCallingConvAttr(), checkForConsumableClass(), checkFunctionConditionAttr(), checkIBOutletCommon(), clang::Sema::CheckRegparmAttr(), checkTryLockFunAttrCommon(), clang::ParsedAttr::diagnoseLangOpts(), getAttrLoc(), handleAbiTagAttr(), handleAcquireHandleAttr(), HandleAddressSpaceTypeAttribute(), handleAliasAttr(), handleAlignedAttr(), handleAllocSizeAttr(), handleAnalyzerNoReturnAttr(), HandleAnnotateTypeAttr(), handleAnyX86InterruptAttr(), handleArgumentWithTypeTagAttr(), handleArmBuiltinAliasAttr(), handleARMInterruptAttr(), HandleArmMveStrictPolymorphismAttr(), HandleArmSveVectorBitsTypeAttr(), handleAvailabilityAttr(), handleBlocksAttr(), HandleBTFTypeTagAttribute(), handleBuiltinAliasAttr(), handleCallbackAttr(), handleCallConvAttr(), handleCalledOnceAttr(), handleCFGuardAttr(), handleCmseNSEntryAttr(), handleCodeSegAttr(), handleCommonAttr(), handleConstantAttr(), handleConstructorAttr(), handleConsumableAttr(), handleCPUSpecificAttr(), handleDeclspecThreadAttr(), handleDependencyAttr(), handleDeprecatedAttr(), handleDeviceAttr(), handleDiagnoseAsBuiltinAttr(), handleDiagnoseIfAttr(), handleEnableIfAttr(), handleEnforceTCBAttr(), handleEnumExtensibilityAttr(), HandleExtVectorTypeAttr(), handleFallThroughAttr(), handleFormatArgAttr(), handleFormatAttr(), handleGNUInlineAttr(), handleHLSLNumThreadsAttr(), handleHLSLResourceBindingAttr(), handleHLSLShaderAttr(), handleHLSLSV_DispatchThreadIDAttr(), handleHLSLSVGroupIndexAttr(), handleIBOutletCollection(), handleIFuncAttr(), handleInitPriorityAttr(), handleLayoutVersion(), handleLifetimeCategoryAttr(), handleLikely(), handleM68kInterruptAttr(), handleManagedAttr(), HandleMatrixTypeAttr(), handleMinVectorWidthAttr(), handleMipsInterruptAttr(), handleModeAttr(), handleMSAllocatorAttr(), handleMSInheritanceAttr(), handleMSP430InterruptAttr(), handleMSPointerTypeQualifierAttr(), handleNakedAttr(), HandleNeonVectorTypeAttr(), handleNoCfCheckAttr(), handleNoEscapeAttr(), handleNoMergeAttr(), handleNonNullAttr(), handleNonNullAttrParameter(), handleNoReturnAttr(), handleNSErrorDomain(), handleObjCBridgeAttr(), handleObjCDirectAttr(), handleObjCDirectMembersAttr(), handleObjCMethodFamilyAttr(), handleObjCPreciseLifetimeAttr(), handleObjCReturnsInnerPointerAttr(), handleObjCSuppresProtocolAttr(), HandleOpenCLAccessAttr(), handleOpenCLAccessAttr(), handleOpenCLNoSVMAttr(), handleOpenCLUnrollHint(), handleOwnershipAttr(), handlePackedAttr(), handleParamTypestateAttr(), handlePreferredName(), handleRestrictAttr(), handleReturnTypestateAttr(), handleRISCVInterruptAttr(), HandleRISCVRVVVectorBitsTypeAttr(), handleSentinelAttr(), handleSetTypestateAttr(), handleSharedAttr(), handleStandardNoReturnAttr(), handleSubGroupSize(), handleSwiftAsyncAttr(), handleSwiftAsyncError(), handleSwiftBridge(), handleSwiftError(), handleSwiftNewType(), handleTargetClonesAttr(), handleTestTypestateAttr(), handleTransparentUnionAttr(), handleTypeTagForDatatypeAttr(), handleUnlikely(), handleUnusedAttr(), handleUuidAttr(), handleVecReturnAttr(), HandleVectorSizeAttr(), handleVecTypeHint(), handleVisibilityAttr(), handleWarnUnusedResult(), handleWeakImportAttr(), handleWeakRefAttr(), HandleWebAssemblyFuncrefAttr(), handleWebAssemblyImportModuleAttr(), handleWebAssemblyImportNameAttr(), handleWorkGroupSize(), handleX86ForceAlignArgPointerAttr(), instantiateDependentAnnotationAttr(), clang::Sema::mergeAlwaysInlineAttr(), clang::Sema::mergeAvailabilityAttr(), clang::Sema::mergeCodeSegAttr(), clang::Sema::mergeDLLImportAttr(), clang::Sema::mergeErrorAttr(), clang::Sema::mergeHLSLNumThreadsAttr(), clang::Sema::mergeHLSLShaderAttr(), clang::Sema::mergeInternalLinkageAttr(), clang::Sema::mergeMinSizeAttr(), clang::Sema::mergeMSInheritanceAttr(), clang::Sema::mergeOptimizeNoneAttr(), clang::Sema::mergeSectionAttr(), clang::Sema::mergeUuidAttr(), mergeVisibilityAttr(), ProcessDeclAttribute(), ProcessStmtAttribute(), threadSafetyCheckIsPointer(), and verifyValidIntegerConstantExpr().
getNormalizedFullName()
std::string AttributeCommonInfo::getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
gnu::attr will be normalized to gnu::attr).
Definition at line 133 of file Attributes.cpp.
References getAttrName(), getScopeName(), getSyntax(), and normalizeName().
Referenced by clang::ParsedAttrInfo::get(), and clang::Sema::mergeErrorAttr().
getParsedKind() [1/2]
Kind clang::AttributeCommonInfo::getParsedKind () const inline
Definition at line 163 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr(), clang::ParsedAttr::asHLSLLangAS(), clang::ParsedAttr::asOpenCLLangAS(), clang::ParsedAttrInfo::get(), clang::ParsedAttr::getAvailabilityDeprecated(), clang::ParsedAttr::getAvailabilityIntroduced(), clang::ParsedAttr::getAvailabilityObsoleted(), clang::ParsedAttr::getLayoutCompatible(), clang::ParsedAttr::getMatchingCType(), clang::ParsedAttr::getMessageExpr(), clang::ParsedAttr::getMustBeNull(), clang::ParsedAttr::getReplacementExpr(), clang::ParsedAttr::getStrictLoc(), clang::ParsedAttr::getUnavailableLoc(), handleCPUSpecificAttr(), clang::ParsedAttributesView::hasAttribute(), IsBuiltInOrStandardCXX11Attribute(), and clang::ParsedAttr::slidesFromDeclToDeclSpecLegacyBehavior().
getParsedKind() [2/2]
AttributeCommonInfo::Kind AttributeCommonInfo::getParsedKind (const IdentifierInfo * Name, const IdentifierInfo * Scope, Syntax SyntaxUsed) static
Definition at line 127 of file Attributes.cpp.
References normalizeName().
getRange()
SourceRange clang::AttributeCommonInfo::getRange () const inline
Definition at line 171 of file AttributeCommonInfo.h.
Referenced by clang::Sema::ActOnIfStmt(), clang::Sema::AddAllocAlignAttr(), clang::Sema::AddAssumeAlignedAttr(), clang::ASTRecordWriter::AddAttr(), clang::Sema::AddModeAttr(), clang::Sema::AddXConsumedAttr(), clang::Sema::CheckAttrTarget(), clang::Sema::CheckCompleteVariableDeclaration(), clang::AttributedTypeLoc::getLocalSourceRange(), clang::Attr::getLocation(), handleAcquireHandleAttr(), handleAvailabilityAttr(), handleCallbackAttr(), handleDeprecatedAttr(), handleDLLAttr(), handleFallThroughAttr(), handleMSAllocatorAttr(), handleNoEscapeAttr(), handleObjCOwnershipAttr(), handleObjCSuppresProtocolAttr(), HandleOpenCLAccessAttr(), handleOpenCLAccessAttr(), handleOpenCLUnrollHint(), handleRISCVInterruptAttr(), handleStandardNoReturnAttr(), handleVisibilityAttr(), handleXReturnsXRetainedAttr(), instantiateOMPDeclareSimdDeclAttr(), instantiateOMPDeclareVariantAttr(), clang::Sema::mergeAvailabilityAttr(), clang::Sema::mergeFormatAttr(), clang::Sema::mergeMSInheritanceAttr(), ProcessDeclAttribute(), ProcessStmtAttribute(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
getScopeLoc()
SourceLocation clang::AttributeCommonInfo::getScopeLoc () const inline
Definition at line 176 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr().
getScopeName()
const IdentifierInfo * clang::AttributeCommonInfo::getScopeName () const inline
Definition at line 175 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr(), getNormalizedFullName(), handleFallThroughAttr(), handleLikely(), handleUnlikely(), handleUnusedAttr(), and handleWarnUnusedResult().
getSyntax()
Syntax clang::AttributeCommonInfo::getSyntax () const inline
Definition at line 164 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr(), clang::ParsedAttrInfo::get(), getForm(), and getNormalizedFullName().
hasScope()
bool clang::AttributeCommonInfo::hasScope () const inline
Definition at line 174 of file AttributeCommonInfo.h.
isAttributeSpellingListCalculated()
bool clang::AttributeCommonInfo::isAttributeSpellingListCalculated () const inline protected
Definition at line 234 of file AttributeCommonInfo.h.
References SpellingNotCalculated.
Referenced by getAttributeSpellingListIndex().
isC2xAttribute()
bool clang::AttributeCommonInfo::isC2xAttribute () const inline
Definition at line 191 of file AttributeCommonInfo.h.
References AS_C2x.
Referenced by isStandardAttributeSyntax().
isClangScope()
bool AttributeCommonInfo::isClangScope () const
Definition at line 103 of file Attributes.cpp.
References clang::IdentifierInfo::isStr().
Referenced by handleWarnUnusedResult(), and ProcessDeclAttribute().
isContextSensitiveKeywordAttribute()
bool clang::AttributeCommonInfo::isContextSensitiveKeywordAttribute () const inline
Definition at line 207 of file AttributeCommonInfo.h.
References AS_ContextSensitiveKeyword.
isCXX11Attribute()
bool clang::AttributeCommonInfo::isCXX11Attribute () const inline
Definition at line 189 of file AttributeCommonInfo.h.
References AS_CXX11.
Referenced by handleDeprecatedAttr(), handleFallThroughAttr(), handleLikely(), handleUnlikely(), handleUnusedAttr(), isStandardAttributeSyntax(), and ProcessDeclAttribute().
isDeclspecAttribute()
bool clang::AttributeCommonInfo::isDeclspecAttribute () const inline
Definition at line 183 of file AttributeCommonInfo.h.
References AS_Declspec.
Referenced by handleDeprecatedAttr(), handleNakedAttr(), ProcessDeclAttribute(), and ProcessStmtAttribute().
isGNUAttribute()
bool clang::AttributeCommonInfo::isGNUAttribute () const inline
Definition at line 199 of file AttributeCommonInfo.h.
References AS_GNU.
Referenced by handleWarnUnusedResult().
isGNUScope()
bool AttributeCommonInfo::isGNUScope () const
Definition at line 99 of file Attributes.cpp.
References clang::IdentifierInfo::isStr().
Referenced by handleDeprecatedAttr(), and handleWarnUnusedResult().
isKeywordAttribute()
bool clang::AttributeCommonInfo::isKeywordAttribute () const inline
Definition at line 201 of file AttributeCommonInfo.h.
References AS_ContextSensitiveKeyword, and AS_Keyword.
isMicrosoftAttribute()
bool clang::AttributeCommonInfo::isMicrosoftAttribute () const inline
Definition at line 184 of file AttributeCommonInfo.h.
References AS_Microsoft.
Referenced by handleUuidAttr().
isRegularKeywordAttribute()
bool clang::AttributeCommonInfo::isRegularKeywordAttribute () const inline
Definition at line 205 of file AttributeCommonInfo.h.
Referenced by clang::ASTRecordWriter::AddAttr(), clang::Sema::AddParameterABIAttr(), checkAttrMutualExclusion(), checkAttrMutualExclusion(), clang::Sema::CheckAttrTarget(), clang::Declarator::Declarator(), clang::Sema::DiagnoseSwiftName(), handleAnalyzerNoReturnAttr(), handleAnyX86InterruptAttr(), handleAVRInterruptAttr(), handleAVRSignalAttr(), handleCallConvAttr(), handleLifetimeCategoryAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), handleNakedAttr(), handleNoReturnAttr(), handleNoSanitizeSpecificAttr(), handleObjCOwnershipAttr(), handleOwnershipAttr(), handleRISCVInterruptAttr(), handleSentinelAttr(), handleSwiftNewType(), handleTransparentUnionAttr(), handleTypeTagForDatatypeAttr(), handleVisibilityAttr(), handleWarnUnusedResult(), handleWeakImportAttr(), handleWebAssemblyExportNameAttr(), handleX86ForceAlignArgPointerAttr(), handleXReturnsXRetainedAttr(), clang::Sema::mergeErrorAttr(), clang::Sema::mergeInternalLinkageAttr(), ProcessDeclAttribute(), ProcessStmtAttribute(), clang::ParsedAttr::slidesFromDeclToDeclSpecLegacyBehavior(), and validateAlignasAppliedType().
isStandardAttributeSyntax()
bool clang::AttributeCommonInfo::isStandardAttributeSyntax () const inline
The attribute is spelled [[]] in either C or C++ mode, including standard attributes spelled with a keyword, like alignas.
Definition at line 195 of file AttributeCommonInfo.h.
References isC2xAttribute(), and isCXX11Attribute().
Referenced by clang::Declarator::Declarator(), handleAnalyzerNoReturnAttr(), handleDeprecatedAttr(), handleNoSanitizeSpecificAttr(), handleWarnUnusedResult(), ProcessDeclAttribute(), and clang::ParsedAttr::slidesFromDeclToDeclSpecLegacyBehavior().
setAttributeSpellingListIndex()
void clang::AttributeCommonInfo::setAttributeSpellingListIndex (unsigned V) inline
Definition at line 218 of file AttributeCommonInfo.h.
References V.
Referenced by handleNoSanitizeSpecificAttr().
setRange()
void clang::AttributeCommonInfo::setRange (SourceRange R) inline
Definition at line 172 of file AttributeCommonInfo.h.
Friends And Related Symbol Documentation
clang::ASTRecordWriter
friend class clang::ASTRecordWriter friend
Definition at line 229 of file AttributeCommonInfo.h.
Member Data Documentation
SpellingNotCalculated
unsigned clang::AttributeCommonInfo::SpellingNotCalculated = 0xf static constexpr protected
Definition at line 83 of file AttributeCommonInfo.h.
Referenced by isAttributeSpellingListCalculated(), and clang::AttributeCommonInfo::Form::Keyword().
The documentation for this class was generated from the following files:
include/clang/Basic/AttributeCommonInfo.h
lib/Basic/Attributes.cpp