clang: clang::CoroutineStmtBuilder Class Reference
clang::CoroutineStmtBuilder Class Reference
#include "/root/llvm-project/clang/lib/Sema/CoroutineStmtBuilder.h"
Public Member Functions
CoroutineStmtBuilder (Sema &S, FunctionDecl &FD, sema::FunctionScopeInfo &Fn, Stmt *Body)
Construct a CoroutineStmtBuilder and initialize the promise statement and initial/final suspends from the FunctionScopeInfo.
bool buildStatements ()
Build the coroutine body statements, including the "promise dependent" statements when the promise type is not dependent.
bool buildDependentStatements ()
Build the coroutine body statements that require a non-dependent promise type in order to construct.
bool isInvalid () const
Additional Inherited Members
Public Attributes inherited from clang::CoroutineBodyStmt::CtorArgs
Stmt * Body = nullptr
Stmt * Promise = nullptr
Expr * InitialSuspend = nullptr
Expr * FinalSuspend = nullptr
Stmt * OnException = nullptr
Stmt * OnFallthrough = nullptr
Expr * Allocate = nullptr
Expr * Deallocate = nullptr
Stmt * ResultDecl = nullptr
Expr * ReturnValue = nullptr
Stmt * ReturnStmt = nullptr
Stmt * ReturnStmtOnAllocFailure = nullptr
ArrayRef< Stmt * > ParamMoves
Detailed Description
Definition at line 24 of file CoroutineStmtBuilder.h.
Constructor & Destructor Documentation
CoroutineStmtBuilder()
CoroutineStmtBuilder::CoroutineStmtBuilder (Sema & S, FunctionDecl & FD, sema::FunctionScopeInfo & Fn, Stmt * Body)
Construct a CoroutineStmtBuilder and initialize the promise statement and initial/final suspends from the FunctionScopeInfo.
Definition at line 1152 of file SemaCoroutine.cpp.
References clang::CoroutineBodyStmt::CtorArgs::Body, buildCoroutineBody(), clang::sema::FunctionScopeInfo::CoroutineParameterMoves, clang::sema::FunctionScopeInfo::CoroutinePromise, clang::Type::getAsCXXRecordDecl(), clang::Sema::getASTContext(), clang::ValueDecl::getType(), and clang::CoroutineBodyStmt::CtorArgs::ParamMoves.
Member Function Documentation
buildDependentStatements()
bool CoroutineStmtBuilder::buildDependentStatements ()
Build the coroutine body statements that require a non-dependent promise type in order to construct.
For example different new/delete overloads are selected depending on if the promise type provides unhandled_exception(), and therefore they cannot be built until the promise type is complete so that we can perform name lookup.
Definition at line 1180 of file SemaCoroutine.cpp.
Referenced by buildStatements().
buildStatements()
bool CoroutineStmtBuilder::buildStatements ()
Build the coroutine body statements, including the "promise dependent" statements when the promise type is not dependent.
Definition at line 1172 of file SemaCoroutine.cpp.
References buildDependentStatements().
isInvalid()
bool clang::CoroutineStmtBuilder::isInvalid () const inline
Definition at line 53 of file CoroutineStmtBuilder.h.
The documentation for this class was generated from the following files:
lib/Sema/CoroutineStmtBuilder.h
lib/Sema/SemaCoroutine.cpp