clang: clang::TreeTransform< Derived > Class Template Reference
clang::TreeTransform< Derived > Class Template Reference
A semantic tree transformation that allows one to transform one abstract syntax tree into another.
#include "/root/llvm-project/clang/lib/Sema/TreeTransform.h"
Classes
class TemporaryBase
RAII object that temporarily sets the base location and entity used for reporting diagnostics in types.
Public Types
enum StmtDiscardKind { SDK_Discarded , SDK_NotDiscarded , SDK_StmtExprResult }
The reason why the value of a statement is not discarded, if any.
Public Member Functions
TreeTransform (Sema &SemaRef)
Initializes a new tree transformer.
Derived & getDerived ()
Retrieves a reference to the derived class.
const Derived & getDerived () const
Retrieves a reference to the derived class.
Sema & getSema () const
Retrieves a reference to the semantic analysis object used for this tree transform.
bool AlwaysRebuild ()
Whether the transformation should always rebuild AST nodes, even if none of the children have changed.
bool ReplacingOriginal ()
Whether the transformation is forming an expression or statement that replaces the original.
bool AllowSkippingCXXConstructExpr ()
Wether CXXConstructExpr can be skipped when they are implicit.
SourceLocation getBaseLocation ()
Returns the location of the entity being transformed, if that information was not available elsewhere in the AST.
DeclarationName getBaseEntity ()
Returns the name of the entity being transformed, if that information was not available elsewhere in the AST.
void setBase (SourceLocation Loc, DeclarationName Entity)
Sets the "base" location and entity when that information is known based on another transformation.
bool AlreadyTransformed (QualType T)
Determine whether the given type T has already been transformed.
unsigned TransformTemplateDepth (unsigned Depth)
Transform a template parameter depth level.
bool DropCallArgument (Expr *E)
Determine whether the given call argument should be dropped, e.g., because it is a default argument.
bool TryExpandParameterPacks (SourceLocation EllipsisLoc, SourceRange PatternRange, ArrayRef< UnexpandedParameterPack > Unexpanded, bool &ShouldExpand, bool &RetainExpansion, std::optional< unsigned > &NumExpansions)
Determine whether we should expand a pack expansion with the given set of parameter packs into separate arguments by repeatedly transforming the pattern.
TemplateArgument ForgetPartiallySubstitutedPack ()
"Forget" about the partially-substituted pack template argument, when performing an instantiation that must preserve the parameter pack use.
void RememberPartiallySubstitutedPack (TemplateArgument Arg)
"Remember" the partially-substituted pack template argument after performing an instantiation that must preserve the parameter pack use.
void ExpandingFunctionParameterPack (ParmVarDecl *Pack)
Note to the derived class when a function parameter pack is being expanded.
QualType TransformType (QualType T)
Transforms the given type into another type.
TypeSourceInfo * TransformType (TypeSourceInfo *DI)
Transforms the given type-with-location into a new type-with-location.
QualType TransformType (TypeLocBuilder &TLB, TypeLoc TL)
Transform the given type-with-location into a new type, collecting location information in the given builder as necessary.
StmtResult TransformStmt (Stmt *S, StmtDiscardKind SDK=SDK_Discarded)
Transform the given statement.
OMPClause * TransformOMPClause (OMPClause *S)
Transform the given statement.
const Attr * TransformAttr (const Attr *S)
Transform the given attribute.
const Attr * TransformStmtAttr (const Stmt *OrigS, const Stmt *InstS, const Attr *A)
ExprResult TransformExpr (Expr *E)
Transform the given expression.
ExprResult TransformInitializer (Expr *Init, bool NotCopyInit)
Transform the given initializer.
bool TransformExprs (Expr *const *Inputs, unsigned NumInputs, bool IsCall, SmallVectorImpl< Expr * > &Outputs, bool *ArgChanged=nullptr)
Transform the given list of expressions.
Decl * TransformDecl (SourceLocation Loc, Decl *D)
Transform the given declaration, which is referenced from a type or expression.
Sema::ConditionResult TransformCondition (SourceLocation Loc, VarDecl *Var, Expr *Expr, Sema::ConditionKind Kind)
Transform the specified condition.
void transformAttrs (Decl *Old, Decl *New)
Transform the attributes associated with the given declaration and place them on the new declaration.
void transformedLocalDecl (Decl *Old, ArrayRef< Decl * > New)
Note that a local declaration has been transformed by this transformer.
Decl * TransformDefinition (SourceLocation Loc, Decl *D)
Transform the definition of the given declaration.
NamedDecl * TransformFirstQualifierInScope (NamedDecl *D, SourceLocation Loc)
Transform the given declaration, which was the first part of a nested-name-specifier in a member access expression.
bool TransformOverloadExprDecls (OverloadExpr *Old, bool RequiresADL, LookupResult &R)
Transform the set of declarations in an OverloadExpr.
NestedNameSpecifierLoc TransformNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS, QualType ObjectType=QualType(), NamedDecl *FirstQualifierInScope=nullptr)
Transform the given nested-name-specifier with source-location information.
DeclarationNameInfo TransformDeclarationNameInfo (const DeclarationNameInfo &NameInfo)
Transform the given declaration name.
bool TransformRequiresExprRequirements (ArrayRef< concepts::Requirement * > Reqs, llvm::SmallVectorImpl< concepts::Requirement * > &Transformed)
concepts::TypeRequirement * TransformTypeRequirement (concepts::TypeRequirement *Req)
concepts::ExprRequirement * TransformExprRequirement (concepts::ExprRequirement *Req)
concepts::NestedRequirement * TransformNestedRequirement (concepts::NestedRequirement *Req)
TemplateName TransformTemplateName (CXXScopeSpec &SS, TemplateName Name, SourceLocation NameLoc, QualType ObjectType=QualType(), NamedDecl *FirstQualifierInScope=nullptr, bool AllowInjectedClassName=false)
Transform the given template name.
bool TransformTemplateArgument (const TemplateArgumentLoc &Input, TemplateArgumentLoc &Output, bool Uneval=false)
Transform the given template argument.
bool TransformTemplateArguments (const TemplateArgumentLoc *Inputs, unsigned NumInputs, TemplateArgumentListInfo &Outputs, bool Uneval=false)
Transform the given set of template arguments.
template<typename InputIterator >
bool TransformTemplateArguments (InputIterator First, InputIterator Last, TemplateArgumentListInfo &Outputs, bool Uneval=false)
Transform the given set of template arguments.
void InventTemplateArgumentLoc (const TemplateArgument &Arg, TemplateArgumentLoc &ArgLoc)
Fakes up a TemplateArgumentLoc for a given TemplateArgument.
TypeSourceInfo * InventTypeSourceInfo (QualType T)
Fakes up a TypeSourceInfo for a type.
QualType TransformTemplateTypeParmType (TypeLocBuilder &TLB, TemplateTypeParmTypeLoc TL, bool SuppressObjCLifetime)
QualType TransformSubstTemplateTypeParmPackType (TypeLocBuilder &TLB, SubstTemplateTypeParmPackTypeLoc TL, bool SuppressObjCLifetime)
template<typename Fn >
QualType TransformFunctionProtoType (TypeLocBuilder &TLB, FunctionProtoTypeLoc TL, CXXRecordDecl *ThisContext, Qualifiers ThisTypeQuals, Fn TransformExceptionSpec)
bool TransformExceptionSpec (SourceLocation Loc, FunctionProtoType::ExceptionSpecInfo &ESI, SmallVectorImpl< QualType > &Exceptions, bool &Changed)
StmtResult TransformSEHHandler (Stmt *Handler)
QualType TransformTemplateSpecializationType (TypeLocBuilder &TLB, TemplateSpecializationTypeLoc TL, TemplateName Template)
QualType TransformDependentTemplateSpecializationType (TypeLocBuilder &TLB, DependentTemplateSpecializationTypeLoc TL, TemplateName Template, CXXScopeSpec &SS)
QualType TransformDependentTemplateSpecializationType (TypeLocBuilder &TLB, DependentTemplateSpecializationTypeLoc TL, NestedNameSpecifierLoc QualifierLoc)
bool TransformFunctionTypeParams (SourceLocation Loc, ArrayRef< ParmVarDecl * > Params, const QualType *ParamTypes, const FunctionProtoType::ExtParameterInfo *ParamInfos, SmallVectorImpl< QualType > &PTypes, SmallVectorImpl< ParmVarDecl * > *PVars, Sema::ExtParameterInfoBuilder &PInfos, unsigned *LastParamTransformed)
Transforms the parameters of a function type into the given vectors.
bool TransformFunctionTypeParams (SourceLocation Loc, ArrayRef< ParmVarDecl * > Params, const QualType *ParamTypes, const FunctionProtoType::ExtParameterInfo *ParamInfos, SmallVectorImpl< QualType > &PTypes, SmallVectorImpl< ParmVarDecl * > *PVars, Sema::ExtParameterInfoBuilder &PInfos)
ExprResult TransformRequiresTypeParams (SourceLocation KWLoc, SourceLocation RBraceLoc, const RequiresExpr *RE, RequiresExprBodyDecl *Body, ArrayRef< ParmVarDecl * > Params, SmallVectorImpl< QualType > &PTypes, SmallVectorImpl< ParmVarDecl * > &TransParams, Sema::ExtParameterInfoBuilder &PInfos)
Transforms the parameters of a requires expresison into the given vectors.
ParmVarDecl * TransformFunctionTypeParam (ParmVarDecl *OldParm, int indexAdjustment, std::optional< unsigned > NumExpansions, bool ExpectParameterPack)
Transforms a single function-type parameter.
StmtResult TransformLambdaBody (LambdaExpr *E, Stmt *Body)
Transform the body of a lambda-expression.
StmtResult SkipLambdaBody (LambdaExpr *E, Stmt *Body)
Alternative implementation of TransformLambdaBody that skips transforming the body.
QualType TransformReferenceType (TypeLocBuilder &TLB, ReferenceTypeLoc TL)
Transforms a reference type.
StmtResult TransformCompoundStmt (CompoundStmt *S, bool IsStmtExpr)
ExprResult TransformCXXNamedCastExpr (CXXNamedCastExpr *E)
TemplateParameterList * TransformTemplateParameterList (TemplateParameterList *TPL)
ExprResult TransformAddressOfOperand (Expr *E)
The operand of a unary address-of operator has special rules: it's allowed to refer to a non-static member of a class even if there's no 'this' object available.
ExprResult TransformDependentScopeDeclRefExpr (DependentScopeDeclRefExpr *E, bool IsAddressOfOperand, TypeSourceInfo **RecoveryTSI)
ExprResult TransformParenDependentScopeDeclRefExpr (ParenExpr *PE, DependentScopeDeclRefExpr *DRE, bool IsAddressOfOperand, TypeSourceInfo **RecoveryTSI)
StmtResult TransformOMPExecutableDirective (OMPExecutableDirective *S)
QualType RebuildQualifiedType (QualType T, QualifiedTypeLoc TL)
Build a new qualified type given its unqualified type and type location.
QualType RebuildPointerType (QualType PointeeType, SourceLocation Sigil)
Build a new pointer type given its pointee type.
QualType RebuildBlockPointerType (QualType PointeeType, SourceLocation Sigil)
Build a new block pointer type given its pointee type.
QualType RebuildReferenceType (QualType ReferentType, bool LValue, SourceLocation Sigil)
Build a new reference type given the type it references.
QualType RebuildMemberPointerType (QualType PointeeType, QualType ClassType, SourceLocation Sigil)
Build a new member pointer type given the pointee type and the class type it refers into.
QualType RebuildObjCTypeParamType (const ObjCTypeParamDecl *Decl, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
QualType RebuildObjCObjectType (QualType BaseType, SourceLocation Loc, SourceLocation TypeArgsLAngleLoc, ArrayRef< TypeSourceInfo * > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
Build an Objective-C object type.
QualType RebuildObjCObjectPointerType (QualType PointeeType, SourceLocation Star)
Build a new Objective-C object pointer type given the pointee type.
QualType RebuildArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, const llvm::APInt *Size, Expr *SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new array type given the element type, size modifier, size of the array (if known), size expression, and index type qualifiers.
QualType RebuildConstantArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, const llvm::APInt &Size, Expr *SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new constant array type given the element type, size modifier, (known) size of the array, and index type qualifiers.
QualType RebuildIncompleteArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new incomplete array type given the element type, size modifier, and index type qualifiers.
QualType RebuildVariableArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, Expr *SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new variable-length array type given the element type, size modifier, size expression, and index type qualifiers.
QualType RebuildDependentSizedArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, Expr *SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new dependent-sized array type given the element type, size modifier, size expression, and index type qualifiers.
QualType RebuildVectorType (QualType ElementType, unsigned NumElements, VectorType::VectorKind VecKind)
Build a new vector type given the element type and number of elements.
QualType RebuildDependentVectorType (QualType ElementType, Expr *SizeExpr, SourceLocation AttributeLoc, VectorType::VectorKind)
Build a new potentially dependently-sized extended vector type given the element type and number of elements.
QualType RebuildExtVectorType (QualType ElementType, unsigned NumElements, SourceLocation AttributeLoc)
Build a new extended vector type given the element type and number of elements.
QualType RebuildDependentSizedExtVectorType (QualType ElementType, Expr *SizeExpr, SourceLocation AttributeLoc)
Build a new potentially dependently-sized extended vector type given the element type and number of elements.
QualType RebuildConstantMatrixType (QualType ElementType, unsigned NumRows, unsigned NumColumns)
Build a new matrix type given the element type and dimensions.
QualType RebuildDependentSizedMatrixType (QualType ElementType, Expr *RowExpr, Expr *ColumnExpr, SourceLocation AttributeLoc)
Build a new matrix type given the type and dependently-defined dimensions.
QualType RebuildDependentAddressSpaceType (QualType PointeeType, Expr *AddrSpaceExpr, SourceLocation AttributeLoc)
Build a new DependentAddressSpaceType or return the pointee type variable with the correct address space (retrieved from AddrSpaceExpr) applied to it.
QualType RebuildFunctionProtoType (QualType T, MutableArrayRef< QualType > ParamTypes, const FunctionProtoType::ExtProtoInfo &EPI)
Build a new function type.
QualType RebuildFunctionNoProtoType (QualType ResultType)
Build a new unprototyped function type.
QualType RebuildUnresolvedUsingType (SourceLocation NameLoc, Decl *D)
Rebuild an unresolved typename type, given the decl that the UnresolvedUsingTypenameDecl was transformed to.
QualType RebuildUsingType (UsingShadowDecl *Found, QualType Underlying)
Build a new type found via an alias.
QualType RebuildTypedefType (TypedefNameDecl *Typedef)
Build a new typedef type.
QualType RebuildMacroQualifiedType (QualType T, const IdentifierInfo *MacroII)
Build a new MacroDefined type.
QualType RebuildRecordType (RecordDecl *Record)
Build a new class/struct/union type.
QualType RebuildEnumType (EnumDecl *Enum)
Build a new Enum type.
QualType RebuildTypeOfExprType (Expr *Underlying, SourceLocation Loc, TypeOfKind Kind)
Build a new typeof(expr) type.
QualType RebuildTypeOfType (QualType Underlying, TypeOfKind Kind)
Build a new typeof(type) type.
QualType RebuildUnaryTransformType (QualType BaseType, UnaryTransformType::UTTKind UKind, SourceLocation Loc)
Build a new unary transform type.
QualType RebuildDecltypeType (Expr *Underlying, SourceLocation Loc)
Build a new C++11 decltype type.
QualType RebuildAutoType (QualType Deduced, AutoTypeKeyword Keyword, ConceptDecl *TypeConstraintConcept, ArrayRef< TemplateArgument > TypeConstraintArgs)
Build a new C++11 auto type.
QualType RebuildDeducedTemplateSpecializationType (TemplateName Template, QualType Deduced)
By default, builds a new DeducedTemplateSpecializationType with the given deduced type.
QualType RebuildTemplateSpecializationType (TemplateName Template, SourceLocation TemplateLoc, TemplateArgumentListInfo &Args)
Build a new template specialization type.
QualType RebuildParenType (QualType InnerType)
Build a new parenthesized type.
QualType RebuildElaboratedType (SourceLocation KeywordLoc, ElaboratedTypeKeyword Keyword, NestedNameSpecifierLoc QualifierLoc, QualType Named)
Build a new qualified name type.
QualType RebuildDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const IdentifierInfo *Name, SourceLocation NameLoc, TemplateArgumentListInfo &Args, bool AllowInjectedClassName)
Build a new typename type that refers to a template-id.
QualType RebuildDependentNameType (ElaboratedTypeKeyword Keyword, SourceLocation KeywordLoc, NestedNameSpecifierLoc QualifierLoc, const IdentifierInfo *Id, SourceLocation IdLoc, bool DeducedTSTContext)
Build a new typename type that refers to an identifier.
QualType RebuildPackExpansionType (QualType Pattern, SourceRange PatternRange, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions)
Build a new pack expansion type.
QualType RebuildAtomicType (QualType ValueType, SourceLocation KWLoc)
Build a new atomic type given its value type.
QualType RebuildPipeType (QualType ValueType, SourceLocation KWLoc, bool isReadPipe)
Build a new pipe type given its value type.
QualType RebuildBitIntType (bool IsUnsigned, unsigned NumBits, SourceLocation Loc)
Build a bit-precise int given its value type.
QualType RebuildDependentBitIntType (bool IsUnsigned, Expr *NumBitsExpr, SourceLocation Loc)
Build a dependent bit-precise int given its value type.
TemplateName RebuildTemplateName (CXXScopeSpec &SS, bool TemplateKW, TemplateDecl *Template)
Build a new template name given a nested name specifier, a flag indicating whether the "template" keyword was provided, and the template that the template name refers to.
TemplateName RebuildTemplateName (CXXScopeSpec &SS, SourceLocation TemplateKWLoc, const IdentifierInfo &Name, SourceLocation NameLoc, QualType ObjectType, NamedDecl *FirstQualifierInScope, bool AllowInjectedClassName)
Build a new template name given a nested name specifier and the name that is referred to as a template.
TemplateName RebuildTemplateName (CXXScopeSpec &SS, SourceLocation TemplateKWLoc, OverloadedOperatorKind Operator, SourceLocation NameLoc, QualType ObjectType, bool AllowInjectedClassName)
Build a new template name given a nested name specifier and the overloaded operator name that is referred to as a template.
TemplateName RebuildTemplateName (const TemplateArgument &ArgPack, Decl *AssociatedDecl, unsigned Index, bool Final)
Build a new template name given a template template parameter pack and the.
StmtResult RebuildCompoundStmt (SourceLocation LBraceLoc, MultiStmtArg Statements, SourceLocation RBraceLoc, bool IsStmtExpr)
Build a new compound statement.
StmtResult RebuildCaseStmt (SourceLocation CaseLoc, Expr *LHS, SourceLocation EllipsisLoc, Expr *RHS, SourceLocation ColonLoc)
Build a new case statement.
StmtResult RebuildCaseStmtBody (Stmt *S, Stmt *Body)
Attach the body to a new case statement.
StmtResult RebuildDefaultStmt (SourceLocation DefaultLoc, SourceLocation ColonLoc, Stmt *SubStmt)
Build a new default statement.
StmtResult RebuildLabelStmt (SourceLocation IdentLoc, LabelDecl *L, SourceLocation ColonLoc, Stmt *SubStmt)
Build a new label statement.
StmtResult RebuildAttributedStmt (SourceLocation AttrLoc, ArrayRef< const Attr * > Attrs, Stmt *SubStmt)
Build a new attributed statement.
StmtResult RebuildIfStmt (SourceLocation IfLoc, IfStatementKind Kind, SourceLocation LParenLoc, Sema::ConditionResult Cond, SourceLocation RParenLoc, Stmt *Init, Stmt *Then, SourceLocation ElseLoc, Stmt *Else)
Build a new "if" statement.
StmtResult RebuildSwitchStmtStart (SourceLocation SwitchLoc, SourceLocation LParenLoc, Stmt *Init, Sema::ConditionResult Cond, SourceLocation RParenLoc)
Start building a new switch statement.
StmtResult RebuildSwitchStmtBody (SourceLocation SwitchLoc, Stmt *Switch, Stmt *Body)
Attach the body to the switch statement.
StmtResult RebuildWhileStmt (SourceLocation WhileLoc, SourceLocation LParenLoc, Sema::ConditionResult Cond, SourceLocation RParenLoc, Stmt *Body)
Build a new while statement.
StmtResult RebuildDoStmt (SourceLocation DoLoc, Stmt *Body, SourceLocation WhileLoc, SourceLocation LParenLoc, Expr *Cond, SourceLocation RParenLoc)
Build a new do-while statement.
StmtResult RebuildForStmt (SourceLocation ForLoc, SourceLocation LParenLoc, Stmt *Init, Sema::ConditionResult Cond, Sema::FullExprArg Inc, SourceLocation RParenLoc, Stmt *Body)
Build a new for statement.
StmtResult RebuildGotoStmt (SourceLocation GotoLoc, SourceLocation LabelLoc, LabelDecl *Label)
Build a new goto statement.
StmtResult RebuildIndirectGotoStmt (SourceLocation GotoLoc, SourceLocation StarLoc, Expr *Target)
Build a new indirect goto statement.
StmtResult RebuildReturnStmt (SourceLocation ReturnLoc, Expr *Result)
Build a new return statement.
StmtResult RebuildDeclStmt (MutableArrayRef< Decl * > Decls, SourceLocation StartLoc, SourceLocation EndLoc)
Build a new declaration statement.
StmtResult RebuildGCCAsmStmt (SourceLocation AsmLoc, bool IsSimple, bool IsVolatile, unsigned NumOutputs, unsigned NumInputs, IdentifierInfo **Names, MultiExprArg Constraints, MultiExprArg Exprs, Expr *AsmString, MultiExprArg Clobbers, unsigned NumLabels, SourceLocation RParenLoc)
Build a new inline asm statement.
StmtResult RebuildMSAsmStmt (SourceLocation AsmLoc, SourceLocation LBraceLoc, ArrayRef< Token > AsmToks, StringRef AsmString, unsigned NumOutputs, unsigned NumInputs, ArrayRef< StringRef > Constraints, ArrayRef< StringRef > Clobbers, ArrayRef< Expr * > Exprs, SourceLocation EndLoc)
Build a new MS style inline asm statement.
StmtResult RebuildCoreturnStmt (SourceLocation CoreturnLoc, Expr *Result, bool IsImplicit)
Build a new co_return statement.
ExprResult RebuildCoawaitExpr (SourceLocation CoawaitLoc, Expr *Operand, UnresolvedLookupExpr *OpCoawaitLookup, bool IsImplicit)
Build a new co_await expression.
ExprResult RebuildDependentCoawaitExpr (SourceLocation CoawaitLoc, Expr *Result, UnresolvedLookupExpr *Lookup)
Build a new co_await expression.
ExprResult RebuildCoyieldExpr (SourceLocation CoyieldLoc, Expr *Result)
Build a new co_yield expression.
StmtResult RebuildCoroutineBodyStmt (CoroutineBodyStmt::CtorArgs Args)
StmtResult RebuildObjCAtTryStmt (SourceLocation AtLoc, Stmt *TryBody, MultiStmtArg CatchStmts, Stmt *Finally)
Build a new Objective-C @try statement.
VarDecl * RebuildObjCExceptionDecl (VarDecl *ExceptionDecl, TypeSourceInfo *TInfo, QualType T)
Rebuild an Objective-C exception declaration.
StmtResult RebuildObjCAtCatchStmt (SourceLocation AtLoc, SourceLocation RParenLoc, VarDecl *Var, Stmt *Body)
Build a new Objective-C @catch statement.
StmtResult RebuildObjCAtFinallyStmt (SourceLocation AtLoc, Stmt *Body)
Build a new Objective-C @finally statement.
StmtResult RebuildObjCAtThrowStmt (SourceLocation AtLoc, Expr *Operand)
Build a new Objective-C @throw statement.
StmtResult RebuildOMPCanonicalLoop (Stmt *LoopStmt)
Build a new OpenMP Canonical loop.
StmtResult RebuildOMPExecutableDirective (OpenMPDirectiveKind Kind, DeclarationNameInfo DirName, OpenMPDirectiveKind CancelRegion, ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Build a new OpenMP executable directive.
OMPClause * RebuildOMPIfClause (OpenMPDirectiveKind NameModifier, Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Build a new OpenMP 'if' clause.
OMPClause * RebuildOMPFinalClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'final' clause.
OMPClause * RebuildOMPNumThreadsClause (Expr *NumThreads, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'num_threads' clause.
OMPClause * RebuildOMPSafelenClause (Expr *Len, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'safelen' clause.
OMPClause * RebuildOMPSimdlenClause (Expr *Len, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'simdlen' clause.
OMPClause * RebuildOMPSizesClause (ArrayRef< Expr * > Sizes, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPClause * RebuildOMPFullClause (SourceLocation StartLoc, SourceLocation EndLoc)
Build a new OpenMP 'full' clause.
OMPClause * RebuildOMPPartialClause (Expr *Factor, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'partial' clause.
OMPClause * RebuildOMPAllocatorClause (Expr *A, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'allocator' clause.
OMPClause * RebuildOMPCollapseClause (Expr *Num, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'collapse' clause.
OMPClause * RebuildOMPDefaultClause (DefaultKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'default' clause.
OMPClause * RebuildOMPProcBindClause (ProcBindKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'proc_bind' clause.
OMPClause * RebuildOMPScheduleClause (OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, OpenMPScheduleClauseKind Kind, Expr *ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation M1Loc, SourceLocation M2Loc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Build a new OpenMP 'schedule' clause.
OMPClause * RebuildOMPOrderedClause (SourceLocation StartLoc, SourceLocation EndLoc, SourceLocation LParenLoc, Expr *Num)
Build a new OpenMP 'ordered' clause.
OMPClause * RebuildOMPPrivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'private' clause.
OMPClause * RebuildOMPFirstprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'firstprivate' clause.
OMPClause * RebuildOMPLastprivateClause (ArrayRef< Expr * > VarList, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'lastprivate' clause.
OMPClause * RebuildOMPSharedClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'shared' clause.
OMPClause * RebuildOMPReductionClause (ArrayRef< Expr * > VarList, OpenMPReductionClauseModifier Modifier, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions)
Build a new OpenMP 'reduction' clause.
OMPClause * RebuildOMPTaskReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions)
Build a new OpenMP 'task_reduction' clause.
OMPClause * RebuildOMPInReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions)
Build a new OpenMP 'in_reduction' clause.
OMPClause * RebuildOMPLinearClause (ArrayRef< Expr * > VarList, Expr *Step, SourceLocation StartLoc, SourceLocation LParenLoc, OpenMPLinearClauseKind Modifier, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Build a new OpenMP 'linear' clause.
OMPClause * RebuildOMPAlignedClause (ArrayRef< Expr * > VarList, Expr *Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Build a new OpenMP 'aligned' clause.
OMPClause * RebuildOMPCopyinClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'copyin' clause.
OMPClause * RebuildOMPCopyprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'copyprivate' clause.
OMPClause * RebuildOMPFlushClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'flush' pseudo clause.
OMPClause * RebuildOMPDepobjClause (Expr *Depobj, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'depobj' pseudo clause.
OMPClause * RebuildOMPDependClause (OMPDependClause::DependDataTy Data, Expr *DepModifier, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'depend' pseudo clause.
OMPClause * RebuildOMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr *Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Build a new OpenMP 'device' clause.
OMPClause * RebuildOMPMapClause (Expr *IteratorModifier, ArrayRef< OpenMPMapModifierKind > MapTypeModifiers, ArrayRef< SourceLocation > MapTypeModifiersLoc, CXXScopeSpec MapperIdScopeSpec, DeclarationNameInfo MapperId, OpenMPMapClauseKind MapType, bool IsMapTypeImplicit, SourceLocation MapLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, ArrayRef< Expr * > UnresolvedMappers)
Build a new OpenMP 'map' clause.
OMPClause * RebuildOMPAllocateClause (Expr *Allocate, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Build a new OpenMP 'allocate' clause.
OMPClause * RebuildOMPNumTeamsClause (Expr *NumTeams, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'num_teams' clause.
OMPClause * RebuildOMPThreadLimitClause (Expr *ThreadLimit, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'thread_limit' clause.
OMPClause * RebuildOMPPriorityClause (Expr *Priority, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'priority' clause.
OMPClause * RebuildOMPGrainsizeClause (OpenMPGrainsizeClauseModifier Modifier, Expr *Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Build a new OpenMP 'grainsize' clause.
OMPClause * RebuildOMPNumTasksClause (OpenMPNumTasksClauseModifier Modifier, Expr *NumTasks, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Build a new OpenMP 'num_tasks' clause.
OMPClause * RebuildOMPHintClause (Expr *Hint, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'hint' clause.
OMPClause * RebuildOMPDetachClause (Expr *Evt, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'detach' clause.
OMPClause * RebuildOMPDistScheduleClause (OpenMPDistScheduleClauseKind Kind, Expr *ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Build a new OpenMP 'dist_schedule' clause.
OMPClause * RebuildOMPToClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, ArrayRef< Expr * > UnresolvedMappers)
Build a new OpenMP 'to' clause.
OMPClause * RebuildOMPFromClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, ArrayRef< Expr * > UnresolvedMappers)
Build a new OpenMP 'from' clause.
OMPClause * RebuildOMPUseDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Build a new OpenMP 'use_device_ptr' clause.
OMPClause * RebuildOMPUseDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Build a new OpenMP 'use_device_addr' clause.
OMPClause * RebuildOMPIsDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Build a new OpenMP 'is_device_ptr' clause.
OMPClause * RebuildOMPHasDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Build a new OpenMP 'has_device_addr' clause.
OMPClause * RebuildOMPDefaultmapClause (OpenMPDefaultmapClauseModifier M, OpenMPDefaultmapClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc)
Build a new OpenMP 'defaultmap' clause.
OMPClause * RebuildOMPNontemporalClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'nontemporal' clause.
OMPClause * RebuildOMPInclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'inclusive' clause.
OMPClause * RebuildOMPExclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'exclusive' clause.
OMPClause * RebuildOMPUsesAllocatorsClause (ArrayRef< Sema::UsesAllocatorsData > Data, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'uses_allocators' clause.
OMPClause * RebuildOMPAffinityClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, Expr *Modifier, ArrayRef< Expr * > Locators)
Build a new OpenMP 'affinity' clause.
OMPClause * RebuildOMPOrderClause (OpenMPOrderClauseKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, OpenMPOrderClauseModifier Modifier, SourceLocation ModifierKwLoc)
Build a new OpenMP 'order' clause.
OMPClause * RebuildOMPInitClause (Expr *InteropVar, OMPInteropInfo &InteropInfo, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Build a new OpenMP 'init' clause.
OMPClause * RebuildOMPUseClause (Expr *InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Build a new OpenMP 'use' clause.
OMPClause * RebuildOMPDestroyClause (Expr *InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Build a new OpenMP 'destroy' clause.
OMPClause * RebuildOMPNovariantsClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'novariants' clause.
OMPClause * RebuildOMPNocontextClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'nocontext' clause.
OMPClause * RebuildOMPFilterClause (Expr *ThreadID, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'filter' clause.
OMPClause * RebuildOMPBindClause (OpenMPBindClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'bind' clause.
OMPClause * RebuildOMPXDynCGroupMemClause (Expr *Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'ompx_dyn_cgroup_mem' clause.
OMPClause * RebuildOMPAlignClause (Expr *A, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'align' clause.
OMPClause * RebuildOMPAtClause (OpenMPAtClauseKind Kind, SourceLocation KwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'at' clause.
OMPClause * RebuildOMPSeverityClause (OpenMPSeverityClauseKind Kind, SourceLocation KwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'severity' clause.
OMPClause * RebuildOMPMessageClause (Expr *MS, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'message' clause.
OMPClause * RebuildOMPDoacrossClause (OpenMPDoacrossClauseModifier DepType, SourceLocation DepLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build a new OpenMP 'doacross' clause.
ExprResult RebuildObjCAtSynchronizedOperand (SourceLocation atLoc, Expr *object)
Rebuild the operand to an Objective-C @synchronized statement.
StmtResult RebuildObjCAtSynchronizedStmt (SourceLocation AtLoc, Expr *Object, Stmt *Body)
Build a new Objective-C @synchronized statement.
StmtResult RebuildObjCAutoreleasePoolStmt (SourceLocation AtLoc, Stmt *Body)
Build a new Objective-C @autoreleasepool statement.
StmtResult RebuildObjCForCollectionStmt (SourceLocation ForLoc, Stmt *Element, Expr *Collection, SourceLocation RParenLoc, Stmt *Body)
Build a new Objective-C fast enumeration statement.
VarDecl * RebuildExceptionDecl (VarDecl *ExceptionDecl, TypeSourceInfo *Declarator, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id)
Build a new C++ exception declaration.
StmtResult RebuildCXXCatchStmt (SourceLocation CatchLoc, VarDecl *ExceptionDecl, Stmt *Handler)
Build a new C++ catch statement.
StmtResult RebuildCXXTryStmt (SourceLocation TryLoc, Stmt *TryBlock, ArrayRef< Stmt * > Handlers)
Build a new C++ try statement.
StmtResult RebuildCXXForRangeStmt (SourceLocation ForLoc, SourceLocation CoawaitLoc, Stmt *Init, SourceLocation ColonLoc, Stmt *Range, Stmt *Begin, Stmt *End, Expr *Cond, Expr *Inc, Stmt *LoopVar, SourceLocation RParenLoc)
Build a new C++0x range-based for statement.
StmtResult RebuildMSDependentExistsStmt (SourceLocation KeywordLoc, bool IsIfExists, NestedNameSpecifierLoc QualifierLoc, DeclarationNameInfo NameInfo, Stmt *Nested)
Build a new C++0x range-based for statement.
StmtResult FinishCXXForRangeStmt (Stmt *ForRange, Stmt *Body)
Attach body to a C++0x range-based for statement.
StmtResult RebuildSEHTryStmt (bool IsCXXTry, SourceLocation TryLoc, Stmt *TryBlock, Stmt *Handler)
StmtResult RebuildSEHExceptStmt (SourceLocation Loc, Expr *FilterExpr, Stmt *Block)
StmtResult RebuildSEHFinallyStmt (SourceLocation Loc, Stmt *Block)
ExprResult RebuildSYCLUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, TypeSourceInfo *TSI)
ExprResult RebuildPredefinedExpr (SourceLocation Loc, PredefinedExpr::IdentKind IK)
Build a new predefined expression.
ExprResult RebuildDeclarationNameExpr (const CXXScopeSpec &SS, LookupResult &R, bool RequiresADL)
Build a new expression that references a declaration.
ExprResult RebuildDeclRefExpr (NestedNameSpecifierLoc QualifierLoc, ValueDecl *VD, const DeclarationNameInfo &NameInfo, NamedDecl *Found, TemplateArgumentListInfo *TemplateArgs)
Build a new expression that references a declaration.
ExprResult RebuildParenExpr (Expr *SubExpr, SourceLocation LParen, SourceLocation RParen)
Build a new expression in parentheses.
ExprResult RebuildCXXPseudoDestructorExpr (Expr *Base, SourceLocation OperatorLoc, bool isArrow, CXXScopeSpec &SS, TypeSourceInfo *ScopeType, SourceLocation CCLoc, SourceLocation TildeLoc, PseudoDestructorTypeStorage Destroyed)
Build a new pseudo-destructor expression.
ExprResult RebuildUnaryOperator (SourceLocation OpLoc, UnaryOperatorKind Opc, Expr *SubExpr)
Build a new unary operator expression.
ExprResult RebuildOffsetOfExpr (SourceLocation OperatorLoc, TypeSourceInfo *Type, ArrayRef< Sema::OffsetOfComponent > Components, SourceLocation RParenLoc)
Build a new builtin offsetof expression.
ExprResult RebuildUnaryExprOrTypeTrait (TypeSourceInfo *TInfo, SourceLocation OpLoc, UnaryExprOrTypeTrait ExprKind, SourceRange R)
Build a new sizeof, alignof or vec_step expression with a type argument.
ExprResult RebuildUnaryExprOrTypeTrait (Expr *SubExpr, SourceLocation OpLoc, UnaryExprOrTypeTrait ExprKind, SourceRange R)
Build a new sizeof, alignof or vec step expression with an expression argument.
ExprResult RebuildArraySubscriptExpr (Expr *LHS, SourceLocation LBracketLoc, Expr *RHS, SourceLocation RBracketLoc)
Build a new array subscript expression.
ExprResult RebuildMatrixSubscriptExpr (Expr *Base, Expr *RowIdx, Expr *ColumnIdx, SourceLocation RBracketLoc)
Build a new matrix subscript expression.
ExprResult RebuildOMPArraySectionExpr (Expr *Base, SourceLocation LBracketLoc, Expr *LowerBound, SourceLocation ColonLocFirst, SourceLocation ColonLocSecond, Expr *Length, Expr *Stride, SourceLocation RBracketLoc)
Build a new array section expression.
ExprResult RebuildOMPArrayShapingExpr (Expr *Base, SourceLocation LParenLoc, SourceLocation RParenLoc, ArrayRef< Expr * > Dims, ArrayRef< SourceRange > BracketsRanges)
Build a new array shaping expression.
ExprResult RebuildOMPIteratorExpr (SourceLocation IteratorKwLoc, SourceLocation LLoc, SourceLocation RLoc, ArrayRef< Sema::OMPIteratorData > Data)
Build a new iterator expression.
ExprResult RebuildCallExpr (Expr *Callee, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc, Expr *ExecConfig=nullptr)
Build a new call expression.
ExprResult RebuildCxxSubscriptExpr (Expr *Callee, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc)
ExprResult RebuildMemberExpr (Expr *Base, SourceLocation OpLoc, bool isArrow, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const DeclarationNameInfo &MemberNameInfo, ValueDecl *Member, NamedDecl *FoundDecl, const TemplateArgumentListInfo *ExplicitTemplateArgs, NamedDecl *FirstQualifierInScope)
Build a new member access expression.
ExprResult RebuildBinaryOperator (SourceLocation OpLoc, BinaryOperatorKind Opc, Expr *LHS, Expr *RHS)
Build a new binary operator expression.
ExprResult RebuildCXXRewrittenBinaryOperator (SourceLocation OpLoc, BinaryOperatorKind Opcode, const UnresolvedSetImpl &UnqualLookups, Expr *LHS, Expr *RHS)
Build a new rewritten operator expression.
ExprResult RebuildConditionalOperator (Expr *Cond, SourceLocation QuestionLoc, Expr *LHS, SourceLocation ColonLoc, Expr *RHS)
Build a new conditional operator expression.
ExprResult RebuildCStyleCastExpr (SourceLocation LParenLoc, TypeSourceInfo *TInfo, SourceLocation RParenLoc, Expr *SubExpr)
Build a new C-style cast expression.
ExprResult RebuildCompoundLiteralExpr (SourceLocation LParenLoc, TypeSourceInfo *TInfo, SourceLocation RParenLoc, Expr *Init)
Build a new compound literal expression.
ExprResult RebuildExtVectorElementExpr (Expr *Base, SourceLocation OpLoc, bool IsArrow, SourceLocation AccessorLoc, IdentifierInfo &Accessor)
Build a new extended vector element access expression.
ExprResult RebuildInitList (SourceLocation LBraceLoc, MultiExprArg Inits, SourceLocation RBraceLoc)
Build a new initializer list expression.
ExprResult RebuildDesignatedInitExpr (Designation &Desig, MultiExprArg ArrayExprs, SourceLocation EqualOrColonLoc, bool GNUSyntax, Expr *Init)
Build a new designated initializer expression.
ExprResult RebuildImplicitValueInitExpr (QualType T)
Build a new value-initialized expression.
ExprResult RebuildVAArgExpr (SourceLocation BuiltinLoc, Expr *SubExpr, TypeSourceInfo *TInfo, SourceLocation RParenLoc)
Build a new va_arg expression.
ExprResult RebuildParenListExpr (SourceLocation LParenLoc, MultiExprArg SubExprs, SourceLocation RParenLoc)
Build a new expression list in parentheses.
ExprResult RebuildAddrLabelExpr (SourceLocation AmpAmpLoc, SourceLocation LabelLoc, LabelDecl *Label)
Build a new address-of-label expression.
ExprResult RebuildStmtExpr (SourceLocation LParenLoc, Stmt *SubStmt, SourceLocation RParenLoc, unsigned TemplateDepth)
Build a new GNU statement expression.
ExprResult RebuildChooseExpr (SourceLocation BuiltinLoc, Expr *Cond, Expr *LHS, Expr *RHS, SourceLocation RParenLoc)
Build a new __builtin_choose_expr expression.
ExprResult RebuildGenericSelectionExpr (SourceLocation KeyLoc, SourceLocation DefaultLoc, SourceLocation RParenLoc, Expr *ControllingExpr, ArrayRef< TypeSourceInfo * > Types, ArrayRef< Expr * > Exprs)
Build a new generic selection expression with an expression predicate.
ExprResult RebuildGenericSelectionExpr (SourceLocation KeyLoc, SourceLocation DefaultLoc, SourceLocation RParenLoc, TypeSourceInfo *ControllingType, ArrayRef< TypeSourceInfo * > Types, ArrayRef< Expr * > Exprs)
Build a new generic selection expression with a type predicate.
ExprResult RebuildCXXOperatorCallExpr (OverloadedOperatorKind Op, SourceLocation OpLoc, SourceLocation CalleeLoc, bool RequiresADL, const UnresolvedSetImpl &Functions, Expr *First, Expr *Second)
Build a new overloaded operator call expression.
ExprResult RebuildCXXNamedCastExpr (SourceLocation OpLoc, Stmt::StmtClass Class, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
Build a new C++ "named" cast expression, such as static_cast or reinterpret_cast.
ExprResult RebuildCXXStaticCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
Build a new C++ static_cast expression.
ExprResult RebuildCXXDynamicCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
Build a new C++ dynamic_cast expression.
ExprResult RebuildCXXReinterpretCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
Build a new C++ reinterpret_cast expression.
ExprResult RebuildCXXConstCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
Build a new C++ const_cast expression.
ExprResult RebuildCXXAddrspaceCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo *TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr *SubExpr, SourceLocation RParenLoc)
ExprResult RebuildCXXFunctionalCastExpr (TypeSourceInfo *TInfo, SourceLocation LParenLoc, Expr *Sub, SourceLocation RParenLoc, bool ListInitialization)
Build a new C++ functional-style cast expression.
ExprResult RebuildBuiltinBitCastExpr (SourceLocation KWLoc, TypeSourceInfo *TSI, Expr *Sub, SourceLocation RParenLoc)
Build a new C++ __builtin_bit_cast expression.
ExprResult RebuildCXXTypeidExpr (QualType TypeInfoType, SourceLocation TypeidLoc, TypeSourceInfo *Operand, SourceLocation RParenLoc)
Build a new C++ typeid(type) expression.
ExprResult RebuildCXXTypeidExpr (QualType TypeInfoType, SourceLocation TypeidLoc, Expr *Operand, SourceLocation RParenLoc)
Build a new C++ typeid(expr) expression.
ExprResult RebuildCXXUuidofExpr (QualType Type, SourceLocation TypeidLoc, TypeSourceInfo *Operand, SourceLocation RParenLoc)
Build a new C++ __uuidof(type) expression.
ExprResult RebuildCXXUuidofExpr (QualType Type, SourceLocation TypeidLoc, Expr *Operand, SourceLocation RParenLoc)
Build a new C++ __uuidof(expr) expression.
ExprResult RebuildCXXThisExpr (SourceLocation ThisLoc, QualType ThisType, bool isImplicit)
Build a new C++ "this" expression.
ExprResult RebuildCXXThrowExpr (SourceLocation ThrowLoc, Expr *Sub, bool IsThrownVariableInScope)
Build a new C++ throw expression.
ExprResult RebuildCXXDefaultArgExpr (SourceLocation Loc, ParmVarDecl *Param, Expr *RewrittenExpr)
Build a new C++ default-argument expression.
ExprResult RebuildCXXDefaultInitExpr (SourceLocation Loc, FieldDecl *Field)
Build a new C++11 default-initialization expression.
ExprResult RebuildCXXScalarValueInitExpr (TypeSourceInfo *TSInfo, SourceLocation LParenLoc, SourceLocation RParenLoc)
Build a new C++ zero-initialization expression.
ExprResult RebuildCXXNewExpr (SourceLocation StartLoc, bool UseGlobal, SourceLocation PlacementLParen, MultiExprArg PlacementArgs, SourceLocation PlacementRParen, SourceRange TypeIdParens, QualType AllocatedType, TypeSourceInfo *AllocatedTypeInfo, std::optional< Expr * > ArraySize, SourceRange DirectInitRange, Expr *Initializer)
Build a new C++ "new" expression.
ExprResult RebuildCXXDeleteExpr (SourceLocation StartLoc, bool IsGlobalDelete, bool IsArrayForm, Expr *Operand)
Build a new C++ "delete" expression.
ExprResult RebuildTypeTrait (TypeTrait Trait, SourceLocation StartLoc, ArrayRef< TypeSourceInfo * > Args, SourceLocation RParenLoc)
Build a new type trait expression.
ExprResult RebuildArrayTypeTrait (ArrayTypeTrait Trait, SourceLocation StartLoc, TypeSourceInfo *TSInfo, Expr *DimExpr, SourceLocation RParenLoc)
Build a new array type trait expression.
ExprResult RebuildExpressionTrait (ExpressionTrait Trait, SourceLocation StartLoc, Expr *Queried, SourceLocation RParenLoc)
Build a new expression trait expression.
ExprResult RebuildDependentScopeDeclRefExpr (NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const DeclarationNameInfo &NameInfo, const TemplateArgumentListInfo *TemplateArgs, bool IsAddressOfOperand, TypeSourceInfo **RecoveryTSI)
Build a new (previously unresolved) declaration reference expression.
ExprResult RebuildTemplateIdExpr (const CXXScopeSpec &SS, SourceLocation TemplateKWLoc, LookupResult &R, bool RequiresADL, const TemplateArgumentListInfo *TemplateArgs)
Build a new template-id expression.
ExprResult RebuildCXXConstructExpr (QualType T, SourceLocation Loc, CXXConstructorDecl *Constructor, bool IsElidable, MultiExprArg Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool RequiresZeroInit, CXXConstructExpr::ConstructionKind ConstructKind, SourceRange ParenRange)
Build a new object-construction expression.
ExprResult RebuildCXXInheritedCtorInitExpr (QualType T, SourceLocation Loc, CXXConstructorDecl *Constructor, bool ConstructsVBase, bool InheritedFromVBase)
Build a new implicit construction via inherited constructor expression.
ExprResult RebuildCXXTemporaryObjectExpr (TypeSourceInfo *TSInfo, SourceLocation LParenOrBraceLoc, MultiExprArg Args, SourceLocation RParenOrBraceLoc, bool ListInitialization)
Build a new object-construction expression.
ExprResult RebuildCXXUnresolvedConstructExpr (TypeSourceInfo *TSInfo, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc, bool ListInitialization)
Build a new object-construction expression.
ExprResult RebuildCXXDependentScopeMemberExpr (Expr *BaseE, QualType BaseType, bool IsArrow, SourceLocation OperatorLoc, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, NamedDecl *FirstQualifierInScope, const DeclarationNameInfo &MemberNameInfo, const TemplateArgumentListInfo *TemplateArgs)
Build a new member reference expression.
ExprResult RebuildUnresolvedMemberExpr (Expr *BaseE, QualType BaseType, SourceLocation OperatorLoc, bool IsArrow, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, NamedDecl *FirstQualifierInScope, LookupResult &R, const TemplateArgumentListInfo *TemplateArgs)
Build a new member reference expression.
ExprResult RebuildCXXNoexceptExpr (SourceRange Range, Expr *Arg)
Build a new noexcept expression.
ExprResult RebuildSizeOfPackExpr (SourceLocation OperatorLoc, NamedDecl *Pack, SourceLocation PackLoc, SourceLocation RParenLoc, std::optional< unsigned > Length, ArrayRef< TemplateArgument > PartialArgs)
Build a new expression to compute the length of a parameter pack.
ExprResult RebuildSourceLocExpr (SourceLocExpr::IdentKind Kind, QualType ResultTy, SourceLocation BuiltinLoc, SourceLocation RPLoc, DeclContext *ParentContext)
Build a new expression representing a call to a source location builtin.
ExprResult RebuildConceptSpecializationExpr (NestedNameSpecifierLoc NNS, SourceLocation TemplateKWLoc, DeclarationNameInfo ConceptNameInfo, NamedDecl *FoundDecl, ConceptDecl *NamedConcept, TemplateArgumentListInfo *TALI)
Build a new Objective-C boxed expression.
ExprResult RebuildRequiresExpr (SourceLocation RequiresKWLoc, RequiresExprBodyDecl *Body, ArrayRef< ParmVarDecl * > LocalParameters, ArrayRef< concepts::Requirement * > Requirements, SourceLocation ClosingBraceLoc)
Build a new requires expression.
concepts::TypeRequirement * RebuildTypeRequirement (concepts::Requirement::SubstitutionDiagnostic *SubstDiag)
concepts::TypeRequirement * RebuildTypeRequirement (TypeSourceInfo *T)
concepts::ExprRequirement * RebuildExprRequirement (concepts::Requirement::SubstitutionDiagnostic *SubstDiag, bool IsSimple, SourceLocation NoexceptLoc, concepts::ExprRequirement::ReturnTypeRequirement Ret)
concepts::ExprRequirement * RebuildExprRequirement (Expr *E, bool IsSimple, SourceLocation NoexceptLoc, concepts::ExprRequirement::ReturnTypeRequirement Ret)
concepts::NestedRequirement * RebuildNestedRequirement (StringRef InvalidConstraintEntity, const ASTConstraintSatisfaction &Satisfaction)
concepts::NestedRequirement * RebuildNestedRequirement (Expr *Constraint)
ExprResult RebuildObjCBoxedExpr (SourceRange SR, Expr *ValueExpr)
Build a new Objective-C boxed expression.
ExprResult RebuildObjCArrayLiteral (SourceRange Range, Expr **Elements, unsigned NumElements)
Build a new Objective-C array literal.
ExprResult RebuildObjCSubscriptRefExpr (SourceLocation RB, Expr *Base, Expr *Key, ObjCMethodDecl *getterMethod, ObjCMethodDecl *setterMethod)
ExprResult RebuildObjCDictionaryLiteral (SourceRange Range, MutableArrayRef< ObjCDictionaryElement > Elements)
Build a new Objective-C dictionary literal.
ExprResult RebuildObjCEncodeExpr (SourceLocation AtLoc, TypeSourceInfo *EncodeTypeInfo, SourceLocation RParenLoc)
Build a new Objective-C @encode expression.
ExprResult RebuildObjCMessageExpr (TypeSourceInfo *ReceiverTypeInfo, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl *Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc)
Build a new Objective-C class message.
ExprResult RebuildObjCMessageExpr (Expr *Receiver, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl *Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc)
Build a new Objective-C instance message.
ExprResult RebuildObjCMessageExpr (SourceLocation SuperLoc, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, QualType SuperType, ObjCMethodDecl *Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc)
Build a new Objective-C instance/class message to 'super'.
ExprResult RebuildObjCIvarRefExpr (Expr *BaseArg, ObjCIvarDecl *Ivar, SourceLocation IvarLoc, bool IsArrow, bool IsFreeIvar)
Build a new Objective-C ivar reference expression.
ExprResult RebuildObjCPropertyRefExpr (Expr *BaseArg, ObjCPropertyDecl *Property, SourceLocation PropertyLoc)
Build a new Objective-C property reference expression.
ExprResult RebuildObjCPropertyRefExpr (Expr *Base, QualType T, ObjCMethodDecl *Getter, ObjCMethodDecl *Setter, SourceLocation PropertyLoc)
Build a new Objective-C property reference expression.
ExprResult RebuildObjCIsaExpr (Expr *BaseArg, SourceLocation IsaLoc, SourceLocation OpLoc, bool IsArrow)
Build a new Objective-C "isa" expression.
ExprResult RebuildShuffleVectorExpr (SourceLocation BuiltinLoc, MultiExprArg SubExprs, SourceLocation RParenLoc)
Build a new shuffle vector expression.
ExprResult RebuildConvertVectorExpr (SourceLocation BuiltinLoc, Expr *SrcExpr, TypeSourceInfo *DstTInfo, SourceLocation RParenLoc)
Build a new convert vector expression.
TemplateArgumentLoc RebuildPackExpansion (TemplateArgumentLoc Pattern, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions)
Build a new template argument pack expansion.
ExprResult RebuildPackExpansion (Expr *Pattern, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions)
Build a new expression pack expansion.
ExprResult RebuildCXXFoldExpr (UnresolvedLookupExpr *ULE, SourceLocation LParenLoc, Expr *LHS, BinaryOperatorKind Operator, SourceLocation EllipsisLoc, Expr *RHS, SourceLocation RParenLoc, std::optional< unsigned > NumExpansions)
Build a new C++1z fold-expression.
ExprResult RebuildEmptyCXXFoldExpr (SourceLocation EllipsisLoc, BinaryOperatorKind Operator)
Build an empty C++1z fold-expression with the given operator.
ExprResult RebuildAtomicExpr (SourceLocation BuiltinLoc, MultiExprArg SubExprs, AtomicExpr::AtomicOp Op, SourceLocation RParenLoc)
Build a new atomic operation expression.
ExprResult RebuildRecoveryExpr (SourceLocation BeginLoc, SourceLocation EndLoc, ArrayRef< Expr * > SubExprs, QualType Type)
template<typename Derived >
QualType TransformFunctionProtoType (TypeLocBuilder &TLB, FunctionProtoTypeLoc TL)
QualType TransformTypeWithDeducedTST (QualType T)
Transform a type that is permitted to produce a DeducedTemplateSpecializationType.
TypeSourceInfo * TransformTypeWithDeducedTST (TypeSourceInfo *DI)
Static Public Member Functions
static ExprResult Owned (Expr *E)
static StmtResult Owned (Stmt *S)
Protected Attributes
Sema & SemaRef
llvm::DenseMap< Decl *, Decl * > TransformedLocalDecls
The set of local declarations that have been transformed, for cases where we are forced to build new declarations within the transformer rather than in the subclass (e.g., lambda closure types).
Detailed Description
template<typename Derived>
class clang::TreeTransform< Derived >
A semantic tree transformation that allows one to transform one abstract syntax tree into another.
A new tree transformation is defined by creating a new subclass X of TreeTransform<X> and then overriding certain operations to provide behavior specific to that transformation. For example, template instantiation is implemented as a tree transformation where the transformation of TemplateTypeParmType nodes involves substituting the template arguments for their corresponding template parameters; a similar transformation is performed for non-type template parameters and template template parameters.
This tree-transformation template uses static polymorphism to allow subclasses to customize any of its operations. Thus, a subclass can override any of the transformation or rebuild operators by providing an operation with the same signature as the default implementation. The overriding function should not be virtual.
Semantic tree transformations are split into two stages, either of which can be replaced by a subclass. The "transform" step transforms an AST node or the parts of an AST node using the various transformation functions, then passes the pieces on to the "rebuild" step, which constructs a new AST node of the appropriate kind from the pieces. The default transformation routines recursively transform the operands to composite AST nodes (e.g., the pointee type of a PointerType node) and, if any of those operand nodes were changed by the transformation, invokes the rebuild operation to create a new AST node.
Subclasses can customize the transformation at various levels. The most coarse-grained transformations involve replacing TransformType(), TransformExpr(), TransformDecl(), TransformNestedNameSpecifierLoc(), TransformTemplateName(), or TransformTemplateArgument() with entirely new implementations.
For more fine-grained transformations, subclasses can replace any of the TransformXXX functions (where XXX is the name of an AST node, e.g., PointerType, StmtExpr) to alter the transformation. As mentioned previously, replacing TransformTemplateTypeParmType() allows template instantiation to substitute template arguments for their corresponding template parameters. Additionally, subclasses can override the RebuildXXX functions to control how AST nodes are rebuilt when their operands change. By default, TreeTransform will invoke semantic analysis to rebuild AST nodes. However, certain other tree transformations (e.g, cloning) may be able to use more efficient rebuild steps.
There are a handful of other functions that can be overridden, allowing one to avoid traversing nodes that don't need any transformation (AlreadyTransformed()), force rebuilding AST nodes even when their operands have not changed (AlwaysRebuild()), and customize the default locations and entity names used for type-checking (getBaseLocation(), getBaseEntity()).
Definition at line 103 of file TreeTransform.h.
Member Enumeration Documentation
StmtDiscardKind
template<typename Derived > enum clang::TreeTransform::StmtDiscardKind
The reason why the value of a statement is not discarded, if any.
Enumerator
SDK_Discarded
SDK_NotDiscarded
SDK_StmtExprResult
Definition at line 349 of file TreeTransform.h.
Constructor & Destructor Documentation
TreeTransform()
template<typename Derived > clang::TreeTransform< Derived >::TreeTransform (Sema & SemaRef) inline
Initializes a new tree transformer.
Definition at line 131 of file TreeTransform.h.
Member Function Documentation
AllowSkippingCXXConstructExpr()
template<typename Derived > bool clang::TreeTransform< Derived >::AllowSkippingCXXConstructExpr () inline
Wether CXXConstructExpr can be skipped when they are implicit.
They will be reconstructed when used if needed. This is useful when the user that cause rebuilding of the CXXConstructExpr is outside of the expression at which the TreeTransform started.
Definition at line 169 of file TreeTransform.h.
AlreadyTransformed()
template<typename Derived > bool clang::TreeTransform< Derived >::AlreadyTransformed (QualType T) inline
Determine whether the given type T has already been transformed.
Subclasses can provide an alternative implementation of this routine to short-circuit evaluation when it is known that a given type will not change. For example, template instantiation need not traverse non-dependent types.
Definition at line 222 of file TreeTransform.h.
AlwaysRebuild()
template<typename Derived > bool clang::TreeTransform< Derived >::AlwaysRebuild () inline
Whether the transformation should always rebuild AST nodes, even if none of the children have changed.
Subclasses may override this function to specify when the transformation should rebuild all AST nodes.
We must always rebuild all AST nodes when performing variadic template pack expansion, in order to avoid violating the AST invariant that each statement node appears at most once in its containing declaration.
Definition at line 157 of file TreeTransform.h.
References clang::Sema::ArgumentPackSubstitutionIndex, and clang::TreeTransform< Derived >::SemaRef.
DropCallArgument()
template<typename Derived > bool clang::TreeTransform< Derived >::DropCallArgument (Expr * E) inline
Determine whether the given call argument should be dropped, e.g., because it is a default argument.
Subclasses can provide an alternative implementation of this routine to determine which kinds of call arguments get dropped. By default, CXXDefaultArgument nodes are dropped (prior to transformation).
Definition at line 240 of file TreeTransform.h.
References clang::Expr::isDefaultArgument().
ExpandingFunctionParameterPack()
template<typename Derived > void clang::TreeTransform< Derived >::ExpandingFunctionParameterPack (ParmVarDecl * Pack) inline
Note to the derived class when a function parameter pack is being expanded.
Definition at line 308 of file TreeTransform.h.
FinishCXXForRangeStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::FinishCXXForRangeStmt (Stmt * ForRange, Stmt * Body) inline
Attach body to a C++0x range-based for statement.
By default, performs semantic analysis to finish the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2577 of file TreeTransform.h.
References clang::Sema::FinishCXXForRangeStmt(), and clang::TreeTransform< Derived >::getSema().
ForgetPartiallySubstitutedPack()
template<typename Derived > TemplateArgument clang::TreeTransform< Derived >::ForgetPartiallySubstitutedPack () inline
"Forget" about the partially-substituted pack template argument, when performing an instantiation that must preserve the parameter pack use.
This routine is meant to be overridden by the template instantiator.
Definition at line 295 of file TreeTransform.h.
getBaseEntity()
template<typename Derived > DeclarationName clang::TreeTransform< Derived >::getBaseEntity () inline
Returns the name of the entity being transformed, if that information was not available elsewhere in the AST.
By default, returns an empty name. Subclasses can provide an alternative implementation with a more precise name.
Definition at line 184 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::TemporaryBase::TemporaryBase().
getBaseLocation()
template<typename Derived > SourceLocation clang::TreeTransform< Derived >::getBaseLocation () inline
Returns the location of the entity being transformed, if that information was not available elsewhere in the AST.
By default, returns no source-location information. Subclasses can provide an alternative implementation that provides better location information.
Definition at line 177 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::InventTypeSourceInfo(), and clang::TreeTransform< Derived >::TemporaryBase::TemporaryBase().
getDerived() [1/2]
template<typename Derived > Derived & clang::TreeTransform< Derived >::getDerived () inline
Retrieves a reference to the derived class.
Definition at line 134 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::InventTypeSourceInfo(), clang::TreeTransform< Derived >::RebuildCXXNamedCastExpr(), clang::TreeTransform< Derived >::RebuildDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TemporaryBase::TemporaryBase(), clang::TreeTransform< Derived >::TransformDefinition(), clang::TreeTransform< Derived >::TransformFirstQualifierInScope(), clang::TreeTransform< Derived >::TransformFunctionTypeParams(), clang::transformOMPMappableExprListClause(), clang::TreeTransform< Derived >::TransformRequiresTypeParams(), and clang::TreeTransform< Derived >::TemporaryBase::~TemporaryBase().
getDerived() [2/2]
template<typename Derived > const Derived & clang::TreeTransform< Derived >::getDerived () const inline
Retrieves a reference to the derived class.
Definition at line 137 of file TreeTransform.h.
getSema()
template<typename Derived > Sema & clang::TreeTransform< Derived >::getSema () const inline
Retrieves a reference to the semantic analysis object used for this tree transform.
Definition at line 146 of file TreeTransform.h.
References clang::TreeTransform< Derived >::SemaRef.
Referenced by clang::TreeTransform< Derived >::FinishCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildAddrLabelExpr(), clang::TreeTransform< Derived >::RebuildArraySubscriptExpr(), clang::TreeTransform< Derived >::RebuildArrayTypeTrait(), clang::TreeTransform< Derived >::RebuildAtomicExpr(), clang::TreeTransform< Derived >::RebuildBinaryOperator(), clang::TreeTransform< Derived >::RebuildBuiltinBitCastExpr(), clang::TreeTransform< Derived >::RebuildCallExpr(), clang::TreeTransform< Derived >::RebuildCaseStmt(), clang::TreeTransform< Derived >::RebuildCaseStmtBody(), clang::TreeTransform< Derived >::RebuildCoawaitExpr(), clang::TreeTransform< Derived >::RebuildCompoundLiteralExpr(), clang::TreeTransform< Derived >::RebuildCompoundStmt(), clang::TreeTransform< Derived >::RebuildConceptSpecializationExpr(), clang::TreeTransform< Derived >::RebuildConditionalOperator(), clang::TreeTransform< Derived >::RebuildCoreturnStmt(), clang::TreeTransform< Derived >::RebuildCoroutineBodyStmt(), clang::TreeTransform< Derived >::RebuildCoyieldExpr(), clang::TreeTransform< Derived >::RebuildCStyleCastExpr(), clang::TreeTransform< Derived >::RebuildCXXAddrspaceCastExpr(), clang::TreeTransform< Derived >::RebuildCXXCatchStmt(), clang::TreeTransform< Derived >::RebuildCXXConstCastExpr(), clang::TreeTransform< Derived >::RebuildCXXConstructExpr(), clang::TreeTransform< Derived >::RebuildCXXDefaultArgExpr(), clang::TreeTransform< Derived >::RebuildCXXDefaultInitExpr(), clang::TreeTransform< Derived >::RebuildCXXDeleteExpr(), clang::TreeTransform< Derived >::RebuildCXXDynamicCastExpr(), clang::TreeTransform< Derived >::RebuildCXXFoldExpr(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildCXXFunctionalCastExpr(), clang::TreeTransform< Derived >::RebuildCXXInheritedCtorInitExpr(), clang::TreeTransform< Derived >::RebuildCXXNewExpr(), clang::TreeTransform< Derived >::RebuildCXXReinterpretCastExpr(), clang::TreeTransform< Derived >::RebuildCXXRewrittenBinaryOperator(), clang::TreeTransform< Derived >::RebuildCXXScalarValueInitExpr(), clang::TreeTransform< Derived >::RebuildCXXStaticCastExpr(), clang::TreeTransform< Derived >::RebuildCxxSubscriptExpr(), clang::TreeTransform< Derived >::RebuildCXXTemporaryObjectExpr(), clang::TreeTransform< Derived >::RebuildCXXThisExpr(), clang::TreeTransform< Derived >::RebuildCXXThrowExpr(), clang::TreeTransform< Derived >::RebuildCXXTryStmt(), clang::TreeTransform< Derived >::RebuildCXXTypeidExpr(), clang::TreeTransform< Derived >::RebuildCXXTypeidExpr(), clang::TreeTransform< Derived >::RebuildCXXUnresolvedConstructExpr(), clang::TreeTransform< Derived >::RebuildCXXUuidofExpr(), clang::TreeTransform< Derived >::RebuildCXXUuidofExpr(), clang::TreeTransform< Derived >::RebuildDeclarationNameExpr(), clang::TreeTransform< Derived >::RebuildDeclRefExpr(), clang::TreeTransform< Derived >::RebuildDeclStmt(), clang::TreeTransform< Derived >::RebuildDefaultStmt(), clang::TreeTransform< Derived >::RebuildDependentCoawaitExpr(), clang::TreeTransform< Derived >::RebuildDependentScopeDeclRefExpr(), clang::TreeTransform< Derived >::RebuildDoStmt(), clang::TreeTransform< Derived >::RebuildEmptyCXXFoldExpr(), clang::TreeTransform< Derived >::RebuildExceptionDecl(), clang::TreeTransform< Derived >::RebuildExpressionTrait(), clang::TreeTransform< Derived >::RebuildExtVectorElementExpr(), clang::TreeTransform< Derived >::RebuildForStmt(), clang::TreeTransform< Derived >::RebuildGCCAsmStmt(), clang::TreeTransform< Derived >::RebuildGenericSelectionExpr(), clang::TreeTransform< Derived >::RebuildGenericSelectionExpr(), clang::TreeTransform< Derived >::RebuildGotoStmt(), clang::TreeTransform< Derived >::RebuildIfStmt(), clang::TreeTransform< Derived >::RebuildIndirectGotoStmt(), clang::TreeTransform< Derived >::RebuildMatrixSubscriptExpr(), clang::TreeTransform< Derived >::RebuildMemberExpr(), clang::TreeTransform< Derived >::RebuildMSAsmStmt(), clang::TreeTransform< Derived >::RebuildMSDependentExistsStmt(), clang::TreeTransform< Derived >::RebuildObjCArrayLiteral(), clang::TreeTransform< Derived >::RebuildObjCAtCatchStmt(), clang::TreeTransform< Derived >::RebuildObjCAtFinallyStmt(), clang::TreeTransform< Derived >::RebuildObjCAtSynchronizedOperand(), clang::TreeTransform< Derived >::RebuildObjCAtSynchronizedStmt(), clang::TreeTransform< Derived >::RebuildObjCAtThrowStmt(), clang::TreeTransform< Derived >::RebuildObjCAtTryStmt(), clang::TreeTransform< Derived >::RebuildObjCAutoreleasePoolStmt(), clang::TreeTransform< Derived >::RebuildObjCBoxedExpr(), clang::TreeTransform< Derived >::RebuildObjCDictionaryLiteral(), clang::TreeTransform< Derived >::RebuildObjCExceptionDecl(), clang::TreeTransform< Derived >::RebuildObjCForCollectionStmt(), clang::TreeTransform< Derived >::RebuildObjCIsaExpr(), clang::TreeTransform< Derived >::RebuildObjCIvarRefExpr(), clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr(), clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr(), clang::TreeTransform< Derived >::RebuildObjCSubscriptRefExpr(), clang::TreeTransform< Derived >::RebuildOffsetOfExpr(), clang::TreeTransform< Derived >::RebuildOMPAffinityClause(), clang::TreeTransform< Derived >::RebuildOMPAlignClause(), clang::TreeTransform< Derived >::RebuildOMPAlignedClause(), clang::TreeTransform< Derived >::RebuildOMPAllocateClause(), clang::TreeTransform< Derived >::RebuildOMPAllocatorClause(), clang::TreeTransform< Derived >::RebuildOMPArraySectionExpr(), clang::TreeTransform< Derived >::RebuildOMPArrayShapingExpr(), clang::TreeTransform< Derived >::RebuildOMPAtClause(), clang::TreeTransform< Derived >::RebuildOMPBindClause(), clang::TreeTransform< Derived >::RebuildOMPCanonicalLoop(), clang::TreeTransform< Derived >::RebuildOMPCollapseClause(), clang::TreeTransform< Derived >::RebuildOMPCopyinClause(), clang::TreeTransform< Derived >::RebuildOMPCopyprivateClause(), clang::TreeTransform< Derived >::RebuildOMPDefaultClause(), clang::TreeTransform< Derived >::RebuildOMPDefaultmapClause(), clang::TreeTransform< Derived >::RebuildOMPDependClause(), clang::TreeTransform< Derived >::RebuildOMPDepobjClause(), clang::TreeTransform< Derived >::RebuildOMPDestroyClause(), clang::TreeTransform< Derived >::RebuildOMPDetachClause(), clang::TreeTransform< Derived >::RebuildOMPDeviceClause(), clang::TreeTransform< Derived >::RebuildOMPDistScheduleClause(), clang::TreeTransform< Derived >::RebuildOMPDoacrossClause(), clang::TreeTransform< Derived >::RebuildOMPExclusiveClause(), clang::TreeTransform< Derived >::RebuildOMPExecutableDirective(), clang::TreeTransform< Derived >::RebuildOMPFilterClause(), clang::TreeTransform< Derived >::RebuildOMPFinalClause(), clang::TreeTransform< Derived >::RebuildOMPFirstprivateClause(), clang::TreeTransform< Derived >::RebuildOMPFlushClause(), clang::TreeTransform< Derived >::RebuildOMPFromClause(), clang::TreeTransform< Derived >::RebuildOMPFullClause(), clang::TreeTransform< Derived >::RebuildOMPGrainsizeClause(), clang::TreeTransform< Derived >::RebuildOMPHasDeviceAddrClause(), clang::TreeTransform< Derived >::RebuildOMPHintClause(), clang::TreeTransform< Derived >::RebuildOMPIfClause(), clang::TreeTransform< Derived >::RebuildOMPInclusiveClause(), clang::TreeTransform< Derived >::RebuildOMPInitClause(), clang::TreeTransform< Derived >::RebuildOMPInReductionClause(), clang::TreeTransform< Derived >::RebuildOMPIsDevicePtrClause(), clang::TreeTransform< Derived >::RebuildOMPIteratorExpr(), clang::TreeTransform< Derived >::RebuildOMPLastprivateClause(), clang::TreeTransform< Derived >::RebuildOMPLinearClause(), clang::TreeTransform< Derived >::RebuildOMPMapClause(), clang::TreeTransform< Derived >::RebuildOMPMessageClause(), clang::TreeTransform< Derived >::RebuildOMPNocontextClause(), clang::TreeTransform< Derived >::RebuildOMPNontemporalClause(), clang::TreeTransform< Derived >::RebuildOMPNovariantsClause(), clang::TreeTransform< Derived >::RebuildOMPNumTasksClause(), clang::TreeTransform< Derived >::RebuildOMPNumTeamsClause(), clang::TreeTransform< Derived >::RebuildOMPNumThreadsClause(), clang::TreeTransform< Derived >::RebuildOMPOrderClause(), clang::TreeTransform< Derived >::RebuildOMPOrderedClause(), clang::TreeTransform< Derived >::RebuildOMPPartialClause(), clang::TreeTransform< Derived >::RebuildOMPPriorityClause(), clang::TreeTransform< Derived >::RebuildOMPPrivateClause(), clang::TreeTransform< Derived >::RebuildOMPProcBindClause(), clang::TreeTransform< Derived >::RebuildOMPReductionClause(), clang::TreeTransform< Derived >::RebuildOMPSafelenClause(), clang::TreeTransform< Derived >::RebuildOMPScheduleClause(), clang::TreeTransform< Derived >::RebuildOMPSeverityClause(), clang::TreeTransform< Derived >::RebuildOMPSharedClause(), clang::TreeTransform< Derived >::RebuildOMPSimdlenClause(), clang::TreeTransform< Derived >::RebuildOMPSizesClause(), clang::TreeTransform< Derived >::RebuildOMPTaskReductionClause(), clang::TreeTransform< Derived >::RebuildOMPThreadLimitClause(), clang::TreeTransform< Derived >::RebuildOMPToClause(), clang::TreeTransform< Derived >::RebuildOMPUseClause(), clang::TreeTransform< Derived >::RebuildOMPUseDeviceAddrClause(), clang::TreeTransform< Derived >::RebuildOMPUseDevicePtrClause(), clang::TreeTransform< Derived >::RebuildOMPUsesAllocatorsClause(), clang::TreeTransform< Derived >::RebuildOMPXDynCGroupMemClause(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::TreeTransform< Derived >::RebuildPackExpansionType(), clang::TreeTransform< Derived >::RebuildParenExpr(), clang::TreeTransform< Derived >::RebuildParenListExpr(), clang::TreeTransform< Derived >::RebuildPredefinedExpr(), clang::TreeTransform< Derived >::RebuildRecoveryExpr(), clang::TreeTransform< Derived >::RebuildReturnStmt(), clang::TreeTransform< Derived >::RebuildSEHExceptStmt(), clang::TreeTransform< Derived >::RebuildSEHFinallyStmt(), clang::TreeTransform< Derived >::RebuildSEHTryStmt(), clang::TreeTransform< Derived >::RebuildSourceLocExpr(), clang::TreeTransform< Derived >::RebuildStmtExpr(), clang::TreeTransform< Derived >::RebuildSwitchStmtBody(), clang::TreeTransform< Derived >::RebuildSwitchStmtStart(), clang::TreeTransform< Derived >::RebuildSYCLUniqueStableNameExpr(), clang::TreeTransform< Derived >::RebuildTemplateIdExpr(), clang::TreeTransform< Derived >::RebuildTemplateName(), clang::TreeTransform< Derived >::RebuildTypeTrait(), clang::TreeTransform< Derived >::RebuildUnaryExprOrTypeTrait(), clang::TreeTransform< Derived >::RebuildUnaryExprOrTypeTrait(), clang::TreeTransform< Derived >::RebuildUnaryOperator(), clang::TreeTransform< Derived >::RebuildVAArgExpr(), clang::TreeTransform< Derived >::RebuildWhileStmt(), and clang::transformOMPMappableExprListClause().
InventTemplateArgumentLoc()
template<typename Derived > void clang::TreeTransform< Derived >::InventTemplateArgumentLoc (const TemplateArgument & Arg, TemplateArgumentLoc & ArgLoc)
Fakes up a TemplateArgumentLoc for a given TemplateArgument.
Definition at line 4541 of file TreeTransform.h.
Referenced by clang::TemplateArgumentLocInventIterator< Derived, InputIterator >::operator*().
InventTypeSourceInfo()
template<typename Derived > TypeSourceInfo * clang::TreeTransform< Derived >::InventTypeSourceInfo (QualType T) inline
Fakes up a TypeSourceInfo for a type.
Definition at line 651 of file TreeTransform.h.
References clang::Sema::Context, clang::TreeTransform< Derived >::getBaseLocation(), clang::TreeTransform< Derived >::getDerived(), clang::ASTContext::getTrivialTypeSourceInfo(), and clang::TreeTransform< Derived >::SemaRef.
Owned() [1/2]
template<typename Derived > static ExprResult clang::TreeTransform< Derived >::Owned (Expr * E) inline static
Definition at line 141 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::RebuildCXXCatchStmt(), and clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr().
Owned() [2/2]
template<typename Derived > static StmtResult clang::TreeTransform< Derived >::Owned (Stmt * S) inline static
Definition at line 142 of file TreeTransform.h.
RebuildAddrLabelExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildAddrLabelExpr (SourceLocation AmpAmpLoc, SourceLocation LabelLoc, LabelDecl * Label) inline
Build a new address-of-label expression.
By default, performs semantic analysis, using the name of the label rather than attempting to map the label statement itself. Subclasses may override this routine to provide different behavior.
Definition at line 3003 of file TreeTransform.h.
References clang::Sema::ActOnAddrLabel(), clang::TreeTransform< Derived >::getSema(), and Label.
RebuildArraySubscriptExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildArraySubscriptExpr (Expr * LHS, SourceLocation LBracketLoc, Expr * RHS, SourceLocation RBracketLoc) inline
Build a new array subscript expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2713 of file TreeTransform.h.
References clang::Sema::ActOnArraySubscriptExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildArrayType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, const llvm::APInt * Size, Expr * SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new array type given the element type, size modifier, size of the array (if known), size expression, and index type qualifiers.
By default, performs semantic analysis when building the array type. Subclasses may override this routine to provide different behavior. Also by default, all of the other Rebuild*Array
Definition at line 14852 of file TreeTransform.h.
References clang::Sema::BuildArrayType(), clang::Sema::Context, clang::IntegerLiteral::Create(), clang::SourceRange::getBegin(), clang::ASTContext::getIntWidth(), clang::ASTContext::UnsignedCharTy, clang::ASTContext::UnsignedInt128Ty, clang::ASTContext::UnsignedIntTy, clang::ASTContext::UnsignedLongLongTy, clang::ASTContext::UnsignedLongTy, and clang::ASTContext::UnsignedShortTy.
RebuildArrayTypeTrait()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildArrayTypeTrait (ArrayTypeTrait Trait, SourceLocation StartLoc, TypeSourceInfo * TSInfo, Expr * DimExpr, SourceLocation RParenLoc) inline
Build a new array type trait expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3377 of file TreeTransform.h.
References clang::Sema::BuildArrayTypeTrait(), and clang::TreeTransform< Derived >::getSema().
RebuildAtomicExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildAtomicExpr (SourceLocation BuiltinLoc, MultiExprArg SubExprs, AtomicExpr::AtomicOp Op, SourceLocation RParenLoc) inline
Build a new atomic operation expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3947 of file TreeTransform.h.
References clang::Sema::AST, clang::Sema::BuildAtomicExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildAtomicType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildAtomicType (QualType ValueType, SourceLocation KWLoc)
Build a new atomic type given its value type.
By default, performs semantic analysis when building the atomic type. Subclasses may override this routine to provide different behavior.
Definition at line 15094 of file TreeTransform.h.
References clang::Sema::BuildAtomicType().
RebuildAttributedStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildAttributedStmt (SourceLocation AttrLoc, ArrayRef< const Attr * > Attrs, Stmt * SubStmt) inline
Build a new attributed statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1381 of file TreeTransform.h.
References clang::Sema::BuildAttributedStmt(), and clang::TreeTransform< Derived >::SemaRef.
RebuildAutoType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildAutoType (QualType Deduced, AutoTypeKeyword Keyword, ConceptDecl * TypeConstraintConcept, ArrayRef< TemplateArgument > TypeConstraintArgs) inline
Build a new C++11 auto type.
By default, builds a new AutoType with the given deduced type.
Definition at line 1054 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getAutoType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildBinaryOperator()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildBinaryOperator (SourceLocation OpLoc, BinaryOperatorKind Opc, Expr * LHS, Expr * RHS) inline
Build a new binary operator expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2867 of file TreeTransform.h.
References clang::Sema::BuildBinOp(), and clang::TreeTransform< Derived >::getSema().
RebuildBitIntType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildBitIntType (bool IsUnsigned, unsigned NumBits, SourceLocation Loc)
Build a bit-precise int given its value type.
Definition at line 15108 of file TreeTransform.h.
References clang::Sema::BuildBitIntType(), clang::Sema::Context, clang::IntegerLiteral::Create(), clang::ASTContext::getIntWidth(), and clang::ASTContext::IntTy.
RebuildBlockPointerType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildBlockPointerType (QualType PointeeType, SourceLocation Sigil)
Build a new block pointer type given its pointee type.
By default, performs semantic analysis when building the block pointer type. Subclasses may override this routine to provide different behavior.
Definition at line 14788 of file TreeTransform.h.
References clang::Sema::BuildBlockPointerType().
RebuildBuiltinBitCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildBuiltinBitCastExpr (SourceLocation KWLoc, TypeSourceInfo * TSI, Expr * Sub, SourceLocation RParenLoc) inline
Build a new C++ __builtin_bit_cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3223 of file TreeTransform.h.
References clang::Sema::BuildBuiltinBitCastExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCallExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCallExpr (Expr * Callee, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc, Expr * ExecConfig = nullptr) inline
Build a new call expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2775 of file TreeTransform.h.
References clang::Sema::ActOnCallExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCaseStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCaseStmt (SourceLocation CaseLoc, Expr * LHS, SourceLocation EllipsisLoc, Expr * RHS, SourceLocation ColonLoc) inline
Build a new case statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1339 of file TreeTransform.h.
References clang::Sema::ActOnCaseStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildCaseStmtBody()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCaseStmtBody (Stmt * S, Stmt * Body) inline
Attach the body to a new case statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1352 of file TreeTransform.h.
References clang::Sema::ActOnCaseStmtBody(), and clang::TreeTransform< Derived >::getSema().
RebuildChooseExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildChooseExpr (SourceLocation BuiltinLoc, Expr * Cond, Expr * LHS, Expr * RHS, SourceLocation RParenLoc) inline
Build a new __builtin_choose_expr expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3022 of file TreeTransform.h.
References clang::Sema::ActOnChooseExpr(), clang::Cond, and clang::TreeTransform< Derived >::SemaRef.
RebuildCoawaitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCoawaitExpr (SourceLocation CoawaitLoc, Expr * Operand, UnresolvedLookupExpr * OpCoawaitLookup, bool IsImplicit) inline
Build a new co_await expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 1536 of file TreeTransform.h.
References clang::Sema::BuildOperatorCoawaitCall(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildUnresolvedCoawaitExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::TreeTransform< Derived >::getSema(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
RebuildCompoundLiteralExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCompoundLiteralExpr (SourceLocation LParenLoc, TypeSourceInfo * TInfo, SourceLocation RParenLoc, Expr * Init) inline
Build a new compound literal expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2913 of file TreeTransform.h.
References clang::Sema::BuildCompoundLiteralExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCompoundStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCompoundStmt (SourceLocation LBraceLoc, MultiStmtArg Statements, SourceLocation RBraceLoc, bool IsStmtExpr) inline
Build a new compound statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1327 of file TreeTransform.h.
References clang::Sema::ActOnCompoundStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildConceptSpecializationExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildConceptSpecializationExpr (NestedNameSpecifierLoc NNS, SourceLocation TemplateKWLoc, DeclarationNameInfo ConceptNameInfo, NamedDecl * FoundDecl, ConceptDecl * NamedConcept, TemplateArgumentListInfo * TALI) inline
Build a new Objective-C boxed expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3585 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::CheckConceptTemplateId(), clang::ExprError(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildConditionalOperator()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildConditionalOperator (Expr * Cond, SourceLocation QuestionLoc, Expr * LHS, SourceLocation ColonLoc, Expr * RHS) inline
Build a new conditional operator expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2888 of file TreeTransform.h.
References clang::Sema::ActOnConditionalOp(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RebuildConstantArrayType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildConstantArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, const llvm::APInt & Size, Expr * SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new constant array type given the element type, size modifier, (known) size of the array, and index type qualifiers.
By default, performs semantic analysis when building the array type. Subclasses may override this routine to provide different behavior.
Definition at line 14887 of file TreeTransform.h.
RebuildConstantMatrixType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildConstantMatrixType (QualType ElementType, unsigned NumRows, unsigned NumColumns)
Build a new matrix type given the element type and dimensions.
Definition at line 14975 of file TreeTransform.h.
References clang::Sema::Context, and clang::ASTContext::getConstantMatrixType().
RebuildConvertVectorExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildConvertVectorExpr (SourceLocation BuiltinLoc, Expr * SrcExpr, TypeSourceInfo * DstTInfo, SourceLocation RParenLoc) inline
Build a new convert vector expression.
Definition at line 3854 of file TreeTransform.h.
References clang::Sema::SemaConvertVectorExpr(), and clang::TreeTransform< Derived >::SemaRef.
RebuildCoreturnStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCoreturnStmt (SourceLocation CoreturnLoc, Expr * Result, bool IsImplicit) inline
Build a new co_return statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1527 of file TreeTransform.h.
References clang::Sema::BuildCoreturnStmt(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildCoroutineBodyStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCoroutineBodyStmt (CoroutineBodyStmt::CtorArgs Args) inline
Definition at line 1578 of file TreeTransform.h.
References clang::Sema::BuildCoroutineBodyStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildCoyieldExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCoyieldExpr (SourceLocation CoyieldLoc, Expr * Result) inline
Build a new co_yield expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 1574 of file TreeTransform.h.
References clang::Sema::BuildCoyieldExpr(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildCStyleCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCStyleCastExpr (SourceLocation LParenLoc, TypeSourceInfo * TInfo, SourceLocation RParenLoc, Expr * SubExpr) inline
Build a new C-style cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2901 of file TreeTransform.h.
References clang::Sema::BuildCStyleCastExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXAddrspaceCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXAddrspaceCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Definition at line 3189 of file TreeTransform.h.
References clang::Sema::BuildCXXNamedCast(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXCatchStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCXXCatchStmt (SourceLocation CatchLoc, VarDecl * ExceptionDecl, Stmt * Handler) inline
Build a new C++ catch statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2504 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getSema(), and clang::TreeTransform< Derived >::Owned().
RebuildCXXConstCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXConstCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Build a new C++ const_cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3175 of file TreeTransform.h.
References clang::Sema::BuildCXXNamedCast(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXConstructExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXConstructExpr (QualType T, SourceLocation Loc, CXXConstructorDecl * Constructor, bool IsElidable, MultiExprArg Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool RequiresZeroInit, CXXConstructExpr::ConstructionKind ConstructKind, SourceRange ParenRange) inline
Build a new object-construction expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3436 of file TreeTransform.h.
References clang::Sema::BuildCXXConstructExpr(), clang::ExprError(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXDefaultArgExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXDefaultArgExpr (SourceLocation Loc, ParmVarDecl * Param, Expr * RewrittenExpr) inline
Build a new C++ default-argument expression.
By default, builds a new default-argument expression, which does not require any semantic analysis. Subclasses may override this routine to provide different behavior.
Definition at line 3298 of file TreeTransform.h.
References clang::CXXDefaultArgExpr::Create(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXDefaultInitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXDefaultInitExpr (SourceLocation Loc, FieldDecl * Field) inline
Build a new C++11 default-initialization expression.
By default, builds a new default field initialization expression, which does not require any semantic analysis. Subclasses may override this routine to provide different behavior.
Definition at line 3309 of file TreeTransform.h.
References clang::Sema::BuildCXXDefaultInitExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXDeleteExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXDeleteExpr (SourceLocation StartLoc, bool IsGlobalDelete, bool IsArrayForm, Expr * Operand) inline
Build a new C++ "delete" expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3354 of file TreeTransform.h.
References clang::Sema::ActOnCXXDelete(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXDependentScopeMemberExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXDependentScopeMemberExpr (Expr * BaseE, QualType BaseType, bool IsArrow, SourceLocation OperatorLoc, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, NamedDecl * FirstQualifierInScope, const DeclarationNameInfo & MemberNameInfo, const TemplateArgumentListInfo * TemplateArgs) inline
Build a new member reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3508 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::BuildMemberReferenceExpr(), and clang::TreeTransform< Derived >::SemaRef.
RebuildCXXDynamicCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXDynamicCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Build a new C++ dynamic_cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3141 of file TreeTransform.h.
References clang::Sema::BuildCXXNamedCast(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXFoldExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXFoldExpr (UnresolvedLookupExpr * ULE, SourceLocation LParenLoc, Expr * LHS, BinaryOperatorKind Operator, SourceLocation EllipsisLoc, Expr * RHS, SourceLocation RParenLoc, std::optional< unsigned > NumExpansions) inline
Build a new C++1z fold-expression.
By default, performs semantic analysis in order to build a new fold expression.
Definition at line 3923 of file TreeTransform.h.
References clang::Sema::BuildCXXFoldExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXForRangeStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCXXForRangeStmt (SourceLocation ForLoc, SourceLocation CoawaitLoc, Stmt * Init, SourceLocation ColonLoc, Stmt * Range, Stmt * Begin, Stmt * End, Expr * Cond, Expr * Inc, Stmt * LoopVar, SourceLocation RParenLoc) inline
Build a new C++0x range-based for statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2524 of file TreeTransform.h.
References clang::Sema::ActOnObjCForCollectionStmt(), Begin, clang::Sema::BFRK_Rebuild, clang::Sema::BuildCXXForRangeStmt(), clang::Cond, clang::Sema::Diag(), clang::TreeTransform< Derived >::getSema(), clang::Expr::getType(), clang::Type::isObjCObjectPointerType(), clang::Expr::isTypeDependent(), clang::TreeTransform< Derived >::SemaRef, and clang::StmtError().
RebuildCXXFunctionalCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXFunctionalCastExpr (TypeSourceInfo * TInfo, SourceLocation LParenLoc, Expr * Sub, SourceLocation RParenLoc, bool ListInitialization) inline
Build a new C++ functional-style cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3202 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeConstructExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXInheritedCtorInitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXInheritedCtorInitExpr (QualType T, SourceLocation Loc, CXXConstructorDecl * Constructor, bool ConstructsVBase, bool InheritedFromVBase) inline
Build a new implicit construction via inherited constructor expression.
Definition at line 3470 of file TreeTransform.h.
References clang::Sema::Context, and clang::TreeTransform< Derived >::getSema().
RebuildCXXNamedCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXNamedCastExpr (SourceLocation OpLoc, Stmt::StmtClass Class, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Build a new C++ "named" cast expression, such as static_cast or reinterpret_cast.
By default, this routine dispatches to one of the more-specific routines for a particular named case, e.g., RebuildCXXStaticCastExpr(). Subclasses may override this routine to provide different behavior.
Definition at line 3081 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getDerived().
RebuildCXXNewExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXNewExpr (SourceLocation StartLoc, bool UseGlobal, SourceLocation PlacementLParen, MultiExprArg PlacementArgs, SourceLocation PlacementRParen, SourceRange TypeIdParens, QualType AllocatedType, TypeSourceInfo * AllocatedTypeInfo, std::optional< Expr * > ArraySize, SourceRange DirectInitRange, Expr * Initializer) inline
Build a new C++ "new" expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3330 of file TreeTransform.h.
References clang::Sema::BuildCXXNew(), clang::TreeTransform< Derived >::getSema(), and clang::Initializer.
RebuildCXXNoexceptExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXNoexceptExpr (SourceRange Range, Expr * Arg) inline
Build a new noexcept expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3554 of file TreeTransform.h.
References clang::Sema::BuildCXXNoexceptExpr(), and clang::TreeTransform< Derived >::SemaRef.
RebuildCXXOperatorCallExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr (OverloadedOperatorKind Op, SourceLocation OpLoc, SourceLocation CalleeLoc, bool RequiresADL, const UnresolvedSetImpl & Functions, Expr * First, Expr * Second)
Build a new overloaded operator call expression.
By default, performs semantic analysis to build the new expression. The semantic analysis provides the behavior of template instantiation, copying with transformations that turn what looks like an overloaded operator call into a use of a builtin operator, performing argument-dependent lookup, etc. Subclasses may override this routine to provide different behavior.
Definition at line 15172 of file TreeTransform.h.
References clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::ExprError(), clang::First, clang::Expr::getObjectKind(), clang::BinaryOperator::getOverloadedOpcode(), clang::UnaryOperator::getOverloadedOpcode(), clang::Expr::getType(), clang::BinaryOperator::isAssignmentOp(), clang::Type::isOverloadableType(), clang::OK_ObjCProperty, and clang::Result.
RebuildCXXPseudoDestructorExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr (Expr * Base, SourceLocation OperatorLoc, bool isArrow, CXXScopeSpec & SS, TypeSourceInfo * ScopeType, SourceLocation CCLoc, SourceLocation TildeLoc, PseudoDestructorTypeStorage Destroyed)
Build a new pseudo-destructor expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 15259 of file TreeTransform.h.
References clang::Sema::BuildPseudoDestructorExpr(), clang::Type::castAs(), clang::Sema::Context, clang::ASTContext::DeclarationNames, clang::ExprError(), clang::CXXScopeSpec::Extend(), clang::ASTContext::getCanonicalType(), clang::DeclarationNameTable::getCXXDestructorName(), clang::PseudoDestructorTypeStorage::getIdentifier(), clang::PseudoDestructorTypeStorage::getLocation(), clang::PointerType::getPointeeType(), clang::TypeSourceInfo::getType(), clang::PseudoDestructorTypeStorage::getTypeSourceInfo(), and clang::DeclarationNameInfo::setNamedTypeInfo().
RebuildCXXReinterpretCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXReinterpretCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Build a new C++ reinterpret_cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3158 of file TreeTransform.h.
References clang::Sema::BuildCXXNamedCast(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXRewrittenBinaryOperator()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXRewrittenBinaryOperator (SourceLocation OpLoc, BinaryOperatorKind Opcode, const UnresolvedSetImpl & UnqualLookups, Expr * LHS, Expr * RHS) inline
Build a new rewritten operator expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2877 of file TreeTransform.h.
References clang::Sema::CreateOverloadedBinOp(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXScalarValueInitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXScalarValueInitExpr (TypeSourceInfo * TSInfo, SourceLocation LParenLoc, SourceLocation RParenLoc) inline
Build a new C++ zero-initialization expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3318 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeConstructExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXStaticCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXStaticCastExpr (SourceLocation OpLoc, SourceLocation LAngleLoc, TypeSourceInfo * TInfo, SourceLocation RAngleLoc, SourceLocation LParenLoc, Expr * SubExpr, SourceLocation RParenLoc) inline
Build a new C++ static_cast expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3124 of file TreeTransform.h.
References clang::Sema::BuildCXXNamedCast(), and clang::TreeTransform< Derived >::getSema().
RebuildCxxSubscriptExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCxxSubscriptExpr (Expr * Callee, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc) inline
Definition at line 2783 of file TreeTransform.h.
References clang::Sema::ActOnArraySubscriptExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXTemporaryObjectExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXTemporaryObjectExpr (TypeSourceInfo * TSInfo, SourceLocation LParenOrBraceLoc, MultiExprArg Args, SourceLocation RParenOrBraceLoc, bool ListInitialization) inline
Build a new object-construction expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3482 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeConstructExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXThisExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXThisExpr (SourceLocation ThisLoc, QualType ThisType, bool isImplicit) inline
Build a new C++ "this" expression.
By default, builds a new "this" expression without performing any semantic analysis. Subclasses may override this routine to provide different behavior.
Definition at line 3278 of file TreeTransform.h.
References clang::Sema::BuildCXXThisExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXThrowExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXThrowExpr (SourceLocation ThrowLoc, Expr * Sub, bool IsThrownVariableInScope) inline
Build a new C++ throw expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3288 of file TreeTransform.h.
References clang::Sema::BuildCXXThrow(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXTryStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildCXXTryStmt (SourceLocation TryLoc, Stmt * TryBlock, ArrayRef< Stmt * > Handlers) inline
Build a new C++ try statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2515 of file TreeTransform.h.
References clang::Sema::ActOnCXXTryBlock(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXTypeidExpr() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXTypeidExpr (QualType TypeInfoType, SourceLocation TypeidLoc, Expr * Operand, SourceLocation RParenLoc) inline
Build a new C++ typeid(expr) expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3246 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeId(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXTypeidExpr() [2/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXTypeidExpr (QualType TypeInfoType, SourceLocation TypeidLoc, TypeSourceInfo * Operand, SourceLocation RParenLoc) inline
Build a new C++ typeid(type) expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3233 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeId(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXUnresolvedConstructExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXUnresolvedConstructExpr (TypeSourceInfo * TSInfo, SourceLocation LParenLoc, MultiExprArg Args, SourceLocation RParenLoc, bool ListInitialization) inline
Build a new object-construction expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3495 of file TreeTransform.h.
References clang::Sema::BuildCXXTypeConstructExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXUuidofExpr() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXUuidofExpr (QualType Type, SourceLocation TypeidLoc, Expr * Operand, SourceLocation RParenLoc) inline
Build a new C++ __uuidof(expr) expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3268 of file TreeTransform.h.
References clang::Sema::BuildCXXUuidof(), and clang::TreeTransform< Derived >::getSema().
RebuildCXXUuidofExpr() [2/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildCXXUuidofExpr (QualType Type, SourceLocation TypeidLoc, TypeSourceInfo * Operand, SourceLocation RParenLoc) inline
Build a new C++ __uuidof(type) expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3258 of file TreeTransform.h.
References clang::Sema::BuildCXXUuidof(), and clang::TreeTransform< Derived >::getSema().
RebuildDeclarationNameExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildDeclarationNameExpr (const CXXScopeSpec & SS, LookupResult & R, bool RequiresADL) inline
Build a new expression that references a declaration.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2615 of file TreeTransform.h.
References clang::Sema::BuildDeclarationNameExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildDeclRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildDeclRefExpr (NestedNameSpecifierLoc QualifierLoc, ValueDecl * VD, const DeclarationNameInfo & NameInfo, NamedDecl * Found, TemplateArgumentListInfo * TemplateArgs) inline
Build a new expression that references a declaration.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2626 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::BuildDeclarationNameExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildDeclStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildDeclStmt (MutableArrayRef< Decl * > Decls, SourceLocation StartLoc, SourceLocation EndLoc) inline
Build a new declaration statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1484 of file TreeTransform.h.
References clang::Sema::ActOnDeclStmt(), clang::Sema::BuildDeclaratorGroup(), and clang::TreeTransform< Derived >::getSema().
RebuildDecltypeType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDecltypeType (Expr * Underlying, SourceLocation Loc)
Build a new C++11 decltype type.
By default, performs semantic analysis when building the decltype type. Subclasses may override this routine to provide different behavior.
Definition at line 15074 of file TreeTransform.h.
References clang::Sema::BuildDecltypeType().
RebuildDeducedTemplateSpecializationType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDeducedTemplateSpecializationType (TemplateName Template, QualType Deduced) inline
By default, builds a new DeducedTemplateSpecializationType with the given deduced type.
Definition at line 1068 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getDeducedTemplateSpecializationType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildDefaultStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildDefaultStmt (SourceLocation DefaultLoc, SourceLocation ColonLoc, Stmt * SubStmt) inline
Build a new default statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1361 of file TreeTransform.h.
References clang::Sema::ActOnDefaultStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildDependentAddressSpaceType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentAddressSpaceType (QualType PointeeType, Expr * AddrSpaceExpr, SourceLocation AttributeLoc)
Build a new DependentAddressSpaceType or return the pointee type variable with the correct address space (retrieved from AddrSpaceExpr) applied to it.
The former will be returned in cases where the address space remains dependent.
By default, performs semantic analysis when building the type with address space applied. Subclasses may override this routine to provide different behavior.
Definition at line 14932 of file TreeTransform.h.
References clang::Sema::BuildAddressSpaceAttr().
RebuildDependentBitIntType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentBitIntType (bool IsUnsigned, Expr * NumBitsExpr, SourceLocation Loc)
Build a dependent bit-precise int given its value type.
Definition at line 15119 of file TreeTransform.h.
References clang::Sema::BuildBitIntType().
RebuildDependentCoawaitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildDependentCoawaitExpr (SourceLocation CoawaitLoc, Expr * Result, UnresolvedLookupExpr * Lookup) inline
Build a new co_await expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 1564 of file TreeTransform.h.
References clang::Sema::BuildUnresolvedCoawaitExpr(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildDependentNameType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentNameType (ElaboratedTypeKeyword Keyword, SourceLocation KeywordLoc, NestedNameSpecifierLoc QualifierLoc, const IdentifierInfo * Id, SourceLocation IdLoc, bool DeducedTSTContext) inline
Build a new typename type that refers to an identifier.
By default, performs semantic analysis when building the typename type (or elaborated type). Subclasses may override this routine to provide different behavior.
Definition at line 1150 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::LookupResult::Ambiguous, clang::Sema::CheckTypenameType(), clang::Sema::computeDeclContext(), clang::Sema::Context, clang::Sema::Diag(), clang::LookupResult::Found, clang::LookupResult::FoundOverloaded, clang::LookupResult::FoundUnresolvedValue, clang::ASTContext::getDependentNameType(), clang::ASTContext::getElaboratedType(), clang::Decl::getLocation(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::Sema::getNonTagTypeDeclKind(), clang::NestedNameSpecifierLoc::getSourceRange(), clang::ASTContext::getTypeDeclType(), Id, clang::Sema::isAcceptableTagRedeclaration(), clang::NestedNameSpecifier::isDependent(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupTagName, clang::LookupResult::NotFound, clang::LookupResult::NotFoundInCurrentInstantiation, clang::Sema::RequireCompleteDeclContext(), clang::Result, and clang::TreeTransform< Derived >::SemaRef.
RebuildDependentScopeDeclRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildDependentScopeDeclRefExpr (NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const DeclarationNameInfo & NameInfo, const TemplateArgumentListInfo * TemplateArgs, bool IsAddressOfOperand, TypeSourceInfo ** RecoveryTSI) inline
Build a new (previously unresolved) declaration reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3401 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), clang::TreeTransform< Derived >::getSema(), and clang::SourceLocation::isValid().
RebuildDependentSizedArrayType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentSizedArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, Expr * SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new dependent-sized array type given the element type, size modifier, size expression, and index type qualifiers.
By default, performs semantic analysis when building the array type. Subclasses may override this routine to provide different behavior.
Definition at line 14921 of file TreeTransform.h.
RebuildDependentSizedExtVectorType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentSizedExtVectorType (QualType ElementType, Expr * SizeExpr, SourceLocation AttributeLoc)
Build a new potentially dependently-sized extended vector type given the element type and number of elements.
By default, performs semantic analysis when building the vector type. Subclasses may override this routine to provide different behavior.
Definition at line 14968 of file TreeTransform.h.
References clang::Sema::BuildExtVectorType().
RebuildDependentSizedMatrixType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentSizedMatrixType (QualType ElementType, Expr * RowExpr, Expr * ColumnExpr, SourceLocation AttributeLoc)
Build a new matrix type given the type and dependently-defined dimensions.
Definition at line 14982 of file TreeTransform.h.
References clang::Sema::BuildMatrixType().
RebuildDependentTemplateSpecializationType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const IdentifierInfo * Name, SourceLocation NameLoc, TemplateArgumentListInfo & Args, bool AllowInjectedClassName) inline
Build a new typename type that refers to a template-id.
By default, builds a new DependentNameType type from the nested-name-specifier and the given type. Subclasses may override this routine to provide different behavior.
Definition at line 1110 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::TemplateArgumentListInfo::arguments(), clang::Sema::Context, clang::TemplateName::getAsDependentTemplateName(), clang::ASTContext::getDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::getDerived(), clang::ASTContext::getElaboratedType(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::TemplateName::isNull(), and clang::TreeTransform< Derived >::SemaRef.
RebuildDependentVectorType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildDependentVectorType (QualType ElementType, Expr * SizeExpr, SourceLocation AttributeLoc, VectorType::VectorKind VecKind)
Build a new potentially dependently-sized extended vector type given the element type and number of elements.
By default, performs semantic analysis when building the vector type. Subclasses may override this routine to provide different behavior.
Definition at line 14948 of file TreeTransform.h.
References clang::Sema::BuildVectorType().
RebuildDesignatedInitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildDesignatedInitExpr (Designation & Desig, MultiExprArg ArrayExprs, SourceLocation EqualOrColonLoc, bool GNUSyntax, Expr * Init) inline
Build a new designated initializer expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2953 of file TreeTransform.h.
References clang::Sema::ActOnDesignatedInitializer(), clang::ExprError(), clang::Result, and clang::TreeTransform< Derived >::SemaRef.
RebuildDoStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildDoStmt (SourceLocation DoLoc, Stmt * Body, SourceLocation WhileLoc, SourceLocation LParenLoc, Expr * Cond, SourceLocation RParenLoc) inline
Build a new do-while statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1434 of file TreeTransform.h.
References clang::Sema::ActOnDoStmt(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RebuildElaboratedType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildElaboratedType (SourceLocation KeywordLoc, ElaboratedTypeKeyword Keyword, NestedNameSpecifierLoc QualifierLoc, QualType Named) inline
Build a new qualified name type.
By default, builds a new ElaboratedType type from the keyword, the nested-name-specifier and the named type. Subclasses may override this routine to provide different behavior.
Definition at line 1096 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getElaboratedType(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), and clang::TreeTransform< Derived >::SemaRef.
RebuildEmptyCXXFoldExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildEmptyCXXFoldExpr (SourceLocation EllipsisLoc, BinaryOperatorKind Operator) inline
Build an empty C++1z fold-expression with the given operator.
By default, produces the fallback value for the fold-expression, or produce an error if there is no fallback value.
Definition at line 3938 of file TreeTransform.h.
References clang::Sema::BuildEmptyCXXFoldExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildEnumType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildEnumType (EnumDecl * Enum) inline
Build a new Enum type.
Definition at line 1024 of file TreeTransform.h.
References clang::Sema::Context, Enum, clang::ASTContext::getTypeDeclType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildExceptionDecl()
template<typename Derived > VarDecl * clang::TreeTransform< Derived >::RebuildExceptionDecl (VarDecl * ExceptionDecl, TypeSourceInfo * Declarator, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id) inline
Build a new C++ exception declaration.
By default, performs semantic analysis to build the new decaration. Subclasses may override this routine to provide different behavior.
Definition at line 2488 of file TreeTransform.h.
References clang::DeclContext::addDecl(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::CurContext, clang::TreeTransform< Derived >::getSema(), and Id.
RebuildExpressionTrait()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildExpressionTrait (ExpressionTrait Trait, SourceLocation StartLoc, Expr * Queried, SourceLocation RParenLoc) inline
Build a new expression trait expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3389 of file TreeTransform.h.
References clang::Sema::BuildExpressionTrait(), and clang::TreeTransform< Derived >::getSema().
RebuildExprRequirement() [1/2]
template<typename Derived > concepts::ExprRequirement * clang::TreeTransform< Derived >::RebuildExprRequirement (concepts::Requirement::SubstitutionDiagnostic * SubstDiag, bool IsSimple, SourceLocation NoexceptLoc, concepts::ExprRequirement::ReturnTypeRequirement Ret) inline
Definition at line 3624 of file TreeTransform.h.
References clang::Sema::BuildExprRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildExprRequirement() [2/2]
template<typename Derived > concepts::ExprRequirement * clang::TreeTransform< Derived >::RebuildExprRequirement (Expr * E, bool IsSimple, SourceLocation NoexceptLoc, concepts::ExprRequirement::ReturnTypeRequirement Ret) inline
Definition at line 3633 of file TreeTransform.h.
References clang::Sema::BuildExprRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildExtVectorElementExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildExtVectorElementExpr (Expr * Base, SourceLocation OpLoc, bool IsArrow, SourceLocation AccessorLoc, IdentifierInfo & Accessor) inline
Build a new extended vector element access expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2925 of file TreeTransform.h.
References clang::Sema::BuildMemberReferenceExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildExtVectorType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildExtVectorType (QualType ElementType, unsigned NumElements, SourceLocation AttributeLoc)
Build a new extended vector type given the element type and number of elements.
By default, performs semantic analysis when building the vector type. Subclasses may override this routine to provide different behavior.
Definition at line 14955 of file TreeTransform.h.
References clang::Sema::BuildExtVectorType(), clang::Sema::Context, clang::IntegerLiteral::Create(), clang::ASTContext::getIntWidth(), and clang::ASTContext::IntTy.
RebuildForStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildForStmt (SourceLocation ForLoc, SourceLocation LParenLoc, Stmt * Init, Sema::ConditionResult Cond, Sema::FullExprArg Inc, SourceLocation RParenLoc, Stmt * Body) inline
Build a new for statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1445 of file TreeTransform.h.
References clang::Sema::ActOnForStmt(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RebuildFunctionNoProtoType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildFunctionNoProtoType (QualType ResultType)
Build a new unprototyped function type.
Definition at line 15001 of file TreeTransform.h.
References clang::Sema::Context, and clang::ASTContext::getFunctionNoProtoType().
RebuildFunctionProtoType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildFunctionProtoType (QualType T, MutableArrayRef< QualType > ParamTypes, const FunctionProtoType::ExtProtoInfo & EPI)
Build a new function type.
By default, performs semantic analysis when building the function type. Subclasses may override this routine to provide different behavior.
Definition at line 14990 of file TreeTransform.h.
References clang::Sema::BuildFunctionType().
RebuildGCCAsmStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildGCCAsmStmt (SourceLocation AsmLoc, bool IsSimple, bool IsVolatile, unsigned NumOutputs, unsigned NumInputs, IdentifierInfo ** Names, MultiExprArg Constraints, MultiExprArg Exprs, Expr * AsmString, MultiExprArg Clobbers, unsigned NumLabels, SourceLocation RParenLoc) inline
Build a new inline asm statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1494 of file TreeTransform.h.
References clang::Sema::ActOnGCCAsmStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildGenericSelectionExpr() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildGenericSelectionExpr (SourceLocation KeyLoc, SourceLocation DefaultLoc, SourceLocation RParenLoc, Expr * ControllingExpr, ArrayRef< TypeSourceInfo * > Types, ArrayRef< Expr * > Exprs) inline
Build a new generic selection expression with an expression predicate.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3034 of file TreeTransform.h.
References clang::Sema::CreateGenericSelectionExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildGenericSelectionExpr() [2/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildGenericSelectionExpr (SourceLocation KeyLoc, SourceLocation DefaultLoc, SourceLocation RParenLoc, TypeSourceInfo * ControllingType, ArrayRef< TypeSourceInfo * > Types, ArrayRef< Expr * > Exprs) inline
Build a new generic selection expression with a type predicate.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3049 of file TreeTransform.h.
References clang::Sema::CreateGenericSelectionExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildGotoStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildGotoStmt (SourceLocation GotoLoc, SourceLocation LabelLoc, LabelDecl * Label) inline
Build a new goto statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1457 of file TreeTransform.h.
References clang::Sema::ActOnGotoStmt(), clang::TreeTransform< Derived >::getSema(), and Label.
RebuildIfStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildIfStmt (SourceLocation IfLoc, IfStatementKind Kind, SourceLocation LParenLoc, Sema::ConditionResult Cond, SourceLocation RParenLoc, Stmt * Init, Stmt * Then, SourceLocation ElseLoc, Stmt * Else) inline
Build a new "if" statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1391 of file TreeTransform.h.
References clang::Sema::ActOnIfStmt(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RebuildImplicitValueInitExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildImplicitValueInitExpr (QualType T) inline
Build a new value-initialized expression.
By default, builds the implicit value initialization without performing any semantic analysis. Subclasses may override this routine to provide different behavior.
Definition at line 2972 of file TreeTransform.h.
References clang::Sema::Context, and clang::TreeTransform< Derived >::SemaRef.
RebuildIncompleteArrayType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildIncompleteArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new incomplete array type given the element type, size modifier, and index type qualifiers.
By default, performs semantic analysis when building the array type. Subclasses may override this routine to provide different behavior.
Definition at line 14899 of file TreeTransform.h.
RebuildIndirectGotoStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildIndirectGotoStmt (SourceLocation GotoLoc, SourceLocation StarLoc, Expr * Target) inline
Build a new indirect goto statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1466 of file TreeTransform.h.
References clang::Sema::ActOnIndirectGotoStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildInitList()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildInitList (SourceLocation LBraceLoc, MultiExprArg Inits, SourceLocation RBraceLoc) inline
Build a new initializer list expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2943 of file TreeTransform.h.
References clang::Sema::BuildInitList(), and clang::TreeTransform< Derived >::SemaRef.
RebuildLabelStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildLabelStmt (SourceLocation IdentLoc, LabelDecl * L, SourceLocation ColonLoc, Stmt * SubStmt) inline
Build a new label statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1372 of file TreeTransform.h.
References clang::Sema::ActOnLabelStmt(), and clang::TreeTransform< Derived >::SemaRef.
RebuildMacroQualifiedType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildMacroQualifiedType (QualType T, const IdentifierInfo * MacroII) inline
Build a new MacroDefined type.
Definition at line 1013 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getMacroQualifiedType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildMatrixSubscriptExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildMatrixSubscriptExpr (Expr * Base, Expr * RowIdx, Expr * ColumnIdx, SourceLocation RBracketLoc) inline
Build a new matrix subscript expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2726 of file TreeTransform.h.
References clang::Sema::CreateBuiltinMatrixSubscriptExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildMemberExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildMemberExpr (Expr * Base, SourceLocation OpLoc, bool isArrow, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, const DeclarationNameInfo & MemberNameInfo, ValueDecl * Member, NamedDecl * FoundDecl, const TemplateArgumentListInfo * ExplicitTemplateArgs, NamedDecl * FirstQualifierInScope) inline
Build a new member access expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2794 of file TreeTransform.h.
References clang::LookupResult::addDecl(), clang::CXXScopeSpec::Adopt(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::cast(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::TreeTransform< Derived >::getSema(), getType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::LookupMemberName, clang::DeclAccessPair::make(), clang::Member, clang::Sema::PerformMemberExprBaseConversion(), clang::Sema::PerformObjectMemberConversion(), clang::LookupResult::resolveKind(), and clang::VK_LValue.
RebuildMemberPointerType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildMemberPointerType (QualType PointeeType, QualType ClassType, SourceLocation Sigil)
Build a new member pointer type given the pointee type and the class type it refers into.
By default, performs semantic analysis when building the member pointer type. Subclasses may override this routine to provide different behavior.
Definition at line 14805 of file TreeTransform.h.
References clang::Sema::BuildMemberPointerType().
RebuildMSAsmStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildMSAsmStmt (SourceLocation AsmLoc, SourceLocation LBraceLoc, ArrayRef< Token > AsmToks, StringRef AsmString, unsigned NumOutputs, unsigned NumInputs, ArrayRef< StringRef > Constraints, ArrayRef< StringRef > Clobbers, ArrayRef< Expr * > Exprs, SourceLocation EndLoc) inline
Build a new MS style inline asm statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1510 of file TreeTransform.h.
References clang::Sema::ActOnMSAsmStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildMSDependentExistsStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildMSDependentExistsStmt (SourceLocation KeywordLoc, bool IsIfExists, NestedNameSpecifierLoc QualifierLoc, DeclarationNameInfo NameInfo, Stmt * Nested) inline
Build a new C++0x range-based for statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2564 of file TreeTransform.h.
References clang::Sema::BuildMSDependentExistsStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildNestedRequirement() [1/2]
template<typename Derived > concepts::NestedRequirement * clang::TreeTransform< Derived >::RebuildNestedRequirement (Expr * Constraint) inline
Definition at line 3646 of file TreeTransform.h.
References clang::Sema::BuildNestedRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildNestedRequirement() [2/2]
template<typename Derived > concepts::NestedRequirement * clang::TreeTransform< Derived >::RebuildNestedRequirement (StringRef InvalidConstraintEntity, const ASTConstraintSatisfaction & Satisfaction) inline
Definition at line 3640 of file TreeTransform.h.
References clang::Sema::BuildNestedRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildObjCArrayLiteral()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCArrayLiteral (SourceRange Range, Expr ** Elements, unsigned NumElements) inline
Build a new Objective-C array literal.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3662 of file TreeTransform.h.
References clang::Sema::BuildObjCArrayLiteral(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtCatchStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAtCatchStmt (SourceLocation AtLoc, SourceLocation RParenLoc, VarDecl * Var, Stmt * Body) inline
Build a new Objective-C @catch statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1610 of file TreeTransform.h.
References clang::Sema::ActOnObjCAtCatchStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtFinallyStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAtFinallyStmt (SourceLocation AtLoc, Stmt * Body) inline
Build a new Objective-C @finally statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1622 of file TreeTransform.h.
References clang::Sema::ActOnObjCAtFinallyStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtSynchronizedOperand()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCAtSynchronizedOperand (SourceLocation atLoc, Expr * object) inline
Rebuild the operand to an Objective-C @synchronized statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2442 of file TreeTransform.h.
References clang::Sema::ActOnObjCAtSynchronizedOperand(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtSynchronizedStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAtSynchronizedStmt (SourceLocation AtLoc, Expr * Object, Stmt * Body) inline
Build a new Objective-C @synchronized statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2451 of file TreeTransform.h.
References clang::Sema::ActOnObjCAtSynchronizedStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtThrowStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAtThrowStmt (SourceLocation AtLoc, Expr * Operand) inline
Build a new Objective-C @throw statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1631 of file TreeTransform.h.
References clang::Sema::BuildObjCAtThrowStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAtTryStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAtTryStmt (SourceLocation AtLoc, Stmt * TryBody, MultiStmtArg CatchStmts, Stmt * Finally) inline
Build a new Objective-C @try statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1586 of file TreeTransform.h.
References clang::Sema::ActOnObjCAtTryStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCAutoreleasePoolStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCAutoreleasePoolStmt (SourceLocation AtLoc, Stmt * Body) inline
Build a new Objective-C @autoreleasepool statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2460 of file TreeTransform.h.
References clang::Sema::ActOnObjCAutoreleasePoolStmt(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCBoxedExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCBoxedExpr (SourceRange SR, Expr * ValueExpr) inline
Build a new Objective-C boxed expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3654 of file TreeTransform.h.
References clang::Sema::BuildObjCBoxedExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCDictionaryLiteral()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCDictionaryLiteral (SourceRange Range, MutableArrayRef< ObjCDictionaryElement > Elements) inline
Build a new Objective-C dictionary literal.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3680 of file TreeTransform.h.
References clang::Sema::BuildObjCDictionaryLiteral(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCEncodeExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCEncodeExpr (SourceLocation AtLoc, TypeSourceInfo * EncodeTypeInfo, SourceLocation RParenLoc) inline
Build a new Objective-C @encode expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3689 of file TreeTransform.h.
References clang::Sema::BuildObjCEncodeExpression(), and clang::TreeTransform< Derived >::SemaRef.
RebuildObjCExceptionDecl()
template<typename Derived > VarDecl * clang::TreeTransform< Derived >::RebuildObjCExceptionDecl (VarDecl * ExceptionDecl, TypeSourceInfo * TInfo, QualType T) inline
Rebuild an Objective-C exception declaration.
By default, performs semantic analysis to build the new declaration. Subclasses may override this routine to provide different behavior.
Definition at line 1598 of file TreeTransform.h.
References clang::Sema::BuildObjCExceptionDecl(), clang::NamedDecl::getIdentifier(), clang::DeclaratorDecl::getInnerLocStart(), clang::Decl::getLocation(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCForCollectionStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildObjCForCollectionStmt (SourceLocation ForLoc, Stmt * Element, Expr * Collection, SourceLocation RParenLoc, Stmt * Body) inline
Build a new Objective-C fast enumeration statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2469 of file TreeTransform.h.
References clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::FinishObjCForCollectionStmt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::TreeTransform< Derived >::getSema(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::StmtError().
RebuildObjCIsaExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCIsaExpr (Expr * BaseArg, SourceLocation IsaLoc, SourceLocation OpLoc, bool IsArrow) inline
Build a new Objective-C "isa" expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3807 of file TreeTransform.h.
References clang::Sema::BuildMemberReferenceExpr(), clang::TreeTransform< Derived >::getSema(), and clang::Expr::getType().
RebuildObjCIvarRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCIvarRefExpr (Expr * BaseArg, ObjCIvarDecl * Ivar, SourceLocation IvarLoc, bool IsArrow, bool IsFreeIvar) inline
Build a new Objective-C ivar reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3752 of file TreeTransform.h.
References clang::Sema::BuildMemberReferenceExpr(), clang::cast(), clang::NamedDecl::getDeclName(), clang::TreeTransform< Derived >::getSema(), clang::Expr::getType(), and clang::Result.
RebuildObjCMessageExpr() [1/3]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCMessageExpr (Expr * Receiver, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl * Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc) inline
Build a new Objective-C instance message.
Definition at line 3711 of file TreeTransform.h.
References clang::Sema::BuildInstanceMessage(), clang::Expr::getType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildObjCMessageExpr() [2/3]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCMessageExpr (SourceLocation SuperLoc, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, QualType SuperType, ObjCMethodDecl * Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc) inline
Build a new Objective-C instance/class message to 'super'.
Definition at line 3726 of file TreeTransform.h.
References clang::Sema::BuildClassMessage(), clang::Sema::BuildInstanceMessage(), and clang::TreeTransform< Derived >::SemaRef.
RebuildObjCMessageExpr() [3/3]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCMessageExpr (TypeSourceInfo * ReceiverTypeInfo, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl * Method, SourceLocation LBracLoc, MultiExprArg Args, SourceLocation RBracLoc) inline
Build a new Objective-C class message.
Definition at line 3696 of file TreeTransform.h.
References clang::Sema::BuildClassMessage(), clang::TypeSourceInfo::getType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildObjCObjectPointerType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildObjCObjectPointerType (QualType PointeeType, SourceLocation Star)
Build a new Objective-C object pointer type given the pointee type.
By default, directly builds the pointer type, with no additional semantic analysis.
Definition at line 14844 of file TreeTransform.h.
References clang::Sema::Context, and clang::ASTContext::getObjCObjectPointerType().
RebuildObjCObjectType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildObjCObjectType (QualType BaseType, SourceLocation Loc, SourceLocation TypeArgsLAngleLoc, ArrayRef< TypeSourceInfo * > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
Build an Objective-C object type.
By default, performs semantic analysis when building the object type. Subclasses may override this routine to provide different behavior.
Definition at line 14826 of file TreeTransform.h.
References clang::Sema::BuildObjCObjectType().
RebuildObjCPropertyRefExpr() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr (Expr * Base, QualType T, ObjCMethodDecl * Getter, ObjCMethodDecl * Setter, SourceLocation PropertyLoc) inline
Build a new Objective-C property reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3791 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getSema(), clang::OK_ObjCProperty, clang::TreeTransform< Derived >::Owned(), and clang::VK_LValue.
RebuildObjCPropertyRefExpr() [2/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr (Expr * BaseArg, ObjCPropertyDecl * Property, SourceLocation PropertyLoc) inline
Build a new Objective-C property reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3772 of file TreeTransform.h.
References clang::Sema::BuildMemberReferenceExpr(), clang::TreeTransform< Derived >::getSema(), and clang::Expr::getType().
RebuildObjCSubscriptRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildObjCSubscriptRefExpr (SourceLocation RB, Expr * Base, Expr * Key, ObjCMethodDecl * getterMethod, ObjCMethodDecl * setterMethod) inline
Definition at line 3668 of file TreeTransform.h.
References clang::Sema::BuildObjCSubscriptExpression(), and clang::TreeTransform< Derived >::getSema().
RebuildObjCTypeParamType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildObjCTypeParamType (const ObjCTypeParamDecl * Decl, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
Definition at line 14813 of file TreeTransform.h.
References clang::Sema::BuildObjCTypeParamType().
RebuildOffsetOfExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildOffsetOfExpr (SourceLocation OperatorLoc, TypeSourceInfo * Type, ArrayRef< Sema::OffsetOfComponent > Components, SourceLocation RParenLoc) inline
Build a new builtin offsetof expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2673 of file TreeTransform.h.
References clang::Sema::BuildBuiltinOffsetOf(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAffinityClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAffinityClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, Expr * Modifier, ArrayRef< Expr * > Locators) inline
Build a new OpenMP 'affinity' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2265 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAffinityClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAlignClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAlignClause (Expr * A, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'align' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2384 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAlignClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAlignedClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAlignedClause (ArrayRef< Expr * > VarList, Expr * Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'aligned' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1925 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAlignedClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAllocateClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAllocateClause (Expr * Allocate, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'allocate' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2029 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAllocateClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAllocatorClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAllocatorClause (Expr * A, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'allocator' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1741 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAllocatorClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPArraySectionExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildOMPArraySectionExpr (Expr * Base, SourceLocation LBracketLoc, Expr * LowerBound, SourceLocation ColonLocFirst, SourceLocation ColonLocSecond, Expr * Length, Expr * Stride, SourceLocation RBracketLoc) inline
Build a new array section expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2737 of file TreeTransform.h.
References clang::Sema::ActOnOMPArraySectionExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPArrayShapingExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildOMPArrayShapingExpr (Expr * Base, SourceLocation LParenLoc, SourceLocation RParenLoc, ArrayRef< Expr * > Dims, ArrayRef< SourceRange > BracketsRanges) inline
Build a new array shaping expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2752 of file TreeTransform.h.
References clang::Sema::ActOnOMPArrayShapingExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPAtClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPAtClause (OpenMPAtClauseKind Kind, SourceLocation KwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'at' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2394 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPAtClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPBindClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPBindClause (OpenMPBindClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'bind' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2360 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPBindClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPCanonicalLoop()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildOMPCanonicalLoop (Stmt * LoopStmt) inline
Build a new OpenMP Canonical loop.
Ensures that the outermost loop in LoopStmt is wrapped by a OMPCanonicalLoop.
Definition at line 1640 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPCanonicalLoop(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPCollapseClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPCollapseClause (Expr * Num, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'collapse' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1751 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPCollapseClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPCopyinClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPCopyinClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'copyin' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1938 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPCopyinClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPCopyprivateClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPCopyprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'copyprivate' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1950 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPCopyprivateClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDefaultClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDefaultClause (DefaultKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'default' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1762 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDefaultClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDefaultmapClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDefaultmapClause (OpenMPDefaultmapClauseModifier M, OpenMPDefaultmapClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'defaultmap' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2203 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDefaultmapClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDependClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDependClause (OMPDependClause::DependDataTy Data, Expr * DepModifier, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'depend' pseudo clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1985 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDependClause(), Data, and clang::TreeTransform< Derived >::getSema().
RebuildOMPDepobjClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDepobjClause (Expr * Depobj, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'depobj' pseudo clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1974 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDepobjClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDestroyClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDestroyClause (Expr * InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'destroy' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2314 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDestroyClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDetachClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDetachClause (Expr * Evt, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'detach' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2112 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDetachClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDeviceClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr * Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'device' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1998 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDeviceClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDistScheduleClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDistScheduleClause (OpenMPDistScheduleClauseKind Kind, Expr * ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'dist_schedule' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2123 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDistScheduleClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPDoacrossClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPDoacrossClause (OpenMPDoacrossClauseModifier DepType, SourceLocation DepLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'doacross' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2430 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPDoacrossClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPExclusiveClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPExclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'exclusive' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2242 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPExclusiveClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPExecutableDirective()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildOMPExecutableDirective (OpenMPDirectiveKind Kind, DeclarationNameInfo DirName, OpenMPDirectiveKind CancelRegion, ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc) inline
Build a new OpenMP executable directive.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1648 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPExecutableDirective(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPFilterClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFilterClause (Expr * ThreadID, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'filter' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2349 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFilterClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPFinalClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFinalClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'final' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1677 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFinalClause(), clang::Condition, and clang::TreeTransform< Derived >::getSema().
RebuildOMPFirstprivateClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFirstprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'firstprivate' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1823 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFirstprivateClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPFlushClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFlushClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'flush' pseudo clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1962 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFlushClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPFromClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFromClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, ArrayRef< Expr * > UnresolvedMappers) inline
Build a new OpenMP 'from' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2152 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFromClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPFullClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPFullClause (SourceLocation StartLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'full' clause.
Definition at line 1724 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPFullClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPGrainsizeClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPGrainsizeClause (OpenMPGrainsizeClauseModifier Modifier, Expr * Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'grainsize' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2076 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPGrainsizeClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPHasDeviceAddrClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPHasDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs) inline
Build a new OpenMP 'has_device_addr' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2194 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPHasDeviceAddrClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPHintClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPHintClause (Expr * Hint, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'hint' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2102 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPHintClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPIfClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPIfClause (OpenMPDirectiveKind NameModifier, Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'if' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1662 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPIfClause(), clang::Condition, and clang::TreeTransform< Derived >::getSema().
RebuildOMPInclusiveClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPInclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'inclusive' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2230 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPInclusiveClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPInitClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPInitClause (Expr * InteropVar, OMPInteropInfo & InteropInfo, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'init' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2290 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPInitClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPInReductionClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPInReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions) inline
Build a new OpenMP 'in_reduction' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1894 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPInReductionClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPIsDevicePtrClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPIsDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs) inline
Build a new OpenMP 'is_device_ptr' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2185 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPIsDevicePtrClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPIteratorExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildOMPIteratorExpr (SourceLocation IteratorKwLoc, SourceLocation LLoc, SourceLocation RLoc, ArrayRef< Sema::OMPIteratorData > Data) inline
Build a new iterator expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2764 of file TreeTransform.h.
References clang::Sema::ActOnOMPIteratorExpr(), Data, and clang::TreeTransform< Derived >::getSema().
RebuildOMPLastprivateClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPLastprivateClause (ArrayRef< Expr * > VarList, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'lastprivate' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1835 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPLastprivateClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPLinearClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPLinearClause (ArrayRef< Expr * > VarList, Expr * Step, SourceLocation StartLoc, SourceLocation LParenLoc, OpenMPLinearClauseKind Modifier, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'linear' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1909 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPLinearClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPMapClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPMapClause (Expr * IteratorModifier, ArrayRef< OpenMPMapModifierKind > MapTypeModifiers, ArrayRef< SourceLocation > MapTypeModifiersLoc, CXXScopeSpec MapperIdScopeSpec, DeclarationNameInfo MapperId, OpenMPMapClauseKind MapType, bool IsMapTypeImplicit, SourceLocation MapLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, ArrayRef< Expr * > UnresolvedMappers) inline
Build a new OpenMP 'map' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2011 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPMapClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPMessageClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPMessageClause (Expr * MS, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'message' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2419 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPMessageClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPNocontextClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNocontextClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'nocontext' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2338 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNocontextClause(), clang::Condition, and clang::TreeTransform< Derived >::getSema().
RebuildOMPNontemporalClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNontemporalClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'nontemporal' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2218 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNontemporalClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPNovariantsClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNovariantsClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'novariants' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2326 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNovariantsClause(), clang::Condition, and clang::TreeTransform< Derived >::getSema().
RebuildOMPNumTasksClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNumTasksClause (OpenMPNumTasksClauseModifier Modifier, Expr * NumTasks, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'num_tasks' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2089 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNumTasksClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPNumTeamsClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNumTeamsClause (Expr * NumTeams, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'num_teams' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2042 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNumTeamsClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPNumThreadsClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPNumThreadsClause (Expr * NumThreads, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'num_threads' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1688 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPNumThreadsClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPOrderClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPOrderClause (OpenMPOrderClauseKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, OpenMPOrderClauseModifier Modifier, SourceLocation ModifierKwLoc) inline
Build a new OpenMP 'order' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2278 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPOrderClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPOrderedClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPOrderedClause (SourceLocation StartLoc, SourceLocation EndLoc, SourceLocation LParenLoc, Expr * Num) inline
Build a new OpenMP 'ordered' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1801 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPOrderedClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPPartialClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPPartialClause (Expr * Factor, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'partial' clause.
Definition at line 1730 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPPartialClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPPriorityClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPPriorityClause (Expr * Priority, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'priority' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2065 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPPriorityClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPPrivateClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPPrivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'private' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1811 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPPrivateClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPProcBindClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPProcBindClause (ProcBindKind Kind, SourceLocation KindKwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'proc_bind' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1774 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPProcBindClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPReductionClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPReductionClause (ArrayRef< Expr * > VarList, OpenMPReductionClauseModifier Modifier, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions) inline
Build a new OpenMP 'reduction' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1862 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPReductionClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPSafelenClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPSafelenClause (Expr * Len, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'safelen' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1700 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPSafelenClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPScheduleClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPScheduleClause (OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, OpenMPScheduleClauseKind Kind, Expr * ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation M1Loc, SourceLocation M2Loc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'schedule' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1787 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPScheduleClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPSeverityClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPSeverityClause (OpenMPSeverityClauseKind Kind, SourceLocation KwLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'severity' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2406 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPSeverityClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPSharedClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPSharedClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'shared' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1850 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPSharedClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPSimdlenClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPSimdlenClause (Expr * Len, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'simdlen' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 1710 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPSimdlenClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPSizesClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPSizesClause (ArrayRef< Expr * > Sizes, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Definition at line 1716 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPSizesClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPTaskReductionClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPTaskReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions) inline
Build a new OpenMP 'task_reduction' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1878 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPTaskReductionClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPThreadLimitClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPThreadLimitClause (Expr * ThreadLimit, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'thread_limit' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2053 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPThreadLimitClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPToClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPToClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, ArrayRef< Expr * > UnresolvedMappers) inline
Build a new OpenMP 'to' clause.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 2136 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPToClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPUseClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPUseClause (Expr * InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'use' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2303 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPUseClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPUseDeviceAddrClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPUseDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs) inline
Build a new OpenMP 'use_device_addr' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2176 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPUseDeviceAddrClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPUseDevicePtrClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPUseDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs) inline
Build a new OpenMP 'use_device_ptr' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2167 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPUseDevicePtrClause(), and clang::TreeTransform< Derived >::getSema().
RebuildOMPUsesAllocatorsClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPUsesAllocatorsClause (ArrayRef< Sema::UsesAllocatorsData > Data, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'uses_allocators' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2254 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPUsesAllocatorClause(), Data, and clang::TreeTransform< Derived >::getSema().
RebuildOMPXDynCGroupMemClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::RebuildOMPXDynCGroupMemClause (Expr * Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build a new OpenMP 'ompx_dyn_cgroup_mem' clause.
By default, performs semantic analysis to build the new OpenMP clause. Subclasses may override this routine to provide different behavior.
Definition at line 2373 of file TreeTransform.h.
References clang::Sema::ActOnOpenMPXDynCGroupMemClause(), and clang::TreeTransform< Derived >::getSema().
RebuildPackExpansion() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildPackExpansion (Expr * Pattern, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions) inline
Build a new expression pack expansion.
By default, performs semantic analysis to build a new pack expansion for an expression. Subclasses may override this routine to provide different behavior.
Definition at line 3914 of file TreeTransform.h.
References clang::Sema::CheckPackExpansion(), and clang::TreeTransform< Derived >::getSema().
RebuildPackExpansion() [2/2]
template<typename Derived > TemplateArgumentLoc clang::TreeTransform< Derived >::RebuildPackExpansion (TemplateArgumentLoc Pattern, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions) inline
Build a new template argument pack expansion.
By default, performs semantic analysis to build a new pack expansion for a template argument. Subclasses may override this routine to provide different behavior.
Definition at line 3867 of file TreeTransform.h.
References clang::Sema::CheckPackExpansion(), clang::Sema::Context, clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getKind(), clang::TreeTransform< Derived >::getSema(), clang::TemplateArgumentLoc::getSourceExpression(), clang::TemplateArgumentLoc::getTemplateNameLoc(), clang::TemplateArgumentLoc::getTemplateQualifierLoc(), clang::TemplateArgumentLoc::getTypeSourceInfo(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::Result, clang::TreeTransform< Derived >::SemaRef, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
RebuildPackExpansionType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildPackExpansionType (QualType Pattern, SourceRange PatternRange, SourceLocation EllipsisLoc, std::optional< unsigned > NumExpansions) inline
Build a new pack expansion type.
By default, builds a new PackExpansionType type from the given pattern. Subclasses may override this routine to provide different behavior.
Definition at line 1247 of file TreeTransform.h.
References clang::Sema::CheckPackExpansion(), and clang::TreeTransform< Derived >::getSema().
RebuildParenExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildParenExpr (Expr * SubExpr, SourceLocation LParen, SourceLocation RParen) inline
Build a new expression in parentheses.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2641 of file TreeTransform.h.
References clang::Sema::ActOnParenExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildParenListExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildParenListExpr (SourceLocation LParenLoc, MultiExprArg SubExprs, SourceLocation RParenLoc) inline
Build a new expression list in parentheses.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2992 of file TreeTransform.h.
References clang::Sema::ActOnParenListExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildParenType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildParenType (QualType InnerType) inline
Build a new parenthesized type.
By default, builds a new ParenType type from the inner type. Subclasses may override this routine to provide different behavior.
Definition at line 1087 of file TreeTransform.h.
References clang::Sema::BuildParenType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildPipeType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildPipeType (QualType ValueType, SourceLocation KWLoc, bool isReadPipe)
Build a new pipe type given its value type.
Definition at line 15100 of file TreeTransform.h.
References clang::Sema::BuildReadPipeType(), and clang::Sema::BuildWritePipeType().
RebuildPointerType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildPointerType (QualType PointeeType, SourceLocation Sigil)
Build a new pointer type given its pointee type.
By default, performs semantic analysis when building the pointer type. Subclasses may override this routine to provide different behavior.
Definition at line 14781 of file TreeTransform.h.
References clang::Sema::BuildPointerType().
RebuildPredefinedExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildPredefinedExpr (SourceLocation Loc, PredefinedExpr::IdentKind IK) inline
Build a new predefined expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2606 of file TreeTransform.h.
References clang::Sema::BuildPredefinedExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildQualifiedType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildQualifiedType (QualType T, QualifiedTypeLoc TL)
Build a new qualified type given its unqualified type and type location.
By default, this routine adds type qualifiers only to types that can have qualifiers, and silently suppresses those qualifiers that are not permitted. Subclasses may override this routine to provide different behavior.
Definition at line 4978 of file TreeTransform.h.
References clang::Sema::BuildQualifiedType(), clang::Sema::Context, clang::Default, clang::Sema::Diag(), clang::Qualifiers::fromCVRMask(), clang::Qualifiers::getAddressSpace(), clang::ASTContext::getAddrSpaceQualType(), clang::Sema::getASTContext(), clang::ASTContext::getAutoType(), clang::TypeLoc::getBeginLoc(), clang::QualType::getLocalQualifiers(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::TypeLoc::getType(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasObjCLifetime(), clang::Qualifiers::hasRestrict(), clang::Type::isDependentType(), clang::Qualifiers::removeObjCLifetime(), and clang::Qualifiers::Restrict.
RebuildRecordType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildRecordType (RecordDecl * Record) inline
Build a new class/struct/union type.
Definition at line 1019 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getTypeDeclType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildRecoveryExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildRecoveryExpr (SourceLocation BeginLoc, SourceLocation EndLoc, ArrayRef< Expr * > SubExprs, QualType Type) inline
Definition at line 3957 of file TreeTransform.h.
References clang::Sema::CreateRecoveryExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildReferenceType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildReferenceType (QualType ReferentType, bool LValue, SourceLocation Sigil)
Build a new reference type given the type it references.
By default, performs semantic analysis when building the reference type. Subclasses may override this routine to provide different behavior.
Parameters
LValue whether the type was written with an lvalue sigil or an rvalue sigil.
Definition at line 14796 of file TreeTransform.h.
References clang::Sema::BuildReferenceType().
RebuildRequiresExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildRequiresExpr (SourceLocation RequiresKWLoc, RequiresExprBodyDecl * Body, ArrayRef< ParmVarDecl * > LocalParameters, ArrayRef< concepts::Requirement * > Requirements, SourceLocation ClosingBraceLoc) inline
Build a new requires expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3604 of file TreeTransform.h.
References clang::Sema::Context, clang::RequiresExpr::Create(), and clang::TreeTransform< Derived >::SemaRef.
RebuildReturnStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildReturnStmt (SourceLocation ReturnLoc, Expr * Result) inline
Build a new return statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1476 of file TreeTransform.h.
References clang::Sema::BuildReturnStmt(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildSEHExceptStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildSEHExceptStmt (SourceLocation Loc, Expr * FilterExpr, Stmt * Block) inline
Definition at line 2586 of file TreeTransform.h.
References clang::Sema::ActOnSEHExceptBlock(), clang::Block, and clang::TreeTransform< Derived >::getSema().
RebuildSEHFinallyStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildSEHFinallyStmt (SourceLocation Loc, Stmt * Block) inline
Definition at line 2591 of file TreeTransform.h.
References clang::Block, clang::SEHFinallyStmt::Create(), and clang::TreeTransform< Derived >::getSema().
RebuildSEHTryStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildSEHTryStmt (bool IsCXXTry, SourceLocation TryLoc, Stmt * TryBlock, Stmt * Handler) inline
Definition at line 2581 of file TreeTransform.h.
References clang::Sema::ActOnSEHTryBlock(), and clang::TreeTransform< Derived >::getSema().
RebuildShuffleVectorExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildShuffleVectorExpr (SourceLocation BuiltinLoc, MultiExprArg SubExprs, SourceLocation RParenLoc) inline
Build a new shuffle vector expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3824 of file TreeTransform.h.
References clang::ASTContext::BuiltinFnTy, clang::cast(), clang::Sema::Context, clang::CallExpr::Create(), clang::DeclContextLookupResult::empty(), clang::DeclContextLookupResult::front(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::IdentifierTable::get(), clang::FunctionDecl::getCallResultType(), clang::ASTContext::getPointerType(), clang::FunctionDecl::getReturnType(), clang::ASTContext::getTranslationUnitDecl(), clang::ValueDecl::getType(), clang::Expr::getValueKindForType(), clang::ASTContext::Idents, clang::Sema::ImpCastExprToType(), clang::DeclContext::lookup(), clang::Sema::SemaBuiltinShuffleVector(), clang::TreeTransform< Derived >::SemaRef, and clang::VK_PRValue.
RebuildSizeOfPackExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildSizeOfPackExpr (SourceLocation OperatorLoc, NamedDecl * Pack, SourceLocation PackLoc, SourceLocation RParenLoc, std::optional< unsigned > Length, ArrayRef< TemplateArgument > PartialArgs) inline
Build a new expression to compute the length of a parameter pack.
Definition at line 3559 of file TreeTransform.h.
References clang::Sema::Context, clang::SizeOfPackExpr::Create(), and clang::TreeTransform< Derived >::SemaRef.
RebuildSourceLocExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildSourceLocExpr (SourceLocExpr::IdentKind Kind, QualType ResultTy, SourceLocation BuiltinLoc, SourceLocation RPLoc, DeclContext * ParentContext) inline
Build a new expression representing a call to a source location builtin.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3573 of file TreeTransform.h.
References clang::Sema::BuildSourceLocExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildStmtExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildStmtExpr (SourceLocation LParenLoc, Stmt * SubStmt, SourceLocation RParenLoc, unsigned TemplateDepth) inline
Build a new GNU statement expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3012 of file TreeTransform.h.
References clang::Sema::BuildStmtExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildSwitchStmtBody()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildSwitchStmtBody (SourceLocation SwitchLoc, Stmt * Switch, Stmt * Body) inline
Attach the body to the switch statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1415 of file TreeTransform.h.
References clang::Sema::ActOnFinishSwitchStmt(), clang::TreeTransform< Derived >::getSema(), and clang::Switch.
RebuildSwitchStmtStart()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildSwitchStmtStart (SourceLocation SwitchLoc, SourceLocation LParenLoc, Stmt * Init, Sema::ConditionResult Cond, SourceLocation RParenLoc) inline
Start building a new switch statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1403 of file TreeTransform.h.
References clang::Sema::ActOnStartOfSwitchStmt(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RebuildSYCLUniqueStableNameExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildSYCLUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, TypeSourceInfo * TSI) inline
Definition at line 2595 of file TreeTransform.h.
References clang::Sema::BuildSYCLUniqueStableNameExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildTemplateIdExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildTemplateIdExpr (const CXXScopeSpec & SS, SourceLocation TemplateKWLoc, LookupResult & R, bool RequiresADL, const TemplateArgumentListInfo * TemplateArgs) inline
Build a new template-id expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3423 of file TreeTransform.h.
References clang::Sema::BuildTemplateIdExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildTemplateName() [1/4]
template<typename Derived > TemplateName clang::TreeTransform< Derived >::RebuildTemplateName (const TemplateArgument & ArgPack, Decl * AssociatedDecl, unsigned Index, bool Final) inline
Build a new template name given a template template parameter pack and the.
By default, performs semantic analysis to determine whether the name can be resolved to a specific template, then builds the appropriate kind of template name. Subclasses may override this routine to provide different behavior.
Definition at line 1316 of file TreeTransform.h.
References clang::Sema::Context, clang::TreeTransform< Derived >::getSema(), and clang::ASTContext::getSubstTemplateTemplateParmPack().
RebuildTemplateName() [2/4]
template<typename Derived > TemplateName clang::TreeTransform< Derived >::RebuildTemplateName (CXXScopeSpec & SS, bool TemplateKW, TemplateDecl * Template)
Build a new template name given a nested name specifier, a flag indicating whether the "template" keyword was provided, and the template that the template name refers to.
By default, builds the new template name directly. Subclasses may override this routine to provide different behavior.
Definition at line 15126 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getQualifiedTemplateName(), and clang::CXXScopeSpec::getScopeRep().
RebuildTemplateName() [3/4]
template<typename Derived > TemplateName clang::TreeTransform< Derived >::RebuildTemplateName (CXXScopeSpec & SS, SourceLocation TemplateKWLoc, const IdentifierInfo & Name, SourceLocation NameLoc, QualType ObjectType, NamedDecl * FirstQualifierInScope, bool AllowInjectedClassName)
Build a new template name given a nested name specifier and the name that is referred to as a template.
By default, performs semantic analysis to determine whether the name can be resolved to a specific template, then builds the appropriate kind of template name. Subclasses may override this routine to provide different behavior.
Definition at line 15135 of file TreeTransform.h.
References clang::OpaquePtr< PtrTy >::get(), and clang::OpaquePtr< QualType >::make().
RebuildTemplateName() [4/4]
template<typename Derived > TemplateName clang::TreeTransform< Derived >::RebuildTemplateName (CXXScopeSpec & SS, SourceLocation TemplateKWLoc, OverloadedOperatorKind Operator, SourceLocation NameLoc, QualType ObjectType, bool AllowInjectedClassName)
Build a new template name given a nested name specifier and the overloaded operator name that is referred to as a template.
By default, performs semantic analysis to determine whether the name can be resolved to a specific template, then builds the appropriate kind of template name. Subclasses may override this routine to provide different behavior.
Definition at line 15154 of file TreeTransform.h.
References clang::OpaquePtr< PtrTy >::get(), and clang::OpaquePtr< QualType >::make().
RebuildTemplateSpecializationType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildTemplateSpecializationType (TemplateName Template, SourceLocation TemplateLoc, TemplateArgumentListInfo & Args)
Build a new template specialization type.
By default, performs semantic analysis when building the template specialization type. Subclasses may override this routine to provide different behavior.
Definition at line 15086 of file TreeTransform.h.
References clang::Sema::CheckTemplateIdType().
RebuildTypedefType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildTypedefType (TypedefNameDecl * Typedef) inline
Build a new typedef type.
Definition at line 1008 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getTypeDeclType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildTypeOfExprType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildTypeOfExprType (Expr * Underlying, SourceLocation Loc, TypeOfKind Kind)
Build a new typeof(expr) type.
By default, performs semantic analysis when building the typeof type. Subclasses may override this routine to provide different behavior.
Definition at line 15062 of file TreeTransform.h.
References clang::Sema::BuildTypeofExprType().
RebuildTypeOfType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildTypeOfType (QualType Underlying, TypeOfKind Kind)
Build a new typeof(type) type.
By default, builds a new TypeOfType with the given underlying type.
Definition at line 15068 of file TreeTransform.h.
References clang::Sema::Context, and clang::ASTContext::getTypeOfType().
RebuildTypeRequirement() [1/2]
template<typename Derived > concepts::TypeRequirement * clang::TreeTransform< Derived >::RebuildTypeRequirement (concepts::Requirement::SubstitutionDiagnostic * SubstDiag) inline
Definition at line 3614 of file TreeTransform.h.
References clang::Sema::BuildTypeRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildTypeRequirement() [2/2]
template<typename Derived > concepts::TypeRequirement * clang::TreeTransform< Derived >::RebuildTypeRequirement (TypeSourceInfo * T) inline
Definition at line 3619 of file TreeTransform.h.
References clang::Sema::BuildTypeRequirement(), and clang::TreeTransform< Derived >::SemaRef.
RebuildTypeTrait()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildTypeTrait (TypeTrait Trait, SourceLocation StartLoc, ArrayRef< TypeSourceInfo * > Args, SourceLocation RParenLoc) inline
Build a new type trait expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3366 of file TreeTransform.h.
References clang::Sema::BuildTypeTrait(), and clang::TreeTransform< Derived >::getSema().
RebuildUnaryExprOrTypeTrait() [1/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildUnaryExprOrTypeTrait (Expr * SubExpr, SourceLocation OpLoc, UnaryExprOrTypeTrait ExprKind, SourceRange R) inline
Build a new sizeof, alignof or vec step expression with an expression argument.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2698 of file TreeTransform.h.
References clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::ExprError(), clang::TreeTransform< Derived >::getSema(), and clang::Result.
RebuildUnaryExprOrTypeTrait() [2/2]
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildUnaryExprOrTypeTrait (TypeSourceInfo * TInfo, SourceLocation OpLoc, UnaryExprOrTypeTrait ExprKind, SourceRange R) inline
Build a new sizeof, alignof or vec_step expression with a type argument.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2686 of file TreeTransform.h.
References clang::Sema::CreateUnaryExprOrTypeTraitExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildUnaryOperator()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildUnaryOperator (SourceLocation OpLoc, UnaryOperatorKind Opc, Expr * SubExpr) inline
Build a new unary operator expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2663 of file TreeTransform.h.
References clang::Sema::BuildUnaryOp(), and clang::TreeTransform< Derived >::getSema().
RebuildUnaryTransformType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildUnaryTransformType (QualType BaseType, UnaryTransformType::UTTKind UKind, SourceLocation Loc)
Build a new unary transform type.
Definition at line 15079 of file TreeTransform.h.
References clang::Sema::BuildUnaryTransformType().
RebuildUnresolvedMemberExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildUnresolvedMemberExpr (Expr * BaseE, QualType BaseType, SourceLocation OperatorLoc, bool IsArrow, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateKWLoc, NamedDecl * FirstQualifierInScope, LookupResult & R, const TemplateArgumentListInfo * TemplateArgs) inline
Build a new member reference expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 3532 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::BuildMemberReferenceExpr(), and clang::TreeTransform< Derived >::SemaRef.
RebuildUnresolvedUsingType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildUnresolvedUsingType (SourceLocation NameLoc, Decl * D)
Rebuild an unresolved typename type, given the decl that the UnresolvedUsingTypenameDecl was transformed to.
Definition at line 15006 of file TreeTransform.h.
References clang::Sema::Context, clang::Sema::DiagnoseUseOfDecl(), clang::Type::getAs(), clang::UsingShadowDecl::getTargetDecl(), clang::ASTContext::getTypeDeclType(), clang::ASTContext::getUsingType(), clang::ASTContext::hasSameType(), clang::Decl::isInvalidDecl(), and clang::QualType::isNull().
RebuildUsingType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildUsingType (UsingShadowDecl * Found, QualType Underlying) inline
Build a new type found via an alias.
Definition at line 1003 of file TreeTransform.h.
References clang::Sema::Context, clang::ASTContext::getUsingType(), and clang::TreeTransform< Derived >::SemaRef.
RebuildVAArgExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::RebuildVAArgExpr (SourceLocation BuiltinLoc, Expr * SubExpr, TypeSourceInfo * TInfo, SourceLocation RParenLoc) inline
Build a new va_arg expression.
By default, performs semantic analysis to build the new expression. Subclasses may override this routine to provide different behavior.
Definition at line 2980 of file TreeTransform.h.
References clang::Sema::BuildVAArgExpr(), and clang::TreeTransform< Derived >::getSema().
RebuildVariableArrayType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildVariableArrayType (QualType ElementType, ArrayType::ArraySizeModifier SizeMod, Expr * SizeExpr, unsigned IndexTypeQuals, SourceRange BracketsRange)
Build a new variable-length array type given the element type, size modifier, size expression, and index type qualifiers.
By default, performs semantic analysis when building the array type. Subclasses may override this routine to provide different behavior.
Definition at line 14909 of file TreeTransform.h.
RebuildVectorType()
template<typename Derived > QualType clang::TreeTransform< Derived >::RebuildVectorType (QualType ElementType, unsigned NumElements, VectorType::VectorKind VecKind)
Build a new vector type given the element type and number of elements.
By default, performs semantic analysis when building the vector type. Subclasses may override this routine to provide different behavior.
Definition at line 14940 of file TreeTransform.h.
References clang::Sema::Context, and clang::ASTContext::getVectorType().
RebuildWhileStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::RebuildWhileStmt (SourceLocation WhileLoc, SourceLocation LParenLoc, Sema::ConditionResult Cond, SourceLocation RParenLoc, Stmt * Body) inline
Build a new while statement.
By default, performs semantic analysis to build the new statement. Subclasses may override this routine to provide different behavior.
Definition at line 1424 of file TreeTransform.h.
References clang::Sema::ActOnWhileStmt(), clang::Cond, and clang::TreeTransform< Derived >::getSema().
RememberPartiallySubstitutedPack()
template<typename Derived > void clang::TreeTransform< Derived >::RememberPartiallySubstitutedPack (TemplateArgument Arg) inline
"Remember" the partially-substituted pack template argument after performing an instantiation that must preserve the parameter pack use.
This routine is meant to be overridden by the template instantiator.
Definition at line 304 of file TreeTransform.h.
ReplacingOriginal()
template<typename Derived > bool clang::TreeTransform< Derived >::ReplacingOriginal () inline
Whether the transformation is forming an expression or statement that replaces the original.
In this case, we'll reuse mangling numbers from existing lambdas.
Definition at line 162 of file TreeTransform.h.
setBase()
template<typename Derived > void clang::TreeTransform< Derived >::setBase (SourceLocation Loc, DeclarationName Entity) inline
Sets the "base" location and entity when that information is known based on another transformation.
By default, the source location and entity are ignored. Subclasses can override this function to provide a customized implementation.
Definition at line 191 of file TreeTransform.h.
SkipLambdaBody()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::SkipLambdaBody (LambdaExpr * E, Stmt * Body)
Alternative implementation of TransformLambdaBody that skips transforming the body.
Definition at line 13614 of file TreeTransform.h.
References clang::C, clang::LambdaExpr::capture_begin(), clang::LambdaExpr::capture_end(), clang::Decl::getLocation(), clang::LambdaExpr::isInitCapture(), clang::Decl::isInvalidDecl(), clang::LCK_StarThis, and clang::StmtError().
TransformAddressOfOperand()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformAddressOfOperand (Expr * E)
The operand of a unary address-of operator has special rules: it's allowed to refer to a non-static member of a class even if there's no 'this' object available.
Definition at line 10967 of file TreeTransform.h.
TransformAttr()
template<typename Derived > const Attr * clang::TreeTransform< Derived >::TransformAttr (const Attr * S)
Transform the given attribute.
By default, this routine transforms a statement by delegating to the appropriate TransformXXXAttr function to transform a specific kind of attribute. Subclasses may override this function to transform attributed statements/types using some other mechanism.
Returns
the transformed attribute
Definition at line 7602 of file TreeTransform.h.
References clang::Attr::getKind().
transformAttrs()
template<typename Derived > void clang::TreeTransform< Derived >::transformAttrs (Decl * Old, Decl * New) inline
Transform the attributes associated with the given declaration and place them on the new declaration.
By default, this operation does nothing. Subclasses may override this behavior to transform attributes.
Definition at line 492 of file TreeTransform.h.
TransformCompoundStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::TransformCompoundStmt (CompoundStmt * S, bool IsStmtExpr)
Definition at line 7472 of file TreeTransform.h.
TransformCondition()
template<typename Derived > Sema::ConditionResult clang::TreeTransform< Derived >::TransformCondition (SourceLocation Loc, VarDecl * Var, Expr * Expr, Sema::ConditionKind Kind)
Transform the specified condition.
By default, this transforms the variable and expression and rebuilds the condition.
Definition at line 4255 of file TreeTransform.h.
References clang::Sema::ConditionError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getLocation(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
TransformCXXNamedCastExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformCXXNamedCastExpr (CXXNamedCastExpr * E)
Definition at line 12104 of file TreeTransform.h.
References clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CXXNamedCastExpr::getAngleBrackets(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::CXXNamedCastExpr::getOperatorLoc(), clang::CXXNamedCastExpr::getRParenLoc(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), clang::CastExpr::getSubExprAsWritten(), clang::ExplicitCastExpr::getTypeInfoAsWritten(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
TransformDecl()
template<typename Derived > Decl * clang::TreeTransform< Derived >::TransformDecl (SourceLocation Loc, Decl * D) inline
Transform the given declaration, which is referenced from a type or expression.
By default, acts as the identity function on declarations, unless the transformer has had to transform the declaration itself. Subclasses may override this function to provide alternate behavior.
Definition at line 470 of file TreeTransform.h.
References clang::TreeTransform< Derived >::TransformedLocalDecls.
Referenced by clang::TreeTransform< Derived >::TransformFirstQualifierInScope().
TransformDeclarationNameInfo()
template<typename Derived > DeclarationNameInfo clang::TreeTransform< Derived >::TransformDeclarationNameInfo (const DeclarationNameInfo & NameInfo)
Transform the given declaration name.
By default, transforms the types of conversion function, constructor, and destructor names and then (if needed) rebuilds the declaration name. Identifiers and selectors are returned unmodified. Subclasses may override this function to provide alternate behavior.
Definition at line 4397 of file TreeTransform.h.
References clang::Sema::Context, clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::ASTContext::DeclarationNames, clang::ASTContext::getCanonicalType(), clang::DeclarationNameTable::getCXXDeductionGuideName(), clang::DeclarationNameTable::getCXXSpecialName(), clang::DeclarationNameInfo::getLoc(), clang::DeclarationNameInfo::getName(), clang::DeclarationNameInfo::getNamedTypeInfo(), clang::TypeSourceInfo::getType(), clang::DeclarationName::Identifier, clang::QualType::isNull(), clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::DeclarationNameInfo::setName(), and clang::DeclarationNameInfo::setNamedTypeInfo().
TransformDefinition()
template<typename Derived > Decl * clang::TreeTransform< Derived >::TransformDefinition (SourceLocation Loc, Decl * D) inline
Transform the definition of the given declaration.
By default, invokes TransformDecl() to transform the declaration. Subclasses may override this function to provide alternate behavior.
Definition at line 511 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getDerived().
TransformDependentScopeDeclRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformDependentScopeDeclRefExpr (DependentScopeDeclRefExpr * E, bool IsAddressOfOperand, TypeSourceInfo ** RecoveryTSI)
Definition at line 13088 of file TreeTransform.h.
TransformDependentTemplateSpecializationType() [1/2]
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType (TypeLocBuilder & TLB, DependentTemplateSpecializationTypeLoc TL, NestedNameSpecifierLoc QualifierLoc)
Definition at line 7185 of file TreeTransform.h.
References clang::DependentTemplateSpecializationTypeLoc::getElaboratedKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::getLAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::getNumArgs(), clang::DependentTemplateSpecializationTypeLoc::getRAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::getTemplateKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::getTemplateNameLoc(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::TypeLocBuilder::push(), clang::Result, clang::DependentTemplateSpecializationTypeLoc::setArgLocInfo(), clang::TemplateSpecializationTypeLoc::setArgLocInfo(), clang::DependentTemplateSpecializationTypeLoc::setElaboratedKeywordLoc(), clang::ElaboratedTypeLoc::setElaboratedKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::setLAngleLoc(), clang::TemplateArgumentListInfo::setLAngleLoc(), clang::TemplateSpecializationTypeLoc::setLAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::setQualifierLoc(), clang::ElaboratedTypeLoc::setQualifierLoc(), clang::DependentTemplateSpecializationTypeLoc::setRAngleLoc(), clang::TemplateArgumentListInfo::setRAngleLoc(), clang::TemplateSpecializationTypeLoc::setRAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::setTemplateKeywordLoc(), clang::TemplateSpecializationTypeLoc::setTemplateKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::setTemplateNameLoc(), clang::TemplateSpecializationTypeLoc::setTemplateNameLoc(), and clang::TemplateArgumentListInfo::size().
TransformDependentTemplateSpecializationType() [2/2]
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType (TypeLocBuilder & TLB, DependentTemplateSpecializationTypeLoc TL, TemplateName Template, CXXScopeSpec & SS)
FIXME: Wrap this in an elaborated-type-specifier?
Definition at line 6917 of file TreeTransform.h.
References clang::TemplateArgumentListInfo::arguments(), clang::Sema::Context, clang::TemplateName::getAsDependentTemplateName(), clang::DependentTemplateSpecializationTypeLoc::getElaboratedKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::getLAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::getNumArgs(), clang::DependentTemplateSpecializationTypeLoc::getRAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::getTemplateKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::getTemplateNameLoc(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::CXXScopeSpec::getWithLocInContext(), clang::TypeLocBuilder::push(), clang::Result, clang::DependentTemplateSpecializationTypeLoc::setArgLocInfo(), clang::TemplateSpecializationTypeLoc::setArgLocInfo(), clang::DependentTemplateSpecializationTypeLoc::setElaboratedKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::setLAngleLoc(), clang::TemplateArgumentListInfo::setLAngleLoc(), clang::TemplateSpecializationTypeLoc::setLAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::setQualifierLoc(), clang::DependentTemplateSpecializationTypeLoc::setRAngleLoc(), clang::TemplateArgumentListInfo::setRAngleLoc(), clang::TemplateSpecializationTypeLoc::setRAngleLoc(), clang::DependentTemplateSpecializationTypeLoc::setTemplateKeywordLoc(), clang::TemplateSpecializationTypeLoc::setTemplateKeywordLoc(), clang::DependentTemplateSpecializationTypeLoc::setTemplateNameLoc(), clang::TemplateSpecializationTypeLoc::setTemplateNameLoc(), and clang::TemplateArgumentListInfo::size().
transformedLocalDecl()
template<typename Derived > void clang::TreeTransform< Derived >::transformedLocalDecl (Decl * Old, ArrayRef< Decl * > New) inline
Note that a local declaration has been transformed by this transformer.
Local declarations are typically transformed via a call to TransformDefinition. However, in some cases (e.g., lambda expressions), the transformer itself has to transform the declarations. This routine can be overridden by a subclass that keeps track of such mappings.
Definition at line 501 of file TreeTransform.h.
References clang::TreeTransform< Derived >::TransformedLocalDecls.
TransformExceptionSpec()
template<typename Derived > bool clang::TreeTransform< Derived >::TransformExceptionSpec (SourceLocation Loc, FunctionProtoType::ExceptionSpecInfo & ESI, SmallVectorImpl< QualType > & Exceptions, bool & Changed)
Definition at line 6165 of file TreeTransform.h.
References clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::collectUnexpandedParameterPacks(), clang::Sema::ConstantEvaluated, clang::Sema::Context, clang::EST_Dynamic, clang::EST_DynamicNone, clang::EST_Unevaluated, clang::EST_Uninstantiated, clang::FunctionProtoType::ExceptionSpecInfo::Exceptions, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getPackExpansionType(), clang::isComputedNoexcept(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::FunctionProtoType::ExceptionSpecInfo::NoexceptExpr, clang::FunctionProtoType::ExceptionSpecInfo::Type, and clang::Unevaluated.
TransformExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformExpr (Expr * E)
Transform the given expression.
By default, this routine transforms an expression by delegating to the appropriate TransformXXXExpr function to build a new expression. Subclasses may override this function to transform expressions using some other mechanism.
Returns
the transformed expression.
Definition at line 4038 of file TreeTransform.h.
References clang::Stmt::getStmtClass(), and clang::Stmt::NoStmtClass.
TransformExprRequirement()
template<typename Derived > concepts::ExprRequirement * clang::TreeTransform< Derived >::TransformExprRequirement (concepts::ExprRequirement * Req)
Definition at line 12968 of file TreeTransform.h.
References clang::Sema::CheckPlaceholderExpr(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::concepts::ExprRequirement::getExpr(), clang::concepts::ExprRequirement::getExprSubstitutionDiagnostic(), clang::concepts::ExprRequirement::getNoexceptLoc(), clang::concepts::ExprRequirement::getReturnTypeRequirement(), clang::Expr::hasPlaceholderType(), clang::concepts::ExprRequirement::isExprSubstitutionFailure(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::concepts::ExprRequirement::isSimple(), and clang::ActionResult< PtrTy, CompressInvalid >::isUsable().
TransformExprs()
template<typename Derived > bool clang::TreeTransform< Derived >::TransformExprs (Expr *const * Inputs, unsigned NumInputs, bool IsCall, SmallVectorImpl< Expr * > & Outputs, bool * ArgChanged = nullptr)
Transform the given list of expressions.
This routine transforms a list of expressions by invoking TransformExpr() for each subexpression. However, it also provides support for variadic templates by expanding any pack expansions (if the derived class permits such expansion) along the way. When pack expansions are present, the number of outputs may not equal the number of inputs.
Parameters
Inputs The set of expressions to be transformed.
NumInputs The number of expressions in Inputs.
IsCall If true, then this transform is being performed on function-call arguments, and any arguments that should be dropped, will be.
Outputs The transformed input expressions will be added to this vector.
ArgChanged If non-NULL, will be set true if any argument changed due to transformation.
Returns
true if an error occurred, false otherwise.
Definition at line 4142 of file TreeTransform.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getSourceRange(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::Result.
TransformFirstQualifierInScope()
template<typename Derived > NamedDecl * clang::TreeTransform< Derived >::TransformFirstQualifierInScope (NamedDecl * D, SourceLocation Loc) inline
Transform the given declaration, which was the first part of a nested-name-specifier in a member access expression.
This specific declaration transformation only applies to the first identifier in a nested-name-specifier of a member access expression, e.g., the T in x->T::member
By default, invokes TransformDecl() to transform the declaration. Subclasses may override this function to provide alternate behavior.
Definition at line 524 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getDerived(), and clang::TreeTransform< Derived >::TransformDecl().
TransformFunctionProtoType() [1/2]
template<typename Derived > template<typename Derived > QualType clang::TreeTransform< Derived >::TransformFunctionProtoType (TypeLocBuilder & TLB, FunctionProtoTypeLoc TL)
Definition at line 6058 of file TreeTransform.h.
References clang::TypeLoc::getBeginLoc().
TransformFunctionProtoType() [2/2]
template<typename Derived > template<typename Fn > QualType clang::TreeTransform< Derived >::TransformFunctionProtoType (TypeLocBuilder & TLB, FunctionProtoTypeLoc TL, CXXRecordDecl * ThisContext, Qualifiers ThisTypeQuals, Fn TransformExceptionSpec)
Definition at line 6071 of file TreeTransform.h.
References clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::FunctionProtoType::ExtProtoInfo::ExtParameterInfos, clang::TypeLoc::getBeginLoc(), clang::FunctionTypeLoc::getExceptionSpecRange(), clang::FunctionTypeLoc::getLocalRangeBegin(), clang::FunctionTypeLoc::getLocalRangeEnd(), clang::FunctionTypeLoc::getLParenLoc(), clang::FunctionTypeLoc::getNumParams(), clang::FunctionTypeLoc::getParams(), clang::Sema::ExtParameterInfoBuilder::getPointerOrNull(), clang::FunctionTypeLoc::getReturnLoc(), clang::FunctionTypeLoc::getRParenLoc(), clang::TypeLoc::getType(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::QualType::isNull(), clang::FunctionProtoType::param_type_begin(), clang::TypeLocBuilder::push(), clang::Result, clang::FunctionTypeLoc::setExceptionSpecRange(), clang::FunctionTypeLoc::setLocalRangeBegin(), clang::FunctionTypeLoc::setLocalRangeEnd(), clang::FunctionTypeLoc::setLParenLoc(), clang::FunctionTypeLoc::setParam(), and clang::FunctionTypeLoc::setRParenLoc().
TransformFunctionTypeParam()
template<typename Derived > ParmVarDecl * clang::TreeTransform< Derived >::TransformFunctionTypeParam (ParmVarDecl * OldParm, int indexAdjustment, std::optional< unsigned > NumExpansions, bool ExpectParameterPack)
Transforms a single function-type parameter.
Return null on error.
Parameters
indexAdjustment - A number to add to the parameter's scope index; can be negative
Definition at line 5767 of file TreeTransform.h.
References clang::TypeLoc::castAs(), clang::Sema::Context, clang::ParmVarDecl::Create(), clang::Decl::getDeclContext(), clang::PackExpansionTypeLoc::getEllipsisLoc(), clang::TypeLoc::getFullDataSize(), clang::ParmVarDecl::getFunctionScopeDepth(), clang::ParmVarDecl::getFunctionScopeIndex(), clang::NamedDecl::getIdentifier(), clang::DeclaratorDecl::getInnerLocStart(), clang::Decl::getLocation(), clang::PackExpansionTypeLoc::getPatternLoc(), clang::TypeLoc::getSourceRange(), clang::VarDecl::getStorageClass(), clang::TypeSourceInfo::getType(), clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::Result, clang::PackExpansionTypeLoc::setEllipsisLoc(), and clang::ParmVarDecl::setScopeInfo().
TransformFunctionTypeParams() [1/2]
template<typename Derived > bool clang::TreeTransform< Derived >::TransformFunctionTypeParams (SourceLocation Loc, ArrayRef< ParmVarDecl * > Params, const QualType * ParamTypes, const FunctionProtoType::ExtParameterInfo * ParamInfos, SmallVectorImpl< QualType > & PTypes, SmallVectorImpl< ParmVarDecl * > * PVars, Sema::ExtParameterInfoBuilder & PInfos) inline
Definition at line 716 of file TreeTransform.h.
References clang::TreeTransform< Derived >::getDerived().
TransformFunctionTypeParams() [2/2]
template<typename Derived > bool clang::TreeTransform< Derived >::TransformFunctionTypeParams (SourceLocation Loc, ArrayRef< ParmVarDecl * > Params, const QualType * ParamTypes, const FunctionProtoType::ExtParameterInfo * ParamInfos, SmallVectorImpl< QualType > & PTypes, SmallVectorImpl< ParmVarDecl * > * PVars, Sema::ExtParameterInfoBuilder & PInfos, unsigned * LastParamTransformed)
Transforms the parameters of a function type into the given vectors.
The result vectors should be kept in sync; null entries in the variables vector are acceptable.
LastParamTransformed, if non-null, will be set to the index of the last parameter on which transfromation was started. In the event of an error, this will contain the parameter which failed to instantiate.
Return true on error.
Definition at line 5823 of file TreeTransform.h.
References clang::TypeLoc::castAs(), clang::Sema::collectUnexpandedParameterPacks(), clang::Type::containsUnexpandedParameterPack(), clang::PackExpansionTypeLoc::getEllipsisLoc(), clang::PackExpansionTypeLoc::getPatternLoc(), clang::ValueDecl::getType(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::QualType::isNull(), clang::VarDecl::isParameterPack(), and clang::Sema::ExtParameterInfoBuilder::set().
Referenced by clang::TreeTransform< Derived >::TransformRequiresTypeParams().
TransformInitializer()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformInitializer (Expr * Init, bool NotCopyInit)
Transform the given initializer.
By default, this routine transforms an initializer by stripping off the semantic nodes added by initialization, then passing the result to TransformExpr or TransformExprs.
Returns
the transformed initializer.
Definition at line 4055 of file TreeTransform.h.
References clang::ExprEmpty(), clang::ExprError(), clang::CXXConstructExpr::getArg(), clang::CXXConstructExpr::getArgs(), clang::CXXConstructExpr::getBeginLoc(), clang::CXXConstructExpr::getEndLoc(), clang::CXXConstructExpr::getNumArgs(), clang::CXXConstructExpr::getParenOrBraceRange(), clang::OpaqueValueExpr::getSourceExpr(), clang::EnterExpressionEvaluationContext::InitList, clang::CXXConstructExpr::isListInitialization(), and clang::CXXConstructExpr::isStdInitListInitialization().
TransformLambdaBody()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::TransformLambdaBody (LambdaExpr * E, Stmt * Body)
Transform the body of a lambda-expression.
Definition at line 13608 of file TreeTransform.h.
TransformNestedNameSpecifierLoc()
template<typename Derived > NestedNameSpecifierLoc clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS, QualType ObjectType = QualType(), NamedDecl * FirstQualifierInScope = nullptr)
Transform the given nested-name-specifier with source-location information.
By default, transforms all of the types and declarations within the nested-name-specifier. Subclasses may override this function to provide alternate behavior.
Definition at line 4281 of file TreeTransform.h.
References clang::CXXScopeSpec::Adopt(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::Context, clang::Sema::Diag(), clang::Qualifiers::empty(), clang::CXXScopeSpec::Extend(), clang::TypeLoc::getAs(), clang::TypeLoc::getAsAdjusted(), clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsRecordDecl(), clang::NestedNameSpecifierLoc::getBeginLoc(), clang::TypeLoc::getBeginLoc(), clang::NestedNameSpecifierLoc::getEndLoc(), clang::NestedNameSpecifier::getKind(), clang::Sema::getLangOpts(), clang::NestedNameSpecifierLoc::getLocalBeginLoc(), clang::NestedNameSpecifierLoc::getLocalEndLoc(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getOpaqueData(), clang::CXXScopeSpec::getRange(), clang::CXXScopeSpec::getScopeRep(), clang::TypeLoc::getType(), clang::TypedefTypeLoc::getTypedefNameDecl(), clang::NestedNameSpecifierLoc::getTypeLoc(), clang::CXXScopeSpec::getWithLocInContext(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, clang::Decl::isInvalidDecl(), clang::CXXScopeSpec::location_data(), clang::CXXScopeSpec::location_size(), clang::CXXScopeSpec::MakeGlobal(), clang::CXXScopeSpec::MakeSuper(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
TransformNestedRequirement()
template<typename Derived > concepts::NestedRequirement * clang::TreeTransform< Derived >::TransformNestedRequirement (concepts::NestedRequirement * Req)
Definition at line 13008 of file TreeTransform.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::concepts::NestedRequirement::getConstraintExpr(), clang::concepts::NestedRequirement::getConstraintSatisfaction(), clang::concepts::NestedRequirement::getInvalidConstraintEntity(), clang::concepts::NestedRequirement::hasInvalidConstraint(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
TransformOMPClause()
template<typename Derived > OMPClause * clang::TreeTransform< Derived >::TransformOMPClause (OMPClause * S)
Transform the given statement.
By default, this routine transforms a statement by delegating to the appropriate TransformOMPXXXClause function to transform a specific kind of clause. Subclasses may override this function to transform statements using some other mechanism.
Returns
the transformed OpenMP clause.
Definition at line 4019 of file TreeTransform.h.
TransformOMPExecutableDirective()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::TransformOMPExecutableDirective (OMPExecutableDirective * S)
Definition at line 8750 of file TreeTransform.h.
References clang::cast(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::isOpenMPLoopDirective(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), and clang::StmtError().
TransformOverloadExprDecls()
template<typename Derived > bool clang::TreeTransform< Derived >::TransformOverloadExprDecls (OverloadExpr * Old, bool RequiresADL, LookupResult & R)
Transform the set of declarations in an OverloadExpr.
Definition at line 12604 of file TreeTransform.h.
References clang::LookupResult::addDecl(), clang::cast(), clang::LookupResult::clear(), clang::OverloadExpr::decls(), clang::OverloadExpr::getName(), clang::OverloadExpr::getNameLoc(), clang::isa(), and clang::LookupResult::resolveKind().
TransformParenDependentScopeDeclRefExpr()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformParenDependentScopeDeclRefExpr (ParenExpr * PE, DependentScopeDeclRefExpr * DRE, bool IsAddressOfOperand, TypeSourceInfo ** RecoveryTSI)
Definition at line 13070 of file TreeTransform.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ParenExpr::getLParen(), clang::ParenExpr::getRParen(), and clang::ActionResult< PtrTy, CompressInvalid >::isUsable().
TransformReferenceType()
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformReferenceType (TypeLocBuilder & TLB, ReferenceTypeLoc TL)
Transforms a reference type.
Note that somewhat paradoxically we don't care whether the type itself is an l-value type or an r-value type; we only care if the type was written as an l-value type or an r-value type.
Definition at line 5241 of file TreeTransform.h.
References clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getPointeeLoc(), clang::ReferenceType::getPointeeTypeAsWritten(), clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::getSigilLoc(), clang::TypeLoc::getType(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::QualType::isNull(), clang::TypeLocBuilder::push(), clang::Result, clang::PointerLikeTypeLoc< Derived, TypeClass, LocalData >::setSigilLoc(), and clang::TypeLocBuilder::TypeWasModifiedSafely().
TransformRequiresExprRequirements()
template<typename Derived > bool clang::TreeTransform< Derived >::TransformRequiresExprRequirements (ArrayRef< concepts::Requirement * > Reqs, llvm::SmallVectorImpl< concepts::Requirement * > & Transformed)
Definition at line 12931 of file TreeTransform.h.
TransformRequiresTypeParams()
template<typename Derived > ExprResult clang::TreeTransform< Derived >::TransformRequiresTypeParams (SourceLocation KWLoc, SourceLocation RBraceLoc, const RequiresExpr * RE, RequiresExprBodyDecl * Body, ArrayRef< ParmVarDecl * > Params, SmallVectorImpl< QualType > & PTypes, SmallVectorImpl< ParmVarDecl * > & TransParams, Sema::ExtParameterInfoBuilder & PInfos) inline
Transforms the parameters of a requires expresison into the given vectors.
The result vectors should be kept in sync; null entries in the variables vector are acceptable.
Returns an unset ExprResult on success. Returns an ExprResult the 'not satisfied' RequiresExpr if subsitution failed, OR an ExprError, both of which are cases where transformation shouldn't continue.
Definition at line 734 of file TreeTransform.h.
References clang::ExprError(), clang::TreeTransform< Derived >::getDerived(), and clang::TreeTransform< Derived >::TransformFunctionTypeParams().
TransformSEHHandler()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::TransformSEHHandler (Stmt * Handler)
Definition at line 8723 of file TreeTransform.h.
TransformStmt()
template<typename Derived > StmtResult clang::TreeTransform< Derived >::TransformStmt (Stmt * S, StmtDiscardKind SDK = SDK_Discarded)
Transform the given statement.
By default, this routine transforms a statement by delegating to the appropriate TransformXXXStmt function to transform a specific kind of statement or the TransformExpr() function to transform an expression. Subclasses may override this function to transform statements using some other mechanism.
Returns
the transformed statement.
Definition at line 3983 of file TreeTransform.h.
References clang::Stmt::NoStmtClass.
TransformStmtAttr()
template<typename Derived > const Attr * clang::TreeTransform< Derived >::TransformStmtAttr (const Stmt * OrigS, const Stmt * InstS, const Attr * A)
Definition at line 7617 of file TreeTransform.h.
References clang::Attr::getKind().
TransformSubstTemplateTypeParmPackType()
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformSubstTemplateTypeParmPackType (TypeLocBuilder & TLB, SubstTemplateTypeParmPackTypeLoc TL, bool SuppressObjCLifetime)
Definition at line 6605 of file TreeTransform.h.
TransformTemplateArgument()
template<typename Derived > bool clang::TreeTransform< Derived >::TransformTemplateArgument (const TemplateArgumentLoc & Input, TemplateArgumentLoc & Output, bool Uneval = false)
Transform the given template argument.
By default, this operation transforms the type, expression, or declaration stored within the template argument and constructs a new template argument from the transformed result. Subclasses may override this function to provide alternate behavior.
Returns true if there was an error.
Definition at line 4549 of file TreeTransform.h.
References clang::Sema::ActOnConstantExpression(), clang::CXXScopeSpec::Adopt(), clang::Sema::ConstantEvaluated, clang::Sema::Context, clang::TemplateArgument::Declaration, clang::Sema::ExpressionEvaluationContextRecord::EK_TemplateArgument, clang::TemplateArgument::Expression, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNonTypeTemplateArgumentType(), clang::TemplateArgumentLoc::getSourceExpression(), clang::TemplateArgumentLoc::getTemplateNameLoc(), clang::TemplateArgumentLoc::getTemplateQualifierLoc(), clang::TypeSourceInfo::getType(), clang::TemplateArgumentLoc::getTypeSourceInfo(), clang::TemplateArgument::Integral, clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::QualType::isNull(), clang::TemplateName::isNull(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::Sema::ReuseLambdaContextDecl, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, clang::Sema::Unevaluated, and clang::Unevaluated.
TransformTemplateArguments() [1/2]
template<typename Derived > bool clang::TreeTransform< Derived >::TransformTemplateArguments (const TemplateArgumentLoc * Inputs, unsigned NumInputs, TemplateArgumentListInfo & Outputs, bool Uneval = false) inline
Transform the given set of template arguments.
By default, this operation transforms all of the template arguments in the input set using TransformTemplateArgument(), and appends the transformed arguments to the output list.
Note that this overload of TransformTemplateArguments() is merely a convenience function. Subclasses that wish to override this behavior should override the iterator-based member template version.
Parameters
Inputs The set of template arguments to be transformed.
NumInputs The number of template arguments in Inputs.
Outputs The set of transformed template arguments output by this routine.
Returns true if an error occurred.
Definition at line 618 of file TreeTransform.h.
References clang::TreeTransform< Derived >::TransformTemplateArguments().
Referenced by clang::TreeTransform< Derived >::TransformTemplateArguments().
TransformTemplateArguments() [2/2]
template<typename Derived > template<typename InputIterator > bool clang::TreeTransform< Derived >::TransformTemplateArguments (InputIterator First, InputIterator Last, TemplateArgumentListInfo & Outputs, bool Uneval = false)
Transform the given set of template arguments.
By default, this operation transforms all of the template arguments in the input set using TransformTemplateArgument(), and appends the transformed arguments to the output list.
Parameters
First An iterator to the first template argument.
Last An iterator one step past the last template argument.
Outputs The set of transformed template arguments output by this routine.
Returns true if an error occurred.
Definition at line 4717 of file TreeTransform.h.
References clang::TemplateArgumentListInfo::addArgument(), clang::First, clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgument::getKind(), clang::TemplateArgumentLoc::getSourceRange(), clang::TemplateArgument::isPackExpansion(), clang::Last, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_begin(), and clang::TemplateArgument::pack_end().
TransformTemplateDepth()
template<typename Derived > unsigned clang::TreeTransform< Derived >::TransformTemplateDepth (unsigned Depth) inline
Transform a template parameter depth level.
During a transformation that transforms template parameters, this maps an old template parameter depth to a new depth.
Definition at line 230 of file TreeTransform.h.
TransformTemplateName()
template<typename Derived > TemplateName clang::TreeTransform< Derived >::TransformTemplateName (CXXScopeSpec & SS, TemplateName Name, SourceLocation NameLoc, QualType ObjectType = QualType(), NamedDecl * FirstQualifierInScope = nullptr, bool AllowInjectedClassName = false)
Transform the given template name.
Parameters
SS The nested-name-specifier that qualifies the template name. This nested-name-specifier must already have been transformed.
Name The template name to transform.
NameLoc The source location of the template name.
ObjectType If we're translating a template name within a member access expression, this is the type of the object whose member template is being referenced.
FirstQualifierInScope If the first part of a nested-name-specifier also refers to a name within the current (lexical) scope, this is the declaration it refers to.
By default, transforms the template name by transforming the declarations and nested-name-specifiers that occur within the template name. Subclasses may override this function to provide alternate behavior.
Definition at line 4460 of file TreeTransform.h.
References clang::CXXScopeSpec::getScopeRep(), and clang::QualType::isNull().
TransformTemplateParameterList()
template<typename Derived > TemplateParameterList * clang::TreeTransform< Derived >::TransformTemplateParameterList (TemplateParameterList * TPL) inline
Definition at line 769 of file TreeTransform.h.
TransformTemplateSpecializationType()
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformTemplateSpecializationType (TypeLocBuilder & TLB, TemplateSpecializationTypeLoc TL, TemplateName Template)
Definition at line 6619 of file TreeTransform.h.
References clang::TemplateSpecializationTypeLoc::getTemplateNameLoc(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and clang::TemplateName::isNull().
TransformTemplateTypeParmType()
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformTemplateTypeParmType (TypeLocBuilder & TLB, TemplateTypeParmTypeLoc TL, bool SuppressObjCLifetime)
Definition at line 6562 of file TreeTransform.h.
TransformType() [1/3]
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformType (QualType T)
Transforms the given type into another type.
By default, this routine transforms a type by creating a TypeSourceInfo for it and delegating to the appropriate function. This is expensive, but we don't mind, because this method is deprecated anyway; all users should be switched to storing TypeSourceInfos.
Returns
the transformed type.
Definition at line 4840 of file TreeTransform.h.
References clang::TypeSourceInfo::getType().
TransformType() [2/3]
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformType (TypeLocBuilder & TLB, TypeLoc TL)
Transform the given type-with-location into a new type, collecting location information in the given builder as necessary.
Definition at line 4879 of file TreeTransform.h.
TransformType() [3/3]
template<typename Derived > TypeSourceInfo * clang::TreeTransform< Derived >::TransformType (TypeSourceInfo * DI)
Transforms the given type-with-location into a new type-with-location.
By default, this routine transforms a type by delegating to the appropriate TransformXXXType to build a new type. Subclasses may override this function (to take over all type transformations) or some set of the TransformXXXType functions to alter the transformation.
Definition at line 4858 of file TreeTransform.h.
References clang::Sema::Context, clang::TypeLoc::getBeginLoc(), clang::TypeLoc::getFullDataSize(), clang::TypeSourceInfo::getType(), clang::TypeSourceInfo::getTypeLoc(), clang::TypeLocBuilder::getTypeSourceInfo(), clang::TypeLocBuilder::reserve(), and clang::Result.
TransformTypeRequirement()
template<typename Derived > concepts::TypeRequirement * clang::TreeTransform< Derived >::TransformTypeRequirement (concepts::TypeRequirement * Req)
Definition at line 12952 of file TreeTransform.h.
References clang::concepts::TypeRequirement::getSubstitutionDiagnostic(), clang::concepts::TypeRequirement::getType(), and clang::concepts::TypeRequirement::isSubstitutionFailure().
TransformTypeWithDeducedTST() [1/2]
template<typename Derived > QualType clang::TreeTransform< Derived >::TransformTypeWithDeducedTST (QualType T)
Transform a type that is permitted to produce a DeducedTemplateSpecializationType.
This is used in the (relatively rare) contexts where it is acceptable for transformation to produce a class template type with deduced template arguments.
Definition at line 4893 of file TreeTransform.h.
References clang::TypeSourceInfo::getType().
TransformTypeWithDeducedTST() [2/2]
template<typename Derived > TypeSourceInfo * clang::TreeTransform< Derived >::TransformTypeWithDeducedTST (TypeSourceInfo * DI)
Definition at line 4907 of file TreeTransform.h.
References clang::TypeLoc::castAs(), clang::Sema::Context, clang::TypeLoc::getAs(), clang::TypeLoc::getBeginLoc(), clang::TypeLoc::getFullDataSize(), clang::TypeSourceInfo::getType(), clang::TypeSourceInfo::getTypeLoc(), clang::TypeLocBuilder::getTypeSourceInfo(), clang::TypeLoc::getUnqualifiedLoc(), clang::TypeLocBuilder::reserve(), clang::Result, and clang::TypeLocBuilder::TypeWasModifiedSafely().
TryExpandParameterPacks()
template<typename Derived > bool clang::TreeTransform< Derived >::TryExpandParameterPacks (SourceLocation EllipsisLoc, SourceRange PatternRange, ArrayRef< UnexpandedParameterPack > Unexpanded, bool & ShouldExpand, bool & RetainExpansion, std::optional< unsigned > & NumExpansions) inline
Determine whether we should expand a pack expansion with the given set of parameter packs into separate arguments by repeatedly transforming the pattern.
By default, the transformer never tries to expand pack expansions. Subclasses can override this routine to provide different behavior.
Parameters
EllipsisLoc The location of the ellipsis that identifies the pack expansion.
PatternRange The source range that covers the entire pattern of the pack expansion.
Unexpanded The set of unexpanded parameter packs within the pattern.
ShouldExpand Will be set to true if the transformer should expand the corresponding pack expansions into separate arguments. When set, NumExpansions must also be set.
RetainExpansion Whether the caller should add an unexpanded pack expansion after all of the expanded arguments. This is used when extending explicitly-specified template argument packs per C++0x [temp.arg.explicit]p9.
NumExpansions The number of separate arguments that will be in the expanded form of the corresponding pack expansion. This is both an input and an output parameter, which can be set by the caller if the number of expansions is known a priori (e.g., due to a prior substitution) and will be set by the callee when the number of expansions is known. The callee must set this value when ShouldExpand is true; it may set this value in other cases.
Returns
true if an error occurred (e.g., because the parameter packs are to be instantiated with arguments of different lengths), false otherwise. If false, ShouldExpand (and possibly NumExpansions) must be set.
Definition at line 281 of file TreeTransform.h.
Member Data Documentation
SemaRef
template<typename Derived > Sema& clang::TreeTransform< Derived >::SemaRef protected
Definition at line 122 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::AlwaysRebuild(), clang::TreeTransform< Derived >::getSema(), clang::TreeTransform< Derived >::InventTypeSourceInfo(), clang::TreeTransform< Derived >::RebuildAttributedStmt(), clang::TreeTransform< Derived >::RebuildAutoType(), clang::TreeTransform< Derived >::RebuildChooseExpr(), clang::TreeTransform< Derived >::RebuildConvertVectorExpr(), clang::TreeTransform< Derived >::RebuildCXXDependentScopeMemberExpr(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildCXXNoexceptExpr(), clang::TreeTransform< Derived >::RebuildDeducedTemplateSpecializationType(), clang::TreeTransform< Derived >::RebuildDependentNameType(), clang::TreeTransform< Derived >::RebuildDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::RebuildDesignatedInitExpr(), clang::TreeTransform< Derived >::RebuildElaboratedType(), clang::TreeTransform< Derived >::RebuildEnumType(), clang::TreeTransform< Derived >::RebuildExprRequirement(), clang::TreeTransform< Derived >::RebuildExprRequirement(), clang::TreeTransform< Derived >::RebuildImplicitValueInitExpr(), clang::TreeTransform< Derived >::RebuildInitList(), clang::TreeTransform< Derived >::RebuildLabelStmt(), clang::TreeTransform< Derived >::RebuildMacroQualifiedType(), clang::TreeTransform< Derived >::RebuildNestedRequirement(), clang::TreeTransform< Derived >::RebuildNestedRequirement(), clang::TreeTransform< Derived >::RebuildObjCEncodeExpr(), clang::TreeTransform< Derived >::RebuildObjCMessageExpr(), clang::TreeTransform< Derived >::RebuildObjCMessageExpr(), clang::TreeTransform< Derived >::RebuildObjCMessageExpr(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::TreeTransform< Derived >::RebuildParenType(), clang::TreeTransform< Derived >::RebuildRecordType(), clang::TreeTransform< Derived >::RebuildRequiresExpr(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), clang::TreeTransform< Derived >::RebuildSizeOfPackExpr(), clang::TreeTransform< Derived >::RebuildTypedefType(), clang::TreeTransform< Derived >::RebuildTypeRequirement(), clang::TreeTransform< Derived >::RebuildTypeRequirement(), clang::TreeTransform< Derived >::RebuildUnresolvedMemberExpr(), and clang::TreeTransform< Derived >::RebuildUsingType().
TransformedLocalDecls
template<typename Derived > llvm::DenseMap<Decl *, Decl *> clang::TreeTransform< Derived >::TransformedLocalDecls protected
The set of local declarations that have been transformed, for cases where we are forced to build new declarations within the transformer rather than in the subclass (e.g., lambda closure types).
Definition at line 127 of file TreeTransform.h.
Referenced by clang::TreeTransform< Derived >::TransformDecl(), and clang::TreeTransform< Derived >::transformedLocalDecl().
The documentation for this class was generated from the following file:
lib/Sema/TreeTransform.h