clang: clang::TypeSourceInfo Class Reference
clang::TypeSourceInfo Class Reference
A container of type source information.
#include "clang/AST/Type.h"
Public Member Functions
QualType getType () const
Return the type wrapped by this type source info.
TypeLoc getTypeLoc () const
Return the TypeLoc wrapper for the type source info.
void overrideType (QualType T)
Override the type stored in this TypeSourceInfo. Use with caution!
Friends
class ASTContext
Detailed Description
A container of type source information.
A client can read the relevant info using TypeLoc wrappers, e.g:
TypeLoc TL = TypeSourceInfo->getTypeLoc();
TL.getBeginLoc().print(OS, SrcMgr);
Definition at line 6655 of file Type.h.
Member Function Documentation
getType()
QualType clang::TypeSourceInfo::getType () const inline
Return the type wrapped by this type source info.
Definition at line 6666 of file Type.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecompositionDeclarator(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFriendTypeDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIvar(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCExceptionDecl(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnOpenMPDeclareMapperVarDecl(), clang::Sema::ActOnPackExpansion(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnProperty(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnTypedefDeclarator(), clang::Sema::ActOnTypeName(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::AddAlignedAttr(), clang::ASTRecordWriter::AddTypeSourceInfo(), adjustFunctionTypeForInstantiation(), applyObjCTypeArgs(), clang::Sema::BuildArrayTypeTrait(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildPseudoDestructorExpr(), buildTypeForLambdaCallOperator(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorLiteral(), clang::Sema::CheckAlignasTypeArgument(), checkAllAtProps(), clang::Sema::CheckBaseSpecifier(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckEnumUnderlyingType(), CheckForModifiableLvalue(), clang::Sema::CheckFriendTypeDecl(), clang::Sema::CheckNonTypeTemplateParameterType(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTypedefForVariablyModifiedType(), clang::Sema::CheckVariableDeclarationType(), clang::Sema::CompleteVarTemplateSpecializationDecl(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::NonTypeTemplateParmDecl::Create(), clang::UsingEnumDecl::Create(), clang::Sema::CreateGenericSelectionExpr(), createMakeIntegerSeqParameterList(), createTypePackElementParameterList(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::deduceVarTypeFromInitializer(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseUnusedExprResult(), EmitDiagForCXXThrowInNonThrowingFunc(), clang::Sema::findInheritingConstructor(), clang::UnaryExprOrTypeTraitExpr::getArgumentType(), clang::TemplateTypeParmDecl::getDefaultArgument(), clang::ObjCEncodeExpr::getEncodedType(), clang::UsingEnumDecl::getEnumDecl(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar(), getLambdaType(), clang::ParmVarDecl::getOriginalType(), clang::ArrayTypeTraitExpr::getQueriedType(), clang::CXXBaseSpecifier::getType(), clang::CXXUnresolvedConstructExpr::getTypeAsWritten(), clang::ExplicitCastExpr::getTypeAsWritten(), clang::CXXTypeidExpr::getTypeOperand(), clang::CXXUuidofExpr::getTypeOperand(), handleAlignedAttr(), clang::Sema::HandleDeclarator(), clang::Sema::HandleField(), clang::Sema::HandleMSProperty(), hasDeducedReturnType(), clang::ASTImporter::Import(), clang::InitializedEntity::InitializeCompoundLiteralInit(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::InstantiateMemInitializers(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), IsStructurallyEquivalent(), print_initializer(), printArgument(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), RebuildDeclaratorInCurrentInstantiation(), clang::TreeTransform< Derived >::RebuildObjCMessageExpr(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::Sema::SemaConvertVectorExpr(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TreeTransform< Derived >::TransformTemplateArgument(), clang::TreeTransform< Derived >::TransformType(), clang::TreeTransform< Derived >::TransformType(), clang::TreeTransform< Derived >::TransformTypeWithDeducedTST(), clang::TreeTransform< Derived >::TransformTypeWithDeducedTST(), TryToFixInvalidVariablyModifiedTypeSourceInfo(), clang::Sema::tryToFixVariablyModifiedVarType(), clang::TextNodeDumper::Visit(), clang::JSONNodeDumper::VisitCXXTypeidExpr(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTNodeImporter::VisitFriendDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFriendDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGenericSelectionExpr(), and clang::JSONNodeDumper::VisitSYCLUniqueStableNameExpr().
getTypeLoc()
TypeLoc clang::TypeSourceInfo::getTypeLoc () const inline
Return the TypeLoc wrapper for the type source info.
Return the TypeLoc for a type source info.
Definition at line 249 of file TypeLoc.h.
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnCXXTypeConstructExpr(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCProtocolQualifierType(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::ActOnTag(), clang::Sema::ActOnTemplatedFriendTag(), clang::Sema::ActOnTemplateTypeArgument(), clang::Sema::AddAlignedAttr(), addFunctionPointerConversion(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::TemplateDeclInstantiator::adjustForRewrite(), AnalyzeBitFieldAssignment(), applyObjCTypeArgs(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildClassMessage(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildVAArgExpr(), CheckAbstractClassUsage(), CheckAbstractClassUsage(), CheckAbstractClassUsage(), checkAllAtProps(), clang::Sema::CheckBaseSpecifier(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckEnumUnderlyingType(), clang::Sema::CheckFriendTypeDecl(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckParameter(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkThisInStaticMemberFunctionExceptionSpec(), clang::Sema::checkThisInStaticMemberFunctionType(), checkTypeParamListConsistency(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::createLambdaInitCaptureVarDecl(), clang::Sema::CreatePropertyDecl(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::deduceVarTypeFromInitializer(), DiagnoseCalleeStaticArrayParam(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseUnusedExprResult(), clang::comments::DeclInfo::fill(), clang::Sema::findInheritingConstructor(), findTypeLocationForBlockDecl(), clang::CXXBaseSpecifier::getBaseTypeLoc(), clang::CXXFunctionalCastExpr::getBeginLoc(), clang::CXXTemporaryObjectExpr::getBeginLoc(), clang::TemplateTypeParmDecl::getDefaultArgumentLoc(), clang::UsingEnumDecl::getEnumTypeLoc(), GetFullTypeForDeclarator(), clang::comments::getFunctionTypeLoc(), clang::FunctionDecl::getFunctionTypeLoc(), getPointeeTypeText(), clang::UsingEnumDecl::getQualifierLoc(), clang::ObjCMessageExpr::getReceiverRange(), clang::Sema::getReturnTypeLoc(), clang::ClassTemplateSpecializationDecl::getSourceRange(), clang::UsingEnumDecl::getSourceRange(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::ASTContext::getTemplateSpecializationTypeInfo(), clang::ASTContext::getTrivialTypeSourceInfo(), getTypeRange(), clang::TypeLocBuilder::getTypeSourceInfo(), GetTypeSourceInfoForDeclarator(), clang::DeclaratorDecl::getTypeSpecEndLoc(), clang::DeclaratorDecl::getTypeSpecStartLoc(), handleAlignedAttr(), implicitObjectParamIsLifetimeBound(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::index::IndexingContext::indexTypeSourceInfo(), InventTemplateParameter(), clang::Expr::isFlexibleArrayMemberLike(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), clang::PseudoDestructorTypeStorage::PseudoDestructorTypeStorage(), clang::ASTRecordReader::readTypeSourceInfo(), clang::Sema::SubstExceptionSpec(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TreeTransform< Derived >::TransformType(), clang::TreeTransform< Derived >::TransformTypeWithDeducedTST(), clang::RecursiveASTVisitor< Derived >::TraverseConceptTypeRequirement(), and TryToFixInvalidVariablyModifiedTypeSourceInfo().
overrideType()
void clang::TypeSourceInfo::overrideType (QualType T) inline
Override the type stored in this TypeSourceInfo. Use with caution!
Definition at line 6672 of file Type.h.
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 6658 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
include/clang/AST/TypeLoc.h