clang: clang::InitListExpr Class Reference
clang::InitListExpr Class Reference
Describes an C or C++ initializer list.
#include "clang/AST/Expr.h"
Public Types
typedef InitExprsTy::iterator iterator
typedef InitExprsTy::const_iterator const_iterator
typedef InitExprsTy::reverse_iterator reverse_iterator
typedef InitExprsTy::const_reverse_iterator const_reverse_iterator
Public Types inherited from clang::Expr
enum LValueClassification {
LV_Valid , LV_NotObjectType , LV_IncompleteVoidType , LV_DuplicateVectorComponents ,
LV_InvalidExpression , LV_InvalidMessageExpression , LV_MemberFunction , LV_SubObjCPropertySetting ,
LV_ClassTemporary , LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid , MLV_NotObjectType , MLV_IncompleteVoidType , MLV_DuplicateVectorComponents ,
MLV_InvalidExpression , MLV_LValueCast , MLV_IncompleteType , MLV_ConstQualified ,
MLV_ConstQualifiedField , MLV_ConstAddrSpace , MLV_ArrayType , MLV_NoSetterProperty ,
MLV_MemberFunction , MLV_SubObjCPropertySetting , MLV_InvalidMessageExpression , MLV_ClassTemporary ,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects , SE_AllowUndefinedBehavior , SE_AllowSideEffects }
enum class ConstantExprKind { Normal , NonClassTemplateArgument , ClassTemplateArgument , ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0 , NPCK_ZeroExpression , NPCK_ZeroLiteral , NPCK_CXX11_nullptr ,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0 , NPC_ValueDependentIsNull , NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
InitListExpr (const ASTContext &C, SourceLocation lbraceloc, ArrayRef< Expr * > initExprs, SourceLocation rbraceloc)
InitListExpr (EmptyShell Empty)
Build an empty initializer list.
unsigned getNumInits () const
Expr ** getInits ()
Retrieve the set of initializers.
Expr *const * getInits () const
Retrieve the set of initializers.
ArrayRef< Expr * > inits ()
ArrayRef< Expr * > inits () const
const Expr * getInit (unsigned Init) const
Expr * getInit (unsigned Init)
void setInit (unsigned Init, Expr *expr)
void markError ()
Mark the semantic form of the InitListExpr as error when the semantic analysis fails.
void reserveInits (const ASTContext &C, unsigned NumInits)
Reserve space for some number of initializers.
void resizeInits (const ASTContext &Context, unsigned NumInits)
Specify the number of initializers.
Expr * updateInit (const ASTContext &C, unsigned Init, Expr *expr)
Updates the initializer at index Init with the new expression expr, and returns the old expression at that location.
Expr * getArrayFiller ()
If this initializer list initializes an array with more elements than there are initializers in the list, specifies an expression to be used for value initialization of the rest of the elements.
const Expr * getArrayFiller () const
void setArrayFiller (Expr *filler)
bool hasArrayFiller () const
Return true if this is an array initializer and its array "filler" has been set.
bool hasDesignatedInit () const
Determine whether this initializer list contains a designated initializer.
FieldDecl * getInitializedFieldInUnion ()
If this initializes a union, specifies which field in the union to initialize.
const FieldDecl * getInitializedFieldInUnion () const
void setInitializedFieldInUnion (FieldDecl *FD)
bool isExplicit () const
bool isStringLiteralInit () const
Is this an initializer for an array of characters, initialized by a string literal or an @encode?
bool isTransparent () const
Is this a transparent initializer list (that is, an InitListExpr that is purely syntactic, and whose semantics are that of the sole contained initializer)?
bool isIdiomaticZeroInitializer (const LangOptions &LangOpts) const
Is this the zero initializer {0} in a language which considers it idiomatic?
SourceLocation getLBraceLoc () const
void setLBraceLoc (SourceLocation Loc)
SourceLocation getRBraceLoc () const
void setRBraceLoc (SourceLocation Loc)
bool isSemanticForm () const
InitListExpr * getSemanticForm () const
bool isSyntacticForm () const
InitListExpr * getSyntacticForm () const
void setSyntacticForm (InitListExpr *Init)
bool hadArrayRangeDesignator () const
void sawArrayRangeDesignator (bool ARD=true)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
Public Member Functions inherited from clang::Expr
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
bool isFlexibleArrayMemberLike (ASTContext &Context, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution=false) const
Check whether this array fits the idiom of a flexible array member, depending on the value of -fstrict-flex-array.
std::optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr, bool isEvaluated=true) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFixedPoint - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
bool EvaluateCharRangeAsString (std::string &Result, const Expr *SizeExpression, const Expr *PtrExpression, ASTContext &Ctx, EvalResult &Status) const
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisible AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parentheses and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Expr
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluted - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
class ASTStmtWriter
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Expr
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
Describes an C or C++ initializer list.
InitListExpr describes an initializer list, which can be used to initialize objects of different types, including struct/class/union types, arrays, and vectors. For example:
struct foo x = { 1, { 2, 3 } };
Prior to semantic analysis, an initializer list will represent the initializer list as written by the user, but will have the placeholder type "void". This initializer list is called the syntactic form of the initializer, and may contain C99 designated initializers (represented as DesignatedInitExprs), initializations of subobject members without explicit braces, and so on. Clients interested in the original syntax of the initializer list should use the syntactic form of the initializer list.
After semantic analysis, the initializer list will represent the semantic form of the initializer, where the initializations of all subobjects are made explicit with nested InitListExpr nodes and C99 designators have been eliminated by placing the designated initializations into the subobject they initialize. Additionally, any "holes" in the initialization, where no initializer has been specified for a particular subobject, will be replaced with implicitly-generated ImplicitValueInitExpr expressions that value-initialize the subobjects. Note, however, that the initializer lists may still have fewer initializers than there are elements to initialize within the object.
After semantic analysis has completed, given an initializer list, method isSemanticForm() returns true if and only if this is the semantic form of the initializer list (note: the same AST node may at the same time be the syntactic form). Given the semantic form of the initializer list, one can retrieve the syntactic form of that initializer list (when different) using method getSyntacticForm(); the method returns null if applied to a initializer list which is already in syntactic form. Similarly, given the syntactic form (i.e., an initializer list such that isSemanticForm() returns false), one can retrieve the semantic form using method getSemanticForm(). Since many initializer lists have the same syntactic and semantic forms, getSyntacticForm() may return NULL, indicating that the current semantic initializer list also serves as its syntactic form.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 4829 of file Expr.h.
Member Typedef Documentation
const_iterator
InitExprsTy::const_iterator clang::InitListExpr::const_iterator
Definition at line 5035 of file Expr.h.
const_reverse_iterator
InitExprsTy::const_reverse_iterator clang::InitListExpr::const_reverse_iterator
Definition at line 5037 of file Expr.h.
iterator
InitExprsTy::iterator clang::InitListExpr::iterator
Definition at line 5034 of file Expr.h.
reverse_iterator
InitExprsTy::reverse_iterator clang::InitListExpr::reverse_iterator
Definition at line 5036 of file Expr.h.
Constructor & Destructor Documentation
InitListExpr() [1/2]
InitListExpr::InitListExpr (const ASTContext & C, SourceLocation lbraceloc, ArrayRef< Expr * > initExprs, SourceLocation rbraceloc)
Definition at line 2389 of file Expr.cpp.
References clang::C, clang::computeDependence(), clang::ASTVector< T >::end(), clang::ASTVector< T >::insert(), sawArrayRangeDesignator(), and clang::Expr::setDependence().
InitListExpr() [2/2]
clang::InitListExpr::InitListExpr (EmptyShell Empty) inline explicit
Build an empty initializer list.
Definition at line 4856 of file Expr.h.
Member Function Documentation
begin() [1/2]
iterator clang::InitListExpr::begin () inline
Definition at line 5039 of file Expr.h.
References clang::ASTVector< T >::begin().
Referenced by hasDesignatedInit().
begin() [2/2]
const_iterator clang::InitListExpr::begin () const inline
Definition at line 5040 of file Expr.h.
References clang::ASTVector< T >::begin().
children() [1/2]
child_range clang::InitListExpr::children () inline
Definition at line 5021 of file Expr.h.
References clang::cast_away_const(), and children().
Referenced by children().
children() [2/2]
const_child_range clang::InitListExpr::children () const inline
Definition at line 5027 of file Expr.h.
References clang::ASTVector< T >::empty(), and clang::ASTVector< T >::size().
classof()
static bool clang::InitListExpr::classof (const Stmt * T) inline static
Definition at line 5016 of file Expr.h.
end() [1/2]
iterator clang::InitListExpr::end () inline
Definition at line 5041 of file Expr.h.
References clang::ASTVector< T >::end().
Referenced by hasDesignatedInit().
end() [2/2]
const_iterator clang::InitListExpr::end () const inline
Definition at line 5042 of file Expr.h.
References clang::ASTVector< T >::end().
getArrayFiller() [1/2]
Expr * clang::InitListExpr::getArrayFiller () inline
If this initializer list initializes an array with more elements than there are initializers in the list, specifies an expression to be used for value initialization of the rest of the elements.
Definition at line 4923 of file Expr.h.
Referenced by getArrayFiller(), hasArrayFiller(), clang::ASTNodeImporter::VisitInitListExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitInitListExpr(), and clang::UsedDeclVisitor< Derived >::VisitInitListExpr().
getArrayFiller() [2/2]
const Expr * clang::InitListExpr::getArrayFiller () const inline
Definition at line 4926 of file Expr.h.
References getArrayFiller().
getBeginLoc()
SourceLocation InitListExpr::getBeginLoc () const
Definition at line 2479 of file Expr.cpp.
References clang::ASTVector< T >::begin(), clang::ASTVector< T >::end(), getSyntacticForm(), and clang::SourceLocation::isInvalid().
Referenced by diagnoseListInit(), TryListConversion(), and TryListInitialization().
getEndLoc()
SourceLocation InitListExpr::getEndLoc () const
Definition at line 2497 of file Expr.cpp.
References getSyntacticForm().
Referenced by TryListConversion().
getInit() [1/2]
Expr * clang::InitListExpr::getInit (unsigned Init) inline
Definition at line 4880 of file Expr.h.
References getNumInits().
getInit() [2/2]
const Expr * clang::InitListExpr::getInit (unsigned Init) const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 4875 of file Expr.h.
References getNumInits().
Referenced by GetNumNonZeroBytesInInit(), clang::Expr::isConstantInitializer(), isIdiomaticZeroInitializer(), isStringLiteralInit(), isTransparent(), clang::InitializationSequence::RewrapReferenceInitList(), tryExtractInitializerFromList(), TryListConversion(), TryListInitialization(), TryReferenceListInitialization(), clang::ento::ExprEngine::VisitInitListExpr(), visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
getInitializedFieldInUnion() [1/2]
FieldDecl * clang::InitListExpr::getInitializedFieldInUnion () inline
If this initializes a union, specifies which field in the union to initialize.
Typically, this field is the first named field within the union. However, a designated initializer can specify the initialization of a different field within the union.
Definition at line 4948 of file Expr.h.
Referenced by getInitializedFieldInUnion(), clang::Expr::isConstantInitializer(), setInitializedFieldInUnion(), clang::ASTNodeImporter::VisitInitListExpr(), clang::JSONNodeDumper::VisitInitListExpr(), clang::TextNodeDumper::VisitInitListExpr(), and visitLocalsRetainedByInitializer().
getInitializedFieldInUnion() [2/2]
const FieldDecl * clang::InitListExpr::getInitializedFieldInUnion () const inline
Definition at line 4951 of file Expr.h.
References getInitializedFieldInUnion().
getInits() [1/2]
Expr ** clang::InitListExpr::getInits () inline
Retrieve the set of initializers.
Definition at line 4862 of file Expr.h.
References clang::ASTVector< T >::data().
Referenced by clang::InitializationSequence::Diagnose(), inits(), inits(), clang::InitializationSequence::Perform(), setArrayFiller(), and TryConstructorInitialization().
getInits() [2/2]
Expr *const * clang::InitListExpr::getInits () const inline
Retrieve the set of initializers.
Definition at line 4865 of file Expr.h.
References clang::ASTVector< T >::data().
getLBraceLoc()
SourceLocation clang::InitListExpr::getLBraceLoc () const inline
Definition at line 4983 of file Expr.h.
Referenced by clang::InitializationSequence::Perform(), TryListInitialization(), and clang::ASTNodeImporter::VisitInitListExpr().
getNumInits()
unsigned clang::InitListExpr::getNumInits () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 4859 of file Expr.h.
References clang::ASTVector< T >::size().
Referenced by DeduceFromInitializerList(), clang::InitializationSequence::Diagnose(), diagnoseListInit(), getInit(), getInit(), GetNumNonZeroBytesInInit(), inits(), inits(), clang::Expr::isConstantInitializer(), isIdiomaticZeroInitializer(), isStringLiteralInit(), isTransparent(), MaybeElementDependentArrayFiller(), clang::InitializationSequence::Perform(), clang::InitializationSequence::RewrapReferenceInitList(), setArrayFiller(), setInit(), TryConstructorInitialization(), tryExtractInitializerFromList(), TryListConversion(), TryListInitialization(), TryReferenceListInitialization(), TryValueInitialization(), clang::ASTNodeImporter::VisitInitListExpr(), clang::ento::ExprEngine::VisitInitListExpr(), and visitLocalsRetainedByInitializer().
getRBraceLoc()
SourceLocation clang::InitListExpr::getRBraceLoc () const inline
Definition at line 4985 of file Expr.h.
Referenced by clang::InitializationSequence::Perform(), TryListInitialization(), and clang::ASTNodeImporter::VisitInitListExpr().
getSemanticForm()
InitListExpr * clang::InitListExpr::getSemanticForm () const inline
Definition at line 4989 of file Expr.h.
References isSemanticForm().
getSyntacticForm()
InitListExpr * clang::InitListExpr::getSyntacticForm () const inline
Definition at line 4995 of file Expr.h.
References isSemanticForm().
Referenced by getBeginLoc(), getEndLoc(), and clang::ASTNodeImporter::VisitInitListExpr().
hadArrayRangeDesignator()
bool clang::InitListExpr::hadArrayRangeDesignator () const inline
Definition at line 5006 of file Expr.h.
References clang::Stmt::InitListExprBits.
Referenced by clang::ASTNodeImporter::VisitInitListExpr().
hasArrayFiller()
bool clang::InitListExpr::hasArrayFiller () const inline
Return true if this is an array initializer and its array "filler" has been set.
Definition at line 4933 of file Expr.h.
References getArrayFiller().
Referenced by setArrayFiller(), clang::ASTNodeImporter::VisitInitListExpr(), and clang::UsedDeclVisitor< Derived >::VisitInitListExpr().
hasDesignatedInit()
bool clang::InitListExpr::hasDesignatedInit () const inline
Determine whether this initializer list contains a designated initializer.
Definition at line 4936 of file Expr.h.
References begin(), end(), and clang::isa().
Referenced by TryListConversion(), and TryListInitialization().
inits() [1/2]
ArrayRef< Expr * > clang::InitListExpr::inits () inline
Definition at line 4869 of file Expr.h.
References getInits(), and getNumInits().
Referenced by clang::computeDependence(), DeduceFromInitializerList(), setArrayFiller(), clang::ASTNodeImporter::VisitInitListExpr(), and clang::interp::ByteCodeExprGen< Emitter >::VisitInitListExpr().
inits() [2/2]
ArrayRef< Expr * > clang::InitListExpr::inits () const inline
Definition at line 4871 of file Expr.h.
References getInits(), and getNumInits().
isExplicit()
bool clang::InitListExpr::isExplicit () const inline
Definition at line 4966 of file Expr.h.
References clang::SourceLocation::isValid().
isIdiomaticZeroInitializer()
bool InitListExpr::isIdiomaticZeroInitializer (const LangOptions & LangOpts) const
Is this the zero initializer {0} in a language which considers it idiomatic?
Definition at line 2468 of file Expr.cpp.
References getInit(), getNumInits(), clang::APIntStorage::getValue(), clang::Expr::IgnoreImplicit(), and isSyntacticForm().
isSemanticForm()
bool clang::InitListExpr::isSemanticForm () const inline
Definition at line 4988 of file Expr.h.
Referenced by getSemanticForm(), getSyntacticForm(), clang::Expr::isConstantInitializer(), isTransparent(), and markError().
isStringLiteralInit()
bool InitListExpr::isStringLiteralInit () const
Is this an initializer for an array of characters, initialized by a string literal or an @encode?
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2431 of file Expr.cpp.
References clang::Type::getAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), getInit(), getNumInits(), clang::Expr::getType(), clang::isa(), and clang::Type::isIntegerType().
isSyntacticForm()
bool clang::InitListExpr::isSyntacticForm () const inline
Definition at line 4992 of file Expr.h.
Referenced by isIdiomaticZeroInitializer().
isTransparent()
bool InitListExpr::isTransparent () const
Is this a transparent initializer list (that is, an InitListExpr that is purely syntactic, and whose semantics are that of the sole contained initializer)?
Definition at line 2445 of file Expr.cpp.
References clang::QualType::getCanonicalType(), getInit(), getNumInits(), clang::Expr::getType(), clang::Expr::isGLValue(), clang::Expr::isPRValue(), isRecordType(), and isSemanticForm().
Referenced by GetNumNonZeroBytesInInit(), clang::ento::ExprEngine::VisitInitListExpr(), visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
markError()
void clang::InitListExpr::markError () inline
Mark the semantic form of the InitListExpr as error when the semantic analysis fails.
Definition at line 4895 of file Expr.h.
References clang::Expr::getDependence(), isSemanticForm(), and clang::Expr::setDependence().
rbegin() [1/2]
reverse_iterator clang::InitListExpr::rbegin () inline
Definition at line 5043 of file Expr.h.
References clang::ASTVector< T >::rbegin().
rbegin() [2/2]
const_reverse_iterator clang::InitListExpr::rbegin () const inline
Definition at line 5044 of file Expr.h.
References clang::ASTVector< T >::rbegin().
rend() [1/2]
reverse_iterator clang::InitListExpr::rend () inline
Definition at line 5045 of file Expr.h.
References clang::ASTVector< T >::rend().
rend() [2/2]
const_reverse_iterator clang::InitListExpr::rend () const inline
Definition at line 5046 of file Expr.h.
References clang::ASTVector< T >::rend().
reserveInits()
void InitListExpr::reserveInits (const ASTContext & C, unsigned NumInits)
Reserve space for some number of initializers.
Definition at line 2400 of file Expr.cpp.
References clang::C, clang::ASTVector< T >::reserve(), and clang::ASTVector< T >::size().
resizeInits()
void InitListExpr::resizeInits (const ASTContext & Context, unsigned NumInits)
Specify the number of initializers.
If there are more than NumInits initializers, the remaining initializers will be destroyed. If there are fewer than NumInits initializers, NULL expressions will be added for the unknown initializers.
Definition at line 2405 of file Expr.cpp.
References clang::C, and clang::ASTVector< T >::resize().
sawArrayRangeDesignator()
void clang::InitListExpr::sawArrayRangeDesignator (bool ARD = true) inline
Definition at line 5009 of file Expr.h.
References clang::Stmt::InitListExprBits.
Referenced by InitListExpr(), and clang::ASTNodeImporter::VisitInitListExpr().
setArrayFiller()
void InitListExpr::setArrayFiller (Expr * filler)
Definition at line 2421 of file Expr.cpp.
References getInits(), getNumInits(), hasArrayFiller(), and inits().
Referenced by clang::ASTNodeImporter::VisitInitListExpr().
setInit()
void clang::InitListExpr::setInit (unsigned Init, Expr * expr) inline
Definition at line 4885 of file Expr.h.
References clang::ast_matchers::expr, clang::Expr::getDependence(), getNumInits(), and clang::Expr::setDependence().
Referenced by updateInit().
setInitializedFieldInUnion()
void clang::InitListExpr::setInitializedFieldInUnion (FieldDecl * FD) inline
Definition at line 4954 of file Expr.h.
References getInitializedFieldInUnion().
Referenced by clang::ASTNodeImporter::VisitInitListExpr().
setLBraceLoc()
void clang::InitListExpr::setLBraceLoc (SourceLocation Loc) inline
Definition at line 4984 of file Expr.h.
setRBraceLoc()
void clang::InitListExpr::setRBraceLoc (SourceLocation Loc) inline
Definition at line 4986 of file Expr.h.
setSyntacticForm()
void clang::InitListExpr::setSyntacticForm (InitListExpr * Init) inline
Definition at line 4999 of file Expr.h.
Referenced by clang::InitializationSequence::Perform(), and clang::ASTNodeImporter::VisitInitListExpr().
updateInit()
Expr * InitListExpr::updateInit (const ASTContext & C, unsigned Init, Expr * expr)
Updates the initializer at index Init with the new expression expr, and returns the old expression at that location.
When Init is out of range for this initializer list, the initializer list will be extended with NULL expressions to accommodate the new entry.
Definition at line 2409 of file Expr.cpp.
References clang::C, clang::ASTVector< T >::end(), clang::ast_matchers::expr, clang::ASTVector< T >::insert(), clang::Result, setInit(), and clang::ASTVector< T >::size().
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 5048 of file Expr.h.
ASTStmtWriter
friend class ASTStmtWriter friend
Definition at line 5049 of file Expr.h.
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp