clang: clang::ModuleMap Class Reference
clang::ModuleMap Class Reference
#include "clang/Lex/ModuleMap.h"
Classes
class KnownHeader
A header that is known to reside within a given module, whether it was included or excluded.
Public Types
enum ModuleHeaderRole { NormalHeader = 0x0 , PrivateHeader = 0x1 , TextualHeader = 0x2 , ExcludedHeader = 0x4 }
Flags describing the role of a module header.
using AdditionalModMapsSet = llvm::SmallPtrSet<const FileEntry *, 1>
using module_iterator = llvm::StringMap<Module *>::const_iterator
Public Member Functions
void resolveLinkAsDependencies (Module *Mod)
Use PendingLinkAsModule information to mark top level link names that are going to be replaced by export_as aliases.
void addLinkAsDependency (Module *Mod)
Make module to use export_as as the link dependency name if enough information is available or add it to a pending list otherwise.
ModuleMap (SourceManager &SourceMgr, DiagnosticsEngine &Diags, const LangOptions &LangOpts, const TargetInfo *Target, HeaderSearch &HeaderInfo)
Construct a new module map.
~ModuleMap ()
Destroy the module map.
void setTarget (const TargetInfo &Target)
Set the target information.
void setBuiltinIncludeDir (DirectoryEntryRef Dir)
Set the directory that contains Clang-supplied include files, such as our stdarg.h or tgmath.h.
const DirectoryEntry * getBuiltinDir () const
Get the directory that contains Clang-supplied include files.
bool isBuiltinHeader (const FileEntry *File)
void addModuleMapCallbacks (std::unique_ptr< ModuleMapCallbacks > Callback)
Add a module map callback.
KnownHeader findModuleForHeader (FileEntryRef File, bool AllowTextual=false, bool AllowExcluded=false)
Retrieve the module that owns the given header file, if any.
ArrayRef< KnownHeader > findAllModulesForHeader (FileEntryRef File)
Retrieve all the modules that contain the given header file.
ArrayRef< KnownHeader > findResolvedModulesForHeader (const FileEntry *File) const
Like findAllModulesForHeader, but do not attempt to infer module ownership from umbrella headers if we've not already done so.
void resolveHeaderDirectives (const FileEntry *File) const
Resolve all lazy header directives for the specified file.
void resolveHeaderDirectives (Module *Mod, std::optional< const FileEntry * > File) const
Resolve lazy header directives for the specified module.
void diagnoseHeaderInclusion (Module *RequestingModule, bool RequestingModuleIsModuleInterface, SourceLocation FilenameLoc, StringRef Filename, FileEntryRef File)
Reports errors if a module must not include a specific file.
bool isHeaderInUnavailableModule (FileEntryRef Header) const
Determine whether the given header is part of a module marked 'unavailable'.
bool isHeaderUnavailableInModule (FileEntryRef Header, const Module *RequestingModule) const
Determine whether the given header is unavailable as part of the specified module.
Module * findModule (StringRef Name) const
Retrieve a module with the given name.
Module * lookupModuleUnqualified (StringRef Name, Module *Context) const
Retrieve a module with the given name using lexical name lookup, starting at the given context.
Module * lookupModuleQualified (StringRef Name, Module *Context) const
Retrieve a module with the given name within the given context, using direct (qualified) name lookup.
std::pair< Module *, bool > findOrCreateModule (StringRef Name, Module *Parent, bool IsFramework, bool IsExplicit)
Find a new module or submodule, or create it if it does not already exist.
Module * createGlobalModuleFragmentForModuleUnit (SourceLocation Loc, Module *Parent=nullptr)
Create a global module fragment for a C++ module unit.
Module * createImplicitGlobalModuleFragmentForModuleUnit (SourceLocation Loc, bool IsExported, Module *Parent=nullptr)
Module * createPrivateModuleFragmentForInterfaceUnit (Module *Parent, SourceLocation Loc)
Create a global module fragment for a C++ module interface unit.
Module * createModuleUnitWithKind (SourceLocation Loc, StringRef Name, Module::ModuleKind Kind)
Create a new C++ module with the specified kind, and reparent any pending global module fragment(s) to it.
Module * createModuleForInterfaceUnit (SourceLocation Loc, StringRef Name)
Create a new module for a C++ module interface unit.
Module * createModuleForImplementationUnit (SourceLocation Loc, StringRef Name)
Create a new module for a C++ module implementation unit.
Module * createHeaderUnit (SourceLocation Loc, StringRef Name, Module::Header H)
Create a C++20 header unit.
Module * inferFrameworkModule (DirectoryEntryRef FrameworkDir, bool IsSystem, Module *Parent)
Infer the contents of a framework module map from the given framework directory.
Module * createShadowedModule (StringRef Name, bool IsFramework, Module *ShadowingModule)
Create a new top-level module that is shadowed by ShadowingModule.
void finishModuleDeclarationScope ()
Creates a new declaration scope for module names, allowing previously defined modules to shadow definitions from the new scope.
bool mayShadowNewModule (Module *ExistingModule)
bool canInferFrameworkModule (const DirectoryEntry *Dir) const
Check whether a framework module can be inferred in the given directory.
OptionalFileEntryRef getContainingModuleMapFile (const Module *Module) const
Retrieve the module map file containing the definition of the given module.
OptionalFileEntryRef getModuleMapFileForUniquing (const Module *M) const
Get the module map file that (along with the module name) uniquely identifies this module.
void setInferredModuleAllowedBy (Module *M, const FileEntry *ModMap)
std::error_code canonicalizeModuleMapPath (SmallVectorImpl< char > &Path)
Canonicalize Path in a manner suitable for a module map file.
AdditionalModMapsSet * getAdditionalModuleMapFiles (const Module *M)
Get any module map files other than getModuleMapFileForUniquing(M) that define submodules of a top-level module M.
void addAdditionalModuleMapFile (const Module *M, const FileEntry *ModuleMap)
bool resolveExports (Module *Mod, bool Complain)
Resolve all of the unresolved exports in the given module.
bool resolveUses (Module *Mod, bool Complain)
Resolve all of the unresolved uses in the given module.
bool resolveConflicts (Module *Mod, bool Complain)
Resolve all of the unresolved conflicts in the given module.
void setUmbrellaHeaderAsWritten (Module *Mod, FileEntryRef UmbrellaHeader, const Twine &NameAsWritten, const Twine &PathRelativeToRootModuleDirectory)
Sets the umbrella header of the given module to the given header.
void setUmbrellaDirAsWritten (Module *Mod, DirectoryEntryRef UmbrellaDir, const Twine &NameAsWritten, const Twine &PathRelativeToRootModuleDirectory)
Sets the umbrella directory of the given module to the given directory.
void addHeader (Module *Mod, Module::Header Header, ModuleHeaderRole Role, bool Imported=false)
Adds this header to the given module.
bool parseModuleMapFile (const FileEntry *File, bool IsSystem, DirectoryEntryRef HomeDir, FileID ID=FileID(), unsigned *Offset=nullptr, SourceLocation ExternModuleLoc=SourceLocation())
Parse the given module map file, and record any modules we encounter.
void dump ()
Dump the contents of the module map, for debugging purposes.
module_iterator module_begin () const
module_iterator module_end () const
llvm::iterator_range< module_iterator > modules () const
void cacheModuleLoad (const IdentifierInfo &II, Module *M)
Cache a module load. M might be nullptr.
std::optional< Module * > getCachedModuleLoad (const IdentifierInfo &II)
Return a cached module load.
Static Public Member Functions
static ModuleHeaderRole headerKindToRole (Module::HeaderKind Kind)
Convert a header kind to a role. Requires Kind to not be HK_Excluded.
static Module::HeaderKind headerRoleToKind (ModuleHeaderRole Role)
Convert a header role to a kind.
static bool isModular (ModuleHeaderRole Role)
Check if the header with the given role is a modular one.
static bool isBuiltinHeader (StringRef FileName)
Is this a compiler builtin header?
Friends
class ModuleMapParser
Detailed Description
Definition at line 74 of file ModuleMap.h.
Member Typedef Documentation
AdditionalModMapsSet
using clang::ModuleMap::AdditionalModMapsSet = llvm::SmallPtrSet<const FileEntry *, 1>
Definition at line 197 of file ModuleMap.h.
module_iterator
using clang::ModuleMap::module_iterator = llvm::StringMap<Module *>::const_iterator
Definition at line 732 of file ModuleMap.h.
Member Enumeration Documentation
ModuleHeaderRole
enum clang::ModuleMap::ModuleHeaderRole
Flags describing the role of a module header.
Enumerator
NormalHeader
This header is normally included in the module.
PrivateHeader
This header is included but private.
TextualHeader
This header is part of the module (for layering purposes) but should be textually included.
ExcludedHeader
This header is explicitly excluded from the module.
Definition at line 127 of file ModuleMap.h.
Constructor & Destructor Documentation
ModuleMap()
ModuleMap::ModuleMap (SourceManager & SourceMgr, DiagnosticsEngine & Diags, const LangOptions & LangOpts, const TargetInfo * Target, HeaderSearch & HeaderInfo)
Construct a new module map.
Parameters
SourceMgr The source manager used to find module files and headers. This source manager should be shared with the header-search mechanism, since they will refer to the same headers.
Diags A diagnostic engine used for diagnostics.
LangOpts Language options for this translation unit.
Target The target for this translation unit.
Definition at line 318 of file ModuleMap.cpp.
~ModuleMap()
ModuleMap::~ModuleMap ()
Destroy the module map.
Definition at line 326 of file ModuleMap.cpp.
Member Function Documentation
addAdditionalModuleMapFile()
void ModuleMap::addAdditionalModuleMapFile (const Module * M, const FileEntry * ModuleMap)
Definition at line 1342 of file ModuleMap.cpp.
addHeader()
void ModuleMap::addHeader (Module * Mod, Module::Header Header, ModuleHeaderRole Role, bool Imported = false)
Adds this header to the given module.
Parameters
Role The role of the header wrt the module.
Definition at line 1257 of file ModuleMap.cpp.
References clang::Module::Header::Entry, clang::FileEntryRef::getName(), clang::Module::getTopLevelModule(), headerRoleToKind(), clang::Module::Headers, clang::LangOptions::isCompilingModule(), clang::HeaderSearch::MarkFileModuleHeader(), and Role.
Referenced by createHeaderUnit(), and clang::serialization::reader::HeaderFileInfoTrait::ReadData().
addLinkAsDependency()
void ModuleMap::addLinkAsDependency (Module * Mod)
Make module to use export_as as the link dependency name if enough information is available or add it to a pending list otherwise.
Definition at line 69 of file ModuleMap.cpp.
References clang::Module::ExportAsModule, findModule(), clang::Module::Name, and clang::Module::UseExportAsModuleLinkName.
addModuleMapCallbacks()
void clang::ModuleMap::addModuleMapCallbacks (std::unique_ptr< ModuleMapCallbacks > Callback) inline
Add a module map callback.
Definition at line 422 of file ModuleMap.h.
Referenced by clang::DependencyCollector::attachToPreprocessor(), and clang::ModuleDependencyCollector::attachToPreprocessor().
cacheModuleLoad()
void clang::ModuleMap::cacheModuleLoad (const IdentifierInfo & II, Module * M) inline
Cache a module load. M might be nullptr.
Definition at line 741 of file ModuleMap.h.
Referenced by clang::CompilerInstance::loadModule().
canInferFrameworkModule()
bool clang::ModuleMap::canInferFrameworkModule (const DirectoryEntry * Dir) const inline
Check whether a framework module can be inferred in the given directory.
Definition at line 609 of file ModuleMap.h.
Referenced by loadModuleMapForModuleBuild().
canonicalizeModuleMapPath()
std::error_code ModuleMap::canonicalizeModuleMapPath (SmallVectorImpl< char > & Path)
Canonicalize Path in a manner suitable for a module map file.
In particular, this canonicalizes the parent directory separately from the filename so that it does not affect header resolution relative to the modulemap.
Returns
an error code if any filesystem operations failed. In this case Path is not modified.
Definition at line 1310 of file ModuleMap.cpp.
References clang::FileManager::getCanonicalName(), clang::FileManager::getDirectoryRef(), and Parent.
createGlobalModuleFragmentForModuleUnit()
Module * ModuleMap::createGlobalModuleFragmentForModuleUnit (SourceLocation Loc, Module * Parent = nullptr)
Create a global module fragment for a C++ module unit.
We model the global module fragment as a submodule of the module interface unit. Unfortunately, we can't create the module interface unit's Module until later, because we don't know what it will be called usually. See C++20 [module.unit]/7.2 for the case we could know its parent.
Definition at line 846 of file ModuleMap.cpp.
References clang::Module::ExplicitGlobalModuleFragment, clang::Module, Parent, and clang::Result.
createHeaderUnit()
Module * ModuleMap::createHeaderUnit (SourceLocation Loc, StringRef Name, Module::Header H)
Create a C++20 header unit.
Definition at line 941 of file ModuleMap.cpp.
References addHeader(), clang::LangOptions::CurrentModule, clang::Module, clang::Module::ModuleHeaderUnit, NormalHeader, and clang::Result.
createImplicitGlobalModuleFragmentForModuleUnit()
Module * ModuleMap::createImplicitGlobalModuleFragmentForModuleUnit (SourceLocation Loc, bool IsExported, Module * Parent = nullptr)
Definition at line 858 of file ModuleMap.cpp.
References clang::Module::ImplicitGlobalModuleFragment, clang::Module, Parent, and clang::Result.
createModuleForImplementationUnit()
Module * ModuleMap::createModuleForImplementationUnit (SourceLocation Loc, StringRef Name)
Create a new module for a C++ module implementation unit.
The interface module for this implementation (implicitly imported) must exist and be loaded and present in the modules map.
Returns
The newly-created module.
Definition at line 917 of file ModuleMap.cpp.
References createModuleUnitWithKind(), clang::LangOptions::CurrentModule, clang::Module::ModuleImplementationUnit, clang::Module::ModuleInterfaceUnit, and clang::Result.
createModuleForInterfaceUnit()
Module * ModuleMap::createModuleForInterfaceUnit (SourceLocation Loc, StringRef Name)
Create a new module for a C++ module interface unit.
The module must not already exist, and will be configured for the current compilation.
Note that this also sets the current module to the newly-created module.
Returns
The newly-created module.
Definition at line 899 of file ModuleMap.cpp.
References createModuleUnitWithKind(), clang::LangOptions::CurrentModule, clang::Module::ModuleInterfaceUnit, PrivateHeader, and clang::Result.
createModuleUnitWithKind()
Module * ModuleMap::createModuleUnitWithKind (SourceLocation Loc, StringRef Name, Module::ModuleKind Kind)
Create a new C++ module with the specified kind, and reparent any pending global module fragment(s) to it.
Definition at line 883 of file ModuleMap.cpp.
References clang::Module, and clang::Result.
Referenced by createModuleForImplementationUnit(), and createModuleForInterfaceUnit().
createPrivateModuleFragmentForInterfaceUnit()
Module * ModuleMap::createPrivateModuleFragmentForInterfaceUnit (Module * Parent, SourceLocation Loc)
Create a global module fragment for a C++ module interface unit.
Definition at line 874 of file ModuleMap.cpp.
References clang::Module, Parent, clang::Module::PrivateModuleFragment, and clang::Result.
createShadowedModule()
Module * ModuleMap::createShadowedModule (StringRef Name, bool IsFramework, Module * ShadowingModule)
Create a new top-level module that is shadowed by ShadowingModule.
Definition at line 1146 of file ModuleMap.cpp.
References clang::Module::markUnavailable(), clang::Module, and clang::Result.
diagnoseHeaderInclusion()
void ModuleMap::diagnoseHeaderInclusion (Module * RequestingModule, bool RequestingModuleIsModuleInterface, SourceLocation FilenameLoc, StringRef Filename, FileEntryRef File)
Reports errors if a module must not include a specific file.
Parameters
RequestingModule The module including a file.
RequestingModuleIsModuleInterface true if the inclusion is in the interface of RequestingModule, false if it's in the implementation of RequestingModule. Value is ignored and meaningless if RequestingModule is nullptr.
FilenameLoc The location of the inclusion's filename.
Filename The included filename as written.
File The included file.
Definition at line 470 of file ModuleMap.cpp.
References clang::Module::directlyUses(), ExcludedHeader, clang::File, Filename, clang::Module::getFullModuleName(), clang::ModuleMap::KnownHeader::getModule(), clang::ModuleMap::KnownHeader::getRole(), clang::Module::getTopLevelModule(), getTopLevelOrNull(), clang::LangOptions::isCompilingModule(), clang::Module::IsFramework, clang::Module::Name, clang::DiagnosticsEngine::Report(), resolveHeaderDirectives(), resolveUses(), and violatesPrivateInclude().
Referenced by clang::Preprocessor::LookupFile().
dump()
LLVM_DUMP_METHOD void ModuleMap::dump ()
Dump the contents of the module map, for debugging purposes.
Definition at line 1347 of file ModuleMap.cpp.
References clang::Module::print().
findAllModulesForHeader()
ArrayRef< ModuleMap::KnownHeader > ModuleMap::findAllModulesForHeader (FileEntryRef File)
Retrieve all the modules that contain the given header file.
Note that this does not implicitly load module maps, except for builtin headers, and does not consult the external source. (Those checks are the responsibility of HeaderSearch.)
Typically, findModuleForHeader should be used instead, as it picks the preferred module for the header.
Definition at line 682 of file ModuleMap.cpp.
References clang::File.
Referenced by clang::HeaderSearch::findAllModulesForHeader().
findModule()
Module * ModuleMap::findModule (StringRef Name) const
Retrieve a module with the given name.
Parameters
Name The name of the module to look up.
Returns
The named module, if known; otherwise, returns null.
Definition at line 801 of file ModuleMap.cpp.
Referenced by addLinkAsDependency(), clang::serialization::ModuleManager::lookupByModuleName(), clang::HeaderSearch::lookupModule(), lookupModuleQualified(), lookupModuleUnqualified(), and resolveLinkAsDependencies().
findModuleForHeader()
ModuleMap::KnownHeader ModuleMap::findModuleForHeader (FileEntryRef File, bool AllowTextual = false, bool AllowExcluded = false)
Retrieve the module that owns the given header file, if any.
Note that this does not implicitly load module maps, except for builtin headers, and does not consult the external source. (Those checks are the responsibility of HeaderSearch.)
Parameters
File The header file that is likely to be included.
AllowTextual If true and File is a textual header, return its owning module. Otherwise, no KnownHeader will be returned if the file is only known as a textual header.
Returns
The module KnownHeader, which provides the module that owns the given header file. The KnownHeader is default constructed to indicate that no module owns this header file.
Definition at line 580 of file ModuleMap.cpp.
References ExcludedHeader, clang::File, clang::ModuleMap::KnownHeader::getModule(), clang::ModuleMap::KnownHeader::getRole(), clang::Module::getTopLevelModule(), isBetterKnownHeader(), clang::Result, and TextualHeader.
Referenced by clang::HeaderSearch::findModuleForHeader(), and clang::Preprocessor::getModuleForLocation().
findOrCreateModule()
std::pair< Module *, bool > ModuleMap::findOrCreateModule (StringRef Name, Module * Parent, bool IsFramework, bool IsExplicit)
Find a new module or submodule, or create it if it does not already exist.
Parameters
Name The name of the module to find or create.
Parent The module that will act as the parent of this submodule, or nullptr to indicate that this is a top-level module.
IsFramework Whether this is a framework module.
IsExplicit Whether this is an explicit submodule.
Returns
The found or newly-created module, along with a boolean value that will be true if the module is newly-created.
Definition at line 826 of file ModuleMap.cpp.
References clang::LangOptions::CurrentModule, lookupModuleQualified(), clang::Module, Parent, and clang::Result.
findResolvedModulesForHeader()
ArrayRef< ModuleMap::KnownHeader > ModuleMap::findResolvedModulesForHeader (const FileEntry * File) const
Like findAllModulesForHeader, but do not attempt to infer module ownership from umbrella headers if we've not already done so.
Definition at line 694 of file ModuleMap.cpp.
References clang::File, and resolveHeaderDirectives().
Referenced by clang::HeaderSearch::findResolvedModulesForHeader().
finishModuleDeclarationScope()
void clang::ModuleMap::finishModuleDeclarationScope () inline
Creates a new declaration scope for module names, allowing previously defined modules to shadow definitions from the new scope.
Note
Module names from earlier scopes will shadow names from the new scope, which is the opposite of how shadowing works for variables.
Definition at line 600 of file ModuleMap.h.
Referenced by clang::FrontendAction::BeginSourceFile().
getAdditionalModuleMapFiles()
AdditionalModMapsSet * clang::ModuleMap::getAdditionalModuleMapFiles (const Module * M) inline
Get any module map files other than getModuleMapFileForUniquing(M) that define submodules of a top-level module M.
This is cheaper than getting the module map file for each submodule individually, since the expected number of results is very small.
Definition at line 649 of file ModuleMap.h.
getBuiltinDir()
const DirectoryEntry * clang::ModuleMap::getBuiltinDir () const inline
Get the directory that contains Clang-supplied include files.
Definition at line 413 of file ModuleMap.h.
getCachedModuleLoad()
std::optional< Module * > clang::ModuleMap::getCachedModuleLoad (const IdentifierInfo & II) inline
Return a cached module load.
Definition at line 746 of file ModuleMap.h.
Referenced by clang::CompilerInstance::loadModule().
getContainingModuleMapFile()
OptionalFileEntryRef ModuleMap::getContainingModuleMapFile (const Module * Module) const
Retrieve the module map file containing the definition of the given module.
Parameters
Module The module whose module map file will be returned, if known.
Returns
The file entry for the module map file containing the given module, or nullptr if the module definition was inferred.
Definition at line 1286 of file ModuleMap.cpp.
References clang::Module::DefinitionLoc, and clang::SourceLocation::isInvalid().
Referenced by compileModule(), and getModuleMapFileForUniquing().
getModuleMapFileForUniquing()
OptionalFileEntryRef ModuleMap::getModuleMapFileForUniquing (const Module * M) const
Get the module map file that (along with the module name) uniquely identifies this module.
The particular module that Name refers to may depend on how the module was found in header search. However, the combination of Name and this module map will be globally unique for top-level modules. In the case of inferred modules, returns the module map that allowed the inference (e.g. contained 'module *'). Otherwise, returns getContainingModuleMapFile().
Definition at line 1295 of file ModuleMap.cpp.
References getContainingModuleMapFile(), and clang::Module::IsInferred.
Referenced by clang::tooling::dependencies::ModuleDepCollector::applyDiscoveredDependencies(), compileModule(), clang::HeaderSearch::getCachedModuleFileName(), and clang::HeaderSearch::getPrebuiltImplicitModuleFileName().
headerKindToRole()
ModuleMap::ModuleHeaderRole ModuleMap::headerKindToRole (Module::HeaderKind Kind) static
Convert a header kind to a role. Requires Kind to not be HK_Excluded.
Definition at line 93 of file ModuleMap.cpp.
References ExcludedHeader, clang::Module::HK_Excluded, clang::Module::HK_Normal, clang::Module::HK_Private, clang::Module::HK_PrivateTextual, clang::Module::HK_Textual, NormalHeader, PrivateHeader, and TextualHeader.
headerRoleToKind()
Module::HeaderKind ModuleMap::headerRoleToKind (ModuleHeaderRole Role) static
Convert a header role to a kind.
Definition at line 76 of file ModuleMap.cpp.
References ExcludedHeader, clang::Module::HK_Excluded, clang::Module::HK_Normal, clang::Module::HK_Private, clang::Module::HK_PrivateTextual, clang::Module::HK_Textual, NormalHeader, PrivateHeader, Role, and TextualHeader.
Referenced by addHeader().
inferFrameworkModule()
Module * ModuleMap::inferFrameworkModule (DirectoryEntryRef FrameworkDir, bool IsSystem, Module * Parent)
Infer the contents of a framework module map from the given framework directory.
Definition at line 965 of file ModuleMap.cpp.
References Parent.
isBuiltinHeader() [1/2]
bool ModuleMap::isBuiltinHeader (const FileEntry * File)
Definition at line 395 of file ModuleMap.cpp.
References clang::File, and isBuiltinHeader().
isBuiltinHeader() [2/2]
bool ModuleMap::isBuiltinHeader (StringRef FileName) static
Is this a compiler builtin header?
Determine whether the given file name is the name of a builtin header, supplied by Clang to replace, override, or augment existing system headers.
Definition at line 379 of file ModuleMap.cpp.
Referenced by isBuiltinHeader(), clang::HeaderSearch::ShouldEnterIncludeFile(), and suggestModule().
isHeaderInUnavailableModule()
bool ModuleMap::isHeaderInUnavailableModule (FileEntryRef Header) const
Determine whether the given header is part of a module marked 'unavailable'.
Definition at line 703 of file ModuleMap.cpp.
References isHeaderUnavailableInModule().
isHeaderUnavailableInModule()
bool ModuleMap::isHeaderUnavailableInModule (FileEntryRef Header, const Module * RequestingModule) const
Determine whether the given header is unavailable as part of the specified module.
Definition at line 707 of file ModuleMap.cpp.
References ExcludedHeader, clang::FileEntryRef::getDir(), clang::Module::getEffectiveUmbrellaDir(), clang::DirectoryEntryRef::getName(), clang::FileEntryRef::getName(), clang::Module::InferSubmodules, clang::Module::isAvailable(), clang::Module::isSubModuleOf(), lookupModuleQualified(), clang::Module::Parent, resolveHeaderDirectives(), sanitizeFilenameAsIdentifier(), and TextualHeader.
Referenced by collectModuleHeaderIncludes(), and isHeaderInUnavailableModule().
isModular()
bool ModuleMap::isModular (ModuleHeaderRole Role) static
Check if the header with the given role is a modular one.
Definition at line 109 of file ModuleMap.cpp.
References ExcludedHeader, Role, and TextualHeader.
Referenced by clang::HeaderSearch::MarkFileModuleHeader(), and clang::serialization::reader::HeaderFileInfoTrait::ReadData().
lookupModuleQualified()
Module * ModuleMap::lookupModuleQualified (StringRef Name, Module * Context) const
Retrieve a module with the given name within the given context, using direct (qualified) name lookup.
Parameters
Name The name of the module to look up.
Context The module for which we will look for a submodule. If null, we will look for a top-level module.
Returns
The named submodule, if known; otherwose, returns null.
Definition at line 819 of file ModuleMap.cpp.
References findModule().
Referenced by findOrCreateModule(), isHeaderUnavailableInModule(), and lookupModuleUnqualified().
lookupModuleUnqualified()
Module * ModuleMap::lookupModuleUnqualified (StringRef Name, Module * Context) const
Retrieve a module with the given name using lexical name lookup, starting at the given context.
Parameters
Name The name of the module to look up.
Context The module context, from which we will perform lexical name lookup.
Returns
The named module, if known; otherwise, returns null.
Definition at line 809 of file ModuleMap.cpp.
References findModule(), and lookupModuleQualified().
mayShadowNewModule()
bool clang::ModuleMap::mayShadowNewModule (Module * ExistingModule) inline
Definition at line 602 of file ModuleMap.h.
References clang::Module::Parent.
module_begin()
module_iterator clang::ModuleMap::module_begin () const inline
Definition at line 734 of file ModuleMap.h.
Referenced by clang::CompilerInstance::loadGlobalModuleIndex(), and modules().
module_end()
module_iterator clang::ModuleMap::module_end () const inline
Definition at line 735 of file ModuleMap.h.
Referenced by clang::CompilerInstance::loadGlobalModuleIndex(), and modules().
modules()
llvm::iterator_range< module_iterator > clang::ModuleMap::modules () const inline
Definition at line 736 of file ModuleMap.h.
References module_begin(), and module_end().
Referenced by clang::HeaderSearch::collectAllModules().
parseModuleMapFile()
bool ModuleMap::parseModuleMapFile (const FileEntry * File, bool IsSystem, DirectoryEntryRef HomeDir, FileID ID = FileID(), unsigned * Offset = nullptr, SourceLocation ExternModuleLoc = SourceLocation())
Parse the given module map file, and record any modules we encounter.
Parameters
File The file to be parsed.
IsSystem Whether this module map file is in a system header directory, and therefore should be considered a system module.
HomeDir The directory in which relative paths within this module map file will be resolved.
ID The FileID of the file to process, if we've already entered it.
Offset [inout] On input the offset at which to start parsing. On output, the offset at which the module map terminated.
ExternModuleLoc The location of the "extern module" declaration that caused us to load this module map file, if any.
Returns
true if an error occurred, false otherwise.
Definition at line 3081 of file ModuleMap.cpp.
References clang::SrcMgr::C_System_ModuleMap, clang::SrcMgr::C_User_ModuleMap, clang::File, clang::Lexer::getSourceLocation(), Offset, and clang::Result.
resolveConflicts()
bool ModuleMap::resolveConflicts (Module * Mod, bool Complain)
Resolve all of the unresolved conflicts in the given module.
Parameters
Mod The module whose conflicts should be resolved.
Complain Whether to emit diagnostics for failures.
Returns
true if any errors were encountered while resolving conflicts, false otherwise.
Definition at line 1395 of file ModuleMap.cpp.
References clang::Module::Conflicts, clang::Module::Conflict::Message, clang::Module::Conflict::Other, clang::Unresolved, and clang::Module::UnresolvedConflicts.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), and clang::Preprocessor::EnterSubmodule().
resolveExports()
bool ModuleMap::resolveExports (Module * Mod, bool Complain)
Resolve all of the unresolved exports in the given module.
Parameters
Mod The module whose exports should be resolved.
Complain Whether to emit diagnostics for failures.
Returns
true if any errors were encountered while resolving exports, false otherwise.
Definition at line 1369 of file ModuleMap.cpp.
References clang::Module::Exports, clang::Unresolved, and clang::Module::UnresolvedExports.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), and clang::Preprocessor::EnterSubmodule().
resolveHeaderDirectives() [1/2]
void ModuleMap::resolveHeaderDirectives (const FileEntry * File) const
Resolve all lazy header directives for the specified file.
This ensures that the HeaderFileInfo on HeaderSearch is up to date. This is effectively internal, but is exposed so HeaderSearch can call it.
Definition at line 1222 of file ModuleMap.cpp.
References clang::File, and resolveHeaderDirectives().
Referenced by collectModuleHeaderIncludes(), diagnoseHeaderInclusion(), findResolvedModulesForHeader(), isHeaderUnavailableInModule(), resolveHeaderDirectives(), and clang::HeaderSearch::ShouldEnterIncludeFile().
resolveHeaderDirectives() [2/2]
void ModuleMap::resolveHeaderDirectives (Module * Mod, std::optional< const FileEntry * > File) const
Resolve lazy header directives for the specified module.
If File is provided, only headers with same size and modtime are resolved. If File is not set, all headers are resolved.
Definition at line 1238 of file ModuleMap.cpp.
References clang::File, clang::Module::UnresolvedHeaderDirective::ModTime, clang::Module::UnresolvedHeaderDirective::Size, and clang::Module::UnresolvedHeaders.
resolveLinkAsDependencies()
void ModuleMap::resolveLinkAsDependencies (Module * Mod)
Use PendingLinkAsModule information to mark top level link names that are going to be replaced by export_as aliases.
Definition at line 58 of file ModuleMap.cpp.
References findModule(), and clang::Module::Name.
Referenced by clang::CompilerInstance::loadModule().
resolveUses()
bool ModuleMap::resolveUses (Module * Mod, bool Complain)
Resolve all of the unresolved uses in the given module.
Parameters
Mod The module whose uses should be resolved.
Complain Whether to emit diagnostics for failures.
Returns
true if any errors were encountered while resolving uses, false otherwise.
Definition at line 1382 of file ModuleMap.cpp.
References clang::Module::DirectUses, clang::Unresolved, and clang::Module::UnresolvedDirectUses.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), diagnoseHeaderInclusion(), clang::Preprocessor::EnterSubmodule(), and suggestModule().
setBuiltinIncludeDir()
void clang::ModuleMap::setBuiltinIncludeDir (DirectoryEntryRef Dir) inline
Set the directory that contains Clang-supplied include files, such as our stdarg.h or tgmath.h.
Definition at line 408 of file ModuleMap.h.
Referenced by clang::ApplyHeaderSearchOptions().
setInferredModuleAllowedBy()
void ModuleMap::setInferredModuleAllowedBy (Module * M, const FileEntry * ModMap)
Definition at line 1304 of file ModuleMap.cpp.
References clang::Module::IsInferred.
Referenced by prepareToBuildModule().
setTarget()
void ModuleMap::setTarget (const TargetInfo & Target)
Set the target information.
Definition at line 333 of file ModuleMap.cpp.
Referenced by clang::HeaderSearch::setTarget().
setUmbrellaDirAsWritten()
void ModuleMap::setUmbrellaDirAsWritten (Module * Mod, DirectoryEntryRef UmbrellaDir, const Twine & NameAsWritten, const Twine & PathRelativeToRootModuleDirectory)
Sets the umbrella directory of the given module to the given directory.
Definition at line 1176 of file ModuleMap.cpp.
References clang::Module::Umbrella, clang::Module::UmbrellaAsWritten, and clang::Module::UmbrellaRelativeToRootModuleDirectory.
setUmbrellaHeaderAsWritten()
void ModuleMap::setUmbrellaHeaderAsWritten (Module * Mod, FileEntryRef UmbrellaHeader, const Twine & NameAsWritten, const Twine & PathRelativeToRootModuleDirectory)
Sets the umbrella header of the given module to the given header.
Definition at line 1161 of file ModuleMap.cpp.
References clang::FileEntryRef::getDir(), NormalHeader, clang::Module::Umbrella, clang::Module::UmbrellaAsWritten, and clang::Module::UmbrellaRelativeToRootModuleDirectory.
Friends And Related Symbol Documentation
ModuleMapParser
friend class ModuleMapParser friend
Definition at line 200 of file ModuleMap.h.
The documentation for this class was generated from the following files:
include/clang/Lex/ModuleMap.h
lib/Lex/ModuleMap.cpp