clang: clang::ObjCInterfaceType Class Reference
clang::ObjCInterfaceType Class Reference
Represents typeof(type), a C2x feature and GCC extension, or `typeof_unqual(type), a C2x feature.
#include "clang/AST/Type.h"
Public Types
enum {
qual_iterator , qual_begin , qual_end , getNumProtocols ,
getProtocol
}
Public Member Functions
ObjCInterfaceDecl * getDecl () const
Get the declaration of this interface.
bool isSugared () const
QualType desugar () const
Static Public Member Functions
static bool classof (const Type *T)
Friends
class ASTContext
class ASTReader
template<class T >
class serialization::AbstractTypeReader
Detailed Description
Represents typeof(type), a C2x feature and GCC extension, or `typeof_unqual(type), a C2x feature.
class TypeOfType : public Type { friend class ASTContext; // ASTContext creates these.
QualType TOType;
TypeOfType(QualType T, QualType Can, TypeOfKind Kind) : Type(TypeOf, Kind == TypeOfKind::Unqualified ? Can.getAtomicUnqualifiedType() : Can, T->getDependence()), TOType(T) { TypeOfBits.IsUnqual = Kind == TypeOfKind::Unqualified; }
public: QualType getUnmodifiedType() const { return TOType; }
/ Remove a single level of sugar. QualType desugar() const { QualType QT = getUnmodifiedType(); return TypeOfBits.IsUnqual ? QT.getAtomicUnqualifiedType() : QT; }
/ Returns whether this type directly provides sugar. bool isSugared() const { return true; }
/ Returns the kind of 'typeof' type this is. TypeOfKind getKind() const { return TypeOfBits.IsUnqual ? TypeOfKind::Unqualified : TypeOfKind::Qualified; }
static bool classof(const Type *T) { return T->getTypeClass() == TypeOf; } };
/ Represents the type decltype(expr) (C++11). class DecltypeType : public Type { Expr *E; QualType UnderlyingType;
protected: friend class ASTContext; // ASTContext creates these.
DecltypeType(Expr *E, QualType underlyingType, QualType can = QualType());
public: Expr *getUnderlyingExpr() const { return E; } QualType getUnderlyingType() const { return UnderlyingType; }
/ Remove a single level of sugar. QualType desugar() const;
/ Returns whether this type directly provides sugar. bool isSugared() const;
static bool classof(const Type *T) { return T->getTypeClass() == Decltype; } };
/ Internal representation of canonical, dependent / decltype(expr) types. / / This class is used internally by the ASTContext to manage / canonical, dependent types, only. Clients will only see instances / of this class via DecltypeType nodes. class DependentDecltypeType : public DecltypeType, public llvm::FoldingSetNode { const ASTContext &Context;
public: DependentDecltypeType(const ASTContext &Context, Expr *E);
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, Context, getUnderlyingExpr()); }
static void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Context, Expr *E); };
/ A unary type transform, which is a type constructed from another. class UnaryTransformType : public Type { public: enum UTTKind { #define TRANSFORM_TYPE_TRAIT_DEF(Enum, _)
};
private: / The untransformed type. QualType BaseType;
/ The transformed type if not dependent, otherwise the same as BaseType. QualType UnderlyingType;
UTTKind UKind;
protected: friend class ASTContext;
UnaryTransformType(QualType BaseTy, QualType UnderlyingTy, UTTKind UKind, QualType CanonicalTy);
public: bool isSugared() const { return !isDependentType(); } QualType desugar() const { return UnderlyingType; }
QualType getUnderlyingType() const { return UnderlyingType; } QualType getBaseType() const { return BaseType; }
UTTKind getUTTKind() const { return UKind; }
static bool classof(const Type *T) { return T->getTypeClass() == UnaryTransform; } };
/ Internal representation of canonical, dependent / __underlying_type(type) types. / / This class is used internally by the ASTContext to manage / canonical, dependent types, only. Clients will only see instances / of this class via UnaryTransformType nodes. class DependentUnaryTransformType : public UnaryTransformType, public llvm::FoldingSetNode { public: DependentUnaryTransformType(const ASTContext &C, QualType BaseType, UTTKind UKind);
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getBaseType(), getUTTKind()); }
static void Profile(llvm::FoldingSetNodeID &ID, QualType BaseType, UTTKind UKind) { ID.AddPointer(BaseType.getAsOpaquePtr()); ID.AddInteger((unsigned)UKind); } };
class TagType : public Type { friend class ASTReader; template <class T> friend class serialization::AbstractTypeReader;
/ Stores the TagDecl associated with this type. The decl may point to any / TagDecl that declares the entity. TagDecl *decl;
protected: TagType(TypeClass TC, const TagDecl *D, QualType can);
public: TagDecl *getDecl() const;
/ Determines whether this type is in the process of being defined. bool isBeingDefined() const;
static bool classof(const Type *T) { return T->getTypeClass() == Enum || T->getTypeClass() == Record; } };
/ A helper class that allows the use of isa/cast/dyncast / to detect TagType objects of structs/unions/classes. class RecordType : public TagType { protected: friend class ASTContext; // ASTContext creates these.
explicit RecordType(const RecordDecl <em>D) : TagType(Record, reinterpret_cast<const TagDecl>(D), QualType()) {} explicit RecordType(TypeClass TC, RecordDecl <em>D) : TagType(TC, reinterpret_cast<const TagDecl>(D), QualType()) {}
public: RecordDecl getDecl() const { return reinterpret_cast<RecordDecl>(TagType::getDecl()); }
/ Recursively check all fields in the record for const-ness. If any field / is declared const, return true. Otherwise, return false. bool hasConstFields() const;
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
static bool classof(const Type *T) { return T->getTypeClass() == Record; } };
/ A helper class that allows the use of isa/cast/dyncast / to detect TagType objects of enums. class EnumType : public TagType { friend class ASTContext; // ASTContext creates these.
explicit EnumType(const EnumDecl <em>D) : TagType(Enum, reinterpret_cast<const TagDecl>(D), QualType()) {}
public: EnumDecl getDecl() const { return reinterpret_cast<EnumDecl>(TagType::getDecl()); }
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
static bool classof(const Type *T) { return T->getTypeClass() == Enum; } };
/ An attributed type is a type to which a type attribute has been applied. / / The "modified type" is the fully-sugared type to which the attributed / type was applied; generally it is not canonically equivalent to the / attributed type. The "equivalent type" is the minimally-desugared type / which the type is canonically equivalent to. / / For example, in the following attributed type: / int32_t attribute((vector_size(16))) / - the modified type is the TypedefType for int32_t / - the equivalent type is VectorType(16, int32_t) / - the canonical type is VectorType(16, int) class AttributedType : public Type, public llvm::FoldingSetNode { public: using Kind = attr::Kind;
private: friend class ASTContext; // ASTContext creates these
QualType ModifiedType; QualType EquivalentType;
AttributedType(QualType canon, attr::Kind attrKind, QualType modified, QualType equivalent) : Type(Attributed, canon, equivalent->getDependence()), ModifiedType(modified), EquivalentType(equivalent) { AttributedTypeBits.AttrKind = attrKind; }
public: Kind getAttrKind() const { return static_cast<Kind>(AttributedTypeBits.AttrKind); }
QualType getModifiedType() const { return ModifiedType; } QualType getEquivalentType() const { return EquivalentType; }
bool isSugared() const { return true; } QualType desugar() const { return getEquivalentType(); }
/ Does this attribute behave like a type qualifier? / / A type qualifier adjusts a type to provide specialized rules for / a specific object, like the standard const and volatile qualifiers. / This includes attributes controlling things like nullability, / address spaces, and ARC ownership. The value of the object is still / largely described by the modified type. / / In contrast, many type attributes "rewrite" their modified type to / produce a fundamentally different type, not necessarily related in any / formalizable way to the original type. For example, calling convention / and vector attributes are not simple type qualifiers. / / Type qualifiers are often, but not always, reflected in the canonical / type. bool isQualifier() const;
bool isMSTypeSpec() const;
bool isWebAssemblyFuncrefSpec() const;
bool isCallingConv() const;
std::optional<NullabilityKind> getImmediateNullability() const;
/ Retrieve the attribute kind corresponding to the given / nullability kind. static Kind getNullabilityAttrKind(NullabilityKind kind) { switch (kind) { case NullabilityKind::NonNull: return attr::TypeNonNull;
case NullabilityKind::Nullable: return attr::TypeNullable;
case NullabilityKind::NullableResult: return attr::TypeNullableResult;
case NullabilityKind::Unspecified: return attr::TypeNullUnspecified; } llvm_unreachable("Unknown nullability kind."); }
/ Strip off the top-level nullability annotation on the given / type, if it's there. / /
Parameters
T The type to strip. If the type is exactly an / AttributedType specifying nullability (without looking through / type sugar), the nullability is returned and this type changed / to the underlying modified type. / /
Returns
the top-level nullability, if present. static std::optional<NullabilityKind> stripOuterNullability(QualType &T);
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getAttrKind(), ModifiedType, EquivalentType); }
static void Profile(llvm::FoldingSetNodeID &ID, Kind attrKind, QualType modified, QualType equivalent) { ID.AddInteger(attrKind); ID.AddPointer(modified.getAsOpaquePtr()); ID.AddPointer(equivalent.getAsOpaquePtr()); }
static bool classof(const Type *T) { return T->getTypeClass() == Attributed; } };
class BTFTagAttributedType : public Type, public llvm::FoldingSetNode { private: friend class ASTContext; // ASTContext creates these
QualType WrappedType; const BTFTypeTagAttr *BTFAttr;
BTFTagAttributedType(QualType Canon, QualType Wrapped, const BTFTypeTagAttr *BTFAttr) : Type(BTFTagAttributed, Canon, Wrapped->getDependence()), WrappedType(Wrapped), BTFAttr(BTFAttr) {}
public: QualType getWrappedType() const { return WrappedType; } const BTFTypeTagAttr *getAttr() const { return BTFAttr; }
bool isSugared() const { return true; } QualType desugar() const { return getWrappedType(); }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, WrappedType, BTFAttr); }
static void Profile(llvm::FoldingSetNodeID &ID, QualType Wrapped, const BTFTypeTagAttr *BTFAttr) { ID.AddPointer(Wrapped.getAsOpaquePtr()); ID.AddPointer(BTFAttr); }
static bool classof(const Type *T) { return T->getTypeClass() == BTFTagAttributed; } };
class TemplateTypeParmType : public Type, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
Helper data collector for canonical types. struct CanonicalTTPTInfo { unsigned Depth : 15; unsigned ParameterPack : 1; unsigned Index : 16; };
union { Info for the canonical type. CanonicalTTPTInfo CanTTPTInfo;
Info for the non-canonical type. TemplateTypeParmDecl *TTPDecl; };
/ Build a non-canonical type. TemplateTypeParmType(TemplateTypeParmDecl *TTPDecl, QualType Canon) : Type(TemplateTypeParm, Canon, TypeDependence::DependentInstantiation | (Canon->getDependence() & TypeDependence::UnexpandedPack)), TTPDecl(TTPDecl) {}
/ Build the canonical type. TemplateTypeParmType(unsigned D, unsigned I, bool PP) : Type(TemplateTypeParm, QualType(this, 0), TypeDependence::DependentInstantiation | (PP ? TypeDependence::UnexpandedPack : TypeDependence::None)) { CanTTPTInfo.Depth = D; CanTTPTInfo.Index = I; CanTTPTInfo.ParameterPack = PP; }
const CanonicalTTPTInfo& getCanTTPTInfo() const { QualType Can = getCanonicalTypeInternal(); return Can->castAs<TemplateTypeParmType>()->CanTTPTInfo; }
public: unsigned getDepth() const { return getCanTTPTInfo().Depth; } unsigned getIndex() const { return getCanTTPTInfo().Index; } bool isParameterPack() const { return getCanTTPTInfo().ParameterPack; }
TemplateTypeParmDecl *getDecl() const { return isCanonicalUnqualified() ? nullptr : TTPDecl; }
IdentifierInfo *getIdentifier() const;
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getDepth(), getIndex(), isParameterPack(), getDecl()); }
static void Profile(llvm::FoldingSetNodeID &ID, unsigned Depth, unsigned Index, bool ParameterPack, TemplateTypeParmDecl *TTPDecl) { ID.AddInteger(Depth); ID.AddInteger(Index); ID.AddBoolean(ParameterPack); ID.AddPointer(TTPDecl); }
static bool classof(const Type *T) { return T->getTypeClass() == TemplateTypeParm; } };
/ Represents the result of substituting a type for a template / type parameter. / / Within an instantiated template, all template type parameters have / been replaced with these. They are used solely to record that a / type was originally written as a template type parameter; / therefore they are never canonical. class SubstTemplateTypeParmType final : public Type, public llvm::FoldingSetNode, private llvm::TrailingObjects<SubstTemplateTypeParmType, QualType> { friend class ASTContext; friend class llvm::TrailingObjects<SubstTemplateTypeParmType, QualType>;
Decl *AssociatedDecl;
SubstTemplateTypeParmType(QualType Replacement, Decl *AssociatedDecl, unsigned Index, std::optional<unsigned> PackIndex);
public: / Gets the type that was substituted for the template / parameter. QualType getReplacementType() const { return SubstTemplateTypeParmTypeBits.HasNonCanonicalUnderlyingType ? *getTrailingObjects<QualType>() : getCanonicalTypeInternal(); }
/ A template-like entity which owns the whole pattern being substituted. / This will usually own a set of template parameters, or in some / cases might even be a template parameter itself. Decl *getAssociatedDecl() const { return AssociatedDecl; }
/ Gets the template parameter declaration that was substituted for. const TemplateTypeParmDecl *getReplacedParameter() const;
/ Returns the index of the replaced parameter in the associated declaration. / This should match the result of getReplacedParameter()->getIndex(). unsigned getIndex() const { return SubstTemplateTypeParmTypeBits.Index; }
std::optional<unsigned> getPackIndex() const { if (SubstTemplateTypeParmTypeBits.PackIndex == 0) return std::nullopt; return SubstTemplateTypeParmTypeBits.PackIndex - 1; }
bool isSugared() const { return true; } QualType desugar() const { return getReplacementType(); }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getReplacementType(), getAssociatedDecl(), getIndex(), getPackIndex()); }
static void Profile(llvm::FoldingSetNodeID &ID, QualType Replacement, const Decl *AssociatedDecl, unsigned Index, std::optional<unsigned> PackIndex) { Replacement.Profile(ID); ID.AddPointer(AssociatedDecl); ID.AddInteger(Index); ID.AddInteger(PackIndex ? *PackIndex - 1 : 0); }
static bool classof(const Type *T) { return T->getTypeClass() == SubstTemplateTypeParm; } };
/ Represents the result of substituting a set of types for a template / type parameter pack. / / When a pack expansion in the source code contains multiple parameter packs / and those parameter packs correspond to different levels of template / parameter lists, this type node is used to represent a template type / parameter pack from an outer level, which has already had its argument pack / substituted but that still lives within a pack expansion that itself / could not be instantiated. When actually performing a substitution into / that pack expansion (e.g., when all template parameters have corresponding / arguments), this type will be replaced with the SubstTemplateTypeParmType / at the current pack substitution index. class SubstTemplateTypeParmPackType : public Type, public llvm::FoldingSetNode { friend class ASTContext;
/ A pointer to the set of template arguments that this / parameter pack is instantiated with. const TemplateArgument *Arguments;
llvm::PointerIntPair<Decl *, 1, bool> AssociatedDeclAndFinal;
SubstTemplateTypeParmPackType(QualType Canon, Decl *AssociatedDecl, unsigned Index, bool Final, const TemplateArgument &ArgPack);
public: IdentifierInfo *getIdentifier() const;
/ A template-like entity which owns the whole pattern being substituted. / This will usually own a set of template parameters, or in some / cases might even be a template parameter itself. Decl *getAssociatedDecl() const;
/ Gets the template parameter declaration that was substituted for. const TemplateTypeParmDecl *getReplacedParameter() const;
/ Returns the index of the replaced parameter in the associated declaration. / This should match the result of getReplacedParameter()->getIndex(). unsigned getIndex() const { return SubstTemplateTypeParmPackTypeBits.Index; }
When true the substitution will be 'Final' (subst node won't be placed). bool getFinal() const;
unsigned getNumArgs() const { return SubstTemplateTypeParmPackTypeBits.NumArgs; }
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
TemplateArgument getArgumentPack() const;
void Profile(llvm::FoldingSetNodeID &ID); static void Profile(llvm::FoldingSetNodeID &ID, const Decl *AssociatedDecl, unsigned Index, bool Final, const TemplateArgument &ArgPack);
static bool classof(const Type *T) { return T->getTypeClass() == SubstTemplateTypeParmPack; } };
/ Common base class for placeholders for types that get replaced by / placeholder type deduction: C++11 auto, C++14 decltype(auto), C++17 deduced / class template types, and constrained type names. / / These types are usually a placeholder for a deduced type. However, before / the initializer is attached, or (usually) if the initializer is / type-dependent, there is no deduced type and the type is canonical. In / the latter case, it is also a dependent type. class DeducedType : public Type { QualType DeducedAsType;
protected: DeducedType(TypeClass TC, QualType DeducedAsType, TypeDependence ExtraDependence, QualType Canon) : Type(TC, Canon, ExtraDependence | (DeducedAsType.isNull() ? TypeDependence::None : DeducedAsType->getDependence() & ~TypeDependence::VariablyModified)), DeducedAsType(DeducedAsType) {}
public: bool isSugared() const { return !DeducedAsType.isNull(); } QualType desugar() const { return isSugared() ? DeducedAsType : QualType(this, 0); }
/ Get the type deduced for this placeholder type, or null if it / has not been deduced. QualType getDeducedType() const { return DeducedAsType; } bool isDeduced() const { return !DeducedAsType.isNull() || isDependentType(); }
static bool classof(const Type *T) { return T->getTypeClass() == Auto || T->getTypeClass() == DeducedTemplateSpecialization; } };
/ Represents a C++11 auto or C++14 decltype(auto) type, possibly constrained / by a type-constraint. class alignas(8) AutoType : public DeducedType, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
ConceptDecl *TypeConstraintConcept;
AutoType(QualType DeducedAsType, AutoTypeKeyword Keyword, TypeDependence ExtraDependence, QualType Canon, ConceptDecl *CD, ArrayRef<TemplateArgument> TypeConstraintArgs);
public: ArrayRef<TemplateArgument> getTypeConstraintArguments() const { return {reinterpret_cast<const TemplateArgument *>(this + 1), AutoTypeBits.NumArgs}; }
ConceptDecl *getTypeConstraintConcept() const { return TypeConstraintConcept; }
bool isConstrained() const { return TypeConstraintConcept != nullptr; }
bool isDecltypeAuto() const { return getKeyword() == AutoTypeKeyword::DecltypeAuto; }
bool isGNUAutoType() const { return getKeyword() == AutoTypeKeyword::GNUAutoType; }
AutoTypeKeyword getKeyword() const { return (AutoTypeKeyword)AutoTypeBits.Keyword; }
void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Context); static void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Context, QualType Deduced, AutoTypeKeyword Keyword, bool IsDependent, ConceptDecl *CD, ArrayRef<TemplateArgument> Arguments);
static bool classof(const Type *T) { return T->getTypeClass() == Auto; } };
/ Represents a C++17 deduced template specialization type. class DeducedTemplateSpecializationType : public DeducedType, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
/ The name of the template whose arguments will be deduced. TemplateName Template;
DeducedTemplateSpecializationType(TemplateName Template, QualType DeducedAsType, bool IsDeducedAsDependent) : DeducedType(DeducedTemplateSpecialization, DeducedAsType, toTypeDependence(Template.getDependence()) | (IsDeducedAsDependent ? TypeDependence::DependentInstantiation : TypeDependence::None), DeducedAsType.isNull() ? QualType(this, 0) : DeducedAsType.getCanonicalType()), Template(Template) {}
public: / Retrieve the name of the template that we are deducing. TemplateName getTemplateName() const { return Template;}
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getTemplateName(), getDeducedType(), isDependentType()); }
static void Profile(llvm::FoldingSetNodeID &ID, TemplateName Template, QualType Deduced, bool IsDependent) { Template.Profile(ID); QualType CanonicalType = Deduced.isNull() ? Deduced : Deduced.getCanonicalType(); ID.AddPointer(CanonicalType.getAsOpaquePtr()); ID.AddBoolean(IsDependent || Template.isDependent()); }
static bool classof(const Type *T) { return T->getTypeClass() == DeducedTemplateSpecialization; } };
/ Represents a type template specialization; the template / must be a class template, a type alias template, or a template / template parameter. A template which cannot be resolved to one of / these, e.g. because it is written with a dependent scope / specifier, is instead represented as a / DependentTemplateSpecializationType. / / A non-dependent template specialization type is always "sugar", / typically for a RecordType. For example, a class template / specialization type of vector<int> will refer to a tag type for / the instantiation std::vector<int, std::allocator<int>> / / Template specializations are dependent if either the template or / any of the template arguments are dependent, in which case the / type may also be canonical. / / Instances of this type are allocated with a trailing array of / TemplateArguments, followed by a QualType representing the / non-canonical aliased type when the template is a type alias / template. class alignas(8) TemplateSpecializationType : public Type, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
/ The name of the template being specialized. This is / either a TemplateName::Template (in which case it is a / ClassTemplateDecl*, a TemplateTemplateParmDecl*, or a / TypeAliasTemplateDecl*), a / TemplateName::SubstTemplateTemplateParmPack, or a / TemplateName::SubstTemplateTemplateParm (in which case the / replacement must, recursively, be one of these). TemplateName Template;
TemplateSpecializationType(TemplateName T, ArrayRef<TemplateArgument> Args, QualType Canon, QualType Aliased);
public: / Determine whether any of the given template arguments are dependent. / / The converted arguments should be supplied when known; whether an / argument is dependent can depend on the conversions performed on it / (for example, a 'const int' passed as a template argument might be / dependent if the parameter is a reference but non-dependent if the / parameter is an int). / / Note that the Args parameter is unused: this is intentional, to remind / the caller that they need to pass in the converted arguments, not the / specified arguments. static bool anyDependentTemplateArguments(ArrayRef<TemplateArgumentLoc> Args, ArrayRef<TemplateArgument> Converted); static bool anyDependentTemplateArguments(const TemplateArgumentListInfo &, ArrayRef<TemplateArgument> Converted); static bool anyInstantiationDependentTemplateArguments(ArrayRef<TemplateArgumentLoc> Args);
/ True if this template specialization type matches a current / instantiation in the context in which it is found. bool isCurrentInstantiation() const { return isa<InjectedClassNameType>(getCanonicalTypeInternal()); }
/ Determine if this template specialization type is for a type alias / template that has been substituted. / / Nearly every template specialization type whose template is an alias / template will be substituted. However, this is not the case when / the specialization contains a pack expansion but the template alias / does not have a corresponding parameter pack, e.g., / /
/// template<typename T, typename U, typename V> struct S;
/// template<typename T, typename U> using A = S<T, int, U>;
/// template<typename... Ts> struct X {
///   typedef A<Ts...> type; // not a type alias
/// };
///
bool isTypeAlias() const { return TemplateSpecializationTypeBits.TypeAlias; }
/ Get the aliased type, if this is a specialization of a type alias / template. QualType getAliasedType() const;
/ Retrieve the name of the template that we are specializing. TemplateName getTemplateName() const { return Template; }
ArrayRef<TemplateArgument> template_arguments() const { return {reinterpret_cast<const TemplateArgument *>(this + 1), TemplateSpecializationTypeBits.NumArgs}; }
bool isSugared() const { return !isDependentType() || isCurrentInstantiation() || isTypeAlias(); }
QualType desugar() const { return isTypeAlias() ? getAliasedType() : getCanonicalTypeInternal(); }
void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Ctx); static void Profile(llvm::FoldingSetNodeID &ID, TemplateName T, ArrayRef<TemplateArgument> Args, const ASTContext &Context);
static bool classof(const Type *T) { return T->getTypeClass() == TemplateSpecialization; } };
/ Print a template argument list, including the '<' and '>' / enclosing the template arguments. void printTemplateArgumentList(raw_ostream &OS, ArrayRef<TemplateArgument> Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL = nullptr);
void printTemplateArgumentList(raw_ostream &OS, ArrayRef<TemplateArgumentLoc> Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL = nullptr);
void printTemplateArgumentList(raw_ostream &OS, const TemplateArgumentListInfo &Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL = nullptr);
/ Make a best-effort determination of whether the type T can be produced by / substituting Args into the default argument of Param. bool isSubstitutedDefaultArgument(ASTContext &Ctx, TemplateArgument Arg, const NamedDecl *Param, ArrayRef<TemplateArgument> Args, unsigned Depth);
/ The injected class name of a C++ class template or class / template partial specialization. Used to record that a type was / spelled with a bare identifier rather than as a template-id; the / equivalent for non-templated classes is just RecordType. / / Injected class name types are always dependent. Template / instantiation turns these into RecordTypes. / / Injected class name types are always canonical. This works / because it is impossible to compare an injected class name type / with the corresponding non-injected template type, for the same / reason that it is impossible to directly compare template / parameters from different dependent contexts: injected class name / types can only occur within the scope of a particular templated / declaration, and within that scope every template specialization / will canonicalize to the injected class name (when appropriate / according to the rules of the language). class InjectedClassNameType : public Type { friend class ASTContext; // ASTContext creates these. friend class ASTNodeImporter; friend class ASTReader; // FIXME: ASTContext::getInjectedClassNameType is not currently suitable for AST reading, too much interdependencies. template <class T> friend class serialization::AbstractTypeReader;
CXXRecordDecl *Decl;
/ The template specialization which this type represents. / For example, in / template <class T> class A { ... }; / this is A<T>, whereas in / template <class X, class Y> class A<B<X,Y> > { ... }; / this is A<B<X,Y> >. / / It is always unqualified, always a template specialization type, / and always dependent. QualType InjectedType;
InjectedClassNameType(CXXRecordDecl *D, QualType TST) : Type(InjectedClassName, QualType(), TypeDependence::DependentInstantiation), Decl(D), InjectedType(TST) { assert(isa<TemplateSpecializationType>(TST)); assert(!TST.hasQualifiers()); assert(TST->isDependentType()); }
public: QualType getInjectedSpecializationType() const { return InjectedType; }
const TemplateSpecializationType *getInjectedTST() const { return cast<TemplateSpecializationType>(InjectedType.getTypePtr()); }
TemplateName getTemplateName() const { return getInjectedTST()->getTemplateName(); }
CXXRecordDecl *getDecl() const;
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
static bool classof(const Type *T) { return T->getTypeClass() == InjectedClassName; } };
/ The kind of a tag type. enum TagTypeKind { / The "struct" keyword. TTK_Struct,
/ The "__interface" keyword. TTK_Interface,
/ The "union" keyword. TTK_Union,
/ The "class" keyword. TTK_Class,
/ The "enum" keyword. TTK_Enum };
/ The elaboration keyword that precedes a qualified type name or / introduces an elaborated-type-specifier. enum ElaboratedTypeKeyword { / The "struct" keyword introduces the elaborated-type-specifier. ETK_Struct,
/ The "__interface" keyword introduces the elaborated-type-specifier. ETK_Interface,
/ The "union" keyword introduces the elaborated-type-specifier. ETK_Union,
/ The "class" keyword introduces the elaborated-type-specifier. ETK_Class,
/ The "enum" keyword introduces the elaborated-type-specifier. ETK_Enum,
/ The "typename" keyword precedes the qualified type name, e.g., / typename T::type. ETK_Typename,
/ No keyword precedes the qualified type name. ETK_None };
/ A helper class for Type nodes having an ElaboratedTypeKeyword. / The keyword in stored in the free bits of the base class. / Also provides a few static helpers for converting and printing / elaborated type keyword and tag type kind enumerations. class TypeWithKeyword : public Type { protected: TypeWithKeyword(ElaboratedTypeKeyword Keyword, TypeClass tc, QualType Canonical, TypeDependence Dependence) : Type(tc, Canonical, Dependence) { TypeWithKeywordBits.Keyword = Keyword; }
public: ElaboratedTypeKeyword getKeyword() const { return static_cast<ElaboratedTypeKeyword>(TypeWithKeywordBits.Keyword); }
/ Converts a type specifier (DeclSpec::TST) into an elaborated type keyword. static ElaboratedTypeKeyword getKeywordForTypeSpec(unsigned TypeSpec);
/ Converts a type specifier (DeclSpec::TST) into a tag type kind. / It is an error to provide a type specifier which isn't a tag kind here. static TagTypeKind getTagTypeKindForTypeSpec(unsigned TypeSpec);
/ Converts a TagTypeKind into an elaborated type keyword. static ElaboratedTypeKeyword getKeywordForTagTypeKind(TagTypeKind Tag);
/ Converts an elaborated type keyword into a TagTypeKind. / It is an error to provide an elaborated type keyword / which isn't a tag kind here. static TagTypeKind getTagTypeKindForKeyword(ElaboratedTypeKeyword Keyword);
static bool KeywordIsTagTypeKind(ElaboratedTypeKeyword Keyword);
static StringRef getKeywordName(ElaboratedTypeKeyword Keyword);
static StringRef getTagTypeKindName(TagTypeKind Kind) { return getKeywordName(getKeywordForTagTypeKind(Kind)); }
class CannotCastToThisType {}; static CannotCastToThisType classof(const Type *); };
/ Represents a type that was referred to using an elaborated type / keyword, e.g., struct S, or via a qualified name, e.g., N::M::type, / or both. / / This type is used to keep track of a type name as written in the / source code, including tag keywords and any nested-name-specifiers. / The type itself is always "sugar", used to express what was written / in the source code but containing no additional semantic information. class ElaboratedType final : public TypeWithKeyword, public llvm::FoldingSetNode, private llvm::TrailingObjects<ElaboratedType, TagDecl *> { friend class ASTContext; // ASTContext creates these friend TrailingObjects;
/ The nested name specifier containing the qualifier. NestedNameSpecifier *NNS;
/ The type that this qualified name refers to. QualType NamedType;
/ The (re)declaration of this tag type owned by this occurrence is stored / as a trailing object if there is one. Use getOwnedTagDecl to obtain / it, or obtain a null pointer if there is none.
ElaboratedType(ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, QualType NamedType, QualType CanonType, TagDecl *OwnedTagDecl) : TypeWithKeyword(Keyword, Elaborated, CanonType, Any semantic dependence on the qualifier will have been incorporated into NamedType. We still need to track syntactic (instantiation / error / pack) dependence on the qualifier. NamedType->getDependence() | (NNS ? toSyntacticDependence(toTypeDependence(NNS->getDependence())) : TypeDependence::None)), NNS(NNS), NamedType(NamedType) { ElaboratedTypeBits.HasOwnedTagDecl = false; if (OwnedTagDecl) { ElaboratedTypeBits.HasOwnedTagDecl = true; getTrailingObjects<TagDecl *>() = OwnedTagDecl; } }
public: / Retrieve the qualification on this type. NestedNameSpecifier *getQualifier() const { return NNS; }
/ Retrieve the type named by the qualified-id. QualType getNamedType() const { return NamedType; }
/ Remove a single level of sugar. QualType desugar() const { return getNamedType(); }
/ Returns whether this type directly provides sugar. bool isSugared() const { return true; }
/ Return the (re)declaration of this type owned by this occurrence of this / type, or nullptr if there is none. TagDecl *getOwnedTagDecl() const { return ElaboratedTypeBits.HasOwnedTagDecl ? *getTrailingObjects<TagDecl *>() : nullptr; }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getKeyword(), NNS, NamedType, getOwnedTagDecl()); }
static void Profile(llvm::FoldingSetNodeID &ID, ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, QualType NamedType, TagDecl *OwnedTagDecl) { ID.AddInteger(Keyword); ID.AddPointer(NNS); NamedType.Profile(ID); ID.AddPointer(OwnedTagDecl); }
static bool classof(const Type *T) { return T->getTypeClass() == Elaborated; } };
/ Represents a qualified type name for which the type name is / dependent. / / DependentNameType represents a class of dependent types that involve a / possibly dependent nested-name-specifier (e.g., "T::") followed by a / name of a type. The DependentNameType may start with a "typename" (for a / typename-specifier), "class", "struct", "union", or "enum" (for a / dependent elaborated-type-specifier), or nothing (in contexts where we / know that we must be referring to a type, e.g., in a base class specifier). / Typically the nested-name-specifier is dependent, but in MSVC compatibility / mode, this type is used with non-dependent names to delay name lookup until / instantiation. class DependentNameType : public TypeWithKeyword, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
/ The nested name specifier containing the qualifier. NestedNameSpecifier *NNS;
/ The type that this typename specifier refers to. const IdentifierInfo *Name;
DependentNameType(ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name, QualType CanonType) : TypeWithKeyword(Keyword, DependentName, CanonType, TypeDependence::DependentInstantiation | toTypeDependence(NNS->getDependence())), NNS(NNS), Name(Name) {}
public: / Retrieve the qualification on this type. NestedNameSpecifier *getQualifier() const { return NNS; }
/ Retrieve the type named by the typename specifier as an identifier. / / This routine will return a non-NULL identifier pointer when the / form of the original typename was terminated by an identifier, / e.g., "typename T::type". const IdentifierInfo *getIdentifier() const { return Name; }
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getKeyword(), NNS, Name); }
static void Profile(llvm::FoldingSetNodeID &ID, ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name) { ID.AddInteger(Keyword); ID.AddPointer(NNS); ID.AddPointer(Name); }
static bool classof(const Type *T) { return T->getTypeClass() == DependentName; } };
/ Represents a template specialization type whose template cannot be / resolved, e.g. / A<T>::template B<T> class alignas(8) DependentTemplateSpecializationType : public TypeWithKeyword, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
/ The nested name specifier containing the qualifier. NestedNameSpecifier *NNS;
/ The identifier of the template. const IdentifierInfo *Name;
DependentTemplateSpecializationType(ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name, ArrayRef<TemplateArgument> Args, QualType Canon);
public: NestedNameSpecifier *getQualifier() const { return NNS; } const IdentifierInfo *getIdentifier() const { return Name; }
ArrayRef<TemplateArgument> template_arguments() const { return {reinterpret_cast<const TemplateArgument *>(this + 1), DependentTemplateSpecializationTypeBits.NumArgs}; }
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Context) { Profile(ID, Context, getKeyword(), NNS, Name, template_arguments()); }
static void Profile(llvm::FoldingSetNodeID &ID, const ASTContext &Context, ElaboratedTypeKeyword Keyword, NestedNameSpecifier *Qualifier, const IdentifierInfo *Name, ArrayRef<TemplateArgument> Args);
static bool classof(const Type *T) { return T->getTypeClass() == DependentTemplateSpecialization; } };
/ Represents a pack expansion of types. / / Pack expansions are part of C++11 variadic templates. A pack / expansion contains a pattern, which itself contains one or more / "unexpanded" parameter packs. When instantiated, a pack expansion / produces a series of types, each instantiated from the pattern of / the expansion, where the Ith instantiation of the pattern uses the / Ith arguments bound to each of the unexpanded parameter packs. The / pack expansion is considered to "expand" these unexpanded / parameter packs. / /
/// template<typename ...Types> struct tuple;
///
/// template<typename ...Types>
/// struct tuple_of_references {
///   typedef tuple<Types&...> type;
/// };
///
/ / Here, the pack expansion Types&... is represented via a / PackExpansionType whose pattern is Types&. class PackExpansionType : public Type, public llvm::FoldingSetNode { friend class ASTContext; // ASTContext creates these
/ The pattern of the pack expansion. QualType Pattern;
PackExpansionType(QualType Pattern, QualType Canon, std::optional<unsigned> NumExpansions) : Type(PackExpansion, Canon, (Pattern->getDependence() | TypeDependence::Dependent | TypeDependence::Instantiation) & ~TypeDependence::UnexpandedPack), Pattern(Pattern) { PackExpansionTypeBits.NumExpansions = NumExpansions ? *NumExpansions + 1 : 0; }
public: / Retrieve the pattern of this pack expansion, which is the / type that will be repeatedly instantiated when instantiating the / pack expansion itself. QualType getPattern() const { return Pattern; }
/ Retrieve the number of expansions that this pack expansion will / generate, if known. std::optional<unsigned> getNumExpansions() const { if (PackExpansionTypeBits.NumExpansions) return PackExpansionTypeBits.NumExpansions - 1; return std::nullopt; }
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
void Profile(llvm::FoldingSetNodeID &ID) { Profile(ID, getPattern(), getNumExpansions()); }
static void Profile(llvm::FoldingSetNodeID &ID, QualType Pattern, std::optional<unsigned> NumExpansions) { ID.AddPointer(Pattern.getAsOpaquePtr()); ID.AddBoolean(NumExpansions.has_value()); if (NumExpansions) ID.AddInteger(*NumExpansions); }
static bool classof(const Type *T) { return T->getTypeClass() == PackExpansion; } };
/ This class wraps the list of protocol qualifiers. For types that can / take ObjC protocol qualifers, they can subclass this class. template <class T> class ObjCProtocolQualifiers { protected: ObjCProtocolQualifiers() = default;
ObjCProtocolDecl * const getProtocolStorage() const { return const_cast<ObjCProtocolQualifiers>(this)->getProtocolStorage(); }
ObjCProtocolDecl **getProtocolStorage() { return static_cast<T*>(this)->getProtocolStorageImpl(); }
void setNumProtocols(unsigned N) { static_cast<T*>(this)->setNumProtocolsImpl(N); }
void initialize(ArrayRef<ObjCProtocolDecl *> protocols) { setNumProtocols(protocols.size()); assert(getNumProtocols() == protocols.size() && "bitfield overflow in protocol count"); if (!protocols.empty()) memcpy(getProtocolStorage(), protocols.data(), protocols.size() * sizeof(ObjCProtocolDecl*)); }
public: using qual_iterator = ObjCProtocolDecl * const *; using qual_range = llvm::iterator_range<qual_iterator>;
qual_range quals() const { return qual_range(qual_begin(), qual_end()); } qual_iterator qual_begin() const { return getProtocolStorage(); } qual_iterator qual_end() const { return qual_begin() + getNumProtocols(); }
bool qual_empty() const { return getNumProtocols() == 0; }
/ Return the number of qualifying protocols in this type, or 0 if / there are none. unsigned getNumProtocols() const { return static_cast<const T*>(this)->getNumProtocolsImpl(); }
/ Fetch a protocol by index. ObjCProtocolDecl *getProtocol(unsigned I) const { assert(I < getNumProtocols() && "Out-of-range protocol access"); return qual_begin()[I]; }
/ Retrieve all of the protocol qualifiers. ArrayRef<ObjCProtocolDecl *> getProtocols() const { return ArrayRef<ObjCProtocolDecl *>(qual_begin(), getNumProtocols()); } };
/ Represents a type parameter type in Objective C. It can take / a list of protocols. class ObjCTypeParamType : public Type, public ObjCProtocolQualifiers<ObjCTypeParamType>, public llvm::FoldingSetNode { friend class ASTContext; friend class ObjCProtocolQualifiers<ObjCTypeParamType>;
/ The number of protocols stored on this type. unsigned NumProtocols : 6;
ObjCTypeParamDecl *OTPDecl;
/ The protocols are stored after the ObjCTypeParamType node. In the / canonical type, the list of protocols are sorted alphabetically / and uniqued. ObjCProtocolDecl **getProtocolStorageImpl();
/ Return the number of qualifying protocols in this interface type, / or 0 if there are none. unsigned getNumProtocolsImpl() const { return NumProtocols; }
void setNumProtocolsImpl(unsigned N) { NumProtocols = N; }
ObjCTypeParamType(const ObjCTypeParamDecl *D, QualType can, ArrayRef<ObjCProtocolDecl *> protocols);
public: bool isSugared() const { return true; } QualType desugar() const { return getCanonicalTypeInternal(); }
static bool classof(const Type *T) { return T->getTypeClass() == ObjCTypeParam; }
void Profile(llvm::FoldingSetNodeID &ID); static void Profile(llvm::FoldingSetNodeID &ID, const ObjCTypeParamDecl *OTPDecl, QualType CanonicalType, ArrayRef<ObjCProtocolDecl *> protocols);
ObjCTypeParamDecl *getDecl() const { return OTPDecl; } };
/ Represents a class type in Objective C. / / Every Objective C type is a combination of a base type, a set of / type arguments (optional, for parameterized classes) and a list of / protocols. / / Given the following declarations: /
///   \@class C<T>;
///   \@protocol P;
///
/ / 'C' is an ObjCInterfaceType C. It is sugar for an ObjCObjectType / with base C and no protocols. / / 'C
' is an unspecialized ObjCObjectType with base C and protocol list [P]. / 'C<C*>' is a specialized ObjCObjectType with type arguments 'C*' and no / protocol list. / 'C<C*>
' is a specialized ObjCObjectType with base C, type arguments 'C*', / and protocol list [P]. / / 'id' is a TypedefType which is sugar for an ObjCObjectPointerType whose / pointee is an ObjCObjectType with base BuiltinType::ObjCIdType / and no protocols. / / 'id
' is an ObjCObjectPointerType whose pointee is an ObjCObjectType / with base BuiltinType::ObjCIdType and protocol list [P]. Eventually / this should get its own sugar class to better represent the source. class ObjCObjectType : public Type, public ObjCProtocolQualifiers<ObjCObjectType> { friend class ObjCProtocolQualifiers<ObjCObjectType>;
ObjCObjectType.NumTypeArgs - the number of type arguments stored after the ObjCObjectPointerType node. ObjCObjectType.NumProtocols - the number of protocols stored after the type arguments of ObjCObjectPointerType node.
These protocols are those written directly on the type. If protocol qualifiers ever become additive, the iterators will need to get kindof complicated.
In the canonical object type, these are sorted alphabetically and uniqued.
/ Either a BuiltinType or an InterfaceType or sugar for either. QualType BaseType;
/ Cached superclass type. mutable llvm::PointerIntPair<const ObjCObjectType *, 1, bool> CachedSuperClassType;
QualType *getTypeArgStorage(); const QualType *getTypeArgStorage() const { return const_cast<ObjCObjectType *>(this)->getTypeArgStorage(); }
ObjCProtocolDecl **getProtocolStorageImpl(); / Return the number of qualifying protocols in this interface type, / or 0 if there are none. unsigned getNumProtocolsImpl() const { return ObjCObjectTypeBits.NumProtocols; } void setNumProtocolsImpl(unsigned N) { ObjCObjectTypeBits.NumProtocols = N; }
protected: enum Nonce_ObjCInterface { Nonce_ObjCInterface };
ObjCObjectType(QualType Canonical, QualType Base, ArrayRef<QualType> typeArgs, ArrayRef<ObjCProtocolDecl *> protocols, bool isKindOf);
ObjCObjectType(enum Nonce_ObjCInterface) : Type(ObjCInterface, QualType(), TypeDependence::None), BaseType(QualType(this_(), 0)) { ObjCObjectTypeBits.NumProtocols = 0; ObjCObjectTypeBits.NumTypeArgs = 0; ObjCObjectTypeBits.IsKindOf = 0; }
void computeSuperClassTypeSlow() const;
public: / Gets the base type of this object type. This is always (possibly / sugar for) one of: / - the 'id' builtin type (as opposed to the 'id' type visible to the / user, which is a typedef for an ObjCObjectPointerType) / - the 'Class' builtin type (same caveat) / - an ObjCObjectType (currently always an ObjCInterfaceType) QualType getBaseType() const { return BaseType; }
bool isObjCId() const { return getBaseType()->isSpecificBuiltinType(BuiltinType::ObjCId); }
bool isObjCClass() const { return getBaseType()->isSpecificBuiltinType(BuiltinType::ObjCClass); }
bool isObjCUnqualifiedId() const { return qual_empty() && isObjCId(); } bool isObjCUnqualifiedClass() const { return qual_empty() && isObjCClass(); } bool isObjCUnqualifiedIdOrClass() const { if (!qual_empty()) return false; if (const BuiltinType *T = getBaseType()->getAs<BuiltinType>()) return T->getKind() == BuiltinType::ObjCId || T->getKind() == BuiltinType::ObjCClass; return false; } bool isObjCQualifiedId() const { return !qual_empty() && isObjCId(); } bool isObjCQualifiedClass() const { return !qual_empty() && isObjCClass(); }
/ Gets the interface declaration for this object type, if the base type / really is an interface. ObjCInterfaceDecl *getInterface() const;
/ Determine whether this object type is "specialized", meaning / that it has type arguments. bool isSpecialized() const;
/ Determine whether this object type was written with type arguments. bool isSpecializedAsWritten() const { return ObjCObjectTypeBits.NumTypeArgs > 0; }
/ Determine whether this object type is "unspecialized", meaning / that it has no type arguments. bool isUnspecialized() const { return !isSpecialized(); }
/ Determine whether this object type is "unspecialized" as / written, meaning that it has no type arguments. bool isUnspecializedAsWritten() const { return !isSpecializedAsWritten(); }
/ Retrieve the type arguments of this object type (semantically). ArrayRef<QualType> getTypeArgs() const;
/ Retrieve the type arguments of this object type as they were / written. ArrayRef<QualType> getTypeArgsAsWritten() const { return llvm::ArrayRef(getTypeArgStorage(), ObjCObjectTypeBits.NumTypeArgs); }
/ Whether this is a "__kindof" type as written. bool isKindOfTypeAsWritten() const { return ObjCObjectTypeBits.IsKindOf; }
/ Whether this ia a "__kindof" type (semantically). bool isKindOfType() const;
/ Retrieve the type of the superclass of this object type. / / This operation substitutes any type arguments into the / superclass of the current class type, potentially producing a / specialization of the superclass type. Produces a null type if / there is no superclass. QualType getSuperClassType() const { if (!CachedSuperClassType.getInt()) computeSuperClassTypeSlow();
assert(CachedSuperClassType.getInt() && "Superclass not set?"); return QualType(CachedSuperClassType.getPointer(), 0); }
/ Strip off the Objective-C "kindof" type and (with it) any / protocol qualifiers. QualType stripObjCKindOfTypeAndQuals(const ASTContext &ctx) const;
bool isSugared() const { return false; } QualType desugar() const { return QualType(this, 0); }
static bool classof(const Type *T) { return T->getTypeClass() == ObjCObject || T->getTypeClass() == ObjCInterface; } };
/ A class providing a concrete implementation / of ObjCObjectType, so as to not increase the footprint of / ObjCInterfaceType. Code outside of ASTContext and the core type / system should not reference this type. class ObjCObjectTypeImpl : public ObjCObjectType, public llvm::FoldingSetNode { friend class ASTContext;
If anyone adds fields here, ObjCObjectType::getProtocolStorage() will need to be modified.
ObjCObjectTypeImpl(QualType Canonical, QualType Base, ArrayRef<QualType> typeArgs, ArrayRef<ObjCProtocolDecl *> protocols, bool isKindOf) : ObjCObjectType(Canonical, Base, typeArgs, protocols, isKindOf) {}
public: void Profile(llvm::FoldingSetNodeID &ID); static void Profile(llvm::FoldingSetNodeID &ID, QualType Base, ArrayRef<QualType> typeArgs, ArrayRef<ObjCProtocolDecl *> protocols, bool isKindOf); };
inline QualType ObjCObjectType::getTypeArgStorage() { return reinterpret_cast<QualType *>(static_cast<ObjCObjectTypeImpl>(this)+1); }
inline ObjCProtocolDecl ObjCObjectType::getProtocolStorageImpl() { return reinterpret_cast<ObjCProtocolDecl>(getTypeArgStorage() + ObjCObjectTypeBits.NumTypeArgs); }
inline ObjCProtocolDecl ObjCTypeParamType::getProtocolStorageImpl() { return reinterpret_cast<ObjCProtocolDecl>(static_cast<ObjCTypeParamType*>(this)+1); }
/ Interfaces are the core concept in Objective-C for object oriented design. / They basically correspond to C++ classes. There are two kinds of interface / types: normal interfaces like NSString, and qualified interfaces, which / are qualified with a protocol list like NSString<NSCopyable, NSAmazing>.
ObjCInterfaceType guarantees the following properties when considered
as a subtype of its superclass, ObjCObjectType:
  - There are no protocol qualifiers.  To reinforce this, code which
    tries to invoke the protocol methods via an ObjCInterfaceType will
    fail to compile.
  - It is its own base type.  That is, if T is an ObjCInterfaceType*,
    T->getBaseType() == QualType(T, 0).
Definition at line 6276 of file Type.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
qual_iterator
qual_begin
qual_end
getNumProtocols
getProtocol
Definition at line 6302 of file Type.h.
Member Function Documentation
classof()
static bool clang::ObjCInterfaceType::classof (const Type * T) inline static
Definition at line 6294 of file Type.h.
desugar()
QualType clang::ObjCInterfaceType::desugar () const inline
Definition at line 6292 of file Type.h.
getDecl()
ObjCInterfaceDecl * ObjCInterfaceType::getDecl () const
Get the declaration of this interface.
Definition at line 829 of file Type.cpp.
References clang::Decl::getCanonicalDecl(), and clang::ObjCInterfaceDecl::getDefinition().
Referenced by clang::ASTContext::canAssignObjCInterfacesInBlockPointer(), clang::CodeGen::CGDebugInfo::finalize(), clang::ObjCInterfaceTypeLoc::getIFaceDecl(), clang::Sema::HandleExprPropertyRefExpr(), and clang::JSONNodeDumper::VisitObjCInterfaceType().
isSugared()
bool clang::ObjCInterfaceType::isSugared () const inline
Definition at line 6291 of file Type.h.
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 6277 of file Type.h.
ASTReader
friend class ASTReader friend
Definition at line 6278 of file Type.h.
serialization::AbstractTypeReader
template<class T > friend class serialization::AbstractTypeReader friend
Definition at line 6279 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/Type.cpp