clang: clang::ento::MemRegion Class Reference
clang::ento::MemRegion Class Reference abstract
MemRegion - The root abstract class for all memory regions.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Types
enum Kind
Public Member Functions
ASTContext & getContext () const
virtual void Profile (llvm::FoldingSetNodeID &ID) const =0
virtual MemRegionManager & getMemRegionManager () const =0
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
virtual bool isSubRegionOf (const MemRegion *R) const
Check if the region is a subregion of the given region.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
virtual void dumpToStream (raw_ostream &os) const
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
virtual bool isBoundable () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Protected Member Functions
MemRegion (Kind k)
virtual ~MemRegion ()
Detailed Description
MemRegion - The root abstract class for all memory regions.
Definition at line 96 of file MemRegion.h.
Member Enumeration Documentation
Kind
enum clang::ento::MemRegion::Kind
Definition at line 98 of file MemRegion.h.
Constructor & Destructor Documentation
MemRegion()
clang::ento::MemRegion::MemRegion (Kind k) inline protected
Definition at line 109 of file MemRegion.h.
~MemRegion()
MemRegion::~MemRegion () protected virtual default
Member Function Documentation
canPrintPretty()
bool MemRegion::canPrintPretty () const virtual
Returns true if this region can be printed in a user-friendly way.
Reimplemented in clang::ento::FieldRegion.
Definition at line 625 of file MemRegion.cpp.
References canPrintPrettyAsExpr().
Referenced by checkAndPrettyPrintRegion(), printPretty(), showBRDefaultDiagnostics(), showBRDiagnostics(), and showBRParamDiagnostics().
canPrintPrettyAsExpr()
bool MemRegion::canPrintPrettyAsExpr () const virtual
Returns true if this region's textual representation can be used as part of a larger expression.
Reimplemented in clang::ento::CXXBaseObjectRegion, clang::ento::CXXDerivedObjectRegion, clang::ento::FieldRegion, clang::ento::NonParamVarRegion, clang::ento::ObjCIvarRegion, and clang::ento::ParamVarRegion.
Definition at line 629 of file MemRegion.cpp.
Referenced by canPrintPretty(), clang::ento::CXXBaseObjectRegion::canPrintPrettyAsExpr(), clang::ento::CXXDerivedObjectRegion::canPrintPrettyAsExpr(), clang::ento::FieldRegion::canPrintPrettyAsExpr(), and getDescriptiveName().
castAs()
template<typename RegionTy > LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * clang::ento::MemRegion::castAs () const
Definition at line 1391 of file MemRegion.h.
References clang::cast().
dump()
LLVM_DUMP_METHOD void MemRegion::dump () const
Definition at line 465 of file MemRegion.cpp.
References dumpToStream().
dumpToStream()
void MemRegion::dumpToStream (raw_ostream & os) const virtual
Reimplemented in clang::ento::AllocaRegion, clang::ento::BlockCodeRegion, clang::ento::BlockDataRegion, clang::ento::CodeSpaceRegion, clang::ento::CompoundLiteralRegion, clang::ento::CXXBaseObjectRegion, clang::ento::CXXDerivedObjectRegion, clang::ento::CXXLifetimeExtendedObjectRegion, clang::ento::CXXTempObjectRegion, clang::ento::CXXThisRegion, clang::ento::ElementRegion, clang::ento::FieldRegion, clang::ento::FunctionCodeRegion, clang::ento::GlobalImmutableSpaceRegion, clang::ento::GlobalInternalSpaceRegion, clang::ento::GlobalSystemSpaceRegion, clang::ento::HeapSpaceRegion, clang::ento::NonParamVarRegion, clang::ento::ObjCIvarRegion, clang::ento::ObjCStringRegion, clang::ento::ParamVarRegion, clang::ento::StackArgumentsSpaceRegion, clang::ento::StackLocalsSpaceRegion, clang::ento::StaticGlobalSpaceRegion, clang::ento::StringRegion, clang::ento::SymbolicRegion, and clang::ento::UnknownSpaceRegion.
Definition at line 476 of file MemRegion.cpp.
Referenced by dump(), getString(), and clang::ento::operator<<().
getAs()
template<typename RegionTy > const RegionTy * clang::ento::MemRegion::getAs () const
Definition at line 1383 of file MemRegion.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkRegionChanges(), dereference(), clang::ento::SVal::getAsFunctionDecl(), getConstructedRegion(), getDescriptiveName(), and parameterTypeFromSVal().
getAsOffset()
RegionOffset MemRegion::getAsOffset () const
Compute the offset within the top level memory object.
Definition at line 1643 of file MemRegion.cpp.
References calculateOffset().
getBaseRegion()
const MemRegion * MemRegion::getBaseRegion () const
Definition at line 1335 of file MemRegion.cpp.
References clang::cast(), and getKind().
Referenced by clang::ento::taint::addPartialTaint(), getExistingLazyBinding(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), clang::ento::PathSensitiveBugReport::getInterestingnessKind(), clang::ento::SymbolReaper::isLiveRegion(), clang::ento::PathSensitiveBugReport::markInteresting(), clang::ento::SymbolReaper::markLazilyCopied(), clang::ento::SymbolReaper::markLive(), clang::ento::PathSensitiveBugReport::markNotInteresting(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::processPointerEscapedOnBind(), clang::ento::ScanReachableSymbols::scan(), and sourceRange().
getContext()
ASTContext & clang::ento::MemRegion::getContext () const inline
Definition at line 1615 of file MemRegion.h.
References clang::ento::MemRegionManager::getContext(), and getMemRegionManager().
Referenced by calculateOffset(), clang::ento::AllocaRegion::dumpToStream(), clang::ento::CompoundLiteralRegion::dumpToStream(), clang::ento::CXXLifetimeExtendedObjectRegion::dumpToStream(), clang::ento::CXXTempObjectRegion::dumpToStream(), clang::ento::ObjCStringRegion::dumpToStream(), clang::ento::StringRegion::dumpToStream(), clang::ento::ElementRegion::getAsArrayOffset(), clang::ento::MemRegionManager::getElementRegionWithSuper(), clang::ento::FunctionCodeRegion::getLocationType(), and clang::ento::TypedValueRegion::getLocationType().
getDescriptiveName()
std::string MemRegion::getDescriptiveName (bool UseQuotes = true) const
Get descriptive name for memory region.
The name is obtained from the variable/field declaration retrieved from the memory region. Regions that point to an element of an array are returned as: "arr[0]". Regions that point to a struct are returned as: "st.var".
Parameters
UseQuotes Set if the name should be quoted.
Returns
variable name for memory region
Definition at line 707 of file MemRegion.cpp.
References canPrintPrettyAsExpr(), getAs(), clang::ento::SVal::getAs(), getDescriptiveName(), clang::ento::ElementRegion::getIndex(), clang::ento::SubRegion::getSuperRegion(), and printPrettyAsExpr().
Referenced by getDescriptiveName(), clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking(), clang::ento::mpi::MPIBugReporter::reportMissingWait(), and clang::ento::mpi::MPIBugReporter::reportUnmatchedWait().
getKind()
Kind clang::ento::MemRegion::getKind () const inline
Definition at line 172 of file MemRegion.h.
Referenced by calculateOffset(), clang::ento::StoreManager::castRegion(), clang::ento::AllocaRegion::classof(), clang::ento::BlockCodeRegion::classof(), clang::ento::BlockDataRegion::classof(), clang::ento::CodeSpaceRegion::classof(), clang::ento::CodeTextRegion::classof(), clang::ento::CompoundLiteralRegion::classof(), clang::ento::CXXBaseObjectRegion::classof(), clang::ento::CXXDerivedObjectRegion::classof(), clang::ento::CXXLifetimeExtendedObjectRegion::classof(), clang::ento::CXXTempObjectRegion::classof(), clang::ento::CXXThisRegion::classof(), clang::ento::DeclRegion::classof(), clang::ento::ElementRegion::classof(), clang::ento::FieldRegion::classof(), clang::ento::FunctionCodeRegion::classof(), clang::ento::GlobalImmutableSpaceRegion::classof(), clang::ento::GlobalInternalSpaceRegion::classof(), clang::ento::GlobalsSpaceRegion::classof(), clang::ento::GlobalSystemSpaceRegion::classof(), clang::ento::HeapSpaceRegion::classof(), clang::ento::MemSpaceRegion::classof(), clang::ento::NonParamVarRegion::classof(), clang::ento::NonStaticGlobalSpaceRegion::classof(), clang::ento::ObjCIvarRegion::classof(), clang::ento::ObjCStringRegion::classof(), clang::ento::ParamVarRegion::classof(), clang::ento::StackArgumentsSpaceRegion::classof(), clang::ento::StackLocalsSpaceRegion::classof(), clang::ento::StackSpaceRegion::classof(), clang::ento::StaticGlobalSpaceRegion::classof(), clang::ento::StringRegion::classof(), clang::ento::SubRegion::classof(), clang::ento::SymbolicRegion::classof(), clang::ento::TypedRegion::classof(), clang::ento::TypedValueRegion::classof(), clang::ento::UnknownSpaceRegion::classof(), clang::ento::VarRegion::classof(), getBaseRegion(), clang::ento::MemSpaceRegion::Profile(), clang::ento::StackSpaceRegion::Profile(), clang::ento::StaticGlobalSpaceRegion::Profile(), StripCasts(), and clang::ento::MemRegionVisitor< ImplClass, RetTy >::Visit().
getMemorySpace()
const MemSpaceRegion * MemRegion::getMemorySpace () const
Definition at line 1309 of file MemRegion.cpp.
References clang::cast().
Referenced by GetAllocationSite(), clang::ento::CXXLifetimeExtendedObjectRegion::getStackFrame(), clang::ento::CXXTempObjectRegion::getStackFrame(), clang::ento::VarRegion::getStackFrame(), hasStackNonParametersStorage(), hasStackParametersStorage(), hasStackStorage(), isInitializationOfVar(), clang::ento::ExprEngine::processPointerEscapedOnBind(), and clang::ento::SValExplainer::VisitSymbolicRegion().
getMemRegionManager()
virtual MemRegionManager & clang::ento::MemRegion::getMemRegionManager () const pure virtual
Implemented in clang::ento::MemSpaceRegion, and clang::ento::SubRegion.
Referenced by getContext(), and clang::ento::SubRegion::getMemRegionManager().
getMostDerivedObjectRegion()
const MemRegion * MemRegion::getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
Definition at line 1355 of file MemRegion.cpp.
getString()
std::string MemRegion::getString () const
Get a string representation of a region for debug use.
Definition at line 469 of file MemRegion.cpp.
References dumpToStream(), and s.
Referenced by clang::ento::SValExplainer::VisitStringRegion().
getSymbolicBase()
const SymbolicRegion * MemRegion::getSymbolicBase () const
If this is a symbolic region, returns the region.
Otherwise, goes up the base chain looking for the first symbolic base region. It might return null.
Definition at line 1393 of file MemRegion.cpp.
hasStackNonParametersStorage()
bool MemRegion::hasStackNonParametersStorage () const
Definition at line 1325 of file MemRegion.cpp.
References getMemorySpace(), and clang::isa().
hasStackParametersStorage()
bool MemRegion::hasStackParametersStorage () const
Definition at line 1329 of file MemRegion.cpp.
References getMemorySpace(), and clang::isa().
hasStackStorage()
bool MemRegion::hasStackStorage () const
Definition at line 1321 of file MemRegion.cpp.
References getMemorySpace(), and clang::isa().
Referenced by shouldEscapeRegion().
isBoundable()
virtual bool clang::ento::MemRegion::isBoundable () const inline virtual
Reimplemented in clang::ento::AllocaRegion, clang::ento::CodeTextRegion, clang::ento::CompoundLiteralRegion, clang::ento::MemSpaceRegion, clang::ento::ObjCStringRegion, clang::ento::StringRegion, clang::ento::SymbolicRegion, and clang::ento::TypedRegion.
Definition at line 178 of file MemRegion.h.
Referenced by clang::ento::StoreManager::castRegion(), clang::ento::ProgramState::getSValAsScalarOrLoc(), and isObjCPointer().
isSubRegionOf()
bool MemRegion::isSubRegionOf (const MemRegion * R) const virtual
Check if the region is a subregion of the given region.
Each region is a subregion of itself.
Reimplemented in clang::ento::SubRegion.
Definition at line 1362 of file MemRegion.cpp.
Referenced by isAnyBaseRegionReported(), and clang::ento::UndefOrNullArgVisitor::VisitNode().
printPretty()
void MemRegion::printPretty (raw_ostream & os) const virtual
Print the region for use in diagnostics.
Reimplemented in clang::ento::FieldRegion.
Definition at line 633 of file MemRegion.cpp.
References canPrintPretty(), and printPrettyAsExpr().
Referenced by checkAndPrettyPrintRegion(), showBRDefaultDiagnostics(), showBRDiagnostics(), and showBRParamDiagnostics().
printPrettyAsExpr()
void MemRegion::printPrettyAsExpr (raw_ostream & os) const virtual
Print the region as expression.
When this region represents a subexpression, the method is for printing an expression containing it.
Reimplemented in clang::ento::CXXBaseObjectRegion, clang::ento::CXXDerivedObjectRegion, clang::ento::FieldRegion, clang::ento::NonParamVarRegion, clang::ento::ObjCIvarRegion, and clang::ento::ParamVarRegion.
Definition at line 640 of file MemRegion.cpp.
Referenced by getDescriptiveName(), printPretty(), clang::ento::CXXBaseObjectRegion::printPrettyAsExpr(), clang::ento::CXXDerivedObjectRegion::printPrettyAsExpr(), and clang::ento::FieldRegion::printPrettyAsExpr().
Profile()
virtual void clang::ento::MemRegion::Profile (llvm::FoldingSetNodeID & ID) const pure virtual
Implemented in clang::ento::AllocaRegion, clang::ento::BlockCodeRegion, clang::ento::BlockDataRegion, clang::ento::CompoundLiteralRegion, clang::ento::CXXBaseObjectRegion, clang::ento::CXXDerivedObjectRegion, clang::ento::CXXLifetimeExtendedObjectRegion, clang::ento::CXXTempObjectRegion, clang::ento::CXXThisRegion, clang::ento::ElementRegion, clang::ento::FieldRegion, clang::ento::FunctionCodeRegion, clang::ento::MemSpaceRegion, clang::ento::NonParamVarRegion, clang::ento::ObjCIvarRegion, clang::ento::ObjCStringRegion, clang::ento::ParamVarRegion, clang::ento::StackSpaceRegion, clang::ento::StaticGlobalSpaceRegion, clang::ento::StringRegion, and clang::ento::SymbolicRegion.
sourceRange()
SourceRange MemRegion::sourceRange () const
Retrieve source range from memory region.
The range retrieval is based on the decl obtained from the memory region. For a VarRegion the range of the base region is returned. For a FieldRegion the range of the field is returned. If no declaration is found, an empty source range is returned. The client is responsible for checking if the returned range is valid.
Returns
source range for declaration retrieved from memory region
Definition at line 746 of file MemRegion.cpp.
References getBaseRegion().
Referenced by clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking(), clang::ento::mpi::MPIBugReporter::reportMissingWait(), and clang::ento::mpi::MPIBugReporter::reportUnmatchedWait().
StripCasts()
const MemRegion * MemRegion::StripCasts (bool StripBaseAndDerivedCasts = true) const
Definition at line 1370 of file MemRegion.cpp.
References clang::cast(), and getKind().
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::StoreManager::castRegion(), clang::ento::retaincountchecker::RetainCountChecker::checkRegionChanges(), clang::ento::StoreManager::evalBaseToDerived(), clang::ento::StoreManager::getLValueElement(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ento::loc::MemRegionVal::stripCasts(), and clang::ento::UndefOrNullArgVisitor::VisitNode().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp