clang: clang::QualType Class Reference
clang::QualType Class Reference
A (possibly-)qualified type.
#include "clang/AST/Type.h"
Classes
class StreamedQualTypeHelper
Public Types
enum PrimitiveDefaultInitializeKind { PDIK_Trivial , PDIK_ARCStrong , PDIK_ARCWeak , PDIK_Struct }
enum PrimitiveCopyKind {
PCK_Trivial , PCK_VolatileTrivial , PCK_ARCStrong , PCK_ARCWeak ,
PCK_Struct
}
enum DestructionKind {
DK_none , DK_cxx_destructor , DK_objc_strong_lifetime , DK_objc_weak_lifetime ,
DK_nontrivial_c_struct
}
Public Member Functions
QualType ()=default
QualType (const Type *Ptr, unsigned Quals)
QualType (const ExtQuals *Ptr, unsigned Quals)
unsigned getLocalFastQualifiers () const
void setLocalFastQualifiers (unsigned Quals)
bool UseExcessPrecision (const ASTContext &Ctx)
const Type * getTypePtr () const
Retrieves a pointer to the underlying (unqualified) type.
const Type * getTypePtrOrNull () const
const IdentifierInfo * getBaseTypeIdentifier () const
Retrieves a pointer to the name of the base type.
SplitQualType split () const
Divides a QualType into its unqualified type and a set of local qualifiers.
void * getAsOpaquePtr () const
const Type & operator* () const
const Type * operator-> () const
bool isCanonical () const
bool isCanonicalAsParam () const
bool isNull () const
Return true if this QualType doesn't point to a type yet.
bool isReferenceable () const
bool isLocalConstQualified () const
Determine whether this particular QualType instance has the "const" qualifier set, without looking through typedefs that may have added "const" at a different level.
bool isConstQualified () const
Determine whether this type is const-qualified.
bool isLocalRestrictQualified () const
Determine whether this particular QualType instance has the "restrict" qualifier set, without looking through typedefs that may have added "restrict" at a different level.
bool isRestrictQualified () const
Determine whether this type is restrict-qualified.
bool isLocalVolatileQualified () const
Determine whether this particular QualType instance has the "volatile" qualifier set, without looking through typedefs that may have added "volatile" at a different level.
bool isVolatileQualified () const
Determine whether this type is volatile-qualified.
bool hasLocalQualifiers () const
Determine whether this particular QualType instance has any qualifiers, without looking through any typedefs that might add qualifiers at a different level.
bool hasQualifiers () const
Determine whether this type has any qualifiers.
bool hasLocalNonFastQualifiers () const
Determine whether this particular QualType instance has any "non-fast" qualifiers, e.g., those that are stored in an ExtQualType instance.
Qualifiers getLocalQualifiers () const
Retrieve the set of qualifiers local to this particular QualType instance, not including any qualifiers acquired through typedefs or other sugar.
Qualifiers getQualifiers () const
Retrieve the set of qualifiers applied to this type.
unsigned getLocalCVRQualifiers () const
Retrieve the set of CVR (const-volatile-restrict) qualifiers local to this particular QualType instance, not including any qualifiers acquired through typedefs or other sugar.
unsigned getCVRQualifiers () const
Retrieve the set of CVR (const-volatile-restrict) qualifiers applied to this type.
bool isConstant (const ASTContext &Ctx) const
bool isPODType (const ASTContext &Context) const
Determine whether this is a Plain Old Data (POD) type (C++ 3.9p10).
bool isCXX98PODType (const ASTContext &Context) const
Return true if this is a POD type according to the rules of the C++98 standard, regardless of the current compilation's language.
bool isCXX11PODType (const ASTContext &Context) const
Return true if this is a POD type according to the more relaxed rules of the C++11 standard, regardless of the current compilation's language.
bool isTrivialType (const ASTContext &Context) const
Return true if this is a trivial type per (C++0x [basic.types]p9)
bool isTriviallyCopyableType (const ASTContext &Context) const
Return true if this is a trivially copyable type (C++0x [basic.types]p9)
bool isTriviallyRelocatableType (const ASTContext &Context) const
Return true if this is a trivially relocatable type.
bool isTriviallyEqualityComparableType (const ASTContext &Context) const
Return true if this is a trivially equality comparable type.
bool mayBeDynamicClass () const
Returns true if it is a class and it might be dynamic.
bool mayBeNotDynamicClass () const
Returns true if it is not a class or if the class might not be dynamic.
bool isWebAssemblyReferenceType () const
Returns true if it is a WebAssembly Reference Type.
bool isWebAssemblyExternrefType () const
Returns true if it is a WebAssembly Externref Type.
bool isWebAssemblyFuncrefType () const
Returns true if it is a WebAssembly Funcref Type.
void addConst ()
Add the const type qualifier to this QualType.
QualType withConst () const
void addVolatile ()
Add the volatile type qualifier to this QualType.
QualType withVolatile () const
void addRestrict ()
Add the restrict qualifier to this QualType.
QualType withRestrict () const
QualType withCVRQualifiers (unsigned CVR) const
void addFastQualifiers (unsigned TQs)
void removeLocalConst ()
void removeLocalVolatile ()
void removeLocalRestrict ()
void removeLocalFastQualifiers ()
void removeLocalFastQualifiers (unsigned Mask)
QualType withFastQualifiers (unsigned TQs) const
QualType withExactLocalFastQualifiers (unsigned TQs) const
QualType withoutLocalFastQualifiers () const
QualType getCanonicalType () const
QualType getLocalUnqualifiedType () const
Return this type with all of the instance-specific qualifiers removed, but without removing any qualifiers that may have been applied through typedefs.
QualType getUnqualifiedType () const
Retrieve the unqualified variant of the given type, removing as little sugar as possible.
SplitQualType getSplitUnqualifiedType () const
Retrieve the unqualified variant of the given type, removing as little sugar as possible.
bool isMoreQualifiedThan (QualType Other) const
Determine whether this type is more qualified than the other given type, requiring exact equality for non-CVR qualifiers.
bool isAtLeastAsQualifiedAs (QualType Other) const
Determine whether this type is at least as qualified as the other given type, requiring exact equality for non-CVR qualifiers.
QualType getNonReferenceType () const
If Type is a reference type (e.g., const int&), returns the type that the reference refers to ("const int").
QualType getNonLValueExprType (const ASTContext &Context) const
Determine the type of a (typically non-lvalue) expression with the specified result type.
QualType getNonPackExpansionType () const
Remove an outer pack expansion type (if any) from this type.
QualType getDesugaredType (const ASTContext &Context) const
Return the specified type with any "sugar" removed from the type.
SplitQualType getSplitDesugaredType () const
QualType getSingleStepDesugaredType (const ASTContext &Context) const
Return the specified type with one level of "sugar" removed from the type.
QualType IgnoreParens () const
Returns the specified type after dropping any outer-level parentheses.
std::string getAsString () const
std::string getAsString (const PrintingPolicy &Policy) const
void print (raw_ostream &OS, const PrintingPolicy &Policy, const Twine &PlaceHolder=Twine(), unsigned Indentation=0) const
void getAsStringInternal (std::string &Str, const PrintingPolicy &Policy) const
StreamedQualTypeHelper stream (const PrintingPolicy &Policy, const Twine &PlaceHolder=Twine(), unsigned Indentation=0) const
void dump (const char *s) const
void dump () const
void dump (llvm::raw_ostream &OS, const ASTContext &Context) const
void Profile (llvm::FoldingSetNodeID &ID) const
bool hasAddressSpace () const
Check if this type has any address space qualifier.
LangAS getAddressSpace () const
Return the address space of this type.
bool isAddressSpaceOverlapping (QualType T) const
Returns true if address space qualifiers overlap with T address space qualifiers.
Qualifiers::GC getObjCGCAttr () const
Returns gc attribute of this type.
bool isObjCGCWeak () const
true when Type is objc's weak.
bool isObjCGCStrong () const
true when Type is objc's strong.
Qualifiers::ObjCLifetime getObjCLifetime () const
Returns lifetime attribute of this type.
bool hasNonTrivialObjCLifetime () const
bool hasStrongOrWeakObjCLifetime () const
bool isNonWeakInMRRWithObjCWeak (const ASTContext &Context) const
PrimitiveDefaultInitializeKind isNonTrivialToPrimitiveDefaultInitialize () const
Functions to query basic properties of non-trivial C struct types.
PrimitiveCopyKind isNonTrivialToPrimitiveCopy () const
Check if this is a non-trivial type that would cause a C struct transitively containing this type to be non-trivial to copy and return the kind.
PrimitiveCopyKind isNonTrivialToPrimitiveDestructiveMove () const
Check if this is a non-trivial type that would cause a C struct transitively containing this type to be non-trivial to destructively move and return the kind.
DestructionKind isDestructedType () const
Returns a nonzero value if objects of this type require non-trivial work to clean up after.
bool hasNonTrivialToPrimitiveDefaultInitializeCUnion () const
Check if this is or contains a C union that is non-trivial to default-initialize, which is a union that has a member that is non-trivial to default-initialize.
bool hasNonTrivialToPrimitiveDestructCUnion () const
Check if this is or contains a C union that is non-trivial to destruct, which is a union that has a member that is non-trivial to destruct.
bool hasNonTrivialToPrimitiveCopyCUnion () const
Check if this is or contains a C union that is non-trivial to copy, which is a union that has a member that is non-trivial to copy.
bool isCForbiddenLValueType () const
Determine whether expressions of the given type are forbidden from being lvalues in C.
QualType substObjCTypeArgs (ASTContext &ctx, ArrayRef< QualType > typeArgs, ObjCSubstitutionContext context) const
Substitute type arguments for the Objective-C type parameters used in the subject type.
QualType substObjCMemberType (QualType objectType, const DeclContext *dc, ObjCSubstitutionContext context) const
Substitute type arguments from an object type for the Objective-C type parameters used in the subject type.
QualType stripObjCKindOfType (const ASTContext &ctx) const
Strip Objective-C "__kindof" types from the given type.
QualType getAtomicUnqualifiedType () const
Remove all qualifiers including _Atomic.
Static Public Member Functions
static QualType getFromOpaquePtr (const void *Ptr)
static std::string getAsString (SplitQualType split, const PrintingPolicy &Policy)
static std::string getAsString (const Type *ty, Qualifiers qs, const PrintingPolicy &Policy)
static void print (SplitQualType split, raw_ostream &OS, const PrintingPolicy &policy, const Twine &PlaceHolder, unsigned Indentation=0)
static void print (const Type *ty, Qualifiers qs, raw_ostream &OS, const PrintingPolicy &policy, const Twine &PlaceHolder, unsigned Indentation=0)
static void getAsStringInternal (SplitQualType split, std::string &out, const PrintingPolicy &policy)
static void getAsStringInternal (const Type *ty, Qualifiers qs, std::string &out, const PrintingPolicy &policy)
Friends
class QualifierCollector
bool operator== (const QualType &LHS, const QualType &RHS)
Indicate whether the specified types and qualifiers are identical.
bool operator!= (const QualType &LHS, const QualType &RHS)
bool operator< (const QualType &LHS, const QualType &RHS)
Detailed Description
A (possibly-)qualified type.
For efficiency, we don't store CV-qualified types as nodes on their own: instead each reference to a type stores the qualifiers. This greatly reduces the number of nodes we need to allocate for types (for example we only need one for 'int', 'const int', 'volatile int', 'const volatile int', etc).
As an added efficiency bonus, instead of making this a pair, we just store the two bits we care about in the low bits of the pointer. To handle the packing/unpacking, we make QualType be a simple wrapper class that acts like a smart pointer. A third bit indicates whether there are extended qualifiers present, in which case the pointer points to a special structure.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 736 of file Type.h.
Member Enumeration Documentation
DestructionKind
enum clang::QualType::DestructionKind
Enumerator
DK_none
DK_cxx_destructor
DK_objc_strong_lifetime
DK_objc_weak_lifetime
DK_nontrivial_c_struct
Definition at line 1287 of file Type.h.
PrimitiveCopyKind
enum clang::QualType::PrimitiveCopyKind
Enumerator
PCK_Trivial
The type does not fall into any of the following categories.
Note that this case is zero-valued so that values of this enum can be used as a boolean condition for non-triviality.
PCK_VolatileTrivial
The type would be trivial except that it is volatile-qualified.
Types that fall into one of the other non-trivial cases may additionally be volatile-qualified.
PCK_ARCStrong
The type is an Objective-C retainable pointer type that is qualified with the ARC __strong qualifier.
PCK_ARCWeak
The type is an Objective-C retainable pointer type that is qualified with the ARC __weak qualifier.
PCK_Struct
The type is a struct containing a field whose type is neither PCK_Trivial nor PCK_VolatileTrivial.
Note that a C++ struct type does not necessarily match this; C++ copying semantics are too complex to express here, in part because they depend on the exact constructor or assignment operator that is chosen by overload resolution to do the copy.
Definition at line 1246 of file Type.h.
PrimitiveDefaultInitializeKind
enum clang::QualType::PrimitiveDefaultInitializeKind
Enumerator
PDIK_Trivial
The type does not fall into any of the following categories.
Note that this case is zero-valued so that values of this enum can be used as a boolean condition for non-triviality.
PDIK_ARCStrong
The type is an Objective-C retainable pointer type that is qualified with the ARC __strong qualifier.
PDIK_ARCWeak
The type is an Objective-C retainable pointer type that is qualified with the ARC __weak qualifier.
PDIK_Struct
The type is a struct containing a field whose type is not PCK_Trivial.
Definition at line 1220 of file Type.h.
Constructor & Destructor Documentation
QualType() [1/3]
clang::QualType::QualType () default
Referenced by getLocalUnqualifiedType(), and getUnqualifiedType().
QualType() [2/3]
clang::QualType::QualType (const Type * Ptr, unsigned Quals) inline
Definition at line 760 of file Type.h.
QualType() [3/3]
clang::QualType::QualType (const ExtQuals * Ptr, unsigned Quals) inline
Definition at line 761 of file Type.h.
Member Function Documentation
addConst()
void clang::QualType::addConst () inline
Add the const type qualifier to this QualType.
Definition at line 924 of file Type.h.
References addFastQualifiers(), and clang::Qualifiers::Const.
Referenced by clang::Sema::ActOnCXXUuidof(), adjustCVQualifiersForCXXThisWithinLambda(), alignReferenceTypes(), captureInCapturedRegion(), captureInLambda(), clang::Sema::CheckExplicitlyDefaultedComparison(), checkTrivialSubobjectCall(), findOMPAllocatorHandleT(), getSubobjectType(), isVariableAlreadyCapturedInScopeInfo(), clang::Sema::LookupSpecialMember(), and clang::Sema::tryCaptureVariable().
addFastQualifiers()
void clang::QualType::addFastQualifiers (unsigned TQs) inline
Definition at line 951 of file Type.h.
References clang::Qualifiers::FastMask.
Referenced by addConst(), addRestrict(), addVolatile(), and withFastQualifiers().
addRestrict()
void clang::QualType::addRestrict () inline
Add the restrict qualifier to this QualType.
Definition at line 940 of file Type.h.
References addFastQualifiers(), and clang::Qualifiers::Restrict.
Referenced by emitReduceInitFunction().
addVolatile()
void clang::QualType::addVolatile () inline
Add the volatile type qualifier to this QualType.
Definition at line 932 of file Type.h.
References addFastQualifiers(), and clang::Qualifiers::Volatile.
Referenced by getSubobjectType(), and clang::Sema::LookupSpecialMember().
dump() [1/3]
LLVM_DUMP_METHOD void QualType::dump () const
Definition at line 184 of file ASTDumper.cpp.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by dump().
dump() [2/3]
void QualType::dump (const char * s) const
Definition at line 178 of file ASTDumper.cpp.
References dump().
dump() [3/3]
LLVM_DUMP_METHOD void QualType::dump (llvm::raw_ostream & OS, const ASTContext & Context) const
Definition at line 189 of file ASTDumper.cpp.
References clang::ASTContext::getDiagnostics(), clang::DiagnosticsEngine::getShowColors(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
getAddressSpace()
LangAS clang::QualType::getAddressSpace () const inline
Return the address space of this type.
Definition at line 6809 of file Type.h.
References clang::Qualifiers::getAddressSpace(), and getQualifiers().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::AddInitializerToDecl(), AdjustAddressSpaceForBuiltinOperandType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::CheckAllocatedType(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), clang::CodeGen::CodeGenTypes::ConvertType(), DeduceTemplateArgumentsByTypeMatch(), diagnoseOpenCLTypes(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalVar(), clang::CodeGen::CodeGenModule::GetAddrOfMSGuidDecl(), clang::CodeGen::CodeGenModule::GetAddrOfTemplateParamObject(), clang::CodeGen::CodeGenModule::GetAddrOfUnnamedGlobalConstantDecl(), clang::ASTContext::getAddrSpaceQualType(), clang::CodeGen::CodeGenModule::GetGlobalVarAddressSpace(), clang::CodeGen::TargetCodeGenInfo::getGlobalVarAddressSpace(), getLambdaType(), getOpenCLKernelParameterType(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::ASTContext::getTargetNullPointerValue(), IsAddressSpaceConversion(), clang::Expr::isNullPointerConstant(), isValidSwiftContextType(), isValidSwiftIndirectResultType(), isWebAssemblyFuncrefType(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PerformQualificationConversion(), clang::Sema::PrepareScalarCast(), clang::ASTContext::removePtrSizeAddrSpace(), clang::CodeGen::ConstantEmitter::tryEmitForInitializer(), and TryReinterpretCast().
getAsOpaquePtr()
void * clang::QualType::getAsOpaquePtr () const inline
Definition at line 783 of file Type.h.
Referenced by clang::Sema::ActOnTemplateTypeArgument(), clang::CodeGen::CGDebugInfo::completeClass(), clang::CodeGen::CGDebugInfo::completeType(), clang::CodeGen::CGDebugInfo::completeUnusedClass(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), clang::CodeGen::CGDebugInfo::finalize(), llvm::DenseMapInfo< clang::QualType >::getHashValue(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::Sema::LookupQualifiedName(), clang::QualTypeOrdering::operator()(), clang::AdjustedType::Profile(), clang::BlockPointerType::Profile(), clang::ConstantArrayType::Profile(), clang::ConstantMatrixType::Profile(), clang::DependentAddressSpaceType::Profile(), clang::DependentSizedArrayType::Profile(), clang::DependentSizedExtVectorType::Profile(), clang::DependentSizedMatrixType::Profile(), clang::DependentVectorType::Profile(), clang::FunctionNoProtoType::Profile(), clang::IncompleteArrayType::Profile(), clang::MemberPointerType::Profile(), clang::PointerType::Profile(), Profile(), clang::ReferenceType::Profile(), clang::VectorType::Profile(), and clang::TemplateArgument::TemplateArgument().
getAsString() [1/4]
std::string QualType::getAsString () const
Definition at line 2391 of file TypePrinter.cpp.
References clang::getAsString().
Referenced by clang::TextNodeDumper::dumpBareType(), getAsString(), printIndicesOfElementsToConstructJson(), printPendingInitLoopJson(), and clang::TextNodeDumper::VisitFunctionDecl().
getAsString() [2/4]
std::string QualType::getAsString (const PrintingPolicy & Policy) const
Definition at line 2395 of file TypePrinter.cpp.
getAsString() [3/4]
std::string QualType::getAsString (const Type * ty, Qualifiers qs, const PrintingPolicy & Policy) static
Definition at line 2401 of file TypePrinter.cpp.
getAsString() [4/4]
static std::string clang::QualType::getAsString (SplitQualType split, const PrintingPolicy & Policy) inline static
Definition at line 1100 of file Type.h.
References getAsString(), clang::SplitQualType::Quals, split(), and clang::SplitQualType::Ty.
Referenced by clang::data_collection::addDataToConsumer(), addFixitForObjCARCConversion(), clang::CodeGen::CGHLSLRuntime::annotateHLSLResource(), checkTypeParamListConsistency(), ConvertTypeToDiagnosticString(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::Sema::diagnoseUnavailableAlignedAllocation(), fixVarDeclWithSpan(), clang::Sema::getAmbiguousPathsDisplayString(), clang::GetFullTypeName(), clang::TypeName::getFullyQualifiedName(), clang::diff::getInitializerValue(), getNoteTag(), getPrettyTypeName(), clang::analyze_format_string::ArgType::getRepresentativeTypeName(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), isISLObjectRef(), isNullPointerValueTemplateArgument(), isOpenCLSizeDependentType(), NoteBuiltinOperatorCandidate(), OpenCLConvertScalarsToVectors(), rewriteToNSMacroDecl(), rewriteToObjCProperty(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinNDRangeAndBlock(), TryStaticDowncast(), and clang::CXXRecordDecl::viewInheritance().
getAsStringInternal() [1/3]
void QualType::getAsStringInternal (const Type * ty, Qualifiers qs, std::string & out, const PrintingPolicy & policy) static
Definition at line 2429 of file TypePrinter.cpp.
getAsStringInternal() [2/3]
static void clang::QualType::getAsStringInternal (SplitQualType split, std::string & out, const PrintingPolicy & policy) inline static
Definition at line 1128 of file Type.h.
References getAsStringInternal(), clang::SplitQualType::Quals, split(), and clang::SplitQualType::Ty.
getAsStringInternal() [3/3]
void QualType::getAsStringInternal (std::string & Str, const PrintingPolicy & Policy) const
Definition at line 2423 of file TypePrinter.cpp.
References splitAccordingToPolicy().
Referenced by clang::Sema::CheckVirtualDtorCall(), clang::PredefinedExpr::ComputeName(), diagnoseNoViableConversion(), formatBlockPlaceholder(), and getAsStringInternal().
getAtomicUnqualifiedType()
QualType QualType::getAtomicUnqualifiedType () const
Remove all qualifiers including _Atomic.
Definition at line 1547 of file Type.cpp.
References getTypePtr(), and getUnqualifiedType().
Referenced by clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckSingleAssignmentConstraints(), clang::TypeOfExprType::desugar(), Evaluate(), and EvaluateInPlace().
getBaseTypeIdentifier()
const IdentifierInfo * QualType::getBaseTypeIdentifier () const
Retrieves a pointer to the name of the base type.
Definition at line 75 of file Type.cpp.
References clang::Type::castAs(), clang::Type::castAsArrayTypeUnsafe(), getBaseTypeIdentifier(), clang::NamedDecl::getIdentifier(), clang::Type::getPointeeType(), clang::Type::getTypeClass(), getTypePtr(), clang::Type::isArrayType(), clang::Type::isEnumeralType(), clang::Type::isPointerType(), clang::Type::isRecordType(), and clang::Type::isReferenceType().
Referenced by appendType(), getBaseTypeIdentifier(), getNestedNameSpecifierIdentifiers(), and hasSimilarParameters().
getCanonicalType()
QualType clang::QualType::getCanonicalType () const inline
Definition at line 6736 of file Type.h.
References getLocalFastQualifiers(), and withFastQualifiers().
Referenced by clang::Sema::ActOnCXXTryBlock(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPDeclareMapperDirective(), adjustReturnValue(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), appendType(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), clang::Sema::BuildExprRequirement(), clang::Sema::BuildReturnStmt(), buildUserDefinedMapperRef(), checkMapConflicts(), checkMappableExpressionList(), checkNoThrow(), checkOpenCLBlockArgs(), checkOpenCLEnqueueVariadicArgs(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::checkTypeSupport(), ConvertTypeToDiagnosticString(), clang::dataflow::copyRecord(), create_call_once(), clang::ConstructionContext::createFromLayers(), clang::Sema::CreateGenericSelectionExpr(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateSpecArguments(), diagnoseOpenCLTypes(), DiagnoseRecursiveConstFields(), DiagnoseRecursiveConstFields(), clang::ento::SMTConv::doTypeConversion(), dumpMicrosoftThunkAdjustment(), emitBadConversionNotes(), emitReadOnlyPlacementAttrWarning(), EvaluateBuiltinClassifyType(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getAArch64LS(), getAArch64MTV(), getAArch64PBV(), clang::ento::StoreManager::getLValueElement(), clang::Sema::getMoreSpecializedTemplate(), getNDSWDS(), getOpenCLKernelParameterType(), clang::dataflow::DataflowAnalysisContext::getOrCreateNullPointerValue(), getOSLogArgType(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::ASTContext::getUnconstrainedType(), handleComplexFloatConversion(), handleDiagnoseAsBuiltinAttr(), clang::Sema::inferGslPointerAttribute(), clang::CFGCXXRecordTypedCall::isCXXRecordTypedCall(), clang::Decl::isFunctionPointerType(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::ento::RetainSummaryManager::isKnownSmartPointer(), isLayoutCompatible(), clang::Sema::isOpenMPPrivateDecl(), isPointerToConst(), IsStringInit(), isSubstitutedType(), clang::InitListExpr::isTransparent(), isTriviallyCopyableType(), isTriviallyEqualityComparableType(), isValidSizelessVectorForConditionalCondition(), isValidVectorForConditionalCondition(), clang::Sema::LookupQualifiedName(), clang::analyze_format_string::ArgType::matchesType(), maybeRecoverWithZeroInitialization(), clang::CodeGen::CodeGenModule::MayDropFunctionReturn(), processImplicitMapsWithDefaultMappers(), clang::dataflow::recordsEqual(), REGISTER_MAP_WITH_PROGRAMSTATE(), SemaOpenCLBuiltinEnqueueKernel(), splitAccordingToPolicy(), SuggestInitializationFixit(), tryExtractInitializerFromList(), clang::Value::Value(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), clang::ASTNodeImporter::VisitDependentNameType(), and clang::ento::SValExplainer::VisitSymbolicRegion().
getCVRQualifiers()
unsigned clang::QualType::getCVRQualifiers () const inline
Retrieve the set of CVR (const-volatile-restrict) qualifiers applied to this type.
Definition at line 6730 of file Type.h.
References getLocalCVRQualifiers().
Referenced by clang::Sema::CheckPointerToMemberOperands(), checkTrivialSubobjectCall(), DeduceTemplateArgumentsByTypeMatch(), diagnoseRedundantReturnTypeQualifiers(), GeneralizeType(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::Sema::SpecialMemberIsTrivial(), TryObjectArgumentInitialization(), and unwrapCastAwayConstnessLevel().
getDesugaredType()
QualType clang::QualType::getDesugaredType (const ASTContext & Context) const inline
Return the specified type with any "sugar" removed from the type.
This takes off typedefs, typeof's etc. If the outer level of the type is already concrete, it returns it unmodified. This is similar to getting the canonical type, but it doesn't remove all typedefs. For example, it returns "T*" as "T*", (not as "int*"), because the pointer is concrete.
Qualifiers are left in place.
Definition at line 1064 of file Type.h.
References getDesugaredType().
Referenced by clang::Sema::ActOnFields(), clang::ento::TypedRegion::getDesugaredLocationType(), getDesugaredType(), clang::Sema::getMessageSendResultType(), isGRealloc(), isStandardRealloc(), and IsStructurallyEquivalent().
getFromOpaquePtr()
static QualType clang::QualType::getFromOpaquePtr (const void * Ptr) inline static
Definition at line 785 of file Type.h.
Referenced by ConvertTypeToDiagnosticString(), clang::FormatASTNodeDiagnosticArgument(), clang::DependentDiagnostic::getAccessBaseObjectType(), clang::TemplateArgument::getAsType(), clang::APValue::LValueBase::getDynamicAllocType(), clang::serialization::UnsafeQualTypeDenseMapInfo::getEmptyKey(), clang::sema::DelayedDiagnostic::getForbiddenTypeOperand(), clang::CanQual< typename >::getFromOpaquePtr(), clang::AmbiguousConversionSequence::getFromType(), clang::BadConversionSequence::getFromType(), clang::StandardConversionSequence::getFromType(), llvm::PointerLikeTypeTraits< clang::QualType >::getFromVoidPointer(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getNullPtrType(), clang::TemplateArgument::getParamTypeForDecl(), clang::ObjCMessageExpr::getSuperType(), clang::serialization::UnsafeQualTypeDenseMapInfo::getTombstoneKey(), clang::AmbiguousConversionSequence::getToType(), clang::BadConversionSequence::getToType(), clang::StandardConversionSequence::getToType(), clang::APValue::LValuePathSerializationHelper::getType(), clang::TypeLoc::getType(), clang::Value::getType(), clang::APValue::LValueBase::getTypeInfoType(), and clang::TypeLoc::getTypePtr().
getLocalCVRQualifiers()
unsigned clang::QualType::getLocalCVRQualifiers () const inline
Retrieve the set of CVR (const-volatile-restrict) qualifiers local to this particular QualType instance, not including any qualifiers acquired through typedefs or other sugar.
Definition at line 868 of file Type.h.
References getLocalFastQualifiers().
Referenced by clang::Sema::CheckOverridingFunctionReturnType(), diagnoseRedundantReturnTypeQualifiers(), getCVRQualifiers(), and TryObjectArgumentInitialization().
getLocalFastQualifiers()
unsigned clang::QualType::getLocalFastQualifiers () const inline
Definition at line 763 of file Type.h.
Referenced by getCanonicalType(), getLocalCVRQualifiers(), getLocalQualifiers(), getQualifiers(), hasLocalQualifiers(), isLocalConstQualified(), isLocalRestrictQualified(), isLocalVolatileQualified(), and split().
getLocalQualifiers()
Qualifiers clang::QualType::getLocalQualifiers () const inline
Retrieve the set of qualifiers local to this particular QualType instance, not including any qualifiers acquired through typedefs or other sugar.
Definition at line 6716 of file Type.h.
References clang::Qualifiers::addFastQualifiers(), getLocalFastQualifiers(), clang::ExtQuals::getQualifiers(), and hasLocalNonFastQualifiers().
Referenced by BuildSimilarlyQualifiedPointerType(), checkBlockPointerTypesForAssignment(), clang::TypeName::getFullyQualifiedType(), getQualifiers(), clang::ASTImporter::Import(), IsStandardConversion(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), and clang::TreeTransform< Derived >::RebuildQualifiedType().
getLocalUnqualifiedType()
QualType clang::QualType::getLocalUnqualifiedType () const inline
Return this type with all of the instance-specific qualifiers removed, but without removing any qualifiers that may have been applied through typedefs.
Definition at line 993 of file Type.h.
References getTypePtr(), and QualType().
Referenced by clang::Sema::AttachBaseSpecifiers(), BuildSimilarlyQualifiedPointerType(), clang::ento::StoreManager::castRegion(), DiagnoseNarrowingInInitList(), handleObjCExternallyRetainedAttr(), IsStandardConversion(), clang::ProgramPoint::printJson(), and TryObjectArgumentInitialization().
getNonLValueExprType()
QualType QualType::getNonLValueExprType (const ASTContext & Context) const
Determine the type of a (typically non-lvalue) expression with the specified result type.
This routine should be used for expressions for which the return type is explicitly specified (e.g., in a cast or call) and isn't necessarily an lvalue. It removes a top-level reference (since there are no expressions of reference type) and deletes top-level cvr-qualifiers from non-class types (in C++) or all types (in C).
Definition at line 3317 of file Type.cpp.
References clang::ASTContext::getLangOpts(), clang::Type::getPointeeType(), getTypePtr(), getUnqualifiedType(), and isRecordType().
Referenced by clang::Sema::ActOnOpenMPLoopInitialization(), clang::Sema::AddConversionCandidate(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckTemplateArgument(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), findOMPAllocatorHandleT(), clang::FunctionType::getCallResultType(), clang::ObjCMethodDecl::getSendResultType(), clang::ObjCMethodDecl::getSendResultType(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::Sema::PerformImplicitConversion(), TryClassUnification(), and TryRefInitWithConversionFunction().
getNonPackExpansionType()
QualType QualType::getNonPackExpansionType () const
Remove an outer pack expansion type (if any) from this type.
Used as part of converting the type of a declaration to the type of an expression that references that expression. It's meaningless for an expression to have a pack expansion type.
Definition at line 3310 of file Type.cpp.
References getTypePtr().
getNonReferenceType()
QualType clang::QualType::getNonReferenceType () const inline
If Type is a reference type (e.g., const int&), returns the type that the reference refers to ("const int").
Otherwise, returns the type itself. This routine is used throughout Sema to implement C++ 5p6:
If an expression initially has the type "reference to T" (8.3.2, 8.5.3), the type is adjusted to "T" prior to any further analysis, the expression designates the object or function denoted by the reference, and the expression is an lvalue.
Definition at line 6884 of file Type.h.
References clang::Type::getPointeeType().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::AddConversionCandidate(), AddObjCKeyValueCompletions(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallToObjectOfClassType(), buildCapture(), buildCapture(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXTypeConstructExpr(), buildDeclareReductionRef(), clang::Sema::BuildMemberReferenceExpr(), buildPromiseCall(), clang::Sema::BuiltinDecay(), clang::Sema::BuiltinRemoveReference(), canCaptureVariableByCopy(), captureInBlock(), captureInLambda(), castToBase(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), checkCastFunctionType(), clang::Sema::CheckCompleteDecompositionDeclaration(), clang::Sema::CheckConditionVariable(), checkMapConflicts(), checkOpenMPIterationSpace(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), CheckTemplateArgumentPointerToMember(), CompleteNonViableCandidate(), clang::Sema::ConstantFoldAttrArgs(), create_call_once(), create_call_once_funcptr_call(), createObjCPropertyGetter(), createPrivatesRecordDecl(), DeduceNonTypeTemplateArgument(), clang::InitializationSequence::Diagnose(), diagnoseAmbiguousConversion(), clang::Sema::diagnoseARCUnbridgedCast(), DiagnoseBadConversion(), DiagnoseForRangeReferenceVariableCopies(), diagnoseNoViableConversion(), clang::Sema::DiagnosePropertyAccessorMismatch(), emitBadConversionNotes(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitPreCond(), emitStructSetterCall(), emitTaskPrivateMappingFunction(), clang::Sema::EndOpenMPDSABlock(), EvaluateBinaryTypeTrait(), FindConversionForRefInit(), clang::CFGImplicitDtor::getDestructorDecl(), clang::Sema::getNamedReturnInfo(), clang::Sema::getNamedReturnInfo(), clang::UnresolvedMemberExpr::getNamingClass(), clang::CodeGen::CodeGenModule::getOMPAllocateAlignment(), getParamType(), clang::dataflow::DataflowAnalysisContext::getStableStorageLocation(), clang::CXXTypeidExpr::getTypeOperand(), clang::CXXUuidofExpr::getTypeOperand(), getVariableCategoryFromDecl(), clang::Sema::HandleFunctionTypeMismatch(), handleTrivialCopy(), hasCopyOrMoveCtorParam(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), isAllowableExplicitConversion(), isFirstArgumentCompatibleWithType(), clang::Sema::isOpenMPCapturedByRef(), clang::Sema::isOpenMPCapturedDecl(), clang::Sema::isOpenMPPrivateDecl(), IsTypeModifiable(), isVariableAlreadyCapturedInScopeInfo(), loadToBegin(), clang::InitializationSequence::Perform(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::APValue::printPretty(), clang::Sema::ProcessPropertyDecl(), recordConversion(), and clang::Sema::tryCaptureVariable().
getObjCGCAttr()
Qualifiers::GC clang::QualType::getObjCGCAttr () const inline
Returns gc attribute of this type.
Return the gc attribute of this type.
Definition at line 6814 of file Type.h.
References clang::Qualifiers::getObjCGCAttr(), and getQualifiers().
Referenced by clang::ASTContext::getObjCGCAttrKind(), clang::ASTContext::getObjCGCQualType(), isObjCGCStrong(), and isObjCGCWeak().
getObjCLifetime()
Qualifiers::ObjCLifetime clang::QualType::getObjCLifetime () const inline
Returns lifetime attribute of this type.
Definition at line 1205 of file Type.h.
References clang::Qualifiers::getObjCLifetime(), and getQualifiers().
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnProperty(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildIvarRefExpr(), clang::Sema::BuildPseudoDestructorExpr(), captureInBlock(), captureInLambda(), checkAllAtProps(), clang::Sema::CheckAllocatedType(), checkARCPropertyImpl(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::CheckObjCARCUnavailableWeakConversion(), clang::Sema::CheckObjCConversion(), checkTrivialClassMembers(), clang::Sema::checkUnsafeAssigns(), clang::Sema::checkUnsafeExprAssigns(), considerVariable(), clang::Sema::DefaultLvalueConversion(), DiagnoseRetainableFlexibleArrayMember(), EmitObjectDelete(), findRetainCycleOwner(), clang::ASTContext::getByrefLifetime(), GetGCAttrTypeForType(), handleObjCPreciseLifetimeAttr(), clang::Sema::HandlePropertyInClassExtension(), inferARCWriteback(), isInvalidICRSource(), isNonTrivialToPrimitiveDefaultInitialize(), isNonWeakInMRRWithObjCWeak(), LookupMemberExpr(), pushTemporaryCleanup(), setImpliedPropertyAttributeForReadOnlyProperty(), shouldExtendReceiverForInnerPointerMessage(), transferARCOwnershipToDeclSpec(), and tryEmitARCCopyWeakInit().
getQualifiers()
Qualifiers clang::QualType::getQualifiers () const inline
Retrieve the set of qualifiers applied to this type.
Definition at line 6724 of file Type.h.
References clang::Qualifiers::addFastQualifiers(), getLocalFastQualifiers(), and getLocalQualifiers().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFields(), clang::Sema::actOnObjCTypeParam(), applyObjCTypeArgs(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildDeclRefExpr(), BuildImplicitBaseInitializer(), clang::Sema::BuildMemberExpr(), BuildSimilarlyQualifiedPointerType(), clang::Sema::BuiltinChangeSignedness(), clang::Sema::CheckAllocatedType(), checkComplexDecomposition(), checkConditionalObjectPointersCompatibility(), checkConditionalPointerCompatibility(), checkMemberDecomposition(), CheckOriginalCallArgDeduction(), clang::Sema::CheckPointerToMemberOperands(), checkVectorDecomposition(), clang::Sema::CreateBuiltinArraySubscriptExpr(), createPlaceholderSlot(), decomposeTypeForEH(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::DefineImplicitCopyAssignment(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseAssignmentResult(), DiagnoseUninitializedUse(), emitBadConversionNotes(), EmitDeclDestroy(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), emitInitWithReductionInitializer(), EmitOMPAggregateInit(), EmitValToTemp(), clang::Sema::FindCompositeObjCPointerType(), fixParamWithSpan(), getAddressSpace(), getCommonArrayElementType(), clang::ASTContext::getDeclAlign(), clang::TypeName::getFullyQualifiedType(), getObjCGCAttr(), getObjCLifetime(), getPointeeTypeText(), clang::ASTContext::getUnconstrainedType(), handleObjCExternallyRetainedAttr(), hasAddressSpace(), hasInconsistentOrSupersetQualifiersOf(), hasNonTrivialObjCLifetime(), hasStrongOrWeakObjCLifetime(), isAddressSpaceOverlapping(), isAtLeastAsQualifiedAs(), isMoreQualifiedThan(), isNonTrivialToPrimitiveCopy(), isNonTrivialToPrimitiveDefaultInitialize(), clang::Expr::isNullPointerConstant(), clang::Sema::isObjCPointerConversion(), clang::Sema::isObjCWritebackConversion(), isQualificationConversionStep(), IsStructurallyEquivalent(), isSubstitutedType(), isValidSwiftErrorResultType(), clang::ASTContext::mergeTypes(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::TreeTransform< Derived >::RebuildQualifiedType(), clang::Sema::RefersToMemberWithReducedAlignment(), ResolveConstructorOverload(), rewriteToObjCProperty(), StoreAnyExprIntoOneUnit(), TryDefaultInitialization(), tryMakeVariablePseudoStrong(), TryObjectArgumentInitialization(), TryReferenceInit(), TryReferenceInitializationCore(), TryRefInitWithConversionFunction(), TryReinterpretCast(), TryStaticCast(), TryUserDefinedConversion(), and TypeInfoIsInStandardLibrary().
getSingleStepDesugaredType()
QualType clang::QualType::getSingleStepDesugaredType (const ASTContext & Context) const inline
Return the specified type with one level of "sugar" removed from the type.
This routine takes off the first typedef, typeof, etc. If the outer level of the type is already concrete, it returns it unmodified.
Definition at line 1077 of file Type.h.
Referenced by computeConditionalNullability(), and isOpenCLSizeDependentType().
getSplitDesugaredType()
SplitQualType clang::QualType::getSplitDesugaredType () const inline
Definition at line 1068 of file Type.h.
References getSplitDesugaredType().
Referenced by getSplitDesugaredType().
getSplitUnqualifiedType()
SplitQualType clang::QualType::getSplitUnqualifiedType () const inline
Retrieve the unqualified variant of the given type, removing as little sugar as possible.
Like getUnqualifiedType(), but also returns the set of qualifiers that were built up.
The resulting type might still be qualified if it's sugar for an array type. To strip qualifiers even from within a sugared array type, use ASTContext::getUnqualifiedArrayType.
Definition at line 6784 of file Type.h.
References getTypePtr(), hasLocalQualifiers(), and split().
Referenced by clang::Sema::BuiltinDecay().
getTypePtr()
const Type * clang::QualType::getTypePtr () const inline
Retrieves a pointer to the underlying (unqualified) type.
This function requires that the type not be NULL. If the type might be NULL, use the (slightly less efficient) getTypePtrOrNull().
Definition at line 6684 of file Type.h.
Referenced by clang::Sema::ActOnCastExpr(), clang::Sema::ActOnFields(), clang::Sema::ActOnOpenMPDependClause(), addAssociatedClassesAndNamespaces(), clang::ASTContext::adjustObjCTypeParamBoundType(), clang::interp::ByteCodeExprGen< Emitter >::allocateLocal(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::CheckAddressOfOperand(), checkArrayExpressionDoesNotReferToUnitySize(), checkArrayExpressionDoesNotReferToWholeSize(), CheckImplicitConversion(), checkIsValidOpenCLKernelParameter(), checkNoThrow(), checkNullabilityTypeSpecifier(), clang::Sema::CheckObjCConversion(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::EnumDecl::completeDefinition(), clang::CodeGen::CodeGenTypes::ConvertRecordDeclType(), clang::ObjCTypeParamDecl::Create(), clang::TemplateTypeParmDecl::Create(), clang::interp::Program::createDescriptor(), clang::CodeGen::CodeGenModule::createOpenCLIntToSamplerConversion(), clang::Sema::DiagnoseUnusedButSetDecl(), clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), clang::TypePropertyCache< Private >::ensure(), FindVA(), clang::Sema::FixOverloadedFunctionReference(), formatBlockPlaceholder(), getAtomicUnqualifiedType(), getBaseTypeIdentifier(), clang::ASTContext::getCanonicalType(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), getCommonNonSugarTypeNode(), clang::ASTContext::getCommonSugaredType(), getCurrentInstantiationOf(), clang::TypeName::getFullyQualifiedTemplateType(), clang::TypeName::getFullyQualifiedType(), getLocalUnqualifiedType(), clang::Sema::getMessageSendResultType(), getNonLValueExprType(), getNonPackExpansionType(), clang::interp::Program::getOrCreateRecord(), clang::Type::getPointeeOrArrayElementType(), GetPrototypeLoc(), getRequiredQualification(), llvm::simplify_type< ::clang::QualType >::getSimplifiedValue(), getSplitUnqualifiedType(), getTypeAlignIfRequired(), GetTypeOfFunction(), clang::TypeLoc::getTypePtr(), getUnqualifiedType(), clang::ASTContext::getUsingType(), getUuidAttrOfType(), handleCallbackAttr(), clang::ASTNodeImporter::hasAutoReturnTypeDeclaredInside(), hasNonTrivialToPrimitiveCopyCUnion(), hasNonTrivialToPrimitiveDefaultInitializeCUnion(), hasNonTrivialToPrimitiveDestructCUnion(), clang::ASTImporter::Import(), clang::Sema::inferGslPointerAttribute(), isCanonical(), isCanonicalAsParam(), isCForbiddenLValueType(), isCXX11PODType(), isCXX98PODType(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::Sema::IsMemberPointerConversion(), isNonTrivialToPrimitiveCopy(), isNonTrivialToPrimitiveDefaultInitialize(), clang::Type::isObjCARCImplicitlyUnretainedType(), clang::Sema::IsOverload(), clang::CodeGen::isSingleElementStruct(), IsStandardConversion(), clang::ASTImporter::IsStructurallyEquivalent(), isTrivialType(), isWebAssemblyExternrefType(), isWebAssemblyFuncrefType(), lookupPromiseType(), clang::Sema::MaybeBindToTemporary(), mayBeDynamicClass(), mayBeNotDynamicClass(), maybeTailCall(), clang::ASTContext::mergeObjCGCQualifiers(), clang::Sema::MergeTypedefNameDecl(), clang::ASTContext::mergeTypes(), clang::StmtIteratorBase::NextVA(), operator*(), operator->(), clang::InitializationSequence::Perform(), printIntegral(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), TryStaticMemberPointerUpcast(), typeIsPostfix(), clang::CodeGen::CodeGenTypes::UpdateCompletedType(), UseExcessPrecision(), clang::Value::Value(), and clang::ASTDeclReader::VisitFieldDecl().
getTypePtrOrNull()
const Type * clang::QualType::getTypePtrOrNull () const inline
Definition at line 6688 of file Type.h.
References isNull().
Referenced by clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::ASTContext::getCommonSugaredType(), handleLifetimeCategoryAttr(), and clang::ASTDeclReader::Visit().
getUnqualifiedType()
QualType clang::QualType::getUnqualifiedType () const inline
Retrieve the unqualified variant of the given type, removing as little sugar as possible.
This routine looks through various kinds of sugar to find the least-desugared type that is unqualified. For example, given:
typedef int Integer;
typedef const Integer CInteger;
typedef CInteger DifferenceType;
Executing getUnqualifiedType() on the type DifferenceType will desugar until we hit the type Integer, which has no qualifiers on it.
The resulting type might still be qualified if it's sugar for an array type. To strip qualifiers even from within a sugared array type, use ASTContext::getUnqualifiedArrayType.
Note: In C, the _Atomic qualifier is special (see C2x 6.2.5p29 for details), and it is not stripped by this function. Use getAtomicUnqualifiedType() to strip qualifiers including _Atomic.
Definition at line 6777 of file Type.h.
References getTypePtr(), hasLocalQualifiers(), QualType(), and clang::SplitQualType::Ty.
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXTryBlock(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::ActOnStmtExprResult(), clang::Sema::AddConversionCandidate(), AdjustFunctionParmAndArgTypesForDeduction(), applyObjCTypeArgs(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBinOp(), clang::Sema::BuildCallToMemberFunction(), buildDeclareReductionRef(), BuildImplicitBaseInitializer(), BuildSimilarlyQualifiedPointerType(), buildUserDefinedMapperRef(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), captureInCapturedRegion(), clang::Sema::CheckAllocatedType(), clang::Sema::CheckAssignmentOperands(), checkBlockPointerTypesForAssignment(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), CheckIncrementDecrementOperand(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), clang::Sema::CheckNonTypeTemplateParameterType(), clang::Sema::checkOpenMPDeclareVariantFunction(), CheckOriginalCallArgDeduction(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), checkTrivialSubobjectCall(), clang::Sema::checkTypeSupport(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorOperands(), CompareDerivedToBaseConversions(), CompareStandardConversionSequences(), clang::dataflow::copyRecord(), decomposeTypeForEH(), clang::Sema::deduceClosureReturnType(), DeduceNonTypeTemplateArgument(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::DiagnoseAssignmentEnum(), clang::Sema::DiagnoseAssignmentResult(), DiagnoseBadFunctionCast(), DiagnoseCastOfObjCSEL(), DiagnoseFloatingImpCast(), FindConversionForRefInit(), clang::Sema::FunctionParamTypesAreEqual(), getAtomicUnqualifiedType(), getNonLValueExprType(), clang::SubstNonTypeTemplateParmExpr::getParameterType(), clang::CXXBaseSpecifier::getType(), handleDiagnoseAsBuiltinAttr(), HandleDynamicCast(), isAtLeastAsQualifiedAs(), clang::Sema::IsBlockPointerConversion(), clang::Sema::isInitListConstructor(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), isLayoutCompatible(), clang::Sema::isObjCWritebackConversion(), isOpenCLSizeDependentType(), clang::Sema::IsQualificationConversion(), clang::ento::cocoa::isRefType(), IsStandardConversion(), isValidInteropVariable(), IsVoidStarType(), clang::analyze_format_string::ArgType::matchesType(), maybeAdjustInterfaceForSubscriptingCheck(), clang::ASTContext::mergeFunctionTypes(), clang::ASTContext::mergeTypes(), OpenCLConvertScalarsToVectors(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::TemplateParamObjectDecl::printAsExpr(), clang::TreeTransform< Derived >::RebuildQualifiedType(), clang::dataflow::recordsEqual(), ResolveOverloadedFunctionForReferenceBinding(), rewriteToObjCProperty(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinNDRangeAndBlock(), clang::Sema::tryCaptureVariable(), TryLValueToRValueCast(), TryRefInitWithConversionFunction(), TryStaticDowncast(), TryUserDefinedConversion(), TryUserDefinedConversion(), TypeIsInnerPointer(), and clang::Sema::UsualArithmeticConversions().
hasAddressSpace()
bool clang::QualType::hasAddressSpace () const inline
Check if this type has any address space qualifier.
Definition at line 6804 of file Type.h.
References getQualifiers(), and clang::Qualifiers::hasAddressSpace().
Referenced by deduceOpenCLPointeeAddrSpace(), clang::InitializationSequence::Perform(), rewriteBuiltinFunctionDecl(), and TryObjectArgumentInitialization().
hasLocalNonFastQualifiers()
bool clang::QualType::hasLocalNonFastQualifiers () const inline
Determine whether this particular QualType instance has any "non-fast" qualifiers, e.g., those that are stored in an ExtQualType instance.
Definition at line 853 of file Type.h.
Referenced by getLocalQualifiers(), hasLocalQualifiers(), and split().
hasLocalQualifiers()
bool clang::QualType::hasLocalQualifiers () const inline
Determine whether this particular QualType instance has any qualifiers, without looking through any typedefs that might add qualifiers at a different level.
Definition at line 843 of file Type.h.
References getLocalFastQualifiers(), and hasLocalNonFastQualifiers().
Referenced by clang::ASTContext::getConstantArrayType(), clang::TypeName::getFullyQualifiedType(), clang::ASTContext::getIncompleteArrayType(), getSplitUnqualifiedType(), getUnqualifiedType(), clang::ASTContext::getUsingType(), clang::ASTContext::getVariableArrayType(), hasQualifiers(), and isCanonicalAsParam().
hasNonTrivialObjCLifetime()
bool clang::QualType::hasNonTrivialObjCLifetime () const inline
Definition at line 1209 of file Type.h.
References getQualifiers(), and clang::Qualifiers::hasNonTrivialObjCLifetime().
Referenced by clang::Sema::ActOnFields(), BuildImplicitMemberInitializer(), checkTrivialClassMembers(), EvaluateBinaryTypeTrait(), isCXX11PODType(), isCXX98PODType(), isTriviallyCopyableType(), and isTrivialType().
hasNonTrivialToPrimitiveCopyCUnion()
bool clang::QualType::hasNonTrivialToPrimitiveCopyCUnion () const inline
Check if this is or contains a C union that is non-trivial to copy, which is a union that has a member that is non-trivial to copy.
If this returns true, isNonTrivialToPrimitiveCopy returns PCK_Struct.
Definition at line 6830 of file Type.h.
References getAsRecordDecl(), getTypePtr(), and hasNonTrivialToPrimitiveCopyCUnion().
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnFields(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::CheckLValueToRValueConversionOperand(), clang::Sema::checkNonTrivialCUnion(), clang::Sema::checkNonTrivialCUnionInInitializer(), clang::Sema::CheckParameter(), clang::Sema::CreateBuiltinBinOp(), hasNonTrivialToPrimitiveCopyCUnion(), and markEscapingByrefs().
hasNonTrivialToPrimitiveDefaultInitializeCUnion()
bool clang::QualType::hasNonTrivialToPrimitiveDefaultInitializeCUnion () const inline
Check if this is or contains a C union that is non-trivial to default-initialize, which is a union that has a member that is non-trivial to default-initialize.
If this returns true, isNonTrivialToPrimitiveDefaultInitialize returns PDIK_Struct.
Definition at line 6818 of file Type.h.
References getAsRecordDecl(), getTypePtr(), and hasNonTrivialToPrimitiveDefaultInitializeCUnion().
Referenced by clang::Sema::ActOnFields(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::checkNonTrivialCUnion(), clang::Sema::checkNonTrivialCUnionInInitializer(), and hasNonTrivialToPrimitiveDefaultInitializeCUnion().
hasNonTrivialToPrimitiveDestructCUnion()
bool clang::QualType::hasNonTrivialToPrimitiveDestructCUnion () const inline
Check if this is or contains a C union that is non-trivial to destruct, which is a union that has a member that is non-trivial to destruct.
If this returns true, isDestructedType returns DK_nontrivial_c_struct.
Definition at line 6824 of file Type.h.
References getAsRecordDecl(), getTypePtr(), and hasNonTrivialToPrimitiveDestructCUnion().
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnFields(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::CheckLValueToRValueConversionOperand(), clang::Sema::checkNonTrivialCUnion(), clang::Sema::CheckParameter(), hasNonTrivialToPrimitiveDestructCUnion(), and markEscapingByrefs().
hasQualifiers()
bool clang::QualType::hasQualifiers () const inline
Determine whether this type has any qualifiers.
Definition at line 6772 of file Type.h.
References hasLocalQualifiers().
Referenced by clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnOpenMPDeclareReductionType(), AdjustFunctionParmAndArgTypesForDeduction(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckTemplateArgument(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateGenericSelectionExpr(), fixParamWithSpan(), GetFullTypeForDeclarator(), getPointeeTypeText(), clang::Sema::IsBlockPointerConversion(), isCForbiddenLValueType(), clang::ASTContext::mergeFunctionTypes(), and TryUserDefinedConversion().
hasStrongOrWeakObjCLifetime()
bool clang::QualType::hasStrongOrWeakObjCLifetime () const inline
Definition at line 1213 of file Type.h.
References getQualifiers(), and clang::Qualifiers::hasStrongOrWeakObjCLifetime().
IgnoreParens()
QualType clang::QualType::IgnoreParens () const inline
Returns the specified type after dropping any outer-level parentheses.
Definition at line 1083 of file Type.h.
References IgnoreParens().
Referenced by IgnoreParens().
isAddressSpaceOverlapping()
bool clang::QualType::isAddressSpaceOverlapping (QualType T) const inline
Returns true if address space qualifiers overlap with T address space qualifiers.
OpenCL C defines conversion rules for pointers to different address spaces and notion of overlapping address spaces. CL1.1 or CL1.2: address spaces overlap iff they are they same. OpenCL C v2.0 s6.5.5 adds: __generic overlaps with any address space except for __constant.
Definition at line 1184 of file Type.h.
References getQualifiers(), and clang::Qualifiers::isAddressSpaceSupersetOf().
Referenced by checkArithmeticBinOpPointerOperands(), and clang::Sema::CheckCompareOperands().
isAtLeastAsQualifiedAs()
bool clang::QualType::isAtLeastAsQualifiedAs (QualType other) const inline
Determine whether this type is at least as qualified as the other given type, requiring exact equality for non-CVR qualifiers.
Determine whether this type is at last as qualified as the Other type.
For example, "const volatile int" is at least as qualified as "const int", "volatile int", "int", and "const volatile int".
Definition at line 6865 of file Type.h.
References clang::Qualifiers::compatiblyIncludes(), getQualifiers(), getUnqualifiedType(), and clang::Qualifiers::removeUnaligned().
Referenced by checkObjCPointerTypesForAssignment(), clang::Sema::isObjCPointerConversion(), TryClassUnification(), and TryObjectArgumentInitialization().
isCanonical()
bool clang::QualType::isCanonical () const inline
Definition at line 6741 of file Type.h.
References getTypePtr(), and clang::Type::isCanonicalUnqualified().
Referenced by checkBlockPointerTypesForAssignment(), checkObjCPointerTypesForAssignment(), checkPointerTypesForAssignment(), clang::Sema::CheckTemplateIdType(), clang::ASTContext::getCommonSugaredType(), clang::ASTContext::getConstantArrayType(), clang::ASTContext::getConstantMatrixType(), clang::ASTContext::getElaboratedType(), clang::ASTContext::getExtVectorType(), clang::ASTContext::getIncompleteArrayType(), clang::ASTContext::getMacroQualifiedType(), clang::ASTContext::getObjCObjectPointerType(), clang::ASTContext::getObjCObjectType(), clang::ASTContext::getPackExpansionType(), clang::ASTContext::getParenType(), clang::ASTContext::getSubstTemplateTypeParmType(), clang::ASTContext::getVariableArrayType(), clang::ASTContext::getVectorType(), isCanonicalAsParam(), isCanonicalExceptionSpecification(), and clang::Sema::MergeFunctionDecl().
isCanonicalAsParam()
bool clang::QualType::isCanonicalAsParam () const inline
Definition at line 6745 of file Type.h.
References getTypePtr(), hasLocalQualifiers(), clang::isa(), and isCanonical().
isCForbiddenLValueType()
bool clang::QualType::isCForbiddenLValueType () const inline
Determine whether expressions of the given type are forbidden from being lvalues in C.
The expression types that are forbidden to be lvalues are:
'void', but not qualified void
function types
The exact rule here is C99 6.3.2.1: An lvalue is an expression with an object type or an incomplete type other than void.
Definition at line 6891 of file Type.h.
References getTypePtr(), and hasQualifiers().
Referenced by clang::Sema::CreateBuiltinArraySubscriptExpr().
isConstant()
bool clang::QualType::isConstant (const ASTContext & Ctx) const inline
Definition at line 876 of file Type.h.
References isConstant().
Referenced by clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), handleLValueToRValueConversion(), isConstant(), clang::CodeGen::CodeGenModule::isTypeConstant(), clang::MaterializeTemporaryExpr::isUsableInConstantExpressions(), and reportOriginalDsa().
isConstQualified()
bool clang::QualType::isConstQualified () const inline
Determine whether this type is const-qualified.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 6756 of file Type.h.
References isLocalConstQualified().
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddInitializerToDecl(), alignReferenceTypes(), clang::interp::ByteCodeExprGen< Emitter >::allocateLocal(), appendQualifier(), clang::Sema::BuildAtomicExpr(), BuildImplicitMemberInitializer(), captureInCapturedRegion(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), CheckForModifiableLvalue(), clang::Sema::CheckLiteralOperatorDeclaration(), CheckTemporary(), decomposeTypeForEH(), DiagnoseForRangeVariableCopies(), diagnoseOpenCLTypes(), DiagnoseRecursiveConstFields(), clang::Sema::DiagnoseSwiftName(), emitReadOnlyPlacementAttrWarning(), clang::ento::ExprEngine::evalCall(), evaluateLValueAsAllocSize(), findSubobject(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::CodeGen::CodeGenModule::GetGlobalVarAddressSpace(), clang::interp::Program::getOrCreateRecord(), getSubobjectType(), clang::ento::MemRegionManager::getVarRegion(), clang::consumed::ConsumedStmtVisitor::handleCall(), clang::Sema::handlerCanCatch(), clang::Sema::IdentifyCUDATarget(), isPointerToConst(), isPointerToConst(), isPointerToConst(), isReferenceToNonConstCapture(), IsTypeModifiable(), isVoidPointerToNonConst(), MarkVarDeclODRUsed(), clang::analyze_format_string::ArgType::matchesType(), clang::Sema::MaybeAddCUDAConstantAttr(), ShouldDiagnoseSwitchCaseNotInEnum(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::tryCaptureVariable(), TryConstructorInitialization(), TryDefaultInitialization(), TryListConversion(), TryReferenceInit(), tryRemoveRetainOfSelf(), and clang::interp::ByteCodeExprGen< Emitter >::visitVarDecl().
isCXX11PODType()
bool QualType::isCXX11PODType (const ASTContext & Context) const
Return true if this is a POD type according to the more relaxed rules of the C++11 standard, regardless of the current compilation's language.
(C++0x [basic.types]p9). Note that, unlike CXXRecordDecl::isCXX11StandardLayout, this takes DRs into account.
Definition at line 2889 of file Type.cpp.
References clang::Type::getAs(), clang::Type::getBaseElementTypeUnsafe(), getTypePtr(), hasNonTrivialObjCLifetime(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), clang::Type::isScalarType(), clang::Type::isSizelessBuiltinType(), and clang::Type::isVectorType().
Referenced by isPODType().
isCXX98PODType()
bool QualType::isCXX98PODType (const ASTContext & Context) const
Return true if this is a POD type according to the rules of the C++98 standard, regardless of the current compilation's language.
Definition at line 2483 of file Type.cpp.
References clang::ASTContext::getBaseElementType(), clang::Type::getTypeClass(), getTypePtr(), hasNonTrivialObjCLifetime(), isCXX98PODType(), and isNull().
Referenced by isCXX98PODType(), isPODType(), and clang::Sema::isValidVarArgType().
isDestructedType()
DestructionKind clang::QualType::isDestructedType () const inline
Returns a nonzero value if objects of this type require non-trivial work to clean up after.
Non-zero because it's conceivable that qualifiers (objc_gc(weak)?) could make something require destruction.
Definition at line 1299 of file Type.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFields(), clang::ASTContext::BlockRequiresCopying(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::CheckCompleteVariableDeclaration(), checkDestructorsRequired(), CheckLValueConstantExpression(), checkNoThrow(), clang::Sema::checkVariadicArgument(), clang::Sema::DefaultLvalueConversion(), clang::CodeGen::CGObjCRuntime::destroyCalleeDestroyedArguments(), EmitArrayDelete(), clang::CodeGen::ReductionCodeGen::emitCleanups(), emitCXXDestructMethod(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), EmitMemberInitializer(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), isTriviallyRelocatableType(), clang::Sema::isValidVarArgType(), clang::Sema::MaybeBindToTemporary(), clang::CodeGen::ReductionCodeGen::needCleanups(), clang::VarDecl::needsDestruction(), clang::InitializationSequence::Perform(), pushCaptureCleanup(), clang::CodeGen::CGCXXABI::requiresArrayCookie(), and clang::DestructedTypeVisitor< Derived, RetTy >::visit().
isLocalConstQualified()
bool clang::QualType::isLocalConstQualified () const inline
Determine whether this particular QualType instance has the "const" qualifier set, without looking through typedefs that may have added "const" at a different level.
Definition at line 813 of file Type.h.
References clang::Qualifiers::Const, and getLocalFastQualifiers().
Referenced by isConstQualified().
isLocalRestrictQualified()
bool clang::QualType::isLocalRestrictQualified () const inline
Determine whether this particular QualType instance has the "restrict" qualifier set, without looking through typedefs that may have added "restrict" at a different level.
Definition at line 823 of file Type.h.
References getLocalFastQualifiers(), and clang::Qualifiers::Restrict.
Referenced by isRestrictQualified().
isLocalVolatileQualified()
bool clang::QualType::isLocalVolatileQualified () const inline
Determine whether this particular QualType instance has the "volatile" qualifier set, without looking through typedefs that may have added "volatile" at a different level.
Definition at line 833 of file Type.h.
References getLocalFastQualifiers(), and clang::Qualifiers::Volatile.
Referenced by isVolatileQualified().
isMoreQualifiedThan()
bool clang::QualType::isMoreQualifiedThan (QualType other) const inline
Determine whether this type is more qualified than the other given type, requiring exact equality for non-CVR qualifiers.
Determine whether this type is more qualified than the Other type.
For example, "const volatile int" is more qualified than "const int", "volatile int", and "int". However, it is not more qualified than "const volatile int".
Definition at line 6855 of file Type.h.
References clang::Qualifiers::compatiblyIncludes(), and getQualifiers().
Referenced by buildDeclareReductionRef(), clang::Sema::CheckOverridingFunctionReturnType(), and CompareStandardConversionSequences().
isNonTrivialToPrimitiveCopy()
QualType::PrimitiveCopyKind QualType::isNonTrivialToPrimitiveCopy () const
Check if this is a non-trivial type that would cause a C struct transitively containing this type to be non-trivial to copy and return the kind.
Definition at line 2750 of file Type.cpp.
References clang::Qualifiers::getObjCLifetime(), getQualifiers(), getTypePtr(), clang::Qualifiers::hasVolatile(), clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, PCK_ARCStrong, PCK_ARCWeak, PCK_Struct, PCK_Trivial, and PCK_VolatileTrivial.
Referenced by clang::Sema::ActOnFields(), isNonTrivialToPrimitiveDestructiveMove(), and clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visit().
isNonTrivialToPrimitiveDefaultInitialize()
QualType::PrimitiveDefaultInitializeKind QualType::isNonTrivialToPrimitiveDefaultInitialize () const
Functions to query basic properties of non-trivial C struct types.
Check if this is a non-trivial type that would cause a C struct transitively containing this type to be non-trivial to default initialize and return the kind.
Definition at line 2734 of file Type.cpp.
References getObjCLifetime(), getQualifiers(), getTypePtr(), clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, PDIK_ARCStrong, PDIK_ARCWeak, PDIK_Struct, and PDIK_Trivial.
Referenced by clang::Sema::ActOnFields(), and clang::DefaultInitializedTypeVisitor< Derived, RetTy >::visit().
isNonTrivialToPrimitiveDestructiveMove()
QualType::PrimitiveCopyKind QualType::isNonTrivialToPrimitiveDestructiveMove () const
Check if this is a non-trivial type that would cause a C struct transitively containing this type to be non-trivial to destructively move and return the kind.
Destructive move in this context is a C++-style move in which the source object is placed in a valid but unspecified state after it is moved, as opposed to a truly destructive move in which the source object is placed in an uninitialized state.
Definition at line 2768 of file Type.cpp.
References isNonTrivialToPrimitiveCopy().
Referenced by clang::ASTContext::BlockRequiresCopying(), isTriviallyRelocatableType(), and clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visit().
isNonWeakInMRRWithObjCWeak()
bool QualType::isNonWeakInMRRWithObjCWeak (const ASTContext & Context) const
Definition at line 2702 of file Type.cpp.
References clang::ASTContext::getLangOpts(), getObjCLifetime(), and clang::Qualifiers::OCL_Weak.
Referenced by clang::Sema::AddInitializerToDecl(), and clang::Sema::CheckAssignmentOperands().
isNull()
bool clang::QualType::isNull () const inline
Return true if this QualType doesn't point to a type yet.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 803 of file Type.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnBuiltinOffsetOf(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnClassMessage(), clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCXXThis(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnLambdaExpressionAfterIntroducer(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnOpenMPDeclareMapperType(), clang::Sema::ActOnOpenMPDeclareReductionType(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::ActOnSuperMessage(), clang::Sema::ActOnSYCLUniqueStableNameExpr(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypeRequirement(), clang::Sema::ActOnUsingEnumDeclaration(), clang::Sema::AddFunctionCandidates(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddModeAttr(), AddObjCKeyValueCompletions(), AddOrdinaryNameResults(), addThisCompletion(), clang::Sema::adjustCCAndNoReturn(), clang::ASTContext::areCommonBaseCompatible(), assertEqualBitWidths(), clang::ento::ProgramState::assumeInBoundDual(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::Sema::BuildClassMessageImplicit(), buildCoroutineHandle(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildImplicitMemberExpr(), clang::Sema::BuildInstanceMessage(), clang::Sema::buildLambdaInitCaptureInitialization(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::BuildReturnStmt(), BuildSimilarlyQualifiedPointerType(), clang::Sema::BuildUnaryTransformType(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuiltinChangeSignedness(), clang::Sema::canDelayFunctionBody(), clang::Sema::canThrow(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), checkDeducedTemplateArguments(), clang::Sema::CheckDestructorAccess(), clang::Sema::CheckExplicitlyDefaultedComparison(), CheckIncrementDecrementOperand(), clang::Sema::checkInitMethod(), CheckKeyForObjCARCConversion(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckNonDependentConversions(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckSizelessVectorCompareOperands(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateIdType(), checkTupleLikeDecomposition(), clang::Sema::checkTypeSupport(), clang::Sema::checkUnsafeExprAssigns(), clang::Sema::CheckVariableDeclarationType(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CheckVectorLogicalOperands(), ClassifyImplicitMemberAccess(), clang::Sema::CodeCompleteObjCClassMessage(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::Sema::CodeCompleteQualifiedId(), clang::Sema::containsUnexpandedParameterPacks(), ConvertTypeToDiagnosticString(), create_call_once(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::Sema::CXXCheckConditionalOperands(), decomposeTypeForEH(), clang::Sema::DeduceAutoType(), clang::Sema::deduceClosureReturnType(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceVariableDeclarationType(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), determineEndOffset(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseBadDeduction(), DiagnoseForRangeReferenceVariableCopies(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ento::SMTConv::doIntTypeConversion(), clang::ento::SMTConv::doTypeConversion(), EmitAsmStores(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::ento::StoreManager::evalBaseToDerived(), clang::ento::ExprEngine::evalCall(), clang::ento::retaincountchecker::RetainCountChecker::evalCall(), clang::ento::ExprEngine::evalLoad(), EvaluateAsRValue(), evaluateCDTSize(), FastEvaluateAsRValue(), clang::Sema::FindCompositePointerType(), FindDesignatorMismatch(), FindImplementableMethods(), findOMPAllocatorHandleT(), findOMPAlloctraitT(), findOMPDependT(), findOMPEventHandleT(), FinishForRangeVarDecl(), clang::Sema::FinishTemplateArgumentDeduction(), fixVarDeclWithSpan(), generateDiagnosticsForCallLike(), clang::ASTContext::getAutoDeductType(), clang::ASTContext::getAutoRRefDeductType(), clang::ASTContext::getAutoType(), clang::CallExpr::getCallReturnType(), clang::ASTContext::getCommentForDecl(), clang::Sema::getCurrentThisType(), GetDeclSpecTypeForDeclarator(), clang::ASTContext::getDependentNameType(), getDependTypes(), clang::Sema::getDestructorName(), clang::Sema::getDestructorTypeForDecltype(), GetEnumUnderlyingType(), getExistingLazyBinding(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForEnum(), GetFullTypeForDeclarator(), clang::ClassTemplateDecl::getInjectedClassNameSpecialization(), getKmpAffinityType(), getLambdaType(), clang::ento::StoreManager::getLValueElement(), clang::Sema::getMostSpecialized(), clang::Sema::GetNameFromUnqualifiedId(), getNSNumberFactoryMethod(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), clang::Type::getObjCSubstitutions(), clang::ASTContext::getObjCSuperType(), clang::dataflow::DataflowAnalysisContext::getOrCreateNullPointerValue(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), getParamType(), getPreferredArgumentTypeForMessageSend(), getPrettyTypeName(), getPrivateItem(), clang::ASTContext::getPromotedIntegerType(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::ObjCObjectPointerType::getSuperClassType(), clang::ASTContext::getTemplateSpecializationType(), clang::Sema::getTrivialTemplateArgumentLoc(), clang::ASTContext::getTypedefType(), clang::Sema::GetTypeFromParser(), getTypePtrOrNull(), clang::ASTContext::getUsingType(), clang::ento::MemRegionManager::getVarRegion(), HandleAddressSpaceTypeAttribute(), clang::Sema::HandleDependentAccessCheck(), clang::Sema::HandleFunctionTypeMismatch(), handleXReturnsXRetainedAttr(), hasNonTrivialConstructorCall(), clang::ASTContext::hasUniqueObjectRepresentations(), haveSameParameterTypes(), HelperIsMethodInObjCType(), clang::ASTImporter::Import(), clang::ASTReader::InitializeContext(), clang::InitializationSequence::InitializeFrom(), instantiateOMPDeclareVariantAttr(), clang::comments::DeclInfo::involvesFunctionType(), IsAcceptableNonMemberOperatorCandidate(), isCXX98PODType(), clang::Declarator::isDeclarationOfFunction(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), isLayoutCompatible(), isOSObjectRelated(), isPointerToConst(), isPointerToObject(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), IsStructurallyEquivalent(), isSubstitutedType(), clang::Sema::isThisOutsideMemberFunctionBody(), isTrivialType(), clang::ento::DynamicTypeInfo::isValid(), isValidOSObjectOutParameter(), isValidSubjectOfOSAttribute(), clang::Sema::LazilyCreateBuiltin(), lookupCoroutineHandleType(), clang::ComparisonCategories::lookupInfoForType(), LookupMemberExpr(), lookupPromiseType(), clang::Sema::LookupQualifiedName(), lookupStdTypeTraitMember(), clang::Sema::LookupTemplateName(), maybeAdjustInterfaceForSubscriptingCheck(), mergeEnumWithInteger(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionParameterTypes(), clang::ASTContext::mergeFunctionTypes(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTransparentUnionType(), clang::ASTContext::mergeTypes(), clang::Sema::MergeVarDeclTypes(), OpenCLCheckVectorConditional(), OpenCLConvertScalarsToVectors(), clang::Sema::ParseObjCProtocolExpression(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::APValue::printPretty(), clang::ento::ExprEngine::processCallExit(), processImplicitMapsWithDefaultMappers(), clang::TypedefType::Profile(), clang::UsingType::Profile(), clang::ASTRecordReader::readTypeSourceInfo(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), recoverFromMSUnqualifiedLookup(), REGISTER_MAP_WITH_PROGRAMSTATE(), ResolveOverloadForDeduction(), rewriteToNSMacroDecl(), clang::Sema::SelectorsForTypoCorrection(), SemaBuiltinAddressof(), clang::InitializationSequence::SetFailed(), clang::ASTContext::setObjCConstantStringInterface(), clang::Expr::setType(), shouldNotPrintDirectly(), clang::Sema::SubstituteExplicitTemplateArguments(), clang::Sema::SubstType(), throwEscapes(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), clang::TreeTransform< Derived >::TransformFunctionTypeParams(), clang::TreeTransform< Derived >::TransformReferenceType(), clang::TreeTransform< Derived >::TransformTemplateArgument(), clang::TreeTransform< Derived >::TransformTemplateName(), clang::Sema::tryCaptureOpenMPLambdas(), clang::Sema::tryExprAsCall(), TryOrBuildParenListInitialization(), tryRearrange(), TryReinterpretCast(), TryToFixInvalidVariablyModifiedType(), TryToFixInvalidVariablyModifiedTypeSourceInfo(), clang::Sema::tryToRecoverWithCall(), clang::ASTContext::typesAreBlockPointerCompatible(), clang::ASTContext::typesAreCompatible(), UnwrapTypeForDebugInfo(), clang::Sema::UsualArithmeticConversions(), clang::Sema::UsualUnaryConversions(), clang::FunctionCallFilterCCC::ValidateCandidate(), clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr(), clang::ASTDeclReader::VisitDeclaratorDecl(), clang::ASTNodeImporter::VisitTypedefNameDecl(), and clang::interp::ByteCodeExprGen< Emitter >::visitVarDecl().
isObjCGCStrong()
bool clang::QualType::isObjCGCStrong () const inline
true when Type is objc's strong.
Definition at line 1200 of file Type.h.
References getObjCGCAttr(), and clang::Qualifiers::Strong.
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnPropertyImplDecl(), and GetGCAttrTypeForType().
isObjCGCWeak()
bool clang::QualType::isObjCGCWeak () const inline
true when Type is objc's weak.
Definition at line 1195 of file Type.h.
References getObjCGCAttr(), and clang::Qualifiers::Weak.
Referenced by clang::Sema::ActOnPropertyImplDecl(), and GetGCAttrTypeForType().
isPODType()
bool QualType::isPODType (const ASTContext & Context) const
Determine whether this is a Plain Old Data (POD) type (C++ 3.9p10).
Definition at line 2475 of file Type.cpp.
References clang::ASTContext::getLangOpts(), isCXX11PODType(), and isCXX98PODType().
Referenced by clang::Sema::BuildVAArgExpr(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::DiagnoseSizeOfParametersAndReturnValue(), EmitMemberInitializer(), and getOpenCLKernelParameterType().
isReferenceable()
bool clang::QualType::isReferenceable () const inline
Definition at line 6692 of file Type.h.
References clang::Type::getAs(), clang::Type::isObjectType(), clang::Type::isReferenceType(), and clang::RQ_None.
Referenced by clang::Sema::BuiltinAddPointer().
isRestrictQualified()
bool clang::QualType::isRestrictQualified () const inline
Determine whether this type is restrict-qualified.
Definition at line 6761 of file Type.h.
References isLocalRestrictQualified().
Referenced by appendQualifier(), CollectVRQualifiers(), and clang::CodeGen::CodeGenModule::GenKernelArgMetadata().
isTriviallyCopyableType()
bool QualType::isTriviallyCopyableType (const ASTContext & Context) const
Return true if this is a trivially copyable type (C++0x [basic.types]p9)
Definition at line 2585 of file Type.cpp.
References clang::Type::getAs(), clang::ASTContext::getBaseElementType(), getCanonicalType(), hasNonTrivialObjCLifetime(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), clang::Type::isScalarType(), clang::Type::isSizelessBuiltinType(), isTriviallyCopyableType(), and clang::Type::isVectorType().
Referenced by clang::Sema::BuildAtomicExpr(), checkTypeMappable(), createObjCPropertyGetter(), DiagnoseForRangeConstVariableCopies(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::Sema::isOpenMPPrivateDecl(), isTriviallyCopyableType(), and clang::CodeGen::CodeGenModule::MayDropFunctionReturn().
isTriviallyEqualityComparableType()
bool QualType::isTriviallyEqualityComparableType (const ASTContext & Context) const
Return true if this is a trivially equality comparable type.
Definition at line 2686 of file Type.cpp.
References clang::Type::getAsCXXRecordDecl(), getCanonicalType(), HasNonDeletedDefaultedEqualityComparison(), clang::ASTContext::hasUniqueObjectRepresentations(), clang::Type::isArrayType(), clang::Type::isDependentType(), clang::Type::isEnumeralType(), and clang::Type::isIncompleteType().
isTriviallyRelocatableType()
bool QualType::isTriviallyRelocatableType (const ASTContext & Context) const
Return true if this is a trivially relocatable type.
Definition at line 2625 of file Type.cpp.
References clang::Type::getAsRecordDecl(), clang::ASTContext::getBaseElementType(), isDestructedType(), clang::Type::isIncompleteType(), isNonTrivialToPrimitiveDestructiveMove(), PCK_ARCStrong, and PCK_Trivial.
isTrivialType()
bool QualType::isTrivialType (const ASTContext & Context) const
Return true if this is a trivial type per (C++0x [basic.types]p9)
Definition at line 2532 of file Type.cpp.
References clang::Type::getAs(), clang::ASTContext::getBaseElementType(), getTypePtr(), hasNonTrivialObjCLifetime(), clang::Type::isDependentType(), isNull(), clang::Type::isScalarType(), isTrivialType(), and clang::Type::isVectorType().
Referenced by isTrivialType(), and clang::cross_tu::shouldImport().
isVolatileQualified()
bool clang::QualType::isVolatileQualified () const inline
Determine whether this type is volatile-qualified.
Definition at line 6767 of file Type.h.
References isLocalVolatileQualified().
Referenced by clang::Sema::ActOnFields(), clang::Sema::AddInitializerToDecl(), appendQualifier(), clang::Sema::BuildFunctionType(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), CheckIdentityFieldAssignment(), CheckIncrementDecrementOperand(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::CheckLValueToRValueConversionOperand(), clang::Sema::CheckUnusedVolatileAssignment(), CollectVRQualifiers(), decomposeTypeForEH(), clang::InitializationSequence::Diagnose(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseUnusedExprResult(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), emitOMPAtomicCompareExpr(), findCompleteObject(), findSubobject(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), getBlockCaptureStr(), clang::Sema::getNamedReturnInfo(), getSubobjectType(), clang::Sema::handlerCanCatch(), clang::Expr::HasSideEffects(), clang::Expr::isUnusedResultAWarning(), clang::MaterializeTemporaryExpr::isUsableInConstantExpressions(), clang::AtomicExpr::isVolatile(), MaybeDecrementCount(), TryListConversion(), and TryReferenceInit().
isWebAssemblyExternrefType()
bool QualType::isWebAssemblyExternrefType () const
Returns true if it is a WebAssembly Externref Type.
Definition at line 2724 of file Type.cpp.
References getTypePtr(), and clang::Type::isWebAssemblyExternrefType().
Referenced by isWebAssemblyReferenceType().
isWebAssemblyFuncrefType()
bool QualType::isWebAssemblyFuncrefType () const
Returns true if it is a WebAssembly Funcref Type.
Definition at line 2728 of file Type.cpp.
References getAddressSpace(), getTypePtr(), clang::Type::isFunctionPointerType(), and clang::wasm_funcref.
Referenced by isWebAssemblyReferenceType().
isWebAssemblyReferenceType()
bool QualType::isWebAssemblyReferenceType () const
Returns true if it is a WebAssembly Reference Type.
Definition at line 2720 of file Type.cpp.
References isWebAssemblyExternrefType(), and isWebAssemblyFuncrefType().
Referenced by captureInLambda(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::CheckSpecifiedExceptionType(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), and clang::Sema::isValidVarArgType().
mayBeDynamicClass()
bool QualType::mayBeDynamicClass () const
Returns true if it is a class and it might be dynamic.
Definition at line 95 of file Type.cpp.
References clang::Type::getPointeeCXXRecordDecl(), getTypePtr(), and clang::CXXRecordDecl::mayBeDynamicClass().
mayBeNotDynamicClass()
bool QualType::mayBeNotDynamicClass () const
Returns true if it is not a class or if the class might not be dynamic.
Definition at line 100 of file Type.cpp.
References clang::Type::getPointeeCXXRecordDecl(), getTypePtr(), and clang::CXXRecordDecl::mayBeNonDynamicClass().
operator*()
const Type & clang::QualType::operator* () const inline
Definition at line 791 of file Type.h.
References getTypePtr().
operator->()
const Type * clang::QualType::operator-> () const inline
Definition at line 795 of file Type.h.
References getTypePtr().
print() [1/3]
void QualType::print (const Type * ty, Qualifiers qs, raw_ostream & OS, const PrintingPolicy & policy, const Twine & PlaceHolder, unsigned Indentation = 0) static
Definition at line 2414 of file TypePrinter.cpp.
print() [2/3]
void QualType::print (raw_ostream & OS, const PrintingPolicy & Policy, const Twine & PlaceHolder = Twine(), unsigned Indentation = 0) const
Definition at line 2408 of file TypePrinter.cpp.
References print(), and splitAccordingToPolicy().
Referenced by clang::DynTypedNode::print(), clang::NestedNameSpecifier::print(), print(), clang::TemplateArgument::print(), clang::TypeInfoLValue::print(), print_elem(), printArgument(), clang::TemplateParamObjectDecl::printAsExpr(), printCXXConstructorDestructorName(), clang::ProgramPoint::printJson(), and clang::TagDecl::printName().
print() [3/3]
static void clang::QualType::print (SplitQualType split, raw_ostream & OS, const PrintingPolicy & policy, const Twine & PlaceHolder, unsigned Indentation = 0) inline static
Definition at line 1114 of file Type.h.
References print(), clang::SplitQualType::Quals, split(), and clang::SplitQualType::Ty.
Profile()
void clang::QualType::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 1166 of file Type.h.
References getAsOpaquePtr().
Referenced by clang::TemplateArgument::Profile(), clang::TypedefType::Profile(), clang::UnnamedGlobalConstantDecl::Profile(), and clang::UsingType::Profile().
removeLocalConst()
void clang::QualType::removeLocalConst () inline
Definition at line 6791 of file Type.h.
References clang::Qualifiers::Const, and removeLocalFastQualifiers().
Referenced by clang::Sema::BuildAtomicExpr(), DiagnoseForRangeReferenceVariableCopies(), and findSubobject().
removeLocalFastQualifiers() [1/2]
void clang::QualType::removeLocalFastQualifiers () inline
Definition at line 961 of file Type.h.
Referenced by removeLocalConst(), removeLocalRestrict(), removeLocalVolatile(), and withoutLocalFastQualifiers().
removeLocalFastQualifiers() [2/2]
void clang::QualType::removeLocalFastQualifiers (unsigned Mask) inline
Definition at line 962 of file Type.h.
References clang::Qualifiers::FastMask.
removeLocalRestrict()
void clang::QualType::removeLocalRestrict () inline
Definition at line 6795 of file Type.h.
References removeLocalFastQualifiers(), and clang::Qualifiers::Restrict.
removeLocalVolatile()
void clang::QualType::removeLocalVolatile () inline
Definition at line 6799 of file Type.h.
References removeLocalFastQualifiers(), and clang::Qualifiers::Volatile.
Referenced by clang::Sema::BuildAtomicExpr(), and findSubobject().
setLocalFastQualifiers()
void clang::QualType::setLocalFastQualifiers (unsigned Quals) inline
Definition at line 764 of file Type.h.
split()
SplitQualType clang::QualType::split () const inline
Divides a QualType into its unqualified type and a set of local qualifiers.
Definition at line 6705 of file Type.h.
References clang::Qualifiers::addFastQualifiers(), clang::Qualifiers::fromFastMask(), clang::ExtQuals::getBaseType(), getLocalFastQualifiers(), clang::ExtQuals::getQualifiers(), and hasLocalNonFastQualifiers().
Referenced by checkARCPropertyImpl(), getAsString(), getAsStringInternal(), clang::ASTContext::getCommonSugaredType(), clang::SplitQualType::getSingleStepDesugaredType(), getSplitUnqualifiedType(), clang::operator<<(), print(), printIndicesOfElementsToConstructJson(), printPendingInitLoopJson(), splitAccordingToPolicy(), unwrapSugar(), and clang::TextNodeDumper::VisitFunctionDecl().
stream()
StreamedQualTypeHelper clang::QualType::stream (const PrintingPolicy & Policy, const Twine & PlaceHolder = Twine(), unsigned Indentation = 0) const inline
Definition at line 1156 of file Type.h.
Referenced by clang::APValue::printPretty().
stripObjCKindOfType()
QualType QualType::stripObjCKindOfType (const ASTContext & ctx) const
Strip Objective-C "__kindof" types from the given type.
Definition at line 1540 of file Type.cpp.
substObjCMemberType()
QualType QualType::substObjCMemberType (QualType objectType, const DeclContext * dc, ObjCSubstitutionContext context) const
Substitute type arguments from an object type for the Objective-C type parameters used in the subject type.
This operation combines the computation of type arguments for substitution (Type::getObjCSubstitutions) with the actual process of substitution (QualType::substObjCTypeArgs) for the convenience of callers that need to perform a single substitution in isolation.
Parameters
objectType The type of the object whose member type we're substituting into. For example, this might be the receiver of a message or the base of a property access.
dc The declaration context from which the subject type was retrieved, which indicates (for example) which type parameters should be substituted.
context The context in which the subject type was written.
Returns
the subject type after replacing all of the Objective-C type parameters with their corresponding arguments.
Definition at line 1531 of file Type.cpp.
References clang::Type::getObjCSubstitutions(), clang::DeclContext::getParentASTContext(), and substObjCTypeArgs().
Referenced by clang::ObjCMethodDecl::getSendResultType(), clang::ObjCIvarDecl::getUsageType(), and clang::ObjCPropertyDecl::getUsageType().
substObjCTypeArgs()
QualType QualType::substObjCTypeArgs (ASTContext & ctx, ArrayRef< QualType > typeArgs, ObjCSubstitutionContext context) const
Substitute type arguments for the Objective-C type parameters used in the subject type.
Substitute the given type arguments for Objective-C type parameters within the given type, recursively.
Parameters
ctx ASTContext in which the type exists.
typeArgs The type arguments that will be substituted for the Objective-C type parameters in the subject type, which are generally computed via Type::getObjCSubstitutions. If empty, the type parameters will be replaced with their bounds or id/Class, as appropriate for the context.
context The context in which the subject type was written.
Returns
the resulting type.
Definition at line 1524 of file Type.cpp.
Referenced by clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), formatBlockPlaceholder(), getReturnTypeForMethod(), clang::ObjCMethodDecl::getSendResultType(), and substObjCMemberType().
UseExcessPrecision()
bool QualType::UseExcessPrecision (const ASTContext & Ctx)
Definition at line 1489 of file Type.cpp.
References clang::Type::getAs(), clang::VectorType::getElementType(), clang::BuiltinType::getKind(), clang::ASTContext::getLangOpts(), clang::ASTContext::getTargetInfo(), getTypePtr(), clang::TargetInfo::hasBFloat16Type(), clang::TargetInfo::hasFloat16Type(), clang::TargetInfo::hasFullBFloat16Type(), clang::TargetInfo::hasLegalHalfType(), and UseExcessPrecision().
Referenced by UseExcessPrecision().
withConst()
QualType clang::QualType::withConst () const inline
Definition at line 927 of file Type.h.
References clang::Qualifiers::Const, and withFastQualifiers().
Referenced by clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnOpenMPRegionStart(), clang::Sema::ActOnSourceLocExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCDictionaryLiteral(), captureInBlock(), clang::Sema::CheckExplicitlyDefaultedComparison(), DiagnoseForRangeReferenceVariableCopies(), diagnoseListInit(), clang::ASTContext::getConstType(), clang::ASTContext::getMSGuidDecl(), clang::ObjCMethodDecl::getSelfType(), clang::ASTContext::getStringLiteralArrayType(), clang::Sema::SpecialMemberIsTrivial(), TryInitializerListConstruction(), tryMakeVariablePseudoStrong(), and clang::CanQual< typename >::withConst().
withCVRQualifiers()
QualType clang::QualType::withCVRQualifiers (unsigned CVR) const inline
Definition at line 947 of file Type.h.
References withFastQualifiers().
Referenced by checkConditionalPointerCompatibility(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), GeneralizeType(), and unwrapCastAwayConstnessLevel().
withExactLocalFastQualifiers()
QualType clang::QualType::withExactLocalFastQualifiers (unsigned TQs) const inline
Definition at line 977 of file Type.h.
References withFastQualifiers(), and withoutLocalFastQualifiers().
withFastQualifiers()
QualType clang::QualType::withFastQualifiers (unsigned TQs) const inline
Definition at line 969 of file Type.h.
References addFastQualifiers().
Referenced by clang::QualifierCollector::apply(), getCanonicalType(), clang::ASTContext::getQualifiedType(), clang::ASTContext::getRestrictType(), clang::ASTContext::getVolatileType(), withConst(), withCVRQualifiers(), withExactLocalFastQualifiers(), withRestrict(), and withVolatile().
withoutLocalFastQualifiers()
QualType clang::QualType::withoutLocalFastQualifiers () const inline
Definition at line 982 of file Type.h.
References removeLocalFastQualifiers().
Referenced by CheckTautologicalComparison(), getCoreType(), and withExactLocalFastQualifiers().
withRestrict()
QualType clang::QualType::withRestrict () const inline
Definition at line 943 of file Type.h.
References clang::Qualifiers::Restrict, and withFastQualifiers().
Referenced by clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnOpenMPRegionStart(), emitCombinerOrInitializer(), emitDestructorsFunction(), emitProxyTaskFunction(), and clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper().
withVolatile()
QualType clang::QualType::withVolatile () const inline
Definition at line 935 of file Type.h.
References clang::Qualifiers::Volatile, and withFastQualifiers().
Referenced by callSpecialFunction(), and getSpecialFunction().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const QualType & LHS, const QualType & RHS) friend
Definition at line 1093 of file Type.h.
operator<
bool operator< (const QualType & LHS, const QualType & RHS) friend
Definition at line 1096 of file Type.h.
operator==
bool operator== (const QualType & LHS, const QualType & RHS) friend
Indicate whether the specified types and qualifiers are identical.
Definition at line 1090 of file Type.h.
QualifierCollector
friend class QualifierCollector friend
Definition at line 737 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/ASTDumper.cpp
lib/AST/Type.cpp
lib/AST/TypePrinter.cpp