clang: clang::format::TokenAnnotator Class Reference
clang::format::TokenAnnotator Class Reference
Determines extra information about the tokens comprising an UnwrappedLine.
#include "/root/llvm-project/clang/lib/Format/TokenAnnotator.h"
Public Member Functions
TokenAnnotator (const FormatStyle &Style, const AdditionalKeywords &Keywords)
void setCommentLineLevels (SmallVectorImpl< AnnotatedLine * > &Lines) const
Adapts the indent levels of comment lines to the indent of the subsequent line.
void annotate (AnnotatedLine &Line)
void calculateFormattingInformation (AnnotatedLine &Line) const
Detailed Description
Determines extra information about the tokens comprising an UnwrappedLine.
Definition at line 195 of file TokenAnnotator.h.
Constructor & Destructor Documentation
TokenAnnotator()
clang::format::TokenAnnotator::TokenAnnotator (const FormatStyle & Style, const AdditionalKeywords & Keywords) inline
Definition at line 197 of file TokenAnnotator.h.
Member Function Documentation
annotate()
void clang::format::TokenAnnotator::annotate (AnnotatedLine & Line)
Definition at line 3099 of file TokenAnnotator.cpp.
References annotate(), clang::format::LT_Invalid, clang::format::LT_ObjCDecl, clang::format::LT_ObjCMethodDecl, clang::format::LT_ObjCProperty, and clang::format::maxNestingDepth().
Referenced by annotate(), and clang::format::TokenAnalyzer::process().
calculateFormattingInformation()
void clang::format::TokenAnnotator::calculateFormattingInformation (AnnotatedLine & Line) const
Definition at line 3303 of file TokenAnnotator.cpp.
References clang::format::BK_BracedInit, calculateFormattingInformation(), Children, clang::format::FormatToken::Children, IndentLevel, clang::format::FormatToken::is(), clang::format::isFunctionDeclarationName(), clang::format::LT_ArrayOfStructInitializer, clang::format::mustBreakAfterAttributes(), Next, clang::Parameter, Tok, and clang::format::FormatToken::TotalLength.
Referenced by calculateFormattingInformation().
setCommentLineLevels()
void clang::format::TokenAnnotator::setCommentLineLevels (SmallVectorImpl< AnnotatedLine * > & Lines) const
Adapts the indent levels of comment lines to the indent of the subsequent line.
Definition at line 3060 of file TokenAnnotator.cpp.
References clang::format::AnnotatedLine::First, clang::format::isClangFormatOff(), clang::format::AnnotatedLine::Level, clang::format::LT_CommentAbovePPDirective, clang::format::LT_ImportStatement, clang::format::LT_PreprocessorDirective, clang::format::FormatToken::NewlinesBefore, clang::format::FormatToken::OriginalColumn, setCommentLineLevels(), and clang::format::AnnotatedLine::Type.
Referenced by setCommentLineLevels().
The documentation for this class was generated from the following files:
lib/Format/TokenAnnotator.h
lib/Format/TokenAnnotator.cpp