clang: clang::DarwinSDKInfo Class Reference
clang::DarwinSDKInfo Class Reference
The information about the darwin SDK that was used during this compilation.
#include "clang/Basic/DarwinSDKInfo.h"
Classes
struct OSEnvPair
A value that describes two os-environment pairs that can be used as a key to the version map in the SDK.
class RelatedTargetVersionMapping
Represents a version mapping that maps from a version of one target to a version of a related target.
Public Member Functions
DarwinSDKInfo (VersionTuple Version, VersionTuple MaximumDeploymentTarget, llvm::DenseMap< OSEnvPair::StorageType, std::optional< RelatedTargetVersionMapping > > VersionMappings=llvm::DenseMap< OSEnvPair::StorageType, std::optional< RelatedTargetVersionMapping > >())
const llvm::VersionTuple & getVersion () const
const RelatedTargetVersionMapping * getVersionMapping (OSEnvPair Kind) const
Static Public Member Functions
static std::optional< DarwinSDKInfo > parseDarwinSDKSettingsJSON (const llvm::json::Object *Obj)
Detailed Description
The information about the darwin SDK that was used during this compilation.
Definition at line 29 of file DarwinSDKInfo.h.
Constructor & Destructor Documentation
DarwinSDKInfo()
clang::DarwinSDKInfo::DarwinSDKInfo (VersionTuple Version, VersionTuple MaximumDeploymentTarget, llvm::DenseMap< OSEnvPair::StorageType, std::optional< RelatedTargetVersionMapping > > VersionMappings = llvm::DenseMap<OSEnvPair::StorageType, std::optional<RelatedTargetVersionMapping>>()) inline
Definition at line 120 of file DarwinSDKInfo.h.
Referenced by parseDarwinSDKSettingsJSON().
Member Function Documentation
getVersion()
const llvm::VersionTuple & clang::DarwinSDKInfo::getVersion () const inline
Definition at line 130 of file DarwinSDKInfo.h.
getVersionMapping()
const RelatedTargetVersionMapping * clang::DarwinSDKInfo::getVersionMapping (OSEnvPair Kind) const inline
Definition at line 143 of file DarwinSDKInfo.h.
Referenced by handleAvailabilityAttr().
parseDarwinSDKSettingsJSON()
std::optional< DarwinSDKInfo > DarwinSDKInfo::parseDarwinSDKSettingsJSON (const llvm::json::Object * Obj) static
Definition at line 77 of file DarwinSDKInfo.cpp.
References DarwinSDKInfo(), getVersionKey(), clang::DarwinSDKInfo::OSEnvPair::macCatalystToMacOSPair(), clang::DarwinSDKInfo::OSEnvPair::macOStoMacCatalystPair(), and clang::DarwinSDKInfo::RelatedTargetVersionMapping::parseJSON().
Referenced by clang::parseDarwinSDKInfo().
The documentation for this class was generated from the following files:
include/clang/Basic/DarwinSDKInfo.h
lib/Basic/DarwinSDKInfo.cpp