clang: clang::FPOptions Class Reference
clang::FPOptions Class Reference
#include "clang/Basic/LangOptions.h"
Public Types
using storage_type = uint32_t
using RoundingMode = llvm::RoundingMode
Public Member Functions
FPOptions ()
FPOptions (const LangOptions &LO)
bool allowFPContractWithinStatement () const
void setAllowFPContractWithinStatement ()
bool allowFPContractAcrossStatement () const
void setAllowFPContractAcrossStatement ()
bool isFPConstrained () const
RoundingMode getRoundingMode () const
LangOptions::FPExceptionModeKind getExceptionMode () const
bool operator== (FPOptions other) const
storage_type getAsOpaqueInt () const
FPOptionsOverride getChangesFrom (const FPOptions &Base) const
Return difference with the given option set.
LLVM_DUMP_METHOD void dump ()
Static Public Member Functions
static FPOptions defaultWithoutTrailingStorage (const LangOptions &LO)
Return the default value of FPOptions that's used when trailing storage isn't required.
static FPOptions getFromOpaqueInt (storage_type Value)
Static Public Attributes
static constexpr unsigned StorageBitSize = 8 * sizeof(storage_type)
static constexpr storage_type FirstShift = 0
static constexpr storage_type FirstWidth = 0
static constexpr storage_type TotalWidth
Detailed Description
Definition at line 661 of file LangOptions.h.
Member Typedef Documentation
RoundingMode
using clang::FPOptions::RoundingMode = llvm::RoundingMode
Definition at line 666 of file LangOptions.h.
storage_type
using clang::FPOptions::storage_type = uint32_t
Definition at line 664 of file LangOptions.h.
Constructor & Destructor Documentation
FPOptions() [1/2]
clang::FPOptions::FPOptions () inline
Definition at line 693 of file LangOptions.h.
References clang::LangOptions::FPE_Default, and clang::LangOptions::FPM_Off.
FPOptions() [2/2]
clang::FPOptions::FPOptions (const LangOptions & LO) inline explicit
Definition at line 698 of file LangOptions.h.
References clang::LangOptions::FPE_Strict, clang::LangOptions::FPM_Fast, clang::LangOptions::FPM_FastHonorPragmas, clang::LangOptions::FPM_Off, clang::LangOptions::FPM_On, getExceptionMode(), and getRoundingMode().
Member Function Documentation
allowFPContractAcrossStatement()
bool clang::FPOptions::allowFPContractAcrossStatement () const inline
Definition at line 733 of file LangOptions.h.
References clang::LangOptions::FPM_Fast.
allowFPContractWithinStatement()
bool clang::FPOptions::allowFPContractWithinStatement () const inline
Definition at line 726 of file LangOptions.h.
References clang::LangOptions::FPM_On.
Referenced by clang::BinaryOperator::isFPContractableWithinStatement(), clang::UnaryOperator::isFPContractableWithinStatement(), and tryEmitFMulAdd().
defaultWithoutTrailingStorage()
FPOptions FPOptions::defaultWithoutTrailingStorage (const LangOptions & LO) static
Return the default value of FPOptions that's used when trailing storage isn't required.
Definition at line 211 of file LangOptions.cpp.
Referenced by clang::BinaryOperator::getFPFeaturesInEffect(), clang::CallExpr::getFPFeaturesInEffect(), clang::CastExpr::getFPFeaturesInEffect(), clang::Expr::getFPFeaturesInEffect(), and clang::UnaryOperator::getFPFeaturesInEffect().
dump()
LLVM_DUMP_METHOD void FPOptions::dump ()
Definition at line 225 of file LangOptions.cpp.
getAsOpaqueInt()
storage_type clang::FPOptions::getAsOpaqueInt () const inline
Definition at line 775 of file LangOptions.h.
getChangesFrom()
FPOptionsOverride clang::FPOptions::getChangesFrom (const FPOptions & Base) const inline
Return difference with the given option set.
Definition at line 914 of file LangOptions.h.
Referenced by clang::Sema::ActOnCompoundStmt(), and clang::Sema::resetFPOptions().
getExceptionMode()
LangOptions::FPExceptionModeKind clang::FPOptions::getExceptionMode () const inline
Definition at line 758 of file LangOptions.h.
References clang::LangOptions::FPE_Default, clang::LangOptions::FPE_Ignore, and clang::LangOptions::FPE_Strict.
Referenced by clang::Sema::ActOnPragmaFloatControl(), checkFloatingPointResult(), clang::interp::CheckFloatResult(), FPOptions(), and isFPConstrained().
getFromOpaqueInt()
static FPOptions clang::FPOptions::getFromOpaqueInt (storage_type Value) inline static
Definition at line 776 of file LangOptions.h.
Referenced by clang::FPOptionsOverride::applyOverrides(), clang::FPOptionsOverride::getFromOpaqueInt(), and clang::ASTReader::ReadLateParsedTemplates().
getRoundingMode()
RoundingMode clang::FPOptions::getRoundingMode () const inline
Definition at line 746 of file LangOptions.h.
Referenced by checkFloatingPointResult(), clang::interp::CheckFloatResult(), FPOptions(), getActiveRoundingMode(), and isFPConstrained().
isFPConstrained()
bool clang::FPOptions::isFPConstrained () const inline
Definition at line 740 of file LangOptions.h.
References clang::LangOptions::FPE_Ignore, getExceptionMode(), and getRoundingMode().
Referenced by addBlockPointerConversion(), addFunctionPointerConversion(), CreateNewFunctionDecl(), EvaluateComparisonBinaryOperator(), InsertOCLBuiltinDeclarationsFromTable(), and rewriteBuiltinFunctionDecl().
operator==()
bool clang::FPOptions::operator== (FPOptions other) const inline
Definition at line 769 of file LangOptions.h.
setAllowFPContractAcrossStatement()
void clang::FPOptions::setAllowFPContractAcrossStatement () inline
Definition at line 736 of file LangOptions.h.
References clang::LangOptions::FPM_Fast.
setAllowFPContractWithinStatement()
void clang::FPOptions::setAllowFPContractWithinStatement () inline
Definition at line 729 of file LangOptions.h.
References clang::LangOptions::FPM_On.
Member Data Documentation
FirstShift
storage_type clang::FPOptions::FirstShift = 0 static constexpr
Definition at line 672 of file LangOptions.h.
FirstWidth
storage_type clang::FPOptions::FirstWidth = 0 static
Definition at line 672 of file LangOptions.h.
StorageBitSize
unsigned clang::FPOptions::StorageBitSize = 8 * sizeof(storage_type) static constexpr
Definition at line 668 of file LangOptions.h.
Referenced by clang::FPOptionsOverride::getAsOpaqueInt(), and clang::FPOptionsOverride::getFromOpaqueInt().
TotalWidth
storage_type clang::FPOptions::TotalWidth static constexpr
Initial value:
= 0
#define OPTION(NAME, TYPE, WIDTH, PREVIOUS)
Definition at line 681 of file LangOptions.h.
The documentation for this class was generated from the following files:
include/clang/Basic/LangOptions.h
lib/Basic/LangOptions.cpp