clang: clang::RISCV::RVVTypeCache Class Reference
clang::RISCV::RVVTypeCache Class Reference
#include "clang/Support/RISCVVIntrinsicUtils.h"
Public Member Functions
std::optional< RVVTypes > computeTypes (BasicType BT, int Log2LMUL, unsigned NF, llvm::ArrayRef< PrototypeDescriptor > Prototype)
Compute output and input types by applying different config (basic type and LMUL with type transformers).
std::optional< RVVTypePtr > computeType (BasicType BT, int Log2LMUL, PrototypeDescriptor Proto)
Detailed Description
Definition at line 342 of file RISCVVIntrinsicUtils.h.
Member Function Documentation
computeType()
std::optional< RVVTypePtr > clang::RISCV::RVVTypeCache::computeType (BasicType BT, int Log2LMUL, PrototypeDescriptor Proto)
Definition at line 851 of file RISCVVIntrinsicUtils.cpp.
References clang::RISCV::computeRVVTypeHashValue().
Referenced by computeTypes(), and clang::RISCV::RVVIntrinsic::getSuffixStr().
computeTypes()
std::optional< RVVTypes > clang::RISCV::RVVTypeCache::computeTypes (BasicType BT, int Log2LMUL, unsigned NF, llvm::ArrayRef< PrototypeDescriptor > Prototype)
Compute output and input types by applying different config (basic type and LMUL with type transformers).
It also record result of type in legal or illegal set to avoid compute the same config again. The result maybe have illegal RVVType.
Definition at line 825 of file RISCVVIntrinsicUtils.cpp.
References computeType(), and clang::Prototype.
The documentation for this class was generated from the following files:
include/clang/Support/RISCVVIntrinsicUtils.h
lib/Support/RISCVVIntrinsicUtils.cpp