clang: clang::OMPDeclarativeDirective< U > Class Template Reference
clang::OMPDeclarativeDirective< U > Class Template Reference
This is a basic class for representing single OpenMP declarative directive.
#include "clang/AST/DeclOpenMP.h"
Public Member Functions
unsigned getNumClauses () const
Get number of clauses.
OMPClause * getClause (unsigned I) const
Returns specified clause.
ArrayRef< OMPClause * > clauses () const
Protected Member Functions
template<typename... Params>
OMPDeclarativeDirective (Params &&... P)
Build instance of directive.
Static Protected Member Functions
template<typename T , typename... Params>
static T * createDirective (const ASTContext &C, DeclContext *DC, ArrayRef< OMPClause * > Clauses, unsigned NumChildren, Params &&... P)
template<typename T , typename... Params>
static T * createEmptyDirective (const ASTContext &C, unsigned ID, unsigned NumClauses, unsigned NumChildren, Params &&... P)
static size_t size (unsigned NumClauses, unsigned NumChildren)
Protected Attributes
OMPChildren * Data = nullptr
Data, associated with the directive.
Friends
class ASTDeclReader
class ASTDeclWriter
Detailed Description
template<typename U>
class clang::OMPDeclarativeDirective< U >
This is a basic class for representing single OpenMP declarative directive.
Definition at line 30 of file DeclOpenMP.h.
Constructor & Destructor Documentation
OMPDeclarativeDirective()
template<typename U > template<typename... Params> clang::OMPDeclarativeDirective< U >::OMPDeclarativeDirective (Params &&... P) inline protected
Build instance of directive.
Definition at line 47 of file DeclOpenMP.h.
Member Function Documentation
clauses()
template<typename U > ArrayRef< OMPClause * > clang::OMPDeclarativeDirective< U >::clauses () const inline
Definition at line 91 of file DeclOpenMP.h.
References clang::OMPDeclarativeDirective< U >::Data, and clang::OMPChildren::getClauses().
Referenced by clang::OMPDeclarativeDirective< U >::getClause().
createDirective()
template<typename U > template<typename T , typename... Params> static T * clang::OMPDeclarativeDirective< U >::createDirective (const ASTContext & C, DeclContext * DC, ArrayRef< OMPClause * > Clauses, unsigned NumChildren, Params &&... P) inline static protected
Definition at line 50 of file DeclOpenMP.h.
References clang::C, P, and clang::OMPDeclarativeDirective< U >::size().
Referenced by clang::OMPAllocateDecl::Create(), clang::OMPDeclareMapperDecl::Create(), clang::OMPRequiresDecl::Create(), and clang::OMPThreadPrivateDecl::Create().
createEmptyDirective()
template<typename U > template<typename T , typename... Params> static T * clang::OMPDeclarativeDirective< U >::createEmptyDirective (const ASTContext & C, unsigned ID, unsigned NumClauses, unsigned NumChildren, Params &&... P) inline static protected
Definition at line 62 of file DeclOpenMP.h.
References clang::C, P, and clang::OMPDeclarativeDirective< U >::size().
Referenced by clang::OMPAllocateDecl::CreateDeserialized(), clang::OMPDeclareMapperDecl::CreateDeserialized(), clang::OMPRequiresDecl::CreateDeserialized(), and clang::OMPThreadPrivateDecl::CreateDeserialized().
getClause()
template<typename U > OMPClause * clang::OMPDeclarativeDirective< U >::getClause (unsigned I) const inline
Returns specified clause.
Parameters
I Number of clause.
Definition at line 89 of file DeclOpenMP.h.
References clang::OMPDeclarativeDirective< U >::clauses().
getNumClauses()
template<typename U > unsigned clang::OMPDeclarativeDirective< U >::getNumClauses () const inline
Get number of clauses.
Definition at line 79 of file DeclOpenMP.h.
References clang::OMPDeclarativeDirective< U >::Data, and clang::OMPChildren::getNumClauses().
size()
template<typename U > static size_t clang::OMPDeclarativeDirective< U >::size (unsigned NumClauses, unsigned NumChildren) inline static protected
Definition at line 72 of file DeclOpenMP.h.
Referenced by clang::OMPDeclarativeDirective< U >::createDirective(), and clang::OMPDeclarativeDirective< U >::createEmptyDirective().
Friends And Related Symbol Documentation
ASTDeclReader
template<typename U > friend class ASTDeclReader friend
Definition at line 31 of file DeclOpenMP.h.
ASTDeclWriter
template<typename U > friend class ASTDeclWriter friend
Definition at line 32 of file DeclOpenMP.h.
Member Data Documentation
Data
template<typename U > OMPChildren* clang::OMPDeclarativeDirective< U >::Data = nullptr protected
Data, associated with the directive.
Definition at line 43 of file DeclOpenMP.h.
Referenced by clang::OMPDeclarativeDirective< U >::clauses(), clang::OMPDeclarativeDirective< U >::getNumClauses(), clang::ASTDeclReader::VisitOMPAllocateDecl(), clang::ASTDeclWriter::VisitOMPAllocateDecl(), clang::ASTDeclReader::VisitOMPDeclareMapperDecl(), clang::ASTDeclWriter::VisitOMPDeclareMapperDecl(), clang::ASTDeclReader::VisitOMPRequiresDecl(), clang::ASTDeclWriter::VisitOMPRequiresDecl(), clang::ASTDeclReader::VisitOMPThreadPrivateDecl(), and clang::ASTDeclWriter::VisitOMPThreadPrivateDecl().
The documentation for this class was generated from the following file:
include/clang/AST/DeclOpenMP.h