clang: clang::TypeLoc Class Reference
clang::TypeLoc Class Reference
Base wrapper for a particular "section" of type source info.
#include "clang/AST/TypeLoc.h"
Public Types
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Public Member Functions
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Static Public Member Functions
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Attributes
const void * Ty = nullptr
void * Data = nullptr
Friends
bool operator== (const TypeLoc &LHS, const TypeLoc &RHS)
bool operator!= (const TypeLoc &LHS, const TypeLoc &RHS)
Detailed Description
Base wrapper for a particular "section" of type source info.
A client should use the TypeLoc subclasses through castAs()/getAs() in order to get at the actual information.
Definition at line 58 of file TypeLoc.h.
Member Enumeration Documentation
TypeLocClass
enum clang::TypeLoc::TypeLocClass
The kinds of TypeLocs.
Equivalent to the Type::TypeClass enum, except it also defines a Qualified enum that corresponds to the QualifiedLoc class.
Enumerator
Qualified
Definition at line 107 of file TypeLoc.h.
Constructor & Destructor Documentation
TypeLoc() [1/3]
clang::TypeLoc::TypeLoc () default
Referenced by getEndLoc(), and getLocalAlignmentForType().
TypeLoc() [2/3]
clang::TypeLoc::TypeLoc (QualType ty, void * opaqueData) inline
Definition at line 67 of file TypeLoc.h.
TypeLoc() [3/3]
clang::TypeLoc::TypeLoc (const Type * ty, void * opaqueData) inline
Definition at line 69 of file TypeLoc.h.
Member Function Documentation
castAs()
template<typename T > T clang::TypeLoc::castAs () const inline
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
Precondition
T::isKind(*this)
Definition at line 77 of file TypeLoc.h.
Referenced by clang::Sema::actOnObjCProtocolQualifierType(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::ActOnTemplatedFriendTag(), clang::TemplateDeclInstantiator::adjustForRewrite(), clang::Sema::BuildMemInitializer(), clang::Sema::CheckTypenameType(), clang::Sema::DiagnoseUnusedExprResult(), clang::Sema::findInheritingConstructor(), FixInvalidVariablyModifiedTypeLoc(), getBeginLoc(), getEndLoc(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::ASTContext::getTemplateSpecializationTypeInfo(), GetTypeSourceInfoForDeclarator(), getUnqualifiedLoc(), NeedsInstantiationAsFunctionType(), clang::TypeLocBuilder::push(), clang::TypeLocBuilder::pushTypeSpec(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TreeTransform< Derived >::TransformFunctionTypeParams(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
copy()
void TypeLoc::copy (TypeLoc other)
Copies the other type loc into this one.
Definition at line 167 of file TypeLoc.cpp.
References Data, getFullDataSize(), getNextTypeLoc(), getType(), memcpy(), and TypeLocMaxDataAlign.
Referenced by initializeFullCopy(), and initializeFullCopy().
findExplicitQualifierLoc()
TypeLoc TypeLoc::findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
The result, if non-null, will be one of: QualifiedTypeLoc AtomicTypeLoc AttributedTypeLoc, for those type attributes that behave as qualifiers
Definition at line 457 of file TypeLoc.cpp.
References clang::ast_matchers::attr, getAs(), and IgnoreParens().
Referenced by clang::Sema::actOnObjCTypeParam(), and applyObjCTypeArgs().
findNullabilityLoc()
SourceLocation TypeLoc::findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Definition at line 446 of file TypeLoc.cpp.
References getAs(), and clang::Attr::getLocation().
getAs()
template<typename T > T clang::TypeLoc::getAs () const inline
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
Definition at line 88 of file TypeLoc.h.
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnTemplateTypeArgument(), addFunctionPointerConversion(), checkAllAtProps(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::checkThisInStaticMemberFunctionExceptionSpec(), clang::Sema::checkThisInStaticMemberFunctionType(), convertTypeTemplateArgumentToTemplate(), clang::Sema::createLambdaInitCaptureVarDecl(), DiagnoseCalleeStaticArrayParam(), findExplicitQualifierLoc(), findNullabilityLoc(), findTypeLocationForBlockDecl(), FixInvalidVariablyModifiedTypeLoc(), getAsAdjusted(), getContainedAutoTypeLoc(), clang::comments::getFunctionTypeLoc(), clang::FunctionDecl::getFunctionTypeLoc(), clang::UsingEnumDecl::getQualifierLoc(), GetTypeSourceInfoForDeclarator(), getUnqualifiedLoc(), isEnableIf(), clang::Expr::isFlexibleArrayMemberLike(), clang::comments::lookThroughTypedefOrTypeAliasLocs(), NeedsInstantiationAsFunctionType(), clang::InitializationSequence::Perform(), clang::Sema::SubstFunctionDeclType(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
getAsAdjusted()
template<typename T > T clang::TypeLoc::getAsAdjusted () const inline
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
It will consider type adjustments from a type that was written as a T to another type that is still canonically a T (ignores parens, attributes, elaborated types, etc).
Definition at line 2636 of file TypeLoc.h.
References getAs().
Referenced by clang::Sema::ActOnBlockArguments(), clang::TemplateDeclInstantiator::adjustForRewrite(), checkAttributesAfterMerging(), clang::Sema::CheckDeductionGuideDeclarator(), findTypeLocationForBlockDecl(), clang::Sema::getReturnTypeLoc(), implicitObjectParamIsLifetimeBound(), clang::Expr::isFlexibleArrayMemberLike(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getBeginLoc()
SourceLocation TypeLoc::getBeginLoc () const
Get the begin source location.
Definition at line 191 of file TypeLoc.cpp.
References castAs(), clang::SourceRange::getBegin(), getLocalSourceRange(), getNextTypeLoc(), getTypeLocClass(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::FunctionProtoType::hasTrailingReturn(), isNull(), clang::SourceLocation::isValid(), and Qualified.
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::Sema::ActOnCXXTypeConstructExpr(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnTag(), clang::Sema::ActOnTemplateTypeArgument(), applyObjCTypeArgs(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckBaseSpecifier(), CheckConstexprDeclStmt(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckEnumUnderlyingType(), clang::Sema::CheckFriendTypeDecl(), clang::Sema::CreatePropertyDecl(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::deduceVarTypeFromInitializer(), clang::CXXScopeSpec::Extend(), clang::CXXBaseSpecifier::getBaseTypeLoc(), clang::CXXFunctionalCastExpr::getBeginLoc(), clang::CXXTemporaryObjectExpr::getBeginLoc(), clang::TemplateTypeParmDecl::getDefaultArgumentLoc(), GetFullTypeForDeclarator(), clang::DependentNameTypeLoc::getLocalSourceRange(), clang::DependentTemplateSpecializationTypeLoc::getLocalSourceRange(), clang::NestedNameSpecifierLoc::getLocalSourceRange(), getPointeeTypeText(), getSourceRange(), clang::DeclaratorDecl::getTypeSpecStartLoc(), handleAlignedAttr(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::TreeTransform< Derived >::RebuildQualifiedType(), ReplaceWithClasstype(), ReplaceWithInstancetype(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), clang::TreeTransform< Derived >::TransformType(), clang::TreeTransform< Derived >::TransformTypeWithDeducedTST(), and clang::tooling::RecursiveSymbolVisitor< T >::VisitTypedefTypeLoc().
getContainedAutoTypeLoc()
AutoTypeLoc TypeLoc::getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
This looks through declarators like pointer types, but not through decltype or typedefs.
Definition at line 715 of file TypeLoc.cpp.
References getAs(), and isNull().
Referenced by clang::Sema::ActOnNonTypeTemplateParameter(), and InventTemplateParameter().
getEndLoc()
SourceLocation TypeLoc::getEndLoc () const
Get the end source location.
Definition at line 234 of file TypeLoc.cpp.
References castAs(), clang::SourceRange::getEnd(), getLocalSourceRange(), getNextTypeLoc(), clang::ObjCObjectPointerTypeLoc::getStarLoc(), getTypeLocClass(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::FunctionProtoType::hasTrailingReturn(), clang::SourceLocation::isInvalid(), clang::Last, Paren, Pointer, Qualified, and TypeLoc().
Referenced by clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckParameter(), clang::Sema::CreatePropertyDecl(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), GetFullTypeForDeclarator(), clang::ElaboratedTypeLoc::getLocalSourceRange(), getPointeeTypeText(), clang::ClassTemplateSpecializationDecl::getSourceRange(), getSourceRange(), clang::UsingEnumDecl::getSourceRange(), clang::DeclaratorDecl::getTypeSpecEndLoc(), ReplaceWithClasstype(), ReplaceWithInstancetype(), and clang::Sema::SubstExceptionSpec().
getFullDataSize()
unsigned clang::TypeLoc::getFullDataSize () const inline
Returns the size of the type source info data block.
Definition at line 163 of file TypeLoc.h.
References getFullDataSizeForType(), and getType().
Referenced by clang::AutoTypeLoc::copy(), clang::DependentNameTypeLoc::copy(), clang::DependentTemplateSpecializationTypeLoc::copy(), clang::ElaboratedTypeLoc::copy(), clang::TemplateSpecializationTypeLoc::copy(), copy(), GetTypeSourceInfoForDeclarator(), initializeFullCopy(), clang::TypeLocBuilder::pushFullCopy(), clang::Sema::SubstFunctionDeclType(), clang::Sema::SubstType(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TreeTransform< Derived >::TransformType(), and clang::TreeTransform< Derived >::TransformTypeWithDeducedTST().
getFullDataSizeForType()
unsigned TypeLoc::getFullDataSizeForType (QualType Ty) static
Returns the size of type source info data block for the given type.
Returns the size of the type source info data block.
Definition at line 93 of file TypeLoc.cpp.
References getLocalAlignmentForType(), getNextTypeLoc(), getType(), isNull(), and Ty.
Referenced by clang::ASTContext::adjustExceptionSpec(), clang::ASTContext::CreateTypeSourceInfo(), and getFullDataSize().
getLocalAlignmentForType()
unsigned TypeLoc::getLocalAlignmentForType (QualType Ty) static
Returns the alignment of type source info data block for the given type.
Returns the alignment of the type source info data block.
Definition at line 73 of file TypeLoc.cpp.
References Ty, and TypeLoc().
Referenced by getFullDataSizeForType(), and clang::QualifiedTypeLoc::getUnqualifiedLoc().
getLocalSourceRange()
SourceRange clang::TypeLoc::getLocalSourceRange () const inline
Get the local source range.
Definition at line 158 of file TypeLoc.h.
Referenced by clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBuiltinOffsetOf(), CheckDeducedPlaceholderConstraints(), getBeginLoc(), getEndLoc(), and clang::MacroQualifiedTypeLoc::getLocalSourceRange().
getNextTypeLoc()
TypeLoc clang::TypeLoc::getNextTypeLoc () const inline
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
Definition at line 169 of file TypeLoc.h.
Referenced by clang::ASTRecordWriter::AddTypeLoc(), copy(), getBeginLoc(), getEndLoc(), getFullDataSizeForType(), getPointeeTypeText(), GetTypeSourceInfoForDeclarator(), clang::TypeLocBuilder::pushFullCopy(), and clang::ASTRecordReader::readTypeLoc().
getOpaqueData()
void * clang::TypeLoc::getOpaqueData () const inline
Get the pointer where source information is stored.
Definition at line 141 of file TypeLoc.h.
References Data.
Referenced by clang::NestedNameSpecifierLocBuilder::Extend(), clang::TypeLocBuilder::getTypeSourceInfo(), GetTypeSourceInfoForDeclarator(), and clang::NestedNameSpecifierLocBuilder::MakeTrivial().
getSourceRange()
SourceRange clang::TypeLoc::getSourceRange () const inline
Get the full source range.
Definition at line 152 of file TypeLoc.h.
References getBeginLoc(), and getEndLoc().
Referenced by clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::AddAlignedAttr(), AnalyzeBitFieldAssignment(), applyObjCTypeArgs(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildClassMessage(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckBaseSpecifier(), CheckConstexprDeclStmt(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckFriendTypeDecl(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckParameter(), clang::Sema::CheckTemplateArgument(), checkTypeParamListConsistency(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::diagnoseQualifiedDeclaration(), findTemplateParameter(), clang::TypeOfExprTypeLoc::getLocalSourceRange(), getPointeeTypeText(), clang::Sema::getPrintable(), getRangeOfTypeInNestedNameSpecifier(), clang::ObjCMessageExpr::getReceiverRange(), clang::FunctionDecl::getReturnTypeSourceRange(), getTypeRange(), clang::Sema::InstantiateMemInitializers(), and clang::TreeTransform< Derived >::TransformFunctionTypeParam().
getType()
QualType clang::TypeLoc::getType () const inline
Get the type for which this source info wrapper provides information.
Definition at line 132 of file TypeLoc.h.
References clang::QualType::getFromOpaquePtr(), and Ty.
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), AddObjCBlockCall(), clang::Sema::AttachTypeConstraint(), CheckConstexprDeclStmt(), copy(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::comments::DeclInfo::fill(), findTemplateParameter(), getFullDataSize(), getFullDataSizeForType(), clang::Sema::getTemplateArgumentPackExpansionPattern(), getTypeLocClass(), initializeFullCopy(), initializeFullCopy(), clang::TreeTransform< Derived >::RebuildQualifiedType(), clang::Sema::SubstType(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::TreeTransform< Derived >::TransformReferenceType().
getTypeLocClass()
TypeLocClass clang::TypeLoc::getTypeLocClass () const inline
Definition at line 115 of file TypeLoc.h.
References getType(), clang::Type::getTypeClass(), and Qualified.
Referenced by getBeginLoc(), getEndLoc(), clang::TypeLocBuilder::pushFullCopy(), clang::RecursiveASTVisitor< Derived >::TraverseTypeLoc(), and clang::TypeLocVisitor< ImplClass, RetTy >::Visit().
getTypePtr()
const Type * clang::TypeLoc::getTypePtr () const inline
Definition at line 136 of file TypeLoc.h.
References clang::QualType::getFromOpaquePtr(), clang::QualType::getTypePtr(), and Ty.
Referenced by clang::NestedNameSpecifierLocBuilder::Extend(), and clang::QualifiedTypeLoc::getUnqualifiedLoc().
getUnqualifiedLoc()
UnqualTypeLoc clang::TypeLoc::getUnqualifiedLoc () const inline
Skips past any qualifiers, if this is qualified.
Definition at line 331 of file TypeLoc.h.
References castAs(), and getAs().
Referenced by clang::comments::DeclInfo::fill(), findTypeLocationForBlockDecl(), FixInvalidVariablyModifiedTypeLoc(), clang::comments::getFunctionTypeLoc(), getPointeeTypeText(), GetTypeSourceInfoForDeclarator(), clang::comments::lookThroughTypedefOrTypeAliasLocs(), clang::TreeTransform< Derived >::TransformTypeWithDeducedTST(), and clang::RecursiveASTVisitor< Derived >::WalkUpFromUnqualTypeLoc().
IgnoreParens()
TypeLoc clang::TypeLoc::IgnoreParens () const inline
Definition at line 1188 of file TypeLoc.h.
Referenced by clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckFunctionDeclaration(), findExplicitQualifierLoc(), clang::Sema::findInheritingConstructor(), findTypeLocationForBlockDecl(), clang::FunctionDecl::getFunctionTypeLoc(), clang::comments::lookThroughTypedefOrTypeAliasLocs(), NeedsInstantiationAsFunctionType(), clang::Sema::SubstFunctionDeclType(), and clang::TemplateDeclInstantiator::SubstFunctionType().
initialize()
void clang::TypeLoc::initialize (ASTContext & Context, SourceLocation Loc) const inline
Initializes this to state that every location in this type is the given location.
This method exists to provide a simple transition for code that relies on location-less types.
Definition at line 196 of file TypeLoc.h.
Referenced by clang::ASTContext::getTrivialTypeSourceInfo().
initializeFullCopy() [1/2]
void clang::TypeLoc::initializeFullCopy (TypeLoc Other) inline
Initializes this by copying its information from another TypeLoc of the same type.
Definition at line 202 of file TypeLoc.h.
References copy(), and getType().
Referenced by clang::Sema::ActOnBlockArguments(), and FixInvalidVariablyModifiedTypeLoc().
initializeFullCopy() [2/2]
void clang::TypeLoc::initializeFullCopy (TypeLoc Other, unsigned Size) inline
Initializes this by copying its information from another TypeLoc of the same type.
The given size must be the full data size.
Definition at line 210 of file TypeLoc.h.
References copy(), getFullDataSize(), and getType().
isNull()
bool clang::TypeLoc::isNull () const inline
Definition at line 120 of file TypeLoc.h.
References Ty.
Referenced by clang::ASTRecordWriter::AddTypeLoc(), clang::Sema::BuildMemInitializer(), getBeginLoc(), getContainedAutoTypeLoc(), getFullDataSizeForType(), clang::index::IndexingContext::indexTypeLoc(), clang::index::IndexingContext::indexTypeSourceInfo(), clang::ASTRecordReader::readTypeLoc(), and clang::RecursiveASTVisitor< Derived >::TraverseTypeLoc().
operator bool()
clang::TypeLoc::operator bool () const inline explicit
Definition at line 121 of file TypeLoc.h.
References Ty.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const TypeLoc & LHS, const TypeLoc & RHS) friend
Definition at line 223 of file TypeLoc.h.
operator==
bool operator== (const TypeLoc & LHS, const TypeLoc & RHS) friend
Definition at line 219 of file TypeLoc.h.
Member Data Documentation
Data
void* clang::TypeLoc::Data = nullptr protected
Definition at line 63 of file TypeLoc.h.
Referenced by clang::DependentNameTypeLoc::copy(), clang::DependentTemplateSpecializationTypeLoc::copy(), clang::ElaboratedTypeLoc::copy(), clang::TemplateSpecializationTypeLoc::copy(), copy(), getOpaqueData(), and clang::QualifiedTypeLoc::getUnqualifiedLoc().
Ty
const void* clang::TypeLoc::Ty = nullptr protected
Definition at line 62 of file TypeLoc.h.
Referenced by getFullDataSizeForType(), getLocalAlignmentForType(), getType(), getTypePtr(), clang::UnqualTypeLoc::getTypePtr(), isNull(), and operator bool().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp