clang: clang::DynTypedNodeList Class Reference
clang::DynTypedNodeList Class Reference
Container for either a single DynTypedNode or for an ArrayRef to DynTypedNode.
#include "clang/AST/ParentMapContext.h"
Public Member Functions
DynTypedNodeList (const DynTypedNode &N)
DynTypedNodeList (ArrayRef< DynTypedNode > A)
const DynTypedNode * begin () const
const DynTypedNode * end () const
size_t size () const
bool empty () const
const DynTypedNode & operator[] (size_t N) const
Detailed Description
Container for either a single DynTypedNode or for an ArrayRef to DynTypedNode.
For use with ParentMap.
Definition at line 92 of file ParentMapContext.h.
Constructor & Destructor Documentation
DynTypedNodeList() [1/2]
clang::DynTypedNodeList::DynTypedNodeList (const DynTypedNode & N) inline
Definition at line 100 of file ParentMapContext.h.
References N, and SingleNode.
DynTypedNodeList() [2/2]
clang::DynTypedNodeList::DynTypedNodeList (ArrayRef< DynTypedNode > A) inline
Definition at line 104 of file ParentMapContext.h.
References Nodes.
Member Function Documentation
begin()
const DynTypedNode * clang::DynTypedNodeList::begin () const inline
Definition at line 108 of file ParentMapContext.h.
References Nodes, and SingleNode.
Referenced by empty(), operator[](), and size().
empty()
bool clang::DynTypedNodeList::empty () const inline
Definition at line 117 of file ParentMapContext.h.
References begin(), and end().
Referenced by isInCondition().
end()
const DynTypedNode * clang::DynTypedNodeList::end () const inline
Definition at line 112 of file ParentMapContext.h.
References Nodes, and SingleNode.
Referenced by empty(), and size().
operator[]()
const DynTypedNode & clang::DynTypedNodeList::operator[] (size_t N) const inline
Definition at line 119 of file ParentMapContext.h.
References begin(), N, and size().
size()
size_t clang::DynTypedNodeList::size () const inline
Definition at line 116 of file ParentMapContext.h.
References begin(), and end().
Referenced by operator[]().
Member Data Documentation
Nodes
ArrayRef<DynTypedNode> clang::DynTypedNodeList::Nodes
Definition at line 95 of file ParentMapContext.h.
Referenced by begin(), DynTypedNodeList(), and end().
SingleNode
DynTypedNode clang::DynTypedNodeList::SingleNode
Definition at line 94 of file ParentMapContext.h.
Referenced by begin(), DynTypedNodeList(), and end().
The documentation for this class was generated from the following file:
include/clang/AST/ParentMapContext.h