clang: clang::OverloadCandidateSet Class Reference
clang::OverloadCandidateSet Class Reference
OverloadCandidateSet - A set of overload candidates, used in C++ overload resolution (C++ 13.3).
#include "clang/Sema/Overload.h"
Classes
struct OperatorRewriteInfo
Information about operator rewrites to consider when adding operator functions to a candidate set.
Public Types
enum CandidateSetKind { CSK_Normal , CSK_Operator , CSK_InitByUserDefinedConversion , CSK_InitByConstructor }
using iterator = SmallVectorImpl<OverloadCandidate>::iterator
Public Member Functions
OverloadCandidateSet (SourceLocation Loc, CandidateSetKind CSK, OperatorRewriteInfo RewriteInfo={})
OverloadCandidateSet (const OverloadCandidateSet &)=delete
OverloadCandidateSet & operator= (const OverloadCandidateSet &)=delete
~OverloadCandidateSet ()
SourceLocation getLocation () const
CandidateSetKind getKind () const
OperatorRewriteInfo getRewriteInfo () const
bool shouldDeferDiags (Sema &S, ArrayRef< Expr * > Args, SourceLocation OpLoc)
Whether diagnostics should be deferred.
bool isNewCandidate (Decl *F, OverloadCandidateParamOrder PO=OverloadCandidateParamOrder::Normal)
Determine when this overload candidate will be new to the overload set.
void exclude (Decl *F)
Exclude a function from being considered by overload resolution.
void clear (CandidateSetKind CSK)
Clear out all of the candidates.
iterator begin ()
iterator end ()
size_t size () const
bool empty () const
ConversionSequenceList allocateConversionSequences (unsigned NumConversions)
Allocate storage for conversion sequences for NumConversions conversions.
OverloadCandidate & addCandidate (unsigned NumConversions=0, ConversionSequenceList Conversions=std::nullopt)
Add a new candidate with NumConversions conversion sequence slots to the overload set.
OverloadingResult BestViableFunction (Sema &S, SourceLocation Loc, OverloadCandidateSet::iterator &Best)
Find the best viable function on this overload set, if it exists.
SmallVector< OverloadCandidate *, 32 > CompleteCandidates (Sema &S, OverloadCandidateDisplayKind OCD, ArrayRef< Expr * > Args, SourceLocation OpLoc=SourceLocation(), llvm::function_ref< bool(OverloadCandidate &)> Filter=[](OverloadCandidate &) { return true;})
void NoteCandidates (PartialDiagnosticAt PA, Sema &S, OverloadCandidateDisplayKind OCD, ArrayRef< Expr * > Args, StringRef Opc="", SourceLocation Loc=SourceLocation(), llvm::function_ref< bool(OverloadCandidate &)> Filter=[](OverloadCandidate &) { return true;})
When overload resolution fails, prints diagnostic messages containing the candidates in the candidate set.
void NoteCandidates (Sema &S, ArrayRef< Expr * > Args, ArrayRef< OverloadCandidate * > Cands, StringRef Opc="", SourceLocation OpLoc=SourceLocation())
LangAS getDestAS ()
void setDestAS (LangAS AS)
Detailed Description
OverloadCandidateSet - A set of overload candidates, used in C++ overload resolution (C++ 13.3).
Definition at line 954 of file Overload.h.
Member Typedef Documentation
iterator
using clang::OverloadCandidateSet::iterator = SmallVectorImpl<OverloadCandidate>::iterator
Definition at line 1127 of file Overload.h.
Member Enumeration Documentation
CandidateSetKind
enum clang::OverloadCandidateSet::CandidateSetKind
Enumerator
CSK_Normal
Normal lookup.
CSK_Operator
C++ [over.match.oper]: Lookup of operator function candidates in a call using operator syntax.
Candidates that have no parameters of class type will be skipped unless there is a parameter of (reference to) enum type and the corresponding argument is of the same enum type.
CSK_InitByUserDefinedConversion
C++ [over.match.copy]: Copy-initialization of an object of class type by user-defined conversion.
CSK_InitByConstructor
C++ [over.match.ctor], [over.match.list] Initialization of an object of class type by constructor, using either a parenthesized or braced list of arguments.
Definition at line 956 of file Overload.h.
Constructor & Destructor Documentation
OverloadCandidateSet() [1/2]
clang::OverloadCandidateSet::OverloadCandidateSet (SourceLocation Loc, CandidateSetKind CSK, OperatorRewriteInfo RewriteInfo = {}) inline
Definition at line 1095 of file Overload.h.
OverloadCandidateSet() [2/2]
clang::OverloadCandidateSet::OverloadCandidateSet (const OverloadCandidateSet &) delete
~OverloadCandidateSet()
clang::OverloadCandidateSet::~OverloadCandidateSet () inline
Definition at line 1100 of file Overload.h.
Member Function Documentation
addCandidate()
OverloadCandidate & clang::OverloadCandidateSet::addCandidate (unsigned NumConversions = 0, ConversionSequenceList Conversions = std::nullopt) inline
Add a new candidate with NumConversions conversion sequence slots to the overload set.
Definition at line 1152 of file Overload.h.
References allocateConversionSequences(), and clang::C.
Referenced by clang::Sema::AddBuiltinCandidate(), clang::Sema::AddConversionCandidate(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddOverloadCandidate(), clang::Sema::AddSurrogateCandidate(), clang::Sema::AddTemplateConversionCandidate(), and clang::Sema::AddTemplateOverloadCandidate().
allocateConversionSequences()
ConversionSequenceList clang::OverloadCandidateSet::allocateConversionSequences (unsigned NumConversions) inline
Allocate storage for conversion sequences for NumConversions conversions.
Definition at line 1138 of file Overload.h.
Referenced by addCandidate(), and clang::Sema::CheckNonDependentConversions().
begin()
iterator clang::OverloadCandidateSet::begin () inline
Definition at line 1129 of file Overload.h.
Referenced by clang::Sema::AddArgumentDependentLookupCandidates(), BestViableFunction(), clang::Sema::BuildCallToObjectOfClassType(), CompleteCandidates(), ComputeSelectedDestructor(), FindConversionForRefInit(), markUnaddressableCandidatesUnviable(), NoteCandidates(), clang::TemplateSpecCandidateSet::NoteCandidates(), and TryUserDefinedConversion().
BestViableFunction()
OverloadingResult OverloadCandidateSet::BestViableFunction (Sema & S, SourceLocation Loc, OverloadCandidateSet::iterator & Best)
Find the best viable function on this overload set, if it exists.
Computes the best viable function (C++ 13.3.3) within an overload candidate set.
Parameters
Loc The location of the function name (or operator symbol) for which overload resolution occurs.
Best If overload resolution was successful or found a deleted function, Best points to the candidate function found.
Returns
The result of overload resolution.
Definition at line 10333 of file SemaOverload.cpp.
References begin(), clang::OverloadCandidate::Best, clang::Sema::CFP_SameSide, clang::Sema::CFP_WrongSide, clang::Sema::diagnoseEquivalentInternalLinkageDeclarations(), end(), clang::OverloadCandidate::Function, clang::Sema::getCurFunctionDecl(), clang::Sema::getLangOpts(), clang::Sema::IdentifyCUDAPreference(), clang::isBetterOverloadCandidate(), clang::Sema::isEquivalentInternalLinkageDeclaration(), clang::OverloadCandidate::NotValidBecauseConstraintExprHasError(), clang::OR_Ambiguous, clang::OR_Deleted, clang::OR_No_Viable_Function, clang::OR_Success, and clang::OverloadCandidate::Viable.
Referenced by clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildOverloadedCallExpr(), clang::Sema::buildOverloadedCallSet(), ComputeSelectedDestructor(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseTwoPhaseLookup(), clang::Sema::EvaluateStaticAssertMessageAsString(), FindConditionalOverload(), FindConversionForRefInit(), clang::InitializationSequence::InitializeFrom(), IsInitializerListConstructorConversion(), IsUserDefinedConversion(), clang::Sema::LookupSpecialMember(), clang::Sema::PerformContextualImplicitConversion(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), ResolveConstructorOverload(), TryRefInitWithConversionFunction(), TryTypoCorrectionForCall(), and TryUserDefinedConversion().
clear()
void OverloadCandidateSet::clear (CandidateSetKind CSK)
Clear out all of the candidates.
Definition at line 1007 of file SemaOverload.cpp.
Referenced by clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), IsInitializerListConstructorConversion(), IsUserDefinedConversion(), ResolveConstructorOverload(), TryRefInitWithConversionFunction(), and TryUserDefinedConversion().
CompleteCandidates()
SmallVector< OverloadCandidate *, 32 > OverloadCandidateSet::CompleteCandidates (Sema & S, OverloadCandidateDisplayKind OCD, ArrayRef< Expr * > Args, SourceLocation OpLoc = SourceLocation(), llvm::function_ref< bool(OverloadCandidate &)> Filter = [](OverloadCandidate &) { return true; })
Definition at line 11989 of file SemaOverload.cpp.
References begin(), CompleteNonViableCandidate(), end(), clang::OCD_AllCandidates, clang::OCD_AmbiguousCandidates, clang::OCD_ViableCandidates, and size().
Referenced by clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::CreateOverloadedBinOp(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), NoteCandidates(), resolveAllocationOverload(), and shouldDeferDiags().
empty()
bool clang::OverloadCandidateSet::empty () const inline
Definition at line 1133 of file Overload.h.
Referenced by clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::buildOverloadedCallSet(), ComputeSelectedDestructor(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), FinishOverloadedCallExpr(), clang::Sema::ProduceCallSignatureHelp(), tryDiagnoseOverloadedCast(), and TryReferenceInitializationCore().
end()
iterator clang::OverloadCandidateSet::end () inline
Definition at line 1130 of file Overload.h.
Referenced by clang::Sema::AddArgumentDependentLookupCandidates(), BestViableFunction(), clang::Sema::BuildCallToObjectOfClassType(), chooseRecoveryType(), CompleteCandidates(), DiagnoseTwoPhaseLookup(), FindConversionForRefInit(), markUnaddressableCandidatesUnviable(), NoteCandidates(), clang::TemplateSpecCandidateSet::NoteCandidates(), clang::Sema::PerformCopyInitialization(), and TryUserDefinedConversion().
exclude()
void clang::OverloadCandidateSet::exclude (Decl * F) inline
Exclude a function from being considered by overload resolution.
Definition at line 1119 of file Overload.h.
References isNewCandidate(), clang::Normal, and clang::Reversed.
Referenced by clang::Sema::CreateOverloadedBinOp().
getDestAS()
LangAS clang::OverloadCandidateSet::getDestAS () inline
Definition at line 1187 of file Overload.h.
Referenced by clang::Sema::AddOverloadCandidate().
getKind()
CandidateSetKind clang::OverloadCandidateSet::getKind () const inline
Definition at line 1103 of file Overload.h.
Referenced by clang::Sema::AddOverloadCandidate(), mergeCandidatesWithResults(), and TryConstructorInitialization().
getLocation()
SourceLocation clang::OverloadCandidateSet::getLocation () const inline
Definition at line 1102 of file Overload.h.
Referenced by clang::Sema::AddConversionCandidate(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddOverloadCandidate(), clang::Sema::AddSurrogateCandidate(), clang::Sema::AddTemplateConversionCandidate(), clang::Sema::AddTemplateOverloadCandidate(), clang::Sema::CheckNonDependentConversions(), and clang::Sema::LookupOverloadedBinOp().
getRewriteInfo()
OperatorRewriteInfo clang::OverloadCandidateSet::getRewriteInfo () const inline
Definition at line 1104 of file Overload.h.
Referenced by clang::Sema::AddArgumentDependentLookupCandidates(), clang::Sema::AddMemberOperatorCandidates(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddNonMemberOperatorCandidates(), clang::Sema::AddOverloadCandidate(), clang::Sema::AddTemplateOverloadCandidate(), clang::Sema::CreateOverloadedBinOp(), and clang::Sema::LookupOverloadedBinOp().
isNewCandidate()
bool clang::OverloadCandidateSet::isNewCandidate (Decl * F, OverloadCandidateParamOrder PO = OverloadCandidateParamOrder::Normal) inline
Determine when this overload candidate will be new to the overload set.
Definition at line 1111 of file Overload.h.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::AddConversionCandidate(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddOverloadCandidate(), clang::Sema::AddSurrogateCandidate(), clang::Sema::AddTemplateConversionCandidate(), clang::Sema::AddTemplateOverloadCandidate(), and exclude().
NoteCandidates() [1/2]
void OverloadCandidateSet::NoteCandidates (PartialDiagnosticAt PA, Sema & S, OverloadCandidateDisplayKind OCD, ArrayRef< Expr * > Args, StringRef Opc = "", SourceLocation Loc = SourceLocation(), llvm::function_ref< bool(OverloadCandidate &)> Filter = [](OverloadCandidate &) { return true; })
When overload resolution fails, prints diagnostic messages containing the candidates in the candidate set.
Definition at line 12053 of file SemaOverload.cpp.
References begin(), CompleteCandidates(), clang::Sema::Diag(), end(), MaybeDiagnoseAmbiguousConstraints(), NoteCandidates(), clang::OCD_AmbiguousCandidates, and shouldDeferDiags().
Referenced by clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildLiteralOperatorCall(), BuildNonArrayForRange(), clang::Sema::BuildOverloadedArrowExpr(), CheckCXX98CompatAccessibleCopy(), ComputeSelectedDestructor(), CopyObject(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), clang::Sema::EvaluateStaticAssertMessageAsString(), FinishOverloadedCallExpr(), NoteCandidates(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), and tryDiagnoseOverloadedCast().
NoteCandidates() [2/2]
void OverloadCandidateSet::NoteCandidates (Sema & S, ArrayRef< Expr * > Args, ArrayRef< OverloadCandidate * > Cands, StringRef Opc = "", SourceLocation OpLoc = SourceLocation())
Definition at line 12077 of file SemaOverload.cpp.
References clang::Sema::Diag(), clang::Sema::Diags, clang::OverloadCandidate::Function, clang::DiagnosticsEngine::getNumOverloadCandidatesToShow(), clang::DiagnosticsEngine::getShowOverloads(), int, clang::OverloadCandidate::IsSurrogate, NoteAmbiguousUserConversions(), NoteBuiltinOperatorCandidate(), NoteFunctionCandidate(), NoteSurrogateCandidate(), clang::DiagnosticsEngine::overloadCandidatesShown(), clang::Ovl_Best, shouldDeferDiags(), and clang::OverloadCandidate::Viable.
operator=()
OverloadCandidateSet & clang::OverloadCandidateSet::operator= (const OverloadCandidateSet &) delete
setDestAS()
void clang::OverloadCandidateSet::setDestAS (LangAS AS) inline
Definition at line 1189 of file Overload.h.
References CSK_InitByConstructor, and CSK_InitByUserDefinedConversion.
Referenced by ResolveConstructorOverload(), and TryUserDefinedConversion().
shouldDeferDiags()
bool OverloadCandidateSet::shouldDeferDiags (Sema & S, ArrayRef< Expr * > Args, SourceLocation OpLoc)
Whether diagnostics should be deferred.
Definition at line 12032 of file SemaOverload.cpp.
References CompleteCandidates(), clang::Sema::getLangOpts(), hasAttr(), clang::OCD_AllCandidates, and clang::ovl_fail_bad_target.
Referenced by clang::Sema::CreateOverloadedBinOp(), NoteCandidates(), and NoteCandidates().
size()
size_t clang::OverloadCandidateSet::size () const inline
Definition at line 1132 of file Overload.h.
Referenced by clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildOverloadedArrowExpr(), CompleteCandidates(), CopyObject(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), FindConversionForRefInit(), IsInitializerListConstructorConversion(), IsUserDefinedConversion(), clang::TemplateSpecCandidateSet::NoteCandidates(), TryConstructorInitialization(), TryRefInitWithConversionFunction(), and TryUserDefinedConversion().
The documentation for this class was generated from the following files:
include/clang/Sema/Overload.h
lib/Sema/SemaOverload.cpp