clang: clang::dataflow::AggregateStorageLocation Class Reference
clang::dataflow::AggregateStorageLocation Class Reference final
A storage location which is subdivided into smaller storage locations that can be traced independently by abstract interpretation.
#include "clang/Analysis/FlowSensitive/StorageLocation.h"
Public Types
using FieldToLoc = llvm::DenseMap<const ValueDecl *, StorageLocation *>
Public Types inherited from clang::dataflow::StorageLocation
enum class Kind { Scalar , Aggregate }
Public Member Functions
AggregateStorageLocation (QualType Type)
AggregateStorageLocation (QualType Type, FieldToLoc TheChildren)
StorageLocation * getChild (const ValueDecl &D) const
Returns the child storage location for D.
void setChild (const ValueDecl &D, StorageLocation *Loc)
Changes the child storage location for a field D of reference type.
llvm::iterator_range< FieldToLoc::const_iterator > children () const
Public Member Functions inherited from clang::dataflow::StorageLocation
StorageLocation (Kind LocKind, QualType Type)
StorageLocation (const StorageLocation &)=delete
StorageLocation & operator= (const StorageLocation &)=delete
virtual ~StorageLocation ()=default
Kind getKind () const
QualType getType () const
Static Public Member Functions
static bool classof (const StorageLocation *Loc)
Detailed Description
A storage location which is subdivided into smaller storage locations that can be traced independently by abstract interpretation.
For example: a struct with public members. The child map is flat, so when used for a struct or class type, all accessible members of base struct and class types are directly accesible as children of this location.
The storage location for a field of reference type may be null. This typically occurs in one of two situations:
The record has not been fully initialized.
The maximum depth for modelling a self-referential data structure has been reached. Storage locations for fields of all other types must be non-null.
FIXME: Currently, the storage location of unions is modelled the same way as that of structs or classes. Eventually, we need to change this modelling so that all of the members of a given union have the same storage location.
Definition at line 85 of file StorageLocation.h.
Member Typedef Documentation
FieldToLoc
using clang::dataflow::AggregateStorageLocation::FieldToLoc = llvm::DenseMap<const ValueDecl *, StorageLocation *>
Definition at line 87 of file StorageLocation.h.
Constructor & Destructor Documentation
AggregateStorageLocation() [1/2]
clang::dataflow::AggregateStorageLocation::AggregateStorageLocation (QualType Type) inline explicit
Definition at line 89 of file StorageLocation.h.
AggregateStorageLocation() [2/2]
clang::dataflow::AggregateStorageLocation::AggregateStorageLocation (QualType Type, FieldToLoc TheChildren) inline
Definition at line 92 of file StorageLocation.h.
References clang::Type::isRecordType().
Member Function Documentation
children()
llvm::iterator_range< FieldToLoc::const_iterator > clang::dataflow::AggregateStorageLocation::children () const inline
Definition at line 146 of file StorageLocation.h.
Referenced by clang::dataflow::copyRecord(), and clang::dataflow::recordsEqual().
classof()
static bool clang::dataflow::AggregateStorageLocation::classof (const StorageLocation * Loc) inline static
Definition at line 106 of file StorageLocation.h.
References clang::dataflow::StorageLocation::Aggregate, and clang::dataflow::StorageLocation::getKind().
getChild()
StorageLocation * clang::dataflow::AggregateStorageLocation::getChild (const ValueDecl & D) const inline
Returns the child storage location for D.
May return null if D has reference type; guaranteed to return non-null in all other cases.
Note that it is an error to call this with a field that does not exist. The function does not return null in this case.
Definition at line 117 of file StorageLocation.h.
References clang::NamedDecl::getNameAsString(), and clang::dataflow::StorageLocation::getType().
Referenced by clang::dataflow::builtinTransferInitializer(), clang::dataflow::copyRecord(), clang::dataflow::getChild(), and clang::dataflow::recordsEqual().
setChild()
void clang::dataflow::AggregateStorageLocation::setChild (const ValueDecl & D, StorageLocation * Loc) inline
Changes the child storage location for a field D of reference type.
All other fields cannot change their storage location and always retain the storage location passed to the AggregateStorageLocation constructor.
Requirements:
D must have reference type.
Definition at line 141 of file StorageLocation.h.
References clang::ValueDecl::getType(), and clang::Type::isReferenceType().
Referenced by clang::dataflow::builtinTransferInitializer(), and clang::dataflow::copyRecord().
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/StorageLocation.h