clang: clang::threadSafety::til::Terminator Class Reference
clang::threadSafety::til::Terminator Class Reference
Base class for basic block terminators: Branch, Goto, and Return.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
ArrayRef< BasicBlock * > successors ()
Return the list of basic blocks that this terminator can branch to.
ArrayRef< BasicBlock * > successors () const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Protected Member Functions
Terminator (TIL_Opcode Op)
Terminator (const SExpr &E)
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Additional Inherited Members
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Base class for basic block terminators: Branch, Goto, and Return.
Definition at line 1355 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Terminator() [1/2]
clang::threadSafety::til::Terminator::Terminator (TIL_Opcode Op) inline protected
Definition at line 1357 of file ThreadSafetyTIL.h.
Terminator() [2/2]
clang::threadSafety::til::Terminator::Terminator (const SExpr & E) inline protected
Definition at line 1358 of file ThreadSafetyTIL.h.
Member Function Documentation
classof()
static bool clang::threadSafety::til::Terminator::classof (const SExpr * E) inline static
Definition at line 1361 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
successors() [1/2]
ArrayRef< BasicBlock * > clang::threadSafety::til::Terminator::successors () inline
Return the list of basic blocks that this terminator can branch to.
Definition at line 1493 of file ThreadSafetyTIL.h.
References clang::cast(), and clang::threadSafety::til::SExpr::opcode().
Referenced by clang::threadSafety::til::BasicBlock::successors(), clang::threadSafety::til::BasicBlock::successors(), and successors().
successors() [2/2]
ArrayRef< BasicBlock * > clang::threadSafety::til::Terminator::successors () const inline
Definition at line 1368 of file ThreadSafetyTIL.h.
References successors().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h