clang: clang::ento::CallEventRef< T > Class Template Reference
clang::ento::CallEventRef< T > Class Template Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
CallEventRef (const T *Call)
CallEventRef (const CallEventRef &Orig)
CallEventRef & operator= (const CallEventRef &)=delete
CallEventRef< T > cloneWithState (ProgramStateRef State) const
template<typename SuperT >
operator CallEventRef< SuperT > () const
Detailed Description
template<typename T = CallEvent>
class clang::ento::CallEventRef< T >
Definition at line 82 of file CallEvent.h.
Constructor & Destructor Documentation
CallEventRef() [1/2]
template<typename T = CallEvent> clang::ento::CallEventRef< T >::CallEventRef (const T * Call) inline
Definition at line 84 of file CallEvent.h.
CallEventRef() [2/2]
template<typename T = CallEvent> clang::ento::CallEventRef< T >::CallEventRef (const CallEventRef< T > & Orig) inline
Definition at line 85 of file CallEvent.h.
Member Function Documentation
cloneWithState()
template<typename T = CallEvent> CallEventRef< T > clang::ento::CallEventRef< T >::cloneWithState (ProgramStateRef State) const inline
Definition at line 91 of file CallEvent.h.
References clang::ento::CallEventRef< T >::cloneWithState().
Referenced by clang::ento::CallEventRef< T >::cloneWithState(), and clang::ento::ExprEngine::VisitObjCMessage().
operator CallEventRef< SuperT >()
template<typename T = CallEvent> template<typename SuperT > clang::ento::CallEventRef< T >::operator CallEventRef< SuperT > () const inline
Definition at line 98 of file CallEvent.h.
operator=()
template<typename T = CallEvent> CallEventRef & clang::ento::CallEventRef< T >::operator= (const CallEventRef< T > &) delete
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h