clang: clang::arcmt::trans::BlockObjCVariableTraverser Class Reference
clang::arcmt::trans::BlockObjCVariableTraverser Class Reference
#include "/root/llvm-project/clang/lib/ARCMigrate/Transforms.h"
Public Member Functions
void traverseBody (BodyContext &BodyCtx) override
Public Member Functions inherited from clang::arcmt::trans::ASTTraverser
virtual ~ASTTraverser ()
virtual void traverseTU (MigrationContext &MigrateCtx)
virtual void traverseObjCImplementation (ObjCImplementationContext &ImplCtx)
Detailed Description
Definition at line 132 of file Transforms.h.
Member Function Documentation
traverseBody()
void BlockObjCVariableTraverser::traverseBody (BodyContext & BodyCtx) override virtual
Reimplemented from clang::arcmt::trans::ASTTraverser.
Definition at line 126 of file TransBlockObjCVariable.cpp.
References clang::ast_matchers::attr, clang::arcmt::trans::canApplyWeak(), clang::arcmt::MigrationPass::Ctx, clang::Decl::getAttr(), clang::arcmt::trans::BodyContext::getMigrationContext(), clang::ASTContext::getSourceManager(), clang::arcmt::trans::BodyContext::getTopStmt(), clang::ValueDecl::getType(), clang::arcmt::trans::MigrationContext::Pass, clang::arcmt::TransformActions::replaceText(), SM, and clang::arcmt::MigrationPass::TA.
The documentation for this class was generated from the following files:
lib/ARCMigrate/Transforms.h
lib/ARCMigrate/TransBlockObjCVariable.cpp