clang: clang::ActionResult< PtrTy, CompressInvalid > Class Template Reference
clang::ActionResult< PtrTy, CompressInvalid > Class Template Reference
ActionResult - This structure is used while parsing/acting on expressions, stmts, etc.
#include "clang/Sema/Ownership.h"
Public Member Functions
ActionResult (bool Invalid=false)
ActionResult (PtrTy val)
ActionResult (const DiagnosticBuilder &)
ActionResult (const void *)=delete
ActionResult (volatile void *)=delete
bool isInvalid () const
bool isUsable () const
bool isUnset () const
PtrTy get () const
template<typename T >
T * getAs ()
void set (PtrTy V)
const ActionResult & operator= (PtrTy RHS)
Detailed Description
template<class PtrTy, bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value>
class clang::ActionResult< PtrTy, CompressInvalid >
ActionResult - This structure is used while parsing/acting on expressions, stmts, etc.
It encapsulates both the object returned by the action, plus a sense of whether or not it is valid. When CompressInvalid is true, the "invalid" flag will be stored in the low bit of the Val pointer.
Definition at line 152 of file Ownership.h.
Constructor & Destructor Documentation
ActionResult() [1/5]
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> clang::ActionResult< PtrTy, CompressInvalid >::ActionResult (bool Invalid = false) inline
Definition at line 157 of file Ownership.h.
ActionResult() [2/5]
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> clang::ActionResult< PtrTy, CompressInvalid >::ActionResult (PtrTy val) inline
Definition at line 158 of file Ownership.h.
ActionResult() [3/5]
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> clang::ActionResult< PtrTy, CompressInvalid >::ActionResult (const DiagnosticBuilder &) inline
Definition at line 159 of file Ownership.h.
ActionResult() [4/5]
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> clang::ActionResult< PtrTy, CompressInvalid >::ActionResult (const void *) delete
ActionResult() [5/5]
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> clang::ActionResult< PtrTy, CompressInvalid >::ActionResult (volatile void *) delete
Member Function Documentation
get()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> PtrTy clang::ActionResult< PtrTy, CompressInvalid >::get () const inline
Definition at line 169 of file Ownership.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCaseStmt(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnCoawaitExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnConditionVariable(), clang::Sema::ActOnConstantExpression(), clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCoyieldExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXForRangeStmt(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnDecltypeExpression(), clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnDoStmt(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExprStmt(), clang::Sema::ActOnForEachLValueExpr(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnIvar(), clang::Sema::ActOnMemberAccessExpr(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPIteratorExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAlignClause(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPAllocateClause(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnOpenMPCollapseClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPFinalClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPHasDeviceAddrClause(), clang::Sema::ActOnOpenMPHintClause(), clang::Sema::ActOnOpenMPIfClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPNocontextClause(), clang::Sema::ActOnOpenMPNovariantsClause(), clang::Sema::ActOnOpenMPOrderedClause(), clang::Sema::ActOnOpenMPPartialClause(), clang::Sema::ActOnOpenMPRegionEnd(), clang::Sema::ActOnOpenMPSafelenClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPSimdlenClause(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::Sema::ActOnOpenMPUseDeviceAddrClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnRequiresClause(), clang::Sema::ActOnReturnStmt(), clang::Sema::ActOnStmtExprResult(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::ActOnTag(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignValueAttr(), clang::Sema::AddInitializerToDecl(), clang::AssertSuccess(), clang::AssertSuccess(), clang::Sema::AttachTypeConstraint(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBinOp(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinCallExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), buildCapture(), buildCaptureDecl(), buildCoawaitCalls(), clang::Sema::BuildCoreturnStmt(), buildCoroutineHandle(), clang::Sema::buildCoroutineParameterMoves(), clang::Sema::buildCoroutinePromise(), buildCounterInit(), buildCounterUpdate(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXDefaultArgExpr(), clang::Sema::BuildCXXDefaultInitExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXNoexceptExpr(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildExprRequirement(), clang::Sema::BuildForRangeBeginEndCall(), BuildImplicitBaseInitializer(), BuildImplicitMemberInitializer(), clang::Sema::BuildInitList(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildIvarRefExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildMemberInitializer(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemberReferenceExpr(), buildMemcpyForAssignmentOp(), clang::Sema::BuildMemInitializer(), BuildNonArrayForRange(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCNumericLiteral(), buildOperatorCoawaitCall(), clang::Sema::BuildOverloadedArrowExpr(), buildPostUpdate(), buildPromiseCall(), BuildRecoveryCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildStaticAssertDeclaration(), buildStdNoThrowDeclRef(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::BuildUnresolvedCoawaitExpr(), calculateConstraintSatisfaction(), calculateConstraintSatisfaction(), clang::Sema::CallExprUnaryConversions(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), CastForMoving(), castForMoving(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAddressOfOperand(), checkArgsForPlaceholders(), checkArithmeticNull(), checkArithmeticOrEnumeralCompare(), checkArithmeticOrEnumeralThreeWayCompare(), checkArrayLikeDecomposition(), CheckArrow(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckBooleanCondition(), checkBuiltinArgument(), checkCastFunctionType(), CheckCommaOperands(), clang::Sema::CheckCompareOperands(), checkConditionalBlockPointerCompatibility(), checkConditionalNullPointer(), checkConditionalObjectPointersCompatibility(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), CheckConstraintSatisfaction(), clang::Sema::CheckConversionToObjCLiteral(), clang::Sema::CheckCXXBooleanCondition(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckForImmediateInvocation(), checkFunctionConditionAttr(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), clang::Sema::CheckLogicalOperands(), checkMappableExpressionList(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), checkMemberDecomposition(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckObjCBridgeRelatedConversions(), clang::Sema::CheckObjCForCollectionOperand(), checkObjCPointerIntrospection(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPIterationSpace(), checkOpenMPLoop(), clang::Sema::CheckPlaceholderExpr(), checkPlaceholderForOverload(), checkPointerIntegerMismatch(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::CheckPtrComparisonWithNullChar(), CheckRealImagOperand(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), checkSimpleDecomposition(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorCompareOperands(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckSwitchCondition(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTransparentUnionArgumentConstraints(), checkTupleLikeDecomposition(), clang::Sema::checkUnknownAnyArg(), clang::Sema::checkUnknownAnyCast(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorLogicalOperands(), clang::Sema::CheckVectorOperands(), checkVectorShift(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCSuperMessage(), clang::Sema::CodeCompletePostfixExpression(), CollectFieldInitializer(), collectPlacementArgs(), clang::Sema::ConstantFoldAttrArgs(), ConstructTransparentUnion(), convertArgsForAvailabilityChecks(), ConvertForConditional(), convertHalfVecBinOp(), convertPointersToCompositeType(), CopyObject(), CorrectDelayedTyposInBinOp(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::CStyleCastPtrExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceAutoType(), DeduceNullPtrTemplateArgument(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitMoveAssignment(), DiagnoseBadDivideOrRemainderValues(), DiagnoseBadFunctionCast(), DiagnoseBadShiftValues(), DiagnoseCallingConvCast(), DiagnoseCastOfObjCSEL(), DiagnoseCastQual(), diagnoseDistinctPointerComparison(), diagnoseFunctionPointerToVoidComparison(), diagnoseLogicalNotOnLHSofCheck(), diagnoseObjCLiteralComparison(), clang::Sema::DiagnoseUnknownTypeName(), diagnoseXorMisusedAsPow(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), clang::Sema::FindCompositePointerType(), FindConditionalOverload(), findOMPAllocatorHandleT(), FinishForRangeVarDecl(), FinishOpenMPLinearClause(), clang::Sema::FixOverloadedFunctionReference(), formImmediatelyDeclaredConstraint(), clang::Sema::GatherArgumentsForCall(), clang::ActionResult< PtrTy, CompressInvalid >::getAs(), clang::ActionResult< PtrTy, true >::getAs(), clang::Sema::ImplicitExceptionSpecification::getExceptionSpec(), clang::DeclaratorChunk::getFunction(), getGenericLambdaTemplateParameterList(), clang::Sema::getOpenMPCapturedExpr(), clang::Sema::getTypeName(), handleComplexFloatConversion(), handleComplexIntConversion(), handleFloatConversion(), handleIntegerConversion(), handleIntegerToComplexFloatConversion(), handleIntToFloatConversion(), clang::Sema::IgnoredValueConversions(), clang::Sema::ImpCastExprToType(), clang::InitializationSequence::InitializeFrom(), clang::Sema::InstantiateClassTemplateSpecialization(), instantiateDependentFunctionAttrCondition(), instantiateExplicitSpecifier(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::InstantiateInClassInitializer(), clang::Sema::InstantiateMemInitializers(), instantiateOMPDeclareSimdDeclAttr(), instantiateOMPDeclareVariantAttr(), clang::Sema::InvalidLogicalVectorOperands(), clang::Sema::InvalidOperands(), isNullPointerValueTemplateArgument(), isObjCObjectLiteral(), isTupleLike(), clang::Sema::LookupInObjCMethod(), LookupMemberExpr(), clang::Sema::MakeFullDiscardedValueExpr(), clang::Sema::MaybeCreateExprWithCleanups(), clang::Sema::maybeExtendBlockObject(), maybeTailCall(), clang::Sema::mightBeIntendedToBeTemplateName(), OpenCLArithmeticConversions(), OpenCLCheckVectorConditional(), OpenCLConvertScalarsToVectors(), clang::Parser::ParseConstraintExpression(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::Parser::ParseConstraintLogicalOrExpression(), clang::Parser::ParseOpenMPParensExpr(), clang::Parser::ParseOpenMPVarList(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PrepareCastToObjCObjectPointer(), clang::Sema::PrepareScalarCast(), clang::Sema::prepareVectorSplat(), processImplicitMapsWithDefaultMappers(), clang::TreeTransform< Derived >::RebuildCoawaitExpr(), RebuildForRangeWithDereference(), clang::TreeTransform< Derived >::RebuildMemberExpr(), clang::TreeTransform< Derived >::RebuildObjCForCollectionStmt(), rebuildPotentialResultsAsNonOdrUsed(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), RemoveNestedImmediateInvocation(), clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), rewriteBuiltinFunctionDecl(), SemaBuiltinAddressof(), SemaBuiltinAlignment(), SemaBuiltinCallWithStaticChain(), SemaBuiltinDumpStruct(), SemaBuiltinFunctionStart(), SemaBuiltinLaunder(), SemaBuiltinOverflow(), clang::Sema::SetIvarInitializers(), clang::DeclSpec::SetTypeSpecType(), ShouldTryAgainWithRedefinitionType(), SubstituteConstraintExpression(), clang::TreeTransform< Derived >::TransformCondition(), clang::TreeTransform< Derived >::TransformCXXNamedCastExpr(), clang::TreeTransform< Derived >::TransformExceptionSpec(), clang::TreeTransform< Derived >::TransformExprRequirement(), clang::TreeTransform< Derived >::TransformExprs(), clang::TreeTransform< Derived >::TransformNestedRequirement(), clang::TreeTransform< Derived >::TransformOMPExecutableDirective(), clang::transformOMPMappableExprListClause(), clang::TreeTransform< Derived >::TransformParenDependentScopeDeclRefExpr(), clang::TreeTransform< Derived >::TransformTemplateArgument(), TryAddressSpaceCast(), clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(), TryConstCast(), clang::Sema::tryExprAsCall(), TryOrBuildParenListInitialization(), TryReinterpretCast(), clang::Sema::tryResolveExplicitSpecifier(), TryStaticCast(), TryStaticImplicitCast(), TryStaticMemberPointerUpcast(), clang::Sema::tryToRecoverWithCall(), tryVectorConvertAndSplat(), clang::Sema::UsualArithmeticConversions(), clang::Sema::UsualUnaryConversions(), clang::Sema::VerifyBitField(), clang::Sema::VerifyIntegerConstantExpression(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getAs()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> template<typename T > T * clang::ActionResult< PtrTy, CompressInvalid >::getAs () inline
Definition at line 170 of file Ownership.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get().
Referenced by clang::Sema::ActOnExprStmt(), clang::Sema::ActOnForStmt(), clang::Sema::ActOnIdExpression(), actOnOMPReductionKindClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildExceptionDeclaration(), BuildImplicitBaseInitializer(), BuildImplicitMemberInitializer(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildReturnStmt(), buildSingleCopyAssignRecursively(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CheckTemplateArgumentList(), CopyObject(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::GatherArgumentsForCall(), clang::Sema::getTrivialTemplateArgumentLoc(), instantiateDependentAMDGPUWavesPerEUAttr(), instantiateDependentCUDALaunchBoundsAttr(), makeLaunchBoundsArgExpr(), clang::InitializationSequence::Perform(), PrepareArgumentsForCallToObjectOfClassType(), clang::Sema::SetIvarInitializers(), and clang::Sema::SubstDefaultTemplateArgumentIfAvailable().
isInvalid()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> bool clang::ActionResult< PtrTy, CompressInvalid >::isInvalid () const inline
Definition at line 165 of file Ownership.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCaseStmt(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnCoawaitExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnConditionVariable(), clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCoyieldExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXForRangeStmt(), clang::Sema::ActOnDecltypeExpression(), clang::Sema::ActOnDoStmt(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExprStmt(), clang::Sema::ActOnForEachLValueExpr(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnMemberAccessExpr(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOMPArraySectionExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAlignClause(), clang::Sema::ActOnOpenMPAlignedClause(), clang::Sema::ActOnOpenMPAllocateClause(), clang::Sema::ActOnOpenMPCollapseClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFinalClause(), clang::Sema::ActOnOpenMPHintClause(), clang::Sema::ActOnOpenMPIfClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPNocontextClause(), clang::Sema::ActOnOpenMPNovariantsClause(), clang::Sema::ActOnOpenMPOrderedClause(), clang::Sema::ActOnOpenMPPartialClause(), clang::Sema::ActOnOpenMPSafelenClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPSimdlenClause(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnRequiresClause(), clang::Sema::ActOnReturnStmt(), clang::Sema::ActOnStmtExprResult(), clang::Sema::ActOnTag(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignValueAttr(), clang::Sema::AddInitializerToDecl(), clang::AssertSuccess(), clang::AssertSuccess(), clang::Sema::AttachTypeConstraint(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildArrayType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBinOp(), clang::Sema::BuildBitIntType(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), buildCoawaitCalls(), clang::Sema::BuildCoreturnStmt(), buildCoroutineHandle(), clang::Sema::buildCoroutineParameterMoves(), clang::Sema::buildCoroutinePromise(), buildCounterUpdate(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXDefaultArgExpr(), clang::Sema::BuildCXXDefaultInitExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXNoexceptExpr(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildExprRequirement(), clang::Sema::BuildForRangeBeginEndCall(), BuildImplicitBaseInitializer(), BuildImplicitMemberInitializer(), clang::Sema::BuildInitList(), clang::Sema::BuildIvarRefExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildMemberInitializer(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemberReferenceExpr(), BuildNonArrayForRange(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCNumericLiteral(), buildOperatorCoawaitCall(), clang::Sema::BuildOverloadedArrowExpr(), buildPromiseCall(), BuildRecoveryCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildReturnStmt(), buildSingleCopyAssignRecursively(), clang::Sema::BuildStaticAssertDeclaration(), buildStdNoThrowDeclRef(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildUnresolvedCoawaitExpr(), calculateConstraintSatisfaction(), calculateConstraintSatisfaction(), clang::Sema::CallExprUnaryConversions(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAddressOfOperand(), checkArgsForPlaceholders(), checkArithmeticOrEnumeralCompare(), checkArithmeticOrEnumeralThreeWayCompare(), checkArrayLikeDecomposition(), CheckArrow(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckBooleanCondition(), checkBuiltinArgument(), CheckCommaOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), CheckConstraintSatisfaction(), clang::Sema::CheckCXXBooleanCondition(), clang::Sema::CheckEnumConstant(), checkFunctionConditionAttr(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), checkMappableExpressionList(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), checkMemberDecomposition(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckObjCForCollectionOperand(), checkPlaceholderForOverload(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::checkPseudoObjectAssignment(), CheckRealImagOperand(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), checkSimpleDecomposition(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckSwitchCondition(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgumentList(), checkTupleLikeDecomposition(), clang::Sema::checkUnknownAnyArg(), clang::Sema::CheckVectorOperands(), checkVectorShift(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteMemberReferenceExpr(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompletePostfixExpression(), CollectFieldInitializer(), collectPlacementArgs(), convertArgsForAvailabilityChecks(), CopyObject(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceAutoType(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitMoveAssignment(), DiagnoseCastQual(), EvaluateArrayTypeTrait(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::Sema::FindCompositePointerType(), FindConditionalOverload(), FinishOverloadedCallExpr(), formImmediatelyDeclaredConstraint(), clang::Sema::GatherArgumentsForCall(), clang::DeclaratorChunk::getFunction(), clang::Sema::IgnoredValueConversions(), clang::Sema::ImpCastExprToType(), clang::InitializationSequence::InitializeFrom(), clang::Sema::InstantiateClassTemplateSpecialization(), instantiateDependentFunctionAttrCondition(), instantiateExplicitSpecifier(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::InstantiateMemInitializers(), instantiateOMPDeclareSimdDeclAttr(), instantiateOMPDeclareVariantAttr(), isNullPointerValueTemplateArgument(), isTupleLike(), clang::Sema::LookupInObjCMethod(), LookupMemberExpr(), makeLaunchBoundsArgExpr(), clang::Sema::MaybeCreateExprWithCleanups(), maybeTailCall(), clang::Sema::mightBeIntendedToBeTemplateName(), OpenCLArithmeticConversions(), clang::Parser::ParseConstraintLogicalAndExpression(), parseDeclareSimdClauses(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), PrepareArgumentsForCallToObjectOfClassType(), clang::Sema::prepareVectorSplat(), processImplicitMapsWithDefaultMappers(), ProcessOpenMPDoacrossClauseCommon(), clang::TreeTransform< Derived >::RebuildCoawaitExpr(), RebuildForRangeWithDereference(), clang::TreeTransform< Derived >::RebuildMemberExpr(), clang::TreeTransform< Derived >::RebuildObjCForCollectionStmt(), rebuildPotentialResultsAsNonOdrUsed(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), rewriteBuiltinFunctionDecl(), SemaBuiltinAlignment(), SemaBuiltinCallWithStaticChain(), SemaBuiltinDumpStruct(), SemaBuiltinFunctionStart(), SemaBuiltinLaunder(), SemaBuiltinOverflow(), clang::Sema::SetIvarInitializers(), clang::DeclSpec::SetTypeSpecType(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), clang::TreeTransform< Derived >::TransformCondition(), clang::TreeTransform< Derived >::TransformCXXNamedCastExpr(), clang::TreeTransform< Derived >::TransformExceptionSpec(), clang::TreeTransform< Derived >::TransformExprRequirement(), clang::TreeTransform< Derived >::TransformExprs(), clang::TreeTransform< Derived >::TransformNestedRequirement(), clang::TreeTransform< Derived >::TransformOMPExecutableDirective(), clang::transformOMPMappableExprListClause(), clang::TreeTransform< Derived >::TransformTemplateArgument(), TryOrBuildParenListInitialization(), TryStaticCast(), clang::Sema::UsualArithmeticConversions(), clang::Sema::UsualUnaryConversions(), clang::Sema::VerifyBitField(), clang::Sema::VerifyIntegerConstantExpression(), and clang::Sema::VerifyPositiveIntegerConstantInClause().
isUnset()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> bool clang::ActionResult< PtrTy, CompressInvalid >::isUnset () const inline
Definition at line 167 of file Ownership.h.
Referenced by clang::Sema::ActOnCaseStmt(), actOnOMPReductionKindClause(), and clang::Sema::ActOnTag().
isUsable()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> bool clang::ActionResult< PtrTy, CompressInvalid >::isUsable () const inline
Definition at line 166 of file Ownership.h.
Referenced by clang::Sema::ActOnCastExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnConstantExpression(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnOMPIteratorExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAffinityClause(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPSizesClause(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::AddInitializerToDecl(), clang::Sema::AttachTypeConstraint(), clang::Sema::BuildArrayType(), clang::Sema::BuildBinOp(), clang::Sema::BuildBuiltinCallExpr(), buildCapture(), buildCaptureDecl(), buildCounterInit(), buildCounterUpdate(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildMemberReferenceExpr(), buildMemcpyForAssignmentOp(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildTemplateIdExpr(), calculateConstraintSatisfaction(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckForImmediateInvocation(), clang::Sema::CheckObjCForCollectionOperand(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPLoop(), clang::Sema::checkUnknownAnyCast(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateOverloadedBinOp(), findOMPAllocatorHandleT(), FinishForRangeVarDecl(), FinishOverloadedCallExpr(), clang::DeclaratorChunk::getFunction(), clang::Sema::getOpenMPCapturedExpr(), clang::Sema::InstantiateClassTemplateSpecialization(), instantiateOMPDeclareVariantAttr(), clang::Sema::LookupInObjCMethod(), clang::Parser::ParseConstraintExpression(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::Parser::ParseConstraintLogicalOrExpression(), parseDeclareSimdClauses(), clang::Parser::ParseOpenMPVarList(), rebuildPotentialResultsAsNonOdrUsed(), RemoveNestedImmediateInvocation(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), SubstituteConstraintExpression(), clang::TreeTransform< Derived >::TransformExprRequirement(), clang::TreeTransform< Derived >::TransformOMPExecutableDirective(), clang::TreeTransform< Derived >::TransformParenDependentScopeDeclRefExpr(), clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(), clang::Sema::tryExprAsCall(), TryReinterpretCast(), clang::Sema::tryResolveExplicitSpecifier(), TryStaticMemberPointerUpcast(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
operator=()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> const ActionResult & clang::ActionResult< PtrTy, CompressInvalid >::operator= (PtrTy RHS) inline
Definition at line 174 of file Ownership.h.
set()
template<class PtrTy , bool CompressInvalid = IsResultPtrLowBitFree<PtrTy>::value> void clang::ActionResult< PtrTy, CompressInvalid >::set (PtrTy V) inline
Definition at line 172 of file Ownership.h.
References V.
The documentation for this class was generated from the following file:
include/clang/Sema/Ownership.h