clang: clang::SelectorTable Class Reference
clang::SelectorTable Class Reference
This table allows us to fully hide how we implement multi-keyword caching.
#include "clang/Basic/IdentifierTable.h"
Public Member Functions
SelectorTable ()
SelectorTable (const SelectorTable &)=delete
SelectorTable & operator= (const SelectorTable &)=delete
~SelectorTable ()
Selector getSelector (unsigned NumArgs, IdentifierInfo **IIV)
Can create any sort of selector.
Selector getUnarySelector (IdentifierInfo *ID)
Selector getNullarySelector (IdentifierInfo *ID)
size_t getTotalMemory () const
Return the total amount of memory allocated for managing selectors.
Static Public Member Functions
static SmallString< 64 > constructSetterName (StringRef Name)
Return the default setter name for the given identifier.
static Selector constructSetterSelector (IdentifierTable &Idents, SelectorTable &SelTable, const IdentifierInfo *Name)
Return the default setter selector for the given identifier.
static std::string getPropertyNameFromSetterSelector (Selector Sel)
Return the property name for the given setter selector.
Detailed Description
This table allows us to fully hide how we implement multi-keyword caching.
Definition at line 946 of file IdentifierTable.h.
Constructor & Destructor Documentation
SelectorTable() [1/2]
SelectorTable::SelectorTable ()
Definition at line 836 of file IdentifierTable.cpp.
SelectorTable() [2/2]
clang::SelectorTable::SelectorTable (const SelectorTable &) delete
~SelectorTable()
SelectorTable::~SelectorTable ()
Definition at line 840 of file IdentifierTable.cpp.
References getSelectorTableImpl().
Member Function Documentation
constructSetterName()
SmallString< 64 > SelectorTable::constructSetterName (StringRef Name) static
Return the default setter name for the given identifier.
This is "set" + Name where the initial character of Name has been capitalized.
Definition at line 783 of file IdentifierTable.cpp.
References clang::toUppercase().
Referenced by constructSetterSelector(), and hasDefaultSetterName().
constructSetterSelector()
Selector SelectorTable::constructSetterSelector (IdentifierTable & Idents, SelectorTable & SelTable, const IdentifierInfo * Name) static
Return the default setter selector for the given identifier.
This is "set" + Name where the initial character of Name has been capitalized.
Definition at line 791 of file IdentifierTable.cpp.
References constructSetterName(), clang::IdentifierTable::get(), and getUnarySelector().
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::HandleExprPropertyRefExpr(), and LookupMemberExpr().
getNullarySelector()
Selector clang::SelectorTable::getNullarySelector (IdentifierInfo * ID) inline
Definition at line 966 of file IdentifierTable.h.
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), AddObjCKeyValueCompletions(), clang::Sema::checkObjCBridgeRelatedComponents(), cleanupDeallocOrFinalize(), GCRewriteFinalize(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSDictionarySelector(), clang::Sema::HandleExprPropertyRefExpr(), LookupMemberExpr(), and clang::serialization::reader::ASTSelectorLookupTrait::ReadKey().
getPropertyNameFromSetterSelector()
std::string SelectorTable::getPropertyNameFromSetterSelector (Selector Sel) static
Return the property name for the given setter selector.
Definition at line 799 of file IdentifierTable.cpp.
References clang::Selector::getNameForSlot(), and clang::toLowercase().
getSelector()
Selector SelectorTable::getSelector (unsigned NumArgs, IdentifierInfo ** IIV)
Can create any sort of selector.
NumArgs indicates whether this is a no argument selector "foo", a single argument selector "foo:" or multi-argument "foo:bar:".
Definition at line 810 of file IdentifierTable.cpp.
References getSelectorTableImpl(), and clang::MultiKeywordSelector::Profile().
Referenced by AddObjCKeyValueCompletions(), clang::Sema::BuildObjCBoxedExpr(), CheckKeyForObjCARCConversion(), clang::Sema::CheckObjCForCollectionOperand(), CheckProtocolMethodDefs(), clang::getKeywordSelector(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSDictionarySelector(), clang::NSAPI::getNSSetSelector(), clang::NSAPI::getNSStringSelector(), clang::GetNullarySelector(), clang::GetUnarySelector(), clang::ASTImporter::Import(), and clang::serialization::reader::ASTSelectorLookupTrait::ReadKey().
getTotalMemory()
size_t SelectorTable::getTotalMemory () const
Return the total amount of memory allocated for managing selectors.
Definition at line 805 of file IdentifierTable.cpp.
References getSelectorTableImpl().
getUnarySelector()
Selector clang::SelectorTable::getUnarySelector (IdentifierInfo * ID) inline
Definition at line 962 of file IdentifierTable.h.
Referenced by clang::Sema::ActOnInstanceMessage(), AddObjCKeyValueCompletions(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::checkObjCBridgeRelatedComponents(), constructSetterSelector(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSDictionarySelector(), clang::NSAPI::getNSNumberLiteralSelector(), clang::NSAPI::getNSSetSelector(), clang::NSAPI::getNSStringSelector(), and clang::serialization::reader::ASTSelectorLookupTrait::ReadKey().
operator=()
SelectorTable & clang::SelectorTable::operator= (const SelectorTable &) delete
The documentation for this class was generated from the following files:
include/clang/Basic/IdentifierTable.h
lib/Basic/IdentifierTable.cpp