clang: clang::ObjCInterfaceDecl Class Reference
clang::ObjCInterfaceDecl Class Reference
Represents an ObjC class declaration.
#include "clang/AST/DeclObjC.h"
Classes
class filtered_category_iterator
Iterator that walks over the list of categories, filtering out those that do not meet specific criteria.
Public Types
using protocol_iterator = ObjCProtocolList::iterator
using protocol_range = llvm::iterator_range<protocol_iterator>
using protocol_loc_iterator = ObjCProtocolList::loc_iterator
using protocol_loc_range = llvm::iterator_range<protocol_loc_iterator>
using all_protocol_iterator = ObjCList<ObjCProtocolDecl>::iterator
using all_protocol_range = llvm::iterator_range<all_protocol_iterator>
using ivar_iterator = specific_decl_iterator<ObjCIvarDecl>
using ivar_range = llvm::iterator_range<specific_decl_iterator<ObjCIvarDecl>>
using visible_categories_iterator
Iterator that walks over the list of categories and extensions that are visible, i.e., not hidden in a non-imported submodule.
using visible_categories_range
using known_categories_iterator = filtered_category_iterator<isKnownCategory>
Iterator that walks over all of the known categories and extensions, including those that are hidden.
using known_categories_range
using visible_extensions_iterator
Iterator that walks over all of the visible extensions, skipping any that are known but hidden.
using visible_extensions_range
using known_extensions_iterator
Iterator that walks over all of the known extensions.
using known_extensions_range
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
Public Types inherited from clang::ObjCContainerDecl
using prop_iterator = specific_decl_iterator<ObjCPropertyDecl>
using prop_range
using instprop_iterator
using instprop_range = llvm::iterator_range<instprop_iterator>
using classprop_iterator
using classprop_range = llvm::iterator_range<classprop_iterator>
using method_iterator = specific_decl_iterator<ObjCMethodDecl>
using method_range
using instmeth_iterator
using instmeth_range = llvm::iterator_range<instmeth_iterator>
using classmeth_iterator
using classmeth_range = llvm::iterator_range<classmeth_iterator>
using PropertyMap
using ProtocolPropertySet = llvm::SmallDenseSet<const ObjCProtocolDecl *, 8>
using PropertyDeclOrder = llvm::SmallVector<ObjCPropertyDecl *, 8>
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Types inherited from clang::DeclContext
using decl_range = llvm::iterator_range<decl_iterator>
using lookup_result = DeclContextLookupResult
using lookup_iterator = lookup_result::iterator
using lookups_range = llvm::iterator_range<all_lookups_iterator>
using udir_iterator_base
using udir_range = llvm::iterator_range<udir_iterator>
using ddiag_range = llvm::iterator_range<DeclContext::ddiag_iterator>
Public Types inherited from clang::Redeclarable< ObjCInterfaceDecl >
using redecl_range
Public Member Functions
ObjCTypeParamList * getTypeParamList () const
Retrieve the type parameters of this class.
void setTypeParamList (ObjCTypeParamList *TPL)
Set the type parameters of this class.
ObjCTypeParamList * getTypeParamListAsWritten () const
Retrieve the type parameters written on this particular declaration of the class.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
void setExternallyCompleted ()
Indicate that this Objective-C class is complete, but that the external AST source will be responsible for filling in its contents when a complete class is required.
void setHasDesignatedInitializers ()
Indicate that this interface decl contains at least one initializer marked with the 'objc_designated_initializer' attribute.
bool hasDesignatedInitializers () const
Returns true if this interface decl contains at least one initializer marked with the 'objc_designated_initializer' attribute.
bool declaresOrInheritsDesignatedInitializers () const
Returns true if this interface decl declares a designated initializer or it inherites one from its super class.
const ObjCProtocolList & getReferencedProtocols () const
ObjCImplementationDecl * getImplementation () const
void setImplementation (ObjCImplementationDecl *ImplD)
ObjCCategoryDecl * FindCategoryDeclaration (IdentifierInfo *CategoryId) const
FindCategoryDeclaration - Finds category declaration in the list of categories for this class and returns it.
ObjCMethodDecl * getCategoryInstanceMethod (Selector Sel) const
ObjCMethodDecl * getCategoryClassMethod (Selector Sel) const
ObjCMethodDecl * getCategoryMethod (Selector Sel, bool isInstance) const
protocol_range protocols () const
protocol_iterator protocol_begin () const
protocol_iterator protocol_end () const
protocol_loc_range protocol_locs () const
protocol_loc_iterator protocol_loc_begin () const
protocol_loc_iterator protocol_loc_end () const
all_protocol_range all_referenced_protocols () const
all_protocol_iterator all_referenced_protocol_begin () const
all_protocol_iterator all_referenced_protocol_end () const
ivar_range ivars () const
ivar_iterator ivar_begin () const
ivar_iterator ivar_end () const
unsigned ivar_size () const
bool ivar_empty () const
ObjCIvarDecl * all_declared_ivar_begin ()
all_declared_ivar_begin - return first ivar declared in this class, its extensions and its implementation.
const ObjCIvarDecl * all_declared_ivar_begin () const
void setIvarList (ObjCIvarDecl *ivar)
void setProtocolList (ObjCProtocolDecl *const *List, unsigned Num, const SourceLocation *Locs, ASTContext &C)
setProtocolList - Set the list of protocols that this interface implements.
void mergeClassExtensionProtocolList (ObjCProtocolDecl *const *List, unsigned Num, ASTContext &C)
mergeClassExtensionProtocolList - Merge class extension's protocol list into the protocol list for this class.
StringRef getObjCRuntimeNameAsString () const
Produce a name to be used for class's metadata.
void getDesignatedInitializers (llvm::SmallVectorImpl< const ObjCMethodDecl * > &Methods) const
Returns the designated initializers for the interface.
bool isDesignatedInitializer (Selector Sel, const ObjCMethodDecl **InitMethod=nullptr) const
Returns true if the given selector is a designated initializer for the interface.
bool isThisDeclarationADefinition () const
Determine whether this particular declaration of this class is actually also a definition.
bool hasDefinition () const
Determine whether this class has been defined.
ObjCInterfaceDecl * getDefinition ()
Retrieve the definition of this class, or NULL if this class has been forward-declared (with @class) but not yet defined (with @interface).
const ObjCInterfaceDecl * getDefinition () const
Retrieve the definition of this class, or NULL if this class has been forward-declared (with @class) but not yet defined (with @interface).
void startDefinition ()
Starts the definition of this Objective-C class, taking it from a forward declaration (@class) to a definition (@interface).
void startDuplicateDefinitionForComparison ()
Starts the definition without sharing it with other redeclarations.
void mergeDuplicateDefinitionWithCommon (const ObjCInterfaceDecl *Definition)
const ObjCObjectType * getSuperClassType () const
Retrieve the superclass type.
TypeSourceInfo * getSuperClassTInfo () const
ObjCInterfaceDecl * getSuperClass () const
void setSuperClass (TypeSourceInfo *superClass)
visible_categories_range visible_categories () const
visible_categories_iterator visible_categories_begin () const
Retrieve an iterator to the beginning of the visible-categories list.
visible_categories_iterator visible_categories_end () const
Retrieve an iterator to the end of the visible-categories list.
bool visible_categories_empty () const
Determine whether the visible-categories list is empty.
known_categories_range known_categories () const
known_categories_iterator known_categories_begin () const
Retrieve an iterator to the beginning of the known-categories list.
known_categories_iterator known_categories_end () const
Retrieve an iterator to the end of the known-categories list.
bool known_categories_empty () const
Determine whether the known-categories list is empty.
visible_extensions_range visible_extensions () const
visible_extensions_iterator visible_extensions_begin () const
Retrieve an iterator to the beginning of the visible-extensions list.
visible_extensions_iterator visible_extensions_end () const
Retrieve an iterator to the end of the visible-extensions list.
bool visible_extensions_empty () const
Determine whether the visible-extensions list is empty.
known_extensions_range known_extensions () const
known_extensions_iterator known_extensions_begin () const
Retrieve an iterator to the beginning of the known-extensions list.
known_extensions_iterator known_extensions_end () const
Retrieve an iterator to the end of the known-extensions list.
bool known_extensions_empty () const
Determine whether the known-extensions list is empty.
ObjCCategoryDecl * getCategoryListRaw () const
Retrieve the raw pointer to the start of the category/extension list.
void setCategoryListRaw (ObjCCategoryDecl *category)
Set the raw pointer to the start of the category/extension list.
ObjCPropertyDecl * FindPropertyVisibleInPrimaryClass (IdentifierInfo *PropertyId, ObjCPropertyQueryKind QueryKind) const
FindPropertyVisibleInPrimaryClass - Finds declaration of the property with name 'PropertyId' in the primary class; including those in protocols (direct or indirect) used by the primary class.
void collectPropertiesToImplement (PropertyMap &PM) const override
This routine collects list of properties to be implemented in the class.
bool isSuperClassOf (const ObjCInterfaceDecl *I) const
isSuperClassOf - Return true if this class is the specified class or is a super class of the specified interface class.
bool isArcWeakrefUnavailable () const
isArcWeakrefUnavailable - Checks for a class or one of its super classes to be incompatible with __weak references.
const ObjCInterfaceDecl * isObjCRequiresPropertyDefs () const
isObjCRequiresPropertyDefs - Checks that a class or one of its super classes must not be auto-synthesized.
ObjCIvarDecl * lookupInstanceVariable (IdentifierInfo *IVarName, ObjCInterfaceDecl *&ClassDeclared)
ObjCIvarDecl * lookupInstanceVariable (IdentifierInfo *IVarName)
ObjCProtocolDecl * lookupNestedProtocol (IdentifierInfo *Name)
ObjCMethodDecl * lookupMethod (Selector Sel, bool isInstance, bool shallowCategoryLookup=false, bool followSuper=true, const ObjCCategoryDecl *C=nullptr) const
lookupMethod - This method returns an instance/class method by looking in the class, its categories, and its super classes (using a linear search).
ObjCMethodDecl * lookupInstanceMethod (Selector Sel) const
Lookup an instance method for a given selector.
ObjCMethodDecl * lookupClassMethod (Selector Sel) const
Lookup a class method for a given selector.
ObjCInterfaceDecl * lookupInheritedClass (const IdentifierInfo *ICName)
lookupInheritedClass - This method returns ObjCInterfaceDecl * of the super class whose name is passed as argument.
ObjCMethodDecl * lookupPrivateMethod (const Selector &Sel, bool Instance=true) const
Lookup a method in the classes implementation hierarchy.
ObjCMethodDecl * lookupPrivateClassMethod (const Selector &Sel)
ObjCMethodDecl * lookupPropertyAccessor (const Selector Sel, const ObjCCategoryDecl *Cat, bool IsClassProperty) const
Lookup a setter or getter in the class hierarchy, including in all categories except for category passed as argument.
SourceLocation getEndOfDefinitionLoc () const
void setEndOfDefinitionLoc (SourceLocation LE)
SourceLocation getSuperClassLoc () const
Retrieve the starting location of the superclass.
bool isImplicitInterfaceDecl () const
isImplicitInterfaceDecl - check that this is an implicitly declared ObjCInterfaceDecl node.
bool ClassImplementsProtocol (ObjCProtocolDecl *lProto, bool lookupCategory, bool RHSIsQualifiedID=false)
ClassImplementsProtocol - Checks that 'lProto' protocol has been implemented in IDecl class, its super class or categories (if lookupCategory is true).
ObjCInterfaceDecl * getCanonicalDecl () override
Retrieves the canonical declaration of this Objective-C class.
const ObjCInterfaceDecl * getCanonicalDecl () const
const Type * getTypeForDecl () const
void setTypeForDecl (const Type *TD) const
unsigned getODRHash ()
Get precomputed ODRHash or add a new one.
Public Member Functions inherited from clang::ObjCContainerDecl
ObjCContainerDecl (Kind DK, DeclContext *DC, IdentifierInfo *Id, SourceLocation nameLoc, SourceLocation atStartLoc)
prop_range properties () const
prop_iterator prop_begin () const
prop_iterator prop_end () const
instprop_range instance_properties () const
instprop_iterator instprop_begin () const
instprop_iterator instprop_end () const
classprop_range class_properties () const
classprop_iterator classprop_begin () const
classprop_iterator classprop_end () const
method_range methods () const
method_iterator meth_begin () const
method_iterator meth_end () const
instmeth_range instance_methods () const
instmeth_iterator instmeth_begin () const
instmeth_iterator instmeth_end () const
classmeth_range class_methods () const
classmeth_iterator classmeth_begin () const
classmeth_iterator classmeth_end () const
ObjCMethodDecl * getMethod (Selector Sel, bool isInstance, bool AllowHidden=false) const
ObjCMethodDecl * getInstanceMethod (Selector Sel, bool AllowHidden=false) const
ObjCMethodDecl * getClassMethod (Selector Sel, bool AllowHidden=false) const
bool HasUserDeclaredSetterMethod (const ObjCPropertyDecl *P) const
This routine returns 'true' if a user declared setter method was found in the class, its protocols, its super classes or categories.
ObjCIvarDecl * getIvarDecl (IdentifierInfo *Id) const
getIvarDecl - This method looks up an ivar in this ContextDecl.
ObjCPropertyDecl * getProperty (const IdentifierInfo *Id, bool IsInstance) const
ObjCPropertyDecl * FindPropertyDeclaration (const IdentifierInfo *PropertyId, ObjCPropertyQueryKind QueryKind) const
FindPropertyDeclaration - Finds declaration of the property given its name in 'PropertyId' and returns it.
SourceLocation getAtStartLoc () const
void setAtStartLoc (SourceLocation Loc)
SourceRange getAtEndRange () const
void setAtEndRange (SourceRange atEnd)
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &OS, const PrintingPolicy &Policy) const
Pretty-print the unqualified name of this declaration.
void printName (raw_ostream &OS) const
Calls printName() with the ASTContext printing policy from the decl.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getQualifiedNameAsString () const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
std::optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isDiscardedInGlobalModuleFragment () const
FIXME: Implement discarding declarations actually in global module fragment.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Public Member Functions inherited from clang::DeclContext
~DeclContext ()
bool hasValidDeclKind () const
Decl::Kind getDeclKind () const
const char * getDeclKindName () const
DeclContext * getParent ()
getParent - Returns the containing DeclContext.
const DeclContext * getParent () const
DeclContext * getLexicalParent ()
getLexicalParent - Returns the containing lexical DeclContext.
const DeclContext * getLexicalParent () const
DeclContext * getLookupParent ()
Find the parent context of this context that will be used for unqualified name lookup.
const DeclContext * getLookupParent () const
ASTContext & getParentASTContext () const
bool isClosure () const
const BlockDecl * getInnermostBlockDecl () const
Return this DeclContext if it is a BlockDecl.
bool isObjCContainer () const
bool isFunctionOrMethod () const
bool isLookupContext () const
Test whether the context supports looking up names.
bool isFileContext () const
bool isTranslationUnit () const
bool isRecord () const
bool isNamespace () const
bool isStdNamespace () const
bool isInlineNamespace () const
bool isDependentContext () const
Determines whether this context is dependent on a template parameter.
bool isTransparentContext () const
isTransparentContext - Determines whether this context is a "transparent" context, meaning that the members declared in this context are semantically declared in the nearest enclosing non-transparent (opaque) context but are lexically declared in this context.
bool isExternCContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C linkage.
const LinkageSpecDecl * getExternCContext () const
Retrieve the nearest enclosing C linkage specification context.
bool isExternCXXContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C++ linkage.
bool Equals (const DeclContext *DC) const
Determine whether this declaration context is equivalent to the declaration context DC.
bool Encloses (const DeclContext *DC) const
Determine whether this declaration context encloses the declaration context DC.
Decl * getNonClosureAncestor ()
Find the nearest non-closure ancestor of this context, i.e.
const Decl * getNonClosureAncestor () const
DeclContext * getNonTransparentContext ()
const DeclContext * getNonTransparentContext () const
DeclContext * getPrimaryContext ()
getPrimaryContext - There may be many different declarations of the same entity (including forward declarations of classes, multiple definitions of namespaces, etc.), each with a different set of declarations.
const DeclContext * getPrimaryContext () const
DeclContext * getRedeclContext ()
getRedeclContext - Retrieve the context in which an entity conflicts with other entities of the same name, or where it is a redeclaration if the two entities are compatible.
const DeclContext * getRedeclContext () const
DeclContext * getEnclosingNamespaceContext ()
Retrieve the nearest enclosing namespace context.
const DeclContext * getEnclosingNamespaceContext () const
RecordDecl * getOuterLexicalRecordContext ()
Retrieve the outermost lexically enclosing record context.
const RecordDecl * getOuterLexicalRecordContext () const
bool InEnclosingNamespaceSetOf (const DeclContext *NS) const
Test if this context is part of the enclosing namespace set of the context NS, as defined in C++0x [namespace.def]p9.
void collectAllContexts (SmallVectorImpl< DeclContext * > &Contexts)
Collects all of the declaration contexts that are semantically connected to this declaration context.
decl_range decls () const
decls_begin/decls_end - Iterate over the declarations stored in this context.
decl_iterator decls_begin () const
decl_iterator decls_end () const
bool decls_empty () const
decl_range noload_decls () const
noload_decls_begin/end - Iterate over the declarations stored in this context that are currently loaded; don't attempt to retrieve anything from an external source.
decl_iterator noload_decls_begin () const
decl_iterator noload_decls_end () const
void addDecl (Decl *D)
Add the declaration D into this context.
void addDeclInternal (Decl *D)
Add the declaration D into this context, but suppress searches for external declarations with the same name.
void addHiddenDecl (Decl *D)
Add the declaration D to this context without modifying any lookup tables.
void removeDecl (Decl *D)
Removes a declaration from this context.
bool containsDecl (Decl *D) const
Checks whether a declaration is in this context.
bool containsDeclAndLoad (Decl *D) const
Checks whether a declaration is in this context.
lookup_result lookup (DeclarationName Name) const
lookup - Find the declarations (if any) with the given Name in this context.
lookup_result noload_lookup (DeclarationName Name)
Find the declarations with the given name that are visible within this context; don't attempt to retrieve anything from an external source.
void localUncachedLookup (DeclarationName Name, SmallVectorImpl< NamedDecl * > &Results)
A simplistic name lookup mechanism that performs name lookup into this declaration context without consulting the external source.
void makeDeclVisibleInContext (NamedDecl *D)
Makes a declaration visible within this context.
lookups_range lookups () const
lookups_range noload_lookups (bool PreserveInternalState) const
all_lookups_iterator lookups_begin () const
Iterators over all possible lookups within this context.
all_lookups_iterator lookups_end () const
all_lookups_iterator noload_lookups_begin () const
Iterators over all possible lookups within this context that are currently loaded; don't attempt to retrieve anything from an external source.
all_lookups_iterator noload_lookups_end () const
udir_range using_directives () const
Returns iterator range [First, Last) of UsingDirectiveDecls stored within this context.
ddiag_range ddiags () const
void setMustBuildLookupTable ()
Mark that there are external lexical declarations that we need to include in our lookup table (and that are not available as external visible lookups).
StoredDeclsMap * getLookupPtr () const
Retrieve the internal representation of the lookup structure.
StoredDeclsMap * buildLookup ()
Ensure the lookup structure is fully-built and return it.
bool hasExternalLexicalStorage () const
Whether this DeclContext has external storage containing additional declarations that are lexically in this context.
void setHasExternalLexicalStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations lexically in this context.
bool hasExternalVisibleStorage () const
Whether this DeclContext has external storage containing additional declarations that are visible in this context.
void setHasExternalVisibleStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations visible in this context.
bool isDeclInLexicalTraversal (const Decl *D) const
Determine whether the given declaration is stored in the list of declarations lexically within this context.
void setUseQualifiedLookup (bool use=true) const
bool shouldUseQualifiedLookup () const
void dumpAsDecl () const
void dumpAsDecl (const ASTContext *Ctx) const
void dumpDeclContext () const
void dumpLookups () const
void dumpLookups (llvm::raw_ostream &OS, bool DumpDecls=false, bool Deserialize=false) const
Public Member Functions inherited from clang::Redeclarable< ObjCInterfaceDecl >
Redeclarable (const ASTContext &Ctx)
ObjCInterfaceDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const ObjCInterfaceDecl * getPreviousDecl () const
ObjCInterfaceDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const ObjCInterfaceDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
ObjCInterfaceDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const ObjCInterfaceDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (ObjCInterfaceDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static ObjCInterfaceDecl * Create (const ASTContext &C, DeclContext *DC, SourceLocation atLoc, IdentifierInfo *Id, ObjCTypeParamList *typeParamList, ObjCInterfaceDecl *PrevDecl, SourceLocation ClassLoc=SourceLocation(), bool isInternal=false)
static ObjCInterfaceDecl * CreateDeserialized (const ASTContext &C, unsigned ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::ObjCContainerDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const ObjCContainerDecl *D)
static ObjCContainerDecl * castFromDeclContext (const DeclContext *DC)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Static Public Member Functions inherited from clang::DeclContext
static bool classof (const Decl *D)
static bool classof (const DeclContext *D)
Friends
class ASTContext
class ODRDiagsEmitter
class ASTDeclReader
class ASTDeclWriter
class ASTReader
Additional Inherited Members
Public Attributes inherited from clang::DeclContext
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::DeclContext
DeclContext (Decl::Kind K)
Protected Member Functions inherited from clang::Redeclarable< ObjCInterfaceDecl >
ObjCInterfaceDecl * getNextRedeclaration () const
Static Protected Member Functions inherited from clang::DeclContext
static std::pair< Decl *, Decl * > BuildDeclChain (ArrayRef< Decl * > Decls, bool FieldsAlreadyLoaded)
Build up a chain of declarations.
Static Protected Member Functions inherited from clang::Redeclarable< ObjCInterfaceDecl >
static DeclLink PreviousDeclLink (ObjCInterfaceDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::DeclContext
union {
DeclContextBitfields DeclContextBits
TagDeclBitfields TagDeclBits
EnumDeclBitfields EnumDeclBits
RecordDeclBitfields RecordDeclBits
OMPDeclareReductionDeclBitfields OMPDeclareReductionDeclBits
FunctionDeclBitfields FunctionDeclBits
CXXConstructorDeclBitfields CXXConstructorDeclBits
ObjCMethodDeclBitfields ObjCMethodDeclBits
ObjCContainerDeclBitfields ObjCContainerDeclBits
LinkageSpecDeclBitfields LinkageSpecDeclBits
BlockDeclBitfields BlockDeclBits
};
This anonymous union stores the bits belonging to DeclContext and classes deriving from it.
Decl * FirstDecl = nullptr
FirstDecl - The first declaration stored within this declaration context.
Decl * LastDecl = nullptr
LastDecl - The last declaration stored within this declaration context.
Protected Attributes inherited from clang::Redeclarable< ObjCInterfaceDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
ObjCInterfaceDecl * First
Detailed Description
Represents an ObjC class declaration.
For example:
// MostPrimitive declares no super class (not particularly useful).
\@interface MostPrimitive
  // no instance variables or methods.
\@end
// NSResponder inherits from NSObject & implements NSCoding (a protocol).
\@interface NSResponder : NSObject \<NSCoding>
{ // instance variables are represented by ObjCIvarDecl.
  id nextResponder; // nextResponder instance variable.
}
- (NSResponder *)nextResponder; // return a pointer to NSResponder.
- (void)mouseMoved:(NSEvent *)theEvent; // return void, takes a pointer
\@end                                    // to an NSEvent.
Unlike C/C++, forward class declarations are accomplished with @class. Unlike C/C++, @class allows for a list of classes to be forward declared. Unlike C++, ObjC is a single-rooted class model. In Cocoa, classes typically inherit from NSObject (an exception is NSProxy).
Definition at line 1146 of file DeclObjC.h.
Member Typedef Documentation
all_protocol_iterator
using clang::ObjCInterfaceDecl::all_protocol_iterator = ObjCList<ObjCProtocolDecl>::iterator
Definition at line 1402 of file DeclObjC.h.
all_protocol_range
using clang::ObjCInterfaceDecl::all_protocol_range = llvm::iterator_range<all_protocol_iterator>
Definition at line 1403 of file DeclObjC.h.
ivar_iterator
using clang::ObjCInterfaceDecl::ivar_iterator = specific_decl_iterator<ObjCIvarDecl>
Definition at line 1436 of file DeclObjC.h.
ivar_range
using clang::ObjCInterfaceDecl::ivar_range = llvm::iterator_range<specific_decl_iterator<ObjCIvarDecl>>
Definition at line 1437 of file DeclObjC.h.
known_categories_iterator
using clang::ObjCInterfaceDecl::known_categories_iterator = filtered_category_iterator<isKnownCategory>
Iterator that walks over all of the known categories and extensions, including those that are hidden.
Definition at line 1671 of file DeclObjC.h.
known_categories_range
using clang::ObjCInterfaceDecl::known_categories_range
Initial value:
     llvm::iterator_range<known_categories_iterator>
Definition at line 1672 of file DeclObjC.h.
known_extensions_iterator
using clang::ObjCInterfaceDecl::known_extensions_iterator
Initial value:
      filtered_category_iterator<isKnownExtension>
Iterator that walks over all of the known extensions.
Definition at line 1744 of file DeclObjC.h.
known_extensions_range
using clang::ObjCInterfaceDecl::known_extensions_range
Initial value:
      llvm::iterator_range<known_extensions_iterator>
Definition at line 1746 of file DeclObjC.h.
protocol_iterator
using clang::ObjCInterfaceDecl::protocol_iterator = ObjCProtocolList::iterator
Definition at line 1344 of file DeclObjC.h.
protocol_loc_iterator
using clang::ObjCInterfaceDecl::protocol_loc_iterator = ObjCProtocolList::loc_iterator
Definition at line 1373 of file DeclObjC.h.
protocol_loc_range
using clang::ObjCInterfaceDecl::protocol_loc_range = llvm::iterator_range<protocol_loc_iterator>
Definition at line 1374 of file DeclObjC.h.
protocol_range
using clang::ObjCInterfaceDecl::protocol_range = llvm::iterator_range<protocol_iterator>
Definition at line 1345 of file DeclObjC.h.
redecl_iterator
using clang::ObjCInterfaceDecl::redecl_iterator = redeclarable_base::redecl_iterator
Definition at line 1892 of file DeclObjC.h.
redecl_range
using clang::ObjCInterfaceDecl::redecl_range = redeclarable_base::redecl_range
Definition at line 1891 of file DeclObjC.h.
visible_categories_iterator
using clang::ObjCInterfaceDecl::visible_categories_iterator
Initial value:
      filtered_category_iterator<isVisibleCategory>
Iterator that walks over the list of categories and extensions that are visible, i.e., not hidden in a non-imported submodule.
Definition at line 1635 of file DeclObjC.h.
visible_categories_range
using clang::ObjCInterfaceDecl::visible_categories_range
Initial value:
      llvm::iterator_range<visible_categories_iterator>
Definition at line 1638 of file DeclObjC.h.
visible_extensions_iterator
using clang::ObjCInterfaceDecl::visible_extensions_iterator
Initial value:
      filtered_category_iterator<isVisibleExtension>
Iterator that walks over all of the visible extensions, skipping any that are known but hidden.
Definition at line 1705 of file DeclObjC.h.
visible_extensions_range
using clang::ObjCInterfaceDecl::visible_extensions_range
Initial value:
      llvm::iterator_range<visible_extensions_iterator>
Definition at line 1708 of file DeclObjC.h.
Member Function Documentation
all_declared_ivar_begin() [1/2]
ObjCIvarDecl * ObjCInterfaceDecl::all_declared_ivar_begin ()
all_declared_ivar_begin - return first ivar declared in this class, its extensions and its implementation.
Lazily build the list on first access.
Caveat: The list returned by this method reflects the current state of the parser. The cache will be updated for every ivar added by an extension or the implementation when they are encountered. See also ObjCIvarDecl::Create().
Definition at line 1678 of file DeclObjC.cpp.
References getImplementation(), hasDefinition(), ivar_begin(), ivar_empty(), ivar_end(), known_extensions(), and clang::ObjCIvarDecl::setNextIvar().
Referenced by all_declared_ivar_begin(), clang::Sema::CollectIvarsToConstructOrDestruct(), DiagnoseVariableSizedIvars(), emitCXXDestructMethod(), FindIvarInterface(), and needsDestructMethod().
all_declared_ivar_begin() [2/2]
const ObjCIvarDecl * clang::ObjCInterfaceDecl::all_declared_ivar_begin () const inline
Definition at line 1464 of file DeclObjC.h.
References all_declared_ivar_begin().
all_referenced_protocol_begin()
all_protocol_iterator clang::ObjCInterfaceDecl::all_referenced_protocol_begin () const inline
Definition at line 1410 of file DeclObjC.h.
References clang::ObjCList< T >::begin(), clang::ObjCListBase::empty(), hasDefinition(), and protocol_begin().
Referenced by all_referenced_protocols(), and mergeClassExtensionProtocolList().
all_referenced_protocol_end()
all_protocol_iterator clang::ObjCInterfaceDecl::all_referenced_protocol_end () const inline
Definition at line 1423 of file DeclObjC.h.
References clang::ObjCListBase::empty(), clang::ObjCList< T >::end(), hasDefinition(), and protocol_end().
Referenced by all_referenced_protocols(), and mergeClassExtensionProtocolList().
all_referenced_protocols()
all_protocol_range clang::ObjCInterfaceDecl::all_referenced_protocols () const inline
Definition at line 1405 of file DeclObjC.h.
References all_referenced_protocol_begin(), and all_referenced_protocol_end().
Referenced by collectPropertiesToImplement(), clang::Sema::DiagnoseUnimplementedProperties(), FindPropertyVisibleInPrimaryClass(), findProtocolsWithExplicitImpls(), lookupNestedProtocol(), mergeClassExtensionProtocolList(), and SelectPropertyForSynthesisFromProtocols().
ClassImplementsProtocol()
bool ObjCInterfaceDecl::ClassImplementsProtocol (ObjCProtocolDecl * lProto, bool lookupCategory, bool RHSIsQualifiedID = false)
ClassImplementsProtocol - Checks that 'lProto' protocol has been implemented in IDecl class, its super class or categories (if lookupCategory is true).
Definition at line 1794 of file DeclObjC.cpp.
References ClassImplementsProtocol(), clang::Decl::getASTContext(), getSuperClass(), hasDefinition(), protocols(), and visible_categories().
Referenced by ClassImplementsProtocol(), clang::Sema::CreatePropertyDecl(), and clang::ASTContext::ObjCObjectAdoptsQTypeProtocols().
classof()
static bool clang::ObjCInterfaceDecl::classof (const Decl * D) inline static
Definition at line 1912 of file DeclObjC.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::ObjCInterfaceDecl::classofKind (Kind K) inline static
Definition at line 1913 of file DeclObjC.h.
Referenced by classof().
collectPropertiesToImplement()
void ObjCInterfaceDecl::collectPropertiesToImplement (PropertyMap & PM) const override virtual
This routine collects list of properties to be implemented in the class.
This includes, class's and its conforming protocols' properties. Note, the superclass's properties are not included in the list.
Reimplemented from clang::ObjCContainerDecl.
Definition at line 406 of file DeclObjC.cpp.
References all_referenced_protocols(), known_extensions(), and clang::ObjCContainerDecl::properties().
Referenced by clang::Sema::DefaultSynthesizeProperties(), and clang::Sema::DiagnoseUnimplementedProperties().
Create()
ObjCInterfaceDecl * ObjCInterfaceDecl::Create (const ASTContext & C, DeclContext * DC, SourceLocation atLoc, IdentifierInfo * Id, ObjCTypeParamList * typeParamList, ObjCInterfaceDecl * PrevDecl, SourceLocation ClassLoc = SourceLocation(), bool isInternal = false) static
Definition at line 1542 of file DeclObjC.cpp.
References clang::C, Id, and clang::Result.
Referenced by clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), clang::Sema::BuildObjCStringLiteral(), clang::ASTContext::getObjCProtocolDecl(), and LookupObjCInterfaceDeclForLiteral().
CreateDeserialized()
ObjCInterfaceDecl * ObjCInterfaceDecl::CreateDeserialized (const ASTContext & C, unsigned ID) static
Definition at line 1558 of file DeclObjC.cpp.
References clang::C, and clang::Result.
declaresOrInheritsDesignatedInitializers()
bool clang::ObjCInterfaceDecl::declaresOrInheritsDesignatedInitializers () const inline
Returns true if this interface decl declares a designated initializer or it inherites one from its super class.
Definition at line 1318 of file DeclObjC.h.
References hasDesignatedInitializers().
FindCategoryDeclaration()
ObjCCategoryDecl * ObjCInterfaceDecl::FindCategoryDeclaration (IdentifierInfo * CategoryId) const
FindCategoryDeclaration - Finds category declaration in the list of categories for this class and returns it.
Name of the category is passed in 'CategoryId'. If category not found, return 0;
Definition at line 1755 of file DeclObjC.cpp.
References hasDefinition(), and visible_categories().
Referenced by clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartCategoryImplementation(), clang::Sema::ActOnStartCategoryInterface(), clang::ObjCImplDecl::setClassInterface(), and clang::ASTNodeImporter::VisitObjCCategoryDecl().
FindPropertyVisibleInPrimaryClass()
ObjCPropertyDecl * ObjCInterfaceDecl::FindPropertyVisibleInPrimaryClass (IdentifierInfo * PropertyId, ObjCPropertyQueryKind QueryKind) const
FindPropertyVisibleInPrimaryClass - Finds declaration of the property with name 'PropertyId' in the primary class; including those in protocols (direct or indirect) used by the primary class.
Definition at line 382 of file DeclObjC.cpp.
References all_referenced_protocols(), clang::ObjCPropertyDecl::findPropertyDecl(), hasDefinition(), and P.
Referenced by findBackingIvar(), and clang::Sema::HandlePropertyInClassExtension().
getCanonicalDecl() [1/2]
const ObjCInterfaceDecl * clang::ObjCInterfaceDecl::getCanonicalDecl () const inline
Definition at line 1903 of file DeclObjC.h.
References clang::Redeclarable< ObjCInterfaceDecl >::getFirstDecl().
getCanonicalDecl() [2/2]
ObjCInterfaceDecl * clang::ObjCInterfaceDecl::getCanonicalDecl () inline override virtual
Retrieves the canonical declaration of this Objective-C class.
Reimplemented from clang::Decl.
Definition at line 1902 of file DeclObjC.h.
References clang::Redeclarable< ObjCInterfaceDecl >::getFirstDecl().
Referenced by checkObjCArrayLiteral(), checkObjCDictionaryLiteral(), clang::Sema::CheckObjCMethodOverrides(), getMostInformativeDerivedClassImpl(), isDesignatedInitializer(), clang::ASTNodeImporter::VisitObjCImplementationDecl(), clang::ASTDeclReader::VisitObjCInterfaceDecl(), and clang::ASTDeclReader::VisitObjCIvarDecl().
getCategoryClassMethod()
ObjCMethodDecl * ObjCInterfaceDecl::getCategoryClassMethod (Selector Sel) const
Definition at line 1781 of file DeclObjC.cpp.
References visible_categories().
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), and getCategoryMethod().
getCategoryInstanceMethod()
ObjCMethodDecl * ObjCInterfaceDecl::getCategoryInstanceMethod (Selector Sel) const
Definition at line 1771 of file DeclObjC.cpp.
References visible_categories().
Referenced by getCategoryMethod().
getCategoryListRaw()
ObjCCategoryDecl * clang::ObjCInterfaceDecl::getCategoryListRaw () const inline
Retrieve the raw pointer to the start of the category/extension list.
Definition at line 1772 of file DeclObjC.h.
References hasDefinition().
Referenced by clang::ObjCCategoryDecl::Create(), known_categories_begin(), known_extensions_begin(), visible_categories_begin(), visible_extensions_begin(), and clang::ASTDeclWriter::VisitObjCInterfaceDecl().
getCategoryMethod()
ObjCMethodDecl * clang::ObjCInterfaceDecl::getCategoryMethod (Selector Sel, bool isInstance) const inline
Definition at line 1339 of file DeclObjC.h.
References getCategoryClassMethod(), and getCategoryInstanceMethod().
Referenced by lookupPrivateMethod().
getDefinition() [1/2]
ObjCInterfaceDecl * clang::ObjCInterfaceDecl::getDefinition () inline
Retrieve the definition of this class, or NULL if this class has been forward-declared (with @class) but not yet defined (with @interface).
Definition at line 1530 of file DeclObjC.h.
References Data, and hasDefinition().
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::ActOnStartClassInterface(), clang::ObjCCategoryImplDecl::Create(), clang::ObjCImplementationDecl::Create(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CodeGen::CGDebugInfo::finalize(), clang::ObjCInterfaceType::getDecl(), getImplementation(), clang::Sema::getObjCInterfaceDecl(), getODRHash(), getSuperClass(), getTypeParamList(), clang::ASTImporter::ImportContext(), clang::ASTNodeImporter::ImportDefinition(), isDesignatedInitializer(), isThisDeclarationADefinition(), ivar_begin(), ivar_end(), setImplementation(), and clang::ASTNodeImporter::VisitObjCInterfaceDecl().
getDefinition() [2/2]
const ObjCInterfaceDecl * clang::ObjCInterfaceDecl::getDefinition () const inline
Retrieve the definition of this class, or NULL if this class has been forward-declared (with @class) but not yet defined (with @interface).
Definition at line 1537 of file DeclObjC.h.
References Data, and hasDefinition().
getDesignatedInitializers()
void ObjCInterfaceDecl::getDesignatedInitializers (llvm::SmallVectorImpl< const ObjCMethodDecl * > & Methods) const
Returns the designated initializers for the interface.
If this declaration does not have methods marked as designated initializers then the interface inherits the designated initializers of its super class.
Definition at line 549 of file DeclObjC.cpp.
References clang::ObjCContainerDecl::instance_methods(), isThisDeclarationADefinition(), and visible_extensions().
Referenced by clang::Sema::DiagnoseMissingDesignatedInitOverrides().
getEndOfDefinitionLoc()
SourceLocation clang::ObjCInterfaceDecl::getEndOfDefinitionLoc () const inline
Definition at line 1865 of file DeclObjC.h.
References clang::Decl::getLocation(), and hasDefinition().
Referenced by clang::ento::ObjCMethodCall::canBeOverridenInSubclass(), and clang::ASTDeclWriter::VisitObjCInterfaceDecl().
getImplementation()
ObjCImplementationDecl * ObjCInterfaceDecl::getImplementation () const
Definition at line 1635 of file DeclObjC.cpp.
References clang::Decl::getASTContext(), getDefinition(), and clang::ASTContext::getObjCImplementation().
Referenced by clang::Sema::ActOnStartCategoryInterface(), clang::Sema::ActOnStartClassImplementation(), AddObjCMethods(), all_declared_ivar_begin(), checkObjCDirectMethodClashes(), clang::ASTContext::CountNonClassIvars(), createObjCPropertyGetter(), clang::Sema::DiagnoseUnimplementedProperties(), clang::ASTNodeImporter::ImportDefinition(), isIntroducingInitializers(), lookupPrivateMethod(), clang::ASTNodeImporter::VisitObjCImplementationDecl(), clang::JSONNodeDumper::VisitObjCInterfaceDecl(), and clang::TextNodeDumper::VisitObjCInterfaceDecl().
getObjCRuntimeNameAsString()
StringRef ObjCInterfaceDecl::getObjCRuntimeNameAsString () const
Produce a name to be used for class's metadata.
It comes either via objc_runtime_name attribute or class name.
Definition at line 1619 of file DeclObjC.cpp.
References clang::Decl::getAttr(), and clang::NamedDecl::getName().
getODRHash()
unsigned ObjCInterfaceDecl::getODRHash ()
Get precomputed ODRHash or add a new one.
Definition at line 792 of file DeclObjC.cpp.
References clang::ODRHash::AddObjCInterfaceDecl(), clang::ODRHash::CalculateHash(), getDefinition(), and hasDefinition().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), and clang::ASTDeclWriter::VisitObjCInterfaceDecl().
getReferencedProtocols()
const ObjCProtocolList & clang::ObjCInterfaceDecl::getReferencedProtocols () const inline
Definition at line 1322 of file DeclObjC.h.
References hasDefinition().
Referenced by clang::ODRHash::AddObjCInterfaceDecl(), clang::ODRDiagsEmitter::diagnoseMismatch(), and rewriteToObjCInterfaceDecl().
getSourceRange()
SourceRange clang::ObjCInterfaceDecl::getSourceRange () const inline override virtual
Source range that this declaration covers.
Reimplemented from clang::ObjCContainerDecl.
Definition at line 1296 of file DeclObjC.h.
References clang::ObjCContainerDecl::getAtStartLoc(), clang::Decl::getLocation(), clang::ObjCContainerDecl::getSourceRange(), and isThisDeclarationADefinition().
getSuperClass()
ObjCInterfaceDecl * ObjCInterfaceDecl::getSuperClass () const
Definition at line 351 of file DeclObjC.cpp.
References getDefinition(), getSuperClassType(), and hasDefinition().
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::ActOnProperty(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartOfObjCMethodDef(), clang::ODRHash::AddObjCInterfaceDecl(), AddObjCMethods(), clang::ento::ObjCMethodCall::canBeOverridenInSubclass(), clang::Sema::CheckCategoryVsClassMethodMatches(), CheckObjCInstMethSignature(), CheckProtocolMethodDefs(), ClassImplementsProtocol(), clang::Sema::CodeCompleteObjCSuperMessage(), clang::ASTContext::CollectInheritedProtocols(), CollectOverriddenMethodsRecurse(), CollectSuperClassPropertyImplementations(), clang::ASTContext::DeepCollectObjCIvars(), DiagnoseDirectIsaAccess(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseMissingDesignatedInitOverrides(), DiagnoseVariableSizedIvars(), clang::ento::ObjCSummaryCache::find(), FindIvarInterface(), findKnownClass(), clang::ObjCContainerDecl::FindPropertyDeclaration(), findProtocolsWithExplicitImpls(), GetAssumedMessageSendExprType(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForObjCInterface(), hasObjCExceptionAttribute(), clang::ObjCContainerDecl::HasUserDeclaredSetterMethod(), clang::ASTNodeImporter::ImportDefinition(), clang::NSAPI::isSubclassOfNSClass(), isSuperClassOf(), isUnitTestCase(), lookupInheritedClass(), lookupInstanceVariable(), lookupMethod(), lookupNestedProtocol(), lookupPrivateMethod(), rewriteToObjCInterfaceDecl(), SelectPropertyForSynthesisFromProtocols(), shouldRunOnFunctionOrMethod(), SuperClassImplementsProperty(), clang::JSONNodeDumper::VisitObjCInterfaceDecl(), and clang::TextNodeDumper::VisitObjCInterfaceDecl().
getSuperClassLoc()
SourceLocation ObjCInterfaceDecl::getSuperClassLoc () const
Retrieve the starting location of the superclass.
Definition at line 371 of file DeclObjC.cpp.
References getSuperClassTInfo().
Referenced by clang::ASTNodeImporter::ImportDefinition(), and rewriteToObjCInterfaceDecl().
getSuperClassTInfo()
TypeSourceInfo * clang::ObjCInterfaceDecl::getSuperClassTInfo () const inline
Definition at line 1561 of file DeclObjC.h.
References hasDefinition().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), getSuperClassLoc(), getSuperClassType(), clang::ASTNodeImporter::ImportDefinition(), and clang::ASTDeclWriter::VisitObjCInterfaceDecl().
getSuperClassType()
const ObjCObjectType * clang::ObjCInterfaceDecl::getSuperClassType () const inline
Retrieve the superclass type.
Definition at line 1553 of file DeclObjC.h.
References getSuperClassTInfo().
Referenced by getSuperClass().
getTypeForDecl()
const Type * clang::ObjCInterfaceDecl::getTypeForDecl () const inline
Definition at line 1906 of file DeclObjC.h.
Referenced by clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), and clang::ASTDeclWriter::VisitObjCInterfaceDecl().
getTypeParamList()
ObjCTypeParamList * ObjCInterfaceDecl::getTypeParamList () const
Retrieve the type parameters of this class.
This function looks for a type parameter list for the given class; if the class has been declared (with @class) but not defined (with @interface), it will search for a declaration that has type parameters, skipping any declarations that do not.
Definition at line 321 of file DeclObjC.cpp.
References clang::ast_matchers::decl, getDefinition(), clang::Redeclarable< ObjCInterfaceDecl >::getMostRecentDecl(), clang::Redeclarable< decl_type >::getPreviousDecl(), and getTypeParamListAsWritten().
Referenced by clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ActOnStartCategoryInterface(), clang::Sema::ActOnStartClassInterface(), applyObjCTypeArgs(), and sameObjCTypeArgs().
getTypeParamListAsWritten()
ObjCTypeParamList * clang::ObjCInterfaceDecl::getTypeParamListAsWritten () const inline
Retrieve the type parameters written on this particular declaration of the class.
Definition at line 1292 of file DeclObjC.h.
Referenced by getTypeParamList(), clang::ASTNodeImporter::VisitObjCInterfaceDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCInterfaceDecl().
hasDefinition()
bool clang::ObjCInterfaceDecl::hasDefinition () const inline
Determine whether this class has been defined.
Definition at line 1516 of file DeclObjC.h.
References Data, and clang::Redeclarable< ObjCInterfaceDecl >::getMostRecentDecl().
Referenced by clang::Sema::ActOnStartCategoryImplementation(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), AddObjCMethods(), all_declared_ivar_begin(), all_referenced_protocol_begin(), all_referenced_protocol_end(), clang::Sema::checkInitMethod(), ClassImplementsProtocol(), clang::ObjCCategoryDecl::Create(), clang::ObjCCategoryImplDecl::Create(), clang::ObjCImplementationDecl::Create(), clang::Sema::DiagnoseAssignmentResult(), FindCategoryDeclaration(), FindPropertyVisibleInPrimaryClass(), getCategoryListRaw(), getDefinition(), getDefinition(), getEndOfDefinitionLoc(), getODRHash(), getReferencedProtocols(), getSuperClass(), getSuperClassTInfo(), isDesignatedInitializer(), isImplicitInterfaceDecl(), clang::Type::isIncompleteType(), lookupInheritedClass(), lookupInstanceVariable(), lookupMethod(), lookupPrivateMethod(), protocol_begin(), protocol_end(), protocol_loc_begin(), protocol_loc_end(), clang::ASTContext::QIdProtocolsAdoptObjCObjectProtocols(), and setExternallyCompleted().
hasDesignatedInitializers()
bool ObjCInterfaceDecl::hasDesignatedInitializers () const
Returns true if this interface decl contains at least one initializer marked with the 'objc_designated_initializer' attribute.
Definition at line 1608 of file DeclObjC.cpp.
References isThisDeclarationADefinition().
Referenced by declaresOrInheritsDesignatedInitializers(), and clang::Sema::DiagnoseMissingDesignatedInitOverrides().
isArcWeakrefUnavailable()
bool ObjCInterfaceDecl::isArcWeakrefUnavailable () const
isArcWeakrefUnavailable - Checks for a class or one of its super classes to be incompatible with __weak references.
Returns true if it is.
Definition at line 423 of file DeclObjC.cpp.
Referenced by clang::Sema::ActOnPropertyImplDecl().
isDesignatedInitializer()
bool ObjCInterfaceDecl::isDesignatedInitializer (Selector Sel, const ObjCMethodDecl ** InitMethod = nullptr) const
Returns true if the given selector is a designated initializer for the interface.
If this declaration does not have methods marked as designated initializers then the interface inherits the designated initializers of its super class.
Parameters
InitMethod if non-null and the function returns true, it receives the method that was marked as a designated initializer.
Definition at line 571 of file DeclObjC.cpp.
References getCanonicalDecl(), getDefinition(), clang::ObjCContainerDecl::getInstanceMethod(), hasDefinition(), isThisDeclarationADefinition(), and visible_extensions().
isImplicitInterfaceDecl()
bool clang::ObjCInterfaceDecl::isImplicitInterfaceDecl () const inline
isImplicitInterfaceDecl - check that this is an implicitly declared ObjCInterfaceDecl node.
This is for legacy objective-c @implementation declaration without an @interface declaration.
Definition at line 1880 of file DeclObjC.h.
References hasDefinition(), and clang::Decl::isImplicit().
Referenced by clang::Sema::CheckImplementationIvars(), and clang::ASTNodeImporter::VisitObjCInterfaceDecl().
isObjCRequiresPropertyDefs()
const ObjCInterfaceDecl * ObjCInterfaceDecl::isObjCRequiresPropertyDefs () const
isObjCRequiresPropertyDefs - Checks that a class or one of its super classes must not be auto-synthesized.
Returns class decl. if it must not be; 0, otherwise.
Definition at line 433 of file DeclObjC.cpp.
Referenced by clang::Sema::ActOnPropertyImplDecl(), and DiagnoseUnimplementedAccessor().
isSuperClassOf()
bool clang::ObjCInterfaceDecl::isSuperClassOf (const ObjCInterfaceDecl * I) const inline
isSuperClassOf - Return true if this class is the specified class or is a super class of the specified interface class.
Definition at line 1797 of file DeclObjC.h.
References clang::declaresSameEntity(), and getSuperClass().
Referenced by clang::ASTContext::canAssignObjCInterfaces(), clang::ASTContext::canAssignObjCInterfacesInBlockPointer(), clang::Sema::checkInitMethod(), CheckObjCBridgeCFCast(), CheckObjCBridgeNSCast(), EvaluateBinaryTypeTrait(), clang::Sema::IsSimplyAccessible(), and LookupMemberExpr().
isThisDeclarationADefinition()
bool clang::ObjCInterfaceDecl::isThisDeclarationADefinition () const inline
Determine whether this particular declaration of this class is actually also a definition.
Definition at line 1511 of file DeclObjC.h.
References getDefinition().
Referenced by getDesignatedInitializers(), getSourceRange(), hasDesignatedInitializers(), isDesignatedInitializer(), setHasDesignatedInitializers(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), and clang::ASTNodeImporter::VisitObjCInterfaceDecl().
ivar_begin()
ivar_iterator clang::ObjCInterfaceDecl::ivar_begin () const inline
Definition at line 1441 of file DeclObjC.h.
References getDefinition().
Referenced by all_declared_ivar_begin(), clang::Sema::CheckImplementationIvars(), DiagnoseDirectIsaAccess(), DiagnoseVariableSizedIvars(), ivar_empty(), ivar_size(), and ivars().
ivar_empty()
bool clang::ObjCInterfaceDecl::ivar_empty () const inline
Definition at line 1461 of file DeclObjC.h.
References ivar_begin(), and ivar_end().
Referenced by all_declared_ivar_begin(), and DiagnoseVariableSizedIvars().
ivar_end()
ivar_iterator clang::ObjCInterfaceDecl::ivar_end () const inline
Definition at line 1449 of file DeclObjC.h.
References getDefinition().
Referenced by all_declared_ivar_begin(), clang::Sema::CheckImplementationIvars(), ivar_empty(), ivar_size(), and ivars().
ivar_size()
unsigned clang::ObjCInterfaceDecl::ivar_size () const inline
Definition at line 1457 of file DeclObjC.h.
References ivar_begin(), and ivar_end().
Referenced by DiagnoseVariableSizedIvars().
ivars()
ivar_range clang::ObjCInterfaceDecl::ivars () const inline
Definition at line 1439 of file DeclObjC.h.
References ivar_begin(), and ivar_end().
Referenced by clang::ASTContext::DeepCollectObjCIvars(), and DiagnoseVariableSizedIvars().
known_categories()
known_categories_range clang::ObjCInterfaceDecl::known_categories () const inline
Definition at line 1675 of file DeclObjC.h.
References known_categories_begin(), and known_categories_end().
Referenced by AddObjCMethods(), clang::ObjCMethodDecl::findPropertyDecl(), and clang::ASTNodeImporter::ImportDefinition().
known_categories_begin()
known_categories_iterator clang::ObjCInterfaceDecl::known_categories_begin () const inline
Retrieve an iterator to the beginning of the known-categories list.
Definition at line 1682 of file DeclObjC.h.
References getCategoryListRaw().
Referenced by known_categories(), and known_categories_empty().
known_categories_empty()
bool clang::ObjCInterfaceDecl::known_categories_empty () const inline
Determine whether the known-categories list is empty.
Definition at line 1692 of file DeclObjC.h.
References known_categories_begin(), and known_categories_end().
known_categories_end()
known_categories_iterator clang::ObjCInterfaceDecl::known_categories_end () const inline
Retrieve an iterator to the end of the known-categories list.
Definition at line 1687 of file DeclObjC.h.
Referenced by known_categories(), and known_categories_empty().
known_extensions()
known_extensions_range clang::ObjCInterfaceDecl::known_extensions () const inline
Definition at line 1749 of file DeclObjC.h.
References known_extensions_begin(), and known_extensions_end().
Referenced by clang::Sema::ActOnFields(), clang::Sema::ActOnPropertyImplDecl(), all_declared_ivar_begin(), clang::Sema::AtomicPropertySetterGetterRules(), collectPropertiesToImplement(), clang::ASTContext::CountNonClassIvars(), clang::BodyFarm::getBody(), and clang::Sema::IvarBacksCurrentMethodAccessor().
known_extensions_begin()
known_extensions_iterator clang::ObjCInterfaceDecl::known_extensions_begin () const inline
Retrieve an iterator to the beginning of the known-extensions list.
Definition at line 1756 of file DeclObjC.h.
References getCategoryListRaw().
Referenced by known_extensions(), and known_extensions_empty().
known_extensions_empty()
bool clang::ObjCInterfaceDecl::known_extensions_empty () const inline
Determine whether the known-extensions list is empty.
Definition at line 1766 of file DeclObjC.h.
References known_extensions_begin(), and known_extensions_end().
known_extensions_end()
known_extensions_iterator clang::ObjCInterfaceDecl::known_extensions_end () const inline
Retrieve an iterator to the end of the known-extensions list.
Definition at line 1761 of file DeclObjC.h.
Referenced by known_extensions(), and known_extensions_empty().
lookupClassMethod()
ObjCMethodDecl * clang::ObjCInterfaceDecl::lookupClassMethod (Selector Sel) const inline
Lookup a class method for a given selector.
Definition at line 1839 of file DeclObjC.h.
References lookupMethod().
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), findMethodDecl(), getNSNumberFactoryMethod(), and LookupMemberExpr().
lookupInheritedClass()
ObjCInterfaceDecl * ObjCInterfaceDecl::lookupInheritedClass (const IdentifierInfo * ICName)
lookupInheritedClass - This method returns ObjCInterfaceDecl * of the super class whose name is passed as argument.
If it is not one of the super classes the it returns NULL.
Definition at line 669 of file DeclObjC.cpp.
References clang::NamedDecl::getIdentifier(), getSuperClass(), and hasDefinition().
Referenced by CheckProtocolMethodDefs().
lookupInstanceMethod()
ObjCMethodDecl * clang::ObjCInterfaceDecl::lookupInstanceMethod (Selector Sel) const inline
Lookup an instance method for a given selector.
Definition at line 1834 of file DeclObjC.h.
References lookupMethod().
Referenced by clang::Sema::BuildInstanceMessage(), canRewriteToSubscriptSyntax(), clang::Sema::CheckObjCForCollectionOperand(), findMethodDecl(), clang::Sema::HandleExprPropertyRefExpr(), lookupPrivateMethod(), and ShouldDiagnoseAvailabilityOfDecl().
lookupInstanceVariable() [1/2]
ObjCIvarDecl * clang::ObjCInterfaceDecl::lookupInstanceVariable (IdentifierInfo * IVarName) inline
Definition at line 1819 of file DeclObjC.h.
References lookupInstanceVariable().
lookupInstanceVariable() [2/2]
ObjCIvarDecl * ObjCInterfaceDecl::lookupInstanceVariable (IdentifierInfo * IVarName, ObjCInterfaceDecl *& ClassDeclared)
Definition at line 638 of file DeclObjC.cpp.
References clang::ObjCContainerDecl::getIvarDecl(), getSuperClass(), hasDefinition(), and visible_extensions().
Referenced by clang::Sema::ActOnPropertyImplDecl(), clang::Sema::DiagnoseDuplicateIvars(), clang::Sema::HandleExprPropertyRefExpr(), lookupInstanceVariable(), clang::Sema::LookupIvarInObjCMethod(), LookupMemberExpr(), and clang::ASTDeclReader::VisitObjCIvarDecl().
lookupMethod()
ObjCMethodDecl * ObjCInterfaceDecl::lookupMethod (Selector Sel, bool isInstance, bool shallowCategoryLookup = false, bool followSuper = true, const ObjCCategoryDecl * C = nullptr) const
lookupMethod - This method returns an instance/class method by looking in the class, its categories, and its super classes (using a linear search).
When argument category "C" is specified, any implicit method found in this category is ignored.
Definition at line 700 of file DeclObjC.cpp.
References clang::C, clang::ObjCContainerDecl::getMethod(), getSuperClass(), hasDefinition(), clang::Decl::isImplicit(), protocols(), and visible_categories().
Referenced by clang::ento::ObjCMethodCall::canBeOverridenInSubclass(), clang::Sema::CheckCategoryVsClassMethodMatches(), clang::Sema::checkObjCBridgeRelatedComponents(), CheckProtocolMethodDefs(), findMethodInCurrentClass(), clang::Sema::GetIvarBackingPropertyAccessor(), clang::Sema::IvarBacksCurrentMethodAccessor(), lookupClassMethod(), lookupInstanceMethod(), lookupPropertyAccessor(), and lookupRuntimeDefinition().
lookupNestedProtocol()
ObjCProtocolDecl * ObjCInterfaceDecl::lookupNestedProtocol (IdentifierInfo * Name)
Definition at line 688 of file DeclObjC.cpp.
References all_referenced_protocols(), getSuperClass(), lookupNestedProtocol(), and P.
Referenced by lookupNestedProtocol(), and PropertyMemoryAttribute().
lookupPrivateClassMethod()
ObjCMethodDecl * clang::ObjCInterfaceDecl::lookupPrivateClassMethod (const Selector & Sel) inline
Definition at line 1849 of file DeclObjC.h.
References lookupPrivateMethod().
Referenced by clang::Sema::ActOnClassPropertyRefExpr().
lookupPrivateMethod()
ObjCMethodDecl * ObjCInterfaceDecl::lookupPrivateMethod (const Selector & Sel, bool Instance = true) const
Lookup a method in the classes implementation hierarchy.
Definition at line 757 of file DeclObjC.cpp.
References getCategoryMethod(), getImplementation(), getSuperClass(), hasDefinition(), lookupInstanceMethod(), and lookupPrivateMethod().
Referenced by clang::Sema::BuildInstanceMessage(), clang::Sema::CheckObjCForCollectionOperand(), findMethodInCurrentClass(), clang::Sema::HandleExprPropertyRefExpr(), LookupMemberExpr(), lookupPrivateClassMethod(), lookupPrivateMethod(), and lookupRuntimeDefinition().
lookupPropertyAccessor()
ObjCMethodDecl * clang::ObjCInterfaceDecl::lookupPropertyAccessor (const Selector Sel, const ObjCCategoryDecl * Cat, bool IsClassProperty) const inline
Lookup a setter or getter in the class hierarchy, including in all categories except for category passed as argument.
Definition at line 1856 of file DeclObjC.h.
References lookupMethod().
Referenced by DiagnoseUnimplementedAccessor().
mergeClassExtensionProtocolList()
void ObjCInterfaceDecl::mergeClassExtensionProtocolList (ObjCProtocolDecl *const * List, unsigned Num, ASTContext & C)
mergeClassExtensionProtocolList - Merge class extension's protocol list into the protocol list for this class.
Definition at line 443 of file DeclObjC.cpp.
References all_referenced_protocol_begin(), all_referenced_protocol_end(), all_referenced_protocols(), clang::C, and clang::ObjCList< T >::set().
Referenced by clang::Sema::ActOnStartCategoryInterface(), and clang::ASTDeclReader::VisitObjCCategoryDecl().
mergeDuplicateDefinitionWithCommon()
void ObjCInterfaceDecl::mergeDuplicateDefinitionWithCommon (const ObjCInterfaceDecl * Definition)
Definition at line 633 of file DeclObjC.cpp.
References clang::Definition.
protocol_begin()
protocol_iterator clang::ObjCInterfaceDecl::protocol_begin () const inline
Definition at line 1351 of file DeclObjC.h.
References clang::ObjCList< T >::begin(), and hasDefinition().
Referenced by all_referenced_protocol_begin(), clang::ASTNodeImporter::ImportDefinition(), and protocols().
protocol_end()
protocol_iterator clang::ObjCInterfaceDecl::protocol_end () const inline
Definition at line 1362 of file DeclObjC.h.
References clang::ObjCList< T >::end(), and hasDefinition().
Referenced by all_referenced_protocol_end(), clang::ASTNodeImporter::ImportDefinition(), and protocols().
protocol_loc_begin()
protocol_loc_iterator clang::ObjCInterfaceDecl::protocol_loc_begin () const inline
Definition at line 1380 of file DeclObjC.h.
References hasDefinition(), and clang::ObjCProtocolList::loc_begin().
Referenced by clang::ASTNodeImporter::ImportDefinition(), and protocol_locs().
protocol_loc_end()
protocol_loc_iterator clang::ObjCInterfaceDecl::protocol_loc_end () const inline
Definition at line 1391 of file DeclObjC.h.
References hasDefinition(), and clang::ObjCProtocolList::loc_end().
Referenced by protocol_locs(), and rewriteToObjCInterfaceDecl().
protocol_locs()
protocol_loc_range clang::ObjCInterfaceDecl::protocol_locs () const inline
Definition at line 1376 of file DeclObjC.h.
References protocol_loc_begin(), and protocol_loc_end().
Referenced by clang::ASTDeclWriter::VisitObjCInterfaceDecl().
protocols()
protocol_range clang::ObjCInterfaceDecl::protocols () const inline
Definition at line 1347 of file DeclObjC.h.
References protocol_begin(), and protocol_end().
Referenced by clang::Sema::ActOnProperty(), clang::ODRHash::AddObjCInterfaceDecl(), AddObjCMethods(), ClassImplementsProtocol(), lookupMethod(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::JSONNodeDumper::VisitObjCInterfaceDecl(), and clang::TextNodeDumper::VisitObjCInterfaceDecl().
setCategoryListRaw()
void clang::ObjCInterfaceDecl::setCategoryListRaw (ObjCCategoryDecl * category) inline
Set the raw pointer to the start of the category/extension list.
Definition at line 1785 of file DeclObjC.h.
Referenced by clang::ObjCCategoryDecl::Create().
setEndOfDefinitionLoc()
void clang::ObjCInterfaceDecl::setEndOfDefinitionLoc (SourceLocation LE) inline
Definition at line 1872 of file DeclObjC.h.
Referenced by clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), clang::Sema::ActOnSuperClassOfClassInterface(), and clang::Sema::CheckImplementationIvars().
setExternallyCompleted()
void ObjCInterfaceDecl::setExternallyCompleted ()
Indicate that this Objective-C class is complete, but that the external AST source will be responsible for filling in its contents when a complete class is required.
Definition at line 1593 of file DeclObjC.cpp.
References clang::Decl::getASTContext(), and hasDefinition().
setHasDesignatedInitializers()
void ObjCInterfaceDecl::setHasDesignatedInitializers ()
Indicate that this interface decl contains at least one initializer marked with the 'objc_designated_initializer' attribute.
Definition at line 1601 of file DeclObjC.cpp.
References isThisDeclarationADefinition().
Referenced by handleObjCDesignatedInitializer().
setImplementation()
void ObjCInterfaceDecl::setImplementation (ObjCImplementationDecl * ImplD)
Definition at line 1648 of file DeclObjC.cpp.
References clang::Decl::getASTContext(), getDefinition(), and clang::ASTContext::setObjCImplementation().
Referenced by clang::Sema::ActOnStartClassImplementation(), clang::ASTNodeImporter::ImportDefinition(), and clang::ASTNodeImporter::VisitObjCImplementationDecl().
setIvarList()
void clang::ObjCInterfaceDecl::setIvarList (ObjCIvarDecl * ivar) inline
Definition at line 1469 of file DeclObjC.h.
setProtocolList()
void clang::ObjCInterfaceDecl::setProtocolList (ObjCProtocolDecl *const * List, unsigned Num, const SourceLocation * Locs, ASTContext & C) inline
setProtocolList - Set the list of protocols that this interface implements.
Definition at line 1473 of file DeclObjC.h.
References clang::C, and clang::ObjCProtocolList::set().
Referenced by clang::Sema::ActOnStartClassInterface(), and clang::ASTNodeImporter::ImportDefinition().
setSuperClass()
void clang::ObjCInterfaceDecl::setSuperClass (TypeSourceInfo * superClass) inline
Definition at line 1576 of file DeclObjC.h.
Referenced by clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnSuperClassOfClassInterface(), and clang::ASTNodeImporter::ImportDefinition().
setTypeForDecl()
void clang::ObjCInterfaceDecl::setTypeForDecl (const Type * TD) const inline
Definition at line 1907 of file DeclObjC.h.
setTypeParamList()
void ObjCInterfaceDecl::setTypeParamList (ObjCTypeParamList * TPL)
Set the type parameters of this class.
This function is used by the AST importer, which must import the type parameters after creating their DeclContext to avoid loops.
Definition at line 342 of file DeclObjC.cpp.
Referenced by clang::ASTNodeImporter::VisitObjCInterfaceDecl().
startDefinition()
void ObjCInterfaceDecl::startDefinition ()
Starts the definition of this Objective-C class, taking it from a forward declaration (@class) to a definition (@interface).
Definition at line 617 of file DeclObjC.cpp.
References clang::Redeclarable< ObjCInterfaceDecl >::redecls().
Referenced by clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), and clang::ASTNodeImporter::ImportDefinition().
startDuplicateDefinitionForComparison()
void ObjCInterfaceDecl::startDuplicateDefinitionForComparison ()
Starts the definition without sharing it with other redeclarations.
Such definition shouldn't be used for anything but only to compare if a duplicate is compatible with previous definition or if it is a distinct duplicate.
Definition at line 627 of file DeclObjC.cpp.
Referenced by clang::Sema::ActOnStartClassInterface().
visible_categories()
visible_categories_range clang::ObjCInterfaceDecl::visible_categories () const inline
Definition at line 1641 of file DeclObjC.h.
References visible_categories_begin(), and visible_categories_end().
Referenced by checkObjCDirectMethodClashes(), ClassImplementsProtocol(), clang::Sema::CodeCompleteObjCMethodDecl(), FindCategoryDeclaration(), getCategoryClassMethod(), getCategoryInstanceMethod(), and lookupMethod().
visible_categories_begin()
visible_categories_iterator clang::ObjCInterfaceDecl::visible_categories_begin () const inline
Retrieve an iterator to the beginning of the visible-categories list.
Definition at line 1648 of file DeclObjC.h.
References getCategoryListRaw().
Referenced by visible_categories(), and visible_categories_empty().
visible_categories_empty()
bool clang::ObjCInterfaceDecl::visible_categories_empty () const inline
Determine whether the visible-categories list is empty.
Definition at line 1658 of file DeclObjC.h.
References visible_categories_begin(), and visible_categories_end().
visible_categories_end()
visible_categories_iterator clang::ObjCInterfaceDecl::visible_categories_end () const inline
Retrieve an iterator to the end of the visible-categories list.
Definition at line 1653 of file DeclObjC.h.
Referenced by visible_categories(), and visible_categories_empty().
visible_extensions()
visible_extensions_range clang::ObjCInterfaceDecl::visible_extensions () const inline
Definition at line 1711 of file DeclObjC.h.
References visible_extensions_begin(), and visible_extensions_end().
Referenced by clang::Sema::CheckImplementationIvars(), clang::Sema::DiagnoseMissingDesignatedInitOverrides(), clang::ObjCMethodDecl::findPropertyDecl(), getDesignatedInitializers(), isDesignatedInitializer(), isIntroducingInitializers(), and lookupInstanceVariable().
visible_extensions_begin()
visible_extensions_iterator clang::ObjCInterfaceDecl::visible_extensions_begin () const inline
Retrieve an iterator to the beginning of the visible-extensions list.
Definition at line 1718 of file DeclObjC.h.
References getCategoryListRaw().
Referenced by visible_extensions(), and visible_extensions_empty().
visible_extensions_empty()
bool clang::ObjCInterfaceDecl::visible_extensions_empty () const inline
Determine whether the visible-extensions list is empty.
Definition at line 1728 of file DeclObjC.h.
References visible_extensions_begin(), and visible_extensions_end().
visible_extensions_end()
visible_extensions_iterator clang::ObjCInterfaceDecl::visible_extensions_end () const inline
Retrieve an iterator to the end of the visible-extensions list.
Definition at line 1723 of file DeclObjC.h.
Referenced by visible_extensions(), and visible_extensions_empty().
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 1148 of file DeclObjC.h.
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 1739 of file DeclObjC.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 1740 of file DeclObjC.h.
ASTReader
friend class ASTReader friend
Definition at line 1741 of file DeclObjC.h.
ODRDiagsEmitter
friend class ODRDiagsEmitter friend
Definition at line 1149 of file DeclObjC.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclObjC.h
lib/AST/DeclObjC.cpp