clang: clang::SubstTemplateTemplateParmStorage Class Reference
clang::SubstTemplateTemplateParmStorage Class Reference
A structure for storing the information associated with a substituted template template parameter.
#include "clang/AST/TemplateName.h"
Public Member Functions
Decl * getAssociatedDecl () const
A template-like entity which owns the whole pattern being substituted.
unsigned getIndex () const
Returns the index of the replaced parameter in the associated declaration.
std::optional< unsigned > getPackIndex () const
TemplateTemplateParmDecl * getParameter () const
TemplateName getReplacement () const
void Profile (llvm::FoldingSetNodeID &ID)
Public Member Functions inherited from clang::UncommonTemplateNameStorage
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, TemplateName Replacement, Decl *AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex)
Friends
class ASTContext
Additional Inherited Members
Public Attributes inherited from clang::UncommonTemplateNameStorage
Protected Types inherited from clang::UncommonTemplateNameStorage
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions inherited from clang::UncommonTemplateNameStorage
UncommonTemplateNameStorage (Kind Kind, unsigned Index, unsigned Data)
Protected Attributes inherited from clang::UncommonTemplateNameStorage
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
A structure for storing the information associated with a substituted template template parameter.
Definition at line 372 of file TemplateName.h.
Member Function Documentation
getAssociatedDecl()
Decl * clang::SubstTemplateTemplateParmStorage::getAssociatedDecl () const inline
A template-like entity which owns the whole pattern being substituted.
This will own a set of template parameters.
Definition at line 391 of file TemplateName.h.
Referenced by getParameter(), clang::ASTImporter::Import(), and Profile().
getIndex()
unsigned clang::SubstTemplateTemplateParmStorage::getIndex () const inline
Returns the index of the replaced parameter in the associated declaration.
This should match the result of getParameter()->getIndex().
Definition at line 395 of file TemplateName.h.
Referenced by clang::ASTImporter::Import(), and Profile().
getPackIndex()
std::optional< unsigned > clang::SubstTemplateTemplateParmStorage::getPackIndex () const inline
Definition at line 397 of file TemplateName.h.
Referenced by clang::ASTImporter::Import(), and Profile().
getParameter()
TemplateTemplateParmDecl * SubstTemplateTemplateParmStorage::getParameter () const
Definition at line 50 of file TemplateName.cpp.
References clang::cast(), getAssociatedDecl(), and clang::getReplacedTemplateParameterList().
Referenced by clang::ASTContext::getNameForTemplate().
getReplacement()
TemplateName clang::SubstTemplateTemplateParmStorage::getReplacement () const inline
Definition at line 404 of file TemplateName.h.
Referenced by clang::ASTContext::getCanonicalTemplateName(), and clang::ASTImporter::Import().
Profile() [1/2]
void SubstTemplateTemplateParmStorage::Profile (llvm::FoldingSetNodeID & ID)
Definition at line 56 of file TemplateName.cpp.
References getAssociatedDecl(), getIndex(), getPackIndex(), and Profile().
Referenced by clang::ASTContext::getSubstTemplateTemplateParm(), and Profile().
Profile() [2/2]
void SubstTemplateTemplateParmStorage::Profile (llvm::FoldingSetNodeID & ID, TemplateName Replacement, Decl * AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex) static
Definition at line 60 of file TemplateName.cpp.
References clang::TemplateName::Profile().
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 374 of file TemplateName.h.
The documentation for this class was generated from the following files:
include/clang/AST/TemplateName.h
lib/AST/TemplateName.cpp