clang: clang::OMPDepobjClause Class Reference
clang::OMPDepobjClause Class Reference final
This represents implicit clause 'depobj' for the '#pragma omp depobj' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
Expr * getDepobj ()
Returns depobj expression associated with the clause.
const Expr * getDepobj () const
SourceLocation getLParenLoc () const
Returns the location of '('.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPDepobjClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, Expr *Depobj)
Creates clause.
static OMPDepobjClause * CreateEmpty (const ASTContext &C)
Creates an empty clause.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents implicit clause 'depobj' for the '#pragma omp depobj' directive.
This clause does not exist by itself, it can be only as a part of 'omp depobj' directive. This clause is introduced to keep the original structure of OMPExecutableDirective class and its derivatives and to use the existing infrastructure of clauses with the list of variables.
#pragma omp depobj(a) destroy
In this example directive '#pragma omp depobj' has implicit clause 'depobj' with the depobj 'a'.
Definition at line 4701 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPDepobjClause::children () inline
Definition at line 4754 of file OpenMPClause.h.
Referenced by children().
children() [2/2]
const_child_range clang::OMPDepobjClause::children () const inline
Definition at line 4759 of file OpenMPClause.h.
References Children, and children().
classof()
static bool clang::OMPDepobjClause::classof (const OMPClause * T) inline static
Definition at line 4771 of file OpenMPClause.h.
Create()
OMPDepobjClause * OMPDepobjClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, Expr * Depobj) static
Creates clause.
Parameters
C AST context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Depobj depobj expression associated with the 'depobj' directive.
Definition at line 1035 of file OpenMPClause.cpp.
References clang::C.
Referenced by clang::Sema::ActOnOpenMPDepobjClause().
CreateEmpty()
OMPDepobjClause * OMPDepobjClause::CreateEmpty (const ASTContext & C) static
Creates an empty clause.
Parameters
C AST context.
Definition at line 1045 of file OpenMPClause.cpp.
References clang::C.
Referenced by clang::OMPClauseReader::readClause().
getDepobj() [1/2]
Expr * clang::OMPDepobjClause::getDepobj () inline
Returns depobj expression associated with the clause.
Definition at line 4748 of file OpenMPClause.h.
getDepobj() [2/2]
const Expr * clang::OMPDepobjClause::getDepobj () const inline
Definition at line 4749 of file OpenMPClause.h.
getLParenLoc()
SourceLocation clang::OMPDepobjClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 4752 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPDepobjClause::used_children () inline
Definition at line 4764 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPDepobjClause::used_children () const inline
Definition at line 4767 of file OpenMPClause.h.
Friends And Related Symbol Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 4702 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp