clang: clang::Sema::NameClassification Class Reference
clang::Sema::NameClassification Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
NameClassification (ParsedType Type)
NameClassification (const IdentifierInfo *Keyword)
NameClassificationKind getKind () const
ExprResult getExpression () const
ParsedType getType () const
NamedDecl * getNonTypeDecl () const
TemplateName getTemplateName () const
TemplateNameKind getTemplateNameKind () const
Static Public Member Functions
static NameClassification Error ()
static NameClassification Unknown ()
static NameClassification OverloadSet (ExprResult E)
static NameClassification NonType (NamedDecl *D)
static NameClassification UndeclaredNonType ()
static NameClassification DependentNonType ()
static NameClassification TypeTemplate (TemplateName Name)
static NameClassification VarTemplate (TemplateName Name)
static NameClassification FunctionTemplate (TemplateName Name)
static NameClassification Concept (TemplateName Name)
static NameClassification UndeclaredTemplate (TemplateName Name)
Detailed Description
Definition at line 2707 of file Sema.h.
Constructor & Destructor Documentation
NameClassification() [1/2]
clang::Sema::NameClassification::NameClassification (ParsedType Type) inline
Definition at line 2719 of file Sema.h.
NameClassification() [2/2]
clang::Sema::NameClassification::NameClassification (const IdentifierInfo * Keyword) inline
Definition at line 2721 of file Sema.h.
Member Function Documentation
Concept()
static NameClassification clang::Sema::NameClassification::Concept (TemplateName Name) inline static
Definition at line 2769 of file Sema.h.
References clang::Sema::NC_Concept, and clang::Result.
Referenced by clang::Sema::ClassifyName().
DependentNonType()
static NameClassification clang::Sema::NameClassification::DependentNonType () inline static
Definition at line 2747 of file Sema.h.
References clang::Sema::NC_DependentNonType.
Referenced by clang::Sema::ClassifyName().
Error()
static NameClassification clang::Sema::NameClassification::Error () inline static
Definition at line 2723 of file Sema.h.
References clang::Sema::NC_Error.
Referenced by clang::Sema::ClassifyName().
FunctionTemplate()
static NameClassification clang::Sema::NameClassification::FunctionTemplate (TemplateName Name) inline static
Definition at line 2763 of file Sema.h.
References clang::Sema::NC_FunctionTemplate, and clang::Result.
Referenced by clang::Sema::ClassifyName().
getExpression()
ExprResult clang::Sema::NameClassification::getExpression () const inline
Definition at line 2783 of file Sema.h.
References Expr, and clang::Sema::NC_OverloadSet.
getKind()
NameClassificationKind clang::Sema::NameClassification::getKind () const inline
Definition at line 2781 of file Sema.h.
getNonTypeDecl()
NamedDecl * clang::Sema::NameClassification::getNonTypeDecl () const inline
Definition at line 2793 of file Sema.h.
References clang::Sema::NC_NonType, and NonTypeDecl.
getTemplateName()
TemplateName clang::Sema::NameClassification::getTemplateName () const inline
Definition at line 2798 of file Sema.h.
References clang::Sema::NC_Concept, clang::Sema::NC_FunctionTemplate, clang::Sema::NC_TypeTemplate, clang::Sema::NC_UndeclaredTemplate, clang::Sema::NC_VarTemplate, and Template.
getTemplateNameKind()
TemplateNameKind clang::Sema::NameClassification::getTemplateNameKind () const inline
Definition at line 2805 of file Sema.h.
References clang::Sema::NC_Concept, clang::Sema::NC_FunctionTemplate, clang::Sema::NC_TypeTemplate, clang::Sema::NC_UndeclaredTemplate, clang::Sema::NC_VarTemplate, clang::TNK_Concept_template, clang::TNK_Function_template, clang::TNK_Type_template, clang::TNK_Undeclared_template, and clang::TNK_Var_template.
getType()
ParsedType clang::Sema::NameClassification::getType () const inline
Definition at line 2788 of file Sema.h.
References clang::Sema::NC_Type, and Type.
NonType()
static NameClassification clang::Sema::NameClassification::NonType (NamedDecl * D) inline static
Definition at line 2737 of file Sema.h.
References clang::Sema::NC_NonType, and clang::Result.
Referenced by clang::Sema::ClassifyName().
OverloadSet()
static NameClassification clang::Sema::NameClassification::OverloadSet (ExprResult E) inline static
Definition at line 2731 of file Sema.h.
References clang::Sema::NC_OverloadSet, and clang::Result.
Referenced by clang::Sema::ClassifyName().
TypeTemplate()
static NameClassification clang::Sema::NameClassification::TypeTemplate (TemplateName Name) inline static
Definition at line 2751 of file Sema.h.
References clang::Sema::NC_TypeTemplate, and clang::Result.
Referenced by clang::Sema::ClassifyName().
UndeclaredNonType()
static NameClassification clang::Sema::NameClassification::UndeclaredNonType () inline static
Definition at line 2743 of file Sema.h.
References clang::Sema::NC_UndeclaredNonType.
Referenced by clang::Sema::ClassifyName().
UndeclaredTemplate()
static NameClassification clang::Sema::NameClassification::UndeclaredTemplate (TemplateName Name) inline static
Definition at line 2775 of file Sema.h.
References clang::Sema::NC_UndeclaredTemplate, and clang::Result.
Referenced by clang::Sema::ClassifyName().
Unknown()
static NameClassification clang::Sema::NameClassification::Unknown () inline static
Definition at line 2727 of file Sema.h.
References clang::Sema::NC_Unknown.
Referenced by clang::Sema::ClassifyName().
VarTemplate()
static NameClassification clang::Sema::NameClassification::VarTemplate (TemplateName Name) inline static
Definition at line 2757 of file Sema.h.
References clang::Sema::NC_VarTemplate, and clang::Result.
Referenced by clang::Sema::ClassifyName().
Member Data Documentation
Expr
ExprResult clang::Sema::NameClassification::Expr
Definition at line 2710 of file Sema.h.
Referenced by getExpression().
NonTypeDecl
NamedDecl* clang::Sema::NameClassification::NonTypeDecl
Definition at line 2711 of file Sema.h.
Referenced by getNonTypeDecl().
Template
TemplateName clang::Sema::NameClassification::Template
Definition at line 2712 of file Sema.h.
Referenced by getTemplateName().
Type
ParsedType clang::Sema::NameClassification::Type
Definition at line 2713 of file Sema.h.
Referenced by getType().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h