clang: clang::ento::SymbolManager Class Reference
clang::ento::SymbolManager Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
SymbolManager (ASTContext &ctx, BasicValueFactory &bv, llvm::BumpPtrAllocator &bpalloc)
const SymbolRegionValue * getRegionValueSymbol (const TypedValueRegion *R)
Make a unique symbol for MemRegion R according to its kind.
const SymbolConjured * conjureSymbol (const Stmt *E, const LocationContext *LCtx, QualType T, unsigned VisitCount, const void *SymbolTag=nullptr)
const SymbolConjured * conjureSymbol (const Expr *E, const LocationContext *LCtx, unsigned VisitCount, const void *SymbolTag=nullptr)
const SymbolDerived * getDerivedSymbol (SymbolRef parentSymbol, const TypedValueRegion *R)
const SymbolExtent * getExtentSymbol (const SubRegion *R)
const SymbolMetadata * getMetadataSymbol (const MemRegion *R, const Stmt *S, QualType T, const LocationContext *LCtx, unsigned VisitCount, const void *SymbolTag=nullptr)
Creates a metadata symbol associated with a specific region.
const SymbolCast * getCastSymbol (const SymExpr *Operand, QualType From, QualType To)
const SymIntExpr * getSymIntExpr (const SymExpr *lhs, BinaryOperator::Opcode op, const llvm::APSInt &rhs, QualType t)
const SymIntExpr * getSymIntExpr (const SymExpr &lhs, BinaryOperator::Opcode op, const llvm::APSInt &rhs, QualType t)
const IntSymExpr * getIntSymExpr (const llvm::APSInt &lhs, BinaryOperator::Opcode op, const SymExpr *rhs, QualType t)
const SymSymExpr * getSymSymExpr (const SymExpr *lhs, BinaryOperator::Opcode op, const SymExpr *rhs, QualType t)
const UnarySymExpr * getUnarySymExpr (const SymExpr *operand, UnaryOperator::Opcode op, QualType t)
QualType getType (const SymExpr *SE) const
void addSymbolDependency (const SymbolRef Primary, const SymbolRef Dependent)
Add artificial symbol dependency.
const SymbolRefSmallVectorTy * getDependentSymbols (const SymbolRef Primary)
ASTContext & getContext ()
BasicValueFactory & getBasicVals ()
Static Public Member Functions
static bool canSymbolicate (QualType T)
Detailed Description
Definition at line 482 of file SymbolManager.h.
Constructor & Destructor Documentation
SymbolManager()
clang::ento::SymbolManager::SymbolManager (ASTContext & ctx, BasicValueFactory & bv, llvm::BumpPtrAllocator & bpalloc) inline
Definition at line 499 of file SymbolManager.h.
Member Function Documentation
addSymbolDependency()
void SymbolManager::addSymbolDependency (const SymbolRef Primary, const SymbolRef Dependent)
Add artificial symbol dependency.
The dependent symbol should stay alive as long as the primary is alive.
Definition at line 364 of file SymbolManager.cpp.
canSymbolicate()
bool SymbolManager::canSymbolicate (QualType T) static
Definition at line 349 of file SymbolManager.cpp.
References clang::ento::Loc::isLocType().
Referenced by clang::ento::SValBuilder::conjureSymbolVal(), clang::ento::SValBuilder::conjureSymbolVal(), clang::ento::SValBuilder::getConjuredHeapSymbolVal(), clang::ento::SValBuilder::getDerivedRegionValueSymbolVal(), clang::ento::SValBuilder::getMetadataSymbolVal(), and clang::ento::SValBuilder::getRegionValueSymbolVal().
conjureSymbol() [1/2]
const SymbolConjured * clang::ento::SymbolManager::conjureSymbol (const Expr * E, const LocationContext * LCtx, unsigned VisitCount, const void * SymbolTag = nullptr) inline
Definition at line 514 of file SymbolManager.h.
References conjureSymbol(), clang::Expr::getType(), and VisitCount.
conjureSymbol() [2/2]
const SymbolConjured * SymbolManager::conjureSymbol (const Stmt * E, const LocationContext * LCtx, QualType T, unsigned VisitCount, const void * SymbolTag = nullptr)
Definition at line 181 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolConjured::Profile().
Referenced by clang::ento::SValBuilder::conjureSymbol(), clang::ento::SValBuilder::conjureSymbol(), conjureSymbol(), clang::ento::SValBuilder::conjureSymbolVal(), clang::ento::SValBuilder::conjureSymbolVal(), clang::ento::SValBuilder::getConjuredHeapSymbolVal(), and populateObjCForDestinationSet().
getBasicVals()
BasicValueFactory & clang::ento::SymbolManager::getBasicVals () inline
Definition at line 569 of file SymbolManager.h.
getCastSymbol()
const SymbolCast * SymbolManager::getCastSymbol (const SymExpr * Operand, QualType From, QualType To)
Definition at line 248 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolCast::Profile().
Referenced by clang::ento::SValBuilder::makeNonLoc().
getContext()
ASTContext & clang::ento::SymbolManager::getContext () inline
Definition at line 568 of file SymbolManager.h.
Referenced by clang::ento::RangedConstraintManager::assumeSym().
getDependentSymbols()
const SymbolRefSmallVectorTy * SymbolManager::getDependentSymbols (const SymbolRef Primary)
Definition at line 373 of file SymbolManager.cpp.
getDerivedSymbol()
const SymbolDerived * SymbolManager::getDerivedSymbol (SymbolRef parentSymbol, const TypedValueRegion * R)
Definition at line 200 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolDerived::Profile().
Referenced by clang::ento::SValBuilder::getDerivedRegionValueSymbolVal().
getExtentSymbol()
const SymbolExtent * SymbolManager::getExtentSymbol (const SubRegion * R)
Definition at line 216 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolExtent::Profile().
Referenced by clang::ento::MemRegionManager::getStaticSize().
getIntSymExpr()
const IntSymExpr * SymbolManager::getIntSymExpr (const llvm::APSInt & lhs, BinaryOperator::Opcode op, const SymExpr * rhs, QualType t)
Definition at line 279 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile().
Referenced by clang::ento::SValBuilder::makeNonLoc().
getMetadataSymbol()
const SymbolMetadata * SymbolManager::getMetadataSymbol (const MemRegion * R, const Stmt * S, QualType T, const LocationContext * LCtx, unsigned VisitCount, const void * SymbolTag = nullptr)
Creates a metadata symbol associated with a specific region.
VisitCount can be used to differentiate regions corresponding to different loop iterations, thus, making the symbol path-dependent.
Definition at line 231 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolMetadata::Profile().
Referenced by clang::ento::SValBuilder::getMetadataSymbolVal().
getRegionValueSymbol()
const SymbolRegionValue * SymbolManager::getRegionValueSymbol (const TypedValueRegion * R)
Make a unique symbol for MemRegion R according to its kind.
Definition at line 167 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::SymbolRegionValue::Profile().
Referenced by clang::ento::SValBuilder::getRegionValueSymbolVal().
getSymIntExpr() [1/2]
const SymIntExpr * clang::ento::SymbolManager::getSymIntExpr (const SymExpr & lhs, BinaryOperator::Opcode op, const llvm::APSInt & rhs, QualType t) inline
Definition at line 542 of file SymbolManager.h.
References getSymIntExpr().
getSymIntExpr() [2/2]
const SymIntExpr * SymbolManager::getSymIntExpr (const SymExpr * lhs, BinaryOperator::Opcode op, const llvm::APSInt & rhs, QualType t)
Definition at line 262 of file SymbolManager.cpp.
References clang::cast(), clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile(), and v.
Referenced by doRearrangeUnchecked(), getSymIntExpr(), and clang::ento::SValBuilder::makeNonLoc().
getSymSymExpr()
const SymSymExpr * SymbolManager::getSymSymExpr (const SymExpr * lhs, BinaryOperator::Opcode op, const SymExpr * rhs, QualType t)
Definition at line 296 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::Profile().
Referenced by clang::ento::RangedConstraintManager::assumeSym(), doRearrangeUnchecked(), and clang::ento::SValBuilder::makeNonLoc().
getType()
QualType clang::ento::SymbolManager::getType (const SymExpr * SE) const inline
Definition at line 557 of file SymbolManager.h.
References clang::ento::SymExpr::getType().
getUnarySymExpr()
const UnarySymExpr * SymbolManager::getUnarySymExpr (const SymExpr * operand, UnaryOperator::Opcode op, QualType t)
Definition at line 313 of file SymbolManager.cpp.
References clang::cast(), and clang::ento::UnarySymExpr::Profile().
Referenced by clang::ento::SValBuilder::makeNonLoc().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp