clang: clang::ento::ConditionBRVisitor Class Reference
clang::ento::ConditionBRVisitor Class Reference final
Visitor that tries to report interesting diagnostics from conditions.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Public Member Functions
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
PathDiagnosticPieceRef VisitNodeImpl (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR)
PathDiagnosticPieceRef VisitTerminator (const Stmt *Term, const ExplodedNode *N, const CFGBlock *SrcBlk, const CFGBlock *DstBlk, PathSensitiveBugReport &R, BugReporterContext &BRC)
PathDiagnosticPieceRef VisitTrueTest (const Expr *Cond, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, bool TookTrue)
PathDiagnosticPieceRef VisitTrueTest (const Expr *Cond, const DeclRefExpr *DR, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, bool TookTrue, bool IsAssuming)
PathDiagnosticPieceRef VisitTrueTest (const Expr *Cond, const BinaryOperator *BExpr, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, bool TookTrue, bool IsAssuming)
PathDiagnosticPieceRef VisitTrueTest (const Expr *Cond, const MemberExpr *ME, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, bool TookTrue, bool IsAssuming)
PathDiagnosticPieceRef VisitConditionVariable (StringRef LhsString, const Expr *CondVarExpr, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, bool TookTrue)
bool printValue (const Expr *CondVarExpr, raw_ostream &Out, const ExplodedNode *N, bool TookTrue, bool IsAssuming)
Tries to print the value of the given expression.
bool patternMatch (const Expr *Ex, const Expr *ParentEx, raw_ostream &Out, BugReporterContext &BRC, PathSensitiveBugReport &R, const ExplodedNode *N, std::optional< bool > &prunable, bool IsSameFieldName)
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
BugReporterVisitor & operator= (const BugReporterVisitor &)=delete
BugReporterVisitor & operator= (BugReporterVisitor &&)=delete
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
virtual PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR)
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Static Public Member Functions
static const char * getTag ()
Return the tag associated with this visitor.
static bool isPieceMessageGeneric (const PathDiagnosticPiece *Piece)
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
Visitor that tries to report interesting diagnostics from conditions.
Definition at line 446 of file BugReporterVisitors.h.
Member Function Documentation
getTag()
const char * ConditionBRVisitor::getTag () static
Return the tag associated with this visitor.
This tag will be used to make all PathDiagnosticPieces created by this visitor.
Definition at line 2738 of file BugReporterVisitors.cpp.
Referenced by eventsDescribeSameCondition().
isPieceMessageGeneric()
bool ConditionBRVisitor::isPieceMessageGeneric (const PathDiagnosticPiece * Piece) static
Definition at line 3264 of file BugReporterVisitors.cpp.
References clang::ento::PathDiagnosticPiece::getString().
Referenced by eventsDescribeSameCondition().
patternMatch()
bool ConditionBRVisitor::patternMatch (const Expr * Ex, const Expr * ParentEx, raw_ostream & Out, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, std::optional< bool > & prunable, bool IsSameFieldName)
Definition at line 2918 of file BugReporterVisitors.cpp.
References clang::ento::ProgramState::get(), clang::Lexer::getAsCharRange(), clang::ento::SVal::getAsRegion(), clang::ento::BugReporterContext::getASTContext(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::ASTContext::getLangOpts(), clang::ento::ProgramState::getLValue(), clang::ento::BugReporterContext::getSourceManager(), clang::Stmt::getSourceRange(), clang::Lexer::getSourceText(), clang::ento::ProgramState::getSVal(), clang::CharSourceRange::getTokenRange(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::isa(), clang::Lexer::isAtEndOfMacroExpansion(), clang::Lexer::isAtStartOfMacroExpansion(), clang::ento::PathSensitiveBugReport::isInteresting(), clang::SourceLocation::isMacroID(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), N, SM, and V.
printValue()
bool ConditionBRVisitor::printValue (const Expr * CondVarExpr, raw_ostream & Out, const ExplodedNode * N, bool TookTrue, bool IsAssuming)
Tries to print the value of the given expression.
Parameters
CondVarExpr The expression to print its value.
Out The stream to print.
N The node where we encountered the condition.
TookTrue Whether we took the true branch of the condition.
Returns
Whether the print was successful. (The printing is successful if we model the value and we could obtain it.)
Definition at line 3224 of file BugReporterVisitors.cpp.
References getConcreteIntegerValue(), clang::Expr::getType(), clang::Type::isBooleanType(), clang::Type::isIntegralOrEnumerationType(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), and N.
Profile()
void clang::ento::ConditionBRVisitor::Profile (llvm::FoldingSetNodeID & ID) const inline override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 454 of file BugReporterVisitors.h.
VisitConditionVariable()
PathDiagnosticPieceRef ConditionBRVisitor::VisitConditionVariable (StringRef LhsString, const Expr * CondVarExpr, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, bool TookTrue)
Definition at line 3123 of file BugReporterVisitors.cpp.
References clang::ento::BugReporterContext::getSourceManager(), isInterestingExpr(), isVarAnInterestingCondition(), N, and WillBeUsedForACondition.
VisitNode()
PathDiagnosticPieceRef ConditionBRVisitor::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 2741 of file BugReporterVisitors.cpp.
References N.
VisitNodeImpl()
PathDiagnosticPieceRef ConditionBRVisitor::VisitNodeImpl (const ExplodedNode * N, BugReporterContext & BRC, PathSensitiveBugReport & BR)
Definition at line 2753 of file BugReporterVisitors.cpp.
References clang::ProgramPoint::getAs(), clang::ento::ExprEngine::geteagerlyAssumeBinOpBifurcationTags(), clang::CFGBlock::getTerminatorStmt(), and N.
VisitTerminator()
PathDiagnosticPieceRef ConditionBRVisitor::VisitTerminator (const Stmt * Term, const ExplodedNode * N, const CFGBlock * SrcBlk, const CFGBlock * DstBlk, PathSensitiveBugReport & R, BugReporterContext & BRC)
Definition at line 2791 of file BugReporterVisitors.cpp.
References clang::cast(), clang::Cond, clang::Stmt::getStmtClass(), clang::Expr::IgnoreParens(), N, clang::CFGBlock::succ_begin(), and clang::CFGBlock::succ_size().
VisitTrueTest() [1/4]
PathDiagnosticPieceRef ConditionBRVisitor::VisitTrueTest (const Expr * Cond, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, bool TookTrue)
Definition at line 2850 of file BugReporterVisitors.cpp.
References clang::cast(), clang::Cond, clang::ento::BugReporterContext::getSourceManager(), clang::ento::BugReporterContext::getStateManager(), clang::Stmt::getStmtClass(), clang::ento::ProgramStateManager::haveEqualConstraints(), clang::Expr::IgnoreParenCasts(), clang::ento::DefinedSVal::isValid(), N, and P.
VisitTrueTest() [2/4]
PathDiagnosticPieceRef ConditionBRVisitor::VisitTrueTest (const Expr * Cond, const BinaryOperator * BExpr, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, bool TookTrue, bool IsAssuming)
Definition at line 3003 of file BugReporterVisitors.cpp.
References clang::Cond, clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getRHS(), clang::ento::BugReporterContext::getSourceManager(), clang::Expr::IgnoreParenCasts(), clang::BinaryOperator::isAssignmentOp(), clang::BinaryOperator::isComparisonOp(), isVarAnInterestingCondition(), N, SM, and WillBeUsedForACondition.
VisitTrueTest() [3/4]
PathDiagnosticPieceRef ConditionBRVisitor::VisitTrueTest (const Expr * Cond, const DeclRefExpr * DR, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, bool TookTrue, bool IsAssuming)
Definition at line 3150 of file BugReporterVisitors.cpp.
References clang::Cond, clang::DeclRefExpr::getDecl(), clang::ento::BugReporterContext::getSourceManager(), isInterestingExpr(), isVarAnInterestingCondition(), N, and WillBeUsedForACondition.
VisitTrueTest() [4/4]
PathDiagnosticPieceRef ConditionBRVisitor::VisitTrueTest (const Expr * Cond, const MemberExpr * ME, BugReporterContext & BRC, PathSensitiveBugReport & R, const ExplodedNode * N, bool TookTrue, bool IsAssuming)
Definition at line 3186 of file BugReporterVisitors.cpp.
References clang::Cond, clang::MemberExpr::getMemberDecl(), clang::MemberExpr::getMemberLoc(), clang::NamedDecl::getName(), clang::ento::BugReporterContext::getSourceManager(), isInterestingExpr(), clang::ento::DefinedSVal::isValid(), clang::SourceLocation::isValid(), isVarAnInterestingCondition(), N, and WillBeUsedForACondition.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp