clang: clang::TemplateSpecCandidateSet Class Reference
clang::TemplateSpecCandidateSet Class Reference
TemplateSpecCandidateSet - A set of generalized overload candidates, used in template specializations.
#include "clang/Sema/TemplateDeduction.h"
Public Types
using iterator = SmallVector<TemplateSpecCandidate, 16>::iterator
Public Member Functions
TemplateSpecCandidateSet (SourceLocation Loc, bool ForTakingAddress=false)
TemplateSpecCandidateSet (const TemplateSpecCandidateSet &)=delete
TemplateSpecCandidateSet & operator= (const TemplateSpecCandidateSet &)=delete
~TemplateSpecCandidateSet ()
SourceLocation getLocation () const
void clear ()
Clear out all of the candidates.
iterator begin ()
iterator end ()
size_t size () const
bool empty () const
TemplateSpecCandidate & addCandidate ()
Add a new candidate with NumConversions conversion sequence slots to the overload set.
void NoteCandidates (Sema &S, SourceLocation Loc)
NoteCandidates - When no template specialization match is found, prints diagnostic messages containing the non-matching specializations that form the candidate set.
void NoteCandidates (Sema &S, SourceLocation Loc) const
Detailed Description
TemplateSpecCandidateSet - A set of generalized overload candidates, used in template specializations.
TODO: In the future, we may need to unify/generalize this with OverloadCandidateSet.
Definition at line 333 of file TemplateDeduction.h.
Member Typedef Documentation
iterator
using clang::TemplateSpecCandidateSet::iterator = SmallVector<TemplateSpecCandidate, 16>::iterator
Definition at line 358 of file TemplateDeduction.h.
Constructor & Destructor Documentation
TemplateSpecCandidateSet() [1/2]
clang::TemplateSpecCandidateSet::TemplateSpecCandidateSet (SourceLocation Loc, bool ForTakingAddress = false) inline
Definition at line 345 of file TemplateDeduction.h.
TemplateSpecCandidateSet() [2/2]
clang::TemplateSpecCandidateSet::TemplateSpecCandidateSet (const TemplateSpecCandidateSet &) delete
~TemplateSpecCandidateSet()
clang::TemplateSpecCandidateSet::~TemplateSpecCandidateSet () inline
Definition at line 350 of file TemplateDeduction.h.
Member Function Documentation
addCandidate()
TemplateSpecCandidate & clang::TemplateSpecCandidateSet::addCandidate () inline
Add a new candidate with NumConversions conversion sequence slots to the overload set.
Definition at line 368 of file TemplateDeduction.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckVarTemplateId(), getPatternForClassTemplateSpecialization(), and clang::Sema::ResolveSingleFunctionTemplateSpecialization().
begin()
iterator clang::TemplateSpecCandidateSet::begin () inline
Definition at line 360 of file TemplateDeduction.h.
clear()
void TemplateSpecCandidateSet::clear ()
Clear out all of the candidates.
TODO: This may be unnecessary.
Definition at line 12182 of file SemaOverload.cpp.
empty()
bool clang::TemplateSpecCandidateSet::empty () const inline
Definition at line 364 of file TemplateDeduction.h.
end()
iterator clang::TemplateSpecCandidateSet::end () inline
Definition at line 361 of file TemplateDeduction.h.
getLocation()
SourceLocation clang::TemplateSpecCandidateSet::getLocation () const inline
Definition at line 352 of file TemplateDeduction.h.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckVarTemplateId(), and getPatternForClassTemplateSpecialization().
NoteCandidates() [1/2]
void TemplateSpecCandidateSet::NoteCandidates (Sema & S, SourceLocation Loc)
NoteCandidates - When no template specialization match is found, prints diagnostic messages containing the non-matching specializations that form the candidate set.
This is analoguous to OverloadCandidateSet::NoteCandidates() with OCD == OCD_AllCandidates and Cand->Viable == false.
Definition at line 12192 of file SemaOverload.cpp.
References clang::OverloadCandidateSet::begin(), clang::Sema::Diag(), clang::Sema::Diags, clang::OverloadCandidateSet::end(), clang::DiagnosticsEngine::getShowOverloads(), int, clang::TemplateSpecCandidate::NoteDeductionFailure(), clang::Ovl_Best, clang::OverloadCandidateSet::size(), and clang::TemplateSpecCandidate::Specialization.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::getMostSpecialized(), and NoteCandidates().
NoteCandidates() [2/2]
void clang::TemplateSpecCandidateSet::NoteCandidates (Sema & S, SourceLocation Loc) const inline
Definition at line 375 of file TemplateDeduction.h.
References NoteCandidates().
operator=()
TemplateSpecCandidateSet & clang::TemplateSpecCandidateSet::operator= (const TemplateSpecCandidateSet &) delete
size()
size_t clang::TemplateSpecCandidateSet::size () const inline
Definition at line 363 of file TemplateDeduction.h.
The documentation for this class was generated from the following files:
include/clang/Sema/TemplateDeduction.h
lib/Sema/SemaOverload.cpp