clang: clang::Sema::InheritedConstructorInfo Class Reference
clang::Sema::InheritedConstructorInfo Class Reference
Public Member Functions
InheritedConstructorInfo (Sema &S, SourceLocation UseLoc, ConstructorUsingShadowDecl *Shadow)
std::pair< CXXConstructorDecl *, bool > findConstructorForBase (CXXRecordDecl *Base, CXXConstructorDecl *Ctor) const
Find the constructor to use for inherited construction of a base class, and whether that base class constructor inherits the constructor from a virtual base class (in which case it won't actually invoke it).
Detailed Description
Definition at line 7257 of file SemaDeclCXX.cpp.
Constructor & Destructor Documentation
InheritedConstructorInfo()
clang::Sema::InheritedConstructorInfo::InheritedConstructorInfo (Sema & S, SourceLocation UseLoc, ConstructorUsingShadowDecl * Shadow) inline
Definition at line 7268 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::if(), clang::Decl::isInvalidDecl(), and clang::Redeclarable< decl_type >::redecls().
Member Function Documentation
findConstructorForBase()
std::pair< CXXConstructorDecl *, bool > clang::Sema::InheritedConstructorInfo::findConstructorForBase (CXXRecordDecl * Base, CXXConstructorDecl * Ctor) const inline
Find the constructor to use for inherited construction of a base class, and whether that base class constructor inherits the constructor from a virtual base class (in which case it won't actually invoke it).
Definition at line 7322 of file SemaDeclCXX.cpp.
References clang::Sema::findInheritingConstructor().
Referenced by clang::Sema::DefineInheritingConstructor().
The documentation for this class was generated from the following file:
lib/Sema/SemaDeclCXX.cpp