clang: clang::format::IndexedTokenSource Class Reference
clang::format::IndexedTokenSource Class Reference
#include "/root/llvm-project/clang/lib/Format/FormatTokenSource.h"
Public Member Functions
IndexedTokenSource (ArrayRef< FormatToken * > Tokens)
FormatToken * getNextToken () override
FormatToken * getPreviousToken () override
FormatToken * peekNextToken (bool SkipComment=false) override
bool isEOF () override
unsigned getPosition () override
FormatToken * setPosition (unsigned P) override
FormatToken * insertTokens (ArrayRef< FormatToken * > New) override
void reset ()
Public Member Functions inherited from clang::format::FormatTokenSource
virtual ~FormatTokenSource ()
Detailed Description
Definition at line 80 of file FormatTokenSource.h.
Constructor & Destructor Documentation
IndexedTokenSource()
clang::format::IndexedTokenSource::IndexedTokenSource (ArrayRef< FormatToken * > Tokens) inline
Definition at line 82 of file FormatTokenSource.h.
Member Function Documentation
getNextToken()
FormatToken * clang::format::IndexedTokenSource::getNextToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 85 of file FormatTokenSource.h.
References isEOF().
getPosition()
unsigned clang::format::IndexedTokenSource::getPosition () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 124 of file FormatTokenSource.h.
getPreviousToken()
FormatToken * clang::format::IndexedTokenSource::getPreviousToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 101 of file FormatTokenSource.h.
References is().
insertTokens()
FormatToken * clang::format::IndexedTokenSource::insertTokens (ArrayRef< FormatToken * > New) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 136 of file FormatTokenSource.h.
References Next.
isEOF()
bool clang::format::IndexedTokenSource::isEOF () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 120 of file FormatTokenSource.h.
References false.
Referenced by getNextToken(), and peekNextToken().
peekNextToken()
FormatToken * clang::format::IndexedTokenSource::peekNextToken (bool SkipComment = false) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 106 of file FormatTokenSource.h.
References is(), isEOF(), and Next.
reset()
void clang::format::IndexedTokenSource::reset () inline
Definition at line 157 of file FormatTokenSource.h.
Referenced by clang::format::UnwrappedLineParser::parse().
setPosition()
FormatToken * clang::format::IndexedTokenSource::setPosition (unsigned P) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 130 of file FormatTokenSource.h.
References P.
The documentation for this class was generated from the following file:
lib/Format/FormatTokenSource.h