clang: clang::format::LeftRightQualifierAlignmentFixer Class Reference
clang::format::LeftRightQualifierAlignmentFixer Class Reference
#include "/root/llvm-project/clang/lib/Format/QualifierAlignmentFixer.h"
Public Member Functions
LeftRightQualifierAlignmentFixer (const Environment &Env, const FormatStyle &Style, const std::string &Qualifier, const std::vector< tok::TokenKind > &ConfiguredQualifierTokens, bool RightAlign)
std::pair< tooling::Replacements, unsigned > analyze (TokenAnnotator &Annotator, SmallVectorImpl< AnnotatedLine * > &AnnotatedLines, FormatTokenLexer &Tokens) override
const FormatToken * analyzeRight (const SourceManager &SourceMgr, const AdditionalKeywords &Keywords, tooling::Replacements &Fixes, const FormatToken *Tok, const std::string &Qualifier, tok::TokenKind QualifierType)
const FormatToken * analyzeLeft (const SourceManager &SourceMgr, const AdditionalKeywords &Keywords, tooling::Replacements &Fixes, const FormatToken *Tok, const std::string &Qualifier, tok::TokenKind QualifierType)
Public Member Functions inherited from clang::format::TokenAnalyzer
TokenAnalyzer (const Environment &Env, const FormatStyle &Style)
std::pair< tooling::Replacements, unsigned > process (bool SkipAnnotation=false)
Public Member Functions inherited from clang::format::UnwrappedLineConsumer
virtual ~UnwrappedLineConsumer ()
Static Public Member Functions
static tok::TokenKind getTokenFromQualifier (const std::string &Qualifier)
static bool isQualifierOrType (const FormatToken *Tok)
static bool isConfiguredQualifierOrType (const FormatToken *Tok, const std::vector< tok::TokenKind > &Qualifiers)
static bool isPossibleMacro (const FormatToken *Tok)
Additional Inherited Members
Protected Member Functions inherited from clang::format::TokenAnalyzer
void consumeUnwrappedLine (const UnwrappedLine &TheLine) override
void finishRun () override
Protected Attributes inherited from clang::format::TokenAnalyzer
FormatStyle Style
const Environment & Env
AffectedRangeManager AffectedRangeMgr
SmallVector< SmallVector< UnwrappedLine, 16 >, 2 > UnwrappedLines
encoding::Encoding Encoding
Detailed Description
Definition at line 36 of file QualifierAlignmentFixer.h.
Constructor & Destructor Documentation
LeftRightQualifierAlignmentFixer()
clang::format::LeftRightQualifierAlignmentFixer::LeftRightQualifierAlignmentFixer (const Environment & Env, const FormatStyle & Style, const std::string & Qualifier, const std::vector< tok::TokenKind > & ConfiguredQualifierTokens, bool RightAlign)
Definition at line 519 of file QualifierAlignmentFixer.cpp.
Member Function Documentation
analyze()
std::pair< tooling::Replacements, unsigned > clang::format::LeftRightQualifierAlignmentFixer::analyze (TokenAnnotator & Annotator, SmallVectorImpl< AnnotatedLine * > & AnnotatedLines, FormatTokenLexer & Tokens) override virtual
Implements clang::format::TokenAnalyzer.
Definition at line 527 of file QualifierAlignmentFixer.cpp.
References clang::format::TokenAnalyzer::AffectedRangeMgr, analyzeLeft(), analyzeRight(), clang::format::AffectedRangeManager::computeAffectedLines(), clang::format::TokenAnalyzer::Env, clang::First, clang::format::Environment::getSourceManager(), getTokenFromQualifier(), clang::Last, and Tok.
analyzeLeft()
const FormatToken * clang::format::LeftRightQualifierAlignmentFixer::analyzeLeft (const SourceManager & SourceMgr, const AdditionalKeywords & Keywords, tooling::Replacements & Fixes, const FormatToken * Tok, const std::string & Qualifier, tok::TokenKind QualifierType)
Definition at line 365 of file QualifierAlignmentFixer.cpp.
References clang::format::FormatToken::ClosesRequiresClause, clang::format::FormatToken::ClosesTemplateDeclaration, clang::format::insertQualifierBefore(), clang::format::FormatToken::is(), clang::format::isConfiguredQualifier(), isConfiguredQualifierOrType(), clang::format::FormatToken::isOneOf(), isPossibleMacro(), clang::format::isQualifier(), clang::format::FormatToken::MatchingParen, Previous, clang::format::removeToken(), clang::format::rotateTokens(), and Tok.
Referenced by analyze().
analyzeRight()
const FormatToken * clang::format::LeftRightQualifierAlignmentFixer::analyzeRight (const SourceManager & SourceMgr, const AdditionalKeywords & Keywords, tooling::Replacements & Fixes, const FormatToken * Tok, const std::string & Qualifier, tok::TokenKind QualifierType)
Definition at line 179 of file QualifierAlignmentFixer.cpp.
References clang::format::FormatToken::ClosesRequiresClause, clang::format::FormatToken::ClosesTemplateDeclaration, clang::CharSourceRange::getCharRange(), clang::format::insertQualifierAfter(), clang::format::FormatToken::is(), clang::format::FormatToken::isOneOf(), isPossibleMacro(), clang::format::isQualifier(), isQualifierOrType(), clang::format::FormatToken::MatchingParen, Next, clang::format::replaceToken(), clang::format::rotateTokens(), and Tok.
Referenced by analyze().
getTokenFromQualifier()
tok::TokenKind clang::format::LeftRightQualifierAlignmentFixer::getTokenFromQualifier (const std::string & Qualifier) static
Definition at line 504 of file QualifierAlignmentFixer.cpp.
Referenced by analyze(), clang::format::prepareLeftRightOrderingForQualifierAlignmentFixer(), and clang::format::validateQualifierOrder().
isConfiguredQualifierOrType()
bool clang::format::LeftRightQualifierAlignmentFixer::isConfiguredQualifierOrType (const FormatToken * Tok, const std::vector< tok::TokenKind > & Qualifiers) static
Definition at line 605 of file QualifierAlignmentFixer.cpp.
References clang::format::isConfiguredQualifier(), and Tok.
Referenced by analyzeLeft().
isPossibleMacro()
bool clang::format::LeftRightQualifierAlignmentFixer::isPossibleMacro (const FormatToken * Tok) static
Definition at line 614 of file QualifierAlignmentFixer.cpp.
References Tok.
Referenced by analyzeLeft(), and analyzeRight().
isQualifierOrType()
bool clang::format::LeftRightQualifierAlignmentFixer::isQualifierOrType (const FormatToken * Tok) static
Definition at line 599 of file QualifierAlignmentFixer.cpp.
References clang::format::isQualifier(), and Tok.
Referenced by analyzeRight().
The documentation for this class was generated from the following files:
lib/Format/QualifierAlignmentFixer.h
lib/Format/QualifierAlignmentFixer.cpp