clang: clang::ento::CheckerBase Class Reference
clang::ento::CheckerBase Class Reference
#include "clang/StaticAnalyzer/Core/Checker.h"
Public Member Functions
StringRef getTagDescription () const override
CheckerNameRef getCheckerName () const
virtual void printState (raw_ostream &Out, ProgramStateRef State, const char *NL, const char *Sep) const
See CheckerManager::runCheckersForPrintState.
Public Member Functions inherited from clang::ProgramPointTag
ProgramPointTag (void *tagKind=nullptr)
virtual ~ProgramPointTag ()
const void * getTagKind () const
Used to implement 'isKind' in subclasses.
Friends
class ::clang::ento::CheckerManager
Detailed Description
Definition at line 491 of file Checker.h.
Member Function Documentation
getCheckerName()
CheckerNameRef CheckerBase::getCheckerName () const
Definition at line 25 of file Checker.cpp.
Referenced by clang::ento::BugReporter::EmitBasicReport(), clang::ento::BugType::getCheckerName(), getTagDescription(), and clang::ento::operator<<().
getTagDescription()
StringRef CheckerBase::getTagDescription () const override virtual
Implements clang::ProgramPointTag.
Definition at line 21 of file Checker.cpp.
References getCheckerName(), and clang::ento::CheckerNameRef::getName().
printState()
virtual void clang::ento::CheckerBase::printState (raw_ostream & Out, ProgramStateRef State, const char * NL, const char * Sep) const inline virtual
See CheckerManager::runCheckersForPrintState.
Reimplemented in clang::ento::retaincountchecker::RetainCountChecker.
Definition at line 500 of file Checker.h.
Friends And Related Symbol Documentation
::clang::ento::CheckerManager
friend class ::clang::ento::CheckerManager friend
Definition at line 493 of file Checker.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/Checker.h
lib/StaticAnalyzer/Core/Checker.cpp