clang: clang::Expr Class Reference
clang::Expr Class Reference
This represents one expression.
#include "clang/AST/Expr.h"
Inherits clang::ValueStmt.
Inherited by clang::AbstractConditionalOperator, clang::AddrLabelExpr, clang::ArrayInitIndexExpr, clang::ArrayInitLoopExpr, clang::ArraySubscriptExpr, clang::ArrayTypeTraitExpr, clang::AsTypeExpr, clang::AtomicExpr, clang::BinaryOperator, clang::BlockExpr, clang::CXXBindTemporaryExpr, clang::CXXBoolLiteralExpr, clang::CXXConstructExpr, clang::CXXDefaultArgExpr, clang::CXXDefaultInitExpr, clang::CXXDeleteExpr, clang::CXXDependentScopeMemberExpr, clang::CXXFoldExpr, clang::CXXInheritedCtorInitExpr, clang::CXXNewExpr, clang::CXXNoexceptExpr, clang::CXXNullPtrLiteralExpr, clang::CXXParenListInitExpr, clang::CXXPseudoDestructorExpr, clang::CXXRewrittenBinaryOperator, clang::CXXScalarValueInitExpr, clang::CXXStdInitializerListExpr, clang::CXXThisExpr, clang::CXXThrowExpr, clang::CXXTypeidExpr, clang::CXXUnresolvedConstructExpr, clang::CXXUuidofExpr, clang::CallExpr, clang::CastExpr, clang::CharacterLiteral, clang::ChooseExpr, clang::CompoundLiteralExpr, clang::ConceptSpecializationExpr, clang::ConvertVectorExpr, clang::CoroutineSuspendExpr, clang::DeclRefExpr, clang::DependentCoawaitExpr, clang::DependentScopeDeclRefExpr, clang::DesignatedInitExpr, clang::DesignatedInitUpdateExpr, clang::ExpressionTraitExpr, clang::ExtVectorElementExpr, clang::FixedPointLiteral, clang::FloatingLiteral, clang::FullExpr, clang::FunctionParmPackExpr, clang::GNUNullExpr, clang::GenericSelectionExpr, clang::ImaginaryLiteral, clang::ImplicitValueInitExpr, clang::InitListExpr, clang::IntegerLiteral, clang::LambdaExpr, clang::MSPropertyRefExpr, clang::MSPropertySubscriptExpr, clang::MaterializeTemporaryExpr, clang::MatrixSubscriptExpr, clang::MemberExpr, clang::NoInitExpr, clang::OMPArraySectionExpr, clang::OMPArrayShapingExpr, clang::OMPIteratorExpr, clang::ObjCArrayLiteral, clang::ObjCAvailabilityCheckExpr, clang::ObjCBoolLiteralExpr, clang::ObjCBoxedExpr, clang::ObjCDictionaryLiteral, clang::ObjCEncodeExpr, clang::ObjCIndirectCopyRestoreExpr, clang::ObjCIsaExpr, clang::ObjCIvarRefExpr, clang::ObjCMessageExpr, clang::ObjCPropertyRefExpr, clang::ObjCProtocolExpr, clang::ObjCSelectorExpr, clang::ObjCStringLiteral, clang::ObjCSubscriptRefExpr, clang::OffsetOfExpr, clang::OpaqueValueExpr, clang::OverloadExpr, clang::PackExpansionExpr, clang::ParenExpr, clang::ParenListExpr, clang::PredefinedExpr, clang::PseudoObjectExpr, clang::RecoveryExpr, clang::RequiresExpr, clang::SYCLUniqueStableNameExpr, clang::ShuffleVectorExpr, clang::SizeOfPackExpr, clang::SourceLocExpr, clang::StmtExpr, clang::StringLiteral, clang::SubstNonTypeTemplateParmExpr, clang::SubstNonTypeTemplateParmPackExpr, clang::TypeTraitExpr, clang::TypoExpr, clang::UnaryExprOrTypeTraitExpr, clang::UnaryOperator, and clang::VAArgExpr.
Classes
class Classification
The return type of classify().
struct EvalResult
EvalResult is a struct with detailed info about an evaluated expression.
struct EvalStatus
EvalStatus is a struct with detailed info about an evaluation in progress.
Public Types
enum LValueClassification {
LV_Valid , LV_NotObjectType , LV_IncompleteVoidType , LV_DuplicateVectorComponents ,
LV_InvalidExpression , LV_InvalidMessageExpression , LV_MemberFunction , LV_SubObjCPropertySetting ,
LV_ClassTemporary , LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid , MLV_NotObjectType , MLV_IncompleteVoidType , MLV_DuplicateVectorComponents ,
MLV_InvalidExpression , MLV_LValueCast , MLV_IncompleteType , MLV_ConstQualified ,
MLV_ConstQualifiedField , MLV_ConstAddrSpace , MLV_ArrayType , MLV_NoSetterProperty ,
MLV_MemberFunction , MLV_SubObjCPropertySetting , MLV_InvalidMessageExpression , MLV_ClassTemporary ,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects , SE_AllowUndefinedBehavior , SE_AllowSideEffects }
enum class ConstantExprKind { Normal , NonClassTemplateArgument , ClassTemplateArgument , ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0 , NPCK_ZeroExpression , NPCK_ZeroLiteral , NPCK_CXX11_nullptr ,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0 , NPC_ValueDependentIsNull , NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
bool isFlexibleArrayMemberLike (ASTContext &Context, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution=false) const
Check whether this array fits the idiom of a flexible array member, depending on the value of -fstrict-flex-array.
std::optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr, bool isEvaluated=true) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFixedPoint - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
bool EvaluateCharRangeAsString (std::string &Result, const Expr *SizeExpression, const Expr *PtrExpression, ASTContext &Ctx, EvalResult &Status) const
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisible AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parentheses and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluted - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Protected Member Functions
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Friends
class ASTImporter
class ASTStmtReader
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
This represents one expression.
Note that Expr's are subclasses of Stmt. This allows an expression to be transparently used any place a Stmt is required.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 110 of file Expr.h.
Member Enumeration Documentation
ConstantExprKind
enum class clang::Expr::ConstantExprKind strong
Enumerator
Normal
An integer constant expression (an array bound, enumerator, case value, bit-field width, or similar) or similar.
NonClassTemplateArgument
A non-class template argument.
Such a value is only used for mangling, not for code generation, so can refer to dllimported functions.
ClassTemplateArgument
A class template argument. Such a value is used for code generation.
ImmediateInvocation
An immediate invocation.
The destruction of the end result of this evaluation is not part of the evaluation, but all other temporaries are destroyed.
Definition at line 728 of file Expr.h.
isModifiableLvalueResult
enum clang::Expr::isModifiableLvalueResult
Enumerator
MLV_Valid
MLV_NotObjectType
MLV_IncompleteVoidType
MLV_DuplicateVectorComponents
MLV_InvalidExpression
MLV_LValueCast
MLV_IncompleteType
MLV_ConstQualified
MLV_ConstQualifiedField
MLV_ConstAddrSpace
MLV_ArrayType
MLV_NoSetterProperty
MLV_MemberFunction
MLV_SubObjCPropertySetting
MLV_InvalidMessageExpression
MLV_ClassTemporary
MLV_ArrayTemporary
Definition at line 291 of file Expr.h.
LValueClassification
enum clang::Expr::LValueClassification
Enumerator
LV_Valid
LV_NotObjectType
LV_IncompleteVoidType
LV_DuplicateVectorComponents
LV_InvalidExpression
LV_InvalidMessageExpression
LV_MemberFunction
LV_SubObjCPropertySetting
LV_ClassTemporary
LV_ArrayTemporary
Definition at line 276 of file Expr.h.
NullPointerConstantKind
enum clang::Expr::NullPointerConstantKind
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
Enumerator
NPCK_NotNull
Expression is not a Null pointer constant.
NPCK_ZeroExpression
Expression is a Null pointer constant built from a zero integer expression that is not a simple, possibly parenthesized, zero literal.
C++ Core Issue 903 will classify these expressions as "not pointers" once it is adopted. http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#903
NPCK_ZeroLiteral
Expression is a Null pointer constant built from a literal zero.
NPCK_CXX11_nullptr
Expression is a C++11 nullptr.
NPCK_GNUNull
Expression is a GNU-style __null constant.
Definition at line 772 of file Expr.h.
NullPointerConstantValueDependence
enum clang::Expr::NullPointerConstantValueDependence
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Enumerator
NPC_NeverValueDependent
Specifies that the expression should never be value-dependent.
NPC_ValueDependentIsNull
Specifies that a value-dependent expression of integral or dependent type should be considered a null pointer constant.
NPC_ValueDependentIsNotNull
Specifies that a value-dependent expression should be considered to never be a null pointer constant.
Definition at line 795 of file Expr.h.
SideEffectsKind
enum clang::Expr::SideEffectsKind
Enumerator
SE_NoSideEffects
Strictly evaluate the expression.
SE_AllowUndefinedBehavior
Allow UB that we can give a value, but not arbitrary unmodeled side effects.
SE_AllowSideEffects
Allow any unmodeled side effect.
Definition at line 647 of file Expr.h.
Constructor & Destructor Documentation
Expr() [1/5]
clang::Expr::Expr () delete
Expr() [2/5]
clang::Expr::Expr (const Expr &) delete
Expr() [3/5]
clang::Expr::Expr (Expr &&) delete
Expr() [4/5]
clang::Expr::Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK) inline protected
Definition at line 121 of file Expr.h.
References clang::Stmt::ExprBits, and setType().
Expr() [5/5]
clang::Expr::Expr (StmtClass SC, EmptyShell) inline explicit protected
Construct an empty expression.
Definition at line 131 of file Expr.h.
Member Function Documentation
Classify()
Classification clang::Expr::Classify (ASTContext & Ctx) const inline
Classify - Classify this expression according to the C++11 expression taxonomy.
C++11 defines ([basic.lval]) a new taxonomy of expressions to replace the old lvalue vs rvalue. This function determines the type of expression this is. There are three expression types:
lvalues are classical lvalues as in C++03.
prvalues are equivalent to rvalues in C++03.
xvalues are expressions yielding unnamed rvalue references, e.g. a function returning an rvalue reference. lvalues and xvalues are collectively referred to as glvalues, while prvalues and xvalues together form rvalues.
Definition at line 399 of file Expr.h.
Referenced by clang::Sema::AddConversionCandidate(), clang::Sema::AddFunctionCandidates(), clang::Sema::BuildCallToMemberFunction(), clang::canTypeidThrow(), clang::Sema::CheckPointerToMemberOperands(), ClassifyLValue(), isTemporaryObject(), clang::Sema::LookupSpecialMember(), and clang::Sema::PerformObjectArgumentInitialization().
ClassifyLValue()
Expr::LValueClassification Expr::ClassifyLValue (ASTContext & Ctx) const
Reasons why an expression might not be an l-value.
Definition at line 682 of file ExprClassification.cpp.
References clang::Expr::Classification::CL_AddressableVoid, clang::Expr::Classification::CL_ArrayTemporary, clang::Expr::Classification::CL_ClassTemporary, clang::Expr::Classification::CL_DuplicateVectorComponents, clang::Expr::Classification::CL_Function, clang::Expr::Classification::CL_LValue, clang::Expr::Classification::CL_MemberFunction, clang::Expr::Classification::CL_ObjCMessageRValue, clang::Expr::Classification::CL_PRValue, clang::Expr::Classification::CL_SubObjCPropertySetting, clang::Expr::Classification::CL_Void, clang::Expr::Classification::CL_XValue, Classify(), clang::Expr::Classification::getKind(), LV_ArrayTemporary, LV_ClassTemporary, LV_DuplicateVectorComponents, LV_IncompleteVoidType, LV_InvalidExpression, LV_InvalidMessageExpression, LV_MemberFunction, LV_NotObjectType, LV_SubObjCPropertySetting, and LV_Valid.
Referenced by clang::Sema::CheckAddressOfOperand(), and isBoundMemberFunction().
ClassifyModifiable()
Classification clang::Expr::ClassifyModifiable (ASTContext & Ctx, SourceLocation & Loc) const inline
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
This function extends classify in that it also tests whether the expression is modifiable (C99 6.3.2.1p1).
Parameters
Loc A source location that might be filled with a relevant location if the expression is not modifiable.
Definition at line 411 of file Expr.h.
Referenced by isModifiableLvalue().
classof()
static bool clang::Expr::classof (const Stmt * T) inline static
Definition at line 1001 of file Expr.h.
containsErrors()
bool clang::Expr::containsErrors () const inline
Whether this expression contains subexpressions which had errors, e.g.
a TypoExpr.
Definition at line 239 of file Expr.h.
References getDependence().
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildBinOp(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildDelegatingInitializer(), calculateConstraintSatisfaction(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckEnumConstant(), clang::interp::ByteCodeExprGen< Emitter >::discard(), EvaluateDependentExpr(), clang::Sema::FinalizeVarWithDestructor(), isNullPointerConstant(), clang::Sema::VerifyBitField(), and clang::interp::ByteCodeExprGen< Emitter >::visit().
containsUnexpandedParameterPack()
bool clang::Expr::containsUnexpandedParameterPack () const inline
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
Given the following function template:
template<typename F, typename ...Types>
void forward(const F &f, Types &&...args) {
  f(static_cast<Types&&>(args)...);
}
The expressions args and static_cast<Types&&>(args) both contain parameter packs.
Definition at line 233 of file Expr.h.
References getDependence().
Referenced by clang::Sema::ActOnCXXFoldExpr(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPInitClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPScheduleClause(), applyOMPAllocateAttribute(), checkMappableExpressionList(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CheckPackExpansion(), checkSimdlenSafelenSpecified(), clang::Sema::containsUnexpandedParameterPacks(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::Sema::DiagnoseUnexpandedParameterPackInRequiresExpr(), getPrivateItem(), handleAlignedAttr(), clang::CXXFoldExpr::isRightFold(), processImplicitMapsWithDefaultMappers(), clang::Sema::VerifyPositiveIntegerConstantInClause(), clang::ASTNodeImporter::VisitGenericSelectionExpr(), and clang::ASTNodeImporter::VisitLambdaExpr().
EvaluateAsBooleanCondition()
bool Expr::EvaluateAsBooleanCondition (bool & Result, const ASTContext & Ctx, bool InConstantContext = false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
Definition at line 15308 of file ExprConstant.cpp.
References EvaluateAsRValue(), and HandleConversionToBool().
Referenced by CheckNonNullExpr(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsForTargetDirective(), FindTypeTagExpr(), getNumThreads(), and clang::CallExpr::isBuiltinAssumeFalse().
EvaluateAsConstantExpr()
bool Expr::EvaluateAsConstantExpr (EvalResult & Result, const ASTContext & Ctx, ConstantExprKind Kind = ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
Does not check the syntactic constraints for C and C++98 constant expressions.
Definition at line 15405 of file ExprConstant.cpp.
References CheckConstantExpression(), CheckMemoryLeaks(), EvaluateDestruction(), EvaluateInPlace(), FastEvaluateAsRValue(), and getType().
Referenced by calculateConstraintSatisfaction(), clang::Sema::CheckForImmediateInvocation(), clang::computeDependence(), clang::Sema::ConstantFoldAttrArgs(), EvaluateAndDiagnoseImmediateInvocation(), EvaluateConvertedConstantExpression(), and getAsBuiltinConstantDeclRef().
EvaluateAsFixedPoint()
bool Expr::EvaluateAsFixedPoint (EvalResult & Result, const ASTContext & Ctx, SideEffectsKind AllowSideEffects = SE_NoSideEffects, bool InConstantContext = false) const
EvaluateAsFixedPoint - Return true if this is a constant which we can fold and convert to a fixed point value.
Definition at line 15329 of file ExprConstant.cpp.
Referenced by CheckImplicitConversion().
EvaluateAsFloat()
bool Expr::EvaluateAsFloat (llvm::APFloat & Result, const ASTContext & Ctx, SideEffectsKind AllowSideEffects = SE_NoSideEffects, bool InConstantContext = false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
Definition at line 15340 of file ExprConstant.cpp.
References EvaluateAsRValue(), getType(), and hasUnacceptableSideEffect().
Referenced by DiagnoseFloatingImpCast().
EvaluateAsInitializer()
bool Expr::EvaluateAsInitializer (APValue & Result, const ASTContext & Ctx, const VarDecl * VD, SmallVectorImpl< PartialDiagnosticAt > & Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
Returns true if the initializer can be folded to a constant, and produces any relevant notes. In C++11, notes will be produced if the expression is not a constant expression.
Definition at line 15467 of file ExprConstant.cpp.
References CheckConstantExpression(), CheckMemoryLeaks(), clang::Expr::EvalStatus::Diag, EvaluateInPlace(), clang::ASTContext::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), and clang::NamedDecl::printQualifiedName().
EvaluateAsInt()
bool Expr::EvaluateAsInt (EvalResult & Result, const ASTContext & Ctx, SideEffectsKind AllowSideEffects = SE_NoSideEffects, bool InConstantContext = false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
Definition at line 15318 of file ExprConstant.cpp.
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPDependClause(), AnalyzeBitFieldAssignment(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), checkArrayExpressionDoesNotReferToUnitySize(), checkArrayExpressionDoesNotReferToWholeSize(), checkFormatStringExpr(), CheckImplicitConversion(), clang::Sema::CheckLogicalOperands(), CheckObjCDictionaryLiteralDuplicateKeys(), checkOMPArraySectionConstantForReduction(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSubtractionOperands(), DiagnoseBadDivideOrRemainderValues(), DiagnoseBadShiftValues(), DiagnoseIntInBoolContext(), getBytesReturnedByAllocSizeCall(), clang::ento::SValBuilder::getConstantVal(), isConstantInitializer(), SemaBuiltinAlignment(), TryToFixInvalidVariablyModifiedType(), and clang::ento::ExprEngine::VisitOffsetOfExpr().
EvaluateAsLValue()
bool Expr::EvaluateAsLValue (EvalResult & Result, const ASTContext & Ctx, bool InConstantContext = false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
Definition at line 15360 of file ExprConstant.cpp.
References CheckLValueConstantExpression(), EvaluateLValue(), clang::ASTContext::getLValueReferenceType(), and getType().
Referenced by clang::Sema::FillInlineAsmIdentifierInfo(), isConstantInitializer(), and clang::CodeGen::ConstantEmitter::tryEmitPrivate().
EvaluateAsRValue()
bool Expr::EvaluateAsRValue (EvalResult & Result, const ASTContext & Ctx, bool InConstantContext = false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
EvaluateAsRValue - Return true if this is a constant which we can fold using any crazy technique (that has nothing to do with language standards) that we want to. If this function returns true, it returns the folded constant in Result. If this expression is a glvalue, an lvalue-to-rvalue conversion will be applied to the result.
If this function returns true, it returns the folded constant in Result. If the expression is a glvalue, an lvalue-to-rvalue conversion will be applied.
Definition at line 15298 of file ExprConstant.cpp.
Referenced by clang::Sema::ActOnGCCAsmStmt(), CheckImplicitConversion(), clang::Sema::DiagnoseStaticAssertDetails(), clang::Sema::FillInlineAsmIdentifierInfo(), GetExprRange(), isNullPointerValueTemplateArgument(), maybeConstEvalStringLiteral(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), and clang::Sema::VerifyIntegerConstantExpression().
EvaluateCharRangeAsString()
bool Expr::EvaluateCharRangeAsString (std::string & Result, const Expr * SizeExpression, const Expr * PtrExpression, ASTContext & Ctx, EvalResult & Status) const
Definition at line 16392 of file ExprConstant.cpp.
References clang::C, CheckMemoryLeaks(), EvaluateInteger(), EvaluatePointer(), clang::APValue::getInt(), clang::Type::getPointeeType(), getType(), HandleLValueArrayAdjustment(), and handleLValueToRValueConversion().
EvaluateForOverflow()
void Expr::EvaluateForOverflow (const ASTContext & Ctx) const
Definition at line 15597 of file ExprConstant.cpp.
References EvaluateAsRValue(), and FastEvaluateAsRValue().
EvaluateKnownConstInt()
APSInt Expr::EvaluateKnownConstInt (const ASTContext & Ctx, SmallVectorImpl< PartialDiagnosticAt > * Diag = nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
This must be called on an expression that constant folds to an integer.
Definition at line 15558 of file ExprConstant.cpp.
References Diag(), and EvaluateAsRValue().
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnOpenMPCriticalDirective(), CheckICE(), clang::Sema::DiagnoseAssignmentEnum(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), EvaluateSwitch(), FindCaseStatementsForValue(), clang::FieldDecl::getBitWidthValue(), clang::IfStmt::getNondiscardedCase(), isNullPointerConstant(), IsStandardConversion(), clang::ento::ExprEngine::processSwitch(), shouldAddCase(), templateArgumentExpressionsEqual(), and clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr().
EvaluateKnownConstIntCheckOverflow()
APSInt Expr::EvaluateKnownConstIntCheckOverflow (const ASTContext & Ctx, SmallVectorImpl< PartialDiagnosticAt > * Diag = nullptr) const
Definition at line 15577 of file ExprConstant.cpp.
References Diag(), and EvaluateAsRValue().
Referenced by clang::Sema::VerifyIntegerConstantExpression().
EvaluateWithSubstitution()
bool Expr::EvaluateWithSubstitution (APValue & Value, ASTContext & Ctx, const FunctionDecl * Callee, ArrayRef< const Expr * > Args, const Expr * This = nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
Returns true if the expression could be folded to a constant.
Definition at line 16181 of file ExprConstant.cpp.
References Evaluate(), EvaluateCallArg(), EvaluateObjectArgument(), clang::ASTContext::getPrintingPolicy(), and clang::Expr::EvalStatus::HasSideEffects.
findBoundMemberType()
QualType Expr::findBoundMemberType (const Expr * expr) static
Given an expression of bound-member type, find the type of the member.
Returns null if this is an overloaded bound member expression.
Definition at line 3028 of file Expr.cpp.
References clang::Type::castAs(), clang::ast_matchers::expr, and clang::ast_matchers::type.
Referenced by clang::CallExpr::getCallReturnType().
getAsBuiltinConstantDeclRef()
const ValueDecl * Expr::getAsBuiltinConstantDeclRef (const ASTContext & Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
Note that this may return a non-static member function or field in C++ if this expression is a member pointer constant.
Definition at line 290 of file Expr.cpp.
References EvaluateAsConstantExpr(), and clang::Expr::EvalResult::Val.
Referenced by SemaBuiltinFunctionStart().
getBestDynamicClassType()
const CXXRecordDecl * Expr::getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
If this expression is a cast, this method looks through it to find the most derived decl that can be inferred from the expression. This is valid because derived-to-base conversions have undefined behavior if the object isn't dynamically of the derived type.
Definition at line 68 of file Expr.cpp.
References clang::cast(), clang::Type::castAs(), clang::Type::getAs(), getBestDynamicClassTypeExpr(), clang::Type::getPointeeType(), getType(), and clang::Type::isDependentType().
getBestDynamicClassTypeExpr()
const Expr * Expr::getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
If this is a prvalue, we guarantee that it is of the most-derived type for the object itself.
Definition at line 43 of file Expr.cpp.
References IgnoreParenBaseCasts().
Referenced by getBestDynamicClassType().
getDependence()
ExprDependence clang::Expr::getDependence () const inline
Definition at line 156 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), containsErrors(), containsUnexpandedParameterPack(), clang::MemberExpr::Create(), isInstantiationDependent(), isTypeDependent(), isValueDependent(), clang::CallExpr::markDependentForPostponedNameLookup(), clang::InitListExpr::markError(), and clang::InitListExpr::setInit().
getExprLoc()
SourceLocation Expr::getExprLoc () const
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
Definition at line 330 of file Expr.cpp.
References clang::Stmt::getStmtClass(), and clang::Stmt::NoStmtClass.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCallExpr(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnDoStmt(), clang::Sema::ActOnExprStmt(), clang::Sema::ActOnFinishFullExpr(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPIteratorExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAllocatorClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDeclareVariantDirective(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDispatchDirective(), clang::Sema::ActOnOpenMPHasDeviceAddrClause(), clang::Sema::ActOnOpenMPInitClause(), clang::Sema::ActOnOpenMPIsDevicePtrClause(), clang::Sema::ActOnOpenMPMapClause(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnSEHExceptBlock(), clang::Sema::ActOnStartLinkageSpecification(), clang::Sema::AddConversionCandidate(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddOverloadedCallCandidates(), clang::interp::AddSubMulHelper(), AnalyzeBitFieldAssignment(), AnalyzeImplicitConversions(), applyCocoaAPICheck(), clang::CodeGen::ApplyDebugLocation::ApplyDebugLocation(), clang::Sema::BuildAtomicExpr(), buildCapture(), buildCapture(), buildCaptureDecl(), BuildConvertedConstantExpression(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDecltypeType(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildOverloadedCallExpr(), buildPostUpdate(), BuildRecoveryCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::BuildTypeofExprType(), clang::Sema::BuildVectorLiteral(), clang::interp::State::CCEDiag(), clang::Sema::CheckAddressOfOperand(), CheckAlignOfExpr(), checkAllocateClauses(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::Sema::CheckAssignmentConstraints(), checkBlockType(), checkCastFunctionType(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::checkDeclIsAllowedInOpenMPTarget(), CheckedIntArithmetic(), checkEnumTypesInSwitchStmt(), CheckFoldOperand(), clang::Sema::CheckForConstantInitializer(), CheckForReference(), CheckIdentityFieldAssignment(), CheckIfAnyEnclosingLambdasMustCaptureAnyPotentialCaptures(), CheckImplicitConversion(), checkIndirectCopyRestoreSource(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), clang::Sema::CheckLValueToRValueConversionOperand(), checkMapClauseExpressionBase(), checkMapConflicts(), checkMappableExpressionList(), CheckMemaccessSize(), clang::Sema::CheckMemberPointerConversion(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPIterationSpace(), checkOpenMPLoop(), clang::Sema::CheckPointerConversion(), checkPositiveIntArgument(), checkPreviousOMPAllocateAttribute(), clang::Sema::CheckPtrComparisonWithNullChar(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSubscriptingKind(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTypenameType(), checkUInt32Argument(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::completeExprArrayBound(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAssignmentEnum(), DiagnoseBadFunctionCast(), DiagnoseCastOfObjCSEL(), clang::Sema::DiagnoseConditionalForNull(), DiagnoseCStringFormatDirectiveInCFAPI(), DiagnoseCStringFormatDirectiveInObjCAPI(), DiagnoseDirectIsaAccess(), DiagnoseFloatingImpCast(), DiagnoseForRangeVariableCopies(), DiagnoseImpCast(), DiagnoseIntInBoolContext(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), diagnoseNoViableConversion(), DiagnoseNullConversion(), diagnoseRetainCycle(), diagnoseUnknownAnyExpr(), clang::Sema::DiagnoseUnusedExprResult(), diagnoseXorMisusedAsPow(), DiagRecursiveConstraintEval(), diagReturnOnAllocFailure(), clang::CodeGen::ConstantEmitter::emitAbstract(), EmitAsmStores(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), EmitDoacrossOrdered(), EmitGlobalVarDeclLValue(), EmitNontemporalLoad(), EmitObjectDelete(), emitPointerArithmetic(), emitRestoreIP(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), EmitTypeidFromVTable(), EvaluateAsRValue(), EvaluateCPlusPlus11IntegralConstantExpr(), clang::interp::State::FFDiag(), findSubobject(), clang::ArraySubscriptExpr::getExprLoc(), clang::CXXMemberCallExpr::getExprLoc(), clang::MatrixSubscriptExpr::getExprLoc(), clang::MSPropertySubscriptExpr::getExprLoc(), clang::ObjCIndirectCopyRestoreExpr::getExprLoc(), clang::OMPArraySectionExpr::getExprLoc(), clang::OpaqueValueExpr::getExprLoc(), clang::PseudoObjectExpr::getExprLoc(), clang::CXXRewrittenBinaryOperator::getOperatorLoc(), getPrivateItem(), GetTypeOfFunction(), handleCleanupAttr(), HandleConstructorCall(), handleHLSLNumThreadsAttr(), HandleLValueArrayAdjustment(), HandleLValueComplexElement(), HandleOperatorDeleteCall(), HandleOperatorNewCall(), HasSideEffects(), clang::Sema::IgnoredValueConversions(), clang::Sema::ImpCastExprToType(), clang::interp::IncDecHelper(), isFlexibleArrayMemberLike(), isIdenticalStmt(), isNonNegativeIntegerValue(), isNullPointerValueTemplateArgument(), isUnusedResultAWarning(), IsUserDefinedConversion(), clang::Sema::MakeFullDiscardedValueExpr(), clang::Sema::MakeFullExpr(), makeLaunchBoundsArgExpr(), clang::Sema::MaybeBindToTemporary(), clang::Sema::MaybeConvertParenListExprToParenExpr(), clang::interp::Neg(), NoteLValueLocation(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PrepareScalarCast(), processImplicitMapsWithDefaultMappers(), clang::Sema::ProduceCallSignatureHelp(), clang::Sema::RebuildExprInCurrentInstantiation(), recordConversion(), reportOriginalDsa(), clang::Sema::RequireCompleteExprType(), clang::Sema::ResolveAddressOfOverloadedFunction(), clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), clang::Sema::ResolveSingleFunctionTemplateSpecialization(), rewriteToNumericBoxedExpression(), SemaBuiltinAlignment(), SemaBuiltinSEHScopeCheck(), clang::Sema::TemporaryMaterializationConversion(), tryEvaluateBuiltinObjectSize(), TryOrBuildParenListInitialization(), clang::Sema::tryToRecoverWithCall(), TryUserDefinedConversion(), clang::Sema::VerifyPositiveIntegerConstantInClause(), clang::ASTNodeImporter::VisitSubstNonTypeTemplateParmExpr(), warnInvalidLock(), and clang::Sema::WarnOnPendingNoDerefs().
getFPFeaturesInEffect()
FPOptions Expr::getFPFeaturesInEffect (const LangOptions & LO) const
Returns the set of floating point options that apply to this expression.
Only meaningful for operations on floating point values.
Definition at line 3832 of file Expr.cpp.
References clang::FPOptions::defaultWithoutTrailingStorage().
Referenced by clang::CodeGen::CodeGenFunction::CGFPOptionsRAII::CGFPOptionsRAII(), checkFloatingPointResult(), clang::interp::CheckFloatResult(), and getActiveRoundingMode().
getIntegerConstantExpr()
std::optional< llvm::APSInt > Expr::getIntegerConstantExpr (const ASTContext & Ctx, SourceLocation * Loc = nullptr, bool isEvaluated = true) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
If not a valid i-c-e, return std::nullopt and fill in Loc (if specified) with the location of the invalid expression.
Note: This does not perform the implicit conversions required by C++11 [expr.const]p5.
Definition at line 16108 of file ExprConstant.cpp.
References EvaluateAsInt(), EvaluateCPlusPlus11IntegralConstantExpr(), and clang::ASTContext::getLangOpts().
Referenced by clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnPragmaPack(), clang::Sema::AddAssumeAlignedAttr(), AnalyzeComparison(), BuildAddressSpaceIndex(), clang::Sema::BuildExtVectorType(), clang::Sema::BuildMatrixType(), clang::Sema::BuildVectorType(), checkFunctionOrMethodParameterIndex(), CheckImplicitConversion(), checkUInt32Argument(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), DeduceTemplateArgumentsByTypeMatch(), EmitAArch64TblBuiltinExpr(), clang::Sema::FinalizeDeclaration(), fitsInto(), fixUPCAddressofArraySubscriptWithSpan(), getAlignmentAndOffsetFromBinAddOrSub(), getAndVerifyMatrixDimension(), GetIntegerConstantValue(), clang::CodeGen::CGOpenMPRuntime::getNumTeamsExprForTargetDirective(), handleM68kInterruptAttr(), handleMSP430InterruptAttr(), handleOpenCLUnrollHint(), handleSentinelAttr(), isNonNegativeIntegerValue(), makeLaunchBoundsArgExpr(), clang::ASTContext::mergeTypes(), and clang::Sema::SemaBuiltinShuffleVector().
getObjCProperty()
const ObjCPropertyRefExpr * Expr::getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
Definition at line 4028 of file Expr.cpp.
References clang::cast(), getObjectKind(), IgnoreParenCasts(), isLValue(), and clang::OK_ObjCProperty.
getObjectKind()
ExprObjectKind clang::Expr::getObjectKind () const inline
getObjectKind - The object kind that this expression produces.
Object kinds are meaningful only for expressions that yield an l-value or x-value.
Definition at line 438 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnConditionalOp(), buildCapture(), buildCaptureDecl(), buildCoawaitCalls(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::CheckAddressOfOperand(), CheckAlignOfExpr(), CheckIncrementDecrementOperand(), ClassifyBinaryOp(), clang::PseudoObjectExpr::Create(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CXXCheckConditionalOperands(), getObjCProperty(), isOrdinaryOrBitFieldObject(), isValidBPFPreserveFieldInfoArg(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr(), refersToBitField(), refersToMatrixElement(), clang::Sema::stripARCUnbridgedCast(), TryReinterpretCast(), clang::ConversionFixItGenerator::tryToFixConversion(), clang::ASTNodeImporter::VisitArraySubscriptExpr(), clang::ASTNodeImporter::VisitBinaryConditionalOperator(), clang::ASTNodeImporter::VisitBinaryOperator(), clang::ASTNodeImporter::VisitChooseExpr(), clang::ASTNodeImporter::VisitCompoundAssignOperator(), clang::ASTNodeImporter::VisitConditionalOperator(), clang::ASTNodeImporter::VisitMemberExpr(), clang::ASTNodeImporter::VisitOpaqueValueExpr(), and clang::ASTNodeImporter::VisitUnaryOperator().
getReferencedDeclOfCallee() [1/2]
Decl * Expr::getReferencedDeclOfCallee ()
Definition at line 1560 of file Expr.cpp.
References IgnoreParenImpCasts().
Referenced by CheckSimplerImplicitMovesMSVCWorkaround(), clang::CallExpr::getCalleeDecl(), clang::CallExpr::getCalleeDecl(), and getReferencedDeclOfCallee().
getReferencedDeclOfCallee() [2/2]
const Decl * clang::Expr::getReferencedDeclOfCallee () const inline
Definition at line 479 of file Expr.h.
References getReferencedDeclOfCallee().
getSourceBitField() [1/2]
FieldDecl * Expr::getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
Note that this returns a non-null pointer in subtly different places than refersToBitField returns true. In particular, this can return a non-null pointer even for r-values loaded from bit-fields, but it will return null for a conditional bit-field.
Definition at line 4065 of file Expr.cpp.
References getSourceBitField(), IgnoreParens(), and clang::FieldDecl::isBitField().
Referenced by clang::Sema::ActOnMSAsmStmt(), AnalyzeAssignment(), GetExprRange(), getSourceBitField(), getSourceBitField(), clang::Sema::IsIntegralPromotion(), isKnownToHaveBooleanValue(), and clang::ASTContext::isPromotableBitField().
getSourceBitField() [2/2]
const FieldDecl * clang::Expr::getSourceBitField () const inline
Definition at line 474 of file Expr.h.
References getSourceBitField().
getType()
QualType clang::Expr::getType () const inline
Definition at line 142 of file Expr.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXNamedCast(), clang::Sema::ActOnDecltypeExpression(), clang::Sema::ActOnFinishFullExpr(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnInstanceMessage(), clang::Sema::ActOnMSAsmStmt(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPIteratorExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPMapClause(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnParenExpr(), clang::Sema::ActOnSEHExceptBlock(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnStmtExprResult(), clang::Sema::AddConversionCandidate(), clang::Sema::AddFunctionCandidates(), clang::interp::AddSubMulHelper(), AdjustAddressSpaceForBuiltinOperandType(), adjustBlockReturnsToEnum(), clang::interp::ByteCodeExprGen< Emitter >::allocateLocal(), AnalyzeAssignment(), AnalyzeBitFieldAssignment(), AnalyzeComparison(), AnalyzeCompoundAssignment(), AnalyzeImplicitConversions(), clang::ASTContext::AtomicUsesUnsupportedLibcall(), clang::ento::ExprEngine::bindReturnValue(), clang::tooling::buildAccess(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildArrayType(), clang::Sema::BuildAsTypeExpr(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBinOp(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), buildCapture(), buildCoawaitCalls(), clang::Sema::BuildCompoundLiteralExpr(), BuildConvertedConstantExpression(), clang::Sema::BuildCoreturnStmt(), buildCounterInit(), buildCounterUpdate(), clang::Sema::BuildCoyieldExpr(), BuildCXXCastArgument(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildCXXUuidof(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildFieldReferenceExpr(), buildGlobalBlock(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildIvarRefExpr(), clang::Sema::BuildMemberReferenceExpr(), buildMemcpyForAssignmentOp(), BuildNonArrayForRange(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::BuildTypeofExprType(), clang::Sema::BuildUnaryOp(), clang::Sema::BuildVAArgExpr(), calculateConstraintSatisfaction(), clang::Sema::CallExprUnaryConversions(), clang::Sema::canCalleeThrow(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), CanThrow(), clang::canTypeidThrow(), castArgToParamTypeIfNeeded(), clang::interp::CastFloatingIntegral(), CastForMoving(), castForMoving(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAddressOfOperand(), CheckAggExprForMemSetUse(), checkArithmeticBinOpPointerOperands(), checkArithmeticNull(), checkArithmeticOnObjCPointer(), checkArithmeticOrEnumeralThreeWayCompare(), checkArraySize(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckAssignmentOperands(), checkAttrArgsAreCapabilityObjs(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckBooleanCondition(), CheckBoolLikeConversion(), clang::Sema::CheckCaseExpression(), clang::Sema::CheckCastAlign(), checkCastFunctionType(), CheckCommaOperands(), clang::Sema::CheckCompareOperands(), checkCondition(), checkConditionalBlockPointerCompatibility(), checkConditionalObjectPointersCompatibility(), CheckConditionalOperand(), clang::Sema::CheckConditionalOperands(), CheckConditionalOperator(), checkConditionalPointerCompatibility(), clang::Sema::CheckConstraintExpression(), CheckCXX98CompatAccessibleCopy(), checkDeducedTemplateArguments(), clang::interp::CheckDivRem(), CheckedIntArithmetic(), checkElementNonNil(), checkEnumArithmeticConversions(), clang::Sema::CheckEnumConstant(), checkEnumTypesInSwitchStmt(), clang::Sema::CheckExceptionSpecCompatibility(), clang::Sema::checkExceptionSpecification(), clang::Sema::CheckExtVectorCast(), clang::Sema::CheckFloatComparison(), checkFormatStringExpr(), CheckForModifiableLvalue(), CheckICE(), CheckImplicitArgumentConversions(), CheckImplicitConversion(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), checkIntToPointerCast(), CheckLiteralType(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), clang::Sema::CheckLValueToRValueConversionOperand(), checkMapConflicts(), checkMappableExpressionList(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckMemberPointerConversion(), CheckMoveOnConstruction(), clang::Sema::CheckMultiplyDivideOperands(), CheckNonNullArguments(), CheckNonNullExpr(), CheckObjCCollectionLiteralElement(), clang::Sema::CheckObjCForCollectionOperand(), checkObjCPointerIntrospection(), checkOpenCLBlockArgs(), checkOpenCLConditionVector(), checkOpenCLEnqueueIntType(), checkOpenCLEnqueueVariadicArgs(), checkOpenCLPipeArg(), checkOpenCLPipePacketType(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPLoop(), clang::Sema::CheckPlaceholderExpr(), checkPlaceholderForOverload(), clang::Sema::CheckPointerConversion(), checkPointerIntegerMismatch(), clang::Sema::CheckPointerToMemberOperands(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckRemainderOperands(), clang::interp::CheckShift(), clang::Sema::CheckShiftOperands(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorCompareOperands(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::Sema::CheckStaticArrayArgument(), CheckStringInit(), clang::Sema::CheckSubscriptingKind(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckSwitchCondition(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTransparentUnionArgumentConstraints(), checkTupleLikeDecomposition(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::checkUnknownAnyArg(), clang::Sema::checkUnsafeExprAssigns(), clang::Sema::CheckUnusedVolatileAssignment(), clang::Sema::checkVariadicArgument(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorLogicalOperands(), clang::Sema::CheckVectorOperands(), checkVectorShift(), CheckWasmBuiltinArgIsInteger(), CheckWasmBuiltinArgIsTable(), clang::interp::ByteCodeExprGen< Emitter >::classify(), ClassifyBinaryOp(), ClassifyConditional(), ClassifyExprValueKind(), ClassifyInternal(), ClassifyMemberExpr(), clang::Sema::CodeCompleteObjCInstanceMessage(), CollectVRQualifiers(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), clang::SYCLUniqueStableNameExpr::ComputeName(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::SymbolManager::conjureSymbol(), clang::ento::SValBuilder::conjureSymbolVal(), clang::Sema::ConstantFoldAttrArgs(), clang::Sema::ConvertArgumentsForCall(), convertHalfVecBinOp(), convertPointersToCompositeType(), convertVector(), CopyObject(), clang::CXXBindTemporaryExpr::Create(), createBinOpInfoFromIncDec(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::ConstructionContext::createFromLayers(), CreateFunctionRefExpr(), clang::Sema::CreateGenericSelectionExpr(), clang::interp::Program::createGlobal(), clang::CodeGen::CodeGenModule::createOpenCLIntToSamplerConversion(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::threadSafety::SExprBuilder::createThisPlaceholder(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::deduceClosureReturnType(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), DeduceTemplateArgumentsFromCallArgument(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::DesignatedInitUpdateExpr::DesignatedInitUpdateExpr(), clang::TypeOfExprType::desugar(), clang::InitializationSequence::Diagnose(), diagnoseArithmeticOnTwoFunctionPointers(), diagnoseBadCast(), DiagnoseBadFunctionCast(), DiagnoseBadShiftValues(), DiagnoseBinOpPrecedence(), DiagnoseCallingConvCast(), DiagnoseCastOfObjCSEL(), DiagnoseCastQual(), clang::Sema::DiagnoseConditionalForNull(), diagnoseDistinctPointerComparison(), DiagnoseDivisionSizeofPointerOrArray(), DiagnoseFloatingImpCast(), DiagnoseForRangeReferenceVariableCopies(), diagnoseFunctionPointerToVoidComparison(), DiagnoseImpCast(), DiagnoseIntInBoolContext(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), diagnoseMutableFields(), DiagnoseNullConversion(), diagnosePointerIncompatibility(), DiagnoseRecursiveConstFields(), DiagnoseReinterpretUpDownCast(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseSelfMove(), clang::Sema::DiagnoseStaticAssertDetails(), diagnoseStringPlusChar(), diagnoseStringPlusInt(), diagnoseTautologicalComparison(), clang::Sema::DiagnoseUnusedExprResult(), clang::Sema::diagnoseZeroToNullptrConversion(), doRewriteToUTF8StringBoxedExpressionHelper(), emitAlignedClause(), emitAtomicCmpXchg(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), clang::CodeGen::CGObjCRuntime::EmitAtSynchronizedStmt(), emitBadConversionNotes(), EmitBinaryAtomicPost(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), EmitCommonNeonSISDBuiltinExpr(), EmitCompare(), EmitCXXNewAllocSize(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), emitDispatchForLoopBounds(), emitDistributeParallelForDispatchBounds(), EmitDoacrossOrdered(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), emitFrexpBuiltin(), EmitFunctionDeclLValue(), EmitGlobalVarDeclLValue(), EmitISOVolatileLoad(), EmitISOVolatileStore(), emitLibraryCall(), emitMaybeConstrainedFPToIntRoundBuiltin(), clang::CodeGen::CGCXXABI::EmitMemberPointerConversion(), clang::CodeGen::CGCXXABI::EmitMemberPointerConversion(), EmitNontemporalLoad(), EmitNontemporalStore(), emitOMPAtomicCaptureExpr(), emitOMPAtomicCompareExpr(), emitPointerArithmetic(), EmitPointerWithAlignment(), emitPreCond(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::Sema::EmitRelatedResultTypeNote(), emitRestoreIP(), emitScanBasedDirectiveFinals(), clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), emitTaskPrivateMappingFunction(), EmitTypeidFromVTable(), clang::CodeGen::CGOpenMPRuntime::emitUsesAllocatorsInit(), EmitValToTemp(), emitWritebackArg(), EmitX86BitTestIntrinsic(), EvalAndBitcastToAPInt(), clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), clang::ento::ExprEngine::evalLoad(), Evaluate(), EvaluateArray(), EvaluateArrayNewConstructExpr(), EvaluateArrayNewInitList(), EvaluateAsFixedPoint(), EvaluateAsInt(), EvaluateAsRValue(), EvaluateAtomic(), EvaluateBuiltinClassifyType(), EvaluateBuiltinConstantP(), EvaluateBuiltinStrLen(), EvaluateCallArg(), EvaluateCharRangeAsString(), EvaluateComparisonBinaryOperator(), EvaluateComplex(), EvaluateCPlusPlus11IntegralConstantExpr(), EvaluateFixedPoint(), EvaluateFixedPointOrInteger(), EvaluateFloat(), clang::SourceLocExpr::EvaluateInContext(), EvaluateInPlace(), EvaluateIntegerOrLValue(), EvaluateLValue(), evaluateLValueAsAllocSize(), EvaluateMemberPointer(), EvaluatePointer(), EvaluateRecord(), EvaluateTemporary(), EvaluateVector(), EvaluateVoid(), ExprLooksBoolean(), FastEvaluateAsRValue(), clang::Sema::FillInlineAsmIdentifierInfo(), clang::OverloadExpr::find(), clang::Sema::FindAssociatedClassesAndNamespaces(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), FindConditionalOverload(), findEnumForBlockReturn(), findWeakLValue(), finishContextualImplicitConversion(), clang::Sema::FixOverloadedFunctionReference(), clang::Sema::FormatStringHasSArg(), clang::Sema::GatherArgumentsForCall(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), GetAlignedMapping(), getAlignmentAndOffsetFromBinAddOrSub(), GetAlignOfExpr(), clang::CXXNewExpr::getAllocatedType(), clang::ArrayInitLoopExpr::getArraySize(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), getBestDynamicClassType(), getBuiltinAlignArguments(), clang::ObjCMessageExpr::getCallReturnType(), getCommonTemplateArgument(), clang::Sema::getCompletedType(), clang::ento::SValBuilder::getConjuredHeapSymbolVal(), clang::CodeGen::CodeGenModule::GetConstantArrayFromStringLiteral(), clang::ento::SValBuilder::getConstantVal(), getCXXRecord(), getDependentArraySubscriptType(), clang::CXXDeleteExpr::getDestroyedType(), GetExprRange(), GetExprType(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), clang::VarDecl::getFlexibleArrayInitChars(), clang::BlockExpr::getFunctionType(), clang::dataflow::getImplicitObjectLocation(), clang::LambdaExpr::getLambdaClass(), clang::CodeGen::CGCXXABI::getMemberPointerAdjustment(), clang::CodeGen::CodeGenModule::getMemberPointerConstant(), clang::TemplateArgument::getNonTypeTemplateArgumentType(), clang::ExtVectorElementExpr::getNumElements(), GetNumNonZeroBytesInInit(), clang::ASTContext::getObjCEncodingForBlock(), clang::CXXMemberCallExpr::getObjectType(), getObjectType(), clang::SubstNonTypeTemplateParmExpr::getParameterType(), clang::CodeGen::CGOpenCLRuntime::getPipeElemAlign(), clang::CodeGen::CGOpenCLRuntime::getPipeElemSize(), getPointerAndSize(), getPreferredTypeOfBinaryRHS(), getPresumedAlignmentOfPointer(), GetPrototypeLoc(), clang::ObjCMessageExpr::getReceiverType(), clang::ObjCPropertyRefExpr::getReceiverType(), clang::CXXMemberCallExpr::getRecordDecl(), clang::CodeGen::CodeGenFunction::ConstantEmission::getReferenceLValue(), clang::ASTContext::getReferenceQualifiedType(), clang::dataflow::Environment::getResultObjectLocation(), GetReturnType(), clang::ento::CallEventManager::getSimpleCall(), clang::dataflow::DataflowAnalysisContext::getStableStorageLocation(), clang::dataflow::Environment::getStorageLocationStrict(), clang::CastExpr::getTargetUnionField(), GetTypeBeforeIntegralPromotion(), clang::UnaryExprOrTypeTraitExpr::getTypeOfArgument(), clang::ASTContext::getTypeOfExprType(), clang::AtomicExpr::getValueType(), clang::ento::CompoundLiteralRegion::getValueType(), clang::ento::CXXLifetimeExtendedObjectRegion::getValueType(), clang::ento::CXXTempObjectRegion::getValueType(), clang::ento::ObjCStringRegion::getValueType(), clang::ento::StringRegion::getValueType(), clang::Sema::getVariadicCallType(), HandleBaseToDerivedCast(), HandleDynamicCast(), clang::Sema::HandleExprEvaluationContextForTypeof(), handleIntIntBinOp(), clang::ento::ExprEngine::handleLValueBitCast(), HandleMemberPointerAccess(), HandleOperatorNewCall(), handleTrivialCopy(), handleVectorVectorBinOp(), clang::Sema::hasCStrMethod(), HasEnumType(), clang::VarDecl::hasFlexibleArrayInit(), hasIsEqualMethod(), hasPlaceholderType(), hasPlaceholderType(), HasSideEffects(), IgnoreCommaOperand(), clang::Sema::IgnoredValueConversions(), IgnoreParenNoopCasts(), ignorePointerCastsAndParens(), clang::Sema::ImpCastExprToType(), clang::interp::IncDecHelper(), clang::BadConversionSequence::init(), clang::Sema::InvalidLogicalVectorOperands(), clang::Sema::InvalidOperands(), clang::CXXDynamicCastExpr::isAlwaysNull(), isArithmeticArgumentPromotion(), clang::ObjCSubscriptRefExpr::isArraySubscriptRefExpr(), clang::ExtVectorElementExpr::isArrow(), isBlockPointer(), isCapabilityExpr(), isConstantInitializer(), clang::CFGCXXRecordTypedCall::isCXXRecordTypedCall(), isFlexibleArrayMemberLike(), IsImplicitBoolFloatConversion(), isIntOrBool(), isInvalidICRSource(), isKnownToHaveBooleanValue(), isKnownToHaveUnsignedValue(), IsModifiable(), clang::BinaryOperator::isNullPointerArithmeticExtension(), isNullPointerConstant(), isNullPointerConstantForConversion(), isNullPointerValueTemplateArgument(), clang::CXXTypeidExpr::isPotentiallyEvaluated(), clang::ASTContext::isPromotableBitField(), isReadIfDiscardedInCPlusPlus11(), isReferenceToNonConstCapture(), clang::ASTContext::isSentinelNullExpr(), isShiftOverflow(), isSimpleArrayDecayOperand(), isSimpleZero(), IsStandardConversion(), isStdBasicOstream(), clang::ento::smartptr::isStdSmartPtr(), isStdSmartPtr(), clang::InitListExpr::isStringLiteralInit(), isTemporaryObject(), clang::InitListExpr::isTransparent(), IsTransparentUnionStandardConversion(), isUnusedResultAWarning(), clang::MaterializeTemporaryExpr::isUsableInConstantExpressions(), IsUserDefinedConversion(), isValidBPFPreserveEnumValueArg(), isValidBPFPreserveFieldInfoArg(), isValidBPFPreserveTypeInfoArg(), isValidInteropVariable(), clang::AtomicExpr::isVolatile(), clang::Sema::LookupInlineAsmVarDeclField(), LookupMemberExpr(), LookupMethodInReceiverType(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), clang::ento::SValBuilder::makeBoolVal(), clang::ento::SValBuilder::makeIntVal(), makeTailCallIfSwiftAsync(), maybeAdjustInterfaceForSubscriptingCheck(), clang::Sema::MaybeBindToTemporary(), maybeDiagnoseAssignmentToFunction(), clang::Sema::maybeExtendBlockObject(), MaybeHandleUnionActiveMemberChange(), maybeTailCall(), needsConversionOfHalfVec(), clang::interp::Neg(), clang::Sema::NoteAllOverloadCandidates(), ObjCEnumerationCollection(), objectifyExpr(), OpenCLArithmeticConversions(), OpenCLCheckVectorConditional(), clang::ento::ConditionBRVisitor::patternMatch(), peelOffPointerArithmetic(), clang::InitializationSequence::Perform(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformCopyInitialization(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PerformQualificationConversion(), precomputeExpr(), clang::Sema::PrepareCastToObjCObjectPointer(), clang::Sema::PrepareScalarCast(), clang::Sema::prepareVectorSplat(), print_elem(), printIndicesOfElementsToConstructJson(), printPendingInitLoopJson(), clang::ento::ConditionBRVisitor::printValue(), processArgument(), processImplicitMapsWithDefaultMappers(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), clang::ento::ExprEngine::processSwitch(), clang::ento::ExprEngine::ProcessTemporaryDtor(), clang::Sema::ProduceCallSignatureHelp(), pushTemporaryCleanup(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr(), clang::TreeTransform< Derived >::RebuildObjCIsaExpr(), clang::TreeTransform< Derived >::RebuildObjCIvarRefExpr(), clang::TreeTransform< Derived >::RebuildObjCMessageExpr(), clang::TreeTransform< Derived >::RebuildObjCPropertyRefExpr(), rebuildPotentialResultsAsNonOdrUsed(), clang::Sema::recreateSyntacticForm(), clang::Sema::RefersToMemberWithReducedAlignment(), clang::dataflow::refreshStructValue(), clang::interp::InterpState::reportOverflow(), clang::Sema::ResolveAddressOfOverloadedFunction(), clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), clang::InitializationSequence::RewrapReferenceInitList(), rewriteBuiltinFunctionDecl(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), SemaBuiltinAlignment(), SemaBuiltinAnnotation(), SemaBuiltinCallWithStaticChain(), SemaBuiltinDumpStruct(), SemaBuiltinLaunder(), SemaBuiltinOverflow(), SemaBuiltinPreserveAI(), SemaBuiltinRWPipe(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::SemaConvertVectorExpr(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinNDRangeAndBlock(), clang::DeclRefExpr::setDecl(), clang::BadConversionSequence::setFromExpr(), clang::MemberExpr::setMemberDecl(), setObjCGCLValueClass(), clang::dataflow::Environment::setStorageLocationStrict(), shouldAddReversedEqEq(), shouldEmitSeparateBlockRetain(), shouldExtendReceiverForInnerPointerMessage(), ShouldTryAgainWithRedefinitionType(), skipRValueSubobjectAdjustments(), clang::Sema::stripARCUnbridgedCast(), clang::Sema::TemporaryMaterializationConversion(), throwEscapes(), clang::threadSafety::SExprBuilder::translateAttrExpr(), TryAddressSpaceCast(), TryClassUnification(), TryConstCast(), TryContextuallyConvertToBool(), tryDiagnoseOverloadedCast(), tryEmitARCCopyWeakInit(), tryEmitARCRetainLoadOfScalar(), clang::CodeGen::ConstantEmitter::tryEmitConstantExpr(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), tryEmitSpecializedAllocInit(), clang::Sema::tryExprAsCall(), tryExtractInitializerFromList(), TryImplicitConversion(), TryListConversion(), TryListInitialization(), TryLValueToRValueCast(), TryReferenceListInitialization(), TryReinterpretCast(), TryStaticCast(), TryStaticMemberPointerUpcast(), TryStaticReferenceDowncast(), tryToConvertMemberExprToDeclRefExpr(), TryUserDefinedConversion(), clang::Sema::UsualArithmeticConversions(), clang::Sema::UsualUnaryConversions(), clang::Sema::VerifyIntegerConstantExpression(), clang::ASTNodeImporter::VisitAddrLabelExpr(), clang::interp::ByteCodeExprGen< Emitter >::visitArrayInitializer(), clang::ASTNodeImporter::VisitArrayInitIndexExpr(), clang::ASTNodeImporter::VisitArrayInitLoopExpr(), clang::ASTNodeImporter::VisitArraySubscriptExpr(), clang::ento::ExprEngine::VisitArraySubscriptExpr(), clang::ASTNodeImporter::VisitArrayTypeTraitExpr(), clang::ASTNodeImporter::VisitAtomicExpr(), clang::ASTNodeImporter::VisitBinaryConditionalOperator(), clang::ASTNodeImporter::VisitBinaryOperator(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::interp::ByteCodeExprGen< Emitter >::VisitBinaryOperator(), clang::ento::ExprEngine::VisitBlockExpr(), clang::interp::ByteCodeExprGen< Emitter >::visitBool(), clang::ASTNodeImporter::VisitCallExpr(), clang::ento::ExprEngine::VisitCast(), clang::interp::ByteCodeExprGen< Emitter >::VisitCastExpr(), clang::ASTNodeImporter::VisitCharacterLiteral(), clang::ASTNodeImporter::VisitChooseExpr(), clang::ASTNodeImporter::VisitCompoundAssignOperator(), clang::interp::ByteCodeExprGen< Emitter >::VisitCompoundAssignOperator(), clang::ASTNodeImporter::VisitCompoundLiteralExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCompoundLiteralExpr(), clang::ASTNodeImporter::VisitConditionalOperator(), clang::JSONNodeDumper::VisitConstantExpr(), clang::ASTNodeImporter::VisitCXXBoolLiteralExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCXXDefaultInitExpr(), clang::ASTNodeImporter::VisitCXXDeleteExpr(), clang::ASTNodeImporter::VisitCXXDependentScopeMemberExpr(), clang::ASTNodeImporter::VisitCXXFoldExpr(), clang::ASTNodeImporter::VisitCXXInheritedCtorInitExpr(), clang::ASTNodeImporter::VisitCXXMemberCallExpr(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeImporter::VisitCXXNamedCastExpr(), clang::ASTNodeImporter::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ASTNodeImporter::VisitCXXNoexceptExpr(), clang::ASTNodeImporter::VisitCXXNullPtrLiteralExpr(), clang::ASTNodeImporter::VisitCXXScalarValueInitExpr(), clang::ASTNodeImporter::VisitCXXStdInitializerListExpr(), clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr(), clang::ASTNodeImporter::VisitCXXThisExpr(), clang::ento::ExprEngine::VisitCXXThisExpr(), clang::ASTNodeImporter::VisitCXXThrowExpr(), clang::ASTNodeImporter::VisitCXXTypeidExpr(), clang::ASTNodeImporter::VisitCXXUnresolvedConstructExpr(), clang::JSONNodeDumper::VisitCXXUnresolvedConstructExpr(), clang::ASTNodeImporter::VisitDeclRefExpr(), clang::ASTNodeImporter::VisitExplicitCastExpr(), clang::ASTNodeImporter::VisitExpressionTraitExpr(), clang::ASTNodeImporter::VisitFixedPointLiteral(), clang::interp::ByteCodeExprGen< Emitter >::VisitFloatCompoundAssignOperator(), clang::ASTNodeImporter::VisitFloatingLiteral(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGenericSelectionExpr(), clang::ASTNodeImporter::VisitGNUNullExpr(), clang::ASTNodeImporter::VisitImaginaryLiteral(), clang::ASTNodeImporter::VisitImplicitCastExpr(), clang::ASTNodeImporter::VisitImplicitValueInitExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitImplicitValueInitExpr(), clang::ASTNodeImporter::VisitInitListExpr(), clang::ento::ExprEngine::VisitInitListExpr(), clang::ASTNodeImporter::VisitIntegerLiteral(), clang::JSONNodeDumper::VisitIntegerLiteral(), visitLocalsRetainedByInitializer(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ASTNodeImporter::VisitMaterializeTemporaryExpr(), clang::ASTNodeImporter::VisitMemberExpr(), clang::ento::ExprEngine::VisitMemberExpr(), clang::JSONNodeDumper::VisitObjCMessageExpr(), clang::ASTNodeImporter::VisitOffsetOfExpr(), clang::ento::ExprEngine::VisitOffsetOfExpr(), clang::ASTNodeImporter::VisitOpaqueValueExpr(), clang::ASTNodeImporter::VisitPackExpansionExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitPointerArithBinOp(), clang::interp::ByteCodeExprGen< Emitter >::VisitPointerCompoundAssignOperator(), clang::ASTNodeImporter::VisitPredefinedExpr(), clang::ASTNodeImporter::VisitShuffleVectorExpr(), clang::ASTNodeImporter::VisitSourceLocExpr(), clang::ASTNodeImporter::VisitStmtExpr(), clang::ASTNodeImporter::VisitStringLiteral(), clang::ASTNodeImporter::VisitSubstNonTypeTemplateParmExpr(), clang::ASTNodeImporter::VisitTypeTraitExpr(), clang::ASTNodeImporter::VisitUnaryExprOrTypeTraitExpr(), clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryExprOrTypeTraitExpr(), clang::ASTNodeImporter::VisitUnaryOperator(), clang::ento::ExprEngine::VisitUnaryOperator(), clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryOperator(), clang::ASTNodeImporter::VisitUnresolvedMemberExpr(), clang::ASTNodeImporter::VisitVAArgExpr(), clang::TextNodeDumper::VisitVarDecl(), warnOnSizeofOnArrayDecay(), and widenIterationCount().
getValueKind()
ExprValueKind clang::Expr::getValueKind () const inline
getValueKind - The value kind that this expression produces.
Definition at line 431 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnConditionalOp(), actOnOMPReductionKindClause(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::CheckPointerToMemberOperands(), CheckTemplateArgumentPointerToMember(), clang::Sema::checkUnknownAnyCast(), ClassifyInternal(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::FixOverloadedFunctionReference(), clang::ASTContext::getReferenceQualifiedType(), clang::InitializationSequence::InitializeFrom(), isGLValue(), isLValue(), isPRValue(), isXValue(), LookupMemberExpr(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), removeLValueToRValueCast(), clang::Sema::stripARCUnbridgedCast(), tryToConvertMemberExprToDeclRefExpr(), clang::ASTNodeImporter::VisitArraySubscriptExpr(), clang::ASTNodeImporter::VisitBinaryConditionalOperator(), clang::ASTNodeImporter::VisitBinaryOperator(), clang::ASTNodeImporter::VisitCallExpr(), clang::ASTNodeImporter::VisitChooseExpr(), clang::ASTNodeImporter::VisitCompoundAssignOperator(), clang::ASTNodeImporter::VisitCompoundLiteralExpr(), clang::ASTNodeImporter::VisitConditionalOperator(), clang::ASTNodeImporter::VisitCXXMemberCallExpr(), clang::ASTNodeImporter::VisitCXXNamedCastExpr(), clang::ASTNodeImporter::VisitDeclRefExpr(), clang::ASTNodeImporter::VisitExplicitCastExpr(), clang::ASTNodeImporter::VisitImplicitCastExpr(), clang::ASTNodeImporter::VisitMemberExpr(), clang::ASTNodeImporter::VisitOpaqueValueExpr(), clang::ASTNodeImporter::VisitSubstNonTypeTemplateParmExpr(), and clang::ASTNodeImporter::VisitUnaryOperator().
getValueKindForType()
static ExprValueKind clang::Expr::getValueKindForType (QualType T) inline static
getValueKindForType - Given a formal return or parameter type, give its value kind.
Definition at line 421 of file Expr.h.
References clang::Type::getAs(), clang::VK_LValue, clang::VK_PRValue, and clang::VK_XValue.
Referenced by clang::Sema::AddConversionCandidate(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), fixOverloadedReinterpretCastExpr(), clang::ASTContext::getInjectedTemplateArg(), and clang::TreeTransform< Derived >::RebuildShuffleVectorExpr().
hasAnyTypeDependentArguments()
bool Expr::hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs) static
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
Definition at line 3292 of file Expr.cpp.
References isTypeDependent().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), and clang::InitializationSequence::InitializeFrom().
hasNonTrivialCall()
bool Expr::hasNonTrivialCall (const ASTContext & Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
Definition at line 3892 of file Expr.cpp.
Referenced by isTrivial().
hasPlaceholderType() [1/2]
bool clang::Expr::hasPlaceholderType () const inline
Returns whether this expression has a placeholder type.
Definition at line 503 of file Expr.h.
References getType(), and clang::Type::isPlaceholderType().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCoawaitExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::BuildArrayType(), clang::Sema::BuildCoreturnStmt(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDecltypeType(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildTypeofExprType(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAssignmentOperands(), CheckForModifiableLvalue(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CheckPointerToMemberOperands(), ClassifyBinaryOp(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::diagnoseARCUnbridgedCast(), clang::Sema::IgnoredValueConversions(), clang::MatrixSubscriptExpr::isIncomplete(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::recreateSyntacticForm(), clang::Sema::stripARCUnbridgedCast(), and clang::TreeTransform< Derived >::TransformExprRequirement().
hasPlaceholderType() [2/2]
bool clang::Expr::hasPlaceholderType (BuiltinType::Kind K) const inline
Returns whether this expression has a specific placeholder type.
Definition at line 508 of file Expr.h.
References getType(), and clang::BuiltinType::isPlaceholderTypeKind().
HasSideEffects()
bool Expr::HasSideEffects (const ASTContext & Ctx, bool IncludePossibleEffects = true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
Example is a function call, volatile variable read, or throwing an exception. If IncludePossibleEffects is false, this call treats certain expressions with potential side effects (such as function call-like expressions, instantiation-dependent expressions, or invocations from a macro) as not having side effects.
Definition at line 3545 of file Expr.cpp.
References clang::cast(), clang::Stmt::children(), clang::CastExpr::getCastKind(), clang::CXXConstructExpr::getConstructor(), getExprLoc(), clang::FieldDecl::getInClassInitializer(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), getType(), clang::ExplicitCastExpr::getTypeAsWritten(), clang::Decl::hasAttr(), HasSideEffects(), clang::Type::isReferenceType(), clang::FunctionDecl::isTrivial(), clang::QualType::isVolatileQualified(), clang::Stmt::NoStmtClass, clang::PseudoObjectExpr::semantics_begin(), and clang::PseudoObjectExpr::semantics_end().
Referenced by clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDecltypeType(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CreateGenericSelectionExpr(), HasSideEffects(), clang::arcmt::trans::hasSideEffects(), isIdenticalStmt(), isSimpleZero(), and isTrivial().
IgnoreCasts() [1/2]
const Expr * clang::Expr::IgnoreCasts () const inline
Definition at line 852 of file Expr.h.
References IgnoreCasts().
IgnoreCasts() [2/2]
Expr * Expr::IgnoreCasts ()
Skip past any casts which might surround this expression until reaching a fixed point.
Skips:
CastExpr
FullExpr
MaterializeTemporaryExpr
SubstNonTypeTemplateParmExpr
Definition at line 3056 of file Expr.cpp.
References clang::IgnoreCastsSingleStep(), and clang::IgnoreExprNodes().
Referenced by getBlockExpr(), IgnoreCasts(), and isConfigurationValue().
IgnoreConversionOperatorSingleStep() [1/2]
const Expr * clang::Expr::IgnoreConversionOperatorSingleStep () const inline
Definition at line 914 of file Expr.h.
References IgnoreConversionOperatorSingleStep().
IgnoreConversionOperatorSingleStep() [2/2]
Expr * Expr::IgnoreConversionOperatorSingleStep ()
Skip conversion operators.
If this Expr is a call to a conversion operator, return the argument.
Definition at line 3081 of file Expr.cpp.
Referenced by IgnoreConversionOperatorSingleStep(), and IsArithmeticBinaryExpr().
IgnoreImpCasts() [1/2]
const Expr * clang::Expr::IgnoreImpCasts () const inline
Definition at line 841 of file Expr.h.
References IgnoreImpCasts().
IgnoreImpCasts() [2/2]
Expr * Expr::IgnoreImpCasts ()
Skip past any implicit casts which might surround this expression until reaching a fixed point.
Skips:
ImplicitCastExpr
FullExpr
Definition at line 3052 of file Expr.cpp.
References clang::IgnoreExprNodes(), and clang::IgnoreImplicitCastsSingleStep().
Referenced by addFixitForObjCARCConversion(), buildCaptureDecl(), clang::Sema::BuildMemberReferenceExpr(), castOperatorNeedsParens(), CheckFoldOperand(), CheckIdentityFieldAssignment(), CheckMoveOnConstruction(), checkOpenMPLoop(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentPointerToMember(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseForRangeReferenceVariableCopies(), diagnoseLogicalNotOnLHSofCheck(), diagnoseStringPlusChar(), diagnoseStringPlusInt(), clang::Sema::DiagnoseUnusedExprResult(), doRewriteToUTF8StringBoxedExpressionHelper(), emitOMPAtomicCaptureExpr(), emitOMPAtomicUpdateExpr(), getAllocatorKind(), getSValForVar(), IgnoreImpCasts(), clang::Sema::InvalidLogicalVectorOperands(), IsArithmeticBinaryExpr(), IsPreserveAIArrayBase(), clang::ASTContext::isSameDefaultTemplateArgument(), lookThroughImplicitCasts(), requiresParensToAddCast(), rewriteToNumericBoxedExpression(), SemaBuiltinCallWithStaticChain(), subscriptOperatorNeedsParens(), clang::ConversionFixItGenerator::tryToFixConversion(), and ValidDuplicateEnum().
IgnoreImplicit() [1/2]
const Expr * clang::Expr::IgnoreImplicit () const inline
Definition at line 862 of file Expr.h.
References IgnoreImplicit().
IgnoreImplicit() [2/2]
Expr * Expr::IgnoreImplicit ()
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
Skips:
What IgnoreImpCasts() skips
MaterializeTemporaryExpr
CXXBindTemporaryExpr
Definition at line 3060 of file Expr.cpp.
References clang::IgnoreExprNodes(), and clang::IgnoreImplicitSingleStep().
Referenced by clang::Sema::ActOnOpenMPCanonicalLoop(), clang::Sema::ActOnOpenMPDispatchDirective(), adornObjCBoolConversionDiagWithTernaryFixit(), clang::Sema::CheckForImmediateInvocation(), CheckMoveOnConstruction(), CheckNonNullExpr(), clang::Sema::checkOpenMPDeclareVariantFunction(), DiagnoseConstAssignment(), clang::Sema::DiagnoseImmediateEscalatingReason(), EvaluateAndDiagnoseImmediateInvocation(), clang::CXXRewrittenBinaryOperator::getDecomposedForm(), getDirectCallExpr(), clang::BindingDecl::getHoldingVar(), clang::CXXConstructorDecl::getTargetConstructor(), IgnoreImplicit(), IsCallableWithAppend(), clang::InitListExpr::isIdiomaticZeroInitializer(), IsReadonlyMessage(), clang::Sema::MarkExpressionAsImmediateEscalating(), needsConversionOfHalfVec(), precomputeExpr(), clang::ento::ExprEngine::ProcessInitializer(), ProcessOpenMPDoacrossClauseCommon(), clang::tooling::reallyIgnoreImplicit(), rebuildPotentialResultsAsNonOdrUsed(), RemoveNestedImmediateInvocation(), and clang::consumed::ConsumedStmtVisitor::VisitVarDecl().
IgnoreImplicitAsWritten() [1/2]
const Expr * clang::Expr::IgnoreImplicitAsWritten () const inline
Definition at line 872 of file Expr.h.
References IgnoreImplicitAsWritten().
IgnoreImplicitAsWritten() [2/2]
Expr * Expr::IgnoreImplicitAsWritten ()
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
Same as IgnoreImplicit, except that it also skips over implicit calls to constructors and conversion functions.
FIXME: Should IgnoreImplicit do this?
Definition at line 3064 of file Expr.cpp.
References clang::IgnoreExprNodes(), and clang::IgnoreImplicitAsWrittenSingleStep().
Referenced by clang::tooling::buildAccess(), emitOMPAtomicCompareExpr(), clang::CXXRewrittenBinaryOperator::getDecomposedForm(), and IgnoreImplicitAsWritten().
IgnoreParenBaseCasts() [1/2]
const Expr * clang::Expr::IgnoreParenBaseCasts () const inline
Definition at line 948 of file Expr.h.
References IgnoreParenBaseCasts().
IgnoreParenBaseCasts() [2/2]
Expr * Expr::IgnoreParenBaseCasts ()
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
Skips:
What IgnoreParens() skips
CastExpr which represent a derived-to-base cast (CK_DerivedToBase, CK_UncheckedDerivedToBase and CK_NoOp)
Definition at line 3094 of file Expr.cpp.
References clang::IgnoreBaseCastsSingleStep(), clang::IgnoreExprNodes(), and clang::IgnoreParensSingleStep().
Referenced by getBestDynamicClassTypeExpr(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), and IgnoreParenBaseCasts().
IgnoreParenCasts() [1/2]
const Expr * clang::Expr::IgnoreParenCasts () const inline
Definition at line 907 of file Expr.h.
References IgnoreParenCasts().
IgnoreParenCasts() [2/2]
Expr * Expr::IgnoreParenCasts ()
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
Skips:
What IgnoreParens() skips
What IgnoreCasts() skips
Definition at line 3077 of file Expr.cpp.
References clang::IgnoreCastsSingleStep(), clang::IgnoreExprNodes(), and clang::IgnoreParensSingleStep().
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDispatchDirective(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAssignmentOperands(), checkFormatStringExpr(), CheckForModifiableLvalue(), CheckForNullPointerDereference(), CheckForNullPointerDereference(), CheckICE(), CheckIndirectionOperand(), checkMappableExpressionList(), checkObjCPointerIntrospection(), clang::Sema::CheckStaticArrayArgument(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::CheckSubtractionOperands(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::Sema::CodeCompleteCase(), clang::analyze_os_log::computeOSLogBufferLayout(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DiagnoseAssignmentAsCondition(), diagnoseTautologicalComparison(), EmitSpecialRegisterBuiltin(), findCapturingExpr(), FindTypeTagExpr(), getDeclFromThisExpr(), getDirectCallExpr(), getIncrementedVar(), getNSArrayObjects(), getObjCProperty(), handleTargetClonesAttr(), clang::arcmt::trans::hasSideEffects(), ignoreLiteralAdditions(), IgnoreParenCasts(), isCalleeArrow(), isCapturedBy(), isEnableIf(), clang::arcmt::trans::isGlobalVar(), clang::BinaryOperator::isNullPointerArithmeticExtension(), clang::arcmt::trans::isPlusOne(), clang::ASTContext::isSentinelNullExpr(), IsStandardConversion(), isTrivialDoWhile(), isTrivialExpression(), LookThroughTransitiveAssignmentsAndCommaOperators(), LookupMemberExpr(), clang::sema::FunctionScopeInfo::markSafeWeakUse(), maybeAdjustInterfaceForSubscriptingCheck(), clang::ento::ConditionBRVisitor::patternMatch(), peelOffOuterExpr(), ProcessOpenMPDoacrossClauseCommon(), clang::Sema::ProduceCallSignatureHelp(), REGISTER_MAP_WITH_PROGRAMSTATE(), RemoveSelectorFromWarningCache(), SemaBuiltinAnnotation(), SemaBuiltinSEHScopeCheck(), tryEmitSpecializedAllocInit(), TryEvaluateBuiltinNaN(), clang::ConversionFixItGenerator::tryToFixConversion(), UseNSOptionsMacro(), clang::ento::ConditionBRVisitor::VisitTrueTest(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
IgnoreParenImpCasts() [1/2]
const Expr * clang::Expr::IgnoreParenImpCasts () const inline
Definition at line 898 of file Expr.h.
References IgnoreParenImpCasts().
IgnoreParenImpCasts() [2/2]
Expr * Expr::IgnoreParenImpCasts ()
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
FIXME: IgnoreParenImpCasts really ought to be equivalent to IgnoreParens() + IgnoreImpCasts() until reaching a fixed point. However this is currently not the case. Instead IgnoreParenImpCasts() skips:
What IgnoreParens() skips
What IgnoreImpCasts() skips
MaterializeTemporaryExpr
SubstNonTypeTemplateParmExpr
Definition at line 3072 of file Expr.cpp.
References clang::IgnoreExprNodes(), clang::IgnoreImplicitCastsExtraSingleStep(), and clang::IgnoreParensSingleStep().
Referenced by clang::Sema::ActOnOpenMPAffinityClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDeclareVariantDirective(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), AnalyzeAssignment(), AnalyzeComparison(), AnalyzeImplicitConversions(), clang::ast_matchers::AST_MATCHER_P(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), buildAccessForPointer(), buildAccessForValue(), calculateConstraintSatisfaction(), clang::Sema::canCalleeThrow(), checkArithmeticNull(), checkArithmeticOrEnumeralThreeWayCompare(), CheckBoolLikeConversion(), CheckConditionalOperand(), CheckConditionalOperator(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckConversionToObjCLiteral(), clang::Sema::CheckFloatComparison(), checkForLiteralCreation(), CheckForReference(), CheckICE(), CheckImplicitArgumentConversions(), CheckImplicitConversion(), clang::Sema::CheckLiteralKind(), checkMapConflicts(), CheckMoveOnConstruction(), CheckObjCDictionaryLiteralDuplicateKeys(), checkOMPArraySectionConstantForReduction(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CheckPlaceholderExpr(), checkPreviousOMPAllocateAttribute(), clang::Sema::CheckShadowingDeclModification(), clang::Sema::CheckSubscriptingKind(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), checkUnsafeAssignLiteral(), clang::Sema::CheckUnusedVolatileAssignment(), ClassifyConditional(), ClassifyMemberExpr(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseCallingConvCast(), clang::Sema::DiagnoseConditionalForNull(), DiagnoseConstAssignment(), DiagnoseCStringFormatDirectiveInCFAPI(), DiagnoseCStringFormatDirectiveInObjCAPI(), DiagnoseFloatingImpCast(), DiagnoseIntInBoolContext(), DiagnoseNullConversion(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseSelfMove(), diagnoseTautologicalComparison(), diagnoseUnknownAnyExpr(), clang::Sema::DiagnoseUnusedExprResult(), diagnoseWellFormedUnsatisfiedConstraintExpr(), clang::Sema::diagnoseZeroToNullptrConversion(), doesExprLikelyComputeSize(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), emitInitWithReductionInitializer(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::Sema::EmitRelatedResultTypeNote(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::Sema::EndOpenMPDSABlock(), ExprLooksBoolean(), clang::Sema::findFailedBooleanCondition(), FindTypeTagExpr(), getBaseDecl(), clang::Sema::getMessageSendResultType(), getPointerAndSize(), getPrivateItem(), getReferencedDeclOfCallee(), getSizeOfExprArg(), hasRecursiveCallInPath(), IgnoreParenImpCasts(), IgnoreUnlessSpelledInSource(), isEnumConstant(), IsEnumConstOrFromMacro(), IsImplicitBoolFloatConversion(), isKnownToHaveUnsignedValue(), isObjCObjectLiteral(), isObjCSelfExpr(), IsReadonlyMessage(), isSameComparisonOperand(), isSameWidthConstantConversion(), isSubstitutedTemplateArgument(), lookThroughRangesV3Condition(), LookupMemberExpr(), maybeDiagnoseAssignmentToFunction(), processImplicitMapsWithDefaultMappers(), ProcessOpenMPDoacrossClauseCommon(), clang::ento::ExprEngine::processSwitch(), refersToGlobalRegisterVar(), clang::Sema::RefersToMemberWithReducedAlignment(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToNumberLiteral(), SemaBuiltinCpuIs(), SemaBuiltinCpuSupports(), ShouldDiagnoseSwitchCaseNotInEnum(), stripCastsAndSugar(), tryTransformToIntOrEnumConstant(), and UsefulToPrintExpr().
IgnoreParenLValueCasts() [1/2]
const Expr * clang::Expr::IgnoreParenLValueCasts () const inline
Definition at line 927 of file Expr.h.
References IgnoreParenLValueCasts().
IgnoreParenLValueCasts() [2/2]
Expr * Expr::IgnoreParenLValueCasts ()
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
Skips:
What IgnoreParens() skips
What IgnoreCasts() skips, except that only lvalue-to-rvalue casts are skipped FIXME: This is intended purely as a temporary workaround for code that hasn't yet been rewritten to do the right thing about those casts, and may disappear along with the last internal use.
Definition at line 3089 of file Expr.cpp.
References clang::IgnoreExprNodes(), clang::IgnoreLValueCastsSingleStep(), and clang::IgnoreParensSingleStep().
Referenced by checkMappableExpressionList(), getDereferenceExpr(), IgnoreParenLValueCasts(), and clang::Sema::isSelfExpr().
IgnoreParenNoopCasts() [1/2]
const Expr * clang::Expr::IgnoreParenNoopCasts (const ASTContext & Ctx) const inline
Definition at line 938 of file Expr.h.
References IgnoreParenNoopCasts().
IgnoreParenNoopCasts() [2/2]
Expr * Expr::IgnoreParenNoopCasts (const ASTContext & Ctx)
Skip past any parentheses and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
Skips:
What IgnoreParens() skips
CastExpr which do not change the value
SubstNonTypeTemplateParmExpr
Definition at line 3099 of file Expr.cpp.
References getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::hasSameUnqualifiedType(), clang::IgnoreExprNodes(), clang::IgnoreParensSingleStep(), and clang::Type::isIntegralType().
Referenced by clang::Sema::ActOnGCCAsmStmt(), CheckAsmLValue(), clang::Sema::CheckMessageArgumentTypes(), findPeephole(), clang::Sema::GatherArgumentsForCall(), GetNumNonZeroBytesInInit(), IgnoreParenNoopCasts(), clang::CXXTypeidExpr::isMostDerived(), and stripCasts().
IgnoreParens() [1/2]
const Expr * clang::Expr::IgnoreParens () const inline
Definition at line 884 of file Expr.h.
References IgnoreParens().
IgnoreParens() [2/2]
Expr * Expr::IgnoreParens ()
Skip past any parentheses which might surround this expression until reaching a fixed point.
Skips:
ParenExpr
UnaryOperator if UO_Extension
GenericSelectionExpr if !isResultDependent()
ChooseExpr if !isConditionDependent()
ConstantExpr
Definition at line 3068 of file Expr.cpp.
References clang::IgnoreExprNodes(), and clang::IgnoreParensSingleStep().
Referenced by clang::Sema::ActOnCXXThrow(), actOnOMPReductionKindClause(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::canThrow(), clang::Sema::CheckAddressOfOperand(), CheckAlignOfExpr(), clang::Sema::CheckFloatComparison(), checkMapClauseExpressionBase(), checkMappableExpressionList(), CheckMoveOnConstruction(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::checkPseudoObjectIncDec(), clang::Sema::checkPseudoObjectRValue(), CheckStringInit(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::checkUnsafeExprAssigns(), clang::Sema::CheckVecStepExpr(), ClassifyMemberExpr(), clang::Sema::completeExprArrayBound(), clang::computeDependence(), clang::Sema::CreateBuiltinBinOp(), clang::ento::ExprEngine::CreateCXXTemporaryObject(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::diagnoseARCUnbridgedCast(), DiagnoseBadConversion(), DiagnoseDivisionSizeofPointerOrArray(), clang::Sema::DiagnoseEqualityWithExtraParens(), clang::Sema::DiscardMisalignedMemberAddress(), DoMarkPotentialCapture(), doRewriteToUTF8StringBoxedExpressionHelper(), EmitPointerWithAlignment(), EvaluateLValue(), clang::OverloadExpr::find(), findEnumForBlockReturn(), findRetainCycleOwner(), findWeakLValue(), GetAlignOfExpr(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), clang::ento::SValBuilder::getConstantVal(), clang::Sema::getDecltypeForExpr(), getExprAsWritten(), GetExprRange(), clang::CXXMemberCallExpr::getImplicitObjectArgument(), clang::CXXMemberCallExpr::getMethodDecl(), clang::Sema::getNamedReturnInfo(), getPrivateItem(), getSourceBitField(), getSyntacticFromForPseudoObjectExpr(), clang::CFGBlock::getTerminatorCondition(), IgnoreCommaOperand(), IgnoreParens(), ignorePointerCastsAndParens(), ignoreTransparentExprs(), isBlockVarRef(), isCheapEnoughToEvaluateUnconditionally(), isFlexibleArrayMemberLike(), isGLValueFromPointerDeref(), IsIntegerLiteralConstantExpr(), isInvalidICRSource(), isKnownToHaveBooleanValue(), IsModifiable(), isOBJCGCCandidate(), isParenthesizedADLCallee(), isReadIfDiscardedInCPlusPlus11(), isReferenceToNonConstCapture(), isSameComparisonOperand(), isSimpleZero(), IsStandardConversion(), clang::Sema::IsStringLiteralToNonConstPointerConversion(), isUnusedResultAWarning(), isValidBPFPreserveEnumValueArg(), isValidBPFPreserveFieldInfoArg(), isValidBPFPreserveTypeInfoArg(), LookThroughExpr(), maybeGetUnaryAddrOfOperand(), clang::InitializationSequence::Perform(), refersToVectorElement(), shouldEmitSeparateBlockRetain(), shouldExtendReceiverForInnerPointerMessage(), skipRValueSubobjectAdjustments(), skipTemporaryBindingsNoOpCastsAndParens(), tryEmitARCCopyWeakInit(), tryEmitARCRetainLoadOfScalar(), clang::Sema::tryExprAsCall(), tryTransformToIntOrEnumConstant(), UnpackConstruction(), clang::ento::ExprEngine::VisitArraySubscriptExpr(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitGuardedExpr(), clang::ento::ConditionBRVisitor::VisitTerminator(), and clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryExprOrTypeTraitExpr().
IgnoreUnlessSpelledInSource() [1/2]
Expr * Expr::IgnoreUnlessSpelledInSource ()
Skip past any invisible AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
Definition at line 3125 of file Expr.cpp.
References clang::C, clang::cast(), clang::Stmt::getSourceRange(), clang::IgnoreExprNodes(), clang::IgnoreImplicitCastsExtraSingleStep(), IgnoreImplicitConstructorSingleStep(), clang::IgnoreImplicitSingleStep(), IgnoreParenImpCasts(), and clang::IgnoreParensOnlySingleStep().
Referenced by IgnoreUnlessSpelledInSource(), and clang::ParentMapContext::traverseIgnored().
IgnoreUnlessSpelledInSource() [2/2]
const Expr * clang::Expr::IgnoreUnlessSpelledInSource () const inline
Definition at line 832 of file Expr.h.
References IgnoreUnlessSpelledInSource().
isBoundMemberFunction()
bool Expr::isBoundMemberFunction (ASTContext & Ctx) const
Returns true if this expression is a bound member function.
Definition at line 3022 of file Expr.cpp.
References ClassifyLValue(), isTypeDependent(), and LV_MemberFunction.
isConstantInitializer()
bool Expr::isConstantInitializer (ASTContext & Ctx, bool ForRef, const Expr ** Culprit = nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
If this expression is not constant and Culprit is non-null, it is used to store the address of first non constant expr.
Definition at line 3300 of file Expr.cpp.
References clang::cast(), clang::Type::castAs(), EvaluateAsInt(), EvaluateAsLValue(), clang::RecordDecl::fields(), clang::CXXConstructExpr::getArg(), clang::DesignatedInitUpdateExpr::getBase(), clang::CastExpr::getCastKind(), clang::CXXConstructExpr::getConstructor(), clang::InitListExpr::getInit(), clang::InitListExpr::getInitializedFieldInUnion(), clang::CXXConstructExpr::getNumArgs(), clang::InitListExpr::getNumInits(), clang::UnaryOperator::getOpcode(), clang::CXXMethodDecl::getParent(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), clang::UnaryOperator::getSubExpr(), getType(), clang::DesignatedInitUpdateExpr::getUpdater(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::Type::isArrayType(), isConstantInitializer(), isEvaluatable(), clang::Type::isRecordType(), clang::InitListExpr::isSemanticForm(), clang::FunctionDecl::isTrivial(), clang::TagDecl::isUnion(), isValueDependent(), clang::Result, and SE_AllowUndefinedBehavior.
Referenced by clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::InstantiateVariableInitializer(), and isConstantInitializer().
isCXX11ConstantExpr()
bool Expr::isCXX11ConstantExpr (const ASTContext & Ctx, APValue * Result = nullptr, SourceLocation * Loc = nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
Can only be used in C++.
Note: This does not perform the implicit conversions required by C++11 [expr.const]p5.
Definition at line 16148 of file ExprConstant.cpp.
References EvaluateAsRValue(), and clang::ASTContext::getLangOpts().
Referenced by EvaluateCPlusPlus11IntegralConstantExpr().
isCXX98IntegralConstantExpr()
bool Expr::isCXX98IntegralConstantExpr (const ASTContext & Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
Can only be used in C++.
Definition at line 16141 of file ExprConstant.cpp.
References CheckICE().
Referenced by isNullPointerConstant().
isDefaultArgument()
bool Expr::isDefaultArgument () const
Determine whether this expression is a default function argument.
Default arguments are implicitly generated in the abstract syntax tree by semantic analysis for function calls, object constructions, etc. in C++. Default arguments are represented by CXXDefaultArgExpr nodes; this routine also looks through any implicit casts to determine whether the expression is a default argument.
Definition at line 3167 of file Expr.cpp.
References clang::isa().
Referenced by clang::TreeTransform< Derived >::DropCallArgument(), and clang::CXXConstructExpr::getEndLoc().
isEvaluatable()
bool Expr::isEvaluatable (const ASTContext & Ctx, SideEffectsKind AllowSideEffects = SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded, but discard the result.
Definition at line 15549 of file ExprConstant.cpp.
References EvaluateAsRValue(), and hasUnacceptableSideEffect().
Referenced by clang::Sema::ActOnGCCAsmStmt(), isCheapEnoughToEvaluateUnconditionally(), isConstantInitializer(), and isTrivial().
isFlexibleArrayMemberLike()
bool Expr::isFlexibleArrayMemberLike (ASTContext & Context, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution = false) const
Check whether this array fits the idiom of a flexible array member, depending on the value of -fstrict-flex-array.
When IgnoreTemplateOrMacroSubstitution is set, it doesn't consider sizes resulting from the substitution of a macro or a template as special sizes.
Definition at line 207 of file Expr.cpp.
References clang::TypeLoc::getAs(), clang::TypeLoc::getAsAdjusted(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getAsIncompleteArrayType(), getExprLoc(), getType(), clang::TypeSourceInfo::getTypeLoc(), clang::TypedefNameDecl::getTypeSourceInfo(), IgnoreParens(), and clang::SourceLocation::isMacroID().
isGLValue()
bool clang::Expr::isGLValue () const inline
Definition at line 274 of file Expr.h.
References getValueKind(), and clang::VK_PRValue.
Referenced by clang::Sema::ActOnConditionalOp(), buildCapture(), buildCaptureDecl(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::interp::ByteCodeExprGen< Emitter >::classify(), clang::ento::SValBuilder::conjureSymbolVal(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DiagnoseUnusedExprResult(), Evaluate(), EvaluateAsRValue(), EvaluateLValue(), clang::ento::SValBuilder::getConstantVal(), clang::Sema::getOpenMPCapturedExpr(), clang::dataflow::Environment::getStorageLocationStrict(), HandleDynamicCast(), hasTrivialGetExpr(), clang::CFGCXXRecordTypedCall::isCXXRecordTypedCall(), isGLValueFromPointerDeref(), clang::CXXTypeidExpr::isPotentiallyEvaluated(), isReadIfDiscardedInCPlusPlus11(), IsStandardConversion(), clang::InitListExpr::isTransparent(), clang::Sema::MaybeBindToTemporary(), clang::dataflow::propagateValueOrStorageLocation(), clang::dataflow::Environment::setStorageLocationStrict(), TryClassUnification(), TryContextuallyConvertToBool(), clang::CodeGen::ConstantEmitter::tryEmitConstantExpr(), tryEvaluateBuiltinObjectSize(), TryLValueToRValueCast(), TryReinterpretCast(), clang::ento::ExprEngine::VisitArraySubscriptExpr(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::ExprEngine::VisitCompoundLiteralExpr(), clang::ento::ExprEngine::VisitInitListExpr(), visitLocalsRetainedByInitializer(), and clang::ento::ExprEngine::VisitMemberExpr().
isImplicitCXXThis()
bool Expr::isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
Definition at line 3248 of file Expr.cpp.
References Paren.
Referenced by clang::tooling::buildAccess(), clang::tooling::buildAddressOf(), clang::MemberExpr::isImplicitAccess(), and clang::MSPropertyRefExpr::isImplicitAccess().
isInstantiationDependent()
bool clang::Expr::isInstantiationDependent () const inline
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
a template parameter (even if neither its type nor (constant) value can change due to the template instantiation)
or an error
In the following example, the expression sizeof(sizeof(T() + T())) is instantiation-dependent (since it involves a template parameter T), but is neither type- nor value-dependent, since the type of the inner sizeof is known (std::size_t) and therefore the size of the outer sizeof is known.
template<typename T>
void f(T x, T y) {
  sizeof(sizeof(T() + T());
}
void func(int) {
  func(); // the expression is instantiation-dependent, because it depends
          // on an error.
}
Definition at line 215 of file Expr.h.
References getDependence().
Referenced by clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPInitClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPScheduleClause(), applyOMPAllocateAttribute(), clang::Sema::BuildBitIntType(), clang::Sema::BuildDecltypeType(), clang::Sema::BuildExprRequirement(), clang::Sema::BuildNestedRequirement(), clang::Sema::checkAndRewriteMustTailAttr(), CheckIfAnyEnclosingLambdasMustCaptureAnyPotentialCaptures(), checkMappableExpressionList(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkSimdlenSafelenSpecified(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::Sema::CorrectDelayedTyposInExpr(), clang::ASTContext::getConstantArrayType(), clang::ASTContext::getDecltypeType(), clang::ASTContext::getDependentAddressSpaceType(), clang::ASTContext::getDependentBitIntType(), isNonNegativeIntegerValue(), clang::concepts::NestedRequirement::NestedRequirement(), and clang::Sema::VerifyPositiveIntegerConstantInClause().
isIntegerConstantExpr()
bool Expr::isIntegerConstantExpr (const ASTContext & Ctx, SourceLocation * Loc = nullptr) const
Definition at line 16089 of file ExprConstant.cpp.
References CheckICE(), EvaluateCPlusPlus11IntegralConstantExpr(), and clang::ASTContext::getLangOpts().
Referenced by clang::Sema::ActOnOpenMPInitClause(), clang::Sema::AddAssumeAlignedAttr(), clang::Sema::CheckCaseExpression(), checkIntToPointerCast(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPLoop(), clang::Sema::DiagnoseAssignmentEnum(), clang::CodeGen::CGOpenMPRuntime::getNumTeamsExprForTargetDirective(), isNullPointerConstant(), IsStandardConversion(), templateArgumentExpressionsEqual(), and clang::Sema::VerifyIntegerConstantExpression().
isKnownToHaveBooleanValue()
bool Expr::isKnownToHaveBooleanValue (bool Semantic = true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
This happens for _Bool/bool expressions but also int expressions which are produced by things like comparisons in C.
Parameters
Semantic If true, only return true for expressions that are known to be semantically boolean, which might not be true even for expressions that are known to evaluate to 0/1. For instance, reading an unsigned bit-field with width '1' will evaluate to 0/1, but doesn't necessarily semantically correspond to a bool.
Definition at line 137 of file Expr.cpp.
References getSourceBitField(), getType(), IgnoreParens(), clang::Type::isBooleanType(), and clang::Type::isIntegralOrEnumerationType().
Referenced by clang::Sema::ActOnStartOfSwitchStmt(), CheckImplicitConversion(), and diagnoseLogicalNotOnLHSofCheck().
isLValue()
bool clang::Expr::isLValue () const inline
isLValue - True if this expression is an "l-value" according to the rules of the current language.
C and C++ give somewhat different rules for this concept, but in general, the result of an l-value expression identifies a specific object whereas the result of an r-value expression is a value detached from any specific storage.
C++11 divides the concept of "r-value" into pure r-values ("pr-values") and so-called expiring values ("x-values"), which identify specific objects that can be safely cannibalized for their resources.
Definition at line 271 of file Expr.h.
References getValueKind(), and clang::VK_LValue.
Referenced by clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOpenMPAffinityClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnParenExpr(), AdjustFunctionParmAndArgTypesForDeduction(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), CheckAsmLValue(), checkMappableExpressionList(), clang::Sema::CheckSizelessVectorOperands(), checkTupleLikeDecomposition(), clang::Sema::CheckVectorOperands(), ClassifyInternal(), clang::Sema::ConstantFoldAttrArgs(), clang::Sema::DefaultFunctionArrayConversion(), clang::InitializationSequence::Diagnose(), EvaluateExpressionTrait(), getObjCProperty(), clang::MaterializeTemporaryExpr::isBoundToLvalueReference(), IsGlobalLValue(), clang::ento::ExplodedGraph::isInterestingLValueExpr(), isReferenceToNonConstCapture(), clang::InitializationSequence::Perform(), TryConstCast(), tryEmitARCCopyWeakInit(), TryLValueToRValueCast(), TryStaticReferenceDowncast(), and clang::ConversionFixItGenerator::tryToFixConversion().
isModifiableLvalue()
Expr::isModifiableLvalueResult Expr::isModifiableLvalue (ASTContext & Ctx, SourceLocation * Loc = nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Parameters
Loc [in,out] - A source location which may be filled in with the location of the expression making this a non-modifiable lvalue, if specified.
Definition at line 702 of file ExprClassification.cpp.
References clang::Expr::Classification::CL_AddressableVoid, clang::Expr::Classification::CL_ArrayTemporary, clang::Expr::Classification::CL_ClassTemporary, clang::Expr::Classification::CL_DuplicateVectorComponents, clang::Expr::Classification::CL_Function, clang::Expr::Classification::CL_LValue, clang::Expr::Classification::CL_MemberFunction, clang::Expr::Classification::CL_ObjCMessageRValue, clang::Expr::Classification::CL_PRValue, clang::Expr::Classification::CL_SubObjCPropertySetting, clang::Expr::Classification::CL_Void, clang::Expr::Classification::CL_XValue, ClassifyModifiable(), clang::Expr::Classification::CM_ArrayType, clang::Expr::Classification::CM_ConstAddrSpace, clang::Expr::Classification::CM_ConstQualified, clang::Expr::Classification::CM_ConstQualifiedField, clang::Expr::Classification::CM_Function, clang::Expr::Classification::CM_IncompleteType, clang::Expr::Classification::CM_LValueCast, clang::Expr::Classification::CM_Modifiable, clang::Expr::Classification::CM_NoSetterProperty, clang::Expr::Classification::CM_RValue, clang::Expr::Classification::CM_Untested, clang::Expr::Classification::getKind(), clang::Expr::Classification::getModifiable(), MLV_ArrayTemporary, MLV_ArrayType, MLV_ClassTemporary, MLV_ConstAddrSpace, MLV_ConstQualified, MLV_ConstQualifiedField, MLV_DuplicateVectorComponents, MLV_IncompleteType, MLV_IncompleteVoidType, MLV_InvalidExpression, MLV_InvalidMessageExpression, MLV_LValueCast, MLV_MemberFunction, MLV_NoSetterProperty, MLV_NotObjectType, MLV_SubObjCPropertySetting, and MLV_Valid.
Referenced by clang::Sema::ActOnGCCAsmStmt(), and CheckForModifiableLvalue().
isNullPointerConstant()
Expr::NullPointerConstantKind Expr::isNullPointerConstant (ASTContext & Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
isNullPointerConstant - C99 6.3.2.3p3 - Return whether this is a null pointer constant or not, as well as the specific kind of constant detected.
The return value can further distinguish the kind of NULL pointer constant that was detected.
Null pointer constants can be integer constant expressions with the value zero, casts of zero to void*, nullptr (C++0X), or __null (a GNU extension).
Definition at line 3904 of file Expr.cpp.
References containsErrors(), clang::Qualifiers::empty(), EvaluateKnownConstInt(), clang::QualType::getAddressSpace(), clang::Type::getAs(), clang::ASTContext::getDefaultOpenCLPointeeAddrSpace(), clang::ASTContext::getLangOpts(), clang::Type::getPointeeType(), clang::QualType::getQualifiers(), getType(), clang::APIntStorage::getValue(), isCXX98IntegralConstantExpr(), isIntegerConstantExpr(), isNullPointerConstant(), isTypeDependent(), isValueDependent(), clang::Type::isVoidType(), NPC_NeverValueDependent, NPC_ValueDependentIsNotNull, NPC_ValueDependentIsNull, NPCK_CXX11_nullptr, NPCK_GNUNull, NPCK_NotNull, NPCK_ZeroExpression, NPCK_ZeroLiteral, and clang::Qualifiers::removeAddressSpace().
Referenced by clang::Sema::BuildCXXUuidof(), clang::Sema::BuildInstanceMessage(), clang::Sema::CheckAdditionOperands(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), checkConditionalNullPointer(), clang::Sema::CheckConversionToObjCLiteral(), checkFormatStringExpr(), clang::Sema::CheckMemberPointerConversion(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckStaticArrayArgument(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTransparentUnionArgumentConstraints(), clang::Sema::DiagnoseConditionalForNull(), diagnoseTautologicalComparison(), clang::Sema::FindCompositePointerType(), clang::ento::SValBuilder::getConstantVal(), isInvalidICRSource(), clang::Sema::IsMemberPointerConversion(), clang::BinaryOperator::isNullPointerArithmeticExtension(), isNullPointerConstant(), isNullPointerConstantForConversion(), isNullPointerValueTemplateArgument(), clang::ASTContext::isSentinelNullExpr(), clang::Sema::PrepareScalarCast(), and SemaOpenCLBuiltinEnqueueKernel().
isOBJCGCCandidate()
bool Expr::isOBJCGCCandidate (ASTContext & Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
isOBJCGCCandidate - Check if an expression is objc gc'able.
returns true, if it is; false otherwise.
Definition at line 2983 of file Expr.cpp.
References clang::cast(), clang::MemberExpr::getBase(), clang::ASTContext::getObjCGCAttrKind(), clang::Stmt::getStmtClass(), IgnoreParens(), isOBJCGCCandidate(), clang::Type::isPointerType(), and clang::Qualifiers::Weak.
Referenced by isOBJCGCCandidate().
isObjCSelfExpr()
bool Expr::isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
Definition at line 4047 of file Expr.cpp.
References clang::DeclRefExpr::getDecl(), clang::ObjCMethodDecl::getSelfDecl(), and IgnoreParenImpCasts().
Referenced by clang::Sema::BuildInstanceMessage(), and clang::Sema::getMessageSendResultType().
isOrdinaryOrBitFieldObject()
bool clang::Expr::isOrdinaryOrBitFieldObject () const inline
Definition at line 442 of file Expr.h.
References getObjectKind(), clang::OK_BitField, and clang::OK_Ordinary.
Referenced by clang::Sema::ActOnConditionalOp(), and clang::Sema::CXXCheckConditionalOperands().
isPotentialConstantExpr()
bool Expr::isPotentialConstantExpr (const FunctionDecl * FD, SmallVectorImpl< PartialDiagnosticAt > & Diags) static
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
Return false if the function can never produce a constant expression, along with diagnostics describing why not.
Definition at line 16252 of file ExprConstant.cpp.
References clang::Expr::EvalStatus::Diag, clang::Decl::getASTContext(), clang::FunctionDecl::getBody(), clang::CXXRecordDecl::getCanonicalDecl(), clang::ASTContext::getInterpContext(), clang::Decl::getLocation(), clang::FunctionDecl::getNameForDiagnostic(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getPrintingPolicy(), clang::ASTContext::getRecordType(), HandleConstructorCall(), HandleFunctionCall(), clang::ASTContext::IntTy, clang::DeclContext::isDependentContext(), clang::CXXMethodDecl::isInstance(), and clang::interp::Context::isPotentialConstantExpr().
Referenced by CheckConstexprFunctionBody().
isPotentialConstantExprUnevaluated()
bool Expr::isPotentialConstantExprUnevaluated (Expr * E, const FunctionDecl * FD, SmallVectorImpl< PartialDiagnosticAt > & Diags) static
isPotentialConstantExprUnevaluted - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
Return false if the function can never produce a constant expression, along with diagnostics describing why not.
Definition at line 16309 of file ExprConstant.cpp.
References clang::Expr::EvalStatus::Diag, Evaluate(), clang::Decl::getASTContext(), and isValueDependent().
Referenced by checkFunctionConditionAttr(), and instantiateDependentFunctionAttrCondition().
isPRValue()
bool clang::Expr::isPRValue () const inline
Definition at line 272 of file Expr.h.
References getValueKind(), and clang::VK_PRValue.
Referenced by clang::Sema::ActOnConditionalOp(), clang::Sema::BuildArrayType(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildResolvedCoawaitExpr(), calculateConstraintSatisfaction(), CheckICE(), checkIndirectCopyRestoreSource(), CheckLiteralType(), CheckMoveOnConstruction(), clang::Sema::CheckPointerToMemberOperands(), ClassifyInternal(), clang::Sema::CreateBuiltinArraySubscriptExpr(), emitPseudoObjectExpr(), EvaluateArray(), EvaluateArrayNewConstructExpr(), EvaluateArrayNewInitList(), EvaluateAsBooleanCondition(), EvaluateAtomic(), EvaluateBuiltinStrLen(), EvaluateComplex(), EvaluateExpressionTrait(), EvaluateFloat(), EvaluateInPlace(), EvaluateIntegerOrLValue(), EvaluateMemberPointer(), EvaluatePointer(), EvaluateRecord(), EvaluateTemporary(), EvaluateVector(), EvaluateVoid(), clang::Sema::FillInlineAsmIdentifierInfo(), clang::dataflow::Environment::getResultObjectLocation(), clang::dataflow::Environment::getValueStrict(), clang::Sema::IgnoredValueConversions(), ignorePointerCastsAndParens(), clang::Sema::ImpCastExprToType(), clang::InitListExpr::isTransparent(), clang::Sema::maybeExtendBlockObject(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::dataflow::refreshStructValue(), clang::dataflow::Environment::setValueStrict(), clang::Sema::TemporaryMaterializationConversion(), TryConstCast(), and TryListInitialization().
isReadIfDiscardedInCPlusPlus11()
bool Expr::isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
This applies to certain forms of volatile glvalues.
Definition at line 2536 of file Expr.cpp.
References getType(), IgnoreParens(), and isGLValue().
Referenced by clang::Sema::IgnoredValueConversions(), and isUnusedResultAWarning().
isSameComparisonOperand()
bool Expr::isSameComparisonOperand (const Expr * E1, const Expr * E2) static
Checks that the two Expr's will refer to the same value as a comparison operand.
The caller must ensure that the values referenced by the Expr's are not modified between E1 and E2 or the result my be invalid.
Definition at line 4149 of file Expr.cpp.
References clang::cast(), clang::declaresSameEntity(), clang::Stmt::getStmtClass(), IgnoreParenImpCasts(), IgnoreParens(), and isSameComparisonOperand().
Referenced by diagnoseTautologicalComparison(), and isSameComparisonOperand().
isTemporaryObject()
bool Expr::isTemporaryObject (ASTContext & Ctx, const CXXRecordDecl * TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
isTemporaryObject - Determines if this expression produces a temporary of the given class type.
Definition at line 3206 of file Expr.cpp.
References clang::C, Classify(), getType(), clang::Expr::Classification::isPRValue(), and skipTemporaryBindingsNoOpCastsAndParens().
Referenced by clang::Sema::BuildCXXConstructExpr(), and CopyObject().
isTypeDependent()
bool clang::Expr::isTypeDependent () const inline
Determines whether the type of this expression depends on.
a template parameter (C++ [temp.dep.expr], which means that its type could change from one template instantiation to the next)
or an error
For example, the expressions "x" and "x + y" are type-dependent in the following code, but "y" is not type-dependent:
template<typename T>
void add(T x, int y) {
  x + y;
}
Definition at line 186 of file Expr.h.
References getDependence().
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnExplicitBoolSpecifier(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPInitClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnPragmaPack(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnStmtExprResult(), AnalyzeBitFieldAssignment(), AnalyzeImplicitConversions(), applyOMPAllocateAttribute(), clang::Sema::BuildArrayType(), clang::Sema::BuildBinOp(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildExtVectorType(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildMatrixType(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCSubscriptExpression(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildStaticAssertDeclaration(), clang::Sema::BuildTypeofExprType(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorType(), clang::canDynamicCastThrow(), clang::Sema::canThrow(), clang::canTypeidThrow(), clang::Sema::CheckAddressOfOperand(), CheckAlignOfExpr(), CheckAsmLValue(), checkAttrArgsAreCapabilityObjs(), clang::Sema::CheckBooleanCondition(), clang::Sema::CheckCaseExpression(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckConstraintExpression(), clang::Sema::CheckEnumConstant(), clang::Sema::checkExceptionSpecification(), checkFormatStringExpr(), checkFunctionConditionAttr(), checkFunctionOrMethodParameterIndex(), CheckImplicitConversion(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), checkMappableExpressionList(), clang::Sema::CheckObjCForCollectionOperand(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::checkPseudoObjectIncDec(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSwitchCondition(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentPointerToMember(), checkUInt32Argument(), clang::Sema::CheckVecStepExpr(), clang::computeDependence(), clang::Sema::ConstantFoldAttrArgs(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::Sema::CorrectDelayedTyposInExpr(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DiagnoseAssignmentEnum(), clang::Sema::DiagnoseEqualityWithExtraParens(), doRewriteToUTF8StringBoxedExpressionHelper(), clang::Sema::EvaluateStaticAssertMessageAsString(), findTemplateParameterInType(), clang::Sema::getDecltypeForExpr(), getDependentArraySubscriptType(), clang::ASTContext::getDependentSizedArrayType(), getPrivateItem(), clang::ASTContext::getTypeOfExprType(), clang::ArrayTypeTraitExpr::getValue(), handleSentinelAttr(), hasAnyTypeDependentArguments(), instantiateDependentFunctionAttrCondition(), instantiateExplicitSpecifier(), isBoundMemberFunction(), clang::ChooseExpr::isConditionDependent(), isNonNegativeIntegerValue(), isNullPointerConstant(), isNullPointerConstantForConversion(), isNullPointerValueTemplateArgument(), clang::ASTContext::isPromotableBitField(), clang::TypeOfExprType::isSugared(), isUnusedResultAWarning(), ObjCEnumerationCollection(), clang::OverloadExpr::OverloadExpr(), clang::Sema::PerformContextualImplicitConversion(), processImplicitMapsWithDefaultMappers(), clang::Sema::ProduceCallSignatureHelp(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), rewriteToNumericBoxedExpression(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::tryExprAsCall(), clang::Sema::VerifyBitField(), and clang::Sema::VerifyPositiveIntegerConstantInClause().
isUnusedResultAWarning()
bool Expr::isUnusedResultAWarning (const Expr *& WarnE, SourceLocation & Loc, SourceRange & R1, SourceRange & R2, ASTContext & Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
If so, fill in expr, location, and ranges with expr to warn on and source locations/ranges appropriate for a warning.
If so, fill in Loc and Ranges with location to warn on and the source range[s] to report with the warning.
Definition at line 2602 of file Expr.cpp.
References clang::CompoundStmt::body_back(), clang::CompoundStmt::body_empty(), clang::cast(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::CallExpr::getCallee(), clang::CallExpr::getCalleeDecl(), clang::CallExpr::getCallReturnType(), clang::ASTContext::getCanonicalType(), clang::CastExpr::getCastKind(), clang::Stmt::getEndLoc(), getExpr(), getExprLoc(), clang::ASTContext::getLangOpts(), clang::BinaryOperator::getLHS(), clang::CStyleCastExpr::getLParenLoc(), clang::ObjCMessageExpr::getMethodDecl(), clang::ObjCMessageExpr::getMethodFamily(), clang::CallExpr::getNumArgs(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::CXXOperatorCallExpr::getOperator(), clang::BinaryOperator::getOperatorLoc(), clang::CXXOperatorCallExpr::getOperatorLoc(), clang::UnaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::CXXOperatorCallExpr::getSourceRange(), clang::Stmt::getSourceRange(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), clang::UnaryOperator::getSubExpr(), getType(), clang::Type::hasAttr(), clang::CallExpr::hasUnusedResultAttr(), IgnoreParens(), clang::Type::isArrayType(), clang::BinaryOperator::isAssignmentOp(), clang::ObjCMessageExpr::isInstanceMessage(), isReadIfDiscardedInCPlusPlus11(), clang::Type::isReferenceType(), isTypeDependent(), isUnusedResultAWarning(), clang::Type::isVoidType(), clang::CanQual< typename >::isVolatileQualified(), clang::QualType::isVolatileQualified(), Label, clang::OMF_init, and clang::Result.
Referenced by clang::Sema::DiagnoseUnusedExprResult(), and isUnusedResultAWarning().
isValueDependent()
bool clang::Expr::isValueDependent () const inline
Determines whether the value of this expression depends on.
a template parameter (C++ [temp.dep.constexpr])
or an error, whose resolution is unknown
For example, the array bound of "Chars" in the following example is value-dependent.
template<int Size, char (&Chars)[Size]> struct meta_string;
Definition at line 169 of file Expr.h.
References getDependence().
Referenced by clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPInitClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignValueAttr(), clang::Sema::AddAssumeAlignedAttr(), AnalyzeBitFieldAssignment(), AnalyzeComparison(), AnalyzeImplicitConversions(), applyOMPAllocateAttribute(), clang::Sema::BuildAddressSpaceAttr(), BuildAddressSpaceIndex(), clang::Sema::BuildArrayType(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildExtVectorType(), clang::Sema::BuildMatrixType(), clang::Sema::BuildStaticAssertDeclaration(), clang::Sema::BuildVectorType(), checkAMDGPUFlatWorkGroupSizeArguments(), checkAMDGPUWavesPerEUArguments(), clang::Sema::CheckCaseExpression(), clang::Sema::CheckCXXBooleanCondition(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckForImmediateInvocation(), checkFormatStringExpr(), checkFunctionConditionAttr(), CheckICE(), CheckImplicitConversion(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckLoopHintExpr(), checkMappableExpressionList(), CheckNonNullExpr(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentPointerToMember(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::Sema::ConstantFoldAttrArgs(), clang::Sema::CorrectDelayedTyposInExpr(), clang::Sema::DiagnoseAssignmentEnum(), DiagnoseBadDivideOrRemainderValues(), DiagnoseBadShiftValues(), DiagnoseIntInBoolContext(), clang::Sema::DiagnoseSentinelCalls(), diagnoseStringPlusInt(), Evaluate(), EvaluateArray(), EvaluateArrayNewConstructExpr(), EvaluateArrayNewInitList(), EvaluateAsBooleanCondition(), EvaluateAsFixedPoint(), EvaluateAsInt(), EvaluateAsRValue(), EvaluateAsRValue(), EvaluateAtomic(), EvaluateComparisonBinaryOperator(), EvaluateComplex(), EvaluateCond(), EvaluateDependentExpr(), EvaluateFixedPoint(), EvaluateFixedPointOrInteger(), EvaluateFloat(), EvaluateIgnoredValue(), EvaluateInPlace(), EvaluateInteger(), EvaluateIntegerOrLValue(), EvaluateLValue(), EvaluateMemberPointer(), EvaluatePointer(), EvaluateRecord(), clang::Sema::EvaluateStaticAssertMessageAsString(), EvaluateStmt(), EvaluateSwitch(), EvaluateTemporary(), EvaluateVarDecl(), EvaluateVoid(), clang::Sema::FinalizeVarWithDestructor(), clang::ASTContext::getDependentSizedArrayType(), clang::SizeOfPackExpr::getPackLength(), getPrivateItem(), clang::ConceptSpecializationExpr::getSatisfaction(), clang::TypeTraitExpr::getValue(), HandleAddressSpaceTypeAttribute(), instantiateDependentFunctionAttrCondition(), clang::CXXDynamicCastExpr::isAlwaysNull(), clang::CallExpr::isBuiltinAssumeFalse(), clang::ChooseExpr::isConditionDependent(), isConstantInitializer(), isNonNegativeIntegerValue(), isNullPointerConstant(), isNullPointerConstantForConversion(), isNullPointerValueTemplateArgument(), clang::SizeOfPackExpr::isPartiallySubstituted(), isPotentialConstantExprUnevaluated(), clang::ASTContext::isPromotableBitField(), clang::ConceptSpecializationExpr::isSatisfied(), clang::RequiresExpr::isSatisfied(), clang::FieldDecl::isZeroLengthBitField(), makeLaunchBoundsArgExpr(), MustDelayAttributeArguments(), processImplicitMapsWithDefaultMappers(), SemaBuiltinAlignment(), clang::Sema::SemaBuiltinShuffleVector(), clang::RequiresExpr::setSatisfied(), templateArgumentExpressionsEqual(), clang::Sema::tryResolveExplicitSpecifier(), clang::Sema::VerifyBitField(), clang::Sema::VerifyPositiveIntegerConstantInClause(), clang::EvaluatedExprVisitorBase< Ptr, ImplClass >::VisitChooseExpr(), clang::ASTNodeImporter::VisitCXXNoexceptExpr(), clang::JSONNodeDumper::VisitRequiresExpr(), clang::ASTNodeImporter::VisitSizeOfPackExpr(), clang::ASTNodeImporter::VisitTypeTraitExpr(), and clang::TextNodeDumper::VisitVarDecl().
isXValue()
bool clang::Expr::isXValue () const inline
Definition at line 273 of file Expr.h.
References getValueKind(), and clang::VK_XValue.
Referenced by clang::Sema::getNamedReturnInfo(), tryEmitARCCopyWeakInit(), and tryEmitARCRetainLoadOfScalar().
operator=() [1/2]
Expr & clang::Expr::operator= (const Expr &) delete
operator=() [2/2]
Expr & clang::Expr::operator= (Expr &&) delete
refersToBitField()
bool clang::Expr::refersToBitField () const inline
Returns true if this expression is a gl-value that potentially refers to a bit-field.
In C++, whether a gl-value refers to a bitfield is essentially an aspect of the value-kind type system.
Definition at line 463 of file Expr.h.
References getObjectKind(), and clang::OK_BitField.
Referenced by clang::Sema::ActOnMSAsmStmt(), clang::Sema::BuildTypeofExprType(), checkExprMemoryConstraintCompat(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CXXCheckConditionalOperands(), isNonReferenceableGLValue(), and TryConstCast().
refersToGlobalRegisterVar()
bool Expr::refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
Definition at line 4137 of file Expr.cpp.
References IgnoreParenImpCasts(), and clang::SC_Register.
Referenced by checkExprMemoryConstraintCompat().
refersToMatrixElement()
bool clang::Expr::refersToMatrixElement () const inline
Returns whether this expression refers to a matrix element.
Definition at line 494 of file Expr.h.
References getObjectKind(), and clang::OK_MatrixComponent.
Referenced by isNonReferenceableGLValue().
refersToVectorElement()
bool Expr::refersToVectorElement () const
Returns whether this expression refers to a vector element.
Definition at line 4112 of file Expr.cpp.
References IgnoreParens(), and refersToVectorElement().
Referenced by checkExprMemoryConstraintCompat(), clang::Sema::CXXCheckConditionalOperands(), isNonReferenceableGLValue(), and refersToVectorElement().
setDependence()
void clang::Expr::setDependence (ExprDependence Deps) inline protected
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Definition at line 135 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::AddrLabelExpr::AddrLabelExpr(), clang::ArrayInitIndexExpr::ArrayInitIndexExpr(), clang::ArrayInitLoopExpr::ArrayInitLoopExpr(), clang::ArraySubscriptExpr::ArraySubscriptExpr(), clang::ArrayTypeTraitExpr::ArrayTypeTraitExpr(), clang::AsTypeExpr::AsTypeExpr(), clang::AtomicExpr::AtomicExpr(), clang::BinaryConditionalOperator::BinaryConditionalOperator(), clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::BinaryOperator(), clang::BlockExpr::BlockExpr(), clang::CharacterLiteral::CharacterLiteral(), clang::ChooseExpr::ChooseExpr(), clang::CompoundLiteralExpr::CompoundLiteralExpr(), clang::CallExpr::computeDependence(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::ConditionalOperator::ConditionalOperator(), clang::ConvertVectorExpr::ConvertVectorExpr(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::MemberExpr::Create(), clang::CXXBoolLiteralExpr::CXXBoolLiteralExpr(), clang::CXXConstructExpr::CXXConstructExpr(), clang::CXXDeleteExpr::CXXDeleteExpr(), clang::CXXFoldExpr::CXXFoldExpr(), clang::CXXInheritedCtorInitExpr::CXXInheritedCtorInitExpr(), clang::CXXNoexceptExpr::CXXNoexceptExpr(), clang::CXXNullPtrLiteralExpr::CXXNullPtrLiteralExpr(), clang::CXXPseudoDestructorExpr::CXXPseudoDestructorExpr(), clang::CXXRewrittenBinaryOperator::CXXRewrittenBinaryOperator(), clang::CXXScalarValueInitExpr::CXXScalarValueInitExpr(), clang::CXXStdInitializerListExpr::CXXStdInitializerListExpr(), clang::CXXThisExpr::CXXThisExpr(), clang::CXXThrowExpr::CXXThrowExpr(), clang::CXXTypeidExpr::CXXTypeidExpr(), clang::CXXTypeidExpr::CXXTypeidExpr(), clang::CXXUuidofExpr::CXXUuidofExpr(), clang::CXXUuidofExpr::CXXUuidofExpr(), clang::DeclRefExpr::DeclRefExpr(), clang::DependentCoawaitExpr::DependentCoawaitExpr(), clang::DesignatedInitUpdateExpr::DesignatedInitUpdateExpr(), clang::ExplicitCastExpr::ExplicitCastExpr(), clang::ExpressionTraitExpr::ExpressionTraitExpr(), clang::ExtVectorElementExpr::ExtVectorElementExpr(), clang::FixedPointLiteral::FixedPointLiteral(), clang::FullExpr::FullExpr(), clang::GNUNullExpr::GNUNullExpr(), clang::ImaginaryLiteral::ImaginaryLiteral(), clang::ImplicitValueInitExpr::ImplicitValueInitExpr(), clang::InitListExpr::InitListExpr(), clang::IntegerLiteral::IntegerLiteral(), clang::CallExpr::markDependentForPostponedNameLookup(), clang::InitListExpr::markError(), clang::MaterializeTemporaryExpr::MaterializeTemporaryExpr(), clang::MatrixSubscriptExpr::MatrixSubscriptExpr(), clang::MSPropertyRefExpr::MSPropertyRefExpr(), clang::MSPropertySubscriptExpr::MSPropertySubscriptExpr(), clang::NoInitExpr::NoInitExpr(), clang::ObjCAvailabilityCheckExpr::ObjCAvailabilityCheckExpr(), clang::ObjCBoolLiteralExpr::ObjCBoolLiteralExpr(), clang::ObjCBoxedExpr::ObjCBoxedExpr(), clang::ObjCEncodeExpr::ObjCEncodeExpr(), clang::ObjCIndirectCopyRestoreExpr::ObjCIndirectCopyRestoreExpr(), clang::ObjCIsaExpr::ObjCIsaExpr(), clang::ObjCIvarRefExpr::ObjCIvarRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCProtocolExpr::ObjCProtocolExpr(), clang::ObjCSelectorExpr::ObjCSelectorExpr(), clang::ObjCStringLiteral::ObjCStringLiteral(), clang::ObjCSubscriptRefExpr::ObjCSubscriptRefExpr(), clang::OMPArraySectionExpr::OMPArraySectionExpr(), clang::OpaqueValueExpr::OpaqueValueExpr(), clang::OverloadExpr::OverloadExpr(), clang::PackExpansionExpr::PackExpansionExpr(), clang::ParenExpr::ParenExpr(), clang::DeclRefExpr::setDecl(), clang::InitListExpr::setInit(), clang::MemberExpr::setMemberDecl(), clang::ShuffleVectorExpr::ShuffleVectorExpr(), clang::SourceLocExpr::SourceLocExpr(), clang::StmtExpr::StmtExpr(), clang::SubstNonTypeTemplateParmExpr::SubstNonTypeTemplateParmExpr(), clang::SubstNonTypeTemplateParmPackExpr::SubstNonTypeTemplateParmPackExpr(), clang::TypoExpr::TypoExpr(), clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr(), clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr(), clang::UnaryOperator::UnaryOperator(), clang::CXXParenListInitExpr::updateDependence(), and clang::VAArgExpr::VAArgExpr().
setObjectKind()
void clang::Expr::setObjectKind (ExprObjectKind Cat) inline
setObjectKind - Set the object kind produced by this expression.
Definition at line 451 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::Sema::BuildDeclRefExpr(), and SemaBuiltinCallWithStaticChain().
setType()
void clang::Expr::setType (QualType t) inline
Definition at line 143 of file Expr.h.
References clang::QualType::isNull(), and clang::Type::isReferenceType().
Referenced by clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildInitList(), clang::Sema::BuildMemberExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVectorLiteral(), clang::Sema::completeExprArrayBound(), ConstructTransparentUnion(), CreateFunctionRefExpr(), clang::DesignatedInitUpdateExpr::DesignatedInitUpdateExpr(), Expr(), clang::OverloadExpr::OverloadExpr(), clang::InitializationSequence::Perform(), SemaBuiltinAddressof(), SemaBuiltinAlignment(), SemaBuiltinAnnotation(), SemaBuiltinCallWithStaticChain(), SemaBuiltinLaunder(), SemaBuiltinPreserveAI(), clang::DeclRefExpr::setDecl(), clang::MemberExpr::setMemberDecl(), TryListConversion(), updateStringLiteralType(), and clang::ASTNodeImporter::VisitInitListExpr().
setValueKind()
void clang::Expr::setValueKind (ExprValueKind Cat) inline
setValueKind - Set the value kind produced by this expression.
Definition at line 448 of file Expr.h.
References clang::Stmt::ExprBits.
Referenced by clang::Sema::BuildResolvedCallExpr(), clang::InitializationSequence::Perform(), removeLValueToRValueCast(), SemaBuiltinCallWithStaticChain(), updateGNUCompoundLiteralRValue(), and updateStringLiteralType().
skipRValueSubobjectAdjustments() [1/2]
const Expr * clang::Expr::skipRValueSubobjectAdjustments () const inline
Definition at line 990 of file Expr.h.
References skipRValueSubobjectAdjustments().
Referenced by skipRValueSubobjectAdjustments().
skipRValueSubobjectAdjustments() [2/2]
const Expr * Expr::skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > & CommaLHS, SmallVectorImpl< SubobjectAdjustment > & Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
Record the LHSs of comma expressions and adjustments needed along the path.
Definition at line 82 of file Expr.cpp.
References clang::cast(), clang::Type::castAs(), clang::Type::getAs(), getType(), IgnoreParens(), and clang::Type::isRecordType().
Referenced by clang::APValue::LValueBase::getType().
tryEvaluateObjectSize()
bool Expr::tryEvaluateObjectSize (uint64_t & Result, ASTContext & Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
Returns true if all of the above holds and we were able to figure out the size, false otherwise.
Parameters
Type - How to evaluate the size of the Expr, as defined by the "type" parameter of __builtin_object_size
Definition at line 16333 of file ExprConstant.cpp.
References getType(), and tryEvaluateBuiltinObjectSize().
tryEvaluateStrLen()
bool Expr::tryEvaluateStrLen (uint64_t & Result, ASTContext & Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
Returns true if all of the above holds and we were able to figure out the strlen, false otherwise.
Definition at line 16431 of file ExprConstant.cpp.
References EvaluateBuiltinStrLen().
Friends And Related Symbol Documentation
ASTImporter
friend class ASTImporter friend
Definition at line 138 of file Expr.h.
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 139 of file Expr.h.
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp
lib/AST/ExprClassification.cpp
lib/AST/ExprConstant.cpp