clang: clang::ento::TypedValueRegion Class Reference
clang::ento::TypedValueRegion Class Reference abstract
TypedValueRegion - An abstract class representing regions having a typed value.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
virtual QualType getValueType () const =0
QualType getLocationType () const override
QualType getDesugaredValueType (ASTContext &Context) const
Public Member Functions inherited from clang::ento::TypedRegion
QualType getDesugaredLocationType (ASTContext &Context) const
bool isBoundable () const override
Public Member Functions inherited from clang::ento::SubRegion
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
virtual void Profile (llvm::FoldingSetNodeID &ID) const =0
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
virtual void dumpToStream (raw_ostream &os) const
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Protected Member Functions
TypedValueRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::TypedRegion
TypedRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
TypedValueRegion - An abstract class representing regions having a typed value.
Definition at line 530 of file MemRegion.h.
Constructor & Destructor Documentation
TypedValueRegion()
clang::ento::TypedValueRegion::TypedValueRegion (const MemRegion * sReg, Kind k) inline protected
Definition at line 534 of file MemRegion.h.
References classof().
Member Function Documentation
classof()
static bool clang::ento::TypedValueRegion::classof (const MemRegion * R) inline static
Definition at line 555 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
Referenced by TypedValueRegion().
getDesugaredValueType()
QualType clang::ento::TypedValueRegion::getDesugaredValueType (ASTContext & Context) const inline
Definition at line 550 of file MemRegion.h.
References getValueType().
getLocationType()
QualType clang::ento::TypedValueRegion::getLocationType () const inline override virtual
Implements clang::ento::TypedRegion.
Definition at line 541 of file MemRegion.h.
References clang::ento::MemRegion::getContext(), clang::ASTContext::getObjCObjectPointerType(), clang::ASTContext::getPointerType(), and getValueType().
Referenced by dereference().
getValueType()
virtual QualType clang::ento::TypedValueRegion::getValueType () const pure virtual
Implemented in clang::ento::CompoundLiteralRegion, clang::ento::CXXBaseObjectRegion, clang::ento::CXXDerivedObjectRegion, clang::ento::CXXLifetimeExtendedObjectRegion, clang::ento::CXXTempObjectRegion, clang::ento::CXXThisRegion, clang::ento::ElementRegion, clang::ento::FieldRegion, clang::ento::NonParamVarRegion, clang::ento::ObjCIvarRegion, clang::ento::ObjCStringRegion, clang::ento::ParamVarRegion, clang::ento::StringRegion, and clang::ento::VarRegion.
Referenced by getConstructedRegion(), clang::ento::SValBuilder::getDerivedRegionValueSymbolVal(), getDerivedSymbolForBinding(), getDesugaredValueType(), getLocationType(), clang::ento::SValBuilder::getRegionValueSymbolVal(), isValidBaseClass(), clang::ento::LazyCompoundValData::LazyCompoundValData(), clang::ento::SymbolDerived::SymbolDerived(), and clang::ento::SymbolRegionValue::SymbolRegionValue().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp