clang: clang::CodeCompletionTUInfo Class Reference
clang::CodeCompletionTUInfo Class Reference
#include "clang/Sema/CodeCompleteConsumer.h"
Public Member Functions
CodeCompletionTUInfo (std::shared_ptr< GlobalCodeCompletionAllocator > Allocator)
std::shared_ptr< GlobalCodeCompletionAllocator > getAllocatorRef () const
CodeCompletionAllocator & getAllocator () const
StringRef getParentName (const DeclContext *DC)
Detailed Description
Definition at line 653 of file CodeCompleteConsumer.h.
Constructor & Destructor Documentation
CodeCompletionTUInfo()
clang::CodeCompletionTUInfo::CodeCompletionTUInfo (std::shared_ptr< GlobalCodeCompletionAllocator > Allocator) inline explicit
Definition at line 658 of file CodeCompleteConsumer.h.
Member Function Documentation
getAllocator()
CodeCompletionAllocator & clang::CodeCompletionTUInfo::getAllocator () const inline
Definition at line 666 of file CodeCompleteConsumer.h.
Referenced by clang::PrintingCodeCompleteConsumer::getAllocator().
getAllocatorRef()
std::shared_ptr< GlobalCodeCompletionAllocator > clang::CodeCompletionTUInfo::getAllocatorRef () const inline
Definition at line 662 of file CodeCompleteConsumer.h.
getParentName()
StringRef CodeCompletionTUInfo::getParentName (const DeclContext * DC)
Definition at line 373 of file CodeCompleteConsumer.cpp.
References clang::First, clang::NamedDecl::getName(), clang::DeclContext::getParent(), and clang::DeclContext::isFunctionOrMethod().
The documentation for this class was generated from the following files:
include/clang/Sema/CodeCompleteConsumer.h
lib/Sema/CodeCompleteConsumer.cpp