clang: clang::VerifyDiagnosticConsumer::MarkerTracker Class Reference
clang::VerifyDiagnosticConsumer::MarkerTracker Class Reference
Public Member Functions
MarkerTracker (DiagnosticsEngine &Diags)
void addMarker (StringRef MarkerName, SourceLocation Pos)
void addDirective (StringRef MarkerName, const UnattachedDirective &UD)
void finalize ()
Detailed Description
Definition at line 326 of file VerifyDiagnosticConsumer.cpp.
Constructor & Destructor Documentation
MarkerTracker()
clang::VerifyDiagnosticConsumer::MarkerTracker::MarkerTracker (DiagnosticsEngine & Diags) inline
Definition at line 341 of file VerifyDiagnosticConsumer.cpp.
Member Function Documentation
addDirective()
void clang::VerifyDiagnosticConsumer::MarkerTracker::addDirective (StringRef MarkerName, const UnattachedDirective & UD) inline
Definition at line 367 of file VerifyDiagnosticConsumer.cpp.
References clang::SourceLocation::isInvalid().
Referenced by ParseDirective().
addMarker()
void clang::VerifyDiagnosticConsumer::MarkerTracker::addMarker (StringRef MarkerName, SourceLocation Pos) inline
Definition at line 344 of file VerifyDiagnosticConsumer.cpp.
References clang::SourceLocation::isInvalid().
Referenced by ParseDirective().
finalize()
void clang::VerifyDiagnosticConsumer::MarkerTracker::finalize () inline
Definition at line 380 of file VerifyDiagnosticConsumer.cpp.
References clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
The documentation for this class was generated from the following file:
lib/Frontend/VerifyDiagnosticConsumer.cpp