clang: clang::extractapi::FunctionSignature Class Reference
clang::extractapi::FunctionSignature Class Reference
Store function signature information with DeclarationFragments of the return type and parameters.
#include "clang/ExtractAPI/DeclarationFragments.h"
Classes
struct Parameter
Parameter holds the name and DeclarationFragments of a single parameter.
Public Member Functions
FunctionSignature ()=default
const std::vector< Parameter > & getParameters () const
const DeclarationFragments & getReturnType () const
FunctionSignature & addParameter (StringRef Name, DeclarationFragments Fragments)
void setReturnType (DeclarationFragments RT)
bool empty () const
Determine if the FunctionSignature is empty.
Detailed Description
Store function signature information with DeclarationFragments of the return type and parameters.
Definition at line 182 of file DeclarationFragments.h.
Constructor & Destructor Documentation
FunctionSignature()
clang::extractapi::FunctionSignature::FunctionSignature () default
Member Function Documentation
addParameter()
FunctionSignature & clang::extractapi::FunctionSignature::addParameter (StringRef Name, DeclarationFragments Fragments) inline
Definition at line 198 of file DeclarationFragments.h.
Referenced by clang::extractapi::DeclarationFragmentsBuilder::getFunctionSignature().
empty()
bool clang::extractapi::FunctionSignature::empty () const inline
Determine if the FunctionSignature is empty.
Returns
true if the return type DeclarationFragments is empty and there is no parameter, otherwise false.
Definition at line 210 of file DeclarationFragments.h.
References clang::extractapi::DeclarationFragments::getFragments().
getParameters()
const std::vector< Parameter > & clang::extractapi::FunctionSignature::getParameters () const inline
Definition at line 195 of file DeclarationFragments.h.
getReturnType()
const DeclarationFragments & clang::extractapi::FunctionSignature::getReturnType () const inline
Definition at line 196 of file DeclarationFragments.h.
setReturnType()
void clang::extractapi::FunctionSignature::setReturnType (DeclarationFragments RT) inline
Definition at line 204 of file DeclarationFragments.h.
Referenced by clang::extractapi::DeclarationFragmentsBuilder::getFunctionSignature().
The documentation for this class was generated from the following file:
include/clang/ExtractAPI/DeclarationFragments.h