clang: clang::analyze_format_string::OptionalAmount Class Reference
clang::analyze_format_string::OptionalAmount Class Reference
#include "clang/AST/FormatString.h"
Public Types
enum HowSpecified { NotSpecified , Constant , Arg , Invalid }
Public Member Functions
OptionalAmount (HowSpecified howSpecified, unsigned amount, const char *amountStart, unsigned amountLength, bool usesPositionalArg)
OptionalAmount (bool valid=true)
OptionalAmount (unsigned Amount)
bool isInvalid () const
HowSpecified getHowSpecified () const
void setHowSpecified (HowSpecified h)
bool hasDataArgument () const
unsigned getArgIndex () const
unsigned getConstantAmount () const
const char * getStart () const
unsigned getConstantLength () const
ArgType getArgType (ASTContext &Ctx) const
void toString (raw_ostream &os) const
bool usesPositionalArg () const
unsigned getPositionalArgIndex () const
bool usesDotPrefix () const
void setUsesDotPrefix ()
Detailed Description
Definition at line 336 of file FormatString.h.
Member Enumeration Documentation
HowSpecified
enum clang::analyze_format_string::OptionalAmount::HowSpecified
Enumerator
NotSpecified
Constant
Arg
Invalid
Definition at line 338 of file FormatString.h.
Constructor & Destructor Documentation
OptionalAmount() [1/3]
clang::analyze_format_string::OptionalAmount::OptionalAmount (HowSpecified howSpecified, unsigned amount, const char * amountStart, unsigned amountLength, bool usesPositionalArg) inline
Definition at line 340 of file FormatString.h.
OptionalAmount() [2/3]
clang::analyze_format_string::OptionalAmount::OptionalAmount (bool valid = true) inline
Definition at line 348 of file FormatString.h.
OptionalAmount() [3/3]
clang::analyze_format_string::OptionalAmount::OptionalAmount (unsigned Amount) inline explicit
Definition at line 352 of file FormatString.h.
Member Function Documentation
getArgIndex()
unsigned clang::analyze_format_string::OptionalAmount::getArgIndex () const inline
Definition at line 365 of file FormatString.h.
References hasDataArgument().
getArgType()
ArgType analyze_format_string::OptionalAmount::getArgType (ASTContext & Ctx) const
Definition at line 635 of file FormatString.cpp.
References clang::ASTContext::IntTy.
getConstantAmount()
unsigned clang::analyze_format_string::OptionalAmount::getConstantAmount () const inline
Definition at line 370 of file FormatString.h.
References Constant.
Referenced by clang::analyze_printf::PrintfSpecifier::getArgType(), clang::analyze_format_string::ParseArgPosition(), clang::analyze_format_string::ParsePositionAmount(), and clang::analyze_printf::PrintfSpecifier::toString().
getConstantLength()
unsigned clang::analyze_format_string::OptionalAmount::getConstantLength () const inline
Definition at line 380 of file FormatString.h.
References Constant.
getHowSpecified()
HowSpecified clang::analyze_format_string::OptionalAmount::getHowSpecified () const inline
Definition at line 360 of file FormatString.h.
Referenced by clang::analyze_printf::PrintfSpecifier::hasValidFieldWidth(), clang::analyze_printf::PrintfSpecifier::hasValidPrecision(), clang::analyze_format_string::ParseArgPosition(), clang::analyze_format_string::ParsePositionAmount(), ParseScanfSpecifier(), and clang::analyze_format_string::ParseVectorModifier().
getPositionalArgIndex()
unsigned clang::analyze_format_string::OptionalAmount::getPositionalArgIndex () const inline
Definition at line 390 of file FormatString.h.
References hasDataArgument().
Referenced by toString().
getStart()
const char * clang::analyze_format_string::OptionalAmount::getStart () const inline
Definition at line 375 of file FormatString.h.
hasDataArgument()
bool clang::analyze_format_string::OptionalAmount::hasDataArgument () const inline
Definition at line 363 of file FormatString.h.
References Arg.
Referenced by getArgIndex(), and getPositionalArgIndex().
isInvalid()
bool clang::analyze_format_string::OptionalAmount::isInvalid () const inline
Definition at line 356 of file FormatString.h.
References Invalid.
Referenced by clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_printf::PrintfSpecifier::getArgType(), clang::analyze_format_string::FormatSpecifier::hasValidLengthModifier(), clang::analyze_format_string::ParseFieldWidth(), ParsePrecision(), and clang::analyze_printf::PrintfSpecifier::toString().
setHowSpecified()
void clang::analyze_format_string::OptionalAmount::setHowSpecified (HowSpecified h) inline
Definition at line 361 of file FormatString.h.
Referenced by clang::analyze_printf::PrintfSpecifier::fixType().
setUsesDotPrefix()
void clang::analyze_format_string::OptionalAmount::setUsesDotPrefix () inline
Definition at line 396 of file FormatString.h.
Referenced by clang::analyze_printf::PrintfSpecifier::setPrecision().
toString()
void OptionalAmount::toString (raw_ostream & os) const
Definition at line 768 of file FormatString.cpp.
References Arg, Constant, getPositionalArgIndex(), Invalid, NotSpecified, and usesPositionalArg().
Referenced by clang::analyze_printf::PrintfSpecifier::toString(), and clang::analyze_scanf::ScanfSpecifier::toString().
usesDotPrefix()
bool clang::analyze_format_string::OptionalAmount::usesDotPrefix () const inline
Definition at line 395 of file FormatString.h.
usesPositionalArg()
bool clang::analyze_format_string::OptionalAmount::usesPositionalArg () const inline
Definition at line 389 of file FormatString.h.
Referenced by toString().
The documentation for this class was generated from the following files:
include/clang/AST/FormatString.h
lib/AST/FormatString.cpp