clang: clang::serialization::TypeIdx Class Reference
clang::serialization::TypeIdx Class Reference
A type index; the type ID with the qualifier bits removed.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
TypeIdx ()=default
TypeIdx (uint32_t index)
uint32_t getIndex () const
TypeID asTypeID (unsigned FastQuals) const
Static Public Member Functions
static TypeIdx fromTypeID (TypeID ID)
Detailed Description
A type index; the type ID with the qualifier bits removed.
Definition at line 88 of file ASTBitCodes.h.
Constructor & Destructor Documentation
TypeIdx() [1/2]
clang::serialization::TypeIdx::TypeIdx () default
Referenced by fromTypeID().
TypeIdx() [2/2]
clang::serialization::TypeIdx::TypeIdx (uint32_t index) inline explicit
Definition at line 93 of file ASTBitCodes.h.
Member Function Documentation
asTypeID()
TypeID clang::serialization::TypeIdx::asTypeID (unsigned FastQuals) const inline
Definition at line 97 of file ASTBitCodes.h.
References clang::Qualifiers::FastWidth.
Referenced by clang::serialization::MakeTypeID().
fromTypeID()
static TypeIdx clang::serialization::TypeIdx::fromTypeID (TypeID ID) inline static
Definition at line 104 of file ASTBitCodes.h.
References clang::Qualifiers::FastWidth, and TypeIdx().
Referenced by clang::ASTReader::GetType().
getIndex()
uint32_t clang::serialization::TypeIdx::getIndex () const inline
Definition at line 95 of file ASTBitCodes.h.
Referenced by clang::ASTWriter::GetOrCreateTypeID().
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTBitCodes.h