clang: clang::ODRDiagsEmitter Class Reference
clang::ODRDiagsEmitter Class Reference
#include "clang/AST/ODRDiagsEmitter.h"
Public Member Functions
ODRDiagsEmitter (DiagnosticsEngine &Diags, const ASTContext &Context, const LangOptions &LangOpts)
bool diagnoseMismatch (const FunctionDecl *FirstFunction, const FunctionDecl *SecondFunction) const
Diagnose ODR mismatch between 2 FunctionDecl.
bool diagnoseMismatch (const EnumDecl *FirstEnum, const EnumDecl *SecondEnum) const
Diagnose ODR mismatch between 2 EnumDecl.
bool diagnoseMismatch (const CXXRecordDecl *FirstRecord, const CXXRecordDecl *SecondRecord, const struct CXXRecordDecl::DefinitionData *SecondDD) const
Diagnose ODR mismatch between 2 CXXRecordDecl.
bool diagnoseMismatch (const RecordDecl *FirstRecord, const RecordDecl *SecondRecord) const
Diagnose ODR mismatch between 2 RecordDecl that are not CXXRecordDecl.
bool diagnoseMismatch (const ObjCInterfaceDecl *FirstID, const ObjCInterfaceDecl *SecondID, const struct ObjCInterfaceDecl::DefinitionData *SecondDD) const
Diagnose ODR mismatch between 2 ObjCInterfaceDecl.
bool diagnoseMismatch (const ObjCInterfaceDecl *FirstID, const ObjCInterfaceDecl *SecondID) const
Diagnose ODR mismatch between ObjCInterfaceDecl with different definitions.
bool diagnoseMismatch (const ObjCProtocolDecl *FirstProtocol, const ObjCProtocolDecl *SecondProtocol, const struct ObjCProtocolDecl::DefinitionData *SecondDD) const
Diagnose ODR mismatch between 2 ObjCProtocolDecl.
bool diagnoseMismatch (const ObjCProtocolDecl *FirstProtocol, const ObjCProtocolDecl *SecondProtocol) const
Diagnose ODR mismatch between ObjCProtocolDecl with different definitions.
Static Public Member Functions
static std::string getOwningModuleNameForDiagnostic (const Decl *D)
Get the best name we know for the module that owns the given declaration, or an empty string if the declaration is not from a module.
Detailed Description
Definition at line 20 of file ODRDiagsEmitter.h.
Constructor & Destructor Documentation
ODRDiagsEmitter()
clang::ODRDiagsEmitter::ODRDiagsEmitter (DiagnosticsEngine & Diags, const ASTContext & Context, const LangOptions & LangOpts) inline
Definition at line 22 of file ODRDiagsEmitter.h.
Member Function Documentation
diagnoseMismatch() [1/8]
bool ODRDiagsEmitter::diagnoseMismatch (const CXXRecordDecl * FirstRecord, const CXXRecordDecl * SecondRecord, const struct CXXRecordDecl::DefinitionData * SecondDD) const
Diagnose ODR mismatch between 2 CXXRecordDecl.
Returns true if found a mismatch and diagnosed it. To compare 2 declarations with merged and identical definition data you need to provide pre-merge definition data in SecondDD.
Definition at line 704 of file ODRDiagsEmitter.cpp.
References clang::ODRHash::AddFunctionDecl(), clang::ODRHash::AddTemplateParameterList(), clang::TemplateParameterList::asArray(), clang::ODRHash::CalculateHash(), clang::cast(), computeODRHash(), clang::NonTypeTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateTypeParmDecl::defaultArgumentWasInherited(), Diag(), diagnoseSubMismatchMethodParameters(), clang::CXXBaseSpecifier::getAccessSpecifierAsWritten(), clang::TemplateArgumentLoc::getArgument(), clang::DeclarationName::getAsIdentifierInfo(), clang::StaticAssertDecl::getAssertExpr(), clang::Decl::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::NamedDecl::getDeclName(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::TemplateTypeParmDecl::getDefaultArgument(), clang::CXXRecordDecl::getDescribedClassTemplate(), clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendLoc(), clang::FriendDecl::getFriendType(), clang::NamedDecl::getIdentifier(), clang::VarDecl::getInit(), clang::Decl::getKind(), clang::Decl::getLocation(), clang::StaticAssertDecl::getMessage(), clang::NamedDecl::getName(), clang::FunctionDecl::getODRHash(), getOwningModuleNameForDiagnostic(), clang::TemplateParameterList::getParam(), clang::FunctionDecl::getParamDecl(), clang::CXXBaseSpecifier::getSourceRange(), clang::Decl::getSourceRange(), clang::FriendDecl::getSourceRange(), clang::FunctionDecl::getSourceRange(), clang::StaticAssertDecl::getSourceRange(), clang::Stmt::getSourceRange(), clang::TemplateDecl::getSourceRange(), clang::FunctionDecl::getStorageClass(), clang::TemplateDecl::getTemplateParameters(), clang::FunctionDecl::getTemplateSpecializationArgs(), clang::CXXBaseSpecifier::getType(), clang::TypeSourceInfo::getType(), clang::ValueDecl::getType(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), clang::TemplateTypeParmDecl::hasDefaultArgument(), int, clang::CXXMethodDecl::isConst(), clang::FunctionDecl::isDeletedAsWritten(), clang::FunctionDecl::isExplicitlyDefaulted(), clang::DeclarationName::isIdentifier(), clang::FunctionDecl::isInlineSpecified(), clang::NonTypeTemplateParmDecl::isParameterPack(), clang::TemplateTemplateParmDecl::isParameterPack(), clang::TemplateTypeParmDecl::isParameterPack(), clang::FunctionDecl::isPure(), clang::ODRHash::isSubDeclToBeProcessed(), clang::CXXBaseSpecifier::isVirtual(), clang::FunctionDecl::isVirtualAsWritten(), clang::CXXMethodDecl::isVolatile(), N, clang::TemplateArgument::Pack, clang::FunctionDecl::param_size(), clang::SC_Static, and clang::TemplateParameterList::size().
diagnoseMismatch() [2/8]
bool ODRDiagsEmitter::diagnoseMismatch (const EnumDecl * FirstEnum, const EnumDecl * SecondEnum) const
Diagnose ODR mismatch between 2 EnumDecl.
Returns true if found a mismatch and diagnosed it.
Definition at line 1787 of file ODRDiagsEmitter.cpp.
References computeODRHash(), Diag(), Enum, clang::NamedDecl::getDeclName(), clang::EnumConstantDecl::getInitExpr(), clang::EnumDecl::getIntegerTypeSourceInfo(), getOwningModuleNameForDiagnostic(), clang::EnumDecl::getSourceRange(), clang::TypeSourceInfo::getType(), int, clang::QualType::isNull(), clang::EnumDecl::isScoped(), clang::EnumDecl::isScopedUsingClassTag(), clang::ODRHash::isSubDeclToBeProcessed(), and N.
diagnoseMismatch() [3/8]
bool ODRDiagsEmitter::diagnoseMismatch (const FunctionDecl * FirstFunction, const FunctionDecl * SecondFunction) const
Diagnose ODR mismatch between 2 FunctionDecl.
Returns true if found a mismatch and diagnosed it.
Definition at line 1654 of file ODRDiagsEmitter.cpp.
References computeODRHash(), Diag(), clang::Type::getAs(), clang::SourceRange::getBegin(), clang::NamedDecl::getDeclName(), clang::VarDecl::getInit(), clang::Decl::getLocation(), getOwningModuleNameForDiagnostic(), clang::FunctionDecl::getParamDecl(), clang::FunctionDecl::getReturnType(), clang::FunctionDecl::getReturnTypeSourceRange(), clang::FunctionDecl::getSourceRange(), clang::ParmVarDecl::getSourceRange(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::ASTContext::hasSameType(), and clang::FunctionDecl::param_size().
Referenced by diagnoseMismatch(), and diagnoseMismatch().
diagnoseMismatch() [4/8]
bool clang::ODRDiagsEmitter::diagnoseMismatch (const ObjCInterfaceDecl * FirstID, const ObjCInterfaceDecl * SecondID) const inline
Diagnose ODR mismatch between ObjCInterfaceDecl with different definitions.
Definition at line 63 of file ODRDiagsEmitter.h.
References diagnoseMismatch().
diagnoseMismatch() [5/8]
bool ODRDiagsEmitter::diagnoseMismatch (const ObjCInterfaceDecl * FirstID, const ObjCInterfaceDecl * SecondID, const struct ObjCInterfaceDecl::DefinitionData * SecondDD) const
Diagnose ODR mismatch between 2 ObjCInterfaceDecl.
Returns true if found a mismatch and diagnosed it.
Definition at line 1921 of file ODRDiagsEmitter.cpp.
References bool, clang::cast(), clang::Type::castAs(), computeODRHash(), Diag(), clang::ObjCIvarDecl::getCanonicalAccessControl(), clang::ObjCInterfaceDecl::getDefinition(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::ObjCInterfaceDecl::getODRHash(), getOwningModuleNameForDiagnostic(), clang::ObjCInterfaceDecl::getReferencedProtocols(), clang::Decl::getSourceRange(), clang::FieldDecl::getSourceRange(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCInterfaceDecl::getSuperClassTInfo(), clang::TypeSourceInfo::getType(), clang::TypeSourceInfo::getTypeLoc(), int, and clang::ODRHash::isSubDeclToBeProcessed().
diagnoseMismatch() [6/8]
bool clang::ODRDiagsEmitter::diagnoseMismatch (const ObjCProtocolDecl * FirstProtocol, const ObjCProtocolDecl * SecondProtocol) const inline
Diagnose ODR mismatch between ObjCProtocolDecl with different definitions.
Definition at line 81 of file ODRDiagsEmitter.h.
References diagnoseMismatch().
diagnoseMismatch() [7/8]
bool ODRDiagsEmitter::diagnoseMismatch (const ObjCProtocolDecl * FirstProtocol, const ObjCProtocolDecl * SecondProtocol, const struct ObjCProtocolDecl::DefinitionData * SecondDD) const
Diagnose ODR mismatch between 2 ObjCProtocolDecl.
Returns true if found a mismatch and diagnosed it. To compare 2 declarations with merged and identical definition data you need to provide pre-merge definition data in SecondDD.
Definition at line 2107 of file ODRDiagsEmitter.cpp.
References computeODRHash(), Diag(), clang::ObjCProtocolDecl::getDefinition(), clang::Decl::getLocation(), getOwningModuleNameForDiagnostic(), clang::ObjCProtocolDecl::getReferencedProtocols(), clang::Decl::getSourceRange(), and clang::ODRHash::isSubDeclToBeProcessed().
diagnoseMismatch() [8/8]
bool ODRDiagsEmitter::diagnoseMismatch (const RecordDecl * FirstRecord, const RecordDecl * SecondRecord) const
Diagnose ODR mismatch between 2 RecordDecl that are not CXXRecordDecl.
Returns true if found a mismatch and diagnosed it.
Definition at line 1558 of file ODRDiagsEmitter.cpp.
References computeODRHash(), Diag(), clang::Decl::getLocation(), getOwningModuleNameForDiagnostic(), clang::Decl::getSourceRange(), and clang::ODRHash::isSubDeclToBeProcessed().
getOwningModuleNameForDiagnostic()
std::string ODRDiagsEmitter::getOwningModuleNameForDiagnostic (const Decl * D) static
Get the best name we know for the module that owns the given declaration, or an empty string if the declaration is not from a module.
Definition at line 43 of file ODRDiagsEmitter.cpp.
References clang::Decl::getImportedOwningModule().
Referenced by diagnoseMismatch(), diagnoseMismatch(), diagnoseMismatch(), diagnoseMismatch(), diagnoseMismatch(), and diagnoseMismatch().
The documentation for this class was generated from the following files:
include/clang/AST/ODRDiagsEmitter.h
lib/AST/ODRDiagsEmitter.cpp