clang: clang::ento::SymbolVisitor Class Reference
clang::ento::SymbolVisitor Class Reference abstract
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
SymbolVisitor ()=default
SymbolVisitor (const SymbolVisitor &)=default
SymbolVisitor (SymbolVisitor &&)
SymbolVisitor & operator= (const SymbolVisitor &)=delete
SymbolVisitor & operator= (SymbolVisitor &&)=delete
virtual bool VisitSymbol (SymbolRef sym)=0
A visitor method invoked by ProgramStateManager::scanReachableSymbols.
virtual bool VisitMemRegion (const MemRegion *)
Protected Member Functions
~SymbolVisitor ()=default
Detailed Description
Definition at line 666 of file SymbolManager.h.
Constructor & Destructor Documentation
~SymbolVisitor()
clang::ento::SymbolVisitor::~SymbolVisitor () protected default
SymbolVisitor() [1/3]
clang::ento::SymbolVisitor::SymbolVisitor () default
SymbolVisitor() [2/3]
clang::ento::SymbolVisitor::SymbolVisitor (const SymbolVisitor &) default
SymbolVisitor() [3/3]
clang::ento::SymbolVisitor::SymbolVisitor (SymbolVisitor &&) inline
Definition at line 673 of file SymbolManager.h.
Member Function Documentation
operator=() [1/2]
SymbolVisitor & clang::ento::SymbolVisitor::operator= (const SymbolVisitor &) delete
operator=() [2/2]
SymbolVisitor & clang::ento::SymbolVisitor::operator= (SymbolVisitor &&) delete
VisitMemRegion()
virtual bool clang::ento::SymbolVisitor::VisitMemRegion (const MemRegion *) inline virtual
Definition at line 685 of file SymbolManager.h.
Referenced by clang::ento::ScanReachableSymbols::scan().
VisitSymbol()
virtual bool clang::ento::SymbolVisitor::VisitSymbol (SymbolRef sym) pure virtual
A visitor method invoked by ProgramStateManager::scanReachableSymbols.
The method returns true if symbols should continue be scanned and false otherwise.
Referenced by clang::ento::ScanReachableSymbols::scan(), and clang::ento::ScanReachableSymbols::scan().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h