clang: clang::GCCAsmStmt Class Reference
clang::GCCAsmStmt Class Reference
This represents a GCC inline-assembly statement extension.
#include "clang/AST/Stmt.h"
Classes
class AsmStringPiece
AsmStringPiece - this is part of a decomposed asm string specification (for use with the AnalyzeAsmString function below).
Public Types
using labels_iterator = CastIterator<AddrLabelExpr>
using const_labels_iterator = ConstCastIterator<AddrLabelExpr>
using labels_range = llvm::iterator_range<labels_iterator>
using labels_const_range = llvm::iterator_range<const_labels_iterator>
Public Types inherited from clang::AsmStmt
using inputs_iterator = ExprIterator
using const_inputs_iterator = ConstExprIterator
using inputs_range = llvm::iterator_range<inputs_iterator>
using inputs_const_range = llvm::iterator_range<const_inputs_iterator>
using outputs_iterator = ExprIterator
using const_outputs_iterator = ConstExprIterator
using outputs_range = llvm::iterator_range<outputs_iterator>
using outputs_const_range = llvm::iterator_range<const_outputs_iterator>
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
GCCAsmStmt (const ASTContext &C, SourceLocation asmloc, bool issimple, bool isvolatile, unsigned numoutputs, unsigned numinputs, IdentifierInfo **names, StringLiteral **constraints, Expr **exprs, StringLiteral *asmstr, unsigned numclobbers, StringLiteral **clobbers, unsigned numlabels, SourceLocation rparenloc)
GCCAsmStmt (EmptyShell Empty)
Build an empty inline-assembly statement.
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation L)
const StringLiteral * getAsmString () const
StringLiteral * getAsmString ()
void setAsmString (StringLiteral *E)
unsigned AnalyzeAsmString (SmallVectorImpl< AsmStringPiece > &Pieces, const ASTContext &C, unsigned &DiagOffs) const
AnalyzeAsmString - Analyze the asm string of the current asm, decomposing it into pieces.
std::string generateAsmString (const ASTContext &C) const
Assemble final IR asm string.
IdentifierInfo * getOutputIdentifier (unsigned i) const
StringRef getOutputName (unsigned i) const
StringRef getOutputConstraint (unsigned i) const
getOutputConstraint - Return the constraint string for the specified output operand.
const StringLiteral * getOutputConstraintLiteral (unsigned i) const
StringLiteral * getOutputConstraintLiteral (unsigned i)
Expr * getOutputExpr (unsigned i)
const Expr * getOutputExpr (unsigned i) const
IdentifierInfo * getInputIdentifier (unsigned i) const
StringRef getInputName (unsigned i) const
StringRef getInputConstraint (unsigned i) const
getInputConstraint - Return the specified input constraint.
const StringLiteral * getInputConstraintLiteral (unsigned i) const
StringLiteral * getInputConstraintLiteral (unsigned i)
Expr * getInputExpr (unsigned i)
void setInputExpr (unsigned i, Expr *E)
const Expr * getInputExpr (unsigned i) const
bool isAsmGoto () const
unsigned getNumLabels () const
IdentifierInfo * getLabelIdentifier (unsigned i) const
AddrLabelExpr * getLabelExpr (unsigned i) const
StringRef getLabelName (unsigned i) const
labels_iterator begin_labels ()
labels_iterator end_labels ()
labels_range labels ()
const_labels_iterator begin_labels () const
const_labels_iterator end_labels () const
labels_const_range labels () const
int getNamedOperand (StringRef SymbolicName) const
getNamedOperand - Given a symbolic operand reference like %[foo], translate this into a numeric value needed to reference the same operand.
StringRef getClobber (unsigned i) const
StringLiteral * getClobberStringLiteral (unsigned i)
const StringLiteral * getClobberStringLiteral (unsigned i) const
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
Public Member Functions inherited from clang::AsmStmt
AsmStmt (StmtClass SC, EmptyShell Empty)
Build an empty inline-assembly statement.
SourceLocation getAsmLoc () const
void setAsmLoc (SourceLocation L)
bool isSimple () const
void setSimple (bool V)
bool isVolatile () const
void setVolatile (bool V)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
std::string generateAsmString (const ASTContext &C) const
Assemble final IR asm string.
unsigned getNumOutputs () const
StringRef getOutputConstraint (unsigned i) const
getOutputConstraint - Return the constraint string for the specified output operand.
bool isOutputPlusConstraint (unsigned i) const
isOutputPlusConstraint - Return true if the specified output constraint is a "+" constraint (which is both an input and an output) or false if it is an "=" constraint (just an output).
const Expr * getOutputExpr (unsigned i) const
unsigned getNumPlusOperands () const
getNumPlusOperands - Return the number of output operands that have a "+" constraint.
unsigned getNumInputs () const
StringRef getInputConstraint (unsigned i) const
getInputConstraint - Return the specified input constraint.
const Expr * getInputExpr (unsigned i) const
unsigned getNumClobbers () const
StringRef getClobber (unsigned i) const
inputs_iterator begin_inputs ()
inputs_iterator end_inputs ()
inputs_range inputs ()
const_inputs_iterator begin_inputs () const
const_inputs_iterator end_inputs () const
inputs_const_range inputs () const
outputs_iterator begin_outputs ()
outputs_iterator end_outputs ()
outputs_range outputs ()
const_outputs_iterator begin_outputs () const
const_outputs_iterator end_outputs () const
outputs_const_range outputs () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::AsmStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
Additional Inherited Members
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::AsmStmt
AsmStmt (StmtClass SC, SourceLocation asmloc, bool issimple, bool isvolatile, unsigned numoutputs, unsigned numinputs, unsigned numclobbers)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::AsmStmt
SourceLocation AsmLoc
bool IsSimple
True if the assembly statement does not have any input or output operands.
bool IsVolatile
If true, treat this inline assembly as having side effects.
unsigned NumOutputs
unsigned NumInputs
unsigned NumClobbers
Stmt ** Exprs = nullptr
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
This represents a GCC inline-assembly statement extension.
Definition at line 3080 of file Stmt.h.
Member Typedef Documentation
const_labels_iterator
using clang::GCCAsmStmt::const_labels_iterator = ConstCastIterator<AddrLabelExpr>
Definition at line 3240 of file Stmt.h.
labels_const_range
using clang::GCCAsmStmt::labels_const_range = llvm::iterator_range<const_labels_iterator>
Definition at line 3242 of file Stmt.h.
labels_iterator
using clang::GCCAsmStmt::labels_iterator = CastIterator<AddrLabelExpr>
Definition at line 3239 of file Stmt.h.
labels_range
using clang::GCCAsmStmt::labels_range = llvm::iterator_range<labels_iterator>
Definition at line 3241 of file Stmt.h.
Constructor & Destructor Documentation
GCCAsmStmt() [1/2]
GCCAsmStmt::GCCAsmStmt (const ASTContext & C, SourceLocation asmloc, bool issimple, bool isvolatile, unsigned numoutputs, unsigned numinputs, IdentifierInfo ** names, StringLiteral ** constraints, Expr ** exprs, StringLiteral * asmstr, unsigned numclobbers, StringLiteral ** clobbers, unsigned numlabels, SourceLocation rparenloc)
Definition at line 846 of file Stmt.cpp.
References clang::C, clang::AsmStmt::Exprs, clang::AsmStmt::NumClobbers, clang::NumConstraints, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
GCCAsmStmt() [2/2]
clang::GCCAsmStmt::GCCAsmStmt (EmptyShell Empty) inline explicit
Build an empty inline-assembly statement.
Definition at line 3101 of file Stmt.h.
Member Function Documentation
AnalyzeAsmString()
unsigned GCCAsmStmt::AnalyzeAsmString (SmallVectorImpl< AsmStringPiece > & Pieces, const ASTContext & C, unsigned & DiagOffs) const
AnalyzeAsmString - Analyze the asm string of the current asm, decomposing it into pieces.
If the asm string is erroneous, emit errors and return true, otherwise return false. This handles canonicalization and translation of strings from GCC syntax to LLVM IR syntax, and handles
If the asm string is erroneous, emit errors and return true, otherwise return false.
Definition at line 601 of file Stmt.cpp.
References Begin, clang::C, getAsmString(), clang::StringLiteral::getLocationOfByte(), getNamedOperand(), clang::AsmStmt::getNumInputs(), getNumLabels(), clang::AsmStmt::getNumOutputs(), clang::AsmStmt::getNumPlusOperands(), clang::StringLiteral::getString(), clang::TargetInfo::handleAsmEscapedChar(), clang::isDigit(), clang::isLetter(), clang::AsmStmt::isSimple(), N, clang::Result, and SM.
Referenced by generateAsmString().
begin_labels() [1/2]
labels_iterator clang::GCCAsmStmt::begin_labels () inline
Definition at line 3244 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
Referenced by labels(), and labels().
begin_labels() [2/2]
const_labels_iterator clang::GCCAsmStmt::begin_labels () const inline
Definition at line 3256 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
classof()
static bool clang::GCCAsmStmt::classof (const Stmt * T) inline static
Definition at line 3297 of file Stmt.h.
end_labels() [1/2]
labels_iterator clang::GCCAsmStmt::end_labels () inline
Definition at line 3248 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
Referenced by labels(), and labels().
end_labels() [2/2]
const_labels_iterator clang::GCCAsmStmt::end_labels () const inline
Definition at line 3260 of file Stmt.h.
References clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
generateAsmString()
std::string GCCAsmStmt::generateAsmString (const ASTContext & C) const
Assemble final IR asm string.
Assemble final IR asm string (GCC-style).
Definition at line 784 of file Stmt.cpp.
References AnalyzeAsmString(), and clang::C.
getAsmString() [1/2]
StringLiteral * clang::GCCAsmStmt::getAsmString () inline
Definition at line 3109 of file Stmt.h.
getAsmString() [2/2]
const StringLiteral * clang::GCCAsmStmt::getAsmString () const inline
Definition at line 3108 of file Stmt.h.
Referenced by AnalyzeAsmString().
getBeginLoc()
SourceLocation clang::GCCAsmStmt::getBeginLoc () const inline
Definition at line 3294 of file Stmt.h.
References clang::AsmStmt::AsmLoc.
getClobber()
StringRef GCCAsmStmt::getClobber (unsigned i) const
Definition at line 504 of file Stmt.cpp.
References getClobberStringLiteral(), and clang::StringLiteral::getString().
getClobberStringLiteral() [1/2]
StringLiteral * clang::GCCAsmStmt::getClobberStringLiteral (unsigned i) inline
Definition at line 3289 of file Stmt.h.
Referenced by getClobber().
getClobberStringLiteral() [2/2]
const StringLiteral * clang::GCCAsmStmt::getClobberStringLiteral (unsigned i) const inline
Definition at line 3290 of file Stmt.h.
getEndLoc()
SourceLocation clang::GCCAsmStmt::getEndLoc () const inline
Definition at line 3295 of file Stmt.h.
getInputConstraint()
StringRef GCCAsmStmt::getInputConstraint (unsigned i) const
getInputConstraint - Return the specified input constraint.
Unlike output constraints, these can be empty.
Definition at line 537 of file Stmt.cpp.
References getInputConstraintLiteral(), and clang::StringLiteral::getString().
getInputConstraintLiteral() [1/2]
StringLiteral * clang::GCCAsmStmt::getInputConstraintLiteral (unsigned i) inline
Definition at line 3212 of file Stmt.h.
References clang::AsmStmt::NumOutputs.
getInputConstraintLiteral() [2/2]
const StringLiteral * clang::GCCAsmStmt::getInputConstraintLiteral (unsigned i) const inline
Definition at line 3209 of file Stmt.h.
References clang::AsmStmt::NumOutputs.
Referenced by getInputConstraint().
getInputExpr() [1/2]
Expr * GCCAsmStmt::getInputExpr (unsigned i)
Definition at line 519 of file Stmt.cpp.
References clang::cast(), clang::AsmStmt::Exprs, and clang::AsmStmt::NumOutputs.
Referenced by getInputExpr().
getInputExpr() [2/2]
const Expr * clang::GCCAsmStmt::getInputExpr (unsigned i) const inline
Definition at line 3219 of file Stmt.h.
References getInputExpr().
getInputIdentifier()
IdentifierInfo * clang::GCCAsmStmt::getInputIdentifier (unsigned i) const inline
Definition at line 3196 of file Stmt.h.
References clang::AsmStmt::NumOutputs.
Referenced by getInputName().
getInputName()
StringRef clang::GCCAsmStmt::getInputName (unsigned i) const inline
Definition at line 3200 of file Stmt.h.
References getInputIdentifier().
Referenced by getNamedOperand().
getLabelExpr()
AddrLabelExpr * GCCAsmStmt::getLabelExpr (unsigned i) const
Definition at line 527 of file Stmt.cpp.
References clang::cast(), clang::AsmStmt::Exprs, clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
Referenced by getLabelName().
getLabelIdentifier()
IdentifierInfo * clang::GCCAsmStmt::getLabelIdentifier (unsigned i) const inline
Definition at line 3233 of file Stmt.h.
References clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
getLabelName()
StringRef GCCAsmStmt::getLabelName (unsigned i) const
Definition at line 531 of file Stmt.cpp.
References clang::AddrLabelExpr::getLabel(), getLabelExpr(), and clang::NamedDecl::getName().
Referenced by getNamedOperand().
getNamedOperand()
int GCCAsmStmt::getNamedOperand (StringRef SymbolicName) const
getNamedOperand - Given a symbolic operand reference like %[foo], translate this into a numeric value needed to reference the same operand.
This returns -1 if the operand name is invalid.
Definition at line 578 of file Stmt.cpp.
References getInputName(), getLabelName(), clang::AsmStmt::getNumInputs(), getNumLabels(), clang::AsmStmt::getNumOutputs(), clang::AsmStmt::getNumPlusOperands(), getOutputName(), clang::AsmStmt::NumInputs, and clang::AsmStmt::NumOutputs.
Referenced by AnalyzeAsmString().
getNumLabels()
unsigned clang::GCCAsmStmt::getNumLabels () const inline
Definition at line 3229 of file Stmt.h.
Referenced by AnalyzeAsmString(), and getNamedOperand().
getOutputConstraint()
StringRef GCCAsmStmt::getOutputConstraint (unsigned i) const
getOutputConstraint - Return the constraint string for the specified output operand.
All output constraints are known to be non-empty (either '=' or '+').
Definition at line 515 of file Stmt.cpp.
References getOutputConstraintLiteral(), and clang::StringLiteral::getString().
getOutputConstraintLiteral() [1/2]
StringLiteral * clang::GCCAsmStmt::getOutputConstraintLiteral (unsigned i) inline
Definition at line 3184 of file Stmt.h.
getOutputConstraintLiteral() [2/2]
const StringLiteral * clang::GCCAsmStmt::getOutputConstraintLiteral (unsigned i) const inline
Definition at line 3181 of file Stmt.h.
Referenced by getOutputConstraint().
getOutputExpr() [1/2]
Expr * GCCAsmStmt::getOutputExpr (unsigned i)
Definition at line 508 of file Stmt.cpp.
References clang::cast(), and clang::AsmStmt::Exprs.
Referenced by getOutputExpr().
getOutputExpr() [2/2]
const Expr * clang::GCCAsmStmt::getOutputExpr (unsigned i) const inline
Definition at line 3190 of file Stmt.h.
References getOutputExpr().
getOutputIdentifier()
IdentifierInfo * clang::GCCAsmStmt::getOutputIdentifier (unsigned i) const inline
Definition at line 3170 of file Stmt.h.
Referenced by getOutputName().
getOutputName()
StringRef clang::GCCAsmStmt::getOutputName (unsigned i) const inline
Definition at line 3172 of file Stmt.h.
References getOutputIdentifier().
Referenced by getNamedOperand().
getRParenLoc()
SourceLocation clang::GCCAsmStmt::getRParenLoc () const inline
Definition at line 3103 of file Stmt.h.
isAsmGoto()
bool clang::GCCAsmStmt::isAsmGoto () const inline
Definition at line 3225 of file Stmt.h.
Referenced by runOnBlock().
labels() [1/2]
labels_range clang::GCCAsmStmt::labels () inline
Definition at line 3252 of file Stmt.h.
References begin_labels(), and end_labels().
labels() [2/2]
labels_const_range clang::GCCAsmStmt::labels () const inline
Definition at line 3264 of file Stmt.h.
References begin_labels(), and end_labels().
setAsmString()
void clang::GCCAsmStmt::setAsmString (StringLiteral * E) inline
Definition at line 3110 of file Stmt.h.
setInputExpr()
void GCCAsmStmt::setInputExpr (unsigned i, Expr * E)
Definition at line 523 of file Stmt.cpp.
References clang::AsmStmt::Exprs, and clang::AsmStmt::NumOutputs.
setRParenLoc()
void clang::GCCAsmStmt::setRParenLoc (SourceLocation L) inline
Definition at line 3104 of file Stmt.h.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 3081 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp