clang: UPCPreIncrementGadget Class Reference
UPCPreIncrementGadget Class Reference
Public Member Functions
UPCPreIncrementGadget (const MatchFinder::MatchResult &Result)
virtual std::optional< FixItList > getFixits (const Strategy &S) const override
virtual const Stmt * getBaseStmt () const override
virtual DeclUseList getClaimedVarUseSites () const override
Static Public Member Functions
static bool classof (const Gadget *G)
static Matcher matcher ()
Detailed Description
Definition at line 911 of file UnsafeBufferUsage.cpp.
Constructor & Destructor Documentation
UPCPreIncrementGadget()
UPCPreIncrementGadget::UPCPreIncrementGadget (const MatchFinder::MatchResult & Result) inline
Definition at line 918 of file UnsafeBufferUsage.cpp.
References Node.
Member Function Documentation
classof()
static bool UPCPreIncrementGadget::classof (const Gadget * G) inline static
Definition at line 924 of file UnsafeBufferUsage.cpp.
getBaseStmt()
virtual const Stmt * UPCPreIncrementGadget::getBaseStmt () const inline override virtual
Definition at line 941 of file UnsafeBufferUsage.cpp.
References Node.
getClaimedVarUseSites()
virtual DeclUseList UPCPreIncrementGadget::getClaimedVarUseSites () const inline override virtual
Definition at line 943 of file UnsafeBufferUsage.cpp.
References Node.
getFixits()
std::optional< FixItList > UPCPreIncrementGadget::getFixits (const Strategy & S) const override virtual
Definition at line 1594 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::CreateReplacement(), clang::Decl::getASTContext(), clang::Stmt::getBeginLoc(), getEndCharLoc(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getName(), and clang::ASTContext::getSourceManager().
matcher()
static Matcher UPCPreIncrementGadget::matcher () inline static
Definition at line 928 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::declRefExpr, clang::ast_matchers::expr, clang::ast_matchers::isInUnspecifiedPointerContext(), clang::ast_matchers::stmt, and clang::ast_matchers::unaryOperator.
The documentation for this class was generated from the following file:
lib/Analysis/UnsafeBufferUsage.cpp