clang: clang::ento::bugreporter::StoreHandler Class Reference
clang::ento::bugreporter::StoreHandler Class Reference abstract
Handles stores during the tracking.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Public Member Functions
StoreHandler (Tracker &ParentTracker)
virtual ~StoreHandler ()
virtual PathDiagnosticPieceRef handle (StoreInfo SI, BugReporterContext &BRC, TrackingOptions Opts)=0
Handle the given store and produce the node.
Tracker & getParentTracker ()
Protected Member Functions
PathDiagnosticPieceRef constructNote (StoreInfo SI, BugReporterContext &BRC, StringRef NodeText)
Detailed Description
Handles stores during the tracking.
Definition at line 322 of file BugReporterVisitors.h.
Constructor & Destructor Documentation
StoreHandler()
clang::ento::bugreporter::StoreHandler::StoreHandler (Tracker & ParentTracker) inline
Definition at line 327 of file BugReporterVisitors.h.
~StoreHandler()
virtual clang::ento::bugreporter::StoreHandler::~StoreHandler () inline virtual
Definition at line 328 of file BugReporterVisitors.h.
Member Function Documentation
constructNote()
PathDiagnosticPieceRef StoreHandler::constructNote (StoreInfo SI, BugReporterContext & BRC, StringRef NodeText) protected
Definition at line 2193 of file BugReporterVisitors.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::PathDiagnosticLocation::create(), clang::ento::ExplodedNode::getLocation(), clang::ento::BugReporterContext::getSourceManager(), clang::ento::PathDiagnosticLocation::isValid(), clang::SourceLocation::isValid(), P, clang::ento::bugreporter::StoreInfo::SourceOfTheValue, and clang::ento::bugreporter::StoreInfo::StoreSite.
getParentTracker()
Tracker & clang::ento::bugreporter::StoreHandler::getParentTracker () inline
Definition at line 340 of file BugReporterVisitors.h.
handle()
virtual PathDiagnosticPieceRef clang::ento::bugreporter::StoreHandler::handle (StoreInfo SI, BugReporterContext & BRC, TrackingOptions Opts) pure virtual
Handle the given store and produce the node.
Parameters
SI The information fully describing the store.
Opts Tracking options specifying how we are tracking the value.
Returns
the produced note, null if the handler doesn't support this kind of stores.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp