clang: clang::ASTImporterLookupTable Class Reference
clang::ASTImporterLookupTable Class Reference
#include "clang/AST/ASTImporterLookupTable.h"
Public Types
using LookupResult = DeclList
Public Member Functions
ASTImporterLookupTable (TranslationUnitDecl &TU)
void add (NamedDecl *ND)
void remove (NamedDecl *ND)
void update (NamedDecl *ND, DeclContext *OldDC)
void updateForced (NamedDecl *ND, DeclContext *OldDC)
LookupResult lookup (DeclContext *DC, DeclarationName Name) const
bool contains (DeclContext *DC, NamedDecl *ND) const
void dump (DeclContext *DC) const
void dump () const
Detailed Description
Definition at line 46 of file ASTImporterLookupTable.h.
Member Typedef Documentation
LookupResult
using clang::ASTImporterLookupTable::LookupResult = DeclList
Definition at line 81 of file ASTImporterLookupTable.h.
Constructor & Destructor Documentation
ASTImporterLookupTable()
clang::ASTImporterLookupTable::ASTImporterLookupTable (TranslationUnitDecl & TU)
Definition at line 87 of file ASTImporterLookupTable.cpp.
References clang::TranslationUnitDecl::getASTContext(), and clang::ASTContext::getVaListTagDecl().
Member Function Documentation
add()
void clang::ASTImporterLookupTable::add (NamedDecl * ND)
Definition at line 126 of file ASTImporterLookupTable.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getPrimaryContext(), and clang::DeclContext::getRedeclContext().
contains()
bool clang::ASTImporterLookupTable::contains (DeclContext * DC, NamedDecl * ND) const
Definition at line 176 of file ASTImporterLookupTable.cpp.
References clang::NamedDecl::getDeclName(), and lookup().
Referenced by update().
dump() [1/2]
void clang::ASTImporterLookupTable::dump () const
Definition at line 196 of file ASTImporterLookupTable.cpp.
References clang::cast(), dump(), and clang::DeclContext::getPrimaryContext().
Referenced by dump().
dump() [2/2]
void clang::ASTImporterLookupTable::dump (DeclContext * DC) const
Definition at line 180 of file ASTImporterLookupTable.cpp.
References clang::DeclContext::getPrimaryContext().
lookup()
ASTImporterLookupTable::LookupResult clang::ASTImporterLookupTable::lookup (DeclContext * DC, DeclarationName Name) const
Definition at line 163 of file ASTImporterLookupTable.cpp.
References clang::DeclContext::getPrimaryContext().
Referenced by contains().
remove()
void clang::ASTImporterLookupTable::remove (NamedDecl * ND)
Definition at line 135 of file ASTImporterLookupTable.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getPrimaryContext(), and clang::DeclContext::getRedeclContext().
update()
void clang::ASTImporterLookupTable::update (NamedDecl * ND, DeclContext * OldDC)
Definition at line 144 of file ASTImporterLookupTable.cpp.
References contains(), and clang::Decl::getDeclContext().
Referenced by clang::ASTNodeImporter::VisitFunctionDecl().
updateForced()
void clang::ASTImporterLookupTable::updateForced (NamedDecl * ND, DeclContext * OldDC)
Definition at line 157 of file ASTImporterLookupTable.cpp.
References clang::NamedDecl::getDeclName().
Referenced by clang::ASTNodeImporter::VisitFunctionTemplateDecl().
The documentation for this class was generated from the following files:
include/clang/AST/ASTImporterLookupTable.h
lib/AST/ASTImporterLookupTable.cpp