clang: clang::LangOptions Class Reference
clang::LangOptions Class Reference
Keeps track of the various options that can be enabled, which controls the dialect of C or C++ that is accepted.
#include "clang/Basic/LangOptions.h"
Public Types
enum GCMode { NonGC , GCOnly , HybridGC }
enum StackProtectorMode { SSPOff , SSPOn , SSPStrong , SSPReq }
enum class TrivialAutoVarInitKind { Uninitialized , Zero , Pattern }
enum SignedOverflowBehaviorTy { SOB_Undefined , SOB_Defined , SOB_Trapping }
enum CompilingModuleKind { CMK_None , CMK_ModuleMap , CMK_HeaderUnit , CMK_ModuleInterface }
enum PragmaMSPointersToMembersKind { PPTMK_BestCase , PPTMK_FullGeneralitySingleInheritance , PPTMK_FullGeneralityMultipleInheritance , PPTMK_FullGeneralityVirtualInheritance }
enum DefaultCallingConvention {
DCC_None , DCC_CDecl , DCC_FastCall , DCC_StdCall ,
DCC_VectorCall , DCC_RegCall
}
enum AddrSpaceMapMangling { ASMM_Target , ASMM_On , ASMM_Off }
enum MSVCMajorVersion {
MSVC2010 = 1600 , MSVC2012 = 1700 , MSVC2013 = 1800 , MSVC2015 = 1900 ,
MSVC2017 = 1910 , MSVC2017_5 = 1912 , MSVC2017_7 = 1914 , MSVC2019 = 1920 ,
MSVC2019_5 = 1925 , MSVC2019_8 = 1928
}
enum SYCLMajorVersion { SYCL_None , SYCL_2017 , SYCL_2020 , SYCL_Default = SYCL_2020 }
enum HLSLLangStd {
HLSL_Unset = 0 , HLSL_2015 = 2015 , HLSL_2016 = 2016 , HLSL_2017 = 2017 ,
HLSL_2018 = 2018 , HLSL_2021 = 2021 , HLSL_202x = 2029
}
enum class ClangABI {
Ver3_8 , Ver4 , Ver6 , Ver7 ,
Ver9 , Ver11 , Ver12 , Ver14 ,
Ver15 , Latest
}
Clang versions with different platform ABI conformance.
enum class CoreFoundationABI {
Unspecified , Standalone , ObjectiveC , Swift ,
Swift5_0 , Swift4_2 , Swift4_1
}
enum FPModeKind { FPM_Off , FPM_On , FPM_Fast , FPM_FastHonorPragmas }
enum FPExceptionModeKind { FPE_Ignore , FPE_MayTrap , FPE_Strict , FPE_Default }
Possible floating point exception behavior.
enum FPEvalMethodKind {
FEM_Indeterminable = -1 , FEM_Source = 0 , FEM_Double = 1 , FEM_Extended = 2 ,
FEM_UnsetOnCommandLine = 3
}
Possible float expression evaluation method choices.
enum ExcessPrecisionKind { FPP_Standard , FPP_Fast , FPP_None }
enum class ExceptionHandlingKind {
None , SjLj , WinEH , DwarfCFI ,
Wasm
}
Possible exception handling behavior.
enum class LaxVectorConversionKind { None , Integer , All }
enum class AltivecSrcCompatKind { Mixed , GCC , XL , Default = Mixed }
enum class SignReturnAddressScopeKind { None , NonLeaf , All }
enum class SignReturnAddressKeyKind { AKey , BKey }
enum class ThreadModelKind { POSIX , Single }
enum class ExtendArgsKind { ExtendTo32 , ExtendTo64 }
enum class GPUDefaultStreamKind { Legacy , PerThread }
enum class DefaultVisiblityExportMapping { None , Explicit , All }
enum class StrictFlexArraysLevelKind { Default = 0 , OneZeroOrIncomplete = 1 , ZeroOrIncomplete = 2 , IncompleteOnly = 3 }
using Visibility = clang::Visibility
using RoundingMode = llvm::RoundingMode
using MSVtorDispMode = clang::MSVtorDispMode
Public Member Functions
LangOptions ()
bool isCompilingModule () const
Are we compiling a module?
bool isCompilingModuleInterface () const
Are we compiling a standard c++ module interface?
bool isCompilingModuleImplementation () const
Are we compiling a module implementation?
bool trackLocalOwningModule () const
Do we need to track the owning module for a local declaration?
bool isSignedOverflowDefined () const
bool isSubscriptPointerArithmetic () const
bool isCompatibleWithMSVC (MSVCMajorVersion MajorVersion) const
void resetNonModularOptions ()
Reset all of the options that are not considered when building a module.
bool isNoBuiltinFunc (StringRef Name) const
Is this a libc/libm function that is no longer recognized as a builtin because a -fno-builtin-* option has been specified?
bool allowsNonTrivialObjCLifetimeQualifiers () const
True if any ObjC types may have non-trivial lifetime qualifiers.
bool assumeFunctionsAreConvergent () const
VersionTuple getOpenCLVersionTuple () const
Return the OpenCL C or C++ version as a VersionTuple.
unsigned getOpenCLCompatibleVersion () const
Return the OpenCL version that kernel language is compatible with.
std::string getOpenCLVersionString () const
Return the OpenCL C or C++ for OpenCL language name and version as a string.
bool requiresStrictPrototypes () const
Returns true if functions without prototypes or functions with an identifier list (aka K&R C functions) are not allowed.
bool implicitFunctionsAllowed () const
Returns true if implicit function declarations are allowed in the current language mode.
bool isImplicitIntRequired () const
Returns true if implicit int is part of the language requirements.
bool isImplicitIntAllowed () const
Returns true if implicit int is supported at all.
bool hasSignReturnAddress () const
Check if return address signing is enabled.
bool isSignReturnAddressWithAKey () const
Check if return address signing uses AKey.
bool isSignReturnAddressScopeAll () const
Check if leaf functions are also signed.
bool hasSjLjExceptions () const
bool hasSEHExceptions () const
bool hasDWARFExceptions () const
bool hasWasmExceptions () const
bool isSYCL () const
bool hasDefaultVisibilityExportMapping () const
bool isExplicitDefaultVisibilityExportMapping () const
bool isAllDefaultVisibilityExportMapping () const
void remapPathPrefix (SmallVectorImpl< char > &Path) const
Remap path prefix according to -fmacro-prefix-path option.
RoundingMode getDefaultRoundingMode () const
FPExceptionModeKind getDefaultExceptionMode () const
Static Public Member Functions
static void setLangDefaults (LangOptions &Opts, Language Lang, const llvm::Triple &T, std::vector< std::string > &Includes, LangStandard::Kind LangStd=LangStandard::lang_unspecified)
Set language defaults for the given input language and language standard in the given LangOptions object.
Public Attributes
LangStandard::Kind LangStd
The used language standard.
SanitizerSet Sanitize
Set of enabled sanitizers.
bool SanitizeCoverage = false
Is at least one coverage instrumentation type enabled.
std::vector< std::string > NoSanitizeFiles
Paths to files specifying which objects (files, functions, variables) should not be instrumented.
std::vector< std::string > XRayAlwaysInstrumentFiles
Paths to the XRay "always instrument" files specifying which objects (files, functions, variables) should be imbued with the XRay "always instrument" attribute.
std::vector< std::string > XRayNeverInstrumentFiles
Paths to the XRay "never instrument" files specifying which objects (files, functions, variables) should be imbued with the XRay "never instrument" attribute.
std::vector< std::string > XRayAttrListFiles
Paths to the XRay attribute list files, specifying which objects (files, functions, variables) should be imbued with the appropriate XRay attribute(s).
std::vector< std::string > ProfileListFiles
Paths to special case list files specifying which entities (files, functions) should or should not be instrumented.
clang::ObjCRuntime ObjCRuntime
CoreFoundationABI CFRuntime = CoreFoundationABI::Unspecified
std::string ObjCConstantStringClass
std::string OverflowHandler
The name of the handler function to be called when -ftrapv is specified.
std::string ModuleName
The module currently being compiled as specified by -fmodule-name.
std::string CurrentModule
The name of the current module, of which the main source file is a part.
std::vector< std::string > ModuleFeatures
The names of any features to enable in module 'requires' decls in addition to the hard-coded list in Module.cpp and the target features.
CommentOptions CommentOpts
Options for parsing comments.
std::vector< std::string > NoBuiltinFuncs
A list of all -fno-builtin-* function names (e.g., memset).
std::map< std::string, std::string, std::greater< std::string > > MacroPrefixMap
A prefix map for FILE, BASE_FILE and __builtin_FILE().
std::vector< llvm::Triple > OMPTargetTriples
Triples of the OpenMP targets that the host code codegen should take into account in order to generate accurate offloading descriptors.
std::string OMPHostIRFile
Name of the IR file that contains the result of the OpenMP target host code generation.
std::string CUID
The user provided compilation unit ID, if non-empty.
std::optional< TargetCXXABI::Kind > CXXABI
C++ ABI to compile with, if specified by the frontend through -fc++-abi=.
bool IsHeaderFile = false
Indicates whether the front-end is explicitly told that the input is a header file (i.e.
GPUDefaultStreamKind GPUDefaultStream
The default stream kind used for HIP kernel launching.
std::string RandstructSeed
The seed used by the randomize structure layout feature.
bool UseTargetPathSeparator = false
Indicates whether to use target's platform-specific file separator when FILE macro is used and when concatenating filename with directory or to use build environment environment's platform-specific file separator.
bool CheckNew = false
Detailed Description
Keeps track of the various options that can be enabled, which controls the dialect of C or C++ that is accepted.
Definition at line 82 of file LangOptions.h.
Member Typedef Documentation
MSVtorDispMode
using clang::LangOptions::MSVtorDispMode = clang::MSVtorDispMode
Definition at line 128 of file LangOptions.h.
RoundingMode
using clang::LangOptions::RoundingMode = llvm::RoundingMode
Definition at line 85 of file LangOptions.h.
Visibility
using clang::LangOptions::Visibility = clang::Visibility
Definition at line 84 of file LangOptions.h.
Member Enumeration Documentation
AddrSpaceMapMangling
enum clang::LangOptions::AddrSpaceMapMangling
Enumerator
ASMM_Target
ASMM_On
ASMM_Off
Definition at line 139 of file LangOptions.h.
AltivecSrcCompatKind
enum class clang::LangOptions::AltivecSrcCompatKind strong
Enumerator
Mixed
GCC
XL
Default
Definition at line 315 of file LangOptions.h.
ClangABI
enum class clang::LangOptions::ClangABI strong
Clang versions with different platform ABI conformance.
Enumerator
Ver3_8
Attempt to be ABI-compatible with code generated by Clang 3.8.x (SVN r257626).
This causes <1 x long long> to be passed in an integer register instead of an SSE register on x64_64.
Ver4
Attempt to be ABI-compatible with code generated by Clang 4.0.x (SVN r291814).
This causes move operations to be ignored when determining whether a class type can be passed or returned directly.
Ver6
Attempt to be ABI-compatible with code generated by Clang 6.0.x (SVN r321711).
This causes determination of whether a type is standard-layout to ignore collisions between empty base classes and between base classes and member subobjects, which affects whether we reuse base class tail padding in some ABIs.
Ver7
Attempt to be ABI-compatible with code generated by Clang 7.0.x (SVN r338536).
This causes alignof (C++) and _Alignof (C11) to be compatible with __alignof (i.e., return the preferred alignment) rather than returning the required alignment.
Ver9
Attempt to be ABI-compatible with code generated by Clang 9.0.x (SVN r351319).
This causes vectors of __int128 to be passed in memory instead of passing in multiple scalar registers on x86_64 on Linux and NetBSD.
Ver11
Attempt to be ABI-compatible with code generated by Clang 11.0.x (git 2e10b7a39b93).
This causes clang to pass unions with a 256-bit vector member on the stack instead of using registers, to not properly mangle substitutions for template names in some cases, and to mangle declaration template arguments without a cast to the parameter type even when that can lead to mangling collisions.
Ver12
Attempt to be ABI-compatible with code generated by Clang 12.0.x (git 8e464dd76bef).
This causes clang to mangle lambdas within global-scope inline variables incorrectly.
Ver14
Attempt to be ABI-compatible with code generated by Clang 14.0.x.
This causes clang to:
mangle dependent nested names incorrectly.
make trivial only those defaulted copy constructors with a parameter-type-list equivalent to the parameter-type-list of an implicit declaration.
Ver15
Attempt to be ABI-compatible with code generated by Clang 15.0.x.
This causes clang to:
Reverse the implementation for DR692, DR1395 and DR1432.
pack non-POD members of packed structs.
consider classes with defaulted special member functions non-pod.
Latest
Conform to the underlying platform's C and C++ ABIs as closely as we can.
Definition at line 175 of file LangOptions.h.
CompilingModuleKind
enum clang::LangOptions::CompilingModuleKind
Enumerator
CMK_None
Not compiling a module interface at all.
CMK_ModuleMap
Compiling a module from a module map.
CMK_HeaderUnit
Compiling a module header unit.
CMK_ModuleInterface
Compiling a C++ modules interface unit.
Definition at line 107 of file LangOptions.h.
CoreFoundationABI
enum class clang::LangOptions::CoreFoundationABI strong
Enumerator
Unspecified
No interoperability ABI has been specified.
Standalone
CoreFoundation does not have any language interoperability.
ObjectiveC
Interoperability with the ObjectiveC runtime.
Swift
Interoperability with the latest known version of the Swift runtime.
Swift5_0
Interoperability with the Swift 5.0 runtime.
Swift4_2
Interoperability with the Swift 4.2 runtime.
Swift4_1
Interoperability with the Swift 4.1 runtime.
Definition at line 238 of file LangOptions.h.
DefaultCallingConvention
enum clang::LangOptions::DefaultCallingConvention
Enumerator
DCC_None
DCC_CDecl
DCC_FastCall
DCC_StdCall
DCC_VectorCall
DCC_RegCall
Definition at line 130 of file LangOptions.h.
DefaultVisiblityExportMapping
enum class clang::LangOptions::DefaultVisiblityExportMapping strong
Enumerator
None
Explicit
map only explicit default visibilities to exported
All
map all default visibilities to exported
Definition at line 364 of file LangOptions.h.
ExceptionHandlingKind
enum class clang::LangOptions::ExceptionHandlingKind strong
Possible exception handling behavior.
Enumerator
None
SjLj
WinEH
DwarfCFI
Wasm
Definition at line 302 of file LangOptions.h.
ExcessPrecisionKind
enum clang::LangOptions::ExcessPrecisionKind
Enumerator
FPP_Standard
FPP_Fast
FPP_None
Definition at line 299 of file LangOptions.h.
ExtendArgsKind
enum class clang::LangOptions::ExtendArgsKind strong
Enumerator
ExtendTo32
Integer arguments are sign or zero extended to 32/64 bits during default argument promotions.
ExtendTo64
Definition at line 350 of file LangOptions.h.
FPEvalMethodKind
enum clang::LangOptions::FPEvalMethodKind
Possible float expression evaluation method choices.
Enumerator
FEM_Indeterminable
The evaluation method cannot be determined or is inconsistent for this target.
FEM_Source
Use the declared type for fp arithmetic.
FEM_Double
Use the type double for fp arithmetic.
FEM_Extended
Use extended type for fp arithmetic.
FEM_UnsetOnCommandLine
Used only for FE option processing; this is only used to indicate that the user did not specify an explicit evaluation method on the command line and so the target should be queried for its default evaluation method instead.
Definition at line 282 of file LangOptions.h.
FPExceptionModeKind
enum clang::LangOptions::FPExceptionModeKind
Possible floating point exception behavior.
Enumerator
FPE_Ignore
Assume that floating-point exceptions are masked.
FPE_MayTrap
Transformations do not cause new exceptions but may hide some.
FPE_Strict
Strictly preserve the floating-point exception semantics.
FPE_Default
Used internally to represent initial unspecified value.
Definition at line 270 of file LangOptions.h.
FPModeKind
enum clang::LangOptions::FPModeKind
Enumerator
FPM_Off
FPM_On
FPM_Fast
FPM_FastHonorPragmas
Definition at line 255 of file LangOptions.h.
GCMode
enum clang::LangOptions::GCMode
Enumerator
NonGC
GCOnly
HybridGC
Definition at line 87 of file LangOptions.h.
GPUDefaultStreamKind
enum class clang::LangOptions::GPUDefaultStreamKind strong
Enumerator
Legacy
Legacy default stream.
PerThread
Per-thread default stream.
Definition at line 357 of file LangOptions.h.
HLSLLangStd
enum clang::LangOptions::HLSLLangStd
Enumerator
HLSL_Unset
HLSL_2015
HLSL_2016
HLSL_2017
HLSL_2018
HLSL_2021
HLSL_202x
Definition at line 164 of file LangOptions.h.
LaxVectorConversionKind
enum class clang::LangOptions::LaxVectorConversionKind strong
Enumerator
None
Permit no implicit vector bitcasts.
Integer
Permit vector bitcasts between integer vectors with different numbers of elements but the same total bit-width.
All
Permit vector bitcasts between all vectors with the same total bit-width.
Definition at line 304 of file LangOptions.h.
MSVCMajorVersion
enum clang::LangOptions::MSVCMajorVersion
Enumerator
MSVC2010
MSVC2012
MSVC2013
MSVC2015
MSVC2017
MSVC2017_5
MSVC2017_7
MSVC2019
MSVC2019_5
MSVC2019_8
Definition at line 142 of file LangOptions.h.
PragmaMSPointersToMembersKind
enum clang::LangOptions::PragmaMSPointersToMembersKind
Enumerator
PPTMK_BestCase
PPTMK_FullGeneralitySingleInheritance
PPTMK_FullGeneralityMultipleInheritance
PPTMK_FullGeneralityVirtualInheritance
Definition at line 121 of file LangOptions.h.
SignedOverflowBehaviorTy
enum clang::LangOptions::SignedOverflowBehaviorTy
Enumerator
SOB_Undefined
SOB_Defined
SOB_Trapping
Definition at line 95 of file LangOptions.h.
SignReturnAddressKeyKind
enum class clang::LangOptions::SignReturnAddressKeyKind strong
Enumerator
AKey
Return address signing uses APIA key.
BKey
Return address signing uses APIB key.
Definition at line 336 of file LangOptions.h.
SignReturnAddressScopeKind
enum class clang::LangOptions::SignReturnAddressScopeKind strong
Enumerator
None
No signing for any function.
NonLeaf
Sign the return address of functions that spill LR.
All
Sign the return address of all functions,.
Definition at line 327 of file LangOptions.h.
StackProtectorMode
enum clang::LangOptions::StackProtectorMode
Enumerator
SSPOff
SSPOn
SSPStrong
SSPReq
Definition at line 88 of file LangOptions.h.
StrictFlexArraysLevelKind
enum class clang::LangOptions::StrictFlexArraysLevelKind strong
Enumerator
Default
Any trailing array member is a FAM.
OneZeroOrIncomplete
Any trailing array member of undefined, 0, or 1 size is a FAM.
ZeroOrIncomplete
Any trailing array member of undefined or 0 size is a FAM.
IncompleteOnly
Any trailing array member of undefined size is a FAM.
Definition at line 372 of file LangOptions.h.
SYCLMajorVersion
enum clang::LangOptions::SYCLMajorVersion
Enumerator
SYCL_None
SYCL_2017
SYCL_2020
SYCL_Default
Definition at line 155 of file LangOptions.h.
ThreadModelKind
enum class clang::LangOptions::ThreadModelKind strong
Enumerator
POSIX
POSIX Threads.
Single
Single Threaded Environment.
Definition at line 343 of file LangOptions.h.
TrivialAutoVarInitKind
enum class clang::LangOptions::TrivialAutoVarInitKind strong
Enumerator
Uninitialized
Zero
Pattern
Definition at line 93 of file LangOptions.h.
Constructor & Destructor Documentation
LangOptions()
LangOptions::LangOptions ()
Definition at line 19 of file LangOptions.cpp.
Member Function Documentation
allowsNonTrivialObjCLifetimeQualifiers()
bool clang::LangOptions::allowsNonTrivialObjCLifetimeQualifiers () const inline
True if any ObjC types may have non-trivial lifetime qualifiers.
Definition at line 559 of file LangOptions.h.
assumeFunctionsAreConvergent()
bool clang::LangOptions::assumeFunctionsAreConvergent () const inline
Definition at line 563 of file LangOptions.h.
Referenced by getTrivialDefaultFunctionAttributes(), and UpdateAsmCallInst().
getDefaultExceptionMode()
FPExceptionModeKind clang::LangOptions::getDefaultExceptionMode () const inline
Definition at line 651 of file LangOptions.h.
References FPE_Default, and FPE_Ignore.
Referenced by clang::Sema::AddKnownFunctionAttributes(), clang::targets::addVisualCDefines(), and getTrivialDefaultFunctionAttributes().
getDefaultRoundingMode()
RoundingMode clang::LangOptions::getDefaultRoundingMode () const inline
Definition at line 646 of file LangOptions.h.
Referenced by clang::targets::addVisualCDefines().
getOpenCLCompatibleVersion()
unsigned LangOptions::getOpenCLCompatibleVersion () const
Return the OpenCL version that kernel language is compatible with.
Definition at line 63 of file LangOptions.cpp.
Referenced by clang::Sema::ActOnNumericConstant(), clang::TargetInfo::adjust(), clang::OpenCLOptions::areProgramScopeVariablesSupported(), builtinIsSupported(), CheckExtVectorComponent(), ConvertDeclSpecToType(), clang::Sema::CreateBuiltinUnaryOp(), FixupInvocation(), GetFullTypeForDeclarator(), getOpenCLKernelParameterType(), handleOpenCLNoSVMAttr(), clang::Sema::Initialize(), clang::OpenCLOptions::OpenCLOptionInfo::isAvailableIn(), clang::CodeGen::CodeGenModule::Release(), setLangDefaults(), clang::DeclSpec::SetStorageClassSpec(), and clang::TargetInfo::validateOpenCLTarget().
getOpenCLVersionString()
std::string LangOptions::getOpenCLVersionString () const
Return the OpenCL C or C++ for OpenCL language name and version as a string.
Definition at line 79 of file LangOptions.cpp.
References getOpenCLVersionTuple(), and clang::Result.
Referenced by clang::Sema::ActOnVariableDeclarator(), FixupInvocation(), and handleOpenCLNoSVMAttr().
getOpenCLVersionTuple()
VersionTuple LangOptions::getOpenCLVersionTuple () const
Return the OpenCL C or C++ version as a VersionTuple.
Definition at line 56 of file LangOptions.cpp.
Referenced by getOpenCLVersionString(), and clang::TargetInfo::validateOpenCLTarget().
hasDefaultVisibilityExportMapping()
bool clang::LangOptions::hasDefaultVisibilityExportMapping () const inline
Definition at line 628 of file LangOptions.h.
References None.
Referenced by clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
hasDWARFExceptions()
bool clang::LangOptions::hasDWARFExceptions () const inline
Definition at line 618 of file LangOptions.h.
References DwarfCFI.
Referenced by getCPersonality(), getCXXPersonality(), InitializePredefinedMacros(), and initTargetOptions().
hasSEHExceptions()
bool clang::LangOptions::hasSEHExceptions () const inline
Definition at line 614 of file LangOptions.h.
References WinEH.
Referenced by getCPersonality(), getCXXPersonality(), getObjCPersonality(), InitializePredefinedMacros(), and initTargetOptions().
hasSignReturnAddress()
bool clang::LangOptions::hasSignReturnAddress () const inline
Check if return address signing is enabled.
Definition at line 596 of file LangOptions.h.
References None.
Referenced by clang::targets::AArch64TargetInfo::getTargetDefines(), clang::targets::ARMTargetInfo::getTargetDefines(), and clang::CodeGen::CodeGenModule::Release().
hasSjLjExceptions()
bool clang::LangOptions::hasSjLjExceptions () const inline
Definition at line 610 of file LangOptions.h.
References SjLj.
Referenced by getCPersonality(), getCXXPersonality(), getObjCPersonality(), InitializePredefinedMacros(), and initTargetOptions().
hasWasmExceptions()
bool clang::LangOptions::hasWasmExceptions () const inline
Definition at line 622 of file LangOptions.h.
References Wasm.
Referenced by getCXXPersonality(), and initTargetOptions().
implicitFunctionsAllowed()
bool clang::LangOptions::implicitFunctionsAllowed () const inline
Returns true if implicit function declarations are allowed in the current language mode.
Definition at line 585 of file LangOptions.h.
References clang::OpenCL, and requiresStrictPrototypes().
Referenced by clang::Sema::ImplicitlyDefineFunction().
isAllDefaultVisibilityExportMapping()
bool clang::LangOptions::isAllDefaultVisibilityExportMapping () const inline
Definition at line 638 of file LangOptions.h.
References All.
Referenced by clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
isCompatibleWithMSVC()
bool clang::LangOptions::isCompatibleWithMSVC (MSVCMajorVersion MajorVersion) const inline
Definition at line 546 of file LangOptions.h.
Referenced by clang::targets::addVisualCDefines(), CompareStandardConversionSequences(), clang::TextDiagnostic::emitDiagnosticLoc(), getKeywordStatus(), getMSManglingNumber(), and NarrowingErrs().
isCompilingModule()
bool clang::LangOptions::isCompilingModule () const inline
Are we compiling a module?
Definition at line 518 of file LangOptions.h.
References CMK_None.
Referenced by clang::ModuleMap::addHeader(), clang::ModuleMap::diagnoseHeaderInclusion(), clang::PCHGenerator::HandleTranslationUnit(), isCompilingModuleImplementation(), clang::ASTUnit::isModuleFile(), and trackLocalOwningModule().
isCompilingModuleImplementation()
bool clang::LangOptions::isCompilingModuleImplementation () const inline
Are we compiling a module implementation?
Definition at line 528 of file LangOptions.h.
References isCompilingModule(), and ModuleName.
isCompilingModuleInterface()
bool clang::LangOptions::isCompilingModuleInterface () const inline
Are we compiling a standard c++ module interface?
Definition at line 523 of file LangOptions.h.
References CMK_ModuleInterface.
isExplicitDefaultVisibilityExportMapping()
bool clang::LangOptions::isExplicitDefaultVisibilityExportMapping () const inline
Definition at line 633 of file LangOptions.h.
References Explicit.
Referenced by clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
isImplicitIntAllowed()
bool clang::LangOptions::isImplicitIntAllowed () const inline
Returns true if implicit int is supported at all.
Definition at line 593 of file LangOptions.h.
References clang::C2x, and clang::CPlusPlus.
Referenced by ConvertDeclSpecToType().
isImplicitIntRequired()
bool clang::LangOptions::isImplicitIntRequired () const inline
Returns true if implicit int is part of the language requirements.
Definition at line 590 of file LangOptions.h.
References clang::C99, and clang::CPlusPlus.
Referenced by ConvertDeclSpecToType().
isNoBuiltinFunc()
bool LangOptions::isNoBuiltinFunc (StringRef Name) const
Is this a libc/libm function that is no longer recognized as a builtin because a -fno-builtin-* option has been specified?
Definition at line 49 of file LangOptions.cpp.
References NoBuiltinFuncs.
Referenced by getTrivialDefaultFunctionAttributes().
isSignedOverflowDefined()
bool clang::LangOptions::isSignedOverflowDefined () const inline
Definition at line 537 of file LangOptions.h.
References SOB_Defined.
Referenced by DiagnoseBadShiftValues(), and emitPointerArithmetic().
isSignReturnAddressScopeAll()
bool clang::LangOptions::isSignReturnAddressScopeAll () const inline
Check if leaf functions are also signed.
Definition at line 606 of file LangOptions.h.
References All.
Referenced by clang::targets::AArch64TargetInfo::getTargetDefines(), clang::targets::ARMTargetInfo::getTargetDefines(), and clang::CodeGen::CodeGenModule::Release().
isSignReturnAddressWithAKey()
bool clang::LangOptions::isSignReturnAddressWithAKey () const inline
Check if return address signing uses AKey.
Definition at line 601 of file LangOptions.h.
References AKey.
Referenced by clang::targets::AArch64TargetInfo::getTargetDefines(), and clang::CodeGen::CodeGenModule::Release().
isSubscriptPointerArithmetic()
bool clang::LangOptions::isSubscriptPointerArithmetic () const inline
Definition at line 541 of file LangOptions.h.
References clang::ObjCRuntime::isSubscriptPointerArithmetic().
Referenced by clang::Sema::BuildObjCSubscriptExpression(), and clang::Sema::CreateBuiltinArraySubscriptExpr().
isSYCL()
bool clang::LangOptions::isSYCL () const inline
Definition at line 626 of file LangOptions.h.
Referenced by getKeywordStatusHelper().
remapPathPrefix()
void LangOptions::remapPathPrefix (SmallVectorImpl< char > & Path) const
Remap path prefix according to -fmacro-prefix-path option.
Definition at line 73 of file LangOptions.cpp.
References MacroPrefixMap.
Referenced by clang::PredefinedExpr::ComputeName(), and clang::Preprocessor::processPathForFileMacro().
requiresStrictPrototypes()
bool clang::LangOptions::requiresStrictPrototypes () const inline
Returns true if functions without prototypes or functions with an identifier list (aka K&R C functions) are not allowed.
Definition at line 579 of file LangOptions.h.
References clang::C2x, and clang::CPlusPlus.
Referenced by CreateNewFunctionDecl(), GetFullTypeForDeclarator(), and implicitFunctionsAllowed().
resetNonModularOptions()
void LangOptions::resetNonModularOptions ()
Reset all of the options that are not considered when building a module.
Definition at line 25 of file LangOptions.cpp.
References CurrentModule, IsHeaderFile, NoSanitizeFiles, XRayAlwaysInstrumentFiles, and XRayNeverInstrumentFiles.
Referenced by clang::CompilerInvocation::resetNonModularOptions().
setLangDefaults()
void LangOptions::setLangDefaults (LangOptions & Opts, Language Lang, const llvm::Triple & T, std::vector< std::string > & Includes, LangStandard::Kind LangStd = LangStandard::lang_unspecified) static
Set language defaults for the given input language and language standard in the given LangOptions object.
Parameters
Opts - The LangOptions object to set up.
Lang - The input language.
T - The target triple.
Includes - If the language requires extra headers to be implicitly included, they will be appended to this list.
LangStd - The input language standard.
Definition at line 89 of file LangOptions.cpp.
References clang::Asm, clang::CUDA, FPM_Fast, FPM_FastHonorPragmas, FPM_On, clang::getDefaultLanguageStandard(), clang::LangStandard::getLangStandardForKind(), getOpenCLCompatibleVersion(), clang::HIP, clang::HLSL, HLSL_2015, HLSL_2016, HLSL_2017, HLSL_2018, HLSL_2021, HLSL_202x, clang::LangStandard::lang_unspecified, LangStd, clang::ObjC, clang::ObjCXX, clang::RenderScript, and Std.
trackLocalOwningModule()
bool clang::LangOptions::trackLocalOwningModule () const inline
Do we need to track the owning module for a local declaration?
Definition at line 533 of file LangOptions.h.
References isCompilingModule().
Referenced by clang::Decl::hasLocalOwningModuleStorage().
Member Data Documentation
CFRuntime
CoreFoundationABI clang::LangOptions::CFRuntime = CoreFoundationABI::Unspecified
Definition at line 419 of file LangOptions.h.
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), and clang::ASTContext::getCFConstantStringDecl().
CheckNew
bool clang::LangOptions::CheckNew = false
Definition at line 492 of file LangOptions.h.
CommentOpts
CommentOptions clang::LangOptions::CommentOpts
Options for parsing comments.
Definition at line 446 of file LangOptions.h.
Referenced by clang::Sema::ActOnComment(), clang::ASTContext::addComment(), clang::ASTContext::cacheRawCommentForDecl(), checkLanguageOptions(), and clang::ASTContext::getRawCommentForDeclNoCacheImpl().
CUID
std::string clang::LangOptions::CUID
The user provided compilation unit ID, if non-empty.
This is used to externalize static variables which is needed to support accessing static device variables in host code for single source offloading languages like CUDA/HIP.
Definition at line 466 of file LangOptions.h.
Referenced by clang::ASTContext::getCUIDHash(), and clang::CodeGen::CodeGenModule::printPostfixForExternalizedDecl().
CurrentModule
std::string clang::LangOptions::CurrentModule
The name of the current module, of which the main source file is a part.
If CompilingModule is set, we are compiling the interface of this module, otherwise we are compiling an implementation file of it. This starts as ModuleName in case -fmodule-name is provided and changes during compilation to reflect the current module.
Definition at line 437 of file LangOptions.h.
Referenced by clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnModuleImport(), clang::FrontendAction::BeginSourceFile(), clang::ModuleMap::createHeaderUnit(), clang::ModuleMap::createModuleForImplementationUnit(), clang::ModuleMap::createModuleForInterfaceUnit(), clang::DumpModuleInfoAction::ExecuteAction(), clang::ModuleMap::findOrCreateModule(), FixupInvocation(), clang::FrontendAction::getCurrentModule(), clang::Preprocessor::getModuleForLocation(), clang::PCHGenerator::HandleTranslationUnit(), clang::Module::isForBuilding(), prepareToBuildModule(), and resetNonModularOptions().
CXXABI
std::optional<TargetCXXABI::Kind> clang::LangOptions::CXXABI
C++ ABI to compile with, if specified by the frontend through -fc++-abi=.
This overrides the default ABI used by the target.
Definition at line 470 of file LangOptions.h.
Referenced by clang::ASTContext::getCXXABIKind().
GPUDefaultStream
GPUDefaultStreamKind clang::LangOptions::GPUDefaultStream
The default stream kind used for HIP kernel launching.
Definition at line 477 of file LangOptions.h.
Referenced by InitializeStandardPredefinedMacros().
IsHeaderFile
bool clang::LangOptions::IsHeaderFile = false
Indicates whether the front-end is explicitly told that the input is a header file (i.e.
-x c-header).
Definition at line 474 of file LangOptions.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), isMainFileLoc(), and resetNonModularOptions().
LangStd
LangStandard::Kind clang::LangOptions::LangStd
The used language standard.
Definition at line 385 of file LangOptions.h.
Referenced by setLangDefaults().
MacroPrefixMap
std::map<std::string, std::string, std::greater<std::string> > clang::LangOptions::MacroPrefixMap
A prefix map for FILE, BASE_FILE and __builtin_FILE().
Definition at line 452 of file LangOptions.h.
Referenced by clang::CodeGen::CodeGenModule::CodeGenModule(), and remapPathPrefix().
ModuleFeatures
std::vector<std::string> clang::LangOptions::ModuleFeatures
The names of any features to enable in module 'requires' decls in addition to the hard-coded list in Module.cpp and the target features.
This list is sorted.
Definition at line 443 of file LangOptions.h.
Referenced by checkLanguageOptions(), and hasFeature().
ModuleName
std::string clang::LangOptions::ModuleName
The module currently being compiled as specified by -fmodule-name.
Definition at line 430 of file LangOptions.h.
Referenced by clang::FrontendAction::BeginSourceFile(), FixupInvocation(), isCompilingModuleImplementation(), clang::Module::isForBuilding(), and loadModuleMapForModuleBuild().
NoBuiltinFuncs
std::vector<std::string> clang::LangOptions::NoBuiltinFuncs
A list of all -fno-builtin-* function names (e.g., memset).
Definition at line 449 of file LangOptions.h.
Referenced by addNoBuiltinAttributes(), clang::Builtin::Context::initializeBuiltins(), and isNoBuiltinFunc().
NoSanitizeFiles
std::vector<std::string> clang::LangOptions::NoSanitizeFiles
Paths to files specifying which objects (files, functions, variables) should not be instrumented.
Definition at line 394 of file LangOptions.h.
Referenced by addSanitizers(), and resetNonModularOptions().
ObjCConstantStringClass
std::string clang::LangOptions::ObjCConstantStringClass
Definition at line 421 of file LangOptions.h.
ObjCRuntime
clang::ObjCRuntime clang::LangOptions::ObjCRuntime
Definition at line 417 of file LangOptions.h.
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnDefs(), clang::Sema::ActOnIvar(), clang::Sema::ActOnLastBitfield(), checkArithmeticOnObjCPointer(), clang::Sema::CheckImplementationIvars(), checkLanguageOptions(), CheckObjCTraitOperandConstraints(), CheckProtocolMethodDefs(), clang::CodeGen::CreateGNUObjCRuntime(), clang::Sema::DefaultSynthesizeProperties(), DiagnoseUnimplementedAccessor(), EncodeBitField(), clang::CodeGen::CodeGenModule::GetAddrOfRTTIDescriptor(), clang::ASTNameGenerator::Implementation::getClassSymbolPrefix(), getObjCPersonality(), getObjCXXPersonality(), handleObjCDirectAttr(), handleObjCDirectMembersAttr(), hasUnwindExceptions(), clang::Sema::ImplMethodsVsClassMethods(), InitializePredefinedMacros(), clang::Sema::MaybeBindToTemporary(), setARCRuntimeFunctionLinkage(), tryEmitSpecializedAllocInit(), and UseOptimizedSetter().
OMPHostIRFile
std::string clang::LangOptions::OMPHostIRFile
Name of the IR file that contains the result of the OpenMP target host code generation.
Definition at line 460 of file LangOptions.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::CGOpenMPRuntime(), and clang::CodeGen::CGOpenMPRuntimeGPU::CGOpenMPRuntimeGPU().
OMPTargetTriples
std::vector<llvm::Triple> clang::LangOptions::OMPTargetTriples
Triples of the OpenMP targets that the host code codegen should take into account in order to generate accurate offloading descriptors.
Definition at line 456 of file LangOptions.h.
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::Sema::AddInitializerToDecl(), emitCommonOMPTargetDirective(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), clang::CodeGen::CGOpenMPRuntime::emitRequiresDirectiveRegFun(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), and clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable().
OverflowHandler
std::string clang::LangOptions::OverflowHandler
The name of the handler function to be called when -ftrapv is specified.
If none is specified, abort (GCC-compatible behaviour).
Definition at line 427 of file LangOptions.h.
ProfileListFiles
std::vector<std::string> clang::LangOptions::ProfileListFiles
Paths to special case list files specifying which entities (files, functions) should or should not be instrumented.
Definition at line 415 of file LangOptions.h.
RandstructSeed
std::string clang::LangOptions::RandstructSeed
The seed used by the randomize structure layout feature.
Definition at line 480 of file LangOptions.h.
Referenced by clang::randstruct::randomizeStructureLayout().
Sanitize
SanitizerSet clang::LangOptions::Sanitize
Set of enabled sanitizers.
Definition at line 388 of file LangOptions.h.
Referenced by addKCFIPass(), addSanitizers(), checkLanguageOptions(), clang::CodeGen::CodeGenModule::CodeGenModule(), clang::CodeGen::CodeGenModule::CreateFunctionTypeMetadataForIcall(), clang::targets::getDarwinDefines(), clang::RecordDecl::mayInsertExtraPadding(), clang::CodeGen::CodeGenModule::NeedAllVtablesTypeId(), clang::CodeGen::CodeGenModule::Release(), clang::CodeGen::CodeGenVTables::RemoveHwasanMetadata(), clang::CodeGen::SanitizerMetadata::reportGlobal(), clang::CodeGen::SanitizerMetadata::reportGlobal(), and shouldEmitLifetimeMarkers().
SanitizeCoverage
bool clang::LangOptions::SanitizeCoverage = false
Is at least one coverage instrumentation type enabled.
Definition at line 390 of file LangOptions.h.
Referenced by FixupInvocation().
UseTargetPathSeparator
bool clang::LangOptions::UseTargetPathSeparator = false
Indicates whether to use target's platform-specific file separator when FILE macro is used and when concatenating filename with directory or to use build environment environment's platform-specific file separator.
The plaform-specific path separator is the backslash() for Windows and forward slash (/) elsewhere.
Definition at line 488 of file LangOptions.h.
Referenced by clang::Preprocessor::processPathForFileMacro().
XRayAlwaysInstrumentFiles
std::vector<std::string> clang::LangOptions::XRayAlwaysInstrumentFiles
Paths to the XRay "always instrument" files specifying which objects (files, functions, variables) should be imbued with the XRay "always instrument" attribute.
WARNING: This is a deprecated field and will go away in the future.
Definition at line 400 of file LangOptions.h.
Referenced by resetNonModularOptions().
XRayAttrListFiles
std::vector<std::string> clang::LangOptions::XRayAttrListFiles
Paths to the XRay attribute list files, specifying which objects (files, functions, variables) should be imbued with the appropriate XRay attribute(s).
Definition at line 411 of file LangOptions.h.
XRayNeverInstrumentFiles
std::vector<std::string> clang::LangOptions::XRayNeverInstrumentFiles
Paths to the XRay "never instrument" files specifying which objects (files, functions, variables) should be imbued with the XRay "never instrument" attribute.
WARNING: This is a deprecated field and will go away in the future.
Definition at line 406 of file LangOptions.h.
Referenced by resetNonModularOptions().
The documentation for this class was generated from the following files:
include/clang/Basic/LangOptions.h
lib/Basic/LangOptions.cpp