clang: clang::format::IntegerLiteralSeparatorFixer Class Reference
clang::format::IntegerLiteralSeparatorFixer Class Reference
#include "/root/llvm-project/clang/lib/Format/IntegerLiteralSeparatorFixer.h"
Public Member Functions
std::pair< tooling::Replacements, unsigned > process (const Environment &Env, const FormatStyle &Style)
Detailed Description
Definition at line 23 of file IntegerLiteralSeparatorFixer.h.
Member Function Documentation
process()
std::pair< tooling::Replacements, unsigned > clang::format::IntegerLiteralSeparatorFixer::process (const Environment & Env, const FormatStyle & Style)
Definition at line 45 of file IntegerLiteralSeparatorFixer.cpp.
References clang::format::AffectedRangeManager::affectsCharSourceRange(), clang::format::Binary, clang::format::Decimal, Env, clang::format::getBase(), clang::CharSourceRange::getCharRange(), clang::format::getFormattingLangOpts(), clang::format::Hex, clang::format::isClangFormatOff(), clang::format::isClangFormatOn(), clang::Lexer::LexFromRawLexer(), clang::format::Other, clang::Result, clang::Lexer::SetCommentRetentionState(), Suffixes, Text, and Tok.
Referenced by clang::format::internal::reformat().
The documentation for this class was generated from the following files:
lib/Format/IntegerLiteralSeparatorFixer.h
lib/Format/IntegerLiteralSeparatorFixer.cpp