clang: clang::ASTContext Class Reference
clang::ASTContext Class Reference
Holds long-lived AST nodes (such as types and decls) that can be referred to throughout the semantic analysis of a file.
#include "clang/AST/ASTContext.h"
Classes
struct BuiltinVectorTypeInfo
struct CUDAConstantEvalContext
struct CUDAConstantEvalContextRAII
struct SectionInfo
Public Types
enum GetBuiltinTypeError {
GE_None , GE_Missing_type , GE_Missing_stdio , GE_Missing_setjmp ,
GE_Missing_ucontext
}
enum NeedExtraManglingDecl_t { NeedExtraManglingDecl }
enum class InlineVariableDefinitionKind { None , Weak , WeakUnknown , Strong }
enum PragmaSectionFlag : unsigned {
PSF_None = 0 , PSF_Read = 0x1 , PSF_Write = 0x2 , PSF_Execute = 0x4 ,
PSF_Implicit = 0x8 , PSF_ZeroInit = 0x10 , PSF_Invalid = 0x80000000U
}
using TemplateOrSpecializationInfo
A type synonym for the TemplateOrInstantiation mapping.
using overridden_cxx_method_iterator = CXXMethodVector::const_iterator
using overridden_method_range
using import_range = llvm::iterator_range<import_iterator>
Public Member Functions
interp::Context & getInterpContext ()
Returns the clang bytecode interpreter context.
ParentMapContext & getParentMapContext ()
Returns the dynamic AST node parent map context.
std::vector< Decl * > getTraversalScope () const
void setTraversalScope (const std::vector< Decl * > &)
template<typename NodeT >
DynTypedNodeList getParents (const NodeT &Node)
Forwards to get node parents from the ParentMapContext.
const clang::PrintingPolicy & getPrintingPolicy () const
void setPrintingPolicy (const clang::PrintingPolicy &Policy)
SourceManager & getSourceManager ()
const SourceManager & getSourceManager () const
void cleanup ()
llvm::BumpPtrAllocator & getAllocator () const
void * Allocate (size_t Size, unsigned Align=8) const
template<typename T >
T * Allocate (size_t Num=1) const
void Deallocate (void *Ptr) const
DeclListNode * AllocateDeclListNode (clang::NamedDecl *ND)
Allocates a DeclListNode or returns one from the ListNodeFreeList pool.
void DeallocateDeclListNode (DeclListNode *N)
Deallcates a DeclListNode by returning it to the ListNodeFreeList pool.
size_t getASTAllocatedMemory () const
Return the total amount of physical memory allocated for representing AST nodes and type information.
size_t getSideTableAllocatedMemory () const
Return the total memory used for various side tables.
PartialDiagnostic::DiagStorageAllocator & getDiagAllocator ()
const TargetInfo & getTargetInfo () const
const TargetInfo * getAuxTargetInfo () const
QualType getIntTypeForBitwidth (unsigned DestWidth, unsigned Signed) const
getIntTypeForBitwidth - sets integer QualTy according to specified details: bitwidth, signed/unsigned.
QualType getRealTypeForBitwidth (unsigned DestWidth, FloatModeKind ExplicitType) const
getRealTypeForBitwidth - sets floating point QualTy according to specified bitwidth.
bool AtomicUsesUnsupportedLibcall (const AtomicExpr *E) const
const LangOptions & getLangOpts () const
bool isDependenceAllowed () const
const NoSanitizeList & getNoSanitizeList () const
const XRayFunctionFilter & getXRayFilter () const
const ProfileList & getProfileList () const
DiagnosticsEngine & getDiagnostics () const
FullSourceLoc getFullLoc (SourceLocation Loc) const
TargetCXXABI::Kind getCXXABIKind () const
Return the C++ ABI kind that should be used.
void cacheRawCommentForDecl (const Decl &OriginalD, const RawComment &Comment) const
Attaches Comment to OriginalD and to its redeclaration chain and removes the redeclaration chain from the set of commentless chains.
RawComment * getRawCommentForDeclNoCacheImpl (const Decl *D, const SourceLocation RepresentativeLocForDecl, const std::map< unsigned, RawComment * > &CommentsInFile) const
RawComment * getRawCommentForDeclNoCache (const Decl *D) const
Return the documentation comment attached to a given declaration, without looking into cache.
void addComment (const RawComment &RC)
const RawComment * getRawCommentForAnyRedecl (const Decl *D, const Decl **OriginalDecl=nullptr) const
Return the documentation comment attached to a given declaration.
void attachCommentsToJustParsedDecls (ArrayRef< Decl * > Decls, const Preprocessor *PP)
Searches existing comments for doc comments that should be attached to Decls.
comments::FullComment * getCommentForDecl (const Decl *D, const Preprocessor *PP) const
Return parsed documentation comment attached to a given declaration.
comments::FullComment * getLocalCommentForDeclUncached (const Decl *D) const
Return parsed documentation comment attached to a given declaration.
comments::FullComment * cloneFullComment (comments::FullComment *FC, const Decl *D) const
comments::CommandTraits & getCommentCommandTraits () const
AttrVec & getDeclAttrs (const Decl *D)
Retrieve the attributes for the given declaration.
void eraseDeclAttrs (const Decl *D)
Erase the attributes corresponding to the given declaration.
MemberSpecializationInfo * getInstantiatedFromStaticDataMember (const VarDecl *Var)
If this variable is an instantiated static data member of a class template specialization, returns the templated static data member from which it was instantiated.
void setInstantiatedFromStaticDataMember (VarDecl *Inst, VarDecl *Tmpl, TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation=SourceLocation())
Note that the static data member Inst is an instantiation of the static data member template Tmpl of a class template.
TemplateOrSpecializationInfo getTemplateOrSpecializationInfo (const VarDecl *Var)
void setTemplateOrSpecializationInfo (VarDecl *Inst, TemplateOrSpecializationInfo TSI)
NamedDecl * getInstantiatedFromUsingDecl (NamedDecl *Inst)
If the given using decl Inst is an instantiation of another (possibly unresolved) using decl, return it.
void setInstantiatedFromUsingDecl (NamedDecl *Inst, NamedDecl *Pattern)
Remember that the using decl Inst is an instantiation of the using decl Pattern of a class template.
UsingEnumDecl * getInstantiatedFromUsingEnumDecl (UsingEnumDecl *Inst)
If the given using-enum decl Inst is an instantiation of another using-enum decl, return it.
void setInstantiatedFromUsingEnumDecl (UsingEnumDecl *Inst, UsingEnumDecl *Pattern)
Remember that the using enum decl Inst is an instantiation of the using enum decl Pattern of a class template.
UsingShadowDecl * getInstantiatedFromUsingShadowDecl (UsingShadowDecl *Inst)
void setInstantiatedFromUsingShadowDecl (UsingShadowDecl *Inst, UsingShadowDecl *Pattern)
FieldDecl * getInstantiatedFromUnnamedFieldDecl (FieldDecl *Field)
void setInstantiatedFromUnnamedFieldDecl (FieldDecl *Inst, FieldDecl *Tmpl)
overridden_cxx_method_iterator overridden_methods_begin (const CXXMethodDecl *Method) const
overridden_cxx_method_iterator overridden_methods_end (const CXXMethodDecl *Method) const
unsigned overridden_methods_size (const CXXMethodDecl *Method) const
overridden_method_range overridden_methods (const CXXMethodDecl *Method) const
void addOverriddenMethod (const CXXMethodDecl *Method, const CXXMethodDecl *Overridden)
Note that the given C++ Method overrides the given Overridden method.
void getOverriddenMethods (const NamedDecl *Method, SmallVectorImpl< const NamedDecl * > &Overridden) const
Return C++ or ObjC overridden methods for the given Method.
void addedLocalImportDecl (ImportDecl *Import)
Notify the AST context that a new import declaration has been parsed or implicitly created within this translation unit.
import_range local_imports () const
Decl * getPrimaryMergedDecl (Decl *D)
void setPrimaryMergedDecl (Decl *D, Decl *Primary)
void mergeDefinitionIntoModule (NamedDecl *ND, Module *M, bool NotifyListeners=true)
Note that the definition ND has been merged into module M, and should be visible whenever M is visible.
void deduplicateMergedDefinitonsFor (NamedDecl *ND)
Clean up the merged definition list.
ArrayRef< Module * > getModulesWithMergedDefinition (const NamedDecl *Def)
Get the additional modules in which the definition Def has been merged.
void addModuleInitializer (Module *M, Decl *Init)
Add a declaration to the list of declarations that are initialized for a module.
void addLazyModuleInitializers (Module *M, ArrayRef< uint32_t > IDs)
ArrayRef< Decl * > getModuleInitializers (Module *M)
Get the initializations to perform when importing a module, if any.
void setCurrentNamedModule (Module *M)
Set the (C++20) module we are building.
Module * getCurrentNamedModule () const
Get module under construction, nullptr if this is not a C++20 module.
TranslationUnitDecl * getTranslationUnitDecl () const
void addTranslationUnitDecl ()
ExternCContextDecl * getExternCContextDecl () const
BuiltinTemplateDecl * getMakeIntegerSeqDecl () const
BuiltinTemplateDecl * getTypePackElementDecl () const
ASTContext (LangOptions &LOpts, SourceManager &SM, IdentifierTable &idents, SelectorTable &sels, Builtin::Context &builtins, TranslationUnitKind TUKind)
ASTContext (const ASTContext &)=delete
ASTContext & operator= (const ASTContext &)=delete
~ASTContext ()
void setExternalSource (IntrusiveRefCntPtr< ExternalASTSource > Source)
Attach an external AST source to the AST context.
ExternalASTSource * getExternalSource () const
Retrieve a pointer to the external AST source associated with this AST context, if any.
void setASTMutationListener (ASTMutationListener *Listener)
Attach an AST mutation listener to the AST context.
ASTMutationListener * getASTMutationListener () const
Retrieve a pointer to the AST mutation listener associated with this AST context, if any.
void PrintStats () const
const SmallVectorImpl< Type * > & getTypes () const
BuiltinTemplateDecl * buildBuiltinTemplateDecl (BuiltinTemplateKind BTK, const IdentifierInfo *II) const
RecordDecl * buildImplicitRecord (StringRef Name, RecordDecl::TagKind TK=TTK_Struct) const
Create a new implicit TU-level CXXRecordDecl or RecordDecl declaration.
TypedefDecl * buildImplicitTypedef (QualType T, StringRef Name) const
Create a new implicit TU-level typedef declaration.
TypedefDecl * getInt128Decl () const
Retrieve the declaration for the 128-bit signed integer type.
TypedefDecl * getUInt128Decl () const
Retrieve the declaration for the 128-bit unsigned integer type.
QualType getAddrSpaceQualType (QualType T, LangAS AddressSpace) const
Return the uniqued reference to the type for an address space qualified type with the specified type and address space.
QualType removeAddrSpaceQualType (QualType T) const
Remove any existing address space on the type and returns the type with qualifiers intact (or that's the idea anyway)
QualType applyObjCProtocolQualifiers (QualType type, ArrayRef< ObjCProtocolDecl * > protocols, bool &hasError, bool allowOnPointerType=false) const
Apply Objective-C protocol qualifiers to the given type.
QualType getObjCGCQualType (QualType T, Qualifiers::GC gcAttr) const
Return the uniqued reference to the type for an Objective-C gc-qualified type.
QualType removePtrSizeAddrSpace (QualType T) const
Remove the existing address space on the type if it is a pointer size address space and return the type with qualifiers intact.
QualType getRestrictType (QualType T) const
Return the uniqued reference to the type for a restrict qualified type.
QualType getVolatileType (QualType T) const
Return the uniqued reference to the type for a volatile qualified type.
QualType getConstType (QualType T) const
Return the uniqued reference to the type for a const qualified type.
const FunctionType * adjustFunctionType (const FunctionType *Fn, FunctionType::ExtInfo EInfo)
Change the ExtInfo on a function type.
CanQualType getCanonicalFunctionResultType (QualType ResultType) const
Adjust the given function result type.
void adjustDeducedFunctionResultType (FunctionDecl *FD, QualType ResultType)
Change the result type of a function type once it is deduced.
QualType getFunctionTypeWithExceptionSpec (QualType Orig, const FunctionProtoType::ExceptionSpecInfo &ESI) const
Get a function type and produce the equivalent function type with the specified exception specification.
bool hasSameFunctionTypeIgnoringExceptionSpec (QualType T, QualType U) const
Determine whether two function types are the same, ignoring exception specifications in cases where they're part of the type.
void adjustExceptionSpec (FunctionDecl *FD, const FunctionProtoType::ExceptionSpecInfo &ESI, bool AsWritten=false)
Change the exception specification on a function once it is delay-parsed, instantiated, or computed.
QualType getFunctionTypeWithoutPtrSizes (QualType T)
Get a function type and produce the equivalent function type where pointer size address spaces in the return type and parameter tyeps are replaced with the default address space.
bool hasSameFunctionTypeIgnoringPtrSizes (QualType T, QualType U)
Determine whether two function types are the same, ignoring pointer sizes in the return type and parameter types.
QualType getComplexType (QualType T) const
Return the uniqued reference to the type for a complex number with the specified element type.
CanQualType getComplexType (CanQualType T) const
QualType getPointerType (QualType T) const
Return the uniqued reference to the type for a pointer to the specified type.
CanQualType getPointerType (CanQualType T) const
QualType getAdjustedType (QualType Orig, QualType New) const
Return the uniqued reference to a type adjusted from the original type to a new type.
CanQualType getAdjustedType (CanQualType Orig, CanQualType New) const
QualType getDecayedType (QualType T) const
Return the uniqued reference to the decayed version of the given type.
CanQualType getDecayedType (CanQualType T) const
QualType getDecayedType (QualType Orig, QualType Decayed) const
Return the uniqued reference to a specified decay from the original type to the decayed type.
QualType getAtomicType (QualType T) const
Return the uniqued reference to the atomic type for the specified type.
QualType getBlockPointerType (QualType T) const
Return the uniqued reference to the type for a block of the specified type.
QualType getBlockDescriptorType () const
Gets the struct used to keep track of the descriptor for pointer to blocks.
QualType getReadPipeType (QualType T) const
Return a read_only pipe type for the specified type.
QualType getWritePipeType (QualType T) const
Return a write_only pipe type for the specified type.
QualType getBitIntType (bool Unsigned, unsigned NumBits) const
Return a bit-precise integer type with the specified signedness and bit count.
QualType getDependentBitIntType (bool Unsigned, Expr *BitsExpr) const
Return a dependent bit-precise integer type with the specified signedness and bit count.
QualType getBlockDescriptorExtendedType () const
Gets the struct used to keep track of the extended descriptor for pointer to blocks.
OpenCLTypeKind getOpenCLTypeKind (const Type *T) const
Map an AST Type to an OpenCLTypeKind enum value.
LangAS getOpenCLTypeAddrSpace (const Type *T) const
Get address space for OpenCL type.
LangAS getDefaultOpenCLPointeeAddrSpace ()
Returns default address space based on OpenCL version and enabled features.
void setcudaConfigureCallDecl (FunctionDecl *FD)
FunctionDecl * getcudaConfigureCallDecl ()
bool BlockRequiresCopying (QualType Ty, const VarDecl *D)
Returns true iff we need copy/dispose helpers for the given type.
bool getByrefLifetime (QualType Ty, Qualifiers::ObjCLifetime &Lifetime, bool &HasByrefExtendedLayout) const
Returns true, if given type has a known lifetime.
QualType getLValueReferenceType (QualType T, bool SpelledAsLValue=true) const
Return the uniqued reference to the type for an lvalue reference to the specified type.
QualType getRValueReferenceType (QualType T) const
Return the uniqued reference to the type for an rvalue reference to the specified type.
QualType getMemberPointerType (QualType T, const Type *Cls) const
Return the uniqued reference to the type for a member pointer to the specified type in the specified class.
QualType getVariableArrayType (QualType EltTy, Expr *NumElts, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals, SourceRange Brackets) const
Return a non-unique reference to the type for a variable array of the specified element type.
QualType getDependentSizedArrayType (QualType EltTy, Expr *NumElts, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals, SourceRange Brackets) const
Return a non-unique reference to the type for a dependently-sized array of the specified element type.
QualType getIncompleteArrayType (QualType EltTy, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals) const
Return a unique reference to the type for an incomplete array of the specified element type.
QualType getConstantArrayType (QualType EltTy, const llvm::APInt &ArySize, const Expr *SizeExpr, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals) const
Return the unique reference to the type for a constant array of the specified element type.
QualType getStringLiteralArrayType (QualType EltTy, unsigned Length) const
Return a type for a constant array for a string literal of the specified element type and length.
QualType getVariableArrayDecayedType (QualType Ty) const
Returns a vla type where known sizes are replaced with [*].
BuiltinVectorTypeInfo getBuiltinVectorTypeInfo (const BuiltinType *VecTy) const
Returns the element type, element count and number of vectors (in case of tuple) for a builtin vector type.
QualType getScalableVectorType (QualType EltTy, unsigned NumElts, unsigned NumFields=1) const
Return the unique reference to a scalable vector type of the specified element type and scalable number of elements.
QualType getWebAssemblyExternrefType () const
Return a WebAssembly externref type.
QualType getVectorType (QualType VectorType, unsigned NumElts, VectorType::VectorKind VecKind) const
Return the unique reference to a vector type of the specified element type and size.
QualType getDependentVectorType (QualType VectorType, Expr *SizeExpr, SourceLocation AttrLoc, VectorType::VectorKind VecKind) const
Return the unique reference to the type for a dependently sized vector of the specified element type.
QualType getExtVectorType (QualType VectorType, unsigned NumElts) const
Return the unique reference to an extended vector type of the specified element type and size.
QualType getDependentSizedExtVectorType (QualType VectorType, Expr *SizeExpr, SourceLocation AttrLoc) const
QualType getConstantMatrixType (QualType ElementType, unsigned NumRows, unsigned NumColumns) const
Return the unique reference to the matrix type of the specified element type and size.
QualType getDependentSizedMatrixType (QualType ElementType, Expr *RowExpr, Expr *ColumnExpr, SourceLocation AttrLoc) const
Return the unique reference to the matrix type of the specified element type and size.
QualType getDependentAddressSpaceType (QualType PointeeType, Expr *AddrSpaceExpr, SourceLocation AttrLoc) const
QualType getFunctionNoProtoType (QualType ResultTy, const FunctionType::ExtInfo &Info) const
Return a K&R style C function type like 'int()'.
QualType getFunctionNoProtoType (QualType ResultTy) const
QualType getFunctionType (QualType ResultTy, ArrayRef< QualType > Args, const FunctionProtoType::ExtProtoInfo &EPI) const
Return a normal function type with a typed argument list.
QualType adjustStringLiteralBaseType (QualType StrLTy) const
QualType getTypeDeclType (const TypeDecl *Decl, const TypeDecl *PrevDecl=nullptr) const
Return the unique reference to the type for the specified type declaration.
QualType getUsingType (const UsingShadowDecl *Found, QualType Underlying) const
QualType getTypedefType (const TypedefNameDecl *Decl, QualType Underlying=QualType()) const
Return the unique reference to the type for the specified typedef-name decl.
QualType getRecordType (const RecordDecl *Decl) const
QualType getEnumType (const EnumDecl *Decl) const
QualType getUnresolvedUsingType (const UnresolvedUsingTypenameDecl *Decl) const
QualType getInjectedClassNameType (CXXRecordDecl *Decl, QualType TST) const
getInjectedClassNameType - Return the unique reference to the injected class name type for the specified templated declaration.
QualType getAttributedType (attr::Kind attrKind, QualType modifiedType, QualType equivalentType) const
QualType getBTFTagAttributedType (const BTFTypeTagAttr *BTFAttr, QualType Wrapped)
QualType getSubstTemplateTypeParmType (QualType Replacement, Decl *AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex) const
Retrieve a substitution-result type.
QualType getSubstTemplateTypeParmPackType (Decl *AssociatedDecl, unsigned Index, bool Final, const TemplateArgument &ArgPack)
Retrieve a.
QualType getTemplateTypeParmType (unsigned Depth, unsigned Index, bool ParameterPack, TemplateTypeParmDecl *ParmDecl=nullptr) const
Retrieve the template type parameter type for a template parameter or parameter pack with the given depth, index, and (optionally) name.
QualType getTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgument > Args, QualType Canon=QualType()) const
QualType getCanonicalTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgument > Args) const
QualType getTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgumentLoc > Args, QualType Canon=QualType()) const
TypeSourceInfo * getTemplateSpecializationTypeInfo (TemplateName T, SourceLocation TLoc, const TemplateArgumentListInfo &Args, QualType Canon=QualType()) const
QualType getParenType (QualType NamedType) const
QualType getMacroQualifiedType (QualType UnderlyingTy, const IdentifierInfo *MacroII) const
QualType getElaboratedType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, QualType NamedType, TagDecl *OwnedTagDecl=nullptr) const
QualType getDependentNameType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name, QualType Canon=QualType()) const
QualType getDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name, ArrayRef< TemplateArgumentLoc > Args) const
QualType getDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier *NNS, const IdentifierInfo *Name, ArrayRef< TemplateArgument > Args) const
TemplateArgument getInjectedTemplateArg (NamedDecl *ParamDecl)
void getInjectedTemplateArgs (const TemplateParameterList *Params, SmallVectorImpl< TemplateArgument > &Args)
Get a template argument list with one argument per template parameter in a template parameter list, such as for the injected class name of a class template.
QualType getPackExpansionType (QualType Pattern, std::optional< unsigned > NumExpansions, bool ExpectPackInType=true)
Form a pack expansion type with the given pattern.
QualType getObjCInterfaceType (const ObjCInterfaceDecl *Decl, ObjCInterfaceDecl *PrevDecl=nullptr) const
getObjCInterfaceType - Return the unique reference to the type for the specified ObjC interface decl.
QualType getObjCObjectType (QualType Base, ObjCProtocolDecl *const *Protocols, unsigned NumProtocols) const
Legacy interface: cannot provide type arguments or __kindof.
QualType getObjCObjectType (QualType Base, ArrayRef< QualType > typeArgs, ArrayRef< ObjCProtocolDecl * > protocols, bool isKindOf) const
QualType getObjCTypeParamType (const ObjCTypeParamDecl *Decl, ArrayRef< ObjCProtocolDecl * > protocols) const
void adjustObjCTypeParamBoundType (const ObjCTypeParamDecl *Orig, ObjCTypeParamDecl *New) const
bool ObjCObjectAdoptsQTypeProtocols (QualType QT, ObjCInterfaceDecl *Decl)
ObjCObjectAdoptsQTypeProtocols - Checks that protocols in IC's protocol list adopt all protocols in QT's qualified-id protocol list.
bool QIdProtocolsAdoptObjCObjectProtocols (QualType QT, ObjCInterfaceDecl *IDecl)
QIdProtocolsAdoptObjCObjectProtocols - Checks that protocols in QT's qualified-id protocol list adopt all protocols in IDecl's list of protocols.
QualType getObjCObjectPointerType (QualType OIT) const
Return a ObjCObjectPointerType type for the given ObjCObjectType.
QualType getTypeOfExprType (Expr *E, TypeOfKind Kind) const
C2x feature and GCC extension.
QualType getTypeOfType (QualType QT, TypeOfKind Kind) const
getTypeOfType - Unlike many "get<Type>" functions, we don't unique TypeOfType nodes.
QualType getReferenceQualifiedType (const Expr *e) const
getReferenceQualifiedType - Given an expr, will return the type for that expression, as in [dcl.type.simple]p4 but without taking id-expressions and class member access into account.
QualType getDecltypeType (Expr *e, QualType UnderlyingType) const
C++11 decltype.
QualType getUnaryTransformType (QualType BaseType, QualType UnderlyingType, UnaryTransformType::UTTKind UKind) const
Unary type transforms.
QualType getAutoType (QualType DeducedType, AutoTypeKeyword Keyword, bool IsDependent, bool IsPack=false, ConceptDecl *TypeConstraintConcept=nullptr, ArrayRef< TemplateArgument > TypeConstraintArgs={}) const
C++11 deduced auto type.
QualType getAutoDeductType () const
C++11 deduction pattern for 'auto' type.
QualType getAutoRRefDeductType () const
C++11 deduction pattern for 'auto &&' type.
QualType getUnconstrainedType (QualType T) const
Remove any type constraints from a template parameter type, for equivalence comparison of template parameters.
QualType getDeducedTemplateSpecializationType (TemplateName Template, QualType DeducedType, bool IsDependent) const
C++17 deduced class template specialization type.
QualType getTagDeclType (const TagDecl *Decl) const
Return the unique reference to the type for the specified TagDecl (struct/union/class/enum) decl.
CanQualType getSizeType () const
Return the unique type for "size_t" (C99 7.17), defined in <stddef.h>.
CanQualType getSignedSizeType () const
Return the unique signed counterpart of the integer type corresponding to size_t.
CanQualType getIntMaxType () const
Return the unique type for "intmax_t" (C99 7.18.1.5), defined in <stdint.h>.
CanQualType getUIntMaxType () const
Return the unique type for "uintmax_t" (C99 7.18.1.5), defined in <stdint.h>.
QualType getWCharType () const
Return the unique wchar_t type available in C++ (and available as __wchar_t as a Microsoft extension).
QualType getWideCharType () const
Return the type of wide characters.
QualType getSignedWCharType () const
Return the type of "signed wchar_t".
QualType getUnsignedWCharType () const
Return the type of "unsigned wchar_t".
QualType getWIntType () const
In C99, this returns a type compatible with the type defined in <stddef.h> as defined by the target.
QualType getIntPtrType () const
Return a type compatible with "intptr_t" (C99 7.18.1.4), as defined by the target.
QualType getUIntPtrType () const
Return a type compatible with "uintptr_t" (C99 7.18.1.4), as defined by the target.
QualType getPointerDiffType () const
Return the unique type for "ptrdiff_t" (C99 7.17) defined in <stddef.h>.
QualType getUnsignedPointerDiffType () const
Return the unique unsigned counterpart of "ptrdiff_t" integer type.
QualType getProcessIDType () const
Return the unique type for "pid_t" defined in <sys/types.h>.
QualType getCFConstantStringType () const
Return the C structure type used to represent constant CFStrings.
QualType getObjCSuperType () const
Returns the C struct type for objc_super.
void setObjCSuperType (QualType ST)
QualType getRawCFConstantStringType () const
Get the structure type used to representation CFStrings, or NULL if it hasn't yet been built.
void setCFConstantStringType (QualType T)
TypedefDecl * getCFConstantStringDecl () const
RecordDecl * getCFConstantStringTagDecl () const
void setObjCConstantStringInterface (ObjCInterfaceDecl *Decl)
QualType getObjCConstantStringInterface () const
QualType getObjCNSStringType () const
void setObjCNSStringType (QualType T)
QualType getObjCIdRedefinitionType () const
Retrieve the type that id has been defined to, which may be different from the built-in id if id has been typedef'd.
void setObjCIdRedefinitionType (QualType RedefType)
Set the user-written type that redefines id.
QualType getObjCClassRedefinitionType () const
Retrieve the type that Class has been defined to, which may be different from the built-in Class if Class has been typedef'd.
void setObjCClassRedefinitionType (QualType RedefType)
Set the user-written type that redefines 'SEL'.
QualType getObjCSelRedefinitionType () const
Retrieve the type that 'SEL' has been defined to, which may be different from the built-in 'SEL' if 'SEL' has been typedef'd.
void setObjCSelRedefinitionType (QualType RedefType)
Set the user-written type that redefines 'SEL'.
IdentifierInfo * getNSObjectName () const
Retrieve the identifier 'NSObject'.
IdentifierInfo * getNSCopyingName ()
Retrieve the identifier 'NSCopying'.
CanQualType getNSUIntegerType () const
CanQualType getNSIntegerType () const
IdentifierInfo * getBoolName () const
Retrieve the identifier 'bool'.
IdentifierInfo * getMakeIntegerSeqName () const
IdentifierInfo * getTypePackElementName () const
QualType getObjCInstanceType ()
Retrieve the Objective-C "instancetype" type, if already known; otherwise, returns a NULL type;.
TypedefDecl * getObjCInstanceTypeDecl ()
Retrieve the typedef declaration corresponding to the Objective-C "instancetype" type.
void setFILEDecl (TypeDecl *FILEDecl)
Set the type for the C FILE type.
QualType getFILEType () const
Retrieve the C FILE type.
void setjmp_bufDecl (TypeDecl *jmp_bufDecl)
Set the type for the C jmp_buf type.
QualType getjmp_bufType () const
Retrieve the C jmp_buf type.
void setsigjmp_bufDecl (TypeDecl *sigjmp_bufDecl)
Set the type for the C sigjmp_buf type.
QualType getsigjmp_bufType () const
Retrieve the C sigjmp_buf type.
void setucontext_tDecl (TypeDecl *ucontext_tDecl)
Set the type for the C ucontext_t type.
QualType getucontext_tType () const
Retrieve the C ucontext_t type.
QualType getLogicalOperationType () const
The result type of logical operations, '<', '>', '!=', etc.
void getObjCEncodingForType (QualType T, std::string &S, const FieldDecl *Field=nullptr, QualType *NotEncodedT=nullptr) const
Emit the Objective-CC type encoding for the given type T into S.
void getObjCEncodingForPropertyType (QualType T, std::string &S) const
Emit the Objective-C property type encoding for the given type T into S.
void getLegacyIntegralTypeEncoding (QualType &t) const
getLegacyIntegralTypeEncoding - Another legacy compatibility encoding: 32-bit longs are encoded as 'l' or 'L' , but not always.
void getObjCEncodingForTypeQualifier (Decl::ObjCDeclQualifier QT, std::string &S) const
Put the string version of the type qualifiers QT into S.
std::string getObjCEncodingForFunctionDecl (const FunctionDecl *Decl) const
Emit the encoded type for the function Decl into S.
std::string getObjCEncodingForMethodDecl (const ObjCMethodDecl *Decl, bool Extended=false) const
Emit the encoded type for the method declaration Decl into S.
std::string getObjCEncodingForBlock (const BlockExpr *blockExpr) const
Return the encoded type for this block declaration.
std::string getObjCEncodingForPropertyDecl (const ObjCPropertyDecl *PD, const Decl *Container) const
getObjCEncodingForPropertyDecl - Return the encoded type for this method declaration.
bool ProtocolCompatibleWithProtocol (ObjCProtocolDecl *lProto, ObjCProtocolDecl *rProto) const
ProtocolCompatibleWithProtocol - return 'true' if 'lProto' is in the inheritance hierarchy of 'rProto'.
ObjCPropertyImplDecl * getObjCPropertyImplDeclForPropertyDecl (const ObjCPropertyDecl *PD, const Decl *Container) const
CharUnits getObjCEncodingTypeSize (QualType T) const
Return the size of type T for Objective-C encoding purpose, in characters.
TypedefDecl * getObjCIdDecl () const
Retrieve the typedef corresponding to the predefined id type in Objective-C.
QualType getObjCIdType () const
Represents the Objective-CC id type.
TypedefDecl * getObjCSelDecl () const
Retrieve the typedef corresponding to the predefined 'SEL' type in Objective-C.
QualType getObjCSelType () const
Retrieve the type that corresponds to the predefined Objective-C 'SEL' type.
TypedefDecl * getObjCClassDecl () const
Retrieve the typedef declaration corresponding to the predefined Objective-C 'Class' type.
QualType getObjCClassType () const
Represents the Objective-C Class type.
ObjCInterfaceDecl * getObjCProtocolDecl () const
Retrieve the Objective-C class declaration corresponding to the predefined Protocol class.
TypedefDecl * getBOOLDecl () const
Retrieve declaration of 'BOOL' typedef.
void setBOOLDecl (TypedefDecl *TD)
Save declaration of 'BOOL' typedef.
QualType getBOOLType () const
type of 'BOOL' type.
QualType getObjCProtoType () const
Retrieve the type of the Objective-C Protocol class.
TypedefDecl * getBuiltinVaListDecl () const
Retrieve the C type declaration corresponding to the predefined __builtin_va_list type.
QualType getBuiltinVaListType () const
Retrieve the type of the __builtin_va_list type.
Decl * getVaListTagDecl () const
Retrieve the C type declaration corresponding to the predefined __va_list_tag type used to help define the __builtin_va_list type for some targets.
TypedefDecl * getBuiltinMSVaListDecl () const
Retrieve the C type declaration corresponding to the predefined __builtin_ms_va_list type.
QualType getBuiltinMSVaListType () const
Retrieve the type of the __builtin_ms_va_list type.
TagDecl * getMSGuidTagDecl () const
Retrieve the implicitly-predeclared 'struct _GUID' declaration.
QualType getMSGuidType () const
Retrieve the implicitly-predeclared 'struct _GUID' type.
bool canBuiltinBeRedeclared (const FunctionDecl *) const
Return whether a declaration to a builtin is allowed to be overloaded/redeclared.
QualType getCVRQualifiedType (QualType T, unsigned CVR) const
Return a type with additional const, volatile, or restrict qualifiers.
QualType getQualifiedType (SplitQualType split) const
Un-split a SplitQualType.
QualType getQualifiedType (QualType T, Qualifiers Qs) const
Return a type with additional qualifiers.
QualType getQualifiedType (const Type *T, Qualifiers Qs) const
Return a type with additional qualifiers.
QualType getLifetimeQualifiedType (QualType type, Qualifiers::ObjCLifetime lifetime)
Return a type with the given lifetime qualifier.
QualType getUnqualifiedObjCPointerType (QualType type) const
getUnqualifiedObjCPointerType - Returns version of Objective-C pointer type with lifetime qualifier removed.
unsigned char getFixedPointScale (QualType Ty) const
unsigned char getFixedPointIBits (QualType Ty) const
llvm::FixedPointSemantics getFixedPointSemantics (QualType Ty) const
llvm::APFixedPoint getFixedPointMax (QualType Ty) const
llvm::APFixedPoint getFixedPointMin (QualType Ty) const
DeclarationNameInfo getNameForTemplate (TemplateName Name, SourceLocation NameLoc) const
TemplateName getOverloadedTemplateName (UnresolvedSetIterator Begin, UnresolvedSetIterator End) const
Retrieve the template name that corresponds to a non-empty lookup.
TemplateName getAssumedTemplateName (DeclarationName Name) const
Retrieve a template name representing an unqualified-id that has been assumed to name a template for ADL purposes.
TemplateName getQualifiedTemplateName (NestedNameSpecifier *NNS, bool TemplateKeyword, TemplateName Template) const
Retrieve the template name that represents a qualified template name such as std::vector.
TemplateName getDependentTemplateName (NestedNameSpecifier *NNS, const IdentifierInfo *Name) const
Retrieve the template name that represents a dependent template name such as MetaFun::template apply.
TemplateName getDependentTemplateName (NestedNameSpecifier *NNS, OverloadedOperatorKind Operator) const
Retrieve the template name that represents a dependent template name such as MetaFun::template operator+.
TemplateName getSubstTemplateTemplateParm (TemplateName replacement, Decl *AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex) const
TemplateName getSubstTemplateTemplateParmPack (const TemplateArgument &ArgPack, Decl *AssociatedDecl, unsigned Index, bool Final) const
QualType DecodeTypeStr (const char *&Str, const ASTContext &Context, ASTContext::GetBuiltinTypeError &Error, bool &RequireICE, bool AllowTypeModifiers) const
QualType GetBuiltinType (unsigned ID, GetBuiltinTypeError &Error, unsigned *IntegerConstantArgs=nullptr) const
Return the type for the specified builtin.
Qualifiers::GC getObjCGCAttrKind (QualType Ty) const
Return one of the GCNone, Weak or Strong Objective-C garbage collection attributes.
bool areCompatibleVectorTypes (QualType FirstVec, QualType SecondVec)
Return true if the given vector types are of the same unqualified type or if they are equivalent to the same GCC vector type.
bool areCompatibleSveTypes (QualType FirstType, QualType SecondType)
Return true if the given types are an SVE builtin and a VectorType that is a fixed-length representation of the SVE builtin for a specific vector-length.
bool areLaxCompatibleSveTypes (QualType FirstType, QualType SecondType)
Return true if the given vector types are lax-compatible SVE vector types, false otherwise.
bool areCompatibleRVVTypes (QualType FirstType, QualType SecondType)
Return true if the given types are an RISC-V vector builtin type and a VectorType that is a fixed-length representation of the RISC-V vector builtin type for a specific vector-length.
bool areLaxCompatibleRVVTypes (QualType FirstType, QualType SecondType)
Return true if the given vector types are lax-compatible RISC-V vector types as defined by -flax-vector-conversions=, which permits implicit conversions between vectors with different number of elements and/or incompatible element types, false otherwise.
bool hasDirectOwnershipQualifier (QualType Ty) const
Return true if the type has been explicitly qualified with ObjC ownership.
const llvm::fltSemantics & getFloatTypeSemantics (QualType T) const
Return the APFloat 'semantics' for the specified scalar floating point type.
TypeInfo getTypeInfo (const Type *T) const
Get the size and alignment of the specified complete type in bits.
TypeInfo getTypeInfo (QualType T) const
unsigned getOpenMPDefaultSimdAlign (QualType T) const
Get default simd alignment of the specified complete type in bits.
uint64_t getTypeSize (QualType T) const
Return the size of the specified (complete) type T, in bits.
uint64_t getTypeSize (const Type *T) const
uint64_t getCharWidth () const
Return the size of the character type, in bits.
CharUnits toCharUnitsFromBits (int64_t BitSize) const
Convert a size in bits to a size in characters.
int64_t toBits (CharUnits CharSize) const
Convert a size in characters to a size in bits.
CharUnits getTypeSizeInChars (QualType T) const
Return the size of the specified (complete) type T, in characters.
CharUnits getTypeSizeInChars (const Type *T) const
std::optional< CharUnits > getTypeSizeInCharsIfKnown (QualType Ty) const
std::optional< CharUnits > getTypeSizeInCharsIfKnown (const Type *Ty) const
unsigned getTypeAlign (QualType T) const
Return the ABI-specified alignment of a (complete) type T, in bits.
unsigned getTypeAlign (const Type *T) const
unsigned getTypeUnadjustedAlign (QualType T) const
Return the ABI-specified natural alignment of a (complete) type T, before alignment adjustments, in bits.
unsigned getTypeUnadjustedAlign (const Type *T) const
unsigned getTypeAlignIfKnown (QualType T, bool NeedsPreferredAlignment=false) const
Return the alignment of a type, in bits, or 0 if the type is incomplete and we cannot determine the alignment (for example, from alignment attributes).
CharUnits getTypeAlignInChars (QualType T) const
Return the ABI-specified alignment of a (complete) type T, in characters.
CharUnits getTypeAlignInChars (const Type *T) const
CharUnits getPreferredTypeAlignInChars (QualType T) const
Return the PreferredAlignment of a (complete) type T, in characters.
CharUnits getTypeUnadjustedAlignInChars (QualType T) const
getTypeUnadjustedAlignInChars - Return the ABI-specified alignment of a type, in characters, before alignment adjustments.
CharUnits getTypeUnadjustedAlignInChars (const Type *T) const
TypeInfoChars getTypeInfoDataSizeInChars (QualType T) const
TypeInfoChars getTypeInfoInChars (const Type *T) const
TypeInfoChars getTypeInfoInChars (QualType T) const
bool isAlignmentRequired (const Type *T) const
Determine if the alignment the type has was required using an alignment attribute.
bool isAlignmentRequired (QualType T) const
bool isPromotableIntegerType (QualType T) const
More type predicates useful for type checking/promotion.
unsigned getPreferredTypeAlign (QualType T) const
Return the "preferred" alignment of the specified type T for the current target, in bits.
unsigned getPreferredTypeAlign (const Type *T) const
getPreferredTypeAlign - Return the "preferred" alignment of the specified type for the current target in bits.
unsigned getTargetDefaultAlignForAttributeAligned () const
Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
unsigned getAlignOfGlobalVar (QualType T) const
Return the alignment in bits that should be given to a global variable with type T.
CharUnits getAlignOfGlobalVarInChars (QualType T) const
Return the alignment in characters that should be given to a global variable with type T.
CharUnits getDeclAlign (const Decl *D, bool ForAlignof=false) const
Return a conservative estimate of the alignment of the specified decl D.
CharUnits getExnObjectAlignment () const
Return the alignment (in bytes) of the thrown exception object.
const ASTRecordLayout & getASTRecordLayout (const RecordDecl *D) const
Get or compute information about the layout of the specified record (struct/union/class) D, which indicates its size and field position information.
const ASTRecordLayout & getASTObjCInterfaceLayout (const ObjCInterfaceDecl *D) const
Get or compute information about the layout of the specified Objective-C interface.
void DumpRecordLayout (const RecordDecl *RD, raw_ostream &OS, bool Simple=false) const
const ASTRecordLayout & getASTObjCImplementationLayout (const ObjCImplementationDecl *D) const
Get or compute information about the layout of the specified Objective-C implementation.
const CXXMethodDecl * getCurrentKeyFunction (const CXXRecordDecl *RD)
Get our current best idea for the key function of the given record decl, or nullptr if there isn't one.
void setNonKeyFunction (const CXXMethodDecl *method)
Observe that the given method cannot be a key function.
CharUnits getOffsetOfBaseWithVBPtr (const CXXRecordDecl *RD) const
Loading virtual member pointers using the virtual inheritance model always results in an adjustment using the vbtable even if the index is zero.
uint64_t getFieldOffset (const ValueDecl *FD) const
Get the offset of a FieldDecl or IndirectFieldDecl, in bits.
uint64_t lookupFieldBitOffset (const ObjCInterfaceDecl *OID, const ObjCImplementationDecl *ID, const ObjCIvarDecl *Ivar) const
Get the offset of an ObjCIvarDecl in bits.
CharUnits getMemberPointerPathAdjustment (const APValue &MP) const
Find the 'this' offset for the member path in a pointer-to-member APValue.
bool isNearlyEmpty (const CXXRecordDecl *RD) const
VTableContextBase * getVTableContext ()
MangleContext * createMangleContext (const TargetInfo *T=nullptr)
If T is null pointer, assume the target in ASTContext.
MangleContext * createDeviceMangleContext (const TargetInfo &T)
Creates a device mangle context to correctly mangle lambdas in a mixed architecture compile by setting the lambda mangling number source to the DeviceLambdaManglingNumber.
void DeepCollectObjCIvars (const ObjCInterfaceDecl *OI, bool leafClass, SmallVectorImpl< const ObjCIvarDecl * > &Ivars) const
DeepCollectObjCIvars - This routine first collects all declared, but not synthesized, ivars in super class and then collects all ivars, including those synthesized for current class.
unsigned CountNonClassIvars (const ObjCInterfaceDecl *OI) const
void CollectInheritedProtocols (const Decl *CDecl, llvm::SmallPtrSet< ObjCProtocolDecl *, 8 > &Protocols)
CollectInheritedProtocols - Collect all protocols in current class and those inherited by it.
bool hasUniqueObjectRepresentations (QualType Ty, bool CheckIfTriviallyCopyable=true) const
Return true if the specified type has unique object representations according to (C++17 [meta.unary.prop]p9)
CanQualType getCanonicalType (QualType T) const
Return the canonical (structural) type corresponding to the specified potentially non-canonical type T.
const Type * getCanonicalType (const Type *T) const
CanQualType getCanonicalParamType (QualType T) const
Return the canonical parameter type corresponding to the specific potentially non-canonical one.
bool hasSameType (QualType T1, QualType T2) const
Determine whether the given types T1 and T2 are equivalent.
bool hasSameType (const Type *T1, const Type *T2) const
bool hasSameExpr (const Expr *X, const Expr *Y) const
Determine whether the given expressions X and Y are equivalent.
QualType getUnqualifiedArrayType (QualType T, Qualifiers &Quals)
Return this type as a completely-unqualified array type, capturing the qualifiers in Quals.
bool hasSameUnqualifiedType (QualType T1, QualType T2) const
Determine whether the given types are equivalent after cvr-qualifiers have been removed.
bool hasSameNullabilityTypeQualifier (QualType SubT, QualType SuperT, bool IsParam) const
bool ObjCMethodsAreEqual (const ObjCMethodDecl *MethodDecl, const ObjCMethodDecl *MethodImp)
bool UnwrapSimilarTypes (QualType &T1, QualType &T2, bool AllowPiMismatch=true)
Attempt to unwrap two types that may be similar (C++ [conv.qual]).
void UnwrapSimilarArrayTypes (QualType &T1, QualType &T2, bool AllowPiMismatch=true)
Attempt to unwrap two types that may both be array types with the same bound (or both be array types of unknown bound) for the purpose of comparing the cv-decomposition of two types per C++ [conv.qual].
bool hasSimilarType (QualType T1, QualType T2)
Determine if two types are similar, according to the C++ rules.
bool hasCvrSimilarType (QualType T1, QualType T2)
Determine if two types are similar, ignoring only CVR qualifiers.
NestedNameSpecifier * getCanonicalNestedNameSpecifier (NestedNameSpecifier *NNS) const
Retrieves the "canonical" nested name specifier for a given nested name specifier.
CallingConv getDefaultCallingConvention (bool IsVariadic, bool IsCXXMethod, bool IsBuiltin=false) const
Retrieves the default calling convention for the current target.
TemplateName getCanonicalTemplateName (const TemplateName &Name) const
Retrieves the "canonical" template name that refers to a given template.
bool hasSameTemplateName (const TemplateName &X, const TemplateName &Y) const
Determine whether the given template names refer to the same template.
bool isSameEntity (const NamedDecl *X, const NamedDecl *Y) const
Determine whether the two declarations refer to the same entity.
bool isSameTemplateParameterList (const TemplateParameterList *X, const TemplateParameterList *Y) const
Determine whether two template parameter lists are similar enough that they may be used in declarations of the same template.
bool isSameTemplateParameter (const NamedDecl *X, const NamedDecl *Y) const
Determine whether two template parameters are similar enough that they may be used in declarations of the same template.
bool isSameConstraintExpr (const Expr *XCE, const Expr *YCE) const
Determine whether two 'requires' expressions are similar enough that they may be used in re-declarations.
bool isSameTypeConstraint (const TypeConstraint *XTC, const TypeConstraint *YTC) const
Determine whether two type contraint are similar enough that they could used in declarations of the same template.
bool isSameDefaultTemplateArgument (const NamedDecl *X, const NamedDecl *Y) const
Determine whether two default template arguments are similar enough that they may be used in declarations of the same template.
TemplateArgument getCanonicalTemplateArgument (const TemplateArgument &Arg) const
Retrieve the "canonical" template argument.
const ArrayType * getAsArrayType (QualType T) const
Type Query functions.
const ConstantArrayType * getAsConstantArrayType (QualType T) const
const VariableArrayType * getAsVariableArrayType (QualType T) const
const IncompleteArrayType * getAsIncompleteArrayType (QualType T) const
const DependentSizedArrayType * getAsDependentSizedArrayType (QualType T) const
QualType getBaseElementType (const ArrayType *VAT) const
Return the innermost element type of an array type.
QualType getBaseElementType (QualType QT) const
Return the innermost element type of a type (which needn't actually be an array type).
uint64_t getConstantArrayElementCount (const ConstantArrayType *CA) const
Return number of constant array elements.
uint64_t getArrayInitLoopExprElementCount (const ArrayInitLoopExpr *AILE) const
Return number of elements initialized in an ArrayInitLoopExpr.
QualType getAdjustedParameterType (QualType T) const
Perform adjustment on the parameter type of a function.
QualType getSignatureParameterType (QualType T) const
Retrieve the parameter type as adjusted for use in the signature of a function, decaying array and function types and removing top-level cv-qualifiers.
QualType getExceptionObjectType (QualType T) const
QualType getArrayDecayedType (QualType T) const
Return the properly qualified result of decaying the specified array type to a pointer.
QualType getPromotedIntegerType (QualType PromotableType) const
Return the type that PromotableType will promote to: C99 6.3.1.1p2, assuming that PromotableType is a promotable integer type.
Qualifiers::ObjCLifetime getInnerObjCOwnership (QualType T) const
Recurses in pointer/array types until it finds an Objective-C retainable type and returns its ownership.
QualType isPromotableBitField (Expr *E) const
Whether this is a promotable bitfield reference according to C99 6.3.1.1p2, bullet 2 (and GCC extensions).
int getIntegerTypeOrder (QualType LHS, QualType RHS) const
Return the highest ranked integer type, see C99 6.3.1.8p1.
int getFloatingTypeOrder (QualType LHS, QualType RHS) const
Compare the rank of the two specified floating point types, ignoring the domain of the type (i.e.
int getFloatingTypeSemanticOrder (QualType LHS, QualType RHS) const
Compare the rank of two floating point types as above, but compare equal if both types have the same floating-point semantics on the target (i.e.
unsigned getTargetAddressSpace (LangAS AS) const
LangAS getLangASForBuiltinAddressSpace (unsigned AS) const
uint64_t getTargetNullPointerValue (QualType QT) const
Get target-dependent integer value for null pointer which is used for constant folding.
bool addressSpaceMapManglingFor (LangAS AS) const
FunctionProtoType::ExceptionSpecInfo mergeExceptionSpecs (FunctionProtoType::ExceptionSpecInfo ESI1, FunctionProtoType::ExceptionSpecInfo ESI2, SmallVectorImpl< QualType > &ExceptionTypeStorage, bool AcceptDependent)
QualType getCommonSugaredType (QualType X, QualType Y, bool Unqualified=false)
bool typesAreCompatible (QualType T1, QualType T2, bool CompareUnqualified=false)
Compatibility predicates used to check assignment expressions.
bool propertyTypesAreCompatible (QualType, QualType)
bool typesAreBlockPointerCompatible (QualType, QualType)
bool isObjCIdType (QualType T) const
bool isObjCClassType (QualType T) const
bool isObjCSelType (QualType T) const
bool ObjCQualifiedIdTypesAreCompatible (const ObjCObjectPointerType *LHS, const ObjCObjectPointerType *RHS, bool ForCompare)
ObjCQualifiedIdTypesAreCompatible - We know that one of lhs/rhs is an ObjCQualifiedIDType.
bool ObjCQualifiedClassTypesAreCompatible (const ObjCObjectPointerType *LHS, const ObjCObjectPointerType *RHS)
ObjCQualifiedClassTypesAreCompatible - compare Class<pr,...> and Class<pr1, ...>.
bool canAssignObjCInterfaces (const ObjCObjectPointerType *LHSOPT, const ObjCObjectPointerType *RHSOPT)
canAssignObjCInterfaces - Return true if the two interface types are compatible for assignment from RHS to LHS.
bool canAssignObjCInterfaces (const ObjCObjectType *LHS, const ObjCObjectType *RHS)
bool canAssignObjCInterfacesInBlockPointer (const ObjCObjectPointerType *LHSOPT, const ObjCObjectPointerType *RHSOPT, bool BlockReturnType)
canAssignObjCInterfacesInBlockPointer - This routine is specifically written for providing type-safety for objective-c pointers used to pass/return arguments in block literals.
bool areComparableObjCPointerTypes (QualType LHS, QualType RHS)
QualType areCommonBaseCompatible (const ObjCObjectPointerType *LHSOPT, const ObjCObjectPointerType *RHSOPT)
bool canBindObjCObjectType (QualType To, QualType From)
QualType mergeTypes (QualType, QualType, bool OfBlockPointer=false, bool Unqualified=false, bool BlockReturnType=false, bool IsConditionalOperator=false)
QualType mergeFunctionTypes (QualType, QualType, bool OfBlockPointer=false, bool Unqualified=false, bool AllowCXX=false, bool IsConditionalOperator=false)
QualType mergeFunctionParameterTypes (QualType, QualType, bool OfBlockPointer=false, bool Unqualified=false)
mergeFunctionParameterTypes - merge two types which appear as function parameter types
QualType mergeTransparentUnionType (QualType, QualType, bool OfBlockPointer=false, bool Unqualified=false)
mergeTransparentUnionType - if T is a transparent union type and a member of T is compatible with SubType, return the merged type, else return QualType()
QualType mergeObjCGCQualifiers (QualType, QualType)
mergeObjCGCQualifiers - This routine merges ObjC's GC attribute of 'LHS' and 'RHS' attributes and returns the merged version; including for function return types.
bool mergeExtParameterInfo (const FunctionProtoType *FirstFnType, const FunctionProtoType *SecondFnType, bool &CanUseFirst, bool &CanUseSecond, SmallVectorImpl< FunctionProtoType::ExtParameterInfo > &NewParamInfos)
This function merges the ExtParameterInfo lists of two functions.
void ResetObjCLayout (const ObjCContainerDecl *CD)
unsigned getIntWidth (QualType T) const
QualType getCorrespondingUnsignedType (QualType T) const
QualType getCorrespondingSignedType (QualType T) const
QualType getCorrespondingSaturatedType (QualType Ty) const
QualType getCorrespondingSignedFixedPointType (QualType Ty) const
llvm::APSInt MakeIntValue (uint64_t Value, QualType Type) const
Make an APSInt of the appropriate width and signedness for the given Value and integer Type.
bool isSentinelNullExpr (const Expr *E)
ObjCImplementationDecl * getObjCImplementation (ObjCInterfaceDecl *D)
Get the implementation of the ObjCInterfaceDecl D, or nullptr if none exists.
ObjCCategoryImplDecl * getObjCImplementation (ObjCCategoryDecl *D)
Get the implementation of the ObjCCategoryDecl D, or nullptr if none exists.
bool AnyObjCImplementation ()
Return true if there is at least one @implementation in the TU.
void setObjCImplementation (ObjCInterfaceDecl *IFaceD, ObjCImplementationDecl *ImplD)
Set the implementation of ObjCInterfaceDecl.
void setObjCImplementation (ObjCCategoryDecl *CatD, ObjCCategoryImplDecl *ImplD)
Set the implementation of ObjCCategoryDecl.
const ObjCMethodDecl * getObjCMethodRedeclaration (const ObjCMethodDecl *MD) const
Get the duplicate declaration of a ObjCMethod in the same interface, or null if none exists.
void setObjCMethodRedeclaration (const ObjCMethodDecl *MD, const ObjCMethodDecl *Redecl)
const ObjCInterfaceDecl * getObjContainingInterface (const NamedDecl *ND) const
Returns the Objective-C interface that ND belongs to if it is an Objective-C method/property/ivar etc.
void setBlockVarCopyInit (const VarDecl *VD, Expr *CopyExpr, bool CanThrow)
Set the copy initialization expression of a block var decl.
BlockVarCopyInit getBlockVarCopyInit (const VarDecl *VD) const
Get the copy initialization expression of the VarDecl VD, or nullptr if none exists.
TypeSourceInfo * CreateTypeSourceInfo (QualType T, unsigned Size=0) const
Allocate an uninitialized TypeSourceInfo.
TypeSourceInfo * getTrivialTypeSourceInfo (QualType T, SourceLocation Loc=SourceLocation()) const
Allocate a TypeSourceInfo where all locations have been initialized to a given location, which defaults to the empty location.
void AddDeallocation (void(*Callback)(void *), void *Data) const
Add a deallocation callback that will be invoked when the ASTContext is destroyed.
template<typename T >
void addDestruction (T *Ptr) const
If T isn't trivially destructible, calls AddDeallocation to register it for destruction.
GVALinkage GetGVALinkageForFunction (const FunctionDecl *FD) const
GVALinkage GetGVALinkageForVariable (const VarDecl *VD) const
bool DeclMustBeEmitted (const Decl *D)
Determines if the decl can be CodeGen'ed or deserialized from PCH lazily, only when used; this is only relevant for function or file scoped var definitions.
void forEachMultiversionedFunctionVersion (const FunctionDecl *FD, llvm::function_ref< void(FunctionDecl *)> Pred) const
Visits all versions of a multiversioned function with the passed predicate.
const CXXConstructorDecl * getCopyConstructorForExceptionObject (CXXRecordDecl *RD)
void addCopyConstructorForExceptionObject (CXXRecordDecl *RD, CXXConstructorDecl *CD)
void addTypedefNameForUnnamedTagDecl (TagDecl *TD, TypedefNameDecl *TND)
TypedefNameDecl * getTypedefNameForUnnamedTagDecl (const TagDecl *TD)
void addDeclaratorForUnnamedTagDecl (TagDecl *TD, DeclaratorDecl *DD)
DeclaratorDecl * getDeclaratorForUnnamedTagDecl (const TagDecl *TD)
void setManglingNumber (const NamedDecl *ND, unsigned Number)
unsigned getManglingNumber (const NamedDecl *ND, bool ForAuxTarget=false) const
void setStaticLocalNumber (const VarDecl *VD, unsigned Number)
unsigned getStaticLocalNumber (const VarDecl *VD) const
MangleNumberingContext & getManglingNumberContext (const DeclContext *DC)
Retrieve the context for computing mangling numbers in the given DeclContext.
MangleNumberingContext & getManglingNumberContext (NeedExtraManglingDecl_t, const Decl *D)
std::unique_ptr< MangleNumberingContext > createMangleNumberingContext () const
void setParameterIndex (const ParmVarDecl *D, unsigned index)
Used by ParmVarDecl to store on the side the index of the parameter when it exceeds the size of the normal bitfield.
unsigned getParameterIndex (const ParmVarDecl *D) const
Used by ParmVarDecl to retrieve on the side the index of the parameter when it exceeds the size of the normal bitfield.
StringLiteral * getPredefinedStringLiteralFromCache (StringRef Key) const
Return a string representing the human readable name for the specified function declaration or file name.
MSGuidDecl * getMSGuidDecl (MSGuidDeclParts Parts) const
Return a declaration for the global GUID object representing the given GUID value.
UnnamedGlobalConstantDecl * getUnnamedGlobalConstantDecl (QualType Ty, const APValue &Value) const
Return a declaration for a uniquified anonymous global constant corresponding to a given APValue.
TemplateParamObjectDecl * getTemplateParamObjectDecl (QualType T, const APValue &V) const
Return the template parameter object of the given type with the given value.
ParsedTargetAttr filterFunctionTargetAttrs (const TargetAttr *TD) const
Parses the target attributes passed in, and returns only the ones that are valid feature names.
std::vector< std::string > filterFunctionTargetVersionAttrs (const TargetVersionAttr *TV) const
void getFunctionFeatureMap (llvm::StringMap< bool > &FeatureMap, const FunctionDecl *) const
void getFunctionFeatureMap (llvm::StringMap< bool > &FeatureMap, GlobalDecl GD) const
void InitBuiltinTypes (const TargetInfo &Target, const TargetInfo *AuxTarget=nullptr)
Initialize built-in types.
void getObjCEncodingForMethodParameter (Decl::ObjCDeclQualifier QT, QualType T, std::string &S, bool Extended) const
getObjCEncodingForMethodParameter - Return the encoded type for a single method parameter or return type.
bool isMSStaticDataMemberInlineDefinition (const VarDecl *VD) const
Returns true if this is an inline-initialized static data member which is treated as a definition for MSVC compatibility.
InlineVariableDefinitionKind getInlineVariableDefinitionKind (const VarDecl *VD) const
Determine whether a definition of this inline variable should be treated as a weak or strong definition.
OMPTraitInfo & getNewOMPTraitInfo ()
Return a new OMPTraitInfo object owned by this context.
bool mayExternalize (const Decl *D) const
Whether a C++ static variable or CUDA/HIP kernel may be externalized.
bool shouldExternalize (const Decl *D) const
Whether a C++ static variable or CUDA/HIP kernel should be externalized.
StringRef getCUIDHash () const
template<>
DynTypedNodeList getParents (const DynTypedNode &Node)
Static Public Member Functions
static ImportDecl * getNextLocalImport (ImportDecl *Import)
static bool isObjCNSObjectType (QualType Ty)
Return true if this is an NSObject object with its NSObject attribute set.
Public Attributes
IdentifierTable & Idents
SelectorTable & Selectors
Builtin::Context & BuiltinInfo
const TranslationUnitKind TUKind
DeclarationNameTable DeclarationNames
IntrusiveRefCntPtr< ExternalASTSource > ExternalSource
ASTMutationListener * Listener = nullptr
struct clang::ASTContext::CUDAConstantEvalContext CUDAConstantEvalCtx
RawCommentList Comments
All comments in this translation unit.
bool CommentsLoaded = false
True if comments are already loaded from ExternalASTSource.
llvm::DenseMap< const Decl *, const RawComment * > DeclRawComments
Mapping from declaration to directly attached comment.
llvm::DenseMap< const Decl *, const Decl * > RedeclChainComments
Mapping from canonical declaration to the first redeclaration in chain that has a comment attached.
llvm::DenseMap< const Decl *, const Decl * > CommentlessRedeclChains
Keeps track of redeclaration chains that don't have any comment attached.
llvm::DenseMap< const Decl *, comments::FullComment * > ParsedComments
Mapping from declarations to parsed comments attached to any redeclaration.
CanQualType VoidTy
CanQualType BoolTy
CanQualType CharTy
CanQualType WCharTy
CanQualType WideCharTy
CanQualType WIntTy
CanQualType Char8Ty
CanQualType Char16Ty
CanQualType Char32Ty
CanQualType SignedCharTy
CanQualType ShortTy
CanQualType IntTy
CanQualType LongTy
CanQualType LongLongTy
CanQualType Int128Ty
CanQualType UnsignedCharTy
CanQualType UnsignedShortTy
CanQualType UnsignedIntTy
CanQualType UnsignedLongTy
CanQualType UnsignedLongLongTy
CanQualType UnsignedInt128Ty
CanQualType FloatTy
CanQualType DoubleTy
CanQualType LongDoubleTy
CanQualType Float128Ty
CanQualType Ibm128Ty
CanQualType ShortAccumTy
CanQualType AccumTy
CanQualType LongAccumTy
CanQualType UnsignedShortAccumTy
CanQualType UnsignedAccumTy
CanQualType UnsignedLongAccumTy
CanQualType ShortFractTy
CanQualType FractTy
CanQualType LongFractTy
CanQualType UnsignedShortFractTy
CanQualType UnsignedFractTy
CanQualType UnsignedLongFractTy
CanQualType SatShortAccumTy
CanQualType SatAccumTy
CanQualType SatLongAccumTy
CanQualType SatUnsignedShortAccumTy
CanQualType SatUnsignedAccumTy
CanQualType SatUnsignedLongAccumTy
CanQualType SatShortFractTy
CanQualType SatFractTy
CanQualType SatLongFractTy
CanQualType SatUnsignedShortFractTy
CanQualType SatUnsignedFractTy
CanQualType SatUnsignedLongFractTy
CanQualType HalfTy
CanQualType BFloat16Ty
CanQualType Float16Ty
CanQualType VoidPtrTy
CanQualType NullPtrTy
CanQualType DependentTy
CanQualType OverloadTy
CanQualType BoundMemberTy
CanQualType UnknownAnyTy
CanQualType BuiltinFnTy
CanQualType PseudoObjectTy
CanQualType ARCUnbridgedCastTy
CanQualType ObjCBuiltinIdTy
CanQualType ObjCBuiltinClassTy
CanQualType ObjCBuiltinSelTy
CanQualType ObjCBuiltinBoolTy
CanQualType OCLSamplerTy
CanQualType OCLEventTy
CanQualType OCLClkEventTy
CanQualType OCLQueueTy
CanQualType OCLReserveIDTy
CanQualType IncompleteMatrixIdxTy
CanQualType OMPArraySectionTy
CanQualType OMPArrayShapingTy
CanQualType OMPIteratorTy
QualType AutoDeductTy
QualType AutoRRefDeductTy
Decl * VaListTagDecl = nullptr
TagDecl * MSGuidTagDecl = nullptr
llvm::DenseSet< const VarDecl * > CUDADeviceVarODRUsedByHost
Keep track of CUDA/HIP device-side variables ODR-used by host code.
llvm::DenseSet< const ValueDecl * > CUDAExternalDeviceDeclODRUsedByHost
Keep track of CUDA/HIP external kernels or device variables ODR-used by host code.
ComparisonCategories CompCategories
Types and expressions required to build C++2a three-way comparisons using operator<=>, including the values return by builtin <=> operators.
unsigned NumImplicitDefaultConstructors = 0
The number of implicitly-declared default constructors.
unsigned NumImplicitDefaultConstructorsDeclared = 0
The number of implicitly-declared default constructors for which declarations were built.
unsigned NumImplicitCopyConstructors = 0
The number of implicitly-declared copy constructors.
unsigned NumImplicitCopyConstructorsDeclared = 0
The number of implicitly-declared copy constructors for which declarations were built.
unsigned NumImplicitMoveConstructors = 0
The number of implicitly-declared move constructors.
unsigned NumImplicitMoveConstructorsDeclared = 0
The number of implicitly-declared move constructors for which declarations were built.
unsigned NumImplicitCopyAssignmentOperators = 0
The number of implicitly-declared copy assignment operators.
unsigned NumImplicitCopyAssignmentOperatorsDeclared = 0
The number of implicitly-declared copy assignment operators for which declarations were built.
unsigned NumImplicitMoveAssignmentOperators = 0
The number of implicitly-declared move assignment operators.
unsigned NumImplicitMoveAssignmentOperatorsDeclared = 0
The number of implicitly-declared move assignment operators for which declarations were built.
unsigned NumImplicitDestructors = 0
The number of implicitly-declared destructors.
unsigned NumImplicitDestructorsDeclared = 0
The number of implicitly-declared destructors for which declarations were built.
llvm::StringMap< SectionInfo > SectionInfos
Friends
class NestedNameSpecifier
class ASTDeclReader
class ASTReader
class ASTWriter
template<class >
class serialization::AbstractTypeReader
class CXXRecordDecl
class IncrementalParser
class DeclarationNameTable
class DeclContext
Detailed Description
Holds long-lived AST nodes (such as types and decls) that can be referred to throughout the semantic analysis of a file.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 182 of file ASTContext.h.
Member Typedef Documentation
import_range
using clang::ASTContext::import_range = llvm::iterator_range<import_iterator>
Definition at line 1015 of file ASTContext.h.
overridden_cxx_method_iterator
using clang::ASTContext::overridden_cxx_method_iterator = CXXMethodVector::const_iterator
Definition at line 977 of file ASTContext.h.
overridden_method_range
using clang::ASTContext::overridden_method_range
Initial value:
      llvm::iterator_range<overridden_cxx_method_iterator>
Definition at line 986 of file ASTContext.h.
TemplateOrSpecializationInfo
using clang::ASTContext::TemplateOrSpecializationInfo
Initial value:
      llvm::PointerUnion<VarTemplateDecl *, MemberSpecializationInfo *>
A type synonym for the TemplateOrInstantiation mapping.
Definition at line 461 of file ASTContext.h.
Member Enumeration Documentation
GetBuiltinTypeError
enum clang::ASTContext::GetBuiltinTypeError
Enumerator
GE_None
No error.
GE_Missing_type
Missing a type.
GE_Missing_stdio
Missing a type from <stdio.h>
GE_Missing_setjmp
Missing a type from <setjmp.h>
GE_Missing_ucontext
Missing a type from <ucontext.h>
Definition at line 2196 of file ASTContext.h.
InlineVariableDefinitionKind
enum class clang::ASTContext::InlineVariableDefinitionKind strong
Enumerator
None
Not an inline variable.
Weak
Weak definition of inline variable.
WeakUnknown
Weak for now, might become strong later in this TU.
Strong
Strong definition.
Definition at line 3270 of file ASTContext.h.
NeedExtraManglingDecl_t
enum clang::ASTContext::NeedExtraManglingDecl_t
Enumerator
NeedExtraManglingDecl
Definition at line 3105 of file ASTContext.h.
PragmaSectionFlag
enum clang::ASTContext::PragmaSectionFlag : unsigned
Enumerator
PSF_None
PSF_Read
PSF_Write
PSF_Execute
PSF_Implicit
PSF_ZeroInit
PSF_Invalid
Definition at line 3324 of file ASTContext.h.
Constructor & Destructor Documentation
ASTContext() [1/2]
ASTContext::ASTContext (LangOptions & LOpts, SourceManager & SM, IdentifierTable & idents, SelectorTable & sels, Builtin::Context & builtins, TranslationUnitKind TUKind)
Definition at line 923 of file ASTContext.cpp.
References addTranslationUnitDecl().
ASTContext() [2/2]
clang::ASTContext::ASTContext (const ASTContext &) delete
~ASTContext()
ASTContext::~ASTContext ()
Definition at line 983 of file ASTContext.cpp.
References cleanup().
Member Function Documentation
addComment()
void ASTContext::addComment (const RawComment & RC)
Definition at line 385 of file ASTContext.cpp.
References clang::RawCommentList::addComment(), clang::LangOptions::CommentOpts, Comments, clang::SourceRange::getBegin(), and clang::RawComment::getSourceRange().
Referenced by clang::Sema::ActOnComment().
addCopyConstructorForExceptionObject()
void ASTContext::addCopyConstructorForExceptionObject (CXXRecordDecl * RD, CXXConstructorDecl * CD)
Definition at line 12202 of file ASTContext.cpp.
References clang::Redeclarable< decl_type >::getFirstDecl().
Referenced by clang::Sema::CheckCXXThrowOperand().
AddDeallocation()
void ASTContext::AddDeallocation (void(* Callback)(void *), void * Data) const
Add a deallocation callback that will be invoked when the ASTContext is destroyed.
Parameters
Callback A callback function that will be invoked on destruction.
Data Pointer data that will be provided to the callback function when it is called.
Definition at line 990 of file ASTContext.cpp.
References Data.
Referenced by addDestruction().
addDeclaratorForUnnamedTagDecl()
void ASTContext::addDeclaratorForUnnamedTagDecl (TagDecl * TD, DeclaratorDecl * DD)
Definition at line 12219 of file ASTContext.cpp.
Referenced by clang::Sema::FinalizeDeclaratorGroup().
addDestruction()
template<typename T > void clang::ASTContext::addDestruction (T * Ptr) const inline
If T isn't trivially destructible, calls AddDeallocation to register it for destruction.
Definition at line 3057 of file ASTContext.h.
References AddDeallocation(), and V.
Referenced by clang::MSGuidDecl::getAsAPValue(), clang::LifetimeExtendedTemporaryDecl::getOrCreateValue(), clang::ConstantExpr::MoveIntoResult(), clang::ASTDeclReader::ReadVarDeclInit(), and clang::ASTDeclReader::VisitLifetimeExtendedTemporaryDecl().
addedLocalImportDecl()
void ASTContext::addedLocalImportDecl (ImportDecl * Import)
Notify the AST context that a new import declaration has been parsed or implicitly created within this translation unit.
Definition at line 1628 of file ASTContext.cpp.
Referenced by clang::DeclContext::addHiddenDecl().
addLazyModuleInitializers()
void ASTContext::addLazyModuleInitializers (Module * M, ArrayRef< uint32_t > IDs)
Definition at line 1134 of file ASTContext.cpp.
addModuleInitializer()
void ASTContext::addModuleInitializer (Module * M, Decl * Init)
Add a declaration to the list of declarations that are initialized for a module.
This will typically be a global variable (with internal linkage) that runs module initializers, such as the iostream initializer, or an ImportDecl nominating another module that has initializers.
Definition at line 1108 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnModuleImport(), clang::Sema::BuildModuleInclude(), and clang::Sema::CheckCompleteVariableDeclaration().
addOverriddenMethod()
void ASTContext::addOverriddenMethod (const CXXMethodDecl * Method, const CXXMethodDecl * Overridden)
Note that the given C++ Method overrides the given Overridden method.
Definition at line 1602 of file ASTContext.cpp.
References clang::Decl::isCanonicalDecl().
Referenced by clang::CXXMethodDecl::addOverriddenMethod(), and clang::ASTDeclReader::VisitCXXMethodDecl().
addressSpaceMapManglingFor()
bool clang::ASTContext::addressSpaceMapManglingFor (LangAS AS) const inline
Definition at line 2812 of file ASTContext.h.
References clang::isTargetAddressSpace().
addTranslationUnitDecl()
void clang::ASTContext::addTranslationUnitDecl () inline
Definition at line 1062 of file ASTContext.h.
References clang::TranslationUnitDecl::Create(), clang::Redeclarable< decl_type >::setPreviousDecl(), clang::TU_Incremental, and TUKind.
Referenced by ASTContext().
addTypedefNameForUnnamedTagDecl()
void ASTContext::addTypedefNameForUnnamedTagDecl (TagDecl * TD, TypedefNameDecl * TND)
Definition at line 12209 of file ASTContext.cpp.
Referenced by clang::Sema::setTagNameForLinkagePurposes().
adjustDeducedFunctionResultType()
void ASTContext::adjustDeducedFunctionResultType (FunctionDecl * FD, QualType ResultType)
Change the result type of a function type once it is deduced.
Definition at line 3179 of file ASTContext.cpp.
References clang::Type::castAs(), getASTMutationListener(), getFunctionType(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::ValueDecl::getType(), Next, and clang::ValueDecl::setType().
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::DeduceReturnType(), and clang::ASTReader::FinishedDeserializing().
adjustExceptionSpec()
void ASTContext::adjustExceptionSpec (FunctionDecl * FD, const FunctionProtoType::ExceptionSpecInfo & ESI, bool AsWritten = false)
Change the exception specification on a function once it is delay-parsed, instantiated, or computed.
Definition at line 3258 of file ASTContext.cpp.
References clang::TypeLoc::getFullDataSizeForType(), getFunctionTypeWithExceptionSpec(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), and clang::ValueDecl::setType().
Referenced by clang::Sema::actOnDelayedExceptionSpecification(), clang::ASTReader::FinishedDeserializing(), and clang::Sema::UpdateExceptionSpec().
adjustFunctionType()
const FunctionType * ASTContext::adjustFunctionType (const FunctionType * Fn, FunctionType::ExtInfo EInfo)
Change the ExtInfo on a function type.
Definition at line 3161 of file ASTContext.cpp.
References clang::cast(), clang::FunctionProtoType::ExtProtoInfo::ExtInfo, getFunctionNoProtoType(), getFunctionType(), and clang::Result.
Referenced by clang::Sema::adjustMemberFunctionCC(), clang::Sema::CheckMain(), clang::Sema::CheckMSVCRTEntryPoint(), handleFunctionTypeAttr(), clang::Sema::IsFunctionConversion(), and clang::Sema::MergeFunctionDecl().
adjustObjCTypeParamBoundType()
void ASTContext::adjustObjCTypeParamBoundType (const ObjCTypeParamDecl * Orig, ObjCTypeParamDecl * New) const
Definition at line 5511 of file ASTContext.cpp.
References clang::cast(), getObjCTypeParamType(), getTrivialTypeSourceInfo(), clang::TypeDecl::getTypeForDecl(), clang::QualType::getTypePtr(), clang::TypedefNameDecl::getUnderlyingType(), clang::TypeDecl::setTypeForDecl(), and clang::TypedefNameDecl::setTypeSourceInfo().
Referenced by checkTypeParamListConsistency().
adjustStringLiteralBaseType()
QualType ASTContext::adjustStringLiteralBaseType (QualType StrLTy) const
Definition at line 4582 of file ASTContext.cpp.
References getAddrSpaceQualType(), and clang::opencl_constant.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::BuildPredefinedExpr(), and getStringLiteralArrayType().
Allocate() [1/2]
template<typename T > T * clang::ASTContext::Allocate (size_t Num = 1) const inline
Definition at line 707 of file ASTContext.h.
References Allocate().
Allocate() [2/2]
void * clang::ASTContext::Allocate (size_t Size, unsigned Align = 8) const inline
Definition at line 704 of file ASTContext.h.
Referenced by Allocate(), clang::CallExpr::Create(), clang::CapturedStmt::Create(), clang::CaseStmt::Create(), clang::ConstantExpr::Create(), clang::CUDAKernelCallExpr::Create(), clang::CXXConstructExpr::Create(), clang::CXXDefaultInitExpr::Create(), clang::CXXDependentScopeMemberExpr::Create(), clang::CXXMemberCallExpr::Create(), clang::CXXNewExpr::Create(), clang::CXXOperatorCallExpr::Create(), clang::CXXTemporaryObjectExpr::Create(), clang::CXXUnresolvedConstructExpr::Create(), clang::DeclRefExpr::Create(), clang::DependentFunctionTemplateSpecializationInfo::Create(), clang::DependentScopeDeclRefExpr::Create(), clang::FunctionDecl::DefaultedFunctionInfo::Create(), clang::FunctionParmPackExpr::Create(), clang::GenericSelectionExpr::Create(), clang::GenericSelectionExpr::Create(), clang::GenericSelectionExpr::Create(), clang::GenericSelectionExpr::Create(), clang::IfStmt::Create(), clang::LambdaExpr::Create(), clang::ObjCAtTryStmt::Create(), clang::OMPArrayShapingExpr::Create(), clang::OMPIteratorExpr::Create(), clang::ParenListExpr::Create(), clang::PredefinedExpr::Create(), clang::PseudoObjectExpr::Create(), clang::RecoveryExpr::Create(), clang::ReturnStmt::Create(), clang::SizeOfPackExpr::Create(), clang::StringLiteral::Create(), clang::SwitchStmt::Create(), clang::UnresolvedLookupExpr::Create(), clang::UnresolvedLookupExpr::Create(), clang::UnresolvedMemberExpr::Create(), clang::UserDefinedLiteral::Create(), clang::WhileStmt::Create(), clang::ObjCTypeParamList::create(), clang::TemplateArgumentList::CreateCopy(), clang::CapturedStmt::CreateDeserialized(), clang::SizeOfPackExpr::CreateDeserialized(), clang::CallExpr::CreateEmpty(), clang::CaseStmt::CreateEmpty(), clang::ConstantExpr::CreateEmpty(), clang::CUDAKernelCallExpr::CreateEmpty(), clang::CXXConstructExpr::CreateEmpty(), clang::CXXDependentScopeMemberExpr::CreateEmpty(), clang::CXXMemberCallExpr::CreateEmpty(), clang::CXXNewExpr::CreateEmpty(), clang::CXXOperatorCallExpr::CreateEmpty(), clang::CXXTemporaryObjectExpr::CreateEmpty(), clang::CXXUnresolvedConstructExpr::CreateEmpty(), clang::DeclRefExpr::CreateEmpty(), clang::DependentScopeDeclRefExpr::CreateEmpty(), clang::FunctionParmPackExpr::CreateEmpty(), clang::GenericSelectionExpr::CreateEmpty(), clang::IfStmt::CreateEmpty(), clang::MemberExpr::CreateEmpty(), clang::ObjCAtTryStmt::CreateEmpty(), clang::OMPArrayShapingExpr::CreateEmpty(), clang::OMPIteratorExpr::CreateEmpty(), clang::ParenListExpr::CreateEmpty(), clang::PredefinedExpr::CreateEmpty(), clang::RecoveryExpr::CreateEmpty(), clang::ReturnStmt::CreateEmpty(), clang::StringLiteral::CreateEmpty(), clang::SwitchStmt::CreateEmpty(), clang::UnresolvedLookupExpr::CreateEmpty(), clang::UnresolvedMemberExpr::CreateEmpty(), clang::UserDefinedLiteral::CreateEmpty(), clang::WhileStmt::CreateEmpty(), getCanonicalTemplateSpecializationType(), getConstantArrayType(), getDeclAttrs(), getDependentTemplateSpecializationType(), getElaboratedType(), clang::ASTReader::GetExternalCXXBaseSpecifiers(), getObjCInterfaceType(), getObjCObjectPointerType(), getObjCObjectType(), getObjCTypeParamType(), getOverloadedTemplateName(), getSubstTemplateTypeParmType(), getTemplateSpecializationType(), getTypedefType(), getUsingType(), clang::NestedNameSpecifierLocBuilder::getWithLocInContext(), clang::Decl::operator new(), clang::Sema::SaveNestedNameSpecifierAnnotation(), clang::CXXRecordDecl::setCaptures(), and clang::TemplateArgument::TemplateArgument().
AllocateDeclListNode()
DeclListNode * clang::ASTContext::AllocateDeclListNode (clang::NamedDecl * ND) inline
Allocates a DeclListNode or returns one from the ListNodeFreeList pool.
Definition at line 714 of file ASTContext.h.
AnyObjCImplementation()
bool clang::ASTContext::AnyObjCImplementation () inline
Return true if there is at least one @implementation in the TU.
Definition at line 2993 of file ASTContext.h.
Referenced by clang::Sema::DiagnoseUseOfUnimplementedSelectors().
applyObjCProtocolQualifiers()
QualType ASTContext::applyObjCProtocolQualifiers (QualType type, ArrayRef< ObjCProtocolDecl * > protocols, bool & hasError, bool allowOnPointerType = false) const
Apply Objective-C protocol qualifiers to the given type.
Parameters
allowOnPointerType specifies if we can apply protocol qualifiers on ObjCObjectPointerType. It can be set to true when constructing the canonical type of a Objective-C type parameter.
If this is for the canonical type of a type parameter, we can apply protocol qualifiers on the ObjCObjectPointerType.
Definition at line 5410 of file ASTContext.cpp.
References getObjCObjectPointerType(), getObjCObjectType(), getObjCTypeParamType(), ObjCBuiltinClassTy, ObjCBuiltinIdTy, and clang::ast_matchers::type.
Referenced by clang::Sema::BuildObjCObjectType(), clang::Sema::BuildObjCTypeParamType(), and getObjCTypeParamType().
areCommonBaseCompatible()
QualType ASTContext::areCommonBaseCompatible (const ObjCObjectPointerType * LHSOPT, const ObjCObjectPointerType * RHSOPT)
Definition at line 10059 of file ASTContext.cpp.
References clang::Type::castAs(), clang::declaresSameEntity(), getIntersectionOfProtocols(), getObjCInterfaceType(), getObjCObjectPointerType(), getObjCObjectType(), clang::ObjCObjectPointerType::getObjectType(), clang::QualType::isNull(), clang::Result, and sameObjCTypeArgs().
Referenced by clang::Sema::FindCompositeObjCPointerType().
areComparableObjCPointerTypes()
bool ASTContext::areComparableObjCPointerTypes (QualType LHS, QualType RHS)
Definition at line 10244 of file ASTContext.cpp.
References canAssignObjCInterfaces(), and clang::Type::getAs().
Referenced by clang::Sema::CheckCompareOperands().
areCompatibleRVVTypes()
bool ASTContext::areCompatibleRVVTypes (QualType FirstType, QualType SecondType)
Return true if the given types are an RISC-V vector builtin type and a VectorType that is a fixed-length representation of the RISC-V vector builtin type for a specific vector-length.
Definition at line 9568 of file ASTContext.cpp.
References clang::VectorType::GenericVector, clang::Type::getAs(), getBuiltinVectorTypeInfo(), getRVVTypeSize(), getTypeSize(), hasSameType(), clang::Type::isRVVSizelessBuiltinType(), clang::Type::isRVVVLSBuiltinType(), clang::Type::isVectorType(), and clang::VectorType::RVVFixedLengthDataVector.
Referenced by clang::Sema::CheckAssignmentConstraints(), CheckImplicitConversion(), CompareStandardConversionSequences(), and IsVectorConversion().
areCompatibleSveTypes()
bool ASTContext::areCompatibleSveTypes (QualType FirstType, QualType SecondType)
Return true if the given types are an SVE builtin and a VectorType that is a fixed-length representation of the SVE builtin for a specific vector-length.
Definition at line 9471 of file ASTContext.cpp.
References clang::VectorType::GenericVector, clang::Type::getAs(), getBuiltinVectorTypeInfo(), clang::Type::getSveEltType(), getSVETypeSize(), getTypeSize(), hasSameType(), clang::Type::isSVESizelessBuiltinType(), clang::Type::isVectorType(), clang::VectorType::SveFixedLengthDataVector, and clang::VectorType::SveFixedLengthPredicateVector.
Referenced by clang::Sema::CheckAssignmentConstraints(), CheckImplicitConversion(), CompareStandardConversionSequences(), and IsVectorConversion().
areCompatibleVectorTypes()
bool ASTContext::areCompatibleVectorTypes (QualType FirstVec, QualType SecondVec)
Return true if the given vector types are of the same unqualified type or if they are equivalent to the same GCC vector type.
Note
This ignores whether they are target-specific (AltiVec or Neon) types.
Definition at line 9433 of file ASTContext.cpp.
References clang::VectorType::AltiVecBool, clang::VectorType::AltiVecPixel, clang::Type::castAs(), clang::First, clang::VectorType::getElementType(), clang::VectorType::getNumElements(), clang::VectorType::getVectorKind(), hasSameType(), hasSameUnqualifiedType(), clang::Type::isVectorType(), clang::VectorType::RVVFixedLengthDataVector, clang::VectorType::SveFixedLengthDataVector, and clang::VectorType::SveFixedLengthPredicateVector.
Referenced by clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckVectorOperands(), CompareStandardConversionSequences(), clang::Sema::IsPointerConversion(), and IsVectorConversion().
areLaxCompatibleRVVTypes()
bool ASTContext::areLaxCompatibleRVVTypes (QualType FirstType, QualType SecondType)
Return true if the given vector types are lax-compatible RISC-V vector types as defined by -flax-vector-conversions=, which permits implicit conversions between vectors with different number of elements and/or incompatible element types, false otherwise.
Definition at line 9593 of file ASTContext.cpp.
References clang::LangOptions::All, clang::VectorType::GenericVector, clang::Type::getAs(), getLangOpts(), clang::Type::getRVVEltType(), getRVVTypeSize(), getTypeSize(), clang::LangOptions::Integer, clang::Type::isIntegerType(), clang::Type::isRVVSizelessBuiltinType(), clang::Type::isVectorType(), and clang::VectorType::RVVFixedLengthDataVector.
Referenced by clang::Sema::CheckAssignmentConstraints(), CheckImplicitConversion(), and IsVectorConversion().
areLaxCompatibleSveTypes()
bool ASTContext::areLaxCompatibleSveTypes (QualType FirstType, QualType SecondType)
Return true if the given vector types are lax-compatible SVE vector types, false otherwise.
Definition at line 9501 of file ASTContext.cpp.
References clang::LangOptions::All, clang::VectorType::GenericVector, clang::Type::getAs(), getLangOpts(), clang::Type::getSveEltType(), getSVETypeSize(), getTypeSize(), clang::LangOptions::Integer, clang::Type::isIntegerType(), clang::Type::isSVESizelessBuiltinType(), clang::Type::isVectorType(), and clang::VectorType::SveFixedLengthDataVector.
Referenced by clang::Sema::CheckAssignmentConstraints(), CheckImplicitConversion(), and IsVectorConversion().
AtomicUsesUnsupportedLibcall()
bool ASTContext::AtomicUsesUnsupportedLibcall (const AtomicExpr * E) const
Definition at line 12319 of file ASTContext.cpp.
References clang::TargetInfo::getMaxAtomicInlineWidth(), clang::Type::getPointeeType(), clang::AtomicExpr::getPtr(), clang::CharUnits::getQuantity(), getTargetInfo(), clang::TargetInfo::getTriple(), clang::Expr::getType(), getTypeAlignInChars(), getTypeSizeInChars(), and toBits().
Referenced by clang::Sema::BuildAtomicExpr().
attachCommentsToJustParsedDecls()
void ASTContext::attachCommentsToJustParsedDecls (ArrayRef< Decl * > Decls, const Preprocessor * PP)
Searches existing comments for doc comments that should be attached to Decls.
If any doc comment is found, it is parsed.
Requirement: All Decls are in the same file.
If the last comment in the file is already attached we assume there are not comments left to be attached to Decls.
Definition at line 555 of file ASTContext.cpp.
References adjustDeclToTemplate(), cacheRawCommentForDecl(), Comments, DeclRawComments, clang::RawCommentList::empty(), clang::File, clang::RawCommentList::getCommentsInFile(), getDeclLocForCommentSearch(), getRawCommentForDeclNoCacheImpl(), clang::SourceLocation::isFileID(), clang::SourceLocation::isInvalid(), and ParsedComments.
Referenced by clang::Sema::ActOnDocumentableDecls().
BlockRequiresCopying()
bool ASTContext::BlockRequiresCopying (QualType Ty, const VarDecl * D)
Returns true iff we need copy/dispose helpers for the given type.
BlockRequiresCopying - Returns true if byref variable "D" of type "Ty" requires copy/dispose.
Note that this must match the logic in buildByrefHelpers.
Definition at line 7533 of file ASTContext.cpp.
References clang::Type::getAsCXXRecordDecl(), getBlockVarCopyInit(), clang::BlockVarCopyInit::getCopyExpr(), clang::Qualifiers::getObjCLifetime(), clang::QualType::getQualifiers(), clang::Type::isBlockPointerType(), clang::QualType::isDestructedType(), clang::QualType::isNonTrivialToPrimitiveDestructiveMove(), isObjCNSObjectType(), clang::Type::isObjCObjectPointerType(), clang::Type::isObjCRetainableType(), clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, and clang::Qualifiers::OCL_Weak.
buildBuiltinTemplateDecl()
BuiltinTemplateDecl * ASTContext::buildBuiltinTemplateDecl (BuiltinTemplateKind BTK, const IdentifierInfo * II) const
Definition at line 1167 of file ASTContext.cpp.
References clang::DeclContext::addDecl(), clang::BuiltinTemplateDecl::Create(), and getTranslationUnitDecl().
Referenced by getMakeIntegerSeqDecl(), and getTypePackElementDecl().
buildImplicitRecord()
RecordDecl * ASTContext::buildImplicitRecord (StringRef Name, RecordDecl::TagKind TK = TTK_Struct) const
Create a new implicit TU-level CXXRecordDecl or RecordDecl declaration.
Definition at line 1193 of file ASTContext.cpp.
References clang::Decl::addAttr(), clang::CPlusPlus, clang::CXXRecordDecl::Create(), clang::RecordDecl::Create(), clang::IdentifierTable::get(), getLangOpts(), getTranslationUnitDecl(), Idents, and clang::Decl::setImplicit().
Referenced by CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), getBlockDescriptorExtendedType(), getBlockDescriptorType(), getCFConstantStringDecl(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getObjCSuperType(), InitBuiltinTypes(), and clang::Sema::Initialize().
buildImplicitTypedef()
TypedefDecl * ASTContext::buildImplicitTypedef (QualType T, StringRef Name) const
Create a new implicit TU-level typedef declaration.
Definition at line 1209 of file ASTContext.cpp.
References clang::TypedefDecl::Create(), clang::IdentifierTable::get(), getTranslationUnitDecl(), getTrivialTypeSourceInfo(), Idents, and clang::Decl::setImplicit().
Referenced by clang::Sema::addImplicitTypedef(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateCharPtrNamedVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePNaClABIBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateVoidPtrBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), getCFConstantStringDecl(), getInt128Decl(), getObjCClassDecl(), getObjCIdDecl(), getObjCInstanceTypeDecl(), getObjCSelDecl(), and getUInt128Decl().
cacheRawCommentForDecl()
void ASTContext::cacheRawCommentForDecl (const Decl & OriginalD, const RawComment & Comment) const
Attaches Comment to OriginalD and to its redeclaration chain and removes the redeclaration chain from the set of commentless chains.
Don't do anything if a comment has already been attached to OriginalD or its redeclaration chain.
Definition at line 529 of file ASTContext.cpp.
References CommentlessRedeclChains, clang::LangOptions::CommentOpts, DeclRawComments, clang::Decl::getCanonicalDecl(), clang::RawComment::isDocumentation(), clang::CommentOptions::ParseAllComments, and RedeclChainComments.
Referenced by attachCommentsToJustParsedDecls(), and getRawCommentForAnyRedecl().
canAssignObjCInterfaces() [1/2]
bool ASTContext::canAssignObjCInterfaces (const ObjCObjectPointerType * LHSOPT, const ObjCObjectPointerType * RHSOPT)
canAssignObjCInterfaces - Return true if the two interface types are compatible for assignment from RHS to LHS.
This handles validation of any protocol qualifiers on the LHS or RHS.
Definition at line 9813 of file ASTContext.cpp.
References canAssignObjCInterfaces(), clang::ObjCObjectPointerType::getObjectType(), ObjCQualifiedClassTypesAreCompatible(), ObjCQualifiedIdTypesAreCompatible(), and clang::ObjCObjectPointerType::stripObjCKindOfTypeAndQuals().
Referenced by clang::Sema::ActOnPropertyImplDecl(), applyObjCTypeArgs(), areComparableObjCPointerTypes(), canAssignObjCInterfaces(), canAssignObjCObjectTypes(), canBindObjCObjectType(), CompareDerivedToBaseConversions(), CompareStandardConversionSequences(), clang::Sema::DiagnosePropertyAccessorMismatch(), clang::Sema::FindCompositeObjCPointerType(), findMethodDecl(), clang::Sema::isObjCPointerConversion(), isObjCTypeSubstitutable(), and mergeTypes().
canAssignObjCInterfaces() [2/2]
bool ASTContext::canAssignObjCInterfaces (const ObjCObjectType * LHS, const ObjCObjectType * RHS)
Definition at line 10182 of file ASTContext.cpp.
References CollectInheritedProtocols(), clang::declaresSameEntity(), clang::ObjCInterfaceDecl::isSuperClassOf(), and sameObjCTypeArgs().
canAssignObjCInterfacesInBlockPointer()
bool ASTContext::canAssignObjCInterfacesInBlockPointer (const ObjCObjectPointerType * LHSOPT, const ObjCObjectPointerType * RHSOPT, bool BlockReturnType)
canAssignObjCInterfacesInBlockPointer - This routine is specifically written for providing type-safety for objective-c pointers used to pass/return arguments in block literals.
When passed as arguments, passing 'A*' where 'id' is expected is not OK. Passing 'Sub *" where 'Super *" is expected is not OK. For the return type, the opposite is not OK.
Definition at line 9866 of file ASTContext.cpp.
References canAssignObjCInterfacesInBlockPointer(), clang::ObjCInterfaceType::getDecl(), clang::ObjCObjectPointerType::getInterfaceType(), getLangOpts(), clang::Type::isObjCBuiltinType(), clang::ObjCObjectPointerType::isObjCIdType(), clang::ObjCObjectPointerType::isObjCQualifiedIdType(), clang::ObjCInterfaceDecl::isSuperClassOf(), ObjCQualifiedIdTypesAreCompatible(), and clang::ObjCObjectPointerType::stripObjCKindOfTypeAndQuals().
Referenced by canAssignObjCInterfacesInBlockPointer(), and mergeTypes().
canBindObjCObjectType()
bool ASTContext::canBindObjCObjectType (QualType To, QualType From)
Definition at line 10256 of file ASTContext.cpp.
References canAssignObjCInterfaces(), and getObjCObjectPointerType().
Referenced by clang::Sema::CompareReferenceRelationship().
canBuiltinBeRedeclared()
bool ASTContext::canBuiltinBeRedeclared (const FunctionDecl * FD) const
Return whether a declaration to a builtin is allowed to be overloaded/redeclared.
Definition at line 9169 of file ASTContext.cpp.
References BuiltinInfo, clang::Builtin::Context::canBeRedeclared(), clang::FunctionDecl::getBuiltinID(), clang::Builtin::Context::hasCustomTypechecking(), and clang::Builtin::NotBuiltin.
cleanup()
void ASTContext::cleanup ()
Definition at line 944 of file ASTContext.cpp.
References clang::Value::clear().
Referenced by ~ASTContext().
cloneFullComment()
comments::FullComment * ASTContext::cloneFullComment (comments::FullComment * FC, const Decl * D) const
Definition at line 611 of file ASTContext.cpp.
References clang::comments::DeclInfo::CommentDecl, clang::comments::FullComment::getBlocks(), clang::comments::FullComment::getDecl(), clang::comments::FullComment::getDeclInfo(), and clang::comments::DeclInfo::TemplateParameters.
Referenced by getCommentForDecl().
CollectInheritedProtocols()
void ASTContext::CollectInheritedProtocols (const Decl * CDecl, llvm::SmallPtrSet< ObjCProtocolDecl *, 8 > & Protocols)
CollectInheritedProtocols - Collect all protocols in current class and those inherited by it.
Definition at line 2627 of file ASTContext.cpp.
References CollectInheritedProtocols(), and clang::ObjCInterfaceDecl::getSuperClass().
Referenced by clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), canAssignObjCInterfaces(), CollectInheritedProtocols(), getIntersectionOfProtocols(), ObjCQualifiedIdTypesAreCompatible(), and QIdProtocolsAdoptObjCObjectProtocols().
CountNonClassIvars()
unsigned ASTContext::CountNonClassIvars (const ObjCInterfaceDecl * OI) const
Definition at line 2881 of file ASTContext.cpp.
References clang::ObjCInterfaceDecl::getImplementation(), and clang::ObjCInterfaceDecl::known_extensions().
createDeviceMangleContext()
MangleContext * ASTContext::createDeviceMangleContext (const TargetInfo & T)
Creates a device mangle context to correctly mangle lambdas in a mixed architecture compile by setting the lambda mangling number source to the DeviceLambdaManglingNumber.
Currently this asserts that the TargetInfo (from the AuxTargetInfo) is a an itanium target.
Definition at line 12055 of file ASTContext.cpp.
References clang::ItaniumMangleContext::create(), clang::MicrosoftMangleContext::create(), and getDiagnostics().
Referenced by InitDeviceMC().
createMangleContext()
MangleContext * ASTContext::createMangleContext (const TargetInfo * T = nullptr)
If T is null pointer, assume the target in ASTContext.
Definition at line 12034 of file ASTContext.cpp.
References clang::ItaniumMangleContext::create(), clang::MicrosoftMangleContext::create(), and getDiagnostics().
Referenced by clang::PredefinedExpr::ComputeName(), clang::ASTNameGenerator::Implementation::getAllManglings(), and InitDeviceMC().
createMangleNumberingContext()
std::unique_ptr< MangleNumberingContext > ASTContext::createMangleNumberingContext () const
Definition at line 12192 of file ASTContext.cpp.
Referenced by getManglingNumberContext(), and getManglingNumberContext().
CreateTypeSourceInfo()
TypeSourceInfo * ASTContext::CreateTypeSourceInfo (QualType T, unsigned Size = 0) const
Allocate an uninitialized TypeSourceInfo.
The caller should initialize the memory held by TypeSourceInfo using the TypeLoc wrappers.
Parameters
T the type that will be the basis for type source info. This type should refer to how the declarator was written in source code, not to what type semantic analysis resolved the declarator to.
Size the size of the type info to create, or 0 if the size should be calculated based on the type.
Definition at line 2991 of file ASTContext.cpp.
References clang::TypeLoc::getFullDataSizeForType().
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::actOnObjCProtocolQualifierType(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::ActOnTemplatedFriendTag(), clang::Sema::BuildMemInitializer(), clang::Sema::CheckTypenameType(), getTemplateSpecializationTypeInfo(), getTrivialTypeSourceInfo(), GetTypeSourceInfoForDeclarator(), and clang::ASTDeclReader::VisitDeclaratorDecl().
Deallocate()
void clang::ASTContext::Deallocate (void * Ptr) const inline
Definition at line 710 of file ASTContext.h.
Referenced by clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::AttachBaseSpecifiers(), clang::VarDecl::setInit(), clang::TagDecl::setQualifierInfo(), and clang::QualifierInfo::setTemplateParameterListsInfo().
DeallocateDeclListNode()
void clang::ASTContext::DeallocateDeclListNode (DeclListNode * N) inline
Deallcates a DeclListNode by returning it to the ListNodeFreeList pool.
Definition at line 725 of file ASTContext.h.
References N.
DeclMustBeEmitted()
bool ASTContext::DeclMustBeEmitted (const Decl * D)
Determines if the decl can be CodeGen'ed or deserialized from PCH lazily, only when used; this is only relevant for function or file scoped var definitions.
Returns
true if the function/var must be CodeGen'ed/deserialized even if it is not used.
Definition at line 11836 of file ASTContext.cpp.
References clang::cast(), clang::VarDecl::DeclarationOnly, DeclMustBeEmitted(), clang::CXXMethodDecl::getCanonicalDecl(), getCurrentKeyFunction(), clang::Decl::getDeclContext(), GetGVALinkageForFunction(), GetGVALinkageForVariable(), clang::DeclContext::getParent(), getTargetInfo(), clang::GVA_AvailableExternally, clang::Decl::hasAttr(), clang::DeclContext::isDependentContext(), clang::isDiscardableGVALinkage(), clang::CXXRecordDecl::isDynamicClass(), isMSStaticDataMemberInlineDefinition(), clang::SC_Register, and clang::FunctionDecl::TK_FunctionTemplate.
Referenced by clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::checkOpenMPDeclareVariantFunction(), DeclMustBeEmitted(), isConsumerInterestedIn(), isRequiredDecl(), and clang::Sema::ShouldWarnIfUnusedFileScopedDecl().
DecodeTypeStr()
QualType ASTContext::DecodeTypeStr (const char *& Str, const ASTContext & Context, ASTContext::GetBuiltinTypeError & Error, bool & RequireICE, bool AllowTypeModifiers) const
Definition at line 11562 of file ASTContext.cpp.
References DecodeTypeFromStr().
Referenced by DecodePPCMMATypeFromStr().
deduplicateMergedDefinitonsFor()
void ASTContext::deduplicateMergedDefinitonsFor (NamedDecl * ND)
Clean up the merged definition list.
Call this if you might have added duplicates into the list.
Definition at line 1069 of file ASTContext.cpp.
References clang::Decl::getCanonicalDecl().
DeepCollectObjCIvars()
void ASTContext::DeepCollectObjCIvars (const ObjCInterfaceDecl * OI, bool leafClass, SmallVectorImpl< const ObjCIvarDecl * > & Ivars) const
DeepCollectObjCIvars - This routine first collects all declared, but not synthesized, ivars in super class and then collects all ivars, including those synthesized for current class.
This routine is used for implementation of current class when all ivars, declared and synthesized are known.
Definition at line 2610 of file ASTContext.cpp.
References DeepCollectObjCIvars(), clang::ObjCIvarDecl::getNextIvar(), clang::ObjCInterfaceDecl::getSuperClass(), and clang::ObjCInterfaceDecl::ivars().
Referenced by clang::Sema::ActOnDefs(), and DeepCollectObjCIvars().
DumpRecordLayout()
void ASTContext::DumpRecordLayout (const RecordDecl * RD, raw_ostream & OS, bool Simple = false) const
Definition at line 3698 of file RecordLayoutBuilder.cpp.
References DumpRecordLayout(), clang::ASTRecordLayout::getAlignment(), clang::ASTRecordLayout::getDataSize(), clang::ASTRecordLayout::getFieldCount(), clang::ASTRecordLayout::getFieldOffset(), clang::ASTRecordLayout::getPreferredAlignment(), clang::ASTRecordLayout::getSize(), and isMsLayout().
eraseDeclAttrs()
void ASTContext::eraseDeclAttrs (const Decl * D)
Erase the attributes corresponding to the given declaration.
Definition at line 1477 of file ASTContext.cpp.
Referenced by clang::Decl::dropAttrs().
filterFunctionTargetAttrs()
ParsedTargetAttr ASTContext::filterFunctionTargetAttrs (const TargetAttr * TD) const
Parses the target attributes passed in, and returns only the ones that are valid feature names.
Definition at line 13476 of file ASTContext.cpp.
Referenced by getFunctionFeatureMap().
filterFunctionTargetVersionAttrs()
std::vector< std::string > ASTContext::filterFunctionTargetVersionAttrs (const TargetVersionAttr * TV) const
Definition at line 13462 of file ASTContext.cpp.
Referenced by getFunctionFeatureMap().
forEachMultiversionedFunctionVersion()
void ASTContext::forEachMultiversionedFunctionVersion (const FunctionDecl * FD, llvm::function_ref< void(FunctionDecl *)> Pred) const
Visits all versions of a multiversioned function with the passed predicate.
Definition at line 11956 of file ASTContext.cpp.
References clang::Decl::getAsFunction(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::DeclContext::getRedeclContext(), clang::ValueDecl::getType(), hasSameType(), clang::FunctionDecl::isMultiVersion(), and clang::DeclContext::lookup().
Referenced by clang::Sema::PerformPendingInstantiations().
getAddrSpaceQualType()
QualType ASTContext::getAddrSpaceQualType (QualType T, LangAS AddressSpace) const
Return the uniqued reference to the type for an address space qualified type with the specified type and address space.
The resulting type has a union of the qualifiers from T and the address space. If T already has an address space specifier, it is silently replaced.
Definition at line 3069 of file ASTContext.cpp.
References clang::Qualifiers::addAddressSpace(), clang::QualType::getAddressSpace(), getCanonicalType(), clang::Qualifiers::hasAddressSpace(), and clang::QualifierCollector::strip().
Referenced by clang::Sema::ActOnVariableDeclarator(), AdjustAddressSpaceForBuiltinOperandType(), AdjustFunctionParmAndArgTypesForDeduction(), adjustStringLiteralBaseType(), clang::Sema::BuildAddressSpaceAttr(), clang::Sema::BuildAtomicExpr(), checkConditionalPointerCompatibility(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), DecodeTypeFromStr(), clang::Sema::deduceOpenCLAddressSpace(), deduceOpenCLPointeeAddrSpace(), clang::CodeGen::CodeGenTypes::DeriveThisType(), HandleAddressSpaceTypeAttribute(), handleMSPointerTypeQualifierAttr(), HandleWebAssemblyFuncrefAttr(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectMemberConversion(), clang::TreeTransform< Derived >::RebuildQualifiedType(), rewriteBuiltinFunctionDecl(), and clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter().
getAdjustedParameterType()
QualType ASTContext::getAdjustedParameterType (QualType T) const
Perform adjustment on the parameter type of a function.
This routine adjusts the given parameter type T to the actual parameter type used by semantic analysis (C99 6.7.5.3p[7,8], C++ [dcl.fct]p3). The adjusted parameter type is returned.
Definition at line 6937 of file ASTContext.cpp.
References getDecayedType().
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::BuildFunctionType(), clang::Sema::CheckParameter(), DeduceNonTypeTemplateArgument(), and getSignatureParameterType().
getAdjustedType() [1/2]
CanQualType clang::ASTContext::getAdjustedType (CanQualType Orig, CanQualType New) const inline
Definition at line 1330 of file ASTContext.h.
References clang::CanQual< Type >::CreateUnsafe(), and getAdjustedType().
getAdjustedType() [2/2]
QualType ASTContext::getAdjustedType (QualType Orig, QualType New) const
Return the uniqued reference to a type adjusted from the original type to a new type.
Definition at line 3342 of file ASTContext.cpp.
References getCanonicalType(), clang::AdjustedType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::adjustMemberFunctionCC(), getAdjustedType(), and getCommonSugarTypeNode().
getAlignOfGlobalVar()
unsigned ASTContext::getAlignOfGlobalVar (QualType T) const
Return the alignment in bits that should be given to a global variable with type T.
getAlignOfGlobalVar - Return the alignment in bits that should be given to a global variable of the specified type.
Definition at line 2564 of file ASTContext.cpp.
References getPreferredTypeAlign(), getTargetInfo(), and getTypeSize().
Referenced by getAlignOfGlobalVarInChars().
getAlignOfGlobalVarInChars()
CharUnits ASTContext::getAlignOfGlobalVarInChars (QualType T) const
Return the alignment in characters that should be given to a global variable with type T.
getAlignOfGlobalVarInChars - Return the alignment in characters that should be given to a global variable of the specified type.
Definition at line 2572 of file ASTContext.cpp.
References getAlignOfGlobalVar(), and toCharUnitsFromBits().
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromLiteral(), and clang::Sema::isOpenMPCapturedByRef().
getAllocator()
llvm::BumpPtrAllocator & clang::ASTContext::getAllocator () const inline
Definition at line 700 of file ASTContext.h.
Referenced by clang::CXXCtorInitializer::getID(), clang::Decl::getID(), clang::Stmt::getID(), and clang::RawComment::parse().
getArrayDecayedType()
QualType ASTContext::getArrayDecayedType (QualType Ty) const
Return the properly qualified result of decaying the specified array type to a pointer.
getArrayDecayedType - Return the properly qualified result of decaying the specified array type to a pointer.
This operation is non-trivial when handling typedefs etc. The canonical type of T must be an array type, this returns a pointer to a properly qualified element of the array.
See C99 6.7.5.3p7 and C99 6.3.2.1p3.
This operation is non-trivial when handling typedefs etc. The canonical type of "T" must be an array type, this returns a pointer to a properly qualified element of the array.
See C99 6.7.5.3p7 and C99 6.3.2.1p3.
Definition at line 6968 of file ASTContext.cpp.
References getAsArrayType(), getAttributedType(), clang::ArrayType::getElementType(), clang::ArrayType::getIndexTypeQualifiers(), clang::Type::getNullability(), getPointerType(), getQualifiedType(), and clang::Result.
Referenced by clang::Sema::ActOnStringLiteral(), BuildCookedLiteralOperatorCall(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckSpecifiedExceptionType(), CheckTemplateArgumentAddressOfObjectOrFunction(), CompareDerivedToBaseConversions(), CompareStandardConversionSequences(), clang::Sema::CreateBuiltinArraySubscriptExpr(), DecodeTypeFromStr(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DiagnoseAssignmentResult(), doRewriteToUTF8StringBoxedExpressionHelper(), GetBuiltinType(), getCanonicalParamType(), getDecayedType(), clang::StandardConversionSequence::isPointerConversionToVoidPointer(), IsStandardConversion(), and clang::Sema::PerformImplicitConversion().
getArrayInitLoopExprElementCount()
uint64_t ASTContext::getArrayInitLoopExprElementCount (const ArrayInitLoopExpr * AILE) const
Return number of elements initialized in an ArrayInitLoopExpr.
Definition at line 7020 of file ASTContext.cpp.
References clang::ArrayInitLoopExpr::getArraySize(), and clang::ArrayInitLoopExpr::getSubExpr().
getAsArrayType()
const ArrayType * ASTContext::getAsArrayType (QualType T) const
Type Query functions.
If the type is an instance of the specified class, return the Type pointer for the underlying maximally pretty type. This is a member of ASTContext because this may need to do some amount of canonicalization, e.g. to move type qualifiers into the element type.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 6879 of file ASTContext.cpp.
References clang::cast(), clang::Qualifiers::empty(), getConstantArrayType(), getDependentSizedArrayType(), getIncompleteArrayType(), getQualifiedType(), getVariableArrayType(), clang::SplitQualType::Quals, and clang::SplitQualType::Ty.
Referenced by clang::Sema::ActOnFields(), actOnOMPReductionKindClause(), clang::Sema::ActOnStartCXXMemberReference(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuiltinRemoveExtent(), clang::Sema::CheckAllocatedType(), checkFormatStringExpr(), clang::Sema::CheckStaticArrayArgument(), DeduceFromInitializerList(), clang::Sema::deduceOpenCLAddressSpace(), DeduceTemplateArgumentsByTypeMatch(), diagnoseArrayStarInParamType(), DiagnoseDivisionSizeofPointerOrArray(), clang::CodeGen::ReductionCodeGen::emitInitialization(), emitPartialArrayDestroy(), EvaluateArrayTypeTrait(), clang::Sema::FillInlineAsmIdentifierInfo(), clang::Sema::FindCompositePointerType(), getArrayDecayedType(), getAsConstantArrayType(), getAsDependentSizedArrayType(), getAsIncompleteArrayType(), getAsVariableArrayType(), getDeclAlign(), clang::CFGImplicitDtor::getDestructorDecl(), getLValueType(), clang::ento::MemRegionManager::getStaticSize(), handleInitPriorityAttr(), clang::ASTNodeImporter::ImportAPValue(), clang::InitializationSequence::InitializeFrom(), isDesignatorAtObjectEnd(), isSameEntity(), IsStringInit(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), mergeTypes(), clang::Sema::MergeVarDeclTypes(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), TryListConversion(), TryListInitialization(), tryObjCWritebackConversion(), TryOrBuildParenListInitialization(), TypeRequiresBuiltinLaunderImp(), unwrapCastAwayConstnessLevel(), UnwrapSimilarArrayTypes(), and clang::ASTNodeImporter::VisitVarDecl().
getAsConstantArrayType()
const ConstantArrayType * clang::ASTContext::getAsConstantArrayType (QualType T) const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2717 of file ASTContext.h.
References getAsArrayType().
Referenced by clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), BitsContainNoUserData(), clang::Sema::BuildCXXNew(), buildSingleCopyAssignRecursively(), clang::Sema::CheckCompleteDecompositionDeclaration(), CheckFormatString(), clang::Sema::CheckStaticArrayArgument(), CompareImplicitConversionSequences(), DeduceTemplateArgumentsByTypeMatch(), EmitCXXNewAllocSize(), EmitMemberInitializer(), clang::CodeGen::CodeGenModule::EmitNullConstant(), EquivalentArrayTypes(), EvaluateArrayTypeTrait(), evenFlexibleArraySize(), expandStringLiteral(), extractStringLiteralCharacter(), findSubobject(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::Sema::FormatStringHasSArg(), clang::CodeGen::CodeGenModule::GetConstantArrayFromStringLiteral(), clang::VarDecl::getFlexibleArrayInitChars(), getTypeExpansion(), HandleDestructionImpl(), clang::VarDecl::hasFlexibleArrayInit(), isConstantSizeArrayWithMoreThanOneElement(), clang::CodeGen::isEmptyField(), clang::Expr::isFlexibleArrayMemberLike(), isIncompleteOrZeroLengthArrayType(), clang::CodeGen::isSingleElementStruct(), isValidStructGUID(), isZeroSizedArray(), mergeTypes(), clang::Sema::ParseObjCStringLiteral(), clang::InitializationSequence::Perform(), populateInitializerFixItWithSpan(), setUsedBits(), and TryOrBuildParenListInitialization().
getAsDependentSizedArrayType()
const DependentSizedArrayType * clang::ASTContext::getAsDependentSizedArrayType (QualType T) const inline
Definition at line 2726 of file ASTContext.h.
References getAsArrayType().
Referenced by DeduceTemplateArgumentsByTypeMatch().
getAsIncompleteArrayType()
const IncompleteArrayType * clang::ASTContext::getAsIncompleteArrayType (QualType T) const inline
Definition at line 2723 of file ASTContext.h.
References getAsArrayType().
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::AddInitializerToDecl(), DeduceTemplateArgumentsByTypeMatch(), clang::Expr::isFlexibleArrayMemberLike(), and clang::InitializationSequence::Perform().
getAssumedTemplateName()
TemplateName ASTContext::getAssumedTemplateName (DeclarationName Name) const
Retrieve a template name representing an unqualified-id that has been assumed to name a template for ADL purposes.
Definition at line 9211 of file ASTContext.cpp.
Referenced by clang::Sema::ClassifyName(), clang::ASTImporter::Import(), and clang::Sema::isTemplateName().
getASTAllocatedMemory()
size_t clang::ASTContext::getASTAllocatedMemory () const inline
Return the total amount of physical memory allocated for representing AST nodes and type information.
Definition at line 732 of file ASTContext.h.
getASTMutationListener()
ASTMutationListener * clang::ASTContext::getASTMutationListener () const inline
Retrieve a pointer to the AST mutation listener associated with this AST context, if any.
Definition at line 1181 of file ASTContext.h.
References Listener.
Referenced by clang::Sema::ActOnOpenMPDeclareTargetName(), adjustDeducedFunctionResultType(), applyOMPAllocateAttribute(), clang::Sema::checkDeclIsAllowedInOpenMPTarget(), clang::Sema::CheckOMPThreadPrivateDecl(), clang::Decl::getASTMutationListener(), and mergeDefinitionIntoModule().
getASTObjCImplementationLayout()
const ASTRecordLayout & ASTContext::getASTObjCImplementationLayout (const ObjCImplementationDecl * D) const
Get or compute information about the layout of the specified Objective-C implementation.
This may differ from the interface if synthesized ivars are present.
Definition at line 3018 of file ASTContext.cpp.
References clang::ObjCImplDecl::getClassInterface().
getASTObjCInterfaceLayout()
const ASTRecordLayout & ASTContext::getASTObjCInterfaceLayout (const ObjCInterfaceDecl * D) const
Get or compute information about the layout of the specified Objective-C interface.
Definition at line 3013 of file ASTContext.cpp.
Referenced by getTypeUnadjustedAlign().
getASTRecordLayout()
const ASTRecordLayout & ASTContext::getASTRecordLayout (const RecordDecl * D) const
Get or compute information about the layout of the specified record (struct/union/class) D, which indicates its size and field position information.
getASTRecordLayout - Get or compute information about the layout of the specified record (struct/union/class), which indicates its size and field position information.
Definition at line 3282 of file RecordLayoutBuilder.cpp.
References DumpRecordLayout(), clang::CharUnits::fromQuantity(), clang::RecordDecl::getDefinition(), clang::RecordDecl::getMostRecentDecl(), clang::DeclContext::hasExternalLexicalStorage(), clang::TagDecl::isCompleteDefinition(), clang::CXXRecordDecl::isDynamicClass(), clang::Decl::isInvalidDecl(), isMsLayout(), mustSkipTailPadding(), and clang::CharUnits::Zero().
Referenced by AddIndirectPrimaryBases(), clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), BitsContainNoUserData(), clang::CodeGen::CGCXXABI::buildThisParam(), calculateOffset(), CastToDerivedClass(), classifyType(), clang::RecordDecl::completeDefinition(), computeFullPathsForVFTables(), clang::CodeGen::CodeGenModule::computeNonVirtualBaseClassOffset(), computeOffsetHint(), DiagnoseReinterpretUpDownCast(), EmitNullBaseClassInitialization(), EmitNullConstant(), EncodeBitField(), findPathsToSubobject(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), getDeclAlign(), getDerivedToBaseAlignmentAndOffset(), clang::CodeGen::CodeGenModule::getDynamicOffsetAlignment(), clang::VarDecl::getFlexibleArrayInitChars(), getMemberPointerPathAdjustment(), clang::CodeGen::CodeGenModule::getMinimumClassObjectSize(), getOffsetOfBaseWithVBPtr(), getOffsetOfFullPath(), getPreferredTypeAlign(), getTypeInfoDataSizeInChars(), getTypeUnadjustedAlign(), clang::CodeGen::CodeGenModule::getVBaseAlignment(), HandleClassZeroInitialization(), HandleConstructorCall(), HandleDestructionImpl(), HandleLValueBase(), HandleLValueDirectBase(), HandleLValueMember(), isDesignatorAtObjectEnd(), isIntegerLikeType(), clang::Sema::LookupInlineAsmField(), setUsedBits(), structHasUniqueObjectRepresentations(), and clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias().
getAsVariableArrayType()
const VariableArrayType * clang::ASTContext::getAsVariableArrayType (QualType T) const inline
Definition at line 2720 of file ASTContext.h.
References getAsArrayType().
Referenced by clang::Sema::CheckVariableDeclarationType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), emitArraySubscriptGEP(), emitGlobalToListReduceFunction(), emitListToGlobalReduceFunction(), emitPointerArithmetic(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), EquivalentArrayTypes(), getFixedSizeElementType(), mergeTypes(), and TryOrBuildParenListInitialization().
getAtomicType()
QualType ASTContext::getAtomicType (QualType T) const
Return the uniqued reference to the atomic type for the specified type.
getAtomicType - Return the uniqued reference to the atomic type for the given value type.
Definition at line 5895 of file ASTContext.cpp.
References getAtomicType(), getCanonicalType(), clang::AtomicType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildAtomicType(), getAtomicType(), getCommonNonSugarTypeNode(), getVariableArrayDecayedType(), clang::Sema::Initialize(), makeQualifiedLValueReferenceType(), mergeTypes(), and clang::ASTNodeImporter::VisitAtomicType().
getAttributedType()
QualType ASTContext::getAttributedType (attr::Kind attrKind, QualType modifiedType, QualType equivalentType) const
Definition at line 4794 of file ASTContext.cpp.
References getCanonicalType(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildObjCBoxedExpr(), computeConditionalNullability(), clang::desugarForDiagnostic(), getArrayDecayedType(), getBaseMessageSendResultType(), getCommonSugarTypeNode(), getFunctionTypeWithExceptionSpec(), clang::Sema::getMessageSendResultType(), mergeParamDeclTypes(), mergeTypeNullabilityForRedecl(), clang::Sema::ProcessPropertyDecl(), stripObjCInstanceType(), and clang::ASTNodeImporter::VisitAttributedType().
getAutoDeductType()
QualType ASTContext::getAutoDeductType () const
C++11 deduction pattern for 'auto' type.
getAutoDeductType - Get type pattern for deducing against 'auto'.
Definition at line 5922 of file ASTContext.cpp.
References clang::Auto, AutoDeductTy, clang::QualType::isNull(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildCXXForRangeStmt(), clang::Sema::buildLambdaInitCaptureInitialization(), clang::Sema::CheckExplicitlyDefaultedComparison(), ConvertDeclSpecToType(), clang::Sema::deduceVarTypeFromInitializer(), getAutoRRefDeductType(), getDummyLambdaType(), and clang::ASTReader::GetType().
getAutoRRefDeductType()
QualType ASTContext::getAutoRRefDeductType () const
C++11 deduction pattern for 'auto &&' type.
getAutoRRefDeductType - Get type pattern for deducing against 'auto &&'.
Definition at line 5933 of file ASTContext.cpp.
References AutoRRefDeductTy, getAutoDeductType(), getRValueReferenceType(), and clang::QualType::isNull().
Referenced by clang::Sema::ActOnCXXForRangeStmt(), and clang::ASTReader::GetType().
getAutoType()
QualType ASTContext::getAutoType (QualType DeducedType, AutoTypeKeyword Keyword, bool IsDependent, bool IsPack = false, ConceptDecl * TypeConstraintConcept = nullptr, ArrayRef< TemplateArgument > TypeConstraintArgs = {}) const
C++11 deduced auto type.
getAutoType - Return the uniqued reference to the 'auto' type which has been deduced to the given type, or to the canonical undeduced 'auto' type, or the canonical deduced-but-dependent 'auto' type.
Definition at line 5838 of file ASTContext.cpp.
References clang::QualType::isNull().
Referenced by ConvertDeclSpecToType(), getCommonNonSugarTypeNode(), getCommonSugarTypeNode(), getUnconstrainedType(), clang::TreeTransform< Derived >::RebuildAutoType(), clang::TreeTransform< Derived >::RebuildQualifiedType(), and clang::ASTNodeImporter::VisitAutoType().
getAuxTargetInfo()
const TargetInfo * clang::ASTContext::getAuxTargetInfo () const inline
Definition at line 744 of file ASTContext.h.
Referenced by clang::Sema::CheckCallingConvAttr(), HandleNeonVectorTypeAttr(), InitDeviceMC(), clang::Sema::Initialize(), and ProcessStmtAttribute().
getBaseElementType() [1/2]
QualType ASTContext::getBaseElementType (const ArrayType * VAT) const
Return the innermost element type of an array type.
For example, will return "int" for int[m][n]
Definition at line 6990 of file ASTContext.cpp.
References getBaseElementType(), and clang::ArrayType::getElementType().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFields(), clang::Sema::ActOnInitializerError(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildArrayType(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildCXXTypeConstructExpr(), BuildImplicitMemberInitializer(), clang::Sema::BuiltinRemoveExtent(), CheckAggExprForMemSetUse(), clang::Sema::CheckAllocatedType(), clang::Sema::checkArrayElementAlignment(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckNontrivialField(), checkTrivialClassMembers(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CollectIvarsToConstructOrDestruct(), defaultedSpecialMemberIsConstexpr(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), DiagnoseDivisionSizeofPointerOrArray(), diagnoseOpenCLTypes(), EmitMemberInitializer(), emitReadOnlyPlacementAttrWarning(), FieldHasTrivialDestructorBody(), clang::Sema::FindAllocationFunctions(), getBaseElementType(), getDeclAlign(), clang::CFGImplicitDtor::getDestructorDecl(), getInnerObjCOwnership(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), getTypeAlignIfKnown(), handleInitPriorityAttr(), hasUniqueObjectRepresentations(), clang::Sema::inferCUDATargetForImplicitSpecialMember(), clang::Sema::isAbstractType(), isConstNotMutableType(), clang::QualType::isCXX98PODType(), clang::arcmt::trans::MigrationContext::isGCOwnedNonObjC(), clang::QualType::isTriviallyCopyableType(), clang::QualType::isTriviallyRelocatableType(), clang::QualType::isTrivialType(), clang::CodeGen::CodeGenModule::isTypeConstant(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), PerformConstructorInitialization(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::Sema::RequireLiteralType(), clang::Sema::RequireNonAbstractType(), clang::Sema::RequireStructuralType(), clang::Sema::SetIvarInitializers(), setUsedBits(), TryDefaultInitialization(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit(), TryValueInitialization(), TypeRequiresBuiltinLaunderImp(), and clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr().
getBaseElementType() [2/2]
QualType ASTContext::getBaseElementType (QualType QT) const
Return the innermost element type of a type (which needn't actually be an array type).
Definition at line 6994 of file ASTContext.cpp.
References clang::Qualifiers::addConsistentQualifiers(), clang::Type::getAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), getQualifiedType(), clang::SplitQualType::Quals, and clang::SplitQualType::Ty.
getBitIntType()
QualType ASTContext::getBitIntType (bool Unsigned, unsigned NumBits) const
Return a bit-precise integer type with the specified signedness and bit count.
Definition at line 4596 of file ASTContext.cpp.
References clang::BitIntType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::BuildBitIntType(), ChangeIntegralSignedness(), getCorrespondingSignedType(), and getCorrespondingUnsignedType().
getBlockDescriptorExtendedType()
QualType ASTContext::getBlockDescriptorExtendedType () const
Gets the struct used to keep track of the extended descriptor for pointer to blocks.
Definition at line 7451 of file ASTContext.cpp.
References clang::DeclContext::addDecl(), clang::AS_public, buildImplicitRecord(), clang::RecordDecl::completeDefinition(), clang::FieldDecl::Create(), clang::IdentifierTable::get(), getPointerType(), getTagDeclType(), clang::ICIS_NoInit, Idents, clang::TagDecl::startDefinition(), UnsignedLongTy, and VoidPtrTy.
getBlockDescriptorType()
QualType ASTContext::getBlockDescriptorType () const
Gets the struct used to keep track of the descriptor for pointer to blocks.
Definition at line 7416 of file ASTContext.cpp.
References clang::DeclContext::addDecl(), clang::AS_public, buildImplicitRecord(), clang::RecordDecl::completeDefinition(), clang::FieldDecl::Create(), clang::IdentifierTable::get(), getTagDeclType(), clang::ICIS_NoInit, Idents, clang::TagDecl::startDefinition(), and UnsignedLongTy.
getBlockPointerType()
QualType ASTContext::getBlockPointerType (QualType T) const
Return the uniqued reference to the type for a block of the specified type.
getBlockPointerType - Return the uniqued reference to the type for a pointer to the specified block.
Definition at line 3408 of file ASTContext.cpp.
References getBlockPointerType(), getCanonicalType(), clang::BlockPointerType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnBlockStmtExpr(), addBlockPointerConversion(), clang::Sema::BuildBlockPointerType(), checkConditionalPointerCompatibility(), clang::Sema::DeduceReturnType(), getBlockPointerType(), getCommonNonSugarTypeNode(), clang::ento::MemRegionManager::getVarRegion(), mergeTypes(), clang::Sema::PerformImplicitConversion(), and clang::ASTNodeImporter::VisitBlockPointerType().
getBlockVarCopyInit()
BlockVarCopyInit ASTContext::getBlockVarCopyInit (const VarDecl * VD) const
Get the copy initialization expression of the VarDecl VD, or nullptr if none exists.
Get the copy initialization expression of VarDecl, or nullptr if none exists.
Definition at line 2972 of file ASTContext.cpp.
References clang::Decl::hasAttr().
Referenced by BlockRequiresCopying(), getBlockCaptureStr(), and clang::ASTDeclWriter::VisitVarDecl().
getBOOLDecl()
TypedefDecl * clang::ASTContext::getBOOLDecl () const inline
Retrieve declaration of 'BOOL' typedef.
Definition at line 2060 of file ASTContext.h.
Referenced by clang::Sema::ActOnObjCBoolLiteral(), and getBOOLType().
getBoolName()
IdentifierInfo * clang::ASTContext::getBoolName () const inline
Retrieve the identifier 'bool'.
Definition at line 1890 of file ASTContext.h.
References clang::IdentifierTable::get(), and Idents.
Referenced by clang::Sema::getPrintingPolicy().
getBOOLType()
QualType clang::ASTContext::getBOOLType () const inline
type of 'BOOL' type.
Definition at line 2070 of file ASTContext.h.
References getBOOLDecl(), and getTypeDeclType().
Referenced by clang::Sema::ActOnObjCBoolLiteral().
getBTFTagAttributedType()
QualType ASTContext::getBTFTagAttributedType (const BTFTypeTagAttr * BTFAttr, QualType Wrapped)
Definition at line 4814 of file ASTContext.cpp.
References getCanonicalType(), and clang::TypeAlignment.
Referenced by getCommonSugarTypeNode().
getBuiltinMSVaListDecl()
TypedefDecl * ASTContext::getBuiltinMSVaListDecl () const
Retrieve the C type declaration corresponding to the predefined __builtin_ms_va_list type.
Definition at line 9162 of file ASTContext.cpp.
References CreateMSVaListDecl().
Referenced by getBuiltinMSVaListType(), getPredefinedDecl(), and clang::Sema::Initialize().
getBuiltinMSVaListType()
QualType clang::ASTContext::getBuiltinMSVaListType () const inline
Retrieve the type of the __builtin_ms_va_list type.
Definition at line 2098 of file ASTContext.h.
References getBuiltinMSVaListDecl(), and getTypeDeclType().
Referenced by clang::Sema::BuildVAArgExpr(), and clang::desugarForDiagnostic().
GetBuiltinType()
QualType ASTContext::GetBuiltinType (unsigned ID, GetBuiltinTypeError & Error, unsigned * IntegerConstantArgs = nullptr) const
Return the type for the specified builtin.
GetBuiltinType - Return the type for the specified builtin.
If IntegerConstantArgs is non-null, it is filled in with a bitmask of arguments to the builtin that are required to be integer constant expressions.
Definition at line 11569 of file ASTContext.cpp.
References BuiltinInfo, clang::CPlusPlus, DecodeTypeFromStr(), clang::EST_BasicNoexcept, clang::EST_DynamicNone, clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::FunctionProtoType::ExtProtoInfo::ExtInfo, GE_Missing_type, GE_None, getArrayDecayedType(), getDefaultCallingConvention(), getFunctionNoProtoType(), getFunctionType(), getLangOpts(), clang::Builtin::Context::getTypeString(), Id, clang::Type::isArrayType(), clang::Builtin::Context::isNoReturn(), clang::Builtin::Context::isNoThrow(), clang::FunctionProtoType::ExceptionSpecInfo::Type, clang::FunctionProtoType::ExtProtoInfo::Variadic, and clang::FunctionType::ExtInfo::withNoReturn().
Referenced by clang::Sema::ActOnFunctionDeclarator(), getAbsoluteValueArgumentType(), and clang::Sema::LazilyCreateBuiltin().
getBuiltinVaListDecl()
TypedefDecl * ASTContext::getBuiltinVaListDecl () const
Retrieve the C type declaration corresponding to the predefined __builtin_va_list type.
Definition at line 9144 of file ASTContext.cpp.
References CreateVaListDecl(), and clang::Decl::isImplicit().
Referenced by getBuiltinVaListType(), GetFullTypeForDeclarator(), getPredefinedDecl(), getVaListTagDecl(), and clang::Sema::Initialize().
getBuiltinVaListType()
QualType clang::ASTContext::getBuiltinVaListType () const inline
Retrieve the type of the __builtin_va_list type.
Definition at line 2084 of file ASTContext.h.
References getBuiltinVaListDecl(), and getTypeDeclType().
Referenced by clang::Sema::BuildVAArgExpr(), DecodeTypeFromStr(), clang::desugarForDiagnostic(), and clang::CodeGen::getVAListElementType().
getBuiltinVectorTypeInfo()
ASTContext::BuiltinVectorTypeInfo ASTContext::getBuiltinVectorTypeInfo (const BuiltinType * VecTy) const
Returns the element type, element count and number of vectors (in case of tuple) for a builtin vector type.
Definition at line 3880 of file ASTContext.cpp.
References BFloat16Ty, BoolTy, DoubleTy, FloatTy, clang::BuiltinType::getKind(), HalfTy, SVE_ELTTY, and SVE_INT_ELTTY.
Referenced by areCompatibleRVVTypes(), areCompatibleSveTypes(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::Type::getRVVEltType(), getRVVTypeSize(), clang::Sema::GetSignedSizelessVectorType(), clang::Type::getSveEltType(), and HandleRISCVRVVVectorBitsTypeAttr().
getByrefLifetime()
bool ASTContext::getByrefLifetime (QualType Ty, Qualifiers::ObjCLifetime & Lifetime, bool & HasByrefExtendedLayout) const
Returns true, if given type has a known lifetime.
HasByrefExtendedLayout is set to false in this case. If HasByrefExtendedLayout returns true, byref variable has extended lifetime.
Definition at line 7573 of file ASTContext.cpp.
References getLangOpts(), clang::QualType::getObjCLifetime(), clang::Type::isBlockPointerType(), clang::Type::isObjCObjectPointerType(), clang::Type::isRecordType(), clang::LangOptions::NonGC, clang::ObjC, clang::Qualifiers::OCL_ExplicitNone, and clang::Qualifiers::OCL_None.
getCanonicalFunctionResultType()
CanQualType ASTContext::getCanonicalFunctionResultType (QualType ResultType) const
Adjust the given function result type.
Definition at line 4369 of file ASTContext.cpp.
References clang::CanQual< Type >::CreateUnsafe(), getCanonicalType(), getQualifiedType(), clang::CanQual< typename >::getQualifiers(), clang::CanQual< typename >::getUnqualifiedType(), clang::Qualifiers::hasObjCLifetime(), and clang::Qualifiers::removeObjCLifetime().
Referenced by clang::Sema::deduceClosureReturnType(), and getFunctionNoProtoType().
getCanonicalNestedNameSpecifier()
NestedNameSpecifier * ASTContext::getCanonicalNestedNameSpecifier (NestedNameSpecifier * NNS) const
Retrieves the "canonical" nested name specifier for a given nested name specifier.
The canonical nested name specifier is a nested name specifier that uniquely identifies a type or namespace within the type system. For example, given:
namespace N {
  struct S {
    template<typename T> struct X { typename T* type; };
  };
}
template<typename T> struct Y {
  typename N::S::X<T>::type member;
};
Here, the nested-name-specifier for N::S::X<T>:: will be S::X<template-param-0-0>, since 'S' and 'X' are uniquely defined by declarations in the type system and the canonical type for the template type parameter 'T' is template-param-0-0.
Definition at line 6820 of file ASTContext.cpp.
References clang::NestedNameSpecifier::Create(), clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsType(), getCanonicalNestedNameSpecifier(), getCanonicalType(), clang::NestedNameSpecifier::getKind(), clang::NamespaceAliasDecl::getNamespace(), clang::NamespaceDecl::getOriginalNamespace(), clang::NestedNameSpecifier::getPrefix(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by clang::Sema::CheckUsingDeclRedeclaration(), clang::NamedDecl::declarationReplaces(), getCanonicalNestedNameSpecifier(), getCommonNNS(), getDependentNameType(), getDependentTemplateName(), getDependentTemplateName(), and getDependentTemplateSpecializationType().
getCanonicalParamType()
CanQualType ASTContext::getCanonicalParamType (QualType T) const
Return the canonical parameter type corresponding to the specific potentially non-canonical one.
Qualifiers are stripped off, functions are turned into function pointers, and arrays decay one level into pointers.
Definition at line 6017 of file ASTContext.cpp.
References clang::CanQual< Type >::CreateUnsafe(), getArrayDecayedType(), getCanonicalType(), getPointerType(), getVariableArrayDecayedType(), and clang::Result.
Referenced by clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), arrangeFreeFunctionLikeCall(), clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), getArgTypesForCall(), and getArgTypesForDeclaration().
getCanonicalTemplateArgument()
TemplateArgument ASTContext::getCanonicalTemplateArgument (const TemplateArgument & Arg) const
Retrieve the "canonical" template argument.
The canonical template argument is the simplest template argument (which may be a type, value, expression, or declaration) that expresses the value of the argument.
Definition at line 6770 of file ASTContext.cpp.
References clang::cast(), clang::TemplateArgument::CreatePackCopy(), clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::Decl::getCanonicalDecl(), getCanonicalTemplateArguments(), getCanonicalTemplateName(), getCanonicalType(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getIsDefaulted(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNullPtrType(), clang::TemplateArgument::getNumTemplateExpansions(), clang::TemplateArgument::getParamTypeForDecl(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
Referenced by clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::Sema::CheckTemplateArgumentList(), CheckTemplateArgumentPointerToMember(), ConvertDeducedTemplateArguments(), getCanonicalTemplateName(), getSubstTemplateTypeParmPackType(), isSubstitutedTemplateArgument(), and clang::ASTRecordReader::readTemplateArgument().
getCanonicalTemplateName()
TemplateName ASTContext::getCanonicalTemplateName (const TemplateName & Name) const
Retrieves the "canonical" template name that refers to a given template.
The canonical template name is the simplest expression that can be used to refer to a given template. For most templates, this expression is just the template declaration itself. For example, the template std::vector can be referred to via a variety of names—std::vector, ::std::vector, vector (if vector is in scope), etc.—but all of these names map down to the same TemplateDecl, which is used to form the canonical template name.
Dependent template names are more interesting. Here, the template name could be something like T::template apply or std::allocator<T>::template rebind, where the nested name specifier itself is dependent. In this case, the canonical template name uses the shortest form of the dependent nested-name-specifier, which itself contains all canonical types, values, and templates.
Definition at line 6274 of file ASTContext.cpp.
References clang::TemplateName::AssumedTemplate, clang::TemplateName::DependentTemplate, clang::SubstTemplateTemplateParmPackStorage::getArgumentPack(), clang::SubstTemplateTemplateParmPackStorage::getAssociatedDecl(), clang::Decl::getCanonicalDecl(), getCanonicalTemplateArgument(), getCanonicalTemplateName(), clang::SubstTemplateTemplateParmPackStorage::getFinal(), clang::SubstTemplateTemplateParmPackStorage::getIndex(), clang::SubstTemplateTemplateParmStorage::getReplacement(), getSubstTemplateTemplateParmPack(), clang::TemplateName::OverloadedTemplate, clang::TemplateName::QualifiedTemplate, clang::TemplateName::SubstTemplateTemplateParm, clang::TemplateName::SubstTemplateTemplateParmPack, clang::TemplateName::Template, and clang::TemplateName::UsingTemplate.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), DeduceTemplateArguments(), getCanonicalTemplateArgument(), getCanonicalTemplateName(), getCanonicalTemplateSpecializationType(), getCommonTemplateName(), clang::Sema::getMoreSpecializedPartialSpecialization(), hasSameTemplateName(), clang::Sema::isMoreSpecializedThanPrimary(), isSameTemplateArg(), and clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs().
getCanonicalTemplateSpecializationType()
QualType ASTContext::getCanonicalTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgument > Args) const
Definition at line 5015 of file ASTContext.cpp.
References Allocate(), clang::TemplateName::getAsDependentTemplateName(), clang::TemplateName::getAsQualifiedTemplateName(), getCanonicalTemplateArguments(), getCanonicalTemplateName(), and clang::TypeAlignment.
Referenced by checkBuiltinTemplateIdType(), clang::Sema::CheckTemplateIdType(), getTemplateSpecializationType(), and clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs().
getCanonicalType() [1/2]
const Type * clang::ASTContext::getCanonicalType (const Type * T) const inline
Definition at line 2528 of file ASTContext.h.
References clang::Type::getCanonicalTypeInternal(), and clang::QualType::getTypePtr().
getCanonicalType() [2/2]
CanQualType clang::ASTContext::getCanonicalType (QualType T) const inline
Return the canonical (structural) type corresponding to the specified potentially non-canonical type T.
The non-canonical version of a type may have many "decorated" versions of types. Decorators can include typedefs, 'typeof' operators, etc. The returned type is guaranteed to be free of any of these, allowing two canonical types to be compared for exact equality with a simple pointer comparison.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2524 of file ASTContext.h.
References clang::CanQual< Type >::CreateUnsafe().
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartCXXMemberReference(), addBlockPointerConversion(), AddBuiltinAssignmentOperatorCandidates(), clang::Sema::AddConversionCandidate(), addFunctionPointerConversion(), clang::Sema::AddOverriddenMethods(), clang::Sema::areMultiversionVariantFunctionsCompatible(), clang::Sema::AttachBaseSpecifiers(), buildDeclareReductionRef(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildReferenceType(), BuildSimilarlyQualifiedPointerType(), buildSingleCopyAssignRecursively(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::ento::StoreManager::castRegion(), CastsAwayConstness(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckConstructor(), clang::Sema::CheckDerivedToBaseConversion(), clang::CheckEquivalentExceptionSpecImpl(), clang::Sema::CheckFunctionDeclaration(), CheckImplicitConversion(), clang::Sema::CheckMain(), clang::Sema::CheckMemberPointerConversion(), clang::Sema::CheckObjCARCUnavailableWeakConversion(), clang::Sema::CheckObjCMethodOverrides(), CheckOperatorDeleteDeclaration(), CheckOperatorNewDeclaration(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTemplateTypeArgument(), clang::Sema::CodeCompleteConstructorInitializer(), CollectVRQualifiers(), CompareDerivedToBaseConversions(), CompareQualificationConversions(), clang::Sema::CompareReferenceRelationship(), CompareStandardConversionSequences(), clang::ConversionFixItGenerator::compareTypesSimple(), clang::Sema::computeDeclContext(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::Sema::DeclareGlobalAllocationFunction(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::Sema::DeclareImplicitMoveConstructor(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), DiagnoseBadConversion(), clang::Sema::DiagnosePropertyAccessorMismatch(), clang::Sema::DiagnosePropertyMismatch(), clang::Sema::ExtractUnqualifiedFunctionType(), clang::Sema::FindCompositeObjCPointerType(), findDecomposableBaseClass(), findSubobject(), getAddrSpaceQualType(), getAdjustedType(), getAtomicType(), getAttributedType(), clang::CodeGen::CodeGenTBAA::getBaseTypeInfo(), getBlockPointerType(), getBTFTagAttributedType(), getCanonicalFunctionResultType(), getCanonicalNestedNameSpecifier(), getCanonicalParamType(), getCanonicalTemplateArgument(), getComplexType(), getConstantArrayType(), getConstantMatrixType(), getConstructors(), GetConversionType(), getDecayedType(), getDecltypeType(), getDependentAddressSpaceType(), getDependentSizedArrayType(), getDependentSizedExtVectorType(), getDependentSizedMatrixType(), getDependentVectorType(), clang::CXXRecordDecl::getDestructor(), getElaboratedType(), clang::ento::MemRegionManager::getElementRegion(), getExtVectorType(), getIncompleteArrayType(), getIntegerTypeOrder(), GetKeyForBase(), getLValueReferenceType(), getMacroQualifiedType(), getMemberPointerType(), clang::Sema::GetNameFromUnqualifiedId(), getObjCGCQualType(), getObjCObjectPointerType(), getObjCObjectType(), getObjCTypeParamType(), getPackExpansionType(), getParenType(), getPointerType(), getRValueReferenceType(), clang::CodeGen::CodeGenTBAA::getTBAAStructInfo(), getTemplateSpecializationType(), getTypedefType(), clang::CodeGen::CodeGenTBAA::getTypeInfo(), getTypeOfExprType(), getTypeOfType(), getUnaryTransformType(), getVariableArrayType(), clang::ento::MemRegionManager::getVarRegion(), getVectorType(), HandleDynamicCast(), clang::Sema::HandlePropertyInClassExtension(), clang::Sema::handlerCanCatch(), hasSameType(), hasSameType(), hasSameUnqualifiedType(), clang::Sema::ImpCastExprToType(), clang::ASTImporter::Import(), InitBuiltinTypes(), InitCatchParam(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::Sema::IsFunctionConversion(), IsImplicitBoolFloatConversion(), IsInvalidCmseNSCallConversion(), IsModifiable(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::Sema::isObjCPointerConversion(), clang::Sema::IsOverload(), clang::Sema::IsQualificationConversion(), isSameTemplateArg(), clang::CXXConstructorDecl::isSpecializationCopyingObject(), IsStandardConversion(), IsStringInit(), IsStructurallyEquivalent(), clang::Expr::isUnusedResultAWarning(), clang::Sema::LookupConstructors(), LookupMemberExpr(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupSpecialMember(), MarkUsedTemplateParameters(), matchTypes(), clang::Sema::MaybeBindToTemporary(), clang::Sema::MergeFunctionDecl(), mergeFunctionTypes(), mergeObjCGCQualifiers(), mergeTypeLists(), mergeTypes(), MightInstantiateTo(), NoteIndirectBases(), OpenCLArithmeticConversions(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::ProcessPropertyDecl(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), clang::CodeGen::CodeGenTypes::RefreshTypeCacheForClass(), RemoveAddressSpaceFromPtr(), clang::LookupResult::resolveKind(), ResolveOverloadedFunctionForReferenceBinding(), rewriteToObjCProperty(), SelectPropertyForSynthesisFromProtocols(), clang::cross_tu::shouldImport(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), TryConstCast(), TryListConversion(), TryObjectArgumentInitialization(), TryReferenceInit(), TryReferenceInitializationCore(), TryReinterpretCast(), TryStaticCast(), TryStaticMemberPointerUpcast(), TryStaticPointerDowncast(), TryStaticReferenceDowncast(), clang::ConversionFixItGenerator::tryToFixConversion(), TryUserDefinedConversion(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitBlockExpr(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ento::ExprEngine::VisitInitListExpr(), and clang::ASTNodeImporter::VisitTemplateSpecializationType().
getCFConstantStringDecl()
TypedefDecl * ASTContext::getCFConstantStringDecl () const
Objective-C ABI
typedef struct __NSConstantString_tag { const int *isa; int flags; const char *str; long length; } __NSConstantString;
Swift ABI (4.1, 4.2)
typedef struct __NSConstantString_tag { uintptr_t _cfisa; uintptr_t _swift_rc; _Atomic(uint64_t) _cfinfoa; const char *_ptr; uint32_t _length; } __NSConstantString;
Swift ABI (5.0)
typedef struct __NSConstantString_tag { uintptr_t _cfisa; uintptr_t _swift_rc; _Atomic(uint64_t) _cfinfoa; const char *_ptr; uintptr_t _length; } __NSConstantString;
Definition at line 7304 of file ASTContext.cpp.
References clang::DeclContext::addDecl(), clang::AS_public, buildImplicitRecord(), buildImplicitTypedef(), clang::LangOptions::CFRuntime, CharTy, clang::RecordDecl::completeDefinition(), clang::FieldDecl::Create(), clang::IdentifierTable::get(), getLangOpts(), getPointerType(), getTagDeclType(), getUIntPtrType(), clang::ICIS_NoInit, Idents, IntTy, LongTy, clang::TagDecl::startDefinition(), clang::LangOptions::Swift, clang::LangOptions::Swift4_1, clang::LangOptions::Swift4_2, clang::ast_matchers::tagType, Type, and clang::CanQual< typename >::withConst().
Referenced by getCFConstantStringTagDecl(), getCFConstantStringType(), getPredefinedDecl(), and clang::Sema::Initialize().
getCFConstantStringTagDecl()
RecordDecl * ASTContext::getCFConstantStringTagDecl () const
Definition at line 7388 of file ASTContext.cpp.
References getCFConstantStringDecl().
Referenced by getPredefinedDecl().
getCFConstantStringType()
QualType ASTContext::getCFConstantStringType () const
Return the C structure type used to represent constant CFStrings.
Definition at line 7395 of file ASTContext.cpp.
References getCFConstantStringDecl(), and getTypedefType().
Referenced by DecodeTypeFromStr(), and clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString().
getCharWidth()
uint64_t clang::ASTContext::getCharWidth () const inline
Return the size of the character type, in bits.
Definition at line 2300 of file ASTContext.h.
References CharTy, and getTypeSize().
Referenced by clang::Sema::AddAlignedAttr(), clang::Sema::BuildCXXNew(), calculateOffset(), collectSubRegionBindings(), clang::CodeGen::CGObjCRuntime::ComputeIvarBaseOffset(), clang::CodeGen::CGObjCRuntime::ComputeIvarBaseOffset(), diagnoseStringPlusChar(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), expandStringLiteral(), extractStringLiteralCharacter(), getSVETypeSize(), HandleArmSveVectorBitsTypeAttr(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), setUsedBits(), setUsedBits(), toBits(), and toCharUnitsFromBits().
getCommentCommandTraits()
comments::CommandTraits & clang::ASTContext::getCommentCommandTraits () const inline
Definition at line 922 of file ASTContext.h.
Referenced by clang::index::CommentToXMLConverter::convertCommentToHTML(), clang::index::CommentToXMLConverter::convertCommentToXML(), clang::index::CommentToXMLConverter::convertHTMLTagNodeToText(), clang::Decl::dump(), and clang::RawComment::parse().
getCommentForDecl()
comments::FullComment * ASTContext::getCommentForDecl (const Decl * D, const Preprocessor * PP) const
Return parsed documentation comment attached to a given declaration.
Returns nullptr if no comment is attached.
Parameters
PP the Preprocessor used with this TU. Could be nullptr if preprocessor is not available.
Definition at line 631 of file ASTContext.cpp.
References addRedeclaredMethods(), adjustDeclToTemplate(), clang::AS_public, cloneFullComment(), clang::ObjCPropertyDecl::findPropertyDecl(), clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::Decl::getCanonicalDecl(), getCommentForDecl(), getOverriddenMethods(), getRawCommentForAnyRedecl(), clang::Decl::isInvalidDecl(), clang::QualType::isNull(), clang::RawComment::parse(), and ParsedComments.
Referenced by getCommentForDecl().
getCommonSugaredType()
QualType ASTContext::getCommonSugaredType (QualType X, QualType Y, bool Unqualified = false)
Definition at line 13198 of file ASTContext.cpp.
References getCommonNonSugarTypeNode(), getCommonSugarTypeNode(), getQualifiedType(), clang::QualType::getTypePtr(), clang::QualType::getTypePtrOrNull(), hasSameType(), hasSameUnqualifiedType(), clang::QualType::isCanonical(), clang::SplitQualType::Quals, clang::Qualifiers::removeCommonQualifiers(), clang::QualType::split(), clang::SplitQualType::Ty, clang::Unqualified, unwrapSugar(), and X.
Referenced by clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), checkDeducedTemplateArguments(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorOperands(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceAutoType(), clang::Sema::FindCompositePointerType(), getCommonArrayElementType(), getCommonElementType(), getCommonNonSugarTypeNode(), getCommonPointeeType(), getCommonSugarTypeNode(), getCommonTemplateArgument(), getCommonTypes(), mergeTypeLists(), and clang::Sema::UsualArithmeticConversions().
getComplexType() [1/2]
CanQualType clang::ASTContext::getComplexType (CanQualType T) const inline
Definition at line 1316 of file ASTContext.h.
References clang::CanQual< Type >::CreateUnsafe(), and getComplexType().
getComplexType() [2/2]
QualType ASTContext::getComplexType (QualType T) const
Return the uniqued reference to the type for a complex number with the specified element type.
getComplexType - Return the uniqued reference to the type for a complex number with the specified element type.
Definition at line 3288 of file ASTContext.cpp.
References getCanonicalType(), getComplexType(), clang::ComplexType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::AddModeAttr(), ConvertDeclSpecToType(), DecodeTypeFromStr(), getCommonNonSugarTypeNode(), getComplexType(), getComplexType(), handleComplexFloatConversion(), handleComplexIntConversion(), handleIntToFloatConversion(), clang::Sema::UsualUnaryConversions(), and clang::ASTNodeImporter::VisitComplexType().
getConstantArrayElementCount()
uint64_t ASTContext::getConstantArrayElementCount (const ConstantArrayType * CA) const
Return number of constant array elements.
getConstantArrayElementCount - Returns number of constant array elements.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 7010 of file ASTContext.cpp.
References clang::Type::getAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), and clang::ConstantArrayType::getSize().
Referenced by clang::CodeGen::CodeGenTypes::isZeroInitializable(), and setUsedBits().
getConstantArrayType()
QualType ASTContext::getConstantArrayType (QualType EltTy, const llvm::APInt & ArySize, const Expr * SizeExpr, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals) const
Return the unique reference to the type for a constant array of the specified element type.
getConstantArrayType - Return the unique reference to the type for an array of the specified element type.
Definition at line 3548 of file ASTContext.cpp.
References Allocate(), getCanonicalType(), getConstantArrayType(), getQualifiedType(), clang::QualType::hasLocalQualifiers(), clang::QualType::isCanonical(), clang::Type::isConstantSizeType(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), clang::Expr::isInstantiationDependent(), clang::ConstantArrayType::Profile(), clang::SplitQualType::Quals, clang::CanQual< typename >::split(), clang::SplitQualType::Ty, and clang::TypeAlignment.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnNumericConstant(), actOnOMPReductionKindClause(), clang::Sema::BuildArrayType(), clang::Sema::BuildCXXNew(), clang::Sema::BuildPredefinedExpr(), CheckStringInit(), CreateHexagonBuiltinVaListDecl(), CreatePNaClABIBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), clang::desugarForDiagnostic(), diagnoseListInit(), EmitDoacrossOrdered(), clang::Sema::FindCompositePointerType(), getAsArrayType(), getCommonNonSugarTypeNode(), getConstantArrayType(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getStringLiteralArrayType(), getUnqualifiedArrayType(), getVariableArrayDecayedType(), HandleOperatorNewCall(), mergeTypes(), clang::Sema::ParseObjCStringLiteral(), clang::InitializationSequence::Perform(), TryInitializerListConstruction(), TryListConversion(), TryOrBuildParenListInitialization(), TryToFixInvalidVariablyModifiedType(), and clang::ASTNodeImporter::VisitConstantArrayType().
getConstantMatrixType()
QualType ASTContext::getConstantMatrixType (QualType ElementType, unsigned NumRows, unsigned NumColumns) const
Return the unique reference to the matrix type of the specified element type and size.
Precondition
ElementType must be a valid matrix element type (see MatrixType::isValidElementType).
Definition at line 4215 of file ASTContext.cpp.
References getCanonicalType(), getConstantMatrixType(), clang::QualType::isCanonical(), clang::ConstantMatrixType::isDimensionValid(), clang::MatrixType::isValidElementType(), clang::ConstantMatrixType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildMatrixType(), clang::Sema::CheckMatrixMultiplyOperands(), getCommonNonSugarTypeNode(), getConstantMatrixType(), and clang::TreeTransform< Derived >::RebuildConstantMatrixType().
getConstType()
QualType clang::ASTContext::getConstType (QualType T) const inline
Return the uniqued reference to the type for a const qualified type.
The resulting type has a union of the qualifiers from T and const.
It can be reasonably expected that this will always be equivalent to calling T.withConst().
Definition at line 1275 of file ASTContext.h.
References clang::QualType::withConst().
Referenced by clang::Sema::EvaluateStaticAssertMessageAsString(), makeLaunchBoundsArgExpr(), and RVVType2Qual().
getCopyConstructorForExceptionObject()
const CXXConstructorDecl * ASTContext::getCopyConstructorForExceptionObject (CXXRecordDecl * RD)
Definition at line 12197 of file ASTContext.cpp.
References clang::Redeclarable< decl_type >::getFirstDecl().
getCorrespondingSaturatedType()
QualType ASTContext::getCorrespondingSaturatedType (QualType Ty) const
Definition at line 13261 of file ASTContext.cpp.
References clang::Type::castAs(), clang::BuiltinType::getKind(), clang::Type::isFixedPointType(), clang::Type::isSaturatedFixedPointType(), SatAccumTy, SatFractTy, SatLongAccumTy, SatLongFractTy, SatShortAccumTy, SatShortFractTy, SatUnsignedAccumTy, SatUnsignedFractTy, SatUnsignedLongAccumTy, SatUnsignedLongFractTy, SatUnsignedShortAccumTy, and SatUnsignedShortFractTy.
Referenced by ConvertDeclSpecToType(), and handleFixedPointConversion().
getCorrespondingSignedFixedPointType()
QualType ASTContext::getCorrespondingSignedFixedPointType (QualType Ty) const
Definition at line 13428 of file ASTContext.cpp.
References AccumTy, clang::Type::castAs(), FractTy, clang::BuiltinType::getKind(), clang::Type::isUnsignedFixedPointType(), LongAccumTy, LongFractTy, SatAccumTy, SatFractTy, SatLongAccumTy, SatLongFractTy, SatShortAccumTy, SatShortFractTy, ShortAccumTy, and ShortFractTy.
Referenced by handleFixedPointConversion().
getCorrespondingSignedType()
QualType ASTContext::getCorrespondingSignedType (QualType T) const
Definition at line 11120 of file ASTContext.cpp.
References AccumTy, FractTy, getBitIntType(), getCorrespondingSignedType(), clang::BuiltinType::getKind(), getSignedWCharType(), getVectorType(), Int128Ty, IntTy, LongAccumTy, LongFractTy, LongLongTy, LongTy, SatAccumTy, SatFractTy, SatLongAccumTy, SatLongFractTy, SatShortAccumTy, SatShortFractTy, ShortAccumTy, ShortFractTy, ShortTy, and SignedCharTy.
Referenced by clang::Sema::BuildVAArgExpr(), clang::Sema::BuiltinChangeSignedness(), and getCorrespondingSignedType().
getCorrespondingUnsignedType()
QualType ASTContext::getCorrespondingUnsignedType (QualType T) const
Definition at line 11046 of file ASTContext.cpp.
References getBitIntType(), getCorrespondingUnsignedType(), clang::BuiltinType::getKind(), getUnsignedWCharType(), getVectorType(), SatUnsignedAccumTy, SatUnsignedFractTy, SatUnsignedLongAccumTy, SatUnsignedLongFractTy, SatUnsignedShortAccumTy, SatUnsignedShortFractTy, UnsignedAccumTy, UnsignedCharTy, UnsignedFractTy, UnsignedInt128Ty, UnsignedIntTy, UnsignedLongAccumTy, UnsignedLongFractTy, UnsignedLongLongTy, UnsignedLongTy, UnsignedShortAccumTy, UnsignedShortFractTy, and UnsignedShortTy.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuiltinChangeSignedness(), checkPointerTypesForAssignment(), ConvertDeclSpecToType(), clang::ento::SMTConv::doIntTypeConversion(), getCorrespondingUnsignedType(), getUIntPtrType(), and handleIntegerConversion().
getcudaConfigureCallDecl()
FunctionDecl * clang::ASTContext::getcudaConfigureCallDecl () inline
Definition at line 1392 of file ASTContext.h.
Referenced by clang::Sema::ActOnCUDAExecConfigExpr().
getCUIDHash()
StringRef ASTContext::getCUIDHash () const
Definition at line 13602 of file ASTContext.cpp.
References clang::LangOptions::CUID.
Referenced by clang::CodeGen::CodeGenModule::printPostfixForExternalizedDecl().
getCurrentKeyFunction()
const CXXMethodDecl * ASTContext::getCurrentKeyFunction (const CXXRecordDecl * RD)
Get our current best idea for the key function of the given record decl, or nullptr if there isn't one.
The key function is, according to the Itanium C++ ABI section 5.2.3: ...the first non-pure virtual function that is not inline at the point of class definition.
Other ABIs use the same idea. However, the ARM C++ ABI ignores virtual functions that are defined 'inline', which means that the result of this computation can change.
Definition at line 3376 of file RecordLayoutBuilder.cpp.
References computeKeyFunction(), clang::LazyOffsetPtr< T, OffsT, Get >::get(), clang::CXXRecordDecl::getDefinition(), clang::LazyOffsetPtr< T, OffsT, Get >::isOffset(), and clang::LazyOffsetPtr< T, OffsT, Get >::isValid().
Referenced by clang::Sema::ActOnFinishFunctionBody(), DeclMustBeEmitted(), clang::Sema::DefineUsedVTables(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::CodeGen::CodeGenVTables::isVTableExternal(), and clang::ASTDeclWriter::VisitCXXRecordDecl().
getCurrentNamedModule()
Module * clang::ASTContext::getCurrentNamedModule () const inline
Get module under construction, nullptr if this is not a C++20 module.
Definition at line 1057 of file ASTContext.h.
Referenced by clang::Decl::isInAnotherModuleUnit(), and clang::CodeGen::CodeGenModule::Release().
getCVRQualifiedType()
QualType clang::ASTContext::getCVRQualifiedType (QualType T, unsigned CVR) const inline
Return a type with additional const, volatile, or restrict qualifiers.
Definition at line 2117 of file ASTContext.h.
References clang::Qualifiers::fromCVRMask(), and getQualifiedType().
Referenced by clang::Sema::CheckPointerToMemberOperands().
getCXXABIKind()
TargetCXXABI::Kind ASTContext::getCXXABIKind () const
Return the C++ ABI kind that should be used.
The C++ ABI can be overriden at compile time with -fc++-abi=. If this is not provided, we instead use the default ABI set by the target.
Definition at line 871 of file ASTContext.cpp.
References clang::LangOptions::CXXABI, clang::TargetInfo::getCXXABI(), clang::TargetCXXABI::getKind(), getLangOpts(), and getTargetInfo().
Referenced by createCXXABI(), and clang::CodeGen::CreateItaniumCXXABI().
getDecayedType() [1/3]
CanQualType clang::ASTContext::getDecayedType (CanQualType T) const inline
Definition at line 1339 of file ASTContext.h.
References clang::CanQual< Type >::CreateUnsafe(), and getDecayedType().
getDecayedType() [2/3]
QualType ASTContext::getDecayedType (QualType Orig, QualType Decayed) const
Return the uniqued reference to a specified decay from the original type to the decayed type.
Definition at line 3363 of file ASTContext.cpp.
References getCanonicalType(), clang::AdjustedType::Profile(), and clang::TypeAlignment.
getDecayedType() [3/3]
QualType ASTContext::getDecayedType (QualType T) const
Return the uniqued reference to the decayed version of the given type.
Can only be called on array and function types which decay to pointer types.
Definition at line 3383 of file ASTContext.cpp.
References getArrayDecayedType(), getDecayedType(), and getPointerType().
Referenced by AdjustFunctionParmAndArgTypesForDeduction(), clang::Sema::BuiltinDecay(), clang::Sema::CheckNonTypeTemplateParameterType(), clang::Sema::deduceOpenCLAddressSpace(), getAdjustedParameterType(), getCommonSugarTypeNode(), getDecayedType(), getDecayedType(), getExceptionObjectType(), SemaBuiltinAlignment(), and clang::ASTNodeImporter::VisitDecayedType().
getDeclAlign()
CharUnits ASTContext::getDeclAlign (const Decl * D, bool ForAlignof = false) const
Return a conservative estimate of the alignment of the specified decl D.
Precondition
D must not be a bitfield type, as bitfields do not have a valid alignment.
If ForAlignof, references are treated like their underlying type and large arrays don't get any special treatment. If not ForAlignof it computes the value expected by CodeGen: references are treated like pointers and large arrays get extra alignment.
Definition at line 1681 of file ASTContext.cpp.
References clang::TypeInfo::Align, clang::ast_matchers::arrayType, clang::ASTRecordLayout::getAlignment(), getAsArrayType(), getASTRecordLayout(), getBaseElementType(), clang::ASTRecordLayout::getFieldOffset(), clang::TargetInfo::getMaxAlignedAttribute(), clang::Decl::getMaxAlignment(), getPointerType(), getPreferredTypeAlign(), clang::QualType::getQualifiers(), getTargetInfo(), getTypeSize(), clang::Decl::hasAttr(), clang::Qualifiers::hasUnaligned(), clang::Type::isIncompleteType(), Offset, Parent, clang::SC_Static, toBits(), and toCharUnitsFromBits().
Referenced by clang::Sema::CheckThreadLocalForLargeAlignment(), emitAddrOfVarFromArray(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), EmitFunctionDeclLValue(), EmitGlobalNamedRegister(), EmitGlobalVarDeclLValue(), emitOutlinedFunctionPrologue(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), GetAlignOfExpr(), getBaseAlignment(), getBaseAlignmentAndOffsetFromLValue(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcAllocShared(), clang::Sema::getNamedReturnInfo(), clang::CodeGen::CodeGenModule::GetWeakRefReference(), clang::Sema::RefersToMemberWithReducedAlignment(), and clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryExprOrTypeTraitExpr().
getDeclaratorForUnnamedTagDecl()
DeclaratorDecl * ASTContext::getDeclaratorForUnnamedTagDecl (const TagDecl * TD)
Definition at line 12224 of file ASTContext.cpp.
getDeclAttrs()
AttrVec & ASTContext::getDeclAttrs (const Decl * D)
Retrieve the attributes for the given declaration.
Definition at line 1466 of file ASTContext.cpp.
References Allocate(), and clang::Result.
Referenced by clang::Decl::getAttrs().
getDecltypeType()
QualType ASTContext::getDecltypeType (Expr * e, QualType UnderlyingType) const
C++11 decltype.
Unlike many "get<Type>" functions, we don't unique DecltypeType nodes.
This would never be helpful, since each such type has its own expression, and would not give a significant memory saving, since there is an Expr tree under each such type.
Definition at line 5717 of file ASTContext.cpp.
References getCanonicalType(), clang::Expr::isInstantiationDependent(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildDecltypeType(), and clang::ASTNodeImporter::VisitDecltypeType().
getDeducedTemplateSpecializationType()
QualType ASTContext::getDeducedTemplateSpecializationType (TemplateName Template, QualType DeducedType, bool IsDependent) const
C++17 deduced class template specialization type.
Return the uniqued reference to the deduced template specialization type which has been deduced to the given type, or to the canonical undeduced such type, or the canonical deduced-but-dependent such type.
Definition at line 5872 of file ASTContext.cpp.
References clang::TypeAlignment.
Referenced by clang::Sema::CheckTypenameType(), clang::Sema::getTypeName(), clang::TreeTransform< Derived >::RebuildDeducedTemplateSpecializationType(), and clang::ASTNodeImporter::VisitDeducedTemplateSpecializationType().
getDefaultCallingConvention()
CallingConv ASTContext::getDefaultCallingConvention (bool IsVariadic, bool IsCXXMethod, bool IsBuiltin = false) const
Retrieves the default calling convention for the current target.
Definition at line 11976 of file ASTContext.cpp.
References clang::CC_C, clang::CC_X86FastCall, clang::CC_X86RegCall, clang::CC_X86StdCall, clang::CC_X86VectorCall, clang::LangOptions::DCC_CDecl, clang::LangOptions::DCC_FastCall, clang::LangOptions::DCC_None, clang::LangOptions::DCC_RegCall, clang::LangOptions::DCC_StdCall, clang::LangOptions::DCC_VectorCall, getTargetInfo(), and hasFeature().
Referenced by addBlockPointerConversion(), addFunctionPointerConversion(), clang::Sema::adjustMemberFunctionCC(), clang::CodeGen::CodeGenTypes::arrangeMSCtorClosure(), clang::Sema::CheckCallingConvAttr(), compareConversionFunctions(), clang::Sema::DeclareGlobalAllocationFunction(), DiagnoseCallingConvCast(), GetBuiltinType(), getCCForDeclaratorChunk(), getDummyLambdaType(), getImplicitMethodEPI(), getLambdaConversionFunctionCallConv(), GetOpenCLBuiltinFctOverloads(), hasDefaultCXXMethodCC(), and repeatForLambdaConversionFunctionCallingConvs().
getDefaultOpenCLPointeeAddrSpace()
LangAS clang::ASTContext::getDefaultOpenCLPointeeAddrSpace () inline
Returns default address space based on OpenCL version and enabled features.
Definition at line 1383 of file ASTContext.h.
References clang::opencl_generic, and clang::opencl_private.
Referenced by AdjustFunctionParmAndArgTypesForDeduction(), deduceOpenCLPointeeAddrSpace(), clang::Sema::getDefaultCXXMethodAddrSpace(), and clang::Expr::isNullPointerConstant().
getDependentAddressSpaceType()
QualType ASTContext::getDependentAddressSpaceType (QualType PointeeType, Expr * AddrSpaceExpr, SourceLocation AttrLoc) const
Definition at line 4287 of file ASTContext.cpp.
References clang::DependentAddressSpaceType::getAddrSpaceExpr(), getCanonicalType(), clang::Expr::isInstantiationDependent(), clang::DependentAddressSpaceType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildAddressSpaceAttr(), and getCommonNonSugarTypeNode().
getDependentBitIntType()
QualType ASTContext::getDependentBitIntType (bool Unsigned, Expr * BitsExpr) const
Return a dependent bit-precise integer type with the specified signedness and bit count.
Definition at line 4610 of file ASTContext.cpp.
References clang::Expr::isInstantiationDependent(), clang::DependentBitIntType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildBitIntType().
getDependentNameType()
QualType ASTContext::getDependentNameType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier * NNS, const IdentifierInfo * Name, QualType Canon = QualType()) const
Definition at line 5123 of file ASTContext.cpp.
References getCanonicalNestedNameSpecifier(), getDependentNameType(), clang::QualType::isNull(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnDependentTag(), clang::Sema::ActOnMSVCUnknownTypeName(), clang::Sema::ActOnTemplatedFriendTag(), clang::Sema::CheckTemplateTypeArgument(), clang::Sema::CheckTypenameType(), getCommonNonSugarTypeNode(), clang::Sema::getConstructorName(), getDependentNameType(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), clang::TreeTransform< Derived >::RebuildDependentNameType(), recoverFromTypeInKnownDependentBase(), and clang::ASTNodeImporter::VisitDependentNameType().
getDependentSizedArrayType()
QualType ASTContext::getDependentSizedArrayType (QualType EltTy, Expr * NumElts, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals, SourceRange Brackets) const
Return a non-unique reference to the type for a dependently-sized array of the specified element type.
getDependentSizedArrayType - Returns a non-unique reference to the type for a dependently-sized array of the specified element type.
FIXME: We will need these to be uniqued, or at least comparable, at some point.
Definition at line 3774 of file ASTContext.cpp.
References getCanonicalType(), getQualifiedType(), clang::DependentSizedArrayType::getSizeExpr(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::DependentSizedArrayType::Profile(), clang::SplitQualType::Quals, clang::CanQual< typename >::split(), clang::SplitQualType::Ty, and clang::TypeAlignment.
Referenced by clang::Sema::BuildArrayType(), clang::desugarForDiagnostic(), getAsArrayType(), getCommonNonSugarTypeNode(), getUnqualifiedArrayType(), getVariableArrayDecayedType(), clang::InitializationSequence::Perform(), and clang::ASTNodeImporter::VisitDependentSizedArrayType().
getDependentSizedExtVectorType()
QualType ASTContext::getDependentSizedExtVectorType (QualType VectorType, Expr * SizeExpr, SourceLocation AttrLoc) const
Precondition
Return a non-unique reference to the type for a dependently-sized vector of the specified element type.
FIXME: We will need these to be uniqued, or at least comparable, at some point.
Definition at line 4174 of file ASTContext.cpp.
References getCanonicalType(), getDependentSizedExtVectorType(), clang::DependentSizedExtVectorType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildExtVectorType(), getCommonNonSugarTypeNode(), and getDependentSizedExtVectorType().
getDependentSizedMatrixType()
QualType ASTContext::getDependentSizedMatrixType (QualType ElementType, Expr * RowExpr, Expr * ColumnExpr, SourceLocation AttrLoc) const
Return the unique reference to the matrix type of the specified element type and size.
Definition at line 4247 of file ASTContext.cpp.
References getCanonicalType(), clang::MatrixType::getElementType(), clang::DependentSizedMatrixType::getRowExpr(), clang::DependentSizedMatrixType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildMatrixType(), and getCommonNonSugarTypeNode().
getDependentTemplateName() [1/2]
TemplateName ASTContext::getDependentTemplateName (NestedNameSpecifier * NNS, const IdentifierInfo * Name) const
Retrieve the template name that represents a dependent template name such as MetaFun::template apply.
Definition at line 9242 of file ASTContext.cpp.
References getCanonicalNestedNameSpecifier(), getDependentTemplateName(), clang::NestedNameSpecifier::isDependent(), and clang::DependentTemplateName::Profile().
Referenced by clang::Sema::ActOnTemplateName(), clang::Sema::DiagnoseUnknownTemplateName(), getDependentTemplateName(), getDependentTemplateName(), and clang::ASTImporter::Import().
getDependentTemplateName() [2/2]
TemplateName ASTContext::getDependentTemplateName (NestedNameSpecifier * NNS, OverloadedOperatorKind Operator) const
Retrieve the template name that represents a dependent template name such as MetaFun::template operator+.
Definition at line 9278 of file ASTContext.cpp.
References getCanonicalNestedNameSpecifier(), getDependentTemplateName(), clang::NestedNameSpecifier::isDependent(), and clang::DependentTemplateName::Profile().
getDependentTemplateSpecializationType() [1/2]
QualType ASTContext::getDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier * NNS, const IdentifierInfo * Name, ArrayRef< TemplateArgument > Args) const
Definition at line 5159 of file ASTContext.cpp.
References Allocate(), getCanonicalNestedNameSpecifier(), getCanonicalTemplateArguments(), getDependentTemplateSpecializationType(), clang::NestedNameSpecifier::isDependent(), and clang::TypeAlignment.
getDependentTemplateSpecializationType() [2/2]
QualType ASTContext::getDependentTemplateSpecializationType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier * NNS, const IdentifierInfo * Name, ArrayRef< TemplateArgumentLoc > Args) const
Definition at line 5148 of file ASTContext.cpp.
References getArgument(), and getDependentTemplateSpecializationType().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), clang::Sema::CheckTemplateIdType(), getCommonNonSugarTypeNode(), getDependentTemplateSpecializationType(), getDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::RebuildDependentTemplateSpecializationType(), and clang::ASTNodeImporter::VisitDependentTemplateSpecializationType().
getDependentVectorType()
QualType ASTContext::getDependentVectorType (QualType VectorType, Expr * SizeExpr, SourceLocation AttrLoc, VectorType::VectorKind VecKind) const
Return the unique reference to the type for a dependently sized vector of the specified element type.
Definition at line 4100 of file ASTContext.cpp.
References getCanonicalType(), getDependentVectorType(), clang::DependentVectorType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildVectorType(), getCommonNonSugarTypeNode(), and getDependentVectorType().
getDiagAllocator()
PartialDiagnostic::DiagStorageAllocator & clang::ASTContext::getDiagAllocator () inline
Definition at line 739 of file ASTContext.h.
Referenced by clang::Sema::EmitCurrentDiagnostic(), and clang::Sema::PDiag().
getDiagnostics()
DiagnosticsEngine & ASTContext::getDiagnostics () const
Definition at line 1462 of file ASTContext.cpp.
Referenced by CheckedIntArithmetic(), checkNullabilityConsistency(), clang::SYCLUniqueStableNameExpr::ComputeName(), createDeviceMangleContext(), createMangleContext(), clang::StructuralEquivalenceContext::Diag1(), clang::StructuralEquivalenceContext::Diag2(), clang::APValue::dump(), clang::comments::Comment::dump(), clang::Decl::dump(), clang::QualType::dump(), clang::Stmt::dump(), clang::DeclContext::dumpAsDecl(), clang::cross_tu::CrossTranslationUnitContext::emitCrossTUDiagnostics(), clang::ASTImporter::FromDiag(), getFunctionFeatureMap(), getFunctionFeatureMap(), clang::ASTImporter::Import(), clang::ASTReader::InitializeContext(), clang::RecordDecl::mayInsertExtraPadding(), clang::RawComment::parse(), rewriteToNumericBoxedExpression(), selectBestPath(), and clang::ASTImporter::ToDiag().
getElaboratedType()
QualType ASTContext::getElaboratedType (ElaboratedTypeKeyword Keyword, NestedNameSpecifier * NNS, QualType NamedType, TagDecl * OwnedTagDecl = nullptr) const
Definition at line 5057 of file ASTContext.cpp.
References Allocate(), getCanonicalType(), clang::QualType::isCanonical(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTypenameType(), buildNamedType(), clang::Sema::BuildStdInitializerList(), clang::Sema::CheckComparisonCategoryType(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckTypenameType(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), getCommonSugarTypeNode(), clang::Sema::getDestructorName(), clang::Sema::getElaboratedType(), GetFullTypeForDeclarator(), clang::TypeName::getFullyQualifiedType(), lookupPromiseType(), clang::TreeTransform< Derived >::RebuildDependentNameType(), clang::TreeTransform< Derived >::RebuildDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::RebuildElaboratedType(), and clang::ASTNodeImporter::VisitElaboratedType().
getEnumType()
QualType ASTContext::getEnumType (const EnumDecl * Decl) const
Definition at line 4765 of file ASTContext.cpp.
References clang::Decl::getPreviousDecl(), and clang::TypeAlignment.
Referenced by clang::CodeGen::CGDebugInfo::completeType(), and getOpenCLEnumType().
getExceptionObjectType()
QualType ASTContext::getExceptionObjectType (QualType T) const
Definition at line 6949 of file ASTContext.cpp.
References getDecayedType(), and getVariableArrayDecayedType().
Referenced by clang::Sema::BuildCXXThrow(), clang::Sema::BuildExceptionDeclaration(), and decomposeTypeForEH().
getExnObjectAlignment()
CharUnits ASTContext::getExnObjectAlignment () const
Return the alignment (in bytes) of the thrown exception object.
This is only meaningful for targets that allocate C++ exceptions in a system runtime, such as those using the Itanium C++ ABI.
Definition at line 1784 of file ASTContext.cpp.
References toCharUnitsFromBits().
Referenced by clang::Sema::CheckCXXThrowOperand().
getExternalSource()
ExternalASTSource * clang::ASTContext::getExternalSource () const inline
Retrieve a pointer to the external AST source associated with this AST context, if any.
Definition at line 1166 of file ASTContext.h.
References ExternalSource.
Referenced by clang::ASTDeclWriter::AddTemplateSpecializations(), adjustGVALinkageForExternalDefinitionKind(), clang::FrontendAction::BeginSourceFile(), clang::ExternalASTMerger::CompleteType(), clang::ExternalASTMerger::CompleteType(), clang::CodeGen::CodeGenModule::EmitTopLevelDecl(), clang::CXXRecordDecl::getLambdaContextDecl(), clang::Sema::getStdAlignValT(), clang::Sema::getStdBadAlloc(), clang::Sema::getStdNamespace(), clang::Sema::handleLambdaNumbering(), clang::Sema::hasAcceptableDefinition(), clang::Sema::Initialize(), isConsumerInterestedIn(), clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl(), clang::DeclContext::lookup(), clang::DeclContext::lookups(), clang::LazyGenerationalUpdatePtr< Owner, T, Update >::makeValue(), clang::ParseAST(), clang::Parser::ParseFirstTopLevelDecl(), shouldOmitDefinition(), clang::Decl::updateOutOfDate(), clang::ASTNodeImporter::VisitRecordDecl(), and clang::Sema::~Sema().
getExternCContextDecl()
ExternCContextDecl * ASTContext::getExternCContextDecl () const
Definition at line 1159 of file ASTContext.cpp.
References clang::ExternCContextDecl::Create(), and getTranslationUnitDecl().
Referenced by clang::Sema::findLocallyScopedExternCDecl(), getPredefinedDecl(), and clang::Sema::RegisterLocallyScopedExternCDecl().
getExtVectorType()
QualType ASTContext::getExtVectorType (QualType vecType, unsigned NumElts) const
Return the unique reference to an extended vector type of the specified element type and size.
getExtVectorType - Return the unique reference to an extended vector type of the specified element type and size.
Precondition
VectorType must be a built-in type.
VectorType must be a built-in type.
Definition at line 4140 of file ASTContext.cpp.
References clang::Type::castAs(), clang::VectorType::GenericVector, getCanonicalType(), getExtVectorType(), clang::BitIntType::getNumBits(), clang::Type::isBitIntType(), clang::Type::isBuiltinType(), clang::QualType::isCanonical(), clang::Type::isDependentType(), clang::VectorType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildExtVectorType(), CheckExtVectorComponent(), clang::Sema::CheckVectorConditionalTypes(), checkVectorShift(), convertVector(), DecodeTypeFromStr(), getCommonNonSugarTypeNode(), getExtVectorType(), clang::Sema::GetSignedVectorType(), OpenCLConvertScalarsToVectors(), and clang::ASTNodeImporter::VisitExtVectorType().
getFieldOffset()
uint64_t ASTContext::getFieldOffset (const ValueDecl * FD) const
Get the offset of a FieldDecl or IndirectFieldDecl, in bits.
Definition at line 3427 of file RecordLayoutBuilder.cpp.
References clang::cast(), clang::IndirectFieldDecl::chain(), and getFieldOffset().
Referenced by emitAddrOfZeroSizeField(), getSubobjectOffset(), and clang::Sema::RefersToMemberWithReducedAlignment().
getFILEType()
QualType clang::ASTContext::getFILEType () const inline
Retrieve the C FILE type.
Definition at line 1922 of file ASTContext.h.
References getTypeDeclType().
Referenced by DecodeTypeFromStr().
getFixedPointIBits()
unsigned char ASTContext::getFixedPointIBits (QualType Ty) const
Definition at line 13361 of file ASTContext.cpp.
References clang::Type::castAs(), clang::BuiltinType::getKind(), getTargetInfo(), and clang::Type::isFixedPointType().
getFixedPointMax()
llvm::APFixedPoint ASTContext::getFixedPointMax (QualType Ty) const
Definition at line 13418 of file ASTContext.cpp.
References getFixedPointSemantics(), and clang::Type::isFixedPointType().
Referenced by clang::Sema::ActOnNumericConstant(), and CheckImplicitConversion().
getFixedPointMin()
llvm::APFixedPoint ASTContext::getFixedPointMin (QualType Ty) const
Definition at line 13423 of file ASTContext.cpp.
References getFixedPointSemantics(), and clang::Type::isFixedPointType().
Referenced by CheckImplicitConversion().
getFixedPointScale()
unsigned char ASTContext::getFixedPointScale (QualType Ty) const
Definition at line 13315 of file ASTContext.cpp.
References clang::Type::castAs(), clang::BuiltinType::getKind(), getTargetInfo(), and clang::Type::isFixedPointType().
Referenced by clang::Sema::ActOnNumericConstant(), getFixedPointSemantics(), and clang::ASTNodeImporter::VisitFixedPointLiteral().
getFixedPointSemantics()
llvm::FixedPointSemantics ASTContext::getFixedPointSemantics (QualType Ty) const
Definition at line 13403 of file ASTContext.cpp.
References getFixedPointScale(), getIntWidth(), getTargetInfo(), getTypeSize(), clang::Type::isFixedPointType(), clang::Type::isIntegerType(), clang::Type::isSaturatedFixedPointType(), clang::Type::isSignedFixedPointType(), and clang::Type::isSignedIntegerType().
Referenced by CheckImplicitConversion(), DiagnoseBadShiftValues(), EvaluateComparisonBinaryOperator(), EvaluateFixedPointOrInteger(), getFixedPointMax(), and getFixedPointMin().
getFloatingTypeOrder()
int ASTContext::getFloatingTypeOrder (QualType LHS, QualType RHS) const
Compare the rank of the two specified floating point types, ignoring the domain of the type (i.e.
getFloatingTypeOrder - Compare the rank of the two specified floating point types, ignoring the domain of the type (i.e.
'double' == '_Complex double').
If LHS > RHS, returns 1. If LHS == RHS, returns 0. If LHS < RHS, return -1.
'double' == '_Complex double'). If LHS > RHS, return 1. If LHS == RHS, return 0. If LHS < RHS, return -1.
Definition at line 7058 of file ASTContext.cpp.
References getFloatingRank().
Referenced by clang::ento::SMTConv::doFloatTypeConversion(), getFloatingTypeSemanticOrder(), clang::StandardConversionSequence::getNarrowingKind(), handleComplexConversion(), handleFloatConversion(), isArithmeticArgumentPromotion(), tryGCCVectorConvertAndSplat(), tryVectorConvertAndSplat(), and clang::Sema::UsualUnaryConversions().
getFloatingTypeSemanticOrder()
int ASTContext::getFloatingTypeSemanticOrder (QualType LHS, QualType RHS) const
Compare the rank of two floating point types as above, but compare equal if both types have the same floating-point semantics on the target (i.e.
long double and double on AArch64 will return 0).
Definition at line 7069 of file ASTContext.cpp.
References getFloatingTypeOrder(), and getFloatTypeSemantics().
Referenced by AnalyzeCompoundAssignment(), and CheckImplicitConversion().
getFloatTypeSemantics()
const llvm::fltSemantics & ASTContext::getFloatTypeSemantics (QualType T) const
Return the APFloat 'semantics' for the specified scalar floating point type.
getFloatTypeSemantics - Return the APFloat 'semantics' for the specified scalar floating point type.
Definition at line 1648 of file ASTContext.cpp.
References clang::TargetInfo::getFloat128Format(), clang::BuiltinType::getKind(), getLangOpts(), clang::TargetInfo::getLongDoubleFormat(), and clang::HLSL.
Referenced by actOnOMPReductionKindClause(), BuildFloatingLiteral(), canConvertIntTyToFloatTy(), clang::Sema::CheckFloatComparison(), CheckImplicitConversion(), clang::Sema::checkTypeSupport(), clang::CodeGen::CodeGenTypes::ConvertType(), getFloatingTypeSemanticOrder(), clang::interp::Context::getFloatSemantics(), clang::StandardConversionSequence::getNarrowingKind(), clang::ento::SMTConv::getZeroExpr(), HandleFloatToFloatCast(), HandleIntToFloatCast(), IsStandardConversion(), TryEvaluateBuiltinNaN(), tryGCCVectorConvertAndSplat(), and unsupportedTypeConversion().
getFullLoc()
FullSourceLoc clang::ASTContext::getFullLoc (SourceLocation Loc) const inline
Definition at line 781 of file ASTContext.h.
Referenced by clang::CodeGen::CodeGenModule::Error(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), and clang::CodeGen::CGCXXABI::ErrorUnsupportedABI().
getFunctionFeatureMap() [1/2]
void ASTContext::getFunctionFeatureMap (llvm::StringMap< bool > & FeatureMap, const FunctionDecl * FD) const
Definition at line 13486 of file ASTContext.cpp.
References getDiagnostics(), and getFunctionFeatureMap().
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::checkTypeSupport(), clang::Sema::CheckVariableDeclarationType(), getFunctionFeatureMap(), and initFeatureMaps().
getFunctionFeatureMap() [2/2]
void ASTContext::getFunctionFeatureMap (llvm::StringMap< bool > & FeatureMap, GlobalDecl GD) const
Definition at line 13498 of file ASTContext.cpp.
References filterFunctionTargetAttrs(), filterFunctionTargetVersionAttrs(), clang::Decl::getAsFunction(), clang::Decl::getAttr(), clang::GlobalDecl::getDecl(), getDiagnostics(), and clang::GlobalDecl::getMultiVersionIndex().
getFunctionNoProtoType() [1/2]
QualType clang::ASTContext::getFunctionNoProtoType (QualType ResultTy) const inline
Definition at line 1534 of file ASTContext.h.
References getFunctionNoProtoType().
getFunctionNoProtoType() [2/2]
QualType ASTContext::getFunctionNoProtoType (QualType ResultTy, const FunctionType::ExtInfo & Info) const
Return a K&R style C function type like 'int()'.
getFunctionNoProtoType - Return a K&R style C function type like 'int()'.
Definition at line 4331 of file ASTContext.cpp.
References getCanonicalFunctionResultType(), getFunctionNoProtoType(), isCanonicalResultType(), clang::FunctionNoProtoType::Profile(), and clang::TypeAlignment.
Referenced by adjustFunctionType(), clang::Sema::BuildDeclarationNameExpr(), clang::desugarForDiagnostic(), EmitFunctionDeclPointer(), GeneralizeFunctionType(), GetBuiltinType(), getCommonNonSugarTypeNode(), GetFullTypeForDeclarator(), getFunctionNoProtoType(), getFunctionNoProtoType(), getFunctionTypeWithoutPtrSizes(), clang::Sema::ImplicitlyDefineFunction(), mergeFunctionTypes(), clang::TreeTransform< Derived >::RebuildFunctionNoProtoType(), and clang::ASTNodeImporter::VisitFunctionNoProtoType().
getFunctionType()
QualType clang::ASTContext::getFunctionType (QualType ResultTy, ArrayRef< QualType > Args, const FunctionProtoType::ExtProtoInfo & EPI) const inline
Return a normal function type with a typed argument list.
Definition at line 1539 of file ASTContext.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnFunctionDeclarator(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPRegionStart(), addBlockPointerConversion(), addFunctionPointerConversion(), clang::Sema::adjustCCAndNoReturn(), adjustDeducedFunctionResultType(), clang::Sema::AdjustDestructorExceptionSpec(), clang::TemplateDeclInstantiator::adjustForRewrite(), adjustFunctionType(), adjustFunctionTypeForInstantiation(), clang::Sema::BuildFunctionType(), buildTypeForLambdaCallOperator(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::CodeGen::CodeGenModule::CreateKCFITypeId(), clang::Sema::DeclareGlobalAllocationFunction(), clang::desugarForDiagnostic(), emitOutlinedFunctionPrologue(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindCompositePointerType(), clang::Sema::findInheritingConstructor(), GeneralizeFunctionType(), GetBuiltinType(), getCommonNonSugarTypeNode(), getDummyLambdaType(), GetFullTypeForDeclarator(), clang::CodeGen::CGDebugInfo::getFunctionType(), getFunctionTypeWithExceptionSpec(), getFunctionTypeWithoutPtrSizes(), clang::Sema::getLambdaConversionFunctionResultType(), GetOpenCLBuiltinFctOverloads(), clang::ento::MemRegionManager::getVarRegion(), clang::TemplateDeclInstantiator::InitFunctionInstantiation(), clang::Sema::IsFunctionConversion(), LookupDirect(), clang::Sema::MergeFunctionDecl(), mergeFunctionTypes(), mergeObjCGCQualifiers(), rewriteBuiltinFunctionDecl(), SemaBuiltinCallWithStaticChain(), clang::ASTDeclReader::UpdateDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), and clang::ASTNodeImporter::VisitFunctionProtoType().
getFunctionTypeWithExceptionSpec()
QualType ASTContext::getFunctionTypeWithExceptionSpec (QualType Orig, const FunctionProtoType::ExceptionSpecInfo & ESI) const
Get a function type and produce the equivalent function type with the specified exception specification.
Type sugar that can be present on a declaration of a function with an exception specification is permitted and preserved. Other type sugar (for instance, typedefs) is not.
Definition at line 3199 of file ASTContext.cpp.
References clang::Type::castAs(), getAttributedType(), getFunctionType(), getFunctionTypeWithExceptionSpec(), getMacroQualifiedType(), and getParenType().
Referenced by adjustExceptionSpec(), extractPBaseFlags(), getFunctionTypeWithExceptionSpec(), handleFunctionTypeAttr(), hasSameFunctionTypeIgnoringExceptionSpec(), and clang::Sema::IsFunctionConversion().
getFunctionTypeWithoutPtrSizes()
QualType ASTContext::getFunctionTypeWithoutPtrSizes (QualType T)
Get a function type and produce the equivalent function type where pointer size address spaces in the return type and parameter tyeps are replaced with the default address space.
Definition at line 3235 of file ASTContext.cpp.
References clang::Type::getAs(), getFunctionNoProtoType(), getFunctionType(), and removePtrSizeAddrSpace().
Referenced by hasSameFunctionTypeIgnoringPtrSizes().
GetGVALinkageForFunction()
GVALinkage ASTContext::GetGVALinkageForFunction (const FunctionDecl * FD) const
Definition at line 11747 of file ASTContext.cpp.
References adjustGVALinkageForAttributes(), adjustGVALinkageForExternalDefinitionKind(), and basicGVALinkageForFunction().
Referenced by clang::ASTRecordWriter::AddFunctionDefinition(), basicGVALinkageForVariable(), DeclMustBeEmitted(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), isFunctionDefinitionDiscarded(), clang::FunctionDecl::isInlineBuiltinDeclaration(), and shouldBeInCOMDAT().
GetGVALinkageForVariable()
GVALinkage ASTContext::GetGVALinkageForVariable (const VarDecl * VD) const
Definition at line 11830 of file ASTContext.cpp.
References adjustGVALinkageForAttributes(), adjustGVALinkageForExternalDefinitionKind(), and basicGVALinkageForVariable().
Referenced by DeclMustBeEmitted(), clang::CodeGen::CodeGenModule::getLLVMLinkageVarDefinition(), shouldBeInCOMDAT(), and clang::ASTDeclWriter::VisitVarDecl().
getIncompleteArrayType()
QualType ASTContext::getIncompleteArrayType (QualType EltTy, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals) const
Return a unique reference to the type for an incomplete array of the specified element type.
Definition at line 3842 of file ASTContext.cpp.
References getCanonicalType(), getIncompleteArrayType(), getQualifiedType(), clang::QualType::hasLocalQualifiers(), clang::QualType::isCanonical(), clang::IncompleteArrayType::Profile(), clang::SplitQualType::Quals, clang::CanQual< typename >::split(), clang::SplitQualType::Ty, and clang::TypeAlignment.
Referenced by clang::Sema::BuildArrayType(), clang::Sema::BuildCXXNew(), clang::desugarForDiagnostic(), clang::Sema::FindCompositePointerType(), getAsArrayType(), getCommonNonSugarTypeNode(), getIncompleteArrayType(), getUnqualifiedArrayType(), mergeTypes(), and clang::ASTNodeImporter::VisitIncompleteArrayType().
getInjectedClassNameType()
QualType ASTContext::getInjectedClassNameType (CXXRecordDecl * Decl, QualType TST) const
getInjectedClassNameType - Return the unique reference to the injected class name type for the specified templated declaration.
Definition at line 4644 of file ASTContext.cpp.
References clang::Decl::getPreviousDecl(), NeedsInjectedClassNameType(), and clang::TypeAlignment.
Referenced by clang::Sema::CheckClassTemplate(), clang::ClassTemplatePartialSpecializationDecl::Create(), getCommonNonSugarTypeNode(), clang::ASTDeclReader::VisitClassTemplateDecl(), and clang::ASTNodeImporter::VisitRecordDecl().
getInjectedTemplateArg()
TemplateArgument ASTContext::getInjectedTemplateArg (NamedDecl * ParamDecl)
Definition at line 5208 of file ASTContext.cpp.
References clang::cast(), clang::TemplateArgument::CreatePackCopy(), DependentTy, getPackExpansionType(), getTypeDeclType(), clang::Expr::getValueKindForType(), and clang::TemplateTemplateParmDecl::isParameterPack().
Referenced by clang::Sema::getIdentityTemplateArgumentLoc(), and getInjectedTemplateArgs().
getInjectedTemplateArgs()
void ASTContext::getInjectedTemplateArgs (const TemplateParameterList * Params, SmallVectorImpl< TemplateArgument > & Args)
Get a template argument list with one argument per template parameter in a template parameter list, such as for the injected class name of a class template.
Definition at line 5248 of file ASTContext.cpp.
References getInjectedTemplateArg(), and clang::TemplateParameterList::size().
Referenced by clang::ClassTemplateDecl::getInjectedClassNameSpecialization(), clang::RedeclarableTemplateDecl::getInjectedTemplateArgs(), and clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs().
getInlineVariableDefinitionKind()
ASTContext::InlineVariableDefinitionKind ASTContext::getInlineVariableDefinitionKind (const VarDecl * VD) const
Determine whether a definition of this inline variable should be treated as a weak or strong definition.
For compatibility with C++14 and before, for a constexpr static data member, if there is an out-of-line declaration of the member, we may promote it from weak to strong.
Definition at line 7655 of file ASTContext.cpp.
References clang::First, clang::Redeclarable< decl_type >::getFirstDecl(), clang::VarDecl::isInline(), None, clang::Redeclarable< decl_type >::redecls(), Strong, Weak, and WeakUnknown.
Referenced by basicGVALinkageForVariable(), and clang::CodeGen::CodeGenModule::EmitGlobal().
getInnerObjCOwnership()
Qualifiers::ObjCLifetime ASTContext::getInnerObjCOwnership (QualType T) const
Recurses in pointer/array types until it finds an Objective-C retainable type and returns its ownership.
Recurses in pointer/array types until it finds an objc retainable type and returns its ownership.
Definition at line 7231 of file ASTContext.cpp.
References getBaseElementType(), and clang::Qualifiers::OCL_None.
Referenced by clang::Sema::GetTypeForDeclaratorCast().
getInstantiatedFromStaticDataMember()
MemberSpecializationInfo * ASTContext::getInstantiatedFromStaticDataMember (const VarDecl * Var)
If this variable is an instantiated static data member of a class template specialization, returns the templated static data member from which it was instantiated.
Definition at line 1487 of file ASTContext.cpp.
References getTemplateOrSpecializationInfo(), and clang::VarDecl::isStaticDataMember().
getInstantiatedFromUnnamedFieldDecl()
FieldDecl * ASTContext::getInstantiatedFromUnnamedFieldDecl (FieldDecl * Field)
Definition at line 1563 of file ASTContext.cpp.
Referenced by isInstantiationOf(), and clang::ASTDeclWriter::VisitFieldDecl().
getInstantiatedFromUsingDecl()
NamedDecl * ASTContext::getInstantiatedFromUsingDecl (NamedDecl * Inst)
If the given using decl Inst is an instantiation of another (possibly unresolved) using decl, return it.
Definition at line 1522 of file ASTContext.cpp.
Referenced by isInstantiationOfUnresolvedUsingDecl(), clang::ASTDeclWriter::VisitUsingDecl(), and clang::ASTNodeImporter::VisitUsingDecl().
getInstantiatedFromUsingEnumDecl()
UsingEnumDecl * ASTContext::getInstantiatedFromUsingEnumDecl (UsingEnumDecl * Inst)
If the given using-enum decl Inst is an instantiation of another using-enum decl, return it.
Definition at line 1541 of file ASTContext.cpp.
Referenced by clang::ASTDeclWriter::VisitUsingEnumDecl(), and clang::ASTNodeImporter::VisitUsingEnumDecl().
getInstantiatedFromUsingShadowDecl()
UsingShadowDecl * ASTContext::getInstantiatedFromUsingShadowDecl (UsingShadowDecl * Inst)
Definition at line 1552 of file ASTContext.cpp.
Referenced by clang::ASTDeclWriter::VisitUsingShadowDecl(), and clang::ASTNodeImporter::VisitUsingShadowDecl().
getInt128Decl()
TypedefDecl * ASTContext::getInt128Decl () const
Retrieve the declaration for the 128-bit signed integer type.
Definition at line 1219 of file ASTContext.cpp.
References buildImplicitTypedef(), and Int128Ty.
Referenced by getPredefinedDecl(), and clang::Sema::Initialize().
getIntegerTypeOrder()
int ASTContext::getIntegerTypeOrder (QualType LHS, QualType RHS) const
Return the highest ranked integer type, see C99 6.3.1.8p1.
getIntegerTypeOrder - Returns the highest ranked integer type: C99 6.3.1.8p1.
If LHS > RHS, returns 1. If LHS == RHS, returns 0. If LHS < RHS, return -1.
If LHS > RHS, return 1. If LHS == RHS, return 0. If LHS < RHS, return -1.
Definition at line 7259 of file ASTContext.cpp.
References getCanonicalType(), getIntegerTypeForEnum(), clang::CanQual< typename >::getTypePtr(), and clang::Type::isUnsignedIntegerType().
Referenced by canConvertIntToOtherIntTy(), clang::ento::SMTConv::doIntTypeConversion(), handleIntegerConversion(), tryGCCVectorConvertAndSplat(), and tryVectorConvertAndSplat().
getInterpContext()
interp::Context & ASTContext::getInterpContext ()
Returns the clang bytecode interpreter context.
Definition at line 897 of file ASTContext.cpp.
Referenced by EvaluateAsRValue(), and clang::Expr::isPotentialConstantExpr().
getIntMaxType()
CanQualType ASTContext::getIntMaxType () const
Return the unique type for "intmax_t" (C99 7.18.1.5), defined in <stdint.h>.
getIntMaxType - Return the unique type for "intmax_t" (C99 7.18.1.5).
Definition at line 5963 of file ASTContext.cpp.
Referenced by clang::analyze_scanf::ScanfSpecifier::getArgType().
getIntPtrType()
QualType ASTContext::getIntPtrType () const
Return a type compatible with "intptr_t" (C99 7.18.1.4), as defined by the target.
Definition at line 5986 of file ASTContext.cpp.
Referenced by getUIntPtrType(), and clang::Sema::Initialize().
getIntTypeForBitwidth()
QualType ASTContext::getIntTypeForBitwidth (unsigned DestWidth, unsigned Signed) const
getIntTypeForBitwidth - sets integer QualTy according to specified details: bitwidth, signed/unsigned.
Returns empty type if there is no appropriate target types.
Definition at line 12106 of file ASTContext.cpp.
References clang::TargetInfo::getIntTypeByWidth(), getTargetInfo(), Int128Ty, clang::Signed, and UnsignedInt128Ty.
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnNumericConstant(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCanonicalLoop(), clang::Sema::ActOnOpenMPRegionStart(), AddDirectArgument(), clang::Sema::AddModeAttr(), checkOpenMPLoop(), createKmpTaskTRecordDecl(), createRuntimeShuffleFunction(), EmitAsmStores(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitDoacrossOrdered(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), emitRestoreIP(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), clang::ento::SMTConv::getAPSIntType(), clang::CodeGen::CGOpenMPRuntimeGPU::getDefaultDistScheduleAndChunk(), clang::CodeGen::CGOpenMPRuntime::getDefaultScheduleAndChunk(), clang::CodeGen::CGOpenMPRuntimeGPU::getDefaultScheduleAndChunk(), clang::Sema::GetSignedSizelessVectorType(), handleAnyX86InterruptAttr(), RVVType2Qual(), and shuffleAndStore().
getIntWidth()
unsigned ASTContext::getIntWidth (QualType T) const
Definition at line 11035 of file ASTContext.cpp.
References clang::Type::getAs(), and getTypeSize().
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnOpenMPCanonicalLoop(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::Sema::ActOnStringLiteral(), AnalyzeComparison(), buildDistanceFunc(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), clang::Sema::CheckEnumConstant(), CheckICE(), CheckImplicitConversion(), clang::Sema::CheckTemplateArgument(), clang::interp::Context::classify(), DeduceFromInitializerList(), clang::Sema::DiagnoseAssignmentEnum(), DiagnoseBadShiftValues(), DiagnoseFloatingImpCast(), getAlignmentArgument(), clang::ento::BasicValueFactory::getAPSIntType(), getFixedPointSemantics(), getIntegerWidthAndSignedness(), getLegacyIntegralTypeEncoding(), clang::StandardConversionSequence::getNarrowingKind(), getPromotedIntegerType(), clang::ento::BasicValueFactory::getTruthValue(), clang::EnumDecl::getValueRange(), HandleFloatToIntCast(), handleIntegerConversion(), HandleIntToIntCast(), handleVectorUnaryOperator(), handleVectorVectorBinOp(), clang::InitializationSequence::InitializeFrom(), isOverflowingIntegerType(), isRepresentableIntegerValue(), isValidStructGUID(), MakeIntValue(), clang::InitializationSequence::Perform(), clang::TreeTransform< Derived >::RebuildArrayType(), clang::TreeTransform< Derived >::RebuildBitIntType(), clang::TreeTransform< Derived >::RebuildExtVectorType(), SemaBuiltinAlignment(), SemaBuiltinOverflow(), and clang::Sema::VerifyBitField().
getjmp_bufType()
QualType clang::ASTContext::getjmp_bufType () const inline
Retrieve the C jmp_buf type.
Definition at line 1934 of file ASTContext.h.
References getTypeDeclType().
Referenced by DecodeTypeFromStr().
getLangASForBuiltinAddressSpace()
LangAS ASTContext::getLangASForBuiltinAddressSpace (unsigned AS) const
Definition at line 13296 of file ASTContext.cpp.
References clang::TargetInfo::getCUDABuiltinAddressSpace(), clang::getLangASFromTargetAS(), clang::TargetInfo::getOpenCLBuiltinAddressSpace(), and getTargetInfo().
Referenced by clang::Sema::ActOnVariableDeclarator(), and DecodeTypeFromStr().
getLangOpts()
const LangOptions & clang::ASTContext::getLangOpts () const inline
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 761 of file ASTContext.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnStartOfObjCMethodDef(), clang::Sema::ActOnVarTemplateSpecialization(), AddEnumerators(), clang::ASTRecordWriter::AddFunctionDefinition(), AddOverloadParameterChunks(), clang::arcmt::trans::MigrationContext::addPropertyAttribute(), adjustGVALinkageForAttributes(), AlignOfType(), AllowOverloadingOfFunction(), clang::arcmt::MigrationProcess::applyTransform(), areLaxCompatibleRVVTypes(), areLaxCompatibleSveTypes(), basicGVALinkageForFunction(), buildGlobalBlock(), buildImplicitRecord(), clang::Sema::BuildMatrixType(), CalculateHiddenNames(), clang::arcmt::trans::canApplyWeak(), canAssignObjCInterfacesInBlockPointer(), CastsAwayConstness(), clang::Sema::CheckCompletedCXXClass(), CheckConstexprFunction(), checkFloatingPointResult(), CheckForIncompatibleAttributes(), clang::arcmt::checkForManualIssues(), CheckICE(), clang::Sema::CheckLogicalOperands(), ClassifyBinaryOp(), ClassifyConditional(), ClassifyDecl(), ClassifyInternal(), ClassifyMemberExpr(), ClassifyUnnamed(), clang::Sema::CodeCompleteObjCMethodDecl(), clang::RecordDecl::completeDefinition(), clang::computeDependence(), computeKeyFunction(), clang::LinkageComputer::computeLVForDecl(), clang::PredefinedExpr::ComputeName(), clang::analyze_os_log::computeOSLogBufferLayout(), constructDebugPieceForTrackedCondition(), clang::CodeGen::CodeGenTypes::ConvertType(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), clang::Sema::CreateBuiltinUnaryOp(), createOverloadsForFixedParams(), clang::Sema::CreateRecoveryExpr(), clang::tooling::createRenameAtomicChanges(), clang::CodeGen::CodeGenModule::CreateRuntimeVariable(), DecodeTypeFromStr(), clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition(), clang::Stmt::dumpPretty(), clang::LocationContext::dumpStack(), EmitDeclDestroy(), EmitDeclInit(), emitMappingInformation(), EncodeBitField(), clang::ento::BasicValueFactory::evalAPSInt(), clang::Expr::EvaluateAsInitializer(), EvaluateComparisonBinaryOperator(), clang::SourceLocExpr::EvaluateInContext(), clang::ASTMergeAction::ExecuteAction(), clang::arcmt::trans::findSemiAfterLocation(), fixParamWithSpan(), fixUPCAddressofArraySubscriptWithSpan(), fixVarDeclWithSpan(), clang::FormatASTNodeDiagnosticArgument(), GCRewriteFinalize(), GenerateFixForUnusedDecl(), getActiveRoundingMode(), GetAlignOfType(), clang::tooling::getAssociatedRange(), getAttrForPlatform(), clang::ento::MemRegionManager::getBlockDataRegion(), clang::FunctionDecl::getBuiltinID(), GetBuiltinType(), getByrefLifetime(), getCallingConvMangling(), getCFConstantStringDecl(), clang::ASTNameGenerator::Implementation::getClassSymbolPrefix(), clang::ento::SValBuilder::getConditionType(), getCXXABIKind(), getDeclLanguageLinkage(), clang::LinkageComputer::getDeclLinkageAndVisibility(), GetDiagForGotoScopeDecl(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), DerefSimplePtrArithFixableGadget::getFixits(), UPCPreIncrementGadget::getFixits(), getFloatTypeSemantics(), clang::AnalysisDeclContext::getFunctionName(), GetGCAttrTypeForType(), clang::Expr::getIntegerConstantExpr(), clang::ASTWriter::getLangOpts(), clang::Decl::getLangOpts(), clang::ento::CheckerContext::getLangOpts(), clang::index::IndexingContext::getLangOpts(), clang::interp::Context::getLangOpts(), getLiteralInfo(), clang::CodeGen::CodeGenModule::getLLVMLinkageForDeclarator(), getLogicalOperationType(), clang::LinkageComputer::getLVForDecl(), getMacroName(), getMoreSpecialized(), clang::Sema::getMoreSpecializedTemplate(), clang::CXXRecordDecl::getMSVtorDispMode(), clang::StandardConversionSequence::getNarrowingKind(), clang::QualType::getNonLValueExprType(), getNSArrayObjects(), clang::NSAPI::GetNSIntegralKind(), getObjCEncodingForBlock(), getObjCGCAttrKind(), clang::Sema::getPrintingPolicy(), getRealizedPlatform(), clang::DeclContext::getRedeclContext(), getRVVTypeSize(), clang::ObjCMethodDecl::getSelfType(), clang::ento::MemRegionManager::getStaticSize(), getStringLiteralArrayType(), getSVETypeSize(), clang::tooling::getText(), getTypeInfoDataSizeInChars(), getVTableContext(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::ento::retaincountchecker::RetainCountChecker::handleAutoreleaseCounts(), handleBuiltinAliasAttr(), clang::Sema::handleTagNumbering(), clang::Decl::hasLocalOwningModuleStorage(), hasSameFunctionTypeIgnoringExceptionSpec(), InsertOCLBuiltinDeclarationsFromTable(), clang::Sema::isAcceptableNestedNameSpecifier(), clang::Expr::isCXX11ConstantExpr(), clang::ParmVarDecl::isDestroyedInCallee(), clang::ObjCMethodDecl::isDirectMethod(), clang::ObjCPropertyDecl::isDirectProperty(), clang::FunctionDecl::isInlineDefinitionExternallyVisible(), clang::Expr::isIntegerConstantExpr(), clang::Type::isIntegralType(), clang::VarDecl::isKnownToBeDefined(), clang::Sema::isLaxVectorConversion(), clang::Type::isLiteralType(), clang::FunctionDecl::isMain(), IsModifiable(), clang::VarDecl::isNoDestroy(), clang::QualType::isNonWeakInMRRWithObjCWeak(), clang::Expr::isNullPointerConstant(), isOutOfScopePreviousDeclaration(), clang::QualType::isPODType(), isPromotableBitField(), isPromotableIntegerType(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), isSameEntity(), IsStringInit(), clang::CodeGen::CodeGenModule::isTypeConstant(), isTypeSubstitutable(), clang::Expr::isUnusedResultAWarning(), clang::VarDecl::isUsableInConstantExpressions(), isUserWritingOffTheEnd(), clang::CXXMethodDecl::isUsualDeallocationFunction(), IsWideCharCompatible(), clang::CodeGen::ABIInfo::isZeroLengthBitfieldPermittedInHomogeneousAggregate(), clang::CXXRecordDecl::lambdaIsDefaultConstructibleAndAssignable(), LocPropertyAttribute(), MarkUsedTemplateParameters(), clang::Sema::MaybeBindToTemporary(), clang::tooling::maybeExtendRange(), clang::RecordDecl::mayInsertExtraPadding(), clang::ASTDeclReader::mergeLambda(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::mergeRedeclarable(), mergeTypes(), needsConversionOfHalfVec(), clang::ento::ConditionBRVisitor::patternMatch(), populateInitializerFixItWithSpan(), printExprAsWritten(), clang::LocationContext::printJson(), clang::ProgramPoint::printJson(), printNode(), printQualifier(), PrintStats(), clang::ento::retaincountchecker::RetainCountChecker::processLeaks(), ProcessStmtAttribute(), clang::randstruct::randomizeStructureLayout(), clang::ASTDeclReader::ReadFunctionDefinition(), clang::CodeGen::CodeGenModule::Release(), reportAnalyzerFunctionMisuse(), resolveAllocationOverload(), clang::edit::rewriteObjCRedundantCallWithLiteral(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), clang::edit::rewriteToObjCLiteralSyntax(), setObjCGCLValueClass(), shouldNotRewriteImmediateMessageArgs(), ShouldUseExternalRTTIDescriptor(), clang::Sema::SpecialMemberIsTrivial(), clang::CodeGen::CodeGenModule::stopAutoInit(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), typesAreCompatible(), UnwrapSimilarArrayTypes(), UnwrapSimilarTypes(), clang::QualType::UseExcessPrecision(), useInlineVisibilityHidden(), clang::FunctionCallFilterCCC::ValidateCandidate(), clang::ASTNodeImporter::VisitBuiltinType(), clang::ASTDeclReader::VisitDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ASTNodeImporter::VisitRecordDecl(), clang::ASTDeclWriter::VisitVarDecl(), and clang::ASTDeclReader::VisitVarDeclImpl().
getLegacyIntegralTypeEncoding()
void ASTContext::getLegacyIntegralTypeEncoding (QualType & PointeeTy) const
getLegacyIntegralTypeEncoding - Another legacy compatibility encoding: 32-bit longs are encoded as 'l' or 'L' , but not always.
For typedefs, we need to use 'i' or 'I' instead if encoding a struct field, or a pointer!
Definition at line 7963 of file ASTContext.cpp.
References clang::Type::getAs(), getIntWidth(), IntTy, and UnsignedIntTy.
getLifetimeQualifiedType()
QualType clang::ASTContext::getLifetimeQualifiedType (QualType type, Qualifiers::ObjCLifetime lifetime) inline
Return a type with the given lifetime qualifier.
Precondition
Neither type.ObjCLifetime() nor lifetime may be OCL_None.
Definition at line 2145 of file ASTContext.h.
References clang::Qualifiers::addObjCLifetime(), getQualifiedType(), and clang::Qualifiers::OCL_None.
Referenced by clang::Sema::BuildCXXNew(), clang::Sema::CheckParameter(), and clang::Sema::inferObjCARCLifetime().
getLocalCommentForDeclUncached()
comments::FullComment * ASTContext::getLocalCommentForDeclUncached (const Decl * D) const
Return parsed documentation comment attached to a given declaration.
Returns nullptr if no comment is attached. Does not look at any redeclarations of the declaration.
Definition at line 626 of file ASTContext.cpp.
References getRawCommentForDeclNoCache(), and clang::RawComment::parse().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
getLogicalOperationType()
QualType clang::ASTContext::getLogicalOperationType () const inline
The result type of logical operations, '<', '>', '!=', etc.
Definition at line 1965 of file ASTContext.h.
References BoolTy, getLangOpts(), and IntTy.
Referenced by clang::Sema::BuildTypeTrait(), checkArithmeticOrEnumeralCompare(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckVectorCompareOperands(), clang::Sema::CreateBuiltinUnaryOp(), and clang::ento::BasicValueFactory::getTruthValue().
getLValueReferenceType()
QualType ASTContext::getLValueReferenceType (QualType T, bool SpelledAsLValue = true) const
Return the uniqued reference to the type for an lvalue reference to the specified type.
getLValueReferenceType - Return the uniqued reference to the type for an lvalue reference to the specified type.
Definition at line 3440 of file ASTContext.cpp.
References getCanonicalType(), getLValueReferenceType(), clang::ReferenceType::Profile(), and clang::TypeAlignment.
Referenced by AddBuiltinAssignmentOperatorCandidates(), AddImplicitObjectParameterType(), AdjustFunctionParmAndArgTypesForDeduction(), alignReferenceTypes(), buildDistanceFunc(), buildLoopVarFunc(), clang::Sema::BuildReferenceType(), clang::Sema::BuildVAArgExpr(), captureInCapturedRegion(), captureInLambda(), checkDynamicType(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitMoveAssignment(), DecodeTypeFromStr(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::desugarForDiagnostic(), DiagnoseForRangeConstVariableCopies(), DiagnoseForRangeReferenceVariableCopies(), clang::Expr::EvaluateAsLValue(), findCompleteObject(), getCaptureFieldType(), getCommonNonSugarTypeNode(), clang::Sema::getDecltypeForExpr(), clang::TypeName::getFullyQualifiedType(), getImplicitObjectParamType(), getLValueReferenceType(), clang::SubstNonTypeTemplateParmExpr::getParameterType(), getReferenceQualifiedType(), getVariableArrayDecayedType(), HandleDestructionImpl(), clang::ento::ExprEngine::handleLValueBitCast(), implicitObjectParamIsLifetimeBound(), lookupPromiseType(), makeQualifiedLValueReferenceType(), NoteSurrogateCandidate(), clang::InitializationSequence::Perform(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::tryCaptureVariable(), clang::CodeGen::ConstantEmitter::tryEmitConstantExpr(), and clang::ASTNodeImporter::VisitLValueReferenceType().
getMacroQualifiedType()
QualType ASTContext::getMacroQualifiedType (QualType UnderlyingTy, const IdentifierInfo * MacroII) const
Definition at line 5111 of file ASTContext.cpp.
References getCanonicalType(), clang::QualType::isCanonical(), and clang::TypeAlignment.
Referenced by getCommonSugarTypeNode(), getFunctionTypeWithExceptionSpec(), and clang::TreeTransform< Derived >::RebuildMacroQualifiedType().
getMakeIntegerSeqDecl()
BuiltinTemplateDecl * ASTContext::getMakeIntegerSeqDecl () const
Definition at line 1178 of file ASTContext.cpp.
References clang::BTK__make_integer_seq, buildBuiltinTemplateDecl(), and getMakeIntegerSeqName().
Referenced by getPredefinedDecl(), and clang::ASTNodeImporter::VisitBuiltinTemplateDecl().
getMakeIntegerSeqName()
IdentifierInfo * clang::ASTContext::getMakeIntegerSeqName () const inline
Definition at line 1896 of file ASTContext.h.
References clang::IdentifierTable::get(), and Idents.
Referenced by getMakeIntegerSeqDecl().
getManglingNumber()
unsigned ASTContext::getManglingNumber (const NamedDecl * ND, bool ForAuxTarget = false) const
Definition at line 12147 of file ASTContext.cpp.
Referenced by clang::Sema::BuildVariableInstantiation(), and clang::TemplateDeclInstantiator::InitFunctionInstantiation().
getManglingNumberContext() [1/2]
MangleNumberingContext & ASTContext::getManglingNumberContext (const DeclContext * DC)
Retrieve the context for computing mangling numbers in the given DeclContext.
Definition at line 12173 of file ASTContext.cpp.
References createMangleNumberingContext().
Referenced by clang::Sema::getCurrentMangleNumberContext(), clang::Sema::handleLambdaNumbering(), and clang::Sema::handleTagNumbering().
getManglingNumberContext() [2/2]
MangleNumberingContext & ASTContext::getManglingNumberContext (NeedExtraManglingDecl_t , const Decl * D)
Definition at line 12182 of file ASTContext.cpp.
References createMangleNumberingContext().
getMemberPointerPathAdjustment()
CharUnits ASTContext::getMemberPointerPathAdjustment (const APValue & MP) const
Find the 'this' offset for the member path in a pointer-to-member APValue.
Definition at line 2586 of file ASTContext.cpp.
References clang::cast(), getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::Decl::getDeclContext(), clang::APValue::getMemberPointerDecl(), clang::APValue::getMemberPointerPath(), clang::APValue::isMemberPointerToDerivedMember(), N, and clang::CharUnits::Zero().
getMemberPointerType()
QualType ASTContext::getMemberPointerType (QualType T, const Type * Cls) const
Return the uniqued reference to the type for a member pointer to the specified type in the specified class.
getMemberPointerType - Return the uniqued reference to the type for a member pointer to the specified type, in the specified class.
The class Cls is a Type because it could be a dependent name.
Definition at line 3518 of file ASTContext.cpp.
References getCanonicalType(), getMemberPointerType(), clang::Type::isCanonicalUnqualified(), clang::MemberPointerType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildMemberPointerType(), clang::Sema::CheckAddressOfOperand(), clang::Sema::checkOpenMPDeclareVariantFunction(), decomposeTypeForEH(), clang::CodeGen::CGCXXABI::EmitMemberFunctionPointer(), clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), clang::Sema::FindCompositePointerType(), clang::Sema::FixOverloadedFunctionReference(), getCommonNonSugarTypeNode(), clang::TypeName::getFullyQualifiedType(), getMemberPointerType(), GetTypeOfFunction(), clang::Sema::IsMemberPointerConversion(), IsStandardConversion(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), TryStaticMemberPointerUpcast(), and clang::ASTNodeImporter::VisitMemberPointerType().
getModuleInitializers()
ArrayRef< Decl * > ASTContext::getModuleInitializers (Module * M)
Get the initializations to perform when importing a module, if any.
Definition at line 1142 of file ASTContext.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitTopLevelDecl(), and clang::TextNodeDumper::VisitImportDecl().
getModulesWithMergedDefinition()
ArrayRef< Module * > ASTContext::getModulesWithMergedDefinition (const NamedDecl * Def)
Get the additional modules in which the definition Def has been merged.
Definition at line 1083 of file ASTContext.cpp.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::diagnoseMissingImport(), clang::Sema::hasMergedDefinitionInCurrentModule(), clang::Sema::hasVisibleMergedDefinition(), and clang::TextNodeDumper::Visit().
getMSGuidDecl()
MSGuidDecl * ASTContext::getMSGuidDecl (MSGuidDeclParts Parts) const
Return a declaration for the global GUID object representing the given GUID value.
Definition at line 12265 of file ASTContext.cpp.
References getMSGuidType(), MSGuidTagDecl, clang::MSGuidDecl::Profile(), and clang::QualType::withConst().
Referenced by clang::Sema::BuildCXXUuidof(), and handleUuidAttr().
getMSGuidTagDecl()
TagDecl * clang::ASTContext::getMSGuidTagDecl () const inline
Retrieve the implicitly-predeclared 'struct _GUID' declaration.
Definition at line 2103 of file ASTContext.h.
References MSGuidTagDecl.
Referenced by getPredefinedDecl().
getMSGuidType()
QualType clang::ASTContext::getMSGuidType () const inline
Retrieve the implicitly-predeclared 'struct _GUID' type.
Definition at line 2106 of file ASTContext.h.
References getTagDeclType(), and MSGuidTagDecl.
Referenced by clang::Sema::ActOnCXXUuidof(), and getMSGuidDecl().
getNameForTemplate()
DeclarationNameInfo ASTContext::getNameForTemplate (TemplateName Name, SourceLocation NameLoc) const
Definition at line 6217 of file ASTContext.cpp.
References clang::TemplateName::AssumedTemplate, clang::OverloadedTemplateStorage::begin(), DeclarationNames, clang::TemplateName::DependentTemplate, clang::DeclarationNameTable::getCXXOperatorName(), clang::AssumedTemplateStorage::getDeclName(), clang::NamedDecl::getDeclName(), clang::DeclarationNameTable::getIdentifier(), clang::DependentTemplateName::getIdentifier(), clang::DependentTemplateName::getOperator(), clang::SubstTemplateTemplateParmStorage::getParameter(), clang::SubstTemplateTemplateParmPackStorage::getParameterPack(), clang::DependentTemplateName::isIdentifier(), clang::DeclarationNameLoc::makeCXXOperatorNameLoc(), clang::TemplateName::OverloadedTemplate, clang::TemplateName::QualifiedTemplate, clang::TemplateName::SubstTemplateTemplateParm, clang::TemplateName::SubstTemplateTemplateParmPack, clang::TemplateName::Template, and clang::TemplateName::UsingTemplate.
Referenced by clang::Sema::DecomposeUnqualifiedId(), and clang::Sema::GetNameFromUnqualifiedId().
getNewOMPTraitInfo()
OMPTraitInfo & ASTContext::getNewOMPTraitInfo ()
Return a new OMPTraitInfo object owned by this context.
Definition at line 13565 of file ASTContext.cpp.
Referenced by instantiateOMPDeclareVariantAttr(), and clang::ASTRecordReader::readOMPTraitInfo().
getNextLocalImport()
static ImportDecl * clang::ASTContext::getNextLocalImport (ImportDecl * Import) inline static
Definition at line 1011 of file ASTContext.h.
getNoSanitizeList()
const NoSanitizeList & clang::ASTContext::getNoSanitizeList () const inline
Definition at line 771 of file ASTContext.h.
Referenced by clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), and clang::RecordDecl::mayInsertExtraPadding().
getNSCopyingName()
IdentifierInfo * clang::ASTContext::getNSCopyingName () inline
Retrieve the identifier 'NSCopying'.
Definition at line 1877 of file ASTContext.h.
References clang::IdentifierTable::get(), and Idents.
Referenced by clang::Type::isBlockCompatibleObjCPointerType().
getNSIntegerType()
CanQualType ASTContext::getNSIntegerType () const
Definition at line 7604 of file ASTContext.cpp.
References LongLongTy, and LongTy.
Referenced by shouldNotPrintDirectly().
getNSObjectName()
IdentifierInfo * clang::ASTContext::getNSObjectName () const inline
Retrieve the identifier 'NSObject'.
Definition at line 1868 of file ASTContext.h.
References clang::IdentifierTable::get(), and Idents.
Referenced by clang::ObjCMethodDecl::definedInNSObject(), and clang::Type::isBlockCompatibleObjCPointerType().
getNSUIntegerType()
CanQualType ASTContext::getNSUIntegerType () const
Definition at line 7595 of file ASTContext.cpp.
References UnsignedLongLongTy, and UnsignedLongTy.
Referenced by shouldNotPrintDirectly().
getObjCClassDecl()
TypedefDecl * ASTContext::getObjCClassDecl () const
Retrieve the typedef declaration corresponding to the predefined Objective-C 'Class' type.
Definition at line 8735 of file ASTContext.cpp.
References buildImplicitTypedef(), getObjCObjectPointerType(), getObjCObjectType(), and ObjCBuiltinClassTy.
Referenced by getObjCClassType(), getPredefinedDecl(), and clang::Sema::Initialize().
getObjCClassRedefinitionType()
QualType clang::ASTContext::getObjCClassRedefinitionType () const inline
Retrieve the type that Class has been defined to, which may be different from the built-in Class if Class has been typedef'd.
Definition at line 1843 of file ASTContext.h.
References getObjCClassType().
Referenced by clang::Sema::CheckAssignmentConstraints(), clang::Sema::FindCompositeObjCPointerType(), and ShouldTryAgainWithRedefinitionType().
getObjCClassType()
QualType clang::ASTContext::getObjCClassType () const inline
Represents the Objective-C Class type.
This is set up lazily, by Sema. Class is always a (typedef for a) pointer type, a pointer to a struct.
Definition at line 2051 of file ASTContext.h.
References getObjCClassDecl(), and getTypeDeclType().
Referenced by clang::desugarForDiagnostic(), getObjCClassRedefinitionType(), clang::ObjCMethodDecl::getSelfType(), isObjCClassType(), LookupMemberExpr(), and clang::Sema::MergeTypedefNameDecl().
getObjCConstantStringInterface()
QualType clang::ASTContext::getObjCConstantStringInterface () const inline
Definition at line 1816 of file ASTContext.h.
Referenced by clang::Sema::BuildObjCStringLiteral().
getObjCEncodingForBlock()
std::string ASTContext::getObjCEncodingForBlock (const BlockExpr * blockExpr) const
Return the encoded type for this block declaration.
getObjCEncodingForBlock - Return the encoded type for this block declaration.
Definition at line 7681 of file ASTContext.cpp.
References clang::Type::castAs(), charUnitsToString(), clang::Type::getCanonicalTypeInternal(), getLangOpts(), getObjCEncodingForMethodParameter(), getObjCEncodingForType(), getObjCEncodingTypeSize(), clang::Expr::getType(), getTypeSizeInChars(), clang::Type::isFunctionType(), clang::CharUnits::isPositive(), clang::CharUnits::isZero(), clang::Decl::OBJC_TQ_None, and VoidPtrTy.
Referenced by buildBlockDescriptor(), and getBlockDescriptorName().
getObjCEncodingForFunctionDecl()
std::string ASTContext::getObjCEncodingForFunctionDecl (const FunctionDecl * Decl) const
Emit the encoded type for the function Decl into S.
This is in the same format as Objective-C method encodings.
Returns
true if an error occurred (e.g., because one of the parameter types is incomplete), false otherwise.
Definition at line 7737 of file ASTContext.cpp.
References charUnitsToString(), clang::Type::getCanonicalTypeInternal(), getObjCEncodingForType(), getObjCEncodingTypeSize(), clang::Type::isFunctionType(), clang::CharUnits::isPositive(), clang::CharUnits::isZero(), and clang::CharUnits::Zero().
getObjCEncodingForMethodDecl()
std::string ASTContext::getObjCEncodingForMethodDecl (const ObjCMethodDecl * Decl, bool Extended = false) const
Emit the encoded type for the method declaration Decl into S.
getObjCEncodingForMethodDecl - Return the encoded type for this method declaration.
Definition at line 7795 of file ASTContext.cpp.
References charUnitsToString(), clang::Type::getCanonicalTypeInternal(), clang::ParmVarDecl::getObjCDeclQualifier(), getObjCEncodingForMethodParameter(), getObjCEncodingTypeSize(), clang::ParmVarDecl::getOriginalType(), clang::ValueDecl::getType(), getTypeSizeInChars(), clang::Type::isFunctionType(), clang::CharUnits::isPositive(), clang::CharUnits::isZero(), and VoidPtrTy.
getObjCEncodingForMethodParameter()
void ASTContext::getObjCEncodingForMethodParameter (Decl::ObjCDeclQualifier QT, QualType T, std::string & S, bool Extended) const
getObjCEncodingForMethodParameter - Return the encoded type for a single method parameter or return type.
If Extended, include class names and block object types.
Definition at line 7778 of file ASTContext.cpp.
References getObjCEncodingForTypeQualifier().
Referenced by getObjCEncodingForBlock(), and getObjCEncodingForMethodDecl().
getObjCEncodingForPropertyDecl()
std::string ASTContext::getObjCEncodingForPropertyDecl (const ObjCPropertyDecl * PD, const Decl * Container) const
getObjCEncodingForPropertyDecl - Return the encoded type for this method declaration.
getObjCEncodingForPropertyDecl - Return the encoded type for this property declaration.
If non-NULL, Container must be either an ObjCCategoryImplDecl or ObjCImplementationDecl; it should only be NULL when getting encodings for protocol properties.
If non-NULL, Container must be either an ObjCCategoryImplDecl or ObjCImplementationDecl; it should only be NULL when getting encodings for protocol properties. Property attributes are stored as a comma-delimited C string. The simple attributes readonly and bycopy are encoded as single characters. The parametrized attributes, getter=name, setter=name, and ivar=name, are encoded as single characters, followed by an identifier. Property types are also encoded as a parametrized attribute. The characters used to encode these attributes are defined by the following enumeration:
enum PropertyAttributes {
kPropertyReadOnly = 'R',   // property is read-only.
kPropertyBycopy = 'C',     // property is a copy of the value last assigned
kPropertyByref = '&',  // property is a reference to the value last assigned
kPropertyDynamic = 'D',    // property is dynamic
kPropertyGetter = 'G',     // followed by getter selector name
kPropertySetter = 'S',     // followed by setter selector name
kPropertyInstanceVariable = 'V'  // followed by instance variable  name
kPropertyType = 'T'              // followed by old-style type encoding.
kPropertyWeak = 'W'              // 'weak' property
kPropertyStrong = 'P'            // property GC'able
kPropertyNonAtomic = 'N'         // property non-atomic
};
Definition at line 7892 of file ASTContext.cpp.
References clang::ObjCPropertyDecl::Assign, clang::ObjCPropertyDecl::Copy, clang::ObjCPropertyImplDecl::Dynamic, clang::Selector::getAsString(), clang::ObjCPropertyDecl::getGetterName(), clang::NamedDecl::getNameAsString(), getObjCEncodingForPropertyType(), getObjCPropertyImplDeclForPropertyDecl(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::ObjCPropertyDecl::getSetterKind(), clang::ObjCPropertyDecl::getSetterName(), clang::ObjCPropertyDecl::getType(), clang::ObjCPropertyDecl::isReadOnly(), clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_getter, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_weak, clang::ObjCPropertyDecl::Retain, and clang::ObjCPropertyDecl::Weak.
getObjCEncodingForPropertyType()
void ASTContext::getObjCEncodingForPropertyType (QualType T, std::string & S) const
Emit the Objective-C property type encoding for the given type T into S.
Definition at line 7990 of file ASTContext.cpp.
Referenced by getObjCEncodingForPropertyDecl().
getObjCEncodingForType()
void ASTContext::getObjCEncodingForType (QualType T, std::string & S, const FieldDecl * Field = nullptr, QualType * NotEncodedT = nullptr) const
Emit the Objective-CC type encoding for the given type T into S.
If Field is specified then record field names are also encoded.
Definition at line 7975 of file ASTContext.cpp.
Referenced by clang::Sema::BuildObjCEncodeExpression(), extractStringLiteralCharacter(), clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromObjCEncode(), getObjCEncodingForBlock(), and getObjCEncodingForFunctionDecl().
getObjCEncodingForTypeQualifier()
void ASTContext::getObjCEncodingForTypeQualifier (Decl::ObjCDeclQualifier QT, std::string & S) const
Put the string version of the type qualifiers QT into S.
Definition at line 8702 of file ASTContext.cpp.
References clang::Decl::OBJC_TQ_Bycopy, clang::Decl::OBJC_TQ_Byref, clang::Decl::OBJC_TQ_In, clang::Decl::OBJC_TQ_Inout, clang::Decl::OBJC_TQ_Oneway, and clang::Decl::OBJC_TQ_Out.
Referenced by getObjCEncodingForMethodParameter().
getObjCEncodingTypeSize()
CharUnits ASTContext::getObjCEncodingTypeSize (QualType T) const
Return the size of type T for Objective-C encoding purpose, in characters.
getObjCEncodingTypeSize returns size of type for objective-c encoding purpose.
Definition at line 7632 of file ASTContext.cpp.
References getTypeSizeInChars(), IntTy, clang::CharUnits::isPositive(), VoidPtrTy, and clang::CharUnits::Zero().
Referenced by getObjCEncodingForBlock(), getObjCEncodingForFunctionDecl(), and getObjCEncodingForMethodDecl().
getObjCGCAttrKind()
Qualifiers::GC ASTContext::getObjCGCAttrKind (QualType Ty) const
Return one of the GCNone, Weak or Strong Objective-C garbage collection attributes.
getObjCGCAttr - Returns one of GCNone, Weak or Strong objc's garbage collection attribute.
Definition at line 9382 of file ASTContext.cpp.
References clang::Type::castAs(), clang::Qualifiers::GCNone, clang::Type::getCanonicalTypeInternal(), getLangOpts(), clang::QualType::getObjCGCAttr(), getObjCGCAttrKind(), clang::PointerType::getPointeeType(), clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), clang::LangOptions::NonGC, clang::ObjC, and clang::Qualifiers::Strong.
Referenced by getObjCGCAttrKind(), and clang::Expr::isOBJCGCCandidate().
getObjCGCQualType()
QualType ASTContext::getObjCGCQualType (QualType T, Qualifiers::GC gcAttr) const
Return the uniqued reference to the type for an Objective-C gc-qualified type.
The resulting type has a union of the qualifiers from T and the gc attribute.
Definition at line 3123 of file ASTContext.cpp.
References clang::Qualifiers::addObjCGCAttr(), getCanonicalType(), clang::QualType::getObjCGCAttr(), getObjCGCQualType(), clang::Type::getPointeeType(), getPointerType(), clang::Qualifiers::hasObjCGCAttr(), clang::Type::isAnyPointerType(), and clang::QualifierCollector::strip().
Referenced by clang::Sema::ActOnPropertyImplDecl(), getObjCGCQualType(), handleObjCGCTypeAttr(), and mergeTypes().
getObjCIdDecl()
TypedefDecl * ASTContext::getObjCIdDecl () const
Retrieve the typedef corresponding to the predefined id type in Objective-C.
Definition at line 8718 of file ASTContext.cpp.
References buildImplicitTypedef(), getObjCObjectPointerType(), getObjCObjectType(), and ObjCBuiltinIdTy.
Referenced by getObjCIdType(), getPredefinedDecl(), and clang::Sema::Initialize().
getObjCIdRedefinitionType()
QualType clang::ASTContext::getObjCIdRedefinitionType () const inline
Retrieve the type that id has been defined to, which may be different from the built-in id if id has been typedef'd.
Definition at line 1830 of file ASTContext.h.
References getObjCIdType().
Referenced by clang::Sema::FindCompositeObjCPointerType(), and ShouldTryAgainWithRedefinitionType().
getObjCIdType()
QualType clang::ASTContext::getObjCIdType () const inline
Represents the Objective-CC id type.
This is set up lazily, by Sema. id is always a (typedef for a) pointer type, a pointer to a struct.
Definition at line 2029 of file ASTContext.h.
References getObjCIdDecl(), and getTypeDeclType().
Referenced by clang::Sema::ActOnFinishFullExpr(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::actOnObjCTypeParam(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCPropertySynthesizeIvar(), DecodeTypeFromStr(), clang::Sema::deduceVarTypeFromInitializer(), clang::desugarForDiagnostic(), clang::Sema::FindCompositeObjCPointerType(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getObjCIdRedefinitionType(), getObjCInstanceTypeDecl(), clang::ObjCMethodDecl::getSelfType(), isObjCIdType(), clang::Sema::MergeTypedefNameDecl(), clang::Sema::PerformContextuallyConvertToObjCPointer(), stripObjCInstanceType(), and TryContextuallyConvertToObjCPointer().
getObjCImplementation() [1/2]
ObjCCategoryImplDecl * ASTContext::getObjCImplementation (ObjCCategoryDecl * D)
Get the implementation of the ObjCCategoryDecl D, or nullptr if none exists.
Get the implementation of ObjCCategoryDecl, or nullptr if none exists.
Definition at line 2925 of file ASTContext.cpp.
References clang::cast().
getObjCImplementation() [2/2]
ObjCImplementationDecl * ASTContext::getObjCImplementation (ObjCInterfaceDecl * D)
Get the implementation of the ObjCInterfaceDecl D, or nullptr if none exists.
Get the implementation of ObjCInterfaceDecl, or nullptr if none exists.
Definition at line 2915 of file ASTContext.cpp.
References clang::cast().
Referenced by clang::ObjCCategoryDecl::getImplementation(), and clang::ObjCInterfaceDecl::getImplementation().
getObjCInstanceType()
QualType clang::ASTContext::getObjCInstanceType () inline
Retrieve the Objective-C "instancetype" type, if already known; otherwise, returns a NULL type;.
Definition at line 1910 of file ASTContext.h.
References getObjCInstanceTypeDecl(), and getTypeDeclType().
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnObjCInstanceType(), clang::Sema::EmitRelatedResultTypeNote(), clang::Sema::EmitRelatedResultTypeNoteForReturn(), clang::ObjCMessageExpr::getCallReturnType(), clang::Sema::getMessageSendResultType(), ReplaceWithInstancetype(), and stripObjCInstanceType().
getObjCInstanceTypeDecl()
TypedefDecl * ASTContext::getObjCInstanceTypeDecl ()
Retrieve the typedef declaration corresponding to the Objective-C "instancetype" type.
Definition at line 7613 of file ASTContext.cpp.
References buildImplicitTypedef(), and getObjCIdType().
Referenced by getObjCInstanceType(), getPredefinedDecl(), and handleFormatArgAttr().
getObjCInterfaceType()
QualType ASTContext::getObjCInterfaceType (const ObjCInterfaceDecl * Decl, ObjCInterfaceDecl * PrevDecl = nullptr) const
getObjCInterfaceType - Return the unique reference to the type for the specified ObjC interface decl.
The list of protocols is optional.
Definition at line 5620 of file ASTContext.cpp.
References Allocate(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ActOnStartCategoryImplementation(), clang::Sema::ActOnStartCategoryInterface(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnSuperClassOfClassInterface(), areCommonBaseCompatible(), clang::Sema::BuildClassMessage(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::BuildReturnStmt(), clang::Sema::CheckObjCBridgeRelatedConversions(), clang::Sema::CheckObjCMethodOverride(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CodeCompleteObjCSuperMessage(), getBaseMessageSendResultType(), clang::Sema::getMessageSendResultType(), getNSNumberFactoryMethod(), clang::Sema::getObjCMessageKind(), getObjCProtoType(), clang::ObjCPropertyRefExpr::getReceiverType(), GetReturnType(), clang::ObjCMethodDecl::getSelfType(), clang::Sema::getTypeName(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), LookupMethodInReceiverType(), setObjCConstantStringInterface(), and clang::ASTNodeImporter::VisitObjCInterfaceType().
getObjCMethodRedeclaration()
const ObjCMethodDecl * ASTContext::getObjCMethodRedeclaration (const ObjCMethodDecl * MD) const
Get the duplicate declaration of a ObjCMethod in the same interface, or null if none exists.
Definition at line 2948 of file ASTContext.cpp.
Referenced by setObjCMethodRedeclaration(), and clang::ASTDeclWriter::VisitObjCMethodDecl().
getObjCNSStringType()
QualType clang::ASTContext::getObjCNSStringType () const inline
Definition at line 1820 of file ASTContext.h.
Referenced by clang::Sema::BuildObjCStringLiteral().
getObjCObjectPointerType()
QualType ASTContext::getObjCObjectPointerType (QualType OIT) const
Return a ObjCObjectPointerType type for the given ObjCObjectType.
getObjCObjectPointerType - Return a ObjCObjectPointerType type for the given object type.
Definition at line 5590 of file ASTContext.cpp.
References Allocate(), getCanonicalType(), getObjCObjectPointerType(), clang::QualType::isCanonical(), clang::ObjCObjectPointerType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::ActOnFields(), clang::Sema::actOnObjCProtocolQualifierType(), clang::Sema::actOnObjCTypeParam(), clang::Sema::ActOnSuperMessage(), applyObjCProtocolQualifiers(), areCommonBaseCompatible(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::BuildReturnStmt(), BuildSimilarlyQualifiedPointerType(), canBindObjCObjectType(), clang::Sema::CheckAddressOfOperand(), checkObjCKindOfType(), clang::Sema::CheckParameter(), clang::Sema::CheckVariableDeclarationType(), clang::Sema::CodeCompleteObjCInstanceMessage(), clang::Sema::CreatePropertyDecl(), clang::desugarForDiagnostic(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), clang::Sema::FindCompositePointerType(), getBaseMessageSendResultType(), getCommonNonSugarTypeNode(), GetFullTypeForDeclarator(), clang::ento::TypedValueRegion::getLocationType(), clang::Sema::getMessageSendResultType(), getNSNumberFactoryMethod(), getObjCClassDecl(), getObjCIdDecl(), getObjCObjectPointerType(), GetReturnType(), clang::ObjCMethodDecl::getSelfType(), clang::ObjCObjectPointerType::getSuperClassType(), handleFormatArgAttr(), clang::Sema::ParseObjCProtocolExpression(), clang::Sema::PerformImplicitConversion(), clang::TreeTransform< Derived >::RebuildObjCObjectPointerType(), clang::ObjCObjectPointerType::stripObjCKindOfTypeAndQuals(), and clang::ASTNodeImporter::VisitObjCObjectPointerType().
getObjCObjectType() [1/2]
QualType ASTContext::getObjCObjectType (QualType Base, ArrayRef< QualType > typeArgs, ArrayRef< ObjCProtocolDecl * > protocols, bool isKindOf) const
Definition at line 5329 of file ASTContext.cpp.
References Allocate(), areSortedAndUniqued(), clang::Type::getAs(), getCanonicalType(), getObjCObjectType(), clang::QualType::isCanonical(), SortAndUniqueProtocols(), and clang::TypeAlignment.
getObjCObjectType() [2/2]
QualType ASTContext::getObjCObjectType (QualType Base, ObjCProtocolDecl *const * Protocols, unsigned NumProtocols) const
Legacy interface: cannot provide type arguments or __kindof.
Definition at line 5321 of file ASTContext.cpp.
References getObjCObjectType().
Referenced by clang::Sema::actOnObjCProtocolQualifierType(), applyObjCProtocolQualifiers(), applyObjCTypeArgs(), areCommonBaseCompatible(), clang::Sema::BuildObjCDictionaryLiteral(), checkObjCKindOfType(), clang::desugarForDiagnostic(), getCommonNonSugarTypeNode(), getObjCClassDecl(), getObjCIdDecl(), getObjCObjectType(), getObjCObjectType(), clang::Type::getObjCSubstitutions(), and clang::ASTNodeImporter::VisitObjCObjectType().
getObjContainingInterface()
const ObjCInterfaceDecl * ASTContext::getObjContainingInterface (const NamedDecl * ND) const
Returns the Objective-C interface that ND belongs to if it is an Objective-C method/property/ivar etc.
that is part of an interface, otherwise returns null.
Definition at line 2958 of file ASTContext.cpp.
References clang::Decl::getDeclContext().
Referenced by clang::edit::rewriteToObjCSubscriptSyntax().
getObjCPropertyImplDeclForPropertyDecl()
ObjCPropertyImplDecl * ASTContext::getObjCPropertyImplDeclForPropertyDecl (const ObjCPropertyDecl * PD, const Decl * Container) const
Definition at line 7848 of file ASTContext.cpp.
References clang::cast().
Referenced by getObjCEncodingForPropertyDecl().
getObjCProtocolDecl()
ObjCInterfaceDecl * ASTContext::getObjCProtocolDecl () const
Retrieve the Objective-C class declaration corresponding to the predefined Protocol class.
Definition at line 8744 of file ASTContext.cpp.
References clang::ObjCInterfaceDecl::Create(), clang::IdentifierTable::get(), getTranslationUnitDecl(), and Idents.
Referenced by getObjCProtoType(), getPredefinedDecl(), and clang::Sema::Initialize().
getObjCProtoType()
QualType clang::ASTContext::getObjCProtoType () const inline
Retrieve the type of the Objective-C Protocol class.
Definition at line 2075 of file ASTContext.h.
References getObjCInterfaceType(), and getObjCProtocolDecl().
Referenced by clang::desugarForDiagnostic(), and clang::Sema::ParseObjCProtocolExpression().
getObjCSelDecl()
TypedefDecl * ASTContext::getObjCSelDecl () const
Retrieve the typedef corresponding to the predefined 'SEL' type in Objective-C.
Definition at line 8727 of file ASTContext.cpp.
References buildImplicitTypedef(), getPointerType(), and ObjCBuiltinSelTy.
Referenced by getObjCSelType(), getPredefinedDecl(), and clang::Sema::Initialize().
getObjCSelRedefinitionType()
QualType clang::ASTContext::getObjCSelRedefinitionType () const inline
Retrieve the type that 'SEL' has been defined to, which may be different from the built-in 'SEL' if 'SEL' has been typedef'd.
Definition at line 1856 of file ASTContext.h.
References getObjCSelType().
Referenced by clang::Sema::FindCompositeObjCPointerType(), and LookupMemberExpr().
getObjCSelType()
QualType clang::ASTContext::getObjCSelType () const inline
Retrieve the type that corresponds to the predefined Objective-C 'SEL' type.
Definition at line 2039 of file ASTContext.h.
References getObjCSelDecl(), and getTypeDeclType().
Referenced by clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), clang::ObjCMethodDecl::createImplicitParams(), DecodeTypeFromStr(), clang::desugarForDiagnostic(), emitCmdValueForGetterSetterBody(), getObjCSelRedefinitionType(), isObjCSelType(), clang::Sema::MergeTypedefNameDecl(), and clang::Sema::ParseObjCSelectorExpression().
getObjCSuperType()
QualType ASTContext::getObjCSuperType () const
Returns the C struct type for objc_super.
Definition at line 7399 of file ASTContext.cpp.
References clang::DeclContext::addDecl(), buildImplicitRecord(), getTagDeclType(), getTranslationUnitDecl(), and clang::QualType::isNull().
Referenced by DecodeTypeFromStr().
getObjCTypeParamType()
QualType ASTContext::getObjCTypeParamType (const ObjCTypeParamDecl * Decl, ArrayRef< ObjCProtocolDecl * > protocols) const
Definition at line 5481 of file ASTContext.cpp.
References Allocate(), applyObjCProtocolQualifiers(), getCanonicalType(), and clang::TypeAlignment.
Referenced by adjustObjCTypeParamBoundType(), applyObjCProtocolQualifiers(), and clang::ObjCTypeParamDecl::Create().
getOffsetOfBaseWithVBPtr()
CharUnits ASTContext::getOffsetOfBaseWithVBPtr (const CXXRecordDecl * RD) const
Loading virtual member pointers using the virtual inheritance model always results in an adjustment using the vbtable even if the index is zero.
This is usually OK because the first slot in the vbtable points backwards to the top of the MDC. However, the MDC might be reusing a vbptr from an nv-base. In this case, the first slot in the vbtable points to the start of the nv-base which introduced the vbptr and not the MDC. Modify the NonVirtualBaseAdjustment to account for this.
Definition at line 2576 of file ASTContext.cpp.
References getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getBaseSharingVBPtr(), Offset, and clang::CharUnits::Zero().
getOpenCLTypeAddrSpace()
LangAS ASTContext::getOpenCLTypeAddrSpace (const Type * T) const
Get address space for OpenCL type.
Definition at line 7526 of file ASTContext.cpp.
References getOpenCLTypeKind().
Referenced by clang::CodeGen::CGOpenCLRuntime::getPipeType(), clang::CodeGen::CGOpenCLRuntime::getPointerType(), and clang::CodeGen::CGOpenCLRuntime::getSamplerType().
getOpenCLTypeKind()
OpenCLTypeKind ASTContext::getOpenCLTypeKind (const Type * T) const
Map an AST Type to an OpenCLTypeKind enum value.
Definition at line 7490 of file ASTContext.cpp.
References clang::OCLTK_ClkEvent, clang::OCLTK_Default, clang::OCLTK_Event, clang::OCLTK_Pipe, clang::OCLTK_Queue, clang::OCLTK_ReserveID, and clang::OCLTK_Sampler.
Referenced by getOpenCLTypeAddrSpace().
getOpenMPDefaultSimdAlign()
unsigned ASTContext::getOpenMPDefaultSimdAlign (QualType T) const
Get default simd alignment of the specified complete type in bits.
Definition at line 2455 of file ASTContext.cpp.
References clang::TargetOptions::FeatureMap, getTargetInfo(), and clang::TargetInfo::getTargetOpts().
Referenced by emitAlignedClause(), and GetAlignedMapping().
getOverloadedTemplateName()
TemplateName ASTContext::getOverloadedTemplateName (UnresolvedSetIterator Begin, UnresolvedSetIterator End) const
Retrieve the template name that corresponds to a non-empty lookup.
Definition at line 9187 of file ASTContext.cpp.
References Allocate(), Begin, and clang::NamedDecl::getUnderlyingDecl().
Referenced by clang::Sema::ClassifyName(), clang::ASTImporter::Import(), and clang::Sema::isTemplateName().
getOverriddenMethods()
void ASTContext::getOverriddenMethods (const NamedDecl * Method, SmallVectorImpl< const NamedDecl * > & Overridden) const
Return C++ or ObjC overridden methods for the given Method.
An ObjC method is considered to override any method in the class's base classes, its protocols, or its categories' protocols, that has the same selector and is of the same kind (class or instance). A method in an implementation is not considered as overriding the same method in the interface or its categories.
Definition at line 1608 of file ASTContext.cpp.
References overridden_methods_begin(), and overridden_methods_end().
Referenced by getCommentForDecl().
getPackExpansionType()
QualType ASTContext::getPackExpansionType (QualType Pattern, std::optional< unsigned > NumExpansions, bool ExpectPackInType = true)
Form a pack expansion type with the given pattern.
Parameters
NumExpansions The number of expansions for the pack, if known.
ExpectPackInType If false, we should not expect Pattern to contain an unexpanded pack. This only makes sense if the pack expansion is used in a context where the arity is inferred from elsewhere, such as if the pattern contains a placeholder type or if this is the canonical type of another pack expansion type.
Definition at line 5256 of file ASTContext.cpp.
References clang::Type::containsUnexpandedParameterPack(), getCanonicalType(), getPackExpansionType(), clang::QualType::isCanonical(), and clang::TypeAlignment.
Referenced by clang::Sema::buildLambdaInitCaptureInitialization(), clang::Sema::CheckPackExpansion(), getCommonNonSugarTypeNode(), GetFullTypeForDeclarator(), getInjectedTemplateArg(), getPackExpansionType(), clang::TreeTransform< Derived >::TransformExceptionSpec(), and clang::ASTNodeImporter::VisitPackExpansionType().
getParameterIndex()
unsigned ASTContext::getParameterIndex (const ParmVarDecl * D) const
Used by ParmVarDecl to retrieve on the side the index of the parameter when it exceeds the size of the normal bitfield.
Definition at line 12232 of file ASTContext.cpp.
getParentMapContext()
ParentMapContext & ASTContext::getParentMapContext ()
Returns the dynamic AST node parent map context.
Definition at line 904 of file ASTContext.cpp.
Referenced by getParents(), getParents(), and setTraversalScope().
getParents() [1/2]
template<> DynTypedNodeList clang::ASTContext::getParents (const DynTypedNode & Node) inline
Definition at line 136 of file ParentMapContext.h.
References getParentMapContext(), clang::ParentMapContext::getParents(), and Node.
getParents() [2/2]
template<typename NodeT > DynTypedNodeList clang::ASTContext::getParents (const NodeT & Node) inline
Forwards to get node parents from the ParentMapContext.
New callers should use ParentMapContext::getParents() directly.
Definition at line 131 of file ParentMapContext.h.
References getParentMapContext(), clang::ParentMapContext::getParents(), and Node.
Referenced by clang::diff::getEnclosingDeclContext().
getParenType()
QualType ASTContext::getParenType (QualType NamedType) const
Definition at line 5087 of file ASTContext.cpp.
References getCanonicalType(), clang::QualType::isCanonical(), clang::ParenType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildParenType(), getCommonSugarTypeNode(), getFunctionTypeWithExceptionSpec(), TryToFixInvalidVariablyModifiedType(), and clang::ASTNodeImporter::VisitParenType().
getPointerDiffType()
QualType ASTContext::getPointerDiffType () const
Return the unique type for "ptrdiff_t" (C99 7.17) defined in <stddef.h>.
getPointerDiffType - Return the unique type for "ptrdiff_t" (C99 7.17) defined in <stddef.h>.
Pointer - pointer requires this (C99 6.5.6p9).
Definition at line 5996 of file ASTContext.cpp.
References clang::Default.
Referenced by clang::ento::RangedConstraintManager::assumeSym(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::CheckSubtractionOperands(), clang::CodeGen::CGCXXABI::ConvertMemberPointerType(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), clang::ento::SMTConv::getBinExpr(), getItaniumDynamicCastFn(), getPreferredTypeAlign(), getPreferredTypeOfBinaryRHS(), clang::Sema::Initialize(), performTypeAdjustment(), and RVVType2Qual().
getPointerType() [1/2]
CanQualType clang::ASTContext::getPointerType (CanQualType T) const inline
Definition at line 1323 of file ASTContext.h.
References clang::CanQual< Type >::CreateUnsafe(), and getPointerType().
getPointerType() [2/2]
QualType ASTContext::getPointerType (QualType T) const
Return the uniqued reference to the type for a pointer to the specified type.
getPointerType - Return the uniqued reference to the type for a pointer to the specified type.
Definition at line 3316 of file ASTContext.cpp.
References getCanonicalType(), getPointerType(), clang::PointerType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnAddrLabel(), clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnIndirectGotoStmt(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPRegionStart(), clang::Sema::ActOnSourceLocExpr(), clang::Sema::AddConversionCandidate(), AddDirectArgument(), addFunctionPointerConversion(), adjustCVQualifiersForCXXThisWithinLambda(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildExceptionDeclaration(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), buildMemcpyForAssignmentOp(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildPointerType(), clang::Sema::BuildResolvedCallExpr(), BuildSimilarlyQualifiedPointerType(), clang::Sema::CallExprUnaryConversions(), castValueFromUintptr(), clang::Sema::CheckAddressOfOperand(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), checkConditionalBlockPointerCompatibility(), checkConditionalObjectPointersCompatibility(), checkConditionalPointerCompatibility(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckMain(), checkOpenCLPipePacketType(), clang::Sema::checkOpenMPDeclareVariantFunction(), CheckOperatorDeleteDeclaration(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::CheckSpecifiedExceptionType(), CheckTemplateArgumentAddressOfObjectOrFunction(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::SValBuilder::conjureSymbolVal(), clang::Sema::ConstantFoldAttrArgs(), clang::SYCLUniqueStableNameExpr::Create(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateCharPtrNamedVaListDecl(), clang::SYCLUniqueStableNameExpr::CreateEmpty(), CreateFunctionRefExpr(), CreateHexagonBuiltinVaListDecl(), clang::Sema::CreateOverloadedBinOp(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateVoidPtrBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), clang::CStyleCastPtrExpr(), clang::Sema::CXXThisScopeRAII::CXXThisScopeRAII(), clang::Sema::DeclareGlobalNewDelete(), DecodePPCMMATypeFromStr(), DecodeTypeFromStr(), decomposeTypeForEH(), clang::Sema::DeduceReturnType(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DefaultFunctionArrayConversion(), clang::CodeGen::CodeGenTypes::DeriveThisType(), clang::desugarForDiagnostic(), clang::APValue::dump(), emitDeclTargetVarDeclLValue(), EmitFunctionDeclPointer(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), GeneralizeType(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), getArrayDecayedType(), getBlockDescriptorExtendedType(), getCanonicalParamType(), getCFConstantStringDecl(), getCommonNonSugarTypeNode(), clang::Sema::getCurrentThisType(), clang::ento::SValBuilder::getCXXThis(), getDecayedType(), getDeclAlign(), getErrnoFunc(), clang::TypeName::getFullyQualifiedType(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::FunctionCodeRegion::getLocationType(), clang::ento::TypedValueRegion::getLocationType(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getObjCGCQualType(), getObjCSelDecl(), getPointerType(), getPointerType(), getPreferredTypeOfUnaryArg(), GetTypeOfFunction(), getVariableArrayDecayedType(), handleCleanupAttr(), handleMSPointerTypeQualifierAttr(), HandleWebAssemblyFuncrefAttr(), InitBuiltinTypes(), clang::Sema::isObjCPointerConversion(), clang::Sema::isObjCWritebackConversion(), IsStandardConversion(), LookupMemberExpr(), LookupStdSourceLocationImpl(), clang::ento::SValBuilder::makeNullWithType(), mergeTypes(), NoteSurrogateCandidate(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectMemberConversion(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), recordFixedType(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), RemoveAddressSpaceFromPtr(), removePtrSizeAddrSpace(), ResolveOverloadForDeduction(), rewriteBuiltinFunctionDecl(), RVVType2Qual(), SemaBuiltinCallWithStaticChain(), SemaBuiltinLaunder(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinToAddr(), clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter(), TryConstCast(), tryObjCWritebackConversion(), TryReinterpretCast(), clang::ConversionFixItGenerator::tryToFixConversion(), TryToFixInvalidVariablyModifiedType(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitDeclStmt(), and clang::ASTNodeImporter::VisitPointerType().
getPredefinedStringLiteralFromCache()
StringLiteral * ASTContext::getPredefinedStringLiteralFromCache (StringRef Key) const
Return a string representing the human readable name for the specified function declaration or file name.
Used by SourceLocExpr and PredefinedExpr to cache evaluated results.
Definition at line 12254 of file ASTContext.cpp.
References CharTy, clang::StringLiteral::Create(), getStringLiteralArrayType(), clang::StringLiteral::Ordinary, and clang::Result.
Referenced by clang::SourceLocExpr::EvaluateInContext().
getPreferredTypeAlign() [1/2]
unsigned ASTContext::getPreferredTypeAlign (const Type * T) const
getPreferredTypeAlign - Return the "preferred" alignment of the specified type for the current target in bits.
This can be different than the ABI alignment in cases where it is beneficial for performance or backwards compatibility preserving to overalign a data type. (Note: despite the name, the preferred alignment is ABI-impacting, and not an optimization.)
Definition at line 2504 of file ASTContext.cpp.
References clang::TypeInfo::Align, clang::TypeInfo::AlignRequirement, getASTRecordLayout(), getPointerDiffType(), getPreferredTypeAlign(), getTypeInfo(), getTypeSize(), clang::TypeInfo::isAlignRequired(), clang::Decl::isInvalidDecl(), clang::RequiredByTypedef, and toBits().
getPreferredTypeAlign() [2/2]
unsigned clang::ASTContext::getPreferredTypeAlign (QualType T) const inline
Return the "preferred" alignment of the specified type T for the current target, in bits.
This can be different than the ABI alignment in cases where it is beneficial for performance or backwards compatibility preserving to overalign a data type. (Note: despite the name, the preferred alignment is ABI-impacting, and not an optimization.)
Definition at line 2387 of file ASTContext.h.
References getPreferredTypeAlign().
Referenced by AlignOfType(), getAlignOfGlobalVar(), GetAlignOfType(), getDeclAlign(), getPreferredTypeAlign(), getPreferredTypeAlign(), getPreferredTypeAlignInChars(), and getTypeAlignIfKnown().
getPreferredTypeAlignInChars()
CharUnits clang::ASTContext::getPreferredTypeAlignInChars (QualType T) const inline
Return the PreferredAlignment of a (complete) type T, in characters.
Definition at line 2355 of file ASTContext.h.
References getPreferredTypeAlign(), and toCharUnitsFromBits().
getPrimaryMergedDecl()
Decl * clang::ASTContext::getPrimaryMergedDecl (Decl * D) inline
Definition at line 1021 of file ASTContext.h.
References clang::Result.
Referenced by clang::getPrimaryMergedDecl().
getPrintingPolicy()
const clang::PrintingPolicy & clang::ASTContext::getPrintingPolicy () const inline
Definition at line 683 of file ASTContext.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnFinishKNRParamDeclarations(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::CodeGen::CodeGenTypes::addRecordTypeName(), annotateConsumedSummaryMismatch(), clang::Sema::BuildAnonymousStructOrUnion(), checkTypeParamListConsistency(), convertCallArgsToString(), ConvertDeclSpecToType(), ConvertTypeToDiagnosticString(), clang::ExtractAPIAction::CreateASTConsumer(), clang::WrappingExtractAPIAction::CreateASTConsumer(), clang::Decl::dump(), clang::ento::CallEvent::dump(), clang::DeclContext::dumpDeclContext(), clang::Expr::EvaluateWithSubstitution(), clang::FormatASTNodeDiagnosticArgument(), generateDiagnosticsForCallLike(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::GetFullTypeName(), clang::Sema::getPrintingPolicy(), getTupleLikeElementType(), clang::Sema::ImplicitlyDefineFunction(), clang::Expr::isPotentialConstantExpr(), isTupleLike(), lookupStdTypeTraitMember(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::PrettyDeclStackTraceEntry::print(), print(), printIndicesOfElementsToConstructJson(), clang::ento::Environment::printJson(), clang::ProgramPoint::printJson(), printObjectsUnderConstructionJson(), printPendingInitLoopJson(), clang::APValue::printPretty(), rewriteToNSMacroDecl(), rewriteToObjCProperty(), clang::TextNodeDumper::VisitUnresolvedUsingTypenameDecl(), clang::TextNodeDumper::VisitUnresolvedUsingValueDecl(), clang::JSONNodeDumper::VisitUsingDecl(), clang::TextNodeDumper::VisitUsingDecl(), and WarnUndefinedMethod().
getProcessIDType()
QualType ASTContext::getProcessIDType () const
Return the unique type for "pid_t" defined in <sys/types.h>.
We need this to compute the correct type for vfork().
Definition at line 6009 of file ASTContext.cpp.
Referenced by DecodeTypeFromStr().
getProfileList()
const ProfileList & clang::ASTContext::getProfileList () const inline
Definition at line 777 of file ASTContext.h.
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList().
getPromotedIntegerType()
QualType ASTContext::getPromotedIntegerType (QualType PromotableType) const
Return the type that PromotableType will promote to: C99 6.3.1.1p2, assuming that PromotableType is a promotable integer type.
getPromotedIntegerType - Returns the type that Promotable will promote to: C99 6.3.1.1p2, assuming that Promotable is a promotable integer type.
Definition at line 7188 of file ASTContext.cpp.
References clang::Type::getAs(), getIntWidth(), getTypeSize(), IntTy, clang::QualType::isNull(), isPromotableIntegerType(), clang::Type::isSignedIntegerType(), clang::Type::isUnsignedIntegerType(), LongLongTy, LongTy, UnsignedIntTy, UnsignedLongLongTy, and UnsignedLongTy.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnTag(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckAdditionOperands(), checkArithmeticOrEnumeralThreeWayCompare(), clang::ento::SMTConv::doIntTypeConversion(), GetFullTypeForDeclarator(), isArithmeticArgumentPromotion(), clang::Sema::UsualArithmeticConversions(), and clang::Sema::UsualUnaryConversions().
getQualifiedTemplateName()
TemplateName ASTContext::getQualifiedTemplateName (NestedNameSpecifier * NNS, bool TemplateKeyword, TemplateName Template) const
Retrieve the template name that represents a qualified template name such as std::vector.
Definition at line 9218 of file ASTContext.cpp.
References clang::QualifiedTemplateName::Profile().
Referenced by clang::Sema::ActOnTemplateTypeArgument(), clang::Sema::ClassifyName(), clang::TypeName::getFullyQualifiedTemplateName(), clang::ASTImporter::Import(), clang::Sema::isTemplateName(), and clang::TreeTransform< Derived >::RebuildTemplateName().
getQualifiedType() [1/3]
QualType clang::ASTContext::getQualifiedType (const Type * T, Qualifiers Qs) const inline
Return a type with additional qualifiers.
Definition at line 2136 of file ASTContext.h.
References clang::Qualifiers::getFastQualifiers(), and clang::Qualifiers::hasNonFastQualifiers().
getQualifiedType() [2/3]
QualType clang::ASTContext::getQualifiedType (QualType T, Qualifiers Qs) const inline
Return a type with additional qualifiers.
Definition at line 2127 of file ASTContext.h.
References clang::Qualifiers::getFastQualifiers(), clang::Qualifiers::hasNonFastQualifiers(), clang::QualifierCollector::strip(), and clang::QualType::withFastQualifiers().
getQualifiedType() [3/3]
QualType clang::ASTContext::getQualifiedType (SplitQualType split) const inline
Un-split a SplitQualType.
Definition at line 2122 of file ASTContext.h.
References getQualifiedType(), clang::SplitQualType::Quals, and clang::SplitQualType::Ty.
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnPropertyImplDecl(), AddImplicitObjectParameterType(), AdoptQualifiers(), clang::QualifierCollector::apply(), clang::QualifierCollector::apply(), clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildFieldReferenceExpr(), BuildImplicitBaseInitializer(), clang::Sema::BuildMemberExpr(), clang::Sema::BuildQualifiedType(), BuildSimilarlyQualifiedPointerType(), clang::Sema::BuiltinChangeCVRQualifiers(), clang::Sema::BuiltinChangeSignedness(), clang::Sema::BuiltinDecay(), clang::Sema::BuiltinRemoveReference(), checkARCPropertyImpl(), checkBlockPointerTypesForAssignment(), checkComplexDecomposition(), checkConditionalObjectPointersCompatibility(), checkConditionalPointerCompatibility(), checkMemberDecomposition(), CheckOriginalCallArgDeduction(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::CheckTemplateTypeArgument(), checkVectorDecomposition(), CompareStandardConversionSequences(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CXXThisScopeRAII::CXXThisScopeRAII(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), getArrayDecayedType(), getAsArrayType(), getBaseElementType(), getCanonicalFunctionResultType(), getCommonSugaredType(), getCommonSugarTypeNode(), getConstantArrayType(), getCVRQualifiedType(), getDependentSizedArrayType(), clang::TypeName::getFullyQualifiedType(), getIncompleteArrayType(), getLifetimeQualifiedType(), getNonMemoryType(), getQualifiedType(), clang::ObjCMethodDecl::getSelfType(), getUnconstrainedType(), getUnqualifiedObjCPointerType(), getVariableArrayDecayedType(), getVariableArrayType(), handleObjCOwnershipTypeAttr(), clang::ASTImporter::Import(), inferARCLifetimeForPointee(), inferARCWriteback(), InitBuiltinTypes(), clang::Sema::isObjCWritebackConversion(), isSubstitutedType(), LookupMemberExpr(), clang::TreeTransform< Derived >::RebuildQualifiedType(), RemoveAddressSpaceFromPtr(), rewriteToObjCProperty(), SemaOpenCLBuiltinToAddr(), transferARCOwnershipToDeclSpec(), TryObjectArgumentInitialization(), TryReferenceInitializationCore(), TryReferenceListInitialization(), TryRefInitWithConversionFunction(), and withoutUnaligned().
getRawCFConstantStringType()
QualType clang::ASTContext::getRawCFConstantStringType () const inline
Get the structure type used to representation CFStrings, or NULL if it hasn't yet been built.
Definition at line 1805 of file ASTContext.h.
References getTypedefType().
getRawCommentForAnyRedecl()
const RawComment * ASTContext::getRawCommentForAnyRedecl (const Decl * D, const Decl ** OriginalDecl = nullptr) const
Return the documentation comment attached to a given declaration.
Returns nullptr if no comment is attached.
Parameters
OriginalDecl if not nullptr, is set to declaration AST node that had the comment, if the comment we found comes from a redeclaration.
Definition at line 461 of file ASTContext.cpp.
References adjustDeclToTemplate(), cacheRawCommentForDecl(), CommentlessRedeclChains, DeclRawComments, clang::Decl::getCanonicalDecl(), getRawCommentForDeclNoCache(), RedeclChainComments, and clang::Decl::redecls().
Referenced by getCommentForDecl(), clang::getCompletionComment(), clang::getParameterComment(), and clang::getPatternCompletionComment().
getRawCommentForDeclNoCache()
RawComment * ASTContext::getRawCommentForDeclNoCache (const Decl * D) const
Return the documentation comment attached to a given declaration, without looking into cache.
Definition at line 358 of file ASTContext.cpp.
References Comments, CommentsLoaded, clang::RawCommentList::empty(), ExternalSource, clang::File, clang::RawCommentList::getCommentsInFile(), getDeclLocForCommentSearch(), getRawCommentForDeclNoCacheImpl(), clang::SourceLocation::isFileID(), and clang::SourceLocation::isInvalid().
Referenced by clang::extractapi::ExtractAPIVisitor< Derived >::fetchRawCommentForDecl(), clang::tooling::getAssociatedRange(), getLocalCommentForDeclUncached(), and getRawCommentForAnyRedecl().
getRawCommentForDeclNoCacheImpl()
RawComment * ASTContext::getRawCommentForDeclNoCacheImpl (const Decl * D, const SourceLocation RepresentativeLocForDecl, const std::map< unsigned, RawComment * > & CommentsInFile) const
Returns
searches CommentsInFile for doc comment for D.
RepresentativeLocForDecl is used as a location for searching doc comments. CommentsInFile is a mapping offset -> comment of files in the same file where RepresentativeLocForDecl is.
Definition at line 280 of file ASTContext.cpp.
References clang::LangOptions::CommentOpts, Comments, clang::RawCommentList::getCommentBeginLine(), clang::RawCommentList::getCommentEndOffset(), clang::Invalid, clang::RawComment::isDocumentation(), clang::SourceLocation::isFileID(), clang::SourceLocation::isInvalid(), clang::RawComment::isTrailingComment(), clang::CommentOptions::ParseAllComments, and Text.
Referenced by attachCommentsToJustParsedDecls(), and getRawCommentForDeclNoCache().
getReadPipeType()
QualType ASTContext::getReadPipeType (QualType T) const
Return a read_only pipe type for the specified type.
Definition at line 4588 of file ASTContext.cpp.
Referenced by clang::Sema::BuildReadPipeType(), and getCommonNonSugarTypeNode().
getRealTypeForBitwidth()
QualType ASTContext::getRealTypeForBitwidth (unsigned DestWidth, FloatModeKind ExplicitType) const
getRealTypeForBitwidth - sets floating point QualTy according to specified bitwidth.
Returns empty type if there is no appropriate target types.
Definition at line 12118 of file ASTContext.cpp.
References clang::Double, DoubleTy, clang::Float, clang::Float128, Float128Ty, FloatTy, clang::TargetInfo::getRealTypeByWidth(), getTargetInfo(), clang::Half, HalfTy, clang::Ibm128, Ibm128Ty, clang::LongDouble, LongDoubleTy, and clang::NoFloat.
Referenced by clang::Sema::AddModeAttr().
getRecordType()
QualType ASTContext::getRecordType (const RecordDecl * Decl) const
Definition at line 4752 of file ASTContext.cpp.
References clang::Decl::getPreviousDecl(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnSourceLocExpr(), clang::Sema::AddOverloadCandidate(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckCompletedCXXClass(), clang::Sema::CheckExplicitlyDefaultedComparison(), checkMemberDecomposition(), CheckOperatorDeleteDeclaration(), clang::Sema::CheckStructuredBindingMemberAccess(), clang::CodeGen::CGDebugInfo::completeClass(), clang::CodeGen::CGDebugInfo::completeRequiredType(), clang::CodeGen::CGDebugInfo::completeUnusedClass(), ComputeDefaultedSpecialMemberExceptionSpec(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), clang::Sema::CXXThisScopeRAII::CXXThisScopeRAII(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::interp::InterpFrame::describe(), clang::Sema::DiagnoseNontrivial(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), clang::Sema::FindDeallocationFunction(), clang::Sema::FindDeallocationFunctionForDestructor(), findDecomposableBaseClass(), findSubobject(), clang::StructuralEquivalenceContext::findUntaggedStructOrUnionIndex(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), getLValueType(), HandleConstructorCall(), HandleDynamicCast(), hasCopyOrMoveCtorParam(), clang::ASTNodeImporter::ImportAPValue(), clang::Expr::isPotentialConstantExpr(), clang::Sema::LookupInSuper(), recordFixedType(), recoverFromTypeInKnownDependentBase(), clang::CodeGen::CodeGenTypes::RefreshTypeCacheForClass(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), and clang::Sema::SpecialMemberIsTrivial().
getReferenceQualifiedType()
QualType ASTContext::getReferenceQualifiedType (const Expr * e) const
getReferenceQualifiedType - Given an expr, will return the type for that expression, as in [dcl.type.simple]p4 but without taking id-expressions and class member access into account.
Definition at line 5693 of file ASTContext.cpp.
References getLValueReferenceType(), getRValueReferenceType(), clang::Expr::getType(), clang::Expr::getValueKind(), clang::VK_LValue, clang::VK_PRValue, and clang::VK_XValue.
Referenced by clang::Sema::BuildExprRequirement(), diagnoseUnsatisfiedRequirement(), clang::ObjCMessageExpr::getCallReturnType(), clang::Sema::getDecltypeForExpr(), clang::ento::CallEvent::getResultType(), and TryClassUnification().
getRestrictType()
QualType clang::ASTContext::getRestrictType (QualType T) const inline
Return the uniqued reference to the type for a restrict qualified type.
The resulting type has a union of the qualifiers from T and restrict.
Definition at line 1255 of file ASTContext.h.
References clang::Qualifiers::Restrict, and clang::QualType::withFastQualifiers().
getRValueReferenceType()
QualType ASTContext::getRValueReferenceType (QualType T) const
Return the uniqued reference to the type for an rvalue reference to the specified type.
getRValueReferenceType - Return the uniqued reference to the type for an rvalue reference to the specified type.
Definition at line 3480 of file ASTContext.cpp.
References getCanonicalType(), getRValueReferenceType(), clang::ReferenceType::Profile(), and clang::TypeAlignment.
Referenced by AddImplicitObjectParameterType(), alignReferenceTypes(), clang::Sema::BuildReferenceType(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::desugarForDiagnostic(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), getAutoRRefDeductType(), getCommonNonSugarTypeNode(), clang::TypeName::getFullyQualifiedType(), getImplicitObjectParamType(), getReferenceQualifiedType(), getRValueReferenceType(), getVariableArrayDecayedType(), clang::ento::ExprEngine::handleLValueBitCast(), lookupPromiseType(), NoteSurrogateCandidate(), clang::InitializationSequence::Perform(), clang::Sema::SpecialMemberIsTrivial(), and clang::ASTNodeImporter::VisitRValueReferenceType().
getScalableVectorType()
QualType ASTContext::getScalableVectorType (QualType EltTy, unsigned NumElts, unsigned NumFields = 1) const
Return the unique reference to a scalable vector type of the specified element type and scalable number of elements.
getScalableVectorType - Return the unique reference to a scalable vector type of the specified element type and size.
For RISC-V, number of fields is also provided when it fetching for tuple type.
Precondition
EltTy must be a built-in type.
VectorType must be a built-in type.
Definition at line 4025 of file ASTContext.cpp.
References getTypeSize().
Referenced by clang::Sema::CheckSizelessVectorConditionalTypes(), checkSizelessVectorShift(), DecodeTypeFromStr(), clang::Sema::GetSignedSizelessVectorType(), and RVVType2Qual().
getSideTableAllocatedMemory()
size_t ASTContext::getSideTableAllocatedMemory () const
Return the total memory used for various side tables.
Definition at line 12086 of file ASTContext.cpp.
getsigjmp_bufType()
QualType clang::ASTContext::getsigjmp_bufType () const inline
Retrieve the C sigjmp_buf type.
Definition at line 1946 of file ASTContext.h.
References getTypeDeclType().
Referenced by DecodeTypeFromStr().
getSignatureParameterType()
QualType ASTContext::getSignatureParameterType (QualType T) const
Retrieve the parameter type as adjusted for use in the signature of a function, decaying array and function types and removing top-level cv-qualifiers.
Definition at line 6943 of file ASTContext.cpp.
References getAdjustedParameterType(), and getVariableArrayDecayedType().
getSignedSizeType()
CanQualType ASTContext::getSignedSizeType () const
Return the unique signed counterpart of the integer type corresponding to size_t.
Definition at line 5958 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnNumericConstant(), and clang::analyze_scanf::ScanfSpecifier::getArgType().
getSignedWCharType()
QualType ASTContext::getSignedWCharType () const
Return the type of "signed wchar_t".
getSignedWCharType - Return the type of "signed wchar_t".
Used when in C++, as a GCC extension.
Definition at line 5974 of file ASTContext.cpp.
References WCharTy.
Referenced by ConvertDeclSpecToType(), and getCorrespondingSignedType().
getSizeType()
CanQualType ASTContext::getSizeType () const
Return the unique type for "size_t" (C99 7.17), defined in <stddef.h>.
getSizeType - Return the unique type for "size_t" (C99 7.17), the result of the sizeof operator (C99 6.5.3.4p4).
The sizeof operator requires this (C99 6.5.3.4p4).
The value is target dependent and needs to agree with the definition in <stddef.h>.
Definition at line 5952 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnNumericConstant(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPRegionStart(), clang::Sema::ActOnStringLiteral(), appendParameterTypes(), clang::Sema::BuildArrayType(), clang::Sema::BuildArrayTypeTrait(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCXXNew(), buildMemcpyForAssignmentOp(), buildSingleCopyAssignRecursively(), captureVariablyModifiedType(), checkArraySize(), clang::Sema::CheckLiteralOperatorDeclaration(), checkOpenCLEnqueueLocalSizeArgs(), CheckOperatorNewDeclaration(), checkTupleLikeDecomposition(), clang::SizeOfPackExpr::Create(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), CreateHexagonBuiltinVaListDecl(), CreatePNaClABIBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), CreateX86_64ABIBuiltinVaListDecl(), clang::Sema::DeclareGlobalNewDelete(), DecodeTypeFromStr(), DeduceFromInitializerList(), DeduceTemplateArgumentsByTypeMatch(), diagnoseListInit(), emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), emitStructGetterCall(), emitStructSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::Sema::FindAllocationFunctions(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getBytesReturnedByAllocSizeCall(), clang::ConstantArrayType::getMaxSizeBits(), clang::ConstantArrayType::getNumAddressingBits(), getPointerAndSize(), getTupleLikeElementType(), clang::ento::SymbolExtent::getType(), clang::Sema::Initialize(), isNonPlacementDeallocationFunction(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::CXXMethodDecl::isUsualDeallocationFunction(), matchesStlAllocatorFn(), clang::InitializationSequence::Perform(), RVVType2Qual(), TryInitializerListConstruction(), and TryListConversion().
getSourceManager() [1/2]
SourceManager & clang::ASTContext::getSourceManager () inline
Definition at line 691 of file ASTContext.h.
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnLabelStmt(), clang::CodeGen::CodeGenModule::AddDeferredUnusedCoverageMapping(), AddOverloadParameterChunks(), clang::arcmt::trans::MigrationContext::addPropertyAttribute(), clang::CodeGen::CGDebugInfo::AddStringLiteralDebugInfo(), clang::arcmt::MigrationProcess::applyTransform(), clang::CodeGen::CodeGenPGO::assignRegionCounters(), checkAllAtProps(), clang::Sema::CheckEquivalentExceptionSpec(), clang::arcmt::checkForManualIssues(), clang::StmtSequence::contains(), clang::index::CommentToXMLConverter::convertCommentToXML(), clang::CodeGen::CGOpenMPRuntime::createOffloadEntriesAndInfoMetadata(), createOverloadsForFixedParams(), clang::tooling::createRenameAtomicChanges(), disambiguateSpellingInScope(), clang::Decl::dump(), clang::arcmt::trans::MigrationContext::dumpGCAttrs(), clang::LocationContext::dumpStack(), clang::CodeGen::CodeGenModule::EmitAnnotationLineNo(), clang::CodeGen::CodeGenModule::EmitAnnotationUnit(), emitBody(), clang::CodeGen::CodeGenPGO::emitEmptyCounterMapping(), emitMappingInformation(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), clang::SourceLocExpr::EvaluateInContext(), clang::tooling::findSelectedASTNodes(), clang::arcmt::trans::findSemiAfterLocation(), fixParamWithSpan(), fixUPCAddressofArraySubscriptWithSpan(), fixVarDeclWithSpan(), GCRewriteFinalize(), GenerateFixForUnusedDecl(), getAsmSrcLocInfo(), clang::tooling::getAssociatedRange(), clang::BackendConsumer::getBestLocationFromDebugLoc(), getEnclosingStmtLocation(), getEntryInfoFromPresumedLoc(), getErrnoFunc(), getFixIts(), DerefSimplePtrArithFixableGadget::getFixits(), UPCPreIncrementGadget::getFixits(), clang::AnalysisDeclContext::getFunctionName(), getIdentStringFromSourceLocation(), getLiteralInfo(), clang::FunctionDecl::getReturnTypeSourceRange(), clang::ento::AnalysisManager::getSourceManager(), clang::tooling::getText(), clang::ento::MemRegionManager::getVarRegion(), clang::BackendConsumer::HandleInlineFunctionDefinition(), clang::BackendConsumer::HandleTagDeclDefinition(), clang::BackendConsumer::HandleTopLevelDecl(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::index::IndexingContext::importedModule(), clang::FilenamePatternConstraint::isAutoGenerated(), isEmptyARCMTMacroStatement(), isForbiddenTypeAllowed(), clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList(), clang::ento::AnalysisManager::isInCodeFile(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::isInSystemHeader(), clang::Sema::isLibstdcxxEagerExceptionSpecHack(), isStandardNewDelete(), LocPropertyAttribute(), makeLocation(), clang::Sema::makeUnavailableInSystemHeader(), clang::tooling::maybeExtendRange(), clang::Sema::MergeTypedefNameDecl(), clang::RawComment::parse(), populateInitializerFixItWithSpan(), clang::ASTWriter::PreparePathForOutput(), clang::PrettyDeclStackTraceEntry::print(), printExprAsWritten(), printIndicesOfElementsToConstructJson(), clang::LocationContext::printJson(), clang::ProgramPoint::printJson(), printPendingInitLoopJson(), clang::CodeGen::CodeGenModule::printPostfixForExternalizedDecl(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), clang::CodeGen::CGDebugInfo::setLocation(), clang::BackendConsumer::SrcMgrDiagHandler(), clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody(), and clang::Sema::warnOnReservedIdentifier().
getSourceManager() [2/2]
const SourceManager & clang::ASTContext::getSourceManager () const inline
Definition at line 692 of file ASTContext.h.
getStaticLocalNumber()
unsigned ASTContext::getStaticLocalNumber (const VarDecl * VD) const
Definition at line 12167 of file ASTContext.cpp.
Referenced by clang::Sema::BuildVariableInstantiation().
getStringLiteralArrayType()
QualType ASTContext::getStringLiteralArrayType (QualType EltTy, unsigned Length) const
Return a type for a constant array for a string literal of the specified element type and length.
Definition at line 12239 of file ASTContext.cpp.
References adjustStringLiteralBaseType(), clang::CPlusPlus, getConstantArrayType(), getLangOpts(), clang::ArrayType::Normal, and clang::QualType::withConst().
Referenced by clang::Sema::ActOnSourceLocExpr(), clang::Sema::ActOnStringLiteral(), clang::Sema::BuildObjCEncodeExpression(), and getPredefinedStringLiteralFromCache().
getSubstTemplateTemplateParm()
TemplateName ASTContext::getSubstTemplateTemplateParm (TemplateName replacement, Decl * AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex) const
Definition at line 9312 of file ASTContext.cpp.
References clang::SubstTemplateTemplateParmStorage::Profile().
Referenced by clang::ASTImporter::Import().
getSubstTemplateTemplateParmPack()
TemplateName ASTContext::getSubstTemplateTemplateParmPack (const TemplateArgument & ArgPack, Decl * AssociatedDecl, unsigned Index, bool Final) const
Definition at line 9333 of file ASTContext.cpp.
References clang::TemplateArgument::pack_elements(), and clang::SubstTemplateTemplateParmPackStorage::Profile().
Referenced by getCanonicalTemplateName(), clang::ASTImporter::Import(), and clang::TreeTransform< Derived >::RebuildTemplateName().
getSubstTemplateTypeParmPackType()
QualType ASTContext::getSubstTemplateTypeParmPackType (Decl * AssociatedDecl, unsigned Index, bool Final, const TemplateArgument & ArgPack)
Retrieve a.
Definition at line 4860 of file ASTContext.cpp.
References clang::Decl::getCanonicalDecl(), getCanonicalTemplateArgument(), getSubstTemplateTypeParmPackType(), clang::Decl::isCanonicalDecl(), P, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::structurallyEquals(), clang::TemplateArgument::Type, and clang::TypeAlignment.
Referenced by getSubstTemplateTypeParmPackType(), and clang::ASTNodeImporter::VisitSubstTemplateTypeParmPackType().
getSubstTemplateTypeParmType()
QualType ASTContext::getSubstTemplateTypeParmType (QualType Replacement, Decl * AssociatedDecl, unsigned Index, std::optional< unsigned > PackIndex) const
Retrieve a substitution-result type.
Definition at line 4835 of file ASTContext.cpp.
References Allocate(), clang::QualType::isCanonical(), and clang::TypeAlignment.
Referenced by getCommonSugarTypeNode(), and clang::ASTNodeImporter::VisitSubstTemplateTypeParmType().
getTagDeclType()
QualType ASTContext::getTagDeclType (const TagDecl * Decl) const
Return the unique reference to the type for the specified TagDecl (struct/union/class/enum) decl.
getTagDeclType - Return the unique reference to the type for the specified TagDecl (struct/union/class/enum) decl.
Definition at line 5942 of file ASTContext.cpp.
References getTypeDeclType().
Referenced by clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnTag(), BuildImplicitMemberInitializer(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::CheckConstructor(), clang::CodeGen::CodeGenTypes::ConvertRecordDeclType(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::CodeGen::CodeGenTypes::DeriveThisType(), clang::InitializationSequence::Diagnose(), emitBadConversionNotes(), EmitCapturedFieldLValue(), clang::CodeGen::CodeGenVTables::GenerateConstructionVTable(), getBlockDescriptorExtendedType(), getBlockDescriptorType(), getCFConstantStringDecl(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), getMSGuidType(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getObjCSuperType(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::CXXConstructorDecl::isSpecializationCopyingObject(), LookupPredefedObjCSuperType(), clang::Sema::LookupSpecialMember(), mergeAlignedAttrs(), clang::Sema::PerformImplicitConversion(), clang::Sema::PrintInstantiationStack(), clang::TagDecl::printName(), clang::Sema::setTagNameForLinkagePurposes(), clang::CodeGen::CodeGenTypes::UpdateCompletedType(), clang::ASTNodeImporter::VisitEnumType(), and clang::ASTNodeImporter::VisitRecordType().
getTargetAddressSpace()
unsigned ASTContext::getTargetAddressSpace (LangAS AS) const
Definition at line 12378 of file ASTContext.cpp.
References clang::TargetInfo::getTargetAddressSpace(), and getTargetInfo().
Referenced by clang::Sema::BuildCallExpr(), buildGlobalBlock(), castStringLiteralToDefaultAddressSpace(), clang::CodeGen::CodeGenTypes::ConvertType(), createReferenceTemporary(), clang::CodeGen::CodeGenModule::createUnnamedGlobalFrom(), EmitDeclDestroy(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), clang::CodeGen::CodeGenModule::EmitOMPAllocateDecl(), GenerateStringLiteral(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), clang::CodeGen::CodeGenModule::getBlockDescriptorType(), clang::CodeGen::ConstantEmitter::getCurrentAddrPrivate(), clang::CodeGen::CGOpenCLRuntime::getGenericVoidPointerType(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::CodeGen::CGOpenCLRuntime::getPipeType(), clang::CodeGen::CGOpenCLRuntime::getPointerType(), clang::CodeGen::CGOpenCLRuntime::getSamplerType(), and clang::CodeGen::CodeGenTypes::getTargetAddressSpace().
getTargetDefaultAlignForAttributeAligned()
unsigned ASTContext::getTargetDefaultAlignForAttributeAligned () const
Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
getTargetDefaultAlignForAttributeAligned - Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
Definition at line 2558 of file ASTContext.cpp.
References clang::TargetInfo::getDefaultAlignForAttributeAligned(), and getTargetInfo().
getTargetInfo()
const TargetInfo & clang::ASTContext::getTargetInfo () const inline
Definition at line 743 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnIntegerConstant(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCAvailabilityCheckExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnPragmaMSSeg(), clang::Sema::ActOnPragmaOptionsAlign(), clang::Sema::ActOnSEHTryBlock(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnTag(), clang::Sema::ActOnTagFinishDefinition(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignedAttr(), clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::AddInitializerToDecl(), clang::Sema::AddKnownFunctionAttributes(), clang::Sema::adjustMemberFunctionCC(), clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), AtomicUsesUnsupportedLibcall(), basicGVALinkageForFunction(), basicGVALinkageForVariable(), clang::Sema::BuildArrayType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBitIntType(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildFunctionType(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVAArgExpr(), clang::arcmt::trans::canApplyWeak(), canPassInRegisters(), clang::ento::SMTConstraintManager::canReasonAbout(), captureInLambda(), ChangeIntegralSignedness(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckAssignmentConstraints(), checkAttributesAfterMerging(), clang::Sema::CheckAttrTarget(), CheckAvailability(), clang::Sema::CheckBaseSpecifier(), CheckBuiltinTargetInSupported(), CheckBuiltinTargetNotInUnsupported(), clang::Sema::CheckCallingConvAttr(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckCompletedCXXClass(), clang::Sema::CheckCompleteDestructorVariant(), clang::Sema::CheckCXXThrowOperand(), checkDLLAttributeRedeclaration(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckFieldDecl(), CheckFormatString(), checkForMultipleExportedDefaultConstructors(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckFunctionReturnType(), clang::Sema::CheckHLSLEntryPoint(), clang::Sema::CheckMain(), CheckMultiVersionAdditionalDecl(), CheckMultiVersionAdditionalRules(), CheckMultiVersionFunction(), CheckMultiVersionValue(), checkObjCMethodX86VectorTypes(), clang::Sema::CheckParameter(), clang::Sema::CheckRegparmAttr(), clang::Sema::CheckSpecializationInstantiationRedecl(), clang::Sema::checkTargetAttr(), CheckTargetCausesMultiVersioning(), clang::Sema::checkTargetClonesAttrString(), clang::Sema::checkTargetVersionAttr(), clang::Sema::CheckThreadLocalForLargeAlignment(), clang::Sema::checkTypeSupport(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckVariableDeclarationType(), checkVAStartABI(), clang::Sema::CheckVectorOperands(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), clang::Sema::CodeCompleteAttribute(), computeKeyFunction(), clang::analyze_os_log::computeOSLogBufferLayout(), ConvertDeclSpecToType(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CreateItaniumCXXABI(), DeclMustBeEmitted(), DecodeTypeFromStr(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefineUsedVTables(), DiagnoseObjCImplementedDeprecations(), clang::Sema::diagnoseUnavailableAlignedAllocation(), clang::Sema::DiagnoseUseOfDecl(), DoEmitAvailabilityWarning(), clang::CodeGen::CodeGenModule::EmitMainVoidAlias(), emitOMPAtomicRMW(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), EvalAndBitcastToAPInt(), clang::SourceLocExpr::EvaluateInContext(), clang::DeclSpec::Finish(), clang::Sema::FixOverloadedFunctionReference(), clang::analyze_printf::PrintfSpecifier::fixType(), clang::analyze_scanf::ScanfSpecifier::fixType(), clang::Sema::FormatStringHasSArg(), funcHasParameterSizeMangling(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), getAlignOfGlobalVar(), clang::ASTNameGenerator::Implementation::getAllManglings(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getAttrForPlatform(), clang::FunctionDecl::getBuiltinID(), getCallingConvMangling(), getCCForDeclaratorChunk(), clang::interp::Context::getCharBit(), getConstantArrayInfoInChars(), clang::Sema::getCudaConfigureFuncName(), getCXXABIKind(), getDeclAlign(), getDefaultCallingConvention(), getFixedPointIBits(), getFixedPointScale(), getFixedPointSemantics(), GetFullTypeForDeclarator(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), getInstrProfSection(), getIntTypeForBitwidth(), getLangASForBuiltinAddressSpace(), clang::Sema::getLocationOfStringLiteralByte(), clang::CodeGen::swiftcall::getMaximumVoluntaryIntegerSize(), getOpenMPDefaultSimdAlign(), clang::CodeGen::CGOpenMPRuntime::getOrCreateThreadPrivateCache(), getRealTypeForBitwidth(), getRVVTypeSize(), getTargetAddressSpace(), getTargetDefaultAlignForAttributeAligned(), getTargetNullPointerValue(), getTypeInfoLinkage(), clang::Decl::getVersionIntroduced(), handleAliasAttr(), handleAnyX86InterruptAttr(), handleArmBuiltinAliasAttr(), HandleArmSveVectorBitsTypeAttr(), handleAvailabilityAttr(), handleBuiltinAliasAttr(), handleCPUSpecificAttr(), handleDeclspecThreadAttr(), handleDLLAttr(), handleHLSLNumThreadsAttr(), handleHLSLSV_DispatchThreadIDAttr(), handleHLSLSVGroupIndexAttr(), handleInterruptAttr(), handleMSPointerTypeQualifierAttr(), handleNakedAttr(), HandleNeonVectorTypeAttr(), handlePackedAttr(), HandleRISCVRVVVectorBitsTypeAttr(), handleTargetClonesAttr(), handleTLSModelAttr(), handleVisibilityAttr(), handleWeakImportAttr(), hasNewExtendedAlignment(), InitDeviceMC(), clang::CodeGen::initializationPatternFor(), clang::Sema::Initialize(), clang::Sema::InstantiateClassMembers(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), clang::Sema::InstantiateFunctionDefinition(), isAIXLayout(), isArc4RandomAvailable(), isDefaultStdCall(), clang::Type::isIncompleteType(), clang::CodeGen::swiftcall::isLegalIntegerType(), clang::FunctionDecl::isMSExternInline(), isMsLayout(), isMSStaticDataMemberInlineDefinition(), clang::FunctionDecl::isMSVCRTEntryPoint(), isPermittedNeonBaseType(), isStdBuiltin(), clang::Sema::isValidSectionSpecifier(), clang::Sema::isValidVarArgType(), isVarDeclStrongDefinition(), IsVectorConversion(), clang::MangleContext::mangleName(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkFunctionReferenced(), clang::Sema::MarkVTableUsed(), needsConversionOfHalfVec(), parseModeAttrArg(), clang::Sema::PerformImplicitConversion(), ProcessDeclAttribute(), ProcessStmtAttribute(), ReferenceDllExportedMembers(), clang::CodeGen::CodeGenModule::Release(), repeatForLambdaConversionFunctionCallingConvs(), roundUpSizeToCharAlignment(), shouldDiagnoseAvailabilityByDefault(), clang::TargetOMPContext::TargetOMPContext(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), TryEvaluateBuiltinNaN(), TryReinterpretCast(), TryStaticMemberPointerUpcast(), clang::QualType::UseExcessPrecision(), and clang::Sema::VerifyBitField().
getTargetNullPointerValue()
uint64_t ASTContext::getTargetNullPointerValue (QualType QT) const
Get target-dependent integer value for null pointer which is used for constant folding.
Definition at line 12368 of file ASTContext.cpp.
References clang::Default, clang::QualType::getAddressSpace(), clang::TargetInfo::getNullPointerValue(), clang::Type::getPointeeType(), getTargetInfo(), clang::Type::getUnqualifiedDesugaredType(), and clang::Type::isNullPtrType().
Referenced by clang::CodeGen::CodeGenTypes::isZeroInitializable(), and clang::APValue::toIntegralConstant().
getTemplateOrSpecializationInfo()
ASTContext::TemplateOrSpecializationInfo ASTContext::getTemplateOrSpecializationInfo (const VarDecl * Var)
Definition at line 1494 of file ASTContext.cpp.
Referenced by clang::VarDecl::getDescribedVarTemplate(), getInstantiatedFromStaticDataMember(), clang::VarDecl::getMemberSpecializationInfo(), and clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::VisitVarDecl().
getTemplateParamObjectDecl()
TemplateParamObjectDecl * ASTContext::getTemplateParamObjectDecl (QualType T, const APValue & V) const
Return the template parameter object of the given type with the given value.
Definition at line 12299 of file ASTContext.cpp.
References clang::TemplateParamObjectDecl::Profile(), and V.
Referenced by clang::Sema::CheckTemplateArgument().
getTemplateSpecializationType() [1/2]
QualType ASTContext::getTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgument > Args, QualType Canon = QualType()) const
Definition at line 4977 of file ASTContext.cpp.
References Allocate(), clang::TemplateName::getAsDependentTemplateName(), clang::TemplateName::getAsQualifiedTemplateName(), clang::TemplateName::getAsTemplateDecl(), getCanonicalTemplateSpecializationType(), getCanonicalType(), hasAnyPackExpansions(), clang::QualType::isNull(), clang::TemplateDecl::isTypeAlias(), and clang::TypeAlignment.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::CheckTemplateIdType(), clang::desugarForDiagnostic(), getCommonNonSugarTypeNode(), getCommonSugarTypeNode(), clang::TypeName::getFullyQualifiedTemplateType(), clang::ClassTemplateDecl::getInjectedClassNameSpecialization(), clang::Sema::getMoreSpecializedPartialSpecialization(), getTemplateSpecializationType(), getTemplateSpecializationTypeInfo(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::Sema::isMoreSpecializedThanPrimary(), and clang::ASTNodeImporter::VisitTemplateSpecializationType().
getTemplateSpecializationType() [2/2]
QualType ASTContext::getTemplateSpecializationType (TemplateName T, ArrayRef< TemplateArgumentLoc > Args, QualType Canon = QualType()) const
Definition at line 4952 of file ASTContext.cpp.
References clang::TemplateName::getAsDependentTemplateName(), and getTemplateSpecializationType().
getTemplateSpecializationTypeInfo()
TypeSourceInfo * ASTContext::getTemplateSpecializationTypeInfo (TemplateName T, SourceLocation TLoc, const TemplateArgumentListInfo & Args, QualType Canon = QualType()) const
Definition at line 4930 of file ASTContext.cpp.
References clang::TemplateArgumentListInfo::arguments(), clang::TypeLoc::castAs(), CreateTypeSourceInfo(), clang::TemplateArgumentListInfo::getLAngleLoc(), clang::TemplateSpecializationTypeLoc::getNumArgs(), clang::TemplateArgumentListInfo::getRAngleLoc(), getTemplateSpecializationType(), clang::TypeSourceInfo::getTypeLoc(), clang::TemplateSpecializationTypeLoc::setArgLocInfo(), clang::TemplateSpecializationTypeLoc::setLAngleLoc(), clang::TemplateSpecializationTypeLoc::setRAngleLoc(), clang::TemplateSpecializationTypeLoc::setTemplateKeywordLoc(), and clang::TemplateSpecializationTypeLoc::setTemplateNameLoc().
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnExplicitInstantiation(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), and clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization().
getTemplateTypeParmType()
QualType ASTContext::getTemplateTypeParmType (unsigned Depth, unsigned Index, bool ParameterPack, TemplateTypeParmDecl * ParmDecl = nullptr) const
Retrieve the template type parameter type for a template parameter or parameter pack with the given depth, index, and (optionally) name.
Definition at line 4899 of file ASTContext.cpp.
References getTemplateTypeParmType(), and clang::TypeAlignment.
Referenced by getCommonNonSugarTypeNode(), getTemplateTypeParmType(), and clang::ASTNodeImporter::VisitTemplateTypeParmType().
getTranslationUnitDecl()
TranslationUnitDecl * clang::ASTContext::getTranslationUnitDecl () const inline
Definition at line 1059 of file ASTContext.h.
References clang::Decl::getMostRecentDecl().
Referenced by clang::Sema::ActOnCXXTypeid(), clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnGlobalModuleFragmentDecl(), clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnOpenMPDeclareMapperDirectiveVarDecl(), clang::Sema::ActOnParamDeclarator(), clang::Sema::ActOnPragmaDetectMismatch(), clang::Sema::ActOnPragmaMSComment(), clang::Sema::ActOnPrivateModuleFragmentDecl(), clang::Sema::ActOnTemplateTemplateParameter(), clang::Sema::ActOnTopLevelStmtDecl(), clang::Sema::ActOnTranslationUnitScope(), clang::Sema::ActOnTypeParameter(), addFunctionPointerConversion(), clang::ASTImporter::ASTImporter(), buildBuiltinTemplateDecl(), buildImplicitRecord(), buildImplicitTypedef(), clang::Sema::BuildModuleInclude(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::BuildPredefinedExpr(), clang::arcmt::trans::checkAPIUses(), checkGlobalOrExternCConflict(), cleanupDeallocOrFinalize(), clang::Sema::CodeCompleteNamespaceDecl(), clang::Sema::CodeCompleteObjCClassForwardDecl(), clang::Sema::CodeCompleteObjCImplementationDecl(), clang::Sema::CodeCompleteObjCInterfaceCategory(), clang::Sema::CodeCompleteObjCInterfaceDecl(), clang::Sema::CodeCompleteObjCProtocolDecl(), clang::Sema::CodeCompleteObjCProtocolReferences(), clang::Sema::CodeCompleteObjCSuperclass(), clang::Sema::computeDeclContext(), configureBlocksRuntimeObject(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), clang::Sema::CreateBuiltin(), clang::Sema::createImplicitModuleImportForErrorRecovery(), clang::Sema::DeclApplyPragmaWeak(), clang::Sema::DeclareGlobalAllocationFunction(), emitOutlinedFunctionPrologue(), EvaluateBinaryTypeTrait(), EvaluateBooleanTypeTrait(), clang::ASTMergeAction::ExecuteAction(), clang::Sema::FindAllocationFunctions(), clang::tooling::findSelectedASTNodes(), clang::Sema::FindUsualDeallocationFunction(), clang::Sema::GatherGlobalCodeCompletions(), GCRewriteFinalize(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), getErrnoFunc(), getExternCContextDecl(), getObjCProtocolDecl(), getObjCSuperType(), clang::Sema::getOrCreateStdNamespace(), getPredefinedDecl(), InitBuiltinTypes(), clang::ASTReader::InitializeContext(), clang::HLSLExternalSemaSource::InitializeSema(), InsertOCLBuiltinDeclarationsFromTable(), InventTemplateParameter(), LookupObjCInterfaceDeclForLiteral(), lookupStdNamespace(), clang::arcmt::trans::makeAssignARCSafe(), makeLocation(), clang::ExternalASTMerger::MaybeRecordOrigin(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), clang::arcmt::trans::removeEmptyStatementsAndDeallocFinalize(), clang::arcmt::trans::removeRetainReleaseDeallocFinalize(), clang::arcmt::trans::removeZeroOutPropsInDeallocFinalize(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), clang::arcmt::trans::rewriteAutoreleasePool(), clang::arcmt::trans::rewriteUnbridgedCasts(), clang::arcmt::trans::rewriteUnusedInitDelegate(), clang::Sema::SubstParmVarDecl(), clang::RecursiveASTVisitor< Derived >::TraverseAST(), traverseAST(), clang::arcmt::trans::GCAttrsTraverser::traverseTU(), clang::ASTDeclReader::VisitDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ASTNodeImporter::VisitImplicitParamDecl(), clang::ASTNodeImporter::VisitNonTypeTemplateParmDecl(), clang::ASTNodeImporter::VisitParmVarDecl(), clang::ASTNodeImporter::VisitTemplateTemplateParmDecl(), clang::ASTNodeImporter::VisitTemplateTypeParmDecl(), clang::ASTNodeImporter::VisitTranslationUnitDecl(), clang::ASTNodeImporter::VisitTypeAliasTemplateDecl(), and clang::ASTNodeImporter::VisitVarTemplateDecl().
getTraversalScope()
std::vector< Decl * > clang::ASTContext::getTraversalScope () const inline
Definition at line 676 of file ASTContext.h.
getTrivialTypeSourceInfo()
TypeSourceInfo * ASTContext::getTrivialTypeSourceInfo (QualType T, SourceLocation Loc = SourceLocation()) const
Allocate a TypeSourceInfo where all locations have been initialized to a given location, which defaults to the empty location.
Definition at line 3005 of file ASTContext.cpp.
References CreateTypeSourceInfo(), clang::TypeSourceInfo::getTypeLoc(), and clang::TypeLoc::initialize().
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::Sema::ActOnArrayTypeTrait(), clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBuiltinOffsetOf(), clang::Sema::ActOnClassMessage(), clang::Sema::ActOnCompoundLiteral(), clang::Sema::ActOnCXXTypeConstructExpr(), clang::Sema::ActOnCXXTypeid(), clang::Sema::ActOnCXXUuidof(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnLastBitfield(), clang::Sema::ActOnObjCBridgedCast(), clang::Sema::ActOnObjCInstanceType(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::actOnObjCTypeParam(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPDeclareMapperDirectiveVarDecl(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnStartClassInterface(), clang::Sema::ActOnStringLiteral(), clang::Sema::ActOnSuperClassOfClassInterface(), clang::Sema::ActOnSYCLUniqueStableNameExpr(), clang::Sema::ActOnTypeTrait(), clang::Sema::ActOnUsingEnumDeclaration(), addBlockPointerConversion(), addFunctionPointerConversion(), clang::TemplateDeclInstantiator::adjustForRewrite(), adjustObjCTypeParamBoundType(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildCaptureField(), clang::Sema::BuildClassMessageImplicit(), clang::Sema::buildCoroutinePromise(), clang::Sema::BuildCXXForRangeStmt(), buildDistanceFunc(), clang::Sema::BuildEmptyCXXFoldExpr(), clang::Sema::BuildExpressionFromIntegralTemplateArgument(), BuildImplicitBaseInitializer(), buildImplicitTypedef(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildParmVarDeclForTypedef(), buildPostUpdate(), clang::Sema::BuildPseudoDestructorExpr(), buildSingleCopyAssignRecursively(), clang::Sema::BuildStdInitializerList(), buildVarDecl(), buildVarDecl(), CastForMoving(), castForMoving(), checkBuiltinTemplateIdType(), CheckDeducedPlaceholderConstraints(), checkOpenMPLoop(), clang::Sema::CheckTemplateArgument(), checkTupleLikeDecomposition(), clang::Sema::createLambdaInitCaptureVarDecl(), clang::Sema::CreatePropertyDecl(), clang::CStyleCastPtrExpr(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DefineInheritingConstructor(), emitOutlinedFunctionPrologue(), clang::Sema::findInheritingConstructor(), clang::Sema::getDestructorName(), getDummyLambdaType(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), clang::Sema::getObjCMessageKind(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::Sema::getTrivialTemplateArgumentLoc(), getTypeSourceInfoForStdAlignValT(), clang::Sema::HandleField(), handleIBOutletCollection(), clang::Sema::HandleMSProperty(), handlePreferredName(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::TemplateSpecializationTypeLoc::initializeArgLocs(), clang::ObjCObjectTypeLoc::initializeLocal(), clang::TypeOfTypeLoc::initializeLocal(), clang::UnaryTransformTypeLoc::initializeLocal(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::TreeTransform< Derived >::InventTypeSourceInfo(), lookupCoroutineHandleType(), lookupPromiseType(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), clang::Sema::ParseObjCEncodeExpression(), clang::Sema::ParseTypedefDecl(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), RebuildDeclaratorInCurrentInstantiation(), translateTemplateArgument(), TryToFixInvalidVariablyModifiedTypeSourceInfo(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::ASTNodeImporter::VisitFunctionDecl().
getTypeAlign() [1/2]
unsigned clang::ASTContext::getTypeAlign (const Type * T) const inline
Definition at line 2328 of file ASTContext.h.
References clang::TypeInfo::Align, and getTypeInfo().
getTypeAlign() [2/2]
unsigned clang::ASTContext::getTypeAlign (QualType T) const inline
Return the ABI-specified alignment of a (complete) type T, in bits.
Definition at line 2327 of file ASTContext.h.
References clang::TypeInfo::Align, and getTypeInfo().
Referenced by clang::Sema::BuildCXXNew(), clang::CodeGen::coerceToIntArray(), getTypeAlignIfKnown(), getTypeAlignInChars(), getTypeAlignInChars(), getTypeUnadjustedAlign(), handlePackedAttr(), handleTransparentUnionAttr(), and mergeAlignedAttrs().
getTypeAlignIfKnown()
unsigned ASTContext::getTypeAlignIfKnown (QualType T, bool NeedsPreferredAlignment = false) const
Return the alignment of a type, in bits, or 0 if the type is incomplete and we cannot determine the alignment (for example, from alignment attributes).
The returned alignment is the Preferred alignment if NeedsPreferredAlignment is true, otherwise is the ABI alignment.
Definition at line 1886 of file ASTContext.cpp.
References getBaseElementType(), getPreferredTypeAlign(), and getTypeAlign().
Referenced by hasNewExtendedAlignment(), and isVarDeclStrongDefinition().
getTypeAlignInChars() [1/2]
CharUnits ASTContext::getTypeAlignInChars (const Type * T) const
Definition at line 2485 of file ASTContext.cpp.
References getTypeAlign(), and toCharUnitsFromBits().
getTypeAlignInChars() [2/2]
CharUnits ASTContext::getTypeAlignInChars (QualType T) const
Return the ABI-specified alignment of a (complete) type T, in characters.
getTypeAlignInChars - Return the ABI-specified alignment of a type, in characters.
This method does not work on incomplete types.
Definition at line 2482 of file ASTContext.cpp.
References getTypeAlign(), and toCharUnitsFromBits().
Referenced by AddDirectArgument(), AlignOfType(), AtomicUsesUnsupportedLibcall(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::checkArrayElementAlignment(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCXXThrowOperand(), classifyType(), createReferenceTemporary(), clang::Sema::DiscardMisalignedMemberAddress(), EmitX86_64VAArgFromMemory(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), clang::CodeGen::CodeGenModule::GetAddrOfUnnamedGlobalConstantDecl(), GetAlignOfType(), clang::Sema::getNamedReturnInfo(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CGOpenCLRuntime::getPipeElemAlign(), getPresumedAlignmentOfPointer(), clang::Sema::isOpenMPCapturedByRef(), and clang::Sema::RefersToMemberWithReducedAlignment().
getTypeDeclType()
QualType clang::ASTContext::getTypeDeclType (const TypeDecl * Decl, const TypeDecl * PrevDecl = nullptr) const inline
Return the unique reference to the type for the specified type declaration.
Definition at line 1561 of file ASTContext.h.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCXXTypeid(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::ActOnStartCXXMemberDeclarations(), clang::Sema::ActOnSuperClassOfClassInterface(), AddImplicitObjectParameterType(), clang::Sema::AddOverloadCandidate(), clang::Sema::AddOverriddenMethods(), AddResultTypeChunk(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildCXXNew(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildMemInitializer(), clang::Sema::BuildMicrosoftCAnonymousStruct(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckBaseSpecifier(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckDestructorAccess(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckFunctionDeclaration(), CheckImplicitConversion(), clang::Sema::checkOpenMPDeclareVariantFunction(), clang::Sema::CheckTemplateIdType(), clang::Sema::CheckTypenameType(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteObjCSuperMessage(), ConvertDeclSpecToType(), clang::ClassTemplateSpecializationDecl::Create(), clang::LambdaExpr::Create(), clang::Sema::DeclareGlobalAllocationFunction(), clang::Sema::DeclareGlobalNewDelete(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), clang::Sema::deduceClosureReturnType(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseAmbiguousLookup(), DiagnoseBadAccess(), clang::Sema::diagnoseQualifiedDeclaration(), clang::Sema::DiagnoseUninstantiableTemplate(), EmitMemberInitializer(), clang::Sema::FindAllocationFunctions(), FindBaseInitializer(), clang::Sema::FindInstantiatedDecl(), clang::Sema::FixOverloadedFunctionReference(), clang::FormatASTNodeDiagnosticArgument(), clang::Sema::getAmbiguousPathsDisplayString(), getBOOLType(), getBuiltinMSVaListType(), getBuiltinVaListType(), clang::Sema::getConstructorName(), getConstructors(), clang::Sema::getCurrentThisType(), GetDeclSpecTypeForDeclarator(), clang::CXXRecordDecl::getDestructor(), clang::Sema::getDestructorName(), getFILEType(), GetFullTypeForDeclarator(), getInjectedTemplateArg(), getjmp_bufType(), clang::Sema::GetNameFromUnqualifiedId(), getObjCClassType(), getObjCIdType(), getObjCInstanceType(), clang::Sema::getObjCMessageKind(), getObjCSelType(), getRequiredQualification(), getsigjmp_bufType(), getTagDeclType(), getTupleLikeElementType(), clang::Sema::getTypeName(), GetTypeOfFunction(), getTypeSourceInfoForStdAlignValT(), getucontext_tType(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::Sema::isAcceptableNestedNameSpecifier(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::Sema::isIncompatibleTypedef(), clang::CXXMethodDecl::isMoveAssignmentOperator(), isNonPlacementDeallocationFunction(), IsStandardConversion(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), clang::Sema::LookupConstructors(), lookupPromiseType(), clang::Sema::LookupQualifiedName(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkVirtualBaseDestructorsReferenced(), clang::Sema::MatchTemplateParametersToScopeSpecifier(), clang::Sema::PerformObjectMemberConversion(), clang::TreeTransform< Derived >::RebuildDependentNameType(), clang::TreeTransform< Derived >::RebuildEnumType(), clang::TreeTransform< Derived >::RebuildRecordType(), clang::TreeTransform< Derived >::RebuildTypedefType(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), clang::Sema::RequireCompleteDeclContext(), clang::LookupResult::resolveKind(), ShouldDiagnoseSwitchCaseNotInEnum(), TryDiagnoseProtectedAccess(), TryObjectArgumentInitialization(), TryStaticMemberPointerUpcast(), clang::CXXRecordDecl::viewInheritance(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeImporter::VisitRecordDecl(), and clang::ASTNodeImporter::VisitUnresolvedUsingType().
getTypedefNameForUnnamedTagDecl()
TypedefNameDecl * ASTContext::getTypedefNameForUnnamedTagDecl (const TagDecl * TD)
Definition at line 12215 of file ASTContext.cpp.
getTypedefType()
QualType ASTContext::getTypedefType (const TypedefNameDecl * Decl, QualType Underlying = QualType()) const
Return the unique reference to the type for the specified typedef-name decl.
getTypedefType - Return the unique reference to the type for the specified typedef name decl.
Definition at line 4691 of file ASTContext.cpp.
References Allocate(), getCanonicalType(), hasSameType(), clang::QualType::isNull(), clang::TypedefType::Profile(), and clang::TypeAlignment.
Referenced by CheckExtVectorComponent(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), getCFConstantStringType(), getCommonSugarTypeNode(), getOpenCLTypedefType(), getRawCFConstantStringType(), and clang::ASTNodeImporter::VisitTypedefType().
getTypeInfo() [1/2]
TypeInfo ASTContext::getTypeInfo (const Type * T) const
Get the size and alignment of the specified complete type in bits.
Definition at line 1911 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnNumericConstant(), getIntegerWidthAndSignedness(), getPreferredTypeAlign(), clang::ConstantExpr::getStorageKind(), getTypeAlign(), getTypeAlign(), getTypeAlignIfRequired(), getTypeInfoInChars(), getTypeSize(), getTypeSize(), isAlignmentRequired(), matchTypes(), and tryMatchRecordTypes().
getTypeInfo() [2/2]
TypeInfo clang::ASTContext::getTypeInfo (QualType T) const inline
Definition at line 2290 of file ASTContext.h.
References getTypeInfo().
Referenced by getTypeInfo().
getTypeInfoDataSizeInChars()
TypeInfoChars ASTContext::getTypeInfoDataSizeInChars (QualType T) const
Definition at line 1792 of file ASTContext.cpp.
References clang::CPlusPlus, getASTRecordLayout(), clang::ASTRecordLayout::getDataSize(), getLangOpts(), getTypeInfoInChars(), and clang::TypeInfoChars::Width.
Referenced by clang::CodeGen::AggValueSlot::getPreferredSize().
getTypeInfoInChars() [1/2]
TypeInfoChars ASTContext::getTypeInfoInChars (const Type * T) const
Definition at line 1828 of file ASTContext.cpp.
References clang::TypeInfo::Align, clang::TypeInfo::AlignRequirement, getConstantArrayInfoInChars(), getTypeInfo(), toCharUnitsFromBits(), and clang::TypeInfo::Width.
Referenced by argTypeIsABIEquivalent(), computeBlockInfo(), clang::CodeGen::EmitVAArgInstr(), getConstantArrayInfoInChars(), getTypeInfoDataSizeInChars(), getTypeInfoInChars(), getTypeSizeInChars(), and getTypeSizeInChars().
getTypeInfoInChars() [2/2]
TypeInfoChars ASTContext::getTypeInfoInChars (QualType T) const
Definition at line 1836 of file ASTContext.cpp.
References getTypeInfoInChars().
getTypeOfExprType()
QualType ASTContext::getTypeOfExprType (Expr * tofExpr, TypeOfKind Kind) const
C2x feature and GCC extension.
getTypeOfExprType - Unlike many "get<Type>" functions, we can't unique TypeOfExprType AST's (since expression's are never shared).
For example, multiple declarations that refer to "typeof(x)" all contain different DeclRefExpr's. This doesn't effect the type checker, since it operates on canonical type's (which are always unique).
Definition at line 5647 of file ASTContext.cpp.
References getCanonicalType(), clang::Expr::getType(), clang::Expr::isTypeDependent(), clang::DependentTypeOfExprType::Profile(), clang::TypeAlignment, and clang::Unqualified.
Referenced by clang::Sema::BuildTypeofExprType(), and clang::ASTNodeImporter::VisitTypeOfExprType().
getTypeOfType()
QualType ASTContext::getTypeOfType (QualType tofType, TypeOfKind Kind) const
getTypeOfType - Unlike many "get<Type>" functions, we don't unique TypeOfType nodes.
The only motivation to unique these nodes would be memory savings. Since typeof(t) is fairly uncommon, space shouldn't be an issue. This doesn't affect the type checker, since it operates on canonical types (which are always unique).
Definition at line 5682 of file ASTContext.cpp.
References getCanonicalType(), and clang::TypeAlignment.
Referenced by ConvertDeclSpecToType(), getCommonSugarTypeNode(), clang::TreeTransform< Derived >::RebuildTypeOfType(), and clang::ASTNodeImporter::VisitTypeOfType().
getTypePackElementDecl()
BuiltinTemplateDecl * ASTContext::getTypePackElementDecl () const
Definition at line 1186 of file ASTContext.cpp.
References clang::BTK__type_pack_element, buildBuiltinTemplateDecl(), and getTypePackElementName().
Referenced by getPredefinedDecl(), and clang::ASTNodeImporter::VisitBuiltinTemplateDecl().
getTypePackElementName()
IdentifierInfo * clang::ASTContext::getTypePackElementName () const inline
Definition at line 1902 of file ASTContext.h.
References clang::IdentifierTable::get(), and Idents.
Referenced by getTypePackElementDecl().
getTypes()
const SmallVectorImpl< Type * > & clang::ASTContext::getTypes () const inline
Definition at line 1184 of file ASTContext.h.
Referenced by clang::TypoCorrectionConsumer::addNamespaces().
getTypeSize() [1/2]
uint64_t clang::ASTContext::getTypeSize (const Type * T) const inline
Definition at line 2297 of file ASTContext.h.
References getTypeInfo(), and clang::TypeInfo::Width.
getTypeSize() [2/2]
uint64_t clang::ASTContext::getTypeSize (QualType T) const inline
Return the size of the specified (complete) type T, in bits.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2296 of file ASTContext.h.
References getTypeInfo(), and clang::TypeInfo::Width.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnLastBitfield(), clang::Sema::ActOnNumericConstant(), actOnOMPReductionKindClause(), clang::Sema::ActOnVariableDeclarator(), addFieldSizes(), clang::Sema::AddModeAttr(), areCompatibleRVVTypes(), areCompatibleSveTypes(), areLaxCompatibleRVVTypes(), areLaxCompatibleSveTypes(), clang::Sema::areVectorTypesSameSize(), assertEqualBitWidths(), BitsContainNoUserData(), clang::Sema::BuildArrayType(), clang::Sema::BuildAsTypeExpr(), clang::Sema::BuildCXXNew(), buildMemcpyForAssignmentOp(), buildSingleCopyAssignRecursively(), clang::Sema::BuildVectorType(), calculateOffset(), canConvertIntTyToFloatTy(), canPassInRegisters(), ChangeIntegralSignedness(), checkAVXParam(), clang::Sema::CheckCompatibleReinterpretCast(), CheckImplicitConversion(), checkIntToPointerCast(), checkOpenMPLoop(), clang::Sema::CheckSizelessVectorConditionalTypes(), checkSizelessVectorShift(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkTypeSupport(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorOperands(), checkVectorResult(), checkVectorShift(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), clang::CodeGen::coerceToIntArray(), CompareStandardConversionSequences(), ConvertDeclSpecToType(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), CreateHexagonBuiltinVaListDecl(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), CreatePNaClABIBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), DeduceTemplateArgumentsByTypeMatch(), DiagnoseBadShiftValues(), DiagnoseDivisionSizeofPointerOrArray(), DiagnoseForRangeConstVariableCopies(), diagnoseListInit(), clang::ento::SMTConv::doFloatTypeConversion(), clang::ento::SMTConv::doIntTypeConversion(), clang::ento::SMTConv::doTypeConversion(), EmitAsmStores(), EmitBinaryAtomicPost(), emitDispatchForLoopBounds(), clang::CodeGen::ConstantEmitter::emitForMemory(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), emitOMPAtomicRMW(), emitReplacement(), EmitX86BitTestIntrinsic(), EvalAndBitcastToAPInt(), EvaluateComparisonBinaryOperator(), clang::Sema::FindAllocationFunctions(), clang::ento::SMTConv::fixAPSInt(), clang::ento::SMTConv::fromData(), getAlignOfGlobalVar(), getBestAbsFunction(), getBytesReturnedByAllocSizeCall(), clang::ento::SMTConv::getCastExpr(), GetCFNumberSize(), getCharWidth(), getDeclAlign(), getFieldSize(), getFixedPointSemantics(), getIntWidth(), clang::ConstantArrayType::getMaxSizeBits(), getNextLargerIntegralType(), clang::ConstantArrayType::getNumAddressingBits(), getPreferredTypeAlign(), getPromotedIntegerType(), getRangeForType(), getRVVTypeSize(), getScalableVectorType(), clang::Sema::GetSignedSizelessVectorType(), clang::Sema::GetSignedVectorType(), clang::ento::SMTConv::getSymExpr(), clang::ento::SMTConstraintManager::getSymVal(), clang::ento::SMTConv::getZeroExpr(), clang::ento::BasicValueFactory::getZeroWithTypeSize(), handleAnyX86InterruptAttr(), HandleArmSveVectorBitsTypeAttr(), HandleNeonVectorTypeAttr(), HandleRISCVRVVVectorBitsTypeAttr(), handleTransparentUnionAttr(), hasUniqueObjectRepresentations(), clang::Expr::IgnoreParenNoopCasts(), clang::Sema::Initialize(), is32Or64BitBasicType(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), isIntegerLikeType(), clang::Sema::IsIntegralPromotion(), clang::CodeGen::CodeGenModule::isPaddedAtomicType(), isPromotableBitField(), clang::CodeGen::isSIMDVectorType(), clang::CodeGen::isSingleElementStruct(), isZeroSized(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), clang::MangleContext::mangleName(), mergeEnumWithInteger(), OpenCLConvertScalarsToVectors(), RecoverCastedSymbol(), rewriteToNumericBoxedExpression(), tryGCCVectorConvertAndSplat(), TryInitializerListConstruction(), TryListConversion(), TryReinterpretCast(), and clang::Sema::VerifyBitField().
getTypeSizeInChars() [1/2]
CharUnits ASTContext::getTypeSizeInChars (const Type * T) const
Definition at line 2476 of file ASTContext.cpp.
References getTypeInfoInChars(), and clang::TypeInfoChars::Width.
getTypeSizeInChars() [2/2]
CharUnits ASTContext::getTypeSizeInChars (QualType T) const
Return the size of the specified (complete) type T, in characters.
getTypeSizeInChars - Return the size of the specified type, in characters.
This method does not work on incomplete types.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2473 of file ASTContext.cpp.
References getTypeInfoInChars(), and clang::TypeInfoChars::Width.
Referenced by clang::Sema::ActOnFields(), clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), AtomicUsesUnsupportedLibcall(), clang::Sema::BuildCXXNew(), buildMemcpyForAssignmentOp(), clang::Sema::BuildPredefinedExpr(), clang::ento::StoreManager::castRegion(), castValueToType(), clang::Sema::checkArrayElementAlignment(), CheckAtomicAlignment(), clang::Sema::CheckSubtractionOperands(), createRuntimeShuffleFunction(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DiagnoseSizeOfParametersAndReturnValue(), EmitArrayDelete(), emitArraySubscriptGEP(), EmitCXXNewAllocSize(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), EmitDeclInvariant(), EmitISOVolatileLoad(), EmitISOVolatileStore(), emitNonZeroVLAInit(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitPointerArithmetic(), emitStructGetterCall(), emitStructSetterCall(), EvaluateComparisonBinaryOperator(), evenFlexibleArraySize(), clang::Sema::FillInlineAsmIdentifierInfo(), forConstantArrayExpansion(), clang::CodeGen::CodeGenTBAA::getAccessInfo(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), getAlignmentAndOffsetFromBinAddOrSub(), getDerivedSymbolForBinding(), clang::VarDecl::getFlexibleArrayInitChars(), clang::CodeGen::CodeGenModule::getMinimumObjectSize(), clang::ConstantArrayType::getNumAddressingBits(), GetNumNonZeroBytesInInit(), getObjCEncodingForBlock(), getObjCEncodingForMethodDecl(), getObjCEncodingTypeSize(), clang::CodeGen::CGOpenCLRuntime::getPipeElemSize(), clang::CodeGen::AggValueSlot::getPreferredSize(), getSubobjectSizeInBits(), getTypeExpansion(), getTypeSizeInCharsIfKnown(), HandleSizeof(), isOnePastTheEndOfCompleteObject(), clang::Sema::isOpenMPCapturedByRef(), clang::CodeGen::CodeGenModule::Release(), setUsedBits(), setUsedBits(), shuffleAndStore(), unionHasUniqueObjectRepresentations(), clang::Value::Value(), and clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryExprOrTypeTraitExpr().
getTypeSizeInCharsIfKnown() [1/2]
std::optional< CharUnits > clang::ASTContext::getTypeSizeInCharsIfKnown (const Type * Ty) const inline
Definition at line 2321 of file ASTContext.h.
References getTypeSizeInCharsIfKnown().
getTypeSizeInCharsIfKnown() [2/2]
std::optional< CharUnits > clang::ASTContext::getTypeSizeInCharsIfKnown (QualType Ty) const inline
Definition at line 2315 of file ASTContext.h.
References getTypeSizeInChars(), clang::Type::isDependentType(), and clang::Type::isIncompleteType().
Referenced by clang::Sema::CheckStaticArrayArgument(), getTypeSizeInCharsIfKnown(), and clang::APValue::printPretty().
getTypeUnadjustedAlign() [1/2]
unsigned ASTContext::getTypeUnadjustedAlign (const Type * T) const
Definition at line 2434 of file ASTContext.cpp.
References getASTObjCInterfaceLayout(), getASTRecordLayout(), getTypeAlign(), clang::ASTRecordLayout::getUnadjustedAlignment(), and toBits().
getTypeUnadjustedAlign() [2/2]
unsigned clang::ASTContext::getTypeUnadjustedAlign (QualType T) const inline
Return the ABI-specified natural alignment of a (complete) type T, before alignment adjustments, in bits.
This alignment is curently used only by ARM and AArch64 when passing arguments of a composite type.
Definition at line 2335 of file ASTContext.h.
References getTypeUnadjustedAlign().
Referenced by getTypeUnadjustedAlign(), getTypeUnadjustedAlignInChars(), and getTypeUnadjustedAlignInChars().
getTypeUnadjustedAlignInChars() [1/2]
CharUnits ASTContext::getTypeUnadjustedAlignInChars (const Type * T) const
Definition at line 2495 of file ASTContext.cpp.
References getTypeUnadjustedAlign(), and toCharUnitsFromBits().
getTypeUnadjustedAlignInChars() [2/2]
CharUnits ASTContext::getTypeUnadjustedAlignInChars (QualType T) const
getTypeUnadjustedAlignInChars - Return the ABI-specified alignment of a type, in characters, before alignment adjustments.
This method does not work on incomplete types.
Definition at line 2492 of file ASTContext.cpp.
References getTypeUnadjustedAlign(), and toCharUnitsFromBits().
getucontext_tType()
QualType clang::ASTContext::getucontext_tType () const inline
Retrieve the C ucontext_t type.
Definition at line 1958 of file ASTContext.h.
References getTypeDeclType().
Referenced by DecodeTypeFromStr().
getUInt128Decl()
TypedefDecl * ASTContext::getUInt128Decl () const
Retrieve the declaration for the 128-bit unsigned integer type.
Definition at line 1225 of file ASTContext.cpp.
References buildImplicitTypedef(), and UnsignedInt128Ty.
Referenced by getPredefinedDecl(), and clang::Sema::Initialize().
getUIntMaxType()
CanQualType ASTContext::getUIntMaxType () const
Return the unique type for "uintmax_t" (C99 7.18.1.5), defined in <stdint.h>.
getUIntMaxType - Return the unique type for "uintmax_t" (C99 7.18.1.5).
Definition at line 5968 of file ASTContext.cpp.
Referenced by clang::analyze_scanf::ScanfSpecifier::getArgType().
getUIntPtrType()
QualType ASTContext::getUIntPtrType () const
Return a type compatible with "uintptr_t" (C99 7.18.1.4), as defined by the target.
Definition at line 5990 of file ASTContext.cpp.
References getCorrespondingUnsignedType(), and getIntPtrType().
Referenced by castValueFromUintptr(), emitOutlinedFunctionPrologue(), getCFConstantStringDecl(), clang::Sema::Initialize(), and clang::Sema::isOpenMPCapturedByRef().
getUnaryTransformType()
QualType ASTContext::getUnaryTransformType (QualType BaseType, QualType UnderlyingType, UnaryTransformType::UTTKind UKind) const
Unary type transforms.
getUnaryTransformationType - We don't unique these, since the memory savings are minimal and these are rare.
Definition at line 5748 of file ASTContext.cpp.
References getCanonicalType(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildUnaryTransformType(), getCommonNonSugarTypeNode(), getCommonSugarTypeNode(), and clang::ASTNodeImporter::VisitUnaryTransformType().
getUnconstrainedType()
QualType ASTContext::getUnconstrainedType (QualType T) const
Remove any type constraints from a template parameter type, for equivalence comparison of template parameters.
Definition at line 5849 of file ASTContext.cpp.
References clang::Type::containsUnexpandedParameterPack(), clang::Type::getAs(), getAutoType(), clang::QualType::getCanonicalType(), clang::Type::getContainedAutoType(), getQualifiedType(), and clang::QualType::getQualifiers().
Referenced by MatchTemplateParameterKind().
getUnnamedGlobalConstantDecl()
UnnamedGlobalConstantDecl * ASTContext::getUnnamedGlobalConstantDecl (QualType Ty, const APValue & Value) const
Return a declaration for a uniquified anonymous global constant corresponding to a given APValue.
Definition at line 12282 of file ASTContext.cpp.
References clang::UnnamedGlobalConstantDecl::Profile().
Referenced by clang::SourceLocExpr::EvaluateInContext().
getUnqualifiedArrayType()
QualType ASTContext::getUnqualifiedArrayType (QualType T, Qualifiers & Quals)
Return this type as a completely-unqualified array type, capturing the qualifiers in Quals.
This will remove the minimal amount of sugaring from the types, similar to the behavior of QualType::getUnqualifiedType().
Parameters
T is the qualified type, which may be an ArrayType
Quals will receive the full set of qualifiers that were applied to the array.
Returns
if this is an array type, the completely unqualified array type that corresponds to it. Otherwise, returns T.getUnqualifiedType().
Definition at line 6035 of file ASTContext.cpp.
References clang::Qualifiers::addConsistentQualifiers(), clang::cast(), clang::Qualifiers::empty(), getConstantArrayType(), getDependentSizedArrayType(), getIncompleteArrayType(), getUnqualifiedArrayType(), clang::Type::getUnqualifiedDesugaredType(), getVariableArrayType(), clang::SplitQualType::Quals, and clang::SplitQualType::Ty.
Referenced by clang::Sema::BuildCXXTypeId(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuiltinChangeCVRQualifiers(), clang::Sema::BuiltinRemoveReference(), CastsAwayConstness(), CompareQualificationConversions(), clang::Sema::CompareReferenceRelationship(), CompareStandardConversionSequences(), DeduceTemplateArgumentsByTypeMatch(), EvaluateBinaryTypeTrait(), clang::Sema::FindCompositePointerType(), clang::CXXTypeidExpr::getTypeOperand(), clang::CXXUuidofExpr::getTypeOperand(), getUnqualifiedArrayType(), clang::Sema::handlerCanCatch(), hasCvrSimilarType(), hasSimilarType(), isSubstitutedType(), shouldBeModeledWithNoOp(), TryReferenceInitialization(), TryReferenceListInitialization(), and withoutUnaligned().
getUnqualifiedObjCPointerType()
QualType clang::ASTContext::getUnqualifiedObjCPointerType (QualType type) const inline
getUnqualifiedObjCPointerType - Returns version of Objective-C pointer type with lifetime qualifier removed.
Definition at line 2157 of file ASTContext.h.
References getQualifiedType(), clang::Qualifiers::removeObjCLifetime(), and clang::ast_matchers::type.
Referenced by clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar().
getUnresolvedUsingType()
QualType ASTContext::getUnresolvedUsingType (const UnresolvedUsingTypenameDecl * Decl) const
Definition at line 4778 of file ASTContext.cpp.
References clang::Decl::getCanonicalDecl(), and clang::TypeAlignment.
getUnsignedPointerDiffType()
QualType ASTContext::getUnsignedPointerDiffType () const
Return the unique unsigned counterpart of "ptrdiff_t" integer type.
The standard (C11 7.21.6.1p7) refers to this type in the definition of tu format specifier.
Definition at line 6003 of file ASTContext.cpp.
References clang::Default.
Referenced by clang::Sema::ActOnOpenMPCanonicalLoop(), and clang::analyze_scanf::ScanfSpecifier::getArgType().
getUnsignedWCharType()
QualType ASTContext::getUnsignedWCharType () const
Return the type of "unsigned wchar_t".
getUnsignedWCharType - Return the type of "unsigned wchar_t".
Used when in C++, as a GCC extension.
Definition at line 5981 of file ASTContext.cpp.
References UnsignedIntTy.
Referenced by ConvertDeclSpecToType(), and getCorrespondingUnsignedType().
getUsingType()
QualType ASTContext::getUsingType (const UsingShadowDecl * Found, QualType Underlying) const
Definition at line 4725 of file ASTContext.cpp.
References Allocate(), clang::cast(), clang::Type::getCanonicalTypeInternal(), clang::UsingShadowDecl::getTargetDecl(), clang::QualType::getTypePtr(), clang::QualType::hasLocalQualifiers(), clang::QualType::isNull(), clang::UsingType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::ClassifyName(), getCommonSugarTypeNode(), clang::Sema::getTypeName(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), clang::TreeTransform< Derived >::RebuildUsingType(), and clang::ASTNodeImporter::VisitUsingType().
getVaListTagDecl()
Decl * ASTContext::getVaListTagDecl () const
Retrieve the C type declaration corresponding to the predefined __va_list_tag type used to help define the __builtin_va_list type for some targets.
Definition at line 9153 of file ASTContext.cpp.
References getBuiltinVaListDecl(), and VaListTagDecl.
Referenced by clang::ASTImporterLookupTable::ASTImporterLookupTable(), getPredefinedDecl(), and isImportedDeclContext().
getVariableArrayDecayedType()
QualType ASTContext::getVariableArrayDecayedType (QualType Ty) const
Returns a vla type where known sizes are replaced with [*].
getVariableArrayDecayedType - Turns the given type, which may be variably-modified, into the corresponding type with all the known sizes replaced with [*].
Definition at line 3605 of file ASTContext.cpp.
References clang::cast(), getAtomicType(), getConstantArrayType(), getDependentSizedArrayType(), getLValueReferenceType(), getPointerType(), getQualifiedType(), getRValueReferenceType(), clang::Type::getTypeClass(), getVariableArrayDecayedType(), getVariableArrayType(), clang::ArrayType::Normal, clang::SplitQualType::Quals, clang::ArrayType::Star, clang::SplitQualType::Ty, and clang::ast_matchers::type.
Referenced by getCanonicalParamType(), getExceptionObjectType(), getSignatureParameterType(), and getVariableArrayDecayedType().
getVariableArrayType()
QualType ASTContext::getVariableArrayType (QualType EltTy, Expr * NumElts, ArrayType::ArraySizeModifier ASM, unsigned IndexTypeQuals, SourceRange Brackets) const
Return a non-unique reference to the type for a variable array of the specified element type.
getVariableArrayType - Returns a non-unique reference to the type for a variable array of the specified element type.
Definition at line 3745 of file ASTContext.cpp.
References getCanonicalType(), getQualifiedType(), getVariableArrayType(), clang::QualType::hasLocalQualifiers(), clang::QualType::isCanonical(), clang::SplitQualType::Quals, clang::CanQual< typename >::split(), clang::SplitQualType::Ty, and clang::TypeAlignment.
Referenced by actOnOMPReductionKindClause(), clang::Sema::BuildArrayType(), clang::desugarForDiagnostic(), getAsArrayType(), getUnqualifiedArrayType(), getVariableArrayDecayedType(), getVariableArrayType(), and clang::ASTNodeImporter::VisitVariableArrayType().
getVectorType()
QualType ASTContext::getVectorType (QualType vecType, unsigned NumElts, VectorType::VectorKind VecKind) const
Return the unique reference to a vector type of the specified element type and size.
getVectorType - Return the unique reference to a vector type of the specified element type and size.
Precondition
VectorType must be a built-in type.
VectorType must be a built-in type.
Definition at line 4066 of file ASTContext.cpp.
References clang::Type::getAs(), getCanonicalType(), clang::BitIntType::getNumBits(), getVectorType(), clang::Type::isBitIntType(), clang::Type::isBuiltinType(), clang::QualType::isCanonical(), clang::VectorType::Profile(), and clang::TypeAlignment.
Referenced by clang::Sema::AddModeAttr(), clang::Sema::BuildVectorType(), clang::Sema::CheckVectorConditionalTypes(), ConvertDeclSpecToType(), convertVector(), DecodePPCMMATypeFromStr(), DecodeTypeFromStr(), getCommonNonSugarTypeNode(), getCorrespondingSignedType(), getCorrespondingUnsignedType(), clang::Sema::GetSignedVectorType(), getVectorType(), HandleArmSveVectorBitsTypeAttr(), HandleNeonVectorTypeAttr(), HandleRISCVRVVVectorBitsTypeAttr(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), clang::TreeTransform< Derived >::RebuildVectorType(), clang::Sema::SemaBuiltinShuffleVector(), and clang::ASTNodeImporter::VisitVectorType().
getVolatileType()
QualType clang::ASTContext::getVolatileType (QualType T) const inline
Return the uniqued reference to the type for a volatile qualified type.
The resulting type has a union of the qualifiers from T and volatile.
Definition at line 1264 of file ASTContext.h.
References clang::Qualifiers::Volatile, and clang::QualType::withFastQualifiers().
Referenced by AddBuiltinAssignmentOperatorCandidates(), DecodeTypeFromStr(), and makeQualifiedLValueReferenceType().
getVTableContext()
VTableContextBase * ASTContext::getVTableContext ()
Definition at line 12019 of file ASTContext.cpp.
References getLangOpts(), clang::ItaniumVTableContext::Pointer, and clang::ItaniumVTableContext::Relative.
Referenced by clang::ASTNameGenerator::Implementation::getAllManglings().
getWCharType()
QualType clang::ASTContext::getWCharType () const inline
Return the unique wchar_t type available in C++ (and available as __wchar_t as a Microsoft extension).
Definition at line 1754 of file ASTContext.h.
References WCharTy.
getWebAssemblyExternrefType()
QualType ASTContext::getWebAssemblyExternrefType () const
Return a WebAssembly externref type.
getExternrefType - Return a WebAssembly externref type, which represents an opaque reference to a host value.
Definition at line 4011 of file ASTContext.cpp.
getWideCharType()
QualType clang::ASTContext::getWideCharType () const inline
Return the type of wide characters.
In C++, this returns the unique wchar_t type. In C99, this returns a type compatible with the type defined in <stddef.h> as defined by the target.
Definition at line 1759 of file ASTContext.h.
References WideCharTy.
Referenced by clang::Sema::ActOnStringLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCNumericLiteral(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), IsStringInit(), clang::Sema::IsStringLiteralToNonConstPointerConversion(), IsWideCharCompatible(), and clang::CodeGen::CodeGenModule::Release().
getWIntType()
QualType clang::ASTContext::getWIntType () const inline
In C99, this returns a type compatible with the type defined in <stddef.h> as defined by the target.
Definition at line 1773 of file ASTContext.h.
References WIntTy.
getWritePipeType()
QualType ASTContext::getWritePipeType (QualType T) const
Return a write_only pipe type for the specified type.
Definition at line 4592 of file ASTContext.cpp.
Referenced by clang::Sema::BuildWritePipeType(), getCommonNonSugarTypeNode(), and HandleOpenCLAccessAttr().
getXRayFilter()
const XRayFunctionFilter & clang::ASTContext::getXRayFilter () const inline
Definition at line 773 of file ASTContext.h.
Referenced by clang::CodeGen::CodeGenModule::imbueXRayAttrs().
hasCvrSimilarType()
bool ASTContext::hasCvrSimilarType (QualType T1, QualType T2)
Determine if two types are similar, ignoring only CVR qualifiers.
Definition at line 6197 of file ASTContext.cpp.
References getUnqualifiedArrayType(), hasSameType(), clang::Qualifiers::removeCVRQualifiers(), and UnwrapSimilarTypes().
Referenced by clang::Sema::CheckAssignmentConstraints(), clang::Sema::PrepareScalarCast(), and TryConstCast().
hasDirectOwnershipQualifier()
bool ASTContext::hasDirectOwnershipQualifier (QualType Ty) const
Return true if the type has been explicitly qualified with ObjC ownership.
A type may be implicitly qualified with ownership under ObjC ARC, and in some cases the compiler treats these differently.
Definition at line 9638 of file ASTContext.cpp.
References Paren.
Referenced by clang::Sema::ActOnFields(), captureInBlock(), and handleObjCOwnershipTypeAttr().
hasSameExpr()
bool ASTContext::hasSameExpr (const Expr * X, const Expr * Y) const
Determine whether the given expressions X and Y are equivalent.
Definition at line 12382 of file ASTContext.cpp.
References clang::Stmt::Profile(), and X.
Referenced by getCommonNonSugarTypeNode(), and getCommonSizeExpr().
hasSameFunctionTypeIgnoringExceptionSpec()
bool ASTContext::hasSameFunctionTypeIgnoringExceptionSpec (QualType T, QualType U) const
Determine whether two function types are the same, ignoring exception specifications in cases where they're part of the type.
Definition at line 3227 of file ASTContext.cpp.
References clang::EST_None, getFunctionTypeWithExceptionSpec(), getLangOpts(), and hasSameType().
Referenced by clang::Sema::ActOnFunctionDeclarator(), isSameEntity(), and clang::Sema::MergeFunctionDecl().
hasSameFunctionTypeIgnoringPtrSizes()
bool ASTContext::hasSameFunctionTypeIgnoringPtrSizes (QualType T, QualType U)
Determine whether two function types are the same, ignoring pointer sizes in the return type and parameter types.
Definition at line 3252 of file ASTContext.cpp.
References getFunctionTypeWithoutPtrSizes(), and hasSameType().
Referenced by clang::Sema::MergeFunctionDecl().
hasSameNullabilityTypeQualifier()
bool clang::ASTContext::hasSameNullabilityTypeQualifier (QualType SubT, QualType SuperT, bool IsParam) const inline
Definition at line 2572 of file ASTContext.h.
References clang::Type::getNullability(), clang::NonNull, clang::Nullable, and clang::Unspecified.
Referenced by CheckMethodOverrideParam(), and CheckMethodOverrideReturn().
hasSameTemplateName()
bool ASTContext::hasSameTemplateName (const TemplateName & X, const TemplateName & Y) const
Determine whether the given template names refer to the same template.
Definition at line 6317 of file ASTContext.cpp.
References clang::TemplateName::getAsVoidPointer(), getCanonicalTemplateName(), and X.
Referenced by clang::Sema::BuildMemInitializer(), checkDeducedTemplateArguments(), clang::Sema::CheckDeductionGuideDeclarator(), DeduceTemplateArguments(), and isSameDefaultTemplateArgument().
hasSameType() [1/2]
bool clang::ASTContext::hasSameType (const Type * T1, const Type * T2) const inline
Definition at line 2543 of file ASTContext.h.
References getCanonicalType().
hasSameType() [2/2]
bool clang::ASTContext::hasSameType (QualType T1, QualType T2) const inline
Determine whether the given types T1 and T2 are equivalent.
Definition at line 2540 of file ASTContext.h.
References getCanonicalType().
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnPropertyImplDecl(), AddResultTypeChunk(), adjustBlockReturnsToEnum(), areCompatibleRVVTypes(), areCompatibleSveTypes(), areCompatibleVectorTypes(), AreSpecialMemberFunctionsSameKind(), buildCounterInit(), buildCounterUpdate(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXNestedNameSpecifier(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDeclaratorGroup(), buildDeclareReductionRef(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), buildUserDefinedMapperRef(), clang::Sema::BuildVAArgExpr(), castToBase(), clang::Sema::CheckARCMethodDecl(), clang::Sema::CheckAssignmentConstraints(), checkCastFunctionType(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), checkDeducedTemplateArguments(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckImplementationIvars(), clang::Sema::CheckLiteralOperatorDeclaration(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckMain(), clang::Sema::CheckMatrixElementwiseOperands(), clang::Sema::CheckMatrixMultiplyOperands(), clang::Sema::CheckMemberSpecialization(), checkOpenCLPipePacketType(), checkOpenMPLoop(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::Sema::CheckSizelessVectorOperands(), clang::Sema::CheckTemplateArgument(), checkTypeParamListConsistency(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVectorOperands(), ClassImplementsAllMethodsAndProperties(), CompareDerivedToBaseConversions(), CompareStandardConversionSequences(), compareStandardConversionSubsets(), clang::Sema::computeDeclContext(), ConvertQualTypeToKind(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceAutoType(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DiagnoseBadDeduction(), DiagnoseCallingConvCast(), DiagnoseCastOfObjCSEL(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnosePropertyAccessorMismatch(), clang::Sema::diagnoseQualifiedDeclaration(), diagnoseVarDeclTypeMismatch(), EvaluateBinaryTypeTrait(), filterNonConflictingPreviousTypedefDecls(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindCompositeObjCPointerType(), clang::Sema::FindCompositePointerType(), findDecomposableBaseClass(), clang::ClassTemplateDecl::findPartialSpecialization(), clang::StructuralEquivalenceContext::findUntaggedStructOrUnionIndex(), clang::Sema::FixOverloadedFunctionReference(), forEachMultiversionedFunctionVersion(), clang::Sema::FunctionParamTypesAreEqual(), getBestAbsFunction(), getCommonSugaredType(), getCommonSugarTypeNode(), getCommonTemplateArgument(), getFixedEnumPromtion(), clang::Sema::getMoreSpecializedTemplate(), getTypedefType(), HandleConstructorCall(), clang::Sema::HandleFunctionTypeMismatch(), clang::Sema::HandlePropertyInClassExtension(), handleVecTypeHint(), hasCompatibleArrayTypes(), hasCvrSimilarType(), hasSameFunctionTypeIgnoringExceptionSpec(), hasSameFunctionTypeIgnoringPtrSizes(), hasSimilarType(), implicitObjectParamIsLifetimeBound(), clang::Sema::IsBlockPointerConversion(), IsEquivalentForUsingDecl(), clang::Sema::isEquivalentInternalLinkageDeclaration(), clang::Sema::isIncompatibleTypedef(), clang::Sema::IsOverload(), isRelevantAttr(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), isSameDefaultTemplateArgument(), isSameEntity(), clang::Sema::isSameOrCompatibleFunctionType(), isSameTemplateArg(), clang::ASTImporter::IsStructurallyEquivalent(), isSubstitutedType(), isValidInteropVariable(), loadToBegin(), MatchTemplateParameterKind(), mergeEnumWithInteger(), clang::Sema::MergeFunctionDecl(), clang::Sema::MergeVarDeclExceptionSpecs(), clang::Sema::MergeVarDeclTypes(), ObjCMethodsAreEqual(), clang::InitializationSequence::Perform(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PrepareScalarCast(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), rewriteToNumberLiteral(), sameObjCTypeArgs(), clang::Sema::setTagNameForLinkagePurposes(), TryAddressSpaceCast(), TryConstructorInitialization(), TryReferenceInitializationCore(), TryRefInitWithConversionFunction(), TryUserDefinedConversion(), typesAreCompatible(), and clang::Sema::UsualArithmeticConversions().
hasSameUnqualifiedType()
bool clang::ASTContext::hasSameUnqualifiedType (QualType T1, QualType T2) const inline
Determine whether the given types are equivalent after cvr-qualifiers have been removed.
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2567 of file ASTContext.h.
References getCanonicalType(), and clang::CanQual< typename >::getTypePtr().
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::AddConversionCandidate(), AddObjCKeyValueCompletions(), clang::Sema::AddOverloadCandidate(), AddSuperSendCompletion(), AnalyzeComparison(), areCompatibleVectorTypes(), argTypeIsABIEquivalent(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildPseudoDestructorExpr(), checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckCompatibleReinterpretCast(), clang::Sema::CheckConstraintExpression(), checkEnumArithmeticConversions(), clang::Sema::CheckEnumRedeclaration(), checkEnumTypesInSwitchStmt(), clang::Sema::CheckExtVectorCast(), clang::Sema::CheckMain(), CheckMethodOverrideParam(), CheckMethodOverrideReturn(), CheckMoveOnConstruction(), CheckOriginalCallArgDeduction(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckPointerConversion(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::CheckSubtractionOperands(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), CheckTemplateArgumentPointerToMember(), clang::Sema::CodeCompleteConstructorInitializer(), CompareDerivedToBaseConversions(), CompareImplicitConversionSequences(), clang::Sema::CompareReferenceRelationship(), CopyObject(), createObjCPropertyGetter(), clang::Sema::CreateOverloadedBinOp(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::deduceVarTypeFromInitializer(), diagnoseArithmeticOnTwoFunctionPointers(), clang::Sema::DiagnoseAssignmentEnum(), DiagnoseDivisionSizeofPointerOrArray(), doRewriteToUTF8StringBoxedExpressionHelper(), EmitAtomicCmpXchgForMSIntrin(), EmitBinaryAtomicPost(), clang::Sema::EmitRelatedResultTypeNote(), clang::Sema::EmitRelatedResultTypeNoteForReturn(), EvaluateBinaryTypeTrait(), EvaluateBuiltinStrLen(), FindBaseInitializer(), FindImplementableMethods(), FunctionsCorrespond(), getCommonSugaredType(), clang::Sema::getCopyElisionCandidate(), clang::Sema::getDestructorName(), clang::Sema::getDestructorTypeForDecltype(), getExistingLazyBinding(), getParamType(), getPreferredArgumentTypeForMessageSend(), getRangeOfTypeInNestedNameSpecifier(), clang::CastExpr::getTargetFieldForToUnionCast(), clang::Sema::handlerCanCatch(), HandleVirtualDispatch(), hasCopyOrMoveCtorParam(), hasSimilarParameters(), haveSameParameterTypes(), clang::Expr::IgnoreParenNoopCasts(), clang::InitializationSequence::InitializeFrom(), IsAcceptableNonMemberOperatorCandidate(), isAllowableExplicitConversion(), clang::CXXMethodDecl::isCopyAssignmentOperator(), isFirstArgumentCompatibleWithType(), clang::Sema::IsFunctionConversion(), clang::Sema::IsIntegralPromotion(), clang::Sema::IsMemberPointerConversion(), clang::Sema::isMicrosoftMissingTypename(), clang::CXXMethodDecl::isMoveAssignmentOperator(), isNonPlacementDeallocationFunction(), isNullPointerValueTemplateArgument(), clang::Sema::isObjCPointerConversion(), clang::Sema::isObjCWritebackConversion(), clang::Sema::IsPointerConversion(), clang::Sema::IsQualificationConversion(), IsStandardConversion(), IsUserDefinedConversion(), clang::CXXMethodDecl::isUsualDeallocationFunction(), IsVectorConversion(), clang::Sema::LookupLiteralOperator(), LookupMemberExpr(), MakeBinaryAtomicValue(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PrepareScalarCast(), clang::Sema::ProcessPropertyDecl(), clang::Sema::SemaBuiltinShuffleVector(), clang::OverloadCandidateSet::OperatorRewriteInfo::shouldAddReversed(), ShouldDiagnoseSwitchCaseNotInEnum(), TryConstructorInitialization(), TryImplicitConversion(), TryListConversion(), TryListInitialization(), TryStaticMemberPointerUpcast(), TryUserDefinedConversion(), and UnwrapSimilarTypes().
hasSimilarType()
bool ASTContext::hasSimilarType (QualType T1, QualType T2)
Determine if two types are similar, according to the C++ rules.
That is, determine if they are the same other than qualifiers on the initial sequence of pointer / pointer-to-member / array (and in Clang, object pointer) types and their element types.
Clang offers a number of qualifiers in addition to the C++ qualifiers; those qualifiers are also ignored in the 'similarity' check.
Definition at line 6185 of file ASTContext.cpp.
References getUnqualifiedArrayType(), hasSameType(), and UnwrapSimilarTypes().
Referenced by clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::CompareReferenceRelationship(), and compareStandardConversionSubsets().
hasUniqueObjectRepresentations()
bool ASTContext::hasUniqueObjectRepresentations (QualType Ty, bool CheckIfTriviallyCopyable = true) const
Return true if the specified type has unique object representations according to (C++17 [meta.unary.prop]p9)
Definition at line 2805 of file ASTContext.cpp.
References clang::Type::castAs(), clang::Type::getAs(), getBaseElementType(), getTypeSize(), hasUniqueObjectRepresentations(), clang::Type::isArrayType(), clang::Type::isIntegralOrEnumerationType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::Type::isRecordType(), clang::QualType::isTriviallyCopyableType(), structHasUniqueObjectRepresentations(), and unionHasUniqueObjectRepresentations().
Referenced by getSubobjectSizeInBits(), hasUniqueObjectRepresentations(), clang::QualType::isTriviallyEqualityComparableType(), and unionHasUniqueObjectRepresentations().
InitBuiltinTypes()
void ASTContext::InitBuiltinTypes (const TargetInfo & Target, const TargetInfo * AuxTarget = nullptr)
Initialize built-in types.
This routine may only be invoked once for a given ASTContext object. It is normally invoked after ASTContext construction.
Parameters
Target The target
Definition at line 1237 of file ASTContext.cpp.
References AccumTy, clang::DeclContext::addDecl(), ARCUnbridgedCastTy, BFloat16Ty, BoolTy, BoundMemberTy, buildImplicitRecord(), BuiltinFnTy, Char16Ty, Char32Ty, Char8Ty, CharTy, DependentTy, DoubleTy, Float128Ty, Float16Ty, FloatTy, FractTy, getCanonicalType(), getPointerType(), getQualifiedType(), clang::CanQual< typename >::getQualifiers(), getTranslationUnitDecl(), clang::CanQual< typename >::getUnqualifiedType(), HalfTy, Ibm128Ty, IncompleteMatrixIdxTy, Int128Ty, IntTy, isAddrSpaceMapManglingEnabled(), clang::CanQual< typename >::isNull(), clang::TargetInfo::isTypeSigned(), LongAccumTy, LongDoubleTy, LongFractTy, LongLongTy, LongTy, MSGuidTagDecl, NullPtrTy, ObjCBuiltinBoolTy, ObjCBuiltinClassTy, ObjCBuiltinIdTy, ObjCBuiltinSelTy, OCLClkEventTy, OCLEventTy, OCLQueueTy, OCLReserveIDTy, OCLSamplerTy, OMPArraySectionTy, OMPArrayShapingTy, OMPIteratorTy, clang::opencl_generic, OverloadTy, PseudoObjectTy, SatAccumTy, SatFractTy, SatLongAccumTy, SatLongFractTy, SatShortAccumTy, SatShortFractTy, SatUnsignedAccumTy, SatUnsignedFractTy, SatUnsignedLongAccumTy, SatUnsignedLongFractTy, SatUnsignedShortAccumTy, SatUnsignedShortFractTy, clang::Qualifiers::setAddressSpace(), ShortAccumTy, ShortFractTy, ShortTy, SignedCharTy, UnknownAnyTy, UnsignedAccumTy, UnsignedCharTy, UnsignedFractTy, UnsignedInt128Ty, UnsignedIntTy, UnsignedLongAccumTy, UnsignedLongFractTy, UnsignedLongLongTy, UnsignedLongTy, UnsignedShortAccumTy, UnsignedShortFractTy, UnsignedShortTy, VaListTagDecl, VoidPtrTy, VoidTy, WCharTy, WideCharTy, and WIntTy.
isAlignmentRequired() [1/2]
bool ASTContext::isAlignmentRequired (const Type * T) const
Determine if the alignment the type has was required using an alignment attribute.
Definition at line 1878 of file ASTContext.cpp.
References clang::TypeInfo::AlignRequirement, getTypeInfo(), and clang::None.
Referenced by isAlignmentRequired(), and isVarDeclStrongDefinition().
isAlignmentRequired() [2/2]
bool ASTContext::isAlignmentRequired (QualType T) const
Definition at line 1882 of file ASTContext.cpp.
References isAlignmentRequired().
isDependenceAllowed()
bool clang::ASTContext::isDependenceAllowed () const inline
Definition at line 767 of file ASTContext.h.
Referenced by clang::Sema::ActOnConditionalOp(), clang::Sema::BuildCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckPlaceholderExpr(), and CorrectDelayedTyposInBinOp().
isMSStaticDataMemberInlineDefinition()
bool ASTContext::isMSStaticDataMemberInlineDefinition (const VarDecl * VD) const
Returns true if this is an inline-initialized static data member which is treated as a definition for MSVC compatibility.
Definition at line 7647 of file ASTContext.cpp.
References clang::TargetInfo::getCXXABI(), clang::Redeclarable< decl_type >::getFirstDecl(), getTargetInfo(), clang::ValueDecl::getType(), clang::VarDecl::hasInit(), clang::Type::isIntegralOrEnumerationType(), clang::TargetCXXABI::isMicrosoft(), clang::VarDecl::isOutOfLine(), and clang::VarDecl::isStaticDataMember().
Referenced by basicGVALinkageForVariable(), DeclMustBeEmitted(), and clang::CodeGen::CodeGenModule::EmitGlobal().
isNearlyEmpty()
bool ASTContext::isNearlyEmpty (const CXXRecordDecl * RD) const
Definition at line 12014 of file ASTContext.cpp.
isObjCClassType()
bool clang::ASTContext::isObjCClassType (QualType T) const inline
Definition at line 2855 of file ASTContext.h.
References getObjCClassType().
isObjCIdType()
bool clang::ASTContext::isObjCIdType (QualType T) const inline
Definition at line 2849 of file ASTContext.h.
References getObjCIdType().
Referenced by maybeAdjustInterfaceForSubscriptingCheck().
isObjCNSObjectType()
static bool clang::ASTContext::isObjCNSObjectType (QualType Ty) inline static
Return true if this is an NSObject object with its NSObject attribute set.
Definition at line 2276 of file ASTContext.h.
References clang::Type::isObjCNSObjectType().
Referenced by BlockRequiresCopying(), clang::Sema::BuildInstanceMessage(), and clang::Sema::CheckAssignmentOperands().
isObjCSelType()
bool clang::ASTContext::isObjCSelType (QualType T) const inline
Definition at line 2861 of file ASTContext.h.
References getObjCSelType().
Referenced by clang::Sema::FindCompositeObjCPointerType().
isPromotableBitField()
QualType ASTContext::isPromotableBitField (Expr * E) const
Whether this is a promotable bitfield reference according to C99 6.3.1.1p2, bullet 2 (and GCC extensions).
Returns
the type this bit-field will promote to, or NULL if no promotion occurs.
Definition at line 7133 of file ASTContext.cpp.
References clang::CPlusPlus, getLangOpts(), clang::Expr::getSourceBitField(), clang::Expr::getType(), getTypeSize(), IntTy, clang::Type::isEnumeralType(), clang::Type::isSignedIntegerType(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and UnsignedIntTy.
Referenced by clang::Sema::CheckAdditionOperands(), clang::Sema::UsualArithmeticConversions(), and clang::Sema::UsualUnaryConversions().
isPromotableIntegerType()
bool ASTContext::isPromotableIntegerType (QualType T) const
More type predicates useful for type checking/promotion.
Definition at line 1840 of file ASTContext.cpp.
References getLangOpts(), and clang::HLSL.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnTag(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckAdditionOperands(), checkArithmeticOrEnumeralThreeWayCompare(), clang::ento::SMTConv::doIntTypeConversion(), GetFullTypeForDeclarator(), getPromotedIntegerType(), isArithmeticArgumentPromotion(), clang::Sema::IsIntegralPromotion(), isOverflowingIntegerType(), mergeFunctionTypes(), clang::Sema::UsualArithmeticConversions(), and clang::Sema::UsualUnaryConversions().
isSameConstraintExpr()
bool ASTContext::isSameConstraintExpr (const Expr * XCE, const Expr * YCE) const
Determine whether two 'requires' expressions are similar enough that they may be used in re-declarations.
Use of 'requires' isn't mandatory, works with constraints expressed in other ways too.
Definition at line 6323 of file ASTContext.cpp.
References clang::Stmt::Profile().
Referenced by isSameEntity(), isSameTemplateParameter(), isSameTemplateParameterList(), and isSameTypeConstraint().
isSameDefaultTemplateArgument()
bool ASTContext::isSameDefaultTemplateArgument (const NamedDecl * X, const NamedDecl * Y) const
Determine whether two default template arguments are similar enough that they may be used in declarations of the same template.
Definition at line 6416 of file ASTContext.cpp.
References clang::cast(), clang::TemplateArgument::getAsTemplate(), hasSameTemplateName(), hasSameType(), clang::Expr::IgnoreImpCasts(), isSameTemplateParameter(), clang::Stmt::Profile(), and X.
isSameEntity()
bool ASTContext::isSameEntity (const NamedDecl * X, const NamedDecl * Y) const
Determine whether the two declarations refer to the same entity.
Definition at line 6535 of file ASTContext.cpp.
References clang::cast(), clang::CPlusPlus17, clang::declaresSameEntity(), clang::Type::getAs(), getAsArrayType(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ArrayType::getElementType(), clang::FunctionProtoType::getExceptionSpecType(), clang::Decl::getKind(), getLangOpts(), clang::DeclContext::getRedeclContext(), hasSameFunctionTypeIgnoringExceptionSpec(), hasSameOverloadableAttrs(), hasSameType(), clang::Type::isIncompleteArrayType(), isSameConstraintExpr(), isSameEntity(), isSameQualifier(), isSameTemplateParameterList(), clang::isUnresolvedExceptionSpec(), and X.
Referenced by clang::Sema::CheckConceptRedefinition(), isSameEntity(), and isSameTypeConstraint().
isSameTemplateParameter()
bool ASTContext::isSameTemplateParameter (const NamedDecl * X, const NamedDecl * Y) const
Determine whether two template parameters are similar enough that they may be used in declarations of the same template.
Definition at line 6374 of file ASTContext.cpp.
References clang::cast(), clang::Decl::getKind(), isSameConstraintExpr(), isSameTemplateParameterList(), isSameTypeConstraint(), and X.
Referenced by isSameDefaultTemplateArgument(), and isSameTemplateParameterList().
isSameTemplateParameterList()
bool ASTContext::isSameTemplateParameterList (const TemplateParameterList * X, const TemplateParameterList * Y) const
Determine whether two template parameter lists are similar enough that they may be used in declarations of the same template.
Definition at line 6404 of file ASTContext.cpp.
References clang::TemplateParameterList::getParam(), clang::TemplateParameterList::getRequiresClause(), isSameConstraintExpr(), isSameTemplateParameter(), N, clang::TemplateParameterList::size(), and X.
Referenced by FunctionsCorrespond(), isSameEntity(), and isSameTemplateParameter().
isSameTypeConstraint()
bool ASTContext::isSameTypeConstraint (const TypeConstraint * XTC, const TypeConstraint * YTC) const
Determine whether two type contraint are similar enough that they could used in declarations of the same template.
Definition at line 6336 of file ASTContext.cpp.
References clang::TypeConstraint::getImmediatelyDeclaredConstraint(), clang::ConceptReference::getNamedConcept(), clang::ConceptReference::getTemplateArgsAsWritten(), clang::ConceptReference::hasExplicitTemplateArgs(), isSameConstraintExpr(), isSameEntity(), and clang::ASTTemplateArgumentListInfo::NumTemplateArgs.
Referenced by isSameTemplateParameter().
isSentinelNullExpr()
bool ASTContext::isSentinelNullExpr (const Expr * E)
Definition at line 2895 of file ASTContext.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::Type::isAnyPointerType(), clang::Expr::isNullPointerConstant(), clang::Type::isNullPtrType(), and clang::Expr::NPC_ValueDependentIsNull.
Referenced by clang::Sema::DiagnoseSentinelCalls(), getNSArrayObjects(), rewriteToArrayLiteral(), and rewriteToDictionaryLiteral().
local_imports()
import_range clang::ASTContext::local_imports () const inline
Definition at line 1017 of file ASTContext.h.
lookupFieldBitOffset()
uint64_t ASTContext::lookupFieldBitOffset (const ObjCInterfaceDecl * OID, const ObjCImplementationDecl * ID, const ObjCIvarDecl * Ivar) const
Get the offset of an ObjCIvarDecl in bits.
Definition at line 3442 of file RecordLayoutBuilder.cpp.
References clang::declaresSameEntity(), clang::ObjCIvarDecl::getCanonicalDecl(), clang::ObjCIvarDecl::getContainingInterface(), and clang::ASTRecordLayout::getFieldOffset().
Referenced by clang::CodeGen::CGObjCRuntime::ComputeBitfieldBitOffset(), clang::CodeGen::CGObjCRuntime::ComputeIvarBaseOffset(), clang::CodeGen::CGObjCRuntime::ComputeIvarBaseOffset(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), and EncodeBitField().
MakeIntValue()
llvm::APSInt clang::ASTContext::MakeIntValue (uint64_t Value, QualType Type) const inline
Make an APSInt of the appropriate width and signedness for the given Value and integer Type.
Definition at line 2971 of file ASTContext.h.
References getIntWidth(), and clang::Type::isSignedIntegerOrEnumerationType().
Referenced by clang::SourceLocExpr::EvaluateInContext(), getTrivialIntegralTemplateArgument(), and clang::APValue::toIntegralConstant().
mayExternalize()
bool ASTContext::mayExternalize (const Decl * D) const
Whether a C++ static variable or CUDA/HIP kernel may be externalized.
Definition at line 13578 of file ASTContext.cpp.
References basicGVALinkageForFunction(), basicGVALinkageForVariable(), clang::Decl::getAttr(), clang::GVA_Internal, clang::Decl::hasAttr(), and clang::isa().
Referenced by shouldExternalize().
mergeDefinitionIntoModule()
void ASTContext::mergeDefinitionIntoModule (NamedDecl * ND, Module * M, bool NotifyListeners = true)
Note that the definition ND has been merged into module M, and should be visible whenever M is visible.
Definition at line 1060 of file ASTContext.cpp.
References clang::cast(), getASTMutationListener(), clang::Decl::getCanonicalDecl(), Listener, and clang::ASTMutationListener::RedefinedHiddenDefinition().
Referenced by clang::Sema::makeMergedDefinitionVisible(), and clang::ASTDeclReader::UpdateDecl().
mergeExceptionSpecs()
FunctionProtoType::ExceptionSpecInfo ASTContext::mergeExceptionSpecs (FunctionProtoType::ExceptionSpecInfo ESI1, FunctionProtoType::ExceptionSpecInfo ESI2, SmallVectorImpl< QualType > & ExceptionTypeStorage, bool AcceptDependent)
Definition at line 12609 of file ASTContext.cpp.
References clang::EST_BasicNoexcept, clang::EST_DependentNoexcept, clang::EST_Dynamic, clang::EST_DynamicNone, clang::EST_MSAny, clang::EST_NoexceptFalse, clang::EST_NoexceptTrue, clang::EST_None, clang::EST_NoThrow, clang::EST_Unevaluated, clang::EST_Uninstantiated, clang::EST_Unparsed, clang::FunctionProtoType::ExceptionSpecInfo::Exceptions, mergeTypeLists(), clang::Result, and clang::FunctionProtoType::ExceptionSpecInfo::Type.
Referenced by clang::Sema::FindCompositePointerType(), and getCommonNonSugarTypeNode().
mergeExtParameterInfo()
bool ASTContext::mergeExtParameterInfo (const FunctionProtoType * FirstFnType, const FunctionProtoType * SecondFnType, bool & CanUseFirst, bool & CanUseSecond, SmallVectorImpl< FunctionProtoType::ExtParameterInfo > & NewParamInfos)
This function merges the ExtParameterInfo lists of two functions.
It returns true if the lists are compatible. The merged list is returned in NewParamInfos.
Parameters
FirstFnType The type of the first function.
SecondFnType The type of the second function.
CanUseFirst This flag is set to true if the first function's ExtParameterInfo list can be used as the composite list of ExtParameterInfo.
CanUseSecond This flag is set to true if the second function's ExtParameterInfo list can be used as the composite list of ExtParameterInfo.
NewParamInfos The composite list of ExtParameterInfo. The list is empty if none of the flags are set.
Definition at line 10905 of file ASTContext.cpp.
References clang::FunctionProtoType::getExtParameterInfo(), clang::FunctionProtoType::getExtParameterInfos(), clang::FunctionProtoType::hasExtParameterInfos(), clang::FunctionType::ExtParameterInfo::isNoEscape(), and clang::FunctionType::ExtParameterInfo::withIsNoEscape().
Referenced by clang::Sema::IsBlockPointerConversion(), clang::Sema::IsFunctionConversion(), and mergeFunctionTypes().
mergeFunctionParameterTypes()
QualType ASTContext::mergeFunctionParameterTypes (QualType lhs, QualType rhs, bool OfBlockPointer = false, bool Unqualified = false)
mergeFunctionParameterTypes - merge two types which appear as function parameter types
Definition at line 10305 of file ASTContext.cpp.
References clang::QualType::isNull(), mergeTransparentUnionType(), mergeTypes(), and clang::Unqualified.
Referenced by mergeFunctionTypes().
mergeFunctionTypes()
QualType ASTContext::mergeFunctionTypes (QualType lhs, QualType rhs, bool OfBlockPointer = false, bool Unqualified = false, bool AllowCXX = false, bool IsConditionalOperator = false)
Definition at line 10324 of file ASTContext.cpp.
References clang::Type::castAs(), Enum, clang::FunctionProtoType::ExtProtoInfo::ExtInfo, clang::FunctionProtoType::ExtProtoInfo::ExtParameterInfos, FloatTy, clang::Type::getAs(), getCanonicalType(), clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::getExtInfo(), clang::FunctionProtoType::getExtProtoInfo(), getFunctionNoProtoType(), getFunctionType(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::ExtInfo::getNoCallerSavedRegs(), clang::FunctionType::ExtInfo::getNoCfCheck(), clang::FunctionType::ExtInfo::getNoReturn(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::getParamType(), clang::FunctionProtoType::getParamTypes(), clang::FunctionType::ExtInfo::getProducesResult(), clang::FunctionType::ExtInfo::getRegParm(), clang::FunctionType::getReturnType(), clang::CanQual< typename >::getUnqualifiedType(), clang::QualType::getUnqualifiedType(), clang::FunctionProtoType::hasExceptionSpec(), clang::QualType::hasQualifiers(), clang::QualType::isNull(), isPromotableIntegerType(), clang::FunctionProtoType::isVariadic(), mergeExtParameterInfo(), mergeFunctionParameterTypes(), mergeTypes(), clang::Unqualified, and clang::FunctionType::ExtInfo::withNoReturn().
Referenced by clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::checkOpenMPDeclareVariantFunction(), instantiateOMPDeclareVariantAttr(), and mergeTypes().
mergeObjCGCQualifiers()
QualType ASTContext::mergeObjCGCQualifiers (QualType LHS, QualType RHS)
mergeObjCGCQualifiers - This routine merges ObjC's GC attribute of 'LHS' and 'RHS' attributes and returns the merged version; including for function return types.
Definition at line 10959 of file ASTContext.cpp.
References clang::cast(), clang::Type::castAs(), clang::FunctionProtoType::ExtProtoInfo::ExtInfo, clang::Qualifiers::getAddressSpace(), getCanonicalType(), clang::Qualifiers::getCVRQualifiers(), clang::getFunctionExtInfo(), getFunctionType(), clang::QualType::getLocalQualifiers(), clang::Qualifiers::getObjCGCAttr(), clang::QualType::getTypePtr(), clang::Type::isFunctionType(), clang::QualType::isNull(), clang::Type::isObjCObjectPointerType(), mergeObjCGCQualifiers(), clang::Qualifiers::Strong, and clang::Qualifiers::Weak.
Referenced by clang::Sema::MergeFunctionDecl(), mergeObjCGCQualifiers(), and clang::Sema::MergeVarDeclTypes().
mergeTransparentUnionType()
QualType ASTContext::mergeTransparentUnionType (QualType T, QualType SubType, bool OfBlockPointer = false, bool Unqualified = false)
mergeTransparentUnionType - if T is a transparent union type and a member of T is compatible with SubType, return the merged type, else return QualType()
Definition at line 10285 of file ASTContext.cpp.
References clang::RecordDecl::fields(), clang::Decl::hasAttr(), clang::QualType::isNull(), mergeTypes(), and clang::Unqualified.
Referenced by mergeFunctionParameterTypes().
mergeTypes()
QualType ASTContext::mergeTypes (QualType LHS, QualType RHS, bool OfBlockPointer = false, bool Unqualified = false, bool BlockReturnType = false, bool IsConditionalOperator = false)
Definition at line 10543 of file ASTContext.cpp.
References areCompatMatrixTypes(), areCompatVectorTypes(), canAssignObjCInterfaces(), canAssignObjCInterfacesInBlockPointer(), clang::Type::castAs(), clang::Qualifiers::getAddressSpace(), clang::Type::getAs(), getAsArrayType(), getAsConstantArrayType(), clang::Qualifiers::getAsOpaqueValue(), getAsVariableArrayType(), getAtomicType(), getBlockPointerType(), getCanonicalType(), getConstantArrayType(), clang::Qualifiers::getCVRQualifiers(), clang::ArrayType::getElementType(), getIncompleteArrayType(), clang::Expr::getIntegerConstantExpr(), getLangOpts(), clang::QualType::getLocalQualifiers(), clang::Qualifiers::getObjCGCAttr(), getObjCGCQualType(), clang::Qualifiers::getObjCLifetime(), clang::ReferenceType::getPointeeType(), getPointerType(), clang::QualType::getQualifiers(), clang::ConstantArrayType::getSize(), clang::ConstantArrayType::getSizeExpr(), clang::VariableArrayType::getSizeExpr(), clang::Type::getTypeClass(), clang::QualType::getTypePtr(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasUnaligned(), clang::Qualifiers::isAddressSpaceSupersetOf(), clang::Type::isBlockPointerType(), clang::QualType::isNull(), clang::Type::isObjCIdType(), clang::Type::isObjCObjectPointerType(), mergeEnumWithInteger(), mergeFunctionTypes(), mergeTypes(), clang::OpenCL, clang::Qualifiers::removeAddressSpace(), clang::Qualifiers::Strong, clang::Unqualified, and clang::Qualifiers::Weak.
Referenced by checkConditionalPointerCompatibility(), clang::Sema::MergeCompatibleFunctionDecls(), clang::Sema::MergeFunctionDecl(), mergeFunctionParameterTypes(), mergeFunctionTypes(), mergeTransparentUnionType(), mergeTypes(), clang::Sema::MergeVarDeclTypes(), typesAreBlockPointerCompatible(), and typesAreCompatible().
ObjCMethodsAreEqual()
bool ASTContext::ObjCMethodsAreEqual (const ObjCMethodDecl * MethodDecl, const ObjCMethodDecl * MethodImp)
Definition at line 12338 of file ASTContext.cpp.
References clang::ObjCMethodDecl::getObjCDeclQualifier(), clang::ParmVarDecl::getObjCDeclQualifier(), clang::ObjCMethodDecl::getReturnType(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), hasSameType(), clang::ObjCMethodDecl::isVariadic(), clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), and clang::ObjCMethodDecl::param_size().
Referenced by ClassImplementsAllMethodsAndProperties().
ObjCObjectAdoptsQTypeProtocols()
bool ASTContext::ObjCObjectAdoptsQTypeProtocols (QualType QT, ObjCInterfaceDecl * Decl)
ObjCObjectAdoptsQTypeProtocols - Checks that protocols in IC's protocol list adopt all protocols in QT's qualified-id protocol list.
Definition at line 5525 of file ASTContext.cpp.
References clang::ObjCInterfaceDecl::ClassImplementsProtocol(), clang::Type::getAs(), and clang::Type::isObjCQualifiedIdType().
Referenced by CheckObjCBridgeNSCast().
ObjCQualifiedClassTypesAreCompatible()
bool ASTContext::ObjCQualifiedClassTypesAreCompatible (const ObjCObjectPointerType * LHS, const ObjCObjectPointerType * RHS)
ObjCQualifiedClassTypesAreCompatible - compare Class<pr,...> and Class<pr1, ...>.
Definition at line 9679 of file ASTContext.cpp.
References clang::ast_matchers::match(), ProtocolCompatibleWithProtocol(), and clang::ObjCObjectPointerType::quals().
Referenced by canAssignObjCInterfaces().
ObjCQualifiedIdTypesAreCompatible()
bool ASTContext::ObjCQualifiedIdTypesAreCompatible (const ObjCObjectPointerType * LHS, const ObjCObjectPointerType * RHS, bool ForCompare)
ObjCQualifiedIdTypesAreCompatible - We know that one of lhs/rhs is an ObjCQualifiedIDType.
Definition at line 9697 of file ASTContext.cpp.
References CollectInheritedProtocols(), compare(), clang::ObjCObjectPointerType::getInterfaceDecl(), clang::ObjCObjectPointerType::getInterfaceType(), clang::ObjCObjectPointerType::isObjCClassType(), clang::ObjCObjectPointerType::isObjCIdType(), clang::ObjCObjectPointerType::isObjCQualifiedClassType(), clang::ObjCObjectPointerType::isObjCQualifiedIdType(), clang::ast_matchers::match(), ProtocolCompatibleWithProtocol(), clang::ObjCObjectPointerType::qual_empty(), and clang::ObjCObjectPointerType::quals().
Referenced by canAssignObjCInterfaces(), canAssignObjCInterfacesInBlockPointer(), clang::Sema::FindCompositeObjCPointerType(), and isObjCTypeSubstitutable().
operator=()
ASTContext & clang::ASTContext::operator= (const ASTContext &) delete
overridden_methods()
ASTContext::overridden_method_range ASTContext::overridden_methods (const CXXMethodDecl * Method) const
Definition at line 1594 of file ASTContext.cpp.
Referenced by clang::CXXMethodDecl::overridden_methods(), overridden_methods_begin(), overridden_methods_end(), and overridden_methods_size().
overridden_methods_begin()
ASTContext::overridden_cxx_method_iterator ASTContext::overridden_methods_begin (const CXXMethodDecl * Method) const
Definition at line 1578 of file ASTContext.cpp.
References overridden_methods().
Referenced by clang::CXXMethodDecl::begin_overridden_methods(), and getOverriddenMethods().
overridden_methods_end()
ASTContext::overridden_cxx_method_iterator ASTContext::overridden_methods_end (const CXXMethodDecl * Method) const
Definition at line 1583 of file ASTContext.cpp.
References overridden_methods().
Referenced by clang::CXXMethodDecl::end_overridden_methods(), and getOverriddenMethods().
overridden_methods_size()
unsigned ASTContext::overridden_methods_size (const CXXMethodDecl * Method) const
Definition at line 1588 of file ASTContext.cpp.
References overridden_methods().
Referenced by clang::CXXMethodDecl::size_overridden_methods().
PrintStats()
void ASTContext::PrintStats () const
Definition at line 999 of file ASTContext.cpp.
References clang::CPlusPlus, ExternalSource, getLangOpts(), NumImplicitCopyAssignmentOperators, NumImplicitCopyAssignmentOperatorsDeclared, NumImplicitCopyConstructors, NumImplicitCopyConstructorsDeclared, NumImplicitDefaultConstructors, NumImplicitDefaultConstructorsDeclared, NumImplicitDestructors, NumImplicitDestructorsDeclared, NumImplicitMoveAssignmentOperators, NumImplicitMoveAssignmentOperatorsDeclared, NumImplicitMoveConstructors, and NumImplicitMoveConstructorsDeclared.
Referenced by clang::ParseAST().
propertyTypesAreCompatible()
bool ASTContext::propertyTypesAreCompatible (QualType LHS, QualType RHS)
Definition at line 10274 of file ASTContext.cpp.
References typesAreCompatible().
Referenced by clang::Sema::DiagnosePropertyMismatch(), and SelectPropertyForSynthesisFromProtocols().
ProtocolCompatibleWithProtocol()
bool ASTContext::ProtocolCompatibleWithProtocol (ObjCProtocolDecl * lProto, ObjCProtocolDecl * rProto) const
ProtocolCompatibleWithProtocol - return 'true' if 'lProto' is in the inheritance hierarchy of 'rProto'.
Definition at line 9667 of file ASTContext.cpp.
References clang::declaresSameEntity(), ProtocolCompatibleWithProtocol(), and clang::ObjCProtocolDecl::protocols().
Referenced by ObjCQualifiedClassTypesAreCompatible(), ObjCQualifiedIdTypesAreCompatible(), ProtocolCompatibleWithProtocol(), and QIdProtocolsAdoptObjCObjectProtocols().
QIdProtocolsAdoptObjCObjectProtocols()
bool ASTContext::QIdProtocolsAdoptObjCObjectProtocols (QualType QT, ObjCInterfaceDecl * IDecl)
QIdProtocolsAdoptObjCObjectProtocols - Checks that protocols in QT's qualified-id protocol list adopt all protocols in IDecl's list of protocols.
Definition at line 5544 of file ASTContext.cpp.
References CollectInheritedProtocols(), clang::Type::getAs(), clang::ObjCInterfaceDecl::hasDefinition(), clang::Type::isObjCQualifiedIdType(), and ProtocolCompatibleWithProtocol().
Referenced by CheckObjCBridgeCFCast().
removeAddrSpaceQualType()
QualType ASTContext::removeAddrSpaceQualType (QualType T) const
Remove any existing address space on the type and returns the type with qualifiers intact (or that's the idea anyway)
The return type should be T with all prior qualifiers minus the address space.
Definition at line 3089 of file ASTContext.cpp.
References clang::Qualifiers::getFastQualifiers(), clang::Qualifiers::hasNonFastQualifiers(), clang::Qualifiers::removeAddressSpace(), and clang::QualifierCollector::strip().
Referenced by DeduceTemplateArgumentsByTypeMatch(), handleMSPointerTypeQualifierAttr(), HandleWebAssemblyFuncrefAttr(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectMemberConversion(), removePtrSizeAddrSpace(), and TryAddressSpaceCast().
removePtrSizeAddrSpace()
QualType ASTContext::removePtrSizeAddrSpace (QualType T) const
Remove the existing address space on the type if it is a pointer size address space and return the type with qualifiers intact.
Definition at line 3151 of file ASTContext.cpp.
References clang::QualType::getAddressSpace(), clang::Type::getAs(), clang::Type::getPointeeType(), getPointerType(), clang::isPtrSizeAddressSpace(), and removeAddrSpaceQualType().
Referenced by clang::Sema::FunctionParamTypesAreEqual(), and getFunctionTypeWithoutPtrSizes().
ResetObjCLayout()
void ASTContext::ResetObjCLayout (const ObjCContainerDecl * CD)
Definition at line 10952 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnFields().
setASTMutationListener()
void clang::ASTContext::setASTMutationListener (ASTMutationListener * Listener) inline
Attach an AST mutation listener to the AST context.
The AST mutation listener provides the ability to track modifications to the abstract syntax tree entities committed after they were initially created.
Definition at line 1175 of file ASTContext.h.
References Listener.
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::CompilerInstance::createASTReader().
setBlockVarCopyInit()
void ASTContext::setBlockVarCopyInit (const VarDecl * VD, Expr * CopyExpr, bool CanThrow)
Set the copy initialization expression of a block var decl.
CanThrow indicates whether the copy expression can throw or not.
Definition at line 2983 of file ASTContext.cpp.
References CanThrow(), and clang::Decl::hasAttr().
Referenced by checkEscapingByref(), and clang::ASTDeclReader::VisitVarDeclImpl().
setBOOLDecl()
void clang::ASTContext::setBOOLDecl (TypedefDecl * TD) inline
Save declaration of 'BOOL' typedef.
Definition at line 2065 of file ASTContext.h.
Referenced by clang::Sema::ActOnObjCBoolLiteral().
setCFConstantStringType()
void ASTContext::setCFConstantStringType (QualType T)
Definition at line 7408 of file ASTContext.cpp.
References clang::cast(), and clang::Type::castAs().
Referenced by clang::ASTReader::InitializeContext().
setcudaConfigureCallDecl()
void clang::ASTContext::setcudaConfigureCallDecl (FunctionDecl * FD) inline
Definition at line 1388 of file ASTContext.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), and clang::ASTReader::InitializeContext().
setCurrentNamedModule()
void ASTContext::setCurrentNamedModule (Module * M)
Set the (C++20) module we are building.
Definition at line 1152 of file ASTContext.cpp.
References clang::Module::isModulePurview().
Referenced by clang::Sema::ActOnModuleDecl().
setExternalSource()
void ASTContext::setExternalSource (IntrusiveRefCntPtr< ExternalASTSource > Source)
Attach an external AST source to the AST context.
The external AST source provides the ability to load parts of the abstract syntax tree as needed from some external storage, e.g., a precompiled header.
Definition at line 995 of file ASTContext.cpp.
References ExternalSource.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::CompilerInstance::createASTReader(), and clang::CompilerInstance::createPCHExternalASTSource().
setFILEDecl()
void clang::ASTContext::setFILEDecl (TypeDecl * FILEDecl) inline
Set the type for the C FILE type.
Definition at line 1919 of file ASTContext.h.
Referenced by clang::Sema::ActOnTag(), clang::Sema::ActOnTypedefNameDecl(), and clang::ASTReader::InitializeContext().
setInstantiatedFromStaticDataMember()
void ASTContext::setInstantiatedFromStaticDataMember (VarDecl * Inst, VarDecl * Tmpl, TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation = SourceLocation())
Note that the static data member Inst is an instantiation of the static data member template Tmpl of a class template.
Definition at line 1504 of file ASTContext.cpp.
References clang::VarDecl::isStaticDataMember(), and setTemplateOrSpecializationInfo().
Referenced by clang::VarDecl::setInstantiationOfStaticDataMember(), and clang::ASTDeclReader::VisitVarDeclImpl().
setInstantiatedFromUnnamedFieldDecl()
void ASTContext::setInstantiatedFromUnnamedFieldDecl (FieldDecl * Inst, FieldDecl * Tmpl)
Definition at line 1567 of file ASTContext.cpp.
References clang::NamedDecl::getDeclName().
Referenced by clang::ASTDeclReader::VisitFieldDecl().
setInstantiatedFromUsingDecl()
void ASTContext::setInstantiatedFromUsingDecl (NamedDecl * Inst, NamedDecl * Pattern)
Remember that the using decl Inst is an instantiation of the using decl Pattern of a class template.
Definition at line 1527 of file ASTContext.cpp.
Referenced by clang::ASTDeclReader::VisitUsingDecl(), and clang::ASTNodeImporter::VisitUsingDecl().
setInstantiatedFromUsingEnumDecl()
void ASTContext::setInstantiatedFromUsingEnumDecl (UsingEnumDecl * Inst, UsingEnumDecl * Pattern)
Remember that the using enum decl Inst is an instantiation of the using enum decl Pattern of a class template.
Definition at line 1545 of file ASTContext.cpp.
Referenced by clang::ASTDeclReader::VisitUsingEnumDecl(), and clang::ASTNodeImporter::VisitUsingEnumDecl().
setInstantiatedFromUsingShadowDecl()
void ASTContext::setInstantiatedFromUsingShadowDecl (UsingShadowDecl * Inst, UsingShadowDecl * Pattern)
Definition at line 1557 of file ASTContext.cpp.
Referenced by clang::TemplateDeclInstantiator::VisitBaseUsingDecls(), clang::ASTDeclReader::VisitUsingShadowDecl(), and clang::ASTNodeImporter::VisitUsingShadowDecl().
setjmp_bufDecl()
void clang::ASTContext::setjmp_bufDecl (TypeDecl * jmp_bufDecl) inline
Set the type for the C jmp_buf type.
Definition at line 1929 of file ASTContext.h.
Referenced by clang::Sema::ActOnTypedefNameDecl(), and clang::ASTReader::InitializeContext().
setManglingNumber()
void ASTContext::setManglingNumber (const NamedDecl * ND, unsigned Number)
Definition at line 12142 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildVariableInstantiation(), clang::Sema::handleTagNumbering(), clang::TemplateDeclInstantiator::InitFunctionInstantiation(), and clang::ASTDeclReader::UpdateDecl().
setNonKeyFunction()
void ASTContext::setNonKeyFunction (const CXXMethodDecl * method)
Observe that the given method cannot be a key function.
Checks the key-function cache for the method's class and clears it if matches the given declaration.
This is used in ABIs where out-of-line definitions marked inline are not considered to be key functions.
Parameters
method should be the declaration from the class definition
Definition at line 3399 of file RecordLayoutBuilder.cpp.
References clang::LazyOffsetPtr< T, OffsT, Get >::get().
Referenced by clang::Sema::ActOnFinishFunctionBody().
setObjCClassRedefinitionType()
void clang::ASTContext::setObjCClassRedefinitionType (QualType RedefType) inline
Set the user-written type that redefines 'SEL'.
Definition at line 1850 of file ASTContext.h.
Referenced by clang::Sema::MergeTypedefNameDecl().
setObjCConstantStringInterface()
void ASTContext::setObjCConstantStringInterface (ObjCInterfaceDecl * Decl)
Definition at line 9177 of file ASTContext.cpp.
References getObjCInterfaceType(), and clang::QualType::isNull().
Referenced by clang::Sema::BuildObjCStringLiteral().
setObjCIdRedefinitionType()
void clang::ASTContext::setObjCIdRedefinitionType (QualType RedefType) inline
Set the user-written type that redefines id.
Definition at line 1837 of file ASTContext.h.
Referenced by clang::Sema::MergeTypedefNameDecl().
setObjCImplementation() [1/2]
void ASTContext::setObjCImplementation (ObjCCategoryDecl * CatD, ObjCCategoryImplDecl * ImplD)
Set the implementation of ObjCCategoryDecl.
Definition at line 2941 of file ASTContext.cpp.
setObjCImplementation() [2/2]
void ASTContext::setObjCImplementation (ObjCInterfaceDecl * IFaceD, ObjCImplementationDecl * ImplD)
Set the implementation of ObjCInterfaceDecl.
Definition at line 2934 of file ASTContext.cpp.
Referenced by clang::ObjCImplDecl::setClassInterface(), clang::ObjCCategoryDecl::setImplementation(), and clang::ObjCInterfaceDecl::setImplementation().
setObjCMethodRedeclaration()
void ASTContext::setObjCMethodRedeclaration (const ObjCMethodDecl * MD, const ObjCMethodDecl * Redecl)
Definition at line 2952 of file ASTContext.cpp.
References getObjCMethodRedeclaration().
Referenced by clang::ObjCMethodDecl::setAsRedeclaration(), and clang::ASTDeclReader::VisitObjCMethodDecl().
setObjCNSStringType()
void clang::ASTContext::setObjCNSStringType (QualType T) inline
Definition at line 1824 of file ASTContext.h.
Referenced by clang::Sema::BuildObjCStringLiteral().
setObjCSelRedefinitionType()
void clang::ASTContext::setObjCSelRedefinitionType (QualType RedefType) inline
Set the user-written type that redefines 'SEL'.
Definition at line 1863 of file ASTContext.h.
Referenced by clang::Sema::MergeTypedefNameDecl().
setObjCSuperType()
void clang::ASTContext::setObjCSuperType (QualType ST) inline
Definition at line 1801 of file ASTContext.h.
Referenced by LookupPredefedObjCSuperType().
setParameterIndex()
void ASTContext::setParameterIndex (const ParmVarDecl * D, unsigned index)
Used by ParmVarDecl to store on the side the index of the parameter when it exceeds the size of the normal bitfield.
Definition at line 12228 of file ASTContext.cpp.
setPrimaryMergedDecl()
void clang::ASTContext::setPrimaryMergedDecl (Decl * D, Decl * Primary) inline
Definition at line 1025 of file ASTContext.h.
Referenced by clang::Sema::CheckConceptRedefinition(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::VisitMSGuidDecl(), clang::ASTDeclReader::VisitTemplateParamObjectDecl(), and clang::ASTDeclReader::VisitUnnamedGlobalConstantDecl().
setPrintingPolicy()
void clang::ASTContext::setPrintingPolicy (const clang::PrintingPolicy & Policy) inline
Definition at line 687 of file ASTContext.h.
Referenced by clang::ExtractAPIAction::CreateASTConsumer(), clang::WrappingExtractAPIAction::CreateASTConsumer(), and clang::Sema::EmitCurrentDiagnostic().
setsigjmp_bufDecl()
void clang::ASTContext::setsigjmp_bufDecl (TypeDecl * sigjmp_bufDecl) inline
Set the type for the C sigjmp_buf type.
Definition at line 1941 of file ASTContext.h.
Referenced by clang::Sema::ActOnTypedefNameDecl(), and clang::ASTReader::InitializeContext().
setStaticLocalNumber()
void ASTContext::setStaticLocalNumber (const VarDecl * VD, unsigned Number)
Definition at line 12162 of file ASTContext.cpp.
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::Sema::BuildAnonymousStructOrUnion(), clang::Sema::BuildVariableInstantiation(), and clang::ASTDeclReader::UpdateDecl().
setTemplateOrSpecializationInfo()
void ASTContext::setTemplateOrSpecializationInfo (VarDecl * Inst, TemplateOrSpecializationInfo TSI)
Definition at line 1514 of file ASTContext.cpp.
Referenced by clang::VarDecl::setDescribedVarTemplate(), and setInstantiatedFromStaticDataMember().
setTraversalScope()
void ASTContext::setTraversalScope (const std::vector< Decl * > & TopLevelDecls)
Definition at line 985 of file ASTContext.cpp.
References clang::ParentMapContext::clear(), and getParentMapContext().
setucontext_tDecl()
void clang::ASTContext::setucontext_tDecl (TypeDecl * ucontext_tDecl) inline
Set the type for the C ucontext_t type.
Definition at line 1953 of file ASTContext.h.
Referenced by clang::Sema::ActOnTypedefNameDecl(), and clang::ASTReader::InitializeContext().
shouldExternalize()
bool ASTContext::shouldExternalize (const Decl * D) const
Whether a C++ static variable or CUDA/HIP kernel should be externalized.
Definition at line 13596 of file ASTContext.cpp.
References CUDADeviceVarODRUsedByHost, clang::Decl::hasAttr(), and mayExternalize().
Referenced by adjustGVALinkageForAttributes(), and getMangledNameImpl().
toBits()
int64_t ASTContext::toBits (CharUnits CharSize) const
Convert a size in characters to a size in bits.
toBits - Convert a size in characters to a size in characters.
Definition at line 2467 of file ASTContext.cpp.
References getCharWidth(), and clang::CharUnits::getQuantity().
Referenced by AddDirectArgument(), AtomicUsesUnsupportedLibcall(), BitsContainNoUserData(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), emitOMPAtomicRMW(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), clang::CodeGen::swiftcall::SwiftAggLowering::finish(), getDeclAlign(), getPreferredTypeAlign(), getSubobjectOffset(), getSubobjectSizeInBits(), getTypeUnadjustedAlign(), isVarDeclStrongDefinition(), and shuffleAndStore().
toCharUnitsFromBits()
CharUnits ASTContext::toCharUnitsFromBits (int64_t BitSize) const
Convert a size in bits to a size in characters.
toCharUnitsFromBits - Convert a size in bits to a size in characters.
Definition at line 2462 of file ASTContext.cpp.
References clang::CharUnits::fromQuantity(), and getCharWidth().
Referenced by clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignedAttr(), clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), AlignOfType(), clang::Sema::CheckAlignasUnderalignment(), clang::Sema::CheckThreadLocalForLargeAlignment(), emitAddrOfZeroSizeField(), emitAlignedClause(), EmitAtomicCmpXchg128ForMSIntrin(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockDeclRefVariable(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), GetAlignedMapping(), getAlignOfGlobalVarInChars(), GetAlignOfType(), getDeclAlign(), getExnObjectAlignment(), clang::VarDecl::getFlexibleArrayInitChars(), clang::CodeGen::swiftcall::getMaximumVoluntaryIntegerSize(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), GetNumNonZeroBytesInInit(), getPreferredTypeAlignInChars(), clang::CodeGen::CodeGenModule::GetTargetTypeStoreSize(), getTypeAlignInChars(), getTypeAlignInChars(), getTypeInfoInChars(), getTypeUnadjustedAlignInChars(), getTypeUnadjustedAlignInChars(), HandleLValueMember(), clang::Sema::LookupInlineAsmField(), mergeAlignedAttrs(), and clang::Sema::RefersToMemberWithReducedAlignment().
typesAreBlockPointerCompatible()
bool ASTContext::typesAreBlockPointerCompatible (QualType LHS, QualType RHS)
Definition at line 10278 of file ASTContext.cpp.
References clang::QualType::isNull(), and mergeTypes().
Referenced by canAssignObjCObjectTypes(), and checkBlockPointerTypesForAssignment().
typesAreCompatible()
bool ASTContext::typesAreCompatible (QualType LHS, QualType RHS, bool CompareUnqualified = false)
Compatibility predicates used to check assignment expressions.
typesAreCompatible - C99 6.7.3p9: For two qualified types to be compatible, both shall have the identically qualified version of a compatible type.
C99 6.2.7p1: Two types have compatible types if their types are the same. See 6.7.[2,3,5] for additional rules.
Definition at line 10266 of file ASTContext.cpp.
References clang::CPlusPlus, getLangOpts(), hasSameType(), clang::QualType::isNull(), and mergeTypes().
Referenced by clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckObjCMethodOverrides(), checkObjCPointerTypesForAssignment(), checkPointerTypesForAssignment(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CreateGenericSelectionExpr(), EvaluateBinaryTypeTrait(), clang::Sema::ImplicitlyDefineFunction(), clang::Sema::isObjCWritebackConversion(), clang::Sema::IsPointerConversion(), IsStandardConversion(), IsStringInit(), clang::Sema::IsStringLiteralToNonConstPointerConversion(), IsWideCharCompatible(), clang::Sema::MergeFunctionDecl(), propertyTypesAreCompatible(), and clang::Sema::tryCaptureOpenMPLambdas().
UnwrapSimilarArrayTypes()
void ASTContext::UnwrapSimilarArrayTypes (QualType & T1, QualType & T2, bool AllowPiMismatch = true)
Attempt to unwrap two types that may both be array types with the same bound (or both be array types of unknown bound) for the purpose of comparing the cv-decomposition of two types per C++ [conv.qual].
Parameters
AllowPiMismatch Allow the Pi1 and Pi2 to differ as described in C++20 [conv.qual], if permitted by the current language mode.
Definition at line 6097 of file ASTContext.cpp.
References clang::CPlusPlus20, getAsArrayType(), and getLangOpts().
Referenced by unwrapCastAwayConstnessLevel(), and UnwrapSimilarTypes().
UnwrapSimilarTypes()
bool ASTContext::UnwrapSimilarTypes (QualType & T1, QualType & T2, bool AllowPiMismatch = true)
Attempt to unwrap two types that may be similar (C++ [conv.qual]).
If T1 and T2 are both pointer types of the same kind, or both array types with the same bound, unwraps layers from T1 and T2 until a pointer type is unwrapped. Top-level qualifiers on T1 and T2 are ignored.
This function will typically be called in a loop that successively "unwraps" pointer and pointer-to-member types to compare them at each level.
Parameters
AllowPiMismatch Allow the Pi1 and Pi2 to differ as described in C++20 [conv.qual], if permitted by the current language mode.
Returns
true if a pointer type was unwrapped, false if we reached a pair of types that can't be unwrapped further.
Definition at line 6148 of file ASTContext.cpp.
References clang::Type::getAs(), clang::MemberPointerType::getClass(), getLangOpts(), clang::MemberPointerType::getPointeeType(), clang::ObjCObjectPointerType::getPointeeType(), clang::PointerType::getPointeeType(), clang::Type::getPointeeType(), hasSameUnqualifiedType(), clang::ObjC, and UnwrapSimilarArrayTypes().
Referenced by clang::Sema::CompareReferenceRelationship(), hasCvrSimilarType(), hasSimilarType(), clang::Sema::IsQualificationConversion(), shouldBeModeledWithNoOp(), and unwrapCastAwayConstnessLevel().
Friends And Related Symbol Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 465 of file ASTContext.h.
ASTReader
friend class ASTReader friend
Definition at line 466 of file ASTContext.h.
ASTWriter
friend class ASTWriter friend
Definition at line 467 of file ASTContext.h.
CXXRecordDecl
friend class CXXRecordDecl friend
Definition at line 469 of file ASTContext.h.
DeclarationNameTable
friend class DeclarationNameTable friend
Definition at line 3293 of file ASTContext.h.
DeclContext
friend class DeclContext friend
Definition at line 3294 of file ASTContext.h.
IncrementalParser
friend class IncrementalParser friend
Definition at line 470 of file ASTContext.h.
NestedNameSpecifier
friend class NestedNameSpecifier friend
Definition at line 183 of file ASTContext.h.
serialization::AbstractTypeReader
template<class > friend class serialization::AbstractTypeReader friend
Definition at line 468 of file ASTContext.h.
Member Data Documentation
AccumTy
CanQualType clang::ASTContext::AccumTy
Definition at line 1090 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
ARCUnbridgedCastTy
CanQualType clang::ASTContext::ARCUnbridgedCastTy
Definition at line 1107 of file ASTContext.h.
Referenced by clang::Sema::GatherArgumentsForCall(), clang::ASTReader::GetType(), and InitBuiltinTypes().
AutoDeductTy
QualType clang::ASTContext::AutoDeductTy mutable
Definition at line 1133 of file ASTContext.h.
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison(), and getAutoDeductType().
AutoRRefDeductTy
QualType clang::ASTContext::AutoRRefDeductTy mutable
Definition at line 1134 of file ASTContext.h.
Referenced by getAutoRRefDeductType().
BFloat16Ty
CanQualType clang::ASTContext::BFloat16Ty
Definition at line 1102 of file ASTContext.h.
Referenced by ConvertDeclSpecToType(), DecodeTypeFromStr(), getBuiltinVectorTypeInfo(), getNeonEltType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
BoolTy
CanQualType clang::ASTContext::BoolTy
Definition at line 1078 of file ASTContext.h.
Referenced by clang::Sema::ActOnCXXBoolLiteral(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnObjCAvailabilityCheckExpr(), clang::Sema::ActOnObjCBoolLiteral(), clang::Sema::AddBuiltinCandidate(), clang::TemplateDeclInstantiator::adjustForRewrite(), clang::ento::SimpleConstraintManager::assumeInternal(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCXXNoexceptExpr(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildResolvedCallExpr(), buildSingleCopyAssignRecursively(), clang::Sema::CheckAssignmentConstraints(), CheckBoolLikeConversion(), clang::Sema::CheckConstraintExpression(), clang::Sema::checkExceptionSpecification(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckPointerConversion(), ConvertDeclSpecToType(), clang::Sema::CreateBuiltinUnaryOp(), DecodeTypeFromStr(), DeduceTemplateArgumentsByTypeMatch(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), emitStructGetterCall(), emitStructSetterCall(), clang::PreferredTypeBuilder::enterCondition(), clang::ento::SMTConv::fixAPSInt(), clang::ento::SMTConv::getBinExpr(), getBuiltinVectorTypeInfo(), clang::ento::SValBuilder::getConditionType(), getLogicalOperationType(), getPreferredTypeOfBinaryRHS(), getPreferredTypeOfUnaryArg(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), InitBuiltinTypes(), IsStandardConversion(), mapCodeCompletionContext(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformImplicitConversion(), clang::Sema::PreferredConditionType(), RVVType2Qual(), SemaBuiltinAlignment(), TryContextuallyConvertToBool(), and clang::Sema::tryResolveExplicitSpecifier().
BoundMemberTy
CanQualType clang::ASTContext::BoundMemberTy
Definition at line 1105 of file ASTContext.h.
Referenced by clang::Sema::ActOnOpenMPCall(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::FixOverloadedFunctionReference(), clang::ASTReader::GetType(), clang::Sema::getVariadicCallType(), InitBuiltinTypes(), clang::Sema::MaybeBindToTemporary(), and clang::Sema::tryExprAsCall().
BuiltinFnTy
CanQualType clang::ASTContext::BuiltinFnTy
Definition at line 1106 of file ASTContext.h.
Referenced by clang::Sema::BuildDeclarationNameExpr(), buildMemcpyForAssignmentOp(), clang::Sema::FixOverloadedFunctionReference(), clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::TreeTransform< Derived >::RebuildShuffleVectorExpr().
BuiltinInfo
Builtin::Context& clang::ASTContext::BuiltinInfo
Definition at line 632 of file ASTContext.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::AddKnownFunctionAttributes(), ArmSmeAliasValid(), ArmSveAliasValid(), clang::Sema::BuildBuiltinCallExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildResolvedCallExpr(), canBuiltinBeRedeclared(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::ConvertArgumentsForCall(), EmitDirectCallee(), emitReplacement(), clang::Sema::FixOverloadedFunctionReference(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenModule::getBuiltinLibFunction(), GetBuiltinType(), clang::ento::CheckerContext::isCLibraryFunction(), clang::CallExpr::isUnevaluatedBuiltinCall(), clang::Sema::LazilyCreateBuiltin(), clang::Sema::LookupBuiltin(), clang::Sema::MergeFunctionDecl(), and rewriteBuiltinFunctionDecl().
Char16Ty
CanQualType clang::ASTContext::Char16Ty
Definition at line 1084 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnStringLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::CheckLiteralOperatorDeclaration(), ConvertDeclSpecToType(), clang::ASTReader::GetType(), InitBuiltinTypes(), IsStringInit(), and IsWideCharCompatible().
Char32Ty
CanQualType clang::ASTContext::Char32Ty
Definition at line 1085 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnStringLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::CheckLiteralOperatorDeclaration(), ConvertDeclSpecToType(), clang::ASTReader::GetType(), InitBuiltinTypes(), IsStringInit(), and IsWideCharCompatible().
Char8Ty
CanQualType clang::ASTContext::Char8Ty
Definition at line 1083 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnStringLiteral(), clang::Sema::CheckLiteralOperatorDeclaration(), ConvertDeclSpecToType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
CharTy
CanQualType clang::ASTContext::CharTy
Definition at line 1079 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnLastBitfield(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnSourceLocExpr(), clang::Sema::ActOnStringLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildPredefinedExpr(), clang::ento::StoreManager::castRegion(), clang::Sema::CheckLiteralOperatorDeclaration(), checkLiteralOperatorTemplateParameterList(), clang::Sema::CheckMain(), clang::Sema::CheckPtrComparisonWithNullChar(), CheckTautologicalComparison(), ConvertDeclSpecToType(), clang::SYCLUniqueStableNameExpr::Create(), CreateCharPtrNamedVaListDecl(), clang::SYCLUniqueStableNameExpr::CreateEmpty(), DecodeTypeFromStr(), diagnoseStringPlusChar(), doRewriteToUTF8StringBoxedExpressionHelper(), clang::APValue::dump(), EvaluateBuiltinStrLen(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), getCFConstantStringDecl(), GetCFNumberSize(), getCharWidth(), getPredefinedStringLiteralFromCache(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), InitBuiltinTypes(), LookupStdSourceLocationImpl(), clang::ento::ExprEngine::VisitArraySubscriptExpr(), and clang::ASTNodeImporter::VisitBuiltinType().
CommentlessRedeclChains
llvm::DenseMap<const Decl *, const Decl *> clang::ASTContext::CommentlessRedeclChains mutable
Keeps track of redeclaration chains that don't have any comment attached.
Mapping from canonical declaration to redeclaration chain that has no comments attached to any redeclaration. Specifically it's mapping to the last redeclaration we've checked.
Shall not contain declarations that have comments attached to any redeclaration in their chain.
Definition at line 816 of file ASTContext.h.
Referenced by cacheRawCommentForDecl(), and getRawCommentForAnyRedecl().
Comments
RawCommentList clang::ASTContext::Comments
All comments in this translation unit.
Definition at line 791 of file ASTContext.h.
Referenced by addComment(), attachCommentsToJustParsedDecls(), getRawCommentForDeclNoCache(), getRawCommentForDeclNoCacheImpl(), and clang::ASTReader::ReadComments().
CommentsLoaded
bool clang::ASTContext::CommentsLoaded = false mutable
True if comments are already loaded from ExternalASTSource.
Definition at line 794 of file ASTContext.h.
Referenced by getRawCommentForDeclNoCache().
CompCategories
ComparisonCategories clang::ASTContext::CompCategories
Types and expressions required to build C++2a three-way comparisons using operator<=>, including the values return by builtin <=> operators.
Definition at line 2227 of file ASTContext.h.
Referenced by clang::Sema::BuildSynthesizedThreeWayComparison(), and clang::Sema::CheckComparisonCategoryType().
CUDAConstantEvalCtx
struct clang::ASTContext::CUDAConstantEvalContext clang::ASTContext::CUDAConstantEvalCtx
Referenced by clang::ASTContext::CUDAConstantEvalContextRAII::CUDAConstantEvalContextRAII(), and clang::ASTContext::CUDAConstantEvalContextRAII::~CUDAConstantEvalContextRAII().
CUDADeviceVarODRUsedByHost
llvm::DenseSet<const VarDecl *> clang::ASTContext::CUDADeviceVarODRUsedByHost
Keep track of CUDA/HIP device-side variables ODR-used by host code.
Definition at line 1144 of file ASTContext.h.
Referenced by MarkVarDeclODRUsed(), and shouldExternalize().
CUDAExternalDeviceDeclODRUsedByHost
llvm::DenseSet<const ValueDecl *> clang::ASTContext::CUDAExternalDeviceDeclODRUsedByHost
Keep track of CUDA/HIP external kernels or device variables ODR-used by host code.
Definition at line 1148 of file ASTContext.h.
Referenced by clang::Sema::CheckCUDACall(), MarkVarDeclODRUsed(), and clang::CodeGen::CodeGenModule::Release().
DeclarationNames
DeclarationNameTable clang::ASTContext::DeclarationNames mutable
Definition at line 634 of file ASTContext.h.
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXFoldExpr(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnStringLiteral(), addBlockPointerConversion(), addFunctionPointerConversion(), clang::Sema::AddMemberOperatorCandidates(), clang::Sema::AddOverriddenMethods(), clang::TemplateDeclInstantiator::adjustForRewrite(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildCallToObjectOfClassType(), BuildCookedLiteralOperatorCall(), clang::Sema::BuildOperatorCoawaitLookupExpr(), clang::Sema::BuildOverloadedArrowExpr(), buildSingleCopyAssignRecursively(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckFunctionDeclaration(), checkMappableExpressionList(), clang::Sema::CreateLambdaCallOperator(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeclareGlobalNewDelete(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), DiagnoseTwoPhaseOperatorLookup(), doesUsualArrayDeleteWantSize(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindDeallocationFunctionForDestructor(), findDeleteForPromise(), findImplicitlyDeclaredEqualityComparisons(), getConstructors(), clang::CXXRecordDecl::getDestructor(), getLambdaCallOperatorHelper(), getNameForTemplate(), clang::Sema::GetNameFromUnqualifiedId(), hasMember(), clang::ASTImporter::Import(), clang::Sema::isTemplateName(), clang::Sema::LookupConstructors(), clang::Sema::LookupOverloadedBinOp(), clang::Sema::LookupOverloadedOperatorName(), clang::Sema::LookupSpecialMember(), clang::Parser::parseMapperModifier(), parseOpenMPReductionId(), processImplicitMapsWithDefaultMappers(), clang::Sema::ProduceCallSignatureHelp(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), shouldAddReversedEqEq(), clang::Sema::ShouldDeleteSpecialMember(), threadSafetyCheckIsSmartPointer(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
DeclRawComments
llvm::DenseMap<const Decl *, const RawComment *> clang::ASTContext::DeclRawComments mutable
Mapping from declaration to directly attached comment.
Raw comments are owned by Comments list. This mapping is populated lazily.
Definition at line 800 of file ASTContext.h.
Referenced by attachCommentsToJustParsedDecls(), cacheRawCommentForDecl(), and getRawCommentForAnyRedecl().
DependentTy
CanQualType clang::ASTContext::DependentTy
Definition at line 1105 of file ASTContext.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPArrayShapingExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnPseudoDestructorExpr(), AddResultTypeChunk(), clang::Sema::BuildBinOp(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::buildCoroutinePromise(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCXXFoldExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::buildOverloadedCallSet(), clang::Sema::BuildPredefinedExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildUnresolvedCoawaitExpr(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckCompleteDecompositionDeclaration(), clang::Sema::CheckConditionalOperands(), clang::Sema::CheckEnumConstant(), CheckIncrementDecrementOperand(), CheckIndirectionOperand(), clang::Sema::CheckPackExpansion(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::checkPseudoObjectIncDec(), CheckRealImagOperand(), ConvertDeclSpecToType(), clang::DependentScopeDeclRefExpr::Create(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateRecoveryExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::CallExpr::getCallReturnType(), GetDeclSpecTypeForDeclarator(), clang::Sema::getDecltypeForExpr(), getDependentArraySubscriptType(), getDummyLambdaType(), GetFullTypeForDeclarator(), getInjectedTemplateArg(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::MergeVarDeclTypes(), clang::OverloadExpr::OverloadExpr(), clang::Sema::SubstAutoType(), and clang::Sema::SubstAutoTypeSourceInfo().
DoubleTy
CanQualType clang::ASTContext::DoubleTy
Definition at line 1089 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::BuildVAArgExpr(), clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::Sema::DefaultArgumentPromotion(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getBuiltinVectorTypeInfo(), GetCFNumberSize(), GetFullTypeForDeclarator(), getNeonEltType(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), RVVType2Qual(), and clang::Sema::UsualUnaryConversions().
ExternalSource
IntrusiveRefCntPtr<ExternalASTSource> clang::ASTContext::ExternalSource
Definition at line 635 of file ASTContext.h.
Referenced by getExternalSource(), getRawCommentForDeclNoCache(), PrintStats(), and setExternalSource().
Float128Ty
CanQualType clang::ASTContext::Float128Ty
Definition at line 1089 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), DecodeTypeFromStr(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), and InitBuiltinTypes().
Float16Ty
CanQualType clang::ASTContext::Float16Ty
Definition at line 1103 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::ASTReader::GetType(), InitBuiltinTypes(), and RVVType2Qual().
FloatTy
CanQualType clang::ASTContext::FloatTy
Definition at line 1089 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), convertHalfVecBinOp(), clang::Sema::CreateBuiltinUnaryOp(), DecodeTypeFromStr(), clang::Sema::DefaultArgumentPromotion(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getBuiltinVectorTypeInfo(), GetCFNumberSize(), getNeonEltType(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), handleFloatConversion(), InitBuiltinTypes(), clang::Sema::Initialize(), mergeFunctionTypes(), clang::Sema::PerformImplicitConversion(), RVVType2Qual(), and clang::Sema::UsualUnaryConversions().
FractTy
CanQualType clang::ASTContext::FractTy
Definition at line 1093 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
HalfTy
CanQualType clang::ASTContext::HalfTy
Definition at line 1101 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), convertHalfVecBinOp(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinUnaryOp(), DecodeTypeFromStr(), getBuiltinVectorTypeInfo(), getNeonEltType(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), and needsConversionOfHalfVec().
Ibm128Ty
CanQualType clang::ASTContext::Ibm128Ty
Definition at line 1089 of file ASTContext.h.
Referenced by ConvertDeclSpecToType(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), and InitBuiltinTypes().
Idents
IdentifierTable& clang::ASTContext::Idents
Definition at line 630 of file ASTContext.h.
Referenced by clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnCompoundRequirement(), clang::Sema::ActOnInstanceMessage(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCBoolLiteral(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnStringLiteral(), addFunctionPointerConversion(), clang::Sema::addImplicitTypedef(), clang::Sema::AddKnownFunctionAttributes(), AddObjCKeyValueCompletions(), clang::Sema::BuildBuiltinCallExpr(), buildCapture(), buildImplicitRecord(), buildImplicitTypedef(), clang::Sema::BuildIvarRefExpr(), buildMemcpyForAssignmentOp(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCStringLiteral(), buildSingleCopyAssignRecursively(), clang::CodeGen::CGCXXABI::buildThisParam(), CheckKeyForObjCARCConversion(), checkMappableExpressionList(), clang::Sema::CheckObjCForCollectionOperand(), clang::Sema::checkOpenMPDeclareVariantFunction(), CheckProtocolMethodDefs(), cleanupDeallocOrFinalize(), configureBlocksRuntimeObject(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), clang::Sema::CreateBuiltinBinOp(), CreateHexagonBuiltinVaListDecl(), clang::ObjCMethodDecl::createImplicitParams(), CreatePowerABIBuiltinVaListDecl(), clang::Sema::CreatePropertyDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), CXXRecordMembersNamed(), clang::Sema::DefaultLvalueConversion(), DiagnoseDirectIsaAccess(), emitOutlinedFunctionPrologue(), emitReplacement(), findOMPAllocatorHandleT(), GCRewriteFinalize(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), getBlockDescriptorExtendedType(), getBlockDescriptorType(), getBoolName(), getCFConstantStringDecl(), clang::ObjCPropertyDecl::getDefaultSynthIvarName(), getErrnoFunc(), clang::getKeywordSelector(), getLambdaStaticInvokers(), getMakeIntegerSeqName(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSClassId(), getNSCopyingName(), clang::NSAPI::getNSDictionarySelector(), getNSNumberFactoryMethod(), clang::NSAPI::getNSNumberLiteralSelector(), getNSObjectName(), clang::NSAPI::getNSSetSelector(), clang::NSAPI::getNSStringSelector(), clang::GetNullarySelector(), getObjCProtocolDecl(), getOpenCLEnumType(), getOpenCLTypedefType(), clang::Sema::getSuperIdentifier(), getTypePackElementName(), clang::GetUnarySelector(), handleAliasAttr(), handleAvailabilityAttr(), handleFormatAttr(), handleIBOutletCollection(), hasMember(), hasTypedefNamed(), clang::ASTImporter::Import(), clang::Sema::Initialize(), clang::HLSLExternalSemaSource::InitializeSema(), clang::Sema::InventAbbreviatedTemplateParameterTypeName(), isCFStringType(), clang::Sema::isKnownName(), clang::NSAPI::isMacroDefined(), isMacroDefined(), isNSStringType(), isNSStringType(), IsValidIdentifier(), isValidInteropVariable(), lookupCXXRecordDecl(), clang::Sema::LookupInlineAsmField(), clang::Sema::LookupInlineAsmVarDeclField(), clang::LookupNamed(), clang::LookupNamespace(), LookupPredefedObjCSuperType(), lookupStdNamespace(), mergeDeclAttribute(), processImplicitMapsWithDefaultMappers(), PropertyMemoryAttribute(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), shouldRunOnFunctionOrMethod(), and transferARCOwnershipToDeclaratorChunk().
IncompleteMatrixIdxTy
CanQualType clang::ASTContext::IncompleteMatrixIdxTy
Definition at line 1115 of file ASTContext.h.
Referenced by clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::ASTReader::GetType(), and InitBuiltinTypes().
Int128Ty
CanQualType clang::ASTContext::Int128Ty
Definition at line 1086 of file ASTContext.h.
Referenced by ChangeIntegralSignedness(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), ConvertDeclSpecToType(), DecodeTypeFromStr(), getCorrespondingSignedType(), getInt128Decl(), getIntTypeForBitwidth(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
IntTy
CanQualType clang::ASTContext::IntTy
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1086 of file ASTContext.h.
Referenced by clang::Sema::ActOnAliasDeclaration(), clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnExceptionDeclarator(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnIntegerConstant(), clang::Sema::ActOnLastBitfield(), clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnTag(), clang::Sema::AddModeAttr(), clang::CodeGen::CodeGenTypes::arrangeMSCtorClosure(), clang::ento::ProgramState::assumeInBoundDual(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBinOp(), ChangeIntegralSignedness(), clang::Sema::CheckEnumConstant(), clang::Sema::CheckFieldDecl(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckMain(), clang::Sema::CheckPlaceholderExpr(), ConvertDeclSpecToType(), CreateAArch64ABIBuiltinVaListDecl(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), CreatePNaClABIBuiltinVaListDecl(), DecodePPCMMATypeFromStr(), DecodeTypeFromStr(), DeduceTemplateArgumentsByTypeMatch(), clang::PreferredTypeBuilder::enterSubscript(), clang::analyze_format_string::OptionalAmount::getArgType(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCFConstantStringDecl(), GetCFNumberSize(), clang::ento::SValBuilder::getConditionType(), getCorrespondingSignedType(), GetDeclSpecTypeForDeclarator(), getErrnoFunc(), GetFullTypeForDeclarator(), getGuardAcquireFn(), clang::ento::BasicValueFactory::getIntValue(), getLegacyIntegralTypeEncoding(), getLogicalOperationType(), getNeonEltType(), getNextLargerIntegralType(), getObjCEncodingTypeSize(), getPreferredTypeOfBinaryRHS(), getPreferredTypeOfUnaryArg(), getPromotedIntegerType(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), clang::Sema::getTypeName(), HandleDestructionImpl(), clang::Sema::HandleField(), handleMIGServerRoutineAttr(), clang::Sema::HandleMSProperty(), clang::Sema::ImplicitlyDefineFunction(), InitBuiltinTypes(), clang::Sema::Initialize(), clang::InitializationSequence::InitializeFrom(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::Sema::IsIntegralPromotion(), isOverflowingIntegerType(), clang::Expr::isPotentialConstantExpr(), isPromotableBitField(), makeLaunchBoundsArgExpr(), mayBeSuccess(), clang::Sema::PreferredConditionType(), clang::Sema::prepareVectorSplat(), clang::TreeTransform< Derived >::RebuildBitIntType(), clang::TreeTransform< Derived >::RebuildExtVectorType(), rewriteToNumericBoxedExpression(), clang::ento::errno_modeling::setErrnoValue(), and shouldNotPrintDirectly().
Listener
ASTMutationListener* clang::ASTContext::Listener = nullptr
Definition at line 636 of file ASTContext.h.
Referenced by getASTMutationListener(), mergeDefinitionIntoModule(), and setASTMutationListener().
LongAccumTy
CanQualType clang::ASTContext::LongAccumTy
Definition at line 1091 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
LongDoubleTy
CanQualType clang::ASTContext::LongDoubleTy
Definition at line 1089 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::checkTypeSupport(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getRealTypeForBitwidth(), clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::Sema::UsualUnaryConversions().
LongFractTy
CanQualType clang::ASTContext::LongFractTy
Definition at line 1093 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
LongLongTy
CanQualType clang::ASTContext::LongLongTy
Definition at line 1086 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnNumericConstant(), ChangeIntegralSignedness(), clang::CodeGen::DefaultABIInfo::classifyArgumentType(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::Sema::DefaultArgumentPromotion(), clang::analyze_scanf::ScanfSpecifier::getArgType(), GetCFNumberSize(), getCorrespondingSignedType(), getNeonEltType(), getNextLargerIntegralType(), getNSIntegerType(), getPromotedIntegerType(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::Sema::IsIntegralPromotion().
LongTy
CanQualType clang::ASTContext::LongTy
Definition at line 1086 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnGNUNullExpr(), clang::Sema::ActOnNumericConstant(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), CreateSystemZBuiltinVaListDecl(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCFConstantStringDecl(), GetCFNumberSize(), getCorrespondingSignedType(), getNeonEltType(), getNextLargerIntegralType(), getNSIntegerType(), getPromotedIntegerType(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), clang::Sema::IsIntegralPromotion(), and RVVType2Qual().
MSGuidTagDecl
TagDecl* clang::ASTContext::MSGuidTagDecl = nullptr mutable
Definition at line 1141 of file ASTContext.h.
Referenced by getMSGuidDecl(), getMSGuidTagDecl(), getMSGuidType(), and InitBuiltinTypes().
NullPtrTy
CanQualType clang::ASTContext::NullPtrTy
Definition at line 1104 of file ASTContext.h.
Referenced by clang::Sema::ActOnCXXNullPtrLiteral(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildExpressionFromIntegralTemplateArgument(), DeduceNullPtrTemplateArgument(), clang::ASTReader::GetType(), and InitBuiltinTypes().
NumImplicitCopyAssignmentOperators
unsigned clang::ASTContext::NumImplicitCopyAssignmentOperators = 0
The number of implicitly-declared copy assignment operators.
Definition at line 3176 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitCopyAssignmentOperatorsDeclared
unsigned clang::ASTContext::NumImplicitCopyAssignmentOperatorsDeclared = 0
The number of implicitly-declared copy assignment operators for which declarations were built.
Definition at line 3180 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitCopyConstructors
unsigned clang::ASTContext::NumImplicitCopyConstructors = 0
The number of implicitly-declared copy constructors.
Definition at line 3162 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitCopyConstructorsDeclared
unsigned clang::ASTContext::NumImplicitCopyConstructorsDeclared = 0
The number of implicitly-declared copy constructors for which declarations were built.
Definition at line 3166 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitDefaultConstructors
unsigned clang::ASTContext::NumImplicitDefaultConstructors = 0
The number of implicitly-declared default constructors.
Definition at line 3155 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitDefaultConstructorsDeclared
unsigned clang::ASTContext::NumImplicitDefaultConstructorsDeclared = 0
The number of implicitly-declared default constructors for which declarations were built.
Definition at line 3159 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitDestructors
unsigned clang::ASTContext::NumImplicitDestructors = 0
The number of implicitly-declared destructors.
Definition at line 3190 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitDestructorsDeclared
unsigned clang::ASTContext::NumImplicitDestructorsDeclared = 0
The number of implicitly-declared destructors for which declarations were built.
Definition at line 3194 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitMoveAssignmentOperators
unsigned clang::ASTContext::NumImplicitMoveAssignmentOperators = 0
The number of implicitly-declared move assignment operators.
Definition at line 3183 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitMoveAssignmentOperatorsDeclared
unsigned clang::ASTContext::NumImplicitMoveAssignmentOperatorsDeclared = 0
The number of implicitly-declared move assignment operators for which declarations were built.
Definition at line 3187 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitMoveConstructors
unsigned clang::ASTContext::NumImplicitMoveConstructors = 0
The number of implicitly-declared move constructors.
Definition at line 3169 of file ASTContext.h.
Referenced by PrintStats().
NumImplicitMoveConstructorsDeclared
unsigned clang::ASTContext::NumImplicitMoveConstructorsDeclared = 0
The number of implicitly-declared move constructors for which declarations were built.
Definition at line 3173 of file ASTContext.h.
Referenced by PrintStats().
ObjCBuiltinBoolTy
CanQualType clang::ASTContext::ObjCBuiltinBoolTy
Definition at line 1109 of file ASTContext.h.
Referenced by clang::Sema::ActOnObjCBoolLiteral(), and InitBuiltinTypes().
ObjCBuiltinClassTy
CanQualType clang::ASTContext::ObjCBuiltinClassTy
Definition at line 1108 of file ASTContext.h.
Referenced by applyObjCProtocolQualifiers(), getObjCClassDecl(), clang::ASTReader::GetType(), and InitBuiltinTypes().
ObjCBuiltinIdTy
CanQualType clang::ASTContext::ObjCBuiltinIdTy
Definition at line 1108 of file ASTContext.h.
Referenced by clang::Sema::actOnObjCProtocolQualifierType(), applyObjCProtocolQualifiers(), clang::Sema::BuildObjCDictionaryLiteral(), getObjCIdDecl(), clang::Type::getObjCSubstitutions(), clang::ASTReader::GetType(), and InitBuiltinTypes().
ObjCBuiltinSelTy
CanQualType clang::ASTContext::ObjCBuiltinSelTy
Definition at line 1108 of file ASTContext.h.
Referenced by getObjCSelDecl(), clang::ASTReader::GetType(), and InitBuiltinTypes().
OCLClkEventTy
CanQualType clang::ASTContext::OCLClkEventTy
Definition at line 1113 of file ASTContext.h.
Referenced by clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), and SemaOpenCLBuiltinEnqueueKernel().
OCLEventTy
CanQualType clang::ASTContext::OCLEventTy
Definition at line 1113 of file ASTContext.h.
Referenced by clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::Sema::Initialize().
OCLQueueTy
CanQualType clang::ASTContext::OCLQueueTy
Definition at line 1114 of file ASTContext.h.
Referenced by clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), and SemaOpenCLBuiltinEnqueueKernel().
OCLReserveIDTy
CanQualType clang::ASTContext::OCLReserveIDTy
Definition at line 1114 of file ASTContext.h.
Referenced by clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), SemaBuiltinCommitRWPipe(), SemaBuiltinReserveRWPipe(), and SemaBuiltinRWPipe().
OCLSamplerTy
CanQualType clang::ASTContext::OCLSamplerTy
Definition at line 1113 of file ASTContext.h.
Referenced by clang::CodeGen::CGOpenCLRuntime::getSamplerType(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), and clang::InitializationSequence::Perform().
OMPArraySectionTy
CanQualType clang::ASTContext::OMPArraySectionTy
Definition at line 1116 of file ASTContext.h.
Referenced by clang::Sema::ActOnOMPArraySectionExpr(), clang::ASTReader::GetType(), and InitBuiltinTypes().
OMPArrayShapingTy
CanQualType clang::ASTContext::OMPArrayShapingTy
Definition at line 1116 of file ASTContext.h.
Referenced by clang::Sema::ActOnOMPArrayShapingExpr(), and InitBuiltinTypes().
OMPIteratorTy
CanQualType clang::ASTContext::OMPIteratorTy
Definition at line 1116 of file ASTContext.h.
Referenced by clang::Sema::ActOnOMPIteratorExpr(), clang::ASTReader::GetType(), and InitBuiltinTypes().
OverloadTy
CanQualType clang::ASTContext::OverloadTy
Definition at line 1105 of file ASTContext.h.
Referenced by AdjustFunctionParmAndArgTypesForDeduction(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildReferenceType(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), DeduceTemplateArgumentsByTypeMatch(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DiagnoseAssignmentResult(), DiagnoseBadConversion(), clang::Sema::FindAssociatedClassesAndNamespaces(), clang::ASTReader::GetType(), handleCleanupAttr(), InitBuiltinTypes(), clang::InitializationSequence::InitializeFrom(), IsStandardConversion(), clang::Sema::NoteAllOverloadCandidates(), clang::Sema::PerformImplicitConversion(), clang::Sema::ResolveAddressOfOverloadedFunction(), clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), ResolveOverloadedFunctionForReferenceBinding(), clang::Sema::tryExprAsCall(), TryListConversion(), TryReferenceInit(), TryReferenceInitializationCore(), TryReinterpretCast(), and TryStaticMemberPointerUpcast().
ParsedComments
llvm::DenseMap<const Decl *, comments::FullComment *> clang::ASTContext::ParsedComments mutable
Mapping from declarations to parsed comments attached to any redeclaration.
Definition at line 820 of file ASTContext.h.
Referenced by attachCommentsToJustParsedDecls(), and getCommentForDecl().
PseudoObjectTy
CanQualType clang::ASTContext::PseudoObjectTy
Definition at line 1107 of file ASTContext.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::BuildCallExpr(), BuildMSPropertyRefExpr(), clang::Sema::BuildObjCSubscriptExpression(), clang::ASTReader::GetType(), clang::Sema::HandleExprPropertyRefExpr(), InitBuiltinTypes(), and LookupMemberExpr().
RedeclChainComments
llvm::DenseMap<const Decl *, const Decl *> clang::ASTContext::RedeclChainComments mutable
Mapping from canonical declaration to the first redeclaration in chain that has a comment attached.
Raw comments are owned by Comments list. This mapping is populated lazily.
Definition at line 807 of file ASTContext.h.
Referenced by cacheRawCommentForDecl(), and getRawCommentForAnyRedecl().
SatAccumTy
CanQualType clang::ASTContext::SatAccumTy
Definition at line 1095 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatFractTy
CanQualType clang::ASTContext::SatFractTy
Definition at line 1098 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatLongAccumTy
CanQualType clang::ASTContext::SatLongAccumTy
Definition at line 1095 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatLongFractTy
CanQualType clang::ASTContext::SatLongFractTy
Definition at line 1098 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatShortAccumTy
CanQualType clang::ASTContext::SatShortAccumTy
Definition at line 1095 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatShortFractTy
CanQualType clang::ASTContext::SatShortFractTy
Definition at line 1098 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedAccumTy
CanQualType clang::ASTContext::SatUnsignedAccumTy
Definition at line 1096 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedFractTy
CanQualType clang::ASTContext::SatUnsignedFractTy
Definition at line 1099 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedLongAccumTy
CanQualType clang::ASTContext::SatUnsignedLongAccumTy
Definition at line 1097 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedLongFractTy
CanQualType clang::ASTContext::SatUnsignedLongFractTy
Definition at line 1100 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedShortAccumTy
CanQualType clang::ASTContext::SatUnsignedShortAccumTy
Definition at line 1096 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SatUnsignedShortFractTy
CanQualType clang::ASTContext::SatUnsignedShortFractTy
Definition at line 1099 of file ASTContext.h.
Referenced by getCorrespondingSaturatedType(), getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SectionInfos
llvm::StringMap<SectionInfo> clang::ASTContext::SectionInfos
Definition at line 3346 of file ASTContext.h.
Referenced by clang::Sema::UnifySection(), and clang::Sema::UnifySection().
Selectors
SelectorTable& clang::ASTContext::Selectors
Definition at line 631 of file ASTContext.h.
Referenced by clang::Sema::ActOnInstanceMessage(), AddObjCKeyValueCompletions(), clang::Sema::BuildObjCBoxedExpr(), CheckKeyForObjCARCConversion(), clang::Sema::checkObjCBridgeRelatedComponents(), clang::Sema::CheckObjCForCollectionOperand(), CheckProtocolMethodDefs(), cleanupDeallocOrFinalize(), GCRewriteFinalize(), clang::getKeywordSelector(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSDictionarySelector(), clang::NSAPI::getNSNumberLiteralSelector(), clang::NSAPI::getNSSetSelector(), clang::NSAPI::getNSStringSelector(), clang::GetNullarySelector(), clang::GetUnarySelector(), and clang::ASTImporter::Import().
ShortAccumTy
CanQualType clang::ASTContext::ShortAccumTy
Definition at line 1090 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
ShortFractTy
CanQualType clang::ASTContext::ShortFractTy
Definition at line 1093 of file ASTContext.h.
Referenced by clang::Sema::ActOnNumericConstant(), ConvertDeclSpecToType(), getCorrespondingSignedFixedPointType(), getCorrespondingSignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
ShortTy
CanQualType clang::ASTContext::ShortTy
Definition at line 1086 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), convertHalfVecBinOp(), DecodeTypeFromStr(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), clang::analyze_scanf::ScanfSpecifier::getArgType(), GetCFNumberSize(), getCorrespondingSignedType(), getNeonEltType(), getNextLargerIntegralType(), clang::Sema::GetSignedVectorType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
SignedCharTy
CanQualType clang::ASTContext::SignedCharTy
Definition at line 1086 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCorrespondingSignedType(), getNeonEltType(), clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::ASTNodeImporter::VisitBuiltinType().
TUKind
const TranslationUnitKind clang::ASTContext::TUKind
Definition at line 633 of file ASTContext.h.
Referenced by addTranslationUnitDecl().
UnknownAnyTy
CanQualType clang::ASTContext::UnknownAnyTy
Definition at line 1105 of file ASTContext.h.
Referenced by clang::Sema::ActOnFinishFullExpr(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::CheckAddressOfOperand(), clang::Sema::CheckMessageArgumentTypes(), ClassifyInternal(), ClassifyMemberExpr(), ConvertDeclSpecToType(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::GatherArgumentsForCall(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedAccumTy
CanQualType clang::ASTContext::UnsignedAccumTy
Definition at line 1092 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedCharTy
CanQualType clang::ASTContext::UnsignedCharTy
Definition at line 1087 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnStringLiteral(), ChangeIntegralSignedness(), checkPointerTypesForAssignment(), ConvertDeclSpecToType(), CreatePowerABIBuiltinVaListDecl(), DecodePPCMMATypeFromStr(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCorrespondingUnsignedType(), getNeonEltType(), clang::Type::getSveEltType(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::TreeTransform< Derived >::RebuildArrayType(), and clang::ASTNodeImporter::VisitBuiltinType().
UnsignedFractTy
CanQualType clang::ASTContext::UnsignedFractTy
Definition at line 1094 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedInt128Ty
CanQualType clang::ASTContext::UnsignedInt128Ty
Definition at line 1088 of file ASTContext.h.
Referenced by ChangeIntegralSignedness(), ConvertDeclSpecToType(), DecodeTypeFromStr(), getCorrespondingUnsignedType(), getIntTypeForBitwidth(), clang::ASTReader::GetType(), getUInt128Decl(), InitBuiltinTypes(), and clang::TreeTransform< Derived >::RebuildArrayType().
UnsignedIntTy
CanQualType clang::ASTContext::UnsignedIntTy
Definition at line 1087 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnSourceLocExpr(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), CreateX86_64ABIBuiltinVaListDecl(), DecodeTypeFromStr(), DeduceTemplateArgumentsByTypeMatch(), clang::SourceLocExpr::EvaluateInContext(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCorrespondingUnsignedType(), clang::ento::BasicValueFactory::getIntValue(), getLegacyIntegralTypeEncoding(), getNeonEltType(), getNextLargerIntegralType(), getPromotedIntegerType(), clang::ASTReader::GetType(), getUnsignedWCharType(), InitBuiltinTypes(), clang::Sema::Initialize(), clang::Sema::IsIntegralPromotion(), isPromotableBitField(), clang::TreeTransform< Derived >::RebuildArrayType(), SemaBuiltinReserveRWPipe(), SemaBuiltinRWPipe(), and shouldNotPrintDirectly().
UnsignedLongAccumTy
CanQualType clang::ASTContext::UnsignedLongAccumTy
Definition at line 1092 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedLongFractTy
CanQualType clang::ASTContext::UnsignedLongFractTy
Definition at line 1094 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedLongLongTy
CanQualType clang::ASTContext::UnsignedLongLongTy
Definition at line 1088 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnNumericConstant(), ChangeIntegralSignedness(), clang::Sema::CheckLiteralOperatorDeclaration(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::Sema::DefaultArgumentPromotion(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCorrespondingUnsignedType(), getNeonEltType(), getNextLargerIntegralType(), getNSUIntegerType(), getPromotedIntegerType(), clang::ASTReader::GetType(), InitBuiltinTypes(), instantiateDependentAllocAlignAttr(), clang::Sema::IsIntegralPromotion(), and clang::TreeTransform< Derived >::RebuildArrayType().
UnsignedLongTy
CanQualType clang::ASTContext::UnsignedLongTy
Definition at line 1087 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), clang::Sema::ActOnNumericConstant(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCDictionaryLiteral(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getBlockDescriptorExtendedType(), getBlockDescriptorType(), getCorrespondingUnsignedType(), getNeonEltType(), getNextLargerIntegralType(), getNSUIntegerType(), clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType(), getPromotedIntegerType(), clang::ASTReader::GetType(), InitBuiltinTypes(), clang::Sema::Initialize(), clang::Sema::IsIntegralPromotion(), clang::TreeTransform< Derived >::RebuildArrayType(), and RVVType2Qual().
UnsignedShortAccumTy
CanQualType clang::ASTContext::UnsignedShortAccumTy
Definition at line 1092 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedShortFractTy
CanQualType clang::ASTContext::UnsignedShortFractTy
Definition at line 1094 of file ASTContext.h.
Referenced by getCorrespondingUnsignedType(), clang::ASTReader::GetType(), and InitBuiltinTypes().
UnsignedShortTy
CanQualType clang::ASTContext::UnsignedShortTy
Definition at line 1087 of file ASTContext.h.
Referenced by clang::Sema::ActOnEnumBody(), ChangeIntegralSignedness(), ConvertDeclSpecToType(), CreatePowerABIBuiltinVaListDecl(), DecodeTypeFromStr(), clang::analyze_scanf::ScanfSpecifier::getArgType(), getCorrespondingUnsignedType(), getNeonEltType(), getNextLargerIntegralType(), clang::ASTReader::GetType(), InitBuiltinTypes(), and clang::TreeTransform< Derived >::RebuildArrayType().
VaListTagDecl
Decl* clang::ASTContext::VaListTagDecl = nullptr mutable
Definition at line 1138 of file ASTContext.h.
Referenced by CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), getVaListTagDecl(), and InitBuiltinTypes().
VoidPtrTy
CanQualType clang::ASTContext::VoidPtrTy
Definition at line 1104 of file ASTContext.h.
Referenced by clang::Sema::ActOnOpenMPRegionStart(), AddDirectArgument(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), clang::ento::SimpleConstraintManager::assumeInternal(), clang::Sema::BuildObjCBoxedExpr(), CheckAtomicAlignment(), CheckDeleteKind(), CheckOperatorDeleteDeclaration(), CheckOperatorNewDeclaration(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::DiagnoseUnusedExprResult(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), emitReduceInitFunction(), emitStructGetterCall(), emitStructSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::CodeGen::CGOpenMPRuntime::emitUsesAllocatorsFini(), clang::CodeGen::CGOpenMPRuntime::emitUsesAllocatorsInit(), clang::Sema::FindAllocationFunctions(), generateByrefCopyHelper(), generateByrefDisposeHelper(), getAllocatorVal(), getBlockDescriptorExtendedType(), getObjCEncodingForBlock(), getObjCEncodingForMethodDecl(), getObjCEncodingTypeSize(), InitBuiltinTypes(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), and clang::Interpreter::SynthesizeExpr().
VoidTy
CanQualType clang::ASTContext::VoidTy
Definition at line 1077 of file ASTContext.h.
Referenced by clang::Sema::ActOnAddrLabel(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnIndirectGotoStmt(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPRegionStart(), clang::Sema::AdjustDestructorExceptionSpec(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), clang::CodeGen::CodeGenTypes::arrangeMSCtorClosure(), clang::CodeGen::CodeGenTypes::arrangeUnprototypedMustTailThunk(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildEmptyCXXFoldExpr(), clang::Sema::BuildInitList(), buildPostUpdate(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildStmtExpr(), clang::ento::StoreManager::castRegion(), clang::Sema::CheckARCMethodDecl(), checkConditionalBlockPointerCompatibility(), checkConditionalPointerCompatibility(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), CheckOperatorDeleteDeclaration(), ConvertDeclSpecToType(), ConvertQualTypeToKind(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateVoidPtrBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), clang::Sema::DeclareGlobalNewDelete(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::Sema::DeclareImplicitMoveConstructor(), DecodeTypeFromStr(), clang::Sema::deduceClosureReturnType(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::CodeGen::CodeGenTypes::DeriveThisType(), diagOpenCLBuiltinTypeError(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), emitOutlinedFunctionPrologue(), emitStructGetterCall(), emitStructSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::Sema::FindAllocationFunctions(), GeneralizeType(), generateByrefCopyHelper(), generateByrefDisposeHelper(), clang::CallExpr::getCallReturnType(), GetDeclSpecTypeForDeclarator(), clang::ento::CallEvent::getResultType(), clang::ASTReader::GetType(), clang::ento::MemRegionManager::getVarRegion(), clang::Sema::IgnoredValueConversions(), InitBuiltinTypes(), clang::Sema::MaybeCreateStmtWithCleanups(), clang::Sema::ProcessPropertyDecl(), clang::Sema::PushCapturedRegionScope(), RVVType2Qual(), TryListConversion(), and clang::ASTNodeImporter::VisitFunctionDecl().
WCharTy
CanQualType clang::ASTContext::WCharTy
Definition at line 1080 of file ASTContext.h.
Referenced by ConvertDeclSpecToType(), getSignedWCharType(), clang::ASTReader::GetType(), getWCharType(), InitBuiltinTypes(), and clang::ASTNodeImporter::VisitBuiltinType().
WideCharTy
CanQualType clang::ASTContext::WideCharTy
Definition at line 1081 of file ASTContext.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::BuildPredefinedExpr(), clang::Sema::CheckLiteralOperatorDeclaration(), getWideCharType(), and InitBuiltinTypes().
WIntTy
CanQualType clang::ASTContext::WIntTy
Definition at line 1082 of file ASTContext.h.
Referenced by getWIntType(), and InitBuiltinTypes().
The documentation for this class was generated from the following files:
include/clang/AST/ASTContext.h
include/clang/AST/ParentMapContext.h
lib/AST/ASTContext.cpp
lib/AST/DeclBase.cpp
lib/AST/RecordLayoutBuilder.cpp