clang: clang::FileMgr::MapEntryOptionalStorage< RefTy > Class Template Reference
clang::FileMgr::MapEntryOptionalStorage< RefTy > Class Template Reference
Customized storage for refs derived from map entires in FileManager, using the private optional_none_tag to keep it to the size of a single pointer.
#include "clang/Basic/DirectoryEntry.h"
Public Member Functions
MapEntryOptionalStorage ()
template<class... ArgTypes>
MapEntryOptionalStorage (std::in_place_t, ArgTypes &&...Args)
void reset ()
bool has_value () const
RefTy & value () &
RefTy const & value () const &
RefTy && value () &&
template<class... Args>
void emplace (Args &&...args)
MapEntryOptionalStorage & operator= (RefTy Ref)
Detailed Description
template<class RefTy>
class clang::FileMgr::MapEntryOptionalStorage< RefTy >
Customized storage for refs derived from map entires in FileManager, using the private optional_none_tag to keep it to the size of a single pointer.
Definition at line 127 of file DirectoryEntry.h.
Constructor & Destructor Documentation
MapEntryOptionalStorage() [1/2]
template<class RefTy > clang::FileMgr::MapEntryOptionalStorage< RefTy >::MapEntryOptionalStorage () inline
Definition at line 132 of file DirectoryEntry.h.
MapEntryOptionalStorage() [2/2]
template<class RefTy > template<class... ArgTypes> clang::FileMgr::MapEntryOptionalStorage< RefTy >::MapEntryOptionalStorage (std::in_place_t , ArgTypes &&... Args) inline explicit
Definition at line 135 of file DirectoryEntry.h.
Member Function Documentation
emplace()
template<class RefTy > template<class... Args> void clang::FileMgr::MapEntryOptionalStorage< RefTy >::emplace (Args &&... args) inline
Definition at line 155 of file DirectoryEntry.h.
has_value()
template<class RefTy > bool clang::FileMgr::MapEntryOptionalStorage< RefTy >::has_value () const inline
Definition at line 140 of file DirectoryEntry.h.
Referenced by clang::FileMgr::MapEntryOptionalStorage< RefTy >::value(), clang::FileMgr::MapEntryOptionalStorage< RefTy >::value(), and clang::FileMgr::MapEntryOptionalStorage< RefTy >::value().
operator=()
template<class RefTy > MapEntryOptionalStorage & clang::FileMgr::MapEntryOptionalStorage< RefTy >::operator= (RefTy Ref) inline
Definition at line 159 of file DirectoryEntry.h.
reset()
template<class RefTy > void clang::FileMgr::MapEntryOptionalStorage< RefTy >::reset () inline
Definition at line 138 of file DirectoryEntry.h.
value() [1/3]
template<class RefTy > RefTy & clang::FileMgr::MapEntryOptionalStorage< RefTy >::value () & inline
Definition at line 142 of file DirectoryEntry.h.
References clang::FileMgr::MapEntryOptionalStorage< RefTy >::has_value().
value() [2/3]
template<class RefTy > RefTy && clang::FileMgr::MapEntryOptionalStorage< RefTy >::value () && inline
Definition at line 150 of file DirectoryEntry.h.
References clang::FileMgr::MapEntryOptionalStorage< RefTy >::has_value().
value() [3/3]
template<class RefTy > RefTy const & clang::FileMgr::MapEntryOptionalStorage< RefTy >::value () const & inline
Definition at line 146 of file DirectoryEntry.h.
References clang::FileMgr::MapEntryOptionalStorage< RefTy >::has_value().
The documentation for this class was generated from the following file:
include/clang/Basic/DirectoryEntry.h