clang: clang::LookupResult::Filter Class Reference
clang::LookupResult::Filter Class Reference
A class for iterating through a result set and possibly filtering out results.
#include "clang/Sema/Lookup.h"
Public Member Functions
Filter (Filter &&F)
Filter & operator= (Filter &&)=delete
Filter (const Filter &)=delete
Filter & operator= (const Filter &)=delete
~Filter ()
bool hasNext () const
NamedDecl * next ()
void restart ()
Restart the iteration.
void erase ()
Erase the last element returned from this iterator.
void replace (NamedDecl *D)
Replaces the current entry with the given one, preserving the access bits.
void replace (NamedDecl *D, AccessSpecifier AS)
Replaces the current entry with the given one.
void done ()
Friends
class LookupResult
Detailed Description
A class for iterating through a result set and possibly filtering out results.
The results returned are possibly sugared.
Definition at line 643 of file Lookup.h.
Constructor & Destructor Documentation
Filter() [1/2]
clang::LookupResult::Filter::Filter (Filter && F) inline
Definition at line 654 of file Lookup.h.
Filter() [2/2]
clang::LookupResult::Filter::Filter (const Filter &) delete
~Filter()
clang::LookupResult::Filter::~Filter () inline
Definition at line 669 of file Lookup.h.
Member Function Documentation
done()
void clang::LookupResult::Filter::done () inline
Definition at line 707 of file Lookup.h.
Referenced by clang::Sema::ActOnTag(), buildSingleCopyAssignRecursively(), clang::Sema::CheckDependentFunctionTemplateSpecialization(), clang::Sema::DiagnoseAmbiguousLookup(), clang::Sema::FilterAcceptableTemplateNames(), clang::Sema::FilterLookupForScope(), clang::Sema::FilterUsingLookup(), clang::Sema::getDestructorName(), clang::Sema::LookupLiteralOperator(), and RemoveUsingDecls().
erase()
void clang::LookupResult::Filter::erase () inline
Erase the last element returned from this iterator.
Definition at line 689 of file Lookup.h.
Referenced by clang::Sema::ActOnTag(), buildSingleCopyAssignRecursively(), clang::Sema::CheckDependentFunctionTemplateSpecialization(), clang::Sema::DiagnoseAmbiguousLookup(), clang::Sema::FilterAcceptableTemplateNames(), clang::Sema::FilterLookupForScope(), clang::Sema::FilterUsingLookup(), clang::Sema::getDestructorName(), clang::Sema::LookupLiteralOperator(), and RemoveUsingDecls().
hasNext()
bool clang::LookupResult::Filter::hasNext () const inline
Definition at line 674 of file Lookup.h.
Referenced by clang::Sema::ActOnTag(), buildSingleCopyAssignRecursively(), clang::Sema::CheckDependentFunctionTemplateSpecialization(), clang::Sema::DiagnoseAmbiguousLookup(), clang::Sema::FilterAcceptableTemplateNames(), clang::Sema::FilterLookupForScope(), clang::Sema::FilterUsingLookup(), clang::Sema::getDestructorName(), clang::Sema::LookupLiteralOperator(), and RemoveUsingDecls().
next()
NamedDecl * clang::LookupResult::Filter::next () inline
Definition at line 678 of file Lookup.h.
Referenced by clang::Sema::ActOnTag(), buildSingleCopyAssignRecursively(), clang::Sema::CheckDependentFunctionTemplateSpecialization(), clang::Sema::DiagnoseAmbiguousLookup(), clang::Sema::FilterAcceptableTemplateNames(), clang::Sema::FilterLookupForScope(), clang::Sema::FilterUsingLookup(), clang::Sema::getDestructorName(), clang::Sema::LookupLiteralOperator(), and RemoveUsingDecls().
operator=() [1/2]
Filter & clang::LookupResult::Filter::operator= (const Filter &) delete
operator=() [2/2]
Filter & clang::LookupResult::Filter::operator= (Filter &&) delete
replace() [1/2]
void clang::LookupResult::Filter::replace (NamedDecl * D) inline
Replaces the current entry with the given one, preserving the access bits.
Definition at line 696 of file Lookup.h.
replace() [2/2]
void clang::LookupResult::Filter::replace (NamedDecl * D, AccessSpecifier AS) inline
Replaces the current entry with the given one.
Definition at line 702 of file Lookup.h.
restart()
void clang::LookupResult::Filter::restart () inline
Restart the iteration.
Definition at line 684 of file Lookup.h.
Referenced by clang::Sema::LookupLiteralOperator().
Friends And Related Symbol Documentation
LookupResult
friend class LookupResult friend
Definition at line 644 of file Lookup.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Lookup.h