clang: clang::ASTDeclWriter Class Reference
clang::ASTDeclWriter Class Reference
Public Member Functions
ASTDeclWriter (ASTWriter &Writer, ASTContext &Context, ASTWriter::RecordDataImpl &Record)
uint64_t Emit (Decl *D)
void Visit (Decl *D)
void VisitDecl (Decl *D)
void VisitPragmaCommentDecl (PragmaCommentDecl *D)
void VisitPragmaDetectMismatchDecl (PragmaDetectMismatchDecl *D)
void VisitTranslationUnitDecl (TranslationUnitDecl *D)
void VisitNamedDecl (NamedDecl *D)
void VisitLabelDecl (LabelDecl *LD)
void VisitNamespaceDecl (NamespaceDecl *D)
void VisitUsingDirectiveDecl (UsingDirectiveDecl *D)
void VisitNamespaceAliasDecl (NamespaceAliasDecl *D)
void VisitTypeDecl (TypeDecl *D)
void VisitTypedefNameDecl (TypedefNameDecl *D)
void VisitTypedefDecl (TypedefDecl *D)
void VisitTypeAliasDecl (TypeAliasDecl *D)
void VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl *D)
void VisitUnresolvedUsingIfExistsDecl (UnresolvedUsingIfExistsDecl *D)
void VisitTagDecl (TagDecl *D)
void VisitEnumDecl (EnumDecl *D)
void VisitRecordDecl (RecordDecl *D)
void VisitCXXRecordDecl (CXXRecordDecl *D)
void VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl *D)
void VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl *D)
void VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl *D)
void VisitVarTemplatePartialSpecializationDecl (VarTemplatePartialSpecializationDecl *D)
void VisitClassScopeFunctionSpecializationDecl (ClassScopeFunctionSpecializationDecl *D)
void VisitTemplateTypeParmDecl (TemplateTypeParmDecl *D)
void VisitValueDecl (ValueDecl *D)
void VisitEnumConstantDecl (EnumConstantDecl *D)
void VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl *D)
void VisitDeclaratorDecl (DeclaratorDecl *D)
void VisitFunctionDecl (FunctionDecl *D)
void VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl *D)
void VisitCXXMethodDecl (CXXMethodDecl *D)
void VisitCXXConstructorDecl (CXXConstructorDecl *D)
void VisitCXXDestructorDecl (CXXDestructorDecl *D)
void VisitCXXConversionDecl (CXXConversionDecl *D)
void VisitFieldDecl (FieldDecl *D)
void VisitMSPropertyDecl (MSPropertyDecl *D)
void VisitMSGuidDecl (MSGuidDecl *D)
void VisitUnnamedGlobalConstantDecl (UnnamedGlobalConstantDecl *D)
void VisitTemplateParamObjectDecl (TemplateParamObjectDecl *D)
void VisitIndirectFieldDecl (IndirectFieldDecl *D)
void VisitVarDecl (VarDecl *D)
void VisitImplicitParamDecl (ImplicitParamDecl *D)
void VisitParmVarDecl (ParmVarDecl *D)
void VisitDecompositionDecl (DecompositionDecl *D)
void VisitBindingDecl (BindingDecl *D)
void VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl *D)
void VisitTemplateDecl (TemplateDecl *D)
void VisitConceptDecl (ConceptDecl *D)
void VisitImplicitConceptSpecializationDecl (ImplicitConceptSpecializationDecl *D)
void VisitRequiresExprBodyDecl (RequiresExprBodyDecl *D)
void VisitRedeclarableTemplateDecl (RedeclarableTemplateDecl *D)
void VisitClassTemplateDecl (ClassTemplateDecl *D)
void VisitVarTemplateDecl (VarTemplateDecl *D)
void VisitFunctionTemplateDecl (FunctionTemplateDecl *D)
void VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl *D)
void VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl *D)
void VisitUsingDecl (UsingDecl *D)
void VisitUsingEnumDecl (UsingEnumDecl *D)
void VisitUsingPackDecl (UsingPackDecl *D)
void VisitUsingShadowDecl (UsingShadowDecl *D)
void VisitConstructorUsingShadowDecl (ConstructorUsingShadowDecl *D)
void VisitLinkageSpecDecl (LinkageSpecDecl *D)
void VisitExportDecl (ExportDecl *D)
void VisitFileScopeAsmDecl (FileScopeAsmDecl *D)
void VisitTopLevelStmtDecl (TopLevelStmtDecl *D)
void VisitImportDecl (ImportDecl *D)
void VisitAccessSpecDecl (AccessSpecDecl *D)
void VisitFriendDecl (FriendDecl *D)
void VisitFriendTemplateDecl (FriendTemplateDecl *D)
void VisitStaticAssertDecl (StaticAssertDecl *D)
void VisitBlockDecl (BlockDecl *D)
void VisitCapturedDecl (CapturedDecl *D)
void VisitEmptyDecl (EmptyDecl *D)
void VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl *D)
void VisitDeclContext (DeclContext *DC)
Emit the DeclContext part of a declaration context decl.
template<typename T >
void VisitRedeclarable (Redeclarable< T > *D)
void VisitHLSLBufferDecl (HLSLBufferDecl *D)
void VisitObjCMethodDecl (ObjCMethodDecl *D)
void VisitObjCTypeParamDecl (ObjCTypeParamDecl *D)
void VisitObjCContainerDecl (ObjCContainerDecl *D)
void VisitObjCInterfaceDecl (ObjCInterfaceDecl *D)
void VisitObjCIvarDecl (ObjCIvarDecl *D)
void VisitObjCProtocolDecl (ObjCProtocolDecl *D)
void VisitObjCAtDefsFieldDecl (ObjCAtDefsFieldDecl *D)
void VisitObjCCategoryDecl (ObjCCategoryDecl *D)
void VisitObjCImplDecl (ObjCImplDecl *D)
void VisitObjCCategoryImplDecl (ObjCCategoryImplDecl *D)
void VisitObjCImplementationDecl (ObjCImplementationDecl *D)
void VisitObjCCompatibleAliasDecl (ObjCCompatibleAliasDecl *D)
void VisitObjCPropertyDecl (ObjCPropertyDecl *D)
void VisitObjCPropertyImplDecl (ObjCPropertyImplDecl *D)
void VisitOMPThreadPrivateDecl (OMPThreadPrivateDecl *D)
void VisitOMPAllocateDecl (OMPAllocateDecl *D)
void VisitOMPRequiresDecl (OMPRequiresDecl *D)
void VisitOMPDeclareReductionDecl (OMPDeclareReductionDecl *D)
void VisitOMPDeclareMapperDecl (OMPDeclareMapperDecl *D)
void VisitOMPCapturedExprDecl (OMPCapturedExprDecl *D)
void AddObjCTypeParamList (ObjCTypeParamList *typeParams)
Add an Objective-C type parameter list to the given record.
void AddFirstDeclFromEachModule (const Decl *D, bool IncludeLocal)
Add to the record the first declaration from each module file that provides a declaration of D.
template<typename EntryType >
RedeclarableTemplateDecl::SpecEntryTraits< EntryType >::DeclType * getSpecializationDecl (EntryType &T)
Get the specialization decl from an entry in the specialization list.
template<typename T >
decltype(T::PartialSpecializations) & getPartialSpecializations (T *Common)
Get the list of partial specializations from a template's common ptr.
ArrayRef< Decl > getPartialSpecializations (FunctionTemplateDecl::Common *)
template<typename DeclTy >
void AddTemplateSpecializations (DeclTy *D)
void RegisterTemplateSpecialization (const Decl *Template, const Decl *Specialization)
Ensure that this template specialization is associated with the specified template on reload.
Public Member Functions inherited from clang::declvisitor::Base< std::add_pointer, ASTDeclWriter, void >
void Visit (PTR(Decl) D)
void VisitDecl (PTR(Decl) D)
Detailed Description
Definition at line 35 of file ASTWriterDecl.cpp.
Constructor & Destructor Documentation
ASTDeclWriter()
clang::ASTDeclWriter::ASTDeclWriter (ASTWriter & Writer, ASTContext & Context, ASTWriter::RecordDataImpl & Record) inline
Definition at line 44 of file ASTWriterDecl.cpp.
Member Function Documentation
AddFirstDeclFromEachModule()
void clang::ASTDeclWriter::AddFirstDeclFromEachModule (const Decl * D, bool IncludeLocal) inline
Add to the record the first declaration from each module file that provides a declaration of D.
The intent is to provide a sufficient set such that reloading this set will load all current redeclarations.
Definition at line 183 of file ASTWriterDecl.cpp.
References clang::Decl::getMostRecentDecl(), clang::ASTReader::getOwningModuleFile(), and clang::Decl::getPreviousDecl().
Referenced by AddTemplateSpecializations(), and VisitRedeclarable().
AddObjCTypeParamList()
void clang::ASTDeclWriter::AddObjCTypeParamList (ObjCTypeParamList * typeParams) inline
Add an Objective-C type parameter list to the given record.
Definition at line 165 of file ASTWriterDecl.cpp.
References clang::ObjCTypeParamList::getLAngleLoc(), clang::ObjCTypeParamList::getRAngleLoc(), and clang::ObjCTypeParamList::size().
Referenced by VisitObjCCategoryDecl(), and VisitObjCInterfaceDecl().
AddTemplateSpecializations()
template<typename DeclTy > void clang::ASTDeclWriter::AddTemplateSpecializations (DeclTy * D) inline
Definition at line 213 of file ASTWriterDecl.cpp.
References AddFirstDeclFromEachModule(), clang::ASTContext::getExternalSource(), getPartialSpecializations(), and getSpecializationDecl().
Referenced by VisitClassTemplateDecl(), VisitFunctionTemplateDecl(), and VisitVarTemplateDecl().
Emit()
uint64_t clang::ASTDeclWriter::Emit (Decl * D) inline
Definition at line 49 of file ASTWriterDecl.cpp.
References clang::Decl::getDeclKindName().
getPartialSpecializations() [1/2]
ArrayRef< Decl > clang::ASTDeclWriter::getPartialSpecializations (FunctionTemplateDecl::Common *) inline
Definition at line 208 of file ASTWriterDecl.cpp.
getPartialSpecializations() [2/2]
template<typename T > decltype(T::PartialSpecializations) & clang::ASTDeclWriter::getPartialSpecializations (T * Common) inline
Get the list of partial specializations from a template's common ptr.
Definition at line 205 of file ASTWriterDecl.cpp.
Referenced by AddTemplateSpecializations().
getSpecializationDecl()
template<typename EntryType > RedeclarableTemplateDecl::SpecEntryTraits< EntryType >::DeclType * clang::ASTDeclWriter::getSpecializationDecl (EntryType & T) inline
Get the specialization decl from an entry in the specialization list.
Definition at line 199 of file ASTWriterDecl.cpp.
References clang::RedeclarableTemplateDecl::SpecEntryTraits< EntryType >::getDecl().
Referenced by AddTemplateSpecializations().
RegisterTemplateSpecialization()
void clang::ASTDeclWriter::RegisterTemplateSpecialization (const Decl * Template, const Decl * Specialization) inline
Ensure that this template specialization is associated with the specified template on reload.
Definition at line 253 of file ASTWriterDecl.cpp.
References clang::Decl::getCanonicalDecl(), clang::ASTWriter::getFirstLocalDecl(), clang::Decl::isFromASTFile(), clang::Specialization, and clang::serialization::UPD_CXX_ADDED_TEMPLATE_SPECIALIZATION.
Referenced by VisitClassTemplateSpecializationDecl(), VisitFunctionDecl(), and VisitVarTemplateSpecializationDecl().
Visit()
void ASTDeclWriter::Visit (Decl * D)
Definition at line 275 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddFunctionDefinition(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeLoc(), clang::ASTRecordWriter::AddVarDeclInit(), clang::ASTRecordWriter::push_back(), clang::declvisitor::Base< std::add_pointer, ImplClass, void >::Visit(), and VisitDeclContext().
VisitAccessSpecDecl()
void ASTDeclWriter::VisitAccessSpecDecl (AccessSpecDecl * D)
Definition at line 1547 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_ACCESS_SPEC, clang::AccessSpecDecl::getColonLoc(), and VisitDecl().
VisitBindingDecl()
void ASTDeclWriter::VisitBindingDecl (BindingDecl * D)
Definition at line 1211 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_BINDING, clang::BindingDecl::getBinding(), and VisitValueDecl().
VisitBlockDecl()
void ASTDeclWriter::VisitBlockDecl (BlockDecl * D)
Definition at line 1246 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::BlockDecl::blockMissingReturnType(), clang::BlockDecl::canAvoidCopyToHeap(), clang::BlockDecl::captures(), clang::BlockDecl::capturesCXXThis(), clang::serialization::DECL_BLOCK, clang::BlockDecl::doesNotEscape(), clang::BlockDecl::getBody(), clang::BlockDecl::getNumCaptures(), clang::BlockDecl::getSignatureAsWritten(), clang::BlockDecl::isConversionFromLambda(), clang::BlockDecl::isVariadic(), P, clang::BlockDecl::param_size(), clang::BlockDecl::parameters(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitCapturedDecl()
void ASTDeclWriter::VisitCapturedDecl (CapturedDecl * D)
Definition at line 1275 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_CAPTURED, clang::CapturedDecl::getContextParamPosition(), clang::CapturedDecl::getNumParams(), clang::CapturedDecl::getParam(), clang::CapturedDecl::isNothrow(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitClassScopeFunctionSpecializationDecl()
void ASTDeclWriter::VisitClassScopeFunctionSpecializationDecl (ClassScopeFunctionSpecializationDecl * D)
Definition at line 1749 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_CLASS_SCOPE_FUNCTION_SPECIALIZATION, clang::ClassScopeFunctionSpecializationDecl::getSpecialization(), clang::ClassScopeFunctionSpecializationDecl::getTemplateArgsAsWritten(), clang::ClassScopeFunctionSpecializationDecl::hasExplicitTemplateArgs(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitClassTemplateDecl()
void ASTDeclWriter::VisitClassTemplateDecl (ClassTemplateDecl * D)
Definition at line 1628 of file ASTWriterDecl.cpp.
References AddTemplateSpecializations(), clang::serialization::DECL_CLASS_TEMPLATE, clang::Redeclarable< decl_type >::isFirstDecl(), and VisitRedeclarableTemplateDecl().
VisitClassTemplatePartialSpecializationDecl()
void ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl * D)
Definition at line 1672 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::serialization::DECL_CLASS_TEMPLATE_PARTIAL_SPECIALIZATION, clang::ClassTemplatePartialSpecializationDecl::getInstantiatedFromMember(), clang::CXXRecordDecl::getPreviousDecl(), clang::ClassTemplatePartialSpecializationDecl::getTemplateArgsAsWritten(), clang::ClassTemplatePartialSpecializationDecl::getTemplateParameters(), clang::ClassTemplatePartialSpecializationDecl::isMemberSpecialization(), clang::ASTRecordWriter::push_back(), and VisitClassTemplateSpecializationDecl().
VisitClassTemplateSpecializationDecl()
void ASTDeclWriter::VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl * D)
Definition at line 1636 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateArgumentList(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_CLASS_TEMPLATE_SPECIALIZATION, clang::ClassTemplateDecl::getCanonicalDecl(), clang::ClassTemplateSpecializationDecl::getExternLoc(), clang::ClassTemplateSpecializationDecl::getPointOfInstantiation(), clang::ClassTemplateSpecializationDecl::getSpecializationKind(), clang::ClassTemplateSpecializationDecl::getSpecializedTemplate(), clang::ClassTemplateSpecializationDecl::getSpecializedTemplateOrPartial(), clang::ClassTemplateSpecializationDecl::getTemplateArgs(), clang::ClassTemplateSpecializationDecl::getTemplateInstantiationArgs(), clang::ClassTemplateSpecializationDecl::getTemplateKeywordLoc(), clang::ClassTemplateSpecializationDecl::getTypeAsWritten(), clang::Decl::isCanonicalDecl(), clang::ASTRecordWriter::push_back(), RegisterTemplateSpecialization(), and VisitCXXRecordDecl().
Referenced by VisitClassTemplatePartialSpecializationDecl().
VisitConceptDecl()
void ASTDeclWriter::VisitConceptDecl (ConceptDecl * D)
Definition at line 1593 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_CONCEPT, clang::ConceptDecl::getConstraintExpr(), and VisitTemplateDecl().
VisitConstructorUsingShadowDecl()
void ASTDeclWriter::VisitConstructorUsingShadowDecl (ConstructorUsingShadowDecl * D)
Definition at line 1388 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_CONSTRUCTOR_USING_SHADOW, clang::ASTRecordWriter::push_back(), and VisitUsingShadowDecl().
VisitCXXConstructorDecl()
void ASTDeclWriter::VisitCXXConstructorDecl (CXXConstructorDecl * D)
Definition at line 1497 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), addExplicitSpecifier(), clang::serialization::DECL_CXX_CONSTRUCTOR, clang::CXXConstructorDecl::getExplicitSpecifier(), clang::CXXConstructorDecl::getInheritedConstructor(), clang::ASTRecordWriter::push_back(), and VisitCXXMethodDecl().
VisitCXXConversionDecl()
void ASTDeclWriter::VisitCXXConversionDecl (CXXConversionDecl * D)
Definition at line 1523 of file ASTWriterDecl.cpp.
References addExplicitSpecifier(), clang::serialization::DECL_CXX_CONVERSION, clang::CXXConversionDecl::getExplicitSpecifier(), and VisitCXXMethodDecl().
VisitCXXDeductionGuideDecl()
void ASTDeclWriter::VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl * D)
Definition at line 729 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), addExplicitSpecifier(), clang::serialization::DECL_CXX_DEDUCTION_GUIDE, clang::CXXDeductionGuideDecl::getDeductionCandidateKind(), clang::CXXDeductionGuideDecl::getExplicitSpecifier(), clang::ASTRecordWriter::push_back(), and VisitFunctionDecl().
VisitCXXDestructorDecl()
void ASTDeclWriter::VisitCXXDestructorDecl (CXXDestructorDecl * D)
Definition at line 1513 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_CXX_DESTRUCTOR, clang::CXXDestructorDecl::getOperatorDelete(), clang::CXXDestructorDecl::getOperatorDeleteThisArg(), and VisitCXXMethodDecl().
VisitCXXMethodDecl()
void ASTDeclWriter::VisitCXXMethodDecl (CXXMethodDecl * D)
Definition at line 1474 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_CXX_METHOD, clang::Decl::getDeclContext(), clang::ASTWriter::getDeclCXXMethodAbbrev(), clang::NamedDecl::getDeclName(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::Decl::getLexicalDeclContext(), clang::CXXMethodDecl::getMostRecentDecl(), clang::DeclarationName::getNameKind(), clang::FunctionDecl::getTemplatedKind(), clang::Decl::hasAttrs(), clang::FunctionDecl::hasInheritedPrototype(), clang::FunctionDecl::hasWrittenPrototype(), clang::DeclarationName::Identifier, clang::Decl::isCanonicalDecl(), clang::Decl::isInvalidDecl(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::CXXMethodDecl::overridden_methods(), clang::ASTRecordWriter::push_back(), clang::CXXMethodDecl::size_overridden_methods(), clang::FunctionDecl::TK_NonTemplate, and VisitFunctionDecl().
Referenced by VisitCXXConstructorDecl(), VisitCXXConversionDecl(), and VisitCXXDestructorDecl().
VisitCXXRecordDecl()
void ASTDeclWriter::VisitCXXRecordDecl (CXXRecordDecl * D)
Definition at line 1431 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddCXXDefinitionData(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_CXX_RECORD, clang::ASTContext::getCurrentKeyFunction(), clang::CXXRecordDecl::getDescribedClassTemplate(), clang::CXXRecordDecl::getLambdaContextDecl(), clang::CXXRecordDecl::getLambdaIndexInContext(), clang::CXXRecordDecl::getMemberSpecializationInfo(), clang::TagDecl::isCompleteDefinition(), clang::CXXRecordDecl::isLambda(), clang::TagDecl::isThisDeclarationADefinition(), clang::ASTRecordWriter::push_back(), and VisitRecordDecl().
Referenced by VisitClassTemplateSpecializationDecl().
VisitDecl()
void ASTDeclWriter::VisitDecl (Decl * D)
Definition at line 324 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddAttributes(), clang::ASTRecordWriter::AddDeclRef(), clang::Decl::getAccess(), clang::Decl::getAttrs(), clang::Decl::getDeclContext(), clang::Decl::getLexicalDeclContext(), clang::Decl::getModuleOwnershipKind(), clang::Decl::getOwningModule(), clang::Decl::hasAttrs(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::Decl::isOutOfLine(), clang::Decl::isReferenced(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::Decl::isUsed(), and clang::ASTRecordWriter::push_back().
Referenced by VisitAccessSpecDecl(), VisitBlockDecl(), VisitCapturedDecl(), VisitClassScopeFunctionSpecializationDecl(), VisitEmptyDecl(), VisitExportDecl(), VisitFileScopeAsmDecl(), VisitFriendDecl(), VisitFriendTemplateDecl(), VisitImplicitConceptSpecializationDecl(), VisitImportDecl(), VisitLifetimeExtendedTemporaryDecl(), VisitLinkageSpecDecl(), VisitNamedDecl(), VisitObjCPropertyImplDecl(), VisitOMPAllocateDecl(), VisitOMPRequiresDecl(), VisitOMPThreadPrivateDecl(), VisitPragmaCommentDecl(), VisitPragmaDetectMismatchDecl(), VisitStaticAssertDecl(), and VisitTopLevelStmtDecl().
VisitDeclaratorDecl()
void ASTDeclWriter::VisitDeclaratorDecl (DeclaratorDecl * D)
Definition at line 568 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddQualifierInfo(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeRef(), clang::DeclaratorDecl::getInnerLocStart(), clang::TypeSourceInfo::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTRecordWriter::push_back(), and VisitValueDecl().
Referenced by VisitFieldDecl(), VisitFunctionDecl(), VisitMSPropertyDecl(), VisitNonTypeTemplateParmDecl(), and VisitVarDecl().
VisitDeclContext()
void ASTDeclWriter::VisitDeclContext (DeclContext * DC)
Emit the DeclContext part of a declaration context decl.
Definition at line 1877 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddOffset().
Referenced by Visit(), and VisitHLSLBufferDecl().
VisitDecompositionDecl()
void ASTDeclWriter::VisitDecompositionDecl (DecompositionDecl * D)
Definition at line 1201 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::DecompositionDecl::bindings(), clang::serialization::DECL_DECOMPOSITION, clang::ASTRecordWriter::push_back(), and VisitVarDecl().
VisitEmptyDecl()
void ASTDeclWriter::VisitEmptyDecl (EmptyDecl * D)
Definition at line 1230 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_EMPTY, and VisitDecl().
VisitEnumConstantDecl()
void ASTDeclWriter::VisitEnumConstantDecl (EnumConstantDecl * D)
Definition at line 558 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddAPSInt(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_ENUM_CONSTANT, clang::EnumConstantDecl::getInitExpr(), clang::EnumConstantDecl::getInitVal(), clang::ASTRecordWriter::push_back(), and VisitValueDecl().
VisitEnumDecl()
void ASTDeclWriter::VisitEnumDecl (EnumDecl * D)
Definition at line 463 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::AS_none, clang::CXXRecordDecl::classofKind(), clang::serialization::DECL_ENUM, clang::Decl::getAccess(), clang::Decl::getDeclContext(), clang::ASTWriter::getDeclEnumAbbrev(), clang::NamedDecl::getDeclName(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::EnumDecl::getIntegerType(), clang::EnumDecl::getIntegerTypeSourceInfo(), clang::Decl::getKind(), clang::Decl::getLexicalDeclContext(), clang::EnumDecl::getMemberSpecializationInfo(), clang::EnumDecl::getMostRecentDecl(), clang::DeclarationName::getNameKind(), clang::EnumDecl::getNumNegativeBits(), clang::EnumDecl::getNumPositiveBits(), clang::EnumDecl::getODRHash(), clang::EnumDecl::getPromotionType(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::Decl::hasAttrs(), clang::DeclarationName::Identifier, clang::EnumDecl::isFixed(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::Decl::isReferenced(), clang::EnumDecl::isScoped(), clang::EnumDecl::isScopedUsingClassTag(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::Decl::isUsed(), clang::serialization::needsAnonymousDeclarationNumber(), clang::ASTRecordWriter::push_back(), and VisitTagDecl().
VisitExportDecl()
void ASTDeclWriter::VisitExportDecl (ExportDecl * D)
Definition at line 1298 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_EXPORT, clang::ExportDecl::getRBraceLoc(), and VisitDecl().
VisitFieldDecl()
void ASTDeclWriter::VisitFieldDecl (FieldDecl * D)
Definition at line 980 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeRef(), clang::ObjCAtDefsFieldDecl::classofKind(), clang::ObjCIvarDecl::classofKind(), clang::serialization::DECL_FIELD, clang::FieldDecl::getBitWidth(), clang::FieldDecl::getCapturedVLAType(), clang::Decl::getDeclContext(), clang::ASTWriter::getDeclFieldAbbrev(), clang::NamedDecl::getDeclName(), clang::ASTContext::getInstantiatedFromUnnamedFieldDecl(), clang::Decl::getKind(), clang::Decl::getLexicalDeclContext(), clang::Decl::hasAttrs(), clang::FieldDecl::hasCapturedVLAType(), clang::FieldDecl::hasInClassInitializer(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::FieldDecl::isMutable(), clang::Decl::isReferenced(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::Decl::isUsed(), clang::ASTRecordWriter::push_back(), and VisitDeclaratorDecl().
Referenced by VisitObjCAtDefsFieldDecl(), and VisitObjCIvarDecl().
VisitFileScopeAsmDecl()
void ASTDeclWriter::VisitFileScopeAsmDecl (FileScopeAsmDecl * D)
Definition at line 1217 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_FILE_SCOPE_ASM, clang::FileScopeAsmDecl::getAsmString(), clang::FileScopeAsmDecl::getRParenLoc(), and VisitDecl().
VisitFriendDecl()
void ASTDeclWriter::VisitFriendDecl (FriendDecl * D)
Definition at line 1553 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_FRIEND, clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendType(), clang::FriendDecl::getFriendTypeTemplateParameterList(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitFriendTemplateDecl()
void ASTDeclWriter::VisitFriendTemplateDecl (FriendTemplateDecl * D)
Definition at line 1572 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_FRIEND_TEMPLATE, clang::FriendTemplateDecl::getFriendDecl(), clang::FriendTemplateDecl::getFriendLoc(), clang::FriendTemplateDecl::getFriendType(), clang::FriendTemplateDecl::getNumTemplateParameters(), clang::FriendTemplateDecl::getTemplateParameterList(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitFunctionDecl()
void ASTDeclWriter::VisitFunctionDecl (FunctionDecl * D)
Definition at line 582 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationNameLoc(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateArgumentList(), clang::ASTRecordWriter::AddTemplateArgumentLoc(), clang::serialization::DECL_FUNCTION, clang::FunctionDecl::FriendConstraintRefersToEnclosingTemplate(), clang::FunctionTemplateDecl::getCanonicalDecl(), clang::FunctionDecl::getConstexprKind(), clang::NamedDecl::getDeclName(), clang::FunctionDecl::getDefaultedFunctionInfo(), clang::FunctionDecl::getDefaultLoc(), clang::FunctionDecl::getDependentSpecializationInfo(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::Decl::getEndLoc(), clang::Decl::getIdentifierNamespace(), clang::MemberSpecializationInfo::getInstantiatedFrom(), clang::FunctionDecl::getInstantiatedFromDecl(), clang::DependentFunctionTemplateSpecializationInfo::getLAngleLoc(), clang::NamedDecl::getLinkageInternal(), clang::FunctionDecl::getMemberSpecializationInfo(), clang::FunctionTemplateSpecializationInfo::getMemberSpecializationInfo(), clang::DependentFunctionTemplateSpecializationInfo::getNumTemplateArgs(), clang::DependentFunctionTemplateSpecializationInfo::getNumTemplates(), clang::FunctionDecl::getODRHash(), clang::FunctionTemplateSpecializationInfo::getPointOfInstantiation(), clang::MemberSpecializationInfo::getPointOfInstantiation(), clang::DependentFunctionTemplateSpecializationInfo::getRAngleLoc(), clang::FunctionDecl::getStorageClass(), clang::DependentFunctionTemplateSpecializationInfo::getTemplate(), clang::FunctionTemplateSpecializationInfo::getTemplate(), clang::DependentFunctionTemplateSpecializationInfo::getTemplateArg(), clang::FunctionDecl::getTemplatedKind(), clang::FunctionDecl::getTemplateSpecializationInfo(), clang::FunctionTemplateSpecializationInfo::getTemplateSpecializationKind(), clang::MemberSpecializationInfo::getTemplateSpecializationKind(), clang::FunctionDecl::hasImplicitReturnZero(), clang::FunctionDecl::hasInheritedPrototype(), clang::FunctionDecl::hasSkippedBody(), clang::FunctionDecl::hasWrittenPrototype(), clang::Decl::isCanonicalDecl(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isExplicitlyDefaulted(), clang::FunctionDecl::isIneligibleOrNotSelected(), clang::FunctionDecl::isInlined(), clang::FunctionDecl::isInlineSpecified(), clang::FunctionDecl::isLateTemplateParsed(), clang::FunctionDecl::isMultiVersion(), clang::FunctionDecl::isPure(), clang::FunctionDecl::isTrivial(), clang::FunctionDecl::isTrivialForCall(), clang::FunctionDecl::isVirtualAsWritten(), clang::ASTTemplateArgumentListInfo::LAngleLoc, clang::ASTTemplateArgumentListInfo::NumTemplateArgs, P, clang::FunctionDecl::param_size(), clang::FunctionDecl::parameters(), clang::ASTRecordWriter::push_back(), clang::ASTTemplateArgumentListInfo::RAngleLoc, RegisterTemplateSpecialization(), clang::FunctionTemplateSpecializationInfo::TemplateArguments, clang::FunctionTemplateSpecializationInfo::TemplateArgumentsAsWritten, clang::FunctionDecl::TK_DependentFunctionTemplateSpecialization, clang::FunctionDecl::TK_DependentNonTemplate, clang::FunctionDecl::TK_FunctionTemplate, clang::FunctionDecl::TK_FunctionTemplateSpecialization, clang::FunctionDecl::TK_MemberSpecialization, clang::FunctionDecl::TK_NonTemplate, clang::FunctionDecl::usesSEHTry(), VisitDeclaratorDecl(), and VisitRedeclarable().
Referenced by VisitCXXDeductionGuideDecl(), and VisitCXXMethodDecl().
VisitFunctionTemplateDecl()
void ASTDeclWriter::VisitFunctionTemplateDecl (FunctionTemplateDecl * D)
Definition at line 1760 of file ASTWriterDecl.cpp.
References AddTemplateSpecializations(), clang::serialization::DECL_FUNCTION_TEMPLATE, clang::Redeclarable< decl_type >::isFirstDecl(), and VisitRedeclarableTemplateDecl().
VisitHLSLBufferDecl()
void ASTDeclWriter::VisitHLSLBufferDecl (HLSLBufferDecl * D)
Definition at line 1962 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_HLSL_BUFFER, clang::HLSLBufferDecl::getLBraceLoc(), clang::HLSLBufferDecl::getLocStart(), clang::HLSLBufferDecl::getRBraceLoc(), clang::HLSLBufferDecl::isCBuffer(), clang::ASTRecordWriter::push_back(), VisitDeclContext(), and VisitNamedDecl().
VisitImplicitConceptSpecializationDecl()
void ASTDeclWriter::VisitImplicitConceptSpecializationDecl (ImplicitConceptSpecializationDecl * D)
Definition at line 1599 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddTemplateArgument(), clang::serialization::DECL_IMPLICIT_CONCEPT_SPECIALIZATION, clang::ImplicitConceptSpecializationDecl::getTemplateArguments(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitImplicitParamDecl()
void ASTDeclWriter::VisitImplicitParamDecl (ImplicitParamDecl * D)
Definition at line 1149 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_IMPLICIT_PARAM, and VisitVarDecl().
VisitImportDecl()
void ASTDeclWriter::VisitImportDecl (ImportDecl * D)
Definition at line 1529 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_IMPORT, clang::Decl::getEndLoc(), clang::ImportDecl::getIdentifierLocs(), clang::ImportDecl::getImportedModule(), N, clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitIndirectFieldDecl()
void ASTDeclWriter::VisitIndirectFieldDecl (IndirectFieldDecl * D)
Definition at line 1043 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::IndirectFieldDecl::chain(), clang::serialization::DECL_INDIRECTFIELD, clang::IndirectFieldDecl::getChainingSize(), P, clang::ASTRecordWriter::push_back(), and VisitValueDecl().
VisitLabelDecl()
void ASTDeclWriter::VisitLabelDecl (LabelDecl * LD)
Definition at line 1304 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_LABEL, clang::Decl::getBeginLoc(), and VisitNamedDecl().
VisitLifetimeExtendedTemporaryDecl()
void ASTDeclWriter::VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl * D)
Definition at line 1235 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddAPValue(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_LIFETIME_EXTENDED_TEMPORARY, clang::LifetimeExtendedTemporaryDecl::getExtendingDecl(), clang::LifetimeExtendedTemporaryDecl::getManglingNumber(), clang::LifetimeExtendedTemporaryDecl::getTemporaryExpr(), clang::LifetimeExtendedTemporaryDecl::getValue(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitLinkageSpecDecl()
void ASTDeclWriter::VisitLinkageSpecDecl (LinkageSpecDecl * D)
Definition at line 1286 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_LINKAGE_SPEC, clang::LinkageSpecDecl::getExternLoc(), clang::LinkageSpecDecl::getLanguage(), clang::LinkageSpecDecl::getRBraceLoc(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitMSGuidDecl()
void ASTDeclWriter::VisitMSGuidDecl (MSGuidDecl * D)
Definition at line 1020 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::append(), clang::serialization::DECL_MS_GUID, clang::MSGuidDecl::getParts(), clang::MSGuidDeclParts::Part1, clang::MSGuidDeclParts::Part2, clang::MSGuidDeclParts::Part3, clang::MSGuidDeclParts::Part4And5, clang::ASTRecordWriter::push_back(), and VisitValueDecl().
VisitMSPropertyDecl()
void ASTDeclWriter::VisitMSPropertyDecl (MSPropertyDecl * D)
Definition at line 1013 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddIdentifierRef(), clang::serialization::DECL_MS_PROPERTY, clang::MSPropertyDecl::getGetterId(), clang::MSPropertyDecl::getSetterId(), and VisitDeclaratorDecl().
VisitNamedDecl()
void ASTDeclWriter::VisitNamedDecl (NamedDecl * D)
Definition at line 389 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationName(), clang::ASTWriter::getAnonymousDeclarationNumber(), clang::NamedDecl::getDeclName(), clang::serialization::needsAnonymousDeclarationNumber(), clang::ASTRecordWriter::push_back(), and VisitDecl().
Referenced by VisitHLSLBufferDecl(), VisitLabelDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCCompatibleAliasDecl(), VisitObjCContainerDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitTemplateDecl(), VisitTypeDecl(), VisitUnresolvedUsingIfExistsDecl(), VisitUsingDecl(), VisitUsingDirectiveDecl(), VisitUsingEnumDecl(), VisitUsingPackDecl(), VisitUsingShadowDecl(), and VisitValueDecl().
VisitNamespaceAliasDecl()
void ASTDeclWriter::VisitNamespaceAliasDecl (NamespaceAliasDecl * D)
Definition at line 1338 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_NAMESPACE_ALIAS, clang::NamespaceAliasDecl::getNamespace(), clang::NamespaceAliasDecl::getNamespaceLoc(), clang::NamespaceAliasDecl::getQualifierLoc(), clang::NamespaceAliasDecl::getTargetNameLoc(), VisitNamedDecl(), and VisitRedeclarable().
VisitNamespaceDecl()
void ASTDeclWriter::VisitNamespaceDecl (NamespaceDecl * D)
Definition at line 1311 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::cast(), clang::serialization::DECL_NAMESPACE, clang::NamespaceDecl::getAnonymousNamespace(), clang::NamespaceDecl::getBeginLoc(), clang::NamedDecl::getMostRecentDecl(), clang::DeclContext::getParent(), clang::DeclContext::getPrimaryContext(), clang::NamespaceDecl::getRBraceLoc(), clang::DeclContext::getRedeclContext(), clang::ASTWriter::hasChain(), clang::NamespaceDecl::isAnonymousNamespace(), clang::NamespaceDecl::isInline(), clang::NamespaceDecl::isNested(), clang::NamespaceDecl::isOriginalNamespace(), Parent, clang::ASTRecordWriter::push_back(), clang::serialization::UPD_CXX_ADDED_ANONYMOUS_NAMESPACE, VisitNamedDecl(), and VisitRedeclarable().
VisitNonTypeTemplateParmDecl()
void ASTDeclWriter::VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl * D)
Definition at line 1798 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_EXPANDED_NON_TYPE_TEMPLATE_PARM_PACK, clang::serialization::DECL_NON_TYPE_TEMPLATE_PARM, clang::NonTypeTemplateParmDecl::defaultArgumentWasInherited(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getExpansionType(), clang::NonTypeTemplateParmDecl::getExpansionTypeSourceInfo(), clang::NonTypeTemplateParmDecl::getNumExpansionTypes(), clang::NonTypeTemplateParmDecl::getPlaceholderTypeConstraint(), clang::NonTypeTemplateParmDecl::getPosition(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), clang::NonTypeTemplateParmDecl::isExpandedParameterPack(), clang::NonTypeTemplateParmDecl::isParameterPack(), N, clang::ASTRecordWriter::push_back(), and VisitDeclaratorDecl().
VisitObjCAtDefsFieldDecl()
void ASTDeclWriter::VisitObjCAtDefsFieldDecl (ObjCAtDefsFieldDecl * D)
Definition at line 893 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_OBJC_AT_DEFS_FIELD, and VisitFieldDecl().
VisitObjCCategoryDecl()
void ASTDeclWriter::VisitObjCCategoryDecl (ObjCCategoryDecl * D)
Definition at line 898 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), AddObjCTypeParamList(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_OBJC_CATEGORY, clang::ObjCCategoryDecl::getCategoryNameLoc(), clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCCategoryDecl::getIvarLBraceLoc(), clang::ObjCCategoryDecl::getIvarRBraceLoc(), clang::ObjCCategoryDecl::protocol_locs(), clang::ObjCCategoryDecl::protocol_size(), clang::ObjCCategoryDecl::protocols(), clang::ASTRecordWriter::push_back(), and VisitObjCContainerDecl().
VisitObjCCategoryImplDecl()
void ASTDeclWriter::VisitObjCCategoryImplDecl (ObjCCategoryImplDecl * D)
Definition at line 946 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_OBJC_CATEGORY_IMPL, clang::ObjCCategoryImplDecl::getCategoryNameLoc(), and VisitObjCImplDecl().
VisitObjCCompatibleAliasDecl()
void ASTDeclWriter::VisitObjCCompatibleAliasDecl (ObjCCompatibleAliasDecl * D)
Definition at line 913 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_OBJC_COMPATIBLE_ALIAS, clang::ObjCCompatibleAliasDecl::getClassInterface(), and VisitNamedDecl().
VisitObjCContainerDecl()
void ASTDeclWriter::VisitObjCContainerDecl (ObjCContainerDecl * D)
Definition at line 799 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddSourceRange(), clang::ObjCContainerDecl::getAtEndRange(), clang::ObjCContainerDecl::getAtStartLoc(), and VisitNamedDecl().
Referenced by VisitObjCCategoryDecl(), VisitObjCImplDecl(), VisitObjCInterfaceDecl(), and VisitObjCProtocolDecl().
VisitObjCImplDecl()
void ASTDeclWriter::VisitObjCImplDecl (ObjCImplDecl * D)
Definition at line 940 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ObjCImplDecl::getClassInterface(), and VisitObjCContainerDecl().
Referenced by VisitObjCCategoryImplDecl(), and VisitObjCImplementationDecl().
VisitObjCImplementationDecl()
void ASTDeclWriter::VisitObjCImplementationDecl (ObjCImplementationDecl * D)
Definition at line 952 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddCXXCtorInitializers(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_OBJC_IMPLEMENTATION, clang::ObjCImplementationDecl::getIvarLBraceLoc(), clang::ObjCImplementationDecl::getIvarRBraceLoc(), clang::ObjCImplementationDecl::getSuperClass(), clang::ObjCImplementationDecl::getSuperClassLoc(), clang::ObjCImplementationDecl::hasDestructors(), clang::ObjCImplementationDecl::hasNonZeroConstructors(), clang::ObjCImplementationDecl::init_begin(), clang::ObjCImplementationDecl::init_end(), clang::ASTRecordWriter::push_back(), and VisitObjCImplDecl().
VisitObjCInterfaceDecl()
void ASTDeclWriter::VisitObjCInterfaceDecl (ObjCInterfaceDecl * D)
Definition at line 810 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), AddObjCTypeParamList(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), Data, clang::serialization::DECL_OBJC_INTERFACE, clang::ObjCInterfaceDecl::getCategoryListRaw(), clang::ASTWriter::GetDeclRef(), clang::ObjCInterfaceDecl::getEndOfDefinitionLoc(), clang::ObjCInterfaceDecl::getODRHash(), clang::ObjCInterfaceDecl::getSuperClassTInfo(), clang::ObjCInterfaceDecl::getTypeForDecl(), clang::ObjCInterfaceDecl::isThisDeclarationADefinition(), P, clang::ObjCInterfaceDecl::protocol_locs(), clang::ObjCInterfaceDecl::protocols(), clang::ASTRecordWriter::push_back(), VisitObjCContainerDecl(), and VisitRedeclarable().
VisitObjCIvarDecl()
void ASTDeclWriter::VisitObjCIvarDecl (ObjCIvarDecl * D)
Definition at line 855 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_OBJC_IVAR, clang::ObjCIvarDecl::getAccessControl(), clang::FieldDecl::getBitWidth(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTWriter::getDeclObjCIvarAbbrev(), clang::Decl::getLexicalDeclContext(), clang::ObjCIvarDecl::getSynthesize(), clang::Decl::hasAttrs(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::Decl::isReferenced(), clang::Decl::isUsed(), clang::ASTRecordWriter::push_back(), and VisitFieldDecl().
VisitObjCMethodDecl()
void ASTDeclWriter::VisitObjCMethodDecl (ObjCMethodDecl * D)
Definition at line 737 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_OBJC_METHOD, clang::ObjCMethodDecl::getBody(), clang::ObjCMethodDecl::getCmdDecl(), clang::ObjCMethodDecl::getEndLoc(), clang::ObjCMethodDecl::getImplementationControl(), clang::ObjCMethodDecl::getObjCDeclQualifier(), clang::ASTContext::getObjCMethodRedeclaration(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getReturnTypeSourceInfo(), clang::ObjCMethodDecl::getSelfDecl(), clang::ObjCMethodDecl::hasRedeclaration(), clang::ObjCMethodDecl::hasRelatedResultType(), clang::ObjCMethodDecl::hasSkippedBody(), clang::ObjCMethodDecl::isDefined(), clang::ObjCMethodDecl::isInstanceMethod(), clang::ObjCMethodDecl::isOverriding(), clang::ObjCMethodDecl::isPropertyAccessor(), clang::ObjCMethodDecl::isRedeclaration(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::ObjCMethodDecl::isVariadic(), P, clang::ObjCMethodDecl::param_size(), clang::ObjCMethodDecl::parameters(), clang::ASTRecordWriter::push_back(), and VisitNamedDecl().
VisitObjCPropertyDecl()
void ASTDeclWriter::VisitObjCPropertyDecl (ObjCPropertyDecl * D)
Definition at line 919 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationName(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_OBJC_PROPERTY, clang::ObjCPropertyDecl::getAtLoc(), clang::ObjCPropertyDecl::getGetterMethodDecl(), clang::ObjCPropertyDecl::getGetterName(), clang::ObjCPropertyDecl::getGetterNameLoc(), clang::ObjCPropertyDecl::getLParenLoc(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyDecl::getPropertyAttributesAsWritten(), clang::ObjCPropertyDecl::getPropertyImplementation(), clang::ObjCPropertyDecl::getPropertyIvarDecl(), clang::ObjCPropertyDecl::getSetterMethodDecl(), clang::ObjCPropertyDecl::getSetterName(), clang::ObjCPropertyDecl::getSetterNameLoc(), clang::ObjCPropertyDecl::getType(), clang::ObjCPropertyDecl::getTypeSourceInfo(), clang::ASTRecordWriter::push_back(), and VisitNamedDecl().
VisitObjCPropertyImplDecl()
void ASTDeclWriter::VisitObjCPropertyImplDecl (ObjCPropertyImplDecl * D)
Definition at line 967 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_OBJC_PROPERTY_IMPL, clang::ObjCPropertyImplDecl::getBeginLoc(), clang::ObjCPropertyImplDecl::getGetterCXXConstructor(), clang::ObjCPropertyImplDecl::getGetterMethodDecl(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::ObjCPropertyImplDecl::getPropertyIvarDeclLoc(), clang::ObjCPropertyImplDecl::getSetterCXXAssignment(), clang::ObjCPropertyImplDecl::getSetterMethodDecl(), and VisitDecl().
VisitObjCProtocolDecl()
void ASTDeclWriter::VisitObjCProtocolDecl (ObjCProtocolDecl * D)
Definition at line 876 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_OBJC_PROTOCOL, clang::ObjCProtocolDecl::getODRHash(), clang::ObjCProtocolDecl::isThisDeclarationADefinition(), clang::ObjCProtocolDecl::protocol_locs(), clang::ObjCProtocolDecl::protocol_size(), clang::ObjCProtocolDecl::protocols(), clang::ASTRecordWriter::push_back(), VisitObjCContainerDecl(), and VisitRedeclarable().
VisitObjCTypeParamDecl()
void ASTDeclWriter::VisitObjCTypeParamDecl (ObjCTypeParamDecl * D)
Definition at line 789 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_OBJC_TYPE_PARAM, clang::ASTRecordWriter::push_back(), and VisitTypedefNameDecl().
VisitOMPAllocateDecl()
void ASTDeclWriter::VisitOMPAllocateDecl (OMPAllocateDecl * D)
Definition at line 1979 of file ASTWriterDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::serialization::DECL_OMP_ALLOCATE, VisitDecl(), and clang::ASTRecordWriter::writeOMPChildren().
VisitOMPCapturedExprDecl()
void ASTDeclWriter::VisitOMPCapturedExprDecl (OMPCapturedExprDecl * D)
Definition at line 2017 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_OMP_CAPTUREDEXPR, and VisitVarDecl().
VisitOMPDeclareMapperDecl()
void ASTDeclWriter::VisitOMPDeclareMapperDecl (OMPDeclareMapperDecl * D)
Definition at line 2009 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationName(), clang::ASTRecordWriter::AddDeclRef(), clang::OMPDeclarativeDirective< U >::Data, clang::serialization::DECL_OMP_DECLARE_MAPPER, clang::OMPDeclareMapperDecl::getPrevDeclInScope(), clang::OMPDeclareMapperDecl::getVarName(), VisitValueDecl(), and clang::ASTRecordWriter::writeOMPChildren().
VisitOMPDeclareReductionDecl()
void ASTDeclWriter::VisitOMPDeclareReductionDecl (OMPDeclareReductionDecl * D)
Definition at line 1991 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_OMP_DECLARE_REDUCTION, clang::Decl::getBeginLoc(), clang::OMPDeclareReductionDecl::getCombiner(), clang::OMPDeclareReductionDecl::getCombinerIn(), clang::OMPDeclareReductionDecl::getCombinerOut(), clang::OMPDeclareReductionDecl::getInitializer(), clang::OMPDeclareReductionDecl::getInitializerKind(), clang::OMPDeclareReductionDecl::getInitOrig(), clang::OMPDeclareReductionDecl::getInitPriv(), clang::OMPDeclareReductionDecl::getPrevDeclInScope(), clang::ASTRecordWriter::push_back(), and VisitValueDecl().
VisitOMPRequiresDecl()
void ASTDeclWriter::VisitOMPRequiresDecl (OMPRequiresDecl * D)
Definition at line 1985 of file ASTWriterDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::serialization::DECL_OMP_REQUIRES, VisitDecl(), and clang::ASTRecordWriter::writeOMPChildren().
VisitOMPThreadPrivateDecl()
void ASTDeclWriter::VisitOMPThreadPrivateDecl (OMPThreadPrivateDecl * D)
Definition at line 1973 of file ASTWriterDecl.cpp.
References clang::OMPDeclarativeDirective< U >::Data, clang::serialization::DECL_OMP_THREADPRIVATE, VisitDecl(), and clang::ASTRecordWriter::writeOMPChildren().
VisitParmVarDecl()
void ASTDeclWriter::VisitParmVarDecl (ParmVarDecl * D)
Definition at line 1154 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddStmt(), clang::AS_none, clang::VarDecl::CInit, clang::serialization::DECL_PARM_VAR, clang::Decl::getAccess(), clang::Decl::getDeclContext(), clang::ASTWriter::getDeclParmVarAbbrev(), clang::ParmVarDecl::getFunctionScopeDepth(), clang::ParmVarDecl::getFunctionScopeIndex(), clang::VarDecl::getInit(), clang::VarDecl::getInitStyle(), clang::Decl::getLexicalDeclContext(), clang::ParmVarDecl::getObjCDeclQualifier(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::VarDecl::getStorageClass(), clang::VarDecl::getTSCSpec(), clang::ParmVarDecl::getUninstantiatedDefaultArg(), clang::Decl::hasAttrs(), clang::ParmVarDecl::hasInheritedDefaultArg(), clang::ParmVarDecl::hasUninstantiatedDefaultArg(), clang::VarDecl::isExceptionVariable(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::ParmVarDecl::isKNRPromoted(), clang::NamedDecl::isModulePrivate(), clang::ParmVarDecl::isObjCMethodParameter(), clang::Decl::isReferenced(), clang::VarDecl::isStaticDataMember(), clang::VarDecl::isThisDeclarationADemotedDefinition(), clang::Decl::isUsed(), clang::ASTRecordWriter::push_back(), and VisitVarDecl().
VisitPragmaCommentDecl()
void ASTDeclWriter::VisitPragmaCommentDecl (PragmaCommentDecl * D)
Definition at line 363 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddString(), clang::serialization::DECL_PRAGMA_COMMENT, clang::PragmaCommentDecl::getArg(), clang::Decl::getBeginLoc(), clang::PragmaCommentDecl::getCommentKind(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitPragmaDetectMismatchDecl()
void ASTDeclWriter::VisitPragmaDetectMismatchDecl (PragmaDetectMismatchDecl * D)
Definition at line 373 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddString(), clang::serialization::DECL_PRAGMA_DETECT_MISMATCH, clang::Decl::getBeginLoc(), clang::PragmaDetectMismatchDecl::getName(), clang::PragmaDetectMismatchDecl::getValue(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitRecordDecl()
void ASTDeclWriter::VisitRecordDecl (RecordDecl * D)
Definition at line 510 of file ASTWriterDecl.cpp.
References clang::AS_none, clang::CXXRecordDecl::classofKind(), clang::serialization::DECL_RECORD, clang::Decl::getAccess(), clang::RecordDecl::getArgPassingRestrictions(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTWriter::getDeclRecordAbbrev(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::Decl::getKind(), clang::Decl::getLexicalDeclContext(), clang::RecordDecl::getMostRecentDecl(), clang::DeclarationName::getNameKind(), clang::RecordDecl::getODRHash(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::Decl::hasAttrs(), clang::RecordDecl::hasFlexibleArrayMember(), clang::RecordDecl::hasNonTrivialToPrimitiveCopyCUnion(), clang::RecordDecl::hasNonTrivialToPrimitiveDefaultInitializeCUnion(), clang::RecordDecl::hasNonTrivialToPrimitiveDestructCUnion(), clang::RecordDecl::hasObjectMember(), clang::RecordDecl::hasVolatileMember(), clang::DeclarationName::Identifier, clang::RecordDecl::isAnonymousStructOrUnion(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::RecordDecl::isNonTrivialToPrimitiveCopy(), clang::RecordDecl::isNonTrivialToPrimitiveDefaultInitialize(), clang::RecordDecl::isNonTrivialToPrimitiveDestroy(), clang::RecordDecl::isParamDestroyedInCallee(), clang::Decl::isReferenced(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::Decl::isUsed(), clang::serialization::needsAnonymousDeclarationNumber(), clang::ASTRecordWriter::push_back(), and VisitTagDecl().
Referenced by VisitCXXRecordDecl().
VisitRedeclarable()
template<typename T > void ASTDeclWriter::VisitRedeclarable (Redeclarable< T > * D)
Definition at line 1904 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), AddFirstDeclFromEachModule(), clang::ASTRecordWriter::AddOffset(), clang::ASTRecordWriter::Emit(), clang::First, clang::ASTWriter::GetDeclRef(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::ASTWriter::getFirstLocalDecl(), clang::Decl::getMostRecentDecl(), clang::Decl::getPreviousDecl(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::serialization::isRedeclarableDeclKind(), clang::serialization::LOCAL_REDECLARATIONS, clang::ASTRecordWriter::push_back(), and clang::ASTRecordWriter::size().
Referenced by VisitFunctionDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCInterfaceDecl(), VisitObjCProtocolDecl(), VisitRedeclarableTemplateDecl(), VisitTagDecl(), VisitTypedefNameDecl(), VisitUsingShadowDecl(), and VisitVarDecl().
VisitRedeclarableTemplateDecl()
void ASTDeclWriter::VisitRedeclarableTemplateDecl (RedeclarableTemplateDecl * D)
Definition at line 1612 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::Decl::getIdentifierNamespace(), clang::RedeclarableTemplateDecl::getInstantiatedFromMemberTemplate(), clang::Redeclarable< decl_type >::isFirstDecl(), clang::RedeclarableTemplateDecl::isMemberSpecialization(), clang::ASTRecordWriter::push_back(), VisitRedeclarable(), and VisitTemplateDecl().
Referenced by VisitClassTemplateDecl(), VisitFunctionTemplateDecl(), VisitTypeAliasTemplateDecl(), and VisitVarTemplateDecl().
VisitRequiresExprBodyDecl()
void ASTDeclWriter::VisitRequiresExprBodyDecl (RequiresExprBodyDecl * D)
Definition at line 1608 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_REQUIRES_EXPR_BODY.
VisitStaticAssertDecl()
void ASTDeclWriter::VisitStaticAssertDecl (StaticAssertDecl * D)
Definition at line 1867 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_STATIC_ASSERT, clang::StaticAssertDecl::getAssertExpr(), clang::StaticAssertDecl::getMessage(), clang::StaticAssertDecl::getRParenLoc(), clang::StaticAssertDecl::isFailed(), clang::ASTRecordWriter::push_back(), and VisitDecl().
VisitTagDecl()
void ASTDeclWriter::VisitTagDecl (TagDecl * D)
Definition at line 435 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddIdentifierRef(), clang::ASTRecordWriter::AddQualifierInfo(), clang::ASTRecordWriter::AddSourceRange(), clang::TagDecl::getBraceRange(), clang::Decl::getIdentifierNamespace(), clang::TagDecl::getTagKind(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::TagDecl::isCompleteDefinition(), clang::TagDecl::isCompleteDefinitionRequired(), clang::TagDecl::isEmbeddedInDeclarator(), clang::TagDecl::isFreeStanding(), clang::ASTRecordWriter::push_back(), VisitRedeclarable(), and VisitTypeDecl().
Referenced by VisitEnumDecl(), and VisitRecordDecl().
VisitTemplateDecl()
void ASTDeclWriter::VisitTemplateDecl (TemplateDecl * D)
Definition at line 1586 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::TemplateDecl::getTemplatedDecl(), clang::TemplateDecl::getTemplateParameters(), and VisitNamedDecl().
Referenced by VisitConceptDecl(), VisitRedeclarableTemplateDecl(), and VisitTemplateTemplateParmDecl().
VisitTemplateParamObjectDecl()
void ASTDeclWriter::VisitTemplateParamObjectDecl (TemplateParamObjectDecl * D)
Definition at line 1037 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddAPValue(), clang::serialization::DECL_TEMPLATE_PARAM_OBJECT, clang::TemplateParamObjectDecl::getValue(), and VisitValueDecl().
VisitTemplateTemplateParmDecl()
void ASTDeclWriter::VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl * D)
Definition at line 1833 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddTemplateArgumentLoc(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::serialization::DECL_EXPANDED_TEMPLATE_TEMPLATE_PARM_PACK, clang::serialization::DECL_TEMPLATE_TEMPLATE_PARM, clang::TemplateTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::TemplateTemplateParmDecl::getDepth(), clang::TemplateTemplateParmDecl::getExpansionTemplateParameters(), clang::TemplateTemplateParmDecl::getNumExpansionTemplateParameters(), clang::TemplateTemplateParmDecl::getPosition(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), clang::TemplateTemplateParmDecl::isExpandedParameterPack(), clang::TemplateTemplateParmDecl::isParameterPack(), N, clang::ASTRecordWriter::push_back(), and VisitTemplateDecl().
VisitTemplateTypeParmDecl()
void ASTDeclWriter::VisitTemplateTypeParmDecl (TemplateTypeParmDecl * D)
Definition at line 1768 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), clang::ASTRecordWriter::AddDeclarationNameInfo(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_TEMPLATE_TYPE_PARM, clang::TemplateTypeParmDecl::defaultArgumentWasInherited(), clang::ConceptReference::getConceptNameInfo(), clang::TemplateTypeParmDecl::getDefaultArgumentInfo(), clang::TypeConstraint::getImmediatelyDeclaredConstraint(), clang::ConceptReference::getNamedConcept(), clang::ConceptReference::getNestedNameSpecifierLoc(), clang::TemplateTypeParmDecl::getNumExpansionParameters(), clang::ConceptReference::getTemplateArgsAsWritten(), clang::TemplateTypeParmDecl::getTypeConstraint(), clang::TemplateTypeParmDecl::hasDefaultArgument(), clang::TemplateTypeParmDecl::hasTypeConstraint(), clang::TemplateTypeParmDecl::isExpandedParameterPack(), clang::ASTRecordWriter::push_back(), VisitTypeDecl(), and clang::TemplateTypeParmDecl::wasDeclaredWithTypename().
VisitTopLevelStmtDecl()
void ASTDeclWriter::VisitTopLevelStmtDecl (TopLevelStmtDecl * D)
Definition at line 1224 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddStmt(), clang::serialization::DECL_TOP_LEVEL_STMT_DECL, clang::TopLevelStmtDecl::getStmt(), and VisitDecl().
VisitTranslationUnitDecl()
void ASTDeclWriter::VisitTranslationUnitDecl (TranslationUnitDecl * D)
Definition at line 385 of file ASTWriterDecl.cpp.
VisitTypeAliasDecl()
void ASTDeclWriter::VisitTypeAliasDecl (TypeAliasDecl * D)
Definition at line 429 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_TYPEALIAS, clang::TypeAliasDecl::getDescribedAliasTemplate(), and VisitTypedefNameDecl().
VisitTypeAliasTemplateDecl()
void ASTDeclWriter::VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl * D)
Definition at line 1862 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_TYPE_ALIAS_TEMPLATE, and VisitRedeclarableTemplateDecl().
VisitTypeDecl()
void ASTDeclWriter::VisitTypeDecl (TypeDecl * D)
Definition at line 397 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTypeRef(), clang::TypeDecl::getBeginLoc(), clang::TypeDecl::getTypeForDecl(), and VisitNamedDecl().
Referenced by VisitTagDecl(), VisitTemplateTypeParmDecl(), VisitTypedefNameDecl(), and VisitUnresolvedUsingTypenameDecl().
VisitTypedefDecl()
void ASTDeclWriter::VisitTypedefDecl (TypedefDecl * D)
Definition at line 413 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_TYPEDEF, clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTWriter::getDeclTypedefAbbrev(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::Decl::getLexicalDeclContext(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::DeclarationName::getNameKind(), clang::Decl::hasAttrs(), clang::DeclarationName::Identifier, clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::serialization::needsAnonymousDeclarationNumber(), and VisitTypedefNameDecl().
VisitTypedefNameDecl()
void ASTDeclWriter::VisitTypedefNameDecl (TypedefNameDecl * D)
Definition at line 403 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddTypeRef(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::TypedefNameDecl::getAnonDeclWithTypedefName(), clang::TypedefNameDecl::getTypeSourceInfo(), clang::TypedefNameDecl::getUnderlyingType(), clang::TypedefNameDecl::isModed(), clang::ASTRecordWriter::push_back(), VisitRedeclarable(), and VisitTypeDecl().
Referenced by VisitObjCTypeParamDecl(), VisitTypeAliasDecl(), and VisitTypedefDecl().
VisitUnnamedGlobalConstantDecl()
void ASTDeclWriter::VisitUnnamedGlobalConstantDecl (UnnamedGlobalConstantDecl * D)
Definition at line 1030 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddAPValue(), clang::serialization::DECL_UNNAMED_GLOBAL_CONSTANT, clang::UnnamedGlobalConstantDecl::getValue(), and VisitValueDecl().
VisitUnresolvedUsingIfExistsDecl()
void ASTDeclWriter::VisitUnresolvedUsingIfExistsDecl (UnresolvedUsingIfExistsDecl * D)
Definition at line 1425 of file ASTWriterDecl.cpp.
References clang::serialization::DECL_UNRESOLVED_USING_IF_EXISTS, and VisitNamedDecl().
VisitUnresolvedUsingTypenameDecl()
void ASTDeclWriter::VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl * D)
Definition at line 1416 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_UNRESOLVED_USING_TYPENAME, clang::UnresolvedUsingTypenameDecl::getEllipsisLoc(), clang::UnresolvedUsingTypenameDecl::getQualifierLoc(), clang::UnresolvedUsingTypenameDecl::getTypenameLoc(), and VisitTypeDecl().
VisitUnresolvedUsingValueDecl()
void ASTDeclWriter::VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl * D)
Definition at line 1407 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationNameLoc(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_UNRESOLVED_USING_VALUE, clang::NamedDecl::getDeclName(), clang::UnresolvedUsingValueDecl::getEllipsisLoc(), clang::UnresolvedUsingValueDecl::getQualifierLoc(), clang::UnresolvedUsingValueDecl::getUsingLoc(), and VisitValueDecl().
VisitUsingDecl()
void ASTDeclWriter::VisitUsingDecl (UsingDecl * D)
Definition at line 1348 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclarationNameLoc(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_USING, clang::NamedDecl::getDeclName(), clang::ASTContext::getInstantiatedFromUsingDecl(), clang::UsingDecl::getQualifierLoc(), clang::UsingDecl::getUsingLoc(), clang::UsingDecl::hasTypename(), clang::ASTRecordWriter::push_back(), and VisitNamedDecl().
VisitUsingDirectiveDecl()
void ASTDeclWriter::VisitUsingDirectiveDecl (UsingDirectiveDecl * D)
Definition at line 1397 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), clang::serialization::DECL_USING_DIRECTIVE, clang::UsingDirectiveDecl::getCommonAncestor(), clang::UsingDirectiveDecl::getNamespaceKeyLocation(), clang::UsingDirectiveDecl::getNominatedNamespace(), clang::UsingDirectiveDecl::getQualifierLoc(), clang::UsingDirectiveDecl::getUsingLoc(), and VisitNamedDecl().
VisitUsingEnumDecl()
void ASTDeclWriter::VisitUsingEnumDecl (UsingEnumDecl * D)
Definition at line 1359 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_USING_ENUM, clang::UsingEnumDecl::getEnumLoc(), clang::UsingEnumDecl::getEnumType(), clang::ASTContext::getInstantiatedFromUsingEnumDecl(), clang::UsingEnumDecl::getUsingLoc(), and VisitNamedDecl().
VisitUsingPackDecl()
void ASTDeclWriter::VisitUsingPackDecl (UsingPackDecl * D)
Definition at line 1369 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_USING_PACK, clang::UsingPackDecl::expansions(), clang::UsingPackDecl::getInstantiatedFromUsingDecl(), clang::ASTRecordWriter::push_back(), and VisitNamedDecl().
VisitUsingShadowDecl()
void ASTDeclWriter::VisitUsingShadowDecl (UsingShadowDecl * D)
Definition at line 1378 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::serialization::DECL_USING_SHADOW, clang::Decl::getIdentifierNamespace(), clang::ASTContext::getInstantiatedFromUsingShadowDecl(), clang::UsingShadowDecl::getTargetDecl(), clang::ASTRecordWriter::push_back(), VisitNamedDecl(), and VisitRedeclarable().
Referenced by VisitConstructorUsingShadowDecl().
VisitValueDecl()
void ASTDeclWriter::VisitValueDecl (ValueDecl * D)
Definition at line 553 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddTypeRef(), clang::ValueDecl::getType(), and VisitNamedDecl().
Referenced by VisitBindingDecl(), VisitDeclaratorDecl(), VisitEnumConstantDecl(), VisitIndirectFieldDecl(), VisitMSGuidDecl(), VisitOMPDeclareMapperDecl(), VisitOMPDeclareReductionDecl(), VisitTemplateParamObjectDecl(), VisitUnnamedGlobalConstantDecl(), and VisitUnresolvedUsingValueDecl().
VisitVarDecl()
void ASTDeclWriter::VisitVarDecl (VarDecl * D)
Definition at line 1052 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::AS_none, clang::serialization::DECL_VAR, clang::Decl::getAccess(), clang::ASTContext::getBlockVarCopyInit(), clang::Type::getContainedDeducedType(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTWriter::GetDeclRef(), clang::ASTWriter::getDeclVarAbbrev(), clang::VarDecl::getDescribedVarTemplate(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::ASTContext::GetGVALinkageForVariable(), clang::VarDecl::getInitStyle(), clang::Decl::getKind(), clang::ASTContext::getLangOpts(), clang::Decl::getLexicalDeclContext(), clang::NamedDecl::getLinkageInternal(), clang::VarDecl::getMemberSpecializationInfo(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::DeclarationName::getNameKind(), clang::VarDecl::getStorageClass(), clang::VarDecl::getStorageDuration(), clang::VarDecl::getTSCSpec(), clang::ValueDecl::getType(), clang::GVA_StrongExternal, clang::Decl::hasAttr(), clang::Decl::hasAttrs(), clang::DeclarationName::Identifier, clang::VarDecl::isARCPseudoStrong(), clang::VarDecl::isConstexpr(), clang::VarDecl::isCXXForRangeDecl(), clang::VarDecl::isEscapingByref(), clang::VarDecl::isExceptionVariable(), clang::Decl::isImplicit(), clang::VarDecl::isInitCapture(), clang::VarDecl::isInline(), clang::VarDecl::isInlineSpecified(), clang::Module::isInterfaceOrPartition(), clang::Decl::isInvalidDecl(), clang::NamedDecl::isModulePrivate(), clang::VarDecl::isNRVOVariable(), clang::VarDecl::isObjCForDecl(), clang::VarDecl::isPreviousDeclInSameBlockScope(), clang::Decl::isReferenced(), clang::VarDecl::isThisDeclarationADemotedDefinition(), clang::Decl::isTopLevelDeclInObjCContainer(), clang::Decl::isUsed(), clang::serialization::needsAnonymousDeclarationNumber(), clang::ASTRecordWriter::push_back(), clang::SD_Static, VisitDeclaratorDecl(), and VisitRedeclarable().
Referenced by VisitDecompositionDecl(), VisitImplicitParamDecl(), VisitOMPCapturedExprDecl(), VisitParmVarDecl(), and VisitVarTemplateSpecializationDecl().
VisitVarTemplateDecl()
void ASTDeclWriter::VisitVarTemplateDecl (VarTemplateDecl * D)
Definition at line 1688 of file ASTWriterDecl.cpp.
References AddTemplateSpecializations(), clang::serialization::DECL_VAR_TEMPLATE, clang::Redeclarable< decl_type >::isFirstDecl(), and VisitRedeclarableTemplateDecl().
VisitVarTemplatePartialSpecializationDecl()
void ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl (VarTemplatePartialSpecializationDecl * D)
Definition at line 1733 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddTemplateParameterList(), clang::serialization::DECL_VAR_TEMPLATE_PARTIAL_SPECIALIZATION, clang::VarTemplatePartialSpecializationDecl::getInstantiatedFromMember(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::VarTemplatePartialSpecializationDecl::getTemplateArgsAsWritten(), clang::VarTemplatePartialSpecializationDecl::getTemplateParameters(), clang::VarTemplatePartialSpecializationDecl::isMemberSpecialization(), clang::ASTRecordWriter::push_back(), and VisitVarTemplateSpecializationDecl().
VisitVarTemplateSpecializationDecl()
void ASTDeclWriter::VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl * D)
Definition at line 1696 of file ASTWriterDecl.cpp.
References clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateArgumentList(), clang::ASTRecordWriter::AddTypeSourceInfo(), clang::serialization::DECL_VAR_TEMPLATE_SPECIALIZATION, clang::VarTemplateDecl::getCanonicalDecl(), clang::VarTemplateSpecializationDecl::getExternLoc(), clang::VarTemplateSpecializationDecl::getPointOfInstantiation(), clang::VarTemplateSpecializationDecl::getSpecializationKind(), clang::VarTemplateSpecializationDecl::getSpecializedTemplate(), clang::VarTemplateSpecializationDecl::getSpecializedTemplateOrPartial(), clang::VarTemplateSpecializationDecl::getTemplateArgs(), clang::VarTemplateSpecializationDecl::getTemplateInstantiationArgs(), clang::VarTemplateSpecializationDecl::getTemplateKeywordLoc(), clang::VarTemplateSpecializationDecl::getTypeAsWritten(), clang::Decl::isCanonicalDecl(), clang::ASTRecordWriter::push_back(), RegisterTemplateSpecialization(), and VisitVarDecl().
Referenced by VisitVarTemplatePartialSpecializationDecl().
The documentation for this class was generated from the following file:
lib/Serialization/ASTWriterDecl.cpp