clang: clang::ItaniumMangleContext Class Reference
clang::ItaniumMangleContext Class Reference abstract
#include "clang/AST/Mangle.h"
Public Types
using DiscriminatorOverrideTy
Public Types inherited from clang::MangleContext
enum ManglerKind { MK_Itanium , MK_Microsoft }
Public Member Functions
ItaniumMangleContext (ASTContext &C, DiagnosticsEngine &D, bool IsAux=false)
virtual void mangleCXXVTable (const CXXRecordDecl *RD, raw_ostream &)=0
virtual void mangleCXXVTT (const CXXRecordDecl *RD, raw_ostream &)=0
virtual void mangleCXXCtorVTable (const CXXRecordDecl *RD, int64_t Offset, const CXXRecordDecl *Type, raw_ostream &)=0
virtual void mangleItaniumThreadLocalInit (const VarDecl *D, raw_ostream &)=0
virtual void mangleItaniumThreadLocalWrapper (const VarDecl *D, raw_ostream &)=0
virtual void mangleCXXCtorComdat (const CXXConstructorDecl *D, raw_ostream &)=0
virtual void mangleCXXDtorComdat (const CXXDestructorDecl *D, raw_ostream &)=0
virtual void mangleLambdaSig (const CXXRecordDecl *Lambda, raw_ostream &)=0
virtual void mangleDynamicStermFinalizer (const VarDecl *D, raw_ostream &)=0
virtual void mangleModuleInitializer (const Module *Module, raw_ostream &)=0
virtual DiscriminatorOverrideTy getDiscriminatorOverride () const =0
Public Member Functions inherited from clang::MangleContext
ManglerKind getKind () const
bool isAux () const
MangleContext (ASTContext &Context, DiagnosticsEngine &Diags, ManglerKind Kind, bool IsAux=false)
virtual ~MangleContext ()
ASTContext & getASTContext () const
DiagnosticsEngine & getDiags () const
virtual void startNewFunction ()
unsigned getBlockId (const BlockDecl *BD, bool Local)
uint64_t getAnonymousStructId (const NamedDecl *D, const FunctionDecl *FD=nullptr)
uint64_t getAnonymousStructIdForDebugInfo (const NamedDecl *D)
virtual std::string getLambdaString (const CXXRecordDecl *Lambda)=0
bool shouldMangleDeclName (const NamedDecl *D)
virtual bool shouldMangleCXXName (const NamedDecl *D)=0
virtual bool shouldMangleStringLiteral (const StringLiteral *SL)=0
virtual bool isUniqueInternalLinkageDecl (const NamedDecl *ND)
virtual void needsUniqueInternalLinkageNames ()
void mangleName (GlobalDecl GD, raw_ostream &)
virtual void mangleCXXName (GlobalDecl GD, raw_ostream &)=0
virtual void mangleThunk (const CXXMethodDecl *MD, const ThunkInfo &Thunk, raw_ostream &)=0
virtual void mangleCXXDtorThunk (const CXXDestructorDecl *DD, CXXDtorType Type, const ThisAdjustment &ThisAdjustment, raw_ostream &)=0
virtual void mangleReferenceTemporary (const VarDecl *D, unsigned ManglingNumber, raw_ostream &)=0
virtual void mangleCXXRTTI (QualType T, raw_ostream &)=0
virtual void mangleCXXRTTIName (QualType T, raw_ostream &, bool NormalizeIntegers=false)=0
virtual void mangleStringLiteral (const StringLiteral *SL, raw_ostream &)=0
virtual void mangleMSGuidDecl (const MSGuidDecl *GD, raw_ostream &)
void mangleGlobalBlock (const BlockDecl *BD, const NamedDecl *ID, raw_ostream &Out)
void mangleCtorBlock (const CXXConstructorDecl *CD, CXXCtorType CT, const BlockDecl *BD, raw_ostream &Out)
void mangleDtorBlock (const CXXDestructorDecl *CD, CXXDtorType DT, const BlockDecl *BD, raw_ostream &Out)
void mangleBlock (const DeclContext *DC, const BlockDecl *BD, raw_ostream &Out)
void mangleObjCMethodName (const ObjCMethodDecl *MD, raw_ostream &OS, bool includePrefixByte=true, bool includeCategoryNamespace=true)
void mangleObjCMethodNameAsSourceName (const ObjCMethodDecl *MD, raw_ostream &)
virtual void mangleStaticGuardVariable (const VarDecl *D, raw_ostream &)=0
virtual void mangleDynamicInitializer (const VarDecl *D, raw_ostream &)=0
virtual void mangleDynamicAtExitDestructor (const VarDecl *D, raw_ostream &)=0
virtual void mangleSEHFilterExpression (GlobalDecl EnclosingDecl, raw_ostream &Out)=0
virtual void mangleSEHFinallyBlock (GlobalDecl EnclosingDecl, raw_ostream &Out)=0
virtual void mangleTypeName (QualType T, raw_ostream &, bool NormalizeIntegers=false)=0
Generates a unique string for an externally visible type for use with TBAA or type uniquing.
Static Public Member Functions
static bool classof (const MangleContext *C)
static ItaniumMangleContext * create (ASTContext &Context, DiagnosticsEngine &Diags, bool IsAux=false)
static ItaniumMangleContext * create (ASTContext &Context, DiagnosticsEngine &Diags, DiscriminatorOverrideTy Discriminator, bool IsAux=false)
Detailed Description
Definition at line 187 of file Mangle.h.
Member Typedef Documentation
DiscriminatorOverrideTy
using clang::ItaniumMangleContext::DiscriminatorOverrideTy
Initial value:
      std::optional<unsigned> (*)(ASTContext &, const NamedDecl *)
Definition at line 189 of file Mangle.h.
Constructor & Destructor Documentation
ItaniumMangleContext()
clang::ItaniumMangleContext::ItaniumMangleContext (ASTContext & C, DiagnosticsEngine & D, bool IsAux = false) inline explicit
Definition at line 191 of file Mangle.h.
Member Function Documentation
classof()
static bool clang::ItaniumMangleContext::classof (const MangleContext * C) inline static
Definition at line 219 of file Mangle.h.
References clang::C, and clang::MangleContext::MK_Itanium.
create() [1/2]
ItaniumMangleContext * ItaniumMangleContext::create (ASTContext & Context, DiagnosticsEngine & Diags, bool IsAux = false) static
Definition at line 6751 of file ItaniumMangle.cpp.
Referenced by clang::SYCLUniqueStableNameExpr::ComputeName(), clang::ASTContext::createDeviceMangleContext(), and clang::ASTContext::createMangleContext().
create() [2/2]
ItaniumMangleContext * ItaniumMangleContext::create (ASTContext & Context, DiagnosticsEngine & Diags, DiscriminatorOverrideTy Discriminator, bool IsAux = false) static
Definition at line 6763 of file ItaniumMangle.cpp.
getDiscriminatorOverride()
virtual DiscriminatorOverrideTy clang::ItaniumMangleContext::getDiscriminatorOverride () const pure virtual
mangleCXXCtorComdat()
virtual void clang::ItaniumMangleContext::mangleCXXCtorComdat (const CXXConstructorDecl * D, raw_ostream &) pure virtual
mangleCXXCtorVTable()
virtual void clang::ItaniumMangleContext::mangleCXXCtorVTable (const CXXRecordDecl * RD, int64_t Offset, const CXXRecordDecl * Type, raw_ostream &) pure virtual
mangleCXXDtorComdat()
virtual void clang::ItaniumMangleContext::mangleCXXDtorComdat (const CXXDestructorDecl * D, raw_ostream &) pure virtual
mangleCXXVTable()
virtual void clang::ItaniumMangleContext::mangleCXXVTable (const CXXRecordDecl * RD, raw_ostream &) pure virtual
mangleCXXVTT()
virtual void clang::ItaniumMangleContext::mangleCXXVTT (const CXXRecordDecl * RD, raw_ostream &) pure virtual
mangleDynamicStermFinalizer()
virtual void clang::ItaniumMangleContext::mangleDynamicStermFinalizer (const VarDecl * D, raw_ostream &) pure virtual
mangleItaniumThreadLocalInit()
virtual void clang::ItaniumMangleContext::mangleItaniumThreadLocalInit (const VarDecl * D, raw_ostream &) pure virtual
mangleItaniumThreadLocalWrapper()
virtual void clang::ItaniumMangleContext::mangleItaniumThreadLocalWrapper (const VarDecl * D, raw_ostream &) pure virtual
mangleLambdaSig()
virtual void clang::ItaniumMangleContext::mangleLambdaSig (const CXXRecordDecl * Lambda, raw_ostream &) pure virtual
mangleModuleInitializer()
virtual void clang::ItaniumMangleContext::mangleModuleInitializer (const Module * Module, raw_ostream &) pure virtual
The documentation for this class was generated from the following files:
include/clang/AST/Mangle.h
lib/AST/ItaniumMangle.cpp