clang: clang::ento::BugReporterContext Class Reference
clang::ento::BugReporterContext Class Reference
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Member Functions
BugReporterContext (PathSensitiveBugReporter &br)
virtual ~BugReporterContext ()=default
PathSensitiveBugReporter & getBugReporter ()
ProgramStateManager & getStateManager () const
ASTContext & getASTContext () const
const SourceManager & getSourceManager () const
const AnalyzerOptions & getAnalyzerOptions () const
Detailed Description
Definition at line 702 of file BugReporter.h.
Constructor & Destructor Documentation
BugReporterContext()
clang::ento::BugReporterContext::BugReporterContext (PathSensitiveBugReporter & br) inline
Definition at line 708 of file BugReporter.h.
~BugReporterContext()
virtual clang::ento::BugReporterContext::~BugReporterContext () virtual default
Member Function Documentation
getAnalyzerOptions()
const AnalyzerOptions & clang::ento::BugReporterContext::getAnalyzerOptions () const inline
Definition at line 726 of file BugReporter.h.
References clang::ento::BugReporter::getAnalyzerOptions().
Referenced by constructDebugPieceForTrackedCondition(), and clang::ento::LikelyFalsePositiveSuppressionBRVisitor::finalizeVisitor().
getASTContext()
ASTContext & clang::ento::BugReporterContext::getASTContext () const inline
Definition at line 718 of file BugReporter.h.
References clang::ento::BugReporter::getContext().
Referenced by constructDebugPieceForTrackedCondition(), clang::ento::FalsePositiveRefutationBRVisitor::finalizeVisitor(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), getMacroName(), and clang::ento::ConditionBRVisitor::patternMatch().
getBugReporter()
PathSensitiveBugReporter & clang::ento::BugReporterContext::getBugReporter () inline
Definition at line 712 of file BugReporter.h.
getSourceManager()
const SourceManager & clang::ento::BugReporterContext::getSourceManager () const inline
Definition at line 722 of file BugReporter.h.
References clang::ento::BugReporter::getSourceManager().
Referenced by constructDebugPieceForTrackedCondition(), clang::ento::bugreporter::StoreHandler::constructNote(), clang::ento::LikelyFalsePositiveSuppressionBRVisitor::finalizeVisitor(), getMacroName(), clang::ento::ConditionBRVisitor::patternMatch(), clang::ento::ConditionBRVisitor::VisitConditionVariable(), clang::ento::NilReceiverBRVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::TagVisitor::VisitNode(), clang::ento::TrackConstraintBRVisitor::VisitNode(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::ento::ConditionBRVisitor::VisitTrueTest(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getStateManager()
ProgramStateManager & clang::ento::BugReporterContext::getStateManager () const inline
Definition at line 714 of file BugReporter.h.
References clang::ento::PathSensitiveBugReporter::getStateManager().
Referenced by clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
lib/StaticAnalyzer/Core/BugReporter.cpp