clang: clang::Stmt Class Reference
clang::Stmt Class Reference
Stmt - This represents one statement.
#include "clang/AST/Stmt.h"
Classes
class ArrayOrMatrixSubscriptExprBitfields
class AttributedStmtBitfields
class BinaryOperatorBitfields
class BreakStmtBitfields
class CallExprBitfields
class CastExprBitfields
struct CastIterator
Iterator for iterating over Stmt * arrays that contain only T *.
class CharacterLiteralBitfields
class CoawaitExprBitfields
class CompoundStmtBitfields
class ConstantExprBitfields
class ContinueStmtBitfields
class CXXBoolLiteralExprBitfields
class CXXConstructExprBitfields
class CXXDefaultArgExprBitfields
class CXXDefaultInitExprBitfields
class CXXDeleteExprBitfields
class CXXDependentScopeMemberExprBitfields
class CXXNewExprBitfields
class CXXNoexceptExprBitfields
class CXXNullPtrLiteralExprBitfields
class CXXOperatorCallExprBitfields
class CXXRewrittenBinaryOperatorBitfields
class CXXScalarValueInitExprBitfields
class CXXThisExprBitfields
class CXXThrowExprBitfields
class CXXUnresolvedConstructExprBitfields
class DeclRefExprBitfields
class DependentScopeDeclRefExprBitfields
class DoStmtBitfields
struct EmptyShell
A placeholder type used to construct an empty shell of a type, that will be filled in later (e.g., by some de-serialization).
class ExprBitfields
class ExprWithCleanupsBitfields
class FloatingLiteralBitfields
class ForStmtBitfields
class GenericSelectionExprBitfields
class GotoStmtBitfields
class IfStmtBitfields
class InitListExprBitfields
class LabelStmtBitfields
class LambdaExprBitfields
class MemberExprBitfields
class NullStmtBitfields
class ObjCIndirectCopyRestoreExprBitfields
class OpaqueValueExprBitfields
class OverloadExprBitfields
class ParenListExprBitfields
class PredefinedExprBitfields
class PseudoObjectExprBitfields
class RequiresExprBitfields
class ReturnStmtBitfields
class SourceLocExprBitfields
class StmtBitfields
class StmtExprBitfields
class StringLiteralBitfields
class SubstNonTypeTemplateParmExprBitfields
class SwitchCaseBitfields
class SwitchStmtBitfields
class TypeTraitExprBitfields
class UnaryExprOrTypeTraitExprBitfields
class UnaryOperatorBitfields
class UnresolvedLookupExprBitfields
class UnresolvedMemberExprBitfields
class WhileStmtBitfields
Public Types
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Member Functions
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Protected Types
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Friends
class ASTStmtReader
class ASTStmtWriter
Detailed Description
Stmt - This represents one statement.
Definition at line 72 of file Stmt.h.
Member Typedef Documentation
child_iterator
using clang::Stmt::child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
This permits easy iteration over all nodes in the AST.
Definition at line 1267 of file Stmt.h.
child_range
using clang::Stmt::child_range = llvm::iterator_range<child_iterator>
Definition at line 1270 of file Stmt.h.
const_child_iterator
using clang::Stmt::const_child_iterator = ConstStmtIterator
Definition at line 1268 of file Stmt.h.
const_child_range
using clang::Stmt::const_child_range = llvm::iterator_range<const_child_iterator>
Definition at line 1271 of file Stmt.h.
ConstCastIterator
template<typename T > using clang::Stmt::ConstCastIterator = CastIterator<T, const T *const, const Stmt *const> protected
Const iterator for iterating over Stmt * arrays that contain only T *.
Definition at line 1152 of file Stmt.h.
ConstExprIterator
using clang::Stmt::ConstExprIterator = ConstCastIterator<Expr> protected
Definition at line 1155 of file Stmt.h.
ExprIterator
using clang::Stmt::ExprIterator = CastIterator<Expr> protected
Definition at line 1154 of file Stmt.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NumStmtBits
Definition at line 108 of file Stmt.h.
anonymous enum
anonymous enum protected
Enumerator
NumExprBits
Definition at line 321 of file Stmt.h.
anonymous enum
anonymous enum protected
Enumerator
NumCallExprBits
Definition at line 491 of file Stmt.h.
anonymous enum
anonymous enum protected
Enumerator
NumOverloadExprBits
Definition at line 896 of file Stmt.h.
Likelihood
enum clang::Stmt::Likelihood
The likelihood of a branch being taken.
Enumerator
LH_Unlikely
Branch has the [[unlikely]] attribute.
LH_None
No attribute set or branches of the IfStmt have the same attribute.
LH_Likely
Branch has the [[likely]] attribute.
Definition at line 1124 of file Stmt.h.
StmtClass
enum clang::Stmt::StmtClass
Enumerator
NoStmtClass
Definition at line 74 of file Stmt.h.
Constructor & Destructor Documentation
Stmt() [1/5]
clang::Stmt::Stmt (StmtClass SC, EmptyShell) inline explicit protected
Construct an empty statement.
Definition at line 1163 of file Stmt.h.
Stmt() [2/5]
clang::Stmt::Stmt () delete
Stmt() [3/5]
clang::Stmt::Stmt (const Stmt &) delete
Stmt() [4/5]
clang::Stmt::Stmt (Stmt &&) delete
Stmt() [5/5]
clang::Stmt::Stmt (StmtClass SC) inline
Definition at line 1172 of file Stmt.h.
References addStmtClass(), and StmtBits.
Member Function Documentation
addStmtClass()
void Stmt::addStmtClass (const StmtClass s) static
Definition at line 125 of file Stmt.cpp.
References StmtClassNameTable::Counter, getStmtInfoTableEntry(), and s.
Referenced by Stmt().
child_begin() [1/2]
child_iterator clang::Stmt::child_begin () inline
Definition at line 1280 of file Stmt.h.
References children().
Referenced by clang::DesignatedInitExpr::getInit(), isAncestorDeclContextOf(), isIdenticalStmt(), and clang::DesignatedInitExpr::setInit().
child_begin() [2/2]
const_child_iterator clang::Stmt::child_begin () const inline
Definition at line 1283 of file Stmt.h.
References children().
child_end() [1/2]
child_iterator clang::Stmt::child_end () inline
Definition at line 1281 of file Stmt.h.
References children().
Referenced by isAncestorDeclContextOf(), and isIdenticalStmt().
child_end() [2/2]
const_child_iterator clang::Stmt::child_end () const inline
Definition at line 1284 of file Stmt.h.
References children().
children() [1/2]
Stmt::child_range Stmt::children ()
Definition at line 286 of file Stmt.cpp.
References getStmtClass(), and NoStmtClass.
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPRegionEnd(), AnalyzeImplicitConversions(), clang::MinComplexityConstraint::calculateStmtComplexity(), CheckConstexprFunctionBody(), CheckNakedParmReference(), checkNoThrow(), child_begin(), child_begin(), child_end(), child_end(), children(), clang::Expr::HasSideEffects(), isCapturedBy(), IsStructurallyEquivalent(), isSupportedByOpenMPIRBuilder(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), seenBefore(), and GlobalDeclRefChecker::VisitExpr().
children() [2/2]
const_child_range clang::Stmt::children () const inline
Definition at line 1275 of file Stmt.h.
References Children, and children().
determineLikelihoodConflict()
std::tuple< bool, const Attr *, const Attr * > Stmt::determineLikelihoodConflict (const Stmt * Then, const Stmt * Else) static
Returns
whether the likelihood of the branches of an if statement are conflicting. When the first element is true there's a conflict and the Attr's are the conflicting attributes of the Then and Else Stmt.
Definition at line 184 of file Stmt.cpp.
References getLikelihood(), and LH_None.
Referenced by clang::Sema::ActOnIfStmt().
dump() [1/2]
LLVM_DUMP_METHOD void Stmt::dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
Definition at line 276 of file ASTDumper.cpp.
References P.
Referenced by clang::Sema::ActOnPragmaDump(), and clang::AnyCall::dump().
dump() [2/2]
LLVM_DUMP_METHOD void Stmt::dump (raw_ostream & OS, const ASTContext & Context) const
Definition at line 281 of file ASTDumper.cpp.
References clang::ASTContext::getDiagnostics(), clang::DiagnosticsEngine::getShowColors(), and P.
dumpColor()
LLVM_DUMP_METHOD void Stmt::dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
Definition at line 287 of file ASTDumper.cpp.
References P.
dumpPretty()
void Stmt::dumpPretty (const ASTContext & Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
Definition at line 2747 of file StmtPrinter.cpp.
References clang::ASTContext::getLangOpts().
EnableStatistics()
void Stmt::EnableStatistics () static
Definition at line 130 of file Stmt.cpp.
Referenced by clang::ParseAST().
getBeginLoc()
SourceLocation Stmt::getBeginLoc () const
Definition at line 337 of file Stmt.cpp.
References getStmtClass(), and NoStmtClass.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnCondition(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXForRangeStmt(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnMSAsmStmt(), clang::Sema::ActOnNoexceptSpec(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPDispatchDirective(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPMessageClause(), clang::Sema::ActOnOpenMPParallelSectionsDirective(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPSectionsDirective(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::Sema::ActOnStmtExprResult(), clang::Sema::AddAllocAlignAttr(), clang::Sema::AddConversionCandidate(), adornObjCBoolConversionDiagWithTernaryFixit(), AnalyzeAssignment(), AnalyzeBitFieldAssignment(), AnalyzeImplicitConversions(), clang::Sema::BuildArrayType(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), buildCaptureDecl(), BuildConvertedConstantExpression(), clang::Sema::BuildCXXDefaultArgExpr(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildInstanceMessage(), BuildNonArrayForRange(), clang::Sema::BuildOverloadedCallExpr(), clang::Sema::buildOverloadedCallSet(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildStaticAssertDeclaration(), clang::Sema::BuildVAArgExpr(), calculateConstraintSatisfaction(), clang::Sema::canCalleeThrow(), clang::Sema::CanPerformCopyInitialization(), CastForMoving(), castForMoving(), clang::Sema::CheckAddressOfOperand(), checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckAssignmentOperands(), clang::Sema::CheckConditionalOperands(), CheckConstexprFunctionBody(), clang::Sema::CheckConversionToObjCLiteral(), clang::Sema::checkDeclIsAllowedInOpenMPTarget(), checkDirectCallValidity(), CheckEvalInICE(), checkExprMemoryConstraintCompat(), CheckFallThroughForBody(), CheckFoldOperand(), clang::Sema::CheckFunctionDeclaration(), CheckICE(), clang::Sema::CheckImplementationIvars(), clang::Sema::CheckMemberPointerConversion(), CheckMoveOnConstruction(), CheckNakedParmReference(), CheckNonTypeTemplatePartialSpecializationArgs(), clang::Sema::CheckObjCBridgeRelatedConversions(), CheckObjCCollectionLiteralElement(), checkOpenCLEnqueueIntType(), checkOpenCLPipeArg(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPLoop(), checkParamIsIntegerType(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::CheckPointerToMemberOperands(), checkRecursiveFunction(), clang::Sema::CheckSingleAssignmentConstraints(), CheckStmtInlineAttr(), CheckStringInit(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), CheckTemplateArgumentPointerToMember(), checkThreeWayNarrowingConversion(), clang::Sema::checkVariadicArgument(), checkVAStartABI(), checkVAStartIsInVariadicFunction(), CheckWasmBuiltinArgIsInteger(), CheckWasmBuiltinArgIsTable(), clang::Sema::ConstantFoldAttrArgs(), ConvertForConditional(), clang::Sema::ConvertMemberDefaultInitExpression(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), CreateIfFixit(), CreateNewFunctionDecl(), createOverloadsForFixedParams(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::InitializationSequence::Diagnose(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAssignmentAsCondition(), DiagnoseBitwisePrecedence(), DiagnoseCastQual(), clang::Sema::DiagnoseCommaOperator(), DiagnoseConditionalPrecedence(), clang::Sema::DiagnoseEmptyLoopBody(), clang::Sema::DiagnoseImmediateEscalatingReason(), DiagnoseIndirectOrAsmJumpStmt(), diagnoseLogicalNotOnLHSofCheck(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), DiagnoseNarrowingInInitList(), diagnoseNoViableConversion(), diagnoseObjCLiteralComparison(), diagnoseRepeatedUseOfWeak(), DiagnoseShiftCompare(), diagnoseStringPlusChar(), diagnoseStringPlusInt(), diagnoseTautologicalComparison(), clang::Sema::DiagnoseUnexpandedParameterPack(), DiagnoseUninitializedConstRefUse(), diagnoseUnsatisfiedRequirement(), diagnoseWellFormedUnsatisfiedConstraintExpr(), clang::Sema::diagnoseZeroToNullptrConversion(), DiagUninitUse(), emitAndFixInvalidAsmCastLValue(), emitOutlinedFunctionPrologue(), EvaluateConvertedConstantExpression(), evaluateVarDeclInit(), findOpenParen(), FinishOverloadedCallExpr(), clang::Sema::GatherArgumentsForCall(), getAndVerifyMatrixDimension(), clang::ArraySubscriptExpr::getBeginLoc(), clang::BinaryConditionalOperator::getBeginLoc(), clang::BinaryOperator::getBeginLoc(), clang::CallExpr::getBeginLoc(), clang::CapturedStmt::getBeginLoc(), clang::ConditionalOperator::getBeginLoc(), clang::ConstantExpr::getBeginLoc(), clang::CXXBindTemporaryExpr::getBeginLoc(), clang::CXXFoldExpr::getBeginLoc(), clang::CXXRewrittenBinaryOperator::getBeginLoc(), clang::CXXStdInitializerListExpr::getBeginLoc(), clang::DesignatedInitUpdateExpr::getBeginLoc(), clang::ExprWithCleanups::getBeginLoc(), clang::ExtVectorElementExpr::getBeginLoc(), clang::ImaginaryLiteral::getBeginLoc(), clang::ImplicitCastExpr::getBeginLoc(), clang::MaterializeTemporaryExpr::getBeginLoc(), clang::MatrixSubscriptExpr::getBeginLoc(), clang::MemberExpr::getBeginLoc(), clang::MSPropertyRefExpr::getBeginLoc(), clang::MSPropertySubscriptExpr::getBeginLoc(), clang::ObjCIsaExpr::getBeginLoc(), clang::ObjCIvarRefExpr::getBeginLoc(), clang::ObjCPropertyRefExpr::getBeginLoc(), clang::ObjCSubscriptRefExpr::getBeginLoc(), clang::OMPArraySectionExpr::getBeginLoc(), clang::OpaqueValueExpr::getBeginLoc(), clang::PackExpansionExpr::getBeginLoc(), clang::PseudoObjectExpr::getBeginLoc(), clang::StmtSequence::getBeginLoc(), clang::UserDefinedLiteral::getBeginLoc(), getExprText(), DerefSimplePtrArithFixableGadget::getFixits(), UPCPreIncrementGadget::getFixits(), clang::CXXRewrittenBinaryOperator::getSourceRange(), clang::ento::PathDiagnosticLocation::getValidSourceLocation(), handleAlwaysInlineAttr(), handleDiagnoseAsBuiltinAttr(), handleDiagnoseIfAttr(), handleFallThroughAttr(), handleLoopHintAttr(), handleNoInlineAttr(), handleNoMergeAttr(), handlePassObjectSizeAttr(), handlePatchableFunctionEntryAttr(), clang::Sema::ImpCastExprToType(), clang::AnalysisDeclContext::isBodyAutosynthesizedFromModelFile(), IsEnumConstOrFromMacro(), IsInitializerListConstructorConversion(), clang::Sema::IsIntegralPromotion(), clang::Sema::IsMemberPointerConversion(), isNullPointerValueTemplateArgument(), clang::Sema::IsPointerConversion(), clang::Expr::isUnusedResultAWarning(), IsUserDefinedConversion(), IsVectorConversion(), MatchTemplateParameterKind(), maybeDiagnoseAssignmentToFunction(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::ento::ConditionBRVisitor::patternMatch(), clang::InitializationSequence::Perform(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformCopyInitialization(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::ento::ExprEngine::ProcessStmt(), ProcessStmtAttribute(), removePunyEdges(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), rewriteToArrayLiteral(), rewriteToDictionaryLiteral(), clang::CodeGen::CGOpenMPRuntime::scanForTargetRegionsFunctions(), SemaBuiltinAnnotation(), SemaBuiltinDumpStruct(), SemaBuiltinOverflow(), clang::Sema::SemaBuiltinShuffleVector(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinKernelWorkGroupSize(), SemaOpenCLBuiltinNDRangeAndBlock(), clang::Sema::SubstDefaultArgument(), clang::Sema::TemplateParameterListsAreEqual(), TryClassUnification(), clang::Sema::tryConvertExprToType(), TryCopyInitialization(), TryImplicitConversion(), TryLValueToRValueCast(), TryOrBuildParenListInitialization(), TryTypoCorrectionForCall(), TryUserDefinedConversion(), clang::Sema::VerifyIntegerConstantExpression(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeImporter::VisitExpr(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode().
getEndLoc()
SourceLocation Stmt::getEndLoc () const
Definition at line 349 of file Stmt.cpp.
References getStmtClass(), and NoStmtClass.
Referenced by clang::Sema::ActOnCondition(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnLambdaExpr(), clang::Sema::ActOnOpenMPUnrollDirective(), addBlockPointerConversion(), addFunctionPointerConversion(), adornObjCBoolConversionDiagWithTernaryFixit(), clang::Sema::BuildCStyleCastExpr(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildReturnStmt(), CheckFallThroughForBody(), CheckFoldOperand(), clang::Sema::CheckLogicalOperands(), clang::Sema::CheckObjCBridgeRelatedConversions(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::ConvertMemberDefaultInitExpression(), clang::Sema::CreateBuiltinBinOp(), CreateIfFixit(), clang::ento::CXXDestructorCall::CXXDestructorCall(), clang::Sema::DefaultVariadicArgumentPromotion(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseBitwisePrecedence(), clang::Sema::DiagnoseCommaOperator(), DiagnoseConditionalPrecedence(), DiagnoseDirectIsaAccess(), diagnoseLogicalNotOnLHSofCheck(), DiagnoseNarrowingInInitList(), diagnoseNoViableConversion(), diagnoseObjCLiteralComparison(), clang::Sema::DiagnoseSentinelCalls(), DiagnoseShiftCompare(), diagnoseStringPlusChar(), diagnoseStringPlusInt(), clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt(), clang::ObjCIsaExpr::getBaseLocEnd(), clang::AttributedStmt::getEndLoc(), clang::BinaryConditionalOperator::getEndLoc(), clang::BinaryOperator::getEndLoc(), clang::BlockExpr::getEndLoc(), clang::CallExpr::getEndLoc(), clang::CapturedStmt::getEndLoc(), clang::CaseStmt::getEndLoc(), clang::ConditionalOperator::getEndLoc(), clang::ConstantExpr::getEndLoc(), clang::CoreturnStmt::getEndLoc(), clang::CoroutineSuspendExpr::getEndLoc(), clang::CStyleCastExpr::getEndLoc(), clang::CXXBindTemporaryExpr::getEndLoc(), clang::CXXCatchStmt::getEndLoc(), clang::CXXConstructExpr::getEndLoc(), clang::CXXDeleteExpr::getEndLoc(), clang::CXXFoldExpr::getEndLoc(), clang::CXXForRangeStmt::getEndLoc(), clang::CXXFunctionalCastExpr::getEndLoc(), clang::CXXRewrittenBinaryOperator::getEndLoc(), clang::CXXStdInitializerListExpr::getEndLoc(), clang::CXXTemporaryObjectExpr::getEndLoc(), clang::CXXThrowExpr::getEndLoc(), clang::CXXTryStmt::getEndLoc(), clang::DefaultStmt::getEndLoc(), clang::DependentCoawaitExpr::getEndLoc(), clang::DesignatedInitExpr::getEndLoc(), clang::DesignatedInitUpdateExpr::getEndLoc(), clang::ExprWithCleanups::getEndLoc(), clang::ForStmt::getEndLoc(), clang::IfStmt::getEndLoc(), clang::ImaginaryLiteral::getEndLoc(), clang::ImplicitCastExpr::getEndLoc(), clang::LabelStmt::getEndLoc(), clang::MaterializeTemporaryExpr::getEndLoc(), clang::MemberExpr::getEndLoc(), clang::MSDependentExistsStmt::getEndLoc(), clang::ObjCAtCatchStmt::getEndLoc(), clang::ObjCAtFinallyStmt::getEndLoc(), clang::ObjCAtThrowStmt::getEndLoc(), clang::ObjCAtTryStmt::getEndLoc(), clang::ObjCAutoreleasePoolStmt::getEndLoc(), clang::ObjCBridgedCastExpr::getEndLoc(), clang::ObjCForCollectionStmt::getEndLoc(), clang::ObjCStringLiteral::getEndLoc(), clang::OMPArrayShapingExpr::getEndLoc(), clang::OpaqueValueExpr::getEndLoc(), clang::PseudoObjectExpr::getEndLoc(), clang::ReturnStmt::getEndLoc(), clang::StmtSequence::getEndLoc(), clang::SwitchStmt::getEndLoc(), clang::WhileStmt::getEndLoc(), clang::BlockDecl::getSourceRange(), clang::ConceptDecl::getSourceRange(), clang::CXXRewrittenBinaryOperator::getSourceRange(), clang::EnumConstantDecl::getSourceRange(), clang::FieldDecl::getSourceRange(), clang::TopLevelStmtDecl::getSourceRange(), isNullPointerValueTemplateArgument(), clang::Expr::isUnusedResultAWarning(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::ento::ConditionBRVisitor::patternMatch(), rewriteToArrayLiteral(), rewriteToDictionaryLiteral(), clang::consumed::ConsumedAnalyzer::run(), SemaBuiltinDumpStruct(), clang::Sema::SemaBuiltinShuffleVector(), clang::FunctionDecl::setBody(), clang::Declarator::setTrailingRequiresClause(), TryOrBuildParenListInitialization(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getID()
int64_t Stmt::getID (const ASTContext & Context) const
Returns
Unique reproducible object identifier
Definition at line 361 of file Stmt.cpp.
References clang::ASTContext::getAllocator().
Referenced by clang::ento::AllocaRegion::dumpToStream(), clang::ento::CompoundLiteralRegion::dumpToStream(), clang::ento::CXXLifetimeExtendedObjectRegion::dumpToStream(), clang::ento::CXXTempObjectRegion::dumpToStream(), clang::ento::SymbolConjured::dumpToStream(), printIndicesOfElementsToConstructJson(), and printPendingInitLoopJson().
getLikelihood() [1/3]
Stmt::Likelihood Stmt::getLikelihood (ArrayRef< const Attr * > Attrs) static
Returns
the likelihood of a set of attributes.
Definition at line 154 of file Stmt.cpp.
Referenced by determineLikelihoodConflict(), and getLikelihood().
getLikelihood() [2/3]
Stmt::Likelihood Stmt::getLikelihood (const Stmt * S) static
Returns
the likelihood of a statement.
Definition at line 158 of file Stmt.cpp.
getLikelihood() [3/3]
Stmt::Likelihood Stmt::getLikelihood (const Stmt * Then, const Stmt * Else) static
Returns
the likelihood of the 'then' branch of an 'if' statement. The 'else' branch is required to determine whether both branches specify the same likelihood, which affects the result.
Definition at line 166 of file Stmt.cpp.
References getLikelihood(), LH_Likely, LH_None, and LH_Unlikely.
getLikelihoodAttr()
const Attr * Stmt::getLikelihoodAttr (const Stmt * S) static
Returns
the likelihood attribute of a statement.
Definition at line 162 of file Stmt.cpp.
Referenced by clang::Sema::ActOnIfStmt().
getSourceRange()
SourceRange Stmt::getSourceRange () const
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
We assume AST clients will have a pointer to the respective SourceManager.
Definition at line 325 of file Stmt.cpp.
References getStmtClass(), and NoStmtClass.
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXFoldExpr(), clang::Sema::ActOnCXXForRangeStmt(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnMSAsmStmt(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnOpenMPAllocateDirective(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDepobjClause(), clang::Sema::ActOnOpenMPDetachClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPHasDeviceAddrClause(), clang::Sema::ActOnOpenMPIsDevicePtrClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnParamDefaultArgument(), clang::Sema::ActOnStartLinkageSpecification(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::AddAlignedAttr(), clang::Sema::AddAlignValueAttr(), clang::Sema::AddAssumeAlignedAttr(), addFixitForObjCARCConversion(), clang::Sema::AddInitializerToDecl(), AnalyzeBitFieldAssignment(), AnalyzeComparison(), AnalyzeImplicitConversions(), applyCocoaAPICheck(), BuildAddressSpaceIndex(), clang::Sema::BuildArrayType(), clang::Sema::BuildAsTypeExpr(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallToMemberFunction(), buildCoawaitCalls(), clang::Sema::BuildCompoundLiteralExpr(), BuildConvertedConstantExpression(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDeclaratorGroup(), clang::Sema::BuildExtVectorType(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildMatrixType(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildNestedRequirement(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildStaticAssertDeclaration(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorLiteral(), clang::Sema::BuildVectorType(), calculateConstraintSatisfaction(), calculateConstraintSatisfaction(), CastForMoving(), castForMoving(), clang::Sema::CheckAddressOfMemberAccess(), clang::Sema::CheckAddressOfOperand(), CheckAlignOfExpr(), checkAllocateClauses(), checkArithmeticBinOpPointerOperands(), checkArithmeticNull(), checkArithmeticOnObjCPointer(), clang::Sema::CheckBooleanCondition(), CheckBuiltinTargetInSupported(), CheckBuiltinTargetNotInUnsupported(), clang::Sema::CheckCallReturnType(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckCompleteVariableDeclaration(), checkCondition(), checkConditionalBlockPointerCompatibility(), clang::Sema::CheckConditionalOperands(), checkConditionalPointerCompatibility(), clang::Sema::CheckConstraintExpression(), CheckCXX98CompatAccessibleCopy(), clang::Sema::CheckCXXThrowOperand(), clang::Sema::checkDeclIsAllowedInOpenMPTarget(), checkEnumArithmeticConversions(), clang::Sema::CheckEnumConstant(), checkEnumTypesInSwitchStmt(), clang::Sema::CheckExceptionSpecCompatibility(), checkExprMemoryConstraintCompat(), clang::Sema::CheckFloatComparison(), CheckFoldOperand(), clang::Sema::CheckForConstantInitializer(), CheckFormatString(), CheckForModifiableLvalue(), checkFunctionOrMethodParameterIndex(), CheckImplicitConversion(), CheckIncrementDecrementOperand(), checkIndirectCopyRestoreSource(), CheckIndirectionOperand(), CheckKeyForObjCARCConversion(), clang::Sema::CheckLogicalOperands(), checkMapClauseExpressionBase(), checkMapConflicts(), checkMappableExpressionList(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckMemberPointerConversion(), clang::Sema::CheckMessageArgumentTypes(), CheckNonNullArgument(), CheckObjCCollectionLiteralElement(), clang::Sema::CheckObjCForCollectionOperand(), checkObjCPointerIntrospection(), checkOpenCLConditionVector(), checkOpenCLPipeArg(), checkOpenCLPipePacketType(), clang::Sema::checkOpenMPDeclareVariantFunction(), checkOpenMPIterationSpace(), checkOpenMPLoop(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckPointerConversion(), checkPointerIntegerMismatch(), clang::Sema::CheckPointerToMemberOperands(), checkPreviousOMPAllocateAttribute(), clang::Sema::CheckRegparmAttr(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::CheckSizelessVectorOperands(), checkSizelessVectorShift(), clang::Sema::CheckStaticArrayArgument(), CheckStringInit(), clang::Sema::CheckSubtractionOperands(), clang::Sema::CheckSwitchCondition(), CheckTautologicalComparison(), clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), CheckTemplateArgumentIsCompatibleWithParameter(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTemplateIdType(), clang::Sema::CheckTypenameType(), checkUInt32Argument(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnresolvedLookupAccess(), clang::Sema::CheckUnresolvedMemberAccess(), checkUnsafeAssignLiteral(), checkUnsafeAssignObject(), clang::Sema::checkUnsafeExprAssigns(), clang::Sema::CheckVariableDeclarationType(), clang::Sema::CheckVectorOperands(), checkVectorShift(), CheckWasmBuiltinArgIsInteger(), CheckWasmBuiltinArgIsTable(), constructDebugPieceForTrackedCondition(), clang::Sema::ConvertArgumentsForCall(), CopyObject(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::CreateGenericSelectionExpr(), CreateIfFixit(), CreateNewFunctionDecl(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::deduceVarTypeFromInitializer(), clang::InitializationSequence::Diagnose(), diagnoseAddressOfInvalidType(), clang::Sema::DiagnoseAlwaysNonNullPointer(), diagnoseAmbiguousConversion(), diagnoseArithmeticOnTwoFunctionPointers(), diagnoseArithmeticOnTwoVoidPointers(), clang::Sema::DiagnoseAssignmentAsCondition(), clang::Sema::DiagnoseAssignmentResult(), diagnoseBadCast(), DiagnoseBadDivideOrRemainderValues(), DiagnoseBadFunctionCast(), DiagnoseBadShiftValues(), DiagnoseCastOfObjCSEL(), clang::Sema::DiagnoseCommaOperator(), clang::Sema::DiagnoseConditionalForNull(), DiagnoseConstAssignment(), diagnoseDistinctPointerComparison(), DiagnoseDivisionSizeofPointerOrArray(), clang::Sema::DiagnoseEqualityWithExtraParens(), DiagnoseFailedExplicitSpec(), DiagnoseFloatingImpCast(), diagnoseFunctionPointerToVoidComparison(), clang::Sema::DiagnoseImmediateEscalatingReason(), DiagnoseImpCast(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), DiagnoseNarrowingInInitList(), DiagnoseNullConversion(), diagnosePointerIncompatibility(), DiagnoseRecursiveConstFields(), diagnoseRepeatedUseOfWeak(), diagnoseRetainCycle(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseSelfMove(), DiagnoseShiftCompare(), diagnoseTautologicalComparison(), DiagnoseUninitializedConstRefUse(), diagnoseUnknownAnyExpr(), DiagnoseUnusedComparison(), diagnoseWellFormedUnsatisfiedConstraintExpr(), clang::Sema::diagnoseZeroToNullptrConversion(), DiagRecursiveConstraintEval(), DiagUninitUse(), doRewriteToUTF8StringBoxedExpressionHelper(), emitAndFixInvalidAsmCastLValue(), emitBug(), EmitDiagnosticForLogicalAndInLogicalOr(), clang::CodeGen::CGOpenMPRuntime::emitIfClause(), clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt(), EvaluateArrayTypeTrait(), EvaluateConvertedConstantExpression(), clang::Sema::FinalizeDeclaration(), clang::Sema::FindCompositeObjCPointerType(), FindConditionalOverload(), findRetainCycleOwner(), findTemplateParameterInType(), finishContextualImplicitConversion(), FinishOverloadedCallExpr(), clang::ento::CallEvent::getArgSourceRange(), clang::ParmVarDecl::getDefaultArgRange(), clang::NonTypeTemplateParmDecl::getDefaultArgumentLoc(), clang::Sema::getExprRange(), getNumThreads(), clang::Sema::getPrintable(), getPrivateItem(), clang::ObjCMessageExpr::getReceiverRange(), clang::CapturedStmt::getSourceRange(), clang::CXXStdInitializerListExpr::getSourceRange(), clang::ento::CallEvent::getSourceRange(), clang::ento::ObjCMethodCall::getSourceRange(), clang::TemplateArgumentLoc::getSourceRange(), GetUnreachableLoc(), handleCallbackAttr(), clang::Sema::HandleExprPropertyRefExpr(), handleFormatArgAttr(), handleFormatAttr(), handleInitPriorityAttr(), handleLayoutVersion(), handleM68kInterruptAttr(), handleMSP430InterruptAttr(), handleNonNullAttr(), handleOpenCLUnrollHint(), handleOwnershipAttr(), handlePassObjectSizeAttr(), handleSentinelAttr(), handleSubGroupSize(), handleWorkGroupSize(), clang::Expr::IgnoreUnlessSpelledInSource(), clang::Sema::ImpCastExprToType(), clang::Sema::InvalidLogicalVectorOperands(), clang::Sema::InvalidOperands(), isConfigurationValue(), isNonNegativeIntegerValue(), isNullPointerValueTemplateArgument(), clang::Expr::isUnusedResultAWarning(), LookupMemberExpr(), LookupMemberExprInRecord(), makeLaunchBoundsArgExpr(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), maybePutParensOnReceiver(), nextPathEntryRange(), objectifyExpr(), OpenCLArithmeticConversions(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::ento::ConditionBRVisitor::patternMatch(), clang::InitializationSequence::Perform(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), populateExecutedLinesWithFunctionSignature(), printExprAsWritten(), printIndicesOfElementsToConstructJson(), printPendingInitLoopJson(), clang::tooling::reallyIgnoreImplicit(), recordConversion(), clang::tooling::replaceStmtWithStmt(), clang::tooling::replaceStmtWithText(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), resolveBuiltinNewDeleteOverload(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToArraySubscriptSet(), rewriteToBoolLiteral(), rewriteToCharLiteral(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), rewriteToSubscriptGetCommon(), SemaBuiltinAnnotation(), SemaBuiltinCallWithStaticChain(), SemaBuiltinCpuIs(), SemaBuiltinCpuSupports(), SemaBuiltinFunctionStart(), SemaBuiltinLaunder(), SemaBuiltinMSVCAnnotation(), SemaBuiltinOverflow(), SemaBuiltinRWPipe(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::SemaConvertVectorExpr(), clang::TreeTransform< Derived >::TransformExprs(), tryDiagnoseOverloadedCast(), TryOrBuildParenListInitialization(), TryReinterpretCast(), clang::ConversionFixItGenerator::tryToFixConversion(), clang::Sema::tryToRecoverWithCall(), clang::Sema::VerifyBitField(), clang::Sema::VerifyIntegerConstantExpression(), clang::Sema::VerifyPositiveIntegerConstantInClause(), and clang::Sema::WarnOnPendingNoDerefs().
getStmtClass()
StmtClass clang::Stmt::getStmtClass () const inline
Definition at line 1181 of file Stmt.h.
References StmtBits.
Referenced by checkFormatStringExpr(), CheckICE(), clang::Sema::CheckLiteralKind(), children(), ClassifyInternal(), DiagUninitUse(), FindTypeTagExpr(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), getBeginLoc(), clang::CXXNamedCastExpr::getCastName(), clang::ento::SValBuilder::getConstantVal(), getEndLoc(), clang::Expr::getExprLoc(), getLoopCondition(), clang::ento::ObjCMethodCall::getMessageKind(), getPrimaryDecl(), clang::threadSafety::getSourceLiteralString(), getSourceRange(), clang::CastExpr::getTrailingFPFeatures(), clang::Expr::HasSideEffects(), ignoreTransparentExprs(), clang::Expr::isConstantInitializer(), IsGlobalLValue(), isIdenticalStmt(), isInLoopBody(), isLoop(), clang::Expr::isOBJCGCCandidate(), isObjCObjectLiteral(), clang::Expr::isSameComparisonOperand(), clang::Expr::isUnusedResultAWarning(), rebuildPotentialResultsAsNonOdrUsed(), requiresParensToAddCast(), clang::TreeTransform< Derived >::TransformCXXNamedCastExpr(), clang::TreeTransform< Derived >::TransformExpr(), clang::ASTNodeImporter::VisitExplicitCastExpr(), clang::ento::ConditionBRVisitor::VisitTerminator(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getStmtClassName()
const char * Stmt::getStmtClassName () const
Definition at line 78 of file Stmt.cpp.
References getStmtInfoTableEntry(), StmtClassNameTable::Name, and StmtBits.
Referenced by print_elem(), printIndicesOfElementsToConstructJson(), printPendingInitLoopJson(), and clang::ASTNodeImporter::VisitExpr().
IgnoreContainers() [1/2]
Stmt * Stmt::IgnoreContainers (bool IgnoreCaptured = false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
Definition at line 196 of file Stmt.cpp.
Referenced by clang::Sema::ActOnOpenMPTargetDirective(), checkOpenMPLoop(), getNestedDistributeDirective(), clang::CodeGen::CGOpenMPRuntime::getNumTeamsExprForTargetDirective(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), and IgnoreContainers().
IgnoreContainers() [2/2]
const Stmt * clang::Stmt::IgnoreContainers (bool IgnoreCaptured = false) const inline
Definition at line 1254 of file Stmt.h.
References IgnoreContainers().
operator delete() [1/5]
void clang::Stmt::operator delete (void * , const ASTContext & , unsigned) inline noexcept
Definition at line 1112 of file Stmt.h.
operator delete() [2/5]
void clang::Stmt::operator delete (void * , const ASTContext * , unsigned) inline noexcept
Definition at line 1113 of file Stmt.h.
operator delete() [3/5]
void clang::Stmt::operator delete (void * , size_t) inline noexcept
Definition at line 1114 of file Stmt.h.
operator delete() [4/5]
void clang::Stmt::operator delete (void * , void *) inline noexcept
Definition at line 1115 of file Stmt.h.
operator delete() [5/5]
void clang::Stmt::operator delete (void * data) inline protected noexcept
Definition at line 94 of file Stmt.h.
operator new() [1/4]
void * clang::Stmt::operator new (size_t bytes) inline protected noexcept
Definition at line 90 of file Stmt.h.
operator new() [2/4]
void * Stmt::operator new (size_t bytes, const ASTContext & C, unsigned alignment = 8)
Definition at line 73 of file Stmt.cpp.
References bytes(), and clang::C.
operator new() [3/4]
void * clang::Stmt::operator new (size_t bytes, const ASTContext * C, unsigned alignment = 8) inline
Definition at line 1105 of file Stmt.h.
References bytes(), and clang::C.
operator new() [4/4]
void * clang::Stmt::operator new (size_t bytes, void * mem) inline noexcept
Definition at line 1110 of file Stmt.h.
operator=() [1/2]
Stmt & clang::Stmt::operator= (const Stmt &) delete
operator=() [2/2]
Stmt & clang::Stmt::operator= (Stmt &&) delete
printJson()
void Stmt::printJson (raw_ostream & Out, PrinterHelper * Helper, const PrintingPolicy & Policy, bool AddQuotes) const
Pretty-prints in JSON format.
Definition at line 2766 of file StmtPrinter.cpp.
References clang::JsonFormat().
printPretty()
void Stmt::printPretty (raw_ostream & OS, PrinterHelper * Helper, const PrintingPolicy & Policy, unsigned Indentation = 0, StringRef NewlineSymbol = "\n", const ASTContext * Context = nullptr) const
Definition at line 2751 of file StmtPrinter.cpp.
References P.
Referenced by clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagTemplateArg(), clang::ento::ObjCStringRegion::dumpToStream(), clang::ento::StringRegion::dumpToStream(), clang::Sema::findFailedBooleanCondition(), clang::TemplateArgument::print(), print_block(), printExplicitSpecifier(), and clang::APValue::printPretty().
printPrettyControlled()
void Stmt::printPrettyControlled (raw_ostream & OS, PrinterHelper * Helper, const PrintingPolicy & Policy, unsigned Indentation = 0, StringRef NewlineSymbol = "\n", const ASTContext * Context = nullptr) const
Definition at line 2758 of file StmtPrinter.cpp.
References P.
PrintStats()
void Stmt::PrintStats () static
Definition at line 100 of file Stmt.cpp.
References StmtClassNameTable::Counter, getStmtInfoTableEntry(), StmtClassNameTable::Name, StmtClassNameTable::Size, and StmtClassInfo.
Referenced by clang::ParseAST().
ProcessODRHash()
void Stmt::ProcessODRHash (llvm::FoldingSetNodeID & ID, ODRHash & Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Parameters
ID profile information will be stored in ID.
Hash an ODRHash object which will be called where pointers would have been used in the Profile function.
Definition at line 2419 of file StmtProfile.cpp.
Profile()
void Stmt::Profile (llvm::FoldingSetNodeID & ID, const ASTContext & Context, bool Canonical, bool ProfileLambdaExpr = false) const
Produce a unique representation of the given statement.
Parameters
ID once the profiling operation is complete, will contain the unique representation of the given statement.
Context the AST context in which the statement resides
Canonical whether the profile should be based on the canonical representation of this statement (e.g., where non-type template parameters are identified by index/level rather than their declaration pointers) or the exact representation of the statement as written in the source.
ProfileLambdaExpr whether or not to profile lambda expressions. When false, the lambda expressions are never considered to be equal to other lambda expressions. When true, the lambda expressions with the same implementation will be considered to be the same. ProfileLambdaExpr should only be true when we try to merge two declarations within modules.
Definition at line 2413 of file StmtProfile.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::AreConstraintExpressionsEqual(), checkDeducedTemplateArguments(), clang::CheckEquivalentExceptionSpecImpl(), checkPreviousOMPAllocateAttribute(), DiagRecursiveConstraintEval(), getAllocatorKind(), clang::ASTContext::hasSameExpr(), clang::ASTContext::isSameConstraintExpr(), clang::ASTContext::isSameDefaultTemplateArgument(), isSameTemplateArg(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), clang::ConstantArrayType::Profile(), clang::DependentAddressSpaceType::Profile(), clang::DependentBitIntType::Profile(), clang::DependentSizedArrayType::Profile(), clang::DependentSizedExtVectorType::Profile(), clang::DependentSizedMatrixType::Profile(), clang::DependentTypeOfExprType::Profile(), clang::DependentVectorType::Profile(), and clang::TemplateArgument::Profile().
stripLabelLikeStatements() [1/2]
Stmt * clang::Stmt::stripLabelLikeStatements () inline
Definition at line 1259 of file Stmt.h.
References stripLabelLikeStatements().
stripLabelLikeStatements() [2/2]
const Stmt * Stmt::stripLabelLikeStatements () const
Strip off all label-like statements.
This will strip off label statements, case statements, attributed statements and default statements recursively.
Definition at line 218 of file Stmt.cpp.
Referenced by stripLabelLikeStatements().
viewAST()
void Stmt::viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Only works on systems with GraphViz (Mac OS X) or dot+gv installed.
Definition at line 20 of file StmtViz.cpp.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 87 of file Stmt.h.
ASTStmtWriter
friend class ASTStmtWriter friend
Definition at line 88 of file Stmt.h.
Member Data Documentation
[union]
union { ... } clang::Stmt
ArrayOrMatrixSubscriptExprBits
ArrayOrMatrixSubscriptExprBitfields clang::Stmt::ArrayOrMatrixSubscriptExprBits
Definition at line 1049 of file Stmt.h.
Referenced by clang::ArraySubscriptExpr::ArraySubscriptExpr(), clang::ArraySubscriptExpr::getRBracketLoc(), clang::MatrixSubscriptExpr::getRBracketLoc(), clang::MatrixSubscriptExpr::MatrixSubscriptExpr(), clang::ArraySubscriptExpr::setRBracketLoc(), and clang::MatrixSubscriptExpr::setRBracketLoc().
AttributedStmtBits
AttributedStmtBitfields clang::Stmt::AttributedStmtBits
Definition at line 1027 of file Stmt.h.
Referenced by clang::AttributedStmt::getAttrLoc(), and clang::AttributedStmt::getAttrs().
BinaryOperatorBits
BinaryOperatorBitfields clang::Stmt::BinaryOperatorBits
Definition at line 1053 of file Stmt.h.
Referenced by clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::getFPFeatures(), clang::BinaryOperator::getFPFeaturesInEffect(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getTrailingFPFeatures(), clang::BinaryOperator::getTrailingFPFeatures(), clang::BinaryOperator::hasStoredFPFeatures(), clang::BinaryOperator::offsetOfTrailingStorage(), clang::BinaryOperator::setHasStoredFPFeatures(), clang::BinaryOperator::setOpcode(), clang::BinaryOperator::setOperatorLoc(), and clang::BinaryOperator::setStoredFPFeatures().
BreakStmtBits
BreakStmtBitfields clang::Stmt::BreakStmtBits
Definition at line 1035 of file Stmt.h.
Referenced by clang::BreakStmt::getBreakLoc(), and clang::BreakStmt::setBreakLoc().
CallExprBits
CallExprBitfields clang::Stmt::CallExprBits
Definition at line 1050 of file Stmt.h.
Referenced by clang::CallExpr::CallExpr(), clang::CallExpr::CallExpr(), clang::CallExpr::getADLCallKind(), clang::CallExpr::getNumPreArgs(), clang::CallExpr::getTrailingFPFeatures(), clang::CallExpr::getTrailingFPFeatures(), clang::CallExpr::hasStoredFPFeatures(), and clang::CallExpr::setADLCallKind().
CastExprBits
CastExprBitfields clang::Stmt::CastExprBits
Definition at line 1052 of file Stmt.h.
Referenced by clang::CastExpr::CastExpr(), clang::CastExpr::CastExpr(), clang::CastExpr::getCastKind(), clang::CastExpr::hasStoredFPFeatures(), clang::ImplicitCastExpr::isPartOfExplicitCast(), clang::CastExpr::path_size(), clang::CastExpr::setCastKind(), and clang::ImplicitCastExpr::setIsPartOfExplicitCast().
CharacterLiteralBits
CharacterLiteralBitfields clang::Stmt::CharacterLiteralBits
Definition at line 1046 of file Stmt.h.
Referenced by clang::CharacterLiteral::CharacterLiteral(), clang::CharacterLiteral::getKind(), and clang::CharacterLiteral::setKind().
CoawaitBits
CoawaitExprBitfields clang::Stmt::CoawaitBits
Definition at line 1090 of file Stmt.h.
Referenced by clang::CoawaitExpr::CoawaitExpr(), clang::CoawaitExpr::CoawaitExpr(), clang::CoawaitExpr::isImplicit(), and clang::CoawaitExpr::setIsImplicit().
CompoundStmtBits
CompoundStmtBitfields clang::Stmt::CompoundStmtBits
Definition at line 1025 of file Stmt.h.
Referenced by clang::CompoundStmt::body_empty(), clang::CompoundStmt::CompoundStmt(), clang::CompoundStmt::CreateEmpty(), clang::CompoundStmt::hasStoredFPFeatures(), and clang::CompoundStmt::size().
ConstantExprBits
ConstantExprBitfields clang::Stmt::ConstantExprBits
Definition at line 1041 of file Stmt.h.
Referenced by clang::ConstantExpr::getAPValueResult(), clang::ConstantExpr::getResultAPValueKind(), clang::ConstantExpr::getResultAsAPSInt(), clang::ConstantExpr::getResultStorageKind(), clang::ConstantExpr::hasAPValueResult(), clang::ConstantExpr::isImmediateInvocation(), and clang::ConstantExpr::MoveIntoResult().
ContinueStmtBits
ContinueStmtBitfields clang::Stmt::ContinueStmtBits
Definition at line 1034 of file Stmt.h.
Referenced by clang::ContinueStmt::getContinueLoc(), and clang::ContinueStmt::setContinueLoc().
CXXBoolLiteralExprBits
CXXBoolLiteralExprBitfields clang::Stmt::CXXBoolLiteralExprBits
Definition at line 1066 of file Stmt.h.
Referenced by clang::CXXBoolLiteralExpr::CXXBoolLiteralExpr(), clang::CXXBoolLiteralExpr::getLocation(), clang::CXXBoolLiteralExpr::getValue(), clang::CXXBoolLiteralExpr::setLocation(), and clang::CXXBoolLiteralExpr::setValue().
CXXConstructExprBits
CXXConstructExprBitfields clang::Stmt::CXXConstructExprBits
Definition at line 1077 of file Stmt.h.
Referenced by clang::CXXConstructExpr::CXXConstructExpr(), clang::CXXConstructExpr::getConstructionKind(), clang::CXXConstructExpr::getLocation(), clang::CXXConstructExpr::hadMultipleCandidates(), clang::CXXConstructExpr::isElidable(), clang::CXXConstructExpr::isImmediateEscalating(), clang::CXXConstructExpr::isListInitialization(), clang::CXXConstructExpr::isStdInitListInitialization(), clang::CXXConstructExpr::requiresZeroInitialization(), clang::CXXConstructExpr::setConstructionKind(), clang::CXXConstructExpr::setElidable(), clang::CXXConstructExpr::setHadMultipleCandidates(), clang::CXXConstructExpr::setIsImmediateEscalating(), clang::CXXConstructExpr::setListInitialization(), clang::CXXConstructExpr::setLocation(), clang::CXXConstructExpr::setRequiresZeroInitialization(), and clang::CXXConstructExpr::setStdInitListInitialization().
CXXDefaultArgExprBits
CXXDefaultArgExprBitfields clang::Stmt::CXXDefaultArgExprBits
Definition at line 1070 of file Stmt.h.
Referenced by clang::CXXDefaultArgExpr::getExpr(), clang::CXXDefaultArgExpr::getUsedLocation(), and clang::CXXDefaultArgExpr::hasRewrittenInit().
CXXDefaultInitExprBits
CXXDefaultInitExprBitfields clang::Stmt::CXXDefaultInitExprBits
Definition at line 1071 of file Stmt.h.
Referenced by clang::CXXDefaultInitExpr::getBeginLoc(), clang::CXXDefaultInitExpr::getEndLoc(), and clang::CXXDefaultInitExpr::hasRewrittenInit().
CXXDeleteExprBits
CXXDeleteExprBitfields clang::Stmt::CXXDeleteExprBits
Definition at line 1074 of file Stmt.h.
Referenced by clang::CXXDeleteExpr::CXXDeleteExpr(), clang::CXXDeleteExpr::doesUsualArrayDeleteWantSize(), clang::CXXDeleteExpr::getBeginLoc(), clang::CXXDeleteExpr::isArrayForm(), clang::CXXDeleteExpr::isArrayFormAsWritten(), and clang::CXXDeleteExpr::isGlobalDelete().
CXXDependentScopeMemberExprBits
CXXDependentScopeMemberExprBitfields clang::Stmt::CXXDependentScopeMemberExprBits
Definition at line 1080 of file Stmt.h.
Referenced by clang::CXXDependentScopeMemberExpr::getOperatorLoc(), and clang::CXXDependentScopeMemberExpr::isArrow().
CXXNewExprBits
CXXNewExprBitfields clang::Stmt::CXXNewExprBits
Definition at line 1073 of file Stmt.h.
Referenced by clang::CXXNewExpr::doesUsualArrayDeleteWantSize(), clang::CXXNewExpr::getInitializationStyle(), clang::CXXNewExpr::getNumPlacementArgs(), clang::CXXNewExpr::hasInitializer(), clang::CXXNewExpr::isArray(), clang::CXXNewExpr::isGlobalNew(), clang::CXXNewExpr::isParenTypeId(), and clang::CXXNewExpr::passAlignment().
CXXNoexceptExprBits
CXXNoexceptExprBitfields clang::Stmt::CXXNoexceptExprBits
Definition at line 1084 of file Stmt.h.
Referenced by clang::CXXNoexceptExpr::CXXNoexceptExpr(), and clang::CXXNoexceptExpr::getValue().
CXXNullPtrLiteralExprBits
CXXNullPtrLiteralExprBitfields clang::Stmt::CXXNullPtrLiteralExprBits
Definition at line 1067 of file Stmt.h.
Referenced by clang::CXXNullPtrLiteralExpr::CXXNullPtrLiteralExpr(), clang::CXXNullPtrLiteralExpr::getLocation(), and clang::CXXNullPtrLiteralExpr::setLocation().
CXXOperatorCallExprBits
CXXOperatorCallExprBitfields clang::Stmt::CXXOperatorCallExprBits
Definition at line 1064 of file Stmt.h.
Referenced by clang::CXXOperatorCallExpr::getOperator().
CXXRewrittenBinaryOperatorBits
CXXRewrittenBinaryOperatorBitfields clang::Stmt::CXXRewrittenBinaryOperatorBits
Definition at line 1065 of file Stmt.h.
Referenced by clang::CXXRewrittenBinaryOperator::CXXRewrittenBinaryOperator(), and clang::CXXRewrittenBinaryOperator::isReversed().
CXXScalarValueInitExprBits
CXXScalarValueInitExprBitfields clang::Stmt::CXXScalarValueInitExprBits
Definition at line 1072 of file Stmt.h.
Referenced by clang::CXXScalarValueInitExpr::CXXScalarValueInitExpr(), and clang::CXXScalarValueInitExpr::getRParenLoc().
CXXThisExprBits
CXXThisExprBitfields clang::Stmt::CXXThisExprBits
Definition at line 1068 of file Stmt.h.
Referenced by clang::CXXThisExpr::CXXThisExpr(), clang::CXXThisExpr::getLocation(), clang::CXXThisExpr::isImplicit(), clang::CXXThisExpr::setImplicit(), and clang::CXXThisExpr::setLocation().
CXXThrowExprBits
CXXThrowExprBitfields clang::Stmt::CXXThrowExprBits
Definition at line 1069 of file Stmt.h.
Referenced by clang::CXXThrowExpr::CXXThrowExpr(), clang::CXXThrowExpr::getThrowLoc(), and clang::CXXThrowExpr::isThrownVariableInScope().
CXXUnresolvedConstructExprBits
CXXUnresolvedConstructExprBitfields clang::Stmt::CXXUnresolvedConstructExprBits
Definition at line 1079 of file Stmt.h.
Referenced by clang::CXXUnresolvedConstructExpr::getNumArgs().
DeclRefExprBits
DeclRefExprBitfields clang::Stmt::DeclRefExprBits
Definition at line 1043 of file Stmt.h.
Referenced by clang::DeclRefExpr::DeclRefExpr(), clang::DeclRefExpr::getLocation(), clang::DeclRefExpr::hadMultipleCandidates(), clang::DeclRefExpr::hasQualifier(), clang::DeclRefExpr::hasTemplateKWAndArgsInfo(), clang::DeclRefExpr::isImmediateEscalating(), clang::DeclRefExpr::isNonOdrUse(), clang::DeclRefExpr::refersToEnclosingVariableOrCapture(), clang::DeclRefExpr::setHadMultipleCandidates(), clang::DeclRefExpr::setIsImmediateEscalating(), and clang::DeclRefExpr::setLocation().
DependentScopeDeclRefExprBits
DependentScopeDeclRefExprBitfields clang::Stmt::DependentScopeDeclRefExprBits
Definition at line 1076 of file Stmt.h.
Referenced by clang::DependentScopeDeclRefExpr::CreateEmpty().
DoStmtBits
DoStmtBitfields clang::Stmt::DoStmtBits
Definition at line 1031 of file Stmt.h.
Referenced by clang::DoStmt::getDoLoc(), and clang::DoStmt::setDoLoc().
ExprBits
ExprBitfields clang::Stmt::ExprBits
Definition at line 1040 of file Stmt.h.
Referenced by clang::Expr::Expr(), clang::Expr::getDependence(), clang::Expr::getObjectKind(), clang::Expr::getValueKind(), clang::Expr::setDependence(), clang::Expr::setObjectKind(), and clang::Expr::setValueKind().
ExprWithCleanupsBits
ExprWithCleanupsBitfields clang::Stmt::ExprWithCleanupsBits
Definition at line 1078 of file Stmt.h.
Referenced by clang::ExprWithCleanups::cleanupsHaveSideEffects(), and clang::ExprWithCleanups::getNumObjects().
FloatingLiteralBits
FloatingLiteralBitfields clang::Stmt::FloatingLiteralBits
Definition at line 1044 of file Stmt.h.
Referenced by clang::FloatingLiteral::getRawSemantics(), clang::FloatingLiteral::getSemantics(), clang::FloatingLiteral::isExact(), clang::FloatingLiteral::setExact(), clang::FloatingLiteral::setRawSemantics(), and clang::FloatingLiteral::setSemantics().
ForStmtBits
ForStmtBitfields clang::Stmt::ForStmtBits
Definition at line 1032 of file Stmt.h.
Referenced by clang::ForStmt::ForStmt(), clang::ForStmt::getForLoc(), and clang::ForStmt::setForLoc().
GenericSelectionExprBits
GenericSelectionExprBitfields clang::Stmt::GenericSelectionExprBits
Definition at line 1056 of file Stmt.h.
Referenced by clang::GenericSelectionExpr::getGenericLoc().
GotoStmtBits
GotoStmtBitfields clang::Stmt::GotoStmtBits
Definition at line 1033 of file Stmt.h.
Referenced by clang::GotoStmt::getGotoLoc(), clang::IndirectGotoStmt::getGotoLoc(), clang::GotoStmt::setGotoLoc(), and clang::IndirectGotoStmt::setGotoLoc().
IfStmtBits
IfStmtBitfields clang::Stmt::IfStmtBits
Definition at line 1028 of file Stmt.h.
Referenced by clang::IfStmt::getIfLoc(), clang::IfStmt::getStatementKind(), clang::IfStmt::hasElseStorage(), clang::IfStmt::hasInitStorage(), clang::IfStmt::hasVarStorage(), clang::IfStmt::setIfLoc(), and clang::IfStmt::setStatementKind().
InitListExprBits
InitListExprBitfields clang::Stmt::InitListExprBits
Definition at line 1054 of file Stmt.h.
Referenced by clang::InitListExpr::hadArrayRangeDesignator(), and clang::InitListExpr::sawArrayRangeDesignator().
LabelStmtBits
LabelStmtBitfields clang::Stmt::LabelStmtBits
Definition at line 1026 of file Stmt.h.
Referenced by clang::LabelStmt::getIdentLoc(), and clang::LabelStmt::setIdentLoc().
LambdaExprBits
LambdaExprBitfields clang::Stmt::LambdaExprBits
Definition at line 1086 of file Stmt.h.
Referenced by clang::LambdaExpr::capture_size(), clang::LambdaExpr::getCaptureDefault(), clang::LambdaExpr::hasExplicitParameters(), and clang::LambdaExpr::hasExplicitResultType().
MemberExprBits
MemberExprBitfields clang::Stmt::MemberExprBits
Definition at line 1051 of file Stmt.h.
Referenced by clang::MemberExpr::Create(), clang::MemberExpr::getOperatorLoc(), clang::MemberExpr::hadMultipleCandidates(), clang::MemberExpr::isArrow(), clang::MemberExpr::isNonOdrUse(), clang::MemberExpr::setArrow(), and clang::MemberExpr::setHadMultipleCandidates().
NullStmtBits
NullStmtBitfields clang::Stmt::NullStmtBits
Definition at line 1024 of file Stmt.h.
Referenced by clang::NullStmt::getSemiLoc(), clang::NullStmt::hasLeadingEmptyMacro(), clang::NullStmt::NullStmt(), and clang::NullStmt::setSemiLoc().
ObjCIndirectCopyRestoreExprBits
ObjCIndirectCopyRestoreExprBitfields clang::Stmt::ObjCIndirectCopyRestoreExprBits
Definition at line 1093 of file Stmt.h.
Referenced by clang::ObjCIndirectCopyRestoreExpr::shouldCopy().
OpaqueValueExprBits
OpaqueValueExprBitfields clang::Stmt::OpaqueValueExprBits
Definition at line 1096 of file Stmt.h.
Referenced by clang::OpaqueValueExpr::getLocation(), clang::OpaqueValueExpr::isUnique(), clang::OpaqueValueExpr::OpaqueValueExpr(), and clang::OpaqueValueExpr::setIsUnique().
OverloadExprBits
OverloadExprBitfields clang::Stmt::OverloadExprBits
Definition at line 1081 of file Stmt.h.
Referenced by clang::OverloadExpr::getNumDecls(), clang::OverloadExpr::hasTemplateKWAndArgsInfo(), clang::OverloadExpr::OverloadExpr(), and clang::OverloadExpr::OverloadExpr().
ParenListExprBits
ParenListExprBitfields clang::Stmt::ParenListExprBits
Definition at line 1055 of file Stmt.h.
Referenced by clang::ParenListExpr::getNumExprs().
PredefinedExprBits
PredefinedExprBitfields clang::Stmt::PredefinedExprBits
Definition at line 1042 of file Stmt.h.
Referenced by clang::PredefinedExpr::getIdentKind(), clang::PredefinedExpr::getLocation(), clang::PredefinedExpr::isTransparent(), and clang::PredefinedExpr::setLocation().
PseudoObjectExprBits
PseudoObjectExprBitfields clang::Stmt::PseudoObjectExprBits
Definition at line 1057 of file Stmt.h.
Referenced by clang::PseudoObjectExpr::getResultExpr(), and clang::PseudoObjectExpr::getResultExprIndex().
RequiresExprBits
RequiresExprBitfields clang::Stmt::RequiresExprBits
Definition at line 1087 of file Stmt.h.
Referenced by clang::RequiresExpr::getBeginLoc(), clang::RequiresExpr::getRequiresKWLoc(), clang::RequiresExpr::isSatisfied(), and clang::RequiresExpr::setSatisfied().
ReturnStmtBits
ReturnStmtBitfields clang::Stmt::ReturnStmtBits
Definition at line 1036 of file Stmt.h.
Referenced by clang::ReturnStmt::getReturnLoc(), and clang::ReturnStmt::setReturnLoc().
SourceLocExprBits
SourceLocExprBitfields clang::Stmt::SourceLocExprBits
Definition at line 1058 of file Stmt.h.
Referenced by clang::SourceLocExpr::getIdentKind(), and clang::SourceLocExpr::SourceLocExpr().
StmtBits
StmtBitfields clang::Stmt::StmtBits
Definition at line 1023 of file Stmt.h.
Referenced by getStmtClass(), getStmtClassName(), and Stmt().
StmtExprBits
StmtExprBitfields clang::Stmt::StmtExprBits
Definition at line 1061 of file Stmt.h.
Referenced by clang::StmtExpr::getTemplateDepth(), and clang::StmtExpr::StmtExpr().
StringLiteralBits
StringLiteralBitfields clang::Stmt::StringLiteralBits
Definition at line 1045 of file Stmt.h.
Referenced by clang::StringLiteral::getCharByteWidth(), clang::StringLiteral::getKind(), clang::StringLiteral::getNumConcatenated(), and clang::StringLiteral::isPascal().
SubstNonTypeTemplateParmExprBits
SubstNonTypeTemplateParmExprBitfields clang::Stmt::SubstNonTypeTemplateParmExprBits
Definition at line 1085 of file Stmt.h.
Referenced by clang::SubstNonTypeTemplateParmExpr::getNameLoc(), and clang::SubstNonTypeTemplateParmExpr::SubstNonTypeTemplateParmExpr().
SwitchCaseBits
SwitchCaseBitfields clang::Stmt::SwitchCaseBits
Definition at line 1037 of file Stmt.h.
Referenced by clang::CaseStmt::caseStmtIsGNURange(), clang::SwitchCase::getKeywordLoc(), and clang::SwitchCase::setKeywordLoc().
SwitchStmtBits
SwitchStmtBitfields clang::Stmt::SwitchStmtBits
Definition at line 1029 of file Stmt.h.
Referenced by clang::SwitchStmt::getSwitchLoc(), clang::SwitchStmt::hasInitStorage(), clang::SwitchStmt::hasVarStorage(), clang::SwitchStmt::isAllEnumCasesCovered(), clang::SwitchStmt::setAllEnumCasesCovered(), and clang::SwitchStmt::setSwitchLoc().
TypeTraitExprBits
TypeTraitExprBitfields clang::Stmt::TypeTraitExprBits
Definition at line 1075 of file Stmt.h.
Referenced by clang::TypeTraitExpr::getNumArgs(), clang::TypeTraitExpr::getTrait(), and clang::TypeTraitExpr::getValue().
UnaryExprOrTypeTraitExprBits
UnaryExprOrTypeTraitExprBitfields clang::Stmt::UnaryExprOrTypeTraitExprBits
Definition at line 1048 of file Stmt.h.
Referenced by clang::UnaryExprOrTypeTraitExpr::getKind(), clang::UnaryExprOrTypeTraitExpr::isArgumentType(), clang::UnaryExprOrTypeTraitExpr::setArgument(), clang::UnaryExprOrTypeTraitExpr::setArgument(), clang::UnaryExprOrTypeTraitExpr::setKind(), clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr(), and clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr().
UnaryOperatorBits
UnaryOperatorBitfields clang::Stmt::UnaryOperatorBits
Definition at line 1047 of file Stmt.h.
Referenced by clang::UnaryOperator::canOverflow(), clang::UnaryOperator::getFPFeaturesInEffect(), clang::UnaryOperator::getFPOptionsOverride(), clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getOperatorLoc(), clang::UnaryOperator::hasStoredFPFeatures(), clang::UnaryOperator::setCanOverflow(), clang::UnaryOperator::setOpcode(), clang::UnaryOperator::setOperatorLoc(), clang::UnaryOperator::UnaryOperator(), and clang::UnaryOperator::UnaryOperator().
UnresolvedLookupExprBits
UnresolvedLookupExprBitfields clang::Stmt::UnresolvedLookupExprBits
Definition at line 1082 of file Stmt.h.
Referenced by clang::UnresolvedLookupExpr::isOverloaded(), and clang::UnresolvedLookupExpr::requiresADL().
UnresolvedMemberExprBits
UnresolvedMemberExprBitfields clang::Stmt::UnresolvedMemberExprBits
Definition at line 1083 of file Stmt.h.
Referenced by clang::UnresolvedMemberExpr::hasUnresolvedUsing(), and clang::UnresolvedMemberExpr::isArrow().
WhileStmtBits
WhileStmtBitfields clang::Stmt::WhileStmtBits
Definition at line 1030 of file Stmt.h.
Referenced by clang::WhileStmt::getWhileLoc(), clang::WhileStmt::hasVarStorage(), and clang::WhileStmt::setWhileLoc().
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/ASTDumper.cpp
lib/AST/Stmt.cpp
lib/AST/StmtPrinter.cpp
lib/AST/StmtProfile.cpp
lib/AST/StmtViz.cpp