clang: clang::SrcMgr::LineOffsetMapping Class Reference
clang::SrcMgr::LineOffsetMapping Class Reference
Mapping of line offsets into a source file.
#include "clang/Basic/SourceManager.h"
Public Member Functions
operator bool () const
unsigned size () const
ArrayRef< unsigned > getLines () const
const unsigned * begin () const
const unsigned * end () const
const unsigned & operator[] (int I) const
LineOffsetMapping ()=default
LineOffsetMapping (ArrayRef< unsigned > LineOffsets, llvm::BumpPtrAllocator &Alloc)
Static Public Member Functions
static LineOffsetMapping get (llvm::MemoryBufferRef Buffer, llvm::BumpPtrAllocator &Alloc)
Detailed Description
Mapping of line offsets into a source file.
This does not own the storage for the line numbers.
Definition at line 100 of file SourceManager.h.
Constructor & Destructor Documentation
LineOffsetMapping() [1/2]
clang::SrcMgr::LineOffsetMapping::LineOffsetMapping () default
LineOffsetMapping() [2/2]
LineOffsetMapping::LineOffsetMapping (ArrayRef< unsigned > LineOffsets, llvm::BumpPtrAllocator & Alloc)
Definition at line 1339 of file SourceManager.cpp.
Member Function Documentation
begin()
const unsigned * clang::SrcMgr::LineOffsetMapping::begin () const inline
Definition at line 111 of file SourceManager.h.
References getLines().
Referenced by clang::SourceManager::getColumnNumber(), and clang::SourceManager::getLineNumber().
end()
const unsigned * clang::SrcMgr::LineOffsetMapping::end () const inline
Definition at line 112 of file SourceManager.h.
References getLines().
Referenced by clang::SourceManager::getLineNumber().
get()
LineOffsetMapping LineOffsetMapping::get (llvm::MemoryBufferRef Buffer, llvm::BumpPtrAllocator & Alloc) static
Definition at line 1273 of file SourceManager.cpp.
References likelyhasbetween(), and N.
Referenced by clang::SourceManager::getLineNumber(), and clang::SourceManager::translateLineCol().
getLines()
ArrayRef< unsigned > clang::SrcMgr::LineOffsetMapping::getLines () const inline
Definition at line 107 of file SourceManager.h.
References size().
Referenced by begin(), end(), and operator[]().
operator bool()
clang::SrcMgr::LineOffsetMapping::operator bool () const inline explicit
Definition at line 102 of file SourceManager.h.
operator[]()
const unsigned & clang::SrcMgr::LineOffsetMapping::operator[] (int I) const inline
Definition at line 113 of file SourceManager.h.
References getLines().
size()
unsigned clang::SrcMgr::LineOffsetMapping::size () const inline
Definition at line 103 of file SourceManager.h.
Referenced by clang::SourceManager::getColumnNumber(), getLines(), and clang::SourceManager::translateLineCol().
The documentation for this class was generated from the following files:
include/clang/Basic/SourceManager.h
lib/Basic/SourceManager.cpp