clang: clang::Token Class Reference
clang::Token Class Reference
Token - This structure provides full information about a lexed token.
#include "clang/Lex/Token.h"
Public Types
enum TokenFlags {
StartOfLine = 0x01 , LeadingSpace = 0x02 , DisableExpand = 0x04 , NeedsCleaning = 0x08 ,
LeadingEmptyMacro = 0x10 , HasUDSuffix = 0x20 , HasUCN = 0x40 , IgnoredComma = 0x80 ,
StringifiedInMacro = 0x100 , CommaAfterElided = 0x200 , IsEditorPlaceholder = 0x400 , IsReinjected = 0x800
}
Public Member Functions
tok::TokenKind getKind () const
void setKind (tok::TokenKind K)
bool is (tok::TokenKind K) const
is/isNot - Predicates to check if this token is a specific kind, as in "if (Tok.is(tok::l_brace)) {...}".
bool isNot (tok::TokenKind K) const
bool isOneOf (tok::TokenKind K1, tok::TokenKind K2) const
template<typename... Ts>
bool isOneOf (tok::TokenKind K1, Ts... Ks) const
bool isAnyIdentifier () const
Return true if this is a raw identifier (when lexing in raw mode) or a non-keyword identifier (when lexing in non-raw mode).
bool isLiteral () const
Return true if this is a "literal", like a numeric constant, string, etc.
bool isAnnotation () const
Return true if this is any of tok::annot_* kind tokens.
bool isRegularKeywordAttribute () const
Return true if the token is a keyword that is parsed in the same position as a standard attribute, but that has semantic meaning and so cannot be a true attribute.
SourceLocation getLocation () const
Return a source location identifier for the specified offset in the current file.
unsigned getLength () const
void setLocation (SourceLocation L)
void setLength (unsigned Len)
SourceLocation getAnnotationEndLoc () const
void setAnnotationEndLoc (SourceLocation L)
SourceLocation getLastLoc () const
SourceLocation getEndLoc () const
SourceRange getAnnotationRange () const
SourceRange of the group of tokens that this annotation token represents.
void setAnnotationRange (SourceRange R)
const char * getName () const
void startToken ()
Reset all flags to cleared.
bool hasPtrData () const
IdentifierInfo * getIdentifierInfo () const
void setIdentifierInfo (IdentifierInfo *II)
const void * getEofData () const
void setEofData (const void *D)
StringRef getRawIdentifier () const
getRawIdentifier - For a raw identifier token (i.e., an identifier lexed in raw mode), returns a reference to the text substring in the buffer if known.
void setRawIdentifierData (const char *Ptr)
const char * getLiteralData () const
getLiteralData - For a literal token (numeric constant, string, etc), this returns a pointer to the start of it in the text buffer if known, null otherwise.
void setLiteralData (const char *Ptr)
void * getAnnotationValue () const
void setAnnotationValue (void *val)
void setFlag (TokenFlags Flag)
Set the specified flag.
bool getFlag (TokenFlags Flag) const
Get the specified flag.
void clearFlag (TokenFlags Flag)
Unset the specified flag.
unsigned getFlags () const
Return the internal represtation of the flags.
void setFlagValue (TokenFlags Flag, bool Val)
Set a flag to either true or false.
bool isAtStartOfLine () const
isAtStartOfLine - Return true if this token is at the start of a line.
bool hasLeadingSpace () const
Return true if this token has whitespace before it.
bool isExpandDisabled () const
Return true if this identifier token should never be expanded in the future, due to C99 6.10.3.4p2.
bool isObjCAtKeyword (tok::ObjCKeywordKind objcKey) const
Return true if we have an ObjC keyword identifier.
tok::ObjCKeywordKind getObjCKeywordID () const
Return the ObjC keyword kind.
bool needsCleaning () const
Return true if this token has trigraphs or escaped newlines in it.
bool hasLeadingEmptyMacro () const
Return true if this token has an empty macro before it.
bool hasUDSuffix () const
Return true if this token is a string or character literal which has a ud-suffix.
bool hasUCN () const
Returns true if this token contains a universal character name.
bool stringifiedInMacro () const
Returns true if this token is formed by macro by stringizing or charizing operator.
bool commaAfterElided () const
Returns true if the comma after this token was elided.
bool isEditorPlaceholder () const
Returns true if this token is an editor placeholder.
Detailed Description
Token - This structure provides full information about a lexed token.
It is not intended to be space efficient, it is intended to return as much information as possible about each returned token. This is expected to be compressed into a smaller form if memory footprint is important.
The parser can create a special "annotation token" representing a stream of tokens that were parsed and semantically resolved, e.g.: "foo::MyClass<int>" can be represented by a single typename annotation token that carries information about the SourceRange of the tokens and the type object.
Definition at line 35 of file Token.h.
Member Enumeration Documentation
TokenFlags
enum clang::Token::TokenFlags
Enumerator
StartOfLine
LeadingSpace
DisableExpand
NeedsCleaning
LeadingEmptyMacro
HasUDSuffix
HasUCN
IgnoredComma
StringifiedInMacro
CommaAfterElided
IsEditorPlaceholder
IsReinjected
Definition at line 73 of file Token.h.
Member Function Documentation
clearFlag()
void clang::Token::clearFlag (TokenFlags Flag) inline
Unset the specified flag.
Definition at line 253 of file Token.h.
Referenced by setFlagValue().
commaAfterElided()
bool clang::Token::commaAfterElided () const inline
Returns true if the comma after this token was elided.
Definition at line 310 of file Token.h.
References CommaAfterElided, and getFlag().
getAnnotationEndLoc()
SourceLocation clang::Token::getAnnotationEndLoc () const inline
Definition at line 145 of file Token.h.
References clang::SourceLocation::getFromRawEncoding(), and isAnnotation().
Referenced by clang::ASTWriter::AddToken(), getAnnotationRange(), getEndLoc(), and getLastLoc().
getAnnotationRange()
SourceRange clang::Token::getAnnotationRange () const inline
SourceRange of the group of tokens that this annotation token represents.
Definition at line 165 of file Token.h.
References getAnnotationEndLoc(), and getLocation().
Referenced by clang::Parser::TryAnnotateTypeOrScopeToken().
getAnnotationValue()
void * clang::Token::getAnnotationValue () const inline
Definition at line 233 of file Token.h.
References isAnnotation().
Referenced by clang::ASTWriter::AddToken(), clang::Parser::ParseTopLevelDecl(), and PrintPreprocessedTokens().
getEndLoc()
SourceLocation clang::Token::getEndLoc () const inline
Definition at line 158 of file Token.h.
References getAnnotationEndLoc(), getLength(), getLocation(), clang::SourceLocation::getLocWithOffset(), and isAnnotation().
Referenced by fixSeparateAttrArgAndNumber(), getEntityEndLoc(), and parseDeclareSimdClauses().
getEofData()
const void * clang::Token::getEofData () const inline
Definition at line 199 of file Token.h.
References is().
getFlag()
bool clang::Token::getFlag (TokenFlags Flag) const inline
Get the specified flag.
Definition at line 248 of file Token.h.
Referenced by commaAfterElided(), hasLeadingEmptyMacro(), hasLeadingSpace(), hasUCN(), hasUDSuffix(), isAtStartOfLine(), isEditorPlaceholder(), isExpandDisabled(), needsCleaning(), and stringifiedInMacro().
getFlags()
unsigned clang::Token::getFlags () const inline
Return the internal represtation of the flags.
This is only intended for low-level operations such as writing tokens to disk.
Definition at line 261 of file Token.h.
Referenced by clang::ASTWriter::AddToken().
getIdentifierInfo()
IdentifierInfo * clang::Token::getIdentifierInfo () const inline
Definition at line 186 of file Token.h.
References is(), isAnnotation(), isLiteral(), and isNot().
Referenced by clang::Sema::ActOnPragmaUnused(), AddDefinedMacroToHash(), clang::ASTWriter::AddToken(), clang::MacroArgs::ArgNeedsPreexpansion(), clang::TokenConcatenation::AvoidConcat(), clang::Preprocessor::CheckMacroName(), diagnoseAutoModuleImport(), clang::MacroInfo::dump(), dumpTokenInto(), EvaluateDefined(), EvaluateFeatureLikeBuiltinMacro(), EvaluateValue(), ExpectFeatureIdentifierInfo(), GetFirstChar(), getIdentifier(), getObjCKeywordID(), clang::Lexer::getSpelling(), clang::Preprocessor::getSpelling(), clang::Preprocessor::HandleDirective(), clang::PragmaNamespace::HandlePragma(), clang::format::FormatToken::is(), isConfigurationPattern(), clang::format::isFunctionDeclarationName(), clang::MacroInfo::isIdenticalTo(), isObjCAtKeyword(), isSameToken(), isTrivialSingleTokenExpansion(), isWideStringLiteralFromMacro(), clang::TokenLexer::Lex(), LexModuleNameComponent(), clang::Preprocessor::LexOnOffSwitch(), clang::MacroPPCallbacks::MacroDefined(), clang::detail::MacroExpansionRangeRecorder::MacroExpands(), clang::MacroPPCallbacks::MacroUndefined(), clang::format::mustBeJSIdent(), ParseAlignPragma(), parseDeclareSimdClauses(), clang::Parser::parseMapperModifier(), clang::Parser::ParseMSAsmIdentifier(), parseOpenMPReductionId(), clang::Parser::ParseOpenMPReservedLocator(), clang::Parser::ParseOpenMPVarList(), clang::Parser::ParseTopLevelDecl(), clang::Parser::ParseUnqualifiedId(), PragmaLoopHintString(), PrintPreprocessedTokens(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
getKind()
tok::TokenKind clang::Token::getKind () const inline
Definition at line 93 of file Token.h.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnStringLiteral(), clang::ASTWriter::AddToken(), atOrBeforeSeparation(), clang::TokenConcatenation::AvoidConcat(), clang::Sema::CheckConstraintExpression(), clang::Preprocessor::CheckMacroName(), clang::Lexer::ComputePreamble(), contains(), clang::MacroInfo::dump(), clang::Preprocessor::DumpToken(), EvaluateDirectiveSubExpr(), EvaluateFeatureLikeBuiltinMacro(), EvaluateHasIncludeCommon(), EvaluateValue(), getBeginningOfFileToken(), getEntityEndLoc(), getIdentifier(), getSpellingSlow(), clang::Preprocessor::HandlePragmaModuleBuild(), isAnnotation(), isAnyIdentifier(), isConfigurationPattern(), clang::MacroInfo::isIdenticalTo(), isLiteral(), clang::Preprocessor::IsPreviousCachedToken(), isRegularKeywordAttribute(), isSameToken(), clang::Parser::ParseConstraintLogicalAndExpression(), parseOpenMPReductionId(), clang::Parser::ParseTopLevelDecl(), clang::Parser::ParseUnqualifiedId(), PrintPreprocessedTokens(), clang::ASTReader::ReadToken(), clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks(), clang::format::ShouldBreakBeforeBrace(), clang::Parser::SkipMalformedDecl(), clang::Parser::SkipUntil(), and clang::MacroArgs::StringifyArgument().
getLastLoc()
SourceLocation clang::Token::getLastLoc () const inline
Definition at line 154 of file Token.h.
References getAnnotationEndLoc(), getLocation(), and isAnnotation().
Referenced by clang::Parser::TryAnnotateTypeOrScopeToken().
getLength()
unsigned clang::Token::getLength () const inline
Definition at line 134 of file Token.h.
References isAnnotation().
Referenced by clang::Sema::ActOnNumericConstant(), clang::ASTWriter::AddToken(), clang::TokenConcatenation::AvoidConcat(), clang::MacroInfo::dump(), clang::Preprocessor::DumpToken(), dumpTokenInto(), EmitAlphaCounter(), clang::Lexer::findLocationAfterToken(), fixSeparateAttrArgAndNumber(), getBeginningOfFileToken(), getEndLoc(), GetFirstChar(), GetLineValue(), clang::StringLiteralParser::getOffsetOfStringByte(), getRawIdentifier(), clang::Lexer::getSpelling(), clang::Lexer::getSpelling(), clang::Lexer::getSpelling(), clang::Preprocessor::getSpelling(), getSpellingSlow(), clang::TokenLexer::Lex(), clang::Preprocessor::LexHeaderName(), clang::detail::MacroExpansionRangeRecorder::MacroExpands(), clang::Lexer::MeasureTokenLength(), NormalizeLine(), PrintPreprocessedTokens(), clang::RewriteMacrosInInput(), clang::MacroArgs::StringifyArgument(), and UseNSOptionsMacro().
getLiteralData()
const char * clang::Token::getLiteralData () const inline
getLiteralData - For a literal token (numeric constant, string, etc), this returns a pointer to the start of it in the text buffer if known, null otherwise.
Definition at line 224 of file Token.h.
References isLiteral().
Referenced by clang::MacroInfo::dump(), dumpTokenInto(), fixSeparateAttrArgAndNumber(), GetFirstChar(), clang::Lexer::getSpelling(), PrintPreprocessedTokens(), and UseNSOptionsMacro().
getLocation()
SourceLocation clang::Token::getLocation () const inline
Return a source location identifier for the specified offset in the current file.
Definition at line 131 of file Token.h.
References clang::SourceLocation::getFromRawEncoding().
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnPragmaUnused(), clang::Sema::ActOnStringLiteral(), clang::Sema::ActOnUnevaluatedStringLiteral(), clang::arcmt::trans::MigrationContext::addPropertyAttribute(), clang::ASTWriter::AddToken(), clang::TokenConcatenation::AvoidConcat(), clang::Preprocessor::CheckEndOfDirective(), clang::Preprocessor::CheckMacroName(), ComputeDATE_TIME(), clang::Lexer::ComputePreamble(), clang::Parser::Diag(), diagnoseUnexpectedOperator(), clang::Preprocessor::DiscardUntilEndOfDirective(), clang::DoPrintPreprocessedInput(), clang::Preprocessor::DumpToken(), EvaluateDefined(), EvaluateDirectiveSubExpr(), EvaluateFeatureLikeBuiltinMacro(), EvaluateHasIncludeCommon(), EvaluateValue(), clang::Parser::ExitScope(), ExpectFeatureIdentifierInfo(), findDirectives(), clang::Lexer::findLocationAfterToken(), clang::arcmt::trans::findSemiAfterLocation(), FixDigraph(), clang::format::UnwrappedLineFormatter::format(), getAnnotationRange(), getBeginningOfFileToken(), getEndLoc(), GetFirstChar(), clang::RawComment::getFormattedLines(), getLastLoc(), GetLineValue(), clang::ModuleMapParser::getLocation(), clang::StringLiteralParser::getOffsetOfStringByte(), clang::Lexer::getSpelling(), clang::Lexer::getSpelling(), clang::Preprocessor::HandleDirective(), clang::Preprocessor::HandlePragmaDependency(), clang::Preprocessor::HandlePragmaHdrstop(), clang::Preprocessor::HandlePragmaIncludeAlias(), clang::Preprocessor::HandlePragmaMark(), clang::Preprocessor::HandlePragmaModuleBuild(), clang::Preprocessor::HandlePragmaPopMacro(), clang::Preprocessor::HandlePragmaSystemHeader(), clang::TokenLexer::Init(), clang::Preprocessor::IsPreviousCachedToken(), clang::TokenLexer::Lex(), clang::Preprocessor::LexHeaderName(), LexModuleNameComponent(), LocPropertyAttribute(), clang::MacroPPCallbacks::MacroDefined(), clang::detail::MacroExpansionRangeRecorder::MacroExpands(), clang::MacroPPCallbacks::MacroUndefined(), clang::tooling::maybeExtendRange(), NormalizeLine(), ParseAlignPragma(), clang::Parser::ParseAssignmentExpression(), parseDeclareSimdClauses(), ParseLoopHintValue(), clang::Parser::parseMapperModifier(), clang::Parser::parseMapTypeModifiers(), clang::Parser::ParseMSAsmIdentifier(), clang::Parser::ParseOpenMPParensExpr(), parseOpenMPReductionId(), parseOpenMPSimpleClause(), clang::Parser::ParseOpenMPVarList(), clang::Preprocessor::ParsePragmaPushOrPopMacro(), clang::Preprocessor::parseSimpleIntegerLiteral(), clang::Parser::ParseTopLevelDecl(), clang::Parser::ParseUnqualifiedId(), ReadLineMarkerFlags(), clang::RewriteMacrosInInput(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks(), startsWithNewline(), clang::Parser::TryAnnotateTypeOrScopeToken(), clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(), and updateConsecutiveMacroArgTokens().
getName()
const char * clang::Token::getName () const inline
Definition at line 173 of file Token.h.
References clang::tok::getTokenName().
Referenced by clang::MacroInfo::dump().
getObjCKeywordID()
tok::ObjCKeywordKind Token::getObjCKeywordID () const
Return the ObjC keyword kind.
getObjCKeywordID - Return the ObjC keyword kind.
Definition at line 66 of file Lexer.cpp.
References getIdentifierInfo(), clang::IdentifierInfo::getObjCKeywordID(), and isAnnotation().
getRawIdentifier()
StringRef clang::Token::getRawIdentifier () const inline
getRawIdentifier - For a raw identifier token (i.e., an identifier lexed in raw mode), returns a reference to the text substring in the buffer if known.
Definition at line 212 of file Token.h.
References getLength(), and is().
Referenced by clang::arcmt::trans::MigrationContext::addPropertyAttribute(), clang::Lexer::ComputePreamble(), clang::Lexer::getSpelling(), clang::Preprocessor::HandlePragmaModuleBuild(), LocPropertyAttribute(), and clang::arcmt::trans::MigrationContext::rewritePropertyAttribute().
hasLeadingEmptyMacro()
bool clang::Token::hasLeadingEmptyMacro () const inline
Return true if this token has an empty macro before it.
Definition at line 296 of file Token.h.
References getFlag(), and LeadingEmptyMacro.
Referenced by clang::Preprocessor::LexHeaderName().
hasLeadingSpace()
bool clang::Token::hasLeadingSpace () const inline
Return true if this token has whitespace before it.
Definition at line 279 of file Token.h.
References getFlag(), and LeadingSpace.
Referenced by buildMSAsmString(), clang::MacroInfo::dump(), clang::Preprocessor::DumpToken(), clang::TokenLexer::Init(), clang::TokenLexer::Init(), clang::MacroInfo::isIdenticalTo(), clang::Preprocessor::LexHeaderName(), PrintMacroDefinition(), clang::RewriteMacrosInInput(), and clang::MacroArgs::StringifyArgument().
hasPtrData()
bool clang::Token::hasPtrData () const inline
Definition at line 184 of file Token.h.
hasUCN()
bool clang::Token::hasUCN () const inline
Returns true if this token contains a universal character name.
Definition at line 303 of file Token.h.
References getFlag(), and HasUCN.
Referenced by clang::Lexer::getSpelling(), and clang::Preprocessor::getSpelling().
hasUDSuffix()
bool clang::Token::hasUDSuffix () const inline
Return true if this token is a string or character literal which has a ud-suffix.
Definition at line 300 of file Token.h.
References getFlag(), and HasUDSuffix.
Referenced by clang::TokenConcatenation::AvoidConcat(), EvaluateValue(), LexModuleNameComponent(), and clang::Preprocessor::ParsePragmaPushOrPopMacro().
is()
bool clang::Token::is (tok::TokenKind K) const inline
is/isNot - Predicates to check if this token is a specific kind, as in "if (Tok.is(tok::l_brace)) {...}".
Definition at line 98 of file Token.h.
Referenced by clang::Sema::ActOnNameClassifiedAsNonType(), clang::arcmt::trans::MigrationContext::addPropertyAttribute(), clang::TokenConcatenation::AvoidConcat(), buildMSAsmString(), clang::Sema::CheckConstraintExpression(), clang::Preprocessor::CheckEndOfDirective(), clang::Preprocessor::CheckMacroName(), clang::Sema::ClassifyName(), clang::Preprocessor::CreateString(), diagnoseUnexpectedOperator(), clang::DoPrintPreprocessedInput(), EvaluateDefined(), EvaluateHasIncludeCommon(), EvaluateValue(), findDirectives(), FormatToken(), getEofData(), clang::RawComment::getFormattedLines(), getIdentifier(), getIdentifierInfo(), getRawIdentifier(), clang::Lexer::getSpelling(), clang::Preprocessor::HandleMicrosoftCommentPaste(), clang::Preprocessor::HandlePragmaHdrstop(), clang::Preprocessor::HandlePragmaIncludeAlias(), clang::Preprocessor::HandlePragmaModuleBuild(), clang::Preprocessor::HandlePragmaPoison(), clang::format::FormatToken::is(), IsCommonTypo(), isMapModifier(), clang::TokenLexer::isNextTokenLParen(), isOneOf(), isOneOf(), clang::TokenLexer::isParsingPreprocessorDirective(), isResultTypeOrTemplate(), isWideStringLiteralFromMacro(), clang::TokenLexer::Lex(), clang::Preprocessor::LexHeaderName(), LexModuleNameComponent(), LexRawTokensFromMainFile(), LocPropertyAttribute(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::tooling::maybeExtendRange(), clang::IncrementalParser::Parse(), clang::Parser::ParseAssignmentExpression(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::Parser::ParseConstraintLogicalOrExpression(), parseDeclareSimdClauses(), ParseLoopHintValue(), parseMapType(), clang::Parser::parseMapTypeModifiers(), clang::Parser::ParseMSAsmIdentifier(), parseOpenMPReductionId(), clang::Parser::ParseOpenMPReservedLocator(), clang::Parser::ParseOpenMPVarList(), clang::Preprocessor::parseSimpleIntegerLiteral(), clang::Parser::ParseUnqualifiedId(), clang::CommaSeparatedList::precomputeFormattingInfos(), PrintPreprocessedTokens(), ReadLineMarkerFlags(), clang::Lexer::ReadToEndOfLine(), clang::RewriteIncludesInInput(), clang::RewriteMacrosInInput(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), setEofData(), setRawIdentifierData(), clang::Preprocessor::SkipTokensWhileUsingPCH(), clang::Parser::SkipUntil(), clang::MacroArgs::StringifyArgument(), clang::format::switchesFormatting(), clang::TokenRewriter::TokenRewriter(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
isAnnotation()
bool clang::Token::isAnnotation () const inline
Return true if this is any of tok::annot_* kind tokens.
Definition at line 120 of file Token.h.
References getKind(), and clang::tok::isAnnotation().
Referenced by clang::ASTWriter::AddToken(), clang::TokenConcatenation::AvoidConcat(), clang::Preprocessor::DumpToken(), dumpTokenInto(), ExpectFeatureIdentifierInfo(), getAnnotationEndLoc(), getAnnotationValue(), getEndLoc(), getIdentifierInfo(), getLastLoc(), getLength(), getObjCKeywordID(), isObjCAtKeyword(), clang::TokenLexer::Lex(), LexModuleNameComponent(), parseOpenMPDirectiveKind(), parseOpenMPSimpleClause(), PrintPreprocessedTokens(), clang::ASTReader::ReadToken(), setAnnotationEndLoc(), setAnnotationValue(), setLength(), and clang::Parser::TryAnnotateTypeOrScopeToken().
isAnyIdentifier()
bool clang::Token::isAnyIdentifier () const inline
Return true if this is a raw identifier (when lexing in raw mode) or a non-keyword identifier (when lexing in non-raw mode).
Definition at line 109 of file Token.h.
References getKind(), and clang::tok::isAnyIdentifier().
isAtStartOfLine()
bool clang::Token::isAtStartOfLine () const inline
isAtStartOfLine - Return true if this token is at the start of a line.
Definition at line 275 of file Token.h.
References getFlag(), and StartOfLine.
Referenced by buildMSAsmString(), clang::Lexer::ComputePreamble(), clang::Preprocessor::DumpToken(), clang::Preprocessor::HandlePragmaModuleBuild(), clang::TokenLexer::Init(), clang::TokenLexer::Init(), clang::MacroInfo::isIdenticalTo(), clang::Preprocessor::LexHeaderName(), NormalizeLine(), PrintPreprocessedTokens(), clang::RewriteMacrosInInput(), clang::Parser::SkipMalformedDecl(), and clang::MacroArgs::StringifyArgument().
isEditorPlaceholder()
bool clang::Token::isEditorPlaceholder () const inline
Returns true if this token is an editor placeholder.
Editor placeholders are produced by the code-completion engine and are represented as characters between '<#' and '#>' in the source code. The lexer uses identifier tokens to represent placeholders.
Definition at line 317 of file Token.h.
References getFlag(), and IsEditorPlaceholder.
Referenced by clang::Parser::TryAnnotateTypeOrScopeToken().
isExpandDisabled()
bool clang::Token::isExpandDisabled () const inline
Return true if this identifier token should never be expanded in the future, due to C99 6.10.3.4p2.
Definition at line 283 of file Token.h.
References DisableExpand, and getFlag().
Referenced by clang::Preprocessor::DumpToken().
isLiteral()
bool clang::Token::isLiteral () const inline
Return true if this is a "literal", like a numeric constant, string, etc.
Definition at line 115 of file Token.h.
References getKind(), and clang::tok::isLiteral().
Referenced by clang::Preprocessor::CreateString(), clang::MacroInfo::dump(), dumpTokenInto(), GetFirstChar(), getIdentifierInfo(), getLiteralData(), clang::Lexer::getSpelling(), isWideStringLiteralFromMacro(), clang::format::mustBeJSIdentOrValue(), PrintPreprocessedTokens(), setLiteralData(), and UseNSOptionsMacro().
isNot()
bool clang::Token::isNot (tok::TokenKind K) const inline
Definition at line 99 of file Token.h.
Referenced by clang::arcmt::trans::MigrationContext::addPropertyAttribute(), clang::MacroArgs::ArgNeedsPreexpansion(), clang::TokenConcatenation::AvoidConcat(), clang::Sema::ClassifyName(), clang::Preprocessor::DiscardUntilEndOfDirective(), DoPrintMacros(), dumpTokenInto(), EvaluateDefined(), EvaluateDirectiveSubExpr(), EvaluateFeatureLikeBuiltinMacro(), EvaluateHasIncludeCommon(), EvaluateValue(), clang::DumpRawTokensAction::ExecuteAction(), clang::DumpTokensAction::ExecuteAction(), clang::PreprocessOnlyAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), findDirectives(), clang::Lexer::findLocationAfterToken(), clang::arcmt::trans::findSemiAfterLocation(), clang::MacroArgs::getArgLength(), clang::RawComment::getFormattedLines(), getIdentifierInfo(), clang::format::getLastNonComment(), GetLineValue(), clang::Preprocessor::getSpelling(), clang::Preprocessor::HandleMicrosoftCommentPaste(), clang::Preprocessor::HandlePragmaDependency(), clang::Preprocessor::HandlePragmaHdrstop(), clang::Preprocessor::HandlePragmaIncludeAlias(), clang::Preprocessor::HandlePragmaModuleBuild(), clang::Preprocessor::HandlePragmaPoison(), clang::format::isC78ParameterDecl(), clang::Preprocessor::LexHeaderName(), LexModuleName(), clang::Preprocessor::LexOnOffSwitch(), LexRawTokensFromMainFile(), LocPropertyAttribute(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), ParseAlignPragma(), parseDeclareSimdClauses(), ParseLoopHintValue(), clang::Parser::parseMapperModifier(), clang::Parser::ParseMSAsmIdentifier(), parseOpenMPSimpleClause(), clang::Parser::ParseOpenMPVarList(), clang::Preprocessor::ParsePragmaPushOrPopMacro(), clang::Parser::ParseUnqualifiedId(), clang::RewriteIncludesInInput(), clang::RewriteMacrosInInput(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), clang::Parser::SkipUntil(), clang::MacroArgs::StringifyArgument(), clang::format::tokenCanStartNewLine(), and clang::TokenRewriter::TokenRewriter().
isObjCAtKeyword()
bool Token::isObjCAtKeyword (tok::ObjCKeywordKind objcKey) const
Return true if we have an ObjC keyword identifier.
isObjCAtKeyword - Return true if we have an ObjC keyword identifier.
Definition at line 57 of file Lexer.cpp.
References getIdentifierInfo(), and isAnnotation().
isOneOf() [1/2]
bool clang::Token::isOneOf (tok::TokenKind K1, tok::TokenKind K2) const inline
Definition at line 100 of file Token.h.
References is().
Referenced by clang::TokenConcatenation::AvoidConcat(), clang::Sema::ClassifyName(), EvaluateFeatureLikeBuiltinMacro(), clang::format::isC78ParameterDecl(), clang::format::isC78Type(), isConfigurationPattern(), isEndOfTemplateArgument(), isMapType(), clang::Preprocessor::LexHeaderName(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::CommaSeparatedList::precomputeFormattingInfos(), and clang::Parser::SkipMalformedDecl().
isOneOf() [2/2]
template<typename... Ts> bool clang::Token::isOneOf (tok::TokenKind K1, Ts... Ks) const inline
Definition at line 103 of file Token.h.
References is(), and isOneOf().
isRegularKeywordAttribute()
bool clang::Token::isRegularKeywordAttribute () const inline
Return true if the token is a keyword that is parsed in the same position as a standard attribute, but that has semantic meaning and so cannot be a true attribute.
Definition at line 125 of file Token.h.
References getKind(), and clang::tok::isRegularKeywordAttribute().
needsCleaning()
bool clang::Token::needsCleaning () const inline
Return true if this token has trigraphs or escaped newlines in it.
Definition at line 292 of file Token.h.
References getFlag(), and NeedsCleaning.
Referenced by clang::Lexer::ComputePreamble(), clang::Preprocessor::DumpToken(), dumpTokenInto(), GetFirstChar(), clang::Lexer::getSpelling(), clang::Lexer::getSpelling(), clang::Lexer::getSpelling(), clang::Preprocessor::getSpelling(), getSpellingSlow(), and PrintPreprocessedTokens().
setAnnotationEndLoc()
void clang::Token::setAnnotationEndLoc (SourceLocation L) inline
Definition at line 149 of file Token.h.
References clang::SourceLocation::getRawEncoding(), and isAnnotation().
Referenced by clang::Preprocessor::EnterAnnotationToken(), clang::ASTReader::ReadToken(), setAnnotationRange(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
setAnnotationRange()
void clang::Token::setAnnotationRange (SourceRange R) inline
Definition at line 168 of file Token.h.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), setAnnotationEndLoc(), and setLocation().
setAnnotationValue()
void clang::Token::setAnnotationValue (void * val) inline
Definition at line 237 of file Token.h.
References isAnnotation().
Referenced by clang::Preprocessor::EnterAnnotationToken(), and clang::ASTReader::ReadToken().
setEofData()
void clang::Token::setEofData (const void * D) inline
Definition at line 203 of file Token.h.
References is().
setFlag()
void clang::Token::setFlag (TokenFlags Flag) inline
Set the specified flag.
Definition at line 243 of file Token.h.
Referenced by clang::TokenLexer::Lex(), clang::ASTReader::ReadToken(), and setFlagValue().
setFlagValue()
void clang::Token::setFlagValue (TokenFlags Flag, bool Val) inline
Set a flag to either true or false.
Definition at line 266 of file Token.h.
References clearFlag(), and setFlag().
Referenced by clang::TokenLexer::Lex(), and clang::Preprocessor::LexHeaderName().
setIdentifierInfo()
void clang::Token::setIdentifierInfo (IdentifierInfo * II) inline
Definition at line 195 of file Token.h.
Referenced by clang::Sema::ActOnIdExpression(), EvaluateHasIncludeCommon(), clang::Preprocessor::LexAfterModuleImport(), and clang::ASTReader::ReadToken().
setKind()
void clang::Token::setKind (tok::TokenKind K) inline
Definition at line 94 of file Token.h.
Referenced by clang::Sema::ActOnIdExpression(), clang::TokenRewriter::AddTokenBefore(), clang::Preprocessor::EnterAnnotationToken(), EvaluateFeatureLikeBuiltinMacro(), findDirectives(), FixDigraph(), GenerateNewArgTokens(), clang::Preprocessor::HandleDirective(), clang::TokenLexer::Lex(), clang::Preprocessor::LexAfterModuleImport(), clang::Preprocessor::LexHeaderName(), ParseLoopHintValue(), clang::Parser::ParseMSAsmIdentifier(), clang::Preprocessor::ParsePragmaPushOrPopMacro(), clang::Parser::Parser(), clang::Parser::ParseUnqualifiedId(), clang::ASTReader::ReadToken(), clang::format::ScopedMacroState::ScopedMacroState(), clang::MacroArgs::StringifyArgument(), clang::Parser::TryAnnotateTypeOrScopeToken(), clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(), and clang::VAOptExpansionContext::VAOptExpansionContext().
setLength()
void clang::Token::setLength (unsigned Len) inline
Definition at line 140 of file Token.h.
References isAnnotation().
Referenced by clang::TokenRewriter::AddTokenBefore(), clang::Preprocessor::CreateString(), FixDigraph(), GenerateNewArgTokens(), clang::Preprocessor::LexAfterModuleImport(), and clang::ASTReader::ReadToken().
setLiteralData()
void clang::Token::setLiteralData (const char * Ptr) inline
Definition at line 228 of file Token.h.
References isLiteral().
Referenced by clang::Preprocessor::CreateString().
setLocation()
void clang::Token::setLocation (SourceLocation L) inline
Definition at line 139 of file Token.h.
References clang::SourceLocation::getRawEncoding().
Referenced by clang::Sema::ActOnIdExpression(), clang::TokenRewriter::AddTokenBefore(), clang::Preprocessor::CreateString(), clang::Preprocessor::EnterAnnotationToken(), FixDigraph(), GenerateNewArgTokens(), clang::TokenLexer::Lex(), clang::Preprocessor::LexAfterModuleImport(), ParseLoopHintValue(), clang::ASTReader::ReadToken(), setAnnotationRange(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
setRawIdentifierData()
void clang::Token::setRawIdentifierData (const char * Ptr) inline
Definition at line 216 of file Token.h.
References is().
Referenced by clang::Preprocessor::CreateString().
startToken()
void clang::Token::startToken () inline
Reset all flags to cleared.
Definition at line 176 of file Token.h.
References clang::SourceLocation::getRawEncoding().
Referenced by clang::Sema::ActOnIdExpression(), clang::TokenRewriter::AddTokenBefore(), ComputeDATE_TIME(), clang::Preprocessor::EnterAnnotationToken(), GenerateNewArgTokens(), clang::Preprocessor::HandlePragmaHdrstop(), clang::format::JavaScriptImportSorter::JavaScriptImportSorter(), clang::TokenLexer::Lex(), clang::Preprocessor::LexAfterModuleImport(), clang::Preprocessor::LexHeaderName(), ParseLoopHintValue(), clang::Parser::ParseMSAsmIdentifier(), clang::Preprocessor::ParsePragmaPushOrPopMacro(), clang::Parser::Parser(), clang::Lexer::ReadToEndOfLine(), clang::ASTReader::ReadToken(), clang::arcmt::trans::MigrationContext::rewritePropertyAttribute(), clang::format::ScopedMacroState::ScopedMacroState(), clang::MacroArgs::StringifyArgument(), and clang::VAOptExpansionContext::VAOptExpansionContext().
stringifiedInMacro()
bool clang::Token::stringifiedInMacro () const inline
Returns true if this token is formed by macro by stringizing or charizing operator.
Definition at line 307 of file Token.h.
References getFlag(), and StringifiedInMacro.
Referenced by isWideStringLiteralFromMacro().
The documentation for this class was generated from the following files:
include/clang/Lex/Token.h
lib/Lex/Lexer.cpp