clang: clang::ASTNodeImporter Class Reference
clang::ASTNodeImporter Class Reference
Public Types
enum ImportDefinitionKind { IDK_Default , IDK_Everything , IDK_Basic }
What we should import from the definition.
using Designator = DesignatedInitExpr::Designator
using TemplateArgsTy = SmallVector<TemplateArgument, 8>
using FunctionTemplateAndArgsTy
Public Member Functions
ASTNodeImporter (ASTImporter &Importer)
ExpectedType VisitType (const Type *T)
ExpectedType VisitAtomicType (const AtomicType *T)
ExpectedType VisitBuiltinType (const BuiltinType *T)
ExpectedType VisitDecayedType (const DecayedType *T)
ExpectedType VisitComplexType (const ComplexType *T)
ExpectedType VisitPointerType (const PointerType *T)
ExpectedType VisitBlockPointerType (const BlockPointerType *T)
ExpectedType VisitLValueReferenceType (const LValueReferenceType *T)
ExpectedType VisitRValueReferenceType (const RValueReferenceType *T)
ExpectedType VisitMemberPointerType (const MemberPointerType *T)
ExpectedType VisitConstantArrayType (const ConstantArrayType *T)
ExpectedType VisitIncompleteArrayType (const IncompleteArrayType *T)
ExpectedType VisitVariableArrayType (const VariableArrayType *T)
ExpectedType VisitDependentSizedArrayType (const DependentSizedArrayType *T)
ExpectedType VisitVectorType (const VectorType *T)
ExpectedType VisitExtVectorType (const ExtVectorType *T)
ExpectedType VisitFunctionNoProtoType (const FunctionNoProtoType *T)
ExpectedType VisitFunctionProtoType (const FunctionProtoType *T)
ExpectedType VisitUnresolvedUsingType (const UnresolvedUsingType *T)
ExpectedType VisitParenType (const ParenType *T)
ExpectedType VisitTypedefType (const TypedefType *T)
ExpectedType VisitTypeOfExprType (const TypeOfExprType *T)
ExpectedType VisitTypeOfType (const TypeOfType *T)
ExpectedType VisitUsingType (const UsingType *T)
ExpectedType VisitDecltypeType (const DecltypeType *T)
ExpectedType VisitUnaryTransformType (const UnaryTransformType *T)
ExpectedType VisitAutoType (const AutoType *T)
ExpectedType VisitDeducedTemplateSpecializationType (const DeducedTemplateSpecializationType *T)
ExpectedType VisitInjectedClassNameType (const InjectedClassNameType *T)
ExpectedType VisitRecordType (const RecordType *T)
ExpectedType VisitEnumType (const EnumType *T)
ExpectedType VisitAttributedType (const AttributedType *T)
ExpectedType VisitTemplateTypeParmType (const TemplateTypeParmType *T)
ExpectedType VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType *T)
ExpectedType VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType *T)
ExpectedType VisitTemplateSpecializationType (const TemplateSpecializationType *T)
ExpectedType VisitElaboratedType (const ElaboratedType *T)
ExpectedType VisitDependentNameType (const DependentNameType *T)
ExpectedType VisitPackExpansionType (const PackExpansionType *T)
ExpectedType VisitDependentTemplateSpecializationType (const DependentTemplateSpecializationType *T)
ExpectedType VisitObjCInterfaceType (const ObjCInterfaceType *T)
ExpectedType VisitObjCObjectType (const ObjCObjectType *T)
ExpectedType VisitObjCObjectPointerType (const ObjCObjectPointerType *T)
Error ImportDeclParts (NamedDecl *D, DeclarationName &Name, NamedDecl *&ToD, SourceLocation &Loc)
Error ImportDeclParts (NamedDecl *D, DeclContext *&DC, DeclContext *&LexicalDC, DeclarationName &Name, NamedDecl *&ToD, SourceLocation &Loc)
Error ImportDefinitionIfNeeded (Decl *FromD, Decl *ToD=nullptr)
Error ImportDeclarationNameLoc (const DeclarationNameInfo &From, DeclarationNameInfo &To)
Error ImportDeclContext (DeclContext *FromDC, bool ForceImport=false)
Error ImportDeclContext (Decl *From, DeclContext *&ToDC, DeclContext *&ToLexicalDC)
Error ImportImplicitMethods (const CXXRecordDecl *From, CXXRecordDecl *To)
Error ImportFieldDeclDefinition (const FieldDecl *From, const FieldDecl *To)
Expected< CXXCastPath > ImportCastPath (CastExpr *E)
Expected< APValue > ImportAPValue (const APValue &FromValue)
bool shouldForceImportDeclContext (ImportDefinitionKind IDK)
Error ImportInitializer (VarDecl *From, VarDecl *To)
Error ImportDefinition (RecordDecl *From, RecordDecl *To, ImportDefinitionKind Kind=IDK_Default)
Error ImportDefinition (EnumDecl *From, EnumDecl *To, ImportDefinitionKind Kind=IDK_Default)
Error ImportDefinition (ObjCInterfaceDecl *From, ObjCInterfaceDecl *To, ImportDefinitionKind Kind=IDK_Default)
Error ImportDefinition (ObjCProtocolDecl *From, ObjCProtocolDecl *To, ImportDefinitionKind Kind=IDK_Default)
Error ImportTemplateArguments (ArrayRef< TemplateArgument > FromArgs, SmallVectorImpl< TemplateArgument > &ToArgs)
Expected< TemplateArgument > ImportTemplateArgument (const TemplateArgument &From)
template<typename InContainerTy >
Error ImportTemplateArgumentListInfo (const InContainerTy &Container, TemplateArgumentListInfo &ToTAInfo)
template<typename InContainerTy >
Error ImportTemplateArgumentListInfo (SourceLocation FromLAngleLoc, SourceLocation FromRAngleLoc, const InContainerTy &Container, TemplateArgumentListInfo &Result)
Expected< FunctionTemplateAndArgsTy > ImportFunctionTemplateWithTemplateArgsFromSpecialization (FunctionDecl *FromFD)
Error ImportTemplateParameterLists (const DeclaratorDecl *FromD, DeclaratorDecl *ToD)
Error ImportTemplateInformation (FunctionDecl *FromFD, FunctionDecl *ToFD)
Error ImportFunctionDeclBody (FunctionDecl *FromFD, FunctionDecl *ToFD)
Error ImportDefaultArgOfParmVarDecl (const ParmVarDecl *FromParam, ParmVarDecl *ToParam)
Expected< InheritedConstructor > ImportInheritedConstructor (const InheritedConstructor &From)
template<typename T >
bool hasSameVisibilityContextAndLinkage (T *Found, T *From)
bool IsStructuralMatch (Decl *From, Decl *To, bool Complain=true)
ExpectedDecl VisitDecl (Decl *D)
ExpectedDecl VisitImportDecl (ImportDecl *D)
ExpectedDecl VisitEmptyDecl (EmptyDecl *D)
ExpectedDecl VisitAccessSpecDecl (AccessSpecDecl *D)
ExpectedDecl VisitStaticAssertDecl (StaticAssertDecl *D)
ExpectedDecl VisitTranslationUnitDecl (TranslationUnitDecl *D)
ExpectedDecl VisitBindingDecl (BindingDecl *D)
ExpectedDecl VisitNamespaceDecl (NamespaceDecl *D)
ExpectedDecl VisitNamespaceAliasDecl (NamespaceAliasDecl *D)
ExpectedDecl VisitTypedefNameDecl (TypedefNameDecl *D, bool IsAlias)
ExpectedDecl VisitTypedefDecl (TypedefDecl *D)
ExpectedDecl VisitTypeAliasDecl (TypeAliasDecl *D)
ExpectedDecl VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl *D)
ExpectedDecl VisitLabelDecl (LabelDecl *D)
ExpectedDecl VisitEnumDecl (EnumDecl *D)
ExpectedDecl VisitRecordDecl (RecordDecl *D)
ExpectedDecl VisitEnumConstantDecl (EnumConstantDecl *D)
ExpectedDecl VisitFunctionDecl (FunctionDecl *D)
ExpectedDecl VisitCXXMethodDecl (CXXMethodDecl *D)
ExpectedDecl VisitCXXConstructorDecl (CXXConstructorDecl *D)
ExpectedDecl VisitCXXDestructorDecl (CXXDestructorDecl *D)
ExpectedDecl VisitCXXConversionDecl (CXXConversionDecl *D)
ExpectedDecl VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl *D)
ExpectedDecl VisitFieldDecl (FieldDecl *D)
ExpectedDecl VisitIndirectFieldDecl (IndirectFieldDecl *D)
ExpectedDecl VisitFriendDecl (FriendDecl *D)
ExpectedDecl VisitObjCIvarDecl (ObjCIvarDecl *D)
ExpectedDecl VisitVarDecl (VarDecl *D)
ExpectedDecl VisitImplicitParamDecl (ImplicitParamDecl *D)
ExpectedDecl VisitParmVarDecl (ParmVarDecl *D)
ExpectedDecl VisitObjCMethodDecl (ObjCMethodDecl *D)
ExpectedDecl VisitObjCTypeParamDecl (ObjCTypeParamDecl *D)
ExpectedDecl VisitObjCCategoryDecl (ObjCCategoryDecl *D)
ExpectedDecl VisitObjCProtocolDecl (ObjCProtocolDecl *D)
ExpectedDecl VisitLinkageSpecDecl (LinkageSpecDecl *D)
ExpectedDecl VisitUsingDecl (UsingDecl *D)
ExpectedDecl VisitUsingShadowDecl (UsingShadowDecl *D)
ExpectedDecl VisitUsingDirectiveDecl (UsingDirectiveDecl *D)
ExpectedDecl VisitUsingPackDecl (UsingPackDecl *D)
ExpectedDecl ImportUsingShadowDecls (BaseUsingDecl *D, BaseUsingDecl *ToSI)
ExpectedDecl VisitUsingEnumDecl (UsingEnumDecl *D)
ExpectedDecl VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl *D)
ExpectedDecl VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl *D)
ExpectedDecl VisitBuiltinTemplateDecl (BuiltinTemplateDecl *D)
ExpectedDecl VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl *D)
Expected< ObjCTypeParamList * > ImportObjCTypeParamList (ObjCTypeParamList *list)
ExpectedDecl VisitObjCInterfaceDecl (ObjCInterfaceDecl *D)
ExpectedDecl VisitObjCCategoryImplDecl (ObjCCategoryImplDecl *D)
ExpectedDecl VisitObjCImplementationDecl (ObjCImplementationDecl *D)
ExpectedDecl VisitObjCPropertyDecl (ObjCPropertyDecl *D)
ExpectedDecl VisitObjCPropertyImplDecl (ObjCPropertyImplDecl *D)
ExpectedDecl VisitTemplateTypeParmDecl (TemplateTypeParmDecl *D)
ExpectedDecl VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl *D)
ExpectedDecl VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl *D)
ExpectedDecl VisitClassTemplateDecl (ClassTemplateDecl *D)
ExpectedDecl VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl *D)
ExpectedDecl VisitVarTemplateDecl (VarTemplateDecl *D)
ExpectedDecl VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl *D)
ExpectedDecl VisitFunctionTemplateDecl (FunctionTemplateDecl *D)
ExpectedStmt VisitStmt (Stmt *S)
ExpectedStmt VisitGCCAsmStmt (GCCAsmStmt *S)
ExpectedStmt VisitDeclStmt (DeclStmt *S)
ExpectedStmt VisitNullStmt (NullStmt *S)
ExpectedStmt VisitCompoundStmt (CompoundStmt *S)
ExpectedStmt VisitCaseStmt (CaseStmt *S)
ExpectedStmt VisitDefaultStmt (DefaultStmt *S)
ExpectedStmt VisitLabelStmt (LabelStmt *S)
ExpectedStmt VisitAttributedStmt (AttributedStmt *S)
ExpectedStmt VisitIfStmt (IfStmt *S)
ExpectedStmt VisitSwitchStmt (SwitchStmt *S)
ExpectedStmt VisitWhileStmt (WhileStmt *S)
ExpectedStmt VisitDoStmt (DoStmt *S)
ExpectedStmt VisitForStmt (ForStmt *S)
ExpectedStmt VisitGotoStmt (GotoStmt *S)
ExpectedStmt VisitIndirectGotoStmt (IndirectGotoStmt *S)
ExpectedStmt VisitContinueStmt (ContinueStmt *S)
ExpectedStmt VisitBreakStmt (BreakStmt *S)
ExpectedStmt VisitReturnStmt (ReturnStmt *S)
ExpectedStmt VisitCXXCatchStmt (CXXCatchStmt *S)
ExpectedStmt VisitCXXTryStmt (CXXTryStmt *S)
ExpectedStmt VisitCXXForRangeStmt (CXXForRangeStmt *S)
ExpectedStmt VisitObjCForCollectionStmt (ObjCForCollectionStmt *S)
ExpectedStmt VisitObjCAtCatchStmt (ObjCAtCatchStmt *S)
ExpectedStmt VisitObjCAtFinallyStmt (ObjCAtFinallyStmt *S)
ExpectedStmt VisitObjCAtTryStmt (ObjCAtTryStmt *S)
ExpectedStmt VisitObjCAtSynchronizedStmt (ObjCAtSynchronizedStmt *S)
ExpectedStmt VisitObjCAtThrowStmt (ObjCAtThrowStmt *S)
ExpectedStmt VisitObjCAutoreleasePoolStmt (ObjCAutoreleasePoolStmt *S)
ExpectedStmt VisitExpr (Expr *E)
ExpectedStmt VisitSourceLocExpr (SourceLocExpr *E)
ExpectedStmt VisitVAArgExpr (VAArgExpr *E)
ExpectedStmt VisitChooseExpr (ChooseExpr *E)
ExpectedStmt VisitShuffleVectorExpr (ShuffleVectorExpr *E)
ExpectedStmt VisitGNUNullExpr (GNUNullExpr *E)
ExpectedStmt VisitGenericSelectionExpr (GenericSelectionExpr *E)
ExpectedStmt VisitPredefinedExpr (PredefinedExpr *E)
ExpectedStmt VisitDeclRefExpr (DeclRefExpr *E)
ExpectedStmt VisitImplicitValueInitExpr (ImplicitValueInitExpr *E)
ExpectedStmt VisitDesignatedInitExpr (DesignatedInitExpr *E)
ExpectedStmt VisitCXXNullPtrLiteralExpr (CXXNullPtrLiteralExpr *E)
ExpectedStmt VisitIntegerLiteral (IntegerLiteral *E)
ExpectedStmt VisitFloatingLiteral (FloatingLiteral *E)
ExpectedStmt VisitImaginaryLiteral (ImaginaryLiteral *E)
ExpectedStmt VisitFixedPointLiteral (FixedPointLiteral *E)
ExpectedStmt VisitCharacterLiteral (CharacterLiteral *E)
ExpectedStmt VisitStringLiteral (StringLiteral *E)
ExpectedStmt VisitCompoundLiteralExpr (CompoundLiteralExpr *E)
ExpectedStmt VisitAtomicExpr (AtomicExpr *E)
ExpectedStmt VisitAddrLabelExpr (AddrLabelExpr *E)
ExpectedStmt VisitConstantExpr (ConstantExpr *E)
ExpectedStmt VisitParenExpr (ParenExpr *E)
ExpectedStmt VisitParenListExpr (ParenListExpr *E)
ExpectedStmt VisitStmtExpr (StmtExpr *E)
ExpectedStmt VisitUnaryOperator (UnaryOperator *E)
ExpectedStmt VisitUnaryExprOrTypeTraitExpr (UnaryExprOrTypeTraitExpr *E)
ExpectedStmt VisitBinaryOperator (BinaryOperator *E)
ExpectedStmt VisitConditionalOperator (ConditionalOperator *E)
ExpectedStmt VisitBinaryConditionalOperator (BinaryConditionalOperator *E)
ExpectedStmt VisitCXXRewrittenBinaryOperator (CXXRewrittenBinaryOperator *E)
ExpectedStmt VisitOpaqueValueExpr (OpaqueValueExpr *E)
ExpectedStmt VisitArrayTypeTraitExpr (ArrayTypeTraitExpr *E)
ExpectedStmt VisitExpressionTraitExpr (ExpressionTraitExpr *E)
ExpectedStmt VisitArraySubscriptExpr (ArraySubscriptExpr *E)
ExpectedStmt VisitCompoundAssignOperator (CompoundAssignOperator *E)
ExpectedStmt VisitImplicitCastExpr (ImplicitCastExpr *E)
ExpectedStmt VisitExplicitCastExpr (ExplicitCastExpr *E)
ExpectedStmt VisitOffsetOfExpr (OffsetOfExpr *OE)
ExpectedStmt VisitCXXThrowExpr (CXXThrowExpr *E)
ExpectedStmt VisitCXXNoexceptExpr (CXXNoexceptExpr *E)
ExpectedStmt VisitCXXDefaultArgExpr (CXXDefaultArgExpr *E)
ExpectedStmt VisitCXXScalarValueInitExpr (CXXScalarValueInitExpr *E)
ExpectedStmt VisitCXXBindTemporaryExpr (CXXBindTemporaryExpr *E)
ExpectedStmt VisitCXXTemporaryObjectExpr (CXXTemporaryObjectExpr *E)
ExpectedStmt VisitMaterializeTemporaryExpr (MaterializeTemporaryExpr *E)
ExpectedStmt VisitPackExpansionExpr (PackExpansionExpr *E)
ExpectedStmt VisitSizeOfPackExpr (SizeOfPackExpr *E)
ExpectedStmt VisitCXXNewExpr (CXXNewExpr *E)
ExpectedStmt VisitCXXDeleteExpr (CXXDeleteExpr *E)
ExpectedStmt VisitCXXConstructExpr (CXXConstructExpr *E)
ExpectedStmt VisitCXXMemberCallExpr (CXXMemberCallExpr *E)
ExpectedStmt VisitCXXDependentScopeMemberExpr (CXXDependentScopeMemberExpr *E)
ExpectedStmt VisitDependentScopeDeclRefExpr (DependentScopeDeclRefExpr *E)
ExpectedStmt VisitCXXUnresolvedConstructExpr (CXXUnresolvedConstructExpr *E)
ExpectedStmt VisitUnresolvedLookupExpr (UnresolvedLookupExpr *E)
ExpectedStmt VisitUnresolvedMemberExpr (UnresolvedMemberExpr *E)
ExpectedStmt VisitExprWithCleanups (ExprWithCleanups *E)
ExpectedStmt VisitCXXThisExpr (CXXThisExpr *E)
ExpectedStmt VisitCXXBoolLiteralExpr (CXXBoolLiteralExpr *E)
ExpectedStmt VisitCXXPseudoDestructorExpr (CXXPseudoDestructorExpr *E)
ExpectedStmt VisitMemberExpr (MemberExpr *E)
ExpectedStmt VisitCallExpr (CallExpr *E)
ExpectedStmt VisitLambdaExpr (LambdaExpr *LE)
ExpectedStmt VisitInitListExpr (InitListExpr *E)
ExpectedStmt VisitCXXStdInitializerListExpr (CXXStdInitializerListExpr *E)
ExpectedStmt VisitCXXInheritedCtorInitExpr (CXXInheritedCtorInitExpr *E)
ExpectedStmt VisitArrayInitLoopExpr (ArrayInitLoopExpr *E)
ExpectedStmt VisitArrayInitIndexExpr (ArrayInitIndexExpr *E)
ExpectedStmt VisitCXXDefaultInitExpr (CXXDefaultInitExpr *E)
ExpectedStmt VisitCXXNamedCastExpr (CXXNamedCastExpr *E)
ExpectedStmt VisitSubstNonTypeTemplateParmExpr (SubstNonTypeTemplateParmExpr *E)
ExpectedStmt VisitTypeTraitExpr (TypeTraitExpr *E)
ExpectedStmt VisitCXXTypeidExpr (CXXTypeidExpr *E)
ExpectedStmt VisitCXXFoldExpr (CXXFoldExpr *E)
template<typename T >
T importChecked (Error &Err, const T &From)
template<typename IIter , typename OIter >
Error ImportArrayChecked (IIter Ibegin, IIter Iend, OIter Obegin)
template<typename InContainerTy , typename OutContainerTy >
Error ImportContainerChecked (const InContainerTy &InContainer, OutContainerTy &OutContainer)
template<typename InContainerTy , typename OIter >
Error ImportArrayChecked (const InContainerTy &InContainer, OIter Obegin)
Error ImportOverriddenMethods (CXXMethodDecl *ToMethod, CXXMethodDecl *FromMethod)
Expected< FunctionDecl * > FindFunctionTemplateSpecialization (FunctionDecl *FromFD)
bool hasAutoReturnTypeDeclaredInside (FunctionDecl *D)
template<>
Error ImportTemplateArgumentListInfo (const TemplateArgumentListInfo &From, TemplateArgumentListInfo &Result)
template<>
Error ImportTemplateArgumentListInfo (const ASTTemplateArgumentListInfo &From, TemplateArgumentListInfo &Result)
template<>
Expected< TemplateParameterList * > import (TemplateParameterList *From)
template<>
Expected< TemplateArgument > import (const TemplateArgument &From)
template<>
Expected< TemplateArgumentLoc > import (const TemplateArgumentLoc &TALoc)
template<>
Expected< DeclGroupRef > import (const DeclGroupRef &DG)
template<>
Expected< ASTNodeImporter::Designator > import (const Designator &D)
template<>
Expected< LambdaCapture > import (const LambdaCapture &From)
template<>
bool hasSameVisibilityContextAndLinkage (TypedefNameDecl *Found, TypedefNameDecl *From)
Public Member Functions inherited from clang::TypeVisitor< ASTNodeImporter, ExpectedType >
ExpectedType Visit (const Type *T)
Performs the operation associated with this visitor object.
ExpectedType VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::declvisitor::Base< std::add_pointer, ASTNodeImporter, ExpectedDecl >
ExpectedDecl Visit (PTR(Decl) D)
ExpectedDecl VisitDecl (PTR(Decl) D)
Public Member Functions inherited from clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >
ExpectedStmt Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) ExpectedStmt VisitStmt(PTR(Stmt) Node
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >
ParamTys P
Detailed Description
Definition at line 178 of file ASTImporter.cpp.
Member Typedef Documentation
Designator
using clang::ASTNodeImporter::Designator = DesignatedInitExpr::Designator
Definition at line 440 of file ASTImporter.cpp.
FunctionTemplateAndArgsTy
using clang::ASTNodeImporter::FunctionTemplateAndArgsTy
Initial value:
        std::tuple<FunctionTemplateDecl *, TemplateArgsTy>
Definition at line 488 of file ASTImporter.cpp.
TemplateArgsTy
using clang::ASTNodeImporter::TemplateArgsTy = SmallVector<TemplateArgument, 8>
Definition at line 487 of file ASTImporter.cpp.
Member Enumeration Documentation
ImportDefinitionKind
enum clang::ASTNodeImporter::ImportDefinitionKind
What we should import from the definition.
Enumerator
IDK_Default
Import the default subset of the definition, which might be nothing (if minimal import is set) or might be everything (if minimal import is not set).
IDK_Everything
Import everything.
IDK_Basic
Import only the bare bones needed to establish a valid DeclContext.
Definition at line 443 of file ASTImporter.cpp.
Constructor & Destructor Documentation
ASTNodeImporter()
clang::ASTNodeImporter::ASTNodeImporter (ASTImporter & Importer) inline explicit
Definition at line 363 of file ASTImporter.cpp.
Referenced by ImportDeclParts(), and ImportDeclParts().
Member Function Documentation
FindFunctionTemplateSpecialization()
Expected< FunctionDecl * > ASTNodeImporter::FindFunctionTemplateSpecialization (FunctionDecl * FromFD)
Definition at line 3245 of file ASTImporter.cpp.
References clang::FunctionTemplateDecl::findSpecialization(), and ImportFunctionTemplateWithTemplateArgsFromSpecialization().
Referenced by VisitFunctionDecl().
hasAutoReturnTypeDeclaredInside()
bool ASTNodeImporter::hasAutoReturnTypeDeclaredInside (FunctionDecl * D)
Definition at line 3449 of file ASTImporter.cpp.
References clang::Type::getAs(), clang::FunctionDecl::getDefinition(), clang::ValueDecl::getType(), and clang::QualType::getTypePtr().
Referenced by VisitFunctionDecl().
hasSameVisibilityContextAndLinkage() [1/2]
template<typename T > bool clang::ASTNodeImporter::hasSameVisibilityContextAndLinkage (T * Found, T * From)
Definition at line 1033 of file ASTImporter.cpp.
References clang::ASTImporter::GetFromTU().
Referenced by VisitClassTemplateDecl(), VisitEnumDecl(), VisitFunctionDecl(), VisitFunctionTemplateDecl(), VisitRecordDecl(), VisitTypedefNameDecl(), VisitVarDecl(), and VisitVarTemplateDecl().
hasSameVisibilityContextAndLinkage() [2/2]
template<> bool clang::ASTNodeImporter::hasSameVisibilityContextAndLinkage (TypedefNameDecl * Found, TypedefNameDecl * From)
Definition at line 1049 of file ASTImporter.cpp.
References clang::ASTImporter::GetFromTU(), clang::NamedDecl::getLinkageInternal(), clang::Decl::getTranslationUnitDecl(), and clang::Decl::isInAnonymousNamespace().
import() [1/6]
template<> Expected< DeclGroupRef > clang::ASTNodeImporter::import (const DeclGroupRef & DG)
Definition at line 950 of file ASTImporter.cpp.
References clang::DeclGroupRef::begin(), clang::DeclGroupRef::Create(), clang::DeclGroupRef::end(), clang::ASTImporter::getToContext(), and clang::DeclGroupRef::isNull().
import() [2/6]
template<> Expected< ASTNodeImporter::Designator > clang::ASTNodeImporter::import (const Designator & D)
Definition at line 969 of file ASTImporter.cpp.
References clang::DesignatedInitExpr::Designator::CreateArrayDesignator(), clang::DesignatedInitExpr::Designator::CreateArrayRangeDesignator(), clang::DesignatedInitExpr::Designator::CreateFieldDesignator(), clang::DesignatedInitExpr::Designator::getArrayIndex(), clang::DesignatedInitExpr::Designator::getDotLoc(), clang::DesignatedInitExpr::Designator::getEllipsisLoc(), clang::DesignatedInitExpr::Designator::getFieldLoc(), clang::DesignatedInitExpr::Designator::getFieldName(), clang::DesignatedInitExpr::Designator::getLBracketLoc(), clang::DesignatedInitExpr::Designator::getRBracketLoc(), clang::ASTImporter::Import(), clang::DesignatedInitExpr::Designator::isArrayDesignator(), clang::DesignatedInitExpr::Designator::isArrayRangeDesignator(), and clang::DesignatedInitExpr::Designator::isFieldDesignator().
import() [3/6]
template<> Expected< LambdaCapture > clang::ASTNodeImporter::import (const LambdaCapture & From)
Definition at line 1009 of file ASTImporter.cpp.
References clang::LambdaCapture::capturesVariable(), clang::LambdaCapture::getCapturedVar(), clang::LambdaCapture::getCaptureKind(), clang::LambdaCapture::getEllipsisLoc(), clang::LambdaCapture::getLocation(), clang::LambdaCapture::isImplicit(), and clang::LambdaCapture::isPackExpansion().
import() [4/6]
template<> Expected< TemplateArgument > clang::ASTNodeImporter::import (const TemplateArgument & From)
Definition at line 832 of file ASTImporter.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getIsDefaulted(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNullPtrType(), clang::TemplateArgument::getNumTemplateExpansions(), clang::TemplateArgument::getParamTypeForDecl(), clang::ASTImporter::getToContext(), ImportTemplateArguments(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::pack_size(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
import() [5/6]
template<> Expected< TemplateArgumentLoc > clang::ASTNodeImporter::import (const TemplateArgumentLoc & TALoc)
Definition at line 910 of file ASTImporter.cpp.
References clang::TemplateArgument::Expression, clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgumentLocInfo::getAsExpr(), clang::TemplateArgumentLocInfo::getAsTypeSourceInfo(), clang::TemplateArgument::getKind(), clang::TemplateArgumentLoc::getLocInfo(), clang::TemplateArgumentLocInfo::getTemplateEllipsisLoc(), clang::TemplateArgumentLocInfo::getTemplateNameLoc(), clang::TemplateArgumentLocInfo::getTemplateQualifierLoc(), clang::ASTImporter::getToContext(), and clang::TemplateArgument::Type.
import() [6/6]
template<> Expected< TemplateParameterList * > clang::ASTNodeImporter::import (TemplateParameterList * From)
Definition at line 802 of file ASTImporter.cpp.
References clang::TemplateParameterList::Create(), clang::TemplateParameterList::getLAngleLoc(), clang::TemplateParameterList::getRAngleLoc(), clang::TemplateParameterList::getRequiresClause(), clang::TemplateParameterList::getTemplateLoc(), clang::ASTImporter::getToContext(), ImportContainerChecked(), and clang::TemplateParameterList::size().
ImportAPValue()
llvm::Expected< APValue > ASTNodeImporter::ImportAPValue (const APValue & FromValue)
Definition at line 9904 of file ASTImporter.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::APValue::LValuePathEntry::ArrayIndex(), clang::cast(), clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::APValue::LValueBase::dyn_cast(), clang::APValue::FixedPoint, clang::APValue::Float, FromDecl, clang::APValue::LValueBase::get(), clang::APValue::getAddrLabelDiffLHS(), clang::APValue::getAddrLabelDiffRHS(), clang::APValue::getArrayInitializedElts(), clang::APValue::getArraySize(), clang::ASTContext::getAsArrayType(), clang::APValue::LValueBase::getCallIndex(), clang::Decl::getCanonicalDecl(), clang::ArrayType::getElementType(), clang::APValue::getKind(), clang::APValue::getLValueBase(), clang::APValue::getLValueOffset(), clang::APValue::getLValuePath(), clang::APValue::getMemberPointerDecl(), clang::APValue::getMemberPointerPath(), clang::ASTContext::getRecordType(), clang::APValue::getStructNumBases(), clang::APValue::getStructNumFields(), clang::TypeInfoLValue::getType(), getType(), clang::APValue::LValueBase::getTypeInfo(), clang::APValue::LValueBase::getTypeInfoType(), clang::APValue::getUnionField(), clang::APValue::getUnionValue(), clang::APValue::getVectorLength(), clang::APValue::LValueBase::getVersion(), clang::APValue::hasLValuePath(), importChecked(), clang::APValue::Indeterminate, clang::APValue::Int, clang::APValue::LValueBase::is(), clang::APValue::isLValueOnePastTheEnd(), clang::APValue::isMemberPointerToDerivedMember(), clang::APValue::isNullPointer(), clang::Type::isRecordType(), clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, Offset, clang::Result, clang::APValue::Struct, clang::APValue::Union, and clang::APValue::Vector.
Referenced by clang::ASTImporter::Import().
ImportArrayChecked() [1/2]
template<typename InContainerTy , typename OIter > Error clang::ASTNodeImporter::ImportArrayChecked (const InContainerTy & InContainer, OIter Obegin) inline
Definition at line 730 of file ASTImporter.cpp.
References ImportArrayChecked().
ImportArrayChecked() [2/2]
template<typename IIter , typename OIter > Error clang::ASTNodeImporter::ImportArrayChecked (IIter Ibegin, IIter Iend, OIter Obegin) inline
Definition at line 707 of file ASTImporter.cpp.
Referenced by ImportArrayChecked(), ImportContainerChecked(), VisitAtomicExpr(), VisitCXXUnresolvedConstructExpr(), VisitGCCAsmStmt(), VisitStringLiteral(), VisitUsingPackDecl(), and VisitVarDecl().
ImportCastPath()
Expected< CXXCastPath > ASTNodeImporter::ImportCastPath (CastExpr * E)
Definition at line 7571 of file ASTImporter.cpp.
References clang::CastExpr::path_begin(), and clang::CastExpr::path_end().
Referenced by VisitCXXNamedCastExpr(), VisitExplicitCastExpr(), and VisitImplicitCastExpr().
importChecked()
template<typename T > T clang::ASTNodeImporter::importChecked (Error & Err, const T & From) inline
Definition at line 694 of file ASTImporter.cpp.
Referenced by ImportAPValue(), ImportInheritedConstructor(), VisitAddrLabelExpr(), VisitArrayInitLoopExpr(), VisitArraySubscriptExpr(), VisitArrayTypeTraitExpr(), VisitAtomicExpr(), VisitBinaryConditionalOperator(), VisitBinaryOperator(), VisitBindingDecl(), VisitCallExpr(), VisitCaseStmt(), VisitChooseExpr(), VisitCompoundAssignOperator(), VisitCompoundLiteralExpr(), VisitConditionalOperator(), VisitConstantArrayType(), VisitConstantExpr(), VisitCXXCatchStmt(), VisitCXXConstructExpr(), VisitCXXDeleteExpr(), VisitCXXDependentScopeMemberExpr(), VisitCXXFoldExpr(), VisitCXXForRangeStmt(), VisitCXXInheritedCtorInitExpr(), VisitCXXMemberCallExpr(), VisitCXXNamedCastExpr(), VisitCXXNewExpr(), VisitCXXNoexceptExpr(), VisitCXXPseudoDestructorExpr(), VisitCXXRewrittenBinaryOperator(), VisitCXXScalarValueInitExpr(), VisitCXXTemporaryObjectExpr(), VisitCXXThrowExpr(), VisitCXXUnresolvedConstructExpr(), VisitDeclRefExpr(), VisitDeclStmt(), VisitDefaultStmt(), VisitDependentScopeDeclRefExpr(), VisitDependentSizedArrayType(), VisitDoStmt(), VisitEnumDecl(), VisitExplicitCastExpr(), VisitExpressionTraitExpr(), VisitFieldDecl(), VisitForStmt(), VisitFunctionDecl(), VisitFunctionProtoType(), VisitGenericSelectionExpr(), VisitGotoStmt(), VisitIfStmt(), VisitImplicitParamDecl(), VisitIndirectGotoStmt(), VisitInitListExpr(), VisitLabelStmt(), VisitLambdaExpr(), VisitLifetimeExtendedTemporaryDecl(), VisitMaterializeTemporaryExpr(), VisitMemberExpr(), VisitNamespaceAliasDecl(), VisitNonTypeTemplateParmDecl(), VisitObjCAtCatchStmt(), VisitObjCAtSynchronizedStmt(), VisitObjCAtTryStmt(), VisitObjCCategoryDecl(), VisitObjCCategoryImplDecl(), VisitObjCForCollectionStmt(), VisitObjCImplementationDecl(), VisitObjCIvarDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitObjCPropertyImplDecl(), VisitObjCTypeParamDecl(), VisitOffsetOfExpr(), VisitOpaqueValueExpr(), VisitPackExpansionExpr(), VisitParenExpr(), VisitParmVarDecl(), VisitPredefinedExpr(), VisitReturnStmt(), VisitShuffleVectorExpr(), VisitSizeOfPackExpr(), VisitSourceLocExpr(), VisitStaticAssertDecl(), VisitStmtExpr(), VisitSubstNonTypeTemplateParmExpr(), VisitSwitchStmt(), VisitTemplateTypeParmDecl(), VisitTypeAliasTemplateDecl(), VisitTypedefNameDecl(), VisitTypeTraitExpr(), VisitUnaryExprOrTypeTraitExpr(), VisitUnaryOperator(), VisitUnresolvedLookupExpr(), VisitUnresolvedMemberExpr(), VisitUnresolvedUsingType(), VisitUnresolvedUsingTypenameDecl(), VisitUnresolvedUsingValueDecl(), VisitUsingDecl(), VisitUsingDirectiveDecl(), VisitUsingEnumDecl(), VisitUsingShadowDecl(), VisitVAArgExpr(), VisitVarDecl(), VisitVariableArrayType(), and VisitWhileStmt().
ImportContainerChecked()
template<typename InContainerTy , typename OutContainerTy > Error clang::ASTNodeImporter::ImportContainerChecked (const InContainerTy & InContainer, OutContainerTy & OutContainer) inline
Definition at line 723 of file ASTImporter.cpp.
References ImportArrayChecked().
Referenced by import(), VisitAttributedStmt(), VisitCallExpr(), VisitCompoundStmt(), VisitCXXConstructExpr(), VisitCXXMemberCallExpr(), VisitCXXNewExpr(), VisitCXXTemporaryObjectExpr(), VisitDesignatedInitExpr(), VisitExprWithCleanups(), VisitFunctionDecl(), VisitGCCAsmStmt(), VisitGenericSelectionExpr(), VisitInitListExpr(), VisitLambdaExpr(), VisitObjCMethodDecl(), VisitParenListExpr(), VisitShuffleVectorExpr(), and VisitTypeTraitExpr().
ImportDeclarationNameLoc()
Error ASTNodeImporter::ImportDeclarationNameLoc (const DeclarationNameInfo & From, DeclarationNameInfo & To)
Definition at line 1796 of file ASTImporter.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationNameInfo::getCXXLiteralOperatorNameLoc(), clang::DeclarationNameInfo::getCXXOperatorNameRange(), clang::DeclarationNameInfo::getName(), clang::DeclarationNameInfo::getNamedTypeInfo(), clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::DeclarationNameInfo::setCXXLiteralOperatorNameLoc(), clang::DeclarationNameInfo::setCXXOperatorNameRange(), and clang::DeclarationNameInfo::setNamedTypeInfo().
Referenced by VisitCXXDependentScopeMemberExpr(), VisitDependentScopeDeclRefExpr(), VisitFunctionDecl(), VisitUnresolvedLookupExpr(), VisitUnresolvedMemberExpr(), VisitUnresolvedUsingValueDecl(), and VisitUsingDecl().
ImportDeclContext() [1/2]
Error ASTNodeImporter::ImportDeclContext (Decl * From, DeclContext *& ToDC, DeclContext *& ToLexicalDC)
Definition at line 1981 of file ASTImporter.cpp.
References clang::Decl::getDeclContext(), clang::Decl::getLexicalDeclContext(), and clang::ASTImporter::ImportContext().
ImportDeclContext() [2/2]
Error ASTNodeImporter::ImportDeclContext (DeclContext * FromDC, bool ForceImport = false)
Definition at line 1837 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::DeclContext::containsDecl(), clang::DeclContext::decls(), clang::ASTImporter::GetAlreadyImportedOrNull(), clang::ChildErrorHandlingStrategy::handleChildImportResult(), clang::ASTImporter::ImportContext(), ImportFieldDeclDefinition(), clang::isa(), clang::ASTImporter::isMinimalImport(), and clang::DeclContext::removeDecl().
Referenced by ImportDeclParts(), clang::ASTImporter::ImportDefinition(), ImportDefinition(), ImportDefinition(), ImportDefinition(), ImportDefinition(), VisitClassTemplateSpecializationDecl(), VisitEmptyDecl(), VisitFriendDecl(), VisitLifetimeExtendedTemporaryDecl(), VisitLinkageSpecDecl(), VisitNamespaceDecl(), VisitObjCCategoryDecl(), VisitObjCCategoryImplDecl(), VisitObjCImplementationDecl(), VisitObjCPropertyImplDecl(), VisitTypedefNameDecl(), and VisitVarTemplateSpecializationDecl().
ImportDeclParts() [1/2]
Error ASTNodeImporter::ImportDeclParts (NamedDecl * D, DeclarationName & Name, NamedDecl *& ToD, SourceLocation & Loc)
Definition at line 1744 of file ASTImporter.cpp.
References ASTNodeImporter(), clang::ASTImporter::GetAlreadyImportedOrNull(), clang::NamedDecl::getDeclName(), and clang::Decl::getLocation().
Referenced by VisitBindingDecl(), VisitClassTemplateDecl(), VisitEnumConstantDecl(), VisitEnumDecl(), VisitFieldDecl(), VisitFunctionDecl(), VisitFunctionTemplateDecl(), VisitIndirectFieldDecl(), VisitLabelDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCCategoryDecl(), VisitObjCInterfaceDecl(), VisitObjCIvarDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitObjCProtocolDecl(), VisitObjCTypeParamDecl(), VisitRecordDecl(), VisitTypeAliasTemplateDecl(), VisitTypedefNameDecl(), VisitUnresolvedUsingTypenameDecl(), VisitUnresolvedUsingValueDecl(), VisitUsingDecl(), VisitUsingDirectiveDecl(), VisitUsingEnumDecl(), VisitUsingPackDecl(), VisitUsingShadowDecl(), VisitVarDecl(), and VisitVarTemplateDecl().
ImportDeclParts() [2/2]
Error ASTNodeImporter::ImportDeclParts (NamedDecl * D, DeclContext *& DC, DeclContext *& LexicalDC, DeclarationName & Name, NamedDecl *& ToD, SourceLocation & Loc)
Definition at line 1693 of file ASTImporter.cpp.
References ASTNodeImporter(), clang::ASTImporter::FromDiag(), clang::ASTImporter::GetAlreadyImportedOrNull(), clang::Decl::getDeclContext(), clang::Decl::getDeclKindName(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::FunctionDecl::hasBody(), ImportDeclContext(), clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >::P, clang::FunctionDecl::parameters(), and clang::ASTImportError::UnsupportedConstruct.
ImportDefaultArgOfParmVarDecl()
Error ASTNodeImporter::ImportDefaultArgOfParmVarDecl (const ParmVarDecl * FromParam, ParmVarDecl * ToParam)
Definition at line 4398 of file ASTImporter.cpp.
References clang::ParmVarDecl::getDefaultArg(), clang::ParmVarDecl::getUninstantiatedDefaultArg(), clang::ParmVarDecl::hasDefaultArg(), clang::ParmVarDecl::hasInheritedDefaultArg(), clang::ParmVarDecl::hasUninstantiatedDefaultArg(), clang::ParmVarDecl::hasUnparsedDefaultArg(), clang::ParmVarDecl::isKNRPromoted(), clang::ParmVarDecl::setDefaultArg(), clang::ParmVarDecl::setHasInheritedDefaultArg(), clang::ParmVarDecl::setKNRPromoted(), clang::ParmVarDecl::setUninstantiatedDefaultArg(), and clang::ParmVarDecl::setUnparsedDefaultArg().
Referenced by VisitCXXDefaultArgExpr(), and VisitParmVarDecl().
ImportDefinition() [1/4]
Error ASTNodeImporter::ImportDefinition (EnumDecl * From, EnumDecl * To, ImportDefinitionKind Kind = IDK_Default)
Definition at line 2175 of file ASTImporter.cpp.
References clang::EnumDecl::completeDefinition(), clang::EnumDecl::getDefinition(), clang::ASTImporter::getFromContext(), clang::EnumDecl::getNumNegativeBits(), clang::EnumDecl::getNumPositiveBits(), clang::EnumDecl::getPromotionType(), IDK_Everything, ImportDeclContext(), clang::TagDecl::isBeingDefined(), setTypedefNameForAnonDecl(), shouldForceImportDeclContext(), and clang::TagDecl::startDefinition().
ImportDefinition() [2/4]
Error ASTNodeImporter::ImportDefinition (ObjCInterfaceDecl * From, ObjCInterfaceDecl * To, ImportDefinitionKind Kind = IDK_Default)
Definition at line 5165 of file ASTImporter.cpp.
References clang::declaresSameEntity(), clang::ASTImporter::FromDiag(), clang::NamedDecl::getDeclName(), clang::ObjCInterfaceDecl::getDefinition(), clang::ObjCInterfaceDecl::getImplementation(), clang::Decl::getLocation(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCInterfaceDecl::getSuperClassLoc(), clang::ObjCInterfaceDecl::getSuperClassTInfo(), clang::ASTImporter::getToContext(), ImportDeclContext(), clang::ObjCInterfaceDecl::known_categories(), clang::ObjCInterfaceDecl::protocol_begin(), clang::ObjCInterfaceDecl::protocol_end(), clang::ObjCInterfaceDecl::protocol_loc_begin(), clang::ObjCInterfaceDecl::setImplementation(), clang::ObjCInterfaceDecl::setProtocolList(), clang::ObjCInterfaceDecl::setSuperClass(), shouldForceImportDeclContext(), clang::ObjCInterfaceDecl::startDefinition(), and clang::ASTImporter::ToDiag().
ImportDefinition() [3/4]
Error ASTNodeImporter::ImportDefinition (ObjCProtocolDecl * From, ObjCProtocolDecl * To, ImportDefinitionKind Kind = IDK_Default)
Definition at line 4724 of file ASTImporter.cpp.
References clang::ObjCProtocolDecl::getDefinition(), clang::ASTImporter::getToContext(), ImportDeclContext(), clang::ObjCProtocolDecl::protocol_begin(), clang::ObjCProtocolDecl::protocol_end(), clang::ObjCProtocolDecl::protocol_loc_begin(), clang::ObjCProtocolDecl::setProtocolList(), shouldForceImportDeclContext(), and clang::ObjCProtocolDecl::startDefinition().
ImportDefinition() [4/4]
Error ASTNodeImporter::ImportDefinition (RecordDecl * From, RecordDecl * To, ImportDefinitionKind Kind = IDK_Default)
Definition at line 2026 of file ASTImporter.cpp.
References clang::cast(), clang::RecordDecl::completeDefinition(), clang::RecordDecl::getDefinition(), clang::ASTImporter::getToContext(), IDK_Everything, ImportDeclContext(), ImportDefinitionIfNeeded(), clang::TagDecl::isBeingDefined(), clang::RecordDecl::isLambda(), clang::ASTImporter::isMinimalImport(), clang::Result, clang::TagDecl::setCompleteDefinition(), setTypedefNameForAnonDecl(), shouldForceImportDeclContext(), and clang::TagDecl::startDefinition().
Referenced by clang::ASTImporter::ImportDefinition(), ImportDefinitionIfNeeded(), ImportFieldDeclDefinition(), VisitClassTemplateSpecializationDecl(), VisitEnumDecl(), VisitObjCInterfaceDecl(), VisitObjCProtocolDecl(), and VisitRecordDecl().
ImportDefinitionIfNeeded()
Error ASTNodeImporter::ImportDefinitionIfNeeded (Decl * FromD, Decl * ToD = nullptr)
Definition at line 1763 of file ASTImporter.cpp.
References ImportDefinition().
Referenced by ImportDefinition().
ImportFieldDeclDefinition()
Error ASTNodeImporter::ImportFieldDeclDefinition (const FieldDecl * From, const FieldDecl * To)
Definition at line 1948 of file ASTImporter.cpp.
References clang::Type::getAs(), clang::Type::getAsRecordDecl(), clang::Type::getBaseElementTypeUnsafe(), clang::ValueDecl::getType(), ImportDefinition(), clang::Type::isArrayType(), and clang::TagDecl::isCompleteDefinition().
Referenced by ImportDeclContext().
ImportFunctionDeclBody()
Error ASTNodeImporter::ImportFunctionDeclBody (FunctionDecl * FromFD, FunctionDecl * ToFD)
Definition at line 3259 of file ASTImporter.cpp.
References clang::FunctionDecl::getBody(), and clang::FunctionDecl::setBody().
Referenced by VisitFunctionDecl().
ImportFunctionTemplateWithTemplateArgsFromSpecialization()
Expected< ASTNodeImporter::FunctionTemplateAndArgsTy > clang::ASTNodeImporter::ImportFunctionTemplateWithTemplateArgsFromSpecialization (FunctionDecl * FromFD)
Definition at line 781 of file ASTImporter.cpp.
References clang::FunctionDecl::getTemplatedKind(), clang::FunctionDecl::getTemplateSpecializationInfo(), ImportTemplateArguments(), clang::Result, and clang::FunctionDecl::TK_FunctionTemplateSpecialization.
Referenced by FindFunctionTemplateSpecialization(), and ImportTemplateInformation().
ImportImplicitMethods()
Error ASTNodeImporter::ImportImplicitMethods (const CXXRecordDecl * From, CXXRecordDecl * To)
Definition at line 2000 of file ASTImporter.cpp.
References clang::CXXRecordDecl::getDefinition(), clang::TagDecl::isCompleteDefinition(), and clang::CXXRecordDecl::methods().
Referenced by VisitRecordDecl().
ImportInheritedConstructor()
Expected< InheritedConstructor > ASTNodeImporter::ImportInheritedConstructor (const InheritedConstructor & From)
Definition at line 4421 of file ASTImporter.cpp.
References clang::InheritedConstructor::getConstructor(), clang::InheritedConstructor::getShadowDecl(), and importChecked().
ImportInitializer()
Error ASTNodeImporter::ImportInitializer (VarDecl * From, VarDecl * To)
Definition at line 2151 of file ASTImporter.cpp.
References clang::VarDecl::ensureEvaluatedStmt(), clang::VarDecl::getAnyInitializer(), clang::VarDecl::getEvaluatedStmt(), clang::VarDecl::getInit(), clang::EvaluatedStmt::HasConstantDestruction, clang::EvaluatedStmt::HasConstantInitialization, and clang::VarDecl::setInit().
Referenced by VisitVarDecl(), and VisitVarTemplateSpecializationDecl().
ImportObjCTypeParamList()
Expected< ObjCTypeParamList * > ASTNodeImporter::ImportObjCTypeParamList (ObjCTypeParamList * list)
Definition at line 5266 of file ASTImporter.cpp.
References clang::ObjCTypeParamList::create(), clang::ObjCTypeParamList::getLAngleLoc(), clang::ObjCTypeParamList::getRAngleLoc(), and clang::ASTImporter::getToContext().
Referenced by VisitObjCCategoryDecl(), and VisitObjCInterfaceDecl().
ImportOverriddenMethods()
Error ASTNodeImporter::ImportOverriddenMethods (CXXMethodDecl * ToMethod, CXXMethodDecl * FromMethod)
Definition at line 8617 of file ASTImporter.cpp.
References clang::CXXMethodDecl::addOverriddenMethod(), clang::CXXMethodDecl::getCanonicalDecl(), and clang::CXXMethodDecl::overridden_methods().
Referenced by VisitFunctionDecl().
ImportTemplateArgument()
Expected< TemplateArgument > ASTNodeImporter::ImportTemplateArgument (const TemplateArgument & From)
Definition at line 2224 of file ASTImporter.cpp.
Referenced by clang::ASTImporter::Import().
ImportTemplateArgumentListInfo() [1/4]
template<> Error clang::ASTNodeImporter::ImportTemplateArgumentListInfo (const ASTTemplateArgumentListInfo & From, TemplateArgumentListInfo & Result)
Definition at line 772 of file ASTImporter.cpp.
References clang::Result.
ImportTemplateArgumentListInfo() [2/4]
template<typename InContainerTy > Error ASTNodeImporter::ImportTemplateArgumentListInfo (const InContainerTy & Container, TemplateArgumentListInfo & ToTAInfo)
Definition at line 2229 of file ASTImporter.cpp.
References clang::TemplateArgumentListInfo::addArgument().
Referenced by ImportTemplateArgumentListInfo(), ImportTemplateArgumentListInfo(), ImportTemplateInformation(), VisitClassTemplateSpecializationDecl(), VisitCXXDependentScopeMemberExpr(), VisitDeclRefExpr(), VisitDependentScopeDeclRefExpr(), VisitMemberExpr(), VisitTemplateTypeParmDecl(), VisitUnresolvedLookupExpr(), VisitUnresolvedMemberExpr(), and VisitVarTemplateSpecializationDecl().
ImportTemplateArgumentListInfo() [3/4]
template<> Error clang::ASTNodeImporter::ImportTemplateArgumentListInfo (const TemplateArgumentListInfo & From, TemplateArgumentListInfo & Result)
Definition at line 765 of file ASTImporter.cpp.
References clang::TemplateArgumentListInfo::arguments(), clang::TemplateArgumentListInfo::getLAngleLoc(), clang::TemplateArgumentListInfo::getRAngleLoc(), ImportTemplateArgumentListInfo(), and clang::Result.
ImportTemplateArgumentListInfo() [4/4]
template<typename InContainerTy > Error clang::ASTNodeImporter::ImportTemplateArgumentListInfo (SourceLocation FromLAngleLoc, SourceLocation FromRAngleLoc, const InContainerTy & Container, TemplateArgumentListInfo & Result)
Definition at line 747 of file ASTImporter.cpp.
References ImportTemplateArgumentListInfo(), and clang::Result.
ImportTemplateArguments()
Error ASTNodeImporter::ImportTemplateArguments (ArrayRef< TemplateArgument > FromArgs, SmallVectorImpl< TemplateArgument > & ToArgs)
Definition at line 2209 of file ASTImporter.cpp.
Referenced by import(), ImportFunctionTemplateWithTemplateArgsFromSpecialization(), VisitAutoType(), VisitClassTemplateSpecializationDecl(), VisitDependentTemplateSpecializationType(), VisitSizeOfPackExpr(), VisitTemplateSpecializationType(), and VisitVarTemplateSpecializationDecl().
ImportTemplateInformation()
Error ASTNodeImporter::ImportTemplateInformation (FunctionDecl * FromFD, FunctionDecl * ToFD)
Definition at line 3154 of file ASTImporter.cpp.
References clang::UnresolvedSetImpl::addDecl(), clang::TemplateArgumentList::CreateCopy(), clang::FunctionDecl::getDependentSpecializationInfo(), clang::FunctionDecl::getInstantiatedFromDecl(), clang::FunctionDecl::getInstantiatedFromMemberFunction(), clang::FunctionDecl::getMemberSpecializationInfo(), clang::MemberSpecializationInfo::getPointOfInstantiation(), clang::FunctionDecl::getTemplatedKind(), clang::FunctionDecl::getTemplateSpecializationInfo(), clang::FunctionDecl::getTemplateSpecializationKind(), clang::ASTImporter::getToContext(), ImportFunctionTemplateWithTemplateArgsFromSpecialization(), ImportTemplateArgumentListInfo(), ImportTemplateParameterLists(), clang::FunctionDecl::setDependentTemplateSpecialization(), clang::FunctionDecl::setInstantiatedFromDecl(), clang::MemberSpecializationInfo::setPointOfInstantiation(), clang::FunctionDecl::TK_DependentFunctionTemplateSpecialization, clang::FunctionDecl::TK_DependentNonTemplate, clang::FunctionDecl::TK_FunctionTemplate, clang::FunctionDecl::TK_FunctionTemplateSpecialization, clang::FunctionDecl::TK_MemberSpecialization, and clang::FunctionDecl::TK_NonTemplate.
Referenced by VisitFunctionDecl().
ImportTemplateParameterLists()
Error ASTNodeImporter::ImportTemplateParameterLists (const DeclaratorDecl * FromD, DeclaratorDecl * ToD)
Definition at line 3138 of file ASTImporter.cpp.
References clang::DeclaratorDecl::getNumTemplateParameterLists(), clang::DeclaratorDecl::getTemplateParameterList(), and clang::DeclaratorDecl::setTemplateParameterListsInfo().
Referenced by ImportTemplateInformation().
ImportUsingShadowDecls()
ExpectedDecl ASTNodeImporter::ImportUsingShadowDecls (BaseUsingDecl * D, BaseUsingDecl * ToSI)
Definition at line 4859 of file ASTImporter.cpp.
References clang::BaseUsingDecl::addShadowDecl(), and clang::BaseUsingDecl::shadows().
Referenced by VisitUsingDecl(), and VisitUsingEnumDecl().
IsStructuralMatch()
bool ASTNodeImporter::IsStructuralMatch (Decl * From, Decl * To, bool Complain = true)
Definition at line 2246 of file ASTImporter.cpp.
References clang::ASTImporter::getFromContext(), clang::ASTImporter::getNonEquivalentDecls(), clang::ASTImporter::GetOriginalDecl(), getStructuralEquivalenceKind(), clang::ASTImporter::getToContext(), and clang::StructuralEquivalenceContext::IsEquivalent().
Referenced by VisitClassTemplateDecl(), VisitClassTemplateSpecializationDecl(), VisitEnumConstantDecl(), VisitEnumDecl(), VisitFriendDecl(), VisitFunctionDecl(), VisitFunctionTemplateDecl(), VisitRecordDecl(), VisitVarTemplateDecl(), and VisitVarTemplateSpecializationDecl().
shouldForceImportDeclContext()
bool clang::ASTNodeImporter::shouldForceImportDeclContext (ImportDefinitionKind IDK) inline
Definition at line 455 of file ASTImporter.cpp.
References IDK_Default, IDK_Everything, and clang::ASTImporter::isMinimalImport().
Referenced by ImportDefinition(), ImportDefinition(), ImportDefinition(), and ImportDefinition().
VisitAccessSpecDecl()
ExpectedDecl ASTNodeImporter::VisitAccessSpecDecl (AccessSpecDecl * D)
Definition at line 2331 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::AccessSpecDecl::getColonLoc(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::ASTImporter::ImportContext(), and clang::Decl::setLexicalDeclContext().
VisitAddrLabelExpr()
ExpectedStmt ASTNodeImporter::VisitAddrLabelExpr (AddrLabelExpr * E)
Definition at line 7325 of file ASTImporter.cpp.
References clang::AddrLabelExpr::getAmpAmpLoc(), clang::AddrLabelExpr::getLabel(), clang::AddrLabelExpr::getLabelLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and importChecked().
VisitArrayInitIndexExpr()
ExpectedStmt ASTNodeImporter::VisitArrayInitIndexExpr (ArrayInitIndexExpr * E)
Definition at line 8450 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitArrayInitLoopExpr()
ExpectedStmt ASTNodeImporter::VisitArrayInitLoopExpr (ArrayInitLoopExpr * E)
Definition at line 8438 of file ASTImporter.cpp.
References clang::ArrayInitLoopExpr::getCommonExpr(), clang::ArrayInitLoopExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and importChecked().
VisitArraySubscriptExpr()
ExpectedStmt ASTNodeImporter::VisitArraySubscriptExpr (ArraySubscriptExpr * E)
Definition at line 7536 of file ASTImporter.cpp.
References clang::ArraySubscriptExpr::getLHS(), clang::Expr::getObjectKind(), clang::ArraySubscriptExpr::getRBracketLoc(), clang::ArraySubscriptExpr::getRHS(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitArrayTypeTraitExpr()
ExpectedStmt ASTNodeImporter::VisitArrayTypeTraitExpr (ArrayTypeTraitExpr * E)
Definition at line 7494 of file ASTImporter.cpp.
References clang::ArrayTypeTraitExpr::getBeginLoc(), clang::ArrayTypeTraitExpr::getDimensionExpression(), clang::ArrayTypeTraitExpr::getEndLoc(), clang::ArrayTypeTraitExpr::getQueriedTypeSourceInfo(), clang::ASTImporter::getToContext(), clang::ArrayTypeTraitExpr::getTrait(), clang::Expr::getType(), clang::ArrayTypeTraitExpr::getValue(), and importChecked().
VisitAtomicExpr()
ExpectedStmt ASTNodeImporter::VisitAtomicExpr (AtomicExpr * E)
Definition at line 7305 of file ASTImporter.cpp.
References clang::AtomicExpr::getBuiltinLoc(), clang::AtomicExpr::getNumSubExprs(), clang::AtomicExpr::getOp(), clang::AtomicExpr::getRParenLoc(), clang::AtomicExpr::getSubExprs(), clang::ASTImporter::getToContext(), clang::Expr::getType(), ImportArrayChecked(), and importChecked().
VisitAtomicType()
ExpectedType ASTNodeImporter::VisitAtomicType (const AtomicType * T)
Definition at line 1073 of file ASTImporter.cpp.
References clang::ASTContext::getAtomicType(), and clang::ASTImporter::getToContext().
VisitAttributedStmt()
ExpectedStmt ASTNodeImporter::VisitAttributedStmt (AttributedStmt * S)
Definition at line 6618 of file ASTImporter.cpp.
References clang::AttributedStmt::Create(), clang::ASTImporter::getToContext(), and ImportContainerChecked().
VisitAttributedType()
ExpectedType ASTNodeImporter::VisitAttributedType (const AttributedType * T)
Definition at line 1500 of file ASTImporter.cpp.
References clang::ASTContext::getAttributedType(), and clang::ASTImporter::getToContext().
VisitAutoType()
ExpectedType ASTNodeImporter::VisitAutoType (const AutoType * T)
Definition at line 1436 of file ASTImporter.cpp.
References clang::ASTContext::getAutoType(), clang::ASTImporter::getToContext(), and ImportTemplateArguments().
VisitBinaryConditionalOperator()
ExpectedStmt ASTNodeImporter::VisitBinaryConditionalOperator (BinaryConditionalOperator * E)
Definition at line 7464 of file ASTImporter.cpp.
References clang::AbstractConditionalOperator::getColonLoc(), clang::BinaryConditionalOperator::getCommon(), clang::BinaryConditionalOperator::getCond(), clang::BinaryConditionalOperator::getFalseExpr(), clang::Expr::getObjectKind(), clang::BinaryConditionalOperator::getOpaqueValue(), clang::AbstractConditionalOperator::getQuestionLoc(), clang::ASTImporter::getToContext(), clang::BinaryConditionalOperator::getTrueExpr(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitBinaryOperator()
ExpectedStmt ASTNodeImporter::VisitBinaryOperator (BinaryOperator * E)
Definition at line 7432 of file ASTImporter.cpp.
References clang::BinaryOperator::Create(), clang::BinaryOperator::getFPFeatures(), clang::BinaryOperator::getLHS(), clang::Expr::getObjectKind(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitBindingDecl()
ExpectedDecl ASTNodeImporter::VisitBindingDecl (BindingDecl * D)
Definition at line 2302 of file ASTImporter.cpp.
References clang::BindingDecl::getBinding(), clang::BindingDecl::getDecomposedDecl(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), importChecked(), ImportDeclParts(), clang::BindingDecl::setBinding(), and clang::BindingDecl::setDecomposedDecl().
VisitBlockPointerType()
ExpectedType ASTNodeImporter::VisitBlockPointerType (const BlockPointerType * T)
Definition at line 1170 of file ASTImporter.cpp.
References clang::ASTContext::getBlockPointerType(), and clang::ASTImporter::getToContext().
VisitBreakStmt()
ExpectedStmt ASTNodeImporter::VisitBreakStmt (BreakStmt * S)
Definition at line 6774 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitBuiltinTemplateDecl()
ExpectedDecl ASTNodeImporter::VisitBuiltinTemplateDecl (BuiltinTemplateDecl * D)
Definition at line 5150 of file ASTImporter.cpp.
References clang::BTK__make_integer_seq, clang::BTK__type_pack_element, clang::BuiltinTemplateDecl::getBuiltinTemplateKind(), clang::ASTContext::getMakeIntegerSeqDecl(), clang::ASTImporter::getToContext(), clang::ASTContext::getTypePackElementDecl(), and clang::ASTImporter::MapImported().
VisitBuiltinType()
ExpectedType ASTNodeImporter::VisitBuiltinType (const BuiltinType * T)
Definition at line 1081 of file ASTImporter.cpp.
References clang::ASTContext::CharTy, clang::ASTContext::getLangOpts(), clang::ASTImporter::getToContext(), clang::ASTContext::SignedCharTy, clang::ASTContext::UnsignedCharTy, and clang::ASTContext::WCharTy.
VisitCallExpr()
ExpectedStmt ASTNodeImporter::VisitCallExpr (CallExpr * E)
Definition at line 8310 of file ASTImporter.cpp.
References clang::CallExpr::arguments(), clang::CallExpr::Create(), clang::CXXOperatorCallExpr::Create(), clang::CallExpr::getADLCallKind(), clang::CallExpr::getCallee(), clang::CallExpr::getFPFeatures(), clang::CallExpr::getNumArgs(), clang::CallExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), importChecked(), and ImportContainerChecked().
VisitCaseStmt()
ExpectedStmt ASTNodeImporter::VisitCaseStmt (CaseStmt * S)
Definition at line 6573 of file ASTImporter.cpp.
References clang::CaseStmt::Create(), clang::ASTImporter::getToContext(), and importChecked().
VisitCharacterLiteral()
ExpectedStmt ASTNodeImporter::VisitCharacterLiteral (CharacterLiteral * E)
Definition at line 7262 of file ASTImporter.cpp.
References clang::CharacterLiteral::getKind(), clang::CharacterLiteral::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and clang::CharacterLiteral::getValue().
VisitChooseExpr()
ExpectedStmt ASTNodeImporter::VisitChooseExpr (ChooseExpr * E)
Definition at line 6997 of file ASTImporter.cpp.
References clang::ChooseExpr::getBuiltinLoc(), clang::ChooseExpr::getCond(), clang::ChooseExpr::getLHS(), clang::Expr::getObjectKind(), clang::ChooseExpr::getRHS(), clang::ChooseExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), importChecked(), clang::ChooseExpr::isConditionDependent(), and clang::ChooseExpr::isConditionTrue().
VisitClassTemplateDecl()
ExpectedDecl ASTNodeImporter::VisitClassTemplateDecl (ClassTemplateDecl * D)
Definition at line 5776 of file ASTImporter.cpp.
References clang::Decl::getAccess(), clang::ClassTemplateDecl::getMostRecentDecl(), clang::CXXRecordDecl::getMostRecentDecl(), clang::CXXRecordDecl::getPreviousDecl(), clang::ClassTemplateDecl::getTemplatedDecl(), getTemplateDefinition(), clang::TemplateDecl::getTemplateParameters(), clang::ASTImporter::getToContext(), clang::ASTImporter::HandleNameConflict(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_TagFriend, ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), IsStructuralMatch(), clang::ClassTemplateDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::CXXRecordDecl::setDescribedClassTemplate(), clang::Decl::setLexicalDeclContext(), and clang::Redeclarable< decl_type >::setPreviousDecl().
VisitClassTemplateSpecializationDecl()
ExpectedDecl ASTNodeImporter::VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl * D)
Definition at line 5883 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ClassTemplateDecl::AddPartialSpecialization(), clang::ClassTemplateDecl::AddSpecialization(), clang::TemplateArgumentList::asArray(), clang::cast(), clang::TemplateArgumentList::CreateCopy(), clang::RecordDecl::fields(), clang::ClassTemplateDecl::findPartialSpecialization(), clang::ClassTemplateDecl::findSpecialization(), clang::TypeDecl::getBeginLoc(), clang::TagDecl::getBraceRange(), clang::QualType::getCanonicalType(), clang::CXXRecordDecl::getDefinition(), clang::ClassTemplateSpecializationDecl::getExternLoc(), clang::ClassTemplatePartialSpecializationDecl::getInjectedSpecializationType(), clang::ClassTemplateSpecializationDecl::getInstantiatedFrom(), clang::Decl::getLocation(), clang::ClassTemplateSpecializationDecl::getPointOfInstantiation(), clang::TagDecl::getQualifierLoc(), clang::ClassTemplateSpecializationDecl::getSpecializationKind(), clang::ClassTemplateSpecializationDecl::getSpecializedTemplate(), clang::TagDecl::getTagKind(), clang::ClassTemplateSpecializationDecl::getTemplateArgs(), clang::ClassTemplatePartialSpecializationDecl::getTemplateArgsAsWritten(), clang::ClassTemplateSpecializationDecl::getTemplateInstantiationArgs(), clang::ClassTemplateSpecializationDecl::getTemplateKeywordLoc(), clang::ClassTemplatePartialSpecializationDecl::getTemplateParameters(), clang::CXXRecordDecl::getTemplateSpecializationKind(), clang::ASTImporter::getToContext(), clang::ClassTemplateSpecializationDecl::getTypeAsWritten(), ImportDeclContext(), ImportDefinition(), ImportTemplateArgumentListInfo(), ImportTemplateArguments(), clang::TagDecl::isCompleteDefinition(), clang::ClassTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), IsStructuralMatch(), clang::TagDecl::isThisDeclarationADefinition(), clang::SourceLocation::isValid(), clang::ASTImporter::MapImported(), clang::CXXRecordDecl::methods(), clang::ASTImportError::NameConflict, clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >::P, clang::TagDecl::setBraceRange(), clang::ClassTemplateSpecializationDecl::setExternLoc(), clang::ClassTemplateSpecializationDecl::setInstantiationOf(), clang::Decl::setLexicalDeclContext(), clang::ClassTemplateSpecializationDecl::setPointOfInstantiation(), clang::TagDecl::setQualifierInfo(), clang::ClassTemplateSpecializationDecl::setSpecializationKind(), clang::ClassTemplateSpecializationDecl::setTemplateKeywordLoc(), clang::CXXRecordDecl::setTemplateSpecializationKind(), clang::ClassTemplateSpecializationDecl::setTypeAsWritten(), and clang::TemplateArgumentList::size().
VisitComplexType()
ExpectedType ASTNodeImporter::VisitComplexType (const ComplexType * T)
Definition at line 1154 of file ASTImporter.cpp.
References clang::ASTContext::getComplexType(), and clang::ASTImporter::getToContext().
VisitCompoundAssignOperator()
ExpectedStmt ASTNodeImporter::VisitCompoundAssignOperator (CompoundAssignOperator * E)
Definition at line 7551 of file ASTImporter.cpp.
References clang::CompoundAssignOperator::Create(), clang::CompoundAssignOperator::getComputationLHSType(), clang::CompoundAssignOperator::getComputationResultType(), clang::BinaryOperator::getFPFeatures(), clang::BinaryOperator::getLHS(), clang::Expr::getObjectKind(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitCompoundLiteralExpr()
ExpectedStmt ASTNodeImporter::VisitCompoundLiteralExpr (CompoundLiteralExpr * E)
Definition at line 7290 of file ASTImporter.cpp.
References clang::CompoundLiteralExpr::getInitializer(), clang::CompoundLiteralExpr::getLParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CompoundLiteralExpr::getTypeSourceInfo(), clang::Expr::getValueKind(), importChecked(), and clang::CompoundLiteralExpr::isFileScope().
VisitCompoundStmt()
ExpectedStmt ASTNodeImporter::VisitCompoundStmt (CompoundStmt * S)
Definition at line 6553 of file ASTImporter.cpp.
References clang::CompoundStmt::Create(), clang::ASTImporter::getToContext(), and ImportContainerChecked().
VisitConditionalOperator()
ExpectedStmt ASTNodeImporter::VisitConditionalOperator (ConditionalOperator * E)
Definition at line 7447 of file ASTImporter.cpp.
References clang::AbstractConditionalOperator::getColonLoc(), clang::ConditionalOperator::getCond(), clang::ConditionalOperator::getLHS(), clang::Expr::getObjectKind(), clang::AbstractConditionalOperator::getQuestionLoc(), clang::ConditionalOperator::getRHS(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitConstantArrayType()
ExpectedType ASTNodeImporter::VisitConstantArrayType (const ConstantArrayType * T)
Definition at line 1215 of file ASTImporter.cpp.
References clang::ASTContext::getConstantArrayType(), clang::ASTImporter::getToContext(), and importChecked().
VisitConstantExpr()
ExpectedStmt ASTNodeImporter::VisitConstantExpr (ConstantExpr * E)
Definition at line 7337 of file ASTImporter.cpp.
References clang::ConstantExpr::Create(), clang::ConstantExpr::getAPValueResult(), clang::FullExpr::getSubExpr(), clang::ASTImporter::getToContext(), and importChecked().
VisitContinueStmt()
ExpectedStmt ASTNodeImporter::VisitContinueStmt (ContinueStmt * S)
Definition at line 6767 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitCXXBindTemporaryExpr()
ExpectedStmt ASTNodeImporter::VisitCXXBindTemporaryExpr (CXXBindTemporaryExpr * E)
Definition at line 7808 of file ASTImporter.cpp.
References clang::CXXBindTemporaryExpr::Create(), clang::CXXTemporary::Create(), clang::CXXBindTemporaryExpr::getSubExpr(), clang::CXXBindTemporaryExpr::getTemporary(), and clang::ASTImporter::getToContext().
VisitCXXBoolLiteralExpr()
ExpectedStmt ASTNodeImporter::VisitCXXBoolLiteralExpr (CXXBoolLiteralExpr * E)
Definition at line 8036 of file ASTImporter.cpp.
References clang::CXXBoolLiteralExpr::Create(), clang::CXXBoolLiteralExpr::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and clang::CXXBoolLiteralExpr::getValue().
VisitCXXCatchStmt()
ExpectedStmt ASTNodeImporter::VisitCXXCatchStmt (CXXCatchStmt * S)
Definition at line 6794 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitCXXConstructExpr()
ExpectedStmt ASTNodeImporter::VisitCXXConstructExpr (CXXConstructExpr * E)
Definition at line 7969 of file ASTImporter.cpp.
References clang::CXXConstructExpr::arguments(), clang::CXXConstructExpr::Create(), clang::CXXConstructExpr::getConstructionKind(), clang::CXXConstructExpr::getConstructor(), clang::CXXConstructExpr::getLocation(), clang::CXXConstructExpr::getNumArgs(), clang::CXXConstructExpr::getParenOrBraceRange(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXConstructExpr::hadMultipleCandidates(), importChecked(), ImportContainerChecked(), clang::CXXConstructExpr::isElidable(), clang::CXXConstructExpr::isImmediateEscalating(), clang::CXXConstructExpr::isListInitialization(), clang::CXXConstructExpr::isStdInitListInitialization(), clang::CXXConstructExpr::requiresZeroInitialization(), and clang::CXXConstructExpr::setIsImmediateEscalating().
VisitCXXConstructorDecl()
ExpectedDecl ASTNodeImporter::VisitCXXConstructorDecl (CXXConstructorDecl * D)
Definition at line 3850 of file ASTImporter.cpp.
References VisitCXXMethodDecl().
VisitCXXConversionDecl()
ExpectedDecl ASTNodeImporter::VisitCXXConversionDecl (CXXConversionDecl * D)
Definition at line 3858 of file ASTImporter.cpp.
References VisitCXXMethodDecl().
VisitCXXDeductionGuideDecl()
ExpectedDecl ASTNodeImporter::VisitCXXDeductionGuideDecl (CXXDeductionGuideDecl * D)
Definition at line 3863 of file ASTImporter.cpp.
References VisitFunctionDecl().
VisitCXXDefaultArgExpr()
ExpectedStmt ASTNodeImporter::VisitCXXDefaultArgExpr (CXXDefaultArgExpr * E)
Definition at line 7754 of file ASTImporter.cpp.
References clang::CXXDefaultArgExpr::Create(), clang::ParmVarDecl::getDefaultArg(), clang::ASTImporter::getImportedFromDecl(), clang::CXXDefaultArgExpr::getParam(), clang::CXXDefaultArgExpr::getRewrittenExpr(), clang::ASTImporter::getToContext(), clang::CXXDefaultArgExpr::getUsedContext(), clang::CXXDefaultArgExpr::getUsedLocation(), clang::CXXDefaultArgExpr::hasRewrittenInit(), clang::ASTImporter::ImportContext(), and ImportDefaultArgOfParmVarDecl().
VisitCXXDefaultInitExpr()
ExpectedStmt ASTNodeImporter::VisitCXXDefaultInitExpr (CXXDefaultInitExpr * E)
Definition at line 8457 of file ASTImporter.cpp.
References clang::CXXDefaultInitExpr::Create(), clang::CXXDefaultInitExpr::getBeginLoc(), clang::CXXDefaultInitExpr::getField(), clang::FieldDecl::getInClassInitializer(), clang::CXXDefaultInitExpr::getRewrittenExpr(), clang::ASTImporter::getToContext(), clang::CXXDefaultInitExpr::getUsedContext(), clang::FieldDecl::hasInClassInitializer(), clang::CXXDefaultInitExpr::hasRewrittenInit(), clang::ASTImporter::ImportContext(), and clang::FieldDecl::setInClassInitializer().
VisitCXXDeleteExpr()
ExpectedStmt ASTNodeImporter::VisitCXXDeleteExpr (CXXDeleteExpr * E)
Definition at line 7954 of file ASTImporter.cpp.
References clang::CXXDeleteExpr::doesUsualArrayDeleteWantSize(), clang::CXXDeleteExpr::getArgument(), clang::CXXDeleteExpr::getBeginLoc(), clang::CXXDeleteExpr::getOperatorDelete(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), clang::CXXDeleteExpr::isArrayForm(), clang::CXXDeleteExpr::isArrayFormAsWritten(), and clang::CXXDeleteExpr::isGlobalDelete().
VisitCXXDependentScopeMemberExpr()
ExpectedStmt ASTNodeImporter::VisitCXXDependentScopeMemberExpr (CXXDependentScopeMemberExpr * E)
Definition at line 8115 of file ASTImporter.cpp.
References clang::CXXDependentScopeMemberExpr::Create(), clang::CXXDependentScopeMemberExpr::getBase(), clang::CXXDependentScopeMemberExpr::getFirstQualifierFoundInScope(), clang::CXXDependentScopeMemberExpr::getLAngleLoc(), clang::CXXDependentScopeMemberExpr::getMember(), clang::CXXDependentScopeMemberExpr::getMemberLoc(), clang::CXXDependentScopeMemberExpr::getMemberNameInfo(), clang::CXXDependentScopeMemberExpr::getOperatorLoc(), clang::CXXDependentScopeMemberExpr::getQualifierLoc(), clang::CXXDependentScopeMemberExpr::getRAngleLoc(), clang::CXXDependentScopeMemberExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXDependentScopeMemberExpr::hasExplicitTemplateArgs(), importChecked(), ImportDeclarationNameLoc(), ImportTemplateArgumentListInfo(), clang::CXXDependentScopeMemberExpr::isArrow(), clang::CXXDependentScopeMemberExpr::isImplicitAccess(), and clang::CXXDependentScopeMemberExpr::template_arguments().
VisitCXXDestructorDecl()
ExpectedDecl ASTNodeImporter::VisitCXXDestructorDecl (CXXDestructorDecl * D)
Definition at line 3854 of file ASTImporter.cpp.
References VisitCXXMethodDecl().
VisitCXXFoldExpr()
ExpectedStmt ASTNodeImporter::VisitCXXFoldExpr (CXXFoldExpr * E)
Definition at line 8598 of file ASTImporter.cpp.
References clang::CXXFoldExpr::getCallee(), clang::CXXFoldExpr::getEllipsisLoc(), clang::CXXFoldExpr::getLHS(), clang::CXXFoldExpr::getLParenLoc(), clang::CXXFoldExpr::getNumExpansions(), clang::CXXFoldExpr::getOperator(), clang::CXXFoldExpr::getRHS(), clang::CXXFoldExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and importChecked().
VisitCXXForRangeStmt()
ExpectedStmt ASTNodeImporter::VisitCXXForRangeStmt (CXXForRangeStmt * S)
Definition at line 6829 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitCXXInheritedCtorInitExpr()
ExpectedStmt ASTNodeImporter::VisitCXXInheritedCtorInitExpr (CXXInheritedCtorInitExpr * E)
Definition at line 8424 of file ASTImporter.cpp.
References clang::CXXInheritedCtorInitExpr::constructsVBase(), clang::CXXInheritedCtorInitExpr::getConstructor(), clang::CXXInheritedCtorInitExpr::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::CXXInheritedCtorInitExpr::inheritedFromVBase().
VisitCXXMemberCallExpr()
ExpectedStmt ASTNodeImporter::VisitCXXMemberCallExpr (CXXMemberCallExpr * E)
Definition at line 8006 of file ASTImporter.cpp.
References clang::CallExpr::arguments(), clang::CXXMemberCallExpr::Create(), clang::CallExpr::getCallee(), clang::CallExpr::getFPFeatures(), clang::CallExpr::getNumArgs(), clang::CallExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), importChecked(), and ImportContainerChecked().
VisitCXXMethodDecl()
ExpectedDecl ASTNodeImporter::VisitCXXMethodDecl (CXXMethodDecl * D)
Definition at line 3846 of file ASTImporter.cpp.
References VisitFunctionDecl().
Referenced by VisitCXXConstructorDecl(), VisitCXXConversionDecl(), and VisitCXXDestructorDecl().
VisitCXXNamedCastExpr()
ExpectedStmt ASTNodeImporter::VisitCXXNamedCastExpr (CXXNamedCastExpr * E)
Definition at line 8497 of file ASTImporter.cpp.
References clang::CXXConstCastExpr::Create(), clang::CXXDynamicCastExpr::Create(), clang::CXXReinterpretCastExpr::Create(), clang::CXXStaticCastExpr::Create(), clang::CXXNamedCastExpr::getAngleBrackets(), clang::CastExpr::getCastKind(), clang::CXXNamedCastExpr::getOperatorLoc(), clang::CXXNamedCastExpr::getRParenLoc(), clang::CastExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::ExplicitCastExpr::getTypeInfoAsWritten(), clang::Expr::getValueKind(), ImportCastPath(), and importChecked().
VisitCXXNewExpr()
ExpectedStmt ASTNodeImporter::VisitCXXNewExpr (CXXNewExpr * E)
Definition at line 7926 of file ASTImporter.cpp.
References clang::CXXNewExpr::Create(), clang::CXXNewExpr::doesUsualArrayDeleteWantSize(), clang::CXXNewExpr::getAllocatedTypeSourceInfo(), clang::CXXNewExpr::getArraySize(), clang::CXXNewExpr::getDirectInitRange(), clang::CXXNewExpr::getInitializationStyle(), clang::CXXNewExpr::getInitializer(), clang::CXXNewExpr::getNumPlacementArgs(), clang::CXXNewExpr::getOperatorDelete(), clang::CXXNewExpr::getOperatorNew(), clang::CXXNewExpr::getSourceRange(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXNewExpr::getTypeIdParens(), importChecked(), ImportContainerChecked(), clang::CXXNewExpr::isGlobalNew(), clang::CXXNewExpr::passAlignment(), and clang::CXXNewExpr::placement_arguments().
VisitCXXNoexceptExpr()
ExpectedStmt ASTNodeImporter::VisitCXXNoexceptExpr (CXXNoexceptExpr * E)
Definition at line 7723 of file ASTImporter.cpp.
References clang::CT_Can, clang::CT_Cannot, clang::CT_Dependent, clang::CXXNoexceptExpr::getBeginLoc(), clang::CXXNoexceptExpr::getEndLoc(), clang::CXXNoexceptExpr::getOperand(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXNoexceptExpr::getValue(), importChecked(), and clang::Expr::isValueDependent().
VisitCXXNullPtrLiteralExpr()
ExpectedStmt ASTNodeImporter::VisitCXXNullPtrLiteralExpr (CXXNullPtrLiteralExpr * E)
Definition at line 7194 of file ASTImporter.cpp.
References clang::CXXNullPtrLiteralExpr::getLocation(), clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitCXXPseudoDestructorExpr()
ExpectedStmt ASTNodeImporter::VisitCXXPseudoDestructorExpr (CXXPseudoDestructorExpr * E)
Definition at line 8085 of file ASTImporter.cpp.
References clang::CXXPseudoDestructorExpr::getBase(), clang::CXXPseudoDestructorExpr::getColonColonLoc(), clang::CXXPseudoDestructorExpr::getDestroyedTypeIdentifier(), clang::CXXPseudoDestructorExpr::getDestroyedTypeInfo(), clang::CXXPseudoDestructorExpr::getDestroyedTypeLoc(), clang::CXXPseudoDestructorExpr::getOperatorLoc(), clang::CXXPseudoDestructorExpr::getQualifierLoc(), clang::CXXPseudoDestructorExpr::getScopeTypeInfo(), clang::CXXPseudoDestructorExpr::getTildeLoc(), clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), importChecked(), and clang::CXXPseudoDestructorExpr::isArrow().
VisitCXXRewrittenBinaryOperator()
ExpectedStmt ASTNodeImporter::VisitCXXRewrittenBinaryOperator (CXXRewrittenBinaryOperator * E)
Definition at line 7483 of file ASTImporter.cpp.
References clang::CXXRewrittenBinaryOperator::getSemanticForm(), clang::ASTImporter::getToContext(), importChecked(), and clang::CXXRewrittenBinaryOperator::isReversed().
VisitCXXScalarValueInitExpr()
ExpectedStmt ASTNodeImporter::VisitCXXScalarValueInitExpr (CXXScalarValueInitExpr * E)
Definition at line 7795 of file ASTImporter.cpp.
References clang::CXXScalarValueInitExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXScalarValueInitExpr::getTypeSourceInfo(), and importChecked().
VisitCXXStdInitializerListExpr()
ExpectedStmt ASTNodeImporter::VisitCXXStdInitializerListExpr (CXXStdInitializerListExpr * E)
Definition at line 8410 of file ASTImporter.cpp.
References clang::CXXStdInitializerListExpr::getSubExpr(), clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitCXXTemporaryObjectExpr()
ExpectedStmt ASTNodeImporter::VisitCXXTemporaryObjectExpr (CXXTemporaryObjectExpr * E)
Definition at line 7824 of file ASTImporter.cpp.
References clang::CXXConstructExpr::arguments(), clang::CXXTemporaryObjectExpr::Create(), clang::CXXConstructExpr::getConstructor(), clang::CXXConstructExpr::getNumArgs(), clang::CXXConstructExpr::getParenOrBraceRange(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXTemporaryObjectExpr::getTypeSourceInfo(), clang::CXXConstructExpr::hadMultipleCandidates(), importChecked(), ImportContainerChecked(), clang::CXXConstructExpr::isListInitialization(), clang::CXXConstructExpr::isStdInitListInitialization(), and clang::CXXConstructExpr::requiresZeroInitialization().
VisitCXXThisExpr()
ExpectedStmt ASTNodeImporter::VisitCXXThisExpr (CXXThisExpr * E)
Definition at line 8023 of file ASTImporter.cpp.
References clang::CXXThisExpr::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and clang::CXXThisExpr::isImplicit().
VisitCXXThrowExpr()
ExpectedStmt ASTNodeImporter::VisitCXXThrowExpr (CXXThrowExpr * E)
Definition at line 7742 of file ASTImporter.cpp.
References clang::CXXThrowExpr::getSubExpr(), clang::CXXThrowExpr::getThrowLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::CXXThrowExpr::isThrownVariableInScope().
VisitCXXTryStmt()
ExpectedStmt ASTNodeImporter::VisitCXXTryStmt (CXXTryStmt * S)
Definition at line 6807 of file ASTImporter.cpp.
References clang::CXXTryStmt::Create(), and clang::ASTImporter::getToContext().
VisitCXXTypeidExpr()
ExpectedStmt ASTNodeImporter::VisitCXXTypeidExpr (CXXTypeidExpr * E)
Definition at line 8573 of file ASTImporter.cpp.
References clang::CXXTypeidExpr::getExprOperand(), clang::CXXTypeidExpr::getSourceRange(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXTypeidExpr::getTypeOperandSourceInfo(), and clang::CXXTypeidExpr::isTypeOperand().
VisitCXXUnresolvedConstructExpr()
ExpectedStmt ASTNodeImporter::VisitCXXUnresolvedConstructExpr (CXXUnresolvedConstructExpr * E)
Definition at line 8191 of file ASTImporter.cpp.
References clang::CXXUnresolvedConstructExpr::arg_begin(), clang::CXXUnresolvedConstructExpr::arg_end(), clang::CXXUnresolvedConstructExpr::Create(), clang::CXXUnresolvedConstructExpr::getLParenLoc(), clang::CXXUnresolvedConstructExpr::getNumArgs(), clang::CXXUnresolvedConstructExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::CXXUnresolvedConstructExpr::getTypeSourceInfo(), ImportArrayChecked(), importChecked(), and clang::CXXUnresolvedConstructExpr::isListInitialization().
VisitDecayedType()
ExpectedType ASTNodeImporter::VisitDecayedType (const DecayedType * T)
Definition at line 1146 of file ASTImporter.cpp.
References clang::ASTContext::getDecayedType(), and clang::ASTImporter::getToContext().
VisitDecl()
ExpectedDecl ASTNodeImporter::VisitDecl (Decl * D)
Definition at line 2261 of file ASTImporter.cpp.
References clang::ASTImporter::FromDiag(), clang::Decl::getDeclKindName(), clang::Decl::getLocation(), and clang::ASTImportError::UnsupportedConstruct.
VisitDeclRefExpr()
ExpectedStmt ASTNodeImporter::VisitDeclRefExpr (DeclRefExpr * E)
Definition at line 7118 of file ASTImporter.cpp.
References clang::DeclRefExpr::Create(), clang::DeclRefExpr::getDecl(), clang::DeclRefExpr::getFoundDecl(), clang::DeclRefExpr::getLAngleLoc(), clang::DeclRefExpr::getLocation(), clang::DeclRefExpr::getQualifierLoc(), clang::DeclRefExpr::getRAngleLoc(), clang::DeclRefExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), clang::DeclRefExpr::hadMultipleCandidates(), clang::DeclRefExpr::hasExplicitTemplateArgs(), importChecked(), ImportTemplateArgumentListInfo(), clang::DeclRefExpr::isImmediateEscalating(), clang::DeclRefExpr::isNonOdrUse(), clang::DeclRefExpr::refersToEnclosingVariableOrCapture(), and clang::DeclRefExpr::template_arguments().
VisitDeclStmt()
ExpectedStmt ASTNodeImporter::VisitDeclStmt (DeclStmt * S)
Definition at line 6534 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitDecltypeType()
ExpectedType ASTNodeImporter::VisitDecltypeType (const DecltypeType * T)
Definition at line 1408 of file ASTImporter.cpp.
References clang::ASTContext::getDecltypeType(), and clang::ASTImporter::getToContext().
VisitDeducedTemplateSpecializationType()
ExpectedType ASTNodeImporter::VisitDeducedTemplateSpecializationType (const DeducedTemplateSpecializationType * T)
Definition at line 1457 of file ASTImporter.cpp.
References clang::ASTContext::getDeducedTemplateSpecializationType(), and clang::ASTImporter::getToContext().
VisitDefaultStmt()
ExpectedStmt ASTNodeImporter::VisitDefaultStmt (DefaultStmt * S)
Definition at line 6592 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitDependentNameType()
ExpectedType ASTNodeImporter::VisitDependentNameType (const DependentNameType * T)
Definition at line 1625 of file ASTImporter.cpp.
References clang::QualType::getCanonicalType(), clang::ASTContext::getDependentNameType(), clang::ASTImporter::getToContext(), and clang::ASTImporter::Import().
VisitDependentScopeDeclRefExpr()
ExpectedStmt ASTNodeImporter::VisitDependentScopeDeclRefExpr (DependentScopeDeclRefExpr * E)
Definition at line 8162 of file ASTImporter.cpp.
References clang::DependentScopeDeclRefExpr::Create(), clang::DependentScopeDeclRefExpr::getDeclName(), clang::DependentScopeDeclRefExpr::getLAngleLoc(), clang::DeclarationNameInfo::getLoc(), clang::DependentScopeDeclRefExpr::getNameInfo(), clang::DependentScopeDeclRefExpr::getQualifierLoc(), clang::DependentScopeDeclRefExpr::getRAngleLoc(), clang::DependentScopeDeclRefExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::DependentScopeDeclRefExpr::hasExplicitTemplateArgs(), importChecked(), ImportDeclarationNameLoc(), ImportTemplateArgumentListInfo(), and clang::DependentScopeDeclRefExpr::template_arguments().
VisitDependentSizedArrayType()
ExpectedType ASTNodeImporter::VisitDependentSizedArrayType (const DependentSizedArrayType * T)
Definition at line 1251 of file ASTImporter.cpp.
References clang::ASTContext::getDependentSizedArrayType(), clang::ASTImporter::getToContext(), and importChecked().
VisitDependentTemplateSpecializationType()
ExpectedType ASTNodeImporter::VisitDependentTemplateSpecializationType (const DependentTemplateSpecializationType * T)
Definition at line 1607 of file ASTImporter.cpp.
References clang::ASTContext::getDependentTemplateSpecializationType(), clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), and ImportTemplateArguments().
VisitDesignatedInitExpr()
ExpectedStmt ASTNodeImporter::VisitDesignatedInitExpr (DesignatedInitExpr * E)
Definition at line 7165 of file ASTImporter.cpp.
References clang::DesignatedInitExpr::Create(), clang::DesignatedInitExpr::designators(), clang::DesignatedInitExpr::getEqualOrColonLoc(), clang::DesignatedInitExpr::getInit(), clang::DesignatedInitExpr::getNumSubExprs(), clang::DesignatedInitExpr::getSubExpr(), clang::ASTImporter::getToContext(), ImportContainerChecked(), N, clang::DesignatedInitExpr::size(), and clang::DesignatedInitExpr::usesGNUSyntax().
VisitDoStmt()
ExpectedStmt ASTNodeImporter::VisitDoStmt (DoStmt * S)
Definition at line 6706 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitElaboratedType()
ExpectedType ASTNodeImporter::VisitElaboratedType (const ElaboratedType * T)
Definition at line 1576 of file ASTImporter.cpp.
References clang::ASTContext::getElaboratedType(), and clang::ASTImporter::getToContext().
VisitEmptyDecl()
ExpectedDecl ASTNodeImporter::VisitEmptyDecl (EmptyDecl * D)
Definition at line 2273 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), ImportDeclContext(), and clang::Decl::setLexicalDeclContext().
VisitEnumConstantDecl()
ExpectedDecl ASTNodeImporter::VisitEnumConstantDecl (EnumConstantDecl * D)
Definition at line 3080 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::EnumConstantDecl::getInitExpr(), clang::EnumConstantDecl::getInitVal(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), clang::ASTImporter::HandleNameConflict(), clang::Decl::IDNS_Ordinary, ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), IsStructuralMatch(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), and clang::Decl::setLexicalDeclContext().
VisitEnumDecl()
ExpectedDecl ASTNodeImporter::VisitEnumDecl (EnumDecl * D)
Definition at line 2724 of file ASTImporter.cpp.
References clang::Decl::getAccess(), clang::TypeDecl::getBeginLoc(), clang::TagDecl::getBraceRange(), clang::NamedDecl::getDeclName(), clang::EnumDecl::getDefinition(), clang::EnumDecl::getInstantiatedFromMemberEnum(), clang::EnumDecl::getIntegerType(), clang::ASTContext::getLangOpts(), clang::EnumDecl::getMemberSpecializationInfo(), clang::EnumDecl::getMostRecentDecl(), clang::TagDecl::getQualifierLoc(), clang::ASTImporter::getToContext(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::ASTImporter::HandleNameConflict(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_Tag, importChecked(), ImportDeclParts(), ImportDefinition(), clang::TagDecl::isCompleteDefinition(), clang::EnumDecl::isFixed(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), clang::EnumDecl::isScoped(), clang::EnumDecl::isScopedUsingClassTag(), IsStructuralMatch(), clang::TagDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::TagDecl::setBraceRange(), clang::EnumDecl::setIntegerType(), clang::Decl::setLexicalDeclContext(), clang::MemberSpecializationInfo::setPointOfInstantiation(), and clang::TagDecl::setQualifierInfo().
VisitEnumType()
ExpectedType ASTNodeImporter::VisitEnumType (const EnumType * T)
Definition at line 1492 of file ASTImporter.cpp.
References clang::ASTContext::getTagDeclType(), and clang::ASTImporter::getToContext().
VisitExplicitCastExpr()
ExpectedStmt ASTNodeImporter::VisitExplicitCastExpr (ExplicitCastExpr * E)
Definition at line 7600 of file ASTImporter.cpp.
References clang::cast(), clang::CStyleCastExpr::Create(), clang::CXXFunctionalCastExpr::Create(), clang::CastExpr::getCastKind(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::ExplicitCastExpr::getTypeInfoAsWritten(), clang::Expr::getValueKind(), ImportCastPath(), importChecked(), and clang::ASTImportError::UnsupportedConstruct.
VisitExpr()
ExpectedStmt ASTNodeImporter::VisitExpr (Expr * E)
Definition at line 6959 of file ASTImporter.cpp.
References clang::ASTImporter::FromDiag(), clang::Stmt::getBeginLoc(), clang::Stmt::getStmtClassName(), and clang::ASTImportError::UnsupportedConstruct.
VisitExpressionTraitExpr()
ExpectedStmt ASTNodeImporter::VisitExpressionTraitExpr (ExpressionTraitExpr * E)
Definition at line 7510 of file ASTImporter.cpp.
References clang::ExpressionTraitExpr::getBeginLoc(), clang::ExpressionTraitExpr::getEndLoc(), clang::ExpressionTraitExpr::getQueriedExpression(), clang::ASTImporter::getToContext(), clang::ExpressionTraitExpr::getTrait(), clang::Expr::getType(), clang::ExpressionTraitExpr::getValue(), and importChecked().
VisitExprWithCleanups()
ExpectedStmt ASTNodeImporter::VisitExprWithCleanups (ExprWithCleanups * E)
Definition at line 7992 of file ASTImporter.cpp.
References clang::ExprWithCleanups::cleanupsHaveSideEffects(), clang::ExprWithCleanups::Create(), clang::ExprWithCleanups::getNumObjects(), clang::ExprWithCleanups::getObjects(), clang::FullExpr::getSubExpr(), clang::ASTImporter::getToContext(), and ImportContainerChecked().
VisitExtVectorType()
ExpectedType ASTNodeImporter::VisitExtVectorType (const ExtVectorType * T)
Definition at line 1277 of file ASTImporter.cpp.
References clang::ASTContext::getExtVectorType(), and clang::ASTImporter::getToContext().
VisitFieldDecl()
ExpectedDecl ASTNodeImporter::VisitFieldDecl (FieldDecl * D)
Definition at line 3867 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::FieldDecl::getBitWidth(), clang::FieldDecl::getCapturedVLAType(), clang::ASTImporter::getFieldIndex(), clang::FieldDecl::getInClassInitializer(), clang::FieldDecl::getInClassInitStyle(), clang::DeclaratorDecl::getInnerLocStart(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), importChecked(), ImportDeclParts(), clang::ASTImporter::importInto(), clang::Decl::isImplicit(), clang::FieldDecl::isMutable(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::Decl::setAccess(), clang::FieldDecl::setCapturedVLAType(), clang::Decl::setImplicit(), clang::FieldDecl::setInClassInitializer(), clang::Decl::setLexicalDeclContext(), and clang::ASTImporter::ToDiag().
VisitFixedPointLiteral()
ExpectedStmt ASTNodeImporter::VisitFixedPointLiteral (FixedPointLiteral * E)
Definition at line 7248 of file ASTImporter.cpp.
References clang::ASTContext::getFixedPointScale(), clang::FixedPointLiteral::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and clang::APIntStorage::getValue().
VisitFloatingLiteral()
ExpectedStmt ASTNodeImporter::VisitFloatingLiteral (FloatingLiteral * E)
Definition at line 7221 of file ASTImporter.cpp.
References clang::FloatingLiteral::Create(), clang::FloatingLiteral::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::FloatingLiteral::getValue(), and clang::FloatingLiteral::isExact().
VisitForStmt()
ExpectedStmt ASTNodeImporter::VisitForStmt (ForStmt * S)
Definition at line 6721 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitFriendDecl()
ExpectedDecl ASTNodeImporter::VisitFriendDecl (FriendDecl * D)
Definition at line 4078 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::cast(), clang::Decl::FOK_None, clang::Decl::getAccess(), getFriendCountAndPosition(), clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendLoc(), clang::FriendDecl::getFriendType(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::TypeSourceInfo::getType(), clang::Decl::IDNS_NonMemberOperator, ImportDeclContext(), FriendCountAndPosition::IndexOfDecl, clang::ASTImporter::IsStructurallyEquivalent(), IsStructuralMatch(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::Decl::setLexicalDeclContext(), clang::Decl::setObjectOfFriendDecl(), and FriendCountAndPosition::TotalCount.
VisitFunctionDecl()
ExpectedDecl ASTNodeImporter::VisitFunctionDecl (FunctionDecl * D)
Definition at line 3472 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::cast(), clang::FunctionDecl::doesThisDeclarationHaveABody(), clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, FindFunctionTemplateSpecialization(), clang::FunctionDecl::FriendConstraintRefersToEnclosingTemplate(), clang::Decl::getAccess(), clang::Type::getAs(), clang::DeclaratorDecl::getBeginLoc(), clang::getCanonicalForwardRedeclChain(), clang::FunctionDecl::getConstexprKind(), clang::Decl::getDeclContext(), clang::FunctionDecl::getDefaultLoc(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::Decl::getEndLoc(), clang::ASTImporter::getFromContext(), clang::ASTContext::getFunctionType(), clang::DeclaratorDecl::getInnerLocStart(), clang::ASTContext::getLangOpts(), clang::Decl::getLexicalDeclContext(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::FunctionDecl::getNameInfo(), clang::DeclaratorDecl::getQualifierLoc(), clang::FunctionDecl::getStorageClass(), clang::FunctionDecl::getTemplatedKind(), clang::ASTImporter::getToContext(), clang::DeclaratorDecl::getTrailingRequiresClause(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTImporter::HandleNameConflict(), hasAutoReturnTypeDeclaredInside(), hasSameVisibilityContextAndLinkage(), clang::FunctionDecl::hasWrittenPrototype(), clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_OrdinaryFriend, importChecked(), ImportContainerChecked(), ImportDeclarationNameLoc(), ImportDeclParts(), ImportFunctionDeclBody(), ImportOverriddenMethods(), ImportTemplateInformation(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isDeletedAsWritten(), clang::FunctionDecl::isExplicitlyDefaulted(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isImplicit(), clang::Decl::isInIdentifierNamespace(), clang::FunctionDecl::isInlineSpecified(), clang::FunctionDecl::isPure(), IsStructuralMatch(), clang::FunctionDecl::isTrivial(), clang::FunctionDecl::isVirtualAsWritten(), LT, clang::ASTImporter::MapImported(), N, clang::FunctionProtoType::ExceptionSpecInfo::NoexceptExpr, clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >::P, clang::FunctionDecl::parameters(), clang::Decl::setAccess(), clang::FunctionDecl::setDefaulted(), clang::FunctionDecl::setDefaultLoc(), clang::FunctionDecl::setDeletedAsWritten(), clang::FunctionDecl::setExplicitlyDefaulted(), clang::FunctionDecl::setFriendConstraintRefersToEnclosingTemplate(), clang::Decl::setLexicalDeclContext(), clang::CXXDestructorDecl::setOperatorDelete(), clang::Redeclarable< decl_type >::setPreviousDecl(), clang::FunctionDecl::setPure(), clang::DeclaratorDecl::setQualifierInfo(), clang::FunctionDecl::setRangeEnd(), clang::FunctionDecl::setTrivial(), clang::ValueDecl::setType(), clang::DeclaratorDecl::setTypeSourceInfo(), clang::FunctionDecl::setVirtualAsWritten(), clang::FunctionProtoType::ExceptionSpecInfo::SourceDecl, clang::FunctionProtoType::ExceptionSpecInfo::SourceTemplate, clang::FunctionDecl::TK_FunctionTemplateSpecialization, clang::ASTImporter::ToDiag(), clang::ASTImporterLookupTable::update(), clang::FunctionDecl::UsesFPIntrin(), and clang::ASTContext::VoidTy.
Referenced by VisitCXXDeductionGuideDecl(), and VisitCXXMethodDecl().
VisitFunctionNoProtoType()
ExpectedType ASTNodeImporter::VisitFunctionNoProtoType (const FunctionNoProtoType * T)
Definition at line 1287 of file ASTImporter.cpp.
References clang::ASTContext::getFunctionNoProtoType(), and clang::ASTImporter::getToContext().
VisitFunctionProtoType()
ExpectedType ASTNodeImporter::VisitFunctionProtoType (const FunctionProtoType * T)
Definition at line 1299 of file ASTImporter.cpp.
References clang::FunctionProtoType::ExceptionSpecInfo::Exceptions, clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::FunctionProtoType::ExtProtoInfo::ExtInfo, clang::ASTContext::getFunctionType(), clang::ASTImporter::getToContext(), clang::FunctionProtoType::ExtProtoInfo::HasTrailingReturn, importChecked(), clang::FunctionProtoType::ExceptionSpecInfo::NoexceptExpr, clang::FunctionProtoType::ExtProtoInfo::RefQualifier, clang::FunctionProtoType::ExceptionSpecInfo::SourceDecl, clang::FunctionProtoType::ExceptionSpecInfo::SourceTemplate, clang::FunctionProtoType::ExceptionSpecInfo::Type, clang::FunctionProtoType::ExtProtoInfo::TypeQuals, and clang::FunctionProtoType::ExtProtoInfo::Variadic.
VisitFunctionTemplateDecl()
ExpectedDecl ASTNodeImporter::VisitFunctionTemplateDecl (FunctionTemplateDecl * D)
Definition at line 6338 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::Decl::getDeclContext(), clang::FunctionTemplateDecl::getMostRecentDecl(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::TemplateParameterList::getParam(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::FunctionTemplateDecl::getTemplatedDecl(), getTemplateDefinition(), clang::TemplateDecl::getTemplateParameters(), clang::ASTImporter::getToContext(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_OrdinaryFriend, ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), IsStructuralMatch(), clang::FunctionTemplateDecl::isThisDeclarationADefinition(), LT, clang::ASTImporter::MapImported(), clang::FunctionDecl::setDescribedFunctionTemplate(), clang::Redeclarable< decl_type >::setPreviousDecl(), clang::TemplateParameterList::size(), and clang::ASTImporterLookupTable::updateForced().
VisitGCCAsmStmt()
ExpectedStmt ASTNodeImporter::VisitGCCAsmStmt (GCCAsmStmt * S)
Definition at line 6452 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), ImportArrayChecked(), ImportContainerChecked(), clang::ASTImporter::returnWithErrorInTest(), and clang::ASTImportError::UnsupportedConstruct.
VisitGenericSelectionExpr()
ExpectedStmt ASTNodeImporter::VisitGenericSelectionExpr (GenericSelectionExpr * E)
Definition at line 7052 of file ASTImporter.cpp.
References clang::Expr::containsUnexpandedParameterPack(), clang::GenericSelectionExpr::Create(), clang::GenericSelectionExpr::getAssocExprs(), clang::GenericSelectionExpr::getAssocTypeSourceInfos(), clang::GenericSelectionExpr::getControllingExpr(), clang::GenericSelectionExpr::getControllingType(), clang::GenericSelectionExpr::getDefaultLoc(), clang::GenericSelectionExpr::getGenericLoc(), clang::GenericSelectionExpr::getResultIndex(), clang::GenericSelectionExpr::getRParenLoc(), clang::ASTImporter::getToContext(), importChecked(), ImportContainerChecked(), clang::GenericSelectionExpr::isExprPredicate(), and clang::GenericSelectionExpr::isResultDependent().
VisitGNUNullExpr()
ExpectedStmt ASTNodeImporter::VisitGNUNullExpr (GNUNullExpr * E)
Definition at line 7039 of file ASTImporter.cpp.
References clang::GNUNullExpr::getBeginLoc(), clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitGotoStmt()
ExpectedStmt ASTNodeImporter::VisitGotoStmt (GotoStmt * S)
Definition at line 6741 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitIfStmt()
ExpectedStmt ASTNodeImporter::VisitIfStmt (IfStmt * S)
Definition at line 6634 of file ASTImporter.cpp.
References clang::IfStmt::Create(), clang::ASTImporter::getToContext(), and importChecked().
VisitImaginaryLiteral()
ExpectedStmt ASTNodeImporter::VisitImaginaryLiteral (ImaginaryLiteral * E)
Definition at line 7235 of file ASTImporter.cpp.
References clang::ImaginaryLiteral::getSubExpr(), clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitImplicitCastExpr()
ExpectedStmt ASTNodeImporter::VisitImplicitCastExpr (ImplicitCastExpr * E)
Definition at line 7582 of file ASTImporter.cpp.
References clang::ImplicitCastExpr::Create(), clang::CastExpr::getCastKind(), clang::CastExpr::getFPFeatures(), clang::CastExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and ImportCastPath().
VisitImplicitParamDecl()
ExpectedDecl ASTNodeImporter::VisitImplicitParamDecl (ImplicitParamDecl * D)
Definition at line 4377 of file ASTImporter.cpp.
References clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::ImplicitParamDecl::getParameterKind(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::ValueDecl::getType(), and importChecked().
VisitImplicitValueInitExpr()
ExpectedStmt ASTNodeImporter::VisitImplicitValueInitExpr (ImplicitValueInitExpr * E)
Definition at line 7157 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::Expr::getType().
VisitImportDecl()
ExpectedDecl ASTNodeImporter::VisitImportDecl (ImportDecl * D)
Definition at line 2267 of file ASTImporter.cpp.
References clang::ASTImporter::FromDiag(), clang::Decl::getDeclKindName(), clang::Decl::getLocation(), and clang::ASTImportError::UnsupportedConstruct.
VisitIncompleteArrayType()
ExpectedType ASTNodeImporter::VisitIncompleteArrayType (const IncompleteArrayType * T)
Definition at line 1228 of file ASTImporter.cpp.
References clang::ASTContext::getIncompleteArrayType(), and clang::ASTImporter::getToContext().
VisitIndirectFieldDecl()
ExpectedDecl ASTNodeImporter::VisitIndirectFieldDecl (IndirectFieldDecl * D)
Definition at line 3960 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::IndirectFieldDecl::chain(), clang::Decl::getAccess(), clang::IndirectFieldDecl::getChainingSize(), clang::ASTImporter::getFieldIndex(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), ImportDeclParts(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ASTImporter::MapImported(), N, clang::ASTImportError::NameConflict, clang::Decl::setAccess(), clang::Decl::setLexicalDeclContext(), and clang::ASTImporter::ToDiag().
VisitIndirectGotoStmt()
ExpectedStmt ASTNodeImporter::VisitIndirectGotoStmt (IndirectGotoStmt * S)
Definition at line 6754 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitInitListExpr()
ExpectedStmt ASTNodeImporter::VisitInitListExpr (InitListExpr * E)
Definition at line 8365 of file ASTImporter.cpp.
References clang::InitListExpr::getArrayFiller(), clang::InitListExpr::getInitializedFieldInUnion(), clang::InitListExpr::getLBraceLoc(), clang::InitListExpr::getNumInits(), clang::InitListExpr::getRBraceLoc(), clang::InitListExpr::getSyntacticForm(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::InitListExpr::hadArrayRangeDesignator(), clang::InitListExpr::hasArrayFiller(), importChecked(), ImportContainerChecked(), clang::InitListExpr::inits(), clang::InitListExpr::sawArrayRangeDesignator(), clang::InitListExpr::setArrayFiller(), clang::InitListExpr::setInitializedFieldInUnion(), clang::InitListExpr::setSyntacticForm(), and clang::Expr::setType().
VisitInjectedClassNameType()
ExpectedType ASTNodeImporter::VisitInjectedClassNameType (const InjectedClassNameType * T)
Definition at line 1471 of file ASTImporter.cpp.
VisitIntegerLiteral()
ExpectedStmt ASTNodeImporter::VisitIntegerLiteral (IntegerLiteral * E)
Definition at line 7207 of file ASTImporter.cpp.
References clang::IntegerLiteral::Create(), clang::IntegerLiteral::getLocation(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and clang::APIntStorage::getValue().
VisitLabelDecl()
ExpectedDecl ASTNodeImporter::VisitLabelDecl (LabelDecl * D)
Definition at line 2685 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getBeginLoc(), clang::LabelDecl::getStmt(), clang::ASTImporter::getToContext(), ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::LabelDecl::isGnuLocal(), clang::Decl::setLexicalDeclContext(), and clang::LabelDecl::setStmt().
VisitLabelStmt()
ExpectedStmt ASTNodeImporter::VisitLabelStmt (LabelStmt * S)
Definition at line 6605 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitLambdaExpr()
ExpectedStmt ASTNodeImporter::VisitLambdaExpr (LambdaExpr * LE)
Definition at line 8335 of file ASTImporter.cpp.
References clang::LambdaExpr::capture_inits(), clang::LambdaExpr::capture_size(), clang::Expr::containsUnexpandedParameterPack(), clang::LambdaExpr::Create(), clang::LambdaExpr::getCallOperator(), clang::LambdaExpr::getCaptureDefault(), clang::LambdaExpr::getCaptureDefaultLoc(), clang::LambdaExpr::getEndLoc(), clang::LambdaExpr::getIntroducerRange(), clang::LambdaExpr::getLambdaClass(), clang::ASTImporter::getToContext(), clang::LambdaExpr::hasExplicitParameters(), clang::LambdaExpr::hasExplicitResultType(), importChecked(), and ImportContainerChecked().
VisitLifetimeExtendedTemporaryDecl()
ExpectedDecl ASTNodeImporter::VisitLifetimeExtendedTemporaryDecl (LifetimeExtendedTemporaryDecl * D)
Definition at line 7844 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::LifetimeExtendedTemporaryDecl::getExtendingDecl(), clang::LifetimeExtendedTemporaryDecl::getManglingNumber(), clang::LifetimeExtendedTemporaryDecl::getTemporaryExpr(), importChecked(), ImportDeclContext(), and clang::Decl::setLexicalDeclContext().
VisitLinkageSpecDecl()
ExpectedDecl ASTNodeImporter::VisitLinkageSpecDecl (LinkageSpecDecl * D)
Definition at line 4825 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::LinkageSpecDecl::getExternLoc(), clang::LinkageSpecDecl::getLanguage(), clang::Decl::getLocation(), clang::LinkageSpecDecl::getRBraceLoc(), clang::ASTImporter::getToContext(), clang::LinkageSpecDecl::hasBraces(), ImportDeclContext(), clang::Decl::setLexicalDeclContext(), and clang::LinkageSpecDecl::setRBraceLoc().
VisitLValueReferenceType()
ExpectedType ASTNodeImporter::VisitLValueReferenceType (const LValueReferenceType * T)
Definition at line 1180 of file ASTImporter.cpp.
References clang::ASTContext::getLValueReferenceType(), and clang::ASTImporter::getToContext().
VisitMaterializeTemporaryExpr()
ExpectedStmt ASTNodeImporter::VisitMaterializeTemporaryExpr (MaterializeTemporaryExpr * E)
Definition at line 7868 of file ASTImporter.cpp.
References clang::cast(), clang::MaterializeTemporaryExpr::getLifetimeExtendedTemporaryDecl(), clang::MaterializeTemporaryExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::MaterializeTemporaryExpr::isBoundToLvalueReference().
VisitMemberExpr()
ExpectedStmt ASTNodeImporter::VisitMemberExpr (MemberExpr * E)
Definition at line 8049 of file ASTImporter.cpp.
References clang::MemberExpr::Create(), clang::DeclAccessPair::getAccess(), clang::MemberExpr::getBase(), clang::DeclAccessPair::getDecl(), clang::MemberExpr::getFoundDecl(), clang::MemberExpr::getLAngleLoc(), clang::DeclarationNameInfo::getLoc(), clang::MemberExpr::getMemberDecl(), clang::MemberExpr::getMemberNameInfo(), clang::DeclarationNameInfo::getName(), clang::Expr::getObjectKind(), clang::MemberExpr::getOperatorLoc(), clang::MemberExpr::getQualifierLoc(), clang::MemberExpr::getRAngleLoc(), clang::MemberExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), clang::MemberExpr::hasExplicitTemplateArgs(), importChecked(), ImportTemplateArgumentListInfo(), clang::MemberExpr::isArrow(), clang::MemberExpr::isNonOdrUse(), clang::DeclAccessPair::make(), and clang::MemberExpr::template_arguments().
VisitMemberPointerType()
ExpectedType ASTNodeImporter::VisitMemberPointerType (const MemberPointerType * T)
Definition at line 1200 of file ASTImporter.cpp.
References clang::ASTContext::getMemberPointerType(), and clang::ASTImporter::getToContext().
VisitNamespaceAliasDecl()
ExpectedDecl ASTNodeImporter::VisitNamespaceAliasDecl (NamespaceAliasDecl * D)
Definition at line 2467 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::NamespaceAliasDecl::getAliasLoc(), clang::NamedDecl::getIdentifier(), clang::NamespaceAliasDecl::getNamespace(), clang::NamespaceAliasDecl::getNamespaceLoc(), clang::NamespaceAliasDecl::getQualifierLoc(), clang::NamespaceAliasDecl::getTargetNameLoc(), clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), importChecked(), ImportDeclParts(), and clang::Decl::setLexicalDeclContext().
VisitNamespaceDecl()
ExpectedDecl ASTNodeImporter::VisitNamespaceDecl (NamespaceDecl * D)
Definition at line 2384 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::cast(), clang::NamespaceDecl::getAnonymousNamespace(), clang::NamespaceDecl::getBeginLoc(), clang::NamespaceDecl::getRBraceLoc(), clang::ASTImporter::getToContext(), clang::ASTImporter::HandleNameConflict(), clang::Decl::IDNS_Namespace, ImportDeclContext(), ImportDeclParts(), clang::Decl::isInIdentifierNamespace(), clang::NamespaceDecl::isInline(), clang::NamespaceDecl::isNested(), clang::ASTImporter::MapImported(), clang::Decl::setLexicalDeclContext(), and clang::NamespaceDecl::setRBraceLoc().
VisitNonTypeTemplateParmDecl()
ExpectedDecl ASTNodeImporter::VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl * D)
Definition at line 5699 of file ASTImporter.cpp.
References clang::NamedDecl::getDeclName(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::NonTypeTemplateParmDecl::getDepth(), clang::DeclaratorDecl::getInnerLocStart(), clang::Decl::getLocation(), clang::NonTypeTemplateParmDecl::getPosition(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), importChecked(), clang::NonTypeTemplateParmDecl::isParameterPack(), and clang::NonTypeTemplateParmDecl::setDefaultArgument().
VisitNullStmt()
ExpectedStmt ASTNodeImporter::VisitNullStmt (NullStmt * S)
Definition at line 6545 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitObjCAtCatchStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAtCatchStmt (ObjCAtCatchStmt * S)
Definition at line 6870 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitObjCAtFinallyStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAtFinallyStmt (ObjCAtFinallyStmt * S)
Definition at line 6884 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitObjCAtSynchronizedStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAtSynchronizedStmt (ObjCAtSynchronizedStmt * S)
Definition at line 6920 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitObjCAtThrowStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAtThrowStmt (ObjCAtThrowStmt * S)
Definition at line 6933 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitObjCAtTryStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAtTryStmt (ObjCAtTryStmt * S)
Definition at line 6895 of file ASTImporter.cpp.
References clang::ObjCAtTryStmt::Create(), clang::ASTImporter::getToContext(), and importChecked().
VisitObjCAutoreleasePoolStmt()
ExpectedStmt ASTNodeImporter::VisitObjCAutoreleasePoolStmt (ObjCAutoreleasePoolStmt * S)
Definition at line 6944 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext().
VisitObjCCategoryDecl()
ExpectedDecl ASTNodeImporter::VisitObjCCategoryDecl (ObjCCategoryDecl * D)
Definition at line 4633 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ObjCInterfaceDecl::FindCategoryDeclaration(), clang::ObjCContainerDecl::getAtStartLoc(), clang::ObjCCategoryDecl::getCategoryNameLoc(), clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCCategoryDecl::getImplementation(), clang::ObjCCategoryDecl::getIvarLBraceLoc(), clang::ObjCCategoryDecl::getIvarRBraceLoc(), clang::ASTImporter::getToContext(), clang::ObjCCategoryDecl::getTypeParamList(), importChecked(), ImportDeclContext(), ImportDeclParts(), ImportObjCTypeParamList(), clang::ASTImporter::MapImported(), clang::ObjCCategoryDecl::protocol_begin(), clang::ObjCCategoryDecl::protocol_end(), clang::ObjCCategoryDecl::protocol_loc_begin(), clang::ObjCCategoryDecl::setImplementation(), clang::Decl::setLexicalDeclContext(), clang::ObjCCategoryDecl::setProtocolList(), and clang::ObjCCategoryDecl::setTypeParamList().
VisitObjCCategoryImplDecl()
ExpectedDecl ASTNodeImporter::VisitObjCCategoryImplDecl (ObjCCategoryImplDecl * D)
Definition at line 5358 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), Category, clang::ObjCContainerDecl::getAtStartLoc(), clang::ObjCCategoryImplDecl::getCategoryDecl(), clang::ObjCCategoryImplDecl::getCategoryNameLoc(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), importChecked(), ImportDeclContext(), clang::ASTImporter::MapImported(), and clang::Decl::setLexicalDeclContext().
VisitObjCForCollectionStmt()
ExpectedStmt ASTNodeImporter::VisitObjCForCollectionStmt (ObjCForCollectionStmt * S)
Definition at line 6853 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and importChecked().
VisitObjCImplementationDecl()
ExpectedDecl ASTNodeImporter::VisitObjCImplementationDecl (ObjCImplementationDecl * D)
Definition at line 5395 of file ASTImporter.cpp.
References clang::declaresSameEntity(), clang::ASTImporter::FromDiag(), clang::ObjCContainerDecl::getAtStartLoc(), clang::ObjCInterfaceDecl::getCanonicalDecl(), clang::ObjCImplDecl::getClassInterface(), clang::NamedDecl::getDeclName(), clang::ObjCInterfaceDecl::getImplementation(), clang::ObjCImplementationDecl::getIvarLBraceLoc(), clang::ObjCImplementationDecl::getIvarRBraceLoc(), clang::Decl::getLocation(), clang::ObjCImplementationDecl::getSuperClass(), clang::ObjCImplementationDecl::getSuperClassLoc(), clang::ASTImporter::getToContext(), importChecked(), ImportDeclContext(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::ObjCInterfaceDecl::setImplementation(), clang::Decl::setLexicalDeclContext(), and clang::ASTImporter::ToDiag().
VisitObjCInterfaceDecl()
ExpectedDecl ASTNodeImporter::VisitObjCInterfaceDecl (ObjCInterfaceDecl * D)
Definition at line 5292 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Definition, clang::ObjCContainerDecl::getAtStartLoc(), clang::ObjCInterfaceDecl::getDefinition(), clang::ASTImporter::getToContext(), clang::ObjCInterfaceDecl::getTypeParamListAsWritten(), clang::Decl::IDNS_Ordinary, ImportDeclParts(), ImportDefinition(), ImportObjCTypeParamList(), clang::ObjCInterfaceDecl::isImplicitInterfaceDecl(), clang::Decl::isInIdentifierNamespace(), clang::ObjCInterfaceDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::Decl::setLexicalDeclContext(), and clang::ObjCInterfaceDecl::setTypeParamList().
VisitObjCInterfaceType()
ExpectedType ASTNodeImporter::VisitObjCInterfaceType (const ObjCInterfaceType * T)
Definition at line 1646 of file ASTImporter.cpp.
References clang::ASTContext::getObjCInterfaceType(), and clang::ASTImporter::getToContext().
VisitObjCIvarDecl()
ExpectedDecl ASTNodeImporter::VisitObjCIvarDecl (ObjCIvarDecl * D)
Definition at line 4163 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ObjCIvarDecl::getAccessControl(), clang::FieldDecl::getBitWidth(), clang::DeclaratorDecl::getInnerLocStart(), clang::ObjCIvarDecl::getSynthesize(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), importChecked(), ImportDeclParts(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::Decl::setLexicalDeclContext(), and clang::ASTImporter::ToDiag().
VisitObjCMethodDecl()
ExpectedDecl ASTNodeImporter::VisitObjCMethodDecl (ObjCMethodDecl * D)
Definition at line 4470 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ObjCMethodDecl::createImplicitParams(), clang::ASTImporter::FromDiag(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCMethodDecl::getEndLoc(), clang::ObjCMethodDecl::getImplementationControl(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getReturnTypeSourceInfo(), clang::ObjCMethodDecl::getSelectorLocs(), clang::ObjCMethodDecl::getSelfDecl(), clang::ASTImporter::getToContext(), clang::ObjCMethodDecl::hasRelatedResultType(), importChecked(), ImportContainerChecked(), ImportDeclParts(), clang::ObjCMethodDecl::isDefined(), clang::Decl::isImplicit(), clang::ObjCMethodDecl::isInstanceMethod(), clang::ObjCMethodDecl::isPropertyAccessor(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::ObjCMethodDecl::isVariadic(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >::P, clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), clang::ObjCMethodDecl::param_size(), clang::ObjCMethodDecl::parameters(), clang::Decl::setLexicalDeclContext(), clang::ObjCMethodDecl::setMethodParams(), and clang::ASTImporter::ToDiag().
VisitObjCObjectPointerType()
ExpectedType ASTNodeImporter::VisitObjCObjectPointerType (const ObjCObjectPointerType * T)
Definition at line 1682 of file ASTImporter.cpp.
References clang::ASTContext::getObjCObjectPointerType(), and clang::ASTImporter::getToContext().
VisitObjCObjectType()
ExpectedType ASTNodeImporter::VisitObjCObjectType (const ObjCObjectType * T)
Definition at line 1654 of file ASTImporter.cpp.
References clang::ASTContext::getObjCObjectType(), clang::ASTImporter::getToContext(), and clang::StmtVisitorBase< std::add_pointer, ASTNodeImporter, ExpectedStmt, ParamTys... >::P.
VisitObjCPropertyDecl()
ExpectedDecl ASTNodeImporter::VisitObjCPropertyDecl (ObjCPropertyDecl * D)
Definition at line 5477 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ObjCPropertyDecl::getAtLoc(), clang::ObjCPropertyDecl::getGetterMethodDecl(), clang::ObjCPropertyDecl::getGetterName(), clang::ObjCPropertyDecl::getGetterNameLoc(), clang::ObjCPropertyDecl::getLParenLoc(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyDecl::getPropertyAttributesAsWritten(), clang::ObjCPropertyDecl::getPropertyImplementation(), clang::ObjCPropertyDecl::getPropertyIvarDecl(), clang::ObjCPropertyDecl::getSetterMethodDecl(), clang::ObjCPropertyDecl::getSetterName(), clang::ObjCPropertyDecl::getSetterNameLoc(), clang::ASTImporter::getToContext(), clang::ObjCPropertyDecl::getType(), clang::ObjCPropertyDecl::getTypeSourceInfo(), importChecked(), ImportDeclParts(), clang::ObjCPropertyDecl::isInstanceProperty(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::ObjCPropertyDecl::setGetterMethodDecl(), clang::ObjCPropertyDecl::setGetterName(), clang::Decl::setLexicalDeclContext(), clang::ObjCPropertyDecl::setPropertyAttributes(), clang::ObjCPropertyDecl::setPropertyAttributesAsWritten(), clang::ObjCPropertyDecl::setPropertyIvarDecl(), clang::ObjCPropertyDecl::setSetterMethodDecl(), clang::ObjCPropertyDecl::setSetterName(), and clang::ASTImporter::ToDiag().
VisitObjCPropertyImplDecl()
ExpectedDecl ASTNodeImporter::VisitObjCPropertyImplDecl (ObjCPropertyImplDecl * D)
Definition at line 5558 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::cast(), clang::ObjCPropertyImplDecl::Dynamic, clang::ASTImporter::FromDiag(), clang::ObjCPropertyImplDecl::getBeginLoc(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyImplementation(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::ObjCPropertyImplDecl::getPropertyIvarDeclLoc(), clang::ASTImporter::getToContext(), importChecked(), ImportDeclContext(), clang::ASTImporter::MapImported(), clang::ASTImportError::NameConflict, clang::Property, clang::Decl::setLexicalDeclContext(), clang::ObjCPropertyImplDecl::Synthesize, and clang::ASTImporter::ToDiag().
VisitObjCProtocolDecl()
ExpectedDecl ASTNodeImporter::VisitObjCProtocolDecl (ObjCProtocolDecl * D)
Definition at line 4769 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Definition, clang::ObjCContainerDecl::getAtStartLoc(), clang::ObjCProtocolDecl::getDefinition(), clang::ASTImporter::getToContext(), clang::Decl::IDNS_ObjCProtocol, ImportDeclParts(), ImportDefinition(), clang::Decl::isInIdentifierNamespace(), clang::ObjCProtocolDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), and clang::Decl::setLexicalDeclContext().
VisitObjCTypeParamDecl()
ExpectedDecl ASTNodeImporter::VisitObjCTypeParamDecl (ObjCTypeParamDecl * D)
Definition at line 4602 of file ASTImporter.cpp.
References clang::ObjCTypeParamDecl::getColonLoc(), clang::ObjCTypeParamDecl::getIndex(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::TypedefNameDecl::getTypeSourceInfo(), clang::ObjCTypeParamDecl::getVariance(), clang::ObjCTypeParamDecl::getVarianceLoc(), importChecked(), ImportDeclParts(), clang::Result, and clang::Decl::setLexicalDeclContext().
VisitOffsetOfExpr()
ExpectedStmt ASTNodeImporter::VisitOffsetOfExpr (OffsetOfExpr * OE)
Definition at line 7660 of file ASTImporter.cpp.
References clang::OffsetOfNode::Array, clang::OffsetOfNode::Base, clang::OffsetOfExpr::Create(), clang::OffsetOfNode::Field, clang::OffsetOfNode::getArrayExprIndex(), clang::OffsetOfNode::getBase(), clang::OffsetOfNode::getBeginLoc(), clang::OffsetOfExpr::getComponent(), clang::OffsetOfNode::getEndLoc(), clang::OffsetOfNode::getField(), clang::OffsetOfNode::getFieldName(), clang::OffsetOfExpr::getIndexExpr(), clang::OffsetOfNode::getKind(), clang::OffsetOfExpr::getNumComponents(), clang::OffsetOfExpr::getNumExpressions(), clang::OffsetOfExpr::getOperatorLoc(), clang::OffsetOfExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::OffsetOfExpr::getTypeSourceInfo(), clang::OffsetOfNode::Identifier, clang::ASTImporter::Import(), importChecked(), and N.
VisitOpaqueValueExpr()
ExpectedStmt ASTNodeImporter::VisitOpaqueValueExpr (OpaqueValueExpr * E)
Definition at line 7524 of file ASTImporter.cpp.
References clang::OpaqueValueExpr::getLocation(), clang::Expr::getObjectKind(), clang::OpaqueValueExpr::getSourceExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitPackExpansionExpr()
ExpectedStmt ASTNodeImporter::VisitPackExpansionExpr (PackExpansionExpr * E)
Definition at line 7888 of file ASTImporter.cpp.
References clang::PackExpansionExpr::getEllipsisLoc(), clang::PackExpansionExpr::getNumExpansions(), clang::PackExpansionExpr::getPattern(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and importChecked().
VisitPackExpansionType()
ExpectedType ASTNodeImporter::VisitPackExpansionType (const PackExpansionType * T)
Definition at line 1597 of file ASTImporter.cpp.
References clang::ASTContext::getPackExpansionType(), and clang::ASTImporter::getToContext().
VisitParenExpr()
ExpectedStmt ASTNodeImporter::VisitParenExpr (ParenExpr * E)
Definition at line 7346 of file ASTImporter.cpp.
References clang::ParenExpr::getLParen(), clang::ParenExpr::getRParen(), clang::ParenExpr::getSubExpr(), clang::ASTImporter::getToContext(), and importChecked().
VisitParenListExpr()
ExpectedStmt ASTNodeImporter::VisitParenListExpr (ParenListExpr * E)
Definition at line 7358 of file ASTImporter.cpp.
References clang::ParenListExpr::Create(), clang::ParenListExpr::exprs(), clang::ParenListExpr::getLParenLoc(), clang::ParenListExpr::getNumExprs(), clang::ParenListExpr::getRParenLoc(), clang::ASTImporter::getToContext(), and ImportContainerChecked().
VisitParenType()
ExpectedType ASTNodeImporter::VisitParenType (const ParenType * T)
Definition at line 1358 of file ASTImporter.cpp.
References clang::ASTContext::getParenType(), and clang::ASTImporter::getToContext().
VisitParmVarDecl()
ExpectedDecl ASTNodeImporter::VisitParmVarDecl (ParmVarDecl * D)
Definition at line 4431 of file ASTImporter.cpp.
References clang::NamedDecl::getDeclName(), clang::ParmVarDecl::getFunctionScopeDepth(), clang::ParmVarDecl::getFunctionScopeIndex(), clang::DeclaratorDecl::getInnerLocStart(), clang::Decl::getLocation(), clang::ParmVarDecl::getObjCDeclQualifier(), clang::VarDecl::getStorageClass(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), importChecked(), ImportDefaultArgOfParmVarDecl(), clang::ParmVarDecl::isObjCMethodParameter(), clang::ParmVarDecl::setObjCDeclQualifier(), clang::ParmVarDecl::setObjCMethodScopeInfo(), and clang::ParmVarDecl::setScopeInfo().
VisitPointerType()
ExpectedType ASTNodeImporter::VisitPointerType (const PointerType * T)
Definition at line 1162 of file ASTImporter.cpp.
References clang::ASTContext::getPointerType(), and clang::ASTImporter::getToContext().
VisitPredefinedExpr()
ExpectedStmt ASTNodeImporter::VisitPredefinedExpr (PredefinedExpr * E)
Definition at line 7104 of file ASTImporter.cpp.
References clang::PredefinedExpr::Create(), clang::PredefinedExpr::getBeginLoc(), clang::PredefinedExpr::getFunctionName(), clang::PredefinedExpr::getIdentKind(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::PredefinedExpr::isTransparent().
VisitRecordDecl()
ExpectedDecl ASTNodeImporter::VisitRecordDecl (RecordDecl * D)
Definition at line 2830 of file ASTImporter.cpp.
References clang::cast(), clang::ExternalASTSource::CompleteType(), clang::CXXRecordDecl::LambdaNumbering::ContextDecl, clang::CXXRecordDecl::CreateLambda(), clang::Decl::FOK_None, clang::Decl::getAccess(), clang::Type::getAs(), clang::Decl::getASTContext(), clang::TypeDecl::getBeginLoc(), clang::TagDecl::getBraceRange(), clang::getCanonicalForwardRedeclChain(), clang::NamedDecl::getDeclName(), clang::RecordDecl::getDefinition(), clang::ASTContext::getExternalSource(), clang::ClassTemplateDecl::getInjectedClassNameSpecialization(), clang::ASTContext::getInjectedClassNameType(), clang::CXXRecordDecl::getInstantiatedFromMemberClass(), clang::ASTContext::getLangOpts(), clang::CXXRecordDecl::getMemberSpecializationInfo(), clang::RecordDecl::getMostRecentDecl(), clang::TagDecl::getQualifierLoc(), clang::TagDecl::getTagKind(), clang::ASTImporter::getToContext(), clang::ASTContext::getTypeDeclType(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::ASTImporter::HandleNameConflict(), clang::DeclContext::hasExternalLexicalStorage(), hasSameVisibilityContextAndLinkage(), IDK_Default, clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_Tag, clang::Decl::IDNS_TagFriend, ImportDeclParts(), ImportDefinition(), ImportImplicitMethods(), clang::RecordDecl::isAnonymousStructOrUnion(), clang::TagDecl::isCompleteDefinition(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), clang::RecordDecl::isLambda(), clang::ASTImporter::isMinimalImport(), IsStructuralMatch(), clang::TagDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::DeclContext::noload_lookup(), clang::Decl::setAccess(), clang::RecordDecl::setAnonymousStructOrUnion(), clang::TagDecl::setBraceRange(), clang::CXXRecordDecl::setDescribedClassTemplate(), clang::CXXRecordDecl::setInstantiationOfMemberClass(), clang::CXXRecordDecl::setLambdaNumbering(), clang::Decl::setLexicalDeclContext(), clang::MemberSpecializationInfo::setPointOfInstantiation(), clang::TagDecl::setQualifierInfo(), and clang::TypeDecl::setTypeForDecl().
VisitRecordType()
ExpectedType ASTNodeImporter::VisitRecordType (const RecordType * T)
Definition at line 1484 of file ASTImporter.cpp.
References clang::ASTContext::getTagDeclType(), and clang::ASTImporter::getToContext().
VisitReturnStmt()
ExpectedStmt ASTNodeImporter::VisitReturnStmt (ReturnStmt * S)
Definition at line 6781 of file ASTImporter.cpp.
References clang::ReturnStmt::Create(), clang::ASTImporter::getToContext(), and importChecked().
VisitRValueReferenceType()
ExpectedType ASTNodeImporter::VisitRValueReferenceType (const RValueReferenceType * T)
Definition at line 1190 of file ASTImporter.cpp.
References clang::ASTContext::getRValueReferenceType(), and clang::ASTImporter::getToContext().
VisitShuffleVectorExpr()
ExpectedStmt ASTNodeImporter::VisitShuffleVectorExpr (ShuffleVectorExpr * E)
Definition at line 7021 of file ASTImporter.cpp.
References clang::ShuffleVectorExpr::getBeginLoc(), clang::ShuffleVectorExpr::getNumSubExprs(), clang::ShuffleVectorExpr::getRParenLoc(), clang::ShuffleVectorExpr::getSubExprs(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and ImportContainerChecked().
VisitSizeOfPackExpr()
ExpectedStmt ASTNodeImporter::VisitSizeOfPackExpr (SizeOfPackExpr * E)
Definition at line 7900 of file ASTImporter.cpp.
References clang::SizeOfPackExpr::Create(), clang::SizeOfPackExpr::getOperatorLoc(), clang::SizeOfPackExpr::getPack(), clang::SizeOfPackExpr::getPackLength(), clang::SizeOfPackExpr::getPackLoc(), clang::SizeOfPackExpr::getPartialArguments(), clang::SizeOfPackExpr::getRParenLoc(), clang::ASTImporter::getToContext(), importChecked(), ImportTemplateArguments(), clang::SizeOfPackExpr::isPartiallySubstituted(), and clang::Expr::isValueDependent().
VisitSourceLocExpr()
ExpectedStmt ASTNodeImporter::VisitSourceLocExpr (SourceLocExpr * E)
Definition at line 6965 of file ASTImporter.cpp.
References clang::SourceLocExpr::getBeginLoc(), clang::SourceLocExpr::getEndLoc(), clang::SourceLocExpr::getIdentKind(), clang::SourceLocExpr::getParentContext(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::ASTImporter::ImportContext().
VisitStaticAssertDecl()
ExpectedDecl ASTNodeImporter::VisitStaticAssertDecl (StaticAssertDecl * D)
Definition at line 2358 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::StaticAssertDecl::getAssertExpr(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::StaticAssertDecl::getMessage(), clang::StaticAssertDecl::getRParenLoc(), clang::ASTImporter::getToContext(), importChecked(), clang::ASTImporter::ImportContext(), clang::StaticAssertDecl::isFailed(), and clang::Decl::setLexicalDeclContext().
VisitStmt()
ExpectedStmt ASTNodeImporter::VisitStmt (Stmt * S)
Definition at line 6445 of file ASTImporter.cpp.
References clang::ASTImporter::FromDiag(), and clang::ASTImportError::UnsupportedConstruct.
VisitStmtExpr()
ExpectedStmt ASTNodeImporter::VisitStmtExpr (StmtExpr * E)
Definition at line 7375 of file ASTImporter.cpp.
References clang::StmtExpr::getLParenLoc(), clang::StmtExpr::getRParenLoc(), clang::StmtExpr::getSubStmt(), clang::StmtExpr::getTemplateDepth(), clang::ASTImporter::getToContext(), clang::Expr::getType(), and importChecked().
VisitStringLiteral()
ExpectedStmt ASTNodeImporter::VisitStringLiteral (StringLiteral * E)
Definition at line 7275 of file ASTImporter.cpp.
References clang::StringLiteral::Create(), clang::StringLiteral::getBytes(), clang::StringLiteral::getKind(), clang::StringLiteral::getNumConcatenated(), clang::ASTImporter::getToContext(), clang::Expr::getType(), ImportArrayChecked(), clang::StringLiteral::isPascal(), clang::StringLiteral::tokloc_begin(), and clang::StringLiteral::tokloc_end().
VisitSubstNonTypeTemplateParmExpr()
ExpectedStmt ASTNodeImporter::VisitSubstNonTypeTemplateParmExpr (SubstNonTypeTemplateParmExpr * E)
Definition at line 8537 of file ASTImporter.cpp.
References clang::SubstNonTypeTemplateParmExpr::getAssociatedDecl(), clang::Expr::getExprLoc(), clang::SubstNonTypeTemplateParmExpr::getIndex(), clang::SubstNonTypeTemplateParmExpr::getPackIndex(), clang::SubstNonTypeTemplateParmExpr::getReplacement(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), importChecked(), and clang::SubstNonTypeTemplateParmExpr::isReferenceParameter().
VisitSubstTemplateTypeParmPackType()
ExpectedType ASTNodeImporter::VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType * T)
Definition at line 1537 of file ASTImporter.cpp.
References clang::ASTContext::getSubstTemplateTypeParmPackType(), and clang::ASTImporter::getToContext().
VisitSubstTemplateTypeParmType()
ExpectedType ASTNodeImporter::VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType * T)
Definition at line 1522 of file ASTImporter.cpp.
References clang::ASTContext::getSubstTemplateTypeParmType(), and clang::ASTImporter::getToContext().
VisitSwitchStmt()
ExpectedStmt ASTNodeImporter::VisitSwitchStmt (SwitchStmt * S)
Definition at line 6654 of file ASTImporter.cpp.
References clang::SwitchStmt::Create(), clang::ASTImporter::getToContext(), importChecked(), and clang::SwitchCase::setNextSwitchCase().
VisitTemplateSpecializationType()
ExpectedType ASTNodeImporter::VisitTemplateSpecializationType (const TemplateSpecializationType * T)
Definition at line 1551 of file ASTImporter.cpp.
References clang::ASTContext::getCanonicalType(), clang::ASTImporter::getFromContext(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTImporter::getToContext(), and ImportTemplateArguments().
VisitTemplateTemplateParmDecl()
ExpectedDecl ASTNodeImporter::VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl * D)
Definition at line 5730 of file ASTImporter.cpp.
References clang::NamedDecl::getDeclName(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::TemplateTemplateParmDecl::getDepth(), clang::Decl::getLocation(), clang::TemplateTemplateParmDecl::getPosition(), clang::TemplateDecl::getTemplateParameters(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), clang::TemplateTemplateParmDecl::isParameterPack(), and clang::TemplateTemplateParmDecl::setDefaultArgument().
VisitTemplateTypeParmDecl()
ExpectedDecl ASTNodeImporter::VisitTemplateTypeParmDecl (TemplateTypeParmDecl * D)
Definition at line 5636 of file ASTImporter.cpp.
References clang::ASTTemplateArgumentListInfo::Create(), clang::TypeDecl::getBeginLoc(), clang::TemplateTypeParmDecl::getDefaultArgumentInfo(), clang::TemplateTypeParmDecl::getDepth(), clang::NamedDecl::getIdentifier(), clang::TemplateTypeParmDecl::getIndex(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::TemplateTypeParmDecl::getTypeConstraint(), clang::TemplateTypeParmDecl::hasDefaultArgument(), clang::TemplateTypeParmDecl::hasTypeConstraint(), clang::ASTImporter::Import(), importChecked(), ImportTemplateArgumentListInfo(), clang::TemplateTypeParmDecl::isParameterPack(), clang::TemplateTypeParmDecl::setDefaultArgument(), clang::TemplateTypeParmDecl::setTypeConstraint(), and clang::TemplateTypeParmDecl::wasDeclaredWithTypename().
VisitTemplateTypeParmType()
ExpectedType ASTNodeImporter::VisitTemplateTypeParmType (const TemplateTypeParmType * T)
Definition at line 1512 of file ASTImporter.cpp.
References clang::ASTContext::getTemplateTypeParmType(), and clang::ASTImporter::getToContext().
VisitTranslationUnitDecl()
ExpectedDecl ASTNodeImporter::VisitTranslationUnitDecl (TranslationUnitDecl * D)
Definition at line 2293 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), and clang::ASTImporter::MapImported().
VisitType()
ExpectedType ASTNodeImporter::VisitType (const Type * T)
Definition at line 1067 of file ASTImporter.cpp.
References clang::ASTImporter::FromDiag(), and clang::ASTImportError::UnsupportedConstruct.
VisitTypeAliasDecl()
ExpectedDecl ASTNodeImporter::VisitTypeAliasDecl (TypeAliasDecl * D)
Definition at line 2623 of file ASTImporter.cpp.
References VisitTypedefNameDecl().
VisitTypeAliasTemplateDecl()
ExpectedDecl ASTNodeImporter::VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl * D)
Definition at line 2628 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::TypeAliasTemplateDecl::getTemplatedDecl(), clang::TemplateDecl::getTemplateParameters(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTImporter::HandleNameConflict(), clang::Decl::IDNS_Ordinary, importChecked(), ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), and clang::Decl::setLexicalDeclContext().
VisitTypedefDecl()
ExpectedDecl ASTNodeImporter::VisitTypedefDecl (TypedefDecl * D)
Definition at line 2619 of file ASTImporter.cpp.
References VisitTypedefNameDecl().
VisitTypedefNameDecl()
ExpectedDecl ASTNodeImporter::VisitTypedefNameDecl (TypedefNameDecl * D, bool IsAlias)
Definition at line 2504 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::cast(), clang::Decl::getAccess(), clang::ASTImporter::GetAlreadyImportedOrNull(), clang::Type::getAsRecordDecl(), clang::TypeDecl::getBeginLoc(), clang::Decl::getDeclContext(), clang::TypeAliasDecl::getDescribedAliasTemplate(), clang::Decl::getLexicalDeclContext(), clang::ASTImporter::getToContext(), clang::TypedefNameDecl::getTypeSourceInfo(), clang::TypedefNameDecl::getUnderlyingType(), clang::ASTImporter::HandleNameConflict(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, importChecked(), ImportDeclContext(), ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Type::isIncompleteType(), clang::Decl::isInIdentifierNamespace(), clang::QualType::isNull(), clang::ASTImporter::IsStructurallyEquivalent(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::Decl::setDeclContext(), clang::Decl::setLexicalDeclContext(), and ToUnderlyingType.
Referenced by VisitTypeAliasDecl(), and VisitTypedefDecl().
VisitTypedefType()
ExpectedType ASTNodeImporter::VisitTypedefType (const TypedefType * T)
Definition at line 1366 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTContext::getTypedefType(), and clang::TypeDecl::getTypeForDecl().
VisitTypeOfExprType()
ExpectedType ASTNodeImporter::VisitTypeOfExprType (const TypeOfExprType * T)
Definition at line 1382 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::ASTContext::getTypeOfExprType().
VisitTypeOfType()
ExpectedType ASTNodeImporter::VisitTypeOfType (const TypeOfType * T)
Definition at line 1389 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::ASTContext::getTypeOfType().
VisitTypeTraitExpr()
ExpectedStmt ASTNodeImporter::VisitTypeTraitExpr (TypeTraitExpr * E)
Definition at line 8552 of file ASTImporter.cpp.
References clang::TypeTraitExpr::Create(), clang::TypeTraitExpr::getArgs(), clang::TypeTraitExpr::getBeginLoc(), clang::TypeTraitExpr::getEndLoc(), clang::TypeTraitExpr::getNumArgs(), clang::ASTImporter::getToContext(), clang::TypeTraitExpr::getTrait(), clang::Expr::getType(), clang::TypeTraitExpr::getValue(), importChecked(), ImportContainerChecked(), and clang::Expr::isValueDependent().
VisitUnaryExprOrTypeTraitExpr()
ExpectedStmt ASTNodeImporter::VisitUnaryExprOrTypeTraitExpr (UnaryExprOrTypeTraitExpr * E)
Definition at line 7405 of file ASTImporter.cpp.
References clang::UnaryExprOrTypeTraitExpr::getArgumentExpr(), clang::UnaryExprOrTypeTraitExpr::getArgumentTypeInfo(), clang::UnaryExprOrTypeTraitExpr::getKind(), clang::UnaryExprOrTypeTraitExpr::getOperatorLoc(), clang::UnaryExprOrTypeTraitExpr::getRParenLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), importChecked(), and clang::UnaryExprOrTypeTraitExpr::isArgumentType().
VisitUnaryOperator()
ExpectedStmt ASTNodeImporter::VisitUnaryOperator (UnaryOperator * E)
Definition at line 7389 of file ASTImporter.cpp.
References clang::UnaryOperator::canOverflow(), clang::UnaryOperator::Create(), clang::UnaryOperator::getFPOptionsOverride(), clang::Expr::getObjectKind(), clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getOperatorLoc(), clang::UnaryOperator::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::Expr::getValueKind(), and importChecked().
VisitUnaryTransformType()
ExpectedType ASTNodeImporter::VisitUnaryTransformType (const UnaryTransformType * T)
Definition at line 1423 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::ASTContext::getUnaryTransformType().
VisitUnresolvedLookupExpr()
ExpectedStmt ASTNodeImporter::VisitUnresolvedLookupExpr (UnresolvedLookupExpr * E)
Definition at line 8212 of file ASTImporter.cpp.
References clang::UnresolvedSetImpl::addDecl(), clang::UnresolvedSetImpl::begin(), clang::UnresolvedLookupExpr::Create(), clang::OverloadExpr::decls(), clang::UnresolvedSetImpl::end(), clang::OverloadExpr::getLAngleLoc(), clang::OverloadExpr::getName(), clang::OverloadExpr::getNameInfo(), clang::OverloadExpr::getNameLoc(), clang::UnresolvedLookupExpr::getNamingClass(), clang::OverloadExpr::getQualifierLoc(), clang::OverloadExpr::getRAngleLoc(), clang::OverloadExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::OverloadExpr::hasExplicitTemplateArgs(), importChecked(), ImportDeclarationNameLoc(), ImportTemplateArgumentListInfo(), clang::UnresolvedLookupExpr::isOverloaded(), clang::UnresolvedLookupExpr::requiresADL(), and clang::OverloadExpr::template_arguments().
VisitUnresolvedMemberExpr()
ExpectedStmt ASTNodeImporter::VisitUnresolvedMemberExpr (UnresolvedMemberExpr * E)
Definition at line 8263 of file ASTImporter.cpp.
References clang::UnresolvedSetImpl::addDecl(), clang::UnresolvedSetImpl::begin(), clang::OverloadExpr::copyTemplateArgumentsInto(), clang::UnresolvedMemberExpr::Create(), clang::OverloadExpr::decls(), clang::UnresolvedSetImpl::end(), clang::UnresolvedMemberExpr::getBase(), clang::OverloadExpr::getName(), clang::OverloadExpr::getNameInfo(), clang::OverloadExpr::getNameLoc(), clang::UnresolvedMemberExpr::getOperatorLoc(), clang::OverloadExpr::getQualifierLoc(), clang::OverloadExpr::getTemplateKeywordLoc(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::OverloadExpr::hasExplicitTemplateArgs(), clang::UnresolvedMemberExpr::hasUnresolvedUsing(), importChecked(), ImportDeclarationNameLoc(), ImportTemplateArgumentListInfo(), clang::UnresolvedMemberExpr::isArrow(), and clang::UnresolvedMemberExpr::isImplicitAccess().
VisitUnresolvedUsingType()
ExpectedType ASTNodeImporter::VisitUnresolvedUsingType (const UnresolvedUsingType * T)
Definition at line 1346 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTContext::getTypeDeclType(), and importChecked().
VisitUnresolvedUsingTypenameDecl()
ExpectedDecl ASTNodeImporter::VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl * D)
Definition at line 5118 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::UnresolvedUsingTypenameDecl::getEllipsisLoc(), clang::UnresolvedUsingTypenameDecl::getQualifierLoc(), clang::ASTImporter::getToContext(), clang::UnresolvedUsingTypenameDecl::getTypenameLoc(), clang::UnresolvedUsingTypenameDecl::getUsingLoc(), importChecked(), ImportDeclParts(), clang::Decl::setAccess(), and clang::Decl::setLexicalDeclContext().
VisitUnresolvedUsingValueDecl()
ExpectedDecl ASTNodeImporter::VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl * D)
Definition at line 5082 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::UnresolvedUsingValueDecl::getEllipsisLoc(), clang::DeclarationNameInfo::getLoc(), clang::UnresolvedUsingValueDecl::getNameInfo(), clang::UnresolvedUsingValueDecl::getQualifierLoc(), clang::ASTImporter::getToContext(), clang::UnresolvedUsingValueDecl::getUsingLoc(), importChecked(), ImportDeclarationNameLoc(), ImportDeclParts(), clang::Decl::setAccess(), and clang::Decl::setLexicalDeclContext().
VisitUsingDecl()
ExpectedDecl ASTNodeImporter::VisitUsingDecl (UsingDecl * D)
Definition at line 4872 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::ASTImporter::getFromContext(), clang::ASTContext::getInstantiatedFromUsingDecl(), clang::DeclarationNameInfo::getLoc(), clang::UsingDecl::getNameInfo(), clang::UsingDecl::getQualifierLoc(), clang::ASTImporter::getToContext(), clang::UsingDecl::getUsingLoc(), clang::UsingDecl::hasTypename(), importChecked(), ImportDeclarationNameLoc(), ImportDeclParts(), ImportUsingShadowDecls(), clang::ASTContext::setInstantiatedFromUsingDecl(), and clang::Decl::setLexicalDeclContext().
VisitUsingDirectiveDecl()
ExpectedDecl ASTNodeImporter::VisitUsingDirectiveDecl (UsingDirectiveDecl * D)
Definition at line 5014 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::UsingDirectiveDecl::getCommonAncestor(), clang::UsingDirectiveDecl::getIdentLocation(), clang::UsingDirectiveDecl::getNamespaceKeyLocation(), clang::UsingDirectiveDecl::getNominatedNamespace(), clang::UsingDirectiveDecl::getQualifierLoc(), clang::ASTImporter::getToContext(), clang::UsingDirectiveDecl::getUsingLoc(), importChecked(), clang::ASTImporter::ImportContext(), ImportDeclParts(), and clang::Decl::setLexicalDeclContext().
VisitUsingEnumDecl()
ExpectedDecl ASTNodeImporter::VisitUsingEnumDecl (UsingEnumDecl * D)
Definition at line 4914 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::UsingEnumDecl::getEnumLoc(), clang::UsingEnumDecl::getEnumType(), clang::ASTImporter::getFromContext(), clang::ASTContext::getInstantiatedFromUsingEnumDecl(), clang::Decl::getLocation(), clang::ASTImporter::getToContext(), clang::UsingEnumDecl::getUsingLoc(), importChecked(), ImportDeclParts(), ImportUsingShadowDecls(), clang::ASTContext::setInstantiatedFromUsingEnumDecl(), and clang::Decl::setLexicalDeclContext().
VisitUsingPackDecl()
ExpectedDecl ASTNodeImporter::VisitUsingPackDecl (UsingPackDecl * D)
Definition at line 5053 of file ASTImporter.cpp.
References clang::UsingPackDecl::expansions(), clang::UsingPackDecl::getInstantiatedFromUsingDecl(), clang::ASTImporter::getToContext(), clang::ASTImporter::Import(), ImportArrayChecked(), and ImportDeclParts().
VisitUsingShadowDecl()
ExpectedDecl ASTNodeImporter::VisitUsingShadowDecl (UsingShadowDecl * D)
Definition at line 4952 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::ASTImporter::getFromContext(), clang::ASTContext::getInstantiatedFromUsingShadowDecl(), clang::UsingShadowDecl::getIntroducer(), clang::UsingShadowDecl::getTargetDecl(), clang::ASTImporter::getToContext(), importChecked(), ImportDeclParts(), clang::Decl::setAccess(), clang::ASTContext::setInstantiatedFromUsingShadowDecl(), and clang::Decl::setLexicalDeclContext().
VisitUsingType()
ExpectedType ASTNodeImporter::VisitUsingType (const UsingType * T)
Definition at line 1397 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::ASTContext::getUsingType().
VisitVAArgExpr()
ExpectedStmt ASTNodeImporter::VisitVAArgExpr (VAArgExpr * E)
Definition at line 6981 of file ASTImporter.cpp.
References clang::VAArgExpr::getBuiltinLoc(), clang::VAArgExpr::getRParenLoc(), clang::VAArgExpr::getSubExpr(), clang::ASTImporter::getToContext(), clang::Expr::getType(), clang::VAArgExpr::getWrittenTypeInfo(), importChecked(), and clang::VAArgExpr::isMicrosoftABI().
VisitVarDecl()
ExpectedDecl ASTNodeImporter::VisitVarDecl (VarDecl * D)
Definition at line 4214 of file ASTImporter.cpp.
References clang::Decl::getAccess(), clang::ASTContext::getAsArrayType(), clang::getCanonicalForwardRedeclChain(), clang::VarDecl::getDefinition(), clang::VarDecl::getDescribedVarTemplate(), clang::VarDecl::getInit(), clang::DeclaratorDecl::getInnerLocStart(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::DeclaratorDecl::getQualifierLoc(), clang::VarDecl::getStorageClass(), clang::ASTImporter::getToContext(), clang::VarDecl::getTSCSpec(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTImporter::HandleNameConflict(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, ImportArrayChecked(), importChecked(), ImportDeclParts(), ImportInitializer(), clang::VarDecl::isConstexpr(), clang::VarDecl::isFileVarDecl(), clang::Decl::isInIdentifierNamespace(), clang::ASTImporter::IsStructurallyEquivalent(), clang::VarDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::VarDecl::setConstexpr(), clang::Decl::setLexicalDeclContext(), clang::Redeclarable< decl_type >::setPreviousDecl(), clang::DeclaratorDecl::setQualifierInfo(), clang::VarDecl::setTSCSpec(), and clang::ASTImporter::ToDiag().
VisitVariableArrayType()
ExpectedType ASTNodeImporter::VisitVariableArrayType (const VariableArrayType * T)
Definition at line 1239 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), clang::ASTContext::getVariableArrayType(), and importChecked().
VisitVarTemplateDecl()
ExpectedDecl ASTNodeImporter::VisitVarTemplateDecl (VarTemplateDecl * D)
Definition at line 6086 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::Decl::getAccess(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::VarTemplateDecl::getMostRecentDecl(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::VarTemplateDecl::getTemplatedDecl(), getTemplateDefinition(), clang::TemplateDecl::getTemplateParameters(), clang::ASTImporter::getToContext(), clang::ASTContext::getTranslationUnitDecl(), clang::ValueDecl::getType(), clang::ASTImporter::HandleNameConflict(), hasSameVisibilityContextAndLinkage(), clang::Decl::IDNS_Ordinary, ImportDeclParts(), clang::DeclContext::isFunctionOrMethod(), clang::Decl::isInIdentifierNamespace(), IsStructuralMatch(), clang::VarTemplateDecl::isThisDeclarationADefinition(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::VarDecl::setDescribedVarTemplate(), clang::Decl::setLexicalDeclContext(), and clang::Redeclarable< decl_type >::setPreviousDecl().
VisitVarTemplateSpecializationDecl()
ExpectedDecl ASTNodeImporter::VisitVarTemplateSpecializationDecl (VarTemplateSpecializationDecl * D)
Definition at line 6185 of file ASTImporter.cpp.
References clang::DeclContext::addDeclInternal(), clang::VarTemplateDecl::AddSpecialization(), clang::TemplateArgumentList::asArray(), clang::Definition, clang::VarTemplateDecl::findSpecialization(), clang::Decl::getAccess(), clang::DeclaratorDecl::getBeginLoc(), clang::VarDecl::getDefinition(), clang::Decl::getLocation(), clang::VarTemplateSpecializationDecl::getPointOfInstantiation(), clang::DeclaratorDecl::getQualifierLoc(), clang::VarTemplateSpecializationDecl::getSpecializationKind(), clang::VarTemplateSpecializationDecl::getSpecializedTemplate(), clang::VarDecl::getStorageClass(), clang::VarTemplateSpecializationDecl::getTemplateArgs(), clang::VarTemplateSpecializationDecl::getTemplateArgsInfo(), clang::ASTImporter::getToContext(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), ImportDeclContext(), ImportInitializer(), ImportTemplateArgumentListInfo(), ImportTemplateArguments(), clang::VarDecl::isConstexpr(), IsStructuralMatch(), clang::VarDecl::isThisDeclarationADefinition(), clang::SourceLocation::isValid(), clang::ASTImporter::MapImported(), clang::Decl::setAccess(), clang::VarDecl::setConstexpr(), clang::Decl::setLexicalDeclContext(), clang::VarTemplateSpecializationDecl::setPointOfInstantiation(), clang::DeclaratorDecl::setQualifierInfo(), clang::VarTemplateSpecializationDecl::setSpecializationKind(), clang::VarTemplateSpecializationDecl::setTemplateArgsInfo(), clang::ValueDecl::setType(), and clang::DeclaratorDecl::setTypeSourceInfo().
VisitVectorType()
ExpectedType ASTNodeImporter::VisitVectorType (const VectorType * T)
Definition at line 1267 of file ASTImporter.cpp.
References clang::ASTImporter::getToContext(), and clang::ASTContext::getVectorType().
VisitWhileStmt()
ExpectedStmt ASTNodeImporter::VisitWhileStmt (WhileStmt * S)
Definition at line 6690 of file ASTImporter.cpp.
References clang::WhileStmt::Create(), clang::ASTImporter::getToContext(), and importChecked().
The documentation for this class was generated from the following file:
lib/AST/ASTImporter.cpp