clang: clang::dataflow::StmtToEnvMap Class Reference
clang::dataflow::StmtToEnvMap Class Reference
Maps statements to the environments of basic blocks that contain them.
#include "clang/Analysis/FlowSensitive/Transfer.h"
Public Member Functions
StmtToEnvMap (const ControlFlowContext &CFCtx, llvm::ArrayRef< std::optional< TypeErasedDataflowAnalysisState > > BlockToState)
const Environment * getEnvironment (const Stmt &S) const
Returns the environment of the basic block that contains S.
Detailed Description
Maps statements to the environments of basic blocks that contain them.
Definition at line 26 of file Transfer.h.
Constructor & Destructor Documentation
StmtToEnvMap()
clang::dataflow::StmtToEnvMap::StmtToEnvMap (const ControlFlowContext & CFCtx, llvm::ArrayRef< std::optional< TypeErasedDataflowAnalysisState > > BlockToState) inline
Definition at line 28 of file Transfer.h.
References CFCtx.
Member Function Documentation
getEnvironment()
const Environment * clang::dataflow::StmtToEnvMap::getEnvironment (const Stmt & S) const
Returns the environment of the basic block that contains S.
The result is guaranteed never to be null.
Definition at line 40 of file Transfer.cpp.
References clang::dataflow::ControlFlowContext::getStmtToBlock(), clang::dataflow::ignoreCFGOmittedNodes(), and clang::dataflow::ControlFlowContext::isBlockReachable().
The documentation for this class was generated from the following files:
include/clang/Analysis/FlowSensitive/Transfer.h
lib/Analysis/FlowSensitive/Transfer.cpp