clang: clang::ConceptReference Class Reference
clang::ConceptReference Class Reference
Common data class for constructs that reference concepts with template arguments.
#include "clang/AST/ASTConcept.h"
Public Member Functions
ConceptReference (NestedNameSpecifierLoc NNS, SourceLocation TemplateKWLoc, DeclarationNameInfo ConceptNameInfo, NamedDecl *FoundDecl, ConceptDecl *NamedConcept, const ASTTemplateArgumentListInfo *ArgsAsWritten)
ConceptReference ()
const NestedNameSpecifierLoc & getNestedNameSpecifierLoc () const
const DeclarationNameInfo & getConceptNameInfo () const
SourceLocation getConceptNameLoc () const
SourceLocation getTemplateKWLoc () const
NamedDecl * getFoundDecl () const
ConceptDecl * getNamedConcept () const
const ASTTemplateArgumentListInfo * getTemplateArgsAsWritten () const
bool hasExplicitTemplateArgs () const
Whether or not template arguments were explicitly specified in the concept reference (they might not be in type constraints, for example)
Protected Attributes
NestedNameSpecifierLoc NestedNameSpec
SourceLocation TemplateKWLoc
The location of the template keyword, if specified when naming the concept.
DeclarationNameInfo ConceptName
The concept name used.
NamedDecl * FoundDecl
The declaration found by name lookup when the expression was created.
ConceptDecl * NamedConcept
The concept named.
const ASTTemplateArgumentListInfo * ArgsAsWritten
The template argument list source info used to specialize the concept.
Detailed Description
Common data class for constructs that reference concepts with template arguments.
Definition at line 112 of file ASTConcept.h.
Constructor & Destructor Documentation
ConceptReference() [1/2]
clang::ConceptReference::ConceptReference (NestedNameSpecifierLoc NNS, SourceLocation TemplateKWLoc, DeclarationNameInfo ConceptNameInfo, NamedDecl * FoundDecl, ConceptDecl * NamedConcept, const ASTTemplateArgumentListInfo * ArgsAsWritten) inline
Definition at line 138 of file ASTConcept.h.
ConceptReference() [2/2]
clang::ConceptReference::ConceptReference () inline
Definition at line 146 of file ASTConcept.h.
Member Function Documentation
getConceptNameInfo()
const DeclarationNameInfo & clang::ConceptReference::getConceptNameInfo () const inline
Definition at line 153 of file ASTConcept.h.
References ConceptName.
Referenced by getConceptNameLoc(), clang::Sema::SubstTypeConstraint(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getConceptNameLoc()
SourceLocation clang::ConceptReference::getConceptNameLoc () const inline
Definition at line 155 of file ASTConcept.h.
References getConceptNameInfo(), and clang::DeclarationNameInfo::getLoc().
getFoundDecl()
NamedDecl * clang::ConceptReference::getFoundDecl () const inline
Definition at line 161 of file ASTConcept.h.
References FoundDecl.
getNamedConcept()
ConceptDecl * clang::ConceptReference::getNamedConcept () const inline
Definition at line 165 of file ASTConcept.h.
References NamedConcept.
Referenced by diagnoseUnsatisfiedRequirement(), clang::ASTContext::isSameTypeConstraint(), substituteParameterMappings(), clang::Sema::SubstTypeConstraint(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getNestedNameSpecifierLoc()
const NestedNameSpecifierLoc & clang::ConceptReference::getNestedNameSpecifierLoc () const inline
Definition at line 149 of file ASTConcept.h.
References NestedNameSpec.
Referenced by clang::ConceptSpecializationExpr::getBeginLoc(), clang::Sema::SubstTypeConstraint(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getTemplateArgsAsWritten()
const ASTTemplateArgumentListInfo * clang::ConceptReference::getTemplateArgsAsWritten () const inline
Definition at line 169 of file ASTConcept.h.
References ArgsAsWritten.
Referenced by clang::computeDependence(), diagnoseUnsatisfiedRequirement(), clang::ASTContext::isSameTypeConstraint(), substituteParameterMappings(), clang::Sema::SubstTypeConstraint(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getTemplateKWLoc()
SourceLocation clang::ConceptReference::getTemplateKWLoc () const inline
Definition at line 159 of file ASTConcept.h.
References TemplateKWLoc.
hasExplicitTemplateArgs()
bool clang::ConceptReference::hasExplicitTemplateArgs () const inline
Whether or not template arguments were explicitly specified in the concept reference (they might not be in type constraints, for example)
Definition at line 175 of file ASTConcept.h.
References ArgsAsWritten.
Referenced by clang::ASTContext::isSameTypeConstraint(), clang::TypeConstraint::print(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr().
Member Data Documentation
ArgsAsWritten
const ASTTemplateArgumentListInfo* clang::ConceptReference::ArgsAsWritten protected
The template argument list source info used to specialize the concept.
Definition at line 135 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::Create(), clang::ConceptSpecializationExpr::Create(), clang::ConceptSpecializationExpr::getEndLoc(), getTemplateArgsAsWritten(), hasExplicitTemplateArgs(), and clang::TypeConstraint::print().
ConceptName
DeclarationNameInfo clang::ConceptReference::ConceptName protected
The concept name used.
Definition at line 122 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::getBeginLoc(), getConceptNameInfo(), clang::ConceptSpecializationExpr::getEndLoc(), and clang::TypeConstraint::print().
FoundDecl
NamedDecl* clang::ConceptReference::FoundDecl protected
The declaration found by name lookup when the expression was created.
Can differ from NamedConcept when, for example, the concept was found through a UsingShadowDecl.
Definition at line 128 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::Create(), and getFoundDecl().
NamedConcept
ConceptDecl* clang::ConceptReference::NamedConcept protected
The concept named.
Definition at line 131 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::Create(), clang::ConceptSpecializationExpr::Create(), and getNamedConcept().
NestedNameSpec
NestedNameSpecifierLoc clang::ConceptReference::NestedNameSpec protected
Definition at line 115 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), getNestedNameSpecifierLoc(), and clang::TypeConstraint::print().
TemplateKWLoc
SourceLocation clang::ConceptReference::TemplateKWLoc protected
The location of the template keyword, if specified when naming the concept.
Definition at line 119 of file ASTConcept.h.
Referenced by clang::ConceptSpecializationExpr::Create(), and getTemplateKWLoc().
The documentation for this class was generated from the following file:
include/clang/AST/ASTConcept.h