clang: clang::threadSafety::til::Project Class Reference
clang::threadSafety::til::Project Class Reference
Project a named slot from a C++ struct or class.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Project (SExpr *R, const ValueDecl *Cvd)
SExpr * record ()
const SExpr * record () const
const ValueDecl * clangDecl () const
bool isArrow () const
void setArrow (bool b)
StringRef slotName () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Project *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Project a named slot from a C++ struct or class.
Definition at line 921 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Project()
clang::threadSafety::til::Project::Project (SExpr * R, const ValueDecl * Cvd) inline
Definition at line 923 of file ThreadSafetyTIL.h.
Member Function Documentation
clangDecl()
const ValueDecl * clang::threadSafety::til::Project::clangDecl () const inline
Definition at line 933 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject().
classof()
static bool clang::threadSafety::til::Project::classof (const SExpr * E) inline static
Definition at line 928 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Project::compare (const Project * E, C & Cmp) const inline
Definition at line 960 of file ThreadSafetyTIL.h.
References record().
isArrow()
bool clang::threadSafety::til::Project::isArrow () const inline
Definition at line 935 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject().
record() [1/2]
SExpr * clang::threadSafety::til::Project::record () inline
Definition at line 930 of file ThreadSafetyTIL.h.
Referenced by compare(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject().
record() [2/2]
const SExpr * clang::threadSafety::til::Project::record () const inline
Definition at line 931 of file ThreadSafetyTIL.h.
setArrow()
void clang::threadSafety::til::Project::setArrow (bool b) inline
Definition at line 937 of file ThreadSafetyTIL.h.
References b, and clang::threadSafety::til::SExpr::Flags.
slotName()
StringRef clang::threadSafety::til::Project::slotName () const inline
Definition at line 942 of file ThreadSafetyTIL.h.
References clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::DeclarationName::isIdentifier(), and clang::NamedDecl::printName().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Project::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 954 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h