clang: lib/StaticAnalyzer/Checkers/CloneChecker.cpp File Reference
CloneChecker.cpp File Reference
CloneChecker is a checker that reports clones in the current translation unit.
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/Analysis/CloneDetection.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
Functions
static PathDiagnosticLocation makeLocation (const StmtSequence &S, AnalysisManager &Mgr)
Detailed Description
CloneChecker is a checker that reports clones in the current translation unit.
Definition in file CloneChecker.cpp.
Function Documentation
makeLocation()
static PathDiagnosticLocation makeLocation (const StmtSequence & S, AnalysisManager & Mgr) static
Definition at line 99 of file CloneChecker.cpp.
References clang::ento::PathDiagnosticLocation::createBegin(), clang::ento::AnalysisManager::getAnalysisDeclContext(), clang::ento::AnalysisManager::getASTContext(), clang::ASTContext::getSourceManager(), and clang::ASTContext::getTranslationUnitDecl().