clang: lib/CodeGen/Targets/PPC.cpp File Reference
PPC.cpp File Reference
#include "ABIInfoImpl.h"
#include "TargetInfo.h"
Functions
static Address complexTempStructure (CodeGenFunction &CGF, Address VAListAddr, QualType Ty, CharUnits SlotSize, CharUnits EltSize, const ComplexType *CTy)
static bool PPC_initDwarfEHRegSizeTable (CodeGen::CodeGenFunction &CGF, llvm::Value *Address, bool Is64Bit, bool IsAIX)
Function Documentation
complexTempStructure()
static Address complexTempStructure (CodeGenFunction & CGF, Address VAListAddr, QualType Ty, CharUnits SlotSize, CharUnits EltSize, const ComplexType * CTy) static
Definition at line 15 of file PPC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CodeGenFunction::EmitStoreOfComplex(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::ComplexType::getElementType(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and clang::CodeGen::Address::withElementType().
PPC_initDwarfEHRegSizeTable()
static bool PPC_initDwarfEHRegSizeTable (CodeGen::CodeGenFunction & CGF, llvm::Value * Address, bool Is64Bit, bool IsAIX) static
Definition at line 45 of file PPC.cpp.
References clang::CodeGen::AssignToArrayRange(), clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenTypeCache::Int8Ty.