clang: lib/Sema/CodeCompleteConsumer.cpp File Reference
CodeCompleteConsumer.cpp File Reference
#include "clang/Sema/CodeCompleteConsumer.h"
#include "clang-c/Index.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Type.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Sema.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <string>
Functions
static std::string getOverloadAsString (const CodeCompletionString &CCS)
static AvailabilityResult getDeclAvailability (const Decl *D)
Retrieve the effective availability of the given declaration.
Function Documentation
getDeclAvailability()
static AvailabilityResult getDeclAvailability (const Decl * D) static
Retrieve the effective availability of the given declaration.
Definition at line 768 of file CodeCompleteConsumer.cpp.
References clang::Decl::getAvailability(), and clang::Decl::getDeclContext().
getOverloadAsString()
static std::string getOverloadAsString (const CodeCompletionString & CCS) static
Definition at line 724 of file CodeCompleteConsumer.cpp.
References clang::C, clang::CodeCompletionString::CK_CurrentParameter, clang::CodeCompletionString::CK_Informative, clang::CodeCompletionString::CK_Optional, clang::CodeCompletionString::CK_ResultType, and clang::Result.
Referenced by clang::PrintingCodeCompleteConsumer::ProcessOverloadCandidates().