clang: lib/CodeGen/MicrosoftCXXABI.cpp File Reference
MicrosoftCXXABI.cpp File Reference
#include "ABIInfo.h"
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGVTables.h"
#include "CodeGenModule.h"
#include "CodeGenTypes.h"
#include "TargetInfo.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/VTableBuilder.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/IR/Intrinsics.h"
Functions
static llvm::CallBase * emitRTtypeidCall (CodeGenFunction &CGF, llvm::Value *Argument)
static bool isDeletingDtor (GlobalDecl GD)
static bool isTrivialForMSVC (const CXXRecordDecl *RD, QualType Ty, CodeGenModule &CGM)
static bool hasDefaultCXXMethodCC (ASTContext &Context, const CXXMethodDecl *MD)
static void mangleVFTableName (MicrosoftMangleContext &MangleContext, const CXXRecordDecl *RD, const VPtrInfo &VFPtr, SmallString< 256 > &Name)
static void emitGlobalDtorWithTLRegDtor (CodeGenFunction &CGF, const VarDecl &VD, llvm::FunctionCallee Dtor, llvm::Constant *Addr)
static llvm::GlobalValue * getTlsGuardVar (CodeGenModule &CGM)
static llvm::FunctionCallee getDynTlsOnDemandInitFn (CodeGenModule &CGM)
static void emitTlsGuardCheck (CodeGenFunction &CGF, llvm::GlobalValue *TlsGuard, llvm::BasicBlock *DynInitBB, llvm::BasicBlock *ContinueBB)
static void emitDynamicTlsInitializationCall (CodeGenFunction &CGF, llvm::GlobalValue *TlsGuard, llvm::BasicBlock *ContinueBB)
static void emitDynamicTlsInitialization (CodeGenFunction &CGF)
static ConstantAddress getInitThreadEpochPtr (CodeGenModule &CGM)
static llvm::FunctionCallee getInitThreadHeaderFn (CodeGenModule &CGM)
static llvm::FunctionCallee getInitThreadFooterFn (CodeGenModule &CGM)
static llvm::FunctionCallee getInitThreadAbortFn (CodeGenModule &CGM)
static llvm::GlobalVariable * getTypeInfoVTable (CodeGenModule &CGM)
static void serializeClassHierarchy (SmallVectorImpl< MSRTTIClass > &Classes, const CXXRecordDecl *RD)
Recursively serializes a class hierarchy in pre-order depth first order.
static void detectAmbiguousBases (SmallVectorImpl< MSRTTIClass > &Classes)
Find ambiguity among base classes.
static QualType decomposeTypeForEH (ASTContext &Context, QualType T, bool &IsConst, bool &IsVolatile, bool &IsUnaligned)
Function Documentation
decomposeTypeForEH()
static QualType decomposeTypeForEH (ASTContext & Context, QualType T, bool & IsConst, bool & IsVolatile, bool & IsUnaligned) static
Definition at line 3937 of file MicrosoftCXXABI.cpp.
References clang::ASTContext::getExceptionObjectType(), clang::ASTContext::getMemberPointerType(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::QualType::getQualifiers(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasUnaligned(), clang::QualType::isConstQualified(), clang::QualType::isNull(), and clang::QualType::isVolatileQualified().
detectAmbiguousBases()
static void detectAmbiguousBases (SmallVectorImpl< MSRTTIClass > & Classes) static
Find ambiguity among base classes.
Definition at line 3733 of file MicrosoftCXXABI.cpp.
emitDynamicTlsInitialization()
static void emitDynamicTlsInitialization (CodeGenFunction & CGF) static
Definition at line 2485 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::CurFn, emitDynamicTlsInitializationCall(), emitTlsGuardCheck(), and getTlsGuardVar().
emitDynamicTlsInitializationCall()
static void emitDynamicTlsInitializationCall (CodeGenFunction & CGF, llvm::GlobalValue * TlsGuard, llvm::BasicBlock * ContinueBB) static
Definition at line 2473 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, getDynTlsOnDemandInitFn(), and clang::Initializer.
Referenced by emitDynamicTlsInitialization().
emitGlobalDtorWithTLRegDtor()
static void emitGlobalDtorWithTLRegDtor (CodeGenFunction & CGF, const VarDecl & VD, llvm::FunctionCallee Dtor, llvm::Constant * Addr) static
Definition at line 2346 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::createAtExitStub(), clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), and clang::CodeGen::CodeGenTypeCache::IntTy.
emitRTtypeidCall()
static llvm::CallBase * emitRTtypeidCall (CodeGenFunction & CGF, llvm::Value * Argument) static
Definition at line 991 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitRuntimeCallOrInvoke(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
emitTlsGuardCheck()
static void emitTlsGuardCheck (CodeGenFunction & CGF, llvm::GlobalValue * TlsGuard, llvm::BasicBlock * DynInitBB, llvm::BasicBlock * ContinueBB) static
Definition at line 2463 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CharUnits::One().
Referenced by emitDynamicTlsInitialization().
getDynTlsOnDemandInitFn()
static llvm::FunctionCallee getDynTlsOnDemandInitFn (CodeGenModule & CGM) static
Definition at line 2449 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), and clang::CodeGen::CodeGenModule::getLLVMContext().
Referenced by emitDynamicTlsInitializationCall().
getInitThreadAbortFn()
static llvm::FunctionCallee getInitThreadAbortFn (CodeGenModule & CGM) static
Definition at line 2565 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::CodeGenTypeCache::IntTy.
getInitThreadEpochPtr()
static ConstantAddress getInitThreadEpochPtr (CodeGenModule & CGM) static
Definition at line 2527 of file MicrosoftCXXABI.cpp.
References clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), clang::CodeGen::CodeGenModule::getModule(), and clang::CodeGen::CodeGenTypeCache::IntTy.
getInitThreadFooterFn()
static llvm::FunctionCallee getInitThreadFooterFn (CodeGenModule & CGM) static
Definition at line 2553 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::CodeGenTypeCache::IntTy.
getInitThreadHeaderFn()
static llvm::FunctionCallee getInitThreadHeaderFn (CodeGenModule & CGM) static
Definition at line 2541 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::CodeGenTypeCache::IntTy.
getTlsGuardVar()
static llvm::GlobalValue * getTlsGuardVar (CodeGenModule & CGM) static
Definition at line 2434 of file MicrosoftCXXABI.cpp.
References clang::cast(), clang::CodeGen::CodeGenModule::CreateRuntimeVariable(), and clang::CodeGen::CodeGenModule::getLLVMContext().
Referenced by emitDynamicTlsInitialization().
getTypeInfoVTable()
static llvm::GlobalVariable * getTypeInfoVTable (CodeGenModule & CGM) static
Definition at line 3604 of file MicrosoftCXXABI.cpp.
References clang::CodeGen::CodeGenModule::getModule(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
hasDefaultCXXMethodCC()
static bool hasDefaultCXXMethodCC (ASTContext & Context, const CXXMethodDecl * MD) static
Definition at line 1273 of file MicrosoftCXXABI.cpp.
References clang::Type::castAs(), clang::ASTContext::getDefaultCallingConvention(), and clang::ValueDecl::getType().
Referenced by clang::ASTNameGenerator::Implementation::getAllManglings().
isDeletingDtor()
static bool isDeletingDtor (GlobalDecl GD) static
Definition at line 1101 of file MicrosoftCXXABI.cpp.
References clang::Dtor_Deleting, clang::GlobalDecl::getDecl(), clang::GlobalDecl::getDtorType(), and clang::isa().
isTrivialForMSVC()
static bool isTrivialForMSVC (const CXXRecordDecl * RD, QualType Ty, CodeGenModule & CGM) static
Definition at line 1110 of file MicrosoftCXXABI.cpp.
References clang::CXXRecordDecl::ctors(), clang::CodeGen::CodeGenTypes::getABIInfo(), clang::CXXRecordDecl::getNumBases(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenModule::getTypes(), clang::CXXRecordDecl::hasNonTrivialCopyAssignment(), clang::CXXRecordDecl::hasNonTrivialDestructor(), clang::CXXRecordDecl::hasPrivateFields(), clang::CXXRecordDecl::hasProtectedFields(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), and clang::CXXRecordDecl::isPolymorphic().
mangleVFTableName()
static void mangleVFTableName (MicrosoftMangleContext & MangleContext, const CXXRecordDecl * RD, const VPtrInfo & VFPtr, SmallString< 256 > & Name) static
Definition at line 1783 of file MicrosoftCXXABI.cpp.
References clang::VPtrInfo::MangledPath.
serializeClassHierarchy()
static void serializeClassHierarchy (SmallVectorImpl< MSRTTIClass > & Classes, const CXXRecordDecl * RD) static
Recursively serializes a class hierarchy in pre-order depth first order.
Definition at line 3724 of file MicrosoftCXXABI.cpp.
References clang::CXXRecordDecl::bases(), and serializeClassHierarchy().
Referenced by serializeClassHierarchy().