clang: lib/CodeGen/Targets/AMDGPU.cpp File Reference
AMDGPU.cpp File Reference
#include "ABIInfoImpl.h"
#include "TargetInfo.h"
Functions
static bool requiresAMDGPUProtectedVisibility (const Decl *D, llvm::GlobalValue *GV)
Function Documentation
requiresAMDGPUProtectedVisibility()
static bool requiresAMDGPUProtectedVisibility (const Decl * D, llvm::GlobalValue * GV) static
Definition at line 297 of file AMDGPU.cpp.
References clang::cast(), clang::Decl::hasAttr(), and clang::isa().