clang: lib/CodeGen/CodeGenModule.cpp File Reference
CodeGenModule.cpp File Reference
#include "CodeGenModule.h"
#include "ABIInfo.h"
#include "CGBlocks.h"
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGCall.h"
#include "CGDebugInfo.h"
#include "CGHLSLRuntime.h"
#include "CGObjCRuntime.h"
#include "CGOpenCLRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGOpenMPRuntimeGPU.h"
#include "CodeGenFunction.h"
#include "CodeGenPGO.h"
#include "ConstantEmitter.h"
#include "CoverageMappingGen.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Version.h"
#include "clang/CodeGen/BackendUtil.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/ProfileData/SampleProf.h"
#include "llvm/Support/CRC.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/xxhash.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/TargetParser/X86TargetParser.h"
#include <optional>
Functions
static llvm::cl::opt< bool > LimitedCoverage ("limited-coverage-experimental", llvm::cl::Hidden, llvm::cl::desc("Emit limited coverage mapping information (experimental)"))
static CGCXXABI * createCXXABI (CodeGenModule &CGM)
static std::unique_ptr< TargetCodeGenInfo > createTargetCodeGenInfo (CodeGenModule &CGM)
static const llvm::GlobalValue * getAliasedGlobal (const llvm::GlobalValue *GV)
static bool checkAliasedGlobal (DiagnosticsEngine &Diags, SourceLocation Location, bool IsIFunc, const llvm::GlobalValue *Alias, const llvm::GlobalValue *&GV, const llvm::MapVector< GlobalDecl, StringRef > &MangledDeclNames, SourceRange AliasRange)
static void setVisibilityFromDLLStorageClass (const clang::LangOptions &LO, llvm::Module &M)
static bool shouldAssumeDSOLocal (const CodeGenModule &CGM, llvm::GlobalValue *GV)
static llvm::GlobalVariable::ThreadLocalMode GetLLVMTLSModel (StringRef S)
static std::string getCPUSpecificMangling (const CodeGenModule &CGM, StringRef Name)
static void AppendCPUSpecificCPUDispatchMangling (const CodeGenModule &CGM, const CPUSpecificAttr *Attr, unsigned CPUIndex, raw_ostream &Out)
static void AppendTargetVersionMangling (const CodeGenModule &CGM, const TargetVersionAttr *Attr, raw_ostream &Out)
static void AppendTargetMangling (const CodeGenModule &CGM, const TargetAttr *Attr, raw_ostream &Out)
static bool isUniqueInternalLinkageDecl (GlobalDecl GD, CodeGenModule &CGM)
static void AppendTargetClonesMangling (const CodeGenModule &CGM, const TargetClonesAttr *Attr, unsigned VersionIndex, raw_ostream &Out)
static std::string getMangledNameImpl (CodeGenModule &CGM, GlobalDecl GD, const NamedDecl *ND, bool OmitMultiVersionMangling=false)
static void removeImageAccessQualifier (std::string &TyName)
static unsigned ArgInfoAddressSpace (LangAS AS)
static bool hasUnwindExceptions (const LangOptions &LangOpts)
Determines whether the language options require us to model unwind exceptions.
static bool requiresMemberFunctionPointerTypeMetadata (CodeGenModule &CGM, const CXXMethodDecl *MD)
static void setLinkageForGV (llvm::GlobalValue *GV, const NamedDecl *ND)
static bool allowKCFIIdentifier (StringRef Name)
static void emitUsed (CodeGenModule &CGM, StringRef Name, std::vector< llvm::WeakTrackingVH > &List)
static void addLinkOptionsPostorder (CodeGenModule &CGM, Module *Mod, SmallVectorImpl< llvm::MDNode * > &Metadata, llvm::SmallPtrSet< Module *, 16 > &Visited)
Add link options implied by the given module, including modules it depends on, using a postorder walk.
static bool HasNonDllImportDtor (QualType T)
static void ReplaceUsesOfNonProtoTypeWithRealFunction (llvm::GlobalValue *Old, llvm::Function *NewFn)
ReplaceUsesOfNonProtoTypeWithRealFunction - This function is called when we implement a function with no prototype, e.g.
static unsigned TargetMVPriority (const TargetInfo &TI, const CodeGenFunction::MultiVersionResolverOption &RO)
llvm::GlobalValue::LinkageTypes getMultiversionLinkage (CodeGenModule &CGM, GlobalDecl GD)
static const FunctionDecl * GetRuntimeFunctionDecl (ASTContext &C, StringRef Name)
static llvm::Constant * castStringLiteralToDefaultAddressSpace (CodeGenModule &CGM, llvm::GlobalVariable *GV)
static bool shouldBeInCOMDAT (CodeGenModule &CGM, const Decl &D)
static bool isVarDeclStrongDefinition (const ASTContext &Context, CodeGenModule &CGM, const VarDecl *D, bool NoCommon)
static void replaceUsesOfNonProtoConstant (llvm::Constant *old, llvm::Function *newFn)
Replace the uses of a function that was declared with a non-proto type.
static llvm::StringMapEntry< llvm::GlobalVariable * > & GetConstantCFStringEntry (llvm::StringMap< llvm::GlobalVariable * > &Map, const StringLiteral *Literal, bool TargetIsLSB, bool &IsUTF16, unsigned &StringLength)
static llvm::GlobalVariable * GenerateStringLiteral (llvm::Constant *C, llvm::GlobalValue::LinkageTypes LT, CodeGenModule &CGM, StringRef GlobalName, CharUnits Alignment)
static bool needsDestructMethod (ObjCImplementationDecl *impl)
static bool AllTrivialInitializers (CodeGenModule &CGM, ObjCImplementationDecl *D)
static llvm::Constant * GetPointerConstant (llvm::LLVMContext &Context, const void *Ptr)
Turns the given pointer into a constant.
static void EmitGlobalDeclMetadata (CodeGenModule &CGM, llvm::NamedMDNode *&GlobalMetadata, GlobalDecl D, llvm::GlobalValue *Addr)
static QualType GeneralizeType (ASTContext &Ctx, QualType Ty)
static QualType GeneralizeFunctionType (ASTContext &Ctx, QualType Ty)
Variables
static const char AnnotationSection [] = "llvm.metadata"
Function Documentation
addLinkOptionsPostorder()
static void addLinkOptionsPostorder (CodeGenModule & CGM, Module * Mod, SmallVectorImpl< llvm::MDNode * > & Metadata, llvm::SmallPtrSet< Module *, 16 > & Visited) static
Add link options implied by the given module, including modules it depends on, using a postorder walk.
Definition at line 2844 of file CodeGenModule.cpp.
References addLinkOptionsPostorder(), clang::CodeGen::TargetCodeGenInfo::getDependentLibraryOption(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::TargetInfo::getTriple(), clang::Module::Imports, clang::Module::LinkLibraries, clang::Module::Parent, clang::Module::UseExportAsModuleLinkName, and Visited.
Referenced by addLinkOptionsPostorder().
allowKCFIIdentifier()
static bool allowKCFIIdentifier (StringRef Name) static
Definition at line 2613 of file CodeGenModule.cpp.
References clang::C.
Referenced by clang::CodeGen::CodeGenModule::finalizeKCFITypes().
AllTrivialInitializers()
static bool AllTrivialInitializers (CodeGenModule & CGM, ObjCImplementationDecl * D) static
Definition at line 6427 of file CodeGenModule.cpp.
References clang::CXXCtorInitializer::getInit(), clang::ObjCImplementationDecl::init_begin(), clang::ObjCImplementationDecl::init_end(), and clang::CodeGen::CodeGenFunction::isTrivialInitializer().
AppendCPUSpecificCPUDispatchMangling()
static void AppendCPUSpecificCPUDispatchMangling (const CodeGenModule & CGM, const CPUSpecificAttr * Attr, unsigned CPUIndex, raw_ostream & Out) static
Definition at line 1587 of file CodeGenModule.cpp.
References getCPUSpecificMangling(), clang::CodeGen::CodeGenModule::getTarget(), and clang::TargetInfo::supportsIFunc().
Referenced by getMangledNameImpl().
AppendTargetClonesMangling()
static void AppendTargetClonesMangling (const CodeGenModule & CGM, const TargetClonesAttr * Attr, unsigned VersionIndex, raw_ostream & Out) static
Definition at line 1659 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), and clang::TargetInfo::multiVersionSortPriority().
Referenced by getMangledNameImpl().
AppendTargetMangling()
static void AppendTargetMangling (const CodeGenModule & CGM, const TargetAttr * Attr, raw_ostream & Out) static
Definition at line 1618 of file CodeGenModule.cpp.
References clang::ParsedTargetAttr::CPU, clang::ParsedTargetAttr::Features, clang::CodeGen::CodeGenModule::getTarget(), and IsFirst.
Referenced by getMangledNameImpl().
AppendTargetVersionMangling()
static void AppendTargetVersionMangling (const CodeGenModule & CGM, const TargetVersionAttr * Attr, raw_ostream & Out) static
Definition at line 1599 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getTarget(), and clang::TargetInfo::multiVersionSortPriority().
Referenced by getMangledNameImpl().
ArgInfoAddressSpace()
static unsigned ArgInfoAddressSpace (LangAS AS) static
Definition at line 2042 of file CodeGenModule.cpp.
References clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_global_device, clang::opencl_global_host, and clang::opencl_local.
Referenced by clang::CodeGen::CodeGenModule::GenKernelArgMetadata().
castStringLiteralToDefaultAddressSpace()
static llvm::Constant * castStringLiteralToDefaultAddressSpace (CodeGenModule & CGM, llvm::GlobalVariable * GV) static
Definition at line 4997 of file CodeGenModule.cpp.
References clang::Default, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::GetGlobalConstantAddressSpace(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::ASTContext::getTargetAddressSpace(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), and clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast().
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), and clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromLiteral().
checkAliasedGlobal()
static bool checkAliasedGlobal (DiagnosticsEngine & Diags, SourceLocation Location, bool IsIFunc, const llvm::GlobalValue * Alias, const llvm::GlobalValue *& GV, const llvm::MapVector< GlobalDecl, StringRef > & MangledDeclNames, SourceRange AliasRange) static
Definition at line 565 of file CodeGenModule.cpp.
References clang::FixItHint::CreateReplacement(), getAliasedGlobal(), and clang::DiagnosticsEngine::Report().
createCXXABI()
static CGCXXABI * createCXXABI (CodeGenModule & CGM) static
Definition at line 84 of file CodeGenModule.cpp.
References clang::CreateItaniumCXXABI(), clang::CreateMicrosoftCXXABI(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getCXXABIKind().
createTargetCodeGenInfo()
static std::unique_ptr< TargetCodeGenInfo > createTargetCodeGenInfo (CodeGenModule & CGM) static
Definition at line 105 of file CodeGenModule.cpp.
References clang::CodeGen::createAArch64TargetCodeGenInfo(), clang::CodeGen::createAIXTargetCodeGenInfo(), clang::CodeGen::createAMDGPUTargetCodeGenInfo(), clang::CodeGen::createARCTargetCodeGenInfo(), clang::CodeGen::createARMTargetCodeGenInfo(), clang::CodeGen::createAVRTargetCodeGenInfo(), clang::CodeGen::createBPFTargetCodeGenInfo(), clang::CodeGen::createCommonSPIRTargetCodeGenInfo(), clang::CodeGen::createCSKYTargetCodeGenInfo(), clang::CodeGen::createDefaultTargetCodeGenInfo(), clang::CodeGen::createHexagonTargetCodeGenInfo(), clang::CodeGen::createLanaiTargetCodeGenInfo(), clang::CodeGen::createLoongArchTargetCodeGenInfo(), clang::CodeGen::createM68kTargetCodeGenInfo(), clang::CodeGen::createMIPSTargetCodeGenInfo(), clang::CodeGen::createMSP430TargetCodeGenInfo(), clang::CodeGen::createNVPTXTargetCodeGenInfo(), clang::CodeGen::createPNaClTargetCodeGenInfo(), clang::CodeGen::createPPC32TargetCodeGenInfo(), clang::CodeGen::createPPC64_SVR4_TargetCodeGenInfo(), clang::CodeGen::createPPC64TargetCodeGenInfo(), clang::CodeGen::createRISCVTargetCodeGenInfo(), clang::CodeGen::createSparcV8TargetCodeGenInfo(), clang::CodeGen::createSparcV9TargetCodeGenInfo(), clang::CodeGen::createSPIRVTargetCodeGenInfo(), clang::CodeGen::createSystemZTargetCodeGenInfo(), clang::CodeGen::createTCETargetCodeGenInfo(), clang::CodeGen::createVETargetCodeGenInfo(), clang::CodeGen::createWebAssemblyTargetCodeGenInfo(), clang::CodeGen::createWindowsAArch64TargetCodeGenInfo(), clang::CodeGen::createWindowsARMTargetCodeGenInfo(), clang::CodeGen::createWinX86_32TargetCodeGenInfo(), clang::CodeGen::createWinX86_64TargetCodeGenInfo(), clang::CodeGen::createX86_32TargetCodeGenInfo(), clang::CodeGen::createX86_64TargetCodeGenInfo(), clang::CodeGen::createXCoreTargetCodeGenInfo(), clang::CodeGenOptions::FloatABI, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getTarget(), and clang::TargetInfo::getTriple().
Referenced by clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
EmitGlobalDeclMetadata()
static void EmitGlobalDeclMetadata (CodeGenModule & CGM, llvm::NamedMDNode *& GlobalMetadata, GlobalDecl D, llvm::GlobalValue * Addr) static
Definition at line 6949 of file CodeGenModule.cpp.
References clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), and GetPointerConstant().
emitUsed()
static void emitUsed (CodeGenModule & CGM, StringRef Name, std::vector< llvm::WeakTrackingVH > & List) static
Definition at line 2783 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getModule(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
GeneralizeFunctionType()
static QualType GeneralizeFunctionType (ASTContext & Ctx, QualType Ty) static
Definition at line 7241 of file CodeGenModule.cpp.
References GeneralizeType(), clang::Type::getAs(), clang::ASTContext::getFunctionNoProtoType(), and clang::ASTContext::getFunctionType().
Referenced by clang::CodeGen::CodeGenModule::CreateMetadataIdentifierGeneralized().
GeneralizeType()
static QualType GeneralizeType (ASTContext & Ctx, QualType Ty) static
Definition at line 7231 of file CodeGenModule.cpp.
References clang::QualType::getCVRQualifiers(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::Type::isPointerType(), clang::ASTContext::VoidTy, and clang::QualType::withCVRQualifiers().
Referenced by GeneralizeFunctionType().
GenerateStringLiteral()
static llvm::GlobalVariable * GenerateStringLiteral (llvm::Constant * C, llvm::GlobalValue::LinkageTypes LT, CodeGenModule & CGM, StringRef GlobalName, CharUnits Alignment) static
Definition at line 6139 of file CodeGenModule.cpp.
References clang::C, clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::GetGlobalConstantAddressSpace(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::ASTContext::getTargetAddressSpace(), LT, clang::CodeGen::CodeGenModule::setDSOLocal(), and clang::CodeGen::CodeGenModule::supportsCOMDAT().
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), and clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromLiteral().
getAliasedGlobal()
static const llvm::GlobalValue * getAliasedGlobal (const llvm::GlobalValue * GV) static
Definition at line 545 of file CodeGenModule.cpp.
References clang::C.
Referenced by checkAliasedGlobal().
GetConstantCFStringEntry()
static llvm::StringMapEntry< llvm::GlobalVariable * > & GetConstantCFStringEntry (llvm::StringMap< llvm::GlobalVariable * > & Map, const StringLiteral * Literal, bool TargetIsLSB, bool & IsUTF16, unsigned & StringLength) static
Definition at line 5831 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString().
getCPUSpecificMangling()
static std::string getCPUSpecificMangling (const CodeGenModule & CGM, StringRef Name) static
Definition at line 1581 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getTarget().
Referenced by AppendCPUSpecificCPUDispatchMangling().
GetLLVMTLSModel()
static llvm::GlobalVariable::ThreadLocalMode GetLLVMTLSModel (StringRef S) static
Definition at line 1544 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::setTLSMode().
getMangledNameImpl()
static std::string getMangledNameImpl (CodeGenModule & CGM, GlobalDecl GD, const NamedDecl * ND, bool OmitMultiVersionMangling = false) static
Definition at line 1692 of file CodeGenModule.cpp.
References AppendCPUSpecificCPUDispatchMangling(), AppendTargetClonesMangling(), AppendTargetMangling(), AppendTargetVersionMangling(), clang::CC_X86RegCall, clang::CPUDispatch, clang::CPUSpecific, clang::FunctionType::getCallConv(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::NamedDecl::getIdentifier(), clang::GlobalDecl::getKernelReferenceKind(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getModuleNameHash(), clang::GlobalDecl::getMultiVersionIndex(), clang::IdentifierInfo::getName(), clang::GlobalDecl::getWithDecl(), isUniqueInternalLinkageDecl(), clang::MangleContext::mangleName(), clang::MangleContext::needsUniqueInternalLinkageNames(), clang::None, clang::CodeGen::CodeGenModule::printPostfixForExternalizedDecl(), clang::ASTContext::shouldExternalize(), clang::MangleContext::shouldMangleDeclName(), clang::Stub, clang::Target, clang::TargetClones, and clang::TargetVersion.
Referenced by clang::CodeGen::CodeGenModule::getMangledName().
getMultiversionLinkage()
llvm::GlobalValue::LinkageTypes getMultiversionLinkage (CodeGenModule & CGM, GlobalDecl GD)
Definition at line 3943 of file CodeGenModule.cpp.
References clang::cast(), clang::GlobalDecl::getDecl(), clang::NamedDecl::getFormalLinkage(), and clang::InternalLinkage.
GetPointerConstant()
static llvm::Constant * GetPointerConstant (llvm::LLVMContext & Context, const void * Ptr) static
Turns the given pointer into a constant.
Definition at line 6942 of file CodeGenModule.cpp.
Referenced by EmitGlobalDeclMetadata().
GetRuntimeFunctionDecl()
static const FunctionDecl * GetRuntimeFunctionDecl (ASTContext & C, StringRef Name) static
Definition at line 4493 of file CodeGenModule.cpp.
References clang::C, clang::TranslationUnitDecl::castToDeclContext(), clang::Decl::getTranslationUnitDecl(), clang::DeclContext::lookup(), N, and clang::Result.
Referenced by clang::CodeGen::CodeGenModule::CreateRuntimeFunction().
HasNonDllImportDtor()
static bool HasNonDllImportDtor (QualType T) static
Definition at line 3677 of file CodeGenModule.cpp.
hasUnwindExceptions()
static bool hasUnwindExceptions (const LangOptions & LangOpts) static
Determines whether the language options require us to model unwind exceptions.
We treat -fexceptions as mandating this except under the fragile ObjC ABI with only ObjC exceptions enabled. This means, for example, that C with -fexceptions enables this.
Definition at line 2211 of file CodeGenModule.cpp.
References clang::ObjCRuntime::hasUnwindExceptions(), and clang::LangOptions::ObjCRuntime.
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
isUniqueInternalLinkageDecl()
static bool isUniqueInternalLinkageDecl (GlobalDecl GD, CodeGenModule & CGM) static
Definition at line 1652 of file CodeGenModule.cpp.
References clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), clang::CodeGen::CodeGenModule::getModuleNameHash(), and clang::isa().
Referenced by getMangledNameImpl().
isVarDeclStrongDefinition()
static bool isVarDeclStrongDefinition (const ASTContext & Context, CodeGenModule & CGM, const VarDecl * D, bool NoCommon) static
Definition at line 5346 of file CodeGenModule.cpp.
References clang::RecordDecl::fields(), clang::CharUnits::fromQuantity(), clang::Type::getAs(), clang::TargetInfo::getCXXABI(), clang::VarDecl::getInit(), clang::ASTContext::getTargetInfo(), clang::VarDecl::getTLSKind(), clang::TargetInfo::getTriple(), clang::ValueDecl::getType(), clang::ASTContext::getTypeAlignIfKnown(), clang::Decl::hasAttr(), clang::VarDecl::hasExternalStorage(), clang::ASTContext::isAlignmentRequired(), clang::TargetCXXABI::isMicrosoft(), shouldBeInCOMDAT(), and clang::ASTContext::toBits().
Referenced by clang::CodeGen::CodeGenModule::getLLVMLinkageForDeclarator().
LimitedCoverage()
static llvm::cl::opt< bool > LimitedCoverage ("limited-coverage-experimental" , llvm::cl::Hidden , llvm::cl::desc("Emit limited coverage mapping information (experimental)")) static
Referenced by clang::CodeGen::CodeGenModule::AddDeferredUnusedCoverageMapping().
needsDestructMethod()
static bool needsDestructMethod (ObjCImplementationDecl * impl) static
Definition at line 6417 of file CodeGenModule.cpp.
References clang::ObjCInterfaceDecl::all_declared_ivar_begin(), clang::ObjCImplDecl::getClassInterface(), and clang::ObjCIvarDecl::getNextIvar().
removeImageAccessQualifier()
static void removeImageAccessQualifier (std::string & TyName) static
Definition at line 2016 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::GenKernelArgMetadata().
replaceUsesOfNonProtoConstant()
static void replaceUsesOfNonProtoConstant (llvm::Constant * old, llvm::Function * newFn) static
Replace the uses of a function that was declared with a non-proto type.
We want to silently drop extra arguments from call sites
Definition at line 5502 of file CodeGenModule.cpp.
References clang::cast(), and replaceUsesOfNonProtoConstant().
Referenced by replaceUsesOfNonProtoConstant(), and ReplaceUsesOfNonProtoTypeWithRealFunction().
ReplaceUsesOfNonProtoTypeWithRealFunction()
static void ReplaceUsesOfNonProtoTypeWithRealFunction (llvm::GlobalValue * Old, llvm::Function * NewFn) static
ReplaceUsesOfNonProtoTypeWithRealFunction - This function is called when we implement a function with no prototype, e.g.
"int foo() {}". If there are existing call uses of the old function in the module, this adjusts them to call the new function directly.
This is not just a cleanup: the always_inline pass requires direct calls to functions to be able to inline them. If there is a bitcast in the way, it won't inline them. Instcombine normally deletes these calls, but it isn't run at -O0.
Definition at line 5608 of file CodeGenModule.cpp.
References replaceUsesOfNonProtoConstant().
requiresMemberFunctionPointerTypeMetadata()
static bool requiresMemberFunctionPointerTypeMetadata (CodeGenModule & CGM, const CXXMethodDecl * MD) static
Definition at line 2226 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CXXMethodDecl::getParent(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::isa(), clang::CXXMethodDecl::isStatic(), and clang::CXXMethodDecl::isVirtual().
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
setLinkageForGV()
static void setLinkageForGV (llvm::GlobalValue * GV, const NamedDecl * ND) static
Definition at line 2573 of file CodeGenModule.cpp.
References clang::LinkageInfo::getLinkage(), clang::NamedDecl::getLinkageAndVisibility(), clang::Decl::hasAttr(), clang::isExternallyVisible(), clang::Decl::isWeakImported(), and clang::LinkageInfo::setLinkage().
setVisibilityFromDLLStorageClass()
static void setVisibilityFromDLLStorageClass (const clang::LangOptions & LO, llvm::Module & M) static
Definition at line 713 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::GetLLVMVisibility().
Referenced by clang::CodeGen::CodeGenModule::Release().
shouldAssumeDSOLocal()
static bool shouldAssumeDSOLocal (const CodeGenModule & CGM, llvm::GlobalValue * GV) static
Definition at line 1397 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getTriple(), and clang::CodeGenOptions::RelocationModel.
Referenced by clang::CodeGen::CodeGenModule::setDSOLocal().
shouldBeInCOMDAT()
static bool shouldBeInCOMDAT (CodeGenModule & CGM, const Decl & D) static
Definition at line 5044 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::GetGVALinkageForFunction(), clang::ASTContext::GetGVALinkageForVariable(), clang::GVA_AvailableExternally, clang::GVA_DiscardableODR, clang::GVA_Internal, clang::GVA_StrongExternal, clang::GVA_StrongODR, clang::Decl::hasAttr(), and clang::CodeGen::CodeGenModule::supportsCOMDAT().
Referenced by isVarDeclStrongDefinition(), and clang::CodeGen::CodeGenModule::maybeSetTrivialComdat().
TargetMVPriority()
static unsigned TargetMVPriority (const TargetInfo & TI, const CodeGenFunction::MultiVersionResolverOption & RO) static
Definition at line 3920 of file CodeGenModule.cpp.
References clang::TargetInfo::multiVersionFeatureCost(), clang::TargetInfo::multiVersionSortPriority(), and Priority.
Variable Documentation
AnnotationSection
const char AnnotationSection[] = "llvm.metadata" static
Definition at line 82 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitAnnotationArgs(), clang::CodeGen::CodeGenModule::EmitAnnotationString(), and clang::CodeGen::CodeGenModule::EmitGlobalAnnotations().