clang: lib/AST/ComputeDependence.cpp File Reference
ComputeDependence.cpp File Reference
#include "clang/AST/ComputeDependence.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/DependenceFlags.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "llvm/ADT/ArrayRef.h"
Functions
static ExprDependence getDependenceInExpr (DeclarationNameInfo Name)
Function Documentation
getDependenceInExpr()
static ExprDependence getDependenceInExpr (DeclarationNameInfo Name) inline static
Definition at line 614 of file ComputeDependence.cpp.
Referenced by clang::computeDependence(), clang::computeDependence(), clang::computeDependence(), and clang::computeDependence().