clang: lib/AST/ComparisonCategories.cpp File Reference
ComparisonCategories.cpp File Reference
#include "clang/AST/ComparisonCategories.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Type.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
Functions
static const NamespaceDecl * lookupStdNamespace (const ASTContext &Ctx, NamespaceDecl *&StdNS)
static CXXRecordDecl * lookupCXXRecordDecl (const ASTContext &Ctx, const NamespaceDecl *StdNS, ComparisonCategoryType Kind)
Function Documentation
lookupCXXRecordDecl()
static CXXRecordDecl * lookupCXXRecordDecl (const ASTContext & Ctx, const NamespaceDecl * StdNS, ComparisonCategoryType Kind) static
Definition at line 101 of file ComparisonCategories.cpp.
References clang::DeclContextLookupResult::empty(), clang::DeclContextLookupResult::front(), clang::IdentifierTable::get(), clang::ComparisonCategories::getCategoryString(), clang::ASTContext::Idents, and clang::DeclContext::lookup().
Referenced by clang::ComparisonCategories::lookupInfo().
lookupStdNamespace()
static const NamespaceDecl * lookupStdNamespace (const ASTContext & Ctx, NamespaceDecl *& StdNS) static
Definition at line 90 of file ComparisonCategories.cpp.
References clang::DeclContextLookupResult::empty(), clang::DeclContextLookupResult::front(), clang::IdentifierTable::get(), clang::ASTContext::getTranslationUnitDecl(), clang::ASTContext::Idents, and clang::DeclContext::lookup().
Referenced by clang::ComparisonCategories::lookupInfo().