clang: lib/Driver/ToolChains/CSKYToolChain.cpp File Reference
CSKYToolChain.cpp File Reference
#include "CSKYToolChain.h"
#include "CommonArgs.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void addMultilibsFilePaths (const Driver &D, const MultilibSet &Multilibs, const Multilib &Multilib, StringRef InstallPath, ToolChain::path_list &Paths)
Function Documentation
addMultilibsFilePaths()
static void addMultilibsFilePaths (const Driver & D, const MultilibSet & Multilibs, const Multilib & Multilib, StringRef InstallPath, ToolChain::path_list & Paths) static
Definition at line 25 of file CSKYToolChain.cpp.
References clang::driver::tools::addPathIfExists(), and clang::driver::MultilibSet::filePathsCallback().
Referenced by clang::driver::toolchains::CSKYToolChain::CSKYToolChain(), and clang::driver::toolchains::RISCVToolChain::RISCVToolChain().