clang: lib/Analysis/FlowSensitive/DataflowAnalysisContext.cpp File Reference
DataflowAnalysisContext.cpp File Reference
#include "clang/Analysis/FlowSensitive/DataflowAnalysisContext.h"
#include "clang/AST/ExprCXX.h"
#include "clang/Analysis/FlowSensitive/DebugSupport.h"
#include "clang/Analysis/FlowSensitive/Formula.h"
#include "clang/Analysis/FlowSensitive/Logger.h"
#include "clang/Analysis/FlowSensitive/Value.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <memory>
#include <string>
#include <utility>
#include <vector>
Namespaces
namespace clang
namespace clang::dataflow
Dataflow Directional Tag Classes.
Functions
static llvm::cl::opt< std::string > DataflowLog ("dataflow-log", llvm::cl::Hidden, llvm::cl::ValueOptional, llvm::cl::desc("Emit log of dataflow analysis. With no arg, writes textual " "log to stderr. With an arg, writes HTML logs under the " "specified directory (one per analyzed function)."))
static std::unique_ptr< Logger > clang::dataflow::makeLoggerFromCommandLine ()
static void getFieldsFromClassHierarchy (QualType Type, clang::dataflow::FieldSet &Fields)
Function Documentation
DataflowLog()
static llvm::cl::opt< std::string > DataflowLog ("dataflow-log" , llvm::cl::Hidden , llvm::cl::ValueOptional , llvm::cl::desc("Emit log of dataflow analysis. With no arg, writes textual " "log to stderr. With an arg, writes HTML logs under the " "specified directory (one per analyzed function).")) static
Referenced by clang::dataflow::DataflowAnalysisContext::DataflowAnalysisContext(), and clang::dataflow::makeLoggerFromCommandLine().
getFieldsFromClassHierarchy()
static void getFieldsFromClassHierarchy (QualType Type, clang::dataflow::FieldSet & Fields) static
Definition at line 309 of file DataflowAnalysisContext.cpp.
References clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), clang::Type::getAsRecordDecl(), getFieldsFromClassHierarchy(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), and clang::Type::isRecordType().
Referenced by getFieldsFromClassHierarchy(), and clang::dataflow::getObjectFields().