clang: lib/AST/DeclBase.cpp File Reference
DeclBase.cpp File Reference
#include "clang/AST/DeclBase.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/Attr.h"
#include "clang/AST/AttrIterator.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclContextInternals.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DependentDiagnostic.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/Type.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/VersionTuple.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <string>
#include <tuple>
#include <utility>
#include "clang/AST/DeclNodes.inc"
Macros
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL(NAME, BASE)
#define DECL_CONTEXT(NAME)
#define DECL_CONTEXT_BASE(NAME)
#define DECL(NAME, BASE)
#define DECL_CONTEXT_BASE(NAME)
#define DECL(NAME, BASE)
#define DECL_CONTEXT(NAME)
#define DECL_CONTEXT_BASE(NAME)
#define DECL(NAME, BASE)
#define DECL_CONTEXT_BASE(NAME)
#define DECL(NAME, BASE)
#define DECL_CONTEXT(NAME)
#define DECL_CONTEXT_BASE(NAME)
#define DECL(NAME, BASE)
#define DECL_CONTEXT_BASE(NAME)
Functions
static StringRef getRealizedPlatform (const AvailabilityAttr *A, const ASTContext &Context)
static AvailabilityResult CheckAvailability (ASTContext &Context, const AvailabilityAttr *A, std::string *Message, VersionTuple EnclosingVersion)
Determine the availability of the given declaration based on the target platform.
static Decl::Kind getKind (const Decl *D)
static Decl::Kind getKind (const DeclContext *DC)
template<class T >
static Decl * getNonClosureContext (T *D)
Starting at a given context (a Decl or DeclContext), look for a code context that is not a closure (a lambda, block, etc.).
static bool isLinkageSpecContext (const DeclContext *DC, LinkageSpecDecl::LanguageIDs ID)
template<typename T >
void collectAllContextsImpl (T *Self, SmallVectorImpl< DeclContext * > &Contexts)
static bool shouldBeHidden (NamedDecl *D)
shouldBeHidden - Determine whether a declaration which was declared within its semantic context should be invisible to qualified name lookup.
Macro Definition Documentation
ABSTRACT_DECL [1/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [2/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [3/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [4/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [5/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [6/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [7/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
ABSTRACT_DECL [8/8]
#define ABSTRACT_DECL (DECL)
Definition at line 61 of file DeclBase.cpp.
DECL [1/14]
#define DECL (DERIVED, BASE)
Value:
static int n##DERIVED##s = 0;
Definition at line 60 of file DeclBase.cpp.
DECL [2/14]
#define DECL (DERIVED, BASE)
Value:
  static_assert(alignof(Decl) >= alignof(DERIVED##Decl),                       \
                "Alignment sufficient after objects prepended to " #DERIVED);
Definition at line 60 of file DeclBase.cpp.
DECL [3/14]
#define DECL (DERIVED, BASE)
Value:
case DERIVED: return #DERIVED;
Definition at line 60 of file DeclBase.cpp.
DECL [4/14]
#define DECL (DERIVED, BASE)
Value:
case Decl::DERIVED: return true;
Definition at line 60 of file DeclBase.cpp.
DECL [5/14]
#define DECL (DERIVED, BASE)
Value:
case Decl::DERIVED: return #DERIVED;
Definition at line 60 of file DeclBase.cpp.
DECL [6/14]
#define DECL (DERIVED, BASE)
Value:
totalDecls += n##DERIVED##s;
Definition at line 60 of file DeclBase.cpp.
DECL [7/14]
#define DECL (DERIVED, BASE)
Value:
  if (n##DERIVED##s > 0) {                                              \
    totalBytes += (int)(n##DERIVED##s * sizeof(DERIVED##Decl));         \
    llvm::errs() << "    " << n##DERIVED##s << " " #DERIVED " decls, "  \
                 << sizeof(DERIVED##Decl) << " each ("                  \
                 << n##DERIVED##s * sizeof(DERIVED##Decl)               \
                 << " bytes)\n";                                        \
  }
Definition at line 60 of file DeclBase.cpp.
DECL [8/14]
#define DECL (DERIVED, BASE)
Value:
case DERIVED: ++n##DERIVED##s; break;
Definition at line 60 of file DeclBase.cpp.
DECL [9/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL [10/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL [11/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL [12/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL [13/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL [14/14]
#define DECL (NAME, BASE)
Definition at line 60 of file DeclBase.cpp.
DECL_CONTEXT [1/3]
#define DECL_CONTEXT (NAME)
Value:
    case Decl::NAME:       \
      return static_cast<NAME##Decl *>(const_cast<DeclContext *>(D));
DECL_CONTEXT [2/3]
#define DECL_CONTEXT (NAME)
Value:
    case Decl::NAME:       \
      return static_cast<NAME##Decl *>(const_cast<Decl *>(D));
DECL_CONTEXT [3/3]
#define DECL_CONTEXT (NAME)
Value:
case Decl::NAME:
DECL_CONTEXT_BASE [1/6]
#define DECL_CONTEXT_BASE (NAME)
DECL_CONTEXT_BASE [2/6]
#define DECL_CONTEXT_BASE (NAME)
Value:
      if (DK >= first##NAME && DK <= last##NAME) \
        return static_cast<NAME##Decl *>(const_cast<DeclContext *>(D));
DECL_CONTEXT_BASE [3/6]
#define DECL_CONTEXT_BASE (NAME)
DECL_CONTEXT_BASE [4/6]
#define DECL_CONTEXT_BASE (NAME)
Value:
      if (DK >= first##NAME && DK <= last##NAME)                  \
        return static_cast<NAME##Decl *>(const_cast<Decl *>(D));
DECL_CONTEXT_BASE [5/6]
#define DECL_CONTEXT_BASE (NAME)
DECL_CONTEXT_BASE [6/6]
#define DECL_CONTEXT_BASE (NAME)
Value:
      if (D->getKind() >= Decl::first##NAME &&  \
          D->getKind() <= Decl::last##NAME)     \
        return true;
Function Documentation
CheckAvailability()
static AvailabilityResult CheckAvailability (ASTContext & Context, const AvailabilityAttr * A, std::string * Message, VersionTuple EnclosingVersion) static
Determine the availability of the given declaration based on the target platform.
When it returns an availability result other than AR_Available, if the Message parameter is non-NULL, it will be set to a string describing why the entity is unavailable.
FIXME: Make these strings localizable, since they end up in diagnostics.
Definition at line 553 of file DeclBase.cpp.
References clang::AR_Available, clang::AR_Deprecated, clang::AR_NotYetIntroduced, clang::AR_Unavailable, clang::TargetInfo::getPlatformMinVersion(), clang::TargetInfo::getPlatformName(), getRealizedPlatform(), and clang::ASTContext::getTargetInfo().
Referenced by clang::Decl::getAvailability(), and clang::Decl::isWeakImported().
collectAllContextsImpl()
template<typename T > void collectAllContextsImpl (T * Self, SmallVectorImpl< DeclContext * > & Contexts)
Definition at line 1378 of file DeclBase.cpp.
Referenced by clang::DeclContext::collectAllContexts().
getKind() [1/2]
static Decl::Kind getKind (const Decl * D) static
Definition at line 1048 of file DeclBase.cpp.
References clang::Decl::getKind().
Referenced by clang::syntax::List::canBeEmpty(), CheckNonTypeTemplatePartialSpecializationArgs(), clang::CodeGen::CGOpenCLRuntime::convertOpenCLSpecificType(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::Sema::DeduceAutoType(), clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), clang::ento::CoreEngine::enqueueStmtNode(), EvaluateBuiltinClassifyType(), clang::PrecompiledPreamble::PCHStorage::filePath(), getCommonSugarTypeNode(), clang::syntax::List::getDelimiterTokenKind(), clang::CFGImplicitDtor::getDestructorDecl(), clang::CodeCompleteConsumer::OverloadCandidate::getFunction(), getNonClosureContext(), clang::getSimplifiedTypeClass(), clang::syntax::List::getTerminationKind(), clang::BuiltinTypeLoc::getWrittenTypeSpec(), clang::TemplateSpecializationTypeLoc::initializeArgLocs(), clang::Declarator::isCtorOrDtor(), isObjCReceiverType(), IsStructurallyEquivalent(), MatchTwoAttributeLists(), clang::PrecompiledPreamble::PCHStorage::memoryContents(), clang::CodeGen::EHScopeStack::iterator::operator++(), clang::Parser::ParseTopLevelDecl(), and clang::ento::PathDiagnosticPiece::Profile().
getKind() [2/2]
static Decl::Kind getKind (const DeclContext * DC) static
Definition at line 1049 of file DeclBase.cpp.
References clang::DeclContext::getDeclKind().
getNonClosureContext()
template<class T > static Decl * getNonClosureContext (T * D) static
Starting at a given context (a Decl or DeclContext), look for a code context that is not a closure (a lambda, block, etc.).
Definition at line 1093 of file DeclBase.cpp.
References clang::cast(), getKind(), and getNonClosureContext().
Referenced by getNonClosureContext().
getRealizedPlatform()
static StringRef getRealizedPlatform (const AvailabilityAttr * A, const ASTContext & Context) static
Definition at line 531 of file DeclBase.cpp.
References clang::ASTContext::getLangOpts().
Referenced by CheckAvailability(), and clang::Decl::getVersionIntroduced().
isLinkageSpecContext()
static bool isLinkageSpecContext (const DeclContext * DC, LinkageSpecDecl::LanguageIDs ID) static
Definition at line 1250 of file DeclBase.cpp.
References clang::cast(), clang::DeclContext::getDeclKind(), and clang::DeclContext::getLexicalParent().
Referenced by clang::DeclContext::isExternCContext(), and clang::DeclContext::isExternCXXContext().
shouldBeHidden()
static bool shouldBeHidden (NamedDecl * D) static
shouldBeHidden - Determine whether a declaration which was declared within its semantic context should be invisible to qualified name lookup.
Definition at line 1524 of file DeclBase.cpp.
References clang::Decl::getCanonicalDecl(), clang::NamedDecl::getDeclName(), clang::Decl::getFriendObjectKind(), clang::Decl::getIdentifierNamespace(), clang::Decl::isInvalidDecl(), clang::Decl::isLocalExternDecl(), and clang::Decl::isTemplateParameter().
Referenced by clang::DeclContext::removeDecl().