clang: lib/AST/DeclCXX.cpp File Reference
DeclCXX.cpp File Reference
#include "clang/AST/DeclCXX.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/ASTUnresolvedSet.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/LambdaCapture.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/ODRHash.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/UnresolvedSet.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
Functions
static bool hasRepeatedBaseClass (const CXXRecordDecl *StartRD)
Determine whether a class has a repeated base class.
static bool allLookupResultsAreTheSame (const DeclContext::lookup_result &R)
static NamedDecl * getLambdaCallOperatorHelper (const CXXRecordDecl &RD)
static DeclContext::lookup_result getLambdaStaticInvokers (const CXXRecordDecl &RD)
static CXXMethodDecl * getInvokerAsMethod (NamedDecl *ND)
static CanQualType GetConversionType (ASTContext &Context, NamedDecl *Conv)
static void CollectVisibleConversions (ASTContext &Context, const CXXRecordDecl *Record, bool InVirtual, AccessSpecifier Access, const llvm::SmallPtrSet< CanQualType, 8 > &ParentHiddenTypes, ASTUnresolvedSet &Output, UnresolvedSetImpl &VOutput, llvm::SmallPtrSet< NamedDecl *, 8 > &HiddenVBaseCs)
Collect the visible conversions of a base class.
static void CollectVisibleConversions (ASTContext &Context, const CXXRecordDecl *Record, ASTUnresolvedSet &Output)
Collect the visible conversions of a class.
static bool isDeclContextInNamespace (const DeclContext *DC)
static bool recursivelyOverrides (const CXXMethodDecl *DerivedMD, const CXXMethodDecl *BaseMD)
static QualType getThisObjectType (ASTContext &C, const FunctionProtoType *FPT, const CXXRecordDecl *Decl)
static bool isValidStructGUID (ASTContext &Ctx, QualType T)
Determine if T is a valid 'struct _GUID' of the shape that we expect.
static const char * getAccessName (AccessSpecifier AS)
Function Documentation
allLookupResultsAreTheSame()
static bool allLookupResultsAreTheSame (const DeclContext::lookup_result & R) static
Definition at line 1527 of file DeclCXX.cpp.
References clang::declaresSameEntity(), and clang::DeclContextLookupResult::front().
Referenced by getLambdaCallOperatorHelper().
CollectVisibleConversions() [1/2]
static void CollectVisibleConversions (ASTContext & Context, const CXXRecordDecl * Record, ASTUnresolvedSet & Output) static
Collect the visible conversions of a class.
This would be extremely straightforward if it weren't for virtual bases. It might be worth special-casing that, really.
Definition at line 1747 of file DeclCXX.cpp.
References clang::ASTUnresolvedSet::addDecl(), clang::ASTUnresolvedSet::append(), clang::UnresolvedSetImpl::begin(), CollectVisibleConversions(), clang::UnresolvedSetImpl::end(), GetConversionType(), and clang::UnresolvedSetIterator::getDecl().
CollectVisibleConversions() [2/2]
static void CollectVisibleConversions (ASTContext & Context, const CXXRecordDecl * Record, bool InVirtual, AccessSpecifier Access, const llvm::SmallPtrSet< CanQualType, 8 > & ParentHiddenTypes, ASTUnresolvedSet & Output, UnresolvedSetImpl & VOutput, llvm::SmallPtrSet< NamedDecl *, 8 > & HiddenVBaseCs) static
Collect the visible conversions of a base class.
Parameters
Record a base class of the class we're considering
InVirtual whether this base class is a virtual base (or a base of a virtual base)
Access the access along the inheritance path to this base
ParentHiddenTypes the conversions provided by the inheritors of this base
Output the set to which to add conversions from non-virtual bases
VOutput the set to which to add conversions from virtual bases
HiddenVBaseCs the set of conversions which were hidden in a virtual base along some inheritance path
Definition at line 1684 of file DeclCXX.cpp.
References clang::Decl::Access, clang::ASTUnresolvedSet::addDecl(), clang::UnresolvedSetImpl::addDecl(), clang::cast(), CollectVisibleConversions(), GetConversionType(), and clang::CXXRecordDecl::MergeAccess().
Referenced by CollectVisibleConversions(), CollectVisibleConversions(), and clang::CXXRecordDecl::getVisibleConversionFunctions().
getAccessName()
static const char * getAccessName (AccessSpecifier AS) static
Definition at line 3476 of file DeclCXX.cpp.
References clang::AS_none, clang::AS_private, clang::AS_protected, and clang::AS_public.
Referenced by clang::operator<<().
GetConversionType()
static CanQualType GetConversionType (ASTContext & Context, NamedDecl * Conv) static
Definition at line 1665 of file DeclCXX.cpp.
References clang::cast(), clang::Decl::getAsFunction(), clang::ASTContext::getCanonicalType(), and clang::NamedDecl::getUnderlyingDecl().
Referenced by CollectVisibleConversions(), and CollectVisibleConversions().
getInvokerAsMethod()
static CXXMethodDecl * getInvokerAsMethod (NamedDecl * ND) static
Definition at line 1578 of file DeclCXX.cpp.
References clang::cast().
Referenced by clang::CXXRecordDecl::getLambdaStaticInvoker().
getLambdaCallOperatorHelper()
static NamedDecl * getLambdaCallOperatorHelper (const CXXRecordDecl & RD) static
Definition at line 1535 of file DeclCXX.cpp.
References allLookupResultsAreTheSame(), clang::ASTContext::DeclarationNames, clang::DeclContextLookupResult::empty(), clang::DeclContextLookupResult::front(), clang::Decl::getASTContext(), clang::DeclarationNameTable::getCXXOperatorName(), clang::CXXRecordDecl::isLambda(), and clang::DeclContext::lookup().
Referenced by clang::CXXRecordDecl::getDependentLambdaCallOperator(), and clang::CXXRecordDecl::getLambdaCallOperator().
getLambdaStaticInvokers()
static DeclContext::lookup_result getLambdaStaticInvokers (const CXXRecordDecl & RD) static
Definition at line 1571 of file DeclCXX.cpp.
References clang::IdentifierTable::get(), clang::Decl::getASTContext(), clang::getLambdaStaticInvokerName(), clang::ASTContext::Idents, clang::CXXRecordDecl::isLambda(), and clang::DeclContext::lookup().
Referenced by clang::CXXRecordDecl::getLambdaStaticInvoker().
getThisObjectType()
static QualType getThisObjectType (ASTContext & C, const FunctionProtoType * FPT, const CXXRecordDecl * Decl) static
Definition at line 2485 of file DeclCXX.cpp.
References clang::C, and clang::FunctionProtoType::getMethodQuals().
Referenced by clang::Sema::CreateOverloadedBinOp(), clang::CXXMethodDecl::getThisType(), and clang::threadSafety::SExprBuilder::translateAttrExpr().
hasRepeatedBaseClass()
static bool hasRepeatedBaseClass (const CXXRecordDecl * StartRD) static
Determine whether a class has a repeated base class.
This is intended for use when determining if a class is standard-layout, so makes no attempt to handle virtual bases.
Definition at line 175 of file DeclCXX.cpp.
References clang::CXXRecordDecl::bases(), clang::TypeDecl::getTypeForDecl(), and clang::Type::isDependentType().
Referenced by clang::CXXRecordDecl::setBases().
isDeclContextInNamespace()
static bool isDeclContextInNamespace (const DeclContext * DC) static
Definition at line 1953 of file DeclCXX.cpp.
References clang::DeclContext::getParent(), clang::DeclContext::isNamespace(), and clang::DeclContext::isTranslationUnit().
Referenced by clang::CXXRecordDecl::isInterfaceLike().
isValidStructGUID()
static bool isValidStructGUID (ASTContext & Ctx, QualType T) static
Determine if T is a valid 'struct _GUID' of the shape that we expect.
Definition at line 3375 of file DeclCXX.cpp.
References bool, clang::RecordDecl::fields(), clang::ASTContext::getAsConstantArrayType(), clang::RecordDecl::getDefinition(), clang::ArrayType::getElementType(), clang::ASTContext::getIntWidth(), clang::ConstantArrayType::getSize(), clang::TagDecl::isUnion(), and N.
Referenced by clang::MSGuidDecl::getAsAPValue().
recursivelyOverrides()
static bool recursivelyOverrides (const CXXMethodDecl * DerivedMD, const CXXMethodDecl * BaseMD) static
Definition at line 2154 of file DeclCXX.cpp.
References clang::CXXMethodDecl::getCanonicalDecl(), clang::CXXMethodDecl::overridden_methods(), and recursivelyOverrides().
Referenced by clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), clang::CXXMethodDecl::getCorrespondingMethodInClass(), and recursivelyOverrides().