clang: lib/AST/Interp/Descriptor.cpp File Reference
Descriptor.cpp File Reference
#include "Descriptor.h"
#include "Boolean.h"
#include "Floating.h"
#include "FunctionPointer.h"
#include "Pointer.h"
#include "PrimType.h"
#include "Record.h"
Functions
template<typename T >
static void ctorTy (Block *, char *Ptr, bool, bool, bool, const Descriptor *)
template<typename T >
static void dtorTy (Block *, char *Ptr, const Descriptor *)
template<typename T >
static void moveTy (Block *, const char *Src, char *Dst, const Descriptor *)
template<typename T >
static void ctorArrayTy (Block *, char *Ptr, bool, bool, bool, const Descriptor *D)
template<typename T >
static void dtorArrayTy (Block *, char *Ptr, const Descriptor *D)
template<typename T >
static void moveArrayTy (Block *, const char *Src, char *Dst, const Descriptor *D)
static void ctorArrayDesc (Block *B, char *Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor *D)
static void dtorArrayDesc (Block *B, char *Ptr, const Descriptor *D)
static void moveArrayDesc (Block *B, const char *Src, char *Dst, const Descriptor *D)
static void ctorRecord (Block *B, char *Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor *D)
static void dtorRecord (Block *B, char *Ptr, const Descriptor *D)
static void moveRecord (Block *B, const char *Src, char *Dst, const Descriptor *D)
static BlockCtorFn getCtorPrim (PrimType Type)
static BlockDtorFn getDtorPrim (PrimType Type)
static BlockMoveFn getMovePrim (PrimType Type)
static BlockCtorFn getCtorArrayPrim (PrimType Type)
static BlockDtorFn getDtorArrayPrim (PrimType Type)
static BlockMoveFn getMoveArrayPrim (PrimType Type)
Function Documentation
ctorArrayDesc()
static void ctorArrayDesc (Block * B, char * Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor * D) static
Definition at line 67 of file Descriptor.cpp.
References clang::interp::Descriptor::CtorFn, clang::interp::Descriptor::ElemDesc, clang::interp::Descriptor::getAllocSize(), clang::interp::Descriptor::getNumElems(), clang::interp::Descriptor::IsConst, and clang::interp::Descriptor::IsMutable.
ctorArrayTy()
template<typename T > static void ctorArrayTy (Block * , char * Ptr, bool , bool , bool , const Descriptor * D) static
Definition at line 38 of file Descriptor.cpp.
References clang::interp::Descriptor::getNumElems(), and clang::interp::NE().
Referenced by getCtorArrayPrim().
ctorRecord()
static void ctorRecord (Block * B, char * Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor * D) static
Definition at line 130 of file Descriptor.cpp.
References clang::interp::Record::bases(), clang::interp::Block::Desc, clang::interp::Descriptor::ElemRecord, clang::interp::Record::fields(), clang::interp::Record::isUnion(), clang::interp::InlineDescriptor::Offset, V, and clang::interp::Record::virtual_bases().
ctorTy()
template<typename T > static void ctorTy (Block * , char * Ptr, bool , bool , bool , const Descriptor *) static
Definition at line 21 of file Descriptor.cpp.
Referenced by getCtorPrim().
dtorArrayDesc()
static void dtorArrayDesc (Block * B, char * Ptr, const Descriptor * D) static
Definition at line 93 of file Descriptor.cpp.
References clang::interp::Descriptor::DtorFn, clang::interp::Descriptor::ElemDesc, clang::interp::Descriptor::getAllocSize(), and clang::interp::Descriptor::getNumElems().
dtorArrayTy()
template<typename T > static void dtorArrayTy (Block * , char * Ptr, const Descriptor * D) static
Definition at line 46 of file Descriptor.cpp.
References clang::interp::Descriptor::getNumElems(), and clang::interp::NE().
Referenced by getDtorArrayPrim().
dtorRecord()
static void dtorRecord (Block * B, char * Ptr, const Descriptor * D) static
Definition at line 154 of file Descriptor.cpp.
References clang::interp::Record::bases(), clang::interp::Descriptor::ElemRecord, clang::interp::Record::fields(), and clang::interp::Record::virtual_bases().
dtorTy()
template<typename T > static void dtorTy (Block * , char * Ptr, const Descriptor *) static
Definition at line 26 of file Descriptor.cpp.
Referenced by emitGlobalDtorWithCXAAtExit(), and getDtorPrim().
getCtorArrayPrim()
static BlockCtorFn getCtorArrayPrim (PrimType Type) static
Definition at line 201 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, and ctorArrayTy().
getCtorPrim()
static BlockCtorFn getCtorPrim (PrimType Type) static
Definition at line 179 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, ctorTy(), and clang::interp::PT_Float.
getDtorArrayPrim()
static BlockDtorFn getDtorArrayPrim (PrimType Type) static
Definition at line 205 of file Descriptor.cpp.
References dtorArrayTy(), and TYPE_SWITCH.
getDtorPrim()
static BlockDtorFn getDtorPrim (PrimType Type) static
Definition at line 188 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, dtorTy(), and clang::interp::PT_Float.
getMoveArrayPrim()
static BlockMoveFn getMoveArrayPrim (PrimType Type) static
Definition at line 210 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, and moveArrayTy().
getMovePrim()
static BlockMoveFn getMovePrim (PrimType Type) static
Definition at line 197 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, and moveTy().
moveArrayDesc()
static void moveArrayDesc (Block * B, const char * Src, char * Dst, const Descriptor * D) static
Definition at line 108 of file Descriptor.cpp.
References clang::interp::Descriptor::ElemDesc, clang::interp::Descriptor::getAllocSize(), clang::interp::Descriptor::getNumElems(), and clang::interp::Descriptor::MoveFn.
moveArrayTy()
template<typename T > static void moveArrayTy (Block * , const char * Src, char * Dst, const Descriptor * D) static
Definition at line 58 of file Descriptor.cpp.
References clang::interp::Descriptor::getNumElems(), and clang::interp::NE().
Referenced by getMoveArrayPrim().
moveRecord()
static void moveRecord (Block * B, const char * Src, char * Dst, const Descriptor * D) static
Definition at line 167 of file Descriptor.cpp.
References clang::interp::Descriptor::ElemRecord, and clang::interp::Record::fields().
moveTy()
template<typename T > static void moveTy (Block * , const char * Src, char * Dst, const Descriptor *) static
Definition at line 31 of file Descriptor.cpp.
Referenced by getMovePrim().