clang: lib/StaticAnalyzer/Checkers/ErrnoChecker.cpp File Reference
ErrnoChecker.cpp File Reference
#include "ErrnoModeling.h"
#include "clang/AST/ParentMapContext.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
#include "llvm/ADT/STLExtras.h"
#include <optional>
Functions
static ProgramStateRef setErrnoStateIrrelevant (ProgramStateRef State)
static bool isInCondition (const Stmt *S, CheckerContext &C)
Check if a statement (expression) or an ancestor of it is in a condition part of a (conditional, loop, switch) statement.
Function Documentation
isInCondition()
static bool isInCondition (const Stmt * S, CheckerContext & C) static
Check if a statement (expression) or an ancestor of it is in a condition part of a (conditional, loop, switch) statement.
Definition at line 71 of file ErrnoChecker.cpp.
References clang::C, clang::cast(), clang::DynTypedNodeList::empty(), and clang::ParentMapContext::getParents().
setErrnoStateIrrelevant()
static ProgramStateRef setErrnoStateIrrelevant (ProgramStateRef State) static
Definition at line 65 of file ErrnoChecker.cpp.
References clang::ento::errno_modeling::Irrelevant, and clang::ento::errno_modeling::setErrnoState().