clang: lib/Basic/FileManager.cpp File Reference
FileManager.cpp File Reference
#include "clang/Basic/FileManager.h"
#include "clang/Basic/FileSystemStatCache.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "file-search"
Functions
ALWAYS_ENABLED_STATISTIC (NumDirLookups, "Number of directory lookups.")
ALWAYS_ENABLED_STATISTIC (NumFileLookups, "Number of file lookups.")
ALWAYS_ENABLED_STATISTIC (NumDirCacheMisses, "Number of directory cache misses.")
ALWAYS_ENABLED_STATISTIC (NumFileCacheMisses, "Number of file cache misses.")
static llvm::Expected< DirectoryEntryRef > getDirectoryFromFile (FileManager &FileMgr, StringRef Filename, bool CacheFailure)
Retrieve the directory that the given file name resides in.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "file-search"
Definition at line 40 of file FileManager.cpp.
Function Documentation
ALWAYS_ENABLED_STATISTIC() [1/4]
ALWAYS_ENABLED_STATISTIC (NumDirCacheMisses , "Number of directory cache misses.")
ALWAYS_ENABLED_STATISTIC() [2/4]
ALWAYS_ENABLED_STATISTIC (NumDirLookups , "Number of directory lookups.")
ALWAYS_ENABLED_STATISTIC() [3/4]
ALWAYS_ENABLED_STATISTIC (NumFileCacheMisses , "Number of file cache misses.")
ALWAYS_ENABLED_STATISTIC() [4/4]
ALWAYS_ENABLED_STATISTIC (NumFileLookups , "Number of file lookups.")
getDirectoryFromFile()
static llvm::Expected< DirectoryEntryRef > getDirectoryFromFile (FileManager & FileMgr, StringRef Filename, bool CacheFailure) static
Retrieve the directory that the given file name resides in.
Filename can point to either a real file or a virtual file.
Definition at line 74 of file FileManager.cpp.
References Filename, clang::FileManager::getDirectoryRef(), and clang::make_error_code().
Referenced by clang::FileManager::getFileRef(), and clang::FileManager::getVirtualFileRef().