clang: lib/Frontend/InitPreprocessor.cpp File Reference
InitPreprocessor.cpp File Reference
#include "clang/Basic/FileManager.h"
#include "clang/Basic/HLSLRuntime.h"
#include "clang/Basic/MacroBuilder.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/SyncScope.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Version.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/FrontendOptions.h"
#include "clang/Frontend/Utils.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Serialization/ASTReader.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "clang/Basic/OpenCLExtensions.def"
Macros
#define OPENCL_GENERIC_EXTENSION(Ext, ...)
#define TOSTR2(X)
#define TOSTR(X)
#define DEFINE_LOCK_FREE_MACRO(TYPE, Type)
Functions
static bool MacroBodyEndsInBackslash (StringRef MacroBody)
static void DefineBuiltinMacro (MacroBuilder &Builder, StringRef Macro, DiagnosticsEngine &Diags)
static void AddImplicitInclude (MacroBuilder &Builder, StringRef File)
AddImplicitInclude - Add an implicit #include of the specified file to the predefines buffer.
static void AddImplicitIncludeMacros (MacroBuilder &Builder, StringRef File)
static void AddImplicitIncludePCH (MacroBuilder &Builder, Preprocessor &PP, const PCHContainerReader &PCHContainerRdr, StringRef ImplicitIncludePCH)
Add an implicit #include using the original file used to generate a PCH file.
template<typename T >
static T PickFP (const llvm::fltSemantics *Sem, T IEEEHalfVal, T IEEESingleVal, T IEEEDoubleVal, T X87DoubleExtendedVal, T PPCDoubleDoubleVal, T IEEEQuadVal)
PickFP - This is used to pick a value based on the FP semantics of the specified FP model.
static void DefineFloatMacros (MacroBuilder &Builder, StringRef Prefix, const llvm::fltSemantics *Sem, StringRef Ext)
static void DefineTypeSize (const Twine &MacroName, unsigned TypeWidth, StringRef ValSuffix, bool isSigned, MacroBuilder &Builder)
DefineTypeSize - Emit a macro to the predefines buffer that declares a macro named MacroName with the max value for a type with width 'TypeWidth' a signedness of 'isSigned' and with a value suffix of 'ValSuffix' (e.g.
static void DefineTypeSize (const Twine &MacroName, TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
DefineTypeSize - An overloaded helper that uses TargetInfo to determine the width, suffix, and signedness of the given type.
static void DefineFmt (const Twine &Prefix, TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineType (const Twine &MacroName, TargetInfo::IntType Ty, MacroBuilder &Builder)
static void DefineTypeWidth (const Twine &MacroName, TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineTypeSizeof (StringRef MacroName, unsigned BitWidth, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineTypeSizeAndWidth (const Twine &Prefix, TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineExactWidthIntType (TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineExactWidthIntTypeSize (TargetInfo::IntType Ty, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineLeastWidthIntType (unsigned TypeWidth, bool IsSigned, const TargetInfo &TI, MacroBuilder &Builder)
static void DefineFastIntType (unsigned TypeWidth, bool IsSigned, const TargetInfo &TI, MacroBuilder &Builder)
static const char * getLockFreeValue (unsigned TypeWidth, const TargetInfo &TI)
Get the value the ATOMIC_*_LOCK_FREE macro should have for a type with the specified properties.
static void AddObjCXXARCLibstdcxxDefines (const LangOptions &LangOpts, MacroBuilder &Builder)
Add definitions required for a smooth interaction between Objective-C++ automated reference counting and libstdc++ (4.2).
static void InitializeStandardPredefinedMacros (const TargetInfo &TI, const LangOptions &LangOpts, const FrontendOptions &FEOpts, MacroBuilder &Builder)
static void InitializeCPlusPlusFeatureTestMacros (const LangOptions &LangOpts, MacroBuilder &Builder)
Initialize the predefined C++ language feature test macros defined in ISO/IEC JTC1/SC22/WG21 (C++) SD-6: "SG10 Feature Test Recommendations".
void InitializeOpenCLFeatureTestMacros (const TargetInfo &TI, const LangOptions &Opts, MacroBuilder &Builder)
InitializeOpenCLFeatureTestMacros - Define OpenCL macros based on target settings and language version.
static void InitializePredefinedMacros (const TargetInfo &TI, const LangOptions &LangOpts, const FrontendOptions &FEOpts, const PreprocessorOptions &PPOpts, MacroBuilder &Builder)
Macro Definition Documentation
DEFINE_LOCK_FREE_MACRO
#define DEFINE_LOCK_FREE_MACRO (TYPE, Type)
Value:
  Builder.defineMacro(Prefix + #TYPE "_LOCK_FREE",                             \
                      getLockFreeValue(TI.get##Type##Width(), TI));
Referenced by InitializePredefinedMacros().
OPENCL_GENERIC_EXTENSION
#define OPENCL_GENERIC_EXTENSION (Ext, ...)
Value:
  defineOpenCLExtMacro(#Ext, __VA_ARGS__);
TOSTR
#define TOSTR (X)
Value:
TOSTR2(X)
Referenced by InitializePredefinedMacros().
TOSTR2
#define TOSTR2 (X)
Value:
#X
Function Documentation
AddImplicitInclude()
static void AddImplicitInclude (MacroBuilder & Builder, StringRef File) static
AddImplicitInclude - Add an implicit #include of the specified file to the predefines buffer.
As these includes are generated by -include arguments the header search logic is going to search relatively to the current working directory.
Definition at line 70 of file InitPreprocessor.cpp.
References clang::File.
Referenced by AddImplicitIncludePCH(), and clang::InitializePreprocessor().
AddImplicitIncludeMacros()
static void AddImplicitIncludeMacros (MacroBuilder & Builder, StringRef File) static
Definition at line 74 of file InitPreprocessor.cpp.
References clang::File.
Referenced by clang::InitializePreprocessor().
AddImplicitIncludePCH()
static void AddImplicitIncludePCH (MacroBuilder & Builder, Preprocessor & PP, const PCHContainerReader & PCHContainerRdr, StringRef ImplicitIncludePCH) static
Add an implicit #include using the original file used to generate a PCH file.
Definition at line 82 of file InitPreprocessor.cpp.
References AddImplicitInclude(), clang::Preprocessor::getDiagnostics(), clang::Preprocessor::getFileManager(), and clang::ASTReader::getOriginalSourceFile().
Referenced by clang::InitializePreprocessor().
AddObjCXXARCLibstdcxxDefines()
static void AddObjCXXARCLibstdcxxDefines (const LangOptions & LangOpts, MacroBuilder & Builder) static
Add definitions required for a smooth interaction between Objective-C++ automated reference counting and libstdc++ (4.2).
Definition at line 316 of file InitPreprocessor.cpp.
References clang::Result.
Referenced by clang::InitializePreprocessor().
DefineBuiltinMacro()
static void DefineBuiltinMacro (MacroBuilder & Builder, StringRef Macro, DiagnosticsEngine & Diags) static
Definition at line 41 of file InitPreprocessor.cpp.
References MacroBodyEndsInBackslash(), and clang::DiagnosticsEngine::Report().
Referenced by clang::InitializePreprocessor().
DefineExactWidthIntType()
static void DefineExactWidthIntType (TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 220 of file InitPreprocessor.cpp.
References DefineFmt(), DefineType(), clang::TargetInfo::getInt16Type(), clang::TargetInfo::getInt64Type(), clang::TargetInfo::getTypeConstantSuffix(), clang::TargetInfo::getTypeWidth(), clang::TargetInfo::getUInt16Type(), clang::TargetInfo::getUInt64Type(), and clang::TargetInfo::isTypeSigned().
Referenced by InitializePredefinedMacros().
DefineExactWidthIntTypeSize()
static void DefineExactWidthIntTypeSize (TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 245 of file InitPreprocessor.cpp.
References DefineTypeSize(), clang::TargetInfo::getInt64Type(), clang::TargetInfo::getTypeWidth(), clang::TargetInfo::getUInt64Type(), and clang::TargetInfo::isTypeSigned().
Referenced by InitializePredefinedMacros().
DefineFastIntType()
static void DefineFastIntType (unsigned TypeWidth, bool IsSigned, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 280 of file InitPreprocessor.cpp.
References DefineFmt(), DefineType(), DefineTypeSize(), DefineTypeSizeAndWidth(), and clang::TargetInfo::getLeastIntTypeByWidth().
Referenced by InitializePredefinedMacros().
DefineFloatMacros()
static void DefineFloatMacros (MacroBuilder & Builder, StringRef Prefix, const llvm::fltSemantics * Sem, StringRef Ext) static
Definition at line 114 of file InitPreprocessor.cpp.
References PickFP().
Referenced by InitializePredefinedMacros().
DefineFmt()
static void DefineFmt (const Twine & Prefix, TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 184 of file InitPreprocessor.cpp.
References clang::TargetInfo::getTypeFormatModifier(), and clang::TargetInfo::isTypeSigned().
Referenced by DefineExactWidthIntType(), DefineFastIntType(), DefineLeastWidthIntType(), and InitializePredefinedMacros().
DefineLeastWidthIntType()
static void DefineLeastWidthIntType (unsigned TypeWidth, bool IsSigned, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 262 of file InitPreprocessor.cpp.
References DefineFmt(), DefineType(), DefineTypeSize(), DefineTypeSizeAndWidth(), and clang::TargetInfo::getLeastIntTypeByWidth().
Referenced by InitializePredefinedMacros().
DefineType()
static void DefineType (const Twine & MacroName, TargetInfo::IntType Ty, MacroBuilder & Builder) static
Definition at line 194 of file InitPreprocessor.cpp.
References clang::TargetInfo::getTypeName().
Referenced by DefineExactWidthIntType(), DefineFastIntType(), DefineLeastWidthIntType(), and InitializePredefinedMacros().
DefineTypeSize() [1/2]
static void DefineTypeSize (const Twine & MacroName, TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
DefineTypeSize - An overloaded helper that uses TargetInfo to determine the width, suffix, and signedness of the given type.
Definition at line 178 of file InitPreprocessor.cpp.
References DefineTypeSize(), clang::TargetInfo::getTypeConstantSuffix(), clang::TargetInfo::getTypeWidth(), and clang::TargetInfo::isTypeSigned().
DefineTypeSize() [2/2]
static void DefineTypeSize (const Twine & MacroName, unsigned TypeWidth, StringRef ValSuffix, bool isSigned, MacroBuilder & Builder) static
DefineTypeSize - Emit a macro to the predefines buffer that declares a macro named MacroName with the max value for a type with width 'TypeWidth' a signedness of 'isSigned' and with a value suffix of 'ValSuffix' (e.g.
LL).
Definition at line 168 of file InitPreprocessor.cpp.
References toString().
Referenced by DefineExactWidthIntTypeSize(), DefineFastIntType(), DefineLeastWidthIntType(), DefineTypeSize(), DefineTypeSizeAndWidth(), and InitializePredefinedMacros().
DefineTypeSizeAndWidth()
static void DefineTypeSizeAndWidth (const Twine & Prefix, TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 213 of file InitPreprocessor.cpp.
References DefineTypeSize(), and DefineTypeWidth().
Referenced by DefineFastIntType(), DefineLeastWidthIntType(), and InitializePredefinedMacros().
DefineTypeSizeof()
static void DefineTypeSizeof (StringRef MacroName, unsigned BitWidth, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 204 of file InitPreprocessor.cpp.
References clang::TargetInfo::getCharWidth().
Referenced by InitializePredefinedMacros().
DefineTypeWidth()
static void DefineTypeWidth (const Twine & MacroName, TargetInfo::IntType Ty, const TargetInfo & TI, MacroBuilder & Builder) static
Definition at line 199 of file InitPreprocessor.cpp.
References clang::TargetInfo::getTypeWidth().
Referenced by DefineTypeSizeAndWidth().
getLockFreeValue()
static const char * getLockFreeValue (unsigned TypeWidth, const TargetInfo & TI) static
Get the value the ATOMIC_*_LOCK_FREE macro should have for a type with the specified properties.
Definition at line 302 of file InitPreprocessor.cpp.
References clang::TargetInfo::hasBuiltinAtomic().
Referenced by InitializePredefinedMacros().
InitializeCPlusPlusFeatureTestMacros()
static void InitializeCPlusPlusFeatureTestMacros (const LangOptions & LangOpts, MacroBuilder & Builder) static
Initialize the predefined C++ language feature test macros defined in ISO/IEC JTC1/SC22/WG21 (C++) SD-6: "SG10 Feature Test Recommendations".
Definition at line 608 of file InitPreprocessor.cpp.
Referenced by InitializePredefinedMacros().
InitializeOpenCLFeatureTestMacros()
void InitializeOpenCLFeatureTestMacros (const TargetInfo & TI, const LangOptions & Opts, MacroBuilder & Builder)
InitializeOpenCLFeatureTestMacros - Define OpenCL macros based on target settings and language version.
Definition at line 731 of file InitPreprocessor.cpp.
References clang::TargetInfo::getSupportedOpenCLOpts(), clang::TargetInfo::hasFeatureEnabled(), and clang::OpenCLOptions::isOpenCLOptionAvailableIn().
Referenced by InitializePredefinedMacros().
InitializePredefinedMacros()
static void InitializePredefinedMacros (const TargetInfo & TI, const LangOptions & LangOpts, const FrontendOptions & FEOpts, const PreprocessorOptions & PPOpts, MacroBuilder & Builder) static
Definition at line 752 of file InitPreprocessor.cpp.
References clang::AtomicScopeOpenCLModel::AllSVMDevices, Bool, DEFINE_LOCK_FREE_MACRO, DefineExactWidthIntType(), DefineExactWidthIntTypeSize(), DefineFastIntType(), DefineFloatMacros(), DefineFmt(), DefineLeastWidthIntType(), DefineType(), DefineTypeSize(), DefineTypeSizeAndWidth(), DefineTypeSizeof(), clang::AtomicScopeOpenCLModel::Device, clang::TargetInfo::getBoolWidth(), clang::TargetInfo::getChar16Type(), clang::TargetInfo::getChar32Type(), clang::TargetInfo::getCharWidth(), clang::getClangFullCPPVersion(), clang::getClangFullRepositoryVersion(), clang::TargetInfo::getDoubleFormat(), clang::TargetInfo::getDoubleWidth(), clang::TargetInfo::getFloatFormat(), clang::TargetInfo::getFloatWidth(), clang::TargetInfo::getHalfFormat(), clang::TargetInfo::getIntMaxType(), clang::TargetInfo::getIntPtrType(), clang::TargetInfo::getIntWidth(), clang::ObjCRuntime::getKind(), getLockFreeValue(), clang::TargetInfo::getLongDoubleFormat(), clang::TargetInfo::getLongDoubleWidth(), clang::TargetInfo::getLongLongWidth(), clang::TargetInfo::getLongWidth(), clang::TargetInfo::getMaxBitIntWidth(), clang::TargetInfo::getPointerWidth(), clang::TargetInfo::getPtrDiffType(), clang::TargetInfo::getShortWidth(), clang::TargetInfo::getSigAtomicType(), clang::TargetInfo::getSizeType(), clang::TargetInfo::getSuitableAlign(), clang::TargetInfo::getTargetDefines(), clang::TargetInfo::getTriple(), clang::TargetInfo::getTypeConstantSuffix(), clang::TargetInfo::getTypeWidth(), clang::TargetInfo::getUIntMaxType(), clang::TargetInfo::getUIntPtrType(), clang::TargetInfo::getUserLabelPrefix(), clang::ObjCRuntime::getVersion(), clang::TargetInfo::getWCharType(), clang::TargetInfo::getWIntType(), clang::ObjCRuntime::GNUstep, clang::LangOptions::hasDWARFExceptions(), clang::TargetInfo::hasFloat16Type(), clang::TargetInfo::hasInt128Type(), clang::LangOptions::hasSEHExceptions(), clang::LangOptions::hasSjLjExceptions(), InitializeCPlusPlusFeatureTestMacros(), InitializeOpenCLFeatureTestMacros(), clang::TargetInfo::isBigEndian(), clang::ObjCRuntime::isNeXTFamily(), clang::ObjCRuntime::isNonFragile(), clang::TargetInfo::isTypeSigned(), clang::Long, clang::LongLong, clang::LangOptions::NonGC, clang::LangOptions::ObjCRuntime, clang::ObjCRuntime::ObjFW, clang::FrontendOptions::ProgramAction, clang::frontend::RewriteObjC, clang::PreprocessorOptions::SetUpStaticAnalyzer, clang::Short, clang::LangOptions::SSPOn, clang::LangOptions::SSPReq, clang::LangOptions::SSPStrong, clang::AtomicScopeOpenCLModel::SubGroup, TOSTR, clang::TargetInfo::useSignedCharForObjCBool(), and clang::AtomicScopeOpenCLModel::WorkGroup.
Referenced by clang::InitializePreprocessor().
InitializeStandardPredefinedMacros()
static void InitializeStandardPredefinedMacros (const TargetInfo & TI, const LangOptions & LangOpts, const FrontendOptions & FEOpts, MacroBuilder & Builder) static
Definition at line 371 of file InitPreprocessor.cpp.
References clang::TargetInfo::getCharWidth(), clang::TargetInfo::getNewAlign(), clang::TargetInfo::getSizeType(), clang::TargetInfo::getTriple(), clang::TargetInfo::getTypeConstantSuffix(), clang::LangOptions::GPUDefaultStream, clang::TargetInfo::hasHIPImageSupport(), clang::TargetInfo::isLittleEndian(), clang::LangOptions::SYCL_2017, and clang::LangOptions::SYCL_2020.
Referenced by clang::InitializePreprocessor().
MacroBodyEndsInBackslash()
static bool MacroBodyEndsInBackslash (StringRef MacroBody) static
Definition at line 32 of file InitPreprocessor.cpp.
References clang::isWhitespace().
Referenced by DefineBuiltinMacro().
PickFP()
template<typename T > static T PickFP (const llvm::fltSemantics * Sem, T IEEEHalfVal, T IEEESingleVal, T IEEEDoubleVal, T X87DoubleExtendedVal, T PPCDoubleDoubleVal, T IEEEQuadVal) static
PickFP - This is used to pick a value based on the FP semantics of the specified FP model.
Definition at line 97 of file InitPreprocessor.cpp.
Referenced by DefineFloatMacros().