clang: lib/AST/Interp/InterpFrame.cpp File Reference
InterpFrame.cpp File Reference
#include "InterpFrame.h"
#include "Boolean.h"
#include "Floating.h"
#include "Function.h"
#include "InterpStack.h"
#include "InterpState.h"
#include "Pointer.h"
#include "PrimType.h"
#include "Program.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclCXX.h"
Functions
template<typename T >
static void print (llvm::raw_ostream &OS, const T &V, ASTContext &, QualType)
template<>
void print (llvm::raw_ostream &OS, const Pointer &P, ASTContext &Ctx, QualType Ty)
Function Documentation
print() [1/2]
template<> void print (llvm::raw_ostream & OS, const Pointer & P, ASTContext & Ctx, QualType Ty)
Definition at line 94 of file InterpFrame.cpp.
References clang::ASTContext::getPrintingPolicy(), clang::Type::isReferenceType(), and P.
print() [2/2]
template<typename T > static void print (llvm::raw_ostream & OS, const T & V, ASTContext & , QualType) static
Definition at line 89 of file InterpFrame.cpp.
References V.
Referenced by clang::interp::InterpFrame::describe(), clang::CodeGen::CGBitFieldInfo::dump(), clang::CodeGen::CGRecordLayout::dump(), clang::Qualifiers::getAsString(), clang::detail::MacroExpansionRangeRecorder::MacroExpands(), and clang::QualType::print().