clang: lib/Interpreter/Value.cpp File Reference
Value.cpp File Reference
#include "clang/Interpreter/Value.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Type.h"
#include "clang/Interpreter/Interpreter.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_os_ostream.h"
#include <cassert>
#include <cstdint>
#include <utility>
Macros
#define X(type, name)
Functions
static Value::Kind ConvertQualTypeToKind (const ASTContext &Ctx, QualType QT)
Macro Definition Documentation
X
#define X (type, name)
Value:
  case BuiltinType::name:                                                      \
    return Value::K_##name;
Function Documentation
ConvertQualTypeToKind()
static Value::Kind ConvertQualTypeToKind (const ASTContext & Ctx, QualType QT) static
Definition at line 100 of file Value.cpp.
References clang::Type::castAs(), clang::Type::getAs(), clang::BuiltinType::getKind(), clang::ASTContext::hasSameType(), REPL_BUILTIN_TYPES, and clang::ASTContext::VoidTy.
Referenced by clang::Value::Value().