clang: lib/Analysis/IssueHash.cpp File Reference
IssueHash.cpp File Reference
#include "clang/Analysis/IssueHash.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/Path.h"
#include <functional>
#include <optional>
#include <sstream>
#include <string>
Functions
static std::string GetSignature (const FunctionDecl *Target)
static std::string GetEnclosingDeclContextSignature (const Decl *D)
static StringRef GetNthLineOfFile (std::optional< llvm::MemoryBufferRef > Buffer, int Line)
static std::string NormalizeLine (const SourceManager &SM, const FullSourceLoc &L, const LangOptions &LangOpts)
static llvm::SmallString< 32 > GetMD5HashOfContent (StringRef Content)
Function Documentation
GetEnclosingDeclContextSignature()
static std::string GetEnclosingDeclContextSignature (const Decl * D) static
Definition at line 89 of file IssueHash.cpp.
References GetSignature().
GetMD5HashOfContent()
static llvm::SmallString< 32 > GetMD5HashOfContent (StringRef Content) static
Definition at line 173 of file IssueHash.cpp.
GetNthLineOfFile()
static StringRef GetNthLineOfFile (std::optional< llvm::MemoryBufferRef > Buffer, int Line) static
Definition at line 125 of file IssueHash.cpp.
Referenced by NormalizeLine().
GetSignature()
static std::string GetSignature (const FunctionDecl * Target) static
Definition at line 32 of file IssueHash.cpp.
References clang::FunctionDecl::getTemplateInstantiationPattern(), clang::RQ_LValue, and clang::RQ_RValue.
Referenced by GetEnclosingDeclContextSignature().
NormalizeLine()
static std::string NormalizeLine (const SourceManager & SM, const FullSourceLoc & L, const LangOptions & LangOpts) static
Definition at line 137 of file IssueHash.cpp.
References clang::FullSourceLoc::getExpansionLineNumber(), clang::FullSourceLoc::getFileID(), clang::Token::getLength(), clang::Token::getLocation(), GetNthLineOfFile(), clang::Token::isAtStartOfLine(), clang::Lexer::LexFromRawLexer(), and SM.