clang: lib/Frontend/LayoutOverrideSource.cpp File Reference
LayoutOverrideSource.cpp File Reference
#include "clang/Frontend/LayoutOverrideSource.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/Basic/CharInfo.h"
#include "llvm/Support/raw_ostream.h"
#include <fstream>
#include <string>
Functions
static std::string parseName (StringRef S)
Parse a simple identifier.
static bool parseUnsigned (StringRef &S, unsigned long long &ULL)
Parse an unsigned integer and move S to the next non-digit character.
Function Documentation
parseName()
static std::string parseName (StringRef S) static
Parse a simple identifier.
Definition at line 19 of file LayoutOverrideSource.cpp.
References clang::isAsciiIdentifierContinue(), clang::isAsciiIdentifierStart(), and Offset.
Referenced by clang::LayoutOverrideSource::LayoutOverrideSource().
parseUnsigned()
static bool parseUnsigned (StringRef & S, unsigned long long & ULL) static
Parse an unsigned integer and move S to the next non-digit character.
Definition at line 31 of file LayoutOverrideSource.cpp.
References clang::isDigit().
Referenced by clang::LayoutOverrideSource::LayoutOverrideSource().