clang: lib/Driver/ToolChains/MinGW.cpp File Reference
MinGW.cpp File Reference
#include "MinGW.h"
#include "CommonArgs.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <system_error>
Functions
static bool isCrossCompiling (const llvm::Triple &T, bool RequireArchMatch)
static bool findGccVersion (StringRef LibDir, std::string &GccLibDir, std::string &Ver, toolchains::Generic_GCC::GCCVersion &Version)
static llvm::Triple getLiteralTriple (const Driver &D, const llvm::Triple &T)
static llvm::ErrorOr< std::string > findGcc (const llvm::Triple &LiteralTriple, const llvm::Triple &T)
static llvm::ErrorOr< std::string > findClangRelativeSysroot (const Driver &D, const llvm::Triple &LiteralTriple, const llvm::Triple &T, std::string &SubdirName)
static bool testTriple (const Driver &D, const llvm::Triple &Triple, const ArgList &Args)
static llvm::Triple adjustTriple (const Driver &D, const llvm::Triple &Triple, const ArgList &Args)
Function Documentation
adjustTriple()
static llvm::Triple adjustTriple (const Driver & D, const llvm::Triple & Triple, const ArgList & Args) static
Definition at line 782 of file MinGW.cpp.
References testTriple().
Referenced by clang::driver::toolchains::MinGW::fixTripleArch().
findClangRelativeSysroot()
static llvm::ErrorOr< std::string > findClangRelativeSysroot (const Driver & D, const llvm::Triple & LiteralTriple, const llvm::Triple & T, std::string & SubdirName) static
Definition at line 445 of file MinGW.cpp.
References clang::driver::Driver::getInstalledDir(), and clang::make_error_code().
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
findGcc()
static llvm::ErrorOr< std::string > findGcc (const llvm::Triple & LiteralTriple, const llvm::Triple & T) static
Definition at line 425 of file MinGW.cpp.
References clang::make_error_code().
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
findGccVersion()
static bool findGccVersion (StringRef LibDir, std::string & GccLibDir, std::string & Ver, toolchains::Generic_GCC::GCCVersion & Version) static
Definition at line 370 of file MinGW.cpp.
References clang::driver::toolchains::Generic_GCC::GCCVersion::Parse().
getLiteralTriple()
static llvm::Triple getLiteralTriple (const Driver & D, const llvm::Triple & T) static
Definition at line 391 of file MinGW.cpp.
References clang::driver::Driver::getTargetTriple().
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
isCrossCompiling()
static bool isCrossCompiling (const llvm::Triple & T, bool RequireArchMatch) static
Definition at line 360 of file MinGW.cpp.
Referenced by clang::driver::toolchains::MinGW::AddClangSystemIncludeArgs().
testTriple()
static bool testTriple (const Driver & D, const llvm::Triple & Triple, const ArgList & Args) static
Definition at line 764 of file MinGW.cpp.
References findClangRelativeSysroot(), findGcc(), getLiteralTriple(), and clang::driver::Driver::SysRoot.
Referenced by adjustTriple().