clang: lib/Tooling/DependencyScanning/ModuleDepCollector.cpp File Reference
ModuleDepCollector.cpp File Reference
#include "clang/Tooling/DependencyScanning/ModuleDepCollector.h"
#include "clang/Basic/MakeSupport.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Tooling/DependencyScanning/DependencyScanningWorker.h"
#include "llvm/Support/BLAKE3.h"
#include "llvm/Support/StringSaver.h"
#include <optional>
Functions
static void optimizeHeaderSearchOpts (HeaderSearchOptions &Opts, ASTReader &Reader, const serialization::ModuleFile &MF)
static std::vector< std::string > splitString (std::string S, char Separator)
static bool needsModules (FrontendInputFile FIF)
static std::string getModuleContextHash (const ModuleDeps &MD, const CompilerInvocation &CI, bool EagerLoadModules)
static void forEachSubmoduleSorted (const Module *M, llvm::function_ref< void(const Module *)> F)
static StringRef makeAbsoluteAndPreferred (CompilerInstance &CI, StringRef Path, SmallVectorImpl< char > &Storage)
Function Documentation
forEachSubmoduleSorted()
static void forEachSubmoduleSorted (const Module * M, llvm::function_ref< void(const Module *)> F) static
Definition at line 498 of file ModuleDepCollector.cpp.
References clang::Module::Name, and clang::Module::submodules().
getModuleContextHash()
static std::string getModuleContextHash (const ModuleDeps & MD, const CompilerInvocation & CI, bool EagerLoadModules) static
Definition at line 258 of file ModuleDepCollector.cpp.
References clang::tooling::dependencies::ModuleDeps::ClangModuleDeps, clang::CompilerInvocation::generateCC1CommandLine(), clang::getClangFullRepositoryVersion(), toString(), clang::serialization::VERSION_MAJOR, and clang::serialization::VERSION_MINOR.
makeAbsoluteAndPreferred()
static StringRef makeAbsoluteAndPreferred (CompilerInstance & CI, StringRef Path, SmallVectorImpl< char > & Storage) static
Definition at line 606 of file ModuleDepCollector.cpp.
References clang::CompilerInstance::getFileManager(), and clang::FileManager::makeAbsolutePath().
needsModules()
static bool needsModules (FrontendInputFile FIF) static
Definition at line 219 of file ModuleDepCollector.cpp.
References clang::Asm, clang::FrontendInputFile::getKind(), clang::InputKind::getLanguage(), clang::LLVM_IR, and clang::Unknown.
Referenced by clang::tooling::dependencies::ModuleDepCollector::applyDiscoveredDependencies().
optimizeHeaderSearchOpts()
static void optimizeHeaderSearchOpts (HeaderSearchOptions & Opts, ASTReader & Reader, const serialization::ModuleFile & MF) static
Definition at line 23 of file ModuleDepCollector.cpp.
References clang::tooling::Import, clang::serialization::ModuleFile::Imports, clang::serialization::ModuleFile::SearchPathUsage, clang::HeaderSearchOptions::UserEntries, and Visited.
splitString()
static std::vector< std::string > splitString (std::string S, char Separator) static
Definition at line 46 of file ModuleDepCollector.cpp.
References clang::Result.