clang: clang::tooling::internal Namespace Reference
clang::tooling::internal Namespace Reference
Classes
struct AreBaseOf
A type trait that returns true when the given type list contains types that derive from Base.
struct AreBaseOf< Base, T >
struct HasBaseOf
A type trait that returns true when the given type list has at least one type whose base is the given base type.
struct HasBaseOf< Base, T >
struct RangeLessThan
Functions
llvm::Expected< std::unique_ptr< ToolExecutor > > createExecutorFromCommandLineArgsImpl (int &argc, const char **argv, llvm::cl::OptionCategory &Category, const char *Overview=nullptr)
llvm::Error findError ()
void ignoreError ()
template<typename FirstT , typename... RestT>
void ignoreError (Expected< FirstT > &First, Expected< RestT > &... Rest)
template<typename FirstT , typename... RestT>
llvm::Error findError (Expected< FirstT > &First, Expected< RestT > &... Rest)
Scans the tuple and returns a valid Error if any of the values are invalid.
template<typename RuleType , typename... RequirementTypes, size_t... Is>
void invokeRuleAfterValidatingRequirements (RefactoringResultConsumer &Consumer, RefactoringRuleContext &Context, const std::tuple< RequirementTypes... > &Requirements, std::index_sequence< Is... >)
void visitRefactoringOptionsImpl (RefactoringOptionVisitor &)
template<typename FirstT , typename... RestT>
void visitRefactoringOptionsImpl (RefactoringOptionVisitor &Visitor, const FirstT &First, const RestT &... Rest)
Scans the list of requirements in a rule and visits all the refactoring options that are used by all the requirements.
template<typename... RequirementTypes, size_t... Is>
void visitRefactoringOptions (RefactoringOptionVisitor &Visitor, const std::tuple< RequirementTypes... > &Requirements, std::index_sequence< Is... >)
static bool locationCallLessThan (const LocationCall *LHS, const LocationCall *RHS)
Function Documentation
createExecutorFromCommandLineArgsImpl()
llvm::Expected< std::unique_ptr< ToolExecutor > > clang::tooling::internal::createExecutorFromCommandLineArgsImpl (int & argc, const char ** argv, llvm::cl::OptionCategory & Category, const char * Overview = nullptr)
Definition at line 58 of file Execution.cpp.
References Category, clang::tooling::CommonOptionsParser::create(), and clang::tooling::ExecutorName.
Referenced by clang::tooling::createExecutorFromCommandLineArgs().
findError() [1/2]
llvm::Error clang::tooling::internal::findError () inline
Definition at line 24 of file RefactoringActionRulesInternal.h.
Referenced by findError(), and invokeRuleAfterValidatingRequirements().
findError() [2/2]
template<typename FirstT , typename... RestT> llvm::Error clang::tooling::internal::findError (Expected< FirstT > & First, Expected< RestT > &... Rest)
Scans the tuple and returns a valid Error if any of the values are invalid.
Definition at line 38 of file RefactoringActionRulesInternal.h.
References findError(), clang::First, and ignoreError().
ignoreError() [1/2]
void clang::tooling::internal::ignoreError () inline
Definition at line 26 of file RefactoringActionRulesInternal.h.
Referenced by findError(), and ignoreError().
ignoreError() [2/2]
template<typename FirstT , typename... RestT> void clang::tooling::internal::ignoreError (Expected< FirstT > & First, Expected< RestT > &... Rest)
Definition at line 29 of file RefactoringActionRulesInternal.h.
References clang::First, and ignoreError().
invokeRuleAfterValidatingRequirements()
template<typename RuleType , typename... RequirementTypes, size_t... Is> void clang::tooling::internal::invokeRuleAfterValidatingRequirements (RefactoringResultConsumer & Consumer, RefactoringRuleContext & Context, const std::tuple< RequirementTypes... > & Requirements, std::index_sequence< Is... >)
Definition at line 47 of file RefactoringActionRulesInternal.h.
References findError(), and clang::tooling::RefactoringResultConsumer::handleError().
locationCallLessThan()
static bool clang::tooling::internal::locationCallLessThan (const LocationCall * LHS, const LocationCall * RHS) static
Definition at line 45 of file NodeIntrospection.cpp.
References locationCallLessThan(), clang::tooling::LocationCall::name(), and clang::tooling::LocationCall::on().
Referenced by locationCallLessThan(), clang::tooling::internal::RangeLessThan::operator()(), and clang::tooling::internal::RangeLessThan::operator()().
visitRefactoringOptions()
template<typename... RequirementTypes, size_t... Is> void clang::tooling::internal::visitRefactoringOptions (RefactoringOptionVisitor & Visitor, const std::tuple< RequirementTypes... > & Requirements, std::index_sequence< Is... >)
Definition at line 87 of file RefactoringActionRulesInternal.h.
References visitRefactoringOptionsImpl().
visitRefactoringOptionsImpl() [1/2]
void clang::tooling::internal::visitRefactoringOptionsImpl (RefactoringOptionVisitor &) inline
Definition at line 66 of file RefactoringActionRulesInternal.h.
Referenced by visitRefactoringOptions(), and visitRefactoringOptionsImpl().
visitRefactoringOptionsImpl() [2/2]
template<typename FirstT , typename... RestT> void clang::tooling::internal::visitRefactoringOptionsImpl (RefactoringOptionVisitor & Visitor, const FirstT & First, const RestT &... Rest)
Scans the list of requirements in a rule and visits all the refactoring options that are used by all the requirements.
Definition at line 71 of file RefactoringActionRulesInternal.h.
References clang::First, clang::tooling::RefactoringOptionsRequirement::getRefactoringOptions(), and visitRefactoringOptionsImpl().