clang: clang::driver::tools::loongarch Namespace Reference
clang::driver::tools::loongarch Namespace Reference
Functions
void getLoongArchTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< llvm::StringRef > &Features)
StringRef getLoongArchABI (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
std::string postProcessTargetCPUString (const std::string &CPU, const llvm::Triple &Triple)
std::string getLoongArchTargetCPU (const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
Function Documentation
getLoongArchABI()
StringRef clang::driver::tools::loongarch::getLoongArchABI (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by clang::driver::tools::ClangAs::AddLoongArchTargetArgs(), clang::driver::tools::gnutools::Assembler::ConstructJob(), and clang::driver::toolchains::Linux::getDynamicLinker().
getLoongArchTargetCPU()
std::string clang::driver::tools::loongarch::getLoongArchTargetCPU (const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Definition at line 193 of file LoongArch.cpp.
References postProcessTargetCPUString().
getLoongArchTargetFeatures()
void clang::driver::tools::loongarch::getLoongArchTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< llvm::StringRef > & Features)
postProcessTargetCPUString()
std::string clang::driver::tools::loongarch::postProcessTargetCPUString (const std::string & CPU, const llvm::Triple & Triple)
Definition at line 180 of file LoongArch.cpp.
Referenced by getLoongArchTargetCPU().