clang: clang::ento::allocation_state Namespace Reference
clang::ento::allocation_state Namespace Reference
Functions
ProgramStateRef markReleased (ProgramStateRef State, SymbolRef Sym, const Expr *Origin)
std::unique_ptr< BugReporterVisitor > getInnerPointerBRVisitor (SymbolRef Sym)
This function provides an additional visitor that augments the bug report with information relevant to memory errors caused by the misuse of AF_InnerBuffer symbols.
const MemRegion * getContainerObjRegion (ProgramStateRef State, SymbolRef Sym)
'Sym' represents a pointer to the inner buffer of a container object.
Function Documentation
getContainerObjRegion()
const MemRegion * clang::ento::allocation_state::getContainerObjRegion (ProgramStateRef State, SymbolRef Sym)
'Sym' represents a pointer to the inner buffer of a container object.
This function looks up the memory region of that object in DanglingInternalBufferChecker's program state map.
Definition at line 292 of file InnerPointerChecker.cpp.
References getContainerObjRegion().
Referenced by getContainerObjRegion().
getInnerPointerBRVisitor()
std::unique_ptr< BugReporterVisitor > clang::ento::allocation_state::getInnerPointerBRVisitor (SymbolRef Sym)
This function provides an additional visitor that augments the bug report with information relevant to memory errors caused by the misuse of AF_InnerBuffer symbols.
Definition at line 288 of file InnerPointerChecker.cpp.
References getInnerPointerBRVisitor().
Referenced by getInnerPointerBRVisitor().
markReleased()
ProgramStateRef clang::ento::allocation_state::markReleased (ProgramStateRef State, SymbolRef Sym, const Expr * Origin)
Definition at line 3581 of file MallocChecker.cpp.
References markReleased().
Referenced by markReleased().