clang: clang::interp Namespace Reference
clang::interp Namespace Reference
Classes
class ArrayIndexScope
class AutoScope
Like a regular LocalScope, except that the destructors of all local variables are automatically emitted when the AutoScope is destroyed.
class Block
A memory block, either on the stack or in the heap.
class BlockScope
Scope for storage declared in a compound statement.
class Boolean
Wrapper around boolean types.
class ByteCodeEmitter
An emitter which links the program to bytecode for later use.
class ByteCodeExprGen
Compilation context for expressions.
struct ByteCodeGenError
Error thrown by the compiler.
class ByteCodeStmtGen
Compilation context for statements.
class CodePtr
Pointer into the code segment.
class Context
Holds all information required to evaluate constexpr code in a module.
class DeadBlock
Descriptor for a dead block.
class DeclScope
Scope used to handle temporaries in toplevel variable declarations.
struct Descriptor
Describes a memory block created by an allocation site.
class DestructorScope
Emits the destructors of the variables of.
class EvalEmitter
An emitter which evaluates opcodes as they are emitted.
class ExprScope
Expression scope which tracks potentially lifetime extended temporaries which are hoisted to the parent scope on exit.
class Floating
class Frame
Base class for stack frames, shared between VM and walker.
class Function
Bytecode function.
class FunctionPointer
struct InitMap
Bitfield tracking the initialisation status of elements of primitive arrays.
struct InlineDescriptor
Inline descriptor embedded in structures and arrays.
class Integral
Wrapper around numeric types.
class InterpFrame
Frame storing local variables.
class InterpStack
Stack frame storing temporaries and parameters.
class InterpState
Interpreter context.
class LabelScope
Scope managing label targets.
class LocalScope
Generic scope for local variables.
class LoopScope
Sets the context for break/continue statements.
class OptionScope
Scope used to handle initialization methods.
class Pointer
A pointer to a memory block, live or dead.
struct PrimConv
Mapping from primitive types to their representation.
struct PrimConv< PT_Bool >
struct PrimConv< PT_Float >
struct PrimConv< PT_FnPtr >
struct PrimConv< PT_Ptr >
struct PrimConv< PT_Sint16 >
struct PrimConv< PT_Sint32 >
struct PrimConv< PT_Sint64 >
struct PrimConv< PT_Sint8 >
struct PrimConv< PT_Uint16 >
struct PrimConv< PT_Uint32 >
struct PrimConv< PT_Uint64 >
struct PrimConv< PT_Uint8 >
class Program
The program contains and links the bytecode for all functions.
class Record
Structure/Class descriptor.
class RecordScope
struct Repr
struct Repr< 16, false >
struct Repr< 16, true >
struct Repr< 32, false >
struct Repr< 32, true >
struct Repr< 64, false >
struct Repr< 64, true >
struct Repr< 8, false >
struct Repr< 8, true >
class Scope
Describes a scope block.
class SourceInfo
Describes the statement/declaration an opcode was generated from.
class SourceMapper
Interface for classes which map locations to sources.
class State
Interface for the VM to interact with the AST walker's context.
class SwitchScope
class VariableScope
Scope chain managing the variable lifetimes.
Typedefs
using DeclTy = llvm::PointerUnion<const Decl *, const Expr *>
using BlockCtorFn
Invoked whenever a block is created.
using BlockDtorFn
Invoked when a block is destroyed.
using BlockMoveFn
Invoked when a block with pointers referencing it goes out of scope.
using APFloat = llvm::APFloat
using APInt = llvm::APInt
using CompareFn = llvm::function_ref<bool(ComparisonCategoryResult)>
using SourceMap = std::vector<std::pair<unsigned, SourceInfo>>
Enumerations
enum class ArithOp { Add , Sub }
enum class PushVal : bool { No , Yes }
enum class IncDecOp { Inc , Dec }
enum Opcode : uint32_t
enum PrimType : unsigned {
PT_Sint8 , PT_Uint8 , PT_Sint16 , PT_Uint16 ,
PT_Sint32 , PT_Uint32 , PT_Sint64 , PT_Uint64 ,
PT_Bool , PT_Float , PT_Ptr , PT_FnPtr
}
Enumeration of the primitive types of the VM.
Functions
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Boolean &B)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Floating F)
Floating getSwappedBytes (Floating F)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, FunctionPointer FP)
template<unsigned Bits, bool Signed>
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Integral< Bits, Signed > I)
bool CheckExtern (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if the variable has externally defined storage.
bool CheckArray (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if the array is offsetable.
bool CheckLive (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
Checks if a pointer is live and accessible.
bool CheckNull (InterpState &S, CodePtr OpPC, const Pointer &Ptr, CheckSubobjectKind CSK)
Checks if a pointer is null.
bool CheckRange (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
Checks if a pointer is in range.
bool CheckRange (InterpState &S, CodePtr OpPC, const Pointer &Ptr, CheckSubobjectKind CSK)
Checks if a field from which a pointer is going to be derived is valid.
bool CheckConst (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a pointer points to const storage.
bool CheckMutable (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a pointer points to a mutable field.
bool CheckInitialized (InterpState &S, CodePtr OpPC, const Pointer &Ptr, AccessKinds AK)
bool CheckLoad (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be loaded from a block.
bool CheckStore (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be stored in a block.
bool CheckInvoke (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a method can be invoked on an object.
bool CheckInit (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
Checks if a value can be initialized.
bool CheckCallable (InterpState &S, CodePtr OpPC, const Function *F)
Checks if a method can be called.
bool CheckCallDepth (InterpState &S, CodePtr OpPC)
Checks if calling the currently active function would exceed the allowed call depth.
bool CheckThis (InterpState &S, CodePtr OpPC, const Pointer &This)
Checks the 'this' pointer.
bool CheckPure (InterpState &S, CodePtr OpPC, const CXXMethodDecl *MD)
Checks if a method is pure virtual.
static void DiagnoseUninitializedSubobject (InterpState &S, const SourceInfo &SI, const FieldDecl *SubObjDecl)
static bool CheckFieldsInitialized (InterpState &S, CodePtr OpPC, const Pointer &BasePtr, const Record *R)
static bool CheckArrayInitialized (InterpState &S, CodePtr OpPC, const Pointer &BasePtr, const ConstantArrayType *CAT)
bool CheckCtorCall (InterpState &S, CodePtr OpPC, const Pointer &This)
Checks that all fields are initialized after a constructor call.
bool CheckFloatResult (InterpState &S, CodePtr OpPC, APFloat::opStatus Status)
Checks if the result is a floating-point operation is valid in the current context.
bool Interpret (InterpState &S, APValue &Result)
Interpreter entry point.
template<typename T >
bool ReturnValue (const T &V, APValue &R)
Convert a value to an APValue.
template<typename LT , typename RT >
bool CheckShift (InterpState &S, CodePtr OpPC, const LT &LHS, const RT &RHS, unsigned Bits)
Checks if the shift operation is legal.
template<typename T >
bool CheckDivRem (InterpState &S, CodePtr OpPC, const T &LHS, const T &RHS)
Checks if Div/Rem operation on LHS and RHS is valid.
bool InterpretBuiltin (InterpState &S, CodePtr OpPC, const Function *F)
Interpret a builtin function.
template<PrimType Name, bool Builtin = false, class T = typename PrimConv<Name>::T>
bool Ret (InterpState &S, CodePtr &PC, APValue &Result)
template<bool Builtin = false>
bool RetVoid (InterpState &S, CodePtr &PC, APValue &Result)
template<typename T , bool(*)(T, T, unsigned, T *) OpFW, template< typename U > class OpAP>
bool AddSubMulHelper (InterpState &S, CodePtr OpPC, unsigned Bits, const T &LHS, const T &RHS)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Add (InterpState &S, CodePtr OpPC)
bool Addf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Sub (InterpState &S, CodePtr OpPC)
bool Subf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Mul (InterpState &S, CodePtr OpPC)
bool Mulf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool BitAnd (InterpState &S, CodePtr OpPC)
1) Pops the RHS from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool BitOr (InterpState &S, CodePtr OpPC)
1) Pops the RHS from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool BitXor (InterpState &S, CodePtr OpPC)
1) Pops the RHS from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Rem (InterpState &S, CodePtr OpPC)
1) Pops the RHS from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Div (InterpState &S, CodePtr OpPC)
1) Pops the RHS from the stack.
bool Divf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Inv (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Neg (InterpState &S, CodePtr OpPC)
template<typename T , IncDecOp Op, PushVal DoPush>
bool IncDecHelper (InterpState &S, CodePtr OpPC, const Pointer &Ptr)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Inc (InterpState &S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value increased by one back to the pointer 4) Pushes the original (pre-inc) value on the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool IncPop (InterpState &S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value increased by one back to the pointer
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Dec (InterpState &S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value decreased by one back to the pointer 4) Pushes the original (pre-dec) value on the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool DecPop (InterpState &S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value decreased by one back to the pointer
template<IncDecOp Op, PushVal DoPush>
bool IncDecFloatHelper (InterpState &S, CodePtr OpPC, const Pointer &Ptr, llvm::RoundingMode RM)
bool Incf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
bool IncfPop (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
bool Decf (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
bool DecfPop (InterpState &S, CodePtr OpPC, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Comp (InterpState &S, CodePtr OpPC)
1) Pops the value from the stack.
template<typename T >
bool CmpHelper (InterpState &S, CodePtr OpPC, CompareFn Fn)
template<typename T >
bool CmpHelperEQ (InterpState &S, CodePtr OpPC, CompareFn Fn)
template<>
bool CmpHelper< FunctionPointer > (InterpState &S, CodePtr OpPC, CompareFn Fn)
Function pointers cannot be compared in an ordered way.
template<>
bool CmpHelperEQ< FunctionPointer > (InterpState &S, CodePtr OpPC, CompareFn Fn)
template<>
bool CmpHelper< Pointer > (InterpState &S, CodePtr OpPC, CompareFn Fn)
template<>
bool CmpHelperEQ< Pointer > (InterpState &S, CodePtr OpPC, CompareFn Fn)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool EQ (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool NE (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool LT (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool LE (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GT (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GE (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InRange (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Dup (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Pop (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Const (InterpState &S, CodePtr OpPC, const T &Arg)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetLocal (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SetLocal (InterpState &S, CodePtr OpPC, uint32_t I)
1) Pops the value from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetParam (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SetParam (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetField (InterpState &S, CodePtr OpPC, uint32_t I)
1) Peeks a pointer on the stack 2) Pushes the value of the pointer's field on the stack
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SetField (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetFieldPop (InterpState &S, CodePtr OpPC, uint32_t I)
1) Pops a pointer from the stack 2) Pushes the value of the pointer's field on the stack
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetThisField (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SetThisField (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool GetGlobal (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SetGlobal (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitGlobal (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitGlobalTemp (InterpState &S, CodePtr OpPC, uint32_t I, const LifetimeExtendedTemporaryDecl *Temp)
1) Converts the value on top of the stack to an APValue 2) Sets that APValue on \Temp 3) Initialized global with index \I with that
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitThisField (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitThisBitField (InterpState &S, CodePtr OpPC, const Record::Field *F)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitThisFieldActive (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitField (InterpState &S, CodePtr OpPC, uint32_t I)
1) Pops the value from the stack 2) Peeks a pointer from the stack 3) Pushes the value to field I of the pointer on the stack
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitBitField (InterpState &S, CodePtr OpPC, const Record::Field *F)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitFieldActive (InterpState &S, CodePtr OpPC, uint32_t I)
bool GetPtrLocal (InterpState &S, CodePtr OpPC, uint32_t I)
bool GetPtrParam (InterpState &S, CodePtr OpPC, uint32_t I)
bool GetPtrGlobal (InterpState &S, CodePtr OpPC, uint32_t I)
bool GetPtrField (InterpState &S, CodePtr OpPC, uint32_t Off)
1) Pops a Pointer from the stack 2) Pushes Pointer.atField(Off) on the stack
bool GetPtrThisField (InterpState &S, CodePtr OpPC, uint32_t Off)
bool GetPtrActiveField (InterpState &S, CodePtr OpPC, uint32_t Off)
bool GetPtrActiveThisField (InterpState &S, CodePtr OpPC, uint32_t Off)
bool GetPtrBase (InterpState &S, CodePtr OpPC, uint32_t Off)
bool GetPtrBasePop (InterpState &S, CodePtr OpPC, uint32_t Off)
bool GetPtrThisBase (InterpState &S, CodePtr OpPC, uint32_t Off)
bool VirtBaseHelper (InterpState &S, CodePtr OpPC, const RecordDecl *Decl, const Pointer &Ptr)
bool GetPtrVirtBase (InterpState &S, CodePtr OpPC, const RecordDecl *D)
bool GetPtrThisVirtBase (InterpState &S, CodePtr OpPC, const RecordDecl *D)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Load (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool LoadPop (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Store (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool StorePop (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool StoreBitField (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool StoreBitFieldPop (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitPop (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitElem (InterpState &S, CodePtr OpPC, uint32_t Idx)
1) Pops the value from the stack 2) Peeks a pointer and gets its index \Idx 3) Sets the value on the pointer, leaving the pointer on the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool InitElemPop (InterpState &S, CodePtr OpPC, uint32_t Idx)
The same as InitElem, but pops the pointer as well.
template<class T , ArithOp Op>
bool OffsetHelper (InterpState &S, CodePtr OpPC, const T &Offset, const Pointer &Ptr)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool AddOffset (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SubOffset (InterpState &S, CodePtr OpPC)
template<ArithOp Op>
static bool IncDecPtrHelper (InterpState &S, CodePtr OpPC)
static bool IncPtr (InterpState &S, CodePtr OpPC)
static bool DecPtr (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool SubPtr (InterpState &S, CodePtr OpPC)
1) Pops a Pointer from the stack.
bool Destroy (InterpState &S, CodePtr OpPC, uint32_t I)
template<PrimType TIn, PrimType TOut>
bool Cast (InterpState &S, CodePtr OpPC)
bool CastFP (InterpState &S, CodePtr OpPC, const llvm::fltSemantics *Sem, llvm::RoundingMode RM)
1) Pops a Floating from the stack.
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool CastIntegralFloating (InterpState &S, CodePtr OpPC, const llvm::fltSemantics *Sem, llvm::RoundingMode RM)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool CastFloatingIntegral (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Zero (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool Null (InterpState &S, CodePtr OpPC)
bool This (InterpState &S, CodePtr OpPC)
bool RVOPtr (InterpState &S, CodePtr OpPC)
template<PrimType NameL, PrimType NameR>
bool Shr (InterpState &S, CodePtr OpPC)
template<PrimType NameL, PrimType NameR>
bool Shl (InterpState &S, CodePtr OpPC)
bool NoRet (InterpState &S, CodePtr OpPC)
bool NarrowPtr (InterpState &S, CodePtr OpPC)
bool ExpandPtr (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool ArrayElemPtr (InterpState &S, CodePtr OpPC)
template<PrimType Name, class T = typename PrimConv<Name>::T>
bool ArrayElemPtrPop (InterpState &S, CodePtr OpPC)
bool CheckGlobalCtor (InterpState &S, CodePtr OpPC)
bool Call (InterpState &S, CodePtr OpPC, const Function *Func)
bool CallVirt (InterpState &S, CodePtr OpPC, const Function *Func)
bool CallBI (InterpState &S, CodePtr &PC, const Function *Func)
bool CallPtr (InterpState &S, CodePtr OpPC)
bool GetFnPtr (InterpState &S, CodePtr OpPC, const Function *Func)
template<typename T >
T ReadArg (InterpState &S, CodePtr &OpPC)
template<typename T >
T getParam (InterpFrame *Frame, unsigned Index)
static bool interp__builtin_strcmp (InterpState &S, CodePtr OpPC, InterpFrame *Frame)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Pointer &P)
template<typename T >
ComparisonCategoryResult Compare (const T &X, const T &Y)
Helper to compare two comparable types.
size_t primSize (PrimType Type)
Returns the size of a primitive type in bytes.
constexpr bool isIntegralType (PrimType T)
constexpr size_t align (size_t Size)
Aligns a size to the pointer alignment.
constexpr bool aligned (uintptr_t Value)
static bool aligned (const void *P)
Typedef Documentation
APFloat
using clang::interp::APFloat = llvm::APFloat
Definition at line 23 of file Floating.h.
APInt
typedef llvm::APInt clang::interp::APInt = llvm::APInt
Definition at line 29 of file Integral.h.
BlockCtorFn
using clang::interp::BlockCtorFn
Initial value:
 void (*)(Block *Storage, char *FieldPtr, bool IsConst,
                             bool IsMutable, bool IsActive,
                             const Descriptor *FieldDesc)
Invoked whenever a block is created.
The constructor method fills in the inline descriptors of all fields and array elements. It also initializes all the fields which contain non-trivial types.
Definition at line 31 of file Descriptor.h.
BlockDtorFn
using clang::interp::BlockDtorFn
Initial value:
 void (*)(Block *Storage, char *FieldPtr,
                             const Descriptor *FieldDesc)
Invoked when a block is destroyed.
Invokes the destructors of all non-trivial nested fields of arrays and records.
Definition at line 37 of file Descriptor.h.
BlockMoveFn
using clang::interp::BlockMoveFn
Initial value:
 void (*)(Block *Storage, const char *SrcFieldPtr,
                             char *DstFieldPtr, const Descriptor *FieldDesc)
Invoked when a block with pointers referencing it goes out of scope.
Such blocks are persisted: the move function copies all inline descriptors and non-trivial fields, as existing pointers might need to reference those descriptors. Data is not copied since it cannot be legally read.
Definition at line 44 of file Descriptor.h.
CompareFn
using clang::interp::CompareFn = llvm::function_ref<bool(ComparisonCategoryResult)>
Definition at line 644 of file Interp.h.
DeclTy
using clang::interp::DeclTy = llvm::PointerUnion<const Decl *, const Expr *>
Definition at line 26 of file Descriptor.h.
SourceMap
using clang::interp::SourceMap = std::vector<std::pair<unsigned, SourceInfo>>
Definition at line 85 of file Source.h.
Enumeration Type Documentation
ArithOp
enum class clang::interp::ArithOp strong
Enumerator
Add
Sub
Definition at line 174 of file Interp.h.
IncDecOp
enum class clang::interp::IncDecOp strong
Enumerator
Inc
Dec
Definition at line 467 of file Interp.h.
Opcode
enum clang::interp::Opcode : uint32_t
Definition at line 21 of file Opcode.h.
PrimType
enum clang::interp::PrimType : unsigned
Enumeration of the primitive types of the VM.
Enumerator
PT_Sint8
PT_Uint8
PT_Sint16
PT_Uint16
PT_Sint32
PT_Uint32
PT_Sint64
PT_Uint64
PT_Bool
PT_Float
PT_Ptr
PT_FnPtr
Definition at line 30 of file PrimType.h.
PushVal
enum class clang::interp::PushVal : bool strong
Enumerator
No
Yes
Definition at line 463 of file Interp.h.
Function Documentation
Add()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Add (InterpState & S, CodePtr OpPC)
Definition at line 257 of file Interp.h.
References AddSubMulHelper().
Addf()
bool clang::interp::Addf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 264 of file Interp.h.
References clang::interp::Floating::add(), CheckFloatResult(), and clang::Result.
AddOffset()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::AddOffset (InterpState & S, CodePtr OpPC)
Definition at line 1359 of file Interp.h.
References Offset, and OffsetHelper().
AddSubMulHelper()
template<typename T , bool(*)(T, T, unsigned, T *) OpFW, template< typename U > class OpAP> bool clang::interp::AddSubMulHelper (InterpState & S, CodePtr OpPC, unsigned Bits, const T & LHS, const T & RHS)
Definition at line 226 of file Interp.h.
References clang::Expr::getExprLoc(), clang::Expr::getType(), clang::Result, and Type.
Referenced by Add(), Mul(), Sub(), and SubPtr().
align()
size_t clang::interp::align (size_t Size) constexpr
Aligns a size to the pointer alignment.
Definition at line 68 of file PrimType.h.
Referenced by aligned(), clang::interp::InitMap::allocate(), clang::interp::ByteCodeEmitter::compileFunc(), clang::interp::ByteCodeEmitter::createLocal(), clang::interp::InterpFrame::describe(), clang::interp::InterpStack::dump(), emit(), clang::interp::ByteCodeEmitter::emitLabel(), clang::interp::Program::getOrCreateRecord(), and clang::interp::CodePtr::read().
aligned() [1/2]
static bool clang::interp::aligned (const void * P) inline static
Definition at line 75 of file PrimType.h.
References aligned(), and P.
aligned() [2/2]
bool clang::interp::aligned (uintptr_t Value) constexpr
Definition at line 72 of file PrimType.h.
References align().
Referenced by aligned(), emit(), clang::interp::ByteCodeEmitter::emitLabel(), clang::interp::InterpStack::peek(), and clang::interp::CodePtr::read().
ArrayElemPtr()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::ArrayElemPtr (InterpState & S, CodePtr OpPC) inline
Definition at line 1602 of file Interp.h.
References NarrowPtr(), Offset, and OffsetHelper().
ArrayElemPtrPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::ArrayElemPtrPop (InterpState & S, CodePtr OpPC) inline
Definition at line 1613 of file Interp.h.
References NarrowPtr(), Offset, and OffsetHelper().
BitAnd()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::BitAnd (InterpState & S, CodePtr OpPC)
1) Pops the RHS from the stack.
2) Pops the LHS from the stack. 3) Pushes 'LHS & RHS' on the stack
Definition at line 313 of file Interp.h.
References clang::Result.
BitOr()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::BitOr (InterpState & S, CodePtr OpPC)
1) Pops the RHS from the stack.
2) Pops the LHS from the stack. 3) Pushes 'LHS | RHS' on the stack
Definition at line 330 of file Interp.h.
References clang::Result.
BitXor()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::BitXor (InterpState & S, CodePtr OpPC)
1) Pops the RHS from the stack.
2) Pops the LHS from the stack. 3) Pushes 'LHS ^ RHS' on the stack
Definition at line 347 of file Interp.h.
References clang::Result.
Call()
bool clang::interp::Call (InterpState & S, CodePtr OpPC, const Function * Func) inline
Definition at line 1628 of file Interp.h.
References Call(), CheckCallable(), CheckCallDepth(), CheckInvoke(), clang::interp::Function::getArgSize(), clang::interp::Function::hasRVO(), clang::interp::Function::hasThisPointer(), Interpret(), primSize(), and PT_Ptr.
Referenced by Call(), CallPtr(), and CallVirt().
CallBI()
bool clang::interp::CallBI (InterpState & S, CodePtr & PC, const Function * Func) inline
Definition at line 1698 of file Interp.h.
References InterpretBuiltin().
CallPtr()
bool clang::interp::CallPtr (InterpState & S, CodePtr OpPC) inline
Definition at line 1712 of file Interp.h.
References Call(), and clang::interp::FunctionPointer::getFunction().
CallVirt()
bool clang::interp::CallVirt (InterpState & S, CodePtr OpPC, const Function * Func) inline
Definition at line 1668 of file Interp.h.
References Call(), clang::cast(), clang::interp::Function::getArgSize(), clang::Type::getAsCXXRecordDecl(), clang::interp::Function::getDecl(), clang::interp::Pointer::getDeclDesc(), clang::interp::Pointer::getDeclPtr(), clang::interp::Pointer::getFieldDesc(), clang::interp::Function::getParentDecl(), clang::interp::Descriptor::getType(), clang::interp::Function::hasRVO(), clang::interp::Function::hasThisPointer(), clang::CXXRecordDecl::isDerivedFrom(), clang::interp::Function::isVirtual(), primSize(), and PT_Ptr.
Cast()
template<PrimType TIn, PrimType TOut> bool clang::interp::Cast (InterpState & S, CodePtr OpPC)
Definition at line 1430 of file Interp.h.
CastFloatingIntegral()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::CastFloatingIntegral (InterpState & S, CodePtr OpPC)
Definition at line 1462 of file Interp.h.
References CheckFloatResult(), clang::interp::Floating::convertToInteger(), clang::interp::Floating::getAPFloat(), clang::Expr::getType(), clang::interp::Floating::isFinite(), clang::interp::Floating::isNonZero(), clang::Result, and Type.
CastFP()
bool clang::interp::CastFP (InterpState & S, CodePtr OpPC, const llvm::fltSemantics * Sem, llvm::RoundingMode RM) inline
1) Pops a Floating from the stack.
2) Pushes a new floating on the stack that uses the given semantics.
Definition at line 1439 of file Interp.h.
References clang::Result, and clang::interp::Floating::toSemantics().
CastIntegralFloating()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::CastIntegralFloating (InterpState & S, CodePtr OpPC, const llvm::fltSemantics * Sem, llvm::RoundingMode RM)
Definition at line 1448 of file Interp.h.
References CheckFloatResult(), clang::interp::Floating::fromIntegral(), and clang::Result.
CheckArray()
bool clang::interp::CheckArray (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if the array is offsetable.
Definition at line 138 of file Interp.cpp.
References clang::interp::Pointer::isUnknownSizeArray().
Referenced by OffsetHelper().
CheckArrayInitialized()
static bool clang::interp::CheckArrayInitialized (InterpState & S, CodePtr OpPC, const Pointer & BasePtr, const ConstantArrayType * CAT) static
Definition at line 394 of file Interp.cpp.
References clang::interp::Pointer::atIndex(), CheckArrayInitialized(), CheckFieldsInitialized(), DiagnoseUninitializedSubobject(), clang::ArrayType::getElementType(), clang::interp::Pointer::getElemRecord(), clang::interp::Pointer::getField(), clang::ConstantArrayType::getSize(), clang::interp::Pointer::isInitialized(), clang::Type::isRecordType(), clang::interp::Pointer::narrow(), and clang::Result.
Referenced by CheckArrayInitialized(), CheckCtorCall(), and CheckFieldsInitialized().
CheckCallable()
bool clang::interp::CheckCallable (InterpState & S, CodePtr OpPC, const Function * F)
Checks if a method can be called.
Definition at line 298 of file Interp.cpp.
References bool, clang::interp::Function::getDecl(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::FunctionDecl::isConstexpr(), clang::interp::Function::isConstexpr(), and clang::interp::Function::isVirtual().
Referenced by Call().
CheckCallDepth()
bool clang::interp::CheckCallDepth (InterpState & S, CodePtr OpPC)
Checks if calling the currently active function would exceed the allowed call depth.
Definition at line 344 of file Interp.cpp.
References clang::Sema::getLangOpts().
Referenced by Call().
CheckConst()
bool clang::interp::CheckConst (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a pointer points to const storage.
Definition at line 203 of file Interp.cpp.
References clang::interp::Pointer::block(), clang::interp::Pointer::getType(), clang::interp::Pointer::isConst(), and clang::interp::Pointer::isLive().
Referenced by CheckStore().
CheckCtorCall()
bool clang::interp::CheckCtorCall (InterpState & S, CodePtr OpPC, const Pointer & This)
Checks that all fields are initialized after a constructor call.
Definition at line 457 of file Interp.cpp.
References clang::cast(), CheckArrayInitialized(), CheckFieldsInitialized(), and This().
Referenced by CheckGlobalCtor().
CheckDivRem()
template<typename T > bool clang::interp::CheckDivRem (InterpState & S, CodePtr OpPC, const T & LHS, const T & RHS)
Checks if Div/Rem operation on LHS and RHS is valid.
Definition at line 145 of file Interp.h.
References clang::Expr::getType().
Referenced by Div(), Divf(), and Rem().
CheckExtern()
bool clang::interp::CheckExtern (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if the variable has externally defined storage.
Definition at line 125 of file Interp.cpp.
References clang::interp::Descriptor::asValueDecl(), clang::interp::Pointer::getDeclDesc(), and clang::interp::Pointer::isExtern().
Referenced by CheckInvoke(), CheckLoad(), CheckStore(), and GetPtrField().
CheckFieldsInitialized()
static bool clang::interp::CheckFieldsInitialized (InterpState & S, CodePtr OpPC, const Pointer & BasePtr, const Record * R) static
Definition at line 425 of file Interp.cpp.
References clang::interp::Pointer::atField(), clang::interp::Record::bases(), clang::cast(), CheckArrayInitialized(), CheckFieldsInitialized(), DiagnoseUninitializedSubobject(), clang::interp::Record::fields(), clang::Type::getAsArrayTypeUnsafe(), clang::interp::Pointer::getRecord(), clang::Type::isArrayType(), clang::interp::Pointer::isInitialized(), clang::Type::isRecordType(), P, and clang::Result.
Referenced by CheckArrayInitialized(), CheckCtorCall(), and CheckFieldsInitialized().
CheckFloatResult()
bool clang::interp::CheckFloatResult (InterpState & S, CodePtr OpPC, APFloat::opStatus Status)
Checks if the result is a floating-point operation is valid in the current context.
Definition at line 466 of file Interp.cpp.
References clang::interp::SourceInfo::asExpr(), clang::LangOptions::FPE_Ignore, clang::FPOptions::getExceptionMode(), clang::Expr::getFPFeaturesInEffect(), clang::Sema::getLangOpts(), and clang::FPOptions::getRoundingMode().
Referenced by Addf(), CastFloatingIntegral(), CastIntegralFloating(), Divf(), IncDecFloatHelper(), Mulf(), and Subf().
CheckGlobalCtor()
bool clang::interp::CheckGlobalCtor (InterpState & S, CodePtr OpPC) inline
Definition at line 1623 of file Interp.h.
References CheckCtorCall().
CheckInit()
bool clang::interp::CheckInit (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a value can be initialized.
Definition at line 290 of file Interp.cpp.
References clang::AK_Assign, CheckLive(), and CheckRange().
Referenced by InitElem(), InitElemPop(), and InitPop().
CheckInitialized()
bool clang::interp::CheckInitialized (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK)
Definition at line 235 of file Interp.cpp.
References clang::interp::Pointer::isInitialized().
Referenced by CheckLoad(), Dec(), Decf(), DecfPop(), DecPop(), Inc(), Incf(), IncfPop(), and IncPop().
CheckInvoke()
bool clang::interp::CheckInvoke (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a method can be invoked on an object.
Definition at line 280 of file Interp.cpp.
References clang::AK_MemberCall, CheckExtern(), CheckLive(), and CheckRange().
Referenced by Call().
CheckLive()
bool clang::interp::CheckLive (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK)
Checks if a pointer is live and accessible.
Definition at line 146 of file Interp.cpp.
References clang::CSK_Field, clang::interp::Pointer::getDeclLoc(), clang::interp::Pointer::isField(), clang::interp::Pointer::isLive(), clang::interp::Pointer::isTemporary(), and clang::interp::Pointer::isZero().
Referenced by CheckInit(), CheckInvoke(), CheckLoad(), CheckStore(), and interp__builtin_strcmp().
CheckLoad()
bool clang::interp::CheckLoad (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a value can be loaded from a block.
Definition at line 248 of file Interp.cpp.
References clang::AK_Read, CheckActive(), CheckExtern(), CheckInitialized(), CheckLive(), CheckMutable(), CheckRange(), and CheckTemporary().
Referenced by GetField(), GetFieldPop(), GetLocal(), GetThisField(), Load(), and LoadPop().
CheckMutable()
bool clang::interp::CheckMutable (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a pointer points to a mutable field.
Definition at line 222 of file Interp.cpp.
References clang::AK_Read, clang::interp::Pointer::getField(), clang::interp::Pointer::isLive(), and clang::interp::Pointer::isMutable().
Referenced by CheckLoad().
CheckNull()
bool clang::interp::CheckNull (InterpState & S, CodePtr OpPC, const Pointer & Ptr, CheckSubobjectKind CSK)
Checks if a pointer is null.
Definition at line 176 of file Interp.cpp.
References clang::interp::Pointer::isZero().
Referenced by GetField(), GetFieldPop(), GetPtrActiveField(), GetPtrBase(), GetPtrBasePop(), GetPtrField(), GetPtrVirtBase(), OffsetHelper(), and SetField().
CheckPure()
bool clang::interp::CheckPure (InterpState & S, CodePtr OpPC, const CXXMethodDecl * MD)
Checks if a method is pure virtual.
Definition at line 373 of file Interp.cpp.
References clang::Decl::getLocation(), and clang::FunctionDecl::isPure().
CheckRange() [1/2]
bool clang::interp::CheckRange (InterpState & S, CodePtr OpPC, const Pointer & Ptr, AccessKinds AK)
Checks if a pointer is in range.
Definition at line 185 of file Interp.cpp.
References clang::interp::Pointer::isOnePastEnd().
Referenced by CheckInit(), CheckInvoke(), CheckLoad(), CheckStore(), GetField(), GetFieldPop(), GetPtrActiveField(), GetPtrField(), interp__builtin_strcmp(), OffsetHelper(), and SetField().
CheckRange() [2/2]
bool clang::interp::CheckRange (InterpState & S, CodePtr OpPC, const Pointer & Ptr, CheckSubobjectKind CSK)
Checks if a field from which a pointer is going to be derived is valid.
Definition at line 194 of file Interp.cpp.
References clang::interp::Pointer::isElementPastEnd().
CheckShift()
template<typename LT , typename RT > bool clang::interp::CheckShift (InterpState & S, CodePtr OpPC, const LT & LHS, const RT & RHS, unsigned Bits)
Checks if the shift operation is legal.
Definition at line 109 of file Interp.h.
References clang::Expr::getType().
Referenced by Shl(), and Shr().
CheckStore()
bool clang::interp::CheckStore (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Checks if a value can be stored in a block.
Definition at line 266 of file Interp.cpp.
References clang::AK_Assign, CheckConst(), CheckExtern(), CheckGlobal(), CheckLive(), and CheckRange().
Referenced by SetField(), SetThisField(), Store(), StoreBitField(), StoreBitFieldPop(), and StorePop().
CheckThis()
bool clang::interp::CheckThis (InterpState & S, CodePtr OpPC, const Pointer & This)
Checks the 'this' pointer.
Definition at line 355 of file Interp.cpp.
References clang::Sema::getLangOpts(), and This().
Referenced by GetPtrActiveThisField(), GetPtrThisBase(), GetPtrThisField(), GetPtrThisVirtBase(), GetThisField(), InitThisBitField(), InitThisField(), InitThisFieldActive(), SetThisField(), and This().
CmpHelper()
template<typename T > bool clang::interp::CmpHelper (InterpState & S, CodePtr OpPC, CompareFn Fn)
Definition at line 647 of file Interp.h.
Referenced by CmpHelperEQ(), GE(), GT(), LE(), and LT().
CmpHelper< FunctionPointer >()
template<> bool clang::interp::CmpHelper< FunctionPointer > (InterpState & S, CodePtr OpPC, CompareFn Fn) inline
Function pointers cannot be compared in an ordered way.
Definition at line 662 of file Interp.h.
References clang::interp::FunctionPointer::toDiagnosticString().
CmpHelper< Pointer >()
template<> bool clang::interp::CmpHelper< Pointer > (InterpState & S, CodePtr OpPC, CompareFn Fn) inline
Definition at line 684 of file Interp.h.
References Compare(), clang::interp::Pointer::getByteOffset(), and clang::interp::Pointer::hasSameBase().
CmpHelperEQ()
template<typename T > bool clang::interp::CmpHelperEQ (InterpState & S, CodePtr OpPC, CompareFn Fn)
Definition at line 656 of file Interp.h.
References CmpHelper().
Referenced by EQ(), and NE().
CmpHelperEQ< FunctionPointer >()
template<> bool clang::interp::CmpHelperEQ< FunctionPointer > (InterpState & S, CodePtr OpPC, CompareFn Fn) inline
Definition at line 675 of file Interp.h.
References clang::interp::FunctionPointer::compare(), and clang::interp::Boolean::from().
CmpHelperEQ< Pointer >()
template<> bool clang::interp::CmpHelperEQ< Pointer > (InterpState & S, CodePtr OpPC, CompareFn Fn) inline
Definition at line 702 of file Interp.h.
References clang::interp::Pointer::atIndex(), Compare(), clang::Equal, clang::interp::Pointer::getByteOffset(), clang::interp::Pointer::hasSameBase(), clang::interp::Pointer::inArray(), clang::interp::Pointer::isRoot(), clang::interp::Pointer::isZero(), and clang::Unordered.
Comp()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Comp (InterpState & S, CodePtr OpPC)
1) Pops the value from the stack.
2) Pushes the bitwise complemented value on the stack (~V).
Definition at line 629 of file Interp.h.
References clang::Result.
Compare()
template<typename T > ComparisonCategoryResult clang::interp::Compare (const T & X, const T & Y)
Helper to compare two comparable types.
Definition at line 25 of file Primitives.h.
References clang::Equal, clang::Greater, clang::Less, and X.
Referenced by CmpHelper< Pointer >(), CmpHelperEQ< Pointer >(), clang::interp::Boolean::compare(), clang::interp::Floating::compare(), and clang::interp::Integral< Bits, Signed >::compare().
Const()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Const (InterpState & S, CodePtr OpPC, const T & Arg)
Definition at line 812 of file Interp.h.
Dec()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Dec (InterpState & S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value decreased by one back to the pointer 4) Pushes the original (pre-dec) value on the stack.
Definition at line 548 of file Interp.h.
References clang::AK_Decrement, CheckInitialized(), and IncDecHelper().
Decf()
bool clang::interp::Decf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 608 of file Interp.h.
References clang::AK_Decrement, CheckInitialized(), and IncDecFloatHelper().
DecfPop()
bool clang::interp::DecfPop (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 617 of file Interp.h.
References clang::AK_Decrement, CheckInitialized(), and IncDecFloatHelper().
DecPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::DecPop (InterpState & S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value decreased by one back to the pointer
Definition at line 561 of file Interp.h.
References clang::AK_Decrement, CheckInitialized(), and IncDecHelper().
DecPtr()
static bool clang::interp::DecPtr (InterpState & S, CodePtr OpPC) inline static
Definition at line 1395 of file Interp.h.
References IncDecPtrHelper().
Destroy()
bool clang::interp::Destroy (InterpState & S, CodePtr OpPC, uint32_t I) inline
Definition at line 1421 of file Interp.h.
DiagnoseUninitializedSubobject()
static void clang::interp::DiagnoseUninitializedSubobject (InterpState & S, const SourceInfo & SI, const FieldDecl * SubObjDecl) static
Definition at line 382 of file Interp.cpp.
References clang::Decl::getLocation().
Referenced by CheckArrayInitialized(), and CheckFieldsInitialized().
Div()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Div (InterpState & S, CodePtr OpPC)
1) Pops the RHS from the stack.
2) Pops the LHS from the stack. 3) Pushes 'LHS / RHS' on the stack
Definition at line 384 of file Interp.h.
References CheckDivRem(), and clang::Result.
Divf()
bool clang::interp::Divf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 400 of file Interp.h.
References CheckDivRem(), CheckFloatResult(), clang::interp::Floating::div(), and clang::Result.
Dup()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Dup (InterpState & S, CodePtr OpPC)
Definition at line 796 of file Interp.h.
EQ()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::EQ (InterpState & S, CodePtr OpPC)
Definition at line 734 of file Interp.h.
References CmpHelperEQ(), and clang::Equal.
ExpandPtr()
bool clang::interp::ExpandPtr (InterpState & S, CodePtr OpPC) inline
Definition at line 1587 of file Interp.h.
References clang::interp::Pointer::expand().
GE()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GE (InterpState & S, CodePtr OpPC)
Definition at line 770 of file Interp.h.
References CmpHelper(), clang::Equal, and clang::Greater.
GetField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetField (InterpState & S, CodePtr OpPC, uint32_t I)
1) Peeks a pointer on the stack 2) Pushes the value of the pointer's field on the stack
Definition at line 857 of file Interp.h.
References clang::interp::Pointer::atField(), CheckLoad(), CheckNull(), CheckRange(), and clang::CSK_Field.
GetFieldPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetFieldPop (InterpState & S, CodePtr OpPC, uint32_t I)
1) Pops a pointer from the stack 2) Pushes the value of the pointer's field on the stack
Definition at line 889 of file Interp.h.
References clang::interp::Pointer::atField(), CheckLoad(), CheckNull(), CheckRange(), and clang::CSK_Field.
GetFnPtr()
bool clang::interp::GetFnPtr (InterpState & S, CodePtr OpPC, const Function * Func) inline
Definition at line 1722 of file Interp.h.
GetGlobal()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetGlobal (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 932 of file Interp.h.
GetLocal()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetLocal (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 822 of file Interp.h.
References CheckLoad(), and clang::interp::Pointer::deref().
GetParam()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetParam (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 840 of file Interp.h.
getParam()
template<typename T > T clang::interp::getParam (InterpFrame * Frame, unsigned Index)
Definition at line 16 of file InterpBuiltin.cpp.
References Offset.
Referenced by interp__builtin_strcmp().
GetPtrActiveField()
bool clang::interp::GetPtrActiveField (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1089 of file Interp.h.
References clang::interp::Pointer::atField(), CheckNull(), CheckRange(), clang::CSK_Field, and clang::interp::Pointer::deactivate().
GetPtrActiveThisField()
bool clang::interp::GetPtrActiveThisField (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1102 of file Interp.h.
References CheckThis(), and This().
GetPtrBase()
bool clang::interp::GetPtrBase (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1115 of file Interp.h.
References clang::interp::Pointer::atField(), CheckNull(), and clang::CSK_Base.
GetPtrBasePop()
bool clang::interp::GetPtrBasePop (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1123 of file Interp.h.
References clang::interp::Pointer::atField(), CheckNull(), and clang::CSK_Base.
GetPtrField()
bool clang::interp::GetPtrField (InterpState & S, CodePtr OpPC, uint32_t Off) inline
1) Pops a Pointer from the stack 2) Pushes Pointer.atField(Off) on the stack
Definition at line 1067 of file Interp.h.
References clang::interp::Pointer::atField(), CheckExtern(), CheckNull(), CheckRange(), and clang::CSK_Field.
GetPtrGlobal()
bool clang::interp::GetPtrGlobal (InterpState & S, CodePtr OpPC, uint32_t I) inline
Definition at line 1060 of file Interp.h.
GetPtrLocal()
bool clang::interp::GetPtrLocal (InterpState & S, CodePtr OpPC, uint32_t I) inline
Definition at line 1047 of file Interp.h.
GetPtrParam()
bool clang::interp::GetPtrParam (InterpState & S, CodePtr OpPC, uint32_t I) inline
Definition at line 1052 of file Interp.h.
GetPtrThisBase()
bool clang::interp::GetPtrThisBase (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1131 of file Interp.h.
References CheckThis(), and This().
GetPtrThisField()
bool clang::interp::GetPtrThisField (InterpState & S, CodePtr OpPC, uint32_t Off) inline
Definition at line 1079 of file Interp.h.
References CheckThis(), and This().
GetPtrThisVirtBase()
bool clang::interp::GetPtrThisVirtBase (InterpState & S, CodePtr OpPC, const RecordDecl * D) inline
Definition at line 1159 of file Interp.h.
References CheckThis(), This(), and VirtBaseHelper().
GetPtrVirtBase()
bool clang::interp::GetPtrVirtBase (InterpState & S, CodePtr OpPC, const RecordDecl * D) inline
Definition at line 1152 of file Interp.h.
References CheckNull(), clang::CSK_Base, and VirtBaseHelper().
getSwappedBytes()
Floating clang::interp::getSwappedBytes (Floating F)
Definition at line 19 of file Floating.cpp.
GetThisField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GetThisField (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 903 of file Interp.h.
References CheckLoad(), CheckThis(), and This().
GT()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::GT (InterpState & S, CodePtr OpPC)
Definition at line 763 of file Interp.h.
References CmpHelper(), and clang::Greater.
Inc()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Inc (InterpState & S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value increased by one back to the pointer 4) Pushes the original (pre-inc) value on the stack.
Definition at line 521 of file Interp.h.
References clang::AK_Increment, CheckInitialized(), and IncDecHelper().
IncDecFloatHelper()
template<IncDecOp Op, PushVal DoPush> bool clang::interp::IncDecFloatHelper (InterpState & S, CodePtr OpPC, const Pointer & Ptr, llvm::RoundingMode RM)
Definition at line 571 of file Interp.h.
References CheckFloatResult(), clang::interp::Floating::decrement(), clang::interp::Pointer::deref(), Inc, clang::interp::Floating::increment(), clang::Result, and Yes.
Referenced by Decf(), DecfPop(), Incf(), and IncfPop().
IncDecHelper()
template<typename T , IncDecOp Op, PushVal DoPush> bool clang::interp::IncDecHelper (InterpState & S, CodePtr OpPC, const Pointer & Ptr)
Definition at line 473 of file Interp.h.
References clang::interp::Pointer::deref(), clang::Expr::getExprLoc(), clang::Expr::getType(), Inc, clang::Result, Type, and Yes.
Referenced by Dec(), DecPop(), Inc(), and IncPop().
IncDecPtrHelper()
template<ArithOp Op> static bool clang::interp::IncDecPtrHelper (InterpState & S, CodePtr OpPC) inline static
Definition at line 1373 of file Interp.h.
References clang::interp::Pointer::deref(), OffsetHelper(), and P.
Referenced by DecPtr(), and IncPtr().
Incf()
bool clang::interp::Incf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 590 of file Interp.h.
References clang::AK_Increment, CheckInitialized(), and IncDecFloatHelper().
IncfPop()
bool clang::interp::IncfPop (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 599 of file Interp.h.
References clang::AK_Increment, CheckInitialized(), and IncDecFloatHelper().
IncPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::IncPop (InterpState & S, CodePtr OpPC)
1) Pops a pointer from the stack 2) Load the value from the pointer 3) Writes the value increased by one back to the pointer
Definition at line 534 of file Interp.h.
References clang::AK_Increment, CheckInitialized(), and IncDecHelper().
IncPtr()
static bool clang::interp::IncPtr (InterpState & S, CodePtr OpPC) inline static
Definition at line 1391 of file Interp.h.
References IncDecPtrHelper().
InitBitField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitBitField (InterpState & S, CodePtr OpPC, const Record::Field * F)
Definition at line 1023 of file Interp.h.
References clang::interp::Record::Field::Decl, clang::FieldDecl::getBitWidthValue(), and clang::interp::Record::Field::Offset.
InitElem()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitElem (InterpState & S, CodePtr OpPC, uint32_t Idx)
1) Pops the value from the stack 2) Peeks a pointer and gets its index \Idx 3) Sets the value on the pointer, leaving the pointer on the stack.
Definition at line 1262 of file Interp.h.
References CheckInit().
InitElemPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitElemPop (InterpState & S, CodePtr OpPC, uint32_t Idx)
The same as InitElem, but pops the pointer as well.
Definition at line 1274 of file Interp.h.
References CheckInit().
InitField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitField (InterpState & S, CodePtr OpPC, uint32_t I)
1) Pops the value from the stack 2) Peeks a pointer from the stack 3) Pushes the value to field I of the pointer on the stack
Definition at line 1013 of file Interp.h.
InitFieldActive()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitFieldActive (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 1033 of file Interp.h.
InitGlobal()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitGlobal (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 947 of file Interp.h.
InitGlobalTemp()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitGlobalTemp (InterpState & S, CodePtr OpPC, uint32_t I, const LifetimeExtendedTemporaryDecl * Temp)
1) Converts the value on top of the stack to an APValue 2) Sets that APValue on \Temp 3) Initialized global with index \I with that
Definition at line 956 of file Interp.h.
References clang::LifetimeExtendedTemporaryDecl::getOrCreateValue().
InitPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitPop (InterpState & S, CodePtr OpPC)
Definition at line 1248 of file Interp.h.
References CheckInit(), and clang::interp::Pointer::initialize().
InitThisBitField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitThisBitField (InterpState & S, CodePtr OpPC, const Record::Field * F)
Definition at line 982 of file Interp.h.
References CheckThis(), clang::interp::Record::Field::Decl, clang::FieldDecl::getBitWidthValue(), clang::interp::Record::Field::Offset, and This().
InitThisField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitThisField (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 969 of file Interp.h.
References CheckThis(), and This().
InitThisFieldActive()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InitThisFieldActive (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 996 of file Interp.h.
References CheckThis(), and This().
InRange()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::InRange (InterpState & S, CodePtr OpPC)
Definition at line 782 of file Interp.h.
interp__builtin_strcmp()
static bool clang::interp::interp__builtin_strcmp (InterpState & S, CodePtr OpPC, InterpFrame * Frame) static
Definition at line 21 of file InterpBuiltin.cpp.
References clang::AK_Read, clang::interp::Pointer::atIndex(), CheckLive(), CheckRange(), clang::interp::Pointer::deref(), clang::interp::Integral< Bits, Signed >::from(), clang::interp::Pointer::getFieldDesc(), clang::interp::Pointer::getIndex(), getParam(), clang::interp::Descriptor::isPrimitiveArray(), and clang::Result.
Referenced by InterpretBuiltin().
Interpret()
bool clang::interp::Interpret (InterpState & S, APValue & Result)
Interpreter entry point.
Definition at line 501 of file Interp.cpp.
References clang::interp::CodePtr::read().
Referenced by Call().
InterpretBuiltin()
bool clang::interp::InterpretBuiltin (InterpState & S, CodePtr OpPC, const Function * F)
Interpret a builtin function.
Definition at line 60 of file InterpBuiltin.cpp.
References clang::interp::Boolean::from(), clang::interp::Function::getBuiltinID(), interp__builtin_strcmp(), Ret(), and RetVoid().
Referenced by CallBI().
Inv()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Inv (InterpState & S, CodePtr OpPC)
Definition at line 418 of file Interp.h.
References clang::interp::Boolean::inv().
isIntegralType()
bool clang::interp::isIntegralType (PrimType T) constexpr
Definition at line 45 of file PrimType.h.
References PT_Uint64.
Referenced by Neg().
LE()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::LE (InterpState & S, CodePtr OpPC)
Definition at line 755 of file Interp.h.
References CmpHelper(), clang::Equal, and clang::Less.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::VisitIntegerLiteral(), and clang::interp::ByteCodeExprGen< Emitter >::visitRecordInitializer().
Load()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Load (InterpState & S, CodePtr OpPC)
Definition at line 1174 of file Interp.h.
References CheckLoad(), and clang::interp::Pointer::deref().
LoadPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::LoadPop (InterpState & S, CodePtr OpPC)
Definition at line 1183 of file Interp.h.
References CheckLoad(), and clang::interp::Pointer::deref().
LT()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::LT (InterpState & S, CodePtr OpPC)
Definition at line 748 of file Interp.h.
References CmpHelper(), and clang::Less.
Mul()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Mul (InterpState & S, CodePtr OpPC)
Definition at line 293 of file Interp.h.
References AddSubMulHelper().
Mulf()
bool clang::interp::Mulf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 300 of file Interp.h.
References CheckFloatResult(), clang::interp::Floating::mul(), and clang::Result.
NarrowPtr()
bool clang::interp::NarrowPtr (InterpState & S, CodePtr OpPC) inline
Definition at line 1581 of file Interp.h.
References clang::interp::Pointer::narrow().
Referenced by ArrayElemPtr(), and ArrayElemPtrPop().
NE()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::NE (InterpState & S, CodePtr OpPC)
Definition at line 741 of file Interp.h.
References CmpHelperEQ(), and clang::Equal.
Referenced by ctorArrayTy(), dtorArrayTy(), and moveArrayTy().
Neg()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Neg (InterpState & S, CodePtr OpPC)
Definition at line 434 of file Interp.h.
References clang::Expr::getExprLoc(), clang::Expr::getType(), isIntegralType(), clang::Result, and Type.
NoRet()
bool clang::interp::NoRet (InterpState & S, CodePtr OpPC) inline
Definition at line 1571 of file Interp.h.
Null()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Null (InterpState & S, CodePtr OpPC) inline
Definition at line 1498 of file Interp.h.
OffsetHelper()
template<class T , ArithOp Op> bool clang::interp::OffsetHelper (InterpState & S, CodePtr OpPC, const T & Offset, const Pointer & Ptr)
Definition at line 1289 of file Interp.h.
References Add, clang::interp::Pointer::atIndex(), CheckArray(), CheckNull(), CheckRange(), clang::CSK_ArrayIndex, clang::CSK_ArrayToPointer, clang::interp::Pointer::getIndex(), clang::interp::Pointer::getNumElems(), clang::interp::Pointer::inArray(), Offset, and clang::Result.
Referenced by AddOffset(), ArrayElemPtr(), ArrayElemPtrPop(), IncDecPtrHelper(), and SubOffset().
operator<<() [1/5]
llvm::raw_ostream & clang::interp::operator<< (llvm::raw_ostream & OS, const Boolean & B) inline
Definition at line 154 of file Boolean.h.
References clang::interp::Boolean::print().
operator<<() [2/5]
llvm::raw_ostream & clang::interp::operator<< (llvm::raw_ostream & OS, const Pointer & P) inline
Definition at line 388 of file Pointer.h.
References P.
operator<<() [3/5]
llvm::raw_ostream & clang::interp::operator<< (llvm::raw_ostream & OS, Floating F)
Definition at line 14 of file Floating.cpp.
References clang::interp::Floating::print().
operator<<() [4/5]
llvm::raw_ostream & clang::interp::operator<< (llvm::raw_ostream & OS, FunctionPointer FP) inline
Definition at line 62 of file FunctionPointer.h.
References clang::interp::FunctionPointer::print().
operator<<() [5/5]
template<unsigned Bits, bool Signed> llvm::raw_ostream & clang::interp::operator<< (llvm::raw_ostream & OS, Integral< Bits, Signed > I)
Definition at line 291 of file Integral.h.
References clang::interp::Integral< Bits, Signed >::print().
Pop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Pop (InterpState & S, CodePtr OpPC)
Definition at line 802 of file Interp.h.
primSize()
size_t clang::interp::primSize (PrimType Type)
Returns the size of a primitive type in bytes.
Definition at line 21 of file PrimType.cpp.
References TYPE_SWITCH.
Referenced by Call(), CallVirt(), clang::interp::ByteCodeEmitter::compileFunc(), clang::interp::Program::createDescriptor(), clang::interp::InterpFrame::describe(), and clang::interp::InterpStack::dump().
ReadArg()
template<typename T > T clang::interp::ReadArg (InterpState & S, CodePtr & OpPC) inline
Definition at line 1732 of file Interp.h.
References clang::interp::CodePtr::read().
Rem()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Rem (InterpState & S, CodePtr OpPC)
1) Pops the RHS from the stack.
2) Pops the LHS from the stack. 3) Pushes 'LHS % RHS' on the stack (the remainder of dividing LHS by RHS).
Definition at line 364 of file Interp.h.
References CheckDivRem(), and clang::Result.
Ret()
template<PrimType Name, bool Builtin = false, class T = typename PrimConv<Name>::T> bool clang::interp::Ret (InterpState & S, CodePtr & PC, APValue & Result)
Definition at line 182 of file Interp.h.
References clang::Result, Ret(), and ReturnValue().
Referenced by InterpretBuiltin(), and Ret().
ReturnValue()
template<typename T > bool clang::interp::ReturnValue (const T & V, APValue & R)
Convert a value to an APValue.
Definition at line 44 of file Interp.h.
References V.
Referenced by Ret().
RetVoid()
template<bool Builtin = false> bool clang::interp::RetVoid (InterpState & S, CodePtr & PC, APValue & Result) inline
Definition at line 204 of file Interp.h.
Referenced by InterpretBuiltin().
RVOPtr()
bool clang::interp::RVOPtr (InterpState & S, CodePtr OpPC) inline
Definition at line 1521 of file Interp.h.
SetField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SetField (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 871 of file Interp.h.
References CheckNull(), CheckRange(), CheckStore(), and clang::CSK_Field.
SetGlobal()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SetGlobal (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 941 of file Interp.h.
SetLocal()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SetLocal (InterpState & S, CodePtr OpPC, uint32_t I)
1) Pops the value from the stack.
2) Writes the value to the local variable with the given offset.
Definition at line 834 of file Interp.h.
SetParam()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SetParam (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 849 of file Interp.h.
SetThisField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SetThisField (InterpState & S, CodePtr OpPC, uint32_t I)
Definition at line 917 of file Interp.h.
References CheckStore(), CheckThis(), and This().
Shl()
template<PrimType NameL, PrimType NameR> bool clang::interp::Shl (InterpState & S, CodePtr OpPC) inline
Definition at line 1551 of file Interp.h.
References CheckShift(), and LT.
Shr()
template<PrimType NameL, PrimType NameR> bool clang::interp::Shr (InterpState & S, CodePtr OpPC) inline
Definition at line 1534 of file Interp.h.
References CheckShift(), and LT.
Store()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Store (InterpState & S, CodePtr OpPC)
Definition at line 1192 of file Interp.h.
References CheckStore(), and clang::interp::Pointer::initialize().
StoreBitField()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::StoreBitField (InterpState & S, CodePtr OpPC)
Definition at line 1216 of file Interp.h.
References CheckStore(), and clang::interp::Pointer::initialize().
StoreBitFieldPop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::StoreBitFieldPop (InterpState & S, CodePtr OpPC)
Definition at line 1232 of file Interp.h.
References CheckStore(), and clang::interp::Pointer::initialize().
StorePop()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::StorePop (InterpState & S, CodePtr OpPC)
Definition at line 1204 of file Interp.h.
References CheckStore(), and clang::interp::Pointer::initialize().
Sub()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Sub (InterpState & S, CodePtr OpPC)
Definition at line 275 of file Interp.h.
References AddSubMulHelper().
Subf()
bool clang::interp::Subf (InterpState & S, CodePtr OpPC, llvm::RoundingMode RM) inline
Definition at line 282 of file Interp.h.
References CheckFloatResult(), clang::Result, and clang::interp::Floating::sub().
SubOffset()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SubOffset (InterpState & S, CodePtr OpPC)
Definition at line 1366 of file Interp.h.
References Offset, and OffsetHelper().
SubPtr()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::SubPtr (InterpState & S, CodePtr OpPC) inline
1) Pops a Pointer from the stack.
2) Pops another Pointer from the stack. 3) Pushes the different of the indices of the two pointers on the stack.
Definition at line 1403 of file Interp.h.
References AddSubMulHelper(), clang::interp::Pointer::getIndex(), and clang::interp::Pointer::hasSameArray().
This()
bool clang::interp::This (InterpState & S, CodePtr OpPC) inline
Definition at line 1507 of file Interp.h.
References CheckThis(), and This().
Referenced by CheckCtorCall(), CheckThis(), GetPtrActiveThisField(), GetPtrThisBase(), GetPtrThisField(), GetPtrThisVirtBase(), GetThisField(), InitThisBitField(), InitThisField(), InitThisFieldActive(), SetThisField(), and This().
VirtBaseHelper()
bool clang::interp::VirtBaseHelper (InterpState & S, CodePtr OpPC, const RecordDecl * Decl, const Pointer & Ptr) inline
Definition at line 1141 of file Interp.h.
Referenced by GetPtrThisVirtBase(), and GetPtrVirtBase().
Zero()
template<PrimType Name, class T = typename PrimConv<Name>::T> bool clang::interp::Zero (InterpState & S, CodePtr OpPC)
Definition at line 1492 of file Interp.h.