clang: clang::ast_matchers::dynamic Namespace Reference
clang::ast_matchers::dynamic Namespace Reference
Namespaces
namespace internal
Classes
class ArgKind
Kind identifier.
class Diagnostics
Helper class to manage error messages.
struct MatcherCompletion
class Parser
Matcher expression parser.
struct ParserValue
A VariantValue instance annotated with its parser context.
class Registry
struct SourceLocation
struct SourceRange
class VariantMatcher
A variant matcher object.
class VariantValue
Variant value class.
Typedefs
using MatcherCtor = const internal::MatcherDescriptor *
Functions
static StringRef contextTypeToFormatString (Diagnostics::ContextType Type)
static StringRef errorTypeToFormatString (Diagnostics::ErrorType Type)
static void formatErrorString (StringRef FormatString, ArrayRef< std::string > Args, llvm::raw_ostream &OS)
static void maybeAddLineAndColumn (SourceRange Range, llvm::raw_ostream &OS)
static void printContextFrameToStream (const Diagnostics::ContextFrame &Frame, llvm::raw_ostream &OS)
static void printMessageToStream (const Diagnostics::ErrorContent::Message &Message, const Twine Prefix, llvm::raw_ostream &OS)
static void printErrorContentToStream (const Diagnostics::ErrorContent &Content, llvm::raw_ostream &OS)
static llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const std::set< ASTNodeKind > &KS)
Variables
static llvm::ManagedStatic< Parser::RegistrySema > DefaultRegistrySema
static llvm::ManagedStatic< RegistryMaps > RegistryData
Typedef Documentation
MatcherCtor
using clang::ast_matchers::dynamic::MatcherCtor = const internal::MatcherDescriptor *
Definition at line 55 of file Registry.h.
Function Documentation
contextTypeToFormatString()
static StringRef clang::ast_matchers::dynamic::contextTypeToFormatString (Diagnostics::ContextType Type) static
Definition at line 76 of file Diagnostics.cpp.
References clang::ast_matchers::dynamic::Diagnostics::CT_MatcherArg, and clang::ast_matchers::dynamic::Diagnostics::CT_MatcherConstruct.
Referenced by printContextFrameToStream().
errorTypeToFormatString()
static StringRef clang::ast_matchers::dynamic::errorTypeToFormatString (Diagnostics::ErrorType Type) static
Definition at line 86 of file Diagnostics.cpp.
References clang::ast_matchers::dynamic::Diagnostics::ET_None, clang::ast_matchers::dynamic::Diagnostics::ET_ParserFailedToBuildMatcher, clang::ast_matchers::dynamic::Diagnostics::ET_ParserInvalidToken, clang::ast_matchers::dynamic::Diagnostics::ET_ParserMalformedBindExpr, clang::ast_matchers::dynamic::Diagnostics::ET_ParserMalformedChainedExpr, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNoCloseParen, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNoCode, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNoComma, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNoOpenParen, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNotAMatcher, clang::ast_matchers::dynamic::Diagnostics::ET_ParserNumberError, clang::ast_matchers::dynamic::Diagnostics::ET_ParserOverloadedType, clang::ast_matchers::dynamic::Diagnostics::ET_ParserStringError, clang::ast_matchers::dynamic::Diagnostics::ET_ParserTrailingCode, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryAmbiguousOverload, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryMatcherNotFound, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryMatcherNoWithSupport, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryNonNodeMatcher, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryNotBindable, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryUnknownEnumWithReplace, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryValueNotFound, clang::ast_matchers::dynamic::Diagnostics::ET_RegistryWrongArgCount, and clang::ast_matchers::dynamic::Diagnostics::ET_RegistryWrongArgType.
Referenced by printMessageToStream().
formatErrorString()
static void clang::ast_matchers::dynamic::formatErrorString (StringRef FormatString, ArrayRef< std::string > Args, llvm::raw_ostream & OS) static
Definition at line 141 of file Diagnostics.cpp.
References Next.
Referenced by printContextFrameToStream(), and printMessageToStream().
maybeAddLineAndColumn()
static void clang::ast_matchers::dynamic::maybeAddLineAndColumn (SourceRange Range, llvm::raw_ostream & OS) static
Definition at line 162 of file Diagnostics.cpp.
Referenced by printContextFrameToStream(), and printMessageToStream().
operator<<()
static llvm::raw_ostream & clang::ast_matchers::dynamic::operator<< (llvm::raw_ostream & OS, const std::set< ASTNodeKind > & KS) static
Definition at line 635 of file Registry.cpp.
printContextFrameToStream()
static void clang::ast_matchers::dynamic::printContextFrameToStream (const Diagnostics::ContextFrame & Frame, llvm::raw_ostream & OS) static
Definition at line 169 of file Diagnostics.cpp.
References clang::ast_matchers::dynamic::Diagnostics::ContextFrame::Args, contextTypeToFormatString(), formatErrorString(), maybeAddLineAndColumn(), clang::ast_matchers::dynamic::Diagnostics::ContextFrame::Range, and clang::ast_matchers::dynamic::Diagnostics::ContextFrame::Type.
Referenced by clang::ast_matchers::dynamic::Diagnostics::printToStreamFull().
printErrorContentToStream()
static void clang::ast_matchers::dynamic::printErrorContentToStream (const Diagnostics::ErrorContent & Content, llvm::raw_ostream & OS) static
Definition at line 183 of file Diagnostics.cpp.
References clang::ast_matchers::dynamic::Diagnostics::ErrorContent::Messages, and printMessageToStream().
Referenced by clang::ast_matchers::dynamic::Diagnostics::printToStream(), and clang::ast_matchers::dynamic::Diagnostics::printToStreamFull().
printMessageToStream()
static void clang::ast_matchers::dynamic::printMessageToStream (const Diagnostics::ErrorContent::Message & Message, const Twine Prefix, llvm::raw_ostream & OS) static
Definition at line 176 of file Diagnostics.cpp.
References errorTypeToFormatString(), formatErrorString(), and maybeAddLineAndColumn().
Referenced by printErrorContentToStream().
Variable Documentation
DefaultRegistrySema
llvm::ManagedStatic<Parser::RegistrySema> clang::ast_matchers::dynamic::DefaultRegistrySema static
Definition at line 822 of file Parser.cpp.
RegistryData
llvm::ManagedStatic<RegistryMaps> clang::ast_matchers::dynamic::RegistryData static
Definition at line 606 of file Registry.cpp.
Referenced by clang::ast_matchers::dynamic::Registry::getMatcherCompletions(), and clang::ast_matchers::dynamic::Registry::lookupMatcherCtor().