clang: clang::tooling::stdlib Namespace Reference
clang::tooling::stdlib Namespace Reference
Classes
class Header
class Recognizer
class Symbol
Enumerations
enum class Lang { C = 0 , CXX , LastValue = CXX }
Functions
static const SymbolHeaderMapping * getMappingPerLang (Lang L)
static int countSymbols (Lang Language)
static int initialize (Lang Language)
static void ensureInitialized ()
Variables
static SymbolHeaderMapping * LanguageMappings [static_cast< unsigned >(Lang::LastValue)+1]
Enumeration Type Documentation
Lang
enum class clang::tooling::stdlib::Lang strong
Enumerator
C
CXX
LastValue
Definition at line 33 of file StandardLibrary.h.
Function Documentation
countSymbols()
static int clang::tooling::stdlib::countSymbols (Lang Language) static
Definition at line 57 of file StandardLibrary.cpp.
References C, and CXX.
Referenced by initialize().
ensureInitialized()
static void clang::tooling::stdlib::ensureInitialized () static
Definition at line 150 of file StandardLibrary.cpp.
References initialize(), and LastValue.
Referenced by clang::tooling::stdlib::Header::all(), clang::tooling::stdlib::Symbol::all(), clang::tooling::stdlib::Header::named(), clang::tooling::stdlib::Symbol::named(), and clang::tooling::stdlib::Recognizer::Recognizer().
getMappingPerLang()
static const SymbolHeaderMapping * clang::tooling::stdlib::getMappingPerLang (Lang L) static
Definition at line 53 of file StandardLibrary.cpp.
References LanguageMappings.
Referenced by clang::tooling::stdlib::Header::all(), clang::tooling::stdlib::Symbol::all(), clang::tooling::stdlib::Symbol::header(), clang::tooling::stdlib::Symbol::headers(), clang::tooling::stdlib::Header::name(), clang::tooling::stdlib::Symbol::name(), clang::tooling::stdlib::Header::named(), clang::tooling::stdlib::Symbol::named(), clang::tooling::stdlib::Symbol::qualifiedName(), and clang::tooling::stdlib::Symbol::scope().
initialize()
static int clang::tooling::stdlib::initialize (Lang Language) static
Definition at line 74 of file StandardLibrary.cpp.
References C, countSymbols(), CXX, and LanguageMappings.
Referenced by ensureInitialized().
Variable Documentation
LanguageMappings
SymbolHeaderMapping* clang::tooling::stdlib::LanguageMappings[static_cast< unsigned >(Lang::LastValue)+1] static
Definition at line 52 of file StandardLibrary.cpp.
Referenced by getMappingPerLang(), and initialize().