clang: clang::dataflow Namespace Reference
clang::dataflow Namespace Reference
Dataflow Directional Tag Classes.
Classes
class AggregateStorageLocation
A storage location which is subdivided into smaller storage locations that can be traced independently by abstract interpretation.
class Arena
The Arena owns the objects that model data within an analysis.
class ASTMatchSwitchBuilder
Collects cases of a "match switch": a collection of matchers paired with callbacks, which together define a switch that can be applied to a node whose type derives from BaseT.
class AtomicBoolValue
Models an atomic boolean.
struct backward_analysis_tag
class BoolValue
Models a boolean.
class CFGMatchSwitchBuilder
Collects cases of a "match switch": a collection of matchers paired with callbacks, which together define a switch that can be applied to an AST node contained in a CFG element.
class ChromiumCheckModel
Models the behavior of Chromium's CHECK, DCHECK, etc.
struct CNFFormula
A boolean formula in conjunctive normal form.
struct ContextSensitiveOptions
class ControlFlowContext
Holds CFG and other derived context that is needed to perform dataflow analysis.
class DataflowAnalysis
Base class template for dataflow analyses built on a single lattice type.
class DataflowAnalysisContext
Owns objects that encompass the state of a program and stores context that is used during dataflow analysis.
struct DataflowAnalysisOptions
struct DataflowAnalysisState
class DataflowModel
Abstract base class for dataflow "models": reusable analysis components that model a particular aspect of program semantics in the Environment.
class Environment
Holds the state of the program (store and heap) at a given program point.
class Formula
class FormulaBoolValue
Models a compound boolean formula.
struct forward_analysis_tag
class IntegerValue
Models an integer.
class Logger
A logger is notified as the analysis progresses.
class MapLattice
A lattice that maps keys to individual lattice elements.
class NoopAnalysis
class NoopLattice
Trivial lattice for dataflow analysis with exactly one element.
class PointerValue
Models a symbolic pointer. Specifically, any value of type T*.
class ReferenceValue
Models a dereferenced pointer.
class ScalarStorageLocation
A storage location that is not subdivided further for the purposes of abstract interpretation.
class Solver
An interface for a SAT solver that can be used by dataflow analyses.
class StmtToEnvMap
Maps statements to the environments of basic blocks that contain them.
class StorageLocation
Base class for elements of the local variable store and of the heap.
class TopBoolValue
A TopBoolValue represents a boolean that is explicitly unconstrained.
struct TransferState
A common form of state shared between the cases of a transfer function.
struct TransferStateForDiagnostics
A read-only version of TransferState.
class TypeErasedDataflowAnalysis
Type-erased base class for dataflow analyses built on a single lattice type.
struct TypeErasedDataflowAnalysisState
Type-erased model of the program at a given program point.
struct TypeErasedLattice
Type-erased lattice element container.
class UncheckedOptionalAccessDiagnoser
class UncheckedOptionalAccessModel
Dataflow analysis that models whether optionals hold values or not.
struct UncheckedOptionalAccessModelOptions
class Value
Base class for all values computed by abstract interpretation.
class WatchedLiteralsSolver
A SAT solver that is an implementation of Algorithm D from Knuth's The Art of Computer Programming Volume 4: Satisfiability, Fascicle 6.
class WatchedLiteralsSolverImpl
Typedefs
template<typename State , typename Result = void>
using CFGMatchSwitch
using FieldSet = llvm::SmallSetVector<const FieldDecl *, 4>
A set of FieldDecl *.
template<typename ElementLattice >
using VarMapLattice = MapLattice<const clang::VarDecl *, ElementLattice>
Convenience alias that captures the common use of map lattices to model in-scope variables.
template<typename T >
using MatchSwitchMatcher = ast_matchers::internal::Matcher<T>
template<typename T , typename State , typename Result = void>
using MatchSwitchAction
template<typename BaseT , typename State , typename Result = void>
using ASTMatchSwitch
using Variable = uint32_t
Boolean variables are represented as positive integers.
using Literal = uint32_t
Literals are represented as positive integers.
using ClauseID = uint32_t
Clause identifiers are represented as positive integers.
Enumerations
enum class SkipPast { None , Reference }
Indicates what kind of indirections should be skipped past when retrieving storage locations or values.
enum class ComparisonResult { Same , Different , Unknown }
Indicates the result of a tentative comparison.
enum class LatticeJoinEffect { Unchanged , Changed }
Effect indicating whether a lattice join operation resulted in a new value.
enum class Atom : unsigned
Identifies an atomic boolean variable such as "V1".
Functions
template<typename AnalysisT >
llvm::Expected< std::vector< std::optional< DataflowAnalysisState< typename AnalysisT::Lattice > > > > runDataflowAnalysis (const ControlFlowContext &CFCtx, AnalysisT &Analysis, const Environment &InitEnv, std::function< void(const CFGElement &, const DataflowAnalysisState< typename AnalysisT::Lattice > &)> PostVisitCFG=nullptr)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
const Expr & ignoreCFGOmittedNodes (const Expr &E)
Skip past nodes that the CFG does not emit.
const Stmt & ignoreCFGOmittedNodes (const Stmt &S)
FieldSet getObjectFields (QualType Type)
Returns the set of all fields in the type.
AggregateStorageLocation * getImplicitObjectLocation (const CXXMemberCallExpr &MCE, const Environment &Env)
Returns the storage location for the implicit object of a CXXMemberCallExpr, or null if none is defined in the environment.
AggregateStorageLocation * getBaseObjectLocation (const MemberExpr &ME, const Environment &Env)
Returns the storage location for the base object of a MemberExpr, or null if none is defined in the environment.
std::vector< FieldDecl * > getFieldsForInitListExpr (const RecordDecl *RD)
Returns the fields of RD that are initialized by an InitListExpr, in the order in which they appear in InitListExpr::inits().
StructValue & refreshStructValue (AggregateStorageLocation &Loc, Environment &Env)
Associates a new StructValue with Loc and returns the new value.
StructValue & refreshStructValue (const Expr &Expr, Environment &Env)
Associates a new StructValue with Expr and returns the new value.
llvm::StringRef debugString (Value::Kind Kind)
Returns a string representation of a value kind.
llvm::StringRef debugString (Solver::Result::Status Status)
Returns a string representation of the result status of a SAT check.
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Atom A)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Formula &F)
template<typename Key , typename ElementLattice >
std::ostream & operator<< (std::ostream &Os, const clang::dataflow::MapLattice< Key, ElementLattice > &M)
template<typename ElementLattice >
std::ostream & operator<< (std::ostream &Os, const clang::dataflow::VarMapLattice< ElementLattice > &M)
std::ostream & operator<< (std::ostream &OS, const NoopLattice &)
void copyRecord (AggregateStorageLocation &Src, AggregateStorageLocation &Dst, Environment &Env)
Copies a record (struct, class, or union) from Src to Dst.
bool recordsEqual (const AggregateStorageLocation &Loc1, const Environment &Env1, const AggregateStorageLocation &Loc2, const Environment &Env2)
Returns whether the records Loc1 and Loc2 are equal.
bool recordsEqual (const AggregateStorageLocation &Loc1, const AggregateStorageLocation &Loc2, const Environment &Env)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Solver::Result &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, Solver::Result::Assignment)
void transfer (const StmtToEnvMap &StmtToEnv, const Stmt &S, Environment &Env)
Evaluates S and updates Env accordingly.
TypeErasedDataflowAnalysisState transferBlock (const ControlFlowContext &CFCtx, llvm::ArrayRef< std::optional< TypeErasedDataflowAnalysisState > > BlockStates, const CFGBlock &Block, const Environment &InitEnv, TypeErasedDataflowAnalysis &Analysis, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG=nullptr)
Transfers the state of a basic block by evaluating each of its elements in the context of Analysis and the states of its predecessors that are available in BlockStates.
llvm::Expected< std::vector< std::optional< TypeErasedDataflowAnalysisState > > > runTypeErasedDataflowAnalysis (const ControlFlowContext &CFCtx, TypeErasedDataflowAnalysis &Analysis, const Environment &InitEnv, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG=nullptr)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
bool areEquivalentValues (const Value &Val1, const Value &Val2)
An equivalence relation for values.
StorageLocation * getChild (const ValueDecl &Field) const
Models a value of struct or class type.
static std::pair< const Formula *, const Formula * > canonicalFormulaPair (const Formula &LHS, const Formula &RHS)
static llvm::DenseMap< const Stmt *, const CFGBlock * > buildStmtToBasicBlockMap (const CFG &Cfg)
Returns a map from statements to basic blocks that contain them.
static llvm::BitVector findReachableBlocks (const CFG &Cfg)
static std::unique_ptr< Logger > makeLoggerFromCommandLine ()
template<typename K , typename V >
llvm::DenseMap< K, V > intersectDenseMaps (const llvm::DenseMap< K, V > &Map1, const llvm::DenseMap< K, V > &Map2)
Returns a map consisting of key-value entries that are present in both maps.
static bool compareDistinctValues (QualType Type, Value &Val1, const Environment &Env1, Value &Val2, const Environment &Env2, Environment::ValueModel &Model)
static Value * mergeDistinctValues (QualType Type, Value &Val1, const Environment &Env1, Value &Val2, const Environment &Env2, Environment &MergedEnv, Environment::ValueModel &Model)
Attempts to merge distinct values Val1 and Val2 in Env1 and Env2, respectively, of the same type Type.
static Value & widenDistinctValues (QualType Type, Value &Prev, const Environment &PrevEnv, Value &Current, Environment &CurrentEnv, Environment::ValueModel &Model)
static void insertIfGlobal (const Decl &D, llvm::DenseSet< const VarDecl * > &Vars)
Initializes a global storage value.
static void insertIfFunction (const Decl &D, llvm::DenseSet< const FunctionDecl * > &Funcs)
static void getFieldsGlobalsAndFuncs (const Decl &D, FieldSet &Fields, llvm::DenseSet< const VarDecl * > &Vars, llvm::DenseSet< const FunctionDecl * > &Funcs)
static void getFieldsGlobalsAndFuncs (const Stmt &S, FieldSet &Fields, llvm::DenseSet< const VarDecl * > &Vars, llvm::DenseSet< const FunctionDecl * > &Funcs)
Traverses S and inserts into Fields, Vars and Funcs any fields, global variables and functions that are declared in or referenced from sub-statements.
static llvm::StringLiteral sigil (Formula::Kind K)
bool isCheckLikeMethod (llvm::SmallDenseSet< const CXXMethodDecl * > &CheckDecls, const CXXMethodDecl &D)
Determines whether D is one of the methods used to implement Chromium's CHECK macros.
static bool isTopLevelNamespaceWithName (const NamespaceDecl &NS, llvm::StringRef Name)
static bool hasOptionalClassName (const CXXRecordDecl &RD)
static BoolValue & evaluateBooleanEquality (const Expr &LHS, const Expr &RHS, Environment &Env)
static BoolValue & unpackValue (BoolValue &V, Environment &Env)
static Value * maybeUnpackLValueExpr (const Expr &E, Environment &Env)
static void propagateValue (const Expr &From, const Expr &To, Environment &Env)
static void propagateStorageLocation (const Expr &From, const Expr &To, Environment &Env)
static void propagateValueOrStorageLocation (const Expr &From, const Expr &To, Environment &Env)
static int blockIndexInPredecessor (const CFGBlock &Pred, const CFGBlock &Block)
Returns the index of Block in the successors of Pred.
static bool isLoopHead (const CFGBlock &B)
static TypeErasedDataflowAnalysisState computeBlockInputState (const CFGBlock &Block, AnalysisContext &AC)
Computes the input state for a given basic block by joining the output states of its predecessors.
static void builtinTransferStatement (const CFGStmt &Elt, TypeErasedDataflowAnalysisState &InputState, AnalysisContext &AC)
Built-in transfer function for CFGStmt.
static void builtinTransferInitializer (const CFGInitializer &Elt, TypeErasedDataflowAnalysisState &InputState)
Built-in transfer function for CFGInitializer.
static void builtinTransfer (const CFGElement &Elt, TypeErasedDataflowAnalysisState &State, AnalysisContext &AC)
static TypeErasedDataflowAnalysisState transferCFGBlock (const CFGBlock &Block, AnalysisContext &AC, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG=nullptr)
Transfers State by evaluating each element in the Block based on the AC.Analysis specified.
static bool areEquivalentIndirectionValues (const Value &Val1, const Value &Val2)
raw_ostream & operator<< (raw_ostream &OS, const Value &Val)
static constexpr Literal posLit (Variable V)
Returns the positive literal V.
static constexpr Literal negLit (Variable V)
Returns the negative literal !V.
static constexpr Literal notLit (Literal L)
Returns the negated literal !L.
static constexpr Variable var (Literal L)
Returns the variable of L.
CNFFormula buildCNF (const llvm::ArrayRef< const Formula * > &Vals)
Converts the conjunction of Vals into a formula in conjunctive normal form where each clause has at least one and at most three literals.
Variables
static constexpr int MaxCompositeValueDepth = 3
static constexpr int MaxCompositeValueSize = 1000
static constexpr Variable NullVar = 0
A null boolean variable is used as a placeholder in various data structures and algorithms.
static constexpr Literal NullLit = 0
A null literal is used as a placeholder in various data structures and algorithms.
static constexpr ClauseID NullClause = 0
A null clause identifier is used as a placeholder in various data structures and algorithms.
Detailed Description
Dataflow Directional Tag Classes.
These are used for tag dispatching within the dataflow solver/transfer functions to determine what direction a dataflow analysis flows.
Typedef Documentation
ASTMatchSwitch
template<typename BaseT , typename State , typename Result = void> using clang::dataflow::ASTMatchSwitch
Initial value:
    std::function<Result(const BaseT &, ASTContext &, State &)>
Definition at line 68 of file MatchSwitch.h.
CFGMatchSwitch
template<typename State , typename Result = void> using clang::dataflow::CFGMatchSwitch
Initial value:
    std::function<Result(const CFGElement &, ASTContext &, State &)>
Definition at line 33 of file CFGMatchSwitch.h.
ClauseID
using clang::dataflow::ClauseID = uint32_t
Clause identifiers are represented as positive integers.
Definition at line 75 of file WatchedLiteralsSolver.cpp.
FieldSet
using clang::dataflow::FieldSet = llvm::SmallSetVector<const FieldDecl *, 4>
A set of FieldDecl *.
Use SmallSetVector to guarantee deterministic iteration order.
Definition at line 56 of file DataflowAnalysisContext.h.
Literal
using clang::dataflow::Literal = uint32_t
Literals are represented as positive integers.
Specifically, for a boolean variable V that is represented as the positive integer I, the positive literal V is represented as the integer 2*I and the negative literal !V is represented as the integer 2*I+1.
Definition at line 56 of file WatchedLiteralsSolver.cpp.
MatchSwitchAction
template<typename T , typename State , typename Result = void> using clang::dataflow::MatchSwitchAction
Initial value:
 std::function<Result(
    const T *, const ast_matchers::MatchFinder::MatchResult &, State &)>
Definition at line 64 of file MatchSwitch.h.
MatchSwitchMatcher
template<typename T > using clang::dataflow::MatchSwitchMatcher = ast_matchers::internal::Matcher<T>
Definition at line 61 of file MatchSwitch.h.
Variable
using clang::dataflow::Variable = uint32_t
Boolean variables are represented as positive integers.
Definition at line 46 of file WatchedLiteralsSolver.cpp.
VarMapLattice
template<typename ElementLattice > using clang::dataflow::VarMapLattice = MapLattice<const clang::VarDecl *, ElementLattice>
Convenience alias that captures the common use of map lattices to model in-scope variables.
Definition at line 112 of file MapLattice.h.
Enumeration Type Documentation
Atom
enum class clang::dataflow::Atom : unsigned strong
Identifies an atomic boolean variable such as "V1".
This often represents an assertion that is interesting to the analysis but cannot immediately be proven true or false. For example:
V1 may mean "the program reaches this point",
V2 may mean "the parameter was null"
We can use these variables in formulas to describe relationships we know to be true: "if the parameter was null, the program reaches this point". We also express hypotheses as formulas, and use a SAT solver to check whether they are consistent with the known facts.
Definition at line 36 of file Formula.h.
ComparisonResult
enum class clang::dataflow::ComparisonResult strong
Indicates the result of a tentative comparison.
Enumerator
Same
Different
Unknown
Definition at line 54 of file DataflowEnvironment.h.
LatticeJoinEffect
enum class clang::dataflow::LatticeJoinEffect strong
Effect indicating whether a lattice join operation resulted in a new value.
Enumerator
Unchanged
Changed
Definition at line 23 of file DataflowLattice.h.
SkipPast
enum class clang::dataflow::SkipPast strong
Indicates what kind of indirections should be skipped past when retrieving storage locations or values.
FIXME: Consider renaming this or replacing it with a more appropriate model. See the discussion in https://reviews.llvm.org/D116596 for context.
Enumerator
None
No indirections should be skipped past.
Reference
An optional reference should be skipped past.
Definition at line 46 of file DataflowEnvironment.h.
Function Documentation
areEquivalentIndirectionValues()
static bool clang::dataflow::areEquivalentIndirectionValues (const Value & Val1, const Value & Val2) static
Definition at line 20 of file Value.cpp.
References clang::cast().
Referenced by areEquivalentValues().
areEquivalentValues()
bool clang::dataflow::areEquivalentValues (const Value & Val1, const Value & Val2)
An equivalence relation for values.
It obeys reflexivity, symmetry and transitivity. It does not include comparison of Properties.
Computes equivalence for these subclasses:
ReferenceValue, PointerValue – pointee locations are equal. Does not compute deep equality of Value at said location.
TopBoolValue – both are TopBoolValues.
Otherwise, falls back to pointer equality.
Definition at line 33 of file Value.cpp.
References areEquivalentIndirectionValues(), and clang::dataflow::Value::getKind().
Referenced by clang::dataflow::Environment::equivalentTo(), clang::dataflow::Environment::join(), and clang::dataflow::Environment::widen().
blockIndexInPredecessor()
static int clang::dataflow::blockIndexInPredecessor (const CFGBlock & Pred, const CFGBlock & Block) static
Returns the index of Block in the successors of Pred.
Definition at line 46 of file TypeErasedDataflowAnalysis.cpp.
References clang::Block, clang::CFGBlock::succ_begin(), and clang::CFGBlock::succs().
Referenced by computeBlockInputState().
buildCNF()
CNFFormula clang::dataflow::buildCNF (const llvm::ArrayRef< const Formula * > & Vals)
Converts the conjunction of Vals into a formula in conjunctive normal form where each clause has at least one and at most three literals.
Definition at line 181 of file WatchedLiteralsSolver.cpp.
References clang::dataflow::CNFFormula::addClause(), clang::dataflow::Formula::And, clang::dataflow::Formula::AtomRef, clang::dataflow::Formula::Equal, clang::dataflow::Formula::getAtom(), clang::dataflow::Formula::Implies, clang::dataflow::Formula::kind(), negLit(), clang::dataflow::Formula::Not, clang::dataflow::Formula::operands(), clang::dataflow::Formula::Or, and posLit().
buildStmtToBasicBlockMap()
static llvm::DenseMap< const Stmt *, const CFGBlock * > clang::dataflow::buildStmtToBasicBlockMap (const CFG & Cfg) static
Returns a map from statements to basic blocks that contain them.
Definition at line 29 of file ControlFlowContext.cpp.
References clang::Block.
Referenced by clang::dataflow::ControlFlowContext::build().
builtinTransfer()
static void clang::dataflow::builtinTransfer (const CFGElement & Elt, TypeErasedDataflowAnalysisState & State, AnalysisContext & AC) static
Definition at line 425 of file TypeErasedDataflowAnalysis.cpp.
References builtinTransferInitializer(), builtinTransferStatement(), clang::CFGElement::castAs(), clang::CFGElement::getKind(), clang::CFGElement::Initializer, and clang::CFGElement::Statement.
Referenced by transferCFGBlock().
builtinTransferInitializer()
static void clang::dataflow::builtinTransferInitializer (const CFGInitializer & Elt, TypeErasedDataflowAnalysisState & InputState) static
Built-in transfer function for CFGInitializer.
Definition at line 363 of file TypeErasedDataflowAnalysis.cpp.
References clang::cast(), clang::IndirectFieldDecl::chain(), copyRecord(), clang::dataflow::TypeErasedDataflowAnalysisState::Env, Env, clang::dataflow::AggregateStorageLocation::getChild(), clang::CFGInitializer::getInitializer(), clang::dataflow::Environment::getStorageLocationStrict(), clang::dataflow::Environment::getThisPointeeStorageLocation(), clang::dataflow::Environment::getValueStrict(), clang::Member, clang::dataflow::AggregateStorageLocation::setChild(), and clang::dataflow::Environment::setValue().
Referenced by builtinTransfer().
builtinTransferStatement()
static void clang::dataflow::builtinTransferStatement (const CFGStmt & Elt, TypeErasedDataflowAnalysisState & InputState, AnalysisContext & AC) static
Built-in transfer function for CFGStmt.
Definition at line 353 of file TypeErasedDataflowAnalysis.cpp.
References clang::dataflow::TypeErasedDataflowAnalysisState::Env, clang::CFGStmt::getStmt(), and transfer().
Referenced by builtinTransfer().
canonicalFormulaPair()
static std::pair< const Formula *, const Formula * > clang::dataflow::canonicalFormulaPair (const Formula & LHS, const Formula & RHS) static
Definition at line 15 of file Arena.cpp.
Referenced by clang::dataflow::Arena::makeAnd(), clang::dataflow::Arena::makeEquals(), and clang::dataflow::Arena::makeOr().
compareDistinctValues()
static bool clang::dataflow::compareDistinctValues (QualType Type, Value & Val1, const Environment & Env1, Value & Val2, const Environment & Env2, Environment::ValueModel & Model) static
Definition at line 53 of file DataflowEnvironment.cpp.
References Different, clang::dataflow::Value::getKind(), clang::dataflow::Value::Integer, clang::dataflow::Value::Pointer, clang::dataflow::Value::Reference, Same, clang::dataflow::Value::Struct, and Unknown.
Referenced by clang::dataflow::Environment::equivalentTo().
computeBlockInputState()
static TypeErasedDataflowAnalysisState clang::dataflow::computeBlockInputState (const CFGBlock & Block, AnalysisContext & AC) static
Computes the input state for a given basic block by joining the output states of its predecessors.
Requirements:
All predecessors of Block except those with loop back edges must have already been transferred. States in AC.BlockStates that are set to std::nullopt represent basic blocks that are not evaluated yet.
Definition at line 278 of file TypeErasedDataflowAnalysis.cpp.
References clang::Block, blockIndexInPredecessor(), clang::dataflow::TypeErasedDataflowAnalysis::builtinOptions(), clang::Cond, clang::Copy, clang::dataflow::TypeErasedDataflowAnalysisState::fork(), clang::dataflow::ControlFlowContext::getStmtToBlock(), and clang::dataflow::TypeErasedDataflowAnalysis::transferBranchTypeErased().
Referenced by transferCFGBlock().
copyRecord()
void clang::dataflow::copyRecord (AggregateStorageLocation & Src, AggregateStorageLocation & Dst, Environment & Env)
Copies a record (struct, class, or union) from Src to Dst.
This performs a deep copy, i.e. it copies every field and recurses on fields of record type. It also copies properties from the StructValue associated with Src to the StructValue associated with Dst (if these StructValues exist).
If there is a StructValue associated with Dst in the environment, this function creates a new StructValue and associates it with Dst; clients need to be aware of this and must not assume that the StructValue associated with Dst remains the same after the call.
We create a new StructValue rather than modifying properties on the old StructValue because the old StructValue may be shared with other Environments, and we don't want changes to properties to be visible there.
Requirements:
Src and Dst must have the same canonical unqualified type.
Definition at line 17 of file RecordOps.cpp.
References clang::dataflow::AggregateStorageLocation::children(), copyRecord(), Env, clang::QualType::getCanonicalType(), clang::dataflow::AggregateStorageLocation::getChild(), clang::dataflow::StorageLocation::getType(), clang::QualType::getUnqualifiedType(), and clang::dataflow::AggregateStorageLocation::setChild().
Referenced by builtinTransferInitializer(), and copyRecord().
debugString() [1/2]
llvm::StringRef clang::dataflow::debugString (Solver::Result::Status Status)
Returns a string representation of the result status of a SAT check.
Definition at line 56 of file DebugSupport.cpp.
References clang::dataflow::Solver::Result::Satisfiable, clang::dataflow::Solver::Result::TimedOut, and clang::dataflow::Solver::Result::Unsatisfiable.
debugString() [2/2]
llvm::StringRef clang::dataflow::debugString (Value::Kind Kind)
Returns a string representation of a value kind.
Definition at line 25 of file DebugSupport.cpp.
References clang::dataflow::Value::AtomicBool, clang::dataflow::Value::FormulaBool, clang::dataflow::Value::Integer, clang::dataflow::Value::Pointer, clang::dataflow::Value::Reference, clang::dataflow::Value::Struct, and clang::dataflow::Value::TopBool.
Referenced by operator<<(), and operator<<().
evaluateBooleanEquality()
static BoolValue & clang::dataflow::evaluateBooleanEquality (const Expr & LHS, const Expr & RHS, Environment & Env) static
Definition at line 50 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getBoolLiteralValue(), clang::dataflow::Environment::getValueStrict(), clang::dataflow::Environment::makeAtomicBoolValue(), and clang::dataflow::Environment::makeIff().
findReachableBlocks()
static llvm::BitVector clang::dataflow::findReachableBlocks (const CFG & Cfg) static
Definition at line 48 of file ControlFlowContext.cpp.
References clang::Block, clang::CFG::getEntry(), clang::CFG::getNumBlockIDs(), and clang::CFGBlock::succs().
Referenced by clang::dataflow::ControlFlowContext::build().
getBaseObjectLocation()
AggregateStorageLocation * clang::dataflow::getBaseObjectLocation (const MemberExpr & ME, const Environment & Env)
Returns the storage location for the base object of a MemberExpr, or null if none is defined in the environment.
Dereferences the pointer if the member expression was written using ->.
Definition at line 964 of file DataflowEnvironment.cpp.
References clang::cast(), Env, clang::MemberExpr::getBase(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::MemberExpr::isArrow(), and Reference.
getChild()
StorageLocation * clang::dataflow::getChild (const ValueDecl & Field) const
Models a value of struct or class type.
In C++, prvalues of class type serve only a limited purpose: They can only be used to initialize a result object. It is not possible to access member variables or call member functions on a prvalue of class type. Correspondingly, StructValue also serves only two limited purposes:
It conveys a prvalue of class type from the place where the object is constructed to the result object that it initializes.
When creating a prvalue of class type, we already need a storage location for this, even though prvalues are otherwise not associated with storage locations. StructValue is therefore essentially a wrapper for a storage location, which is then used to set the storage location for the result object when we process the AST node for that result object.
For example: MyStruct S = MyStruct(3);
In this example, MyStruct(3) is a prvalue, which is modeled as a /StructValuethat wraps anAbstractStorageLocation. This AbstractStorageLocationis then used as the storage location forS. / / - It allows properties to be associated with an object of class type. / Note that when doing so, you should avoid mutating the properties of an / existingStructValuein place, as these changes would be visible to / otherEnvironments that share the sameStructValue. Instead, associate / a newStructValuewith theAggregateStorageLocationand set the / properties on this newStructValue. (See alsorefreshStructValue()in / DataflowEnvironment.h, which makes this easy.) / Note also that this implies that it is common for the same /AggregateStorageLocationto be associated with differentStructValues / in different environments. / Over time, we may eliminateStructValue` entirely. See also the discussion / here: https://reviews.llvm.org/D155204#inline-1503204 class StructValue final : public Value { public: explicit StructValue(AggregateStorageLocation &Loc) : Value(Kind::Struct), Loc(Loc) {}
static bool classof(const Value *Val) { return Val->getKind() == Kind::Struct; }
/ Returns the storage location that this StructValue is associated with. AggregateStorageLocation &getAggregateLoc() const { return Loc; }
/ Convenience function that returns the child storage location for Field. / See also the documentation for AggregateStorageLocation::getChild().
Definition at line 248 of file Value.h.
References clang::dataflow::AggregateStorageLocation::getChild(), and getChild().
Referenced by getChild().
getFieldsForInitListExpr()
std::vector< FieldDecl * > clang::dataflow::getFieldsForInitListExpr (const RecordDecl * RD)
Returns the fields of RD that are initialized by an InitListExpr, in the order in which they appear in InitListExpr::inits().
Definition at line 980 of file DataflowEnvironment.cpp.
References clang::RecordDecl::fields().
Referenced by getFieldsGlobalsAndFuncs().
getFieldsGlobalsAndFuncs() [1/2]
static void clang::dataflow::getFieldsGlobalsAndFuncs (const Decl & D, FieldSet & Fields, llvm::DenseSet< const VarDecl * > & Vars, llvm::DenseSet< const FunctionDecl * > & Funcs) static
Definition at line 195 of file DataflowEnvironment.cpp.
References insertIfFunction(), and insertIfGlobal().
Referenced by getFieldsGlobalsAndFuncs().
getFieldsGlobalsAndFuncs() [2/2]
static void clang::dataflow::getFieldsGlobalsAndFuncs (const Stmt & S, FieldSet & Fields, llvm::DenseSet< const VarDecl * > & Vars, llvm::DenseSet< const FunctionDecl * > & Funcs) static
Traverses S and inserts into Fields, Vars and Funcs any fields, global variables and functions that are declared in or referenced from sub-statements.
Definition at line 212 of file DataflowEnvironment.cpp.
References getFieldsForInitListExpr(), getFieldsGlobalsAndFuncs(), insertIfFunction(), and insertIfGlobal().
getImplicitObjectLocation()
AggregateStorageLocation * clang::dataflow::getImplicitObjectLocation (const CXXMemberCallExpr & MCE, const Environment & Env)
Returns the storage location for the implicit object of a CXXMemberCallExpr, or null if none is defined in the environment.
Dereferences the pointer if the member call expression was written using ->.
Definition at line 947 of file DataflowEnvironment.cpp.
References clang::cast(), Env, clang::CXXMemberCallExpr::getImplicitObjectArgument(), clang::dataflow::Environment::getStorageLocation(), clang::Expr::getType(), clang::dataflow::Environment::getValue(), clang::Type::isPointerType(), and Reference.
getObjectFields()
clang::dataflow::FieldSet clang::dataflow::getObjectFields (QualType Type)
Returns the set of all fields in the type.
Gets the set of all fields in the type.
Definition at line 323 of file DataflowAnalysisContext.cpp.
References getFieldsFromClassHierarchy().
Referenced by clang::dataflow::DataflowAnalysisContext::getModeledFields().
hasOptionalClassName()
static bool clang::dataflow::hasOptionalClassName (const CXXRecordDecl & RD) static
Definition at line 48 of file UncheckedOptionalAccessModel.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::DeclarationName::isIdentifier(), isTopLevelNamespaceWithName(), and N.
ignoreCFGOmittedNodes() [1/2]
const Expr & clang::dataflow::ignoreCFGOmittedNodes (const Expr & E)
Skip past nodes that the CFG does not emit.
These nodes are invisible to flow-sensitive analysis, and should be ignored as they will effectively not exist.
ParenExpr - The CFG takes the operator precedence into account, but otherwise omits the node afterwards.
ExprWithCleanups - The CFG will generate the appropriate calls to destructors and then omit the node.
Definition at line 290 of file DataflowAnalysisContext.cpp.
Referenced by clang::dataflow::StmtToEnvMap::getEnvironment(), clang::dataflow::DataflowAnalysisContext::getStorageLocation(), clang::dataflow::Environment::getStorageLocation(), ignoreCFGOmittedNodes(), clang::dataflow::DataflowAnalysisContext::setStorageLocation(), and clang::dataflow::Environment::setStorageLocation().
ignoreCFGOmittedNodes() [2/2]
const Stmt & clang::dataflow::ignoreCFGOmittedNodes (const Stmt & S)
Definition at line 301 of file DataflowAnalysisContext.cpp.
References ignoreCFGOmittedNodes().
insertIfFunction()
static void clang::dataflow::insertIfFunction (const Decl & D, llvm::DenseSet< const FunctionDecl * > & Funcs) static
Definition at line 188 of file DataflowEnvironment.cpp.
Referenced by getFieldsGlobalsAndFuncs(), and getFieldsGlobalsAndFuncs().
insertIfGlobal()
static void clang::dataflow::insertIfGlobal (const Decl & D, llvm::DenseSet< const VarDecl * > & Vars) static
Initializes a global storage value.
Definition at line 181 of file DataflowEnvironment.cpp.
References V.
Referenced by getFieldsGlobalsAndFuncs(), and getFieldsGlobalsAndFuncs().
intersectDenseMaps()
template<typename K , typename V > llvm::DenseMap< K, V > clang::dataflow::intersectDenseMaps (const llvm::DenseMap< K, V > & Map1, const llvm::DenseMap< K, V > & Map2)
Returns a map consisting of key-value entries that are present in both maps.
Definition at line 42 of file DataflowEnvironment.cpp.
References clang::Result.
Referenced by clang::dataflow::Environment::join().
isCheckLikeMethod()
bool clang::dataflow::isCheckLikeMethod (llvm::SmallDenseSet< const CXXMethodDecl * > & CheckDecls, const CXXMethodDecl & D)
Determines whether D is one of the methods used to implement Chromium's CHECK macros.
Populates CheckDecls, if empty.
Definition at line 19 of file ChromiumCheckModel.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::CXXMethodDecl::getParent(), clang::DeclarationName::isIdentifier(), clang::CXXMethodDecl::isStatic(), clang::CXXRecordDecl::methods(), and N.
Referenced by clang::dataflow::ChromiumCheckModel::transfer().
isLoopHead()
static bool clang::dataflow::isLoopHead (const CFGBlock & B) static
Definition at line 55 of file TypeErasedDataflowAnalysis.cpp.
References clang::CFGBlock::getTerminatorStmt().
Referenced by runTypeErasedDataflowAnalysis().
isTopLevelNamespaceWithName()
static bool clang::dataflow::isTopLevelNamespaceWithName (const NamespaceDecl & NS, llvm::StringRef Name) static
Definition at line 42 of file UncheckedOptionalAccessModel.cpp.
References clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::DeclContext::getParent(), clang::DeclarationName::isIdentifier(), and clang::DeclContext::isTranslationUnit().
Referenced by hasOptionalClassName().
makeLoggerFromCommandLine()
static std::unique_ptr< Logger > clang::dataflow::makeLoggerFromCommandLine () static
Definition at line 237 of file DataflowAnalysisContext.cpp.
References DataflowLog(), clang::File, clang::dataflow::Logger::html(), and clang::dataflow::Logger::textual().
Referenced by clang::dataflow::DataflowAnalysisContext::DataflowAnalysisContext().
maybeUnpackLValueExpr()
static Value * clang::dataflow::maybeUnpackLValueExpr (const Expr & E, Environment & Env) static
Definition at line 76 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getStorageLocationStrict(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::setValue(), and unpackValue().
mergeDistinctValues()
static Value * clang::dataflow::mergeDistinctValues (QualType Type, Value & Val1, const Environment & Env1, Value & Val2, const Environment & Env2, Environment & MergedEnv, Environment::ValueModel & Model) static
Attempts to merge distinct values Val1 and Val2 in Env1 and Env2, respectively, of the same type Type.
Merging generally produces a single value that (soundly) approximates the two inputs, although the actual meaning depends on Model.
Definition at line 90 of file DataflowEnvironment.cpp.
References clang::dataflow::Environment::addToFlowCondition(), clang::dataflow::Environment::arena(), clang::cast(), clang::dataflow::Environment::create(), clang::dataflow::Environment::createValue(), clang::dataflow::Environment::getFlowConditionToken(), and clang::dataflow::Arena::makeAtomRef().
Referenced by clang::dataflow::Environment::join().
negLit()
static constexpr Literal clang::dataflow::negLit (Variable V) static constexpr
Returns the negative literal !V.
Definition at line 66 of file WatchedLiteralsSolver.cpp.
References V.
Referenced by buildCNF(), clang::dataflow::WatchedLiteralsSolverImpl::solve(), and clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().
notLit()
static constexpr Literal clang::dataflow::notLit (Literal L) static constexpr
Returns the negated literal !L.
Definition at line 69 of file WatchedLiteralsSolver.cpp.
operator<<() [1/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, const Solver::Result & R)
Definition at line 68 of file DebugSupport.cpp.
References debugString(), clang::dataflow::Solver::Result::getSolution(), and clang::dataflow::Solver::Result::getStatus().
operator<<() [2/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, Solver::Result::Assignment Assignment)
Definition at line 45 of file DebugSupport.cpp.
References clang::dataflow::Solver::Result::AssignedFalse, and clang::dataflow::Solver::Result::AssignedTrue.
operator<<() [3/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, Atom A) inline
Definition at line 116 of file Formula.h.
operator<<() [4/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, const Formula & F) inline
Definition at line 119 of file Formula.h.
References clang::dataflow::Formula::print().
operator<<() [5/8]
raw_ostream & clang::dataflow::operator<< (raw_ostream & OS, const Value & Val)
Definition at line 39 of file Value.cpp.
References clang::cast(), debugString(), clang::dataflow::Value::getKind(), clang::dataflow::Value::Pointer, and clang::dataflow::Value::Reference.
operator<<() [6/8]
template<typename Key , typename ElementLattice > std::ostream & clang::dataflow::operator<< (std::ostream & Os, const clang::dataflow::MapLattice< Key, ElementLattice > & M)
Definition at line 115 of file MapLattice.h.
operator<<() [7/8]
template<typename ElementLattice > std::ostream & clang::dataflow::operator<< (std::ostream & Os, const clang::dataflow::VarMapLattice< ElementLattice > & M)
Definition at line 128 of file MapLattice.h.
operator<<() [8/8]
std::ostream & clang::dataflow::operator<< (std::ostream & OS, const NoopLattice &) inline
Definition at line 34 of file NoopLattice.h.
posLit()
static constexpr Literal clang::dataflow::posLit (Variable V) static constexpr
Returns the positive literal V.
Definition at line 63 of file WatchedLiteralsSolver.cpp.
References V.
Referenced by buildCNF(), clang::dataflow::WatchedLiteralsSolverImpl::solve(), and clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().
propagateStorageLocation()
static void clang::dataflow::propagateStorageLocation (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 98 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getStorageLocationStrict(), and clang::dataflow::Environment::setStorageLocationStrict().
Referenced by propagateValueOrStorageLocation().
propagateValue()
static void clang::dataflow::propagateValue (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 93 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getValueStrict(), and clang::dataflow::Environment::setValueStrict().
Referenced by propagateValueOrStorageLocation().
propagateValueOrStorageLocation()
static void clang::dataflow::propagateValueOrStorageLocation (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 107 of file Transfer.cpp.
References Env, clang::Expr::isGLValue(), propagateStorageLocation(), and propagateValue().
recordsEqual() [1/2]
bool clang::dataflow::recordsEqual (const AggregateStorageLocation & Loc1, const AggregateStorageLocation & Loc2, const Environment & Env) inline
Definition at line 67 of file RecordOps.h.
References Env, and recordsEqual().
recordsEqual() [2/2]
bool clang::dataflow::recordsEqual (const AggregateStorageLocation & Loc1, const Environment & Env1, const AggregateStorageLocation & Loc2, const Environment & Env2)
Returns whether the records Loc1 and Loc2 are equal.
Values for Loc1 are retrieved from Env1, and values for Loc2 are retrieved from Env2. A convenience overload retrieves values for Loc1 and Loc2 from the same environment.
This performs a deep comparison, i.e. it compares every field and recurses on fields of record type. Fields of reference type compare equal if they refer to the same storage location. If StructValues are associated with Loc1 and Loc2, it also compares the properties on those StructValues.
Note on how to interpret the result:
If this returns true, the records are guaranteed to be equal at runtime.
If this returns false, the records may still be equal at runtime; our analysis merely cannot guarantee that they will be equal.
Requirements:
Src and Dst must have the same canonical unqualified type.
Definition at line 64 of file RecordOps.cpp.
References clang::dataflow::AggregateStorageLocation::children(), clang::QualType::getCanonicalType(), clang::dataflow::AggregateStorageLocation::getChild(), clang::dataflow::StorageLocation::getType(), clang::QualType::getUnqualifiedType(), clang::dataflow::Environment::getValue(), and recordsEqual().
Referenced by recordsEqual(), and recordsEqual().
refreshStructValue() [1/2]
StructValue & clang::dataflow::refreshStructValue (AggregateStorageLocation & Loc, Environment & Env)
Associates a new StructValue with Loc and returns the new value.
It is not defined whether the field values remain the same or not.
This function is primarily intended for use by checks that set custom properties on StructValues to model the state of these values. Such checks should avoid modifying the properties of an existing StructValue because these changes would be visible to other Environments that share the same StructValue. Instead, call refreshStructValue(), then set the properties on the new StructValue that it returns. Typical usage:
refreshStructValue(Loc, Env).setProperty("my_prop", MyPropValue);
Definition at line 992 of file DataflowEnvironment.cpp.
References clang::dataflow::Environment::create(), Env, and clang::dataflow::Environment::setValue().
refreshStructValue() [2/2]
StructValue & clang::dataflow::refreshStructValue (const Expr & Expr, Environment & Env)
Associates a new StructValue with Expr and returns the new value.
See also documentation for the overload above.
Definition at line 999 of file DataflowEnvironment.cpp.
References clang::cast(), clang::dataflow::Environment::create(), clang::dataflow::Environment::createValue(), Env, clang::dataflow::Environment::getStorageLocationStrict(), clang::Expr::getType(), clang::dataflow::Environment::getValueStrict(), clang::Expr::isPRValue(), clang::Type::isRecordType(), clang::dataflow::Environment::setStorageLocationStrict(), clang::dataflow::Environment::setValue(), and clang::dataflow::Environment::setValueStrict().
runDataflowAnalysis()
template<typename AnalysisT > llvm::Expected< std::vector< std::optional< DataflowAnalysisState< typename AnalysisT::Lattice > > > > clang::dataflow::runDataflowAnalysis (const ControlFlowContext & CFCtx, AnalysisT & Analysis, const Environment & InitEnv, std::function< void(const CFGElement &, const DataflowAnalysisState< typename AnalysisT::Lattice > &)> PostVisitCFG = nullptr)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
The returned vector, if any, will have the same size as the number of CFG blocks, with indices corresponding to basic block IDs. Returns an error if the dataflow analysis cannot be performed successfully. Otherwise, calls PostVisitCFG on each CFG element with the final analysis results at that program point.
Definition at line 196 of file DataflowAnalysis.h.
References Analysis, BlockStates, CFCtx, InitEnv, and runTypeErasedDataflowAnalysis().
runTypeErasedDataflowAnalysis()
llvm::Expected< std::vector< std::optional< TypeErasedDataflowAnalysisState > > > clang::dataflow::runTypeErasedDataflowAnalysis (const ControlFlowContext & CFCtx, TypeErasedDataflowAnalysis & Analysis, const Environment & InitEnv, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG = nullptr)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
Indices of the returned vector correspond to basic block IDs. Returns an error if the dataflow analysis cannot be performed successfully. Otherwise, calls PostVisitCFG on each CFG element with the final analysis results at that program point.
Definition at line 504 of file TypeErasedDataflowAnalysis.cpp.
References Analysis, clang::Block, clang::dataflow::Logger::blockConverged(), BlockStates, CFCtx, clang::DataflowWorklistBase< Comp, QueueSize >::dequeue(), clang::dataflow::Environment::dump(), clang::ForwardDataflowWorklist::enqueueSuccessors(), clang::dataflow::TypeErasedDataflowAnalysisState::Env, clang::dataflow::Environment::fork(), clang::CFGBlock::getBlockID(), clang::dataflow::ControlFlowContext::getCFG(), clang::CFG::getEntry(), InitEnv, clang::dataflow::TypeErasedDataflowAnalysis::isEqualTypeErased(), isLoopHead(), clang::dataflow::TypeErasedDataflowAnalysisState::Lattice, clang::CFG::size(), transferCFGBlock(), clang::dataflow::TypeErasedDataflowAnalysis::typeErasedInitialElement(), Unchanged, clang::dataflow::Environment::widen(), and clang::dataflow::TypeErasedDataflowAnalysis::widenTypeErased().
Referenced by runDataflowAnalysis().
sigil()
static llvm::StringLiteral clang::dataflow::sigil (Formula::Kind K) static
Definition at line 37 of file Formula.cpp.
References clang::dataflow::Formula::And, clang::dataflow::Formula::AtomRef, clang::dataflow::Formula::Equal, clang::dataflow::Formula::Implies, clang::dataflow::Formula::Not, and clang::dataflow::Formula::Or.
Referenced by clang::dataflow::Formula::print().
transfer()
void clang::dataflow::transfer (const StmtToEnvMap & StmtToEnv, const Stmt & S, Environment & Env)
Evaluates S and updates Env accordingly.
Requirements:
S must not be ParenExpr or ExprWithCleanups.
Definition at line 763 of file Transfer.cpp.
References Env.
Referenced by builtinTransferStatement(), and clang::dataflow::DataflowAnalysis< Derived, LatticeT >::transferTypeErased().
transferBlock()
TypeErasedDataflowAnalysisState clang::dataflow::transferBlock (const ControlFlowContext & CFCtx, llvm::ArrayRef< std::optional< TypeErasedDataflowAnalysisState > > BlockStates, const CFGBlock & Block, const Environment & InitEnv, TypeErasedDataflowAnalysis & Analysis, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG = nullptr)
Transfers the state of a basic block by evaluating each of its elements in the context of Analysis and the states of its predecessors that are available in BlockStates.
PostVisitCFG (if provided) will be applied to each element in the block, after it is evaluated.
Requirements:
All predecessors of Block except those with loop back edges must have already been transferred. States in BlockStates that are set to std::nullopt represent basic blocks that are not evaluated yet.
Definition at line 491 of file TypeErasedDataflowAnalysis.cpp.
References Analysis, clang::Block, BlockStates, CFCtx, InitEnv, and transferCFGBlock().
transferCFGBlock()
static TypeErasedDataflowAnalysisState clang::dataflow::transferCFGBlock (const CFGBlock & Block, AnalysisContext & AC, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG = nullptr) static
Transfers State by evaluating each element in the Block based on the AC.Analysis specified.
Built-in transfer functions (if the option for ApplyBuiltinTransfer is set by the analysis) will be applied to the element before evaluation by the user-specified analysis. PostVisitCFG (if provided) will be applied to the element after evaluation by the user-specified analysis.
Definition at line 461 of file TypeErasedDataflowAnalysis.cpp.
References clang::Block, clang::dataflow::TypeErasedDataflowAnalysis::builtinOptions(), builtinTransfer(), computeBlockInputState(), clang::dataflow::Logger::enterBlock(), clang::dataflow::Logger::enterElement(), clang::dataflow::Logger::recordState(), and clang::dataflow::TypeErasedDataflowAnalysis::transferTypeErased().
Referenced by runTypeErasedDataflowAnalysis(), and transferBlock().
unpackValue()
static BoolValue & clang::dataflow::unpackValue (BoolValue & V, Environment & Env) static
Definition at line 65 of file Transfer.cpp.
References clang::dataflow::DataflowAnalysisContext::arena(), Env, clang::dataflow::Environment::getDataflowAnalysisContext(), clang::dataflow::Arena::makeBoolValue(), and V.
Referenced by maybeUnpackLValueExpr().
var()
static constexpr Variable clang::dataflow::var (Literal L) static constexpr
Returns the variable of L.
Definition at line 72 of file WatchedLiteralsSolver.cpp.
widenDistinctValues()
static Value & clang::dataflow::widenDistinctValues (QualType Type, Value & Prev, const Environment & PrevEnv, Value & Current, Environment & CurrentEnv, Environment::ValueModel & Model) static
Definition at line 156 of file DataflowEnvironment.cpp.
References clang::dataflow::Environment::makeTopBoolValue().
Referenced by clang::dataflow::Environment::widen().
Variable Documentation
MaxCompositeValueDepth
int clang::dataflow::MaxCompositeValueDepth = 3 static constexpr
Definition at line 37 of file DataflowEnvironment.cpp.
MaxCompositeValueSize
int clang::dataflow::MaxCompositeValueSize = 1000 static constexpr
Definition at line 38 of file DataflowEnvironment.cpp.
Referenced by clang::dataflow::Environment::createValue().
NullClause
ClauseID clang::dataflow::NullClause = 0 static constexpr
A null clause identifier is used as a placeholder in various data structures and algorithms.
Definition at line 79 of file WatchedLiteralsSolver.cpp.
NullLit
Literal clang::dataflow::NullLit = 0 static constexpr
A null literal is used as a placeholder in various data structures and algorithms.
Definition at line 60 of file WatchedLiteralsSolver.cpp.
Referenced by clang::dataflow::CNFFormula::addClause().
NullVar
Variable clang::dataflow::NullVar = 0 static constexpr
A null boolean variable is used as a placeholder in various data structures and algorithms.
Definition at line 50 of file WatchedLiteralsSolver.cpp.
Referenced by clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().