clang: lib/AST/NestedNameSpecifier.cpp File Reference
NestedNameSpecifier.cpp File Reference
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DependenceFlags.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <cstring>
Functions
static SourceLocation LoadSourceLocation (void *Data, unsigned Offset)
Load a (possibly unaligned) source location from a given address and offset.
static void * LoadPointer (void *Data, unsigned Offset)
Load a (possibly unaligned) pointer from a given address and offset.
static void Append (char *Start, char *End, char *&Buffer, unsigned &BufferSize, unsigned &BufferCapacity)
static void SaveSourceLocation (SourceLocation Loc, char *&Buffer, unsigned &BufferSize, unsigned &BufferCapacity)
Save a source location to the given buffer.
static void SavePointer (void *Ptr, char *&Buffer, unsigned &BufferSize, unsigned &BufferCapacity)
Save a pointer to the given buffer.
Function Documentation
Append()
static void Append (char * Start, char * End, char *& Buffer, unsigned & BufferSize, unsigned & BufferCapacity) static
Definition at line 464 of file NestedNameSpecifier.cpp.
References memcpy().
Referenced by clang::driver::RocmInstallationDetector::detectHIPRuntime(), clang::NestedNameSpecifierLocBuilder::NestedNameSpecifierLocBuilder(), clang::NestedNameSpecifierLocBuilder::operator=(), SavePointer(), and SaveSourceLocation().
LoadPointer()
static void * LoadPointer (void * Data, unsigned Offset) static
Load a (possibly unaligned) pointer from a given address and offset.
Definition at line 404 of file NestedNameSpecifier.cpp.
References Data, memcpy(), Offset, and clang::Result.
Referenced by clang::NestedNameSpecifierLoc::getLocalSourceRange(), and clang::NestedNameSpecifierLoc::getTypeLoc().
LoadSourceLocation()
static SourceLocation LoadSourceLocation (void * Data, unsigned Offset) static
Load a (possibly unaligned) source location from a given address and offset.
Definition at line 396 of file NestedNameSpecifier.cpp.
References Data, clang::SourceLocation::getFromRawEncoding(), memcpy(), and Offset.
Referenced by clang::NestedNameSpecifierLoc::getLocalSourceRange().
SavePointer()
static void SavePointer (void * Ptr, char *& Buffer, unsigned & BufferSize, unsigned & BufferCapacity) static
Save a pointer to the given buffer.
Definition at line 499 of file NestedNameSpecifier.cpp.
References Append().
Referenced by clang::NestedNameSpecifierLocBuilder::Extend(), and clang::NestedNameSpecifierLocBuilder::MakeTrivial().
SaveSourceLocation()
static void SaveSourceLocation (SourceLocation Loc, char *& Buffer, unsigned & BufferSize, unsigned & BufferCapacity) static
Save a source location to the given buffer.
Definition at line 490 of file NestedNameSpecifier.cpp.
References Append().
Referenced by clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::MakeGlobal(), clang::NestedNameSpecifierLocBuilder::MakeSuper(), and clang::NestedNameSpecifierLocBuilder::MakeTrivial().