clang: lib/StaticAnalyzer/Checkers/NSErrorChecker.cpp File Reference
NSErrorChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclObjC.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Typedefs
typedef llvm::ImmutableMap< SymbolRef, unsigned > ErrorOutFlag
Functions
static bool IsNSError (QualType T, IdentifierInfo *II)
static bool IsCFError (QualType T, IdentifierInfo *II)
static bool hasReservedReturnType (const FunctionDecl *D)
template<typename T >
static bool hasFlag (SVal val, ProgramStateRef state)
template<typename T >
static void setFlag (ProgramStateRef state, SVal val, CheckerContext &C)
static QualType parameterTypeFromSVal (SVal val, CheckerContext &C)
Typedef Documentation
ErrorOutFlag
typedef llvm::ImmutableMap<SymbolRef, unsigned> ErrorOutFlag
Definition at line 180 of file NSErrorChecker.cpp.
Function Documentation
hasFlag()
template<typename T > static bool hasFlag (SVal val, ProgramStateRef state) static
Definition at line 185 of file NSErrorChecker.cpp.
References clang::ento::SVal::getAsSymbol().
hasReservedReturnType()
static bool hasReservedReturnType (const FunctionDecl * D) static
Definition at line 99 of file NSErrorChecker.cpp.
References clang::FunctionDecl::getOverloadedOperator().
IsCFError()
static bool IsCFError (QualType T, IdentifierInfo * II) static
Definition at line 313 of file NSErrorChecker.cpp.
References clang::Type::getAs(), clang::TypedefType::getDecl(), clang::NamedDecl::getIdentifier(), and clang::PointerType::getPointeeType().
IsNSError()
static bool IsNSError (QualType T, IdentifierInfo * II) static
Definition at line 292 of file NSErrorChecker.cpp.
References clang::Type::getAs(), clang::ObjCObjectPointerType::getInterfaceDecl(), and clang::PointerType::getPointeeType().
parameterTypeFromSVal()
static QualType parameterTypeFromSVal (SVal val, CheckerContext & C) static
Definition at line 199 of file NSErrorChecker.cpp.
References clang::C, clang::ento::MemRegion::getAs(), clang::ento::SVal::getAs(), clang::LocationContext::getStackFrame(), and X.
setFlag()
template<typename T > static void setFlag (ProgramStateRef state, SVal val, CheckerContext & C) static
Definition at line 193 of file NSErrorChecker.cpp.
References clang::C, and clang::ento::SVal::getAsSymbol().