clang: lib/StaticAnalyzer/Checkers/ObjCAutoreleaseWriteChecker.cpp File Reference
ObjCAutoreleaseWriteChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/BugReporter/CommonBugCategories.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "llvm/ADT/Twine.h"
Functions
static std::vector< llvm::StringRef > toRefs (const std::vector< std::string > &V)
static decltype(auto) callsNames (const std::vector< std::string > &FunctionNames)
static void emitDiagnostics (BoundNodes &Match, const Decl *D, BugReporter &BR, AnalysisManager &AM, const ObjCAutoreleaseWriteChecker *Checker)
Function Documentation
callsNames()
static decltype(auto) callsNames (const std::vector< std::string > & FunctionNames) static
Definition at line 107 of file ObjCAutoreleaseWriteChecker.cpp.
References clang::ast_matchers::functionDecl, clang::ast_matchers::hasAnyName, and toRefs().
emitDiagnostics()
static void emitDiagnostics (BoundNodes & Match, const Decl * D, BugReporter & BR, AnalysisManager & AM, const ObjCAutoreleaseWriteChecker * Checker) static
Definition at line 111 of file ObjCAutoreleaseWriteChecker.cpp.
References clang::ento::PathDiagnosticLocation::createBegin(), clang::ento::BugReporter::EmitBasicReport(), clang::ento::AnalysisManager::getAnalysisDeclContext(), clang::AnalysisDeclContext::getDecl(), clang::ast_matchers::BoundNodes::getNodeAs(), clang::ento::BugReporter::getSourceManager(), clang::ento::categories::MemoryRefCount, and clang::Qualifiers::OCL_Autoreleasing.
toRefs()
static std::vector< llvm::StringRef > toRefs (const std::vector< std::string > & V) inline static
Definition at line 102 of file ObjCAutoreleaseWriteChecker.cpp.
References V.
Referenced by callsNames().