clang: lib/StaticAnalyzer/Checkers/ObjCUnusedIVarsChecker.cpp File Reference
ObjCUnusedIVarsChecker.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprObjC.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceManager.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "llvm/ADT/STLExtras.h"
Typedefs
typedef llvm::DenseMap< const ObjCIvarDecl *, IVarState > IvarUsageMap
Enumerations
enum IVarState { Unused , Used }
Functions
static void Scan (IvarUsageMap &M, const Stmt *S)
static void Scan (IvarUsageMap &M, const ObjCPropertyImplDecl *D)
static void Scan (IvarUsageMap &M, const ObjCContainerDecl *D)
static void Scan (IvarUsageMap &M, const DeclContext *C, const FileID FID, const SourceManager &SM)
static void checkObjCUnusedIvar (const ObjCImplementationDecl *D, BugReporter &BR, const CheckerBase *Checker)
Typedef Documentation
IvarUsageMap
typedef llvm::DenseMap<const ObjCIvarDecl*,IVarState> IvarUsageMap
Definition at line 31 of file ObjCUnusedIVarsChecker.cpp.
Enumeration Type Documentation
IVarState
enum IVarState
Enumerator
Unused
Used
Definition at line 30 of file ObjCUnusedIVarsChecker.cpp.
Function Documentation
checkObjCUnusedIvar()
static void checkObjCUnusedIvar (const ObjCImplementationDecl * D, BugReporter & BR, const CheckerBase * Checker) static
Definition at line 105 of file ObjCUnusedIVarsChecker.cpp.
References clang::ento::PathDiagnosticLocation::create(), clang::ento::BugReporter::EmitBasicReport(), clang::ObjCImplDecl::getClassInterface(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::ento::BugReporter::getSourceManager(), clang::ObjCIvarDecl::Private, Scan(), SM, and Unused.
Scan() [1/4]
static void Scan (IvarUsageMap & M, const DeclContext * C, const FileID FID, const SourceManager & SM) static
Definition at line 95 of file ObjCUnusedIVarsChecker.cpp.
References clang::C, Scan(), and SM.
Scan() [2/4]
static void Scan (IvarUsageMap & M, const ObjCContainerDecl * D) static
Definition at line 76 of file ObjCUnusedIVarsChecker.cpp.
References clang::ObjCContainerDecl::instance_methods(), and Scan().
Scan() [3/4]
static void Scan (IvarUsageMap & M, const ObjCPropertyImplDecl * D) static
Definition at line 62 of file ObjCUnusedIVarsChecker.cpp.
References clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), and Used.
Scan() [4/4]
static void Scan (IvarUsageMap & M, const Stmt * S) static
Definition at line 33 of file ObjCUnusedIVarsChecker.cpp.
References Scan(), and Used.
Referenced by checkObjCUnusedIvar(), clang::getAsFileEvents(), Scan(), Scan(), and Scan().