clang: lib/AST/ODRDiagsEmitter.cpp File Reference
ODRDiagsEmitter.cpp File Reference
#include "clang/AST/ODRDiagsEmitter.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ODRHash.h"
#include "clang/Basic/DiagnosticAST.h"
#include "clang/Basic/Module.h"
Functions
static unsigned computeODRHash (QualType Ty)
static unsigned computeODRHash (const Stmt *S)
static unsigned computeODRHash (const Decl *D)
static unsigned computeODRHash (const TemplateArgument &TA)
template<typename MethodT >
static bool diagnoseSubMismatchMethodParameters (DiagnosticsEngine &Diags, const NamedDecl *FirstContainer, StringRef FirstModule, StringRef SecondModule, const MethodT *FirstMethod, const MethodT *SecondMethod)
Function Documentation
computeODRHash() [1/4]
static unsigned computeODRHash (const Decl * D) static
Definition at line 30 of file ODRDiagsEmitter.cpp.
References clang::ODRHash::AddSubDecl(), and clang::ODRHash::CalculateHash().
computeODRHash() [2/4]
static unsigned computeODRHash (const Stmt * S) static
Definition at line 24 of file ODRDiagsEmitter.cpp.
References clang::ODRHash::AddStmt(), and clang::ODRHash::CalculateHash().
computeODRHash() [3/4]
static unsigned computeODRHash (const TemplateArgument & TA) static
Definition at line 37 of file ODRDiagsEmitter.cpp.
References clang::ODRHash::AddTemplateArgument(), and clang::ODRHash::CalculateHash().
computeODRHash() [4/4]
static unsigned computeODRHash (QualType Ty) static
Definition at line 18 of file ODRDiagsEmitter.cpp.
References clang::ODRHash::AddQualType(), and clang::ODRHash::CalculateHash().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::ODRDiagsEmitter::diagnoseMismatch(), and diagnoseSubMismatchMethodParameters().
diagnoseSubMismatchMethodParameters()
template<typename MethodT > static bool diagnoseSubMismatchMethodParameters (DiagnosticsEngine & Diags, const NamedDecl * FirstContainer, StringRef FirstModule, StringRef SecondModule, const MethodT * FirstMethod, const MethodT * SecondMethod) static
Definition at line 53 of file ODRDiagsEmitter.cpp.
References computeODRHash(), clang::Type::getAs(), clang::NamedDecl::getDeclName(), clang::ValueDecl::getType(), and clang::DiagnosticsEngine::Report().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch().