clang: lib/Driver/ToolChains/OHOS.cpp File Reference
OHOS.cpp File Reference
#include "OHOS.h"
#include "Arch/ARM.h"
#include "CommonArgs.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/Option/ArgList.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/ScopedPrinter.h"
Functions
static bool findOHOSMuslMultilibs (const Multilib::flags_list &Flags, DetectedMultilibs &Result)
static bool findOHOSMultilibs (const Driver &D, const ToolChain &TC, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static std::string makePath (const std::initializer_list< std::string > &IL)
Function Documentation
findOHOSMultilibs()
static bool findOHOSMultilibs (const Driver & D, const ToolChain & TC, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 60 of file OHOS.cpp.
References clang::driver::tools::addMultilibFlag(), findOHOSMuslMultilibs(), clang::driver::tools::arm::getARMFloatABI(), and clang::Result.
Referenced by clang::driver::toolchains::OHOS::OHOS().
findOHOSMuslMultilibs()
static bool findOHOSMuslMultilibs (const Multilib::flags_list & Flags, DetectedMultilibs & Result) static
Definition at line 35 of file OHOS.cpp.
References clang::driver::MultilibSet::push_back(), clang::Result, and clang::driver::MultilibSet::select().
Referenced by findOHOSMultilibs().
makePath()
static std::string makePath (const std::initializer_list< std::string > & IL) static
Definition at line 123 of file OHOS.cpp.
References P.
Referenced by clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::computeSysRoot(), clang::driver::toolchains::OHOS::getArchSpecificLibPaths(), and clang::driver::toolchains::OHOS::OHOS().