clang: lib/Parse/ParsePragma.cpp File Reference
ParsePragma.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/Basic/PragmaKinds.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/Token.h"
#include "clang/Parse/LoopHint.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Scope.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringSwitch.h"
#include <optional>
#include "clang/Parse/AttrSubMatchRulesParserStringSwitches.inc"
#include "clang/Basic/AttrSubMatchRulesList.inc"
Macros
#define ATTR_MATCH_RULE(Value, Spelling, IsAbstract)
Functions
static std::string PragmaLoopHintString (Token PragmaName, Token Option)
static StringRef getIdentifier (const Token &Tok)
static bool isAbstractAttrMatcherRule (attr::SubjectMatchRule Rule)
static void diagnoseExpectedAttributeSubjectSubRule (Parser &PRef, attr::SubjectMatchRule PrimaryRule, StringRef PrimaryRuleName, SourceLocation SubRuleLoc)
static void diagnoseUnknownAttributeSubjectSubRule (Parser &PRef, attr::SubjectMatchRule PrimaryRule, StringRef PrimaryRuleName, StringRef SubRuleName, SourceLocation SubRuleLoc)
static void ParseAlignPragma (Preprocessor &PP, Token &FirstTok, bool IsOptions)
static bool ParseLoopHintValue (Preprocessor &PP, Token &Tok, Token PragmaName, Token Option, bool ValueInParens, PragmaLoopHintInfo &Info)
Parses loop or unroll pragma hint value and fills in Info.
Macro Definition Documentation
ATTR_MATCH_RULE
#define ATTR_MATCH_RULE (Value, Spelling, IsAbstract)
Value:
  case Value:                                                                  \
    return IsAbstract;
Function Documentation
diagnoseExpectedAttributeSubjectSubRule()
static void diagnoseExpectedAttributeSubjectSubRule (Parser & PRef, attr::SubjectMatchRule PrimaryRule, StringRef PrimaryRuleName, SourceLocation SubRuleLoc) static
Definition at line 1559 of file ParsePragma.cpp.
References clang::Parser::Diag().
diagnoseUnknownAttributeSubjectSubRule()
static void diagnoseUnknownAttributeSubjectSubRule (Parser & PRef, attr::SubjectMatchRule PrimaryRule, StringRef PrimaryRuleName, StringRef SubRuleName, SourceLocation SubRuleLoc) static
Definition at line 1572 of file ParsePragma.cpp.
References clang::Parser::Diag().
getIdentifier()
static StringRef getIdentifier (const Token & Tok) static
Definition at line 1538 of file ParsePragma.cpp.
References clang::Token::getIdentifierInfo(), clang::tok::getKeywordSpelling(), clang::Token::getKind(), clang::IdentifierInfo::getName(), clang::Token::is(), and Tok.
Referenced by clang::Sema::DiagnoseUnexpandedParameterPacks().
isAbstractAttrMatcherRule()
static bool isAbstractAttrMatcherRule (attr::SubjectMatchRule Rule) static
Definition at line 1547 of file ParsePragma.cpp.
References clang::ast_matchers::attr.
ParseAlignPragma()
static void ParseAlignPragma (Preprocessor & PP, Token & FirstTok, bool IsOptions) static
Definition at line 2248 of file ParsePragma.cpp.
References clang::Preprocessor::Diag(), clang::Token::getIdentifierInfo(), clang::Preprocessor::getLangOpts(), clang::Token::getLocation(), clang::Preprocessor::getPreprocessorAllocator(), clang::Token::isNot(), clang::IdentifierInfo::isStr(), clang::Preprocessor::Lex(), clang::Sema::POAK_Mac68k, clang::Sema::POAK_Native, clang::Sema::POAK_Natural, clang::Sema::POAK_Packed, clang::Sema::POAK_Power, clang::Sema::POAK_Reset, and Tok.
ParseLoopHintValue()
static bool ParseLoopHintValue (Preprocessor & PP, Token & Tok, Token PragmaName, Token Option, bool ValueInParens, PragmaLoopHintInfo & Info) static
Parses loop or unroll pragma hint value and fills in Info.
Definition at line 3414 of file ParsePragma.cpp.
References clang::Preprocessor::Diag(), clang::Token::getLocation(), clang::Preprocessor::getPreprocessorAllocator(), clang::Token::is(), clang::Token::isNot(), clang::Preprocessor::Lex(), clang::PragmaLoopHintInfo::Option, clang::PragmaLoopHintInfo::PragmaName, clang::Token::setKind(), clang::Token::setLocation(), clang::Token::startToken(), Tok, and clang::PragmaLoopHintInfo::Toks.
PragmaLoopHintString()
static std::string PragmaLoopHintString (Token PragmaName, Token Option) static
Definition at line 1316 of file ParsePragma.cpp.
References clang::Default, clang::Token::getIdentifierInfo(), and clang::IdentifierInfo::getName().