clang: lib/Lex/PPLexerChange.cpp File Reference
PPLexerChange.cpp File Reference
#include "clang/Basic/FileManager.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/Support/Path.h"
#include <optional>
Functions
static void computeRelativePath (FileManager &FM, const DirectoryEntry *Dir, FileEntryRef File, SmallString< 128 > &Result)
Compute the relative path that names the given file relative to the given directory.
static void collectAllSubModulesWithUmbrellaHeader (const Module &Mod, SmallVectorImpl< const Module * > &SubMods)
Function Documentation
collectAllSubModulesWithUmbrellaHeader()
static void collectAllSubModulesWithUmbrellaHeader (const Module & Mod, SmallVectorImpl< const Module * > & SubMods) static
Definition at line 282 of file PPLexerChange.cpp.
References collectAllSubModulesWithUmbrellaHeader(), clang::Module::getUmbrellaHeaderAsWritten(), and clang::Module::submodules().
Referenced by collectAllSubModulesWithUmbrellaHeader(), and clang::Preprocessor::HandleEndOfFile().
computeRelativePath()
static void computeRelativePath (FileManager & FM, const DirectoryEntry * Dir, FileEntryRef File, SmallString< 128 > & Result) static
Compute the relative path that names the given file relative to the given directory.
Definition at line 225 of file PPLexerChange.cpp.
References clang::File, clang::FileManager::getDirectory(), and clang::Result.