clang: lib/AST/PrintfFormatString.cpp File Reference
PrintfFormatString.cpp File Reference
#include "FormatStringParsing.h"
#include "clang/AST/FormatString.h"
#include "clang/AST/OSLog.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/Support/Regex.h"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/Basic/RISCVVTypes.def"
#include "clang/Basic/WebAssemblyReferenceTypes.def"
#include "clang/AST/BuiltinTypes.def"
Macros
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define RVV_TYPE(Name, Id, SingletonId)
#define WASM_TYPE(Name, Id, SingletonId)
#define SIGNED_TYPE(Id, SingletonId)
#define UNSIGNED_TYPE(Id, SingletonId)
#define FLOATING_TYPE(Id, SingletonId)
#define BUILTIN_TYPE(Id, SingletonId)
Typedefs
typedef clang::analyze_format_string::SpecifierResult< PrintfSpecifier > PrintfSpecifierResult
Functions
static bool ParsePrecision (FormatStringHandler &H, PrintfSpecifier &FS, const char *Start, const char *&Beg, const char *E, unsigned *argIndex)
static bool ParseObjCFlags (FormatStringHandler &H, PrintfSpecifier &FS, const char *FlagBeg, const char *E, bool Warn)
static PrintfSpecifierResult ParsePrintfSpecifier (FormatStringHandler &H, const char *&Beg, const char *E, unsigned &argIndex, const LangOptions &LO, const TargetInfo &Target, bool Warn, bool isFreeBSDKPrintf)
Macro Definition Documentation
BUILTIN_TYPE
#define BUILTIN_TYPE (Id, SingletonId)
Value:
  case BuiltinType::Id:
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id:
FLOATING_TYPE
#define FLOATING_TYPE (Id, SingletonId)
IMAGE_TYPE
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id:
PPC_VECTOR_TYPE
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
  case BuiltinType::Id:
RVV_TYPE
#define RVV_TYPE (Name, Id, SingletonId)
Value:
case BuiltinType::Id:
SIGNED_TYPE
#define SIGNED_TYPE (Id, SingletonId)
SVE_TYPE
#define SVE_TYPE (Name, Id, SingletonId)
Value:
  case BuiltinType::Id:
UNSIGNED_TYPE
#define UNSIGNED_TYPE (Id, SingletonId)
WASM_TYPE
#define WASM_TYPE (Name, Id, SingletonId)
Value:
case BuiltinType::Id:
Typedef Documentation
PrintfSpecifierResult
typedef clang::analyze_format_string::SpecifierResult<PrintfSpecifier> PrintfSpecifierResult
Definition at line 30 of file PrintfFormatString.cpp.
Function Documentation
ParseObjCFlags()
static bool ParseObjCFlags (FormatStringHandler & H, PrintfSpecifier & FS, const char * FlagBeg, const char * E, bool Warn) static
Definition at line 53 of file PrintfFormatString.cpp.
References clang::analyze_format_string::FormatStringHandler::HandleEmptyObjCModifierFlag(), and clang::analyze_format_string::FormatStringHandler::HandleInvalidObjCModifierFlag().
Referenced by ParsePrintfSpecifier().
ParsePrecision()
static bool ParsePrecision (FormatStringHandler & H, PrintfSpecifier & FS, const char * Start, const char *& Beg, const char * E, unsigned * argIndex) static
Definition at line 38 of file PrintfFormatString.cpp.
References clang::analyze_format_string::OptionalAmount::isInvalid(), and clang::analyze_format_string::PrecisionPos.
Referenced by ParsePrintfSpecifier().
ParsePrintfSpecifier()
static PrintfSpecifierResult ParsePrintfSpecifier (FormatStringHandler & H, const char *& Beg, const char * E, unsigned & argIndex, const LangOptions & LO, const TargetInfo & Target, bool Warn, bool isFreeBSDKPrintf) static
Definition at line 71 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::BArg, clang::analyze_format_string::ConversionSpecifier::bArg, c, clang::analyze_format_string::ConversionSpecifier::CArg, clang::analyze_format_string::ConversionSpecifier::cArg, clang::analyze_format_string::ConversionSpecifier::consumesDataArgument(), clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDbArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDDArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::FormatStringHandler::HandleIncompleteSpecifier(), clang::analyze_format_string::FormatStringHandler::handleInvalidMaskType(), clang::analyze_format_string::FormatStringHandler::HandleInvalidPrintfConversionSpecifier(), clang::analyze_format_string::FormatStringHandler::HandleNullChar(), clang::analyze_format_string::FormatStringHandler::HandleObjCFlagsWithNonObjCConversion(), clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::InvalidSpecifier, clang::analyze_os_log::OSLogBufferItem::IsPrivate, clang::analyze_os_log::OSLogBufferItem::IsPublic, clang::analyze_os_log::OSLogBufferItem::IsSensitive, clang::analyze_format_string::ConversionSpecifier::nArg, clang::analyze_format_string::ConversionSpecifier::OArg, clang::analyze_format_string::ConversionSpecifier::oArg, clang::analyze_format_string::ConversionSpecifier::ObjCObjArg, clang::analyze_format_string::ConversionSpecifier::PArg, clang::analyze_format_string::ConversionSpecifier::pArg, ParseObjCFlags(), ParsePrecision(), clang::analyze_format_string::ConversionSpecifier::PercentArg, clang::analyze_format_string::ConversionSpecifier::PrintErrno, clang::analyze_format_string::ConversionSpecifier::SArg, clang::analyze_format_string::ConversionSpecifier::sArg, clang::analyze_format_string::ConversionSpecifier::setEndScanList(), clang::analyze_format_string::ConversionSpecifier::UArg, clang::analyze_format_string::ConversionSpecifier::uArg, clang::analyze_format_string::ConversionSpecifier::XArg, clang::analyze_format_string::ConversionSpecifier::xArg, and clang::analyze_format_string::ConversionSpecifier::ZArg.
Referenced by clang::analyze_format_string::parseFormatStringHasFormattingSpecifiers(), clang::analyze_format_string::ParseFormatStringHasSArg(), and clang::analyze_format_string::ParsePrintfString().