clang: lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountDiagnostics.cpp File Reference
RetainCountDiagnostics.cpp File Reference
#include "RetainCountDiagnostics.h"
#include "RetainCountChecker.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
Classes
class clang::ento::retaincountchecker::RefCountReportVisitor
class clang::ento::retaincountchecker::RefLeakReportVisitor
Namespaces
namespace clang
namespace clang::ento
namespace clang::ento::retaincountchecker
Typedefs
using Bindings = llvm::SmallVector<std::pair<const MemRegion *, SVal>, 4>
Functions
static bool isNumericLiteralExpression (const Expr *E)
static std::string getPrettyTypeName (QualType QT)
If type represents a pointer to CXXRecordDecl, and is not a typedef, return the decl name.
static bool shouldGenerateNote (llvm::raw_string_ostream &os, const RefVal *PrevT, const RefVal &CurrV, bool DeallocSent)
Write information about the type state change to os, return whether the note should be generated.
static std::optional< unsigned > findArgIdxOfSymbol (ProgramStateRef CurrSt, const LocationContext *LCtx, SymbolRef &Sym, std::optional< CallEventRef<> > CE)
Finds argument index of the out paramter in the call S corresponding to the symbol Sym.
static std::optional< std::string > findMetaClassAlloc (const Expr *Callee)
static std::string findAllocatedObjectName (const Stmt *S, QualType QT)
static void generateDiagnosticsForCallLike (ProgramStateRef CurrSt, const LocationContext *LCtx, const RefVal &CurrV, SymbolRef &Sym, const Stmt *S, llvm::raw_string_ostream &os)
static const ExplodedNode * getCalleeNode (const ExplodedNode *Pred)
Find the first node with the parent stack frame.
static std::shared_ptr< PathDiagnosticEventPiece > annotateConsumedSummaryMismatch (const ExplodedNode *N, CallExitBegin &CallExitLoc, const SourceManager &SM, CallEventManager &CEMgr)
Insert a diagnostic piece at function exit if a function parameter is annotated as "os_consumed", but it does not actually consume the reference.
static std::shared_ptr< PathDiagnosticEventPiece > annotateStartParameter (const ExplodedNode *N, SymbolRef Sym, const SourceManager &SM)
Annotate the parameter at the analysis entry point.
static std::optional< std::string > describeRegion (const MemRegion *MR)
Bindings getAllVarBindingsForSymbol (ProgramStateManager &Manager, const ExplodedNode *Node, SymbolRef Sym)
static AllocationInfo GetAllocationSite (ProgramStateManager &StateMgr, const ExplodedNode *N, SymbolRef Sym)
Typedef Documentation
Bindings
using Bindings = llvm::SmallVector<std::pair<const MemRegion *, SVal>, 4>
Examples
/root/llvm-project/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 613 of file RetainCountDiagnostics.cpp.
Function Documentation
annotateConsumedSummaryMismatch()
static std::shared_ptr< PathDiagnosticEventPiece > annotateConsumedSummaryMismatch (const ExplodedNode * N, CallExitBegin & CallExitLoc, const SourceManager & SM, CallEventManager & CEMgr) static
Insert a diagnostic piece at function exit if a function parameter is annotated as "os_consumed", but it does not actually consume the reference.
Definition at line 373 of file RetainCountDiagnostics.cpp.
References clang::ento::PathDiagnosticLocation::create(), clang::Decl::getASTContext(), getCalleeNode(), clang::ento::CallEventManager::getCaller(), clang::ento::retaincountchecker::RefVal::getCount(), clang::NamedDecl::getNameForDiagnostic(), clang::ASTContext::getPrintingPolicy(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::ExplodedNode::getState(), clang::Decl::hasAttr(), N, and SM.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
annotateStartParameter()
static std::shared_ptr< PathDiagnosticEventPiece > annotateStartParameter (const ExplodedNode * N, SymbolRef Sym, const SourceManager & SM) static
Annotate the parameter at the analysis entry point.
Definition at line 423 of file RetainCountDiagnostics.cpp.
References clang::cast(), clang::ento::retaincountchecker::RefVal::getCount(), clang::CFG::getEntry(), clang::CFGBlock::getParent(), clang::ento::retaincountchecker::getRefBinding(), N, s, and SM.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
describeRegion()
static std::optional< std::string > describeRegion (const MemRegion * MR) static
Definition at line 605 of file RetainCountDiagnostics.cpp.
Referenced by clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath().
findAllocatedObjectName()
static std::string findAllocatedObjectName (const Stmt * S, QualType QT) static
Definition at line 203 of file RetainCountDiagnostics.cpp.
References findMetaClassAlloc(), and getPrettyTypeName().
Referenced by generateDiagnosticsForCallLike().
findArgIdxOfSymbol()
static std::optional< unsigned > findArgIdxOfSymbol (ProgramStateRef CurrSt, const LocationContext * LCtx, SymbolRef & Sym, std::optional< CallEventRef<> > CE) static
Finds argument index of the out paramter in the call S corresponding to the symbol Sym.
If none found, returns std::nullopt.
Definition at line 171 of file RetainCountDiagnostics.cpp.
Referenced by generateDiagnosticsForCallLike().
findMetaClassAlloc()
static std::optional< std::string > findMetaClassAlloc (const Expr * Callee) static
Definition at line 185 of file RetainCountDiagnostics.cpp.
References clang::Decl::getDeclContext(), and clang::NamedDecl::getNameAsString().
Referenced by findAllocatedObjectName().
generateDiagnosticsForCallLike()
static void generateDiagnosticsForCallLike (ProgramStateRef CurrSt, const LocationContext * LCtx, const RefVal & CurrV, SymbolRef & Sym, const Stmt * S, llvm::raw_string_ostream & os) static
Definition at line 210 of file RetainCountDiagnostics.cpp.
References clang::cast(), clang::ento::CF, findAllocatedObjectName(), findArgIdxOfSymbol(), clang::ento::Generalized, clang::Decl::getASTContext(), clang::ento::CallEventManager::getCall(), clang::NamedDecl::getNameForDiagnostic(), clang::ento::CallEventManager::getObjCMethodCall(), clang::ento::retaincountchecker::RefVal::getObjKind(), clang::ObjCObjectPointerType::getPointeeType(), clang::ASTContext::getPrintingPolicy(), clang::NamedDecl::getQualifiedNameAsString(), clang::ento::SymExpr::getType(), clang::ento::retaincountchecker::RefVal::isNotOwned(), clang::QualType::isNull(), clang::ento::retaincountchecker::RefVal::isOwned(), clang::Type::isVoidType(), clang::ento::ObjC, clang::ento::OCM_Message, clang::ento::OCM_PropertyAccess, clang::ento::OCM_Subscript, clang::ento::OS, and X.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
GetAllocationSite()
static AllocationInfo GetAllocationSite (ProgramStateManager & StateMgr, const ExplodedNode * N, SymbolRef Sym) static
Definition at line 667 of file RetainCountDiagnostics.cpp.
References clang::ProgramPoint::getAs(), clang::ento::SVal::getAsSymbol(), clang::ento::ExplodedNode::getFirstPred(), clang::ento::ExplodedNode::getLocation(), clang::ento::ExplodedNode::getLocationContext(), clang::ento::MemRegion::getMemorySpace(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::StoreManager::FindUniqueBinding::getRegion(), clang::LocationContext::getStackFrame(), clang::LocationContext::isParentOf(), clang::ento::ProgramStateManager::iterBindings(), N, clang::OMF_alloc, and clang::OMF_init.
getAllVarBindingsForSymbol()
Bindings getAllVarBindingsForSymbol (ProgramStateManager & Manager, const ExplodedNode * Node, SymbolRef Sym)
Definition at line 638 of file RetainCountDiagnostics.cpp.
References clang::ento::ProgramStateManager::iterBindings(), and Node.
getCalleeNode()
static const ExplodedNode * getCalleeNode (const ExplodedNode * Pred) static
Find the first node with the parent stack frame.
Definition at line 353 of file RetainCountDiagnostics.cpp.
References clang::LocationContext::getParent(), clang::ento::ExplodedNode::getStackFrame(), clang::LocationContext::getStackFrame(), clang::StackFrameContext::inTopFrame(), and N.
Referenced by annotateConsumedSummaryMismatch().
getPrettyTypeName()
static std::string getPrettyTypeName (QualType QT) static
If type represents a pointer to CXXRecordDecl, and is not a typedef, return the decl name.
Otherwise, return the serialization of type.
Definition at line 84 of file RetainCountDiagnostics.cpp.
References clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::QualType::getAsString(), clang::Type::getPointeeType(), and clang::QualType::isNull().
Referenced by findAllocatedObjectName(), and clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath().
isNumericLiteralExpression()
static bool isNumericLiteralExpression (const Expr * E) static
Definition at line 75 of file RetainCountDiagnostics.cpp.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
shouldGenerateNote()
static bool shouldGenerateNote (llvm::raw_string_ostream & os, const RefVal * PrevT, const RefVal & CurrV, bool DeallocSent) static
Write information about the type state change to os, return whether the note should be generated.
Definition at line 94 of file RetainCountDiagnostics.cpp.
References clang::ento::retaincountchecker::RefVal::getAutoreleaseCount(), clang::ento::retaincountchecker::RefVal::getCombinedCounts(), clang::ento::retaincountchecker::RefVal::getCount(), clang::ento::retaincountchecker::RefVal::getIvarAccessHistory(), clang::ento::retaincountchecker::RefVal::getKind(), clang::ento::retaincountchecker::RefVal::hasSameState(), clang::ento::retaincountchecker::RefVal::NotOwned, clang::ento::retaincountchecker::RefVal::Owned, clang::ento::retaincountchecker::RefVal::Released, clang::ento::retaincountchecker::RefVal::ReleasedAfterDirectAccess, clang::ento::retaincountchecker::RefVal::ReturnedNotOwned, and clang::ento::retaincountchecker::RefVal::ReturnedOwned.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().