clang: lib/StaticAnalyzer/Checkers/ReturnValueChecker.cpp File Reference
ReturnValueChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
Functions
static std::string getName (const CallEvent &Call)
static std::optional< bool > isInvariantBreak (bool ExpectedValue, SVal ReturnV, CheckerContext &C)
Function Documentation
getName()
static std::string getName (const CallEvent & Call) static
Definition at line 61 of file ReturnValueChecker.cpp.
References clang::DeclContext::getParent().
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::CheckAddressOfOperand(), clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString(), clang::interp::Function::dump(), clang::serialization::DeclarationNameKey::getHash(), clang::DiagnosticIDs::getWarningOptionForGroup(), handleMIGServerRoutineAttr(), isBetterMultiversionCandidate(), clang::IdentifierInfo::isEditorPlaceholder(), clang::IdentifierInfo::operator<(), REGISTER_MAP_WITH_PROGRAMSTATE(), and clang::TargetInfo::resolveSymbolicName().
isInvariantBreak()
static std::optional< bool > isInvariantBreak (bool ExpectedValue, SVal ReturnV, CheckerContext & C) static
Definition at line 73 of file ReturnValueChecker.cpp.
References clang::C, and clang::ento::SVal::getAs().