clang: lib/Rewrite/Rewriter.cpp File Reference
Rewriter.cpp File Reference
#include "clang/Rewrite/Core/Rewriter.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticIDs.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/Lexer.h"
#include "clang/Rewrite/Core/RewriteBuffer.h"
#include "clang/Rewrite/Core/RewriteRope.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <iterator>
#include <map>
#include <utility>
Functions
static bool isWhitespaceExceptNL (unsigned char c)
Return true if this character is non-new-line whitespace: ' ', '\t', '\f', '\v', '\r'.
Function Documentation
isWhitespaceExceptNL()
static bool isWhitespaceExceptNL (unsigned char c) inline static
Return true if this character is non-new-line whitespace: ' ', '\t', '\f', '\v', '\r'.
Definition at line 44 of file Rewriter.cpp.
References c.
Referenced by clang::Rewriter::IncreaseIndentation(), clang::Rewriter::InsertText(), and clang::RewriteBuffer::RemoveText().