clang: lib/Driver/SanitizerArgs.cpp File Reference
SanitizerArgs.cpp File Reference
#include "clang/Driver/SanitizerArgs.h"
#include "ToolChains/CommonArgs.h"
#include "clang/Basic/Sanitizers.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/ToolChain.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SpecialCaseList.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/TargetParser/RISCVTargetParser.h"
#include "llvm/TargetParser/TargetParser.h"
#include "llvm/Transforms/Instrumentation/AddressSanitizerOptions.h"
#include <memory>
#include "clang/Basic/Sanitizers.def"
Macros
#define SANITIZER(NAME, ID)
#define SANITIZER_GROUP(NAME, ID, ALIAS)
#define SANITIZER(NAME, ID)
Enumerations
enum CoverageFeature {
CoverageFunc = 1 << 0 , CoverageBB = 1 << 1 , CoverageEdge = 1 << 2 , CoverageIndirCall = 1 << 3 ,
CoverageTraceBB = 1 << 4 , CoverageTraceCmp = 1 << 5 , CoverageTraceDiv = 1 << 6 , CoverageTraceGep = 1 << 7 ,
Coverage8bitCounters = 1 << 8 , CoverageTracePC = 1 << 9 , CoverageTracePCGuard = 1 << 10 , CoverageNoPrune = 1 << 11 ,
CoverageInline8bitCounters = 1 << 12 , CoveragePCTable = 1 << 13 , CoverageStackDepth = 1 << 14 , CoverageInlineBoolFlag = 1 << 15 ,
CoverageTraceLoads = 1 << 16 , CoverageTraceStores = 1 << 17 , CoverageControlFlow = 1 << 18
}
enum BinaryMetadataFeature { BinaryMetadataCovered = 1 << 0 , BinaryMetadataAtomics = 1 << 1 , BinaryMetadataUAR = 1 << 2 }
Functions
static SanitizerMask parseArgValues (const Driver &D, const llvm::opt::Arg *A, bool DiagnoseErrors)
Parse a -fsanitize= or -fno-sanitize= argument's values, diagnosing any invalid components.
static int parseCoverageFeatures (const Driver &D, const llvm::opt::Arg *A, bool DiagnoseErrors)
Parse -f(no-)?sanitize-coverage= flag values, diagnosing any invalid components.
static int parseBinaryMetadataFeatures (const Driver &D, const llvm::opt::Arg *A, bool DiagnoseErrors)
Parse -f(no-)?sanitize-metadata= flag values, diagnosing any invalid components.
static std::string lastArgumentForMask (const Driver &D, const llvm::opt::ArgList &Args, SanitizerMask Mask)
Produce an argument string from ArgList Args, which shows how it provides some sanitizer kind from Mask.
static std::string describeSanitizeArg (const llvm::opt::Arg *A, SanitizerMask Mask)
Produce an argument string from argument A, which shows how it provides a value in Mask.
static std::string toString (const clang::SanitizerSet &Sanitizers)
Produce a string containing comma-separated names of sanitizers in Sanitizers set.
static bool isExecuteOnlyTarget (const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
Return true if an execute-only target disallows data access to code sections.
static void validateSpecialCaseListFormat (const Driver &D, std::vector< std::string > &SCLFiles, unsigned MalformedSCLErrorDiagID, bool DiagnoseErrors)
static void addDefaultIgnorelists (const Driver &D, SanitizerMask Kinds, std::vector< std::string > &IgnorelistFiles, bool DiagnoseErrors)
static void parseSpecialCaseListArg (const Driver &D, const llvm::opt::ArgList &Args, std::vector< std::string > &SCLFiles, llvm::opt::OptSpecifier SCLOptionID, llvm::opt::OptSpecifier NoSCLOptionID, unsigned MalformedSCLErrorDiagID, bool DiagnoseErrors)
Parse -f(no-)?sanitize-(coverage-)?(allow|ignore)list argument's values, diagnosing any invalid file paths and validating special case list format.
static SanitizerMask setGroupBits (SanitizerMask Kinds)
Sets group bits for every group that has at least one representative already enabled in Kinds.
static SanitizerMask parseSanitizeTrapArgs (const Driver &D, const llvm::opt::ArgList &Args, bool DiagnoseErrors)
static void addSpecialCaseListOpt (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const char *SCLOptFlag, const std::vector< std::string > &SCLFiles)
static void addIncludeLinkerOption (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, StringRef SymbolName)
static bool hasTargetFeatureMTE (const llvm::opt::ArgStringList &CmdArgs)
Variables
static const SanitizerMask NeedsUbsanRt
static const SanitizerMask NeedsUbsanCxxRt
static const SanitizerMask NotAllowedWithTrap = SanitizerKind::Vptr
static const SanitizerMask NotAllowedWithMinimalRuntime = SanitizerKind::Vptr
static const SanitizerMask NotAllowedWithExecuteOnly
static const SanitizerMask RequiresPIE
static const SanitizerMask NeedsUnwindTables
static const SanitizerMask SupportsCoverage
static const SanitizerMask RecoverableByDefault
static const SanitizerMask Unrecoverable
static const SanitizerMask AlwaysRecoverable
static const SanitizerMask NeedsLTO = SanitizerKind::CFI
static const SanitizerMask TrappingSupported
static const SanitizerMask TrappingDefault = SanitizerKind::CFI
static const SanitizerMask CFIClasses
static const SanitizerMask CompatibleWithMinimalRuntime
Macro Definition Documentation
SANITIZER [1/2]
#define SANITIZER (NAME, ID)
SANITIZER [2/2]
#define SANITIZER (NAME, ID)
Value:
  if (Sanitizers.has(SanitizerKind::ID)) {                                     \
    if (!Res.empty())                                                          \
      Res += ",";                                                              \
    Res += NAME;                                                               \
  }
SANITIZER_GROUP
#define SANITIZER_GROUP (NAME, ID, ALIAS)
Value:
  if (Kinds & SanitizerKind::ID)                                               \
    Kinds |= SanitizerKind::ID##Group;
Enumeration Type Documentation
BinaryMetadataFeature
enum BinaryMetadataFeature
Enumerator
BinaryMetadataCovered
BinaryMetadataAtomics
BinaryMetadataUAR
Definition at line 106 of file SanitizerArgs.cpp.
CoverageFeature
enum CoverageFeature
Enumerator
CoverageFunc
CoverageBB
CoverageEdge
CoverageIndirCall
CoverageTraceBB
CoverageTraceCmp
CoverageTraceDiv
CoverageTraceGep
Coverage8bitCounters
CoverageTracePC
CoverageTracePCGuard
CoverageNoPrune
CoverageInline8bitCounters
CoveragePCTable
CoverageStackDepth
CoverageInlineBoolFlag
CoverageTraceLoads
CoverageTraceStores
CoverageControlFlow
Definition at line 84 of file SanitizerArgs.cpp.
Function Documentation
addDefaultIgnorelists()
static void addDefaultIgnorelists (const Driver & D, SanitizerMask Kinds, std::vector< std::string > & IgnorelistFiles, bool DiagnoseErrors) static
Definition at line 170 of file SanitizerArgs.cpp.
References clang::driver::Driver::Diag(), clang::File, clang::driver::Driver::getVFS(), clang::driver::Driver::ResourceDir, and validateSpecialCaseListFormat().
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
addIncludeLinkerOption()
static void addIncludeLinkerOption (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, StringRef SymbolName) static
Definition at line 1097 of file SanitizerArgs.cpp.
References clang::driver::ToolChain::getTriple().
Referenced by clang::driver::SanitizerArgs::addArgs().
addSpecialCaseListOpt()
static void addSpecialCaseListOpt (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const char * SCLOptFlag, const std::vector< std::string > & SCLFiles) static
Definition at line 1086 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::addArgs().
describeSanitizeArg()
std::string describeSanitizeArg (const llvm::opt::Arg * A, SanitizerMask Mask) static
Produce an argument string from argument A, which shows how it provides a value in Mask.
For instance, the argument "-fsanitize=address,alignment" with mask NeedsUbsanRt would produce "-fsanitize=alignment".
Definition at line 1496 of file SanitizerArgs.cpp.
References clang::expandSanitizerGroups(), and clang::parseSanitizerValue().
Referenced by lastArgumentForMask(), and clang::driver::SanitizerArgs::SanitizerArgs().
hasTargetFeatureMTE()
static bool hasTargetFeatureMTE (const llvm::opt::ArgStringList & CmdArgs) static
Definition at line 1111 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::addArgs().
isExecuteOnlyTarget()
static bool isExecuteOnlyTarget (const llvm::Triple & Triple, const llvm::opt::ArgList & Args) static
Return true if an execute-only target disallows data access to code sections.
Definition at line 148 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
lastArgumentForMask()
std::string lastArgumentForMask (const Driver & D, const llvm::opt::ArgList & Args, SanitizerMask Mask) static
Produce an argument string from ArgList Args, which shows how it provides some sanitizer kind from Mask.
For example, the argument list "-fsanitize=thread,vptr -fsanitize=address" with mask NeedsUbsanRt would produce "-fsanitize=vptr".
Definition at line 1476 of file SanitizerArgs.cpp.
References describeSanitizeArg(), clang::expandSanitizerGroups(), and parseArgValues().
Referenced by clang::driver::SanitizerArgs::addArgs(), and clang::driver::SanitizerArgs::SanitizerArgs().
parseArgValues()
SanitizerMask parseArgValues (const Driver & D, const llvm::opt::Arg * A, bool DiagnoseErrors) static
Parse a -fsanitize= or -fno-sanitize= argument's values, diagnosing any invalid components.
Returns a SanitizerMask.
Definition at line 1388 of file SanitizerArgs.cpp.
References clang::driver::Driver::Diag(), and clang::parseSanitizerValue().
Referenced by lastArgumentForMask(), parseSanitizeTrapArgs(), and clang::driver::SanitizerArgs::SanitizerArgs().
parseBinaryMetadataFeatures()
int parseBinaryMetadataFeatures (const Driver & D, const llvm::opt::Arg * A, bool DiagnoseErrors) static
Parse -f(no-)?sanitize-metadata= flag values, diagnosing any invalid components.
Returns OR of members of BinaryMetadataFeature enumeration.
Definition at line 1453 of file SanitizerArgs.cpp.
References BinaryMetadataAtomics, BinaryMetadataCovered, BinaryMetadataUAR, and clang::driver::Driver::Diag().
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
parseCoverageFeatures()
int parseCoverageFeatures (const Driver & D, const llvm::opt::Arg * A, bool DiagnoseErrors) static
Parse -f(no-)?sanitize-coverage= flag values, diagnosing any invalid components.
Returns OR of members of CoverageFeature enumeration.
Definition at line 1417 of file SanitizerArgs.cpp.
References Coverage8bitCounters, CoverageBB, CoverageControlFlow, CoverageEdge, CoverageFunc, CoverageIndirCall, CoverageInline8bitCounters, CoverageInlineBoolFlag, CoverageNoPrune, CoveragePCTable, CoverageStackDepth, CoverageTraceBB, CoverageTraceCmp, CoverageTraceDiv, CoverageTraceGep, CoverageTraceLoads, CoverageTracePC, CoverageTracePCGuard, CoverageTraceStores, and clang::driver::Driver::Diag().
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
parseSanitizeTrapArgs()
static SanitizerMask parseSanitizeTrapArgs (const Driver & D, const llvm::opt::ArgList & Args, bool DiagnoseErrors) static
Definition at line 246 of file SanitizerArgs.cpp.
References clang::driver::Driver::Diag(), clang::expandSanitizerGroups(), parseArgValues(), setGroupBits(), toString(), TrappingDefault, and TrappingSupported.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
parseSpecialCaseListArg()
static void parseSpecialCaseListArg (const Driver & D, const llvm::opt::ArgList & Args, std::vector< std::string > & SCLFiles, llvm::opt::OptSpecifier SCLOptionID, llvm::opt::OptSpecifier NoSCLOptionID, unsigned MalformedSCLErrorDiagID, bool DiagnoseErrors) static
Parse -f(no-)?sanitize-(coverage-)?(allow|ignore)list argument's values, diagnosing any invalid file paths and validating special case list format.
Definition at line 208 of file SanitizerArgs.cpp.
References clang::driver::Driver::Diag(), clang::driver::Driver::getVFS(), and validateSpecialCaseListFormat().
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
setGroupBits()
static SanitizerMask setGroupBits (SanitizerMask Kinds) static
Sets group bits for every group that has at least one representative already enabled in Kinds.
Definition at line 237 of file SanitizerArgs.cpp.
Referenced by parseSanitizeTrapArgs(), and clang::driver::SanitizerArgs::SanitizerArgs().
toString()
static std::string toString (const clang::SanitizerSet & Sanitizers) static
Produce a string containing comma-separated names of sanitizers in Sanitizers set.
Definition at line 1074 of file SanitizerArgs.cpp.
Referenced by clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPArrayShapingExpr(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnPragmaClangSection(), clang::driver::SanitizerArgs::addArgs(), AnalyzeBitFieldAssignment(), clang::ast_matchers::AST_MATCHER_P(), clang::Sema::BuildArrayType(), clang::Sema::BuildCXXNew(), clang::driver::Driver::BuildJobs(), CheckArrayDesignatorExpr(), checkCaseValue(), checkCodeSegName(), CheckedIntArithmetic(), clang::Sema::CheckEnumConstant(), CheckForDuplicateEnumValues(), CheckImplicitConversion(), clang::Sema::CheckLoopHintExpr(), checkPositiveIntArgument(), clang::Sema::checkSectionName(), checkSimpleDecomposition(), clang::Sema::CheckTemplateArgument(), checkTupleLikeDecomposition(), clang::Sema::CheckTypedefForVariablyModifiedType(), checkUInt32Argument(), DefineTypeSize(), diagnoseWellFormedUnsatisfiedConstraintExpr(), diagnoseXorMisusedAsPow(), DiagTemplateArg(), clang::ento::Range::dump(), clang::ento::CheckerInfo::dumpToStream(), EvaluateDirectiveSubExpr(), getModuleContextHash(), clang::CompilerInvocation::getModuleHash(), clang::threadSafety::getSourceLiteralString(), clang::tooling::RefactoringASTConsumer::HandleTranslationUnit(), IsStructurallyEquivalent(), makeLaunchBoundsArgExpr(), clang::operator<<(), parseSanitizeTrapArgs(), PrettyPrintInRange(), clang::ento::CheckerManager::runCheckersForEvalCall(), clang::driver::SanitizerArgs::SanitizerArgs(), SemaBuiltinAlignment(), toString(), clang::Sema::tryToFixVariablyModifiedVarType(), clang::Sema::VerifyBitField(), clang::TextNodeDumper::VisitIntegerLiteral(), clang::Interpreter::~Interpreter(), and clang::SavedStreamPosition::~SavedStreamPosition().
validateSpecialCaseListFormat()
static void validateSpecialCaseListFormat (const Driver & D, std::vector< std::string > & SCLFiles, unsigned MalformedSCLErrorDiagID, bool DiagnoseErrors) static
Definition at line 156 of file SanitizerArgs.cpp.
References clang::driver::Driver::Diag(), and clang::driver::Driver::getVFS().
Referenced by addDefaultIgnorelists(), and parseSpecialCaseListArg().
Variable Documentation
AlwaysRecoverable
const SanitizerMask AlwaysRecoverable static
Initial value:
= SanitizerKind::KernelAddress |
                                               SanitizerKind::KernelHWAddress |
                                               SanitizerKind::KCFI
Definition at line 65 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
CFIClasses
const SanitizerMask CFIClasses static
Initial value:
=
    SanitizerKind::CFIVCall | SanitizerKind::CFINVCall |
    SanitizerKind::CFIMFCall | SanitizerKind::CFIDerivedCast |
    SanitizerKind::CFIUnrelatedCast
Definition at line 75 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::addArgs().
CompatibleWithMinimalRuntime
const SanitizerMask CompatibleWithMinimalRuntime static
Initial value:
=
    TrappingSupported | SanitizerKind::Scudo | SanitizerKind::ShadowCallStack |
    SanitizerKind::MemtagStack | SanitizerKind::MemtagHeap |
    SanitizerKind::MemtagGlobals | SanitizerKind::KCFI
Definition at line 79 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
NeedsLTO
const SanitizerMask NeedsLTO = SanitizerKind::CFI static
Definition at line 68 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::needsLTO(), and clang::driver::SanitizerArgs::SanitizerArgs().
NeedsUbsanCxxRt
const SanitizerMask NeedsUbsanCxxRt static
Initial value:
=
    SanitizerKind::Vptr | SanitizerKind::CFI
Definition at line 36 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
NeedsUbsanRt
const SanitizerMask NeedsUbsanRt static
Initial value:
=
    SanitizerKind::Undefined | SanitizerKind::Integer |
    SanitizerKind::ImplicitConversion | SanitizerKind::Nullability |
    SanitizerKind::CFI | SanitizerKind::FloatDivideByZero |
    SanitizerKind::ObjCCast
Definition at line 31 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::needsUbsanRt().
NeedsUnwindTables
const SanitizerMask NeedsUnwindTables static
Initial value:
=
    SanitizerKind::Address | SanitizerKind::HWAddress | SanitizerKind::Thread |
    SanitizerKind::Memory | SanitizerKind::DataFlow
Definition at line 44 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::needsUnwindTables().
NotAllowedWithExecuteOnly
const SanitizerMask NotAllowedWithExecuteOnly static
Initial value:
=
    SanitizerKind::Function | SanitizerKind::KCFI
Definition at line 40 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
NotAllowedWithMinimalRuntime
const SanitizerMask NotAllowedWithMinimalRuntime = SanitizerKind::Vptr static
Definition at line 39 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
NotAllowedWithTrap
const SanitizerMask NotAllowedWithTrap = SanitizerKind::Vptr static
Definition at line 38 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
RecoverableByDefault
const SanitizerMask RecoverableByDefault static
Initial value:
=
    SanitizerKind::Undefined | SanitizerKind::Integer |
    SanitizerKind::ImplicitConversion | SanitizerKind::Nullability |
    SanitizerKind::FloatDivideByZero | SanitizerKind::ObjCCast
Definition at line 59 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
RequiresPIE
const SanitizerMask RequiresPIE static
Initial value:
=
    SanitizerKind::DataFlow | SanitizerKind::Scudo
Definition at line 42 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::requiresPIE().
SupportsCoverage
const SanitizerMask SupportsCoverage static
Initial value:
=
    SanitizerKind::Address | SanitizerKind::HWAddress |
    SanitizerKind::KernelAddress | SanitizerKind::KernelHWAddress |
    SanitizerKind::MemtagStack | SanitizerKind::MemtagHeap |
    SanitizerKind::MemtagGlobals | SanitizerKind::Memory |
    SanitizerKind::KernelMemory | SanitizerKind::Leak |
    SanitizerKind::Undefined | SanitizerKind::Integer | SanitizerKind::Bounds |
    SanitizerKind::ImplicitConversion | SanitizerKind::Nullability |
    SanitizerKind::DataFlow | SanitizerKind::Fuzzer |
    SanitizerKind::FuzzerNoLink | SanitizerKind::FloatDivideByZero |
    SanitizerKind::SafeStack | SanitizerKind::ShadowCallStack |
    SanitizerKind::Thread | SanitizerKind::ObjCCast | SanitizerKind::KCFI
Definition at line 47 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
TrappingDefault
const SanitizerMask TrappingDefault = SanitizerKind::CFI static
Definition at line 74 of file SanitizerArgs.cpp.
Referenced by parseSanitizeTrapArgs().
TrappingSupported
const SanitizerMask TrappingSupported static
Initial value:
=
    (SanitizerKind::Undefined & ~SanitizerKind::Vptr) | SanitizerKind::Integer |
    SanitizerKind::Nullability | SanitizerKind::LocalBounds |
    SanitizerKind::CFI | SanitizerKind::FloatDivideByZero |
    SanitizerKind::ObjCCast
Definition at line 69 of file SanitizerArgs.cpp.
Referenced by parseSanitizeTrapArgs().
Unrecoverable
const SanitizerMask Unrecoverable static
Initial value:
=
    SanitizerKind::Unreachable | SanitizerKind::Return
Definition at line 63 of file SanitizerArgs.cpp.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().