clang: lib/AST/ScanfFormatString.cpp File Reference
ScanfFormatString.cpp File Reference
#include "clang/AST/FormatString.h"
#include "FormatStringParsing.h"
#include "clang/Basic/TargetInfo.h"
Typedefs
typedef clang::analyze_format_string::SpecifierResult< ScanfSpecifier > ScanfSpecifierResult
Functions
static bool ParseScanList (FormatStringHandler &H, ScanfConversionSpecifier &CS, const char *&Beg, const char *E)
static ScanfSpecifierResult ParseScanfSpecifier (FormatStringHandler &H, const char *&Beg, const char *E, unsigned &argIndex, const LangOptions &LO, const TargetInfo &Target)
Typedef Documentation
ScanfSpecifierResult
typedef clang::analyze_format_string::SpecifierResult<ScanfSpecifier> ScanfSpecifierResult
Definition at line 29 of file ScanfFormatString.cpp.
Function Documentation
ParseScanfSpecifier()
static ScanfSpecifierResult ParseScanfSpecifier (FormatStringHandler & H, const char *& Beg, const char * E, unsigned & argIndex, const LangOptions & LO, const TargetInfo & Target) static
Definition at line 75 of file ScanfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::bArg, c, clang::analyze_format_string::ConversionSpecifier::CArg, clang::analyze_format_string::ConversionSpecifier::cArg, clang::analyze_format_string::OptionalAmount::Constant, clang::analyze_format_string::ConversionSpecifier::consumesDataArgument(), clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::OptionalAmount::getHowSpecified(), clang::analyze_format_string::FormatStringHandler::HandleIncompleteSpecifier(), clang::analyze_format_string::FormatStringHandler::HandleInvalidScanfConversionSpecifier(), clang::analyze_format_string::FormatStringHandler::HandleNullChar(), clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::InvalidSpecifier, clang::analyze_format_string::ConversionSpecifier::nArg, clang::analyze_format_string::OptionalAmount::NotSpecified, clang::analyze_format_string::ConversionSpecifier::OArg, clang::analyze_format_string::ConversionSpecifier::oArg, clang::analyze_format_string::ConversionSpecifier::pArg, clang::analyze_format_string::ParseAmount(), ParseScanList(), clang::analyze_format_string::ConversionSpecifier::PercentArg, clang::analyze_format_string::ConversionSpecifier::SArg, clang::analyze_format_string::ConversionSpecifier::sArg, clang::analyze_format_string::ConversionSpecifier::ScanListArg, clang::analyze_format_string::ConversionSpecifier::setEndScanList(), clang::analyze_format_string::ConversionSpecifier::UArg, clang::analyze_format_string::ConversionSpecifier::uArg, clang::analyze_format_string::ConversionSpecifier::XArg, and clang::analyze_format_string::ConversionSpecifier::xArg.
Referenced by clang::analyze_format_string::ParseScanfString().
ParseScanList()
static bool ParseScanList (FormatStringHandler & H, ScanfConversionSpecifier & CS, const char *& Beg, const char * E) static
Definition at line 31 of file ScanfFormatString.cpp.
References clang::analyze_format_string::FormatStringHandler::HandleIncompleteScanList(), and clang::analyze_format_string::ConversionSpecifier::setEndScanList().
Referenced by ParseScanfSpecifier().