clang: lib/Sema/SemaFixItUtils.cpp File Reference
SemaFixItUtils.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaFixItUtils.h"
Functions
static bool isMacroDefined (const Sema &S, SourceLocation Loc, StringRef Name)
static std::string getScalarZeroExpressionForType (const Type &T, SourceLocation Loc, const Sema &S)
Function Documentation
getScalarZeroExpressionForType()
static std::string getScalarZeroExpressionForType (const Type & T, SourceLocation Loc, const Sema & S) static
Definition at line 171 of file SemaFixItUtils.cpp.
References isMacroDefined(), and clang::Sema::LangOpts.
Referenced by clang::Sema::getFixItZeroInitializerForType(), and clang::Sema::getFixItZeroLiteralForType().
isMacroDefined()
static bool isMacroDefined (const Sema & S, SourceLocation Loc, StringRef Name) static
Definition at line 166 of file SemaFixItUtils.cpp.
References clang::IdentifierTable::get(), clang::Sema::getASTContext(), clang::Preprocessor::getMacroDefinitionAtLoc(), clang::ASTContext::Idents, and clang::Sema::PP.
Referenced by getScalarZeroExpressionForType().