clang: lib/Sema/SemaAccess.cpp File Reference
SemaAccess.cpp File Reference
#include "clang/Basic/Specifiers.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DependentDiagnostic.h"
#include "clang/AST/ExprCXX.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
Enumerations
enum AccessResult { AR_accessible , AR_inaccessible , AR_dependent }
A copy of Sema's enum without AR_delayed.
Functions
static CXXRecordDecl * FindDeclaringClass (NamedDecl *D)
static bool MightInstantiateTo (const CXXRecordDecl *From, const CXXRecordDecl *To)
Checks whether one class might instantiate to the other.
static AccessResult IsDerivedFromInclusive (const CXXRecordDecl *Derived, const CXXRecordDecl *Target)
Checks whether one class is derived from another, inclusively.
static bool MightInstantiateTo (Sema &S, DeclContext *Context, DeclContext *Friend)
static bool MightInstantiateTo (Sema &S, CanQualType Context, CanQualType Friend)
static bool MightInstantiateTo (Sema &S, FunctionDecl *Context, FunctionDecl *Friend)
static bool MightInstantiateTo (Sema &S, FunctionTemplateDecl *Context, FunctionTemplateDecl *Friend)
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, const CXXRecordDecl *Friend)
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, CanQualType Friend)
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, ClassTemplateDecl *Friend)
Determines whether the given friend class template matches anything in the effective context.
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, FunctionDecl *Friend)
Determines whether the given friend function matches anything in the effective context.
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, FunctionTemplateDecl *Friend)
Determines whether the given friend function template matches anything in the effective context.
static AccessResult MatchesFriend (Sema &S, const EffectiveContext &EC, FriendDecl *FriendD)
Determines whether the given friend declaration matches anything in the effective context.
static AccessResult GetFriendKind (Sema &S, const EffectiveContext &EC, const CXXRecordDecl *Class)
static AccessResult GetProtectedFriendKind (Sema &S, const EffectiveContext &EC, const CXXRecordDecl *InstanceContext, const CXXRecordDecl *NamingClass)
Search for a class P that EC is a friend of, under the constraint InstanceContext <= P if InstanceContext exists, or else NamingClass <= P and with the additional restriction that a protected member of NamingClass would have some natural access in P, which implicitly imposes the constraint that P <= NamingClass.
static AccessResult HasAccess (Sema &S, const EffectiveContext &EC, const CXXRecordDecl *NamingClass, AccessSpecifier Access, const AccessTarget &Target)
static CXXBasePath * FindBestPath (Sema &S, const EffectiveContext &EC, AccessTarget &Target, AccessSpecifier FinalAccess, CXXBasePaths &Paths)
Finds the best path from the naming class to the declaring class, taking friend declarations into account.
static bool TryDiagnoseProtectedAccess (Sema &S, const EffectiveContext &EC, AccessTarget &Target)
Given that an entity has protected natural access, check whether access might be denied because of the protected member access restriction.
static void diagnoseBadDirectAccess (Sema &S, const EffectiveContext &EC, AccessTarget &entity)
We are unable to access a given declaration due to its direct access control; diagnose that.
static void DiagnoseAccessPath (Sema &S, const EffectiveContext &EC, AccessTarget &entity)
Diagnose the path which caused the given declaration or base class to become inaccessible.
static void DiagnoseBadAccess (Sema &S, SourceLocation Loc, const EffectiveContext &EC, AccessTarget &Entity)
static bool IsMicrosoftUsingDeclarationAccessBug (Sema &S, SourceLocation AccessLoc, AccessTarget &Entity)
MSVC has a bug where if during an using declaration name lookup, the declaration found is unaccessible (private) and that declaration was bring into scope via another using declaration whose target declaration is accessible (public) then no error is generated.
static AccessResult IsAccessible (Sema &S, const EffectiveContext &EC, AccessTarget &Entity)
Determines whether the accessed entity is accessible.
static void DelayDependentAccess (Sema &S, const EffectiveContext &EC, SourceLocation Loc, const AccessTarget &Entity)
static AccessResult CheckEffectiveAccess (Sema &S, const EffectiveContext &EC, SourceLocation Loc, AccessTarget &Entity)
Checks access to an entity from the given effective context.
static Sema::AccessResult CheckAccess (Sema &S, SourceLocation Loc, AccessTarget &Entity)
Enumeration Type Documentation
AccessResult
enum AccessResult
A copy of Sema's enum without AR_delayed.
Enumerator
AR_accessible
AR_inaccessible
AR_dependent
Definition at line 30 of file SemaAccess.cpp.
Function Documentation
CheckAccess()
static Sema::AccessResult CheckAccess (Sema & S, SourceLocation Loc, AccessTarget & Entity) static
Definition at line 1461 of file SemaAccess.cpp.
References clang::Sema::DelayedDiagnostics::add(), AR_accessible, clang::Sema::AR_accessible, clang::Sema::AR_delayed, AR_dependent, clang::Sema::AR_dependent, AR_inaccessible, clang::Sema::AR_inaccessible, clang::AS_public, CheckEffectiveAccess(), clang::Sema::CurContext, clang::Sema::DelayedDiagnostics, clang::sema::DelayedDiagnostic::makeAccess(), and clang::Sema::DelayedDiagnostics::shouldDelayDiagnostics().
Referenced by clang::Sema::CheckAddressOfMemberAccess(), clang::Sema::CheckAllocationAccess(), clang::Sema::CheckBaseClassAccess(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckDestructorAccess(), clang::Sema::CheckLookupAccess(), clang::Sema::CheckMemberAccess(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckStructuredBindingMemberAccess(), clang::Sema::CheckUnresolvedLookupAccess(), clang::Sema::CheckUnresolvedMemberAccess(), clang::Sema::HandleDependentAccessCheck(), and clang::Sema::isMemberAccessibleForDeletion().
CheckEffectiveAccess()
static AccessResult CheckEffectiveAccess (Sema & S, const EffectiveContext & EC, SourceLocation Loc, AccessTarget & Entity) static
Checks access to an entity from the given effective context.
Definition at line 1434 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::AS_public, DelayDependentAccess(), DiagnoseBadAccess(), clang::Sema::getLangOpts(), IsAccessible(), and IsMicrosoftUsingDeclarationAccessBug().
Referenced by CheckAccess(), clang::Sema::CheckBaseClassAccess(), clang::Sema::CheckFriendAccess(), and clang::Sema::HandleDelayedAccessCheck().
DelayDependentAccess()
static void DelayDependentAccess (Sema & S, const EffectiveContext & EC, SourceLocation Loc, const AccessTarget & Entity) static
Definition at line 1416 of file SemaAccess.cpp.
References clang::DependentDiagnostic::Access, clang::Sema::Context, clang::DependentDiagnostic::Create(), and clang::DeclContext::isDependentContext().
Referenced by CheckEffectiveAccess().
DiagnoseAccessPath()
static void DiagnoseAccessPath (Sema & S, const EffectiveContext & EC, AccessTarget & entity) static
Diagnose the path which caused the given declaration or base class to become inaccessible.
Definition at line 1173 of file SemaAccess.cpp.
References clang::CXXBasePath::Access, AR_accessible, AR_dependent, AR_inaccessible, clang::AS_none, clang::AS_private, clang::AS_protected, clang::AS_public, clang::Sema::Diag(), diagnoseBadDirectAccess(), FindBestPath(), clang::Decl::getAccess(), clang::CXXBaseSpecifier::getAccessSpecifier(), clang::CXXBaseSpecifier::getAccessSpecifierAsWritten(), clang::SourceRange::getBegin(), clang::CXXRecordDecl::getCanonicalDecl(), clang::CXXBaseSpecifier::getSourceRange(), and HasAccess().
Referenced by DiagnoseBadAccess().
DiagnoseBadAccess()
static void DiagnoseBadAccess (Sema & S, SourceLocation Loc, const EffectiveContext & EC, AccessTarget & Entity) static
Definition at line 1282 of file SemaAccess.cpp.
References clang::AS_protected, clang::Sema::Context, clang::Sema::Diag(), DiagnoseAccessPath(), clang::NamedDecl::getDeclName(), and clang::ASTContext::getTypeDeclType().
Referenced by CheckEffectiveAccess().
diagnoseBadDirectAccess()
static void diagnoseBadDirectAccess (Sema & S, const EffectiveContext & EC, AccessTarget & entity) static
We are unable to access a given declaration due to its direct access control; diagnose that.
Definition at line 1116 of file SemaAccess.cpp.
References clang::AS_protected, clang::cast(), clang::DeclContext::decls(), clang::Sema::Diag(), FindDeclaringClass(), clang::Decl::getAccess(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::DeclContext::getParent(), clang::Decl::getPreviousDecl(), clang::Decl::isOutOfLine(), and TryDiagnoseProtectedAccess().
Referenced by DiagnoseAccessPath().
FindBestPath()
static CXXBasePath * FindBestPath (Sema & S, const EffectiveContext & EC, AccessTarget & Target, AccessSpecifier FinalAccess, CXXBasePaths & Paths) static
Finds the best path from the naming class to the declaring class, taking friend declarations into account.
C++0x [class.access.base]p5: A member m is accessible at the point R when named in class N if [M1] m as a member of N is public, or [M2] m as a member of N is private, and R occurs in a member or friend of class N, or [M3] m as a member of N is protected, and R occurs in a member or friend of class N, or in a member or friend of a class P derived from N, where m as a member of P is public, private, or protected, or [M4] there exists a base class B of N that is accessible at R, and m is accessible at R when named in class B.
C++0x [class.access.base]p4: A base class B of N is accessible at R, if [B1] an invented public member of B would be a public member of N, or [B2] R occurs in a member or friend of class N, and an invented public member of B would be a private or protected member of N, or [B3] R occurs in a member or friend of a class P derived from N, and an invented public member of B would be a private or protected member of P, or [B4] there exists a class S such that B is a base class of S accessible at R and S is a base class of N accessible at R.
Along a single inheritance path we can restate both of these iteratively:
First, we note that M1-4 are equivalent to B1-4 if the member is treated as a notional base of its declaring class with inheritance access equivalent to the member's access. Therefore we need only ask whether a class B is accessible from a class N in context R.
Let B_1 .. B_n be the inheritance path in question (i.e. where B_1 = N, B_n = B, and for all i, B_{i+1} is a direct base class of B_i). For i in 1..n, we will calculate ACAB(i), the access to the closest accessible base in the path: Access(a, b) = (* access on the base specifier from a to b *) Merge(a, forbidden) = forbidden Merge(a, private) = forbidden Merge(a, b) = min(a,b) Accessible(c, forbidden) = false Accessible(c, private) = (R is c) || IsFriend(c, R) Accessible(c, protected) = (R derived from c) || IsFriend(c, R) Accessible(c, public) = true ACAB(n) = public ACAB(i) = let AccessToBase = Merge(Access(B_i, B_{i+1}), ACAB(i+1)) in if Accessible(B_i, AccessToBase) then public else AccessToBase
B is an accessible base of N at R iff ACAB(1) = public.
Parameters
FinalAccess the access of the "final step", or AS_public if there is no final step.
Returns
null if friendship is dependent
Definition at line 949 of file SemaAccess.cpp.
References clang::CXXBasePath::Access, AR_accessible, AR_dependent, AR_inaccessible, clang::AS_none, clang::AS_private, clang::AS_public, clang::CXXRecordDecl::getCanonicalDecl(), HasAccess(), clang::CXXRecordDecl::isDerivedFrom(), and Next.
Referenced by DiagnoseAccessPath(), and IsAccessible().
FindDeclaringClass()
static CXXRecordDecl * FindDeclaringClass (NamedDecl * D) static
Definition at line 65 of file SemaAccess.cpp.
References clang::cast(), clang::Decl::getDeclContext(), and clang::RecordDecl::isAnonymousStructOrUnion().
Referenced by diagnoseBadDirectAccess().
GetFriendKind()
static AccessResult GetFriendKind (Sema & S, const EffectiveContext & EC, const CXXRecordDecl * Class) static
Definition at line 592 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, and MatchesFriend().
Referenced by GetProtectedFriendKind(), and HasAccess().
GetProtectedFriendKind()
static AccessResult GetProtectedFriendKind (Sema & S, const EffectiveContext & EC, const CXXRecordDecl * InstanceContext, const CXXRecordDecl * NamingClass) static
Search for a class P that EC is a friend of, under the constraint InstanceContext <= P if InstanceContext exists, or else NamingClass <= P and with the additional restriction that a protected member of NamingClass would have some natural access in P, which implicitly imposes the constraint that P <= NamingClass.
This isn't quite the condition laid out in the standard. Instead of saying that a notional protected member of NamingClass would have to have some natural access in P, it says the actual target has to have some natural access in P, which opens up the possibility that the target (which is not necessarily a member of NamingClass) might be more accessible along some path not passing through it. That's really a bad idea, though, because it introduces two problems:
Most importantly, it breaks encapsulation because you can access a forbidden base class's members by directly subclassing it elsewhere.
It also makes access substantially harder to compute because it breaks the hill-climbing algorithm: knowing that the target is accessible in some base class would no longer let you change the question solely to whether the base class is accessible, because the original target might have been more accessible because of crazy subclassing. So we don't implement that.
Definition at line 733 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::CXXRecordDecl::getCanonicalDecl(), and GetFriendKind().
Referenced by HasAccess().
HasAccess()
static AccessResult HasAccess (Sema & S, const EffectiveContext & EC, const CXXRecordDecl * NamingClass, AccessSpecifier Access, const AccessTarget & Target) static
Definition at line 751 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::AS_private, clang::AS_protected, clang::AS_public, clang::CXXRecordDecl::getCanonicalDecl(), GetFriendKind(), clang::Sema::getLangOpts(), GetProtectedFriendKind(), IsDerivedFromInclusive(), and MightInstantiateTo().
Referenced by DiagnoseAccessPath(), FindBestPath(), and IsAccessible().
IsAccessible()
static AccessResult IsAccessible (Sema & S, const EffectiveContext & EC, AccessTarget & Entity) static
Determines whether the accessed entity is accessible.
Public members have been weeded out by this point.
Definition at line 1338 of file SemaAccess.cpp.
References clang::CXXBasePath::Access, AR_accessible, AR_dependent, AR_inaccessible, clang::AS_none, clang::AS_public, FindBestPath(), and HasAccess().
Referenced by CheckEffectiveAccess().
IsDerivedFromInclusive()
static AccessResult IsDerivedFromInclusive (const CXXRecordDecl * Derived, const CXXRecordDecl * Target) static
Checks whether one class is derived from another, inclusively.
Properly indicates when it couldn't be determined due to dependence.
This should probably be donated to AST or at least Sema.
Definition at line 302 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::CXXRecordDecl::bases(), clang::cast(), clang::CXXRecordDecl::getCanonicalDecl(), clang::CXXRecordDecl::hasDefinition(), clang::DeclContext::isDependentContext(), clang::CXXRecordDecl::isLambda(), and MightInstantiateTo().
Referenced by HasAccess(), and TryDiagnoseProtectedAccess().
IsMicrosoftUsingDeclarationAccessBug()
static bool IsMicrosoftUsingDeclarationAccessBug (Sema & S, SourceLocation AccessLoc, AccessTarget & Entity) static
MSVC has a bug where if during an using declaration name lookup, the declaration found is unaccessible (private) and that declaration was bring into scope via another using declaration whose target declaration is accessible (public) then no error is generated.
Example: class A { public: int f(); }; class B : public A { private: using A::f; }; class C : public B { private: using B::f; };
Here, B::f is private so this should fail in Standard C++, but because B::f refers to A::f which is public MSVC accepts it.
Definition at line 1317 of file SemaAccess.cpp.
References clang::AS_private, clang::AS_protected, clang::AS_public, clang::Sema::Diag(), clang::Decl::getAccess(), and clang::NamedDecl::getQualifiedNameAsString().
Referenced by CheckEffectiveAccess().
MatchesFriend() [1/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, CanQualType Friend) static
Definition at line 446 of file SemaAccess.cpp.
References AR_dependent, AR_inaccessible, clang::CanQual< typename >::getAs(), and MatchesFriend().
MatchesFriend() [2/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, ClassTemplateDecl * Friend) static
Determines whether the given friend class template matches anything in the effective context.
Definition at line 461 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::cast(), clang::ClassTemplateDecl::getCanonicalDecl(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), and MightInstantiateTo().
MatchesFriend() [3/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, const CXXRecordDecl * Friend) static
Definition at line 430 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, and MightInstantiateTo().
Referenced by GetFriendKind(), MatchesFriend(), and MatchesFriend().
MatchesFriend() [4/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, FriendDecl * FriendD) static
Determines whether the given friend declaration matches anything in the effective context.
Definition at line 563 of file SemaAccess.cpp.
References AR_accessible, clang::cast(), clang::Decl::getCanonicalDecl(), clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendType(), clang::Decl::isInvalidDecl(), clang::FriendDecl::isUnsupportedFriend(), and MatchesFriend().
MatchesFriend() [5/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, FunctionDecl * Friend) static
Determines whether the given friend function matches anything in the effective context.
Definition at line 514 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, and MightInstantiateTo().
MatchesFriend() [6/6]
static AccessResult MatchesFriend (Sema & S, const EffectiveContext & EC, FunctionTemplateDecl * Friend) static
Determines whether the given friend function template matches anything in the effective context.
Definition at line 533 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::FunctionTemplateDecl::getCanonicalDecl(), and MightInstantiateTo().
MightInstantiateTo() [1/5]
static bool MightInstantiateTo (const CXXRecordDecl * From, const CXXRecordDecl * To) static
Checks whether one class might instantiate to the other.
Definition at line 282 of file SemaAccess.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::DeclContext::getPrimaryContext(), and clang::DeclContext::isFileContext().
Referenced by HasAccess(), IsDerivedFromInclusive(), MatchesFriend(), MatchesFriend(), MatchesFriend(), MatchesFriend(), MightInstantiateTo(), and MightInstantiateTo().
MightInstantiateTo() [2/5]
static bool MightInstantiateTo (Sema & S, CanQualType Context, CanQualType Friend) static
Definition at line 373 of file SemaAccess.cpp.
MightInstantiateTo() [3/5]
static bool MightInstantiateTo (Sema & S, DeclContext * Context, DeclContext * Friend) static
Definition at line 353 of file SemaAccess.cpp.
References clang::DeclContext::isDependentContext(), and clang::DeclContext::isFileContext().
MightInstantiateTo() [4/5]
static bool MightInstantiateTo (Sema & S, FunctionDecl * Context, FunctionDecl * Friend) static
Definition at line 384 of file SemaAccess.cpp.
References clang::Sema::Context, clang::CanQual< typename >::getAs(), clang::ASTContext::getCanonicalType(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::CanQual< typename >::getQualifiers(), clang::ValueDecl::getType(), and MightInstantiateTo().
MightInstantiateTo() [5/5]
static bool MightInstantiateTo (Sema & S, FunctionTemplateDecl * Context, FunctionTemplateDecl * Friend) static
Definition at line 422 of file SemaAccess.cpp.
References clang::FunctionTemplateDecl::getTemplatedDecl(), and MightInstantiateTo().
TryDiagnoseProtectedAccess()
static bool TryDiagnoseProtectedAccess (Sema & S, const EffectiveContext & EC, AccessTarget & Target) static
Given that an entity has protected natural access, check whether access might be denied because of the protected member access restriction.
Returns
true if a note was emitted
Definition at line 1041 of file SemaAccess.cpp.
References AR_accessible, AR_dependent, AR_inaccessible, clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAsFunction(), clang::Decl::getLocation(), clang::ASTContext::getTypeDeclType(), clang::isa(), and IsDerivedFromInclusive().
Referenced by diagnoseBadDirectAccess().