clang: lib/Sema/SemaStmtAttr.cpp File Reference
SemaStmtAttr.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/StringExtras.h"
#include <optional>
#include "clang/Sema/AttrParsedAttrImpl.inc"
Macros
#define WANT_STMT_MERGE_LOGIC
Functions
static Attr * handleFallThroughAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleSuppressAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleLoopHintAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange)
static Attr * handleNoMergeAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
template<typename OtherAttr , int DiagIdx>
static bool CheckStmtInlineAttr (Sema &SemaRef, const Stmt *OrigSt, const Stmt *CurSt, const AttributeCommonInfo &A)
static Attr * handleNoInlineAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleAlwaysInlineAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleMustTailAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleLikely (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleUnlikely (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static void CheckForIncompatibleAttributes (Sema &S, const SmallVectorImpl< const Attr * > &Attrs)
static Attr * handleOpenCLUnrollHint (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * ProcessStmtAttribute (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
Macro Definition Documentation
WANT_STMT_MERGE_LOGIC
#define WANT_STMT_MERGE_LOGIC
Definition at line 325 of file SemaStmtAttr.cpp.
Function Documentation
CheckForIncompatibleAttributes()
static void CheckForIncompatibleAttributes (Sema & S, const SmallVectorImpl< const Attr * > & Attrs) static
Definition at line 330 of file SemaStmtAttr.cpp.
References Category, clang::Sema::Context, clang::Sema::Diag(), and clang::ASTContext::getLangOpts().
Referenced by clang::Sema::ProcessStmtAttributes().
CheckStmtInlineAttr()
template<typename OtherAttr , int DiagIdx> static bool CheckStmtInlineAttr (Sema & SemaRef, const Stmt * OrigSt, const Stmt * CurSt, const AttributeCommonInfo & A) static
Definition at line 219 of file SemaStmtAttr.cpp.
References clang::Sema::Diag(), and clang::Stmt::getBeginLoc().
Referenced by clang::Sema::CheckAlwaysInlineAttr(), and clang::Sema::CheckNoInlineAttr().
handleAlwaysInlineAttr()
static Attr * handleAlwaysInlineAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 286 of file SemaStmtAttr.cpp.
References clang::Sema::CheckAlwaysInlineAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Stmt::getBeginLoc().
handleFallThroughAttr()
static Attr * handleFallThroughAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 27 of file SemaStmtAttr.cpp.
References clang::Sema::Context, clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::Stmt::getBeginLoc(), clang::Sema::getCurFunction(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::Sema::getLocForEndOfToken(), clang::AttributeCommonInfo::getRange(), clang::AttributeCommonInfo::getScopeName(), and clang::AttributeCommonInfo::isCXX11Attribute().
Referenced by ProcessStmtAttribute().
handleLikely()
static Attr * handleLikely (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 307 of file SemaStmtAttr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getScopeName(), and clang::AttributeCommonInfo::isCXX11Attribute().
Referenced by ProcessStmtAttribute().
handleLoopHintAttr()
static Attr * handleLoopHintAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange) static
Definition at line 72 of file SemaStmtAttr.cpp.
References clang::Sema::CheckLoopHintExpr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::Stmt::getBeginLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, and clang::IdentifierInfo::isStr().
Referenced by ProcessStmtAttribute().
handleMustTailAttr()
static Attr * handleMustTailAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 301 of file SemaStmtAttr.cpp.
References clang::Sema::Context.
Referenced by ProcessStmtAttribute().
handleNoInlineAttr()
static Attr * handleNoInlineAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 271 of file SemaStmtAttr.cpp.
References clang::Sema::CheckNoInlineAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Stmt::getBeginLoc().
Referenced by ProcessStmtAttribute().
handleNoMergeAttr()
static Attr * handleNoMergeAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 204 of file SemaStmtAttr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), and clang::Stmt::getBeginLoc().
handleOpenCLUnrollHint()
static Attr * handleOpenCLUnrollHint (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 449 of file SemaStmtAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::SourceRange::getBegin(), clang::Expr::getIntegerConstantExpr(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::AttributeCommonInfo::getRange(), and clang::Stmt::getSourceRange().
Referenced by ProcessStmtAttribute().
handleSuppressAttr()
static Attr * handleSuppressAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 54 of file SemaStmtAttr.cpp.
References clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and clang::ParsedAttr::getNumArgs().
handleUnlikely()
static Attr * handleUnlikely (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 316 of file SemaStmtAttr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getScopeName(), and clang::AttributeCommonInfo::isCXX11Attribute().
Referenced by ProcessStmtAttribute().
ProcessStmtAttribute()
static Attr * ProcessStmtAttribute (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 480 of file SemaStmtAttr.cpp.
References clang::Sema::checkCommonAttributeFeatures(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::existsInTarget(), clang::ASTContext::getAuxTargetInfo(), clang::SourceRange::getBegin(), clang::Stmt::getBeginLoc(), clang::ParsedAttr::getKind(), clang::ASTContext::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::ASTContext::getTargetInfo(), handleAlwaysInlineAttr(), handleFallThroughAttr(), handleLikely(), handleLoopHintAttr(), handleMustTailAttr(), handleNoInlineAttr(), handleNoMergeAttr(), handleOpenCLUnrollHint(), handleSuppressAttr(), handleUnlikely(), clang::AttributeCommonInfo::IgnoredAttribute, clang::AttributeCommonInfo::isDeclspecAttribute(), clang::ParsedAttr::isInvalid(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::AttributeCommonInfo::UnknownAttribute.
Referenced by clang::Sema::ProcessStmtAttributes().