clang: lib/Sema/SemaRISCVVectorLookup.cpp File Reference
SemaRISCVVectorLookup.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/RISCVIntrinsicManager.h"
#include "clang/Sema/Sema.h"
#include "clang/Support/RISCVVIntrinsicUtils.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
#include <string>
#include <vector>
#include "clang/Basic/riscv_vector_builtin_sema.inc"
#include "clang/Basic/riscv_sifive_vector_builtin_sema.inc"
Namespaces
namespace clang
Macros
#define DECL_SIGNATURE_TABLE
#define DECL_SIGNATURE_TABLE
#define DECL_INTRINSIC_RECORDS
#define DECL_INTRINSIC_RECORDS
Typedefs
using IntrinsicKind = sema::RISCVIntrinsicManager::IntrinsicKind
Functions
static ArrayRef< PrototypeDescriptor > ProtoSeq2ArrayRef (IntrinsicKind K, uint16_t Index, uint8_t Length)
static QualType RVVType2Qual (ASTContext &Context, const RVVType *Type)
std::unique_ptr< sema::RISCVIntrinsicManager > clang::CreateRISCVIntrinsicManager (Sema &S)
Variables
static const PrototypeDescriptor RVVSignatureTable []
static const PrototypeDescriptor RVSiFiveVectorSignatureTable []
static const RVVIntrinsicRecord RVVIntrinsicRecords []
static const RVVIntrinsicRecord RVSiFiveVectorIntrinsicRecords []
Macro Definition Documentation
DECL_INTRINSIC_RECORDS [1/2]
#define DECL_INTRINSIC_RECORDS
DECL_INTRINSIC_RECORDS [2/2]
#define DECL_INTRINSIC_RECORDS
DECL_SIGNATURE_TABLE [1/2]
#define DECL_SIGNATURE_TABLE
DECL_SIGNATURE_TABLE [2/2]
#define DECL_SIGNATURE_TABLE
Typedef Documentation
IntrinsicKind
using IntrinsicKind = sema::RISCVIntrinsicManager::IntrinsicKind
Definition at line 31 of file SemaRISCVVectorLookup.cpp.
Function Documentation
ProtoSeq2ArrayRef()
static ArrayRef< PrototypeDescriptor > ProtoSeq2ArrayRef (IntrinsicKind K, uint16_t Index, uint8_t Length) static
Definition at line 83 of file SemaRISCVVectorLookup.cpp.
References RVSiFiveVectorSignatureTable, and RVVSignatureTable.
RVVType2Qual()
static QualType RVVType2Qual (ASTContext & Context, const RVVType * Type) static
Definition at line 93 of file SemaRISCVVectorLookup.cpp.
References clang::ASTContext::BoolTy, clang::ASTContext::DoubleTy, clang::ASTContext::Float16Ty, clang::ASTContext::FloatTy, clang::ASTContext::getConstType(), clang::ASTContext::getIntTypeForBitwidth(), clang::ASTContext::getPointerDiffType(), clang::ASTContext::getPointerType(), clang::ASTContext::getScalableVectorType(), clang::ASTContext::getSizeType(), clang::RISCV::Invalid, clang::ASTContext::LongTy, clang::ASTContext::UnsignedLongTy, and clang::ASTContext::VoidTy.
Variable Documentation
RVSiFiveVectorIntrinsicRecords
const RVVIntrinsicRecord RVSiFiveVectorIntrinsicRecords[] static
Initial value:
= {
#define DECL_INTRINSIC_RECORDS
}
Definition at line 75 of file SemaRISCVVectorLookup.cpp.
RVSiFiveVectorSignatureTable
const PrototypeDescriptor RVSiFiveVectorSignatureTable[] static
Initial value:
= {
#define DECL_SIGNATURE_TABLE
}
Definition at line 63 of file SemaRISCVVectorLookup.cpp.
Referenced by ProtoSeq2ArrayRef().
RVVIntrinsicRecords
const RVVIntrinsicRecord RVVIntrinsicRecords[] static
Initial value:
= {
#define DECL_INTRINSIC_RECORDS
}
Definition at line 69 of file SemaRISCVVectorLookup.cpp.
RVVSignatureTable
const PrototypeDescriptor RVVSignatureTable[] static
Initial value:
= {
#define DECL_SIGNATURE_TABLE
}
Definition at line 57 of file SemaRISCVVectorLookup.cpp.
Referenced by ProtoSeq2ArrayRef().