clang: lib/Sema/SemaDeclAttr.cpp File Reference
SemaDeclAttr.cpp File Reference
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Type.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/DarwinSDKInfo.h"
#include "clang/Basic/HLSLRuntime.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ParsedAttr.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Assumptions.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
#include "clang/Basic/arm_mve_builtin_aliases.inc"
#include "clang/Basic/arm_cde_builtin_aliases.inc"
Namespaces
namespace AttributeLangSupport
Enumerations
enum AttributeLangSupport::LANG { AttributeLangSupport::C , AttributeLangSupport::Cpp , AttributeLangSupport::ObjC }
enum FormatAttrKind {
CFStringFormat , NSStringFormat , StrftimeFormat , SupportedFormat ,
IgnoredFormat , InvalidFormat
}
Functions
static bool isFunctionOrMethod (const Decl *D)
isFunctionOrMethod - Return true if the given decl has function type (function or function-typed variable) or an Objective-C method.
static bool isFunctionOrMethodOrBlock (const Decl *D)
Return true if the given decl has function type (function or function-typed variable) or an Objective-C method or a block.
static bool hasDeclarator (const Decl *D)
Return true if the given decl has a declarator that should have been processed by Sema::GetTypeForDeclarator.
static bool hasFunctionProto (const Decl *D)
hasFunctionProto - Return true if the given decl has a argument information.
static unsigned getFunctionOrMethodNumParams (const Decl *D)
getFunctionOrMethodNumParams - Return number of function or method parameters.
static const ParmVarDecl * getFunctionOrMethodParam (const Decl *D, unsigned Idx)
static QualType getFunctionOrMethodParamType (const Decl *D, unsigned Idx)
static SourceRange getFunctionOrMethodParamRange (const Decl *D, unsigned Idx)
static QualType getFunctionOrMethodResultType (const Decl *D)
static SourceRange getFunctionOrMethodResultSourceRange (const Decl *D)
static bool isFunctionOrMethodVariadic (const Decl *D)
static bool isInstanceMethod (const Decl *D)
static bool isNSStringType (QualType T, ASTContext &Ctx, bool AllowNSAttributedString=false)
static bool isCFStringType (QualType T, ASTContext &Ctx)
static unsigned getNumAttributeArgs (const ParsedAttr &AL)
template<typename AttrInfo >
static std::enable_if_t< std::is_base_of_v< Attr, AttrInfo >, SourceLocation > getAttrLoc (const AttrInfo &AL)
A helper function to provide Attribute Location for the Attr types AND the ParsedAttr.
static SourceLocation getAttrLoc (const ParsedAttr &AL)
template<typename AttrInfo >
static bool checkUInt32Argument (Sema &S, const AttrInfo &AI, const Expr *Expr, uint32_t &Val, unsigned Idx=UINT_MAX, bool StrictlyUnsigned=false)
If Expr is a valid integer constant, get the value of the integer expression and return success or failure.
template<typename AttrInfo >
static bool checkPositiveIntArgument (Sema &S, const AttrInfo &AI, const Expr *Expr, int &Val, unsigned Idx=UINT_MAX)
Wrapper around checkUInt32Argument, with an extra check to be sure that the result will fit into a regular (signed) int.
template<typename AttrTy >
static bool checkAttrMutualExclusion (Sema &S, Decl *D, const ParsedAttr &AL)
Diagnose mutually exclusive attributes when present on a given declaration.
template<typename AttrTy >
static bool checkAttrMutualExclusion (Sema &S, Decl *D, const Attr &AL)
template<typename AttrInfo >
static bool checkFunctionOrMethodParameterIndex (Sema &S, const Decl *D, const AttrInfo &AI, unsigned AttrArgNum, const Expr *IdxExpr, ParamIdx &Idx, bool CanIndexImplicitThis=false)
Check if IdxExpr is a valid parameter index for a function or instance method D.
template<typename AttrType >
static void handleSimpleAttribute (Sema &S, Decl *D, const AttributeCommonInfo &CI)
Applies the given attribute to the Decl without performing any additional semantic checking.
template<typename... DiagnosticArgs>
static const Sema::SemaDiagnosticBuilder & appendDiagnostics (const Sema::SemaDiagnosticBuilder &Bldr)
template<typename T , typename... DiagnosticArgs>
static const Sema::SemaDiagnosticBuilder & appendDiagnostics (const Sema::SemaDiagnosticBuilder &Bldr, T &&ExtraArg, DiagnosticArgs &&... ExtraArgs)
template<typename AttrType , typename... DiagnosticArgs>
static void handleSimpleAttributeOrDiagnose (Sema &S, Decl *D, const AttributeCommonInfo &CI, bool PassesCheck, unsigned DiagID, DiagnosticArgs &&... ExtraArgs)
Add an attribute AttrType to declaration D, provided that PassesCheck is true.
static bool isIntOrBool (Expr *Exp)
Check if the passed-in expression is of type int or bool.
static bool threadSafetyCheckIsSmartPointer (Sema &S, const RecordType *RT)
static bool threadSafetyCheckIsPointer (Sema &S, const Decl *D, const ParsedAttr &AL)
Check if passed in Decl is a pointer type.
static const RecordType * getRecordType (QualType QT)
Checks that the passed in QualType either is of RecordType or points to RecordType.
template<typename AttrType >
static bool checkRecordDeclForAttr (const RecordDecl *RD)
static bool checkRecordTypeForCapability (Sema &S, QualType Ty)
static bool checkTypedefTypeForCapability (QualType Ty)
static bool typeHasCapability (Sema &S, QualType Ty)
static bool isCapabilityExpr (Sema &S, const Expr *Ex)
static void checkAttrArgsAreCapabilityObjs (Sema &S, Decl *D, const ParsedAttr &AL, SmallVectorImpl< Expr * > &Args, unsigned Sidx=0, bool ParamIdxOk=false)
Checks that all attribute arguments, starting from Sidx, resolve to a capability object.
static void handlePtGuardedVarAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkGuardedByAttrCommon (Sema &S, Decl *D, const ParsedAttr &AL, Expr *&Arg)
static void handleGuardedByAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handlePtGuardedByAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkAcquireOrderAttrCommon (Sema &S, Decl *D, const ParsedAttr &AL, SmallVectorImpl< Expr * > &Args)
static void handleAcquiredAfterAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAcquiredBeforeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkLockFunAttrCommon (Sema &S, Decl *D, const ParsedAttr &AL, SmallVectorImpl< Expr * > &Args)
static void handleAssertSharedLockAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAssertExclusiveLockAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename AttrInfo >
static bool checkParamIsIntegerType (Sema &S, const Decl *D, const AttrInfo &AI, unsigned AttrArgNo)
Checks to be sure that the given parameter number is in bounds, and is an integral type.
static void handleAllocSizeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkTryLockFunAttrCommon (Sema &S, Decl *D, const ParsedAttr &AL, SmallVectorImpl< Expr * > &Args)
static void handleSharedTrylockFunctionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleExclusiveTrylockFunctionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleLockReturnedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleLocksExcludedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkFunctionConditionAttr (Sema &S, Decl *D, const ParsedAttr &AL, Expr *&Cond, StringRef &Msg)
static void handleEnableIfAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleErrorAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDiagnoseAsBuiltinAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDiagnoseIfAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoBuiltinAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handlePassObjectSizeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleConsumableAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkForConsumableClass (Sema &S, const CXXMethodDecl *MD, const ParsedAttr &AL)
static void handleCallableWhenAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleParamTypestateAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleReturnTypestateAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSetTypestateAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTestTypestateAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleExtVectorTypeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handlePackedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handlePreferredName (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkIBOutletCommon (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleIBOutlet (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleIBOutletCollection (Sema &S, Decl *D, const ParsedAttr &AL)
static bool attrNonNullArgCheck (Sema &S, QualType T, const ParsedAttr &AL, SourceRange AttrParmRange, SourceRange TypeRange, bool isReturnValue=false)
static void handleNonNullAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNonNullAttrParameter (Sema &S, ParmVarDecl *D, const ParsedAttr &AL)
static void handleReturnsNonNullAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoEscapeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAssumeAlignedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAllocAlignAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void checkAssumptionAttr (Sema &S, SourceLocation Loc, StringRef AssumptionStr)
Check if AssumptionStr is a known assumption and warn if not.
static void handleAssumumptionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool normalizeName (StringRef &AttrName)
Normalize the attribute, foo becomes foo.
static void handleOwnershipAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWeakRefAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleIFuncAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAliasAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTLSModelAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleRestrictAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCPUSpecificAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCommonAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCmseNSEntryAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNakedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoReturnAttr (Sema &S, Decl *D, const ParsedAttr &Attrs)
static void handleStandardNoReturnAttr (Sema &S, Decl *D, const ParsedAttr &A)
static void handleNoCfCheckAttr (Sema &S, Decl *D, const ParsedAttr &Attrs)
static void handleAnalyzerNoReturnAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleVecReturnAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDependencyAttr (Sema &S, Scope *Scope, Decl *D, const ParsedAttr &AL)
static void handleUnusedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleConstructorAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDestructorAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename AttrTy >
static void handleAttrWithMessage (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCSuppresProtocolAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkAvailabilityAttr (Sema &S, SourceRange Range, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted)
static bool versionsMatch (const VersionTuple &X, const VersionTuple &Y, bool BeforeIsOkay)
Check whether the two versions match.
static void handleAvailabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleExternalSourceSymbolAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<class T >
static T * mergeVisibilityAttr (Sema &S, Decl *D, const AttributeCommonInfo &CI, typename T::VisibilityType value)
static void handleVisibilityAttr (Sema &S, Decl *D, const ParsedAttr &AL, bool isTypeVisibility)
static void handleObjCDirectAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCDirectMembersAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCMethodFamilyAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCNSObject (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCIndependentClass (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleBlocksAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSentinelAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWarnUnusedResult (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWeakImportAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename WorkGroupAttr >
static void handleWorkGroupSize (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSubGroupSize (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleVecTypeHint (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSectionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkCodeSegName (Sema &S, SourceLocation LiteralLoc, StringRef CodeSegName)
static void handleCodeSegAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTargetVersionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTargetAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTargetClonesAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMinVectorWidthAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCleanupAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleEnumExtensibilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleFormatArgAttr (Sema &S, Decl *D, const ParsedAttr &AL)
Handle attribute((format_arg((idx)))) attribute based on http://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html.
static FormatAttrKind getFormatAttrKind (StringRef Format)
getFormatAttrKind - Map from format attribute names to supported format types.
static void handleInitPriorityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
Handle attribute((init_priority(priority))) attributes based on http://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Attributes.html.
static void handleFormatAttr (Sema &S, Decl *D, const ParsedAttr &AL)
Handle attribute((format(type,idx,firstarg))) attributes based on http://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html.
static void handleCallbackAttr (Sema &S, Decl *D, const ParsedAttr &AL)
Handle attribute((callback(CalleeIdx, PayloadIdx0, ...))) attributes.
static bool isFunctionLike (const Type &T)
static void handleCalledOnceAttr (Sema &S, Decl *D, const ParsedAttr &AL)
Handle 'called_once' attribute.
static void handleTransparentUnionAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAnnotateAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAlignValueAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAlignedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool validateAlignasAppliedType (Sema &S, Decl *D, const AlignedAttr &Attr, SourceLocation AttrLoc)
Perform checking of type validity.
static void parseModeAttrArg (Sema &S, StringRef Str, unsigned &DestWidth, bool &IntegerMode, bool &ComplexMode, FloatModeKind &ExplicitType)
parseModeAttrArg - Parses attribute mode string and returns parsed type attribute.
static void handleModeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
handleModeAttr - This attribute modifies the width of a decl with primitive type.
static void handleNoDebugAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAlwaysInlineAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMinSizeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleOptimizeNoneAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleConstantAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSharedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleGlobalAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDeviceAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleManagedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleGNUInlineAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCallConvAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSuppressAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleLifetimeCategoryAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleRandomizeLayoutAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoRandomizeLayoutAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool isValidSwiftContextType (QualType Ty)
Pointer-like types in the default address space.
static bool isValidSwiftIndirectResultType (QualType Ty)
Pointers and references in the default address space.
static bool isValidSwiftErrorResultType (QualType Ty)
Pointers and references to pointers in the default address space.
static Expr * makeLaunchBoundsArgExpr (Sema &S, Expr *E, const CUDALaunchBoundsAttr &AL, const unsigned Idx)
static void handleLaunchBoundsAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleArgumentWithTypeTagAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTypeTagForDatatypeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleXRayLogArgsAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handlePatchableFunctionEntryAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool ArmBuiltinAliasValid (unsigned BuiltinID, StringRef AliasName, ArrayRef< IntrinToName > Map, const char *IntrinNames)
static bool ArmMveAliasValid (unsigned BuiltinID, StringRef AliasName)
static bool ArmCdeAliasValid (unsigned BuiltinID, StringRef AliasName)
static bool ArmSveAliasValid (ASTContext &Context, unsigned BuiltinID, StringRef AliasName)
static bool ArmSmeAliasValid (ASTContext &Context, unsigned BuiltinID, StringRef AliasName)
static void handleArmBuiltinAliasAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool RISCVAliasValid (unsigned BuiltinID, StringRef AliasName)
static void handleBuiltinAliasAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool isValidSubjectOfNSReturnsRetainedAttribute (QualType QT)
static bool isValidSubjectOfNSAttribute (QualType QT)
static bool isValidSubjectOfCFAttribute (QualType QT)
static bool isValidSubjectOfOSAttribute (QualType QT)
static Sema::RetainOwnershipKind parsedAttrToRetainOwnershipKind (const ParsedAttr &AL)
static bool isValidOSObjectOutParameter (const Decl *D)
static void handleXReturnsXRetainedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCReturnsInnerPointerAttr (Sema &S, Decl *D, const ParsedAttr &Attrs)
static void handleObjCRequiresSuperAttr (Sema &S, Decl *D, const ParsedAttr &Attrs)
static void handleNSErrorDomain (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCBridgeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCBridgeMutableAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCBridgeRelatedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCDesignatedInitializer (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCRuntimeName (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCBoxable (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCOwnershipAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleObjCPreciseLifetimeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSwiftAttrAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSwiftBridge (Sema &S, Decl *D, const ParsedAttr &AL)
static bool isErrorParameter (Sema &S, QualType QT)
static void handleSwiftError (Sema &S, Decl *D, const ParsedAttr &AL)
static void checkSwiftAsyncErrorBlock (Sema &S, Decl *D, const SwiftAsyncErrorAttr *ErrorAttr, const SwiftAsyncAttr *AsyncAttr)
static void handleSwiftAsyncError (Sema &S, Decl *D, const ParsedAttr &AL)
static bool validateSwiftFunctionName (Sema &S, const ParsedAttr &AL, SourceLocation Loc, StringRef Name, unsigned &SwiftParamCount, bool &IsSingleParamInit)
static void handleSwiftName (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSwiftAsyncName (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSwiftNewType (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSwiftAsyncAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleUuidAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleHLSLNumThreadsAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleHLSLSVGroupIndexAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool isLegalTypeForHLSLSV_DispatchThreadID (QualType T)
static void handleHLSLSV_DispatchThreadIDAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleHLSLShaderAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleHLSLResourceBindingAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMSInheritanceAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDeclspecThreadAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAbiTagAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleARMInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMSP430InterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMipsInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleM68kInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAnyX86InterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAVRInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAVRSignalAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleBPFPreserveAIRecord (Sema &S, RecordDecl *RD)
static void handleBPFPreserveAccessIndexAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool hasBTFDeclTagAttr (Decl *D, StringRef Tag)
static void handleBTFDeclTagAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWebAssemblyExportNameAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWebAssemblyImportModuleAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleWebAssemblyImportNameAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleRISCVInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleInterruptAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkAMDGPUFlatWorkGroupSizeArguments (Sema &S, Expr *MinExpr, Expr *MaxExpr, const AMDGPUFlatWorkGroupSizeAttr &Attr)
static void handleAMDGPUFlatWorkGroupSizeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool checkAMDGPUWavesPerEUArguments (Sema &S, Expr *MinExpr, Expr *MaxExpr, const AMDGPUWavesPerEUAttr &Attr)
static void handleAMDGPUWavesPerEUAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAMDGPUNumSGPRAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAMDGPUNumVGPRAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleX86ForceAlignArgPointerAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleLayoutVersion (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDLLAttr (Sema &S, Decl *D, const ParsedAttr &A)
static void handleCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAssertCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAcquireCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleTryAcquireCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleReleaseCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleRequiresCapabilityAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDeprecatedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool isGlobalVar (const Decl *D)
static bool isSanitizerAttributeAllowedOnGlobals (StringRef Sanitizer)
static void handleNoSanitizeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoSanitizeSpecificAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleInternalLinkageAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleOpenCLNoSVMAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleOpenCLAccessAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleZeroCallUsedRegsAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleFunctionReturnThunksAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAvailableOnlyInDefaultEvalMethod (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleNoMergeAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleSYCLKernelAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleDestroyAttr (Sema &S, Decl *D, const ParsedAttr &A)
static void handleUninitializedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static bool tryMakeVariablePseudoStrong (Sema &S, VarDecl *VD, bool DiagnoseFailure)
static void handleObjCExternallyRetainedAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMIGServerRoutineAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleMSAllocatorAttr (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleAcquireHandleAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename Attr >
static void handleHandleAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename Attr >
static void handleUnsafeBufferUsage (Sema &S, Decl *D, const ParsedAttr &AL)
static void handleCFGuardAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename AttrTy >
static const AttrTy * findEnforceTCBAttrByName (Decl *D, StringRef Name)
template<typename AttrTy , typename ConflictingAttrTy >
static void handleEnforceTCBAttr (Sema &S, Decl *D, const ParsedAttr &AL)
template<typename AttrTy , typename ConflictingAttrTy >
static AttrTy * mergeEnforceTCBAttrImpl (Sema &S, Decl *D, const AttrTy &AL)
static bool MustDelayAttributeArguments (const ParsedAttr &AL)
static void ProcessDeclAttribute (Sema &S, Scope *scope, Decl *D, const ParsedAttr &AL, const Sema::ProcessDeclAttributeOptions &Options)
ProcessDeclAttribute - Apply the specific attribute to the specified decl if the attribute applies to decls.
static void checkUnusedDeclAttributes (Sema &S, const ParsedAttributesView &A)
checkUnusedDeclAttributes - Check a list of attributes to see if it contains any decl attributes that we should warn about.
static bool isForbiddenTypeAllowed (Sema &S, Decl *D, const DelayedDiagnostic &diag, UnavailableAttr::ImplicitReason &reason)
Is the given declaration allowed to use a forbidden type? If so, it'll still be annotated with an attribute that makes it illegal to actually use.
static void handleDelayedForbiddenType (Sema &S, DelayedDiagnostic &DD, Decl *D)
Handle a delayed forbidden-type diagnostic.
Enumeration Type Documentation
FormatAttrKind
enum FormatAttrKind
Enumerator
CFStringFormat
NSStringFormat
StrftimeFormat
SupportedFormat
IgnoredFormat
InvalidFormat
Definition at line 3811 of file SemaDeclAttr.cpp.
Function Documentation
appendDiagnostics() [1/2]
template<typename... DiagnosticArgs> static const Sema::SemaDiagnosticBuilder & appendDiagnostics (const Sema::SemaDiagnosticBuilder & Bldr) static
Definition at line 397 of file SemaDeclAttr.cpp.
Referenced by appendDiagnostics(), and handleSimpleAttributeOrDiagnose().
appendDiagnostics() [2/2]
template<typename T , typename... DiagnosticArgs> static const Sema::SemaDiagnosticBuilder & appendDiagnostics (const Sema::SemaDiagnosticBuilder & Bldr, T && ExtraArg, DiagnosticArgs &&... ExtraArgs) static
Definition at line 403 of file SemaDeclAttr.cpp.
References appendDiagnostics().
ArmBuiltinAliasValid()
static bool ArmBuiltinAliasValid (unsigned BuiltinID, StringRef AliasName, ArrayRef< IntrinToName > Map, const char * IntrinNames) static
Definition at line 5760 of file SemaDeclAttr.cpp.
References Id.
Referenced by ArmCdeAliasValid(), and ArmMveAliasValid().
ArmCdeAliasValid()
static bool ArmCdeAliasValid (unsigned BuiltinID, StringRef AliasName) static
Definition at line 5788 of file SemaDeclAttr.cpp.
References ArmBuiltinAliasValid().
Referenced by handleArmBuiltinAliasAttr(), and handleBuiltinAliasAttr().
ArmMveAliasValid()
static bool ArmMveAliasValid (unsigned BuiltinID, StringRef AliasName) static
Definition at line 5780 of file SemaDeclAttr.cpp.
References ArmBuiltinAliasValid().
Referenced by handleArmBuiltinAliasAttr(), and handleBuiltinAliasAttr().
ArmSmeAliasValid()
static bool ArmSmeAliasValid (ASTContext & Context, unsigned BuiltinID, StringRef AliasName) static
Definition at line 5801 of file SemaDeclAttr.cpp.
References clang::ASTContext::BuiltinInfo, clang::AArch64::FirstSMEBuiltin, clang::Builtin::Context::getAuxBuiltinID(), clang::Builtin::Context::isAuxBuiltinID(), and clang::AArch64::LastSMEBuiltin.
Referenced by handleArmBuiltinAliasAttr().
ArmSveAliasValid()
static bool ArmSveAliasValid (ASTContext & Context, unsigned BuiltinID, StringRef AliasName) static
Definition at line 5793 of file SemaDeclAttr.cpp.
References clang::ASTContext::BuiltinInfo, clang::AArch64::FirstSVEBuiltin, clang::Builtin::Context::getAuxBuiltinID(), clang::Builtin::Context::isAuxBuiltinID(), and clang::AArch64::LastSVEBuiltin.
Referenced by handleArmBuiltinAliasAttr(), and handleBuiltinAliasAttr().
attrNonNullArgCheck()
static bool attrNonNullArgCheck (Sema & S, QualType T, const ParsedAttr & AL, SourceRange AttrParmRange, SourceRange TypeRange, bool isReturnValue = false) static
Definition at line 1567 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::Sema::isValidPointerAttrType().
Referenced by handleNonNullAttr(), handleNonNullAttrParameter(), and handleReturnsNonNullAttr().
checkAcquireOrderAttrCommon()
static bool checkAcquireOrderAttrCommon (Sema & S, Decl * D, const ParsedAttr & AL, SmallVectorImpl< Expr * > & Args) static
Definition at line 729 of file SemaDeclAttr.cpp.
References clang::cast(), clang::ParsedAttr::checkAtLeastNumArgs(), checkAttrArgsAreCapabilityObjs(), clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::Type::isDependentType(), and typeHasCapability().
Referenced by handleAcquiredAfterAttr(), and handleAcquiredBeforeAttr().
checkAMDGPUFlatWorkGroupSizeArguments()
static bool checkAMDGPUFlatWorkGroupSizeArguments (Sema & S, Expr * MinExpr, Expr * MaxExpr, const AMDGPUFlatWorkGroupSizeAttr & Attr) static
Definition at line 7836 of file SemaDeclAttr.cpp.
References checkUInt32Argument(), clang::Sema::Diag(), clang::Attr::getLocation(), and clang::Expr::isValueDependent().
Referenced by clang::Sema::addAMDGPUFlatWorkGroupSizeAttr().
checkAMDGPUWavesPerEUArguments()
static bool checkAMDGPUWavesPerEUArguments (Sema & S, Expr * MinExpr, Expr * MaxExpr, const AMDGPUWavesPerEUAttr & Attr) static
Definition at line 7885 of file SemaDeclAttr.cpp.
References checkUInt32Argument(), clang::Sema::Diag(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::Attr::getLocation(), and clang::Expr::isValueDependent().
Referenced by clang::Sema::addAMDGPUWavesPerEUAttr().
checkAssumptionAttr()
static void checkAssumptionAttr (Sema & S, SourceLocation Loc, StringRef AssumptionStr) static
Check if AssumptionStr is a known assumption and warn if not.
Definition at line 1763 of file SemaDeclAttr.cpp.
References clang::Sema::Diag().
Referenced by handleAssumumptionAttr().
checkAttrArgsAreCapabilityObjs()
static void checkAttrArgsAreCapabilityObjs (Sema & S, Decl * D, const ParsedAttr & AL, SmallVectorImpl< Expr * > & Args, unsigned Sidx = 0, bool ParamIdxOk = false) static
Checks that all attribute arguments, starting from Sidx, resolve to a capability object.
Parameters
Sidx The attribute argument index to start checking with.
ParamIdxOk Whether an argument can be indexing into a function parameter list.
Definition at line 592 of file SemaDeclAttr.cpp.
References checkRecordDeclForAttr(), clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::DeclContext::getParent(), getRecordType(), clang::Expr::getType(), isCapabilityExpr(), clang::Expr::isTypeDependent(), and typeHasCapability().
Referenced by checkAcquireOrderAttrCommon(), checkGuardedByAttrCommon(), checkLockFunAttrCommon(), checkTryLockFunAttrCommon(), handleLockReturnedAttr(), handleLocksExcludedAttr(), handleReleaseCapabilityAttr(), and handleRequiresCapabilityAttr().
checkAttrMutualExclusion() [1/2]
template<typename AttrTy > static bool checkAttrMutualExclusion (Sema & S, Decl * D, const Attr & AL) static
Definition at line 286 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Decl::getAttr(), clang::Attr::getLocation(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
checkAttrMutualExclusion() [2/2]
template<typename AttrTy > static bool checkAttrMutualExclusion (Sema & S, Decl * D, const ParsedAttr & AL) static
Diagnose mutually exclusive attributes when present on a given declaration.
Returns true if diagnosed.
Definition at line 274 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by handleCPUSpecificAttr(), handleLifetimeCategoryAttr(), handleMipsInterruptAttr(), handleNoRandomizeLayoutAttr(), handleRandomizeLayoutAttr(), and handleTargetClonesAttr().
checkAvailabilityAttr()
static bool checkAvailabilityAttr (Sema & S, SourceRange Range, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted) static
Definition at line 2383 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), and clang::IdentifierInfo::getName().
Referenced by clang::Sema::mergeAvailabilityAttr().
checkCodeSegName()
static bool checkCodeSegName (Sema & S, SourceLocation LiteralLoc, StringRef CodeSegName) static
Definition at line 3358 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Sema::isValidSectionSpecifier(), and toString().
Referenced by handleCodeSegAttr().
checkForConsumableClass()
static bool checkForConsumableClass (Sema & S, const CXXMethodDecl * MD, const ParsedAttr & AL) static
Definition at line 1224 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Type::getAsCXXRecordDecl(), clang::AttributeCommonInfo::getLoc(), clang::Type::getPointeeType(), and clang::CXXMethodDecl::getThisType().
Referenced by handleCallableWhenAttr(), handleSetTypestateAttr(), and handleTestTypestateAttr().
checkFunctionConditionAttr()
static bool checkFunctionConditionAttr (Sema & S, Decl * D, const ParsedAttr & AL, Expr *& Cond, StringRef & Msg) static
Definition at line 927 of file SemaDeclAttr.cpp.
References clang::Sema::checkStringLiteralArgumentAttr(), clang::Cond, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ParsedAttr::getArgAsExpr(), clang::AttributeCommonInfo::getLoc(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Expr::isPotentialConstantExprUnevaluated(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::Sema::PerformContextuallyConvertToBool().
Referenced by handleDiagnoseIfAttr(), and handleEnableIfAttr().
checkFunctionOrMethodParameterIndex()
template<typename AttrInfo > static bool checkFunctionOrMethodParameterIndex (Sema & S, const Decl * D, const AttrInfo & AI, unsigned AttrArgNum, const Expr * IdxExpr, ParamIdx & Idx, bool CanIndexImplicitThis = false) static
Check if IdxExpr is a valid parameter index for a function or instance method D.
May output an error.
Returns
true if IdxExpr is a valid index.
Definition at line 302 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Sema::Context, clang::Sema::Diag(), getAttrLoc(), getFunctionOrMethodNumParams(), clang::Expr::getIntegerConstantExpr(), clang::Stmt::getSourceRange(), hasFunctionProto(), isFunctionOrMethodOrBlock(), isFunctionOrMethodVariadic(), isInstanceMethod(), clang::Expr::isTypeDependent(), and UINT_MAX.
Referenced by clang::Sema::AddAllocAlignAttr(), checkParamIsIntegerType(), handleArgumentWithTypeTagAttr(), handleFormatArgAttr(), handleNonNullAttr(), handleOwnershipAttr(), handleSwiftAsyncAttr(), and handleXRayLogArgsAttr().
checkGuardedByAttrCommon()
static bool checkGuardedByAttrCommon (Sema & S, Decl * D, const ParsedAttr & AL, Expr *& Arg) static
Definition at line 696 of file SemaDeclAttr.cpp.
References checkAttrArgsAreCapabilityObjs().
Referenced by handleGuardedByAttr(), and handlePtGuardedByAttr().
checkIBOutletCommon()
static bool checkIBOutletCommon (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1467 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), and clang::AttributeCommonInfo::getLoc().
Referenced by handleIBOutlet(), and handleIBOutletCollection().
checkLockFunAttrCommon()
static bool checkLockFunAttrCommon (Sema & S, Decl * D, const ParsedAttr & AL, SmallVectorImpl< Expr * > & Args) static
Definition at line 769 of file SemaDeclAttr.cpp.
References checkAttrArgsAreCapabilityObjs().
Referenced by handleAcquireCapabilityAttr(), handleAssertCapabilityAttr(), handleAssertExclusiveLockAttr(), and handleAssertSharedLockAttr().
checkParamIsIntegerType()
template<typename AttrInfo > static bool checkParamIsIntegerType (Sema & S, const Decl * D, const AttrInfo & AI, unsigned AttrArgNo) static
Checks to be sure that the given parameter number is in bounds, and is an integral type.
Will emit appropriate diagnostics if this returns false.
AttrArgNo is used to actually retrieve the argument, so it's base-0.
Definition at line 807 of file SemaDeclAttr.cpp.
References checkFunctionOrMethodParameterIndex(), clang::Sema::Diag(), clang::ParamIdx::getASTIndex(), clang::Stmt::getBeginLoc(), getFunctionOrMethodParamRange(), getFunctionOrMethodParamType(), clang::Type::isCharType(), and clang::Type::isIntegerType().
Referenced by handleAllocSizeAttr().
checkPositiveIntArgument()
template<typename AttrInfo > static bool checkPositiveIntArgument (Sema & S, const AttrInfo & AI, const Expr * Expr, int & Val, unsigned Idx = UINT_MAX) static
Wrapper around checkUInt32Argument, with an extra check to be sure that the result will fit into a regular (signed) int.
All args have the same purpose as they do in checkUInt32Argument.
Definition at line 253 of file SemaDeclAttr.cpp.
References checkUInt32Argument(), clang::Sema::Diag(), clang::Expr::getExprLoc(), and toString().
Referenced by handleAllocSizeAttr().
checkRecordDeclForAttr()
template<typename AttrType > static bool checkRecordDeclForAttr (const RecordDecl * RD) static
Definition at line 507 of file SemaDeclAttr.cpp.
References clang::Decl::hasAttr().
Referenced by checkAttrArgsAreCapabilityObjs(), and checkRecordTypeForCapability().
checkRecordTypeForCapability()
static bool checkRecordTypeForCapability (Sema & S, QualType Ty) static
Definition at line 522 of file SemaDeclAttr.cpp.
References checkRecordDeclForAttr(), getRecordType(), and threadSafetyCheckIsSmartPointer().
Referenced by typeHasCapability().
checkSwiftAsyncErrorBlock()
static void checkSwiftAsyncErrorBlock (Sema & S, Decl * D, const SwiftAsyncErrorAttr * ErrorAttr, const SwiftAsyncAttr * AsyncAttr) static
Definition at line 6456 of file SemaDeclAttr.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), getFunctionOrMethodParam(), clang::Sema::getNSErrorIdent(), clang::ValueDecl::getType(), clang::Sema::isCFError(), and clang::Type::isIntegralType().
Referenced by handleSwiftAsyncAttr(), and handleSwiftAsyncError().
checkTryLockFunAttrCommon()
static bool checkTryLockFunAttrCommon (Sema & S, Decl * D, const ParsedAttr & AL, SmallVectorImpl< Expr * > & Args) static
Definition at line 863 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntOrBool, clang::ParsedAttr::checkAtLeastNumArgs(), checkAttrArgsAreCapabilityObjs(), clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::AttributeCommonInfo::getLoc(), and isIntOrBool().
Referenced by handleExclusiveTrylockFunctionAttr(), handleSharedTrylockFunctionAttr(), and handleTryAcquireCapabilityAttr().
checkTypedefTypeForCapability()
static bool checkTypedefTypeForCapability (QualType Ty) static
Definition at line 540 of file SemaDeclAttr.cpp.
References clang::Type::getAs(), and clang::Decl::hasAttr().
Referenced by typeHasCapability().
checkUInt32Argument()
template<typename AttrInfo > static bool checkUInt32Argument (Sema & S, const AttrInfo & AI, const Expr * Expr, uint32_t & Val, unsigned Idx = UINT_MAX, bool StrictlyUnsigned = false) static
If Expr is a valid integer constant, get the value of the integer expression and return success or failure.
May output an error.
Negative argument is implicitly converted to unsigned, unless StrictlyUnsigned is true.
Definition at line 217 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Sema::Context, clang::Sema::Diag(), getAttrLoc(), clang::Expr::getExprLoc(), clang::Expr::getIntegerConstantExpr(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), toString(), and UINT_MAX.
Referenced by checkAMDGPUFlatWorkGroupSizeArguments(), checkAMDGPUWavesPerEUArguments(), checkPositiveIntArgument(), clang::Sema::CheckRegparmAttr(), handleAMDGPUNumSGPRAttr(), handleAMDGPUNumVGPRAttr(), handleCallbackAttr(), handleConstructorAttr(), handleDestructorAttr(), handleDiagnoseAsBuiltinAttr(), handleFormatAttr(), handleHLSLNumThreadsAttr(), handleInitPriorityAttr(), handleLayoutVersion(), handleMinVectorWidthAttr(), handlePassObjectSizeAttr(), handlePatchableFunctionEntryAttr(), handleSubGroupSize(), handleSwiftAsyncError(), and handleWorkGroupSize().
checkUnusedDeclAttributes()
static void checkUnusedDeclAttributes (Sema & S, const ParsedAttributesView & A) static
checkUnusedDeclAttributes - Check a list of attributes to see if it contains any decl attributes that we should warn about.
Definition at line 9608 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::AttributeCommonInfo::IgnoredAttribute, and clang::AttributeCommonInfo::UnknownAttribute.
findEnforceTCBAttrByName()
template<typename AttrTy > static const AttrTy * findEnforceTCBAttrByName (Decl * D, StringRef Name) static
Definition at line 8608 of file SemaDeclAttr.cpp.
References clang::Decl::specific_attrs().
Referenced by handleEnforceTCBAttr(), and mergeEnforceTCBAttrImpl().
getAttrLoc() [1/2]
template<typename AttrInfo > static std::enable_if_t< std::is_base_of_v< Attr, AttrInfo >, SourceLocation > getAttrLoc (const AttrInfo & AL) static
A helper function to provide Attribute Location for the Attr types AND the ParsedAttr.
Definition at line 206 of file SemaDeclAttr.cpp.
Referenced by checkFunctionOrMethodParameterIndex(), checkUInt32Argument(), and handlePatchableFunctionEntryAttr().
getAttrLoc() [2/2]
static SourceLocation getAttrLoc (const ParsedAttr & AL) static
Definition at line 209 of file SemaDeclAttr.cpp.
References clang::AttributeCommonInfo::getLoc().
getFormatAttrKind()
static FormatAttrKind getFormatAttrKind (StringRef Format) static
getFormatAttrKind - Map from format attribute names to supported format types.
Definition at line 3822 of file SemaDeclAttr.cpp.
References CFStringFormat, IgnoredFormat, InvalidFormat, NSStringFormat, StrftimeFormat, and SupportedFormat.
Referenced by handleFormatAttr().
getFunctionOrMethodNumParams()
static unsigned getFunctionOrMethodNumParams (const Decl * D) static
getFunctionOrMethodNumParams - Return number of function or method parameters.
It is an error to call this on a K&R function (use hasFunctionProto first).
Definition at line 99 of file SemaDeclAttr.cpp.
References clang::cast(), and clang::Decl::getFunctionType().
Referenced by checkFunctionOrMethodParameterIndex(), handleAnyX86InterruptAttr(), handleArgumentWithTypeTagAttr(), handleCallbackAttr(), handleFormatAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), handleNonNullAttr(), handleObjCExternallyRetainedAttr(), handleRISCVInterruptAttr(), handleSwiftError(), and handleSYCLKernelAttr().
getFunctionOrMethodParam()
static const ParmVarDecl * getFunctionOrMethodParam (const Decl * D, unsigned Idx) static
Definition at line 107 of file SemaDeclAttr.cpp.
Referenced by checkSwiftAsyncErrorBlock(), getFunctionOrMethodParamRange(), handleObjCExternallyRetainedAttr(), and handleSwiftAsyncAttr().
getFunctionOrMethodParamRange()
static SourceRange getFunctionOrMethodParamRange (const Decl * D, unsigned Idx) static
Definition at line 127 of file SemaDeclAttr.cpp.
References getFunctionOrMethodParam().
Referenced by checkParamIsIntegerType(), handleAnyX86InterruptAttr(), handleFormatArgAttr(), handleFormatAttr(), and handleNonNullAttr().
getFunctionOrMethodParamType()
static QualType getFunctionOrMethodParamType (const Decl * D, unsigned Idx) static
Definition at line 118 of file SemaDeclAttr.cpp.
References clang::cast(), and clang::Decl::getFunctionType().
Referenced by clang::Sema::AddAllocAlignAttr(), checkParamIsIntegerType(), handleAnyX86InterruptAttr(), handleArgumentWithTypeTagAttr(), handleCallbackAttr(), handleFormatArgAttr(), handleFormatAttr(), handleNonNullAttr(), handleOwnershipAttr(), and handleSwiftError().
getFunctionOrMethodResultSourceRange()
static SourceRange getFunctionOrMethodResultSourceRange (const Decl * D) static
Definition at line 139 of file SemaDeclAttr.cpp.
Referenced by clang::Sema::AddAllocAlignAttr(), clang::Sema::AddAssumeAlignedAttr(), handleAnyX86InterruptAttr(), handleRestrictAttr(), and handleReturnsNonNullAttr().
getFunctionOrMethodResultType()
static QualType getFunctionOrMethodResultType (const Decl * D) static
Definition at line 133 of file SemaDeclAttr.cpp.
References clang::cast(), and clang::Decl::getFunctionType().
Referenced by clang::Sema::AddAllocAlignAttr(), clang::Sema::AddAssumeAlignedAttr(), handleAllocSizeAttr(), handleAnyX86InterruptAttr(), handleFormatArgAttr(), handleMIGServerRoutineAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), handleRestrictAttr(), handleReturnsNonNullAttr(), handleRISCVInterruptAttr(), handleSwiftError(), and handleSYCLKernelAttr().
getNumAttributeArgs()
static unsigned getNumAttributeArgs (const ParsedAttr & AL) static
Definition at line 197 of file SemaDeclAttr.cpp.
References clang::ParsedAttr::getNumArgs(), and clang::ParsedAttr::hasParsedType().
getRecordType()
static const RecordType * getRecordType (QualType QT) static
Checks that the passed in QualType either is of RecordType or points to RecordType.
Returns the relevant RecordType, null if it does not exit.
Definition at line 495 of file SemaDeclAttr.cpp.
References clang::Type::getAs(), and clang::Type::getPointeeType().
Referenced by checkAttrArgsAreCapabilityObjs(), checkRecordTypeForCapability(), and clang::CodeGen::CodeGenModule::EmitTopLevelDecl().
handleAbiTagAttr()
static void handleAbiTagAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7319 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleAcquireCapabilityAttr()
static void handleAcquireCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8122 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkLockFunAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAcquiredAfterAttr()
static void handleAcquiredAfterAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 749 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAcquireOrderAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAcquiredBeforeAttr()
static void handleAcquiredBeforeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 759 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAcquireOrderAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAcquireHandleAttr()
static void handleAcquireHandleAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8557 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), and clang::ParsedAttr::isUsedAsTypeAttr().
Referenced by ProcessDeclAttribute().
handleAliasAttr()
static void handleAliasAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1986 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Sema::getCurLexicalContext(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ASTContext::Idents, clang::FunctionDecl::isThisDeclarationADefinition(), clang::Sema::LangOpts, clang::Sema::LookupOrdinaryName, and clang::Sema::LookupQualifiedName().
Referenced by ProcessDeclAttribute().
handleAlignedAttr()
static void handleAlignedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4348 of file SemaDeclAttr.cpp.
References clang::Sema::AddAlignedAttr(), clang::Decl::addAttr(), clang::Expr::containsUnexpandedParameterPack(), clang::Type::containsUnexpandedParameterPack(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::ParsedAttr::getArgAsExpr(), clang::OpaquePtr< PtrTy >::getAsOpaquePtr(), clang::TypeLoc::getBeginLoc(), clang::ParsedAttr::getEllipsisLoc(), clang::OpaquePtr< QualType >::getFromOpaquePtr(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::TypeSourceInfo::getType(), clang::ParsedAttr::getTypeArg(), clang::Sema::GetTypeFromParser(), clang::TypeSourceInfo::getTypeLoc(), clang::ParsedAttr::hasParsedType(), clang::ParsedAttr::isPackExpansion(), and clang::Sema::UPPC_Expression.
Referenced by ProcessDeclAttribute().
handleAlignValueAttr()
static void handleAlignValueAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4304 of file SemaDeclAttr.cpp.
References clang::Sema::AddAlignValueAttr(), and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleAllocAlignAttr()
static void handleAllocAlignAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1677 of file SemaDeclAttr.cpp.
References clang::Sema::AddAllocAlignAttr(), and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleAllocSizeAttr()
static void handleAllocSizeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 826 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), checkParamIsIntegerType(), checkPositiveIntArgument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), hasFunctionProto(), isFunctionOrMethod(), and clang::Type::isPointerType().
Referenced by ProcessDeclAttribute().
handleAlwaysInlineAttr()
static void handleAlwaysInlineAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4988 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::AttributeCommonInfo::getAttrName(), and clang::Sema::mergeAlwaysInlineAttr().
Referenced by ProcessDeclAttribute(), and ProcessStmtAttribute().
handleAMDGPUFlatWorkGroupSizeAttr()
static void handleAMDGPUFlatWorkGroupSizeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7877 of file SemaDeclAttr.cpp.
References clang::Sema::addAMDGPUFlatWorkGroupSizeAttr(), and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleAMDGPUNumSGPRAttr()
static void handleAMDGPUNumSGPRAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7940 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleAMDGPUNumVGPRAttr()
static void handleAMDGPUNumVGPRAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7949 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleAMDGPUWavesPerEUAttr()
static void handleAMDGPUWavesPerEUAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7930 of file SemaDeclAttr.cpp.
References clang::Sema::addAMDGPUWavesPerEUAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleAnalyzerNoReturnAttr()
static void handleAnalyzerNoReturnAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2239 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionMethodOrBlock, clang::AttributeCommonInfo::getLoc(), clang::ValueDecl::getType(), clang::Type::isBlockPointerType(), isFunctionOrMethodOrBlock(), clang::Type::isFunctionPointerType(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::AttributeCommonInfo::isStandardAttributeSyntax().
Referenced by ProcessDeclAttribute().
handleAnnotateAttr()
static void handleAnnotateAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4287 of file SemaDeclAttr.cpp.
References clang::Sema::AddAnnotationAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getNumArgs(), and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleAnyX86InterruptAttr()
static void handleAnyX86InterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7517 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionWithProtoType, clang::Decl::getBeginLoc(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamRange(), getFunctionOrMethodParamType(), getFunctionOrMethodResultSourceRange(), getFunctionOrMethodResultType(), clang::ASTContext::getIntTypeForBitwidth(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ASTContext::getTypeSize(), hasFunctionProto(), isFunctionOrMethod(), isInstanceMethod(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::CXXMethodDecl::isStaticOverloadedOperator().
Referenced by handleInterruptAttr().
handleArgumentWithTypeTagAttr()
static void handleArgumentWithTypeTagAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5661 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), checkFunctionOrMethodParameterIndex(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::ParamIdx::getASTIndex(), clang::AttributeCommonInfo::getAttrName(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamType(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleArmBuiltinAliasAttr()
static void handleArmBuiltinAliasAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5809 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), ArmCdeAliasValid(), ArmMveAliasValid(), ArmSmeAliasValid(), ArmSveAliasValid(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::IdentifierInfo::getBuiltinID(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleARMInterruptAttr()
static void handleARMInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7350 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::ParsedAttr::getNumArgs().
Referenced by handleInterruptAttr().
handleAssertCapabilityAttr()
static void handleAssertCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8113 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkLockFunAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAssertExclusiveLockAttr()
static void handleAssertExclusiveLockAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 789 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkLockFunAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAssertSharedLockAttr()
static void handleAssertSharedLockAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 778 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkLockFunAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAssumeAlignedAttr()
static void handleAssumeAlignedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1671 of file SemaDeclAttr.cpp.
References clang::Sema::AddAssumeAlignedAttr(), clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleAssumumptionAttr()
static void handleAssumumptionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1786 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAssumptionAttr(), clang::Sema::checkStringLiteralArgumentAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleAttrWithMessage()
template<typename AttrTy > static void handleAttrWithMessage (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2363 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleAvailabilityAttr()
static void handleAvailabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2604 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::AMK_None, clang::Sema::AP_Explicit, clang::Sema::AP_InferredFromOtherPlatform, clang::Sema::AP_PragmaClangAttribute, clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::ParsedAttr::getArgAsIdent(), clang::ParsedAttr::getAvailabilityDeprecated(), clang::ParsedAttr::getAvailabilityIntroduced(), clang::ParsedAttr::getAvailabilityObsoleted(), clang::SourceRange::getBegin(), clang::Sema::getDarwinSDKInfoForAvailabilityChecking(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getMessageExpr(), clang::IdentifierInfo::getName(), clang::AttributeCommonInfo::getRange(), clang::ParsedAttr::getReplacementExpr(), clang::ParsedAttr::getStrictLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ParsedAttr::getUnavailableLoc(), clang::DarwinSDKInfo::getVersionMapping(), clang::IdentifierLoc::Ident, clang::ASTContext::Idents, clang::DarwinSDKInfo::OSEnvPair::iOStoTvOSPair(), clang::DarwinSDKInfo::OSEnvPair::iOStoWatchOSPair(), clang::ParsedAttr::isPragmaClangAttribute(), clang::IdentifierInfo::isStr(), clang::AvailabilityChange::isValid(), clang::SourceLocation::isValid(), clang::IdentifierLoc::Loc, clang::DarwinSDKInfo::OSEnvPair::macOStoMacCatalystPair(), clang::Sema::mergeAvailabilityAttr(), V, and clang::AvailabilityChange::Version.
Referenced by ProcessDeclAttribute().
handleAvailableOnlyInDefaultEvalMethod()
static void handleAvailableOnlyInDefaultEvalMethod (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8372 of file SemaDeclAttr.cpp.
References handleSimpleAttribute().
Referenced by ProcessDeclAttribute().
handleAVRInterruptAttr()
static void handleAVRInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7582 of file SemaDeclAttr.cpp.
References clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Diag(), clang::ExpectedFunction, clang::Decl::getLocation(), handleSimpleAttribute(), isFunctionOrMethod(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by handleInterruptAttr().
handleAVRSignalAttr()
static void handleAVRSignalAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7595 of file SemaDeclAttr.cpp.
References clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Diag(), clang::ExpectedFunction, clang::Decl::getLocation(), handleSimpleAttribute(), isFunctionOrMethod(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleBlocksAttr()
static void handleBlocksAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3030 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::ast_matchers::type.
Referenced by ProcessDeclAttribute().
handleBPFPreserveAccessIndexAttr()
static void handleBPFPreserveAccessIndexAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7620 of file SemaDeclAttr.cpp.
References clang::cast(), clang::Sema::Context, and handleBPFPreserveAIRecord().
Referenced by ProcessDeclAttribute().
handleBPFPreserveAIRecord()
static void handleBPFPreserveAIRecord (Sema & S, RecordDecl * RD) static
Definition at line 7608 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::DeclContext::decls(), and handleBPFPreserveAIRecord().
Referenced by handleBPFPreserveAccessIndexAttr(), handleBPFPreserveAIRecord(), and clang::Sema::ProcessDeclAttributeDelayed().
handleBTFDeclTagAttr()
static void handleBTFDeclTagAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7635 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and hasBTFDeclTagAttr().
Referenced by ProcessDeclAttribute().
handleBuiltinAliasAttr()
static void handleBuiltinAliasAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5837 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), ArmCdeAliasValid(), ArmMveAliasValid(), ArmSveAliasValid(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::IdentifierInfo::getBuiltinID(), clang::ASTContext::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and RISCVAliasValid().
Referenced by ProcessDeclAttribute().
handleCallableWhenAttr()
static void handleCallableWhenAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1239 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), checkForConsumableClass(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::IdentifierInfo::getName(), clang::ParsedAttr::getNumArgs(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleCallbackAttr()
static void handleCallbackAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Handle attribute((callback(CalleeIdx, PayloadIdx0, ...))) attributes.
Definition at line 4049 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getAsFunction(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamType(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::ParsedAttr::getNumArgs(), clang::Type::getPointeeType(), clang::AttributeCommonInfo::getRange(), clang::Stmt::getSourceRange(), clang::QualType::getTypePtr(), clang::Type::getUnqualifiedDesugaredType(), clang::Decl::hasAttr(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgExpr(), clang::ParsedAttr::isArgIdent(), clang::Type::isFunctionPointerType(), isInstanceMethod(), clang::IdentifierLoc::Loc, and clang::FunctionDecl::parameters().
Referenced by ProcessDeclAttribute().
handleCallConvAttr()
static void handleCallConvAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5114 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::CC_AAPCS, clang::CC_AAPCS_VFP, clang::Sema::CheckCallingConvAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionOrMethod, clang::ParsedAttr::getKind(), clang::AttributeCommonInfo::getLoc(), hasDeclarator(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleCalledOnceAttr()
static void handleCalledOnceAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Handle 'called_once' attribute.
Definition at line 4195 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and isFunctionLike().
Referenced by ProcessDeclAttribute().
handleCapabilityAttr()
static void handleCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8095 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::ParsedAttr::getKind(), and N.
Referenced by ProcessDeclAttribute().
handleCFGuardAttr()
static void handleCFGuardAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8587 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleCleanupAttr()
static void handleCleanupAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3695 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::CheckAssignmentConstraints(), clang::Sema::Compatible, clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::DeclRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::Decl::getLocation(), clang::DeclarationNameInfo::getName(), clang::DeclRefExpr::getNameInfo(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), getType(), clang::DeclRefExpr::hasQualifier(), clang::Sema::NoteAllOverloadCandidates(), clang::ASTContext::OverloadTy, and clang::Sema::ResolveSingleFunctionTemplateSpecialization().
Referenced by ProcessDeclAttribute().
handleCmseNSEntryAttr()
static void handleCmseNSEntryAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2143 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::AttributeCommonInfo::getLoc(), clang::NamedDecl::isExternallyVisible(), clang::DeclContext::isExternCContext(), and clang::Sema::LangOpts.
Referenced by ProcessDeclAttribute().
handleCodeSegAttr()
static void handleCodeSegAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3388 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkCodeSegName(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Diag(), clang::Decl::dropAttr(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and clang::Sema::mergeCodeSegAttr().
Referenced by ProcessDeclAttribute().
handleCommonAttr()
static void handleCommonAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2133 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, AttributeLangSupport::Cpp, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::Sema::LangOpts.
Referenced by ProcessDeclAttribute().
handleConstantAttr()
static void handleConstantAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5004 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::dropAttr(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleConstructorAttr()
static void handleConstructorAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2340 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleConsumableAttr()
static void handleConsumableAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1204 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleCPUSpecificAttr()
static void handleCPUSpecificAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2061 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::cast(), clang::ParsedAttr::checkAtLeastNumArgs(), checkAttrMutualExclusion(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getAttr(), clang::ParsedAttr::getKind(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), getNumAttributeArgs(), clang::AttributeCommonInfo::getParsedKind(), clang::ASTContext::getTargetInfo(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), clang::IdentifierLoc::Loc, clang::FunctionDecl::setIsMultiVersion(), and clang::TargetInfo::validateCPUSpecificCPUDispatch().
Referenced by ProcessDeclAttribute().
handleDeclspecThreadAttr()
static void handleDeclspecThreadAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7302 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::isTLSSupported(), and clang::TSCS_unspecified.
Referenced by ProcessDeclAttribute().
handleDelayedForbiddenType()
static void handleDelayedForbiddenType (Sema & S, DelayedDiagnostic & DD, Decl * D) static
Handle a delayed forbidden-type diagnostic.
Definition at line 9820 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::sema::DelayedDiagnostic::getForbiddenTypeArgument(), clang::sema::DelayedDiagnostic::getForbiddenTypeDiagnostic(), clang::sema::DelayedDiagnostic::getForbiddenTypeOperand(), clang::Sema::getLangOpts(), clang::Decl::hasAttr(), isForbiddenTypeAllowed(), clang::sema::DelayedDiagnostic::Loc, and clang::sema::DelayedDiagnostic::Triggered.
Referenced by clang::Sema::PopParsingDeclaration().
handleDependencyAttr()
static void handleDependencyAttr (Sema & S, Scope * Scope, Decl * D, const ParsedAttr & AL) static
Definition at line 2314 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Scope::FunctionDeclarationScope, clang::Scope::getFlags(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleDeprecatedAttr()
static void handleDeprecatedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8169 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtMostNumArgs(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::SourceRange::getBegin(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::ParsedAttr::isArgExpr(), clang::AttributeCommonInfo::isCXX11Attribute(), clang::AttributeCommonInfo::isDeclspecAttribute(), clang::AttributeCommonInfo::isGNUScope(), and clang::AttributeCommonInfo::isStandardAttributeSyntax().
Referenced by ProcessDeclAttribute().
handleDestroyAttr()
static void handleDestroyAttr (Sema & S, Decl * D, const ParsedAttr & A) static
Definition at line 8427 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::ParsedAttr::getKind(), clang::Decl::getLocation(), and handleSimpleAttribute().
Referenced by ProcessDeclAttribute().
handleDestructorAttr()
static void handleDestructorAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2353 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleDeviceAttr()
static void handleDeviceAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5072 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::dropAttr(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleDiagnoseAsBuiltinAttr()
static void handleDiagnoseAsBuiltinAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1018 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentBuiltinFunction, clang::AANT_ArgumentIntegerConstant, clang::Decl::addAttr(), clang::cast(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArg(), clang::ParsedAttr::getArgAsExpr(), clang::Stmt::getBeginLoc(), clang::FunctionDecl::getBuiltinID(), clang::QualType::getCanonicalType(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::ParsedAttr::isArgExpr(), and Union.
Referenced by ProcessDeclAttribute().
handleDiagnoseIfAttr()
static void handleDiagnoseIfAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1096 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkFunctionConditionAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Cond, clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Stmt::getBeginLoc(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleDLLAttr()
static void handleDLLAttr (Sema & S, Decl * D, const ParsedAttr & A) static
Definition at line 8028 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::ParsedAttr::getKind(), clang::AttributeCommonInfo::getRange(), clang::ASTContext::getTargetInfo(), clang::FunctionDecl::isInlined(), clang::Sema::mergeDLLExportAttr(), clang::Sema::mergeDLLImportAttr(), and clang::TargetInfo::shouldDLLImportComdatSymbols().
Referenced by ProcessDeclAttribute().
handleEnableIfAttr()
static void handleEnableIfAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 955 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkFunctionConditionAttr(), clang::Cond, clang::Sema::Context, clang::Sema::Diag(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleEnforceTCBAttr()
template<typename AttrTy , typename ConflictingAttrTy > static void handleEnforceTCBAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8618 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::dropAttr(), findEnforceTCBAttrByName(), clang::AttributeCommonInfo::getAttrName(), clang::AttributeCommonInfo::getLoc(), and clang::IdentifierInfo::getName().
Referenced by ProcessDeclAttribute().
handleEnumExtensibilityAttr()
static void handleEnumExtensibilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3750 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleErrorAttr()
static void handleErrorAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 964 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), and clang::Sema::mergeErrorAttr().
Referenced by ProcessDeclAttribute().
handleExclusiveTrylockFunctionAttr()
static void handleExclusiveTrylockFunctionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 890 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkTryLockFunAttrCommon(), clang::Sema::Context, and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleExternalSourceSymbolAttr()
static void handleExternalSourceSymbolAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2845 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), clang::Sema::Context, clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getArgAsIdent().
Referenced by ProcessDeclAttribute().
handleExtVectorTypeAttr()
static void handleExtVectorTypeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1397 of file SemaDeclAttr.cpp.
References clang::Sema::ExtVectorDecls, and clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >::push_back().
Referenced by ProcessDeclAttribute().
handleFormatArgAttr()
static void handleFormatArgAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Handle attribute((format_arg((idx)))) attribute based on http://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html.
Definition at line 3772 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Type::castAs(), checkFunctionOrMethodParameterIndex(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Type::getAs(), clang::ParamIdx::getASTIndex(), getFunctionOrMethodParamRange(), getFunctionOrMethodParamType(), getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getObjCInstanceTypeDecl(), clang::ASTContext::getObjCObjectPointerType(), clang::PointerType::getPointeeType(), clang::Stmt::getSourceRange(), clang::TypeDecl::getTypeForDecl(), isCFStringType(), clang::Type::isCharType(), isNSStringType(), and clang::Type::isPointerType().
Referenced by ProcessDeclAttribute().
handleFormatAttr()
static void handleFormatAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Handle attribute((format(type,idx,firstarg))) attributes based on http://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html.
Definition at line 3934 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Type::castAs(), checkUInt32Argument(), clang::Sema::Context, clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::IdentifierTable::get(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), getFormatAttrKind(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamRange(), getFunctionOrMethodParamType(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::IdentifierInfo::getName(), clang::PointerType::getPointeeType(), clang::Stmt::getSourceRange(), clang::IdentifierLoc::Ident, clang::ASTContext::Idents, IgnoredFormat, InvalidFormat, clang::ParsedAttr::isArgIdent(), isCFStringType(), clang::Type::isCharType(), isFunctionOrMethodVariadic(), isInstanceMethod(), isNSStringType(), clang::Type::isPointerType(), clang::Sema::mergeFormatAttr(), normalizeName(), and StrftimeFormat.
Referenced by ProcessDeclAttribute().
handleFunctionReturnThunksAttr()
static void handleFunctionReturnThunksAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8352 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Decl::dropAttr().
Referenced by ProcessDeclAttribute().
handleGlobalAttr()
static void handleGlobalAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5036 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Type::getAs(), clang::DeclaratorDecl::getBeginLoc(), clang::ParsedAttr::getKind(), clang::Sema::getLangOpts(), clang::FunctionDecl::getReturnType(), clang::FunctionDecl::getReturnTypeSourceRange(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSpecStartLoc(), clang::FunctionDecl::isInlineSpecified(), clang::Type::isInstantiationDependentType(), clang::SourceRange::isValid(), clang::Type::isVoidType(), and clang::Sema::LangOpts.
Referenced by ProcessDeclAttribute().
handleGNUInlineAttr()
static void handleGNUInlineAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5101 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::Sema::LangOpts, and clang::SC_Extern.
Referenced by ProcessDeclAttribute().
handleGuardedByAttr()
static void handleGuardedByAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 710 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkGuardedByAttrCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleHandleAttr()
template<typename Attr > static void handleHandleAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8575 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleHLSLNumThreadsAttr()
static void handleHLSLNumThreadsAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7046 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), Env, clang::ParsedAttr::getArgAsExpr(), clang::Expr::getExprLoc(), clang::AttributeCommonInfo::getLoc(), clang::hlsl::getStageFromEnvironment(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::Sema::mergeHLSLNumThreadsAttr(), and X.
Referenced by ProcessDeclAttribute().
handleHLSLResourceBindingAttr()
static void handleHLSLResourceBindingAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7216 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::Sema::getASTContext(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleHLSLShaderAttr()
static void handleHLSLShaderAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7179 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::Sema::mergeHLSLShaderAttr().
Referenced by ProcessDeclAttribute().
handleHLSLSV_DispatchThreadIDAttr()
static void handleHLSLSV_DispatchThreadIDAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7142 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), and isLegalTypeForHLSLSV_DispatchThreadID().
Referenced by ProcessDeclAttribute().
handleHLSLSVGroupIndexAttr()
static void handleHLSLSVGroupIndexAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7119 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), Env, clang::AttributeCommonInfo::getLoc(), clang::hlsl::getStageFromEnvironment(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
Referenced by ProcessDeclAttribute().
handleIBOutlet()
static void handleIBOutlet (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1493 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkIBOutletCommon(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleIBOutletCollection()
static void handleIBOutletCollection (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1500 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkIBOutletCommon(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Decl::getDeclContext(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::DeclContext::getParent(), clang::Sema::getScopeForContext(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ParsedAttr::getTypeArg(), clang::Sema::GetTypeFromParser(), clang::Sema::getTypeName(), clang::ParsedAttr::hasParsedType(), clang::ASTContext::Idents, clang::Type::isBuiltinType(), clang::Type::isObjCIdType(), and clang::Type::isObjCObjectType().
Referenced by ProcessDeclAttribute().
handleIFuncAttr()
static void handleIFuncAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1971 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::FunctionDecl::isThisDeclarationADefinition().
Referenced by ProcessDeclAttribute().
handleInitPriorityAttr()
static void handleInitPriorityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Handle attribute((init_priority(priority))) attributes based on http://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Attributes.html.
Definition at line 3843 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getBaseElementType(), clang::Sema::getCurFunctionOrMethodDecl(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::Sema::getSourceManager(), clang::Stmt::getSourceRange(), clang::SourceManager::isInSystemHeader(), and clang::ParsedAttr::setInvalid().
Referenced by ProcessDeclAttribute().
handleInternalLinkageAttr()
static void handleInternalLinkageAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8273 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::mergeInternalLinkageAttr().
Referenced by ProcessDeclAttribute().
handleInterruptAttr()
static void handleInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7805 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), handleAnyX86InterruptAttr(), handleARMInterruptAttr(), handleAVRInterruptAttr(), handleM68kInterruptAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), and handleRISCVInterruptAttr().
Referenced by ProcessDeclAttribute().
handleLaunchBoundsAttr()
static void handleLaunchBoundsAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5653 of file SemaDeclAttr.cpp.
References clang::Sema::AddLaunchBoundsAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute().
handleLayoutVersion()
static void handleLayoutVersion (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7981 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::AttributeCommonInfo::getLoc(), clang::Stmt::getSourceRange(), and clang::LangOptions::MSVC2015.
Referenced by ProcessDeclAttribute().
handleLifetimeCategoryAttr()
static void handleLifetimeCategoryAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5222 of file SemaDeclAttr.cpp.
References checkAttrMutualExclusion(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAttr(), clang::Decl::getCanonicalDecl(), clang::ParsedAttr::getKind(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getTypeArg(), clang::Sema::GetTypeFromParser(), clang::QualType::getTypePtrOrNull(), clang::ParsedAttr::hasParsedType(), clang::Type::isArrayType(), clang::Type::isReferenceType(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::Decl::redecls().
Referenced by ProcessDeclAttribute().
handleLockReturnedAttr()
static void handleLockReturnedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 900 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAttrArgsAreCapabilityObjs(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleLocksExcludedAttr()
static void handleLocksExcludedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 911 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), checkAttrArgsAreCapabilityObjs(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleM68kInterruptAttr()
static void handleM68kInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7484 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Decl::addAttr(), clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Expr::getIntegerConstantExpr(), clang::AttributeCommonInfo::getLoc(), clang::Stmt::getSourceRange(), int, and clang::ParsedAttr::isArgExpr().
Referenced by handleInterruptAttr().
handleManagedAttr()
static void handleManagedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5088 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::Decl::hasAttr().
Referenced by ProcessDeclAttribute().
handleMIGServerRoutineAttr()
static void handleMIGServerRoutineAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8521 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Sema::getASTContext(), clang::Decl::getBeginLoc(), getFunctionOrMethodResultType(), getName(), handleSimpleAttribute(), and clang::ASTContext::IntTy.
Referenced by ProcessDeclAttribute().
handleMinSizeAttr()
static void handleMinSizeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4994 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::mergeMinSizeAttr().
Referenced by ProcessDeclAttribute().
handleMinVectorWidthAttr()
static void handleMinVectorWidthAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3678 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and clang::ParsedAttr::setInvalid().
Referenced by ProcessDeclAttribute().
handleMipsInterruptAttr()
static void handleMipsInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7427 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAttrMutualExclusion(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionOrMethod, getFunctionOrMethodNumParams(), getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), hasFunctionProto(), isFunctionOrMethod(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by handleInterruptAttr().
handleModeAttr()
static void handleModeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
handleModeAttr - This attribute modifies the width of a decl with primitive type.
Despite what would be logical, the mode attribute is a decl attribute, not a type attribute: 'int ** __attribute((mode(HI))) *G;' tries to make 'G' be HImode, not an intermediate pointer.
Definition at line 4721 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Sema::AddModeAttr(), clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleMSAllocatorAttr()
static void handleMSAllocatorAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8543 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::FunctionDecl::getReturnType(), handleSimpleAttribute(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by ProcessDeclAttribute().
handleMSInheritanceAttr()
static void handleMSInheritanceAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7288 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ASTConsumer::AssignInheritanceModel(), AttributeLangSupport::C, clang::Sema::Consumer, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getSemanticSpelling(), clang::Sema::LangOpts, and clang::Sema::mergeMSInheritanceAttr().
Referenced by ProcessDeclAttribute().
handleMSP430InterruptAttr()
static void handleMSP430InterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7375 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Decl::addAttr(), clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionOrMethod, clang::ParsedAttr::getArgAsExpr(), getFunctionOrMethodNumParams(), getFunctionOrMethodResultType(), clang::Expr::getIntegerConstantExpr(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::Stmt::getSourceRange(), hasFunctionProto(), int, clang::ParsedAttr::isArgExpr(), isFunctionOrMethod(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by handleInterruptAttr().
handleNakedAttr()
static void handleNakedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2158 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getASTContext(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::AttributeCommonInfo::isDeclspecAttribute(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleNoBuiltinAttr()
static void handleNoBuiltinAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1122 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::dropAttr(), clang::Decl::getAttr(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), clang::Decl::hasAttr(), and clang::Builtin::Context::isBuiltinFunc().
Referenced by ProcessDeclAttribute().
handleNoCfCheckAttr()
static void handleNoCfCheckAttr (Sema & S, Decl * D, const ParsedAttr & Attrs) static
Definition at line 2209 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), and handleSimpleAttribute().
Referenced by ProcessDeclAttribute().
handleNoDebugAttr()
static void handleNoDebugAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4878 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleNoEscapeAttr()
static void handleNoEscapeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1656 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::Decl::isInvalidDecl(), and clang::Sema::isValidPointerAttrType().
Referenced by ProcessDeclAttribute().
handleNoMergeAttr()
static void handleNoMergeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8378 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute(), and ProcessStmtAttribute().
handleNonNullAttr()
static void handleNonNullAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1583 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), attrNonNullArgCheck(), checkFunctionOrMethodParameterIndex(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParamIdx::getASTIndex(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamRange(), getFunctionOrMethodParamType(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::Stmt::getSourceRange(), clang::Sema::inTemplateInstantiation(), clang::SourceLocation::isFileID(), isFunctionOrMethodVariadic(), and clang::Sema::isValidPointerAttrType().
Referenced by handleNonNullAttrParameter(), and ProcessDeclAttribute().
handleNonNullAttrParameter()
static void handleNonNullAttrParameter (Sema & S, ParmVarDecl * D, const ParsedAttr & AL) static
Definition at line 1626 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), attrNonNullArgCheck(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getFunctionType(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::ParmVarDecl::getSourceRange(), clang::ValueDecl::getType(), and handleNonNullAttr().
Referenced by ProcessDeclAttribute().
handleNoRandomizeLayoutAttr()
static void handleNoRandomizeLayoutAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5296 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAttrMutualExclusion(), clang::Sema::Context, and clang::Decl::hasAttr().
Referenced by ProcessDeclAttribute().
handleNoReturnAttr()
static void handleNoReturnAttr (Sema & S, Decl * D, const ParsedAttr & Attrs) static
Definition at line 2181 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionOrMethod, clang::AttributeCommonInfo::getLoc(), hasDeclarator(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleNoSanitizeAttr()
static void handleNoSanitizeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8215 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), isGlobalVar(), isSanitizerAttributeAllowedOnGlobals(), and clang::parseSanitizerValue().
Referenced by ProcessDeclAttribute().
handleNoSanitizeSpecificAttr()
static void handleNoSanitizeSpecificAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8242 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunction, clang::AttributeCommonInfo::getAttrName(), clang::Decl::getLocation(), clang::IdentifierInfo::getName(), isGlobalVar(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::AttributeCommonInfo::isStandardAttributeSyntax(), normalizeName(), and clang::AttributeCommonInfo::setAttributeSpellingListIndex().
Referenced by ProcessDeclAttribute().
handleNSErrorDomain()
static void handleNSErrorDomain (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6144 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::DeclRefExpr::getDecl(), clang::AttributeCommonInfo::getLoc(), isCFStringType(), and isNSStringType().
Referenced by ProcessDeclAttribute().
handleObjCBoxable()
static void handleObjCBoxable (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6262 of file SemaDeclAttr.cpp.
References clang::Sema::Context, and clang::Sema::getASTMutationListener().
Referenced by ProcessDeclAttribute().
handleObjCBridgeAttr()
static void handleObjCBridgeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6169 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getBeginLoc(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierInfo::isStr().
Referenced by ProcessDeclAttribute().
handleObjCBridgeMutableAttr()
static void handleObjCBridgeMutableAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6195 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getBeginLoc(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleObjCBridgeRelatedAttr()
static void handleObjCBridgeRelatedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6208 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getBeginLoc(), clang::IdentifierLoc::Ident, and clang::ParsedAttr::isArgIdent().
Referenced by ProcessDeclAttribute().
handleObjCDesignatedInitializer()
static void handleObjCDesignatedInitializer (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6224 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), and clang::ObjCInterfaceDecl::setHasDesignatedInitializers().
Referenced by ProcessDeclAttribute().
handleObjCDirectAttr()
static void handleObjCDirectAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2940 of file SemaDeclAttr.cpp.
References clang::ObjCRuntime::allowsDirectDispatch(), clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), handleSimpleAttribute(), and clang::LangOptions::ObjCRuntime.
Referenced by ProcessDeclAttribute().
handleObjCDirectMembersAttr()
static void handleObjCDirectMembersAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2954 of file SemaDeclAttr.cpp.
References clang::ObjCRuntime::allowsDirectDispatch(), clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), handleSimpleAttribute(), and clang::LangOptions::ObjCRuntime.
Referenced by ProcessDeclAttribute().
handleObjCExternallyRetainedAttr()
static void handleObjCExternallyRetainedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8483 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Decl::getBeginLoc(), getFunctionOrMethodNumParams(), getFunctionOrMethodParam(), clang::QualType::getLocalUnqualifiedType(), clang::Qualifiers::getObjCLifetime(), clang::QualType::getQualifiers(), handleSimpleAttribute(), hasFunctionProto(), clang::Qualifiers::OCL_Strong, and tryMakeVariablePseudoStrong().
Referenced by ProcessDeclAttribute().
handleObjCIndependentClass()
static void handleObjCIndependentClass (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3016 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Decl::getLocation().
Referenced by ProcessDeclAttribute().
handleObjCMethodFamilyAttr()
static void handleObjCMethodFamilyAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2963 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleObjCNSObject()
static void handleObjCNSObject (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2989 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Decl::getLocation().
Referenced by ProcessDeclAttribute().
handleObjCOwnershipAttr()
static void handleObjCOwnershipAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6284 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::ExpectedVariable, clang::Decl::getBeginLoc(), clang::AttributeCommonInfo::getRange(), hasDeclarator(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleObjCPreciseLifetimeAttr()
static void handleObjCPreciseLifetimeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6293 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::Type::getObjCARCImplicitLifetime(), clang::QualType::getObjCLifetime(), clang::Type::isDependentType(), clang::Type::isObjCLifetimeType(), clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, and clang::Qualifiers::OCL_Weak.
Referenced by ProcessDeclAttribute().
handleObjCRequiresSuperAttr()
static void handleObjCRequiresSuperAttr (Sema & S, Decl * D, const ParsedAttr & Attrs) static
Definition at line 6124 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getBeginLoc(), and clang::OMF_dealloc.
Referenced by ProcessDeclAttribute().
handleObjCReturnsInnerPointerAttr()
static void handleObjCReturnsInnerPointerAttr (Sema & S, Decl * D, const ParsedAttr & Attrs) static
Definition at line 6098 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getBeginLoc(), clang::AttributeCommonInfo::getLoc(), clang::isa(), clang::Type::isObjCRetainableType(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by ProcessDeclAttribute().
handleObjCRuntimeName()
static void handleObjCRuntimeName (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6250 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleObjCSuppresProtocolAttr()
static void handleObjCSuppresProtocolAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2372 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::AttributeCommonInfo::getRange().
Referenced by ProcessDeclAttribute().
handleOpenCLAccessAttr()
static void handleOpenCLAccessAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8287 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getAttrName(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::Sema::getOpenCLOptions(), clang::AttributeCommonInfo::getRange(), clang::ParsedAttr::getSemanticSpelling(), clang::Decl::getSourceRange(), clang::Decl::hasAttr(), clang::Decl::isInvalidDecl(), clang::OpenCLOptions::isSupported(), and clang::Decl::setInvalidDecl().
Referenced by ProcessDeclAttribute().
handleOpenCLNoSVMAttr()
static void handleOpenCLNoSVMAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8278 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::LangOptions::getOpenCLCompatibleVersion(), clang::LangOptions::getOpenCLVersionString(), and clang::Sema::LangOpts.
Referenced by ProcessDeclAttribute().
handleOptimizeNoneAttr()
static void handleOptimizeNoneAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4999 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::mergeOptimizeNoneAttr().
Referenced by ProcessDeclAttribute().
handleOwnershipAttr()
static void handleOwnershipAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1809 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), checkFunctionOrMethodParameterIndex(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::ParamIdx::getASTIndex(), getFunctionOrMethodParamType(), clang::Preprocessor::getIdentifierTable(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::ParamIdx::getSourceIndex(), clang::Stmt::getSourceRange(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), normalizeName(), clang::Sema::PP, and clang::Decl::specific_attrs().
Referenced by ProcessDeclAttribute().
handlePackedAttr()
static void handlePackedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1402 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getASTContext(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ValueDecl::getType(), clang::ASTContext::getTypeAlign(), and clang::Type::isIncompleteType().
Referenced by ProcessDeclAttribute().
handleParamTypestateAttr()
static void handleParamTypestateAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1274 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handlePassObjectSizeAttr()
static void handlePassObjectSizeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1172 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Decl::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), getType(), clang::Decl::hasAttr(), and Type.
Referenced by ProcessDeclAttribute().
handlePatchableFunctionEntryAttr()
static void handlePatchableFunctionEntryAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5733 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), getAttrLoc(), clang::Stmt::getBeginLoc(), clang::ParsedAttr::getNumArgs(), and Offset.
Referenced by ProcessDeclAttribute().
handlePreferredName()
static void handlePreferredName (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1430 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::declaresSameEntity(), clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ParsedAttr::getTypeArg(), and clang::Sema::GetTypeFromParser().
Referenced by ProcessDeclAttribute().
handlePtGuardedByAttr()
static void handlePtGuardedByAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 718 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkGuardedByAttrCommon(), clang::Sema::Context, and threadSafetyCheckIsPointer().
Referenced by ProcessDeclAttribute().
handlePtGuardedVarAttr()
static void handlePtGuardedVarAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 689 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, and threadSafetyCheckIsPointer().
Referenced by ProcessDeclAttribute().
handleRandomizeLayoutAttr()
static void handleRandomizeLayoutAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5289 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAttrMutualExclusion(), clang::Sema::Context, and clang::Decl::hasAttr().
Referenced by ProcessDeclAttribute().
handleReleaseCapabilityAttr()
static void handleReleaseCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8142 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkAttrArgsAreCapabilityObjs(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleRequiresCapabilityAttr()
static void handleRequiresCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8152 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), checkAttrArgsAreCapabilityObjs(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleRestrictAttr()
static void handleRestrictAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2050 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), getFunctionOrMethodResultSourceRange(), getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::Type::isAnyPointerType(), and clang::Type::isBlockPointerType().
Referenced by ProcessDeclAttribute().
handleReturnsNonNullAttr()
static void handleReturnsNonNullAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1646 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), attrNonNullArgCheck(), clang::Sema::Context, getFunctionOrMethodResultSourceRange(), and getFunctionOrMethodResultType().
Referenced by ProcessDeclAttribute().
handleReturnTypestateAttr()
static void handleReturnTypestateAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1308 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleRISCVInterruptAttr()
static void handleRISCVInterruptAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7747 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtMostNumArgs(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunction, clang::Decl::getAttr(), clang::SourceRange::getBegin(), getFunctionOrMethodNumParams(), getFunctionOrMethodResultType(), clang::Decl::getFunctionType(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), clang::AttributeCommonInfo::getRange(), hasFunctionProto(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by handleInterruptAttr().
handleSectionAttr()
static void handleSectionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3334 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkSectionName(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::mergeSectionAttr(), clang::ASTContext::PSF_Execute, clang::ASTContext::PSF_Read, and clang::Sema::UnifySection().
Referenced by ProcessDeclAttribute().
handleSentinelAttr()
static void handleSentinelAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3047 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Decl::addAttr(), clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunctionMethodOrBlock, clang::ParsedAttr::getArgAsExpr(), clang::Decl::getFunctionType(), clang::Expr::getIntegerConstantExpr(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::Type::isBlockPointerType(), clang::Type::isFunctionPointerType(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::Expr::isTypeDependent(), and V.
Referenced by ProcessDeclAttribute().
handleSetTypestateAttr()
static void handleSetTypestateAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1353 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), checkForConsumableClass(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleSharedAttr()
static void handleSharedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5020 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::CUDADiagIfHostCode(), clang::Sema::CurrentCUDATarget(), clang::Sema::Diag(), clang::Sema::getLangOpts(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleSharedTrylockFunctionAttr()
static void handleSharedTrylockFunctionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 880 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkTryLockFunAttrCommon(), clang::Sema::Context, and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleSimpleAttribute()
template<typename AttrType > static void handleSimpleAttribute (Sema & S, Decl * D, const AttributeCommonInfo & CI) static
Applies the given attribute to the Decl without performing any additional semantic checking.
Definition at line 390 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::Context.
Referenced by handleAvailableOnlyInDefaultEvalMethod(), handleAVRInterruptAttr(), handleAVRSignalAttr(), handleDestroyAttr(), handleMIGServerRoutineAttr(), handleMSAllocatorAttr(), handleNoCfCheckAttr(), handleObjCDirectAttr(), handleObjCDirectMembersAttr(), handleObjCExternallyRetainedAttr(), handleSimpleAttributeOrDiagnose(), handleSYCLKernelAttr(), handleXReturnsXRetainedAttr(), and ProcessDeclAttribute().
handleSimpleAttributeOrDiagnose()
template<typename AttrType , typename... DiagnosticArgs> static void handleSimpleAttributeOrDiagnose (Sema & S, Decl * D, const AttributeCommonInfo & CI, bool PassesCheck, unsigned DiagID, DiagnosticArgs &&... ExtraArgs) static
Add an attribute AttrType to declaration D, provided that PassesCheck is true.
Otherwise, emit diagnostic DiagID, passing in all parameters specified in ExtraArgs.
Definition at line 414 of file SemaDeclAttr.cpp.
References appendDiagnostics(), clang::Sema::Diag(), clang::Decl::getBeginLoc(), and handleSimpleAttribute().
Referenced by clang::Sema::AddXConsumedAttr(), and ProcessDeclAttribute().
handleStandardNoReturnAttr()
static void handleStandardNoReturnAttr (Sema & S, Decl * D, const ParsedAttr & A) static
Definition at line 2194 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::ParsedAttr::getSemanticSpelling(), clang::Sema::getSourceManager(), clang::SourceManager::isInSystemMacro(), and clang::SourceLocation::isMacroID().
Referenced by ProcessDeclAttribute().
handleSubGroupSize()
static void handleSubGroupSize (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3237 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and clang::Stmt::getSourceRange().
Referenced by ProcessDeclAttribute().
handleSuppressAttr()
static void handleSuppressAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5202 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and clang::ParsedAttr::getNumArgs().
Referenced by ProcessDeclAttribute(), and ProcessStmtAttribute().
handleSwiftAsyncAttr()
static void handleSwiftAsyncAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6912 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::Type::castAs(), clang::ParsedAttr::checkExactlyNumArgs(), checkFunctionOrMethodParameterIndex(), checkSwiftAsyncErrorBlock(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::ParamIdx::getASTIndex(), clang::Decl::getAttr(), getFunctionOrMethodParam(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::IdentifierInfo::getName(), clang::FunctionType::getReturnType(), clang::ValueDecl::getType(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), clang::Type::isBlockPointerType(), and clang::Type::isVoidType().
Referenced by ProcessDeclAttribute().
handleSwiftAsyncError()
static void handleSwiftAsyncError (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6537 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkExactlyNumArgs(), checkSwiftAsyncErrorBlock(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getArgAsIdent(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), and clang::IdentifierLoc::Ident.
Referenced by ProcessDeclAttribute().
handleSwiftAsyncName()
static void handleSwiftAsyncName (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6873 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and clang::Sema::DiagnoseSwiftName().
Referenced by ProcessDeclAttribute().
handleSwiftAttrAttr()
static void handleSwiftAttrAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6332 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleSwiftBridge()
static void handleSwiftBridge (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6342 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleSwiftError()
static void handleSwiftError (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6382 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamType(), getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::Type::hasPointerRepresentation(), clang::IdentifierLoc::Ident, clang::isa(), isErrorParameter(), clang::Type::isIntegralType(), clang::Decl::isInvalidDecl(), and clang::Type::isReferenceType().
Referenced by ProcessDeclAttribute().
handleSwiftName()
static void handleSwiftName (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6861 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, and clang::Sema::DiagnoseSwiftName().
Referenced by ProcessDeclAttribute().
handleSwiftNewType()
static void handleSwiftNewType (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6885 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleSYCLKernelAttr()
static void handleSYCLKernelAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8388 of file SemaDeclAttr.cpp.
References clang::cast(), clang::Sema::Diag(), clang::FunctionDecl::getDescribedFunctionTemplate(), getFunctionOrMethodNumParams(), getFunctionOrMethodResultType(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateDecl::getTemplateParameters(), handleSimpleAttribute(), clang::Type::isVoidType(), and clang::TemplateParameterList::size().
Referenced by ProcessDeclAttribute().
handleTargetAttr()
static void handleTargetAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3503 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::checkTargetAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleTargetClonesAttr()
static void handleTargetClonesAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3611 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), checkAttrMutualExclusion(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::checkTargetClonesAttrString(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::TargetInfo::hasFeature(), clang::Expr::IgnoreParenCasts(), and clang::TargetClones.
Referenced by ProcessDeclAttribute().
handleTargetVersionAttr()
static void handleTargetVersionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3488 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::checkTargetVersionAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleTestTypestateAttr()
static void handleTestTypestateAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1375 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), checkForConsumableClass(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::IdentifierLoc::Loc.
Referenced by ProcessDeclAttribute().
handleTLSModelAttr()
static void handleTLSModelAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2027 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
Referenced by ProcessDeclAttribute().
handleTransparentUnionAttr()
static void handleTransparentUnionAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 4207 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedUnion, clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::ASTContext::getTypeAlign(), clang::ASTContext::getTypeSize(), clang::Type::hasFloatingRepresentation(), clang::TagDecl::isBeingDefined(), clang::TagDecl::isCompleteDefinition(), clang::Type::isIncompleteType(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::TagDecl::isUnion(), and clang::Type::isVectorType().
Referenced by ProcessDeclAttribute(), and clang::Sema::ProcessDeclAttributeDelayed().
handleTryAcquireCapabilityAttr()
static void handleTryAcquireCapabilityAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8132 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkTryLockFunAttrCommon(), clang::Sema::Context, and clang::ParsedAttr::getArgAsExpr().
Referenced by ProcessDeclAttribute().
handleTypeTagForDatatypeAttr()
static void handleTypeTagForDatatypeAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5693 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), clang::ParsedAttr::checkExactlyNumArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedVariable, clang::ParsedAttr::getArgAsIdent(), clang::ParsedAttr::getLayoutCompatible(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getMatchingCType(), clang::ParsedAttr::getMustBeNull(), clang::Sema::GetTypeFromParser(), clang::IdentifierLoc::Ident, clang::ParsedAttr::isArgIdent(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleUninitializedAttr()
static void handleUninitializedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8440 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, and clang::SD_Automatic.
Referenced by ProcessDeclAttribute().
handleUnsafeBufferUsage()
template<typename Attr > static void handleUnsafeBufferUsage (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8583 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), and clang::Sema::Context.
Referenced by ProcessDeclAttribute().
handleUnusedAttr()
static void handleUnusedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2329 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getScopeName(), and clang::AttributeCommonInfo::isCXX11Attribute().
Referenced by ProcessDeclAttribute().
handleUuidAttr()
static void handleUuidAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 6986 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), AttributeLangSupport::C, clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getMSGuidDecl(), clang::isHexDigit(), clang::AttributeCommonInfo::isMicrosoftAttribute(), clang::Sema::LangOpts, clang::Sema::mergeUuidAttr(), clang::MSGuidDeclParts::Part1, clang::MSGuidDeclParts::Part2, clang::MSGuidDeclParts::Part3, and clang::MSGuidDeclParts::Part4And5.
Referenced by ProcessDeclAttribute().
handleVecReturnAttr()
static void handleVecReturnAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 2260 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
Referenced by ProcessDeclAttribute().
handleVecTypeHint()
static void handleVecTypeHint (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3257 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getASTContext(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getTypeArg(), clang::Sema::GetTypeFromParser(), clang::ParsedAttr::hasParsedType(), clang::ASTContext::hasSameType(), clang::Type::isBooleanType(), clang::Type::isExtVectorType(), clang::Type::isFloatingType(), and clang::Type::isIntegralType().
Referenced by ProcessDeclAttribute().
handleVisibilityAttr()
static void handleVisibilityAttr (Sema & S, Decl * D, const ParsedAttr & AL, bool isTypeVisibility) static
Definition at line 2892 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedTypeOrNamespace, clang::SourceRange::getBegin(), clang::AttributeCommonInfo::getLoc(), clang::AttributeCommonInfo::getRange(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::hasProtectedVisibility(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::Sema::mergeTypeVisibilityAttr(), clang::Sema::mergeVisibilityAttr(), and clang::ast_matchers::type.
Referenced by ProcessDeclAttribute().
handleWarnUnusedResult()
static void handleWarnUnusedResult (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3136 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getFunctionType(), clang::Sema::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::FunctionType::getReturnType(), clang::AttributeCommonInfo::getScopeName(), clang::AttributeCommonInfo::isClangScope(), clang::AttributeCommonInfo::isGNUAttribute(), clang::AttributeCommonInfo::isGNUScope(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::AttributeCommonInfo::isStandardAttributeSyntax(), and clang::Type::isVoidType().
Referenced by ProcessDeclAttribute().
handleWeakImportAttr()
static void handleWeakImportAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3189 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Decl::canBeWeakImported(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedVariableOrFunction, clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleWeakRefAttr()
static void handleWeakRefAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 1913 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::DeclContext::getRedeclContext(), and clang::DeclContext::isFileContext().
Referenced by ProcessDeclAttribute().
handleWebAssemblyExportNameAttr()
static void handleWebAssemblyExportNameAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7651 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunction, clang::Decl::getLocation(), isFunctionOrMethod(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::FunctionDecl::isThisDeclarationADefinition().
Referenced by ProcessDeclAttribute().
handleWebAssemblyImportModuleAttr()
static void handleWebAssemblyImportModuleAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7715 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::FunctionDecl::hasBody().
Referenced by ProcessDeclAttribute().
handleWebAssemblyImportNameAttr()
static void handleWebAssemblyImportNameAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7732 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::cast(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::AttributeCommonInfo::getLoc(), and clang::FunctionDecl::hasBody().
Referenced by ProcessDeclAttribute().
handleWorkGroupSize()
template<typename WorkGroupAttr > static void handleWorkGroupSize (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 3212 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkUInt32Argument(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and clang::Stmt::getSourceRange().
Referenced by ProcessDeclAttribute().
handleX86ForceAlignArgPointerAttr()
static void handleX86ForceAlignArgPointerAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 7958 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::Sema::Diag(), clang::ExpectedFunction, clang::AttributeCommonInfo::getLoc(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
Referenced by ProcessDeclAttribute().
handleXRayLogArgsAttr()
static void handleXRayLogArgsAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5720 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), checkFunctionOrMethodParameterIndex(), clang::Sema::Context, clang::ParsedAttr::getArgAsExpr(), and clang::ParamIdx::getSourceIndex().
Referenced by ProcessDeclAttribute().
handleXReturnsXRetainedAttr()
static void handleXReturnsXRetainedAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 5966 of file SemaDeclAttr.cpp.
References clang::Sema::CF, clang::Sema::Diag(), clang::ExpectedFunctionMethodOrParameter, clang::ExpectedFunctionOrMethod, clang::Decl::getBeginLoc(), clang::ParsedAttr::getKind(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::AttributeCommonInfo::getRange(), clang::FunctionDecl::getReturnType(), handleSimpleAttribute(), hasDeclarator(), clang::QualType::isNull(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::ParsedAttr::isUsedAsTypeAttr(), isValidSubjectOfCFAttribute(), isValidSubjectOfNSAttribute(), isValidSubjectOfNSReturnsRetainedAttribute(), isValidSubjectOfOSAttribute(), parsedAttrToRetainOwnershipKind(), and clang::Property.
Referenced by ProcessDeclAttribute().
handleZeroCallUsedRegsAttr()
static void handleZeroCallUsedRegsAttr (Sema & S, Decl * D, const ParsedAttr & AL) static
Definition at line 8334 of file SemaDeclAttr.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), clang::Sema::Context, clang::Sema::Diag(), and clang::Decl::dropAttr().
Referenced by ProcessDeclAttribute().
hasBTFDeclTagAttr()
static bool hasBTFDeclTagAttr (Decl * D, StringRef Tag) static
Definition at line 7627 of file SemaDeclAttr.cpp.
References clang::Decl::specific_attrs().
Referenced by handleBTFDeclTagAttr(), and clang::Sema::mergeBTFDeclTagAttr().
hasDeclarator()
static bool hasDeclarator (const Decl * D) static
Return true if the given decl has a declarator that should have been processed by Sema::GetTypeForDeclarator.
Definition at line 81 of file SemaDeclAttr.cpp.
References clang::isa().
Referenced by handleCallConvAttr(), handleNoReturnAttr(), handleObjCOwnershipAttr(), and handleXReturnsXRetainedAttr().
hasFunctionProto()
static bool hasFunctionProto (const Decl * D) static
hasFunctionProto - Return true if the given decl has a argument information.
This decl should have already passed isFunctionOrMethod or isFunctionOrMethodOrBlock.
Definition at line 90 of file SemaDeclAttr.cpp.
References clang::Decl::getFunctionType(), and clang::isa().
Referenced by checkFunctionOrMethodParameterIndex(), handleAllocSizeAttr(), handleAnyX86InterruptAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), handleObjCExternallyRetainedAttr(), and handleRISCVInterruptAttr().
isCapabilityExpr()
static bool isCapabilityExpr (Sema & S, const Expr * Ex) static
Definition at line 562 of file SemaDeclAttr.cpp.
References clang::Expr::getType(), isCapabilityExpr(), and typeHasCapability().
Referenced by checkAttrArgsAreCapabilityObjs(), and isCapabilityExpr().
isCFStringType()
static bool isCFStringType (QualType T, ASTContext & Ctx) inline static
Definition at line 181 of file SemaDeclAttr.cpp.
References clang::IdentifierTable::get(), clang::Type::getAs(), clang::NamedDecl::getIdentifier(), clang::PointerType::getPointeeType(), clang::TagDecl::getTagKind(), and clang::ASTContext::Idents.
Referenced by handleFormatArgAttr(), handleFormatAttr(), and handleNSErrorDomain().
isErrorParameter()
static bool isErrorParameter (Sema & S, QualType QT) static
Definition at line 6360 of file SemaDeclAttr.cpp.
References clang::Type::getAs(), clang::Sema::getNSErrorIdent(), clang::Type::getPointeeType(), and clang::Sema::isCFError().
Referenced by handleSwiftError().
isForbiddenTypeAllowed()
static bool isForbiddenTypeAllowed (Sema & S, Decl * D, const DelayedDiagnostic & diag, UnavailableAttr::ImplicitReason & reason) static
Is the given declaration allowed to use a forbidden type? If so, it'll still be annotated with an attribute that makes it illegal to actually use.
Definition at line 9785 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::sema::DelayedDiagnostic::getForbiddenTypeDiagnostic(), clang::Decl::getLocation(), clang::ASTContext::getSourceManager(), and clang::SourceManager::isInSystemHeader().
Referenced by handleDelayedForbiddenType().
isFunctionLike()
static bool isFunctionLike (const Type & T) static
Definition at line 4187 of file SemaDeclAttr.cpp.
Referenced by handleCalledOnceAttr().
isFunctionOrMethod()
static bool isFunctionOrMethod (const Decl * D) static
isFunctionOrMethod - Return true if the given decl has function type (function or function-typed variable) or an Objective-C method.
Definition at line 69 of file SemaDeclAttr.cpp.
References clang::Decl::getFunctionType(), and clang::isa().
Referenced by GetFullTypeForDeclarator(), handleAllocSizeAttr(), handleAnyX86InterruptAttr(), handleAVRInterruptAttr(), handleAVRSignalAttr(), handleMipsInterruptAttr(), handleMSP430InterruptAttr(), handleWebAssemblyExportNameAttr(), isFunctionOrMethodOrBlock(), mergeTypeWithPrevious(), and clang::NamedDecl::printQualifiedName().
isFunctionOrMethodOrBlock()
static bool isFunctionOrMethodOrBlock (const Decl * D) static
Return true if the given decl has function type (function or function-typed variable) or an Objective-C method or a block.
Definition at line 75 of file SemaDeclAttr.cpp.
References clang::isa(), and isFunctionOrMethod().
Referenced by checkFunctionOrMethodParameterIndex(), and handleAnalyzerNoReturnAttr().
isFunctionOrMethodVariadic()
static bool isFunctionOrMethodVariadic (const Decl * D) static
Definition at line 147 of file SemaDeclAttr.cpp.
References clang::cast(), and clang::Decl::getFunctionType().
Referenced by checkFunctionOrMethodParameterIndex(), handleFormatAttr(), and handleNonNullAttr().
isGlobalVar()
static bool isGlobalVar (const Decl * D) static
Definition at line 8204 of file SemaDeclAttr.cpp.
Referenced by handleNoSanitizeAttr(), and handleNoSanitizeSpecificAttr().
isInstanceMethod()
static bool isInstanceMethod (const Decl * D) static
Definition at line 155 of file SemaDeclAttr.cpp.
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), checkFunctionOrMethodParameterIndex(), handleAnyX86InterruptAttr(), handleCallbackAttr(), and handleFormatAttr().
isIntOrBool()
static bool isIntOrBool (Expr * Exp) static
Check if the passed-in expression is of type int or bool.
Definition at line 427 of file SemaDeclAttr.cpp.
References clang::Expr::getType(), clang::Type::isBooleanType(), and clang::Type::isIntegerType().
Referenced by checkTryLockFunAttrCommon().
isLegalTypeForHLSLSV_DispatchThreadID()
static bool isLegalTypeForHLSLSV_DispatchThreadID (QualType T) static
Definition at line 7134 of file SemaDeclAttr.cpp.
Referenced by handleHLSLSV_DispatchThreadIDAttr().
isNSStringType()
static bool isNSStringType (QualType T, ASTContext & Ctx, bool AllowNSAttributedString = false) inline static
Definition at line 161 of file SemaDeclAttr.cpp.
References clang::IdentifierTable::get(), clang::NamedDecl::getIdentifier(), and clang::ASTContext::Idents.
Referenced by handleFormatArgAttr(), handleFormatAttr(), and handleNSErrorDomain().
isSanitizerAttributeAllowedOnGlobals()
static bool isSanitizerAttributeAllowedOnGlobals (StringRef Sanitizer) static
Definition at line 8210 of file SemaDeclAttr.cpp.
Referenced by handleNoSanitizeAttr().
isValidOSObjectOutParameter()
static bool isValidOSObjectOutParameter (const Decl * D) static
Returns
whether the parameter is a pointer to OSObject pointer.
Definition at line 5957 of file SemaDeclAttr.cpp.
References clang::Type::getPointeeType(), clang::QualType::isNull(), and isValidSubjectOfOSAttribute().
Referenced by ProcessDeclAttribute().
isValidSubjectOfCFAttribute()
static bool isValidSubjectOfCFAttribute (QualType QT) static
Definition at line 5877 of file SemaDeclAttr.cpp.
References clang::Type::isDependentType(), clang::Type::isPointerType(), and isValidSubjectOfNSAttribute().
Referenced by clang::Sema::AddXConsumedAttr(), and handleXReturnsXRetainedAttr().
isValidSubjectOfNSAttribute()
static bool isValidSubjectOfNSAttribute (QualType QT) static
Definition at line 5872 of file SemaDeclAttr.cpp.
References clang::Type::isDependentType(), clang::Type::isObjCNSObjectType(), and clang::Type::isObjCObjectPointerType().
Referenced by clang::Sema::AddXConsumedAttr(), handleXReturnsXRetainedAttr(), and isValidSubjectOfCFAttribute().
isValidSubjectOfNSReturnsRetainedAttribute()
static bool isValidSubjectOfNSReturnsRetainedAttribute (QualType QT) static
Definition at line 5868 of file SemaDeclAttr.cpp.
References clang::Type::isDependentType(), and clang::Type::isObjCRetainableType().
Referenced by clang::Sema::checkNSReturnsRetainedReturnType(), and handleXReturnsXRetainedAttr().
isValidSubjectOfOSAttribute()
static bool isValidSubjectOfOSAttribute (QualType QT) static
Definition at line 5882 of file SemaDeclAttr.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Type::getPointeeType(), clang::Type::isDependentType(), and clang::QualType::isNull().
Referenced by clang::Sema::AddXConsumedAttr(), handleXReturnsXRetainedAttr(), and isValidOSObjectOutParameter().
isValidSwiftContextType()
static bool isValidSwiftContextType (QualType Ty) static
Pointer-like types in the default address space.
Definition at line 5472 of file SemaDeclAttr.cpp.
References clang::Default, clang::QualType::getAddressSpace(), clang::Type::getPointeeType(), clang::Type::hasPointerRepresentation(), and clang::Type::isDependentType().
Referenced by clang::Sema::AddParameterABIAttr(), and isValidSwiftErrorResultType().
isValidSwiftErrorResultType()
static bool isValidSwiftErrorResultType (QualType Ty) static
Pointers and references to pointers in the default address space.
Definition at line 5491 of file SemaDeclAttr.cpp.
References clang::Qualifiers::empty(), clang::Type::getAs(), clang::Type::getPointeeType(), clang::QualType::getQualifiers(), clang::Type::isDependentType(), and isValidSwiftContextType().
Referenced by clang::Sema::AddParameterABIAttr().
isValidSwiftIndirectResultType()
static bool isValidSwiftIndirectResultType (QualType Ty) static
Pointers and references in the default address space.
Definition at line 5479 of file SemaDeclAttr.cpp.
References clang::Default, clang::QualType::getAddressSpace(), clang::Type::getAs(), clang::Type::getPointeeType(), and clang::Type::isDependentType().
Referenced by clang::Sema::AddParameterABIAttr().
makeLaunchBoundsArgExpr()
static Expr * makeLaunchBoundsArgExpr (Sema & S, Expr * E, const CUDALaunchBoundsAttr & AL, const unsigned Idx) static
Definition at line 5599 of file SemaDeclAttr.cpp.
References clang::AANT_ArgumentIntegerConstant, clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::ActionResult< PtrTy, CompressInvalid >::getAs(), clang::ASTContext::getConstType(), clang::Expr::getExprLoc(), clang::Expr::getIntegerConstantExpr(), clang::Stmt::getSourceRange(), clang::InitializedEntity::InitializeParameter(), clang::ASTContext::IntTy, clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Expr::isValueDependent(), clang::Sema::PerformCopyInitialization(), and toString().
Referenced by clang::Sema::AddLaunchBoundsAttr().
mergeEnforceTCBAttrImpl()
template<typename AttrTy , typename ConflictingAttrTy > static AttrTy * mergeEnforceTCBAttrImpl (Sema & S, Decl * D, const AttrTy & AL) static
Definition at line 8643 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::Decl::dropAttr(), findEnforceTCBAttrByName(), and clang::Sema::getASTContext().
Referenced by clang::Sema::mergeEnforceTCBAttr(), and clang::Sema::mergeEnforceTCBLeafAttr().
mergeVisibilityAttr()
template<class T > static T * mergeVisibilityAttr (Sema & S, Decl * D, const AttributeCommonInfo & CI, typename T::VisibilityType value) static
Definition at line 2866 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Decl::dropAttr(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
MustDelayAttributeArguments()
static bool MustDelayAttributeArguments (const ParsedAttr & AL) static
Definition at line 8681 of file SemaDeclAttr.cpp.
References clang::ParsedAttr::acceptsExprPack(), clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getNumArgMembers(), clang::ParsedAttr::getNumArgs(), clang::ParsedAttr::hasVariadicArg(), clang::ParsedAttr::isParamExpr(), and clang::Expr::isValueDependent().
Referenced by ProcessDeclAttribute().
normalizeName()
static bool normalizeName (StringRef & AttrName) static
Normalize the attribute, foo becomes foo.
Returns true if normalization was applied.
Definition at line 1800 of file SemaDeclAttr.cpp.
parsedAttrToRetainOwnershipKind()
static Sema::RetainOwnershipKind parsedAttrToRetainOwnershipKind (const ParsedAttr & AL) static
Definition at line 5923 of file SemaDeclAttr.cpp.
References clang::Sema::CF, clang::ParsedAttr::getKind(), clang::Sema::NS, and clang::Sema::OS.
Referenced by handleXReturnsXRetainedAttr(), and ProcessDeclAttribute().
parseModeAttrArg()
static void parseModeAttrArg (Sema & S, StringRef Str, unsigned & DestWidth, bool & IntegerMode, bool & ComplexMode, FloatModeKind & ExplicitType) static
parseModeAttrArg - Parses attribute mode string and returns parsed type attribute.
Definition at line 4650 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::Default, clang::Float128, clang::TargetInfo::getCharWidth(), clang::TargetInfo::getPointerWidth(), clang::TargetInfo::getRegisterWidth(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getUnwindWordWidth(), clang::Ibm128, clang::LongDouble, and clang::NoFloat.
Referenced by clang::Sema::AddModeAttr().
ProcessDeclAttribute()
static void ProcessDeclAttribute (Sema & S, Scope * scope, Decl * D, const ParsedAttr & AL, const Sema::ProcessDeclAttributeOptions & Options) static
ProcessDeclAttribute - Apply the specific attribute to the specified decl if the attribute applies to decls.
If the attribute is a type attribute, just silently ignore it if a GNU attribute.
Definition at line 8714 of file SemaDeclAttr.cpp.
References clang::Sema::AddParameterABIAttr(), clang::Sema::AddXConsumedAttr(), clang::Sema::checkCommonAttributeFeatures(), clang::Sema::Context, clang::Sema::Diag(), clang::ParsedAttr::existsInTarget(), clang::ParsedAttr::getInfo(), clang::ParsedAttr::getKind(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::AttributeCommonInfo::getRange(), clang::ASTContext::getTargetInfo(), handleAbiTagAttr(), handleAcquireCapabilityAttr(), handleAcquiredAfterAttr(), handleAcquiredBeforeAttr(), handleAcquireHandleAttr(), handleAliasAttr(), handleAlignedAttr(), handleAlignValueAttr(), handleAllocAlignAttr(), handleAllocSizeAttr(), handleAlwaysInlineAttr(), handleAMDGPUFlatWorkGroupSizeAttr(), handleAMDGPUNumSGPRAttr(), handleAMDGPUNumVGPRAttr(), handleAMDGPUWavesPerEUAttr(), handleAnalyzerNoReturnAttr(), handleAnnotateAttr(), handleArgumentWithTypeTagAttr(), handleArmBuiltinAliasAttr(), handleAssertCapabilityAttr(), handleAssertExclusiveLockAttr(), handleAssertSharedLockAttr(), handleAssumeAlignedAttr(), handleAssumumptionAttr(), clang::ParsedAttr::handleAttrWithDelayedArgs(), handleAttrWithMessage(), handleAvailabilityAttr(), handleAvailableOnlyInDefaultEvalMethod(), handleAVRSignalAttr(), handleBlocksAttr(), handleBPFPreserveAccessIndexAttr(), handleBTFDeclTagAttr(), handleBuiltinAliasAttr(), handleCallableWhenAttr(), handleCallbackAttr(), handleCallConvAttr(), handleCalledOnceAttr(), handleCapabilityAttr(), handleCFGuardAttr(), handleCleanupAttr(), handleCmseNSEntryAttr(), handleCodeSegAttr(), handleCommonAttr(), handleConstantAttr(), handleConstructorAttr(), handleConsumableAttr(), handleCPUSpecificAttr(), clang::ParsedAttrInfo::handleDeclAttribute(), handleDeclspecThreadAttr(), handleDependencyAttr(), handleDeprecatedAttr(), handleDestroyAttr(), handleDestructorAttr(), handleDeviceAttr(), handleDiagnoseAsBuiltinAttr(), handleDiagnoseIfAttr(), handleDLLAttr(), handleEnableIfAttr(), handleEnforceTCBAttr(), handleEnumExtensibilityAttr(), handleErrorAttr(), handleExclusiveTrylockFunctionAttr(), handleExternalSourceSymbolAttr(), handleExtVectorTypeAttr(), handleFormatArgAttr(), handleFormatAttr(), handleFunctionReturnThunksAttr(), handleGlobalAttr(), handleGNUInlineAttr(), handleGuardedByAttr(), handleHandleAttr(), handleHLSLNumThreadsAttr(), handleHLSLResourceBindingAttr(), handleHLSLShaderAttr(), handleHLSLSV_DispatchThreadIDAttr(), handleHLSLSVGroupIndexAttr(), handleIBOutlet(), handleIBOutletCollection(), handleIFuncAttr(), handleInitPriorityAttr(), handleInternalLinkageAttr(), handleInterruptAttr(), handleLaunchBoundsAttr(), handleLayoutVersion(), handleLifetimeCategoryAttr(), handleLockReturnedAttr(), handleLocksExcludedAttr(), handleManagedAttr(), handleMIGServerRoutineAttr(), handleMinSizeAttr(), handleMinVectorWidthAttr(), handleModeAttr(), handleMSAllocatorAttr(), handleMSInheritanceAttr(), handleNakedAttr(), handleNoBuiltinAttr(), handleNoCfCheckAttr(), handleNoDebugAttr(), handleNoEscapeAttr(), handleNoMergeAttr(), handleNonNullAttr(), handleNonNullAttrParameter(), handleNoRandomizeLayoutAttr(), handleNoReturnAttr(), handleNoSanitizeAttr(), handleNoSanitizeSpecificAttr(), handleNSErrorDomain(), handleObjCBoxable(), handleObjCBridgeAttr(), handleObjCBridgeMutableAttr(), handleObjCBridgeRelatedAttr(), handleObjCDesignatedInitializer(), handleObjCDirectAttr(), handleObjCDirectMembersAttr(), handleObjCExternallyRetainedAttr(), handleObjCIndependentClass(), handleObjCMethodFamilyAttr(), handleObjCNSObject(), handleObjCOwnershipAttr(), handleObjCPreciseLifetimeAttr(), handleObjCRequiresSuperAttr(), handleObjCReturnsInnerPointerAttr(), handleObjCRuntimeName(), handleObjCSuppresProtocolAttr(), handleOpenCLAccessAttr(), handleOpenCLNoSVMAttr(), handleOptimizeNoneAttr(), handleOwnershipAttr(), handlePackedAttr(), handleParamTypestateAttr(), handlePassObjectSizeAttr(), handlePatchableFunctionEntryAttr(), handlePreferredName(), handlePtGuardedByAttr(), handlePtGuardedVarAttr(), handleRandomizeLayoutAttr(), handleReleaseCapabilityAttr(), handleRequiresCapabilityAttr(), handleRestrictAttr(), handleReturnsNonNullAttr(), handleReturnTypestateAttr(), handleSectionAttr(), handleSentinelAttr(), handleSetTypestateAttr(), handleSharedAttr(), handleSharedTrylockFunctionAttr(), handleSimpleAttribute(), handleSimpleAttributeOrDiagnose(), handleStandardNoReturnAttr(), handleSubGroupSize(), handleSuppressAttr(), handleSwiftAsyncAttr(), handleSwiftAsyncError(), handleSwiftAsyncName(), handleSwiftAttrAttr(), handleSwiftBridge(), handleSwiftError(), handleSwiftName(), handleSwiftNewType(), handleSYCLKernelAttr(), handleTargetAttr(), handleTargetClonesAttr(), handleTargetVersionAttr(), handleTestTypestateAttr(), handleTLSModelAttr(), handleTransparentUnionAttr(), handleTryAcquireCapabilityAttr(), handleTypeTagForDatatypeAttr(), handleUninitializedAttr(), handleUnsafeBufferUsage(), handleUnusedAttr(), handleUuidAttr(), handleVecReturnAttr(), handleVecTypeHint(), handleVisibilityAttr(), handleWarnUnusedResult(), handleWeakImportAttr(), handleWeakRefAttr(), handleWebAssemblyExportNameAttr(), handleWebAssemblyImportModuleAttr(), handleWebAssemblyImportNameAttr(), handleWorkGroupSize(), handleX86ForceAlignArgPointerAttr(), handleXRayLogArgsAttr(), handleXReturnsXRetainedAttr(), handleZeroCallUsedRegsAttr(), clang::AttributeCommonInfo::IgnoredAttribute, clang::AttributeCommonInfo::isClangScope(), clang::AttributeCommonInfo::isCXX11Attribute(), clang::AttributeCommonInfo::isDeclspecAttribute(), clang::ParsedAttr::isInvalid(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), clang::AttributeCommonInfo::isStandardAttributeSyntax(), clang::ParsedAttr::isStmtAttr(), clang::ParsedAttr::isTypeAttr(), clang::ParsedAttr::isUsedAsTypeAttr(), isValidOSObjectOutParameter(), MustDelayAttributeArguments(), clang::ParsedAttrInfo::NotHandled, parsedAttrToRetainOwnershipKind(), clang::ParsedAttr::slidesFromDeclToDeclSpecLegacyBehavior(), clang::SwiftAsyncContext, clang::SwiftContext, clang::SwiftErrorResult, clang::SwiftIndirectResult, and clang::AttributeCommonInfo::UnknownAttribute.
Referenced by clang::Sema::ProcessAccessDeclAttributeList(), and clang::Sema::ProcessDeclAttributeList().
RISCVAliasValid()
static bool RISCVAliasValid (unsigned BuiltinID, StringRef AliasName) static
Definition at line 5832 of file SemaDeclAttr.cpp.
References clang::RISCV::FirstRVVBuiltin, and clang::RISCV::LastRVVBuiltin.
Referenced by handleBuiltinAliasAttr().
threadSafetyCheckIsPointer()
static bool threadSafetyCheckIsPointer (Sema & S, const Decl * D, const ParsedAttr & AL) static
Check if passed in Decl is a pointer type.
Note that this function may produce an error message.
Returns
true if the Decl is a pointer type; false otherwise
Definition at line 471 of file SemaDeclAttr.cpp.
References clang::cast(), clang::Sema::Diag(), clang::Type::getAs(), clang::AttributeCommonInfo::getLoc(), clang::Type::isAnyPointerType(), and threadSafetyCheckIsSmartPointer().
Referenced by handlePtGuardedByAttr(), and handlePtGuardedVarAttr().
threadSafetyCheckIsSmartPointer()
static bool threadSafetyCheckIsSmartPointer (Sema & S, const RecordType * RT) static
Definition at line 435 of file SemaDeclAttr.cpp.
References clang::Sema::Context, clang::ASTContext::DeclarationNames, clang::DeclarationNameTable::getCXXOperatorName(), and clang::Result.
Referenced by checkRecordTypeForCapability(), and threadSafetyCheckIsPointer().
tryMakeVariablePseudoStrong()
static bool tryMakeVariablePseudoStrong (Sema & S, VarDecl * VD, bool DiagnoseFailure) static
Definition at line 8446 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::DeclaratorDecl::getBeginLoc(), clang::Type::getObjCARCImplicitLifetime(), clang::Qualifiers::getObjCLifetime(), clang::QualType::getQualifiers(), clang::ValueDecl::getType(), clang::Type::isObjCRetainableType(), clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::VarDecl::setARCPseudoStrong(), clang::ValueDecl::setType(), and clang::QualType::withConst().
Referenced by handleObjCExternallyRetainedAttr().
typeHasCapability()
static bool typeHasCapability (Sema & S, QualType Ty) static
Definition at line 552 of file SemaDeclAttr.cpp.
References checkRecordTypeForCapability(), and checkTypedefTypeForCapability().
Referenced by checkAcquireOrderAttrCommon(), checkAttrArgsAreCapabilityObjs(), and isCapabilityExpr().
validateAlignasAppliedType()
static bool validateAlignasAppliedType (Sema & S, Decl * D, const AlignedAttr & Attr, SourceLocation AttrLoc) static
Perform checking of type validity.
C++11 [dcl.align]p1: An alignment-specifier may be applied to a variable or to a class data member, but it shall not be applied to a bit-field, a function parameter, the formal parameter of a catch clause, or a variable declared with the register storage class specifier. An alignment-specifier may also be applied to the declaration of a class or enumeration type. CWG 2354: CWG agreed to remove permission for alignas to be applied to enumerations. C11 6.7.5/2: An alignment attribute shall not be specified in a declaration of a typedef, or a bit-field, or a function, or a parameter, or an object declared with the register storage-class specifier.
Definition at line 4410 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), clang::ExpectedVariableFieldOrTag, clang::ExpectedVariableOrField, clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::SC_Register.
Referenced by clang::Sema::AddAlignedAttr(), and clang::Sema::AddAlignedAttr().
validateSwiftFunctionName()
static bool validateSwiftFunctionName (Sema & S, const ParsedAttr & AL, SourceLocation Loc, StringRef Name, unsigned & SwiftParamCount, bool & IsSingleParamInit) static
Definition at line 6584 of file SemaDeclAttr.cpp.
References clang::Sema::Diag(), and clang::isValidAsciiIdentifier().
Referenced by clang::Sema::DiagnoseSwiftName().
versionsMatch()
static bool versionsMatch (const VersionTuple & X, const VersionTuple & Y, bool BeforeIsOkay) static
Check whether the two versions match.
If either version tuple is empty, then they are assumed to match. If BeforeIsOkay is true, then X can be less than or equal to Y.
Definition at line 2426 of file SemaDeclAttr.cpp.
References X.