clang: lib/Sema/SemaTemplate.cpp File Reference
SemaTemplate.cpp File Reference
#include "TreeTransform.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/TypeVisitor.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/DiagnosticSema.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/Stack.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include "clang/Sema/TemplateDeduction.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include <iterator>
#include <optional>
#include "clang/AST/TypeNodes.inc"
Macros
#define TYPE(Class, Parent)
#define ABSTRACT_TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Parent)
Enumerations
enum NullPointerValueKind { NPV_NotNullPointer , NPV_NullPointer , NPV_Error }
Functions
static TemplateArgumentLoc translateTemplateArgument (Sema &SemaRef, const ParsedTemplateArgument &Arg)
static void maybeDiagnoseTemplateParameterShadow (Sema &SemaRef, Scope *S, SourceLocation Loc, IdentifierInfo *Name)
static TemplateArgumentListInfo makeTemplateArgumentListInfo (Sema &S, TemplateIdAnnotation &TemplateId)
Convert the parser's template argument list representation into our form.
template<typename ArgumentLocAppender >
static ExprResult formImmediatelyDeclaredConstraint (Sema &S, NestedNameSpecifierLoc NS, DeclarationNameInfo NameInfo, ConceptDecl *NamedConcept, SourceLocation LAngleLoc, SourceLocation RAngleLoc, QualType ConstrainedType, SourceLocation ParamNameLoc, ArgumentLocAppender Appender, SourceLocation EllipsisLoc)
static void SetNestedNameSpecifier (Sema &S, TagDecl *T, const CXXScopeSpec &SS)
static bool DiagnoseDefaultTemplateArgument (Sema &S, Sema::TemplateParamListContext TPC, SourceLocation ParamLoc, SourceRange DefArgRange)
Diagnose the presence of a default template argument on a template parameter, which is ill-formed in certain contexts.
static bool DiagnoseUnexpandedParameterPacks (Sema &S, TemplateTemplateParmDecl *TTP)
Check for unexpanded parameter packs within the template parameters of a template template parameter, recursively.
static bool DependsOnTemplateParameters (QualType T, TemplateParameterList *Params)
Determines whether a given type depends on the given parameter list.
static SourceRange getRangeOfTypeInNestedNameSpecifier (ASTContext &Context, QualType T, const CXXScopeSpec &SS)
static QualType checkBuiltinTemplateIdType (Sema &SemaRef, BuiltinTemplateDecl *BTD, ArrayRef< TemplateArgument > Converted, SourceLocation TemplateLoc, TemplateArgumentListInfo &TemplateArgs)
static bool isEnableIfAliasTemplate (TypeAliasTemplateDecl *AliasTemplate)
Determine whether this alias template is "enable_if_t".
static void collectConjunctionTerms (Expr *Clause, SmallVectorImpl< Expr * > &Terms)
Collect all of the separable terms in the given condition, which might be a conjunction.
static Expr * lookThroughRangesV3Condition (Preprocessor &PP, Expr *Cond)
static bool CheckTemplateSpecializationScope (Sema &S, NamedDecl *Specialized, NamedDecl *PrevDecl, SourceLocation Loc, bool IsPartialSpecialization)
Check whether a specialization is well-formed in the current context.
static TemplateSpecializationKind getTemplateSpecializationKind (Decl *D)
Determine what kind of template specialization the given declaration is.
static bool isTemplateArgumentTemplateParameter (const TemplateArgument &Arg, unsigned Depth, unsigned Index)
static bool isSameAsPrimaryTemplate (TemplateParameterList *Params, ArrayRef< TemplateArgument > Args)
template<typename PartialSpecDecl >
static void checkMoreSpecializedThanPrimary (Sema &S, PartialSpecDecl *Partial)
static void noteNonDeducibleParameters (Sema &S, TemplateParameterList *TemplateParams, const llvm::SmallBitVector &DeducibleParams)
template<typename PartialSpecDecl >
static void checkTemplatePartialSpecialization (Sema &S, PartialSpecDecl *Partial)
static TypeSourceInfo * SubstDefaultTemplateArgument (Sema &SemaRef, TemplateDecl *Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, TemplateTypeParmDecl *Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted)
Substitute template arguments into the default template argument for the given template type parameter.
static ExprResult SubstDefaultTemplateArgument (Sema &SemaRef, TemplateDecl *Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, NonTypeTemplateParmDecl *Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted)
Substitute template arguments into the default template argument for the given non-type template parameter.
static TemplateName SubstDefaultTemplateArgument (Sema &SemaRef, TemplateDecl *Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, TemplateTemplateParmDecl *Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted, NestedNameSpecifierLoc &QualifierLoc)
Substitute template arguments into the default template argument for the given template template parameter.
static TemplateArgumentLoc convertTypeTemplateArgumentToTemplate (ASTContext &Context, TypeLoc TLoc)
Convert a template-argument that we parsed as a type into a template, if possible.
template<typename TemplateParmDecl >
static bool diagnoseMissingArgument (Sema &S, SourceLocation Loc, TemplateDecl *TD, const TemplateParmDecl *D, TemplateArgumentListInfo &Args)
Diagnose a missing template argument.
static NullPointerValueKind isNullPointerValueTemplateArgument (Sema &S, NonTypeTemplateParmDecl *Param, QualType ParamType, Expr *Arg, Decl *Entity=nullptr)
Determine whether the given template argument is a null pointer value of the appropriate type.
static bool CheckTemplateArgumentIsCompatibleWithParameter (Sema &S, NonTypeTemplateParmDecl *Param, QualType ParamType, Expr *ArgIn, Expr *Arg, QualType ArgType)
Checks whether the given template argument is compatible with its template parameter.
static bool CheckTemplateArgumentAddressOfObjectOrFunction (Sema &S, NonTypeTemplateParmDecl *Param, QualType ParamType, Expr *ArgIn, TemplateArgument &SugaredConverted, TemplateArgument &CanonicalConverted)
Checks whether the given template argument is the address of an object or function according to C++ [temp.arg.nontype]p1.
static bool CheckTemplateArgumentPointerToMember (Sema &S, NonTypeTemplateParmDecl *Param, QualType ParamType, Expr *&ResultArg, TemplateArgument &SugaredConverted, TemplateArgument &CanonicalConverted)
Checks whether the given template argument is a pointer to member constant according to C++ [temp.arg.nontype]p1.
static void DiagnoseTemplateParameterListArityMismatch (Sema &S, TemplateParameterList *New, TemplateParameterList *Old, Sema::TemplateParameterListEqualKind Kind, SourceLocation TemplateArgLoc)
Diagnose a known arity mismatch when comparing template argument lists.
static bool MatchTemplateParameterKind (Sema &S, NamedDecl *New, const NamedDecl *NewInstFrom, NamedDecl *Old, const NamedDecl *OldInstFrom, bool Complain, Sema::TemplateParameterListEqualKind Kind, SourceLocation TemplateArgLoc)
Match two template parameters within template parameter lists.
static SourceRange findTemplateParameterInType (unsigned Depth, Expr *E)
static SourceRange findTemplateParameter (unsigned Depth, TypeLoc TL)
static bool CheckNonTypeTemplatePartialSpecializationArgs (Sema &S, SourceLocation TemplateNameLoc, NonTypeTemplateParmDecl *Param, const TemplateArgument *Args, unsigned NumArgs, bool IsDefaultArgument)
Subroutine of Sema::CheckTemplatePartialSpecializationArgs that checks non-type template partial specialization arguments.
static void StripImplicitInstantiation (NamedDecl *D, bool MinGW)
Strips various properties off an implicit instantiation that has just been explicitly specialized.
static SourceLocation DiagLocForExplicitInstantiation (NamedDecl *D, SourceLocation PointOfInstantiation)
Compute the diagnostic location for an explicit instantiation.
template<typename DeclT >
static void completeMemberSpecializationImpl (Sema &S, DeclT *OrigD, SourceLocation Loc)
Complete the explicit specialization of a member of a class template by updating the instantiated member to be marked as an explicit specialization.
static bool CheckExplicitInstantiationScope (Sema &S, NamedDecl *D, SourceLocation InstLoc, bool WasQualifiedName)
Check the scope of an explicit instantiation.
static bool CheckExplicitInstantiation (Sema &S, NamedDecl *D, SourceLocation InstLoc, bool WasQualifiedName, TemplateSpecializationKind TSK)
Common checks for whether an explicit instantiation of D is valid.
static bool ScopeSpecifierHasTemplateId (const CXXScopeSpec &SS)
Determine whether the given scope specifier has a template-id in it.
static void dllExportImportClassTemplateSpecialization (Sema &S, ClassTemplateSpecializationDecl *Def)
Make a dllexport or dllimport attr on a class template specialization take effect.
static bool isEnableIf (NestedNameSpecifierLoc NNS, const IdentifierInfo &II, SourceRange &CondRange, Expr *&Cond)
Determine whether this failed name lookup should be treated as being disabled by a usage of std::enable_if.
Macro Definition Documentation
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Parent)
Value:
    bool Visit##Class##Type(const Class##Type *) { return false; }
Definition at line 6235 of file SemaTemplate.cpp.
NON_CANONICAL_TYPE
#define NON_CANONICAL_TYPE (Class, Parent)
Value:
    bool Visit##Class##Type(const Class##Type *) { return false; }
Definition at line 6237 of file SemaTemplate.cpp.
TYPE
#define TYPE (Class, Parent)
Value:
    bool Visit##Class##Type(const Class##Type *);
Definition at line 6233 of file SemaTemplate.cpp.
Enumeration Type Documentation
NullPointerValueKind
enum NullPointerValueKind
Enumerator
NPV_NotNullPointer
NPV_NullPointer
NPV_Error
Definition at line 6528 of file SemaTemplate.cpp.
Function Documentation
checkBuiltinTemplateIdType()
static QualType checkBuiltinTemplateIdType (Sema & SemaRef, BuiltinTemplateDecl * BTD, ArrayRef< TemplateArgument > Converted, SourceLocation TemplateLoc, TemplateArgumentListInfo & TemplateArgs) static
Definition at line 3643 of file SemaTemplate.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::BTK__make_integer_seq, clang::BTK__type_pack_element, clang::Sema::CheckTemplateIdType(), clang::Sema::Context, clang::Sema::Diag(), clang::TemplateArgument::getAsIntegral(), clang::Sema::getASTContext(), clang::BuiltinTemplateDecl::getBuiltinTemplateKind(), clang::ASTContext::getCanonicalTemplateSpecializationType(), clang::Sema::getTrivialTemplateArgumentLoc(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::TemplateArgument::isDependent(), clang::Type::isDependentType(), clang::Type::isIntegralType(), and N.
Referenced by clang::Sema::CheckTemplateIdType().
CheckExplicitInstantiation()
static bool CheckExplicitInstantiation (Sema & S, NamedDecl * D, SourceLocation InstLoc, bool WasQualifiedName, TemplateSpecializationKind TSK) static
Common checks for whether an explicit instantiation of D is valid.
Definition at line 9875 of file SemaTemplate.cpp.
References CheckExplicitInstantiationScope(), clang::Sema::Diag(), clang::NamedDecl::getFormalLinkage(), clang::InternalLinkage, and clang::TSK_ExplicitInstantiationDeclaration.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), and clang::Sema::ActOnExplicitInstantiation().
CheckExplicitInstantiationScope()
static bool CheckExplicitInstantiationScope (Sema & S, NamedDecl * D, SourceLocation InstLoc, bool WasQualifiedName) static
Check the scope of an explicit instantiation.
Returns
true if a serious error occurs, false otherwise.
Definition at line 9823 of file SemaTemplate.cpp.
References clang::Sema::CurContext, clang::Sema::Diag(), clang::DeclContext::Encloses(), clang::Decl::getDeclContext(), clang::DeclContext::getEnclosingNamespaceContext(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::DeclContext::getRedeclContext(), clang::DeclContext::InEnclosingNamespaceSetOf(), and clang::DeclContext::isRecord().
Referenced by CheckExplicitInstantiation().
checkMoreSpecializedThanPrimary()
template<typename PartialSpecDecl > static void checkMoreSpecializedThanPrimary (Sema & S, PartialSpecDecl * Partial) static
Definition at line 4399 of file SemaTemplate.cpp.
References clang::Sema::Diag(), Diag(), clang::TemplateDecl::getAssociatedConstraints(), clang::Sema::getDiagnostics(), clang::Decl::getLocation(), clang::sema::TemplateDeductionInfo::hasSFINAEDiagnostic(), clang::isa(), clang::Sema::isMoreSpecializedThanPrimary(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), and clang::sema::TemplateDeductionInfo::takeSFINAEDiagnostic().
Referenced by checkTemplatePartialSpecialization().
CheckNonTypeTemplatePartialSpecializationArgs()
static bool CheckNonTypeTemplatePartialSpecializationArgs (Sema & S, SourceLocation TemplateNameLoc, NonTypeTemplateParmDecl * Param, const TemplateArgument * Args, unsigned NumArgs, bool IsDefaultArgument) static
Subroutine of Sema::CheckTemplatePartialSpecializationArgs that checks non-type template partial specialization arguments.
Definition at line 8488 of file SemaTemplate.cpp.
References CheckNonTypeTemplatePartialSpecializationArgs(), clang::Sema::Diag(), clang::TemplateArgument::Expression, findTemplateParameter(), findTemplateParameterInType(), clang::TemplateArgument::getAsExpr(), clang::SourceRange::getBegin(), clang::Stmt::getBeginLoc(), getKind(), clang::SourceRange::isValid(), and clang::TemplateArgument::Pack.
Referenced by CheckNonTypeTemplatePartialSpecializationArgs(), and clang::Sema::CheckTemplatePartialSpecializationArgs().
CheckTemplateArgumentAddressOfObjectOrFunction()
static bool CheckTemplateArgumentAddressOfObjectOrFunction (Sema & S, NonTypeTemplateParmDecl * Param, QualType ParamType, Expr * ArgIn, TemplateArgument & SugaredConverted, TemplateArgument & CanonicalConverted) static
Checks whether the given template argument is the address of an object or function according to C++ [temp.arg.nontype]p1.
Definition at line 6699 of file SemaTemplate.cpp.
References CheckTemplateArgumentIsCompatibleWithParameter(), clang::Sema::Context, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), clang::Sema::Diag(), clang::ASTContext::getArrayDecayedType(), clang::Stmt::getBeginLoc(), clang::Decl::getCanonicalDecl(), clang::ASTContext::getCanonicalTemplateArgument(), clang::ASTContext::getCanonicalType(), clang::Expr::getExprLoc(), clang::NamedDecl::getFormalLinkage(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::VarDecl::getTLSKind(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::NamedDecl::hasLinkage(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::IgnoreImpCasts(), clang::Expr::IgnoreParenCasts(), clang::InternalLinkage, clang::Invalid, clang::Type::isArrayType(), isNullPointerValueTemplateArgument(), clang::Type::isNullPtrType(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::SourceLocation::isValid(), clang::Expr::isValueDependent(), clang::Sema::MarkAnyDeclReferenced(), NPV_Error, NPV_NotNullPointer, and NPV_NullPointer.
Referenced by clang::Sema::CheckTemplateArgument().
CheckTemplateArgumentIsCompatibleWithParameter()
static bool CheckTemplateArgumentIsCompatibleWithParameter (Sema & S, NonTypeTemplateParmDecl * Param, QualType ParamType, Expr * ArgIn, Expr * Arg, QualType ArgType) static
Checks whether the given template argument is compatible with its template parameter.
Definition at line 6642 of file SemaTemplate.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::Stmt::getBeginLoc(), clang::QualType::getNonReferenceType(), clang::PointerType::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isFunctionType(), clang::Type::isPointerType(), clang::Sema::IsQualificationConversion(), and clang::Type::isReferenceType().
Referenced by CheckTemplateArgumentAddressOfObjectOrFunction().
CheckTemplateArgumentPointerToMember()
static bool CheckTemplateArgumentPointerToMember (Sema & S, NonTypeTemplateParmDecl * Param, QualType ParamType, Expr *& ResultArg, TemplateArgument & SugaredConverted, TemplateArgument & CanonicalConverted) static
Checks whether the given template argument is a pointer to member constant according to C++ [temp.arg.nontype]p1.
Definition at line 6966 of file SemaTemplate.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Decl::getCanonicalDecl(), clang::ASTContext::getCanonicalTemplateArgument(), clang::ASTContext::getCanonicalType(), clang::DeclRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), clang::DeclRefExpr::getQualifier(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::Expr::getValueKind(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::IgnoreImpCasts(), clang::Sema::ImpCastExprToType(), clang::Invalid, clang::Type::isMemberPointerType(), isNullPointerValueTemplateArgument(), clang::Sema::IsQualificationConversion(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), NPV_Error, NPV_NotNullPointer, and NPV_NullPointer.
Referenced by clang::Sema::CheckTemplateArgument().
checkTemplatePartialSpecialization()
template<typename PartialSpecDecl > static void checkTemplatePartialSpecialization (Sema & S, PartialSpecDecl * Partial) static
Definition at line 4451 of file SemaTemplate.cpp.
References checkMoreSpecializedThanPrimary(), clang::Sema::Diag(), clang::TemplateParameterList::getDepth(), clang::isa(), clang::Sema::MarkUsedTemplateParameters(), noteNonDeducibleParameters(), and clang::TemplateParameterList::size().
Referenced by clang::Sema::CheckTemplatePartialSpecialization(), and clang::Sema::CheckTemplatePartialSpecialization().
CheckTemplateSpecializationScope()
static bool CheckTemplateSpecializationScope (Sema & S, NamedDecl * Specialized, NamedDecl * PrevDecl, SourceLocation Loc, bool IsPartialSpecialization) static
Check whether a specialization is well-formed in the current context.
This routine determines whether a template specialization can be declared in the current context (C++ [temp.expl.spec]p2).
Parameters
S the semantic analysis object for which this check is being performed.
Specialized the entity being specialized or instantiated, which may be a kind of template (class template, function template, etc.) or a member of a class template (member function, static data member, member class).
PrevDecl the previous declaration of this entity, if any.
Loc the location of the explicit specialization or instantiation of this entity.
IsPartialSpecialization whether this is a partial specialization of a class template.
Returns
true if there was an error that we cannot recover from, false otherwise.
Definition at line 8394 of file SemaTemplate.cpp.
References clang::cast(), clang::Sema::CurContext, clang::Sema::Diag(), Diag(), clang::DeclContext::Encloses(), clang::DeclContext::Equals(), clang::Decl::getDeclContext(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::DeclContext::getRedeclContext(), clang::DeclContext::isFileContext(), clang::DeclContext::isFunctionOrMethod(), and clang::DeclContext::isRecord().
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckFunctionTemplateSpecialization(), and clang::Sema::CheckMemberSpecialization().
collectConjunctionTerms()
static void collectConjunctionTerms (Expr * Clause, SmallVectorImpl< Expr * > & Terms) static
Collect all of the separable terms in the given condition, which might be a conjunction.
FIXME: The right answer is to convert the logical expression into disjunctive normal form, so we can find the first failed term within each possible clause.
Definition at line 3740 of file SemaTemplate.cpp.
References collectConjunctionTerms().
Referenced by collectConjunctionTerms(), and clang::Sema::findFailedBooleanCondition().
completeMemberSpecializationImpl()
template<typename DeclT > static void completeMemberSpecializationImpl (Sema & S, DeclT * OrigD, SourceLocation Loc) static
Complete the explicit specialization of a member of a class template by updating the instantiated member to be marked as an explicit specialization.
Parameters
OrigD The member declaration instantiated from the template.
Loc The location of the explicit specialization of the member.
Definition at line 9789 of file SemaTemplate.cpp.
References clang::TSK_ExplicitSpecialization, and clang::TSK_ImplicitInstantiation.
Referenced by clang::Sema::CompleteMemberSpecialization().
convertTypeTemplateArgumentToTemplate()
static TemplateArgumentLoc convertTypeTemplateArgumentToTemplate (ASTContext & Context, TypeLoc TLoc) static
Convert a template-argument that we parsed as a type into a template, if possible.
C++ permits injected-class-names to perform dual service as template template arguments and as template type arguments.
Definition at line 5535 of file SemaTemplate.cpp.
References clang::TypeLoc::getAs().
Referenced by clang::Sema::CheckTemplateArgument().
DependsOnTemplateParameters()
static bool DependsOnTemplateParameters (QualType T, TemplateParameterList * Params) static
Determines whether a given type depends on the given parameter list.
Definition at line 3195 of file SemaTemplate.cpp.
References clang::TemplateParameterList::size().
Referenced by clang::Sema::MatchTemplateParametersToScopeSpecifier().
DiagLocForExplicitInstantiation()
static SourceLocation DiagLocForExplicitInstantiation (NamedDecl * D, SourceLocation PointOfInstantiation) static
Compute the diagnostic location for an explicit instantiation.
Definition at line 9106 of file SemaTemplate.cpp.
References clang::SourceLocation::isValid().
Referenced by clang::Sema::CheckSpecializationInstantiationRedecl().
DiagnoseDefaultTemplateArgument()
static bool DiagnoseDefaultTemplateArgument (Sema & S, Sema::TemplateParamListContext TPC, SourceLocation ParamLoc, SourceRange DefArgRange) static
Diagnose the presence of a default template argument on a template parameter, which is ill-formed in certain contexts.
Returns
true if the default template argument should be dropped.
Definition at line 2701 of file SemaTemplate.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Sema::TPC_ClassTemplate, clang::Sema::TPC_ClassTemplateMember, clang::Sema::TPC_FriendClassTemplate, clang::Sema::TPC_FriendFunctionTemplate, clang::Sema::TPC_FriendFunctionTemplateDefinition, clang::Sema::TPC_FunctionTemplate, clang::Sema::TPC_TypeAliasTemplate, and clang::Sema::TPC_VarTemplate.
Referenced by clang::Sema::CheckTemplateParameterList().
diagnoseMissingArgument()
template<typename TemplateParmDecl > static bool diagnoseMissingArgument (Sema & S, SourceLocation Loc, TemplateDecl * TD, const TemplateParmDecl * D, TemplateArgumentListInfo & Args) static
Diagnose a missing template argument.
Definition at line 5843 of file SemaTemplate.cpp.
References clang::cast(), clang::Sema::DefaultArgument, clang::Sema::Diag(), clang::Sema::diagnoseMissingImport(), clang::Decl::getLocation(), clang::NamedDecl::getMostRecentDecl(), clang::TemplateParameterList::getSourceRange(), clang::Sema::getTemplateNameKindForDiagnostics(), clang::TemplateDecl::getTemplateParameters(), clang::Sema::hasReachableDefaultArgument(), and int.
Referenced by clang::Sema::CheckTemplateArgumentList().
DiagnoseTemplateParameterListArityMismatch()
static void DiagnoseTemplateParameterListArityMismatch (Sema & S, TemplateParameterList * New, TemplateParameterList * Old, Sema::TemplateParameterListEqualKind Kind, SourceLocation TemplateArgLoc) static
Diagnose a known arity mismatch when comparing template argument lists.
Definition at line 8159 of file SemaTemplate.cpp.
References clang::Sema::Diag(), clang::TemplateParameterList::getRAngleLoc(), clang::TemplateParameterList::getTemplateLoc(), clang::SourceLocation::isValid(), clang::TemplateParameterList::size(), and clang::Sema::TPL_TemplateMatch.
Referenced by clang::Sema::TemplateParameterListsAreEqual().
DiagnoseUnexpandedParameterPacks()
static bool DiagnoseUnexpandedParameterPacks (Sema & S, TemplateTemplateParmDecl * TTP) static
Check for unexpanded parameter packs within the template parameters of a template template parameter, recursively.
Definition at line 2755 of file SemaTemplate.cpp.
References clang::Sema::DiagnoseUnexpandedParameterPack(), DiagnoseUnexpandedParameterPacks(), clang::TemplateParameterList::getParam(), clang::TemplateDecl::getTemplateParameters(), clang::TemplateTemplateParmDecl::isParameterPack(), N, P, clang::TemplateParameterList::size(), clang::Sema::UPPC_NonTypeTemplateParameterType, and clang::Sema::UPPC_TypeConstraint.
Referenced by clang::Sema::checkExceptionSpecification(), and DiagnoseUnexpandedParameterPacks().
dllExportImportClassTemplateSpecialization()
static void dllExportImportClassTemplateSpecialization (Sema & S, ClassTemplateSpecializationDecl * Def) static
Make a dllexport or dllimport attr on a class template specialization take effect.
Definition at line 9920 of file SemaTemplate.cpp.
References clang::CXXRecordDecl::bases(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::DelayedDllExportClasses, clang::TypeDecl::getBeginLoc(), clang::getDLLAttr(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), and clang::Sema::referenceDLLExportedClassMethods().
Referenced by clang::Sema::ActOnExplicitInstantiation().
findTemplateParameter()
static SourceRange findTemplateParameter (unsigned Depth, TypeLoc TL) static
Definition at line 8476 of file SemaTemplate.cpp.
References clang::TypeLoc::getSourceRange(), clang::TypeLoc::getType(), clang::Type::isDependentType(), and clang::SourceLocation::isInvalid().
Referenced by CheckNonTypeTemplatePartialSpecializationArgs().
findTemplateParameterInType()
static SourceRange findTemplateParameterInType (unsigned Depth, Expr * E) static
Definition at line 8466 of file SemaTemplate.cpp.
References clang::Stmt::getSourceRange(), clang::SourceLocation::isInvalid(), and clang::Expr::isTypeDependent().
Referenced by CheckNonTypeTemplatePartialSpecializationArgs().
formImmediatelyDeclaredConstraint()
template<typename ArgumentLocAppender > static ExprResult formImmediatelyDeclaredConstraint (Sema & S, NestedNameSpecifierLoc NS, DeclarationNameInfo NameInfo, ConceptDecl * NamedConcept, SourceLocation LAngleLoc, SourceLocation RAngleLoc, QualType ConstrainedType, SourceLocation ParamNameLoc, ArgumentLocAppender Appender, SourceLocation EllipsisLoc) static
Definition at line 1179 of file SemaTemplate.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::CXXScopeSpec::Adopt(), clang::Sema::BuildCXXFoldExpr(), clang::Sema::CheckConceptTemplateId(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getTrivialTemplateArgumentLoc(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::SourceLocation::isValid(), clang::TemplateArgumentListInfo::setLAngleLoc(), and clang::TemplateArgumentListInfo::setRAngleLoc().
Referenced by clang::Sema::AttachTypeConstraint(), and clang::Sema::AttachTypeConstraint().
getRangeOfTypeInNestedNameSpecifier()
static SourceRange getRangeOfTypeInNestedNameSpecifier (ASTContext & Context, QualType T, const CXXScopeSpec & SS) static
Definition at line 3206 of file SemaTemplate.cpp.
References clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getPrefix(), clang::CXXScopeSpec::getScopeRep(), clang::TypeLoc::getSourceRange(), clang::NestedNameSpecifierLoc::getTypeLoc(), clang::ASTContext::hasSameUnqualifiedType(), and clang::CXXScopeSpec::location_data().
Referenced by clang::Sema::MatchTemplateParametersToScopeSpecifier().
getTemplateSpecializationKind()
static TemplateSpecializationKind getTemplateSpecializationKind (Decl * D) static
Determine what kind of template specialization the given declaration is.
Definition at line 8356 of file SemaTemplate.cpp.
References clang::TSK_Undeclared.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnVarTemplateSpecialization(), clang::Sema::CheckMemberSpecialization(), and clang::Sema::CheckSpecializationInstantiationRedecl().
isEnableIf()
static bool isEnableIf (NestedNameSpecifierLoc NNS, const IdentifierInfo & II, SourceRange & CondRange, Expr *& Cond) static
Determine whether this failed name lookup should be treated as being disabled by a usage of std::enable_if.
Definition at line 10913 of file SemaTemplate.cpp.
References clang::Cond, clang::TemplateArgument::Expression, clang::TemplateSpecializationTypeLoc::getArgLoc(), clang::TemplateArgumentLoc::getArgument(), clang::TypeLoc::getAs(), clang::DeclarationName::getAsIdentifierInfo(), clang::NestedNameSpecifier::getAsType(), clang::NamedDecl::getDeclName(), clang::TemplateArgument::getKind(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::TemplateSpecializationTypeLoc::getNumArgs(), clang::TemplateArgumentLoc::getSourceExpression(), clang::TemplateArgumentLoc::getSourceRange(), clang::NestedNameSpecifierLoc::getTypeLoc(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::Expr::IgnoreParenCasts(), and clang::IdentifierInfo::isStr().
Referenced by clang::Sema::CheckTypenameType().
isEnableIfAliasTemplate()
static bool isEnableIfAliasTemplate (TypeAliasTemplateDecl * AliasTemplate) static
Determine whether this alias template is "enable_if_t".
libc++ >=14 uses "__enable_if_t" in C++11 mode.
Definition at line 3729 of file SemaTemplate.cpp.
References clang::AliasTemplate.
Referenced by clang::Sema::CheckTemplateIdType().
isNullPointerValueTemplateArgument()
static NullPointerValueKind isNullPointerValueTemplateArgument (Sema & S, NonTypeTemplateParmDecl * Param, QualType ParamType, Expr * Arg, Decl * Entity = nullptr) static
Determine whether the given template argument is a null pointer value of the appropriate type.
Definition at line 6537 of file SemaTemplate.cpp.
References clang::Sema::Context, clang::FixItHint::CreateInsertion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Expr::EvalStatus::Diag, clang::Sema::Diag(), clang::Expr::EvaluateAsRValue(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::APValue::getAsString(), clang::QualType::getAsString(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::Sema::getLocForEndOfToken(), clang::APValue::getLValueBase(), clang::APValue::getMemberPointerDecl(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::EvalStatus::HasSideEffects, clang::Sema::isCompleteType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::APValue::isLValue(), clang::APValue::isMemberPointer(), clang::APValue::isNullPointer(), clang::Expr::isNullPointerConstant(), clang::Type::isNullPtrType(), clang::Sema::IsQualificationConversion(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), N, clang::Expr::NPC_NeverValueDependent, NPV_Error, NPV_NotNullPointer, NPV_NullPointer, and clang::Expr::EvalResult::Val.
Referenced by clang::Sema::CheckTemplateArgument(), CheckTemplateArgumentAddressOfObjectOrFunction(), and CheckTemplateArgumentPointerToMember().
isSameAsPrimaryTemplate()
static bool isSameAsPrimaryTemplate (TemplateParameterList * Params, ArrayRef< TemplateArgument > Args) static
Definition at line 4372 of file SemaTemplate.cpp.
References clang::TemplateParameterList::getDepth(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getPackExpansionPattern(), clang::TemplateParameterList::getParam(), clang::TemplateArgument::isPackExpansion(), clang::Decl::isParameterPack(), isTemplateArgumentTemplateParameter(), N, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_begin(), clang::TemplateArgument::pack_size(), and clang::TemplateParameterList::size().
Referenced by clang::Sema::ActOnVarTemplateSpecialization().
isTemplateArgumentTemplateParameter()
static bool isTemplateArgumentTemplateParameter (const TemplateArgument & Arg, unsigned Depth, unsigned Index) static
Definition at line 4335 of file SemaTemplate.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::Type::getAs(), clang::TemplateArgument::getAsExpr(), clang::TemplateName::getAsTemplateDecl(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::DeclRefExpr::getDecl(), clang::NonTypeTemplateParmDecl::getDepth(), clang::TemplateTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::TemplateTemplateParmDecl::getIndex(), clang::TemplateArgument::getKind(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
Referenced by isSameAsPrimaryTemplate().
lookThroughRangesV3Condition()
static Expr * lookThroughRangesV3Condition (Preprocessor & PP, Expr * Cond) static
Definition at line 3756 of file SemaTemplate.cpp.
References clang::Cond, clang::Preprocessor::getImmediateMacroName(), and clang::Expr::IgnoreParenImpCasts().
Referenced by clang::Sema::findFailedBooleanCondition().
makeTemplateArgumentListInfo()
static TemplateArgumentListInfo makeTemplateArgumentListInfo (Sema & S, TemplateIdAnnotation & TemplateId) static
Convert the parser's template argument list representation into our form.
Definition at line 1101 of file SemaTemplate.cpp.
References clang::TemplateIdAnnotation::getTemplateArgs(), clang::TemplateIdAnnotation::LAngleLoc, clang::TemplateIdAnnotation::NumArgs, clang::TemplateIdAnnotation::RAngleLoc, and clang::Sema::translateTemplateArguments().
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnVarTemplateSpecialization(), and clang::Sema::BuildTypeConstraint().
MatchTemplateParameterKind()
static bool MatchTemplateParameterKind (Sema & S, NamedDecl * New, const NamedDecl * NewInstFrom, NamedDecl * Old, const NamedDecl * OldInstFrom, bool Complain, Sema::TemplateParameterListEqualKind Kind, SourceLocation TemplateArgLoc) static
Match two template parameters within template parameter lists.
Definition at line 8008 of file SemaTemplate.cpp.
References clang::Sema::AreConstraintExpressionsEqual(), clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::Decl::getKind(), clang::Decl::getLocation(), clang::TemplateDecl::getTemplateParameters(), clang::ValueDecl::getType(), clang::ASTContext::getUnconstrainedType(), clang::ASTContext::hasSameType(), clang::isa(), clang::Type::isDependentType(), clang::Decl::isParameterPack(), clang::Decl::isTemplateParameterPack(), clang::SourceLocation::isValid(), clang::Sema::TemplateParameterListsAreEqual(), clang::Sema::TPL_TemplateMatch, clang::Sema::TPL_TemplateParamsEquivalent, clang::Sema::TPL_TemplateTemplateArgumentMatch, and clang::Sema::TPL_TemplateTemplateParmMatch.
Referenced by clang::Sema::TemplateParameterListsAreEqual().
maybeDiagnoseTemplateParameterShadow()
static void maybeDiagnoseTemplateParameterShadow (Sema & SemaRef, Scope * S, SourceLocation Loc, IdentifierInfo * Name) static
Definition at line 967 of file SemaTemplate.cpp.
References clang::Sema::DiagnoseTemplateParameterShadow(), clang::Sema::ForVisibleRedeclaration, clang::Decl::isTemplateParameter(), clang::Sema::LookupOrdinaryName, and clang::Sema::LookupSingleName().
Referenced by clang::Sema::ActOnNonTypeTemplateParameter(), clang::Sema::ActOnTemplateTemplateParameter(), and clang::Sema::ActOnTypeParameter().
noteNonDeducibleParameters()
static void noteNonDeducibleParameters (Sema & S, TemplateParameterList * TemplateParams, const llvm::SmallBitVector & DeducibleParams) static
Definition at line 4434 of file SemaTemplate.cpp.
References clang::Sema::Diag(), clang::TemplateParameterList::getParam(), and N.
Referenced by clang::Sema::CheckDeductionGuideTemplate(), and checkTemplatePartialSpecialization().
ScopeSpecifierHasTemplateId()
static bool ScopeSpecifierHasTemplateId (const CXXScopeSpec & SS) static
Determine whether the given scope specifier has a template-id in it.
Definition at line 9898 of file SemaTemplate.cpp.
References clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getPrefix(), clang::CXXScopeSpec::getScopeRep(), and clang::CXXScopeSpec::isSet().
Referenced by clang::Sema::ActOnExplicitInstantiation(), and clang::Sema::ActOnExplicitInstantiation().
SetNestedNameSpecifier()
static void SetNestedNameSpecifier (Sema & S, TagDecl * T, const CXXScopeSpec & SS) static
Definition at line 1814 of file SemaTemplate.cpp.
References clang::Sema::Context, clang::CXXScopeSpec::getWithLocInContext(), and clang::CXXScopeSpec::isSet().
StripImplicitInstantiation()
static void StripImplicitInstantiation (NamedDecl * D, bool MinGW) static
Strips various properties off an implicit instantiation that has just been explicitly specialized.
Definition at line 9093 of file SemaTemplate.cpp.
References clang::Decl::dropAttr().
Referenced by clang::Sema::CheckSpecializationInstantiationRedecl().
SubstDefaultTemplateArgument() [1/3]
static ExprResult SubstDefaultTemplateArgument (Sema & SemaRef, TemplateDecl * Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, NonTypeTemplateParmDecl * Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted) static
Substitute template arguments into the default template argument for the given non-type template parameter.
Parameters
SemaRef the semantic analysis object for which we are performing the substitution.
Template the template that we are synthesizing template arguments for.
TemplateLoc the location of the template name that started the template-id we are checking.
RAngleLoc the location of the right angle bracket ('>') that terminates the template-id.
Param the non-type template parameter whose default we are substituting into.
Converted the list of template arguments provided for template parameters that precede Param in the template parameter list.
Returns
the substituted template argument, or NULL if an error occurred.
Definition at line 5389 of file SemaTemplate.cpp.
References clang::MultiLevelTemplateArgumentList::addOuterTemplateArguments(), clang::Sema::ConstantEvaluated, clang::ExprError(), clang::Decl::getDeclContext(), clang::Sema::InstantiatingTemplate::isInvalid(), and clang::Sema::SubstExpr().
SubstDefaultTemplateArgument() [2/3]
static TemplateName SubstDefaultTemplateArgument (Sema & SemaRef, TemplateDecl * Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, TemplateTemplateParmDecl * Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted, NestedNameSpecifierLoc & QualifierLoc) static
Substitute template arguments into the default template argument for the given template template parameter.
Parameters
SemaRef the semantic analysis object for which we are performing the substitution.
Template the template that we are synthesizing template arguments for.
TemplateLoc the location of the template name that started the template-id we are checking.
RAngleLoc the location of the right angle bracket ('>') that terminates the template-id.
Param the template template parameter whose default we are substituting into.
Converted the list of template arguments provided for template parameters that precede Param in the template parameter list.
QualifierLoc Will be set to the nested-name-specifier (with source-location information) that precedes the template name.
Returns
the substituted template argument, or NULL if an error occurred.
Definition at line 5437 of file SemaTemplate.cpp.
References clang::MultiLevelTemplateArgumentList::addOuterTemplateArguments(), clang::Decl::getDeclContext(), clang::Sema::InstantiatingTemplate::isInvalid(), clang::Sema::SubstNestedNameSpecifierLoc(), and clang::Sema::SubstTemplateName().
SubstDefaultTemplateArgument() [3/3]
static TypeSourceInfo * SubstDefaultTemplateArgument (Sema & SemaRef, TemplateDecl * Template, SourceLocation TemplateLoc, SourceLocation RAngleLoc, TemplateTypeParmDecl * Param, ArrayRef< TemplateArgument > SugaredConverted, ArrayRef< TemplateArgument > CanonicalConverted) static
Substitute template arguments into the default template argument for the given template type parameter.
Parameters
SemaRef the semantic analysis object for which we are performing the substitution.
Template the template that we are synthesizing template arguments for.
TemplateLoc the location of the template name that started the template-id we are checking.
RAngleLoc the location of the right angle bracket ('>') that terminates the template-id.
Param the template template parameter whose default we are substituting into.
Converted the list of template arguments provided for template parameters that precede Param in the template parameter list.
Returns
the substituted template argument, or NULL if an error occurred.
Definition at line 5332 of file SemaTemplate.cpp.
References clang::MultiLevelTemplateArgumentList::addOuterTemplateArguments(), clang::Decl::getDeclContext(), clang::Sema::InstantiatingTemplate::isInvalid(), and clang::Sema::SubstType().
Referenced by clang::Sema::CheckTemplateArgumentList(), and clang::Sema::SubstDefaultTemplateArgumentIfAvailable().
translateTemplateArgument()
static TemplateArgumentLoc translateTemplateArgument (Sema & SemaRef, const ParsedTemplateArgument & Arg) static
Definition at line 924 of file SemaTemplate.cpp.
References clang::Sema::Context, clang::OpaquePtr< PtrTy >::get(), clang::ParsedTemplateArgument::getAsExpr(), clang::ParsedTemplateArgument::getAsTemplate(), clang::ParsedTemplateArgument::getAsType(), clang::ParsedTemplateArgument::getEllipsisLoc(), clang::ParsedTemplateArgument::getKind(), clang::ParsedTemplateArgument::getLocation(), clang::ParsedTemplateArgument::getScopeSpec(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::Sema::GetTypeFromParser(), clang::CXXScopeSpec::getWithLocInContext(), clang::SourceLocation::isValid(), clang::ParsedTemplateArgument::NonType, clang::ParsedTemplateArgument::Template, and clang::ParsedTemplateArgument::Type.
Referenced by clang::Sema::ActOnTemplateTemplateParameter(), and clang::Sema::translateTemplateArguments().