clang: lib/Sema/Sema.cpp File Reference
Sema.cpp File Reference
#include "UsedDeclVisitor.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Basic/DarwinSDKInfo.h"
#include "clang/Basic/DiagnosticOptions.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Stack.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/CXXFieldCollector.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/ExternalSemaSource.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/MultiplexExternalSemaSource.h"
#include "clang/Sema/ObjCMethodList.h"
#include "clang/Sema/RISCVIntrinsicManager.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaConsumer.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/TemplateDeduction.h"
#include "clang/Sema/TemplateInstCallback.h"
#include "clang/Sema/TypoCorrection.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/TimeProfiler.h"
#include <optional>
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/Basic/RISCVVTypes.def"
#include "clang/Basic/WebAssemblyReferenceTypes.def"
Classes
class clang::sema::SemaPPCallbacks
Namespaces
namespace clang
namespace clang::sema
Macros
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_MMA_TYPE(Name, Id, Size)
#define PPC_VECTOR_VSX_TYPE(Name, Id, Size)
#define RVV_TYPE(Name, Id, SingletonId)
#define WASM_TYPE(Name, Id, SingletonId)
Typedefs
typedef llvm::DenseMap< const CXXRecordDecl *, bool > RecordCompleteMap
Functions
static bool ShouldRemoveFromUnused (Sema *SemaRef, const DeclaratorDecl *D)
Used to prune the decls of Sema's UnusedFileScopedDecls vector.
static bool isFunctionOrVarDeclExternC (const NamedDecl *ND)
static void checkUndefinedButUsed (Sema &S)
checkUndefinedButUsed - Check for undefined objects with internal linkage or that are inline.
static bool MethodsAndNestedClassesComplete (const CXXRecordDecl *RD, RecordCompleteMap &MNCComplete)
Returns true, if all methods and nested classes of the given CXXRecordDecl are defined in this translation unit.
static bool IsRecordFullyDefined (const CXXRecordDecl *RD, RecordCompleteMap &RecordsComplete, RecordCompleteMap &MNCComplete)
Returns true, if the given CXXRecordDecl is fully defined in this translation unit, i.e.
static void emitCallStackNotes (Sema &S, const FunctionDecl *FD)
static void checkEscapingByref (VarDecl *VD, Sema &S)
static void markEscapingByrefs (const FunctionScopeInfo &FSI, Sema &S)
static void noteOverloads (Sema &S, const UnresolvedSetImpl &Overloads, const SourceLocation FinalNoteLoc)
Give notes for a set of overloads.
static void notePlausibleOverloads (Sema &S, SourceLocation Loc, const UnresolvedSetImpl &Overloads, bool(*IsPlausibleResult)(QualType))
static bool IsCallableWithAppend (const Expr *E)
Determine whether the given expression can be called by just putting parentheses after it.
static bool IsCPUDispatchCPUSpecificMultiVersion (const Expr *E)
Macro Definition Documentation
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  if (getOpenCLOptions().isSupported(#Ext, getLangOpts())) {                   \
    addImplicitTypedef(#ExtType, Context.Id##Ty);                              \
  }
PPC_VECTOR_MMA_TYPE
#define PPC_VECTOR_MMA_TYPE (Name, Id, Size)
Value:
      addImplicitTypedef(#Name, Context.Id##Ty);
PPC_VECTOR_VSX_TYPE
#define PPC_VECTOR_VSX_TYPE (Name, Id, Size)
Value:
    addImplicitTypedef(#Name, Context.Id##Ty);
RVV_TYPE
#define RVV_TYPE (Name, Id, SingletonId)
Value:
  addImplicitTypedef(Name, Context.SingletonId);
SVE_TYPE
#define SVE_TYPE (Name, Id, SingletonId)
Value:
    addImplicitTypedef(Name, Context.SingletonId);
WASM_TYPE
#define WASM_TYPE (Name, Id, SingletonId)
Value:
  addImplicitTypedef(Name, Context.SingletonId);
Typedef Documentation
RecordCompleteMap
typedef llvm::DenseMap<const CXXRecordDecl*, bool> RecordCompleteMap
Definition at line 934 of file Sema.cpp.
Function Documentation
checkEscapingByref()
static void checkEscapingByref (VarDecl * VD, Sema & S) static
Definition at line 2166 of file Sema.cpp.
References clang::Sema::canThrow(), clang::Sema::Context, clang::ImplicitCastExpr::Create(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::InitializedEntity::InitializeBlock(), clang::Sema::MaybeCreateExprWithCleanups(), clang::Sema::NamedReturnInfo::MoveEligible, clang::Sema::PerformCopyInitialization(), clang::Sema::PerformMoveOrCopyInitialization(), clang::Sema::PotentiallyEvaluated, clang::Sema::ResolveExceptionSpec(), clang::Result, clang::ASTContext::setBlockVarCopyInit(), clang::VK_LValue, and clang::VK_XValue.
Referenced by markEscapingByrefs().
checkUndefinedButUsed()
static void checkUndefinedButUsed (Sema & S) static
checkUndefinedButUsed - Check for undefined objects with internal linkage or that are inline.
Definition at line 860 of file Sema.cpp.
References clang::cast(), clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Type::getLinkage(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::Sema::getUndefinedButUsed(), clang::isa(), clang::isExternallyVisible(), clang::NamedDecl::isExternallyVisible(), clang::Sema::isExternalWithNoLinkageType(), clang::SourceLocation::isValid(), and clang::Sema::UndefinedButUsed.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
emitCallStackNotes()
static void emitCallStackNotes (Sema & S, const FunctionDecl * FD) static
Definition at line 1621 of file Sema.cpp.
References clang::Sema::DeviceKnownEmittedFns, clang::Sema::Diags, clang::DiagnosticsEngine::hasFatalErrorOccurred(), and clang::DiagnosticsEngine::Report().
Referenced by clang::Sema::SemaDiagnosticBuilder::~SemaDiagnosticBuilder().
IsCallableWithAppend()
static bool IsCallableWithAppend (const Expr * E) static
Determine whether the given expression can be called by just putting parentheses after it.
Notably, expressions with unary operators can't be because the unary operator will start parsing outside the call.
Definition at line 2613 of file Sema.cpp.
References clang::Expr::IgnoreImplicit().
Referenced by clang::Sema::tryToRecoverWithCall().
IsCPUDispatchCPUSpecificMultiVersion()
static bool IsCPUDispatchCPUSpecificMultiVersion (const Expr * E) static
Definition at line 2621 of file Sema.cpp.
References clang::FunctionDecl::isCPUDispatchMultiVersion(), and clang::FunctionDecl::isCPUSpecificMultiVersion().
Referenced by clang::Sema::tryToRecoverWithCall().
isFunctionOrVarDeclExternC()
static bool isFunctionOrVarDeclExternC (const NamedDecl * ND) static
Definition at line 788 of file Sema.cpp.
References clang::cast().
Referenced by clang::Sema::isExternalWithNoLinkageType().
IsRecordFullyDefined()
static bool IsRecordFullyDefined (const CXXRecordDecl * RD, RecordCompleteMap & RecordsComplete, RecordCompleteMap & MNCComplete) static
Returns true, if the given CXXRecordDecl is fully defined in this translation unit, i.e.
all methods are defined or pure virtual and all friends, friend functions and nested classes are fully defined in this translation unit.
Should only be called from ActOnEndOfTranslationUnit so that all definitions are actually read.
Definition at line 983 of file Sema.cpp.
References clang::CXXRecordDecl::friend_begin(), clang::CXXRecordDecl::friend_end(), and MethodsAndNestedClassesComplete().
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
markEscapingByrefs()
static void markEscapingByrefs (const FunctionScopeInfo & FSI, Sema & S) static
Definition at line 2200 of file Sema.cpp.
References clang::sema::FunctionScopeInfo::Blocks, clang::sema::FunctionScopeInfo::ByrefBlockVars, clang::BlockDecl::captures(), checkEscapingByref(), clang::Sema::checkNonTrivialCUnion(), clang::BlockDecl::doesNotEscape(), clang::BlockDecl::getCaretLocation(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::QualType::hasNonTrivialToPrimitiveCopyCUnion(), clang::QualType::hasNonTrivialToPrimitiveDestructCUnion(), clang::VarDecl::isEscapingByref(), clang::Type::isStructureOrClassType(), clang::Sema::NTCUC_BlockCapture, clang::Sema::NTCUK_Copy, clang::Sema::NTCUK_Destruct, and clang::VarDecl::setEscapingByref().
Referenced by clang::Sema::PopFunctionScopeInfo().
MethodsAndNestedClassesComplete()
static bool MethodsAndNestedClassesComplete (const CXXRecordDecl * RD, RecordCompleteMap & MNCComplete) static
Returns true, if all methods and nested classes of the given CXXRecordDecl are defined in this translation unit.
Should only be called from ActOnEndOfTranslationUnit so that all definitions are actually read.
Definition at line 941 of file Sema.cpp.
References clang::DeclContext::decls_begin(), clang::DeclContext::decls_end(), clang::TagDecl::isCompleteDefinition(), and MethodsAndNestedClassesComplete().
Referenced by IsRecordFullyDefined(), and MethodsAndNestedClassesComplete().
noteOverloads()
static void noteOverloads (Sema & S, const UnresolvedSetImpl & Overloads, const SourceLocation FinalNoteLoc) static
Give notes for a set of overloads.
A companion to tryExprAsCall. In cases when the name that the programmer wrote was an overloaded function, we may be able to make some guesses about plausible overloads based on their return types; such guesses can be handed off to this method to be emitted as notes.
Parameters
Overloads - The overloads to note.
FinalNoteLoc - If we've suppressed printing some overloads due to -fshow-overloads=best, this is the location to attach to the note about too many candidates. Typically this will be the location of the original ill-formed expression.
Definition at line 2560 of file Sema.cpp.
References clang::UnresolvedSetImpl::begin(), clang::Sema::Diag(), clang::Sema::Diags, clang::UnresolvedSetImpl::end(), clang::Decl::getAsFunction(), clang::Decl::getAttr(), clang::Decl::getLocation(), clang::DiagnosticsEngine::getNumOverloadCandidatesToShow(), clang::NamedDecl::getUnderlyingDecl(), clang::Decl::hasAttr(), clang::FunctionDecl::isMultiVersion(), and clang::DiagnosticsEngine::overloadCandidatesShown().
Referenced by notePlausibleOverloads().
notePlausibleOverloads()
static void notePlausibleOverloads (Sema & S, SourceLocation Loc, const UnresolvedSetImpl & Overloads, bool(* IsPlausibleResult)(QualType)) static
Definition at line 2592 of file Sema.cpp.
References clang::UnresolvedSetImpl::addDecl(), clang::UnresolvedSetImpl::begin(), clang::cast(), clang::UnresolvedSetImpl::end(), and noteOverloads().
Referenced by clang::Sema::tryToRecoverWithCall().
ShouldRemoveFromUnused()
static bool ShouldRemoveFromUnused (Sema * SemaRef, const DeclaratorDecl * D) static
Used to prune the decls of Sema's UnusedFileScopedDecls vector.
Definition at line 727 of file Sema.cpp.
References clang::Sema::Context, clang::VarDecl::getDefinition(), clang::NamedDecl::getMostRecentDecl(), clang::Redeclarable< decl_type >::getMostRecentDecl(), clang::NamedDecl::isExternallyVisible(), clang::Decl::isUsed(), ShouldRemoveFromUnused(), and clang::Sema::ShouldWarnIfUnusedFileScopedDecl().
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), and ShouldRemoveFromUnused().