clang: lib/Sema/SemaCUDA.cpp File Reference
SemaCUDA.cpp File Reference
This file implements semantic analysis for CUDA constructs.
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/ExprCXX.h"
#include "clang/Basic/Cuda.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaDiagnostic.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
Functions
template<typename AttrT >
static bool hasExplicitAttr (const VarDecl *D)
template<typename A >
static bool hasAttr (const FunctionDecl *D, bool IgnoreImplicitAttr)
template<typename AttrT >
static bool hasImplicitAttr (const FunctionDecl *D)
static bool resolveCalleeCUDATargetConflict (Sema::CUDAFunctionTarget Target1, Sema::CUDAFunctionTarget Target2, Sema::CUDAFunctionTarget *ResolvedTarget)
When an implicitly-declared special member has to invoke more than one base/field special member, conflicts may occur in the targets of these members.
template<typename AttrTy >
static void copyAttrIfPresent (Sema &S, FunctionDecl *FD, const FunctionDecl &TemplateFD)
Detailed Description
This file implements semantic analysis for CUDA constructs.
Definition in file SemaCUDA.cpp.
Function Documentation
copyAttrIfPresent()
template<typename AttrTy > static void copyAttrIfPresent (Sema & S, FunctionDecl * FD, const FunctionDecl & TemplateFD) static
Definition at line 933 of file SemaCUDA.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, and clang::Decl::getAttr().
Referenced by clang::Sema::inheritCUDATargetAttrs().
hasAttr()
template<typename A > static bool hasAttr (const FunctionDecl * D, bool IgnoreImplicitAttr) static
Definition at line 108 of file SemaCUDA.cpp.
References clang::Decl::getAttrs(), and clang::Decl::hasAttrs().
Referenced by clang::GlobalDecl::getKernelReferenceKind(), clang::GlobalDecl::getMultiVersionIndex(), clang::GlobalDecl::getWithKernelReferenceKind(), clang::GlobalDecl::getWithMultiVersionIndex(), clang::Sema::IdentifyCUDATarget(), isIncompleteDeclExternC(), clang::ast_matchers::isInUnspecifiedPointerContext(), clang::CodeGen::CodeGenModule::MaybeHandleStaticInExternC(), and clang::OverloadCandidateSet::shouldDeferDiags().
hasExplicitAttr()
template<typename AttrT > static bool hasExplicitAttr (const VarDecl * D) static
Definition at line 29 of file SemaCUDA.cpp.
References clang::Decl::getAttr().
Referenced by clang::Sema::IdentifyCUDATarget().
hasImplicitAttr()
template<typename AttrT > static bool hasImplicitAttr (const FunctionDecl * D) static
Definition at line 258 of file SemaCUDA.cpp.
References clang::Decl::getAttr(), and clang::Decl::isImplicit().
Referenced by clang::Sema::isCUDAImplicitHostDeviceFunction().
resolveCalleeCUDATargetConflict()
static bool resolveCalleeCUDATargetConflict (Sema::CUDAFunctionTarget Target1, Sema::CUDAFunctionTarget Target2, Sema::CUDAFunctionTarget * ResolvedTarget) static
When an implicitly-declared special member has to invoke more than one base/field special member, conflicts may occur in the targets of these members.
For example, if one base's member host and another's is device, it's a conflict. This function figures out if the given targets
Parameters
Target1 and
Target2 conflict, and if they do not it fills in
ResolvedTarget with a target that resolves for both calls.
Returns
true if there's a conflict, false otherwise.
Definition at line 304 of file SemaCUDA.cpp.
References clang::Sema::CFT_Global, and clang::Sema::CFT_HostDevice.
Referenced by clang::Sema::inferCUDATargetForImplicitSpecialMember().