clang: lib/Sema/SemaDeclCXX.cpp File Reference
SemaDeclCXX.cpp File Reference
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/ComparisonCategories.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/TypeOrdering.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/CXXFieldCollector.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/SaveAndRestore.h"
#include <map>
#include <optional>
#include <set>
#include "clang/AST/TypeLocNodes.def"
#include "clang/Basic/OperatorKinds.def"
Classes
class clang::Sema::InheritedConstructorInfo
Macros
#define ABSTRACT_TYPELOC(CLASS, PARENT)
#define TYPELOC(CLASS, PARENT)
#define CheckPolymorphic(Type)
#define OVERLOADED_OPERATOR(Name, Spelling, Token, Unary, Binary, MemberOnly)
Typedefs
typedef llvm::SmallPtrSet< QualType, 4 > IndirectBaseSet
Use small set to collect indirect bases.
Enumerations
enum ImplicitInitializerKind { IIK_Default , IIK_Copy , IIK_Move , IIK_Inherit }
ImplicitInitializerKind - How an implicit base or member initializer should initialize its base or member.
enum TrivialSubobjectKind { TSK_BaseClass , TSK_Field , TSK_CompleteObject }
The kind of subobject we are checking for triviality.
Functions
static bool functionDeclHasDefaultArgument (const FunctionDecl *FD)
static bool checkSimpleDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const llvm::APSInt &NumElems, QualType ElemType, llvm::function_ref< ExprResult(SourceLocation, Expr *, unsigned)> GetInit)
static bool checkArrayLikeDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const llvm::APSInt &NumElems, QualType ElemType)
static bool checkArrayDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const ConstantArrayType *CAT)
static bool checkVectorDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const VectorType *VT)
static bool checkComplexDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const ComplexType *CT)
static std::string printTemplateArgs (const PrintingPolicy &PrintingPolicy, TemplateArgumentListInfo &Args, const TemplateParameterList *Params)
static bool lookupStdTypeTraitMember (Sema &S, LookupResult &TraitMemberLookup, SourceLocation Loc, StringRef Trait, TemplateArgumentListInfo &Args, unsigned DiagID)
static TemplateArgumentLoc getTrivialIntegralTemplateArgument (Sema &S, SourceLocation Loc, QualType T, uint64_t I)
static TemplateArgumentLoc getTrivialTypeTemplateArgument (Sema &S, SourceLocation Loc, QualType T)
static IsTupleLike isTupleLike (Sema &S, SourceLocation Loc, QualType T, llvm::APSInt &Size)
static QualType getTupleLikeElementType (Sema &S, SourceLocation Loc, unsigned I, QualType T)
static bool checkTupleLikeDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, VarDecl *Src, QualType DecompType, const llvm::APSInt &TupleSize)
static DeclAccessPair findDecomposableBaseClass (Sema &S, SourceLocation Loc, const CXXRecordDecl *RD, CXXCastPath &BasePath)
Find the base class to decompose in a built-in decomposition of a class type.
static bool checkMemberDecomposition (Sema &S, ArrayRef< BindingDecl * > Bindings, ValueDecl *Src, QualType DecompType, const CXXRecordDecl *OrigRD)
template<typename... Ts>
static bool CheckLiteralType (Sema &SemaRef, Sema::CheckConstexprKind Kind, SourceLocation Loc, QualType T, unsigned DiagID, Ts &&...DiagArgs)
Check that the given type is a literal type.
static bool CheckConstexprDestructorSubobjects (Sema &SemaRef, const CXXDestructorDecl *DD, Sema::CheckConstexprKind Kind)
Determine whether a destructor cannot be constexpr due to.
static bool CheckConstexprParameterTypes (Sema &SemaRef, const FunctionDecl *FD, Sema::CheckConstexprKind Kind)
Check whether a function's parameter types are all literal types.
static bool CheckConstexprReturnType (Sema &SemaRef, const FunctionDecl *FD, Sema::CheckConstexprKind Kind)
Check whether a function's return type is a literal type.
static unsigned getRecordDiagFromTagKind (TagTypeKind Tag)
Get diagnostic select index for tag kind for record diagnostic message.
static bool CheckConstexprFunctionBody (Sema &SemaRef, const FunctionDecl *Dcl, Stmt *Body, Sema::CheckConstexprKind Kind)
Check the body for the given constexpr function declaration only contains the permitted types of statement.
static bool CheckConstexprDeclStmt (Sema &SemaRef, const FunctionDecl *Dcl, DeclStmt *DS, SourceLocation &Cxx1yLoc, Sema::CheckConstexprKind Kind)
Check the given declaration statement is legal within a constexpr function body.
static bool CheckConstexprCtorInitializer (Sema &SemaRef, const FunctionDecl *Dcl, FieldDecl *Field, llvm::SmallSet< Decl *, 16 > &Inits, bool &Diagnosed, Sema::CheckConstexprKind Kind)
Check that the given field is initialized within a constexpr constructor.
static bool CheckConstexprFunctionStmt (Sema &SemaRef, const FunctionDecl *Dcl, Stmt *S, SmallVectorImpl< SourceLocation > &ReturnStmts, SourceLocation &Cxx1yLoc, SourceLocation &Cxx2aLoc, SourceLocation &Cxx2bLoc, Sema::CheckConstexprKind Kind)
Check the provided statement is allowed in a constexpr function definition.
static bool findCircularInheritance (const CXXRecordDecl *Class, const CXXRecordDecl *Current)
Determine whether the given class is a base class of the given class, including looking at dependent bases.
static void NoteIndirectBases (ASTContext &Context, IndirectBaseSet &Set, const QualType &Type)
Recursively add the bases of Type. Don't add Type itself.
static void BuildBasePathArray (const CXXBasePath &Path, CXXCastPath &BasePathArray)
static bool InitializationHasSideEffects (const FieldDecl &FD)
static bool FindBaseInitializer (Sema &SemaRef, CXXRecordDecl *ClassDecl, QualType BaseType, const CXXBaseSpecifier *&DirectBaseSpec, const CXXBaseSpecifier *&VirtualBaseSpec)
Find the direct and/or virtual base specifiers that correspond to the given base type, for use in base initialization within a constructor.
static Expr * CastForMoving (Sema &SemaRef, Expr *E)
static bool BuildImplicitBaseInitializer (Sema &SemaRef, CXXConstructorDecl *Constructor, ImplicitInitializerKind ImplicitInitKind, CXXBaseSpecifier *BaseSpec, bool IsInheritedVirtualBase, CXXCtorInitializer *&CXXBaseInit)
static bool RefersToRValueRef (Expr *MemRef)
static bool BuildImplicitMemberInitializer (Sema &SemaRef, CXXConstructorDecl *Constructor, ImplicitInitializerKind ImplicitInitKind, FieldDecl *Field, IndirectFieldDecl *Indirect, CXXCtorInitializer *&CXXMemberInit)
static bool isIncompleteOrZeroLengthArrayType (ASTContext &Context, QualType T)
Determine whether the given type is an incomplete or zero-lenfgth array type.
static bool CollectFieldInitializer (Sema &SemaRef, BaseAndFieldInfo &Info, FieldDecl *Field, IndirectFieldDecl *Indirect=nullptr)
static void PopulateKeysForFields (FieldDecl *Field, SmallVectorImpl< const void * > &IdealInits)
static const void * GetKeyForBase (ASTContext &Context, QualType BaseType)
static const void * GetKeyForMember (ASTContext &Context, CXXCtorInitializer *Member)
static void AddInitializerToDiag (const Sema::SemaDiagnosticBuilder &Diag, const CXXCtorInitializer *Previous, const CXXCtorInitializer *Current)
static void DiagnoseBaseOrMemInitializerOrder (Sema &SemaRef, const CXXConstructorDecl *Constructor, ArrayRef< CXXCtorInitializer * > Inits)
static void CheckAbstractClassUsage (AbstractUsageInfo &Info, FunctionDecl *FD)
Check for invalid uses of an abstract type in a function declaration.
static void CheckAbstractClassUsage (AbstractUsageInfo &Info, VarDecl *VD)
Check for invalid uses of an abstract type in a variable0 declaration.
static void CheckAbstractClassUsage (AbstractUsageInfo &Info, CXXRecordDecl *RD)
Check for invalid uses of an abstract type within a class definition.
static void ReferenceDllExportedMembers (Sema &S, CXXRecordDecl *Class)
static void checkForMultipleExportedDefaultConstructors (Sema &S, CXXRecordDecl *Class)
static void checkCUDADeviceBuiltinSurfaceClassTemplate (Sema &S, CXXRecordDecl *Class)
static void checkCUDADeviceBuiltinTextureClassTemplate (Sema &S, CXXRecordDecl *Class)
static void DefineDefaultedFunction (Sema &S, FunctionDecl *FD, SourceLocation DefaultLoc)
static bool canPassInRegisters (Sema &S, CXXRecordDecl *D, TargetInfo::CallingConvKind CCK)
Determine whether a type is permitted to be passed or returned in registers, per C++ [class.temporary]p3.
static bool ReportOverrides (Sema &S, unsigned DiagID, const CXXMethodDecl *MD, llvm::function_ref< bool(const CXXMethodDecl *)> Report)
Report an error regarding overriding, along with any relevant overridden methods.
static Sema::SpecialMemberOverloadResult lookupCallFromSpecialMember (Sema &S, CXXRecordDecl *Class, Sema::CXXSpecialMember CSM, unsigned FieldQuals, bool ConstRHS)
Look up the special member function that would be called by a special member function for a subobject of class type.
static bool specialMemberIsConstexpr (Sema &S, CXXRecordDecl *ClassDecl, Sema::CXXSpecialMember CSM, unsigned Quals, bool ConstRHS, CXXConstructorDecl *InheritedCtor=nullptr, Sema::InheritedConstructorInfo *Inherited=nullptr)
Is the special member function which would be selected to perform the specified operation on the specified class type a constexpr constructor?
static bool defaultedSpecialMemberIsConstexpr (Sema &S, CXXRecordDecl *ClassDecl, Sema::CXXSpecialMember CSM, bool ConstArg, CXXConstructorDecl *InheritedCtor=nullptr, Sema::InheritedConstructorInfo *Inherited=nullptr)
Determine whether the specified special member function would be constexpr if it were implicitly defined.
static Sema::ImplicitExceptionSpecification ComputeDefaultedSpecialMemberExceptionSpec (Sema &S, SourceLocation Loc, CXXMethodDecl *MD, Sema::CXXSpecialMember CSM, Sema::InheritedConstructorInfo *ICI)
static Sema::ImplicitExceptionSpecification ComputeDefaultedComparisonExceptionSpec (Sema &S, SourceLocation Loc, FunctionDecl *FD, Sema::DefaultedComparisonKind DCK)
static Sema::ImplicitExceptionSpecification computeImplicitExceptionSpec (Sema &S, SourceLocation Loc, FunctionDecl *FD)
static FunctionProtoType::ExtProtoInfo getImplicitMethodEPI (Sema &S, CXXMethodDecl *MD)
static void lookupOperatorsForDefaultedComparison (Sema &Self, Scope *S, UnresolvedSetImpl &Operators, OverloadedOperatorKind Op)
Perform the unqualified lookups that might be needed to form a defaulted comparison function for the given operator.
static bool findTrivialSpecialMember (Sema &S, CXXRecordDecl *RD, Sema::CXXSpecialMember CSM, unsigned Quals, bool ConstRHS, Sema::TrivialABIHandling TAH, CXXMethodDecl **Selected)
Perform lookup for a special member of the specified kind, and determine whether it is trivial.
static CXXConstructorDecl * findUserDeclaredCtor (CXXRecordDecl *RD)
static bool checkTrivialSubobjectCall (Sema &S, SourceLocation SubobjLoc, QualType SubType, bool ConstRHS, Sema::CXXSpecialMember CSM, TrivialSubobjectKind Kind, Sema::TrivialABIHandling TAH, bool Diagnose)
Check whether the special member selected for a given type would be trivial.
static bool checkTrivialClassMembers (Sema &S, CXXRecordDecl *RD, Sema::CXXSpecialMember CSM, bool ConstArg, Sema::TrivialABIHandling TAH, bool Diagnose)
Check whether the members of a class type allow a special member to be trivial.
static void AddMostOverridenMethods (const CXXMethodDecl *MD, llvm::SmallPtrSetImpl< const CXXMethodDecl * > &Methods)
Add the most overridden methods from MD to Methods.
static void findImplicitlyDeclaredEqualityComparisons (ASTContext &Ctx, CXXRecordDecl *RD, llvm::SmallVectorImpl< FunctionDecl * > &Spaceships)
Find the equality comparison functions that should be implicitly declared in a given class definition, per C++2a [class.compare.default]p3.
static void checkMethodTypeQualifiers (Sema &S, Declarator &D, unsigned DiagID)
static void extendLeft (SourceRange &R, SourceRange Before)
static void extendRight (SourceRange &R, SourceRange After)
static void DiagnoseNamespaceInlineMismatch (Sema &S, SourceLocation KeywordLoc, SourceLocation Loc, IdentifierInfo *II, bool *IsInline, NamespaceDecl *PrevNS)
Diagnose a mismatch in 'inline' qualifiers when a namespace is reopened.
static NamespaceDecl * getNamespaceDecl (NamedDecl *D)
getNamespaceDecl - Returns the namespace a decl represents.
static ClassTemplateDecl * LookupStdInitializerList (Sema &S, SourceLocation Loc)
static bool IsUsingDirectiveInToplevelContext (DeclContext *CurContext)
Determine whether a using statement is in a context where it will be apply in all contexts.
static bool TryNamespaceTypoCorrection (Sema &S, LookupResult &R, Scope *Sc, CXXScopeSpec &SS, SourceLocation IdentLoc, IdentifierInfo *Ident)
static bool IsEquivalentForUsingDecl (ASTContext &Context, NamedDecl *D1, NamedDecl *D2)
Determine whether a using declaration considers the given declarations as "equivalent", e.g., if they are redeclarations of the same entity or are both typedefs of the same type.
static bool isVirtualDirectBase (CXXRecordDecl *Derived, CXXRecordDecl *Base)
Determine whether a direct base class is a virtual base class.
static CXXBaseSpecifier * findDirectBaseWithType (CXXRecordDecl *Derived, QualType DesiredBase, bool &AnyDependentBases)
Find the base specifier for a base class with the given type.
static StmtResult buildMemcpyForAssignmentOp (Sema &S, SourceLocation Loc, QualType T, const ExprBuilder &ToB, const ExprBuilder &FromB)
When generating a defaulted copy or move assignment operator, if a field should be copied with __builtin_memcpy rather than via explicit assignments, do so.
static StmtResult buildSingleCopyAssignRecursively (Sema &S, SourceLocation Loc, QualType T, const ExprBuilder &To, const ExprBuilder &From, bool CopyingBaseSubobject, bool Copying, unsigned Depth=0)
Builds a statement that copies/moves the given entity from From to To.
static StmtResult buildSingleCopyAssign (Sema &S, SourceLocation Loc, QualType T, const ExprBuilder &To, const ExprBuilder &From, bool CopyingBaseSubobject, bool Copying)
static void diagnoseDeprecatedCopyOperation (Sema &S, CXXMethodDecl *CopyOp)
Diagnose an implicit copy operation for a class which is odr-used, but which is deprecated because the class has a user-declared copy constructor, copy assignment operator, or destructor.
static void checkMoveAssignmentForRepeatedMove (Sema &S, CXXRecordDecl *Class, SourceLocation CurrentLocation)
Check if we're implicitly defining a move assignment operator for a class with virtual bases.
static bool hasOneRealArgument (MultiExprArg Args)
Determine whether the given list arguments contains exactly one "real" (non-default) argument.
static bool CheckOperatorNewDeleteDeclarationScope (Sema &SemaRef, const FunctionDecl *FnDecl)
static CanQualType RemoveAddressSpaceFromPtr (Sema &SemaRef, const PointerType *PtrTy)
static bool CheckOperatorNewDeleteTypes (Sema &SemaRef, const FunctionDecl *FnDecl, CanQualType ExpectedResultType, CanQualType ExpectedFirstParamType, unsigned DependentParamTypeDiag, unsigned InvalidParamTypeDiag)
static bool CheckOperatorNewDeclaration (Sema &SemaRef, const FunctionDecl *FnDecl)
static bool CheckOperatorDeleteDeclaration (Sema &SemaRef, FunctionDecl *FnDecl)
static bool checkLiteralOperatorTemplateParameterList (Sema &SemaRef, FunctionTemplateDecl *TpDecl)
static bool ConvertAPValueToString (const APValue &V, QualType T, SmallVectorImpl< char > &Str)
Convert \V to a string we can present to the user in a diagnostic \T is the type of the expression that has been evaluated into \V.
static bool UsefulToPrintExpr (const Expr *E)
Some Expression types are not useful to print notes about, e.g.
static void SearchForReturnInStmt (Sema &Self, Stmt *S)
static bool isNonlocalVariable (const Decl *D)
Determine whether the given declaration is a global variable or static data member.
static void DelegatingCycleHelper (CXXConstructorDecl *Ctor, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > &Valid, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > &Invalid, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > &Current, Sema &S)
Macro Definition Documentation
ABSTRACT_TYPELOC
#define ABSTRACT_TYPELOC (CLASS, PARENT)
CheckPolymorphic
#define CheckPolymorphic (Type)
Value:
  void Check(Type TL, Sema::AbstractDiagSelID Sel) { \
    Visit(TL.getNextTypeLoc(), Sema::AbstractNone); \
  }
Definition at line 6059 of file SemaDeclCXX.cpp.
OVERLOADED_OPERATOR
#define OVERLOADED_OPERATOR (Name, Spelling, Token, Unary, Binary, MemberOnly)
Value:
    , { Unary, Binary, MemberOnly }
TYPELOC
#define TYPELOC (CLASS, PARENT)
Value:
    case TypeLoc::CLASS: Check(TL.castAs<CLASS##TypeLoc>(), Sel); break;
Typedef Documentation
IndirectBaseSet
typedef llvm::SmallPtrSet<QualType, 4> IndirectBaseSet
Use small set to collect indirect bases.
As this is only used locally, there's no need to abstract the small size parameter.
Definition at line 2850 of file SemaDeclCXX.cpp.
Enumeration Type Documentation
ImplicitInitializerKind
enum ImplicitInitializerKind
ImplicitInitializerKind - How an implicit base or member initializer should initialize its base or member.
Enumerator
IIK_Default
IIK_Copy
IIK_Move
IIK_Inherit
Definition at line 4833 of file SemaDeclCXX.cpp.
TrivialSubobjectKind
enum TrivialSubobjectKind
The kind of subobject we are checking for triviality.
The values of this enumeration are used in diagnostics.
Enumerator
TSK_BaseClass
The subobject is a base class.
TSK_Field
The subobject is a non-static data member.
TSK_CompleteObject
The object is actually the complete object.
Definition at line 9883 of file SemaDeclCXX.cpp.
Function Documentation
AddInitializerToDiag()
static void AddInitializerToDiag (const Sema::SemaDiagnosticBuilder & Diag, const CXXCtorInitializer * Previous, const CXXCtorInitializer * Current) static
Definition at line 5478 of file SemaDeclCXX.cpp.
References Diag(), and Previous.
Referenced by DiagnoseBaseOrMemInitializerOrder().
AddMostOverridenMethods()
static void AddMostOverridenMethods (const CXXMethodDecl * MD, llvm::SmallPtrSetImpl< const CXXMethodDecl * > & Methods) static
Add the most overridden methods from MD to Methods.
Definition at line 10227 of file SemaDeclCXX.cpp.
References AddMostOverridenMethods(), clang::CXXMethodDecl::getCanonicalDecl(), clang::CXXMethodDecl::overridden_methods(), and clang::CXXMethodDecl::size_overridden_methods().
Referenced by AddMostOverridenMethods(), and clang::Sema::FindHiddenVirtualMethods().
BuildBasePathArray()
static void BuildBasePathArray (const CXXBasePath & Path, CXXCastPath & BasePathArray) static
Definition at line 3040 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::CheckDerivedToBaseConversion(), and clang::Sema::CheckMemberPointerConversion().
BuildImplicitBaseInitializer()
static bool BuildImplicitBaseInitializer (Sema & SemaRef, CXXConstructorDecl * Constructor, ImplicitInitializerKind ImplicitInitKind, CXXBaseSpecifier * BaseSpec, bool IsInheritedVirtualBase, CXXCtorInitializer *& CXXBaseInit) static
Definition at line 4841 of file SemaDeclCXX.cpp.
References CastForMoving(), clang::Sema::Context, clang::DeclRefExpr::Create(), clang::InitializationKind::CreateDefault(), clang::InitializationKind::CreateDirect(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ActionResult< PtrTy, CompressInvalid >::getAs(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::CXXBaseSpecifier::getType(), clang::QualType::getUnqualifiedType(), IIK_Copy, IIK_Default, IIK_Inherit, IIK_Move, clang::Sema::ImpCastExprToType(), clang::InitializedEntity::InitializeBase(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::CXXBaseSpecifier::isVirtual(), clang::Sema::MarkDeclRefReferenced(), clang::Sema::MaybeCreateExprWithCleanups(), clang::InitializationSequence::Perform(), clang::VK_LValue, and clang::VK_XValue.
Referenced by clang::Sema::SetCtorInitializers().
BuildImplicitMemberInitializer()
static bool BuildImplicitMemberInitializer (Sema & SemaRef, CXXConstructorDecl * Constructor, ImplicitInitializerKind ImplicitInitKind, FieldDecl * Field, IndirectFieldDecl * Indirect, CXXCtorInitializer *& CXXMemberInit) static
Definition at line 4924 of file SemaDeclCXX.cpp.
References clang::LookupResult::addDecl(), clang::AS_public, clang::Sema::BuildMemberReferenceExpr(), CastForMoving(), clang::Sema::Context, clang::DeclRefExpr::Create(), clang::InitializationKind::CreateDefault(), clang::InitializationKind::CreateDirect(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ActionResult< PtrTy, CompressInvalid >::getAs(), clang::ASTContext::getBaseElementType(), clang::ASTContext::getTagDeclType(), clang::QualType::hasNonTrivialObjCLifetime(), IIK_Copy, IIK_Default, IIK_Inherit, IIK_Move, clang::InitializedEntity::InitializeMember(), int, clang::QualType::isConstQualified(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isRecordType(), clang::Type::isReferenceType(), clang::Sema::LookupMemberName, clang::Sema::MarkDeclRefReferenced(), clang::Sema::MaybeCreateExprWithCleanups(), clang::InitializationSequence::Perform(), RefersToRValueRef(), clang::LookupResult::resolveKind(), and clang::VK_LValue.
Referenced by CollectFieldInitializer().
buildMemcpyForAssignmentOp()
static StmtResult buildMemcpyForAssignmentOp (Sema & S, SourceLocation Loc, QualType T, const ExprBuilder & ToB, const ExprBuilder & FromB) static
When generating a defaulted copy or move assignment operator, if a field should be copied with __builtin_memcpy rather than via explicit assignments, do so.
This optimization only applies for arrays of scalars, and for arrays of class type where the selected copy/move-assignment operator is trivial.
Definition at line 14314 of file SemaDeclCXX.cpp.
References clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclRefExpr(), clang::ASTContext::BuiltinFnTy, clang::Type::castAs(), clang::Sema::Context, clang::IntegerLiteral::Create(), clang::UnaryOperator::Create(), clang::Sema::CurFPFeatureOverrides(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::IdentifierTable::get(), clang::LookupResult::getAsSingle(), clang::ASTContext::getPointerType(), clang::CharUnits::getQuantity(), clang::ASTContext::getSizeType(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::getTypeSizeInChars(), clang::ASTContext::Idents, clang::Type::isRecordType(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::Sema::LookupName(), clang::Sema::LookupOrdinaryName, clang::OK_Ordinary, clang::StmtError(), clang::Sema::TUScope, and clang::VK_PRValue.
Referenced by buildSingleCopyAssign().
buildSingleCopyAssign()
static StmtResult buildSingleCopyAssign (Sema & S, SourceLocation Loc, QualType T, const ExprBuilder & To, const ExprBuilder & From, bool CopyingBaseSubobject, bool Copying) static
Definition at line 14586 of file SemaDeclCXX.cpp.
References buildMemcpyForAssignmentOp(), buildSingleCopyAssignRecursively(), and clang::Sema::Context.
Referenced by clang::Sema::DefineImplicitCopyAssignment(), and clang::Sema::DefineImplicitMoveAssignment().
buildSingleCopyAssignRecursively()
static StmtResult buildSingleCopyAssignRecursively (Sema & S, SourceLocation Loc, QualType T, const ExprBuilder & To, const ExprBuilder & From, bool CopyingBaseSubobject, bool Copying, unsigned Depth = 0) static
Builds a statement that copies/moves the given entity from From to To.
This routine is used to copy/move the members of a class with an implicitly-declared copy/move assignment operator. When the entities being copied are arrays, this routine builds for loops to copy them.
Parameters
S The Sema object used for type-checking.
Loc The location where the implicit copy/move is being generated.
T The type of the expressions being copied/moved. Both expressions must have this type.
To The expression we are copying/moving to.
From The expression we are copying/moving from.
CopyingBaseSubobject Whether we're copying/moving a base subobject. Otherwise, it's a non-static member subobject.
Copying Whether we're copying or moving.
Depth Internal parameter recording the depth of the recursion.
Returns
A statement or a loop that copies the expressions, or StmtResult(0) if a memcpy should be used instead.
Definition at line 14394 of file SemaDeclCXX.cpp.
References clang::Sema::ActOnCondition(), clang::Sema::ActOnExprStmt(), clang::Sema::ActOnForStmt(), clang::AS_protected, clang::AS_public, clang::LookupResult::begin(), clang::ASTContext::BoolTy, clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildMemberReferenceExpr(), buildSingleCopyAssignRecursively(), clang::cast(), clang::Sema::Context, clang::Copy, clang::BinaryOperator::Create(), clang::IntegerLiteral::Create(), clang::NestedNameSpecifier::Create(), clang::UnaryOperator::Create(), clang::VarDecl::Create(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CurContext, clang::Sema::CurFPFeatureOverrides(), clang::ASTContext::DeclarationNames, clang::LookupResult::Filter::done(), clang::LookupResult::end(), clang::LookupResult::Filter::erase(), clang::IdentifierTable::get(), clang::ActionResult< PtrTy, CompressInvalid >::getAs(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getCanonicalType(), clang::DeclarationNameTable::getCXXOperatorName(), clang::ArrayType::getElementType(), clang::Sema::getLangOpts(), clang::CXXMemberCallExpr::getMethodDecl(), clang::ConstantArrayType::getSize(), clang::ASTContext::getSizeType(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ASTContext::getTypeSize(), clang::LookupResult::Filter::hasNext(), clang::ASTContext::Idents, clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::FunctionDecl::isTrivial(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::LookupResult::makeFilter(), clang::Sema::MakeFullDiscardedValueExpr(), clang::CXXScopeSpec::MakeTrivial(), clang::LookupResult::Filter::next(), clang::OK_Ordinary, clang::SC_None, clang::VarDecl::setInit(), clang::StmtError(), clang::VK_LValue, and clang::VK_PRValue.
Referenced by buildSingleCopyAssign(), and buildSingleCopyAssignRecursively().
canPassInRegisters()
static bool canPassInRegisters (Sema & S, CXXRecordDecl * D, TargetInfo::CallingConvKind CCK) static
Determine whether a type is permitted to be passed or returned in registers, per C++ [class.temporary]p3.
Definition at line 6763 of file SemaDeclCXX.cpp.
References clang::TargetInfo::CCK_ClangABI4OrPS4, clang::TargetInfo::CCK_MicrosoftWin64, clang::Sema::Context, clang::CXXRecordDecl::ctors(), clang::CXXRecordDecl::defaultedCopyConstructorIsDeleted(), clang::CXXRecordDecl::defaultedDestructorIsDeleted(), clang::CXXRecordDecl::defaultedMoveConstructorIsDeleted(), clang::Sema::getASTContext(), clang::CXXRecordDecl::getDestructor(), clang::Sema::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::TypeDecl::getTypeForDecl(), clang::ASTContext::getTypeSize(), clang::CXXRecordDecl::hasNonTrivialCopyConstructorForCall(), clang::CXXRecordDecl::hasNonTrivialDestructorForCall(), clang::CXXRecordDecl::hasTrivialCopyConstructor(), clang::CXXRecordDecl::hasTrivialCopyConstructorForCall(), clang::CXXRecordDecl::hasTrivialDestructorForCall(), clang::CXXRecordDecl::hasTrivialMoveConstructorForCall(), clang::TagDecl::isDependentType(), clang::Decl::isInvalidDecl(), clang::CXXRecordDecl::methods(), clang::CXXRecordDecl::needsImplicitCopyConstructor(), clang::CXXRecordDecl::needsImplicitDestructor(), and clang::CXXRecordDecl::needsImplicitMoveConstructor().
Referenced by clang::Sema::CheckCompletedCXXClass(), and clang::TextNodeDumper::VisitCXXRecordDecl().
CastForMoving()
static Expr * CastForMoving (Sema & SemaRef, Expr * E) static
Definition at line 4818 of file SemaDeclCXX.cpp.
References clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildReferenceType(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), clang::ASTContext::getTrivialTypeSourceInfo(), and clang::Expr::getType().
Referenced by BuildImplicitBaseInitializer(), and BuildImplicitMemberInitializer().
CheckAbstractClassUsage() [1/3]
static void CheckAbstractClassUsage (AbstractUsageInfo & Info, CXXRecordDecl * RD) static
Check for invalid uses of an abstract type within a class definition.
Definition at line 6139 of file SemaDeclCXX.cpp.
References clang::Sema::AbstractFieldType, CheckAbstractClassUsage(), clang::DeclContext::decls(), clang::TypeSourceInfo::getTypeLoc(), and clang::DeclaratorDecl::getTypeSourceInfo().
CheckAbstractClassUsage() [2/3]
static void CheckAbstractClassUsage (AbstractUsageInfo & Info, FunctionDecl * FD) static
Check for invalid uses of an abstract type in a function declaration.
Definition at line 6112 of file SemaDeclCXX.cpp.
References clang::Sema::AbstractNone, clang::FunctionDecl::doesThisDeclarationHaveABody(), clang::TypeSourceInfo::getTypeLoc(), and clang::DeclaratorDecl::getTypeSourceInfo().
Referenced by CheckAbstractClassUsage(), and clang::Sema::CheckCompletedCXXClass().
CheckAbstractClassUsage() [3/3]
static void CheckAbstractClassUsage (AbstractUsageInfo & Info, VarDecl * VD) static
Check for invalid uses of an abstract type in a variable0 declaration.
Definition at line 6127 of file SemaDeclCXX.cpp.
References clang::Sema::AbstractVariableType, clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), and clang::VarDecl::isThisDeclarationADefinition().
checkArrayDecomposition()
static bool checkArrayDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const ConstantArrayType * CAT) static
Definition at line 983 of file SemaDeclCXX.cpp.
References checkArrayLikeDecomposition(), clang::ArrayType::getElementType(), and clang::ConstantArrayType::getSize().
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
checkArrayLikeDecomposition()
static bool checkArrayLikeDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const llvm::APSInt & NumElems, QualType ElemType) static
Definition at line 968 of file SemaDeclCXX.cpp.
References clang::Sema::ActOnIntegerConstant(), checkSimpleDecomposition(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
Referenced by checkArrayDecomposition(), and checkVectorDecomposition().
checkComplexDecomposition()
static bool checkComplexDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const ComplexType * CT) static
Definition at line 1000 of file SemaDeclCXX.cpp.
References checkSimpleDecomposition(), clang::Sema::Context, clang::ComplexType::getElementType(), clang::ASTContext::getQualifiedType(), and clang::QualType::getQualifiers().
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
CheckConstexprCtorInitializer()
static bool CheckConstexprCtorInitializer (Sema & SemaRef, const FunctionDecl * Dcl, FieldDecl * Field, llvm::SmallSet< Decl *, 16 > & Inits, bool & Diagnosed, Sema::CheckConstexprKind Kind) static
Check that the given field is initialized within a constexpr constructor.
Parameters
Dcl The constexpr constructor being checked.
Field The field being checked. This may be a member of an anonymous struct or union nested within the class being checked.
Inits All declarations, including anonymous struct/union members and indirect members, for which any initialization was provided.
Diagnosed Whether we've emitted the error message yet. Used to attach multiple notes for different members to the same error.
Kind Whether we're diagnosing a constructor as written or determining whether the formal requirements are satisfied.
Returns
false if we're checking for validity and the constructor does not satisfy the requirements on a constexpr constructor.
Definition at line 2012 of file SemaDeclCXX.cpp.
References CheckConstexprCtorInitializer(), clang::Sema::Diag(), clang::RecordDecl::fields(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), and clang::TagDecl::isUnion().
Referenced by CheckConstexprCtorInitializer(), and CheckConstexprFunctionBody().
CheckConstexprDeclStmt()
static bool CheckConstexprDeclStmt (Sema & SemaRef, const FunctionDecl * Dcl, DeclStmt * DS, SourceLocation & Cxx1yLoc, Sema::CheckConstexprKind Kind) static
Check the given declaration statement is legal within a constexpr function body.
C++11 [dcl.constexpr]p3,p4, and C++1y [dcl.constexpr]p3.
Returns
true if the body is OK (maybe only as an extension), false if we have diagnosed a problem.
Definition at line 1859 of file SemaDeclCXX.cpp.
References clang::cast(), CheckLiteralType(), clang::DeclStmt::decls(), clang::Sema::Diag(), clang::DeclStmt::getBeginLoc(), clang::TypeLoc::getBeginLoc(), clang::Sema::getLangOpts(), clang::TypeLoc::getSourceRange(), clang::TypeLoc::getType(), clang::isa(), clang::FunctionDecl::isConsteval(), clang::SourceLocation::isValid(), clang::Sema::LangOpts, and clang::VarDecl::TLS_Dynamic.
Referenced by CheckConstexprFunctionStmt().
CheckConstexprDestructorSubobjects()
static bool CheckConstexprDestructorSubobjects (Sema & SemaRef, const CXXDestructorDecl * DD, Sema::CheckConstexprKind Kind) static
Determine whether a destructor cannot be constexpr due to.
Definition at line 1686 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::bases(), clang::Sema::Diag(), clang::RecordDecl::fields(), clang::FunctionDecl::getConstexprKind(), clang::Decl::getLocation(), clang::CXXMethodDecl::getParent(), and clang::CXXRecordDecl::hasConstexprDestructor().
Referenced by clang::Sema::CheckConstexprFunctionDefinition().
CheckConstexprFunctionBody()
static bool CheckConstexprFunctionBody (Sema & SemaRef, const FunctionDecl * Dcl, Stmt * Body, Sema::CheckConstexprKind Kind) static
Check the body for the given constexpr function declaration only contains the permitted types of statement.
C++11 [dcl.constexpr]p3,p4.
Returns
true if the body is OK, false if we have found or diagnosed a problem.
Definition at line 2230 of file SemaDeclCXX.cpp.
References CheckConstexprCtorInitializer(), CheckConstexprFunctionStmt(), clang::Stmt::children(), clang::Sema::Diag(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::RecordDecl::fields(), clang::Stmt::getBeginLoc(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::CXXRecordDecl::getNumBases(), clang::CXXRecordDecl::getNumVBases(), clang::FunctionDecl::getReturnType(), clang::CXXRecordDecl::hasVariantMembers(), clang::isa(), clang::FunctionDecl::isConsteval(), clang::Type::isDependentType(), clang::Expr::isPotentialConstantExpr(), clang::TagDecl::isUnion(), clang::SourceLocation::isValid(), and N.
Referenced by clang::Sema::CheckConstexprFunctionDefinition().
CheckConstexprFunctionStmt()
static bool CheckConstexprFunctionStmt (Sema & SemaRef, const FunctionDecl * Dcl, Stmt * S, SmallVectorImpl< SourceLocation > & ReturnStmts, SourceLocation & Cxx1yLoc, SourceLocation & Cxx2aLoc, SourceLocation & Cxx2bLoc, Sema::CheckConstexprKind Kind) static
Check the provided statement is allowed in a constexpr function definition.
Definition at line 2068 of file SemaDeclCXX.cpp.
References clang::CompoundStmt::body(), clang::cast(), CheckConstexprDeclStmt(), CheckConstexprFunctionStmt(), clang::Sema::Diag(), clang::IfStmt::getElse(), clang::Sema::getLangOpts(), clang::IfStmt::getThen(), clang::isa(), clang::FunctionDecl::isConsteval(), clang::SourceLocation::isInvalid(), and clang::SourceLocation::isValid().
Referenced by CheckConstexprFunctionBody(), and CheckConstexprFunctionStmt().
CheckConstexprParameterTypes()
static bool CheckConstexprParameterTypes (Sema & SemaRef, const FunctionDecl * FD, Sema::CheckConstexprKind Kind) static
Check whether a function's parameter types are all literal types.
If so, return true. If not, produce a suitable diagnostic and return false.
Definition at line 1717 of file SemaDeclCXX.cpp.
References clang::Type::castAs(), CheckLiteralType(), clang::Decl::getLocation(), clang::FunctionDecl::getParamDecl(), clang::ParmVarDecl::getSourceRange(), clang::ValueDecl::getType(), and clang::FunctionDecl::isConsteval().
Referenced by clang::Sema::CheckConstexprFunctionDefinition(), and clang::Sema::CheckExplicitlyDefaultedComparison().
CheckConstexprReturnType()
static bool CheckConstexprReturnType (Sema & SemaRef, const FunctionDecl * FD, Sema::CheckConstexprKind Kind) static
Check whether a function's return type is a literal type.
If so, return true. If not, produce a suitable diagnostic and return false.
Definition at line 1739 of file SemaDeclCXX.cpp.
References CheckLiteralType(), clang::Decl::getLocation(), clang::FunctionDecl::getReturnType(), and clang::FunctionDecl::isConsteval().
Referenced by clang::Sema::CheckConstexprFunctionDefinition(), and clang::Sema::CheckExplicitlyDefaultedComparison().
checkCUDADeviceBuiltinSurfaceClassTemplate()
static void checkCUDADeviceBuiltinSurfaceClassTemplate (Sema & S, CXXRecordDecl * Class) static
Definition at line 6307 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateDecl::getTemplateParameters(), N, and clang::TemplateParameterList::size().
Referenced by clang::Sema::CheckCompletedCXXClass().
checkCUDADeviceBuiltinTextureClassTemplate()
static void checkCUDADeviceBuiltinTextureClassTemplate (Sema & S, CXXRecordDecl * Class) static
Definition at line 6361 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateDecl::getTemplateParameters(), N, and clang::TemplateParameterList::size().
Referenced by clang::Sema::CheckCompletedCXXClass().
checkForMultipleExportedDefaultConstructors()
static void checkForMultipleExportedDefaultConstructors (Sema & S, CXXRecordDecl * Class) static
Definition at line 6269 of file SemaDeclCXX.cpp.
References clang::Sema::CheckCXXDefaultArgExpr(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiscardCleanupsInEvaluationContext(), clang::TargetInfo::getCXXABI(), clang::Attr::getLocation(), clang::Decl::getLocation(), clang::ASTContext::getTargetInfo(), clang::TargetCXXABI::isMicrosoft(), and clang::Member.
Referenced by clang::Sema::ActOnFinishCXXMemberDecls().
checkLiteralOperatorTemplateParameterList()
static bool checkLiteralOperatorTemplateParameterList (Sema & SemaRef, FunctionTemplateDecl * TpDecl) static
Definition at line 16287 of file SemaDeclCXX.cpp.
References clang::ASTContext::CharTy, clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::SourceRange::getBegin(), clang::TemplateTypeParmDecl::getDepth(), clang::TemplateTypeParmDecl::getIndex(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateParameterList::getSourceRange(), clang::TemplateDecl::getTemplateParameters(), clang::ValueDecl::getType(), clang::ASTContext::hasSameType(), clang::Sema::inTemplateInstantiation(), clang::Type::isRecordType(), clang::Decl::isTemplateParameterPack(), and clang::TemplateParameterList::size().
Referenced by clang::Sema::CheckLiteralOperatorDeclaration().
CheckLiteralType()
template<typename... Ts> static bool CheckLiteralType (Sema & SemaRef, Sema::CheckConstexprKind Kind, SourceLocation Loc, QualType T, unsigned DiagID, Ts &&... DiagArgs) static
Check that the given type is a literal type.
Issue a diagnostic if not, if Kind is Diagnose.
Returns
true if a problem has been found (and optionally diagnosed).
Definition at line 1667 of file SemaDeclCXX.cpp.
References clang::Sema::Context, and clang::Sema::RequireLiteralType().
checkMemberDecomposition()
static bool checkMemberDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const CXXRecordDecl * OrigRD) static
Definition at line 1406 of file SemaDeclCXX.cpp.
References clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildQualifiedType(), clang::Sema::CheckStructuredBindingMemberAccess(), clang::Sema::Context, clang::Sema::Diag(), clang::RecordDecl::fields(), findDecomposableBaseClass(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::DeclAccessPair::getAccess(), clang::DeclAccessPair::getDecl(), clang::Decl::getLocation(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::ASTContext::getRecordType(), clang::Sema::ImpCastExprToType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::CXXRecordDecl::isLambda(), clang::Type::isUnionType(), clang::DeclAccessPair::make(), clang::CXXRecordDecl::MergeAccess(), clang::Qualifiers::removeConst(), clang::Sema::RequireCompleteType(), and clang::VK_LValue.
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
checkMethodTypeQualifiers()
static void checkMethodTypeQualifiers (Sema & S, Declarator & D, unsigned DiagID) static
Definition at line 10681 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::DeclSpec::forEachQualifier(), clang::Declarator::getFunctionTypeInfo(), clang::DeclaratorChunk::FunctionTypeInfo::hasMethodTypeQualifiers(), clang::Declarator::isInvalidType(), clang::DeclaratorChunk::FunctionTypeInfo::MethodQualifiers, and clang::Declarator::setInvalidType().
Referenced by clang::Sema::CheckConstructorDeclarator(), and clang::Sema::CheckDestructorDeclarator().
checkMoveAssignmentForRepeatedMove()
static void checkMoveAssignmentForRepeatedMove (Sema & S, CXXRecordDecl * Class, SourceLocation CurrentLocation) static
Check if we're implicitly defining a move assignment operator for a class with virtual bases.
Such a move assignment might move-assign the virtual base multiple times.
Definition at line 15030 of file SemaDeclCXX.cpp.
References clang::Sema::CXXMoveAssignment, clang::Sema::Diag(), clang::Type::getAsCXXRecordDecl(), clang::CXXBaseSpecifier::getBeginLoc(), clang::CXXRecordDecl::getCanonicalDecl(), clang::Sema::SpecialMemberOverloadResult::getMethod(), clang::CXXBaseSpecifier::getSourceRange(), clang::CXXBaseSpecifier::getType(), clang::FunctionDecl::isDefaulted(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::FunctionDecl::isTrivial(), clang::CXXBaseSpecifier::isVirtual(), and clang::Sema::LookupSpecialMember().
Referenced by clang::Sema::DefineImplicitMoveAssignment().
CheckOperatorDeleteDeclaration()
static bool CheckOperatorDeleteDeclaration (Sema & SemaRef, FunctionDecl * FnDecl) static
Definition at line 16076 of file SemaDeclCXX.cpp.
References CheckOperatorNewDeleteDeclarationScope(), CheckOperatorNewDeleteTypes(), clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getCanonicalType(), clang::Decl::getLocation(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getPointerType(), clang::ASTContext::getRecordType(), clang::DeclContext::isDependentContext(), clang::FunctionDecl::isDestroyingOperatorDelete(), clang::Sema::isUsualDeallocationFunction(), clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by clang::Sema::CheckOverloadedOperatorDeclaration().
CheckOperatorNewDeclaration()
static bool CheckOperatorNewDeclaration (Sema & SemaRef, const FunctionDecl * FnDecl) static
Definition at line 16045 of file SemaDeclCXX.cpp.
References CheckOperatorNewDeleteDeclarationScope(), CheckOperatorNewDeleteTypes(), clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getCanonicalType(), clang::NamedDecl::getDeclName(), clang::ParmVarDecl::getDefaultArgRange(), clang::Decl::getLocation(), clang::FunctionDecl::getParamDecl(), clang::ASTContext::getSizeType(), clang::ParmVarDecl::hasDefaultArg(), and clang::ASTContext::VoidPtrTy.
Referenced by clang::Sema::CheckOverloadedOperatorDeclaration().
CheckOperatorNewDeleteDeclarationScope()
static bool CheckOperatorNewDeleteDeclarationScope (Sema & SemaRef, const FunctionDecl * FnDecl) inline static
Definition at line 15945 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::DeclContext::getRedeclContext(), clang::FunctionDecl::getStorageClass(), and clang::SC_Static.
Referenced by CheckOperatorDeleteDeclaration(), and CheckOperatorNewDeclaration().
CheckOperatorNewDeleteTypes()
static bool CheckOperatorNewDeleteTypes (Sema & SemaRef, const FunctionDecl * FnDecl, CanQualType ExpectedResultType, CanQualType ExpectedFirstParamType, unsigned DependentParamTypeDiag, unsigned InvalidParamTypeDiag) inline static
Definition at line 15974 of file SemaDeclCXX.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::CanQual< typename >::getAs(), clang::Type::getAs(), clang::ASTContext::getCanonicalType(), clang::NamedDecl::getDeclName(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), clang::CanQual< typename >::getUnqualifiedType(), clang::Type::isDependentType(), and RemoveAddressSpaceFromPtr().
Referenced by CheckOperatorDeleteDeclaration(), and CheckOperatorNewDeclaration().
checkSimpleDecomposition()
static bool checkSimpleDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const llvm::APSInt & NumElems, QualType ElemType, llvm::function_ref< ExprResult(SourceLocation, Expr *, unsigned)> GetInit) static
Definition at line 941 of file SemaDeclCXX.cpp.
References clang::Sema::BuildDeclRefExpr(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getLocation(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), toString(), UINT_MAX, and clang::VK_LValue.
Referenced by checkArrayLikeDecomposition(), and checkComplexDecomposition().
checkTrivialClassMembers()
static bool checkTrivialClassMembers (Sema & S, CXXRecordDecl * RD, Sema::CXXSpecialMember CSM, bool ConstArg, Sema::TrivialABIHandling TAH, bool Diagnose) static
Check whether the members of a class type allow a special member to be trivial.
Definition at line 9944 of file SemaDeclCXX.cpp.
References checkTrivialClassMembers(), checkTrivialSubobjectCall(), clang::Sema::Context, clang::Sema::CXXDefaultConstructor, clang::Sema::Diag(), clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getBaseElementType(), clang::QualType::getObjCLifetime(), clang::QualType::hasNonTrivialObjCLifetime(), and TSK_Field.
Referenced by checkTrivialClassMembers(), and clang::Sema::SpecialMemberIsTrivial().
checkTrivialSubobjectCall()
static bool checkTrivialSubobjectCall (Sema & S, SourceLocation SubobjLoc, QualType SubType, bool ConstRHS, Sema::CXXSpecialMember CSM, TrivialSubobjectKind Kind, Sema::TrivialABIHandling TAH, bool Diagnose) static
Check whether the special member selected for a given type would be trivial.
Definition at line 9893 of file SemaDeclCXX.cpp.
References clang::QualType::addConst(), clang::Sema::CXXDefaultConstructor, clang::Sema::Diag(), findTrivialSpecialMember(), findUserDeclaredCtor(), clang::Type::getAsCXXRecordDecl(), clang::QualType::getCVRQualifiers(), clang::Decl::getLocation(), clang::QualType::getUnqualifiedType(), clang::FunctionDecl::isUserProvided(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::TAH_IgnoreTrivialABI, and TSK_CompleteObject.
Referenced by checkTrivialClassMembers(), clang::Sema::DiagnoseNontrivial(), and clang::Sema::SpecialMemberIsTrivial().
checkTupleLikeDecomposition()
static bool checkTupleLikeDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, VarDecl * Src, QualType DecompType, const llvm::APSInt & TupleSize) static
Definition at line 1196 of file SemaDeclCXX.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::TemplateArgumentListInfo::addArgument(), clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildReferenceType(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::Context, clang::ImplicitCastExpr::Create(), clang::UnresolvedLookupExpr::Create(), clang::VarDecl::Create(), clang::InitializationKind::CreateCopy(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAsCXXRecordDecl(), clang::Decl::getDeclContext(), clang::Preprocessor::getIdentifierInfo(), clang::Decl::getLexicalDeclContext(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::ASTContext::getSizeType(), clang::VarDecl::getStorageClass(), getTrivialIntegralTemplateArgument(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::VarDecl::getTSCSpec(), getTupleLikeElementType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::InitializedEntity::InitializeBinding(), clang::LookupResult::isAmbiguous(), clang::Sema::isCompleteType(), clang::VarDecl::isInlineSpecified(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Expr::isLValue(), clang::Type::isLValueReferenceType(), clang::QualType::isNull(), clang::Sema::LookupMemberName, clang::Sema::LookupQualifiedName(), clang::InitializationSequence::Perform(), clang::Sema::PP, clang::TemplateParameterList::size(), toString(), UINT_MAX, clang::VK_LValue, and clang::VK_XValue.
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
checkVectorDecomposition()
static bool checkVectorDecomposition (Sema & S, ArrayRef< BindingDecl * > Bindings, ValueDecl * Src, QualType DecompType, const VectorType * VT) static
Definition at line 991 of file SemaDeclCXX.cpp.
References checkArrayLikeDecomposition(), clang::Sema::Context, clang::VectorType::getElementType(), clang::VectorType::getNumElements(), clang::ASTContext::getQualifiedType(), and clang::QualType::getQualifiers().
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
CollectFieldInitializer()
static bool CollectFieldInitializer (Sema & SemaRef, BaseAndFieldInfo & Info, FieldDecl * Field, IndirectFieldDecl * Indirect = nullptr) static
Definition at line 5188 of file SemaDeclCXX.cpp.
References clang::Sema::BuildCXXDefaultInitExpr(), BuildImplicitMemberInitializer(), clang::Sema::checkInitializerLifetime(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getLocation(), clang::InitializedEntity::InitializeMember(), isIncompleteOrZeroLengthArrayType(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
Referenced by clang::Sema::SetCtorInitializers().
ComputeDefaultedComparisonExceptionSpec()
static Sema::ImplicitExceptionSpecification ComputeDefaultedComparisonExceptionSpec (Sema & S, SourceLocation Loc, FunctionDecl * FD, Sema::DefaultedComparisonKind DCK) static
Definition at line 9052 of file SemaDeclCXX.cpp.
References clang::Sema::ImplicitExceptionSpecification::CalledStmt(), clang::cast(), clang::FunctionDecl::getBody(), clang::Decl::getEndLoc(), clang::DeclContext::getLexicalParent(), clang::Decl::getLocation(), clang::FunctionDecl::hasBody(), clang::Decl::isInvalidDecl(), and clang::SourceLocation::isValid().
Referenced by computeImplicitExceptionSpec().
ComputeDefaultedSpecialMemberExceptionSpec()
static Sema::ImplicitExceptionSpecification ComputeDefaultedSpecialMemberExceptionSpec (Sema & S, SourceLocation Loc, CXXMethodDecl * MD, Sema::CXXSpecialMember CSM, Sema::InheritedConstructorInfo * ICI) static
Definition at line 13562 of file SemaDeclCXX.cpp.
References clang::Sema::Context, clang::Decl::getLocation(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getRecordType(), clang::Decl::isInvalidDecl(), and clang::Sema::RequireCompleteType().
Referenced by computeImplicitExceptionSpec().
computeImplicitExceptionSpec()
static Sema::ImplicitExceptionSpecification computeImplicitExceptionSpec (Sema & S, SourceLocation Loc, FunctionDecl * FD) static
Definition at line 7514 of file SemaDeclCXX.cpp.
References clang::cast(), ComputeDefaultedComparisonExceptionSpec(), ComputeDefaultedSpecialMemberExceptionSpec(), clang::Sema::CXXDefaultConstructor, and clang::Sema::getDefaultedFunctionKind().
Referenced by clang::Sema::EvaluateImplicitExceptionSpec().
ConvertAPValueToString()
static bool ConvertAPValueToString (const APValue & V, QualType T, SmallVectorImpl< char > & Str) static
Convert \V to a string we can present to the user in a diagnostic \T is the type of the expression that has been evaluated into \V.
Definition at line 16804 of file SemaDeclCXX.cpp.
References V.
Referenced by clang::Sema::DiagnoseStaticAssertDetails().
defaultedSpecialMemberIsConstexpr()
static bool defaultedSpecialMemberIsConstexpr (Sema & S, CXXRecordDecl * ClassDecl, Sema::CXXSpecialMember CSM, bool ConstArg, CXXConstructorDecl * InheritedCtor = nullptr, Sema::InheritedConstructorInfo * Inherited = nullptr) static
Determine whether the specified special member function would be constexpr if it were implicitly defined.
Definition at line 7377 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::bases(), clang::cast(), clang::Sema::Context, clang::Sema::CXXCopyAssignment, clang::Sema::CXXCopyConstructor, clang::Sema::CXXDefaultConstructor, clang::Sema::CXXDestructor, clang::Sema::CXXInvalid, clang::Sema::CXXMoveAssignment, clang::Sema::CXXMoveConstructor, clang::CXXRecordDecl::defaultedDefaultConstructorIsConstexpr(), clang::CXXRecordDecl::defaultedDestructorIsConstexpr(), clang::RecordDecl::fields(), clang::ASTContext::getBaseElementType(), clang::Sema::getLangOpts(), clang::CXXRecordDecl::getNumVBases(), clang::CXXRecordDecl::hasInClassInitializer(), clang::CXXRecordDecl::hasVariantMembers(), clang::CXXRecordDecl::isLiteral(), clang::TagDecl::isUnion(), and specialMemberIsConstexpr().
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), and clang::Sema::findInheritingConstructor().
DefineDefaultedFunction()
static void DefineDefaultedFunction (Sema & S, FunctionDecl * FD, SourceLocation DefaultLoc) static
Definition at line 6730 of file SemaDeclCXX.cpp.
References clang::Sema::DefaultedFunctionKind::asComparison(), clang::Sema::DefaultedFunctionKind::asSpecialMember(), clang::Sema::CXXCopyAssignment, clang::Sema::CXXCopyConstructor, clang::Sema::CXXDefaultConstructor, clang::Sema::CXXDestructor, clang::Sema::CXXInvalid, clang::Sema::CXXMoveAssignment, clang::Sema::CXXMoveConstructor, clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitCopyConstructor(), clang::Sema::DefineImplicitDefaultConstructor(), clang::Sema::DefineImplicitDestructor(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DefineImplicitMoveConstructor(), clang::Sema::getDefaultedFunctionKind(), and clang::Sema::DefaultedFunctionKind::isComparison().
Referenced by clang::Sema::ActOnFinishCXXNonNestedClass(), clang::Sema::CheckCompletedCXXClass(), and clang::Sema::SetDeclDefaulted().
DelegatingCycleHelper()
static void DelegatingCycleHelper (CXXConstructorDecl * Ctor, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > & Valid, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > & Invalid, llvm::SmallPtrSet< CXXConstructorDecl *, 4 > & Current, Sema & S) static
Definition at line 18501 of file SemaDeclCXX.cpp.
References clang::C, clang::cast(), DelegatingCycleHelper(), clang::Sema::Diag(), clang::CXXConstructorDecl::getCanonicalDecl(), clang::CXXConstructorDecl::getTargetConstructor(), clang::FunctionDecl::hasBody(), clang::CXXConstructorDecl::init_begin(), clang::Invalid, clang::Decl::isInvalidDecl(), and clang::Target.
Referenced by clang::Sema::CheckDelegatingCtorCycles(), and DelegatingCycleHelper().
DiagnoseBaseOrMemInitializerOrder()
static void DiagnoseBaseOrMemInitializerOrder (Sema & SemaRef, const CXXConstructorDecl * Constructor, ArrayRef< CXXCtorInitializer * > Inits) static
Definition at line 5492 of file SemaDeclCXX.cpp.
References AddInitializerToDiag(), clang::CXXRecordDecl::bases(), clang::Sema::Context, clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Sema::Diags, clang::RecordDecl::fields(), GetKeyForBase(), GetKeyForMember(), clang::Sema::getLangOpts(), clang::CXXCtorInitializer::getSourceLocation(), clang::Sema::getSourceManager(), clang::CXXCtorInitializer::getSourceRange(), clang::Lexer::getSourceText(), clang::CharSourceRange::getTokenRange(), clang::DiagnosticsEngine::isIgnored(), PopulateKeysForFields(), and clang::CXXRecordDecl::vbases().
Referenced by clang::Sema::ActOnMemInitializers().
diagnoseDeprecatedCopyOperation()
static void diagnoseDeprecatedCopyOperation (Sema & S, CXXMethodDecl * CopyOp) static
Diagnose an implicit copy operation for a class which is odr-used, but which is deprecated because the class has a user-declared copy constructor, copy assignment operator, or destructor.
Definition at line 14691 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::ctors(), clang::Sema::Diag(), clang::CXXRecordDecl::getDestructor(), clang::Decl::getLocation(), clang::CXXMethodDecl::getParent(), clang::CXXRecordDecl::hasUserDeclaredCopyAssignment(), clang::CXXRecordDecl::hasUserDeclaredCopyConstructor(), clang::CXXRecordDecl::hasUserDeclaredDestructor(), clang::isa(), clang::Decl::isImplicit(), clang::FunctionDecl::isUserProvided(), and clang::CXXRecordDecl::methods().
Referenced by clang::Sema::DefineImplicitCopyAssignment(), and clang::Sema::DefineImplicitCopyConstructor().
DiagnoseNamespaceInlineMismatch()
static void DiagnoseNamespaceInlineMismatch (Sema & S, SourceLocation KeywordLoc, SourceLocation Loc, IdentifierInfo * II, bool * IsInline, NamespaceDecl * PrevNS) static
Diagnose a mismatch in 'inline' qualifiers when a namespace is reopened.
Definition at line 11348 of file SemaDeclCXX.cpp.
References clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::Decl::getLocation(), and clang::NamespaceDecl::isInline().
Referenced by clang::Sema::ActOnStartNamespaceDef().
extendLeft()
static void extendLeft (SourceRange & R, SourceRange Before) static
Definition at line 10959 of file SemaDeclCXX.cpp.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::SourceLocation::isInvalid(), clang::SourceRange::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Referenced by clang::Sema::CheckConversionDeclarator().
extendRight()
static void extendRight (SourceRange & R, SourceRange After) static
Definition at line 10967 of file SemaDeclCXX.cpp.
References clang::SourceRange::getBegin(), clang::SourceLocation::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Referenced by clang::Sema::CheckConversionDeclarator().
FindBaseInitializer()
static bool FindBaseInitializer (Sema & SemaRef, CXXRecordDecl * ClassDecl, QualType BaseType, const CXXBaseSpecifier *& DirectBaseSpec, const CXXBaseSpecifier *& VirtualBaseSpec) static
Find the direct and/or virtual base specifiers that correspond to the given base type, for use in base initialization within a constructor.
Definition at line 4227 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::bases(), clang::Sema::Context, clang::Decl::getLocation(), clang::ASTContext::getTypeDeclType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Sema::IsDerivedFrom(), and clang::CXXBaseSpecifier::isVirtual().
Referenced by clang::Sema::BuildBaseInitializer(), and clang::Sema::BuildMemInitializer().
findCircularInheritance()
static bool findCircularInheritance (const CXXRecordDecl * Class, const CXXRecordDecl * Current) static
Determine whether the given class is a base class of the given class, including looking at dependent bases.
Definition at line 2609 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::CheckBaseSpecifier().
findDecomposableBaseClass()
static DeclAccessPair findDecomposableBaseClass (Sema & S, SourceLocation Loc, const CXXRecordDecl * RD, CXXCastPath & BasePath) static
Find the base class to decompose in a built-in decomposition of a class type.
This base class search is, unfortunately, not quite like any other that we perform anywhere else in C++.
Definition at line 1335 of file SemaDeclCXX.cpp.
References clang::CXXBasePath::Access, clang::AS_public, clang::Sema::BuildBasePathArray(), clang::Sema::CheckBaseClassAccess(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getAmbiguousPathsDisplayString(), clang::ASTContext::getCanonicalType(), clang::ASTContext::getRecordType(), clang::CXXRecordDecl::hasDirectFields(), clang::ASTContext::hasSameType(), clang::CXXRecordDecl::lookupInBases(), clang::DeclAccessPair::make(), P, and Specifier.
Referenced by checkMemberDecomposition().
findDirectBaseWithType()
static CXXBaseSpecifier * findDirectBaseWithType (CXXRecordDecl * Derived, QualType DesiredBase, bool & AnyDependentBases) static
Find the base specifier for a base class with the given type.
Definition at line 12439 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::bases(), clang::Type::getCanonicalTypeUnqualified(), and clang::CanQual< typename >::getUnqualifiedType().
Referenced by clang::Sema::CheckInheritingConstructorUsingDecl().
findImplicitlyDeclaredEqualityComparisons()
static void findImplicitlyDeclaredEqualityComparisons (ASTContext & Ctx, CXXRecordDecl * RD, llvm::SmallVectorImpl< FunctionDecl * > & Spaceships) static
Find the equality comparison functions that should be implicitly declared in a given class definition, per C++2a [class.compare.default]p3.
Definition at line 10397 of file SemaDeclCXX.cpp.
References clang::ASTContext::DeclarationNames, clang::DeclContextLookupResult::empty(), clang::CXXRecordDecl::friends(), clang::DeclarationNameTable::getCXXOperatorName(), clang::FunctionDecl::getOverloadedOperator(), clang::FunctionDecl::isExplicitlyDefaulted(), and clang::DeclContext::lookup().
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass().
findTrivialSpecialMember()
static bool findTrivialSpecialMember (Sema & S, CXXRecordDecl * RD, Sema::CXXSpecialMember CSM, unsigned Quals, bool ConstRHS, Sema::TrivialABIHandling TAH, CXXMethodDecl ** Selected) static
Perform lookup for a special member of the specified kind, and determine whether it is trivial.
If the triviality can be determined without the lookup, skip it. This is intended for use when determining whether a special member of a containing object is trivial, and thus does not ever perform overload resolution for default constructors.
If Selected is not NULL, *Selected will be filled in with the member that was most likely to be intended to be trivial, if any.
If ForCall is true, look at CXXRecord::HasTrivialSpecialMembersForCall to determine whether the special member is trivial.
Definition at line 9738 of file SemaDeclCXX.cpp.
References clang::Sema::SpecialMemberOverloadResult::Ambiguous, clang::Qualifiers::Const, clang::CXXRecordDecl::ctors(), clang::Sema::CXXCopyAssignment, clang::Sema::CXXCopyConstructor, clang::Sema::CXXDefaultConstructor, clang::Sema::CXXDestructor, clang::Sema::CXXInvalid, clang::Sema::CXXMoveAssignment, clang::Sema::CXXMoveConstructor, clang::Sema::DeclareImplicitDefaultConstructor(), clang::Sema::DeclareImplicitDestructor(), clang::CXXRecordDecl::getDestructor(), clang::Sema::SpecialMemberOverloadResult::getKind(), clang::Sema::SpecialMemberOverloadResult::getMethod(), clang::CXXRecordDecl::hasTrivialCopyAssignment(), clang::CXXRecordDecl::hasTrivialCopyConstructor(), clang::CXXRecordDecl::hasTrivialCopyConstructorForCall(), clang::CXXRecordDecl::hasTrivialDefaultConstructor(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::CXXRecordDecl::hasTrivialDestructorForCall(), clang::FunctionDecl::isTrivial(), clang::FunctionDecl::isTrivialForCall(), clang::FunctionDecl::isUserProvided(), lookupCallFromSpecialMember(), clang::CXXRecordDecl::needsImplicitDefaultConstructor(), clang::CXXRecordDecl::needsImplicitDestructor(), clang::Sema::SpecialMemberOverloadResult::NoMemberOrDeleted, and clang::Sema::TAH_ConsiderTrivialABI.
Referenced by checkTrivialSubobjectCall().
findUserDeclaredCtor()
static CXXConstructorDecl * findUserDeclaredCtor (CXXRecordDecl * RD) static
Definition at line 9865 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::ctors(), clang::DeclContext::decls_begin(), and clang::DeclContext::decls_end().
Referenced by checkTrivialSubobjectCall().
functionDeclHasDefaultArgument()
static bool functionDeclHasDefaultArgument (const FunctionDecl * FD) static
Definition at line 454 of file SemaDeclCXX.cpp.
References P, and clang::FunctionDecl::parameters().
Referenced by clang::Sema::ActOnFriendFunctionDecl(), and clang::Sema::MergeCXXFunctionDecl().
getImplicitMethodEPI()
static FunctionProtoType::ExtProtoInfo getImplicitMethodEPI (Sema & S, CXXMethodDecl * MD) static
Definition at line 7533 of file SemaDeclCXX.cpp.
References clang::Sema::Context, clang::EST_Unevaluated, clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::FunctionProtoType::ExtProtoInfo::ExtInfo, clang::ASTContext::getDefaultCallingConvention(), clang::FunctionProtoType::ExceptionSpecInfo::SourceDecl, clang::FunctionProtoType::ExceptionSpecInfo::Type, and clang::FunctionType::ExtInfo::withCallingConv().
GetKeyForBase()
static const void * GetKeyForBase (ASTContext & Context, QualType BaseType) static
Definition at line 5466 of file SemaDeclCXX.cpp.
References clang::ASTContext::getCanonicalType(), and clang::CanQual< typename >::getTypePtr().
Referenced by DiagnoseBaseOrMemInitializerOrder(), and GetKeyForMember().
GetKeyForMember()
static const void * GetKeyForMember (ASTContext & Context, CXXCtorInitializer * Member) static
Definition at line 5470 of file SemaDeclCXX.cpp.
References GetKeyForBase(), and clang::Member.
Referenced by clang::Sema::ActOnMemInitializers(), and DiagnoseBaseOrMemInitializerOrder().
getNamespaceDecl()
static NamespaceDecl * getNamespaceDecl (NamedDecl * D) inline static
getNamespaceDecl - Returns the namespace a decl represents.
If the decl is a namespace alias, returns the namespace it points to.
Definition at line 11540 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::ActOnNamespaceAliasDef().
getRecordDiagFromTagKind()
static unsigned getRecordDiagFromTagKind (TagTypeKind Tag) static
Get diagnostic select index for tag kind for record diagnostic message.
WARNING: Indexes apply to particular diagnostics only!
Returns
diagnostic select index.
Definition at line 1753 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::AttachBaseSpecifiers(), and clang::Sema::CheckConstexprFunctionDefinition().
getTrivialIntegralTemplateArgument()
static TemplateArgumentLoc getTrivialIntegralTemplateArgument (Sema & S, SourceLocation Loc, QualType T, uint64_t I) static
Definition at line 1091 of file SemaDeclCXX.cpp.
References clang::Sema::Context, clang::Sema::getTrivialTemplateArgumentLoc(), and clang::ASTContext::MakeIntValue().
Referenced by checkTupleLikeDecomposition(), and getTupleLikeElementType().
getTrivialTypeTemplateArgument()
static TemplateArgumentLoc getTrivialTypeTemplateArgument (Sema & S, SourceLocation Loc, QualType T) static
Definition at line 1098 of file SemaDeclCXX.cpp.
References clang::Sema::getTrivialTemplateArgumentLoc().
Referenced by getTupleLikeElementType(), and isTupleLike().
getTupleLikeElementType()
static QualType getTupleLikeElementType (Sema & S, SourceLocation Loc, unsigned I, QualType T) static
Returns
std::tuple_element<I, T>::type.
Definition at line 1151 of file SemaDeclCXX.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::Sema::Context, clang::Sema::Diag(), clang::LookupResult::empty(), clang::LookupResult::getAsSingle(), clang::Preprocessor::getIdentifierInfo(), clang::Decl::getLocation(), clang::ASTContext::getPrintingPolicy(), clang::LookupResult::getRepresentativeDecl(), clang::ASTContext::getSizeType(), getTrivialIntegralTemplateArgument(), getTrivialTypeTemplateArgument(), clang::ASTContext::getTypeDeclType(), clang::Sema::LookupOrdinaryName, lookupStdTypeTraitMember(), clang::Sema::PP, printTemplateArgs(), and clang::LookupResult::suppressDiagnostics().
Referenced by checkTupleLikeDecomposition().
hasOneRealArgument()
static bool hasOneRealArgument (MultiExprArg Args) static
Determine whether the given list arguments contains exactly one "real" (non-default) argument.
Definition at line 15719 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::BuildCXXConstructExpr().
InitializationHasSideEffects()
static bool InitializationHasSideEffects (const FieldDecl & FD) static
Definition at line 3337 of file SemaDeclCXX.cpp.
References clang::Type::getBaseElementTypeUnsafe(), and clang::ValueDecl::getType().
Referenced by clang::Sema::ActOnCXXMemberDeclarator().
IsEquivalentForUsingDecl()
static bool IsEquivalentForUsingDecl (ASTContext & Context, NamedDecl * D1, NamedDecl * D2) static
Determine whether a using declaration considers the given declarations as "equivalent", e.g., if they are redeclarations of the same entity or are both typedefs of the same type.
Definition at line 12143 of file SemaDeclCXX.cpp.
References clang::Decl::getCanonicalDecl(), and clang::ASTContext::hasSameType().
Referenced by clang::Sema::CheckUsingShadowDecl().
isIncompleteOrZeroLengthArrayType()
static bool isIncompleteOrZeroLengthArrayType (ASTContext & Context, QualType T) static
Determine whether the given type is an incomplete or zero-lenfgth array type.
Definition at line 5174 of file SemaDeclCXX.cpp.
References clang::ASTContext::getAsConstantArrayType().
Referenced by CollectFieldInitializer(), and clang::Sema::MarkBaseAndMemberDestructorsReferenced().
isNonlocalVariable()
static bool isNonlocalVariable (const Decl * D) static
Determine whether the given declaration is a global variable or static data member.
Definition at line 18156 of file SemaDeclCXX.cpp.
Referenced by clang::Sema::ActOnCXXEnterDeclInitializer(), and clang::Sema::ActOnCXXExitDeclInitializer().
isTupleLike()
static IsTupleLike isTupleLike (Sema & S, SourceLocation Loc, QualType T, llvm::APSInt & Size) static
Definition at line 1104 of file SemaDeclCXX.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::Context, clang::Sema::Diag(), clang::LookupResult::empty(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Preprocessor::getIdentifierInfo(), clang::ASTContext::getPrintingPolicy(), getTrivialTypeTemplateArgument(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::LookupOrdinaryName, lookupStdTypeTraitMember(), clang::Sema::PP, printTemplateArgs(), and clang::Sema::VerifyIntegerConstantExpression().
Referenced by clang::Sema::CheckCompleteDecompositionDeclaration().
IsUsingDirectiveInToplevelContext()
static bool IsUsingDirectiveInToplevelContext (DeclContext * CurContext) static
Determine whether a using statement is in a context where it will be apply in all contexts.
Definition at line 11859 of file SemaDeclCXX.cpp.
References clang::DeclContext::getDeclKind(), clang::DeclContext::getParent(), and IsUsingDirectiveInToplevelContext().
Referenced by clang::Sema::ActOnUsingDirective(), and IsUsingDirectiveInToplevelContext().
isVirtualDirectBase()
static bool isVirtualDirectBase (CXXRecordDecl * Derived, CXXRecordDecl * Base) static
Determine whether a direct base class is a virtual base class.
Definition at line 12337 of file SemaDeclCXX.cpp.
References clang::CXXRecordDecl::bases(), and clang::CXXRecordDecl::getNumVBases().
Referenced by clang::Sema::BuildUsingShadowDecl().
lookupCallFromSpecialMember()
static Sema::SpecialMemberOverloadResult lookupCallFromSpecialMember (Sema & S, CXXRecordDecl * Class, Sema::CXXSpecialMember CSM, unsigned FieldQuals, bool ConstRHS) static
Look up the special member function that would be called by a special member function for a subobject of class type.
Parameters
Class The class type of the subobject.
CSM The kind of special member function.
FieldQuals If the subobject is a field, its cv-qualifiers.
ConstRHS True if this is a copy operation with a const object on its RHS, that is, if the argument to the outer special member function is 'const' and this is not a field marked 'mutable'.
Definition at line 7236 of file SemaDeclCXX.cpp.
References clang::Qualifiers::Const, clang::Sema::CXXCopyAssignment, clang::Sema::CXXDefaultConstructor, clang::Sema::CXXDestructor, clang::Sema::CXXMoveAssignment, clang::Sema::LookupSpecialMember(), and clang::Qualifiers::Volatile.
Referenced by findTrivialSpecialMember(), and specialMemberIsConstexpr().
lookupOperatorsForDefaultedComparison()
static void lookupOperatorsForDefaultedComparison (Sema & Self, Scope * S, UnresolvedSetImpl & Operators, OverloadedOperatorKind Op) static
Perform the unqualified lookups that might be needed to form a defaulted comparison function for the given operator.
Definition at line 8654 of file SemaDeclCXX.cpp.
References clang::getRewrittenOverloadedOperator(), and clang::Sema::LookupOverloadedOperatorName().
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison().
LookupStdInitializerList()
static ClassTemplateDecl * LookupStdInitializerList (Sema & S, SourceLocation Loc) static
Definition at line 11790 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::Decl::getLocation(), clang::TemplateParameterList::getMinRequiredArguments(), clang::TemplateParameterList::getParam(), clang::Sema::getStdNamespace(), clang::TemplateDecl::getTemplateParameters(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::Sema::PP, and Std.
Referenced by clang::Sema::BuildStdInitializerList().
lookupStdTypeTraitMember()
static bool lookupStdTypeTraitMember (Sema & S, LookupResult & TraitMemberLookup, SourceLocation Loc, StringRef Trait, TemplateArgumentListInfo & Args, unsigned DiagID) static
Definition at line 1032 of file SemaDeclCXX.cpp.
References clang::Sema::CheckTemplateIdType(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Type::getAsCXXRecordDecl(), clang::Preprocessor::getIdentifierTable(), clang::Decl::getLocation(), clang::ASTContext::getPrintingPolicy(), clang::Sema::getStdNamespace(), clang::TemplateDecl::getTemplateParameters(), clang::LookupResult::isAmbiguous(), clang::Sema::isCompleteType(), clang::QualType::isNull(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::Sema::PP, printTemplateArgs(), clang::Sema::RequireCompleteType(), and Std.
Referenced by getTupleLikeElementType(), and isTupleLike().
NoteIndirectBases()
static void NoteIndirectBases (ASTContext & Context, IndirectBaseSet & Set, const QualType & Type) static
Recursively add the bases of Type. Don't add Type itself.
Definition at line 2854 of file SemaDeclCXX.cpp.
References clang::Type::getAs(), clang::ASTContext::getCanonicalType(), clang::CanQual< typename >::getUnqualifiedType(), and NoteIndirectBases().
Referenced by clang::Sema::AttachBaseSpecifiers(), and NoteIndirectBases().
PopulateKeysForFields()
static void PopulateKeysForFields (FieldDecl * Field, SmallVectorImpl< const void * > & IdealInits) static
Definition at line 5454 of file SemaDeclCXX.cpp.
References clang::RecordDecl::fields(), clang::RecordDecl::isAnonymousStructOrUnion(), and PopulateKeysForFields().
Referenced by DiagnoseBaseOrMemInitializerOrder(), and PopulateKeysForFields().
printTemplateArgs()
static std::string printTemplateArgs (const PrintingPolicy & PrintingPolicy, TemplateArgumentListInfo & Args, const TemplateParameterList * Params) static
Definition at line 1013 of file SemaDeclCXX.cpp.
References clang::TemplateArgumentListInfo::arguments(), and clang::First.
Referenced by getTupleLikeElementType(), isTupleLike(), and lookupStdTypeTraitMember().
ReferenceDllExportedMembers()
static void ReferenceDllExportedMembers (Sema & S, CXXRecordDecl * Class) static
Definition at line 6174 of file SemaDeclCXX.cpp.
References clang::Sema::Consumer, clang::Sema::Context, clang::Sema::CodeSynthesisContext::Entity, clang::TargetInfo::getCXXABI(), clang::getDLLAttr(), clang::Attr::getKind(), clang::Attr::getLocation(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ASTConsumer::HandleTopLevelDecl(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), clang::Attr::isInherited(), clang::TargetCXXABI::isMicrosoft(), clang::Sema::CodeSynthesisContext::Kind, clang::Sema::MarkFunctionReferenced(), clang::Sema::CodeSynthesisContext::MarkingClassDllexported, clang::Sema::MarkVariableReferenced(), clang::Sema::MarkVTableUsed(), clang::Member, clang::Sema::CodeSynthesisContext::PointOfInstantiation, clang::Sema::popCodeSynthesisContext(), clang::Sema::pushCodeSynthesisContext(), clang::SC_Static, clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, clang::TSK_ImplicitInstantiation, and clang::TSK_Undeclared.
Referenced by clang::Sema::referenceDLLExportedClassMethods().
RefersToRValueRef()
static bool RefersToRValueRef (Expr * MemRef) static
Definition at line 4918 of file SemaDeclCXX.cpp.
References clang::cast(), clang::ValueDecl::getType(), and clang::Type::isRValueReferenceType().
Referenced by BuildImplicitMemberInitializer().
RemoveAddressSpaceFromPtr()
static CanQualType RemoveAddressSpaceFromPtr (Sema & SemaRef, const PointerType * PtrTy) static
Definition at line 15964 of file SemaDeclCXX.cpp.
References clang::Sema::Context, clang::ASTContext::getCanonicalType(), clang::ASTContext::getPointerType(), clang::ASTContext::getQualifiedType(), and clang::Qualifiers::removeAddressSpace().
Referenced by CheckOperatorNewDeleteTypes().
ReportOverrides()
static bool ReportOverrides (Sema & S, unsigned DiagID, const CXXMethodDecl * MD, llvm::function_ref< bool(const CXXMethodDecl *)> Report) static
Report an error regarding overriding, along with any relevant overridden methods.
Parameters
DiagID the primary error to report.
MD the overriding method.
Definition at line 6882 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), and clang::CXXMethodDecl::overridden_methods().
Referenced by clang::Sema::CheckCompletedCXXClass().
SearchForReturnInStmt()
static void SearchForReturnInStmt (Sema & Self, Stmt * S) static
Definition at line 17936 of file SemaDeclCXX.cpp.
References clang::Sema::Diag(), and SearchForReturnInStmt().
Referenced by clang::Sema::DiagnoseReturnInConstructorExceptionHandler(), and SearchForReturnInStmt().
specialMemberIsConstexpr()
static bool specialMemberIsConstexpr (Sema & S, CXXRecordDecl * ClassDecl, Sema::CXXSpecialMember CSM, unsigned Quals, bool ConstRHS, CXXConstructorDecl * InheritedCtor = nullptr, Sema::InheritedConstructorInfo * Inherited = nullptr) static
Is the special member function which would be selected to perform the specified operation on the specified class type a constexpr constructor?
Definition at line 7341 of file SemaDeclCXX.cpp.
References clang::Sema::CXXDefaultConstructor, clang::Sema::CXXDestructor, clang::Sema::SpecialMemberOverloadResult::getMethod(), clang::CXXRecordDecl::hasConstexprDefaultConstructor(), clang::CXXRecordDecl::hasConstexprDestructor(), clang::FunctionDecl::isConstexpr(), and lookupCallFromSpecialMember().
Referenced by defaultedSpecialMemberIsConstexpr().
TryNamespaceTypoCorrection()
static bool TryNamespaceTypoCorrection (Sema & S, LookupResult & R, Scope * Sc, CXXScopeSpec & SS, SourceLocation IdentLoc, IdentifierInfo * Ident) static
Definition at line 11888 of file SemaDeclCXX.cpp.
References clang::LookupResult::addDecl(), clang::LookupResult::clear(), clang::Sema::computeDeclContext(), clang::Sema::CorrectTypo(), clang::Sema::CTK_ErrorRecovery, clang::Sema::diagnoseTypo(), clang::Sema::getLangOpts(), clang::LookupResult::getLookupKind(), clang::LookupResult::getLookupNameInfo(), clang::IdentifierInfo::getName(), clang::CXXScopeSpec::getRange(), and clang::Sema::PDiag().
Referenced by clang::Sema::ActOnNamespaceAliasDef(), and clang::Sema::ActOnUsingDirective().
UsefulToPrintExpr()
static bool UsefulToPrintExpr (const Expr * E) static
Some Expression types are not useful to print notes about, e.g.
literals and values that have already been expanded before such as int-valued template parameters.
Definition at line 16870 of file SemaDeclCXX.cpp.
References clang::Expr::IgnoreParenImpCasts(), and UsefulToPrintExpr().
Referenced by clang::Sema::DiagnoseStaticAssertDetails(), and UsefulToPrintExpr().