clang: lib/Sema/SemaChecking.cpp File Reference
SemaChecking.cpp File Reference
#include "clang/AST/APValue.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/AttrIterator.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/AST/FormatString.h"
#include "clang/AST/NSAPI.h"
#include "clang/AST/NonTrivialTypeVisitor.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/UnresolvedSet.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/OpenCLOptions.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/SyncScope.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/Basic/TargetCXXABI.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TypeTraits.h"
#include "clang/Lex/Lexer.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Ownership.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Locale.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include <algorithm>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <limits>
#include <optional>
#include <string>
#include <tuple>
#include <utility>
#include "clang/Basic/Builtins.def"
#include "clang/Basic/arm_sve_sema_rangechecks.inc"
#include "clang/Basic/arm_sme_sema_rangechecks.inc"
#include "clang/Basic/arm_neon.inc"
#include "clang/Basic/arm_fp16.inc"
#include "clang/Basic/arm_mve_builtin_sema.inc"
#include "clang/Basic/arm_cde_builtin_sema.inc"
#include "clang/Basic/PPCTypes.def"
#include "clang/Basic/BuiltinsPPC.def"
Macros
#define BUILTIN(ID, TYPE, ATTRS)
#define ATOMIC_BUILTIN(ID, TYPE, ATTRS)
#define GET_SVE_IMMEDIATE_CHECK
#define GET_SME_IMMEDIATE_CHECK
#define GET_NEON_OVERLOAD_CHECK
#define GET_NEON_IMMEDIATE_CHECK
#define PPC_VECTOR_TYPE(typeName, Id, size)
#define CUSTOM_BUILTIN(Name, Intr, Types, Acc, Feature)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define BUILTIN_ROW(x)
Enumerations
enum { TileRegLow = 0 , TileRegHigh = 7 }
enum AbsoluteValueKind { AVK_Integer , AVK_Floating , AVK_Complex }
Functions
static constexpr unsigned short combineFAPK (Sema::FormatArgumentPassingKind A, Sema::FormatArgumentPassingKind B)
static bool checkArgCountAtLeast (Sema &S, CallExpr *Call, unsigned MinArgCount)
Checks that a call expression's argument count is at least the desired number.
static bool checkArgCountAtMost (Sema &S, CallExpr *Call, unsigned MaxArgCount)
Checks that a call expression's argument count is at most the desired number.
static bool checkArgCountRange (Sema &S, CallExpr *Call, unsigned MinArgCount, unsigned MaxArgCount)
Checks that a call expression's argument count is in the desired range.
static bool checkArgCount (Sema &S, CallExpr *Call, unsigned DesiredArgCount)
Checks that a call expression's argument count is the desired number.
static bool convertArgumentToType (Sema &S, Expr *&Value, QualType Ty)
static bool SemaBuiltinAnnotation (Sema &S, CallExpr *TheCall)
Check that the first argument to __builtin_annotation is an integer and the second argument is a non-wide string literal.
static bool SemaBuiltinMSVCAnnotation (Sema &S, CallExpr *TheCall)
static bool SemaBuiltinAddressof (Sema &S, CallExpr *TheCall)
Check that the argument to __builtin_addressof is a glvalue, and set the result type to the corresponding pointer type.
static bool SemaBuiltinFunctionStart (Sema &S, CallExpr *TheCall)
Check that the argument to __builtin_function_start is a function.
static bool SemaBuiltinPreserveAI (Sema &S, CallExpr *TheCall)
Check the number of arguments and set the result type to the argument type.
static bool SemaBuiltinAlignment (Sema &S, CallExpr *TheCall, unsigned ID)
Check that the value argument for __builtin_is_aligned(value, alignment) and __builtin_aligned_{up,down}(value, alignment) is an integer or a pointer type (but not a function pointer) and that the alignment is a power-of-two.
static bool SemaBuiltinOverflow (Sema &S, CallExpr *TheCall, unsigned BuiltinID)
static ExprResult SemaBuiltinDumpStruct (Sema &S, CallExpr *TheCall)
static bool SemaBuiltinCallWithStaticChain (Sema &S, CallExpr *BuiltinCall)
static bool SemaBuiltinSEHScopeCheck (Sema &SemaRef, CallExpr *TheCall, Scope::ScopeFlags NeededScopeFlags, unsigned DiagID)
static bool isBlockPointer (Expr *Arg)
static bool checkOpenCLBlockArgs (Sema &S, Expr *BlockArg)
OpenCL C v2.0, s6.13.17.2 - Checks that the block parameters are all local void*, which is a requirement of device side enqueue.
static bool checkOpenCLSubgroupExt (Sema &S, CallExpr *Call)
static bool SemaOpenCLBuiltinNDRangeAndBlock (Sema &S, CallExpr *TheCall)
static bool SemaOpenCLBuiltinKernelWorkGroupSize (Sema &S, CallExpr *TheCall)
OpenCL C v2.0, s6.13.17.6 - Check the argument to the get_kernel_work_group_size and get_kernel_preferred_work_group_size_multiple builtin functions.
static bool checkOpenCLEnqueueIntType (Sema &S, Expr *E, const QualType &IntType)
Diagnose integer type and any valid implicit conversion to it.
static bool checkOpenCLEnqueueLocalSizeArgs (Sema &S, CallExpr *TheCall, unsigned Start, unsigned End)
static bool checkOpenCLEnqueueVariadicArgs (Sema &S, CallExpr *TheCall, Expr *BlockArg, unsigned NumNonVarArgs)
OpenCL v2.0, s6.13.17.1 - Check that sizes are provided for all 'local void*' parameter of passed block.
static bool SemaOpenCLBuiltinEnqueueKernel (Sema &S, CallExpr *TheCall)
OpenCL C v2.0, s6.13.17 - Enqueue kernel function contains four different overload formats specified in Table 6.13.17.1.
static OpenCLAccessAttr * getOpenCLArgAccess (const Decl *D)
Returns OpenCL access qual.
static bool checkOpenCLPipeArg (Sema &S, CallExpr *Call)
Returns true if pipe element type is different from the pointer.
static bool checkOpenCLPipePacketType (Sema &S, CallExpr *Call, unsigned Idx)
Returns true if pipe element type is different from the pointer.
static bool SemaBuiltinRWPipe (Sema &S, CallExpr *Call)
static bool SemaBuiltinReserveRWPipe (Sema &S, CallExpr *Call)
static bool SemaBuiltinCommitRWPipe (Sema &S, CallExpr *Call)
static bool SemaBuiltinPipePackets (Sema &S, CallExpr *Call)
static bool SemaOpenCLBuiltinToAddr (Sema &S, unsigned BuiltinID, CallExpr *Call)
static ExprResult SemaBuiltinLaunder (Sema &S, CallExpr *TheCall)
static bool CheckBuiltinTargetNotInUnsupported (Sema &S, unsigned BuiltinID, CallExpr *TheCall, ArrayRef< llvm::Triple::ObjectFormatType > UnsupportedObjectFormatTypes)
static bool CheckBuiltinTargetInSupported (Sema &S, unsigned BuiltinID, CallExpr *TheCall, ArrayRef< llvm::Triple::ArchType > SupportedArchs)
static void CheckNonNullArgument (Sema &S, const Expr *ArgExpr, SourceLocation CallSiteLoc)
static bool checkMathBuiltinElementType (Sema &S, SourceLocation Loc, QualType Ty)
static bool checkFPMathBuiltinElementType (Sema &S, SourceLocation Loc, QualType ArgTy, int ArgIndex)
static unsigned RFT (unsigned t, bool shift=false, bool ForceQuad=false)
static QualType getNeonEltType (NeonTypeFlags Flags, ASTContext &Context, bool IsPolyUnsigned, bool IsInt64Long)
getNeonEltType - Return the QualType corresponding to the elements of the vector type specified by the NeonTypeFlags.
static bool isValidBPFPreserveFieldInfoArg (Expr *Arg)
static bool isValidBPFPreserveTypeInfoArg (Expr *Arg)
static bool isValidBPFPreserveEnumValueArg (Expr *Arg)
static QualType DecodePPCMMATypeFromStr (ASTContext &Context, const char *&Str, unsigned &Mask)
DecodePPCMMATypeFromStr - This decodes one PPC MMA type descriptor from Str, advancing the pointer over the consumed characters.
static bool isPPC_64Builtin (unsigned BuiltinID)
static bool SemaBuiltinCpuSupports (Sema &S, const TargetInfo &TI, CallExpr *TheCall)
SemaBuiltinCpuSupports - Handle __builtin_cpu_supports(char *).
static bool SemaBuiltinCpuIs (Sema &S, const TargetInfo &TI, CallExpr *TheCall)
SemaBuiltinCpuIs - Handle __builtin_cpu_is(char *).
static bool isX86_32Builtin (unsigned BuiltinID)
static bool CheckNonNullExpr (Sema &S, const Expr *Expr)
Checks if a the given expression evaluates to null.
static void DiagnoseCStringFormatDirectiveInCFAPI (Sema &S, const NamedDecl *FDecl, Expr **Args, unsigned NumArgs)
Diagnose use of s directive in an NSString which is being passed as formatting string to formatting method.
static bool isNonNullType (QualType type)
Determine whether the given type has a non-null nullability annotation.
static void CheckNonNullArguments (Sema &S, const NamedDecl *FDecl, const FunctionProtoType *Proto, ArrayRef< const Expr * > Args, SourceLocation CallSiteLoc)
static bool isValidOrderingForOp (int64_t Ordering, AtomicExpr::AtomicOp Op)
static bool checkBuiltinArgument (Sema &S, CallExpr *E, unsigned ArgIndex)
checkBuiltinArgument - Given a call to a builtin function, perform normal type-checking on the given argument, updating the call in place.
static bool checkVAStartABI (Sema &S, unsigned BuiltinID, Expr *Fn)
Check that the user is calling the appropriate va_start builtin for the target and calling convention.
static bool checkVAStartIsInVariadicFunction (Sema &S, Expr *Fn, ParmVarDecl **LastParam=nullptr)
static bool IsShiftedByte (llvm::APSInt Value)
static void sumOffsets (llvm::APSInt &Offset, llvm::APSInt Addend, BinaryOperatorKind BinOpKind, bool AddendIsRight)
static void CheckFormatString (Sema &S, const FormatStringLiteral *FExpr, const Expr *OrigFormatExpr, ArrayRef< const Expr * > Args, Sema::FormatArgumentPassingKind APK, unsigned format_idx, unsigned firstDataArg, Sema::FormatStringType Type, bool inFunctionCall, Sema::VariadicCallType CallType, llvm::SmallBitVector &CheckedVarArgs, UncoveredArgHandler &UncoveredArg, bool IgnoreStringsWithoutSpecifiers)
static const Expr * maybeConstEvalStringLiteral (ASTContext &Context, const Expr *E)
static StringLiteralCheckType checkFormatStringExpr (Sema &S, const Expr *E, ArrayRef< const Expr * > Args, Sema::FormatArgumentPassingKind APK, unsigned format_idx, unsigned firstDataArg, Sema::FormatStringType Type, Sema::VariadicCallType CallType, bool InFunctionCall, llvm::SmallBitVector &CheckedVarArgs, UncoveredArgHandler &UncoveredArg, llvm::APSInt Offset, bool IgnoreStringsWithoutSpecifiers=false)
template<typename MemberKind >
static llvm::SmallPtrSet< MemberKind *, 1 > CXXRecordMembersNamed (StringRef Name, Sema &S, QualType Ty)
static bool requiresParensToAddCast (const Expr *E)
static std::pair< QualType, StringRef > shouldNotPrintDirectly (const ASTContext &Context, QualType IntendedTy, const Expr *E)
static bool isArithmeticArgumentPromotion (Sema &S, const ImplicitCastExpr *ICE)
Return true if ICE is an implicit argument promotion of an arithmetic type.
static unsigned getLargerAbsoluteValueFunction (unsigned AbsFunction)
static QualType getAbsoluteValueArgumentType (ASTContext &Context, unsigned AbsType)
static unsigned getBestAbsFunction (ASTContext &Context, QualType ArgType, unsigned AbsFunctionKind)
static AbsoluteValueKind getAbsoluteValueKind (QualType T)
static unsigned changeAbsFunction (unsigned AbsKind, AbsoluteValueKind ValueKind)
static unsigned getAbsoluteValueFunctionKind (const FunctionDecl *FDecl)
static void emitReplacement (Sema &S, SourceLocation Loc, SourceRange Range, unsigned AbsKind, QualType ArgType)
template<std::size_t StrLen>
static bool IsStdFunction (const FunctionDecl *FDecl, const char(&Str)[StrLen])
static bool CheckMemorySizeofForComparison (Sema &S, const Expr *E, IdentifierInfo *FnName, SourceLocation FnLoc, SourceLocation RParenLoc)
Takes the expression passed to the size_t parameter of functions such as memcmp, strncat, etc and warns if it's a comparison.
static const CXXRecordDecl * getContainedDynamicClass (QualType T, bool &IsContained)
Determine whether the given type is or contains a dynamic class type (e.g., whether it has a vtable).
static const UnaryExprOrTypeTraitExpr * getAsSizeOfExpr (const Expr *E)
static const Expr * getSizeOfExprArg (const Expr *E)
If E is a sizeof expression, returns its argument expression, otherwise returns NULL.
static QualType getSizeOfArgType (const Expr *E)
If E is a sizeof expression, returns its argument type.
static bool doesExprLikelyComputeSize (const Expr *SizeofExpr)
Detect if SizeofExpr is likely to calculate the sizeof an object.
static bool isArgumentExpandedFromMacro (SourceManager &SM, SourceLocation CallLoc, SourceLocation ArgLoc)
Check if the ArgLoc originated from a macro passed to the call at CallLoc.
static void CheckMemaccessSize (Sema &S, unsigned BId, const CallExpr *Call)
Diagnose cases like 'memset(buf, sizeof(buf), 0)', which should have the last two arguments transposed.
static const Expr * ignoreLiteralAdditions (const Expr *Ex, ASTContext &Ctx)
static bool isConstantSizeArrayWithMoreThanOneElement (QualType Ty, ASTContext &Context)
static bool referToTheSameDecl (const Expr *E1, const Expr *E2)
Check if two expressions refer to the same declaration.
static const Expr * getStrlenExprArg (const Expr *E)
static IntRange GetValueRange (ASTContext &C, llvm::APSInt &value, unsigned MaxWidth)
static IntRange GetValueRange (ASTContext &C, APValue &result, QualType Ty, unsigned MaxWidth)
static QualType GetExprType (const Expr *E)
static IntRange GetExprRange (ASTContext &C, const Expr *E, unsigned MaxWidth, bool InConstantContext, bool Approximate)
Pseudo-evaluate the given integer expression, estimating the range of values it might take.
static IntRange GetExprRange (ASTContext &C, const Expr *E, bool InConstantContext, bool Approximate)
static bool IsSameFloatAfterCast (const llvm::APFloat &value, const llvm::fltSemantics &Src, const llvm::fltSemantics &Tgt)
Checks whether the given value, which currently has the given source semantics, has the same value when coerced through the target semantics.
static bool IsSameFloatAfterCast (const APValue &value, const llvm::fltSemantics &Src, const llvm::fltSemantics &Tgt)
Checks whether the given value, which currently has the given source semantics, has the same value when coerced through the target semantics.
static void AnalyzeImplicitConversions (Sema &S, Expr *OrigE, SourceLocation CC, bool IsListInit)
AnalyzeImplicitConversions - Find and report any interesting implicit conversions in the given expression.
static bool IsEnumConstOrFromMacro (Sema &S, Expr *E)
static bool isKnownToHaveUnsignedValue (Expr *E)
static bool HasEnumType (Expr *E)
static int classifyConstantValue (Expr *Constant)
static bool CheckTautologicalComparison (Sema &S, BinaryOperator *E, Expr *Constant, Expr *Other, const llvm::APSInt &Value, bool RhsConstant)
static void AnalyzeImpConvsInComparison (Sema &S, BinaryOperator *E)
Analyze the operands of the given comparison.
static void AnalyzeComparison (Sema &S, BinaryOperator *E)
Implements -Wsign-compare.
static bool AnalyzeBitFieldAssignment (Sema &S, FieldDecl *Bitfield, Expr *Init, SourceLocation InitLoc)
Analyzes an attempt to assign the given value to a bitfield.
static void AnalyzeAssignment (Sema &S, BinaryOperator *E)
Analyze the given simple or compound assignment for warning-worthy operations.
static void DiagnoseImpCast (Sema &S, Expr *E, QualType SourceType, QualType T, SourceLocation CContext, unsigned diag, bool pruneControlFlow=false)
Diagnose an implicit cast; purely a helper for CheckImplicitConversion.
static void DiagnoseImpCast (Sema &S, Expr *E, QualType T, SourceLocation CContext, unsigned diag, bool pruneControlFlow=false)
Diagnose an implicit cast; purely a helper for CheckImplicitConversion.
static bool isObjCSignedCharBool (Sema &S, QualType Ty)
static void adornObjCBoolConversionDiagWithTernaryFixit (Sema &S, Expr *SourceExpr, const Sema::SemaDiagnosticBuilder &Builder)
static void DiagnoseFloatingImpCast (Sema &S, Expr *E, QualType T, SourceLocation CContext)
Diagnose an implicit cast from a floating point value to an integer value.
static void AnalyzeCompoundAssignment (Sema &S, BinaryOperator *E)
Analyze the given compound assignment for the possible losing of floating-point precision.
static std::string PrettyPrintInRange (const llvm::APSInt &Value, IntRange Range)
static bool IsImplicitBoolFloatConversion (Sema &S, Expr *Ex, bool ToBool)
static void CheckImplicitArgumentConversions (Sema &S, CallExpr *TheCall, SourceLocation CC)
static void DiagnoseNullConversion (Sema &S, Expr *E, QualType T, SourceLocation CC)
static void checkObjCArrayLiteral (Sema &S, QualType TargetType, ObjCArrayLiteral *ArrayLiteral)
Check an Objective-C array literal being converted to the given target type.
static void checkObjCDictionaryLiteral (Sema &S, QualType TargetType, ObjCDictionaryLiteral *DictionaryLiteral)
Check an Objective-C dictionary literal being converted to the given target type.
static void checkObjCCollectionLiteralElement (Sema &S, QualType TargetElementType, Expr *Element, unsigned ElementKind)
Check a single element within a collection literal against the target element type.
static bool isSameWidthConstantConversion (Sema &S, Expr *E, QualType T, SourceLocation CC)
static const IntegerLiteral * getIntegerLiteral (Expr *E)
static void DiagnoseIntInBoolContext (Sema &S, Expr *E)
static void CheckImplicitConversion (Sema &S, Expr *E, QualType T, SourceLocation CC, bool *ICContext=nullptr, bool IsListInit=false)
static void CheckConditionalOperator (Sema &S, AbstractConditionalOperator *E, SourceLocation CC, QualType T)
static void CheckConditionalOperand (Sema &S, Expr *E, QualType T, SourceLocation CC, bool &ICContext)
static void CheckBoolLikeConversion (Sema &S, Expr *E, SourceLocation CC)
Check conversion of given expression to boolean.
static void AnalyzeImplicitConversions (Sema &S, AnalyzeImplicitConversionsWorkItem Item, llvm::SmallVectorImpl< AnalyzeImplicitConversionsWorkItem > &WorkList)
Data recursive variant of AnalyzeImplicitConversions.
static bool CheckForReference (Sema &SemaRef, const Expr *E, const PartialDiagnostic &PD)
static bool IsInAnyMacroBody (const SourceManager &SM, SourceLocation Loc)
static void diagnoseArrayStarInParamType (Sema &S, QualType PType, SourceLocation Loc)
static std::optional< std::pair< CharUnits, CharUnits > > getBaseAlignmentAndOffsetFromPtr (const Expr *E, ASTContext &Ctx)
This helper function takes a pointer expression and returns the alignment of a VarDecl and a constant offset from the VarDecl.
static std::pair< CharUnits, CharUnits > getDerivedToBaseAlignmentAndOffset (const CastExpr *CE, QualType DerivedType, CharUnits BaseAlignment, CharUnits Offset, ASTContext &Ctx)
Compute the alignment and offset of the base class object given the derived-to-base cast expression and the alignment and offset of the derived class object.
static std::optional< std::pair< CharUnits, CharUnits > > getAlignmentAndOffsetFromBinAddOrSub (const Expr *PtrE, const Expr *IntE, bool IsSub, ASTContext &Ctx)
Compute the alignment and offset of a binary additive operator.
static std::optional< std::pair< CharUnits, CharUnits > > getBaseAlignmentAndOffsetFromLValue (const Expr *E, ASTContext &Ctx)
This helper function takes an lvalue expression and returns the alignment of a VarDecl and a constant offset from the VarDecl.
static CharUnits getPresumedAlignmentOfPointer (const Expr *E, Sema &S)
static bool considerVariable (VarDecl *var, Expr *ref, RetainCycleOwner &owner)
Consider whether capturing the given variable can possibly lead to a retain cycle.
static bool findRetainCycleOwner (Sema &S, Expr *e, RetainCycleOwner &owner)
static Expr * findCapturingExpr (Sema &S, Expr *e, RetainCycleOwner &owner)
Check whether the given argument is a block which captures a variable.
static void diagnoseRetainCycle (Sema &S, Expr *capturer, RetainCycleOwner &owner)
static bool isSetterLikeSelector (Selector sel)
Check for a keyword selector that starts with the word 'add' or 'set'.
static std::optional< int > GetNSMutableArrayArgumentIndex (Sema &S, ObjCMessageExpr *Message)
static std::optional< int > GetNSMutableDictionaryArgumentIndex (Sema &S, ObjCMessageExpr *Message)
static std::optional< int > GetNSSetArgumentIndex (Sema &S, ObjCMessageExpr *Message)
static bool checkUnsafeAssignLiteral (Sema &S, SourceLocation Loc, Expr *RHS, bool isProperty)
static bool checkUnsafeAssignObject (Sema &S, SourceLocation Loc, Qualifiers::ObjCLifetime LT, Expr *RHS, bool isProperty)
static bool ShouldDiagnoseEmptyStmtBody (const SourceManager &SourceMgr, SourceLocation StmtLoc, const NullStmt *Body)
static bool isLayoutCompatible (ASTContext &C, QualType T1, QualType T2)
Check if two types are layout-compatible in C++11 sense.
static bool isLayoutCompatible (ASTContext &C, EnumDecl *ED1, EnumDecl *ED2)
Check if two enumeration types are layout-compatible.
static bool isLayoutCompatible (ASTContext &C, FieldDecl *Field1, FieldDecl *Field2)
Check if two fields are layout-compatible.
static bool isLayoutCompatibleStruct (ASTContext &C, RecordDecl *RD1, RecordDecl *RD2)
Check if two standard-layout structs are layout-compatible.
static bool isLayoutCompatibleUnion (ASTContext &C, RecordDecl *RD1, RecordDecl *RD2)
Check if two standard-layout unions are layout-compatible.
static bool isLayoutCompatible (ASTContext &C, RecordDecl *RD1, RecordDecl *RD2)
static bool FindTypeTagExpr (const Expr *TypeExpr, const ASTContext &Ctx, const ValueDecl **VD, uint64_t *MagicValue, bool isConstantEvaluated)
Given a type tag expression find the type tag itself.
static bool GetMatchingCType (const IdentifierInfo *ArgumentKind, const Expr *TypeExpr, const ASTContext &Ctx, const llvm::DenseMap< Sema::TypeTagMagicValue, Sema::TypeTagData > *MagicValues, bool &FoundWrongKind, Sema::TypeTagData &TypeInfo, bool isConstantEvaluated)
Retrieve the C type corresponding to type tag TypeExpr.
static bool IsSameCharType (QualType T1, QualType T2)
static std::optional< unsigned > getAndVerifyMatrixDimension (Expr *Expr, StringRef Name, Sema &S)
static bool CheckWasmBuiltinArgIsTable (Sema &S, CallExpr *E, unsigned ArgIndex, QualType &ElTy)
Checks the argument at the given index is a WebAssembly table and if it is, sets ElTy to the element type.
static bool CheckWasmBuiltinArgIsInteger (Sema &S, CallExpr *E, unsigned ArgIndex)
Checks the argument at the given index is an integer.
Macro Definition Documentation
ATOMIC_BUILTIN
#define ATOMIC_BUILTIN (ID, TYPE, ATTRS)
Value:
  case Builtin::BI##ID: \
    return SemaAtomicOpsOverloaded(TheCallResult, AtomicExpr::AO##ID);
BUILTIN
#define BUILTIN (ID, TYPE, ATTRS)
BUILTIN_ROW
#define BUILTIN_ROW (x)
Value:
  { Builtin::BI##x##_1, Builtin::BI##x##_2, Builtin::BI##x##_4, \
    Builtin::BI##x##_8, Builtin::BI##x##_16 }
CUSTOM_BUILTIN
#define CUSTOM_BUILTIN (Name, Intr, Types, Acc, Feature)
Value:
  case PPC::BI__builtin_##Name:                                                \
    return SemaBuiltinPPCMMACall(TheCall, BuiltinID, Types);
GET_NEON_IMMEDIATE_CHECK
#define GET_NEON_IMMEDIATE_CHECK
GET_NEON_OVERLOAD_CHECK
#define GET_NEON_OVERLOAD_CHECK
GET_SME_IMMEDIATE_CHECK
#define GET_SME_IMMEDIATE_CHECK
GET_SVE_IMMEDIATE_CHECK
#define GET_SVE_IMMEDIATE_CHECK
PPC_VECTOR_TYPE [1/2]
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
|| CoreType == Context.Id##Ty
PPC_VECTOR_TYPE [2/2]
#define PPC_VECTOR_TYPE (typeName, Id, size)
Value:
    case size: Type = Context.Id##Ty; break;
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TileRegLow
TileRegHigh
Definition at line 5896 of file SemaChecking.cpp.
AbsoluteValueKind
enum AbsoluteValueKind
Enumerator
AVK_Integer
AVK_Floating
AVK_Complex
Definition at line 11794 of file SemaChecking.cpp.
Function Documentation
adornObjCBoolConversionDiagWithTernaryFixit()
static void adornObjCBoolConversionDiagWithTernaryFixit (Sema & S, Expr * SourceExpr, const Sema::SemaDiagnosticBuilder & Builder) static
Definition at line 14214 of file SemaChecking.cpp.
References clang::FixItHint::CreateInsertion(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Sema::getLocForEndOfToken(), clang::Expr::IgnoreImplicit(), and clang::isa().
Referenced by CheckImplicitConversion(), and DiagnoseFloatingImpCast().
AnalyzeAssignment()
static void AnalyzeAssignment (Sema & S, BinaryOperator * E) static
Analyze the given simple or compound assignment for warning-worthy operations.
Definition at line 14165 of file SemaChecking.cpp.
References AnalyzeBitFieldAssignment(), AnalyzeImplicitConversions(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::Expr::getSourceBitField(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), and clang::Type::isAtomicType().
Referenced by AnalyzeImplicitConversions().
AnalyzeBitFieldAssignment()
static bool AnalyzeBitFieldAssignment (Sema & S, FieldDecl * Bitfield, Expr * Init, SourceLocation InitLoc) static
Analyzes an attempt to assign the given value to a bitfield.
Returns true if there was something fishy about the attempt.
Definition at line 14026 of file SemaChecking.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::Expr::EvaluateAsInt(), clang::Sema::findMacroSpelling(), clang::Type::getAs(), clang::Stmt::getBeginLoc(), clang::FieldDecl::getBitWidth(), clang::FieldDecl::getBitWidthValue(), clang::Expr::getExprLoc(), clang::EnumDecl::getIntegerTypeSourceInfo(), clang::Sema::getLangOpts(), clang::EnumDecl::getNumNegativeBits(), clang::EnumDecl::getNumPositiveBits(), clang::Stmt::getSourceRange(), clang::TypeLoc::getSourceRange(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::DeclaratorDecl::getTypeSpecStartLoc(), clang::FieldDecl::isBitField(), clang::Type::isBooleanType(), clang::Type::isEnumeralType(), clang::SourceManager::isInSystemMacro(), clang::Decl::isInvalidDecl(), clang::Type::isSignedIntegerType(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::Sema::LangOpts, clang::Result, clang::Expr::SE_AllowSideEffects, clang::Sema::SourceMgr, and toString().
Referenced by AnalyzeAssignment().
AnalyzeComparison()
static void AnalyzeComparison (Sema & S, BinaryOperator * E) static
Implements -Wsign-compare.
Parameters
E the binary operator to check for warnings
Definition at line 13910 of file SemaChecking.cpp.
References AnalyzeImpConvsInComparison(), AnalyzeImplicitConversions(), bool, CheckTautologicalComparison(), clang::Sema::Context, clang::Sema::DiagRuntimeBehavior(), GetExprRange(), clang::Expr::getIntegerConstantExpr(), clang::ASTContext::getIntWidth(), clang::Sema::getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::hasSignedIntegerRepresentation(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::isConstantEvaluated(), clang::BinaryOperator::isEqualityOp(), clang::Expr::isValueDependent(), and clang::Sema::PDiag().
Referenced by AnalyzeImplicitConversions().
AnalyzeCompoundAssignment()
static void AnalyzeCompoundAssignment (Sema & S, BinaryOperator * E) static
Analyze the given compound assignment for the possible losing of floating-point precision.
Definition at line 14347 of file SemaChecking.cpp.
References AnalyzeImplicitConversions(), clang::cast(), clang::Sema::Diag(), DiagnoseImpCast(), clang::Type::getAs(), clang::Sema::getASTContext(), clang::BinaryOperator::getExprLoc(), clang::ASTContext::getFloatingTypeSemanticOrder(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isAtomicType(), clang::BuiltinType::isFloatingPoint(), clang::SourceManager::isInSystemMacro(), and clang::Sema::SourceMgr.
Referenced by AnalyzeImplicitConversions().
AnalyzeImpConvsInComparison()
static void AnalyzeImpConvsInComparison (Sema & S, BinaryOperator * E) static
Analyze the operands of the given comparison.
Implements the fallback case from AnalyzeComparison.
Definition at line 13902 of file SemaChecking.cpp.
References AnalyzeImplicitConversions(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOperatorLoc(), and clang::BinaryOperator::getRHS().
Referenced by AnalyzeComparison().
AnalyzeImplicitConversions() [1/2]
static void AnalyzeImplicitConversions (Sema & S, AnalyzeImplicitConversionsWorkItem Item, llvm::SmallVectorImpl< AnalyzeImplicitConversionsWorkItem > & WorkList) static
Data recursive variant of AnalyzeImplicitConversions.
Subexpressions that should be visited are added to WorkList.
Definition at line 15207 of file SemaChecking.cpp.
References AnalyzeAssignment(), AnalyzeComparison(), AnalyzeCompoundAssignment(), CheckBoolLikeConversion(), CheckConditionalOperator(), CheckImplicitArgumentConversions(), CheckImplicitConversion(), clang::Stmt::children(), clang::Sema::Context, clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::BinaryOperator::getExprLoc(), clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::isa(), clang::Type::isAtomicType(), clang::BinaryOperator::isLogicalOp(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::Type::isVoidType().
AnalyzeImplicitConversions() [2/2]
static void AnalyzeImplicitConversions (Sema & S, Expr * OrigE, SourceLocation CC, bool IsListInit) static
AnalyzeImplicitConversions - Find and report any interesting implicit conversions in the given expression.
There are a couple of competing diagnostics here, -Wconversion and -Wsign-compare.
Definition at line 15362 of file SemaChecking.cpp.
References AnalyzeImplicitConversions().
Referenced by AnalyzeAssignment(), AnalyzeComparison(), AnalyzeCompoundAssignment(), AnalyzeImpConvsInComparison(), AnalyzeImplicitConversions(), CheckConditionalOperand(), and CheckConditionalOperator().
changeAbsFunction()
static unsigned changeAbsFunction (unsigned AbsKind, AbsoluteValueKind ValueKind) static
Definition at line 11813 of file SemaChecking.cpp.
References AVK_Complex, AVK_Floating, and AVK_Integer.
checkArgCount()
static bool checkArgCount (Sema & S, CallExpr * Call, unsigned DesiredArgCount) static
Checks that a call expression's argument count is the desired number.
This is useful when doing custom type-checking. Returns true on error.
Definition at line 155 of file SemaChecking.cpp.
References checkArgCountAtLeast(), and clang::Sema::Diag().
Referenced by SemaBuiltinAddressof(), SemaBuiltinAlignment(), SemaBuiltinAnnotation(), SemaBuiltinCallWithStaticChain(), SemaBuiltinCommitRWPipe(), SemaBuiltinFunctionStart(), SemaBuiltinLaunder(), SemaBuiltinOverflow(), SemaBuiltinPipePackets(), SemaBuiltinPreserveAI(), SemaBuiltinReserveRWPipe(), SemaOpenCLBuiltinKernelWorkGroupSize(), SemaOpenCLBuiltinNDRangeAndBlock(), and SemaOpenCLBuiltinToAddr().
checkArgCountAtLeast()
static bool checkArgCountAtLeast (Sema & S, CallExpr * Call, unsigned MinArgCount) static
Checks that a call expression's argument count is at least the desired number.
This is useful when doing custom type-checking on a variadic function. Returns true on error.
Definition at line 120 of file SemaChecking.cpp.
References clang::Sema::Diag().
Referenced by checkArgCount(), checkArgCountRange(), and SemaBuiltinDumpStruct().
checkArgCountAtMost()
static bool checkArgCountAtMost (Sema & S, CallExpr * Call, unsigned MaxArgCount) static
Checks that a call expression's argument count is at most the desired number.
This is useful when doing custom type-checking on a variadic function. Returns true on error.
Definition at line 134 of file SemaChecking.cpp.
References clang::Sema::Diag().
Referenced by checkArgCountRange().
checkArgCountRange()
static bool checkArgCountRange (Sema & S, CallExpr * Call, unsigned MinArgCount, unsigned MaxArgCount) static
Checks that a call expression's argument count is in the desired range.
This is useful when doing custom type-checking on a variadic function. Returns true on error.
Definition at line 147 of file SemaChecking.cpp.
References checkArgCountAtLeast(), and checkArgCountAtMost().
CheckBoolLikeConversion()
static void CheckBoolLikeConversion (Sema & S, Expr * E, SourceLocation CC) static
Check conversion of given expression to boolean.
Input argument E is a logical expression.
Definition at line 15189 of file SemaChecking.cpp.
References clang::ASTContext::BoolTy, CheckImplicitConversion(), clang::Sema::Context, clang::Sema::getLangOpts(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), and clang::Type::isAtomicType().
Referenced by AnalyzeImplicitConversions().
checkBuiltinArgument()
static bool checkBuiltinArgument (Sema & S, CallExpr * E, unsigned ArgIndex) static
checkBuiltinArgument - Given a call to a builtin function, perform normal type-checking on the given argument, updating the call in place.
This is useful when a builtin function requires custom type-checking for some of its arguments but not necessarily all of them.
Returns true on error.
Definition at line 7473 of file SemaChecking.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::CallExpr::getDirectCallee(), clang::FunctionDecl::getParamDecl(), clang::InitializedEntity::InitializeParameter(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::PerformCopyInitialization(), and clang::CallExpr::setArg().
CheckBuiltinTargetInSupported()
static bool CheckBuiltinTargetInSupported (Sema & S, unsigned BuiltinID, CallExpr * TheCall, ArrayRef< llvm::Triple::ArchType > SupportedArchs) static
Definition at line 1971 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Sema::getASTContext(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
CheckBuiltinTargetNotInUnsupported()
static bool CheckBuiltinTargetNotInUnsupported (Sema & S, unsigned BuiltinID, CallExpr * TheCall, ArrayRef< llvm::Triple::ObjectFormatType > UnsupportedObjectFormatTypes) static
Definition at line 1955 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Sema::getASTContext(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
CheckConditionalOperand()
static void CheckConditionalOperand (Sema & S, Expr * E, QualType T, SourceLocation CC, bool & ICContext) static
Definition at line 15137 of file SemaChecking.cpp.
References AnalyzeImplicitConversions(), CheckConditionalOperator(), CheckImplicitConversion(), clang::Sema::getLangOpts(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isRecordType(), and clang::Sema::RequireCompleteExprType().
Referenced by CheckConditionalOperator().
CheckConditionalOperator()
static void CheckConditionalOperator (Sema & S, AbstractConditionalOperator * E, SourceLocation CC, QualType T) static
Definition at line 15152 of file SemaChecking.cpp.
References AnalyzeImplicitConversions(), CheckConditionalOperand(), CheckImplicitConversion(), DiagnoseIntInBoolContext(), clang::Sema::Diags, clang::AbstractConditionalOperator::getCond(), clang::AbstractConditionalOperator::getFalseExpr(), clang::AbstractConditionalOperator::getQuestionLoc(), clang::AbstractConditionalOperator::getTrueExpr(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), and clang::DiagnosticsEngine::isIgnored().
Referenced by AnalyzeImplicitConversions(), and CheckConditionalOperand().
CheckFormatString()
static void CheckFormatString (Sema & S, const FormatStringLiteral * FExpr, const Expr * OrigFormatExpr, ArrayRef< const Expr * > Args, Sema::FormatArgumentPassingKind APK, unsigned format_idx, unsigned firstDataArg, Sema::FormatStringType Type, bool inFunctionCall, Sema::VariadicCallType CallType, llvm::SmallBitVector & CheckedVarArgs, UncoveredArgHandler & UncoveredArg, bool IgnoreStringsWithoutSpecifiers) static
Definition at line 11609 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Sema::FST_FreeBSDKPrintf, clang::Sema::FST_NSString, clang::Sema::FST_OSLog, clang::Sema::FST_OSTrace, clang::Sema::FST_Printf, clang::Sema::FST_Scanf, clang::ASTContext::getAsConstantArrayType(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::ASTContext::getTargetInfo(), clang::analyze_format_string::parseFormatStringHasFormattingSpecifiers(), clang::analyze_format_string::ParsePrintfString(), clang::analyze_format_string::ParseScanfString(), and clang::Sema::PDiag().
Referenced by checkFormatStringExpr().
checkFormatStringExpr()
static StringLiteralCheckType checkFormatStringExpr (Sema & S, const Expr * E, ArrayRef< const Expr * > Args, Sema::FormatArgumentPassingKind APK, unsigned format_idx, unsigned firstDataArg, Sema::FormatStringType Type, Sema::VariadicCallType CallType, bool InFunctionCall, llvm::SmallBitVector & CheckedVarArgs, UncoveredArgHandler & UncoveredArg, llvm::APSInt Offset, bool IgnoreStringsWithoutSpecifiers = false) static
Definition at line 9500 of file SemaChecking.cpp.
References clang::Sema::FormatStringInfo::ArgPassingKind, clang::C, clang::cast(), CheckFormatString(), checkFormatStringExpr(), combineFAPK(), clang::Cond, clang::Sema::Context, clang::Expr::EvaluateAsInt(), clang::Sema::FAPK_Fixed, clang::Sema::FAPK_VAList, clang::Sema::FAPK_Variadic, clang::Sema::FormatStringInfo::FormatIdx, clang::CallExpr::getArg(), clang::Type::getAs(), clang::ASTContext::getAsArrayType(), clang::Sema::getASTContext(), clang::FunctionDecl::getBuiltinID(), clang::CallExpr::getCalleeDecl(), clang::DeclRefExpr::getDecl(), clang::Sema::getFormatStringInfo(), clang::Sema::GetFormatStringType(), clang::Decl::getFunctionType(), clang::NamedDecl::getIdentifier(), clang::APValue::getInt(), clang::StringLiteral::getLength(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Stmt::getStmtClass(), clang::StringLiteral::getString(), clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::BinaryOperator::isAdditiveOp(), clang::Sema::isConstantEvaluated(), IsFirst, clang::Expr::isNullPointerConstant(), clang::IdentifierInfo::isStr(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), maybeConstEvalStringLiteral(), clang::Expr::NPC_ValueDependentIsNotNull, Offset, clang::Result, clang::Expr::SE_NoSideEffects, clang::Decl::specific_attrs(), sumOffsets(), and clang::Expr::EvalResult::Val.
Referenced by checkFormatStringExpr().
CheckForReference()
static bool CheckForReference (Sema & SemaRef, const Expr * E, const PartialDiagnostic & PD) static
Definition at line 15387 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::DeclRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::Expr::IgnoreParenImpCasts(), and clang::Type::isReferenceType().
Referenced by clang::Sema::DiagnoseAlwaysNonNullPointer().
checkFPMathBuiltinElementType()
static bool checkFPMathBuiltinElementType (Sema & S, SourceLocation Loc, QualType ArgTy, int ArgIndex) static
Definition at line 2051 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Type::getAs(), and clang::Type::isRealFloatingType().
CheckImplicitArgumentConversions()
static void CheckImplicitArgumentConversions (Sema & S, CallExpr * TheCall, SourceLocation CC) static
Definition at line 14412 of file SemaChecking.cpp.
References DiagnoseImpCast(), clang::CallExpr::getArg(), clang::CallExpr::getNumArgs(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), and IsImplicitBoolFloatConversion().
Referenced by AnalyzeImplicitConversions().
CheckImplicitConversion()
static void CheckImplicitConversion (Sema & S, Expr * E, QualType T, SourceLocation CC, bool * ICContext = nullptr, bool IsListInit = false) static
Definition at line 14652 of file SemaChecking.cpp.
References adornObjCBoolConversionDiagWithTernaryFixit(), clang::ASTContext::areCompatibleRVVTypes(), clang::ASTContext::areCompatibleSveTypes(), clang::ASTContext::areLaxCompatibleRVVTypes(), clang::ASTContext::areLaxCompatibleSveTypes(), clang::cast(), checkObjCArrayLiteral(), checkObjCDictionaryLiteral(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagnoseAlwaysNonNullPointer(), DiagnoseFloatingImpCast(), DiagnoseImpCast(), DiagnoseIntInBoolContext(), DiagnoseNullConversion(), clang::Sema::DiagRuntimeBehavior(), clang::Sema::DiscardMisalignedMemberAddress(), Enum, clang::Expr::EvaluateAsFixedPoint(), clang::Expr::EvaluateAsInt(), clang::Expr::EvaluateAsRValue(), clang::CallExpr::getArg(), clang::Sema::getASTContext(), clang::ASTContext::getCanonicalType(), clang::DeclRefExpr::getDecl(), clang::Expr::getExprLoc(), GetExprRange(), clang::ASTContext::getFixedPointMax(), clang::ASTContext::getFixedPointMin(), clang::ASTContext::getFixedPointSemantics(), clang::ASTContext::getFloatingTypeSemanticOrder(), clang::ASTContext::getFloatTypeSemantics(), clang::Expr::getIntegerConstantExpr(), clang::ASTContext::getIntWidth(), clang::Sema::getLangOpts(), clang::CallExpr::getNumArgs(), clang::Stmt::getSourceRange(), clang::Type::getSveEltType(), clang::Expr::getType(), clang::ASTContext::getTypeDeclType(), clang::CanQual< typename >::getTypePtr(), clang::QualType::getTypePtr(), clang::ASTContext::getTypeSize(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isBooleanType(), clang::Sema::isConstantEvaluated(), clang::BuiltinType::isFloatingPoint(), clang::Type::isFloatingType(), clang::SourceManager::isInSystemMacro(), clang::BuiltinType::isInteger(), clang::Type::isIntegerType(), clang::SourceLocation::isInvalid(), clang::Expr::isKnownToHaveBooleanValue(), isObjCSignedCharBool(), IsSameFloatAfterCast(), isSameWidthConstantConversion(), clang::BuiltinType::isSignedInteger(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::Type::isVLSTBuiltinType(), clang::Expr::NPCK_NotNull, clang::Sema::PDiag(), PrettyPrintInRange(), clang::Result, clang::Expr::SE_AllowSideEffects, clang::Sema::SourceMgr, toString(), and clang::Expr::EvalResult::Val.
Referenced by AnalyzeImplicitConversions(), CheckBoolLikeConversion(), CheckConditionalOperand(), CheckConditionalOperator(), and checkOpenCLEnqueueIntType().
checkMathBuiltinElementType()
static bool checkMathBuiltinElementType (Sema & S, SourceLocation Loc, QualType Ty) static
Definition at line 2041 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Type::getAs(), and clang::MatrixType::isValidElementType().
CheckMemaccessSize()
static void CheckMemaccessSize (Sema & S, unsigned BId, const CallExpr * Call) static
Diagnose cases like 'memset(buf, sizeof(buf), 0)', which should have the last two arguments transposed.
Definition at line 12365 of file SemaChecking.cpp.
References clang::cast(), clang::Sema::Diag(), doesExprLikelyComputeSize(), clang::Expr::getExprLoc(), clang::Lexer::getImmediateMacroName(), clang::Sema::getLangOpts(), clang::Sema::getSourceManager(), clang::isa(), isArgumentExpandedFromMacro(), clang::SourceLocation::isMacroID(), and SM.
CheckMemorySizeofForComparison()
static bool CheckMemorySizeofForComparison (Sema & S, const Expr * E, IdentifierInfo * FnName, SourceLocation FnLoc, SourceLocation RParenLoc) static
Takes the expression passed to the size_t parameter of functions such as memcmp, strncat, etc and warns if it's a comparison.
This is to catch typos like if (memcmp(&a, &b, sizeof(a) > 0)).
Definition at line 12154 of file SemaChecking.cpp.
References clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), and clang::Sema::getLocForEndOfToken().
CheckNonNullArgument()
static void CheckNonNullArgument (Sema & S, const Expr * ArgExpr, SourceLocation CallSiteLoc) static
Definition at line 6409 of file SemaChecking.cpp.
References CheckNonNullExpr(), clang::Sema::DiagRuntimeBehavior(), clang::Stmt::getSourceRange(), and clang::Sema::PDiag().
Referenced by clang::Sema::BuildAtomicExpr(), and CheckNonNullArguments().
CheckNonNullArguments()
static void CheckNonNullArguments (Sema & S, const NamedDecl * FDecl, const FunctionProtoType * Proto, ArrayRef< const Expr * > Args, SourceLocation CallSiteLoc) static
Definition at line 6478 of file SemaChecking.cpp.
References clang::cast(), CheckNonNullArgument(), clang::Type::getAs(), clang::FunctionProtoType::getParamTypes(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::Sema::isConstantEvaluated(), isNonNullType(), clang::Sema::isValidPointerAttrType(), clang::NonNull, clang::FunctionDecl::parameters(), clang::ast_matchers::pointerType, and clang::Decl::specific_attrs().
CheckNonNullExpr()
static bool CheckNonNullExpr (Sema & S, const Expr * Expr) static
Checks if a the given expression evaluates to null.
Returns true if the value evaluates to null.
Definition at line 6385 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Expr::EvaluateAsBooleanCondition(), clang::Type::getAsUnionType(), clang::Type::getNullability(), clang::Expr::getType(), clang::Expr::IgnoreImplicit(), clang::Expr::isValueDependent(), clang::NonNull, and clang::Result.
Referenced by CheckNonNullArgument().
checkObjCArrayLiteral()
static void checkObjCArrayLiteral (Sema & S, QualType TargetType, ObjCArrayLiteral * ArrayLiteral) static
Check an Objective-C array literal being converted to the given target type.
Definition at line 14521 of file SemaChecking.cpp.
References checkObjCCollectionLiteralElement(), clang::Type::getAs(), clang::ObjCInterfaceDecl::getCanonicalDecl(), clang::ObjCArrayLiteral::getElement(), clang::ObjCArrayLiteral::getNumElements(), clang::ObjCObjectPointerType::getTypeArgs(), N, and clang::Sema::NSArrayDecl.
Referenced by CheckImplicitConversion(), and checkObjCCollectionLiteralElement().
checkObjCCollectionLiteralElement()
static void checkObjCCollectionLiteralElement (Sema & S, QualType TargetElementType, Expr * Element, unsigned ElementKind) static
Check a single element within a collection literal against the target element type.
Definition at line 14490 of file SemaChecking.cpp.
References checkObjCArrayLiteral(), checkObjCDictionaryLiteral(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::Compatible, clang::Sema::Diag(), and clang::Type::getAs().
Referenced by checkObjCArrayLiteral(), and checkObjCDictionaryLiteral().
checkObjCDictionaryLiteral()
static void checkObjCDictionaryLiteral (Sema & S, QualType TargetType, ObjCDictionaryLiteral * DictionaryLiteral) static
Check an Objective-C dictionary literal being converted to the given target type.
Definition at line 14550 of file SemaChecking.cpp.
References checkObjCCollectionLiteralElement(), clang::Type::getAs(), clang::ObjCInterfaceDecl::getCanonicalDecl(), clang::ObjCDictionaryLiteral::getKeyValueElement(), clang::ObjCDictionaryLiteral::getNumElements(), clang::ObjCObjectPointerType::getTypeArgs(), N, and clang::Sema::NSDictionaryDecl.
Referenced by CheckImplicitConversion(), and checkObjCCollectionLiteralElement().
checkOpenCLBlockArgs()
static bool checkOpenCLBlockArgs (Sema & S, Expr * BlockArg) static
OpenCL C v2.0, s6.13.17.2 - Checks that the block parameters are all local void*, which is a requirement of device side enqueue.
Definition at line 1376 of file SemaChecking.cpp.
References clang::cast(), clang::Type::castAs(), clang::Sema::Diag(), clang::DeclaratorDecl::getBeginLoc(), clang::QualType::getCanonicalType(), clang::BlockDecl::getParamDecl(), clang::BlockPointerType::getPointeeType(), clang::Expr::getType(), and clang::opencl_local.
Referenced by SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinKernelWorkGroupSize(), and SemaOpenCLBuiltinNDRangeAndBlock().
checkOpenCLEnqueueIntType()
static bool checkOpenCLEnqueueIntType (Sema & S, Expr * E, const QualType & IntType) static
Diagnose integer type and any valid implicit conversion to it.
Definition at line 15371 of file SemaChecking.cpp.
References CheckImplicitConversion(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Expr::getType(), and clang::Type::isIntegerType().
Referenced by checkOpenCLEnqueueLocalSizeArgs().
checkOpenCLEnqueueLocalSizeArgs()
static bool checkOpenCLEnqueueLocalSizeArgs (Sema & S, CallExpr * TheCall, unsigned Start, unsigned End) static
Definition at line 1468 of file SemaChecking.cpp.
References checkOpenCLEnqueueIntType(), clang::Sema::Context, clang::CallExpr::getArg(), and clang::ASTContext::getSizeType().
Referenced by checkOpenCLEnqueueVariadicArgs().
checkOpenCLEnqueueVariadicArgs()
static bool checkOpenCLEnqueueVariadicArgs (Sema & S, CallExpr * TheCall, Expr * BlockArg, unsigned NumNonVarArgs) static
OpenCL v2.0, s6.13.17.1 - Check that sizes are provided for all 'local void*' parameter of passed block.
Definition at line 1479 of file SemaChecking.cpp.
References clang::cast(), clang::Type::castAs(), checkOpenCLEnqueueLocalSizeArgs(), clang::Sema::Diag(), clang::CallExpr::getBeginLoc(), clang::QualType::getCanonicalType(), clang::CallExpr::getNumArgs(), clang::BlockPointerType::getPointeeType(), and clang::Expr::getType().
Referenced by SemaOpenCLBuiltinEnqueueKernel().
checkOpenCLPipeArg()
static bool checkOpenCLPipeArg (Sema & S, CallExpr * Call) static
Returns true if pipe element type is different from the pointer.
Definition at line 1653 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Stmt::getBeginLoc(), getOpenCLArgAccess(), clang::Stmt::getSourceRange(), clang::Expr::getType(), and clang::Type::isPipeType().
Referenced by SemaBuiltinCommitRWPipe(), SemaBuiltinReserveRWPipe(), and SemaBuiltinRWPipe().
checkOpenCLPipePacketType()
static bool checkOpenCLPipePacketType (Sema & S, CallExpr * Call, unsigned Idx) static
Returns true if pipe element type is different from the pointer.
Definition at line 1703 of file SemaChecking.cpp.
References clang::cast(), clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::Type::getCanonicalTypeInternal(), clang::PipeType::getElementType(), clang::PointerType::getPointeeType(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), and clang::ASTContext::hasSameType().
Referenced by SemaBuiltinRWPipe().
checkOpenCLSubgroupExt()
static bool checkOpenCLSubgroupExt (Sema & S, CallExpr * Call) static
Definition at line 1409 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Sema::getOpenCLOptions(), and clang::OpenCLOptions::isSupported().
Referenced by SemaOpenCLBuiltinNDRangeAndBlock().
CheckTautologicalComparison()
static bool CheckTautologicalComparison (Sema & S, BinaryOperator * E, Expr * Constant, Expr * Other, const llvm::APSInt & Value, bool RhsConstant) static
Definition at line 13748 of file SemaChecking.cpp.
References clang::ASTContext::CharTy, classifyConstantValue(), clang::Sema::Context, clang::Sema::Diag(), Diag(), clang::Sema::DiagRuntimeBehavior(), clang::Type::getAs(), GetExprRange(), clang::Sema::getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getOperatorLoc(), clang::BinaryOperator::getRHS(), clang::Stmt::getSourceRange(), clang::Expr::getType(), HasEnumType(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::inTemplateInstantiation(), clang::Type::isBooleanType(), clang::Sema::isConstantEvaluated(), IsEnumConstOrFromMacro(), clang::Type::isEnumeralType(), isKnownToHaveUnsignedValue(), clang::Type::isSpecificBuiltinType(), clang::Sema::NSAPIObj, clang::Sema::PDiag(), clang::Result, and clang::QualType::withoutLocalFastQualifiers().
Referenced by AnalyzeComparison().
checkUnsafeAssignLiteral()
static bool checkUnsafeAssignLiteral (Sema & S, SourceLocation Loc, Expr * RHS, bool isProperty) static
Definition at line 17721 of file SemaChecking.cpp.
References clang::Sema::CheckLiteralKind(), clang::Sema::Diag(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::LK_None, and clang::Sema::LK_String.
Referenced by checkUnsafeAssignObject().
checkUnsafeAssignObject()
static bool checkUnsafeAssignObject (Sema & S, SourceLocation Loc, Qualifiers::ObjCLifetime LT, Expr * RHS, bool isProperty) static
Definition at line 17742 of file SemaChecking.cpp.
References checkUnsafeAssignLiteral(), clang::Sema::Diag(), clang::Stmt::getSourceRange(), LT, clang::Qualifiers::OCL_ExplicitNone, and clang::Qualifiers::OCL_Weak.
Referenced by clang::Sema::checkUnsafeAssigns(), and clang::Sema::checkUnsafeExprAssigns().
checkVAStartABI()
static bool checkVAStartABI (Sema & S, unsigned BuiltinID, Expr * Fn) static
Check that the user is calling the appropriate va_start builtin for the target and calling convention.
Definition at line 8027 of file SemaChecking.cpp.
References clang::Type::castAs(), clang::CC_C, clang::CC_Win64, clang::CC_X86_64SysV, clang::Sema::Context, clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Sema::getCurFunctionDecl(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), and clang::ValueDecl::getType().
checkVAStartIsInVariadicFunction()
static bool checkVAStartIsInVariadicFunction (Sema & S, Expr * Fn, ParmVarDecl ** LastParam = nullptr) static
Definition at line 8062 of file SemaChecking.cpp.
References clang::Block, clang::Sema::CurContext, clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::FunctionDecl::isVariadic(), and clang::FunctionDecl::parameters().
CheckWasmBuiltinArgIsInteger()
static bool CheckWasmBuiltinArgIsInteger (Sema & S, CallExpr * E, unsigned ArgIndex) static
Checks the argument at the given index is an integer.
Definition at line 19011 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::getType(), and clang::Type::isIntegerType().
CheckWasmBuiltinArgIsTable()
static bool CheckWasmBuiltinArgIsTable (Sema & S, CallExpr * E, unsigned ArgIndex, QualType & ElTy) static
Checks the argument at the given index is a WebAssembly table and if it is, sets ElTy to the element type.
Definition at line 18997 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), and clang::Expr::getType().
classifyConstantValue()
static int classifyConstantValue (Expr * Constant) static
Definition at line 13734 of file SemaChecking.cpp.
Referenced by CheckTautologicalComparison().
combineFAPK()
static constexpr unsigned short combineFAPK (Sema::FormatArgumentPassingKind A, Sema::FormatArgumentPassingKind B) static constexpr
Definition at line 112 of file SemaChecking.cpp.
Referenced by checkFormatStringExpr().
considerVariable()
static bool considerVariable (VarDecl * var, Expr * ref, RetainCycleOwner & owner) static
Consider whether capturing the given variable can possibly lead to a retain cycle.
Definition at line 17283 of file SemaChecking.cpp.
References clang::QualType::getObjCLifetime(), clang::ValueDecl::getType(), and clang::Qualifiers::OCL_Strong.
Referenced by clang::Sema::checkRetainCycles(), and findRetainCycleOwner().
convertArgumentToType()
static bool convertArgumentToType (Sema & S, Expr *& Value, QualType Ty) static
Definition at line 173 of file SemaChecking.cpp.
References clang::Sema::Context, clang::InitializedEntity::InitializeParameter(), clang::Sema::PerformCopyInitialization(), and clang::Result.
CXXRecordMembersNamed()
template<typename MemberKind > static llvm::SmallPtrSet< MemberKind *, 1 > CXXRecordMembersNamed (StringRef Name, Sema & S, QualType Ty) static
Definition at line 10671 of file SemaChecking.cpp.
References clang::LookupResult::begin(), clang::Sema::Context, clang::ast_matchers::decl, clang::LookupResult::end(), clang::IdentifierTable::get(), clang::Type::getAs(), clang::CXXRecordDecl::getDefinition(), clang::NamedDecl::getUnderlyingDecl(), clang::ASTContext::Idents, clang::Sema::LookupMemberName, clang::Sema::LookupQualifiedName(), and clang::LookupResult::suppressDiagnostics().
Referenced by clang::Sema::hasCStrMethod().
DecodePPCMMATypeFromStr()
static QualType DecodePPCMMATypeFromStr (ASTContext & Context, const char *& Str, unsigned & Mask) static
DecodePPCMMATypeFromStr - This decodes one PPC MMA type descriptor from Str, advancing the pointer over the consumed characters.
The decoded type is returned. If the decoded type represents a constant integer with a constraint on its value then Mask is set to that value. The type descriptors used in Str are specific to PPC MMA builtins and are documented in the file defining the PPC builtins.
Definition at line 4131 of file SemaChecking.cpp.
References clang::VectorType::AltiVecVector, clang::ASTContext::DecodeTypeStr(), clang::ASTContext::GE_None, clang::ASTContext::getPointerType(), clang::ASTContext::getVectorType(), clang::ASTContext::IntTy, Type, and clang::ASTContext::UnsignedCharTy.
diagnoseArrayStarInParamType()
static void diagnoseArrayStarInParamType (Sema & S, QualType PType, SourceLocation Loc) static
Definition at line 16590 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Sema::Diag(), diagnoseArrayStarInParamType(), clang::ASTContext::getAsArrayType(), clang::ArrayType::getElementType(), clang::ArrayType::getSizeModifier(), clang::Type::isVariablyModifiedType(), and clang::ArrayType::Star.
Referenced by clang::Sema::CheckParmsForFunctionDef(), and diagnoseArrayStarInParamType().
DiagnoseCStringFormatDirectiveInCFAPI()
static void DiagnoseCStringFormatDirectiveInCFAPI (Sema & S, const NamedDecl * FDecl, Expr ** Args, unsigned NumArgs) static
Diagnose use of s directive in an NSString which is being passed as formatting string to formatting method.
Definition at line 6431 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Sema::FormatStringHasSArg(), clang::NamedDecl::getDeclName(), clang::Expr::getExprLoc(), clang::Sema::GetFormatNSStringIdx(), clang::Decl::getLocation(), clang::NamedDecl::getObjCFStringFormattingFamily(), clang::StringLiteral::getString(), clang::Expr::IgnoreParenImpCasts(), clang::SFF_CFString, and clang::Decl::specific_attrs().
DiagnoseFloatingImpCast()
static void DiagnoseFloatingImpCast (Sema & S, Expr * E, QualType T, SourceLocation CContext) static
Diagnose an implicit cast from a floating point value to an integer value.
Definition at line 14230 of file SemaChecking.cpp.
References adornObjCBoolConversionDiagWithTernaryFixit(), clang::Sema::Context, clang::Sema::Diag(), DiagnoseImpCast(), clang::Sema::DiagRuntimeBehavior(), clang::Expr::EvaluateAsFloat(), clang::Expr::getExprLoc(), clang::ASTContext::getIntWidth(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::inTemplateInstantiation(), clang::isa(), isObjCSignedCharBool(), clang::Sema::PDiag(), clang::Result, and clang::Expr::SE_AllowSideEffects.
Referenced by CheckImplicitConversion().
DiagnoseImpCast() [1/2]
static void DiagnoseImpCast (Sema & S, Expr * E, QualType SourceType, QualType T, SourceLocation CContext, unsigned diag, bool pruneControlFlow = false) static
Diagnose an implicit cast; purely a helper for CheckImplicitConversion.
Definition at line 14188 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Sema::DiagRuntimeBehavior(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), and clang::Sema::PDiag().
Referenced by AnalyzeCompoundAssignment(), CheckImplicitArgumentConversions(), CheckImplicitConversion(), DiagnoseFloatingImpCast(), and DiagnoseImpCast().
DiagnoseImpCast() [2/2]
static void DiagnoseImpCast (Sema & S, Expr * E, QualType T, SourceLocation CContext, unsigned diag, bool pruneControlFlow = false) static
Diagnose an implicit cast; purely a helper for CheckImplicitConversion.
Definition at line 14203 of file SemaChecking.cpp.
References DiagnoseImpCast(), and clang::Expr::getType().
DiagnoseIntInBoolContext()
static void DiagnoseIntInBoolContext (Sema & S, Expr * E) static
Definition at line 14615 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Expr::EvaluateAsInt(), clang::Expr::getExprLoc(), getIntegerLiteral(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isSignedIntegerType(), clang::Expr::isValueDependent(), clang::Result, and clang::Expr::SE_AllowSideEffects.
Referenced by CheckConditionalOperator(), and CheckImplicitConversion().
DiagnoseNullConversion()
static void DiagnoseNullConversion (Sema & S, Expr * E, QualType T, SourceLocation CC) static
Definition at line 14433 of file SemaChecking.cpp.
References clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Sema::Diags, clang::CharSourceRange::getBegin(), clang::SourceRange::getBegin(), clang::Expr::getExprLoc(), clang::SourceManager::getFileID(), clang::Sema::getFixItZeroLiteralForType(), clang::SourceManager::getImmediateExpansionRange(), clang::Lexer::getImmediateMacroNameForDiagnostics(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::SourceManager::getTopMacroCallerLoc(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::isa(), clang::DiagnosticsEngine::isIgnored(), clang::Type::isNullPtrType(), and clang::Sema::SourceMgr.
Referenced by CheckImplicitConversion().
diagnoseRetainCycle()
static void diagnoseRetainCycle (Sema & S, Expr * capturer, RetainCycleOwner & owner) static
Definition at line 17467 of file SemaChecking.cpp.
References clang::Sema::Diag(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), and clang::SourceLocation::isValid().
Referenced by clang::Sema::checkRetainCycles(), clang::Sema::checkRetainCycles(), and clang::Sema::checkRetainCycles().
doesExprLikelyComputeSize()
static bool doesExprLikelyComputeSize (const Expr * SizeofExpr) static
Detect if SizeofExpr is likely to calculate the sizeof an object.
Definition at line 12329 of file SemaChecking.cpp.
References doesExprLikelyComputeSize(), getAsSizeOfExpr(), and clang::Expr::IgnoreParenImpCasts().
Referenced by CheckMemaccessSize(), and doesExprLikelyComputeSize().
emitReplacement()
static void emitReplacement (Sema & S, SourceLocation Loc, SourceRange Range, unsigned AbsKind, QualType ArgType) static
Definition at line 11910 of file SemaChecking.cpp.
References clang::ASTContext::BuiltinInfo, clang::Sema::Context, clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::LookupResult::empty(), clang::IdentifierTable::get(), getAbsoluteValueKind(), clang::FunctionDecl::getBuiltinID(), clang::Sema::getCurScope(), clang::LookupResult::getFoundDecl(), clang::Builtin::Context::getHeaderName(), clang::Sema::getLangOpts(), clang::Builtin::Context::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::Sema::getStdNamespace(), clang::ValueDecl::getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::Idents, clang::LookupResult::isSingleResult(), clang::Sema::LookupAnyName, clang::Sema::LookupName(), clang::Sema::LookupQualifiedName(), Std, and clang::LookupResult::suppressDiagnostics().
Referenced by clang::syntax::computeReplacements().
findCapturingExpr()
static Expr * findCapturingExpr (Sema & S, Expr * e, RetainCycleOwner & owner) static
Check whether the given argument is a block which captures a variable.
Definition at line 17432 of file SemaChecking.cpp.
References clang::BlockDecl::capturesVariable(), Cmd, clang::Sema::Context, clang::CallExpr::getArg(), clang::BlockExpr::getBlockDecl(), clang::BlockDecl::getBody(), clang::CallExpr::getCalleeDecl(), clang::NamedDecl::getIdentifier(), clang::CallExpr::getNumArgs(), clang::Expr::IgnoreParenCasts(), clang::IdentifierInfo::isStr(), and clang::SourceLocation::isValid().
Referenced by clang::Sema::checkRetainCycles(), clang::Sema::checkRetainCycles(), and clang::Sema::checkRetainCycles().
findRetainCycleOwner()
static bool findRetainCycleOwner (Sema & S, Expr * e, RetainCycleOwner & owner) static
Definition at line 17296 of file SemaChecking.cpp.
References clang::cast(), considerVariable(), findRetainCycleOwner(), clang::ObjCPropertyRefExpr::getBase(), clang::Sema::getCurMethodDecl(), clang::ObjCPropertyRefExpr::getExplicitProperty(), clang::ObjCPropertyRefExpr::getLocation(), clang::QualType::getObjCLifetime(), clang::ObjCMethodDecl::getSelfDecl(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::Expr::IgnoreParens(), clang::ObjCPropertyRefExpr::isImplicitProperty(), clang::ObjCPropertyRefExpr::isSuperReceiver(), and clang::Qualifiers::OCL_Strong.
Referenced by clang::Sema::checkRetainCycles(), clang::Sema::checkRetainCycles(), and findRetainCycleOwner().
FindTypeTagExpr()
static bool FindTypeTagExpr (const Expr * TypeExpr, const ASTContext & Ctx, const ValueDecl ** VD, uint64_t * MagicValue, bool isConstantEvaluated) static
Given a type tag expression find the type tag itself.
Parameters
TypeExpr Type tag expression, as it appears in user's code.
VD Declaration of an identifier that appears in a type tag.
MagicValue Type tag magic value.
isConstantEvaluated whether the evalaution should be performed in constant context.
Definition at line 18218 of file SemaChecking.cpp.
References clang::cast(), clang::Expr::EvaluateAsBooleanCondition(), clang::AbstractConditionalOperator::getCond(), clang::DeclRefExpr::getDecl(), clang::AbstractConditionalOperator::getFalseExpr(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Stmt::getStmtClass(), clang::UnaryOperator::getSubExpr(), clang::AbstractConditionalOperator::getTrueExpr(), clang::APIntStorage::getValue(), clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenImpCasts(), and clang::Result.
Referenced by GetMatchingCType().
getAbsoluteValueArgumentType()
static QualType getAbsoluteValueArgumentType (ASTContext & Context, unsigned AbsType) static
Definition at line 11753 of file SemaChecking.cpp.
References clang::ASTContext::GE_None, clang::Type::getAs(), clang::ASTContext::GetBuiltinType(), clang::FunctionProtoType::getNumParams(), and clang::FunctionProtoType::getParamType().
Referenced by getBestAbsFunction().
getAbsoluteValueFunctionKind()
static unsigned getAbsoluteValueFunctionKind (const FunctionDecl * FDecl) static
Definition at line 11877 of file SemaChecking.cpp.
References clang::FunctionDecl::getBuiltinID(), and clang::NamedDecl::getIdentifier().
getAbsoluteValueKind()
static AbsoluteValueKind getAbsoluteValueKind (QualType T) static
Definition at line 11800 of file SemaChecking.cpp.
References AVK_Complex, AVK_Floating, and AVK_Integer.
Referenced by emitReplacement().
getAlignmentAndOffsetFromBinAddOrSub()
static std::optional< std::pair< CharUnits, CharUnits > > getAlignmentAndOffsetFromBinAddOrSub (const Expr * PtrE, const Expr * IntE, bool IsSub, ASTContext & Ctx) static
Compute the alignment and offset of a binary additive operator.
Definition at line 16753 of file SemaChecking.cpp.
References getBaseAlignmentAndOffsetFromPtr(), clang::Expr::getIntegerConstantExpr(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeSizeInChars(), clang::Type::isConstantSizeType(), Offset, P, and clang::CharUnits::Zero().
Referenced by getBaseAlignmentAndOffsetFromLValue(), and getBaseAlignmentAndOffsetFromPtr().
getAndVerifyMatrixDimension()
static std::optional< unsigned > getAndVerifyMatrixDimension (Expr * Expr, StringRef Name, Sema & S) static
Definition at line 18763 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Expr::getIntegerConstantExpr(), clang::ConstantMatrixType::getMaxElementsPerDimension(), and clang::ConstantMatrixType::isDimensionValid().
getAsSizeOfExpr()
static const UnaryExprOrTypeTraitExpr * getAsSizeOfExpr (const Expr * E) static
Definition at line 12213 of file SemaChecking.cpp.
Referenced by doesExprLikelyComputeSize(), getSizeOfArgType(), and getSizeOfExprArg().
getBaseAlignmentAndOffsetFromLValue()
static std::optional< std::pair< CharUnits, CharUnits > > getBaseAlignmentAndOffsetFromLValue (const Expr * E, ASTContext & Ctx) static
This helper function takes an lvalue expression and returns the alignment of a VarDecl and a constant offset from the VarDecl.
Definition at line 16785 of file SemaChecking.cpp.
References clang::cast(), clang::CharUnits::fromQuantity(), getAlignmentAndOffsetFromBinAddOrSub(), clang::ASTContext::getASTRecordLayout(), clang::ArraySubscriptExpr::getBase(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), clang::ASTContext::getDeclAlign(), getDerivedToBaseAlignmentAndOffset(), clang::ASTRecordLayout::getFieldOffset(), clang::ArraySubscriptExpr::getIdx(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::DeclContext::getParent(), clang::BinaryOperator::getRHS(), clang::Stmt::getStmtClass(), clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::Expr::IgnoreParens(), clang::Type::isReferenceType(), Offset, P, and clang::CharUnits::Zero().
Referenced by getBaseAlignmentAndOffsetFromLValue(), and getBaseAlignmentAndOffsetFromPtr().
getBaseAlignmentAndOffsetFromPtr()
static std::optional< std::pair< CharUnits, CharUnits > > getBaseAlignmentAndOffsetFromPtr (const Expr * E, ASTContext & Ctx) static
This helper function takes a pointer expression and returns the alignment of a VarDecl and a constant offset from the VarDecl.
Definition at line 16878 of file SemaChecking.cpp.
References clang::cast(), getAlignmentAndOffsetFromBinAddOrSub(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getASTRecordLayout(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), getDerivedToBaseAlignmentAndOffset(), clang::BinaryOperator::getLHS(), clang::ASTRecordLayout::getNonVirtualAlignment(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::Type::getPointeeType(), clang::BinaryOperator::getRHS(), clang::Stmt::getStmtClass(), clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), clang::Expr::IgnoreParens(), P, and clang::CharUnits::Zero().
Referenced by getAlignmentAndOffsetFromBinAddOrSub(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), and getPresumedAlignmentOfPointer().
getBestAbsFunction()
static unsigned getBestAbsFunction (ASTContext & Context, QualType ArgType, unsigned AbsFunctionKind) static
Definition at line 11775 of file SemaChecking.cpp.
References getAbsoluteValueArgumentType(), getLargerAbsoluteValueFunction(), clang::ASTContext::getTypeSize(), and clang::ASTContext::hasSameType().
getContainedDynamicClass()
static const CXXRecordDecl * getContainedDynamicClass (QualType T, bool & IsContained) static
Determine whether the given type is or contains a dynamic class type (e.g., whether it has a vtable).
Definition at line 12184 of file SemaChecking.cpp.
References clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), clang::Type::getBaseElementTypeUnsafe(), getContainedDynamicClass(), clang::CXXRecordDecl::getDefinition(), clang::ValueDecl::getType(), clang::CXXRecordDecl::isDynamicClass(), and clang::Decl::isInvalidDecl().
Referenced by getContainedDynamicClass().
getDerivedToBaseAlignmentAndOffset()
static std::pair< CharUnits, CharUnits > getDerivedToBaseAlignmentAndOffset (const CastExpr * CE, QualType DerivedType, CharUnits BaseAlignment, CharUnits Offset, ASTContext & Ctx) static
Compute the alignment and offset of the base class object given the derived-to-base cast expression and the alignment and offset of the derived class object.
Definition at line 16724 of file SemaChecking.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getNonVirtualAlignment(), Offset, clang::CastExpr::path_begin(), clang::CastExpr::path_end(), and clang::CharUnits::Zero().
Referenced by getBaseAlignmentAndOffsetFromLValue(), and getBaseAlignmentAndOffsetFromPtr().
GetExprRange() [1/2]
static IntRange GetExprRange (ASTContext & C, const Expr * E, bool InConstantContext, bool Approximate) static
Definition at line 13523 of file SemaChecking.cpp.
References clang::C, GetExprRange(), and GetExprType().
GetExprRange() [2/2]
static IntRange GetExprRange (ASTContext & C, const Expr * E, unsigned MaxWidth, bool InConstantContext, bool Approximate) static
Pseudo-evaluate the given integer expression, estimating the range of values it might take.
Parameters
MaxWidth The width to which the value will be truncated.
Approximate If true, return a likely range for the result: in particular, assume that arithmetic on narrower types doesn't leave those types. If false, return a range including all possible result values.
Definition at line 13274 of file SemaChecking.cpp.
References clang::C, clang::Expr::EvaluateAsRValue(), GetExprRange(), GetExprType(), clang::Expr::getSourceBitField(), clang::Expr::getType(), GetValueRange(), clang::Expr::IgnoreParens(), clang::Type::isVoidType(), log2, and clang::Expr::EvalResult::Val.
Referenced by AnalyzeComparison(), CheckImplicitConversion(), CheckTautologicalComparison(), GetExprRange(), and GetExprRange().
GetExprType()
static QualType GetExprType (const Expr * E) static
Definition at line 13259 of file SemaChecking.cpp.
References clang::Type::getAs(), and clang::Expr::getType().
Referenced by GetExprRange(), and GetExprRange().
getIntegerLiteral()
static const IntegerLiteral * getIntegerLiteral (Expr * E) static
Definition at line 14603 of file SemaChecking.cpp.
Referenced by DiagnoseIntInBoolContext().
getLargerAbsoluteValueFunction()
static unsigned getLargerAbsoluteValueFunction (unsigned AbsFunction) static
Definition at line 11703 of file SemaChecking.cpp.
Referenced by getBestAbsFunction().
GetMatchingCType()
static bool GetMatchingCType (const IdentifierInfo * ArgumentKind, const Expr * TypeExpr, const ASTContext & Ctx, const llvm::DenseMap< Sema::TypeTagMagicValue, Sema::TypeTagData > * MagicValues, bool & FoundWrongKind, Sema::TypeTagData & TypeInfo, bool isConstantEvaluated) static
Retrieve the C type corresponding to type tag TypeExpr.
Parameters
TypeExpr Expression that specifies a type tag.
MagicValues Registered magic values.
FoundWrongKind Set to true if a type tag was found, but of a wrong kind.
TypeInfo Information about the corresponding C type.
isConstantEvaluated whether the evalaution should be performed in constant context.
Returns
true if the corresponding C type was found.
Definition at line 18299 of file SemaChecking.cpp.
References FindTypeTagExpr(), and clang::Decl::getAttr().
getNeonEltType()
static QualType getNeonEltType (NeonTypeFlags Flags, ASTContext & Context, bool IsPolyUnsigned, bool IsInt64Long) static
getNeonEltType - Return the QualType corresponding to the elements of the vector type specified by the NeonTypeFlags.
This is used to check the pointer arguments for Neon load/store intrinsics.
Definition at line 2858 of file SemaChecking.cpp.
References clang::NeonTypeFlags::BFloat16, clang::ASTContext::BFloat16Ty, clang::ASTContext::DoubleTy, clang::NeonTypeFlags::Float16, clang::NeonTypeFlags::Float32, clang::NeonTypeFlags::Float64, clang::ASTContext::FloatTy, clang::NeonTypeFlags::getEltType(), clang::ASTContext::HalfTy, clang::NeonTypeFlags::Int16, clang::NeonTypeFlags::Int32, clang::NeonTypeFlags::Int64, clang::NeonTypeFlags::Int8, clang::ASTContext::IntTy, clang::NeonTypeFlags::isUnsigned(), clang::ASTContext::LongLongTy, clang::ASTContext::LongTy, clang::NeonTypeFlags::Poly128, clang::NeonTypeFlags::Poly16, clang::NeonTypeFlags::Poly64, clang::NeonTypeFlags::Poly8, clang::ASTContext::ShortTy, clang::ASTContext::SignedCharTy, clang::ASTContext::UnsignedCharTy, clang::ASTContext::UnsignedIntTy, clang::ASTContext::UnsignedLongLongTy, clang::ASTContext::UnsignedLongTy, and clang::ASTContext::UnsignedShortTy.
GetNSMutableArrayArgumentIndex()
static std::optional< int > GetNSMutableArrayArgumentIndex (Sema & S, ObjCMessageExpr * Message) static
Definition at line 17501 of file SemaChecking.cpp.
References clang::NSAPI::ClassId_NSMutableArray, clang::Sema::NSAPIObj, clang::NSAPI::NSMutableArr_addObject, clang::NSAPI::NSMutableArr_insertObjectAtIndex, clang::NSAPI::NSMutableArr_replaceObjectAtIndex, and clang::NSAPI::NSMutableArr_setObjectAtIndexedSubscript.
GetNSMutableDictionaryArgumentIndex()
static std::optional< int > GetNSMutableDictionaryArgumentIndex (Sema & S, ObjCMessageExpr * Message) static
Definition at line 17535 of file SemaChecking.cpp.
References clang::NSAPI::ClassId_NSMutableDictionary, clang::Sema::NSAPIObj, clang::NSAPI::NSMutableDict_setObjectForKey, clang::NSAPI::NSMutableDict_setObjectForKeyedSubscript, and clang::NSAPI::NSMutableDict_setValueForKey.
GetNSSetArgumentIndex()
static std::optional< int > GetNSSetArgumentIndex (Sema & S, ObjCMessageExpr * Message) static
Definition at line 17566 of file SemaChecking.cpp.
References clang::NSAPI::ClassId_NSMutableOrderedSet, clang::NSAPI::ClassId_NSMutableSet, clang::Sema::NSAPIObj, clang::NSAPI::NSMutableSet_addObject, clang::NSAPI::NSOrderedSet_insertObjectAtIndex, clang::NSAPI::NSOrderedSet_replaceObjectAtIndexWithObject, clang::NSAPI::NSOrderedSet_setObjectAtIndex, and clang::NSAPI::NSOrderedSet_setObjectAtIndexedSubscript.
getOpenCLArgAccess()
static OpenCLAccessAttr * getOpenCLArgAccess (const Decl * D) static
Returns OpenCL access qual.
Definition at line 1648 of file SemaChecking.cpp.
References clang::Decl::getAttr().
Referenced by checkOpenCLPipeArg().
getPresumedAlignmentOfPointer()
static CharUnits getPresumedAlignmentOfPointer (const Expr * E, Sema & S) static
Definition at line 16943 of file SemaChecking.cpp.
References clang::Sema::Context, getBaseAlignmentAndOffsetFromPtr(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeAlignInChars(), and P.
Referenced by clang::Sema::CheckCastAlign().
getSizeOfArgType()
static QualType getSizeOfArgType (const Expr * E) static
If E is a sizeof expression, returns its argument type.
Definition at line 12230 of file SemaChecking.cpp.
References getAsSizeOfExpr().
getSizeOfExprArg()
static const Expr * getSizeOfExprArg (const Expr * E) static
If E is a sizeof expression, returns its argument expression, otherwise returns NULL.
Definition at line 12222 of file SemaChecking.cpp.
References getAsSizeOfExpr(), and clang::Expr::IgnoreParenImpCasts().
getStrlenExprArg()
static const Expr * getStrlenExprArg (const Expr * E) static
Definition at line 12724 of file SemaChecking.cpp.
References clang::FunctionDecl::getMemoryFunctionKind().
GetValueRange() [1/2]
static IntRange GetValueRange (ASTContext & C, APValue & result, QualType Ty, unsigned MaxWidth) static
Definition at line 13230 of file SemaChecking.cpp.
References clang::C, clang::APValue::getComplexIntImag(), clang::APValue::getComplexIntReal(), clang::APValue::getInt(), GetValueRange(), clang::APValue::getVectorElt(), clang::APValue::getVectorLength(), clang::APValue::isAddrLabelDiff(), clang::APValue::isComplexInt(), clang::APValue::isInt(), clang::APValue::isLValue(), clang::Type::isUnsignedIntegerOrEnumerationType(), and clang::APValue::isVector().
GetValueRange() [2/2]
static IntRange GetValueRange (ASTContext & C, llvm::APSInt & value, unsigned MaxWidth) static
Definition at line 13217 of file SemaChecking.cpp.
Referenced by GetExprRange(), and GetValueRange().
HasEnumType()
static bool HasEnumType (Expr * E) static
Definition at line 13722 of file SemaChecking.cpp.
References clang::Expr::getType(), and clang::Type::isEnumeralType().
Referenced by CheckTautologicalComparison().
ignoreLiteralAdditions()
static const Expr * ignoreLiteralAdditions (const Expr * Ex, ASTContext & Ctx) static
Definition at line 12612 of file SemaChecking.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getRHS(), clang::Expr::IgnoreParenCasts(), and clang::BinaryOperator::isAdditiveOp().
isArgumentExpandedFromMacro()
static bool isArgumentExpandedFromMacro (SourceManager & SM, SourceLocation CallLoc, SourceLocation ArgLoc) static
Check if the ArgLoc originated from a macro passed to the call at CallLoc.
#define MACRO 0
foo(MACRO);
foo(0);
This should return true for the first call to foo, but not for the second (regardless of whether foo is a macro or function).
Definition at line 12353 of file SemaChecking.cpp.
References clang::SourceLocation::isMacroID(), and SM.
Referenced by CheckMemaccessSize().
isArithmeticArgumentPromotion()
static bool isArithmeticArgumentPromotion (Sema & S, const ImplicitCastExpr * ICE) static
Return true if ICE is an implicit argument promotion of an arithmetic type.
Bit-field 'promotions' from a higher ranked type to a lower ranked type do not count.
Definition at line 11048 of file SemaChecking.cpp.
References clang::Sema::Context, clang::Type::getAs(), clang::CastExpr::getCastKind(), clang::ASTContext::getFloatingTypeOrder(), clang::ASTContext::getPromotedIntegerType(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), and clang::ASTContext::isPromotableIntegerType().
isBlockPointer()
static bool isBlockPointer (Expr * Arg) inline static
Definition at line 1370 of file SemaChecking.cpp.
References clang::Expr::getType(), and clang::Type::isBlockPointerType().
Referenced by computeCopyInfoForBlockCapture(), inferARCWriteback(), SemaOpenCLBuiltinEnqueueKernel(), SemaOpenCLBuiltinKernelWorkGroupSize(), and SemaOpenCLBuiltinNDRangeAndBlock().
isConstantSizeArrayWithMoreThanOneElement()
static bool isConstantSizeArrayWithMoreThanOneElement (QualType Ty, ASTContext & Context) static
Definition at line 12634 of file SemaChecking.cpp.
References clang::ASTContext::getAsConstantArrayType(), and clang::Type::isVariableArrayType().
IsEnumConstOrFromMacro()
static bool IsEnumConstOrFromMacro (Sema & S, Expr * E) static
Definition at line 13570 of file SemaChecking.cpp.
References clang::Stmt::getBeginLoc(), clang::Lexer::getImmediateMacroName(), clang::Sema::getLangOpts(), clang::Sema::getSourceManager(), clang::Expr::IgnoreParenImpCasts(), and clang::SourceLocation::isMacroID().
Referenced by CheckTautologicalComparison().
IsImplicitBoolFloatConversion()
static bool IsImplicitBoolFloatConversion (Sema & S, Expr * Ex, bool ToBool) static
Definition at line 14393 of file SemaChecking.cpp.
References clang::Sema::Context, clang::ASTContext::getCanonicalType(), clang::Expr::getType(), clang::CanQual< typename >::getTypePtr(), clang::Expr::IgnoreParenImpCasts(), clang::BuiltinType::isFloatingPoint(), clang::Type::isSpecificBuiltinType(), and clang::Target.
Referenced by CheckImplicitArgumentConversions().
IsInAnyMacroBody()
static bool IsInAnyMacroBody (const SourceManager & SM, SourceLocation Loc) static
Definition at line 15420 of file SemaChecking.cpp.
References SM.
Referenced by clang::Sema::DiagnoseAlwaysNonNullPointer().
isKnownToHaveUnsignedValue()
static bool isKnownToHaveUnsignedValue (Expr * E) static
Definition at line 13591 of file SemaChecking.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isIntegerType(), and clang::Type::isSignedIntegerType().
Referenced by CheckTautologicalComparison().
isLayoutCompatible() [1/4]
static bool isLayoutCompatible (ASTContext & C, EnumDecl * ED1, EnumDecl * ED2) static
Check if two enumeration types are layout-compatible.
Definition at line 18057 of file SemaChecking.cpp.
References clang::C, clang::EnumDecl::getIntegerType(), and clang::EnumDecl::isComplete().
isLayoutCompatible() [2/4]
static bool isLayoutCompatible (ASTContext & C, FieldDecl * Field1, FieldDecl * Field2) static
Check if two fields are layout-compatible.
Definition at line 18066 of file SemaChecking.cpp.
References clang::C, clang::FieldDecl::getBitWidthValue(), clang::ValueDecl::getType(), clang::FieldDecl::isBitField(), and isLayoutCompatible().
isLayoutCompatible() [3/4]
static bool isLayoutCompatible (ASTContext & C, QualType T1, QualType T2) static
Check if two types are layout-compatible in C++11 sense.
Definition at line 18170 of file SemaChecking.cpp.
References clang::C, clang::QualType::getCanonicalType(), clang::Type::getTypeClass(), clang::QualType::getUnqualifiedType(), isLayoutCompatible(), clang::QualType::isNull(), and clang::Type::isStandardLayoutType().
Referenced by isLayoutCompatible(), isLayoutCompatible(), isLayoutCompatibleStruct(), and isLayoutCompatibleUnion().
isLayoutCompatible() [4/4]
static bool isLayoutCompatible (ASTContext & C, RecordDecl * RD1, RecordDecl * RD2) static
Definition at line 18158 of file SemaChecking.cpp.
References clang::C, isLayoutCompatibleStruct(), isLayoutCompatibleUnion(), and clang::TagDecl::isUnion().
isLayoutCompatibleStruct()
static bool isLayoutCompatibleStruct (ASTContext & C, RecordDecl * RD1, RecordDecl * RD2) static
Check if two standard-layout structs are layout-compatible.
(C++11 [class.mem] p17)
Definition at line 18088 of file SemaChecking.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::C, clang::cast(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::CXXRecordDecl::getNumBases(), and isLayoutCompatible().
Referenced by isLayoutCompatible().
isLayoutCompatibleUnion()
static bool isLayoutCompatibleUnion (ASTContext & C, RecordDecl * RD1, RecordDecl * RD2) static
Check if two standard-layout unions are layout-compatible.
(C++11 [class.mem] p18)
Definition at line 18132 of file SemaChecking.cpp.
References clang::C, clang::RecordDecl::fields(), isLayoutCompatible(), and clang::Result.
Referenced by isLayoutCompatible().
isNonNullType()
static bool isNonNullType (QualType type) static
Determine whether the given type has a non-null nullability annotation.
Definition at line 6471 of file SemaChecking.cpp.
References clang::NonNull.
Referenced by CheckNonNullArguments().
isObjCSignedCharBool()
static bool isObjCSignedCharBool (Sema & S, QualType Ty) static
Definition at line 14209 of file SemaChecking.cpp.
References clang::Sema::getLangOpts(), clang::Type::isSpecificBuiltinType(), and clang::Sema::NSAPIObj.
Referenced by CheckImplicitConversion(), and DiagnoseFloatingImpCast().
isPPC_64Builtin()
static bool isPPC_64Builtin (unsigned BuiltinID) static
Definition at line 4181 of file SemaChecking.cpp.
IsSameCharType()
static bool IsSameCharType (QualType T1, QualType T2) static
Definition at line 18356 of file SemaChecking.cpp.
References clang::Type::getAs(), and clang::BuiltinType::getKind().
IsSameFloatAfterCast() [1/2]
static bool IsSameFloatAfterCast (const APValue & value, const llvm::fltSemantics & Src, const llvm::fltSemantics & Tgt) static
Checks whether the given value, which currently has the given source semantics, has the same value when coerced through the target semantics.
The value might be a vector of floats (or a complex number).
Definition at line 13549 of file SemaChecking.cpp.
References clang::APValue::getComplexFloatImag(), clang::APValue::getComplexFloatReal(), clang::APValue::getFloat(), clang::APValue::getVectorElt(), clang::APValue::getVectorLength(), clang::APValue::isComplexFloat(), clang::APValue::isFloat(), IsSameFloatAfterCast(), and clang::APValue::isVector().
IsSameFloatAfterCast() [2/2]
static bool IsSameFloatAfterCast (const llvm::APFloat & value, const llvm::fltSemantics & Src, const llvm::fltSemantics & Tgt) static
Checks whether the given value, which currently has the given source semantics, has the same value when coerced through the target semantics.
Definition at line 13532 of file SemaChecking.cpp.
Referenced by CheckImplicitConversion(), and IsSameFloatAfterCast().
isSameWidthConstantConversion()
static bool isSameWidthConstantConversion (Sema & S, Expr * E, QualType T, SourceLocation CC) static
Definition at line 14579 of file SemaChecking.cpp.
References clang::SourceManager::getCharacterData(), clang::Sema::getSourceManager(), clang::Expr::IgnoreParenImpCasts(), and clang::SourceLocation::isValid().
Referenced by CheckImplicitConversion().
isSetterLikeSelector()
static bool isSetterLikeSelector (Selector sel) static
Check for a keyword selector that starts with the word 'add' or 'set'.
Definition at line 17480 of file SemaChecking.cpp.
References clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::isLowercase(), and clang::Selector::isUnarySelector().
Referenced by clang::Sema::checkRetainCycles().
IsShiftedByte()
static bool IsShiftedByte (llvm::APSInt Value) static
Definition at line 8867 of file SemaChecking.cpp.
IsStdFunction()
template<std::size_t StrLen> static bool IsStdFunction (const FunctionDecl * FDecl, const char(&) Str[StrLen]) static
Definition at line 11993 of file SemaChecking.cpp.
References clang::NamedDecl::getIdentifier(), clang::Decl::isInStdNamespace(), and clang::IdentifierInfo::isStr().
isValidBPFPreserveEnumValueArg()
static bool isValidBPFPreserveEnumValueArg (Expr * Arg) static
Definition at line 3454 of file SemaChecking.cpp.
References clang::Type::getAs(), clang::Expr::getType(), clang::Type::getUnqualifiedDesugaredType(), and clang::Expr::IgnoreParens().
isValidBPFPreserveFieldInfoArg()
static bool isValidBPFPreserveFieldInfoArg (Expr * Arg) static
Definition at line 3410 of file SemaChecking.cpp.
References clang::Type::getAsPlaceholderType(), clang::Expr::getObjectKind(), clang::Expr::getType(), clang::Expr::IgnoreParens(), and clang::OK_BitField.
isValidBPFPreserveTypeInfoArg()
static bool isValidBPFPreserveTypeInfoArg (Expr * Arg) static
Definition at line 3423 of file SemaChecking.cpp.
References clang::Type::getAs(), clang::Expr::getType(), clang::Type::getUnqualifiedDesugaredType(), and clang::Expr::IgnoreParens().
isValidOrderingForOp()
static bool isValidOrderingForOp (int64_t Ordering, AtomicExpr::AtomicOp Op) static
Definition at line 6913 of file SemaChecking.cpp.
Referenced by clang::Sema::BuildAtomicExpr().
isX86_32Builtin()
static bool isX86_32Builtin (unsigned BuiltinID) static
Definition at line 5958 of file SemaChecking.cpp.
maybeConstEvalStringLiteral()
static const Expr * maybeConstEvalStringLiteral (ASTContext & Context, const Expr * E) static
Definition at line 9861 of file SemaChecking.cpp.
References clang::Expr::EvaluateAsRValue(), and clang::Result.
Referenced by checkFormatStringExpr().
PrettyPrintInRange()
static std::string PrettyPrintInRange (const llvm::APSInt & Value, IntRange Range) static
Definition at line 14383 of file SemaChecking.cpp.
References toString().
Referenced by CheckImplicitConversion().
referToTheSameDecl()
static bool referToTheSameDecl (const Expr * E1, const Expr * E2) static
Check if two expressions refer to the same declaration.
Definition at line 12717 of file SemaChecking.cpp.
requiresParensToAddCast()
static bool requiresParensToAddCast (const Expr * E) static
Definition at line 10952 of file SemaChecking.cpp.
References clang::Stmt::getStmtClass(), and clang::Expr::IgnoreImpCasts().
RFT()
static unsigned RFT (unsigned t, bool shift = false, bool ForceQuad = false) static
Definition at line 2822 of file SemaChecking.cpp.
References clang::NeonTypeFlags::BFloat16, clang::NeonTypeFlags::Float16, clang::NeonTypeFlags::Float32, clang::NeonTypeFlags::Float64, clang::NeonTypeFlags::Int16, clang::NeonTypeFlags::Int32, clang::NeonTypeFlags::Int64, clang::NeonTypeFlags::Int8, clang::NeonTypeFlags::Poly128, clang::NeonTypeFlags::Poly16, clang::NeonTypeFlags::Poly64, clang::NeonTypeFlags::Poly8, true, and Type.
SemaBuiltinAddressof()
static bool SemaBuiltinAddressof (Sema & S, CallExpr * TheCall) static
Check that the argument to __builtin_addressof is a glvalue, and set the result type to the corresponding pointer type.
Definition at line 239 of file SemaChecking.cpp.
References clang::Sema::CheckAddressOfOperand(), checkArgCount(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::QualType::isNull(), clang::CallExpr::setArg(), and clang::Expr::setType().
SemaBuiltinAlignment()
static bool SemaBuiltinAlignment (Sema & S, CallExpr * TheCall, unsigned ID) static
Check that the value argument for __builtin_is_aligned(value, alignment) and __builtin_aligned_{up,down}(value, alignment) is an integer or a pointer type (but not a function pointer) and that the alignment is a power-of-two.
Definition at line 289 of file SemaChecking.cpp.
References clang::ASTContext::BoolTy, clang::Type::canDecayToPointerType(), checkArgCount(), clang::Sema::Context, clang::Sema::Diag(), clang::Expr::EvaluateAsInt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::ASTContext::getDecayedType(), clang::Expr::getExprLoc(), clang::APValue::getInt(), clang::ASTContext::getIntWidth(), clang::Expr::getType(), clang::InitializedEntity::InitializeParameter(), clang::Type::isArrayType(), clang::Type::isFunctionPointerType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isPointerType(), clang::Expr::isValueDependent(), clang::Sema::PerformCopyInitialization(), clang::Expr::SE_AllowSideEffects, clang::CallExpr::setArg(), clang::Expr::setType(), toString(), and clang::Expr::EvalResult::Val.
SemaBuiltinAnnotation()
static bool SemaBuiltinAnnotation (Sema & S, CallExpr * TheCall) static
Check that the first argument to __builtin_annotation is an integer and the second argument is a non-wide string literal.
Definition at line 189 of file SemaChecking.cpp.
References checkArgCount(), clang::Sema::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::Type::isIntegerType(), and clang::Expr::setType().
SemaBuiltinCallWithStaticChain()
static bool SemaBuiltinCallWithStaticChain (Sema & S, CallExpr * BuiltinCall) static
Definition at line 729 of file SemaChecking.cpp.
References clang::cast(), checkArgCount(), clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::CallExpr::getCallee(), clang::ASTContext::getFunctionType(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreImpCasts(), clang::Sema::ImpCastExprToType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isPointerType(), clang::CallExpr::setArg(), clang::CallExpr::setCallee(), clang::Expr::setObjectKind(), clang::Expr::setType(), clang::Expr::setValueKind(), and clang::Sema::UsualUnaryConversions().
SemaBuiltinCommitRWPipe()
static bool SemaBuiltinCommitRWPipe (Sema & S, CallExpr * Call) static
Definition at line 1810 of file SemaChecking.cpp.
References checkArgCount(), checkOpenCLPipeArg(), clang::Sema::Context, clang::Sema::Diag(), and clang::ASTContext::OCLReserveIDTy.
SemaBuiltinCpuIs()
static bool SemaBuiltinCpuIs (Sema & S, const TargetInfo & TI, CallExpr * TheCall) static
SemaBuiltinCpuIs - Handle __builtin_cpu_is(char *).
This checks that the target supports __builtin_cpu_is and that the string argument is constant and valid.
Definition at line 5480 of file SemaChecking.cpp.
References clang::cast(), clang::Sema::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), and clang::TargetInfo::validateCpuIs().
SemaBuiltinCpuSupports()
static bool SemaBuiltinCpuSupports (Sema & S, const TargetInfo & TI, CallExpr * TheCall) static
SemaBuiltinCpuSupports - Handle __builtin_cpu_supports(char *).
This checks that the target supports __builtin_cpu_supports and that the string argument is constant and valid.
Definition at line 5459 of file SemaChecking.cpp.
References clang::cast(), clang::Sema::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), and clang::TargetInfo::validateCpuSupports().
SemaBuiltinDumpStruct()
static ExprResult SemaBuiltinDumpStruct (Sema & S, CallExpr * TheCall) static
Definition at line 668 of file SemaChecking.cpp.
References checkArgCountAtLeast(), clang::Sema::Context, clang::Sema::DefaultLvalueConversion(), clang::Sema::Diag(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::Type::getAs(), clang::Type::getAsRecordDecl(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::Stmt::getEndLoc(), clang::Sema::getLangOpts(), clang::Sema::getLocForEndOfToken(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::Type::isBlockPointerType(), clang::Type::isFunctionPointerType(), clang::Type::isFunctionType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isPointerType(), clang::Type::isRecordType(), and clang::CallExpr::setArg().
SemaBuiltinFunctionStart()
static bool SemaBuiltinFunctionStart (Sema & S, CallExpr * TheCall) static
Check that the argument to __builtin_function_start is a function.
Definition at line 254 of file SemaChecking.cpp.
References clang::Sema::checkAddressOfFunctionIsAvailable(), checkArgCount(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::Expr::getAsBuiltinConstantDeclRef(), clang::Sema::getASTContext(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::CallExpr::setArg().
SemaBuiltinLaunder()
static ExprResult SemaBuiltinLaunder (Sema & S, CallExpr * TheCall) static
Definition at line 1893 of file SemaChecking.cpp.
References checkArgCount(), clang::Sema::Context, clang::Sema::Diag(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::Type::getAsArrayTypeUnsafe(), clang::CallExpr::getBeginLoc(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::InitializedEntity::InitializeParameter(), clang::Type::isFunctionPointerType(), clang::Type::isFunctionType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isObjectType(), clang::Type::isPointerType(), clang::Type::isVoidPointerType(), clang::Sema::PerformCopyInitialization(), clang::Sema::RequireCompleteType(), clang::CallExpr::setArg(), and clang::Expr::setType().
SemaBuiltinMSVCAnnotation()
static bool SemaBuiltinMSVCAnnotation (Sema & S, CallExpr * TheCall) static
Definition at line 215 of file SemaChecking.cpp.
References clang::CallExpr::arguments(), clang::Sema::Diag(), clang::CallExpr::getCallee(), clang::CallExpr::getEndLoc(), clang::CallExpr::getNumArgs(), and clang::Stmt::getSourceRange().
SemaBuiltinOverflow()
static bool SemaBuiltinOverflow (Sema & S, CallExpr * TheCall, unsigned BuiltinID) static
Definition at line 367 of file SemaChecking.cpp.
References checkArgCount(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getArg(), clang::Type::getAs(), clang::Sema::getASTContext(), clang::Stmt::getBeginLoc(), clang::ASTContext::getIntWidth(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isIntegerType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::CallExpr::setArg().
SemaBuiltinPipePackets()
static bool SemaBuiltinPipePackets (Sema & S, CallExpr * Call) static
Definition at line 1833 of file SemaChecking.cpp.
References checkArgCount(), and clang::Sema::Diag().
SemaBuiltinPreserveAI()
static bool SemaBuiltinPreserveAI (Sema & S, CallExpr * TheCall) static
Check the number of arguments and set the result type to the argument type.
Definition at line 278 of file SemaChecking.cpp.
References checkArgCount(), clang::CallExpr::getArg(), clang::Expr::getType(), and clang::Expr::setType().
SemaBuiltinReserveRWPipe()
static bool SemaBuiltinReserveRWPipe (Sema & S, CallExpr * Call) static
Definition at line 1781 of file SemaChecking.cpp.
References checkArgCount(), checkOpenCLPipeArg(), clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::OCLReserveIDTy, and clang::ASTContext::UnsignedIntTy.
SemaBuiltinRWPipe()
static bool SemaBuiltinRWPipe (Sema & S, CallExpr * Call) static
Definition at line 1726 of file SemaChecking.cpp.
References checkOpenCLPipeArg(), checkOpenCLPipePacketType(), clang::Sema::Context, clang::Sema::Diag(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isIntegerType(), clang::Type::isUnsignedIntegerType(), clang::ASTContext::OCLReserveIDTy, and clang::ASTContext::UnsignedIntTy.
SemaBuiltinSEHScopeCheck()
static bool SemaBuiltinSEHScopeCheck (Sema & SemaRef, CallExpr * TheCall, Scope::ScopeFlags NeededScopeFlags, unsigned DiagID) static
Definition at line 1348 of file SemaChecking.cpp.
References clang::cast(), clang::Sema::Diag(), clang::CallExpr::getCallee(), clang::Sema::getCurScope(), clang::Expr::getExprLoc(), clang::Expr::IgnoreParenCasts(), and clang::Sema::inTemplateInstantiation().
SemaOpenCLBuiltinEnqueueKernel()
static bool SemaOpenCLBuiltinEnqueueKernel (Sema & S, CallExpr * TheCall) static
OpenCL C v2.0, s6.13.17 - Enqueue kernel function contains four different overload formats specified in Table 6.13.17.1.
int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, void (^block)(void)) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, uint num_events_in_wait_list, clk_event_t event_wait_list, clk_event_t *event_ret, void (^block)(void)) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, void (^block)(local void, ...), uint size0, ...) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, uint num_events_in_wait_list, clk_event_t event_wait_list, clk_event_t *event_ret, void (^block)(local void, ...), uint size0, ...)
Definition at line 1527 of file SemaChecking.cpp.
References clang::cast(), clang::Type::castAs(), checkOpenCLBlockArgs(), checkOpenCLEnqueueVariadicArgs(), clang::Sema::Context, clang::Sema::Diag(), clang::CallExpr::getArg(), clang::QualType::getAsString(), clang::CallExpr::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::QualType::getCanonicalType(), clang::CallExpr::getDirectCallee(), clang::CallExpr::getNumArgs(), clang::FunctionProtoType::getNumParams(), clang::Type::getPointeeOrArrayElementType(), clang::BlockPointerType::getPointeeType(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), isBlockPointer(), clang::Type::isClkEventT(), clang::Type::isIntegerType(), clang::Expr::isNullPointerConstant(), clang::Type::isPointerType(), clang::Type::isQueueT(), clang::Expr::NPC_ValueDependentIsNotNull, clang::ASTContext::OCLClkEventTy, and clang::ASTContext::OCLQueueTy.
SemaOpenCLBuiltinKernelWorkGroupSize()
static bool SemaOpenCLBuiltinKernelWorkGroupSize (Sema & S, CallExpr * TheCall) static
OpenCL C v2.0, s6.13.17.6 - Check the argument to the get_kernel_work_group_size and get_kernel_preferred_work_group_size_multiple builtin functions.
Definition at line 1451 of file SemaChecking.cpp.
References checkArgCount(), checkOpenCLBlockArgs(), clang::Sema::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), and isBlockPointer().
SemaOpenCLBuiltinNDRangeAndBlock()
static bool SemaOpenCLBuiltinNDRangeAndBlock (Sema & S, CallExpr * TheCall) static
Definition at line 1424 of file SemaChecking.cpp.
References checkArgCount(), checkOpenCLBlockArgs(), checkOpenCLSubgroupExt(), clang::Sema::Diag(), clang::CallExpr::getArg(), clang::QualType::getAsString(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), and isBlockPointer().
SemaOpenCLBuiltinToAddr()
static bool SemaOpenCLBuiltinToAddr (Sema & S, unsigned BuiltinID, CallExpr * Call) static
Definition at line 1852 of file SemaChecking.cpp.
References checkArgCount(), clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getPointerType(), clang::ASTContext::getQualifiedType(), clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_local, and clang::opencl_private.
ShouldDiagnoseEmptyStmtBody()
static bool ShouldDiagnoseEmptyStmtBody (const SourceManager & SourceMgr, SourceLocation StmtLoc, const NullStmt * Body) static
Definition at line 17841 of file SemaChecking.cpp.
References clang::NullStmt::getSemiLoc(), and clang::NullStmt::hasLeadingEmptyMacro().
Referenced by clang::Sema::DiagnoseEmptyLoopBody(), and clang::Sema::DiagnoseEmptyStmtBody().
shouldNotPrintDirectly()
static std::pair< QualType, StringRef > shouldNotPrintDirectly (const ASTContext & Context, QualType IntendedTy, const Expr * E) static
Definition at line 10989 of file SemaChecking.cpp.
References clang::Type::getAs(), clang::ASTContext::getNSIntegerType(), clang::ASTContext::getNSUIntegerType(), clang::ASTContext::IntTy, clang::QualType::isNull(), shouldNotPrintDirectly(), and clang::ASTContext::UnsignedIntTy.
Referenced by shouldNotPrintDirectly().
sumOffsets()
static void sumOffsets (llvm::APSInt & Offset, llvm::APSInt Addend, BinaryOperatorKind BinOpKind, bool AddendIsRight) static
Definition at line 9391 of file SemaChecking.cpp.
References Offset, and sumOffsets().
Referenced by checkFormatStringExpr(), and sumOffsets().