clang: lib/Sema/SemaTemplateVariadic.cpp File Reference
SemaTemplateVariadic.cpp File Reference
#include "clang/Sema/Sema.h"
#include "TypeLocBuilder.h"
#include "clang/AST/Expr.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include <optional>
#include "clang/Basic/TransformTypeTraits.def"
#include "clang/Basic/OpenCLImageTypes.def"
Macros
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait)
#define GENERIC_IMAGE_TYPE(ImgType, Id)
Functions
static void CheckFoldOperand (Sema &S, Expr *E)
Macro Definition Documentation
GENERIC_IMAGE_TYPE
#define GENERIC_IMAGE_TYPE (ImgType, Id)
Value:
case TST_##ImgType##_t:
TRANSFORM_TYPE_TRAIT_DEF
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait)
Value:
case TST_##Trait:
Function Documentation
CheckFoldOperand()
static void CheckFoldOperand (Sema & S, Expr * E) static
Definition at line 1173 of file SemaTemplateVariadic.cpp.
References clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), and clang::Expr::IgnoreImpCasts().
Referenced by clang::Sema::ActOnCXXFoldExpr().