clang: lib/Sema/SemaSYCL.cpp File Reference
SemaSYCL.cpp File Reference
#include "clang/AST/Mangle.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaDiagnostic.h"
Functions
static bool isZeroSizedArray (Sema &SemaRef, QualType Ty)
Function Documentation
isZeroSizedArray()
static bool isZeroSizedArray (Sema & SemaRef, QualType Ty) static
Definition at line 36 of file SemaSYCL.cpp.
References clang::ASTContext::getAsConstantArrayType(), and clang::Sema::getASTContext().
Referenced by clang::Sema::deepTypeCheckForSYCLDevice().