clang: lib/Sema/SemaConcept.cpp File Reference
SemaConcept.cpp File Reference
#include "clang/Sema/SemaConcept.h"
#include "TreeTransform.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Basic/OperatorPrecedence.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaDiagnostic.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include "clang/Sema/TemplateDeduction.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/StringExtras.h"
#include <optional>
Typedefs
using NormalForm
Functions
template<typename AtomicEvaluator >
static ExprResult calculateConstraintSatisfaction (Sema &S, const Expr *ConstraintExpr, ConstraintSatisfaction &Satisfaction, AtomicEvaluator &&Evaluator)
static bool DiagRecursiveConstraintEval (Sema &S, llvm::FoldingSetNodeID &ID, const NamedDecl *Templ, const Expr *E, const MultiLevelTemplateArgumentList &MLTAL)
static ExprResult calculateConstraintSatisfaction (Sema &S, const NamedDecl *Template, SourceLocation TemplateNameLoc, const MultiLevelTemplateArgumentList &MLTAL, const Expr *ConstraintExpr, ConstraintSatisfaction &Satisfaction)
static bool CheckConstraintSatisfaction (Sema &S, const NamedDecl *Template, ArrayRef< const Expr * > ConstraintExprs, llvm::SmallVectorImpl< Expr * > &Converted, const MultiLevelTemplateArgumentList &TemplateArgsLists, SourceRange TemplateIDRange, ConstraintSatisfaction &Satisfaction)
static unsigned CalculateTemplateDepthForConstraints (Sema &S, const NamedDecl *ND, bool SkipForSpecialization=false)
static const Expr * SubstituteConstraintExpression (Sema &S, const NamedDecl *ND, const Expr *ConstrExpr)
static void diagnoseUnsatisfiedRequirement (Sema &S, concepts::ExprRequirement *Req, bool First)
static void diagnoseUnsatisfiedRequirement (Sema &S, concepts::TypeRequirement *Req, bool First)
static void diagnoseWellFormedUnsatisfiedConstraintExpr (Sema &S, Expr *SubstExpr, bool First=true)
static void diagnoseUnsatisfiedRequirement (Sema &S, concepts::NestedRequirement *Req, bool First)
template<typename SubstitutionDiagnostic >
static void diagnoseUnsatisfiedConstraintExpr (Sema &S, const Expr *E, const llvm::PointerUnion< Expr *, SubstitutionDiagnostic * > &Record, bool First=true)
static bool substituteParameterMappings (Sema &S, NormalizedConstraint &N, ConceptDecl *Concept, const MultiLevelTemplateArgumentList &MLTAL, const ASTTemplateArgumentListInfo *ArgsAsWritten)
static bool substituteParameterMappings (Sema &S, NormalizedConstraint &N, const ConceptSpecializationExpr *CSE)
static NormalForm makeCNF (const NormalizedConstraint &Normalized)
static NormalForm makeDNF (const NormalizedConstraint &Normalized)
template<typename AtomicSubsumptionEvaluator >
static bool subsumes (const NormalForm &PDNF, const NormalForm &QCNF, AtomicSubsumptionEvaluator E)
template<typename AtomicSubsumptionEvaluator >
static bool subsumes (Sema &S, NamedDecl *DP, ArrayRef< const Expr * > P, NamedDecl *DQ, ArrayRef< const Expr * > Q, bool &Subsumes, AtomicSubsumptionEvaluator E)
Typedef Documentation
NormalForm
using NormalForm
Initial value:
    llvm::SmallVector<llvm::SmallVector<AtomicConstraint *, 2>, 4>
Definition at line 1334 of file SemaConcept.cpp.
Function Documentation
calculateConstraintSatisfaction() [1/2]
template<typename AtomicEvaluator > static ExprResult calculateConstraintSatisfaction (Sema & S, const Expr * ConstraintExpr, ConstraintSatisfaction & Satisfaction, AtomicEvaluator && Evaluator) static
Definition at line 180 of file SemaConcept.cpp.
References clang::C, calculateConstraintSatisfaction(), clang::Sema::ConstantEvaluated, clang::ConstraintSatisfaction::ContainsErrors, clang::Expr::containsErrors(), clang::Sema::Context, clang::ConstraintSatisfaction::Details, clang::Expr::EvalStatus::Diag, clang::Sema::Diag(), clang::PartialDiagnostic::EmitToString(), clang::Expr::EvaluateAsConstantExpr(), clang::ExprEmpty(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Sema::getDiagnostics(), clang::APValue::getInt(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), clang::APValue::isInt(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::ConstraintSatisfaction::IsSatisfied, clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), memcpy(), clang::Sema::PDiag(), and clang::Expr::EvalResult::Val.
Referenced by calculateConstraintSatisfaction(), calculateConstraintSatisfaction(), CheckConstraintSatisfaction(), and clang::Sema::CheckConstraintSatisfaction().
calculateConstraintSatisfaction() [2/2]
static ExprResult calculateConstraintSatisfaction (Sema & S, const NamedDecl * Template, SourceLocation TemplateNameLoc, const MultiLevelTemplateArgumentList & MLTAL, const Expr * ConstraintExpr, ConstraintSatisfaction & Satisfaction) static
Definition at line 316 of file SemaConcept.cpp.
References calculateConstraintSatisfaction(), clang::Sema::CheckConstraintExpression(), clang::Sema::ConstantEvaluated, clang::ConstraintSatisfaction::ContainsErrors, clang::Sema::Context, clang::ImplicitCastExpr::Create(), clang::ConstraintSatisfaction::Details, DiagRecursiveConstraintEval(), clang::ExprEmpty(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::AtomicExpr::getBeginLoc(), clang::Sema::getDiagnostics(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Sema::SFINAETrap::hasErrorOccurred(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::InstantiatingTemplate::isInvalid(), clang::Expr::isPRValue(), clang::ConstraintSatisfaction::IsSatisfied, memcpy(), clang::Sema::ReuseLambdaContextDecl, clang::Sema::SubstConstraintExpr(), clang::sema::TemplateDeductionInfo::takeSFINAEDiagnostic(), and clang::VK_PRValue.
CalculateTemplateDepthForConstraints()
static unsigned CalculateTemplateDepthForConstraints (Sema & S, const NamedDecl * ND, bool SkipForSpecialization = false) static
Definition at line 728 of file SemaConcept.cpp.
References clang::MultiLevelTemplateArgumentList::getNumLevels(), and clang::Sema::getTemplateInstantiationArgs().
Referenced by clang::Sema::FriendConstraintsDependOnEnclosingTemplate(), and clang::Sema::IsAtLeastAsConstrained().
CheckConstraintSatisfaction()
static bool CheckConstraintSatisfaction (Sema & S, const NamedDecl * Template, ArrayRef< const Expr * > ConstraintExprs, llvm::SmallVectorImpl< Expr * > & Converted, const MultiLevelTemplateArgumentList & TemplateArgsLists, SourceRange TemplateIDRange, ConstraintSatisfaction & Satisfaction) static
Definition at line 408 of file SemaConcept.cpp.
References calculateConstraintSatisfaction(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::SourceRange::getBegin(), clang::MultiLevelTemplateArgumentList::getNumSubstitutedLevels(), clang::MultiLevelTemplateArgumentList::getOutermost(), clang::MultiLevelTemplateArgumentList::isAnyArgInstantiationDependent(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::InstantiatingTemplate::isInvalid(), and clang::ConstraintSatisfaction::IsSatisfied.
Referenced by clang::Sema::BuildStaticAssertDeclaration().
diagnoseUnsatisfiedConstraintExpr()
template<typename SubstitutionDiagnostic > static void diagnoseUnsatisfiedConstraintExpr (Sema & S, const Expr * E, const llvm::PointerUnion< Expr *, SubstitutionDiagnostic * > & Record, bool First = true) static
Definition at line 1128 of file SemaConcept.cpp.
References clang::Sema::Diag(), Diag(), diagnoseWellFormedUnsatisfiedConstraintExpr(), and clang::First.
Referenced by clang::Sema::DiagnoseUnsatisfiedConstraint(), and clang::Sema::DiagnoseUnsatisfiedConstraint().
diagnoseUnsatisfiedRequirement() [1/3]
static void diagnoseUnsatisfiedRequirement (Sema & S, concepts::ExprRequirement * Req, bool First) static
Definition at line 915 of file SemaConcept.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagnoseUnsatisfiedConstraint(), clang::First, clang::ConceptSpecializationExpr::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::concepts::ExprRequirement::getExpr(), clang::concepts::ExprRequirement::getExprSubstitutionDiagnostic(), clang::ConceptReference::getNamedConcept(), clang::concepts::ExprRequirement::getNoexceptLoc(), clang::ASTContext::getReferenceQualifiedType(), clang::concepts::ExprRequirement::getReturnTypeRequirement(), clang::concepts::ExprRequirement::getReturnTypeRequirementSubstitutedConstraintExpr(), clang::ConceptSpecializationExpr::getSatisfaction(), clang::concepts::ExprRequirement::getSatisfactionStatus(), clang::concepts::ExprRequirement::ReturnTypeRequirement::getSubstitutionDiagnostic(), clang::ConceptReference::getTemplateArgsAsWritten(), int, clang::concepts::Requirement::isSatisfied(), clang::ASTTemplateArgumentListInfo::NumTemplateArgs, clang::concepts::ExprRequirement::SS_ConstraintsNotSatisfied, clang::concepts::ExprRequirement::SS_Dependent, clang::concepts::ExprRequirement::SS_ExprSubstitutionFailure, clang::concepts::ExprRequirement::SS_NoexceptNotMet, clang::concepts::ExprRequirement::SS_Satisfied, and clang::concepts::ExprRequirement::SS_TypeRequirementSubstitutionFailure.
Referenced by diagnoseWellFormedUnsatisfiedConstraintExpr().
diagnoseUnsatisfiedRequirement() [2/3]
static void diagnoseUnsatisfiedRequirement (Sema & S, concepts::NestedRequirement * Req, bool First) static
Definition at line 1010 of file SemaConcept.cpp.
References clang::Sema::Diag(), diagnoseWellFormedUnsatisfiedConstraintExpr(), clang::First, clang::concepts::NestedRequirement::getConstraintSatisfaction(), clang::concepts::NestedRequirement::getInvalidConstraintEntity(), and int.
diagnoseUnsatisfiedRequirement() [3/3]
static void diagnoseUnsatisfiedRequirement (Sema & S, concepts::TypeRequirement * Req, bool First) static
Definition at line 980 of file SemaConcept.cpp.
References clang::Sema::Diag(), clang::First, clang::concepts::TypeRequirement::getSatisfactionStatus(), clang::concepts::TypeRequirement::getSubstitutionDiagnostic(), int, clang::concepts::Requirement::isSatisfied(), clang::concepts::TypeRequirement::SS_Dependent, and clang::concepts::TypeRequirement::SS_SubstitutionFailure.
diagnoseWellFormedUnsatisfiedConstraintExpr()
static void diagnoseWellFormedUnsatisfiedConstraintExpr (Sema & S, Expr * SubstExpr, bool First = true) static
Definition at line 1025 of file SemaConcept.cpp.
References clang::Sema::Context, clang::Expr::EvalStatus::Diag, clang::Sema::Diag(), clang::Sema::DiagnoseUnsatisfiedConstraint(), diagnoseUnsatisfiedRequirement(), diagnoseWellFormedUnsatisfiedConstraintExpr(), clang::First, clang::SourceRange::getBegin(), clang::Stmt::getBeginLoc(), clang::APValue::getInt(), clang::BinaryOperator::getOpcodeStr(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), int, clang::Expr::SE_NoSideEffects, toString(), and clang::Expr::EvalResult::Val.
Referenced by diagnoseUnsatisfiedConstraintExpr(), diagnoseUnsatisfiedRequirement(), and diagnoseWellFormedUnsatisfiedConstraintExpr().
DiagRecursiveConstraintEval()
static bool DiagRecursiveConstraintEval (Sema & S, llvm::FoldingSetNodeID & ID, const NamedDecl * Templ, const Expr * E, const MultiLevelTemplateArgumentList & MLTAL) static
Definition at line 293 of file SemaConcept.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), clang::Stmt::Profile(), clang::Sema::SatisfactionStackContains(), and clang::TemplateArg.
Referenced by calculateConstraintSatisfaction().
makeCNF()
static NormalForm makeCNF (const NormalizedConstraint & Normalized) static
Definition at line 1337 of file SemaConcept.cpp.
References clang::NormalizedConstraint::CCK_Conjunction, clang::NormalizedConstraint::getAtomicConstraint(), clang::NormalizedConstraint::getCompoundKind(), clang::NormalizedConstraint::getLHS(), clang::NormalizedConstraint::getRHS(), clang::NormalizedConstraint::isAtomic(), and makeCNF().
Referenced by makeCNF(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), and subsumes().
makeDNF()
static NormalForm makeDNF (const NormalizedConstraint & Normalized) static
Definition at line 1366 of file SemaConcept.cpp.
References clang::NormalizedConstraint::CCK_Disjunction, clang::NormalizedConstraint::getAtomicConstraint(), clang::NormalizedConstraint::getCompoundKind(), clang::NormalizedConstraint::getLHS(), clang::NormalizedConstraint::getRHS(), clang::NormalizedConstraint::isAtomic(), and makeDNF().
Referenced by makeDNF(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), and subsumes().
SubstituteConstraintExpression()
static const Expr * SubstituteConstraintExpression (Sema & S, const NamedDecl * ND, const Expr * ConstrExpr) static
Definition at line 765 of file SemaConcept.cpp.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::MultiLevelTemplateArgumentList::getNumSubstitutedLevels(), clang::Sema::getTemplateInstantiationArgs(), clang::Sema::SFINAETrap::hasErrorOccurred(), clang::Sema::InstantiatingTemplate::isInvalid(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), and clang::Sema::SubstConstraintExpr().
Referenced by clang::Sema::AreConstraintExpressionsEqual().
substituteParameterMappings() [1/2]
static bool substituteParameterMappings (Sema & S, NormalizedConstraint & N, ConceptDecl * Concept, const MultiLevelTemplateArgumentList & MLTAL, const ASTTemplateArgumentListInfo * ArgsAsWritten) static
Definition at line 1190 of file SemaConcept.cpp.
References clang::ASTTemplateArgumentListInfo::arguments(), clang::TemplateArgumentListInfo::arguments(), clang::TemplateParameterList::begin(), clang::C, clang::AtomicConstraint::ConstraintExpr, clang::Sema::Context, clang::Sema::getIdentityTemplateArgumentLoc(), clang::Sema::MarkUsedTemplateParameters(), N, clang::ASTTemplateArgumentListInfo::NumTemplateArgs, clang::AtomicConstraint::ParameterMapping, clang::TemplateArgumentListInfo::size(), clang::TemplateParameterList::size(), substituteParameterMappings(), and clang::Sema::SubstTemplateArguments().
Referenced by substituteParameterMappings(), and substituteParameterMappings().
substituteParameterMappings() [2/2]
static bool substituteParameterMappings (Sema & S, NormalizedConstraint & N, const ConceptSpecializationExpr * CSE) static
Definition at line 1244 of file SemaConcept.cpp.
References clang::ConceptReference::getNamedConcept(), clang::ConceptReference::getTemplateArgsAsWritten(), clang::ConceptSpecializationExpr::getTemplateArguments(), clang::Sema::getTemplateInstantiationArgs(), N, clang::TemplateArgumentList::OnStack, and substituteParameterMappings().
subsumes() [1/2]
template<typename AtomicSubsumptionEvaluator > static bool subsumes (const NormalForm & PDNF, const NormalForm & QCNF, AtomicSubsumptionEvaluator E) static
Definition at line 1397 of file SemaConcept.cpp.
Referenced by clang::Sema::IsAtLeastAsConstrained(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), and subsumes().
subsumes() [2/2]
template<typename AtomicSubsumptionEvaluator > static bool subsumes (Sema & S, NamedDecl * DP, ArrayRef< const Expr * > P, NamedDecl * DQ, ArrayRef< const Expr * > Q, bool & Subsumes, AtomicSubsumptionEvaluator E) static
Definition at line 1429 of file SemaConcept.cpp.
References clang::Sema::getNormalizedAssociatedConstraints(), makeCNF(), makeDNF(), P, and subsumes().