clang: lib/Sema/SemaTemplateDeduction.cpp File Reference
SemaTemplateDeduction.cpp File Reference
#include "TreeTransform.h"
#include "TypeLocBuilder.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclAccessPair.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/UnresolvedSet.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Ownership.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/Template.h"
#include "clang/Sema/TemplateDeduction.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <optional>
#include <tuple>
#include <type_traits>
#include <utility>
#include "clang/AST/TypeNodes.inc"
Classes
struct clang::DeducedPack
A pack that we're currently deducing.
struct IsPartialSpecialization< T >
struct IsPartialSpecialization< ClassTemplatePartialSpecializationDecl >
struct IsPartialSpecialization< VarTemplatePartialSpecializationDecl >
Namespaces
namespace clang
Macros
#define NON_CANONICAL_TYPE(Class, Base)
#define TYPE(Class, Base)
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
Enumerations
enum clang::TemplateDeductionFlags {
clang::TDF_None = 0 , clang::TDF_ParamWithReferenceType = 0x1 , clang::TDF_IgnoreQualifiers = 0x02 , clang::TDF_DerivedClass = 0x04 ,
clang::TDF_SkipNonDependent = 0x08 , clang::TDF_TopLevelParameterTypeList = 0x10 , clang::TDF_AllowCompatibleFunctionType = 0x20 , clang::TDF_ArgWithReferenceType = 0x40
}
Various flags that control template argument deduction.
Functions
static bool hasSameExtendedValue (llvm::APSInt X, llvm::APSInt Y)
Compare two APSInts, extending and switching the sign as necessary to compare their values regardless of underlying type.
static Sema::TemplateDeductionResult DeduceTemplateArgumentsByTypeMatch (Sema &S, TemplateParameterList *TemplateParams, QualType P, QualType A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, unsigned TDF, bool PartialOrdering, bool DeducedFromArrayBound)
Deduce the template arguments by comparing the parameter type and the argument type (C++ [temp.deduct.type]).
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, ArrayRef< TemplateArgument > Ps, ArrayRef< TemplateArgument > As, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, bool NumberOfArgumentsMustMatch)
static void MarkUsedTemplateParameters (ASTContext &Ctx, const TemplateArgument &TemplateArg, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by this template argument.
static void MarkUsedTemplateParameters (ASTContext &Ctx, QualType T, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given type.
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (const Expr *E, unsigned Depth)
If the given expression is of a form that permits the deduction of a non-type template parameter, return the declaration of that non-type template parameter.
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (TemplateDeductionInfo &Info, Expr *E)
static bool isSameDeclaration (Decl *X, Decl *Y)
Determine whether two declaration pointers refer to the same declaration.
static DeducedTemplateArgument checkDeducedTemplateArguments (ASTContext &Context, const DeducedTemplateArgument &X, const DeducedTemplateArgument &Y, bool AggregateCandidateDeduction=false)
Verify that the given, deduced template arguments are compatible.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, const DeducedTemplateArgument &NewDeduced, QualType ValueType, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter as the given deduced template argument.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, const llvm::APSInt &Value, QualType ValueType, bool DeducedFromArrayBound, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given integral constant.
static Sema::TemplateDeductionResult DeduceNullPtrTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, QualType NullPtrType, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given null pointer template argument type.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, Expr *Value, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given type- or value-dependent expression.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, ValueDecl *D, QualType T, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given declaration.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, TemplateName Param, TemplateName Arg, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static Sema::TemplateDeductionResult DeduceTemplateSpecArguments (Sema &S, TemplateParameterList *TemplateParams, const QualType P, QualType A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the template arguments by comparing the template parameter type (which is a template-id) with the template argument type.
static bool IsPossiblyOpaquelyQualifiedTypeInternal (const Type *T)
static bool IsPossiblyOpaquelyQualifiedType (QualType T)
Determines whether the given type is an opaque type that might be more qualified when instantiated.
static TemplateParameter makeTemplateParameter (Decl *D)
Helper function to build a TemplateParameter when we don't know its type statically.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const QualType *Params, unsigned NumParams, const QualType *Args, unsigned NumArgs, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, unsigned TDF, bool PartialOrdering=false)
Deduce the template arguments by comparing the list of parameter types to the list of argument types, as in the parameter-type-lists of function types (C++ [temp.deduct.type]p10).
static bool hasInconsistentOrSupersetQualifiersOf (QualType ParamType, QualType ArgType)
Determine whether the parameter has qualifiers that the argument lacks.
static unsigned getFirstInnerIndex (FunctionTemplateDecl *FTD)
Get the index of the first template parameter that was originally from the innermost template-parameter-list.
static bool isForwardingReference (QualType Param, unsigned FirstInnerIndex)
Determine whether a type denotes a forwarding reference.
static CXXRecordDecl * getCanonicalRD (QualType T)
static Sema::TemplateDeductionResult DeduceTemplateBases (Sema &S, const CXXRecordDecl *RD, TemplateParameterList *TemplateParams, QualType P, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Attempt to deduce the template arguments by checking the base types according to (C++20 [temp.deduct.call] p4b3.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const TemplateArgument &P, TemplateArgument A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static bool hasTemplateArgumentForDeduction (ArrayRef< TemplateArgument > &Args, unsigned &ArgIdx)
Determine whether there is a template argument to be used for deduction.
static bool hasPackExpansionBeforeEnd (ArrayRef< TemplateArgument > Args)
Determine whether the given set of template arguments has a pack expansion that is not the last template argument.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const TemplateArgumentList &ParamList, const TemplateArgumentList &ArgList, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static bool isSameTemplateArg (ASTContext &Context, TemplateArgument X, const TemplateArgument &Y, bool PartialOrdering, bool PackExpansionMatchesPack=false)
Determine whether two template arguments are the same.
static bool ConvertDeducedTemplateArgument (Sema &S, NamedDecl *Param, DeducedTemplateArgument Arg, NamedDecl *Template, TemplateDeductionInfo &Info, bool IsDeduced, SmallVectorImpl< TemplateArgument > &SugaredOutput, SmallVectorImpl< TemplateArgument > &CanonicalOutput)
Convert the given deduced template argument and add it to the set of fully-converted template arguments.
template<typename TemplateDeclT >
static Sema::TemplateDeductionResult ConvertDeducedTemplateArguments (Sema &S, TemplateDeclT *Template, bool IsDeduced, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info, SmallVectorImpl< TemplateArgument > &SugaredBuilder, SmallVectorImpl< TemplateArgument > &CanonicalBuilder, LocalInstantiationScope *CurrentInstantiationScope=nullptr, unsigned NumAlreadyConverted=0, bool PartialOverloading=false)
static DeclContext * getAsDeclContextOrEnclosing (Decl *D)
template<typename TemplateDeclT >
static bool DeducedArgsNeedReplacement (TemplateDeclT *Template)
template<>
bool DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl > (VarTemplatePartialSpecializationDecl *Spec)
template<>
bool DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl > (ClassTemplatePartialSpecializationDecl *Spec)
template<typename TemplateDeclT >
static Sema::TemplateDeductionResult CheckDeducedArgumentConstraints (Sema &S, TemplateDeclT *Template, ArrayRef< TemplateArgument > SugaredDeducedArgs, ArrayRef< TemplateArgument > CanonicalDeducedArgs, TemplateDeductionInfo &Info)
template<typename T >
static std::enable_if_t< IsPartialSpecialization< T >::value, Sema::TemplateDeductionResult > FinishTemplateArgumentDeduction (Sema &S, T *Partial, bool IsPartialOrdering, const TemplateArgumentList &TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info)
Complete template argument deduction for a partial specialization.
static Sema::TemplateDeductionResult FinishTemplateArgumentDeduction (Sema &S, TemplateDecl *Template, bool PartialOrdering, const TemplateArgumentList &TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info)
Complete template argument deduction for a class or variable template, when partial ordering against a partial specialization.
static bool isSimpleTemplateIdType (QualType T)
Determine whether the given type T is a simple-template-id type.
static Sema::TemplateDeductionResult CheckOriginalCallArgDeduction (Sema &S, TemplateDeductionInfo &Info, Sema::OriginalCallArg OriginalArg, QualType DeducedA)
Check whether the deduced argument type for a call to a function template matches the actual argument type per C++ [temp.deduct.call]p4.
static unsigned getPackIndexForParam (Sema &S, FunctionTemplateDecl *FunctionTemplate, const MultiLevelTemplateArgumentList &Args, unsigned ParamIdx)
Find the pack index for a particular parameter index in an instantiation of a function template with specific arguments.
static QualType GetTypeOfFunction (Sema &S, const OverloadExpr::FindResult &R, FunctionDecl *Fn)
Gets the type of a function for template-argument-deducton purposes when it's considered as part of an overload set.
static QualType ResolveOverloadForDeduction (Sema &S, TemplateParameterList *TemplateParams, Expr *Arg, QualType ParamType, bool ParamWasReference, TemplateSpecCandidateSet *FailedTSC=nullptr)
Apply the deduction rules for overload sets.
static bool AdjustFunctionParmAndArgTypesForDeduction (Sema &S, TemplateParameterList *TemplateParams, unsigned FirstInnerIndex, QualType &ParamType, QualType &ArgType, Expr *Arg, unsigned &TDF, TemplateSpecCandidateSet *FailedTSC=nullptr)
Perform the adjustments to the parameter and argument types described in C++ [temp.deduct.call].
static bool hasDeducibleTemplateParameters (Sema &S, FunctionTemplateDecl *FunctionTemplate, QualType T)
static Sema::TemplateDeductionResult DeduceTemplateArgumentsFromCallArgument (Sema &S, TemplateParameterList *TemplateParams, unsigned FirstInnerIndex, QualType ParamType, Expr *Arg, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, SmallVectorImpl< Sema::OriginalCallArg > &OriginalCallArgs, bool DecomposedParam, unsigned ArgIdx, unsigned TDF, TemplateSpecCandidateSet *FailedTSC)
Perform template argument deduction per [temp.deduct.call] for a single parameter / argument pair.
static Sema::TemplateDeductionResult DeduceFromInitializerList (Sema &S, TemplateParameterList *TemplateParams, QualType AdjustedParamType, InitListExpr *ILE, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, SmallVectorImpl< Sema::OriginalCallArg > &OriginalCallArgs, unsigned ArgIdx, unsigned TDF)
Attempt template argument deduction from an initializer list deemed to be an argument in a function call.
static bool CheckDeducedPlaceholderConstraints (Sema &S, const AutoType &Type, AutoTypeLoc TypeLoc, QualType Deduced)
static void AddImplicitObjectParameterType (ASTContext &Context, CXXMethodDecl *Method, SmallVectorImpl< QualType > &ArgTypes)
If this is a non-static member function,.
static bool isAtLeastAsSpecializedAs (Sema &S, SourceLocation Loc, FunctionTemplateDecl *FT1, FunctionTemplateDecl *FT2, TemplatePartialOrderingContext TPOC, unsigned NumCallArguments1, bool Reversed)
Determine whether the function template FT1 is at least as specialized as FT2.
static bool isSameTemplate (TemplateDecl *T1, TemplateDecl *T2)
Determine if the two templates are equivalent.
template<typename TemplateLikeDecl >
static bool isAtLeastAsSpecializedAs (Sema &S, QualType T1, QualType T2, TemplateLikeDecl *P2, TemplateDeductionInfo &Info)
Determine whether one partial specialization, P1, is at least as specialized than another, P2.
template<typename TemplateLikeDecl , typename PrimaryDel >
static TemplateLikeDecl * getMoreSpecialized (Sema &S, QualType T1, QualType T2, TemplateLikeDecl *P1, PrimaryDel *P2, TemplateDeductionInfo &Info)
Returns the more specialized template specialization between T1/P1 and T2/P2.
static void MarkUsedTemplateParameters (ASTContext &Ctx, const Expr *E, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given expression.
static void MarkUsedTemplateParameters (ASTContext &Ctx, NestedNameSpecifier *NNS, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given nested name specifier.
static void MarkUsedTemplateParameters (ASTContext &Ctx, TemplateName Name, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given template name.
Macro Definition Documentation
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Base)
DEPENDENT_TYPE
#define DEPENDENT_TYPE (Class, Base)
NON_CANONICAL_TYPE [1/2]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
  case Type::Class: llvm_unreachable("deducing non-canonical type: " #Class);
NON_CANONICAL_TYPE [2/2]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
case Type::Class:
TYPE [1/2]
#define TYPE (Class, Base)
TYPE [2/2]
#define TYPE (Class, Base)
Function Documentation
AddImplicitObjectParameterType()
static void AddImplicitObjectParameterType (ASTContext & Context, CXXMethodDecl * Method, SmallVectorImpl< QualType > & ArgTypes) static
If this is a non-static member function,.
Definition at line 5073 of file SemaTemplateDeduction.cpp.
References clang::ASTContext::getLValueReferenceType(), clang::ASTContext::getQualifiedType(), clang::ASTContext::getRValueReferenceType(), clang::ASTContext::getTypeDeclType(), and clang::RQ_RValue.
Referenced by isAtLeastAsSpecializedAs().
AdjustFunctionParmAndArgTypesForDeduction()
static bool AdjustFunctionParmAndArgTypesForDeduction (Sema & S, TemplateParameterList * TemplateParams, unsigned FirstInnerIndex, QualType & ParamType, QualType & ArgType, Expr * Arg, unsigned & TDF, TemplateSpecCandidateSet * FailedTSC = nullptr) static
Perform the adjustments to the parameter and argument types described in C++ [temp.deduct.call].
Returns
true if the caller should not attempt to perform any template argument deduction based on this P/A pair because the argument is an overloaded function set that could not be resolved.
Definition at line 3875 of file SemaTemplateDeduction.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::ASTContext::getAddrSpaceQualType(), clang::Type::getAs(), clang::Sema::getCompletedType(), clang::ASTContext::getDecayedType(), clang::ASTContext::getDefaultOpenCLPointeeAddrSpace(), clang::Sema::getLangOpts(), clang::ASTContext::getLValueReferenceType(), clang::PointerType::getPointeeType(), clang::ReferenceType::getPointeeType(), clang::QualType::getUnqualifiedType(), clang::QualType::hasQualifiers(), isForwardingReference(), clang::Expr::isLValue(), isSimpleTemplateIdType(), clang::ASTContext::OverloadTy, ResolveOverloadForDeduction(), clang::TDF_DerivedClass, clang::TDF_IgnoreQualifiers, clang::TDF_ParamWithReferenceType, and clang::TDF_SkipNonDependent.
Referenced by DeduceTemplateArgumentsFromCallArgument().
CheckDeducedArgumentConstraints()
template<typename TemplateDeclT > static Sema::TemplateDeductionResult CheckDeducedArgumentConstraints (Sema & S, TemplateDeclT * Template, ArrayRef< TemplateArgument > SugaredDeducedArgs, ArrayRef< TemplateArgument > CanonicalDeducedArgs, TemplateDeductionInfo & Info) static
Definition at line 2880 of file SemaTemplateDeduction.cpp.
References clang::sema::TemplateDeductionInfo::AssociatedConstraintsSatisfaction, clang::Sema::CheckConstraintSatisfaction(), clang::Sema::Context, clang::TemplateArgumentList::CreateCopy(), DeducedArgsNeedReplacement(), clang::sema::TemplateDeductionInfo::getLocation(), clang::Sema::getTemplateInstantiationArgs(), clang::ConstraintSatisfaction::IsSatisfied, clang::TemplateArgumentList::OnStack, clang::MultiLevelTemplateArgumentList::replaceInnermostTemplateArguments(), clang::sema::TemplateDeductionInfo::reset(), clang::Sema::TDK_ConstraintsNotSatisfied, and clang::Sema::TDK_Success.
Referenced by FinishTemplateArgumentDeduction(), and FinishTemplateArgumentDeduction().
CheckDeducedPlaceholderConstraints()
static bool CheckDeducedPlaceholderConstraints (Sema & S, const AutoType & Type, AutoTypeLoc TypeLoc, QualType Deduced) static
Definition at line 4695 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::C, clang::Sema::CheckConstraintSatisfaction(), clang::Sema::CheckTemplateArgumentList(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagnoseUnsatisfiedConstraint(), clang::TypeLoc::getLocalSourceRange(), clang::Sema::getPrintingPolicy(), clang::ASTContext::getTrivialTypeSourceInfo(), and clang::ConstraintSatisfaction::IsSatisfied.
Referenced by clang::Sema::DeduceAutoType().
checkDeducedTemplateArguments()
static DeducedTemplateArgument checkDeducedTemplateArguments (ASTContext & Context, const DeducedTemplateArgument & X, const DeducedTemplateArgument & Y, bool AggregateCandidateDeduction = false) static
Verify that the given, deduced template arguments are compatible.
Returns
The deduced template argument, or a NULL template argument if the deduced template arguments were incompatible.
Definition at line 213 of file SemaTemplateDeduction.cpp.
References checkDeducedTemplateArguments(), clang::TemplateArgument::CreatePackCopy(), clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::ASTContext::getCommonSugaredType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNonTypeTemplateArgumentType(), clang::TemplateArgument::getNullPtrType(), clang::Expr::getType(), hasSameExtendedValue(), clang::ASTContext::hasSameTemplateName(), clang::ASTContext::hasSameType(), clang::TemplateArgument::Integral, clang::QualType::isNull(), clang::TemplateArgument::isNull(), isSameDeclaration(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_begin(), clang::TemplateArgument::pack_end(), clang::TemplateArgument::pack_size(), clang::Stmt::Profile(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, clang::DeducedTemplateArgument::wasDeducedFromArrayBound(), and X.
Referenced by checkDeducedTemplateArguments(), DeduceNonTypeTemplateArgument(), DeduceTemplateArguments(), and DeduceTemplateArgumentsByTypeMatch().
CheckOriginalCallArgDeduction()
static Sema::TemplateDeductionResult CheckOriginalCallArgDeduction (Sema & S, TemplateDeductionInfo & Info, Sema::OriginalCallArg OriginalArg, QualType DeducedA) static
Check whether the deduced argument type for a call to a function template matches the actual argument type per C++ [temp.deduct.call]p4.
Definition at line 3406 of file SemaTemplateDeduction.cpp.
References clang::Sema::OriginalCallArg::ArgIdx, clang::sema::TemplateDeductionInfo::CallArgIndex, clang::Qualifiers::compatiblyIncludes(), clang::Sema::Context, clang::Sema::OriginalCallArg::DecomposedParam, clang::sema::TemplateDeductionInfo::FirstArg, clang::Type::getAs(), clang::Sema::getLangOpts(), clang::sema::TemplateDeductionInfo::getLocation(), clang::Qualifiers::getObjCLifetime(), clang::Type::getPointeeType(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasConst(), clang::ASTContext::hasSameUnqualifiedType(), clang::Type::isAnyPointerType(), clang::Sema::IsDerivedFrom(), clang::Sema::IsFunctionConversion(), clang::Type::isFunctionType(), clang::Type::isMemberPointerType(), clang::Sema::IsQualificationConversion(), clang::Type::isRecordType(), isSimpleTemplateIdType(), clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Sema::OriginalCallArg::OriginalArgType, clang::Sema::OriginalCallArg::OriginalParamType, clang::sema::TemplateDeductionInfo::SecondArg, clang::Qualifiers::setObjCLifetime(), clang::Sema::TDK_DeducedMismatch, clang::Sema::TDK_DeducedMismatchNested, and clang::Sema::TDK_Success.
Referenced by clang::Sema::DeduceAutoType(), and clang::Sema::FinishTemplateArgumentDeduction().
ConvertDeducedTemplateArgument()
static bool ConvertDeducedTemplateArgument (Sema & S, NamedDecl * Param, DeducedTemplateArgument Arg, NamedDecl * Template, TemplateDeductionInfo & Info, bool IsDeduced, SmallVectorImpl< TemplateArgument > & SugaredOutput, SmallVectorImpl< TemplateArgument > & CanonicalOutput) static
Convert the given deduced template argument and add it to the set of fully-converted template arguments.
Definition at line 2631 of file SemaTemplateDeduction.cpp.
References clang::Sema::CheckTemplateArgument(), clang::Sema::Context, clang::TemplateArgument::CreatePackCopy(), clang::Sema::CTAK_Deduced, clang::Sema::CTAK_DeducedFromArrayBound, clang::Sema::CTAK_Specified, clang::Sema::CurContext, clang::Sema::Diag(), clang::SourceRange::getEnd(), clang::TemplateArgument::getKind(), clang::Decl::getLocation(), clang::sema::TemplateDeductionInfo::getLocation(), clang::Decl::getSourceRange(), clang::Sema::getTrivialTemplateArgumentLoc(), clang::Sema::InstantiatingTemplate::isInvalid(), P, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::DeducedTemplateArgument::setDeducedFromArrayBound(), clang::Sema::SubstDecl(), clang::Sema::SubstType(), and clang::DeducedTemplateArgument::wasDeducedFromArrayBound().
Referenced by ConvertDeducedTemplateArguments().
ConvertDeducedTemplateArguments()
template<typename TemplateDeclT > static Sema::TemplateDeductionResult ConvertDeducedTemplateArguments (Sema & S, TemplateDeclT * Template, bool IsDeduced, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info, SmallVectorImpl< TemplateArgument > & SugaredBuilder, SmallVectorImpl< TemplateArgument > & CanonicalBuilder, LocalInstantiationScope * CurrentInstantiationScope = nullptr, unsigned NumAlreadyConverted = 0, bool PartialOverloading = false) static
Definition at line 2726 of file SemaTemplateDeduction.cpp.
References clang::Sema::CheckTemplateArgument(), clang::Sema::Context, ConvertDeducedTemplateArgument(), clang::TemplateArgumentList::CreateCopy(), clang::Sema::CTAK_Specified, clang::TemplateArgumentLoc::getArgument(), clang::ASTContext::getCanonicalTemplateArgument(), clang::Decl::getDeclContext(), clang::SourceRange::getEnd(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::DeclContext::getParent(), clang::TemplateDecl::getSourceRange(), clang::TemplateArgument::isNull(), makeTemplateParameter(), N, clang::sema::TemplateDeductionInfo::Param, clang::sema::TemplateDeductionInfo::reset(), clang::Result, clang::TemplateParameterList::size(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), clang::Sema::TDK_Incomplete, clang::Sema::TDK_SubstitutionFailure, and clang::Sema::TDK_Success.
Referenced by clang::Sema::FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), and FinishTemplateArgumentDeduction().
DeducedArgsNeedReplacement()
template<typename TemplateDeclT > static bool DeducedArgsNeedReplacement (TemplateDeclT * Template) static
Definition at line 2864 of file SemaTemplateDeduction.cpp.
Referenced by CheckDeducedArgumentConstraints().
DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl >()
template<> bool DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl > (ClassTemplatePartialSpecializationDecl * Spec)
Definition at line 2873 of file SemaTemplateDeduction.cpp.
References clang::ClassTemplateSpecializationDecl::isClassScopeExplicitSpecialization().
DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl >()
template<> bool DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl > (VarTemplatePartialSpecializationDecl * Spec)
Definition at line 2868 of file SemaTemplateDeduction.cpp.
References clang::VarTemplateSpecializationDecl::isClassScopeExplicitSpecialization().
DeduceFromInitializerList()
static Sema::TemplateDeductionResult DeduceFromInitializerList (Sema & S, TemplateParameterList * TemplateParams, QualType AdjustedParamType, InitListExpr * ILE, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, SmallVectorImpl< Sema::OriginalCallArg > & OriginalCallArgs, unsigned ArgIdx, unsigned TDF) static
Attempt template argument deduction from an initializer list deemed to be an argument in a function call.
Definition at line 3979 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, DeduceNonTypeTemplateArgument(), DeduceTemplateArgumentsFromCallArgument(), clang::ASTContext::getAsArrayType(), getDeducedParameterFromExpr(), clang::ASTContext::getIntWidth(), clang::InitListExpr::getNumInits(), clang::ASTContext::getSizeType(), clang::InitListExpr::inits(), clang::Type::isDependentType(), clang::Sema::isStdInitializerList(), clang::Result, and clang::Sema::TDK_Success.
Referenced by DeduceTemplateArgumentsFromCallArgument().
DeduceNonTypeTemplateArgument() [1/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, const DeducedTemplateArgument & NewDeduced, QualType ValueType, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter as the given deduced template argument.
All non-type template parameter deduction is funneled through here.
Definition at line 386 of file SemaTemplateDeduction.cpp.
References checkDeducedTemplateArguments(), clang::Sema::Context, DeduceTemplateArgumentsByTypeMatch(), clang::sema::TemplateDeductionInfo::FirstArg, clang::ASTContext::getAdjustedParameterType(), clang::sema::TemplateDeductionInfo::getDeducedDepth(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::Sema::getLangOpts(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::NonTypeTemplateParmDecl::isExpandedParameterPack(), clang::Type::isReferenceType(), clang::sema::TemplateDeductionInfo::Param, clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::TDF_SkipNonDependent, clang::Sema::TDK_Inconsistent, clang::Sema::TDK_Success, and clang::DeducedTemplateArgument::wasDeducedFromArrayBound().
Referenced by DeduceFromInitializerList(), DeduceNonTypeTemplateArgument(), DeduceNonTypeTemplateArgument(), DeduceNonTypeTemplateArgument(), DeduceNullPtrTemplateArgument(), DeduceTemplateArguments(), and DeduceTemplateArgumentsByTypeMatch().
DeduceNonTypeTemplateArgument() [2/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, const llvm::APSInt & Value, QualType ValueType, bool DeducedFromArrayBound, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given integral constant.
Definition at line 439 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, and DeduceNonTypeTemplateArgument().
DeduceNonTypeTemplateArgument() [3/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, Expr * Value, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given type- or value-dependent expression.
Returns
true if deduction succeeded, false otherwise.
Definition at line 474 of file SemaTemplateDeduction.cpp.
References DeduceNonTypeTemplateArgument(), and clang::Value::getType().
DeduceNonTypeTemplateArgument() [4/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, ValueDecl * D, QualType T, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given declaration.
Returns
true if deduction succeeded, false otherwise.
Definition at line 487 of file SemaTemplateDeduction.cpp.
References clang::cast(), DeduceNonTypeTemplateArgument(), and clang::Decl::getCanonicalDecl().
DeduceNullPtrTemplateArgument()
static Sema::TemplateDeductionResult DeduceNullPtrTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, QualType NullPtrType, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given null pointer template argument type.
Definition at line 453 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, DeduceNonTypeTemplateArgument(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getLocation(), clang::Value::getType(), clang::Sema::ImpCastExprToType(), clang::Type::isMemberPointerType(), and clang::ASTContext::NullPtrTy.
Referenced by DeduceTemplateArguments().
DeduceTemplateArguments() [1/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, ArrayRef< TemplateArgument > Ps, ArrayRef< TemplateArgument > As, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, bool NumberOfArgumentsMustMatch) static
Definition at line 2379 of file SemaTemplateDeduction.cpp.
References DeduceTemplateArguments(), hasPackExpansionBeforeEnd(), hasTemplateArgumentForDeduction(), P, clang::Result, clang::Sema::TDK_MiscellaneousDeductionFailure, and clang::Sema::TDK_Success.
Referenced by clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddTemplateConversionCandidate(), clang::Sema::AddTemplateOverloadCandidate(), DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateSpecArguments(), isAtLeastAsSpecializedAs(), clang::Sema::ResolveSingleFunctionTemplateSpecialization(), and clang::Sema::usesPartialOrExplicitSpecialization().
DeduceTemplateArguments() [2/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const QualType * Params, unsigned NumParams, const QualType * Args, unsigned NumArgs, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, unsigned TDF, bool PartialOrdering = false) static
Deduce the template arguments by comparing the list of parameter types to the list of argument types, as in the parameter-type-lists of function types (C++ [temp.deduct.type]p10).
Parameters
S The semantic analysis object within which we are deducing
TemplateParams The template parameters that we are deducing
Params The list of parameter types
NumParams The number of types in Params
Args The list of argument types
NumArgs The number of types in Args
Info information about the template argument deduction itself
Deduced the deduced template arguments
TDF bitwise OR of the TemplateDeductionFlags bits that describe how template argument deduction is performed.
PartialOrdering If true, we are performing template argument deduction for during partial ordering for a call (C++0x [temp.deduct.partial]).
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 1035 of file SemaTemplateDeduction.cpp.
References DeduceTemplateArgumentsByTypeMatch(), clang::QualType::getUnqualifiedType(), clang::PartialOrdering, clang::Result, clang::Sema::TDK_MiscellaneousDeductionFailure, and clang::Sema::TDK_Success.
DeduceTemplateArguments() [3/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const TemplateArgument & P, TemplateArgument A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 2243 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, clang::TemplateArgument::Declaration, DeduceNonTypeTemplateArgument(), DeduceNullPtrTemplateArgument(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), clang::TemplateArgument::Expression, clang::sema::TemplateDeductionInfo::FirstArg, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsType(), getDeducedParameterFromExpr(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNullPtrType(), clang::TemplateArgument::getPackExpansionPattern(), clang::TemplateArgument::getParamTypeForDecl(), hasSameExtendedValue(), clang::ASTContext::hasSameType(), clang::TemplateArgument::Integral, clang::TemplateArgument::isPackExpansion(), isSameDeclaration(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, P, clang::TemplateArgument::Pack, clang::sema::TemplateDeductionInfo::SecondArg, clang::Sema::TDK_NonDeducedMismatch, clang::Sema::TDK_Success, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
DeduceTemplateArguments() [4/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const TemplateArgumentList & ParamList, const TemplateArgumentList & ArgList, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 2460 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgumentList::asArray(), and DeduceTemplateArguments().
DeduceTemplateArguments() [5/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, TemplateName Param, TemplateName Arg, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 499 of file SemaTemplateDeduction.cpp.
References checkDeducedTemplateArguments(), clang::Sema::Context, clang::sema::TemplateDeductionInfo::FirstArg, clang::ASTContext::getCanonicalTemplateName(), clang::sema::TemplateDeductionInfo::getDeducedDepth(), clang::ASTContext::hasSameTemplateName(), clang::sema::TemplateDeductionInfo::Param, clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::Sema::TDK_Inconsistent, clang::Sema::TDK_NonDeducedMismatch, and clang::Sema::TDK_Success.
DeduceTemplateArgumentsByTypeMatch()
static Sema::TemplateDeductionResult DeduceTemplateArgumentsByTypeMatch (Sema & S, TemplateParameterList * TemplateParams, QualType P, QualType A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, unsigned TDF, bool PartialOrdering, bool DeducedFromArrayBound) static
Deduce the template arguments by comparing the parameter type and the argument type (C++ [temp.deduct.type]).
Parameters
S the semantic analysis object within which we are deducing
TemplateParams the template parameters that we are deducing
P the parameter type
A the argument type
Info information about the template argument deduction itself
Deduced the deduced template arguments
TDF bitwise OR of the TemplateDeductionFlags bits that describe how template argument deduction is performed.
PartialOrdering Whether we're performing template argument deduction in the context of partial ordering (C++0x [temp.deduct.partial]).
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 1378 of file SemaTemplateDeduction.cpp.
References clang::Sema::adjustMemberFunctionCC(), clang::ASTContext::BoolTy, clang::cast(), checkDeducedTemplateArguments(), clang::Qualifiers::compatiblyIncludes(), clang::Sema::Context, clang::CT_Can, clang::CT_Cannot, clang::CT_Dependent, DeduceNonTypeTemplateArgument(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateBases(), DeduceTemplateSpecArguments(), clang::sema::TemplateDeductionInfo::FirstArg, clang::QualType::getAddressSpace(), clang::Type::getAs(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getAsDependentSizedArrayType(), clang::ASTContext::getAsIncompleteArrayType(), getCanonicalRD(), clang::QualType::getCanonicalType(), clang::Type::getCanonicalTypeInternal(), clang::DependentSizedMatrixType::getColumnExpr(), clang::Qualifiers::getCVRQualifiers(), clang::QualType::getCVRQualifiers(), clang::sema::TemplateDeductionInfo::getDeducedDepth(), getDeducedParameterFromExpr(), clang::NonTypeTemplateParmDecl::getDepth(), clang::MatrixType::getElementType(), clang::Expr::getIntegerConstantExpr(), clang::Sema::getLangOpts(), clang::sema::TemplateDeductionInfo::getLocation(), clang::ConstantMatrixType::getNumColumns(), clang::ConstantMatrixType::getNumRows(), clang::TemplateParameterList::getParam(), clang::PointerType::getPointeeType(), clang::ReferenceType::getPointeeType(), clang::Type::getPointeeType(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::DependentSizedMatrixType::getRowExpr(), clang::ASTContext::getSizeType(), clang::ASTContext::getTypeSize(), clang::ASTContext::getUnqualifiedArrayType(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasAddressSpace(), hasInconsistentOrSupersetQualifiersOf(), clang::Qualifiers::hasNonTrivialObjCLifetime(), clang::Qualifiers::hasObjCGCAttr(), clang::Qualifiers::hasObjCLifetime(), clang::ASTContext::hasSameType(), clang::ASTContext::hasSameUnqualifiedType(), clang::ASTContext::IntTy, clang::Type::isArrayType(), clang::Sema::isCompleteType(), clang::Type::isDependentType(), isForwardingReference(), clang::Type::isFunctionType(), clang::Type::isLValueReferenceType(), clang::Type::isObjCLifetimeType(), clang::Type::isPlaceholderType(), IsPossiblyOpaquelyQualifiedType(), clang::Type::isRecordType(), clang::Sema::isSameOrCompatibleFunctionType(), clang::Qualifiers::isStrictSupersetOf(), clang::isTargetAddressSpace(), clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_Strong, clang::ASTContext::OverloadTy, P, clang::sema::TemplateDeductionInfo::Param, clang::PartialOrdering, clang::Qualifiers::removeAddressSpace(), clang::ASTContext::removeAddrSpaceQualType(), clang::Qualifiers::removeCVRQualifiers(), clang::Qualifiers::removeObjCGCAttr(), clang::Qualifiers::removeObjCLifetime(), clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::Qualifiers::setCVRQualifiers(), clang::Qualifiers::setObjCLifetime(), clang::TDF_AllowCompatibleFunctionType, clang::TDF_ArgWithReferenceType, clang::TDF_DerivedClass, clang::TDF_IgnoreQualifiers, clang::TDF_ParamWithReferenceType, clang::TDF_SkipNonDependent, clang::TDF_TopLevelParameterTypeList, clang::Sema::TDK_Inconsistent, clang::Sema::TDK_Invalid, clang::Sema::TDK_NonDeducedMismatch, clang::Sema::TDK_Success, clang::Sema::TDK_Underqualified, clang::toTargetAddressSpace(), clang::ASTContext::UnsignedIntTy, and clang::Qualifiers::withoutObjCLifetime().
Referenced by DeduceNonTypeTemplateArgument(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateArgumentsFromCallArgument(), isAtLeastAsSpecializedAs(), isAtLeastAsSpecializedAs(), and ResolveOverloadForDeduction().
DeduceTemplateArgumentsFromCallArgument()
static Sema::TemplateDeductionResult DeduceTemplateArgumentsFromCallArgument (Sema & S, TemplateParameterList * TemplateParams, unsigned FirstInnerIndex, QualType ParamType, Expr * Arg, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, SmallVectorImpl< Sema::OriginalCallArg > & OriginalCallArgs, bool DecomposedParam, unsigned ArgIdx, unsigned TDF, TemplateSpecCandidateSet * FailedTSC = nullptr) static
Perform template argument deduction per [temp.deduct.call] for a single parameter / argument pair.
Definition at line 4046 of file SemaTemplateDeduction.cpp.
References AdjustFunctionParmAndArgTypesForDeduction(), DeduceFromInitializerList(), DeduceTemplateArgumentsByTypeMatch(), clang::Expr::getType(), and clang::Sema::TDK_Success.
Referenced by clang::Sema::DeduceAutoType(), DeduceFromInitializerList(), and clang::Sema::DeduceTemplateArguments().
DeduceTemplateBases()
static Sema::TemplateDeductionResult DeduceTemplateBases (Sema & S, const CXXRecordDecl * RD, TemplateParameterList * TemplateParams, QualType P, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Attempt to deduce the template arguments by checking the base types according to (C++20 [temp.deduct.call] p4b3.
Parameters
S the semantic analysis object within which we are deducing.
RD the top level record object we are deducing against.
TemplateParams the template parameters that we are deducing.
P the template specialization parameter type.
Info information about the template argument deduction itself.
Deduced the deduced template arguments.
Returns
the result of template argument deduction with the bases. "invalid" means no matches, "success" found a single item, and the "MiscellaneousDeductionFailure" result happens when the match is ambiguous.
Definition at line 1259 of file SemaTemplateDeduction.cpp.
References clang::CXXRecordDecl::bases(), DeduceTemplateSpecArguments(), clang::sema::TemplateDeductionInfo::ForBase, getCanonicalRD(), P, clang::Sema::TDK_Invalid, clang::Sema::TDK_MiscellaneousDeductionFailure, clang::Sema::TDK_Success, and Visited.
Referenced by DeduceTemplateArgumentsByTypeMatch().
DeduceTemplateSpecArguments()
static Sema::TemplateDeductionResult DeduceTemplateSpecArguments (Sema & S, TemplateParameterList * TemplateParams, const QualType P, QualType A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the template arguments by comparing the template parameter type (which is a template-id) with the template argument type.
Parameters
S the Sema
TemplateParams the template parameters that we are deducing
P the parameter type
A the argument type
Info information about the template argument deduction itself
Deduced the deduced template arguments
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 562 of file SemaTemplateDeduction.cpp.
References clang::Type::castAs(), DeduceTemplateArguments(), clang::sema::TemplateDeductionInfo::FirstArg, clang::Type::getAs(), clang::TemplateName::getAsTemplateDecl(), clang::QualType::getCanonicalType(), clang::TemplateDecl::isTypeAlias(), P, clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::Sema::TDK_NonDeducedMismatch, and clang::Sema::TDK_Success.
Referenced by DeduceTemplateArgumentsByTypeMatch(), and DeduceTemplateBases().
FinishTemplateArgumentDeduction() [1/2]
template<typename T > static std::enable_if_t< IsPartialSpecialization< T >::value, Sema::TemplateDeductionResult > FinishTemplateArgumentDeduction (Sema & S, T * Partial, bool IsPartialOrdering, const TemplateArgumentList & TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info) static
Complete template argument deduction for a partial specialization.
Definition at line 2920 of file SemaTemplateDeduction.cpp.
References clang::ASTTemplateArgumentListInfo::arguments(), CheckDeducedArgumentConstraints(), clang::Sema::CheckTemplateArgumentList(), clang::Sema::Context, ConvertDeducedTemplateArguments(), clang::TemplateArgumentList::CreateCopy(), clang::sema::TemplateDeductionInfo::FirstArg, getAsDeclContextOrEnclosing(), clang::TemplateParameterList::getParam(), clang::Sema::SFINAETrap::hasErrorOccurred(), isSameTemplateArg(), clang::ASTTemplateArgumentListInfo::LAngleLoc, makeTemplateParameter(), clang::sema::TemplateDeductionInfo::Param, clang::ASTTemplateArgumentListInfo::RAngleLoc, clang::sema::TemplateDeductionInfo::reset(), clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::TemplateArgumentListInfo::size(), clang::TemplateParameterList::size(), clang::Sema::SubstTemplateArguments(), clang::Sema::TDK_ConstraintsNotSatisfied, clang::Sema::TDK_NonDeducedMismatch, clang::Sema::TDK_SubstitutionFailure, clang::Sema::TDK_Success, clang::Sema::Unevaluated, and clang::Unevaluated.
FinishTemplateArgumentDeduction() [2/2]
static Sema::TemplateDeductionResult FinishTemplateArgumentDeduction (Sema & S, TemplateDecl * Template, bool PartialOrdering, const TemplateArgumentList & TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info) static
Complete template argument deduction for a class or variable template, when partial ordering against a partial specialization.
Definition at line 3013 of file SemaTemplateDeduction.cpp.
References CheckDeducedArgumentConstraints(), clang::Sema::Context, ConvertDeducedTemplateArguments(), clang::sema::TemplateDeductionInfo::FirstArg, getAsDeclContextOrEnclosing(), clang::TemplateParameterList::getParam(), clang::TemplateDecl::getTemplateParameters(), clang::Sema::SFINAETrap::hasErrorOccurred(), isSameTemplateArg(), makeTemplateParameter(), clang::sema::TemplateDeductionInfo::Param, clang::PartialOrdering, clang::Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::TemplateParameterList::size(), clang::Sema::TDK_NonDeducedMismatch, clang::Sema::TDK_SubstitutionFailure, clang::Sema::TDK_Success, clang::Sema::Unevaluated, and clang::Unevaluated.
getAsDeclContextOrEnclosing()
static DeclContext * getAsDeclContextOrEnclosing (Decl * D) static
Definition at line 2846 of file SemaTemplateDeduction.cpp.
References clang::Decl::getDeclContext().
Referenced by FinishTemplateArgumentDeduction(), and FinishTemplateArgumentDeduction().
getCanonicalRD()
static CXXRecordDecl * getCanonicalRD (QualType T) static
Definition at line 1235 of file SemaTemplateDeduction.cpp.
References clang::cast().
Referenced by DeduceTemplateArgumentsByTypeMatch(), and DeduceTemplateBases().
getDeducedParameterFromExpr() [1/2]
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (const Expr * E, unsigned Depth) static
If the given expression is of a form that permits the deduction of a non-type template parameter, return the declaration of that non-type template parameter.
Definition at line 163 of file SemaTemplateDeduction.cpp.
Referenced by DeduceFromInitializerList(), DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), getDeducedParameterFromExpr(), and MarkUsedTemplateParameters().
getDeducedParameterFromExpr() [2/2]
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (TemplateDeductionInfo & Info, Expr * E) static
Definition at line 193 of file SemaTemplateDeduction.cpp.
References clang::sema::TemplateDeductionInfo::getDeducedDepth(), and getDeducedParameterFromExpr().
getFirstInnerIndex()
static unsigned getFirstInnerIndex (FunctionTemplateDecl * FTD) static
Get the index of the first template parameter that was originally from the innermost template-parameter-list.
This is 0 except when we concatenate the template parameter lists of a class template and a constructor template when forming an implicit deduction guide.
Definition at line 1213 of file SemaTemplateDeduction.cpp.
References clang::FunctionTemplateDecl::getTemplatedDecl().
Referenced by clang::Sema::DeduceTemplateArguments().
getMoreSpecialized()
template<typename TemplateLikeDecl , typename PrimaryDel > static TemplateLikeDecl * getMoreSpecialized (Sema & S, QualType T1, QualType T2, TemplateLikeDecl * P1, PrimaryDel * P2, TemplateDeductionInfo & Info) static
Returns the more specialized template specialization between T1/P1 and T2/P2.
If IsMoreSpecialThanPrimaryCheck is true, T1/P1 is the partial specialization and T2/P2 is the primary template.
otherwise, both T1/P1 and T2/P2 are the partial specialization.
Parameters
T1 the type of the first template partial specialization
T2 if IsMoreSpecialThanPrimaryCheck is true, the type of the second template partial specialization; otherwise, the type of the primary template.
P1 the first template partial specialization
P2 if IsMoreSpecialThanPrimaryCheck is true, the second template partial specialization; otherwise, the primary template.
Returns
- If IsMoreSpecialThanPrimaryCheck is true, returns P1 if P1 is more specialized, returns nullptr if P1 is not more specialized.
otherwise, returns the more specialized template partial specialization. If neither partial specialization is more specialized, returns NULL.
Definition at line 5660 of file SemaTemplateDeduction.cpp.
References clang::cast(), clang::Sema::Context, clang::Sema::getASTContext(), clang::TemplateArgument::getKind(), clang::ASTContext::getLangOpts(), clang::Sema::IsAtLeastAsConstrained(), isAtLeastAsSpecializedAs(), clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::pack_size(), clang::TemplateParameterList::size(), clang::Sema::TemplateParameterListsAreEqual(), and clang::Sema::TPL_TemplateParamsEquivalent.
Referenced by clang::Sema::getMoreSpecializedPartialSpecialization(), clang::Sema::getMoreSpecializedPartialSpecialization(), clang::Sema::isMoreSpecializedThanPrimary(), and clang::Sema::isMoreSpecializedThanPrimary().
getPackIndexForParam()
static unsigned getPackIndexForParam (Sema & S, FunctionTemplateDecl * FunctionTemplate, const MultiLevelTemplateArgumentList & Args, unsigned ParamIdx) static
Find the pack index for a particular parameter index in an instantiation of a function template with specific arguments.
Returns
The pack index for whichever pack produced this parameter, or -1 if this was not produced by a parameter. Intended to be used as the ArgumentPackSubstitutionIndex for further substitutions.
Definition at line 3527 of file SemaTemplateDeduction.cpp.
References clang::Sema::getNumArgumentsInExpansion(), clang::FunctionTemplateDecl::getTemplatedDecl(), and clang::FunctionDecl::parameters().
Referenced by clang::Sema::FinishTemplateArgumentDeduction().
GetTypeOfFunction()
static QualType GetTypeOfFunction (Sema & S, const OverloadExpr::FindResult & R, FunctionDecl * Fn) static
Gets the type of a function for template-argument-deducton purposes when it's considered as part of an overload set.
Definition at line 3740 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, clang::Sema::DeduceReturnType(), clang::OverloadExpr::FindResult::Expression, clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::ASTContext::getMemberPointerType(), clang::ASTContext::getPointerType(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), clang::ASTContext::getTypeDeclType(), clang::QualType::getTypePtr(), clang::OverloadExpr::FindResult::HasFormOfMemberPointer, clang::OverloadExpr::FindResult::IsAddressOfOperand, and clang::Type::isUndeducedType().
Referenced by ResolveOverloadForDeduction().
hasDeducibleTemplateParameters()
bool hasDeducibleTemplateParameters (Sema & S, FunctionTemplateDecl * FunctionTemplate, QualType T) static
Definition at line 6388 of file SemaTemplateDeduction.cpp.
References clang::Sema::Context, clang::TemplateParameterList::getDepth(), clang::TemplateDecl::getTemplateParameters(), MarkUsedTemplateParameters(), and clang::TemplateParameterList::size().
Referenced by clang::Sema::DeduceTemplateArguments().
hasInconsistentOrSupersetQualifiersOf()
static bool hasInconsistentOrSupersetQualifiersOf (QualType ParamType, QualType ArgType) static
Determine whether the parameter has qualifiers that the argument lacks.
Put another way, determine whether there is no way to add a deduced set of qualifiers to the ParamType that would result in its qualifiers matching those of the ArgType.
Definition at line 1157 of file SemaTemplateDeduction.cpp.
References clang::Qualifiers::getAddressSpace(), clang::Qualifiers::getCVRQualifiers(), clang::Qualifiers::getObjCGCAttr(), clang::Qualifiers::getObjCLifetime(), clang::QualType::getQualifiers(), clang::Qualifiers::hasAddressSpace(), clang::Qualifiers::hasObjCGCAttr(), and clang::Qualifiers::hasObjCLifetime().
Referenced by DeduceTemplateArgumentsByTypeMatch().
hasPackExpansionBeforeEnd()
static bool hasPackExpansionBeforeEnd (ArrayRef< TemplateArgument > Args) static
Determine whether the given set of template arguments has a pack expansion that is not the last template argument.
Definition at line 2360 of file SemaTemplateDeduction.cpp.
References hasPackExpansionBeforeEnd(), and clang::TemplateArgument::Pack.
Referenced by DeduceTemplateArguments(), hasPackExpansionBeforeEnd(), clang::Sema::MarkUsedTemplateParameters(), and MarkUsedTemplateParameters().
hasSameExtendedValue()
static bool hasSameExtendedValue (llvm::APSInt X, llvm::APSInt Y) static
Compare two APSInts, extending and switching the sign as necessary to compare their values regardless of underlying type.
Definition at line 117 of file SemaTemplateDeduction.cpp.
References X.
Referenced by checkDeducedTemplateArguments(), DeduceTemplateArguments(), and isSameTemplateArg().
hasTemplateArgumentForDeduction()
static bool hasTemplateArgumentForDeduction (ArrayRef< TemplateArgument > & Args, unsigned & ArgIdx) static
Determine whether there is a template argument to be used for deduction.
This routine "expands" argument packs in-place, overriding its input parameters so that Args[ArgIdx] will be the available template argument.
Returns
true if there is another template argument (which will be at Args[ArgIdx]), false otherwise.
Definition at line 2343 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::getKind(), clang::TemplateArgument::Pack, and clang::TemplateArgument::pack_elements().
Referenced by DeduceTemplateArguments().
isAtLeastAsSpecializedAs() [1/2]
template<typename TemplateLikeDecl > static bool isAtLeastAsSpecializedAs (Sema & S, QualType T1, QualType T2, TemplateLikeDecl * P2, TemplateDeductionInfo & Info) static
Determine whether one partial specialization, P1, is at least as specialized than another, P2.
Template Parameters
TemplateLikeDecl The kind of P2, which must be a TemplateDecl or {Class,Var}TemplatePartialSpecializationDecl.
Parameters
T1 The injected-class-name of P1 (faked for a variable template).
T2 The injected-class-name of P2 (faked for a variable template).
Definition at line 5518 of file SemaTemplateDeduction.cpp.
References clang::cast(), DeduceTemplateArgumentsByTypeMatch(), clang::sema::TemplateDeductionInfo::getLocation(), clang::Sema::InstantiatingTemplate::isInvalid(), clang::Sema::runWithSufficientStackSpace(), and clang::TDF_None.
isAtLeastAsSpecializedAs() [2/2]
static bool isAtLeastAsSpecializedAs (Sema & S, SourceLocation Loc, FunctionTemplateDecl * FT1, FunctionTemplateDecl * FT2, TemplatePartialOrderingContext TPOC, unsigned NumCallArguments1, bool Reversed) static
Determine whether the function template FT1 is at least as specialized as FT2.
Definition at line 5094 of file SemaTemplateDeduction.cpp.
References AddImplicitObjectParameterType(), clang::Sema::Context, DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), clang::Type::getAs(), clang::TemplateParameterList::getDepth(), clang::FunctionType::getReturnType(), clang::FunctionTemplateDecl::getTemplatedDecl(), clang::TemplateDecl::getTemplateParameters(), clang::ValueDecl::getType(), clang::CXXMethodDecl::isStatic(), MarkUsedTemplateParameters(), N, clang::FunctionProtoType::param_type_begin(), clang::FunctionProtoType::param_type_end(), clang::Reversed, clang::TemplateParameterList::size(), clang::TDF_None, clang::TPOC_Call, clang::TPOC_Conversion, and clang::TPOC_Other.
Referenced by getMoreSpecialized(), clang::Sema::getMoreSpecializedTemplate(), and clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs().
isForwardingReference()
static bool isForwardingReference (QualType Param, unsigned FirstInnerIndex) static
Determine whether a type denotes a forwarding reference.
Definition at line 1221 of file SemaTemplateDeduction.cpp.
Referenced by AdjustFunctionParmAndArgTypesForDeduction(), and DeduceTemplateArgumentsByTypeMatch().
IsPossiblyOpaquelyQualifiedType()
static bool IsPossiblyOpaquelyQualifiedType (QualType T) static
Determines whether the given type is an opaque type that might be more qualified when instantiated.
Definition at line 657 of file SemaTemplateDeduction.cpp.
References IsPossiblyOpaquelyQualifiedTypeInternal().
Referenced by DeduceTemplateArgumentsByTypeMatch().
IsPossiblyOpaquelyQualifiedTypeInternal()
static bool IsPossiblyOpaquelyQualifiedTypeInternal (const Type * T) static
Definition at line 631 of file SemaTemplateDeduction.cpp.
References IsPossiblyOpaquelyQualifiedTypeInternal().
Referenced by IsPossiblyOpaquelyQualifiedType(), and IsPossiblyOpaquelyQualifiedTypeInternal().
isSameDeclaration()
static bool isSameDeclaration (Decl * X, Decl * Y) static
Determine whether two declaration pointers refer to the same declaration.
Definition at line 199 of file SemaTemplateDeduction.cpp.
References clang::Decl::getCanonicalDecl(), and X.
Referenced by checkDeducedTemplateArguments(), DeduceTemplateArguments(), and isSameTemplateArg().
isSameTemplate()
static bool isSameTemplate (TemplateDecl * T1, TemplateDecl * T2) static
Determine if the two templates are equivalent.
Definition at line 5400 of file SemaTemplateDeduction.cpp.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::getMostSpecialized().
isSameTemplateArg()
static bool isSameTemplateArg (ASTContext & Context, TemplateArgument X, const TemplateArgument & Y, bool PartialOrdering, bool PackExpansionMatchesPack = false) static
Determine whether two template arguments are the same.
Definition at line 2471 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateName::getAsVoidPointer(), clang::ASTContext::getCanonicalTemplateName(), clang::ASTContext::getCanonicalType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNullPtrType(), hasSameExtendedValue(), clang::ASTContext::hasSameType(), clang::TemplateArgument::Integral, clang::TemplateArgument::isPackExpansion(), isSameDeclaration(), isSameTemplateArg(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::pack_size(), clang::PartialOrdering, clang::Stmt::Profile(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, and X.
Referenced by FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), and isSameTemplateArg().
isSimpleTemplateIdType()
static bool isSimpleTemplateIdType (QualType T) static
Determine whether the given type T is a simple-template-id type.
Definition at line 3162 of file SemaTemplateDeduction.cpp.
Referenced by AdjustFunctionParmAndArgTypesForDeduction(), and CheckOriginalCallArgDeduction().
makeTemplateParameter()
static TemplateParameter makeTemplateParameter (Decl * D) static
Helper function to build a TemplateParameter when we don't know its type statically.
Definition at line 664 of file SemaTemplateDeduction.cpp.
Referenced by ConvertDeducedTemplateArguments(), FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), and clang::Sema::SubstituteExplicitTemplateArguments().
MarkUsedTemplateParameters() [1/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, const Expr * E, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given expression.
Definition at line 5923 of file SemaTemplateDeduction.cpp.
References getDeducedParameterFromExpr(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::ASTContext::getLangOpts(), clang::ValueDecl::getType(), MarkUsedTemplateParameters(), and Used.
MarkUsedTemplateParameters() [2/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, const TemplateArgument & TemplateArg, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by this template argument.
Definition at line 6292 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::Integral, MarkUsedTemplateParameters(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, P, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArg, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, and Used.
Referenced by hasDeducibleTemplateParameters(), isAtLeastAsSpecializedAs(), MarkUsedTemplateParameters(), MarkUsedTemplateParameters(), MarkUsedTemplateParameters(), MarkUsedTemplateParameters(), and MarkUsedTemplateParameters().
MarkUsedTemplateParameters() [3/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, NestedNameSpecifier * NNS, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given nested name specifier.
Definition at line 5954 of file SemaTemplateDeduction.cpp.
References clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getPrefix(), MarkUsedTemplateParameters(), and Used.
MarkUsedTemplateParameters() [4/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, QualType T, bool OnlyDeduced, unsigned Level, llvm::SmallBitVector & Deduced) static
Mark the template parameters that are used by the given type.
Definition at line 5996 of file SemaTemplateDeduction.cpp.
References clang::cast(), clang::DependentAddressSpaceType::getAddrSpaceExpr(), clang::Type::getAs(), clang::ASTContext::getCanonicalType(), clang::MemberPointerType::getClass(), clang::DependentSizedMatrixType::getColumnExpr(), clang::DependentSizedExtVectorType::getElementType(), clang::MatrixType::getElementType(), clang::FunctionProtoType::getNoexceptExpr(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::getParamType(), clang::DependentAddressSpaceType::getPointeeType(), clang::MemberPointerType::getPointeeType(), clang::FunctionType::getReturnType(), clang::DependentSizedMatrixType::getRowExpr(), clang::DependentSizedExtVectorType::getSizeExpr(), getUnderlyingType(), hasPackExpansionBeforeEnd(), MarkUsedTemplateParameters(), N, and Used.
MarkUsedTemplateParameters() [5/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, TemplateName Name, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given template name.
Definition at line 5971 of file SemaTemplateDeduction.cpp.
References MarkUsedTemplateParameters(), and Used.
ResolveOverloadForDeduction()
static QualType ResolveOverloadForDeduction (Sema & S, TemplateParameterList * TemplateParams, Expr * Arg, QualType ParamType, bool ParamWasReference, TemplateSpecCandidateSet * FailedTSC = nullptr) static
Apply the deduction rules for overload sets.
Returns
the null type if this argument should be treated as an undeduced context
Definition at line 3767 of file SemaTemplateDeduction.cpp.
References clang::cast(), clang::Sema::Context, clang::OverloadExpr::copyTemplateArgumentsInto(), clang::OverloadExpr::decls_begin(), clang::OverloadExpr::decls_end(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), clang::OverloadExpr::FindResult::Expression, clang::OverloadExpr::find(), clang::OverloadExpr::getNameLoc(), clang::ASTContext::getPointerType(), GetTypeOfFunction(), clang::NamedDecl::getUnderlyingDecl(), clang::OverloadExpr::hasExplicitTemplateArgs(), clang::OverloadExpr::FindResult::IsAddressOfOperand, clang::Type::isFunctionPointerType(), clang::Type::isFunctionType(), clang::Type::isMemberFunctionPointerType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::Sema::resolveAddressOfSingleOverloadCandidate(), clang::Sema::ResolveSingleFunctionTemplateSpecialization(), clang::Result, clang::TemplateParameterList::size(), clang::Specialization, clang::TDF_IgnoreQualifiers, and clang::TDF_ParamWithReferenceType.
Referenced by AdjustFunctionParmAndArgTypesForDeduction().