clang: lib/StaticAnalyzer/Core/SimpleSValBuilder.cpp File Reference
SimpleSValBuilder.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/APSIntType.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SValVisitor.h"
#include <optional>
Functions
static bool isNegationValuePreserving (const llvm::APSInt &Value, APSIntType ResultType)
static bool isInRelation (BinaryOperator::Opcode Rel, SymbolRef Sym, llvm::APSInt Bound, ProgramStateRef State)
static bool isWithinConstantOverflowBounds (SymbolRef Sym, ProgramStateRef State)
static bool isWithinConstantOverflowBounds (llvm::APSInt I)
static std::pair< SymbolRef, llvm::APSInt > decomposeSymbol (SymbolRef Sym, BasicValueFactory &BV)
static NonLoc doRearrangeUnchecked (ProgramStateRef State, BinaryOperator::Opcode Op, SymbolRef LSym, llvm::APSInt LInt, SymbolRef RSym, llvm::APSInt RInt)
static bool shouldRearrange (ProgramStateRef State, BinaryOperator::Opcode Op, SymbolRef Sym, llvm::APSInt Int, QualType Ty)
static std::optional< NonLoc > tryRearrange (ProgramStateRef State, BinaryOperator::Opcode Op, NonLoc Lhs, NonLoc Rhs, QualType ResultTy)
static SVal evalBinOpFieldRegionFieldRegion (const FieldRegion *LeftFR, const FieldRegion *RightFR, BinaryOperator::Opcode op, QualType resultTy, SimpleSValBuilder &SVB)
static void assertEqualBitWidths (ProgramStateRef State, Loc RhsLoc, Loc LhsLoc)
Function Documentation
assertEqualBitWidths()
static void assertEqualBitWidths (ProgramStateRef State, Loc RhsLoc, Loc LhsLoc) static
Definition at line 747 of file SimpleSValBuilder.cpp.
References clang::ento::SVal::getSubKind(), clang::ento::SVal::getType(), clang::ASTContext::getTypeSize(), and clang::QualType::isNull().
decomposeSymbol()
static std::pair< SymbolRef, llvm::APSInt > decomposeSymbol (SymbolRef Sym, BasicValueFactory & BV) static
Definition at line 263 of file SimpleSValBuilder.cpp.
References clang::ento::SymExpr::getType(), and clang::BinaryOperator::isAdditiveOp().
Referenced by tryRearrange().
doRearrangeUnchecked()
static NonLoc doRearrangeUnchecked (ProgramStateRef State, BinaryOperator::Opcode Op, SymbolRef LSym, llvm::APSInt LInt, SymbolRef RSym, llvm::APSInt RInt) static
Definition at line 278 of file SimpleSValBuilder.cpp.
References clang::ento::SVal::castAs(), clang::ento::SValBuilder::evalBinOpNN(), clang::ento::BasicValueFactory::getAPSIntType(), clang::ento::SValBuilder::getBasicValueFactory(), clang::ento::SValBuilder::getConditionType(), clang::ento::SValBuilder::getStateManager(), clang::ento::ProgramStateManager::getSValBuilder(), clang::ento::SValBuilder::getSymbolManager(), clang::ento::SymbolManager::getSymIntExpr(), clang::ento::SymbolManager::getSymSymExpr(), clang::ento::SymExpr::getType(), clang::BinaryOperator::isAdditiveOp(), clang::BinaryOperator::isComparisonOp(), and clang::BinaryOperator::reverseComparisonOp().
Referenced by tryRearrange().
evalBinOpFieldRegionFieldRegion()
static SVal evalBinOpFieldRegionFieldRegion (const FieldRegion * LeftFR, const FieldRegion * RightFR, BinaryOperator::Opcode op, QualType resultTy, SimpleSValBuilder & SVB) static
Definition at line 694 of file SimpleSValBuilder.cpp.
References clang::RecordDecl::fields(), clang::ento::FieldRegion::getDecl(), clang::FieldDecl::getParent(), clang::ento::SubRegion::getSuperRegion(), and clang::BinaryOperator::isComparisonOp().
isInRelation()
static bool isInRelation (BinaryOperator::Opcode Rel, SymbolRef Sym, llvm::APSInt Bound, ProgramStateRef State) static
Definition at line 220 of file SimpleSValBuilder.cpp.
References clang::ento::SValBuilder::evalBinOpNN(), clang::ento::SValBuilder::getConditionType(), clang::ento::SValBuilder::getStateManager(), and clang::ento::ProgramStateManager::getSValBuilder().
Referenced by isWithinConstantOverflowBounds().
isNegationValuePreserving()
static bool isNegationValuePreserving (const llvm::APSInt & Value, APSIntType ResultType) static
Definition at line 94 of file SimpleSValBuilder.cpp.
References clang::ento::APSIntType::getBitWidth(), and clang::ento::APSIntType::isUnsigned().
isWithinConstantOverflowBounds() [1/2]
static bool isWithinConstantOverflowBounds (llvm::APSInt I) static
Definition at line 253 of file SimpleSValBuilder.cpp.
References clang::ento::APSIntType::getMaxValue(), clang::ento::APSIntType::getValue(), and clang::ento::APSIntType::isUnsigned().
isWithinConstantOverflowBounds() [2/2]
static bool isWithinConstantOverflowBounds (SymbolRef Sym, ProgramStateRef State) static
Definition at line 237 of file SimpleSValBuilder.cpp.
References clang::ento::BasicValueFactory::getAPSIntType(), clang::ento::SValBuilder::getBasicValueFactory(), clang::ento::APSIntType::getMaxValue(), clang::ento::SValBuilder::getStateManager(), clang::ento::ProgramStateManager::getSValBuilder(), clang::ento::SymExpr::getType(), clang::ento::APSIntType::getValue(), and isInRelation().
Referenced by shouldRearrange().
shouldRearrange()
static bool shouldRearrange (ProgramStateRef State, BinaryOperator::Opcode Op, SymbolRef Sym, llvm::APSInt Int, QualType Ty) static
Definition at line 344 of file SimpleSValBuilder.cpp.
References clang::ento::SymExpr::getType(), clang::BinaryOperator::isComparisonOp(), and isWithinConstantOverflowBounds().
Referenced by tryRearrange().
tryRearrange()
static std::optional< NonLoc > tryRearrange (ProgramStateRef State, BinaryOperator::Opcode Op, NonLoc Lhs, NonLoc Rhs, QualType ResultTy) static
Definition at line 352 of file SimpleSValBuilder.cpp.
References decomposeSymbol(), doRearrangeUnchecked(), clang::ento::SValBuilder::getAnalyzerOptions(), clang::ento::SVal::getAsSymbol(), clang::ento::SValBuilder::getConditionType(), clang::ento::ProgramStateManager::getSValBuilder(), clang::ento::SymExpr::getType(), clang::BinaryOperator::isAdditiveOp(), clang::BinaryOperator::isComparisonOp(), clang::QualType::isNull(), clang::Type::isSignedIntegerOrEnumerationType(), and shouldRearrange().