clang: lib/Tooling/Transformer/SourceCode.cpp File Reference
SourceCode.cpp File Reference
#include "clang/Tooling/Transformer/SourceCode.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Comment.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/Lexer.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include <set>
Functions
static llvm::Error validateRange (const CharSourceRange &Range, const SourceManager &SM, bool AllowSystemHeaders)
static bool spelledInMacroDefinition (SourceLocation Loc, const SourceManager &SM)
static CharSourceRange getRange (const CharSourceRange &EditRange, const SourceManager &SM, const LangOptions &LangOpts, bool IncludeMacroExpansion)
static bool startsWithNewline (const SourceManager &SM, const Token &Tok)
static bool contains (const std::set< tok::TokenKind > &Terminators, const Token &Tok)
static SourceLocation getEntityEndLoc (const SourceManager &SM, SourceLocation EntityLast, const std::set< tok::TokenKind > &Terminators, const LangOptions &LangOpts)
static std::set< tok::TokenKind > getTerminators (const Decl &D)
static SourceLocation skipWhitespaceAndNewline (const SourceManager &SM, SourceLocation Loc, const LangOptions &LangOpts)
static bool atOrBeforeSeparation (const SourceManager &SM, SourceLocation Loc, const LangOptions &LangOpts)
Function Documentation
atOrBeforeSeparation()
static bool atOrBeforeSeparation (const SourceManager & SM, SourceLocation Loc, const LangOptions & LangOpts) static
Definition at line 327 of file SourceCode.cpp.
References clang::Token::getKind(), clang::Lexer::getRawToken(), clang::Invalid, clang::isVerticalWhitespace(), clang::isWhitespace(), SM, and Tok.
Referenced by clang::tooling::getAssociatedRange().
contains()
static bool contains (const std::set< tok::TokenKind > & Terminators, const Token & Tok) static
Definition at line 152 of file SourceCode.cpp.
References clang::Token::getKind(), and Tok.
Referenced by getEntityEndLoc().
getEntityEndLoc()
static SourceLocation getEntityEndLoc (const SourceManager & SM, SourceLocation EntityLast, const std::set< tok::TokenKind > & Terminators, const LangOptions & LangOpts) static
Definition at line 166 of file SourceCode.cpp.
References contains(), clang::File, clang::CharSourceRange::getEnd(), clang::Token::getEndLoc(), clang::Token::getKind(), clang::Invalid, clang::SourceLocation::isMacroID(), clang::SourceLocation::isValid(), clang::Lexer::LexFromRawLexer(), clang::Lexer::SetKeepWhitespaceMode(), SM, startsWithNewline(), and Tok.
Referenced by clang::tooling::getAssociatedRange().
getRange()
static CharSourceRange getRange (const CharSourceRange & EditRange, const SourceManager & SM, const LangOptions & LangOpts, bool IncludeMacroExpansion) static
Definition at line 104 of file SourceCode.cpp.
References clang::CharSourceRange::getBegin(), clang::CharSourceRange::getCharRange(), clang::CharSourceRange::getEnd(), clang::Lexer::getLocForEndOfToken(), clang::CharSourceRange::isTokenRange(), clang::Lexer::makeFileCharRange(), SM, and spelledInMacroDefinition().
Referenced by clang::Sema::checkOpenMPDeclareVariantFunction(), clang::tooling::getFileRange(), clang::tooling::getFileRangeForEdit(), and clang::Sema::mergeDeclAttributes().
getTerminators()
static std::set< tok::TokenKind > getTerminators (const Decl & D) static
Definition at line 295 of file SourceCode.cpp.
Referenced by clang::tooling::getAssociatedRange().
skipWhitespaceAndNewline()
static SourceLocation skipWhitespaceAndNewline (const SourceManager & SM, SourceLocation Loc, const LangOptions & LangOpts) static
Definition at line 311 of file SourceCode.cpp.
References clang::isHorizontalWhitespace(), clang::isVerticalWhitespace(), and SM.
Referenced by clang::tooling::getAssociatedRange().
spelledInMacroDefinition()
static bool spelledInMacroDefinition (SourceLocation Loc, const SourceManager & SM) static
Definition at line 89 of file SourceCode.cpp.
References SM.
Referenced by getRange().
startsWithNewline()
static bool startsWithNewline (const SourceManager & SM, const Token & Tok) static
Definition at line 148 of file SourceCode.cpp.
References clang::Token::getLocation(), clang::isVerticalWhitespace(), SM, and Tok.
Referenced by getEntityEndLoc().
validateRange()
static llvm::Error validateRange (const CharSourceRange & Range, const SourceManager & SM, bool AllowSystemHeaders) static
Definition at line 53 of file SourceCode.cpp.
References SM.
Referenced by clang::tooling::getFileRange(), and clang::tooling::validateEditRange().