clang: include/clang/AST/StmtOpenMP.h File Reference
StmtOpenMP.h File Reference
This file defines OpenMP AST classes for executable directives and clauses.
#include "clang/AST/ASTContext.h"
#include "clang/AST/Expr.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/SourceLocation.h"
Classes
class OMPTargetDirective
This represents '#pragma omp target' directive.
class OMPTargetDataDirective
This represents '#pragma omp target data' directive.
class OMPTargetEnterDataDirective
This represents '#pragma omp target enter data' directive.
class OMPTargetExitDataDirective
This represents '#pragma omp target exit data' directive.
class OMPTargetParallelDirective
This represents '#pragma omp target parallel' directive.
class OMPTargetParallelForDirective
This represents '#pragma omp target parallel for' directive.
class OMPTeamsDirective
This represents '#pragma omp teams' directive.
class OMPCancellationPointDirective
This represents '#pragma omp cancellation point' directive.
class OMPCancelDirective
This represents '#pragma omp cancel' directive.
class OMPTaskLoopDirective
This represents '#pragma omp taskloop' directive.
class OMPTaskLoopSimdDirective
This represents '#pragma omp taskloop simd' directive.
class OMPMasterTaskLoopDirective
This represents '#pragma omp master taskloop' directive.
class OMPMaskedTaskLoopDirective
This represents '#pragma omp masked taskloop' directive.
class OMPMasterTaskLoopSimdDirective
This represents '#pragma omp master taskloop simd' directive.
class OMPMaskedTaskLoopSimdDirective
This represents '#pragma omp masked taskloop simd' directive.
class OMPParallelMasterTaskLoopDirective
This represents '#pragma omp parallel master taskloop' directive.
class OMPParallelMaskedTaskLoopDirective
This represents '#pragma omp parallel masked taskloop' directive.
class OMPParallelMasterTaskLoopSimdDirective
This represents '#pragma omp parallel master taskloop simd' directive.
class OMPParallelMaskedTaskLoopSimdDirective
This represents '#pragma omp parallel masked taskloop simd' directive.
class OMPDistributeDirective
This represents '#pragma omp distribute' directive.
class OMPTargetUpdateDirective
This represents '#pragma omp target update' directive.
class OMPDistributeParallelForDirective
This represents '#pragma omp distribute parallel for' composite directive.
class OMPDistributeParallelForSimdDirective
This represents '#pragma omp distribute parallel for simd' composite directive.
class OMPDistributeSimdDirective
This represents '#pragma omp distribute simd' composite directive.
class OMPTargetParallelForSimdDirective
This represents '#pragma omp target parallel for simd' directive.
class OMPTargetSimdDirective
This represents '#pragma omp target simd' directive.
class OMPTeamsDistributeDirective
This represents '#pragma omp teams distribute' directive.
class OMPTeamsDistributeSimdDirective
This represents '#pragma omp teams distribute simd' combined directive.
class OMPTeamsDistributeParallelForSimdDirective
This represents '#pragma omp teams distribute parallel for simd' composite directive.
class OMPTeamsDistributeParallelForDirective
This represents '#pragma omp teams distribute parallel for' composite directive.
class OMPTargetTeamsDirective
This represents '#pragma omp target teams' directive.
class OMPTargetTeamsDistributeDirective
This represents '#pragma omp target teams distribute' combined directive.
class OMPTargetTeamsDistributeParallelForDirective
This represents '#pragma omp target teams distribute parallel for' combined directive.
class OMPTargetTeamsDistributeParallelForSimdDirective
This represents '#pragma omp target teams distribute parallel for simd' combined directive.
class OMPTargetTeamsDistributeSimdDirective
This represents '#pragma omp target teams distribute simd' combined directive.
class OMPTileDirective
This represents the '#pragma omp tile' loop transformation directive.
class OMPUnrollDirective
This represents the '#pragma omp unroll' loop transformation directive.
class OMPScanDirective
This represents '#pragma omp scan' directive.
class OMPInteropDirective
This represents '#pragma omp interop' directive.
class OMPDispatchDirective
This represents '#pragma omp dispatch' directive.
class OMPMaskedDirective
This represents '#pragma omp masked' directive.
class OMPMetaDirective
This represents '#pragma omp metadirective' directive.
class OMPGenericLoopDirective
This represents '#pragma omp loop' directive.
class OMPTeamsGenericLoopDirective
This represents '#pragma omp teams loop' directive.
class OMPTargetTeamsGenericLoopDirective
This represents '#pragma omp target teams loop' directive.
class OMPParallelGenericLoopDirective
This represents '#pragma omp parallel loop' directive.
class OMPTargetParallelGenericLoopDirective
This represents '#pragma omp target parallel loop' directive.
class OMPErrorDirective
This represents '#pragma omp error' directive.
Namespaces
namespace clang
Functions
static OMPAtomicDirective * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation EndLoc, ArrayRef< OMPClause * > Clauses, Stmt *AssociatedStmt, Expressions Exprs)
Creates directive with a list of Clauses and 'x', 'v' and 'expr' parts of the atomic construct (see Section 2.12.6, atomic Construct, for detailed description of 'x', 'v' and 'expr').
static OMPAtomicDirective * CreateEmpty (const ASTContext &C, unsigned NumClauses, EmptyShell)
Creates an empty directive with the place for NumClauses clauses.
Expr * getX ()
Get 'x' part of the associated expression/statement.
Expr * getUpdateExpr ()
Get helper expression of the form 'OpaqueValueExpr(x) binop OpaqueValueExpr(expr)' or 'OpaqueValueExpr(expr) binop OpaqueValueExpr(x)'.
bool isXLHSInRHSPart () const
Return true if helper update expression has form 'OpaqueValueExpr(x) binop OpaqueValueExpr(expr)' and false if it has form 'OpaqueValueExpr(expr) binop OpaqueValueExpr(x)'.
bool isPostfixUpdate () const
Return true if 'v' expression must be updated to original value of 'x', false if 'v' must be updated to the new value of 'x'.
bool isFailOnly () const
Return true if 'v' is updated only when the condition is evaluated false (compare capture only).
Expr * getV ()
Get 'v' part of the associated expression/statement.
Expr * getR ()
Get 'r' part of the associated expression/statement.
Expr * getExpr ()
Get 'expr' part of the associated expression/statement.
Expr * getD ()
Get 'd' part of the associated expression/statement.
Expr * getCondExpr ()
Get the 'cond' part of the source atomic expression.
static bool classof (const Stmt *T)
Variables
Expr * clang::Cond = nullptr
};
bool clang::IsXLHSInRHSPart
True if UE has the first form and false if the second.
bool clang::IsPostfixUpdate
True if original value of 'x' must be stored in 'v', not an updated one.
bool clang::IsFailOnly
True if 'v' is updated only when the condition is false (compare capture only).
Detailed Description
This file defines OpenMP AST classes for executable directives and clauses.
Definition in file StmtOpenMP.h.
Function Documentation
classof()
static bool classof (const Stmt * T) static
Definition at line 3084 of file StmtOpenMP.h.
Create()
static OMPAtomicDirective * Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation EndLoc, ArrayRef< OMPClause * > Clauses, Stmt * AssociatedStmt, Expressions Exprs) static
Creates directive with a list of Clauses and 'x', 'v' and 'expr' parts of the atomic construct (see Section 2.12.6, atomic Construct, for detailed description of 'x', 'v' and 'expr').
Parameters
C AST context.
StartLoc Starting location of the directive kind.
EndLoc Ending Location of the directive.
Clauses List of clauses.
AssociatedStmt Statement, associated with the directive.
Exprs Associated expressions or statements.
CreateEmpty()
static OMPAtomicDirective * CreateEmpty (const ASTContext & C, unsigned NumClauses, EmptyShell) static
Creates an empty directive with the place for NumClauses clauses.
Parameters
C AST context.
NumClauses Number of clauses.
getCondExpr()
Expr * getCondExpr ()
Get the 'cond' part of the source atomic expression.
Definition at line 3077 of file StmtOpenMP.h.
References Data.
getD()
Expr * getD ()
Get 'd' part of the associated expression/statement.
Definition at line 3070 of file StmtOpenMP.h.
References Data.
getExpr()
const Expr * getExpr ()
Get 'expr' part of the associated expression/statement.
Definition at line 3063 of file StmtOpenMP.h.
References Data.
Referenced by clang::Sema::canThrow(), CheckICE(), ClassifyInternal(), clang::ParenListExpr::getExpr(), clang::ento::SMTConv::getRangeExpr(), clang::ShuffleVectorExpr::getShuffleMaskIdx(), clang::ExplicitSpecifier::isEquivalent(), and clang::Expr::isUnusedResultAWarning().
getR()
const Expr * getR ()
Get 'r' part of the associated expression/statement.
Definition at line 3056 of file StmtOpenMP.h.
References Data.
getUpdateExpr()
const Expr * getUpdateExpr ()
Get helper expression of the form 'OpaqueValueExpr(x) binop OpaqueValueExpr(expr)' or 'OpaqueValueExpr(expr) binop OpaqueValueExpr(x)'.
Definition at line 3030 of file StmtOpenMP.h.
References Data.
getV()
const Expr * getV ()
Get 'v' part of the associated expression/statement.
Definition at line 3049 of file StmtOpenMP.h.
References Data.
getX()
const Expr * getX ()
Get 'x' part of the associated expression/statement.
Definition at line 3021 of file StmtOpenMP.h.
References Data.
isFailOnly()
bool isFailOnly () const
Return true if 'v' is updated only when the condition is evaluated false (compare capture only).
Definition at line 3047 of file StmtOpenMP.h.
isPostfixUpdate()
bool isPostfixUpdate () const
Return true if 'v' expression must be updated to original value of 'x', false if 'v' must be updated to the new value of 'x'.
Definition at line 3044 of file StmtOpenMP.h.
isXLHSInRHSPart()
bool isXLHSInRHSPart () const
Return true if helper update expression has form 'OpaqueValueExpr(x) binop OpaqueValueExpr(expr)' and false if it has form 'OpaqueValueExpr(expr) binop OpaqueValueExpr(x)'.
Definition at line 3041 of file StmtOpenMP.h.