clang: clang::BadConversionSequence Struct Reference
clang::BadConversionSequence Struct Reference
BadConversionSequence - Records information about an invalid conversion sequence.
#include "clang/Sema/Overload.h"
Public Types
enum FailureKind {
no_conversion , unrelated_class , bad_qualifiers , lvalue_ref_to_rvalue ,
rvalue_ref_to_lvalue , too_few_initializers , too_many_initializers
}
Public Member Functions
void init (FailureKind K, Expr *From, QualType To)
void init (FailureKind K, QualType From, QualType To)
QualType getFromType () const
QualType getToType () const
void setFromExpr (Expr *E)
void setFromType (QualType T)
void setToType (QualType T)
Public Attributes
Expr * FromExpr
FailureKind Kind
Detailed Description
BadConversionSequence - Records information about an invalid conversion sequence.
Definition at line 468 of file Overload.h.
Member Enumeration Documentation
FailureKind
enum clang::BadConversionSequence::FailureKind
Enumerator
no_conversion
unrelated_class
bad_qualifiers
lvalue_ref_to_rvalue
rvalue_ref_to_lvalue
too_few_initializers
too_many_initializers
Definition at line 469 of file Overload.h.
Member Function Documentation
getFromType()
QualType clang::BadConversionSequence::getFromType () const inline
Definition at line 504 of file Overload.h.
References clang::QualType::getFromOpaquePtr().
Referenced by DiagnoseBadConversion().
getToType()
QualType clang::BadConversionSequence::getToType () const inline
Definition at line 505 of file Overload.h.
References clang::QualType::getFromOpaquePtr().
Referenced by DiagnoseBadConversion().
init() [1/2]
void clang::BadConversionSequence::init (FailureKind K, Expr * From, QualType To) inline
Definition at line 492 of file Overload.h.
References FromExpr, clang::Expr::getType(), and init().
Referenced by init(), clang::ImplicitConversionSequence::setBad(), and clang::ImplicitConversionSequence::setBad().
init() [2/2]
void clang::BadConversionSequence::init (FailureKind K, QualType From, QualType To) inline
Definition at line 497 of file Overload.h.
References FromExpr, setFromType(), and setToType().
setFromExpr()
void clang::BadConversionSequence::setFromExpr (Expr * E) inline
Definition at line 507 of file Overload.h.
References FromExpr, clang::Expr::getType(), and setFromType().
setFromType()
void clang::BadConversionSequence::setFromType (QualType T) inline
Definition at line 512 of file Overload.h.
Referenced by init(), and setFromExpr().
setToType()
void clang::BadConversionSequence::setToType (QualType T) inline
Definition at line 513 of file Overload.h.
Referenced by init().
Member Data Documentation
FromExpr
Expr* clang::BadConversionSequence::FromExpr
Definition at line 480 of file Overload.h.
Referenced by DiagnoseBadConversion(), init(), init(), and setFromExpr().
Kind
FailureKind clang::BadConversionSequence::Kind
Definition at line 482 of file Overload.h.
Referenced by DiagnoseBadConversion(), and clang::Sema::PerformObjectArgumentInitialization().
The documentation for this struct was generated from the following file:
include/clang/Sema/Overload.h