clang: clang::dataflow::TypeErasedDataflowAnalysisState Struct Reference
clang::dataflow::TypeErasedDataflowAnalysisState Struct Reference
Type-erased model of the program at a given program point.
#include "clang/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.h"
Public Member Functions
TypeErasedDataflowAnalysisState (TypeErasedLattice Lattice, Environment Env)
TypeErasedDataflowAnalysisState fork () const
Public Attributes
TypeErasedLattice Lattice
Type-erased model of a program property.
Environment Env
Model of the state of the program (store and heap).
Detailed Description
Type-erased model of the program at a given program point.
Definition at line 120 of file TypeErasedDataflowAnalysis.h.
Constructor & Destructor Documentation
TypeErasedDataflowAnalysisState()
clang::dataflow::TypeErasedDataflowAnalysisState::TypeErasedDataflowAnalysisState (TypeErasedLattice Lattice, Environment Env) inline
Definition at line 127 of file TypeErasedDataflowAnalysis.h.
Referenced by fork().
Member Function Documentation
fork()
TypeErasedDataflowAnalysisState clang::dataflow::TypeErasedDataflowAnalysisState::fork () const inline
Definition at line 130 of file TypeErasedDataflowAnalysis.h.
References Env, clang::dataflow::Environment::fork(), Lattice, and TypeErasedDataflowAnalysisState().
Referenced by clang::dataflow::computeBlockInputState().
Member Data Documentation
Env
Environment clang::dataflow::TypeErasedDataflowAnalysisState::Env
Model of the state of the program (store and heap).
Definition at line 125 of file TypeErasedDataflowAnalysis.h.
Referenced by clang::dataflow::builtinTransferInitializer(), clang::dataflow::builtinTransferStatement(), fork(), and clang::dataflow::runTypeErasedDataflowAnalysis().
Lattice
TypeErasedLattice clang::dataflow::TypeErasedDataflowAnalysisState::Lattice
Type-erased model of a program property.
Definition at line 122 of file TypeErasedDataflowAnalysis.h.
Referenced by fork(), and clang::dataflow::runTypeErasedDataflowAnalysis().
The documentation for this struct was generated from the following file:
include/clang/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.h