clang: clang::driver::ResponseFileSupport Struct Reference
clang::driver::ResponseFileSupport Struct Reference
#include "clang/Driver/Job.h"
Public Types
enum ResponseFileKind { RF_Full , RF_FileList , RF_None }
Static Public Member Functions
static constexpr ResponseFileSupport None ()
Returns a ResponseFileSupport indicating that response files are not supported.
static constexpr ResponseFileSupport AtFileUTF8 ()
static constexpr ResponseFileSupport AtFileCurCP ()
static constexpr ResponseFileSupport AtFileUTF16 ()
Public Attributes
ResponseFileKind ResponseKind
The level of support for response files.
llvm::sys::WindowsEncodingMethod ResponseEncoding
The encoding to use when writing response files on Windows.
const char * ResponseFlag
What prefix to use for the command-line argument when passing a response file.
Detailed Description
Definition at line 44 of file Job.h.
Member Enumeration Documentation
ResponseFileKind
enum clang::driver::ResponseFileSupport::ResponseFileKind
Enumerator
RF_Full
RF_FileList
RF_None
Definition at line 45 of file Job.h.
Member Function Documentation
AtFileCurCP()
static constexpr ResponseFileSupport clang::driver::ResponseFileSupport::AtFileCurCP () inline static constexpr
Definition at line 92 of file Job.h.
References RF_Full.
Referenced by clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::ananas::Assembler::ConstructJob(), clang::driver::tools::ananas::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::Linker::ConstructJob(), clang::driver::tools::baremetal::StaticLibTool::ConstructJob(), clang::driver::tools::cloudabi::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::fuchsia::StaticLibTool::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::gnutools::StaticLibTool::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::hexagon::Linker::ConstructJob(), clang::driver::tools::minix::Assembler::ConstructJob(), clang::driver::tools::minix::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::Myriad::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::GetSDLFromOffloadArchive().
AtFileUTF16()
static constexpr ResponseFileSupport clang::driver::ResponseFileSupport::AtFileUTF16 () inline static constexpr
Definition at line 99 of file Job.h.
References RF_Full.
Referenced by clang::driver::tools::visualstudio::Linker::ConstructJob().
AtFileUTF8()
static constexpr ResponseFileSupport clang::driver::ResponseFileSupport::AtFileUTF8 () inline static constexpr
Definition at line 85 of file Job.h.
References RF_Full.
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::darwin::StaticLibTool::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), and clang::driver::tools::PScpu::Linker::ConstructJob().
None()
static constexpr ResponseFileSupport clang::driver::ResponseFileSupport::None () inline static constexpr
Returns a ResponseFileSupport indicating that response files are not supported.
Definition at line 78 of file Job.h.
References RF_None.
Referenced by clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Assembler::ConstructJob(), clang::driver::tools::darwin::Assembler::ConstructJob(), clang::driver::tools::darwin::Dsymutil::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::darwin::Lipo::ConstructJob(), clang::driver::tools::darwin::VerifyDebug::ConstructJob(), clang::driver::tools::hlsl::Validator::ConstructJob(), clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::MinGW::Assembler::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::SHAVE::Assembler::ConstructJob(), clang::driver::tools::SHAVE::Compiler::ConstructJob(), clang::driver::tools::solaris::Assembler::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::XCore::Assembler::ConstructJob(), clang::driver::tools::XCore::Linker::ConstructJob(), clang::driver::tools::zos::Assembler::ConstructJob(), clang::driver::tools::zos::Linker::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), and clang::driver::tools::SPIRV::constructTranslateCommand().
Member Data Documentation
ResponseEncoding
llvm::sys::WindowsEncodingMethod clang::driver::ResponseFileSupport::ResponseEncoding
The encoding to use when writing response files on Windows.
Ignored on other host OSes.
Windows use cases: - GCC and Binutils on mingw only accept ANSI response files encoded with the system current code page.
MSVC's CL.exe and LINK.exe accept UTF16 on Windows.
Clang accepts both UTF8 and UTF16.
FIXME: When GNU tools learn how to parse UTF16 on Windows, we should always use UTF16 for Windows, which is the Windows official encoding for international characters.
Definition at line 70 of file Job.h.
Referenced by clang::driver::Command::Execute().
ResponseFlag
const char* clang::driver::ResponseFileSupport::ResponseFlag
What prefix to use for the command-line argument when passing a response file.
Definition at line 74 of file Job.h.
Referenced by clang::driver::Command::setResponseFile().
ResponseKind
ResponseFileKind clang::driver::ResponseFileSupport::ResponseKind
The level of support for response files.
Definition at line 57 of file Job.h.
Referenced by clang::driver::Command::Print().
The documentation for this struct was generated from the following file:
include/clang/Driver/Job.h