clang: clang::CodeCompletionString::Chunk Struct Reference
clang::CodeCompletionString::Chunk Struct Reference
One piece of the code completion string.
#include "clang/Sema/CodeCompleteConsumer.h"
Public Member Functions
Chunk ()
Chunk (ChunkKind Kind, const char *Text="")
Static Public Member Functions
static Chunk CreateText (const char *Text)
Create a new text chunk.
static Chunk CreateOptional (CodeCompletionString *Optional)
Create a new optional chunk.
static Chunk CreatePlaceholder (const char *Placeholder)
Create a new placeholder chunk.
static Chunk CreateInformative (const char *Informative)
Create a new informative chunk.
static Chunk CreateResultType (const char *ResultType)
Create a new result type chunk.
static Chunk CreateCurrentParameter (const char *CurrentParameter)
Create a new current-parameter chunk.
Public Attributes
ChunkKind Kind = CK_Text
The kind of data stored in this piece of the code completion string.
union {
const char * Text
The text string associated with a CK_Text, CK_Placeholder, CK_Informative, or CK_Comma chunk.
CodeCompletionString * Optional
The code completion string associated with a CK_Optional chunk.
};
Detailed Description
One piece of the code completion string.
Definition at line 524 of file CodeCompleteConsumer.h.
Constructor & Destructor Documentation
Chunk() [1/2]
clang::CodeCompletionString::Chunk::Chunk () inline
Definition at line 542 of file CodeCompleteConsumer.h.
Chunk() [2/2]
CodeCompletionString::Chunk::Chunk (ChunkKind Kind, const char * Text = "") explicit
Definition at line 180 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_Colon, clang::CodeCompletionString::CK_Comma, clang::CodeCompletionString::CK_CurrentParameter, clang::CodeCompletionString::CK_Equal, clang::CodeCompletionString::CK_HorizontalSpace, clang::CodeCompletionString::CK_Informative, clang::CodeCompletionString::CK_LeftAngle, clang::CodeCompletionString::CK_LeftBrace, clang::CodeCompletionString::CK_LeftBracket, clang::CodeCompletionString::CK_LeftParen, clang::CodeCompletionString::CK_Optional, clang::CodeCompletionString::CK_Placeholder, clang::CodeCompletionString::CK_ResultType, clang::CodeCompletionString::CK_RightAngle, clang::CodeCompletionString::CK_RightBrace, clang::CodeCompletionString::CK_RightBracket, clang::CodeCompletionString::CK_RightParen, clang::CodeCompletionString::CK_SemiColon, clang::CodeCompletionString::CK_Text, clang::CodeCompletionString::CK_TypedText, clang::CodeCompletionString::CK_VerticalSpace, and Text.
Member Function Documentation
CreateCurrentParameter()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreateCurrentParameter (const char * CurrentParameter) static
Create a new current-parameter chunk.
Definition at line 281 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_CurrentParameter.
Referenced by clang::CodeCompletionBuilder::AddCurrentParameterChunk().
CreateInformative()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreateInformative (const char * Informative) static
Create a new informative chunk.
Definition at line 272 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_Informative.
Referenced by clang::CodeCompletionBuilder::AddInformativeChunk().
CreateOptional()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreateOptional (CodeCompletionString * Optional) static
Create a new optional chunk.
Definition at line 259 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_Optional, Kind, Optional, and clang::Result.
Referenced by clang::CodeCompletionBuilder::AddOptionalChunk().
CreatePlaceholder()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreatePlaceholder (const char * Placeholder) static
Create a new placeholder chunk.
Definition at line 267 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_Placeholder.
Referenced by clang::CodeCompletionBuilder::AddPlaceholderChunk().
CreateResultType()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreateResultType (const char * ResultType) static
Create a new result type chunk.
Definition at line 277 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_ResultType.
Referenced by clang::CodeCompletionBuilder::AddResultTypeChunk().
CreateText()
CodeCompletionString::Chunk CodeCompletionString::Chunk::CreateText (const char * Text) static
Create a new text chunk.
Definition at line 254 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionString::CK_Text, and Text.
Referenced by clang::CodeCompletionBuilder::AddTextChunk().
Member Data Documentation
[union]
union { ... } clang::CodeCompletionString::Chunk
Kind
ChunkKind clang::CodeCompletionString::Chunk::Kind = CK_Text
The kind of data stored in this piece of the code completion string.
Definition at line 527 of file CodeCompleteConsumer.h.
Referenced by CreateOptional().
Optional
CodeCompletionString* clang::CodeCompletionString::Chunk::Optional
The code completion string associated with a CK_Optional chunk.
The optional code completion string is owned by the chunk, and will be deallocated (with delete) when the chunk is destroyed.
Definition at line 539 of file CodeCompleteConsumer.h.
Text
const char* clang::CodeCompletionString::Chunk::Text
The text string associated with a CK_Text, CK_Placeholder, CK_Informative, or CK_Comma chunk.
The string is owned by the chunk and will be deallocated (with delete[]) when the chunk is destroyed.
Definition at line 534 of file CodeCompleteConsumer.h.
Referenced by Chunk().
The documentation for this struct was generated from the following files:
include/clang/Sema/CodeCompleteConsumer.h
lib/Sema/CodeCompleteConsumer.cpp