clang: ImmediateCallVisitor Struct Reference
ImmediateCallVisitor Struct Reference
Public Member Functions
ImmediateCallVisitor (const ASTContext &Ctx)
bool shouldVisitImplicitCode () const
bool VisitCallExpr (CallExpr *E)
bool VisitSourceLocExpr (SourceLocExpr *E)
bool VisitLambdaExpr (LambdaExpr *E)
bool VisitBlockDecl (BlockDecl *B)
bool VisitCompoundStmt (CompoundStmt *B)
bool VisitCXXDefaultArgExpr (CXXDefaultArgExpr *E)
bool VisitCXXDefaultInitExpr (CXXDefaultInitExpr *E)
Public Member Functions inherited from clang::RecursiveASTVisitor< ImmediateCallVisitor >
ImmediateCallVisitor & getDerived ()
Return a reference to the derived class.
bool shouldVisitTemplateInstantiations () const
Return whether this visitor should recurse into template instantiations.
bool shouldWalkTypesOfTypeLocs () const
Return whether this visitor should recurse into the types of TypeLocs.
bool shouldVisitImplicitCode () const
Return whether this visitor should recurse into implicit code, e.g., implicit constructors and destructors.
bool shouldVisitLambdaBody () const
Return whether this visitor should recurse into lambda body.
bool shouldTraversePostOrder () const
Return whether this visitor should traverse post-order.
bool TraverseAST (ASTContext &AST)
Recursively visits an entire AST, starting from the TranslationUnitDecl.
bool TraverseStmt (Stmt *S, DataRecursionQueue *Queue=nullptr)
Recursively visit a statement or expression, by dispatching to Traverse*() based on the argument's dynamic type.
bool dataTraverseStmtPre (Stmt *S)
Invoked before visiting a statement or expression via data recursion.
bool dataTraverseStmtPost (Stmt *S)
Invoked after visiting a statement or expression via data recursion.
bool TraverseType (QualType T)
Recursively visit a type, by dispatching to Traverse*Type() based on the argument's getTypeClass() property.
bool TraverseTypeLoc (TypeLoc TL)
Recursively visit a type with location, by dispatching to Traverse*TypeLoc() based on the argument type's getTypeClass() property.
bool TraverseAttr (Attr *At)
Recursively visit an attribute, by dispatching to Traverse*Attr() based on the argument's dynamic type.
bool TraverseDecl (Decl *D)
Recursively visit a declaration, by dispatching to Traverse*Decl() based on the argument's dynamic type.
bool TraverseNestedNameSpecifier (NestedNameSpecifier *NNS)
Recursively visit a C++ nested-name-specifier.
bool TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Recursively visit a C++ nested-name-specifier with location information.
bool TraverseDeclarationNameInfo (DeclarationNameInfo NameInfo)
Recursively visit a name with its location information.
bool TraverseTemplateName (TemplateName Template)
Recursively visit a template name and dispatch to the appropriate method.
bool TraverseTemplateArgument (const TemplateArgument &Arg)
Recursively visit a template argument and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArgumentLoc (const TemplateArgumentLoc &ArgLoc)
Recursively visit a template argument location and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArguments (ArrayRef< TemplateArgument > Args)
Recursively visit a set of template arguments.
bool TraverseCXXBaseSpecifier (const CXXBaseSpecifier &Base)
Recursively visit a base specifier.
bool TraverseConstructorInitializer (CXXCtorInitializer *Init)
Recursively visit a constructor initializer.
bool TraverseLambdaCapture (LambdaExpr *LE, const LambdaCapture *C, Expr *Init)
Recursively visit a lambda capture.
bool TraverseSynOrSemInitListExpr (InitListExpr *S, DataRecursionQueue *Queue=nullptr)
Recursively visit the syntactic or semantic form of an initialization list.
bool TraverseObjCProtocolLoc (ObjCProtocolLoc ProtocolLoc)
Recursively visit an Objective-C protocol reference with location information.
bool VisitAttr (Attr *A)
Stmt::child_range getStmtChildren (Stmt *S)
bool WalkUpFromStmt (Stmt *S)
bool VisitStmt (Stmt *S)
bool WalkUpFromType (Type *T)
bool VisitType (Type *T)
bool WalkUpFromTypeLoc (TypeLoc TL)
bool VisitTypeLoc (TypeLoc TL)
bool WalkUpFromQualifiedTypeLoc (QualifiedTypeLoc TL)
bool VisitQualifiedTypeLoc (QualifiedTypeLoc TL)
bool WalkUpFromUnqualTypeLoc (UnqualTypeLoc TL)
bool VisitUnqualTypeLoc (UnqualTypeLoc TL)
bool WalkUpFromDecl (Decl *D)
bool VisitDecl (Decl *D)
bool canIgnoreChildDeclWhileTraversingDeclContext (const Decl *Child)
bool TraverseTypeConstraint (const TypeConstraint *C)
bool TraverseConceptRequirement (concepts::Requirement *R)
bool TraverseConceptTypeRequirement (concepts::TypeRequirement *R)
bool TraverseConceptExprRequirement (concepts::ExprRequirement *R)
bool TraverseConceptNestedRequirement (concepts::NestedRequirement *R)
bool dataTraverseNode (Stmt *S, DataRecursionQueue *Queue)
Public Attributes
const ASTContext & Context
bool HasImmediateCalls = false
Additional Inherited Members
Public Types inherited from clang::RecursiveASTVisitor< ImmediateCallVisitor >
typedef SmallVectorImpl< llvm::PointerIntPair< Stmt *, 1, bool > > DataRecursionQueue
A queue used for performing data recursion over statements.
Detailed Description
Definition at line 6082 of file SemaExpr.cpp.
Constructor & Destructor Documentation
ImmediateCallVisitor()
ImmediateCallVisitor::ImmediateCallVisitor (const ASTContext & Ctx) inline
Definition at line 6084 of file SemaExpr.cpp.
Member Function Documentation
shouldVisitImplicitCode()
bool ImmediateCallVisitor::shouldVisitImplicitCode () const inline
Definition at line 6087 of file SemaExpr.cpp.
VisitBlockDecl()
bool ImmediateCallVisitor::VisitBlockDecl (BlockDecl * B) inline
Definition at line 6116 of file SemaExpr.cpp.
VisitCallExpr()
bool ImmediateCallVisitor::VisitCallExpr (CallExpr * E) inline
Definition at line 6089 of file SemaExpr.cpp.
References clang::CallExpr::getDirectCallee(), and clang::RecursiveASTVisitor< Derived >::VisitStmt().
VisitCompoundStmt()
bool ImmediateCallVisitor::VisitCompoundStmt (CompoundStmt * B) inline
Definition at line 6118 of file SemaExpr.cpp.
VisitCXXDefaultArgExpr()
bool ImmediateCallVisitor::VisitCXXDefaultArgExpr (CXXDefaultArgExpr * E) inline
Definition at line 6120 of file SemaExpr.cpp.
References clang::CXXDefaultArgExpr::getExpr().
VisitCXXDefaultInitExpr()
bool ImmediateCallVisitor::VisitCXXDefaultInitExpr (CXXDefaultInitExpr * E) inline
Definition at line 6124 of file SemaExpr.cpp.
References clang::CXXDefaultInitExpr::getExpr().
VisitLambdaExpr()
bool ImmediateCallVisitor::VisitLambdaExpr (LambdaExpr * E) inline
Definition at line 6110 of file SemaExpr.cpp.
References clang::LambdaExpr::getCallOperator().
VisitSourceLocExpr()
bool ImmediateCallVisitor::VisitSourceLocExpr (SourceLocExpr * E) inline
Definition at line 6099 of file SemaExpr.cpp.
References clang::RecursiveASTVisitor< Derived >::VisitStmt().
Member Data Documentation
Context
const ASTContext& ImmediateCallVisitor::Context
Definition at line 6083 of file SemaExpr.cpp.
HasImmediateCalls
bool ImmediateCallVisitor::HasImmediateCalls = false
Definition at line 6086 of file SemaExpr.cpp.
The documentation for this struct was generated from the following file:
lib/Sema/SemaExpr.cpp