clang: clang::ASTConstraintSatisfaction Struct Reference
clang::ASTConstraintSatisfaction Struct Reference final
The result of a constraint satisfaction check, containing the necessary information to diagnose an unsatisfied constraint.
#include "clang/AST/ASTConcept.h"
Public Member Functions
const UnsatisfiedConstraintRecord * begin () const
const UnsatisfiedConstraintRecord * end () const
ASTConstraintSatisfaction (const ASTContext &C, const ConstraintSatisfaction &Satisfaction)
ASTConstraintSatisfaction (const ASTContext &C, const ASTConstraintSatisfaction &Satisfaction)
Static Public Member Functions
static ASTConstraintSatisfaction * Create (const ASTContext &C, const ConstraintSatisfaction &Satisfaction)
static ASTConstraintSatisfaction * Rebuild (const ASTContext &C, const ASTConstraintSatisfaction &Satisfaction)
Public Attributes
std::size_t NumRecords
bool IsSatisfied: 1
bool ContainsErrors: 1
Detailed Description
The result of a constraint satisfaction check, containing the necessary information to diagnose an unsatisfied constraint.
This is safe to store in an AST node, as opposed to ConstraintSatisfaction.
Definition at line 84 of file ASTConcept.h.
Constructor & Destructor Documentation
ASTConstraintSatisfaction() [1/2]
ASTConstraintSatisfaction::ASTConstraintSatisfaction (const ASTContext & C, const ConstraintSatisfaction & Satisfaction)
Definition at line 44 of file ASTConcept.cpp.
References clang::C, clang::ConstraintSatisfaction::Details, and NumRecords.
Referenced by Create(), and Rebuild().
ASTConstraintSatisfaction() [2/2]
ASTConstraintSatisfaction::ASTConstraintSatisfaction (const ASTContext & C, const ASTConstraintSatisfaction & Satisfaction)
Definition at line 55 of file ASTConcept.cpp.
References begin(), clang::C, and NumRecords.
Member Function Documentation
begin()
const UnsatisfiedConstraintRecord * clang::ASTConstraintSatisfaction::begin () const inline
Definition at line 91 of file ASTConcept.h.
Referenced by ASTConstraintSatisfaction().
Create()
ASTConstraintSatisfaction * ASTConstraintSatisfaction::Create (const ASTContext & C, const ConstraintSatisfaction & Satisfaction) static
Definition at line 67 of file ASTConcept.cpp.
References ASTConstraintSatisfaction(), clang::C, and clang::ConstraintSatisfaction::Details.
end()
const UnsatisfiedConstraintRecord * clang::ASTConstraintSatisfaction::end () const inline
Definition at line 95 of file ASTConcept.h.
References NumRecords.
Rebuild()
ASTConstraintSatisfaction * ASTConstraintSatisfaction::Rebuild (const ASTContext & C, const ASTConstraintSatisfaction & Satisfaction) static
Definition at line 76 of file ASTConcept.cpp.
References ASTConstraintSatisfaction(), clang::C, and NumRecords.
Referenced by clang::Sema::BuildNestedRequirement().
Member Data Documentation
ContainsErrors
bool clang::ASTConstraintSatisfaction::ContainsErrors
Definition at line 89 of file ASTConcept.h.
Referenced by addConstraintSatisfaction(), and clang::computeDependence().
IsSatisfied
bool clang::ASTConstraintSatisfaction::IsSatisfied
Definition at line 88 of file ASTConcept.h.
Referenced by addConstraintSatisfaction(), clang::Sema::DiagnoseUnsatisfiedConstraint(), and clang::ConceptSpecializationExpr::isSatisfied().
NumRecords
std::size_t clang::ASTConstraintSatisfaction::NumRecords
Definition at line 87 of file ASTConcept.h.
Referenced by addConstraintSatisfaction(), ASTConstraintSatisfaction(), ASTConstraintSatisfaction(), end(), and Rebuild().
The documentation for this struct was generated from the following files:
include/clang/AST/ASTConcept.h
lib/AST/ASTConcept.cpp