clang: clang::OffloadTargetInfo Struct Reference
clang::OffloadTargetInfo Struct Reference
Obtain the offload kind, real machine triple, and an optional GPUArch out of the target information specified by the user.
#include "clang/Driver/OffloadBundler.h"
Public Member Functions
OffloadTargetInfo (const llvm::StringRef Target, const OffloadBundlerConfig &BC)
bool hasHostKind () const
bool isOffloadKindValid () const
bool isOffloadKindCompatible (const llvm::StringRef TargetOffloadKind) const
bool isTripleValid () const
bool operator== (const OffloadTargetInfo &Target) const
std::string str () const
Public Attributes
llvm::StringRef OffloadKind
llvm::Triple Triple
llvm::StringRef TargetID
const OffloadBundlerConfig & BundlerConfig
Detailed Description
Obtain the offload kind, real machine triple, and an optional GPUArch out of the target information specified by the user.
Bundle Entry ID (or, Offload Target String) has following components:
Offload Kind - Host, OpenMP, or HIP
Triple - Standard LLVM Triple
TargetID (Optional) - target ID, like gfx906:xnack+ or sm_30
Definition at line 70 of file OffloadBundler.h.
Constructor & Destructor Documentation
OffloadTargetInfo()
OffloadTargetInfo::OffloadTargetInfo (const llvm::StringRef Target, const OffloadBundlerConfig & BC)
Definition at line 64 of file OffloadBundler.cpp.
References clang::StringToCudaArch(), and clang::UNKNOWN.
Member Function Documentation
hasHostKind()
bool OffloadTargetInfo::hasHostKind () const
Definition at line 95 of file OffloadBundler.cpp.
isOffloadKindCompatible()
bool OffloadTargetInfo::isOffloadKindCompatible (const llvm::StringRef TargetOffloadKind) const
Definition at line 104 of file OffloadBundler.cpp.
References BundlerConfig, and clang::OffloadBundlerConfig::HipOpenmpCompatible.
Referenced by isCodeObjectCompatible().
isOffloadKindValid()
bool OffloadTargetInfo::isOffloadKindValid () const
Definition at line 99 of file OffloadBundler.cpp.
isTripleValid()
bool OffloadTargetInfo::isTripleValid () const
Definition at line 119 of file OffloadBundler.cpp.
operator==()
bool OffloadTargetInfo::operator== (const OffloadTargetInfo & Target) const
Definition at line 123 of file OffloadBundler.cpp.
References TargetID.
str()
std::string OffloadTargetInfo::str () const
Definition at line 128 of file OffloadBundler.cpp.
References TargetID.
Referenced by isCodeObjectCompatible().
Member Data Documentation
BundlerConfig
const OffloadBundlerConfig& clang::OffloadTargetInfo::BundlerConfig
Definition at line 75 of file OffloadBundler.h.
Referenced by isOffloadKindCompatible().
OffloadKind
llvm::StringRef clang::OffloadTargetInfo::OffloadKind
Definition at line 71 of file OffloadBundler.h.
TargetID
llvm::StringRef clang::OffloadTargetInfo::TargetID
Definition at line 73 of file OffloadBundler.h.
Referenced by isCodeObjectCompatible(), operator==(), and str().
Triple
llvm::Triple clang::OffloadTargetInfo::Triple
Definition at line 72 of file OffloadBundler.h.
Referenced by isCodeObjectCompatible().
The documentation for this struct was generated from the following files:
include/clang/Driver/OffloadBundler.h
lib/Driver/OffloadBundler.cpp