clang: clang::BlockVarCopyInit Struct Reference
clang::BlockVarCopyInit Struct Reference
Copy initialization expr of a __block variable and a boolean flag that indicates whether the expression can throw.
#include "clang/AST/Expr.h"
Public Member Functions
BlockVarCopyInit ()=default
BlockVarCopyInit (Expr *CopyExpr, bool CanThrow)
void setExprAndFlag (Expr *CopyExpr, bool CanThrow)
Expr * getCopyExpr () const
bool canThrow () const
Public Attributes
llvm::PointerIntPair< Expr *, 1, bool > ExprAndFlag
Detailed Description
Copy initialization expr of a __block variable and a boolean flag that indicates whether the expression can throw.
Definition at line 6199 of file Expr.h.
Constructor & Destructor Documentation
BlockVarCopyInit() [1/2]
clang::BlockVarCopyInit::BlockVarCopyInit () default
BlockVarCopyInit() [2/2]
clang::BlockVarCopyInit::BlockVarCopyInit (Expr * CopyExpr, bool CanThrow) inline
Definition at line 6201 of file Expr.h.
Member Function Documentation
canThrow()
bool clang::BlockVarCopyInit::canThrow () const inline
Definition at line 6207 of file Expr.h.
References ExprAndFlag.
Referenced by getBlockCaptureStr().
getCopyExpr()
Expr * clang::BlockVarCopyInit::getCopyExpr () const inline
Definition at line 6206 of file Expr.h.
References ExprAndFlag.
Referenced by clang::ASTContext::BlockRequiresCopying().
setExprAndFlag()
void clang::BlockVarCopyInit::setExprAndFlag (Expr * CopyExpr, bool CanThrow) inline
Definition at line 6203 of file Expr.h.
References CanThrow(), and ExprAndFlag.
Member Data Documentation
ExprAndFlag
llvm::PointerIntPair<Expr *, 1, bool> clang::BlockVarCopyInit::ExprAndFlag
Definition at line 6208 of file Expr.h.
Referenced by canThrow(), getCopyExpr(), and setExprAndFlag().
The documentation for this struct was generated from the following file:
include/clang/AST/Expr.h