clang: clang::ento::CheckerRegistryData Struct Reference
clang::ento::CheckerRegistryData Struct Reference
#include "clang/StaticAnalyzer/Core/CheckerRegistryData.h"
Public Member Functions
CheckerInfoListRange getMutableCheckersForCmdLineArg (StringRef CmdLineArg)
void printCheckerWithDescList (const AnalyzerOptions &AnOpts, raw_ostream &Out, size_t MaxNameChars=30) const
Prints the name and description of all checkers in this registry.
void printEnabledCheckerList (raw_ostream &Out) const
void printCheckerOptionList (const AnalyzerOptions &AnOpts, raw_ostream &Out) const
Public Attributes
CheckerInfoSet EnabledCheckers
CheckerInfoList Checkers
PackageInfoList Packages
llvm::StringMap< size_t > PackageSizes
Used for counting how many checkers belong to a certain package in the Checkers field.
llvm::SmallVector< std::pair< StringRef, CmdLineOption >, 0 > PackageOptions
Contains all (FullName, CmdLineOption) pairs.
llvm::SmallVector< std::pair< StringRef, CmdLineOption >, 0 > CheckerOptions
llvm::SmallVector< std::pair< StringRef, StringRef >, 0 > Dependencies
llvm::SmallVector< std::pair< StringRef, StringRef >, 0 > WeakDependencies
Detailed Description
Definition at line 193 of file CheckerRegistryData.h.
Member Function Documentation
getMutableCheckersForCmdLineArg()
CheckerInfoListRange CheckerRegistryData::getMutableCheckersForCmdLineArg (StringRef CmdLineArg)
Definition at line 100 of file CheckerRegistryData.cpp.
References clang::ento::checker_registry::binaryFind(), Checkers, isInPackage(), and PackageSizes.
printCheckerOptionList()
void CheckerRegistryData::printCheckerOptionList (const AnalyzerOptions & AnOpts, raw_ostream & Out) const
Definition at line 178 of file CheckerRegistryData.cpp.
References Checkers, clang::ento::CmdLineOption::DefaultValStr, clang::ento::CmdLineOption::Description, clang::ento::CmdLineOption::DevelopmentStatus, clang::ento::CmdLineOption::IsHidden, clang::ento::CmdLineOption::OptionName, clang::ento::CmdLineOption::OptionType, Packages, clang::AnalyzerOptions::printFormattedEntry(), clang::AnalyzerOptions::ShowCheckerOptionAlphaList, clang::AnalyzerOptions::ShowCheckerOptionDeveloperList, and clang::AnalyzerOptions::ShowCheckerOptionList.
printCheckerWithDescList()
void CheckerRegistryData::printCheckerWithDescList (const AnalyzerOptions & AnOpts, raw_ostream & Out, size_t MaxNameChars = 30) const
Prints the name and description of all checkers in this registry.
This output is not intended to be machine-parseable.
Definition at line 122 of file CheckerRegistryData.cpp.
References Checkers, clang::AnalyzerOptions::printFormattedEntry(), clang::AnalyzerOptions::ShowCheckerHelp, clang::AnalyzerOptions::ShowCheckerHelpAlpha, and clang::AnalyzerOptions::ShowCheckerHelpDeveloper.
printEnabledCheckerList()
void CheckerRegistryData::printEnabledCheckerList (raw_ostream & Out) const
Definition at line 173 of file CheckerRegistryData.cpp.
References EnabledCheckers.
Member Data Documentation
CheckerOptions
llvm::SmallVector<std::pair<StringRef, CmdLineOption>, 0> clang::ento::CheckerRegistryData::CheckerOptions
Definition at line 207 of file CheckerRegistryData.h.
Checkers
CheckerInfoList clang::ento::CheckerRegistryData::Checkers
Definition at line 197 of file CheckerRegistryData.h.
Referenced by getMutableCheckersForCmdLineArg(), isHidden(), printCheckerOptionList(), and printCheckerWithDescList().
Dependencies
llvm::SmallVector<std::pair<StringRef, StringRef>, 0> clang::ento::CheckerRegistryData::Dependencies
Definition at line 209 of file CheckerRegistryData.h.
Referenced by isDependency().
EnabledCheckers
CheckerInfoSet clang::ento::CheckerRegistryData::EnabledCheckers
Definition at line 195 of file CheckerRegistryData.h.
Referenced by printEnabledCheckerList().
PackageOptions
llvm::SmallVector<std::pair<StringRef, CmdLineOption>, 0> clang::ento::CheckerRegistryData::PackageOptions
Contains all (FullName, CmdLineOption) pairs.
Similarly to dependencies, we only modify the actual CheckerInfo and PackageInfo objects once all of them have been added.
Definition at line 206 of file CheckerRegistryData.h.
Packages
PackageInfoList clang::ento::CheckerRegistryData::Packages
Definition at line 198 of file CheckerRegistryData.h.
Referenced by printCheckerOptionList().
PackageSizes
llvm::StringMap<size_t> clang::ento::CheckerRegistryData::PackageSizes
Used for counting how many checkers belong to a certain package in the Checkers field.
For convenience purposes.
Definition at line 201 of file CheckerRegistryData.h.
Referenced by getMutableCheckersForCmdLineArg().
WeakDependencies
llvm::SmallVector<std::pair<StringRef, StringRef>, 0> clang::ento::CheckerRegistryData::WeakDependencies
Definition at line 210 of file CheckerRegistryData.h.
The documentation for this struct was generated from the following files:
include/clang/StaticAnalyzer/Core/CheckerRegistryData.h
lib/StaticAnalyzer/Core/CheckerRegistryData.cpp