clang: clang::CodeGen::DominatingValue< Address > Struct Reference
clang::CodeGen::DominatingValue< Address > Struct Reference
A specialization of DominatingValue for Address.
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Classes
struct saved_type
Public Types
typedef Address type
Static Public Member Functions
static bool needsSaving (type value)
static saved_type save (CodeGenFunction &CGF, type value)
static type restore (CodeGenFunction &CGF, saved_type value)
Detailed Description
A specialization of DominatingValue for Address.
Definition at line 175 of file CodeGenFunction.h.
Member Typedef Documentation
type
Address clang::CodeGen::DominatingValue< Address >::type
Definition at line 176 of file CodeGenFunction.h.
Member Function Documentation
needsSaving()
static bool clang::CodeGen::DominatingValue< Address >::needsSaving (type value) inline static
Definition at line 184 of file CodeGenFunction.h.
References clang::CodeGen::Address::getPointer(), and clang::CodeGen::DominatingLLVMValue::needsSaving().
restore()
static type clang::CodeGen::DominatingValue< Address >::restore (CodeGenFunction & CGF, saved_type value) inline static
Definition at line 191 of file CodeGenFunction.h.
References clang::CodeGen::DominatingValue< Address >::saved_type::Alignment, clang::CodeGen::DominatingValue< Address >::saved_type::ElementType, clang::CodeGen::DominatingLLVMValue::restore(), and clang::CodeGen::DominatingValue< Address >::saved_type::SavedValue.
save()
static saved_type clang::CodeGen::DominatingValue< Address >::save (CodeGenFunction & CGF, type value) inline static
Definition at line 187 of file CodeGenFunction.h.
References clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), and clang::CodeGen::DominatingLLVMValue::save().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h