clang: clang::TargetInfo::ConstraintInfo Struct Reference
clang::TargetInfo::ConstraintInfo Struct Reference
#include "clang/Basic/TargetInfo.h"
Public Types
enum {
CI_None = 0x00 , CI_AllowsMemory = 0x01 , CI_AllowsRegister = 0x02 , CI_ReadWrite = 0x04 ,
CI_HasMatchingInput = 0x08 , CI_ImmediateConstant = 0x10 , CI_EarlyClobber = 0x20
}
Public Member Functions
ConstraintInfo (StringRef ConstraintStr, StringRef Name)
const std::string & getConstraintStr () const
const std::string & getName () const
bool isReadWrite () const
bool earlyClobber ()
bool allowsRegister () const
bool allowsMemory () const
bool hasMatchingInput () const
Return true if this output operand has a matching (tied) input operand.
bool hasTiedOperand () const
Return true if this input operand is a matching constraint that ties it to an output operand.
unsigned getTiedOperand () const
bool requiresImmediateConstant () const
bool isValidAsmImmediate (const llvm::APInt &Value) const
void setIsReadWrite ()
void setEarlyClobber ()
void setAllowsMemory ()
void setAllowsRegister ()
void setHasMatchingInput ()
void setRequiresImmediate (int Min, int Max)
void setRequiresImmediate (llvm::ArrayRef< int > Exacts)
void setRequiresImmediate (int Exact)
void setRequiresImmediate ()
void setTiedOperand (unsigned N, ConstraintInfo &Output)
Indicate that this is an input operand that is tied to the specified output operand.
Public Attributes
unsigned Flags
int TiedOperand
struct {
int Min
int Max
bool isConstrained
} ImmRange
llvm::SmallSet< int, 4 > ImmSet
std::string ConstraintStr
std::string Name
Detailed Description
Definition at line 1035 of file TargetInfo.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
CI_None
CI_AllowsMemory
CI_AllowsRegister
CI_ReadWrite
CI_HasMatchingInput
CI_ImmediateConstant
CI_EarlyClobber
Definition at line 1036 of file TargetInfo.h.
Constructor & Destructor Documentation
ConstraintInfo()
clang::TargetInfo::ConstraintInfo::ConstraintInfo (StringRef ConstraintStr, StringRef Name) inline
Definition at line 1057 of file TargetInfo.h.
References ImmRange.
Member Function Documentation
allowsMemory()
bool clang::TargetInfo::ConstraintInfo::allowsMemory () const inline
Definition at line 1069 of file TargetInfo.h.
References CI_AllowsMemory, and Flags.
Referenced by clang::Sema::ActOnGCCAsmStmt(), and clang::TargetInfo::validateOutputConstraint().
allowsRegister()
bool clang::TargetInfo::ConstraintInfo::allowsRegister () const inline
Definition at line 1068 of file TargetInfo.h.
References CI_AllowsRegister, and Flags.
Referenced by clang::Sema::ActOnGCCAsmStmt(), AddVariableConstraints(), and clang::TargetInfo::validateOutputConstraint().
earlyClobber()
bool clang::TargetInfo::ConstraintInfo::earlyClobber () inline
Definition at line 1067 of file TargetInfo.h.
References CI_EarlyClobber, and Flags.
Referenced by clang::TargetInfo::validateOutputConstraint().
getConstraintStr()
const std::string & clang::TargetInfo::ConstraintInfo::getConstraintStr () const inline
Definition at line 1064 of file TargetInfo.h.
References ConstraintStr.
Referenced by clang::Sema::ActOnGCCAsmStmt(), checkExprMemoryConstraintCompat(), and clang::TargetInfo::validateOutputConstraint().
getName()
const std::string & clang::TargetInfo::ConstraintInfo::getName () const inline
Definition at line 1065 of file TargetInfo.h.
References Name.
getTiedOperand()
unsigned clang::TargetInfo::ConstraintInfo::getTiedOperand () const inline
Definition at line 1081 of file TargetInfo.h.
References hasTiedOperand(), and TiedOperand.
Referenced by clang::Sema::ActOnGCCAsmStmt(), and clang::TargetInfo::validateInputConstraint().
hasMatchingInput()
bool clang::TargetInfo::ConstraintInfo::hasMatchingInput () const inline
Return true if this output operand has a matching (tied) input operand.
Definition at line 1073 of file TargetInfo.h.
References CI_HasMatchingInput, and Flags.
hasTiedOperand()
bool clang::TargetInfo::ConstraintInfo::hasTiedOperand () const inline
Return true if this input operand is a matching constraint that ties it to an output operand.
If this returns true then getTiedOperand will indicate which output operand this is tied to.
Definition at line 1080 of file TargetInfo.h.
References TiedOperand.
Referenced by clang::Sema::ActOnGCCAsmStmt(), getTiedOperand(), and clang::TargetInfo::validateInputConstraint().
isReadWrite()
bool clang::TargetInfo::ConstraintInfo::isReadWrite () const inline
Definition at line 1066 of file TargetInfo.h.
References CI_ReadWrite, and Flags.
Referenced by clang::TargetInfo::validateOutputConstraint().
isValidAsmImmediate()
bool clang::TargetInfo::ConstraintInfo::isValidAsmImmediate (const llvm::APInt & Value) const inline
Definition at line 1089 of file TargetInfo.h.
References ImmRange, and ImmSet.
Referenced by clang::Sema::ActOnGCCAsmStmt().
requiresImmediateConstant()
bool clang::TargetInfo::ConstraintInfo::requiresImmediateConstant () const inline
Definition at line 1086 of file TargetInfo.h.
References CI_ImmediateConstant, and Flags.
Referenced by clang::Sema::ActOnGCCAsmStmt().
setAllowsMemory()
void clang::TargetInfo::ConstraintInfo::setAllowsMemory () inline
Definition at line 1098 of file TargetInfo.h.
References CI_AllowsMemory, and Flags.
Referenced by clang::targets::AArch64TargetInfo::validateAsmConstraint(), clang::targets::ARMTargetInfo::validateAsmConstraint(), clang::targets::LoongArchTargetInfo::validateAsmConstraint(), clang::targets::M68kTargetInfo::validateAsmConstraint(), clang::targets::MipsTargetInfo::validateAsmConstraint(), clang::targets::PPCTargetInfo::validateAsmConstraint(), clang::targets::RISCVTargetInfo::validateAsmConstraint(), clang::targets::SystemZTargetInfo::validateAsmConstraint(), clang::TargetInfo::validateInputConstraint(), and clang::TargetInfo::validateOutputConstraint().
setAllowsRegister()
void clang::TargetInfo::ConstraintInfo::setAllowsRegister () inline
Definition at line 1099 of file TargetInfo.h.
References CI_AllowsRegister, and Flags.
Referenced by clang::targets::AArch64TargetInfo::validateAsmConstraint(), clang::targets::AMDGPUTargetInfo::validateAsmConstraint(), clang::targets::ARMTargetInfo::validateAsmConstraint(), clang::targets::AVRTargetInfo::validateAsmConstraint(), clang::targets::BPFTargetInfo::validateAsmConstraint(), clang::targets::CSKYTargetInfo::validateAsmConstraint(), clang::targets::HexagonTargetInfo::validateAsmConstraint(), clang::targets::LoongArchTargetInfo::validateAsmConstraint(), clang::targets::M68kTargetInfo::validateAsmConstraint(), clang::targets::MipsTargetInfo::validateAsmConstraint(), clang::targets::NVPTXTargetInfo::validateAsmConstraint(), clang::targets::PPCTargetInfo::validateAsmConstraint(), clang::targets::RISCVTargetInfo::validateAsmConstraint(), clang::targets::SparcTargetInfo::validateAsmConstraint(), clang::targets::SystemZTargetInfo::validateAsmConstraint(), clang::targets::VETargetInfo::validateAsmConstraint(), clang::targets::X86TargetInfo::validateAsmConstraint(), clang::TargetInfo::validateInputConstraint(), and clang::TargetInfo::validateOutputConstraint().
setEarlyClobber()
void clang::TargetInfo::ConstraintInfo::setEarlyClobber () inline
Definition at line 1097 of file TargetInfo.h.
References CI_EarlyClobber, and Flags.
Referenced by clang::TargetInfo::validateOutputConstraint().
setHasMatchingInput()
void clang::TargetInfo::ConstraintInfo::setHasMatchingInput () inline
Definition at line 1100 of file TargetInfo.h.
References CI_HasMatchingInput, and Flags.
Referenced by setTiedOperand().
setIsReadWrite()
void clang::TargetInfo::ConstraintInfo::setIsReadWrite () inline
Definition at line 1096 of file TargetInfo.h.
References CI_ReadWrite, and Flags.
Referenced by clang::TargetInfo::validateOutputConstraint().
setRequiresImmediate() [1/4]
void clang::TargetInfo::ConstraintInfo::setRequiresImmediate () inline
Definition at line 1116 of file TargetInfo.h.
References CI_ImmediateConstant, and Flags.
setRequiresImmediate() [2/4]
void clang::TargetInfo::ConstraintInfo::setRequiresImmediate (int Exact) inline
Definition at line 1112 of file TargetInfo.h.
References CI_ImmediateConstant, Flags, and ImmSet.
setRequiresImmediate() [3/4]
void clang::TargetInfo::ConstraintInfo::setRequiresImmediate (int Min, int Max) inline
Definition at line 1101 of file TargetInfo.h.
References CI_ImmediateConstant, Flags, ImmRange, Max, and Min.
Referenced by clang::targets::AMDGPUTargetInfo::validateAsmConstraint(), clang::targets::ARMTargetInfo::validateAsmConstraint(), clang::targets::AVRTargetInfo::validateAsmConstraint(), clang::targets::LoongArchTargetInfo::validateAsmConstraint(), clang::targets::M68kTargetInfo::validateAsmConstraint(), clang::targets::RISCVTargetInfo::validateAsmConstraint(), clang::targets::X86TargetInfo::validateAsmConstraint(), and clang::TargetInfo::validateInputConstraint().
setRequiresImmediate() [4/4]
void clang::TargetInfo::ConstraintInfo::setRequiresImmediate (llvm::ArrayRef< int > Exacts) inline
Definition at line 1107 of file TargetInfo.h.
References CI_ImmediateConstant, Flags, and ImmSet.
setTiedOperand()
void clang::TargetInfo::ConstraintInfo::setTiedOperand (unsigned N, ConstraintInfo & Output) inline
Indicate that this is an input operand that is tied to the specified output operand.
Copy over the various constraint information from the output.
Definition at line 1124 of file TargetInfo.h.
References Flags, N, setHasMatchingInput(), and TiedOperand.
Referenced by clang::TargetInfo::validateInputConstraint().
Member Data Documentation
ConstraintStr
std::string clang::TargetInfo::ConstraintInfo::ConstraintStr
Definition at line 1054 of file TargetInfo.h.
Referenced by getConstraintStr(), clang::targets::X86TargetInfo::validateAsmConstraint(), and clang::TargetInfo::validateInputConstraint().
Flags
unsigned clang::TargetInfo::ConstraintInfo::Flags
Definition at line 1045 of file TargetInfo.h.
Referenced by allowsMemory(), allowsRegister(), earlyClobber(), hasMatchingInput(), isReadWrite(), requiresImmediateConstant(), setAllowsMemory(), setAllowsRegister(), setEarlyClobber(), setHasMatchingInput(), setIsReadWrite(), setRequiresImmediate(), setRequiresImmediate(), setRequiresImmediate(), setRequiresImmediate(), and setTiedOperand().
[struct]
struct { ... } clang::TargetInfo::ConstraintInfo::ImmRange
Referenced by ConstraintInfo(), isValidAsmImmediate(), and setRequiresImmediate().
ImmSet
llvm::SmallSet<int, 4> clang::TargetInfo::ConstraintInfo::ImmSet
Definition at line 1052 of file TargetInfo.h.
Referenced by isValidAsmImmediate(), setRequiresImmediate(), and setRequiresImmediate().
isConstrained
bool clang::TargetInfo::ConstraintInfo::isConstrained
Definition at line 1050 of file TargetInfo.h.
Max
int clang::TargetInfo::ConstraintInfo::Max
Definition at line 1049 of file TargetInfo.h.
Referenced by setRequiresImmediate().
Min
int clang::TargetInfo::ConstraintInfo::Min
Definition at line 1048 of file TargetInfo.h.
Referenced by setRequiresImmediate().
Name
std::string clang::TargetInfo::ConstraintInfo::Name
Definition at line 1055 of file TargetInfo.h.
Referenced by getName().
TiedOperand
int clang::TargetInfo::ConstraintInfo::TiedOperand
Definition at line 1046 of file TargetInfo.h.
Referenced by getTiedOperand(), hasTiedOperand(), and setTiedOperand().
The documentation for this struct was generated from the following file:
include/clang/Basic/TargetInfo.h