clang: clang::DarwinSDKInfo::OSEnvPair Struct Reference
clang::DarwinSDKInfo::OSEnvPair Struct Reference
A value that describes two os-environment pairs that can be used as a key to the version map in the SDK.
#include "clang/Basic/DarwinSDKInfo.h"
Public Types
using StorageType = uint64_t
Public Member Functions
constexpr OSEnvPair (llvm::Triple::OSType FromOS, llvm::Triple::EnvironmentType FromEnv, llvm::Triple::OSType ToOS, llvm::Triple::EnvironmentType ToEnv)
Static Public Member Functions
static constexpr OSEnvPair macOStoMacCatalystPair ()
Returns the os-environment mapping pair that's used to represent the macOS -> Mac Catalyst version mapping.
static constexpr OSEnvPair macCatalystToMacOSPair ()
Returns the os-environment mapping pair that's used to represent the Mac Catalyst -> macOS version mapping.
static constexpr OSEnvPair iOStoWatchOSPair ()
Returns the os-environment mapping pair that's used to represent the iOS -> watchOS version mapping.
static constexpr OSEnvPair iOStoTvOSPair ()
Returns the os-environment mapping pair that's used to represent the iOS -> tvOS version mapping.
Friends
class DarwinSDKInfo
Detailed Description
A value that describes two os-environment pairs that can be used as a key to the version map in the SDK.
Definition at line 33 of file DarwinSDKInfo.h.
Member Typedef Documentation
StorageType
using clang::DarwinSDKInfo::OSEnvPair::StorageType = uint64_t
Definition at line 35 of file DarwinSDKInfo.h.
Constructor & Destructor Documentation
OSEnvPair()
clang::DarwinSDKInfo::OSEnvPair::OSEnvPair (llvm::Triple::OSType FromOS, llvm::Triple::EnvironmentType FromEnv, llvm::Triple::OSType ToOS, llvm::Triple::EnvironmentType ToEnv) inline constexpr
Definition at line 37 of file DarwinSDKInfo.h.
Referenced by iOStoTvOSPair(), iOStoWatchOSPair(), macCatalystToMacOSPair(), and macOStoMacCatalystPair().
Member Function Documentation
iOStoTvOSPair()
static constexpr OSEnvPair clang::DarwinSDKInfo::OSEnvPair::iOStoTvOSPair () inline static constexpr
Returns the os-environment mapping pair that's used to represent the iOS -> tvOS version mapping.
Definition at line 70 of file DarwinSDKInfo.h.
References OSEnvPair().
Referenced by handleAvailabilityAttr().
iOStoWatchOSPair()
static constexpr OSEnvPair clang::DarwinSDKInfo::OSEnvPair::iOStoWatchOSPair () inline static constexpr
Returns the os-environment mapping pair that's used to represent the iOS -> watchOS version mapping.
Definition at line 63 of file DarwinSDKInfo.h.
References OSEnvPair().
Referenced by handleAvailabilityAttr().
macCatalystToMacOSPair()
static constexpr OSEnvPair clang::DarwinSDKInfo::OSEnvPair::macCatalystToMacOSPair () inline static constexpr
Returns the os-environment mapping pair that's used to represent the Mac Catalyst -> macOS version mapping.
Definition at line 56 of file DarwinSDKInfo.h.
References OSEnvPair().
Referenced by clang::DarwinSDKInfo::parseDarwinSDKSettingsJSON().
macOStoMacCatalystPair()
static constexpr OSEnvPair clang::DarwinSDKInfo::OSEnvPair::macOStoMacCatalystPair () inline static constexpr
Returns the os-environment mapping pair that's used to represent the macOS -> Mac Catalyst version mapping.
Definition at line 49 of file DarwinSDKInfo.h.
References OSEnvPair().
Referenced by clang::driver::toolchains::Darwin::addClangCC1ASTargetOptions(), clang::driver::toolchains::Darwin::addPlatformVersionArgs(), handleAvailabilityAttr(), and clang::DarwinSDKInfo::parseDarwinSDKSettingsJSON().
Friends And Related Symbol Documentation
DarwinSDKInfo
friend class DarwinSDKInfo friend
Definition at line 78 of file DarwinSDKInfo.h.
The documentation for this struct was generated from the following file:
include/clang/Basic/DarwinSDKInfo.h