clang: clang::AtomicConstraint Struct Reference
clang::AtomicConstraint Struct Reference
#include "clang/Sema/SemaConcept.h"
Public Member Functions
AtomicConstraint (Sema &S, const Expr *ConstraintExpr)
bool hasMatchingParameterMapping (ASTContext &C, const AtomicConstraint &Other) const
bool subsumes (ASTContext &C, const AtomicConstraint &Other) const
Public Attributes
const Expr * ConstraintExpr
std::optional< ArrayRef< TemplateArgumentLoc > > ParameterMapping
Detailed Description
Definition at line 29 of file SemaConcept.h.
Constructor & Destructor Documentation
AtomicConstraint()
clang::AtomicConstraint::AtomicConstraint (Sema & S, const Expr * ConstraintExpr) inline
Definition at line 33 of file SemaConcept.h.
Member Function Documentation
hasMatchingParameterMapping()
bool clang::AtomicConstraint::hasMatchingParameterMapping (ASTContext & C, const AtomicConstraint & Other) const inline
Definition at line 36 of file SemaConcept.h.
References clang::C, getArgument(), and ParameterMapping.
Referenced by clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), and subsumes().
subsumes()
bool clang::AtomicConstraint::subsumes (ASTContext & C, const AtomicConstraint & Other) const inline
Definition at line 57 of file SemaConcept.h.
References clang::C, ConstraintExpr, and hasMatchingParameterMapping().
Referenced by clang::Sema::IsAtLeastAsConstrained(), and clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic().
Member Data Documentation
ConstraintExpr
const Expr* clang::AtomicConstraint::ConstraintExpr
Definition at line 30 of file SemaConcept.h.
Referenced by clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), substituteParameterMappings(), and subsumes().
ParameterMapping
std::optional<ArrayRef<TemplateArgumentLoc> > clang::AtomicConstraint::ParameterMapping
Definition at line 31 of file SemaConcept.h.
Referenced by hasMatchingParameterMapping(), and substituteParameterMappings().
The documentation for this struct was generated from the following file:
include/clang/Sema/SemaConcept.h