clang: clang::ento::NodeBuilderContext Struct Reference
clang::ento::NodeBuilderContext Struct Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
Public Member Functions
NodeBuilderContext (const CoreEngine &E, const CFGBlock *B, const LocationContext *L)
NodeBuilderContext (const CoreEngine &E, const CFGBlock *B, ExplodedNode *N)
const CFGBlock * getBlock () const
Return the CFGBlock associated with this builder.
unsigned blockCount () const
Returns the number of times the current basic block has been visited on the exploded graph path.
Public Attributes
const CoreEngine & Eng
const CFGBlock * Block
const LocationContext * LC
Detailed Description
Definition at line 203 of file CoreEngine.h.
Constructor & Destructor Documentation
NodeBuilderContext() [1/2]
clang::ento::NodeBuilderContext::NodeBuilderContext (const CoreEngine & E, const CFGBlock * B, const LocationContext * L) inline
Definition at line 208 of file CoreEngine.h.
NodeBuilderContext() [2/2]
clang::ento::NodeBuilderContext::NodeBuilderContext (const CoreEngine & E, const CFGBlock * B, ExplodedNode * N) inline
Definition at line 214 of file CoreEngine.h.
Member Function Documentation
blockCount()
unsigned clang::ento::NodeBuilderContext::blockCount () const inline
Returns the number of times the current basic block has been visited on the exploded graph path.
Definition at line 222 of file CoreEngine.h.
References Block, Eng, clang::CFGBlock::getBlockID(), clang::LocationContext::getStackFrame(), and LC.
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::CheckerContext::blockCount(), clang::ento::ExprEngine::computeObjectUnderConstruction(), populateObjCForDestinationSet(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::Visit(), clang::ento::ExprEngine::VisitAtomicExpr(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitBlockExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXCatchStmt(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitGuardedExpr(), and clang::ento::ExprEngine::VisitIncrementDecrementOperator().
getBlock()
const CFGBlock * clang::ento::NodeBuilderContext::getBlock () const inline
Return the CFGBlock associated with this builder.
Definition at line 218 of file CoreEngine.h.
References Block.
Referenced by clang::ento::CheckerContext::getBlockID(), clang::ento::ExprEngine::getCFGElementRef(), clang::ento::ExprEngine::getCurrentCFGElement(), clang::ento::ExprEngine::processBranch(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessImplicitDtor(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessLoopExit(), clang::ento::ExprEngine::ProcessNewAllocator(), clang::ento::ExprEngine::ProcessStmt(), and clang::ento::ExprEngine::Visit().
Member Data Documentation
Block
const CFGBlock* clang::ento::NodeBuilderContext::Block
Definition at line 205 of file CoreEngine.h.
Referenced by blockCount(), clang::ento::BranchNodeBuilder::generateNode(), and getBlock().
Eng
const CoreEngine& clang::ento::NodeBuilderContext::Eng
Definition at line 204 of file CoreEngine.h.
Referenced by blockCount(), expandGraphWithCheckers(), and clang::ento::NodeBuilder::generateNodeImpl().
LC
const LocationContext* clang::ento::NodeBuilderContext::LC
Definition at line 206 of file CoreEngine.h.
Referenced by blockCount().
The documentation for this struct was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h