clang: clang::SanitizerSet Struct Reference
clang::SanitizerSet Struct Reference
#include "clang/Basic/Sanitizers.h"
Public Member Functions
bool has (SanitizerMask K) const
Check if a certain (single) sanitizer is enabled.
bool hasOneOf (SanitizerMask K) const
Check if one or more sanitizers are enabled.
void set (SanitizerMask K, bool Value)
Enable or disable a certain (single) sanitizer.
void clear (SanitizerMask K=SanitizerKind::All)
Disable the sanitizers specified in K.
bool empty () const
Returns true if no sanitizers are enabled.
Public Attributes
SanitizerMask Mask
Bitmask of enabled sanitizers.
Detailed Description
Definition at line 157 of file Sanitizers.h.
Member Function Documentation
clear()
void clang::SanitizerSet::clear (SanitizerMask K = SanitizerKind::All) inline
Disable the sanitizers specified in K.
Definition at line 174 of file Sanitizers.h.
References Mask.
Referenced by checkLanguageOptions(), and clang::CompilerInvocation::getModuleHash().
empty()
bool clang::SanitizerSet::empty () const inline
Returns true if no sanitizers are enabled.
Definition at line 177 of file Sanitizers.h.
References Mask.
Referenced by clang::driver::SanitizerArgs::addArgs(), clang::CompilerInvocation::getModuleHash(), and clang::driver::SanitizerArgs::hasAnySanitizer().
has()
bool clang::SanitizerSet::has (SanitizerMask K) const inline
Check if a certain (single) sanitizer is enabled.
Definition at line 159 of file Sanitizers.h.
References clang::SanitizerMask::isPowerOf2(), and Mask.
Referenced by clang::driver::SanitizerArgs::addArgs(), addKCFIPass(), addSanitizers(), clang::CodeGen::CodeGenModule::CodeGenModule(), clang::CodeGen::CodeGenModule::CreateFunctionTypeMetadataForIcall(), emitPointerArithmetic(), EmitPointerWithAlignment(), clang::targets::getDarwinDefines(), clang::driver::SanitizerArgs::hasMemtagGlobals(), clang::driver::SanitizerArgs::hasMemtagHeap(), clang::driver::SanitizerArgs::hasMemtagStack(), clang::driver::SanitizerArgs::hasShadowCallStack(), clang::CodeGen::CodeGenModule::NeedAllVtablesTypeId(), clang::driver::SanitizerArgs::needsAsanRt(), clang::driver::SanitizerArgs::needsDfsanRt(), clang::driver::SanitizerArgs::needsFuzzer(), clang::driver::SanitizerArgs::needsHwasanRt(), clang::driver::SanitizerArgs::needsLsanRt(), clang::driver::SanitizerArgs::needsMsanRt(), clang::driver::SanitizerArgs::needsScudoRt(), clang::driver::SanitizerArgs::needsTsanRt(), clang::CodeGen::CodeGenModule::Release(), clang::CodeGen::CodeGenVTables::RemoveHwasanMetadata(), clang::CodeGen::SanitizerMetadata::reportGlobal(), and shouldEmitLifetimeMarkers().
hasOneOf()
bool clang::SanitizerSet::hasOneOf (SanitizerMask K) const inline
Check if one or more sanitizers are enabled.
Definition at line 165 of file Sanitizers.h.
References Mask.
Referenced by clang::driver::SanitizerArgs::addArgs(), isAsanHwasanOrMemTag(), and clang::CodeGen::SanitizerMetadata::reportGlobal().
set()
void clang::SanitizerSet::set (SanitizerMask K, bool Value) inline
Enable or disable a certain (single) sanitizer.
Definition at line 168 of file Sanitizers.h.
References clang::SanitizerMask::isPowerOf2(), and Mask.
Member Data Documentation
Mask
SanitizerMask clang::SanitizerSet::Mask
Bitmask of enabled sanitizers.
Definition at line 180 of file Sanitizers.h.
Referenced by clang::driver::SanitizerArgs::addArgs(), checkLanguageOptions(), clear(), empty(), clang::CompilerInvocation::getModuleHash(), has(), hasOneOf(), clang::RecordDecl::mayInsertExtraPadding(), clang::driver::SanitizerArgs::needsCfiDiagRt(), clang::driver::SanitizerArgs::needsCfiRt(), clang::driver::SanitizerArgs::needsLTO(), clang::driver::SanitizerArgs::needsUbsanRt(), clang::driver::SanitizerArgs::needsUnwindTables(), clang::CodeGen::SanitizerMetadata::reportGlobal(), clang::driver::SanitizerArgs::requiresPIE(), clang::driver::SanitizerArgs::SanitizerArgs(), and set().
The documentation for this struct was generated from the following file:
include/clang/Basic/Sanitizers.h