clang: lib/StaticAnalyzer/Checkers/UndefResultChecker.cpp File Reference
UndefResultChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicExtent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool isArrayIndexOutOfBounds (CheckerContext &C, const Expr *Ex)
static bool isShiftOverflow (const BinaryOperator *B, CheckerContext &C)
static bool isLeftShiftResultUnrepresentable (const BinaryOperator *B, CheckerContext &C)
Function Documentation
isArrayIndexOutOfBounds()
static bool isArrayIndexOutOfBounds (CheckerContext & C, const Expr * Ex) static
Definition at line 38 of file UndefResultChecker.cpp.
References clang::C, clang::ento::SVal::castAs(), clang::ento::getDynamicElementCount(), clang::ento::ElementRegion::getIndex(), clang::ento::SubRegion::getSuperRegion(), clang::ento::ElementRegion::getValueType(), and clang::ento::DefinedSVal::isValid().
isLeftShiftResultUnrepresentable()
static bool isLeftShiftResultUnrepresentable (const BinaryOperator * B, CheckerContext & C) static
Definition at line 66 of file UndefResultChecker.cpp.
References clang::C, clang::ento::SValBuilder::getKnownValue(), clang::BinaryOperator::getLHS(), and clang::BinaryOperator::getRHS().
isShiftOverflow()
static bool isShiftOverflow (const BinaryOperator * B, CheckerContext & C) static
Definition at line 61 of file UndefResultChecker.cpp.
References clang::C, clang::BinaryOperator::getLHS(), clang::BinaryOperator::getRHS(), and clang::Expr::getType().