clang: lib/Analysis/UnsafeBufferUsage.cpp File Reference
UnsafeBufferUsage.cpp File Reference
#include "clang/Analysis/Analyses/UnsafeBufferUsage.h"
#include "clang/AST/Decl.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/Preprocessor.h"
#include "llvm/ADT/SmallVector.h"
#include <memory>
#include <optional>
#include <sstream>
#include <queue>
#include "clang/Analysis/Analyses/UnsafeBufferUsageGadgets.def"
Classes
class clang::ast_matchers::MatchDescendantVisitor
class UPCPreIncrementGadget
class DerefSimplePtrArithFixableGadget
struct CompareNode< NodeTy >
struct WarningGadgetSets
struct FixableGadgetSets
Namespaces
namespace clang
namespace clang::ast_matchers
Macros
#define GADGET(x)
#define NEXT ++numFound
#define FIXABLE_GADGET(name)
#define WARNING_GADGET(name)
#define WARNING_GADGET(x)
#define FIXABLE_GADGET(x)
Functions
static auto clang::ast_matchers::hasPointerType ()
static auto clang::ast_matchers::hasArrayType ()
clang::ast_matchers::AST_MATCHER_P (Stmt, forEachDescendantEvaluatedStmt, internal::Matcher< Stmt >, innerMatcher)
clang::ast_matchers::AST_MATCHER_P (Stmt, forEachDescendantStmt, internal::Matcher< Stmt >, innerMatcher)
clang::ast_matchers::AST_MATCHER_P (Stmt, notInSafeBufferOptOut, const UnsafeBufferUsageHandler *, Handler)
clang::ast_matchers::AST_MATCHER_P (CastExpr, castSubExpr, internal::Matcher< Expr >, innerMatcher)
clang::ast_matchers::AST_MATCHER (UnaryOperator, isPreInc)
static auto clang::ast_matchers::isInUnspecifiedLvalueContext (internal::Matcher< Expr > innerMatcher)
static internal::Matcher< Stmt > clang::ast_matchers::isInUnspecifiedPointerContext (internal::Matcher< Stmt > InnerMatcher)
static internal::Matcher< Stmt > clang::ast_matchers::isInUnspecifiedUntypedContext (internal::Matcher< Stmt > InnerMatcher)
static std::tuple< FixableGadgetList, WarningGadgetList, DeclUseTracker > findGadgets (const Decl *D, const UnsafeBufferUsageHandler &Handler, bool EmitSuggestions)
Scan the function and return a list of gadgets found with provided kits.
static WarningGadgetSets groupWarningGadgetsByVar (const WarningGadgetList &AllUnsafeOperations)
static FixableGadgetSets groupFixablesByVar (FixableGadgetList &&AllFixableOperations)
static std::optional< FixItList > fixUPCAddressofArraySubscriptWithSpan (const UnaryOperator *Node)
static StringRef getEndOfLine ()
std::string getUserFillPlaceHolder (StringRef HintTextToUser="placeholder")
static std::string getAPIntText (APInt Val)
template<typename NodeTy >
static std::optional< SourceLocation > getEndCharLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
template<typename NodeTy >
static std::optional< SourceLocation > getPastLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< StringRef > getExprText (const Expr *E, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< StringRef > getRangeText (SourceRange SR, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< std::string > getPointeeTypeText (const ParmVarDecl *VD, const SourceManager &SM, const LangOptions &LangOpts, std::optional< Qualifiers > *QualifiersToAppend)
static std::optional< StringRef > getFunNameText (const FunctionDecl *FD, const SourceManager &SM, const LangOptions &LangOpts)
static FixItList populateInitializerFixItWithSpan (const Expr *Init, ASTContext &Ctx, const StringRef UserFillPlaceHolder)
static FixItList fixVarDeclWithSpan (const VarDecl *D, ASTContext &Ctx, const StringRef UserFillPlaceHolder)
static bool hasConflictingOverload (const FunctionDecl *FD)
static std::optional< FixItList > createOverloadsForFixedParams (unsigned ParmIdx, StringRef NewTyText, const FunctionDecl *FD, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixParamWithSpan (const ParmVarDecl *PVD, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariableWithSpan (const VarDecl *VD, const DeclUseTracker &Tracker, ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariable (const VarDecl *VD, Strategy::Kind K, const Decl *D, const DeclUseTracker &Tracker, ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static bool overlapWithMacro (const FixItList &FixIts)
static bool impossibleToFixForVar (const FixableGadgetSets &FixablesForAllVars, const Strategy &S, const VarDecl *Var)
static std::map< const VarDecl *, FixItList > getFixIts (FixableGadgetSets &FixablesForAllVars, const Strategy &S, ASTContext &Ctx, const Decl *D, const DeclUseTracker &Tracker, UnsafeBufferUsageHandler &Handler, const DefMapTy &VarGrpMap)
static Strategy getNaiveStrategy (const llvm::SmallVectorImpl< const VarDecl * > &UnsafeVars)
Macro Definition Documentation
FIXABLE_GADGET [1/2]
#define FIXABLE_GADGET (name)
Value:
  if (Result.Nodes.getNodeAs<Stmt>(#name)) {                                   \
    FixableGadgets.push_back(std::make_unique<name##Gadget>(Result));          \
    NEXT;                                                                      \
  }
Referenced by findGadgets().
FIXABLE_GADGET [2/2]
#define FIXABLE_GADGET (x)
Value:
            x ## Gadget::matcher().bind(#x),
GADGET
#define GADGET (x)
Value:
x,
Definition at line 306 of file UnsafeBufferUsage.cpp.
NEXT
#define NEXT ++numFound
Referenced by findGadgets().
WARNING_GADGET [1/2]
#define WARNING_GADGET (name)
Value:
  if (Result.Nodes.getNodeAs<Stmt>(#name)) {                                   \
    WarningGadgets.push_back(std::make_unique<name##Gadget>(Result));          \
    NEXT;                                                                      \
  }
Referenced by findGadgets().
WARNING_GADGET [2/2]
#define WARNING_GADGET (x)
Value:
          allOf(x ## Gadget::matcher().bind(#x),                               \
                notInSafeBufferOptOut(&Handler)),
Function Documentation
createOverloadsForFixedParams()
static std::optional< FixItList > createOverloadsForFixedParams (unsigned ParmIdx, StringRef NewTyText, const FunctionDecl * FD, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 1810 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::CreateInsertion(), clang::DeclaratorDecl::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::FunctionDecl::getBody(), getEndOfLine(), getFunNameText(), clang::NamedDecl::getIdentifier(), clang::ASTContext::getLangOpts(), clang::IdentifierInfo::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), getPastLoc(), getRangeText(), clang::ASTContext::getSourceManager(), clang::ParmVarDecl::getSourceRange(), clang::UnsafeBufferUsageHandler::getUnsafeBufferUsageAttributeTextAt(), getUserFillPlaceHolder(), hasConflictingOverload(), clang::Decl::isImplicit(), clang::FunctionDecl::param_begin(), clang::Redeclarable< decl_type >::redecls(), and SM.
Referenced by fixParamWithSpan().
findGadgets()
static std::tuple< FixableGadgetList, WarningGadgetList, DeclUseTracker > findGadgets (const Decl * D, const UnsafeBufferUsageHandler & Handler, bool EmitSuggestions) static
Scan the function and return a list of gadgets found with provided kits.
Definition at line 1000 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::MatchFinder::addMatcher(), clang::ast_matchers::allOf, clang::ast_matchers::anyOf, clang::ast_matchers::declRefExpr, clang::ast_matchers::declStmt, clang::ast_matchers::eachOf, FIXABLE_GADGET, clang::Decl::getASTContext(), clang::Decl::getBody(), clang::ast_matchers::hasArrayType(), clang::ast_matchers::hasPointerType(), clang::ast_matchers::MatchFinder::match(), NEXT, clang::ast_matchers::stmt, clang::ast_matchers::unless, clang::ast_matchers::varDecl, and WARNING_GADGET.
Referenced by clang::checkUnsafeBufferUsage().
fixParamWithSpan()
static FixItList fixParamWithSpan (const ParmVarDecl * PVD, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 1949 of file UnsafeBufferUsage.cpp.
References createOverloadsForFixedParams(), clang::FixItHint::CreateReplacement(), clang::Qualifiers::getAsString(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::ASTContext::getLangOpts(), clang::IdentifierInfo::getName(), getPointeeTypeText(), clang::QualType::getQualifiers(), clang::ASTContext::getSourceManager(), clang::ParmVarDecl::getSourceRange(), clang::ValueDecl::getType(), clang::ParmVarDecl::hasDefaultArg(), clang::QualType::hasQualifiers(), and clang::Type::isPointerType().
Referenced by fixVariable().
fixUPCAddressofArraySubscriptWithSpan()
static std::optional< FixItList > fixUPCAddressofArraySubscriptWithSpan (const UnaryOperator * Node) static
Definition at line 1559 of file UnsafeBufferUsage.cpp.
References clang::cast(), clang::FixItHint::CreateReplacement(), clang::Decl::getASTContext(), clang::DeclRefExpr::getDecl(), getExprText(), clang::Expr::getIntegerConstantExpr(), clang::ASTContext::getLangOpts(), clang::ASTContext::getSourceManager(), clang::DynTypedNode::getSourceRange(), Node, and SM.
fixVarDeclWithSpan()
static FixItList fixVarDeclWithSpan (const VarDecl * D, ASTContext & Ctx, const StringRef UserFillPlaceHolder) static
Definition at line 1728 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::CreateReplacement(), clang::QualType::getAsString(), clang::DeclaratorDecl::getBeginLoc(), getEndCharLoc(), clang::VarDecl::getInit(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getName(), clang::Type::getPointeeType(), clang::ASTContext::getSourceManager(), clang::ValueDecl::getType(), clang::QualType::isNull(), populateInitializerFixItWithSpan(), and SM.
Referenced by fixVariableWithSpan().
fixVariable()
static FixItList fixVariable (const VarDecl * VD, Strategy::Kind K, const Decl * D, const DeclUseTracker & Tracker, ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2031 of file UnsafeBufferUsage.cpp.
References fixParamWithSpan(), fixVariableWithSpan(), clang::ValueDecl::getType(), clang::VarDecl::isLocalVarDecl(), and clang::Type::isPointerType().
Referenced by getFixIts().
fixVariableWithSpan()
static FixItList fixVariableWithSpan (const VarDecl * VD, const DeclUseTracker & Tracker, ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2009 of file UnsafeBufferUsage.cpp.
References fixVarDeclWithSpan(), getUserFillPlaceHolder(), and clang::DeclStmt::isSingleDecl().
Referenced by fixVariable().
getAPIntText()
static std::string getAPIntText (APInt Val) static
Definition at line 1301 of file UnsafeBufferUsage.cpp.
Referenced by populateInitializerFixItWithSpan().
getEndCharLoc()
template<typename NodeTy > static std::optional< SourceLocation > getEndCharLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1312 of file UnsafeBufferUsage.cpp.
References clang::Lexer::MeasureTokenLength(), Node, and SM.
Referenced by fixVarDeclWithSpan(), UPCPreIncrementGadget::getFixits(), and populateInitializerFixItWithSpan().
getEndOfLine()
static StringRef getEndOfLine () static
Definition at line 1287 of file UnsafeBufferUsage.cpp.
Referenced by createOverloadsForFixedParams().
getExprText()
static std::optional< StringRef > getExprText (const Expr * E, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1338 of file UnsafeBufferUsage.cpp.
References clang::Stmt::getBeginLoc(), clang::CharSourceRange::getCharRange(), getPastLoc(), clang::Lexer::getSourceText(), and SM.
Referenced by fixUPCAddressofArraySubscriptWithSpan(), and populateInitializerFixItWithSpan().
getFixIts()
static std::map< const VarDecl *, FixItList > getFixIts (FixableGadgetSets & FixablesForAllVars, const Strategy & S, ASTContext & Ctx, const Decl * D, const DeclUseTracker & Tracker, UnsafeBufferUsageHandler & Handler, const DefMapTy & VarGrpMap) static
Definition at line 2105 of file UnsafeBufferUsage.cpp.
References clang::internal::anyConflict(), FixableGadgetSets::byVar, fixVariable(), clang::Decl::getASTContext(), clang::ASTContext::getSourceManager(), impossibleToFixForVar(), overlapWithMacro(), and V.
Referenced by clang::checkUnsafeBufferUsage().
getFunNameText()
static std::optional< StringRef > getFunNameText (const FunctionDecl * FD, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1418 of file UnsafeBufferUsage.cpp.
References clang::DeclarationNameInfo::getBeginLoc(), clang::NestedNameSpecifierLoc::getBeginLoc(), clang::DeclarationNameInfo::getEndLoc(), clang::Lexer::getLocForEndOfToken(), clang::FunctionDecl::getNameInfo(), clang::DeclaratorDecl::getQualifier(), clang::DeclaratorDecl::getQualifierLoc(), getRangeText(), and SM.
Referenced by createOverloadsForFixedParams().
getNaiveStrategy()
static Strategy getNaiveStrategy (const llvm::SmallVectorImpl< const VarDecl * > & UnsafeVars) static
Definition at line 2199 of file UnsafeBufferUsage.cpp.
Referenced by clang::checkUnsafeBufferUsage().
getPastLoc()
template<typename NodeTy > static std::optional< SourceLocation > getPastLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1325 of file UnsafeBufferUsage.cpp.
References clang::Lexer::getLocForEndOfToken(), Node, and SM.
Referenced by createOverloadsForFixedParams(), getExprText(), DerefSimplePtrArithFixableGadget::getFixits(), and populateInitializerFixItWithSpan().
getPointeeTypeText()
static std::optional< std::string > getPointeeTypeText (const ParmVarDecl * VD, const SourceManager & SM, const LangOptions & LangOpts, std::optional< Qualifiers > * QualifiersToAppend) static
Definition at line 1370 of file UnsafeBufferUsage.cpp.
References clang::TypeLoc::getBeginLoc(), clang::TypeLoc::getEndLoc(), clang::Decl::getLocation(), clang::Lexer::getLocForEndOfToken(), clang::TypeLoc::getNextTypeLoc(), clang::Type::getPointeeType(), clang::QualType::getQualifiers(), getRangeText(), clang::TypeLoc::getSourceRange(), clang::ValueDecl::getType(), clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::TypeLoc::getUnqualifiedLoc(), clang::QualType::hasQualifiers(), clang::Type::hasUnnamedOrLocalType(), clang::Type::isFunctionPointerType(), clang::Type::isPointerType(), clang::SourceLocation::isValid(), clang::SourceRange::isValid(), and SM.
Referenced by fixParamWithSpan().
getRangeText()
static std::optional< StringRef > getRangeText (SourceRange SR, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1352 of file UnsafeBufferUsage.cpp.
References clang::SourceRange::getBegin(), clang::CharSourceRange::getCharRange(), clang::SourceRange::getEnd(), clang::Lexer::getSourceText(), clang::Invalid, SM, and Text.
Referenced by createOverloadsForFixedParams(), getFunNameText(), and getPointeeTypeText().
getUserFillPlaceHolder()
std::string getUserFillPlaceHolder (StringRef HintTextToUser = "placeholder")
Definition at line 1293 of file UnsafeBufferUsage.cpp.
References s.
Referenced by createOverloadsForFixedParams(), and fixVariableWithSpan().
groupFixablesByVar()
static FixableGadgetSets groupFixablesByVar (FixableGadgetList && AllFixableOperations) static
Definition at line 1154 of file UnsafeBufferUsage.cpp.
References FixableGadgetSets::byVar, and clang::DeclRefExpr::getDecl().
Referenced by clang::checkUnsafeBufferUsage().
groupWarningGadgetsByVar()
static WarningGadgetSets groupWarningGadgetsByVar (const WarningGadgetList & AllUnsafeOperations) static
Definition at line 1126 of file UnsafeBufferUsage.cpp.
References WarningGadgetSets::byVar, clang::DeclRefExpr::getDecl(), and WarningGadgetSets::noVar.
Referenced by clang::checkUnsafeBufferUsage().
hasConflictingOverload()
static bool hasConflictingOverload (const FunctionDecl * FD) static
Definition at line 1766 of file UnsafeBufferUsage.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::DeclContextLookupResult::isSingleResult(), and clang::DeclContext::lookup().
Referenced by createOverloadsForFixedParams().
impossibleToFixForVar()
static bool impossibleToFixForVar (const FixableGadgetSets & FixablesForAllVars, const Strategy & S, const VarDecl * Var) static
Definition at line 2092 of file UnsafeBufferUsage.cpp.
References FixableGadgetSets::byVar.
Referenced by getFixIts().
overlapWithMacro()
static bool overlapWithMacro (const FixItList & FixIts) static
Definition at line 2080 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::RemoveRange.
Referenced by getFixIts().
populateInitializerFixItWithSpan()
static FixItList populateInitializerFixItWithSpan (const Expr * Init, ASTContext & Ctx, const StringRef UserFillPlaceHolder) static
Definition at line 1638 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), getAPIntText(), clang::ASTContext::getAsConstantArrayType(), getEndCharLoc(), getExprText(), clang::ASTContext::getLangOpts(), getPastLoc(), clang::ASTContext::getSourceManager(), and SM.
Referenced by fixVarDeclWithSpan().