clang: lib/AST/VTableBuilder.cpp File Reference
VTableBuilder.cpp File Reference
#include "clang/AST/VTableBuilder.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/RecordLayout.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstdio>
Macros
#define DUMP_OVERRIDERS 0
Functions
static VTableLayout::AddressPointsIndexMapTy MakeAddressPointIndices (const VTableLayout::AddressPointsMapTy &addressPoints, unsigned numVTables)
static std::unique_ptr< VTableLayout > CreateVTableLayout (const ItaniumVTableBuilder &Builder)
static void GroupNewVirtualOverloads (const CXXRecordDecl *RD, SmallVector< const CXXMethodDecl *, 10 > &VirtualMethods)
static bool isDirectVBase (const CXXRecordDecl *Base, const CXXRecordDecl *RD)
static void PrintBasePath (const VPtrInfo::BasePath &Path, raw_ostream &Out)
static void dumpMicrosoftThunkAdjustment (const ThunkInfo &TI, raw_ostream &Out, bool ContinueFirstLine)
static bool setsIntersect (const llvm::SmallPtrSet< const CXXRecordDecl *, 4 > &A, ArrayRef< const CXXRecordDecl * > B)
static bool rebucketPaths (VPtrInfoVector &Paths)
static bool extendPath (VPtrInfo &P)
static void findPathsToSubobject (ASTContext &Context, const ASTRecordLayout &MostDerivedLayout, const CXXRecordDecl *RD, CharUnits Offset, BaseSubobject IntroducingObject, FullPathTy &FullPath, std::list< FullPathTy > &Paths)
static void removeRedundantPaths (std::list< FullPathTy > &FullPaths)
static CharUnits getOffsetOfFullPath (ASTContext &Context, const CXXRecordDecl *RD, const FullPathTy &FullPath)
static const FullPathTy * selectBestPath (ASTContext &Context, const CXXRecordDecl *RD, const VPtrInfo &Info, std::list< FullPathTy > &FullPaths)
static void computeFullPathsForVFTables (ASTContext &Context, const CXXRecordDecl *RD, VPtrInfoVector &Paths)
static bool vfptrIsEarlierInMDC (const ASTRecordLayout &Layout, const MethodVFTableLocation &LHS, const MethodVFTableLocation &RHS)
Macro Definition Documentation
DUMP_OVERRIDERS
#define DUMP_OVERRIDERS 0
Definition at line 29 of file VTableBuilder.cpp.
Function Documentation
computeFullPathsForVFTables()
static void computeFullPathsForVFTables (ASTContext & Context, const CXXRecordDecl * RD, VPtrInfoVector & Paths) static
Definition at line 3565 of file VTableBuilder.cpp.
References findPathsToSubobject(), clang::ASTContext::getASTRecordLayout(), removeRedundantPaths(), selectBestPath(), and clang::CharUnits::Zero().
CreateVTableLayout()
static std::unique_ptr< VTableLayout > CreateVTableLayout (const ItaniumVTableBuilder & Builder) static
Definition at line 2315 of file VTableBuilder.cpp.
Referenced by clang::ItaniumVTableContext::createConstructionVTableLayout().
dumpMicrosoftThunkAdjustment()
static void dumpMicrosoftThunkAdjustment (const ThunkInfo & TI, raw_ostream & Out, bool ContinueFirstLine) static
Definition at line 3109 of file VTableBuilder.cpp.
References clang::QualType::getCanonicalType(), clang::FunctionDecl::getReturnType(), clang::ReturnAdjustment::isEmpty(), clang::ThisAdjustment::VirtualAdjustment::isEmpty(), clang::ThunkInfo::Method, clang::ReturnAdjustment::VirtualAdjustment::Microsoft, clang::ReturnAdjustment::NonVirtual, clang::ThunkInfo::Return, clang::ThunkInfo::This, clang::ReturnAdjustment::VirtualAdjustment::VBIndex, clang::ReturnAdjustment::VirtualAdjustment::VBPtrOffset, clang::ReturnAdjustment::Virtual, and clang::ThisAdjustment::Virtual.
extendPath()
static bool extendPath (VPtrInfo & P) static
Definition at line 3372 of file VTableBuilder.cpp.
References P.
Referenced by rebucketPaths().
findPathsToSubobject()
static void findPathsToSubobject (ASTContext & Context, const ASTRecordLayout & MostDerivedLayout, const CXXRecordDecl * RD, CharUnits Offset, BaseSubobject IntroducingObject, FullPathTy & FullPath, std::list< FullPathTy > & Paths) static
Definition at line 3422 of file VTableBuilder.cpp.
References clang::CXXRecordDecl::bases(), findPathsToSubobject(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getVBaseClassOffset(), and Offset.
Referenced by computeFullPathsForVFTables(), and findPathsToSubobject().
getOffsetOfFullPath()
static CharUnits getOffsetOfFullPath (ASTContext & Context, const CXXRecordDecl * RD, const FullPathTy & FullPath) static
Definition at line 3463 of file VTableBuilder.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::CXXRecordDecl::bases_end(), clang::CharUnits::fromQuantity(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::CXXBaseSpecifier::isVirtual(), Offset, and clang::CharUnits::Zero().
Referenced by selectBestPath().
GroupNewVirtualOverloads()
static void GroupNewVirtualOverloads (const CXXRecordDecl * RD, SmallVector< const CXXMethodDecl *, 10 > & VirtualMethods) static
Definition at line 2902 of file VTableBuilder.cpp.
References clang::DeclContext::decls(), clang::CXXMethodDecl::getCanonicalDecl(), and clang::VTableContextBase::hasVtableSlot().
isDirectVBase()
static bool isDirectVBase (const CXXRecordDecl * Base, const CXXRecordDecl * RD) static
Definition at line 2934 of file VTableBuilder.cpp.
References clang::CXXRecordDecl::bases().
MakeAddressPointIndices()
static VTableLayout::AddressPointsIndexMapTy MakeAddressPointIndices (const VTableLayout::AddressPointsMapTy & addressPoints, unsigned numVTables) static
Definition at line 2213 of file VTableBuilder.cpp.
PrintBasePath()
static void PrintBasePath (const VPtrInfo::BasePath & Path, raw_ostream & Out) static
Definition at line 3101 of file VTableBuilder.cpp.
rebucketPaths()
static bool rebucketPaths (VPtrInfoVector & Paths) static
Definition at line 3381 of file VTableBuilder.cpp.
References extendPath(), and clang::VPtrInfo::MangledPath.
removeRedundantPaths()
static void removeRedundantPaths (std::list< FullPathTy > & FullPaths) static
Definition at line 3448 of file VTableBuilder.cpp.
Referenced by computeFullPathsForVFTables().
selectBestPath()
static const FullPathTy * selectBestPath (ASTContext & Context, const CXXRecordDecl * RD, const VPtrInfo & Info, std::list< FullPathTy > & FullPaths) static
Definition at line 3495 of file VTableBuilder.cpp.
References clang::BaseSubobject::getBase(), clang::CXXMethodDecl::getCanonicalDecl(), clang::ASTContext::getDiagnostics(), clang::Decl::getLocation(), getOffsetOfFullPath(), clang::CXXMethodDecl::getParent(), clang::VTableContextBase::hasVtableSlot(), clang::VPtrInfo::IntroducingObject, clang::CXXRecordDecl::methods(), clang::DiagnosticsEngine::Report(), and clang::CharUnits::Zero().
Referenced by computeFullPathsForVFTables().
setsIntersect()
static bool setsIntersect (const llvm::SmallPtrSet< const CXXRecordDecl *, 4 > & A, ArrayRef< const CXXRecordDecl * > B) static
Definition at line 3263 of file VTableBuilder.cpp.
vfptrIsEarlierInMDC()
static bool vfptrIsEarlierInMDC (const ASTRecordLayout & Layout, const MethodVFTableLocation & LHS, const MethodVFTableLocation & RHS) static
Definition at line 3587 of file VTableBuilder.cpp.
References clang::ASTRecordLayout::getVBaseClassOffset(), clang::MethodVFTableLocation::VBase, and clang::MethodVFTableLocation::VFPtrOffset.