clang: lib/Serialization/ASTReaderDecl.cpp File Reference
ASTReaderDecl.cpp File Reference
#include "ASTCommon.h"
#include "ASTReaderInternals.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/AttrIterator.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclVisitor.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/LambdaCapture.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/Redeclarable.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/Type.h"
#include "clang/AST/UnresolvedSet.h"
#include "clang/Basic/AttrKinds.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/Lambda.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Linkage.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/PragmaKinds.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Sema/IdentifierResolver.h"
#include "clang/Serialization/ASTBitCodes.h"
#include "clang/Serialization/ASTRecordReader.h"
#include "clang/Serialization/ContinuousRangeMap.h"
#include "clang/Serialization/ModuleFile.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Bitstream/BitstreamReader.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <string>
#include <utility>
#include "clang/AST/CXXRecordDeclDefinitionBits.def"
#include "clang/Serialization/AttrPCHRead.inc"
#include "clang/AST/DeclNodes.inc"
Classes
class clang::ASTDeclReader
Namespaces
namespace clang
Dataflow Directional Tag Classes.
Macros
#define FIELD(Name, Width, Merge)
#define FIELD(Name, Width, Merge)
#define MERGE_OR(Field)
#define NO_MERGE(Field)
#define ABSTRACT_DECL(TYPE)
#define DECL(TYPE, BASE)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
#define ABSTRACT_DECL(TYPE)
#define DECL(TYPE, BASE)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
#define ABSTRACT_DECL(TYPE)
#define DECL(TYPE, BASE)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
#define ABSTRACT_DECL(TYPE)
#define DECL(TYPE, BASE)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
Functions
template<typename DeclT >
static llvm::iterator_range< MergedRedeclIterator< DeclT > > merged_redecls (DeclT *D)
template<typename T >
static T assert_cast (T t)
"Cast" to type T, asserting if we don't have an implicit conversion.
template<typename T >
static T assert_cast (...)
static bool allowODRLikeMergeInC (NamedDecl *ND)
ODR-like semantics for C/ObjC allow us to merge tag types and a structural check in Sema guarantees the types can be merged (see C11 6.2.7/1 or C89 6.1.2.6/1).
static bool isConsumerInterestedIn (ASTContext &Ctx, Decl *D, bool HasBody)
Determine whether the consumer will be interested in seeing this declaration (via HandleTopLevelDecl).
static bool isSameTemplateParameterList (const ASTContext &C, const TemplateParameterList *X, const TemplateParameterList *Y)
Determine whether two template parameter lists are similar enough that they may be used in declarations of the same template.
static bool isSameTemplateParameter (const NamedDecl *X, const NamedDecl *Y)
Determine whether two template parameters are similar enough that they may be used in declarations of the same template.
static NamespaceDecl * getNamespace (const NestedNameSpecifier *X)
static bool isSameQualifier (const NestedNameSpecifier *X, const NestedNameSpecifier *Y)
static bool hasSameOverloadableAttrs (const FunctionDecl *A, const FunctionDecl *B)
Determine whether the attributes we can overload on are identical for A and B.
static bool isSameEntity (NamedDecl *X, NamedDecl *Y)
Determine whether the two declarations refer to the same entity.pr.
static NamedDecl * getDeclForMerging (NamedDecl *Found, bool IsTypedefNameForLinkage)
Find the declaration that should be merged into, given the declaration found by name lookup.
static bool clang::isUndeducedReturnType (QualType T)
template<typename ParmDecl >
static bool inheritDefaultTemplateArgument (ASTContext &Context, ParmDecl *From, Decl *ToD)
Inherit the default template argument from From to To.
static void inheritDefaultTemplateArguments (ASTContext &Context, TemplateDecl *From, TemplateDecl *To)
template<typename DeclT , typename Fn >
static void forAllLaterRedecls (DeclT *D, Fn F)
Macro Definition Documentation
ABSTRACT_DECL [1/4]
#define ABSTRACT_DECL (TYPE)
ABSTRACT_DECL [2/4]
#define ABSTRACT_DECL (TYPE)
ABSTRACT_DECL [3/4]
#define ABSTRACT_DECL (TYPE)
ABSTRACT_DECL [4/4]
#define ABSTRACT_DECL (TYPE)
ACCESSSPEC [1/4]
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
ACCESSSPEC [2/4]
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
ACCESSSPEC [3/4]
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
ACCESSSPEC [4/4]
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
BINDING [1/4]
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BINDING [2/4]
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BINDING [3/4]
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BINDING [4/4]
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK [1/4]
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BLOCK [2/4]
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BLOCK [3/4]
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BLOCK [4/4]
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BUILTINTEMPLATE [1/4]
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
BUILTINTEMPLATE [2/4]
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
BUILTINTEMPLATE [3/4]
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
BUILTINTEMPLATE [4/4]
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CAPTURED [1/4]
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CAPTURED [2/4]
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CAPTURED [3/4]
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CAPTURED [4/4]
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION [1/4]
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION [2/4]
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION [3/4]
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION [4/4]
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE [1/4]
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATE [2/4]
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATE [3/4]
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATE [4/4]
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION [1/4]
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION [2/4]
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION [3/4]
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION [4/4]
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION [1/4]
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CLASSTEMPLATESPECIALIZATION [2/4]
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CLASSTEMPLATESPECIALIZATION [3/4]
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CLASSTEMPLATESPECIALIZATION [4/4]
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CONCEPT [1/4]
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONCEPT [2/4]
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONCEPT [3/4]
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONCEPT [4/4]
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONSTRUCTORUSINGSHADOW [1/4]
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CONSTRUCTORUSINGSHADOW [2/4]
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CONSTRUCTORUSINGSHADOW [3/4]
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CONSTRUCTORUSINGSHADOW [4/4]
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CXXCONSTRUCTOR [1/4]
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONSTRUCTOR [2/4]
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONSTRUCTOR [3/4]
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONSTRUCTOR [4/4]
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION [1/4]
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION [2/4]
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION [3/4]
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION [4/4]
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE [1/4]
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDEDUCTIONGUIDE [2/4]
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDEDUCTIONGUIDE [3/4]
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDEDUCTIONGUIDE [4/4]
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDESTRUCTOR [1/4]
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDESTRUCTOR [2/4]
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDESTRUCTOR [3/4]
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDESTRUCTOR [4/4]
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXMETHOD [1/4]
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXMETHOD [2/4]
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXMETHOD [3/4]
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXMETHOD [4/4]
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXRECORD [1/4]
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
CXXRECORD [2/4]
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
CXXRECORD [3/4]
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
CXXRECORD [4/4]
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
DECL [1/4]
#define DECL (TYPE, BASE)
Value:
  case Decl::TYPE:                                     \
    return getMostRecentDeclImpl(cast<TYPE##Decl>(D));
DECL [2/4]
#define DECL (TYPE, BASE)
Value:
  case Decl::TYPE:                                                        \
    attachPreviousDeclImpl(Reader, cast<TYPE##Decl>(D), Previous, Canon); \
    break;
DECL [3/4]
#define DECL (TYPE, BASE)
Value:
  case Decl::TYPE:                                        \
    attachLatestDeclImpl(cast<TYPE##Decl>(D), Latest); \
    break;
DECL [4/4]
#define DECL (TYPE, BASE)
Value:
  case Decl::TYPE:                                                   \
    ASTDeclReader::markIncompleteDeclChainImpl(cast<TYPE##Decl>(D)); \
    break;
DECL_CONTEXT [1/4]
#define DECL_CONTEXT (DECL)
DECL_CONTEXT [2/4]
#define DECL_CONTEXT (DECL)
DECL_CONTEXT [3/4]
#define DECL_CONTEXT (DECL)
DECL_CONTEXT [4/4]
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE [1/4]
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_CONTEXT_BASE [2/4]
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_CONTEXT_BASE [3/4]
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_CONTEXT_BASE [4/4]
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_RANGE [1/4]
#define DECL_RANGE (Base, First, Last)
DECL_RANGE [2/4]
#define DECL_RANGE (Base, First, Last)
DECL_RANGE [3/4]
#define DECL_RANGE (Base, First, Last)
DECL_RANGE [4/4]
#define DECL_RANGE (Base, First, Last)
DECLARATOR [1/4]
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECLARATOR [2/4]
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECLARATOR [3/4]
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECLARATOR [4/4]
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECOMPOSITION [1/4]
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
DECOMPOSITION [2/4]
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
DECOMPOSITION [3/4]
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
DECOMPOSITION [4/4]
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
EMPTY [1/4]
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
EMPTY [2/4]
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
EMPTY [3/4]
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
EMPTY [4/4]
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM [1/4]
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUM [2/4]
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUM [3/4]
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUM [4/4]
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT [1/4]
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
ENUMCONSTANT [2/4]
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
ENUMCONSTANT [3/4]
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
ENUMCONSTANT [4/4]
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPORT [1/4]
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXPORT [2/4]
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXPORT [3/4]
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXPORT [4/4]
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT [1/4]
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT [2/4]
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT [3/4]
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT [4/4]
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
FIELD [1/5]
#define FIELD (Name, Width, Merge)
Value:
  Data.Name = Record.readInt();
FIELD [2/5]
#define FIELD (Name, Width, Merge)
Value:
Merge(Name)
FIELD [3/5]
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FIELD [4/5]
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FIELD [5/5]
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM [1/4]
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FILESCOPEASM [2/4]
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FILESCOPEASM [3/4]
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FILESCOPEASM [4/4]
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FRIEND [1/4]
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIEND [2/4]
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIEND [3/4]
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIEND [4/4]
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE [1/4]
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE [2/4]
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE [3/4]
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE [4/4]
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FUNCTION [1/4]
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTION [2/4]
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTION [3/4]
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTION [4/4]
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONTEMPLATE [1/4]
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
FUNCTIONTEMPLATE [2/4]
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
FUNCTIONTEMPLATE [3/4]
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
FUNCTIONTEMPLATE [4/4]
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
IMPLICITPARAM [1/4]
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPLICITPARAM [2/4]
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPLICITPARAM [3/4]
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPLICITPARAM [4/4]
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPORT [1/4]
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
IMPORT [2/4]
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
IMPORT [3/4]
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
IMPORT [4/4]
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD [1/4]
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
INDIRECTFIELD [2/4]
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
INDIRECTFIELD [3/4]
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
INDIRECTFIELD [4/4]
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
LABEL [1/4]
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LABEL [2/4]
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LABEL [3/4]
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LABEL [4/4]
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LAST_DECL_RANGE [1/4]
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LAST_DECL_RANGE [2/4]
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LAST_DECL_RANGE [3/4]
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LAST_DECL_RANGE [4/4]
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY [1/4]
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LIFETIMEEXTENDEDTEMPORARY [2/4]
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LIFETIMEEXTENDEDTEMPORARY [3/4]
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LIFETIMEEXTENDEDTEMPORARY [4/4]
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC [1/4]
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC [2/4]
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC [3/4]
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC [4/4]
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MERGE_OR
#define MERGE_OR (Field)
Value:
DD.Field |= MergeDD.Field;
MSGUID [1/4]
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSGUID [2/4]
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSGUID [3/4]
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSGUID [4/4]
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY [1/4]
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
MSPROPERTY [2/4]
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
MSPROPERTY [3/4]
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
MSPROPERTY [4/4]
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
NAMED [1/4]
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMED [2/4]
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMED [3/4]
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMED [4/4]
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE [1/4]
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACE [2/4]
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACE [3/4]
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACE [4/4]
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS [1/4]
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS [2/4]
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS [3/4]
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS [4/4]
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NO_MERGE
#define NO_MERGE (Field)
Value:
    DetectedOdrViolation |= DD.Field != MergeDD.Field; \
    MERGE_OR(Field)
NONTYPETEMPLATEPARM [1/4]
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
NONTYPETEMPLATEPARM [2/4]
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
NONTYPETEMPLATEPARM [3/4]
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
NONTYPETEMPLATEPARM [4/4]
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
OBJCATDEFSFIELD [1/4]
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCATDEFSFIELD [2/4]
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCATDEFSFIELD [3/4]
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCATDEFSFIELD [4/4]
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCCATEGORY [1/4]
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORY [2/4]
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORY [3/4]
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORY [4/4]
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL [1/4]
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCATEGORYIMPL [2/4]
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCATEGORYIMPL [3/4]
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCATEGORYIMPL [4/4]
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS [1/4]
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCOMPATIBLEALIAS [2/4]
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCOMPATIBLEALIAS [3/4]
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCOMPATIBLEALIAS [4/4]
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER [1/4]
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER [2/4]
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER [3/4]
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER [4/4]
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCIMPL [1/4]
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPL [2/4]
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPL [3/4]
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPL [4/4]
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION [1/4]
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCIMPLEMENTATION [2/4]
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCIMPLEMENTATION [3/4]
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCIMPLEMENTATION [4/4]
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINTERFACE [1/4]
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCINTERFACE [2/4]
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCINTERFACE [3/4]
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCINTERFACE [4/4]
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIVAR [1/4]
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCIVAR [2/4]
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCIVAR [3/4]
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCIVAR [4/4]
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCMETHOD [1/4]
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCMETHOD [2/4]
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCMETHOD [3/4]
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCMETHOD [4/4]
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY [1/4]
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY [2/4]
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY [3/4]
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY [4/4]
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL [1/4]
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROPERTYIMPL [2/4]
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROPERTYIMPL [3/4]
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROPERTYIMPL [4/4]
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROTOCOL [1/4]
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCPROTOCOL [2/4]
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCPROTOCOL [3/4]
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCPROTOCOL [4/4]
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCTYPEPARAM [1/4]
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OBJCTYPEPARAM [2/4]
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OBJCTYPEPARAM [3/4]
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OBJCTYPEPARAM [4/4]
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OMPALLOCATE [1/4]
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPALLOCATE [2/4]
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPALLOCATE [3/4]
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPALLOCATE [4/4]
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPCAPTUREDEXPR [1/4]
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPCAPTUREDEXPR [2/4]
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPCAPTUREDEXPR [3/4]
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPCAPTUREDEXPR [4/4]
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPDECLAREMAPPER [1/4]
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREMAPPER [2/4]
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREMAPPER [3/4]
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREMAPPER [4/4]
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION [1/4]
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION [2/4]
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION [3/4]
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION [4/4]
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPREQUIRES [1/4]
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPREQUIRES [2/4]
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPREQUIRES [3/4]
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPREQUIRES [4/4]
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE [1/4]
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE [2/4]
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE [3/4]
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE [4/4]
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
PARMVAR [1/4]
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PARMVAR [2/4]
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PARMVAR [3/4]
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PARMVAR [4/4]
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PRAGMACOMMENT [1/4]
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMACOMMENT [2/4]
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMACOMMENT [3/4]
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMACOMMENT [4/4]
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH [1/4]
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH [2/4]
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH [3/4]
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH [4/4]
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
RECORD [1/4]
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
RECORD [2/4]
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
RECORD [3/4]
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
RECORD [4/4]
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
REDECLARABLETEMPLATE [1/4]
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REDECLARABLETEMPLATE [2/4]
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REDECLARABLETEMPLATE [3/4]
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REDECLARABLETEMPLATE [4/4]
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPRBODY [1/4]
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
REQUIRESEXPRBODY [2/4]
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
REQUIRESEXPRBODY [3/4]
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
REQUIRESEXPRBODY [4/4]
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT [1/4]
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT [2/4]
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT [3/4]
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT [4/4]
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
TAG [1/4]
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TAG [2/4]
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TAG [3/4]
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TAG [4/4]
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE [1/4]
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATE [2/4]
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATE [3/4]
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATE [4/4]
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT [1/4]
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATEPARAMOBJECT [2/4]
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATEPARAMOBJECT [3/4]
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATEPARAMOBJECT [4/4]
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM [1/4]
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETEMPLATEPARM [2/4]
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETEMPLATEPARM [3/4]
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETEMPLATEPARM [4/4]
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM [1/4]
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATETYPEPARM [2/4]
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATETYPEPARM [3/4]
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATETYPEPARM [4/4]
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT [1/4]
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TRANSLATIONUNIT [2/4]
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TRANSLATIONUNIT [3/4]
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TRANSLATIONUNIT [4/4]
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE [1/4]
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPE [2/4]
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPE [3/4]
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPE [4/4]
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPEALIAS [1/4]
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIAS [2/4]
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIAS [3/4]
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIAS [4/4]
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE [1/4]
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEALIASTEMPLATE [2/4]
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEALIASTEMPLATE [3/4]
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEALIASTEMPLATE [4/4]
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF [1/4]
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEF [2/4]
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEF [3/4]
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEF [4/4]
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME [1/4]
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
TYPEDEFNAME [2/4]
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
TYPEDEFNAME [3/4]
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
TYPEDEFNAME [4/4]
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME [1/4]
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME [2/4]
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME [3/4]
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME [4/4]
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE [1/4]
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
UNRESOLVEDUSINGVALUE [2/4]
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
UNRESOLVEDUSINGVALUE [3/4]
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
UNRESOLVEDUSINGVALUE [4/4]
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USING [1/4]
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USING [2/4]
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USING [3/4]
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USING [4/4]
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE [1/4]
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE [2/4]
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE [3/4]
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE [4/4]
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK [1/4]
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK [2/4]
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK [3/4]
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK [4/4]
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW [1/4]
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW [2/4]
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW [3/4]
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW [4/4]
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VALUE [1/4]
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VALUE [2/4]
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VALUE [3/4]
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VALUE [4/4]
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VAR [1/4]
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VAR [2/4]
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VAR [3/4]
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VAR [4/4]
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE [1/4]
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATE [2/4]
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATE [3/4]
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATE [4/4]
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION [1/4]
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION [2/4]
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION [3/4]
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION [4/4]
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION [1/4]
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
VARTEMPLATESPECIALIZATION [2/4]
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
VARTEMPLATESPECIALIZATION [3/4]
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
VARTEMPLATESPECIALIZATION [4/4]
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
Function Documentation
allowODRLikeMergeInC()
static bool allowODRLikeMergeInC (NamedDecl * ND) static
ODR-like semantics for C/ObjC allow us to merge tag types and a structural check in Sema guarantees the types can be merged (see C11 6.2.7/1 or C89 6.1.2.6/1).
Although most merging is done in Sema, we need to guarantee that some types are mergeable during deserialization, otherwise name lookup fails. This is the case for EnumConstantDecl.
Definition at line 2625 of file ASTReaderDecl.cpp.
Referenced by clang::ASTDeclReader::mergeMergeable().
assert_cast() [1/2]
template<typename T > static T assert_cast (...) static
Definition at line 2534 of file ASTReaderDecl.cpp.
assert_cast() [2/2]
template<typename T > static T assert_cast (T t) static
"Cast" to type T, asserting if we don't have an implicit conversion.
We use this to put code in a template that will only be valid for certain instantiations.
Definition at line 2533 of file ASTReaderDecl.cpp.
Referenced by clang::ASTDeclReader::mergeRedeclarable().
forAllLaterRedecls()
template<typename DeclT , typename Fn > static void forAllLaterRedecls (DeclT * D, Fn F) static
Definition at line 4401 of file ASTReaderDecl.cpp.
References clang::Decl::getMostRecentDecl(), and clang::Decl::getPreviousDecl().
Referenced by clang::ASTDeclReader::UpdateDecl().
getDeclForMerging()
static NamedDecl * getDeclForMerging (NamedDecl * Found, bool IsTypedefNameForLinkage) static
Find the declaration that should be merged into, given the declaration found by name lookup.
If we're merging an anonymous declaration within a typedef, we need a matching typedef, and we merge with the type inside it.
Definition at line 3335 of file ASTReaderDecl.cpp.
References clang::Decl::isFromASTFile().
getNamespace()
static NamespaceDecl * getNamespace (const NestedNameSpecifier * X) static
Definition at line 2944 of file ASTReaderDecl.cpp.
References X().
Referenced by isSameQualifier().
hasSameOverloadableAttrs()
static bool hasSameOverloadableAttrs (const FunctionDecl * A, const FunctionDecl * B) static
Determine whether the attributes we can overload on are identical for A and B.
Will ignore any overloadable attrs represented in the type of A and B.
Definition at line 3020 of file ASTReaderDecl.cpp.
References clang::Decl::getASTContext(), and clang::Decl::specific_attrs().
Referenced by isSameEntity().
inheritDefaultTemplateArgument()
template<typename ParmDecl > static bool inheritDefaultTemplateArgument (ASTContext & Context, ParmDecl * From, Decl * ToD) static
Inherit the default template argument from From to To.
Returns false if there is no default template for From.
Definition at line 3651 of file ASTReaderDecl.cpp.
References clang::cast().
Referenced by inheritDefaultTemplateArguments().
inheritDefaultTemplateArguments()
static void inheritDefaultTemplateArguments (ASTContext & Context, TemplateDecl * From, TemplateDecl * To) static
Definition at line 3660 of file ASTReaderDecl.cpp.
References clang::TemplateDecl::getTemplateParameters(), inheritDefaultTemplateArgument(), and N.
Referenced by clang::ASTDeclReader::attachPreviousDecl().
isConsumerInterestedIn()
static bool isConsumerInterestedIn (ASTContext & Ctx, Decl * D, bool HasBody) static
Determine whether the consumer will be interested in seeing this declaration (via HandleTopLevelDecl).
This routine should return true for anything that might affect code generation, e.g., inline function definitions, Objective-C declarations with metadata, etc.
Definition at line 2826 of file ASTReaderDecl.cpp.
References clang::ASTContext::DeclMustBeEmitted(), clang::VarDecl::Definition, clang::ExternalASTSource::EK_Never, clang::Decl::getASTContext(), clang::Decl::getDeclContext(), clang::ASTContext::getExternalSource(), clang::Decl::getImportedOwningModule(), clang::OMPDeclareTargetDeclAttr::isDeclareTargetDeclaration(), clang::DeclContext::isFunctionOrMethod(), clang::serialization::isPartOfPerModuleInitializer(), and clang::Module::ModuleMapModule.
isSameEntity()
static bool isSameEntity (NamedDecl * X, NamedDecl * Y) static
Determine whether the two declarations refer to the same entity.pr.
Definition at line 3052 of file ASTReaderDecl.cpp.
References clang::C, clang::cast(), clang::declaresSameEntity(), clang::Type::getAs(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ArrayType::getElementType(), clang::FunctionProtoType::getExceptionSpecType(), clang::TargetAttr::getFeaturesStr(), clang::Decl::getKind(), clang::DeclContext::getRedeclContext(), hasSameOverloadableAttrs(), clang::Type::isIncompleteArrayType(), isSameEntity(), isSameQualifier(), isSameTemplateParameterList(), clang::isUnresolvedExceptionSpec(), clang::Stmt::Profile(), clang::TTK_Class, clang::TTK_Interface, clang::TTK_Struct, and X().
Referenced by isSameEntity().
isSameQualifier()
static bool isSameQualifier (const NestedNameSpecifier * X, const NestedNameSpecifier * Y) static
Definition at line 2952 of file ASTReaderDecl.cpp.
References clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsType(), clang::Type::getCanonicalTypeInternal(), clang::NestedNameSpecifier::getKind(), getNamespace(), clang::NestedNameSpecifier::getPrefix(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, isSameQualifier(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, clang::NestedNameSpecifier::TypeSpecWithTemplate, and X().
Referenced by isSameEntity(), and isSameQualifier().
isSameTemplateParameter()
static bool isSameTemplateParameter (const NamedDecl * X, const NamedDecl * Y) static
Determine whether two template parameters are similar enough that they may be used in declarations of the same template.
Definition at line 2893 of file ASTReaderDecl.cpp.
References clang::cast(), clang::Decl::getASTContext(), clang::Decl::getKind(), clang::ConceptReference::getNamedConcept(), clang::ConceptReference::getTemplateArgsAsWritten(), clang::ConceptReference::hasExplicitTemplateArgs(), isSameTemplateParameterList(), and X().
Referenced by isSameTemplateParameterList().
isSameTemplateParameterList()
static bool isSameTemplateParameterList (const ASTContext & C, const TemplateParameterList * X, const TemplateParameterList * Y) static
Determine whether two template parameter lists are similar enough that they may be used in declarations of the same template.
Definition at line 2993 of file ASTReaderDecl.cpp.
References clang::C, clang::TemplateParameterList::getParam(), clang::TemplateParameterList::getRequiresClause(), isSameTemplateParameter(), N, clang::Stmt::Profile(), clang::TemplateParameterList::size(), and X().
Referenced by isSameEntity(), and isSameTemplateParameter().
merged_redecls()
template<typename DeclT > static llvm::iterator_range< MergedRedeclIterator< DeclT > > merged_redecls (DeclT * D) static
Definition at line 500 of file ASTReaderDecl.cpp.
Referenced by clang::ASTDeclReader::VisitEnumDecl().