clang: lib/AST/ASTStructuralEquivalence.cpp File Reference
ASTStructuralEquivalence.cpp File Reference
#include "clang/AST/ASTStructuralEquivalence.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/StmtObjC.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <utility>
#include "clang/AST/StmtNodes.inc"
#include "clang/AST/DeclNodes.inc"
Macros
#define STMT(CLASS, PARENT)
#define ABSTRACT_STMT(Type)
#define STMT_RANGE(Base, First, Last)
#define LAST_STMT_RANGE(Base, First, Last)
#define ASMSTMT(Type, Base)
#define GCCASMSTMT(Type, Base)
#define MSASMSTMT(Type, Base)
#define BREAKSTMT(Type, Base)
#define CXXCATCHSTMT(Type, Base)
#define CXXFORRANGESTMT(Type, Base)
#define CXXTRYSTMT(Type, Base)
#define CAPTUREDSTMT(Type, Base)
#define COMPOUNDSTMT(Type, Base)
#define CONTINUESTMT(Type, Base)
#define CORETURNSTMT(Type, Base)
#define COROUTINEBODYSTMT(Type, Base)
#define DECLSTMT(Type, Base)
#define DOSTMT(Type, Base)
#define FORSTMT(Type, Base)
#define GOTOSTMT(Type, Base)
#define IFSTMT(Type, Base)
#define INDIRECTGOTOSTMT(Type, Base)
#define MSDEPENDENTEXISTSSTMT(Type, Base)
#define NULLSTMT(Type, Base)
#define OMPEXECUTABLEDIRECTIVE(Type, Base)
#define OMPATOMICDIRECTIVE(Type, Base)
#define OMPBARRIERDIRECTIVE(Type, Base)
#define OMPCANCELDIRECTIVE(Type, Base)
#define OMPCANCELLATIONPOINTDIRECTIVE(Type, Base)
#define OMPCRITICALDIRECTIVE(Type, Base)
#define OMPDEPOBJDIRECTIVE(Type, Base)
#define OMPFLUSHDIRECTIVE(Type, Base)
#define OMPLOOPDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPFORDIRECTIVE(Type, Base)
#define OMPFORSIMDDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELFORDIRECTIVE(Type, Base)
#define OMPPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPSIMDDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPTASKLOOPDIRECTIVE(Type, Base)
#define OMPTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPMASTERDIRECTIVE(Type, Base)
#define OMPORDEREDDIRECTIVE(Type, Base)
#define OMPPARALLELDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERDIRECTIVE(Type, Base)
#define OMPPARALLELSECTIONSDIRECTIVE(Type, Base)
#define OMPSCANDIRECTIVE(Type, Base)
#define OMPSECTIONDIRECTIVE(Type, Base)
#define OMPSECTIONSDIRECTIVE(Type, Base)
#define OMPSINGLEDIRECTIVE(Type, Base)
#define OMPTARGETDATADIRECTIVE(Type, Base)
#define OMPTARGETDIRECTIVE(Type, Base)
#define OMPTARGETENTERDATADIRECTIVE(Type, Base)
#define OMPTARGETEXITDATADIRECTIVE(Type, Base)
#define OMPTARGETPARALLELDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDIRECTIVE(Type, Base)
#define OMPTARGETUPDATEDIRECTIVE(Type, Base)
#define OMPTASKDIRECTIVE(Type, Base)
#define OMPTASKGROUPDIRECTIVE(Type, Base)
#define OMPTASKWAITDIRECTIVE(Type, Base)
#define OMPTASKYIELDDIRECTIVE(Type, Base)
#define OMPTEAMSDIRECTIVE(Type, Base)
#define OBJCATCATCHSTMT(Type, Base)
#define OBJCATFINALLYSTMT(Type, Base)
#define OBJCATSYNCHRONIZEDSTMT(Type, Base)
#define OBJCATTHROWSTMT(Type, Base)
#define OBJCATTRYSTMT(Type, Base)
#define OBJCAUTORELEASEPOOLSTMT(Type, Base)
#define OBJCFORCOLLECTIONSTMT(Type, Base)
#define RETURNSTMT(Type, Base)
#define SEHEXCEPTSTMT(Type, Base)
#define SEHFINALLYSTMT(Type, Base)
#define SEHLEAVESTMT(Type, Base)
#define SEHTRYSTMT(Type, Base)
#define SWITCHCASE(Type, Base)
#define CASESTMT(Type, Base)
#define DEFAULTSTMT(Type, Base)
#define SWITCHSTMT(Type, Base)
#define VALUESTMT(Type, Base)
#define ATTRIBUTEDSTMT(Type, Base)
#define EXPR(Type, Base)
#define ABSTRACTCONDITIONALOPERATOR(Type, Base)
#define BINARYCONDITIONALOPERATOR(Type, Base)
#define CONDITIONALOPERATOR(Type, Base)
#define ADDRLABELEXPR(Type, Base)
#define ARRAYINITINDEXEXPR(Type, Base)
#define ARRAYINITLOOPEXPR(Type, Base)
#define ARRAYSUBSCRIPTEXPR(Type, Base)
#define ARRAYTYPETRAITEXPR(Type, Base)
#define ASTYPEEXPR(Type, Base)
#define ATOMICEXPR(Type, Base)
#define BINARYOPERATOR(Type, Base)
#define COMPOUNDASSIGNOPERATOR(Type, Base)
#define BLOCKEXPR(Type, Base)
#define CXXBINDTEMPORARYEXPR(Type, Base)
#define CXXBOOLLITERALEXPR(Type, Base)
#define CXXCONSTRUCTEXPR(Type, Base)
#define CXXTEMPORARYOBJECTEXPR(Type, Base)
#define CXXDEFAULTARGEXPR(Type, Base)
#define CXXDEFAULTINITEXPR(Type, Base)
#define CXXDELETEEXPR(Type, Base)
#define CXXDEPENDENTSCOPEMEMBEREXPR(Type, Base)
#define CXXFOLDEXPR(Type, Base)
#define CXXINHERITEDCTORINITEXPR(Type, Base)
#define CXXNEWEXPR(Type, Base)
#define CXXNOEXCEPTEXPR(Type, Base)
#define CXXNULLPTRLITERALEXPR(Type, Base)
#define CXXPSEUDODESTRUCTOREXPR(Type, Base)
#define CXXREWRITTENBINARYOPERATOR(Type, Base)
#define CXXSCALARVALUEINITEXPR(Type, Base)
#define CXXSTDINITIALIZERLISTEXPR(Type, Base)
#define CXXTHISEXPR(Type, Base)
#define CXXTHROWEXPR(Type, Base)
#define CXXTYPEIDEXPR(Type, Base)
#define CXXUNRESOLVEDCONSTRUCTEXPR(Type, Base)
#define CXXUUIDOFEXPR(Type, Base)
#define CALLEXPR(Type, Base)
#define CUDAKERNELCALLEXPR(Type, Base)
#define CXXMEMBERCALLEXPR(Type, Base)
#define CXXOPERATORCALLEXPR(Type, Base)
#define USERDEFINEDLITERAL(Type, Base)
#define CASTEXPR(Type, Base)
#define EXPLICITCASTEXPR(Type, Base)
#define BUILTINBITCASTEXPR(Type, Base)
#define CSTYLECASTEXPR(Type, Base)
#define CXXFUNCTIONALCASTEXPR(Type, Base)
#define CXXNAMEDCASTEXPR(Type, Base)
#define CXXADDRSPACECASTEXPR(Type, Base)
#define CXXCONSTCASTEXPR(Type, Base)
#define CXXDYNAMICCASTEXPR(Type, Base)
#define CXXREINTERPRETCASTEXPR(Type, Base)
#define CXXSTATICCASTEXPR(Type, Base)
#define OBJCBRIDGEDCASTEXPR(Type, Base)
#define IMPLICITCASTEXPR(Type, Base)
#define CHARACTERLITERAL(Type, Base)
#define CHOOSEEXPR(Type, Base)
#define COMPOUNDLITERALEXPR(Type, Base)
#define CONCEPTSPECIALIZATIONEXPR(Type, Base)
#define CONVERTVECTOREXPR(Type, Base)
#define COROUTINESUSPENDEXPR(Type, Base)
#define COAWAITEXPR(Type, Base)
#define COYIELDEXPR(Type, Base)
#define DECLREFEXPR(Type, Base)
#define DEPENDENTCOAWAITEXPR(Type, Base)
#define DEPENDENTSCOPEDECLREFEXPR(Type, Base)
#define DESIGNATEDINITEXPR(Type, Base)
#define DESIGNATEDINITUPDATEEXPR(Type, Base)
#define EXPRESSIONTRAITEXPR(Type, Base)
#define EXTVECTORELEMENTEXPR(Type, Base)
#define FIXEDPOINTLITERAL(Type, Base)
#define FLOATINGLITERAL(Type, Base)
#define FULLEXPR(Type, Base)
#define CONSTANTEXPR(Type, Base)
#define EXPRWITHCLEANUPS(Type, Base)
#define FUNCTIONPARMPACKEXPR(Type, Base)
#define GNUNULLEXPR(Type, Base)
#define GENERICSELECTIONEXPR(Type, Base)
#define IMAGINARYLITERAL(Type, Base)
#define IMPLICITVALUEINITEXPR(Type, Base)
#define INITLISTEXPR(Type, Base)
#define INTEGERLITERAL(Type, Base)
#define LAMBDAEXPR(Type, Base)
#define MSPROPERTYREFEXPR(Type, Base)
#define MSPROPERTYSUBSCRIPTEXPR(Type, Base)
#define MATERIALIZETEMPORARYEXPR(Type, Base)
#define MATRIXSUBSCRIPTEXPR(Type, Base)
#define MEMBEREXPR(Type, Base)
#define NOINITEXPR(Type, Base)
#define OMPARRAYSECTIONEXPR(Type, Base)
#define OMPARRAYSHAPINGEXPR(Type, Base)
#define OMPITERATOREXPR(Type, Base)
#define OBJCARRAYLITERAL(Type, Base)
#define OBJCAVAILABILITYCHECKEXPR(Type, Base)
#define OBJCBOOLLITERALEXPR(Type, Base)
#define OBJCBOXEDEXPR(Type, Base)
#define OBJCDICTIONARYLITERAL(Type, Base)
#define OBJCENCODEEXPR(Type, Base)
#define OBJCINDIRECTCOPYRESTOREEXPR(Type, Base)
#define OBJCISAEXPR(Type, Base)
#define OBJCIVARREFEXPR(Type, Base)
#define OBJCMESSAGEEXPR(Type, Base)
#define OBJCPROPERTYREFEXPR(Type, Base)
#define OBJCPROTOCOLEXPR(Type, Base)
#define OBJCSELECTOREXPR(Type, Base)
#define OBJCSTRINGLITERAL(Type, Base)
#define OBJCSUBSCRIPTREFEXPR(Type, Base)
#define OFFSETOFEXPR(Type, Base)
#define OPAQUEVALUEEXPR(Type, Base)
#define OVERLOADEXPR(Type, Base)
#define UNRESOLVEDLOOKUPEXPR(Type, Base)
#define UNRESOLVEDMEMBEREXPR(Type, Base)
#define PACKEXPANSIONEXPR(Type, Base)
#define PARENEXPR(Type, Base)
#define PARENLISTEXPR(Type, Base)
#define PREDEFINEDEXPR(Type, Base)
#define PSEUDOOBJECTEXPR(Type, Base)
#define RECOVERYEXPR(Type, Base)
#define REQUIRESEXPR(Type, Base)
#define SHUFFLEVECTOREXPR(Type, Base)
#define SIZEOFPACKEXPR(Type, Base)
#define SOURCELOCEXPR(Type, Base)
#define STMTEXPR(Type, Base)
#define STRINGLITERAL(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMEXPR(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR(Type, Base)
#define TYPETRAITEXPR(Type, Base)
#define TYPOEXPR(Type, Base)
#define UNARYEXPRORTYPETRAITEXPR(Type, Base)
#define UNARYOPERATOR(Type, Base)
#define VAARGEXPR(Type, Base)
#define LABELSTMT(Type, Base)
#define WHILESTMT(Type, Base)
#define STMT(CLASS, PARENT)
#define ABSTRACT_STMT(S)
#define STMT_RANGE(Base, First, Last)
#define LAST_STMT_RANGE(Base, First, Last)
#define ASMSTMT(Type, Base)
#define GCCASMSTMT(Type, Base)
#define MSASMSTMT(Type, Base)
#define BREAKSTMT(Type, Base)
#define CXXCATCHSTMT(Type, Base)
#define CXXFORRANGESTMT(Type, Base)
#define CXXTRYSTMT(Type, Base)
#define CAPTUREDSTMT(Type, Base)
#define COMPOUNDSTMT(Type, Base)
#define CONTINUESTMT(Type, Base)
#define CORETURNSTMT(Type, Base)
#define COROUTINEBODYSTMT(Type, Base)
#define DECLSTMT(Type, Base)
#define DOSTMT(Type, Base)
#define FORSTMT(Type, Base)
#define GOTOSTMT(Type, Base)
#define IFSTMT(Type, Base)
#define INDIRECTGOTOSTMT(Type, Base)
#define MSDEPENDENTEXISTSSTMT(Type, Base)
#define NULLSTMT(Type, Base)
#define OMPEXECUTABLEDIRECTIVE(Type, Base)
#define OMPATOMICDIRECTIVE(Type, Base)
#define OMPBARRIERDIRECTIVE(Type, Base)
#define OMPCANCELDIRECTIVE(Type, Base)
#define OMPCANCELLATIONPOINTDIRECTIVE(Type, Base)
#define OMPCRITICALDIRECTIVE(Type, Base)
#define OMPDEPOBJDIRECTIVE(Type, Base)
#define OMPFLUSHDIRECTIVE(Type, Base)
#define OMPLOOPDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPFORDIRECTIVE(Type, Base)
#define OMPFORSIMDDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELFORDIRECTIVE(Type, Base)
#define OMPPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPSIMDDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPTASKLOOPDIRECTIVE(Type, Base)
#define OMPTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPMASTERDIRECTIVE(Type, Base)
#define OMPORDEREDDIRECTIVE(Type, Base)
#define OMPPARALLELDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERDIRECTIVE(Type, Base)
#define OMPPARALLELSECTIONSDIRECTIVE(Type, Base)
#define OMPSCANDIRECTIVE(Type, Base)
#define OMPSECTIONDIRECTIVE(Type, Base)
#define OMPSECTIONSDIRECTIVE(Type, Base)
#define OMPSINGLEDIRECTIVE(Type, Base)
#define OMPTARGETDATADIRECTIVE(Type, Base)
#define OMPTARGETDIRECTIVE(Type, Base)
#define OMPTARGETENTERDATADIRECTIVE(Type, Base)
#define OMPTARGETEXITDATADIRECTIVE(Type, Base)
#define OMPTARGETPARALLELDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDIRECTIVE(Type, Base)
#define OMPTARGETUPDATEDIRECTIVE(Type, Base)
#define OMPTASKDIRECTIVE(Type, Base)
#define OMPTASKGROUPDIRECTIVE(Type, Base)
#define OMPTASKWAITDIRECTIVE(Type, Base)
#define OMPTASKYIELDDIRECTIVE(Type, Base)
#define OMPTEAMSDIRECTIVE(Type, Base)
#define OBJCATCATCHSTMT(Type, Base)
#define OBJCATFINALLYSTMT(Type, Base)
#define OBJCATSYNCHRONIZEDSTMT(Type, Base)
#define OBJCATTHROWSTMT(Type, Base)
#define OBJCATTRYSTMT(Type, Base)
#define OBJCAUTORELEASEPOOLSTMT(Type, Base)
#define OBJCFORCOLLECTIONSTMT(Type, Base)
#define RETURNSTMT(Type, Base)
#define SEHEXCEPTSTMT(Type, Base)
#define SEHFINALLYSTMT(Type, Base)
#define SEHLEAVESTMT(Type, Base)
#define SEHTRYSTMT(Type, Base)
#define SWITCHCASE(Type, Base)
#define CASESTMT(Type, Base)
#define DEFAULTSTMT(Type, Base)
#define SWITCHSTMT(Type, Base)
#define VALUESTMT(Type, Base)
#define ATTRIBUTEDSTMT(Type, Base)
#define EXPR(Type, Base)
#define ABSTRACTCONDITIONALOPERATOR(Type, Base)
#define BINARYCONDITIONALOPERATOR(Type, Base)
#define CONDITIONALOPERATOR(Type, Base)
#define ADDRLABELEXPR(Type, Base)
#define ARRAYINITINDEXEXPR(Type, Base)
#define ARRAYINITLOOPEXPR(Type, Base)
#define ARRAYSUBSCRIPTEXPR(Type, Base)
#define ARRAYTYPETRAITEXPR(Type, Base)
#define ASTYPEEXPR(Type, Base)
#define ATOMICEXPR(Type, Base)
#define BINARYOPERATOR(Type, Base)
#define COMPOUNDASSIGNOPERATOR(Type, Base)
#define BLOCKEXPR(Type, Base)
#define CXXBINDTEMPORARYEXPR(Type, Base)
#define CXXBOOLLITERALEXPR(Type, Base)
#define CXXCONSTRUCTEXPR(Type, Base)
#define CXXTEMPORARYOBJECTEXPR(Type, Base)
#define CXXDEFAULTARGEXPR(Type, Base)
#define CXXDEFAULTINITEXPR(Type, Base)
#define CXXDELETEEXPR(Type, Base)
#define CXXDEPENDENTSCOPEMEMBEREXPR(Type, Base)
#define CXXFOLDEXPR(Type, Base)
#define CXXINHERITEDCTORINITEXPR(Type, Base)
#define CXXNEWEXPR(Type, Base)
#define CXXNOEXCEPTEXPR(Type, Base)
#define CXXNULLPTRLITERALEXPR(Type, Base)
#define CXXPSEUDODESTRUCTOREXPR(Type, Base)
#define CXXREWRITTENBINARYOPERATOR(Type, Base)
#define CXXSCALARVALUEINITEXPR(Type, Base)
#define CXXSTDINITIALIZERLISTEXPR(Type, Base)
#define CXXTHISEXPR(Type, Base)
#define CXXTHROWEXPR(Type, Base)
#define CXXTYPEIDEXPR(Type, Base)
#define CXXUNRESOLVEDCONSTRUCTEXPR(Type, Base)
#define CXXUUIDOFEXPR(Type, Base)
#define CALLEXPR(Type, Base)
#define CUDAKERNELCALLEXPR(Type, Base)
#define CXXMEMBERCALLEXPR(Type, Base)
#define CXXOPERATORCALLEXPR(Type, Base)
#define USERDEFINEDLITERAL(Type, Base)
#define CASTEXPR(Type, Base)
#define EXPLICITCASTEXPR(Type, Base)
#define BUILTINBITCASTEXPR(Type, Base)
#define CSTYLECASTEXPR(Type, Base)
#define CXXFUNCTIONALCASTEXPR(Type, Base)
#define CXXNAMEDCASTEXPR(Type, Base)
#define CXXADDRSPACECASTEXPR(Type, Base)
#define CXXCONSTCASTEXPR(Type, Base)
#define CXXDYNAMICCASTEXPR(Type, Base)
#define CXXREINTERPRETCASTEXPR(Type, Base)
#define CXXSTATICCASTEXPR(Type, Base)
#define OBJCBRIDGEDCASTEXPR(Type, Base)
#define IMPLICITCASTEXPR(Type, Base)
#define CHARACTERLITERAL(Type, Base)
#define CHOOSEEXPR(Type, Base)
#define COMPOUNDLITERALEXPR(Type, Base)
#define CONCEPTSPECIALIZATIONEXPR(Type, Base)
#define CONVERTVECTOREXPR(Type, Base)
#define COROUTINESUSPENDEXPR(Type, Base)
#define COAWAITEXPR(Type, Base)
#define COYIELDEXPR(Type, Base)
#define DECLREFEXPR(Type, Base)
#define DEPENDENTCOAWAITEXPR(Type, Base)
#define DEPENDENTSCOPEDECLREFEXPR(Type, Base)
#define DESIGNATEDINITEXPR(Type, Base)
#define DESIGNATEDINITUPDATEEXPR(Type, Base)
#define EXPRESSIONTRAITEXPR(Type, Base)
#define EXTVECTORELEMENTEXPR(Type, Base)
#define FIXEDPOINTLITERAL(Type, Base)
#define FLOATINGLITERAL(Type, Base)
#define FULLEXPR(Type, Base)
#define CONSTANTEXPR(Type, Base)
#define EXPRWITHCLEANUPS(Type, Base)
#define FUNCTIONPARMPACKEXPR(Type, Base)
#define GNUNULLEXPR(Type, Base)
#define GENERICSELECTIONEXPR(Type, Base)
#define IMAGINARYLITERAL(Type, Base)
#define IMPLICITVALUEINITEXPR(Type, Base)
#define INITLISTEXPR(Type, Base)
#define INTEGERLITERAL(Type, Base)
#define LAMBDAEXPR(Type, Base)
#define MSPROPERTYREFEXPR(Type, Base)
#define MSPROPERTYSUBSCRIPTEXPR(Type, Base)
#define MATERIALIZETEMPORARYEXPR(Type, Base)
#define MATRIXSUBSCRIPTEXPR(Type, Base)
#define MEMBEREXPR(Type, Base)
#define NOINITEXPR(Type, Base)
#define OMPARRAYSECTIONEXPR(Type, Base)
#define OMPARRAYSHAPINGEXPR(Type, Base)
#define OMPITERATOREXPR(Type, Base)
#define OBJCARRAYLITERAL(Type, Base)
#define OBJCAVAILABILITYCHECKEXPR(Type, Base)
#define OBJCBOOLLITERALEXPR(Type, Base)
#define OBJCBOXEDEXPR(Type, Base)
#define OBJCDICTIONARYLITERAL(Type, Base)
#define OBJCENCODEEXPR(Type, Base)
#define OBJCINDIRECTCOPYRESTOREEXPR(Type, Base)
#define OBJCISAEXPR(Type, Base)
#define OBJCIVARREFEXPR(Type, Base)
#define OBJCMESSAGEEXPR(Type, Base)
#define OBJCPROPERTYREFEXPR(Type, Base)
#define OBJCPROTOCOLEXPR(Type, Base)
#define OBJCSELECTOREXPR(Type, Base)
#define OBJCSTRINGLITERAL(Type, Base)
#define OBJCSUBSCRIPTREFEXPR(Type, Base)
#define OFFSETOFEXPR(Type, Base)
#define OPAQUEVALUEEXPR(Type, Base)
#define OVERLOADEXPR(Type, Base)
#define UNRESOLVEDLOOKUPEXPR(Type, Base)
#define UNRESOLVEDMEMBEREXPR(Type, Base)
#define PACKEXPANSIONEXPR(Type, Base)
#define PARENEXPR(Type, Base)
#define PARENLISTEXPR(Type, Base)
#define PREDEFINEDEXPR(Type, Base)
#define PSEUDOOBJECTEXPR(Type, Base)
#define RECOVERYEXPR(Type, Base)
#define REQUIRESEXPR(Type, Base)
#define SHUFFLEVECTOREXPR(Type, Base)
#define SIZEOFPACKEXPR(Type, Base)
#define SOURCELOCEXPR(Type, Base)
#define STMTEXPR(Type, Base)
#define STRINGLITERAL(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMEXPR(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR(Type, Base)
#define TYPETRAITEXPR(Type, Base)
#define TYPOEXPR(Type, Base)
#define UNARYEXPRORTYPETRAITEXPR(Type, Base)
#define UNARYOPERATOR(Type, Base)
#define VAARGEXPR(Type, Base)
#define LABELSTMT(Type, Base)
#define WHILESTMT(Type, Base)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
Functions
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, QualType T1, QualType T2)
Determine structural equivalence of two types.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, Decl *D1, Decl *D2)
Determine structural equivalence of two declarations.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const TemplateArgument &Arg1, const TemplateArgument &Arg2)
Determine whether two template arguments are equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, NestedNameSpecifier *NNS1, NestedNameSpecifier *NNS2)
Determine whether two nested-name-specifiers are equivalent.
static bool IsStructurallyEquivalent (const IdentifierInfo *Name1, const IdentifierInfo *Name2)
Determine whether two identifiers are equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const DeclarationName Name1, const DeclarationName Name2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const Stmt *S1, const Stmt *S2)
Determine structural equivalence of two statements.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const TemplateName &N1, const TemplateName &N2)
static bool IsArrayStructurallyEquivalent (StructuralEquivalenceContext &Context, const ArrayType *Array1, const ArrayType *Array2)
Determine structural equivalence for the common part of array types.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionType::ExtInfo EI1, FunctionType::ExtInfo EI2)
Determine structural equivalence based on the ExtInfo of functions.
static bool IsEquivalentExceptionSpec (StructuralEquivalenceContext &Context, const FunctionProtoType *Proto1, const FunctionProtoType *Proto2)
Check the equivalence of exception specifications.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FieldDecl *Field1, FieldDecl *Field2)
Determine structural equivalence of two fields.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, CXXMethodDecl *Method1, CXXMethodDecl *Method2)
Determine structural equivalence of two methods.
static bool IsStructurallyEquivalentLambdas (StructuralEquivalenceContext &Context, CXXRecordDecl *D1, CXXRecordDecl *D2)
Determine structural equivalence of two lambda classes.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, RecordDecl *D1, RecordDecl *D2)
Determine structural equivalence of two records.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, EnumDecl *D1, EnumDecl *D2)
Determine structural equivalence of two enums.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateParameterList *Params1, TemplateParameterList *Params2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateTypeParmDecl *D1, TemplateTypeParmDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, NonTypeTemplateParmDecl *D1, NonTypeTemplateParmDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateTemplateParmDecl *D1, TemplateTemplateParmDecl *D2)
static bool IsTemplateDeclCommonStructurallyEquivalent (StructuralEquivalenceContext &Ctx, TemplateDecl *D1, TemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ClassTemplateDecl *D1, ClassTemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionTemplateDecl *D1, FunctionTemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ConceptDecl *D1, ConceptDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FriendDecl *D1, FriendDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TypedefNameDecl *D1, TypedefNameDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionDecl *D1, FunctionDecl *D2)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
ABSTRACT_STMT [1/2]
#define ABSTRACT_STMT (S)
ABSTRACT_STMT [2/2]
#define ABSTRACT_STMT (Type)
Value:
Type
ABSTRACTCONDITIONALOPERATOR [1/2]
#define ABSTRACTCONDITIONALOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
ABSTRACTCONDITIONALOPERATOR [2/2]
#define ABSTRACTCONDITIONALOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
ACCESSSPEC
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
ADDRLABELEXPR [1/2]
#define ADDRLABELEXPR (Type, Base)
Value:
EXPR(Type, Base)
ADDRLABELEXPR [2/2]
#define ADDRLABELEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITINDEXEXPR [1/2]
#define ARRAYINITINDEXEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITINDEXEXPR [2/2]
#define ARRAYINITINDEXEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITLOOPEXPR [1/2]
#define ARRAYINITLOOPEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITLOOPEXPR [2/2]
#define ARRAYINITLOOPEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYSUBSCRIPTEXPR [1/2]
#define ARRAYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYSUBSCRIPTEXPR [2/2]
#define ARRAYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYTYPETRAITEXPR [1/2]
#define ARRAYTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYTYPETRAITEXPR [2/2]
#define ARRAYTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
ASMSTMT [1/2]
#define ASMSTMT (Type, Base)
Value:
STMT(Type, Base)
ASMSTMT [2/2]
#define ASMSTMT (Type, Base)
Value:
STMT(Type, Base)
ASTYPEEXPR [1/2]
#define ASTYPEEXPR (Type, Base)
Value:
EXPR(Type, Base)
ASTYPEEXPR [2/2]
#define ASTYPEEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATOMICEXPR [1/2]
#define ATOMICEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATOMICEXPR [2/2]
#define ATOMICEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATTRIBUTEDSTMT [1/2]
#define ATTRIBUTEDSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
ATTRIBUTEDSTMT [2/2]
#define ATTRIBUTEDSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
BINARYCONDITIONALOPERATOR [1/2]
#define BINARYCONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
BINARYCONDITIONALOPERATOR [2/2]
#define BINARYCONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
BINARYOPERATOR [1/2]
#define BINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
BINARYOPERATOR [2/2]
#define BINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
BINDING
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BLOCKEXPR [1/2]
#define BLOCKEXPR (Type, Base)
Value:
EXPR(Type, Base)
BLOCKEXPR [2/2]
#define BLOCKEXPR (Type, Base)
Value:
EXPR(Type, Base)
BREAKSTMT [1/2]
#define BREAKSTMT (Type, Base)
Value:
STMT(Type, Base)
BREAKSTMT [2/2]
#define BREAKSTMT (Type, Base)
Value:
STMT(Type, Base)
BUILTINBITCASTEXPR [1/2]
#define BUILTINBITCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
BUILTINBITCASTEXPR [2/2]
#define BUILTINBITCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
BUILTINTEMPLATE
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CALLEXPR [1/2]
#define CALLEXPR (Type, Base)
Value:
EXPR(Type, Base)
CALLEXPR [2/2]
#define CALLEXPR (Type, Base)
Value:
EXPR(Type, Base)
CAPTURED
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CAPTUREDSTMT [1/2]
#define CAPTUREDSTMT (Type, Base)
Value:
STMT(Type, Base)
CAPTUREDSTMT [2/2]
#define CAPTUREDSTMT (Type, Base)
Value:
STMT(Type, Base)
CASESTMT [1/2]
#define CASESTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
CASESTMT [2/2]
#define CASESTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
CASTEXPR [1/2]
#define CASTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CASTEXPR [2/2]
#define CASTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CHARACTERLITERAL [1/2]
#define CHARACTERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
CHARACTERLITERAL [2/2]
#define CHARACTERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
CHOOSEEXPR [1/2]
#define CHOOSEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CHOOSEEXPR [2/2]
#define CHOOSEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
COAWAITEXPR [1/2]
#define COAWAITEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
COAWAITEXPR [2/2]
#define COAWAITEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
COMPOUNDASSIGNOPERATOR [1/2]
#define COMPOUNDASSIGNOPERATOR (Type, Base)
Value:
BINARYOPERATOR(Type, Base)
COMPOUNDASSIGNOPERATOR [2/2]
#define COMPOUNDASSIGNOPERATOR (Type, Base)
Value:
BINARYOPERATOR(Type, Base)
COMPOUNDLITERALEXPR [1/2]
#define COMPOUNDLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
COMPOUNDLITERALEXPR [2/2]
#define COMPOUNDLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
COMPOUNDSTMT [1/2]
#define COMPOUNDSTMT (Type, Base)
Value:
STMT(Type, Base)
COMPOUNDSTMT [2/2]
#define COMPOUNDSTMT (Type, Base)
Value:
STMT(Type, Base)
CONCEPT
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONCEPTSPECIALIZATIONEXPR [1/2]
#define CONCEPTSPECIALIZATIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
CONCEPTSPECIALIZATIONEXPR [2/2]
#define CONCEPTSPECIALIZATIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
CONDITIONALOPERATOR [1/2]
#define CONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
CONDITIONALOPERATOR [2/2]
#define CONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
CONSTANTEXPR [1/2]
#define CONSTANTEXPR (Type, Base)
Value:
FULLEXPR(Type, Base)
CONSTANTEXPR [2/2]
#define CONSTANTEXPR (Type, Base)
Value:
FULLEXPR(Type, Base)
CONSTRUCTORUSINGSHADOW
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CONTINUESTMT [1/2]
#define CONTINUESTMT (Type, Base)
Value:
STMT(Type, Base)
CONTINUESTMT [2/2]
#define CONTINUESTMT (Type, Base)
Value:
STMT(Type, Base)
CONVERTVECTOREXPR [1/2]
#define CONVERTVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CONVERTVECTOREXPR [2/2]
#define CONVERTVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CORETURNSTMT [1/2]
#define CORETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
CORETURNSTMT [2/2]
#define CORETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINEBODYSTMT [1/2]
#define COROUTINEBODYSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINEBODYSTMT [2/2]
#define COROUTINEBODYSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINESUSPENDEXPR [1/2]
#define COROUTINESUSPENDEXPR (Type, Base)
Value:
EXPR(Type, Base)
COROUTINESUSPENDEXPR [2/2]
#define COROUTINESUSPENDEXPR (Type, Base)
Value:
EXPR(Type, Base)
COYIELDEXPR [1/2]
#define COYIELDEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
COYIELDEXPR [2/2]
#define COYIELDEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
CSTYLECASTEXPR [1/2]
#define CSTYLECASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CSTYLECASTEXPR [2/2]
#define CSTYLECASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CUDAKERNELCALLEXPR [1/2]
#define CUDAKERNELCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CUDAKERNELCALLEXPR [2/2]
#define CUDAKERNELCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXADDRSPACECASTEXPR [1/2]
#define CXXADDRSPACECASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXADDRSPACECASTEXPR [2/2]
#define CXXADDRSPACECASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXBINDTEMPORARYEXPR [1/2]
#define CXXBINDTEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXBINDTEMPORARYEXPR [2/2]
#define CXXBINDTEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXBOOLLITERALEXPR [1/2]
#define CXXBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXBOOLLITERALEXPR [2/2]
#define CXXBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXCATCHSTMT [1/2]
#define CXXCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXCATCHSTMT [2/2]
#define CXXCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXCONSTCASTEXPR [1/2]
#define CXXCONSTCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXCONSTCASTEXPR [2/2]
#define CXXCONSTCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXCONSTRUCTEXPR [1/2]
#define CXXCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXCONSTRUCTEXPR [2/2]
#define CXXCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXCONSTRUCTOR
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDEFAULTARGEXPR [1/2]
#define CXXDEFAULTARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTARGEXPR [2/2]
#define CXXDEFAULTARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTINITEXPR [1/2]
#define CXXDEFAULTINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTINITEXPR [2/2]
#define CXXDEFAULTINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDELETEEXPR [1/2]
#define CXXDELETEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDELETEEXPR [2/2]
#define CXXDELETEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEPENDENTSCOPEMEMBEREXPR [1/2]
#define CXXDEPENDENTSCOPEMEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEPENDENTSCOPEMEMBEREXPR [2/2]
#define CXXDEPENDENTSCOPEMEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDESTRUCTOR
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDYNAMICCASTEXPR [1/2]
#define CXXDYNAMICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXDYNAMICCASTEXPR [2/2]
#define CXXDYNAMICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXFOLDEXPR [1/2]
#define CXXFOLDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXFOLDEXPR [2/2]
#define CXXFOLDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXFORRANGESTMT [1/2]
#define CXXFORRANGESTMT (Type, Base)
Value:
STMT(Type, Base)
CXXFORRANGESTMT [2/2]
#define CXXFORRANGESTMT (Type, Base)
Value:
STMT(Type, Base)
CXXFUNCTIONALCASTEXPR [1/2]
#define CXXFUNCTIONALCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXFUNCTIONALCASTEXPR [2/2]
#define CXXFUNCTIONALCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXINHERITEDCTORINITEXPR [1/2]
#define CXXINHERITEDCTORINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXINHERITEDCTORINITEXPR [2/2]
#define CXXINHERITEDCTORINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXMEMBERCALLEXPR [1/2]
#define CXXMEMBERCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXMEMBERCALLEXPR [2/2]
#define CXXMEMBERCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXMETHOD
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXNAMEDCASTEXPR [1/2]
#define CXXNAMEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXNAMEDCASTEXPR [2/2]
#define CXXNAMEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXNEWEXPR [1/2]
#define CXXNEWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNEWEXPR [2/2]
#define CXXNEWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNOEXCEPTEXPR [1/2]
#define CXXNOEXCEPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNOEXCEPTEXPR [2/2]
#define CXXNOEXCEPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNULLPTRLITERALEXPR [1/2]
#define CXXNULLPTRLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNULLPTRLITERALEXPR [2/2]
#define CXXNULLPTRLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXOPERATORCALLEXPR [1/2]
#define CXXOPERATORCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXOPERATORCALLEXPR [2/2]
#define CXXOPERATORCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXPSEUDODESTRUCTOREXPR [1/2]
#define CXXPSEUDODESTRUCTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXPSEUDODESTRUCTOREXPR [2/2]
#define CXXPSEUDODESTRUCTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXRECORD
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
CXXREINTERPRETCASTEXPR [1/2]
#define CXXREINTERPRETCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXREINTERPRETCASTEXPR [2/2]
#define CXXREINTERPRETCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXREWRITTENBINARYOPERATOR [1/2]
#define CXXREWRITTENBINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
CXXREWRITTENBINARYOPERATOR [2/2]
#define CXXREWRITTENBINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
CXXSCALARVALUEINITEXPR [1/2]
#define CXXSCALARVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXSCALARVALUEINITEXPR [2/2]
#define CXXSCALARVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXSTATICCASTEXPR [1/2]
#define CXXSTATICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXSTATICCASTEXPR [2/2]
#define CXXSTATICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXSTDINITIALIZERLISTEXPR [1/2]
#define CXXSTDINITIALIZERLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXSTDINITIALIZERLISTEXPR [2/2]
#define CXXSTDINITIALIZERLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTEMPORARYOBJECTEXPR [1/2]
#define CXXTEMPORARYOBJECTEXPR (Type, Base)
Value:
CXXCONSTRUCTEXPR(Type, Base)
CXXTEMPORARYOBJECTEXPR [2/2]
#define CXXTEMPORARYOBJECTEXPR (Type, Base)
Value:
CXXCONSTRUCTEXPR(Type, Base)
CXXTHISEXPR [1/2]
#define CXXTHISEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTHISEXPR [2/2]
#define CXXTHISEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTHROWEXPR [1/2]
#define CXXTHROWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTHROWEXPR [2/2]
#define CXXTHROWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTRYSTMT [1/2]
#define CXXTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXTRYSTMT [2/2]
#define CXXTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXTYPEIDEXPR [1/2]
#define CXXTYPEIDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTYPEIDEXPR [2/2]
#define CXXTYPEIDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUNRESOLVEDCONSTRUCTEXPR [1/2]
#define CXXUNRESOLVEDCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUNRESOLVEDCONSTRUCTEXPR [2/2]
#define CXXUNRESOLVEDCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUUIDOFEXPR [1/2]
#define CXXUUIDOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUUIDOFEXPR [2/2]
#define CXXUUIDOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECL
#define DECL (DERIVED, BASE)
Value:
  case Decl::Kind::DERIVED:                                                    \
    return ::IsStructurallyEquivalent(*this, static_cast<DERIVED##Decl *>(D1), \
                                      static_cast<DERIVED##Decl *>(D2));
DECL_CONTEXT
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_RANGE
#define DECL_RANGE (Base, First, Last)
DECLARATOR
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECLREFEXPR [1/2]
#define DECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECLREFEXPR [2/2]
#define DECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECLSTMT [1/2]
#define DECLSTMT (Type, Base)
Value:
STMT(Type, Base)
DECLSTMT [2/2]
#define DECLSTMT (Type, Base)
Value:
STMT(Type, Base)
DECOMPOSITION
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
DEFAULTSTMT [1/2]
#define DEFAULTSTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
DEFAULTSTMT [2/2]
#define DEFAULTSTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
DEPENDENTCOAWAITEXPR [1/2]
#define DEPENDENTCOAWAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEPENDENTCOAWAITEXPR [2/2]
#define DEPENDENTCOAWAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEPENDENTSCOPEDECLREFEXPR [1/2]
#define DEPENDENTSCOPEDECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEPENDENTSCOPEDECLREFEXPR [2/2]
#define DEPENDENTSCOPEDECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITEXPR [1/2]
#define DESIGNATEDINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITEXPR [2/2]
#define DESIGNATEDINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITUPDATEEXPR [1/2]
#define DESIGNATEDINITUPDATEEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITUPDATEEXPR [2/2]
#define DESIGNATEDINITUPDATEEXPR (Type, Base)
Value:
EXPR(Type, Base)
DOSTMT [1/2]
#define DOSTMT (Type, Base)
Value:
STMT(Type, Base)
DOSTMT [2/2]
#define DOSTMT (Type, Base)
Value:
STMT(Type, Base)
EMPTY
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPLICITCASTEXPR [1/2]
#define EXPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
EXPLICITCASTEXPR [2/2]
#define EXPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
EXPORT
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXPR [1/2]
#define EXPR (Type, Base)
Value:
VALUESTMT(Type, Base)
EXPR [2/2]
#define EXPR (Type, Base)
Value:
VALUESTMT(Type, Base)
EXPRESSIONTRAITEXPR [1/2]
#define EXPRESSIONTRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
EXPRESSIONTRAITEXPR [2/2]
#define EXPRESSIONTRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
EXPRWITHCLEANUPS [1/2]
#define EXPRWITHCLEANUPS (Type, Base)
Value:
FULLEXPR(Type, Base)
EXPRWITHCLEANUPS [2/2]
#define EXPRWITHCLEANUPS (Type, Base)
Value:
FULLEXPR(Type, Base)
EXTERNCCONTEXT
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
EXTVECTORELEMENTEXPR [1/2]
#define EXTVECTORELEMENTEXPR (Type, Base)
Value:
EXPR(Type, Base)
EXTVECTORELEMENTEXPR [2/2]
#define EXTVECTORELEMENTEXPR (Type, Base)
Value:
EXPR(Type, Base)
FIELD
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FIXEDPOINTLITERAL [1/2]
#define FIXEDPOINTLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FIXEDPOINTLITERAL [2/2]
#define FIXEDPOINTLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FLOATINGLITERAL [1/2]
#define FLOATINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FLOATINGLITERAL [2/2]
#define FLOATINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FORSTMT [1/2]
#define FORSTMT (Type, Base)
Value:
STMT(Type, Base)
FORSTMT [2/2]
#define FORSTMT (Type, Base)
Value:
STMT(Type, Base)
FRIEND
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FULLEXPR [1/2]
#define FULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
FULLEXPR [2/2]
#define FULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
FUNCTION
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONPARMPACKEXPR [1/2]
#define FUNCTIONPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
FUNCTIONPARMPACKEXPR [2/2]
#define FUNCTIONPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
FUNCTIONTEMPLATE
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
GCCASMSTMT [1/2]
#define GCCASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
GCCASMSTMT [2/2]
#define GCCASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
GENERICSELECTIONEXPR [1/2]
#define GENERICSELECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
GENERICSELECTIONEXPR [2/2]
#define GENERICSELECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
GNUNULLEXPR [1/2]
#define GNUNULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
GNUNULLEXPR [2/2]
#define GNUNULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
GOTOSTMT [1/2]
#define GOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
GOTOSTMT [2/2]
#define GOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
IFSTMT [1/2]
#define IFSTMT (Type, Base)
Value:
STMT(Type, Base)
IFSTMT [2/2]
#define IFSTMT (Type, Base)
Value:
STMT(Type, Base)
IMAGINARYLITERAL [1/2]
#define IMAGINARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
IMAGINARYLITERAL [2/2]
#define IMAGINARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
IMPLICITCASTEXPR [1/2]
#define IMPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
IMPLICITCASTEXPR [2/2]
#define IMPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
IMPLICITPARAM
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPLICITVALUEINITEXPR [1/2]
#define IMPLICITVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
IMPLICITVALUEINITEXPR [2/2]
#define IMPLICITVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
IMPORT
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
INDIRECTGOTOSTMT [1/2]
#define INDIRECTGOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
INDIRECTGOTOSTMT [2/2]
#define INDIRECTGOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
INITLISTEXPR [1/2]
#define INITLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
INITLISTEXPR [2/2]
#define INITLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
INTEGERLITERAL [1/2]
#define INTEGERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
INTEGERLITERAL [2/2]
#define INTEGERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
LABEL
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LABELSTMT [1/2]
#define LABELSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
LABELSTMT [2/2]
#define LABELSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
LAMBDAEXPR [1/2]
#define LAMBDAEXPR (Type, Base)
Value:
EXPR(Type, Base)
LAMBDAEXPR [2/2]
#define LAMBDAEXPR (Type, Base)
Value:
EXPR(Type, Base)
LAST_DECL_RANGE
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LAST_STMT_RANGE [1/2]
#define LAST_STMT_RANGE (Base, First, Last)
Value:
STMT_RANGE(Base, First, Last)
LAST_STMT_RANGE [2/2]
#define LAST_STMT_RANGE (Base, First, Last)
Value:
STMT_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MATERIALIZETEMPORARYEXPR [1/2]
#define MATERIALIZETEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
MATERIALIZETEMPORARYEXPR [2/2]
#define MATERIALIZETEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
MATRIXSUBSCRIPTEXPR [1/2]
#define MATRIXSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
MATRIXSUBSCRIPTEXPR [2/2]
#define MATRIXSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
MEMBEREXPR [1/2]
#define MEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
MEMBEREXPR [2/2]
#define MEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
MSASMSTMT [1/2]
#define MSASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
MSASMSTMT [2/2]
#define MSASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
MSDEPENDENTEXISTSSTMT [1/2]
#define MSDEPENDENTEXISTSSTMT (Type, Base)
Value:
STMT(Type, Base)
MSDEPENDENTEXISTSSTMT [2/2]
#define MSDEPENDENTEXISTSSTMT (Type, Base)
Value:
STMT(Type, Base)
MSGUID
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
MSPROPERTYREFEXPR [1/2]
#define MSPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
MSPROPERTYREFEXPR [2/2]
#define MSPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
MSPROPERTYSUBSCRIPTEXPR [1/2]
#define MSPROPERTYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
MSPROPERTYSUBSCRIPTEXPR [2/2]
#define MSPROPERTYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
NAMED
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NOINITEXPR [1/2]
#define NOINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
NOINITEXPR [2/2]
#define NOINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
NONTYPETEMPLATEPARM
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
NULLSTMT [1/2]
#define NULLSTMT (Type, Base)
Value:
STMT(Type, Base)
NULLSTMT [2/2]
#define NULLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCARRAYLITERAL [1/2]
#define OBJCARRAYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCARRAYLITERAL [2/2]
#define OBJCARRAYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCATCATCHSTMT [1/2]
#define OBJCATCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATCATCHSTMT [2/2]
#define OBJCATCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATDEFSFIELD
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCATFINALLYSTMT [1/2]
#define OBJCATFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATFINALLYSTMT [2/2]
#define OBJCATFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATSYNCHRONIZEDSTMT [1/2]
#define OBJCATSYNCHRONIZEDSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATSYNCHRONIZEDSTMT [2/2]
#define OBJCATSYNCHRONIZEDSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTHROWSTMT [1/2]
#define OBJCATTHROWSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTHROWSTMT [2/2]
#define OBJCATTHROWSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTRYSTMT [1/2]
#define OBJCATTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTRYSTMT [2/2]
#define OBJCATTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAUTORELEASEPOOLSTMT [1/2]
#define OBJCAUTORELEASEPOOLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAUTORELEASEPOOLSTMT [2/2]
#define OBJCAUTORELEASEPOOLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAVAILABILITYCHECKEXPR [1/2]
#define OBJCAVAILABILITYCHECKEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCAVAILABILITYCHECKEXPR [2/2]
#define OBJCAVAILABILITYCHECKEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOOLLITERALEXPR [1/2]
#define OBJCBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOOLLITERALEXPR [2/2]
#define OBJCBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOXEDEXPR [1/2]
#define OBJCBOXEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOXEDEXPR [2/2]
#define OBJCBOXEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBRIDGEDCASTEXPR [1/2]
#define OBJCBRIDGEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
OBJCBRIDGEDCASTEXPR [2/2]
#define OBJCBRIDGEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
OBJCCATEGORY
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCDICTIONARYLITERAL [1/2]
#define OBJCDICTIONARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCDICTIONARYLITERAL [2/2]
#define OBJCDICTIONARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCENCODEEXPR [1/2]
#define OBJCENCODEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCENCODEEXPR [2/2]
#define OBJCENCODEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCFORCOLLECTIONSTMT [1/2]
#define OBJCFORCOLLECTIONSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCFORCOLLECTIONSTMT [2/2]
#define OBJCFORCOLLECTIONSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCIMPL
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINDIRECTCOPYRESTOREEXPR [1/2]
#define OBJCINDIRECTCOPYRESTOREEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCINDIRECTCOPYRESTOREEXPR [2/2]
#define OBJCINDIRECTCOPYRESTOREEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCINTERFACE
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCISAEXPR [1/2]
#define OBJCISAEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCISAEXPR [2/2]
#define OBJCISAEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCIVAR
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCIVARREFEXPR [1/2]
#define OBJCIVARREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCIVARREFEXPR [2/2]
#define OBJCIVARREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCMESSAGEEXPR [1/2]
#define OBJCMESSAGEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCMESSAGEEXPR [2/2]
#define OBJCMESSAGEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCMETHOD
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROPERTYREFEXPR [1/2]
#define OBJCPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROPERTYREFEXPR [2/2]
#define OBJCPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROTOCOL
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCPROTOCOLEXPR [1/2]
#define OBJCPROTOCOLEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROTOCOLEXPR [2/2]
#define OBJCPROTOCOLEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSELECTOREXPR [1/2]
#define OBJCSELECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSELECTOREXPR [2/2]
#define OBJCSELECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSTRINGLITERAL [1/2]
#define OBJCSTRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCSTRINGLITERAL [2/2]
#define OBJCSTRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCSUBSCRIPTREFEXPR [1/2]
#define OBJCSUBSCRIPTREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSUBSCRIPTREFEXPR [2/2]
#define OBJCSUBSCRIPTREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCTYPEPARAM
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OFFSETOFEXPR [1/2]
#define OFFSETOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OFFSETOFEXPR [2/2]
#define OFFSETOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPALLOCATE
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPARRAYSECTIONEXPR [1/2]
#define OMPARRAYSECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSECTIONEXPR [2/2]
#define OMPARRAYSECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSHAPINGEXPR [1/2]
#define OMPARRAYSHAPINGEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSHAPINGEXPR [2/2]
#define OMPARRAYSHAPINGEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPATOMICDIRECTIVE [1/2]
#define OMPATOMICDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPATOMICDIRECTIVE [2/2]
#define OMPATOMICDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPBARRIERDIRECTIVE [1/2]
#define OMPBARRIERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPBARRIERDIRECTIVE [2/2]
#define OMPBARRIERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELDIRECTIVE [1/2]
#define OMPCANCELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELDIRECTIVE [2/2]
#define OMPCANCELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELLATIONPOINTDIRECTIVE [1/2]
#define OMPCANCELLATIONPOINTDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELLATIONPOINTDIRECTIVE [2/2]
#define OMPCANCELLATIONPOINTDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCAPTUREDEXPR
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPCRITICALDIRECTIVE [1/2]
#define OMPCRITICALDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCRITICALDIRECTIVE [2/2]
#define OMPCRITICALDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDECLAREMAPPER
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPDEPOBJDIRECTIVE [1/2]
#define OMPDEPOBJDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDEPOBJDIRECTIVE [2/2]
#define OMPDEPOBJDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDISTRIBUTEDIRECTIVE [1/2]
#define OMPDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEDIRECTIVE [2/2]
#define OMPDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORDIRECTIVE [1/2]
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORDIRECTIVE [2/2]
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE [1/2]
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE [2/2]
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTESIMDDIRECTIVE [1/2]
#define OMPDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTESIMDDIRECTIVE [2/2]
#define OMPDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPEXECUTABLEDIRECTIVE [1/2]
#define OMPEXECUTABLEDIRECTIVE (Type, Base)
Value:
STMT(Type, Base)
OMPEXECUTABLEDIRECTIVE [2/2]
#define OMPEXECUTABLEDIRECTIVE (Type, Base)
Value:
STMT(Type, Base)
OMPFLUSHDIRECTIVE [1/2]
#define OMPFLUSHDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPFLUSHDIRECTIVE [2/2]
#define OMPFLUSHDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPFORDIRECTIVE [1/2]
#define OMPFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPFORDIRECTIVE [2/2]
#define OMPFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPFORSIMDDIRECTIVE [1/2]
#define OMPFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPFORSIMDDIRECTIVE [2/2]
#define OMPFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPITERATOREXPR [1/2]
#define OMPITERATOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPITERATOREXPR [2/2]
#define OMPITERATOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPLOOPDIRECTIVE [1/2]
#define OMPLOOPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPLOOPDIRECTIVE [2/2]
#define OMPLOOPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERDIRECTIVE [1/2]
#define OMPMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERDIRECTIVE [2/2]
#define OMPMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPDIRECTIVE [1/2]
#define OMPMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPDIRECTIVE [2/2]
#define OMPMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPSIMDDIRECTIVE [1/2]
#define OMPMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPSIMDDIRECTIVE [2/2]
#define OMPMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPORDEREDDIRECTIVE [1/2]
#define OMPORDEREDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPORDEREDDIRECTIVE [2/2]
#define OMPORDEREDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELDIRECTIVE [1/2]
#define OMPPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELDIRECTIVE [2/2]
#define OMPPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELFORDIRECTIVE [1/2]
#define OMPPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELFORDIRECTIVE [2/2]
#define OMPPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELFORSIMDDIRECTIVE [1/2]
#define OMPPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELFORSIMDDIRECTIVE [2/2]
#define OMPPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERDIRECTIVE [1/2]
#define OMPPARALLELMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELMASTERDIRECTIVE [2/2]
#define OMPPARALLELMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPDIRECTIVE [1/2]
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPDIRECTIVE [2/2]
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE [1/2]
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE [2/2]
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELSECTIONSDIRECTIVE [1/2]
#define OMPPARALLELSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELSECTIONSDIRECTIVE [2/2]
#define OMPPARALLELSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPREQUIRES
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPSCANDIRECTIVE [1/2]
#define OMPSCANDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSCANDIRECTIVE [2/2]
#define OMPSCANDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONDIRECTIVE [1/2]
#define OMPSECTIONDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONDIRECTIVE [2/2]
#define OMPSECTIONDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONSDIRECTIVE [1/2]
#define OMPSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONSDIRECTIVE [2/2]
#define OMPSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSIMDDIRECTIVE [1/2]
#define OMPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPSIMDDIRECTIVE [2/2]
#define OMPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPSINGLEDIRECTIVE [1/2]
#define OMPSINGLEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSINGLEDIRECTIVE [2/2]
#define OMPSINGLEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDATADIRECTIVE [1/2]
#define OMPTARGETDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDATADIRECTIVE [2/2]
#define OMPTARGETDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDIRECTIVE [1/2]
#define OMPTARGETDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDIRECTIVE [2/2]
#define OMPTARGETDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETENTERDATADIRECTIVE [1/2]
#define OMPTARGETENTERDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETENTERDATADIRECTIVE [2/2]
#define OMPTARGETENTERDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETEXITDATADIRECTIVE [1/2]
#define OMPTARGETEXITDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETEXITDATADIRECTIVE [2/2]
#define OMPTARGETEXITDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELDIRECTIVE [1/2]
#define OMPTARGETPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELDIRECTIVE [2/2]
#define OMPTARGETPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORDIRECTIVE [1/2]
#define OMPTARGETPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORDIRECTIVE [2/2]
#define OMPTARGETPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORSIMDDIRECTIVE [1/2]
#define OMPTARGETPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORSIMDDIRECTIVE [2/2]
#define OMPTARGETPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETSIMDDIRECTIVE [1/2]
#define OMPTARGETSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETSIMDDIRECTIVE [2/2]
#define OMPTARGETSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDIRECTIVE [1/2]
#define OMPTARGETTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETTEAMSDIRECTIVE [2/2]
#define OMPTARGETTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEDIRECTIVE [1/2]
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEDIRECTIVE [2/2]
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE [1/2]
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE [2/2]
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE [1/2]
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE [2/2]
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE [1/2]
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE [2/2]
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETUPDATEDIRECTIVE [1/2]
#define OMPTARGETUPDATEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETUPDATEDIRECTIVE [2/2]
#define OMPTARGETUPDATEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKDIRECTIVE [1/2]
#define OMPTASKDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKDIRECTIVE [2/2]
#define OMPTASKDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKGROUPDIRECTIVE [1/2]
#define OMPTASKGROUPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKGROUPDIRECTIVE [2/2]
#define OMPTASKGROUPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKLOOPDIRECTIVE [1/2]
#define OMPTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKLOOPDIRECTIVE [2/2]
#define OMPTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKLOOPSIMDDIRECTIVE [1/2]
#define OMPTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKLOOPSIMDDIRECTIVE [2/2]
#define OMPTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKWAITDIRECTIVE [1/2]
#define OMPTASKWAITDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKWAITDIRECTIVE [2/2]
#define OMPTASKWAITDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKYIELDDIRECTIVE [1/2]
#define OMPTASKYIELDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKYIELDDIRECTIVE [2/2]
#define OMPTASKYIELDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDIRECTIVE [1/2]
#define OMPTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDIRECTIVE [2/2]
#define OMPTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEDIRECTIVE [1/2]
#define OMPTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEDIRECTIVE [2/2]
#define OMPTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE [1/2]
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE [2/2]
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE [1/2]
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE [2/2]
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTESIMDDIRECTIVE [1/2]
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTESIMDDIRECTIVE [2/2]
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTHREADPRIVATE
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
OPAQUEVALUEEXPR [1/2]
#define OPAQUEVALUEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OPAQUEVALUEEXPR [2/2]
#define OPAQUEVALUEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OVERLOADEXPR [1/2]
#define OVERLOADEXPR (Type, Base)
Value:
EXPR(Type, Base)
OVERLOADEXPR [2/2]
#define OVERLOADEXPR (Type, Base)
Value:
EXPR(Type, Base)
PACKEXPANSIONEXPR [1/2]
#define PACKEXPANSIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
PACKEXPANSIONEXPR [2/2]
#define PACKEXPANSIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENEXPR [1/2]
#define PARENEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENEXPR [2/2]
#define PARENEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENLISTEXPR [1/2]
#define PARENLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENLISTEXPR [2/2]
#define PARENLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARMVAR
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PRAGMACOMMENT
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
PREDEFINEDEXPR [1/2]
#define PREDEFINEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
PREDEFINEDEXPR [2/2]
#define PREDEFINEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
PSEUDOOBJECTEXPR [1/2]
#define PSEUDOOBJECTEXPR (Type, Base)
Value:
EXPR(Type, Base)
PSEUDOOBJECTEXPR [2/2]
#define PSEUDOOBJECTEXPR (Type, Base)
Value:
EXPR(Type, Base)
RECORD
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
RECOVERYEXPR [1/2]
#define RECOVERYEXPR (Type, Base)
Value:
EXPR(Type, Base)
RECOVERYEXPR [2/2]
#define RECOVERYEXPR (Type, Base)
Value:
EXPR(Type, Base)
REDECLARABLETEMPLATE
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPR [1/2]
#define REQUIRESEXPR (Type, Base)
Value:
EXPR(Type, Base)
REQUIRESEXPR [2/2]
#define REQUIRESEXPR (Type, Base)
Value:
EXPR(Type, Base)
REQUIRESEXPRBODY
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
RETURNSTMT [1/2]
#define RETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
RETURNSTMT [2/2]
#define RETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHEXCEPTSTMT [1/2]
#define SEHEXCEPTSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHEXCEPTSTMT [2/2]
#define SEHEXCEPTSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHFINALLYSTMT [1/2]
#define SEHFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHFINALLYSTMT [2/2]
#define SEHFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHLEAVESTMT [1/2]
#define SEHLEAVESTMT (Type, Base)
Value:
STMT(Type, Base)
SEHLEAVESTMT [2/2]
#define SEHLEAVESTMT (Type, Base)
Value:
STMT(Type, Base)
SEHTRYSTMT [1/2]
#define SEHTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHTRYSTMT [2/2]
#define SEHTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
SHUFFLEVECTOREXPR [1/2]
#define SHUFFLEVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
SHUFFLEVECTOREXPR [2/2]
#define SHUFFLEVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
SIZEOFPACKEXPR [1/2]
#define SIZEOFPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SIZEOFPACKEXPR [2/2]
#define SIZEOFPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SOURCELOCEXPR [1/2]
#define SOURCELOCEXPR (Type, Base)
Value:
EXPR(Type, Base)
SOURCELOCEXPR [2/2]
#define SOURCELOCEXPR (Type, Base)
Value:
EXPR(Type, Base)
STATICASSERT
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
STMT [1/2]
#define STMT (CLASS, PARENT)
Value:
  bool TraverseStmt(const CLASS *S1, const CLASS *S2) {                        \
    if (!TraverseStmt(static_cast<const PARENT *>(S1),                         \
                      static_cast<const PARENT *>(S2)))                        \
      return false;                                                            \
    return IsStmtEquivalent(S1, S2);                                           \
  }
Definition at line 344 of file ASTStructuralEquivalence.cpp.
STMT [2/2]
#define STMT (CLASS, PARENT)
Value:
  case Stmt::StmtClass::CLASS##Class:                                          \
    return TraverseStmt(static_cast<const CLASS *>(S1),                        \
                        static_cast<const CLASS *>(S2));
Definition at line 344 of file ASTStructuralEquivalence.cpp.
STMT_RANGE [1/2]
#define STMT_RANGE (Base, First, Last)
STMT_RANGE [2/2]
#define STMT_RANGE (Base, First, Last)
STMTEXPR [1/2]
#define STMTEXPR (Type, Base)
Value:
EXPR(Type, Base)
STMTEXPR [2/2]
#define STMTEXPR (Type, Base)
Value:
EXPR(Type, Base)
STRINGLITERAL [1/2]
#define STRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
STRINGLITERAL [2/2]
#define STRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMEXPR [1/2]
#define SUBSTNONTYPETEMPLATEPARMEXPR (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMEXPR [2/2]
#define SUBSTNONTYPETEMPLATEPARMEXPR (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMPACKEXPR [1/2]
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMPACKEXPR [2/2]
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SWITCHCASE [1/2]
#define SWITCHCASE (Type, Base)
Value:
STMT(Type, Base)
SWITCHCASE [2/2]
#define SWITCHCASE (Type, Base)
Value:
STMT(Type, Base)
SWITCHSTMT [1/2]
#define SWITCHSTMT (Type, Base)
Value:
STMT(Type, Base)
SWITCHSTMT [2/2]
#define SWITCHSTMT (Type, Base)
Value:
STMT(Type, Base)
TAG
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPEALIAS
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
TYPETRAITEXPR [1/2]
#define TYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
TYPETRAITEXPR [2/2]
#define TYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
TYPOEXPR [1/2]
#define TYPOEXPR (Type, Base)
Value:
EXPR(Type, Base)
TYPOEXPR [2/2]
#define TYPOEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYEXPRORTYPETRAITEXPR [1/2]
#define UNARYEXPRORTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYEXPRORTYPETRAITEXPR [2/2]
#define UNARYEXPRORTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYOPERATOR [1/2]
#define UNARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
UNARYOPERATOR [2/2]
#define UNARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
UNRESOLVEDLOOKUPEXPR [1/2]
#define UNRESOLVEDLOOKUPEXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDLOOKUPEXPR [2/2]
#define UNRESOLVEDLOOKUPEXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDMEMBEREXPR [1/2]
#define UNRESOLVEDMEMBEREXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDMEMBEREXPR [2/2]
#define UNRESOLVEDMEMBEREXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDUSINGTYPENAME
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USERDEFINEDLITERAL [1/2]
#define USERDEFINEDLITERAL (Type, Base)
Value:
CALLEXPR(Type, Base)
USERDEFINEDLITERAL [2/2]
#define USERDEFINEDLITERAL (Type, Base)
Value:
CALLEXPR(Type, Base)
USING
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VAARGEXPR [1/2]
#define VAARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
VAARGEXPR [2/2]
#define VAARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
VALUE
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VALUESTMT [1/2]
#define VALUESTMT (Type, Base)
Value:
STMT(Type, Base)
VALUESTMT [2/2]
#define VALUESTMT (Type, Base)
Value:
STMT(Type, Base)
VAR
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
WHILESTMT [1/2]
#define WHILESTMT (Type, Base)
Value:
STMT(Type, Base)
WHILESTMT [2/2]
#define WHILESTMT (Type, Base)
Value:
STMT(Type, Base)
Function Documentation
IsArrayStructurallyEquivalent()
static bool IsArrayStructurallyEquivalent (StructuralEquivalenceContext & Context, const ArrayType * Array1, const ArrayType * Array2) static
Determine structural equivalence for the common part of array types.
Definition at line 585 of file ASTStructuralEquivalence.cpp.
References clang::ArrayType::getElementType(), clang::ArrayType::getIndexTypeQualifiers(), clang::ArrayType::getSizeModifier(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent().
IsEquivalentExceptionSpec()
static bool IsEquivalentExceptionSpec (StructuralEquivalenceContext & Context, const FunctionProtoType * Proto1, const FunctionProtoType * Proto2) static
Check the equivalence of exception specifications.
Definition at line 626 of file ASTStructuralEquivalence.cpp.
References clang::EST_Dynamic, clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionProtoType::getExceptionType(), clang::FunctionProtoType::getNoexceptExpr(), clang::FunctionProtoType::getNumExceptions(), clang::isComputedNoexcept(), IsStructurallyEquivalent(), clang::isUnresolvedExceptionSpec(), and N.
Referenced by IsStructurallyEquivalent().
IsStructurallyEquivalent() [1/23]
static bool IsStructurallyEquivalent (const IdentifierInfo * Name1, const IdentifierInfo * Name2) static
Determine whether two identifiers are equivalent.
Definition at line 409 of file ASTStructuralEquivalence.cpp.
References clang::IdentifierInfo::getName().
IsStructurallyEquivalent() [2/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ClassTemplateDecl * D1, ClassTemplateDecl * D2) static
Definition at line 1780 of file ASTStructuralEquivalence.cpp.
References clang::ClassTemplateDecl::getTemplatedDecl(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [3/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ConceptDecl * D1, ConceptDecl * D2) static
Definition at line 1804 of file ASTStructuralEquivalence.cpp.
References clang::ConceptDecl::getConstraintExpr(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [4/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const DeclarationName Name1, const DeclarationName Name2) static
Definition at line 110 of file ASTStructuralEquivalence.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::getAsIdentifierInfo(), clang::DeclarationName::getCXXDeductionGuideTemplate(), clang::DeclarationName::getCXXLiteralIdentifier(), clang::DeclarationName::getCXXNameType(), clang::DeclarationName::getCXXOverloadedOperator(), clang::NamedDecl::getDeclName(), clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, IsStructurallyEquivalent(), clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
IsStructurallyEquivalent() [5/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const Stmt * S1, const Stmt * S2) static
Determine structural equivalence of two statements.
Definition at line 384 of file ASTStructuralEquivalence.cpp.
References clang::Stmt::children(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [6/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const TemplateArgument & Arg1, const TemplateArgument & Arg2) static
Determine whether two template arguments are equivalent.
Definition at line 528 of file ASTStructuralEquivalence.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::Integral, IsStructurallyEquivalent(), N, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_begin(), clang::TemplateArgument::pack_size(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
IsStructurallyEquivalent() [7/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const TemplateName & N1, const TemplateName & N2) static
Definition at line 456 of file ASTStructuralEquivalence.cpp.
References clang::TemplateName::AssumedTemplate, clang::OverloadedTemplateStorage::begin(), clang::TemplateName::DependentTemplate, clang::OverloadedTemplateStorage::end(), clang::SubstTemplateTemplateParmPackStorage::getArgumentPack(), clang::TemplateName::getAsAssumedTemplateName(), clang::TemplateName::getAsDependentTemplateName(), clang::TemplateName::getAsOverloadedTemplate(), clang::TemplateName::getAsSubstTemplateTemplateParmPack(), clang::TemplateName::getAsTemplateDecl(), clang::AssumedTemplateStorage::getDeclName(), clang::DependentTemplateName::getIdentifier(), clang::TemplateName::getKind(), clang::DependentTemplateName::getOperator(), clang::SubstTemplateTemplateParmPackStorage::getParameterPack(), clang::DependentTemplateName::getQualifier(), clang::DependentTemplateName::isIdentifier(), clang::DependentTemplateName::isOverloadedOperator(), IsStructurallyEquivalent(), clang::TemplateName::OverloadedTemplate, clang::TemplateName::QualifiedTemplate, clang::TemplateName::SubstTemplateTemplateParm, clang::TemplateName::SubstTemplateTemplateParmPack, and clang::TemplateName::Template.
IsStructurallyEquivalent() [8/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, CXXMethodDecl * Method1, CXXMethodDecl * Method2) static
Determine structural equivalence of two methods.
Definition at line 1285 of file ASTStructuralEquivalence.cpp.
References clang::cast(), clang::Decl::getAccess(), clang::DeclContext::getDeclKind(), clang::NamedDecl::getIdentifier(), clang::FunctionDecl::getOverloadedOperator(), clang::CXXMethodDecl::getRefQualifier(), clang::ValueDecl::getType(), clang::CXXMethodDecl::isConst(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isDeleted(), clang::FunctionDecl::isPure(), clang::CXXMethodDecl::isStatic(), IsStructurallyEquivalent(), clang::CXXMethodDecl::isVirtual(), and clang::CXXMethodDecl::isVolatile().
IsStructurallyEquivalent() [9/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, Decl * D1, Decl * D2) static
Determine structural equivalence of two declarations.
Definition at line 1861 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getCanonicalDecl(), and P.
IsStructurallyEquivalent() [10/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, EnumDecl * D1, EnumDecl * D2) static
Determine structural equivalence of two enums.
Definition at line 1594 of file ASTStructuralEquivalence.cpp.
References clang::EnumDecl::enumerator_begin(), clang::EnumDecl::enumerator_end(), clang::EnumDecl::getDefinition(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::ASTContext::getTypeDeclType(), clang::TagDecl::getTypedefNameForAnonDecl(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [11/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FieldDecl * Field1, FieldDecl * Field2) static
Determine structural equivalence of two fields.
Definition at line 1231 of file ASTStructuralEquivalence.cpp.
References clang::cast(), clang::Type::castAs(), clang::FieldDecl::getBitWidth(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::ASTContext::getTypeDeclType(), clang::FieldDecl::isAnonymousStructOrUnion(), clang::FieldDecl::isBitField(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [12/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FriendDecl * D1, FriendDecl * D2) static
Definition at line 1816 of file ASTStructuralEquivalence.cpp.
References clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendType(), clang::TypeSourceInfo::getType(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [13/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionDecl * D1, FunctionDecl * D2) static
Definition at line 1841 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::FunctionDecl::getOverloadedOperator(), clang::ValueDecl::getType(), clang::FunctionDecl::isOverloadedOperator(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [14/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionTemplateDecl * D1, FunctionTemplateDecl * D2) static
Definition at line 1792 of file ASTStructuralEquivalence.cpp.
References clang::FunctionTemplateDecl::getTemplatedDecl(), clang::ValueDecl::getType(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [15/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionType::ExtInfo EI1, FunctionType::ExtInfo EI2) static
Determine structural equivalence based on the ExtInfo of functions.
This is inspired by ASTContext::mergeFunctionTypes(), we compare calling conventions bits but must not compare some other bits.
Definition at line 602 of file ASTStructuralEquivalence.cpp.
References clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::ExtInfo::getNoCallerSavedRegs(), clang::FunctionType::ExtInfo::getNoCfCheck(), clang::FunctionType::ExtInfo::getProducesResult(), and clang::FunctionType::ExtInfo::getRegParm().
IsStructurallyEquivalent() [16/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, NestedNameSpecifier * NNS1, NestedNameSpecifier * NNS2) static
Determine whether two nested-name-specifiers are equivalent.
Definition at line 418 of file ASTStructuralEquivalence.cpp.
References clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsRecordDecl(), clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getKind(), clang::NestedNameSpecifier::getPrefix(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, IsStructurallyEquivalent(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
IsStructurallyEquivalent() [17/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, NonTypeTemplateParmDecl * D1, NonTypeTemplateParmDecl * D2) static
Definition at line 1718 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::NonTypeTemplateParmDecl::isParameterPack(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [18/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, QualType T1, QualType T2) static
Determine structural equivalence of two types.
Definition at line 656 of file ASTStructuralEquivalence.cpp.
References clang::cast(), clang::ASTContext::getCanonicalType(), clang::DependentSizedMatrixType::getColumnExpr(), clang::QualType::getDesugaredType(), clang::DependentSizedMatrixType::getElementType(), clang::MatrixType::getElementType(), getKind(), clang::ConstantMatrixType::getNumColumns(), clang::ConstantMatrixType::getNumRows(), clang::QualType::getQualifiers(), clang::DependentSizedMatrixType::getRowExpr(), clang::Type::getTypeClass(), getUnderlyingType(), IsArrayStructurallyEquivalent(), IsEquivalentExceptionSpec(), clang::QualType::isNull(), IsStructurallyEquivalent(), and N.
Referenced by IsArrayStructurallyEquivalent(), clang::StructuralEquivalenceContext::IsEquivalent(), clang::StructuralEquivalenceContext::IsEquivalent(), clang::StructuralEquivalenceContext::IsEquivalent(), IsEquivalentExceptionSpec(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalentLambdas(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [19/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, RecordDecl * D1, RecordDecl * D2) static
Determine structural equivalence of two records.
Definition at line 1350 of file ASTStructuralEquivalence.cpp.
References clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::StructuralEquivalenceContext::findUntaggedStructOrUnionIndex(), clang::CXXBaseSpecifier::getBeginLoc(), clang::NamedDecl::getDeclName(), clang::RecordDecl::getDefinition(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::CXXBaseSpecifier::getSourceRange(), clang::TagDecl::getTagKind(), clang::CXXBaseSpecifier::getType(), clang::ASTContext::getTypeDeclType(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::DeclContext::hasExternalLexicalStorage(), clang::TagDecl::isBeingDefined(), IsStructurallyEquivalent(), IsStructurallyEquivalentLambdas(), clang::TagDecl::isUnion(), and N.
IsStructurallyEquivalent() [20/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateParameterList * Params1, TemplateParameterList * Params2) static
Definition at line 1665 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getKind(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateParameterList::getTemplateLoc(), IsStructurallyEquivalent(), N, and clang::TemplateParameterList::size().
IsStructurallyEquivalent() [21/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateTemplateParmDecl * D1, TemplateTemplateParmDecl * D2) static
Definition at line 1749 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), clang::TemplateDecl::getTemplateParameters(), clang::TemplateTemplateParmDecl::isParameterPack(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [22/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateTypeParmDecl * D1, TemplateTypeParmDecl * D2) static
Definition at line 1700 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), and clang::TemplateTypeParmDecl::isParameterPack().
IsStructurallyEquivalent() [23/23]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TypedefNameDecl * D1, TypedefNameDecl * D2) static
Definition at line 1832 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::TypedefNameDecl::getUnderlyingType(), and IsStructurallyEquivalent().
IsStructurallyEquivalentLambdas()
static bool IsStructurallyEquivalentLambdas (StructuralEquivalenceContext & Context, CXXRecordDecl * D1, CXXRecordDecl * D2) static
Determine structural equivalence of two lambda classes.
Definition at line 1338 of file ASTStructuralEquivalence.cpp.
References clang::CXXRecordDecl::getLambdaCallOperator(), clang::CXXRecordDecl::isLambda(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent().
IsTemplateDeclCommonStructurallyEquivalent()
static bool IsTemplateDeclCommonStructurallyEquivalent (StructuralEquivalenceContext & Ctx, TemplateDecl * D1, TemplateDecl * D2) static
Definition at line 1769 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::NamedDecl::getNameAsString(), clang::TemplateDecl::getTemplateParameters(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent(), IsStructurallyEquivalent(), and IsStructurallyEquivalent().