clang: lib/Basic/Targets/X86.cpp File Reference
X86.cpp File Reference
#include "X86.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/TargetBuiltins.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/X86TargetParser.h"
#include "clang/Basic/BuiltinsX86.def"
#include "clang/Basic/BuiltinsX86_64.def"
#include "llvm/Support/X86TargetParser.def"
#include "clang/Basic/X86Target.def"
Namespaces
namespace clang
Dataflow Directional Tag Classes.
namespace clang::targets
Macros
#define BUILTIN(ID, TYPE, ATTRS)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define TARGET_HEADER_BUILTIN(ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
#define BUILTIN(ID, TYPE, ATTRS)
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)
#define TARGET_HEADER_BUILTIN(ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
#define X86_FEATURE_COMPAT(ENUM, STR)
#define X86_FEATURE_COMPAT(ENUM, STR)
#define FEATURE(FEAT)
#define FEATURE(FEAT)
#define CPU_SPECIFIC(NAME, MANGLING, FEATURES)
#define CPU_SPECIFIC_ALIAS(NEW_NAME, NAME)
#define CPU_SPECIFIC_ALIAS(NEW_NAME, NAME)
#define CPU_SPECIFIC(NAME, MANGLING, FEATURES)
#define CPU_SPECIFIC(NAME, MANGLING, FEATURES)
#define X86_VENDOR(ENUM, STRING)
#define X86_CPU_TYPE_ALIAS(ENUM, ALIAS)
#define X86_CPU_TYPE(ENUM, STR)
#define X86_CPU_SUBTYPE(ENUM, STR)
Functions
static llvm::X86::ProcessorFeatures getFeature (StringRef Name)
static unsigned getFeaturePriority (llvm::X86::ProcessorFeatures Feat)
static StringRef CPUSpecificCPUDispatchNameDealias (StringRef Name)
static unsigned matchAsmCCConstraint (const char *&Name)
Variables
const Builtin::Info clang::targets::BuiltinInfoX86 []
static const char *const clang::targets::GCCRegNames []
const TargetInfo::AddlRegName clang::targets::AddlRegNames []
Macro Definition Documentation
BUILTIN [1/2]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, ALL_LANGUAGES, nullptr},
BUILTIN [2/2]
#define BUILTIN (ID, TYPE, ATTRS)
Value:
  {#ID, TYPE, ATTRS, nullptr, ALL_LANGUAGES, nullptr},
CPU_SPECIFIC [1/3]
#define CPU_SPECIFIC (NAME, MANGLING, FEATURES)
Value:
.Case(NAME, true)
CPU_SPECIFIC [2/3]
#define CPU_SPECIFIC (NAME, MANGLING, FEATURES)
Value:
.Case(NAME, MANGLING)
CPU_SPECIFIC [3/3]
#define CPU_SPECIFIC (NAME, MANGLING, FEATURES)
Value:
.Case(NAME, FEATURES)
CPU_SPECIFIC_ALIAS [1/2]
#define CPU_SPECIFIC_ALIAS (NEW_NAME, NAME)
Value:
.Case(NEW_NAME, true)
CPU_SPECIFIC_ALIAS [2/2]
#define CPU_SPECIFIC_ALIAS (NEW_NAME, NAME)
Value:
.Case(NEW_NAME, NAME)
FEATURE [1/2]
#define FEATURE (FEAT)
Value:
FEAT,
FEATURE [2/2]
#define FEATURE (FEAT)
Value:
  case llvm::X86::FEAT:                                                        \
    return static_cast<unsigned>(FeatPriority::FEAT);
TARGET_BUILTIN [1/2]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, nullptr, ALL_LANGUAGES, FEATURE},
TARGET_BUILTIN [2/2]
#define TARGET_BUILTIN (ID, TYPE, ATTRS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, nullptr, ALL_LANGUAGES, FEATURE},
TARGET_HEADER_BUILTIN [1/2]
#define TARGET_HEADER_BUILTIN (ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, HEADER, LANGS, FEATURE},
TARGET_HEADER_BUILTIN [2/2]
#define TARGET_HEADER_BUILTIN (ID, TYPE, ATTRS, HEADER, LANGS, FEATURE)
Value:
  {#ID, TYPE, ATTRS, HEADER, LANGS, FEATURE},
X86_CPU_SUBTYPE
#define X86_CPU_SUBTYPE (ENUM, STR)
Value:
.Case(STR, true)
X86_CPU_TYPE
#define X86_CPU_TYPE (ENUM, STR)
Value:
.Case(STR, true)
X86_CPU_TYPE_ALIAS
#define X86_CPU_TYPE_ALIAS (ENUM, ALIAS)
Value:
.Case(ALIAS, true)
X86_FEATURE_COMPAT [1/2]
#define X86_FEATURE_COMPAT (ENUM, STR)
Value:
.Case(STR, true)
X86_FEATURE_COMPAT [2/2]
#define X86_FEATURE_COMPAT (ENUM, STR)
Value:
.Case(STR, llvm::X86::FEATURE_##ENUM)
X86_VENDOR
#define X86_VENDOR (ENUM, STRING)
Value:
.Case(STRING, true)
Function Documentation
CPUSpecificCPUDispatchNameDealias()
static StringRef CPUSpecificCPUDispatchNameDealias (StringRef Name) static
Definition at line 1074 of file X86.cpp.
Referenced by clang::targets::X86TargetInfo::CPUSpecificManglingCharacter(), and clang::targets::X86TargetInfo::getCPUSpecificCPUDispatchFeatures().
getFeature()
static llvm::X86::ProcessorFeatures getFeature (StringRef Name) static
Definition at line 1027 of file X86.cpp.
Referenced by clang::targets::X86TargetInfo::multiVersionSortPriority().
getFeaturePriority()
static unsigned getFeaturePriority (llvm::X86::ProcessorFeatures Feat) static
Definition at line 1036 of file X86.cpp.
Referenced by clang::targets::X86TargetInfo::multiVersionSortPriority().
matchAsmCCConstraint()
static unsigned matchAsmCCConstraint (const char *& Name) static
Definition at line 1112 of file X86.cpp.
Referenced by clang::targets::X86TargetInfo::convertConstraint(), and clang::targets::X86TargetInfo::validateAsmConstraint().