clang: lib/StaticAnalyzer/Checkers/CallAndMessageChecker.cpp File Reference
CallAndMessageChecker.cpp File Reference
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ParentMap.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define QUERY_CHECKER_OPTION(OPTION)
Functions
static void describeUninitializedArgumentInCall (const CallEvent &Call, int ArgumentNumber, llvm::raw_svector_ostream &Os)
static bool supportsNilWithFloatRet (const llvm::Triple &triple)
Macro Definition Documentation
QUERY_CHECKER_OPTION
#define QUERY_CHECKER_OPTION (OPTION)
Value:
  checker->ChecksEnabled[CallAndMessageChecker::CK_##OPTION] =                 \
      mgr.getAnalyzerOptions().getCheckerBooleanOption(                        \
          mgr.getCurrentCheckerName(), #OPTION);
Function Documentation
describeUninitializedArgumentInCall()
static void describeUninitializedArgumentInCall (const CallEvent & Call, int ArgumentNumber, llvm::raw_svector_ostream & Os) static
Definition at line 152 of file CallAndMessageChecker.cpp.
References clang::cast(), clang::ento::CE_Block, clang::ento::CE_ObjCMessage, clang::ento::ObjCMethodCall::getMessageKind(), clang::ento::ObjCMethodCall::isSetter(), clang::ento::OCM_Message, clang::ento::OCM_PropertyAccess, and clang::ento::OCM_Subscript.
supportsNilWithFloatRet()
static bool supportsNilWithFloatRet (const llvm::Triple & triple) static
Definition at line 667 of file CallAndMessageChecker.cpp.