clang: lib/CodeGen/CGDecl.cpp File Reference
CGDecl.cpp File Reference
#include "CGBlocks.h"
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGDebugInfo.h"
#include "CGOpenCLRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "PatternInit.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "clang/Sema/Sema.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
Enumerations
enum class IsPattern { No , Yes }
Functions
static std::string getStaticDeclName (CodeGenModule &CGM, const VarDecl &D)
static void EmitAutoVarWithLifetime (CodeGenFunction &CGF, const VarDecl &var, Address addr, Qualifiers::ObjCLifetime lifetime)
EmitAutoVarWithLifetime - Does the setup required for an automatic variable with lifetime.
static bool isAccessedBy (const VarDecl &var, const Stmt *s)
static bool isAccessedBy (const ValueDecl *decl, const Expr *e)
static bool tryEmitARCCopyWeakInit (CodeGenFunction &CGF, const LValue &destLV, const Expr *init)
static void drillIntoBlockVariable (CodeGenFunction &CGF, LValue &lvalue, const VarDecl *var)
static bool canEmitInitWithFewStoresAfterBZero (llvm::Constant *Init, unsigned &NumStores)
Decide whether we can emit the non-zero parts of the specified initializer with equal or fewer than NumStores scalar stores.
static void emitStoresForInitAfterBZero (CodeGenModule &CGM, llvm::Constant *Init, Address Loc, bool isVolatile, CGBuilderTy &Builder, bool IsAutoInit)
For inits that canEmitInitWithFewStoresAfterBZero returned true for, emit the scalar stores that would be required.
static bool shouldUseBZeroPlusStoresToInitialize (llvm::Constant *Init, uint64_t GlobalSize)
Decide whether we should use bzero plus some stores to initialize a local variable instead of using a memcpy from a constant global.
static llvm::Value * shouldUseMemSetToInitialize (llvm::Constant *Init, uint64_t GlobalSize, const llvm::DataLayout &DL)
Decide whether we should use memset to initialize a local variable instead of using a memcpy from a constant global.
static bool shouldSplitConstantStore (CodeGenModule &CGM, uint64_t GlobalByteSize)
Decide whether we want to split a constant structure or array store into a sequence of its fields' stores.
static llvm::Constant * patternOrZeroFor (CodeGenModule &CGM, IsPattern isPattern, llvm::Type *Ty)
Generate a constant filled with either a pattern or zeroes.
static llvm::Constant * constWithPadding (CodeGenModule &CGM, IsPattern isPattern, llvm::Constant *constant)
Replace all padding bytes in a given constant with either a pattern byte or 0x00.
static llvm::Constant * constStructWithPadding (CodeGenModule &CGM, IsPattern isPattern, llvm::StructType *STy, llvm::Constant *constant)
Helper function for constWithPadding() to deal with padding in structures.
static Address createUnnamedGlobalForMemcpyFrom (CodeGenModule &CGM, const VarDecl &D, CGBuilderTy &Builder, llvm::Constant *Constant, CharUnits Align)
static void emitStoresForConstant (CodeGenModule &CGM, const VarDecl &D, Address Loc, bool isVolatile, CGBuilderTy &Builder, llvm::Constant *constant, bool IsAutoInit)
static void emitStoresForZeroInit (CodeGenModule &CGM, const VarDecl &D, Address Loc, bool isVolatile, CGBuilderTy &Builder)
static void emitStoresForPatternInit (CodeGenModule &CGM, const VarDecl &D, Address Loc, bool isVolatile, CGBuilderTy &Builder)
static bool containsUndef (llvm::Constant *constant)
static llvm::Constant * replaceUndef (CodeGenModule &CGM, IsPattern isPattern, llvm::Constant *constant)
static bool isCapturedBy (const VarDecl &Var, const Expr *E)
Determines whether the given __block variable is potentially captured by the given expression.
static bool isCapturedBy (const VarDecl &Var, const Stmt *S)
Determines whether the given __block variable is potentially captured by the given statement.
static void emitPartialArrayDestroy (CodeGenFunction &CGF, llvm::Value *begin, llvm::Value *end, QualType type, CharUnits elementAlign, CodeGenFunction::Destroyer *destroyer)
Perform partial array destruction as if in an EH cleanup.
Enumeration Type Documentation
IsPattern
enum class IsPattern strong
Enumerator
No
Yes
Definition at line 1002 of file CGDecl.cpp.
Function Documentation
canEmitInitWithFewStoresAfterBZero()
static bool canEmitInitWithFewStoresAfterBZero (llvm::Constant * Init, unsigned & NumStores) static
Decide whether we can emit the non-zero parts of the specified initializer with equal or fewer than NumStores scalar stores.
Definition at line 873 of file CGDecl.cpp.
References canEmitInitWithFewStoresAfterBZero(), clang::cast(), and clang::NumStores.
Referenced by canEmitInitWithFewStoresAfterBZero(), and shouldUseBZeroPlusStoresToInitialize().
constStructWithPadding()
static llvm::Constant * constStructWithPadding (CodeGenModule & CGM, IsPattern isPattern, llvm::StructType * STy, llvm::Constant * constant) static
Helper function for constWithPadding() to deal with padding in structures.
Definition at line 1017 of file CGDecl.cpp.
References clang::cast(), constWithPadding(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenModule::getLLVMContext(), and patternOrZeroFor().
Referenced by constWithPadding().
constWithPadding()
static llvm::Constant * constWithPadding (CodeGenModule & CGM, IsPattern isPattern, llvm::Constant * constant) static
Replace all padding bytes in a given constant with either a pattern byte or 0x00.
Definition at line 1057 of file CGDecl.cpp.
References constStructWithPadding(), and constWithPadding().
Referenced by constStructWithPadding(), constWithPadding(), emitStoresForPatternInit(), and emitStoresForZeroInit().
containsUndef()
static bool containsUndef (llvm::Constant * constant) static
Definition at line 1271 of file CGDecl.cpp.
References containsUndef().
Referenced by containsUndef(), and replaceUndef().
createUnnamedGlobalForMemcpyFrom()
static Address createUnnamedGlobalForMemcpyFrom (CodeGenModule & CGM, const VarDecl & D, CGBuilderTy & Builder, llvm::Constant * Constant, CharUnits Align) static
Definition at line 1143 of file CGDecl.cpp.
References clang::CodeGen::CodeGenModule::createUnnamedGlobalFrom(), clang::CodeGen::Address::getAddressSpace(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::Address::getType().
Referenced by emitStoresForConstant().
drillIntoBlockVariable()
static void drillIntoBlockVariable (CodeGenFunction & CGF, LValue & lvalue, const VarDecl * var) static
Definition at line 728 of file CGDecl.cpp.
References clang::CodeGen::CodeGenFunction::emitBlockByrefAddress().
EmitAutoVarWithLifetime()
static void EmitAutoVarWithLifetime (CodeGenFunction & CGF, const VarDecl & var, Address addr, Qualifiers::ObjCLifetime lifetime) static
EmitAutoVarWithLifetime - Does the setup required for an automatic variable with lifetime.
Definition at line 610 of file CGDecl.cpp.
References clang::CodeGen::CodeGenFunction::destroyARCStrongImprecise, clang::CodeGen::CodeGenFunction::destroyARCStrongPrecise, clang::CodeGen::CodeGenFunction::destroyARCWeak, clang::CodeGen::EHCleanup, clang::CodeGen::CodeGenFunction::getARCCleanupKind(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::CodeGen::NormalAndEHCleanup, clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, and clang::CodeGen::CodeGenFunction::pushDestroy().
emitPartialArrayDestroy()
static void emitPartialArrayDestroy (CodeGenFunction & CGF, llvm::Value * begin, llvm::Value * end, QualType type, CharUnits elementAlign, CodeGenFunction::Destroyer * destroyer) static
Perform partial array destruction as if in an EH cleanup.
Unlike emitArrayDestroy, the element type here may still be an array type.
Definition at line 2265 of file CGDecl.cpp.
References clang::ast_matchers::arrayType, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::emitArrayDestroy(), clang::ASTContext::getAsArrayType(), clang::CodeGen::CodeGenFunction::getContext(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
emitStoresForConstant()
static void emitStoresForConstant (CodeGenModule & CGM, const VarDecl & D, Address Loc, bool isVolatile, CGBuilderTy & Builder, llvm::Constant * constant, bool IsAutoInit) static
Definition at line 1156 of file CGDecl.cpp.
References clang::cast(), createUnnamedGlobalForMemcpyFrom(), emitStoresForConstant(), emitStoresForInitAfterBZero(), clang::CodeGen::Address::getAddressSpace(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::isa(), shouldSplitConstantStore(), shouldUseBZeroPlusStoresToInitialize(), and shouldUseMemSetToInitialize().
Referenced by emitStoresForConstant(), emitStoresForPatternInit(), and emitStoresForZeroInit().
emitStoresForInitAfterBZero()
static void emitStoresForInitAfterBZero (CodeGenModule & CGM, llvm::Constant * Init, Address Loc, bool isVolatile, CGBuilderTy & Builder, bool IsAutoInit) static
For inits that canEmitInitWithFewStoresAfterBZero returned true for, emit the scalar stores that would be required.
Definition at line 911 of file CGDecl.cpp.
References clang::cast(), and emitStoresForInitAfterBZero().
Referenced by emitStoresForConstant(), and emitStoresForInitAfterBZero().
emitStoresForPatternInit()
static void emitStoresForPatternInit (CodeGenModule & CGM, const VarDecl & D, Address Loc, bool isVolatile, CGBuilderTy & Builder) static
Definition at line 1260 of file CGDecl.cpp.
References constWithPadding(), emitStoresForConstant(), clang::CodeGen::Address::getElementType(), clang::CodeGen::initializationPatternFor(), and Yes.
emitStoresForZeroInit()
static void emitStoresForZeroInit (CodeGenModule & CGM, const VarDecl & D, Address Loc, bool isVolatile, CGBuilderTy & Builder) static
Definition at line 1250 of file CGDecl.cpp.
References constWithPadding(), emitStoresForConstant(), clang::CodeGen::Address::getElementType(), and No.
getStaticDeclName()
static std::string getStaticDeclName (CodeGenModule & CGM, const VarDecl & D) static
Definition at line 211 of file CGDecl.cpp.
References clang::cast(), clang::CodeGen::CodeGenModule::getBlockMangledName(), clang::Decl::getDeclContext(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getMangledName(), clang::NamedDecl::getNameAsString(), and clang::NamedDecl::isExternallyVisible().
Referenced by clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl().
isAccessedBy() [1/2]
static bool isAccessedBy (const ValueDecl * decl, const Expr * e) static
Definition at line 671 of file CGDecl.cpp.
References clang::cast(), clang::ast_matchers::decl, and isAccessedBy().
isAccessedBy() [2/2]
static bool isAccessedBy (const VarDecl & var, const Stmt * s) static
Definition at line 646 of file CGDecl.cpp.
References clang::BlockDecl::captures(), isAccessedBy(), and s.
Referenced by isAccessedBy(), and isAccessedBy().
isCapturedBy() [1/2]
static bool isCapturedBy (const VarDecl & Var, const Expr * E) static
Determines whether the given __block variable is potentially captured by the given expression.
Definition at line 1635 of file CGDecl.cpp.
References clang::Block, clang::CompoundStmt::body(), clang::Stmt::children(), clang::VarDecl::getInit(), clang::Expr::IgnoreParenCasts(), and isCapturedBy().
Referenced by isCapturedBy(), and isCapturedBy().
isCapturedBy() [2/2]
static bool isCapturedBy (const VarDecl & Var, const Stmt * S) static
Determines whether the given __block variable is potentially captured by the given statement.
Definition at line 1624 of file CGDecl.cpp.
References isCapturedBy().
patternOrZeroFor()
static llvm::Constant * patternOrZeroFor (CodeGenModule & CGM, IsPattern isPattern, llvm::Type * Ty) static
Generate a constant filled with either a pattern or zeroes.
Definition at line 1005 of file CGDecl.cpp.
References clang::CodeGen::initializationPatternFor(), and Yes.
Referenced by constStructWithPadding(), and replaceUndef().
replaceUndef()
static llvm::Constant * replaceUndef (CodeGenModule & CGM, IsPattern isPattern, llvm::Constant * constant) static
Definition at line 1282 of file CGDecl.cpp.
References clang::cast(), containsUndef(), patternOrZeroFor(), and replaceUndef().
Referenced by replaceUndef().
shouldSplitConstantStore()
static bool shouldSplitConstantStore (CodeGenModule & CGM, uint64_t GlobalByteSize) static
Decide whether we want to split a constant structure or array store into a sequence of its fields' stores.
This may cost us code size and compilation speed, but plays better with store optimizations.
Definition at line 991 of file CGDecl.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts().
Referenced by emitStoresForConstant().
shouldUseBZeroPlusStoresToInitialize()
static bool shouldUseBZeroPlusStoresToInitialize (llvm::Constant * Init, uint64_t GlobalSize) static
Decide whether we should use bzero plus some stores to initialize a local variable instead of using a memcpy from a constant global.
It is beneficial to use bzero if the global is all zeros, or mostly zeros and large.
Definition at line 958 of file CGDecl.cpp.
References canEmitInitWithFewStoresAfterBZero().
Referenced by emitStoresForConstant().
shouldUseMemSetToInitialize()
static llvm::Value * shouldUseMemSetToInitialize (llvm::Constant * Init, uint64_t GlobalSize, const llvm::DataLayout & DL) static
Decide whether we should use memset to initialize a local variable instead of using a memcpy from a constant global.
Assumes we've already decided to not user bzero. FIXME We could be more clever, as we are for bzero above, and generate memset followed by stores. It's unclear that's worth the effort.
Definition at line 979 of file CGDecl.cpp.
Referenced by emitStoresForConstant().
tryEmitARCCopyWeakInit()
static bool tryEmitARCCopyWeakInit (CodeGenFunction & CGF, const LValue & destLV, const Expr * init) static
Definition at line 678 of file CGDecl.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::ast_matchers::castExpr, clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenFunction::EmitARCCopyWeak(), clang::CodeGen::CodeGenFunction::EmitARCMoveWeak(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::QualType::getObjCLifetime(), clang::Expr::getType(), clang::Expr::getValueKind(), clang::Expr::IgnoreParens(), clang::Qualifiers::OCL_Weak, clang::VK_LValue, and clang::VK_XValue.