clang: lib/CodeGen/CGExprAgg.cpp File Reference
CGExprAgg.cpp File Reference
#include "CGCXXABI.h"
#include "CGObjCRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/StmtVisitor.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
Enumerations
enum CompareKind { CK_Less , CK_Greater , CK_Equal }
Functions
static bool isTrivialFiller (Expr *E)
Determine if E is a trivial array filler, that is, one that is equivalent to zero-initialization.
static Expr * findPeephole (Expr *op, CastKind kind, const ASTContext &ctx)
Attempt to look through various unimportant expressions to find a cast of the given kind.
static llvm::Value * EmitCompare (CGBuilderTy &Builder, CodeGenFunction &CGF, const BinaryOperator *E, llvm::Value *LHS, llvm::Value *RHS, CompareKind Kind, const char *NameSuffix="")
static bool isBlockVarRef (const Expr *E)
Is the value of the given expression possibly a reference to or into a __block variable?
static bool castPreservesZero (const CastExpr *CE)
Determine whether the given cast kind is known to always convert values with all zero bits in their value representation to values with all zero bits in their value representation.
static bool isSimpleZero (const Expr *E, CodeGenFunction &CGF)
isSimpleZero - If emitting this value will obviously just cause a store of zero to memory, return true.
static CharUnits GetNumNonZeroBytesInInit (const Expr *E, CodeGenFunction &CGF)
GetNumNonZeroBytesInInit - Get an approximate count of the number of non-zero bytes that will be stored when outputting the initializer for the specified initializer expression.
static void CheckAggExprForMemSetUse (AggValueSlot &Slot, const Expr *E, CodeGenFunction &CGF)
CheckAggExprForMemSetUse - If the initializer is large and has a lot of zeros in it, emit a memset and avoid storing the individual zeros.
Enumeration Type Documentation
CompareKind
enum CompareKind
Enumerator
CK_Less
CK_Greater
CK_Equal
Definition at line 943 of file CGExprAgg.cpp.
Function Documentation
castPreservesZero()
static bool castPreservesZero (const CastExpr * CE) static
Determine whether the given cast kind is known to always convert values with all zero bits in their value representation to values with all zero bits in their value representation.
Definition at line 1392 of file CGExprAgg.cpp.
References clang::CastExpr::getCastKind().
Referenced by isSimpleZero().
CheckAggExprForMemSetUse()
static void CheckAggExprForMemSetUse (AggValueSlot & Slot, const Expr * E, CodeGenFunction & CGF) static
CheckAggExprForMemSetUse - If the initializer is large and has a lot of zeros in it, emit a memset and avoid storing the individual zeros.
Definition at line 1936 of file CGExprAgg.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CharUnits::fromQuantity(), clang::CodeGen::AggValueSlot::getAddress(), clang::Type::getAs(), clang::ASTContext::getBaseElementType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getLangOpts(), GetNumNonZeroBytesInInit(), clang::CodeGen::AggValueSlot::getPreferredSize(), clang::Expr::getType(), clang::CXXRecordDecl::hasUserDeclaredConstructor(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::Address::isValid(), clang::CodeGen::AggValueSlot::isVolatile(), clang::CodeGen::AggValueSlot::isZeroed(), and clang::CodeGen::AggValueSlot::setZeroed().
EmitCompare()
static llvm::Value * EmitCompare (CGBuilderTy & Builder, CodeGenFunction & CGF, const BinaryOperator * E, llvm::Value * LHS, llvm::Value * RHS, CompareKind Kind, const char * NameSuffix = "") static
Definition at line 949 of file CGExprAgg.cpp.
References clang::CodeGen::CodeGenFunction::CGM, CK_Equal, CK_Greater, CK_Less, clang::CodeGen::CGCXXABI::EmitMemberPointerComparison(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::BinaryOperator::getLHS(), clang::Expr::getType(), clang::Type::hasFloatingRepresentation(), clang::Type::hasSignedIntegerRepresentation(), clang::Type::isIntegralOrEnumerationType(), and clang::Type::isPointerType().
findPeephole()
static Expr * findPeephole (Expr * op, CastKind kind, const ASTContext & ctx) static
Attempt to look through various unimportant expressions to find a cast of the given kind.
Definition at line 685 of file CGExprAgg.cpp.
References clang::Expr::IgnoreParenNoopCasts().
GetNumNonZeroBytesInInit()
static CharUnits GetNumNonZeroBytesInInit (const Expr * E, CodeGenFunction & CGF) static
GetNumNonZeroBytesInInit - Get an approximate count of the number of non-zero bytes that will be stored when outputting the initializer for the specified initializer expression.
Definition at line 1874 of file CGExprAgg.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), clang::CodeGen::CodeGenFunction::getContext(), clang::InitListExpr::getInit(), clang::InitListExpr::getNumInits(), GetNumNonZeroBytesInInit(), clang::TargetInfo::getPointerWidth(), clang::CodeGen::CodeGenFunction::getTarget(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::Expr::IgnoreParenNoopCasts(), isSimpleZero(), clang::InitListExpr::isTransparent(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), clang::ASTContext::toCharUnitsFromBits(), and clang::CharUnits::Zero().
Referenced by CheckAggExprForMemSetUse(), and GetNumNonZeroBytesInInit().
isBlockVarRef()
static bool isBlockVarRef (const Expr * E) static
Is the value of the given expression possibly a reference to or into a __block variable?
Definition at line 1094 of file CGExprAgg.cpp.
References clang::Decl::hasAttr(), clang::Expr::IgnoreParens(), and isBlockVarRef().
Referenced by isBlockVarRef().
isSimpleZero()
static bool isSimpleZero (const Expr * E, CodeGenFunction & CGF) static
isSimpleZero - If emitting this value will obviously just cause a store of zero to memory, return true.
This can return false if uncertain, so it just handles simple cases.
Definition at line 1486 of file CGExprAgg.cpp.
References castPreservesZero(), clang::CodeGen::CodeGenFunction::getContext(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::Expr::HasSideEffects(), clang::Expr::IgnoreParens(), clang::CodeGen::CodeGenTypes::isPointerZeroInitializable(), and clang::CodeGen::CodeGenTypes::isZeroInitializable().
Referenced by GetNumNonZeroBytesInInit().
isTrivialFiller()
static bool isTrivialFiller (Expr * E) static
Determine if E is a trivial array filler, that is, one that is equivalent to zero-initialization.
Definition at line 451 of file CGExprAgg.cpp.
References isTrivialFiller().
Referenced by isTrivialFiller().