clang: lib/CodeGen/CGExprConstant.cpp File Reference
CGExprConstant.cpp File Reference
#include "CGCXXABI.h"
#include "CGObjCRuntime.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/APValue.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Builtins.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
Functions
static QualType getNonMemoryType (CodeGenModule &CGM, QualType type)
static ConstantLValue emitConstantObjCStringLiteral (const StringLiteral *S, QualType T, CodeGenModule &CGM)
static llvm::Constant * EmitNullConstantForBase (CodeGenModule &CGM, llvm::Type *baseType, const CXXRecordDecl *base)
Emit the null constant for a base subobject.
static llvm::Constant * EmitNullConstant (CodeGenModule &CGM, const RecordDecl *record, bool asCompleteObject)
Function Documentation
emitConstantObjCStringLiteral()
static ConstantLValue emitConstantObjCStringLiteral (const StringLiteral * S, QualType T, CodeGenModule & CGM) static
Definition at line 1951 of file CGExprConstant.cpp.
References clang::C, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGObjCRuntime::GenerateConstantString(), clang::CodeGen::ConstantAddress::getElementBitCast(), clang::CodeGen::CodeGenModule::getObjCRuntime(), and clang::CodeGen::CodeGenModule::getTypes().
EmitNullConstant()
static llvm::Constant * EmitNullConstant (CodeGenModule & CGM, const RecordDecl * record, bool asCompleteObject) static
Definition at line 2202 of file CGExprConstant.cpp.
References clang::cast(), clang::CodeGen::CodeGenModule::EmitNullConstant(), EmitNullConstantForBase(), clang::RecordDecl::fields(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CGRecordLayout::getBaseSubobjectLLVMType(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenModule::getContext(), clang::RecordType::getDecl(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::CodeGen::CGRecordLayout::getLLVMType(), clang::CodeGen::CGRecordLayout::getNonVirtualBaseLLVMFieldNo(), clang::ASTRecordLayout::getNonVirtualSize(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CGRecordLayout::getVirtualBaseIndex(), clang::CXXRecordDecl::isEmpty(), clang::TagDecl::isUnion(), and clang::CharUnits::isZero().
Referenced by EmitNullConstantForBase().
EmitNullConstantForBase()
static llvm::Constant * EmitNullConstantForBase (CodeGenModule & CGM, llvm::Type * baseType, const CXXRecordDecl * base) static
Emit the null constant for a base subobject.
Definition at line 2287 of file CGExprConstant.cpp.
References EmitNullConstant(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenModule::getTypes(), and clang::CodeGen::CGRecordLayout::isZeroInitializableAsBase().
Referenced by EmitNullConstant().
getNonMemoryType()
static QualType getNonMemoryType (CodeGenModule & CGM, QualType type) static
Definition at line 1604 of file CGExprConstant.cpp.
References clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getQualifiedType(), and clang::ast_matchers::type.
Referenced by clang::CodeGen::ConstantEmitter::tryEmitAbstractForMemory(), clang::CodeGen::ConstantEmitter::tryEmitAbstractForMemory(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForMemory(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForMemory(), and clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit().