clang: lib/CodeGen/CGOpenMPRuntimeGPU.cpp File Reference
CGOpenMPRuntimeGPU.cpp File Reference
#include "CGOpenMPRuntimeGPU.h"
#include "CGOpenMPRuntimeNVPTX.h"
#include "CodeGenFunction.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Cuda.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Frontend/OpenMP/OMPGridValues.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
Classes
struct CopyOptionsTy
Functions
static llvm::Value * getNVPTXWarpID (CodeGenFunction &CGF)
Get the id of the warp in the block.
static llvm::Value * getNVPTXLaneID (CodeGenFunction &CGF)
Get the id of the current lane in the Warp.
static llvm::Value * getThreadLimit (CodeGenFunction &CGF, bool IsInSPMDExecutionMode=false)
Get the value of the thread_limit clause in the teams directive.
static llvm::Value * getMasterThreadID (CodeGenFunction &CGF)
Get the thread id of the OMP master thread.
static CGOpenMPRuntimeGPU::DataSharingMode getDataSharingMode (CodeGenModule &CGM)
static bool hasNestedSPMDDirective (ASTContext &Ctx, const OMPExecutableDirective &D)
Check for inner (nested) SPMD construct, if any.
static bool supportsSPMDExecutionMode (ASTContext &Ctx, const OMPExecutableDirective &D)
static bool hasStaticScheduling (const OMPExecutableDirective &D)
Check if the directive is loops based and has schedule clause at all or has static scheduling.
static bool hasNestedLightweightDirective (ASTContext &Ctx, const OMPExecutableDirective &D)
Check for inner (nested) lightweight runtime construct, if any.
static bool supportsLightweightRuntime (ASTContext &Ctx, const OMPExecutableDirective &D)
Checks if the construct supports lightweight runtime.
static void setPropertyExecutionMode (CodeGenModule &CGM, StringRef Name, bool Mode)
static void getDistributeLastprivateVars (ASTContext &Ctx, const OMPExecutableDirective &D, llvm::SmallVectorImpl< const ValueDecl * > &Vars)
Get list of lastprivate variables from the teams distribute ... or teams {distribute ...} directives.
static void getTeamsReductionVars (ASTContext &Ctx, const OMPExecutableDirective &D, llvm::SmallVectorImpl< const ValueDecl * > &Vars)
Get list of reduction variables from the teams ... directives.
static llvm::Value * castValueToType (CodeGenFunction &CGF, llvm::Value *Val, QualType ValTy, QualType CastTy, SourceLocation Loc)
Cast value to the specified type.
static llvm::Value * createRuntimeShuffleFunction (CodeGenFunction &CGF, llvm::Value *Elem, QualType ElemType, llvm::Value *Offset, SourceLocation Loc)
This function creates calls to one of two shuffle functions to copy variables between lanes in a warp.
static void shuffleAndStore (CodeGenFunction &CGF, Address SrcAddr, Address DestAddr, QualType ElemType, llvm::Value *Offset, SourceLocation Loc)
static void emitReductionListCopy (CopyAction Action, CodeGenFunction &CGF, QualType ReductionArrayTy, ArrayRef< const Expr * > Privates, Address SrcBase, Address DestBase, CopyOptionsTy CopyOptions={nullptr, nullptr, nullptr})
Emit instructions to copy a Reduce list, which contains partially aggregated values, in the specified direction.
static llvm::Value * emitInterWarpCopyFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc)
This function emits a helper that gathers Reduce lists from the first lane of every active warp to lanes in the first warp.
static llvm::Function * emitShuffleAndReduceFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, llvm::Function *ReduceFn, SourceLocation Loc)
Emit a helper that reduces data across two OpenMP threads (lanes) in the same warp.
static llvm::Value * emitListToGlobalCopyFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl *TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > &VarFieldMap)
This function emits a helper that copies all the reduction variables from the team into the provided global buffer for the reduction variables.
static llvm::Value * emitListToGlobalReduceFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl *TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > &VarFieldMap, llvm::Function *ReduceFn)
This function emits a helper that reduces all the reduction variables from the team into the provided global buffer for the reduction variables.
static llvm::Value * emitGlobalToListCopyFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl *TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > &VarFieldMap)
This function emits a helper that copies all the reduction variables from the team into the provided global buffer for the reduction variables.
static llvm::Value * emitGlobalToListReduceFunction (CodeGenModule &CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl *TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > &VarFieldMap, llvm::Function *ReduceFn)
This function emits a helper that reduces all the reduction variables from the team into the provided global buffer for the reduction variables.
static CudaArch getCudaArch (CodeGenModule &CGM)
static std::pair< unsigned, unsigned > getSMsBlocksPerSM (CodeGenModule &CGM)
Get number of SMs and number of blocks per SM.
Function Documentation
castValueToType()
static llvm::Value * castValueToType (CodeGenFunction & CGF, llvm::Value * Val, QualType ValTy, QualType CastTy, SourceLocation Loc) static
Cast value to the specified type.
Definition at line 2432 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::Address::getAddressSpace(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getType(), clang::ASTContext::getTypeSizeInChars(), clang::Type::hasSignedIntegerRepresentation(), clang::Type::isIntegerType(), clang::CharUnits::isZero(), and clang::CodeGen::Type.
Referenced by createRuntimeShuffleFunction().
createRuntimeShuffleFunction()
static llvm::Value * createRuntimeShuffleFunction (CodeGenFunction & CGF, llvm::Value * Elem, QualType ElemType, llvm::Value * Offset, SourceLocation Loc) static
This function creates calls to one of two shuffle functions to copy variables between lanes in a warp.
Definition at line 2461 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, castValueToType(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitRuntimeCall(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUWarpSize(), clang::ASTContext::getIntTypeForBitwidth(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::ASTContext::getTypeSizeInChars(), and clang::CodeGen::CodeGenTypeCache::Int16Ty.
Referenced by shuffleAndStore().
emitGlobalToListCopyFunction()
static llvm::Value * emitGlobalToListCopyFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl * TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > & VarFieldMap) static
This function emits a helper that copies all the reduction variables from the team into the provided global buffer for the reduction variables.
void list_to_global_copy_func(void *buffer, int Idx, void *reduce_data) For all data entries D in reduce_data: Copy buffer.D[Idx] to local D;
Definition at line 3465 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitLoadOfComplex(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfComplex(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, clang::CodeGen::Type, and V.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
emitGlobalToListReduceFunction()
static llvm::Value * emitGlobalToListReduceFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl * TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > & VarFieldMap, llvm::Function * ReduceFn) static
This function emits a helper that reduces all the reduction variables from the team into the provided global buffer for the reduction variables.
void global_to_list_reduce_func(void <em>buffer, int Idx, void *reduce_data) void *GlobPtrs[]; GlobPtrs[0] = (void)&buffer.D0[Idx]; ... GlobPtrs[N] = (void*)&buffer.DN[Idx]; reduce_function(reduce_data, GlobPtrs);
Definition at line 3573 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitCastToVoidPtr(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CGOpenMPRuntime::emitOutlinedFunctionCall(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenFunction::getVLASize(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenTypeCache::SizeTy, clang::CodeGen::CodeGenFunction::StartFunction(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
emitInterWarpCopyFunction()
static llvm::Value * emitInterWarpCopyFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc) static
This function emits a helper that gathers Reduce lists from the first lane of every active warp to lanes in the first warp.
void inter_warp_copy_func(void* reduce_data, num_warps) shared smem[warp_size]; For all data entries D in reduce_data: sync If (I am the first lane in each warp) Copy my local D to smem[warp_id] sync if (I am the first warp) Copy smem[thread_id] to my local D
Definition at line 2807 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenModule::addCompilerUsedGlobal(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::ApplyDebugLocation::CreateEmpty(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::cuda_shared, clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitBranch(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CharUnits::fromQuantity(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUThreadID(), clang::TargetInfo::getGridValue(), clang::CodeGen::CodeGenModule::getModule(), getNVPTXLaneID(), getNVPTXWarpID(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenFunction::getTarget(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CodeGenTypeCache::IntTy, clang::CodeGen::Address::invalid(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::CodeGen::Type.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
emitListToGlobalCopyFunction()
static llvm::Value * emitListToGlobalCopyFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl * TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > & VarFieldMap) static
This function emits a helper that copies all the reduction variables from the team into the provided global buffer for the reduction variables.
void list_to_global_copy_func(void *buffer, int Idx, void *reduce_data) For all data entries D in reduce_data: Copy local D to buffer.D[Idx]
Definition at line 3262 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitLoadOfComplex(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfComplex(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::Address::getType(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, clang::CodeGen::Type, and V.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
emitListToGlobalReduceFunction()
static llvm::Value * emitListToGlobalReduceFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, SourceLocation Loc, const RecordDecl * TeamReductionRec, const llvm::SmallDenseMap< const ValueDecl *, const FieldDecl * > & VarFieldMap, llvm::Function * ReduceFn) static
This function emits a helper that reduces all the reduction variables from the team into the provided global buffer for the reduction variables.
void list_to_global_reduce_func(void <em>buffer, int Idx, void *reduce_data) void *GlobPtrs[]; GlobPtrs[0] = (void)&buffer.D0[Idx]; ... GlobPtrs[N] = (void*)&buffer.DN[Idx]; reduce_function(GlobPtrs, reduce_data);
Definition at line 3369 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitCastToVoidPtr(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CGOpenMPRuntime::emitOutlinedFunctionCall(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenFunction::getVLASize(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenTypeCache::SizeTy, clang::CodeGen::CodeGenFunction::StartFunction(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
emitReductionListCopy()
static void emitReductionListCopy (CopyAction Action, CodeGenFunction & CGF, QualType ReductionArrayTy, ArrayRef< const Expr * > Privates, Address SrcBase, Address DestBase, CopyOptionsTy CopyOptions = {nullptr, nullptr, nullptr}) static
Emit instructions to copy a Reduce list, which contains partially aggregated values, in the specified direction.
Definition at line 2599 of file CGOpenMPRuntimeGPU.cpp.
Referenced by emitShuffleAndReduceFunction().
emitShuffleAndReduceFunction()
static llvm::Function * emitShuffleAndReduceFunction (CodeGenModule & CGM, ArrayRef< const Expr * > Privates, QualType ReductionArrayTy, llvm::Function * ReduceFn, SourceLocation Loc) static
Emit a helper that reduces data across two OpenMP threads (lanes) in the same warp.
It uses shuffle instructions to copy over data from a remote lane's stack. The reduction algorithm performed is specified by the fourth parameter.
Algorithm Versions. Full Warp Reduce (argument value 0): This algorithm assumes that all 32 lanes are active and gathers data from these 32 lanes, producing a single resultant value. Contiguous Partial Warp Reduce (argument value 1): This algorithm assumes that only a contiguous subset of lanes are active. This happens for the last warp in a parallel region when the user specified num_threads is not an integer multiple of
This contiguous subset always starts with the zeroth lane. Partial Warp Reduce (argument value 2): This algorithm gathers data from any number of lanes at any position. All reduced values are stored in the lowest possible lane. The set of problems every algorithm addresses is a super set of those addressable by algorithms with a lower version number. Overhead increases as algorithm version increases.
Terminology Reduce element: Reduce element refers to the individual data field with primitive data types to be combined and reduced across threads. Reduce list: Reduce list refers to a collection of local, thread-private reduce elements. Remote Reduce list: Remote Reduce list refers to a collection of remote (relative to the current thread) reduce elements.
We distinguish between three states of threads that are important to the implementation of this function. Alive threads: Threads in a warp executing the SIMT instruction, as distinguished from threads that are inactive due to divergent control flow. Active threads: The minimal set of threads that has to be alive upon entry to this function. The computation is correct iff active threads are alive. Some threads are alive but they are not active because they do not contribute to the computation in any useful manner. Turning them off may introduce control flow overheads without any tangible benefits. Effective threads: In order to comply with the argument requirements of the shuffle function, we must keep all lanes holding data alive. But at most half of them perform value aggregation; we refer to this half of threads as effective. The other half is simply handing off their data.
Procedure Value shuffle: In this step active threads transfer data from higher lane positions in the warp to lower lane positions, creating Remote Reduce list. Value aggregation: In this step, effective threads combine their thread local Reduce list with Remote Reduce list and store the result in the thread local Reduce list. Value copy: In this step, we deal with the assumption made by algorithm 2 (i.e. contiguity assumption). When we have an odd number of lanes active, say 2k+1, only k threads will be effective and therefore k new values will be produced. However, the Reduce list owned by the (2k+1)th thread is ignored in the value aggregation. Therefore we copy the Reduce list from the (2k+1)th lane to (k+1)th lane so that the contiguity assumption still holds.
Definition at line 3105 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CGOpenMPRuntime::emitOutlinedFunctionCall(), emitReductionListCopy(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenModule::getTypes(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction().
getCudaArch()
static CudaArch getCudaArch (CodeGenModule & CGM) static
Definition at line 4572 of file CGOpenMPRuntimeGPU.cpp.
References clang::TargetOptions::FeatureMap, clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTargetOpts(), clang::TargetInfo::hasFeature(), clang::StringToCudaArch(), and clang::UNKNOWN.
Referenced by getSMsBlocksPerSM(), and clang::CodeGen::CGOpenMPRuntimeGPU::processRequiresDirective().
getDataSharingMode()
static CGOpenMPRuntimeGPU::DataSharingMode getDataSharingMode (CodeGenModule & CGM) static
Definition at line 613 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CGOpenMPRuntimeGPU::CUDA, clang::CodeGen::CGOpenMPRuntimeGPU::Generic, and clang::CodeGen::CodeGenModule::getLangOpts().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog(), and clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable().
getDistributeLastprivateVars()
static void getDistributeLastprivateVars (ASTContext & Ctx, const OMPExecutableDirective & D, llvm::SmallVectorImpl< const ValueDecl * > & Vars) static
Get list of lastprivate variables from the teams distribute ... or teams {distribute ...} directives.
Definition at line 1594 of file CGOpenMPRuntimeGPU.cpp.
References clang::C, clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), getPrivateItem(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::Stmt::IgnoreContainers(), clang::isOpenMPDistributeDirective(), and clang::isOpenMPTeamsDirective().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction().
getMasterThreadID()
static llvm::Value * getMasterThreadID (CodeGenFunction & CGF) static
Get the thread id of the OMP master thread.
The master thread id is the first thread (lane) of the last warp in the GPU block. Warp size is assumed to be some power of 2. Thread id is 0 indexed. E.g: If NumThreads is 33, master id is 32. If NumThreads is 64, master id is 32. If NumThreads is 1024, master id is 992.
Definition at line 578 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntimeGPU::getGPUNumThreads(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
getNVPTXLaneID()
static llvm::Value * getNVPTXLaneID (CodeGenFunction & CGF) static
Get the id of the current lane in the Warp.
We assume that the warp size is 32, which is always the case on the NVPTX device, to generate more efficient code.
Definition at line 547 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::getContext(), clang::TargetInfo::getGridValue(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::ASTContext::getTargetInfo().
Referenced by emitInterWarpCopyFunction().
getNVPTXWarpID()
static llvm::Value * getNVPTXWarpID (CodeGenFunction & CGF) static
Get the id of the warp in the block.
We assume that the warp size is 32, which is always the case on the NVPTX device, to generate more efficient code.
Definition at line 536 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::TargetInfo::getGridValue(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CodeGen::CodeGenFunction::getTarget().
Referenced by emitInterWarpCopyFunction().
getSMsBlocksPerSM()
static std::pair< unsigned, unsigned > getSMsBlocksPerSM (CodeGenModule & CGM) static
Get number of SMs and number of blocks per SM.
Definition at line 4656 of file CGOpenMPRuntimeGPU.cpp.
References getCudaArch(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::GFX1010, clang::GFX1011, clang::GFX1012, clang::GFX1030, clang::GFX1031, clang::GFX1032, clang::GFX1033, clang::GFX600, clang::GFX601, clang::GFX602, clang::GFX700, clang::GFX701, clang::GFX702, clang::GFX703, clang::GFX704, clang::GFX705, clang::GFX801, clang::GFX802, clang::GFX803, clang::GFX805, clang::GFX810, clang::GFX900, clang::GFX902, clang::GFX904, clang::GFX906, clang::GFX908, clang::GFX909, clang::GFX90c, clang::LAST, clang::SM_20, clang::SM_21, clang::SM_30, clang::SM_32, clang::SM_35, clang::SM_37, clang::SM_50, clang::SM_52, clang::SM_53, clang::SM_60, clang::SM_61, clang::SM_62, clang::SM_70, clang::SM_72, clang::SM_75, clang::SM_80, clang::UNKNOWN, and clang::UNUSED.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::clear().
getTeamsReductionVars()
static void getTeamsReductionVars (ASTContext & Ctx, const OMPExecutableDirective & D, llvm::SmallVectorImpl< const ValueDecl * > & Vars) static
Get list of reduction variables from the teams ... directives.
Definition at line 1619 of file CGOpenMPRuntimeGPU.cpp.
References clang::C, clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), getPrivateItem(), and clang::isOpenMPTeamsDirective().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction().
getThreadLimit()
static llvm::Value * getThreadLimit (CodeGenFunction & CGF, bool IsInSPMDExecutionMode = false) static
Get the value of the thread_limit clause in the teams directive.
For the 'generic' execution mode, the runtime encodes thread_limit in the launch parameters, always starting thread_limit+warpSize threads per CTA. The threads in the last warp are reserved for master execution. For the 'spmd' execution mode, all threads in a CTA are part of the team.
Definition at line 561 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntimeGPU::getGPUNumThreads(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
hasNestedLightweightDirective()
static bool hasNestedLightweightDirective (ASTContext & Ctx, const OMPExecutableDirective & D) static
Check for inner (nested) lightweight runtime construct, if any.
Definition at line 816 of file CGOpenMPRuntimeGPU.cpp.
References clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), hasStaticScheduling(), clang::Stmt::IgnoreContainers(), clang::isOpenMPLoopDirective(), clang::isOpenMPParallelDirective(), clang::isOpenMPWorksharingDirective(), and supportsSPMDExecutionMode().
Referenced by supportsLightweightRuntime().
hasNestedSPMDDirective()
static bool hasNestedSPMDDirective (ASTContext & Ctx, const OMPExecutableDirective & D) static
Check for inner (nested) SPMD construct, if any.
Definition at line 619 of file CGOpenMPRuntimeGPU.cpp.
References clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::Stmt::IgnoreContainers(), and clang::isOpenMPParallelDirective().
Referenced by supportsSPMDExecutionMode().
hasStaticScheduling()
static bool hasStaticScheduling (const OMPExecutableDirective & D) static
Check if the directive is loops based and has schedule clause at all or has static scheduling.
Definition at line 803 of file CGOpenMPRuntimeGPU.cpp.
References clang::C, clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::hasClausesOfKind(), clang::isOpenMPLoopDirective(), and clang::isOpenMPWorksharingDirective().
Referenced by hasNestedLightweightDirective(), and supportsLightweightRuntime().
setPropertyExecutionMode()
static void setPropertyExecutionMode (CodeGenModule & CGM, StringRef Name, bool Mode) static
Definition at line 1307 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenModule::addCompilerUsedGlobal(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenModule::getModule(), and clang::CodeGen::CodeGenTypeCache::Int8Ty.
shuffleAndStore()
static void shuffleAndStore (CodeGenFunction & CGF, Address SrcAddr, Address DestAddr, QualType ElemType, llvm::Value * Offset, SourceLocation Loc) static
Definition at line 2494 of file CGOpenMPRuntimeGPU.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateConstGEP(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), createRuntimeShuffleFunction(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitBranch(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CharUnits::fromQuantity(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getIntTypeForBitwidth(), clang::CodeGen::Address::getPointer(), clang::CodeGen::Address::getType(), clang::ASTContext::getTypeSizeInChars(), Offset, clang::ASTContext::toBits(), clang::CodeGen::Type, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
supportsLightweightRuntime()
static bool supportsLightweightRuntime (ASTContext & Ctx, const OMPExecutableDirective & D) static
Checks if the construct supports lightweight runtime.
It must be SPMD construct + inner loop-based construct with static scheduling.
Definition at line 978 of file CGOpenMPRuntimeGPU.cpp.
References clang::OMPExecutableDirective::getDirectiveKind(), hasNestedLightweightDirective(), hasStaticScheduling(), and supportsSPMDExecutionMode().
supportsSPMDExecutionMode()
static bool supportsSPMDExecutionMode (ASTContext & Ctx, const OMPExecutableDirective & D) static
Definition at line 721 of file CGOpenMPRuntimeGPU.cpp.
References clang::OMPExecutableDirective::getDirectiveKind(), and hasNestedSPMDDirective().
Referenced by hasNestedLightweightDirective(), and supportsLightweightRuntime().