clang: lib/CodeGen/CGOpenMPRuntime.cpp File Reference
CGOpenMPRuntime.cpp File Reference
#include "CGOpenMPRuntime.h"
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/BitmaskEnum.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/SourceManager.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <numeric>
Functions
static const OMPDeclareReductionDecl * getReductionInit (const Expr *ReductionOp)
Check if the combiner is a call to UDR combiner and if it is so return the UDR decl used for reduction.
static void emitInitWithReductionInitializer (CodeGenFunction &CGF, const OMPDeclareReductionDecl *DRD, const Expr *InitOp, Address Private, Address Original, QualType Ty)
static void EmitOMPAggregateInit (CodeGenFunction &CGF, Address DestAddr, QualType Type, bool EmitDeclareReductionInit, const Expr *Init, const OMPDeclareReductionDecl *DRD, Address SrcAddr=Address::invalid())
Emit initialization of arrays of complex types.
static LValue loadToBegin (CodeGenFunction &CGF, QualType BaseTy, QualType ElTy, LValue BaseLV)
static Address castToBase (CodeGenFunction &CGF, QualType BaseTy, QualType ElTy, llvm::Type *BaseLVType, CharUnits BaseLVAlignment, llvm::Value *Addr)
static const VarDecl * getBaseDecl (const Expr *Ref, const DeclRefExpr *&DE)
static FieldDecl * addFieldToRecordDecl (ASTContext &C, DeclContext *DC, QualType FieldTy)
static llvm::Function * emitCombinerOrInitializer (CodeGenModule &CGM, QualType Ty, const Expr *CombinerInitializer, const VarDecl *In, const VarDecl *Out, bool IsCombiner)
static llvm::Function * emitParallelOrTeamsOutlinedFunction (CodeGenModule &CGM, const OMPExecutableDirective &D, const CapturedStmt *CS, const VarDecl *ThreadIDVar, OpenMPDirectiveKind InnermostKind, const StringRef OutlinedHelperName, const RegionCodeGenTy &CodeGen)
static void buildStructValue (ConstantStructBuilder &Fields, CodeGenModule &CGM, const RecordDecl *RD, const CGRecordLayout &RL, ArrayRef< llvm::Constant * > Data)
template<class... As>
static llvm::GlobalVariable * createGlobalStruct (CodeGenModule &CGM, QualType Ty, bool IsConstant, ArrayRef< llvm::Constant * > Data, const Twine &Name, As &&... Args)
template<typename T >
static void createConstantGlobalStructAndAddToParent (CodeGenModule &CGM, QualType Ty, ArrayRef< llvm::Constant * > Data, T &Parent)
static StringRef getIdentStringFromSourceLocation (CodeGenFunction &CGF, SourceLocation Loc, SmallString< 128 > &Buffer)
static void getTargetEntryUniqueInfo (ASTContext &C, SourceLocation Loc, unsigned &DeviceID, unsigned &FileID, unsigned &LineNum)
Obtain information that uniquely identifies a target entry.
static Address emitAddrOfVarFromArray (CodeGenFunction &CGF, Address Array, unsigned Index, const VarDecl *Var)
Given an array of pointers to variables, project the address of a given variable.
static llvm::Value * emitCopyprivateCopyFunction (CodeGenModule &CGM, llvm::Type *ArgsType, ArrayRef< const Expr * > CopyprivateVars, ArrayRef< const Expr * > DestExprs, ArrayRef< const Expr * > SrcExprs, ArrayRef< const Expr * > AssignmentOps, SourceLocation Loc)
static OpenMPSchedType getRuntimeSchedule (OpenMPScheduleClauseKind ScheduleKind, bool Chunked, bool Ordered)
Map the OpenMP loop schedule to the runtime enumeration.
static OpenMPSchedType getRuntimeSchedule (OpenMPDistScheduleClauseKind ScheduleKind, bool Chunked)
Map the OpenMP distribute schedule to the runtime enumeration.
static int addMonoNonMonoModifier (CodeGenModule &CGM, OpenMPSchedType Schedule, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2)
static void emitForStaticInitCall (CodeGenFunction &CGF, llvm::Value *UpdateLocation, llvm::Value *ThreadId, llvm::FunctionCallee ForStaticInitFunction, OpenMPSchedType Schedule, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, const CGOpenMPRuntime::StaticRTInput &Values)
static bool isAllocatableDecl (const VarDecl *VD)
static RecordDecl * createPrivatesRecordDecl (CodeGenModule &CGM, ArrayRef< PrivateDataTy > Privates)
static RecordDecl * createKmpTaskTRecordDecl (CodeGenModule &CGM, OpenMPDirectiveKind Kind, QualType KmpInt32Ty, QualType KmpRoutineEntryPointerQTy)
static RecordDecl * createKmpTaskTWithPrivatesRecordDecl (CodeGenModule &CGM, QualType KmpTaskTQTy, ArrayRef< PrivateDataTy > Privates)
static llvm::Function * emitProxyTaskFunction (CodeGenModule &CGM, SourceLocation Loc, OpenMPDirectiveKind Kind, QualType KmpInt32Ty, QualType KmpTaskTWithPrivatesPtrQTy, QualType KmpTaskTWithPrivatesQTy, QualType KmpTaskTQTy, QualType SharedsPtrTy, llvm::Function *TaskFunction, llvm::Value *TaskPrivatesMap)
Emit a proxy function which accepts kmp_task_t as the second argument.
static llvm::Value * emitDestructorsFunction (CodeGenModule &CGM, SourceLocation Loc, QualType KmpInt32Ty, QualType KmpTaskTWithPrivatesPtrQTy, QualType KmpTaskTWithPrivatesQTy)
static llvm::Value * emitTaskPrivateMappingFunction (CodeGenModule &CGM, SourceLocation Loc, const OMPTaskDataTy &Data, QualType PrivatesQTy, ArrayRef< PrivateDataTy > Privates)
Emit a privates mapping function for correct handling of private and firstprivate variables.
static void emitPrivatesInit (CodeGenFunction &CGF, const OMPExecutableDirective &D, Address KmpTaskSharedsPtr, LValue TDBase, const RecordDecl *KmpTaskTWithPrivatesQTyRD, QualType SharedsTy, QualType SharedsPtrTy, const OMPTaskDataTy &Data, ArrayRef< PrivateDataTy > Privates, bool ForDup)
Emit initialization for private variables in task-based directives.
static bool checkInitIsRequired (CodeGenFunction &CGF, ArrayRef< PrivateDataTy > Privates)
Check if duplication function is required for taskloops.
static llvm::Value * emitTaskDupFunction (CodeGenModule &CGM, SourceLocation Loc, const OMPExecutableDirective &D, QualType KmpTaskTWithPrivatesPtrQTy, const RecordDecl *KmpTaskTWithPrivatesQTyRD, const RecordDecl *KmpTaskTQTyRD, QualType SharedsTy, QualType SharedsPtrTy, const OMPTaskDataTy &Data, ArrayRef< PrivateDataTy > Privates, bool WithLastIter)
Emit task_dup function (for initialization of private/firstprivate/lastprivate vars and last_iter flag)
static bool checkDestructorsRequired (const RecordDecl *KmpTaskTWithPrivatesQTyRD, ArrayRef< PrivateDataTy > Privates)
Checks if destructor function is required to be generated.
static std::pair< llvm::Value *, llvm::Value * > getPointerAndSize (CodeGenFunction &CGF, const Expr *E)
static void getKmpAffinityType (ASTContext &C, QualType &KmpTaskAffinityInfoTy)
Builds kmp_depend_info, if it is not built yet, and builds flags type.
static RTLDependenceKindTy translateDependencyKind (OpenMPDependClauseKind K)
Translates internal dependency kind into the runtime kind.
static void getDependTypes (ASTContext &C, QualType &KmpDependInfoTy, QualType &FlagsTy)
Builds kmp_depend_info, if it is not built yet, and builds flags type.
static void emitDependData (CodeGenFunction &CGF, QualType &KmpDependInfoTy, llvm::PointerUnion< unsigned *, LValue * > Pos, const OMPTaskDataTy::DependData &Data, Address DependenciesArray)
static SmallVector< llvm::Value *, 4 > emitDepobjElementsSizes (CodeGenFunction &CGF, QualType &KmpDependInfoTy, const OMPTaskDataTy::DependData &Data)
static void emitDepobjElements (CodeGenFunction &CGF, QualType &KmpDependInfoTy, LValue PosLVal, const OMPTaskDataTy::DependData &Data, Address DependenciesArray)
static void EmitOMPAggregateReduction (CodeGenFunction &CGF, QualType Type, const VarDecl *LHSVar, const VarDecl *RHSVar, const llvm::function_ref< void(CodeGenFunction &CGF, const Expr *, const Expr *, const Expr *)> &RedOpGen, const Expr *XExpr=nullptr, const Expr *EExpr=nullptr, const Expr *UpExpr=nullptr)
Emit reduction operation for each element of array (required for array sections) LHS op = RHS.
static void emitReductionCombiner (CodeGenFunction &CGF, const Expr *ReductionOp)
Emit reduction combiner.
static std::string generateUniqueName (CodeGenModule &CGM, StringRef Prefix, const Expr *Ref)
Generates unique name for artificial threadprivate variables.
static llvm::Value * emitReduceInitFunction (CodeGenModule &CGM, SourceLocation Loc, ReductionCodeGen &RCG, unsigned N)
Emits reduction initializer function:
static llvm::Value * emitReduceCombFunction (CodeGenModule &CGM, SourceLocation Loc, ReductionCodeGen &RCG, unsigned N, const Expr *ReductionOp, const Expr *LHS, const Expr *RHS, const Expr *PrivateRef)
Emits reduction combiner function:
static llvm::Value * emitReduceFiniFunction (CodeGenModule &CGM, SourceLocation Loc, ReductionCodeGen &RCG, unsigned N)
Emits reduction finalizer function:
static RTCancelKind getCancellationKind (OpenMPDirectiveKind CancelRegion)
static bool isTrivial (ASTContext &Ctx, const Expr *E)
Checks if the expression is constant or does not have non-trivial function calls.
static llvm::Value * emitNumTeamsForTargetDirective (CodeGenFunction &CGF, const OMPExecutableDirective &D)
Emit the number of teams for a target directive.
static llvm::Value * getNumThreads (CodeGenFunction &CGF, const CapturedStmt *CS, llvm::Value *DefaultThreadLimitVal)
static llvm::Value * emitNumThreadsForTargetDirective (CodeGenFunction &CGF, const OMPExecutableDirective &D)
Emit the number of threads for a target directive.
static void emitNonContiguousDescriptor (CodeGenFunction &CGF, MappableExprsHandler::MapCombinedInfoTy &CombinedInfo, CGOpenMPRuntime::TargetDataInfo &Info)
llvm::Constant * emitMappingInformation (CodeGenFunction &CGF, llvm::OpenMPIRBuilder &OMPBuilder, MappableExprsHandler::MappingExprInfo &MapExprs)
Emit a string constant containing the names of the values mapped to the offloading runtime library.
static void emitOffloadingArrays (CodeGenFunction &CGF, MappableExprsHandler::MapCombinedInfoTy &CombinedInfo, CGOpenMPRuntime::TargetDataInfo &Info, llvm::OpenMPIRBuilder &OMPBuilder, bool IsNonContiguous=false)
Emit the arrays used to pass the captures and map information to the offloading runtime library.
static void emitOffloadingArraysArgument (CodeGenFunction &CGF, llvm::Value *&BasePointersArrayArg, llvm::Value *&PointersArrayArg, llvm::Value *&SizesArrayArg, llvm::Value *&MapTypesArrayArg, llvm::Value *&MapNamesArrayArg, llvm::Value *&MappersArrayArg, CGOpenMPRuntime::TargetDataInfo &Info, const ArgumentsOptions &Options=ArgumentsOptions())
Emit the arguments to be passed to the runtime library based on the arrays of base pointers, pointers, sizes, map types, and mappers.
static const OMPExecutableDirective * getNestedDistributeDirective (ASTContext &Ctx, const OMPExecutableDirective &D)
Check for inner distribute directive.
static unsigned evaluateCDTSize (const FunctionDecl *FD, ArrayRef< ParamAttrTy > ParamAttrs)
static void emitX86DeclareSimdFunction (const FunctionDecl *FD, llvm::Function *Fn, const llvm::APSInt &VLENVal, ArrayRef< ParamAttrTy > ParamAttrs, OMPDeclareSimdDeclAttr::BranchStateTy State)
static bool getAArch64MTV (QualType QT, ParamKindTy Kind)
Maps To Vector (MTV), as defined in 3.1.1 of the AAVFABI.
static bool getAArch64PBV (QualType QT, ASTContext &C)
Pass By Value (PBV), as defined in 3.1.2 of the AAVFABI.
static unsigned getAArch64LS (QualType QT, ParamKindTy Kind, ASTContext &C)
Computes the lane size (LS) of a return type or of an input parameter, as defined by LS(P) in 3.2.1 of the AAVFABI.
static std::tuple< unsigned, unsigned, bool > getNDSWDS (const FunctionDecl *FD, ArrayRef< ParamAttrTy > ParamAttrs)
static std::string mangleVectorParameters (ArrayRef< ParamAttrTy > ParamAttrs)
Mangle the parameter part of the vector function name according to their OpenMP classification.
template<typename T >
static void addAArch64VectorName (T VLEN, StringRef LMask, StringRef Prefix, char ISA, StringRef ParSeq, StringRef MangledName, bool OutputBecomesInput, llvm::Function *Fn)
static void addAArch64AdvSIMDNDSNames (unsigned NDS, StringRef Mask, StringRef Prefix, char ISA, StringRef ParSeq, StringRef MangledName, bool OutputBecomesInput, llvm::Function *Fn)
static void emitAArch64DeclareSimdFunction (CodeGenModule &CGM, const FunctionDecl *FD, unsigned UserVLEN, ArrayRef< ParamAttrTy > ParamAttrs, OMPDeclareSimdDeclAttr::BranchStateTy State, StringRef MangledName, char ISA, unsigned VecRegSize, llvm::Function *Fn, SourceLocation SLoc)
Emit vector function attributes for AArch64, as defined in the AAVFABI.
Function Documentation
addAArch64AdvSIMDNDSNames()
static void addAArch64AdvSIMDNDSNames (unsigned NDS, StringRef Mask, StringRef Prefix, char ISA, StringRef ParSeq, StringRef MangledName, bool OutputBecomesInput, llvm::Function * Fn) static
Definition at line 11380 of file CGOpenMPRuntime.cpp.
References addAArch64VectorName().
Referenced by emitAArch64DeclareSimdFunction().
addAArch64VectorName()
template<typename T > static void addAArch64VectorName (T VLEN, StringRef LMask, StringRef Prefix, char ISA, StringRef ParSeq, StringRef MangledName, bool OutputBecomesInput, llvm::Function * Fn) static
Definition at line 11365 of file CGOpenMPRuntime.cpp.
Referenced by addAArch64AdvSIMDNDSNames(), and emitAArch64DeclareSimdFunction().
addFieldToRecordDecl()
static FieldDecl * addFieldToRecordDecl (ASTContext & C, DeclContext * DC, QualType FieldTy) static
Definition at line 1057 of file CGOpenMPRuntime.cpp.
References clang::DeclContext::addDecl(), clang::AS_public, clang::C, clang::FieldDecl::Create(), and clang::ICIS_NoInit.
Referenced by createKmpTaskTRecordDecl(), createKmpTaskTWithPrivatesRecordDecl(), createPrivatesRecordDecl(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitNonContiguousDescriptor(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), getDependTypes(), and getKmpAffinityType().
addMonoNonMonoModifier()
static int addMonoNonMonoModifier (CodeGenModule & CGM, OpenMPSchedType Schedule, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2) static
Definition at line 2637 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::OMPC_SCHEDULE_MODIFIER_last, and clang::OMPC_SCHEDULE_MODIFIER_unknown.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitForDispatchInit(), and emitForStaticInitCall().
buildStructValue()
static void buildStructValue (ConstantStructBuilder & Fields, CodeGenModule & CGM, const RecordDecl * RD, const CGRecordLayout & RL, ArrayRef< llvm::Constant * > Data) static
Definition at line 1343 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::ConstantAggregateBuilderBase::add(), clang::RecordDecl::fields(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), and clang::CodeGen::CGRecordLayout::getLLVMType().
Referenced by createConstantGlobalStructAndAddToParent(), and createGlobalStruct().
castToBase()
static Address castToBase (CodeGenFunction & CGF, QualType BaseTy, QualType ElTy, llvm::Type * BaseLVType, CharUnits BaseLVAlignment, llvm::Value * Addr) static
Definition at line 951 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getElementType(), clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::CodeGen::Address::getPointer(), clang::ASTContext::hasSameType(), clang::CodeGen::Address::invalid(), clang::Type::isPointerType(), clang::Type::isReferenceType(), and clang::CodeGen::Address::isValid().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress().
checkDestructorsRequired()
static bool checkDestructorsRequired (const RecordDecl * KmpTaskTWithPrivatesQTyRD, ArrayRef< PrivateDataTy > Privates) static
Checks if destructor function is required to be generated.
Returns
true if cleanups are required, false otherwise.
Definition at line 4009 of file CGOpenMPRuntime.cpp.
References clang::QualType::isDestructedType(), and P.
checkInitIsRequired()
static bool checkInitIsRequired (CodeGenFunction & CGF, ArrayRef< PrivateDataTy > Privates) static
Check if duplication function is required for taskloops.
Definition at line 3910 of file CGOpenMPRuntime.cpp.
References clang::VarDecl::getAnyInitializer(), clang::isa(), and clang::CodeGen::CodeGenFunction::isTrivialInitializer().
createConstantGlobalStructAndAddToParent()
template<typename T > static void createConstantGlobalStructAndAddToParent (CodeGenModule & CGM, QualType Ty, ArrayRef< llvm::Constant * > Data, T & Parent) static
Definition at line 1378 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::ConstantAggregateBuilderTemplateBase< Impl, Traits >::beginStruct(), buildStructValue(), clang::cast(), clang::CodeGen::ConstantAggregateBuilderTemplateBase< Impl, Traits >::finishAndAddTo(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CGRecordLayout::getLLVMType(), clang::CodeGen::CodeGenModule::getTypes(), and Parent.
createGlobalStruct()
template<class... As> static llvm::GlobalVariable * createGlobalStruct (CodeGenModule & CGM, QualType Ty, bool IsConstant, ArrayRef< llvm::Constant * > Data, const Twine & Name, As &&... Args) static
Definition at line 1363 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::beginStruct(), buildStructValue(), clang::cast(), clang::CodeGen::ConstantAggregateBuilderTemplateBase< Impl, Traits >::finishAndCreateGlobal(), clang::ASTContext::getAlignOfGlobalVarInChars(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CGRecordLayout::getLLVMType(), and clang::CodeGen::CodeGenModule::getTypes().
Referenced by clang::CodeGen::CGOpenMPRuntime::createOffloadEntry().
createKmpTaskTRecordDecl()
static RecordDecl * createKmpTaskTRecordDecl (CodeGenModule & CGM, OpenMPDirectiveKind Kind, QualType KmpInt32Ty, QualType KmpRoutineEntryPointerQTy) static
Definition at line 3452 of file CGOpenMPRuntime.cpp.
References addFieldToRecordDecl(), clang::C, clang::CodeGen::CGOpenMPRuntime::CGM, clang::RecordDecl::completeDefinition(), clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getIntTypeForBitwidth(), clang::isOpenMPTaskLoopDirective(), clang::TagDecl::startDefinition(), and clang::TTK_Union.
createKmpTaskTWithPrivatesRecordDecl()
static RecordDecl * createKmpTaskTWithPrivatesRecordDecl (CodeGenModule & CGM, QualType KmpTaskTQTy, ArrayRef< PrivateDataTy > Privates) static
Definition at line 3498 of file CGOpenMPRuntime.cpp.
References addFieldToRecordDecl(), clang::C, clang::CodeGen::CGOpenMPRuntime::CGM, clang::RecordDecl::completeDefinition(), createPrivatesRecordDecl(), clang::CodeGen::CodeGenModule::getContext(), and clang::TagDecl::startDefinition().
createPrivatesRecordDecl()
static RecordDecl * createPrivatesRecordDecl (CodeGenModule & CGM, ArrayRef< PrivateDataTy > Privates) static
Definition at line 3418 of file CGOpenMPRuntime.cpp.
References clang::Decl::addAttr(), addFieldToRecordDecl(), clang::C, clang::CodeGen::CGOpenMPRuntime::CGM, clang::RecordDecl::completeDefinition(), clang::Decl::getAttrs(), clang::CodeGen::CodeGenModule::getContext(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::Decl::hasAttrs(), isAllocatableDecl(), clang::Type::isLValueReferenceType(), and clang::TagDecl::startDefinition().
Referenced by createKmpTaskTWithPrivatesRecordDecl().
emitAArch64DeclareSimdFunction()
static void emitAArch64DeclareSimdFunction (CodeGenModule & CGM, const FunctionDecl * FD, unsigned UserVLEN, ArrayRef< ParamAttrTy > ParamAttrs, OMPDeclareSimdDeclAttr::BranchStateTy State, StringRef MangledName, char ISA, unsigned VecRegSize, llvm::Function * Fn, SourceLocation SLoc) static
Emit vector function attributes for AArch64, as defined in the AAVFABI.
Definition at line 11415 of file CGOpenMPRuntime.cpp.
References addAArch64AdvSIMDNDSNames(), addAArch64VectorName(), clang::OMPDeclareSimdDeclAttr::BS_Inbranch, clang::OMPDeclareSimdDeclAttr::BS_Notinbranch, clang::OMPDeclareSimdDeclAttr::BS_Undefined, clang::CodeGen::CGOpenMPRuntime::CGM, clang::DiagnosticsEngine::getCustomDiagID(), clang::CodeGen::CodeGenModule::getDiags(), getNDSWDS(), mangleVectorParameters(), clang::DiagnosticsEngine::Report(), and clang::DiagnosticsEngine::Warning.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction().
emitAddrOfVarFromArray()
static Address emitAddrOfVarFromArray (CodeGenFunction & CGF, Address Array, unsigned Index, const VarDecl * Var) static
Given an array of pointers to variables, project the address of a given variable.
Definition at line 2314 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getDeclAlign(), and clang::ValueDecl::getType().
Referenced by emitCopyprivateCopyFunction(), and clang::CodeGen::CGOpenMPRuntime::emitReductionFunction().
emitCombinerOrInitializer()
static llvm::Function * emitCombinerOrInitializer (CodeGenModule & CGM, QualType Ty, const Expr * CombinerInitializer, const VarDecl * In, const VarDecl * Out, bool IsCombiner) static
Definition at line 1106 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::VarDecl::getInit(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::QualType::getQualifiers(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::VarDecl::hasInit(), clang::CodeGen::CodeGenFunction::isTrivialInitializer(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::QualType::withRestrict().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitUserDefinedReduction().
emitCopyprivateCopyFunction()
static llvm::Value * emitCopyprivateCopyFunction (CodeGenModule & CGM, llvm::Type * ArgsType, ArrayRef< const Expr * > CopyprivateVars, ArrayRef< const Expr * > DestExprs, ArrayRef< const Expr * > SrcExprs, ArrayRef< const Expr * > AssignmentOps, SourceLocation Loc) static
Definition at line 2326 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), emitAddrOfVarFromArray(), clang::CodeGen::CodeGenFunction::EmitOMPCopy(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenFunction::StartFunction().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitSingleRegion().
emitDependData()
static void emitDependData (CodeGenFunction & CGF, QualType & KmpDependInfoTy, llvm::PointerUnion< unsigned *, LValue * > Pos, const OMPTaskDataTy::DependData & Data, Address DependenciesArray) static
Definition at line 4619 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstGEP(), clang::CodeGen::OMPTaskDataTy::DependData::DepExprs, clang::CodeGen::OMPTaskDataTy::DependData::DepKind, clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::RecordDecl::field_begin(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenModule::getContext(), getDependTypes(), clang::Expr::getExprLoc(), clang::CodeGen::Address::getPointer(), getPointerAndSize(), clang::Expr::IgnoreParenImpCasts(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::OMPTaskDataTy::DependData::IteratorExpr, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), P, and translateDependencyKind().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDependClause(), and clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause().
emitDepobjElements()
static void emitDepobjElements (CodeGenFunction & CGF, QualType & KmpDependInfoTy, LValue PosLVal, const OMPTaskDataTy::DependData & Data, Address DependenciesArray) static
Definition at line 4736 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::OMPTaskDataTy::DependData::DepExprs, clang::CodeGen::OMPTaskDataTy::DependData::DepKind, clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::RecordDecl::field_begin(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenFunction::getContext(), getDependTypes(), clang::Expr::getExprLoc(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenFunction::getTypeSize(), clang::Expr::IgnoreParenImpCasts(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::OMPTaskDataTy::DependData::IteratorExpr, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDependClause().
emitDepobjElementsSizes()
static SmallVector< llvm::Value *, 4 > emitDepobjElementsSizes (CodeGenFunction & CGF, QualType & KmpDependInfoTy, const OMPTaskDataTy::DependData & Data) static
Definition at line 4679 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::OMPTaskDataTy::DependData::DepExprs, clang::CodeGen::OMPTaskDataTy::DependData::DepKind, clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::RecordDecl::field_begin(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenFunction::getContext(), getDependTypes(), clang::Expr::getExprLoc(), clang::CodeGen::Address::getPointer(), clang::Expr::IgnoreParenImpCasts(), clang::CodeGen::CodeGenFunction::InitTempAlloca(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::OMPTaskDataTy::DependData::IteratorExpr, and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDependClause().
emitDestructorsFunction()
static llvm::Value * emitDestructorsFunction (CodeGenModule & CGM, SourceLocation Loc, QualType KmpInt32Ty, QualType KmpTaskTWithPrivatesPtrQTy, QualType KmpTaskTWithPrivatesQTy) static
Definition at line 3629 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::cast(), clang::Type::castAs(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenModule::getTypes(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenFunction::pushDestroy(), clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::QualType::withRestrict().
emitForStaticInitCall()
static void emitForStaticInitCall (CodeGenFunction & CGF, llvm::Value * UpdateLocation, llvm::Value * ThreadId, llvm::FunctionCallee ForStaticInitFunction, OpenMPSchedType Schedule, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, const CGOpenMPRuntime::StaticRTInput & Values) static
Definition at line 2721 of file CGOpenMPRuntime.cpp.
References addMonoNonMonoModifier(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::StaticRTInput::Chunk, clang::CodeGen::CodeGenFunction::EmitRuntimeCall(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenFunction::HaveInsertPoint(), clang::CodeGen::CGOpenMPRuntime::StaticRTInput::IL, clang::CodeGen::CGOpenMPRuntime::StaticRTInput::IVSize, clang::CodeGen::CGOpenMPRuntime::StaticRTInput::LB, clang::CodeGen::CGOpenMPRuntime::StaticRTInput::Ordered, clang::CodeGen::CGOpenMPRuntime::StaticRTInput::ST, and clang::CodeGen::CGOpenMPRuntime::StaticRTInput::UB.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDistributeStaticInit(), and clang::CodeGen::CGOpenMPRuntime::emitForStaticInit().
emitInitWithReductionInitializer()
static void emitInitWithReductionInitializer (CodeGenFunction & CGF, const OMPDeclareReductionDecl * DRD, const Expr * InitOp, Address Private, Address Original, QualType Ty) static
Definition at line 617 of file CGOpenMPRuntime.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitLoadOfComplex(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getAggregate(), clang::CodeGen::RValue::getComplex(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::OMPDeclareReductionDecl::getInitializer(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::QualType::getQualifiers(), clang::CodeGen::CGOpenMPRuntime::getUserDefinedReduction(), clang::Expr::IgnoreParenImpCasts(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, and clang::VK_RValue.
Referenced by clang::CodeGen::ReductionCodeGen::emitInitialization(), and EmitOMPAggregateInit().
emitMappingInformation()
llvm::Constant * emitMappingInformation (CodeGenFunction & CGF, llvm::OpenMPIRBuilder & OMPBuilder, MappableExprsHandler::MappingExprInfo & MapExprs)
Emit a string constant containing the names of the values mapped to the offloading runtime library.
Definition at line 9117 of file CGOpenMPRuntime.cpp.
References clang::PresumedLoc::getColumn(), clang::CodeGen::CodeGenFunction::getContext(), clang::PresumedLoc::getFilename(), clang::ASTContext::getLangOpts(), clang::PresumedLoc::getLine(), clang::SourceManager::getPresumedLoc(), clang::ASTContext::getSourceManager(), clang::CodeGen::CGOpenMPRuntime::OMPBuilder, and P.
Referenced by emitOffloadingArrays(), and clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper().
emitNonContiguousDescriptor()
static void emitNonContiguousDescriptor (CodeGenFunction & CGF, MappableExprsHandler::MapCombinedInfoTy & CombinedInfo, CGOpenMPRuntime::TargetDataInfo & Info) static
Definition at line 9046 of file CGOpenMPRuntime.cpp.
References addFieldToRecordDecl(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::CGM, clang::RecordDecl::completeDefinition(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::RecordDecl::field_begin(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::ArrayType::Normal, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::NumberOfPtrs, P, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::PointersArray, clang::TagDecl::startDefinition(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by emitOffloadingArrays().
emitNumTeamsForTargetDirective()
static llvm::Value * emitNumTeamsForTargetDirective (CodeGenFunction & CGF, const OMPExecutableDirective & D) static
Emit the number of teams for a target directive.
Inspect the num_teams clause associated with a teams construct combined or closely nested with the target directive.
Emit a team of size one for directives such as 'target parallel' that have no associated teams construct.
Otherwise, return nullptr.
Definition at line 6567 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CapturedStmt::getCapturedStmt(), clang::CodeGen::CodeGenFunction::getContext(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::OMPExecutableDirective::getSingleClause(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::OMPExecutableDirective::hasClausesOfKind(), clang::Stmt::IgnoreContainers(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::isOpenMPParallelDirective(), clang::isOpenMPSimdDirective(), clang::isOpenMPTargetExecutionDirective(), and clang::isOpenMPTeamsDirective().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
emitNumThreadsForTargetDirective()
static llvm::Value * emitNumThreadsForTargetDirective (CodeGenFunction & CGF, const OMPExecutableDirective & D) static
Emit the number of threads for a target directive.
Inspect the thread_limit clause associated with a teams construct combined or closely nested with the target directive.
Emit the num_threads clause for directives such as 'target parallel' that have no associated teams construct.
Otherwise, return nullptr.
Definition at line 6792 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitAutoVarCleanups(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitVarDecl(), clang::Expr::EvaluateAsBooleanCondition(), clang::CodeGen::CodeGenFunction::EvaluateExprAsBool(), clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPIfClause::getCondition(), clang::CodeGen::CodeGenFunction::getContext(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CodeGenFunction::getLangOpts(), getNumThreads(), clang::OMPExecutableDirective::getSingleClause(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::OMPExecutableDirective::hasClausesOfKind(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::isOpenMPDistributeDirective(), clang::isOpenMPSimdDirective(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTeamsDirective(), and clang::Result.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
emitOffloadingArrays()
static void emitOffloadingArrays (CodeGenFunction & CGF, MappableExprsHandler::MapCombinedInfoTy & CombinedInfo, CGOpenMPRuntime::TargetDataInfo & Info, llvm::OpenMPIRBuilder & OMPBuilder, bool IsNonContiguous = false) static
Emit the arrays used to pass the captures and map information to the offloading runtime library.
If there is no map or capture information, return nullptr by reference.
Definition at line 9148 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::BasePointersArray, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::CaptureDeviceAddrMap, clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::clearArrayInfo(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32(), clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CGBuilderTy::CreateStore(), emitMappingInformation(), emitNonContiguousDescriptor(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::ASTContext::getConstantArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getIntTypeForBitwidth(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CGOpenMPRuntime::getOrCreateUserDefinedMapperFunc(), clang::CodeGen::Address::getPointer(), clang::ASTContext::getTypeAlignInChars(), clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::HasMapper, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapNamesArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MappersArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapTypesArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapTypesArrayEnd, clang::codegenoptions::NoDebugInfo, clang::ArrayType::Normal, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::NumberOfPtrs, clang::CodeGen::CGOpenMPRuntime::OMPBuilder, P, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::PointersArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::requiresDevicePointerInfo(), clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::separateBeginEndCalls(), clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::SizesArray, clang::ASTContext::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
emitOffloadingArraysArgument()
static void emitOffloadingArraysArgument (CodeGenFunction & CGF, llvm::Value *& BasePointersArrayArg, llvm::Value *& PointersArrayArg, llvm::Value *& SizesArrayArg, llvm::Value *& MapTypesArrayArg, llvm::Value *& MapNamesArrayArg, llvm::Value *& MappersArrayArg, CGOpenMPRuntime::TargetDataInfo & Info, const ArgumentsOptions & Options = ArgumentsOptions()) static
Emit the arguments to be passed to the runtime library based on the arrays of base pointers, pointers, sizes, map types, and mappers.
If ForEndCall, emit map types to be passed for the end of the region instead of the beginning.
Definition at line 9352 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::BasePointersArray, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::HasMapper, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapNamesArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MappersArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapTypesArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::MapTypesArrayEnd, clang::codegenoptions::NoDebugInfo, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::NumberOfPtrs, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::PointersArray, clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::separateBeginEndCalls(), clang::CodeGen::CGOpenMPRuntime::TargetDataInfo::SizesArray, clang::CodeGen::CodeGenTypeCache::VoidPtrPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
EmitOMPAggregateInit()
static void EmitOMPAggregateInit (CodeGenFunction & CGF, Address DestAddr, QualType Type, bool EmitDeclareReductionInit, const Expr * Init, const OMPDeclareReductionDecl * DRD, Address SrcAddr = Address::invalid()) static
Emit initialization of arrays of complex types.
Parameters
DestAddr Address of the array.
Type Type of array.
Init Initial expression of array.
SrcAddr Address of the original array.
Definition at line 674 of file CGOpenMPRuntime.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitBlock(), emitInitWithReductionInitializer(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsArrayTypeUnsafe(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::Address::getPointer(), clang::QualType::getQualifiers(), clang::ASTContext::getTypeSizeInChars(), and clang::CodeGen::Address::invalid().
EmitOMPAggregateReduction()
static void EmitOMPAggregateReduction (CodeGenFunction & CGF, QualType Type, const VarDecl * LHSVar, const VarDecl * RHSVar, const llvm::function_ref< void(CodeGenFunction &CGF, const Expr *, const Expr *, const Expr *)> & RedOpGen, const Expr * XExpr = nullptr, const Expr * EExpr = nullptr, const Expr * UpExpr = nullptr) static
Emit reduction operation for each element of array (required for array sections) LHS op = RHS.
Parameters
Type Type of array.
LHSVar Variable on the left side of the reduction operation (references element of array in original variable).
RHSVar Variable on the right side of the reduction operation (references element of array in original variable).
RedOpGen Generator of reduction operation with use of LHSVar and RHSVar.
Definition at line 5287 of file CGOpenMPRuntime.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsArrayTypeUnsafe(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getPointer(), and clang::ASTContext::getTypeSizeInChars().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), and clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner().
emitParallelOrTeamsOutlinedFunction()
static llvm::Function * emitParallelOrTeamsOutlinedFunction (CodeGenModule & CGM, const OMPExecutableDirective & D, const CapturedStmt * CS, const VarDecl * ThreadIDVar, OpenMPDirectiveKind InnermostKind, const StringRef OutlinedHelperName, const RegionCodeGenTy & CodeGen) static
Definition at line 1243 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::GenerateOpenMPCapturedStmtFunction(), clang::OMPExecutableDirective::getBeginLoc(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::ValueDecl::getType(), and clang::Type::isPointerType().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitParallelOutlinedFunction(), and clang::CodeGen::CGOpenMPRuntime::emitTeamsOutlinedFunction().
emitPrivatesInit()
static void emitPrivatesInit (CodeGenFunction & CGF, const OMPExecutableDirective & D, Address KmpTaskSharedsPtr, LValue TDBase, const RecordDecl * KmpTaskTWithPrivatesQTyRD, QualType SharedsTy, QualType SharedsPtrTy, const OMPTaskDataTy & Data, ArrayRef< PrivateDataTy > Privates, bool ForDup) static
Emit initialization for private variables in task-based directives.
Definition at line 3788 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::CurCodeDecl, clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitAggregateAssign(), clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), clang::CodeGen::CodeGenFunction::EmitExprAsInit(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitOMPAggregateAssign(), clang::RecordDecl::field_begin(), clang::CodeGen::OMPTaskDataTy::FirstprivateVars, clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::VarDecl::getAnyInitializer(), clang::OMPExecutableDirective::getCapturedStmt(), clang::CodeGen::CodeGenFunction::getContext(), clang::Decl::getDeclContext(), clang::OMPExecutableDirective::getDirectiveKind(), clang::Type::isArrayType(), clang::isOpenMPTargetDataManagementDirective(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTaskLoopDirective(), clang::CodeGen::CodeGenFunction::isTrivialInitializer(), clang::CodeGen::Address::isValid(), clang::CodeGen::CodeGenFunction::LambdaCaptureFields, and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
Referenced by emitTaskDupFunction().
emitProxyTaskFunction()
static llvm::Function * emitProxyTaskFunction (CodeGenModule & CGM, SourceLocation Loc, OpenMPDirectiveKind Kind, QualType KmpInt32Ty, QualType KmpTaskTWithPrivatesPtrQTy, QualType KmpTaskTWithPrivatesQTy, QualType KmpTaskTQTy, QualType SharedsPtrTy, llvm::Function * TaskFunction, llvm::Value * TaskPrivatesMap) static
Emit a proxy function which accepts kmp_task_t as the second argument.
kmp_int32 .omp_task_entry.(kmp_int32 gtid, kmp_task_t *tt) {
  TaskFunction(gtid, tt->part_id, &tt->privates, task_privates_map, tt,
  For taskloops:
  tt->task_data.lb, tt->task_data.ub, tt->task_data.st, tt->task_data.liter,
  tt->reductions, tt->shareds);
  return 0;
}
Definition at line 3526 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::Type::castAs(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CGOpenMPRuntime::emitOutlinedFunctionCall(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getTypes(), clang::isOpenMPTaskLoopDirective(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenFunction::ReturnValue, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::QualType::withRestrict().
emitReduceCombFunction()
static llvm::Value * emitReduceCombFunction (CodeGenModule & CGM, SourceLocation Loc, ReductionCodeGen & RCG, unsigned N, const Expr * ReductionOp, const Expr * LHS, const Expr * RHS, const Expr * PrivateRef) static
Emits reduction combiner function:
void @.red_comb(void* %arg0, void* %arg1) {
%lhs = bitcast void* %arg0 to <type>*
%rhs = bitcast void* %arg1 to <type>*
%2 = <ReductionOp>(<type>* %lhs, <type>* %rhs)
store <type> %2, <type>* %lhs
ret void
}
Definition at line 5895 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::cast(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner(), clang::CodeGen::CodeGenFunction::FinishFunction(), generateUniqueName(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::ReductionCodeGen::getRefExpr(), clang::CodeGen::ReductionCodeGen::getSizes(), clang::ASTContext::getSizeType(), clang::CodeGen::CodeGenModule::getTypes(), N, clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenFunction::StartFunction().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
emitReduceFiniFunction()
static llvm::Value * emitReduceFiniFunction (CodeGenModule & CGM, SourceLocation Loc, ReductionCodeGen & RCG, unsigned N) static
Emits reduction finalizer function:
void @.red_fini(void* %arg) {
%0 = bitcast void* %arg to <type>*
<destroy>(<type>* %0)
ret void
}
Definition at line 5971 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitCleanups(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), generateUniqueName(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::ReductionCodeGen::getRefExpr(), clang::CodeGen::ReductionCodeGen::getSizes(), clang::ASTContext::getSizeType(), clang::CodeGen::CodeGenModule::getTypes(), N, clang::CodeGen::ReductionCodeGen::needCleanups(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenFunction::StartFunction().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
emitReduceInitFunction()
static llvm::Value * emitReduceInitFunction (CodeGenModule & CGM, SourceLocation Loc, ReductionCodeGen & RCG, unsigned N) static
Emits reduction initializer function:
void @.red_init(void* %arg, void* %orig) {
%0 = bitcast void* %arg to <type>*
store <type> <init>, <type>* %0
ret void
}
Definition at line 5824 of file CGOpenMPRuntime.cpp.
References clang::QualType::addRestrict(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::CanQual< typename >::castAs(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitInitialization(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), generateUniqueName(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::ReductionCodeGen::getRefExpr(), clang::CodeGen::ReductionCodeGen::getSizes(), clang::ASTContext::getSizeType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), N, clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::CodeGen::ReductionCodeGen::usesReductionInitializer(), clang::ASTContext::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
emitReductionCombiner()
static void emitReductionCombiner (CodeGenFunction & CGF, const Expr * ReductionOp) static
Emit reduction combiner.
If the combiner is a simple expression emit it as is, otherwise consider it as combiner of UDR decl and emit it as a call of UDR combiner function.
Definition at line 5361 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CodeGen::CGOpenMPRuntime::getUserDefinedReduction().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), and clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner().
emitTaskDupFunction()
static llvm::Value * emitTaskDupFunction (CodeGenModule & CGM, SourceLocation Loc, const OMPExecutableDirective & D, QualType KmpTaskTWithPrivatesPtrQTy, const RecordDecl * KmpTaskTWithPrivatesQTyRD, const RecordDecl * KmpTaskTQTyRD, QualType SharedsTy, QualType SharedsPtrTy, const OMPTaskDataTy & Data, ArrayRef< PrivateDataTy > Privates, bool WithLastIter) static
Emit task_dup function (for initialization of private/firstprivate/lastprivate vars and last_iter flag)
void __task_dup_entry(kmp_task_t *task_dst, const kmp_task_t *task_src, int
lastpriv) {
// setup lastprivate flag
   task_dst->last = lastpriv;
// could be constructor calls here...
}
Definition at line 3938 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::Type::castAs(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitPrivatesInit(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::RecordDecl::field_begin(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::OMPTaskDataTy::FirstprivateVars, clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::Address::invalid(), clang::ImplicitParamDecl::Other, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenFunction::StartFunction().
emitTaskPrivateMappingFunction()
static llvm::Value * emitTaskPrivateMappingFunction (CodeGenModule & CGM, SourceLocation Loc, const OMPTaskDataTy & Data, QualType PrivatesQTy, ArrayRef< PrivateDataTy > Privates) static
Emit a privates mapping function for correct handling of private and firstprivate variables.
void .omp_task_privates_map.(const .privates. *noalias privs, <ty1>
**noalias priv1,...,  <tyn> **noalias privn) {
  *priv1 = &.privates.priv1;
  ...;
  *privn = &.privates.privn;
}
Definition at line 3689 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::C, clang::cast(), clang::Type::castAs(), clang::CodeGen::CGOpenMPRuntime::CGM, clang::ImplicitParamDecl::Create(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::OMPTaskDataTy::FirstprivateVars, clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::Type::getAsTagDecl(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::QualType::getNonReferenceType(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), isAllocatableDecl(), clang::Type::isLValueReferenceType(), clang::CodeGen::OMPTaskDataTy::LastprivateVars, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::ImplicitParamDecl::Other, clang::CodeGen::OMPTaskDataTy::PrivateLocals, clang::CodeGen::OMPTaskDataTy::PrivateVars, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenFunction::StartFunction().
emitX86DeclareSimdFunction()
static void emitX86DeclareSimdFunction (const FunctionDecl * FD, llvm::Function * Fn, const llvm::APSInt & VLENVal, ArrayRef< ParamAttrTy > ParamAttrs, OMPDeclareSimdDeclAttr::BranchStateTy State) static
Definition at line 11149 of file CGOpenMPRuntime.cpp.
References clang::OMPDeclareSimdDeclAttr::BS_Inbranch, clang::OMPDeclareSimdDeclAttr::BS_Notinbranch, clang::OMPDeclareSimdDeclAttr::BS_Undefined, and evaluateCDTSize().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction().
evaluateCDTSize()
static unsigned evaluateCDTSize (const FunctionDecl * FD, ArrayRef< ParamAttrTy > ParamAttrs) static
Definition at line 11096 of file CGOpenMPRuntime.cpp.
References clang::C, clang::Decl::getASTContext(), clang::Type::getCanonicalTypeUnqualified(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), clang::QualType::isNull(), clang::Type::isRecordType(), clang::Type::isUnionType(), clang::Type::isVoidType(), and Offset.
Referenced by emitX86DeclareSimdFunction().
generateUniqueName()
static std::string generateUniqueName (CodeGenModule & CGM, StringRef Prefix, const Expr * Ref) static
Generates unique name for artificial threadprivate variables.
Format is: <Prefix> "." <Decl_mangled_name> "_" "<Decl_start_loc_raw_enc>"
Definition at line 5800 of file CGOpenMPRuntime.cpp.
References clang::cast(), clang::CodeGen::CGOpenMPRuntime::CGM, getBaseDecl(), clang::DeclaratorDecl::getBeginLoc(), clang::VarDecl::getCanonicalDecl(), clang::CodeGen::CodeGenModule::getMangledName(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::NamedDecl::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::SourceLocation::getRawEncoding(), and clang::VarDecl::isLocalVarDeclOrParm().
Referenced by emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups().
getAArch64LS()
static unsigned getAArch64LS (QualType QT, ParamKindTy Kind, ASTContext & C) static
Computes the lane size (LS) of a return type or of an input parameter, as defined by LS(P) in 3.2.1 of the AAVFABI.
TODO: Add support for references, section 3.2.1, item 1.
Definition at line 11279 of file CGOpenMPRuntime.cpp.
References clang::C, getAArch64MTV(), getAArch64PBV(), clang::QualType::getCanonicalType(), clang::Type::getPointeeType(), and clang::Type::isPointerType().
Referenced by getNDSWDS().
getAArch64MTV()
static bool getAArch64MTV (QualType QT, ParamKindTy Kind) static
Maps To Vector (MTV), as defined in 3.1.1 of the AAVFABI.
TODO: Need to implement the behavior for reference marked with a var or no linear modifiers (1.b in the section). For this, we need to extend ParamKindTy to support the linear modifiers.
Definition at line 11233 of file CGOpenMPRuntime.cpp.
References clang::QualType::getCanonicalType(), and clang::Type::isVoidType().
Referenced by getAArch64LS(), and getNDSWDS().
getAArch64PBV()
static bool getAArch64PBV (QualType QT, ASTContext & C) static
Pass By Value (PBV), as defined in 3.1.2 of the AAVFABI.
Definition at line 11254 of file CGOpenMPRuntime.cpp.
References clang::C, clang::QualType::getCanonicalType(), clang::Type::isFloatingType(), clang::Type::isIntegerType(), and clang::Type::isPointerType().
Referenced by getAArch64LS(), and getNDSWDS().
getBaseDecl()
static const VarDecl * getBaseDecl (const Expr * Ref, const DeclRefExpr *& DE) static
Definition at line 979 of file CGOpenMPRuntime.cpp.
References clang::cast(), and clang::DeclRefExpr::getDecl().
Referenced by generateUniqueName().
getCancellationKind()
static RTCancelKind getCancellationKind (OpenMPDirectiveKind CancelRegion) static
Definition at line 6239 of file CGOpenMPRuntime.cpp.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitCancelCall(), and clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall().
getDependTypes()
static void getDependTypes (ASTContext & C, QualType & KmpDependInfoTy, QualType & FlagsTy) static
Builds kmp_depend_info, if it is not built yet, and builds flags type.
Definition at line 4576 of file CGOpenMPRuntime.cpp.
References addFieldToRecordDecl(), clang::C, clang::RecordDecl::completeDefinition(), clang::QualType::isNull(), and clang::TagDecl::startDefinition().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), emitDepobjElements(), emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), and clang::CodeGen::CGOpenMPRuntime::emitUpdateClause().
getIdentStringFromSourceLocation()
static StringRef getIdentStringFromSourceLocation (CodeGenFunction & CGF, SourceLocation Loc, SmallString< 128 > & Buffer) static
Definition at line 1413 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::CurFuncDecl, clang::PresumedLoc::getColumn(), clang::CodeGen::CodeGenFunction::getContext(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::SourceManager::getPresumedLoc(), and clang::ASTContext::getSourceManager().
Referenced by clang::CodeGen::CGOpenMPRuntime::getThreadID().
getKmpAffinityType()
static void getKmpAffinityType (ASTContext & C, QualType & KmpTaskAffinityInfoTy) static
Builds kmp_depend_info, if it is not built yet, and builds flags type.
Definition at line 4136 of file CGOpenMPRuntime.cpp.
References addFieldToRecordDecl(), clang::C, clang::RecordDecl::completeDefinition(), clang::QualType::isNull(), and clang::TagDecl::startDefinition().
getNDSWDS()
static std::tuple< unsigned, unsigned, bool > getNDSWDS (const FunctionDecl * FD, ArrayRef< ParamAttrTy > ParamAttrs) static
Definition at line 11295 of file CGOpenMPRuntime.cpp.
References clang::C, getAArch64LS(), getAArch64MTV(), getAArch64PBV(), clang::Decl::getASTContext(), clang::QualType::getCanonicalType(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), and clang::Type::isVoidType().
Referenced by emitAArch64DeclareSimdFunction().
getNestedDistributeDirective()
static const OMPExecutableDirective * getNestedDistributeDirective (ASTContext & Ctx, const OMPExecutableDirective & D) static
Check for inner distribute directive.
Definition at line 9411 of file CGOpenMPRuntime.cpp.
References clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::Stmt::IgnoreContainers(), and clang::isOpenMPDistributeDirective().
getNumThreads()
static llvm::Value * getNumThreads (CodeGenFunction & CGF, const CapturedStmt * CS, llvm::Value * DefaultThreadLimitVal) static
Definition at line 6691 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::C, clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitAutoVarCleanups(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitVarDecl(), clang::Expr::EvaluateAsBooleanCondition(), clang::CodeGen::CodeGenFunction::EvaluateExprAsBool(), clang::CapturedStmt::getCapturedStmt(), clang::OMPIfClause::getCondition(), clang::CodeGen::CodeGenFunction::getContext(), clang::OMPClauseWithPreInit::getPreInitStmt(), clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), clang::Stmt::getSourceRange(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::isOpenMPParallelDirective(), clang::isOpenMPSimdDirective(), and clang::Result.
Referenced by emitNumThreadsForTargetDirective().
getPointerAndSize()
static std::pair< llvm::Value *, llvm::Value * > getPointerAndSize (CodeGenFunction & CGF, const Expr * E) static
Definition at line 4101 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), clang::CodeGen::CodeGenFunction::EmitScalarConversion(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::LValue::getPointer(), clang::ASTContext::getSizeType(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::getTypeSize(), clang::Expr::IgnoreParenImpCasts(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by emitDependData().
getReductionInit()
static const OMPDeclareReductionDecl * getReductionInit (const Expr * ReductionOp) static
Check if the combiner is a call to UDR combiner and if it is so return the UDR decl used for reduction.
Definition at line 607 of file CGOpenMPRuntime.cpp.
Referenced by clang::CodeGen::ReductionCodeGen::emitInitialization(), and clang::CodeGen::ReductionCodeGen::usesReductionInitializer().
getRuntimeSchedule() [1/2]
static OpenMPSchedType getRuntimeSchedule (OpenMPDistScheduleClauseKind ScheduleKind, bool Chunked) static
Map the OpenMP distribute schedule to the runtime enumeration.
Definition at line 2599 of file CGOpenMPRuntime.cpp.
getRuntimeSchedule() [2/2]
static OpenMPSchedType getRuntimeSchedule (OpenMPScheduleClauseKind ScheduleKind, bool Chunked, bool Ordered) static
Map the OpenMP loop schedule to the runtime enumeration.
Definition at line 2576 of file CGOpenMPRuntime.cpp.
References clang::OMPC_SCHEDULE_unknown.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDistributeStaticInit(), clang::CodeGen::CGOpenMPRuntime::emitForDispatchInit(), clang::CodeGen::CGOpenMPRuntime::emitForStaticInit(), clang::CodeGen::CGOpenMPRuntime::isDynamic(), clang::CodeGen::CGOpenMPRuntime::isStaticChunked(), clang::CodeGen::CGOpenMPRuntime::isStaticChunked(), clang::CodeGen::CGOpenMPRuntime::isStaticNonchunked(), and clang::CodeGen::CGOpenMPRuntime::isStaticNonchunked().
getTargetEntryUniqueInfo()
static void getTargetEntryUniqueInfo (ASTContext & C, SourceLocation Loc, unsigned & DeviceID, unsigned & FileID, unsigned & LineNum) static
Obtain information that uniquely identifies a target entry.
This consists of the file and device IDs as well as line number associated with the relevant entry source location.
Definition at line 1643 of file CGOpenMPRuntime.cpp.
References clang::C, clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::PresumedLoc::isValid(), clang::SourceLocation::isValid(), and SM.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetVarDefinition(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunctionHelper(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), and clang::CodeGen::CGOpenMPRuntime::registerTargetFirstprivateCopy().
isAllocatableDecl()
static bool isAllocatableDecl (const VarDecl * VD) static
Definition at line 3406 of file CGOpenMPRuntime.cpp.
References clang::Decl::getAttr(), clang::VarDecl::getCanonicalDecl(), clang::Decl::hasAttr(), clang::OMPAllocateDeclAttr::OMPDefaultMemAlloc, and clang::OMPAllocateDeclAttr::OMPNullMemAlloc.
Referenced by createPrivatesRecordDecl(), emitTaskPrivateMappingFunction(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), and clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable().
isTrivial()
static bool isTrivial (ASTContext & Ctx, const Expr * E) static
Checks if the expression is constant or does not have non-trivial function calls.
Definition at line 6505 of file CGOpenMPRuntime.cpp.
References clang::Expr::hasNonTrivialCall(), clang::Expr::HasSideEffects(), clang::Expr::isEvaluatable(), and clang::Expr::SE_AllowUndefinedBehavior.
Referenced by clang::CodeGen::CGOpenMPRuntime::getSingleCompoundChild(), and clang::TextNodeDumper::VisitCXXRecordDecl().
loadToBegin()
static LValue loadToBegin (CodeGenFunction & CGF, QualType BaseTy, QualType ElTy, LValue BaseLV) static
Definition at line 931 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointerLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue(), clang::Type::getAs(), clang::CodeGen::CodeGenFunction::getContext(), clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::ASTContext::hasSameType(), clang::Type::isPointerType(), clang::Type::isReferenceType(), and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress().
mangleVectorParameters()
static std::string mangleVectorParameters (ArrayRef< ParamAttrTy > ParamAttrs) static
Mangle the parameter part of the vector function name according to their OpenMP classification.
The mangling function is defined in section 3.5 of the AAVFABI.
Definition at line 11331 of file CGOpenMPRuntime.cpp.
Referenced by emitAArch64DeclareSimdFunction().
translateDependencyKind()
static RTLDependenceKindTy translateDependencyKind (OpenMPDependClauseKind K) static
Translates internal dependency kind into the runtime kind.
Definition at line 4552 of file CGOpenMPRuntime.cpp.
References clang::OMPC_DEPEND_unknown.
Referenced by emitDependData(), and clang::CodeGen::CGOpenMPRuntime::emitUpdateClause().