clang: lib/CodeGen/CGVTT.cpp File Reference
CGVTT.cpp File Reference
#include "CodeGenModule.h"
#include "CGCXXABI.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/VTTBuilder.h"
Functions
static llvm::GlobalVariable * GetAddrOfVTTVTable (CodeGenVTables &CGVT, CodeGenModule &CGM, const CXXRecordDecl *MostDerivedClass, const VTTVTable &VTable, llvm::GlobalVariable::LinkageTypes Linkage, VTableLayout::AddressPointsMapTy &AddressPoints)
Function Documentation
GetAddrOfVTTVTable()
static llvm::GlobalVariable * GetAddrOfVTTVTable (CodeGenVTables & CGVT, CodeGenModule & CGM, const CXXRecordDecl * MostDerivedClass, const VTTVTable & VTable, llvm::GlobalVariable::LinkageTypes Linkage, VTableLayout::AddressPointsMapTy & AddressPoints) static
Definition at line 21 of file CGVTT.cpp.
References clang::CodeGen::CodeGenVTables::GenerateConstructionVTable(), clang::CodeGen::CGCXXABI::getAddrOfVTable(), clang::VTTVTable::getBase(), clang::VTTVTable::getBaseOffset(), clang::VTTVTable::getBaseSubobject(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::VTTVTable::isVirtual(), and clang::CharUnits::isZero().
Referenced by clang::CodeGen::CodeGenVTables::EmitVTTDefinition().