clang: lib/StaticAnalyzer/Checkers/CheckObjCInstMethSignature.cpp File Reference
CheckObjCInstMethSignature.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Type.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool AreTypesCompatible (QualType Derived, QualType Ancestor, ASTContext &C)
static void CompareReturnTypes (const ObjCMethodDecl *MethDerived, const ObjCMethodDecl *MethAncestor, BugReporter &BR, ASTContext &Ctx, const ObjCImplementationDecl *ID, const CheckerBase *Checker)
static void CheckObjCInstMethSignature (const ObjCImplementationDecl *ID, BugReporter &BR, const CheckerBase *Checker)
Function Documentation
AreTypesCompatible()
static bool AreTypesCompatible (QualType Derived, QualType Ancestor, ASTContext & C) static
Definition at line 28 of file CheckObjCInstMethSignature.cpp.
References clang::C, and clang::Type::isAnyPointerType().
Referenced by CompareReturnTypes().
CheckObjCInstMethSignature()
static void CheckObjCInstMethSignature (const ObjCImplementationDecl * ID, BugReporter & BR, const CheckerBase * Checker) static
Definition at line 78 of file CheckObjCInstMethSignature.cpp.
References clang::C, CompareReturnTypes(), clang::ento::BugReporter::getContext(), and clang::ObjCInterfaceDecl::getSuperClass().
CompareReturnTypes()
static void CompareReturnTypes (const ObjCMethodDecl * MethDerived, const ObjCMethodDecl * MethAncestor, BugReporter & BR, ASTContext & Ctx, const ObjCImplementationDecl * ID, const CheckerBase * Checker) static
Definition at line 39 of file CheckObjCInstMethSignature.cpp.
References AreTypesCompatible(), clang::ento::categories::CoreFoundationObjectiveC, clang::ento::PathDiagnosticLocation::createBegin(), clang::ento::BugReporter::EmitBasicReport(), clang::QualType::getAsString(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ento::BugReporter::getSourceManager(), and clang::Selector::print().
Referenced by CheckObjCInstMethSignature().