clang: clang::AvailabilityAttr Class Reference
clang::AvailabilityAttr Class Reference
#include "clang/AST/Attr.h"
Public Types
enum Spelling { GNU_availability = 0 , CXX11_clang_availability = 1 , C2x_clang_availability = 2 , SpellingNotCalculated = 15 }
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
AvailabilityAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority)
AvailabilityAttr * clone (ASTContext &C) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
const char * getSpelling () const
IdentifierInfo * getPlatform () const
VersionTuple getIntroduced () const
void setIntroduced (ASTContext &C, VersionTuple V)
VersionTuple getDeprecated () const
void setDeprecated (ASTContext &C, VersionTuple V)
VersionTuple getObsoleted () const
void setObsoleted (ASTContext &C, VersionTuple V)
bool getUnavailable () const
llvm::StringRef getMessage () const
unsigned getMessageLength () const
void setMessage (ASTContext &C, llvm::StringRef S)
bool getStrict () const
llvm::StringRef getReplacement () const
unsigned getReplacementLength () const
void setReplacement (ASTContext &C, llvm::StringRef S)
int getPriority () const
Public Member Functions inherited from clang::InheritableAttr
void setInherited (bool I)
bool shouldInheritEvenIfAlreadyPresent () const
Should this attribute be inherited from a prior declaration even if it's explicitly provided in the current declaration?
Public Member Functions inherited from clang::Attr
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static AvailabilityAttr * CreateImplicit (ASTContext &Ctx, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, const AttributeCommonInfo &CommonInfo={SourceRange{}})
static AvailabilityAttr * Create (ASTContext &Ctx, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, const AttributeCommonInfo &CommonInfo)
static AvailabilityAttr * CreateImplicit (ASTContext &Ctx, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static AvailabilityAttr * Create (ASTContext &Ctx, IdentifierInfo *Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static llvm::StringRef getPrettyPlatformName (llvm::StringRef Platform)
static llvm::StringRef getPlatformNameSourceSpelling (llvm::StringRef Platform)
static llvm::StringRef canonicalizePlatformName (llvm::StringRef Platform)
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::InheritableAttr
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Additional Inherited Members
Protected Member Functions inherited from clang::InheritableAttr
InheritableAttr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed, bool InheritEvenIfAlreadyPresent)
Protected Member Functions inherited from clang::Attr
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes inherited from clang::Attr
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Definition at line 1506 of file Attr.h.
Member Enumeration Documentation
Spelling
enum clang::AvailabilityAttr::Spelling
Enumerator
GNU_availability
CXX11_clang_availability
C2x_clang_availability
SpellingNotCalculated
Definition at line 1531 of file Attr.h.
Constructor & Destructor Documentation
AvailabilityAttr()
clang::AvailabilityAttr::AvailabilityAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority)
Member Function Documentation
canonicalizePlatformName()
static llvm::StringRef clang::AvailabilityAttr::canonicalizePlatformName (llvm::StringRef Platform) inline static
Definition at line 1652 of file Attr.h.
classof()
static bool clang::AvailabilityAttr::classof (const Attr * A) inline static
Definition at line 1665 of file Attr.h.
clone()
AvailabilityAttr * clang::AvailabilityAttr::clone (ASTContext & C) const
Create() [1/2]
static AvailabilityAttr * clang::AvailabilityAttr::Create (ASTContext & Ctx, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, const AttributeCommonInfo & CommonInfo) static
Create() [2/2]
static AvailabilityAttr * clang::AvailabilityAttr::Create (ASTContext & Ctx, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
CreateImplicit() [1/2]
static AvailabilityAttr * clang::AvailabilityAttr::CreateImplicit (ASTContext & Ctx, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, const AttributeCommonInfo & CommonInfo = {SourceRange{}}) static
CreateImplicit() [2/2]
static AvailabilityAttr * clang::AvailabilityAttr::CreateImplicit (ASTContext & Ctx, IdentifierInfo * Platform, VersionTuple Introduced, VersionTuple Deprecated, VersionTuple Obsoleted, bool Unavailable, llvm::StringRef Message, bool Strict, llvm::StringRef Replacement, int Priority, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
getDeprecated()
VersionTuple clang::AvailabilityAttr::getDeprecated () const inline
Definition at line 1573 of file Attr.h.
Referenced by AvailabilityAttrsMatch(), and CheckAvailability().
getIntroduced()
VersionTuple clang::AvailabilityAttr::getIntroduced () const inline
Definition at line 1566 of file Attr.h.
Referenced by AvailabilityAttrsMatch(), CheckAvailability(), and DoEmitAvailabilityWarning().
getMessage()
llvm::StringRef clang::AvailabilityAttr::getMessage () const inline
Definition at line 1591 of file Attr.h.
Referenced by CheckAvailability().
getMessageLength()
unsigned clang::AvailabilityAttr::getMessageLength () const inline
Definition at line 1594 of file Attr.h.
getObsoleted()
VersionTuple clang::AvailabilityAttr::getObsoleted () const inline
Definition at line 1580 of file Attr.h.
Referenced by AvailabilityAttrsMatch(), and CheckAvailability().
getPlatform()
IdentifierInfo * clang::AvailabilityAttr::getPlatform () const inline
Definition at line 1562 of file Attr.h.
Referenced by CheckAvailability(), and getRealizedPlatform().
getPlatformNameSourceSpelling()
static llvm::StringRef clang::AvailabilityAttr::getPlatformNameSourceSpelling (llvm::StringRef Platform) inline static
Definition at line 1639 of file Attr.h.
Referenced by clang::Sema::diagnoseUnavailableAlignedAllocation(), and DoEmitAvailabilityWarning().
getPrettyPlatformName()
static llvm::StringRef clang::AvailabilityAttr::getPrettyPlatformName (llvm::StringRef Platform) inline static
Definition at line 1625 of file Attr.h.
Referenced by CheckAvailability(), and DoEmitAvailabilityWarning().
getPriority()
int clang::AvailabilityAttr::getPriority () const inline
Definition at line 1621 of file Attr.h.
getReplacement()
llvm::StringRef clang::AvailabilityAttr::getReplacement () const inline
Definition at line 1608 of file Attr.h.
getReplacementLength()
unsigned clang::AvailabilityAttr::getReplacementLength () const inline
Definition at line 1611 of file Attr.h.
getSpelling()
const char * clang::AvailabilityAttr::getSpelling () const
getStrict()
bool clang::AvailabilityAttr::getStrict () const inline
Definition at line 1604 of file Attr.h.
Referenced by CheckAvailability().
getUnavailable()
bool clang::AvailabilityAttr::getUnavailable () const inline
Definition at line 1587 of file Attr.h.
Referenced by AvailabilityAttrsMatch(), and CheckAvailability().
printPretty()
void clang::AvailabilityAttr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
setDeprecated()
void clang::AvailabilityAttr::setDeprecated (ASTContext & C, VersionTuple V) inline
Definition at line 1576 of file Attr.h.
setIntroduced()
void clang::AvailabilityAttr::setIntroduced (ASTContext & C, VersionTuple V) inline
Definition at line 1569 of file Attr.h.
setMessage()
void clang::AvailabilityAttr::setMessage (ASTContext & C, llvm::StringRef S) inline
Definition at line 1597 of file Attr.h.
setObsoleted()
void clang::AvailabilityAttr::setObsoleted (ASTContext & C, VersionTuple V) inline
Definition at line 1583 of file Attr.h.
setReplacement()
void clang::AvailabilityAttr::setReplacement (ASTContext & C, llvm::StringRef S) inline
Definition at line 1614 of file Attr.h.
The documentation for this class was generated from the following file:
include/clang/AST/Attr.h