clang: clang::ObjCInterfaceTypeLoc Class Reference
clang::ObjCInterfaceTypeLoc Class Reference
Wrapper for source info for ObjC interfaces.
#include "clang/AST/TypeLoc.h"
Public Member Functions
ObjCInterfaceDecl * getIFaceDecl () const
SourceLocation getNameLoc () const
void setNameLoc (SourceLocation Loc)
SourceRange getLocalSourceRange () const
SourceLocation getNameEndLoc () const
void setNameEndLoc (SourceLocation Loc)
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (ObjCInterfaceTypeLoc other)
TypeLoc getNextTypeLoc () const
const ObjCInterfaceType * getTypePtr () const
Public Member Functions inherited from clang::ObjCObjectTypeLoc
SourceLocation getTypeArgsLAngleLoc () const
void setTypeArgsLAngleLoc (SourceLocation Loc)
SourceLocation getTypeArgsRAngleLoc () const
void setTypeArgsRAngleLoc (SourceLocation Loc)
unsigned getNumTypeArgs () const
TypeSourceInfo * getTypeArgTInfo (unsigned i) const
void setTypeArgTInfo (unsigned i, TypeSourceInfo *TInfo)
SourceLocation getProtocolLAngleLoc () const
void setProtocolLAngleLoc (SourceLocation Loc)
SourceLocation getProtocolRAngleLoc () const
void setProtocolRAngleLoc (SourceLocation Loc)
unsigned getNumProtocols () const
SourceLocation getProtocolLoc (unsigned i) const
void setProtocolLoc (unsigned i, SourceLocation Loc)
ObjCProtocolDecl * getProtocol (unsigned i) const
ArrayRef< SourceLocation > getProtocolLocs () const
bool hasBaseTypeAsWritten () const
void setHasBaseTypeAsWritten (bool HasBaseType)
TypeLoc getBaseLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (ObjCObjectTypeLoc other)
TypeLoc getNextTypeLoc () const
const ObjCObjectType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
ObjCInterfaceLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
ObjCObjectTypeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Wrapper for source info for ObjC interfaces.
Definition at line 1040 of file TypeLoc.h.
Member Function Documentation
getIFaceDecl()
ObjCInterfaceDecl * clang::ObjCInterfaceTypeLoc::getIFaceDecl () const inline
Definition at line 1045 of file TypeLoc.h.
References clang::ObjCInterfaceType::getDecl(), and clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >::getTypePtr().
getLocalSourceRange()
SourceRange clang::ObjCInterfaceTypeLoc::getLocalSourceRange () const inline
Definition at line 1057 of file TypeLoc.h.
References getNameEndLoc(), and getNameLoc().
getNameEndLoc()
SourceLocation clang::ObjCInterfaceTypeLoc::getNameEndLoc () const inline
Definition at line 1061 of file TypeLoc.h.
References clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >::getLocalData(), and clang::ObjCInterfaceLocInfo::NameEndLoc.
Referenced by getLocalSourceRange().
getNameLoc()
SourceLocation clang::ObjCInterfaceTypeLoc::getNameLoc () const inline
Definition at line 1049 of file TypeLoc.h.
References clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >::getLocalData(), and clang::ObjCInterfaceLocInfo::NameLoc.
Referenced by getLocalSourceRange().
initializeLocal()
void clang::ObjCInterfaceTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 1069 of file TypeLoc.h.
References setNameEndLoc(), and setNameLoc().
setNameEndLoc()
void clang::ObjCInterfaceTypeLoc::setNameEndLoc (SourceLocation Loc) inline
Definition at line 1065 of file TypeLoc.h.
References clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >::getLocalData(), and clang::ObjCInterfaceLocInfo::NameEndLoc.
Referenced by initializeLocal().
setNameLoc()
void clang::ObjCInterfaceTypeLoc::setNameLoc (SourceLocation Loc) inline
Definition at line 1053 of file TypeLoc.h.
References clang::ConcreteTypeLoc< ObjCObjectTypeLoc, ObjCInterfaceTypeLoc, ObjCInterfaceType, ObjCInterfaceLocInfo >::getLocalData(), and clang::ObjCInterfaceLocInfo::NameLoc.
Referenced by initializeLocal().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h