clang: clang::UnresolvedSetImpl Class Reference
clang::UnresolvedSetImpl Class Reference
A set of unresolved declarations.
#include "clang/AST/UnresolvedSet.h"
Public Types
using iterator = UnresolvedSetIterator
using const_iterator = UnresolvedSetIterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
ArrayRef< DeclAccessPair > pairs () const
void addDecl (NamedDecl *D)
void addDecl (NamedDecl *D, AccessSpecifier AS)
bool replace (const NamedDecl *Old, NamedDecl *New)
Replaces the given declaration with the new one, once.
void replace (iterator I, NamedDecl *New)
Replaces the declaration at the given iterator with the new one, preserving the original access bits.
void replace (iterator I, NamedDecl *New, AccessSpecifier AS)
void erase (unsigned I)
void erase (iterator I)
void setAccess (iterator I, AccessSpecifier AS)
void clear ()
void set_size (unsigned N)
bool empty () const
unsigned size () const
void append (iterator I, iterator E)
template<typename Iter >
void assign (Iter I, Iter E)
DeclAccessPair & operator[] (unsigned I)
const DeclAccessPair & operator[] (unsigned I) const
Friends
template<unsigned N>
class UnresolvedSet
Detailed Description
A set of unresolved declarations.
Definition at line 61 of file UnresolvedSet.h.
Member Typedef Documentation
const_iterator
using clang::UnresolvedSetImpl::const_iterator = UnresolvedSetIterator
Definition at line 81 of file UnresolvedSet.h.
iterator
using clang::UnresolvedSetImpl::iterator = UnresolvedSetIterator
Definition at line 80 of file UnresolvedSet.h.
Member Function Documentation
addDecl() [1/2]
void clang::UnresolvedSetImpl::addDecl (NamedDecl * D) inline
Definition at line 91 of file UnresolvedSet.h.
References addDecl(), and clang::AS_none.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::LookupResult::addDecl(), addDecl(), buildDeclareReductionRef(), clang::Sema::CheckFunctionTemplateSpecialization(), CollectVisibleConversions(), clang::ASTImporter::Import(), clang::ASTNodeImporter::ImportTemplateInformation(), notePlausibleOverloads(), clang::Sema::PerformContextualImplicitConversion(), clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr(), clang::transformOMPMappableExprListClause(), clang::Sema::tryExprAsCall(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTNodeImporter::VisitUnresolvedLookupExpr(), and clang::ASTNodeImporter::VisitUnresolvedMemberExpr().
addDecl() [2/2]
void clang::UnresolvedSetImpl::addDecl (NamedDecl * D, AccessSpecifier AS) inline
Definition at line 95 of file UnresolvedSet.h.
References clang::DeclAccessPair::make().
append()
void clang::UnresolvedSetImpl::append (iterator I, iterator E) inline
Definition at line 129 of file UnresolvedSet.h.
Referenced by clang::LookupResult::addAllDecls(), buildDeclareReductionRef(), buildOperatorCoawaitCall(), buildUserDefinedMapperRef(), clang::Sema::LookupOverloadedOperatorName(), clang::Sema::ProduceCallSignatureHelp(), and clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr().
assign()
template<typename Iter > void clang::UnresolvedSetImpl::assign (Iter I, Iter E) inline
Definition at line 131 of file UnresolvedSet.h.
begin() [1/2]
iterator clang::UnresolvedSetImpl::begin () inline
Definition at line 83 of file UnresolvedSet.h.
References begin().
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::LookupResult::addAllDecls(), clang::Sema::AddFunctionCandidates(), clang::Sema::AddNonMemberOperatorCandidates(), clang::LookupResult::begin(), begin(), buildDeclareReductionRef(), buildUserDefinedMapperRef(), clang::Sema::CheckFunctionTemplateSpecialization(), CollectVisibleConversions(), clang::Sema::CreateUnresolvedLookupExpr(), clang::ASTImporter::Import(), IsOverloaded(), noteOverloads(), notePlausibleOverloads(), replace(), clang::LookupResult::resolveKind(), clang::transformOMPMappableExprListClause(), clang::ASTNodeImporter::VisitUnresolvedLookupExpr(), and clang::ASTNodeImporter::VisitUnresolvedMemberExpr().
begin() [2/2]
const_iterator clang::UnresolvedSetImpl::begin () const inline
Definition at line 86 of file UnresolvedSet.h.
References begin().
Referenced by begin().
clear()
void clang::UnresolvedSetImpl::clear () inline
Definition at line 123 of file UnresolvedSet.h.
Referenced by clang::LookupResult::clear(), and clang::Sema::tryExprAsCall().
empty()
bool clang::UnresolvedSetImpl::empty () const inline
Definition at line 126 of file UnresolvedSet.h.
Referenced by clang::Sema::ActOnCXXFoldExpr(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::LookupResult::empty(), clang::LookupResult::getRepresentativeDecl(), clang::LookupResult::resolveKindAfterFilter(), and clang::LookupResult::setNotFoundInCurrentInstantiation().
end() [1/2]
iterator clang::UnresolvedSetImpl::end () inline
Definition at line 84 of file UnresolvedSet.h.
References end().
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::LookupResult::addAllDecls(), clang::Sema::AddFunctionCandidates(), clang::Sema::AddNonMemberOperatorCandidates(), buildDeclareReductionRef(), buildUserDefinedMapperRef(), clang::Sema::CheckFunctionTemplateSpecialization(), CollectVisibleConversions(), clang::Sema::CreateUnresolvedLookupExpr(), clang::LookupResult::end(), end(), clang::ASTImporter::Import(), noteOverloads(), notePlausibleOverloads(), replace(), clang::transformOMPMappableExprListClause(), clang::ASTNodeImporter::VisitUnresolvedLookupExpr(), and clang::ASTNodeImporter::VisitUnresolvedMemberExpr().
end() [2/2]
const_iterator clang::UnresolvedSetImpl::end () const inline
Definition at line 87 of file UnresolvedSet.h.
References end().
Referenced by end().
erase() [1/2]
void clang::UnresolvedSetImpl::erase (iterator I) inline
Definition at line 119 of file UnresolvedSet.h.
erase() [2/2]
void clang::UnresolvedSetImpl::erase (unsigned I) inline
Definition at line 117 of file UnresolvedSet.h.
operator[]() [1/2]
DeclAccessPair & clang::UnresolvedSetImpl::operator[] (unsigned I) inline
Definition at line 133 of file UnresolvedSet.h.
operator[]() [2/2]
const DeclAccessPair & clang::UnresolvedSetImpl::operator[] (unsigned I) const inline
Definition at line 134 of file UnresolvedSet.h.
pairs()
ArrayRef< DeclAccessPair > clang::UnresolvedSetImpl::pairs () const inline
Definition at line 89 of file UnresolvedSet.h.
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison().
replace() [1/3]
bool clang::UnresolvedSetImpl::replace (const NamedDecl * Old, NamedDecl * New) inline
Replaces the given declaration with the new one, once.
Returns
true if the set changed
Definition at line 102 of file UnresolvedSet.h.
References begin(), and end().
replace() [2/3]
void clang::UnresolvedSetImpl::replace (iterator I, NamedDecl * New) inline
Replaces the declaration at the given iterator with the new one, preserving the original access bits.
Definition at line 111 of file UnresolvedSet.h.
replace() [3/3]
void clang::UnresolvedSetImpl::replace (iterator I, NamedDecl * New, AccessSpecifier AS) inline
Definition at line 113 of file UnresolvedSet.h.
set_size()
void clang::UnresolvedSetImpl::set_size (unsigned N) inline
Definition at line 124 of file UnresolvedSet.h.
References N.
Referenced by clang::LookupResult::resolveKind().
setAccess()
void clang::UnresolvedSetImpl::setAccess (iterator I, AccessSpecifier AS) inline
Definition at line 121 of file UnresolvedSet.h.
References clang::Decl::setAccess().
size()
unsigned clang::UnresolvedSetImpl::size () const inline
Definition at line 127 of file UnresolvedSet.h.
Referenced by collectViableConversionCandidates(), clang::DependentFunctionTemplateSpecializationInfo::Create(), diagnoseAmbiguousConversion(), diagnoseNoViableConversion(), IsOverloaded(), clang::Sema::PerformContextualImplicitConversion(), clang::LookupResult::print(), and clang::LookupResult::resolveKind().
Friends And Related Symbol Documentation
UnresolvedSet
template<unsigned N> friend class UnresolvedSet friend
Definition at line 67 of file UnresolvedSet.h.
The documentation for this class was generated from the following file:
include/clang/AST/UnresolvedSet.h