clang: clang::interp::InterpState Class Reference
clang::interp::InterpState Class Reference final
Interpreter context.
#include "/root/llvm-project/clang/lib/AST/Interp/InterpState.h"
Public Member Functions
InterpState (State &Parent, Program &P, InterpStack &Stk, Context &Ctx, SourceMapper *M=nullptr)
~InterpState ()
Frame * getSplitFrame ()
Frame * getCurrentFrame () override
unsigned getCallStackDepth () override
const Frame * getBottomFrame () const override
Expr::EvalStatus & getEvalStatus () const override
ASTContext & getCtx () const override
bool checkingForUndefinedBehavior () const override
bool keepEvaluatingAfterFailure () const override
bool checkingPotentialConstantExpression () const override
bool noteUndefinedBehavior () override
bool hasActiveDiagnostic () override
void setActiveDiagnostic (bool Flag) override
void setFoldFailureDiagnostic (bool Flag) override
bool hasPriorDiagnostic () override
bool reportOverflow (const Expr *E, const llvm::APSInt &Value)
Reports overflow and return true if evaluation should continue.
void deallocate (Block *B)
Deallocates a pointer.
SourceInfo getSource (Function *F, CodePtr PC) const override
Delegates source mapping to the mapper.
Public Member Functions inherited from clang::interp::State
virtual ~State ()
OptionalDiagnostic FFDiag (SourceLocation Loc, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic FFDiag (const Expr *E, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic FFDiag (const SourceInfo &SI, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic CCEDiag (SourceLocation Loc, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
Diagnose that the evaluation does not produce a C++11 core constant expression.
OptionalDiagnostic CCEDiag (const Expr *E, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic CCEDiag (const SourceInfo &SI, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic Note (SourceLocation Loc, diag::kind DiagId)
Add a note to a prior diagnostic.
void addNotes (ArrayRef< PartialDiagnosticAt > Diags)
Add a stack of notes to a prior diagnostic.
DiagnosticBuilder report (SourceLocation Loc, diag::kind DiagId)
Directly reports a diagnostic message.
const LangOptions & getLangOpts () const
Public Member Functions inherited from clang::interp::SourceMapper
virtual ~SourceMapper ()
const Expr * getExpr (Function *F, CodePtr PC) const
Returns the expression if an opcode belongs to one, null otherwise.
SourceLocation getLocation (Function *F, CodePtr PC) const
Returns the location from which an opcode originates.
Public Attributes
Program & P
Reference to the module containing all bytecode.
InterpStack & Stk
Temporary stack.
Context & Ctx
Interpreter Context.
InterpFrame * Current = nullptr
The current frame.
unsigned CallStackDepth
Call stack depth.
Detailed Description
Interpreter context.
Definition at line 34 of file InterpState.h.
Constructor & Destructor Documentation
InterpState()
InterpState::InterpState (State & Parent, Program & P, InterpStack & Stk, Context & Ctx, SourceMapper * M = nullptr)
Definition at line 24 of file InterpState.cpp.
~InterpState()
InterpState::~InterpState ()
Definition at line 29 of file InterpState.cpp.
References clang::interp::InterpFrame::Caller, Current, and Next.
Member Function Documentation
checkingForUndefinedBehavior()
bool clang::interp::InterpState::checkingForUndefinedBehavior () const inline override virtual
Implements clang::interp::State.
Definition at line 56 of file InterpState.h.
References Parent.
checkingPotentialConstantExpression()
bool clang::interp::InterpState::checkingPotentialConstantExpression () const inline override virtual
Implements clang::interp::State.
Definition at line 62 of file InterpState.h.
References Parent.
deallocate()
void InterpState::deallocate (Block * B)
Deallocates a pointer.
Definition at line 57 of file InterpState.cpp.
References clang::interp::Block::data(), clang::interp::Descriptor::DtorFn, clang::interp::Block::getDescriptor(), clang::interp::Block::getSize(), clang::interp::Block::hasPointers(), and clang::interp::Descriptor::MoveFn.
Referenced by clang::interp::InterpFrame::destroy(), and clang::interp::InterpFrame::~InterpFrame().
getBottomFrame()
const Frame * clang::interp::InterpState::getBottomFrame () const inline override virtual
Implements clang::interp::State.
Definition at line 45 of file InterpState.h.
References Parent.
getCallStackDepth()
unsigned clang::interp::InterpState::getCallStackDepth () inline override virtual
Implements clang::interp::State.
Definition at line 44 of file InterpState.h.
References CallStackDepth.
getCtx()
ASTContext & clang::interp::InterpState::getCtx () const inline override virtual
Implements clang::interp::State.
Definition at line 53 of file InterpState.h.
References Parent.
Referenced by clang::interp::InterpFrame::describe().
getCurrentFrame()
Frame * InterpState::getCurrentFrame () override virtual
Implements clang::interp::State.
Definition at line 43 of file InterpState.cpp.
References clang::interp::InterpFrame::Caller, Current, and clang::interp::State::getCurrentFrame().
getEvalStatus()
Expr::EvalStatus & clang::interp::InterpState::getEvalStatus () const inline override virtual
Implements clang::interp::State.
Definition at line 50 of file InterpState.h.
References Parent.
getSource()
SourceInfo clang::interp::InterpState::getSource (Function * F, CodePtr PC) const inline override virtual
Delegates source mapping to the mapper.
Implements clang::interp::SourceMapper.
Definition at line 84 of file InterpState.h.
References clang::interp::Function::getSource(), and clang::interp::SourceMapper::getSource().
Referenced by clang::interp::InterpFrame::getSource().
getSplitFrame()
Frame * clang::interp::InterpState::getSplitFrame () inline
Definition at line 42 of file InterpState.h.
References Parent.
Referenced by clang::interp::InterpFrame::getCaller().
hasActiveDiagnostic()
bool clang::interp::InterpState::hasActiveDiagnostic () inline override virtual
Implements clang::interp::State.
Definition at line 68 of file InterpState.h.
References Parent.
hasPriorDiagnostic()
bool clang::interp::InterpState::hasPriorDiagnostic () inline override virtual
Implements clang::interp::State.
Definition at line 75 of file InterpState.h.
References Parent.
keepEvaluatingAfterFailure()
bool clang::interp::InterpState::keepEvaluatingAfterFailure () const inline override virtual
Implements clang::interp::State.
Definition at line 59 of file InterpState.h.
References Parent.
noteUndefinedBehavior()
bool clang::interp::InterpState::noteUndefinedBehavior () inline override virtual
Implements clang::interp::State.
Definition at line 65 of file InterpState.h.
References Parent.
Referenced by reportOverflow().
reportOverflow()
bool InterpState::reportOverflow (const Expr * E, const llvm::APSInt & Value)
Reports overflow and return true if evaluation should continue.
Definition at line 51 of file InterpState.cpp.
References clang::interp::State::CCEDiag(), clang::Expr::getType(), noteUndefinedBehavior(), and Type.
setActiveDiagnostic()
void clang::interp::InterpState::setActiveDiagnostic (bool Flag) inline override virtual
Implements clang::interp::State.
Definition at line 69 of file InterpState.h.
References Parent.
setFoldFailureDiagnostic()
void clang::interp::InterpState::setFoldFailureDiagnostic (bool Flag) inline override virtual
Implements clang::interp::State.
Definition at line 72 of file InterpState.h.
References Parent.
Member Data Documentation
CallStackDepth
unsigned clang::interp::InterpState::CallStackDepth
Call stack depth.
Definition at line 106 of file InterpState.h.
Referenced by getCallStackDepth().
Ctx
Context& clang::interp::InterpState::Ctx
Interpreter Context.
Definition at line 102 of file InterpState.h.
Referenced by clang::interp::InterpFrame::describe().
Current
InterpFrame* clang::interp::InterpState::Current = nullptr
The current frame.
Definition at line 104 of file InterpState.h.
Referenced by clang::interp::EvalEmitter::EvalEmitter(), getCurrentFrame(), and ~InterpState().
P
Program& clang::interp::InterpState::P
Reference to the module containing all bytecode.
Definition at line 98 of file InterpState.h.
Stk
InterpStack& clang::interp::InterpState::Stk
Temporary stack.
Definition at line 100 of file InterpState.h.
Referenced by clang::interp::EvalEmitter::jumpFalse(), clang::interp::EvalEmitter::jumpTrue(), and clang::interp::InterpFrame::popArgs().
The documentation for this class was generated from the following files:
lib/AST/Interp/InterpState.h
lib/AST/Interp/InterpState.cpp