clang: clang::interp::SourceInfo Class Reference
clang::interp::SourceInfo Class Reference
Describes the statement/declaration an opcode was generated from.
#include "/root/llvm-project/clang/lib/AST/Interp/Source.h"
Public Member Functions
SourceInfo ()
SourceInfo (const Stmt *E)
SourceInfo (const Decl *D)
SourceLocation getLoc () const
const Stmt * asStmt () const
const Decl * asDecl () const
const Expr * asExpr () const
operator bool () const
Detailed Description
Describes the statement/declaration an opcode was generated from.
Definition at line 81 of file Source.h.
Constructor & Destructor Documentation
SourceInfo() [1/3]
clang::interp::SourceInfo::SourceInfo () inline
Definition at line 83 of file Source.h.
SourceInfo() [2/3]
clang::interp::SourceInfo::SourceInfo (const Stmt * E) inline
Definition at line 84 of file Source.h.
SourceInfo() [3/3]
clang::interp::SourceInfo::SourceInfo (const Decl * D) inline
Definition at line 85 of file Source.h.
Member Function Documentation
asDecl()
const Decl * clang::interp::SourceInfo::asDecl () const inline
Definition at line 90 of file Source.h.
Referenced by getLoc().
asExpr()
const Expr * SourceInfo::asExpr () const
Definition at line 25 of file Source.cpp.
Referenced by clang::interp::CheckThis(), and getLoc().
asStmt()
const Stmt * clang::interp::SourceInfo::asStmt () const inline
Definition at line 89 of file Source.h.
Referenced by getLoc().
getLoc()
SourceLocation SourceInfo::getLoc () const
Definition at line 15 of file Source.cpp.
References asDecl(), asExpr(), and asStmt().
Referenced by clang::interp::State::CCEDiag(), clang::interp::State::FFDiag(), and clang::interp::SourceMapper::getLocation().
operator bool()
clang::interp::SourceInfo::operator bool () const inline
Definition at line 93 of file Source.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/Source.h
lib/AST/Interp/Source.cpp