clang: clang::SanitizerBlacklist Class Reference
clang::SanitizerBlacklist Class Reference
#include "clang/Basic/SanitizerBlacklist.h"
Public Member Functions
SanitizerBlacklist (const std::vector< std::string > &BlacklistPaths, SourceManager &SM)
~SanitizerBlacklist ()
bool isBlacklistedGlobal (SanitizerMask Mask, StringRef GlobalName, StringRef Category=StringRef()) const
bool isBlacklistedType (SanitizerMask Mask, StringRef MangledTypeName, StringRef Category=StringRef()) const
bool isBlacklistedFunction (SanitizerMask Mask, StringRef FunctionName) const
bool isBlacklistedFile (SanitizerMask Mask, StringRef FileName, StringRef Category=StringRef()) const
bool isBlacklistedLocation (SanitizerMask Mask, SourceLocation Loc, StringRef Category=StringRef()) const
Detailed Description
Definition at line 28 of file SanitizerBlacklist.h.
Constructor & Destructor Documentation
SanitizerBlacklist()
SanitizerBlacklist::SanitizerBlacklist (const std::vector< std::string > & BlacklistPaths, SourceManager & SM)
Definition at line 22 of file SanitizerBlacklist.cpp.
~SanitizerBlacklist()
SanitizerBlacklist::~SanitizerBlacklist () default
Member Function Documentation
isBlacklistedFile()
bool SanitizerBlacklist::isBlacklistedFile (SanitizerMask Mask, StringRef FileName, StringRef Category = StringRef()) const
Definition at line 47 of file SanitizerBlacklist.cpp.
References Category.
Referenced by isBlacklistedLocation().
isBlacklistedFunction()
bool SanitizerBlacklist::isBlacklistedFunction (SanitizerMask Mask, StringRef FunctionName) const
Definition at line 42 of file SanitizerBlacklist.cpp.
isBlacklistedGlobal()
bool SanitizerBlacklist::isBlacklistedGlobal (SanitizerMask Mask, StringRef GlobalName, StringRef Category = StringRef()) const
Definition at line 30 of file SanitizerBlacklist.cpp.
References Category.
isBlacklistedLocation()
bool SanitizerBlacklist::isBlacklistedLocation (SanitizerMask Mask, SourceLocation Loc, StringRef Category = StringRef()) const
Definition at line 53 of file SanitizerBlacklist.cpp.
References Category, clang::SourceManager::getFileLoc(), clang::SourceManager::getFilename(), isBlacklistedFile(), and clang::SourceLocation::isValid().
Referenced by clang::CodeGen::CodeGenModule::isInSanitizerBlacklist().
isBlacklistedType()
bool SanitizerBlacklist::isBlacklistedType (SanitizerMask Mask, StringRef MangledTypeName, StringRef Category = StringRef()) const
Definition at line 36 of file SanitizerBlacklist.cpp.
References Category.
The documentation for this class was generated from the following files:
include/clang/Basic/SanitizerBlacklist.h
lib/Basic/SanitizerBlacklist.cpp