clang: clang::DependentTemplateName Class Reference
clang::DependentTemplateName Class Reference
Represents a dependent template name that cannot be resolved prior to template instantiation.
#include "clang/AST/TemplateName.h"
Public Member Functions
NestedNameSpecifier * getQualifier () const
Return the nested name specifier that qualifies this name.
bool isIdentifier () const
Determine whether this template name refers to an identifier.
const IdentifierInfo * getIdentifier () const
Returns the identifier to which this template name refers.
bool isOverloadedOperator () const
Determine whether this template name refers to an overloaded operator.
OverloadedOperatorKind getOperator () const
Return the overloaded operator to which this template name refers.
void Profile (llvm::FoldingSetNodeID &ID)
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, NestedNameSpecifier *NNS, const IdentifierInfo *Identifier)
static void Profile (llvm::FoldingSetNodeID &ID, NestedNameSpecifier *NNS, OverloadedOperatorKind Operator)
Friends
class ASTContext
Detailed Description
Represents a dependent template name that cannot be resolved prior to template instantiation.
This kind of template name refers to a dependent template name, including its nested name specifier (if any). For example, DependentTemplateName can refer to "MetaFun::template apply", where "MetaFun::" is the nested name specifier and "apply" is the template name referenced. The "template" keyword is implied.
Definition at line 447 of file TemplateName.h.
Member Function Documentation
getIdentifier()
const IdentifierInfo * clang::DependentTemplateName::getIdentifier () const inline
Returns the identifier to which this template name refers.
Definition at line 509 of file TemplateName.h.
References Identifier, and isIdentifier().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::CheckTemplateIdType(), clang::ASTContext::getNameForTemplate(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and Profile().
getOperator()
OverloadedOperatorKind clang::DependentTemplateName::getOperator () const inline
Return the overloaded operator to which this template name refers.
Definition at line 519 of file TemplateName.h.
References isOverloadedOperator(), and Operator.
Referenced by clang::ASTContext::getNameForTemplate(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and Profile().
getQualifier()
NestedNameSpecifier * clang::DependentTemplateName::getQualifier () const inline
Return the nested name specifier that qualifies this name.
Definition at line 503 of file TemplateName.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::CheckTemplateIdType(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and Profile().
isIdentifier()
bool clang::DependentTemplateName::isIdentifier () const inline
Determine whether this template name refers to an identifier.
Definition at line 506 of file TemplateName.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::CheckTemplateIdType(), getIdentifier(), clang::ASTContext::getNameForTemplate(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and Profile().
isOverloadedOperator()
bool clang::DependentTemplateName::isOverloadedOperator () const inline
Determine whether this template name refers to an overloaded operator.
Definition at line 516 of file TemplateName.h.
Referenced by getOperator(), and IsStructurallyEquivalent().
Profile() [1/3]
void clang::DependentTemplateName::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 525 of file TemplateName.h.
References getIdentifier(), getOperator(), getQualifier(), isIdentifier(), and Profile().
Referenced by clang::ASTContext::getDependentTemplateName(), clang::ASTContext::getDependentTemplateName(), and Profile().
Profile() [2/3]
static void clang::DependentTemplateName::Profile (llvm::FoldingSetNodeID & ID, NestedNameSpecifier * NNS, const IdentifierInfo * Identifier) inline static
Definition at line 532 of file TemplateName.h.
References Identifier.
Profile() [3/3]
static void clang::DependentTemplateName::Profile (llvm::FoldingSetNodeID & ID, NestedNameSpecifier * NNS, OverloadedOperatorKind Operator) inline static
Definition at line 539 of file TemplateName.h.
References Operator.
Friends And Related Symbol Documentation
ASTContext
friend class ASTContext friend
Definition at line 448 of file TemplateName.h.
Member Data Documentation
Identifier
const IdentifierInfo* clang::DependentTemplateName::Identifier
The identifier template name.
Only valid when the bit on Qualifier is clear.
Definition at line 463 of file TemplateName.h.
Referenced by getIdentifier(), and Profile().
Operator
OverloadedOperatorKind clang::DependentTemplateName::Operator
The overloaded operator name.
Only valid when the bit on Qualifier is set.
Definition at line 468 of file TemplateName.h.
Referenced by getOperator(), and Profile().
The documentation for this class was generated from the following file:
include/clang/AST/TemplateName.h