clang: clang::WrapperFrontendAction Class Reference
clang::WrapperFrontendAction Class Reference
A frontend action which simply wraps some other runtime-specified frontend action.
#include "clang/Frontend/FrontendAction.h"
Public Member Functions
WrapperFrontendAction (std::unique_ptr< FrontendAction > WrappedAction)
Construct a WrapperFrontendAction from an existing action, taking ownership of it.
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
TranslationUnitKind getTranslationUnitKind () override
For AST-based actions, the kind of translation unit we're handling.
bool hasPCHSupport () const override
Does this action support use with PCH?
bool hasASTFileSupport () const override
Does this action support use with AST files?
bool hasIRSupport () const override
Does this action support use with IR files?
bool hasCodeCompletionSupport () const override
Does this action support use with code completion?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Protected Member Functions
bool PrepareToExecuteAction (CompilerInstance &CI) override
Prepare to execute the action on the given CompilerInstance.
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
bool BeginInvocation (CompilerInstance &CI) override
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
bool BeginSourceFileAction (CompilerInstance &CI) override
Callback at the start of processing a single input.
void ExecuteAction () override
Callback to run the program action, using the initialized compiler instance.
void EndSourceFileAction () override
Callback at the end of processing a single input.
bool shouldEraseOutputFiles () override
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Protected Member Functions inherited from clang::FrontendAction
Detailed Description
A frontend action which simply wraps some other runtime-specified frontend action.
Deriving from this class allows an action to inject custom logic around some existing action's behavior. It implements every virtual method in the FrontendAction interface by forwarding to the wrapped action.
Definition at line 304 of file FrontendAction.h.
Constructor & Destructor Documentation
WrapperFrontendAction()
WrapperFrontendAction::WrapperFrontendAction (std::unique_ptr< FrontendAction > WrappedAction)
Construct a WrapperFrontendAction from an existing action, taking ownership of it.
Definition at line 1116 of file FrontendAction.cpp.
Member Function Documentation
BeginInvocation()
bool WrapperFrontendAction::BeginInvocation (CompilerInstance & CI) override protected virtual
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
Returns
True on success; on failure BeginSourceFileAction(), ExecuteAction() and EndSourceFileAction() will not be called.
Reimplemented from clang::FrontendAction.
Definition at line 1076 of file FrontendAction.cpp.
BeginSourceFileAction()
bool WrapperFrontendAction::BeginSourceFileAction (CompilerInstance & CI) override protected virtual
Callback at the start of processing a single input.
Returns
True on success; on failure ExecutionAction() and EndSourceFileAction() will not be called.
Reimplemented from clang::FrontendAction.
Definition at line 1079 of file FrontendAction.cpp.
References clang::FrontendAction::getCurrentInput(), Ret(), and clang::FrontendAction::setCurrentInput().
CreateASTConsumer()
std::unique_ptr< ASTConsumer > WrapperFrontendAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) override protected virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Implements clang::FrontendAction.
Definition at line 1072 of file FrontendAction.cpp.
Referenced by clang::arcmt::ObjCMigrateAction::CreateASTConsumer().
EndSourceFileAction()
void WrapperFrontendAction::EndSourceFileAction () override protected virtual
Callback at the end of processing a single input.
This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented from clang::FrontendAction.
Definition at line 1090 of file FrontendAction.cpp.
ExecuteAction()
void WrapperFrontendAction::ExecuteAction () override protected virtual
Callback to run the program action, using the initialized compiler instance.
This is guaranteed to only be called between BeginSourceFileAction() and EndSourceFileAction().
Implements clang::FrontendAction.
Definition at line 1087 of file FrontendAction.cpp.
getTranslationUnitKind()
TranslationUnitKind WrapperFrontendAction::getTranslationUnitKind () override virtual
For AST-based actions, the kind of translation unit we're handling.
Reimplemented from clang::FrontendAction.
Definition at line 1100 of file FrontendAction.cpp.
hasASTFileSupport()
bool WrapperFrontendAction::hasASTFileSupport () const override virtual
Does this action support use with AST files?
Reimplemented from clang::FrontendAction.
Definition at line 1106 of file FrontendAction.cpp.
hasCodeCompletionSupport()
bool WrapperFrontendAction::hasCodeCompletionSupport () const override virtual
Does this action support use with code completion?
Reimplemented from clang::FrontendAction.
Definition at line 1112 of file FrontendAction.cpp.
hasIRSupport()
bool WrapperFrontendAction::hasIRSupport () const override virtual
Does this action support use with IR files?
Reimplemented from clang::FrontendAction.
Definition at line 1109 of file FrontendAction.cpp.
hasPCHSupport()
bool WrapperFrontendAction::hasPCHSupport () const override virtual
Does this action support use with PCH?
Reimplemented from clang::FrontendAction.
Definition at line 1103 of file FrontendAction.cpp.
PrepareToExecuteAction()
bool WrapperFrontendAction::PrepareToExecuteAction (CompilerInstance & CI) override protected virtual
Prepare to execute the action on the given CompilerInstance.
This is called before executing the action on any inputs, and can modify the configuration as needed (including adjusting the input list).
Reimplemented from clang::FrontendAction.
Definition at line 1068 of file FrontendAction.cpp.
shouldEraseOutputFiles()
bool WrapperFrontendAction::shouldEraseOutputFiles () override protected virtual
Callback at the end of processing a single input, to determine if the output files should be erased or not.
By default it returns true if a compiler error occurred. This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented from clang::FrontendAction.
Definition at line 1093 of file FrontendAction.cpp.
usesPreprocessorOnly()
bool WrapperFrontendAction::usesPreprocessorOnly () const override virtual
Does this action only use the preprocessor?
If so no AST context will be created and this action will be invalid with AST file inputs.
Implements clang::FrontendAction.
Definition at line 1097 of file FrontendAction.cpp.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendAction.h
lib/Frontend/FrontendAction.cpp