clang: clang::ProgramPoint Class Reference
clang::ProgramPoint Class Reference
#include "clang/Analysis/ProgramPoint.h"
Public Types
enum Kind {
BlockEdgeKind , BlockEntranceKind , BlockExitKind , PreStmtKind ,
PreStmtPurgeDeadSymbolsKind , PostStmtPurgeDeadSymbolsKind , PostStmtKind , PreLoadKind ,
PostLoadKind , PreStoreKind , PostStoreKind , PostConditionKind ,
PostLValueKind , PostAllocatorCallKind , MinPostStmtKind = PostStmtKind , MaxPostStmtKind = PostAllocatorCallKind ,
PostInitializerKind , CallEnterKind , CallExitBeginKind , CallExitEndKind ,
FunctionExitKind , PreImplicitCallKind , PostImplicitCallKind , MinImplicitCallKind = PreImplicitCallKind ,
MaxImplicitCallKind = PostImplicitCallKind , LoopExitKind , EpsilonKind
}
Public Member Functions
ProgramPoint withTag (const ProgramPointTag *tag) const
Create a new ProgramPoint object that is the same as the original except for using the specified tag value.
template<typename T >
T castAs () const
Convert to the specified ProgramPoint type, asserting that this ProgramPoint is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified ProgramPoint type, returning None if this ProgramPoint is not of the desired type.
Kind getKind () const
bool isPurgeKind ()
Is this a program point corresponding to purge/removal of dead symbols and bindings.
const ProgramPointTag * getTag () const
const LocationContext * getLocationContext () const
const StackFrameContext * getStackFrame () const
unsigned getHashValue () const
bool operator== (const ProgramPoint &RHS) const
bool operator!= (const ProgramPoint &RHS) const
void Profile (llvm::FoldingSetNodeID &ID) const
void printJson (llvm::raw_ostream &Out, const char *NL="\n") const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static ProgramPoint getProgramPoint (const Stmt *S, ProgramPoint::Kind K, const LocationContext *LC, const ProgramPointTag *tag)
Protected Member Functions
ProgramPoint ()=default
ProgramPoint (const void *P, Kind k, const LocationContext *l, const ProgramPointTag *tag=nullptr)
ProgramPoint (const void *P1, const void *P2, Kind k, const LocationContext *l, const ProgramPointTag *tag=nullptr)
const void * getData1 () const
const void * getData2 () const
void setData2 (const void *d)
Detailed Description
Definition at line 59 of file ProgramPoint.h.
Member Enumeration Documentation
Kind
enum clang::ProgramPoint::Kind
Enumerator
BlockEdgeKind
BlockEntranceKind
BlockExitKind
PreStmtKind
PreStmtPurgeDeadSymbolsKind
PostStmtPurgeDeadSymbolsKind
PostStmtKind
PreLoadKind
PostLoadKind
PreStoreKind
PostStoreKind
PostConditionKind
PostLValueKind
PostAllocatorCallKind
MinPostStmtKind
MaxPostStmtKind
PostInitializerKind
CallEnterKind
CallExitBeginKind
CallExitEndKind
FunctionExitKind
PreImplicitCallKind
PostImplicitCallKind
MinImplicitCallKind
MaxImplicitCallKind
LoopExitKind
EpsilonKind
Definition at line 61 of file ProgramPoint.h.
Constructor & Destructor Documentation
ProgramPoint() [1/3]
clang::ProgramPoint::ProgramPoint () protected default
Referenced by withTag().
ProgramPoint() [2/3]
clang::ProgramPoint::ProgramPoint (const void * P, Kind k, const LocationContext * l, const ProgramPointTag * tag = nullptr) inline protected
Definition at line 101 of file ProgramPoint.h.
References getData1(), getKind(), getLocationContext(), and P.
ProgramPoint() [3/3]
clang::ProgramPoint::ProgramPoint (const void * P1, const void * P2, Kind k, const LocationContext * l, const ProgramPointTag * tag = nullptr) inline protected
Definition at line 114 of file ProgramPoint.h.
Member Function Documentation
castAs()
template<typename T > T clang::ProgramPoint::castAs () const inline
Convert to the specified ProgramPoint type, asserting that this ProgramPoint is of the desired type.
Definition at line 140 of file ProgramPoint.h.
Referenced by printJson(), clang::ento::ExprEngine::VisitGuardedExpr(), and clang::ento::ExprEngine::VisitLogicalExpr().
dump()
LLVM_DUMP_METHOD void ProgramPoint::dump () const
Definition at line 47 of file ProgramPoint.cpp.
References printJson().
getAs()
template<typename T > Optional< T > clang::ProgramPoint::getAs () const inline
Convert to the specified ProgramPoint type, returning None if this ProgramPoint is not of the desired type.
Definition at line 151 of file ProgramPoint.h.
References clang::None.
Referenced by clang::ento::CoreEngine::enqueueStmtNode(), getLastStmt(), clang::ento::CheckerContext::getLocationRegionIfPostStore(), clang::ento::PathSensitiveBugReport::getStmt(), printJson(), shouldRemoveDeadBindings(), clang::ento::ExprEngine::VisitGuardedExpr(), clang::ento::FindLastStoreBRVisitor::VisitNode(), and clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode().
getData1()
const void * clang::ProgramPoint::getData1 () const inline protected
Definition at line 125 of file ProgramPoint.h.
Referenced by clang::BlockEntrance::getBlock(), clang::BlockExit::getBlock(), clang::CallExitEnd::getCalleeContext(), clang::CallEnter::getCallExpr(), clang::EpsilonPoint::getData(), clang::PostInitializer::getInitializer(), clang::ImplicitCallPoint::getLocation(), clang::LoopExit::getLoopStmt(), clang::CallExitBegin::getReturnStmt(), clang::BlockEdge::getSrc(), clang::FunctionExitPoint::getStmt(), clang::StmtPoint::getStmt(), Profile(), ProgramPoint(), and withTag().
getData2()
const void * clang::ProgramPoint::getData2 () const inline protected
Definition at line 126 of file ProgramPoint.h.
Referenced by clang::CallEnter::getCalleeContext(), clang::ImplicitCallPoint::getDecl(), clang::BlockEdge::getDst(), clang::PostInitializer::getLocationValue(), clang::PostStore::getLocationValue(), clang::PreStmt::getSubStmt(), clang::PostStore::PostStore(), Profile(), and withTag().
getHashValue()
unsigned clang::ProgramPoint::getHashValue () const inline
Definition at line 188 of file ProgramPoint.h.
References Profile().
Referenced by llvm::DenseMapInfo< clang::ProgramPoint >::getHashValue().
getKind()
Kind clang::ProgramPoint::getKind () const inline
Definition at line 160 of file ProgramPoint.h.
Referenced by isPurgeKind(), printJson(), Profile(), ProgramPoint(), and withTag().
getLocationContext()
const LocationContext * clang::ProgramPoint::getLocationContext () const inline
Definition at line 179 of file ProgramPoint.h.
Referenced by clang::ento::PathDiagnosticCallPiece::construct(), clang::FunctionExitPoint::getBlock(), clang::ento::ExplodedNode::getLocationContext(), getStackFrame(), clang::ento::PathSensitiveBugReport::getStmt(), printJson(), clang::ento::ExprEngine::processCFGBlockEntrance(), Profile(), ProgramPoint(), clang::ento::PathDiagnosticCallPiece::setCallee(), and withTag().
getProgramPoint()
ProgramPoint ProgramPoint::getProgramPoint (const Stmt * S, ProgramPoint::Kind K, const LocationContext * LC, const ProgramPointTag * tag) static
Definition at line 22 of file ProgramPoint.cpp.
References PostLoadKind, PostLValueKind, PostStmtKind, PostStmtPurgeDeadSymbolsKind, PreLoadKind, PreStmtKind, PreStmtPurgeDeadSymbolsKind, and PreStoreKind.
Referenced by clang::ento::StmtNodeBuilder::generateNode(), clang::ento::StmtNodeBuilder::generateSink(), and clang::ento::CheckerManager::runCheckersForEvalCall().
getStackFrame()
const StackFrameContext * clang::ProgramPoint::getStackFrame () const inline
Definition at line 183 of file ProgramPoint.h.
References getLocationContext(), and clang::LocationContext::getStackFrame().
Referenced by getLastStmt(), and clang::ento::ExplodedNode::getStackFrame().
getTag()
const ProgramPointTag * clang::ProgramPoint::getTag () const inline
Definition at line 177 of file ProgramPoint.h.
Referenced by clang::ento::CheckerContext::generateErrorNode(), clang::ento::CheckerContext::generateNonFatalErrorNode(), clang::ento::CheckerContext::generateNonFatalErrorNode(), Profile(), and clang::ento::ExprEngine::VisitObjCMessage().
isPurgeKind()
bool clang::ProgramPoint::isPurgeKind () inline
Is this a program point corresponding to purge/removal of dead symbols and bindings.
Definition at line 171 of file ProgramPoint.h.
References getKind(), PostStmtPurgeDeadSymbolsKind, and PreStmtPurgeDeadSymbolsKind.
operator!=()
bool clang::ProgramPoint::operator!= (const ProgramPoint & RHS) const inline
Definition at line 201 of file ProgramPoint.h.
operator==()
bool clang::ProgramPoint::operator== (const ProgramPoint & RHS) const inline
Definition at line 194 of file ProgramPoint.h.
printJson()
void ProgramPoint::printJson (llvm::raw_ostream & Out, const char * NL = "\n") const
Definition at line 51 of file ProgramPoint.cpp.
References BlockEdgeKind, BlockEntranceKind, BlockExitKind, clang::C, CallEnterKind, CallExitBeginKind, CallExitEndKind, castAs(), EpsilonKind, FunctionExitKind, clang::LocationContext::getAnalysisDeclContext(), getAs(), clang::Decl::getAsFunction(), clang::AnalysisDeclContext::getASTContext(), clang::CFGBlock::getBlockID(), clang::ImplicitCallPoint::getDecl(), clang::BlockEdge::getDst(), getKind(), clang::CFGBlock::getLabel(), clang::ASTContext::getLangOpts(), clang::QualType::getLocalUnqualifiedType(), clang::ImplicitCallPoint::getLocation(), getLocationContext(), clang::ASTContext::getPrintingPolicy(), clang::NamedDecl::getQualifiedNameAsString(), clang::ASTContext::getSourceManager(), clang::BlockEdge::getSrc(), clang::CFGBlock::getTerminatorStmt(), Label, LoopExitKind, PostImplicitCallKind, PostInitializerKind, PreImplicitCallKind, clang::QualType::print(), clang::printSourceLocationAsJson(), clang::CFGBlock::printTerminatorJson(), and SM.
Referenced by dump().
Profile()
void clang::ProgramPoint::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 208 of file ProgramPoint.h.
References getData1(), getData2(), getKind(), getLocationContext(), and getTag().
Referenced by getHashValue().
setData2()
void clang::ProgramPoint::setData2 (const void * d) inline protected
Definition at line 127 of file ProgramPoint.h.
Referenced by clang::PostStore::PostStore().
withTag()
ProgramPoint clang::ProgramPoint::withTag (const ProgramPointTag * tag) const inline
Create a new ProgramPoint object that is the same as the original except for using the specified tag value.
Definition at line 132 of file ProgramPoint.h.
References getData1(), getData2(), getKind(), getLocationContext(), and ProgramPoint().
Referenced by clang::ento::NodeBuilderWithSinks::generateNode(), clang::ento::NodeBuilderWithSinks::generateSink(), and clang::ento::ExprEngine::VisitCXXDestructor().
The documentation for this class was generated from the following files:
include/clang/Analysis/ProgramPoint.h
lib/Analysis/ProgramPoint.cpp