clang: clang::BackendConsumer Class Reference
clang::BackendConsumer Class Reference
Public Member Functions
BackendConsumer (BackendAction Action, DiagnosticsEngine &Diags, const HeaderSearchOptions &HeaderSearchOpts, const PreprocessorOptions &PPOpts, const CodeGenOptions &CodeGenOpts, const TargetOptions &TargetOpts, const LangOptions &LangOpts, const std::string &InFile, SmallVector< LinkModule, 4 > LinkModules, std::unique_ptr< raw_pwrite_stream > OS, LLVMContext &C, CoverageSourceInfo *CoverageInfo=nullptr)
BackendConsumer (BackendAction Action, DiagnosticsEngine &Diags, const HeaderSearchOptions &HeaderSearchOpts, const PreprocessorOptions &PPOpts, const CodeGenOptions &CodeGenOpts, const TargetOptions &TargetOpts, const LangOptions &LangOpts, SmallVector< LinkModule, 4 > LinkModules, LLVMContext &C, CoverageSourceInfo *CoverageInfo=nullptr)
llvm::Module * getModule () const
std::unique_ptr< llvm::Module > takeModule ()
CodeGenerator * getCodeGenerator ()
void HandleCXXStaticMemberVarInstantiation (VarDecl *VD) override
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
void Initialize (ASTContext &Ctx) override
Initialize - This is called to initialize the consumer, providing the ASTContext.
bool HandleTopLevelDecl (DeclGroupRef D) override
HandleTopLevelDecl - Handle the specified top-level declaration.
void HandleInlineFunctionDefinition (FunctionDecl *D) override
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
void HandleInterestingDecl (DeclGroupRef D) override
HandleInterestingDecl - Handle the specified interesting declaration.
bool LinkInModules ()
void HandleTranslationUnit (ASTContext &C) override
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
void HandleTagDeclDefinition (TagDecl *D) override
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
void HandleTagDeclRequiredDefinition (const TagDecl *D) override
This callback is invoked the first time each TagDecl is required to be complete.
void CompleteTentativeDefinition (VarDecl *D) override
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
void CompleteExternalDeclaration (VarDecl *D) override
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
void AssignInheritanceModel (CXXRecordDecl *RD) override
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
void HandleVTable (CXXRecordDecl *RD) override
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
const FullSourceLoc getBestLocationFromDebugLoc (const llvm::DiagnosticInfoWithLocationBase &D, bool &BadDebugInfo, StringRef &Filename, unsigned &Line, unsigned &Column) const
Get the best possible source location to represent a diagnostic that may have associated debug info.
void InlineAsmDiagHandler2 (const llvm::SMDiagnostic &, SourceLocation LocCookie)
InlineAsmDiagHandler2 - This function is invoked when the backend hits an error parsing inline asm.
void DiagnosticHandlerImpl (const llvm::DiagnosticInfo &DI)
This function is invoked when the backend needs to report something to the user.
bool InlineAsmDiagHandler (const llvm::DiagnosticInfoInlineAsm &D)
Specialized handler for InlineAsm diagnostic.
bool StackSizeDiagHandler (const llvm::DiagnosticInfoStackSize &D)
Specialized handler for StackSize diagnostic.
void UnsupportedDiagHandler (const llvm::DiagnosticInfoUnsupported &D)
Specialized handler for unsupported backend feature diagnostic.
void EmitOptimizationMessage (const llvm::DiagnosticInfoOptimizationBase &D, unsigned DiagID)
Specialized handlers for optimization remarks.
void OptimizationRemarkHandler (const llvm::DiagnosticInfoOptimizationBase &D)
void OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisFPCommute &D)
void OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisAliasing &D)
void OptimizationFailureHandler (const llvm::DiagnosticInfoOptimizationFailure &D)
Public Member Functions inherited from clang::ASTConsumer
ASTConsumer ()
virtual ~ASTConsumer ()
virtual void HandleCXXImplicitFunctionInstantiation (FunctionDecl *D)
Invoked when a function is implicitly instantiated.
virtual void HandleTopLevelDeclInObjCContainer (DeclGroupRef D)
Handle the specified top-level declaration that occurred inside and ObjC container.
virtual void HandleImplicitImportDecl (ImportDecl *D)
Handle an ImportDecl that was implicitly created due to an inclusion directive.
virtual ASTMutationListener * GetASTMutationListener ()
If the consumer is interested in entities getting modified after their initial creation, it should return a pointer to an ASTMutationListener here.
virtual ASTDeserializationListener * GetASTDeserializationListener ()
If the consumer is interested in entities being deserialized from AST files, it should return a pointer to a ASTDeserializationListener here.
virtual void PrintStats ()
PrintStats - If desired, print any statistics.
virtual bool shouldSkipFunctionBody (Decl *D)
This callback is called for each function if the Parser was initialized with SkipFunctionBodies set to true.
Static Public Member Functions
static void InlineAsmDiagHandler (const llvm::SMDiagnostic &SM, void *Context, unsigned LocCookie)
Detailed Description
Definition at line 104 of file CodeGenAction.cpp.
Constructor & Destructor Documentation
BackendConsumer() [1/2]
clang::BackendConsumer::BackendConsumer (BackendAction Action, DiagnosticsEngine & Diags, const HeaderSearchOptions & HeaderSearchOpts, const PreprocessorOptions & PPOpts, const CodeGenOptions & CodeGenOpts, const TargetOptions & TargetOpts, const LangOptions & LangOpts, const std::string & InFile, SmallVector< LinkModule, 4 > LinkModules, std::unique_ptr< raw_pwrite_stream > OS, LLVMContext & C, CoverageSourceInfo * CoverageInfo = nullptr) inline
Definition at line 136 of file CodeGenAction.cpp.
BackendConsumer() [2/2]
clang::BackendConsumer::BackendConsumer (BackendAction Action, DiagnosticsEngine & Diags, const HeaderSearchOptions & HeaderSearchOpts, const PreprocessorOptions & PPOpts, const CodeGenOptions & CodeGenOpts, const TargetOptions & TargetOpts, const LangOptions & LangOpts, SmallVector< LinkModule, 4 > LinkModules, LLVMContext & C, CoverageSourceInfo * CoverageInfo = nullptr) inline
Definition at line 161 of file CodeGenAction.cpp.
Member Function Documentation
AssignInheritanceModel()
void clang::BackendConsumer::AssignInheritanceModel (CXXRecordDecl * RD) inline override virtual
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
Reimplemented from clang::ASTConsumer.
Definition at line 375 of file CodeGenAction.cpp.
CompleteExternalDeclaration()
void clang::BackendConsumer::CompleteExternalDeclaration (VarDecl * D) inline override virtual
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
Reimplemented from clang::ASTConsumer.
Definition at line 371 of file CodeGenAction.cpp.
CompleteTentativeDefinition()
void clang::BackendConsumer::CompleteTentativeDefinition (VarDecl * D) inline override virtual
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
The variable declaration itself will be a tentative definition. If it had an incomplete array type, its type will have already been changed to an array of size 1. However, the declaration remains a tentative definition and has not been modified by the introduction of an implicit zero initializer.
Reimplemented from clang::ASTConsumer.
Definition at line 367 of file CodeGenAction.cpp.
DiagnosticHandlerImpl()
void BackendConsumer::DiagnosticHandlerImpl (const llvm::DiagnosticInfo & DI)
This function is invoked when the backend needs to report something to the user.
Definition at line 784 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), ComputeDiagID, ComputeDiagRemarkID, InlineAsmDiagHandler(), OptimizationFailureHandler(), OptimizationRemarkHandler(), clang::DiagnosticsEngine::Report(), StackSizeDiagHandler(), and UnsupportedDiagHandler().
Referenced by clang::ClangDiagnosticHandler::handleDiagnostics().
EmitOptimizationMessage()
void BackendConsumer::EmitOptimizationMessage (const llvm::DiagnosticInfoOptimizationBase & D, unsigned DiagID)
Specialized handlers for optimization remarks.
Note that these handlers only accept remarks and they always handle them.
Definition at line 677 of file CodeGenAction.cpp.
References Filename, getBestLocationFromDebugLoc(), and clang::DiagnosticsEngine::Report().
Referenced by OptimizationFailureHandler(), OptimizationRemarkHandler(), OptimizationRemarkHandler(), and OptimizationRemarkHandler().
getBestLocationFromDebugLoc()
const FullSourceLoc BackendConsumer::getBestLocationFromDebugLoc (const llvm::DiagnosticInfoWithLocationBase & D, bool & BadDebugInfo, StringRef & Filename, unsigned & Line, unsigned & Column) const
Get the best possible source location to represent a diagnostic that may have associated debug info.
Definition at line 599 of file CodeGenAction.cpp.
References Filename, clang::FileManager::getFile(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isInvalid(), and clang::DiagnosticsEngine::Report().
Referenced by EmitOptimizationMessage(), and UnsupportedDiagHandler().
getCodeGenerator()
CodeGenerator * clang::BackendConsumer::getCodeGenerator () inline
Definition at line 186 of file CodeGenAction.cpp.
Referenced by clang::CodeGenAction::CreateASTConsumer().
getModule()
llvm::Module * clang::BackendConsumer::getModule () const inline
Definition at line 181 of file CodeGenAction.cpp.
Referenced by LinkInModules().
HandleCXXStaticMemberVarInstantiation()
void clang::BackendConsumer::HandleCXXStaticMemberVarInstantiation (VarDecl * D) inline override virtual
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
Reimplemented from clang::ASTConsumer.
Definition at line 188 of file CodeGenAction.cpp.
HandleInlineFunctionDefinition()
void clang::BackendConsumer::HandleInlineFunctionDefinition (FunctionDecl * D) inline override virtual
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
Reimplemented from clang::ASTConsumer.
Definition at line 229 of file CodeGenAction.cpp.
References clang::ASTContext::getSourceManager().
HandleInterestingDecl()
void clang::BackendConsumer::HandleInterestingDecl (DeclGroupRef D) inline override virtual
HandleInterestingDecl - Handle the specified interesting declaration.
This is called by the AST reader when deserializing things that might interest the consumer. The default implementation forwards to HandleTopLevelDecl.
Reimplemented from clang::ASTConsumer.
Definition at line 242 of file CodeGenAction.cpp.
References HandleTopLevelDecl().
HandleTagDeclDefinition()
void clang::BackendConsumer::HandleTagDeclDefinition (TagDecl * D) inline override virtual
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
struct, union, enum, class) is completed. This allows the client to hack on the type, which can occur at any point in the file (because these can be defined in declspecs).
Reimplemented from clang::ASTConsumer.
Definition at line 356 of file CodeGenAction.cpp.
References clang::ASTContext::getSourceManager().
HandleTagDeclRequiredDefinition()
void clang::BackendConsumer::HandleTagDeclRequiredDefinition (const TagDecl * D) inline override virtual
This callback is invoked the first time each TagDecl is required to be complete.
Reimplemented from clang::ASTConsumer.
Definition at line 363 of file CodeGenAction.cpp.
HandleTopLevelDecl()
bool clang::BackendConsumer::HandleTopLevelDecl (DeclGroupRef D) inline override virtual
HandleTopLevelDecl - Handle the specified top-level declaration.
This is called by the parser to process every top-level Decl*.
Returns
true to continue parsing, or false to abort parsing.
Reimplemented from clang::ASTConsumer.
Definition at line 206 of file CodeGenAction.cpp.
References clang::DeclGroupRef::begin(), and clang::ASTContext::getSourceManager().
Referenced by HandleInterestingDecl().
HandleTranslationUnit()
void clang::BackendConsumer::HandleTranslationUnit (ASTContext & Ctx) inline override virtual
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
Reimplemented from clang::ASTConsumer.
Definition at line 282 of file CodeGenAction.cpp.
References clang::C, clang::EmbedBitcode(), clang::EmitBackendOutput(), clang::CodeGenOptions::ProfileNone, and clang::reportOptRecordError().
HandleVTable()
void clang::BackendConsumer::HandleVTable (CXXRecordDecl * RD) inline override virtual
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
Parameters
RD The class whose vtable was used.
Reimplemented from clang::ASTConsumer.
Definition at line 379 of file CodeGenAction.cpp.
Initialize()
void clang::BackendConsumer::Initialize (ASTContext & Context) inline override virtual
Initialize - This is called to initialize the consumer, providing the ASTContext.
Reimplemented from clang::ASTConsumer.
Definition at line 192 of file CodeGenAction.cpp.
InlineAsmDiagHandler() [1/2]
bool BackendConsumer::InlineAsmDiagHandler (const llvm::DiagnosticInfoInlineAsm & D)
Specialized handler for InlineAsm diagnostic.
Returns
True if the diagnostic has been successfully reported, false otherwise.
Definition at line 557 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), ComputeDiagID, clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
InlineAsmDiagHandler() [2/2]
static void clang::BackendConsumer::InlineAsmDiagHandler (const llvm::SMDiagnostic & SM, void * Context, unsigned LocCookie) inline static
Definition at line 383 of file CodeGenAction.cpp.
References clang::SourceLocation::getFromRawEncoding(), and SM.
Referenced by DiagnosticHandlerImpl().
InlineAsmDiagHandler2()
void BackendConsumer::InlineAsmDiagHandler2 (const llvm::SMDiagnostic & D, SourceLocation LocCookie)
InlineAsmDiagHandler2 - This function is invoked when the backend hits an error parsing inline asm.
The SMDiagnostic indicates the error relative to the temporary memory buffer that the inline asm parser has set up.
Definition at line 466 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), ConvertBackendLocation(), clang::SourceLocation::getLocWithOffset(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
LinkInModules()
bool clang::BackendConsumer::LinkInModules () inline
Definition at line 249 of file CodeGenAction.cpp.
References getModule().
OptimizationFailureHandler()
void BackendConsumer::OptimizationFailureHandler (const llvm::DiagnosticInfoOptimizationFailure & D)
Definition at line 777 of file CodeGenAction.cpp.
References EmitOptimizationMessage().
Referenced by DiagnosticHandlerImpl().
OptimizationRemarkHandler() [1/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::DiagnosticInfoOptimizationBase & D)
Definition at line 716 of file CodeGenAction.cpp.
References EmitOptimizationMessage(), clang::CodeGenOptions::OptimizationRemarkAnalysisPattern, clang::CodeGenOptions::OptimizationRemarkMissedPattern, and clang::CodeGenOptions::OptimizationRemarkPattern.
Referenced by DiagnosticHandlerImpl().
OptimizationRemarkHandler() [2/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisAliasing & D)
Definition at line 764 of file CodeGenAction.cpp.
References EmitOptimizationMessage(), and clang::CodeGenOptions::OptimizationRemarkAnalysisPattern.
OptimizationRemarkHandler() [3/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisFPCommute & D)
Definition at line 751 of file CodeGenAction.cpp.
References EmitOptimizationMessage(), and clang::CodeGenOptions::OptimizationRemarkAnalysisPattern.
StackSizeDiagHandler()
bool BackendConsumer::StackSizeDiagHandler (const llvm::DiagnosticInfoStackSize & D)
Specialized handler for StackSize diagnostic.
Returns
True if the diagnostic has been successfully reported, false otherwise.
Definition at line 582 of file CodeGenAction.cpp.
References clang::Decl::castToDeclContext(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
takeModule()
std::unique_ptr< llvm::Module > clang::BackendConsumer::takeModule () inline
Definition at line 182 of file CodeGenAction.cpp.
Referenced by clang::CodeGenAction::EndSourceFileAction().
UnsupportedDiagHandler()
void BackendConsumer::UnsupportedDiagHandler (const llvm::DiagnosticInfoUnsupported & D)
Specialized handler for unsupported backend feature diagnostic.
Definition at line 640 of file CodeGenAction.cpp.
References Filename, getBestLocationFromDebugLoc(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenAction.cpp