clang: clang::CompilerInstance Class Reference
clang::CompilerInstance Class Reference
CompilerInstance - Helper class for managing a single instance of the Clang compiler.
#include "clang/Frontend/CompilerInstance.h"
Public Member Functions
CompilerInstance (std::shared_ptr< PCHContainerOperations > PCHContainerOps=std::make_shared< PCHContainerOperations >(), InMemoryModuleCache *SharedModuleCache=nullptr)
~CompilerInstance () override
High-Level Operations
{
bool ExecuteAction (FrontendAction &Act)
ExecuteAction - Execute the provided action against the compiler's CompilerInvocation object.
Compiler Invocation and Options
}
{
bool hasInvocation () const
CompilerInvocation & getInvocation ()
void setInvocation (std::shared_ptr< CompilerInvocation > Value)
setInvocation - Replace the current invocation.
bool shouldBuildGlobalModuleIndex () const
Indicates whether we should (re)build the global module index.
void setBuildGlobalModuleIndex (bool Build)
Set the flag indicating whether we should (re)build the global module index.
Forwarding Methods
}
{
AnalyzerOptionsRef getAnalyzerOpts ()
CodeGenOptions & getCodeGenOpts ()
const CodeGenOptions & getCodeGenOpts () const
DependencyOutputOptions & getDependencyOutputOpts ()
const DependencyOutputOptions & getDependencyOutputOpts () const
DiagnosticOptions & getDiagnosticOpts ()
const DiagnosticOptions & getDiagnosticOpts () const
FileSystemOptions & getFileSystemOpts ()
const FileSystemOptions & getFileSystemOpts () const
FrontendOptions & getFrontendOpts ()
const FrontendOptions & getFrontendOpts () const
HeaderSearchOptions & getHeaderSearchOpts ()
const HeaderSearchOptions & getHeaderSearchOpts () const
std::shared_ptr< HeaderSearchOptions > getHeaderSearchOptsPtr () const
LangOptions & getLangOpts ()
const LangOptions & getLangOpts () const
PreprocessorOptions & getPreprocessorOpts ()
const PreprocessorOptions & getPreprocessorOpts () const
PreprocessorOutputOptions & getPreprocessorOutputOpts ()
const PreprocessorOutputOptions & getPreprocessorOutputOpts () const
TargetOptions & getTargetOpts ()
const TargetOptions & getTargetOpts () const
Diagnostics Engine
}
{
bool hasDiagnostics () const
DiagnosticsEngine & getDiagnostics () const
Get the current diagnostics engine.
void setDiagnostics (DiagnosticsEngine *Value)
setDiagnostics - Replace the current diagnostics engine.
DiagnosticConsumer & getDiagnosticClient () const
VerboseOutputStream
}
}
void setVerboseOutputStream (raw_ostream &Value)
Replace the current stream for verbose output.
void setVerboseOutputStream (std::unique_ptr< raw_ostream > Value)
Replace the current stream for verbose output.
raw_ostream & getVerboseOutputStream ()
Get the current stream for verbose output.
Target Info
}
{
bool hasTarget () const
TargetInfo & getTarget () const
void setTarget (TargetInfo *Value)
Replace the current Target.
AuxTarget Info
}
{
TargetInfo * getAuxTarget () const
void setAuxTarget (TargetInfo *Value)
Replace the current AuxTarget.
Virtual File System
}
{
llvm::vfs::FileSystem & getVirtualFileSystem () const
File Manager
}
{
bool hasFileManager () const
FileManager & getFileManager () const
Return the current file manager to the caller.
void resetAndLeakFileManager ()
void setFileManager (FileManager *Value)
Replace the current file manager and virtual file system.
Source Manager
}
{
bool hasSourceManager () const
SourceManager & getSourceManager () const
Return the current source manager.
void resetAndLeakSourceManager ()
void setSourceManager (SourceManager *Value)
setSourceManager - Replace the current source manager.
Preprocessor
}
{
bool hasPreprocessor () const
Preprocessor & getPreprocessor () const
Return the current preprocessor.
std::shared_ptr< Preprocessor > getPreprocessorPtr ()
void resetAndLeakPreprocessor ()
void setPreprocessor (std::shared_ptr< Preprocessor > Value)
Replace the current preprocessor.
ASTContext
}
{
bool hasASTContext () const
ASTContext & getASTContext () const
void resetAndLeakASTContext ()
void setASTContext (ASTContext *Value)
setASTContext - Replace the current AST context.
void setSema (Sema *S)
Replace the current Sema; the compiler instance takes ownership of S.
ASTConsumer
}
{
bool hasASTConsumer () const
ASTConsumer & getASTConsumer () const
std::unique_ptr< ASTConsumer > takeASTConsumer ()
takeASTConsumer - Remove the current AST consumer and give ownership to the caller.
void setASTConsumer (std::unique_ptr< ASTConsumer > Value)
setASTConsumer - Replace the current AST consumer; the compiler instance takes ownership of Value.
Semantic analysis
}
{
bool hasSema () const
Sema & getSema () const
std::unique_ptr< Sema > takeSema ()
void resetAndLeakSema ()
Module Management
}
{
IntrusiveRefCntPtr< ASTReader > getASTReader () const
void setASTReader (IntrusiveRefCntPtr< ASTReader > Reader)
std::shared_ptr< ModuleDependencyCollector > getModuleDepCollector () const
void setModuleDepCollector (std::shared_ptr< ModuleDependencyCollector > Collector)
std::shared_ptr< PCHContainerOperations > getPCHContainerOperations () const
const PCHContainerWriter & getPCHContainerWriter () const
Return the appropriate PCHContainerWriter depending on the current CodeGenOptions.
const PCHContainerReader & getPCHContainerReader () const
Return the appropriate PCHContainerReader depending on the current CodeGenOptions.
Code Completion
}
{
bool hasCodeCompletionConsumer () const
CodeCompleteConsumer & getCodeCompletionConsumer () const
void setCodeCompletionConsumer (CodeCompleteConsumer *Value)
setCodeCompletionConsumer - Replace the current code completion consumer; the compiler instance takes ownership of Value.
Frontend timer
}
{
bool hasFrontendTimer () const
llvm::Timer & getFrontendTimer () const
Output Files
}
{
void clearOutputFiles (bool EraseFiles)
clearOutputFiles - Clear the output file list.
Public Member Functions inherited from clang::ModuleLoader
ModuleLoader (bool BuildingModule=false)
virtual ~ModuleLoader ()
bool buildingModule () const
Returns true if this instance is building a module.
void setBuildingModule (bool BuildingModuleFlag)
Flag indicating whether this instance is building a module.
Construction Utility Methods
}
{
void createDiagnostics (DiagnosticConsumer *Client=nullptr, bool ShouldOwnClient=true)
Create the diagnostics engine using the invocation's diagnostic options and replace any existing one with it.
FileManager * createFileManager (IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS=nullptr)
Create the file manager and replace any existing one with it.
void createSourceManager (FileManager &FileMgr)
Create the source manager and replace any existing one with it.
void createPreprocessor (TranslationUnitKind TUKind)
Create the preprocessor, using the invocation, file, and source managers, and replace any existing one with it.
std::string getSpecificModuleCachePath (StringRef ModuleHash)
std::string getSpecificModuleCachePath ()
void createASTContext ()
Create the AST context.
void createPCHExternalASTSource (StringRef Path, DisableValidationForModuleKind DisableValidation, bool AllowPCHWithCompilerErrors, void *DeserializationListener, bool OwnDeserializationListener)
Create an external AST source to read a PCH file and attach it to the AST context.
void createCodeCompletionConsumer ()
Create a code completion consumer using the invocation; note that this will cause the source manager to truncate the input source file at the completion point.
void createSema (TranslationUnitKind TUKind, CodeCompleteConsumer *CompletionConsumer)
Create the Sema object to be used for parsing.
void createFrontendTimer ()
Create the frontend timer and replace any existing one with it.
std::unique_ptr< raw_pwrite_stream > createDefaultOutputFile (bool Binary=true, StringRef BaseInput="", StringRef Extension="", bool RemoveFileOnSignal=true, bool CreateMissingDirectories=false)
Create the default output file (from the invocation's options) and add it to the list of tracked output files.
std::unique_ptr< raw_pwrite_stream > createOutputFile (StringRef OutputPath, bool Binary, bool RemoveFileOnSignal, bool UseTemporary, bool CreateMissingDirectories=false)
Create a new output file, optionally deriving the output path name, and add it to the list of tracked output files.
std::unique_ptr< raw_pwrite_stream > createNullOutputFile ()
static IntrusiveRefCntPtr< DiagnosticsEngine > createDiagnostics (DiagnosticOptions *Opts, DiagnosticConsumer *Client=nullptr, bool ShouldOwnClient=true, const CodeGenOptions *CodeGenOpts=nullptr)
Create a DiagnosticsEngine object with a the TextDiagnosticPrinter.
static IntrusiveRefCntPtr< ASTReader > createPCHExternalASTSource (StringRef Path, StringRef Sysroot, DisableValidationForModuleKind DisableValidation, bool AllowPCHWithCompilerErrors, Preprocessor &PP, InMemoryModuleCache &ModuleCache, ASTContext &Context, const PCHContainerReader &PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension > > Extensions, ArrayRef< std::shared_ptr< DependencyCollector > > DependencyCollectors, void *DeserializationListener, bool OwnDeserializationListener, bool Preamble, bool UseGlobalModuleIndex)
Create an external AST source to read a PCH file.
static CodeCompleteConsumer * createCodeCompletionConsumer (Preprocessor &PP, StringRef Filename, unsigned Line, unsigned Column, const CodeCompleteOptions &Opts, raw_ostream &OS)
Create a code completion consumer to print code completion results, at Filename, Line, and Column, to the given output stream OS.
Initialization Utility Methods
}
{
bool InitializeSourceManager (const FrontendInputFile &Input)
InitializeSourceManager - Initialize the source manager to set InputFile as the main file.
void setOutputStream (std::unique_ptr< llvm::raw_pwrite_stream > OutStream)
}
std::unique_ptr< llvm::raw_pwrite_stream > takeOutputStream ()
void createASTReader ()
bool loadModuleFile (StringRef FileName)
ModuleLoadResult loadModule (SourceLocation ImportLoc, ModuleIdPath Path, Module::NameVisibilityKind Visibility, bool IsInclusionDirective) override
Attempt to load the given module.
void createModuleFromSource (SourceLocation ImportLoc, StringRef ModuleName, StringRef Source) override
Attempt to create the given module from the specified source buffer.
void makeModuleVisible (Module *Mod, Module::NameVisibilityKind Visibility, SourceLocation ImportLoc) override
Make the given module visible.
bool hadModuleLoaderFatalFailure () const
GlobalModuleIndex * loadGlobalModuleIndex (SourceLocation TriggerLoc) override
Load, create, or return global module.
bool lookupMissingImports (StringRef Name, SourceLocation TriggerLoc) override
Check global module index for missing imports.
void addDependencyCollector (std::shared_ptr< DependencyCollector > Listener)
void setExternalSemaSource (IntrusiveRefCntPtr< ExternalSemaSource > ESS)
InMemoryModuleCache & getModuleCache () const
static bool InitializeSourceManager (const FrontendInputFile &Input, DiagnosticsEngine &Diags, FileManager &FileMgr, SourceManager &SourceMgr)
InitializeSourceManager - Initialize the source manager to set InputFile as the main file.
Additional Inherited Members
Public Attributes inherited from clang::ModuleLoader
bool HadFatalFailure = false
Detailed Description
CompilerInstance - Helper class for managing a single instance of the Clang compiler.
The CompilerInstance serves two purposes: (1) It manages the various objects which are necessary to run the compiler, for example the preprocessor, the target information, and the AST context. (2) It provides utility routines for constructing and manipulating the common Clang objects.
The compiler instance generally owns the instance of all the objects that it manages. However, clients can still share objects by manually setting the object and retaking ownership prior to destroying the CompilerInstance.
The compiler instance is intended to simplify clients, but not to lock them in to the compiler instance for everything. When possible, utility functions come in two forms; a short form that reuses the CompilerInstance objects, and a long form that takes explicit instances of any required objects.
Definition at line 73 of file CompilerInstance.h.
Constructor & Destructor Documentation
CompilerInstance()
CompilerInstance::CompilerInstance (std::shared_ptr< PCHContainerOperations > PCHContainerOps = std::make_shared<PCHContainerOperations>(), InMemoryModuleCache * SharedModuleCache = nullptr) explicit
Definition at line 58 of file CompilerInstance.cpp.
~CompilerInstance()
CompilerInstance::~CompilerInstance () override
Definition at line 67 of file CompilerInstance.cpp.
Member Function Documentation
addDependencyCollector()
void clang::CompilerInstance::addDependencyCollector (std::shared_ptr< DependencyCollector > Listener) inline
Definition at line 809 of file CompilerInstance.h.
Referenced by createPreprocessor().
clearOutputFiles()
void CompilerInstance::clearOutputFiles (bool EraseFiles)
clearOutputFiles - Clear the output file list.
The underlying output streams must have been closed beforehand.
Parameters
EraseFiles - If true, attempt to erase the files from disk.
Definition at line 649 of file CompilerInstance.cpp.
References getDiagnostics(), and clang::DiagnosticsEngine::Report().
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::FrontendAction::EndSourceFile().
createASTContext()
void CompilerInstance::createASTContext ()
Create the AST context.
Definition at line 494 of file CompilerInstance.cpp.
References getAuxTarget(), clang::Preprocessor::getBuiltinInfo(), clang::Preprocessor::getIdentifierTable(), getLangOpts(), getPreprocessor(), clang::Preprocessor::getSelectorTable(), clang::Preprocessor::getSourceManager(), getTarget(), and setASTContext().
Referenced by clang::FrontendAction::BeginSourceFile(), and createASTReader().
createASTReader()
void CompilerInstance::createASTReader ()
Definition at line 1463 of file CompilerInstance.cpp.
References clang::FrontendOptions::AllowPCMWithCompilerErrors, createASTContext(), clang::PreprocessorOptions::DisablePCHOrModuleValidation, getASTConsumer(), getASTContext(), getFrontendOpts(), getHeaderSearchOpts(), getModuleCache(), getPCHContainerReader(), getPreprocessor(), getPreprocessorOpts(), getSema(), getSourceManager(), hasASTConsumer(), hasASTContext(), hasSema(), clang::HeaderSearchOptions::ModulesValidateSystemHeaders, pruneModuleCache(), clang::ASTContext::setASTMutationListener(), clang::ASTContext::setExternalSource(), clang::HeaderSearchOptions::Sysroot, and clang::HeaderSearchOptions::ValidateASTInputFilesContent.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::RewriteIncludesAction::BeginSourceFileAction(), loadGlobalModuleIndex(), loadModuleFile(), and makeModuleVisible().
createCodeCompletionConsumer() [1/2]
void CompilerInstance::createCodeCompletionConsumer ()
Create a code completion consumer using the invocation; note that this will cause the source manager to truncate the input source file at the completion point.
Definition at line 597 of file CompilerInstance.cpp.
References clang::FrontendOptions::CodeCompletionAt, clang::ParsedSourceLocation::Column, createCodeCompletionConsumer(), EnableCodeCompletion(), clang::ParsedSourceLocation::FileName, getFrontendOpts(), getPreprocessor(), clang::ParsedSourceLocation::Line, and setCodeCompletionConsumer().
Referenced by createCodeCompletionConsumer(), and clang::ASTFrontendAction::ExecuteAction().
createCodeCompletionConsumer() [2/2]
CodeCompleteConsumer * CompilerInstance::createCodeCompletionConsumer (Preprocessor & PP, StringRef Filename, unsigned Line, unsigned Column, const CodeCompleteOptions & Opts, raw_ostream & OS) static
Create a code completion consumer to print code completion results, at Filename, Line, and Column, to the given output stream OS.
Definition at line 623 of file CompilerInstance.cpp.
References EnableCodeCompletion(), and Filename.
createDefaultOutputFile()
std::unique_ptr< raw_pwrite_stream > CompilerInstance::createDefaultOutputFile (bool Binary = true, StringRef BaseInput = "", StringRef Extension = "", bool RemoveFileOnSignal = true, bool CreateMissingDirectories = false)
Create the default output file (from the invocation's options) and add it to the list of tracked output files.
The files created by this are usually removed on signal, and, depending on FrontendOptions, may also use a temporary file (that is, the data is written to a temporary file which will atomically replace the target output on success). If a client (like libclang) needs to disable RemoveFileOnSignal, temporary files will be forced on.
Returns
- Null on error.
Definition at line 685 of file CompilerInstance.cpp.
References createOutputFile(), getFrontendOpts(), and clang::FrontendOptions::OutputFile.
Referenced by clang::RewriteIncludesAction::BeginSourceFileAction(), clang::ASTPrintAction::CreateASTConsumer(), clang::HTMLPrintAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateOutputFile(), clang::PrintPreprocessedAction::ExecuteAction(), clang::RewriteMacrosAction::ExecuteAction(), clang::RewriteTestAction::ExecuteAction(), and GetOutputStream().
createDiagnostics() [1/2]
void CompilerInstance::createDiagnostics (DiagnosticConsumer * Client = nullptr, bool ShouldOwnClient = true)
Create the diagnostics engine using the invocation's diagnostic options and replace any existing one with it.
Note that this routine also replaces the diagnostic client, allocating one if one is not provided.
Parameters
Client If non-NULL, a diagnostic client that will be attached to (and, then, owned by) the DiagnosticsEngine inside this AST unit.
ShouldOwnClient If Client is non-NULL, specifies whether the diagnostic object should take ownership of the client.
Definition at line 272 of file CompilerInstance.cpp.
References createDiagnostics(), getCodeGenOpts(), and getDiagnosticOpts().
Referenced by createDiagnostics(), clang::createInvocationFromCommandLine(), and clang::tooling::FrontendActionFactory::runInvocation().
createDiagnostics() [2/2]
IntrusiveRefCntPtr< DiagnosticsEngine > CompilerInstance::createDiagnostics (DiagnosticOptions * Opts, DiagnosticConsumer * Client = nullptr, bool ShouldOwnClient = true, const CodeGenOptions * CodeGenOpts = nullptr) static
Create a DiagnosticsEngine object with a the TextDiagnosticPrinter.
If no diagnostic client is provided, this creates a DiagnosticConsumer that is owned by the returned diagnostic object, if using directly the caller is responsible for releasing the returned DiagnosticsEngine's client eventually.
Parameters
Opts - The diagnostic options; note that the created text diagnostic object contains a reference to these options.
Client If non-NULL, a diagnostic client that will be attached to (and, then, owned by) the returned DiagnosticsEngine object.
CodeGenOpts If non-NULL, the code gen options in use, which may be used by some diagnostics printers (for logging purposes only).
Returns
The new object on success, or null on failure.
Definition at line 279 of file CompilerInstance.cpp.
References clang::DiagnosticOptions::DiagnosticLogFile, clang::DiagnosticOptions::DiagnosticSerializationFile, clang::ProcessWarningOptions(), SetUpDiagnosticLog(), and SetupSerializedDiagnostics().
createFileManager()
FileManager * CompilerInstance::createFileManager (IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS = nullptr)
Create the file manager and replace any existing one with it.
Returns
The new file manager on success, or null on failure.
Definition at line 314 of file CompilerInstance.cpp.
References clang::createVFSFromCompilerInvocation(), getDiagnostics(), getFileSystemOpts(), and getInvocation().
Referenced by clang::FrontendAction::BeginSourceFile().
createFrontendTimer()
void CompilerInstance::createFrontendTimer ()
Create the frontend timer and replace any existing one with it.
Definition at line 614 of file CompilerInstance.cpp.
Referenced by ExecuteAction().
createModuleFromSource()
void CompilerInstance::createModuleFromSource (SourceLocation Loc, StringRef ModuleName, StringRef Source) override virtual
Attempt to create the given module from the specified source buffer.
Does not load the module or make any submodule visible; for that, use loadModule and makeModuleVisible.
Parameters
Loc The location at which to create the module.
ModuleName The name of the module to create.
Source The source of the module: a (preprocessed) module map.
Implements clang::ModuleLoader.
Definition at line 2019 of file CompilerInstance.cpp.
References clang::C, compileModuleImpl(), getDiagnostics(), getLanguageFromOptions(), clang::isAlphanumeric(), clang::InputKind::ModuleMap, and clang::DiagnosticsEngine::Report().
createNullOutputFile()
std::unique_ptr< raw_pwrite_stream > CompilerInstance::createNullOutputFile ()
Definition at line 707 of file CompilerInstance.cpp.
Referenced by GetOutputStream().
createOutputFile()
std::unique_ptr< raw_pwrite_stream > CompilerInstance::createOutputFile (StringRef OutputPath, bool Binary, bool RemoveFileOnSignal, bool UseTemporary, bool CreateMissingDirectories = false)
Create a new output file, optionally deriving the output path name, and add it to the list of tracked output files.
Returns
- Null on error.
Definition at line 712 of file CompilerInstance.cpp.
References getDiagnostics(), and clang::DiagnosticsEngine::Report().
Referenced by createDefaultOutputFile().
createPCHExternalASTSource() [1/2]
void CompilerInstance::createPCHExternalASTSource (StringRef Path, DisableValidationForModuleKind DisableValidation, bool AllowPCHWithCompilerErrors, void * DeserializationListener, bool OwnDeserializationListener)
Create an external AST source to read a PCH file and attach it to the AST context.
Definition at line 505 of file CompilerInstance.cpp.
References createPCHExternalASTSource(), getASTContext(), getFrontendOpts(), getHeaderSearchOpts(), getModuleCache(), getPCHContainerReader(), getPreprocessor(), getPreprocessorOpts(), clang::Preamble, and clang::PreprocessorOptions::PrecompiledPreambleBytes.
Referenced by clang::FrontendAction::BeginSourceFile(), and createPCHExternalASTSource().
createPCHExternalASTSource() [2/2]
IntrusiveRefCntPtr< ASTReader > CompilerInstance::createPCHExternalASTSource (StringRef Path, StringRef Sysroot, DisableValidationForModuleKind DisableValidation, bool AllowPCHWithCompilerErrors, Preprocessor & PP, InMemoryModuleCache & ModuleCache, ASTContext & Context, const PCHContainerReader & PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension > > Extensions, ArrayRef< std::shared_ptr< DependencyCollector > > DependencyCollectors, void * DeserializationListener, bool OwnDeserializationListener, bool Preamble, bool UseGlobalModuleIndex) static
Create an external AST source to read a PCH file.
Returns
- The new object on success, or null on failure.
Definition at line 519 of file CompilerInstance.cpp.
References clang::ASTReader::ARR_None, clang::ASTReader::ConfigurationMismatch, clang::ASTReader::Failure, clang::Preprocessor::getHeaderSearchInfo(), clang::HeaderSearch::getHeaderSearchOpts(), clang::ASTReader::HadErrors, clang::ASTReader::Missing, clang::serialization::MK_PCH, clang::serialization::MK_Preamble, clang::HeaderSearchOptions::ModulesValidateSystemHeaders, clang::ASTReader::OutOfDate, clang::Preamble, clang::ASTContext::setExternalSource(), clang::Preprocessor::setPredefines(), clang::ASTReader::Success, clang::HeaderSearchOptions::ValidateASTInputFilesContent, and clang::ASTReader::VersionMismatch.
createPreprocessor()
void CompilerInstance::createPreprocessor (TranslationUnitKind TUKind)
Create the preprocessor, using the invocation, file, and source managers, and replace any existing one with it.
Definition at line 389 of file CompilerInstance.cpp.
References addDependencyCollector(), clang::TargetInfo::adjust(), clang::ApplyHeaderSearchOptions(), clang::AttachDependencyGraphGen(), clang::AttachHeaderIncludeGen(), collectHeaderMaps(), collectIncludePCH(), collectVFSEntries(), clang::PreprocessorOptions::DetailedRecord, clang::DependencyOutputOptions::DOTOutputFile, getAuxTarget(), getDependencyOutputOpts(), getDiagnostics(), getFrontendOpts(), getHeaderSearchOpts(), getHeaderSearchOptsPtr(), getInvocation(), getLangOpts(), clang::CompilerInvocation::getModuleHash(), getPCHContainerReader(), getPreprocessorOpts(), getPreprocessorOutputOpts(), getSourceManager(), getSpecificModuleCachePath(), getTarget(), clang::DependencyOutputOptions::HeaderIncludeOutputFile, InitializeFileRemapping(), clang::InitializePreprocessor(), clang::DependencyOutputOptions::ModuleDependencyOutputDir, clang::None, clang::DependencyOutputOptions::OutputFile, clang::DependencyOutputOptions::ShowHeaderIncludes, and clang::DependencyOutputOptions::ShowIncludesDest.
Referenced by clang::FrontendAction::BeginSourceFile().
createSema()
void CompilerInstance::createSema (TranslationUnitKind TUKind, CodeCompleteConsumer * CompletionConsumer)
Create the Sema object to be used for parsing.
Definition at line 636 of file CompilerInstance.cpp.
References getASTConsumer(), getASTContext(), and getPreprocessor().
Referenced by clang::ASTFrontendAction::ExecuteAction().
createSourceManager()
void CompilerInstance::createSourceManager (FileManager & FileMgr)
Create the source manager and replace any existing one with it.
Definition at line 327 of file CompilerInstance.cpp.
References getDiagnostics().
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::tooling::FrontendActionFactory::runInvocation().
ExecuteAction()
bool CompilerInstance::ExecuteAction (FrontendAction & Act)
ExecuteAction - Execute the provided action against the compiler's CompilerInvocation object.
This function makes the following assumptions:
The invocation options should be initialized. This function does not handle the '-help' or '-version' options, clients should handle those directly.
The diagnostics engine should have already been created by the client.
No other CompilerInstance state should have been initialized (this is an unchecked error).
Clients should have initialized any LLVM target features that may be required.
Clients should eventually call llvm_shutdown() upon the completion of this routine to ensure that any managed objects are properly destroyed.
Note that this routine may write output to 'stderr'.
Parameters
Act - The action to execute.
Returns
- True on success.
Definition at line 866 of file CompilerInstance.cpp.
References clang::TargetInfo::adjust(), clang::TargetInfo::adjustTargetOptions(), clang::FrontendOptions::AuxTargetCPU, clang::FrontendOptions::AuxTargetFeatures, clang::FrontendAction::BeginSourceFile(), clang::SourceManager::clearIDTables(), clang::TargetOptions::CPU, createFrontendTimer(), clang::TargetInfo::CreateTargetInfo(), clang::CUDA, clang::FrontendAction::EndSourceFile(), clang::FrontendAction::Execute(), clang::DiagnosticConsumer::finish(), clang::LangOptions::FPE_Ignore, getAuxTarget(), clang::DiagnosticsEngine::getClient(), getCodeGenOpts(), getDiagnosticOpts(), getDiagnostics(), getFileManager(), getFrontendOpts(), getHeaderSearchOpts(), getInvocation(), getLangOpts(), clang::DiagnosticConsumer::getNumErrors(), clang::DiagnosticConsumer::getNumWarnings(), getSourceManager(), getTarget(), getTargetOpts(), clang::TargetInfo::getTriple(), getVerboseOutputStream(), hasDiagnostics(), hasFileManager(), hasSourceManager(), hasTarget(), clang::FrontendAction::isModelParsingAction(), clang::TargetInfo::noSignedCharForObjCBool(), clang::noteBottomOfStack(), clang::FrontendAction::PrepareToExecute(), clang::FileManager::PrintStats(), clang::DiagnosticsEngine::Report(), clang::frontend::RewriteObjC, setAuxTarget(), clang::TargetInfo::setAuxTarget(), setTarget(), and clang::FrontendOptions::StatsFile.
Referenced by clang::ExecuteCompilerInvocation(), and clang::tooling::FrontendActionFactory::runInvocation().
getAnalyzerOpts()
AnalyzerOptionsRef clang::CompilerInstance::getAnalyzerOpts () inline
Definition at line 249 of file CompilerInstance.h.
Referenced by clang::ento::CreateAnalysisConsumer(), and clang::ExecuteCompilerInvocation().
getASTConsumer()
ASTConsumer & clang::CompilerInstance::getASTConsumer () const inline
Definition at line 481 of file CompilerInstance.h.
Referenced by createASTReader(), createSema(), clang::ASTMergeAction::ExecuteAction(), setASTConsumer(), and setASTContext().
getASTContext()
ASTContext & clang::CompilerInstance::getASTContext () const inline
Definition at line 458 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), createASTReader(), createASTReader(), createPCHExternalASTSource(), createSema(), clang::ASTMergeAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), setASTConsumer(), and setASTContext().
getASTReader()
IntrusiveRefCntPtr< ASTReader > CompilerInstance::getASTReader () const
Definition at line 142 of file CompilerInstance.cpp.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::RewriteIncludesAction::BeginSourceFileAction(), compileModuleAndReadAST(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getAuxTarget()
TargetInfo * clang::CompilerInstance::getAuxTarget () const inline
Definition at line 380 of file CompilerInstance.h.
Referenced by createASTContext(), createPreprocessor(), and ExecuteAction().
getCodeCompletionConsumer()
CodeCompleteConsumer & clang::CompilerInstance::getCodeCompletionConsumer () const inline
Definition at line 556 of file CompilerInstance.h.
Referenced by clang::ASTFrontendAction::ExecuteAction().
getCodeGenOpts() [1/2]
CodeGenOptions & clang::CompilerInstance::getCodeGenOpts () inline
Definition at line 253 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::CodeGenAction::CreateASTConsumer(), createDiagnostics(), clang::CodeGenAction::ExecuteAction(), and ExecuteAction().
getCodeGenOpts() [2/2]
const CodeGenOptions & clang::CompilerInstance::getCodeGenOpts () const inline
Definition at line 256 of file CompilerInstance.h.
getDependencyOutputOpts() [1/2]
DependencyOutputOptions & clang::CompilerInstance::getDependencyOutputOpts () inline
Definition at line 260 of file CompilerInstance.h.
Referenced by createPreprocessor().
getDependencyOutputOpts() [2/2]
const DependencyOutputOptions & clang::CompilerInstance::getDependencyOutputOpts () const inline
Definition at line 263 of file CompilerInstance.h.
getDiagnosticClient()
DiagnosticConsumer & clang::CompilerInstance::getDiagnosticClient () const inline
Definition at line 341 of file CompilerInstance.h.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::EndSourceFile(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getDiagnosticOpts() [1/2]
DiagnosticOptions & clang::CompilerInstance::getDiagnosticOpts () inline
Definition at line 267 of file CompilerInstance.h.
Referenced by clang::createChainedIncludesSource(), createDiagnostics(), clang::ASTMergeAction::ExecuteAction(), ExecuteAction(), and clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction().
getDiagnosticOpts() [2/2]
const DiagnosticOptions & clang::CompilerInstance::getDiagnosticOpts () const inline
Definition at line 270 of file CompilerInstance.h.
getDiagnostics()
DiagnosticsEngine & clang::CompilerInstance::getDiagnostics () const inline
Get the current diagnostics engine.
Definition at line 333 of file CompilerInstance.h.
Referenced by clang::arcmt::CheckAction::BeginInvocation(), clang::arcmt::MigrateAction::BeginInvocation(), clang::arcmt::MigrateSourceAction::BeginInvocation(), clang::arcmt::ModifyAction::BeginInvocation(), clang::arcmt::ObjCMigrateAction::BeginInvocation(), clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FixItAction::BeginSourceFileAction(), clearOutputFiles(), compileModuleAndReadAST(), clang::GeneratePCHAction::ComputeASTConsumerArguments(), clang::CodeGenAction::CreateASTConsumer(), createFileManager(), clang::CreateFrontendBaseAction(), createModuleFromSource(), createOutputFile(), createPreprocessor(), createSourceManager(), clang::ASTMergeAction::ExecuteAction(), clang::CodeGenAction::ExecuteAction(), ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), clang::ExecuteCompilerInvocation(), getInputBufferForModule(), InitializeSourceManager(), loadModule(), loadModuleFile(), prepareToBuildModule(), and clang::FrontendAction::shouldEraseOutputFiles().
getFileManager()
FileManager & clang::CompilerInstance::getFileManager () const inline
Return the current file manager to the caller.
Definition at line 398 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), collectIncludePCH(), compileModule(), clang::arcmt::MigrateSourceAction::CreateASTConsumer(), clang::arcmt::ObjCMigrateAction::CreateASTConsumer(), clang::CodeGenAction::CreateASTConsumer(), clang::FrontendAction::Execute(), clang::ASTMergeAction::ExecuteAction(), ExecuteAction(), clang::DumpModuleInfoAction::ExecuteAction(), clang::PrintPreambleAction::ExecuteAction(), getInputBufferForModule(), getVirtualFileSystem(), InitializeSourceManager(), loadGlobalModuleIndex(), prepareToBuildModule(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getFileSystemOpts() [1/2]
FileSystemOptions & clang::CompilerInstance::getFileSystemOpts () inline
Definition at line 274 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), createFileManager(), and clang::ASTMergeAction::ExecuteAction().
getFileSystemOpts() [2/2]
const FileSystemOptions & clang::CompilerInstance::getFileSystemOpts () const inline
Definition at line 277 of file CompilerInstance.h.
getFrontendOpts() [1/2]
FrontendOptions & clang::CompilerInstance::getFrontendOpts () inline
Definition at line 281 of file CompilerInstance.h.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FixItAction::BeginSourceFileAction(), compileModule(), clang::GeneratePCHAction::ComputeASTConsumerArguments(), clang::ento::CreateAnalysisConsumer(), clang::arcmt::MigrateSourceAction::CreateASTConsumer(), clang::ASTDumpAction::CreateASTConsumer(), clang::ASTPrintAction::CreateASTConsumer(), clang::GenerateModuleAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), createASTReader(), clang::createChainedIncludesSource(), createCodeCompletionConsumer(), createDefaultOutputFile(), clang::CreateFrontendAction(), clang::CreateFrontendBaseAction(), clang::GeneratePCHAction::CreateOutputFile(), createPCHExternalASTSource(), createPreprocessor(), clang::FrontendAction::EndSourceFile(), clang::ASTFrontendAction::ExecuteAction(), ExecuteAction(), clang::DumpModuleInfoAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), clang::ExecuteCompilerInvocation(), prepareToBuildModule(), shouldBuildGlobalModuleIndex(), and clang::GenerateModuleAction::shouldEraseOutputFiles().
getFrontendOpts() [2/2]
const FrontendOptions & clang::CompilerInstance::getFrontendOpts () const inline
Definition at line 284 of file CompilerInstance.h.
getFrontendTimer()
llvm::Timer & clang::CompilerInstance::getFrontendTimer () const inline
Definition at line 572 of file CompilerInstance.h.
Referenced by clang::FrontendAction::Execute().
getHeaderSearchOpts() [1/2]
HeaderSearchOptions & clang::CompilerInstance::getHeaderSearchOpts () inline
Definition at line 288 of file CompilerInstance.h.
Referenced by clang::DumpModuleInfoAction::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), collectVFSEntries(), clang::GeneratePCHAction::ComputeASTConsumerArguments(), clang::CodeGenAction::CreateASTConsumer(), createASTReader(), createPCHExternalASTSource(), createPreprocessor(), clang::CodeGenAction::ExecuteAction(), ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), getPCHContainerReader(), getPCHContainerWriter(), and getSpecificModuleCachePath().
getHeaderSearchOpts() [2/2]
const HeaderSearchOptions & clang::CompilerInstance::getHeaderSearchOpts () const inline
Definition at line 291 of file CompilerInstance.h.
getHeaderSearchOptsPtr()
std::shared_ptr< HeaderSearchOptions > clang::CompilerInstance::getHeaderSearchOptsPtr () const inline
Definition at line 294 of file CompilerInstance.h.
Referenced by createPreprocessor().
getInvocation()
CompilerInvocation & clang::CompilerInstance::getInvocation () inline
Definition at line 228 of file CompilerInstance.h.
Referenced by clang::arcmt::CheckAction::BeginInvocation(), clang::arcmt::MigrateAction::BeginInvocation(), clang::arcmt::ModifyAction::BeginInvocation(), clang::createChainedIncludesSource(), createFileManager(), createPreprocessor(), ExecuteAction(), clang::tooling::dependencies::ModuleDepCollectorPP::FileChanged(), getSpecificModuleCachePath(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getLangOpts() [1/2]
LangOptions & clang::CompilerInstance::getLangOpts () inline
Definition at line 298 of file CompilerInstance.h.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FixItAction::BeginSourceFileAction(), clang::GeneratePCHAction::BeginSourceFileAction(), compileModule(), clang::CodeGenAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), createASTContext(), createPreprocessor(), clang::FrontendAction::EndSourceFile(), clang::CodeGenAction::ExecuteAction(), ExecuteAction(), clang::PrintPreambleAction::ExecuteAction(), clang::FrontendAction::getCurrentModule(), getInputBufferForModule(), loadModule(), prepareToBuildModule(), and ReadOriginalFileName().
getLangOpts() [2/2]
const LangOptions & clang::CompilerInstance::getLangOpts () const inline
Definition at line 301 of file CompilerInstance.h.
getModuleCache()
InMemoryModuleCache & clang::CompilerInstance::getModuleCache () const inline
Definition at line 815 of file CompilerInstance.h.
Referenced by clang::GenerateModuleAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), createASTReader(), createASTReader(), createPCHExternalASTSource(), clang::VerifyPCHAction::ExecuteAction(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getModuleDepCollector()
std::shared_ptr< ModuleDependencyCollector > CompilerInstance::getModuleDepCollector () const
Definition at line 152 of file CompilerInstance.cpp.
getPCHContainerOperations()
std::shared_ptr< PCHContainerOperations > clang::CompilerInstance::getPCHContainerOperations () const inline
Definition at line 518 of file CompilerInstance.h.
Referenced by clang::arcmt::CheckAction::BeginInvocation(), clang::arcmt::MigrateAction::BeginInvocation(), clang::arcmt::ModifyAction::BeginInvocation(), clang::createChainedIncludesSource(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getPCHContainerReader()
const PCHContainerReader & clang::CompilerInstance::getPCHContainerReader () const inline
Return the appropriate PCHContainerReader depending on the current CodeGenOptions.
Definition at line 538 of file CompilerInstance.h.
References getHeaderSearchOpts(), and clang::HeaderSearchOptions::ModuleFormat.
Referenced by clang::FrontendAction::BeginSourceFile(), collectIncludePCH(), createASTReader(), createASTReader(), createPCHExternalASTSource(), createPreprocessor(), clang::FrontendAction::Execute(), clang::ASTMergeAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), and loadGlobalModuleIndex().
getPCHContainerWriter()
const PCHContainerWriter & clang::CompilerInstance::getPCHContainerWriter () const inline
Return the appropriate PCHContainerWriter depending on the current CodeGenOptions.
Definition at line 524 of file CompilerInstance.h.
References getHeaderSearchOpts(), and clang::HeaderSearchOptions::ModuleFormat.
Referenced by clang::GenerateModuleAction::CreateASTConsumer(), and clang::GeneratePCHAction::CreateASTConsumer().
getPreprocessor()
Preprocessor & clang::CompilerInstance::getPreprocessor () const inline
Return the current preprocessor.
Definition at line 438 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), collectIncludePCH(), compileModule(), clang::ento::CreateAnalysisConsumer(), clang::arcmt::MigrateSourceAction::CreateASTConsumer(), clang::arcmt::ObjCMigrateAction::CreateASTConsumer(), clang::CodeGenAction::CreateASTConsumer(), clang::GenerateModuleAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), clang::HTMLPrintAction::CreateASTConsumer(), createASTContext(), createASTReader(), createASTReader(), createCodeCompletionConsumer(), createPCHExternalASTSource(), createSema(), clang::FrontendAction::EndSourceFile(), clang::FrontendAction::Execute(), clang::DumpModuleInfoAction::ExecuteAction(), clang::DumpRawTokensAction::ExecuteAction(), clang::DumpTokensAction::ExecuteAction(), clang::PreprocessOnlyAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), clang::PrintPreprocessedAction::ExecuteAction(), clang::RewriteIncludesAction::ExecuteAction(), clang::RewriteMacrosAction::ExecuteAction(), clang::RewriteTestAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), clang::FrontendAction::getCurrentModule(), getInputBufferForModule(), loadGlobalModuleIndex(), loadModule(), loadModuleFile(), loadModuleMapForModuleBuild(), prepareToBuildModule(), and ReadOriginalFileName().
getPreprocessorOpts() [1/2]
PreprocessorOptions & clang::CompilerInstance::getPreprocessorOpts () inline
Definition at line 305 of file CompilerInstance.h.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), collectIncludePCH(), clang::CodeGenAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), createASTReader(), clang::createChainedIncludesSource(), createPCHExternalASTSource(), createPreprocessor(), clang::CodeGenAction::ExecuteAction(), and clang::VerifyPCHAction::ExecuteAction().
getPreprocessorOpts() [2/2]
const PreprocessorOptions & clang::CompilerInstance::getPreprocessorOpts () const inline
Definition at line 308 of file CompilerInstance.h.
getPreprocessorOutputOpts() [1/2]
PreprocessorOutputOptions & clang::CompilerInstance::getPreprocessorOutputOpts () inline
Definition at line 312 of file CompilerInstance.h.
Referenced by clang::RewriteIncludesAction::BeginSourceFileAction(), clang::CreateFrontendBaseAction(), createPreprocessor(), clang::PrintPreprocessedAction::ExecuteAction(), and clang::RewriteIncludesAction::ExecuteAction().
getPreprocessorOutputOpts() [2/2]
const PreprocessorOutputOptions & clang::CompilerInstance::getPreprocessorOutputOpts () const inline
Definition at line 315 of file CompilerInstance.h.
getPreprocessorPtr()
std::shared_ptr< Preprocessor > clang::CompilerInstance::getPreprocessorPtr () inline
Definition at line 443 of file CompilerInstance.h.
getSema()
Sema & clang::CompilerInstance::getSema () const inline
Definition at line 499 of file CompilerInstance.h.
Referenced by createASTReader(), clang::ASTFrontendAction::ExecuteAction(), and clang::TemplightDumpAction::ExecuteAction().
getSourceManager()
SourceManager & clang::CompilerInstance::getSourceManager () const inline
Return the current source manager.
Definition at line 418 of file CompilerInstance.h.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FixItAction::BeginSourceFileAction(), clang::arcmt::MigrateSourceAction::CreateASTConsumer(), clang::arcmt::ObjCMigrateAction::CreateASTConsumer(), createASTReader(), createPreprocessor(), clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile(), clang::FrontendAction::EndSourceFile(), clang::CodeGenAction::ExecuteAction(), ExecuteAction(), clang::PrintPreprocessedAction::ExecuteAction(), clang::tooling::dependencies::ModuleDepCollectorPP::FileChanged(), InitializeSourceManager(), loadModuleMapForModuleBuild(), prepareToBuildModule(), and ReadOriginalFileName().
getSpecificModuleCachePath() [1/2]
std::string clang::CompilerInstance::getSpecificModuleCachePath () inline
Definition at line 644 of file CompilerInstance.h.
References getInvocation(), and getSpecificModuleCachePath().
Referenced by createPreprocessor(), and getSpecificModuleCachePath().
getSpecificModuleCachePath() [2/2]
std::string CompilerInstance::getSpecificModuleCachePath (StringRef ModuleHash)
Definition at line 484 of file CompilerInstance.cpp.
References getHeaderSearchOpts().
Referenced by clang::FrontendAction::BeginSourceFile().
getTarget()
TargetInfo & clang::CompilerInstance::getTarget () const inline
Definition at line 368 of file CompilerInstance.h.
Referenced by createASTContext(), createPreprocessor(), clang::CodeGenAction::ExecuteAction(), ExecuteAction(), loadModule(), and prepareToBuildModule().
getTargetOpts() [1/2]
TargetOptions & clang::CompilerInstance::getTargetOpts () inline
Definition at line 319 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::CodeGenAction::CreateASTConsumer(), clang::CodeGenAction::ExecuteAction(), and ExecuteAction().
getTargetOpts() [2/2]
const TargetOptions & clang::CompilerInstance::getTargetOpts () const inline
Definition at line 322 of file CompilerInstance.h.
getVerboseOutputStream()
raw_ostream & clang::CompilerInstance::getVerboseOutputStream () inline
Get the current stream for verbose output.
Definition at line 358 of file CompilerInstance.h.
Referenced by ExecuteAction().
getVirtualFileSystem()
llvm::vfs::FileSystem & CompilerInstance::getVirtualFileSystem () const
Definition at line 100 of file CompilerInstance.cpp.
References getFileManager(), and clang::FileManager::getVirtualFileSystem().
hadModuleLoaderFatalFailure()
bool clang::CompilerInstance::hadModuleLoaderFatalFailure () const inline
Definition at line 801 of file CompilerInstance.h.
References clang::ModuleLoader::HadFatalFailure.
hasASTConsumer()
bool clang::CompilerInstance::hasASTConsumer () const inline
Definition at line 479 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), and createASTReader().
hasASTContext()
bool clang::CompilerInstance::hasASTContext () const inline
Definition at line 456 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), and createASTReader().
hasCodeCompletionConsumer()
bool clang::CompilerInstance::hasCodeCompletionConsumer () const inline
Definition at line 554 of file CompilerInstance.h.
Referenced by clang::ASTFrontendAction::ExecuteAction().
hasDiagnostics()
bool clang::CompilerInstance::hasDiagnostics () const inline
Definition at line 330 of file CompilerInstance.h.
Referenced by ExecuteAction(), and clang::tooling::FrontendActionFactory::runInvocation().
hasFileManager()
bool clang::CompilerInstance::hasFileManager () const inline
Definition at line 395 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::Execute(), ExecuteAction(), and loadGlobalModuleIndex().
hasFrontendTimer()
bool clang::CompilerInstance::hasFrontendTimer () const inline
Definition at line 570 of file CompilerInstance.h.
Referenced by clang::FrontendAction::Execute().
hasInvocation()
bool clang::CompilerInstance::hasInvocation () const inline
Definition at line 226 of file CompilerInstance.h.
hasPreprocessor()
bool clang::CompilerInstance::hasPreprocessor () const inline
Definition at line 435 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile(), clang::FrontendAction::Execute(), clang::ASTFrontendAction::ExecuteAction(), and loadGlobalModuleIndex().
hasSema()
bool clang::CompilerInstance::hasSema () const inline
Definition at line 497 of file CompilerInstance.h.
Referenced by createASTReader(), and clang::ASTFrontendAction::ExecuteAction().
hasSourceManager()
bool clang::CompilerInstance::hasSourceManager () const inline
Definition at line 415 of file CompilerInstance.h.
Referenced by clang::FrontendAction::BeginSourceFile(), and ExecuteAction().
hasTarget()
bool clang::CompilerInstance::hasTarget () const inline
Definition at line 366 of file CompilerInstance.h.
Referenced by ExecuteAction().
InitializeSourceManager() [1/2]
bool CompilerInstance::InitializeSourceManager (const FrontendInputFile & Input)
InitializeSourceManager - Initialize the source manager to set InputFile as the main file.
Returns
True on success.
Definition at line 817 of file CompilerInstance.cpp.
References getDiagnostics(), getFileManager(), getSourceManager(), and InitializeSourceManager().
Referenced by clang::FrontendAction::BeginSourceFile(), and InitializeSourceManager().
InitializeSourceManager() [2/2]
bool CompilerInstance::InitializeSourceManager (const FrontendInputFile & Input, DiagnosticsEngine & Diags, FileManager & FileMgr, SourceManager & SourceMgr) static
InitializeSourceManager - Initialize the source manager to set InputFile as the main file.
Returns
True on success.
Definition at line 823 of file CompilerInstance.cpp.
References clang::SrcMgr::C_System, clang::SrcMgr::C_System_ModuleMap, clang::SrcMgr::C_User, clang::SrcMgr::C_User_ModuleMap, clang::FrontendInputFile::getBuffer(), clang::FrontendInputFile::getFile(), clang::FileManager::getFileRef(), clang::InputKind::getFormat(), clang::FrontendInputFile::getKind(), clang::FileManager::getSTDIN(), clang::FrontendInputFile::isBuffer(), clang::FrontendInputFile::isSystem(), clang::InputKind::ModuleMap, and clang::DiagnosticsEngine::Report().
loadGlobalModuleIndex()
GlobalModuleIndex * CompilerInstance::loadGlobalModuleIndex (SourceLocation TriggerLoc) override virtual
Load, create, or return global module.
This function returns an existing global module index, if one had already been loaded or created, or loads one if it exists, or creates one if it doesn't exist. Also, importantly, if the index doesn't cover all the modules in the module map, it will be update to do so here, because of its use in searching for needed module imports and associated fixit messages.
Parameters
TriggerLoc The location for what triggered the load.
Returns
Returns null if load failed.
Implements clang::ModuleLoader.
Definition at line 2083 of file CompilerInstance.cpp.
References clang::ModuleLoader::buildingModule(), createASTReader(), clang::Module::DefinitionLoc, clang::Module::getASTFile(), getFileManager(), clang::Preprocessor::getHeaderSearchInfo(), clang::HeaderSearch::getModuleMap(), getPCHContainerReader(), getPreprocessor(), hasFileManager(), hasPreprocessor(), clang::Module::Hidden, loadModule(), clang::ModuleMap::module_begin(), clang::ModuleMap::module_end(), clang::Module::Name, shouldBuildGlobalModuleIndex(), and clang::GlobalModuleIndex::writeIndex().
Referenced by lookupMissingImports().
loadModule()
ModuleLoadResult CompilerInstance::loadModule (SourceLocation ImportLoc, ModuleIdPath Path, Module::NameVisibilityKind Visibility, bool IsInclusionDirective) override virtual
Attempt to load the given module.
This routine attempts to load the module described by the given parameters. If there is a module cache, this may implicitly compile the module before loading it.
Parameters
ImportLoc The location of the 'import' keyword.
Path The identifiers (and their locations) of the module "path", e.g., "std.vector" would be split into "std" and "vector".
Visibility The visibility provided for the names in the loaded module.
IsInclusionDirective Indicates that this module is being loaded implicitly, due to the presence of an inclusion directive. Otherwise, it is being loaded due to an import declaration.
Returns
If successful, returns the loaded module. Otherwise, returns NULL to indicate that the module could not be loaded.
FIXME: perhaps we should (a) look for a module using the module name
Implements clang::ModuleLoader.
Definition at line 1824 of file CompilerInstance.cpp.
References clang::ModuleMap::cacheModuleLoad(), checkConfigMacro(), clang::Preprocessor::checkModuleIsAvailable(), clang::Module::ConfigMacros, clang::FixItHint::CreateReplacement(), clang::Module::findSubmodule(), clang::ModuleMap::getCachedModuleLoad(), getDiagnostics(), clang::Module::getFullModuleName(), clang::Preprocessor::getHeaderSearchInfo(), getLangOpts(), clang::HeaderSearch::getModuleMap(), getPreprocessor(), getTarget(), clang::Module::getTopLevelModule(), clang::Module::IsFromModuleFile, clang::SourceLocation::isValid(), loadModule(), clang::ModuleLoadResult::MissingExpected, clang::Module, N, clang::Module::Name, clang::DiagnosticsEngine::Report(), clang::ModuleMap::resolveLinkAsDependencies(), clang::Result, clang::Module::submodule_begin(), and clang::Module::submodule_end().
Referenced by loadGlobalModuleIndex(), and loadModule().
loadModuleFile()
bool CompilerInstance::loadModuleFile (StringRef FileName)
Definition at line 1514 of file CompilerInstance.cpp.
References clang::ASTReader::ARR_ConfigurationMismatch, clang::ModuleMap::cacheModuleLoad(), clang::ASTReader::ConfigurationMismatch, createASTReader(), clang::ModuleMap::findModule(), clang::DiagnosticsEngine::getDiagnosticLevel(), getDiagnostics(), clang::Preprocessor::getHeaderSearchInfo(), clang::Preprocessor::getIdentifierInfo(), clang::HeaderSearch::getModuleMap(), getPreprocessor(), clang::serialization::MK_ExplicitModule, clang::DiagnosticsEngine::Report(), clang::ASTReader::Success, and clang::DiagnosticsEngine::Warning.
Referenced by clang::FrontendAction::BeginSourceFile().
lookupMissingImports()
bool CompilerInstance::lookupMissingImports (StringRef Name, SourceLocation TriggerLoc) override virtual
Check global module index for missing imports.
Parameters
Name The symbol name to look for.
TriggerLoc The location for what triggered the load.
Returns
Returns true if any modules with that symbol found.
Implements clang::ModuleLoader.
Definition at line 2153 of file CompilerInstance.cpp.
References clang::ModuleLoader::buildingModule(), loadGlobalModuleIndex(), and clang::GlobalModuleIndex::lookupIdentifier().
makeModuleVisible()
void CompilerInstance::makeModuleVisible (Module * Mod, Module::NameVisibilityKind Visibility, SourceLocation ImportLoc) override virtual
Make the given module visible.
Implements clang::ModuleLoader.
Definition at line 2072 of file CompilerInstance.cpp.
References createASTReader().
resetAndLeakASTContext()
void clang::CompilerInstance::resetAndLeakASTContext () inline
Definition at line 463 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile().
resetAndLeakFileManager()
void clang::CompilerInstance::resetAndLeakFileManager () inline
Definition at line 403 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile().
resetAndLeakPreprocessor()
void clang::CompilerInstance::resetAndLeakPreprocessor () inline
Definition at line 445 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile().
resetAndLeakSema()
void CompilerInstance::resetAndLeakSema ()
Definition at line 2176 of file CompilerInstance.cpp.
References takeSema().
Referenced by clang::FrontendAction::EndSourceFile().
resetAndLeakSourceManager()
void clang::CompilerInstance::resetAndLeakSourceManager () inline
Definition at line 423 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile().
setASTConsumer()
void CompilerInstance::setASTConsumer (std::unique_ptr< ASTConsumer > Value)
setASTConsumer - Replace the current AST consumer; the compiler instance takes ownership of Value.
Definition at line 127 of file CompilerInstance.cpp.
References getASTConsumer(), getASTContext(), and clang::ASTConsumer::Initialize().
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::FrontendAction::EndSourceFile().
setASTContext()
void CompilerInstance::setASTContext (ASTContext * Value)
setASTContext - Replace the current AST context.
Definition at line 116 of file CompilerInstance.cpp.
References getASTConsumer(), getASTContext(), and clang::ASTConsumer::Initialize().
Referenced by clang::FrontendAction::BeginSourceFile(), createASTContext(), and clang::FrontendAction::EndSourceFile().
setASTReader()
void CompilerInstance::setASTReader (IntrusiveRefCntPtr< ASTReader > Reader)
Definition at line 145 of file CompilerInstance.cpp.
Referenced by clang::FrontendAction::BeginSourceFile().
setAuxTarget()
void CompilerInstance::setAuxTarget (TargetInfo * Value)
Replace the current AuxTarget.
Definition at line 98 of file CompilerInstance.cpp.
Referenced by ExecuteAction().
setBuildGlobalModuleIndex()
void clang::CompilerInstance::setBuildGlobalModuleIndex (bool Build) inline
Set the flag indicating whether we should (re)build the global module index.
Definition at line 241 of file CompilerInstance.h.
Referenced by compileModule().
setCodeCompletionConsumer()
void CompilerInstance::setCodeCompletionConsumer (CodeCompleteConsumer * Value)
setCodeCompletionConsumer - Replace the current code completion consumer; the compiler instance takes ownership of Value.
Definition at line 134 of file CompilerInstance.cpp.
Referenced by createCodeCompletionConsumer().
setDiagnostics()
void CompilerInstance::setDiagnostics (DiagnosticsEngine * Value)
setDiagnostics - Replace the current diagnostics engine.
Definition at line 83 of file CompilerInstance.cpp.
setExternalSemaSource()
void CompilerInstance::setExternalSemaSource (IntrusiveRefCntPtr< ExternalSemaSource > ESS)
Definition at line 2178 of file CompilerInstance.cpp.
setFileManager()
void CompilerInstance::setFileManager (FileManager * Value)
Replace the current file manager and virtual file system.
Definition at line 104 of file CompilerInstance.cpp.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::EndSourceFile(), and clang::tooling::FrontendActionFactory::runInvocation().
setInvocation()
void CompilerInstance::setInvocation (std::shared_ptr< CompilerInvocation > Value)
setInvocation - Replace the current invocation.
Definition at line 71 of file CompilerInstance.cpp.
Referenced by clang::tooling::FrontendActionFactory::runInvocation().
setModuleDepCollector()
void CompilerInstance::setModuleDepCollector (std::shared_ptr< ModuleDependencyCollector > Collector)
Definition at line 156 of file CompilerInstance.cpp.
setOutputStream()
void clang::CompilerInstance::setOutputStream (std::unique_ptr< llvm::raw_pwrite_stream > OutStream) inline
}
Definition at line 761 of file CompilerInstance.h.
setPreprocessor()
void CompilerInstance::setPreprocessor (std::shared_ptr< Preprocessor > Value)
Replace the current preprocessor.
Definition at line 112 of file CompilerInstance.cpp.
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::FrontendAction::EndSourceFile().
setSema()
void CompilerInstance::setSema (Sema * S)
Replace the current Sema; the compiler instance takes ownership of S.
Definition at line 123 of file CompilerInstance.cpp.
Referenced by clang::FrontendAction::EndSourceFile().
setSourceManager()
void CompilerInstance::setSourceManager (SourceManager * Value)
setSourceManager - Replace the current source manager.
Definition at line 108 of file CompilerInstance.cpp.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::FrontendAction::BeginSourceFile(), and clang::FrontendAction::EndSourceFile().
setTarget()
void CompilerInstance::setTarget (TargetInfo * Value)
Replace the current Target.
Definition at line 97 of file CompilerInstance.cpp.
Referenced by ExecuteAction().
setVerboseOutputStream() [1/2]
void CompilerInstance::setVerboseOutputStream (raw_ostream & Value)
Replace the current stream for verbose output.
Definition at line 87 of file CompilerInstance.cpp.
setVerboseOutputStream() [2/2]
void CompilerInstance::setVerboseOutputStream (std::unique_ptr< raw_ostream > Value)
Replace the current stream for verbose output.
Definition at line 92 of file CompilerInstance.cpp.
shouldBuildGlobalModuleIndex()
bool CompilerInstance::shouldBuildGlobalModuleIndex () const
Indicates whether we should (re)build the global module index.
Definition at line 76 of file CompilerInstance.cpp.
References getFrontendOpts().
Referenced by clang::FrontendAction::Execute(), and loadGlobalModuleIndex().
takeASTConsumer()
std::unique_ptr< ASTConsumer > clang::CompilerInstance::takeASTConsumer () inline
takeASTConsumer - Remove the current AST consumer and give ownership to the caller.
Definition at line 488 of file CompilerInstance.h.
Referenced by clang::FrontendAction::EndSourceFile().
takeOutputStream()
std::unique_ptr< llvm::raw_pwrite_stream > clang::CompilerInstance::takeOutputStream () inline
Definition at line 765 of file CompilerInstance.h.
Referenced by clang::CodeGenAction::CreateASTConsumer().
takeSema()
std::unique_ptr< Sema > CompilerInstance::takeSema ()
Definition at line 138 of file CompilerInstance.cpp.
Referenced by resetAndLeakSema().
The documentation for this class was generated from the following files:
include/clang/Frontend/CompilerInstance.h
lib/Frontend/CompilerInstance.cpp