clang: clang::Attr Class Reference
clang::Attr Class Reference
Attr - This represents one attribute.
#include "clang/AST/Attr.h"
Public Member Functions
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Protected Member Functions
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Additional Inherited Members
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Attr - This represents one attribute.
Definition at line 46 of file Attr.h.
Constructor & Destructor Documentation
Attr()
clang::Attr::Attr (ASTContext & Context, const AttributeCommonInfo & CommonInfo, attr::Kind AK, bool IsLateParsed) inline protected
Definition at line 79 of file Attr.h.
Referenced by clang::OMPDeclareTargetDeclAttr::getDeviceType(), clang::OMPDeclareTargetDeclAttr::getLocation(), and clang::OMPDeclareTargetDeclAttr::isDeclareTargetDeclaration().
Member Function Documentation
clone()
Attr * clang::Attr::clone (ASTContext & C) const
Referenced by clang::Sema::checkClassLevelDLLAttribute(), getImplicitCodeSegAttrFromClass(), clang::ASTImporter::Import(), InjectAnonymousStructOrUnionMembers(), mergeDeclAttribute(), and clang::Sema::propagateDLLAttrToBaseClassTemplate().
getKind()
attr::Kind clang::Attr::getKind () const inline
Definition at line 86 of file Attr.h.
Referenced by clang::ASTRecordWriter::AddAttr(), clang::AMDGPUWavesPerEUAttr::AMDGPUWavesPerEUAttr(), attrToRetainOwnershipKind(), clang::Sema::checkClassLevelDLLAttribute(), checkNewAttributesAfterDef(), clang::InheritableParamAttr::classof(), clang::ParameterABIAttr::classof(), clang::StmtAttr::classof(), clang::TypeAttr::classof(), DeclHasAttr(), getCCTypeAttr(), HandleAddressSpaceTypeAttribute(), handleMSPointerTypeQualifierAttr(), clang::ASTImporter::Import(), ReferenceDllExportedMembers(), clang::TreeTransform< Derived >::TransformAttr(), clang::attrvisitor::Base< Ptr, ImplClass, RetTy, ParamTys >::Visit(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
getLocation()
SourceLocation clang::Attr::getLocation () const inline
Definition at line 93 of file Attr.h.
References clang::SourceRange::getBegin(), and clang::AttributeCommonInfo::getRange().
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnOpenMPDeclareTargetName(), clang::Sema::ActOnStartOfFunctionDef(), checkAttributesAfterMerging(), checkAttrMutualExclusion(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckCompleteVariableDeclaration(), CheckForIncompatibleAttributes(), checkForMultipleExportedDefaultConstructors(), clang::Sema::checkIllFormedTrivialABIStruct(), CheckNakedParmReference(), checkNewAttributesAfterDef(), diagnoseDiagnoseIfAttrsWith(), diagnoseMissingConstinit(), clang::Sema::FinalizeDeclaration(), clang::TypeLoc::findNullabilityLoc(), clang::tooling::getAssociatedRange(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), instantiateDependentAlignedAttr(), instantiateDependentAlignedAttr(), instantiateDependentAllocAlignAttr(), instantiateDependentFunctionAttrCondition(), mergeAlignedAttrs(), clang::Sema::MergeFunctionDecl(), mergeParamDeclAttributes(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), ReferenceDllExportedMembers(), and clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody().
getSpelling()
const char * clang::Attr::getSpelling () const
Referenced by clang::Sema::CheckParmsForFunctionDef(), clang::FormatASTNodeDiagnosticArgument(), handleFallThroughAttr(), and HandleOpenCLAccessAttr().
getSpellingListIndex()
unsigned clang::Attr::getSpellingListIndex () const inline
Definition at line 88 of file Attr.h.
isImplicit()
bool clang::Attr::isImplicit () const inline
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
Definition at line 99 of file Attr.h.
Referenced by clang::Sema::inferCUDATargetForImplicitSpecialMember(), clang::ASTContext::mayExternalizeStaticVar(), clang::Sema::mergeDeclAttributes(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
isInherited()
bool clang::Attr::isInherited () const inline
Definition at line 95 of file Attr.h.
References Inherited.
Referenced by clang::Sema::ActOnVariableDeclarator(), clang::Decl::addAttr(), clang::Sema::checkClassLevelDLLAttribute(), DoEmitAvailabilityWarning(), clang::Sema::FinalizeDeclaration(), ReferenceDllExportedMembers(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
isLateParsed()
bool clang::Attr::isLateParsed () const inline
Definition at line 108 of file Attr.h.
References IsLateParsed.
isPackExpansion()
bool clang::Attr::isPackExpansion () const inline
Definition at line 103 of file Attr.h.
References IsPackExpansion.
Referenced by instantiateDependentAlignedAttr().
operator delete() [1/2]
void clang::Attr::operator delete (void * data) inline protected noexcept
Definition at line 64 of file Attr.h.
operator delete() [2/2]
void clang::Attr::operator delete (void * Ptr, ASTContext & C, size_t Alignment) inline noexcept
Definition at line 74 of file Attr.h.
operator new() [1/2]
void * clang::Attr::operator new (size_t bytes) inline protected noexcept
Definition at line 61 of file Attr.h.
operator new() [2/2]
void * clang::Attr::operator new (size_t Bytes, ASTContext & C, size_t Alignment = 8) inline noexcept
Definition at line 70 of file Attr.h.
printPretty()
void clang::Attr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
setImplicit()
void clang::Attr::setImplicit (bool I) inline
Definition at line 100 of file Attr.h.
References Implicit.
Referenced by checkObjCKindOfType(), getImplicitCodeSegAttrFromClass(), and clang::ASTImporter::Import().
setPackExpansion()
void clang::Attr::setPackExpansion (bool PE) inline
Definition at line 102 of file Attr.h.
Referenced by clang::ASTImporter::Import().
Member Data Documentation
Implicit
unsigned clang::Attr::Implicit protected
Definition at line 55 of file Attr.h.
Referenced by clang::AMDGPUNumSGPRAttr::Create(), and setImplicit().
Inherited
unsigned clang::Attr::Inherited protected
An index into the spelling list of an attribute defined in Attr.td file.
Definition at line 53 of file Attr.h.
Referenced by isInherited(), and clang::InheritableAttr::setInherited().
InheritEvenIfAlreadyPresent
unsigned clang::Attr::InheritEvenIfAlreadyPresent protected
Definition at line 59 of file Attr.h.
Referenced by clang::AMDGPUNumVGPRAttr::getNumVGPR(), and clang::InheritableAttr::shouldInheritEvenIfAlreadyPresent().
IsLateParsed
unsigned clang::Attr::IsLateParsed protected
Definition at line 58 of file Attr.h.
Referenced by isLateParsed().
IsPackExpansion
unsigned clang::Attr::IsPackExpansion protected
Definition at line 54 of file Attr.h.
Referenced by clang::AMDGPUNumSGPRAttr::AMDGPUNumSGPRAttr(), and isPackExpansion().
The documentation for this class was generated from the following file:
include/clang/AST/Attr.h