clang: clang::Preprocessor Class Reference
clang::Preprocessor Class Reference
Engages in a tight little dance with the lexer to efficiently preprocess tokens.
#include "clang/Lex/Preprocessor.h"
Classes
struct PreambleSkipInfo
class ResetMacroExpansionHelper
Public Member Functions
Preprocessor (std::shared_ptr< PreprocessorOptions > PPOpts, DiagnosticsEngine &diags, LangOptions &opts, SourceManager &SM, HeaderSearch &Headers, ModuleLoader &TheModuleLoader, IdentifierInfoLookup *IILookup=nullptr, bool OwnsHeaderSearch=false, TranslationUnitKind TUKind=TU_Complete)
~Preprocessor ()
void Initialize (const TargetInfo &Target, const TargetInfo *AuxTarget=nullptr)
Initialize the preprocessor using information about the target.
void InitializeForModelFile ()
Initialize the preprocessor to parse a model file.
void FinalizeForModelFile ()
Cleanup after model file parsing.
PreprocessorOptions & getPreprocessorOpts () const
Retrieve the preprocessor options used to initialize this preprocessor.
DiagnosticsEngine & getDiagnostics () const
void setDiagnostics (DiagnosticsEngine &D)
const LangOptions & getLangOpts () const
const TargetInfo & getTargetInfo () const
const TargetInfo * getAuxTargetInfo () const
FileManager & getFileManager () const
SourceManager & getSourceManager () const
HeaderSearch & getHeaderSearchInfo () const
IdentifierTable & getIdentifierTable ()
const IdentifierTable & getIdentifierTable () const
SelectorTable & getSelectorTable ()
Builtin::Context & getBuiltinInfo ()
llvm::BumpPtrAllocator & getPreprocessorAllocator ()
void setExternalSource (ExternalPreprocessorSource *Source)
ExternalPreprocessorSource * getExternalSource () const
ModuleLoader & getModuleLoader () const
Retrieve the module loader associated with this preprocessor.
bool hadModuleLoaderFatalFailure () const
unsigned getNumDirectives () const
Retrieve the number of Directives that have been processed by the Preprocessor.
bool isParsingIfOrElifDirective () const
True if we are currently preprocessing a if or #elif directive.
void SetCommentRetentionState (bool KeepComments, bool KeepMacroComments)
Control whether the preprocessor retains comments in output.
bool getCommentRetentionState () const
void setPragmasEnabled (bool Enabled)
bool getPragmasEnabled () const
void SetSuppressIncludeNotFoundError (bool Suppress)
bool GetSuppressIncludeNotFoundError ()
void setPreprocessedOutput (bool IsPreprocessedOutput)
Sets whether the preprocessor is responsible for producing output or if it is producing tokens to be consumed by Parse and Sema.
bool isPreprocessedOutput () const
Returns true if the preprocessor is responsible for generating output, false if it is producing tokens to be consumed by Parse and Sema.
bool isCurrentLexer (const PreprocessorLexer *L) const
Return true if we are lexing directly from the specified lexer.
PreprocessorLexer * getCurrentLexer () const
Return the current lexer being lexed from.
PreprocessorLexer * getCurrentFileLexer () const
Return the current file lexer being lexed from.
Module * getCurrentLexerSubmodule () const
Return the submodule owning the file being lexed.
FileID getPredefinesFileID () const
Returns the FileID for the preprocessor predefines.
unsigned getTokenCount () const
Get the number of tokens processed so far.
unsigned getMaxTokens () const
Get the max number of tokens before issuing a -Wmax-tokens warning.
void overrideMaxTokens (unsigned Value, SourceLocation Loc)
SourceLocation getMaxTokensOverrideLoc () const
void setTokenWatcher (llvm::unique_function< void(const clang::Token &)> F)
Register a function that would be called on each token in the final expanded token stream.
void setPreprocessToken (bool Preprocess)
bool isMacroDefined (StringRef Id)
bool isMacroDefined (const IdentifierInfo *II)
bool isMacroDefinedInLocalModule (const IdentifierInfo *II, Module *M)
Determine whether II is defined as a macro within the module M, if that is a module that we've already preprocessed.
MacroDefinition getMacroDefinition (const IdentifierInfo *II)
MacroDefinition getMacroDefinitionAtLoc (const IdentifierInfo *II, SourceLocation Loc)
MacroDirective * getLocalMacroDirective (const IdentifierInfo *II) const
Given an identifier, return its latest non-imported MacroDirective if it is #define'd and not #undef'd, or null if it isn't #define'd.
const MacroInfo * getMacroInfo (const IdentifierInfo *II) const
MacroInfo * getMacroInfo (const IdentifierInfo *II)
MacroDirective * getLocalMacroDirectiveHistory (const IdentifierInfo *II) const
Given an identifier, return the latest non-imported macro directive for that identifier.
void appendMacroDirective (IdentifierInfo *II, MacroDirective *MD)
Add a directive to the macro directive history for this identifier.
DefMacroDirective * appendDefMacroDirective (IdentifierInfo *II, MacroInfo *MI, SourceLocation Loc)
DefMacroDirective * appendDefMacroDirective (IdentifierInfo *II, MacroInfo *MI)
void setLoadedMacroDirective (IdentifierInfo *II, MacroDirective *ED, MacroDirective *MD)
Set a MacroDirective that was loaded from a PCH file.
ModuleMacro * addModuleMacro (Module *Mod, IdentifierInfo *II, MacroInfo *Macro, ArrayRef< ModuleMacro * > Overrides, bool &IsNew)
Register an exported macro for a module and identifier.
ModuleMacro * getModuleMacro (Module *Mod, IdentifierInfo *II)
ArrayRef< ModuleMacro * > getLeafModuleMacros (const IdentifierInfo *II) const
Get the list of leaf (non-overridden) module macros for a name.
StringRef getLastMacroWithSpelling (SourceLocation Loc, ArrayRef< TokenValue > Tokens) const
Return the name of the macro defined before Loc that has spelling Tokens.
const std::string & getPredefines () const
void setPredefines (const char *P)
Set the predefines for this Preprocessor.
void setPredefines (StringRef P)
IdentifierInfo * getIdentifierInfo (StringRef Name) const
Return information about the specified preprocessor identifier token.
void AddPragmaHandler (StringRef Namespace, PragmaHandler *Handler)
Add the specified pragma handler to this preprocessor.
void AddPragmaHandler (PragmaHandler *Handler)
void RemovePragmaHandler (StringRef Namespace, PragmaHandler *Handler)
Remove the specific pragma handler from this preprocessor.
void RemovePragmaHandler (PragmaHandler *Handler)
void IgnorePragmas ()
Install empty handlers for all pragmas (making them ignored).
void setEmptylineHandler (EmptylineHandler *Handler)
Set empty line handler.
EmptylineHandler * getEmptylineHandler () const
void addCommentHandler (CommentHandler *Handler)
Add the specified comment handler to the preprocessor.
void removeCommentHandler (CommentHandler *Handler)
Remove the specified comment handler.
void setCodeCompletionHandler (CodeCompletionHandler &Handler)
Set the code completion handler to the given object.
CodeCompletionHandler * getCodeCompletionHandler () const
Retrieve the current code-completion handler.
void clearCodeCompletionHandler ()
Clear out the code completion handler.
void CodeCompleteIncludedFile (llvm::StringRef Dir, bool IsAngled)
Hook used by the lexer to invoke the "included file" code completion point.
void CodeCompleteNaturalLanguage ()
Hook used by the lexer to invoke the "natural language" code completion point.
void setCodeCompletionIdentifierInfo (IdentifierInfo *Filter)
Set the code completion token for filtering purposes.
void setCodeCompletionTokenRange (const SourceLocation Start, const SourceLocation End)
Set the code completion token range for detecting replacement range later on.
SourceRange getCodeCompletionTokenRange () const
StringRef getCodeCompletionFilter ()
Get the code completion token for filtering purposes.
PreprocessingRecord * getPreprocessingRecord () const
Retrieve the preprocessing record, or NULL if there is no preprocessing record.
void createPreprocessingRecord ()
Create a new preprocessing record, which will keep track of all macro expansions, macro definitions, etc.
bool isPCHThroughHeader (const FileEntry *FE)
Returns true if the FileEntry is the PCH through header.
bool creatingPCHWithThroughHeader ()
True if creating a PCH with a through header.
bool usingPCHWithThroughHeader ()
True if using a PCH with a through header.
bool creatingPCHWithPragmaHdrStop ()
True if creating a PCH with a #pragma hdrstop.
bool usingPCHWithPragmaHdrStop ()
True if using a PCH with a #pragma hdrstop.
void SkipTokensWhileUsingPCH ()
Skip tokens until after the #include of the through header or until after a #pragma hdrstop.
void HandleSkippedDirectiveWhileUsingPCH (Token &Result, SourceLocation HashLoc)
Process directives while skipping until the through header or #pragma hdrstop is found.
void EnterMainSourceFile ()
Enter the specified FileID as the main source file, which implicitly adds the builtin defines etc.
void EndSourceFile ()
Inform the preprocessor callbacks that processing is complete.
bool EnterSourceFile (FileID FID, const DirectoryLookup *Dir, SourceLocation Loc)
Add a source file to the top of the include stack and start lexing tokens from it instead of the current buffer.
void EnterMacro (Token &Tok, SourceLocation ILEnd, MacroInfo *Macro, MacroArgs *Args)
Add a Macro to the top of the include stack and start lexing tokens from it instead of the current buffer.
void EnterTokenStream (std::unique_ptr< Token[]> Toks, unsigned NumToks, bool DisableMacroExpansion, bool IsReinject)
void EnterTokenStream (ArrayRef< Token > Toks, bool DisableMacroExpansion, bool IsReinject)
void RemoveTopOfLexerStack ()
Pop the current lexer/macro exp off the top of the lexer stack.
void EnableBacktrackAtThisPos ()
From the point that this method is called, and until CommitBacktrackedTokens() or Backtrack() is called, the Preprocessor keeps track of the lexed tokens so that a subsequent Backtrack() call will make the Preprocessor re-lex the same tokens.
void CommitBacktrackedTokens ()
Disable the last EnableBacktrackAtThisPos call.
void Backtrack ()
Make Preprocessor re-lex the tokens that were lexed since EnableBacktrackAtThisPos() was previously called.
bool isBacktrackEnabled () const
True if EnableBacktrackAtThisPos() was called and caching of tokens is on.
void Lex (Token &Result)
Lex the next token for this preprocessor.
bool LexHeaderName (Token &Result, bool AllowMacroExpansion=true)
Lex a token, forming a header-name token if possible.
bool LexAfterModuleImport (Token &Result)
Lex a token following the 'import' contextual keyword.
void CollectPpImportSuffix (SmallVectorImpl< Token > &Toks)
Collect the tokens of a C++20 pp-import-suffix.
void makeModuleVisible (Module *M, SourceLocation Loc)
SourceLocation getModuleImportLoc (Module *M) const
bool LexStringLiteral (Token &Result, std::string &String, const char *DiagnosticTag, bool AllowMacroExpansion)
Lex a string literal, which may be the concatenation of multiple string literals and may even come from macro expansion.
bool FinishLexStringLiteral (Token &Result, std::string &String, const char *DiagnosticTag, bool AllowMacroExpansion)
Complete the lexing of a string literal where the first token has already been lexed (see LexStringLiteral).
void LexNonComment (Token &Result)
Lex a token.
void LexUnexpandedToken (Token &Result)
Just like Lex, but disables macro expansion of identifier tokens.
void LexUnexpandedNonComment (Token &Result)
Like LexNonComment, but this disables macro expansion of identifier tokens.
bool parseSimpleIntegerLiteral (Token &Tok, uint64_t &Value)
Parses a simple integer literal to get its numeric value.
void SetMacroExpansionOnlyInDirectives ()
Disables macro expansion everywhere except for preprocessor directives.
const Token & LookAhead (unsigned N)
Peeks ahead N tokens and returns that token without consuming any tokens.
void RevertCachedTokens (unsigned N)
When backtracking is enabled and tokens are cached, this allows to revert a specific number of tokens.
void EnterToken (const Token &Tok, bool IsReinject)
Enters a token in the token stream to be lexed next.
void AnnotateCachedTokens (const Token &Tok)
We notify the Preprocessor that if it is caching tokens (because backtrack is enabled) it should replace the most recent cached tokens with the given annotation token.
SourceLocation getLastCachedTokenLocation () const
Get the location of the last cached token, suitable for setting the end location of an annotation token.
bool IsPreviousCachedToken (const Token &Tok) const
Whether Tok is the most recent token (CachedLexPos - 1) in CachedTokens.
void ReplacePreviousCachedToken (ArrayRef< Token > NewToks)
Replace token in CachedLexPos - 1 in CachedTokens by the tokens in NewToks.
void ReplaceLastTokenWithAnnotation (const Token &Tok)
Replace the last token with an annotation token.
void EnterAnnotationToken (SourceRange Range, tok::TokenKind Kind, void *AnnotationVal)
Enter an annotation token into the token stream.
bool mightHavePendingAnnotationTokens ()
Determine whether it's possible for a future call to Lex to produce an annotation token created by a previous call to EnterAnnotationToken.
void TypoCorrectToken (const Token &Tok)
Update the current token to represent the provided identifier, in order to cache an action performed by typo correction.
void recomputeCurLexerKind ()
Recompute the current lexer kind based on the CurLexer/ CurTokenLexer pointers.
bool isIncrementalProcessingEnabled () const
Returns true if incremental processing is enabled.
void enableIncrementalProcessing (bool value=true)
Enables the incremental processing.
bool SetCodeCompletionPoint (const FileEntry *File, unsigned Line, unsigned Column)
Specify the point at which code-completion will be performed.
bool isCodeCompletionEnabled () const
Determine if we are performing code completion.
SourceLocation getCodeCompletionLoc () const
Returns the location of the code-completion point.
SourceLocation getCodeCompletionFileLoc () const
Returns the start location of the file of code-completion point.
bool isCodeCompletionReached () const
Returns true if code-completion is enabled and we have hit the code-completion point.
void setCodeCompletionReached ()
Note that we hit the code-completion point.
std::pair< IdentifierInfo *, SourceLocation > getPragmaARCCFCodeAuditedInfo () const
The location of the currently-active #pragma clang arc_cf_code_audited begin.
void setPragmaARCCFCodeAuditedInfo (IdentifierInfo *Ident, SourceLocation Loc)
Set the location of the currently-active #pragma clang arc_cf_code_audited begin.
SourceLocation getPragmaAssumeNonNullLoc () const
The location of the currently-active #pragma clang assume_nonnull begin.
void setPragmaAssumeNonNullLoc (SourceLocation Loc)
Set the location of the currently-active #pragma clang assume_nonnull begin.
void setMainFileDir (const DirectoryEntry *Dir)
Set the directory in which the main file should be considered to have been found, if it is not a real file.
void setSkipMainFilePreamble (unsigned Bytes, bool StartOfLine)
Instruct the preprocessor to skip part of the main source file.
DiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID) const
Forwarding function for diagnostics.
DiagnosticBuilder Diag (const Token &Tok, unsigned DiagID) const
StringRef getSpelling (SourceLocation loc, SmallVectorImpl< char > &buffer, bool *invalid=nullptr) const
Return the 'spelling' of the token at the given location; does not go up to the spelling location or down to the expansion location.
std::string getSpelling (const Token &Tok, bool *Invalid=nullptr) const
Return the 'spelling' of the Tok token.
unsigned getSpelling (const Token &Tok, const char *&Buffer, bool *Invalid=nullptr) const
Get the spelling of a token into a preallocated buffer, instead of as an std::string.
StringRef getSpelling (const Token &Tok, SmallVectorImpl< char > &Buffer, bool *Invalid=nullptr) const
Get the spelling of a token into a SmallVector.
bool getRawToken (SourceLocation Loc, Token &Result, bool IgnoreWhiteSpace=false)
Relex the token at the specified location.
char getSpellingOfSingleCharacterNumericConstant (const Token &Tok, bool *Invalid=nullptr) const
Given a Token Tok that is a numeric constant with length 1, return the character.
StringRef getImmediateMacroName (SourceLocation Loc)
Retrieve the name of the immediate macro expansion.
void CreateString (StringRef Str, Token &Tok, SourceLocation ExpansionLocStart=SourceLocation(), SourceLocation ExpansionLocEnd=SourceLocation())
Plop the specified string into a scratch buffer and set the specified token's location and length to it.
SourceLocation SplitToken (SourceLocation TokLoc, unsigned Length)
Split the first Length characters out of the token starting at TokLoc and return a location pointing to the split token.
SourceLocation getLocForEndOfToken (SourceLocation Loc, unsigned Offset=0)
Computes the source location just past the end of the token at this source location.
bool isAtStartOfMacroExpansion (SourceLocation loc, SourceLocation *MacroBegin=nullptr) const
Returns true if the given MacroID location points at the first token of the macro expansion.
bool isAtEndOfMacroExpansion (SourceLocation loc, SourceLocation *MacroEnd=nullptr) const
Returns true if the given MacroID location points at the last token of the macro expansion.
void DumpToken (const Token &Tok, bool DumpFlags=false) const
Print the token to stderr, used for debugging.
void DumpLocation (SourceLocation Loc) const
void DumpMacro (const MacroInfo &MI) const
void dumpMacroInfo (const IdentifierInfo *II)
SourceLocation AdvanceToTokenCharacter (SourceLocation TokStart, unsigned Char) const
Given a location that specifies the start of a token, return a new location that specifies a character within the token.
void IncrementPasteCounter (bool isFast)
Increment the counters for the number of token paste operations performed.
void PrintStats ()
size_t getTotalMemory () const
void HandleMicrosoftCommentPaste (Token &Tok)
When the macro expander pastes together a comment (/##/) in Microsoft mode, this method handles updating the current state, returning the token on the next source line.
IdentifierInfo * LookUpIdentifierInfo (Token &Identifier) const
Given a tok::raw_identifier token, look up the identifier information for the token and install it into the token, updating the token kind accordingly.
void SetPoisonReason (IdentifierInfo *II, unsigned DiagID)
Specifies the reason for poisoning an identifier.
void HandlePoisonedIdentifier (Token &Identifier)
Display reason for poisoned identifier.
void MaybeHandlePoisonedIdentifier (Token &Identifier)
void PoisonSEHIdentifiers (bool Poison=true)
bool HandleIdentifier (Token &Identifier)
Callback invoked when the lexer reads an identifier and has filled in the tokens IdentifierInfo member.
bool HandleEndOfFile (Token &Result, bool isEndOfMacro=false)
Callback invoked when the lexer hits the end of the current file.
bool HandleEndOfTokenLexer (Token &Result)
Callback invoked when the current TokenLexer hits the end of its token stream.
void HandleDirective (Token &Result)
Callback invoked when the lexer sees a # token at the start of a line.
SourceLocation CheckEndOfDirective (const char *DirType, bool EnableMacros=false)
Ensure that the next token is a tok::eod token.
SourceRange DiscardUntilEndOfDirective ()
Read and discard all tokens remaining on the current line until the tok::eod token is found.
bool SawDateOrTime () const
Returns true if the preprocessor has seen a use of DATE or TIME in the file so far.
unsigned getCounterValue () const
void setCounterValue (unsigned V)
Module * getCurrentModule ()
Retrieves the module that we're currently building, if any.
MacroInfo * AllocateMacroInfo (SourceLocation L)
Allocate a new MacroInfo object with the provided SourceLocation.
bool GetIncludeFilenameSpelling (SourceLocation Loc, StringRef &Buffer)
Turn the specified lexer token into a fully checked and spelled filename, e.g.
Optional< FileEntryRef > LookupFile (SourceLocation FilenameLoc, StringRef Filename, bool isAngled, const DirectoryLookup *FromDir, const FileEntry *FromFile, const DirectoryLookup *&CurDir, SmallVectorImpl< char > *SearchPath, SmallVectorImpl< char > *RelativePath, ModuleMap::KnownHeader *SuggestedModule, bool *IsMapped, bool *IsFrameworkFound, bool SkipCache=false)
Given a "foo" or <foo> reference, look up the indicated file.
const DirectoryLookup * GetCurDirLookup ()
Get the DirectoryLookup structure used to find the current FileEntry, if CurLexer is non-null and if applicable.
bool isInPrimaryFile () const
Return true if we're in the top-level file, not in a #include.
bool LexOnOffSwitch (tok::OnOffSwitch &Result)
Lex an on-off-switch (C99 6.10.6p2) and verify that it is followed by EOD.
bool CheckMacroName (Token &MacroNameTok, MacroUse isDefineUndef, bool *ShadowFlag=nullptr)
void EnterSubmodule (Module *M, SourceLocation ImportLoc, bool ForPragma)
Module * LeaveSubmodule (bool ForPragma)
Module * getModuleForLocation (SourceLocation Loc)
Find the module that owns the source or header file that Loc points to.
const FileEntry * getHeaderToIncludeForDiagnostics (SourceLocation IncLoc, SourceLocation MLoc)
We want to produce a diagnostic at location IncLoc concerning an unreachable effect at location MLoc (eg, where a desired entity was declared or defined).
bool isRecordingPreamble () const
bool hasRecordedPreamble () const
ArrayRef< PPConditionalInfo > getPreambleConditionalStack () const
void setRecordedPreambleConditionalStack (ArrayRef< PPConditionalInfo > s)
void setReplayablePreambleConditionalStack (ArrayRef< PPConditionalInfo > s, llvm::Optional< PreambleSkipInfo > SkipInfo)
llvm::Optional< PreambleSkipInfo > getPreambleSkipInfo () const
void HandlePragmaOnce (Token &OnceTok)
HandlePragmaOnce - Handle #pragma once. OnceTok is the 'once'.
void HandlePragmaMark ()
void HandlePragmaPoison ()
HandlePragmaPoison - Handle #pragma GCC poison. PoisonTok is the 'poison'.
void HandlePragmaSystemHeader (Token &SysHeaderTok)
HandlePragmaSystemHeader - Implement #pragma GCC system_header.
void HandlePragmaDependency (Token &DependencyTok)
HandlePragmaDependency - Handle #pragma GCC dependency "foo" blah.
void HandlePragmaPushMacro (Token &Tok)
Handle #pragma push_macro.
void HandlePragmaPopMacro (Token &Tok)
Handle #pragma pop_macro.
void HandlePragmaIncludeAlias (Token &Tok)
void HandlePragmaModuleBuild (Token &Tok)
void HandlePragmaHdrstop (Token &Tok)
IdentifierInfo * ParsePragmaPushOrPopMacro (Token &Tok)
ParsePragmaPushOrPopMacro - Handle parsing of pragma push_macro/pop_macro.
bool HandleComment (Token &result, SourceRange Comment)
void markMacroAsUsed (MacroInfo *MI)
A macro is used, update information about macros that need unused warnings.
PPCallbacks * getPPCallbacks () const
void addPPCallbacks (std::unique_ptr< PPCallbacks > C)
Static Public Member Functions
static bool checkModuleIsAvailable (const LangOptions &LangOpts, const TargetInfo &TargetInfo, DiagnosticsEngine &Diags, Module *M)
Check that the given module is available, producing a diagnostic if not.
Friends
class VAOptDefinitionContext
class VariadicMacroScopeGuard
class ASTReader
class MacroArgs
void TokenLexer::ExpandFunctionArguments ()
using macro_iterator = MacroMap::const_iterator
macro_iterator macro_begin (bool IncludeExternalMacros=true) const
macro_iterator macro_end (bool IncludeExternalMacros=true) const
llvm::iterator_range< macro_iterator > macros (bool IncludeExternalMacros=true) const
Detailed Description
Engages in a tight little dance with the lexer to efficiently preprocess tokens.
Lexers know only about tokens within a single source file, and don't know anything about preprocessor-level issues like the #include stack, token expansion, etc.
Definition at line 129 of file Preprocessor.h.
Member Typedef Documentation
macro_iterator
using clang::Preprocessor::macro_iterator = MacroMap::const_iterator
Iterators for the macro history table. Currently defined macros have IdentifierInfo::hasMacroDefinition() set and an empty MacroInfo::getUndefLoc() at the head of the list.
Definition at line 1170 of file Preprocessor.h.
Constructor & Destructor Documentation
Preprocessor()
Preprocessor::Preprocessor (std::shared_ptr< PreprocessorOptions > PPOpts, DiagnosticsEngine & diags, LangOptions & opts, SourceManager & SM, HeaderSearch & Headers, ModuleLoader & TheModuleLoader, IdentifierInfoLookup * IILookup = nullptr, bool OwnsHeaderSearch = false, TranslationUnitKind TUKind = TU_Complete)
Definition at line 79 of file Preprocessor.cpp.
References getIdentifierInfo(), SetPoisonReason(), and usingPCHWithPragmaHdrStop().
~Preprocessor()
Preprocessor::~Preprocessor ()
Definition at line 169 of file Preprocessor.cpp.
Member Function Documentation
addCommentHandler()
void Preprocessor::addCommentHandler (CommentHandler * Handler)
Add the specified comment handler to the preprocessor.
Definition at line 1382 of file Preprocessor.cpp.
Referenced by clang::Parser::Parser(), and clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks().
addModuleMacro()
ModuleMacro * Preprocessor::addModuleMacro (Module * Mod, IdentifierInfo * II, MacroInfo * Macro, ArrayRef< ModuleMacro * > Overrides, bool & IsNew)
Register an exported macro for a module and identifier.
Definition at line 131 of file PPMacroExpansion.cpp.
References clang::ModuleMacro::create(), clang::ModuleMacro::Profile(), and clang::IdentifierInfo::setHasMacroDefinition().
Referenced by LeaveSubmodule().
addPPCallbacks()
void clang::Preprocessor::addPPCallbacks (std::unique_ptr< PPCallbacks > C) inline
Definition at line 1020 of file Preprocessor.h.
References clang::C.
Referenced by clang::AttachDependencyGraphGen(), clang::AttachHeaderIncludeGen(), clang::DependencyCollector::attachToPreprocessor(), clang::ModuleDependencyCollector::attachToPreprocessor(), clang::tooling::dependencies::ModuleDepCollector::attachToPreprocessor(), clang::arcmt::MigrateSourceAction::CreateASTConsumer(), clang::arcmt::ObjCMigrateAction::CreateASTConsumer(), clang::CodeGenAction::CreateASTConsumer(), createPreprocessingRecord(), clang::DoPrintPreprocessedInput(), clang::RewriteIncludesInInput(), clang::Sema::Sema(), clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks(), and clang::syntax::TokenCollector::TokenCollector().
AddPragmaHandler() [1/2]
void clang::Preprocessor::AddPragmaHandler (PragmaHandler * Handler) inline
Definition at line 1209 of file Preprocessor.h.
References AddPragmaHandler().
AddPragmaHandler() [2/2]
void Preprocessor::AddPragmaHandler (StringRef Namespace, PragmaHandler * Handler)
Add the specified pragma handler to this preprocessor.
AddPragmaHandler - Add the specified pragma handler to the preprocessor.
If Namespace is non-null, then it is a token required to exist on the pragma line before the pragma string starts, e.g. "STDC" or "GCC".
If 'Namespace' is non-null, then it is a token required to exist on the pragma line before the pragma string starts, e.g. "STDC" or "GCC".
Definition at line 895 of file Pragma.cpp.
References clang::PragmaNamespace::AddPragma(), clang::PragmaNamespace::FindHandler(), clang::PragmaNamespace::getIfNamespace(), and clang::PragmaHandler::getName().
Referenced by AddPragmaHandler(), clang::DoPrintPreprocessedInput(), and IgnorePragmas().
AdvanceToTokenCharacter()
SourceLocation clang::Preprocessor::AdvanceToTokenCharacter (SourceLocation TokStart, unsigned Char) const inline
Given a location that specifies the start of a token, return a new location that specifies a character within the token.
Definition at line 1858 of file Preprocessor.h.
References clang::Lexer::AdvanceToTokenCharacter().
Referenced by GetLineValue().
AllocateMacroInfo()
MacroInfo * Preprocessor::AllocateMacroInfo (SourceLocation L)
Allocate a new MacroInfo object with the provided SourceLocation.
Definition at line 58 of file PPDirectives.cpp.
Referenced by RegisterBuiltinMacro().
AnnotateCachedTokens()
void clang::Preprocessor::AnnotateCachedTokens (const Token & Tok) inline
We notify the Preprocessor that if it is caching tokens (because backtrack is enabled) it should replace the most recent cached tokens with the given annotation token.
This function has no effect if backtracking is not enabled.
Note that the use of this function is just for optimization, so that the cached tokens doesn't get re-parsed and re-resolved after a backtrack is invoked.
Definition at line 1537 of file Preprocessor.h.
References isBacktrackEnabled(), and Tok.
Referenced by clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
appendDefMacroDirective() [1/2]
DefMacroDirective * clang::Preprocessor::appendDefMacroDirective (IdentifierInfo * II, MacroInfo * MI) inline
Definition at line 1142 of file Preprocessor.h.
References appendDefMacroDirective(), and clang::MacroInfo::getDefinitionLoc().
appendDefMacroDirective() [2/2]
DefMacroDirective * clang::Preprocessor::appendDefMacroDirective (IdentifierInfo * II, MacroInfo * MI, SourceLocation Loc) inline
Definition at line 1136 of file Preprocessor.h.
References appendMacroDirective().
Referenced by appendDefMacroDirective(), HandlePragmaPopMacro(), and RegisterBuiltinMacro().
appendMacroDirective()
void Preprocessor::appendMacroDirective (IdentifierInfo * II, MacroDirective * MD)
Add a directive to the macro directive history for this identifier.
Definition at line 70 of file PPMacroExpansion.cpp.
References clang::MacroDirective::getPrevious(), clang::MacroDirective::isDefined(), clang::IdentifierInfo::isFromAST(), clang::IdentifierInfo::setChangedSinceDeserialization(), clang::IdentifierInfo::setHasMacroDefinition(), and clang::MacroDirective::setPrevious().
Referenced by appendDefMacroDirective(), and HandlePragmaPopMacro().
Backtrack()
void Preprocessor::Backtrack ()
Make Preprocessor re-lex the tokens that were lexed since EnableBacktrackAtThisPos() was previously called.
Definition at line 40 of file PPCaching.cpp.
References recomputeCurLexerKind().
CheckEndOfDirective()
SourceLocation Preprocessor::CheckEndOfDirective (const char * DirType, bool EnableMacros = false)
Ensure that the next token is a tok::eod token.
If not, emit a diagnostic and consume up until the eod. If EnableMacros is true, then we consider macros that expand to zero tokens as being ok.
Returns
The location of the end of the directive (the terminating newline).
If not, emit a diagnostic and consume up until the eod. If EnableMacros is true, then we consider macros that expand to zero tokens as being ok.
Returns the location of the end of the directive.
Definition at line 342 of file PPDirectives.cpp.
References clang::FixItHint::CreateInsertion(), Diag(), DiscardUntilEndOfDirective(), clang::SourceRange::getEnd(), clang::Token::getLocation(), clang::Token::is(), Lex(), and LexUnexpandedToken().
CheckMacroName()
bool Preprocessor::CheckMacroName (Token & MacroNameTok, MacroUse isDefineUndef, bool * ShadowFlag = nullptr)
Definition at line 241 of file PPDirectives.cpp.
References Diag(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), getLangOpts(), clang::Token::getLocation(), getMacroInfo(), clang::IdentifierInfo::getPPKeywordID(), clang::Token::is(), clang::MacroInfo::isBuiltinMacro(), clang::IdentifierInfo::isCPlusPlusOperatorKeyword(), MD_KeywordDef, MD_NoWarn, MD_ReservedMacro, clang::MU_Define, clang::MU_Other, clang::MU_Undef, shouldWarnOnMacroDef(), and shouldWarnOnMacroUndef().
Referenced by EvaluateDefined().
checkModuleIsAvailable()
bool Preprocessor::checkModuleIsAvailable (const LangOptions & LangOpts, const TargetInfo & TargetInfo, DiagnosticsEngine & Diags, Module * M) static
Check that the given module is available, producing a diagnostic if not.
Returns
true if the check failed (because the module is not available). false if the module appears to be usable.
Definition at line 1648 of file PPDirectives.cpp.
References clang::Module::DefinitionLoc, clang::Module::UnresolvedHeaderDirective::FileName, clang::Module::UnresolvedHeaderDirective::FileNameLoc, clang::Module::getFullModuleName(), clang::Module::isAvailable(), clang::Module::UnresolvedHeaderDirective::IsUmbrella, clang::SourceLocation::isValid(), clang::Module::Name, and clang::DiagnosticsEngine::Report().
Referenced by clang::CompilerInstance::loadModule(), and prepareToBuildModule().
clearCodeCompletionHandler()
void clang::Preprocessor::clearCodeCompletionHandler () inline
Clear out the code completion handler.
Definition at line 1250 of file Preprocessor.h.
Referenced by clang::Parser::~Parser().
CodeCompleteIncludedFile()
void Preprocessor::CodeCompleteIncludedFile (llvm::StringRef Dir, bool IsAngled)
Hook used by the lexer to invoke the "included file" code completion point.
Definition at line 443 of file Preprocessor.cpp.
References clang::CodeCompletionHandler::CodeCompleteIncludedFile(), and setCodeCompletionReached().
CodeCompleteNaturalLanguage()
void Preprocessor::CodeCompleteNaturalLanguage ()
Hook used by the lexer to invoke the "natural language" code completion point.
Definition at line 450 of file Preprocessor.cpp.
References clang::CodeCompletionHandler::CodeCompleteNaturalLanguage(), and setCodeCompletionReached().
Referenced by clang::Lexer::ReadToEndOfLine(), and clang::MacroArgs::StringifyArgument().
CollectPpImportSuffix()
void Preprocessor::CollectPpImportSuffix (SmallVectorImpl< Token > & Toks)
Collect the tokens of a C++20 pp-import-suffix.
Definition at line 1075 of file Preprocessor.cpp.
References Lex().
Referenced by LexAfterModuleImport().
CommitBacktrackedTokens()
void Preprocessor::CommitBacktrackedTokens ()
Disable the last EnableBacktrackAtThisPos call.
Definition at line 32 of file PPCaching.cpp.
createPreprocessingRecord()
void Preprocessor::createPreprocessingRecord ()
Create a new preprocessing record, which will keep track of all macro expansions, macro definitions, etc.
Definition at line 1418 of file Preprocessor.cpp.
References addPPCallbacks(), and getSourceManager().
CreateString()
void Preprocessor::CreateString (StringRef Str, Token & Tok, SourceLocation ExpansionLocStart = SourceLocation(), SourceLocation ExpansionLocEnd = SourceLocation())
Plop the specified string into a scratch buffer and set the specified token's location and length to it.
CreateString - Plop the specified string into a scratch buffer and return a location for it.
If specified, the source location provides a location of the expansion point of the token.
If specified, the source location provides a source location for the token.
Definition at line 481 of file Preprocessor.cpp.
References clang::Token::is(), clang::Token::isLiteral(), clang::SourceLocation::isValid(), clang::Token::setLength(), clang::Token::setLiteralData(), clang::Token::setLocation(), clang::Token::setRawIdentifierData(), and Tok.
Referenced by ComputeDATE_TIME(), LexHeaderName(), ParsePragmaPushOrPopMacro(), and clang::MacroArgs::StringifyArgument().
creatingPCHWithPragmaHdrStop()
bool Preprocessor::creatingPCHWithPragmaHdrStop ()
True if creating a PCH with a #pragma hdrstop.
Definition at line 613 of file Preprocessor.cpp.
References clang::TU_Prefix.
Referenced by HandlePragmaHdrstop().
creatingPCHWithThroughHeader()
bool Preprocessor::creatingPCHWithThroughHeader ()
True if creating a PCH with a through header.
Definition at line 603 of file Preprocessor.cpp.
References clang::FileID::isValid(), and clang::TU_Prefix.
Referenced by HandleEndOfFile().
Diag() [1/2]
DiagnosticBuilder clang::Preprocessor::Diag (const Token & Tok, unsigned DiagID) const inline
Definition at line 1705 of file Preprocessor.h.
References clang::DiagnosticsEngine::Report(), and Tok.
Diag() [2/2]
DiagnosticBuilder clang::Preprocessor::Diag (SourceLocation Loc, unsigned DiagID) const inline
Forwarding function for diagnostics.
This emits a diagnostic at the specified Token's location, translating the token's start position in the current buffer into a SourcePosition object for rendering.
Definition at line 1701 of file Preprocessor.h.
References clang::DiagnosticsEngine::Report().
Referenced by buildMSAsmString(), clang::CharLiteralParser::CharLiteralParser(), checkConfigMacro(), CheckEndOfDirective(), CheckMacroName(), clang::Lexer::Diag(), diagnoseAutoModuleImport(), diagnoseUnexpectedOperator(), EnterMainSourceFile(), EnterSourceFile(), EvaluateDefined(), EvaluateDirectiveSubExpr(), EvaluateFeatureLikeBuiltinMacro(), EvaluateHasIncludeCommon(), EvaluateHasIncludeNext(), EvaluateValue(), ExpectFeatureIdentifierInfo(), FinishLexStringLiteral(), GetIncludeFilenameSpelling(), GetLineValue(), HandleDirective(), HandleEndOfFile(), HandleIdentifier(), HandlePoisonedIdentifier(), clang::PragmaNamespace::HandlePragma(), HandlePragmaDependency(), HandlePragmaHdrstop(), HandlePragmaIncludeAlias(), HandlePragmaModuleBuild(), HandlePragmaOnce(), HandlePragmaPoison(), HandlePragmaPopMacro(), HandlePragmaSystemHeader(), LexAfterModuleImport(), LexHeaderName(), LexModuleNameComponent(), LexOnOffSwitch(), makeModuleVisible(), ParseAlignPragma(), ParseLoopHintValue(), ParsePragmaPushOrPopMacro(), clang::Parser::ParseTopLevelDecl(), ReadLineMarkerFlags(), SkipTokensWhileUsingPCH(), and clang::MacroArgs::StringifyArgument().
DiscardUntilEndOfDirective()
SourceRange Preprocessor::DiscardUntilEndOfDirective ()
Read and discard all tokens remaining on the current line until the tok::eod token is found.
Returns the range of the skipped tokens.
Definition at line 82 of file PPDirectives.cpp.
References clang::Token::getLocation(), clang::Token::isNot(), LexUnexpandedToken(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Referenced by CheckEndOfDirective(), GetLineValue(), HandleDirective(), HandlePragmaModuleBuild(), HandleSkippedDirectiveWhileUsingPCH(), and ReadLineMarkerFlags().
DumpLocation()
void Preprocessor::DumpLocation (SourceLocation Loc) const
Definition at line 255 of file Preprocessor.cpp.
References clang::SourceLocation::print().
Referenced by DumpToken().
DumpMacro()
void Preprocessor::DumpMacro (const MacroInfo & MI) const
Definition at line 259 of file Preprocessor.cpp.
References DumpToken(), clang::MacroInfo::getNumTokens(), and clang::MacroInfo::getReplacementToken().
dumpMacroInfo()
void Preprocessor::dumpMacroInfo (const IdentifierInfo * II)
Definition at line 259 of file PPMacroExpansion.cpp.
References clang::MacroInfo::dump(), clang::IdentifierInfo::getNameStart(), and clang::VisibleModuleSet::isVisible().
DumpToken()
void Preprocessor::DumpToken (const Token & Tok, bool DumpFlags = false) const
Print the token to stderr, used for debugging.
Definition at line 231 of file Preprocessor.cpp.
References DumpLocation(), clang::Token::getKind(), clang::Token::getLength(), clang::Token::getLocation(), getSpelling(), clang::tok::getTokenName(), clang::Token::hasLeadingSpace(), clang::Token::isAtStartOfLine(), clang::Token::isExpandDisabled(), clang::Token::needsCleaning(), and Tok.
Referenced by DumpMacro(), clang::DumpRawTokensAction::ExecuteAction(), and clang::DumpTokensAction::ExecuteAction().
EnableBacktrackAtThisPos()
void Preprocessor::EnableBacktrackAtThisPos ()
From the point that this method is called, and until CommitBacktrackedTokens() or Backtrack() is called, the Preprocessor keeps track of the lexed tokens so that a subsequent Backtrack() call will make the Preprocessor re-lex the same tokens.
Nested backtracks are allowed, meaning that EnableBacktrackAtThisPos can be called multiple times and CommitBacktrackedTokens/Backtrack calls will be combined with the EnableBacktrackAtThisPos calls in reverse order.
NOTE: DO NOT forget to call either CommitBacktrackedTokens or Backtrack at some point after EnableBacktrackAtThisPos. If you don't, caching of tokens will continue indefinitely.
Definition at line 25 of file PPCaching.cpp.
enableIncrementalProcessing()
void clang::Preprocessor::enableIncrementalProcessing (bool value = true) inline
Enables the incremental processing.
Definition at line 1601 of file Preprocessor.h.
EndSourceFile()
void Preprocessor::EndSourceFile ()
Inform the preprocessor callbacks that processing is complete.
Definition at line 683 of file Preprocessor.cpp.
Referenced by clang::FrontendAction::EndSourceFile().
EnterAnnotationToken()
void Preprocessor::EnterAnnotationToken (SourceRange Range, tok::TokenKind Kind, void * AnnotationVal)
Enter an annotation token into the token stream.
Push a token onto the token stream containing an annotation.
Definition at line 1550 of file PPDirectives.cpp.
References clang::Token::setAnnotationEndLoc(), clang::Token::setAnnotationValue(), clang::Token::setKind(), clang::Token::setLocation(), clang::Token::startToken(), and Tok.
EnterMacro()
void Preprocessor::EnterMacro (Token & Tok, SourceLocation ILEnd, MacroInfo * Macro, MacroArgs * Args)
Add a Macro to the top of the include stack and start lexing tokens from it instead of the current buffer.
EnterMacro - Add a Macro to the top of the include stack and start lexing tokens from it instead of the current buffer.
Parameters
Args specifies the tokens input to a function-like macro.
ILEnd specifies the location of the ')' for a function-like macro or the identifier for an object-like macro.
Definition at line 124 of file PPLexerChange.cpp.
References Tok.
EnterMainSourceFile()
void Preprocessor::EnterMainSourceFile ()
Enter the specified FileID as the main source file, which implicitly adds the builtin defines etc.
EnterMainSourceFile - Enter the specified FileID as the main source file, which implicitly adds the builtin defines etc.
Definition at line 530 of file Preprocessor.cpp.
References clang::SrcMgr::C_User, Diag(), EnterSourceFile(), clang::File, clang::HeaderSearch::IncrementIncludeCount(), clang::FileID::isValid(), LookupFile(), SkipTokensWhileUsingPCH(), usingPCHWithPragmaHdrStop(), and usingPCHWithThroughHeader().
Referenced by DoPrintMacros(), clang::DoPrintPreprocessedInput(), clang::DumpTokensAction::ExecuteAction(), clang::PreprocessOnlyAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), clang::ParseAST(), clang::RewriteIncludesInInput(), and clang::RewriteMacrosInInput().
EnterSourceFile()
bool Preprocessor::EnterSourceFile (FileID FID, const DirectoryLookup * Dir, SourceLocation Loc)
Add a source file to the top of the include stack and start lexing tokens from it instead of the current buffer.
EnterSourceFile - Add a source file to the top of the include stack and start lexing tokens from it instead of the current buffer.
Emits a diagnostic, doesn't enter the file, and returns true on error.
Definition at line 67 of file PPLexerChange.cpp.
References Diag(), clang::SourceManager::getBufferOrNone(), clang::SourceLocation::getLocWithOffset(), getSourceManager(), and isCodeCompletionEnabled().
Referenced by EnterMainSourceFile().
EnterSubmodule()
void Preprocessor::EnterSubmodule (Module * M, SourceLocation ImportLoc, bool ForPragma)
Definition at line 646 of file PPLexerChange.cpp.
References getHeaderSearchInfo(), getLangOpts(), clang::HeaderSearch::getModuleMap(), makeModuleVisible(), clang::ModuleMap::resolveConflicts(), clang::ModuleMap::resolveExports(), clang::ModuleMap::resolveUses(), and State.
EnterToken()
void clang::Preprocessor::EnterToken (const Token & Tok, bool IsReinject) inline
Enters a token in the token stream to be lexed next.
If BackTrack() is called afterwards, the token will remain at the insertion point. If IsReinject is true, resulting token will have Token::IsReinjected flag set. See the flag documentation for details.
Definition at line 1515 of file Preprocessor.h.
References Tok.
Referenced by FixDigraph(), and clang::Parser::TryAnnotateTypeOrScopeToken().
EnterTokenStream() [1/2]
void clang::Preprocessor::EnterTokenStream (ArrayRef< Token > Toks, bool DisableMacroExpansion, bool IsReinject) inline
Definition at line 1365 of file Preprocessor.h.
EnterTokenStream() [2/2]
void clang::Preprocessor::EnterTokenStream (std::unique_ptr< Token[]> Toks, unsigned NumToks, bool DisableMacroExpansion, bool IsReinject) inline
Definition at line 1359 of file Preprocessor.h.
FinalizeForModelFile()
void Preprocessor::FinalizeForModelFile ()
Cleanup after model file parsing.
Definition at line 225 of file Preprocessor.cpp.
FinishLexStringLiteral()
bool Preprocessor::FinishLexStringLiteral (Token & Result, std::string & String, const char * DiagnosticTag, bool AllowMacroExpansion)
Complete the lexing of a string literal where the first token has already been lexed (see LexStringLiteral).
Definition at line 1321 of file Preprocessor.cpp.
References Diag(), clang::StringLiteralParser::GetString(), clang::StringLiteralParser::hadError, clang::StringLiteralParser::isAscii(), Lex(), LexUnexpandedToken(), clang::StringLiteralParser::Pascal, and clang::Result.
Referenced by LexStringLiteral().
getAuxTargetInfo()
const TargetInfo * clang::Preprocessor::getAuxTargetInfo () const inline
Definition at line 924 of file Preprocessor.h.
Referenced by clang::InitializePreprocessor().
getBuiltinInfo()
Builtin::Context & clang::Preprocessor::getBuiltinInfo () inline
Definition at line 932 of file Preprocessor.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::CompilerInstance::createASTContext(), clang::createChainedIncludesSource(), and clang::ASTUnit::LoadFromASTFile().
getCodeCompletionFileLoc()
SourceLocation clang::Preprocessor::getCodeCompletionFileLoc () const inline
Returns the start location of the file of code-completion point.
Returns an invalid location if code-completion is not enabled or the file containing the code-completion point has not been lexed yet.
Definition at line 1635 of file Preprocessor.h.
getCodeCompletionFilter()
StringRef clang::Preprocessor::getCodeCompletionFilter () inline
Get the code completion token for filtering purposes.
Definition at line 1278 of file Preprocessor.h.
Referenced by clang::PrintingCodeCompleteConsumer::ProcessCodeCompleteResults().
getCodeCompletionHandler()
CodeCompletionHandler * clang::Preprocessor::getCodeCompletionHandler () const inline
Retrieve the current code-completion handler.
Definition at line 1245 of file Preprocessor.h.
Referenced by EvaluateDefined(), and EvaluateValue().
getCodeCompletionLoc()
SourceLocation clang::Preprocessor::getCodeCompletionLoc () const inline
Returns the location of the code-completion point.
Returns an invalid location if code-completion is not enabled or the file containing the code-completion point has not been lexed yet.
Definition at line 1629 of file Preprocessor.h.
getCodeCompletionTokenRange()
SourceRange clang::Preprocessor::getCodeCompletionTokenRange () const inline
Definition at line 1273 of file Preprocessor.h.
getCommentRetentionState()
bool clang::Preprocessor::getCommentRetentionState () const inline
Definition at line 967 of file Preprocessor.h.
Referenced by HandleComment(), PrintPreprocessedTokens(), and clang::Lexer::resetExtendedTokenMode().
getCounterValue()
unsigned clang::Preprocessor::getCounterValue () const inline
Definition at line 1983 of file Preprocessor.h.
GetCurDirLookup()
const DirectoryLookup * clang::Preprocessor::GetCurDirLookup () inline
Get the DirectoryLookup structure used to find the current FileEntry, if CurLexer is non-null and if applicable.
This allows us to implement #include_next and find directory-specific properties.
Definition at line 2020 of file Preprocessor.h.
Referenced by EvaluateHasIncludeNext().
getCurrentFileLexer()
PreprocessorLexer * Preprocessor::getCurrentFileLexer () const
Return the current file lexer being lexed from.
getCurrentLexer - Return the current file lexer being lexed from.
Note that this ignores any potentially active macro expansions and _Pragma expansions going on at the time.
Definition at line 48 of file PPLexerChange.cpp.
Referenced by HandlePragmaDependency(), HandlePragmaOnce(), HandlePragmaSystemHeader(), and LookupFile().
getCurrentLexer()
PreprocessorLexer * clang::Preprocessor::getCurrentLexer () const inline
Return the current lexer being lexed from.
Note that this ignores any potentially active macro expansions and _Pragma expansions going on at the time.
Definition at line 999 of file Preprocessor.h.
Referenced by EvaluateHasIncludeNext(), and clang::ParseAST().
getCurrentLexerSubmodule()
Module * clang::Preprocessor::getCurrentLexerSubmodule () const inline
Return the submodule owning the file being lexed.
This may not be the current module if we have changed modules since entering the file.
Definition at line 1009 of file Preprocessor.h.
Referenced by EvaluateHasIncludeNext().
getCurrentModule()
Module * Preprocessor::getCurrentModule ()
Retrieves the module that we're currently building, if any.
Definition at line 517 of file Preprocessor.cpp.
References getHeaderSearchInfo(), getLangOpts(), and clang::HeaderSearch::lookupModule().
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), HandleEndOfFile(), LookupFile(), and markIdentifierFromAST().
getDiagnostics()
DiagnosticsEngine & clang::Preprocessor::getDiagnostics () const inline
Definition at line 919 of file Preprocessor.h.
Referenced by clang::Sema::ActOnNumericConstant(), AddImplicitIncludePCH(), clang::AttachHeaderIncludeGen(), clang::DependencyCollector::attachToPreprocessor(), clang::CharLiteralParser::CharLiteralParser(), clang::ento::CreateAnalysisConsumer(), EnableCodeCompletion(), EvaluateValue(), clang::PCHGenerator::HandleTranslationUnit(), HasExtension(), clang::InitializePreprocessor(), ParseDirective(), parseSimpleIntegerLiteral(), clang::PCHValidator::ReadDiagnosticOptions(), and setCodeCompletionReached().
getEmptylineHandler()
EmptylineHandler * clang::Preprocessor::getEmptylineHandler () const inline
Definition at line 1229 of file Preprocessor.h.
getExternalSource()
ExternalPreprocessorSource * clang::Preprocessor::getExternalSource () const inline
Definition at line 939 of file Preprocessor.h.
Referenced by isTrivialSingleTokenExpansion().
getFileManager()
FileManager & clang::Preprocessor::getFileManager () const inline
Definition at line 925 of file Preprocessor.h.
Referenced by AddImplicitIncludePCH(), EnableCodeCompletion(), clang::PCHValidator::ReadPreprocessorOptions(), and clang::SimpleASTReaderListener::ReadPreprocessorOptions().
getHeaderSearchInfo()
HeaderSearch & clang::Preprocessor::getHeaderSearchInfo () const inline
Definition at line 927 of file Preprocessor.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnGlobalModuleFragmentDecl(), clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnPrivateModuleFragmentDecl(), clang::DependencyCollector::attachToPreprocessor(), clang::ModuleDependencyCollector::attachToPreprocessor(), clang::FrontendAction::BeginSourceFile(), compileModule(), clang::CompilerInstance::createPCHExternalASTSource(), clang::FrontendAction::EndSourceFile(), EnterSubmodule(), EvaluateHasIncludeCommon(), clang::FrontendAction::Execute(), clang::FrontendAction::getCurrentModule(), getCurrentModule(), getHeaderNameForHeader(), getHeaderToIncludeForDiagnostics(), getInputBufferForModule(), getTopImportImplicitModule(), clang::VerifyDiagnosticConsumer::HandleDiagnostic(), HandlePragmaIncludeAlias(), clang::PCHGenerator::HandleTranslationUnit(), clang::CompilerInstance::loadGlobalModuleIndex(), clang::CompilerInstance::loadModule(), clang::CompilerInstance::loadModuleFile(), loadModuleMapForModuleBuild(), clang::Sema::notePreviousDefinition(), prepareToBuildModule(), and clang::PCHValidator::ReadHeaderSearchOptions().
getHeaderToIncludeForDiagnostics()
const FileEntry * Preprocessor::getHeaderToIncludeForDiagnostics (SourceLocation IncLoc, SourceLocation MLoc)
We want to produce a diagnostic at location IncLoc concerning an unreachable effect at location MLoc (eg, where a desired entity was declared or defined).
Determine whether the right way to make MLoc reachable is by #include, and if so, what header should be included.
This is not necessarily fast, and might load unexpected module maps, so should only be called by code that intends to produce an error.
Parameters
IncLoc The location at which the missing effect was detected.
MLoc A location within an unimported module at which the desired effect occurred.
Returns
A file that can be #included to provide the desired effect. Null if no such file could be determined or if a #include is not appropriate (eg, if a module should be imported instead).
Definition at line 656 of file PPDirectives.cpp.
References clang::HeaderSearch::findAllModulesForHeader(), getHeaderSearchInfo(), getLangOpts(), getModuleForLocation(), getSourceManager(), clang::HeaderSearch::hasModuleMap(), clang::SourceLocation::isInvalid(), clang::ObjC, SM, and clang::ModuleMap::TextualHeader.
Referenced by clang::Sema::diagnoseMissingImport().
getIdentifierInfo()
IdentifierInfo * clang::Preprocessor::getIdentifierInfo (StringRef Name) const inline
Return information about the specified preprocessor identifier token.
Definition at line 1200 of file Preprocessor.h.
References clang::IdentifierTable::get().
Referenced by clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnModuleImport(), checkConfigMacro(), clang::comments::Sema::checkDeprecatedCommand(), checkTupleLikeDecomposition(), clang::Sema::DefaultVariadicArgumentPromotion(), DiagnoseCallingConvCast(), clang::Sema::DiagnoseOwningPropertyGetterSynthesis(), getFallthroughAttrSpelling(), clang::Sema::getNSErrorIdent(), clang::Sema::getNullabilityKeyword(), clang::Sema::GetOrCreateMSAsmLabel(), getTupleLikeElementType(), clang::Parser::Initialize(), clang::Sema::Initialize(), isTupleLike(), LexAfterModuleImport(), LexModuleNameComponent(), clang::CompilerInstance::loadModuleFile(), LookUpIdentifierInfo(), lookupMember(), Preprocessor(), RegisterBuiltinMacro(), and clang::ento::tryExpandAsInteger().
getIdentifierTable() [1/2]
IdentifierTable & clang::Preprocessor::getIdentifierTable () inline
Definition at line 929 of file Preprocessor.h.
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::ActOnCXXTypeid(), clang::FrontendAction::BeginSourceFile(), buildCoroutineHandle(), clang::Sema::buildCoroutinePromise(), buildMemberCall(), BuildNonArrayForRange(), buildStdNoThrowDeclRef(), buildVarDecl(), clang::CompilerInstance::createASTContext(), clang::createChainedIncludesSource(), clang::Sema::DeclareGlobalNewDelete(), clang::ASTReader::DecodeIdentifierInfo(), clang::FrontendAction::EndSourceFile(), findOMPAlloctraitT(), findOMPDependT(), findOMPEventHandleT(), clang::ASTReader::getIdentifierTable(), clang::Sema::HandleExprPropertyRefExpr(), clang::Parser::Initialize(), clang::ASTUnit::LoadFromASTFile(), lookupCoroutineHandleType(), clang::Sema::lookupCoroutineTraits(), LookupMemberExpr(), lookupPromiseType(), LookupStdInitializerList(), and lookupStdTypeTraitMember().
getIdentifierTable() [2/2]
const IdentifierTable & clang::Preprocessor::getIdentifierTable () const inline
Definition at line 930 of file Preprocessor.h.
getImmediateMacroName()
StringRef clang::Preprocessor::getImmediateMacroName (SourceLocation Loc) inline
Retrieve the name of the immediate macro expansion.
This routine starts from a source location, and finds the name of the macro responsible for its immediate expansion. It looks through any intervening macro argument expansions to compute this. It returns a StringRef that refers to the SourceManager-owned buffer of the source where that macro name is spelled. Thus, the result shouldn't out-live the SourceManager.
Definition at line 1792 of file Preprocessor.h.
References clang::Lexer::getImmediateMacroName(), and getLangOpts().
Referenced by isExpandedFromConfigurationMacro(), and lookThroughRangesV3Condition().
GetIncludeFilenameSpelling()
bool Preprocessor::GetIncludeFilenameSpelling (SourceLocation Loc, StringRef & Buffer)
Turn the specified lexer token into a fully checked and spelled filename, e.g.
GetIncludeFilenameSpelling - Turn the specified lexer token into a fully checked and spelled filename, e.g.
as an operand of #include.
The caller is expected to provide a buffer that is large enough to hold the spelling of the filename, but is also expected to handle the case when this method decides to use a different buffer.
Returns
true if the input filename was in <>'s or false if it was in ""'s.
as an operand of #include. This returns true if the input filename was in <>'s or false if it were in ""'s. The caller is expected to provide a buffer that is large enough to hold the spelling of the filename, but is also expected to handle the case when this method decides to use a different buffer.
Definition at line 1502 of file PPDirectives.cpp.
References Diag().
Referenced by EvaluateHasIncludeCommon(), HandlePragmaDependency(), and HandlePragmaIncludeAlias().
getLangOpts()
const LangOptions & clang::Preprocessor::getLangOpts () const inline
Definition at line 922 of file Preprocessor.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnNumericConstant(), AddFunctionParameterChunks(), AddMacroResults(), clang::TokenConcatenation::AvoidConcat(), clang::FrontendAction::BeginSourceFile(), clang::CharLiteralParser::CharLiteralParser(), CheckMacroName(), clang::createChainedIncludesSource(), diagnoseAutoModuleImport(), clang::DoPrintPreprocessedInput(), clang::DoRewriteTest(), emitPremigrationErrors(), EnterSubmodule(), EvaluateDirectiveSubExpr(), EvaluateHasIncludeNext(), EvaluateValue(), clang::DumpRawTokensAction::ExecuteAction(), FindLocsWithCommonFileID(), getCurrentModule(), getFallthroughAttrSpelling(), getHeaderToIncludeForDiagnostics(), getImmediateMacroName(), clang::Parser::getLangOpts(), getModuleForLocation(), HandleDirective(), HandleIdentifier(), HandlePragmaOnce(), clang::PCHGenerator::HandleTranslationUnit(), HasExtension(), HasFeature(), clang::InitializePreprocessor(), isExpandedFromConfigurationMacro(), isMacroDefined(), LeaveSubmodule(), Lex(), clang::TokenLexer::Lex(), LexAfterModuleImport(), LexRawTokensFromMainFile(), clang::ASTUnit::LoadFromASTFile(), LookUpIdentifierInfo(), MaybeAddSentinel(), ParseAlignPragma(), parseSimpleIntegerLiteral(), PrintPreprocessedTokens(), clang::PCHValidator::ReadHeaderSearchOptions(), clang::PCHValidator::ReadLanguageOptions(), clang::PCHValidator::ReadPreprocessorOptions(), clang::SimpleASTReaderListener::ReadPreprocessorOptions(), clang::RewriteMacrosInInput(), shouldWarnOnMacroDef(), shouldWarnOnMacroUndef(), and clang::TokenConcatenation::TokenConcatenation().
getLastCachedTokenLocation()
SourceLocation clang::Preprocessor::getLastCachedTokenLocation () const inline
Get the location of the last cached token, suitable for setting the end location of an annotation token.
Definition at line 1545 of file Preprocessor.h.
Referenced by IsPreviousCachedToken().
getLastMacroWithSpelling()
StringRef Preprocessor::getLastMacroWithSpelling (SourceLocation Loc, ArrayRef< TokenValue > Tokens) const
Return the name of the macro defined before Loc that has spelling Tokens.
If there are multiple macros with same spelling, return the last one defined.
Definition at line 351 of file Preprocessor.cpp.
References clang::MacroDirective::DefInfo::getLocation(), clang::MacroDirective::DefInfo::getMacroInfo(), clang::SourceLocation::isInvalid(), clang::MacroInfo::isObjectLike(), clang::SourceLocation::isValid(), macro_begin(), macro_end(), and MacroDefinitionEquals().
Referenced by clang::comments::Sema::checkDeprecatedCommand(), DiagnoseCallingConvCast(), diagnoseMissingConstinit(), clang::Sema::DiagnoseOwningPropertyGetterSynthesis(), and getFallthroughAttrSpelling().
getLeafModuleMacros()
ArrayRef< ModuleMacro * > clang::Preprocessor::getLeafModuleMacros (const IdentifierInfo * II) const inline
Get the list of leaf (non-overridden) module macros for a name.
Definition at line 1157 of file Preprocessor.h.
References clang::IdentifierInfo::isOutOfDate(), and clang::None.
getLocalMacroDirective()
MacroDirective * clang::Preprocessor::getLocalMacroDirective (const IdentifierInfo * II) const inline
Given an identifier, return its latest non-imported MacroDirective if it is #define'd and not #undef'd, or null if it isn't #define'd.
Definition at line 1104 of file Preprocessor.h.
References getLocalMacroDirectiveHistory(), and clang::IdentifierInfo::hasMacroDefinition().
getLocalMacroDirectiveHistory()
MacroDirective * Preprocessor::getLocalMacroDirectiveHistory (const IdentifierInfo * II) const
Given an identifier, return the latest non-imported macro directive for that identifier.
One can iterate over all previous macro directives from the most recent one.
Definition at line 62 of file PPMacroExpansion.cpp.
References clang::IdentifierInfo::hadMacroDefinition().
Referenced by checkConfigMacro(), and getLocalMacroDirective().
getLocForEndOfToken()
SourceLocation clang::Preprocessor::getLocForEndOfToken (SourceLocation Loc, unsigned Offset = 0) inline
Computes the source location just past the end of the token at this source location.
This routine can be used to produce a source location that points just past the end of the token referenced by Loc, and is generally used when a diagnostic needs to point just after a token where it expected something different that it received. If the returned source location would not be meaningful (e.g., if it points into a macro), this routine returns an invalid source location.
Parameters
Offset an offset from the end of the token, where the source location should refer to. The default offset (0) produces a source location pointing just past the end of the token; an offset of 1 produces a source location pointing to the last character in the token, etc.
Definition at line 1825 of file Preprocessor.h.
References clang::Lexer::getLocForEndOfToken(), and Offset.
Referenced by clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::DiagnoseCommaOperator(), EvaluateHasIncludeCommon(), GenerateNewArgTokens(), clang::Parser::getEndOfPreviousToken(), and clang::Parser::ParseConstraintLogicalAndExpression().
getMacroDefinition()
MacroDefinition clang::Preprocessor::getMacroDefinition (const IdentifierInfo * II) inline
Definition at line 1074 of file Preprocessor.h.
References clang::IdentifierInfo::hasMacroDefinition().
Referenced by AddMacroResults(), EvaluateDefined(), getMacroInfo(), HandleIdentifier(), and isMacroDefined().
getMacroDefinitionAtLoc()
MacroDefinition clang::Preprocessor::getMacroDefinitionAtLoc (const IdentifierInfo * II, SourceLocation Loc) inline
Definition at line 1087 of file Preprocessor.h.
References clang::MacroDirective::DefInfo::getDirective(), getSourceManager(), and clang::IdentifierInfo::hadMacroDefinition().
Referenced by isMacroDefined().
getMacroInfo() [1/2]
MacroInfo * clang::Preprocessor::getMacroInfo (const IdentifierInfo * II) inline
Definition at line 1119 of file Preprocessor.h.
References getMacroDefinition(), and clang::IdentifierInfo::hasMacroDefinition().
getMacroInfo() [2/2]
const MacroInfo * clang::Preprocessor::getMacroInfo (const IdentifierInfo * II) const inline
Definition at line 1115 of file Preprocessor.h.
References getMacroInfo().
Referenced by checkConfigMacro(), CheckMacroName(), clang::CodeCompletionResult::CreateCodeCompletionStringForMacro(), getMacroInfo(), clang::Sema::getPrintingPolicy(), HandleEndOfFile(), HandlePragmaPopMacro(), HandlePragmaPushMacro(), isTrivialSingleTokenExpansion(), and clang::ento::tryExpandAsInteger().
getMaxTokens()
unsigned clang::Preprocessor::getMaxTokens () const inline
Get the max number of tokens before issuing a -Wmax-tokens warning.
Definition at line 1032 of file Preprocessor.h.
Referenced by clang::Parser::ParseTopLevelDecl().
getMaxTokensOverrideLoc()
SourceLocation clang::Preprocessor::getMaxTokensOverrideLoc () const inline
Definition at line 1039 of file Preprocessor.h.
Referenced by clang::Parser::ParseTopLevelDecl().
getModuleForLocation()
Module * Preprocessor::getModuleForLocation (SourceLocation Loc)
Find the module that owns the source or header file that Loc points to.
If the location is in a file that was included into a module, or is outside any module, returns nullptr.
Definition at line 635 of file PPDirectives.cpp.
References clang::LangOptions::CurrentModule, clang::ModuleMap::findModuleForHeader(), getLangOpts(), clang::ModuleMap::KnownHeader::getModule(), clang::HeaderSearch::getModuleMap(), and clang::HeaderSearch::lookupModule().
Referenced by getHeaderToIncludeForDiagnostics(), and LookupFile().
getModuleImportLoc()
SourceLocation clang::Preprocessor::getModuleImportLoc (Module * M) const inline
Definition at line 1414 of file Preprocessor.h.
getModuleLoader()
ModuleLoader & clang::Preprocessor::getModuleLoader () const inline
Retrieve the module loader associated with this preprocessor.
Definition at line 944 of file Preprocessor.h.
Referenced by clang::Sema::getModuleLoader(), and clang::PCHGenerator::HandleTranslationUnit().
getModuleMacro()
ModuleMacro * Preprocessor::getModuleMacro (Module * Mod, IdentifierInfo * II)
Definition at line 173 of file PPMacroExpansion.cpp.
References clang::ModuleMacro::Profile().
getNumDirectives()
unsigned clang::Preprocessor::getNumDirectives () const inline
Retrieve the number of Directives that have been processed by the Preprocessor.
Definition at line 952 of file Preprocessor.h.
getPPCallbacks()
PPCallbacks * clang::Preprocessor::getPPCallbacks () const inline
Accessors for preprocessor callbacks.
Note that this class takes ownership of any PPCallbacks object given to it.
Definition at line 1019 of file Preprocessor.h.
Referenced by EvaluateDefined(), and EvaluateHasIncludeCommon().
getPragmaARCCFCodeAuditedInfo()
std::pair< IdentifierInfo *, SourceLocation > clang::Preprocessor::getPragmaARCCFCodeAuditedInfo () const inline
The location of the currently-active #pragma clang arc_cf_code_audited begin.
Returns an invalid location if there is no such pragma active.
Definition at line 1656 of file Preprocessor.h.
Referenced by clang::Sema::AddCFAuditedAttribute().
getPragmaAssumeNonNullLoc()
SourceLocation clang::Preprocessor::getPragmaAssumeNonNullLoc () const inline
The location of the currently-active #pragma clang assume_nonnull begin.
Returns an invalid location if there is no such pragma active.
Definition at line 1671 of file Preprocessor.h.
Referenced by GetFullTypeForDeclarator().
getPragmasEnabled()
bool clang::Preprocessor::getPragmasEnabled () const inline
Definition at line 970 of file Preprocessor.h.
getPreambleConditionalStack()
ArrayRef< PPConditionalInfo > clang::Preprocessor::getPreambleConditionalStack () const inline
Definition at line 2320 of file Preprocessor.h.
getPreambleSkipInfo()
llvm::Optional< PreambleSkipInfo > clang::Preprocessor::getPreambleSkipInfo () const inline
Definition at line 2335 of file Preprocessor.h.
getPredefines()
const std::string & clang::Preprocessor::getPredefines () const inline
Definition at line 1190 of file Preprocessor.h.
getPredefinesFileID()
FileID clang::Preprocessor::getPredefinesFileID () const inline
Returns the FileID for the preprocessor predefines.
Definition at line 1012 of file Preprocessor.h.
Referenced by checkConfigMacro(), HandleEndOfFile(), clang::RewriteIncludesInInput(), shouldIgnoreMacro(), and SkipTokensWhileUsingPCH().
getPreprocessingRecord()
PreprocessingRecord * clang::Preprocessor::getPreprocessingRecord () const inline
Retrieve the preprocessing record, or NULL if there is no preprocessing record.
Definition at line 1286 of file Preprocessor.h.
Referenced by clang::ASTUnit::getLocalPreprocessingEntities().
getPreprocessorAllocator()
llvm::BumpPtrAllocator & clang::Preprocessor::getPreprocessorAllocator () inline
Definition at line 933 of file Preprocessor.h.
Referenced by clang::ModuleMacro::create(), ParseAlignPragma(), and ParseLoopHintValue().
getPreprocessorOpts()
PreprocessorOptions & clang::Preprocessor::getPreprocessorOpts () const inline
Retrieve the preprocessor options used to initialize this preprocessor.
Definition at line 917 of file Preprocessor.h.
Referenced by clang::InitializePreprocessor(), clang::PCHValidator::ReadPreprocessorOptions(), and clang::SimpleASTReaderListener::ReadPreprocessorOptions().
getRawToken()
bool clang::Preprocessor::getRawToken (SourceLocation Loc, Token & Result, bool IgnoreWhiteSpace = false) inline
Relex the token at the specified location.
Returns
true if there was a failure, false on success.
Definition at line 1761 of file Preprocessor.h.
References clang::Lexer::getRawToken(), and clang::Result.
Referenced by UseNSOptionsMacro().
getSelectorTable()
SelectorTable & clang::Preprocessor::getSelectorTable () inline
Definition at line 931 of file Preprocessor.h.
Referenced by clang::Sema::ActOnClassPropertyRefExpr(), clang::CompilerInstance::createASTContext(), clang::Sema::HandleExprPropertyRefExpr(), clang::ASTUnit::LoadFromASTFile(), and LookupMemberExpr().
getSourceManager()
SourceManager & clang::Preprocessor::getSourceManager () const inline
Definition at line 926 of file Preprocessor.h.
Referenced by clang::Sema::ActOnNumericConstant(), AddFunctionParameterChunks(), clang::DependencyCollector::attachToPreprocessor(), clang::ModuleDependencyCollector::attachToPreprocessor(), clang::TokenConcatenation::AvoidConcat(), clang::VerifyDiagnosticConsumer::BeginSourceFile(), clang::CharLiteralParser::CharLiteralParser(), checkConfigMacro(), clang::Lexer::Create_PragmaLexer(), clang::CompilerInstance::createASTContext(), createPreprocessingRecord(), clang::DoPrintPreprocessedInput(), clang::DoRewriteTest(), emitPremigrationErrors(), EnterSourceFile(), EvaluateDefined(), EvaluateValue(), clang::DumpRawTokensAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), FindLocsWithCommonFileID(), clang::PreprocessorLexer::getFileEntry(), GetFirstChar(), getHeaderToIncludeForDiagnostics(), getMacroDefinitionAtLoc(), GetMappedTokenLoc(), clang::VerifyDiagnosticConsumer::HandleComment(), clang::TokenLexer::Init(), isExpandedFromConfigurationMacro(), IsPreviousCachedToken(), clang::TokenLexer::Lex(), LexRawTokensFromMainFile(), LookUpIdentifierInfo(), parseSimpleIntegerLiteral(), clang::PreprocessorLexer::PreprocessorLexer(), ReadLineMarkerFlags(), clang::RewriteIncludesInInput(), clang::RewriteMacrosInInput(), clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks(), shouldIgnoreMacro(), SplitToken(), and clang::syntax::TokenCollector::TokenCollector().
getSpelling() [1/4]
std::string clang::Preprocessor::getSpelling (const Token & Tok, bool * Invalid = nullptr) const inline
Return the 'spelling' of the Tok token.
The spelling of a token is the characters used to represent the token in the source file after trigraph expansion and escaped-newline folding. In particular, this wants to get the true, uncanonicalized, spelling of things like digraphs, UCNs, etc.
Parameters
Invalid If non-null, will be set true if an error occurs.
Definition at line 1730 of file Preprocessor.h.
References clang::Lexer::getSpelling(), and Tok.
getSpelling() [2/4]
unsigned clang::Preprocessor::getSpelling (const Token & Tok, const char *& Buffer, bool * Invalid = nullptr) const inline
Get the spelling of a token into a preallocated buffer, instead of as an std::string.
The caller is required to allocate enough space for the token, which is guaranteed to be at least Tok.getLength() bytes long. The length of the actual result is returned.
Note that this method may do two possible things: it may either fill in the buffer specified with characters, or it may change the input pointer to point to a constant buffer with the data already in it (avoiding a copy). The caller is not allowed to modify the returned buffer pointer if an internal buffer is returned.
Definition at line 1746 of file Preprocessor.h.
References clang::Lexer::getSpelling(), and Tok.
getSpelling() [3/4]
StringRef Preprocessor::getSpelling (const Token & Tok, SmallVectorImpl< char > & Buffer, bool * Invalid = nullptr) const
Get the spelling of a token into a SmallVector.
getSpelling - This method is used to get the spelling of a token into a SmallVector.
Note that the returned StringRef may not point to the supplied buffer if a copy can be avoided.
Definition at line 459 of file Preprocessor.cpp.
References clang::Token::getIdentifierInfo(), clang::Token::getLength(), getSpelling(), clang::Token::hasUCN(), clang::Token::isNot(), clang::Token::needsCleaning(), and Tok.
getSpelling() [4/4]
StringRef clang::Preprocessor::getSpelling (SourceLocation loc, SmallVectorImpl< char > & buffer, bool * invalid = nullptr) const inline
Return the 'spelling' of the token at the given location; does not go up to the spelling location or down to the expansion location.
Parameters
buffer A buffer which will be used only if the token requires "cleaning", e.g. if it contains trigraphs or escaped newlines
invalid If non-null, will be set true if an error occurs.
Definition at line 1716 of file Preprocessor.h.
References clang::Lexer::getSpelling().
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnNumericConstant(), buildMSAsmString(), clang::DoRewriteTest(), DumpToken(), EvaluateHasIncludeCommon(), EvaluateValue(), GetFirstChar(), GetLineValue(), getSpelling(), HandlePragmaDependency(), HandlePragmaIncludeAlias(), clang::MacroInfo::isIdenticalTo(), isMapModifier(), isMapType(), LexHeaderName(), LookUpIdentifierInfo(), clang::Parser::ParseOpenMPVarList(), ParsePragmaPushOrPopMacro(), parseSimpleIntegerLiteral(), PrintMacroDefinition(), PrintPreprocessedTokens(), clang::RewriteMacrosInInput(), and clang::MacroArgs::StringifyArgument().
getSpellingOfSingleCharacterNumericConstant()
char clang::Preprocessor::getSpellingOfSingleCharacterNumericConstant (const Token & Tok, bool * Invalid = nullptr) const inline
Given a Token Tok that is a numeric constant with length 1, return the character.
Definition at line 1769 of file Preprocessor.h.
References Tok.
Referenced by clang::Sema::ActOnNumericConstant().
GetSuppressIncludeNotFoundError()
bool clang::Preprocessor::GetSuppressIncludeNotFoundError () inline
Definition at line 976 of file Preprocessor.h.
getTargetInfo()
const TargetInfo & clang::Preprocessor::getTargetInfo () const inline
Definition at line 923 of file Preprocessor.h.
Referenced by clang::Sema::ActOnNumericConstant(), clang::CharLiteralParser::CharLiteralParser(), EvaluateValue(), clang::Parser::getTargetInfo(), clang::InitializePreprocessor(), parseSimpleIntegerLiteral(), and clang::PCHValidator::ReadTargetOptions().
getTokenCount()
unsigned clang::Preprocessor::getTokenCount () const inline
Get the number of tokens processed so far.
Definition at line 1029 of file Preprocessor.h.
Referenced by clang::Parser::ParseTopLevelDecl().
getTotalMemory()
size_t Preprocessor::getTotalMemory () const
Definition at line 321 of file Preprocessor.cpp.
Referenced by PrintStats().
hadModuleLoaderFatalFailure()
bool clang::Preprocessor::hadModuleLoaderFatalFailure () const inline
Definition at line 946 of file Preprocessor.h.
References clang::ModuleLoader::HadFatalFailure.
HandleComment()
bool Preprocessor::HandleComment (Token & result, SourceRange Comment)
Definition at line 1396 of file Preprocessor.cpp.
References getCommentRetentionState(), and Lex().
HandleDirective()
void Preprocessor::HandleDirective (Token & Result)
Callback invoked when the lexer sees a # token at the start of a line.
HandleDirective - This callback is invoked when the lexer sees a # token at the start of a line.
This consumes the directive, modifies the lexer/preprocessor state, and advances the lexer(s) so that the next token read is the correct one.
Definition at line 903 of file PPDirectives.cpp.
References clang::CodeCompletionHandler::CodeCompleteDirective(), Diag(), DiscardUntilEndOfDirective(), clang::PreprocessorLexer::getConditionalStackDepth(), clang::MultipleIncludeOpt::getHasReadAnyTokensVal(), clang::Token::getIdentifierInfo(), clang::MultipleIncludeOpt::getImmediatelyAfterTopLevelIfndef(), getLangOpts(), clang::Token::getLocation(), clang::IdentifierInfo::getPPKeywordID(), HandleSkippedDirectiveWhileUsingPCH(), LexUnexpandedToken(), clang::PreprocessorLexer::MIOpt, clang::PreprocessorLexer::ParsingPreprocessorDirective, clang::PIK_HashPragma, clang::MultipleIncludeOpt::resetImmediatelyAfterTopLevelIfndef(), clang::Result, setCodeCompletionReached(), and clang::Token::setKind().
HandleEndOfFile()
bool Preprocessor::HandleEndOfFile (Token & Result, bool isEndOfMacro = false)
Callback invoked when the lexer hits the end of the current file.
HandleEndOfFile - This callback is invoked when the lexer hits the end of the current file.
This either returns the EOF token and returns true, or pops a level off the include stack and returns false, at which point the client should call lex again.
This either returns the EOF token or pops a level off the include stack and keeps going.
Definition at line 305 of file PPLexerChange.cpp.
References collectAllSubModulesWithUmbrellaHeader(), clang::FixItHint::CreateReplacement(), creatingPCHWithThroughHeader(), Diag(), clang::PPCallbacks::ExitFile, clang::HeaderSearch::FirstTimeLexingFile(), clang::MultipleIncludeOpt::GetControllingMacroAtEndOfFile(), getCurrentModule(), clang::MultipleIncludeOpt::GetDefinedLocation(), clang::MultipleIncludeOpt::GetDefinedMacro(), clang::PreprocessorLexer::getFileEntry(), clang::PreprocessorLexer::getFileID(), clang::PreprocessorLexer::getInitialNumSLocEntries(), getMacroInfo(), clang::MultipleIncludeOpt::GetMacroLocation(), getPredefinesFileID(), clang::PreprocessorLexer::getSourceLocation(), isCodeCompletionEnabled(), isIncrementalProcessingEnabled(), isInPrimaryFile(), isMacroDefined(), isPCHThroughHeader(), clang::FileID::isValid(), clang::SourceLocation::isValid(), LeaveSubmodule(), clang::PreprocessorLexer::MIOpt, recomputeCurLexerKind(), RemoveTopOfLexerStack(), clang::Result, clang::HeaderSearch::SetFileControllingMacro(), and clang::TU_Complete.
Referenced by HandleEndOfTokenLexer().
HandleEndOfTokenLexer()
bool Preprocessor::HandleEndOfTokenLexer (Token & Result)
Callback invoked when the current TokenLexer hits the end of its token stream.
HandleEndOfTokenLexer - This callback is invoked when the current TokenLexer hits the end of its token stream.
Definition at line 548 of file PPLexerChange.cpp.
References HandleEndOfFile(), and clang::Result.
Referenced by HandleMicrosoftCommentPaste(), and clang::TokenLexer::Lex().
HandleIdentifier()
bool Preprocessor::HandleIdentifier (Token & Identifier)
Callback invoked when the lexer reads an identifier and has filled in the tokens IdentifierInfo member.
HandleIdentifier - This callback is invoked when the lexer reads an identifier.
This callback potentially macro expands it or turns it into a named token (like 'for').
Returns
true if we actually computed a token, false if we need to lex again.
This callback looks up the identifier in the map and/or potentially macro expands it or turns it into a named token (like 'for').
Note that callers of this method are guarded by checking the IdentifierInfo's 'isHandleIdentifierCase' bit. If this method changes, the IdentifierInfo methods that compute these properties will need to change to match.
Definition at line 794 of file Preprocessor.cpp.
References Diag(), clang::Token::DisableExpand, getFutureCompatDiagKind(), getLangOpts(), getMacroDefinition(), clang::IdentifierInfo::getName(), clang::IdentifierInfo::getTokenID(), HandlePoisonedIdentifier(), Identifier, clang::IdentifierInfo::isExtensionToken(), clang::IdentifierInfo::isFutureCompatKeyword(), clang::IdentifierInfo::isModulesImport(), clang::IdentifierInfo::isOutOfDate(), clang::IdentifierInfo::isPoisoned(), clang::IdentifierInfo::setIsFutureCompatKeyword(), and clang::IdentifierInfo::setIsPoisoned().
Referenced by clang::TokenLexer::Lex().
HandleMicrosoftCommentPaste()
void Preprocessor::HandleMicrosoftCommentPaste (Token & Tok)
When the macro expander pastes together a comment (/##/) in Microsoft mode, this method handles updating the current state, returning the token on the next source line.
HandleMicrosoftCommentPaste - When the macro expander pastes together a comment (/##/) in microsoft mode, this method handles updating the current state, returning the token on the next source line.
Definition at line 586 of file PPLexerChange.cpp.
References HandleEndOfTokenLexer(), clang::Token::is(), clang::Token::isNot(), Lex(), clang::PreprocessorLexer::LexingRawMode, clang::PreprocessorLexer::ParsingPreprocessorDirective, and Tok.
HandlePoisonedIdentifier()
void Preprocessor::HandlePoisonedIdentifier (Token & Identifier)
Display reason for poisoned identifier.
Definition at line 747 of file Preprocessor.cpp.
References Diag(), and Identifier.
Referenced by HandleIdentifier(), clang::TokenLexer::Lex(), and MaybeHandlePoisonedIdentifier().
HandlePragmaDependency()
void Preprocessor::HandlePragmaDependency (Token & DependencyTok)
HandlePragmaDependency - Handle #pragma GCC dependency "foo" blah.
Definition at line 495 of file Pragma.cpp.
References Diag(), clang::File, Filename, getCurrentFileLexer(), clang::PreprocessorLexer::getFileEntry(), GetIncludeFilenameSpelling(), clang::Token::getLocation(), clang::FileEntry::getModificationTime(), getSpelling(), clang::Token::isNot(), Lex(), LexHeaderName(), and LookupFile().
HandlePragmaHdrstop()
void Preprocessor::HandlePragmaHdrstop (Token & Tok)
Definition at line 861 of file Pragma.cpp.
References creatingPCHWithPragmaHdrStop(), Diag(), clang::Token::getLocation(), clang::Token::is(), clang::Token::isNot(), Lex(), LexStringLiteral(), clang::Result, clang::Token::startToken(), Tok, and usingPCHWithPragmaHdrStop().
Referenced by HandleSkippedDirectiveWhileUsingPCH().
HandlePragmaIncludeAlias()
void Preprocessor::HandlePragmaIncludeAlias (Token & Tok)
Definition at line 665 of file Pragma.cpp.
References clang::HeaderSearch::AddIncludeAlias(), Diag(), getHeaderSearchInfo(), GetIncludeFilenameSpelling(), clang::Token::getLocation(), getSpelling(), clang::Token::is(), clang::Token::isNot(), Lex(), LexHeaderName(), and Tok.
HandlePragmaMark()
void Preprocessor::HandlePragmaMark ()
Definition at line 415 of file Pragma.cpp.
HandlePragmaModuleBuild()
void Preprocessor::HandlePragmaModuleBuild (Token & Tok)
Definition at line 787 of file Pragma.cpp.
References clang::ModuleLoader::createModuleFromSource(), Diag(), DiscardUntilEndOfDirective(), clang::Token::getKind(), clang::Token::getLocation(), clang::IdentifierInfo::getName(), clang::Token::getRawIdentifier(), clang::Token::is(), clang::Token::isAtStartOfLine(), clang::Token::isNot(), LexModuleNameComponent(), LexUnexpandedToken(), NestingLevel, and Tok.
HandlePragmaOnce()
void Preprocessor::HandlePragmaOnce (Token & OnceTok)
HandlePragmaOnce - Handle #pragma once. OnceTok is the 'once'.
Definition at line 400 of file Pragma.cpp.
References Diag(), getCurrentFileLexer(), getLangOpts(), isInPrimaryFile(), clang::HeaderSearch::MarkFileIncludeOnce(), and clang::TU_Prefix.
HandlePragmaPoison()
void Preprocessor::HandlePragmaPoison ()
HandlePragmaPoison - Handle #pragma GCC poison. PoisonTok is the 'poison'.
Definition at line 421 of file Pragma.cpp.
References Diag(), clang::Token::is(), clang::IdentifierInfo::isFromAST(), isMacroDefined(), clang::Token::isNot(), clang::IdentifierInfo::isPoisoned(), clang::PreprocessorLexer::LexingRawMode, LexUnexpandedToken(), LookUpIdentifierInfo(), clang::IdentifierInfo::setChangedSinceDeserialization(), clang::IdentifierInfo::setIsPoisoned(), and Tok.
HandlePragmaPopMacro()
void Preprocessor::HandlePragmaPopMacro (Token & PopMacroTok)
Handle #pragma pop_macro.
The syntax is:
#pragma pop_macro("macro")
Definition at line 630 of file Pragma.cpp.
References appendDefMacroDirective(), appendMacroDirective(), Diag(), clang::Token::getLocation(), getMacroInfo(), clang::IdentifierInfo::getName(), and ParsePragmaPushOrPopMacro().
HandlePragmaPushMacro()
void Preprocessor::HandlePragmaPushMacro (Token & PushMacroTok)
Handle #pragma push_macro.
The syntax is:
#pragma push_macro("macro")
Definition at line 607 of file Pragma.cpp.
References getMacroInfo(), ParsePragmaPushOrPopMacro(), and clang::MacroInfo::setIsAllowRedefinitionsWithoutWarning().
HandlePragmaSystemHeader()
void Preprocessor::HandlePragmaSystemHeader (Token & SysHeaderTok)
HandlePragmaSystemHeader - Implement #pragma GCC system_header.
We know that the whole directive has been parsed.
Definition at line 463 of file Pragma.cpp.
References clang::SrcMgr::C_System, Diag(), getCurrentFileLexer(), clang::PreprocessorLexer::getFileEntry(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::Token::getLocation(), isInPrimaryFile(), clang::PresumedLoc::isInvalid(), clang::HeaderSearch::MarkFileSystemHeader(), and clang::PPCallbacks::SystemHeaderPragma.
HandleSkippedDirectiveWhileUsingPCH()
void Preprocessor::HandleSkippedDirectiveWhileUsingPCH (Token & Result, SourceLocation HashLoc)
Process directives while skipping until the through header or #pragma hdrstop is found.
Process a directive while looking for the through header or a #pragma hdrstop.
The following directives are handled: #include (to check if it is the through header) #define (to warn about macros that don't match the PCH) #pragma (to check for pragma hdrstop). All other directives are completely discarded.
Definition at line 878 of file PPDirectives.cpp.
References DiscardUntilEndOfDirective(), HandlePragmaHdrstop(), Lex(), and clang::Result.
Referenced by HandleDirective().
hasRecordedPreamble()
bool clang::Preprocessor::hasRecordedPreamble () const inline
Definition at line 2316 of file Preprocessor.h.
IgnorePragmas()
void Preprocessor::IgnorePragmas ()
Install empty handlers for all pragmas (making them ignored).
Ignore all pragmas, useful for modes such as -Eonly which would otherwise warn about those pragmas being unknown.
Definition at line 1918 of file Pragma.cpp.
References AddPragmaHandler().
Referenced by DoPrintMacros(), clang::PreprocessOnlyAction::ExecuteAction(), and clang::RewriteIncludesInInput().
IncrementPasteCounter()
void clang::Preprocessor::IncrementPasteCounter (bool isFast) inline
Increment the counters for the number of token paste operations performed.
If fast was specified, this is a 'fast paste' case we handled.
Definition at line 1867 of file Preprocessor.h.
Initialize()
void Preprocessor::Initialize (const TargetInfo & Target, const TargetInfo * AuxTarget = nullptr)
Initialize the preprocessor using information about the target.
Parameters
Target is owned by the caller and must remain valid for the lifetime of the preprocessor.
AuxTarget is owned by the caller and must remain valid for the lifetime of the preprocessor.
Definition at line 195 of file Preprocessor.cpp.
References clang::IdentifierTable::AddKeywords(), and clang::HeaderSearch::setTarget().
InitializeForModelFile()
void Preprocessor::InitializeForModelFile ()
Initialize the preprocessor to parse a model file.
To parse model files the preprocessor of the original source is reused to preserver the identifier table. However to avoid some duplicate information in the preprocessor some cleanup is needed before it is used to parse model files. This method does that cleanup.
Definition at line 213 of file Preprocessor.cpp.
isAtEndOfMacroExpansion()
bool clang::Preprocessor::isAtEndOfMacroExpansion (SourceLocation loc, SourceLocation * MacroEnd = nullptr) const inline
Returns true if the given MacroID location points at the last token of the macro expansion.
Parameters
MacroEnd If non-null and function returns true, it is set to end location of the macro.
Definition at line 1845 of file Preprocessor.h.
References clang::Lexer::isAtEndOfMacroExpansion().
isAtStartOfMacroExpansion()
bool clang::Preprocessor::isAtStartOfMacroExpansion (SourceLocation loc, SourceLocation * MacroBegin = nullptr) const inline
Returns true if the given MacroID location points at the first token of the macro expansion.
Parameters
MacroBegin If non-null and function returns true, it is set to begin location of the macro.
Definition at line 1834 of file Preprocessor.h.
References clang::Lexer::isAtStartOfMacroExpansion().
isBacktrackEnabled()
bool clang::Preprocessor::isBacktrackEnabled () const inline
True if EnableBacktrackAtThisPos() was called and caching of tokens is on.
Definition at line 1401 of file Preprocessor.h.
Referenced by AnnotateCachedTokens(), ReplaceLastTokenWithAnnotation(), RevertCachedTokens(), and TypoCorrectToken().
isCodeCompletionEnabled()
bool clang::Preprocessor::isCodeCompletionEnabled () const inline
Determine if we are performing code completion.
Definition at line 1623 of file Preprocessor.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnFinishFunctionBody(), EnterSourceFile(), HandleEndOfFile(), clang::Parser::Parser(), and setCodeCompletionReached().
isCodeCompletionReached()
bool clang::Preprocessor::isCodeCompletionReached () const inline
Returns true if code-completion is enabled and we have hit the code-completion point.
Definition at line 1641 of file Preprocessor.h.
isCurrentLexer()
bool clang::Preprocessor::isCurrentLexer (const PreprocessorLexer * L) const inline
Return true if we are lexing directly from the specified lexer.
Definition at line 991 of file Preprocessor.h.
isIncrementalProcessingEnabled()
bool clang::Preprocessor::isIncrementalProcessingEnabled () const inline
Returns true if incremental processing is enabled.
Definition at line 1598 of file Preprocessor.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), HandleEndOfFile(), and clang::Parser::ParseTopLevelDecl().
isInPrimaryFile()
bool Preprocessor::isInPrimaryFile () const
Return true if we're in the top-level file, not in a #include.
isInPrimaryFile - Return true if we're in the top-level file, not in a #include.
This looks through macro expansions and active _Pragma lexers.
Definition at line 33 of file PPLexerChange.cpp.
Referenced by EvaluateHasIncludeNext(), HandleEndOfFile(), HandlePragmaOnce(), and HandlePragmaSystemHeader().
isMacroDefined() [1/2]
bool clang::Preprocessor::isMacroDefined (const IdentifierInfo * II) inline
Definition at line 1053 of file Preprocessor.h.
References bool, getLangOpts(), getMacroDefinition(), and clang::IdentifierInfo::hasMacroDefinition().
isMacroDefined() [2/2]
bool clang::Preprocessor::isMacroDefined (StringRef Id) inline
Definition at line 1050 of file Preprocessor.h.
References clang::IdentifierTable::get(), Id, and isMacroDefined().
Referenced by AddOrdinaryNameResults(), clang::Sema::CheckPtrComparisonWithNullChar(), clang::Sema::DiagnoseSentinelCalls(), diagnoseXorMisusedAsPow(), DoEmitAvailabilityWarning(), clang::arcmt::trans::getNilString(), HandleEndOfFile(), HandlePragmaPoison(), isMacroDefined(), MaybeAddSentinel(), and clang::HeaderSearch::ShouldEnterIncludeFile().
isMacroDefinedInLocalModule()
bool clang::Preprocessor::isMacroDefinedInLocalModule (const IdentifierInfo * II, Module * M) inline
Determine whether II is defined as a macro within the module M, if that is a module that we've already preprocessed.
Does not check for macros imported into M.
Definition at line 1061 of file Preprocessor.h.
References clang::IdentifierInfo::hasMacroDefinition().
Referenced by clang::HeaderSearch::ShouldEnterIncludeFile().
isParsingIfOrElifDirective()
bool clang::Preprocessor::isParsingIfOrElifDirective () const inline
True if we are currently preprocessing a if or #elif directive.
Definition at line 957 of file Preprocessor.h.
Referenced by EvaluateHasIncludeCommon().
isPCHThroughHeader()
bool Preprocessor::isPCHThroughHeader (const FileEntry * FE)
Returns true if the FileEntry is the PCH through header.
Definition at line 597 of file Preprocessor.cpp.
References clang::FileID::isValid().
Referenced by HandleEndOfFile().
isPreprocessedOutput()
bool clang::Preprocessor::isPreprocessedOutput () const inline
Returns true if the preprocessor is responsible for generating output, false if it is producing tokens to be consumed by Parse and Sema.
Definition at line 988 of file Preprocessor.h.
IsPreviousCachedToken()
bool Preprocessor::IsPreviousCachedToken (const Token & Tok) const
Whether Tok is the most recent token (CachedLexPos - 1) in CachedTokens.
Definition at line 139 of file PPCaching.cpp.
References clang::Token::getKind(), getLastCachedTokenLocation(), clang::Token::getLocation(), getSourceManager(), and Tok.
isRecordingPreamble()
bool clang::Preprocessor::isRecordingPreamble () const inline
Definition at line 2312 of file Preprocessor.h.
LeaveSubmodule()
Module * Preprocessor::LeaveSubmodule (bool ForPragma)
Definition at line 723 of file PPLexerChange.cpp.
References addModuleMacro(), getLangOpts(), clang::MacroDirective::getPrevious(), clang::Module::getTopLevelModuleName(), and makeModuleVisible().
Referenced by HandleEndOfFile().
Lex()
void Preprocessor::Lex (Token & Result)
Lex the next token for this preprocessor.
Definition at line 886 of file Preprocessor.cpp.
References getLangOpts(), clang::ModuleLoader::HadFatalFailure, clang::Token::IsReinjected, LexAfterModuleImport(), clang::Result, setCodeCompletionIdentifierInfo(), and setCodeCompletionTokenRange().
Referenced by CheckEndOfDirective(), CollectPpImportSuffix(), clang::Parser::ConsumeToken(), DoPrintMacros(), clang::DoPrintPreprocessedInput(), clang::DumpTokensAction::ExecuteAction(), clang::PreprocessOnlyAction::ExecuteAction(), clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction(), FinishLexStringLiteral(), FixDigraph(), clang::MacroArgs::getPreExpArgument(), HandleComment(), HandleMicrosoftCommentPaste(), HandlePragmaDependency(), HandlePragmaHdrstop(), HandlePragmaIncludeAlias(), HandleSkippedDirectiveWhileUsingPCH(), LexAfterModuleImport(), LexHeaderName(), clang::PreprocessorLexer::LexIncludeFilename(), LexNonComment(), LexStringLiteral(), LexUnexpandedToken(), ParseAlignPragma(), ParseLoopHintValue(), ParsePragmaPushOrPopMacro(), parseSimpleIntegerLiteral(), PrintPreprocessedTokens(), ReadLineMarkerFlags(), clang::RewriteIncludesInInput(), clang::RewriteMacrosInInput(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryConsumeToken().
LexAfterModuleImport()
bool Preprocessor::LexAfterModuleImport (Token & Result)
Lex a token following the 'import' contextual keyword.
pp-import: [C++20]
      import header-name pp-import-suffix[opt] ;
      import header-name-tokens pp-import-suffix[opt] ;
[ObjC] @ import module-name ; [Clang] import module-name ;
header-name-tokens:
      string-literal
      < [any sequence of preprocessing-tokens other than >] >
module-name:
      module-name-qualifier[opt] identifier
module-name-qualifier
      module-name-qualifier[opt] identifier .
We respond to a pp-import by importing macros from the named module.
Definition at line 1129 of file Preprocessor.cpp.
References CollectPpImportSuffix(), Diag(), getIdentifierInfo(), getLangOpts(), clang::ModuleLoader::HadFatalFailure, clang::Module::Hidden, clang::SourceLocation::isMacroID(), Lex(), LexHeaderName(), clang::ModuleLoader::loadModule(), makeModuleVisible(), recomputeCurLexerKind(), clang::Result, clang::Token::setIdentifierInfo(), clang::Token::setKind(), clang::Token::setLength(), clang::Token::setLocation(), and clang::Token::startToken().
Referenced by Lex(), and SkipTokensWhileUsingPCH().
LexHeaderName()
bool Preprocessor::LexHeaderName (Token & FilenameTok, bool AllowMacroExpansion = true)
Lex a token, forming a header-name token if possible.
Lex a header-name token (including one formed from header-name-tokens if AllowConcatenation is true).
Parameters
FilenameTok Filled in with the next token. On success, this will be either a header_name token. On failure, it will be whatever other token was found instead.
AllowMacroExpansion If true, allow the header name to be formed by macro expansion (concatenating tokens as necessary if the first token is a '<').
Returns
true if we reached EOD or EOF while looking for a > token in a concatenated header name and diagnosed it. false otherwise.
Definition at line 986 of file Preprocessor.cpp.
References CreateString(), Diag(), clang::Token::getLength(), clang::Token::getLocation(), getSpelling(), clang::Token::hasLeadingEmptyMacro(), clang::Token::hasLeadingSpace(), clang::Token::is(), clang::Token::isAtStartOfLine(), clang::Token::isNot(), clang::Token::isOneOf(), clang::Token::LeadingEmptyMacro, clang::Token::LeadingSpace, Lex(), clang::PreprocessorLexer::LexIncludeFilename(), memcpy(), setCodeCompletionReached(), clang::Token::setFlagValue(), clang::Token::setKind(), clang::Token::StartOfLine, and clang::Token::startToken().
Referenced by EvaluateHasIncludeCommon(), HandlePragmaDependency(), HandlePragmaIncludeAlias(), and LexAfterModuleImport().
LexNonComment()
void clang::Preprocessor::LexNonComment (Token & Result) inline
Lex a token.
If it's a comment, keep lexing until we get something not a comment.
This is useful in -E -C mode where comments would foul up preprocessor directive handling.
Definition at line 1442 of file Preprocessor.h.
References Lex(), and clang::Result.
Referenced by EvaluateDefined(), EvaluateDirectiveSubExpr(), EvaluateHasIncludeCommon(), and EvaluateValue().
LexOnOffSwitch()
bool Preprocessor::LexOnOffSwitch (tok::OnOffSwitch & Result)
Lex an on-off-switch (C99 6.10.6p2) and verify that it is followed by EOD.
Return true if the token is not a valid on-off-switch.
Definition at line 948 of file Pragma.cpp.
References Diag(), clang::Token::getIdentifierInfo(), clang::Token::isNot(), clang::IdentifierInfo::isStr(), LexUnexpandedToken(), clang::tok::OOS_DEFAULT, clang::tok::OOS_OFF, clang::tok::OOS_ON, clang::Result, and Tok.
LexStringLiteral()
bool clang::Preprocessor::LexStringLiteral (Token & Result, std::string & String, const char * DiagnosticTag, bool AllowMacroExpansion) inline
Lex a string literal, which may be the concatenation of multiple string literals and may even come from macro expansion.
Returns
true on success, false if a error diagnostic has been generated.
Definition at line 1421 of file Preprocessor.h.
References FinishLexStringLiteral(), Lex(), LexUnexpandedToken(), and clang::Result.
Referenced by HandlePragmaHdrstop().
LexUnexpandedNonComment()
void clang::Preprocessor::LexUnexpandedNonComment (Token & Result) inline
Like LexNonComment, but this disables macro expansion of identifier tokens.
Definition at line 1462 of file Preprocessor.h.
References LexUnexpandedToken(), and clang::Result.
Referenced by EvaluateDefined().
LexUnexpandedToken()
void clang::Preprocessor::LexUnexpandedToken (Token & Result) inline
Just like Lex, but disables macro expansion of identifier tokens.
Definition at line 1449 of file Preprocessor.h.
References Lex(), and clang::Result.
Referenced by CheckEndOfDirective(), DiscardUntilEndOfDirective(), EvaluateFeatureLikeBuiltinMacro(), FinishLexStringLiteral(), HandleDirective(), clang::PragmaNamespace::HandlePragma(), HandlePragmaModuleBuild(), HandlePragmaPoison(), LexModuleName(), LexModuleNameComponent(), LexOnOffSwitch(), LexStringLiteral(), and LexUnexpandedNonComment().
LookAhead()
const Token & clang::Preprocessor::LookAhead (unsigned N) inline
Peeks ahead N tokens and returns that token without consuming any tokens.
LookAhead(0) returns the next token that would be returned by Lex(), LookAhead(1) returns the token after it, etc. This returns normal tokens after phase 5. As such, it is equivalent to using 'Lex', not 'LexUnexpandedToken'.
Definition at line 1486 of file Preprocessor.h.
References N.
Referenced by clang::Parser::NextToken(), clang::Parser::parseMapTypeModifiers(), and clang::Parser::ParseOpenMPVarList().
LookupFile()
Optional< FileEntryRef > Preprocessor::LookupFile (SourceLocation FilenameLoc, StringRef Filename, bool isAngled, const DirectoryLookup * FromDir, const FileEntry * FromFile, const DirectoryLookup *& CurDir, SmallVectorImpl< char > * SearchPath, SmallVectorImpl< char > * RelativePath, ModuleMap::KnownHeader * SuggestedModule, bool * IsMapped, bool * IsFrameworkFound, bool SkipCache = false)
Given a "foo" or <foo> reference, look up the indicated file.
Returns None on failure. isAngled indicates whether the file reference is for system #include's or not (i.e. using <> instead of "").
Definition at line 722 of file PPDirectives.cpp.
References clang::ModuleMap::diagnoseHeaderInclusion(), Filename, getCurrentFileLexer(), getCurrentModule(), clang::FileEntry::getDir(), clang::FileManager::getDirectory(), clang::PreprocessorLexer::getFileEntry(), clang::PreprocessorLexer::getFileID(), getModuleForLocation(), clang::HeaderSearch::getModuleMap(), clang::Module::IsSystem, clang::HeaderSearch::LookupFile(), clang::HeaderSearch::LookupSubframeworkHeader(), and clang::None.
Referenced by EnterMainSourceFile(), EvaluateHasIncludeCommon(), HandlePragmaDependency(), and ParseDirective().
LookUpIdentifierInfo()
IdentifierInfo * Preprocessor::LookUpIdentifierInfo (Token & Identifier) const
Given a tok::raw_identifier token, look up the identifier information for the token and install it into the token, updating the token kind accordingly.
LookUpIdentifierInfo - Given a tok::raw_identifier token, look up the identifier information for the token and install it into the token, updating the token kind accordingly.
Definition at line 696 of file Preprocessor.cpp.
References clang::expandUCNs(), getIdentifierInfo(), getLangOpts(), getSourceManager(), getSpelling(), clang::IdentifierInfo::getTokenID(), Identifier, and clang::IdentifierInfo::isCPlusPlusOperatorKeyword().
Referenced by HandlePragmaPoison(), LexRawTokensFromMainFile(), and ParsePragmaPushOrPopMacro().
macro_begin()
Preprocessor::macro_iterator Preprocessor::macro_begin (bool IncludeExternalMacros = true) const
Definition at line 307 of file Preprocessor.cpp.
References clang::ExternalPreprocessorSource::ReadDefinedMacros().
Referenced by AddMacroResults(), DoPrintMacros(), getLastMacroWithSpelling(), and macros().
macro_end()
Preprocessor::macro_iterator Preprocessor::macro_end (bool IncludeExternalMacros = true) const
Definition at line 334 of file Preprocessor.cpp.
References clang::ExternalPreprocessorSource::ReadDefinedMacros().
Referenced by AddMacroResults(), DoPrintMacros(), getLastMacroWithSpelling(), and macros().
macros()
llvm::iterator_range< macro_iterator > clang::Preprocessor::macros (bool IncludeExternalMacros = true) const inline
Definition at line 1176 of file Preprocessor.h.
References macro_begin(), and macro_end().
Referenced by indexPreprocessorMacros().
makeModuleVisible()
void Preprocessor::makeModuleVisible (Module * M, SourceLocation Loc)
Definition at line 1304 of file Preprocessor.cpp.
References Diag(), and clang::VisibleModuleSet::setVisible().
Referenced by EnterSubmodule(), LeaveSubmodule(), and LexAfterModuleImport().
markMacroAsUsed()
void Preprocessor::markMacroAsUsed (MacroInfo * MI)
A macro is used, update information about macros that need unused warnings.
Definition at line 1868 of file PPMacroExpansion.cpp.
References clang::MacroInfo::getDefinitionLoc(), clang::MacroInfo::isUsed(), clang::MacroInfo::isWarnIfUnused(), and clang::MacroInfo::setIsUsed().
Referenced by EvaluateDefined().
MaybeHandlePoisonedIdentifier()
void clang::Preprocessor::MaybeHandlePoisonedIdentifier (Token & Identifier) inline
Definition at line 1905 of file Preprocessor.h.
References HandlePoisonedIdentifier(), and Identifier.
mightHavePendingAnnotationTokens()
bool clang::Preprocessor::mightHavePendingAnnotationTokens () inline
Determine whether it's possible for a future call to Lex to produce an annotation token created by a previous call to EnterAnnotationToken.
Definition at line 1581 of file Preprocessor.h.
overrideMaxTokens()
void clang::Preprocessor::overrideMaxTokens (unsigned Value, SourceLocation Loc) inline
Definition at line 1034 of file Preprocessor.h.
ParsePragmaPushOrPopMacro()
IdentifierInfo * Preprocessor::ParsePragmaPushOrPopMacro (Token & Tok)
ParsePragmaPushOrPopMacro - Handle parsing of pragma push_macro/pop_macro.
Return the IdentifierInfo* associated with the macro to push or pop.
Definition at line 552 of file Pragma.cpp.
References CreateString(), Diag(), clang::Token::getLocation(), getSpelling(), clang::Token::hasUDSuffix(), clang::Token::isNot(), Lex(), LookUpIdentifierInfo(), clang::Token::setKind(), clang::Token::startToken(), and Tok.
Referenced by HandlePragmaPopMacro(), and HandlePragmaPushMacro().
parseSimpleIntegerLiteral()
bool Preprocessor::parseSimpleIntegerLiteral (Token & Tok, uint64_t & Value)
Parses a simple integer literal to get its numeric value.
Floating point literals and user defined literals are rejected. Used primarily to handle pragmas that accept integer arguments.
Definition at line 1362 of file Preprocessor.cpp.
References getDiagnostics(), clang::NumericLiteralParser::GetIntegerValue(), getLangOpts(), clang::Token::getLocation(), getSourceManager(), getSpelling(), getTargetInfo(), clang::NumericLiteralParser::hadError, clang::NumericLiteralParser::hasUDSuffix(), clang::Token::is(), clang::NumericLiteralParser::isIntegerLiteral(), Lex(), and Tok.
PoisonSEHIdentifiers()
void Preprocessor::PoisonSEHIdentifiers (bool Poison = true)
Definition at line 733 of file Preprocessor.cpp.
References clang::IdentifierInfo::setIsPoisoned().
PrintStats()
void Preprocessor::PrintStats ()
Definition at line 268 of file Preprocessor.cpp.
References getTotalMemory().
Referenced by clang::FrontendAction::EndSourceFile().
recomputeCurLexerKind()
void Preprocessor::recomputeCurLexerKind ()
Recompute the current lexer kind based on the CurLexer/ CurTokenLexer pointers.
Definition at line 378 of file Preprocessor.cpp.
Referenced by Backtrack(), HandleEndOfFile(), and LexAfterModuleImport().
removeCommentHandler()
void Preprocessor::removeCommentHandler (CommentHandler * Handler)
Remove the specified comment handler.
It is an error to remove a handler that has not been registered.
Definition at line 1389 of file Preprocessor.cpp.
Referenced by clang::Parser::~Parser().
RemovePragmaHandler() [1/2]
void clang::Preprocessor::RemovePragmaHandler (PragmaHandler * Handler) inline
Definition at line 1219 of file Preprocessor.h.
References RemovePragmaHandler().
RemovePragmaHandler() [2/2]
void Preprocessor::RemovePragmaHandler (StringRef Namespace, PragmaHandler * Handler)
Remove the specific pragma handler from this preprocessor.
RemovePragmaHandler - Remove the specific pragma handler from the preprocessor.
If Namespace is non-null, then it should be the namespace that Handler was added to. It is an error to remove a handler that has not been registered.
If
Namespace is non-null, then it should be the namespace that
Handler was added to. It is an error to remove a handler that has not been registered.
Definition at line 926 of file Pragma.cpp.
References clang::PragmaHandler::getIfNamespace(), clang::PragmaNamespace::IsEmpty(), and clang::PragmaNamespace::RemovePragmaHandler().
Referenced by clang::DoPrintPreprocessedInput(), and RemovePragmaHandler().
RemoveTopOfLexerStack()
void Preprocessor::RemoveTopOfLexerStack ()
Pop the current lexer/macro exp off the top of the lexer stack.
RemoveTopOfLexerStack - Pop the current lexer/macro exp off the top of the lexer stack.
This should only be used in situations where the current state of the top-of-stack lexer is known.
This should only be used in situations where the current state of the top-of-stack lexer is unknown.
Definition at line 569 of file PPLexerChange.cpp.
Referenced by clang::MacroArgs::getPreExpArgument(), and HandleEndOfFile().
ReplaceLastTokenWithAnnotation()
void clang::Preprocessor::ReplaceLastTokenWithAnnotation (const Token & Tok) inline
Replace the last token with an annotation token.
Like AnnotateCachedTokens(), this routine replaces an already-parsed (and resolved) token with an annotation token. However, this routine only replaces the last token with the annotation token; it does not affect any other cached tokens. This function has no effect if backtracking is not enabled.
Definition at line 1569 of file Preprocessor.h.
References isBacktrackEnabled(), and Tok.
ReplacePreviousCachedToken()
void Preprocessor::ReplacePreviousCachedToken (ArrayRef< Token > NewToks)
Replace token in CachedLexPos - 1 in CachedTokens by the tokens in NewToks.
Useful when a token needs to be split in smaller ones and CachedTokens most recent token must to be updated to reflect that.
Definition at line 157 of file PPCaching.cpp.
RevertCachedTokens()
void clang::Preprocessor::RevertCachedTokens (unsigned N) inline
When backtracking is enabled and tokens are cached, this allows to revert a specific number of tokens.
Note that the number of tokens being reverted should be up to the last backtrack position, not more.
Definition at line 1499 of file Preprocessor.h.
References isBacktrackEnabled(), and N.
SawDateOrTime()
bool clang::Preprocessor::SawDateOrTime () const inline
Returns true if the preprocessor has seen a use of DATE or TIME in the file so far.
Definition at line 1980 of file Preprocessor.h.
setCodeCompletionHandler()
void clang::Preprocessor::setCodeCompletionHandler (CodeCompletionHandler & Handler) inline
Set the code completion handler to the given object.
Definition at line 1240 of file Preprocessor.h.
Referenced by clang::Parser::Parser().
setCodeCompletionIdentifierInfo()
void clang::Preprocessor::setCodeCompletionIdentifierInfo (IdentifierInfo * Filter) inline
Set the code completion token for filtering purposes.
Definition at line 1263 of file Preprocessor.h.
Referenced by Lex().
SetCodeCompletionPoint()
bool Preprocessor::SetCodeCompletionPoint (const FileEntry * File, unsigned Line, unsigned Column)
Specify the point at which code-completion will be performed.
Parameters
File the file in which code completion should occur. If this file is included multiple times, code-completion will perform completion the first time it is included. If NULL, this function clears out the code-completion point.
Line the line at which code completion should occur (1-based).
Column the column at which code completion should occur (1-based).
Returns
true if an error occurred, false otherwise.
Definition at line 387 of file Preprocessor.cpp.
References clang::File.
Referenced by EnableCodeCompletion().
setCodeCompletionReached()
void clang::Preprocessor::setCodeCompletionReached () inline
Note that we hit the code-completion point.
Definition at line 1644 of file Preprocessor.h.
References getDiagnostics(), isCodeCompletionEnabled(), and clang::DiagnosticsEngine::setSuppressAllDiagnostics().
Referenced by CodeCompleteIncludedFile(), CodeCompleteNaturalLanguage(), EvaluateDefined(), EvaluateValue(), HandleDirective(), and LexHeaderName().
setCodeCompletionTokenRange()
void clang::Preprocessor::setCodeCompletionTokenRange (const SourceLocation Start, const SourceLocation End) inline
Set the code completion token range for detecting replacement range later on.
Definition at line 1269 of file Preprocessor.h.
Referenced by Lex().
SetCommentRetentionState()
void clang::Preprocessor::SetCommentRetentionState (bool KeepComments, bool KeepMacroComments) inline
Control whether the preprocessor retains comments in output.
Definition at line 962 of file Preprocessor.h.
Referenced by clang::DoPrintPreprocessedInput().
setCounterValue()
void clang::Preprocessor::setCounterValue (unsigned V) inline
Definition at line 1984 of file Preprocessor.h.
References V.
Referenced by clang::ASTUnit::LoadFromASTFile(), and clang::PCHValidator::ReadCounter().
setDiagnostics()
void clang::Preprocessor::setDiagnostics (DiagnosticsEngine & D) inline
Definition at line 920 of file Preprocessor.h.
setEmptylineHandler()
void clang::Preprocessor::setEmptylineHandler (EmptylineHandler * Handler) inline
Set empty line handler.
Definition at line 1227 of file Preprocessor.h.
Referenced by clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks().
setExternalSource()
void clang::Preprocessor::setExternalSource (ExternalPreprocessorSource * Source) inline
Definition at line 935 of file Preprocessor.h.
setLoadedMacroDirective()
void Preprocessor::setLoadedMacroDirective (IdentifierInfo * II, MacroDirective * ED, MacroDirective * MD)
Set a MacroDirective that was loaded from a PCH file.
Definition at line 95 of file PPMacroExpansion.cpp.
References clang::MacroDirective::isDefined(), clang::IdentifierInfo::setHasMacroDefinition(), and clang::MacroDirective::setPrevious().
SetMacroExpansionOnlyInDirectives()
void clang::Preprocessor::SetMacroExpansionOnlyInDirectives () inline
Disables macro expansion everywhere except for preprocessor directives.
Definition at line 1474 of file Preprocessor.h.
Referenced by clang::RewriteIncludesInInput().
setMainFileDir()
void clang::Preprocessor::setMainFileDir (const DirectoryEntry * Dir) inline
Set the directory in which the main file should be considered to have been found, if it is not a real file.
Definition at line 1683 of file Preprocessor.h.
Referenced by prepareToBuildModule().
SetPoisonReason()
void Preprocessor::SetPoisonReason (IdentifierInfo * II, unsigned DiagID)
Specifies the reason for poisoning an identifier.
If that identifier is accessed while poisoned, then this reason will be used instead of the default "poisoned" diagnostic.
Definition at line 729 of file Preprocessor.cpp.
Referenced by clang::Parser::Initialize(), and Preprocessor().
setPragmaARCCFCodeAuditedInfo()
void clang::Preprocessor::setPragmaARCCFCodeAuditedInfo (IdentifierInfo * Ident, SourceLocation Loc) inline
Set the location of the currently-active #pragma clang arc_cf_code_audited begin.
An invalid location ends the pragma.
Definition at line 1662 of file Preprocessor.h.
setPragmaAssumeNonNullLoc()
void clang::Preprocessor::setPragmaAssumeNonNullLoc (SourceLocation Loc) inline
Set the location of the currently-active #pragma clang assume_nonnull begin.
An invalid location ends the pragma.
Definition at line 1677 of file Preprocessor.h.
setPragmasEnabled()
void clang::Preprocessor::setPragmasEnabled (bool Enabled) inline
Definition at line 969 of file Preprocessor.h.
setPredefines() [1/2]
void clang::Preprocessor::setPredefines (const char * P) inline
Set the predefines for this Preprocessor.
These predefines are automatically injected when parsing the main file.
Definition at line 1195 of file Preprocessor.h.
References P.
Referenced by createASTReader(), clang::CompilerInstance::createPCHExternalASTSource(), and clang::InitializePreprocessor().
setPredefines() [2/2]
void clang::Preprocessor::setPredefines (StringRef P) inline
Definition at line 1196 of file Preprocessor.h.
References P.
setPreprocessedOutput()
void clang::Preprocessor::setPreprocessedOutput (bool IsPreprocessedOutput) inline
Sets whether the preprocessor is responsible for producing output or if it is producing tokens to be consumed by Parse and Sema.
Definition at line 982 of file Preprocessor.h.
setPreprocessToken()
void clang::Preprocessor::setPreprocessToken (bool Preprocess) inline
Definition at line 1048 of file Preprocessor.h.
Referenced by clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks().
setRecordedPreambleConditionalStack()
void clang::Preprocessor::setRecordedPreambleConditionalStack (ArrayRef< PPConditionalInfo > s) inline
Definition at line 2324 of file Preprocessor.h.
References s.
setReplayablePreambleConditionalStack()
void clang::Preprocessor::setReplayablePreambleConditionalStack (ArrayRef< PPConditionalInfo > s, llvm::Optional< PreambleSkipInfo > SkipInfo) inline
Definition at line 2328 of file Preprocessor.h.
References s.
setSkipMainFilePreamble()
void clang::Preprocessor::setSkipMainFilePreamble (unsigned Bytes, bool StartOfLine) inline
Instruct the preprocessor to skip part of the main source file.
Parameters
Bytes The number of bytes in the preamble to skip.
StartOfLine Whether skipping these bytes puts the lexer at the start of a line.
Definition at line 1693 of file Preprocessor.h.
Referenced by clang::FrontendAction::BeginSourceFile(), and clang::InitializePreprocessor().
SetSuppressIncludeNotFoundError()
void clang::Preprocessor::SetSuppressIncludeNotFoundError (bool Suppress) inline
Definition at line 972 of file Preprocessor.h.
Referenced by clang::DependencyFileGenerator::attachToPreprocessor().
setTokenWatcher()
void clang::Preprocessor::setTokenWatcher (llvm::unique_function< void(const clang::Token &)> F) inline
Register a function that would be called on each token in the final expanded token stream.
This also reports annotation tokens produced by the parser.
Definition at line 1044 of file Preprocessor.h.
Referenced by clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks(), and clang::syntax::TokenCollector::TokenCollector().
SkipTokensWhileUsingPCH()
void Preprocessor::SkipTokensWhileUsingPCH ()
Skip tokens until after the #include of the through header or until after a #pragma hdrstop.
Skip tokens until after the #include of the through header or until after a #pragma hdrstop is seen.
Tokens in the predefines file and the main file may be skipped. If the end of the predefines file is reached, skipping continues into the main file. If the end of the main file is reached, it's a fatal error.
Definition at line 626 of file Preprocessor.cpp.
References Diag(), getPredefinesFileID(), clang::Token::is(), LexAfterModuleImport(), and Tok.
Referenced by EnterMainSourceFile().
SplitToken()
SourceLocation Preprocessor::SplitToken (SourceLocation TokLoc, unsigned Length)
Split the first Length characters out of the token starting at TokLoc and return a location pointing to the split token.
Re-lexing from the split token will return the split token rather than the original.
Definition at line 501 of file Preprocessor.cpp.
References clang::SourceLocation::getLocWithOffset(), getSourceManager(), and SM.
TypoCorrectToken()
void clang::Preprocessor::TypoCorrectToken (const Token & Tok) inline
Update the current token to represent the provided identifier, in order to cache an action performed by typo correction.
Definition at line 1587 of file Preprocessor.h.
References isBacktrackEnabled(), and Tok.
usingPCHWithPragmaHdrStop()
bool Preprocessor::usingPCHWithPragmaHdrStop ()
True if using a PCH with a #pragma hdrstop.
Definition at line 617 of file Preprocessor.cpp.
References clang::TU_Prefix.
Referenced by EnterMainSourceFile(), HandlePragmaHdrstop(), and Preprocessor().
usingPCHWithThroughHeader()
bool Preprocessor::usingPCHWithThroughHeader ()
True if using a PCH with a through header.
Definition at line 608 of file Preprocessor.cpp.
References clang::FileID::isValid(), and clang::TU_Prefix.
Referenced by EnterMainSourceFile().
Friends And Related Symbol Documentation
ASTReader
friend class ASTReader friend
Definition at line 451 of file Preprocessor.h.
MacroArgs
friend class MacroArgs friend
Definition at line 452 of file Preprocessor.h.
TokenLexer::ExpandFunctionArguments
void TokenLexer::ExpandFunctionArguments () friend
VAOptDefinitionContext
friend class VAOptDefinitionContext friend
Definition at line 130 of file Preprocessor.h.
VariadicMacroScopeGuard
friend class VariadicMacroScopeGuard friend
Definition at line 131 of file Preprocessor.h.
The documentation for this class was generated from the following files:
include/clang/Lex/Preprocessor.h
lib/Lex/PPCaching.cpp
lib/Lex/PPDirectives.cpp
lib/Lex/PPExpressions.cpp
lib/Lex/PPLexerChange.cpp
lib/Lex/PPMacroExpansion.cpp
lib/Lex/Pragma.cpp
lib/Lex/Preprocessor.cpp