clang: clang::ento::BugReporterData Class Reference
clang::ento::BugReporterData Class Reference abstract
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Member Functions
virtual ~BugReporterData ()=default
virtual ArrayRef< PathDiagnosticConsumer * > getPathDiagnosticConsumers ()=0
virtual ASTContext & getASTContext ()=0
virtual SourceManager & getSourceManager ()=0
virtual AnalyzerOptions & getAnalyzerOptions ()=0
virtual Preprocessor & getPreprocessor ()=0
Detailed Description
Definition at line 562 of file BugReporter.h.
Constructor & Destructor Documentation
~BugReporterData()
virtual clang::ento::BugReporterData::~BugReporterData () virtual default
Member Function Documentation
getAnalyzerOptions()
virtual AnalyzerOptions & clang::ento::BugReporterData::getAnalyzerOptions () pure virtual
Implemented in clang::ento::AnalysisManager.
Referenced by clang::ento::BugReporter::getAnalyzerOptions().
getASTContext()
virtual ASTContext & clang::ento::BugReporterData::getASTContext () pure virtual
Implemented in clang::ento::AnalysisManager.
Referenced by clang::ento::BugReporter::getContext().
getPathDiagnosticConsumers()
virtual ArrayRef< PathDiagnosticConsumer * > clang::ento::BugReporterData::getPathDiagnosticConsumers () pure virtual
Implemented in clang::ento::AnalysisManager.
Referenced by clang::ento::BugReporter::getPathDiagnosticConsumers().
getPreprocessor()
virtual Preprocessor & clang::ento::BugReporterData::getPreprocessor () pure virtual
Implemented in clang::ento::AnalysisManager.
Referenced by clang::ento::BugReporter::getPreprocessor().
getSourceManager()
virtual SourceManager & clang::ento::BugReporterData::getSourceManager () pure virtual
Implemented in clang::ento::AnalysisManager.
Referenced by clang::ento::BugReporter::getSourceManager().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h