clang: clang::ASTNameGenerator::Implementation Class Reference
clang::ASTNameGenerator::Implementation Class Reference
Public Types
enum ObjCKind { ObjCClass , ObjCMetaclass }
Public Member Functions
Implementation (ASTContext &Ctx)
bool writeName (const Decl *D, raw_ostream &OS)
std::string getName (const Decl *D)
std::vector< std::string > getAllManglings (const ObjCContainerDecl *OCD)
std::vector< std::string > getAllManglings (const Decl *D)
Static Public Member Functions
static StringRef getClassSymbolPrefix (ObjCKind Kind, const ASTContext &Context)
Detailed Description
Definition at line 374 of file Mangle.cpp.
Member Enumeration Documentation
ObjCKind
enum ASTNameGenerator::Implementation::ObjCKind
Enumerator
ObjCClass
ObjCMetaclass
Definition at line 419 of file Mangle.cpp.
Constructor & Destructor Documentation
Implementation()
clang::ASTNameGenerator::Implementation::Implementation (ASTContext & Ctx) inline explicit
Definition at line 379 of file Mangle.cpp.
Member Function Documentation
getAllManglings() [1/2]
std::vector< std::string > clang::ASTNameGenerator::Implementation::getAllManglings (const Decl * D) inline
Definition at line 454 of file Mangle.cpp.
References clang::C, clang::cast(), clang::ASTContext::createMangleContext(), clang::Ctor_Base, clang::Ctor_Complete, clang::Ctor_DefaultClosure, clang::Dtor_Base, clang::Dtor_Complete, clang::Dtor_Deleting, clang::ASTNameGenerator::Implementation::getAllManglings(), clang::Decl::getASTContext(), clang::TargetInfo::getCXXABI(), clang::ASTNameGenerator::Implementation::getName(), clang::ASTContext::getTargetInfo(), clang::VTableContextBase::getThunkInfo(), clang::ASTContext::getVTableContext(), hasDefaultCXXMethodCC(), clang::TargetCXXABI::isItaniumFamily(), and clang::TargetCXXABI::isMicrosoft().
getAllManglings() [2/2]
std::vector< std::string > clang::ASTNameGenerator::Implementation::getAllManglings (const ObjCContainerDecl * OCD) inline
Definition at line 431 of file Mangle.cpp.
References clang::Decl::getASTContext(), clang::ASTNameGenerator::Implementation::getClassSymbolPrefix(), clang::ASTNameGenerator::Implementation::ObjCClass, and clang::ASTNameGenerator::Implementation::ObjCMetaclass.
Referenced by clang::ASTNameGenerator::Implementation::getAllManglings().
getClassSymbolPrefix()
static StringRef clang::ASTNameGenerator::Implementation::getClassSymbolPrefix (ObjCKind Kind, const ASTContext & Context) inline static
Definition at line 424 of file Mangle.cpp.
References clang::ASTContext::getLangOpts(), clang::ObjCRuntime::isGNUFamily(), clang::ASTNameGenerator::Implementation::ObjCMetaclass, and clang::LangOptions::ObjCRuntime.
Referenced by clang::ASTNameGenerator::Implementation::getAllManglings().
getName()
std::string clang::ASTNameGenerator::Implementation::getName (const Decl * D) inline
Definition at line 410 of file Mangle.cpp.
References clang::ASTNameGenerator::Implementation::writeName().
Referenced by clang::ASTNameGenerator::Implementation::getAllManglings().
writeName()
bool clang::ASTNameGenerator::Implementation::writeName (const Decl * D, raw_ostream & OS) inline
Definition at line 383 of file Mangle.cpp.
Referenced by clang::ASTNameGenerator::Implementation::getName().
The documentation for this class was generated from the following file:
lib/AST/Mangle.cpp