clang: clang::TargetAttr Class Reference
clang::TargetAttr Class Reference
#include "clang/AST/Attr.h"
Public Types
enum Spelling { GNU_target = 0 , CXX11_gnu_target = 1 , C2x_gnu_target = 2 , SpellingNotCalculated = 15 }
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
TargetAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, llvm::StringRef FeaturesStr)
TargetAttr * clone (ASTContext &C) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
const char * getSpelling () const
llvm::StringRef getFeaturesStr () const
unsigned getFeaturesStrLength () const
void setFeaturesStr (ASTContext &C, llvm::StringRef S)
ParsedTargetAttr parse () const
StringRef getArchitecture () const
void getAddedFeatures (llvm::SmallVectorImpl< StringRef > &Out) const
template<class Compare >
ParsedTargetAttr parse (Compare cmp) const
bool isDefaultVersion () const
Public Member Functions inherited from clang::InheritableAttr
void setInherited (bool I)
bool shouldInheritEvenIfAlreadyPresent () const
Should this attribute be inherited from a prior declaration even if it's explicitly provided in the current declaration?
Public Member Functions inherited from clang::Attr
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static TargetAttr * CreateImplicit (ASTContext &Ctx, llvm::StringRef FeaturesStr, const AttributeCommonInfo &CommonInfo={SourceRange{}})
static TargetAttr * Create (ASTContext &Ctx, llvm::StringRef FeaturesStr, const AttributeCommonInfo &CommonInfo)
static TargetAttr * CreateImplicit (ASTContext &Ctx, llvm::StringRef FeaturesStr, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static TargetAttr * Create (ASTContext &Ctx, llvm::StringRef FeaturesStr, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static ParsedTargetAttr parse (StringRef Features)
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::InheritableAttr
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Additional Inherited Members
Protected Member Functions inherited from clang::InheritableAttr
InheritableAttr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed, bool InheritEvenIfAlreadyPresent)
Protected Member Functions inherited from clang::Attr
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes inherited from clang::Attr
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Definition at line 10222 of file Attr.h.
Member Enumeration Documentation
Spelling
enum clang::TargetAttr::Spelling
Enumerator
GNU_target
CXX11_gnu_target
C2x_gnu_target
SpellingNotCalculated
Definition at line 10227 of file Attr.h.
Constructor & Destructor Documentation
TargetAttr()
clang::TargetAttr::TargetAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, llvm::StringRef FeaturesStr)
Member Function Documentation
classof()
static bool clang::TargetAttr::classof (const Attr * A) inline static
Definition at line 10354 of file Attr.h.
clone()
TargetAttr * clang::TargetAttr::clone (ASTContext & C) const
Create() [1/2]
static TargetAttr * clang::TargetAttr::Create (ASTContext & Ctx, llvm::StringRef FeaturesStr, const AttributeCommonInfo & CommonInfo) static
Create() [2/2]
static TargetAttr * clang::TargetAttr::Create (ASTContext & Ctx, llvm::StringRef FeaturesStr, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
CreateImplicit() [1/2]
static TargetAttr * clang::TargetAttr::CreateImplicit (ASTContext & Ctx, llvm::StringRef FeaturesStr, const AttributeCommonInfo & CommonInfo = {SourceRange{}}) static
CreateImplicit() [2/2]
static TargetAttr * clang::TargetAttr::CreateImplicit (ASTContext & Ctx, llvm::StringRef FeaturesStr, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
getAddedFeatures()
void clang::TargetAttr::getAddedFeatures (llvm::SmallVectorImpl< StringRef > & Out) const inline
Definition at line 10285 of file Attr.h.
getArchitecture()
StringRef clang::TargetAttr::getArchitecture () const inline
Definition at line 10268 of file Attr.h.
getFeaturesStr()
llvm::StringRef clang::TargetAttr::getFeaturesStr () const inline
Definition at line 10250 of file Attr.h.
Referenced by CheckMultiVersionAdditionalDecl(), CheckTargetCausesMultiVersioning(), and isSameEntity().
getFeaturesStrLength()
unsigned clang::TargetAttr::getFeaturesStrLength () const inline
Definition at line 10253 of file Attr.h.
getSpelling()
const char * clang::TargetAttr::getSpelling () const
isDefaultVersion()
bool clang::TargetAttr::isDefaultVersion () const inline
Definition at line 10308 of file Attr.h.
Referenced by clang::Sema::AddConversionCandidate(), clang::Sema::AddMethodCandidate(), clang::Sema::AddOverloadCandidate(), CheckMultiVersionFirstFunction(), CheckTargetCausesMultiVersioning(), clang::Sema::NoteOverloadCandidate(), and noteOverloads().
parse() [1/3]
ParsedTargetAttr clang::TargetAttr::parse () const inline
Definition at line 10264 of file Attr.h.
Referenced by CheckMultiVersionAdditionalDecl(), CheckTargetCausesMultiVersioning(), and clang::ASTContext::filterFunctionTargetAttrs().
parse() [2/3]
template<class Compare > ParsedTargetAttr clang::TargetAttr::parse (Compare cmp) const inline
Definition at line 10302 of file Attr.h.
parse() [3/3]
static ParsedTargetAttr clang::TargetAttr::parse (StringRef Features) inline static
Definition at line 10310 of file Attr.h.
printPretty()
void clang::TargetAttr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
setFeaturesStr()
void clang::TargetAttr::setFeaturesStr (ASTContext & C, llvm::StringRef S) inline
Definition at line 10256 of file Attr.h.
The documentation for this class was generated from the following file:
include/clang/AST/Attr.h