clang: clang::CodeGen::CGDebugInfo Class Reference
clang::CodeGen::CGDebugInfo Class Reference
This class gathers all debug information during compilation and is responsible for emitting to llvm globals or pass directly to the backend.
#include "/root/llvm-project/clang/lib/CodeGen/CGDebugInfo.h"
Public Member Functions
CGDebugInfo (CodeGenModule &CGM)
~CGDebugInfo ()
void finalize ()
std::string remapDIPath (StringRef) const
Remap a given path with the current debug prefix map.
void registerVLASizeExpression (QualType Ty, llvm::Metadata *SizeExpr)
Register VLA size expression debug node with the qualified type.
void setLocation (SourceLocation Loc)
Update the current source location.
SourceLocation getLocation () const
Return the current source location.
void setInlinedAt (llvm::MDNode *InlinedAt)
Update the current inline scope.
llvm::MDNode * getInlinedAt () const
llvm::DebugLoc SourceLocToDebugLoc (SourceLocation Loc)
void EmitLocation (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate a change in line/column information in the source file.
void emitFunctionStart (GlobalDecl GD, SourceLocation Loc, SourceLocation ScopeLoc, QualType FnType, llvm::Function *Fn, bool CurFnIsThunk)
Emit a call to llvm.dbg.function.start to indicate start of a new function.
void EmitInlineFunctionStart (CGBuilderTy &Builder, GlobalDecl GD)
Start a new scope for an inlined function.
void EmitInlineFunctionEnd (CGBuilderTy &Builder)
End an inlined function scope.
void EmitFunctionDecl (GlobalDecl GD, SourceLocation Loc, QualType FnType, llvm::Function *Fn=nullptr)
Emit debug info for a function declaration.
void EmitFuncDeclForCallSite (llvm::CallBase *CallOrInvoke, QualType CalleeType, const FunctionDecl *CalleeDecl)
Emit debug info for an extern function being called.
void EmitFunctionEnd (CGBuilderTy &Builder, llvm::Function *Fn)
Constructs the debug code for exiting a function.
void EmitLexicalBlockStart (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate the beginning of a new lexical block and push the block onto the stack.
void EmitLexicalBlockEnd (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate the end of a new lexical block and pop the current block.
llvm::DILocalVariable * EmitDeclareOfAutoVariable (const VarDecl *Decl, llvm::Value *AI, CGBuilderTy &Builder, const bool UsePointerValue=false)
Emit call to llvm.dbg.declare for an automatic variable declaration.
void EmitLabel (const LabelDecl *D, CGBuilderTy &Builder)
Emit call to llvm.dbg.label for an label.
void EmitDeclareOfBlockDeclRefVariable (const VarDecl *variable, llvm::Value *storage, CGBuilderTy &Builder, const CGBlockInfo &blockInfo, llvm::Instruction *InsertPoint=nullptr)
Emit call to llvm.dbg.declare for an imported variable declaration in a block.
void EmitDeclareOfArgVariable (const VarDecl *Decl, llvm::Value *AI, unsigned ArgNo, CGBuilderTy &Builder)
Emit call to llvm.dbg.declare for an argument variable declaration.
void EmitDeclareOfBlockLiteralArgVariable (const CGBlockInfo &block, StringRef Name, unsigned ArgNo, llvm::AllocaInst *LocalAddr, CGBuilderTy &Builder)
Emit call to llvm.dbg.declare for the block-literal argument to a block invocation function.
void EmitGlobalVariable (llvm::GlobalVariable *GV, const VarDecl *Decl)
Emit information about a global variable.
void EmitGlobalVariable (const ValueDecl *VD, const APValue &Init)
Emit a constant global variable's debug info.
void EmitExternalVariable (llvm::GlobalVariable *GV, const VarDecl *Decl)
Emit information about an external variable.
void EmitUsingDirective (const UsingDirectiveDecl &UD)
Emit C++ using directive.
void EmitExplicitCastType (QualType Ty)
Emit the type explicitly casted to.
void EmitAndRetainType (QualType Ty)
Emit the type even if it might not be used.
void EmitUsingDecl (const UsingDecl &UD)
Emit C++ using declaration.
void EmitImportDecl (const ImportDecl &ID)
Emit an @import declaration.
llvm::DIImportedEntity * EmitNamespaceAlias (const NamespaceAliasDecl &NA)
Emit C++ namespace alias.
llvm::DIType * getOrCreateRecordType (QualType Ty, SourceLocation L)
Emit record type's standalone debug info.
llvm::DIType * getOrCreateInterfaceType (QualType Ty, SourceLocation Loc)
Emit an Objective-C interface type standalone debug info.
llvm::DIType * getOrCreateStandaloneType (QualType Ty, SourceLocation Loc)
Emit standalone debug info for a type.
void addHeapAllocSiteMetadata (llvm::CallBase *CallSite, QualType AllocatedTy, SourceLocation Loc)
Add heapallocsite metadata for MSAllocator calls.
void completeType (const EnumDecl *ED)
void completeType (const RecordDecl *RD)
void completeRequiredType (const RecordDecl *RD)
void completeClassData (const RecordDecl *RD)
void completeClass (const RecordDecl *RD)
void completeTemplateDefinition (const ClassTemplateSpecializationDecl &SD)
void completeUnusedClass (const CXXRecordDecl &D)
llvm::DIMacro * CreateMacro (llvm::DIMacroFile *Parent, unsigned MType, SourceLocation LineLoc, StringRef Name, StringRef Value)
Create debug info for a macro defined by a #define directive or a macro undefined by a #undef directive.
llvm::DIMacroFile * CreateTempMacroFile (llvm::DIMacroFile *Parent, SourceLocation LineLoc, SourceLocation FileLoc)
Create debug info for a file referenced by an #include directive.
void setDwoId (uint64_t Signature)
Module debugging: Support for building PCMs.
void setModuleMap (ModuleMap &MMap)
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
void setPCHDescriptor (ASTSourceDescriptor PCH)
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Friends
class ApplyDebugLocation
class SaveAndRestoreLocation
Detailed Description
This class gathers all debug information during compilation and is responsible for emitting to llvm globals or pass directly to the backend.
Definition at line 56 of file CGDebugInfo.h.
Constructor & Destructor Documentation
CGDebugInfo()
CGDebugInfo::CGDebugInfo (CodeGenModule & CGM)
Definition at line 66 of file CGDebugInfo.cpp.
References clang::CodeGenOptions::DebugPrefixMap, and clang::CodeGen::CodeGenModule::getCodeGenOpts().
~CGDebugInfo()
CGDebugInfo::~CGDebugInfo ()
Definition at line 75 of file CGDebugInfo.cpp.
Member Function Documentation
addHeapAllocSiteMetadata()
void CGDebugInfo::addHeapAllocSiteMetadata (llvm::CallBase * CallSite, QualType AllocatedTy, SourceLocation Loc)
Add heapallocsite metadata for MSAllocator calls.
Definition at line 2180 of file CGDebugInfo.cpp.
References clang::codegenoptions::DebugLineTablesOnly, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::Type::isVoidType().
completeClass()
void CGDebugInfo::completeClass (const RecordDecl * RD)
Definition at line 2270 of file CGDebugInfo.cpp.
References clang::Type::castAs(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getRecordType().
Referenced by completeClassData().
completeClassData()
void CGDebugInfo::completeClassData (const RecordDecl * RD)
Definition at line 2256 of file CGDebugInfo.cpp.
References completeClass(), clang::RecordDecl::getDefinition(), clang::CodeGen::CodeGenModule::getVTableLinkage(), isClassOrMethodDLLImport(), and isDefinedInClangModule().
Referenced by completeRequiredType(), and completeUnusedClass().
completeRequiredType()
void CGDebugInfo::completeRequiredType (const RecordDecl * RD)
Definition at line 2368 of file CGDebugInfo.cpp.
References completeClassData(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::ASTContext::getRecordType(), and shouldOmitDefinition().
Referenced by completeType().
completeTemplateDefinition()
void CGDebugInfo::completeTemplateDefinition (const ClassTemplateSpecializationDecl & SD)
Definition at line 3142 of file CGDebugInfo.cpp.
References completeUnusedClass().
completeType() [1/2]
void CGDebugInfo::completeType (const EnumDecl * ED)
Definition at line 2195 of file CGDebugInfo.cpp.
References clang::Type::castAs(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getEnumType().
completeType() [2/2]
void CGDebugInfo::completeType (const RecordDecl * RD)
Definition at line 2208 of file CGDebugInfo.cpp.
References completeRequiredType(), clang::CodeGen::CodeGenModule::getLangOpts(), and clang::codegenoptions::LimitedDebugInfo.
completeUnusedClass()
void CGDebugInfo::completeUnusedClass (const CXXRecordDecl & D)
Definition at line 3147 of file CGDebugInfo.cpp.
References completeClassData(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getRecordType().
Referenced by completeTemplateDefinition().
CreateMacro()
llvm::DIMacro * CGDebugInfo::CreateMacro (llvm::DIMacroFile * Parent, unsigned MType, SourceLocation LineLoc, StringRef Name, StringRef Value)
Create debug info for a macro defined by a #define directive or a macro undefined by a #undef directive.
Definition at line 3050 of file CGDebugInfo.cpp.
References clang::SourceLocation::isInvalid(), and Parent.
Referenced by clang::MacroPPCallbacks::MacroDefined(), and clang::MacroPPCallbacks::MacroUndefined().
CreateTempMacroFile()
llvm::DIMacroFile * CGDebugInfo::CreateTempMacroFile (llvm::DIMacroFile * Parent, SourceLocation LineLoc, SourceLocation FileLoc)
Create debug info for a file referenced by an #include directive.
Definition at line 3057 of file CGDebugInfo.cpp.
References clang::SourceLocation::isInvalid(), and Parent.
EmitAndRetainType()
void CGDebugInfo::EmitAndRetainType (QualType Ty)
Emit the type even if it might not be used.
Definition at line 5019 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasMaybeUnusedDebugInfo().
EmitDeclareOfArgVariable()
void CGDebugInfo::EmitDeclareOfArgVariable (const VarDecl * Decl, llvm::Value * AI, unsigned ArgNo, CGBuilderTy & Builder)
Emit call to llvm.dbg.declare for an argument variable declaration.
Definition at line 4424 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitDeclareOfAutoVariable()
llvm::DILocalVariable * CGDebugInfo::EmitDeclareOfAutoVariable (const VarDecl * Decl, llvm::Value * AI, CGBuilderTy & Builder, const bool UsePointerValue = false)
Emit call to llvm.dbg.declare for an automatic variable declaration.
Returns a pointer to the DILocalVariable associated with the llvm.dbg.declare, or nullptr otherwise.
Definition at line 4310 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitDeclareOfBlockDeclRefVariable()
void CGDebugInfo::EmitDeclareOfBlockDeclRefVariable (const VarDecl * variable, llvm::Value * storage, CGBuilderTy & Builder, const CGBlockInfo & blockInfo, llvm::Instruction * InsertPoint = nullptr)
Emit call to llvm.dbg.declare for an imported variable declaration in a block.
Definition at line 4352 of file CGDebugInfo.cpp.
References clang::CharUnits::fromQuantity(), clang::CodeGen::CGBlockInfo::getCapture(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getDeclAlignIfRequired(), clang::CodeGen::CGBlockInfo::Capture::getIndex(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::CharUnits::getQuantity(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::SourceLocation::isValid(), clang::ImplicitParamDecl::ObjCSelf, clang::CodeGen::CGBlockInfo::StructureType, and clang::ASTContext::toCharUnitsFromBits().
EmitDeclareOfBlockLiteralArgVariable()
void CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable (const CGBlockInfo & block, StringRef Name, unsigned ArgNo, llvm::AllocaInst * LocalAddr, CGBuilderTy & Builder)
Emit call to llvm.dbg.declare for the block-literal argument to a block invocation function.
Definition at line 4479 of file CGDebugInfo.cpp.
References clang::TypeInfo::Align, clang::TypeInfo::AlignIsRequired, clang::AS_public, clang::ast_matchers::blockDecl, clang::CodeGen::CGBlockInfo::BlockSize, clang::C, clang::BlockDecl::Capture::Capture(), clang::cast(), clang::CodeGen::CGBlockInfo::CXXThisIndex, clang::CodeGen::CGBlockInfo::getBlockDecl(), clang::CodeGen::CGBlockInfo::getCapture(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getDeclAlignIfRequired(), clang::CodeGen::CGBlockInfo::Capture::getIndex(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::NamedDecl::getName(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getUniqueBlockCount(), clang::BlockDecl::Capture::getVariable(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::BlockDecl::Capture::isByRef(), clang::CodeGen::CGBlockInfo::Capture::isConstant(), clang::CodeGen::CodeGenTypeCache::PointerWidthInBits, clang::CodeGen::CGBlockInfo::StructureType, clang::ASTContext::toBits(), clang::ast_matchers::type, and clang::TypeInfo::Width.
EmitExplicitCastType()
void CGDebugInfo::EmitExplicitCastType (QualType Ty)
Emit the type explicitly casted to.
Definition at line 5013 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitExternalVariable()
void CGDebugInfo::EmitExternalVariable (llvm::GlobalVariable * GV, const VarDecl * Decl)
Emit information about an external variable.
Definition at line 4808 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), getDeclAlignIfRequired(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitFuncDeclForCallSite()
void CGDebugInfo::EmitFuncDeclForCallSite (llvm::CallBase * CallOrInvoke, QualType CalleeType, const FunctionDecl * CalleeDecl)
Emit debug info for an extern function being called.
This is needed for call site debug info.
Definition at line 3968 of file CGDebugInfo.cpp.
References EmitFunctionDecl(), clang::FunctionDecl::getBuiltinID(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::Decl::hasAttr(), Id, clang::FunctionDecl::isInlined(), and clang::FunctionDecl::isStatic().
EmitFunctionDecl()
void CGDebugInfo::EmitFunctionDecl (GlobalDecl GD, SourceLocation Loc, QualType FnType, llvm::Function * Fn = nullptr)
Emit debug info for a function declaration.
Fn is set only when a declaration for a debug call site gets created.
Definition at line 3908 of file CGDebugInfo.cpp.
References clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::isImplicit(), clang::SourceLocation::isInvalid(), and true.
Referenced by EmitFuncDeclForCallSite().
EmitFunctionEnd()
void CGDebugInfo::EmitFunctionEnd (CGBuilderTy & Builder, llvm::Function * Fn)
Constructs the debug code for exiting a function.
Definition at line 4084 of file CGDebugInfo.cpp.
References EmitLocation().
Referenced by EmitInlineFunctionEnd().
emitFunctionStart()
void CGDebugInfo::emitFunctionStart (GlobalDecl GD, SourceLocation Loc, SourceLocation ScopeLoc, QualType FnType, llvm::Function * Fn, bool CurFnIsThunk)
Emit a call to llvm.dbg.function.start to indicate start of a new function.
Parameters
Loc The location of the function header.
ScopeLoc The location of the function body.
Definition at line 3807 of file CGDebugInfo.cpp.
References clang::Decl::getCanonicalDecl(), clang::GlobalDecl::getDecl(), clang::GlobalDecl::getDynamicInitKind(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::hasAttr(), clang::isa(), clang::Decl::isImplicit(), clang::SourceLocation::isValid(), and clang::NoStub.
EmitGlobalVariable() [1/2]
void CGDebugInfo::EmitGlobalVariable (const ValueDecl * VD, const APValue & Init)
Emit a constant global variable's debug info.
Definition at line 4719 of file CGDebugInfo.cpp.
References clang::cast(), clang::QualType::getAsOpaquePtr(), clang::Decl::getCanonicalDecl(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), getDeclAlignIfRequired(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::NamedDecl::getNameForDiagnostic(), clang::ASTContext::getRecordType(), clang::ValueDecl::getType(), clang::TypeDecl::getTypeForDecl(), clang::ASTContext::getTypeSize(), clang::Decl::hasAttr(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitGlobalVariable() [2/2]
void CGDebugInfo::EmitGlobalVariable (llvm::GlobalVariable * GV, const VarDecl * Decl)
Emit information about a global variable.
Definition at line 4649 of file CGDebugInfo.cpp.
References clang::cuda_constant, clang::cuda_shared, clang::VarDecl::getCanonicalDecl(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getContext(), getDeclAlignIfRequired(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::NamedDecl::getNameForDiagnostic(), clang::ASTContext::getTargetAddressSpace(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::CodeGenOptions::hasReducedDebugInfo(), and clang::RecordDecl::isAnonymousStructOrUnion().
EmitImportDecl()
void CGDebugInfo::EmitImportDecl (const ImportDecl & ID)
Emit an @import declaration.
Definition at line 4876 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts().
EmitInlineFunctionEnd()
void CGDebugInfo::EmitInlineFunctionEnd (CGBuilderTy & Builder)
End an inlined function scope.
Definition at line 4013 of file CGDebugInfo.cpp.
References EmitFunctionEnd(), getInlinedAt(), and setInlinedAt().
Referenced by clang::CodeGen::ApplyInlineDebugLocation::~ApplyInlineDebugLocation().
EmitInlineFunctionStart()
void CGDebugInfo::EmitInlineFunctionStart (CGBuilderTy & Builder, GlobalDecl GD)
Start a new scope for an inlined function.
Definition at line 3998 of file CGDebugInfo.cpp.
References clang::cast(), EmitLocation(), clang::GlobalDecl::getDecl(), and setInlinedAt().
EmitLabel()
void CGDebugInfo::EmitLabel (const LabelDecl * D, CGBuilderTy & Builder)
Emit call to llvm.dbg.label for an label.
Definition at line 4317 of file CGDebugInfo.cpp.
References clang::cast(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::Decl::hasAttr(), and clang::CodeGenOptions::hasReducedDebugInfo().
EmitLexicalBlockEnd()
void CGDebugInfo::EmitLexicalBlockEnd (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate the end of a new lexical block and pop the current block.
Definition at line 4071 of file CGDebugInfo.cpp.
References clang::codegenoptions::DebugLineTablesOnly, and EmitLocation().
EmitLexicalBlockStart()
void CGDebugInfo::EmitLexicalBlockStart (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate the beginning of a new lexical block and push the block onto the stack.
Definition at line 4054 of file CGDebugInfo.cpp.
References clang::codegenoptions::DebugLineTablesOnly, clang::CodeGen::CodeGenModule::getLLVMContext(), and setLocation().
EmitLocation()
void CGDebugInfo::EmitLocation (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate a change in line/column information in the source file.
If the location is invalid, the previous location will be reused.
Definition at line 4019 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getLLVMContext(), and setLocation().
Referenced by EmitFunctionEnd(), EmitInlineFunctionStart(), and EmitLexicalBlockEnd().
EmitNamespaceAlias()
llvm::DIImportedEntity * CGDebugInfo::EmitNamespaceAlias (const NamespaceAliasDecl & NA)
Emit C++ namespace alias.
Definition at line 4890 of file CGDebugInfo.cpp.
References clang::cast(), EmitNamespaceAlias(), clang::NamespaceAliasDecl::getAliasedNamespace(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::NamedDecl::getName(), and clang::CodeGenOptions::hasReducedDebugInfo().
Referenced by EmitNamespaceAlias().
EmitUsingDecl()
void CGDebugInfo::EmitUsingDecl (const UsingDecl & UD)
Emit C++ using declaration.
Definition at line 4849 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::Type::getContainedAutoType(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::NamedDecl::getUnderlyingDecl(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::UsingDecl::shadow_begin(), and clang::UsingDecl::shadow_size().
EmitUsingDirective()
void CGDebugInfo::EmitUsingDirective (const UsingDirectiveDecl & UD)
Emit C++ using directive.
Definition at line 4834 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::UsingDirectiveDecl::getNominatedNamespace(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::NamespaceDecl::isAnonymousNamespace(), and clang::SourceLocation::isValid().
finalize()
void CGDebugInfo::finalize ()
Definition at line 4936 of file CGDebugInfo.cpp.
References clang::cast(), clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::ObjCInterfaceType::getDecl(), clang::ObjCInterfaceDecl::getDefinition(), and P.
getInlinedAt()
llvm::MDNode * clang::CodeGen::CGDebugInfo::getInlinedAt () const inline
Returns
the current inline scope.
Definition at line 401 of file CGDebugInfo.h.
Referenced by EmitInlineFunctionEnd().
getLocation()
SourceLocation clang::CodeGen::CGDebugInfo::getLocation () const inline
Return the current source location.
This does not necessarily correspond to the IRBuilder's current DebugLoc.
Definition at line 394 of file CGDebugInfo.h.
getOrCreateInterfaceType()
llvm::DIType * CGDebugInfo::getOrCreateInterfaceType (QualType Ty, SourceLocation Loc)
Emit an Objective-C interface type standalone debug info.
Definition at line 2164 of file CGDebugInfo.cpp.
References getOrCreateStandaloneType().
getOrCreateRecordType()
llvm::DIType * CGDebugInfo::getOrCreateRecordType (QualType Ty, SourceLocation L)
Emit record type's standalone debug info.
Definition at line 2157 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasReducedDebugInfo().
getOrCreateStandaloneType()
llvm::DIType * CGDebugInfo::getOrCreateStandaloneType (QualType Ty, SourceLocation Loc)
Emit standalone debug info for a type.
Definition at line 2169 of file CGDebugInfo.cpp.
References clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGenOptions::hasReducedDebugInfo(), and clang::QualType::isNull().
Referenced by emitArraySubscriptGEP(), emitPreserveStructAccess(), and getOrCreateInterfaceType().
registerVLASizeExpression()
void clang::CodeGen::CGDebugInfo::registerVLASizeExpression (QualType Ty, llvm::Metadata * SizeExpr) inline
Register VLA size expression debug node with the qualified type.
Definition at line 368 of file CGDebugInfo.h.
remapDIPath()
std::string CGDebugInfo::remapDIPath (StringRef Path) const
Remap a given path with the current debug prefix map.
Definition at line 472 of file CGDebugInfo.cpp.
References P.
setDwoId()
void CGDebugInfo::setDwoId (uint64_t Signature)
Module debugging: Support for building PCMs.
Set the main CU's DwoId field to Signature.
Definition at line 4931 of file CGDebugInfo.cpp.
setInlinedAt()
void clang::CodeGen::CGDebugInfo::setInlinedAt (llvm::MDNode * InlinedAt) inline
Update the current inline scope.
All subsequent calls to EmitLocation will create a location with this inlinedAt field.
Definition at line 398 of file CGDebugInfo.h.
Referenced by EmitInlineFunctionEnd(), and EmitInlineFunctionStart().
setLocation()
void CGDebugInfo::setLocation (SourceLocation Loc)
Update the current source location.
If
loc is invalid it is ignored.
Definition at line 170 of file CGDebugInfo.cpp.
References clang::cast(), clang::CodeGen::CodeGenModule::getContext(), clang::SourceManager::getExpansionLoc(), clang::ASTContext::getSourceManager(), clang::PresumedLoc::isInvalid(), clang::SourceLocation::isInvalid(), and SM.
Referenced by EmitLexicalBlockStart(), and EmitLocation().
setModuleMap()
void clang::CodeGen::CGDebugInfo::setModuleMap (ModuleMap & MMap) inline
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Definition at line 380 of file CGDebugInfo.h.
setPCHDescriptor()
void clang::CodeGen::CGDebugInfo::setPCHDescriptor (ASTSourceDescriptor PCH) inline
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Definition at line 385 of file CGDebugInfo.h.
References clang::PCH.
SourceLocToDebugLoc()
llvm::DebugLoc CGDebugInfo::SourceLocToDebugLoc (SourceLocation Loc)
Definition at line 5025 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getLLVMContext().
Friends And Related Symbol Documentation
ApplyDebugLocation
friend class ApplyDebugLocation friend
Definition at line 57 of file CGDebugInfo.h.
SaveAndRestoreLocation
friend class SaveAndRestoreLocation friend
Definition at line 58 of file CGDebugInfo.h.
The documentation for this class was generated from the following files:
lib/CodeGen/CGDebugInfo.h
lib/CodeGen/CGDebugInfo.cpp