clang: clang::DiagnosticError Class Reference
clang::DiagnosticError Class Reference
Carries a Clang diagnostic in an llvm::Error.
#include "clang/Basic/DiagnosticError.h"
Public Member Functions
DiagnosticError (PartialDiagnosticAt Diag)
void log (raw_ostream &OS) const override
PartialDiagnosticAt & getDiagnostic ()
const PartialDiagnosticAt & getDiagnostic () const
Static Public Member Functions
static llvm::Error create (SourceLocation Loc, PartialDiagnostic Diag)
Creates a new DiagnosticError that contains the given diagnostic at the given location.
static Optional< PartialDiagnosticAt > take (llvm::Error &Err)
Extracts and returns the diagnostic payload from the given Error if the error is a DiagnosticError.
Static Public Attributes
static char ID
Detailed Description
Carries a Clang diagnostic in an llvm::Error.
Users should emit the stored diagnostic using the DiagnosticsEngine.
Definition at line 20 of file DiagnosticError.h.
Constructor & Destructor Documentation
DiagnosticError()
clang::DiagnosticError::DiagnosticError (PartialDiagnosticAt Diag) inline
Definition at line 22 of file DiagnosticError.h.
Member Function Documentation
create()
static llvm::Error clang::DiagnosticError::create (SourceLocation Loc, PartialDiagnostic Diag) inline static
Creates a new DiagnosticError that contains the given diagnostic at the given location.
Definition at line 31 of file DiagnosticError.h.
Referenced by clang::tooling::RefactoringRuleContext::createDiagnosticError().
getDiagnostic() [1/2]
PartialDiagnosticAt & clang::DiagnosticError::getDiagnostic () inline
Definition at line 26 of file DiagnosticError.h.
Referenced by take().
getDiagnostic() [2/2]
const PartialDiagnosticAt & clang::DiagnosticError::getDiagnostic () const inline
Definition at line 27 of file DiagnosticError.h.
log()
void clang::DiagnosticError::log (raw_ostream & OS) const inline override
Definition at line 24 of file DiagnosticError.h.
take()
static Optional< PartialDiagnosticAt > clang::DiagnosticError::take (llvm::Error & Err) inline static
Extracts and returns the diagnostic payload from the given Error if the error is a DiagnosticError.
Returns none if the given error is not a DiagnosticError.
Definition at line 39 of file DiagnosticError.h.
References getDiagnostic(), and clang::Result.
Member Data Documentation
ID
char DiagnosticError::ID static
Definition at line 47 of file DiagnosticError.h.
The documentation for this class was generated from the following files:
include/clang/Basic/DiagnosticError.h
lib/Basic/Diagnostic.cpp