clang: clang::CodeGen::ReductionCodeGen Class Reference
clang::CodeGen::ReductionCodeGen Class Reference
Class intended to support codegen of all kind of the reduction clauses.
#include "/root/llvm-project/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
ReductionCodeGen (ArrayRef< const Expr * > Shareds, ArrayRef< const Expr * > Origs, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > ReductionOps)
void emitSharedOrigLValue (CodeGenFunction &CGF, unsigned N)
Emits lvalue for the shared and original reduction item.
void emitAggregateType (CodeGenFunction &CGF, unsigned N)
Emits the code for the variable-modified type, if required.
void emitAggregateType (CodeGenFunction &CGF, unsigned N, llvm::Value *Size)
Emits the code for the variable-modified type, if required.
void emitInitialization (CodeGenFunction &CGF, unsigned N, Address PrivateAddr, LValue SharedLVal, llvm::function_ref< bool(CodeGenFunction &)> DefaultInit)
Performs initialization of the private copy for the reduction item.
bool needCleanups (unsigned N)
Returns true if the private copy requires cleanups.
void emitCleanups (CodeGenFunction &CGF, unsigned N, Address PrivateAddr)
Emits cleanup code for the reduction item.
Address adjustPrivateAddress (CodeGenFunction &CGF, unsigned N, Address PrivateAddr)
Adjusts PrivatedAddr for using instead of the original variable address in normal operations.
LValue getSharedLValue (unsigned N) const
Returns LValue for the reduction item.
LValue getOrigLValue (unsigned N) const
Returns LValue for the original reduction item.
std::pair< llvm::Value *, llvm::Value * > getSizes (unsigned N) const
Returns the size of the reduction item (in chars and total number of elements in the item), or nullptr, if the size is a constant.
const VarDecl * getBaseDecl (unsigned N) const
Returns the base declaration of the reduction item.
const Expr * getRefExpr (unsigned N) const
Returns the base declaration of the reduction item.
bool usesReductionInitializer (unsigned N) const
Returns true if the initialization of the reduction item uses initializer from declare reduction construct.
Detailed Description
Class intended to support codegen of all kind of the reduction clauses.
Definition at line 130 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
ReductionCodeGen()
ReductionCodeGen::ReductionCodeGen (ArrayRef< const Expr * > Shareds, ArrayRef< const Expr * > Origs, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > ReductionOps)
Definition at line 786 of file CGOpenMPRuntime.cpp.
Member Function Documentation
adjustPrivateAddress()
Address ReductionCodeGen::adjustPrivateAddress (CodeGenFunction & CGF, unsigned N, Address PrivateAddr)
Adjusts PrivatedAddr for using instead of the original variable address in normal operations.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
Definition at line 999 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, castToBase(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getAlignment(), getBaseDecl(), clang::CodeGen::Address::getPointer(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::Address::getType(), loadToBegin(), and N.
emitAggregateType() [1/2]
void ReductionCodeGen::emitAggregateType (CodeGenFunction & CGF, unsigned N)
Emits the code for the variable-modified type, if required.
Parameters
N Number of the reduction item.
Definition at line 820 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(), clang::CodeGen::RValue::get(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::VariableArrayType::getSizeExpr(), clang::CodeGen::CodeGenFunction::getTypeSize(), clang::isa(), clang::Type::isVariablyModifiedType(), and N.
Referenced by emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), emitScanBasedDirective(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
emitAggregateType() [2/2]
void ReductionCodeGen::emitAggregateType (CodeGenFunction & CGF, unsigned N, llvm::Value * Size)
Emits the code for the variable-modified type, if required.
Parameters
N Number of the reduction item.
Size Size of the type in chars.
Definition at line 857 of file CGOpenMPRuntime.cpp.
References clang::cast(), clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(), clang::CodeGen::RValue::get(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::VariableArrayType::getSizeExpr(), clang::Type::isVariablyModifiedType(), and N.
emitCleanups()
void ReductionCodeGen::emitCleanups (CodeGenFunction & CGF, unsigned N, Address PrivateAddr)
Emits cleanup code for the reduction item.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
Definition at line 918 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::QualType::isDestructedType(), N, needCleanups(), and clang::CodeGen::CodeGenFunction::pushDestroy().
Referenced by emitReduceFiniFunction().
emitInitialization()
void ReductionCodeGen::emitInitialization (CodeGenFunction & CGF, unsigned N, Address PrivateAddr, LValue SharedLVal, llvm::function_ref< bool(CodeGenFunction &)> DefaultInit)
Performs initialization of the private copy for the reduction item.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
DefaultInit Default initialization sequence that should be performed if no reduction specific initialization is found.
SharedLVal Address of the original shared variable.
Definition at line 876 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::cast(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), emitInitWithReductionInitializer(), clang::CodeGen::LValue::getAddress(), clang::ASTContext::getAsArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::OMPDeclareReductionDecl::getInitializer(), getReductionInit(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::CodeGen::Address::getType(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenFunction::isTrivialInitializer(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and N.
Referenced by emitReduceInitFunction().
emitSharedOrigLValue()
void ReductionCodeGen::emitSharedOrigLValue (CodeGenFunction & CGF, unsigned N)
Emits lvalue for the shared and original reduction item.
Parameters
N Number of the reduction item.
Definition at line 805 of file CGOpenMPRuntime.cpp.
References clang::First, and N.
Referenced by emitScanBasedDirective(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getBaseDecl()
const VarDecl * clang::CodeGen::ReductionCodeGen::getBaseDecl (unsigned N) const inline
Returns the base declaration of the reduction item.
Definition at line 218 of file CGOpenMPRuntime.h.
References N.
Referenced by adjustPrivateAddress().
getOrigLValue()
LValue clang::CodeGen::ReductionCodeGen::getOrigLValue (unsigned N) const inline
Returns LValue for the original reduction item.
Definition at line 211 of file CGOpenMPRuntime.h.
References N.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getRefExpr()
const Expr * clang::CodeGen::ReductionCodeGen::getRefExpr (unsigned N) const inline
Returns the base declaration of the reduction item.
Definition at line 220 of file CGOpenMPRuntime.h.
References N.
Referenced by emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups().
getSharedLValue()
LValue clang::CodeGen::ReductionCodeGen::getSharedLValue (unsigned N) const inline
Returns LValue for the reduction item.
Definition at line 209 of file CGOpenMPRuntime.h.
References N.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getSizes()
std::pair< llvm::Value *, llvm::Value * > clang::CodeGen::ReductionCodeGen::getSizes (unsigned N) const inline
Returns the size of the reduction item (in chars and total number of elements in the item), or nullptr, if the size is a constant.
Definition at line 214 of file CGOpenMPRuntime.h.
References N.
Referenced by emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
needCleanups()
bool ReductionCodeGen::needCleanups (unsigned N)
Returns true if the private copy requires cleanups.
Definition at line 910 of file CGOpenMPRuntime.cpp.
References clang::cast(), clang::QualType::DK_none, clang::QualType::isDestructedType(), and N.
Referenced by emitCleanups(), and emitReduceFiniFunction().
usesReductionInitializer()
bool ReductionCodeGen::usesReductionInitializer (unsigned N) const
Returns true if the initialization of the reduction item uses initializer from declare reduction construct.
Definition at line 1025 of file CGOpenMPRuntime.cpp.
References clang::OMPDeclareReductionDecl::getInitializer(), getReductionInit(), and N.
Referenced by emitReduceInitFunction().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntime.h
lib/CodeGen/CGOpenMPRuntime.cpp