clang: clang::ExplicitSpecifier Class Reference
clang::ExplicitSpecifier Class Reference
Store information needed for an explicit specifier.
#include "clang/AST/DeclCXX.h"
Public Member Functions
ExplicitSpecifier ()=default
ExplicitSpecifier (Expr *Expression, ExplicitSpecKind Kind)
ExplicitSpecKind getKind () const
const Expr * getExpr () const
Expr * getExpr ()
bool isSpecified () const
Determine if the declaration had an explicit specifier of any kind.
bool isEquivalent (const ExplicitSpecifier Other) const
Check for equivalence of explicit specifiers.
bool isExplicit () const
Determine whether this specifier is known to correspond to an explicit declaration.
bool isInvalid () const
Determine if the explicit specifier is invalid.
void setKind (ExplicitSpecKind Kind)
void setExpr (Expr *E)
Static Public Member Functions
static ExplicitSpecifier getFromDecl (FunctionDecl *Function)
static const ExplicitSpecifier getFromDecl (const FunctionDecl *Function)
static ExplicitSpecifier Invalid ()
Detailed Description
Store information needed for an explicit specifier.
Used by CXXDeductionGuideDecl, CXXConstructorDecl and CXXConversionDecl.
Definition at line 1793 of file DeclCXX.h.
Constructor & Destructor Documentation
ExplicitSpecifier() [1/2]
clang::ExplicitSpecifier::ExplicitSpecifier () default
Referenced by Invalid().
ExplicitSpecifier() [2/2]
clang::ExplicitSpecifier::ExplicitSpecifier (Expr * Expression, ExplicitSpecKind Kind) inline
Definition at line 1799 of file DeclCXX.h.
Member Function Documentation
getExpr() [1/2]
Expr * clang::ExplicitSpecifier::getExpr () inline
Definition at line 1803 of file DeclCXX.h.
getExpr() [2/2]
const Expr * clang::ExplicitSpecifier::getExpr () const inline
Definition at line 1802 of file DeclCXX.h.
Referenced by addExplicitSpecifier(), clang::CXXConstructorDecl::Create(), DiagnoseFailedExplicitSpec(), clang::DeclSpec::getExplicitSpecRange(), instantiateExplicitSpecifier(), isEquivalent(), printExplicitSpecifier(), clang::CXXConstructorDecl::setExplicitSpecifier(), clang::DeclSpec::setFunctionSpecExplicit(), and clang::Sema::tryResolveExplicitSpecifier().
getFromDecl() [1/2]
static const ExplicitSpecifier clang::ExplicitSpecifier::getFromDecl (const FunctionDecl * Function) inline static
Definition at line 1830 of file DeclCXX.h.
References getFromDecl().
getFromDecl() [2/2]
ExplicitSpecifier ExplicitSpecifier::getFromDecl (FunctionDecl * Function) static
Definition at line 2063 of file DeclCXX.cpp.
References clang::cast().
Referenced by clang::Sema::AddOverloadCandidate(), DiagnoseFailedExplicitSpec(), getFromDecl(), isNonDependentlyExplicit(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
getKind()
ExplicitSpecKind clang::ExplicitSpecifier::getKind () const inline
Definition at line 1801 of file DeclCXX.h.
Referenced by addExplicitSpecifier(), instantiateExplicitSpecifier(), and isEquivalent().
Invalid()
static ExplicitSpecifier clang::ExplicitSpecifier::Invalid () inline static
Definition at line 1833 of file DeclCXX.h.
References ExplicitSpecifier(), and clang::Unresolved.
Referenced by instantiateExplicitSpecifier().
isEquivalent()
bool ExplicitSpecifier::isEquivalent (const ExplicitSpecifier Other) const
Check for equivalence of explicit specifiers.
Returns
true if the explicit specifier are equivalent, false otherwise.
Definition at line 2048 of file DeclCXX.cpp.
References clang::ODRHash::AddStmt(), clang::ODRHash::CalculateHash(), getExpr(), getKind(), and clang::Unresolved.
isExplicit()
bool clang::ExplicitSpecifier::isExplicit () const inline
Determine whether this specifier is known to correspond to an explicit declaration.
Returns false if the specifier is absent or has an expression that is value-dependent or evaluates to false.
Definition at line 1817 of file DeclCXX.h.
References clang::ResolvedTrue.
Referenced by DiagnoseFailedExplicitSpec(), clang::CXXConstructorDecl::isExplicit(), clang::CXXConversionDecl::isExplicit(), clang::CXXDeductionGuideDecl::isExplicit(), isNonDependentlyExplicit(), and clang::CXXConstructorDecl::setExplicitSpecifier().
isInvalid()
bool clang::ExplicitSpecifier::isInvalid () const inline
Determine if the explicit specifier is invalid.
This state occurs after a substitution failures.
Definition at line 1822 of file DeclCXX.h.
References clang::Unresolved.
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
isSpecified()
bool clang::ExplicitSpecifier::isSpecified () const inline
Determine if the declaration had an explicit specifier of any kind.
Definition at line 1806 of file DeclCXX.h.
References clang::ResolvedFalse.
Referenced by clang::DeclSpec::hasExplicitSpecifier().
setExpr()
void clang::ExplicitSpecifier::setExpr (Expr * E) inline
Definition at line 1827 of file DeclCXX.h.
Referenced by clang::Sema::tryResolveExplicitSpecifier().
setKind()
void clang::ExplicitSpecifier::setKind (ExplicitSpecKind Kind) inline
Definition at line 1826 of file DeclCXX.h.
Referenced by clang::Sema::tryResolveExplicitSpecifier().
The documentation for this class was generated from the following files:
include/clang/AST/DeclCXX.h
lib/AST/DeclCXX.cpp