clang: clang::ento::SymbolCast Class Reference
clang::ento::SymbolCast Class Reference
Represents a cast expression.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
SymbolCast (const SymExpr *In, QualType From, QualType To)
unsigned computeComplexity () const override
QualType getType () const override
const SymExpr * getOperand () const
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &ID) override
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
symbol_iterator symbol_begin () const
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const SymExpr *In, QualType From, QualType To)
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymExpr
static symbol_iterator symbol_end ()
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
Represents a cast expression.
Definition at line 264 of file SymbolManager.h.
Constructor & Destructor Documentation
SymbolCast()
clang::ento::SymbolCast::SymbolCast (const SymExpr * In, QualType From, QualType To) inline
Definition at line 274 of file SymbolManager.h.
References clang::ento::SymExpr::isValidTypeForSymbol().
Member Function Documentation
classof()
static bool clang::ento::SymbolCast::classof (const SymExpr * SE) inline static
Definition at line 307 of file SymbolManager.h.
References clang::ento::SymExpr::getKind().
computeComplexity()
unsigned clang::ento::SymbolCast::computeComplexity () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 282 of file SymbolManager.h.
References clang::ento::SymExpr::Complexity.
dumpToStream()
void SymbolCast::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::SymExpr.
Definition at line 67 of file SymbolManager.cpp.
References clang::ento::SymExpr::dumpToStream(), and clang::QualType::getAsString().
getOperand()
const SymExpr * clang::ento::SymbolCast::getOperand () const inline
Definition at line 290 of file SymbolManager.h.
getType()
QualType clang::ento::SymbolCast::getType () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 288 of file SymbolManager.h.
Profile() [1/2]
void clang::ento::SymbolCast::Profile (llvm::FoldingSetNodeID & ID) inline override virtual
Implements clang::ento::SymExpr.
Definition at line 302 of file SymbolManager.h.
References Profile().
Profile() [2/2]
static void clang::ento::SymbolCast::Profile (llvm::FoldingSetNodeID & ID, const SymExpr * In, QualType From, QualType To) inline static
Definition at line 294 of file SymbolManager.h.
Referenced by clang::ento::SymbolManager::getCastSymbol(), and Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp