clang: clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData > Class Template Reference
clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData > Class Template Reference
A metaprogramming base class for TypeLoc classes which correspond to a particular Type subclass.
#include "clang/AST/TypeLoc.h"
Classes
struct HasNoInnerType
Public Member Functions
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Protected Member Functions
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
LocalData * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Friends
class TypeLoc
Detailed Description
template<class Base, class Derived, class TypeClass, class LocalData>
class clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
A metaprogramming base class for TypeLoc classes which correspond to a particular Type subclass.
It is accepted for a single TypeLoc class to correspond to multiple Type classes.
Template Parameters
Base a class from which to derive
Derived the class deriving from this one
TypeClass the concrete Type subclass associated with this location type
LocalData the structure type of local location data for this type
TypeLocs with non-constant amounts of local data should override getExtraLocalDataSize(); getExtraLocalData() will then point to this extra memory.
TypeLocs with an inner type should define QualType getInnerType() const and getInnerTypeLoc() will then point to this inner type's location data.
A word about hierarchies: this template is not designed to be derived from multiple times in a hierarchy. It is also not designed to be used for classes where subtypes might provide different amounts of source information. It should be subclassed only at the deepest portion of the hierarchy where all children have identical source information; if that's an abstract type, then further descendents should inherit from InheritingConcreteTypeLoc instead.
Definition at line 361 of file TypeLoc.h.
Member Function Documentation
copyLocal()
template<class Base , class Derived , class TypeClass , class LocalData > void clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal (Derived other) inline
Definition at line 391 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalData(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataSize(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataSize(), and memcpy().
getExtraLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > void * clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalData () const inline protected
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
because it's of variable size).
Definition at line 429 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getExtraLocalDataAlignment()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataAlignment () const inline protected
Definition at line 418 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataAlignment().
getExtraLocalDataSize()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataSize () const inline protected
Definition at line 414 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getInnerType()
template<class Base , class Derived , class TypeClass , class LocalData > HasNoInnerType clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType () const inline protected
Definition at line 444 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc(), and clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc().
getInnerTypeLoc()
template<class Base , class Derived , class TypeClass , class LocalData > TypeLoc clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc () const inline protected
Definition at line 446 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNonLocalData(), and clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::TypeLoc.
getLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > LocalData * clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData () const inline protected
Definition at line 422 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getLocalDataAlignment()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataAlignment () const inline
Definition at line 378 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataAlignment().
getLocalDataSize()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataSize () const inline
Definition at line 383 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getNextTypeLoc()
template<class Base , class Derived , class TypeClass , class LocalData > TypeLoc clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc () const inline
Definition at line 405 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType(), and clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc().
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc(), and GetTypeSourceInfoForDeclarator().
getNonLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > void * clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNonLocalData () const inline protected
Definition at line 436 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc().
getTypePtr()
template<class Base , class Derived , class TypeClass , class LocalData > const TypeClass * clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr () const inline
Definition at line 409 of file TypeLoc.h.
References clang::cast().
Referenced by AddObjCProperties(), clang::DEF_TRAVERSE_TYPELOC(), clang::DEF_TRAVERSE_TYPELOC(), fillAttributedTypeLoc(), clang::Sema::getTemplateArgumentPackExpansionPattern(), GetTypeSourceInfoForDeclarator(), isEnableIf(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformFunctionTypeParams(), clang::TreeTransform< Derived >::TransformReferenceType(), clang::TreeTransform< Derived >::TransformTemplateSpecializationType(), clang::RecursiveASTVisitor< Derived >::VisitTargetAttr(), clang::RecursiveASTVisitor< Derived >::VisitWarnUnusedAttr(), and clang::RecursiveASTVisitor< Derived >::VisitWarnUnusedResultAttr().
Friends And Related Symbol Documentation
TypeLoc
template<class Base , class Derived , class TypeClass , class LocalData > friend class TypeLoc friend
Definition at line 362 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h