clang: clang::comments::Comment Class Reference
clang::comments::Comment Class Reference
Any part of the comment.
#include "clang/AST/Comment.h"
Classes
class BlockCommandCommentBitfields
class CommentBitfields
class HTMLStartTagCommentBitfields
class HTMLTagCommentBitfields
class InlineCommandCommentBitfields
class InlineContentCommentBitfields
class ParagraphCommentBitfields
class ParamCommandCommentBitfields
class TextCommentBitfields
Public Types
enum CommentKind { NoCommentKind = 0 }
typedef Comment *const * child_iterator
Public Member Functions
Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
CommentKind getCommentKind () const
const char * getCommentKindName () const
void dump () const
void dumpColor () const
void dump (raw_ostream &OS, const ASTContext &Context) const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const LLVM_READONLY
child_iterator child_begin () const
child_iterator child_end () const
unsigned child_count () const
Protected Types
enum { NumCommentBits = 8 }
enum { NumInlineContentCommentBits = NumCommentBits + 1 }
enum { NumTextCommentBits = NumInlineContentCommentBits + 2 }
enum { NumInlineCommandCommentBits }
enum { NumHTMLTagCommentBits = NumInlineContentCommentBits + 1 }
enum { NumHTMLStartTagCommentBits = NumHTMLTagCommentBits + 1 }
enum { NumParagraphCommentBits = NumCommentBits + 2 }
enum { NumBlockCommandCommentBits }
enum { NumParamCommandCommentBits = NumBlockCommandCommentBits + 3 }
Protected Member Functions
void setSourceRange (SourceRange SR)
void setLocation (SourceLocation L)
Protected Attributes
SourceLocation Loc
Preferred location to show caret.
SourceRange Range
Source range of this AST node.
union {
CommentBitfields CommentBits
InlineContentCommentBitfields InlineContentCommentBits
TextCommentBitfields TextCommentBits
InlineCommandCommentBitfields InlineCommandCommentBits
HTMLTagCommentBitfields HTMLTagCommentBits
HTMLStartTagCommentBitfields HTMLStartTagCommentBits
ParagraphCommentBitfields ParagraphCommentBits
BlockCommandCommentBitfields BlockCommandCommentBits
ParamCommandCommentBitfields ParamCommandCommentBits
};
Detailed Description
Any part of the comment.
Abstract class.
Definition at line 52 of file Comment.h.
Member Typedef Documentation
child_iterator
Comment* const* clang::comments::Comment::child_iterator
Definition at line 222 of file Comment.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NumHTMLStartTagCommentBits
Definition at line 123 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumParagraphCommentBits
Definition at line 136 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumBlockCommandCommentBits
Definition at line 149 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumParamCommandCommentBits
Definition at line 163 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumCommentBits
Definition at line 66 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumInlineContentCommentBits
Definition at line 77 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumTextCommentBits
Definition at line 90 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumInlineCommandCommentBits
Definition at line 101 of file Comment.h.
anonymous enum
anonymous enum protected
Enumerator
NumHTMLTagCommentBits
Definition at line 112 of file Comment.h.
CommentKind
enum clang::comments::Comment::CommentKind
Enumerator
NoCommentKind
Definition at line 186 of file Comment.h.
Constructor & Destructor Documentation
Comment()
clang::comments::Comment::Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd) inline
Definition at line 197 of file Comment.h.
References CommentBits.
Member Function Documentation
child_begin()
Comment::child_iterator clang::comments::Comment::child_begin () const
Definition at line 82 of file Comment.cpp.
References getCommentKind(), and NoCommentKind.
Referenced by child_count().
child_count()
unsigned clang::comments::Comment::child_count () const inline
Definition at line 229 of file Comment.h.
References child_begin(), and child_end().
child_end()
Comment::child_iterator clang::comments::Comment::child_end () const
Definition at line 96 of file Comment.cpp.
References getCommentKind(), and NoCommentKind.
Referenced by child_count().
dump() [1/2]
LLVM_DUMP_METHOD void Comment::dump () const
Definition at line 251 of file ASTDumper.cpp.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
dump() [2/2]
LLVM_DUMP_METHOD void Comment::dump (raw_ostream & OS, const ASTContext & Context) const
Definition at line 259 of file ASTDumper.cpp.
References clang::ASTContext::getDiagnostics(), clang::DiagnosticsEngine::getShowColors(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
dumpColor()
LLVM_DUMP_METHOD void Comment::dumpColor () const
Definition at line 268 of file ASTDumper.cpp.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
getBeginLoc()
SourceLocation clang::comments::Comment::getBeginLoc () const inline
Definition at line 216 of file Comment.h.
References clang::SourceRange::getBegin(), and Range.
Referenced by clang::comments::BlockCommandComment::getCommandNameBeginLoc(), clang::comments::BlockCommandComment::getCommandNameRange(), clang::comments::InlineCommandComment::getCommandNameRange(), clang::comments::BlockCommandComment::setArgs(), and clang::comments::BlockCommandComment::setParagraph().
getCommentKind()
CommentKind clang::comments::Comment::getCommentKind () const inline
Definition at line 204 of file Comment.h.
References CommentBits.
Referenced by child_begin(), child_end(), and getCommentKindName().
getCommentKindName()
const char * clang::comments::Comment::getCommentKindName () const
Definition at line 35 of file Comment.cpp.
References getCommentKind(), and NoCommentKind.
getEndLoc()
SourceLocation clang::comments::Comment::getEndLoc () const inline
Definition at line 218 of file Comment.h.
References clang::SourceRange::getEnd(), and Range.
Referenced by clang::comments::InlineCommandComment::getCommandNameRange(), clang::comments::VerbatimLineComment::getTextRange(), and clang::comments::BlockCommandComment::setParagraph().
getLocation()
SourceLocation clang::comments::Comment::getLocation () const inline
Definition at line 220 of file Comment.h.
References Loc.
Referenced by clang::comments::Sema::actOnFullComment(), clang::comments::Sema::actOnHTMLEndTag(), clang::comments::Sema::actOnParamCommandStart(), clang::comments::Sema::actOnTParamCommandParamNameArg(), clang::comments::Sema::actOnTParamCommandStart(), clang::comments::Sema::checkBlockCommandDuplicate(), clang::comments::Sema::checkContainerDecl(), clang::comments::Sema::checkContainerDeclVerbatimLine(), clang::comments::Sema::checkDeprecatedCommand(), clang::comments::Sema::checkFunctionDeclVerbatimLine(), clang::comments::Sema::checkReturnsCommand(), clang::comments::HTMLTagComment::getTagNameSourceRange(), clang::comments::Parser::parseHTMLStartTag(), and clang::comments::Sema::resolveParamCommandIndexes().
getSourceRange()
SourceRange clang::comments::Comment::getSourceRange () const inline
Definition at line 214 of file Comment.h.
References Range.
Referenced by clang::comments::Sema::actOnFullComment(), clang::comments::Sema::actOnHTMLEndTag(), clang::comments::Sema::checkBlockCommandDuplicate(), clang::comments::Sema::checkBlockCommandEmptyParagraph(), clang::comments::Sema::checkContainerDecl(), clang::comments::Sema::checkContainerDeclVerbatimLine(), clang::comments::Sema::checkDeprecatedCommand(), clang::comments::Sema::checkFunctionDeclVerbatimLine(), clang::comments::Sema::checkReturnsCommand(), and clang::comments::Parser::parseHTMLStartTag().
setLocation()
void clang::comments::Comment::setLocation (SourceLocation L) inline protected
Definition at line 181 of file Comment.h.
References Loc.
Referenced by clang::comments::BlockCommandComment::BlockCommandComment(), clang::comments::BlockCommandComment::BlockCommandComment(), clang::comments::FullComment::FullComment(), clang::comments::HTMLTagComment::HTMLTagComment(), and clang::comments::ParagraphComment::ParagraphComment().
setSourceRange()
void clang::comments::Comment::setSourceRange (SourceRange SR) inline protected
Definition at line 177 of file Comment.h.
References Range.
Referenced by clang::comments::FullComment::FullComment(), clang::comments::ParagraphComment::ParagraphComment(), clang::comments::BlockCommandComment::setArgs(), and clang::comments::BlockCommandComment::setParagraph().
Member Data Documentation
[union]
union { ... } clang::comments::Comment
BlockCommandCommentBits
BlockCommandCommentBitfields clang::comments::Comment::BlockCommandCommentBits
Definition at line 173 of file Comment.h.
Referenced by clang::comments::BlockCommandComment::BlockCommandComment(), clang::comments::BlockCommandComment::BlockCommandComment(), clang::comments::BlockCommandComment::getCommandID(), and clang::comments::BlockCommandComment::getCommandMarker().
CommentBits
CommentBitfields clang::comments::Comment::CommentBits
Definition at line 166 of file Comment.h.
Referenced by Comment(), and getCommentKind().
HTMLStartTagCommentBits
HTMLStartTagCommentBitfields clang::comments::Comment::HTMLStartTagCommentBits
Definition at line 171 of file Comment.h.
Referenced by clang::comments::HTMLStartTagComment::HTMLStartTagComment(), clang::comments::HTMLStartTagComment::isSelfClosing(), and clang::comments::HTMLStartTagComment::setSelfClosing().
HTMLTagCommentBits
HTMLTagCommentBitfields clang::comments::Comment::HTMLTagCommentBits
Definition at line 170 of file Comment.h.
Referenced by clang::comments::HTMLTagComment::HTMLTagComment(), clang::comments::HTMLTagComment::isMalformed(), and clang::comments::HTMLTagComment::setIsMalformed().
InlineCommandCommentBits
InlineCommandCommentBitfields clang::comments::Comment::InlineCommandCommentBits
Definition at line 169 of file Comment.h.
Referenced by clang::comments::InlineCommandComment::getCommandID(), clang::comments::InlineCommandComment::getRenderKind(), and clang::comments::InlineCommandComment::InlineCommandComment().
InlineContentCommentBits
InlineContentCommentBitfields clang::comments::Comment::InlineContentCommentBits
Definition at line 167 of file Comment.h.
Referenced by clang::comments::InlineContentComment::addTrailingNewline(), and clang::comments::InlineContentComment::hasTrailingNewline().
Loc
SourceLocation clang::comments::Comment::Loc protected
Preferred location to show caret.
Definition at line 55 of file Comment.h.
Referenced by getLocation(), and setLocation().
ParagraphCommentBits
ParagraphCommentBitfields clang::comments::Comment::ParagraphCommentBits
Definition at line 172 of file Comment.h.
Referenced by clang::comments::ParagraphComment::isWhitespace(), and clang::comments::ParagraphComment::ParagraphComment().
ParamCommandCommentBits
ParamCommandCommentBitfields clang::comments::Comment::ParamCommandCommentBits
Definition at line 174 of file Comment.h.
Referenced by clang::comments::ParamCommandComment::getDirection(), clang::comments::ParamCommandComment::isDirectionExplicit(), clang::comments::ParamCommandComment::ParamCommandComment(), and clang::comments::ParamCommandComment::setDirection().
Range
SourceRange clang::comments::Comment::Range protected
Source range of this AST node.
Definition at line 58 of file Comment.h.
Referenced by getBeginLoc(), getEndLoc(), getSourceRange(), clang::comments::HTMLStartTagComment::setAttrs(), clang::comments::HTMLStartTagComment::setGreaterLoc(), and setSourceRange().
TextCommentBits
TextCommentBitfields clang::comments::Comment::TextCommentBits
Definition at line 168 of file Comment.h.
Referenced by clang::comments::TextComment::isWhitespace().
The documentation for this class was generated from the following files:
include/clang/AST/Comment.h
lib/AST/ASTDumper.cpp
lib/AST/Comment.cpp