clang: clang::Sema::SFINAETrap Class Reference
clang::Sema::SFINAETrap Class Reference
RAII class used to determine whether SFINAE has trapped any errors that occur during template argument deduction.
#include "clang/Sema/Sema.h"
Public Member Functions
SFINAETrap (Sema &SemaRef, bool AccessCheckingSFINAE=false)
~SFINAETrap ()
bool hasErrorOccurred () const
Determine whether any SFINAE errors have been trapped.
Detailed Description
RAII class used to determine whether SFINAE has trapped any errors that occur during template argument deduction.
Definition at line 8986 of file Sema.h.
Constructor & Destructor Documentation
SFINAETrap()
clang::Sema::SFINAETrap::SFINAETrap (Sema & SemaRef, bool AccessCheckingSFINAE = false) inline explicit
Definition at line 8994 of file Sema.h.
References clang::Sema::AccessCheckingSFINAE, clang::Sema::InNonInstantiationSFINAEContext, and clang::Sema::isSFINAEContext().
~SFINAETrap()
clang::Sema::SFINAETrap::~SFINAETrap () inline
Definition at line 9007 of file Sema.h.
References clang::Sema::AccessCheckingSFINAE, clang::Sema::getDiagnostics(), clang::Sema::InNonInstantiationSFINAEContext, clang::Sema::NumSFINAEErrors, and clang::DiagnosticsEngine::setLastDiagnosticIgnored().
Member Function Documentation
hasErrorOccurred()
bool clang::Sema::SFINAETrap::hasErrorOccurred () const inline
Determine whether any SFINAE errors have been trapped.
Definition at line 9017 of file Sema.h.
References clang::Sema::NumSFINAEErrors.
Referenced by clang::Sema::BuildMemberReferenceExpr(), calculateConstraintSatisfaction(), convertArgsForAvailabilityChecks(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DeduceTemplateArguments(), DiagnoseInvalidRedeclaration(), EvaluateBinaryTypeTrait(), evaluateTypeTrait(), clang::Sema::FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), FinishTemplateArgumentDeduction(), clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs(), clang::Sema::LookupLiteralOperator(), and clang::Sema::SubstituteExplicitTemplateArguments().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h