clang: clang::ASTRecordReader Class Reference
clang::ASTRecordReader Class Reference
An object for streaming information from a record.
#include "clang/Serialization/ASTRecordReader.h"
Public Member Functions
ASTRecordReader (ASTReader &Reader, ModuleFile &F)
Construct an ASTRecordReader that uses the default encoding scheme.
Expected< unsigned > readRecord (llvm::BitstreamCursor &Cursor, unsigned AbbrevID)
Reads a record with id AbbrevID from Cursor, resetting the internal state.
bool isModule () const
Is this a module file for a module (rather than a PCH or similar).
ASTContext & getContext ()
Retrieve the AST context that this AST reader supplements.
unsigned getIdx () const
The current position in this record.
size_t size () const
The length of this record.
const uint64_t & operator[] (size_t N)
An arbitrary index in this record.
uint64_t back ()
Returns the last value in this record.
uint64_t readInt ()
Returns the current value in this record, and advances to the next value.
ArrayRef< uint64_t > readIntArray (unsigned Len)
uint64_t peekInt ()
Returns the current value in this record, without advancing.
void skipInts (unsigned N)
Skips the specified number of values.
serialization::SubmoduleID getGlobalSubmoduleID (unsigned LocalID)
Retrieve the global submodule ID its local ID number.
Module * getSubmodule (serialization::SubmoduleID GlobalID)
Retrieve the submodule that corresponds to a global submodule ID.
bool readLexicalDeclContextStorage (uint64_t Offset, DeclContext *DC)
Read the record that describes the lexical contents of a DC.
bool readVisibleDeclContextStorage (uint64_t Offset, serialization::DeclID ID)
Read the record that describes the visible contents of a DC.
ExplicitSpecifier readExplicitSpec ()
uint64_t getGlobalBitOffset (uint64_t LocalOffset)
Read information about an exception specification (inherited).
Stmt * readStmt ()
Reads a statement.
Stmt * readStmtRef ()
Expr * readExpr ()
Reads an expression.
Stmt * readSubStmt ()
Reads a sub-statement operand during statement reading.
Expr * readSubExpr ()
Reads a sub-expression operand during statement reading.
template<typename T >
T * GetLocalDeclAs (uint32_t LocalID)
Reads a declaration with the given local ID in the given module.
TemplateArgumentLocInfo readTemplateArgumentLocInfo (TemplateArgument::ArgKind Kind)
Reads a TemplateArgumentLocInfo appropriate for the given TemplateArgument kind, advancing Idx.
TemplateArgumentLoc readTemplateArgumentLoc ()
Reads a TemplateArgumentLoc, advancing Idx.
const ASTTemplateArgumentListInfo * readASTTemplateArgumentListInfo ()
TypeSourceInfo * readTypeSourceInfo ()
Reads a declarator info from the given record, advancing Idx.
void readTypeLoc (TypeLoc TL)
Reads the location information for a type.
serialization::TypeID getGlobalTypeID (unsigned LocalID) const
Map a local type ID within a given AST file to a global type ID.
Qualifiers readQualifiers ()
QualType readType ()
Read a type from the current position in the record.
QualType readQualType ()
serialization::DeclID readDeclID ()
Reads a declaration ID from the given position in this record.
Decl * readDecl ()
Reads a declaration from the given position in a record in the given module, advancing Idx.
Decl * readDeclRef ()
template<typename T >
T * readDeclAs ()
Reads a declaration from the given position in the record, advancing Idx.
IdentifierInfo * readIdentifier ()
Selector readSelector ()
Read a selector from the Record, advancing Idx.
DeclarationNameLoc readDeclarationNameLoc (DeclarationName Name)
Read a declaration name, advancing Idx.
DeclarationNameInfo readDeclarationNameInfo ()
void readQualifierInfo (QualifierInfo &Info)
NestedNameSpecifierLoc readNestedNameSpecifierLoc ()
Return a nested name specifier, advancing Idx.
TemplateArgument readTemplateArgument (bool Canonicalize)
TemplateParameterList * readTemplateParameterList ()
Read a template parameter list, advancing Idx.
void readTemplateArgumentList (SmallVectorImpl< TemplateArgument > &TemplArgs, bool Canonicalize=false)
Read a template argument array, advancing Idx.
void readUnresolvedSet (LazyASTUnresolvedSet &Set)
Read a UnresolvedSet structure, advancing Idx.
CXXBaseSpecifier readCXXBaseSpecifier ()
Read a C++ base specifier, advancing Idx.
CXXCtorInitializer ** readCXXCtorInitializers ()
Read a CXXCtorInitializer array, advancing Idx.
CXXTemporary * readCXXTemporary ()
OMPTraitInfo * readOMPTraitInfo ()
Read an OMPTraitInfo object, advancing Idx.
OMPClause * readOMPClause ()
Read an OpenMP clause, advancing Idx.
void readOMPChildren (OMPChildren *Data)
Read an OpenMP children, advancing Idx.
SourceLocation readSourceLocation ()
Read a source location, advancing Idx.
SourceRange readSourceRange ()
Read a source range, advancing Idx.
llvm::APFloat readAPFloat (const llvm::fltSemantics &Sem)
Read an arbitrary constant value, advancing Idx.
bool readBool ()
Read a boolean value, advancing Idx.
uint32_t readUInt32 ()
Read a 32-bit unsigned value; required to satisfy BasicReader.
uint64_t readUInt64 ()
Read a 64-bit unsigned value; required to satisfy BasicReader.
std::string readString ()
Read a string, advancing Idx.
std::string readPath ()
Read a path, advancing Idx.
VersionTuple readVersionTuple ()
Read a version tuple, advancing Idx.
Attr * readAttr ()
Reads one attribute from the current stream position, advancing Idx.
void readAttributes (AttrVec &Attrs)
Reads attributes from the current stream position, advancing Idx.
Token readToken ()
Reads a token out of a record, advancing Idx.
void recordSwitchCaseID (SwitchCase *SC, unsigned ID)
SwitchCase * getSwitchCaseWithID (unsigned ID)
Retrieve the switch-case statement with the given ID.
Public Member Functions inherited from clang::serialization::DataStreamBasicReader< ASTRecordReader >
ASTRecordReader & find (const char *propertyName)
Implement property-find by ignoring it.
T readEnum ()
ASTRecordReader & readObject ()
llvm::ArrayRef< T > readArray (llvm::SmallVectorImpl< T > &buffer)
llvm::Optional< T > readOptional (Args &&...args)
llvm::APSInt readAPSInt ()
llvm::APInt readAPInt ()
llvm::FixedPointSemantics readFixedPointSemantics ()
APValue::LValuePathSerializationHelper readLValuePathSerializationHelper (SmallVectorImpl< APValue::LValuePathEntry > &path)
Qualifiers readQualifiers ()
FunctionProtoType::ExceptionSpecInfo readExceptionSpecInfo (llvm::SmallVectorImpl< QualType > &buffer)
FunctionProtoType::ExtParameterInfo readExtParameterInfo ()
NestedNameSpecifier * readNestedNameSpecifier ()
Public Member Functions inherited from clang::serialization::BasicReaderBase< ASTRecordReader >
ASTContext & getASTContext ()
Impl & asImpl ()
APValue readAPValue ()
APValue::ValueKind readAPValueKind ()
ArrayType::ArraySizeModifier readArraySizeModifier ()
attr::Kind readAttrKind ()
AutoTypeKeyword readAutoTypeKeyword ()
BuiltinType::Kind readBuiltinTypeKind ()
CXXRecordDecl * readCXXRecordDeclRef ()
CallingConv readCallingConv ()
ConceptDecl * readConceptDeclRef ()
DeclarationName readDeclarationName ()
DeclarationName::NameKind readDeclarationNameKind ()
ElaboratedTypeKeyword readElaboratedTypeKeyword ()
Expr * readExprRef ()
FunctionDecl * readFunctionDeclRef ()
NamedDecl * readNamedDeclRef ()
NamespaceAliasDecl * readNamespaceAliasDeclRef ()
NamespaceDecl * readNamespaceDeclRef ()
NestedNameSpecifier::SpecifierKind readNestedNameSpecifierKind ()
ObjCProtocolDecl * readObjCProtocolDeclRef ()
ObjCTypeParamDecl * readObjCTypeParamDeclRef ()
OverloadedOperatorKind readOverloadedOperatorKind ()
RefQualifierKind readRefQualifierKind ()
TagDecl * readTagDeclRef ()
TemplateArgument readTemplateArgument ()
TemplateArgument::ArgKind readTemplateArgumentKind ()
TemplateDecl * readTemplateDeclRef ()
TemplateName readTemplateName ()
TemplateName::NameKind readTemplateNameKind ()
TemplateTemplateParmDecl * readTemplateTemplateParmDeclRef ()
TemplateTypeParmDecl * readTemplateTypeParmDeclRef ()
UnaryTransformType::UTTKind readUnaryTypeTransformKind ()
ValueDecl * readValueDeclRef ()
VectorType::VectorKind readVectorKind ()
Additional Inherited Members
Protected Member Functions inherited from clang::serialization::DataStreamBasicReader< ASTRecordReader >
DataStreamBasicReader (ASTContext &ctx)
Protected Member Functions inherited from clang::serialization::BasicReaderBase< ASTRecordReader >
BasicReaderBase (ASTContext &ctx)
Detailed Description
An object for streaming information from a record.
Definition at line 30 of file ASTRecordReader.h.
Constructor & Destructor Documentation
ASTRecordReader()
clang::ASTRecordReader::ASTRecordReader (ASTReader & Reader, ModuleFile & F) inline
Construct an ASTRecordReader that uses the default encoding scheme.
Definition at line 44 of file ASTRecordReader.h.
Member Function Documentation
back()
uint64_t clang::ASTRecordReader::back () inline
Returns the last value in this record.
Definition at line 68 of file ASTRecordReader.h.
Referenced by clang::ASTDeclReader::VisitImportDecl().
getContext()
ASTContext & clang::ASTRecordReader::getContext () inline
Retrieve the AST context that this AST reader supplements.
Definition at line 56 of file ASTRecordReader.h.
References clang::ASTReader::getContext().
Referenced by readAttr(), readCXXCtorInitializers(), readNestedNameSpecifierLoc(), readOMPTraitInfo(), readQualifierInfo(), readTemplateArgument(), readTemplateParameterList(), and readUnresolvedSet().
getGlobalBitOffset()
uint64_t clang::ASTRecordReader::getGlobalBitOffset (uint64_t LocalOffset) inline
Read information about an exception specification (inherited).
Get the global offset corresponding to a local offset.
Definition at line 123 of file ASTRecordReader.h.
getGlobalSubmoduleID()
serialization::SubmoduleID clang::ASTRecordReader::getGlobalSubmoduleID (unsigned LocalID) inline
Retrieve the global submodule ID its local ID number.
Definition at line 88 of file ASTRecordReader.h.
References clang::ASTReader::getGlobalSubmoduleID().
getGlobalTypeID()
serialization::TypeID clang::ASTRecordReader::getGlobalTypeID (unsigned LocalID) const inline
Map a local type ID within a given AST file to a global type ID.
Definition at line 167 of file ASTRecordReader.h.
References clang::ASTReader::getGlobalTypeID().
Referenced by clang::ASTDeclReader::VisitObjCInterfaceDecl(), clang::ASTDeclReader::VisitTypeDecl(), and clang::ASTDeclReader::VisitValueDecl().
getIdx()
unsigned clang::ASTRecordReader::getIdx () const inline
The current position in this record.
Definition at line 59 of file ASTRecordReader.h.
Referenced by clang::ASTStmtReader::VisitStmt().
GetLocalDeclAs()
template<typename T > T * clang::ASTRecordReader::GetLocalDeclAs (uint32_t LocalID) inline
Reads a declaration with the given local ID in the given module.
Returns
The requested declaration, casted to the given return type.
Definition at line 144 of file ASTRecordReader.h.
References clang::ASTReader::GetLocalDecl().
getSubmodule()
Module * clang::ASTRecordReader::getSubmodule (serialization::SubmoduleID GlobalID) inline
Retrieve the submodule that corresponds to a global submodule ID.
Definition at line 93 of file ASTRecordReader.h.
References clang::ASTReader::getSubmodule().
getSwitchCaseWithID()
SwitchCase * clang::ASTRecordReader::getSwitchCaseWithID (unsigned ID) inline
Retrieve the switch-case statement with the given ID.
Definition at line 339 of file ASTRecordReader.h.
References clang::ASTReader::getSwitchCaseWithID().
isModule()
bool clang::ASTRecordReader::isModule () const inline
Is this a module file for a module (rather than a PCH or similar).
Definition at line 53 of file ASTRecordReader.h.
References clang::serialization::ModuleFile::isModule().
Referenced by clang::ASTDeclReader::VisitNamespaceDecl().
operator[]()
const uint64_t & clang::ASTRecordReader::operator[] (size_t N) inline
An arbitrary index in this record.
Definition at line 65 of file ASTRecordReader.h.
References N.
peekInt()
uint64_t clang::ASTRecordReader::peekInt () inline
Returns the current value in this record, without advancing.
Definition at line 81 of file ASTRecordReader.h.
readAPFloat()
llvm::APFloat ASTRecordReader::readAPFloat (const llvm::fltSemantics & Sem)
Read an arbitrary constant value, advancing Idx.
Read a floating-point value.
Read an integral value, advancing Idx. Read a signed integral value, advancing Idx. Read a floating-point value, advancing Idx.
Definition at line 8982 of file ASTReader.cpp.
References clang::serialization::DataStreamBasicReader< ASTRecordReader >::readAPInt().
readASTTemplateArgumentListInfo()
const ASTTemplateArgumentListInfo * ASTRecordReader::readASTTemplateArgumentListInfo ()
Definition at line 7153 of file ASTReader.cpp.
References clang::TemplateArgumentListInfo::addArgument(), and clang::ASTTemplateArgumentListInfo::Create().
Referenced by clang::ASTDeclReader::VisitClassScopeFunctionSpecializationDecl(), clang::ASTDeclReader::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclReader::VisitTemplateTypeParmDecl(), and clang::ASTDeclReader::VisitVarTemplatePartialSpecializationDecl().
readAttr()
Attr * ASTRecordReader::readAttr ()
Reads one attribute from the current stream position, advancing Idx.
Definition at line 2769 of file ASTReaderDecl.cpp.
References getContext(), and V.
Referenced by readAttributes().
readAttributes()
void ASTRecordReader::readAttributes (AttrVec & Attrs)
Reads attributes from the current stream position, advancing Idx.
Reads attributes from the current stream position.
Definition at line 2800 of file ASTReaderDecl.cpp.
References readAttr(), and readInt().
Referenced by clang::ASTDeclReader::VisitDecl().
readBool()
bool clang::ASTRecordReader::readBool () inline
Read a boolean value, advancing Idx.
Definition at line 296 of file ASTRecordReader.h.
References readInt().
Referenced by readCXXBaseSpecifier(), readCXXCtorInitializers(), readNestedNameSpecifierLoc(), readOMPTraitInfo(), readTemplateParameterList(), and clang::ASTDeclReader::VisitTemplateTypeParmDecl().
readCXXBaseSpecifier()
CXXBaseSpecifier ASTRecordReader::readCXXBaseSpecifier ()
Read a C++ base specifier, advancing Idx.
Definition at line 8832 of file ASTReader.cpp.
References readBool(), readInt(), readSourceLocation(), readSourceRange(), readTypeSourceInfo(), and clang::Result.
readCXXCtorInitializers()
CXXCtorInitializer ** ASTRecordReader::readCXXCtorInitializers ()
Read a CXXCtorInitializer array, advancing Idx.
Definition at line 8847 of file ASTReader.cpp.
References clang::serialization::CTOR_INITIALIZER_BASE, clang::serialization::CTOR_INITIALIZER_DELEGATING, clang::serialization::CTOR_INITIALIZER_INDIRECT_MEMBER, clang::serialization::CTOR_INITIALIZER_MEMBER, getContext(), clang::Member, readBool(), readDeclAs(), readExpr(), readInt(), readSourceLocation(), readTypeSourceInfo(), and clang::CXXCtorInitializer::setSourceOrder().
readCXXTemporary()
CXXTemporary * clang::ASTRecordReader::readCXXTemporary () inline
Definition at line 260 of file ASTRecordReader.h.
References clang::ASTReader::ReadCXXTemporary().
readDecl()
Decl * clang::ASTRecordReader::readDecl () inline
Reads a declaration from the given position in a record in the given module, advancing Idx.
Definition at line 192 of file ASTRecordReader.h.
References clang::ASTReader::ReadDecl().
Referenced by readDeclRef().
readDeclarationNameInfo()
DeclarationNameInfo ASTRecordReader::readDeclarationNameInfo ()
Definition at line 8771 of file ASTReader.cpp.
References clang::DeclarationNameInfo::getName(), clang::serialization::BasicReaderBase< ASTRecordReader >::readDeclarationName(), readDeclarationNameLoc(), readSourceLocation(), clang::DeclarationNameInfo::setInfo(), clang::DeclarationNameInfo::setLoc(), and clang::DeclarationNameInfo::setName().
Referenced by clang::ASTDeclReader::VisitTemplateTypeParmDecl().
readDeclarationNameLoc()
DeclarationNameLoc ASTRecordReader::readDeclarationNameLoc (DeclarationName Name)
Read a declaration name, advancing Idx.
Definition at line 8739 of file ASTReader.cpp.
References clang::DeclarationNameLoc::CXXOpName::BeginOpNameLoc, clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationNameLoc::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationNameLoc::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationNameLoc::CXXOpName::EndOpNameLoc, clang::SourceLocation::getRawEncoding(), clang::DeclarationName::Identifier, clang::DeclarationNameLoc::NamedType, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::DeclarationNameLoc::CXXLitOpName::OpNameLoc, readSourceLocation(), readTypeSourceInfo(), and clang::DeclarationNameLoc::NT::TInfo.
Referenced by readDeclarationNameInfo(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclReader::VisitUnresolvedUsingValueDecl(), and clang::ASTDeclReader::VisitUsingDecl().
readDeclAs()
template<typename T > T * clang::ASTRecordReader::readDeclAs () inline
Reads a declaration from the given position in the record, advancing Idx.
Returns
The declaration read from this location, casted to the given result type.
Definition at line 205 of file ASTRecordReader.h.
References clang::ASTReader::ReadDeclAs().
Referenced by readCXXCtorInitializers(), readNestedNameSpecifierLoc(), readTemplateParameterList(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::ASTDeclReader::VisitTemplateTypeParmDecl().
readDeclID()
serialization::DeclID clang::ASTRecordReader::readDeclID () inline
Reads a declaration ID from the given position in this record.
Returns
The declaration ID read from the record, adjusted to a global ID.
Definition at line 186 of file ASTRecordReader.h.
References clang::ASTReader::ReadDeclID().
Referenced by readUnresolvedSet().
readDeclRef()
Decl * clang::ASTRecordReader::readDeclRef () inline
Definition at line 195 of file ASTRecordReader.h.
References readDecl().
readExplicitSpec()
ExplicitSpecifier clang::ASTRecordReader::readExplicitSpec () inline
Definition at line 110 of file ASTRecordReader.h.
References readExpr(), and readInt().
Referenced by clang::ASTDeclReader::VisitCXXConstructorDecl(), clang::ASTDeclReader::VisitCXXConversionDecl(), and clang::ASTDeclReader::VisitCXXDeductionGuideDecl().
readExpr()
Expr * clang::ASTRecordReader::readExpr () inline
Reads an expression.
Definition at line 132 of file ASTRecordReader.h.
References clang::ASTReader::ReadExpr().
Referenced by readCXXCtorInitializers(), readExplicitSpec(), readTemplateParameterList(), clang::ASTDeclReader::VisitBindingDecl(), clang::ASTDeclReader::VisitBlockDecl(), clang::ASTDeclReader::VisitConceptDecl(), clang::ASTDeclReader::VisitCXXDestructorDecl(), clang::ASTDeclReader::VisitDeclaratorDecl(), clang::ASTDeclReader::VisitEnumConstantDecl(), clang::ASTDeclReader::VisitFieldDecl(), clang::ASTDeclReader::VisitFileScopeAsmDecl(), clang::ASTDeclReader::VisitNonTypeTemplateParmDecl(), clang::ASTDeclReader::VisitObjCPropertyImplDecl(), clang::ASTDeclReader::VisitOMPDeclareReductionDecl(), clang::ASTDeclReader::VisitParmVarDecl(), clang::ASTDeclReader::VisitStaticAssertDecl(), clang::ASTDeclReader::VisitTemplateTypeParmDecl(), and clang::ASTDeclReader::VisitVarDeclImpl().
readIdentifier()
IdentifierInfo * clang::ASTRecordReader::readIdentifier () inline
Definition at line 209 of file ASTRecordReader.h.
References clang::ASTReader::readIdentifier().
Referenced by readNestedNameSpecifierLoc(), clang::ASTDeclReader::VisitMSPropertyDecl(), and clang::ASTDeclReader::VisitTagDecl().
readInt()
uint64_t clang::ASTRecordReader::readInt () inline
Returns the current value in this record, and advances to the next value.
Definition at line 72 of file ASTRecordReader.h.
Referenced by readAttributes(), readBool(), readCXXBaseSpecifier(), readCXXCtorInitializers(), readExplicitSpec(), clang::ASTDeclReader::ReadFunctionDefinition(), readNestedNameSpecifierLoc(), clang::ASTDeclReader::ReadObjCTypeParamList(), readQualifierInfo(), readQualifiers(), readTemplateArgumentList(), readTemplateParameterList(), readUInt32(), readUInt64(), readUnresolvedSet(), clang::ASTDeclReader::Visit(), clang::ASTDeclReader::VisitBlockDecl(), clang::ASTDeclReader::VisitCapturedDecl(), clang::ASTDeclReader::VisitClassScopeFunctionSpecializationDecl(), clang::ASTDeclReader::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclReader::VisitClassTemplateSpecializationDeclImpl(), clang::ASTDeclReader::VisitConstructorUsingShadowDecl(), clang::ASTDeclReader::VisitCXXDeductionGuideDecl(), clang::ASTDeclReader::VisitCXXMethodDecl(), clang::ASTDeclReader::VisitCXXRecordDeclImpl(), clang::ASTDeclReader::VisitDecl(), clang::ASTDeclReader::VisitDeclaratorDecl(), clang::ASTDeclReader::VisitEnumConstantDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTDeclReader::VisitFieldDecl(), clang::ASTDeclReader::VisitFriendDecl(), clang::ASTDeclReader::VisitFriendTemplateDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclReader::VisitImportDecl(), clang::ASTDeclReader::VisitIndirectFieldDecl(), clang::ASTDeclReader::VisitLifetimeExtendedTemporaryDecl(), clang::ASTDeclReader::VisitLinkageSpecDecl(), clang::ASTDeclReader::VisitMSGuidDecl(), clang::ASTDeclReader::VisitNamedDecl(), clang::ASTDeclReader::VisitNamespaceDecl(), clang::ASTDeclReader::VisitNonTypeTemplateParmDecl(), clang::ASTDeclReader::VisitObjCCategoryDecl(), clang::ASTDeclReader::VisitObjCImplementationDecl(), clang::ASTDeclReader::VisitObjCInterfaceDecl(), clang::ASTDeclReader::VisitObjCIvarDecl(), clang::ASTDeclReader::VisitObjCMethodDecl(), clang::ASTDeclReader::VisitObjCPropertyDecl(), clang::ASTDeclReader::VisitObjCProtocolDecl(), clang::ASTDeclReader::VisitObjCTypeParamDecl(), clang::ASTDeclReader::VisitOMPDeclareReductionDecl(), clang::ASTDeclReader::VisitParmVarDecl(), clang::ASTDeclReader::VisitPragmaCommentDecl(), clang::ASTDeclReader::VisitRecordDeclImpl(), clang::ASTDeclReader::VisitRedeclarable(), clang::ASTDeclReader::VisitRedeclarableTemplateDecl(), clang::ASTDeclReader::VisitStaticAssertDecl(), clang::ASTDeclReader::VisitTagDecl(), clang::ASTDeclReader::VisitTemplateTemplateParmDecl(), clang::ASTDeclReader::VisitTemplateTypeParmDecl(), clang::ASTDeclReader::VisitTypeDecl(), clang::ASTDeclReader::VisitTypedefNameDecl(), clang::ASTDeclReader::VisitUsingDecl(), clang::ASTDeclReader::VisitUsingShadowDecl(), clang::ASTDeclReader::VisitValueDecl(), clang::ASTDeclReader::VisitVarDeclImpl(), clang::ASTDeclReader::VisitVarTemplatePartialSpecializationDecl(), and clang::ASTDeclReader::VisitVarTemplateSpecializationDeclImpl().
readIntArray()
ArrayRef< uint64_t > clang::ASTRecordReader::readIntArray (unsigned Len) inline
Definition at line 74 of file ASTRecordReader.h.
readLexicalDeclContextStorage()
bool clang::ASTRecordReader::readLexicalDeclContextStorage (uint64_t Offset, DeclContext * DC) inline
Read the record that describes the lexical contents of a DC.
Definition at line 98 of file ASTRecordReader.h.
References clang::serialization::ModuleFile::DeclsCursor, and Offset.
readNestedNameSpecifierLoc()
NestedNameSpecifierLoc ASTRecordReader::readNestedNameSpecifierLoc ()
Return a nested name specifier, advancing Idx.
Definition at line 8912 of file ASTReader.cpp.
References getContext(), clang::NestedNameSpecifierLocBuilder::getWithLocInContext(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, N, clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, readBool(), readDeclAs(), readIdentifier(), readInt(), clang::serialization::BasicReaderBase< ASTRecordReader >::readNestedNameSpecifierKind(), readSourceLocation(), readSourceRange(), readTypeSourceInfo(), clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by readQualifierInfo(), clang::ASTDeclReader::VisitNamespaceAliasDecl(), clang::ASTDeclReader::VisitTemplateTypeParmDecl(), clang::ASTDeclReader::VisitUnresolvedUsingTypenameDecl(), clang::ASTDeclReader::VisitUnresolvedUsingValueDecl(), clang::ASTDeclReader::VisitUsingDecl(), and clang::ASTDeclReader::VisitUsingDirectiveDecl().
readOMPChildren()
void ASTRecordReader::readOMPChildren (OMPChildren * Data)
Read an OpenMP children, advancing Idx.
Definition at line 12916 of file ASTReader.cpp.
References clang::OMPChildren::getChildren(), clang::OMPChildren::getNumChildren(), clang::OMPChildren::getNumClauses(), clang::OMPChildren::hasAssociatedStmt(), readOMPClause(), readStmt(), clang::OMPChildren::setAssociatedStmt(), clang::OMPChildren::setClauses(), and skipInts().
Referenced by clang::ASTDeclReader::VisitOMPAllocateDecl(), clang::ASTDeclReader::VisitOMPDeclareMapperDecl(), clang::ASTDeclReader::VisitOMPRequiresDecl(), and clang::ASTDeclReader::VisitOMPThreadPrivateDecl().
readOMPClause()
OMPClause * ASTRecordReader::readOMPClause ()
Read an OpenMP clause, advancing Idx.
Definition at line 11711 of file ASTReader.cpp.
References clang::OMPClauseReader::readClause().
Referenced by readOMPChildren().
readOMPTraitInfo()
OMPTraitInfo * ASTRecordReader::readOMPTraitInfo ()
Read an OMPTraitInfo object, advancing Idx.
Definition at line 12897 of file ASTReader.cpp.
References getContext(), clang::ASTContext::getNewOMPTraitInfo(), readBool(), clang::serialization::DataStreamBasicReader< ASTRecordReader >::readEnum(), clang::serialization::BasicReaderBase< ASTRecordReader >::readExprRef(), readUInt32(), and clang::OMPTraitInfo::Sets.
readPath()
std::string clang::ASTRecordReader::readPath () inline
Read a path, advancing Idx.
Definition at line 314 of file ASTRecordReader.h.
References clang::ASTReader::ReadPath().
readQualifierInfo()
void ASTRecordReader::readQualifierInfo (QualifierInfo & Info)
Definition at line 8779 of file ASTReader.cpp.
References getContext(), clang::QualifierInfo::NumTemplParamLists, clang::QualifierInfo::QualifierLoc, readInt(), readNestedNameSpecifierLoc(), readTemplateParameterList(), and clang::QualifierInfo::TemplParamLists.
Referenced by clang::ASTDeclReader::VisitDeclaratorDecl(), and clang::ASTDeclReader::VisitTagDecl().
readQualifiers()
Qualifiers clang::ASTRecordReader::readQualifiers () inline
Definition at line 171 of file ASTRecordReader.h.
References clang::Qualifiers::fromOpaqueValue(), and readInt().
readQualType()
QualType clang::ASTRecordReader::readQualType () inline
Definition at line 179 of file ASTRecordReader.h.
References readType().
readRecord()
Expected< unsigned > ASTRecordReader::readRecord (llvm::BitstreamCursor & Cursor, unsigned AbbrevID)
Reads a record with id AbbrevID from Cursor, resetting the internal state.
Definition at line 11680 of file ASTReader.cpp.
readSelector()
Selector clang::ASTRecordReader::readSelector () inline
Read a selector from the Record, advancing Idx.
Definition at line 214 of file ASTRecordReader.h.
References clang::ASTReader::ReadSelector().
readSourceLocation()
SourceLocation clang::ASTRecordReader::readSourceLocation () inline
Read a source location, advancing Idx.
Definition at line 274 of file ASTRecordReader.h.
References clang::ASTReader::ReadSourceLocation().
Referenced by readCXXBaseSpecifier(), readCXXCtorInitializers(), readDeclarationNameInfo(), readDeclarationNameLoc(), readNestedNameSpecifierLoc(), and readTemplateParameterList().
readSourceRange()
SourceRange clang::ASTRecordReader::readSourceRange () inline
Read a source range, advancing Idx.
Definition at line 279 of file ASTRecordReader.h.
References clang::ASTReader::ReadSourceRange().
Referenced by readCXXBaseSpecifier(), and readNestedNameSpecifierLoc().
readStmt()
Stmt * clang::ASTRecordReader::readStmt () inline
Reads a statement.
Definition at line 128 of file ASTRecordReader.h.
References clang::ASTReader::ReadStmt().
Referenced by readOMPChildren(), readStmtRef(), clang::ASTDeclReader::VisitBlockDecl(), and clang::ASTDeclReader::VisitLifetimeExtendedTemporaryDecl().
readStmtRef()
Stmt * clang::ASTRecordReader::readStmtRef () inline
Definition at line 129 of file ASTRecordReader.h.
References readStmt().
readString()
std::string clang::ASTRecordReader::readString () inline
Read a string, advancing Idx.
Definition at line 309 of file ASTRecordReader.h.
References clang::ASTReader::ReadString().
readSubExpr()
Expr * clang::ASTRecordReader::readSubExpr () inline
Reads a sub-expression operand during statement reading.
Definition at line 138 of file ASTRecordReader.h.
References clang::ASTReader::ReadSubExpr().
readSubStmt()
Stmt * clang::ASTRecordReader::readSubStmt () inline
Reads a sub-statement operand during statement reading.
Definition at line 135 of file ASTRecordReader.h.
References clang::ASTReader::ReadSubStmt().
readTemplateArgument()
TemplateArgument clang::ASTRecordReader::readTemplateArgument (bool Canonicalize) inline
Definition at line 236 of file ASTRecordReader.h.
References clang::ASTContext::getCanonicalTemplateArgument(), getContext(), and clang::serialization::BasicReaderBase< ASTRecordReader >::readTemplateArgument().
readTemplateArgumentList()
void ASTRecordReader::readTemplateArgumentList (SmallVectorImpl< TemplateArgument > & TemplArgs, bool Canonicalize = false)
Read a template argument array, advancing Idx.
Definition at line 8811 of file ASTReader.cpp.
References readInt(), and clang::serialization::BasicReaderBase< ASTRecordReader >::readTemplateArgument().
Referenced by clang::ASTDeclReader::VisitClassTemplateSpecializationDeclImpl(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::ASTDeclReader::VisitVarTemplateSpecializationDeclImpl().
readTemplateArgumentLoc()
TemplateArgumentLoc ASTRecordReader::readTemplateArgumentLoc ()
Reads a TemplateArgumentLoc, advancing Idx.
Definition at line 7142 of file ASTReader.cpp.
References clang::TemplateArgument::Expression, clang::TemplateArgument::getAsExpr(), and clang::TemplateArgument::getKind().
Referenced by clang::ASTStmtReader::ReadTemplateKWAndArgsInfo(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::ASTDeclReader::VisitTemplateTemplateParmDecl().
readTemplateArgumentLocInfo()
TemplateArgumentLocInfo ASTRecordReader::readTemplateArgumentLocInfo (TemplateArgument::ArgKind Kind)
Reads a TemplateArgumentLocInfo appropriate for the given TemplateArgument kind, advancing Idx.
Definition at line 7111 of file ASTReader.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
readTemplateParameterList()
TemplateParameterList * ASTRecordReader::readTemplateParameterList ()
Read a template parameter list, advancing Idx.
Definition at line 8792 of file ASTReader.cpp.
References clang::TemplateParameterList::Create(), getContext(), readBool(), readDeclAs(), readExpr(), readInt(), and readSourceLocation().
Referenced by readQualifierInfo(), clang::ASTDeclReader::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclReader::VisitFriendDecl(), clang::ASTDeclReader::VisitFriendTemplateDecl(), clang::ASTDeclReader::VisitTemplateDecl(), clang::ASTDeclReader::VisitTemplateTemplateParmDecl(), and clang::ASTDeclReader::VisitVarTemplatePartialSpecializationDecl().
readToken()
Token clang::ASTRecordReader::readToken () inline
Reads a token out of a record, advancing Idx.
Definition at line 330 of file ASTRecordReader.h.
References clang::ASTReader::ReadToken().
readType()
QualType clang::ASTRecordReader::readType () inline
Read a type from the current position in the record.
Definition at line 176 of file ASTRecordReader.h.
References clang::ASTReader::readType().
Referenced by readQualType(), clang::ASTDeclReader::VisitDeclaratorDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTDeclReader::VisitFieldDecl(), clang::ASTDeclReader::VisitNonTypeTemplateParmDecl(), clang::ASTDeclReader::VisitObjCMethodDecl(), clang::ASTDeclReader::VisitObjCPropertyDecl(), clang::ASTDeclReader::VisitTypedefNameDecl(), and clang::ASTDeclReader::VisitValueDecl().
readTypeLoc()
void ASTRecordReader::readTypeLoc (TypeLoc TL)
Reads the location information for a type.
Definition at line 6799 of file ASTReader.cpp.
References clang::TypeLoc::getNextTypeLoc(), clang::TypeLoc::isNull(), and clang::TypeLocVisitor< ImplClass, RetTy >::Visit().
Referenced by clang::ASTDeclReader::Visit().
readTypeSourceInfo()
TypeSourceInfo * ASTRecordReader::readTypeSourceInfo ()
Reads a declarator info from the given record, advancing Idx.
Definition at line 6805 of file ASTReader.cpp.
References clang::TypeSourceInfo::getTypeLoc(), and clang::QualType::isNull().
Referenced by readCXXBaseSpecifier(), readCXXCtorInitializers(), readDeclarationNameLoc(), and readNestedNameSpecifierLoc().
readUInt32()
uint32_t clang::ASTRecordReader::readUInt32 () inline
Read a 32-bit unsigned value; required to satisfy BasicReader.
Definition at line 299 of file ASTRecordReader.h.
References readInt().
Referenced by readOMPTraitInfo().
readUInt64()
uint64_t clang::ASTRecordReader::readUInt64 () inline
Read a 64-bit unsigned value; required to satisfy BasicReader.
Definition at line 304 of file ASTRecordReader.h.
References readInt().
readUnresolvedSet()
void ASTRecordReader::readUnresolvedSet (LazyASTUnresolvedSet & Set)
Read a UnresolvedSet structure, advancing Idx.
Read a UnresolvedSet structure.
Definition at line 8821 of file ASTReader.cpp.
References clang::LazyASTUnresolvedSet::addLazyDecl(), getContext(), readDeclID(), readInt(), and clang::LazyASTUnresolvedSet::reserve().
readVersionTuple()
VersionTuple clang::ASTRecordReader::readVersionTuple () inline
Read a version tuple, advancing Idx.
Definition at line 319 of file ASTRecordReader.h.
References clang::ASTReader::ReadVersionTuple().
readVisibleDeclContextStorage()
bool clang::ASTRecordReader::readVisibleDeclContextStorage (uint64_t Offset, serialization::DeclID ID) inline
Read the record that describes the visible contents of a DC.
Definition at line 104 of file ASTRecordReader.h.
References clang::serialization::ModuleFile::DeclsCursor, and Offset.
recordSwitchCaseID()
void clang::ASTRecordReader::recordSwitchCaseID (SwitchCase * SC, unsigned ID) inline
Definition at line 334 of file ASTRecordReader.h.
References clang::ASTReader::RecordSwitchCaseID().
size()
size_t clang::ASTRecordReader::size () const inline
The length of this record.
Definition at line 62 of file ASTRecordReader.h.
skipInts()
void clang::ASTRecordReader::skipInts (unsigned N) inline
Skips the specified number of values.
Definition at line 84 of file ASTRecordReader.h.
References N.
Referenced by readOMPChildren(), clang::ASTDeclReader::VisitCXXMethodDecl(), and clang::ASTDeclReader::VisitImportDecl().
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTRecordReader.h
lib/Serialization/ASTReader.cpp
lib/Serialization/ASTReaderDecl.cpp