clang: clang::MatrixTypeLoc Class Reference
clang::MatrixTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getAttrNameLoc () const
The location of the attribute name, i.e.
void setAttrNameLoc (SourceLocation loc)
Expr * getAttrRowOperand () const
The attribute's row operand, if it has one.
void setAttrRowOperand (Expr *e)
Expr * getAttrColumnOperand () const
The attribute's column operand, if it has one.
void setAttrColumnOperand (Expr *e)
SourceRange getAttrOperandParensRange () const
The location of the parentheses around the operand, if there is an operand.
void setAttrOperandParensRange (SourceRange range)
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (MatrixTypeLoc other)
TypeLoc getNextTypeLoc () const
const MatrixType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
MatrixTypeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Definition at line 1834 of file TypeLoc.h.
Member Function Documentation
getAttrColumnOperand()
Expr * clang::MatrixTypeLoc::getAttrColumnOperand () const inline
The attribute's column operand, if it has one.
float attribute((matrix_type(4, 2))) ^
Definition at line 1852 of file TypeLoc.h.
References clang::MatrixTypeLocInfo::ColumnOperand, and clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData().
getAttrNameLoc()
SourceLocation clang::MatrixTypeLoc::getAttrNameLoc () const inline
The location of the attribute name, i.e.
float attribute((matrix_type(4, 2))) ^~~~~~~~~~~~~~~~~
Definition at line 1840 of file TypeLoc.h.
References clang::MatrixTypeLocInfo::AttrLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData().
Referenced by getLocalSourceRange().
getAttrOperandParensRange()
SourceRange clang::MatrixTypeLoc::getAttrOperandParensRange () const inline
The location of the parentheses around the operand, if there is an operand.
float attribute((matrix_type(4, 2))) ^ ^
Definition at line 1859 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData(), and clang::MatrixTypeLocInfo::OperandParens.
Referenced by getLocalSourceRange().
getAttrRowOperand()
Expr * clang::MatrixTypeLoc::getAttrRowOperand () const inline
The attribute's row operand, if it has one.
float attribute((matrix_type(4, 2))) ^
Definition at line 1846 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData(), and clang::MatrixTypeLocInfo::RowOperand.
getLocalSourceRange()
SourceRange clang::MatrixTypeLoc::getLocalSourceRange () const inline
Definition at line 1866 of file TypeLoc.h.
References getAttrNameLoc(), and getAttrOperandParensRange().
initializeLocal()
void clang::MatrixTypeLoc::initializeLocal (ASTContext & Context, SourceLocation loc) inline
Definition at line 1872 of file TypeLoc.h.
References setAttrColumnOperand(), setAttrNameLoc(), setAttrOperandParensRange(), and setAttrRowOperand().
setAttrColumnOperand()
void clang::MatrixTypeLoc::setAttrColumnOperand (Expr * e) inline
Definition at line 1853 of file TypeLoc.h.
References clang::MatrixTypeLocInfo::ColumnOperand, and clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData().
Referenced by fillMatrixTypeLoc(), and initializeLocal().
setAttrNameLoc()
void clang::MatrixTypeLoc::setAttrNameLoc (SourceLocation loc) inline
Definition at line 1841 of file TypeLoc.h.
References clang::MatrixTypeLocInfo::AttrLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData().
Referenced by fillMatrixTypeLoc(), and initializeLocal().
setAttrOperandParensRange()
void clang::MatrixTypeLoc::setAttrOperandParensRange (SourceRange range) inline
Definition at line 1862 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData(), and clang::MatrixTypeLocInfo::OperandParens.
Referenced by fillMatrixTypeLoc(), and initializeLocal().
setAttrRowOperand()
void clang::MatrixTypeLoc::setAttrRowOperand (Expr * e) inline
Definition at line 1847 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, MatrixTypeLoc, MatrixType, MatrixTypeLocInfo >::getLocalData(), and clang::MatrixTypeLocInfo::RowOperand.
Referenced by fillMatrixTypeLoc(), and initializeLocal().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h