clang: clang::TemplateArgumentLoc Class Reference
clang::TemplateArgumentLoc Class Reference
Location wrapper for a TemplateArgument.
#include "clang/AST/TemplateBase.h"
Public Member Functions
TemplateArgumentLoc ()
TemplateArgumentLoc (const TemplateArgument &Argument, TemplateArgumentLocInfo Opaque)
TemplateArgumentLoc (const TemplateArgument &Argument, TypeSourceInfo *TInfo)
TemplateArgumentLoc (const TemplateArgument &Argument, Expr *E)
TemplateArgumentLoc (ASTContext &Ctx, const TemplateArgument &Argument, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateNameLoc, SourceLocation EllipsisLoc=SourceLocation())
SourceLocation getLocation () const
SourceRange getSourceRange () const LLVM_READONLY
const TemplateArgument & getArgument () const
TemplateArgumentLocInfo getLocInfo () const
TypeSourceInfo * getTypeSourceInfo () const
Expr * getSourceExpression () const
Expr * getSourceDeclExpression () const
Expr * getSourceNullPtrExpression () const
Expr * getSourceIntegralExpression () const
NestedNameSpecifierLoc getTemplateQualifierLoc () const
SourceLocation getTemplateNameLoc () const
SourceLocation getTemplateEllipsisLoc () const
Detailed Description
Location wrapper for a TemplateArgument.
TemplateArgument is to TemplateArgumentLoc as Type is to TypeLoc.
Definition at line 457 of file TemplateBase.h.
Constructor & Destructor Documentation
TemplateArgumentLoc() [1/5]
clang::TemplateArgumentLoc::TemplateArgumentLoc () inline
Definition at line 462 of file TemplateBase.h.
TemplateArgumentLoc() [2/5]
clang::TemplateArgumentLoc::TemplateArgumentLoc (const TemplateArgument & Argument, TemplateArgumentLocInfo Opaque) inline
Definition at line 464 of file TemplateBase.h.
TemplateArgumentLoc() [3/5]
clang::TemplateArgumentLoc::TemplateArgumentLoc (const TemplateArgument & Argument, TypeSourceInfo * TInfo) inline
Definition at line 468 of file TemplateBase.h.
References clang::TemplateArgument::getKind(), and clang::TemplateArgument::Type.
TemplateArgumentLoc() [4/5]
clang::TemplateArgumentLoc::TemplateArgumentLoc (const TemplateArgument & Argument, Expr * E) inline
Definition at line 473 of file TemplateBase.h.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getKind(), clang::TemplateArgument::Integral, and clang::TemplateArgument::NullPtr.
TemplateArgumentLoc() [5/5]
clang::TemplateArgumentLoc::TemplateArgumentLoc (ASTContext & Ctx, const TemplateArgument & Argument, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateNameLoc, SourceLocation EllipsisLoc = SourceLocation()) inline
Definition at line 484 of file TemplateBase.h.
References clang::TemplateArgument::getKind(), clang::TemplateArgument::Template, and clang::TemplateArgument::TemplateExpansion.
Member Function Documentation
getArgument()
const TemplateArgument & clang::TemplateArgumentLoc::getArgument () const inline
Definition at line 506 of file TemplateBase.h.
Referenced by clang::Sema::ActOnTemplateTemplateParameter(), clang::ASTRecordWriter::AddTemplateArgumentLoc(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateTemplateArgument(), clang::Sema::CheckTemplateTypeArgument(), ConvertDeducedTemplateArguments(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc(), FinishTemplateArgumentDeduction(), getArgument(), clang::comments::getFunctionTypeLoc(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::ASTNodeImporter::import(), isEnableIf(), printArgument(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::TemplateTemplateParmDecl::setDefaultArgument(), clang::TreeTransform< Derived >::TransformTemplateArgument(), clang::TreeTransform< Derived >::TransformTemplateArguments(), and clang::JSONNodeDumper::VisitTemplateTemplateParmDecl().
getLocation()
SourceLocation clang::TemplateArgumentLoc::getLocation () const inline
Fetches the primary location of the argument.
Definition at line 495 of file TemplateBase.h.
References clang::SourceRange::getBegin(), clang::TemplateArgument::getKind(), getSourceRange(), getTemplateNameLoc(), clang::TemplateArgument::Template, and clang::TemplateArgument::TemplateExpansion.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnTemplateTemplateParameter(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateParameterList(), clang::Sema::CheckTemplateTemplateArgument(), clang::Sema::DiagnoseUnexpandedParameterPack(), and clang::TemplateTemplateParmDecl::getDefaultArgumentLoc().
getLocInfo()
TemplateArgumentLocInfo clang::TemplateArgumentLoc::getLocInfo () const inline
Definition at line 510 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLoc(), and clang::ASTNodeImporter::import().
getSourceDeclExpression()
Expr * clang::TemplateArgumentLoc::getSourceDeclExpression () const inline
Definition at line 524 of file TemplateBase.h.
References clang::TemplateArgument::Declaration, clang::TemplateArgumentLocInfo::getAsExpr(), and clang::TemplateArgument::getKind().
Referenced by getSourceRange().
getSourceExpression()
Expr * clang::TemplateArgumentLoc::getSourceExpression () const inline
Definition at line 519 of file TemplateBase.h.
References clang::TemplateArgument::Expression, clang::TemplateArgumentLocInfo::getAsExpr(), and clang::TemplateArgument::getKind().
Referenced by getSourceRange(), isEnableIf(), clang::TreeTransform< Derived >::RebuildPackExpansion(), and clang::TreeTransform< Derived >::TransformTemplateArgument().
getSourceIntegralExpression()
Expr * clang::TemplateArgumentLoc::getSourceIntegralExpression () const inline
Definition at line 534 of file TemplateBase.h.
References clang::TemplateArgumentLocInfo::getAsExpr(), clang::TemplateArgument::getKind(), and clang::TemplateArgument::Integral.
Referenced by getSourceRange().
getSourceNullPtrExpression()
Expr * clang::TemplateArgumentLoc::getSourceNullPtrExpression () const inline
Definition at line 529 of file TemplateBase.h.
References clang::TemplateArgumentLocInfo::getAsExpr(), clang::TemplateArgument::getKind(), and clang::TemplateArgument::NullPtr.
Referenced by getSourceRange().
getSourceRange()
SourceRange TemplateArgumentLoc::getSourceRange () const
Fetches the full source range of the argument.
Definition at line 422 of file TemplateBase.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getKind(), getSourceDeclExpression(), getSourceExpression(), getSourceIntegralExpression(), getSourceNullPtrExpression(), clang::Stmt::getSourceRange(), getTemplateEllipsisLoc(), getTemplateNameLoc(), getTemplateQualifierLoc(), getTypeSourceInfo(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
Referenced by clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnTemplateTemplateParameter(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateParameterList(), clang::Sema::CheckTemplateTemplateArgument(), clang::Sema::CheckTemplateTypeArgument(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc(), getLocation(), clang::TemplateTemplateParmDecl::getSourceRange(), isEnableIf(), and clang::TreeTransform< Derived >::TransformTemplateArguments().
getTemplateEllipsisLoc()
SourceLocation clang::TemplateArgumentLoc::getTemplateEllipsisLoc () const inline
Definition at line 553 of file TemplateBase.h.
References clang::TemplateArgument::getKind(), clang::TemplateArgumentLocInfo::getTemplateEllipsisLoc(), and clang::TemplateArgument::TemplateExpansion.
Referenced by clang::Sema::CheckTemplateArgument(), getSourceRange(), and clang::Sema::getTemplateArgumentPackExpansionPattern().
getTemplateNameLoc()
SourceLocation clang::TemplateArgumentLoc::getTemplateNameLoc () const inline
Definition at line 546 of file TemplateBase.h.
References clang::TemplateArgument::getKind(), clang::TemplateArgumentLocInfo::getTemplateNameLoc(), clang::TemplateArgument::Template, and clang::TemplateArgument::TemplateExpansion.
Referenced by clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgumentList(), getLocation(), getSourceRange(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), and clang::TreeTransform< Derived >::TransformTemplateArgument().
getTemplateQualifierLoc()
NestedNameSpecifierLoc clang::TemplateArgumentLoc::getTemplateQualifierLoc () const inline
Definition at line 539 of file TemplateBase.h.
References clang::TemplateArgument::getKind(), clang::TemplateArgumentLocInfo::getTemplateQualifierLoc(), clang::TemplateArgument::Template, and clang::TemplateArgument::TemplateExpansion.
Referenced by clang::Sema::CheckTemplateArgument(), getSourceRange(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), and clang::TreeTransform< Derived >::TransformTemplateArgument().
getTypeSourceInfo()
TypeSourceInfo * clang::TemplateArgumentLoc::getTypeSourceInfo () const inline
Definition at line 514 of file TemplateBase.h.
References clang::TemplateArgumentLocInfo::getAsTypeSourceInfo(), clang::TemplateArgument::getKind(), and clang::TemplateArgument::Type.
Referenced by clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateTypeArgument(), clang::comments::getFunctionTypeLoc(), getSourceRange(), clang::Sema::getTemplateArgumentPackExpansionPattern(), printArgument(), clang::TreeTransform< Derived >::RebuildPackExpansion(), clang::TreeTransform< Derived >::TransformTemplateArgument(), and clang::RecursiveASTVisitor< Derived >::VisitObjCExplicitProtocolImplAttr().
The documentation for this class was generated from the following files:
include/clang/AST/TemplateBase.h
lib/AST/TemplateBase.cpp