clang: clang::ASTRecordWriter Class Reference
clang::ASTRecordWriter Class Reference
An object for streaming information to a record.
#include "clang/Serialization/ASTRecordWriter.h"
Public Member Functions
ASTRecordWriter (ASTWriter &W, ASTWriter::RecordDataImpl &Record)
Construct a ASTRecordWriter that uses the default encoding scheme.
ASTRecordWriter (ASTRecordWriter &Parent, ASTWriter::RecordDataImpl &Record)
Construct a ASTRecordWriter that uses the same encoding scheme as another ASTRecordWriter.
ASTRecordWriter (const ASTRecordWriter &)=delete
Copying an ASTRecordWriter is almost certainly a bug.
ASTRecordWriter & operator= (const ASTRecordWriter &)=delete
ASTWriter::RecordDataImpl & getRecordData () const
Extract the underlying record storage.
uint64_t Emit (unsigned Code, unsigned Abbrev=0)
Emit the record to the stream, followed by its substatements, and return its offset.
uint64_t EmitStmt (unsigned Code, unsigned Abbrev=0)
Emit the record to the stream, preceded by its substatements.
void AddOffset (uint64_t BitOffset)
Add a bit offset into the record.
void AddStmt (Stmt *S)
Add the given statement or expression to the queue of statements to emit.
void writeStmtRef (const Stmt *S)
void AddFunctionDefinition (const FunctionDecl *FD)
Add a definition for the given function to the queue of statements to emit.
void AddSourceLocation (SourceLocation Loc)
Emit a source location.
void writeSourceLocation (SourceLocation Loc)
void AddSourceRange (SourceRange Range)
Emit a source range.
void writeBool (bool Value)
void writeUInt32 (uint32_t Value)
void writeUInt64 (uint64_t Value)
void AddAPInt (const llvm::APInt &Value)
Emit an integral value.
void AddAPSInt (const llvm::APSInt &Value)
Emit a signed integral value.
void AddAPFloat (const llvm::APFloat &Value)
Emit a floating-point value.
void AddAPValue (const APValue &Value)
Emit an APvalue.
void AddIdentifierRef (const IdentifierInfo *II)
Emit a reference to an identifier.
void writeIdentifier (const IdentifierInfo *II)
void AddSelectorRef (Selector S)
Emit a Selector (which is a smart pointer reference).
void writeSelector (Selector sel)
void AddCXXTemporary (const CXXTemporary *Temp)
Emit a CXXTemporary.
void AddCXXBaseSpecifier (const CXXBaseSpecifier &Base)
Emit a C++ base specifier.
void AddCXXBaseSpecifiers (ArrayRef< CXXBaseSpecifier > Bases)
Emit a set of C++ base specifiers.
void AddTypeRef (QualType T)
Emit a reference to a type.
void writeQualType (QualType T)
void AddTypeSourceInfo (TypeSourceInfo *TInfo)
Emits a reference to a declarator info.
void AddTypeLoc (TypeLoc TL)
Emits source location information for a type. Does not emit the type.
void AddTemplateArgumentLocInfo (TemplateArgument::ArgKind Kind, const TemplateArgumentLocInfo &Arg)
Emits a template argument location info.
void AddTemplateArgumentLoc (const TemplateArgumentLoc &Arg)
Emits a template argument location.
void AddASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo *ASTTemplArgList)
Emits an AST template argument list info.
void AddDeclRef (const Decl *D)
Emit a reference to a declaration.
void writeDeclRef (const Decl *D)
void AddDeclarationName (DeclarationName Name)
Emit a declaration name.
void AddDeclarationNameLoc (const DeclarationNameLoc &DNLoc, DeclarationName Name)
void AddDeclarationNameInfo (const DeclarationNameInfo &NameInfo)
void AddQualifierInfo (const QualifierInfo &Info)
void AddNestedNameSpecifier (NestedNameSpecifier *NNS)
Emit a nested name specifier.
void AddNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Emit a nested name specifier with source-location information.
void AddTemplateName (TemplateName Name)
Emit a template name.
void AddTemplateArgument (const TemplateArgument &Arg)
Emit a template argument.
void AddTemplateParameterList (const TemplateParameterList *TemplateParams)
Emit a template parameter list.
void AddTemplateArgumentList (const TemplateArgumentList *TemplateArgs)
Emit a template argument list.
void AddUnresolvedSet (const ASTUnresolvedSet &Set)
Emit a UnresolvedSet structure.
void AddCXXCtorInitializers (ArrayRef< CXXCtorInitializer * > CtorInits)
Emit a CXXCtorInitializer array.
void AddCXXDefinitionData (const CXXRecordDecl *D)
void AddVarDeclInit (const VarDecl *VD)
Emit information about the initializer of a VarDecl.
void writeOMPTraitInfo (const OMPTraitInfo *TI)
Write an OMPTraitInfo object.
void writeOMPClause (OMPClause *C)
void writeOMPChildren (OMPChildren *Data)
Writes data related to the OpenMP directives.
void AddString (StringRef Str)
Emit a string.
void AddPath (StringRef Path)
Emit a path.
void AddVersionTuple (const VersionTuple &Version)
Emit a version tuple.
void AddAttr (const Attr *A)
void AddAttributes (ArrayRef< const Attr * > Attrs)
Emit a list of attributes.
void push_back (uint64_t N)
Minimal vector-like interface.
template<typename InputIterator >
void append (InputIterator begin, InputIterator end)
bool empty () const
size_t size () const
uint64_t & operator[] (size_t N)
Public Member Functions inherited from clang::serialization::DataStreamBasicWriter< ASTRecordWriter >
ASTRecordWriter & find (const char *propertyName)
Implement property-find by ignoring it.
ASTRecordWriter & writeObject ()
void writeEnum (T value)
void writeArray (llvm::ArrayRef< T > array)
void writeOptional (llvm::Optional< T > value)
void writeAPSInt (const llvm::APSInt &value)
void writeAPInt (const llvm::APInt &value)
void writeFixedPointSemantics (const llvm::FixedPointSemantics &sema)
void writeLValuePathSerializationHelper (APValue::LValuePathSerializationHelper lvaluePath)
void writeQualifiers (Qualifiers value)
void writeExceptionSpecInfo (const FunctionProtoType::ExceptionSpecInfo &esi)
void writeExtParameterInfo (FunctionProtoType::ExtParameterInfo epi)
void writeNestedNameSpecifier (NestedNameSpecifier *NNS)
Public Member Functions inherited from clang::serialization::BasicWriterBase< ASTRecordWriter >
ASTContext & getASTContext ()
ASTRecordWriter & asImpl ()
void writeAPValue (const APValue &node)
void writeAPValueKind (APValue::ValueKind value)
void writeArraySizeModifier (ArrayType::ArraySizeModifier value)
void writeAttrKind (attr::Kind value)
void writeAutoTypeKeyword (AutoTypeKeyword value)
void writeBuiltinTypeKind (BuiltinType::Kind value)
void writeCXXRecordDeclRef (const CXXRecordDecl *value)
void writeCallingConv (CallingConv value)
void writeConceptDeclRef (const ConceptDecl *value)
void writeDeclarationName (DeclarationName node)
void writeDeclarationNameKind (DeclarationName::NameKind value)
void writeElaboratedTypeKeyword (ElaboratedTypeKeyword value)
void writeExprRef (const Expr *value)
void writeFunctionDeclRef (const FunctionDecl *value)
void writeNamedDeclRef (const NamedDecl *value)
void writeNamespaceAliasDeclRef (const NamespaceAliasDecl *value)
void writeNamespaceDeclRef (const NamespaceDecl *value)
void writeNestedNameSpecifierKind (NestedNameSpecifier::SpecifierKind value)
void writeObjCProtocolDeclRef (const ObjCProtocolDecl *value)
void writeObjCTypeParamDeclRef (const ObjCTypeParamDecl *value)
void writeOverloadedOperatorKind (OverloadedOperatorKind value)
void writeRefQualifierKind (RefQualifierKind value)
void writeTagDeclRef (const TagDecl *value)
void writeTemplateArgument (TemplateArgument node)
void writeTemplateArgumentKind (TemplateArgument::ArgKind value)
void writeTemplateDeclRef (const TemplateDecl *value)
void writeTemplateName (TemplateName node)
void writeTemplateNameKind (TemplateName::NameKind value)
void writeTemplateTemplateParmDeclRef (const TemplateTemplateParmDecl *value)
void writeTemplateTypeParmDeclRef (const TemplateTypeParmDecl *value)
void writeUnaryTypeTransformKind (UnaryTransformType::UTTKind value)
void writeValueDeclRef (const ValueDecl *value)
void writeVectorKind (VectorType::VectorKind value)
Additional Inherited Members
Protected Member Functions inherited from clang::serialization::DataStreamBasicWriter< ASTRecordWriter >
DataStreamBasicWriter (ASTContext &ctx)
Protected Member Functions inherited from clang::serialization::BasicWriterBase< ASTRecordWriter >
BasicWriterBase (ASTContext &ctx)
Detailed Description
An object for streaming information to a record.
Definition at line 26 of file ASTRecordWriter.h.
Constructor & Destructor Documentation
ASTRecordWriter() [1/3]
clang::ASTRecordWriter::ASTRecordWriter (ASTWriter & W, ASTWriter::RecordDataImpl & Record) inline
Construct a ASTRecordWriter that uses the default encoding scheme.
Definition at line 58 of file ASTRecordWriter.h.
ASTRecordWriter() [2/3]
clang::ASTRecordWriter::ASTRecordWriter (ASTRecordWriter & Parent, ASTWriter::RecordDataImpl & Record) inline
Construct a ASTRecordWriter that uses the same encoding scheme as another ASTRecordWriter.
Definition at line 63 of file ASTRecordWriter.h.
ASTRecordWriter() [3/3]
clang::ASTRecordWriter::ASTRecordWriter (const ASTRecordWriter &) delete
Copying an ASTRecordWriter is almost certainly a bug.
Member Function Documentation
AddAPFloat()
void ASTRecordWriter::AddAPFloat (const llvm::APFloat & Value)
Emit a floating-point value.
Definition at line 5127 of file ASTWriter.cpp.
References AddAPInt().
AddAPInt()
void clang::ASTRecordWriter::AddAPInt (const llvm::APInt & Value) inline
Emit an integral value.
Definition at line 156 of file ASTRecordWriter.h.
References clang::serialization::DataStreamBasicWriter< ASTRecordWriter >::writeAPInt().
Referenced by AddAPFloat().
AddAPSInt()
void clang::ASTRecordWriter::AddAPSInt (const llvm::APSInt & Value) inline
Emit a signed integral value.
Definition at line 161 of file ASTRecordWriter.h.
References clang::serialization::DataStreamBasicWriter< ASTRecordWriter >::writeAPSInt().
Referenced by clang::ASTDeclWriter::VisitEnumConstantDecl().
AddAPValue()
void clang::ASTRecordWriter::AddAPValue (const APValue & Value) inline
Emit an APvalue.
Definition at line 169 of file ASTRecordWriter.h.
References clang::serialization::BasicWriterBase< ASTRecordWriter >::writeAPValue().
Referenced by clang::ASTDeclWriter::VisitLifetimeExtendedTemporaryDecl(), and clang::ASTDeclWriter::VisitTemplateParamObjectDecl().
AddASTTemplateArgumentListInfo()
void ASTRecordWriter::AddASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo * ASTTemplArgList)
Emits an AST template argument list info.
Definition at line 5536 of file ASTWriter.cpp.
References AddSourceLocation(), AddTemplateArgumentLoc(), clang::ASTTemplateArgumentListInfo::getTemplateArgs(), clang::ASTTemplateArgumentListInfo::LAngleLoc, clang::ASTTemplateArgumentListInfo::NumTemplateArgs, and clang::ASTTemplateArgumentListInfo::RAngleLoc.
Referenced by clang::ASTDeclWriter::VisitClassScopeFunctionSpecializationDecl(), clang::ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), and clang::ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl().
AddAttr()
void ASTRecordWriter::AddAttr (const Attr * A)
Definition at line 4234 of file ASTWriter.cpp.
References clang::AttributeCommonInfo::getAttrName(), clang::Attr::getKind(), clang::AttributeCommonInfo::getParsedKind(), clang::AttributeCommonInfo::getRange(), clang::AttributeCommonInfo::getScopeLoc(), clang::AttributeCommonInfo::getScopeName(), and clang::AttributeCommonInfo::getSyntax().
AddAttributes()
void ASTRecordWriter::AddAttributes (ArrayRef< const Attr * > Attrs)
Emit a list of attributes.
Emit the list of attributes to the specified record.
Definition at line 4252 of file ASTWriter.cpp.
Referenced by clang::ASTDeclWriter::VisitDecl().
AddCXXBaseSpecifier()
void ASTRecordWriter::AddCXXBaseSpecifier (const CXXBaseSpecifier & Base)
Emit a C++ base specifier.
Definition at line 5557 of file ASTWriter.cpp.
References AddSourceLocation(), AddSourceRange(), and AddTypeSourceInfo().
Referenced by EmitCXXBaseSpecifiers().
AddCXXBaseSpecifiers()
void ASTRecordWriter::AddCXXBaseSpecifiers (ArrayRef< CXXBaseSpecifier > Bases)
Emit a set of C++ base specifiers.
Definition at line 5581 of file ASTWriter.cpp.
References AddOffset(), and EmitCXXBaseSpecifiers().
Referenced by AddCXXDefinitionData().
AddCXXCtorInitializers()
void ASTRecordWriter::AddCXXCtorInitializers (ArrayRef< CXXCtorInitializer * > CtorInits)
Emit a CXXCtorInitializer array.
Definition at line 5621 of file ASTWriter.cpp.
References AddOffset(), and EmitCXXCtorInitializers().
Referenced by AddFunctionDefinition(), and clang::ASTDeclWriter::VisitObjCImplementationDecl().
AddCXXDefinitionData()
void ASTRecordWriter::AddCXXDefinitionData (const CXXRecordDecl * D)
Definition at line 5626 of file ASTWriter.cpp.
References AddCXXBaseSpecifiers(), AddDeclRef(), AddSourceLocation(), AddTypeSourceInfo(), AddUnresolvedSet(), clang::CXXRecordDecl::getDeviceLambdaManglingNumber(), clang::sema::Capture::getEllipsisLoc(), clang::CXXRecordDecl::getLambdaContextDecl(), clang::sema::Capture::getLocation(), clang::CXXRecordDecl::getODRHash(), clang::TagDecl::isDependentType(), clang::LCK_ByCopy, clang::LCK_ByRef, clang::LCK_StarThis, clang::LCK_This, clang::LCK_VLAType, and N.
Referenced by clang::ASTDeclWriter::VisitCXXRecordDecl().
AddCXXTemporary()
void ASTRecordWriter::AddCXXTemporary (const CXXTemporary * Temp)
Emit a CXXTemporary.
Definition at line 5196 of file ASTWriter.cpp.
References AddDeclRef(), and clang::CXXTemporary::getDestructor().
AddDeclarationName()
void clang::ASTRecordWriter::AddDeclarationName (DeclarationName Name) inline
Emit a declaration name.
Definition at line 228 of file ASTRecordWriter.h.
References clang::serialization::BasicWriterBase< ASTRecordWriter >::writeDeclarationName().
Referenced by AddDeclarationNameInfo(), clang::ASTDeclWriter::VisitNamedDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), and clang::ASTDeclWriter::VisitOMPDeclareMapperDecl().
AddDeclarationNameInfo()
void ASTRecordWriter::AddDeclarationNameInfo (const DeclarationNameInfo & NameInfo)
Definition at line 5441 of file ASTWriter.cpp.
References AddDeclarationName(), AddDeclarationNameLoc(), AddSourceLocation(), clang::DeclarationNameInfo::getInfo(), clang::DeclarationNameInfo::getLoc(), and clang::DeclarationNameInfo::getName().
Referenced by clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
AddDeclarationNameLoc()
void ASTRecordWriter::AddDeclarationNameLoc (const DeclarationNameLoc & DNLoc, DeclarationName Name)
Definition at line 5410 of file ASTWriter.cpp.
References AddSourceLocation(), AddTypeSourceInfo(), clang::DeclarationNameLoc::CXXOpName::BeginOpNameLoc, clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationNameLoc::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationNameLoc::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationNameLoc::CXXOpName::EndOpNameLoc, clang::SourceLocation::getFromRawEncoding(), clang::DeclarationName::Identifier, clang::DeclarationNameLoc::NamedType, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::DeclarationNameLoc::CXXLitOpName::OpNameLoc, and clang::DeclarationNameLoc::NT::TInfo.
Referenced by AddDeclarationNameInfo(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingValueDecl(), and clang::ASTDeclWriter::VisitUsingDecl().
AddDeclRef()
void clang::ASTRecordWriter::AddDeclRef (const Decl * D) inline
Emit a reference to a declaration.
Definition at line 220 of file ASTRecordWriter.h.
References clang::ASTWriter::AddDeclRef().
Referenced by AddCXXDefinitionData(), AddCXXTemporary(), AddNestedNameSpecifierLoc(), AddTemplateParameterList(), AddUnresolvedSet(), EmitCXXCtorInitializers(), clang::ASTDeclWriter::VisitBlockDecl(), clang::ASTDeclWriter::VisitCapturedDecl(), clang::ASTDeclWriter::VisitClassScopeFunctionSpecializationDecl(), clang::ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclWriter::VisitConstructorUsingShadowDecl(), clang::ASTDeclWriter::VisitCXXConstructorDecl(), clang::ASTDeclWriter::VisitCXXDestructorDecl(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitCXXRecordDecl(), clang::ASTDeclWriter::VisitDecl(), clang::ASTDeclWriter::VisitDecompositionDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTDeclWriter::VisitFriendDecl(), clang::ASTDeclWriter::VisitFriendTemplateDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitIndirectFieldDecl(), clang::ASTDeclWriter::VisitLifetimeExtendedTemporaryDecl(), clang::ASTDeclWriter::VisitNamespaceAliasDecl(), clang::ASTDeclWriter::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitObjCCategoryDecl(), clang::ASTDeclWriter::VisitObjCCompatibleAliasDecl(), clang::ASTDeclWriter::VisitObjCImplDecl(), clang::ASTDeclWriter::VisitObjCImplementationDecl(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), clang::ASTDeclWriter::VisitObjCPropertyImplDecl(), clang::ASTDeclWriter::VisitObjCProtocolDecl(), clang::ASTDeclWriter::VisitOMPDeclareMapperDecl(), clang::ASTDeclWriter::VisitOMPDeclareReductionDecl(), clang::ASTDeclWriter::VisitRedeclarable(), clang::ASTDeclWriter::VisitRedeclarableTemplateDecl(), clang::ASTDeclWriter::VisitTagDecl(), clang::ASTDeclWriter::VisitTemplateDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), clang::ASTDeclWriter::VisitTypeAliasDecl(), clang::ASTDeclWriter::VisitTypedefNameDecl(), clang::ASTDeclWriter::VisitUsingDecl(), clang::ASTDeclWriter::VisitUsingDirectiveDecl(), clang::ASTDeclWriter::VisitUsingPackDecl(), clang::ASTDeclWriter::VisitUsingShadowDecl(), clang::ASTDeclWriter::VisitVarDecl(), clang::ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl(), clang::ASTDeclWriter::VisitVarTemplateSpecializationDecl(), and writeDeclRef().
AddFunctionDefinition()
void ASTRecordWriter::AddFunctionDefinition (const FunctionDecl * FD)
Add a definition for the given function to the queue of statements to emit.
Definition at line 2439 of file ASTWriterDecl.cpp.
References AddCXXCtorInitializers(), AddStmt(), clang::ASTWriter::ClearSwitchCaseIDs(), clang::FunctionDecl::doesThisDeclarationHaveABody(), clang::FunctionDecl::getBody(), clang::ASTWriter::GetDeclRef(), clang::ASTContext::GetGVALinkageForFunction(), clang::ASTContext::getLangOpts(), clang::GVA_AvailableExternally, clang::GVA_Internal, clang::GVA_StrongExternal, clang::Decl::hasAttr(), clang::DeclContext::isDependentContext(), clang::Module::Kind, and clang::Module::ModuleInterfaceUnit.
Referenced by clang::ASTDeclWriter::Visit().
AddIdentifierRef()
void clang::ASTRecordWriter::AddIdentifierRef (const IdentifierInfo * II) inline
Emit a reference to an identifier.
Definition at line 172 of file ASTRecordWriter.h.
References clang::ASTWriter::AddIdentifierRef().
Referenced by AddNestedNameSpecifierLoc(), clang::ASTDeclWriter::VisitMSPropertyDecl(), clang::ASTDeclWriter::VisitTagDecl(), and writeIdentifier().
AddNestedNameSpecifier()
void clang::ASTRecordWriter::AddNestedNameSpecifier (NestedNameSpecifier * NNS) inline
Emit a nested name specifier.
Definition at line 239 of file ASTRecordWriter.h.
References clang::serialization::DataStreamBasicWriter< ASTRecordWriter >::writeNestedNameSpecifier().
AddNestedNameSpecifierLoc()
void ASTRecordWriter::AddNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Emit a nested name specifier with source-location information.
Definition at line 5455 of file ASTWriter.cpp.
References AddDeclRef(), AddIdentifierRef(), AddSourceLocation(), AddSourceRange(), AddTypeLoc(), AddTypeRef(), clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsRecordDecl(), clang::SourceRange::getEnd(), clang::NestedNameSpecifier::getKind(), clang::NestedNameSpecifierLoc::getLocalSourceRange(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getPrefix(), clang::TypeLoc::getType(), clang::NestedNameSpecifierLoc::getTypeLoc(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by AddQualifierInfo(), AddTemplateArgumentLocInfo(), clang::ASTDeclWriter::VisitNamespaceAliasDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingTypenameDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingValueDecl(), clang::ASTDeclWriter::VisitUsingDecl(), and clang::ASTDeclWriter::VisitUsingDirectiveDecl().
AddOffset()
void clang::ASTRecordWriter::AddOffset (uint64_t BitOffset) inline
Add a bit offset into the record.
This will be converted into an offset relative to the current record when emitted.
Definition at line 107 of file ASTRecordWriter.h.
Referenced by AddCXXBaseSpecifiers(), AddCXXCtorInitializers(), clang::ASTDeclWriter::VisitDeclContext(), and clang::ASTDeclWriter::VisitRedeclarable().
AddPath()
void clang::ASTRecordWriter::AddPath (StringRef Path) inline
Emit a path.
Definition at line 287 of file ASTRecordWriter.h.
References clang::ASTWriter::AddPath().
AddQualifierInfo()
void ASTRecordWriter::AddQualifierInfo (const QualifierInfo & Info)
Definition at line 5448 of file ASTWriter.cpp.
References AddNestedNameSpecifierLoc(), AddTemplateParameterList(), clang::QualifierInfo::NumTemplParamLists, clang::QualifierInfo::QualifierLoc, and clang::QualifierInfo::TemplParamLists.
Referenced by clang::ASTDeclWriter::VisitDeclaratorDecl(), and clang::ASTDeclWriter::VisitTagDecl().
AddSelectorRef()
void ASTRecordWriter::AddSelectorRef (Selector S)
Emit a Selector (which is a smart pointer reference).
Definition at line 5173 of file ASTWriter.cpp.
Referenced by writeSelector().
AddSourceLocation()
void clang::ASTRecordWriter::AddSourceLocation (SourceLocation Loc) inline
Emit a source location.
Definition at line 131 of file ASTRecordWriter.h.
References clang::ASTWriter::AddSourceLocation().
Referenced by AddASTTemplateArgumentListInfo(), AddCXXBaseSpecifier(), AddCXXDefinitionData(), AddDeclarationNameInfo(), AddDeclarationNameLoc(), AddNestedNameSpecifierLoc(), AddTemplateArgumentLocInfo(), clang::ASTStmtWriter::AddTemplateKWAndArgsInfo(), AddTemplateParameterList(), EmitCXXCtorInitializers(), clang::ASTDeclWriter::VisitAccessSpecDecl(), clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclWriter::VisitCXXRecordDecl(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitExportDecl(), clang::ASTDeclWriter::VisitFileScopeAsmDecl(), clang::ASTDeclWriter::VisitFriendDecl(), clang::ASTDeclWriter::VisitFriendTemplateDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitImportDecl(), clang::ASTDeclWriter::VisitLabelDecl(), clang::ASTDeclWriter::VisitLinkageSpecDecl(), clang::ASTDeclWriter::VisitNamespaceAliasDecl(), clang::ASTDeclWriter::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitObjCCategoryDecl(), clang::ASTDeclWriter::VisitObjCCategoryImplDecl(), clang::ASTDeclWriter::VisitObjCContainerDecl(), clang::ASTDeclWriter::VisitObjCImplementationDecl(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), clang::ASTDeclWriter::VisitObjCPropertyImplDecl(), clang::ASTDeclWriter::VisitObjCProtocolDecl(), clang::ASTDeclWriter::VisitObjCTypeParamDecl(), clang::ASTDeclWriter::VisitOMPDeclareReductionDecl(), clang::ASTDeclWriter::VisitPragmaCommentDecl(), clang::ASTDeclWriter::VisitPragmaDetectMismatchDecl(), clang::ASTDeclWriter::VisitStaticAssertDecl(), clang::ASTDeclWriter::VisitTypeDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingTypenameDecl(), clang::ASTDeclWriter::VisitUnresolvedUsingValueDecl(), clang::ASTDeclWriter::VisitUsingDecl(), clang::ASTDeclWriter::VisitUsingDirectiveDecl(), clang::ASTDeclWriter::VisitVarDecl(), clang::ASTDeclWriter::VisitVarTemplateSpecializationDecl(), and writeSourceLocation().
AddSourceRange()
void clang::ASTRecordWriter::AddSourceRange (SourceRange Range) inline
Emit a source range.
Definition at line 139 of file ASTRecordWriter.h.
References clang::ASTWriter::AddSourceRange().
Referenced by AddCXXBaseSpecifier(), AddNestedNameSpecifierLoc(), clang::ASTDeclWriter::VisitObjCContainerDecl(), and clang::ASTDeclWriter::VisitTagDecl().
AddStmt()
void clang::ASTRecordWriter::AddStmt (Stmt * S) inline
Add the given statement or expression to the queue of statements to emit.
This routine should be used when emitting types and declarations that have expressions as part of their formulation. Once the type or declaration has been written, Emit() will write the corresponding statements just after the record.
Definition at line 119 of file ASTRecordWriter.h.
Referenced by AddFunctionDefinition(), AddTemplateArgumentLocInfo(), AddTemplateParameterList(), EmitCXXCtorInitializers(), clang::ASTDeclWriter::VisitBindingDecl(), clang::ASTDeclWriter::VisitBlockDecl(), clang::ASTDeclWriter::VisitConceptDecl(), clang::ASTDeclWriter::VisitCXXDestructorDecl(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTDeclWriter::VisitEnumConstantDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTDeclWriter::VisitFileScopeAsmDecl(), clang::ASTDeclWriter::VisitLifetimeExtendedTemporaryDecl(), clang::ASTDeclWriter::VisitNonTypeTemplateParmDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyImplDecl(), clang::ASTDeclWriter::VisitOMPDeclareReductionDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitStaticAssertDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), clang::ASTDeclWriter::VisitVarDecl(), writeOMPChildren(), and writeStmtRef().
AddString()
void clang::ASTRecordWriter::AddString (StringRef Str) inline
Emit a string.
Definition at line 282 of file ASTRecordWriter.h.
References clang::ASTWriter::AddString().
Referenced by clang::ASTDeclWriter::VisitPragmaCommentDecl(), and clang::ASTDeclWriter::VisitPragmaDetectMismatchDecl().
AddTemplateArgument()
void clang::ASTRecordWriter::AddTemplateArgument (const TemplateArgument & Arg) inline
Emit a template argument.
Definition at line 252 of file ASTRecordWriter.h.
References clang::serialization::BasicWriterBase< ASTRecordWriter >::writeTemplateArgument().
Referenced by AddTemplateArgumentList(), and AddTemplateArgumentLoc().
AddTemplateArgumentList()
void ASTRecordWriter::AddTemplateArgumentList (const TemplateArgumentList * TemplateArgs)
Emit a template argument list.
Definition at line 5528 of file ASTWriter.cpp.
References AddTemplateArgument(), clang::TemplateArgumentList::get(), and clang::TemplateArgumentList::size().
Referenced by clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitVarTemplateSpecializationDecl().
AddTemplateArgumentLoc()
void ASTRecordWriter::AddTemplateArgumentLoc (const TemplateArgumentLoc & Arg)
Emits a template argument location.
Definition at line 5228 of file ASTWriter.cpp.
References AddTemplateArgument(), AddTemplateArgumentLocInfo(), clang::TemplateArgument::Expression, clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgumentLocInfo::getAsExpr(), clang::TemplateArgument::getKind(), and clang::TemplateArgumentLoc::getLocInfo().
Referenced by AddASTTemplateArgumentListInfo(), clang::ASTStmtWriter::AddTemplateKWAndArgsInfo(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitTemplateTemplateParmDecl().
AddTemplateArgumentLocInfo()
void ASTRecordWriter::AddTemplateArgumentLocInfo (TemplateArgument::ArgKind Kind, const TemplateArgumentLocInfo & Arg)
Emits a template argument location info.
Definition at line 5200 of file ASTWriter.cpp.
References AddNestedNameSpecifierLoc(), AddSourceLocation(), AddStmt(), AddTypeSourceInfo(), clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgumentLocInfo::getAsExpr(), clang::TemplateArgumentLocInfo::getAsTypeSourceInfo(), clang::TemplateArgumentLocInfo::getTemplateEllipsisLoc(), clang::TemplateArgumentLocInfo::getTemplateNameLoc(), clang::TemplateArgumentLocInfo::getTemplateQualifierLoc(), clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
Referenced by AddTemplateArgumentLoc().
AddTemplateName()
void clang::ASTRecordWriter::AddTemplateName (TemplateName Name) inline
Emit a template name.
Definition at line 247 of file ASTRecordWriter.h.
References clang::serialization::BasicWriterBase< ASTRecordWriter >::writeTemplateName().
AddTemplateParameterList()
void ASTRecordWriter::AddTemplateParameterList (const TemplateParameterList * TemplateParams)
Emit a template parameter list.
Definition at line 5509 of file ASTWriter.cpp.
References AddDeclRef(), AddSourceLocation(), AddStmt(), clang::TemplateParameterList::getLAngleLoc(), clang::TemplateParameterList::getRAngleLoc(), clang::TemplateParameterList::getRequiresClause(), clang::TemplateParameterList::getTemplateLoc(), P, and clang::TemplateParameterList::size().
Referenced by AddQualifierInfo(), clang::ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclWriter::VisitFriendDecl(), clang::ASTDeclWriter::VisitFriendTemplateDecl(), clang::ASTDeclWriter::VisitTemplateDecl(), clang::ASTDeclWriter::VisitTemplateTemplateParmDecl(), and clang::ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl().
AddTypeLoc()
void ASTRecordWriter::AddTypeLoc (TypeLoc TL)
Emits source location information for a type. Does not emit the type.
Definition at line 5251 of file ASTWriter.cpp.
References clang::TypeLoc::getNextTypeLoc(), and clang::TypeLoc::isNull().
Referenced by AddNestedNameSpecifierLoc(), AddTypeSourceInfo(), and clang::ASTDeclWriter::Visit().
AddTypeRef()
void clang::ASTRecordWriter::AddTypeRef (QualType T) inline
Emit a reference to a type.
Definition at line 195 of file ASTRecordWriter.h.
References clang::ASTWriter::AddTypeRef().
Referenced by AddNestedNameSpecifierLoc(), AddTypeSourceInfo(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTDeclWriter::VisitNonTypeTemplateParmDecl(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), clang::ASTDeclWriter::VisitTypeDecl(), clang::ASTDeclWriter::VisitTypedefNameDecl(), clang::ASTDeclWriter::VisitValueDecl(), and writeQualType().
AddTypeSourceInfo()
void ASTRecordWriter::AddTypeSourceInfo (TypeSourceInfo * TInfo)
Emits a reference to a declarator info.
Definition at line 5241 of file ASTWriter.cpp.
References AddTypeLoc(), AddTypeRef(), clang::TypeSourceInfo::getType(), and clang::TypeSourceInfo::getTypeLoc().
Referenced by AddCXXBaseSpecifier(), AddCXXDefinitionData(), AddDeclarationNameLoc(), AddTemplateArgumentLocInfo(), EmitCXXCtorInitializers(), clang::ASTDeclWriter::VisitBlockDecl(), clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFriendDecl(), clang::ASTDeclWriter::VisitFriendTemplateDecl(), clang::ASTDeclWriter::VisitNonTypeTemplateParmDecl(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), clang::ASTDeclWriter::VisitTypedefNameDecl(), and clang::ASTDeclWriter::VisitVarTemplateSpecializationDecl().
AddUnresolvedSet()
void ASTRecordWriter::AddUnresolvedSet (const ASTUnresolvedSet & Set)
Emit a UnresolvedSet structure.
Definition at line 5547 of file ASTWriter.cpp.
References AddDeclRef(), clang::ASTUnresolvedSet::begin(), clang::ASTUnresolvedSet::end(), and clang::ASTUnresolvedSet::size().
Referenced by AddCXXDefinitionData().
AddVarDeclInit()
void ASTRecordWriter::AddVarDeclInit (const VarDecl * VD)
Emit information about the initializer of a VarDecl.
Definition at line 5696 of file ASTWriter.cpp.
References clang::VarDecl::getEvaluatedStmt(), clang::VarDecl::getInit(), push_back(), and writeStmtRef().
Referenced by clang::ASTDeclWriter::VisitVarDecl().
AddVersionTuple()
void clang::ASTRecordWriter::AddVersionTuple (const VersionTuple & Version) inline
Emit a version tuple.
Definition at line 292 of file ASTRecordWriter.h.
References clang::ASTWriter::AddVersionTuple().
append()
template<typename InputIterator > void clang::ASTRecordWriter::append (InputIterator begin, InputIterator end) inline
Definition at line 78 of file ASTRecordWriter.h.
Emit()
uint64_t clang::ASTRecordWriter::Emit (unsigned Code, unsigned Abbrev = 0) inline
Emit the record to the stream, followed by its substatements, and return its offset.
Definition at line 89 of file ASTRecordWriter.h.
References Offset.
Referenced by EmitCXXBaseSpecifiers(), EmitCXXCtorInitializers(), and clang::ASTDeclWriter::VisitRedeclarable().
EmitStmt()
uint64_t clang::ASTRecordWriter::EmitStmt (unsigned Code, unsigned Abbrev = 0) inline
Emit the record to the stream, preceded by its substatements.
Definition at line 98 of file ASTRecordWriter.h.
empty()
bool clang::ASTRecordWriter::empty () const inline
Definition at line 81 of file ASTRecordWriter.h.
getRecordData()
ASTWriter::RecordDataImpl & clang::ASTRecordWriter::getRecordData () const inline
Extract the underlying record storage.
Definition at line 72 of file ASTRecordWriter.h.
operator=()
ASTRecordWriter & clang::ASTRecordWriter::operator= (const ASTRecordWriter &) delete
operator[]()
uint64_t & clang::ASTRecordWriter::operator[] (size_t N) inline
Definition at line 83 of file ASTRecordWriter.h.
References N.
push_back()
void clang::ASTRecordWriter::push_back (uint64_t N) inline
Minimal vector-like interface.
Definition at line 76 of file ASTRecordWriter.h.
References N.
Referenced by AddVarDeclInit(), EmitCXXBaseSpecifiers(), EmitCXXCtorInitializers(), clang::ASTDeclWriter::Visit(), clang::ASTDeclWriter::VisitBlockDecl(), clang::ASTDeclWriter::VisitCapturedDecl(), clang::ASTDeclWriter::VisitClassScopeFunctionSpecializationDecl(), clang::ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl(), clang::ASTDeclWriter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclWriter::VisitConstructorUsingShadowDecl(), clang::ASTDeclWriter::VisitCXXConstructorDecl(), clang::ASTDeclWriter::VisitCXXDeductionGuideDecl(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitCXXRecordDecl(), clang::ASTDeclWriter::VisitDecl(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTDeclWriter::VisitDecompositionDecl(), clang::ASTDeclWriter::VisitEnumConstantDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTDeclWriter::VisitFriendDecl(), clang::ASTDeclWriter::VisitFriendTemplateDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitImportDecl(), clang::ASTDeclWriter::VisitIndirectFieldDecl(), clang::ASTDeclWriter::VisitLifetimeExtendedTemporaryDecl(), clang::ASTDeclWriter::VisitLinkageSpecDecl(), clang::ASTDeclWriter::VisitMSGuidDecl(), clang::ASTDeclWriter::VisitNamedDecl(), clang::ASTDeclWriter::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitNonTypeTemplateParmDecl(), clang::ASTDeclWriter::VisitObjCCategoryDecl(), clang::ASTDeclWriter::VisitObjCImplementationDecl(), clang::ASTDeclWriter::VisitObjCInterfaceDecl(), clang::ASTDeclWriter::VisitObjCIvarDecl(), clang::ASTDeclWriter::VisitObjCMethodDecl(), clang::ASTDeclWriter::VisitObjCPropertyDecl(), clang::ASTDeclWriter::VisitObjCProtocolDecl(), clang::ASTDeclWriter::VisitObjCTypeParamDecl(), clang::ASTDeclWriter::VisitOMPDeclareReductionDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitPragmaCommentDecl(), clang::ASTDeclWriter::VisitPragmaDetectMismatchDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::ASTDeclWriter::VisitRedeclarable(), clang::ASTDeclWriter::VisitRedeclarableTemplateDecl(), clang::ASTDeclWriter::VisitStaticAssertDecl(), clang::ASTDeclWriter::VisitTagDecl(), clang::ASTDeclWriter::VisitTemplateTemplateParmDecl(), clang::ASTDeclWriter::VisitTemplateTypeParmDecl(), clang::ASTDeclWriter::VisitTypedefNameDecl(), clang::ASTDeclWriter::VisitUsingDecl(), clang::ASTDeclWriter::VisitUsingPackDecl(), clang::ASTDeclWriter::VisitUsingShadowDecl(), clang::ASTDeclWriter::VisitVarDecl(), clang::ASTDeclWriter::VisitVarTemplatePartialSpecializationDecl(), and clang::ASTDeclWriter::VisitVarTemplateSpecializationDecl().
size()
size_t clang::ASTRecordWriter::size () const inline
Definition at line 82 of file ASTRecordWriter.h.
Referenced by clang::ASTDeclWriter::VisitRedeclarable().
writeBool()
void clang::ASTRecordWriter::writeBool (bool Value) inline
Definition at line 143 of file ASTRecordWriter.h.
Referenced by writeOMPChildren(), and writeOMPTraitInfo().
writeDeclRef()
void clang::ASTRecordWriter::writeDeclRef (const Decl * D) inline
Definition at line 223 of file ASTRecordWriter.h.
References AddDeclRef().
writeIdentifier()
void clang::ASTRecordWriter::writeIdentifier (const IdentifierInfo * II) inline
Definition at line 175 of file ASTRecordWriter.h.
References AddIdentifierRef().
writeOMPChildren()
void ASTRecordWriter::writeOMPChildren (OMPChildren * Data)
Writes data related to the OpenMP directives.
Definition at line 6753 of file ASTWriter.cpp.
References AddStmt(), clang::OMPChildren::getAssociatedStmt(), clang::OMPChildren::getChildren(), clang::OMPChildren::getClauses(), clang::OMPChildren::getNumChildren(), clang::OMPChildren::getNumClauses(), clang::OMPChildren::hasAssociatedStmt(), writeBool(), writeOMPClause(), and writeUInt32().
Referenced by clang::ASTDeclWriter::VisitOMPAllocateDecl(), clang::ASTDeclWriter::VisitOMPDeclareMapperDecl(), clang::ASTDeclWriter::VisitOMPRequiresDecl(), and clang::ASTDeclWriter::VisitOMPThreadPrivateDecl().
writeOMPClause()
void ASTRecordWriter::writeOMPClause (OMPClause * C)
Definition at line 6093 of file ASTWriter.cpp.
References clang::C.
Referenced by writeOMPChildren().
writeOMPTraitInfo()
void ASTRecordWriter::writeOMPTraitInfo (const OMPTraitInfo * TI)
Write an OMPTraitInfo object.
Definition at line 6736 of file ASTWriter.cpp.
References clang::OMPTraitInfo::Sets, writeBool(), clang::serialization::DataStreamBasicWriter< ASTRecordWriter >::writeEnum(), clang::serialization::BasicWriterBase< ASTRecordWriter >::writeExprRef(), and writeUInt32().
writeQualType()
void clang::ASTRecordWriter::writeQualType (QualType T) inline
Definition at line 198 of file ASTRecordWriter.h.
References AddTypeRef().
writeSelector()
void clang::ASTRecordWriter::writeSelector (Selector sel) inline
Definition at line 181 of file ASTRecordWriter.h.
References AddSelectorRef().
writeSourceLocation()
void clang::ASTRecordWriter::writeSourceLocation (SourceLocation Loc) inline
Definition at line 134 of file ASTRecordWriter.h.
References AddSourceLocation().
writeStmtRef()
void clang::ASTRecordWriter::writeStmtRef (const Stmt * S) inline
Definition at line 122 of file ASTRecordWriter.h.
References AddStmt().
Referenced by AddVarDeclInit().
writeUInt32()
void clang::ASTRecordWriter::writeUInt32 (uint32_t Value) inline
Definition at line 147 of file ASTRecordWriter.h.
Referenced by writeOMPChildren(), and writeOMPTraitInfo().
writeUInt64()
void clang::ASTRecordWriter::writeUInt64 (uint64_t Value) inline
Definition at line 151 of file ASTRecordWriter.h.
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTRecordWriter.h
lib/Serialization/ASTWriter.cpp
lib/Serialization/ASTWriterDecl.cpp
lib/Serialization/ASTWriterStmt.cpp