clang: clang::FullSourceLoc Class Reference
clang::FullSourceLoc Class Reference
A SourceLocation and its associated SourceManager.
#include "clang/Basic/SourceLocation.h"
Classes
struct BeforeThanCompare
Comparison function class, useful for sorting FullSourceLocs.
Public Member Functions
FullSourceLoc ()=default
Creates a FullSourceLoc where isValid() returns false.
FullSourceLoc (SourceLocation Loc, const SourceManager &SM)
bool hasManager () const
const SourceManager & getManager () const
FileID getFileID () const
FullSourceLoc getExpansionLoc () const
FullSourceLoc getSpellingLoc () const
FullSourceLoc getFileLoc () const
PresumedLoc getPresumedLoc (bool UseLineDirectives=true) const
bool isMacroArgExpansion (FullSourceLoc *StartLoc=nullptr) const
FullSourceLoc getImmediateMacroCallerLoc () const
std::pair< FullSourceLoc, StringRef > getModuleImportLoc () const
unsigned getFileOffset () const
unsigned getExpansionLineNumber (bool *Invalid=nullptr) const
unsigned getExpansionColumnNumber (bool *Invalid=nullptr) const
unsigned getSpellingLineNumber (bool *Invalid=nullptr) const
unsigned getSpellingColumnNumber (bool *Invalid=nullptr) const
const char * getCharacterData (bool *Invalid=nullptr) const
unsigned getLineNumber (bool *Invalid=nullptr) const
unsigned getColumnNumber (bool *Invalid=nullptr) const
const FileEntry * getFileEntry () const
StringRef getBufferData (bool *Invalid=nullptr) const
Return a StringRef to the source buffer data for the specified FileID.
std::pair< FileID, unsigned > getDecomposedLoc () const
Decompose the specified location into a raw FileID + Offset pair.
bool isInSystemHeader () const
bool isBeforeInTranslationUnitThan (SourceLocation Loc) const
Determines the order of 2 source locations in the translation unit.
bool isBeforeInTranslationUnitThan (FullSourceLoc Loc) const
Determines the order of 2 source locations in the translation unit.
void dump () const
Prints information about this FullSourceLoc to stderr.
Public Member Functions inherited from clang::SourceLocation
bool isFileID () const
bool isMacroID () const
bool isValid () const
Return true if this is a valid SourceLocation object.
bool isInvalid () const
SourceLocation getLocWithOffset (int Offset) const
Return a source location with the specified offset from this SourceLocation.
unsigned getRawEncoding () const
When a SourceLocation itself cannot be used, this returns an (opaque) 32-bit integer encoding for it.
void * getPtrEncoding () const
When a SourceLocation itself cannot be used, this returns an (opaque) pointer encoding for it.
unsigned getHashValue () const
void print (raw_ostream &OS, const SourceManager &SM) const
std::string printToString (const SourceManager &SM) const
void dump (const SourceManager &SM) const
Friends
bool operator== (const FullSourceLoc &LHS, const FullSourceLoc &RHS)
bool operator!= (const FullSourceLoc &LHS, const FullSourceLoc &RHS)
Additional Inherited Members
Static Public Member Functions inherited from clang::SourceLocation
static SourceLocation getFromRawEncoding (unsigned Encoding)
Turn a raw encoding of a SourceLocation object into a real SourceLocation.
static SourceLocation getFromPtrEncoding (const void *Encoding)
Turn a pointer encoding of a SourceLocation object back into a real SourceLocation.
static bool isPairOfFileLocations (SourceLocation Start, SourceLocation End)
Detailed Description
A SourceLocation and its associated SourceManager.
This is useful for argument passing to functions that expect both objects.
Definition at line 366 of file SourceLocation.h.
Constructor & Destructor Documentation
FullSourceLoc() [1/2]
clang::FullSourceLoc::FullSourceLoc () default
Creates a FullSourceLoc where isValid() returns false.
Referenced by getExpansionLoc(), getFileLoc(), getImmediateMacroCallerLoc(), getModuleImportLoc(), and getSpellingLoc().
FullSourceLoc() [2/2]
clang::FullSourceLoc::FullSourceLoc (SourceLocation Loc, const SourceManager & SM) inline explicit
Definition at line 373 of file SourceLocation.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void FullSourceLoc::dump () const
Prints information about this FullSourceLoc to stderr.
This is useful for debugging.
Definition at line 256 of file SourceLocation.cpp.
References clang::SourceLocation::dump().
getBufferData()
StringRef FullSourceLoc::getBufferData (bool * Invalid = nullptr) const
Return a StringRef to the source buffer data for the specified FileID.
Definition at line 265 of file SourceLocation.cpp.
References clang::SourceManager::getBufferData(), clang::SourceManager::getFileID(), and clang::SourceLocation::isValid().
getCharacterData()
const char * FullSourceLoc::getCharacterData (bool * Invalid = nullptr) const
Definition at line 260 of file SourceLocation.cpp.
References clang::SourceManager::getCharacterData(), and clang::SourceLocation::isValid().
getColumnNumber()
unsigned FullSourceLoc::getColumnNumber (bool * Invalid = nullptr) const
Definition at line 216 of file SourceLocation.cpp.
References clang::SourceManager::getColumnNumber(), getFileID(), getFileOffset(), and clang::SourceLocation::isValid().
Referenced by clang::TextDiagnostic::emitDiagnosticLoc().
getDecomposedLoc()
std::pair< FileID, unsigned > FullSourceLoc::getDecomposedLoc () const
Decompose the specified location into a raw FileID + Offset pair.
The first element is the FileID, the second is the offset from the start of the buffer of the location.
Definition at line 270 of file SourceLocation.cpp.
References clang::SourceManager::getDecomposedLoc().
Referenced by clang::tooling::AtomicChange::AtomicChange(), and compareCrossTUSourceLocs().
getExpansionColumnNumber()
unsigned FullSourceLoc::getExpansionColumnNumber (bool * Invalid = nullptr) const
Definition at line 231 of file SourceLocation.cpp.
References clang::SourceManager::getExpansionColumnNumber(), and clang::SourceLocation::isValid().
Referenced by clang::markup::EmitLocation().
getExpansionLineNumber()
unsigned FullSourceLoc::getExpansionLineNumber (bool * Invalid = nullptr) const
Definition at line 226 of file SourceLocation.cpp.
References clang::SourceManager::getExpansionLineNumber(), and clang::SourceLocation::isValid().
Referenced by clang::markup::EmitLocation(), and NormalizeLine().
getExpansionLoc()
FullSourceLoc FullSourceLoc::getExpansionLoc () const
Definition at line 164 of file SourceLocation.cpp.
References FullSourceLoc(), clang::SourceManager::getExpansionLoc(), and clang::SourceLocation::isValid().
Referenced by clang::TextDiagnostic::emitDiagnosticLoc(), and clang::ento::PathDiagnosticConsumer::HandlePathDiagnostic().
getFileEntry()
const FileEntry * FullSourceLoc::getFileEntry () const
Definition at line 221 of file SourceLocation.cpp.
References clang::SourceManager::getFileEntryForID(), getFileID(), and clang::SourceLocation::isValid().
Referenced by clang::TextDiagnostic::emitDiagnosticLoc().
getFileID()
FileID FullSourceLoc::getFileID () const
Definition at line 159 of file SourceLocation.cpp.
References clang::SourceManager::getFileID(), and clang::SourceLocation::isValid().
Referenced by compareCrossTUSourceLocs(), clang::TextDiagnostic::emitDiagnosticLoc(), getColumnNumber(), getFileEntry(), getLineNumber(), mapDiagnosticRanges(), and NormalizeLine().
getFileLoc()
FullSourceLoc FullSourceLoc::getFileLoc () const
Definition at line 174 of file SourceLocation.cpp.
References FullSourceLoc(), clang::SourceManager::getFileLoc(), and clang::SourceLocation::isValid().
Referenced by clang::DiagnosticRenderer::emitDiagnostic().
getFileOffset()
unsigned FullSourceLoc::getFileOffset () const
Definition at line 206 of file SourceLocation.cpp.
References clang::SourceManager::getFileOffset(), and clang::SourceLocation::isValid().
Referenced by getColumnNumber(), and getLineNumber().
getImmediateMacroCallerLoc()
FullSourceLoc FullSourceLoc::getImmediateMacroCallerLoc () const
Definition at line 191 of file SourceLocation.cpp.
References FullSourceLoc(), clang::SourceManager::getImmediateMacroCallerLoc(), and clang::SourceLocation::isValid().
getLineNumber()
unsigned FullSourceLoc::getLineNumber (bool * Invalid = nullptr) const
Definition at line 211 of file SourceLocation.cpp.
References getFileID(), getFileOffset(), clang::SourceManager::getLineNumber(), and clang::SourceLocation::isValid().
Referenced by clang::TextDiagnostic::emitDiagnosticLoc().
getManager()
const SourceManager & clang::FullSourceLoc::getManager () const inline
Precondition
This FullSourceLoc has an associated SourceManager.
Definition at line 383 of file SourceLocation.h.
Referenced by checkRangesForMacroArgExpansion(), compare(), compareCrossTUSourceLocs(), comparePiece(), clang::ento::PathDiagnosticLocation::createSingleLocation(), Diag(), clang::DiagnosticRenderer::emitDiagnostic(), clang::TextDiagnostic::emitDiagnosticLoc(), MakeCharSourceRange(), makeStandaloneDiagnostic(), and mapDiagnosticRanges().
getModuleImportLoc()
std::pair< FullSourceLoc, StringRef > FullSourceLoc::getModuleImportLoc () const
Definition at line 196 of file SourceLocation.cpp.
References FullSourceLoc(), clang::SourceManager::getModuleImportLoc(), and clang::SourceLocation::isValid().
getPresumedLoc()
PresumedLoc FullSourceLoc::getPresumedLoc (bool UseLineDirectives = true) const
Definition at line 179 of file SourceLocation.cpp.
References clang::SourceManager::getPresumedLoc(), and clang::SourceLocation::isValid().
Referenced by clang::DiagnosticRenderer::emitDiagnostic().
getSpellingColumnNumber()
unsigned FullSourceLoc::getSpellingColumnNumber (bool * Invalid = nullptr) const
Definition at line 241 of file SourceLocation.cpp.
References clang::SourceManager::getSpellingColumnNumber(), and clang::SourceLocation::isValid().
getSpellingLineNumber()
unsigned FullSourceLoc::getSpellingLineNumber (bool * Invalid = nullptr) const
Definition at line 236 of file SourceLocation.cpp.
References clang::SourceManager::getSpellingLineNumber(), and clang::SourceLocation::isValid().
getSpellingLoc()
FullSourceLoc FullSourceLoc::getSpellingLoc () const
Definition at line 169 of file SourceLocation.cpp.
References FullSourceLoc(), clang::SourceManager::getSpellingLoc(), and clang::SourceLocation::isValid().
Referenced by clang::tooling::AtomicChange::AtomicChange(), and compareCrossTUSourceLocs().
hasManager()
bool clang::FullSourceLoc::hasManager () const inline
Definition at line 376 of file SourceLocation.h.
References clang::SourceLocation::isValid().
Referenced by clang::DiagnosticRenderer::emitDiagnostic().
isBeforeInTranslationUnitThan() [1/2]
bool clang::FullSourceLoc::isBeforeInTranslationUnitThan (FullSourceLoc Loc) const inline
Determines the order of 2 source locations in the translation unit.
Returns
true if this source location comes before 'Loc', false otherwise.
Definition at line 432 of file SourceLocation.h.
References isBeforeInTranslationUnitThan(), and clang::SourceLocation::isValid().
isBeforeInTranslationUnitThan() [2/2]
bool FullSourceLoc::isBeforeInTranslationUnitThan (SourceLocation Loc) const
Determines the order of 2 source locations in the translation unit.
Returns
true if this source location comes before 'Loc', false otherwise.
Definition at line 251 of file SourceLocation.cpp.
References clang::SourceManager::isBeforeInTranslationUnit(), and clang::SourceLocation::isValid().
Referenced by clang::arcmt::CapturedDiagList::clearDiagnostic(), compareCall(), compareControlFlow(), compareCrossTUSourceLocs(), comparePiece(), clang::arcmt::CapturedDiagList::hasDiagnostic(), isBeforeInTranslationUnitThan(), and clang::FullSourceLoc::BeforeThanCompare::operator()().
isInSystemHeader()
bool FullSourceLoc::isInSystemHeader () const
Definition at line 246 of file SourceLocation.cpp.
References clang::SourceManager::isInSystemHeader(), and clang::SourceLocation::isValid().
isMacroArgExpansion()
bool FullSourceLoc::isMacroArgExpansion (FullSourceLoc * StartLoc = nullptr) const
Definition at line 186 of file SourceLocation.cpp.
References clang::SourceManager::isMacroArgExpansion(), and clang::SourceLocation::isValid().
Referenced by checkRangesForMacroArgExpansion().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FullSourceLoc & LHS, const FullSourceLoc & RHS) friend
Definition at line 457 of file SourceLocation.h.
operator==
bool operator== (const FullSourceLoc & LHS, const FullSourceLoc & RHS) friend
Definition at line 451 of file SourceLocation.h.
The documentation for this class was generated from the following files:
include/clang/Basic/SourceLocation.h
lib/Basic/SourceLocation.cpp