clang: clang::comments::InlineCommandComment Class Reference
clang::comments::InlineCommandComment Class Reference
A command with word-like arguments that is considered inline content.
#include "clang/AST/Comment.h"
Classes
struct Argument
Public Types
enum RenderKind {
RenderNormal , RenderBold , RenderMonospaced , RenderEmphasized ,
RenderAnchor
}
The most appropriate rendering mode for this command, chosen on command semantics in Doxygen.
Public Types inherited from clang::comments::Comment
enum CommentKind { NoCommentKind = 0 }
typedef Comment *const * child_iterator
Public Member Functions
InlineCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, RenderKind RK, ArrayRef< Argument > Args)
child_iterator child_begin () const
child_iterator child_end () const
unsigned getCommandID () const
StringRef getCommandName (const CommandTraits &Traits) const
SourceRange getCommandNameRange () const
RenderKind getRenderKind () const
unsigned getNumArgs () const
StringRef getArgText (unsigned Idx) const
SourceRange getArgRange (unsigned Idx) const
Public Member Functions inherited from clang::comments::InlineContentComment
void addTrailingNewline ()
bool hasTrailingNewline () const
Public Member Functions inherited from clang::comments::Comment
Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
CommentKind getCommentKind () const
const char * getCommentKindName () const
void dump () const
void dumpColor () const
void dump (raw_ostream &OS, const ASTContext &Context) const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const LLVM_READONLY
child_iterator child_begin () const
child_iterator child_end () const
unsigned child_count () const
Static Public Member Functions
static bool classof (const Comment *C)
Static Public Member Functions inherited from clang::comments::InlineContentComment
static bool classof (const Comment *C)
Protected Attributes
ArrayRef< Argument > Args
Command arguments.
Protected Attributes inherited from clang::comments::Comment
SourceLocation Loc
Preferred location to show caret.
SourceRange Range
Source range of this AST node.
union {
CommentBitfields CommentBits
InlineContentCommentBitfields InlineContentCommentBits
TextCommentBitfields TextCommentBits
InlineCommandCommentBitfields InlineCommandCommentBits
HTMLTagCommentBitfields HTMLTagCommentBits
HTMLStartTagCommentBitfields HTMLStartTagCommentBits
ParagraphCommentBitfields ParagraphCommentBits
BlockCommandCommentBitfields BlockCommandCommentBits
ParamCommandCommentBitfields ParamCommandCommentBits
};
Additional Inherited Members
Public Attributes inherited from clang::comments::Comment
Protected Types inherited from clang::comments::Comment
enum { NumCommentBits = 8 }
enum { NumInlineContentCommentBits = NumCommentBits + 1 }
enum { NumTextCommentBits = NumInlineContentCommentBits + 2 }
enum { NumInlineCommandCommentBits }
enum { NumHTMLTagCommentBits = NumInlineContentCommentBits + 1 }
enum { NumHTMLStartTagCommentBits = NumHTMLTagCommentBits + 1 }
enum { NumParagraphCommentBits = NumCommentBits + 2 }
enum { NumBlockCommandCommentBits }
enum { NumParamCommandCommentBits = NumBlockCommandCommentBits + 3 }
Protected Member Functions inherited from clang::comments::InlineContentComment
InlineContentComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
Protected Member Functions inherited from clang::comments::Comment
void setSourceRange (SourceRange SR)
void setLocation (SourceLocation L)
Detailed Description
A command with word-like arguments that is considered inline content.
Definition at line 297 of file Comment.h.
Member Enumeration Documentation
RenderKind
enum clang::comments::InlineCommandComment::RenderKind
The most appropriate rendering mode for this command, chosen on command semantics in Doxygen.
Enumerator
RenderNormal
RenderBold
RenderMonospaced
RenderEmphasized
RenderAnchor
Definition at line 308 of file Comment.h.
Constructor & Destructor Documentation
InlineCommandComment()
clang::comments::InlineCommandComment::InlineCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, RenderKind RK, ArrayRef< Argument > Args) inline
Definition at line 321 of file Comment.h.
References clang::comments::Comment::InlineCommandCommentBits.
Member Function Documentation
child_begin()
child_iterator clang::comments::InlineCommandComment::child_begin () const inline
Definition at line 336 of file Comment.h.
child_end()
child_iterator clang::comments::InlineCommandComment::child_end () const inline
Definition at line 338 of file Comment.h.
classof()
static bool clang::comments::InlineCommandComment::classof (const Comment * C) inline static
Definition at line 332 of file Comment.h.
References clang::C.
getArgRange()
SourceRange clang::comments::InlineCommandComment::getArgRange (unsigned Idx) const inline
Definition at line 364 of file Comment.h.
References Args.
getArgText()
StringRef clang::comments::InlineCommandComment::getArgText (unsigned Idx) const inline
Definition at line 360 of file Comment.h.
References Args.
getCommandID()
unsigned clang::comments::InlineCommandComment::getCommandID () const inline
Definition at line 340 of file Comment.h.
References clang::comments::Comment::InlineCommandCommentBits.
Referenced by getCommandName().
getCommandName()
StringRef clang::comments::InlineCommandComment::getCommandName (const CommandTraits & Traits) const inline
Definition at line 344 of file Comment.h.
References getCommandID(), clang::comments::CommandTraits::getCommandInfo(), and clang::comments::CommandInfo::Name.
getCommandNameRange()
SourceRange clang::comments::InlineCommandComment::getCommandNameRange () const inline
Definition at line 348 of file Comment.h.
References clang::comments::Comment::getBeginLoc(), and clang::comments::Comment::getEndLoc().
getNumArgs()
unsigned clang::comments::InlineCommandComment::getNumArgs () const inline
Definition at line 356 of file Comment.h.
References Args.
getRenderKind()
RenderKind clang::comments::InlineCommandComment::getRenderKind () const inline
Definition at line 352 of file Comment.h.
References clang::comments::Comment::InlineCommandCommentBits.
Member Data Documentation
Args
ArrayRef<Argument> clang::comments::InlineCommandComment::Args protected
Command arguments.
Definition at line 318 of file Comment.h.
Referenced by getArgRange(), getArgText(), and getNumArgs().
The documentation for this class was generated from the following file:
include/clang/AST/Comment.h