clang: clang::driver::tools::AVR::Linker Class Reference
clang::driver::tools::AVR::Linker Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/AVR.h"
Public Member Functions
Linker (const llvm::Triple &Triple, const ToolChain &TC, bool LinkStdlib)
bool hasIntegratedCPP () const override
bool isLinkJob () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Protected Attributes
const llvm::Triple & Triple
bool LinkStdlib
Detailed Description
Definition at line 43 of file AVR.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::AVR::Linker::Linker (const llvm::Triple & Triple, const ToolChain & TC, bool LinkStdlib) inline
Definition at line 45 of file AVR.h.
Member Function Documentation
ConstructJob()
void AVR::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 357 of file AVR.cpp.
References clang::driver::tools::AddLinkerInputs(), clang::driver::ResponseFileSupport::AtFileCurCP(), clang::C, clang::driver::tools::getCPUName(), and clang::driver::InputInfo::getFilename().
hasIntegratedCPP()
bool clang::driver::tools::AVR::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 49 of file AVR.h.
isLinkJob()
bool clang::driver::tools::AVR::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 50 of file AVR.h.
Member Data Documentation
LinkStdlib
bool clang::driver::tools::AVR::Linker::LinkStdlib protected
Definition at line 58 of file AVR.h.
Triple
const llvm::Triple& clang::driver::tools::AVR::Linker::Triple protected
Definition at line 57 of file AVR.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/AVR.h
lib/Driver/ToolChains/AVR.cpp