clang: clang::ExprMutationAnalyzer Class Reference
clang::ExprMutationAnalyzer Class Reference
Analyzes whether any mutative operations are applied to an expression within a given statement.
#include "clang/Analysis/Analyses/ExprMutationAnalyzer.h"
Public Member Functions
ExprMutationAnalyzer (const Stmt &Stm, ASTContext &Context)
bool isMutated (const Expr *Exp)
bool isMutated (const Decl *Dec)
const Stmt * findMutation (const Expr *Exp)
const Stmt * findMutation (const Decl *Dec)
bool isPointeeMutated (const Expr *Exp)
bool isPointeeMutated (const Decl *Dec)
const Stmt * findPointeeMutation (const Expr *Exp)
const Stmt * findPointeeMutation (const Decl *Dec)
Detailed Description
Analyzes whether any mutative operations are applied to an expression within a given statement.
Definition at line 23 of file ExprMutationAnalyzer.h.
Constructor & Destructor Documentation
ExprMutationAnalyzer()
clang::ExprMutationAnalyzer::ExprMutationAnalyzer (const Stmt & Stm, ASTContext & Context) inline
Definition at line 25 of file ExprMutationAnalyzer.h.
Member Function Documentation
findMutation() [1/2]
const Stmt * clang::ExprMutationAnalyzer::findMutation (const Decl * Dec)
Definition at line 154 of file ExprMutationAnalyzer.cpp.
References findMutation().
findMutation() [2/2]
const Stmt * clang::ExprMutationAnalyzer::findMutation (const Expr * Exp)
Definition at line 142 of file ExprMutationAnalyzer.cpp.
Referenced by findMutation(), clang::FunctionParmMutationAnalyzer::findMutation(), clang::FunctionParmMutationAnalyzer::FunctionParmMutationAnalyzer(), isMutated(), and isMutated().
findPointeeMutation() [1/2]
const Stmt * clang::ExprMutationAnalyzer::findPointeeMutation (const Decl * Dec)
Definition at line 162 of file ExprMutationAnalyzer.cpp.
References findPointeeMutation().
findPointeeMutation() [2/2]
const Stmt * clang::ExprMutationAnalyzer::findPointeeMutation (const Expr * Exp)
Definition at line 158 of file ExprMutationAnalyzer.cpp.
Referenced by findPointeeMutation(), isPointeeMutated(), and isPointeeMutated().
isMutated() [1/2]
bool clang::ExprMutationAnalyzer::isMutated (const Decl * Dec) inline
Definition at line 29 of file ExprMutationAnalyzer.h.
References findMutation().
isMutated() [2/2]
bool clang::ExprMutationAnalyzer::isMutated (const Expr * Exp) inline
Definition at line 28 of file ExprMutationAnalyzer.h.
References findMutation().
isPointeeMutated() [1/2]
bool clang::ExprMutationAnalyzer::isPointeeMutated (const Decl * Dec) inline
Definition at line 36 of file ExprMutationAnalyzer.h.
References findPointeeMutation().
isPointeeMutated() [2/2]
bool clang::ExprMutationAnalyzer::isPointeeMutated (const Expr * Exp) inline
Definition at line 33 of file ExprMutationAnalyzer.h.
References findPointeeMutation().
The documentation for this class was generated from the following files:
include/clang/Analysis/Analyses/ExprMutationAnalyzer.h
lib/Analysis/ExprMutationAnalyzer.cpp