clang: clang::comments::Sema Class Reference
clang::comments::Sema Class Reference
#include "clang/AST/CommentSema.h"
Public Member Functions
Sema (llvm::BumpPtrAllocator &Allocator, const SourceManager &SourceMgr, DiagnosticsEngine &Diags, CommandTraits &Traits, const Preprocessor *PP)
void setDecl (const Decl *D)
template<typename T >
ArrayRef< T > copyArray (ArrayRef< T > Source)
Returns a copy of array, owned by Sema's allocator.
ParagraphComment * actOnParagraphComment (ArrayRef< InlineContentComment * > Content)
BlockCommandComment * actOnBlockCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
void actOnBlockCommandArgs (BlockCommandComment *Command, ArrayRef< BlockCommandComment::Argument > Args)
void actOnBlockCommandFinish (BlockCommandComment *Command, ParagraphComment *Paragraph)
ParamCommandComment * actOnParamCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
void actOnParamCommandDirectionArg (ParamCommandComment *Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
void actOnParamCommandParamNameArg (ParamCommandComment *Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
void actOnParamCommandFinish (ParamCommandComment *Command, ParagraphComment *Paragraph)
TParamCommandComment * actOnTParamCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
void actOnTParamCommandParamNameArg (TParamCommandComment *Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
void actOnTParamCommandFinish (TParamCommandComment *Command, ParagraphComment *Paragraph)
InlineCommandComment * actOnInlineCommand (SourceLocation CommandLocBegin, SourceLocation CommandLocEnd, unsigned CommandID)
InlineCommandComment * actOnInlineCommand (SourceLocation CommandLocBegin, SourceLocation CommandLocEnd, unsigned CommandID, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
InlineContentComment * actOnUnknownCommand (SourceLocation LocBegin, SourceLocation LocEnd, StringRef CommandName)
InlineContentComment * actOnUnknownCommand (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID)
TextComment * actOnText (SourceLocation LocBegin, SourceLocation LocEnd, StringRef Text)
VerbatimBlockComment * actOnVerbatimBlockStart (SourceLocation Loc, unsigned CommandID)
VerbatimBlockLineComment * actOnVerbatimBlockLine (SourceLocation Loc, StringRef Text)
void actOnVerbatimBlockFinish (VerbatimBlockComment *Block, SourceLocation CloseNameLocBegin, StringRef CloseName, ArrayRef< VerbatimBlockLineComment * > Lines)
VerbatimLineComment * actOnVerbatimLine (SourceLocation LocBegin, unsigned CommandID, SourceLocation TextBegin, StringRef Text)
HTMLStartTagComment * actOnHTMLStartTagStart (SourceLocation LocBegin, StringRef TagName)
void actOnHTMLStartTagFinish (HTMLStartTagComment *Tag, ArrayRef< HTMLStartTagComment::Attribute > Attrs, SourceLocation GreaterLoc, bool IsSelfClosing)
HTMLEndTagComment * actOnHTMLEndTag (SourceLocation LocBegin, SourceLocation LocEnd, StringRef TagName)
FullComment * actOnFullComment (ArrayRef< BlockContentComment * > Blocks)
void checkBlockCommandEmptyParagraph (BlockCommandComment *Command)
void checkReturnsCommand (const BlockCommandComment *Command)
void checkBlockCommandDuplicate (const BlockCommandComment *Command)
Emit diagnostics about duplicate block commands that should be used only once per comment, e.g., \and \returns.
void checkDeprecatedCommand (const BlockCommandComment *Comment)
void checkFunctionDeclVerbatimLine (const BlockCommandComment *Comment)
void checkContainerDeclVerbatimLine (const BlockCommandComment *Comment)
void checkContainerDecl (const BlockCommandComment *Comment)
void resolveParamCommandIndexes (const FullComment *FC)
Resolve parameter names to parameter indexes in function declaration.
bool isFunctionDecl ()
bool isAnyFunctionDecl ()
bool isFunctionPointerVarDecl ()
bool isFunctionOrBlockPointerVarLikeDecl ()
bool isFunctionOrMethodVariadic ()
bool isObjCMethodDecl ()
bool isObjCPropertyDecl ()
bool isTemplateOrSpecialization ()
bool isRecordLikeDecl ()
bool isClassOrStructDecl ()
bool isClassOrStructOrTagTypedefDecl ()
bool isUnionDecl ()
bool isObjCInterfaceDecl ()
bool isObjCProtocolDecl ()
bool isClassTemplateDecl ()
bool isFunctionTemplateDecl ()
ArrayRef< const ParmVarDecl * > getParamVars ()
void inspectThisDecl ()
Extract all important semantic information from ThisDeclInfo->ThisDecl into ThisDeclInfo members.
unsigned resolveParmVarReference (StringRef Name, ArrayRef< const ParmVarDecl * > ParamVars)
Returns index of a function parameter with a given name.
unsigned correctTypoInParmVarReference (StringRef Typo, ArrayRef< const ParmVarDecl * > ParamVars)
Returns index of a function parameter with the name closest to a given typo.
bool resolveTParamReference (StringRef Name, const TemplateParameterList *TemplateParameters, SmallVectorImpl< unsigned > *Position)
StringRef correctTypoInTParamReference (StringRef Typo, const TemplateParameterList *TemplateParameters)
InlineCommandComment::RenderKind getInlineCommandRenderKind (StringRef Name) const
Detailed Description
Definition at line 32 of file CommentSema.h.
Constructor & Destructor Documentation
Sema()
clang::comments::Sema::Sema (llvm::BumpPtrAllocator & Allocator, const SourceManager & SourceMgr, DiagnosticsEngine & Diags, CommandTraits & Traits, const Preprocessor * PP)
Definition at line 28 of file CommentSema.cpp.
Member Function Documentation
actOnBlockCommandArgs()
void clang::comments::Sema::actOnBlockCommandArgs (BlockCommandComment * Command, ArrayRef< BlockCommandComment::Argument > Args)
Definition at line 62 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::setArgs().
Referenced by clang::comments::Parser::parseBlockCommandArgs().
actOnBlockCommandFinish()
void clang::comments::Sema::actOnBlockCommandFinish (BlockCommandComment * Command, ParagraphComment * Paragraph)
Definition at line 67 of file CommentSema.cpp.
References checkBlockCommandDuplicate(), checkBlockCommandEmptyParagraph(), checkDeprecatedCommand(), checkReturnsCommand(), and clang::comments::BlockCommandComment::setParagraph().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnBlockCommandStart()
BlockCommandComment * clang::comments::Sema::actOnBlockCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Definition at line 50 of file CommentSema.cpp.
References checkContainerDecl().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnFullComment()
FullComment * clang::comments::Sema::actOnFullComment (ArrayRef< BlockContentComment * > Blocks)
Definition at line 546 of file CommentSema.cpp.
References clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), clang::comments::HTMLTagComment::getTagName(), resolveParamCommandIndexes(), and clang::comments::HTMLTagComment::setIsMalformed().
Referenced by clang::comments::Parser::parseFullComment().
actOnHTMLEndTag()
HTMLEndTagComment * clang::comments::Sema::actOnHTMLEndTag (SourceLocation LocBegin, SourceLocation LocEnd, StringRef TagName)
Definition at line 478 of file CommentSema.cpp.
References clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), clang::comments::HTMLTagComment::getTagName(), clang::comments::HTMLTagComment::isMalformed(), and clang::comments::HTMLTagComment::setIsMalformed().
Referenced by clang::comments::Parser::parseHTMLEndTag().
actOnHTMLStartTagFinish()
void clang::comments::Sema::actOnHTMLStartTagFinish (HTMLStartTagComment * Tag, ArrayRef< HTMLStartTagComment::Attribute > Attrs, SourceLocation GreaterLoc, bool IsSelfClosing)
Definition at line 465 of file CommentSema.cpp.
References clang::comments::HTMLStartTagComment::setAttrs().
Referenced by clang::comments::Parser::parseHTMLStartTag().
actOnHTMLStartTagStart()
HTMLStartTagComment * clang::comments::Sema::actOnHTMLStartTagStart (SourceLocation LocBegin, StringRef TagName)
Definition at line 460 of file CommentSema.cpp.
Referenced by clang::comments::Parser::parseHTMLStartTag().
actOnInlineCommand() [1/2]
InlineCommandComment * clang::comments::Sema::actOnInlineCommand (SourceLocation CommandLocBegin, SourceLocation CommandLocEnd, unsigned CommandID)
Definition at line 366 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), getInlineCommandRenderKind(), and clang::comments::CommandInfo::Name.
Referenced by clang::comments::Parser::parseInlineCommand().
actOnInlineCommand() [2/2]
InlineCommandComment * clang::comments::Sema::actOnInlineCommand (SourceLocation CommandLocBegin, SourceLocation CommandLocEnd, unsigned CommandID, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
Definition at line 379 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), getInlineCommandRenderKind(), and clang::comments::CommandInfo::Name.
actOnParagraphComment()
ParagraphComment * clang::comments::Sema::actOnParagraphComment (ArrayRef< InlineContentComment * > Content)
Definition at line 45 of file CommentSema.cpp.
Referenced by clang::comments::Parser::parseBlockCommand(), and clang::comments::Parser::parseParagraphOrBlockCommand().
actOnParamCommandDirectionArg()
void clang::comments::Sema::actOnParamCommandDirectionArg (ParamCommandComment * Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
Definition at line 230 of file CommentSema.cpp.
References clang::FixItHint::CreateReplacement(), clang::comments::ParamCommandComment::getDirectionAsString(), clang::comments::getParamPassDirection(), clang::comments::ParamCommandComment::In, clang::isWhitespace(), and clang::comments::ParamCommandComment::setDirection().
Referenced by clang::comments::Parser::parseParamCommandArgs().
actOnParamCommandFinish()
void clang::comments::Sema::actOnParamCommandFinish (ParamCommandComment * Command, ParagraphComment * Paragraph)
Definition at line 277 of file CommentSema.cpp.
References checkBlockCommandEmptyParagraph(), and clang::comments::BlockCommandComment::setParagraph().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnParamCommandParamNameArg()
void clang::comments::Sema::actOnParamCommandParamNameArg (ParamCommandComment * Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
Definition at line 259 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::getNumArgs(), clang::comments::ParamCommandComment::In, clang::comments::ParamCommandComment::isDirectionExplicit(), clang::comments::BlockCommandComment::setArgs(), and clang::comments::ParamCommandComment::setDirection().
Referenced by clang::comments::Parser::parseParamCommandArgs().
actOnParamCommandStart()
ParamCommandComment * clang::comments::Sema::actOnParamCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Definition at line 80 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::getCommandNameRange(), clang::comments::Comment::getLocation(), isFunctionDecl(), and isFunctionOrBlockPointerVarLikeDecl().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnText()
TextComment * clang::comments::Sema::actOnText (SourceLocation LocBegin, SourceLocation LocEnd, StringRef Text)
Definition at line 416 of file CommentSema.cpp.
References Text.
Referenced by clang::comments::Parser::parseParagraphOrBlockCommand().
actOnTParamCommandFinish()
void clang::comments::Sema::actOnTParamCommandFinish (TParamCommandComment * Command, ParagraphComment * Paragraph)
Definition at line 360 of file CommentSema.cpp.
References checkBlockCommandEmptyParagraph(), and clang::comments::BlockCommandComment::setParagraph().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnTParamCommandParamNameArg()
void clang::comments::Sema::actOnTParamCommandParamNameArg (TParamCommandComment * Command, SourceLocation ArgLocBegin, SourceLocation ArgLocEnd, StringRef Arg)
Definition at line 301 of file CommentSema.cpp.
References copyArray(), correctTypoInTParamReference(), clang::FixItHint::CreateReplacement(), clang::comments::Comment::getLocation(), clang::IdentifierInfo::getName(), clang::comments::BlockCommandComment::getNumArgs(), clang::TemplateParameterList::getParam(), clang::comments::TParamCommandComment::getParamNameRange(), isTemplateOrSpecialization(), resolveTParamReference(), clang::comments::BlockCommandComment::setArgs(), clang::comments::TParamCommandComment::setPosition(), clang::TemplateParameterList::size(), and clang::comments::DeclInfo::TemplateParameters.
Referenced by clang::comments::Parser::parseTParamCommandArgs().
actOnTParamCommandStart()
TParamCommandComment * clang::comments::Sema::actOnTParamCommandStart (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Definition at line 283 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::getCommandNameRange(), clang::comments::Comment::getLocation(), and isTemplateOrSpecialization().
Referenced by clang::comments::Parser::parseBlockCommand().
actOnUnknownCommand() [1/2]
InlineContentComment * clang::comments::Sema::actOnUnknownCommand (SourceLocation LocBegin, SourceLocation LocEnd, StringRef CommandName)
Definition at line 399 of file CommentSema.cpp.
References actOnUnknownCommand(), clang::comments::CommandInfo::getID(), and clang::comments::CommandTraits::registerUnknownCommand().
Referenced by actOnUnknownCommand(), and clang::comments::Parser::parseParagraphOrBlockCommand().
actOnUnknownCommand() [2/2]
InlineContentComment * clang::comments::Sema::actOnUnknownCommand (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID)
Definition at line 406 of file CommentSema.cpp.
References clang::comments::InlineCommandComment::RenderNormal.
actOnVerbatimBlockFinish()
void clang::comments::Sema::actOnVerbatimBlockFinish (VerbatimBlockComment * Block, SourceLocation CloseNameLocBegin, StringRef CloseName, ArrayRef< VerbatimBlockLineComment * > Lines)
Definition at line 436 of file CommentSema.cpp.
References clang::Block.
Referenced by clang::comments::Parser::parseVerbatimBlock().
actOnVerbatimBlockLine()
VerbatimBlockLineComment * clang::comments::Sema::actOnVerbatimBlockLine (SourceLocation Loc, StringRef Text)
Definition at line 431 of file CommentSema.cpp.
References Text.
Referenced by clang::comments::Parser::parseVerbatimBlock().
actOnVerbatimBlockStart()
VerbatimBlockComment * clang::comments::Sema::actOnVerbatimBlockStart (SourceLocation Loc, unsigned CommandID)
Definition at line 422 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), clang::SourceLocation::getLocWithOffset(), and clang::comments::CommandInfo::Name.
Referenced by clang::comments::Parser::parseVerbatimBlock().
actOnVerbatimLine()
VerbatimLineComment * clang::comments::Sema::actOnVerbatimLine (SourceLocation LocBegin, unsigned CommandID, SourceLocation TextBegin, StringRef Text)
Definition at line 445 of file CommentSema.cpp.
References checkContainerDeclVerbatimLine(), checkFunctionDeclVerbatimLine(), clang::SourceLocation::getLocWithOffset(), and Text.
Referenced by clang::comments::Parser::parseVerbatimLine().
checkBlockCommandDuplicate()
void clang::comments::Sema::checkBlockCommandDuplicate (const BlockCommandComment * Command)
Emit diagnostics about duplicate block commands that should be used only once per comment, e.g., \and \returns.
Definition at line 629 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::getCommandID(), clang::comments::CommandTraits::getCommandInfo(), clang::comments::BlockCommandComment::getCommandMarker(), clang::comments::BlockCommandComment::getCommandName(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), clang::comments::CommandInfo::IsBriefCommand, and clang::comments::CommandInfo::IsHeaderfileCommand.
Referenced by actOnBlockCommandFinish().
checkBlockCommandEmptyParagraph()
void clang::comments::Sema::checkBlockCommandEmptyParagraph (BlockCommandComment * Command)
Definition at line 565 of file CommentSema.cpp.
References clang::comments::BlockCommandComment::getArgRange(), clang::comments::BlockCommandComment::getCommandID(), clang::comments::CommandTraits::getCommandInfo(), clang::comments::BlockCommandComment::getCommandMarker(), clang::comments::BlockCommandComment::getCommandName(), clang::comments::BlockCommandComment::getCommandNameRange(), clang::SourceRange::getEnd(), clang::comments::BlockCommandComment::getNumArgs(), clang::comments::BlockCommandComment::getParagraph(), clang::comments::Comment::getSourceRange(), clang::comments::CommandInfo::IsEmptyParagraphAllowed, clang::SourceLocation::isValid(), and clang::comments::ParagraphComment::isWhitespace().
Referenced by actOnBlockCommandFinish(), actOnParamCommandFinish(), and actOnTParamCommandFinish().
checkContainerDecl()
void clang::comments::Sema::checkContainerDecl (const BlockCommandComment * Comment)
Definition at line 170 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), isRecordLikeDecl(), and clang::comments::CommandInfo::IsRecordLikeDetailCommand.
Referenced by actOnBlockCommandStart().
checkContainerDeclVerbatimLine()
void clang::comments::Sema::checkContainerDeclVerbatimLine (const BlockCommandComment * Comment)
Definition at line 131 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), isClassOrStructOrTagTypedefDecl(), isClassTemplateDecl(), isObjCInterfaceDecl(), isObjCProtocolDecl(), clang::comments::CommandInfo::IsRecordLikeDeclarationCommand, and isUnionDecl().
Referenced by actOnVerbatimLine().
checkDeprecatedCommand()
void clang::comments::Sema::checkDeprecatedCommand (const BlockCommandComment * Comment)
Definition at line 667 of file CommentSema.cpp.
References clang::comments::DeclInfo::CommentDecl, clang::FixItHint::CreateInsertion(), clang::comments::BlockCommandComment::getCommandID(), clang::comments::CommandTraits::getCommandInfo(), clang::comments::BlockCommandComment::getCommandMarker(), clang::Preprocessor::getIdentifierInfo(), clang::Preprocessor::getLastMacroWithSpelling(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), clang::Decl::hasAttr(), clang::comments::CommandInfo::IsDeprecatedCommand, and clang::DeclContext::isRecord().
Referenced by actOnBlockCommandFinish().
checkFunctionDeclVerbatimLine()
void clang::comments::Sema::checkFunctionDeclVerbatimLine (const BlockCommandComment * Comment)
Definition at line 98 of file CommentSema.cpp.
References clang::comments::CommandTraits::getCommandInfo(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), isAnyFunctionDecl(), clang::comments::CommandInfo::IsFunctionDeclarationCommand, isFunctionPointerVarDecl(), isFunctionTemplateDecl(), and isObjCMethodDecl().
Referenced by actOnVerbatimLine().
checkReturnsCommand()
void clang::comments::Sema::checkReturnsCommand (const BlockCommandComment * Command)
Definition at line 583 of file CommentSema.cpp.
References clang::comments::DeclInfo::CommentDecl, clang::comments::BlockCommandComment::getCommandID(), clang::comments::CommandTraits::getCommandInfo(), clang::comments::BlockCommandComment::getCommandMarker(), clang::comments::BlockCommandComment::getCommandName(), clang::Decl::getKind(), clang::comments::Comment::getLocation(), clang::comments::Comment::getSourceRange(), isFunctionDecl(), isFunctionOrBlockPointerVarLikeDecl(), clang::QualType::isNull(), clang::comments::DeclInfo::IsObjCMethod, isObjCPropertyDecl(), clang::comments::CommandInfo::IsReturnsCommand, clang::Type::isVoidType(), and clang::comments::DeclInfo::ReturnType.
Referenced by actOnBlockCommandFinish().
copyArray()
template<typename T > ArrayRef< T > clang::comments::Sema::copyArray (ArrayRef< T > Source) inline
Returns a copy of array, owned by Sema's allocator.
Definition at line 80 of file CommentSema.h.
References clang::None.
Referenced by actOnTParamCommandParamNameArg(), clang::comments::Parser::parseFullComment(), clang::comments::Parser::parseHTMLStartTag(), clang::comments::Parser::parseParagraphOrBlockCommand(), and clang::comments::Parser::parseVerbatimBlock().
correctTypoInParmVarReference()
unsigned clang::comments::Sema::correctTypoInParmVarReference (StringRef Typo, ArrayRef< const ParmVarDecl * > ParamVars)
Returns index of a function parameter with the name closest to a given typo.
Definition at line 1098 of file CommentSema.cpp.
References clang::comments::ParamCommandComment::InvalidParamIndex.
Referenced by resolveParamCommandIndexes().
correctTypoInTParamReference()
StringRef clang::comments::Sema::correctTypoInTParamReference (StringRef Typo, const TemplateParameterList * TemplateParameters)
Definition at line 1163 of file CommentSema.cpp.
References clang::IdentifierInfo::getName().
Referenced by actOnTParamCommandParamNameArg().
getInlineCommandRenderKind()
InlineCommandComment::RenderKind clang::comments::Sema::getInlineCommandRenderKind (StringRef Name) const
Definition at line 1177 of file CommentSema.cpp.
References clang::comments::InlineCommandComment::RenderAnchor, clang::comments::InlineCommandComment::RenderBold, clang::comments::InlineCommandComment::RenderEmphasized, clang::comments::InlineCommandComment::RenderMonospaced, and clang::comments::InlineCommandComment::RenderNormal.
Referenced by actOnInlineCommand(), and actOnInlineCommand().
getParamVars()
ArrayRef< const ParmVarDecl * > clang::comments::Sema::getParamVars ()
Definition at line 1023 of file CommentSema.cpp.
References inspectThisDecl(), clang::comments::DeclInfo::IsFilled, and clang::comments::DeclInfo::ParamVars.
Referenced by resolveParamCommandIndexes().
inspectThisDecl()
void clang::comments::Sema::inspectThisDecl ()
Extract all important semantic information from ThisDeclInfo->ThisDecl into ThisDeclInfo members.
Definition at line 1029 of file CommentSema.cpp.
References clang::comments::DeclInfo::fill().
Referenced by getParamVars(), isClassOrStructDecl(), isClassOrStructOrTagTypedefDecl(), isClassTemplateDecl(), isFunctionDecl(), isFunctionOrBlockPointerVarLikeDecl(), isFunctionPointerVarDecl(), isFunctionTemplateDecl(), isObjCInterfaceDecl(), isObjCPropertyDecl(), isObjCProtocolDecl(), isRecordLikeDecl(), isTemplateOrSpecialization(), and isUnionDecl().
isAnyFunctionDecl()
bool clang::comments::Sema::isAnyFunctionDecl ()
Definition at line 829 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::isa(), and isFunctionDecl().
Referenced by checkFunctionDeclVerbatimLine().
isClassOrStructDecl()
bool clang::comments::Sema::isClassOrStructDecl ()
Definition at line 948 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::comments::isClassOrStructDeclImpl(), and clang::comments::DeclInfo::IsFilled.
Referenced by isRecordLikeDecl().
isClassOrStructOrTagTypedefDecl()
bool clang::comments::Sema::isClassOrStructOrTagTypedefDecl ()
Returns
true if the declaration that this comment is attached to declares either struct, class or tag typedef.
Definition at line 960 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::comments::isClassOrStructDeclImpl(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkContainerDeclVerbatimLine().
isClassTemplateDecl()
bool clang::comments::Sema::isClassTemplateDecl ()
Definition at line 987 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::isa(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkContainerDeclVerbatimLine().
isFunctionDecl()
bool clang::comments::Sema::isFunctionDecl ()
Definition at line 821 of file CommentSema.cpp.
References clang::comments::DeclInfo::FunctionKind, clang::comments::DeclInfo::getKind(), inspectThisDecl(), and clang::comments::DeclInfo::IsFilled.
Referenced by actOnParamCommandStart(), checkReturnsCommand(), isAnyFunctionDecl(), isFunctionOrMethodVariadic(), isObjCMethodDecl(), and resolveParamCommandIndexes().
isFunctionOrBlockPointerVarLikeDecl()
bool clang::comments::Sema::isFunctionOrBlockPointerVarLikeDecl ()
Returns
true if the declaration that this comment is attached to declares a variable or a field whose type is a function or a block pointer.
Definition at line 876 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::Type::getAs(), clang::comments::DeclInfo::getKind(), inspectThisDecl(), clang::Type::isBlockPointerType(), clang::comments::DeclInfo::IsFilled, clang::Type::isFunctionPointerType(), P, and clang::comments::DeclInfo::VariableKind.
Referenced by actOnParamCommandStart(), and checkReturnsCommand().
isFunctionOrMethodVariadic()
bool clang::comments::Sema::isFunctionOrMethodVariadic ()
Definition at line 834 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::Type::getAs(), clang::Type::getPointeeType(), clang::Type::isBlockPointerType(), isFunctionDecl(), and clang::Type::isFunctionPointerType().
Referenced by resolveParmVarReference().
isFunctionPointerVarDecl()
bool clang::comments::Sema::isFunctionPointerVarDecl ()
Returns
true if declaration that this comment is attached to declares a function pointer.
Definition at line 862 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::comments::DeclInfo::getKind(), inspectThisDecl(), clang::comments::DeclInfo::IsFilled, clang::Type::isFunctionPointerType(), and clang::comments::DeclInfo::VariableKind.
Referenced by checkFunctionDeclVerbatimLine().
isFunctionTemplateDecl()
bool clang::comments::Sema::isFunctionTemplateDecl ()
Definition at line 996 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::isa(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkFunctionDeclVerbatimLine().
isObjCInterfaceDecl()
bool clang::comments::Sema::isObjCInterfaceDecl ()
Definition at line 1005 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::isa(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkContainerDeclVerbatimLine(), and isRecordLikeDecl().
isObjCMethodDecl()
bool clang::comments::Sema::isObjCMethodDecl ()
Definition at line 857 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::isa(), and isFunctionDecl().
Referenced by checkFunctionDeclVerbatimLine().
isObjCPropertyDecl()
bool clang::comments::Sema::isObjCPropertyDecl ()
Definition at line 906 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, clang::Decl::getKind(), inspectThisDecl(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkReturnsCommand().
isObjCProtocolDecl()
bool clang::comments::Sema::isObjCProtocolDecl ()
Definition at line 1014 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), clang::isa(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkContainerDeclVerbatimLine(), and isRecordLikeDecl().
isRecordLikeDecl()
bool clang::comments::Sema::isRecordLikeDecl ()
Definition at line 922 of file CommentSema.cpp.
References inspectThisDecl(), isClassOrStructDecl(), clang::comments::DeclInfo::IsFilled, isObjCInterfaceDecl(), isObjCProtocolDecl(), and isUnionDecl().
Referenced by checkContainerDecl().
isTemplateOrSpecialization()
bool clang::comments::Sema::isTemplateOrSpecialization ()
Definition at line 914 of file CommentSema.cpp.
References clang::comments::DeclInfo::getTemplateKind(), inspectThisDecl(), clang::comments::DeclInfo::IsFilled, and clang::comments::DeclInfo::NotTemplate.
Referenced by actOnTParamCommandParamNameArg(), and actOnTParamCommandStart().
isUnionDecl()
bool clang::comments::Sema::isUnionDecl ()
Definition at line 931 of file CommentSema.cpp.
References clang::comments::DeclInfo::CurrentDecl, inspectThisDecl(), and clang::comments::DeclInfo::IsFilled.
Referenced by checkContainerDeclVerbatimLine(), and isRecordLikeDecl().
resolveParamCommandIndexes()
void clang::comments::Sema::resolveParamCommandIndexes (const FullComment * FC)
Resolve parameter names to parameter indexes in function declaration.
Emit diagnostics about unknown parametrs.
Definition at line 732 of file CommentSema.cpp.
References clang::comments::FullComment::child_begin(), clang::comments::FullComment::child_end(), correctTypoInParmVarReference(), clang::FixItHint::CreateReplacement(), clang::SourceRange::getBegin(), clang::NamedDecl::getIdentifier(), clang::comments::Comment::getLocation(), clang::comments::ParamCommandComment::getParamNameAsWritten(), clang::comments::ParamCommandComment::getParamNameRange(), getParamVars(), clang::comments::ParamCommandComment::hasParamName(), clang::comments::ParamCommandComment::InvalidParamIndex, isFunctionDecl(), resolveParmVarReference(), clang::comments::ParamCommandComment::setIsVarArgParam(), clang::comments::ParamCommandComment::setParamIndex(), and clang::comments::ParamCommandComment::VarArgParamIndex.
Referenced by actOnFullComment().
resolveParmVarReference()
unsigned clang::comments::Sema::resolveParmVarReference (StringRef Name, ArrayRef< const ParmVarDecl * > ParamVars)
Returns index of a function parameter with a given name.
Definition at line 1033 of file CommentSema.cpp.
References clang::IdentifierInfo::getName(), clang::comments::ParamCommandComment::InvalidParamIndex, isFunctionOrMethodVariadic(), and clang::comments::ParamCommandComment::VarArgParamIndex.
Referenced by resolveParamCommandIndexes().
resolveTParamReference()
bool clang::comments::Sema::resolveTParamReference (StringRef Name, const TemplateParameterList * TemplateParameters, SmallVectorImpl< unsigned > * Position)
Definition at line 1136 of file CommentSema.cpp.
Referenced by actOnTParamCommandParamNameArg().
setDecl()
void clang::comments::Sema::setDecl (const Decl * D)
Definition at line 36 of file CommentSema.cpp.
References clang::comments::DeclInfo::CommentDecl, and clang::comments::DeclInfo::IsFilled.
The documentation for this class was generated from the following files:
include/clang/AST/CommentSema.h
lib/AST/CommentSema.cpp