clang: clang::ento::SymbolExtent Class Reference
clang::ento::SymbolExtent Class Reference
SymbolExtent - Represents the extent (size in bytes) of a bounded region.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
SymbolExtent (SymbolID sym, const SubRegion *r)
const SubRegion * getRegion () const
QualType getType () const override
StringRef getKindStr () const override
Get a string representation of the kind of the region.
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &profile) override
Public Member Functions inherited from clang::ento::SymbolData
~SymbolData () override=default
SymbolID getSymbolID () const
unsigned computeComplexity () const override
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
symbol_iterator symbol_begin () const
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &profile, const SubRegion *R)
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymbolData
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymExpr
static symbol_iterator symbol_end ()
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Protected Member Functions inherited from clang::ento::SymbolData
SymbolData (Kind k, SymbolID sym)
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
SymbolExtent - Represents the extent (size in bytes) of a bounded region.
Clients should not ask the SymbolManager for a region's extent. Always use SubRegion::getExtent instead – the value returned may not be a symbol.
Definition at line 173 of file SymbolManager.h.
Constructor & Destructor Documentation
SymbolExtent()
clang::ento::SymbolExtent::SymbolExtent (SymbolID sym, const SubRegion * r) inline
Definition at line 177 of file SymbolManager.h.
Member Function Documentation
classof()
static bool clang::ento::SymbolExtent::classof (const SymExpr * SE) inline static
Definition at line 200 of file SymbolManager.h.
References clang::ento::SymExpr::getKind().
dumpToStream()
void SymbolExtent::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::SymExpr.
Definition at line 88 of file SymbolManager.cpp.
References getKindStr(), getRegion(), and clang::ento::SymbolData::getSymbolID().
getKindStr()
StringRef SymbolExtent::getKindStr () const override virtual
Get a string representation of the kind of the region.
Implements clang::ento::SymbolData.
Definition at line 40 of file SymbolManager.cpp.
Referenced by dumpToStream().
getRegion()
const SubRegion * clang::ento::SymbolExtent::getRegion () const inline
Definition at line 182 of file SymbolManager.h.
Referenced by dumpToStream().
getType()
QualType SymbolExtent::getType () const override virtual
Implements clang::ento::SymExpr.
Definition at line 320 of file SymbolManager.cpp.
References clang::ASTContext::getSizeType().
Profile() [1/2]
void clang::ento::SymbolExtent::Profile (llvm::FoldingSetNodeID & profile) inline override virtual
Implements clang::ento::SymExpr.
Definition at line 195 of file SymbolManager.h.
References Profile().
Profile() [2/2]
static void clang::ento::SymbolExtent::Profile (llvm::FoldingSetNodeID & profile, const SubRegion * R) inline static
Definition at line 190 of file SymbolManager.h.
Referenced by clang::ento::SymbolManager::getExtentSymbol(), and Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp