clang: clang::analyze_os_log::OSLogBufferItem Class Reference
clang::analyze_os_log::OSLogBufferItem Class Reference
An OSLogBufferItem represents a single item in the data written by a call to os_log() or os_trace().
#include "clang/AST/OSLog.h"
Public Types
enum Kind {
ScalarKind = 0 , CountKind , StringKind , PointerKind ,
ObjCObjKind , WideStringKind , ErrnoKind , MaskKind
}
enum { IsPrivate = 0x1 , IsPublic = 0x2 , IsSensitive = 0x4 | IsPrivate }
Public Member Functions
OSLogBufferItem (Kind kind, const Expr *expr, CharUnits size, unsigned flags, StringRef maskType=StringRef())
OSLogBufferItem (ASTContext &Ctx, CharUnits value, unsigned flags)
unsigned char getDescriptorByte () const
unsigned char getSizeByte () const
Kind getKind () const
bool getIsPrivate () const
const Expr * getExpr () const
CharUnits getConstValue () const
CharUnits size () const
StringRef getMaskType () const
Detailed Description
An OSLogBufferItem represents a single item in the data written by a call to os_log() or os_trace().
Definition at line 25 of file OSLog.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IsPrivate
IsPublic
IsSensitive
Definition at line 60 of file OSLog.h.
Kind
enum clang::analyze_os_log::OSLogBufferItem::Kind
Enumerator
ScalarKind
CountKind
StringKind
PointerKind
ObjCObjKind
WideStringKind
ErrnoKind
MaskKind
Definition at line 27 of file OSLog.h.
Constructor & Destructor Documentation
OSLogBufferItem() [1/2]
clang::analyze_os_log::OSLogBufferItem::OSLogBufferItem (Kind kind, const Expr * expr, CharUnits size, unsigned flags, StringRef maskType = StringRef()) inline
Definition at line 80 of file OSLog.h.
References IsPrivate, IsPublic, and IsSensitive.
OSLogBufferItem() [2/2]
clang::analyze_os_log::OSLogBufferItem::OSLogBufferItem (ASTContext & Ctx, CharUnits value, unsigned flags) inline
Definition at line 89 of file OSLog.h.
Member Function Documentation
getConstValue()
CharUnits clang::analyze_os_log::OSLogBufferItem::getConstValue () const inline
Definition at line 105 of file OSLog.h.
getDescriptorByte()
unsigned char clang::analyze_os_log::OSLogBufferItem::getDescriptorByte () const inline
Definition at line 93 of file OSLog.h.
References getKind().
getExpr()
const Expr * clang::analyze_os_log::OSLogBufferItem::getExpr () const inline
Definition at line 104 of file OSLog.h.
getIsPrivate()
bool clang::analyze_os_log::OSLogBufferItem::getIsPrivate () const inline
Definition at line 102 of file OSLog.h.
References IsPrivate.
Referenced by clang::analyze_os_log::OSLogBufferLayout::hasPrivateItems().
getKind()
Kind clang::analyze_os_log::OSLogBufferItem::getKind () const inline
Definition at line 101 of file OSLog.h.
Referenced by getDescriptorByte(), and clang::analyze_os_log::OSLogBufferLayout::hasNonScalarOrMask().
getMaskType()
StringRef clang::analyze_os_log::OSLogBufferItem::getMaskType () const inline
Definition at line 108 of file OSLog.h.
Referenced by clang::analyze_os_log::OSLogBufferLayout::hasNonScalarOrMask().
getSizeByte()
unsigned char clang::analyze_os_log::OSLogBufferItem::getSizeByte () const inline
Definition at line 99 of file OSLog.h.
References clang::CharUnits::getQuantity(), and size().
size()
CharUnits clang::analyze_os_log::OSLogBufferItem::size () const inline
Definition at line 106 of file OSLog.h.
Referenced by getSizeByte().
The documentation for this class was generated from the following file:
include/clang/AST/OSLog.h