clang: clang::CodeGen::ConstantInitBuilderTemplateBase< Traits > Class Template Reference
clang::CodeGen::ConstantInitBuilderTemplateBase< Traits > Class Template Reference
A template class designed to allow other frontends to easily customize the builder classes used by ConstantInitBuilder, and thus to extend the API to work with the abstractions they prefer.
#include "clang/CodeGen/ConstantInitBuilder.h"
Public Types
using InitBuilder = typename Traits::InitBuilder
using ArrayBuilder = typename Traits::ArrayBuilder
using StructBuilder = typename Traits::StructBuilder
Public Member Functions
ArrayBuilder beginArray (llvm::Type *eltTy=nullptr)
StructBuilder beginStruct (llvm::StructType *structTy=nullptr)
Protected Member Functions
ConstantInitBuilderTemplateBase (CodeGenModule &CGM)
Protected Member Functions inherited from clang::CodeGen::ConstantInitBuilderBase
ConstantInitBuilderBase (CodeGenModule &CGM)
~ConstantInitBuilderBase ()
Detailed Description
template<class Traits>
class clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >
A template class designed to allow other frontends to easily customize the builder classes used by ConstantInitBuilder, and thus to extend the API to work with the abstractions they prefer.
This would probably not be necessary if C++ just supported extension methods.
Definition at line 504 of file ConstantInitBuilder.h.
Member Typedef Documentation
ArrayBuilder
template<class Traits > using clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::ArrayBuilder = typename Traits::ArrayBuilder
Definition at line 511 of file ConstantInitBuilder.h.
InitBuilder
template<class Traits > using clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::InitBuilder = typename Traits::InitBuilder
Definition at line 510 of file ConstantInitBuilder.h.
StructBuilder
template<class Traits > using clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::StructBuilder = typename Traits::StructBuilder
Definition at line 512 of file ConstantInitBuilder.h.
Constructor & Destructor Documentation
ConstantInitBuilderTemplateBase()
template<class Traits > clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::ConstantInitBuilderTemplateBase (CodeGenModule & CGM) inline protected
Definition at line 506 of file ConstantInitBuilder.h.
Member Function Documentation
beginArray()
template<class Traits > ArrayBuilder clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::beginArray (llvm::Type * eltTy = nullptr) inline
Definition at line 514 of file ConstantInitBuilder.h.
beginStruct()
template<class Traits > StructBuilder clang::CodeGen::ConstantInitBuilderTemplateBase< Traits >::beginStruct (llvm::StructType * structTy = nullptr) inline
Definition at line 518 of file ConstantInitBuilder.h.
Referenced by buildBlockDescriptor(), buildGlobalBlock(), createGlobalStruct(), and clang::CodeGen::CodeGenVTables::GenerateConstructionVTable().
The documentation for this class was generated from the following file:
include/clang/CodeGen/ConstantInitBuilder.h