clang: clang::format::TokenAnalyzer Class Reference
clang::format::TokenAnalyzer Class Reference abstract
#include "/root/llvm-project/clang/lib/Format/TokenAnalyzer.h"
Public Member Functions
TokenAnalyzer (const Environment &Env, const FormatStyle &Style)
std::pair< tooling::Replacements, unsigned > process ()
Public Member Functions inherited from clang::format::UnwrappedLineConsumer
virtual ~UnwrappedLineConsumer ()
Protected Member Functions
virtual std::pair< tooling::Replacements, unsigned > analyze (TokenAnnotator &Annotator, SmallVectorImpl< AnnotatedLine * > &AnnotatedLines, FormatTokenLexer &Tokens)=0
void consumeUnwrappedLine (const UnwrappedLine &TheLine) override
void finishRun () override
Protected Attributes
FormatStyle Style
const Environment & Env
AffectedRangeManager AffectedRangeMgr
SmallVector< SmallVector< UnwrappedLine, 16 >, 2 > UnwrappedLines
encoding::Encoding Encoding
Detailed Description
Definition at line 80 of file TokenAnalyzer.h.
Constructor & Destructor Documentation
TokenAnalyzer()
clang::format::TokenAnalyzer::TokenAnalyzer (const Environment & Env, const FormatStyle & Style)
Definition at line 51 of file TokenAnalyzer.cpp.
References clang::format::encoding::Encoding_UTF8, and clang::format::getLanguageName().
Member Function Documentation
analyze()
virtual std::pair< tooling::Replacements, unsigned > clang::format::TokenAnalyzer::analyze (TokenAnnotator & Annotator, SmallVectorImpl< AnnotatedLine * > & AnnotatedLines, FormatTokenLexer & Tokens) protected pure virtual
Implemented in clang::format::JavaScriptImportSorter, clang::format::NamespaceEndCommentsFixer, and clang::format::UsingDeclarationsSorter.
Referenced by process().
consumeUnwrappedLine()
void clang::format::TokenAnalyzer::consumeUnwrappedLine (const UnwrappedLine & TheLine) override protected virtual
Implements clang::format::UnwrappedLineConsumer.
Definition at line 119 of file TokenAnalyzer.cpp.
References UnwrappedLines.
finishRun()
void clang::format::TokenAnalyzer::finishRun () override protected virtual
Implements clang::format::UnwrappedLineConsumer.
Definition at line 124 of file TokenAnalyzer.cpp.
References UnwrappedLines.
process()
std::pair< tooling::Replacements, unsigned > clang::format::TokenAnalyzer::process ()
Definition at line 65 of file TokenAnalyzer.cpp.
References analyze(), clang::format::TokenAnnotator::annotate(), Env, clang::format::Environment::getFileID(), clang::format::Environment::getFirstStartColumn(), clang::format::getFormattingLangOpts(), clang::format::FormatTokenLexer::getKeywords(), clang::format::Environment::getSourceManager(), clang::format::FormatTokenLexer::lex(), clang::Result, and UnwrappedLines.
Referenced by clang::format::fixNamespaceEndComments(), clang::format::internal::reformat(), clang::format::sortJavaScriptImports(), and clang::format::sortUsingDeclarations().
Member Data Documentation
AffectedRangeMgr
AffectedRangeManager clang::format::TokenAnalyzer::AffectedRangeMgr protected
Definition at line 100 of file TokenAnalyzer.h.
Referenced by clang::format::JavaScriptImportSorter::analyze(), clang::format::NamespaceEndCommentsFixer::analyze(), and clang::format::UsingDeclarationsSorter::analyze().
Encoding
encoding::Encoding clang::format::TokenAnalyzer::Encoding protected
Definition at line 102 of file TokenAnalyzer.h.
Env
const Environment& clang::format::TokenAnalyzer::Env protected
Definition at line 98 of file TokenAnalyzer.h.
Referenced by clang::format::JavaScriptImportSorter::analyze(), clang::format::NamespaceEndCommentsFixer::analyze(), clang::format::UsingDeclarationsSorter::analyze(), and process().
Style
FormatStyle clang::format::TokenAnalyzer::Style protected
Definition at line 96 of file TokenAnalyzer.h.
UnwrappedLines
SmallVector<SmallVector<UnwrappedLine, 16>, 2> clang::format::TokenAnalyzer::UnwrappedLines protected
Definition at line 101 of file TokenAnalyzer.h.
Referenced by consumeUnwrappedLine(), finishRun(), and process().
The documentation for this class was generated from the following files:
lib/Format/TokenAnalyzer.h
lib/Format/TokenAnalyzer.cpp