clang: clang::NestedNameSpecifier Class Reference
clang::NestedNameSpecifier Class Reference
Represents a C++ nested name specifier, such as "\::std::vector<int>::".
#include "clang/AST/NestedNameSpecifier.h"
Public Types
enum SpecifierKind {
Identifier , Namespace , NamespaceAlias , TypeSpec ,
TypeSpecWithTemplate , Global , Super
}
The kind of specifier that completes this nested name specifier.
Public Member Functions
NestedNameSpecifier & operator= (const NestedNameSpecifier &)=delete
NestedNameSpecifier * getPrefix () const
Return the prefix of this nested name specifier.
SpecifierKind getKind () const
Determine what kind of nested name specifier is stored.
IdentifierInfo * getAsIdentifier () const
Retrieve the identifier stored in this nested name specifier.
NamespaceDecl * getAsNamespace () const
Retrieve the namespace stored in this nested name specifier.
NamespaceAliasDecl * getAsNamespaceAlias () const
Retrieve the namespace alias stored in this nested name specifier.
CXXRecordDecl * getAsRecordDecl () const
Retrieve the record declaration stored in this nested name specifier.
const Type * getAsType () const
Retrieve the type stored in this nested name specifier.
NestedNameSpecifierDependence getDependence () const
bool isDependent () const
Whether this nested name specifier refers to a dependent type or not.
bool isInstantiationDependent () const
Whether this nested name specifier involves a template parameter.
bool containsUnexpandedParameterPack () const
Whether this nested-name-specifier contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this nested name specifier contains an error.
void print (raw_ostream &OS, const PrintingPolicy &Policy, bool ResolveTemplateArguments=false) const
Print this nested name specifier to the given output stream.
void Profile (llvm::FoldingSetNodeID &ID) const
void dump (const LangOptions &LO) const
Dump the nested name specifier to standard output to aid in debugging.
void dump () const
void dump (llvm::raw_ostream &OS) const
void dump (llvm::raw_ostream &OS, const LangOptions &LO) const
Static Public Member Functions
static NestedNameSpecifier * Create (const ASTContext &Context, NestedNameSpecifier *Prefix, IdentifierInfo *II)
Builds a specifier combining a prefix and an identifier.
static NestedNameSpecifier * Create (const ASTContext &Context, NestedNameSpecifier *Prefix, const NamespaceDecl *NS)
Builds a nested name specifier that names a namespace.
static NestedNameSpecifier * Create (const ASTContext &Context, NestedNameSpecifier *Prefix, NamespaceAliasDecl *Alias)
Builds a nested name specifier that names a namespace alias.
static NestedNameSpecifier * Create (const ASTContext &Context, NestedNameSpecifier *Prefix, bool Template, const Type *T)
Builds a nested name specifier that names a type.
static NestedNameSpecifier * Create (const ASTContext &Context, IdentifierInfo *II)
Builds a specifier that consists of just an identifier.
static NestedNameSpecifier * GlobalSpecifier (const ASTContext &Context)
Returns the nested name specifier representing the global scope.
static NestedNameSpecifier * SuperSpecifier (const ASTContext &Context, CXXRecordDecl *RD)
Returns the nested name specifier representing the __super scope for the given CXXRecordDecl.
Detailed Description
Represents a C++ nested name specifier, such as "\::std::vector<int>::".
C++ nested name specifiers are the prefixes to qualified names. For example, "foo::" in "foo::x" is a nested name specifier. Nested name specifiers are made up of a sequence of specifiers, each of which can be a namespace, type, identifier (for dependent names), decltype specifier, or the global specifier ('::'). The last two specifiers can only appear at the start of a nested-namespace-specifier.
Definition at line 50 of file NestedNameSpecifier.h.
Member Enumeration Documentation
SpecifierKind
enum clang::NestedNameSpecifier::SpecifierKind
The kind of specifier that completes this nested name specifier.
Enumerator
Identifier
An identifier, stored as an IdentifierInfo*.
Namespace
A namespace, stored as a NamespaceDecl*.
NamespaceAlias
A namespace alias, stored as a NamespaceAliasDecl*.
TypeSpec
A type, stored as a Type*.
TypeSpecWithTemplate
A type that was preceded by the 'template' keyword, stored as a Type*.
Global
The global specifier '::'. There is no stored value.
Super
Microsoft's '__super' specifier, stored as a CXXRecordDecl* of the class it appeared in.
Definition at line 79 of file NestedNameSpecifier.h.
Member Function Documentation
containsErrors()
bool NestedNameSpecifier::containsErrors () const
Whether this nested name specifier contains an error.
Definition at line 246 of file NestedNameSpecifier.cpp.
References getDependence().
Referenced by clang::Sema::DiagnoseUnknownTypeName().
containsUnexpandedParameterPack()
bool NestedNameSpecifier::containsUnexpandedParameterPack () const
Whether this nested-name-specifier contains an unexpanded parameter pack (for C++11 variadic templates).
Definition at line 242 of file NestedNameSpecifier.cpp.
References getDependence().
Referenced by clang::Sema::ActOnUsingDeclaration(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::Sema::containsUnexpandedParameterPacks(), and clang::Sema::DiagnoseUnexpandedParameterPack().
Create() [1/5]
NestedNameSpecifier * NestedNameSpecifier::Create (const ASTContext & Context, IdentifierInfo * II) static
Builds a specifier that consists of just an identifier.
The nested-name-specifier is assumed to be dependent, but has no prefix because the prefix is implied by something outside of the nested name specifier, e.g., in "x->Base::f", the "x" has a dependent type.
Definition at line 116 of file NestedNameSpecifier.cpp.
Create() [2/5]
NestedNameSpecifier * NestedNameSpecifier::Create (const ASTContext & Context, NestedNameSpecifier * Prefix, bool Template, const Type * T) static
Builds a nested name specifier that names a type.
Definition at line 104 of file NestedNameSpecifier.cpp.
Create() [3/5]
NestedNameSpecifier * NestedNameSpecifier::Create (const ASTContext & Context, NestedNameSpecifier * Prefix, const NamespaceDecl * NS) static
Builds a nested name specifier that names a namespace.
Definition at line 72 of file NestedNameSpecifier.cpp.
References getAsIdentifier(), and getAsType().
Create() [4/5]
NestedNameSpecifier * NestedNameSpecifier::Create (const ASTContext & Context, NestedNameSpecifier * Prefix, IdentifierInfo * II) static
Builds a specifier combining a prefix and an identifier.
The prefix must be dependent, since nested name specifiers referencing an identifier are only permitted when the identifier cannot be resolved.
Definition at line 59 of file NestedNameSpecifier.cpp.
References isDependent().
Referenced by clang::Sema::ActOnMSVCUnknownTypeName(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), buildSingleCopyAssignRecursively(), clang::Sema::CheckComparisonCategoryType(), clang::TypeName::createNestedNameSpecifier(), clang::TypeName::createNestedNameSpecifier(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::NestedNameSpecifierLocBuilder::Extend(), clang::ASTContext::getCanonicalNestedNameSpecifier(), getRequiredQualification(), clang::ASTImporter::Import(), lookupPromiseType(), clang::serialization::ReadDispatcher< RefQualifierKind >::read(), recoverFromMSUnqualifiedLookup(), recoverFromTypeInKnownDependentBase(), and synthesizeCurrentNestedNameSpecifier().
Create() [5/5]
NestedNameSpecifier * NestedNameSpecifier::Create (const ASTContext & Context, NestedNameSpecifier * Prefix, NamespaceAliasDecl * Alias) static
Builds a nested name specifier that names a namespace alias.
Definition at line 88 of file NestedNameSpecifier.cpp.
References getAsIdentifier(), and getAsType().
dump() [1/4]
LLVM_DUMP_METHOD void NestedNameSpecifier::dump () const
Definition at line 341 of file NestedNameSpecifier.cpp.
References dump().
Referenced by dump(), dump(), and dump().
dump() [2/4]
LLVM_DUMP_METHOD void NestedNameSpecifier::dump (const LangOptions & LO) const
Dump the nested name specifier to standard output to aid in debugging.
Definition at line 337 of file NestedNameSpecifier.cpp.
References dump().
dump() [3/4]
LLVM_DUMP_METHOD void NestedNameSpecifier::dump (llvm::raw_ostream & OS) const
Definition at line 343 of file NestedNameSpecifier.cpp.
References dump().
dump() [4/4]
LLVM_DUMP_METHOD void NestedNameSpecifier::dump (llvm::raw_ostream & OS, const LangOptions & LO) const
Definition at line 348 of file NestedNameSpecifier.cpp.
References print().
getAsIdentifier()
IdentifierInfo * clang::NestedNameSpecifier::getAsIdentifier () const inline
Retrieve the identifier stored in this nested name specifier.
Definition at line 176 of file NestedNameSpecifier.h.
Referenced by clang::ODRHash::AddNestedNameSpecifier(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), Create(), Create(), clang::Sema::FindFirstQualifierInScope(), clang::ASTContext::getCanonicalNestedNameSpecifier(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), isSameQualifier(), IsStructurallyEquivalent(), print(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getAsNamespace()
NamespaceDecl * NestedNameSpecifier::getAsNamespace () const
Retrieve the namespace stored in this nested name specifier.
Definition at line 169 of file NestedNameSpecifier.cpp.
Referenced by clang::ODRHash::AddNestedNameSpecifier(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::Sema::computeDeclContext(), clang::ASTContext::getCanonicalNestedNameSpecifier(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), IsStructurallyEquivalent(), print(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::tooling::RecursiveSymbolVisitor< T >::TraverseNestedNameSpecifierLoc().
getAsNamespaceAlias()
NamespaceAliasDecl * NestedNameSpecifier::getAsNamespaceAlias () const
Retrieve the namespace alias stored in this nested name specifier.
Definition at line 177 of file NestedNameSpecifier.cpp.
Referenced by clang::ODRHash::AddNestedNameSpecifier(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::Sema::computeDeclContext(), clang::ASTContext::getCanonicalNestedNameSpecifier(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), IsStructurallyEquivalent(), print(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getAsRecordDecl()
CXXRecordDecl * NestedNameSpecifier::getAsRecordDecl () const
Retrieve the record declaration stored in this nested name specifier.
Definition at line 185 of file NestedNameSpecifier.cpp.
References clang::Type::getAsCXXRecordDecl(), and getAsType().
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::Sema::BuildUsingShadowDecl(), clang::Sema::computeDeclContext(), clang::ConstructorUsingShadowDecl::getNominatedBaseClass(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), clang::Sema::LookupParsedName(), print(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getAsType()
const Type * clang::NestedNameSpecifier::getAsType () const inline
Retrieve the type stored in this nested name specifier.
Definition at line 196 of file NestedNameSpecifier.h.
Referenced by clang::TypoCorrectionConsumer::addNamespaces(), clang::ODRHash::AddNestedNameSpecifier(), clang::Sema::CheckInheritingConstructorUsingDecl(), clang::Sema::CheckTypenameType(), clang::Sema::CodeCompleteQualifiedId(), clang::Sema::computeDeclContext(), Create(), Create(), clang::Sema::DiagnoseEmptyLookup(), clang::Sema::diagnoseQualifiedDeclaration(), getAsRecordDecl(), clang::ASTContext::getCanonicalNestedNameSpecifier(), clang::Sema::getCurrentInstantiationOf(), getDependence(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), clang::UnresolvedMemberExpr::getNamingClass(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), isEnableIf(), clang::Sema::isMicrosoftMissingTypename(), isSameQualifier(), IsStructurallyEquivalent(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), MarkUsedTemplateParameters(), clang::Sema::MatchTemplateParametersToScopeSpecifier(), print(), and ScopeSpecifierHasTemplateId().
getDependence()
NestedNameSpecifierDependence NestedNameSpecifier::getDependence () const
Definition at line 201 of file NestedNameSpecifier.cpp.
References clang::CXXRecordDecl::bases(), getAsType(), getDependence(), getKind(), getPrefix(), Global, Identifier, Namespace, NamespaceAlias, Super, clang::toNestedNameSpecifierDependendence(), TypeSpec, and TypeSpecWithTemplate.
Referenced by containsErrors(), containsUnexpandedParameterPack(), getDependence(), isDependent(), and isInstantiationDependent().
getKind()
NestedNameSpecifier::SpecifierKind NestedNameSpecifier::getKind () const
Determine what kind of nested name specifier is stored.
Definition at line 143 of file NestedNameSpecifier.cpp.
References Global, Identifier, clang::isa(), Namespace, NamespaceAlias, Super, TypeSpec, and TypeSpecWithTemplate.
Referenced by clang::ODRHash::AddNestedNameSpecifier(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::Sema::checkLiteralOperatorId(), clang::Sema::computeDeclContext(), clang::Sema::FindFirstQualifierInScope(), clang::ASTContext::getCanonicalNestedNameSpecifier(), getDependence(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), isFullyQualified(), clang::Sema::isMicrosoftMissingTypename(), isSameQualifier(), IsStructurallyEquivalent(), clang::Sema::LookupParsedName(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), print(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::serialization::WriteDispatcher< NamespaceAliasDecl * >::write().
getPrefix()
NestedNameSpecifier * clang::NestedNameSpecifier::getPrefix () const inline
Return the prefix of this nested name specifier.
The prefix contains all of the parts of the nested name specifier that preced this current specifier. For example, for a nested name specifier that represents "foo::bar::", the current specifier will contain "bar::" and the prefix will contain "foo::".
Definition at line 169 of file NestedNameSpecifier.h.
Referenced by clang::ODRHash::AddNestedNameSpecifier(), clang::Sema::FindFirstQualifierInScope(), clang::ASTContext::getCanonicalNestedNameSpecifier(), getDependence(), clang::Sema::getDestructorName(), GetFullTypeForDeclarator(), clang::Sema::getInheritingConstructorName(), getNestedNameSpecifierIdentifiers(), clang::ASTImporter::Import(), isFullyQualified(), isSameQualifier(), IsStructurallyEquivalent(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), MarkUsedTemplateParameters(), print(), ScopeSpecifierHasTemplateId(), warnAboutRedundantParens(), and clang::serialization::WriteDispatcher< const NamedDecl * >::write().
GlobalSpecifier()
NestedNameSpecifier * NestedNameSpecifier::GlobalSpecifier (const ASTContext & Context) static
Returns the nested name specifier representing the global scope.
Definition at line 126 of file NestedNameSpecifier.cpp.
Referenced by clang::TypeName::createNestedNameSpecifierForScopeOf(), clang::TypeName::createOuterNNS(), clang::ASTImporter::Import(), clang::NestedNameSpecifierLocBuilder::MakeGlobal(), and synthesizeCurrentNestedNameSpecifier().
isDependent()
bool NestedNameSpecifier::isDependent () const
Whether this nested name specifier refers to a dependent type or not.
Definition at line 234 of file NestedNameSpecifier.cpp.
References getDependence().
Referenced by clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::CheckTypenameType(), clang::Sema::CheckUsingDeclRedeclaration(), clang::Sema::CodeCompleteQualifiedId(), clang::Sema::computeDeclContext(), clang::MemberExpr::Create(), Create(), clang::Sema::getCurrentInstantiationOf(), clang::ASTContext::getDependentTemplateName(), clang::ASTContext::getDependentTemplateName(), clang::ASTContext::getDependentTemplateSpecializationType(), clang::Sema::isDependentScopeSpecifier(), and clang::TreeTransform< Derived >::RebuildDependentNameType().
isInstantiationDependent()
bool NestedNameSpecifier::isInstantiationDependent () const
Whether this nested name specifier involves a template parameter.
Definition at line 238 of file NestedNameSpecifier.cpp.
References getDependence().
Referenced by clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), and clang::MemberExpr::Create().
operator=()
NestedNameSpecifier & clang::NestedNameSpecifier::operator= (const NestedNameSpecifier &) delete
print()
void NestedNameSpecifier::print (raw_ostream & OS, const PrintingPolicy & Policy, bool ResolveTemplateArguments = false) const
Print this nested name specifier to the given output stream.
If ResolveTemplateArguments is true, we'll print actual types, e.g. ns::SomeTemplate<int, MyClass> instead of ns::SomeTemplate<Container::value_type, T>.
Definition at line 252 of file NestedNameSpecifier.cpp.
References getAsIdentifier(), getAsNamespace(), getAsNamespaceAlias(), getAsRecordDecl(), getAsType(), getKind(), clang::IdentifierInfo::getName(), clang::NamedDecl::getName(), getPrefix(), Global, Identifier, Namespace, NamespaceAlias, print(), clang::QualType::print(), clang::printTemplateArgumentList(), Super, clang::PrintingPolicy::SuppressScope, TypeSpec, and TypeSpecWithTemplate.
Referenced by dump(), clang::FormatASTNodeDiagnosticArgument(), MaybeAddOverrideCalls(), print(), clang::TypeConstraint::print(), PrintMapper(), printQualifier(), clang::TextNodeDumper::VisitUnresolvedUsingTypenameDecl(), clang::TextNodeDumper::VisitUnresolvedUsingValueDecl(), and clang::TextNodeDumper::VisitUsingDecl().
Profile()
void clang::NestedNameSpecifier::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 228 of file NestedNameSpecifier.h.
SuperSpecifier()
NestedNameSpecifier * NestedNameSpecifier::SuperSpecifier (const ASTContext & Context, CXXRecordDecl * RD) static
Returns the nested name specifier representing the __super scope for the given CXXRecordDecl.
Definition at line 134 of file NestedNameSpecifier.cpp.
Referenced by clang::ASTImporter::Import(), and clang::NestedNameSpecifierLocBuilder::MakeSuper().
The documentation for this class was generated from the following files:
include/clang/AST/NestedNameSpecifier.h
lib/AST/NestedNameSpecifier.cpp