clang: clang::ento::SVal Class Reference
clang::ento::SVal Class Reference
SVal - This represents a symbolic expression, which can be either an L-value or an R-value.
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
Public Types
enum BaseKind
enum { BaseBits = 2 , BaseMask = 0b11 }
Public Member Functions
SVal ()=default
template<typename T >
T castAs () const
Convert to the specified SVal type, asserting that this SVal is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified SVal type, returning None if this SVal is not of the desired type.
unsigned getRawKind () const
BaseKind getBaseKind () const
unsigned getSubKind () const
void Profile (llvm::FoldingSetNodeID &ID) const
bool operator== (const SVal &R) const
bool operator!= (const SVal &R) const
bool isUnknown () const
bool isUndef () const
bool isUnknownOrUndef () const
bool isValid () const
bool isConstant () const
bool isConstant (int I) const
bool isZeroConstant () const
bool hasConjuredSymbol () const
hasConjuredSymbol - If this SVal wraps a conjured symbol, return true;
const FunctionDecl * getAsFunctionDecl () const
getAsFunctionDecl - If this SVal is a MemRegionVal and wraps a CodeTextRegion wrapping a FunctionDecl, return that FunctionDecl.
SymbolRef getAsLocSymbol (bool IncludeBaseRegions=false) const
If this SVal is a location and wraps a symbol, return that SymbolRef.
SymbolRef getLocSymbolInBase () const
Get the symbol in the SVal or its base region.
SymbolRef getAsSymbol (bool IncludeBaseRegions=false) const
If this SVal wraps a symbol return that SymbolRef.
const MemRegion * getAsRegion () const
void printJson (raw_ostream &Out, bool AddQuotes) const
printJson - Pretty-prints in JSON format.
void dumpToStream (raw_ostream &OS) const
void dump () const
SymExpr::symbol_iterator symbol_begin () const
SymExpr::symbol_iterator symbol_end () const
Protected Member Functions
SVal (const void *d, bool isLoc, unsigned ValKind)
SVal (BaseKind k, const void *D=nullptr)
Protected Attributes
const void * Data = nullptr
unsigned Kind = 0
The lowest 2 bits are a BaseKind (0 – 3).
Detailed Description
SVal - This represents a symbolic expression, which can be either an L-value or an R-value.
Definition at line 75 of file SVals.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
BaseBits
BaseMask
Definition at line 83 of file SVals.h.
BaseKind
enum clang::ento::SVal::BaseKind
Definition at line 77 of file SVals.h.
Constructor & Destructor Documentation
SVal() [1/3]
clang::ento::SVal::SVal (const void * d, bool isLoc, unsigned ValKind) inline explicit protected
Definition at line 92 of file SVals.h.
SVal() [2/3]
clang::ento::SVal::SVal (BaseKind k, const void * D = nullptr) inline explicit protected
Definition at line 95 of file SVals.h.
SVal() [3/3]
clang::ento::SVal::SVal () explicit default
Member Function Documentation
castAs()
template<typename T > T clang::ento::SVal::castAs () const inline
Convert to the specified SVal type, asserting that this SVal is of the desired type.
Definition at line 103 of file SVals.h.
Referenced by addInstanceOfTransition(), addValue(), clang::ento::ProgramState::assume(), clang::ento::ProgramState::assume(), clang::ento::SimpleConstraintManager::assume(), assumeCondition(), clang::ento::ProgramState::assumeInBound(), clang::ento::ProgramState::assumeInclusiveRange(), clang::ento::ProgramState::assumeInclusiveRange(), clang::ento::ProgramState::bindDefaultInitial(), clang::ento::ProgramState::bindDefaultZero(), clang::ento::ExprEngine::bindReturnValue(), checkElementNonNil(), clang::ento::SValBuilder::convertToArrayIndex(), clang::ento::CoreEngine::dispatchWorkItem(), doRearrangeUnchecked(), clang::ento::ExprEngine::evalBinOp(), clang::ento::SValBuilder::evalBinOp(), clang::ento::SValBuilder::evalCast(), evalComparison(), clang::ento::SValBuilder::evalEQ(), clang::ento::SValBuilder::evalIntegralCast(), clang::ento::ExprEngine::evalLoad(), getArgumentValueString(), clang::ento::getDynamicElementCount(), clang::ento::StoreManager::getLValueElement(), isArrayIndexOutOfBounds(), isSelfVar(), IsZeroByteAllocation(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::ento::ExprEngine::processSwitch(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), and clang::ento::ExprEngine::VisitObjCMessage().
dump()
LLVM_DUMP_METHOD void SVal::dump () const
Definition at line 263 of file SVals.cpp.
dumpToStream()
void SVal::dumpToStream (raw_ostream & OS) const
Definition at line 274 of file SVals.cpp.
getAs()
template<typename T > Optional< T > clang::ento::SVal::getAs () const inline
Convert to the specified SVal type, returning None if this SVal is not of the desired type.
Definition at line 111 of file SVals.h.
References clang::None.
Referenced by clang::ento::iterator::advancePosition(), clang::ento::SimpleConstraintManager::assume(), assumeCollectionNonEmpty(), clang::ento::ProgramState::assumeInclusiveRange(), clang::ento::ProgramState::assumeInclusiveRange(), clang::ento::iterator::assumeNoOverflow(), clang::ento::ProgramState::bindLoc(), checkCollectionNonNil(), checkValueAtLValForInvariantViolation(), collectSubRegionBindings(), conjureOffsetSymbolOnLocation(), clang::ento::SValBuilder::convertToArrayIndex(), dereference(), clang::ento::CoreEngine::dispatchWorkItem(), clang::ento::SValBuilder::evalBinOp(), clang::ento::retaincountchecker::RetainCountChecker::evalCall(), clang::ento::SValBuilder::evalCast(), evalComparison(), clang::ento::ExprEngine::evalLoad(), clang::ento::ElementRegion::getAsArrayOffset(), getAsFunctionDecl(), getAsPointeeSymbol(), getAsRegion(), getAsSymbol(), clang::ento::CXXInstanceCall::getCXXThisVal(), clang::ento::MemRegion::getDescriptiveName(), getFuchsiaHandleSymbols(), clang::ento::ExprEngine::getInitialState(), clang::ento::iterator::getIteratorPosition(), getLocSymbolInBase(), clang::ento::ProgramState::getLValue(), clang::ento::StoreManager::getLValueElement(), clang::ento::StackHintGeneratorForSymbol::getMessage(), getReceiverNullability(), getSimplifiedOffsets(), getValue(), hasConjuredSymbol(), hasVisibleUpdate(), isInvariantBreak(), isSelfVar(), clang::ento::ProgramState::killBinding(), clang::ento::SValBuilder::makeSymExprValNN(), parameterTypeFromSVal(), populateObjCForDestinationSet(), clang::ento::ExprEngine::processIndirectGoto(), clang::ento::ExprEngine::processSwitch(), clang::ento::ScanReachableSymbols::scan(), clang::ento::iterator::setIteratorPosition(), updateOutParameters(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::SValExplainer::VisitElementRegion(), and clang::ento::TrackConstraintBRVisitor::VisitNode().
getAsFunctionDecl()
const FunctionDecl * SVal::getAsFunctionDecl () const
getAsFunctionDecl - If this SVal is a MemRegionVal and wraps a CodeTextRegion wrapping a FunctionDecl, return that FunctionDecl.
Otherwise return 0.
Definition at line 63 of file SVals.cpp.
References clang::ento::MemRegion::getAs(), getAs(), and X().
Referenced by clang::ento::CheckerContext::getCalleeDecl(), clang::ento::CXXInstanceCall::getDecl(), and clang::ento::SimpleFunctionCall::getDecl().
getAsLocSymbol()
SymbolRef SVal::getAsLocSymbol (bool IncludeBaseRegions = false) const
If this SVal is a location and wraps a symbol, return that SymbolRef.
If this SVal is a location (subclasses Loc) and wraps a symbol, return that SymbolRef.
Otherwise return 0.
Casts are ignored during lookup.
Parameters
IncludeBaseRegions The boolean that controls whether the search should continue to the base regions if the region is not symbolic.
Otherwise return 0.
Implicit casts (ex: void* -> char*) can turn Symbolic region into Element region. If that is the case, gets the underlining region. When IncludeBaseRegions is set to true and the SubRegion is non-symbolic, the first symbolic parent region is returned.
Definition at line 85 of file SVals.cpp.
References getAsRegion().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostCall(), getAsSymbol(), clang::ento::StackHintGeneratorForSymbol::getMessage(), clang::ento::StoreManager::FindUniqueBinding::HandleBinding(), and updateOutParameters().
getAsRegion()
const MemRegion * SVal::getAsRegion () const
Definition at line 129 of file SVals.cpp.
References getAs(), and X().
Referenced by addCastTransition(), addInstanceOfTransition(), clang::ento::ProgramState::bindLoc(), clang::ento::retaincountchecker::RetainCountChecker::checkBind(), clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::SValBuilder::evalCast(), clang::ento::StoreManager::evalDerivedToBase(), getAsLocSymbol(), clang::ento::BlockCall::getBlockRegion(), clang::ento::CallEventManager::getCaller(), getConstructedRegion(), clang::ento::getDynamicSizeWithOffset(), clang::ento::CXXInstanceCall::getExtraInvalidatedValues(), clang::ento::ObjCMethodCall::getExtraInvalidatedValues(), clang::ento::iterator::getIteratorPosition(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::ento::ExprEngine::ProcessInitializer(), REGISTER_MAP_WITH_PROGRAMSTATE(), clang::ento::iterator::setIteratorPosition(), updateOutParameters(), clang::ento::ExprEngine::VisitCXXNewExpr(), and clang::ento::ExprEngine::VisitMemberExpr().
getAsSymbol()
SymbolRef SVal::getAsSymbol (bool IncludeBaseRegions = false) const
If this SVal wraps a symbol return that SymbolRef.
Otherwise, return 0.
Casts are ignored during lookup.
Parameters
IncludeBaseRegions The boolean that controls whether the search should continue to the base regions if the region is not symbolic.
Definition at line 121 of file SVals.cpp.
References getAs(), getAsLocSymbol(), and X().
Referenced by addSelfFlag(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), clang::ento::SValBuilder::evalCast(), clang::ento::SValBuilder::evalIntegralCast(), getFuchsiaHandleSymbols(), clang::ento::iterator::getIteratorPosition(), hasFlag(), clang::ento::SValBuilder::makeSymExprValNN(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), REGISTER_MAP_WITH_PROGRAMSTATE(), clang::ento::ScanReachableSymbols::scan(), setFlag(), clang::ento::iterator::setIteratorPosition(), symbol_begin(), and tryRearrange().
getBaseKind()
BaseKind clang::ento::SVal::getBaseKind () const inline
Definition at line 118 of file SVals.h.
References BaseMask.
getLocSymbolInBase()
SymbolRef SVal::getLocSymbolInBase () const
Get the symbol in the SVal or its base region.
Definition at line 97 of file SVals.cpp.
References getAs(), and X().
getRawKind()
unsigned clang::ento::SVal::getRawKind () const inline
Definition at line 117 of file SVals.h.
References Kind.
Referenced by isUndef(), isUnknown(), isUnknownOrUndef(), isValid(), operator==(), and Profile().
getSubKind()
unsigned clang::ento::SVal::getSubKind () const inline
Definition at line 119 of file SVals.h.
References BaseBits.
hasConjuredSymbol()
bool SVal::hasConjuredSymbol () const
hasConjuredSymbol - If this SVal wraps a conjured symbol, return true;
Definition at line 44 of file SVals.cpp.
References getAs().
isConstant() [1/2]
bool SVal::isConstant () const
Definition at line 200 of file SVals.cpp.
Referenced by clang::ento::SValBuilder::evalCast(), and clang::ento::ExprEngine::VisitCast().
isConstant() [2/2]
bool SVal::isConstant (int I) const
Definition at line 204 of file SVals.cpp.
isUndef()
bool clang::ento::SVal::isUndef () const inline
Definition at line 140 of file SVals.h.
References getRawKind().
Referenced by clang::ento::SValBuilder::evalBinOp(), clang::ento::ExprEngine::evalLoad(), clang::ento::ExprEngine::evalStore(), getArgumentValueString(), clang::ento::ExprEngine::processSwitch(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ento::ExprEngine::VisitObjCMessage(), and wasRegionOfInterestModifiedAt().
isUnknown()
bool clang::ento::SVal::isUnknown () const inline
Definition at line 136 of file SVals.h.
References getRawKind().
Referenced by addParameterValuesToBindings(), clang::ento::ProgramState::assume(), clang::ento::ProgramState::assume(), assumeCondition(), clang::ento::ProgramState::assumeInBound(), clang::ento::ProgramState::assumeInclusiveRange(), clang::ento::ProgramState::assumeInclusiveRange(), conjureOffsetSymbolOnLocation(), clang::ento::SValBuilder::evalBinOp(), clang::ento::retaincountchecker::RetainCountChecker::evalCall(), clang::ento::AnyCXXConstructorCall::getInitialStackFrameContents(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ento::ExprEngine::handleLValueBitCast(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXNewExpr(), and clang::ento::ExprEngine::VisitDeclStmt().
isUnknownOrUndef()
bool clang::ento::SVal::isUnknownOrUndef () const inline
Definition at line 144 of file SVals.h.
References getRawKind().
Referenced by addValue(), clang::ento::ProgramState::assumeInBound(), clang::ento::SValBuilder::convertToArrayIndex(), clang::ento::SValBuilder::evalCast(), evalComparison(), clang::ento::CXXInstanceCall::getCXXThisVal(), clang::ento::ExprEngine::ProcessInitializer(), and clang::ento::ExprEngine::VisitIncrementDecrementOperator().
isValid()
bool clang::ento::SVal::isValid () const inline
Definition at line 148 of file SVals.h.
References getRawKind().
Referenced by clang::ento::ExprEngine::evalBinOp(), clang::ento::ExprEngine::evalComplement(), clang::ento::ExprEngine::evalLoad(), clang::ento::ExprEngine::evalMinus(), and clang::ento::ObjCMethodCall::getReceiverSVal().
isZeroConstant()
bool SVal::isZeroConstant () const
Definition at line 212 of file SVals.cpp.
Referenced by clang::ento::SValBuilder::evalCast(), and clang::ento::ExprEngine::VisitCast().
operator!=()
bool clang::ento::SVal::operator!= (const SVal & R) const inline
Definition at line 132 of file SVals.h.
operator==()
bool clang::ento::SVal::operator== (const SVal & R) const inline
Definition at line 128 of file SVals.h.
References Data, and getRawKind().
printJson()
void SVal::printJson (raw_ostream & Out, bool AddQuotes) const
printJson - Pretty-prints in JSON format.
Definition at line 265 of file SVals.cpp.
References clang::JsonFormat().
Profile()
void clang::ento::SVal::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 123 of file SVals.h.
References Data, and getRawKind().
Referenced by clang::ento::BasicValueFactory::getPersistentSValPair().
symbol_begin()
SymExpr::symbol_iterator clang::ento::SVal::symbol_begin () const inline
Definition at line 193 of file SVals.h.
References getAsSymbol(), and clang::ento::SymExpr::symbol_begin().
Referenced by clang::ento::SymbolReaper::markElementIndicesLive().
symbol_end()
SymExpr::symbol_iterator clang::ento::SVal::symbol_end () const inline
Definition at line 201 of file SVals.h.
References clang::ento::SymExpr::symbol_end().
Referenced by clang::ento::SymbolReaper::markElementIndicesLive().
Member Data Documentation
Data
const void* clang::ento::SVal::Data = nullptr protected
Definition at line 86 of file SVals.h.
Referenced by clang::ento::nonloc::LazyCompoundVal::getCVData(), clang::ento::loc::GotoLabel::getLabel(), clang::ento::nonloc::LocAsInteger::getLoc(), clang::ento::nonloc::LocAsInteger::getNumBits(), clang::ento::nonloc::LocAsInteger::getPersistentLoc(), clang::ento::nonloc::PointerToMember::getPTMData(), clang::ento::loc::MemRegionVal::getRegion(), clang::ento::nonloc::SymbolVal::getSymbol(), clang::ento::loc::ConcreteInt::getValue(), clang::ento::nonloc::CompoundVal::getValue(), clang::ento::nonloc::ConcreteInt::getValue(), operator==(), and Profile().
Kind
unsigned clang::ento::SVal::Kind = 0 protected
The lowest 2 bits are a BaseKind (0 – 3).
The higher bits are an unsigned "kind" value.
Definition at line 90 of file SVals.h.
Referenced by getRawKind().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h
lib/StaticAnalyzer/Core/SVals.cpp