clang: clang::FunctionDecl::DefaultedFunctionInfo Class Reference
clang::FunctionDecl::DefaultedFunctionInfo Class Reference final
Stashed information about a defaulted function definition whose body has not yet been lazily generated.
#include "clang/AST/Decl.h"
Public Member Functions
ArrayRef< DeclAccessPair > getUnqualifiedLookups () const
Get the unqualified lookup results that should be used in this defaulted function definition.
Static Public Member Functions
static DefaultedFunctionInfo * Create (ASTContext &Context, ArrayRef< DeclAccessPair > Lookups)
Detailed Description
Stashed information about a defaulted function definition whose body has not yet been lazily generated.
Definition at line 1837 of file Decl.h.
Member Function Documentation
Create()
FunctionDecl::DefaultedFunctionInfo * FunctionDecl::DefaultedFunctionInfo::Create (ASTContext & Context, ArrayRef< DeclAccessPair > Lookups) static
Definition at line 2873 of file Decl.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::Sema::CheckExplicitlyDefaultedComparison(), clang::TemplateDeclInstantiator::SubstDefaultedFunction(), and clang::ASTDeclReader::VisitFunctionDecl().
getUnqualifiedLookups()
ArrayRef< DeclAccessPair > clang::FunctionDecl::DefaultedFunctionInfo::getUnqualifiedLookups () const inline
Get the unqualified lookup results that should be used in this defaulted function definition.
Definition at line 1847 of file Decl.h.
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp