clang: clang::serialization::BasicWriterBase< Impl > Class Template Reference
clang::serialization::BasicWriterBase< Impl > Class Template Reference
#include "clang/AST/AbstractBasicWriter.h"
Public Member Functions
ASTContext & getASTContext ()
Impl & asImpl ()
void writeAPValue (const APValue &node)
void writeAPValueKind (APValue::ValueKind value)
void writeArraySizeModifier (ArrayType::ArraySizeModifier value)
void writeAttrKind (attr::Kind value)
void writeAutoTypeKeyword (AutoTypeKeyword value)
void writeBuiltinTypeKind (BuiltinType::Kind value)
void writeCXXRecordDeclRef (const CXXRecordDecl *value)
void writeCallingConv (CallingConv value)
void writeConceptDeclRef (const ConceptDecl *value)
void writeDeclarationName (DeclarationName node)
void writeDeclarationNameKind (DeclarationName::NameKind value)
void writeElaboratedTypeKeyword (ElaboratedTypeKeyword value)
void writeExprRef (const Expr *value)
void writeFunctionDeclRef (const FunctionDecl *value)
void writeNamedDeclRef (const NamedDecl *value)
void writeNamespaceAliasDeclRef (const NamespaceAliasDecl *value)
void writeNamespaceDeclRef (const NamespaceDecl *value)
void writeNestedNameSpecifierKind (NestedNameSpecifier::SpecifierKind value)
void writeObjCProtocolDeclRef (const ObjCProtocolDecl *value)
void writeObjCTypeParamDeclRef (const ObjCTypeParamDecl *value)
void writeOverloadedOperatorKind (OverloadedOperatorKind value)
void writeRefQualifierKind (RefQualifierKind value)
void writeTagDeclRef (const TagDecl *value)
void writeTemplateArgument (TemplateArgument node)
void writeTemplateArgumentKind (TemplateArgument::ArgKind value)
void writeTemplateDeclRef (const TemplateDecl *value)
void writeTemplateName (TemplateName node)
void writeTemplateNameKind (TemplateName::NameKind value)
void writeTemplateTemplateParmDeclRef (const TemplateTemplateParmDecl *value)
void writeTemplateTypeParmDeclRef (const TemplateTypeParmDecl *value)
void writeUnaryTypeTransformKind (UnaryTransformType::UTTKind value)
void writeValueDeclRef (const ValueDecl *value)
void writeVectorKind (VectorType::VectorKind value)
Protected Member Functions
BasicWriterBase (ASTContext &ctx)
Detailed Description
template<class Impl>
class clang::serialization::BasicWriterBase< Impl >
Definition at line 735 of file AbstractBasicWriter.h.
Constructor & Destructor Documentation
BasicWriterBase()
template<class Impl > clang::serialization::BasicWriterBase< Impl >::BasicWriterBase (ASTContext & ctx) inline protected
Definition at line 738 of file AbstractBasicWriter.h.
Member Function Documentation
asImpl()
template<class Impl > Impl & clang::serialization::BasicWriterBase< Impl >::asImpl () inline
Definition at line 741 of file AbstractBasicWriter.h.
Referenced by clang::serialization::DataStreamBasicWriter< Impl >::find(), clang::serialization::WriteDispatcher< FunctionDecl * >::write(), clang::serialization::WriteDispatcher< llvm::FixedPointSemantics >::write(), clang::serialization::WriteDispatcher< NamespaceAliasDecl * >::write(), clang::serialization::DataStreamBasicWriter< Impl >::writeAPSInt(), clang::serialization::DataStreamBasicWriter< Impl >::writeArray(), clang::serialization::DataStreamBasicWriter< Impl >::writeEnum(), and clang::serialization::DataStreamBasicWriter< Impl >::writeObject().
getASTContext()
template<class Impl > ASTContext & clang::serialization::BasicWriterBase< Impl >::getASTContext () inline
Definition at line 740 of file AbstractBasicWriter.h.
writeAPValue()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeAPValue (const APValue & node) inline
Definition at line 742 of file AbstractBasicWriter.h.
writeAPValueKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeAPValueKind (APValue::ValueKind value) inline
Definition at line 948 of file AbstractBasicWriter.h.
writeArraySizeModifier()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeArraySizeModifier (ArrayType::ArraySizeModifier value) inline
Definition at line 951 of file AbstractBasicWriter.h.
writeAttrKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeAttrKind (attr::Kind value) inline
Definition at line 954 of file AbstractBasicWriter.h.
writeAutoTypeKeyword()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeAutoTypeKeyword (AutoTypeKeyword value) inline
Definition at line 957 of file AbstractBasicWriter.h.
writeBuiltinTypeKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeBuiltinTypeKind (BuiltinType::Kind value) inline
Definition at line 960 of file AbstractBasicWriter.h.
writeCallingConv()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeCallingConv (CallingConv value) inline
Definition at line 966 of file AbstractBasicWriter.h.
writeConceptDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeConceptDeclRef (const ConceptDecl * value) inline
Definition at line 969 of file AbstractBasicWriter.h.
writeCXXRecordDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeCXXRecordDeclRef (const CXXRecordDecl * value) inline
Definition at line 963 of file AbstractBasicWriter.h.
writeDeclarationName()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeDeclarationName (DeclarationName node) inline
Definition at line 972 of file AbstractBasicWriter.h.
writeDeclarationNameKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeDeclarationNameKind (DeclarationName::NameKind value) inline
Definition at line 1044 of file AbstractBasicWriter.h.
writeElaboratedTypeKeyword()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeElaboratedTypeKeyword (ElaboratedTypeKeyword value) inline
Definition at line 1047 of file AbstractBasicWriter.h.
writeExprRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeExprRef (const Expr * value) inline
Definition at line 1050 of file AbstractBasicWriter.h.
writeFunctionDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeFunctionDeclRef (const FunctionDecl * value) inline
Definition at line 1053 of file AbstractBasicWriter.h.
writeNamedDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeNamedDeclRef (const NamedDecl * value) inline
Definition at line 1056 of file AbstractBasicWriter.h.
writeNamespaceAliasDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeNamespaceAliasDeclRef (const NamespaceAliasDecl * value) inline
Definition at line 1059 of file AbstractBasicWriter.h.
writeNamespaceDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeNamespaceDeclRef (const NamespaceDecl * value) inline
Definition at line 1062 of file AbstractBasicWriter.h.
writeNestedNameSpecifierKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeNestedNameSpecifierKind (NestedNameSpecifier::SpecifierKind value) inline
Definition at line 1065 of file AbstractBasicWriter.h.
writeObjCProtocolDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeObjCProtocolDeclRef (const ObjCProtocolDecl * value) inline
Definition at line 1068 of file AbstractBasicWriter.h.
writeObjCTypeParamDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeObjCTypeParamDeclRef (const ObjCTypeParamDecl * value) inline
Definition at line 1071 of file AbstractBasicWriter.h.
writeOverloadedOperatorKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeOverloadedOperatorKind (OverloadedOperatorKind value) inline
Definition at line 1074 of file AbstractBasicWriter.h.
writeRefQualifierKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeRefQualifierKind (RefQualifierKind value) inline
Definition at line 1077 of file AbstractBasicWriter.h.
writeTagDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTagDeclRef (const TagDecl * value) inline
Definition at line 1080 of file AbstractBasicWriter.h.
writeTemplateArgument()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateArgument (TemplateArgument node) inline
Definition at line 1083 of file AbstractBasicWriter.h.
writeTemplateArgumentKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateArgumentKind (TemplateArgument::ArgKind value) inline
Definition at line 1153 of file AbstractBasicWriter.h.
writeTemplateDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateDeclRef (const TemplateDecl * value) inline
Definition at line 1156 of file AbstractBasicWriter.h.
writeTemplateName()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateName (TemplateName node) inline
Definition at line 1159 of file AbstractBasicWriter.h.
writeTemplateNameKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateNameKind (TemplateName::NameKind value) inline
Definition at line 1238 of file AbstractBasicWriter.h.
writeTemplateTemplateParmDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateTemplateParmDeclRef (const TemplateTemplateParmDecl * value) inline
Definition at line 1241 of file AbstractBasicWriter.h.
writeTemplateTypeParmDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeTemplateTypeParmDeclRef (const TemplateTypeParmDecl * value) inline
Definition at line 1244 of file AbstractBasicWriter.h.
writeUnaryTypeTransformKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeUnaryTypeTransformKind (UnaryTransformType::UTTKind value) inline
Definition at line 1247 of file AbstractBasicWriter.h.
writeValueDeclRef()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeValueDeclRef (const ValueDecl * value) inline
Definition at line 1250 of file AbstractBasicWriter.h.
writeVectorKind()
template<class Impl > void clang::serialization::BasicWriterBase< Impl >::writeVectorKind (VectorType::VectorKind value) inline
Definition at line 1253 of file AbstractBasicWriter.h.
The documentation for this class was generated from the following file:
include/clang/AST/AbstractBasicWriter.h