clang: clang::ento::SymbolRegionValue Class Reference
clang::ento::SymbolRegionValue Class Reference
A symbol representing the value stored at a MemRegion.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
SymbolRegionValue (SymbolID sym, const TypedValueRegion *r)
const TypedValueRegion * getRegion () const
void Profile (llvm::FoldingSetNodeID &profile) override
StringRef getKindStr () const override
Get a string representation of the kind of the region.
void dumpToStream (raw_ostream &os) const override
const MemRegion * getOriginRegion () const override
Find the region from which this symbol originates.
QualType getType () const override
Public Member Functions inherited from clang::ento::SymbolData
~SymbolData () override=default
SymbolID getSymbolID () const
unsigned computeComplexity () const override
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
symbol_iterator symbol_begin () const
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &profile, const TypedValueRegion *R)
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymbolData
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymExpr
static symbol_iterator symbol_end ()
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Protected Member Functions inherited from clang::ento::SymbolData
SymbolData (Kind k, SymbolID sym)
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
A symbol representing the value stored at a MemRegion.
Definition at line 41 of file SymbolManager.h.
Constructor & Destructor Documentation
SymbolRegionValue()
clang::ento::SymbolRegionValue::SymbolRegionValue (SymbolID sym, const TypedValueRegion * r) inline
Definition at line 45 of file SymbolManager.h.
References clang::ento::TypedValueRegion::getValueType(), and clang::ento::SymExpr::isValidTypeForSymbol().
Member Function Documentation
classof()
static bool clang::ento::SymbolRegionValue::classof (const SymExpr * SE) inline static
Definition at line 70 of file SymbolManager.h.
References clang::ento::SymExpr::getKind().
dumpToStream()
void SymbolRegionValue::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::SymExpr.
Definition at line 99 of file SymbolManager.cpp.
References clang::QualType::getAsString(), getKindStr(), clang::ento::SymbolData::getSymbolID(), and getType().
getKindStr()
StringRef SymbolRegionValue::getKindStr () const override virtual
Get a string representation of the kind of the region.
Implements clang::ento::SymbolData.
Definition at line 42 of file SymbolManager.cpp.
Referenced by dumpToStream().
getOriginRegion()
const MemRegion * clang::ento::SymbolRegionValue::getOriginRegion () const inline override virtual
Find the region from which this symbol originates.
Whenever the symbol was constructed to denote an unknown value of a certain memory region, return this region. This method allows checkers to make decisions depending on the origin of the symbol. Symbol classes for which the origin region is known include SymbolRegionValue which denotes the value of the region before the beginning of the analysis, and SymbolDerived which denotes the value of a certain memory region after its super region (a memory space or a larger record region) is default-bound with a certain symbol.
Reimplemented from clang::ento::SymExpr.
Definition at line 65 of file SymbolManager.h.
References getRegion().
getRegion()
const TypedValueRegion * clang::ento::SymbolRegionValue::getRegion () const inline
Definition at line 51 of file SymbolManager.h.
Referenced by getOriginRegion().
getType()
QualType SymbolRegionValue::getType () const override virtual
Implements clang::ento::SymExpr.
Definition at line 329 of file SymbolManager.cpp.
Referenced by dumpToStream().
Profile() [1/2]
void clang::ento::SymbolRegionValue::Profile (llvm::FoldingSetNodeID & profile) inline override virtual
Implements clang::ento::SymExpr.
Definition at line 58 of file SymbolManager.h.
References Profile().
Profile() [2/2]
static void clang::ento::SymbolRegionValue::Profile (llvm::FoldingSetNodeID & profile, const TypedValueRegion * R) inline static
Definition at line 53 of file SymbolManager.h.
Referenced by clang::ento::SymbolManager::getRegionValueSymbol(), and Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp