clang: clang::ASTVector< T > Class Template Reference
clang::ASTVector< T > Class Template Reference
#include "clang/AST/ASTVector.h"
Public Types
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = std::reverse_iterator<iterator>
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
ASTVector ()
ASTVector (ASTVector &&O)
ASTVector (const ASTContext &C, unsigned N)
ASTVector & operator= (ASTVector &&RHS)
~ASTVector ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_type size () const
reference operator[] (unsigned idx)
const_reference operator[] (unsigned idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void pop_back ()
T pop_back_val ()
void clear ()
pointer data ()
data - Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
data - Return a pointer to the vector's buffer, even if empty().
void push_back (const_reference Elt, const ASTContext &C)
void reserve (const ASTContext &C, unsigned N)
size_t capacity () const
capacity - Return the total number of elements in the currently allocated buffer.
template<typename in_iter >
void append (const ASTContext &C, in_iter in_start, in_iter in_end)
append - Add the specified range to the end of the SmallVector.
void append (const ASTContext &C, size_type NumInputs, const T &Elt)
append - Add the specified range to the end of the SmallVector.
iterator insert (const ASTContext &C, iterator I, const T &Elt)
iterator insert (const ASTContext &C, iterator I, size_type NumToInsert, const T &Elt)
template<typename ItTy >
iterator insert (const ASTContext &C, iterator I, ItTy From, ItTy To)
void resize (const ASTContext &C, unsigned N, const T &NV)
Static Public Member Functions
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
uninitialized_copy - Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Protected Member Functions
bool getTag () const
void setTag (bool B)
const_iterator capacity_ptr () const
iterator capacity_ptr ()
Detailed Description
template<typename T>
class clang::ASTVector< T >
Definition at line 36 of file ASTVector.h.
Member Typedef Documentation
const_iterator
template<typename T > using clang::ASTVector< T >::const_iterator = const T *
Definition at line 86 of file ASTVector.h.
const_pointer
template<typename T > using clang::ASTVector< T >::const_pointer = const T *
Definition at line 94 of file ASTVector.h.
const_reference
template<typename T > using clang::ASTVector< T >::const_reference = const T &
Definition at line 92 of file ASTVector.h.
const_reverse_iterator
template<typename T > using clang::ASTVector< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 88 of file ASTVector.h.
difference_type
template<typename T > using clang::ASTVector< T >::difference_type = ptrdiff_t
Definition at line 83 of file ASTVector.h.
iterator
template<typename T > using clang::ASTVector< T >::iterator = T *
Definition at line 85 of file ASTVector.h.
pointer
template<typename T > using clang::ASTVector< T >::pointer = T *
Definition at line 93 of file ASTVector.h.
reference
template<typename T > using clang::ASTVector< T >::reference = T &
Definition at line 91 of file ASTVector.h.
reverse_iterator
template<typename T > using clang::ASTVector< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 89 of file ASTVector.h.
size_type
template<typename T > using clang::ASTVector< T >::size_type = size_t
Definition at line 82 of file ASTVector.h.
value_type
template<typename T > using clang::ASTVector< T >::value_type = T
Definition at line 84 of file ASTVector.h.
Constructor & Destructor Documentation
ASTVector() [1/3]
template<typename T > clang::ASTVector< T >::ASTVector () inline
Definition at line 52 of file ASTVector.h.
ASTVector() [2/3]
template<typename T > clang::ASTVector< T >::ASTVector (ASTVector< T > && O) inline
Definition at line 54 of file ASTVector.h.
References Begin.
ASTVector() [3/3]
template<typename T > clang::ASTVector< T >::ASTVector (const ASTContext & C, unsigned N) inline
Definition at line 60 of file ASTVector.h.
References clang::C, N, and clang::ASTVector< T >::reserve().
~ASTVector()
template<typename T > clang::ASTVector< T >::~ASTVector () inline
Definition at line 75 of file ASTVector.h.
References Begin.
Member Function Documentation
append() [1/2]
template<typename T > template<typename in_iter > void clang::ASTVector< T >::append (const ASTContext & C, in_iter in_start, in_iter in_end) inline
append - Add the specified range to the end of the SmallVector.
Definition at line 184 of file ASTVector.h.
References clang::C, clang::ASTVector< T >::capacity_ptr(), clang::ASTVector< T >::end(), and clang::ASTVector< T >::size().
Referenced by clang::ASTVector< T >::insert(), and clang::ASTVector< T >::insert().
append() [2/2]
template<typename T > void clang::ASTVector< T >::append (const ASTContext & C, size_type NumInputs, const T & Elt) inline
append - Add the specified range to the end of the SmallVector.
Definition at line 202 of file ASTVector.h.
References clang::C, clang::ASTVector< T >::capacity_ptr(), clang::ASTVector< T >::end(), and clang::ASTVector< T >::size().
back() [1/2]
template<typename T > reference clang::ASTVector< T >::back () inline
Definition at line 127 of file ASTVector.h.
References clang::ASTVector< T >::end().
Referenced by clang::ASTVector< T >::insert(), and clang::ASTVector< T >::pop_back_val().
back() [2/2]
template<typename T > const_reference clang::ASTVector< T >::back () const inline
Definition at line 130 of file ASTVector.h.
References clang::ASTVector< T >::end().
begin() [1/2]
template<typename T > iterator clang::ASTVector< T >::begin () inline
Definition at line 97 of file ASTVector.h.
References Begin.
Referenced by clang::InitListExpr::begin(), clang::InitListExpr::begin(), clang::ASTVector< T >::front(), clang::ASTVector< T >::front(), clang::InitListExpr::getBeginLoc(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::rend(), clang::ASTVector< T >::rend(), and clang::ASTVector< T >::resize().
begin() [2/2]
template<typename T > const_iterator clang::ASTVector< T >::begin () const inline
Definition at line 98 of file ASTVector.h.
References Begin.
capacity()
template<typename T > size_t clang::ASTVector< T >::capacity () const inline
capacity - Return the total number of elements in the currently allocated buffer.
Definition at line 180 of file ASTVector.h.
References clang::ASTVector< T >::capacity_ptr().
Referenced by clang::ASTVector< T >::resize().
capacity_ptr() [1/2]
template<typename T > iterator clang::ASTVector< T >::capacity_ptr () inline protected
Definition at line 375 of file ASTVector.h.
capacity_ptr() [2/2]
template<typename T > const_iterator clang::ASTVector< T >::capacity_ptr () const inline protected
Definition at line 371 of file ASTVector.h.
Referenced by clang::ASTVector< T >::append(), clang::ASTVector< T >::append(), clang::ASTVector< T >::capacity(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::push_back(), and clang::ASTVector< T >::reserve().
clear()
template<typename T > void clang::ASTVector< T >::clear () inline
Definition at line 145 of file ASTVector.h.
References Begin.
data() [1/2]
template<typename T > pointer clang::ASTVector< T >::data () inline
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 153 of file ASTVector.h.
References Begin.
Referenced by clang::InitListExpr::getInits(), and clang::InitListExpr::getInits().
data() [2/2]
template<typename T > const_pointer clang::ASTVector< T >::data () const inline
data - Return a pointer to the vector's buffer, even if empty().
Definition at line 158 of file ASTVector.h.
References Begin.
empty()
template<typename T > bool clang::ASTVector< T >::empty () const inline
Definition at line 108 of file ASTVector.h.
References Begin.
Referenced by clang::InitListExpr::children().
end() [1/2]
template<typename T > iterator clang::ASTVector< T >::end () inline
Definition at line 99 of file ASTVector.h.
Referenced by clang::ASTVector< T >::append(), clang::ASTVector< T >::append(), clang::ASTVector< T >::back(), clang::ASTVector< T >::back(), clang::InitListExpr::end(), clang::InitListExpr::end(), clang::InitListExpr::getBeginLoc(), clang::InitListExpr::InitListExpr(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::rbegin(), clang::ASTVector< T >::rbegin(), clang::ASTVector< T >::resize(), and clang::InitListExpr::updateInit().
end() [2/2]
template<typename T > const_iterator clang::ASTVector< T >::end () const inline
Definition at line 100 of file ASTVector.h.
front() [1/2]
template<typename T > reference clang::ASTVector< T >::front () inline
Definition at line 120 of file ASTVector.h.
References clang::ASTVector< T >::begin().
front() [2/2]
template<typename T > const_reference clang::ASTVector< T >::front () const inline
Definition at line 123 of file ASTVector.h.
References clang::ASTVector< T >::begin().
getTag()
template<typename T > bool clang::ASTVector< T >::getTag () const inline protected
Definition at line 47 of file ASTVector.h.
insert() [1/3]
template<typename T > iterator clang::ASTVector< T >::insert (const ASTContext & C, iterator I, const T & Elt) inline
Definition at line 219 of file ASTVector.h.
References clang::ASTVector< T >::back(), clang::ASTVector< T >::begin(), clang::C, clang::ASTVector< T >::capacity_ptr(), clang::ASTVector< T >::end(), and clang::ASTVector< T >::push_back().
Referenced by clang::InitListExpr::InitListExpr(), and clang::InitListExpr::updateInit().
insert() [2/3]
template<typename T > template<typename ItTy > iterator clang::ASTVector< T >::insert (const ASTContext & C, iterator I, ItTy From, ItTy To) inline
Definition at line 289 of file ASTVector.h.
References clang::ASTVector< T >::append(), clang::ASTVector< T >::begin(), clang::C, clang::ASTVector< T >::end(), clang::ASTVector< T >::reserve(), clang::ASTVector< T >::size(), and clang::ASTVector< T >::uninitialized_copy().
insert() [3/3]
template<typename T > iterator clang::ASTVector< T >::insert (const ASTContext & C, iterator I, size_type NumToInsert, const T & Elt) inline
Definition at line 240 of file ASTVector.h.
References clang::ASTVector< T >::append(), clang::ASTVector< T >::begin(), clang::C, clang::ASTVector< T >::end(), clang::ASTVector< T >::reserve(), clang::ASTVector< T >::size(), and clang::ASTVector< T >::uninitialized_copy().
operator=()
template<typename T > ASTVector & clang::ASTVector< T >::operator= (ASTVector< T > && RHS) inline
Definition at line 64 of file ASTVector.h.
References Begin.
operator[]() [1/2]
template<typename T > reference clang::ASTVector< T >::operator[] (unsigned idx) inline
Definition at line 111 of file ASTVector.h.
References Begin.
operator[]() [2/2]
template<typename T > const_reference clang::ASTVector< T >::operator[] (unsigned idx) const inline
Definition at line 115 of file ASTVector.h.
References Begin.
pop_back()
template<typename T > void clang::ASTVector< T >::pop_back () inline
Definition at line 134 of file ASTVector.h.
Referenced by clang::ASTVector< T >::pop_back_val().
pop_back_val()
template<typename T > T clang::ASTVector< T >::pop_back_val () inline
Definition at line 139 of file ASTVector.h.
References clang::ASTVector< T >::back(), clang::ASTVector< T >::pop_back(), and clang::Result.
push_back()
template<typename T > void clang::ASTVector< T >::push_back (const_reference Elt, const ASTContext & C) inline
Definition at line 162 of file ASTVector.h.
References clang::C, and clang::ASTVector< T >::capacity_ptr().
Referenced by clang::ASTVector< T >::insert().
rbegin() [1/2]
template<typename T > reverse_iterator clang::ASTVector< T >::rbegin () inline
Definition at line 103 of file ASTVector.h.
References clang::ASTVector< T >::end().
Referenced by clang::InitListExpr::getEndLoc(), clang::InitListExpr::rbegin(), and clang::InitListExpr::rbegin().
rbegin() [2/2]
template<typename T > const_reverse_iterator clang::ASTVector< T >::rbegin () const inline
Definition at line 104 of file ASTVector.h.
References clang::ASTVector< T >::end().
rend() [1/2]
template<typename T > reverse_iterator clang::ASTVector< T >::rend () inline
Definition at line 105 of file ASTVector.h.
References clang::ASTVector< T >::begin().
Referenced by clang::InitListExpr::getEndLoc(), clang::InitListExpr::rend(), and clang::InitListExpr::rend().
rend() [2/2]
template<typename T > const_reverse_iterator clang::ASTVector< T >::rend () const inline
Definition at line 106 of file ASTVector.h.
References clang::ASTVector< T >::begin().
reserve()
template<typename T > void clang::ASTVector< T >::reserve (const ASTContext & C, unsigned N) inline
Definition at line 173 of file ASTVector.h.
References clang::C, clang::ASTVector< T >::capacity_ptr(), and N.
Referenced by clang::ASTVector< T >::ASTVector(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), and clang::InitListExpr::reserveInits().
resize()
template<typename T > void clang::ASTVector< T >::resize (const ASTContext & C, unsigned N, const T & NV) inline
Definition at line 341 of file ASTVector.h.
References clang::ASTVector< T >::begin(), clang::C, clang::ASTVector< T >::capacity(), clang::ASTVector< T >::end(), N, and clang::ASTVector< T >::size().
Referenced by clang::InitListExpr::resizeInits().
setTag()
template<typename T > void clang::ASTVector< T >::setTag (bool B) inline protected
Definition at line 48 of file ASTVector.h.
size()
template<typename T > size_type clang::ASTVector< T >::size () const inline
Definition at line 109 of file ASTVector.h.
References Begin.
Referenced by clang::ASTVector< T >::append(), clang::ASTVector< T >::append(), clang::InitListExpr::children(), clang::ASTRecordLayout::getFieldCount(), clang::InitListExpr::getNumInits(), clang::ASTVector< T >::insert(), clang::ASTVector< T >::insert(), clang::InitListExpr::reserveInits(), clang::ASTVector< T >::resize(), and clang::InitListExpr::updateInit().
uninitialized_copy()
template<typename T > template<typename It1 , typename It2 > static void clang::ASTVector< T >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static
uninitialized_copy - Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 215 of file ASTVector.h.
Referenced by clang::ASTVector< T >::insert(), and clang::ASTVector< T >::insert().
The documentation for this class was generated from the following file:
include/clang/AST/ASTVector.h