clang: clang::CodeGen::CodeGenFunction::OpaqueValueMappingData Class Reference
clang::CodeGen::CodeGenFunction::OpaqueValueMappingData Class Reference
A non-RAII class containing all the information about a bound opaque value.
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
OpaqueValueMappingData ()
bool isValid () const
void clear ()
void unbind (CodeGenFunction &CGF)
Static Public Member Functions
static bool shouldBindAsLValue (const Expr *expr)
static OpaqueValueMappingData bind (CodeGenFunction &CGF, const OpaqueValueExpr *ov, const Expr *e)
static OpaqueValueMappingData bind (CodeGenFunction &CGF, const OpaqueValueExpr *ov, const LValue &lv)
static OpaqueValueMappingData bind (CodeGenFunction &CGF, const OpaqueValueExpr *ov, const RValue &rv)
Detailed Description
A non-RAII class containing all the information about a bound opaque value.
OpaqueValueMapping, below, is a RAII wrapper for this which makes individual mappings very simple; using this class directly is useful when you have a variable number of opaque values or don't want the RAII functionality for some reason.
Definition at line 1181 of file CodeGenFunction.h.
Constructor & Destructor Documentation
OpaqueValueMappingData()
clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::OpaqueValueMappingData () inline
Definition at line 1190 of file CodeGenFunction.h.
Referenced by bind().
Member Function Documentation
bind() [1/3]
static OpaqueValueMappingData clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind (CodeGenFunction & CGF, const OpaqueValueExpr * ov, const Expr * e) inline static
Definition at line 1203 of file CodeGenFunction.h.
References bind(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CodeGenFunction::EmitLValue(), and shouldBindAsLValue().
Referenced by bind(), emitSuspendExpression(), clang::CodeGen::CodeGenFunction::OpaqueValueMapping::OpaqueValueMapping(), and clang::CodeGen::CodeGenFunction::OpaqueValueMapping::OpaqueValueMapping().
bind() [2/3]
static OpaqueValueMappingData clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind (CodeGenFunction & CGF, const OpaqueValueExpr * ov, const LValue & lv) inline static
Definition at line 1211 of file CodeGenFunction.h.
References OpaqueValueMappingData(), and shouldBindAsLValue().
bind() [3/3]
static OpaqueValueMappingData clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind (CodeGenFunction & CGF, const OpaqueValueExpr * ov, const RValue & rv) inline static
Definition at line 1219 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::protectFromPeepholes(), and shouldBindAsLValue().
clear()
void clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::clear () inline
Definition at line 1236 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMapping::pop().
isValid()
bool clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::isValid () const inline
Definition at line 1235 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMapping::~OpaqueValueMapping().
shouldBindAsLValue()
static bool clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::shouldBindAsLValue (const Expr * expr) inline static
Definition at line 1192 of file CodeGenFunction.h.
References clang::ast_matchers::expr, and clang::CodeGen::CodeGenFunction::hasAggregateEvaluationKind().
Referenced by bind(), bind(), bind(), and clang::CodeGen::CodeGenFunction::OpaqueValueMapping::shouldBindAsLValue().
unbind()
void clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::unbind (CodeGenFunction & CGF) inline
Definition at line 1238 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::unprotectFromPeepholes().
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMapping::pop(), and clang::CodeGen::CodeGenFunction::OpaqueValueMapping::~OpaqueValueMapping().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h