clang: clang::AlignedAttr Class Reference
clang::AlignedAttr Class Reference
#include "clang/AST/Attr.h"
Public Types
enum Spelling {
GNU_aligned = 0 , CXX11_gnu_aligned = 1 , C2x_gnu_aligned = 2 , Declspec_align = 3 ,
Keyword_alignas = 4 , Keyword_Alignas = 5 , SpellingNotCalculated = 15
}
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
AlignedAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, bool IsAlignmentExpr, void *Alignment)
AlignedAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo)
AlignedAttr * clone (ASTContext &C) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
const char * getSpelling () const
Spelling getSemanticSpelling () const
bool isGNU () const
bool isC11 () const
bool isAlignas () const
bool isDeclspec () const
bool isAlignmentDependent () const
bool isAlignmentErrorDependent () const
unsigned getAlignment (ASTContext &Ctx) const
bool isAlignmentExpr () const
Expr * getAlignmentExpr () const
TypeSourceInfo * getAlignmentType () const
Public Member Functions inherited from clang::InheritableAttr
void setInherited (bool I)
bool shouldInheritEvenIfAlreadyPresent () const
Should this attribute be inherited from a prior declaration even if it's explicitly provided in the current declaration?
Public Member Functions inherited from clang::Attr
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static AlignedAttr * CreateImplicit (ASTContext &Ctx, bool IsAlignmentExpr, void *Alignment, const AttributeCommonInfo &CommonInfo={SourceRange{}})
static AlignedAttr * Create (ASTContext &Ctx, bool IsAlignmentExpr, void *Alignment, const AttributeCommonInfo &CommonInfo)
static AlignedAttr * CreateImplicit (ASTContext &Ctx, bool IsAlignmentExpr, void *Alignment, SourceRange Range, AttributeCommonInfo::Syntax Syntax, AlignedAttr::Spelling S=static_cast< Spelling >(SpellingNotCalculated))
static AlignedAttr * Create (ASTContext &Ctx, bool IsAlignmentExpr, void *Alignment, SourceRange Range, AttributeCommonInfo::Syntax Syntax, AlignedAttr::Spelling S=static_cast< Spelling >(SpellingNotCalculated))
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::InheritableAttr
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Additional Inherited Members
Protected Member Functions inherited from clang::InheritableAttr
InheritableAttr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed, bool InheritEvenIfAlreadyPresent)
Protected Member Functions inherited from clang::Attr
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes inherited from clang::Attr
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Definition at line 663 of file Attr.h.
Member Enumeration Documentation
Spelling
enum clang::AlignedAttr::Spelling
Enumerator
GNU_aligned
CXX11_gnu_aligned
C2x_gnu_aligned
Declspec_align
Keyword_alignas
Keyword_Alignas
SpellingNotCalculated
Definition at line 671 of file Attr.h.
Constructor & Destructor Documentation
AlignedAttr() [1/2]
clang::AlignedAttr::AlignedAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, bool IsAlignmentExpr, void * Alignment)
AlignedAttr() [2/2]
clang::AlignedAttr::AlignedAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo)
Member Function Documentation
classof()
static bool clang::AlignedAttr::classof (const Attr * A) inline static
Definition at line 724 of file Attr.h.
clone()
AlignedAttr * clang::AlignedAttr::clone (ASTContext & C) const
Referenced by mergeAlignedAttrs().
Create() [1/2]
static AlignedAttr * clang::AlignedAttr::Create (ASTContext & Ctx, bool IsAlignmentExpr, void * Alignment, const AttributeCommonInfo & CommonInfo) static
Referenced by clang::ASTImporter::Import().
Create() [2/2]
static AlignedAttr * clang::AlignedAttr::Create (ASTContext & Ctx, bool IsAlignmentExpr, void * Alignment, SourceRange Range, AttributeCommonInfo::Syntax Syntax, AlignedAttr::Spelling S = static_cast< Spelling >(SpellingNotCalculated)) static
CreateImplicit() [1/2]
static AlignedAttr * clang::AlignedAttr::CreateImplicit (ASTContext & Ctx, bool IsAlignmentExpr, void * Alignment, const AttributeCommonInfo & CommonInfo = {SourceRange{}}) static
CreateImplicit() [2/2]
static AlignedAttr * clang::AlignedAttr::CreateImplicit (ASTContext & Ctx, bool IsAlignmentExpr, void * Alignment, SourceRange Range, AttributeCommonInfo::Syntax Syntax, AlignedAttr::Spelling S = static_cast< Spelling >(SpellingNotCalculated)) static
getAlignment()
unsigned clang::AlignedAttr::getAlignment (ASTContext & Ctx) const
Referenced by mergeAlignedAttrs().
getAlignmentExpr()
Expr * clang::AlignedAttr::getAlignmentExpr () const inline
Definition at line 713 of file Attr.h.
Referenced by instantiateDependentAlignedAttr(), and instantiateDependentAlignedAttr().
getAlignmentType()
TypeSourceInfo * clang::AlignedAttr::getAlignmentType () const inline
Definition at line 717 of file Attr.h.
Referenced by instantiateDependentAlignedAttr(), and instantiateDependentAlignedAttr().
getSemanticSpelling()
Spelling clang::AlignedAttr::getSemanticSpelling () const
getSpelling()
const char * clang::AlignedAttr::getSpelling () const
isAlignas()
bool clang::AlignedAttr::isAlignas () const inline
Definition at line 704 of file Attr.h.
Referenced by mergeAlignedAttrs().
isAlignmentDependent()
bool clang::AlignedAttr::isAlignmentDependent () const
Referenced by clang::Sema::InstantiateAttrs().
isAlignmentErrorDependent()
bool clang::AlignedAttr::isAlignmentErrorDependent () const
isAlignmentExpr()
bool clang::AlignedAttr::isAlignmentExpr () const inline
Definition at line 710 of file Attr.h.
Referenced by instantiateDependentAlignedAttr(), and instantiateDependentAlignedAttr().
isC11()
bool clang::AlignedAttr::isC11 () const inline
Definition at line 703 of file Attr.h.
isDeclspec()
bool clang::AlignedAttr::isDeclspec () const inline
Definition at line 706 of file Attr.h.
isGNU()
bool clang::AlignedAttr::isGNU () const inline
Definition at line 700 of file Attr.h.
printPretty()
void clang::AlignedAttr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
Member Data Documentation
alignmentExpr
Expr* clang::AlignedAttr::alignmentExpr
Definition at line 666 of file Attr.h.
alignmentType
TypeSourceInfo* clang::AlignedAttr::alignmentType
Definition at line 667 of file Attr.h.
The documentation for this class was generated from the following file:
include/clang/AST/Attr.h