clang: clang::ento::EnvironmentEntry Class Reference
clang::ento::EnvironmentEntry Class Reference
An entry in the environment consists of a Stmt and an LocationContext.
#include "clang/StaticAnalyzer/Core/PathSensitive/Environment.h"
Public Member Functions
EnvironmentEntry (const Stmt *s, const LocationContext *L)
const Stmt * getStmt () const
const LocationContext * getLocationContext () const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const EnvironmentEntry &E)
Profile an EnvironmentEntry for inclusion in a FoldingSet.
Detailed Description
An entry in the environment consists of a Stmt and an LocationContext.
This allows the environment to manage context-sensitive bindings, which is essentially for modeling recursive function analysis, among other things.
Definition at line 35 of file Environment.h.
Constructor & Destructor Documentation
EnvironmentEntry()
EnvironmentEntry::EnvironmentEntry (const Stmt * s, const LocationContext * L)
Definition at line 71 of file Environment.cpp.
Member Function Documentation
getLocationContext()
const LocationContext * clang::ento::EnvironmentEntry::getLocationContext () const inline
Definition at line 41 of file Environment.h.
Referenced by clang::ento::Environment::getSVal(), Profile(), and clang::ento::EnvironmentManager::removeDeadBindings().
getStmt()
const Stmt * clang::ento::EnvironmentEntry::getStmt () const inline
Definition at line 40 of file Environment.h.
Referenced by clang::ento::Environment::getSVal(), Profile(), and clang::ento::EnvironmentManager::removeDeadBindings().
Profile() [1/2]
void clang::ento::EnvironmentEntry::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 50 of file Environment.h.
References Profile().
Profile() [2/2]
static void clang::ento::EnvironmentEntry::Profile (llvm::FoldingSetNodeID & ID, const EnvironmentEntry & E) inline static
Profile an EnvironmentEntry for inclusion in a FoldingSet.
Definition at line 44 of file Environment.h.
References getLocationContext(), and getStmt().
Referenced by Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/Environment.h
lib/StaticAnalyzer/Core/Environment.cpp