clang: clang::VTableLayout Class Reference
clang::VTableLayout Class Reference
#include "clang/AST/VTableBuilder.h"
Classes
struct AddressPointLocation
Public Types
typedef std::pair< uint64_t, ThunkInfo > VTableThunkTy
typedef llvm::DenseMap< BaseSubobject, AddressPointLocation > AddressPointsMapTy
typedef llvm::SmallVector< unsigned, 4 > AddressPointsIndexMapTy
Public Member Functions
VTableLayout (ArrayRef< size_t > VTableIndices, ArrayRef< VTableComponent > VTableComponents, ArrayRef< VTableThunkTy > VTableThunks, const AddressPointsMapTy &AddressPoints)
~VTableLayout ()
ArrayRef< VTableComponent > vtable_components () const
ArrayRef< VTableThunkTy > vtable_thunks () const
AddressPointLocation getAddressPoint (BaseSubobject Base) const
const AddressPointsMapTy & getAddressPoints () const
const AddressPointsIndexMapTy & getAddressPointIndices () const
size_t getNumVTables () const
size_t getVTableOffset (size_t i) const
size_t getVTableSize (size_t i) const
Detailed Description
Definition at line 232 of file VTableBuilder.h.
Member Typedef Documentation
AddressPointsIndexMapTy
llvm::SmallVector<unsigned, 4> clang::VTableLayout::AddressPointsIndexMapTy
Definition at line 244 of file VTableBuilder.h.
AddressPointsMapTy
llvm::DenseMap<BaseSubobject, AddressPointLocation> clang::VTableLayout::AddressPointsMapTy
Definition at line 239 of file VTableBuilder.h.
VTableThunkTy
std::pair<uint64_t, ThunkInfo> clang::VTableLayout::VTableThunkTy
Definition at line 234 of file VTableBuilder.h.
Constructor & Destructor Documentation
VTableLayout()
VTableLayout::VTableLayout (ArrayRef< size_t > VTableIndices, ArrayRef< VTableComponent > VTableComponents, ArrayRef< VTableThunkTy > VTableThunks, const AddressPointsMapTy & AddressPoints)
Definition at line 2238 of file VTableBuilder.cpp.
~VTableLayout()
VTableLayout::~VTableLayout ()
Definition at line 2258 of file VTableBuilder.cpp.
Member Function Documentation
getAddressPoint()
AddressPointLocation clang::VTableLayout::getAddressPoint (BaseSubobject Base) const inline
Definition at line 279 of file VTableBuilder.h.
Referenced by BuildAppleKextVirtualCall(), and clang::CodeGen::CodeGenVTables::EmitVTTDefinition().
getAddressPointIndices()
const AddressPointsIndexMapTy & clang::VTableLayout::getAddressPointIndices () const inline
Definition at line 288 of file VTableBuilder.h.
Referenced by clang::CodeGen::CodeGenVTables::createVTableInitializer().
getAddressPoints()
const AddressPointsMapTy & clang::VTableLayout::getAddressPoints () const inline
Definition at line 284 of file VTableBuilder.h.
Referenced by clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata().
getNumVTables()
size_t clang::VTableLayout::getNumVTables () const inline
Definition at line 292 of file VTableBuilder.h.
Referenced by clang::CodeGen::CodeGenVTables::createVTableInitializer(), and clang::CodeGen::CodeGenVTables::getVTableType().
getVTableOffset()
size_t clang::VTableLayout::getVTableOffset (size_t i) const inline
Definition at line 298 of file VTableBuilder.h.
Referenced by BuildAppleKextVirtualCall(), clang::CodeGen::CodeGenVTables::createVTableInitializer(), and clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata().
getVTableSize()
size_t clang::VTableLayout::getVTableSize (size_t i) const inline
Definition at line 306 of file VTableBuilder.h.
References vtable_components().
Referenced by clang::CodeGen::CodeGenVTables::createVTableInitializer(), and clang::CodeGen::CodeGenVTables::getVTableType().
vtable_components()
ArrayRef< VTableComponent > clang::VTableLayout::vtable_components () const inline
Definition at line 271 of file VTableBuilder.h.
Referenced by clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), and getVTableSize().
vtable_thunks()
ArrayRef< VTableThunkTy > clang::VTableLayout::vtable_thunks () const inline
Definition at line 275 of file VTableBuilder.h.
The documentation for this class was generated from the following files:
include/clang/AST/VTableBuilder.h
lib/AST/VTableBuilder.cpp