clang: clang::CompilerInvocationBase Class Reference
clang::CompilerInvocationBase Class Reference
#include "clang/Frontend/CompilerInvocation.h"
Public Member Functions
CompilerInvocationBase ()
CompilerInvocationBase (const CompilerInvocationBase &X)
CompilerInvocationBase & operator= (const CompilerInvocationBase &)=delete
~CompilerInvocationBase ()
LangOptions * getLangOpts ()
const LangOptions * getLangOpts () const
TargetOptions & getTargetOpts ()
const TargetOptions & getTargetOpts () const
DiagnosticOptions & getDiagnosticOpts () const
HeaderSearchOptions & getHeaderSearchOpts ()
const HeaderSearchOptions & getHeaderSearchOpts () const
std::shared_ptr< HeaderSearchOptions > getHeaderSearchOptsPtr () const
std::shared_ptr< PreprocessorOptions > getPreprocessorOptsPtr ()
PreprocessorOptions & getPreprocessorOpts ()
const PreprocessorOptions & getPreprocessorOpts () const
Public Attributes
std::shared_ptr< LangOptions > LangOpts
Options controlling the language variant.
std::shared_ptr< TargetOptions > TargetOpts
Options controlling the target.
IntrusiveRefCntPtr< DiagnosticOptions > DiagnosticOpts
Options controlling the diagnostic engine.
std::shared_ptr< HeaderSearchOptions > HeaderSearchOpts
Options controlling the #include directive.
std::shared_ptr< PreprocessorOptions > PreprocessorOpts
Options controlling the preprocessor (aside from #include handling).
Detailed Description
Definition at line 64 of file CompilerInvocation.h.
Constructor & Destructor Documentation
CompilerInvocationBase() [1/2]
CompilerInvocationBase::CompilerInvocationBase ()
Definition at line 109 of file CompilerInvocation.cpp.
CompilerInvocationBase() [2/2]
CompilerInvocationBase::CompilerInvocationBase (const CompilerInvocationBase & X)
Definition at line 115 of file CompilerInvocation.cpp.
~CompilerInvocationBase()
CompilerInvocationBase::~CompilerInvocationBase () default
Member Function Documentation
getDiagnosticOpts()
DiagnosticOptions & clang::CompilerInvocationBase::getDiagnosticOpts () const inline
Definition at line 92 of file CompilerInvocation.h.
References DiagnosticOpts.
Referenced by applyTransforms(), clang::arcmt::checkForManualIssues(), clang::CompilerInvocation::CreateFromArgs(), createInvocationForMigration(), and clang::CompilerInvocation::getModuleHash().
getHeaderSearchOpts() [1/2]
HeaderSearchOptions & clang::CompilerInvocationBase::getHeaderSearchOpts () inline
Definition at line 94 of file CompilerInvocation.h.
References HeaderSearchOpts.
Referenced by clang::CompilerInvocation::CreateFromArgs(), clang::createVFSFromCompilerInvocation(), and clang::CompilerInvocation::getModuleHash().
getHeaderSearchOpts() [2/2]
const HeaderSearchOptions & clang::CompilerInvocationBase::getHeaderSearchOpts () const inline
Definition at line 96 of file CompilerInvocation.h.
References HeaderSearchOpts.
getHeaderSearchOptsPtr()
std::shared_ptr< HeaderSearchOptions > clang::CompilerInvocationBase::getHeaderSearchOptsPtr () const inline
Definition at line 100 of file CompilerInvocation.h.
References HeaderSearchOpts.
getLangOpts() [1/2]
LangOptions * clang::CompilerInvocationBase::getLangOpts () inline
Definition at line 86 of file CompilerInvocation.h.
References LangOpts.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), applyTransforms(), clang::arcmt::checkForManualIssues(), clang::CompilerInvocation::CreateFromArgs(), FixupInvocation(), and clang::PrecompiledPreamble::OverridePreamble().
getLangOpts() [2/2]
const LangOptions * clang::CompilerInvocationBase::getLangOpts () const inline
Definition at line 87 of file CompilerInvocation.h.
References LangOpts.
getPreprocessorOpts() [1/2]
PreprocessorOptions & clang::CompilerInvocationBase::getPreprocessorOpts () inline
Definition at line 108 of file CompilerInvocation.h.
References PreprocessorOpts.
Referenced by clang::CompilerInvocation::CreateFromArgs(), getBufferForFileHandlingRemapping(), and clang::CompilerInvocation::getModuleHash().
getPreprocessorOpts() [2/2]
const PreprocessorOptions & clang::CompilerInvocationBase::getPreprocessorOpts () const inline
Definition at line 110 of file CompilerInvocation.h.
References PreprocessorOpts.
getPreprocessorOptsPtr()
std::shared_ptr< PreprocessorOptions > clang::CompilerInvocationBase::getPreprocessorOptsPtr () inline
Definition at line 104 of file CompilerInvocation.h.
References PreprocessorOpts.
getTargetOpts() [1/2]
TargetOptions & clang::CompilerInvocationBase::getTargetOpts () inline
Definition at line 89 of file CompilerInvocation.h.
References TargetOpts.
Referenced by clang::CompilerInvocation::CreateFromArgs(), FixupInvocation(), and HasARCRuntime().
getTargetOpts() [2/2]
const TargetOptions & clang::CompilerInvocationBase::getTargetOpts () const inline
Definition at line 90 of file CompilerInvocation.h.
References TargetOpts.
operator=()
CompilerInvocationBase & clang::CompilerInvocationBase::operator= (const CompilerInvocationBase &) delete
Member Data Documentation
DiagnosticOpts
IntrusiveRefCntPtr<DiagnosticOptions> clang::CompilerInvocationBase::DiagnosticOpts
Options controlling the diagnostic engine.
Definition at line 73 of file CompilerInvocation.h.
Referenced by getDiagnosticOpts().
HeaderSearchOpts
std::shared_ptr<HeaderSearchOptions> clang::CompilerInvocationBase::HeaderSearchOpts
Options controlling the #include directive.
Definition at line 76 of file CompilerInvocation.h.
Referenced by getHeaderSearchOpts(), getHeaderSearchOpts(), and getHeaderSearchOptsPtr().
LangOpts
std::shared_ptr<LangOptions> clang::CompilerInvocationBase::LangOpts
Options controlling the language variant.
Definition at line 67 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::CreateFromArgs(), clang::CompilerInvocation::generateCC1CommandLine(), getLangOpts(), getLangOpts(), and clang::CompilerInvocation::getModuleHash().
PreprocessorOpts
std::shared_ptr<PreprocessorOptions> clang::CompilerInvocationBase::PreprocessorOpts
Options controlling the preprocessor (aside from #include handling).
Definition at line 79 of file CompilerInvocation.h.
Referenced by getPreprocessorOpts(), getPreprocessorOpts(), and getPreprocessorOptsPtr().
TargetOpts
std::shared_ptr<TargetOptions> clang::CompilerInvocationBase::TargetOpts
Options controlling the target.
Definition at line 70 of file CompilerInvocation.h.
Referenced by clang::CompilerInvocation::getModuleHash(), getTargetOpts(), and getTargetOpts().
The documentation for this class was generated from the following files:
include/clang/Frontend/CompilerInvocation.h
lib/Frontend/CompilerInvocation.cpp