clang: clang::Sema::RequiredTemplateKind Class Reference
clang::Sema::RequiredTemplateKind Class Reference
Whether and why a template name is required in this lookup.
#include "clang/Sema/Sema.h"
Public Member Functions
RequiredTemplateKind (SourceLocation TemplateKWLoc=SourceLocation())
Template name is required if TemplateKWLoc is valid.
RequiredTemplateKind (TemplateNameIsRequiredTag)
Template name is unconditionally required.
SourceLocation getTemplateKeywordLoc () const
bool hasTemplateKeyword () const
bool isRequired () const
operator bool () const
Detailed Description
Whether and why a template name is required in this lookup.
Definition at line 7332 of file Sema.h.
Constructor & Destructor Documentation
RequiredTemplateKind() [1/2]
clang::Sema::RequiredTemplateKind::RequiredTemplateKind (SourceLocation TemplateKWLoc = SourceLocation()) inline
Template name is required if TemplateKWLoc is valid.
Definition at line 7335 of file Sema.h.
RequiredTemplateKind() [2/2]
clang::Sema::RequiredTemplateKind::RequiredTemplateKind (TemplateNameIsRequiredTag) inline
Template name is unconditionally required.
Definition at line 7338 of file Sema.h.
Member Function Documentation
getTemplateKeywordLoc()
SourceLocation clang::Sema::RequiredTemplateKind::getTemplateKeywordLoc () const inline
Definition at line 7340 of file Sema.h.
Referenced by hasTemplateKeyword(), and clang::Sema::LookupTemplateName().
hasTemplateKeyword()
bool clang::Sema::RequiredTemplateKind::hasTemplateKeyword () const inline
Definition at line 7343 of file Sema.h.
References getTemplateKeywordLoc(), and clang::SourceLocation::isValid().
Referenced by clang::Sema::LookupTemplateName().
isRequired()
bool clang::Sema::RequiredTemplateKind::isRequired () const inline
Definition at line 7344 of file Sema.h.
Referenced by operator bool().
operator bool()
clang::Sema::RequiredTemplateKind::operator bool () const inline explicit
Definition at line 7345 of file Sema.h.
References isRequired().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h