clang: clang::CodeGen::ConstantAddress Class Reference
clang::CodeGen::ConstantAddress Class Reference
A specialization of Address that requires the address to be an LLVM Constant.
#include "/root/llvm-project/clang/lib/CodeGen/Address.h"
Public Member Functions
ConstantAddress (llvm::Constant *pointer, CharUnits alignment)
llvm::Constant * getPointer () const
ConstantAddress getBitCast (llvm::Type *ty) const
ConstantAddress getElementBitCast (llvm::Type *ty) const
Public Member Functions inherited from clang::CodeGen::Address
Address (llvm::Value *pointer, CharUnits alignment)
bool isValid () const
llvm::Value * getPointer () const
llvm::PointerType * getType () const
Return the type of the pointer value.
llvm::Type * getElementType () const
Return the type of the values stored in this address.
unsigned getAddressSpace () const
Return the address space that this address resides in.
llvm::StringRef getName () const
Return the IR name of the pointer value.
CharUnits getAlignment () const
Return the alignment of this pointer.
Static Public Member Functions
static ConstantAddress invalid ()
static bool isaImpl (Address addr)
static ConstantAddress castImpl (Address addr)
Static Public Member Functions inherited from clang::CodeGen::Address
static Address invalid ()
Detailed Description
A specialization of Address that requires the address to be an LLVM Constant.
Definition at line 74 of file Address.h.
Constructor & Destructor Documentation
ConstantAddress()
clang::CodeGen::ConstantAddress::ConstantAddress (llvm::Constant * pointer, CharUnits alignment) inline
Definition at line 76 of file Address.h.
Referenced by castImpl(), getBitCast(), and invalid().
Member Function Documentation
castImpl()
static ConstantAddress clang::CodeGen::ConstantAddress::castImpl (Address addr) inline static
Definition at line 99 of file Address.h.
References ConstantAddress(), clang::CodeGen::Address::getAlignment(), and clang::CodeGen::Address::getPointer().
getBitCast()
ConstantAddress clang::CodeGen::ConstantAddress::getBitCast (llvm::Type * ty) const inline
Definition at line 87 of file Address.h.
References ConstantAddress(), clang::CodeGen::Address::getAlignment(), and getPointer().
Referenced by getElementBitCast().
getElementBitCast()
ConstantAddress clang::CodeGen::ConstantAddress::getElementBitCast (llvm::Type * ty) const inline
Definition at line 92 of file Address.h.
References clang::CodeGen::Address::getAddressSpace(), and getBitCast().
Referenced by emitConstantObjCStringLiteral().
getPointer()
llvm::Constant * clang::CodeGen::ConstantAddress::getPointer () const inline
Definition at line 83 of file Address.h.
References clang::CodeGen::Address::getPointer().
Referenced by buildBlockDescriptor(), EmitDeclDestroy(), EmitFunctionDeclPointer(), and getBitCast().
invalid()
static ConstantAddress clang::CodeGen::ConstantAddress::invalid () inline static
Definition at line 79 of file Address.h.
References ConstantAddress().
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfTemplateParamObject().
isaImpl()
static bool clang::CodeGen::ConstantAddress::isaImpl (Address addr) inline static
Definition at line 96 of file Address.h.
References clang::CodeGen::Address::getPointer().
The documentation for this class was generated from the following file:
lib/CodeGen/Address.h