clang: clang::AnalysisDeclContext Class Reference
clang::AnalysisDeclContext Class Reference
AnalysisDeclContext contains the context data for the function, method or block under analysis.
#include "clang/Analysis/AnalysisDeclContext.h"
Public Types
using referenced_decls_iterator = const VarDecl *const *
Public Member Functions
AnalysisDeclContext (AnalysisDeclContextManager *Mgr, const Decl *D)
AnalysisDeclContext (AnalysisDeclContextManager *Mgr, const Decl *D, const CFG::BuildOptions &BuildOptions)
~AnalysisDeclContext ()
ASTContext & getASTContext () const
const Decl * getDecl () const
AnalysisDeclContextManager * getManager () const
CFG::BuildOptions & getCFGBuildOptions ()
const CFG::BuildOptions & getCFGBuildOptions () const
bool getAddEHEdges () const
bool getUseUnoptimizedCFG () const
bool getAddImplicitDtors () const
bool getAddInitializers () const
void registerForcedBlockExpression (const Stmt *stmt)
const CFGBlock * getBlockForRegisteredExpression (const Stmt *stmt)
Stmt * getBody () const
Stmt * getBody (bool &IsAutosynthesized) const
bool isBodyAutosynthesized () const
bool isBodyAutosynthesizedFromModelFile () const
CFG * getCFG ()
CFGStmtMap * getCFGStmtMap ()
CFGReverseBlockReachabilityAnalysis * getCFGReachablityAnalysis ()
CFG * getUnoptimizedCFG ()
void dumpCFG (bool ShowColors)
bool isCFGBuilt () const
ParentMap & getParentMap ()
llvm::iterator_range< referenced_decls_iterator > getReferencedBlockVars (const BlockDecl *BD)
const ImplicitParamDecl * getSelfDecl () const
const StackFrameContext * getStackFrame (LocationContext const *ParentLC, const Stmt *S, const CFGBlock *Blk, unsigned BlockCount, unsigned Index)
Obtain a context of the call stack using its parent context.
const BlockInvocationContext * getBlockInvocationContext (const LocationContext *ParentLC, const BlockDecl *BD, const void *Data)
Obtain a context of the block invocation using its parent context.
template<typename T >
T * getAnalysis ()
Static Public Member Functions
static bool isInStdNamespace (const Decl *D)
Detailed Description
AnalysisDeclContext contains the context data for the function, method or block under analysis.
Definition at line 72 of file AnalysisDeclContext.h.
Member Typedef Documentation
referenced_decls_iterator
using clang::AnalysisDeclContext::referenced_decls_iterator = const VarDecl *const *
Definition at line 171 of file AnalysisDeclContext.h.
Constructor & Destructor Documentation
AnalysisDeclContext() [1/2]
AnalysisDeclContext::AnalysisDeclContext (AnalysisDeclContextManager * Mgr, const Decl * D)
Definition at line 62 of file AnalysisDeclContext.cpp.
References clang::CFG::BuildOptions::forcedBlkExprs.
AnalysisDeclContext() [2/2]
AnalysisDeclContext::AnalysisDeclContext (AnalysisDeclContextManager * Mgr, const Decl * D, const CFG::BuildOptions & BuildOptions)
Definition at line 55 of file AnalysisDeclContext.cpp.
References clang::CFG::BuildOptions::forcedBlkExprs.
~AnalysisDeclContext()
AnalysisDeclContext::~AnalysisDeclContext ()
Definition at line 633 of file AnalysisDeclContext.cpp.
Member Function Documentation
dumpCFG()
void AnalysisDeclContext::dumpCFG (bool ShowColors)
Definition at line 275 of file AnalysisDeclContext.cpp.
References clang::CFG::dump(), getASTContext(), and getCFG().
getAddEHEdges()
bool clang::AnalysisDeclContext::getAddEHEdges () const inline
Returns
Whether we are adding exception handling edges from CallExprs. If this is false, then try/catch statements and blocks reachable from them can appear to be dead in the CFG, analysis passes must cope with that.
Definition at line 119 of file AnalysisDeclContext.h.
References clang::CFG::BuildOptions::AddEHEdges.
Referenced by CheckFallThrough().
getAddImplicitDtors()
bool clang::AnalysisDeclContext::getAddImplicitDtors () const inline
Definition at line 123 of file AnalysisDeclContext.h.
References clang::CFG::BuildOptions::AddImplicitDtors.
getAddInitializers()
bool clang::AnalysisDeclContext::getAddInitializers () const inline
Definition at line 124 of file AnalysisDeclContext.h.
References clang::CFG::BuildOptions::AddInitializers.
getAnalysis()
template<typename T > T * clang::AnalysisDeclContext::getAnalysis () inline
Returns
The specified analysis object, lazily running the analysis if necessary or nullptr if the analysis could not run.
Definition at line 192 of file AnalysisDeclContext.h.
Referenced by clang::ento::AnalysisManager::getAnalysis(), clang::LocationContext::getAnalysis(), clang::threadSafety::CFGWalker::init(), and clang::consumed::ConsumedAnalyzer::run().
getASTContext()
ASTContext & clang::AnalysisDeclContext::getASTContext () const inline
Definition at line 104 of file AnalysisDeclContext.h.
References clang::Decl::getASTContext().
Referenced by clang::ento::SValBuilder::conjureSymbolVal(), dumpCFG(), clang::LocationContext::dumpStack(), clang::reachable_code::FindUnreachableCode(), clang::ento::getWidenedLoopState(), clang::LocationContext::printJson(), clang::ProgramPoint::printJson(), printObjectsUnderConstructionJson(), clang::consumed::ConsumedAnalyzer::run(), and clang::threadSafety::CFGWalker::walk().
getBlockForRegisteredExpression()
const CFGBlock * AnalysisDeclContext::getBlockForRegisteredExpression (const Stmt * stmt)
Definition at line 190 of file AnalysisDeclContext.cpp.
References clang::ast_matchers::stmt.
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
getBlockInvocationContext()
const BlockInvocationContext * AnalysisDeclContext::getBlockInvocationContext (const LocationContext * ParentLC, const BlockDecl * BD, const void * Data)
Obtain a context of the block invocation using its parent context.
Parameters
ADC The AnalysisDeclContext.
ParentLC The parent context of this newly created context.
BD The BlockDecl.
Data The raw data to store as part of the context.
Definition at line 319 of file AnalysisDeclContext.cpp.
References clang::LocationContextManager::getBlockInvocationContext().
Referenced by REGISTER_MAP_WITH_PROGRAMSTATE().
getBody() [1/2]
Stmt * AnalysisDeclContext::getBody () const
Returns
The body of the stored Decl D.
Definition at line 126 of file AnalysisDeclContext.cpp.
References getBody().
Referenced by DiagnoseSwitchLabelsFallthrough(), getBody(), getCFG(), getLocationForCaller(), getParentMap(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), getUnoptimizedCFG(), clang::ento::PathDiagnosticLocation::getValidSourceLocation(), isBodyAutosynthesized(), isBodyAutosynthesizedFromModelFile(), clang::ento::ExprEngine::processCallExit(), and clang::ento::ExprEngine::removeDeadOnEndOfFunction().
getBody() [2/2]
Stmt * AnalysisDeclContext::getBody (bool & IsAutosynthesized) const
Returns
The body of the stored Decl D.
Parameters
[out] IsAutosynthesized Specifies if the body is auto-generated by the BodyFarm.
Definition at line 93 of file AnalysisDeclContext.cpp.
References clang::BodyFarm::getBody(), clang::AnalysisDeclContextManager::getBodyFarm(), and clang::AnalysisDeclContextManager::synthesizeBodies().
getCFG()
CFG * AnalysisDeclContext::getCFG ()
Definition at line 213 of file AnalysisDeclContext.cpp.
References addParentsForSyntheticStmts(), clang::CFG::buildCFG(), clang::Decl::getASTContext(), getBody(), getCFGBuildOptions(), getUnoptimizedCFG(), clang::CFG::BuildOptions::Observer, and clang::CFG::BuildOptions::PruneTriviallyFalseEdges.
Referenced by CheckFallThrough(), checkRecursiveFunction(), checkThrowInNonThrowingFunc(), clang::LiveVariables::computeLiveness(), clang::PostOrderCFGView::create(), DiagnoseSwitchLabelsFallthrough(), dumpCFG(), clang::reachable_code::FindUnreachableCode(), clang::ento::AnalysisManager::getCFG(), clang::LocationContext::getCFG(), getCFGReachablityAnalysis(), getCFGStmtMap(), getParentMap(), clang::threadSafety::CFGWalker::init(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), clang::consumed::ConsumedAnalyzer::run(), and clang::LiveVariables::runOnAllBlocks().
getCFGBuildOptions() [1/2]
CFG::BuildOptions & clang::AnalysisDeclContext::getCFGBuildOptions () inline
Definition at line 110 of file AnalysisDeclContext.h.
Referenced by clang::reachable_code::FindUnreachableCode(), getCFG(), getUnoptimizedCFG(), and clang::sema::AnalysisBasedWarnings::IssueWarnings().
getCFGBuildOptions() [2/2]
const CFG::BuildOptions & clang::AnalysisDeclContext::getCFGBuildOptions () const inline
Definition at line 112 of file AnalysisDeclContext.h.
getCFGReachablityAnalysis()
CFGReverseBlockReachabilityAnalysis * AnalysisDeclContext::getCFGReachablityAnalysis ()
Definition at line 263 of file AnalysisDeclContext.cpp.
References c, and getCFG().
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
getCFGStmtMap()
CFGStmtMap * AnalysisDeclContext::getCFGStmtMap ()
Definition at line 251 of file AnalysisDeclContext.cpp.
References clang::CFGStmtMap::Build(), c, getCFG(), and getParentMap().
Referenced by clang::ento::CallEvent::getCalleeStackFrame(), clang::ento::ExplodedNode::getCFGBlock(), and clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode().
getDecl()
const Decl * clang::AnalysisDeclContext::getDecl () const inline
Definition at line 106 of file AnalysisDeclContext.h.
Referenced by CheckUnreachable(), DiagnoseSwitchLabelsFallthrough(), emitDiagnostics(), emitDiagnostics(), clang::LocationContext::getDecl(), clang::threadSafety::CFGWalker::getDecl(), getLocationForCaller(), getParentMap(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::ento::PathDiagnosticLocation::getValidSourceLocation(), clang::threadSafety::CFGWalker::init(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), and clang::consumed::ConsumedAnalyzer::run().
getManager()
AnalysisDeclContextManager * clang::AnalysisDeclContext::getManager () const inline
Definition at line 108 of file AnalysisDeclContext.h.
Referenced by clang::ento::CallEvent::getCalleeAnalysisDeclContext(), and clang::ento::CallEvent::getCalleeStackFrame().
getParentMap()
ParentMap & AnalysisDeclContext::getParentMap ()
Definition at line 279 of file AnalysisDeclContext.cpp.
References addParentsForSyntheticStmts(), clang::C, getBody(), getCFG(), getDecl(), and getUnoptimizedCFG().
Referenced by getCFGStmtMap(), clang::ento::AnalysisManager::getParentMap(), clang::LocationContext::getParentMap(), clang::ento::PathDiagnosticLocation::getValidSourceLocation(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), and shouldRemoveDeadBindings().
getReferencedBlockVars()
llvm::iterator_range< AnalysisDeclContext::referenced_decls_iterator > AnalysisDeclContext::getReferencedBlockVars (const BlockDecl * BD)
Definition at line 611 of file AnalysisDeclContext.cpp.
References LazyInitializeReferencedDecls(), and V.
getSelfDecl()
const ImplicitParamDecl * AnalysisDeclContext::getSelfDecl () const
Returns
The ImplicitParamDecl associated with self if this AnalysisDeclContext wraps an ObjCMethodDecl or nullptr otherwise.
Definition at line 148 of file AnalysisDeclContext.cpp.
References clang::CXXRecordDecl::captures(), clang::DeclContext::getParent(), clang::CXXRecordDecl::isLambda(), and isSelfDecl().
Referenced by clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::LocationContext::getSelfDecl(), and isSelfVar().
getStackFrame()
const StackFrameContext * AnalysisDeclContext::getStackFrame (LocationContext const * ParentLC, const Stmt * S, const CFGBlock * Blk, unsigned BlockCount, unsigned Index)
Obtain a context of the call stack using its parent context.
Parameters
ADC The AnalysisDeclContext.
ParentLC The parent context of this newly created context.
S The call.
Block The basic block.
BlockCount The current count of entering into Blk.
Index The index of Blk.
Returns
The context for D with parent context ParentLC.
Definition at line 312 of file AnalysisDeclContext.cpp.
References clang::LocationContextManager::getStackFrame().
Referenced by REGISTER_MAP_WITH_PROGRAMSTATE().
getUnoptimizedCFG()
CFG * AnalysisDeclContext::getUnoptimizedCFG ()
Returns
A version of the CFG without any edges pruned.
Definition at line 232 of file AnalysisDeclContext.cpp.
References addParentsForSyntheticStmts(), clang::CFG::buildCFG(), clang::Decl::getASTContext(), getBody(), getCFGBuildOptions(), clang::CFG::BuildOptions::Observer, and clang::CFG::BuildOptions::PruneTriviallyFalseEdges.
Referenced by getCFG(), and getParentMap().
getUseUnoptimizedCFG()
bool clang::AnalysisDeclContext::getUseUnoptimizedCFG () const inline
Definition at line 120 of file AnalysisDeclContext.h.
References clang::CFG::BuildOptions::PruneTriviallyFalseEdges.
isBodyAutosynthesized()
bool AnalysisDeclContext::isBodyAutosynthesized () const
Returns
Whether the body of the Decl D is generated by the BodyFarm.
Note
The lookup is not free. We are going to call getBody behind the scenes.
See also
getBody
Definition at line 131 of file AnalysisDeclContext.cpp.
References getBody().
Referenced by findTopAutosynthesizedParentContext(), clang::ento::ExplodedNode::getStmtForDiagnostics(), clang::ento::retaincountchecker::isSynthesizedAccessor(), and clang::ento::PathDiagnosticCallPiece::setCallee().
isBodyAutosynthesizedFromModelFile()
bool AnalysisDeclContext::isBodyAutosynthesizedFromModelFile () const
Returns
Whether the body of the Decl D is generated by the BodyFarm from a model file.
Note
The lookup is not free. We are going to call getBody behind the scenes.
See also
getBody
Definition at line 137 of file AnalysisDeclContext.cpp.
References clang::Stmt::getBeginLoc(), getBody(), and clang::SourceLocation::isValid().
isCFGBuilt()
bool clang::AnalysisDeclContext::isCFGBuilt () const inline
Returns
Whether we have built a CFG for this analysis context.
Note
This doesn't correspond to whether or not a valid CFG exists, it corresponds to whether we attempted to build one.
Definition at line 167 of file AnalysisDeclContext.h.
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
isInStdNamespace()
bool AnalysisDeclContext::isInStdNamespace (const Decl * D) static
Returns
Whether the root namespace of D is the std C++ namespace.
Definition at line 325 of file AnalysisDeclContext.cpp.
References clang::cast(), clang::Decl::getDeclContext(), clang::DeclContext::getEnclosingNamespaceContext(), clang::DeclContext::getParent(), and Parent.
registerForcedBlockExpression()
void AnalysisDeclContext::registerForcedBlockExpression (const Stmt * stmt)
Definition at line 180 of file AnalysisDeclContext.cpp.
References clang::ast_matchers::stmt.
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
The documentation for this class was generated from the following files:
include/clang/Analysis/AnalysisDeclContext.h
lib/Analysis/AnalysisDeclContext.cpp