clang: clang::DefaultArgStorage< ParmDecl, ArgType > Class Template Reference
clang::DefaultArgStorage< ParmDecl, ArgType > Class Template Reference
Storage for a default argument.
#include "clang/AST/DeclTemplate.h"
Public Member Functions
DefaultArgStorage ()
bool isSet () const
Determine whether there is a default argument for this parameter.
bool isInherited () const
Determine whether the default argument for this parameter was inherited from a previous declaration of the same entity.
ArgType get () const
Get the default argument's value.
const ParmDecl * getInheritedFrom () const
Get the parameter from which we inherit the default argument, if any.
void set (ArgType Arg)
Set the default argument.
void setInherited (const ASTContext &C, ParmDecl *InheritedFrom)
Set that the default argument was inherited from another parameter.
void clear ()
Remove the default argument, even if it was inherited.
Detailed Description
template<typename ParmDecl, typename ArgType>
class clang::DefaultArgStorage< ParmDecl, ArgType >
Storage for a default argument.
This is conceptually either empty, or an argument value, or a pointer to a previous declaration that had a default argument.
However, this is complicated by modules: while we require all the default arguments for a template to be equivalent, there may be more than one, and we need to track all the originating parameters to determine if the default argument is visible.
Definition at line 312 of file DeclTemplate.h.
Constructor & Destructor Documentation
DefaultArgStorage()
template<typename ParmDecl , typename ArgType > clang::DefaultArgStorage< ParmDecl, ArgType >::DefaultArgStorage () inline
Definition at line 336 of file DeclTemplate.h.
Member Function Documentation
clear()
template<typename ParmDecl , typename ArgType > void clang::DefaultArgStorage< ParmDecl, ArgType >::clear () inline
Remove the default argument, even if it was inherited.
Definition at line 384 of file DeclTemplate.h.
Referenced by clang::NonTypeTemplateParmDecl::removeDefaultArgument(), clang::TemplateTemplateParmDecl::removeDefaultArgument(), and clang::TemplateTypeParmDecl::removeDefaultArgument().
get()
template<typename ParmDecl , typename ArgType > ArgType clang::DefaultArgStorage< ParmDecl, ArgType >::get () const inline
Get the default argument's value.
This does not consider whether the default argument is visible.
Definition at line 347 of file DeclTemplate.h.
References clang::C, and clang::DefaultArgStorage< ParmDecl, ArgType >::get().
Referenced by clang::DefaultArgStorage< ParmDecl, ArgType >::get(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::TemplateTypeParmDecl::getDefaultArgument(), clang::TemplateTypeParmDecl::getDefaultArgumentInfo(), and clang::DefaultArgStorage< ParmDecl, ArgType >::setInherited().
getInheritedFrom()
template<typename ParmDecl , typename ArgType > const ParmDecl * clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom () const inline
Get the parameter from which we inherit the default argument, if any.
This is the parameter on which the default argument was actually written.
Definition at line 358 of file DeclTemplate.h.
References clang::C.
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitNonTypeTemplateParmDecl(), clang::JSONNodeDumper::VisitNonTypeTemplateParmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTemplateParmDecl(), clang::JSONNodeDumper::VisitTemplateTemplateParmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTypeParmDecl(), and clang::JSONNodeDumper::VisitTemplateTypeParmDecl().
isInherited()
template<typename ParmDecl , typename ArgType > bool clang::DefaultArgStorage< ParmDecl, ArgType >::isInherited () const inline
Determine whether the default argument for this parameter was inherited from a previous declaration of the same entity.
Definition at line 343 of file DeclTemplate.h.
References is().
Referenced by clang::NonTypeTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateTypeParmDecl::defaultArgumentWasInherited(), and clang::DefaultArgStorage< ParmDecl, ArgType >::setInherited().
isSet()
template<typename ParmDecl , typename ArgType > bool clang::DefaultArgStorage< ParmDecl, ArgType >::isSet () const inline
Determine whether there is a default argument for this parameter.
Definition at line 339 of file DeclTemplate.h.
Referenced by clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), clang::TemplateTypeParmDecl::hasDefaultArgument(), clang::DefaultArgStorage< ParmDecl, ArgType >::set(), and clang::DefaultArgStorage< ParmDecl, ArgType >::setInherited().
set()
template<typename ParmDecl , typename ArgType > void clang::DefaultArgStorage< ParmDecl, ArgType >::set (ArgType Arg) inline
Set the default argument.
Definition at line 367 of file DeclTemplate.h.
References clang::DefaultArgStorage< ParmDecl, ArgType >::isSet().
Referenced by clang::NonTypeTemplateParmDecl::setDefaultArgument(), clang::TemplateTemplateParmDecl::setDefaultArgument(), and clang::TemplateTypeParmDecl::setDefaultArgument().
setInherited()
template<typename ParmDecl , typename ArgType > void clang::DefaultArgStorage< ParmDecl, ArgType >::setInherited (const ASTContext & C, ParmDecl * InheritedFrom) inline
Set that the default argument was inherited from another parameter.
Definition at line 373 of file DeclTemplate.h.
References clang::allocateDefaultArgStorageChain(), clang::C, clang::DefaultArgStorage< ParmDecl, ArgType >::get(), clang::DefaultArgStorage< ParmDecl, ArgType >::isInherited(), and clang::DefaultArgStorage< ParmDecl, ArgType >::isSet().
Referenced by clang::NonTypeTemplateParmDecl::setInheritedDefaultArgument(), clang::TemplateTemplateParmDecl::setInheritedDefaultArgument(), and clang::TemplateTypeParmDecl::setInheritedDefaultArgument().
The documentation for this class was generated from the following file:
include/clang/AST/DeclTemplate.h