clang: clang::DeclAccessPair Class Reference
clang::DeclAccessPair Class Reference
A POD class for pairing a NamedDecl* with an access specifier.
#include "clang/AST/DeclAccessPair.h"
Public Member Functions
NamedDecl * getDecl () const
AccessSpecifier getAccess () const
void setDecl (NamedDecl *D)
void setAccess (AccessSpecifier AS)
void set (NamedDecl *D, AccessSpecifier AS)
operator NamedDecl * () const
NamedDecl * operator-> () const
Static Public Member Functions
static DeclAccessPair make (NamedDecl *D, AccessSpecifier AS)
Detailed Description
A POD class for pairing a NamedDecl* with an access specifier.
Can be put into unions.
Definition at line 29 of file DeclAccessPair.h.
Member Function Documentation
getAccess()
AccessSpecifier clang::DeclAccessPair::getAccess () const inline
Definition at line 44 of file DeclAccessPair.h.
Referenced by clang::Sema::CheckAddressOfMemberAccess(), clang::Sema::CheckAllocationAccess(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckMemberAccess(), checkMemberDecomposition(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckUnresolvedLookupAccess(), clang::Sema::CheckUnresolvedMemberAccess(), clang::Sema::isMemberAccessibleForDeletion(), setDecl(), and clang::ASTNodeImporter::VisitMemberExpr().
getDecl()
NamedDecl * clang::DeclAccessPair::getDecl () const inline
Definition at line 41 of file DeclAccessPair.h.
Referenced by clang::Sema::CheckConstructorAccess(), checkMemberDecomposition(), clang::Sema::FixOverloadedFunctionReference(), clang::isBetterOverloadCandidate(), clang::Sema::LookupSpecialMember(), operator NamedDecl *(), operator->(), PerformConstructorInitialization(), setAccess(), and clang::ASTNodeImporter::VisitMemberExpr().
make()
static DeclAccessPair clang::DeclAccessPair::make (NamedDecl * D, AccessSpecifier AS) inline static
Definition at line 35 of file DeclAccessPair.h.
References set().
Referenced by clang::Sema::ActOnCXXDelete(), clang::Sema::AddArgumentDependentLookupCandidates(), clang::Sema::AddBuiltinCandidate(), clang::ASTUnresolvedSet::addDecl(), clang::UnresolvedSetImpl::addDecl(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckDestructorAccess(), clang::Sema::CheckFriendAccess(), checkMemberDecomposition(), clang::Sema::CheckVarTemplateId(), clang::MemberExpr::CreateImplicit(), clang::Sema::DiagnoseEmptyLookup(), clang::Sema::FindAllocationFunctions(), findDecomposableBaseClass(), clang::getConstructorInfo(), clang::MemberExpr::getFoundDecl(), getPatternForClassTemplateSpecialization(), clang::Sema::HandleDependentAccessCheck(), clang::Sema::IsSimplyAccessible(), clang::Sema::LookupSpecialMember(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::ProduceCallSignatureHelp(), clang::Sema::ProduceConstructorSignatureHelp(), clang::TreeTransform< Derived >::RebuildMemberExpr(), clang::TemplateDeclInstantiator::SubstDefaultedFunction(), TryTypoCorrectionForCall(), clang::ASTDeclReader::VisitFunctionDecl(), and clang::ASTNodeImporter::VisitMemberExpr().
operator NamedDecl *()
clang::DeclAccessPair::operator NamedDecl * () const inline
Definition at line 58 of file DeclAccessPair.h.
References getDecl().
operator->()
NamedDecl * clang::DeclAccessPair::operator-> () const inline
Definition at line 59 of file DeclAccessPair.h.
References getDecl().
set()
void clang::DeclAccessPair::set (NamedDecl * D, AccessSpecifier AS) inline
Definition at line 54 of file DeclAccessPair.h.
Referenced by make(), setAccess(), and setDecl().
setAccess()
void clang::DeclAccessPair::setAccess (AccessSpecifier AS) inline
Definition at line 51 of file DeclAccessPair.h.
References getDecl(), and set().
setDecl()
void clang::DeclAccessPair::setDecl (NamedDecl * D) inline
Definition at line 48 of file DeclAccessPair.h.
References getAccess(), and set().
The documentation for this class was generated from the following file:
include/clang/AST/DeclAccessPair.h