clang: clang::RecursiveASTVisitor< Derived > Class Template Reference
clang::RecursiveASTVisitor< Derived > Class Template Reference
A class that does preorder or postorder depth-first traversal on the entire Clang AST and visits each node.
#include "clang/AST/RecursiveASTVisitor.h"
Public Types
typedef SmallVectorImpl< llvm::PointerIntPair< Stmt *, 1, bool > > DataRecursionQueue
A queue used for performing data recursion over statements.
Public Member Functions
Derived & getDerived ()
Return a reference to the derived class.
bool shouldVisitTemplateInstantiations () const
Return whether this visitor should recurse into template instantiations.
bool shouldWalkTypesOfTypeLocs () const
Return whether this visitor should recurse into the types of TypeLocs.
bool shouldVisitImplicitCode () const
Return whether this visitor should recurse into implicit code, e.g., implicit constructors and destructors.
bool shouldVisitLambdaBody () const
Return whether this visitor should recurse into lambda body.
bool shouldTraversePostOrder () const
Return whether this visitor should traverse post-order.
bool TraverseAST (ASTContext &AST)
Recursively visits an entire AST, starting from the top-level Decls in the AST traversal scope (by default, the TranslationUnitDecl).
bool TraverseStmt (Stmt *S, DataRecursionQueue *Queue=nullptr)
Recursively visit a statement or expression, by dispatching to Traverse*() based on the argument's dynamic type.
bool dataTraverseStmtPre (Stmt *S)
Invoked before visiting a statement or expression via data recursion.
bool dataTraverseStmtPost (Stmt *S)
Invoked after visiting a statement or expression via data recursion.
bool TraverseType (QualType T)
Recursively visit a type, by dispatching to Traverse*Type() based on the argument's getTypeClass() property.
bool TraverseTypeLoc (TypeLoc TL)
Recursively visit a type with location, by dispatching to Traverse*TypeLoc() based on the argument type's getTypeClass() property.
bool TraverseAttr (Attr *At)
Recursively visit an attribute, by dispatching to Traverse*Attr() based on the argument's dynamic type.
bool TraverseDecl (Decl *D)
Recursively visit a declaration, by dispatching to Traverse*Decl() based on the argument's dynamic type.
bool TraverseNestedNameSpecifier (NestedNameSpecifier *NNS)
Recursively visit a C++ nested-name-specifier.
bool TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Recursively visit a C++ nested-name-specifier with location information.
bool TraverseDeclarationNameInfo (DeclarationNameInfo NameInfo)
Recursively visit a name with its location information.
bool TraverseTemplateName (TemplateName Template)
Recursively visit a template name and dispatch to the appropriate method.
bool TraverseTemplateArgument (const TemplateArgument &Arg)
Recursively visit a template argument and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArgumentLoc (const TemplateArgumentLoc &ArgLoc)
Recursively visit a template argument location and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArguments (const TemplateArgument *Args, unsigned NumArgs)
Recursively visit a set of template arguments.
bool TraverseCXXBaseSpecifier (const CXXBaseSpecifier &Base)
Recursively visit a base specifier.
bool TraverseConstructorInitializer (CXXCtorInitializer *Init)
Recursively visit a constructor initializer.
bool TraverseLambdaCapture (LambdaExpr *LE, const LambdaCapture *C, Expr *Init)
Recursively visit a lambda capture.
bool TraverseSynOrSemInitListExpr (InitListExpr *S, DataRecursionQueue *Queue=nullptr)
Recursively visit the syntactic or semantic form of an initialization list.
bool TraverseConceptReference (const ConceptReference &C)
Recursively visit a reference to a concept with potential arguments.
bool VisitAttr (Attr *A)
bool TraverseAArch64VectorPcsAttr (AArch64VectorPcsAttr *A)
bool VisitAArch64VectorPcsAttr (AArch64VectorPcsAttr *A)
bool TraverseAMDGPUFlatWorkGroupSizeAttr (AMDGPUFlatWorkGroupSizeAttr *A)
bool VisitAMDGPUFlatWorkGroupSizeAttr (AMDGPUFlatWorkGroupSizeAttr *A)
bool TraverseAMDGPUNumSGPRAttr (AMDGPUNumSGPRAttr *A)
bool VisitAMDGPUNumSGPRAttr (AMDGPUNumSGPRAttr *A)
bool TraverseAMDGPUNumVGPRAttr (AMDGPUNumVGPRAttr *A)
bool VisitAMDGPUNumVGPRAttr (AMDGPUNumVGPRAttr *A)
bool TraverseAMDGPUWavesPerEUAttr (AMDGPUWavesPerEUAttr *A)
bool VisitAMDGPUWavesPerEUAttr (AMDGPUWavesPerEUAttr *A)
bool TraverseARMInterruptAttr (ARMInterruptAttr *A)
bool VisitARMInterruptAttr (ARMInterruptAttr *A)
bool TraverseAVRInterruptAttr (AVRInterruptAttr *A)
bool VisitAVRInterruptAttr (AVRInterruptAttr *A)
bool TraverseAVRSignalAttr (AVRSignalAttr *A)
bool VisitAVRSignalAttr (AVRSignalAttr *A)
bool TraverseAbiTagAttr (AbiTagAttr *A)
bool VisitAbiTagAttr (AbiTagAttr *A)
bool TraverseAcquireCapabilityAttr (AcquireCapabilityAttr *A)
bool VisitAcquireCapabilityAttr (AcquireCapabilityAttr *A)
bool TraverseAcquireHandleAttr (AcquireHandleAttr *A)
bool VisitAcquireHandleAttr (AcquireHandleAttr *A)
bool TraverseAcquiredAfterAttr (AcquiredAfterAttr *A)
bool VisitAcquiredAfterAttr (AcquiredAfterAttr *A)
bool TraverseAcquiredBeforeAttr (AcquiredBeforeAttr *A)
bool VisitAcquiredBeforeAttr (AcquiredBeforeAttr *A)
bool TraverseAddressSpaceAttr (AddressSpaceAttr *A)
bool VisitAddressSpaceAttr (AddressSpaceAttr *A)
bool TraverseAliasAttr (AliasAttr *A)
bool VisitAliasAttr (AliasAttr *A)
bool TraverseAlignMac68kAttr (AlignMac68kAttr *A)
bool VisitAlignMac68kAttr (AlignMac68kAttr *A)
bool TraverseAlignNaturalAttr (AlignNaturalAttr *A)
bool VisitAlignNaturalAttr (AlignNaturalAttr *A)
bool TraverseAlignValueAttr (AlignValueAttr *A)
bool VisitAlignValueAttr (AlignValueAttr *A)
bool TraverseAlignedAttr (AlignedAttr *A)
bool VisitAlignedAttr (AlignedAttr *A)
bool TraverseAllocAlignAttr (AllocAlignAttr *A)
bool VisitAllocAlignAttr (AllocAlignAttr *A)
bool TraverseAllocSizeAttr (AllocSizeAttr *A)
bool VisitAllocSizeAttr (AllocSizeAttr *A)
bool TraverseAlwaysDestroyAttr (AlwaysDestroyAttr *A)
bool VisitAlwaysDestroyAttr (AlwaysDestroyAttr *A)
bool TraverseAlwaysInlineAttr (AlwaysInlineAttr *A)
bool VisitAlwaysInlineAttr (AlwaysInlineAttr *A)
bool TraverseAnalyzerNoReturnAttr (AnalyzerNoReturnAttr *A)
bool VisitAnalyzerNoReturnAttr (AnalyzerNoReturnAttr *A)
bool TraverseAnnotateAttr (AnnotateAttr *A)
bool VisitAnnotateAttr (AnnotateAttr *A)
bool TraverseAnyX86InterruptAttr (AnyX86InterruptAttr *A)
bool VisitAnyX86InterruptAttr (AnyX86InterruptAttr *A)
bool TraverseAnyX86NoCallerSavedRegistersAttr (AnyX86NoCallerSavedRegistersAttr *A)
bool VisitAnyX86NoCallerSavedRegistersAttr (AnyX86NoCallerSavedRegistersAttr *A)
bool TraverseAnyX86NoCfCheckAttr (AnyX86NoCfCheckAttr *A)
bool VisitAnyX86NoCfCheckAttr (AnyX86NoCfCheckAttr *A)
bool TraverseArcWeakrefUnavailableAttr (ArcWeakrefUnavailableAttr *A)
bool VisitArcWeakrefUnavailableAttr (ArcWeakrefUnavailableAttr *A)
bool TraverseArgumentWithTypeTagAttr (ArgumentWithTypeTagAttr *A)
bool VisitArgumentWithTypeTagAttr (ArgumentWithTypeTagAttr *A)
bool TraverseArmBuiltinAliasAttr (ArmBuiltinAliasAttr *A)
bool VisitArmBuiltinAliasAttr (ArmBuiltinAliasAttr *A)
bool TraverseArmMveStrictPolymorphismAttr (ArmMveStrictPolymorphismAttr *A)
bool VisitArmMveStrictPolymorphismAttr (ArmMveStrictPolymorphismAttr *A)
bool TraverseArtificialAttr (ArtificialAttr *A)
bool VisitArtificialAttr (ArtificialAttr *A)
bool TraverseAsmLabelAttr (AsmLabelAttr *A)
bool VisitAsmLabelAttr (AsmLabelAttr *A)
bool TraverseAssertCapabilityAttr (AssertCapabilityAttr *A)
bool VisitAssertCapabilityAttr (AssertCapabilityAttr *A)
bool TraverseAssertExclusiveLockAttr (AssertExclusiveLockAttr *A)
bool VisitAssertExclusiveLockAttr (AssertExclusiveLockAttr *A)
bool TraverseAssertSharedLockAttr (AssertSharedLockAttr *A)
bool VisitAssertSharedLockAttr (AssertSharedLockAttr *A)
bool TraverseAssumeAlignedAttr (AssumeAlignedAttr *A)
bool VisitAssumeAlignedAttr (AssumeAlignedAttr *A)
bool TraverseAssumptionAttr (AssumptionAttr *A)
bool VisitAssumptionAttr (AssumptionAttr *A)
bool TraverseAvailabilityAttr (AvailabilityAttr *A)
bool VisitAvailabilityAttr (AvailabilityAttr *A)
bool TraverseBPFPreserveAccessIndexAttr (BPFPreserveAccessIndexAttr *A)
bool VisitBPFPreserveAccessIndexAttr (BPFPreserveAccessIndexAttr *A)
bool TraverseBlocksAttr (BlocksAttr *A)
bool VisitBlocksAttr (BlocksAttr *A)
bool TraverseBuiltinAttr (BuiltinAttr *A)
bool VisitBuiltinAttr (BuiltinAttr *A)
bool TraverseC11NoReturnAttr (C11NoReturnAttr *A)
bool VisitC11NoReturnAttr (C11NoReturnAttr *A)
bool TraverseCDeclAttr (CDeclAttr *A)
bool VisitCDeclAttr (CDeclAttr *A)
bool TraverseCFAuditedTransferAttr (CFAuditedTransferAttr *A)
bool VisitCFAuditedTransferAttr (CFAuditedTransferAttr *A)
bool TraverseCFConsumedAttr (CFConsumedAttr *A)
bool VisitCFConsumedAttr (CFConsumedAttr *A)
bool TraverseCFGuardAttr (CFGuardAttr *A)
bool VisitCFGuardAttr (CFGuardAttr *A)
bool TraverseCFICanonicalJumpTableAttr (CFICanonicalJumpTableAttr *A)
bool VisitCFICanonicalJumpTableAttr (CFICanonicalJumpTableAttr *A)
bool TraverseCFReturnsNotRetainedAttr (CFReturnsNotRetainedAttr *A)
bool VisitCFReturnsNotRetainedAttr (CFReturnsNotRetainedAttr *A)
bool TraverseCFReturnsRetainedAttr (CFReturnsRetainedAttr *A)
bool VisitCFReturnsRetainedAttr (CFReturnsRetainedAttr *A)
bool TraverseCFUnknownTransferAttr (CFUnknownTransferAttr *A)
bool VisitCFUnknownTransferAttr (CFUnknownTransferAttr *A)
bool TraverseCPUDispatchAttr (CPUDispatchAttr *A)
bool VisitCPUDispatchAttr (CPUDispatchAttr *A)
bool TraverseCPUSpecificAttr (CPUSpecificAttr *A)
bool VisitCPUSpecificAttr (CPUSpecificAttr *A)
bool TraverseCUDAConstantAttr (CUDAConstantAttr *A)
bool VisitCUDAConstantAttr (CUDAConstantAttr *A)
bool TraverseCUDADeviceAttr (CUDADeviceAttr *A)
bool VisitCUDADeviceAttr (CUDADeviceAttr *A)
bool TraverseCUDADeviceBuiltinSurfaceTypeAttr (CUDADeviceBuiltinSurfaceTypeAttr *A)
bool VisitCUDADeviceBuiltinSurfaceTypeAttr (CUDADeviceBuiltinSurfaceTypeAttr *A)
bool TraverseCUDADeviceBuiltinTextureTypeAttr (CUDADeviceBuiltinTextureTypeAttr *A)
bool VisitCUDADeviceBuiltinTextureTypeAttr (CUDADeviceBuiltinTextureTypeAttr *A)
bool TraverseCUDAGlobalAttr (CUDAGlobalAttr *A)
bool VisitCUDAGlobalAttr (CUDAGlobalAttr *A)
bool TraverseCUDAHostAttr (CUDAHostAttr *A)
bool VisitCUDAHostAttr (CUDAHostAttr *A)
bool TraverseCUDAInvalidTargetAttr (CUDAInvalidTargetAttr *A)
bool VisitCUDAInvalidTargetAttr (CUDAInvalidTargetAttr *A)
bool TraverseCUDALaunchBoundsAttr (CUDALaunchBoundsAttr *A)
bool VisitCUDALaunchBoundsAttr (CUDALaunchBoundsAttr *A)
bool TraverseCUDASharedAttr (CUDASharedAttr *A)
bool VisitCUDASharedAttr (CUDASharedAttr *A)
bool TraverseCXX11NoReturnAttr (CXX11NoReturnAttr *A)
bool VisitCXX11NoReturnAttr (CXX11NoReturnAttr *A)
bool TraverseCallableWhenAttr (CallableWhenAttr *A)
bool VisitCallableWhenAttr (CallableWhenAttr *A)
bool TraverseCallbackAttr (CallbackAttr *A)
bool VisitCallbackAttr (CallbackAttr *A)
bool TraverseCalledOnceAttr (CalledOnceAttr *A)
bool VisitCalledOnceAttr (CalledOnceAttr *A)
bool TraverseCapabilityAttr (CapabilityAttr *A)
bool VisitCapabilityAttr (CapabilityAttr *A)
bool TraverseCapturedRecordAttr (CapturedRecordAttr *A)
bool VisitCapturedRecordAttr (CapturedRecordAttr *A)
bool TraverseCarriesDependencyAttr (CarriesDependencyAttr *A)
bool VisitCarriesDependencyAttr (CarriesDependencyAttr *A)
bool TraverseCleanupAttr (CleanupAttr *A)
bool VisitCleanupAttr (CleanupAttr *A)
bool TraverseCmseNSCallAttr (CmseNSCallAttr *A)
bool VisitCmseNSCallAttr (CmseNSCallAttr *A)
bool TraverseCmseNSEntryAttr (CmseNSEntryAttr *A)
bool VisitCmseNSEntryAttr (CmseNSEntryAttr *A)
bool TraverseCodeSegAttr (CodeSegAttr *A)
bool VisitCodeSegAttr (CodeSegAttr *A)
bool TraverseColdAttr (ColdAttr *A)
bool VisitColdAttr (ColdAttr *A)
bool TraverseCommonAttr (CommonAttr *A)
bool VisitCommonAttr (CommonAttr *A)
bool TraverseConstAttr (ConstAttr *A)
bool VisitConstAttr (ConstAttr *A)
bool TraverseConstInitAttr (ConstInitAttr *A)
bool VisitConstInitAttr (ConstInitAttr *A)
bool TraverseConstructorAttr (ConstructorAttr *A)
bool VisitConstructorAttr (ConstructorAttr *A)
bool TraverseConsumableAttr (ConsumableAttr *A)
bool VisitConsumableAttr (ConsumableAttr *A)
bool TraverseConsumableAutoCastAttr (ConsumableAutoCastAttr *A)
bool VisitConsumableAutoCastAttr (ConsumableAutoCastAttr *A)
bool TraverseConsumableSetOnReadAttr (ConsumableSetOnReadAttr *A)
bool VisitConsumableSetOnReadAttr (ConsumableSetOnReadAttr *A)
bool TraverseConvergentAttr (ConvergentAttr *A)
bool VisitConvergentAttr (ConvergentAttr *A)
bool TraverseDLLExportAttr (DLLExportAttr *A)
bool VisitDLLExportAttr (DLLExportAttr *A)
bool TraverseDLLExportStaticLocalAttr (DLLExportStaticLocalAttr *A)
bool VisitDLLExportStaticLocalAttr (DLLExportStaticLocalAttr *A)
bool TraverseDLLImportAttr (DLLImportAttr *A)
bool VisitDLLImportAttr (DLLImportAttr *A)
bool TraverseDLLImportStaticLocalAttr (DLLImportStaticLocalAttr *A)
bool VisitDLLImportStaticLocalAttr (DLLImportStaticLocalAttr *A)
bool TraverseDeprecatedAttr (DeprecatedAttr *A)
bool VisitDeprecatedAttr (DeprecatedAttr *A)
bool TraverseDestructorAttr (DestructorAttr *A)
bool VisitDestructorAttr (DestructorAttr *A)
bool TraverseDiagnoseIfAttr (DiagnoseIfAttr *A)
bool VisitDiagnoseIfAttr (DiagnoseIfAttr *A)
bool TraverseDisableTailCallsAttr (DisableTailCallsAttr *A)
bool VisitDisableTailCallsAttr (DisableTailCallsAttr *A)
bool TraverseEmptyBasesAttr (EmptyBasesAttr *A)
bool VisitEmptyBasesAttr (EmptyBasesAttr *A)
bool TraverseEnableIfAttr (EnableIfAttr *A)
bool VisitEnableIfAttr (EnableIfAttr *A)
bool TraverseEnforceTCBAttr (EnforceTCBAttr *A)
bool VisitEnforceTCBAttr (EnforceTCBAttr *A)
bool TraverseEnforceTCBLeafAttr (EnforceTCBLeafAttr *A)
bool VisitEnforceTCBLeafAttr (EnforceTCBLeafAttr *A)
bool TraverseEnumExtensibilityAttr (EnumExtensibilityAttr *A)
bool VisitEnumExtensibilityAttr (EnumExtensibilityAttr *A)
bool TraverseExcludeFromExplicitInstantiationAttr (ExcludeFromExplicitInstantiationAttr *A)
bool VisitExcludeFromExplicitInstantiationAttr (ExcludeFromExplicitInstantiationAttr *A)
bool TraverseExclusiveTrylockFunctionAttr (ExclusiveTrylockFunctionAttr *A)
bool VisitExclusiveTrylockFunctionAttr (ExclusiveTrylockFunctionAttr *A)
bool TraverseExternalSourceSymbolAttr (ExternalSourceSymbolAttr *A)
bool VisitExternalSourceSymbolAttr (ExternalSourceSymbolAttr *A)
bool TraverseFallThroughAttr (FallThroughAttr *A)
bool VisitFallThroughAttr (FallThroughAttr *A)
bool TraverseFastCallAttr (FastCallAttr *A)
bool VisitFastCallAttr (FastCallAttr *A)
bool TraverseFinalAttr (FinalAttr *A)
bool VisitFinalAttr (FinalAttr *A)
bool TraverseFlagEnumAttr (FlagEnumAttr *A)
bool VisitFlagEnumAttr (FlagEnumAttr *A)
bool TraverseFlattenAttr (FlattenAttr *A)
bool VisitFlattenAttr (FlattenAttr *A)
bool TraverseFormatAttr (FormatAttr *A)
bool VisitFormatAttr (FormatAttr *A)
bool TraverseFormatArgAttr (FormatArgAttr *A)
bool VisitFormatArgAttr (FormatArgAttr *A)
bool TraverseGNUInlineAttr (GNUInlineAttr *A)
bool VisitGNUInlineAttr (GNUInlineAttr *A)
bool TraverseGuardedByAttr (GuardedByAttr *A)
bool VisitGuardedByAttr (GuardedByAttr *A)
bool TraverseGuardedVarAttr (GuardedVarAttr *A)
bool VisitGuardedVarAttr (GuardedVarAttr *A)
bool TraverseHIPManagedAttr (HIPManagedAttr *A)
bool VisitHIPManagedAttr (HIPManagedAttr *A)
bool TraverseHotAttr (HotAttr *A)
bool VisitHotAttr (HotAttr *A)
bool TraverseIBActionAttr (IBActionAttr *A)
bool VisitIBActionAttr (IBActionAttr *A)
bool TraverseIBOutletAttr (IBOutletAttr *A)
bool VisitIBOutletAttr (IBOutletAttr *A)
bool TraverseIBOutletCollectionAttr (IBOutletCollectionAttr *A)
bool VisitIBOutletCollectionAttr (IBOutletCollectionAttr *A)
bool TraverseIFuncAttr (IFuncAttr *A)
bool VisitIFuncAttr (IFuncAttr *A)
bool TraverseInitPriorityAttr (InitPriorityAttr *A)
bool VisitInitPriorityAttr (InitPriorityAttr *A)
bool TraverseInitSegAttr (InitSegAttr *A)
bool VisitInitSegAttr (InitSegAttr *A)
bool TraverseIntelOclBiccAttr (IntelOclBiccAttr *A)
bool VisitIntelOclBiccAttr (IntelOclBiccAttr *A)
bool TraverseInternalLinkageAttr (InternalLinkageAttr *A)
bool VisitInternalLinkageAttr (InternalLinkageAttr *A)
bool TraverseLTOVisibilityPublicAttr (LTOVisibilityPublicAttr *A)
bool VisitLTOVisibilityPublicAttr (LTOVisibilityPublicAttr *A)
bool TraverseLayoutVersionAttr (LayoutVersionAttr *A)
bool VisitLayoutVersionAttr (LayoutVersionAttr *A)
bool TraverseLeafAttr (LeafAttr *A)
bool VisitLeafAttr (LeafAttr *A)
bool TraverseLifetimeBoundAttr (LifetimeBoundAttr *A)
bool VisitLifetimeBoundAttr (LifetimeBoundAttr *A)
bool TraverseLikelyAttr (LikelyAttr *A)
bool VisitLikelyAttr (LikelyAttr *A)
bool TraverseLoaderUninitializedAttr (LoaderUninitializedAttr *A)
bool VisitLoaderUninitializedAttr (LoaderUninitializedAttr *A)
bool TraverseLockReturnedAttr (LockReturnedAttr *A)
bool VisitLockReturnedAttr (LockReturnedAttr *A)
bool TraverseLocksExcludedAttr (LocksExcludedAttr *A)
bool VisitLocksExcludedAttr (LocksExcludedAttr *A)
bool TraverseLoopHintAttr (LoopHintAttr *A)
bool VisitLoopHintAttr (LoopHintAttr *A)
bool TraverseMIGServerRoutineAttr (MIGServerRoutineAttr *A)
bool VisitMIGServerRoutineAttr (MIGServerRoutineAttr *A)
bool TraverseMSABIAttr (MSABIAttr *A)
bool VisitMSABIAttr (MSABIAttr *A)
bool TraverseMSAllocatorAttr (MSAllocatorAttr *A)
bool VisitMSAllocatorAttr (MSAllocatorAttr *A)
bool TraverseMSInheritanceAttr (MSInheritanceAttr *A)
bool VisitMSInheritanceAttr (MSInheritanceAttr *A)
bool TraverseMSNoVTableAttr (MSNoVTableAttr *A)
bool VisitMSNoVTableAttr (MSNoVTableAttr *A)
bool TraverseMSP430InterruptAttr (MSP430InterruptAttr *A)
bool VisitMSP430InterruptAttr (MSP430InterruptAttr *A)
bool TraverseMSStructAttr (MSStructAttr *A)
bool VisitMSStructAttr (MSStructAttr *A)
bool TraverseMSVtorDispAttr (MSVtorDispAttr *A)
bool VisitMSVtorDispAttr (MSVtorDispAttr *A)
bool TraverseMaxFieldAlignmentAttr (MaxFieldAlignmentAttr *A)
bool VisitMaxFieldAlignmentAttr (MaxFieldAlignmentAttr *A)
bool TraverseMayAliasAttr (MayAliasAttr *A)
bool VisitMayAliasAttr (MayAliasAttr *A)
bool TraverseMicroMipsAttr (MicroMipsAttr *A)
bool VisitMicroMipsAttr (MicroMipsAttr *A)
bool TraverseMinSizeAttr (MinSizeAttr *A)
bool VisitMinSizeAttr (MinSizeAttr *A)
bool TraverseMinVectorWidthAttr (MinVectorWidthAttr *A)
bool VisitMinVectorWidthAttr (MinVectorWidthAttr *A)
bool TraverseMips16Attr (Mips16Attr *A)
bool VisitMips16Attr (Mips16Attr *A)
bool TraverseMipsInterruptAttr (MipsInterruptAttr *A)
bool VisitMipsInterruptAttr (MipsInterruptAttr *A)
bool TraverseMipsLongCallAttr (MipsLongCallAttr *A)
bool VisitMipsLongCallAttr (MipsLongCallAttr *A)
bool TraverseMipsShortCallAttr (MipsShortCallAttr *A)
bool VisitMipsShortCallAttr (MipsShortCallAttr *A)
bool TraverseModeAttr (ModeAttr *A)
bool VisitModeAttr (ModeAttr *A)
bool TraverseNSConsumedAttr (NSConsumedAttr *A)
bool VisitNSConsumedAttr (NSConsumedAttr *A)
bool TraverseNSConsumesSelfAttr (NSConsumesSelfAttr *A)
bool VisitNSConsumesSelfAttr (NSConsumesSelfAttr *A)
bool TraverseNSErrorDomainAttr (NSErrorDomainAttr *A)
bool VisitNSErrorDomainAttr (NSErrorDomainAttr *A)
bool TraverseNSReturnsAutoreleasedAttr (NSReturnsAutoreleasedAttr *A)
bool VisitNSReturnsAutoreleasedAttr (NSReturnsAutoreleasedAttr *A)
bool TraverseNSReturnsNotRetainedAttr (NSReturnsNotRetainedAttr *A)
bool VisitNSReturnsNotRetainedAttr (NSReturnsNotRetainedAttr *A)
bool TraverseNSReturnsRetainedAttr (NSReturnsRetainedAttr *A)
bool VisitNSReturnsRetainedAttr (NSReturnsRetainedAttr *A)
bool TraverseNakedAttr (NakedAttr *A)
bool VisitNakedAttr (NakedAttr *A)
bool TraverseNoAliasAttr (NoAliasAttr *A)
bool VisitNoAliasAttr (NoAliasAttr *A)
bool TraverseNoBuiltinAttr (NoBuiltinAttr *A)
bool VisitNoBuiltinAttr (NoBuiltinAttr *A)
bool TraverseNoCommonAttr (NoCommonAttr *A)
bool VisitNoCommonAttr (NoCommonAttr *A)
bool TraverseNoDebugAttr (NoDebugAttr *A)
bool VisitNoDebugAttr (NoDebugAttr *A)
bool TraverseNoDerefAttr (NoDerefAttr *A)
bool VisitNoDerefAttr (NoDerefAttr *A)
bool TraverseNoDestroyAttr (NoDestroyAttr *A)
bool VisitNoDestroyAttr (NoDestroyAttr *A)
bool TraverseNoDuplicateAttr (NoDuplicateAttr *A)
bool VisitNoDuplicateAttr (NoDuplicateAttr *A)
bool TraverseNoEscapeAttr (NoEscapeAttr *A)
bool VisitNoEscapeAttr (NoEscapeAttr *A)
bool TraverseNoInlineAttr (NoInlineAttr *A)
bool VisitNoInlineAttr (NoInlineAttr *A)
bool TraverseNoInstrumentFunctionAttr (NoInstrumentFunctionAttr *A)
bool VisitNoInstrumentFunctionAttr (NoInstrumentFunctionAttr *A)
bool TraverseNoMergeAttr (NoMergeAttr *A)
bool VisitNoMergeAttr (NoMergeAttr *A)
bool TraverseNoMicroMipsAttr (NoMicroMipsAttr *A)
bool VisitNoMicroMipsAttr (NoMicroMipsAttr *A)
bool TraverseNoMips16Attr (NoMips16Attr *A)
bool VisitNoMips16Attr (NoMips16Attr *A)
bool TraverseNoReturnAttr (NoReturnAttr *A)
bool VisitNoReturnAttr (NoReturnAttr *A)
bool TraverseNoSanitizeAttr (NoSanitizeAttr *A)
bool VisitNoSanitizeAttr (NoSanitizeAttr *A)
bool TraverseNoSpeculativeLoadHardeningAttr (NoSpeculativeLoadHardeningAttr *A)
bool VisitNoSpeculativeLoadHardeningAttr (NoSpeculativeLoadHardeningAttr *A)
bool TraverseNoSplitStackAttr (NoSplitStackAttr *A)
bool VisitNoSplitStackAttr (NoSplitStackAttr *A)
bool TraverseNoStackProtectorAttr (NoStackProtectorAttr *A)
bool VisitNoStackProtectorAttr (NoStackProtectorAttr *A)
bool TraverseNoThreadSafetyAnalysisAttr (NoThreadSafetyAnalysisAttr *A)
bool VisitNoThreadSafetyAnalysisAttr (NoThreadSafetyAnalysisAttr *A)
bool TraverseNoThrowAttr (NoThrowAttr *A)
bool VisitNoThrowAttr (NoThrowAttr *A)
bool TraverseNoUniqueAddressAttr (NoUniqueAddressAttr *A)
bool VisitNoUniqueAddressAttr (NoUniqueAddressAttr *A)
bool TraverseNonNullAttr (NonNullAttr *A)
bool VisitNonNullAttr (NonNullAttr *A)
bool TraverseNotTailCalledAttr (NotTailCalledAttr *A)
bool VisitNotTailCalledAttr (NotTailCalledAttr *A)
bool TraverseOMPAllocateDeclAttr (OMPAllocateDeclAttr *A)
bool VisitOMPAllocateDeclAttr (OMPAllocateDeclAttr *A)
bool TraverseOMPCaptureKindAttr (OMPCaptureKindAttr *A)
bool VisitOMPCaptureKindAttr (OMPCaptureKindAttr *A)
bool TraverseOMPCaptureNoInitAttr (OMPCaptureNoInitAttr *A)
bool VisitOMPCaptureNoInitAttr (OMPCaptureNoInitAttr *A)
bool TraverseOMPDeclareSimdDeclAttr (OMPDeclareSimdDeclAttr *A)
bool VisitOMPDeclareSimdDeclAttr (OMPDeclareSimdDeclAttr *A)
bool TraverseOMPDeclareTargetDeclAttr (OMPDeclareTargetDeclAttr *A)
bool VisitOMPDeclareTargetDeclAttr (OMPDeclareTargetDeclAttr *A)
bool TraverseOMPDeclareVariantAttr (OMPDeclareVariantAttr *A)
bool VisitOMPDeclareVariantAttr (OMPDeclareVariantAttr *A)
bool TraverseOMPReferencedVarAttr (OMPReferencedVarAttr *A)
bool VisitOMPReferencedVarAttr (OMPReferencedVarAttr *A)
bool TraverseOMPThreadPrivateDeclAttr (OMPThreadPrivateDeclAttr *A)
bool VisitOMPThreadPrivateDeclAttr (OMPThreadPrivateDeclAttr *A)
bool TraverseOSConsumedAttr (OSConsumedAttr *A)
bool VisitOSConsumedAttr (OSConsumedAttr *A)
bool TraverseOSConsumesThisAttr (OSConsumesThisAttr *A)
bool VisitOSConsumesThisAttr (OSConsumesThisAttr *A)
bool TraverseOSReturnsNotRetainedAttr (OSReturnsNotRetainedAttr *A)
bool VisitOSReturnsNotRetainedAttr (OSReturnsNotRetainedAttr *A)
bool TraverseOSReturnsRetainedAttr (OSReturnsRetainedAttr *A)
bool VisitOSReturnsRetainedAttr (OSReturnsRetainedAttr *A)
bool TraverseOSReturnsRetainedOnNonZeroAttr (OSReturnsRetainedOnNonZeroAttr *A)
bool VisitOSReturnsRetainedOnNonZeroAttr (OSReturnsRetainedOnNonZeroAttr *A)
bool TraverseOSReturnsRetainedOnZeroAttr (OSReturnsRetainedOnZeroAttr *A)
bool VisitOSReturnsRetainedOnZeroAttr (OSReturnsRetainedOnZeroAttr *A)
bool TraverseObjCBoxableAttr (ObjCBoxableAttr *A)
bool VisitObjCBoxableAttr (ObjCBoxableAttr *A)
bool TraverseObjCBridgeAttr (ObjCBridgeAttr *A)
bool VisitObjCBridgeAttr (ObjCBridgeAttr *A)
bool TraverseObjCBridgeMutableAttr (ObjCBridgeMutableAttr *A)
bool VisitObjCBridgeMutableAttr (ObjCBridgeMutableAttr *A)
bool TraverseObjCBridgeRelatedAttr (ObjCBridgeRelatedAttr *A)
bool VisitObjCBridgeRelatedAttr (ObjCBridgeRelatedAttr *A)
bool TraverseObjCClassStubAttr (ObjCClassStubAttr *A)
bool VisitObjCClassStubAttr (ObjCClassStubAttr *A)
bool TraverseObjCDesignatedInitializerAttr (ObjCDesignatedInitializerAttr *A)
bool VisitObjCDesignatedInitializerAttr (ObjCDesignatedInitializerAttr *A)
bool TraverseObjCDirectAttr (ObjCDirectAttr *A)
bool VisitObjCDirectAttr (ObjCDirectAttr *A)
bool TraverseObjCDirectMembersAttr (ObjCDirectMembersAttr *A)
bool VisitObjCDirectMembersAttr (ObjCDirectMembersAttr *A)
bool TraverseObjCExceptionAttr (ObjCExceptionAttr *A)
bool VisitObjCExceptionAttr (ObjCExceptionAttr *A)
bool TraverseObjCExplicitProtocolImplAttr (ObjCExplicitProtocolImplAttr *A)
bool VisitObjCExplicitProtocolImplAttr (ObjCExplicitProtocolImplAttr *A)
bool TraverseObjCExternallyRetainedAttr (ObjCExternallyRetainedAttr *A)
bool VisitObjCExternallyRetainedAttr (ObjCExternallyRetainedAttr *A)
bool TraverseObjCGCAttr (ObjCGCAttr *A)
bool VisitObjCGCAttr (ObjCGCAttr *A)
bool TraverseObjCIndependentClassAttr (ObjCIndependentClassAttr *A)
bool VisitObjCIndependentClassAttr (ObjCIndependentClassAttr *A)
bool TraverseObjCInertUnsafeUnretainedAttr (ObjCInertUnsafeUnretainedAttr *A)
bool VisitObjCInertUnsafeUnretainedAttr (ObjCInertUnsafeUnretainedAttr *A)
bool TraverseObjCKindOfAttr (ObjCKindOfAttr *A)
bool VisitObjCKindOfAttr (ObjCKindOfAttr *A)
bool TraverseObjCMethodFamilyAttr (ObjCMethodFamilyAttr *A)
bool VisitObjCMethodFamilyAttr (ObjCMethodFamilyAttr *A)
bool TraverseObjCNSObjectAttr (ObjCNSObjectAttr *A)
bool VisitObjCNSObjectAttr (ObjCNSObjectAttr *A)
bool TraverseObjCNonLazyClassAttr (ObjCNonLazyClassAttr *A)
bool VisitObjCNonLazyClassAttr (ObjCNonLazyClassAttr *A)
bool TraverseObjCNonRuntimeProtocolAttr (ObjCNonRuntimeProtocolAttr *A)
bool VisitObjCNonRuntimeProtocolAttr (ObjCNonRuntimeProtocolAttr *A)
bool TraverseObjCOwnershipAttr (ObjCOwnershipAttr *A)
bool VisitObjCOwnershipAttr (ObjCOwnershipAttr *A)
bool TraverseObjCPreciseLifetimeAttr (ObjCPreciseLifetimeAttr *A)
bool VisitObjCPreciseLifetimeAttr (ObjCPreciseLifetimeAttr *A)
bool TraverseObjCRequiresPropertyDefsAttr (ObjCRequiresPropertyDefsAttr *A)
bool VisitObjCRequiresPropertyDefsAttr (ObjCRequiresPropertyDefsAttr *A)
bool TraverseObjCRequiresSuperAttr (ObjCRequiresSuperAttr *A)
bool VisitObjCRequiresSuperAttr (ObjCRequiresSuperAttr *A)
bool TraverseObjCReturnsInnerPointerAttr (ObjCReturnsInnerPointerAttr *A)
bool VisitObjCReturnsInnerPointerAttr (ObjCReturnsInnerPointerAttr *A)
bool TraverseObjCRootClassAttr (ObjCRootClassAttr *A)
bool VisitObjCRootClassAttr (ObjCRootClassAttr *A)
bool TraverseObjCRuntimeNameAttr (ObjCRuntimeNameAttr *A)
bool VisitObjCRuntimeNameAttr (ObjCRuntimeNameAttr *A)
bool TraverseObjCRuntimeVisibleAttr (ObjCRuntimeVisibleAttr *A)
bool VisitObjCRuntimeVisibleAttr (ObjCRuntimeVisibleAttr *A)
bool TraverseObjCSubclassingRestrictedAttr (ObjCSubclassingRestrictedAttr *A)
bool VisitObjCSubclassingRestrictedAttr (ObjCSubclassingRestrictedAttr *A)
bool TraverseOpenCLAccessAttr (OpenCLAccessAttr *A)
bool VisitOpenCLAccessAttr (OpenCLAccessAttr *A)
bool TraverseOpenCLConstantAddressSpaceAttr (OpenCLConstantAddressSpaceAttr *A)
bool VisitOpenCLConstantAddressSpaceAttr (OpenCLConstantAddressSpaceAttr *A)
bool TraverseOpenCLGenericAddressSpaceAttr (OpenCLGenericAddressSpaceAttr *A)
bool VisitOpenCLGenericAddressSpaceAttr (OpenCLGenericAddressSpaceAttr *A)
bool TraverseOpenCLGlobalAddressSpaceAttr (OpenCLGlobalAddressSpaceAttr *A)
bool VisitOpenCLGlobalAddressSpaceAttr (OpenCLGlobalAddressSpaceAttr *A)
bool TraverseOpenCLGlobalDeviceAddressSpaceAttr (OpenCLGlobalDeviceAddressSpaceAttr *A)
bool VisitOpenCLGlobalDeviceAddressSpaceAttr (OpenCLGlobalDeviceAddressSpaceAttr *A)
bool TraverseOpenCLGlobalHostAddressSpaceAttr (OpenCLGlobalHostAddressSpaceAttr *A)
bool VisitOpenCLGlobalHostAddressSpaceAttr (OpenCLGlobalHostAddressSpaceAttr *A)
bool TraverseOpenCLIntelReqdSubGroupSizeAttr (OpenCLIntelReqdSubGroupSizeAttr *A)
bool VisitOpenCLIntelReqdSubGroupSizeAttr (OpenCLIntelReqdSubGroupSizeAttr *A)
bool TraverseOpenCLKernelAttr (OpenCLKernelAttr *A)
bool VisitOpenCLKernelAttr (OpenCLKernelAttr *A)
bool TraverseOpenCLLocalAddressSpaceAttr (OpenCLLocalAddressSpaceAttr *A)
bool VisitOpenCLLocalAddressSpaceAttr (OpenCLLocalAddressSpaceAttr *A)
bool TraverseOpenCLPrivateAddressSpaceAttr (OpenCLPrivateAddressSpaceAttr *A)
bool VisitOpenCLPrivateAddressSpaceAttr (OpenCLPrivateAddressSpaceAttr *A)
bool TraverseOpenCLUnrollHintAttr (OpenCLUnrollHintAttr *A)
bool VisitOpenCLUnrollHintAttr (OpenCLUnrollHintAttr *A)
bool TraverseOptimizeNoneAttr (OptimizeNoneAttr *A)
bool VisitOptimizeNoneAttr (OptimizeNoneAttr *A)
bool TraverseOverloadableAttr (OverloadableAttr *A)
bool VisitOverloadableAttr (OverloadableAttr *A)
bool TraverseOverrideAttr (OverrideAttr *A)
bool VisitOverrideAttr (OverrideAttr *A)
bool TraverseOwnerAttr (OwnerAttr *A)
bool VisitOwnerAttr (OwnerAttr *A)
bool TraverseOwnershipAttr (OwnershipAttr *A)
bool VisitOwnershipAttr (OwnershipAttr *A)
bool TraversePackedAttr (PackedAttr *A)
bool VisitPackedAttr (PackedAttr *A)
bool TraverseParamTypestateAttr (ParamTypestateAttr *A)
bool VisitParamTypestateAttr (ParamTypestateAttr *A)
bool TraversePascalAttr (PascalAttr *A)
bool VisitPascalAttr (PascalAttr *A)
bool TraversePassObjectSizeAttr (PassObjectSizeAttr *A)
bool VisitPassObjectSizeAttr (PassObjectSizeAttr *A)
bool TraversePatchableFunctionEntryAttr (PatchableFunctionEntryAttr *A)
bool VisitPatchableFunctionEntryAttr (PatchableFunctionEntryAttr *A)
bool TraversePcsAttr (PcsAttr *A)
bool VisitPcsAttr (PcsAttr *A)
bool TraversePointerAttr (PointerAttr *A)
bool VisitPointerAttr (PointerAttr *A)
bool TraversePragmaClangBSSSectionAttr (PragmaClangBSSSectionAttr *A)
bool VisitPragmaClangBSSSectionAttr (PragmaClangBSSSectionAttr *A)
bool TraversePragmaClangDataSectionAttr (PragmaClangDataSectionAttr *A)
bool VisitPragmaClangDataSectionAttr (PragmaClangDataSectionAttr *A)
bool TraversePragmaClangRelroSectionAttr (PragmaClangRelroSectionAttr *A)
bool VisitPragmaClangRelroSectionAttr (PragmaClangRelroSectionAttr *A)
bool TraversePragmaClangRodataSectionAttr (PragmaClangRodataSectionAttr *A)
bool VisitPragmaClangRodataSectionAttr (PragmaClangRodataSectionAttr *A)
bool TraversePragmaClangTextSectionAttr (PragmaClangTextSectionAttr *A)
bool VisitPragmaClangTextSectionAttr (PragmaClangTextSectionAttr *A)
bool TraversePreferredNameAttr (PreferredNameAttr *A)
bool VisitPreferredNameAttr (PreferredNameAttr *A)
bool TraversePreserveAllAttr (PreserveAllAttr *A)
bool VisitPreserveAllAttr (PreserveAllAttr *A)
bool TraversePreserveMostAttr (PreserveMostAttr *A)
bool VisitPreserveMostAttr (PreserveMostAttr *A)
bool TraversePtGuardedByAttr (PtGuardedByAttr *A)
bool VisitPtGuardedByAttr (PtGuardedByAttr *A)
bool TraversePtGuardedVarAttr (PtGuardedVarAttr *A)
bool VisitPtGuardedVarAttr (PtGuardedVarAttr *A)
bool TraversePtr32Attr (Ptr32Attr *A)
bool VisitPtr32Attr (Ptr32Attr *A)
bool TraversePtr64Attr (Ptr64Attr *A)
bool VisitPtr64Attr (Ptr64Attr *A)
bool TraversePureAttr (PureAttr *A)
bool VisitPureAttr (PureAttr *A)
bool TraverseRISCVInterruptAttr (RISCVInterruptAttr *A)
bool VisitRISCVInterruptAttr (RISCVInterruptAttr *A)
bool TraverseRegCallAttr (RegCallAttr *A)
bool VisitRegCallAttr (RegCallAttr *A)
bool TraverseReinitializesAttr (ReinitializesAttr *A)
bool VisitReinitializesAttr (ReinitializesAttr *A)
bool TraverseReleaseCapabilityAttr (ReleaseCapabilityAttr *A)
bool VisitReleaseCapabilityAttr (ReleaseCapabilityAttr *A)
bool TraverseReleaseHandleAttr (ReleaseHandleAttr *A)
bool VisitReleaseHandleAttr (ReleaseHandleAttr *A)
bool TraverseRenderScriptKernelAttr (RenderScriptKernelAttr *A)
bool VisitRenderScriptKernelAttr (RenderScriptKernelAttr *A)
bool TraverseReqdWorkGroupSizeAttr (ReqdWorkGroupSizeAttr *A)
bool VisitReqdWorkGroupSizeAttr (ReqdWorkGroupSizeAttr *A)
bool TraverseRequiresCapabilityAttr (RequiresCapabilityAttr *A)
bool VisitRequiresCapabilityAttr (RequiresCapabilityAttr *A)
bool TraverseRestrictAttr (RestrictAttr *A)
bool VisitRestrictAttr (RestrictAttr *A)
bool TraverseReturnTypestateAttr (ReturnTypestateAttr *A)
bool VisitReturnTypestateAttr (ReturnTypestateAttr *A)
bool TraverseReturnsNonNullAttr (ReturnsNonNullAttr *A)
bool VisitReturnsNonNullAttr (ReturnsNonNullAttr *A)
bool TraverseReturnsTwiceAttr (ReturnsTwiceAttr *A)
bool VisitReturnsTwiceAttr (ReturnsTwiceAttr *A)
bool TraverseSPtrAttr (SPtrAttr *A)
bool VisitSPtrAttr (SPtrAttr *A)
bool TraverseSYCLKernelAttr (SYCLKernelAttr *A)
bool VisitSYCLKernelAttr (SYCLKernelAttr *A)
bool TraverseScopedLockableAttr (ScopedLockableAttr *A)
bool VisitScopedLockableAttr (ScopedLockableAttr *A)
bool TraverseSectionAttr (SectionAttr *A)
bool VisitSectionAttr (SectionAttr *A)
bool TraverseSelectAnyAttr (SelectAnyAttr *A)
bool VisitSelectAnyAttr (SelectAnyAttr *A)
bool TraverseSentinelAttr (SentinelAttr *A)
bool VisitSentinelAttr (SentinelAttr *A)
bool TraverseSetTypestateAttr (SetTypestateAttr *A)
bool VisitSetTypestateAttr (SetTypestateAttr *A)
bool TraverseSharedTrylockFunctionAttr (SharedTrylockFunctionAttr *A)
bool VisitSharedTrylockFunctionAttr (SharedTrylockFunctionAttr *A)
bool TraverseSpeculativeLoadHardeningAttr (SpeculativeLoadHardeningAttr *A)
bool VisitSpeculativeLoadHardeningAttr (SpeculativeLoadHardeningAttr *A)
bool TraverseStdCallAttr (StdCallAttr *A)
bool VisitStdCallAttr (StdCallAttr *A)
bool TraverseStrictFPAttr (StrictFPAttr *A)
bool VisitStrictFPAttr (StrictFPAttr *A)
bool TraverseSuppressAttr (SuppressAttr *A)
bool VisitSuppressAttr (SuppressAttr *A)
bool TraverseSwiftAsyncAttr (SwiftAsyncAttr *A)
bool VisitSwiftAsyncAttr (SwiftAsyncAttr *A)
bool TraverseSwiftAsyncNameAttr (SwiftAsyncNameAttr *A)
bool VisitSwiftAsyncNameAttr (SwiftAsyncNameAttr *A)
bool TraverseSwiftAttrAttr (SwiftAttrAttr *A)
bool VisitSwiftAttrAttr (SwiftAttrAttr *A)
bool TraverseSwiftBridgeAttr (SwiftBridgeAttr *A)
bool VisitSwiftBridgeAttr (SwiftBridgeAttr *A)
bool TraverseSwiftBridgedTypedefAttr (SwiftBridgedTypedefAttr *A)
bool VisitSwiftBridgedTypedefAttr (SwiftBridgedTypedefAttr *A)
bool TraverseSwiftCallAttr (SwiftCallAttr *A)
bool VisitSwiftCallAttr (SwiftCallAttr *A)
bool TraverseSwiftContextAttr (SwiftContextAttr *A)
bool VisitSwiftContextAttr (SwiftContextAttr *A)
bool TraverseSwiftErrorAttr (SwiftErrorAttr *A)
bool VisitSwiftErrorAttr (SwiftErrorAttr *A)
bool TraverseSwiftErrorResultAttr (SwiftErrorResultAttr *A)
bool VisitSwiftErrorResultAttr (SwiftErrorResultAttr *A)
bool TraverseSwiftIndirectResultAttr (SwiftIndirectResultAttr *A)
bool VisitSwiftIndirectResultAttr (SwiftIndirectResultAttr *A)
bool TraverseSwiftNameAttr (SwiftNameAttr *A)
bool VisitSwiftNameAttr (SwiftNameAttr *A)
bool TraverseSwiftNewTypeAttr (SwiftNewTypeAttr *A)
bool VisitSwiftNewTypeAttr (SwiftNewTypeAttr *A)
bool TraverseSwiftObjCMembersAttr (SwiftObjCMembersAttr *A)
bool VisitSwiftObjCMembersAttr (SwiftObjCMembersAttr *A)
bool TraverseSwiftPrivateAttr (SwiftPrivateAttr *A)
bool VisitSwiftPrivateAttr (SwiftPrivateAttr *A)
bool TraverseSysVABIAttr (SysVABIAttr *A)
bool VisitSysVABIAttr (SysVABIAttr *A)
bool TraverseTLSModelAttr (TLSModelAttr *A)
bool VisitTLSModelAttr (TLSModelAttr *A)
bool TraverseTargetAttr (TargetAttr *A)
bool VisitTargetAttr (TargetAttr *A)
bool TraverseTestTypestateAttr (TestTypestateAttr *A)
bool VisitTestTypestateAttr (TestTypestateAttr *A)
bool TraverseThisCallAttr (ThisCallAttr *A)
bool VisitThisCallAttr (ThisCallAttr *A)
bool TraverseThreadAttr (ThreadAttr *A)
bool VisitThreadAttr (ThreadAttr *A)
bool TraverseTransparentUnionAttr (TransparentUnionAttr *A)
bool VisitTransparentUnionAttr (TransparentUnionAttr *A)
bool TraverseTrivialABIAttr (TrivialABIAttr *A)
bool VisitTrivialABIAttr (TrivialABIAttr *A)
bool TraverseTryAcquireCapabilityAttr (TryAcquireCapabilityAttr *A)
bool VisitTryAcquireCapabilityAttr (TryAcquireCapabilityAttr *A)
bool TraverseTypeNonNullAttr (TypeNonNullAttr *A)
bool VisitTypeNonNullAttr (TypeNonNullAttr *A)
bool TraverseTypeNullUnspecifiedAttr (TypeNullUnspecifiedAttr *A)
bool VisitTypeNullUnspecifiedAttr (TypeNullUnspecifiedAttr *A)
bool TraverseTypeNullableAttr (TypeNullableAttr *A)
bool VisitTypeNullableAttr (TypeNullableAttr *A)
bool TraverseTypeNullableResultAttr (TypeNullableResultAttr *A)
bool VisitTypeNullableResultAttr (TypeNullableResultAttr *A)
bool TraverseTypeTagForDatatypeAttr (TypeTagForDatatypeAttr *A)
bool VisitTypeTagForDatatypeAttr (TypeTagForDatatypeAttr *A)
bool TraverseTypeVisibilityAttr (TypeVisibilityAttr *A)
bool VisitTypeVisibilityAttr (TypeVisibilityAttr *A)
bool TraverseUPtrAttr (UPtrAttr *A)
bool VisitUPtrAttr (UPtrAttr *A)
bool TraverseUnavailableAttr (UnavailableAttr *A)
bool VisitUnavailableAttr (UnavailableAttr *A)
bool TraverseUninitializedAttr (UninitializedAttr *A)
bool VisitUninitializedAttr (UninitializedAttr *A)
bool TraverseUnlikelyAttr (UnlikelyAttr *A)
bool VisitUnlikelyAttr (UnlikelyAttr *A)
bool TraverseUnusedAttr (UnusedAttr *A)
bool VisitUnusedAttr (UnusedAttr *A)
bool TraverseUseHandleAttr (UseHandleAttr *A)
bool VisitUseHandleAttr (UseHandleAttr *A)
bool TraverseUsedAttr (UsedAttr *A)
bool VisitUsedAttr (UsedAttr *A)
bool TraverseUuidAttr (UuidAttr *A)
bool VisitUuidAttr (UuidAttr *A)
bool TraverseVecReturnAttr (VecReturnAttr *A)
bool VisitVecReturnAttr (VecReturnAttr *A)
bool TraverseVecTypeHintAttr (VecTypeHintAttr *A)
bool VisitVecTypeHintAttr (VecTypeHintAttr *A)
bool TraverseVectorCallAttr (VectorCallAttr *A)
bool VisitVectorCallAttr (VectorCallAttr *A)
bool TraverseVisibilityAttr (VisibilityAttr *A)
bool VisitVisibilityAttr (VisibilityAttr *A)
bool TraverseWarnUnusedAttr (WarnUnusedAttr *A)
bool VisitWarnUnusedAttr (WarnUnusedAttr *A)
bool TraverseWarnUnusedResultAttr (WarnUnusedResultAttr *A)
bool VisitWarnUnusedResultAttr (WarnUnusedResultAttr *A)
bool TraverseWeakAttr (WeakAttr *A)
bool VisitWeakAttr (WeakAttr *A)
bool TraverseWeakImportAttr (WeakImportAttr *A)
bool VisitWeakImportAttr (WeakImportAttr *A)
bool TraverseWeakRefAttr (WeakRefAttr *A)
bool VisitWeakRefAttr (WeakRefAttr *A)
bool TraverseWebAssemblyExportNameAttr (WebAssemblyExportNameAttr *A)
bool VisitWebAssemblyExportNameAttr (WebAssemblyExportNameAttr *A)
bool TraverseWebAssemblyImportModuleAttr (WebAssemblyImportModuleAttr *A)
bool VisitWebAssemblyImportModuleAttr (WebAssemblyImportModuleAttr *A)
bool TraverseWebAssemblyImportNameAttr (WebAssemblyImportNameAttr *A)
bool VisitWebAssemblyImportNameAttr (WebAssemblyImportNameAttr *A)
bool TraverseWorkGroupSizeHintAttr (WorkGroupSizeHintAttr *A)
bool VisitWorkGroupSizeHintAttr (WorkGroupSizeHintAttr *A)
bool TraverseX86ForceAlignArgPointerAttr (X86ForceAlignArgPointerAttr *A)
bool VisitX86ForceAlignArgPointerAttr (X86ForceAlignArgPointerAttr *A)
bool TraverseXRayInstrumentAttr (XRayInstrumentAttr *A)
bool VisitXRayInstrumentAttr (XRayInstrumentAttr *A)
bool TraverseXRayLogArgsAttr (XRayLogArgsAttr *A)
bool VisitXRayLogArgsAttr (XRayLogArgsAttr *A)
Stmt::child_range getStmtChildren (Stmt *S)
bool WalkUpFromStmt (Stmt *S)
bool VisitStmt (Stmt *S)
bool WalkUpFromType (Type *T)
bool VisitType (Type *T)
bool WalkUpFromTypeLoc (TypeLoc TL)
bool VisitTypeLoc (TypeLoc TL)
bool WalkUpFromQualifiedTypeLoc (QualifiedTypeLoc TL)
bool VisitQualifiedTypeLoc (QualifiedTypeLoc TL)
bool WalkUpFromUnqualTypeLoc (UnqualTypeLoc TL)
bool VisitUnqualTypeLoc (UnqualTypeLoc TL)
bool WalkUpFromDecl (Decl *D)
bool VisitDecl (Decl *D)
bool canIgnoreChildDeclWhileTraversingDeclContext (const Decl *Child)
bool dataTraverseNode (Stmt *S, DataRecursionQueue *Queue)
Detailed Description
template<typename Derived>
class clang::RecursiveASTVisitor< Derived >
A class that does preorder or postorder depth-first traversal on the entire Clang AST and visits each node.
This class performs three distinct tasks:
traverse the AST (i.e. go to each node);
at a given node, walk up the class hierarchy, starting from the node's dynamic type, until the top-most class (e.g. Stmt, Decl, or Type) is reached.
given a (node, class) combination, where 'class' is some base class of the dynamic type of 'node', call a user-overridable function to actually visit the node.
These tasks are done by three groups of methods, respectively:
TraverseDecl(Decl *x) does task #1. It is the entry point for traversing an AST rooted at x. This method simply dispatches (i.e. forwards) to TraverseFoo(Foo *x) where Foo is the dynamic type of *x, which calls WalkUpFromFoo(x) and then recursively visits the child nodes of x. TraverseStmt(Stmt *x) and TraverseType(QualType x) work similarly.
WalkUpFromFoo(Foo *x) does task #2. It does not try to visit any child node of x. Instead, it first calls WalkUpFromBar(x) where Bar is the direct parent class of Foo (unless Foo has no parent), and then calls VisitFoo(x) (see the next list item).
VisitFoo(Foo *x) does task #3.
These three method groups are tiered (Traverse* > WalkUpFrom* > Visit*). A method (e.g. Traverse*) may call methods from the same tier (e.g. other Traverse*) or one tier lower (e.g. WalkUpFrom*). It may not call methods from a higher tier.
Note that since WalkUpFromFoo() calls WalkUpFromBar() (where Bar is Foo's super class) before calling VisitFoo(), the result is that the Visit*() methods for a given node are called in the top-down order (e.g. for a node of type NamespaceDecl, the order will be VisitDecl(), VisitNamedDecl(), and then VisitNamespaceDecl()).
This scheme guarantees that all Visit*() calls for the same AST node are grouped together. In other words, Visit*() methods for different nodes are never interleaved.
Clients of this visitor should subclass the visitor (providing themselves as the template argument, using the curiously recurring template pattern) and override any of the Traverse*, WalkUpFrom*, and Visit* methods for declarations, types, statements, expressions, or other AST nodes where the visitor should customize behavior. Most users only need to override Visit*. Advanced users may override Traverse* and WalkUpFrom* to implement custom traversal strategies. Returning false from one of these overridden functions will abort the entire traversal.
By default, this visitor tries to visit every part of the explicit source code exactly once. The default policy towards templates is to descend into the 'pattern' class or function body, not any explicit or implicit instantiations. Explicit specializations are still visited, and the patterns of partial specializations are visited separately. This behavior can be changed by overriding shouldVisitTemplateInstantiations() in the derived class to return true, in which case all known implicit and explicit instantiations will be visited at the same time as the pattern from which they were produced.
By default, this visitor preorder traverses the AST. If postorder traversal is needed, the shouldTraversePostOrder method needs to be overridden to return true.
Definition at line 164 of file RecursiveASTVisitor.h.
Member Typedef Documentation
DataRecursionQueue
template<typename Derived > SmallVectorImpl<llvm::PointerIntPair<Stmt *, 1, bool> > clang::RecursiveASTVisitor< Derived >::DataRecursionQueue
A queue used for performing data recursion over statements.
Parameters involving this type are used to implement data recursion over Stmts and Exprs within this class, and should typically not be explicitly specified by derived classes. The bool bit indicates whether the statement has been traversed or not.
Definition at line 172 of file RecursiveASTVisitor.h.
Member Function Documentation
canIgnoreChildDeclWhileTraversingDeclContext()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::canIgnoreChildDeclWhileTraversingDeclContext (const Decl * Child)
Referenced by clang::LexicallyOrderedRecursiveASTVisitor< Derived >::TraverseDeclContextHelper().
dataTraverseNode()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::dataTraverseNode (Stmt * S, DataRecursionQueue * Queue)
Definition at line 509 of file RecursiveASTVisitor.h.
dataTraverseStmtPost()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::dataTraverseStmtPost (Stmt * S) inline
Invoked after visiting a statement or expression via data recursion.
This is not invoked if the previously invoked dataTraverseStmtPre returned false.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 222 of file RecursiveASTVisitor.h.
dataTraverseStmtPre()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::dataTraverseStmtPre (Stmt * S) inline
Invoked before visiting a statement or expression via data recursion.
Returns
false to skip visiting the node, true otherwise.
Definition at line 215 of file RecursiveASTVisitor.h.
getDerived()
template<typename Derived > Derived & clang::RecursiveASTVisitor< Derived >::getDerived () inline
Return a reference to the derived class.
Definition at line 175 of file RecursiveASTVisitor.h.
Referenced by clang::LexicallyOrderedRecursiveASTVisitor< Derived >::TraverseDeclContextHelper(), clang::RecursiveASTVisitor< Derived >::TraverseExclusiveTrylockFunctionAttr(), clang::RecursiveASTVisitor< Derived >::VisitFlagEnumAttr(), clang::RecursiveASTVisitor< Derived >::WalkUpFromDecl(), clang::RecursiveASTVisitor< Derived >::WalkUpFromQualifiedTypeLoc(), clang::RecursiveASTVisitor< Derived >::WalkUpFromStmt(), and clang::RecursiveASTVisitor< Derived >::WalkUpFromUnqualTypeLoc().
getStmtChildren()
template<typename Derived > Stmt::child_range clang::RecursiveASTVisitor< Derived >::getStmtChildren (Stmt * S) inline
Definition at line 341 of file RecursiveASTVisitor.h.
shouldTraversePostOrder()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::shouldTraversePostOrder () const inline
Return whether this visitor should traverse post-order.
Definition at line 193 of file RecursiveASTVisitor.h.
shouldVisitImplicitCode()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::shouldVisitImplicitCode () const inline
Return whether this visitor should recurse into implicit code, e.g., implicit constructors and destructors.
Definition at line 187 of file RecursiveASTVisitor.h.
shouldVisitLambdaBody()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::shouldVisitLambdaBody () const inline
Return whether this visitor should recurse into lambda body.
Definition at line 190 of file RecursiveASTVisitor.h.
shouldVisitTemplateInstantiations()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::shouldVisitTemplateInstantiations () const inline
Return whether this visitor should recurse into template instantiations.
Definition at line 179 of file RecursiveASTVisitor.h.
shouldWalkTypesOfTypeLocs()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::shouldWalkTypesOfTypeLocs () const inline
Return whether this visitor should recurse into the types of TypeLocs.
Definition at line 183 of file RecursiveASTVisitor.h.
TraverseAArch64VectorPcsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAArch64VectorPcsAttr (AArch64VectorPcsAttr * A)
TraverseAbiTagAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAbiTagAttr (AbiTagAttr * A)
TraverseAcquireCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAcquireCapabilityAttr (AcquireCapabilityAttr * A)
TraverseAcquiredAfterAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAcquiredAfterAttr (AcquiredAfterAttr * A)
TraverseAcquiredBeforeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAcquiredBeforeAttr (AcquiredBeforeAttr * A)
TraverseAcquireHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAcquireHandleAttr (AcquireHandleAttr * A)
TraverseAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAddressSpaceAttr (AddressSpaceAttr * A)
TraverseAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAliasAttr (AliasAttr * A)
TraverseAlignedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlignedAttr (AlignedAttr * A)
TraverseAlignMac68kAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlignMac68kAttr (AlignMac68kAttr * A)
TraverseAlignNaturalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlignNaturalAttr (AlignNaturalAttr * A)
TraverseAlignValueAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlignValueAttr (AlignValueAttr * A)
TraverseAllocAlignAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAllocAlignAttr (AllocAlignAttr * A)
TraverseAllocSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAllocSizeAttr (AllocSizeAttr * A)
TraverseAlwaysDestroyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlwaysDestroyAttr (AlwaysDestroyAttr * A)
TraverseAlwaysInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAlwaysInlineAttr (AlwaysInlineAttr * A)
TraverseAMDGPUFlatWorkGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAMDGPUFlatWorkGroupSizeAttr (AMDGPUFlatWorkGroupSizeAttr * A)
TraverseAMDGPUNumSGPRAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAMDGPUNumSGPRAttr (AMDGPUNumSGPRAttr * A)
TraverseAMDGPUNumVGPRAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAMDGPUNumVGPRAttr (AMDGPUNumVGPRAttr * A)
TraverseAMDGPUWavesPerEUAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAMDGPUWavesPerEUAttr (AMDGPUWavesPerEUAttr * A)
TraverseAnalyzerNoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAnalyzerNoReturnAttr (AnalyzerNoReturnAttr * A)
TraverseAnnotateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAnnotateAttr (AnnotateAttr * A)
TraverseAnyX86InterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAnyX86InterruptAttr (AnyX86InterruptAttr * A)
TraverseAnyX86NoCallerSavedRegistersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAnyX86NoCallerSavedRegistersAttr (AnyX86NoCallerSavedRegistersAttr * A)
TraverseAnyX86NoCfCheckAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAnyX86NoCfCheckAttr (AnyX86NoCfCheckAttr * A)
TraverseArcWeakrefUnavailableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseArcWeakrefUnavailableAttr (ArcWeakrefUnavailableAttr * A)
TraverseArgumentWithTypeTagAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseArgumentWithTypeTagAttr (ArgumentWithTypeTagAttr * A)
TraverseArmBuiltinAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseArmBuiltinAliasAttr (ArmBuiltinAliasAttr * A)
TraverseARMInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseARMInterruptAttr (ARMInterruptAttr * A)
TraverseArmMveStrictPolymorphismAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseArmMveStrictPolymorphismAttr (ArmMveStrictPolymorphismAttr * A)
TraverseArtificialAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseArtificialAttr (ArtificialAttr * A)
TraverseAsmLabelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAsmLabelAttr (AsmLabelAttr * A)
TraverseAssertCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAssertCapabilityAttr (AssertCapabilityAttr * A)
TraverseAssertExclusiveLockAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAssertExclusiveLockAttr (AssertExclusiveLockAttr * A)
TraverseAssertSharedLockAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAssertSharedLockAttr (AssertSharedLockAttr * A)
TraverseAssumeAlignedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAssumeAlignedAttr (AssumeAlignedAttr * A)
TraverseAssumptionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAssumptionAttr (AssumptionAttr * A)
TraverseAST()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAST (ASTContext & AST) inline
Recursively visits an entire AST, starting from the top-level Decls in the AST traversal scope (by default, the TranslationUnitDecl).
Returns
false if visitation was terminated early.
Definition at line 198 of file RecursiveASTVisitor.h.
References clang::ASTContext::getTraversalScope().
Referenced by clang::ParentMapContext::ParentMap::ParentMap().
TraverseAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAttr (Attr * At)
Recursively visit an attribute, by dispatching to Traverse*Attr() based on the argument's dynamic type.
Returns
false if the visitation was terminated early, true otherwise (including when the argument is a Null type location).
TraverseAvailabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAvailabilityAttr (AvailabilityAttr * A)
TraverseAVRInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAVRInterruptAttr (AVRInterruptAttr * A)
TraverseAVRSignalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseAVRSignalAttr (AVRSignalAttr * A)
TraverseBlocksAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseBlocksAttr (BlocksAttr * A)
TraverseBPFPreserveAccessIndexAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseBPFPreserveAccessIndexAttr (BPFPreserveAccessIndexAttr * A)
TraverseBuiltinAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseBuiltinAttr (BuiltinAttr * A)
TraverseC11NoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseC11NoReturnAttr (C11NoReturnAttr * A)
TraverseCallableWhenAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCallableWhenAttr (CallableWhenAttr * A)
TraverseCallbackAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCallbackAttr (CallbackAttr * A)
TraverseCalledOnceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCalledOnceAttr (CalledOnceAttr * A)
TraverseCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCapabilityAttr (CapabilityAttr * A)
TraverseCapturedRecordAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCapturedRecordAttr (CapturedRecordAttr * A)
TraverseCarriesDependencyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCarriesDependencyAttr (CarriesDependencyAttr * A)
TraverseCDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCDeclAttr (CDeclAttr * A)
TraverseCFAuditedTransferAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFAuditedTransferAttr (CFAuditedTransferAttr * A)
TraverseCFConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFConsumedAttr (CFConsumedAttr * A)
TraverseCFGuardAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFGuardAttr (CFGuardAttr * A)
TraverseCFICanonicalJumpTableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFICanonicalJumpTableAttr (CFICanonicalJumpTableAttr * A)
TraverseCFReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFReturnsNotRetainedAttr (CFReturnsNotRetainedAttr * A)
TraverseCFReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFReturnsRetainedAttr (CFReturnsRetainedAttr * A)
TraverseCFUnknownTransferAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCFUnknownTransferAttr (CFUnknownTransferAttr * A)
TraverseCleanupAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCleanupAttr (CleanupAttr * A)
TraverseCmseNSCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCmseNSCallAttr (CmseNSCallAttr * A)
TraverseCmseNSEntryAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCmseNSEntryAttr (CmseNSEntryAttr * A)
TraverseCodeSegAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCodeSegAttr (CodeSegAttr * A)
TraverseColdAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseColdAttr (ColdAttr * A)
TraverseCommonAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCommonAttr (CommonAttr * A)
TraverseConceptReference()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConceptReference (const ConceptReference & C)
Recursively visit a reference to a concept with potential arguments.
Returns
false if the visitation was terminated early, true otherwise.
TraverseConstAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConstAttr (ConstAttr * A)
TraverseConstInitAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConstInitAttr (ConstInitAttr * A)
TraverseConstructorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConstructorAttr (ConstructorAttr * A)
TraverseConstructorInitializer()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConstructorInitializer (CXXCtorInitializer * Init)
Recursively visit a constructor initializer.
This automatically dispatches to another visitor for the initializer expression, but not for the name of the initializer, so may be overridden for clients that need access to the name.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 847 of file RecursiveASTVisitor.h.
TraverseConsumableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConsumableAttr (ConsumableAttr * A)
TraverseConsumableAutoCastAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConsumableAutoCastAttr (ConsumableAutoCastAttr * A)
TraverseConsumableSetOnReadAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConsumableSetOnReadAttr (ConsumableSetOnReadAttr * A)
TraverseConvergentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseConvergentAttr (ConvergentAttr * A)
TraverseCPUDispatchAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCPUDispatchAttr (CPUDispatchAttr * A)
TraverseCPUSpecificAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCPUSpecificAttr (CPUSpecificAttr * A)
TraverseCUDAConstantAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDAConstantAttr (CUDAConstantAttr * A)
TraverseCUDADeviceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDADeviceAttr (CUDADeviceAttr * A)
TraverseCUDADeviceBuiltinSurfaceTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDADeviceBuiltinSurfaceTypeAttr (CUDADeviceBuiltinSurfaceTypeAttr * A)
TraverseCUDADeviceBuiltinTextureTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDADeviceBuiltinTextureTypeAttr (CUDADeviceBuiltinTextureTypeAttr * A)
TraverseCUDAGlobalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDAGlobalAttr (CUDAGlobalAttr * A)
TraverseCUDAHostAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDAHostAttr (CUDAHostAttr * A)
TraverseCUDAInvalidTargetAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDAInvalidTargetAttr (CUDAInvalidTargetAttr * A)
TraverseCUDALaunchBoundsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDALaunchBoundsAttr (CUDALaunchBoundsAttr * A)
TraverseCUDASharedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCUDASharedAttr (CUDASharedAttr * A)
TraverseCXX11NoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCXX11NoReturnAttr (CXX11NoReturnAttr * A)
TraverseCXXBaseSpecifier()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseCXXBaseSpecifier (const CXXBaseSpecifier & Base)
Recursively visit a base specifier.
This can be overridden by a subclass.
Returns
false if the visitation was terminated early, true otherwise.
TraverseDecl()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDecl (Decl * D)
Recursively visit a declaration, by dispatching to Traverse*Decl() based on the argument's dynamic type.
Returns
false if the visitation was terminated early, true otherwise (including when the argument is NULL).
Definition at line 655 of file RecursiveASTVisitor.h.
Referenced by clang::arcmt::trans::removeRetainReleaseDeallocFinalize(), clang::arcmt::trans::rewriteAutoreleasePool(), clang::arcmt::trans::rewriteUnbridgedCasts(), clang::arcmt::trans::rewriteUnusedInitDelegate(), and clang::LexicallyOrderedRecursiveASTVisitor< Derived >::TraverseDeclContextHelper().
TraverseDeclarationNameInfo()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDeclarationNameInfo (DeclarationNameInfo NameInfo)
Recursively visit a name with its location information.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 728 of file RecursiveASTVisitor.h.
TraverseDeprecatedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDeprecatedAttr (DeprecatedAttr * A)
TraverseDestructorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDestructorAttr (DestructorAttr * A)
TraverseDiagnoseIfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDiagnoseIfAttr (DiagnoseIfAttr * A)
TraverseDisableTailCallsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDisableTailCallsAttr (DisableTailCallsAttr * A)
TraverseDLLExportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDLLExportAttr (DLLExportAttr * A)
TraverseDLLExportStaticLocalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDLLExportStaticLocalAttr (DLLExportStaticLocalAttr * A)
TraverseDLLImportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDLLImportAttr (DLLImportAttr * A)
TraverseDLLImportStaticLocalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseDLLImportStaticLocalAttr (DLLImportStaticLocalAttr * A)
TraverseEmptyBasesAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseEmptyBasesAttr (EmptyBasesAttr * A)
TraverseEnableIfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseEnableIfAttr (EnableIfAttr * A)
TraverseEnforceTCBAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseEnforceTCBAttr (EnforceTCBAttr * A)
TraverseEnforceTCBLeafAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseEnforceTCBLeafAttr (EnforceTCBLeafAttr * A)
TraverseEnumExtensibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseEnumExtensibilityAttr (EnumExtensibilityAttr * A)
TraverseExcludeFromExplicitInstantiationAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseExcludeFromExplicitInstantiationAttr (ExcludeFromExplicitInstantiationAttr * A)
TraverseExclusiveTrylockFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseExclusiveTrylockFunctionAttr (ExclusiveTrylockFunctionAttr * A)
References clang::RecursiveASTVisitor< Derived >::getDerived().
TraverseExternalSourceSymbolAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseExternalSourceSymbolAttr (ExternalSourceSymbolAttr * A)
TraverseFallThroughAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFallThroughAttr (FallThroughAttr * A)
TraverseFastCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFastCallAttr (FastCallAttr * A)
TraverseFinalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFinalAttr (FinalAttr * A)
TraverseFlagEnumAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFlagEnumAttr (FlagEnumAttr * A)
TraverseFlattenAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFlattenAttr (FlattenAttr * A)
TraverseFormatArgAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFormatArgAttr (FormatArgAttr * A)
TraverseFormatAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseFormatAttr (FormatAttr * A)
TraverseGNUInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseGNUInlineAttr (GNUInlineAttr * A)
TraverseGuardedByAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseGuardedByAttr (GuardedByAttr * A)
TraverseGuardedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseGuardedVarAttr (GuardedVarAttr * A)
TraverseHIPManagedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseHIPManagedAttr (HIPManagedAttr * A)
TraverseHotAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseHotAttr (HotAttr * A)
TraverseIBActionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseIBActionAttr (IBActionAttr * A)
TraverseIBOutletAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseIBOutletAttr (IBOutletAttr * A)
TraverseIBOutletCollectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseIBOutletCollectionAttr (IBOutletCollectionAttr * A)
TraverseIFuncAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseIFuncAttr (IFuncAttr * A)
TraverseInitPriorityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseInitPriorityAttr (InitPriorityAttr * A)
TraverseInitSegAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseInitSegAttr (InitSegAttr * A)
TraverseIntelOclBiccAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseIntelOclBiccAttr (IntelOclBiccAttr * A)
TraverseInternalLinkageAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseInternalLinkageAttr (InternalLinkageAttr * A)
TraverseLambdaCapture()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLambdaCapture (LambdaExpr * LE, const LambdaCapture * C, Expr * Init)
Recursively visit a lambda capture.
Init is the expression that will be used to initialize the capture.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 860 of file RecursiveASTVisitor.h.
TraverseLayoutVersionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLayoutVersionAttr (LayoutVersionAttr * A)
TraverseLeafAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLeafAttr (LeafAttr * A)
TraverseLifetimeBoundAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLifetimeBoundAttr (LifetimeBoundAttr * A)
TraverseLikelyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLikelyAttr (LikelyAttr * A)
TraverseLoaderUninitializedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLoaderUninitializedAttr (LoaderUninitializedAttr * A)
TraverseLockReturnedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLockReturnedAttr (LockReturnedAttr * A)
TraverseLocksExcludedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLocksExcludedAttr (LocksExcludedAttr * A)
TraverseLoopHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLoopHintAttr (LoopHintAttr * A)
TraverseLTOVisibilityPublicAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseLTOVisibilityPublicAttr (LTOVisibilityPublicAttr * A)
TraverseMaxFieldAlignmentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMaxFieldAlignmentAttr (MaxFieldAlignmentAttr * A)
TraverseMayAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMayAliasAttr (MayAliasAttr * A)
TraverseMicroMipsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMicroMipsAttr (MicroMipsAttr * A)
TraverseMIGServerRoutineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMIGServerRoutineAttr (MIGServerRoutineAttr * A)
TraverseMinSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMinSizeAttr (MinSizeAttr * A)
TraverseMinVectorWidthAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMinVectorWidthAttr (MinVectorWidthAttr * A)
TraverseMips16Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMips16Attr (Mips16Attr * A)
TraverseMipsInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMipsInterruptAttr (MipsInterruptAttr * A)
TraverseMipsLongCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMipsLongCallAttr (MipsLongCallAttr * A)
TraverseMipsShortCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMipsShortCallAttr (MipsShortCallAttr * A)
TraverseModeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseModeAttr (ModeAttr * A)
TraverseMSABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSABIAttr (MSABIAttr * A)
TraverseMSAllocatorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSAllocatorAttr (MSAllocatorAttr * A)
TraverseMSInheritanceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSInheritanceAttr (MSInheritanceAttr * A)
TraverseMSNoVTableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSNoVTableAttr (MSNoVTableAttr * A)
TraverseMSP430InterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSP430InterruptAttr (MSP430InterruptAttr * A)
TraverseMSStructAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSStructAttr (MSStructAttr * A)
TraverseMSVtorDispAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseMSVtorDispAttr (MSVtorDispAttr * A)
TraverseNakedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNakedAttr (NakedAttr * A)
TraverseNestedNameSpecifier()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNestedNameSpecifier (NestedNameSpecifier * NNS)
Recursively visit a C++ nested-name-specifier.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 677 of file RecursiveASTVisitor.h.
TraverseNestedNameSpecifierLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Recursively visit a C++ nested-name-specifier with location information.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 702 of file RecursiveASTVisitor.h.
TraverseNoAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoAliasAttr (NoAliasAttr * A)
TraverseNoBuiltinAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoBuiltinAttr (NoBuiltinAttr * A)
TraverseNoCommonAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoCommonAttr (NoCommonAttr * A)
TraverseNoDebugAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoDebugAttr (NoDebugAttr * A)
TraverseNoDerefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoDerefAttr (NoDerefAttr * A)
TraverseNoDestroyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoDestroyAttr (NoDestroyAttr * A)
TraverseNoDuplicateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoDuplicateAttr (NoDuplicateAttr * A)
TraverseNoEscapeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoEscapeAttr (NoEscapeAttr * A)
TraverseNoInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoInlineAttr (NoInlineAttr * A)
TraverseNoInstrumentFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoInstrumentFunctionAttr (NoInstrumentFunctionAttr * A)
TraverseNoMergeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoMergeAttr (NoMergeAttr * A)
TraverseNoMicroMipsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoMicroMipsAttr (NoMicroMipsAttr * A)
TraverseNoMips16Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoMips16Attr (NoMips16Attr * A)
TraverseNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNonNullAttr (NonNullAttr * A)
TraverseNoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoReturnAttr (NoReturnAttr * A)
TraverseNoSanitizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoSanitizeAttr (NoSanitizeAttr * A)
TraverseNoSpeculativeLoadHardeningAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoSpeculativeLoadHardeningAttr (NoSpeculativeLoadHardeningAttr * A)
TraverseNoSplitStackAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoSplitStackAttr (NoSplitStackAttr * A)
TraverseNoStackProtectorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoStackProtectorAttr (NoStackProtectorAttr * A)
TraverseNoThreadSafetyAnalysisAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoThreadSafetyAnalysisAttr (NoThreadSafetyAnalysisAttr * A)
TraverseNoThrowAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoThrowAttr (NoThrowAttr * A)
TraverseNotTailCalledAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNotTailCalledAttr (NotTailCalledAttr * A)
TraverseNoUniqueAddressAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNoUniqueAddressAttr (NoUniqueAddressAttr * A)
TraverseNSConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSConsumedAttr (NSConsumedAttr * A)
TraverseNSConsumesSelfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSConsumesSelfAttr (NSConsumesSelfAttr * A)
TraverseNSErrorDomainAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSErrorDomainAttr (NSErrorDomainAttr * A)
TraverseNSReturnsAutoreleasedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSReturnsAutoreleasedAttr (NSReturnsAutoreleasedAttr * A)
TraverseNSReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSReturnsNotRetainedAttr (NSReturnsNotRetainedAttr * A)
TraverseNSReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseNSReturnsRetainedAttr (NSReturnsRetainedAttr * A)
TraverseObjCBoxableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCBoxableAttr (ObjCBoxableAttr * A)
TraverseObjCBridgeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCBridgeAttr (ObjCBridgeAttr * A)
TraverseObjCBridgeMutableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCBridgeMutableAttr (ObjCBridgeMutableAttr * A)
TraverseObjCBridgeRelatedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCBridgeRelatedAttr (ObjCBridgeRelatedAttr * A)
TraverseObjCClassStubAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCClassStubAttr (ObjCClassStubAttr * A)
TraverseObjCDesignatedInitializerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCDesignatedInitializerAttr (ObjCDesignatedInitializerAttr * A)
TraverseObjCDirectAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCDirectAttr (ObjCDirectAttr * A)
TraverseObjCDirectMembersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCDirectMembersAttr (ObjCDirectMembersAttr * A)
TraverseObjCExceptionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCExceptionAttr (ObjCExceptionAttr * A)
TraverseObjCExplicitProtocolImplAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCExplicitProtocolImplAttr (ObjCExplicitProtocolImplAttr * A)
TraverseObjCExternallyRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCExternallyRetainedAttr (ObjCExternallyRetainedAttr * A)
TraverseObjCGCAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCGCAttr (ObjCGCAttr * A)
TraverseObjCIndependentClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCIndependentClassAttr (ObjCIndependentClassAttr * A)
TraverseObjCInertUnsafeUnretainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCInertUnsafeUnretainedAttr (ObjCInertUnsafeUnretainedAttr * A)
TraverseObjCKindOfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCKindOfAttr (ObjCKindOfAttr * A)
TraverseObjCMethodFamilyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCMethodFamilyAttr (ObjCMethodFamilyAttr * A)
TraverseObjCNonLazyClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCNonLazyClassAttr (ObjCNonLazyClassAttr * A)
TraverseObjCNonRuntimeProtocolAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCNonRuntimeProtocolAttr (ObjCNonRuntimeProtocolAttr * A)
TraverseObjCNSObjectAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCNSObjectAttr (ObjCNSObjectAttr * A)
TraverseObjCOwnershipAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCOwnershipAttr (ObjCOwnershipAttr * A)
TraverseObjCPreciseLifetimeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCPreciseLifetimeAttr (ObjCPreciseLifetimeAttr * A)
TraverseObjCRequiresPropertyDefsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCRequiresPropertyDefsAttr (ObjCRequiresPropertyDefsAttr * A)
TraverseObjCRequiresSuperAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCRequiresSuperAttr (ObjCRequiresSuperAttr * A)
TraverseObjCReturnsInnerPointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCReturnsInnerPointerAttr (ObjCReturnsInnerPointerAttr * A)
TraverseObjCRootClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCRootClassAttr (ObjCRootClassAttr * A)
TraverseObjCRuntimeNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCRuntimeNameAttr (ObjCRuntimeNameAttr * A)
TraverseObjCRuntimeVisibleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCRuntimeVisibleAttr (ObjCRuntimeVisibleAttr * A)
TraverseObjCSubclassingRestrictedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseObjCSubclassingRestrictedAttr (ObjCSubclassingRestrictedAttr * A)
TraverseOMPAllocateDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPAllocateDeclAttr (OMPAllocateDeclAttr * A)
TraverseOMPCaptureKindAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPCaptureKindAttr (OMPCaptureKindAttr * A)
TraverseOMPCaptureNoInitAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPCaptureNoInitAttr (OMPCaptureNoInitAttr * A)
TraverseOMPDeclareSimdDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPDeclareSimdDeclAttr (OMPDeclareSimdDeclAttr * A)
TraverseOMPDeclareTargetDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPDeclareTargetDeclAttr (OMPDeclareTargetDeclAttr * A)
TraverseOMPDeclareVariantAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPDeclareVariantAttr (OMPDeclareVariantAttr * A)
TraverseOMPReferencedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPReferencedVarAttr (OMPReferencedVarAttr * A)
TraverseOMPThreadPrivateDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOMPThreadPrivateDeclAttr (OMPThreadPrivateDeclAttr * A)
TraverseOpenCLAccessAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLAccessAttr (OpenCLAccessAttr * A)
TraverseOpenCLConstantAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLConstantAddressSpaceAttr (OpenCLConstantAddressSpaceAttr * A)
References TRY_TO.
TraverseOpenCLGenericAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLGenericAddressSpaceAttr (OpenCLGenericAddressSpaceAttr * A)
TraverseOpenCLGlobalAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLGlobalAddressSpaceAttr (OpenCLGlobalAddressSpaceAttr * A)
TraverseOpenCLGlobalDeviceAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLGlobalDeviceAddressSpaceAttr (OpenCLGlobalDeviceAddressSpaceAttr * A)
TraverseOpenCLGlobalHostAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLGlobalHostAddressSpaceAttr (OpenCLGlobalHostAddressSpaceAttr * A)
References TRY_TO.
TraverseOpenCLIntelReqdSubGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLIntelReqdSubGroupSizeAttr (OpenCLIntelReqdSubGroupSizeAttr * A)
TraverseOpenCLKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLKernelAttr (OpenCLKernelAttr * A)
TraverseOpenCLLocalAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLLocalAddressSpaceAttr (OpenCLLocalAddressSpaceAttr * A)
TraverseOpenCLPrivateAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLPrivateAddressSpaceAttr (OpenCLPrivateAddressSpaceAttr * A)
TraverseOpenCLUnrollHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOpenCLUnrollHintAttr (OpenCLUnrollHintAttr * A)
TraverseOptimizeNoneAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOptimizeNoneAttr (OptimizeNoneAttr * A)
TraverseOSConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSConsumedAttr (OSConsumedAttr * A)
TraverseOSConsumesThisAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSConsumesThisAttr (OSConsumesThisAttr * A)
TraverseOSReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSReturnsNotRetainedAttr (OSReturnsNotRetainedAttr * A)
TraverseOSReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSReturnsRetainedAttr (OSReturnsRetainedAttr * A)
TraverseOSReturnsRetainedOnNonZeroAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSReturnsRetainedOnNonZeroAttr (OSReturnsRetainedOnNonZeroAttr * A)
TraverseOSReturnsRetainedOnZeroAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOSReturnsRetainedOnZeroAttr (OSReturnsRetainedOnZeroAttr * A)
TraverseOverloadableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOverloadableAttr (OverloadableAttr * A)
TraverseOverrideAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOverrideAttr (OverrideAttr * A)
TraverseOwnerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOwnerAttr (OwnerAttr * A)
TraverseOwnershipAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseOwnershipAttr (OwnershipAttr * A)
TraversePackedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePackedAttr (PackedAttr * A)
TraverseParamTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseParamTypestateAttr (ParamTypestateAttr * A)
TraversePascalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePascalAttr (PascalAttr * A)
TraversePassObjectSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePassObjectSizeAttr (PassObjectSizeAttr * A)
TraversePatchableFunctionEntryAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePatchableFunctionEntryAttr (PatchableFunctionEntryAttr * A)
TraversePcsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePcsAttr (PcsAttr * A)
TraversePointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePointerAttr (PointerAttr * A)
TraversePragmaClangBSSSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePragmaClangBSSSectionAttr (PragmaClangBSSSectionAttr * A)
TraversePragmaClangDataSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePragmaClangDataSectionAttr (PragmaClangDataSectionAttr * A)
TraversePragmaClangRelroSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePragmaClangRelroSectionAttr (PragmaClangRelroSectionAttr * A)
References TRY_TO.
TraversePragmaClangRodataSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePragmaClangRodataSectionAttr (PragmaClangRodataSectionAttr * A)
TraversePragmaClangTextSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePragmaClangTextSectionAttr (PragmaClangTextSectionAttr * A)
TraversePreferredNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePreferredNameAttr (PreferredNameAttr * A)
TraversePreserveAllAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePreserveAllAttr (PreserveAllAttr * A)
TraversePreserveMostAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePreserveMostAttr (PreserveMostAttr * A)
TraversePtGuardedByAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePtGuardedByAttr (PtGuardedByAttr * A)
TraversePtGuardedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePtGuardedVarAttr (PtGuardedVarAttr * A)
TraversePtr32Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePtr32Attr (Ptr32Attr * A)
TraversePtr64Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePtr64Attr (Ptr64Attr * A)
TraversePureAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraversePureAttr (PureAttr * A)
References TRY_TO.
TraverseRegCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseRegCallAttr (RegCallAttr * A)
TraverseReinitializesAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReinitializesAttr (ReinitializesAttr * A)
TraverseReleaseCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReleaseCapabilityAttr (ReleaseCapabilityAttr * A)
TraverseReleaseHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReleaseHandleAttr (ReleaseHandleAttr * A)
TraverseRenderScriptKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseRenderScriptKernelAttr (RenderScriptKernelAttr * A)
TraverseReqdWorkGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReqdWorkGroupSizeAttr (ReqdWorkGroupSizeAttr * A)
TraverseRequiresCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseRequiresCapabilityAttr (RequiresCapabilityAttr * A)
TraverseRestrictAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseRestrictAttr (RestrictAttr * A)
TraverseReturnsNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReturnsNonNullAttr (ReturnsNonNullAttr * A)
TraverseReturnsTwiceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReturnsTwiceAttr (ReturnsTwiceAttr * A)
TraverseReturnTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseReturnTypestateAttr (ReturnTypestateAttr * A)
TraverseRISCVInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseRISCVInterruptAttr (RISCVInterruptAttr * A)
TraverseScopedLockableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseScopedLockableAttr (ScopedLockableAttr * A)
TraverseSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSectionAttr (SectionAttr * A)
TraverseSelectAnyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSelectAnyAttr (SelectAnyAttr * A)
TraverseSentinelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSentinelAttr (SentinelAttr * A)
TraverseSetTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSetTypestateAttr (SetTypestateAttr * A)
TraverseSharedTrylockFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSharedTrylockFunctionAttr (SharedTrylockFunctionAttr * A)
TraverseSpeculativeLoadHardeningAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSpeculativeLoadHardeningAttr (SpeculativeLoadHardeningAttr * A)
TraverseSPtrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSPtrAttr (SPtrAttr * A)
TraverseStdCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseStdCallAttr (StdCallAttr * A)
TraverseStmt()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseStmt (Stmt * S, DataRecursionQueue * Queue = nullptr)
Recursively visit a statement or expression, by dispatching to Traverse*() based on the argument's dynamic type.
Returns
false if the visitation was terminated early, true otherwise (including when the argument is nullptr).
Definition at line 576 of file RecursiveASTVisitor.h.
TraverseStrictFPAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseStrictFPAttr (StrictFPAttr * A)
TraverseSuppressAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSuppressAttr (SuppressAttr * A)
TraverseSwiftAsyncAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftAsyncAttr (SwiftAsyncAttr * A)
TraverseSwiftAsyncNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftAsyncNameAttr (SwiftAsyncNameAttr * A)
References TRY_TO.
TraverseSwiftAttrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftAttrAttr (SwiftAttrAttr * A)
TraverseSwiftBridgeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftBridgeAttr (SwiftBridgeAttr * A)
TraverseSwiftBridgedTypedefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftBridgedTypedefAttr (SwiftBridgedTypedefAttr * A)
TraverseSwiftCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftCallAttr (SwiftCallAttr * A)
TraverseSwiftContextAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftContextAttr (SwiftContextAttr * A)
TraverseSwiftErrorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftErrorAttr (SwiftErrorAttr * A)
TraverseSwiftErrorResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftErrorResultAttr (SwiftErrorResultAttr * A)
TraverseSwiftIndirectResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftIndirectResultAttr (SwiftIndirectResultAttr * A)
TraverseSwiftNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftNameAttr (SwiftNameAttr * A)
TraverseSwiftNewTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftNewTypeAttr (SwiftNewTypeAttr * A)
TraverseSwiftObjCMembersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftObjCMembersAttr (SwiftObjCMembersAttr * A)
TraverseSwiftPrivateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSwiftPrivateAttr (SwiftPrivateAttr * A)
TraverseSYCLKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSYCLKernelAttr (SYCLKernelAttr * A)
TraverseSynOrSemInitListExpr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSynOrSemInitListExpr (InitListExpr * S, DataRecursionQueue * Queue = nullptr)
Recursively visit the syntactic or semantic form of an initialization list.
Returns
false if the visitation was terminated early, true otherwise.
TraverseSysVABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseSysVABIAttr (SysVABIAttr * A)
TraverseTargetAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTargetAttr (TargetAttr * A)
TraverseTemplateArgument()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTemplateArgument (const TemplateArgument & Arg)
Recursively visit a template argument and dispatch to the appropriate method for the argument type.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 767 of file RecursiveASTVisitor.h.
TraverseTemplateArgumentLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTemplateArgumentLoc (const TemplateArgumentLoc & ArgLoc)
Recursively visit a template argument location and dispatch to the appropriate method for the argument type.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 798 of file RecursiveASTVisitor.h.
TraverseTemplateArguments()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTemplateArguments (const TemplateArgument * Args, unsigned NumArgs)
Recursively visit a set of template arguments.
This can be overridden by a subclass, but it's not expected that will be needed – this visitor always dispatches to another.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 837 of file RecursiveASTVisitor.h.
TraverseTemplateName()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTemplateName (TemplateName Template)
Recursively visit a template name and dispatch to the appropriate method.
Returns
false if the visitation was terminated early, true otherwise.
Definition at line 757 of file RecursiveASTVisitor.h.
References clang::TemplateName::getAsDependentTemplateName(), and TRY_TO.
TraverseTestTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTestTypestateAttr (TestTypestateAttr * A)
TraverseThisCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseThisCallAttr (ThisCallAttr * A)
TraverseThreadAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseThreadAttr (ThreadAttr * A)
TraverseTLSModelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTLSModelAttr (TLSModelAttr * A)
TraverseTransparentUnionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTransparentUnionAttr (TransparentUnionAttr * A)
TraverseTrivialABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTrivialABIAttr (TrivialABIAttr * A)
TraverseTryAcquireCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTryAcquireCapabilityAttr (TryAcquireCapabilityAttr * A)
TraverseType()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseType (QualType T)
Recursively visit a type, by dispatching to Traverse*Type() based on the argument's getTypeClass() property.
Returns
false if the visitation was terminated early, true otherwise (including when the argument is a Null type).
Definition at line 617 of file RecursiveASTVisitor.h.
TraverseTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeLoc (TypeLoc TL)
Recursively visit a type with location, by dispatching to Traverse*TypeLoc() based on the argument type's getTypeClass() property.
Returns
false if the visitation was terminated early, true otherwise (including when the argument is a Null type location).
Definition at line 634 of file RecursiveASTVisitor.h.
References clang::TypeLoc::isNull().
TraverseTypeNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeNonNullAttr (TypeNonNullAttr * A)
TraverseTypeNullableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeNullableAttr (TypeNullableAttr * A)
TraverseTypeNullableResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeNullableResultAttr (TypeNullableResultAttr * A)
TraverseTypeNullUnspecifiedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeNullUnspecifiedAttr (TypeNullUnspecifiedAttr * A)
TraverseTypeTagForDatatypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeTagForDatatypeAttr (TypeTagForDatatypeAttr * A)
TraverseTypeVisibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseTypeVisibilityAttr (TypeVisibilityAttr * A)
TraverseUnavailableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUnavailableAttr (UnavailableAttr * A)
TraverseUninitializedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUninitializedAttr (UninitializedAttr * A)
TraverseUnlikelyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUnlikelyAttr (UnlikelyAttr * A)
TraverseUnusedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUnusedAttr (UnusedAttr * A)
TraverseUPtrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUPtrAttr (UPtrAttr * A)
TraverseUsedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUsedAttr (UsedAttr * A)
TraverseUseHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUseHandleAttr (UseHandleAttr * A)
TraverseUuidAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseUuidAttr (UuidAttr * A)
TraverseVecReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseVecReturnAttr (VecReturnAttr * A)
TraverseVectorCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseVectorCallAttr (VectorCallAttr * A)
TraverseVecTypeHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseVecTypeHintAttr (VecTypeHintAttr * A)
TraverseVisibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseVisibilityAttr (VisibilityAttr * A)
TraverseWarnUnusedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWarnUnusedAttr (WarnUnusedAttr * A)
TraverseWarnUnusedResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWarnUnusedResultAttr (WarnUnusedResultAttr * A)
TraverseWeakAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWeakAttr (WeakAttr * A)
TraverseWeakImportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWeakImportAttr (WeakImportAttr * A)
TraverseWeakRefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWeakRefAttr (WeakRefAttr * A)
TraverseWebAssemblyExportNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWebAssemblyExportNameAttr (WebAssemblyExportNameAttr * A)
TraverseWebAssemblyImportModuleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWebAssemblyImportModuleAttr (WebAssemblyImportModuleAttr * A)
TraverseWebAssemblyImportNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWebAssemblyImportNameAttr (WebAssemblyImportNameAttr * A)
TraverseWorkGroupSizeHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseWorkGroupSizeHintAttr (WorkGroupSizeHintAttr * A)
TraverseX86ForceAlignArgPointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseX86ForceAlignArgPointerAttr (X86ForceAlignArgPointerAttr * A)
TraverseXRayInstrumentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseXRayInstrumentAttr (XRayInstrumentAttr * A)
TraverseXRayLogArgsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::TraverseXRayLogArgsAttr (XRayLogArgsAttr * A)
VisitAArch64VectorPcsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAArch64VectorPcsAttr (AArch64VectorPcsAttr * A) inline
Definition at line 13 of file RecursiveASTVisitor.h.
VisitAbiTagAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAbiTagAttr (AbiTagAttr * A) inline
Definition at line 45 of file RecursiveASTVisitor.h.
VisitAcquireCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAcquireCapabilityAttr (AcquireCapabilityAttr * A) inline
Definition at line 49 of file RecursiveASTVisitor.h.
VisitAcquiredAfterAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAcquiredAfterAttr (AcquiredAfterAttr * A) inline
Definition at line 57 of file RecursiveASTVisitor.h.
VisitAcquiredBeforeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAcquiredBeforeAttr (AcquiredBeforeAttr * A) inline
Definition at line 61 of file RecursiveASTVisitor.h.
VisitAcquireHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAcquireHandleAttr (AcquireHandleAttr * A) inline
Definition at line 53 of file RecursiveASTVisitor.h.
VisitAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAddressSpaceAttr (AddressSpaceAttr * A) inline
Definition at line 65 of file RecursiveASTVisitor.h.
VisitAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAliasAttr (AliasAttr * A) inline
Definition at line 69 of file RecursiveASTVisitor.h.
VisitAlignedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlignedAttr (AlignedAttr * A) inline
Definition at line 85 of file RecursiveASTVisitor.h.
VisitAlignMac68kAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlignMac68kAttr (AlignMac68kAttr * A) inline
Definition at line 73 of file RecursiveASTVisitor.h.
VisitAlignNaturalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlignNaturalAttr (AlignNaturalAttr * A) inline
Definition at line 77 of file RecursiveASTVisitor.h.
VisitAlignValueAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlignValueAttr (AlignValueAttr * A) inline
Definition at line 81 of file RecursiveASTVisitor.h.
VisitAllocAlignAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAllocAlignAttr (AllocAlignAttr * A) inline
Definition at line 89 of file RecursiveASTVisitor.h.
VisitAllocSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAllocSizeAttr (AllocSizeAttr * A) inline
Definition at line 93 of file RecursiveASTVisitor.h.
VisitAlwaysDestroyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlwaysDestroyAttr (AlwaysDestroyAttr * A) inline
Definition at line 97 of file RecursiveASTVisitor.h.
VisitAlwaysInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAlwaysInlineAttr (AlwaysInlineAttr * A) inline
Definition at line 101 of file RecursiveASTVisitor.h.
VisitAMDGPUFlatWorkGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAMDGPUFlatWorkGroupSizeAttr (AMDGPUFlatWorkGroupSizeAttr * A) inline
Definition at line 17 of file RecursiveASTVisitor.h.
VisitAMDGPUNumSGPRAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAMDGPUNumSGPRAttr (AMDGPUNumSGPRAttr * A) inline
Definition at line 21 of file RecursiveASTVisitor.h.
VisitAMDGPUNumVGPRAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAMDGPUNumVGPRAttr (AMDGPUNumVGPRAttr * A) inline
Definition at line 25 of file RecursiveASTVisitor.h.
VisitAMDGPUWavesPerEUAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAMDGPUWavesPerEUAttr (AMDGPUWavesPerEUAttr * A) inline
Definition at line 29 of file RecursiveASTVisitor.h.
VisitAnalyzerNoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAnalyzerNoReturnAttr (AnalyzerNoReturnAttr * A) inline
Definition at line 105 of file RecursiveASTVisitor.h.
VisitAnnotateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAnnotateAttr (AnnotateAttr * A) inline
Definition at line 109 of file RecursiveASTVisitor.h.
VisitAnyX86InterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAnyX86InterruptAttr (AnyX86InterruptAttr * A) inline
Definition at line 113 of file RecursiveASTVisitor.h.
VisitAnyX86NoCallerSavedRegistersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAnyX86NoCallerSavedRegistersAttr (AnyX86NoCallerSavedRegistersAttr * A) inline
Definition at line 117 of file RecursiveASTVisitor.h.
VisitAnyX86NoCfCheckAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAnyX86NoCfCheckAttr (AnyX86NoCfCheckAttr * A) inline
Definition at line 121 of file RecursiveASTVisitor.h.
VisitArcWeakrefUnavailableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitArcWeakrefUnavailableAttr (ArcWeakrefUnavailableAttr * A) inline
Definition at line 125 of file RecursiveASTVisitor.h.
VisitArgumentWithTypeTagAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitArgumentWithTypeTagAttr (ArgumentWithTypeTagAttr * A) inline
Definition at line 129 of file RecursiveASTVisitor.h.
VisitArmBuiltinAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitArmBuiltinAliasAttr (ArmBuiltinAliasAttr * A) inline
Definition at line 133 of file RecursiveASTVisitor.h.
VisitARMInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitARMInterruptAttr (ARMInterruptAttr * A) inline
Definition at line 33 of file RecursiveASTVisitor.h.
VisitArmMveStrictPolymorphismAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitArmMveStrictPolymorphismAttr (ArmMveStrictPolymorphismAttr * A) inline
Definition at line 137 of file RecursiveASTVisitor.h.
VisitArtificialAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitArtificialAttr (ArtificialAttr * A) inline
Definition at line 141 of file RecursiveASTVisitor.h.
VisitAsmLabelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAsmLabelAttr (AsmLabelAttr * A) inline
Definition at line 145 of file RecursiveASTVisitor.h.
VisitAssertCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAssertCapabilityAttr (AssertCapabilityAttr * A) inline
Definition at line 149 of file RecursiveASTVisitor.h.
VisitAssertExclusiveLockAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAssertExclusiveLockAttr (AssertExclusiveLockAttr * A) inline
Definition at line 153 of file RecursiveASTVisitor.h.
VisitAssertSharedLockAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAssertSharedLockAttr (AssertSharedLockAttr * A) inline
Definition at line 157 of file RecursiveASTVisitor.h.
VisitAssumeAlignedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAssumeAlignedAttr (AssumeAlignedAttr * A) inline
Definition at line 161 of file RecursiveASTVisitor.h.
VisitAssumptionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAssumptionAttr (AssumptionAttr * A) inline
Definition at line 165 of file RecursiveASTVisitor.h.
VisitAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAttr (Attr * A) inline
Definition at line 332 of file RecursiveASTVisitor.h.
VisitAvailabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAvailabilityAttr (AvailabilityAttr * A) inline
Definition at line 169 of file RecursiveASTVisitor.h.
VisitAVRInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAVRInterruptAttr (AVRInterruptAttr * A) inline
Definition at line 37 of file RecursiveASTVisitor.h.
VisitAVRSignalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitAVRSignalAttr (AVRSignalAttr * A) inline
Definition at line 41 of file RecursiveASTVisitor.h.
VisitBlocksAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitBlocksAttr (BlocksAttr * A) inline
Definition at line 177 of file RecursiveASTVisitor.h.
VisitBPFPreserveAccessIndexAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitBPFPreserveAccessIndexAttr (BPFPreserveAccessIndexAttr * A) inline
Definition at line 173 of file RecursiveASTVisitor.h.
VisitBuiltinAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitBuiltinAttr (BuiltinAttr * A) inline
Definition at line 181 of file RecursiveASTVisitor.h.
VisitC11NoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitC11NoReturnAttr (C11NoReturnAttr * A) inline
Definition at line 185 of file RecursiveASTVisitor.h.
VisitCallableWhenAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCallableWhenAttr (CallableWhenAttr * A) inline
Definition at line 269 of file RecursiveASTVisitor.h.
VisitCallbackAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCallbackAttr (CallbackAttr * A) inline
Definition at line 273 of file RecursiveASTVisitor.h.
VisitCalledOnceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCalledOnceAttr (CalledOnceAttr * A) inline
Definition at line 277 of file RecursiveASTVisitor.h.
VisitCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCapabilityAttr (CapabilityAttr * A) inline
Definition at line 281 of file RecursiveASTVisitor.h.
VisitCapturedRecordAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCapturedRecordAttr (CapturedRecordAttr * A) inline
Definition at line 285 of file RecursiveASTVisitor.h.
VisitCarriesDependencyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCarriesDependencyAttr (CarriesDependencyAttr * A) inline
Definition at line 289 of file RecursiveASTVisitor.h.
VisitCDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCDeclAttr (CDeclAttr * A) inline
Definition at line 189 of file RecursiveASTVisitor.h.
VisitCFAuditedTransferAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFAuditedTransferAttr (CFAuditedTransferAttr * A) inline
Definition at line 193 of file RecursiveASTVisitor.h.
VisitCFConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFConsumedAttr (CFConsumedAttr * A) inline
Definition at line 197 of file RecursiveASTVisitor.h.
VisitCFGuardAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFGuardAttr (CFGuardAttr * A) inline
Definition at line 201 of file RecursiveASTVisitor.h.
VisitCFICanonicalJumpTableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFICanonicalJumpTableAttr (CFICanonicalJumpTableAttr * A) inline
Definition at line 205 of file RecursiveASTVisitor.h.
VisitCFReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFReturnsNotRetainedAttr (CFReturnsNotRetainedAttr * A) inline
Definition at line 209 of file RecursiveASTVisitor.h.
VisitCFReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFReturnsRetainedAttr (CFReturnsRetainedAttr * A) inline
Definition at line 213 of file RecursiveASTVisitor.h.
VisitCFUnknownTransferAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCFUnknownTransferAttr (CFUnknownTransferAttr * A) inline
Definition at line 217 of file RecursiveASTVisitor.h.
VisitCleanupAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCleanupAttr (CleanupAttr * A) inline
Definition at line 293 of file RecursiveASTVisitor.h.
VisitCmseNSCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCmseNSCallAttr (CmseNSCallAttr * A) inline
Definition at line 297 of file RecursiveASTVisitor.h.
VisitCmseNSEntryAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCmseNSEntryAttr (CmseNSEntryAttr * A) inline
Definition at line 301 of file RecursiveASTVisitor.h.
VisitCodeSegAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCodeSegAttr (CodeSegAttr * A) inline
Definition at line 305 of file RecursiveASTVisitor.h.
VisitColdAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitColdAttr (ColdAttr * A) inline
Definition at line 309 of file RecursiveASTVisitor.h.
VisitCommonAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCommonAttr (CommonAttr * A) inline
Definition at line 313 of file RecursiveASTVisitor.h.
VisitConstAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConstAttr (ConstAttr * A) inline
Definition at line 317 of file RecursiveASTVisitor.h.
VisitConstInitAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConstInitAttr (ConstInitAttr * A) inline
Definition at line 321 of file RecursiveASTVisitor.h.
VisitConstructorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConstructorAttr (ConstructorAttr * A) inline
Definition at line 325 of file RecursiveASTVisitor.h.
VisitConsumableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConsumableAttr (ConsumableAttr * A) inline
Definition at line 329 of file RecursiveASTVisitor.h.
VisitConsumableAutoCastAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConsumableAutoCastAttr (ConsumableAutoCastAttr * A) inline
Definition at line 333 of file RecursiveASTVisitor.h.
VisitConsumableSetOnReadAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConsumableSetOnReadAttr (ConsumableSetOnReadAttr * A) inline
Definition at line 337 of file RecursiveASTVisitor.h.
VisitConvergentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitConvergentAttr (ConvergentAttr * A) inline
Definition at line 341 of file RecursiveASTVisitor.h.
VisitCPUDispatchAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCPUDispatchAttr (CPUDispatchAttr * A) inline
Definition at line 221 of file RecursiveASTVisitor.h.
VisitCPUSpecificAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCPUSpecificAttr (CPUSpecificAttr * A) inline
Definition at line 225 of file RecursiveASTVisitor.h.
VisitCUDAConstantAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDAConstantAttr (CUDAConstantAttr * A) inline
Definition at line 229 of file RecursiveASTVisitor.h.
VisitCUDADeviceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDADeviceAttr (CUDADeviceAttr * A) inline
Definition at line 233 of file RecursiveASTVisitor.h.
VisitCUDADeviceBuiltinSurfaceTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDADeviceBuiltinSurfaceTypeAttr (CUDADeviceBuiltinSurfaceTypeAttr * A) inline
Definition at line 237 of file RecursiveASTVisitor.h.
VisitCUDADeviceBuiltinTextureTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDADeviceBuiltinTextureTypeAttr (CUDADeviceBuiltinTextureTypeAttr * A) inline
Definition at line 241 of file RecursiveASTVisitor.h.
VisitCUDAGlobalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDAGlobalAttr (CUDAGlobalAttr * A) inline
Definition at line 245 of file RecursiveASTVisitor.h.
VisitCUDAHostAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDAHostAttr (CUDAHostAttr * A) inline
Definition at line 249 of file RecursiveASTVisitor.h.
VisitCUDAInvalidTargetAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDAInvalidTargetAttr (CUDAInvalidTargetAttr * A) inline
Definition at line 253 of file RecursiveASTVisitor.h.
VisitCUDALaunchBoundsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDALaunchBoundsAttr (CUDALaunchBoundsAttr * A) inline
Definition at line 257 of file RecursiveASTVisitor.h.
VisitCUDASharedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCUDASharedAttr (CUDASharedAttr * A) inline
Definition at line 261 of file RecursiveASTVisitor.h.
VisitCXX11NoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitCXX11NoReturnAttr (CXX11NoReturnAttr * A) inline
Definition at line 265 of file RecursiveASTVisitor.h.
VisitDecl()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDecl (Decl * D) inline
Definition at line 455 of file RecursiveASTVisitor.h.
VisitDeprecatedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDeprecatedAttr (DeprecatedAttr * A) inline
Definition at line 361 of file RecursiveASTVisitor.h.
VisitDestructorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDestructorAttr (DestructorAttr * A) inline
Definition at line 365 of file RecursiveASTVisitor.h.
VisitDiagnoseIfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDiagnoseIfAttr (DiagnoseIfAttr * A) inline
Definition at line 369 of file RecursiveASTVisitor.h.
VisitDisableTailCallsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDisableTailCallsAttr (DisableTailCallsAttr * A) inline
Definition at line 373 of file RecursiveASTVisitor.h.
VisitDLLExportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDLLExportAttr (DLLExportAttr * A) inline
Definition at line 345 of file RecursiveASTVisitor.h.
VisitDLLExportStaticLocalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDLLExportStaticLocalAttr (DLLExportStaticLocalAttr * A) inline
Definition at line 349 of file RecursiveASTVisitor.h.
VisitDLLImportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDLLImportAttr (DLLImportAttr * A) inline
Definition at line 353 of file RecursiveASTVisitor.h.
VisitDLLImportStaticLocalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitDLLImportStaticLocalAttr (DLLImportStaticLocalAttr * A) inline
Definition at line 357 of file RecursiveASTVisitor.h.
VisitEmptyBasesAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitEmptyBasesAttr (EmptyBasesAttr * A) inline
Definition at line 377 of file RecursiveASTVisitor.h.
VisitEnableIfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitEnableIfAttr (EnableIfAttr * A) inline
Definition at line 381 of file RecursiveASTVisitor.h.
VisitEnforceTCBAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitEnforceTCBAttr (EnforceTCBAttr * A) inline
Definition at line 385 of file RecursiveASTVisitor.h.
VisitEnforceTCBLeafAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitEnforceTCBLeafAttr (EnforceTCBLeafAttr * A) inline
Definition at line 389 of file RecursiveASTVisitor.h.
VisitEnumExtensibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitEnumExtensibilityAttr (EnumExtensibilityAttr * A) inline
Definition at line 393 of file RecursiveASTVisitor.h.
VisitExcludeFromExplicitInstantiationAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitExcludeFromExplicitInstantiationAttr (ExcludeFromExplicitInstantiationAttr * A) inline
Definition at line 397 of file RecursiveASTVisitor.h.
VisitExclusiveTrylockFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitExclusiveTrylockFunctionAttr (ExclusiveTrylockFunctionAttr * A) inline
Definition at line 401 of file RecursiveASTVisitor.h.
VisitExternalSourceSymbolAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitExternalSourceSymbolAttr (ExternalSourceSymbolAttr * A) inline
Definition at line 405 of file RecursiveASTVisitor.h.
VisitFallThroughAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFallThroughAttr (FallThroughAttr * A) inline
Definition at line 409 of file RecursiveASTVisitor.h.
VisitFastCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFastCallAttr (FastCallAttr * A) inline
Definition at line 413 of file RecursiveASTVisitor.h.
VisitFinalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFinalAttr (FinalAttr * A) inline
Definition at line 417 of file RecursiveASTVisitor.h.
VisitFlagEnumAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFlagEnumAttr (FlagEnumAttr * A) inline
Definition at line 421 of file RecursiveASTVisitor.h.
References clang::RecursiveASTVisitor< Derived >::getDerived().
VisitFlattenAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFlattenAttr (FlattenAttr * A) inline
Definition at line 425 of file RecursiveASTVisitor.h.
VisitFormatArgAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFormatArgAttr (FormatArgAttr * A) inline
Definition at line 433 of file RecursiveASTVisitor.h.
VisitFormatAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitFormatAttr (FormatAttr * A) inline
Definition at line 429 of file RecursiveASTVisitor.h.
VisitGNUInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitGNUInlineAttr (GNUInlineAttr * A) inline
Definition at line 437 of file RecursiveASTVisitor.h.
VisitGuardedByAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitGuardedByAttr (GuardedByAttr * A) inline
Definition at line 441 of file RecursiveASTVisitor.h.
VisitGuardedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitGuardedVarAttr (GuardedVarAttr * A) inline
Definition at line 445 of file RecursiveASTVisitor.h.
VisitHIPManagedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitHIPManagedAttr (HIPManagedAttr * A) inline
Definition at line 449 of file RecursiveASTVisitor.h.
VisitHotAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitHotAttr (HotAttr * A) inline
Definition at line 453 of file RecursiveASTVisitor.h.
VisitIBActionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitIBActionAttr (IBActionAttr * A) inline
Definition at line 457 of file RecursiveASTVisitor.h.
VisitIBOutletAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitIBOutletAttr (IBOutletAttr * A) inline
Definition at line 461 of file RecursiveASTVisitor.h.
VisitIBOutletCollectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitIBOutletCollectionAttr (IBOutletCollectionAttr * A) inline
Definition at line 465 of file RecursiveASTVisitor.h.
VisitIFuncAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitIFuncAttr (IFuncAttr * A) inline
Definition at line 469 of file RecursiveASTVisitor.h.
VisitInitPriorityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitInitPriorityAttr (InitPriorityAttr * A) inline
Definition at line 473 of file RecursiveASTVisitor.h.
VisitInitSegAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitInitSegAttr (InitSegAttr * A) inline
Definition at line 477 of file RecursiveASTVisitor.h.
VisitIntelOclBiccAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitIntelOclBiccAttr (IntelOclBiccAttr * A) inline
Definition at line 481 of file RecursiveASTVisitor.h.
VisitInternalLinkageAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitInternalLinkageAttr (InternalLinkageAttr * A) inline
Definition at line 485 of file RecursiveASTVisitor.h.
VisitLayoutVersionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLayoutVersionAttr (LayoutVersionAttr * A) inline
Definition at line 493 of file RecursiveASTVisitor.h.
VisitLeafAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLeafAttr (LeafAttr * A) inline
Definition at line 497 of file RecursiveASTVisitor.h.
VisitLifetimeBoundAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLifetimeBoundAttr (LifetimeBoundAttr * A) inline
Definition at line 501 of file RecursiveASTVisitor.h.
VisitLikelyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLikelyAttr (LikelyAttr * A) inline
Definition at line 505 of file RecursiveASTVisitor.h.
VisitLoaderUninitializedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLoaderUninitializedAttr (LoaderUninitializedAttr * A) inline
Definition at line 509 of file RecursiveASTVisitor.h.
VisitLockReturnedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLockReturnedAttr (LockReturnedAttr * A) inline
Definition at line 513 of file RecursiveASTVisitor.h.
VisitLocksExcludedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLocksExcludedAttr (LocksExcludedAttr * A) inline
Definition at line 517 of file RecursiveASTVisitor.h.
VisitLoopHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLoopHintAttr (LoopHintAttr * A) inline
Definition at line 521 of file RecursiveASTVisitor.h.
VisitLTOVisibilityPublicAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitLTOVisibilityPublicAttr (LTOVisibilityPublicAttr * A) inline
Definition at line 489 of file RecursiveASTVisitor.h.
VisitMaxFieldAlignmentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMaxFieldAlignmentAttr (MaxFieldAlignmentAttr * A) inline
Definition at line 557 of file RecursiveASTVisitor.h.
VisitMayAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMayAliasAttr (MayAliasAttr * A) inline
Definition at line 561 of file RecursiveASTVisitor.h.
VisitMicroMipsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMicroMipsAttr (MicroMipsAttr * A) inline
Definition at line 565 of file RecursiveASTVisitor.h.
VisitMIGServerRoutineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMIGServerRoutineAttr (MIGServerRoutineAttr * A) inline
Definition at line 525 of file RecursiveASTVisitor.h.
VisitMinSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMinSizeAttr (MinSizeAttr * A) inline
Definition at line 569 of file RecursiveASTVisitor.h.
VisitMinVectorWidthAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMinVectorWidthAttr (MinVectorWidthAttr * A) inline
Definition at line 573 of file RecursiveASTVisitor.h.
VisitMips16Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMips16Attr (Mips16Attr * A) inline
Definition at line 577 of file RecursiveASTVisitor.h.
VisitMipsInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMipsInterruptAttr (MipsInterruptAttr * A) inline
Definition at line 581 of file RecursiveASTVisitor.h.
VisitMipsLongCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMipsLongCallAttr (MipsLongCallAttr * A) inline
Definition at line 585 of file RecursiveASTVisitor.h.
VisitMipsShortCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMipsShortCallAttr (MipsShortCallAttr * A) inline
Definition at line 589 of file RecursiveASTVisitor.h.
VisitModeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitModeAttr (ModeAttr * A) inline
Definition at line 593 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitMSABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSABIAttr (MSABIAttr * A) inline
Definition at line 529 of file RecursiveASTVisitor.h.
VisitMSAllocatorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSAllocatorAttr (MSAllocatorAttr * A) inline
Definition at line 533 of file RecursiveASTVisitor.h.
VisitMSInheritanceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSInheritanceAttr (MSInheritanceAttr * A) inline
Definition at line 537 of file RecursiveASTVisitor.h.
VisitMSNoVTableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSNoVTableAttr (MSNoVTableAttr * A) inline
Definition at line 541 of file RecursiveASTVisitor.h.
VisitMSP430InterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSP430InterruptAttr (MSP430InterruptAttr * A) inline
Definition at line 545 of file RecursiveASTVisitor.h.
References clang::Stmt::NoStmtClass.
VisitMSStructAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSStructAttr (MSStructAttr * A) inline
Definition at line 549 of file RecursiveASTVisitor.h.
VisitMSVtorDispAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitMSVtorDispAttr (MSVtorDispAttr * A) inline
Definition at line 553 of file RecursiveASTVisitor.h.
VisitNakedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNakedAttr (NakedAttr * A) inline
Definition at line 621 of file RecursiveASTVisitor.h.
VisitNoAliasAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoAliasAttr (NoAliasAttr * A) inline
Definition at line 625 of file RecursiveASTVisitor.h.
VisitNoBuiltinAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoBuiltinAttr (NoBuiltinAttr * A) inline
Definition at line 629 of file RecursiveASTVisitor.h.
VisitNoCommonAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoCommonAttr (NoCommonAttr * A) inline
Definition at line 633 of file RecursiveASTVisitor.h.
VisitNoDebugAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoDebugAttr (NoDebugAttr * A) inline
Definition at line 637 of file RecursiveASTVisitor.h.
VisitNoDerefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoDerefAttr (NoDerefAttr * A) inline
Definition at line 641 of file RecursiveASTVisitor.h.
VisitNoDestroyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoDestroyAttr (NoDestroyAttr * A) inline
Definition at line 645 of file RecursiveASTVisitor.h.
VisitNoDuplicateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoDuplicateAttr (NoDuplicateAttr * A) inline
Definition at line 649 of file RecursiveASTVisitor.h.
VisitNoEscapeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoEscapeAttr (NoEscapeAttr * A) inline
Definition at line 653 of file RecursiveASTVisitor.h.
VisitNoInlineAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoInlineAttr (NoInlineAttr * A) inline
Definition at line 657 of file RecursiveASTVisitor.h.
VisitNoInstrumentFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoInstrumentFunctionAttr (NoInstrumentFunctionAttr * A) inline
Definition at line 661 of file RecursiveASTVisitor.h.
VisitNoMergeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoMergeAttr (NoMergeAttr * A) inline
Definition at line 665 of file RecursiveASTVisitor.h.
VisitNoMicroMipsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoMicroMipsAttr (NoMicroMipsAttr * A) inline
Definition at line 669 of file RecursiveASTVisitor.h.
VisitNoMips16Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoMips16Attr (NoMips16Attr * A) inline
Definition at line 673 of file RecursiveASTVisitor.h.
VisitNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNonNullAttr (NonNullAttr * A) inline
Definition at line 709 of file RecursiveASTVisitor.h.
References clang::NestedNameSpecifier::Identifier.
VisitNoReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoReturnAttr (NoReturnAttr * A) inline
Definition at line 677 of file RecursiveASTVisitor.h.
VisitNoSanitizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoSanitizeAttr (NoSanitizeAttr * A) inline
Definition at line 681 of file RecursiveASTVisitor.h.
VisitNoSpeculativeLoadHardeningAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoSpeculativeLoadHardeningAttr (NoSpeculativeLoadHardeningAttr * A) inline
Definition at line 685 of file RecursiveASTVisitor.h.
References clang::NestedNameSpecifier::Identifier, and clang::NestedNameSpecifier::Namespace.
VisitNoSplitStackAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoSplitStackAttr (NoSplitStackAttr * A) inline
Definition at line 689 of file RecursiveASTVisitor.h.
VisitNoStackProtectorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoStackProtectorAttr (NoStackProtectorAttr * A) inline
Definition at line 693 of file RecursiveASTVisitor.h.
VisitNoThreadSafetyAnalysisAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoThreadSafetyAnalysisAttr (NoThreadSafetyAnalysisAttr * A) inline
Definition at line 697 of file RecursiveASTVisitor.h.
VisitNoThrowAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoThrowAttr (NoThrowAttr * A) inline
Definition at line 701 of file RecursiveASTVisitor.h.
VisitNotTailCalledAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNotTailCalledAttr (NotTailCalledAttr * A) inline
Definition at line 713 of file RecursiveASTVisitor.h.
VisitNoUniqueAddressAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNoUniqueAddressAttr (NoUniqueAddressAttr * A) inline
Definition at line 705 of file RecursiveASTVisitor.h.
VisitNSConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSConsumedAttr (NSConsumedAttr * A) inline
Definition at line 597 of file RecursiveASTVisitor.h.
VisitNSConsumesSelfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSConsumesSelfAttr (NSConsumesSelfAttr * A) inline
Definition at line 601 of file RecursiveASTVisitor.h.
VisitNSErrorDomainAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSErrorDomainAttr (NSErrorDomainAttr * A) inline
Definition at line 605 of file RecursiveASTVisitor.h.
VisitNSReturnsAutoreleasedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSReturnsAutoreleasedAttr (NSReturnsAutoreleasedAttr * A) inline
Definition at line 609 of file RecursiveASTVisitor.h.
VisitNSReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSReturnsNotRetainedAttr (NSReturnsNotRetainedAttr * A) inline
Definition at line 613 of file RecursiveASTVisitor.h.
VisitNSReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitNSReturnsRetainedAttr (NSReturnsRetainedAttr * A) inline
Definition at line 617 of file RecursiveASTVisitor.h.
VisitObjCBoxableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCBoxableAttr (ObjCBoxableAttr * A) inline
Definition at line 773 of file RecursiveASTVisitor.h.
VisitObjCBridgeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCBridgeAttr (ObjCBridgeAttr * A) inline
Definition at line 777 of file RecursiveASTVisitor.h.
VisitObjCBridgeMutableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCBridgeMutableAttr (ObjCBridgeMutableAttr * A) inline
Definition at line 781 of file RecursiveASTVisitor.h.
VisitObjCBridgeRelatedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCBridgeRelatedAttr (ObjCBridgeRelatedAttr * A) inline
Definition at line 785 of file RecursiveASTVisitor.h.
VisitObjCClassStubAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCClassStubAttr (ObjCClassStubAttr * A) inline
Definition at line 789 of file RecursiveASTVisitor.h.
VisitObjCDesignatedInitializerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCDesignatedInitializerAttr (ObjCDesignatedInitializerAttr * A) inline
Definition at line 793 of file RecursiveASTVisitor.h.
VisitObjCDirectAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCDirectAttr (ObjCDirectAttr * A) inline
Definition at line 797 of file RecursiveASTVisitor.h.
VisitObjCDirectMembersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCDirectMembersAttr (ObjCDirectMembersAttr * A) inline
Definition at line 801 of file RecursiveASTVisitor.h.
References clang::TemplateArgument::Null.
VisitObjCExceptionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCExceptionAttr (ObjCExceptionAttr * A) inline
Definition at line 805 of file RecursiveASTVisitor.h.
VisitObjCExplicitProtocolImplAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCExplicitProtocolImplAttr (ObjCExplicitProtocolImplAttr * A) inline
Definition at line 809 of file RecursiveASTVisitor.h.
References clang::TemplateArgumentLoc::getTypeSourceInfo().
VisitObjCExternallyRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCExternallyRetainedAttr (ObjCExternallyRetainedAttr * A) inline
Definition at line 813 of file RecursiveASTVisitor.h.
VisitObjCGCAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCGCAttr (ObjCGCAttr * A) inline
Definition at line 817 of file RecursiveASTVisitor.h.
VisitObjCIndependentClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCIndependentClassAttr (ObjCIndependentClassAttr * A) inline
Definition at line 821 of file RecursiveASTVisitor.h.
VisitObjCInertUnsafeUnretainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCInertUnsafeUnretainedAttr (ObjCInertUnsafeUnretainedAttr * A) inline
Definition at line 825 of file RecursiveASTVisitor.h.
VisitObjCKindOfAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCKindOfAttr (ObjCKindOfAttr * A) inline
Definition at line 829 of file RecursiveASTVisitor.h.
VisitObjCMethodFamilyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCMethodFamilyAttr (ObjCMethodFamilyAttr * A) inline
Definition at line 833 of file RecursiveASTVisitor.h.
VisitObjCNonLazyClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCNonLazyClassAttr (ObjCNonLazyClassAttr * A) inline
Definition at line 841 of file RecursiveASTVisitor.h.
VisitObjCNonRuntimeProtocolAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCNonRuntimeProtocolAttr (ObjCNonRuntimeProtocolAttr * A) inline
Definition at line 845 of file RecursiveASTVisitor.h.
VisitObjCNSObjectAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCNSObjectAttr (ObjCNSObjectAttr * A) inline
Definition at line 837 of file RecursiveASTVisitor.h.
VisitObjCOwnershipAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCOwnershipAttr (ObjCOwnershipAttr * A) inline
Definition at line 849 of file RecursiveASTVisitor.h.
VisitObjCPreciseLifetimeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCPreciseLifetimeAttr (ObjCPreciseLifetimeAttr * A) inline
Definition at line 853 of file RecursiveASTVisitor.h.
VisitObjCRequiresPropertyDefsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCRequiresPropertyDefsAttr (ObjCRequiresPropertyDefsAttr * A) inline
Definition at line 857 of file RecursiveASTVisitor.h.
VisitObjCRequiresSuperAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCRequiresSuperAttr (ObjCRequiresSuperAttr * A) inline
Definition at line 861 of file RecursiveASTVisitor.h.
References clang::C.
VisitObjCReturnsInnerPointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCReturnsInnerPointerAttr (ObjCReturnsInnerPointerAttr * A) inline
Definition at line 865 of file RecursiveASTVisitor.h.
VisitObjCRootClassAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCRootClassAttr (ObjCRootClassAttr * A) inline
Definition at line 869 of file RecursiveASTVisitor.h.
VisitObjCRuntimeNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCRuntimeNameAttr (ObjCRuntimeNameAttr * A) inline
Definition at line 873 of file RecursiveASTVisitor.h.
VisitObjCRuntimeVisibleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCRuntimeVisibleAttr (ObjCRuntimeVisibleAttr * A) inline
Definition at line 877 of file RecursiveASTVisitor.h.
VisitObjCSubclassingRestrictedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitObjCSubclassingRestrictedAttr (ObjCSubclassingRestrictedAttr * A) inline
Definition at line 881 of file RecursiveASTVisitor.h.
VisitOMPAllocateDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPAllocateDeclAttr (OMPAllocateDeclAttr * A) inline
Definition at line 717 of file RecursiveASTVisitor.h.
VisitOMPCaptureKindAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPCaptureKindAttr (OMPCaptureKindAttr * A) inline
Definition at line 721 of file RecursiveASTVisitor.h.
VisitOMPCaptureNoInitAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPCaptureNoInitAttr (OMPCaptureNoInitAttr * A) inline
Definition at line 725 of file RecursiveASTVisitor.h.
VisitOMPDeclareSimdDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPDeclareSimdDeclAttr (OMPDeclareSimdDeclAttr * A) inline
Definition at line 729 of file RecursiveASTVisitor.h.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationNameInfo::getName(), and clang::DeclarationName::getNameKind().
VisitOMPDeclareTargetDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPDeclareTargetDeclAttr (OMPDeclareTargetDeclAttr * A) inline
Definition at line 733 of file RecursiveASTVisitor.h.
VisitOMPDeclareVariantAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPDeclareVariantAttr (OMPDeclareVariantAttr * A) inline
Definition at line 737 of file RecursiveASTVisitor.h.
VisitOMPReferencedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPReferencedVarAttr (OMPReferencedVarAttr * A) inline
Definition at line 741 of file RecursiveASTVisitor.h.
VisitOMPThreadPrivateDeclAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOMPThreadPrivateDeclAttr (OMPThreadPrivateDeclAttr * A) inline
Definition at line 745 of file RecursiveASTVisitor.h.
VisitOpenCLAccessAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLAccessAttr (OpenCLAccessAttr * A) inline
Definition at line 885 of file RecursiveASTVisitor.h.
VisitOpenCLConstantAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLConstantAddressSpaceAttr (OpenCLConstantAddressSpaceAttr * A) inline
Definition at line 889 of file RecursiveASTVisitor.h.
VisitOpenCLGenericAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLGenericAddressSpaceAttr (OpenCLGenericAddressSpaceAttr * A) inline
Definition at line 893 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLGlobalAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLGlobalAddressSpaceAttr (OpenCLGlobalAddressSpaceAttr * A) inline
Definition at line 897 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLGlobalDeviceAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLGlobalDeviceAddressSpaceAttr (OpenCLGlobalDeviceAddressSpaceAttr * A) inline
Definition at line 901 of file RecursiveASTVisitor.h.
VisitOpenCLGlobalHostAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLGlobalHostAddressSpaceAttr (OpenCLGlobalHostAddressSpaceAttr * A) inline
Definition at line 905 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLIntelReqdSubGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLIntelReqdSubGroupSizeAttr (OpenCLIntelReqdSubGroupSizeAttr * A) inline
Definition at line 909 of file RecursiveASTVisitor.h.
VisitOpenCLKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLKernelAttr (OpenCLKernelAttr * A) inline
Definition at line 913 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLLocalAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLLocalAddressSpaceAttr (OpenCLLocalAddressSpaceAttr * A) inline
Definition at line 917 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLPrivateAddressSpaceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLPrivateAddressSpaceAttr (OpenCLPrivateAddressSpaceAttr * A) inline
Definition at line 921 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOpenCLUnrollHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOpenCLUnrollHintAttr (OpenCLUnrollHintAttr * A) inline
Definition at line 925 of file RecursiveASTVisitor.h.
VisitOptimizeNoneAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOptimizeNoneAttr (OptimizeNoneAttr * A) inline
Definition at line 929 of file RecursiveASTVisitor.h.
VisitOSConsumedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSConsumedAttr (OSConsumedAttr * A) inline
Definition at line 749 of file RecursiveASTVisitor.h.
VisitOSConsumesThisAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSConsumesThisAttr (OSConsumesThisAttr * A) inline
Definition at line 753 of file RecursiveASTVisitor.h.
VisitOSReturnsNotRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSReturnsNotRetainedAttr (OSReturnsNotRetainedAttr * A) inline
Definition at line 757 of file RecursiveASTVisitor.h.
VisitOSReturnsRetainedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSReturnsRetainedAttr (OSReturnsRetainedAttr * A) inline
Definition at line 761 of file RecursiveASTVisitor.h.
VisitOSReturnsRetainedOnNonZeroAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSReturnsRetainedOnNonZeroAttr (OSReturnsRetainedOnNonZeroAttr * A) inline
Definition at line 765 of file RecursiveASTVisitor.h.
VisitOSReturnsRetainedOnZeroAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOSReturnsRetainedOnZeroAttr (OSReturnsRetainedOnZeroAttr * A) inline
Definition at line 769 of file RecursiveASTVisitor.h.
References clang::TemplateArgument::Declaration, and clang::TemplateArgument::Null.
VisitOverloadableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOverloadableAttr (OverloadableAttr * A) inline
Definition at line 933 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitOverrideAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOverrideAttr (OverrideAttr * A) inline
Definition at line 937 of file RecursiveASTVisitor.h.
VisitOwnerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOwnerAttr (OwnerAttr * A) inline
Definition at line 941 of file RecursiveASTVisitor.h.
VisitOwnershipAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitOwnershipAttr (OwnershipAttr * A) inline
Definition at line 945 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPackedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPackedAttr (PackedAttr * A) inline
Definition at line 949 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitParamTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitParamTypestateAttr (ParamTypestateAttr * A) inline
Definition at line 953 of file RecursiveASTVisitor.h.
VisitPascalAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPascalAttr (PascalAttr * A) inline
Definition at line 957 of file RecursiveASTVisitor.h.
VisitPassObjectSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPassObjectSizeAttr (PassObjectSizeAttr * A) inline
Definition at line 961 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPatchableFunctionEntryAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPatchableFunctionEntryAttr (PatchableFunctionEntryAttr * A) inline
Definition at line 965 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPcsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPcsAttr (PcsAttr * A) inline
Definition at line 969 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPointerAttr (PointerAttr * A) inline
Definition at line 973 of file RecursiveASTVisitor.h.
VisitPragmaClangBSSSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPragmaClangBSSSectionAttr (PragmaClangBSSSectionAttr * A) inline
Definition at line 977 of file RecursiveASTVisitor.h.
VisitPragmaClangDataSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPragmaClangDataSectionAttr (PragmaClangDataSectionAttr * A) inline
Definition at line 981 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPragmaClangRelroSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPragmaClangRelroSectionAttr (PragmaClangRelroSectionAttr * A) inline
Definition at line 985 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPragmaClangRodataSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPragmaClangRodataSectionAttr (PragmaClangRodataSectionAttr * A) inline
Definition at line 989 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPragmaClangTextSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPragmaClangTextSectionAttr (PragmaClangTextSectionAttr * A) inline
Definition at line 993 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPreferredNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPreferredNameAttr (PreferredNameAttr * A) inline
Definition at line 997 of file RecursiveASTVisitor.h.
VisitPreserveAllAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPreserveAllAttr (PreserveAllAttr * A) inline
Definition at line 1001 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPreserveMostAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPreserveMostAttr (PreserveMostAttr * A) inline
Definition at line 1005 of file RecursiveASTVisitor.h.
VisitPtGuardedByAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPtGuardedByAttr (PtGuardedByAttr * A) inline
Definition at line 1009 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitPtGuardedVarAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPtGuardedVarAttr (PtGuardedVarAttr * A) inline
Definition at line 1013 of file RecursiveASTVisitor.h.
VisitPtr32Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPtr32Attr (Ptr32Attr * A) inline
Definition at line 1017 of file RecursiveASTVisitor.h.
VisitPtr64Attr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPtr64Attr (Ptr64Attr * A) inline
Definition at line 1021 of file RecursiveASTVisitor.h.
VisitPureAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitPureAttr (PureAttr * A) inline
Definition at line 1025 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitQualifiedTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitQualifiedTypeLoc (QualifiedTypeLoc TL) inline
Definition at line 429 of file RecursiveASTVisitor.h.
VisitRegCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitRegCallAttr (RegCallAttr * A) inline
Definition at line 1033 of file RecursiveASTVisitor.h.
VisitReinitializesAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReinitializesAttr (ReinitializesAttr * A) inline
Definition at line 1037 of file RecursiveASTVisitor.h.
VisitReleaseCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReleaseCapabilityAttr (ReleaseCapabilityAttr * A) inline
Definition at line 1041 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitReleaseHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReleaseHandleAttr (ReleaseHandleAttr * A) inline
Definition at line 1045 of file RecursiveASTVisitor.h.
VisitRenderScriptKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitRenderScriptKernelAttr (RenderScriptKernelAttr * A) inline
Definition at line 1049 of file RecursiveASTVisitor.h.
VisitReqdWorkGroupSizeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReqdWorkGroupSizeAttr (ReqdWorkGroupSizeAttr * A) inline
Definition at line 1053 of file RecursiveASTVisitor.h.
VisitRequiresCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitRequiresCapabilityAttr (RequiresCapabilityAttr * A) inline
Definition at line 1057 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitRestrictAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitRestrictAttr (RestrictAttr * A) inline
Definition at line 1061 of file RecursiveASTVisitor.h.
VisitReturnsNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReturnsNonNullAttr (ReturnsNonNullAttr * A) inline
Definition at line 1069 of file RecursiveASTVisitor.h.
VisitReturnsTwiceAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReturnsTwiceAttr (ReturnsTwiceAttr * A) inline
Definition at line 1073 of file RecursiveASTVisitor.h.
VisitReturnTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitReturnTypestateAttr (ReturnTypestateAttr * A) inline
Definition at line 1065 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitRISCVInterruptAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitRISCVInterruptAttr (RISCVInterruptAttr * A) inline
Definition at line 1029 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitScopedLockableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitScopedLockableAttr (ScopedLockableAttr * A) inline
Definition at line 1085 of file RecursiveASTVisitor.h.
References TYPE.
VisitSectionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSectionAttr (SectionAttr * A) inline
Definition at line 1089 of file RecursiveASTVisitor.h.
VisitSelectAnyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSelectAnyAttr (SelectAnyAttr * A) inline
Definition at line 1093 of file RecursiveASTVisitor.h.
VisitSentinelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSentinelAttr (SentinelAttr * A) inline
Definition at line 1097 of file RecursiveASTVisitor.h.
VisitSetTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSetTypestateAttr (SetTypestateAttr * A) inline
Definition at line 1101 of file RecursiveASTVisitor.h.
VisitSharedTrylockFunctionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSharedTrylockFunctionAttr (SharedTrylockFunctionAttr * A) inline
Definition at line 1105 of file RecursiveASTVisitor.h.
VisitSpeculativeLoadHardeningAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSpeculativeLoadHardeningAttr (SpeculativeLoadHardeningAttr * A) inline
Definition at line 1109 of file RecursiveASTVisitor.h.
VisitSPtrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSPtrAttr (SPtrAttr * A) inline
Definition at line 1077 of file RecursiveASTVisitor.h.
VisitStdCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitStdCallAttr (StdCallAttr * A) inline
Definition at line 1113 of file RecursiveASTVisitor.h.
VisitStmt()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitStmt (Stmt * S) inline
Definition at line 380 of file RecursiveASTVisitor.h.
VisitStrictFPAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitStrictFPAttr (StrictFPAttr * A) inline
Definition at line 1117 of file RecursiveASTVisitor.h.
VisitSuppressAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSuppressAttr (SuppressAttr * A) inline
Definition at line 1121 of file RecursiveASTVisitor.h.
VisitSwiftAsyncAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftAsyncAttr (SwiftAsyncAttr * A) inline
Definition at line 1125 of file RecursiveASTVisitor.h.
VisitSwiftAsyncNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftAsyncNameAttr (SwiftAsyncNameAttr * A) inline
Definition at line 1129 of file RecursiveASTVisitor.h.
VisitSwiftAttrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftAttrAttr (SwiftAttrAttr * A) inline
Definition at line 1133 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitSwiftBridgeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftBridgeAttr (SwiftBridgeAttr * A) inline
Definition at line 1137 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitSwiftBridgedTypedefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftBridgedTypedefAttr (SwiftBridgedTypedefAttr * A) inline
Definition at line 1141 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitSwiftCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftCallAttr (SwiftCallAttr * A) inline
Definition at line 1145 of file RecursiveASTVisitor.h.
VisitSwiftContextAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftContextAttr (SwiftContextAttr * A) inline
Definition at line 1149 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitSwiftErrorAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftErrorAttr (SwiftErrorAttr * A) inline
Definition at line 1153 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitSwiftErrorResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftErrorResultAttr (SwiftErrorResultAttr * A) inline
Definition at line 1157 of file RecursiveASTVisitor.h.
VisitSwiftIndirectResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftIndirectResultAttr (SwiftIndirectResultAttr * A) inline
Definition at line 1161 of file RecursiveASTVisitor.h.
VisitSwiftNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftNameAttr (SwiftNameAttr * A) inline
Definition at line 1165 of file RecursiveASTVisitor.h.
VisitSwiftNewTypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftNewTypeAttr (SwiftNewTypeAttr * A) inline
Definition at line 1169 of file RecursiveASTVisitor.h.
VisitSwiftObjCMembersAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftObjCMembersAttr (SwiftObjCMembersAttr * A) inline
Definition at line 1173 of file RecursiveASTVisitor.h.
VisitSwiftPrivateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSwiftPrivateAttr (SwiftPrivateAttr * A) inline
Definition at line 1177 of file RecursiveASTVisitor.h.
References clang::ArrayTypeLoc::getElementLoc(), and TRY_TO.
VisitSYCLKernelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSYCLKernelAttr (SYCLKernelAttr * A) inline
Definition at line 1081 of file RecursiveASTVisitor.h.
VisitSysVABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitSysVABIAttr (SysVABIAttr * A) inline
Definition at line 1181 of file RecursiveASTVisitor.h.
VisitTargetAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTargetAttr (TargetAttr * A) inline
Definition at line 1189 of file RecursiveASTVisitor.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and TRY_TO.
VisitTestTypestateAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTestTypestateAttr (TestTypestateAttr * A) inline
Definition at line 1193 of file RecursiveASTVisitor.h.
VisitThisCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitThisCallAttr (ThisCallAttr * A) inline
Definition at line 1197 of file RecursiveASTVisitor.h.
VisitThreadAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitThreadAttr (ThreadAttr * A) inline
Definition at line 1201 of file RecursiveASTVisitor.h.
VisitTLSModelAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTLSModelAttr (TLSModelAttr * A) inline
Definition at line 1185 of file RecursiveASTVisitor.h.
VisitTransparentUnionAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTransparentUnionAttr (TransparentUnionAttr * A) inline
Definition at line 1205 of file RecursiveASTVisitor.h.
VisitTrivialABIAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTrivialABIAttr (TrivialABIAttr * A) inline
Definition at line 1209 of file RecursiveASTVisitor.h.
VisitTryAcquireCapabilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTryAcquireCapabilityAttr (TryAcquireCapabilityAttr * A) inline
Definition at line 1213 of file RecursiveASTVisitor.h.
VisitType()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitType (Type * T) inline
Definition at line 401 of file RecursiveASTVisitor.h.
VisitTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeLoc (TypeLoc TL) inline
Definition at line 422 of file RecursiveASTVisitor.h.
VisitTypeNonNullAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeNonNullAttr (TypeNonNullAttr * A) inline
Definition at line 1217 of file RecursiveASTVisitor.h.
VisitTypeNullableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeNullableAttr (TypeNullableAttr * A) inline
Definition at line 1225 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitTypeNullableResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeNullableResultAttr (TypeNullableResultAttr * A) inline
Definition at line 1229 of file RecursiveASTVisitor.h.
VisitTypeNullUnspecifiedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeNullUnspecifiedAttr (TypeNullUnspecifiedAttr * A) inline
Definition at line 1221 of file RecursiveASTVisitor.h.
VisitTypeTagForDatatypeAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeTagForDatatypeAttr (TypeTagForDatatypeAttr * A) inline
Definition at line 1233 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitTypeVisibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitTypeVisibilityAttr (TypeVisibilityAttr * A) inline
Definition at line 1237 of file RecursiveASTVisitor.h.
VisitUnavailableAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUnavailableAttr (UnavailableAttr * A) inline
Definition at line 1245 of file RecursiveASTVisitor.h.
VisitUninitializedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUninitializedAttr (UninitializedAttr * A) inline
Definition at line 1249 of file RecursiveASTVisitor.h.
VisitUnlikelyAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUnlikelyAttr (UnlikelyAttr * A) inline
Definition at line 1253 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitUnqualTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUnqualTypeLoc (UnqualTypeLoc TL) inline
Definition at line 433 of file RecursiveASTVisitor.h.
VisitUnusedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUnusedAttr (UnusedAttr * A) inline
Definition at line 1257 of file RecursiveASTVisitor.h.
VisitUPtrAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUPtrAttr (UPtrAttr * A) inline
Definition at line 1241 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitUsedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUsedAttr (UsedAttr * A) inline
Definition at line 1265 of file RecursiveASTVisitor.h.
VisitUseHandleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUseHandleAttr (UseHandleAttr * A) inline
Definition at line 1261 of file RecursiveASTVisitor.h.
VisitUuidAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitUuidAttr (UuidAttr * A) inline
Definition at line 1269 of file RecursiveASTVisitor.h.
VisitVecReturnAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitVecReturnAttr (VecReturnAttr * A) inline
Definition at line 1273 of file RecursiveASTVisitor.h.
VisitVectorCallAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitVectorCallAttr (VectorCallAttr * A) inline
Definition at line 1281 of file RecursiveASTVisitor.h.
VisitVecTypeHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitVecTypeHintAttr (VecTypeHintAttr * A) inline
Definition at line 1277 of file RecursiveASTVisitor.h.
VisitVisibilityAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitVisibilityAttr (VisibilityAttr * A) inline
Definition at line 1285 of file RecursiveASTVisitor.h.
VisitWarnUnusedAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWarnUnusedAttr (WarnUnusedAttr * A) inline
Definition at line 1289 of file RecursiveASTVisitor.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and TRY_TO.
VisitWarnUnusedResultAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWarnUnusedResultAttr (WarnUnusedResultAttr * A) inline
Definition at line 1293 of file RecursiveASTVisitor.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and TRY_TO.
VisitWeakAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWeakAttr (WeakAttr * A) inline
Definition at line 1297 of file RecursiveASTVisitor.h.
VisitWeakImportAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWeakImportAttr (WeakImportAttr * A) inline
Definition at line 1301 of file RecursiveASTVisitor.h.
VisitWeakRefAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWeakRefAttr (WeakRefAttr * A) inline
Definition at line 1305 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitWebAssemblyExportNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWebAssemblyExportNameAttr (WebAssemblyExportNameAttr * A) inline
Definition at line 1309 of file RecursiveASTVisitor.h.
References TRY_TO.
VisitWebAssemblyImportModuleAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWebAssemblyImportModuleAttr (WebAssemblyImportModuleAttr * A) inline
Definition at line 1313 of file RecursiveASTVisitor.h.
VisitWebAssemblyImportNameAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWebAssemblyImportNameAttr (WebAssemblyImportNameAttr * A) inline
Definition at line 1317 of file RecursiveASTVisitor.h.
VisitWorkGroupSizeHintAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitWorkGroupSizeHintAttr (WorkGroupSizeHintAttr * A) inline
Definition at line 1321 of file RecursiveASTVisitor.h.
VisitX86ForceAlignArgPointerAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitX86ForceAlignArgPointerAttr (X86ForceAlignArgPointerAttr * A) inline
Definition at line 1325 of file RecursiveASTVisitor.h.
VisitXRayInstrumentAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitXRayInstrumentAttr (XRayInstrumentAttr * A) inline
Definition at line 1329 of file RecursiveASTVisitor.h.
VisitXRayLogArgsAttr()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::VisitXRayLogArgsAttr (XRayLogArgsAttr * A) inline
Definition at line 1333 of file RecursiveASTVisitor.h.
References TRY_TO.
WalkUpFromDecl()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromDecl (Decl * D) inline
Definition at line 454 of file RecursiveASTVisitor.h.
References clang::RecursiveASTVisitor< Derived >::getDerived().
WalkUpFromQualifiedTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromQualifiedTypeLoc (QualifiedTypeLoc TL) inline
Definition at line 426 of file RecursiveASTVisitor.h.
References clang::RecursiveASTVisitor< Derived >::getDerived(), and clang::QualifiedTypeLoc::getUnqualifiedLoc().
WalkUpFromStmt()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromStmt (Stmt * S) inline
Definition at line 379 of file RecursiveASTVisitor.h.
References clang::RecursiveASTVisitor< Derived >::getDerived().
WalkUpFromType()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromType (Type * T) inline
Definition at line 400 of file RecursiveASTVisitor.h.
WalkUpFromTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromTypeLoc (TypeLoc TL) inline
Definition at line 421 of file RecursiveASTVisitor.h.
WalkUpFromUnqualTypeLoc()
template<typename Derived > bool clang::RecursiveASTVisitor< Derived >::WalkUpFromUnqualTypeLoc (UnqualTypeLoc TL) inline
Definition at line 430 of file RecursiveASTVisitor.h.
References clang::RecursiveASTVisitor< Derived >::getDerived(), and clang::TypeLoc::getUnqualifiedLoc().
The documentation for this class was generated from the following file:
include/clang/AST/RecursiveASTVisitor.h