clang: clang::threadSafety::CFGWalker Class Reference
clang::threadSafety::CFGWalker Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyCommon.h"
Public Member Functions
CFGWalker ()=default
bool init (AnalysisDeclContext &AC)
template<class Visitor >
void walk (Visitor &V)
const CFG * getGraph () const
CFG * getGraph ()
const NamedDecl * getDecl () const
const PostOrderCFGView * getSortedGraph () const
Detailed Description
Definition at line 145 of file ThreadSafetyCommon.h.
Constructor & Destructor Documentation
CFGWalker()
clang::threadSafety::CFGWalker::CFGWalker () default
Member Function Documentation
getDecl()
const NamedDecl * clang::threadSafety::CFGWalker::getDecl () const inline
Definition at line 255 of file ThreadSafetyCommon.h.
References clang::AnalysisDeclContext::getDecl().
Referenced by walk().
getGraph() [1/2]
CFG * clang::threadSafety::CFGWalker::getGraph () inline
Definition at line 253 of file ThreadSafetyCommon.h.
getGraph() [2/2]
const CFG * clang::threadSafety::CFGWalker::getGraph () const inline
Definition at line 252 of file ThreadSafetyCommon.h.
getSortedGraph()
const PostOrderCFGView * clang::threadSafety::CFGWalker::getSortedGraph () const inline
Definition at line 259 of file ThreadSafetyCommon.h.
init()
bool clang::threadSafety::CFGWalker::init (AnalysisDeclContext & AC) inline
Definition at line 151 of file ThreadSafetyCommon.h.
References clang::AnalysisDeclContext::getAnalysis(), clang::AnalysisDeclContext::getCFG(), and clang::AnalysisDeclContext::getDecl().
walk()
template<class Visitor > void clang::threadSafety::CFGWalker::walk (Visitor & V) inline
Definition at line 170 of file ThreadSafetyCommon.h.
References clang::PostOrderCFGView::CFGBlockSet::alreadySet(), clang::CFGElement::AutomaticObjectDtor, clang::CFGElement::castAs(), clang::AnalysisDeclContext::getASTContext(), getDecl(), clang::CFGImplicitDtor::getDestructorDecl(), clang::CFG::getEntry(), clang::CFG::getExit(), clang::CFGStmt::getStmt(), clang::CFGAutomaticObjDtor::getVarDecl(), clang::PostOrderCFGView::CFGBlockSet::insert(), clang::CFGElement::Statement, and V.
Referenced by clang::threadSafety::SExprBuilder::buildCFG().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyCommon.h