clang: clang::serialization::DataStreamBasicReader< Impl > Class Template Reference
clang::serialization::DataStreamBasicReader< Impl > Class Template Reference
DataStreamBasicReader provides convenience implementations for many BasicReader methods based on the assumption that the ultimate reader implementation is based on a variable-length stream of unstructured data (like Clang's module files).
#include "clang/AST/AbstractBasicReader.h"
Public Member Functions
Impl & find (const char *propertyName)
Implement property-find by ignoring it.
template<class T >
T readEnum ()
Impl & readObject ()
template<class T >
llvm::ArrayRef< T > readArray (llvm::SmallVectorImpl< T > &buffer)
template<class T , class... Args>
llvm::Optional< T > readOptional (Args &&...args)
llvm::APSInt readAPSInt ()
llvm::APInt readAPInt ()
llvm::FixedPointSemantics readFixedPointSemantics ()
APValue::LValuePathSerializationHelper readLValuePathSerializationHelper (SmallVectorImpl< APValue::LValuePathEntry > &path)
Qualifiers readQualifiers ()
FunctionProtoType::ExceptionSpecInfo readExceptionSpecInfo (llvm::SmallVectorImpl< QualType > &buffer)
FunctionProtoType::ExtParameterInfo readExtParameterInfo ()
NestedNameSpecifier * readNestedNameSpecifier ()
Public Member Functions inherited from clang::serialization::BasicReaderBase< Impl >
ASTContext & getASTContext ()
Impl & asImpl ()
APValue readAPValue ()
APValue::ValueKind readAPValueKind ()
ArrayType::ArraySizeModifier readArraySizeModifier ()
attr::Kind readAttrKind ()
AutoTypeKeyword readAutoTypeKeyword ()
BuiltinType::Kind readBuiltinTypeKind ()
CXXRecordDecl * readCXXRecordDeclRef ()
CallingConv readCallingConv ()
ConceptDecl * readConceptDeclRef ()
DeclarationName readDeclarationName ()
DeclarationName::NameKind readDeclarationNameKind ()
ElaboratedTypeKeyword readElaboratedTypeKeyword ()
Expr * readExprRef ()
FunctionDecl * readFunctionDeclRef ()
NamedDecl * readNamedDeclRef ()
NamespaceAliasDecl * readNamespaceAliasDeclRef ()
NamespaceDecl * readNamespaceDeclRef ()
NestedNameSpecifier::SpecifierKind readNestedNameSpecifierKind ()
ObjCProtocolDecl * readObjCProtocolDeclRef ()
ObjCTypeParamDecl * readObjCTypeParamDeclRef ()
OverloadedOperatorKind readOverloadedOperatorKind ()
RefQualifierKind readRefQualifierKind ()
TagDecl * readTagDeclRef ()
TemplateArgument readTemplateArgument ()
TemplateArgument::ArgKind readTemplateArgumentKind ()
TemplateDecl * readTemplateDeclRef ()
TemplateName readTemplateName ()
TemplateName::NameKind readTemplateNameKind ()
TemplateTemplateParmDecl * readTemplateTemplateParmDeclRef ()
TemplateTypeParmDecl * readTemplateTypeParmDeclRef ()
UnaryTransformType::UTTKind readUnaryTypeTransformKind ()
ValueDecl * readValueDeclRef ()
VectorType::VectorKind readVectorKind ()
Protected Member Functions
DataStreamBasicReader (ASTContext &ctx)
Protected Member Functions inherited from clang::serialization::BasicReaderBase< Impl >
BasicReaderBase (ASTContext &ctx)
Detailed Description
template<class Impl>
class clang::serialization::DataStreamBasicReader< Impl >
DataStreamBasicReader provides convenience implementations for many BasicReader methods based on the assumption that the ultimate reader implementation is based on a variable-length stream of unstructured data (like Clang's module files).
It is designed to pair with DataStreamBasicWriter.
This class can also act as a PropertyReader, implementing find("...") by simply forwarding to itself.
Unimplemented methods: readBool readUInt32 readUInt64 readIdentifier readSelector readSourceLocation readQualType readStmtRef readDeclRef
Definition at line 123 of file AbstractBasicReader.h.
Constructor & Destructor Documentation
DataStreamBasicReader()
template<class Impl > clang::serialization::DataStreamBasicReader< Impl >::DataStreamBasicReader (ASTContext & ctx) inline protected
Definition at line 126 of file AbstractBasicReader.h.
Member Function Documentation
find()
template<class Impl > Impl & clang::serialization::DataStreamBasicReader< Impl >::find (const char * propertyName) inline
Implement property-find by ignoring it.
We rely on properties being serialized and deserialized in a reliable order instead.
Definition at line 133 of file AbstractBasicReader.h.
readAPInt()
template<class Impl > llvm::APInt clang::serialization::DataStreamBasicReader< Impl >::readAPInt () inline
Definition at line 171 of file AbstractBasicReader.h.
References clang::serialization::BasicReaderBase< Impl >::asImpl().
readAPSInt()
template<class Impl > llvm::APSInt clang::serialization::DataStreamBasicReader< Impl >::readAPSInt () inline
Definition at line 165 of file AbstractBasicReader.h.
References clang::serialization::BasicReaderBase< Impl >::asImpl().
Referenced by clang::ASTDeclReader::VisitEnumConstantDecl().
readArray()
template<class Impl > template<class T > llvm::ArrayRef< T > clang::serialization::DataStreamBasicReader< Impl >::readArray (llvm::SmallVectorImpl< T > & buffer) inline
Definition at line 147 of file AbstractBasicReader.h.
Referenced by clang::serialization::ReadDispatcher< ObjCTypeParamDecl * >::read().
readEnum()
template<class Impl > template<class T > T clang::serialization::DataStreamBasicReader< Impl >::readEnum () inline
Definition at line 138 of file AbstractBasicReader.h.
readExceptionSpecInfo()
template<class Impl > FunctionProtoType::ExceptionSpecInfo clang::serialization::DataStreamBasicReader< Impl >::readExceptionSpecInfo (llvm::SmallVectorImpl< QualType > & buffer) inline
Definition at line 222 of file AbstractBasicReader.h.
readExtParameterInfo()
template<class Impl > FunctionProtoType::ExtParameterInfo clang::serialization::DataStreamBasicReader< Impl >::readExtParameterInfo () inline
Definition at line 238 of file AbstractBasicReader.h.
readFixedPointSemantics()
template<class Impl > llvm::FixedPointSemantics clang::serialization::DataStreamBasicReader< Impl >::readFixedPointSemantics () inline
Definition at line 180 of file AbstractBasicReader.h.
readLValuePathSerializationHelper()
template<class Impl > APValue::LValuePathSerializationHelper clang::serialization::DataStreamBasicReader< Impl >::readLValuePathSerializationHelper (SmallVectorImpl< APValue::LValuePathEntry > & path) inline
Definition at line 191 of file AbstractBasicReader.h.
References clang::serialization::BasicReaderBase< Impl >::asImpl().
readNestedNameSpecifier()
template<class Impl > NestedNameSpecifier * clang::serialization::DataStreamBasicReader< Impl >::readNestedNameSpecifier () inline
Definition at line 246 of file AbstractBasicReader.h.
readObject()
template<class Impl > Impl & clang::serialization::DataStreamBasicReader< Impl >::readObject () inline
Definition at line 144 of file AbstractBasicReader.h.
References clang::serialization::BasicReaderBase< Impl >::asImpl().
readOptional()
template<class Impl > template<class T , class... Args> llvm::Optional< T > clang::serialization::DataStreamBasicReader< Impl >::readOptional (Args &&... args) inline
Definition at line 160 of file AbstractBasicReader.h.
readQualifiers()
template<class Impl > Qualifiers clang::serialization::DataStreamBasicReader< Impl >::readQualifiers () inline
Definition at line 214 of file AbstractBasicReader.h.
References clang::Qualifiers::getAsOpaqueValue().
The documentation for this class was generated from the following file:
include/clang/AST/AbstractBasicReader.h