clang: clang::ento::ExplodedNodeSet Class Reference
clang::ento::ExplodedNodeSet Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h"
Public Types
using iterator = ImplTy::iterator
using const_iterator = ImplTy::const_iterator
Public Member Functions
ExplodedNodeSet (ExplodedNode *N)
ExplodedNodeSet ()=default
void Add (ExplodedNode *N)
unsigned size () const
bool empty () const
bool erase (ExplodedNode *N)
void clear ()
void insert (const ExplodedNodeSet &S)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Detailed Description
Definition at line 463 of file ExplodedGraph.h.
Member Typedef Documentation
const_iterator
using clang::ento::ExplodedNodeSet::const_iterator = ImplTy::const_iterator
Definition at line 480 of file ExplodedGraph.h.
iterator
using clang::ento::ExplodedNodeSet::iterator = ImplTy::iterator
Definition at line 479 of file ExplodedGraph.h.
Constructor & Destructor Documentation
ExplodedNodeSet() [1/2]
clang::ento::ExplodedNodeSet::ExplodedNodeSet (ExplodedNode * N) inline
Definition at line 468 of file ExplodedGraph.h.
References N.
ExplodedNodeSet() [2/2]
clang::ento::ExplodedNodeSet::ExplodedNodeSet () default
Member Function Documentation
Add()
void clang::ento::ExplodedNodeSet::Add (ExplodedNode * N) inline
Definition at line 475 of file ExplodedGraph.h.
References N.
Referenced by clang::ento::NodeBuilder::addNodes(), clang::ento::CoreEngine::ExecuteWorkListWithInitialState(), clang::ento::NodeBuilder::generateNodeImpl(), clang::ento::NodeBuilder::NodeBuilder(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::ProcessLoopExit(), clang::ento::ExprEngine::ProcessStmt(), clang::ento::ExprEngine::removeDeadOnEndOfFunction(), and clang::ento::ExprEngine::VisitCXXCatchStmt().
begin() [1/2]
iterator clang::ento::ExplodedNodeSet::begin () inline
Definition at line 496 of file ExplodedGraph.h.
Referenced by clang::ento::NodeBuilder::begin(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::ProcessTemporaryDtor(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXDestructor(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitObjCMessage(), clang::ento::ExprEngine::VisitReturnStmt(), clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr(), and clang::ento::ExprEngine::VisitUnaryOperator().
begin() [2/2]
const_iterator clang::ento::ExplodedNodeSet::begin () const inline
Definition at line 499 of file ExplodedGraph.h.
clear()
void clang::ento::ExplodedNodeSet::clear () inline
Definition at line 486 of file ExplodedGraph.h.
Referenced by expandGraphWithCheckers().
empty()
bool clang::ento::ExplodedNodeSet::empty () const inline
Definition at line 483 of file ExplodedGraph.h.
Referenced by clang::ento::ExprEngine::evalLoad(), clang::ento::ExprEngine::evalStore(), expandGraphWithCheckers(), insert(), clang::ento::ExprEngine::processBranch(), and clang::ento::ExprEngine::ProcessTemporaryDtor().
end() [1/2]
iterator clang::ento::ExplodedNodeSet::end () inline
Definition at line 497 of file ExplodedGraph.h.
Referenced by clang::ento::NodeBuilder::end(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXDestructor(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitObjCMessage(), clang::ento::ExprEngine::VisitReturnStmt(), clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr(), and clang::ento::ExprEngine::VisitUnaryOperator().
end() [2/2]
const_iterator clang::ento::ExplodedNodeSet::end () const inline
Definition at line 500 of file ExplodedGraph.h.
erase()
bool clang::ento::ExplodedNodeSet::erase (ExplodedNode * N) inline
Definition at line 484 of file ExplodedGraph.h.
References N.
Referenced by clang::ento::NodeBuilder::generateNodeImpl(), clang::ento::NodeBuilder::takeNodes(), and clang::ento::NodeBuilder::takeNodes().
insert()
void clang::ento::ExplodedNodeSet::insert (const ExplodedNodeSet & S) inline
Definition at line 488 of file ExplodedGraph.h.
References empty().
Referenced by clang::ento::NodeBuilder::addNodes(), clang::ento::ExprEngine::evalCall(), expandGraphWithCheckers(), clang::ento::NodeBuilder::NodeBuilder(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessStmt(), clang::ento::CheckerManager::runCheckersForBeginFunction(), clang::ento::CheckerManager::runCheckersForBranchCondition(), clang::ento::CheckerManager::runCheckersForEvalCall(), clang::ento::CheckerManager::runCheckersForNewAllocator(), clang::ento::ExprEngine::VisitDeclStmt(), and clang::ento::ExprEngine::VisitIncrementDecrementOperator().
size()
unsigned clang::ento::ExplodedNodeSet::size () const inline
Definition at line 482 of file ExplodedGraph.h.
Referenced by clang::ento::ExprEngine::ProcessTemporaryDtor(), and clang::ento::ExprEngine::VisitCXXNewExpr().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h