clang: clang::FunctionTemplateSpecializationInfo Class Reference
clang::FunctionTemplateSpecializationInfo Class Reference final
Provides information about a function template specialization, which is a FunctionDecl that has been explicitly specialization or instantiated from a function template.
#include "clang/AST/DeclTemplate.h"
Public Member Functions
FunctionDecl * getFunction () const
Retrieve the declaration of the function template specialization.
FunctionTemplateDecl * getTemplate () const
Retrieve the template from which this function was specialized.
TemplateSpecializationKind getTemplateSpecializationKind () const
Determine what kind of template specialization this is.
bool isExplicitSpecialization () const
bool isExplicitInstantiationOrSpecialization () const
True if this declaration is an explicit specialization, explicit instantiation declaration, or explicit instantiation definition.
void setTemplateSpecializationKind (TemplateSpecializationKind TSK)
Set the template specialization kind.
SourceLocation getPointOfInstantiation () const
Retrieve the first point of instantiation of this function template specialization.
void setPointOfInstantiation (SourceLocation POI)
Set the (first) point of instantiation of this function template specialization.
MemberSpecializationInfo * getMemberSpecializationInfo () const
Get the specialization info if this function template specialization is also a member specialization:
void Profile (llvm::FoldingSetNodeID &ID)
Static Public Member Functions
static FunctionTemplateSpecializationInfo * Create (ASTContext &C, FunctionDecl *FD, FunctionTemplateDecl *Template, TemplateSpecializationKind TSK, const TemplateArgumentList *TemplateArgs, const TemplateArgumentListInfo *TemplateArgsAsWritten, SourceLocation POI, MemberSpecializationInfo *MSInfo)
static void Profile (llvm::FoldingSetNodeID &ID, ArrayRef< TemplateArgument > TemplateArgs, ASTContext &Context)
Public Attributes
const TemplateArgumentList * TemplateArguments
The template arguments used to produce the function template specialization from the function template.
const ASTTemplateArgumentListInfo * TemplateArgumentsAsWritten
The template arguments as written in the sources, if provided.
SourceLocation PointOfInstantiation
The point at which this function template specialization was first instantiated.
friend TrailingObjects
Detailed Description
Provides information about a function template specialization, which is a FunctionDecl that has been explicitly specialization or instantiated from a function template.
Definition at line 466 of file DeclTemplate.h.
Member Function Documentation
Create()
FunctionTemplateSpecializationInfo * FunctionTemplateSpecializationInfo::Create (ASTContext & C, FunctionDecl * FD, FunctionTemplateDecl * Template, TemplateSpecializationKind TSK, const TemplateArgumentList * TemplateArgs, const TemplateArgumentListInfo * TemplateArgsAsWritten, SourceLocation POI, MemberSpecializationInfo * MSInfo) static
Definition at line 829 of file DeclTemplate.cpp.
References clang::C, and clang::ASTTemplateArgumentListInfo::Create().
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
getFunction()
FunctionDecl * clang::FunctionTemplateSpecializationInfo::getFunction () const inline
Retrieve the declaration of the function template specialization.
Definition at line 522 of file DeclTemplate.h.
Referenced by clang::RedeclarableTemplateDecl::SpecEntryTraits< FunctionTemplateSpecializationInfo >::getDecl(), Profile(), and clang::ASTDeclReader::VisitFunctionDecl().
getMemberSpecializationInfo()
MemberSpecializationInfo * clang::FunctionTemplateSpecializationInfo::getMemberSpecializationInfo () const inline
Get the specialization info if this function template specialization is also a member specialization:
template<typename> struct A {
  template<typename> void f();
  template<> void f<int>(); // ClassScopeFunctionSpecializationDecl
};
Here, A<int>::f<int> is a function template specialization that is an explicit specialization of A<int>::f, but it's also a member specialization (an implicit instantiation in this case) of A::f<int>. Further:
template<> template<> void A<int>::f<int>() {}
... declares a function template specialization that is an explicit specialization of A<int>::f, and is also an explicit member specialization of A::f<int>.
Note that the TemplateSpecializationKind of the MemberSpecializationInfo need not be the same as that returned by getTemplateSpecializationKind(), and represents the relationship between the function and the class-scope explicit specialization in the original templated class – whereas our TemplateSpecializationKind represents the relationship between the function and the function template, and should always be TSK_ExplicitSpecialization whenever we have MemberSpecializationInfo.
Definition at line 596 of file DeclTemplate.h.
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getPointOfInstantiation()
SourceLocation clang::FunctionTemplateSpecializationInfo::getPointOfInstantiation () const inline
Retrieve the first point of instantiation of this function template specialization.
The point of instantiation may be an invalid source location if this function has yet to be instantiated.
Definition at line 556 of file DeclTemplate.h.
References PointOfInstantiation.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization(), and clang::ASTDeclWriter::VisitFunctionDecl().
getTemplate()
FunctionTemplateDecl * clang::FunctionTemplateSpecializationInfo::getTemplate () const inline
Retrieve the template from which this function was specialized.
Definition at line 525 of file DeclTemplate.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::PredefinedExpr::ComputeName(), and clang::ASTDeclWriter::VisitFunctionDecl().
getTemplateSpecializationKind()
TemplateSpecializationKind clang::FunctionTemplateSpecializationInfo::getTemplateSpecializationKind () const inline
Determine what kind of template specialization this is.
Definition at line 528 of file DeclTemplate.h.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization(), isExplicitInstantiationOrSpecialization(), isExplicitSpecialization(), and clang::ASTDeclWriter::VisitFunctionDecl().
isExplicitInstantiationOrSpecialization()
bool clang::FunctionTemplateSpecializationInfo::isExplicitInstantiationOrSpecialization () const inline
True if this declaration is an explicit specialization, explicit instantiation declaration, or explicit instantiation definition.
Definition at line 539 of file DeclTemplate.h.
References getTemplateSpecializationKind(), and clang::isTemplateExplicitInstantiationOrSpecialization().
Referenced by shouldConsiderTemplateVisibility().
isExplicitSpecialization()
bool clang::FunctionTemplateSpecializationInfo::isExplicitSpecialization () const inline
Definition at line 532 of file DeclTemplate.h.
References getTemplateSpecializationKind(), and clang::TSK_ExplicitSpecialization.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization(), and clang::PredefinedExpr::ComputeName().
Profile() [1/2]
void clang::FunctionTemplateSpecializationInfo::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 602 of file DeclTemplate.h.
References clang::TemplateArgumentList::asArray(), getFunction(), Profile(), and TemplateArguments.
Referenced by Profile(), and clang::ASTDeclReader::VisitFunctionDecl().
Profile() [2/2]
static void clang::FunctionTemplateSpecializationInfo::Profile (llvm::FoldingSetNodeID & ID, ArrayRef< TemplateArgument > TemplateArgs, ASTContext & Context) inline static
Definition at line 607 of file DeclTemplate.h.
References clang::TemplateArg.
setPointOfInstantiation()
void clang::FunctionTemplateSpecializationInfo::setPointOfInstantiation (SourceLocation POI) inline
Set the (first) point of instantiation of this function template specialization.
Definition at line 562 of file DeclTemplate.h.
References PointOfInstantiation.
setTemplateSpecializationKind()
void clang::FunctionTemplateSpecializationInfo::setTemplateSpecializationKind (TemplateSpecializationKind TSK) inline
Set the template specialization kind.
Definition at line 545 of file DeclTemplate.h.
References clang::TSK_Undeclared.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization().
Member Data Documentation
PointOfInstantiation
SourceLocation clang::FunctionTemplateSpecializationInfo::PointOfInstantiation
The point at which this function template specialization was first instantiated.
Definition at line 491 of file DeclTemplate.h.
Referenced by getPointOfInstantiation(), and setPointOfInstantiation().
TemplateArguments
const TemplateArgumentList* clang::FunctionTemplateSpecializationInfo::TemplateArguments
The template arguments used to produce the function template specialization from the function template.
Definition at line 483 of file DeclTemplate.h.
Referenced by clang::PredefinedExpr::ComputeName(), clang::RedeclarableTemplateDecl::SpecEntryTraits< FunctionTemplateSpecializationInfo >::getTemplateArgs(), Profile(), and clang::ASTDeclWriter::VisitFunctionDecl().
TemplateArgumentsAsWritten
const ASTTemplateArgumentListInfo* clang::FunctionTemplateSpecializationInfo::TemplateArgumentsAsWritten
The template arguments as written in the sources, if provided.
FIXME: Normally null; tail-allocate this.
Definition at line 487 of file DeclTemplate.h.
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
TrailingObjects
friend clang::FunctionTemplateSpecializationInfo::TrailingObjects
Definition at line 512 of file DeclTemplate.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclTemplate.h
lib/AST/DeclTemplate.cpp