clang: clang::driver::XRayArgs Class Reference
clang::driver::XRayArgs Class Reference
#include "clang/Driver/XRayArgs.h"
Public Member Functions
XRayArgs (const ToolChain &TC, const llvm::opt::ArgList &Args)
Parses the XRay arguments from an argument list.
void addArgs (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, types::ID InputType) const
bool needsXRayRt () const
llvm::ArrayRef< std::string > modeList () const
XRayInstrSet instrumentationBundle () const
Detailed Description
Definition at line 21 of file XRayArgs.h.
Constructor & Destructor Documentation
XRayArgs()
XRayArgs::XRayArgs (const ToolChain & TC, const llvm::opt::ArgList & Args)
Parses the XRay arguments from an argument list.
Definition at line 32 of file XRayArgs.cpp.
References clang::XRayInstrKind::All, clang::XRayInstrSet::clear(), clang::driver::Driver::Diag(), Filename, clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getTriple(), clang::driver::Driver::getVFS(), clang::XRayInstrSet::Mask, clang::XRayInstrKind::None, P, and clang::parseXRayInstrValue().
Member Function Documentation
addArgs()
void XRayArgs::addArgs (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, types::ID InputType) const
Definition at line 209 of file XRayArgs.cpp.
References clang::XRayInstrKind::Custom, clang::XRayInstrSet::empty(), clang::XRayInstrSet::full(), clang::XRayInstrKind::FunctionEntry, clang::XRayInstrKind::FunctionExit, clang::XRayInstrSet::has(), clang::Never, and clang::XRayInstrKind::Typed.
Referenced by clang::driver::tools::Clang::ConstructJob().
instrumentationBundle()
XRayInstrSet clang::driver::XRayArgs::instrumentationBundle () const inline
Definition at line 46 of file XRayArgs.h.
modeList()
llvm::ArrayRef< std::string > clang::driver::XRayArgs::modeList () const inline
Definition at line 45 of file XRayArgs.h.
needsXRayRt()
bool clang::driver::XRayArgs::needsXRayRt () const inline
Definition at line 44 of file XRayArgs.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs().
The documentation for this class was generated from the following files:
include/clang/Driver/XRayArgs.h
lib/Driver/XRayArgs.cpp