clang: clang::CodeGen::SanitizerMetadata Class Reference
clang::CodeGen::SanitizerMetadata Class Reference
#include "/root/llvm-project/clang/lib/CodeGen/SanitizerMetadata.h"
Public Member Functions
SanitizerMetadata (CodeGenModule &CGM)
void reportGlobalToASan (llvm::GlobalVariable *GV, const VarDecl &D, bool IsDynInit=false)
void reportGlobalToASan (llvm::GlobalVariable *GV, SourceLocation Loc, StringRef Name, QualType Ty, bool IsDynInit=false, bool IsExcluded=false)
void disableSanitizerForGlobal (llvm::GlobalVariable *GV)
void disableSanitizerForInstruction (llvm::Instruction *I)
Detailed Description
Definition at line 32 of file SanitizerMetadata.h.
Constructor & Destructor Documentation
SanitizerMetadata()
SanitizerMetadata::SanitizerMetadata (CodeGenModule & CGM)
Definition at line 23 of file SanitizerMetadata.cpp.
Member Function Documentation
disableSanitizerForGlobal()
void SanitizerMetadata::disableSanitizerForGlobal (llvm::GlobalVariable * GV)
Definition at line 80 of file SanitizerMetadata.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), isAsanHwasanOrMemTag(), reportGlobalToASan(), and clang::LangOptions::Sanitize.
disableSanitizerForInstruction()
void SanitizerMetadata::disableSanitizerForInstruction (llvm::Instruction * I)
Definition at line 87 of file SanitizerMetadata.cpp.
References clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::CodeGenModule::getModule().
reportGlobalToASan() [1/2]
void SanitizerMetadata::reportGlobalToASan (llvm::GlobalVariable * GV, const VarDecl & D, bool IsDynInit = false)
Definition at line 64 of file SanitizerMetadata.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), isAsanHwasanOrMemTag(), clang::NamedDecl::printQualifiedName(), reportGlobalToASan(), clang::LangOptions::Sanitize, and clang::Decl::specific_attrs().
Referenced by disableSanitizerForGlobal(), and reportGlobalToASan().
reportGlobalToASan() [2/2]
void SanitizerMetadata::reportGlobalToASan (llvm::GlobalVariable * GV, SourceLocation Loc, StringRef Name, QualType Ty, bool IsDynInit = false, bool IsExcluded = false)
Definition at line 31 of file SanitizerMetadata.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), isAsanHwasanOrMemTag(), clang::CodeGen::CodeGenModule::isInSanitizerBlacklist(), and clang::LangOptions::Sanitize.
The documentation for this class was generated from the following files:
lib/CodeGen/SanitizerMetadata.h
lib/CodeGen/SanitizerMetadata.cpp