clang: clang::OMPDeclareSimdDeclAttr Class Reference
clang::OMPDeclareSimdDeclAttr Class Reference
#include "clang/AST/Attr.h"
Public Types
enum BranchStateTy { BS_Undefined , BS_Inbranch , BS_Notinbranch }
typedef Expr ** uniforms_iterator
typedef Expr ** aligneds_iterator
typedef Expr ** alignments_iterator
typedef Expr ** linears_iterator
typedef unsigned * modifiers_iterator
typedef Expr ** steps_iterator
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
OMPDeclareSimdDeclAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, BranchStateTy BranchState, Expr *Simdlen, Expr **Uniforms, unsigned UniformsSize, Expr **Aligneds, unsigned AlignedsSize, Expr **Alignments, unsigned AlignmentsSize, Expr **Linears, unsigned LinearsSize, unsigned *Modifiers, unsigned ModifiersSize, Expr **Steps, unsigned StepsSize)
OMPDeclareSimdDeclAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, BranchStateTy BranchState, Expr *Simdlen)
OMPDeclareSimdDeclAttr * clone (ASTContext &C) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
const char * getSpelling () const
BranchStateTy getBranchState () const
Expr * getSimdlen () const
uniforms_iterator uniforms_begin () const
uniforms_iterator uniforms_end () const
unsigned uniforms_size () const
llvm::iterator_range< uniforms_iterator > uniforms () const
aligneds_iterator aligneds_begin () const
aligneds_iterator aligneds_end () const
unsigned aligneds_size () const
llvm::iterator_range< aligneds_iterator > aligneds () const
alignments_iterator alignments_begin () const
alignments_iterator alignments_end () const
unsigned alignments_size () const
llvm::iterator_range< alignments_iterator > alignments () const
linears_iterator linears_begin () const
linears_iterator linears_end () const
unsigned linears_size () const
llvm::iterator_range< linears_iterator > linears () const
modifiers_iterator modifiers_begin () const
modifiers_iterator modifiers_end () const
unsigned modifiers_size () const
llvm::iterator_range< modifiers_iterator > modifiers () const
steps_iterator steps_begin () const
steps_iterator steps_end () const
unsigned steps_size () const
llvm::iterator_range< steps_iterator > steps () const
void printPrettyPragma (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::Attr
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static OMPDeclareSimdDeclAttr * CreateImplicit (ASTContext &Ctx, BranchStateTy BranchState, Expr *Simdlen, Expr **Uniforms, unsigned UniformsSize, Expr **Aligneds, unsigned AlignedsSize, Expr **Alignments, unsigned AlignmentsSize, Expr **Linears, unsigned LinearsSize, unsigned *Modifiers, unsigned ModifiersSize, Expr **Steps, unsigned StepsSize, const AttributeCommonInfo &CommonInfo={SourceRange{}})
static OMPDeclareSimdDeclAttr * Create (ASTContext &Ctx, BranchStateTy BranchState, Expr *Simdlen, Expr **Uniforms, unsigned UniformsSize, Expr **Aligneds, unsigned AlignedsSize, Expr **Alignments, unsigned AlignmentsSize, Expr **Linears, unsigned LinearsSize, unsigned *Modifiers, unsigned ModifiersSize, Expr **Steps, unsigned StepsSize, const AttributeCommonInfo &CommonInfo)
static OMPDeclareSimdDeclAttr * CreateImplicit (ASTContext &Ctx, BranchStateTy BranchState, Expr *Simdlen, Expr **Uniforms, unsigned UniformsSize, Expr **Aligneds, unsigned AlignedsSize, Expr **Alignments, unsigned AlignmentsSize, Expr **Linears, unsigned LinearsSize, unsigned *Modifiers, unsigned ModifiersSize, Expr **Steps, unsigned StepsSize, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static OMPDeclareSimdDeclAttr * Create (ASTContext &Ctx, BranchStateTy BranchState, Expr *Simdlen, Expr **Uniforms, unsigned UniformsSize, Expr **Aligneds, unsigned AlignedsSize, Expr **Alignments, unsigned AlignmentsSize, Expr **Linears, unsigned LinearsSize, unsigned *Modifiers, unsigned ModifiersSize, Expr **Steps, unsigned StepsSize, SourceRange Range, AttributeCommonInfo::Syntax Syntax)
static bool ConvertStrToBranchStateTy (StringRef Val, BranchStateTy &Out)
static const char * ConvertBranchStateTyToStr (BranchStateTy Val)
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Additional Inherited Members
Protected Member Functions inherited from clang::Attr
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes inherited from clang::Attr
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Definition at line 6297 of file Attr.h.
Member Typedef Documentation
aligneds_iterator
Expr** clang::OMPDeclareSimdDeclAttr::aligneds_iterator
Definition at line 6371 of file Attr.h.
alignments_iterator
Expr** clang::OMPDeclareSimdDeclAttr::alignments_iterator
Definition at line 6378 of file Attr.h.
linears_iterator
Expr** clang::OMPDeclareSimdDeclAttr::linears_iterator
Definition at line 6385 of file Attr.h.
modifiers_iterator
unsigned* clang::OMPDeclareSimdDeclAttr::modifiers_iterator
Definition at line 6392 of file Attr.h.
steps_iterator
Expr** clang::OMPDeclareSimdDeclAttr::steps_iterator
Definition at line 6399 of file Attr.h.
uniforms_iterator
Expr** clang::OMPDeclareSimdDeclAttr::uniforms_iterator
Definition at line 6364 of file Attr.h.
Member Enumeration Documentation
BranchStateTy
enum clang::OMPDeclareSimdDeclAttr::BranchStateTy
Enumerator
BS_Undefined
BS_Inbranch
BS_Notinbranch
Definition at line 6299 of file Attr.h.
Constructor & Destructor Documentation
OMPDeclareSimdDeclAttr() [1/2]
clang::OMPDeclareSimdDeclAttr::OMPDeclareSimdDeclAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, BranchStateTy BranchState, Expr * Simdlen, Expr ** Uniforms, unsigned UniformsSize, Expr ** Aligneds, unsigned AlignedsSize, Expr ** Alignments, unsigned AlignmentsSize, Expr ** Linears, unsigned LinearsSize, unsigned * Modifiers, unsigned ModifiersSize, Expr ** Steps, unsigned StepsSize)
OMPDeclareSimdDeclAttr() [2/2]
clang::OMPDeclareSimdDeclAttr::OMPDeclareSimdDeclAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, BranchStateTy BranchState, Expr * Simdlen)
Member Function Documentation
aligneds()
llvm::iterator_range< aligneds_iterator > clang::OMPDeclareSimdDeclAttr::aligneds () const inline
Definition at line 6375 of file Attr.h.
Referenced by printPrettyPragma().
aligneds_begin()
aligneds_iterator clang::OMPDeclareSimdDeclAttr::aligneds_begin () const inline
Definition at line 6372 of file Attr.h.
aligneds_end()
aligneds_iterator clang::OMPDeclareSimdDeclAttr::aligneds_end () const inline
Definition at line 6373 of file Attr.h.
aligneds_size()
unsigned clang::OMPDeclareSimdDeclAttr::aligneds_size () const inline
Definition at line 6374 of file Attr.h.
alignments()
llvm::iterator_range< alignments_iterator > clang::OMPDeclareSimdDeclAttr::alignments () const inline
Definition at line 6382 of file Attr.h.
alignments_begin()
alignments_iterator clang::OMPDeclareSimdDeclAttr::alignments_begin () const inline
Definition at line 6379 of file Attr.h.
Referenced by printPrettyPragma().
alignments_end()
alignments_iterator clang::OMPDeclareSimdDeclAttr::alignments_end () const inline
Definition at line 6380 of file Attr.h.
alignments_size()
unsigned clang::OMPDeclareSimdDeclAttr::alignments_size () const inline
Definition at line 6381 of file Attr.h.
classof()
static bool clang::OMPDeclareSimdDeclAttr::classof (const Attr * A) inline static
Definition at line 6411 of file Attr.h.
clone()
OMPDeclareSimdDeclAttr * clang::OMPDeclareSimdDeclAttr::clone (ASTContext & C) const
ConvertBranchStateTyToStr()
static const char * clang::OMPDeclareSimdDeclAttr::ConvertBranchStateTyToStr (BranchStateTy Val) static
Referenced by parseDeclareSimdClauses(), and printPrettyPragma().
ConvertStrToBranchStateTy()
static bool clang::OMPDeclareSimdDeclAttr::ConvertStrToBranchStateTy (StringRef Val, BranchStateTy & Out) static
Referenced by parseDeclareSimdClauses().
Create() [1/2]
static OMPDeclareSimdDeclAttr * clang::OMPDeclareSimdDeclAttr::Create (ASTContext & Ctx, BranchStateTy BranchState, Expr * Simdlen, Expr ** Uniforms, unsigned UniformsSize, Expr ** Aligneds, unsigned AlignedsSize, Expr ** Alignments, unsigned AlignmentsSize, Expr ** Linears, unsigned LinearsSize, unsigned * Modifiers, unsigned ModifiersSize, Expr ** Steps, unsigned StepsSize, const AttributeCommonInfo & CommonInfo) static
Create() [2/2]
static OMPDeclareSimdDeclAttr * clang::OMPDeclareSimdDeclAttr::Create (ASTContext & Ctx, BranchStateTy BranchState, Expr * Simdlen, Expr ** Uniforms, unsigned UniformsSize, Expr ** Aligneds, unsigned AlignedsSize, Expr ** Alignments, unsigned AlignmentsSize, Expr ** Linears, unsigned LinearsSize, unsigned * Modifiers, unsigned ModifiersSize, Expr ** Steps, unsigned StepsSize, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
CreateImplicit() [1/2]
static OMPDeclareSimdDeclAttr * clang::OMPDeclareSimdDeclAttr::CreateImplicit (ASTContext & Ctx, BranchStateTy BranchState, Expr * Simdlen, Expr ** Uniforms, unsigned UniformsSize, Expr ** Aligneds, unsigned AlignedsSize, Expr ** Alignments, unsigned AlignmentsSize, Expr ** Linears, unsigned LinearsSize, unsigned * Modifiers, unsigned ModifiersSize, Expr ** Steps, unsigned StepsSize, const AttributeCommonInfo & CommonInfo = {SourceRange{}}) static
Referenced by clang::Sema::ActOnOpenMPDeclareSimdDirective().
CreateImplicit() [2/2]
static OMPDeclareSimdDeclAttr * clang::OMPDeclareSimdDeclAttr::CreateImplicit (ASTContext & Ctx, BranchStateTy BranchState, Expr * Simdlen, Expr ** Uniforms, unsigned UniformsSize, Expr ** Aligneds, unsigned AlignedsSize, Expr ** Alignments, unsigned AlignmentsSize, Expr ** Linears, unsigned LinearsSize, unsigned * Modifiers, unsigned ModifiersSize, Expr ** Steps, unsigned StepsSize, SourceRange Range, AttributeCommonInfo::Syntax Syntax) static
getBranchState()
BranchStateTy clang::OMPDeclareSimdDeclAttr::getBranchState () const inline
Definition at line 6354 of file Attr.h.
Referenced by printPrettyPragma().
getSimdlen()
Expr * clang::OMPDeclareSimdDeclAttr::getSimdlen () const inline
Definition at line 6360 of file Attr.h.
Referenced by printPrettyPragma().
getSpelling()
const char * clang::OMPDeclareSimdDeclAttr::getSpelling () const
linears()
llvm::iterator_range< linears_iterator > clang::OMPDeclareSimdDeclAttr::linears () const inline
Definition at line 6389 of file Attr.h.
Referenced by printPrettyPragma().
linears_begin()
linears_iterator clang::OMPDeclareSimdDeclAttr::linears_begin () const inline
Definition at line 6386 of file Attr.h.
linears_end()
linears_iterator clang::OMPDeclareSimdDeclAttr::linears_end () const inline
Definition at line 6387 of file Attr.h.
linears_size()
unsigned clang::OMPDeclareSimdDeclAttr::linears_size () const inline
Definition at line 6388 of file Attr.h.
modifiers()
llvm::iterator_range< modifiers_iterator > clang::OMPDeclareSimdDeclAttr::modifiers () const inline
Definition at line 6396 of file Attr.h.
modifiers_begin()
modifiers_iterator clang::OMPDeclareSimdDeclAttr::modifiers_begin () const inline
Definition at line 6393 of file Attr.h.
Referenced by printPrettyPragma().
modifiers_end()
modifiers_iterator clang::OMPDeclareSimdDeclAttr::modifiers_end () const inline
Definition at line 6394 of file Attr.h.
modifiers_size()
unsigned clang::OMPDeclareSimdDeclAttr::modifiers_size () const inline
Definition at line 6395 of file Attr.h.
printPretty()
void clang::OMPDeclareSimdDeclAttr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
printPrettyPragma()
void OMPDeclareSimdDeclAttr::printPrettyPragma (raw_ostream & OS, const PrintingPolicy & Policy) const
Definition at line 85 of file AttrImpl.cpp.
References aligneds(), alignments_begin(), BS_Undefined, ConvertBranchStateTyToStr(), getBranchState(), clang::getOpenMPSimpleClauseTypeName(), getSimdlen(), linears(), modifiers_begin(), clang::OMPC_LINEAR_unknown, steps_begin(), uniforms(), and uniforms_size().
steps()
llvm::iterator_range< steps_iterator > clang::OMPDeclareSimdDeclAttr::steps () const inline
Definition at line 6403 of file Attr.h.
steps_begin()
steps_iterator clang::OMPDeclareSimdDeclAttr::steps_begin () const inline
Definition at line 6400 of file Attr.h.
Referenced by printPrettyPragma().
steps_end()
steps_iterator clang::OMPDeclareSimdDeclAttr::steps_end () const inline
Definition at line 6401 of file Attr.h.
steps_size()
unsigned clang::OMPDeclareSimdDeclAttr::steps_size () const inline
Definition at line 6402 of file Attr.h.
uniforms()
llvm::iterator_range< uniforms_iterator > clang::OMPDeclareSimdDeclAttr::uniforms () const inline
Definition at line 6368 of file Attr.h.
Referenced by printPrettyPragma().
uniforms_begin()
uniforms_iterator clang::OMPDeclareSimdDeclAttr::uniforms_begin () const inline
Definition at line 6365 of file Attr.h.
uniforms_end()
uniforms_iterator clang::OMPDeclareSimdDeclAttr::uniforms_end () const inline
Definition at line 6366 of file Attr.h.
uniforms_size()
unsigned clang::OMPDeclareSimdDeclAttr::uniforms_size () const inline
Definition at line 6367 of file Attr.h.
Referenced by printPrettyPragma().
The documentation for this class was generated from the following files:
include/clang/AST/Attr.h
lib/AST/AttrImpl.cpp