clang: clang::FunctionTypeLoc Class Reference
clang::FunctionTypeLoc Class Reference
Wrapper for source info for functions.
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getLocalRangeBegin () const
void setLocalRangeBegin (SourceLocation L)
SourceLocation getLocalRangeEnd () const
void setLocalRangeEnd (SourceLocation L)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
SourceRange getParensRange () const
SourceRange getExceptionSpecRange () const
void setExceptionSpecRange (SourceRange R)
ArrayRef< ParmVarDecl * > getParams () const
ParmVarDecl ** getParmArray () const
unsigned getNumParams () const
ParmVarDecl * getParam (unsigned i) const
void setParam (unsigned i, ParmVarDecl *VD)
TypeLoc getReturnLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
Returns the size of the type source info data block that is specific to this type.
unsigned getExtraLocalDataAlignment () const
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (FunctionTypeLoc other)
TypeLoc getNextTypeLoc () const
const FunctionType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
FunctionLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Wrapper for source info for functions.
Definition at line 1351 of file TypeLoc.h.
Member Function Documentation
getExceptionSpecRange()
SourceRange clang::FunctionTypeLoc::getExceptionSpecRange () const inline
Definition at line 1406 of file TypeLoc.h.
Referenced by clang::FunctionDecl::getExceptionSpecSourceRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getExtraLocalDataAlignment()
unsigned clang::FunctionTypeLoc::getExtraLocalDataAlignment () const inline
Definition at line 1461 of file TypeLoc.h.
getExtraLocalDataSize()
unsigned clang::FunctionTypeLoc::getExtraLocalDataSize () const inline
Returns the size of the type source info data block that is specific to this type.
Definition at line 1456 of file TypeLoc.h.
References getNumParams().
getInnerType()
QualType clang::FunctionTypeLoc::getInnerType () const inline
Definition at line 1463 of file TypeLoc.h.
References clang::FunctionType::getReturnType(), and clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getTypePtr().
getLocalRangeBegin()
SourceLocation clang::FunctionTypeLoc::getLocalRangeBegin () const inline
Definition at line 1370 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LocalRangeBegin.
Referenced by clang::Sema::ActOnBlockArguments(), getLocalSourceRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getLocalRangeEnd()
SourceLocation clang::FunctionTypeLoc::getLocalRangeEnd () const inline
Definition at line 1378 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LocalRangeEnd.
Referenced by clang::Sema::ActOnBlockArguments(), getLocalSourceRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getLocalSourceRange()
SourceRange clang::FunctionTypeLoc::getLocalSourceRange () const inline
Definition at line 1439 of file TypeLoc.h.
References getLocalRangeBegin(), and getLocalRangeEnd().
getLParenLoc()
SourceLocation clang::FunctionTypeLoc::getLParenLoc () const inline
Definition at line 1386 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LParenLoc.
Referenced by clang::Sema::ActOnFinishFunctionBody(), getParensRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getNumParams()
unsigned clang::FunctionTypeLoc::getNumParams () const inline
Definition at line 1426 of file TypeLoc.h.
References clang::cast(), and clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getTypePtr().
Referenced by clang::Sema::ActOnBlockArguments(), AddObjCBlockCall(), formatBlockPlaceholder(), getExtraLocalDataSize(), getParams(), initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
getParam()
ParmVarDecl * clang::FunctionTypeLoc::getParam (unsigned i) const inline
Definition at line 1432 of file TypeLoc.h.
References getParmArray().
Referenced by clang::Sema::ActOnBlockArguments(), AddObjCBlockCall(), and clang::TemplateDeclInstantiator::SubstFunctionType().
getParams()
ArrayRef< ParmVarDecl * > clang::FunctionTypeLoc::getParams () const inline
Definition at line 1417 of file TypeLoc.h.
References getNumParams(), and getParmArray().
Referenced by clang::comments::DeclInfo::fill(), NeedsInstantiationAsFunctionType(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getParensRange()
SourceRange clang::FunctionTypeLoc::getParensRange () const inline
Definition at line 1402 of file TypeLoc.h.
References getLParenLoc(), and getRParenLoc().
getParmArray()
ParmVarDecl ** clang::FunctionTypeLoc::getParmArray () const inline
Definition at line 1422 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getExtraLocalData().
Referenced by getParam(), getParams(), and setParam().
getReturnLoc()
TypeLoc clang::FunctionTypeLoc::getReturnLoc () const inline
Definition at line 1435 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getInnerTypeLoc().
Referenced by clang::Sema::ActOnBlockArguments(), addFunctionPointerConversion(), AddObjCBlockCall(), buildTrailingReturn(), clang::Sema::checkThisInStaticMemberFunctionType(), clang::comments::DeclInfo::fill(), clang::FunctionDecl::getReturnTypeSourceRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
getRParenLoc()
SourceLocation clang::FunctionTypeLoc::getRParenLoc () const inline
Definition at line 1394 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::RParenLoc.
Referenced by getParensRange(), and clang::TreeTransform< Derived >::TransformFunctionProtoType().
initializeLocal()
void clang::FunctionTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 1443 of file TypeLoc.h.
References getNumParams(), setExceptionSpecRange(), setLocalRangeBegin(), setLocalRangeEnd(), setLParenLoc(), setParam(), and setRParenLoc().
setExceptionSpecRange()
void clang::FunctionTypeLoc::setExceptionSpecRange (SourceRange R) inline
Definition at line 1412 of file TypeLoc.h.
Referenced by initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
setLocalRangeBegin()
void clang::FunctionTypeLoc::setLocalRangeBegin (SourceLocation L) inline
Definition at line 1374 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LocalRangeBegin.
Referenced by initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
setLocalRangeEnd()
void clang::FunctionTypeLoc::setLocalRangeEnd (SourceLocation L) inline
Definition at line 1382 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LocalRangeEnd.
Referenced by initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
setLParenLoc()
void clang::FunctionTypeLoc::setLParenLoc (SourceLocation Loc) inline
Definition at line 1390 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::LParenLoc.
Referenced by initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
setParam()
void clang::FunctionTypeLoc::setParam (unsigned i, ParmVarDecl * VD) inline
Definition at line 1433 of file TypeLoc.h.
References getParmArray().
Referenced by clang::TemplateDeclInstantiator::adjustForRewrite(), clang::Sema::findInheritingConstructor(), initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
setRParenLoc()
void clang::FunctionTypeLoc::setRParenLoc (SourceLocation Loc) inline
Definition at line 1398 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, FunctionTypeLoc, FunctionType, FunctionLocInfo >::getLocalData(), and clang::FunctionLocInfo::RParenLoc.
Referenced by initializeLocal(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::TypeLocReader::VisitFunctionTypeLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h