clang: clang::DependentTemplateSpecializationTypeLoc Class Reference
clang::DependentTemplateSpecializationTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getElaboratedKeywordLoc () const
void setElaboratedKeywordLoc (SourceLocation Loc)
NestedNameSpecifierLoc getQualifierLoc () const
void setQualifierLoc (NestedNameSpecifierLoc QualifierLoc)
SourceLocation getTemplateKeywordLoc () const
void setTemplateKeywordLoc (SourceLocation Loc)
SourceLocation getTemplateNameLoc () const
void setTemplateNameLoc (SourceLocation Loc)
SourceLocation getLAngleLoc () const
void setLAngleLoc (SourceLocation Loc)
SourceLocation getRAngleLoc () const
void setRAngleLoc (SourceLocation Loc)
unsigned getNumArgs () const
void setArgLocInfo (unsigned i, TemplateArgumentLocInfo AI)
TemplateArgumentLocInfo getArgLocInfo (unsigned i) const
TemplateArgumentLoc getArgLoc (unsigned i) const
SourceRange getLocalSourceRange () const
void copy (DependentTemplateSpecializationTypeLoc Loc)
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (DependentTemplateSpecializationTypeLoc other)
TypeLoc getNextTypeLoc () const
const DependentTemplateSpecializationType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
DependentTemplateSpecializationLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Definition at line 2314 of file TypeLoc.h.
Member Function Documentation
copy()
void clang::DependentTemplateSpecializationTypeLoc::copy (DependentTemplateSpecializationTypeLoc Loc) inline
Definition at line 2411 of file TypeLoc.h.
References clang::TypeLoc::Data, clang::TypeLoc::getFullDataSize(), and memcpy().
getArgLoc()
TemplateArgumentLoc clang::DependentTemplateSpecializationTypeLoc::getArgLoc (unsigned i) const inline
Definition at line 2396 of file TypeLoc.h.
References getArgLocInfo(), and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getTypePtr().
getArgLocInfo()
TemplateArgumentLocInfo clang::DependentTemplateSpecializationTypeLoc::getArgLocInfo (unsigned i) const inline
Definition at line 2392 of file TypeLoc.h.
Referenced by getArgLoc().
getElaboratedKeywordLoc()
SourceLocation clang::DependentTemplateSpecializationTypeLoc::getElaboratedKeywordLoc () const inline
Definition at line 2320 of file TypeLoc.h.
References clang::ElaboratedLocInfo::ElaboratedKWLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData().
Referenced by getLocalSourceRange(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
getExtraLocalDataAlignment()
unsigned clang::DependentTemplateSpecializationTypeLoc::getExtraLocalDataAlignment () const inline
Definition at line 2423 of file TypeLoc.h.
getExtraLocalDataSize()
unsigned clang::DependentTemplateSpecializationTypeLoc::getExtraLocalDataSize () const inline
Definition at line 2419 of file TypeLoc.h.
References getNumArgs().
getLAngleLoc()
SourceLocation clang::DependentTemplateSpecializationTypeLoc::getLAngleLoc () const inline
Definition at line 2368 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::LAngleLoc.
Referenced by clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
getLocalSourceRange()
SourceRange clang::DependentTemplateSpecializationTypeLoc::getLocalSourceRange () const inline
Definition at line 2400 of file TypeLoc.h.
References clang::TypeLoc::getBeginLoc(), getElaboratedKeywordLoc(), getQualifierLoc(), getRAngleLoc(), getTemplateKeywordLoc(), and getTemplateNameLoc().
getNumArgs()
unsigned clang::DependentTemplateSpecializationTypeLoc::getNumArgs () const inline
Definition at line 2384 of file TypeLoc.h.
References clang::DependentTemplateSpecializationType::getNumArgs(), and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getTypePtr().
Referenced by clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), getExtraLocalDataSize(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
getQualifierLoc()
NestedNameSpecifierLoc clang::DependentTemplateSpecializationTypeLoc::getQualifierLoc () const inline
Definition at line 2328 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getTypePtr().
Referenced by getLocalSourceRange().
getRAngleLoc()
SourceLocation clang::DependentTemplateSpecializationTypeLoc::getRAngleLoc () const inline
Definition at line 2376 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::RAngleLoc.
Referenced by getLocalSourceRange(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
getTemplateKeywordLoc()
SourceLocation clang::DependentTemplateSpecializationTypeLoc::getTemplateKeywordLoc () const inline
Definition at line 2352 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::TemplateKWLoc.
Referenced by getLocalSourceRange(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
getTemplateNameLoc()
SourceLocation clang::DependentTemplateSpecializationTypeLoc::getTemplateNameLoc () const inline
Definition at line 2360 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentNameLocInfo::NameLoc.
Referenced by getLocalSourceRange(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
initializeLocal()
void DependentTemplateSpecializationTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc)
Definition at line 533 of file TypeLoc.cpp.
References getNumArgs(), clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getTypePtr(), clang::TemplateSpecializationTypeLoc::initializeArgLocs(), clang::NestedNameSpecifierLocBuilder::MakeTrivial(), setElaboratedKeywordLoc(), setLAngleLoc(), setQualifierLoc(), setRAngleLoc(), setTemplateKeywordLoc(), and setTemplateNameLoc().
setArgLocInfo()
void clang::DependentTemplateSpecializationTypeLoc::setArgLocInfo (unsigned i, TemplateArgumentLocInfo AI) inline
Definition at line 2388 of file TypeLoc.h.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setElaboratedKeywordLoc()
void clang::DependentTemplateSpecializationTypeLoc::setElaboratedKeywordLoc (SourceLocation Loc) inline
Definition at line 2324 of file TypeLoc.h.
References clang::ElaboratedLocInfo::ElaboratedKWLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setLAngleLoc()
void clang::DependentTemplateSpecializationTypeLoc::setLAngleLoc (SourceLocation Loc) inline
Definition at line 2372 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::LAngleLoc.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setQualifierLoc()
void clang::DependentTemplateSpecializationTypeLoc::setQualifierLoc (NestedNameSpecifierLoc QualifierLoc) inline
Definition at line 2336 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getOpaqueData(), clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getTypePtr(), and clang::ElaboratedLocInfo::QualifierData.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setRAngleLoc()
void clang::DependentTemplateSpecializationTypeLoc::setRAngleLoc (SourceLocation Loc) inline
Definition at line 2380 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::RAngleLoc.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setTemplateKeywordLoc()
void clang::DependentTemplateSpecializationTypeLoc::setTemplateKeywordLoc (SourceLocation Loc) inline
Definition at line 2356 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentTemplateSpecializationLocInfo::TemplateKWLoc.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
setTemplateNameLoc()
void clang::DependentTemplateSpecializationTypeLoc::setTemplateNameLoc (SourceLocation Loc) inline
Definition at line 2364 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentTemplateSpecializationTypeLoc, DependentTemplateSpecializationType, DependentTemplateSpecializationLocInfo >::getLocalData(), and clang::DependentNameLocInfo::NameLoc.
Referenced by clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTemplateIdType(), clang::Sema::ActOnTypenameType(), initializeLocal(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), and clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp