clang: clang::CodeGen::CGOpenMPRuntimeNVPTX Class Reference
clang::CodeGen::CGOpenMPRuntimeNVPTX Class Reference final
#include "/root/llvm-project/clang/lib/CodeGen/CGOpenMPRuntimeNVPTX.h"
Public Member Functions
CGOpenMPRuntimeNVPTX (CodeGenModule &CGM)
llvm::Value * getGPUWarpSize (CodeGenFunction &CGF) override
Get the GPU warp size.
llvm::Value * getGPUThreadID (CodeGenFunction &CGF) override
Get the id of the current thread on the GPU.
llvm::Value * getGPUNumThreads (CodeGenFunction &CGF) override
Get the maximum number of threads in a block of the GPU.
Public Member Functions inherited from clang::CodeGen::CGOpenMPRuntimeGPU
CGOpenMPRuntimeGPU (CodeGenModule &CGM)
void clear () override
virtual void emitProcBindClause (CodeGenFunction &CGF, llvm::omp::ProcBindKind ProcBind, SourceLocation Loc) override
Emit call to void __kmpc_push_proc_bind(ident_t *loc, kmp_int32 global_tid, int proc_bind) to generate code for 'proc_bind' clause.
virtual void emitNumThreadsClause (CodeGenFunction &CGF, llvm::Value *NumThreads, SourceLocation Loc) override
Emits call to void __kmpc_push_num_threads(ident_t *loc, kmp_int32 global_tid, kmp_int32 num_threads) to generate code for 'num_threads' clause.
void emitNumTeamsClause (CodeGenFunction &CGF, const Expr *NumTeams, const Expr *ThreadLimit, SourceLocation Loc) override
This function ought to emit, in the general case, a call to.
llvm::Function * emitParallelOutlinedFunction (const OMPExecutableDirective &D, const VarDecl *ThreadIDVar, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen) override
Emits inlined function for the specified OpenMP parallel.
llvm::Function * emitTeamsOutlinedFunction (const OMPExecutableDirective &D, const VarDecl *ThreadIDVar, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen) override
Emits inlined function for the specified OpenMP teams.
void emitTeamsCall (CodeGenFunction &CGF, const OMPExecutableDirective &D, SourceLocation Loc, llvm::Function *OutlinedFn, ArrayRef< llvm::Value * > CapturedVars) override
Emits code for teams call of the OutlinedFn with variables captured in a record which address is stored in CapturedStruct.
void emitParallelCall (CodeGenFunction &CGF, SourceLocation Loc, llvm::Function *OutlinedFn, ArrayRef< llvm::Value * > CapturedVars, const Expr *IfCond) override
Emits code for parallel or serial call of the OutlinedFn with variables captured in a record which address is stored in CapturedStruct.
void emitBarrierCall (CodeGenFunction &CGF, SourceLocation Loc, OpenMPDirectiveKind Kind, bool EmitChecks=true, bool ForceSimpleCall=false) override
Emit an implicit/explicit barrier for OpenMP threads.
void emitCriticalRegion (CodeGenFunction &CGF, StringRef CriticalName, const RegionCodeGenTy &CriticalOpGen, SourceLocation Loc, const Expr *Hint=nullptr) override
Emits a critical region.
virtual void emitReduction (CodeGenFunction &CGF, SourceLocation Loc, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > LHSExprs, ArrayRef< const Expr * > RHSExprs, ArrayRef< const Expr * > ReductionOps, ReductionOptionsTy Options) override
Emit a code for reduction clause.
llvm::FunctionCallee createNVPTXRuntimeFunction (unsigned Function)
Returns specified OpenMP runtime function for the current OpenMP implementation.
const VarDecl * translateParameter (const FieldDecl *FD, const VarDecl *NativeParam) const override
Translates the native parameter of outlined function if this is required for target.
Address getParameterAddress (CodeGenFunction &CGF, const VarDecl *NativeParam, const VarDecl *TargetParam) const override
Gets the address of the native argument basing on the address of the target-specific parameter.
void emitOutlinedFunctionCall (CodeGenFunction &CGF, SourceLocation Loc, llvm::FunctionCallee OutlinedFn, ArrayRef< llvm::Value * > Args=llvm::None) const override
Emits call of the outlined function with the provided arguments, translating these arguments to correct target-specific arguments.
void emitFunctionProlog (CodeGenFunction &CGF, const Decl *D) override
Emits OpenMP-specific function prolog.
Address getAddressOfLocalVariable (CodeGenFunction &CGF, const VarDecl *VD) override
Gets the OpenMP-specific address of the local variable.
void functionFinished (CodeGenFunction &CGF) override
Cleans up references to the objects in finished function.
void getDefaultDistScheduleAndChunk (CodeGenFunction &CGF, const OMPLoopDirective &S, OpenMPDistScheduleClauseKind &ScheduleKind, llvm::Value *&Chunk) const override
Choose a default value for the dist_schedule clause.
void getDefaultScheduleAndChunk (CodeGenFunction &CGF, const OMPLoopDirective &S, OpenMPScheduleClauseKind &ScheduleKind, const Expr *&ChunkExpr) const override
Choose a default value for the schedule clause.
void adjustTargetSpecificDataForLambdas (CodeGenFunction &CGF, const OMPExecutableDirective &D) const override
Adjust some parameters for the target-based directives, like addresses of the variables captured by reference in lambdas.
void processRequiresDirective (const OMPRequiresDecl *D) override
Perform check on requires decl to ensure that target architecture supports unified addressing.
unsigned getDefaultFirstprivateAddressSpace () const override
Returns default address space for the constant firstprivates, constant address space by default.
bool hasAllocateAttributeForGlobalVar (const VarDecl *VD, LangAS &AS) override
Checks if the variable has associated OMPAllocateDeclAttr attribute with the predefined allocator and translates it into the corresponding address space.
Public Member Functions inherited from clang::CodeGen::CGOpenMPRuntime
llvm::OpenMPIRBuilder & getOMPBuilder ()
CGOpenMPRuntime (CodeGenModule &CGM)
virtual ~CGOpenMPRuntime ()
void emitIfClause (CodeGenFunction &CGF, const Expr *Cond, const RegionCodeGenTy &ThenGen, const RegionCodeGenTy &ElseGen)
Emits code for OpenMP 'if' clause using specified CodeGen function.
std::string getName (ArrayRef< StringRef > Parts) const
Get the platform-specific name separator.
virtual void emitUserDefinedReduction (CodeGenFunction *CGF, const OMPDeclareReductionDecl *D)
Emit code for the specified user defined reduction construct.
virtual std::pair< llvm::Function *, llvm::Function * > getUserDefinedReduction (const OMPDeclareReductionDecl *D)
Get combiner/initializer for the specified user-defined reduction, if any.
void emitUserDefinedMapper (const OMPDeclareMapperDecl *D, CodeGenFunction *CGF=nullptr)
Emit the function for the user defined mapper construct.
llvm::Function * getOrCreateUserDefinedMapperFunc (const OMPDeclareMapperDecl *D)
Get the function for the specified user-defined mapper.
virtual llvm::Function * emitTaskOutlinedFunction (const OMPExecutableDirective &D, const VarDecl *ThreadIDVar, const VarDecl *PartIDVar, const VarDecl *TaskTVar, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen, bool Tied, unsigned &NumberOfParts)
Emits outlined function for the OpenMP task directive D.
virtual void emitMasterRegion (CodeGenFunction &CGF, const RegionCodeGenTy &MasterOpGen, SourceLocation Loc)
Emits a master region.
virtual void emitTaskyieldCall (CodeGenFunction &CGF, SourceLocation Loc)
Emits code for a taskyield directive.
virtual void emitTaskgroupRegion (CodeGenFunction &CGF, const RegionCodeGenTy &TaskgroupOpGen, SourceLocation Loc)
Emit a taskgroup region.
virtual void emitSingleRegion (CodeGenFunction &CGF, const RegionCodeGenTy &SingleOpGen, SourceLocation Loc, ArrayRef< const Expr * > CopyprivateVars, ArrayRef< const Expr * > DestExprs, ArrayRef< const Expr * > SrcExprs, ArrayRef< const Expr * > AssignmentOps)
Emits a single region.
virtual void emitOrderedRegion (CodeGenFunction &CGF, const RegionCodeGenTy &OrderedOpGen, SourceLocation Loc, bool IsThreads)
Emit an ordered region.
virtual bool isStaticNonchunked (OpenMPScheduleClauseKind ScheduleKind, bool Chunked) const
Check if the specified ScheduleKind is static non-chunked.
virtual bool isStaticNonchunked (OpenMPDistScheduleClauseKind ScheduleKind, bool Chunked) const
Check if the specified ScheduleKind is static non-chunked.
virtual bool isStaticChunked (OpenMPScheduleClauseKind ScheduleKind, bool Chunked) const
Check if the specified ScheduleKind is static chunked.
virtual bool isStaticChunked (OpenMPDistScheduleClauseKind ScheduleKind, bool Chunked) const
Check if the specified ScheduleKind is static non-chunked.
virtual bool isDynamic (OpenMPScheduleClauseKind ScheduleKind) const
Check if the specified ScheduleKind is dynamic.
virtual void emitForDispatchInit (CodeGenFunction &CGF, SourceLocation Loc, const OpenMPScheduleTy &ScheduleKind, unsigned IVSize, bool IVSigned, bool Ordered, const DispatchRTInput &DispatchValues)
Call the appropriate runtime routine to initialize it before start of loop.
virtual void emitForStaticInit (CodeGenFunction &CGF, SourceLocation Loc, OpenMPDirectiveKind DKind, const OpenMPScheduleTy &ScheduleKind, const StaticRTInput &Values)
Call the appropriate runtime routine to initialize it before start of loop.
virtual void emitDistributeStaticInit (CodeGenFunction &CGF, SourceLocation Loc, OpenMPDistScheduleClauseKind SchedKind, const StaticRTInput &Values)
virtual void emitForOrderedIterationEnd (CodeGenFunction &CGF, SourceLocation Loc, unsigned IVSize, bool IVSigned)
Call the appropriate runtime routine to notify that we finished iteration of the ordered loop with the dynamic scheduling.
virtual void emitForStaticFinish (CodeGenFunction &CGF, SourceLocation Loc, OpenMPDirectiveKind DKind)
Call the appropriate runtime routine to notify that we finished all the work with current loop.
virtual llvm::Value * emitForNext (CodeGenFunction &CGF, SourceLocation Loc, unsigned IVSize, bool IVSigned, Address IL, Address LB, Address UB, Address ST)
Call __kmpc_dispatch_next(ident_t *loc, kmp_int32 tid, kmp_int32 *p_lastiter, kmp_int[32|64] *p_lower, kmp_int[32|64] *p_upper, kmp_int[32|64] *p_stride);.
virtual Address getAddrOfThreadPrivate (CodeGenFunction &CGF, const VarDecl *VD, Address VDAddr, SourceLocation Loc)
Returns address of the threadprivate variable for the current thread.
virtual Address getAddrOfDeclareTargetVar (const VarDecl *VD)
Returns the address of the variable marked as declare target with link clause OR as declare target with to clause and unified memory.
virtual llvm::Function * emitThreadPrivateVarDefinition (const VarDecl *VD, Address VDAddr, SourceLocation Loc, bool PerformInit, CodeGenFunction *CGF=nullptr)
Emit a code for initialization of threadprivate variable.
virtual bool emitDeclareTargetVarDefinition (const VarDecl *VD, llvm::GlobalVariable *Addr, bool PerformInit)
Emit a code for initialization of declare target variable.
virtual Address getAddrOfArtificialThreadPrivate (CodeGenFunction &CGF, QualType VarType, StringRef Name)
Creates artificial threadprivate variable with name Name and type VarType.
virtual void emitFlush (CodeGenFunction &CGF, ArrayRef< const Expr * > Vars, SourceLocation Loc, llvm::AtomicOrdering AO)
Emit flush of the variables specified in 'omp flush' directive.
virtual void emitTaskCall (CodeGenFunction &CGF, SourceLocation Loc, const OMPExecutableDirective &D, llvm::Function *TaskFunction, QualType SharedsTy, Address Shareds, const Expr *IfCond, const OMPTaskDataTy &Data)
Emit task region for the task directive.
virtual void emitTaskLoopCall (CodeGenFunction &CGF, SourceLocation Loc, const OMPLoopDirective &D, llvm::Function *TaskFunction, QualType SharedsTy, Address Shareds, const Expr *IfCond, const OMPTaskDataTy &Data)
Emit task region for the taskloop directive.
virtual void emitInlinedDirective (CodeGenFunction &CGF, OpenMPDirectiveKind InnermostKind, const RegionCodeGenTy &CodeGen, bool HasCancel=false)
Emit code for the directive that does not require outlining.
llvm::Function * emitReductionFunction (SourceLocation Loc, llvm::Type *ArgsType, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > LHSExprs, ArrayRef< const Expr * > RHSExprs, ArrayRef< const Expr * > ReductionOps)
Emits reduction function.
void emitSingleReductionCombiner (CodeGenFunction &CGF, const Expr *ReductionOp, const Expr *PrivateRef, const DeclRefExpr *LHS, const DeclRefExpr *RHS)
Emits single reduction combiner.
virtual llvm::Value * emitTaskReductionInit (CodeGenFunction &CGF, SourceLocation Loc, ArrayRef< const Expr * > LHSExprs, ArrayRef< const Expr * > RHSExprs, const OMPTaskDataTy &Data)
Emit a code for initialization of task reduction clause.
virtual void emitTaskReductionFini (CodeGenFunction &CGF, SourceLocation Loc, bool IsWorksharingReduction)
Emits the following code for reduction clause with task modifier:
virtual void emitTaskReductionFixups (CodeGenFunction &CGF, SourceLocation Loc, ReductionCodeGen &RCG, unsigned N)
Required to resolve existing problems in the runtime.
virtual Address getTaskReductionItem (CodeGenFunction &CGF, SourceLocation Loc, llvm::Value *ReductionsPtr, LValue SharedLVal)
Get the address of void * type of the privatue copy of the reduction item specified by the SharedLVal.
virtual void emitTaskwaitCall (CodeGenFunction &CGF, SourceLocation Loc)
Emit code for 'taskwait' directive.
virtual void emitCancellationPointCall (CodeGenFunction &CGF, SourceLocation Loc, OpenMPDirectiveKind CancelRegion)
Emit code for 'cancellation point' construct.
virtual void emitCancelCall (CodeGenFunction &CGF, SourceLocation Loc, const Expr *IfCond, OpenMPDirectiveKind CancelRegion)
Emit code for 'cancel' construct.
virtual void emitTargetCall (CodeGenFunction &CGF, const OMPExecutableDirective &D, llvm::Function *OutlinedFn, llvm::Value *OutlinedFnID, const Expr *IfCond, llvm::PointerIntPair< const Expr *, 2, OpenMPDeviceClauseModifier > Device, llvm::function_ref< llvm::Value *(CodeGenFunction &CGF, const OMPLoopDirective &D)> SizeEmitter)
Emit the target offloading code associated with D.
virtual bool emitTargetFunctions (GlobalDecl GD)
Emit the target regions enclosed in GD function definition or the function itself in case it is a valid device function.
virtual bool emitTargetGlobalVariable (GlobalDecl GD)
Emit the global variable if it is a valid device global variable.
virtual void registerTargetGlobalVariable (const VarDecl *VD, llvm::Constant *Addr)
Checks if the provided global decl GD is a declare target variable and registers it when emitting code for the host.
llvm::Constant * registerTargetFirstprivateCopy (CodeGenFunction &CGF, const VarDecl *VD)
Registers provided target firstprivate variable as global on the target.
virtual bool emitTargetGlobal (GlobalDecl GD)
Emit the global GD if it is meaningful for the target.
llvm::Function * emitRequiresDirectiveRegFun ()
Creates and returns a registration function for when at least one requires directives was used in the current module.
void createOffloadEntriesAndInfoMetadata ()
Creates all the offload entries in the current compilation unit along with the associated metadata.
virtual void emitTargetDataCalls (CodeGenFunction &CGF, const OMPExecutableDirective &D, const Expr *IfCond, const Expr *Device, const RegionCodeGenTy &CodeGen, TargetDataInfo &Info)
Emit the target data mapping code associated with D.
virtual void emitTargetDataStandAloneCall (CodeGenFunction &CGF, const OMPExecutableDirective &D, const Expr *IfCond, const Expr *Device)
Emit the data mapping/movement code associated with the directive D that should be of the form 'target [{enter|exit} data | update]'.
virtual void emitDeclareSimdFunction (const FunctionDecl *FD, llvm::Function *Fn)
Marks function Fn with properly mangled versions of vector functions.
virtual void emitDoacrossInit (CodeGenFunction &CGF, const OMPLoopDirective &D, ArrayRef< Expr * > NumIterations)
Emit initialization for doacross loop nesting support.
virtual void emitDoacrossOrdered (CodeGenFunction &CGF, const OMPDependClause *C)
Emit code for doacross ordered directive with 'depend' clause.
bool markAsGlobalTarget (GlobalDecl GD)
Marks the declaration as already emitted for the device code and returns true, if it was marked already, and false, otherwise.
void emitDeferredTargetDecls () const
Emit deferred declare target variables marked for deferred emission.
llvm::AtomicOrdering getDefaultMemoryOrdering () const
Gets default memory ordering as specified in requires directive.
bool hasRequiresUnifiedSharedMemory () const
Return whether the unified_shared_memory has been specified.
bool isNontemporalDecl (const ValueDecl *VD) const
Checks if the VD variable is marked as nontemporal declaration in current context.
Address emitLastprivateConditionalInit (CodeGenFunction &CGF, const VarDecl *VD)
Create specialized alloca to handle lastprivate conditionals.
virtual void checkAndEmitLastprivateConditional (CodeGenFunction &CGF, const Expr *LHS)
Checks if the provided LVal is lastprivate conditional and emits the code to update the value of the original variable.
virtual void checkAndEmitSharedLastprivateConditional (CodeGenFunction &CGF, const OMPExecutableDirective &D, const llvm::DenseSet< CanonicalDeclPtr< const VarDecl > > &IgnoredDecls)
Checks if the lastprivate conditional was updated in inner region and writes the value.
virtual void emitLastprivateConditionalFinalUpdate (CodeGenFunction &CGF, LValue PrivLVal, const VarDecl *VD, SourceLocation Loc)
Gets the address of the global copy used for lastprivate conditional update, if any.
std::pair< llvm::Value *, Address > emitDependClause (CodeGenFunction &CGF, ArrayRef< OMPTaskDataTy::DependData > Dependencies, SourceLocation Loc)
Emits list of dependecies based on the provided data (array of dependence/expression pairs).
Address emitDepobjDependClause (CodeGenFunction &CGF, const OMPTaskDataTy::DependData &Dependencies, SourceLocation Loc)
Emits list of dependecies based on the provided data (array of dependence/expression pairs) for depobj construct.
void emitDestroyClause (CodeGenFunction &CGF, LValue DepobjLVal, SourceLocation Loc)
Emits the code to destroy the dependency object provided in depobj directive.
void emitUpdateClause (CodeGenFunction &CGF, LValue DepobjLVal, OpenMPDependClauseKind NewDepKind, SourceLocation Loc)
Updates the dependency kind in the specified depobj object.
void emitUsesAllocatorsInit (CodeGenFunction &CGF, const Expr *Allocator, const Expr *AllocatorTraits)
Initializes user defined allocators specified in the uses_allocators clauses.
void emitUsesAllocatorsFini (CodeGenFunction &CGF, const Expr *Allocator)
Destroys user defined allocators specified in the uses_allocators clause.
bool isLocalVarInUntiedTask (CodeGenFunction &CGF, const VarDecl *VD) const
Returns true if the variable is a local variable in untied task.
Additional Inherited Members
Public Types inherited from clang::CodeGen::CGOpenMPRuntimeGPU
enum ExecutionMode { EM_SPMD , EM_NonSPMD , EM_Unknown }
Defines the execution mode.
enum DataSharingMode { CUDA , Generic }
Target codegen is specialized based on two data-sharing modes: CUDA, in which the local variables are actually global threadlocal, and Generic, in which the local variables are placed in global memory if they may escape their declaration context.
Static Public Member Functions inherited from clang::CodeGen::CGOpenMPRuntime
static const Stmt * getSingleCompoundChild (ASTContext &Ctx, const Stmt *Body)
Checks if the Body is the CompoundStmt and returns its child statement iff there is only one that is not evaluatable at the compile time.
Protected Member Functions inherited from clang::CodeGen::CGOpenMPRuntimeGPU
StringRef getOutlinedHelperName () const override
Get the function name of an outlined region.
bool isDefaultLocationConstant () const override
Check if the default location must be constant.
unsigned getDefaultLocationReserved2Flags () const override
Returns additional flags that can be stored in reserved_2 field of the default location.
Protected Member Functions inherited from clang::CodeGen::CGOpenMPRuntime
CGOpenMPRuntime (CodeGenModule &CGM, StringRef FirstSeparator, StringRef Separator)
Constructor allowing to redefine the name separator for the variables.
virtual void emitTargetOutlinedFunctionHelper (const OMPExecutableDirective &D, StringRef ParentName, llvm::Function *&OutlinedFn, llvm::Constant *&OutlinedFnID, bool IsOffloadEntry, const RegionCodeGenTy &CodeGen)
Helper to emit outlined function for 'target' directive.
llvm::Value * emitUpdateLocation (CodeGenFunction &CGF, SourceLocation Loc, unsigned Flags=0)
Emits object of ident_t type with info for source location.
llvm::Type * getIdentTyPointerTy ()
Returns pointer to ident_t type.
llvm::Value * getThreadID (CodeGenFunction &CGF, SourceLocation Loc)
Gets thread id value for the current thread.
void emitCall (CodeGenFunction &CGF, SourceLocation Loc, llvm::FunctionCallee Callee, ArrayRef< llvm::Value * > Args=llvm::None) const
Emits Callee function call with arguments Args with location Loc.
virtual Address emitThreadIDAddress (CodeGenFunction &CGF, SourceLocation Loc)
Emits address of the word in a memory where current thread id is stored.
void setLocThreadIdInsertPt (CodeGenFunction &CGF, bool AtCurrentPoint=false)
void clearLocThreadIdInsertPt (CodeGenFunction &CGF)
llvm::ArrayType * getKmpCriticalNameTy () const
Get the LLVM type for the critical name.
llvm::Value * getCriticalRegionLock (StringRef CriticalName)
Returns corresponding lock object for the specified critical region name.
Static Protected Member Functions inherited from clang::CodeGen::CGOpenMPRuntime
static unsigned getDefaultFlagsForBarriers (OpenMPDirectiveKind Kind)
Returns default flags for the barriers depending on the directive, for which this barier is going to be emitted.
Protected Attributes inherited from clang::CodeGen::CGOpenMPRuntime
CodeGenModule & CGM
StringRef FirstSeparator
StringRef Separator
llvm::OpenMPIRBuilder OMPBuilder
An OpenMP-IR-Builder instance.
Detailed Description
Definition at line 25 of file CGOpenMPRuntimeNVPTX.h.
Constructor & Destructor Documentation
CGOpenMPRuntimeNVPTX()
CGOpenMPRuntimeNVPTX::CGOpenMPRuntimeNVPTX (CodeGenModule & CGM) explicit
Definition at line 29 of file CGOpenMPRuntimeNVPTX.cpp.
References clang::CodeGen::CGOpenMPRuntime::CGM, and clang::CodeGen::CodeGenModule::getLangOpts().
Member Function Documentation
getGPUNumThreads()
llvm::Value * CGOpenMPRuntimeNVPTX::getGPUNumThreads (CodeGenFunction & CGF) override virtual
Get the maximum number of threads in a block of the GPU.
Implements clang::CodeGen::CGOpenMPRuntimeGPU.
Definition at line 50 of file CGOpenMPRuntimeNVPTX.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenModule::getModule().
getGPUThreadID()
llvm::Value * CGOpenMPRuntimeNVPTX::getGPUThreadID (CodeGenFunction & CGF) override virtual
Get the id of the current thread on the GPU.
Implements clang::CodeGen::CGOpenMPRuntimeGPU.
Definition at line 42 of file CGOpenMPRuntimeNVPTX.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenModule::getModule().
getGPUWarpSize()
llvm::Value * CGOpenMPRuntimeNVPTX::getGPUWarpSize (CodeGenFunction & CGF) override virtual
Get the GPU warp size.
Implements clang::CodeGen::CGOpenMPRuntimeGPU.
Definition at line 35 of file CGOpenMPRuntimeNVPTX.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitRuntimeCall(), and clang::CodeGen::CodeGenModule::getModule().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntimeNVPTX.h
lib/CodeGen/CGOpenMPRuntimeNVPTX.cpp