clang: clang::ento::SValExplainer Class Reference
clang::ento::SValExplainer Class Reference
#include "clang/StaticAnalyzer/Checkers/SValExplainer.h"
Public Member Functions
SValExplainer (ASTContext &Ctx)
std::string VisitUnknownVal (UnknownVal V)
std::string VisitUndefinedVal (UndefinedVal V)
std::string VisitLocMemRegionVal (loc::MemRegionVal V)
std::string VisitLocConcreteInt (loc::ConcreteInt V)
std::string VisitNonLocSymbolVal (nonloc::SymbolVal V)
std::string VisitNonLocConcreteInt (nonloc::ConcreteInt V)
std::string VisitNonLocLazyCompoundVal (nonloc::LazyCompoundVal V)
std::string VisitSymbolRegionValue (const SymbolRegionValue *S)
std::string VisitSymbolConjured (const SymbolConjured *S)
std::string VisitSymbolDerived (const SymbolDerived *S)
std::string VisitSymbolExtent (const SymbolExtent *S)
std::string VisitSymbolMetadata (const SymbolMetadata *S)
std::string VisitSymIntExpr (const SymIntExpr *S)
std::string VisitSymSymExpr (const SymSymExpr *S)
std::string VisitSymbolicRegion (const SymbolicRegion *R)
std::string VisitAllocaRegion (const AllocaRegion *R)
std::string VisitCompoundLiteralRegion (const CompoundLiteralRegion *R)
std::string VisitStringRegion (const StringRegion *R)
std::string VisitElementRegion (const ElementRegion *R)
std::string VisitNonParamVarRegion (const NonParamVarRegion *R)
std::string VisitObjCIvarRegion (const ObjCIvarRegion *R)
std::string VisitFieldRegion (const FieldRegion *R)
std::string VisitCXXTempObjectRegion (const CXXTempObjectRegion *R)
std::string VisitCXXBaseObjectRegion (const CXXBaseObjectRegion *R)
std::string VisitParamVarRegion (const ParamVarRegion *R)
std::string VisitSVal (SVal V)
std::string VisitSymExpr (SymbolRef S)
std::string VisitMemRegion (const MemRegion *R)
Public Member Functions inherited from clang::ento::SValVisitor< SValExplainer, std::string >
std::string Visit (SVal V)
std::string VisitSVal (SVal V)
Public Member Functions inherited from clang::ento::SymExprVisitor< SValExplainer, std::string >
std::string Visit (SymbolRef S)
std::string VisitSymExpr (SymbolRef S)
Public Member Functions inherited from clang::ento::MemRegionVisitor< SValExplainer, std::string >
std::string Visit (const MemRegion *R)
std::string VisitMemRegion (const MemRegion *R)
Detailed Description
Definition at line 27 of file SValExplainer.h.
Constructor & Destructor Documentation
SValExplainer()
clang::ento::SValExplainer::SValExplainer (ASTContext & Ctx) inline
Definition at line 46 of file SValExplainer.h.
Member Function Documentation
VisitAllocaRegion()
std::string clang::ento::SValExplainer::VisitAllocaRegion (const AllocaRegion * R) inline
Definition at line 157 of file SValExplainer.h.
References clang::ento::AllocaRegion::getExpr().
VisitCompoundLiteralRegion()
std::string clang::ento::SValExplainer::VisitCompoundLiteralRegion (const CompoundLiteralRegion * R) inline
Definition at line 161 of file SValExplainer.h.
References clang::ento::CompoundLiteralRegion::getLiteralExpr().
VisitCXXBaseObjectRegion()
std::string clang::ento::SValExplainer::VisitCXXBaseObjectRegion (const CXXBaseObjectRegion * R) inline
Definition at line 215 of file SValExplainer.h.
References clang::ento::CXXBaseObjectRegion::getDecl(), clang::NamedDecl::getQualifiedNameAsString(), clang::ento::SubRegion::getSuperRegion(), and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitCXXTempObjectRegion()
std::string clang::ento::SValExplainer::VisitCXXTempObjectRegion (const CXXTempObjectRegion * R) inline
Definition at line 210 of file SValExplainer.h.
References clang::ento::CXXTempObjectRegion::getExpr().
VisitElementRegion()
std::string clang::ento::SValExplainer::VisitElementRegion (const ElementRegion * R) inline
Definition at line 169 of file SValExplainer.h.
References clang::ento::SVal::getAs(), clang::QualType::getAsString(), clang::ento::ElementRegion::getElementType(), clang::ento::ElementRegion::getIndex(), clang::ento::SubRegion::getSuperRegion(), clang::ento::OS, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitFieldRegion()
std::string clang::ento::SValExplainer::VisitFieldRegion (const FieldRegion * R) inline
Definition at line 205 of file SValExplainer.h.
References clang::ento::FieldRegion::getDecl(), clang::NamedDecl::getNameAsString(), clang::ento::SubRegion::getSuperRegion(), and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitLocConcreteInt()
std::string clang::ento::SValExplainer::VisitLocConcreteInt (loc::ConcreteInt V) inline
Definition at line 67 of file SValExplainer.h.
References clang::ento::OS, and V.
VisitLocMemRegionVal()
std::string clang::ento::SValExplainer::VisitLocMemRegionVal (loc::MemRegionVal V) inline
Definition at line 56 of file SValExplainer.h.
References V, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitMemRegion()
std::string clang::ento::SValExplainer::VisitMemRegion (const MemRegion * R) inline
Definition at line 269 of file SValExplainer.h.
References clang::ento::OS.
VisitNonLocConcreteInt()
std::string clang::ento::SValExplainer::VisitNonLocConcreteInt (nonloc::ConcreteInt V) inline
Definition at line 79 of file SValExplainer.h.
References clang::ento::OS, and V.
VisitNonLocLazyCompoundVal()
std::string clang::ento::SValExplainer::VisitNonLocLazyCompoundVal (nonloc::LazyCompoundVal V) inline
Definition at line 88 of file SValExplainer.h.
References V, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitNonLocSymbolVal()
std::string clang::ento::SValExplainer::VisitNonLocSymbolVal (nonloc::SymbolVal V) inline
Definition at line 75 of file SValExplainer.h.
References V, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitNonParamVarRegion()
std::string clang::ento::SValExplainer::VisitNonParamVarRegion (const NonParamVarRegion * R) inline
Definition at line 183 of file SValExplainer.h.
References clang::ento::NonParamVarRegion::getDecl(), clang::NamedDecl::getQualifiedNameAsString(), clang::Decl::hasAttr(), clang::VarDecl::hasGlobalStorage(), clang::VarDecl::hasLocalStorage(), and clang::VarDecl::isStaticLocal().
VisitObjCIvarRegion()
std::string clang::ento::SValExplainer::VisitObjCIvarRegion (const ObjCIvarRegion * R) inline
Definition at line 200 of file SValExplainer.h.
References clang::ento::ObjCIvarRegion::getDecl(), clang::NamedDecl::getNameAsString(), clang::ento::SubRegion::getSuperRegion(), and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitParamVarRegion()
std::string clang::ento::SValExplainer::VisitParamVarRegion (const ParamVarRegion * R) inline
Definition at line 220 of file SValExplainer.h.
References clang::ento::ParamVarRegion::getDecl(), clang::LocationContext::getDecl(), clang::ento::ParamVarRegion::getIndex(), clang::NamedDecl::getQualifiedNameAsString(), clang::ento::VarRegion::getStackFrame(), clang::ento::OS, and Parent.
VisitStringRegion()
std::string clang::ento::SValExplainer::VisitStringRegion (const StringRegion * R) inline
Definition at line 165 of file SValExplainer.h.
References clang::ento::MemRegion::getString().
VisitSVal()
std::string clang::ento::SValExplainer::VisitSVal (SVal V) inline
Definition at line 253 of file SValExplainer.h.
References clang::ento::OS, and V.
VisitSymbolConjured()
std::string clang::ento::SValExplainer::VisitSymbolConjured (const SymbolConjured * S) inline
Definition at line 101 of file SValExplainer.h.
VisitSymbolDerived()
std::string clang::ento::SValExplainer::VisitSymbolDerived (const SymbolDerived * S) inline
Definition at line 106 of file SValExplainer.h.
References clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymbolExtent()
std::string clang::ento::SValExplainer::VisitSymbolExtent (const SymbolExtent * S) inline
Definition at line 111 of file SValExplainer.h.
References clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymbolicRegion()
std::string clang::ento::SValExplainer::VisitSymbolicRegion (const SymbolicRegion * R) inline
Definition at line 141 of file SValExplainer.h.
References clang::Type::getAs(), clang::QualType::getCanonicalType(), clang::ento::MemRegion::getMemorySpace(), clang::ento::SymbolicRegion::getSymbol(), clang::ento::SymExpr::getType(), and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymbolMetadata()
std::string clang::ento::SValExplainer::VisitSymbolMetadata (const SymbolMetadata * S) inline
Definition at line 115 of file SValExplainer.h.
References clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymbolRegionValue()
std::string clang::ento::SValExplainer::VisitSymbolRegionValue (const SymbolRegionValue * S) inline
Definition at line 92 of file SValExplainer.h.
References V, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymExpr()
std::string clang::ento::SValExplainer::VisitSymExpr (SymbolRef S) inline
Definition at line 261 of file SValExplainer.h.
References clang::ento::OS.
VisitSymIntExpr()
std::string clang::ento::SValExplainer::VisitSymIntExpr (const SymIntExpr * S) inline
Definition at line 120 of file SValExplainer.h.
References clang::BinaryOperator::getOpcodeStr(), clang::ento::OS, and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitSymSymExpr()
std::string clang::ento::SValExplainer::VisitSymSymExpr (const SymSymExpr * S) inline
Definition at line 132 of file SValExplainer.h.
References clang::BinaryOperator::getOpcodeStr(), and clang::ento::SValVisitor< SValExplainer, std::string >::Visit().
VisitUndefinedVal()
std::string clang::ento::SValExplainer::VisitUndefinedVal (UndefinedVal V) inline
Definition at line 52 of file SValExplainer.h.
VisitUnknownVal()
std::string clang::ento::SValExplainer::VisitUnknownVal (UnknownVal V) inline
Definition at line 48 of file SValExplainer.h.
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Checkers/SValExplainer.h