clang: clang::DirectoryEntry Class Reference
clang::DirectoryEntry Class Reference
Cached information about one directory (either on disk or in the virtual file system).
#include "clang/Basic/DirectoryEntry.h"
Public Member Functions
StringRef getName () const
Friends
class FileManager
Detailed Description
Cached information about one directory (either on disk or in the virtual file system).
Definition at line 33 of file DirectoryEntry.h.
Member Function Documentation
getName()
StringRef clang::DirectoryEntry::getName () const inline
Definition at line 40 of file DirectoryEntry.h.
Referenced by clang::ASTSourceDescriptor::ASTSourceDescriptor(), compileModule(), clang::FileManager::getCanonicalName(), clang::FileManager::getDirectoryRef(), clang::DirectoryLookup::getName(), inferFrameworkLink(), clang::ModuleMap::isHeaderUnavailableInModule(), clang::HeaderSearch::loadModuleMapFile(), clang::DirectoryLookup::LookupFile(), and clang::HeaderSearch::lookupModuleMapFile().
Friends And Related Symbol Documentation
FileManager
friend class FileManager friend
Definition at line 34 of file DirectoryEntry.h.
The documentation for this class was generated from the following file:
include/clang/Basic/DirectoryEntry.h