clang: clang::targets::DarwinTargetInfo< Target > Class Template Reference
clang::targets::DarwinTargetInfo< Target > Class Template Reference
#include "/root/llvm-project/clang/lib/Basic/Targets/OSTargets.h"
Public Member Functions
DarwinTargetInfo (const llvm::Triple &Triple, const TargetOptions &Opts)
std::string isValidSectionSpecifier (StringRef SR) const override
const char * getStaticInitSectionSpecifier () const override
bool hasProtectedVisibility () const override
Darwin does not support protected visibility.
unsigned getExnObjectAlignment () const override
TargetInfo::IntType getLeastIntTypeByWidth (unsigned BitWidth, bool IsSigned) const final
Public Member Functions inherited from clang::targets::OSTargetInfo< Target >
OSTargetInfo (const llvm::Triple &Triple, const TargetOptions &Opts)
void getTargetDefines (const LangOptions &Opts, MacroBuilder &Builder) const override
Protected Member Functions
void getOSDefines (const LangOptions &Opts, const llvm::Triple &Triple, MacroBuilder &Builder) const override
Protected Member Functions inherited from clang::targets::OSTargetInfo< Target >
Detailed Description
template<typename Target>
class clang::targets::DarwinTargetInfo< Target >
Definition at line 79 of file OSTargets.h.
Constructor & Destructor Documentation
DarwinTargetInfo()
template<typename Target > clang::targets::DarwinTargetInfo< Target >::DarwinTargetInfo (const llvm::Triple & Triple, const TargetOptions & Opts) inline
Definition at line 88 of file OSTargets.h.
References if().
Member Function Documentation
getExnObjectAlignment()
template<typename Target > unsigned clang::targets::DarwinTargetInfo< Target >::getExnObjectAlignment () const inline override
Definition at line 136 of file OSTargets.h.
getLeastIntTypeByWidth()
template<typename Target > TargetInfo::IntType clang::targets::DarwinTargetInfo< Target >::getLeastIntTypeByWidth (unsigned BitWidth, bool IsSigned) const inline final
Definition at line 168 of file OSTargets.h.
References clang::TargetInfo::getLeastIntTypeByWidth(), clang::TransferrableTargetInfo::SignedLongLong, and clang::TransferrableTargetInfo::UnsignedLongLong.
getOSDefines()
template<typename Target > void clang::targets::DarwinTargetInfo< Target >::getOSDefines (const LangOptions & Opts, const llvm::Triple & Triple, MacroBuilder & Builder) const inline override protected virtual
Implements clang::targets::OSTargetInfo< Target >.
Definition at line 81 of file OSTargets.h.
References clang::targets::getDarwinDefines().
getStaticInitSectionSpecifier()
template<typename Target > const char * clang::targets::DarwinTargetInfo< Target >::getStaticInitSectionSpecifier () const inline override
Definition at line 126 of file OSTargets.h.
hasProtectedVisibility()
template<typename Target > bool clang::targets::DarwinTargetInfo< Target >::hasProtectedVisibility () const inline override
Darwin does not support protected visibility.
Darwin's "default" is very similar to ELF's "protected"; Darwin requires a "weak" attribute on declarations that can be dynamically replaced.
Definition at line 134 of file OSTargets.h.
isValidSectionSpecifier()
template<typename Target > std::string clang::targets::DarwinTargetInfo< Target >::isValidSectionSpecifier (StringRef SR) const inline override
Definition at line 117 of file OSTargets.h.
The documentation for this class was generated from the following file:
lib/Basic/Targets/OSTargets.h