clang: clang::ASTReader Class Reference
clang::ASTReader Class Reference
Reads an AST files chain containing the contents of a translation unit.
#include "clang/Serialization/ASTReader.h"
Classes
struct ImportedSubmodule
class ListenerScope
RAII object to temporarily add an AST callback listener.
class ModuleDeclIterator
Public Types
enum ASTReadResult {
Success , Failure , Missing , OutOfDate ,
VersionMismatch , ConfigurationMismatch , HadErrors
}
The result of reading the control block of an AST file, which can fail for various reasons.
using RecordData = SmallVector<uint64_t, 64>
using RecordDataImpl = SmallVectorImpl<uint64_t>
using ModuleFile = serialization::ModuleFile
using ModuleKind = serialization::ModuleKind
using ModuleManager = serialization::ModuleManager
using ModuleIterator = ModuleManager::ModuleIterator
using ModuleConstIterator = ModuleManager::ModuleConstIterator
using ModuleReverseIterator = ModuleManager::ModuleReverseIterator
Public Types inherited from clang::ExternalASTSource
enum ExtKind { EK_Always , EK_Never , EK_ReplyHazy }
Friends
class ASTDeclReader
Types of AST files.
class ASTIdentifierIterator
class ASTRecordReader
class ASTUnit
class ASTWriter
class PCHValidator
class serialization::reader::ASTIdentifierLookupTrait
class serialization::ReadMethodPoolVisitor
class TypeLocReader
Sema-relevant special data
Fields containing data that is used for semantic analysis
enum LoadFailureCapabilities {
ARR_None = 0 , ARR_Missing = 0x1 , ARR_OutOfDate = 0x2 , ARR_VersionMismatch = 0x4 ,
ARR_ConfigurationMismatch = 0x8
}
Flags that indicate what kind of AST loading failures the client of the AST reader can directly handle.
SmallVector< uint64_t, 16 > PreloadedDeclIDs
SmallVector< std::pair< llvm::BitstreamCursor, serialization::ModuleFile * >, 8 > CommentsCursors
Cursors for comments blocks.
void ResolveImportedPath (ModuleFile &M, std::string &Filename)
If we are loading a relocatable PCH or module file, and the filename is not an absolute path, add the system or module root to the beginning of the file name.
Decl * getKeyDeclaration (Decl *D)
Returns the first key declaration for the given declaration.
const Decl * getKeyDeclaration (const Decl *D)
template<typename Fn >
void forEachImportedKeyDecl (const Decl *D, Fn Visit)
Run a callback on each imported key declaration of D.
const serialization::reader::DeclContextLookupTable * getLoadedLookupTables (DeclContext *Primary) const
Get the loaded lookup tables for Primary, if any.
llvm::iterator_range< ModuleDeclIterator > getModuleFileLevelDecls (ModuleFile &Mod)
ASTReader (Preprocessor &PP, InMemoryModuleCache &ModuleCache, ASTContext *Context, const PCHContainerReader &PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension > > Extensions, StringRef isysroot="", DisableValidationForModuleKind DisableValidationKind=DisableValidationForModuleKind::None, bool AllowASTWithCompilerErrors=false, bool AllowConfigurationMismatch=false, bool ValidateSystemInputs=false, bool ValidateASTInputFilesContent=false, bool UseGlobalIndex=true, std::unique_ptr< llvm::Timer > ReadTimer={})
Load the AST file and validate its contents against the given Preprocessor.
ASTReader (const ASTReader &)=delete
ASTReader & operator= (const ASTReader &)=delete
~ASTReader () override
SourceManager & getSourceManager () const
FileManager & getFileManager () const
DiagnosticsEngine & getDiags () const
ASTReadResult ReadAST (StringRef FileName, ModuleKind Type, SourceLocation ImportLoc, unsigned ClientLoadCapabilities, SmallVectorImpl< ImportedSubmodule > *Imported=nullptr)
Load the AST file designated by the given file name.
void makeModuleVisible (Module *Mod, Module::NameVisibilityKind NameVisibility, SourceLocation ImportLoc)
Make the entities in the given module and any of its (non-explicit) submodules visible to name lookup.
void makeNamesVisible (const HiddenNames &Names, Module *Owner)
Make the names within this set of hidden names visible.
void mergeDefinitionVisibility (NamedDecl *Def, NamedDecl *MergedDef)
Note that MergedDef is a redefinition of the canonical definition Def, so Def should be visible whenever MergedDef is.
std::unique_ptr< ASTReaderListener > takeListener ()
Take the AST callbacks listener.
void setListener (std::unique_ptr< ASTReaderListener > Listener)
Set the AST callbacks listener.
void addListener (std::unique_ptr< ASTReaderListener > L)
Add an AST callback listener.
void setDeserializationListener (ASTDeserializationListener *Listener, bool TakeOwnership=false)
Set the AST deserialization listener.
ASTDeserializationListener * getDeserializationListener ()
Get the AST deserialization listener.
bool hasGlobalIndex () const
Determine whether this AST reader has a global index.
GlobalModuleIndex * getGlobalIndex ()
Return global module index.
void resetForReload ()
Reset reader for a reload try.
bool loadGlobalIndex ()
Attempts to load the global index.
bool isGlobalIndexUnavailable () const
Determine whether we tried to load the global index, but failed, e.g., because it is out-of-date or does not exist.
void InitializeContext ()
Initializes the ASTContext.
void UpdateSema ()
Update the state of Sema after loading some additional modules.
void addInMemoryBuffer (StringRef &FileName, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Add in-memory (virtual file) buffer.
void finalizeForWriting ()
Finalizes the AST reader's state before writing an AST file to disk.
ModuleManager & getModuleManager ()
Retrieve the module manager.
Preprocessor & getPreprocessor () const
Retrieve the preprocessor.
StringRef getOriginalSourceFile ()
Retrieve the name of the original source file name for the primary module file.
const std::string & getSuggestedPredefines ()
Returns the suggested contents of the predefines buffer, which contains a (typically-empty) subset of the predefines build prior to including the precompiled header.
PreprocessedEntity * ReadPreprocessedEntity (unsigned Index) override
Read a preallocated preprocessed entity from the external source.
std::pair< unsigned, unsigned > findPreprocessedEntitiesInRange (SourceRange Range) override
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that Range encompasses.
Optional< bool > isPreprocessedEntityInFileID (unsigned Index, FileID FID) override
Optionally returns true or false if the preallocated preprocessed entity with index Index came from file FID.
SourceRange ReadSkippedRange (unsigned Index) override
Read a preallocated skipped range from the external source.
HeaderFileInfo GetHeaderFileInfo (const FileEntry *FE) override
Read the header file information for the given file entry.
void ReadPragmaDiagnosticMappings (DiagnosticsEngine &Diag)
unsigned getTotalNumSLocs () const
Returns the number of source locations found in the chain.
unsigned getTotalNumIdentifiers () const
Returns the number of identifiers found in the chain.
unsigned getTotalNumMacros () const
Returns the number of macros found in the chain.
unsigned getTotalNumTypes () const
Returns the number of types found in the chain.
unsigned getTotalNumDecls () const
Returns the number of declarations found in the chain.
unsigned getTotalNumSubmodules () const
Returns the number of submodules known.
unsigned getTotalNumSelectors () const
Returns the number of selectors found in the chain.
unsigned getTotalNumPreprocessedEntities () const
Returns the number of preprocessed entities known to the AST reader.
QualType GetType (serialization::TypeID ID)
Resolve a type ID into a type, potentially building a new type.
QualType getLocalType (ModuleFile &F, unsigned LocalID)
Resolve a local type ID within a given AST file into a type.
serialization::TypeID getGlobalTypeID (ModuleFile &F, unsigned LocalID) const
Map a local type ID within a given AST file into a global type ID.
QualType readType (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Read a type from the current position in the given record, which was read from the given AST file.
serialization::DeclID getGlobalDeclID (ModuleFile &F, serialization::LocalDeclID LocalID) const
Map from a local declaration ID within a given module to a global declaration ID.
bool isDeclIDFromModule (serialization::GlobalDeclID ID, ModuleFile &M) const
Returns true if global DeclID ID originated from module M.
ModuleFile * getOwningModuleFile (const Decl *D)
Retrieve the module file that owns the given declaration, or NULL if the declaration is not from a module file.
std::string getOwningModuleNameForDiagnostic (const Decl *D)
Get the best name we know for the module that owns the given declaration, or an empty string if the declaration is not from a module.
SourceLocation getSourceLocationForDeclID (serialization::GlobalDeclID ID)
Returns the source location for the decl ID.
Decl * GetDecl (serialization::DeclID ID)
Resolve a declaration ID into a declaration, potentially building a new declaration.
Decl * GetExternalDecl (uint32_t ID) override
Resolve a declaration ID into a declaration, potentially building a new declaration.
Decl * GetExistingDecl (serialization::DeclID ID)
Resolve a declaration ID into a declaration.
Decl * GetLocalDecl (ModuleFile &F, uint32_t LocalID)
Reads a declaration with the given local ID in the given module.
template<typename T >
T * GetLocalDeclAs (ModuleFile &F, uint32_t LocalID)
Reads a declaration with the given local ID in the given module.
serialization::DeclID mapGlobalIDToModuleFileGlobalID (ModuleFile &M, serialization::DeclID GlobalID)
Map a global declaration ID into the declaration ID used to refer to this declaration within the given module fule.
serialization::DeclID ReadDeclID (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Reads a declaration ID from the given position in a record in the given module.
Decl * ReadDecl (ModuleFile &F, const RecordData &R, unsigned &I)
Reads a declaration from the given position in a record in the given module.
template<typename T >
T * ReadDeclAs (ModuleFile &F, const RecordData &R, unsigned &I)
Reads a declaration from the given position in a record in the given module.
void CompleteRedeclChain (const Decl *D) override
If any redeclarations of D have been imported since it was last checked, this digs out those redeclarations and adds them to the redeclaration chain for D.
CXXBaseSpecifier * GetExternalCXXBaseSpecifiers (uint64_t Offset) override
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
Stmt * GetExternalDeclStmt (uint64_t Offset) override
Resolve the offset of a statement into a statement.
bool FindExternalVisibleDeclsByName (const DeclContext *DC, DeclarationName Name) override
Finds all the visible declarations with a given name.
void FindExternalLexicalDecls (const DeclContext *DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > &Decls) override
Read all of the declarations lexically stored in a declaration context.
void FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > &Decls) override
Get the decls that are contained in a file in the Offset/Length range.
void StartedDeserializing () override
Notify ASTReader that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
void FinishedDeserializing () override
Notify ASTReader that we finished the deserialization of a decl or type.
void StartTranslationUnit (ASTConsumer *Consumer) override
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
void PrintStats () override
Print some statistics about AST usage.
void dump ()
Dump information about the AST reader to standard error.
void getMemoryBufferSizes (MemoryBufferSizes &sizes) const override
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
void InitializeSema (Sema &S) override
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
void ForgetSema () override
Inform the semantic consumer that Sema is no longer available.
IdentifierInfo * get (StringRef Name) override
Retrieve the IdentifierInfo for the named identifier.
IdentifierIterator * getIdentifiers () override
Retrieve an iterator into the set of all identifiers in all loaded AST files.
void ReadMethodPool (Selector Sel) override
Load the contents of the global method pool for a given selector.
void updateOutOfDateSelector (Selector Sel) override
Load the contents of the global method pool for a given selector if necessary.
void ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > &Namespaces) override
Load the set of namespaces that are known to the external source, which will be used during typo correction.
void ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > &Undefined) override
Load the set of used but not defined functions or variables with internal linkage, or used but not defined internal functions.
void ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 > > &Exprs) override
void ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > &TentativeDefs) override
Read the set of tentative definitions known to the external Sema source.
void ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > &Decls) override
Read the set of unused file-scope declarations known to the external Sema source.
void ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > &Decls) override
Read the set of delegating constructors known to the external Sema source.
void ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > &Decls) override
Read the set of ext_vector type declarations known to the external Sema source.
void ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > &Decls) override
Read the set of potentially unused typedefs known to the source.
void ReadDeclsToCheckForDeferredDiags (llvm::SmallVector< Decl *, 4 > &Decls) override
Read the set of decls to be checked for deferred diags.
void ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation > > &Sels) override
Read the set of referenced selectors known to the external Sema source.
void ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo > > &WI) override
Read the set of weak, undeclared identifiers known to the external Sema source.
void ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > &VTables) override
Read the set of used vtables known to the external Sema source.
void ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation > > &Pending) override
Read the set of pending instantiations known to the external Sema source.
void ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate > > &LPTMap) override
Read the set of late parsed template functions for this source.
void LoadSelector (Selector Sel)
Load a selector from disk, registering its ID if it exists.
void SetIdentifierInfo (unsigned ID, IdentifierInfo *II)
void SetGloballyVisibleDecls (IdentifierInfo *II, const SmallVectorImpl< uint32_t > &DeclIDs, SmallVectorImpl< Decl * > *Decls=nullptr)
Set the globally-visible declarations associated with the given identifier.
DiagnosticBuilder Diag (unsigned DiagID) const
Report a diagnostic.
DiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID) const
Report a diagnostic.
IdentifierInfo * DecodeIdentifierInfo (serialization::IdentifierID ID)
IdentifierInfo * readIdentifier (ModuleFile &M, const RecordData &Record, unsigned &Idx)
IdentifierInfo * GetIdentifier (serialization::IdentifierID ID) override
IdentifierInfo * getLocalIdentifier (ModuleFile &M, unsigned LocalID)
serialization::IdentifierID getGlobalIdentifierID (ModuleFile &M, unsigned LocalID)
void resolvePendingMacro (IdentifierInfo *II, const PendingMacroInfo &PMInfo)
MacroInfo * getMacro (serialization::MacroID ID)
Retrieve the macro with the given ID.
serialization::MacroID getGlobalMacroID (ModuleFile &M, unsigned LocalID)
Retrieve the global macro ID corresponding to the given local ID within the given module file.
bool ReadSLocEntry (int ID) override
Read the source location entry with index ID.
std::pair< SourceLocation, StringRef > getModuleImportLoc (int ID) override
Retrieve the module import location and module name for the given source manager entry ID.
serialization::SubmoduleID getGlobalSubmoduleID (ModuleFile &M, unsigned LocalID)
Retrieve the global submodule ID given a module and its local ID number.
Module * getSubmodule (serialization::SubmoduleID GlobalID)
Retrieve the submodule that corresponds to a global submodule ID.
Module * getModule (unsigned ID) override
Retrieve the module that corresponds to the given module ID.
ModuleFile * getLocalModuleFile (ModuleFile &M, unsigned ID)
Retrieve the module file with a given local ID within the specified ModuleFile.
unsigned getModuleFileID (ModuleFile *M)
Get an ID for the given module file.
llvm::Optional< ASTSourceDescriptor > getSourceDescriptor (unsigned ID) override
Return a descriptor for the corresponding module.
ExtKind hasExternalDefinitions (const Decl *D) override
Selector getLocalSelector (ModuleFile &M, unsigned LocalID)
Retrieve a selector from the given module with its local ID number.
Selector DecodeSelector (serialization::SelectorID Idx)
Selector GetExternalSelector (serialization::SelectorID ID) override
Resolve a selector ID into a selector.
uint32_t GetNumExternalSelectors () override
Returns the number of selectors known to the external AST source.
Selector ReadSelector (ModuleFile &M, const RecordData &Record, unsigned &Idx)
serialization::SelectorID getGlobalSelectorID (ModuleFile &F, unsigned LocalID) const
Retrieve the global selector ID that corresponds to this the local selector ID in a given module.
CXXCtorInitializer ** GetExternalCXXCtorInitializers (uint64_t Offset) override
Read the contents of a CXXCtorInitializer array.
Sema::AlignPackInfo ReadAlignPackInfo (uint32_t Raw) const
Read a AlignPackInfo from raw form.
SourceLocation ReadUntranslatedSourceLocation (uint32_t Raw) const
Read a source location from raw form and return it in its originating module file's source location space.
SourceLocation ReadSourceLocation (ModuleFile &ModuleFile, uint32_t Raw) const
Read a source location from raw form.
SourceLocation TranslateSourceLocation (ModuleFile &ModuleFile, SourceLocation Loc) const
Translate a source location from another module file's source location space into ours.
SourceLocation ReadSourceLocation (ModuleFile &ModuleFile, const RecordDataImpl &Record, unsigned &Idx)
Read a source location.
SourceRange ReadSourceRange (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Read a source range.
std::string ReadPath (ModuleFile &F, const RecordData &Record, unsigned &Idx)
std::string ReadPath (StringRef BaseDirectory, const RecordData &Record, unsigned &Idx)
CXXTemporary * ReadCXXTemporary (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Stmt * ReadStmt (ModuleFile &F)
Reads a statement.
Expr * ReadExpr (ModuleFile &F)
Reads an expression.
Stmt * ReadSubStmt ()
Reads a sub-statement operand during statement reading.
Expr * ReadSubExpr ()
Reads a sub-expression operand during statement reading.
Token ReadToken (ModuleFile &M, const RecordDataImpl &Record, unsigned &Idx)
Reads a token out of a record.
MacroInfo * ReadMacroRecord (ModuleFile &F, uint64_t Offset)
Reads the macro record located at the given offset.
serialization::PreprocessedEntityID getGlobalPreprocessedEntityID (ModuleFile &M, unsigned LocalID) const
Determine the global preprocessed entity ID that corresponds to the given local ID within the given module.
void addPendingMacro (IdentifierInfo *II, ModuleFile *M, uint32_t MacroDirectivesOffset)
Add a macro to deserialize its macro directive history.
void ReadDefinedMacros () override
Read the set of macros defined by this external macro source.
void updateOutOfDateIdentifier (IdentifierInfo &II) override
Update an out-of-date identifier.
void markIdentifierUpToDate (IdentifierInfo *II)
Note that this identifier is up-to-date.
void completeVisibleDeclsMap (const DeclContext *DC) override
Load all external visible decls in the given DeclContext.
ASTContext & getContext ()
Retrieve the AST context that this AST reader supplements.
Sema * getSema ()
Retrieve the semantic analysis object used to analyze the translation unit in which the precompiled header is being imported.
IdentifierResolver & getIdResolver ()
Get the identifier resolver used for name lookup / updates in the translation unit scope.
IdentifierTable & getIdentifierTable ()
Retrieve the identifier table associated with the preprocessor.
void RecordSwitchCaseID (SwitchCase *SC, unsigned ID)
Record that the given ID maps to the given switch-case statement.
SwitchCase * getSwitchCaseWithID (unsigned ID)
Retrieve the switch-case statement with the given ID.
void ClearSwitchCaseIDs ()
void ReadComments () override
Loads comments ranges.
void visitInputFiles (serialization::ModuleFile &MF, bool IncludeSystem, bool Complain, llvm::function_ref< void(const serialization::InputFile &IF, bool isSystem)> Visitor)
Visit all the input files of the given module file.
void visitTopLevelModuleMaps (serialization::ModuleFile &MF, llvm::function_ref< void(const FileEntry *)> Visitor)
Visit all the top-level module maps loaded when building the given module file.
bool isProcessingUpdateRecords ()
static void ResolveImportedPath (std::string &Filename, StringRef Prefix)
static std::string getOriginalSourceFile (const std::string &ASTFileName, FileManager &FileMgr, const PCHContainerReader &PCHContainerRdr, DiagnosticsEngine &Diags)
Retrieve the name of the original source file name directly from the AST file, without actually loading the AST file.
static bool readASTFileControlBlock (StringRef Filename, FileManager &FileMgr, const PCHContainerReader &PCHContainerRdr, bool FindModuleFileExtensions, ASTReaderListener &Listener, bool ValidateDiagnosticOptions)
Read the control block for the named AST file.
static bool isAcceptableASTFile (StringRef Filename, FileManager &FileMgr, const PCHContainerReader &PCHContainerRdr, const LangOptions &LangOpts, const TargetOptions &TargetOpts, const PreprocessorOptions &PPOpts, StringRef ExistingModuleCachePath)
Determine whether the given AST file is acceptable to load into a translation unit with the given language and target options.
static bool ReadBlockAbbrevs (llvm::BitstreamCursor &Cursor, unsigned BlockID, uint64_t *StartOfBlockOffset=nullptr)
ReadBlockAbbrevs - Enter a subblock of the specified BlockID with the specified cursor.
static std::string ReadString (const RecordData &Record, unsigned &Idx)
static void SkipString (const RecordData &Record, unsigned &Idx)
static void SkipPath (const RecordData &Record, unsigned &Idx)
static VersionTuple ReadVersionTuple (const RecordData &Record, unsigned &Idx)
Read a version tuple.
Additional Inherited Members
Public Member Functions inherited from clang::ExternalPreprocessorSource
virtual ~ExternalPreprocessorSource ()
virtual IdentifierInfo * GetIdentifier (unsigned ID)=0
Return the identifier associated with the given ID number.
Public Member Functions inherited from clang::ExternalPreprocessingRecordSource
virtual ~ExternalPreprocessingRecordSource ()
Public Member Functions inherited from clang::ExternalHeaderFileInfoSource
virtual ~ExternalHeaderFileInfoSource ()
Public Member Functions inherited from clang::ExternalSemaSource
ExternalSemaSource ()=default
~ExternalSemaSource () override
virtual bool LookupUnqualified (LookupResult &R, Scope *S)
Do last resort, unqualified lookup on a LookupResult that Sema cannot find.
virtual TypoCorrection CorrectTypo (const DeclarationNameInfo &Typo, int LookupKind, Scope *S, CXXScopeSpec *SS, CorrectionCandidateCallback &CCC, DeclContext *MemberContext, bool EnteringContext, const ObjCObjectPointerType *OPT)
Try to "correct" a typo in the source code by finding visible declarations whose names are similar to the name that was present in the source code.
virtual bool MaybeDiagnoseMissingCompleteType (SourceLocation Loc, QualType T)
Produces a diagnostic note if the external source contains a complete definition for T.
bool isA (const void *ClassID) const override
LLVM-style RTTI.
Public Member Functions inherited from clang::ExternalASTSource
ExternalASTSource ()=default
virtual ~ExternalASTSource ()
uint32_t getGeneration () const
Get the current generation of this AST source.
void FindExternalLexicalDecls (const DeclContext *DC, SmallVectorImpl< Decl * > &Result)
Finds all declarations lexically contained within the given DeclContext.
virtual void CompleteType (TagDecl *Tag)
Gives the external AST source an opportunity to complete an incomplete type.
virtual void CompleteType (ObjCInterfaceDecl *Class)
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
virtual bool layoutRecordType (const RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &VirtualBaseOffsets)
Perform layout on the given record.
MemoryBufferSizes getMemoryBufferSizes () const
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Public Member Functions inherited from clang::IdentifierInfoLookup
virtual ~IdentifierInfoLookup ()
Public Member Functions inherited from clang::ExternalSLocEntrySource
virtual ~ExternalSLocEntrySource ()
Static Public Member Functions inherited from clang::ExternalSemaSource
static bool classof (const ExternalASTSource *S)
Static Public Member Functions inherited from clang::ExternalASTSource
static bool classof (const ExternalASTSource *S)
Protected Member Functions inherited from clang::ExternalASTSource
uint32_t incrementGeneration (ASTContext &C)
Increment the current generation.
Static Protected Member Functions inherited from clang::ExternalASTSource
static DeclContextLookupResult SetExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name, ArrayRef< NamedDecl * > Decls)
static DeclContextLookupResult SetNoExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name)
Detailed Description
Reads an AST files chain containing the contents of a translation unit.
The ASTReader class reads bitstreams (produced by the ASTWriter class) containing the serialized representation of a given abstract syntax tree and its supporting data structures. An instance of the ASTReader can be attached to an ASTContext object, which will provide access to the contents of the AST files.
The AST reader provides lazy de-serialization of declarations, as required when traversing the AST. Only those AST nodes that are actually required will be de-serialized.
Definition at line 342 of file ASTReader.h.
Member Typedef Documentation
ModuleConstIterator
using clang::ASTReader::ModuleConstIterator = ModuleManager::ModuleConstIterator
Definition at line 397 of file ASTReader.h.
ModuleFile
using clang::ASTReader::ModuleFile = serialization::ModuleFile
Definition at line 393 of file ASTReader.h.
ModuleIterator
using clang::ASTReader::ModuleIterator = ModuleManager::ModuleIterator
Definition at line 396 of file ASTReader.h.
ModuleKind
using clang::ASTReader::ModuleKind = serialization::ModuleKind
Definition at line 394 of file ASTReader.h.
ModuleManager
using clang::ASTReader::ModuleManager = serialization::ModuleManager
Definition at line 395 of file ASTReader.h.
ModuleReverseIterator
using clang::ASTReader::ModuleReverseIterator = ModuleManager::ModuleReverseIterator
Definition at line 398 of file ASTReader.h.
RecordData
using clang::ASTReader::RecordData = SmallVector<uint64_t, 64>
Definition at line 362 of file ASTReader.h.
RecordDataImpl
using clang::ASTReader::RecordDataImpl = SmallVectorImpl<uint64_t>
Definition at line 363 of file ASTReader.h.
Member Enumeration Documentation
ASTReadResult
enum clang::ASTReader::ASTReadResult
The result of reading the control block of an AST file, which can fail for various reasons.
Enumerator
Success
The control block was read successfully.
Aside from failures, the AST file is safe to read into the current context.
Failure
The AST file itself appears corrupted.
Missing
The AST file was missing.
OutOfDate
The AST file is out-of-date relative to its input files, and needs to be regenerated.
VersionMismatch
The AST file was written by a different version of Clang.
ConfigurationMismatch
The AST file was writtten with a different language/target configuration.
HadErrors
The AST file has errors.
Definition at line 367 of file ASTReader.h.
LoadFailureCapabilities
enum clang::ASTReader::LoadFailureCapabilities
Flags that indicate what kind of AST loading failures the client of the AST reader can directly handle.
When a client states that it can handle a particular kind of failure, the AST reader will not emit errors when producing that kind of failure.
Enumerator
ARR_None
The client can't handle any AST loading failures.
ARR_Missing
The client can handle an AST file that cannot load because it is missing.
ARR_OutOfDate
The client can handle an AST file that cannot load because it is out-of-date relative to its input files.
ARR_VersionMismatch
The client can handle an AST file that cannot load because it was built with a different version of Clang.
ARR_ConfigurationMismatch
The client can handle an AST file that cannot load because it's compiled configuration doesn't match that of the context it was loaded into.
Definition at line 1527 of file ASTReader.h.
Constructor & Destructor Documentation
ASTReader() [1/2]
ASTReader::ASTReader (Preprocessor & PP, InMemoryModuleCache & ModuleCache, ASTContext * Context, const PCHContainerReader & PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension > > Extensions, StringRef isysroot = "", DisableValidationForModuleKind DisableValidationKind = DisableValidationForModuleKind::None, bool AllowASTWithCompilerErrors = false, bool AllowConfigurationMismatch = false, bool ValidateSystemInputs = false, bool ValidateASTInputFilesContent = false, bool UseGlobalIndex = true, std::unique_ptr< llvm::Timer > ReadTimer = {})
Load the AST file and validate its contents against the given Preprocessor.
Parameters
PP the preprocessor associated with the context in which this precompiled header will be loaded.
Context the AST context that this precompiled header will be loaded into, if any.
PCHContainerRdr the PCHContainerOperations to use for loading and creating modules.
Extensions the list of module file extensions that can be loaded from the AST files.
isysroot If non-NULL, the system include path specified by the user. This is only used with relocatable PCH files. If non-NULL, a relocatable PCH file will use the default path "/".
DisableValidationKind If set, the AST reader will suppress most of its regular consistency checking, allowing the use of precompiled headers and module files that cannot be determined to be compatible.
AllowASTWithCompilerErrors If true, the AST reader will accept an AST file the was created out of an AST with compiler errors, otherwise it will reject it.
AllowConfigurationMismatch If true, the AST reader will not check for configuration differences between the AST file and the invocation.
ValidateSystemInputs If true, the AST reader will validate system input files in addition to user input files. This is only meaningful if DisableValidation is false.
UseGlobalIndex If true, the AST reader will try to load and use the global module index.
ReadTimer If non-null, a timer used to track the time spent deserializing.
Definition at line 11632 of file ASTReader.cpp.
References clang::DiagnosticsEngine::Report().
ASTReader() [2/2]
clang::ASTReader::ASTReader (const ASTReader &) delete
~ASTReader()
ASTReader::~ASTReader () override
Definition at line 11671 of file ASTReader.cpp.
Member Function Documentation
addInMemoryBuffer()
void clang::ASTReader::addInMemoryBuffer (StringRef & FileName, std::unique_ptr< llvm::MemoryBuffer > Buffer) inline
Add in-memory (virtual file) buffer.
Definition at line 1669 of file ASTReader.h.
References clang::serialization::ModuleManager::addInMemoryBuffer().
addListener()
void clang::ASTReader::addListener (std::unique_ptr< ASTReaderListener > L) inline
Add an AST callback listener.
Takes ownership of L.
Definition at line 1603 of file ASTReader.h.
Referenced by clang::DependencyCollector::attachToASTReader(), and clang::ModuleDependencyCollector::attachToASTReader().
addPendingMacro()
void ASTReader::addPendingMacro (IdentifierInfo * II, ModuleFile * M, uint32_t MacroDirectivesOffset)
Add a macro to deserialize its macro directive history.
Parameters
II The name of the macro.
M The module file.
MacroDirectivesOffset Offset of the serialized macro directive history.
Definition at line 1929 of file ASTReader.cpp.
ClearSwitchCaseIDs()
void ASTReader::ClearSwitchCaseIDs ()
Definition at line 9056 of file ASTReader.cpp.
CompleteRedeclChain()
void ASTReader::CompleteRedeclChain (const Decl * D) override virtual
If any redeclarations of D have been imported since it was last checked, this digs out those redeclarations and adds them to the redeclaration chain for D.
Reimplemented from clang::ExternalASTSource.
Definition at line 7167 of file ASTReader.cpp.
References clang::cast(), clang::CPlusPlus, clang::Decl::getDeclContext(), clang::Decl::getKind(), clang::Decl::getLexicalDeclContext(), clang::DeclContext::getRedeclContext(), clang::DeclContext::lookup(), and clang::serialization::needsAnonymousDeclarationNumber().
completeVisibleDeclsMap()
void ASTReader::completeVisibleDeclsMap (const DeclContext * DC) override virtual
Load all external visible decls in the given DeclContext.
Reimplemented from clang::ExternalASTSource.
Definition at line 7642 of file ASTReader.cpp.
References clang::cast(), clang::NamedDecl::getDeclName(), and clang::DeclContext::hasExternalVisibleStorage().
DecodeIdentifierInfo()
IdentifierInfo * ASTReader::DecodeIdentifierInfo (serialization::IdentifierID ID)
Definition at line 8500 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseIdentifierID, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::Error, clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::serialization::ModuleFile::IdentifierOffsets, clang::ASTDeserializationListener::IdentifierRead(), clang::serialization::ModuleFile::IdentifierTableData, and markIdentifierFromAST().
Referenced by GetIdentifier(), getLocalIdentifier(), readIdentifier(), and ReadWeakUndeclaredIdentifiers().
DecodeSelector()
Selector ASTReader::DecodeSelector (serialization::SelectorID Idx)
Definition at line 8688 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseSelectorID, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::Error, clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::NUM_PREDEF_SELECTOR_IDS, clang::serialization::reader::ASTSelectorLookupTrait::ReadKey(), clang::serialization::ModuleFile::SelectorLookupTableData, clang::serialization::ModuleFile::SelectorOffsets, and clang::ASTDeserializationListener::SelectorRead().
Referenced by GetExternalSelector(), getLocalSelector(), and ReadReferencedSelectors().
Diag() [1/2]
DiagnosticBuilder ASTReader::Diag (SourceLocation Loc, unsigned DiagID) const
Report a diagnostic.
Definition at line 9032 of file ASTReader.cpp.
References clang::DiagnosticsEngine::Report().
Diag() [2/2]
DiagnosticBuilder ASTReader::Diag (unsigned DiagID) const
Report a diagnostic.
Definition at line 9028 of file ASTReader.cpp.
References Diag().
Referenced by Diag().
dump()
LLVM_DUMP_METHOD void ASTReader::dump ()
Dump information about the AST reader to standard error.
Definition at line 7814 of file ASTReader.cpp.
References clang::serialization::ModuleFile::dump(), and dumpModuleIDMap().
finalizeForWriting()
void ASTReader::finalizeForWriting ()
Finalizes the AST reader's state before writing an AST file to disk.
This operation may undo temporary state in the AST that should not be emitted.
Definition at line 5007 of file ASTReader.cpp.
FindExternalLexicalDecls()
void ASTReader::FindExternalLexicalDecls (const DeclContext * DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > & Decls) override virtual
Read all of the declarations lexically stored in a declaration context.
Parameters
DC The declaration context whose declarations will be read.
IsKindWeWant A predicate indicating which declaration kinds we are interested in.
Decls Vector that will contain the declarations loaded from the external source. The caller is responsible for merging these declarations with any declarations already stored in the declaration context.
Reimplemented from clang::ExternalASTSource.
Definition at line 7498 of file ASTReader.cpp.
References clang::DeclContext::isDeclInLexicalTraversal(), N, and clang::serialization::NUM_PREDEF_DECL_IDS.
FindExternalVisibleDeclsByName()
bool ASTReader::FindExternalVisibleDeclsByName (const DeclContext * DC, DeclarationName Name) override virtual
Finds all the visible declarations with a given name.
The current implementation of this method just loads the entire lookup table as unmaterialized references.
Reimplemented from clang::ExternalASTSource.
Definition at line 7616 of file ASTReader.cpp.
References clang::cast(), clang::NamedDecl::getDeclName(), clang::DeclContext::getPrimaryContext(), and clang::DeclContext::hasExternalVisibleStorage().
FindFileRegionDecls()
void ASTReader::FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > & Decls) override virtual
Get the decls that are contained in a file in the Offset/Length range.
Length can be 0 to indicate a point at Offset instead of a range.
Reimplemented from clang::ExternalASTSource.
Definition at line 7574 of file ASTReader.cpp.
References clang::File, clang::SourceLocation::getLocWithOffset(), Offset, and SM.
findPreprocessedEntitiesInRange()
std::pair< unsigned, unsigned > ASTReader::findPreprocessedEntitiesInRange (SourceRange Range) override virtual
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that Range encompasses.
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that.
Range encompasses.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 6159 of file ASTReader.cpp.
FinishedDeserializing()
void ASTReader::FinishedDeserializing () override virtual
Notify ASTReader that we finished the deserialization of a decl or type.
Must be paired with StartedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 11554 of file ASTReader.cpp.
References clang::ASTContext::adjustDeducedFunctionResultType(), clang::ASTContext::adjustExceptionSpec(), clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, getContext(), and clang::FunctionProtoType::getExtProtoInfo().
forEachImportedKeyDecl()
template<typename Fn > void clang::ASTReader::forEachImportedKeyDecl (const Decl * D, Fn Visit) inline
Run a callback on each imported key declaration of D.
Definition at line 1268 of file ASTReader.h.
References clang::Decl::getCanonicalDecl(), GetExistingDecl(), and clang::Decl::isFromASTFile().
ForgetSema()
void clang::ASTReader::ForgetSema () inline override virtual
Inform the semantic consumer that Sema is no longer available.
Reimplemented from clang::ExternalSemaSource.
Definition at line 1966 of file ASTReader.h.
get()
IdentifierInfo * ASTReader::get (StringRef Name) override virtual
Retrieve the IdentifierInfo for the named identifier.
This routine builds a new IdentifierInfo for the given identifier. If any declarations with this name are visible from translation unit scope, their declarations will be deserialized and introduced into the declaration chain of the identifier.
Implements clang::IdentifierInfoLookup.
Definition at line 7982 of file ASTReader.cpp.
getContext()
ASTContext & clang::ASTReader::getContext () inline
Retrieve the AST context that this AST reader supplements.
Definition at line 2248 of file ASTReader.h.
Referenced by clang::ASTDeclReader::attachPreviousDecl(), FinishedDeserializing(), clang::ASTRecordReader::getContext(), clang::index::indexModuleFile(), clang::ASTDeclReader::mergeInheritableAttributes(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::mergeMergeable(), clang::ASTDeclReader::mergeRedeclarable(), ReadComments(), ReadCXXTemporary(), clang::ASTDeclReader::ReadFunctionDefinition(), clang::ASTDeclReader::ReadObjCTypeParamList(), clang::ASTDeclReader::UpdateDecl(), clang::ASTDeclReader::VisitBlockDecl(), clang::ASTDeclReader::VisitClassTemplateDecl(), clang::ASTDeclReader::VisitClassTemplateSpecializationDeclImpl(), clang::ASTDeclReader::VisitCXXMethodDecl(), clang::ASTDeclReader::VisitCXXRecordDeclImpl(), clang::ASTDeclReader::VisitDecl(), clang::ASTDeclReader::VisitDeclaratorDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTDeclReader::VisitFieldDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclReader::VisitIndirectFieldDecl(), clang::ASTDeclReader::VisitMSGuidDecl(), clang::ASTDeclReader::VisitObjCCategoryDecl(), clang::ASTDeclReader::VisitObjCMethodDecl(), clang::ASTDeclReader::VisitRedeclarableTemplateDecl(), clang::ASTDeclReader::VisitTagDecl(), clang::ASTDeclReader::VisitTemplateParamObjectDecl(), clang::ASTDeclReader::VisitTemplateTemplateParmDecl(), clang::ASTDeclReader::VisitUsingDecl(), clang::ASTDeclReader::VisitUsingShadowDecl(), clang::ASTDeclReader::VisitVarDeclImpl(), and clang::ASTDeclReader::VisitVarTemplateSpecializationDeclImpl().
GetDecl()
Decl * ASTReader::GetDecl (serialization::DeclID ID)
Resolve a declaration ID into a declaration, potentially building a new declaration.
Definition at line 7428 of file ASTReader.cpp.
References clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by GetLocalDecl(), clang::ASTReader::ModuleDeclIterator::operator*(), ReadDecl(), ReadDeclAs(), ReadDeclsToCheckForDeferredDiags(), ReadDelegatingConstructors(), ReadExtVectorDecls(), ReadKnownNamespaces(), ReadMismatchingDeleteExpressions(), ReadPendingInstantiations(), ReadTentativeDefinitions(), ReadUndefinedButUsed(), ReadUnusedFileScopedDecls(), ReadUnusedLocalTypedefNameCandidates(), ReadUsedVTables(), SetGloballyVisibleDecls(), clang::ASTDeclReader::Visit(), clang::ASTDeclReader::VisitNamespaceDecl(), clang::ASTDeclReader::VisitRedeclarable(), and clang::ASTDeclReader::VisitTemplateDecl().
getDeserializationListener()
ASTDeserializationListener * clang::ASTReader::getDeserializationListener () inline
Get the AST deserialization listener.
Definition at line 1640 of file ASTReader.h.
getDiags()
DiagnosticsEngine & clang::ASTReader::getDiags () const inline
Definition at line 1520 of file ASTReader.h.
GetExistingDecl()
Decl * ASTReader::GetExistingDecl (serialization::DeclID ID)
Resolve a declaration ID into a declaration.
Return 0 if it's not been loaded yet.
Definition at line 7403 of file ASTReader.cpp.
References clang::Decl::getCanonicalDecl(), getPredefinedDecl(), and clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by forEachImportedKeyDecl(), and getKeyDeclaration().
GetExternalCXXBaseSpecifiers()
CXXBaseSpecifier * ASTReader::GetExternalCXXBaseSpecifiers (uint64_t Offset) override virtual
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 7251 of file ASTReader.cpp.
References clang::ASTContext::Allocate(), clang::serialization::DECL_CXX_BASE_SPECIFIERS, clang::serialization::ModuleFile::DeclsCursor, and Offset.
GetExternalCXXCtorInitializers()
CXXCtorInitializer ** ASTReader::GetExternalCXXCtorInitializers (uint64_t Offset) override virtual
Read the contents of a CXXCtorInitializer array.
Reimplemented from clang::ExternalASTSource.
Definition at line 7220 of file ASTReader.cpp.
References clang::serialization::DECL_CXX_CTOR_INITIALIZERS, clang::serialization::ModuleFile::DeclsCursor, and Offset.
GetExternalDecl()
Decl * ASTReader::GetExternalDecl (uint32_t ID) override virtual
Resolve a declaration ID into a declaration, potentially building a new declaration.
This method only needs to be implemented if the AST source ever passes back decl sets as VisibleDeclaration objects.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 7163 of file ASTReader.cpp.
GetExternalDeclStmt()
Stmt * ASTReader::GetExternalDeclStmt (uint64_t Offset) override virtual
Resolve the offset of a statement into a statement.
This operation will read a new statement from the external source each time it is called, and is meant to be used via a LazyOffsetPtr (which is used by Decls for the body of functions, etc).
Reimplemented from clang::ExternalASTSource.
Definition at line 7482 of file ASTReader.cpp.
References clang::serialization::ModuleFile::DeclsCursor, and Offset.
GetExternalSelector()
Selector ASTReader::GetExternalSelector (serialization::SelectorID ID) override virtual
Resolve a selector ID into a selector.
This operation only needs to be implemented if the AST source returns non-zero for GetNumKnownSelectors().
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 8713 of file ASTReader.cpp.
References DecodeSelector().
getFileManager()
FileManager & clang::ASTReader::getFileManager () const inline
Definition at line 1519 of file ASTReader.h.
getGlobalDeclID()
serialization::DeclID ASTReader::getGlobalDeclID (ModuleFile & F, serialization::LocalDeclID LocalID) const
Map from a local declaration ID within a given module to a global declaration ID.
Definition at line 7293 of file ASTReader.cpp.
References clang::serialization::ModuleFile::DeclRemap, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by GetLocalDecl(), and clang::ASTReader::ModuleDeclIterator::operator*().
getGlobalIdentifierID()
IdentifierID ASTReader::getGlobalIdentifierID (ModuleFile & M, unsigned LocalID)
Definition at line 8539 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::IdentifierRemap, clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_IDENT_IDS.
Referenced by getLocalIdentifier(), and readIdentifier().
getGlobalIndex()
GlobalModuleIndex * clang::ASTReader::getGlobalIndex () inline
Return global module index.
Definition at line 1648 of file ASTReader.h.
getGlobalMacroID()
MacroID ASTReader::getGlobalMacroID (ModuleFile & M, unsigned LocalID)
Retrieve the global macro ID corresponding to the given local ID within the given module file.
Definition at line 8581 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::MacroRemap, clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_MACRO_IDS.
getGlobalPreprocessedEntityID()
PreprocessedEntityID ASTReader::getGlobalPreprocessedEntityID (ModuleFile & M, unsigned LocalID) const
Determine the global preprocessed entity ID that corresponds to the given local ID within the given module.
Definition at line 1795 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_PP_ENTITY_IDS, and clang::serialization::ModuleFile::PreprocessedEntityRemap.
getGlobalSelectorID()
serialization::SelectorID ASTReader::getGlobalSelectorID (ModuleFile & F, unsigned LocalID) const
Retrieve the global selector ID that corresponds to this the local selector ID in a given module.
Definition at line 8723 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_SELECTOR_IDS, and clang::serialization::ModuleFile::SelectorRemap.
Referenced by getLocalSelector().
getGlobalSubmoduleID()
serialization::SubmoduleID ASTReader::getGlobalSubmoduleID (ModuleFile & M, unsigned LocalID)
Retrieve the global submodule ID given a module and its local ID number.
Definition at line 8596 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_SUBMODULE_IDS, and clang::serialization::ModuleFile::SubmoduleRemap.
Referenced by clang::ASTRecordReader::getGlobalSubmoduleID(), and getLocalModuleFile().
getGlobalTypeID()
serialization::TypeID ASTReader::getGlobalTypeID (ModuleFile & F, unsigned LocalID) const
Map a local type ID within a given AST file into a global type ID.
Definition at line 7092 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::Qualifiers::FastMask, clang::Qualifiers::FastWidth, clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_TYPE_IDS, and clang::serialization::ModuleFile::TypeRemap.
Referenced by clang::ASTRecordReader::getGlobalTypeID().
GetHeaderFileInfo()
HeaderFileInfo ASTReader::GetHeaderFileInfo (const FileEntry * FE) override virtual
Read the header file information for the given file entry.
Implements clang::ExternalHeaderFileInfoSource.
Definition at line 6222 of file ASTReader.cpp.
GetIdentifier()
IdentifierInfo * clang::ASTReader::GetIdentifier (serialization::IdentifierID ID) inline override
Definition at line 2054 of file ASTReader.h.
References DecodeIdentifierInfo().
getIdentifiers()
IdentifierIterator * ASTReader::getIdentifiers () override virtual
Retrieve an iterator into the set of all identifiers in all loaded AST files.
Reimplemented from clang::IdentifierInfoLookup.
Definition at line 8107 of file ASTReader.cpp.
References ASTIdentifierIterator, and loadGlobalIndex().
getIdentifierTable()
IdentifierTable & ASTReader::getIdentifierTable ()
Retrieve the identifier table associated with the preprocessor.
Definition at line 9038 of file ASTReader.cpp.
References clang::Preprocessor::getIdentifierTable().
getIdResolver()
IdentifierResolver & ASTReader::getIdResolver ()
Get the identifier resolver used for name lookup / updates in the translation unit scope.
We have one of these even if we don't have a Sema object.
Definition at line 11676 of file ASTReader.cpp.
References clang::Sema::IdResolver.
getKeyDeclaration() [1/2]
const Decl * clang::ASTReader::getKeyDeclaration (const Decl * D) inline
Definition at line 1262 of file ASTReader.h.
References getKeyDeclaration().
getKeyDeclaration() [2/2]
Decl * clang::ASTReader::getKeyDeclaration (Decl * D) inline
Returns the first key declaration for the given declaration.
This is one that is formerly-canonical (or still canonical) and whose module did not import any other key declaration of the entity.
Definition at line 1252 of file ASTReader.h.
References clang::Decl::getCanonicalDecl(), GetExistingDecl(), and clang::Decl::isFromASTFile().
Referenced by getKeyDeclaration().
getLoadedLookupTables()
const serialization::reader::DeclContextLookupTable * ASTReader::getLoadedLookupTables (DeclContext * Primary) const
Get the loaded lookup tables for Primary, if any.
Definition at line 7666 of file ASTReader.cpp.
GetLocalDecl()
Decl * clang::ASTReader::GetLocalDecl (ModuleFile & F, uint32_t LocalID) inline
Reads a declaration with the given local ID in the given module.
Definition at line 1840 of file ASTReader.h.
References GetDecl(), and getGlobalDeclID().
Referenced by GetLocalDeclAs(), clang::ASTRecordReader::GetLocalDeclAs(), and ReadLateParsedTemplates().
GetLocalDeclAs()
template<typename T > T * clang::ASTReader::GetLocalDeclAs (ModuleFile & F, uint32_t LocalID) inline
Reads a declaration with the given local ID in the given module.
Returns
The requested declaration, casted to the given return type.
Definition at line 1848 of file ASTReader.h.
References GetLocalDecl().
getLocalIdentifier()
IdentifierInfo * ASTReader::getLocalIdentifier (ModuleFile & M, unsigned LocalID)
Definition at line 8535 of file ASTReader.cpp.
References DecodeIdentifierInfo(), and getGlobalIdentifierID().
getLocalModuleFile()
ModuleFile * ASTReader::getLocalModuleFile (ModuleFile & M, unsigned ID)
Retrieve the module file with a given local ID within the specified ModuleFile.
Definition at line 8629 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), getGlobalSubmoduleID(), getModuleManager(), and clang::serialization::ModuleManager::pch_modules().
getLocalSelector()
Selector ASTReader::getLocalSelector (ModuleFile & M, unsigned LocalID)
Retrieve a selector from the given module with its local ID number.
Definition at line 8684 of file ASTReader.cpp.
References DecodeSelector(), and getGlobalSelectorID().
Referenced by ReadSelector().
getLocalType()
QualType ASTReader::getLocalType (ModuleFile & F, unsigned LocalID)
Resolve a local type ID within a given AST file into a type.
Definition at line 7087 of file ASTReader.cpp.
Referenced by readType().
getMacro()
MacroInfo * ASTReader::getMacro (serialization::MacroID ID)
Retrieve the macro with the given ID.
Definition at line 8554 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseMacroID, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::Error, clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::MacroOffsets, clang::serialization::ModuleFile::MacroOffsetsBase, clang::ASTDeserializationListener::MacroRead(), clang::serialization::NUM_PREDEF_MACRO_IDS, and ReadMacroRecord().
getMemoryBufferSizes()
void ASTReader::getMemoryBufferSizes (MemoryBufferSizes & sizes) const override virtual
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Reimplemented from clang::ExternalASTSource.
Definition at line 7834 of file ASTReader.cpp.
References bytes(), clang::ExternalASTSource::MemoryBufferSizes::malloc_bytes, and clang::ExternalASTSource::MemoryBufferSizes::mmap_bytes.
getModule()
Module * ASTReader::getModule (unsigned ID) override virtual
Retrieve the module that corresponds to the given module ID.
Note: overrides method in ExternalASTSource
Implements clang::ExternalPreprocessorSource.
Definition at line 8625 of file ASTReader.cpp.
References getSubmodule().
getModuleFileID()
unsigned ASTReader::getModuleFileID (ModuleFile * M)
Get an ID for the given module file.
Definition at line 8642 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseSubmoduleID, getModuleManager(), clang::serialization::ModuleFile::isModule(), clang::serialization::NUM_PREDEF_SUBMODULE_IDS, and clang::serialization::ModuleManager::pch_modules().
getModuleFileLevelDecls()
llvm::iterator_range< ASTReader::ModuleDeclIterator > ASTReader::getModuleFileLevelDecls (ModuleFile & Mod)
Definition at line 5931 of file ASTReader.cpp.
References clang::serialization::ModuleFile::FileSortedDecls, and clang::serialization::ModuleFile::NumFileSortedDecls.
Referenced by clang::index::indexModuleFile().
getModuleImportLoc()
std::pair< SourceLocation, StringRef > ASTReader::getModuleImportLoc (int ID) override virtual
Retrieve the module import location and module name for the given source manager entry ID.
Implements clang::ExternalSLocEntrySource.
Definition at line 1582 of file ASTReader.cpp.
References clang::Error, clang::serialization::ModuleFile::ImportLoc, clang::serialization::ModuleFile::isModule(), and clang::serialization::ModuleFile::ModuleName.
getModuleManager()
ModuleManager & clang::ASTReader::getModuleManager () inline
Retrieve the module manager.
Definition at line 1682 of file ASTReader.h.
Referenced by clang::FrontendAction::BeginSourceFile(), getLocalModuleFile(), getModuleFileID(), and clang::PCHValidator::ReadDiagnosticOptions().
GetNumExternalSelectors()
uint32_t ASTReader::GetNumExternalSelectors () override virtual
Returns the number of selectors known to the external AST source.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 8717 of file ASTReader.cpp.
References getTotalNumSelectors().
getOriginalSourceFile() [1/2]
StringRef clang::ASTReader::getOriginalSourceFile () inline
Retrieve the name of the original source file name for the primary module file.
Definition at line 1689 of file ASTReader.h.
References clang::serialization::ModuleManager::getPrimaryModule(), and clang::serialization::ModuleFile::OriginalSourceFileName.
Referenced by AddImplicitIncludePCH(), and createInvocationForMigration().
getOriginalSourceFile() [2/2]
std::string ASTReader::getOriginalSourceFile (const std::string & ASTFileName, FileManager & FileMgr, const PCHContainerReader & PCHContainerRdr, DiagnosticsEngine & Diags) static
Retrieve the name of the original source file name directly from the AST file, without actually loading the AST file.
Definition at line 5057 of file ASTReader.cpp.
References clang::serialization::CONTROL_BLOCK_ID, doesntStartWithASTFileMagic(), clang::PCHContainerReader::ExtractPCH(), clang::FileManager::getBufferForFile(), clang::serialization::ORIGINAL_FILE, clang::DiagnosticsEngine::Report(), and SkipCursorToBlock().
getOwningModuleFile()
ModuleFile * ASTReader::getOwningModuleFile (const Decl * D)
Retrieve the module file that owns the given declaration, or NULL if the declaration is not from a module file.
Definition at line 7317 of file ASTReader.cpp.
References clang::Decl::getGlobalID(), and clang::Decl::isFromASTFile().
Referenced by clang::ASTDeclWriter::AddFirstDeclFromEachModule(), getOwningModuleNameForDiagnostic(), and ReadLateParsedTemplates().
getOwningModuleNameForDiagnostic()
std::string ASTReader::getOwningModuleNameForDiagnostic (const Decl * D)
Get the best name we know for the module that owns the given declaration, or an empty string if the declaration is not from a module.
Definition at line 9160 of file ASTReader.cpp.
References clang::Decl::getImportedOwningModule(), getOwningModuleFile(), and clang::serialization::ModuleFile::ModuleName.
getPreprocessor()
Preprocessor & clang::ASTReader::getPreprocessor () const inline
Retrieve the preprocessor.
Definition at line 1685 of file ASTReader.h.
Referenced by clang::index::indexModuleFile(), isInterestingIdentifier(), and markIdentifierFromAST().
getSema()
Sema * clang::ASTReader::getSema () inline
Retrieve the semantic analysis object used to analyze the translation unit in which the precompiled header is being imported.
Definition at line 2260 of file ASTReader.h.
Referenced by ReadMethodPool().
getSourceDescriptor()
llvm::Optional< ASTSourceDescriptor > ASTReader::getSourceDescriptor (unsigned ID) override virtual
Return a descriptor for the corresponding module.
Reimplemented from clang::ExternalASTSource.
Definition at line 8660 of file ASTReader.cpp.
References clang::serialization::ModuleFile::FileName, clang::serialization::ModuleManager::getPrimaryModule(), getSubmodule(), clang::None, clang::serialization::ModuleFile::OriginalDir, clang::serialization::ModuleFile::OriginalSourceFileName, clang::serialization::ModuleManager::pch_modules(), and clang::serialization::ModuleFile::Signature.
getSourceLocationForDeclID()
SourceLocation ASTReader::getSourceLocationForDeclID (serialization::GlobalDeclID ID)
Returns the source location for the decl ID.
Definition at line 7325 of file ASTReader.cpp.
References clang::serialization::NUM_PREDEF_DECL_IDS.
getSourceManager()
SourceManager & clang::ASTReader::getSourceManager () const inline
Definition at line 1518 of file ASTReader.h.
getSubmodule()
Module * ASTReader::getSubmodule (serialization::SubmoduleID GlobalID)
Retrieve the submodule that corresponds to a global submodule ID.
Definition at line 8611 of file ASTReader.cpp.
References clang::Error, and clang::serialization::NUM_PREDEF_SUBMODULE_IDS.
Referenced by getModule(), getSourceDescriptor(), clang::ASTRecordReader::getSubmodule(), clang::ASTDeclReader::UpdateDecl(), and clang::ASTDeclReader::VisitDecl().
getSuggestedPredefines()
const std::string & clang::ASTReader::getSuggestedPredefines () inline
Returns the suggested contents of the predefines buffer, which contains a (typically-empty) subset of the predefines build prior to including the precompiled header.
Definition at line 1722 of file ASTReader.h.
getSwitchCaseWithID()
SwitchCase * ASTReader::getSwitchCaseWithID (unsigned ID)
Retrieve the switch-case statement with the given ID.
Definition at line 9051 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::getSwitchCaseWithID().
getTotalNumDecls()
unsigned clang::ASTReader::getTotalNumDecls () const inline
Returns the number of declarations found in the chain.
Definition at line 1769 of file ASTReader.h.
getTotalNumIdentifiers()
unsigned clang::ASTReader::getTotalNumIdentifiers () const inline
Returns the number of identifiers found in the chain.
Definition at line 1754 of file ASTReader.h.
getTotalNumMacros()
unsigned clang::ASTReader::getTotalNumMacros () const inline
Returns the number of macros found in the chain.
Definition at line 1759 of file ASTReader.h.
getTotalNumPreprocessedEntities()
unsigned clang::ASTReader::getTotalNumPreprocessedEntities () const inline
Returns the number of preprocessed entities known to the AST reader.
Definition at line 1785 of file ASTReader.h.
References clang::Result.
getTotalNumSelectors()
unsigned clang::ASTReader::getTotalNumSelectors () const inline
Returns the number of selectors found in the chain.
Definition at line 1779 of file ASTReader.h.
Referenced by GetNumExternalSelectors().
getTotalNumSLocs()
unsigned clang::ASTReader::getTotalNumSLocs () const inline
Returns the number of source locations found in the chain.
Definition at line 1749 of file ASTReader.h.
getTotalNumSubmodules()
unsigned clang::ASTReader::getTotalNumSubmodules () const inline
Returns the number of submodules known.
Definition at line 1774 of file ASTReader.h.
getTotalNumTypes()
unsigned clang::ASTReader::getTotalNumTypes () const inline
Returns the number of types found in the chain.
Definition at line 1764 of file ASTReader.h.
GetType()
QualType ASTReader::GetType (serialization::TypeID ID)
Resolve a type ID into a type, potentially building a new type.
Definition at line 6815 of file ASTReader.cpp.
References clang::ASTContext::AccumTy, clang::ASTContext::ARCUnbridgedCastTy, clang::ASTContext::BFloat16Ty, clang::ASTContext::BoolTy, clang::ASTContext::BoundMemberTy, clang::ASTContext::BuiltinFnTy, clang::ASTContext::Char16Ty, clang::ASTContext::Char32Ty, clang::ASTContext::Char8Ty, clang::ASTContext::CharTy, clang::ASTContext::DependentTy, clang::ASTContext::DoubleTy, clang::Qualifiers::FastMask, clang::Qualifiers::FastWidth, clang::ASTContext::Float128Ty, clang::ASTContext::Float16Ty, clang::ASTContext::FloatTy, clang::ASTContext::FractTy, clang::serialization::TypeIdx::fromTypeID(), clang::ASTContext::getAutoDeductType(), clang::ASTContext::getAutoRRefDeductType(), clang::ASTContext::HalfTy, clang::ASTContext::IncompleteMatrixIdxTy, clang::ASTContext::Int128Ty, clang::ASTContext::IntTy, clang::ASTContext::LongAccumTy, clang::ASTContext::LongDoubleTy, clang::ASTContext::LongFractTy, clang::ASTContext::LongLongTy, clang::ASTContext::LongTy, clang::ASTContext::NullPtrTy, clang::serialization::NUM_PREDEF_TYPE_IDS, clang::ASTContext::ObjCBuiltinClassTy, clang::ASTContext::ObjCBuiltinIdTy, clang::ASTContext::ObjCBuiltinSelTy, clang::ASTContext::OCLClkEventTy, clang::ASTContext::OCLEventTy, clang::ASTContext::OCLQueueTy, clang::ASTContext::OCLReserveIDTy, clang::ASTContext::OCLSamplerTy, clang::ASTContext::OMPArraySectionTy, clang::ASTContext::OMPIteratorTy, clang::ASTContext::OverloadTy, clang::serialization::PREDEF_TYPE_ACCUM_ID, clang::serialization::PREDEF_TYPE_ARC_UNBRIDGED_CAST, clang::serialization::PREDEF_TYPE_AUTO_DEDUCT, clang::serialization::PREDEF_TYPE_AUTO_RREF_DEDUCT, clang::serialization::PREDEF_TYPE_BFLOAT16_ID, clang::serialization::PREDEF_TYPE_BOOL_ID, clang::serialization::PREDEF_TYPE_BOUND_MEMBER, clang::serialization::PREDEF_TYPE_BUILTIN_FN, clang::serialization::PREDEF_TYPE_CHAR16_ID, clang::serialization::PREDEF_TYPE_CHAR32_ID, clang::serialization::PREDEF_TYPE_CHAR8_ID, clang::serialization::PREDEF_TYPE_CHAR_S_ID, clang::serialization::PREDEF_TYPE_CHAR_U_ID, clang::serialization::PREDEF_TYPE_CLK_EVENT_ID, clang::serialization::PREDEF_TYPE_DEPENDENT_ID, clang::serialization::PREDEF_TYPE_DOUBLE_ID, clang::serialization::PREDEF_TYPE_EVENT_ID, clang::serialization::PREDEF_TYPE_FLOAT128_ID, clang::serialization::PREDEF_TYPE_FLOAT16_ID, clang::serialization::PREDEF_TYPE_FLOAT_ID, clang::serialization::PREDEF_TYPE_FRACT_ID, clang::serialization::PREDEF_TYPE_HALF_ID, clang::serialization::PREDEF_TYPE_INCOMPLETE_MATRIX_IDX, clang::serialization::PREDEF_TYPE_INT128_ID, clang::serialization::PREDEF_TYPE_INT_ID, clang::serialization::PREDEF_TYPE_LONG_ACCUM_ID, clang::serialization::PREDEF_TYPE_LONG_FRACT_ID, clang::serialization::PREDEF_TYPE_LONG_ID, clang::serialization::PREDEF_TYPE_LONGDOUBLE_ID, clang::serialization::PREDEF_TYPE_LONGLONG_ID, clang::serialization::PREDEF_TYPE_NULL_ID, clang::serialization::PREDEF_TYPE_NULLPTR_ID, clang::serialization::PREDEF_TYPE_OBJC_CLASS, clang::serialization::PREDEF_TYPE_OBJC_ID, clang::serialization::PREDEF_TYPE_OBJC_SEL, clang::serialization::PREDEF_TYPE_OMP_ARRAY_SECTION, clang::serialization::PREDEF_TYPE_OMP_ARRAY_SHAPING, clang::serialization::PREDEF_TYPE_OMP_ITERATOR, clang::serialization::PREDEF_TYPE_OVERLOAD_ID, clang::serialization::PREDEF_TYPE_PSEUDO_OBJECT, clang::serialization::PREDEF_TYPE_QUEUE_ID, clang::serialization::PREDEF_TYPE_RESERVE_ID_ID, clang::serialization::PREDEF_TYPE_SAMPLER_ID, clang::serialization::PREDEF_TYPE_SAT_ACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_FRACT_ID, clang::serialization::PREDEF_TYPE_SAT_LONG_ACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_LONG_FRACT_ID, clang::serialization::PREDEF_TYPE_SAT_SHORT_ACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_SHORT_FRACT_ID, clang::serialization::PREDEF_TYPE_SAT_UACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_UFRACT_ID, clang::serialization::PREDEF_TYPE_SAT_ULONG_ACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_ULONG_FRACT_ID, clang::serialization::PREDEF_TYPE_SAT_USHORT_ACCUM_ID, clang::serialization::PREDEF_TYPE_SAT_USHORT_FRACT_ID, clang::serialization::PREDEF_TYPE_SCHAR_ID, clang::serialization::PREDEF_TYPE_SHORT_ACCUM_ID, clang::serialization::PREDEF_TYPE_SHORT_FRACT_ID, clang::serialization::PREDEF_TYPE_SHORT_ID, clang::serialization::PREDEF_TYPE_UACCUM_ID, clang::serialization::PREDEF_TYPE_UCHAR_ID, clang::serialization::PREDEF_TYPE_UFRACT_ID, clang::serialization::PREDEF_TYPE_UINT128_ID, clang::serialization::PREDEF_TYPE_UINT_ID, clang::serialization::PREDEF_TYPE_ULONG_ACCUM_ID, clang::serialization::PREDEF_TYPE_ULONG_FRACT_ID, clang::serialization::PREDEF_TYPE_ULONG_ID, clang::serialization::PREDEF_TYPE_ULONGLONG_ID, clang::serialization::PREDEF_TYPE_UNKNOWN_ANY, clang::serialization::PREDEF_TYPE_USHORT_ACCUM_ID, clang::serialization::PREDEF_TYPE_USHORT_FRACT_ID, clang::serialization::PREDEF_TYPE_USHORT_ID, clang::serialization::PREDEF_TYPE_VOID_ID, clang::serialization::PREDEF_TYPE_WCHAR_ID, clang::ASTContext::PseudoObjectTy, clang::ASTContext::SatAccumTy, clang::ASTContext::SatFractTy, clang::ASTContext::SatLongAccumTy, clang::ASTContext::SatLongFractTy, clang::ASTContext::SatShortAccumTy, clang::ASTContext::SatShortFractTy, clang::ASTContext::SatUnsignedAccumTy, clang::ASTContext::SatUnsignedFractTy, clang::ASTContext::SatUnsignedLongAccumTy, clang::ASTContext::SatUnsignedLongFractTy, clang::ASTContext::SatUnsignedShortAccumTy, clang::ASTContext::SatUnsignedShortFractTy, clang::ASTContext::ShortAccumTy, clang::ASTContext::ShortFractTy, clang::ASTContext::ShortTy, clang::ASTContext::SignedCharTy, clang::ASTContext::UnknownAnyTy, clang::ASTContext::UnsignedAccumTy, clang::ASTContext::UnsignedCharTy, clang::ASTContext::UnsignedFractTy, clang::ASTContext::UnsignedInt128Ty, clang::ASTContext::UnsignedIntTy, clang::ASTContext::UnsignedLongAccumTy, clang::ASTContext::UnsignedLongFractTy, clang::ASTContext::UnsignedLongLongTy, clang::ASTContext::UnsignedLongTy, clang::ASTContext::UnsignedShortAccumTy, clang::ASTContext::UnsignedShortFractTy, clang::ASTContext::UnsignedShortTy, clang::ASTContext::VoidTy, and clang::ASTContext::WCharTy.
Referenced by clang::ASTDeclReader::Visit(), and clang::ASTDeclReader::VisitFunctionDecl().
hasExternalDefinitions()
ExternalASTSource::ExtKind ASTReader::hasExternalDefinitions (const Decl * D) override virtual
Reimplemented from clang::ExternalASTSource.
Definition at line 8677 of file ASTReader.cpp.
References clang::ExternalASTSource::EK_Always, clang::ExternalASTSource::EK_Never, and clang::ExternalASTSource::EK_ReplyHazy.
hasGlobalIndex()
bool clang::ASTReader::hasGlobalIndex () const inline
Determine whether this AST reader has a global index.
Definition at line 1645 of file ASTReader.h.
InitializeContext()
void ASTReader::InitializeContext ()
Initializes the ASTContext.
Definition at line 4868 of file ASTReader.cpp.
References clang::Module::AllVisible, clang::Error, clang::File, clang::Type::getAs(), clang::ASTContext::getDiagnostics(), clang::ASTContext::getTranslationUnitDecl(), clang::QualType::isNull(), clang::serialization::NumSpecialTypeIDs, clang::serialization::PREDEF_DECL_TRANSLATION_UNIT_ID, clang::ASTContext::setCFConstantStringType(), clang::ASTContext::setcudaConfigureCallDecl(), clang::ASTContext::setFILEDecl(), clang::ASTContext::setjmp_bufDecl(), clang::ASTContext::setsigjmp_bufDecl(), clang::ASTContext::setucontext_tDecl(), clang::serialization::SPECIAL_TYPE_CF_CONSTANT_STRING, clang::serialization::SPECIAL_TYPE_FILE, clang::serialization::SPECIAL_TYPE_JMP_BUF, clang::serialization::SPECIAL_TYPE_OBJC_CLASS_REDEFINITION, clang::serialization::SPECIAL_TYPE_OBJC_ID_REDEFINITION, clang::serialization::SPECIAL_TYPE_OBJC_SEL_REDEFINITION, clang::serialization::SPECIAL_TYPE_SIGJMP_BUF, and clang::serialization::SPECIAL_TYPE_UCONTEXT_T.
InitializeSema()
void ASTReader::InitializeSema (Sema & S) override virtual
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
Reimplemented from clang::ExternalSemaSource.
Definition at line 7850 of file ASTReader.cpp.
References clang::Sema::addExternalSource(), clang::FPOptionsOverride::applyOverrides(), clang::cast(), clang::NamedDecl::getDeclName(), and clang::FPOptionsOverride::getFromOpaqueInt().
isAcceptableASTFile()
bool ASTReader::isAcceptableASTFile (StringRef Filename, FileManager & FileMgr, const PCHContainerReader & PCHContainerRdr, const LangOptions & LangOpts, const TargetOptions & TargetOpts, const PreprocessorOptions & PPOpts, StringRef ExistingModuleCachePath) static
Determine whether the given AST file is acceptable to load into a translation unit with the given language and target options.
Definition at line 5431 of file ASTReader.cpp.
References Filename.
Referenced by clang::FrontendAction::BeginSourceFile().
isDeclIDFromModule()
bool ASTReader::isDeclIDFromModule (serialization::GlobalDeclID ID, ModuleFile & M) const
Returns true if global DeclID ID originated from module M.
Definition at line 7307 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDeclID, clang::serialization::ModuleFile::LocalNumDecls, and clang::serialization::NUM_PREDEF_DECL_IDS.
isGlobalIndexUnavailable()
bool ASTReader::isGlobalIndexUnavailable () const
Determine whether we tried to load the global index, but failed, e.g., because it is out-of-date or does not exist.
Definition at line 4148 of file ASTReader.cpp.
isPreprocessedEntityInFileID()
Optional< bool > ASTReader::isPreprocessedEntityInFileID (unsigned Index, FileID FID) override virtual
Optionally returns true or false if the preallocated preprocessed entity with index Index came from file FID.
Optionally returns true or false if the preallocated preprocessed entity with index.
Index came from file
FID.
Reimplemented from clang::ExternalPreprocessingRecordSource.
Definition at line 6172 of file ASTReader.cpp.
References clang::serialization::PPEntityOffset::getBegin(), clang::FileID::isInvalid(), clang::SourceLocation::isInvalid(), and clang::serialization::ModuleFile::PreprocessedEntityOffsets.
isProcessingUpdateRecords()
bool clang::ASTReader::isProcessingUpdateRecords () inline
Definition at line 2299 of file ASTReader.h.
loadGlobalIndex()
bool ASTReader::loadGlobalIndex ()
Attempts to load the global index.
Returns
true if loading the global index has failed for any reason.
Definition at line 4123 of file ASTReader.cpp.
References clang::GlobalModuleIndex::readIndex(), and clang::Result.
Referenced by getIdentifiers().
LoadSelector()
void ASTReader::LoadSelector (Selector Sel)
Load a selector from disk, registering its ID if it exists.
Definition at line 8438 of file ASTReader.cpp.
References ReadMethodPool().
Referenced by clang::ASTWriter::getSelectorRef().
makeModuleVisible()
void ASTReader::makeModuleVisible (Module * Mod, Module::NameVisibilityKind NameVisibility, SourceLocation ImportLoc)
Make the entities in the given module and any of its (non-explicit) submodules visible to name lookup.
Parameters
Mod The module whose names should be made visible.
NameVisibility The level of visibility to give the names in the module. Visibility can only be increased over time.
ImportLoc The location at which the import occurs.
Definition at line 4059 of file ASTReader.cpp.
References clang::Module::getExportedModules(), clang::Module::isUnimportable(), and clang::Module::NameVisibility.
makeNamesVisible()
void ASTReader::makeNamesVisible (const HiddenNames & Names, Module * Owner)
Make the names within this set of hidden names visible.
Definition at line 4045 of file ASTReader.cpp.
References clang::Module::Hidden, moveMethodToBackOfGlobalList(), and clang::Module::NameVisibility.
mapGlobalIDToModuleFileGlobalID()
DeclID ASTReader::mapGlobalIDToModuleFileGlobalID (ModuleFile & M, serialization::DeclID GlobalID)
Map a global declaration ID into the declaration ID used to refer to this declaration within the given module fule.
Returns
the global ID of the given declaration as known in the given module file.
Definition at line 7449 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDeclID, clang::serialization::ModuleFile::GlobalToLocalDeclIDs, and clang::serialization::NUM_PREDEF_DECL_IDS.
markIdentifierUpToDate()
void ASTReader::markIdentifierUpToDate (IdentifierInfo * II)
Note that this identifier is up-to-date.
Definition at line 2078 of file ASTReader.cpp.
References clang::IdentifierInfo::setOutOfDate().
mergeDefinitionVisibility()
void ASTReader::mergeDefinitionVisibility (NamedDecl * Def, NamedDecl * MergedDef)
Note that MergedDef is a redefinition of the canonical definition Def, so Def should be visible whenever MergedDef is.
We've merged the definition MergedDef into the existing definition Def.
Ensure that Def is made visible whenever MergedDef is made visible.
Definition at line 4108 of file ASTReader.cpp.
References clang::Decl::getImportedOwningModule(), clang::Decl::isUnconditionallyVisible(), and clang::Decl::setVisibleDespiteOwningModule().
Referenced by clang::ASTDeclReader::attachPreviousDeclImpl(), and clang::ASTDeclReader::VisitEnumDecl().
operator=()
ASTReader & clang::ASTReader::operator= (const ASTReader &) delete
PrintStats()
void ASTReader::PrintStats () override virtual
Print some statistics about AST usage.
Reimplemented from clang::ExternalASTSource.
Definition at line 7702 of file ASTReader.cpp.
References dump().
ReadAlignPackInfo()
Sema::AlignPackInfo clang::ASTReader::ReadAlignPackInfo (uint32_t Raw) const inline
Read a AlignPackInfo from raw form.
Definition at line 2130 of file ASTReader.h.
References clang::Sema::AlignPackInfo::getFromRawEncoding().
ReadAST()
ASTReader::ASTReadResult ASTReader::ReadAST (StringRef FileName, ModuleKind Type, SourceLocation ImportLoc, unsigned ClientLoadCapabilities, SmallVectorImpl< ImportedSubmodule > * Imported = nullptr)
Load the AST file designated by the given file name.
Parameters
FileName The name of the AST file to load.
Type The kind of AST being loaded, e.g., PCH, module, main file, or preamble.
ImportLoc the location where the module file will be considered as imported from. For non-module AST types it should be invalid.
ClientLoadCapabilities The set of client load-failure capabilities, represented as a bitset of the enumerators of LoadFailureCapabilities.
Imported optional out-parameter to append the list of modules that were imported by precompiled headers or any other non-module AST file
Definition at line 4213 of file ASTReader.cpp.
References clang::serialization::ModuleFile::DidReadTopLevelSubmodule, clang::serialization::ModuleFile::DirectImportLoc, clang::Error, clang::serialization::EXTENSION_BLOCK_ID, clang::serialization::ModuleFile::FileName, clang::serialization::ModuleFile::GlobalBitOffset, Id, clang::serialization::ModuleFile::IdentifierTableData, clang::serialization::ModuleFile::ImportLoc, int, clang::serialization::ModuleFile::isModule(), clang::FileID::isValid(), clang::serialization::ModuleFile::Kind, markIdentifierFromAST(), clang::Module::Conflict::Message, clang::serialization::MK_ExplicitModule, clang::serialization::MK_ImplicitModule, clang::serialization::MK_MainFile, clang::serialization::MK_Preamble, clang::serialization::MK_PrebuiltModule, N, Offset, clang::serialization::ModuleFile::OriginalSourceFileID, clang::Module::Conflict::Other, clang::serialization::ModuleFile::PreloadIdentifierOffsets, clang::serialization::ModuleFile::PreloadSLocEntries, clang::serialization::reader::ASTIdentifierLookupTrait::ReadIdentifierID(), clang::serialization::reader::ASTIdentifierLookupTraitBase::ReadKey(), clang::serialization::reader::ASTIdentifierLookupTraitBase::ReadKeyDataLength(), clang::Result, clang::serialization::ModuleFile::SizeInBits, SkipCursorToBlock(), clang::serialization::ModuleFile::SLocEntryBaseID, clang::serialization::ModuleFile::Stream, clang::Unresolved, and updateModuleTimestamp().
readASTFileControlBlock()
bool ASTReader::readASTFileControlBlock (StringRef Filename, FileManager & FileMgr, const PCHContainerReader & PCHContainerRdr, bool FindModuleFileExtensions, ASTReaderListener & Listener, bool ValidateDiagnosticOptions) static
Read the control block for the named AST file.
Returns
true if an error occurred, false otherwise.
Definition at line 5165 of file ASTReader.cpp.
References clang::serialization::CONTROL_BLOCK_ID, doesntStartWithASTFileMagic(), clang::serialization::EXTENSION_BLOCK_ID, clang::serialization::EXTENSION_METADATA, clang::PCHContainerReader::ExtractPCH(), Filename, clang::FileManager::getBufferForFile(), clang::serialization::IMPORTS, clang::serialization::INPUT_FILE, clang::serialization::INPUT_FILE_HASH, clang::serialization::INPUT_FILE_OFFSETS, clang::serialization::INPUT_FILES_BLOCK_ID, clang::serialization::METADATA, clang::serialization::MODULE_DIRECTORY, clang::serialization::MODULE_MAP_FILE, clang::serialization::MODULE_NAME, N, clang::ASTReaderListener::needsImportVisitation(), clang::ASTReaderListener::needsInputFileVisitation(), clang::ASTReaderListener::needsSystemInputFileVisitation(), clang::serialization::OPTIONS_BLOCK_ID, parseModuleFileExtensionMetadata(), clang::ASTReaderListener::ReadFullVersionInformation(), clang::ASTReaderListener::readModuleFileExtension(), clang::ASTReaderListener::ReadModuleMapFile(), clang::ASTReaderListener::ReadModuleName(), clang::ASTFileSignature::size, SkipCursorToBlock(), clang::serialization::VERSION_MAJOR, clang::ASTReaderListener::visitImport(), and clang::ASTReaderListener::visitInputFile().
Referenced by collectIncludePCH(), and clang::DumpModuleInfoAction::ExecuteAction().
ReadBlockAbbrevs()
bool ASTReader::ReadBlockAbbrevs (llvm::BitstreamCursor & Cursor, unsigned BlockID, uint64_t * StartOfBlockOffset = nullptr) static
ReadBlockAbbrevs - Enter a subblock of the specified BlockID with the specified cursor.
Enter a subblock of the specified BlockID with the specified cursor.
Read the abbreviations that are at the top of the block and then leave the cursor pointing into the block.
Definition at line 1619 of file ASTReader.cpp.
References Offset.
ReadComments()
void ASTReader::ReadComments () override virtual
Loads comments ranges.
Reimplemented from clang::ExternalASTSource.
Definition at line 9060 of file ASTReader.cpp.
References clang::C, clang::ASTContext::Comments, clang::serialization::COMMENTS_RAW_COMMENT, CommentsCursors, clang::Error, getContext(), clang::SourceLocation::isValid(), and ReadSourceRange().
ReadCXXTemporary()
CXXTemporary * ASTReader::ReadCXXTemporary (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Definition at line 9021 of file ASTReader.cpp.
References clang::CXXTemporary::Create(), getContext(), and ReadDeclAs().
Referenced by clang::ASTRecordReader::readCXXTemporary().
ReadDecl()
Decl * clang::ASTReader::ReadDecl (ModuleFile & F, const RecordData & R, unsigned & I) inline
Reads a declaration from the given position in a record in the given module.
Definition at line 1870 of file ASTReader.h.
References GetDecl(), and ReadDeclID().
Referenced by clang::ASTRecordReader::readDecl().
ReadDeclAs()
template<typename T > T * clang::ASTReader::ReadDeclAs (ModuleFile & F, const RecordData & R, unsigned & I) inline
Reads a declaration from the given position in a record in the given module.
Returns
The declaration read from this location, casted to the given result type.
Definition at line 1880 of file ASTReader.h.
References GetDecl(), and ReadDeclID().
Referenced by ReadCXXTemporary(), and clang::ASTRecordReader::readDeclAs().
ReadDeclID()
serialization::DeclID ASTReader::ReadDeclID (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Reads a declaration ID from the given position in a record in the given module.
Returns
The declaration ID read from the record, adjusted to a global ID.
Definition at line 7466 of file ASTReader.cpp.
Referenced by ReadDecl(), ReadDeclAs(), and clang::ASTRecordReader::readDeclID().
ReadDeclsToCheckForDeferredDiags()
void ASTReader::ReadDeclsToCheckForDeferredDiags (llvm::SmallVector< Decl *, 4 > & Decls) override virtual
Read the set of decls to be checked for deferred diags.
The external source should append its own potentially emitted function and variable decls which may cause deferred diags. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8336 of file ASTReader.cpp.
References GetDecl(), and N.
ReadDefinedMacros()
void ASTReader::ReadDefinedMacros () override virtual
Read the set of macros defined by this external macro source.
Implements clang::ExternalPreprocessorSource.
Definition at line 1935 of file ASTReader.cpp.
References clang::Error, clang::IdentifierInfo::isOutOfDate(), clang::serialization::PP_MACRO_FUNCTION_LIKE, clang::serialization::PP_MACRO_OBJECT_LIKE, and clang::serialization::PP_TOKEN.
ReadDelegatingConstructors()
void ASTReader::ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > & Decls) override virtual
Read the set of delegating constructors known to the external Sema source.
The external source should append its own delegating constructors to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8303 of file ASTReader.cpp.
References GetDecl(), and N.
ReadExpr()
Expr * ASTReader::ReadExpr (ModuleFile & F)
Reads an expression.
Definition at line 2595 of file ASTReaderStmt.cpp.
References ReadStmt().
Referenced by clang::ASTRecordReader::readExpr().
ReadExtVectorDecls()
void ASTReader::ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > & Decls) override virtual
Read the set of ext_vector type declarations known to the external Sema source.
The external source should append its own ext_vector type declarations to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8314 of file ASTReader.cpp.
References GetDecl(), and N.
readIdentifier()
IdentifierInfo * clang::ASTReader::readIdentifier (ModuleFile & M, const RecordData & Record, unsigned & Idx) inline
Definition at line 2049 of file ASTReader.h.
References DecodeIdentifierInfo(), and getGlobalIdentifierID().
Referenced by clang::ASTRecordReader::readIdentifier().
ReadKnownNamespaces()
void ASTReader::ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > & Namespaces) override virtual
Load the set of namespaces that are known to the external source, which will be used during typo correction.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8246 of file ASTReader.cpp.
References GetDecl(), and N.
ReadLateParsedTemplates()
void ASTReader::ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate > > & LPTMap) override virtual
Read the set of late parsed template functions for this source.
The external source should insert its own late parsed template functions into the map. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same map entries repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8411 of file ASTReader.cpp.
References clang::cast(), GetLocalDecl(), getOwningModuleFile(), LT, N, and ReadToken().
ReadMacroRecord()
MacroInfo * ASTReader::ReadMacroRecord (ModuleFile & F, uint64_t Offset)
Reads the macro record located at the given offset.
Definition at line 1670 of file ASTReader.cpp.
References clang::Error, clang::serialization::ModuleFile::MacroCursor, Offset, clang::serialization::PP_MACRO_DIRECTIVE_HISTORY, clang::serialization::PP_MACRO_FUNCTION_LIKE, clang::serialization::PP_MACRO_OBJECT_LIKE, clang::serialization::PP_MODULE_MACRO, clang::serialization::PP_TOKEN, clang::MacroInfo::setDefinitionEndLoc(), clang::MacroInfo::setHasCommaPasting(), clang::MacroInfo::setIsC99Varargs(), clang::MacroInfo::setIsFunctionLike(), clang::MacroInfo::setIsGNUVarargs(), clang::MacroInfo::setIsUsed(), clang::MacroInfo::setParameterList(), clang::MacroInfo::setUsedForHeaderGuard(), and Tok.
Referenced by getMacro().
ReadMethodPool()
void ASTReader::ReadMethodPool (Selector Sel) override virtual
Load the contents of the global method pool for a given selector.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8204 of file ASTReader.cpp.
References addMethodsToPool(), clang::serialization::ReadMethodPoolVisitor::factoryHasMoreThanOneDecl(), clang::serialization::ReadMethodPoolVisitor::getFactoryBits(), clang::serialization::ReadMethodPoolVisitor::getFactoryMethods(), clang::ExternalASTSource::getGeneration(), clang::serialization::ReadMethodPoolVisitor::getInstanceBits(), clang::serialization::ReadMethodPoolVisitor::getInstanceMethods(), getSema(), clang::serialization::ReadMethodPoolVisitor::instanceHasMoreThanOneDecl(), clang::Sema::MethodPool, and clang::serialization::ModuleManager::visit().
Referenced by LoadSelector(), and updateOutOfDateSelector().
ReadMismatchingDeleteExpressions()
void ASTReader::ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 > > & Exprs) override virtual
Reimplemented from clang::ExternalSemaSource.
Definition at line 8267 of file ASTReader.cpp.
References clang::C, clang::cast(), GetDecl(), clang::SourceLocation::getFromRawEncoding(), and N.
ReadPath() [1/2]
std::string ASTReader::ReadPath (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Definition at line 8994 of file ASTReader.cpp.
References Filename, ReadString(), and ResolveImportedPath().
Referenced by clang::ASTRecordReader::readPath().
ReadPath() [2/2]
std::string ASTReader::ReadPath (StringRef BaseDirectory, const RecordData & Record, unsigned & Idx)
Definition at line 9001 of file ASTReader.cpp.
References Filename, ReadString(), and ResolveImportedPath().
ReadPendingInstantiations()
void ASTReader::ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation > > & Pending) override virtual
Read the set of pending instantiations known to the external Sema source.
The external source should append its own pending instantiations to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same instantiations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8399 of file ASTReader.cpp.
References clang::cast(), GetDecl(), clang::SourceLocation::getFromRawEncoding(), and N.
ReadPragmaDiagnosticMappings()
void ASTReader::ReadPragmaDiagnosticMappings (DiagnosticsEngine & Diag)
Definition at line 6231 of file ASTReader.cpp.
References clang::DiagnosticMapping::deserialize(), Diag(), clang::SourceLocation::getLocWithOffset(), clang::DiagnosticMapping::isErrorOrFatal(), clang::serialization::ModuleFile::isModule(), clang::DiagnosticMapping::isPragma(), clang::FileID::isValid(), clang::serialization::ModuleFile::Kind, clang::serialization::MK_ImplicitModule, Offset, clang::serialization::ModuleFile::OriginalSourceFileID, clang::serialization::ModuleFile::PragmaDiagMappings, clang::DiagnosticMapping::setSeverity(), clang::DiagnosticMapping::setUpgradedFromWarning(), State, clang::diag::Warning, and clang::DiagnosticMapping::wasUpgradedFromWarning().
ReadPreprocessedEntity()
PreprocessedEntity * ASTReader::ReadPreprocessedEntity (unsigned Index) override virtual
Read a preallocated preprocessed entity from the external source.
Returns
null if an error occurred that prevented the preprocessed entity from being loaded.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 5952 of file ASTReader.cpp.
References clang::serialization::PPEntityOffset::BitOffset, clang::cast(), clang::Error, clang::File, clang::serialization::PPEntityOffset::getBegin(), clang::serialization::PPEntityOffset::getEnd(), clang::serialization::ModuleFile::MacroOffsetsBase, clang::serialization::PPD_INCLUSION_DIRECTIVE, clang::serialization::PPD_MACRO_DEFINITION, clang::serialization::PPD_MACRO_EXPANSION, clang::serialization::ModuleFile::PreprocessedEntityOffsets, and clang::serialization::ModuleFile::PreprocessorDetailCursor.
ReadReferencedSelectors()
void ASTReader::ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation > > & Sels) override virtual
Read the set of referenced selectors known to the external Sema source.
The external source should append its own referenced selectors to the given vector of selectors. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same selectors repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8349 of file ASTReader.cpp.
References DecodeSelector(), and clang::SourceLocation::getFromRawEncoding().
ReadSelector()
Selector clang::ASTReader::ReadSelector (ModuleFile & M, const RecordData & Record, unsigned & Idx) inline
Definition at line 2117 of file ASTReader.h.
References getLocalSelector().
Referenced by clang::ASTRecordReader::readSelector().
ReadSkippedRange()
SourceRange ASTReader::ReadSkippedRange (unsigned Index) override virtual
Read a preallocated skipped range from the external source.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 5938 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BasePreprocessedSkippedRangeID, clang::serialization::PPSkippedRange::getBegin(), clang::serialization::PPSkippedRange::getEnd(), and clang::serialization::ModuleFile::PreprocessedSkippedRangeOffsets.
ReadSLocEntry()
bool ASTReader::ReadSLocEntry (int ID) override virtual
Read the source location entry with index ID.
Implements clang::ExternalSLocEntrySource.
Definition at line 1408 of file ASTReader.cpp.
References clang::SrcMgr::ContentCache::BufferOverridden, clang::SrcMgr::ContentCache::ContentsEntry, clang::Error, clang::File, clang::serialization::ModuleFile::FileSortedDecls, clang::SrcMgr::ContentCache::getBufferIfLoaded(), clang::serialization::InputFile::getFile(), clang::SourceLocation::isInvalid(), clang::serialization::ModuleFile::isModule(), clang::serialization::InputFile::isOverridden(), clang::serialization::ModuleFile::Kind, clang::serialization::MK_MainFile, Offset, clang::SrcMgr::ContentCache::OrigEntry, clang::SrcMgr::FileInfo::setHasLineDirectives(), clang::serialization::ModuleFile::SLocEntryBaseID, clang::serialization::ModuleFile::SLocEntryBaseOffset, clang::serialization::ModuleFile::SLocEntryCursor, clang::serialization::ModuleFile::SLocEntryOffsets, clang::serialization::ModuleFile::SLocEntryOffsetsBase, clang::serialization::SM_SLOC_BUFFER_BLOB, clang::serialization::SM_SLOC_BUFFER_BLOB_COMPRESSED, clang::serialization::SM_SLOC_BUFFER_ENTRY, clang::serialization::SM_SLOC_EXPANSION_ENTRY, and clang::serialization::SM_SLOC_FILE_ENTRY.
ReadSourceLocation() [1/2]
SourceLocation clang::ASTReader::ReadSourceLocation (ModuleFile & ModuleFile, const RecordDataImpl & Record, unsigned & Idx) inline
Read a source location.
Definition at line 2160 of file ASTReader.h.
References ReadSourceLocation().
ReadSourceLocation() [2/2]
SourceLocation clang::ASTReader::ReadSourceLocation (ModuleFile & ModuleFile, uint32_t Raw) const inline
Read a source location from raw form.
Definition at line 2141 of file ASTReader.h.
References ReadUntranslatedSourceLocation(), and TranslateSourceLocation().
Referenced by ReadSourceLocation(), clang::ASTRecordReader::readSourceLocation(), and ReadSourceRange().
ReadSourceRange()
SourceRange ASTReader::ReadSourceRange (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Read a source range.
Definition at line 8974 of file ASTReader.cpp.
References ReadSourceLocation().
Referenced by ReadComments(), and clang::ASTRecordReader::readSourceRange().
ReadStmt()
Stmt * ASTReader::ReadStmt (ModuleFile & F)
Reads a statement.
Definition at line 2581 of file ASTReaderStmt.cpp.
References ReadSubStmt().
Referenced by ReadExpr(), and clang::ASTRecordReader::readStmt().
ReadString()
std::string ASTReader::ReadString (const RecordData & Record, unsigned & Idx) static
Definition at line 8987 of file ASTReader.cpp.
References clang::Result.
Referenced by ReadPath(), ReadPath(), and clang::ASTRecordReader::readString().
ReadSubExpr()
Expr * ASTReader::ReadSubExpr ()
Reads a sub-expression operand during statement reading.
Definition at line 2599 of file ASTReaderStmt.cpp.
References ReadSubStmt().
Referenced by clang::ASTRecordReader::readSubExpr().
ReadSubStmt()
Stmt * clang::ASTReader::ReadSubStmt () inline
Reads a sub-statement operand during statement reading.
Definition at line 2203 of file ASTReader.h.
Referenced by ReadStmt(), ReadSubExpr(), and clang::ASTRecordReader::readSubStmt().
ReadTentativeDefinitions()
void ASTReader::ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > & TentativeDefs) override virtual
Read the set of tentative definitions known to the external Sema source.
The external source should append its own tentative definitions to the given vector of tentative definitions. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8282 of file ASTReader.cpp.
References GetDecl(), and N.
ReadToken()
Token ASTReader::ReadToken (ModuleFile & M, const RecordDataImpl & Record, unsigned & Idx)
Reads a token out of a record.
Definition at line 1657 of file ASTReader.cpp.
References clang::Token::setFlag(), clang::Token::setIdentifierInfo(), clang::Token::setKind(), clang::Token::setLength(), clang::Token::setLocation(), clang::Token::startToken(), and Tok.
Referenced by ReadLateParsedTemplates(), and clang::ASTRecordReader::readToken().
readType()
QualType clang::ASTReader::readType (ModuleFile & F, const RecordData & Record, unsigned & Idx) inline
Read a type from the current position in the given record, which was read from the given AST file.
Definition at line 1804 of file ASTReader.h.
References getLocalType().
Referenced by clang::ASTRecordReader::readType().
ReadUndefinedButUsed()
void ASTReader::ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > & Undefined) override virtual
Load the set of used but not defined functions or variables with internal linkage, or used but not defined internal functions.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8257 of file ASTReader.cpp.
References clang::cast(), GetDecl(), clang::SourceLocation::getFromRawEncoding(), and N.
ReadUntranslatedSourceLocation()
SourceLocation clang::ASTReader::ReadUntranslatedSourceLocation (uint32_t Raw) const inline
Read a source location from raw form and return it in its originating module file's source location space.
Definition at line 2136 of file ASTReader.h.
References clang::SourceLocation::getFromRawEncoding().
Referenced by ReadSourceLocation().
ReadUnusedFileScopedDecls()
void ASTReader::ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > & Decls) override virtual
Read the set of unused file-scope declarations known to the external Sema source.
The external source should append its own unused, filed-scope to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8292 of file ASTReader.cpp.
References GetDecl(), and N.
ReadUnusedLocalTypedefNameCandidates()
void ASTReader::ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > & Decls) override virtual
Read the set of potentially unused typedefs known to the source.
The external source should append its own potentially unused local typedefs to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8324 of file ASTReader.cpp.
References GetDecl(), and N.
ReadUsedVTables()
void ASTReader::ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > & VTables) override virtual
Read the set of used vtables known to the external Sema source.
The external source should append its own used vtables to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same vtables repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8387 of file ASTReader.cpp.
References clang::ExternalVTableUse::DefinitionRequired, GetDecl(), clang::SourceLocation::getFromRawEncoding(), clang::ExternalVTableUse::Location, N, and clang::ExternalVTableUse::Record.
ReadVersionTuple()
VersionTuple ASTReader::ReadVersionTuple (const RecordData & Record, unsigned & Idx) static
Read a version tuple.
Definition at line 9009 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::readVersionTuple().
ReadWeakUndeclaredIdentifiers()
void ASTReader::ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo > > & WI) override virtual
Read the set of weak, undeclared identifiers known to the external Sema source.
The external source should append its own weak, undeclared identifiers to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same identifiers repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8367 of file ASTReader.cpp.
References DecodeIdentifierInfo(), clang::SourceLocation::getFromRawEncoding(), N, clang::WeakInfo::setUsed(), and Used.
RecordSwitchCaseID()
void ASTReader::RecordSwitchCaseID (SwitchCase * SC, unsigned ID)
Record that the given ID maps to the given switch-case statement.
Definition at line 9044 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::recordSwitchCaseID().
resetForReload()
void clang::ASTReader::resetForReload () inline
Reset reader for a reload try.
Definition at line 1651 of file ASTReader.h.
ResolveImportedPath() [1/2]
void ASTReader::ResolveImportedPath (ModuleFile & M, std::string & Filename)
If we are loading a relocatable PCH or module file, and the filename is not an absolute path, add the system or module root to the beginning of the file name.
Definition at line 2452 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDirectory, and Filename.
Referenced by ReadPath(), and ReadPath().
ResolveImportedPath() [2/2]
void ASTReader::ResolveImportedPath (std::string & Filename, StringRef Prefix) static
Definition at line 2458 of file ASTReader.cpp.
References Filename.
resolvePendingMacro()
void ASTReader::resolvePendingMacro (IdentifierInfo * II, const PendingMacroInfo & PMInfo)
Definition at line 2089 of file ASTReader.cpp.
References clang::Error, clang::serialization::ModuleFile::isModule(), clang::serialization::ModuleFile::MacroCursor, clang::serialization::ModuleFile::MacroOffsetsBase, clang::MacroDirective::MD_Define, clang::MacroDirective::MD_Undefine, clang::MacroDirective::MD_Visibility, N, clang::serialization::PP_MACRO_DIRECTIVE_HISTORY, clang::serialization::PP_MODULE_MACRO, and clang::MacroDirective::setPrevious().
setDeserializationListener()
void ASTReader::setDeserializationListener (ASTDeserializationListener * Listener, bool TakeOwnership = false)
Set the AST deserialization listener.
Definition at line 815 of file ASTReader.cpp.
SetGloballyVisibleDecls()
void ASTReader::SetGloballyVisibleDecls (IdentifierInfo * II, const SmallVectorImpl< uint32_t > & DeclIDs, SmallVectorImpl< Decl * > * Decls = nullptr)
Set the globally-visible declarations associated with the given identifier.
If the AST reader is currently in a state where the given declaration IDs cannot safely be resolved, they are queued until it is safe to resolve them.
Parameters
II an IdentifierInfo that refers to one or more globally-visible declarations.
DeclIDs the set of declaration IDs with the name II that are visible at global scope.
Decls if non-null, this vector will be populated with the set of deserialized declarations. These declarations will not be pushed into scope.
Definition at line 8468 of file ASTReader.cpp.
References clang::cast(), GetDecl(), N, and PreloadedDeclIDs.
SetIdentifierInfo()
void ASTReader::SetIdentifierInfo (unsigned ID, IdentifierInfo * II)
Definition at line 8443 of file ASTReader.cpp.
References clang::ASTDeserializationListener::IdentifierRead().
setListener()
void clang::ASTReader::setListener (std::unique_ptr< ASTReaderListener > Listener) inline
Set the AST callbacks listener.
Definition at line 1596 of file ASTReader.h.
Referenced by clang::ASTReader::ListenerScope::ListenerScope(), and clang::ASTReader::ListenerScope::~ListenerScope().
SkipPath()
static void clang::ASTReader::SkipPath (const RecordData & Record, unsigned & Idx) inline static
Definition at line 2186 of file ASTReader.h.
References SkipString().
SkipString()
static void clang::ASTReader::SkipString (const RecordData & Record, unsigned & Idx) inline static
Definition at line 2174 of file ASTReader.h.
Referenced by SkipPath().
StartedDeserializing()
void ASTReader::StartedDeserializing () override virtual
Notify ASTReader that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
Must be paired with FinishedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 11549 of file ASTReader.cpp.
StartTranslationUnit()
void ASTReader::StartTranslationUnit (ASTConsumer * Consumer) override virtual
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
This function will provide all of the external definitions to the ASTConsumer.
Reimplemented from clang::ExternalASTSource.
Definition at line 7692 of file ASTReader.cpp.
takeListener()
std::unique_ptr< ASTReaderListener > clang::ASTReader::takeListener () inline
Take the AST callbacks listener.
Definition at line 1591 of file ASTReader.h.
Referenced by clang::ASTReader::ListenerScope::ListenerScope(), and clang::ASTReader::ListenerScope::~ListenerScope().
TranslateSourceLocation()
SourceLocation clang::ASTReader::TranslateSourceLocation (ModuleFile & ModuleFile, SourceLocation Loc) const inline
Translate a source location from another module file's source location space into ours.
Definition at line 2148 of file ASTReader.h.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::SourceLocation::getLocWithOffset(), clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::ModuleFile::SLocRemap.
Referenced by ReadSourceLocation().
updateOutOfDateIdentifier()
void ASTReader::updateOutOfDateIdentifier (IdentifierInfo & II) override virtual
Update an out-of-date identifier.
Implements clang::ExternalPreprocessorSource.
Definition at line 2053 of file ASTReader.cpp.
References clang::IdentifierInfo::getName().
updateOutOfDateSelector()
void ASTReader::updateOutOfDateSelector (Selector Sel) override virtual
Load the contents of the global method pool for a given selector if necessary.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8241 of file ASTReader.cpp.
References ReadMethodPool().
UpdateSema()
void ASTReader::UpdateSema ()
Update the state of Sema after loading some additional modules.
Definition at line 7878 of file ASTReader.cpp.
visitInputFiles()
void ASTReader::visitInputFiles (serialization::ModuleFile & MF, bool IncludeSystem, bool Complain, llvm::function_ref< void(const serialization::InputFile &IF, bool isSystem)> Visitor)
Visit all the input files of the given module file.
Definition at line 9132 of file ASTReader.cpp.
References clang::serialization::ModuleFile::InputFilesLoaded, N, and clang::serialization::ModuleFile::NumUserInputFiles.
visitTopLevelModuleMaps()
void ASTReader::visitTopLevelModuleMaps (serialization::ModuleFile & MF, llvm::function_ref< void(const FileEntry *)> Visitor)
Visit all the top-level module maps loaded when building the given module file.
Definition at line 9147 of file ASTReader.cpp.
References clang::serialization::ModuleFile::InputFilesLoaded.
Referenced by clang::FrontendAction::BeginSourceFile().
Friends And Related Symbol Documentation
ASTDeclReader
friend class ASTDeclReader friend
Types of AST files.
Definition at line 352 of file ASTReader.h.
ASTIdentifierIterator
friend class ASTIdentifierIterator friend
Definition at line 353 of file ASTReader.h.
Referenced by getIdentifiers().
ASTRecordReader
friend class ASTRecordReader friend
Definition at line 354 of file ASTReader.h.
ASTUnit
friend class ASTUnit friend
Definition at line 355 of file ASTReader.h.
ASTWriter
friend class ASTWriter friend
Definition at line 356 of file ASTReader.h.
PCHValidator
friend class PCHValidator friend
Definition at line 357 of file ASTReader.h.
serialization::reader::ASTIdentifierLookupTrait
friend class serialization::reader::ASTIdentifierLookupTrait friend
Definition at line 358 of file ASTReader.h.
serialization::ReadMethodPoolVisitor
friend class serialization::ReadMethodPoolVisitor friend
Definition at line 359 of file ASTReader.h.
TypeLocReader
friend class TypeLocReader friend
Definition at line 360 of file ASTReader.h.
Member Data Documentation
CommentsCursors
SmallVector<std::pair<llvm::BitstreamCursor, serialization::ModuleFile *>, 8> clang::ASTReader::CommentsCursors
Cursors for comments blocks.
Definition at line 2282 of file ASTReader.h.
Referenced by ReadComments().
PreloadedDeclIDs
SmallVector<uint64_t, 16> clang::ASTReader::PreloadedDeclIDs
Definition at line 2255 of file ASTReader.h.
Referenced by SetGloballyVisibleDecls().
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTReader.h
lib/Serialization/ASTReader.cpp
lib/Serialization/ASTReaderDecl.cpp
lib/Serialization/ASTReaderStmt.cpp