clang: clang::ento::NodeBuilder Class Reference
clang::ento::NodeBuilder Class Reference
This is the simplest builder which generates nodes in the ExplodedGraph.
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
Public Types
using iterator = ExplodedNodeSet::iterator
Public Member Functions
NodeBuilder (ExplodedNode *SrcNode, ExplodedNodeSet &DstSet, const NodeBuilderContext &Ctx, bool F=true)
NodeBuilder (const ExplodedNodeSet &SrcSet, ExplodedNodeSet &DstSet, const NodeBuilderContext &Ctx, bool F=true)
virtual ~NodeBuilder ()=default
ExplodedNode * generateNode (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred)
Generates a node in the ExplodedGraph.
ExplodedNode * generateSink (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred)
Generates a sink in the ExplodedGraph.
const ExplodedNodeSet & getResults ()
iterator begin ()
Iterators through the results frontier.
iterator end ()
const NodeBuilderContext & getContext ()
bool hasGeneratedNodes ()
void takeNodes (const ExplodedNodeSet &S)
void takeNodes (ExplodedNode *N)
void addNodes (const ExplodedNodeSet &S)
void addNodes (ExplodedNode *N)
Protected Member Functions
virtual bool checkResults ()
Checks if the results are ready.
bool hasNoSinksInFrontier ()
virtual void finalizeResults ()
Allow subclasses to finalize results before result_begin() is executed.
ExplodedNode * generateNodeImpl (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred, bool MarkAsSink=false)
Protected Attributes
const NodeBuilderContext & C
bool Finalized
Specifies if the builder results have been finalized.
bool HasGeneratedNodes = false
ExplodedNodeSet & Frontier
The frontier set - a set of nodes which need to be propagated after the builder dies.
Detailed Description
This is the simplest builder which generates nodes in the ExplodedGraph.
The main benefit of the builder is that it automatically tracks the frontier nodes (or destination set). This is the set of nodes which should be propagated to the next step / builder. They are the nodes which have been added to the builder (either as the input node set or as the newly constructed nodes) but did not have any outgoing transitions added.
Definition at line 236 of file CoreEngine.h.
Member Typedef Documentation
iterator
using clang::ento::NodeBuilder::iterator = ExplodedNodeSet::iterator
Definition at line 312 of file CoreEngine.h.
Constructor & Destructor Documentation
NodeBuilder() [1/2]
clang::ento::NodeBuilder::NodeBuilder (ExplodedNode * SrcNode, ExplodedNodeSet & DstSet, const NodeBuilderContext & Ctx, bool F = true) inline
Definition at line 273 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::Add(), and Frontier.
NodeBuilder() [2/2]
clang::ento::NodeBuilder::NodeBuilder (const ExplodedNodeSet & SrcSet, ExplodedNodeSet & DstSet, const NodeBuilderContext & Ctx, bool F = true) inline
Definition at line 279 of file CoreEngine.h.
References Frontier, hasNoSinksInFrontier(), and clang::ento::ExplodedNodeSet::insert().
~NodeBuilder()
virtual clang::ento::NodeBuilder::~NodeBuilder () virtual default
Member Function Documentation
addNodes() [1/2]
void clang::ento::NodeBuilder::addNodes (const ExplodedNodeSet & S) inline
Definition at line 335 of file CoreEngine.h.
References Frontier, and clang::ento::ExplodedNodeSet::insert().
Referenced by clang::ento::ExprEngine::Visit(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitMemberExpr(), clang::ento::ExprEngine::VisitUnaryOperator(), and clang::ento::StmtNodeBuilder::~StmtNodeBuilder().
addNodes() [2/2]
void clang::ento::NodeBuilder::addNodes (ExplodedNode * N) inline
Definition at line 336 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::Add(), Frontier, and N.
begin()
iterator clang::ento::NodeBuilder::begin () inline
Iterators through the results frontier.
Definition at line 315 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::begin(), checkResults(), finalizeResults(), and Frontier.
checkResults()
virtual bool clang::ento::NodeBuilder::checkResults () inline protected virtual
Checks if the results are ready.
Definition at line 253 of file CoreEngine.h.
References Finalized.
Referenced by begin(), and getResults().
end()
iterator clang::ento::NodeBuilder::end () inline
Definition at line 321 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::end(), finalizeResults(), and Frontier.
finalizeResults()
virtual void clang::ento::NodeBuilder::finalizeResults () inline protected virtual
Allow subclasses to finalize results before result_begin() is executed.
Definition at line 265 of file CoreEngine.h.
Referenced by begin(), end(), and getResults().
generateNode()
ExplodedNode * clang::ento::NodeBuilder::generateNode (const ProgramPoint & PP, ProgramStateRef State, ExplodedNode * Pred) inline
Generates a node in the ExplodedGraph.
Definition at line 289 of file CoreEngine.h.
References generateNodeImpl().
Referenced by clang::ento::ExprEngine::evalCall(), clang::ento::NodeBuilderWithSinks::generateNode(), clang::ento::StmtNodeBuilder::generateNode(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::ento::ExprEngine::processEndOfFunction(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessLoopExit(), clang::ento::ExprEngine::ProcessNewAllocator(), clang::ento::ExprEngine::ProcessTemporaryDtor(), and clang::ento::ExprEngine::VisitCXXDestructor().
generateNodeImpl()
ExplodedNode * NodeBuilder::generateNodeImpl (const ProgramPoint & PP, ProgramStateRef State, ExplodedNode * Pred, bool MarkAsSink = false) protected
Definition at line 604 of file CoreEngine.cpp.
References clang::ento::ExplodedNodeSet::Add(), clang::ento::ExplodedNode::addPredecessor(), C, clang::ento::NodeBuilderContext::Eng, clang::ento::ExplodedNodeSet::erase(), Frontier, clang::ento::ExplodedGraph::getNode(), HasGeneratedNodes, and N.
Referenced by clang::ento::BranchNodeBuilder::generateNode(), generateNode(), and generateSink().
generateSink()
ExplodedNode * clang::ento::NodeBuilder::generateSink (const ProgramPoint & PP, ProgramStateRef State, ExplodedNode * Pred) inline
Generates a sink in the ExplodedGraph.
When a node is marked as sink, the exploration from the node is stopped - the node becomes the last node on the path and certain kinds of bugs are suppressed.
Definition at line 300 of file CoreEngine.h.
References generateNodeImpl().
Referenced by clang::ento::NodeBuilderWithSinks::generateSink(), clang::ento::StmtNodeBuilder::generateSink(), and clang::ento::ExprEngine::VisitCXXDestructor().
getContext()
const NodeBuilderContext & clang::ento::NodeBuilder::getContext () inline
Definition at line 326 of file CoreEngine.h.
References C.
Referenced by clang::ento::CheckerContext::blockCount(), clang::ento::CheckerContext::getBlockID(), and clang::ento::ExprEngine::processCFGBlockEntrance().
getResults()
const ExplodedNodeSet & clang::ento::NodeBuilder::getResults () inline
Definition at line 306 of file CoreEngine.h.
References checkResults(), finalizeResults(), and Frontier.
Referenced by clang::ento::ExprEngine::VisitCXXNewExpr(), and clang::ento::ExprEngine::VisitDeclStmt().
hasGeneratedNodes()
bool clang::ento::NodeBuilder::hasGeneratedNodes () inline
Definition at line 327 of file CoreEngine.h.
References HasGeneratedNodes.
hasNoSinksInFrontier()
bool clang::ento::NodeBuilder::hasNoSinksInFrontier () inline protected
Definition at line 257 of file CoreEngine.h.
References Frontier.
Referenced by NodeBuilder().
takeNodes() [1/2]
void clang::ento::NodeBuilder::takeNodes (const ExplodedNodeSet & S) inline
Definition at line 329 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::erase(), and Frontier.
Referenced by clang::ento::BranchNodeBuilder::BranchNodeBuilder(), clang::ento::BranchNodeBuilder::BranchNodeBuilder(), REGISTER_MAP_WITH_PROGRAMSTATE(), clang::ento::StmtNodeBuilder::StmtNodeBuilder(), clang::ento::StmtNodeBuilder::StmtNodeBuilder(), clang::ento::ExprEngine::Visit(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitMemberExpr(), and clang::ento::ExprEngine::VisitUnaryOperator().
takeNodes() [2/2]
void clang::ento::NodeBuilder::takeNodes (ExplodedNode * N) inline
Definition at line 334 of file CoreEngine.h.
References clang::ento::ExplodedNodeSet::erase(), Frontier, and N.
Member Data Documentation
C
const NodeBuilderContext& clang::ento::NodeBuilder::C protected
Definition at line 240 of file CoreEngine.h.
Referenced by clang::ento::BranchNodeBuilder::generateNode(), generateNodeImpl(), and getContext().
Finalized
bool clang::ento::NodeBuilder::Finalized protected
Specifies if the builder results have been finalized.
For example, if it is set to false, autotransitions are yet to be generated.
Definition at line 244 of file CoreEngine.h.
Referenced by checkResults().
Frontier
ExplodedNodeSet& clang::ento::NodeBuilder::Frontier protected
The frontier set - a set of nodes which need to be propagated after the builder dies.
Definition at line 250 of file CoreEngine.h.
Referenced by addNodes(), addNodes(), begin(), end(), generateNodeImpl(), getResults(), hasNoSinksInFrontier(), NodeBuilder(), NodeBuilder(), takeNodes(), takeNodes(), and clang::ento::StmtNodeBuilder::~StmtNodeBuilder().
HasGeneratedNodes
bool clang::ento::NodeBuilder::HasGeneratedNodes = false protected
Definition at line 246 of file CoreEngine.h.
Referenced by generateNodeImpl(), and hasGeneratedNodes().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h
lib/StaticAnalyzer/Core/CoreEngine.cpp