clang: clang::serialization::BasicReaderBase< T > Class Template Reference
clang::serialization::BasicReaderBase< T > Class Template Reference
#include "clang/AST/AbstractBasicReader.h"
Public Member Functions
ASTContext & getASTContext ()
Impl & asImpl ()
APValue readAPValue ()
APValue::ValueKind readAPValueKind ()
ArrayType::ArraySizeModifier readArraySizeModifier ()
attr::Kind readAttrKind ()
AutoTypeKeyword readAutoTypeKeyword ()
BuiltinType::Kind readBuiltinTypeKind ()
CXXRecordDecl * readCXXRecordDeclRef ()
CallingConv readCallingConv ()
ConceptDecl * readConceptDeclRef ()
DeclarationName readDeclarationName ()
DeclarationName::NameKind readDeclarationNameKind ()
ElaboratedTypeKeyword readElaboratedTypeKeyword ()
Expr * readExprRef ()
FunctionDecl * readFunctionDeclRef ()
NamedDecl * readNamedDeclRef ()
NamespaceAliasDecl * readNamespaceAliasDeclRef ()
NamespaceDecl * readNamespaceDeclRef ()
NestedNameSpecifier::SpecifierKind readNestedNameSpecifierKind ()
ObjCProtocolDecl * readObjCProtocolDeclRef ()
ObjCTypeParamDecl * readObjCTypeParamDeclRef ()
OverloadedOperatorKind readOverloadedOperatorKind ()
RefQualifierKind readRefQualifierKind ()
TagDecl * readTagDeclRef ()
TemplateArgument readTemplateArgument ()
TemplateArgument::ArgKind readTemplateArgumentKind ()
TemplateDecl * readTemplateDeclRef ()
TemplateName readTemplateName ()
TemplateName::NameKind readTemplateNameKind ()
TemplateTemplateParmDecl * readTemplateTemplateParmDeclRef ()
TemplateTypeParmDecl * readTemplateTypeParmDeclRef ()
UnaryTransformType::UTTKind readUnaryTypeTransformKind ()
ValueDecl * readValueDeclRef ()
VectorType::VectorKind readVectorKind ()
Protected Member Functions
BasicReaderBase (ASTContext &ctx)
Detailed Description
template<typename T>
class clang::serialization::BasicReaderBase< T >
Definition at line 27 of file APValue.h.
Constructor & Destructor Documentation
BasicReaderBase()
template<typename T > clang::serialization::BasicReaderBase< T >::BasicReaderBase (ASTContext & ctx) inline protected
Definition at line 517 of file AbstractBasicReader.h.
Member Function Documentation
asImpl()
template<typename T > Impl & clang::serialization::BasicReaderBase< T >::asImpl () inline
Definition at line 520 of file AbstractBasicReader.h.
getASTContext()
template<typename T > ASTContext & clang::serialization::BasicReaderBase< T >::getASTContext () inline
Definition at line 519 of file AbstractBasicReader.h.
readAPValue()
template<typename T > APValue clang::serialization::BasicReaderBase< T >::readAPValue () inline
Definition at line 521 of file AbstractBasicReader.h.
Referenced by clang::ASTDeclReader::VisitLifetimeExtendedTemporaryDecl(), and clang::ASTDeclReader::VisitTemplateParamObjectDecl().
readAPValueKind()
template<typename T > APValue::ValueKind clang::serialization::BasicReaderBase< T >::readAPValueKind () inline
Definition at line 729 of file AbstractBasicReader.h.
readArraySizeModifier()
template<typename T > ArrayType::ArraySizeModifier clang::serialization::BasicReaderBase< T >::readArraySizeModifier () inline
Definition at line 732 of file AbstractBasicReader.h.
readAttrKind()
template<typename T > attr::Kind clang::serialization::BasicReaderBase< T >::readAttrKind () inline
Definition at line 735 of file AbstractBasicReader.h.
readAutoTypeKeyword()
template<typename T > AutoTypeKeyword clang::serialization::BasicReaderBase< T >::readAutoTypeKeyword () inline
Definition at line 738 of file AbstractBasicReader.h.
readBuiltinTypeKind()
template<typename T > BuiltinType::Kind clang::serialization::BasicReaderBase< T >::readBuiltinTypeKind () inline
Definition at line 741 of file AbstractBasicReader.h.
readCallingConv()
template<typename T > CallingConv clang::serialization::BasicReaderBase< T >::readCallingConv () inline
Definition at line 747 of file AbstractBasicReader.h.
readConceptDeclRef()
template<typename T > ConceptDecl * clang::serialization::BasicReaderBase< T >::readConceptDeclRef () inline
Definition at line 750 of file AbstractBasicReader.h.
readCXXRecordDeclRef()
template<typename T > CXXRecordDecl * clang::serialization::BasicReaderBase< T >::readCXXRecordDeclRef () inline
Definition at line 744 of file AbstractBasicReader.h.
readDeclarationName()
template<typename T > DeclarationName clang::serialization::BasicReaderBase< T >::readDeclarationName () inline
Definition at line 753 of file AbstractBasicReader.h.
Referenced by clang::ASTDeclReader::VisitNamedDecl(), clang::ASTDeclReader::VisitObjCPropertyDecl(), and clang::ASTDeclReader::VisitOMPDeclareMapperDecl().
readDeclarationNameKind()
template<typename T > DeclarationName::NameKind clang::serialization::BasicReaderBase< T >::readDeclarationNameKind () inline
Definition at line 840 of file AbstractBasicReader.h.
readElaboratedTypeKeyword()
template<typename T > ElaboratedTypeKeyword clang::serialization::BasicReaderBase< T >::readElaboratedTypeKeyword () inline
Definition at line 843 of file AbstractBasicReader.h.
readExprRef()
template<typename T > Expr * clang::serialization::BasicReaderBase< T >::readExprRef () inline
Definition at line 846 of file AbstractBasicReader.h.
readFunctionDeclRef()
template<typename T > FunctionDecl * clang::serialization::BasicReaderBase< T >::readFunctionDeclRef () inline
Definition at line 849 of file AbstractBasicReader.h.
readNamedDeclRef()
template<typename T > NamedDecl * clang::serialization::BasicReaderBase< T >::readNamedDeclRef () inline
Definition at line 852 of file AbstractBasicReader.h.
readNamespaceAliasDeclRef()
template<typename T > NamespaceAliasDecl * clang::serialization::BasicReaderBase< T >::readNamespaceAliasDeclRef () inline
Definition at line 855 of file AbstractBasicReader.h.
readNamespaceDeclRef()
template<typename T > NamespaceDecl * clang::serialization::BasicReaderBase< T >::readNamespaceDeclRef () inline
Definition at line 858 of file AbstractBasicReader.h.
readNestedNameSpecifierKind()
template<typename T > NestedNameSpecifier::SpecifierKind clang::serialization::BasicReaderBase< T >::readNestedNameSpecifierKind () inline
Definition at line 861 of file AbstractBasicReader.h.
readObjCProtocolDeclRef()
template<typename T > ObjCProtocolDecl * clang::serialization::BasicReaderBase< T >::readObjCProtocolDeclRef () inline
Definition at line 864 of file AbstractBasicReader.h.
readObjCTypeParamDeclRef()
template<typename T > ObjCTypeParamDecl * clang::serialization::BasicReaderBase< T >::readObjCTypeParamDeclRef () inline
Definition at line 867 of file AbstractBasicReader.h.
readOverloadedOperatorKind()
template<typename T > OverloadedOperatorKind clang::serialization::BasicReaderBase< T >::readOverloadedOperatorKind () inline
Definition at line 870 of file AbstractBasicReader.h.
readRefQualifierKind()
template<typename T > RefQualifierKind clang::serialization::BasicReaderBase< T >::readRefQualifierKind () inline
Definition at line 873 of file AbstractBasicReader.h.
readTagDeclRef()
template<typename T > TagDecl * clang::serialization::BasicReaderBase< T >::readTagDeclRef () inline
Definition at line 876 of file AbstractBasicReader.h.
readTemplateArgument()
template<typename T > TemplateArgument clang::serialization::BasicReaderBase< T >::readTemplateArgument () inline
Definition at line 879 of file AbstractBasicReader.h.
readTemplateArgumentKind()
template<typename T > TemplateArgument::ArgKind clang::serialization::BasicReaderBase< T >::readTemplateArgumentKind () inline
Definition at line 959 of file AbstractBasicReader.h.
readTemplateDeclRef()
template<typename T > TemplateDecl * clang::serialization::BasicReaderBase< T >::readTemplateDeclRef () inline
Definition at line 962 of file AbstractBasicReader.h.
readTemplateName()
template<typename T > TemplateName clang::serialization::BasicReaderBase< T >::readTemplateName () inline
Definition at line 965 of file AbstractBasicReader.h.
readTemplateNameKind()
template<typename T > TemplateName::NameKind clang::serialization::BasicReaderBase< T >::readTemplateNameKind () inline
Definition at line 1044 of file AbstractBasicReader.h.
readTemplateTemplateParmDeclRef()
template<typename T > TemplateTemplateParmDecl * clang::serialization::BasicReaderBase< T >::readTemplateTemplateParmDeclRef () inline
Definition at line 1047 of file AbstractBasicReader.h.
readTemplateTypeParmDeclRef()
template<typename T > TemplateTypeParmDecl * clang::serialization::BasicReaderBase< T >::readTemplateTypeParmDeclRef () inline
Definition at line 1050 of file AbstractBasicReader.h.
readUnaryTypeTransformKind()
template<typename T > UnaryTransformType::UTTKind clang::serialization::BasicReaderBase< T >::readUnaryTypeTransformKind () inline
Definition at line 1053 of file AbstractBasicReader.h.
readValueDeclRef()
template<typename T > ValueDecl * clang::serialization::BasicReaderBase< T >::readValueDeclRef () inline
Definition at line 1056 of file AbstractBasicReader.h.
readVectorKind()
template<typename T > VectorType::VectorKind clang::serialization::BasicReaderBase< T >::readVectorKind () inline
Definition at line 1059 of file AbstractBasicReader.h.
The documentation for this class was generated from the following files:
include/clang/AST/AbstractBasicReader.h
include/clang/AST/APValue.h