clang: clang::ento::PathDiagnosticCallPiece Class Reference
clang::ento::PathDiagnosticCallPiece Class Reference
#include "clang/Analysis/PathDiagnostic.h"
Public Member Functions
~PathDiagnosticCallPiece () override
const Decl * getCaller () const
const Decl * getCallee () const
void setCallee (const CallEnter &CE, const SourceManager &SM)
bool hasCallStackMessage ()
void setCallStackMessage (StringRef st)
PathDiagnosticLocation getLocation () const override
std::shared_ptr< PathDiagnosticEventPiece > getCallEnterEvent () const
std::shared_ptr< PathDiagnosticEventPiece > getCallEnterWithinCallerEvent () const
std::shared_ptr< PathDiagnosticEventPiece > getCallExitEvent () const
void flattenLocations () override
void dump () const override
void Profile (llvm::FoldingSetNodeID &ID) const override
Public Member Functions inherited from clang::ento::PathDiagnosticPiece
PathDiagnosticPiece ()=delete
PathDiagnosticPiece (const PathDiagnosticPiece &)=delete
PathDiagnosticPiece & operator= (const PathDiagnosticPiece &)=delete
virtual ~PathDiagnosticPiece ()
StringRef getString () const
void setTag (const char *tag)
Tag this PathDiagnosticPiece with the given C-string.
const void * getTag () const
Return the opaque tag (if any) on the PathDiagnosticPiece.
StringRef getTagStr () const
Return the string representation of the tag.
DisplayHint getDisplayHint () const
getDisplayHint - Return a hint indicating where the diagnostic should be displayed by the PathDiagnosticConsumer.
Kind getKind () const
void addRange (SourceRange R)
void addRange (SourceLocation B, SourceLocation E)
void addFixit (FixItHint F)
ArrayRef< SourceRange > getRanges () const
Return the SourceRanges associated with this PathDiagnosticPiece.
ArrayRef< FixItHint > getFixits () const
Return the fix-it hints associated with this PathDiagnosticPiece.
void setAsLastInMainSourceFile ()
bool isLastInMainSourceFile () const
Static Public Member Functions
static std::shared_ptr< PathDiagnosticCallPiece > construct (const CallExitEnd &CE, const SourceManager &SM)
static PathDiagnosticCallPiece * construct (PathPieces &pieces, const Decl *caller)
static bool classof (const PathDiagnosticPiece *P)
Public Attributes
PathDiagnosticLocation callEnter
PathDiagnosticLocation callEnterWithin
PathDiagnosticLocation callReturn
PathPieces path
Additional Inherited Members
Public Types inherited from clang::ento::PathDiagnosticPiece
enum Kind {
ControlFlow , Event , Macro , Call ,
Note , PopUp
}
enum DisplayHint { Above , Below }
Protected Member Functions inherited from clang::ento::PathDiagnosticPiece
PathDiagnosticPiece (StringRef s, Kind k, DisplayHint hint=Below)
PathDiagnosticPiece (Kind k, DisplayHint hint=Below)
Detailed Description
Definition at line 565 of file PathDiagnostic.h.
Constructor & Destructor Documentation
~PathDiagnosticCallPiece()
PathDiagnosticCallPiece::~PathDiagnosticCallPiece () override default
Member Function Documentation
classof()
static bool clang::ento::PathDiagnosticCallPiece::classof (const PathDiagnosticPiece * P) inline static
Definition at line 630 of file PathDiagnostic.h.
References clang::ento::PathDiagnosticPiece::Call, and P.
construct() [1/2]
std::shared_ptr< PathDiagnosticCallPiece > PathDiagnosticCallPiece::construct (const CallExitEnd & CE, const SourceManager & SM) static
Definition at line 847 of file PathDiagnostic.cpp.
References clang::CallExitEnd::getCalleeContext(), clang::LocationContext::getDecl(), clang::ProgramPoint::getLocationContext(), getLocationForCaller(), and SM.
construct() [2/2]
PathDiagnosticCallPiece * PathDiagnosticCallPiece::construct (PathPieces & pieces, const Decl * caller) static
Definition at line 858 of file PathDiagnostic.cpp.
References clang::C.
dump()
LLVM_DUMP_METHOD void PathDiagnosticCallPiece::dump () const override virtual
Implements clang::ento::PathDiagnosticPiece.
Definition at line 1159 of file PathDiagnostic.cpp.
flattenLocations()
void clang::ento::PathDiagnosticCallPiece::flattenLocations () inline override virtual
Implements clang::ento::PathDiagnosticPiece.
Definition at line 612 of file PathDiagnostic.h.
References callEnter, callReturn, clang::ento::PathDiagnosticLocation::flatten(), and path.
getCallee()
const Decl * clang::ento::PathDiagnosticCallPiece::getCallee () const inline
Definition at line 599 of file PathDiagnostic.h.
getCallEnterEvent()
std::shared_ptr< PathDiagnosticEventPiece > PathDiagnosticCallPiece::getCallEnterEvent () const
Definition at line 1002 of file PathDiagnostic.cpp.
References describeCodeDecl().
getCallEnterWithinCallerEvent()
std::shared_ptr< PathDiagnosticEventPiece > PathDiagnosticCallPiece::getCallEnterWithinCallerEvent () const
Definition at line 1021 of file PathDiagnostic.cpp.
References describeCodeDecl().
getCaller()
const Decl * clang::ento::PathDiagnosticCallPiece::getCaller () const inline
Definition at line 597 of file PathDiagnostic.h.
getCallExitEvent()
std::shared_ptr< PathDiagnosticEventPiece > PathDiagnosticCallPiece::getCallExitEvent () const
Definition at line 1040 of file PathDiagnostic.cpp.
References describeCodeDecl().
getLocation()
PathDiagnosticLocation clang::ento::PathDiagnosticCallPiece::getLocation () const inline override virtual
Implements clang::ento::PathDiagnosticPiece.
Definition at line 605 of file PathDiagnostic.h.
References callEnter.
hasCallStackMessage()
bool clang::ento::PathDiagnosticCallPiece::hasCallStackMessage () inline
Definition at line 602 of file PathDiagnostic.h.
Profile()
void PathDiagnosticCallPiece::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Reimplemented from clang::ento::PathDiagnosticPiece.
Definition at line 1103 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticPiece::Profile().
setCallee()
void PathDiagnosticCallPiece::setCallee (const CallEnter & CE, const SourceManager & SM)
Definition at line 868 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticLocation::createBegin(), clang::LocationContext::getAnalysisDeclContext(), clang::CallEnter::getCalleeContext(), clang::LocationContext::getDecl(), clang::ProgramPoint::getLocationContext(), getLocationForCaller(), clang::AnalysisDeclContext::isBodyAutosynthesized(), and SM.
setCallStackMessage()
void clang::ento::PathDiagnosticCallPiece::setCallStackMessage (StringRef st) inline
Definition at line 603 of file PathDiagnostic.h.
Member Data Documentation
callEnter
PathDiagnosticLocation clang::ento::PathDiagnosticCallPiece::callEnter
Definition at line 590 of file PathDiagnostic.h.
Referenced by compareCall(), flattenLocations(), and getLocation().
callEnterWithin
PathDiagnosticLocation clang::ento::PathDiagnosticCallPiece::callEnterWithin
Definition at line 591 of file PathDiagnostic.h.
Referenced by compareCall().
callReturn
PathDiagnosticLocation clang::ento::PathDiagnosticCallPiece::callReturn
Definition at line 592 of file PathDiagnostic.h.
Referenced by compareCall(), and flattenLocations().
path
PathPieces clang::ento::PathDiagnosticCallPiece::path
Definition at line 593 of file PathDiagnostic.h.
Referenced by compareCall(), and flattenLocations().
The documentation for this class was generated from the following files:
include/clang/Analysis/PathDiagnostic.h
lib/Analysis/PathDiagnostic.cpp