clang: clang::TextNodeDumper Class Reference
clang::TextNodeDumper Class Reference
#include "clang/AST/TextNodeDumper.h"
Public Member Functions
TextNodeDumper (raw_ostream &OS, const ASTContext &Context, bool ShowColors)
TextNodeDumper (raw_ostream &OS, bool ShowColors)
void Visit (const comments::Comment *C, const comments::FullComment *FC)
void Visit (const Attr *A)
void Visit (const TemplateArgument &TA, SourceRange R, const Decl *From=nullptr, StringRef Label={})
void Visit (const Stmt *Node)
void Visit (const Type *T)
void Visit (QualType T)
void Visit (const Decl *D)
void Visit (const CXXCtorInitializer *Init)
void Visit (const OMPClause *C)
void Visit (const BlockDecl::Capture &C)
void Visit (const GenericSelectionExpr::ConstAssociation &A)
void Visit (const APValue &Value, QualType Ty)
void dumpPointer (const void *Ptr)
void dumpLocation (SourceLocation Loc)
void dumpSourceRange (SourceRange R)
void dumpBareType (QualType T, bool Desugar=true)
void dumpType (QualType T)
void dumpBareDeclRef (const Decl *D)
void dumpName (const NamedDecl *ND)
void dumpAccessSpecifier (AccessSpecifier AS)
void dumpCleanupObject (const ExprWithCleanups::CleanupObject &C)
void dumpDeclRef (const Decl *D, StringRef Label={})
void visitTextComment (const comments::TextComment *C, const comments::FullComment *)
void visitInlineCommandComment (const comments::InlineCommandComment *C, const comments::FullComment *)
void visitHTMLStartTagComment (const comments::HTMLStartTagComment *C, const comments::FullComment *)
void visitHTMLEndTagComment (const comments::HTMLEndTagComment *C, const comments::FullComment *)
void visitBlockCommandComment (const comments::BlockCommandComment *C, const comments::FullComment *)
void visitParamCommandComment (const comments::ParamCommandComment *C, const comments::FullComment *FC)
void visitTParamCommandComment (const comments::TParamCommandComment *C, const comments::FullComment *FC)
void visitVerbatimBlockComment (const comments::VerbatimBlockComment *C, const comments::FullComment *)
void visitVerbatimBlockLineComment (const comments::VerbatimBlockLineComment *C, const comments::FullComment *)
void visitVerbatimLineComment (const comments::VerbatimLineComment *C, const comments::FullComment *)
void VisitAMDGPUNumSGPRAttr (const AMDGPUNumSGPRAttr *A)
void VisitAMDGPUNumVGPRAttr (const AMDGPUNumVGPRAttr *A)
void VisitARMInterruptAttr (const ARMInterruptAttr *A)
void VisitAbiTagAttr (const AbiTagAttr *A)
void VisitAcquireCapabilityAttr (const AcquireCapabilityAttr *A)
void VisitAcquireHandleAttr (const AcquireHandleAttr *A)
void VisitAddressSpaceAttr (const AddressSpaceAttr *A)
void VisitAliasAttr (const AliasAttr *A)
void VisitAlignedAttr (const AlignedAttr *A)
void VisitAllocAlignAttr (const AllocAlignAttr *A)
void VisitAllocSizeAttr (const AllocSizeAttr *A)
void VisitAlwaysInlineAttr (const AlwaysInlineAttr *A)
void VisitAnnotateAttr (const AnnotateAttr *A)
void VisitArgumentWithTypeTagAttr (const ArgumentWithTypeTagAttr *A)
void VisitArmBuiltinAliasAttr (const ArmBuiltinAliasAttr *A)
void VisitAsmLabelAttr (const AsmLabelAttr *A)
void VisitAssertCapabilityAttr (const AssertCapabilityAttr *A)
void VisitAssumptionAttr (const AssumptionAttr *A)
void VisitAvailabilityAttr (const AvailabilityAttr *A)
void VisitBlocksAttr (const BlocksAttr *A)
void VisitBuiltinAttr (const BuiltinAttr *A)
void VisitCFGuardAttr (const CFGuardAttr *A)
void VisitCPUDispatchAttr (const CPUDispatchAttr *A)
void VisitCPUSpecificAttr (const CPUSpecificAttr *A)
void VisitCallableWhenAttr (const CallableWhenAttr *A)
void VisitCallbackAttr (const CallbackAttr *A)
void VisitCapabilityAttr (const CapabilityAttr *A)
void VisitCleanupAttr (const CleanupAttr *A)
void VisitCodeSegAttr (const CodeSegAttr *A)
void VisitConstInitAttr (const ConstInitAttr *A)
void VisitConstructorAttr (const ConstructorAttr *A)
void VisitConsumableAttr (const ConsumableAttr *A)
void VisitDeprecatedAttr (const DeprecatedAttr *A)
void VisitDestructorAttr (const DestructorAttr *A)
void VisitDiagnoseIfAttr (const DiagnoseIfAttr *A)
void VisitEnableIfAttr (const EnableIfAttr *A)
void VisitEnforceTCBAttr (const EnforceTCBAttr *A)
void VisitEnforceTCBLeafAttr (const EnforceTCBLeafAttr *A)
void VisitEnumExtensibilityAttr (const EnumExtensibilityAttr *A)
void VisitExternalSourceSymbolAttr (const ExternalSourceSymbolAttr *A)
void VisitFinalAttr (const FinalAttr *A)
void VisitFormatAttr (const FormatAttr *A)
void VisitFormatArgAttr (const FormatArgAttr *A)
void VisitIBOutletCollectionAttr (const IBOutletCollectionAttr *A)
void VisitIFuncAttr (const IFuncAttr *A)
void VisitInitPriorityAttr (const InitPriorityAttr *A)
void VisitInitSegAttr (const InitSegAttr *A)
void VisitLayoutVersionAttr (const LayoutVersionAttr *A)
void VisitLoopHintAttr (const LoopHintAttr *A)
void VisitMSInheritanceAttr (const MSInheritanceAttr *A)
void VisitMSP430InterruptAttr (const MSP430InterruptAttr *A)
void VisitMSVtorDispAttr (const MSVtorDispAttr *A)
void VisitMaxFieldAlignmentAttr (const MaxFieldAlignmentAttr *A)
void VisitMinVectorWidthAttr (const MinVectorWidthAttr *A)
void VisitMipsInterruptAttr (const MipsInterruptAttr *A)
void VisitMipsLongCallAttr (const MipsLongCallAttr *A)
void VisitMipsShortCallAttr (const MipsShortCallAttr *A)
void VisitModeAttr (const ModeAttr *A)
void VisitNSErrorDomainAttr (const NSErrorDomainAttr *A)
void VisitNoBuiltinAttr (const NoBuiltinAttr *A)
void VisitNoSanitizeAttr (const NoSanitizeAttr *A)
void VisitNonNullAttr (const NonNullAttr *A)
void VisitOMPAllocateDeclAttr (const OMPAllocateDeclAttr *A)
void VisitOMPCaptureKindAttr (const OMPCaptureKindAttr *A)
void VisitOMPDeclareSimdDeclAttr (const OMPDeclareSimdDeclAttr *A)
void VisitOMPDeclareTargetDeclAttr (const OMPDeclareTargetDeclAttr *A)
void VisitOMPDeclareVariantAttr (const OMPDeclareVariantAttr *A)
void VisitObjCBridgeAttr (const ObjCBridgeAttr *A)
void VisitObjCBridgeMutableAttr (const ObjCBridgeMutableAttr *A)
void VisitObjCBridgeRelatedAttr (const ObjCBridgeRelatedAttr *A)
void VisitObjCGCAttr (const ObjCGCAttr *A)
void VisitObjCMethodFamilyAttr (const ObjCMethodFamilyAttr *A)
void VisitObjCOwnershipAttr (const ObjCOwnershipAttr *A)
void VisitObjCRuntimeNameAttr (const ObjCRuntimeNameAttr *A)
void VisitOpenCLAccessAttr (const OpenCLAccessAttr *A)
void VisitOpenCLConstantAddressSpaceAttr (const OpenCLConstantAddressSpaceAttr *A)
void VisitOpenCLGenericAddressSpaceAttr (const OpenCLGenericAddressSpaceAttr *A)
void VisitOpenCLGlobalAddressSpaceAttr (const OpenCLGlobalAddressSpaceAttr *A)
void VisitOpenCLIntelReqdSubGroupSizeAttr (const OpenCLIntelReqdSubGroupSizeAttr *A)
void VisitOpenCLLocalAddressSpaceAttr (const OpenCLLocalAddressSpaceAttr *A)
void VisitOpenCLPrivateAddressSpaceAttr (const OpenCLPrivateAddressSpaceAttr *A)
void VisitOpenCLUnrollHintAttr (const OpenCLUnrollHintAttr *A)
void VisitOwnerAttr (const OwnerAttr *A)
void VisitOwnershipAttr (const OwnershipAttr *A)
void VisitParamTypestateAttr (const ParamTypestateAttr *A)
void VisitPassObjectSizeAttr (const PassObjectSizeAttr *A)
void VisitPatchableFunctionEntryAttr (const PatchableFunctionEntryAttr *A)
void VisitPcsAttr (const PcsAttr *A)
void VisitPointerAttr (const PointerAttr *A)
void VisitPragmaClangBSSSectionAttr (const PragmaClangBSSSectionAttr *A)
void VisitPragmaClangDataSectionAttr (const PragmaClangDataSectionAttr *A)
void VisitPragmaClangRelroSectionAttr (const PragmaClangRelroSectionAttr *A)
void VisitPragmaClangRodataSectionAttr (const PragmaClangRodataSectionAttr *A)
void VisitPragmaClangTextSectionAttr (const PragmaClangTextSectionAttr *A)
void VisitPreferredNameAttr (const PreferredNameAttr *A)
void VisitRISCVInterruptAttr (const RISCVInterruptAttr *A)
void VisitReleaseCapabilityAttr (const ReleaseCapabilityAttr *A)
void VisitReleaseHandleAttr (const ReleaseHandleAttr *A)
void VisitReqdWorkGroupSizeAttr (const ReqdWorkGroupSizeAttr *A)
void VisitRequiresCapabilityAttr (const RequiresCapabilityAttr *A)
void VisitRestrictAttr (const RestrictAttr *A)
void VisitReturnTypestateAttr (const ReturnTypestateAttr *A)
void VisitSectionAttr (const SectionAttr *A)
void VisitSentinelAttr (const SentinelAttr *A)
void VisitSetTypestateAttr (const SetTypestateAttr *A)
void VisitSuppressAttr (const SuppressAttr *A)
void VisitSwiftAsyncAttr (const SwiftAsyncAttr *A)
void VisitSwiftAsyncNameAttr (const SwiftAsyncNameAttr *A)
void VisitSwiftAttrAttr (const SwiftAttrAttr *A)
void VisitSwiftBridgeAttr (const SwiftBridgeAttr *A)
void VisitSwiftErrorAttr (const SwiftErrorAttr *A)
void VisitSwiftNameAttr (const SwiftNameAttr *A)
void VisitSwiftNewTypeAttr (const SwiftNewTypeAttr *A)
void VisitTLSModelAttr (const TLSModelAttr *A)
void VisitTargetAttr (const TargetAttr *A)
void VisitTestTypestateAttr (const TestTypestateAttr *A)
void VisitTryAcquireCapabilityAttr (const TryAcquireCapabilityAttr *A)
void VisitTypeTagForDatatypeAttr (const TypeTagForDatatypeAttr *A)
void VisitTypeVisibilityAttr (const TypeVisibilityAttr *A)
void VisitUnavailableAttr (const UnavailableAttr *A)
void VisitUnusedAttr (const UnusedAttr *A)
void VisitUseHandleAttr (const UseHandleAttr *A)
void VisitUuidAttr (const UuidAttr *A)
void VisitVecTypeHintAttr (const VecTypeHintAttr *A)
void VisitVisibilityAttr (const VisibilityAttr *A)
void VisitWarnUnusedResultAttr (const WarnUnusedResultAttr *A)
void VisitWeakRefAttr (const WeakRefAttr *A)
void VisitWebAssemblyExportNameAttr (const WebAssemblyExportNameAttr *A)
void VisitWebAssemblyImportModuleAttr (const WebAssemblyImportModuleAttr *A)
void VisitWebAssemblyImportNameAttr (const WebAssemblyImportNameAttr *A)
void VisitWorkGroupSizeHintAttr (const WorkGroupSizeHintAttr *A)
void VisitXRayInstrumentAttr (const XRayInstrumentAttr *A)
void VisitXRayLogArgsAttr (const XRayLogArgsAttr *A)
void VisitNullTemplateArgument (const TemplateArgument &TA)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitDeclarationTemplateArgument (const TemplateArgument &TA)
void VisitNullPtrTemplateArgument (const TemplateArgument &TA)
void VisitIntegralTemplateArgument (const TemplateArgument &TA)
void VisitTemplateTemplateArgument (const TemplateArgument &TA)
void VisitTemplateExpansionTemplateArgument (const TemplateArgument &TA)
void VisitExpressionTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
void VisitIfStmt (const IfStmt *Node)
void VisitSwitchStmt (const SwitchStmt *Node)
void VisitWhileStmt (const WhileStmt *Node)
void VisitLabelStmt (const LabelStmt *Node)
void VisitGotoStmt (const GotoStmt *Node)
void VisitCaseStmt (const CaseStmt *Node)
void VisitConstantExpr (const ConstantExpr *Node)
void VisitCallExpr (const CallExpr *Node)
void VisitCXXOperatorCallExpr (const CXXOperatorCallExpr *Node)
void VisitCastExpr (const CastExpr *Node)
void VisitImplicitCastExpr (const ImplicitCastExpr *Node)
void VisitDeclRefExpr (const DeclRefExpr *Node)
void VisitPredefinedExpr (const PredefinedExpr *Node)
void VisitCharacterLiteral (const CharacterLiteral *Node)
void VisitIntegerLiteral (const IntegerLiteral *Node)
void VisitFixedPointLiteral (const FixedPointLiteral *Node)
void VisitFloatingLiteral (const FloatingLiteral *Node)
void VisitStringLiteral (const StringLiteral *Str)
void VisitInitListExpr (const InitListExpr *ILE)
void VisitGenericSelectionExpr (const GenericSelectionExpr *E)
void VisitUnaryOperator (const UnaryOperator *Node)
void VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr *Node)
void VisitMemberExpr (const MemberExpr *Node)
void VisitExtVectorElementExpr (const ExtVectorElementExpr *Node)
void VisitBinaryOperator (const BinaryOperator *Node)
void VisitCompoundAssignOperator (const CompoundAssignOperator *Node)
void VisitAddrLabelExpr (const AddrLabelExpr *Node)
void VisitCXXNamedCastExpr (const CXXNamedCastExpr *Node)
void VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr *Node)
void VisitCXXThisExpr (const CXXThisExpr *Node)
void VisitCXXFunctionalCastExpr (const CXXFunctionalCastExpr *Node)
void VisitCXXStaticCastExpr (const CXXStaticCastExpr *Node)
void VisitCXXUnresolvedConstructExpr (const CXXUnresolvedConstructExpr *Node)
void VisitCXXConstructExpr (const CXXConstructExpr *Node)
void VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *Node)
void VisitCXXNewExpr (const CXXNewExpr *Node)
void VisitCXXDeleteExpr (const CXXDeleteExpr *Node)
void VisitTypeTraitExpr (const TypeTraitExpr *Node)
void VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr *Node)
void VisitExpressionTraitExpr (const ExpressionTraitExpr *Node)
void VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *Node)
void VisitExprWithCleanups (const ExprWithCleanups *Node)
void VisitUnresolvedLookupExpr (const UnresolvedLookupExpr *Node)
void VisitSizeOfPackExpr (const SizeOfPackExpr *Node)
void VisitCXXDependentScopeMemberExpr (const CXXDependentScopeMemberExpr *Node)
void VisitObjCAtCatchStmt (const ObjCAtCatchStmt *Node)
void VisitObjCEncodeExpr (const ObjCEncodeExpr *Node)
void VisitObjCMessageExpr (const ObjCMessageExpr *Node)
void VisitObjCBoxedExpr (const ObjCBoxedExpr *Node)
void VisitObjCSelectorExpr (const ObjCSelectorExpr *Node)
void VisitObjCProtocolExpr (const ObjCProtocolExpr *Node)
void VisitObjCPropertyRefExpr (const ObjCPropertyRefExpr *Node)
void VisitObjCSubscriptRefExpr (const ObjCSubscriptRefExpr *Node)
void VisitObjCIvarRefExpr (const ObjCIvarRefExpr *Node)
void VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr *Node)
void VisitOMPIteratorExpr (const OMPIteratorExpr *Node)
void VisitConceptSpecializationExpr (const ConceptSpecializationExpr *Node)
void VisitRValueReferenceType (const ReferenceType *T)
void VisitArrayType (const ArrayType *T)
void VisitConstantArrayType (const ConstantArrayType *T)
void VisitVariableArrayType (const VariableArrayType *T)
void VisitDependentSizedArrayType (const DependentSizedArrayType *T)
void VisitDependentSizedExtVectorType (const DependentSizedExtVectorType *T)
void VisitVectorType (const VectorType *T)
void VisitFunctionType (const FunctionType *T)
void VisitFunctionProtoType (const FunctionProtoType *T)
void VisitUnresolvedUsingType (const UnresolvedUsingType *T)
void VisitTypedefType (const TypedefType *T)
void VisitUnaryTransformType (const UnaryTransformType *T)
void VisitTagType (const TagType *T)
void VisitTemplateTypeParmType (const TemplateTypeParmType *T)
void VisitAutoType (const AutoType *T)
void VisitTemplateSpecializationType (const TemplateSpecializationType *T)
void VisitInjectedClassNameType (const InjectedClassNameType *T)
void VisitObjCInterfaceType (const ObjCInterfaceType *T)
void VisitPackExpansionType (const PackExpansionType *T)
void VisitLabelDecl (const LabelDecl *D)
void VisitTypedefDecl (const TypedefDecl *D)
void VisitEnumDecl (const EnumDecl *D)
void VisitRecordDecl (const RecordDecl *D)
void VisitEnumConstantDecl (const EnumConstantDecl *D)
void VisitIndirectFieldDecl (const IndirectFieldDecl *D)
void VisitFunctionDecl (const FunctionDecl *D)
void VisitFieldDecl (const FieldDecl *D)
void VisitVarDecl (const VarDecl *D)
void VisitBindingDecl (const BindingDecl *D)
void VisitCapturedDecl (const CapturedDecl *D)
void VisitImportDecl (const ImportDecl *D)
void VisitPragmaCommentDecl (const PragmaCommentDecl *D)
void VisitPragmaDetectMismatchDecl (const PragmaDetectMismatchDecl *D)
void VisitOMPExecutableDirective (const OMPExecutableDirective *D)
void VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl *D)
void VisitOMPRequiresDecl (const OMPRequiresDecl *D)
void VisitOMPCapturedExprDecl (const OMPCapturedExprDecl *D)
void VisitNamespaceDecl (const NamespaceDecl *D)
void VisitUsingDirectiveDecl (const UsingDirectiveDecl *D)
void VisitNamespaceAliasDecl (const NamespaceAliasDecl *D)
void VisitTypeAliasDecl (const TypeAliasDecl *D)
void VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl *D)
void VisitCXXRecordDecl (const CXXRecordDecl *D)
void VisitFunctionTemplateDecl (const FunctionTemplateDecl *D)
void VisitClassTemplateDecl (const ClassTemplateDecl *D)
void VisitBuiltinTemplateDecl (const BuiltinTemplateDecl *D)
void VisitVarTemplateDecl (const VarTemplateDecl *D)
void VisitTemplateTypeParmDecl (const TemplateTypeParmDecl *D)
void VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl *D)
void VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl *D)
void VisitUsingDecl (const UsingDecl *D)
void VisitUnresolvedUsingTypenameDecl (const UnresolvedUsingTypenameDecl *D)
void VisitUnresolvedUsingValueDecl (const UnresolvedUsingValueDecl *D)
void VisitUsingShadowDecl (const UsingShadowDecl *D)
void VisitConstructorUsingShadowDecl (const ConstructorUsingShadowDecl *D)
void VisitLinkageSpecDecl (const LinkageSpecDecl *D)
void VisitAccessSpecDecl (const AccessSpecDecl *D)
void VisitFriendDecl (const FriendDecl *D)
void VisitObjCIvarDecl (const ObjCIvarDecl *D)
void VisitObjCMethodDecl (const ObjCMethodDecl *D)
void VisitObjCTypeParamDecl (const ObjCTypeParamDecl *D)
void VisitObjCCategoryDecl (const ObjCCategoryDecl *D)
void VisitObjCCategoryImplDecl (const ObjCCategoryImplDecl *D)
void VisitObjCProtocolDecl (const ObjCProtocolDecl *D)
void VisitObjCInterfaceDecl (const ObjCInterfaceDecl *D)
void VisitObjCImplementationDecl (const ObjCImplementationDecl *D)
void VisitObjCCompatibleAliasDecl (const ObjCCompatibleAliasDecl *D)
void VisitObjCPropertyDecl (const ObjCPropertyDecl *D)
void VisitObjCPropertyImplDecl (const ObjCPropertyImplDecl *D)
void VisitBlockDecl (const BlockDecl *D)
void VisitConceptDecl (const ConceptDecl *D)
void VisitLifetimeExtendedTemporaryDecl (const LifetimeExtendedTemporaryDecl *D)
Public Member Functions inherited from clang::TextTreeStructure
template<typename Fn >
void AddChild (Fn DoAddChild)
Add a child of the current node. Calls DoAddChild without arguments.
template<typename Fn >
void AddChild (StringRef Label, Fn DoAddChild)
Add a child of the current node with an optional label.
TextTreeStructure (raw_ostream &OS, bool ShowColors)
Public Member Functions inherited from clang::comments::CommentVisitorBase< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >
void visit (PTR(Comment) C, ParamTys... P)
void visitComment (PTR(Comment) C, ParamTys... P)
Public Member Functions inherited from clang::attrvisitor::Base< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >
void Visit (PTR(Attr) A)
void VisitAttr (PTR(Attr))
Public Member Functions inherited from clang::templateargumentvisitor::Base< llvm::make_const_ref, TextNodeDumper, void, ParamTys... >
void Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
void VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Public Member Functions inherited from clang::StmtVisitorBase< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Public Member Functions inherited from clang::TypeVisitor< TextNodeDumper >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::declvisitor::Base< llvm::make_const_ptr, TextNodeDumper, void >
void Visit (PTR(Decl) D)
void VisitDecl (PTR(Decl) D)
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >
ParamTys P
Detailed Description
Definition at line 128 of file TextNodeDumper.h.
Constructor & Destructor Documentation
TextNodeDumper() [1/2]
TextNodeDumper::TextNodeDumper (raw_ostream & OS, const ASTContext & Context, bool ShowColors)
Definition at line 59 of file TextNodeDumper.cpp.
Referenced by Visit().
TextNodeDumper() [2/2]
TextNodeDumper::TextNodeDumper (raw_ostream & OS, bool ShowColors)
Definition at line 66 of file TextNodeDumper.cpp.
Member Function Documentation
dumpAccessSpecifier()
void TextNodeDumper::dumpAccessSpecifier (AccessSpecifier AS)
Definition at line 668 of file TextNodeDumper.cpp.
References clang::getAccessSpelling().
Referenced by VisitAccessSpecDecl(), and VisitCXXRecordDecl().
dumpBareDeclRef()
void TextNodeDumper::dumpBareDeclRef (const Decl * D)
Definition at line 639 of file TextNodeDumper.cpp.
References clang::DeclKindNameColor, clang::DeclNameColor, dumpPointer(), dumpType(), clang::Decl::getDeclKindName(), and clang::NullColor.
Referenced by dumpDeclRef(), clang::ASTDumper::dumpLookups(), Visit(), Visit(), VisitConceptSpecializationExpr(), VisitConstructorUsingShadowDecl(), VisitCXXDeleteExpr(), VisitCXXNewExpr(), VisitDeclRefExpr(), VisitInitListExpr(), VisitLifetimeExtendedTemporaryDecl(), VisitMaterializeTemporaryExpr(), VisitTemplateTypeParmDecl(), VisitUsingDirectiveDecl(), and VisitUsingShadowDecl().
dumpBareType()
void TextNodeDumper::dumpBareType (QualType T, bool Desugar = true)
Definition at line 620 of file TextNodeDumper.cpp.
References Desugar(), clang::QualType::getAsString(), clang::QualType::isNull(), and clang::TypeColor.
Referenced by dumpType(), Visit(), Visit(), VisitCompoundAssignOperator(), and VisitObjCMessageExpr().
dumpCleanupObject()
void TextNodeDumper::dumpCleanupObject (const ExprWithCleanups::CleanupObject & C)
Definition at line 675 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::C, dumpDeclRef(), dumpPointer(), and clang::StmtColor.
Referenced by VisitExprWithCleanups().
dumpDeclRef()
void TextNodeDumper::dumpDeclRef (const Decl * D, StringRef Label = {})
Definition at line 692 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), dumpBareDeclRef(), and Label.
Referenced by dumpCleanupObject(), clang::ASTDumper::dumpTemplateDeclSpecialization(), Visit(), VisitAutoType(), VisitDeclarationTemplateArgument(), VisitImportDecl(), VisitIndirectFieldDecl(), VisitInjectedClassNameType(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitObjCCategoryDecl(), VisitObjCCategoryImplDecl(), VisitObjCCompatibleAliasDecl(), VisitObjCImplementationDecl(), VisitObjCInterfaceDecl(), VisitObjCInterfaceType(), VisitObjCPropertyDecl(), VisitObjCPropertyImplDecl(), VisitObjCProtocolDecl(), VisitTagType(), VisitTemplateTypeParmType(), VisitTypedefType(), and VisitUnresolvedUsingType().
dumpLocation()
void TextNodeDumper::dumpLocation (SourceLocation Loc)
Definition at line 575 of file TextNodeDumper.cpp.
References clang::PresumedLoc::getColumn(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::SourceManager::getPresumedLoc(), clang::SourceManager::getSpellingLoc(), clang::PresumedLoc::isInvalid(), and clang::LocationColor.
Referenced by dumpSourceRange(), Visit(), and VisitDependentSizedExtVectorType().
dumpName()
void TextNodeDumper::dumpName (const NamedDecl * ND)
Definition at line 661 of file TextNodeDumper.cpp.
References clang::DeclNameColor, and clang::NamedDecl::getDeclName().
Referenced by VisitBindingDecl(), VisitBuiltinTemplateDecl(), VisitClassTemplateDecl(), VisitConceptDecl(), VisitEnumConstantDecl(), VisitEnumDecl(), VisitFieldDecl(), VisitFunctionDecl(), VisitFunctionTemplateDecl(), VisitIndirectFieldDecl(), VisitLabelDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitNonTypeTemplateParmDecl(), VisitObjCCategoryDecl(), VisitObjCCategoryImplDecl(), VisitObjCCompatibleAliasDecl(), VisitObjCImplementationDecl(), VisitObjCInterfaceDecl(), VisitObjCIvarDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitObjCPropertyImplDecl(), VisitObjCProtocolDecl(), VisitObjCTypeParamDecl(), VisitOMPCapturedExprDecl(), VisitOMPDeclareReductionDecl(), VisitRecordDecl(), VisitSizeOfPackExpr(), VisitTemplateTemplateParmDecl(), VisitTemplateTypeParmDecl(), VisitTypeAliasDecl(), VisitTypeAliasTemplateDecl(), VisitTypedefDecl(), VisitVarDecl(), and VisitVarTemplateDecl().
dumpPointer()
void TextNodeDumper::dumpPointer (const void * Ptr)
Definition at line 570 of file TextNodeDumper.cpp.
References clang::AddressColor.
Referenced by dumpBareDeclRef(), dumpCleanupObject(), clang::ASTDumper::dumpLookups(), Visit(), Visit(), Visit(), Visit(), Visit(), Visit(), Visit(), VisitAddrLabelExpr(), VisitCXXBindTemporaryExpr(), VisitGotoStmt(), VisitMemberExpr(), VisitObjCIvarRefExpr(), VisitOMPDeclareReductionDecl(), VisitOMPRequiresDecl(), VisitSizeOfPackExpr(), and VisitUnresolvedLookupExpr().
dumpSourceRange()
void TextNodeDumper::dumpSourceRange (SourceRange R)
Definition at line 604 of file TextNodeDumper.cpp.
References dumpLocation(), clang::SourceRange::getBegin(), and clang::SourceRange::getEnd().
Referenced by Visit(), Visit(), Visit(), Visit(), Visit(), Visit(), VisitDependentSizedArrayType(), VisitOMPRequiresDecl(), and VisitVariableArrayType().
dumpType()
void TextNodeDumper::dumpType (QualType T)
Definition at line 634 of file TextNodeDumper.cpp.
References dumpBareType().
Referenced by dumpBareDeclRef(), Visit(), Visit(), Visit(), VisitBindingDecl(), VisitCXXConstructExpr(), VisitCXXRecordDecl(), VisitCXXUnresolvedConstructExpr(), VisitEnumConstantDecl(), VisitEnumDecl(), VisitFieldDecl(), VisitFriendDecl(), VisitFunctionDecl(), VisitIndirectFieldDecl(), VisitNonTypeTemplateParmDecl(), VisitObjCEncodeExpr(), VisitObjCIvarDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitObjCTypeParamDecl(), VisitOMPCapturedExprDecl(), VisitOMPDeclareReductionDecl(), VisitTypeAliasDecl(), VisitTypedefDecl(), VisitTypeTemplateArgument(), VisitUnaryExprOrTypeTraitExpr(), VisitUnresolvedUsingValueDecl(), and VisitVarDecl().
Visit() [1/12]
void TextNodeDumper::Visit (const APValue & Value, QualType Ty)
Definition at line 436 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::cast(), clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::APValue::FixedPoint, clang::APValue::Float, GetApproxValue(), clang::APValue::getStructNumBases(), clang::APValue::getStructNumFields(), clang::APValue::getUnionValue(), clang::APValue::Indeterminate, clang::APValue::Int, isSimpleAPValue(), clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, clang::APValue::Struct, clang::APValue::Union, clang::ValueColor, clang::ValueKindColor, clang::APValue::Vector, and Visit().
Visit() [2/12]
void TextNodeDumper::Visit (const Attr * A)
Definition at line 88 of file TextNodeDumper.cpp.
References clang::AttrColor, dumpPointer(), dumpSourceRange(), clang::Attr::getKind(), clang::AttributeCommonInfo::getRange(), clang::Attr::isImplicit(), clang::Attr::isInherited(), and clang::attrvisitor::Base< llvm::make_const_ptr, ImplClass, void, ParamTys... >::Visit().
Visit() [3/12]
void TextNodeDumper::Visit (const BlockDecl::Capture & C)
Definition at line 315 of file TextNodeDumper.cpp.
References clang::C, and dumpBareDeclRef().
Visit() [4/12]
void TextNodeDumper::Visit (const comments::Comment * C, const comments::FullComment * FC)
Definition at line 69 of file TextNodeDumper.cpp.
References clang::C, clang::CommentColor, dumpPointer(), dumpSourceRange(), clang::NullColor, TextNodeDumper(), and clang::comments::CommentVisitorBase< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >::visit().
Referenced by Visit(), VisitConstantExpr(), VisitOMPIteratorExpr(), and VisitVarDecl().
Visit() [5/12]
void TextNodeDumper::Visit (const CXXCtorInitializer * Init)
Definition at line 301 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and dumpType().
Visit() [6/12]
void TextNodeDumper::Visit (const Decl * D)
Definition at line 241 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::cast(), clang::DeclKindNameColor, dumpLocation(), dumpPointer(), dumpPreviousDecl(), dumpSourceRange(), clang::Decl::getASTContext(), clang::Decl::getDeclContext(), clang::Decl::getDeclKindName(), clang::Decl::getLexicalDeclContext(), clang::Decl::getLocation(), clang::ASTContext::getModulesWithMergedDefinition(), clang::Decl::getOwningModule(), clang::Decl::getSourceRange(), clang::Decl::isFromASTFile(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::Decl::isThisDeclarationReferenced(), clang::Decl::isUsed(), clang::NullColor, clang::UndeserializedColor, and clang::declvisitor::Base< llvm::make_const_ptr, ImplClass, void >::Visit().
Visit() [7/12]
void TextNodeDumper::Visit (const GenericSelectionExpr::ConstAssociation & A)
Definition at line 345 of file TextNodeDumper.cpp.
References dumpType(), and clang::TypeSourceInfo::getType().
Visit() [8/12]
void TextNodeDumper::Visit (const OMPClause * C)
Definition at line 327 of file TextNodeDumper.cpp.
References clang::AttrColor, clang::C, dumpPointer(), dumpSourceRange(), and clang::NullColor.
Visit() [9/12]
void TextNodeDumper::Visit (const Stmt * Node)
Definition at line 123 of file TextNodeDumper.cpp.
References dumpPointer(), dumpSourceRange(), dumpType(), clang::ErrorsColor, clang::DynTypedNode::getSourceRange(), Node, clang::NullColor, clang::ObjectKindColor, clang::OK_BitField, clang::OK_MatrixComponent, clang::OK_ObjCProperty, clang::OK_ObjCSubscript, clang::OK_Ordinary, clang::OK_VectorComponent, clang::StmtColor, clang::ValueKindColor, clang::StmtVisitorBase< llvm::make_const_ptr, ImplClass, void, ParamTys... >::Visit(), clang::VK_LValue, clang::VK_RValue, and clang::VK_XValue.
Visit() [10/12]
void TextNodeDumper::Visit (const TemplateArgument & TA, SourceRange R, const Decl * From = nullptr, StringRef Label = {})
Definition at line 111 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpSourceRange(), clang::SourceRange::isValid(), Label, and clang::templateargumentvisitor::Base< llvm::make_const_ref, ImplClass, void, ParamTys... >::Visit().
Visit() [11/12]
void TextNodeDumper::Visit (const Type * T)
Definition at line 185 of file TextNodeDumper.cpp.
References dumpBareType(), dumpPointer(), clang::ErrorsColor, clang::Type::getLocallyUnqualifiedSingleStepDesugaredType(), clang::NullColor, clang::TypeColor, and clang::TypeVisitor< ImplClass, RetTy >::Visit().
Visit() [12/12]
void TextNodeDumper::Visit (QualType T)
Definition at line 233 of file TextNodeDumper.cpp.
References dumpBareType(), and dumpPointer().
VisitAbiTagAttr()
void clang::TextNodeDumper::VisitAbiTagAttr (const AbiTagAttr * A) inline
Definition at line 41 of file TextNodeDumper.h.
VisitAccessSpecDecl()
void TextNodeDumper::VisitAccessSpecDecl (const AccessSpecDecl * D)
Definition at line 2112 of file TextNodeDumper.cpp.
References dumpAccessSpecifier(), and clang::Decl::getAccess().
VisitAcquireCapabilityAttr()
void clang::TextNodeDumper::VisitAcquireCapabilityAttr (const AcquireCapabilityAttr * A) inline
Definition at line 46 of file TextNodeDumper.h.
VisitAcquireHandleAttr()
void clang::TextNodeDumper::VisitAcquireHandleAttr (const AcquireHandleAttr * A) inline
Definition at line 50 of file TextNodeDumper.h.
VisitAddressSpaceAttr()
void clang::TextNodeDumper::VisitAddressSpaceAttr (const AddressSpaceAttr * A) inline
Definition at line 54 of file TextNodeDumper.h.
VisitAddrLabelExpr()
void TextNodeDumper::VisitAddrLabelExpr (const AddrLabelExpr * Node)
Definition at line 1112 of file TextNodeDumper.cpp.
References dumpPointer(), and Node.
VisitAliasAttr()
void clang::TextNodeDumper::VisitAliasAttr (const AliasAttr * A) inline
Definition at line 58 of file TextNodeDumper.h.
VisitAlignedAttr()
void clang::TextNodeDumper::VisitAlignedAttr (const AlignedAttr * A) inline
Definition at line 62 of file TextNodeDumper.h.
VisitAllocAlignAttr()
void clang::TextNodeDumper::VisitAllocAlignAttr (const AllocAlignAttr * A) inline
Definition at line 68 of file TextNodeDumper.h.
VisitAllocSizeAttr()
void clang::TextNodeDumper::VisitAllocSizeAttr (const AllocSizeAttr * A) inline
Definition at line 72 of file TextNodeDumper.h.
VisitAlwaysInlineAttr()
void clang::TextNodeDumper::VisitAlwaysInlineAttr (const AlwaysInlineAttr * A) inline
Definition at line 78 of file TextNodeDumper.h.
VisitAMDGPUNumSGPRAttr()
void clang::TextNodeDumper::VisitAMDGPUNumSGPRAttr (const AMDGPUNumSGPRAttr * A) inline
Definition at line 10 of file TextNodeDumper.h.
VisitAMDGPUNumVGPRAttr()
void clang::TextNodeDumper::VisitAMDGPUNumVGPRAttr (const AMDGPUNumVGPRAttr * A) inline
Definition at line 14 of file TextNodeDumper.h.
VisitAnnotateAttr()
void clang::TextNodeDumper::VisitAnnotateAttr (const AnnotateAttr * A) inline
Definition at line 81 of file TextNodeDumper.h.
VisitArgumentWithTypeTagAttr()
void clang::TextNodeDumper::VisitArgumentWithTypeTagAttr (const ArgumentWithTypeTagAttr * A) inline
Definition at line 85 of file TextNodeDumper.h.
References clang::IndentColor.
VisitArmBuiltinAliasAttr()
void clang::TextNodeDumper::VisitArmBuiltinAliasAttr (const ArmBuiltinAliasAttr * A) inline
Definition at line 94 of file TextNodeDumper.h.
VisitARMInterruptAttr()
void clang::TextNodeDumper::VisitARMInterruptAttr (const ARMInterruptAttr * A) inline
Definition at line 18 of file TextNodeDumper.h.
VisitArrayType()
void TextNodeDumper::VisitArrayType (const ArrayType * T)
Definition at line 1366 of file TextNodeDumper.cpp.
References clang::ArrayType::Normal, clang::ArrayType::Star, and clang::ArrayType::Static.
Referenced by VisitConstantArrayType(), VisitDependentSizedArrayType(), and VisitVariableArrayType().
VisitArrayTypeTraitExpr()
void TextNodeDumper::VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr * Node)
Definition at line 1204 of file TextNodeDumper.cpp.
References clang::getTraitSpelling(), and Node.
VisitAsmLabelAttr()
void clang::TextNodeDumper::VisitAsmLabelAttr (const AsmLabelAttr * A) inline
Definition at line 99 of file TextNodeDumper.h.
VisitAssertCapabilityAttr()
void clang::TextNodeDumper::VisitAssertCapabilityAttr (const AssertCapabilityAttr * A) inline
Definition at line 104 of file TextNodeDumper.h.
VisitAssumptionAttr()
void clang::TextNodeDumper::VisitAssumptionAttr (const AssumptionAttr * A) inline
Definition at line 108 of file TextNodeDumper.h.
VisitAutoType()
void TextNodeDumper::VisitAutoType (const AutoType * T)
Definition at line 1498 of file TextNodeDumper.cpp.
References dumpDeclRef(), and clang::templateargumentvisitor::Base< llvm::make_const_ref, TextNodeDumper, void, ParamTys... >::VisitTemplateArgument().
VisitAvailabilityAttr()
void clang::TextNodeDumper::VisitAvailabilityAttr (const AvailabilityAttr * A) inline
Definition at line 112 of file TextNodeDumper.h.
VisitBinaryOperator()
void TextNodeDumper::VisitBinaryOperator (const BinaryOperator * Node)
Definition at line 1095 of file TextNodeDumper.cpp.
References clang::BinaryOperator::getOpcodeStr(), and Node.
VisitBindingDecl()
void TextNodeDumper::VisitBindingDecl (const BindingDecl * D)
Definition at line 1720 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), and clang::ValueDecl::getType().
visitBlockCommandComment()
void TextNodeDumper::visitBlockCommandComment (const comments::BlockCommandComment * C, const comments::FullComment *)
Definition at line 769 of file TextNodeDumper.cpp.
References clang::C.
VisitBlockDecl()
void TextNodeDumper::VisitBlockDecl (const BlockDecl * D)
Definition at line 2274 of file TextNodeDumper.cpp.
References clang::BlockDecl::capturesCXXThis(), and clang::BlockDecl::isVariadic().
VisitBlocksAttr()
void clang::TextNodeDumper::VisitBlocksAttr (const BlocksAttr * A) inline
Definition at line 125 of file TextNodeDumper.h.
VisitBuiltinAttr()
void clang::TextNodeDumper::VisitBuiltinAttr (const BuiltinAttr * A) inline
Definition at line 133 of file TextNodeDumper.h.
VisitBuiltinTemplateDecl()
void TextNodeDumper::VisitBuiltinTemplateDecl (const BuiltinTemplateDecl * D)
Definition at line 2007 of file TextNodeDumper.cpp.
References dumpName().
VisitCallableWhenAttr()
void clang::TextNodeDumper::VisitCallableWhenAttr (const CallableWhenAttr * A) inline
Definition at line 155 of file TextNodeDumper.h.
VisitCallbackAttr()
void clang::TextNodeDumper::VisitCallbackAttr (const CallbackAttr * A) inline
Definition at line 171 of file TextNodeDumper.h.
VisitCallExpr()
void TextNodeDumper::VisitCallExpr (const CallExpr * Node)
Definition at line 944 of file TextNodeDumper.cpp.
References Node.
Referenced by VisitCXXOperatorCallExpr().
VisitCapabilityAttr()
void clang::TextNodeDumper::VisitCapabilityAttr (const CapabilityAttr * A) inline
Definition at line 176 of file TextNodeDumper.h.
VisitCapturedDecl()
void TextNodeDumper::VisitCapturedDecl (const CapturedDecl * D)
Definition at line 1725 of file TextNodeDumper.cpp.
References clang::CapturedDecl::isNothrow().
VisitCaseStmt()
void TextNodeDumper::VisitCaseStmt (const CaseStmt * Node)
Definition at line 933 of file TextNodeDumper.cpp.
References Node.
VisitCastExpr()
void TextNodeDumper::VisitCastExpr (const CastExpr * Node)
Definition at line 959 of file TextNodeDumper.cpp.
References clang::CastColor, dumpBasePath(), and Node.
Referenced by VisitImplicitCastExpr().
VisitCFGuardAttr()
void clang::TextNodeDumper::VisitCFGuardAttr (const CFGuardAttr * A) inline
Definition at line 137 of file TextNodeDumper.h.
VisitCharacterLiteral()
void TextNodeDumper::VisitCharacterLiteral (const CharacterLiteral * Node)
Definition at line 1023 of file TextNodeDumper.cpp.
References Node, and clang::ValueColor.
VisitClassTemplateDecl()
void TextNodeDumper::VisitClassTemplateDecl (const ClassTemplateDecl * D)
Definition at line 1999 of file TextNodeDumper.cpp.
References dumpName().
VisitCleanupAttr()
void clang::TextNodeDumper::VisitCleanupAttr (const CleanupAttr * A) inline
Definition at line 181 of file TextNodeDumper.h.
VisitCodeSegAttr()
void clang::TextNodeDumper::VisitCodeSegAttr (const CodeSegAttr * A) inline
Definition at line 186 of file TextNodeDumper.h.
VisitCompoundAssignOperator()
void TextNodeDumper::VisitCompoundAssignOperator (const CompoundAssignOperator * Node)
Definition at line 1101 of file TextNodeDumper.cpp.
References dumpBareType(), clang::BinaryOperator::getOpcodeStr(), and Node.
VisitConceptDecl()
void TextNodeDumper::VisitConceptDecl (const ConceptDecl * D)
Definition at line 2282 of file TextNodeDumper.cpp.
References dumpName().
VisitConceptSpecializationExpr()
void TextNodeDumper::VisitConceptSpecializationExpr (const ConceptSpecializationExpr * Node)
Definition at line 1355 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and Node.
VisitConstantArrayType()
void TextNodeDumper::VisitConstantArrayType (const ConstantArrayType * T)
Definition at line 1380 of file TextNodeDumper.cpp.
References VisitArrayType().
VisitConstantExpr()
void TextNodeDumper::VisitConstantExpr (const ConstantExpr * Node)
Definition at line 938 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), Node, and Visit().
VisitConstInitAttr()
void clang::TextNodeDumper::VisitConstInitAttr (const ConstInitAttr * A) inline
Definition at line 190 of file TextNodeDumper.h.
VisitConstructorAttr()
void clang::TextNodeDumper::VisitConstructorAttr (const ConstructorAttr * A) inline
Definition at line 193 of file TextNodeDumper.h.
VisitConstructorUsingShadowDecl()
void TextNodeDumper::VisitConstructorUsingShadowDecl (const ConstructorUsingShadowDecl * D)
Definition at line 2076 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::ConstructorUsingShadowDecl::constructsVirtualBase(), dumpBareDeclRef(), clang::ConstructorUsingShadowDecl::getConstructedBaseClass(), clang::ConstructorUsingShadowDecl::getConstructedBaseClassShadowDecl(), clang::ConstructorUsingShadowDecl::getNominatedBaseClass(), clang::ConstructorUsingShadowDecl::getNominatedBaseClassShadowDecl(), and clang::UsingShadowDecl::getTargetDecl().
VisitConsumableAttr()
void clang::TextNodeDumper::VisitConsumableAttr (const ConsumableAttr * A) inline
Definition at line 197 of file TextNodeDumper.h.
VisitCPUDispatchAttr()
void clang::TextNodeDumper::VisitCPUDispatchAttr (const CPUDispatchAttr * A) inline
Definition at line 145 of file TextNodeDumper.h.
VisitCPUSpecificAttr()
void clang::TextNodeDumper::VisitCPUSpecificAttr (const CPUSpecificAttr * A) inline
Definition at line 150 of file TextNodeDumper.h.
VisitCXXBindTemporaryExpr()
void TextNodeDumper::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * Node)
Definition at line 1169 of file TextNodeDumper.cpp.
References dumpPointer(), and Node.
VisitCXXBoolLiteralExpr()
void TextNodeDumper::VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr * Node)
Definition at line 1125 of file TextNodeDumper.cpp.
References Node.
VisitCXXConstructExpr()
void TextNodeDumper::VisitCXXConstructExpr (const CXXConstructExpr * Node)
Definition at line 1156 of file TextNodeDumper.cpp.
References dumpType(), clang::ValueDecl::getType(), and Node.
VisitCXXDeleteExpr()
void TextNodeDumper::VisitCXXDeleteExpr (const CXXDeleteExpr * Node)
Definition at line 1189 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and Node.
VisitCXXDependentScopeMemberExpr()
void TextNodeDumper::VisitCXXDependentScopeMemberExpr (const CXXDependentScopeMemberExpr * Node)
Definition at line 1230 of file TextNodeDumper.cpp.
References Node.
VisitCXXFunctionalCastExpr()
void TextNodeDumper::VisitCXXFunctionalCastExpr (const CXXFunctionalCastExpr * Node)
Definition at line 1135 of file TextNodeDumper.cpp.
References Node.
VisitCXXNamedCastExpr()
void TextNodeDumper::VisitCXXNamedCastExpr (const CXXNamedCastExpr * Node)
Definition at line 1117 of file TextNodeDumper.cpp.
References dumpBasePath(), and Node.
Referenced by VisitCXXStaticCastExpr().
VisitCXXNewExpr()
void TextNodeDumper::VisitCXXNewExpr (const CXXNewExpr * Node)
Definition at line 1176 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and Node.
VisitCXXOperatorCallExpr()
void TextNodeDumper::VisitCXXOperatorCallExpr (const CXXOperatorCallExpr * Node)
Definition at line 951 of file TextNodeDumper.cpp.
References clang::getOperatorSpelling(), Node, and VisitCallExpr().
VisitCXXRecordDecl()
void TextNodeDumper::VisitCXXRecordDecl (const CXXRecordDecl * D)
Definition at line 1851 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::CXXRecordDecl::bases(), canPassInRegisters(), clang::DeclKindNameColor, dumpAccessSpecifier(), dumpType(), FLAG, clang::TagDecl::isCompleteDefinition(), isTrivial(), clang::CXXRecordDecl::needsOverloadResolutionForCopyConstructor(), clang::CXXRecordDecl::needsOverloadResolutionForDestructor(), clang::CXXRecordDecl::needsOverloadResolutionForMoveConstructor(), and VisitRecordDecl().
VisitCXXStaticCastExpr()
void TextNodeDumper::VisitCXXStaticCastExpr (const CXXStaticCastExpr * Node)
Definition at line 1143 of file TextNodeDumper.cpp.
References Node, and VisitCXXNamedCastExpr().
VisitCXXThisExpr()
void TextNodeDumper::VisitCXXThisExpr (const CXXThisExpr * Node)
Definition at line 1129 of file TextNodeDumper.cpp.
References Node.
VisitCXXUnresolvedConstructExpr()
void TextNodeDumper::VisitCXXUnresolvedConstructExpr (const CXXUnresolvedConstructExpr * Node)
Definition at line 1149 of file TextNodeDumper.cpp.
References dumpType(), and Node.
VisitDeclarationTemplateArgument()
void TextNodeDumper::VisitDeclarationTemplateArgument (const TemplateArgument & TA)
Definition at line 845 of file TextNodeDumper.cpp.
References dumpDeclRef(), and clang::TemplateArgument::getAsDecl().
VisitDeclRefExpr()
void TextNodeDumper::VisitDeclRefExpr (const DeclRefExpr * Node)
Definition at line 977 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), Node, clang::NOUR_Constant, clang::NOUR_Discarded, clang::NOUR_None, and clang::NOUR_Unevaluated.
VisitDependentSizedArrayType()
void TextNodeDumper::VisitDependentSizedArrayType (const DependentSizedArrayType * T)
Definition at line 1391 of file TextNodeDumper.cpp.
References dumpSourceRange(), and VisitArrayType().
VisitDependentSizedExtVectorType()
void TextNodeDumper::VisitDependentSizedExtVectorType (const DependentSizedExtVectorType * T)
Definition at line 1398 of file TextNodeDumper.cpp.
References dumpLocation().
VisitDeprecatedAttr()
void clang::TextNodeDumper::VisitDeprecatedAttr (const DeprecatedAttr * A) inline
Definition at line 211 of file TextNodeDumper.h.
VisitDestructorAttr()
void clang::TextNodeDumper::VisitDestructorAttr (const DestructorAttr * A) inline
Definition at line 216 of file TextNodeDumper.h.
VisitDiagnoseIfAttr()
void clang::TextNodeDumper::VisitDiagnoseIfAttr (const DiagnoseIfAttr * A) inline
Definition at line 220 of file TextNodeDumper.h.
VisitEnableIfAttr()
void clang::TextNodeDumper::VisitEnableIfAttr (const EnableIfAttr * A) inline
Definition at line 235 of file TextNodeDumper.h.
VisitEnforceTCBAttr()
void clang::TextNodeDumper::VisitEnforceTCBAttr (const EnforceTCBAttr * A) inline
Definition at line 239 of file TextNodeDumper.h.
VisitEnforceTCBLeafAttr()
void clang::TextNodeDumper::VisitEnforceTCBLeafAttr (const EnforceTCBLeafAttr * A) inline
Definition at line 243 of file TextNodeDumper.h.
VisitEnumConstantDecl()
void TextNodeDumper::VisitEnumConstantDecl (const EnumConstantDecl * D)
Definition at line 1564 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), and clang::ValueDecl::getType().
VisitEnumDecl()
void TextNodeDumper::VisitEnumDecl (const EnumDecl * D)
Definition at line 1541 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::EnumDecl::getIntegerType(), clang::EnumDecl::isFixed(), clang::NamedDecl::isModulePrivate(), clang::EnumDecl::isScoped(), and clang::EnumDecl::isScopedUsingClassTag().
VisitEnumExtensibilityAttr()
void clang::TextNodeDumper::VisitEnumExtensibilityAttr (const EnumExtensibilityAttr * A) inline
Definition at line 247 of file TextNodeDumper.h.
VisitExpressionTemplateArgument()
void TextNodeDumper::VisitExpressionTemplateArgument (const TemplateArgument & TA)
Definition at line 870 of file TextNodeDumper.cpp.
VisitExpressionTraitExpr()
void TextNodeDumper::VisitExpressionTraitExpr (const ExpressionTraitExpr * Node)
Definition at line 1208 of file TextNodeDumper.cpp.
References clang::getTraitSpelling(), and Node.
VisitExprWithCleanups()
void TextNodeDumper::VisitExprWithCleanups (const ExprWithCleanups * Node)
Definition at line 1220 of file TextNodeDumper.cpp.
References dumpCleanupObject(), and Node.
VisitExternalSourceSymbolAttr()
void clang::TextNodeDumper::VisitExternalSourceSymbolAttr (const ExternalSourceSymbolAttr * A) inline
Definition at line 258 of file TextNodeDumper.h.
VisitExtVectorElementExpr()
void TextNodeDumper::VisitExtVectorElementExpr (const ExtVectorElementExpr * Node)
Definition at line 1090 of file TextNodeDumper.cpp.
References Node.
VisitFieldDecl()
void TextNodeDumper::VisitFieldDecl (const FieldDecl * D)
Definition at line 1658 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::ValueDecl::getType(), clang::NamedDecl::isModulePrivate(), and clang::FieldDecl::isMutable().
VisitFinalAttr()
void clang::TextNodeDumper::VisitFinalAttr (const FinalAttr * A) inline
Definition at line 264 of file TextNodeDumper.h.
VisitFixedPointLiteral()
void TextNodeDumper::VisitFixedPointLiteral (const FixedPointLiteral * Node)
Definition at line 1034 of file TextNodeDumper.cpp.
References Node, and clang::ValueColor.
VisitFloatingLiteral()
void TextNodeDumper::VisitFloatingLiteral (const FloatingLiteral * Node)
Definition at line 1039 of file TextNodeDumper.cpp.
References Node, and clang::ValueColor.
VisitFormatArgAttr()
void clang::TextNodeDumper::VisitFormatArgAttr (const FormatArgAttr * A) inline
Definition at line 274 of file TextNodeDumper.h.
VisitFormatAttr()
void clang::TextNodeDumper::VisitFormatAttr (const FormatAttr * A) inline
Definition at line 267 of file TextNodeDumper.h.
VisitFriendDecl()
void TextNodeDumper::VisitFriendDecl (const FriendDecl * D)
Definition at line 2117 of file TextNodeDumper.cpp.
References dumpType(), and clang::FriendDecl::getFriendType().
VisitFunctionDecl()
void TextNodeDumper::VisitFunctionDecl (const FunctionDecl * D)
Definition at line 1577 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), dumpName(), dumpType(), clang::EST_Unevaluated, clang::EST_Uninstantiated, clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::Type::getAs(), clang::QualType::getAsString(), clang::NamedDecl::getDeclName(), clang::FunctionDecl::getNumParams(), clang::DeclContext::getParent(), clang::FunctionDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::ValueDecl::getType(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isDeleted(), clang::FunctionDecl::isDeletedAsWritten(), clang::FunctionDecl::isInlineSpecified(), clang::NamedDecl::isModulePrivate(), clang::FunctionDecl::isPure(), clang::FunctionDecl::isTrivial(), clang::FunctionDecl::isVirtualAsWritten(), clang::FunctionDecl::param_begin(), clang::FunctionDecl::param_empty(), clang::SC_None, clang::FunctionProtoType::ExceptionSpecInfo::SourceDecl, clang::FunctionProtoType::ExceptionSpecInfo::SourceTemplate, clang::QualType::split(), and clang::FunctionProtoType::ExceptionSpecInfo::Type.
VisitFunctionProtoType()
void TextNodeDumper::VisitFunctionProtoType (const FunctionProtoType * T)
Definition at line 1444 of file TextNodeDumper.cpp.
References clang::RQ_LValue, clang::RQ_None, clang::RQ_RValue, and VisitFunctionType().
VisitFunctionTemplateDecl()
void TextNodeDumper::VisitFunctionTemplateDecl (const FunctionTemplateDecl * D)
Definition at line 1995 of file TextNodeDumper.cpp.
References dumpName().
VisitFunctionType()
void TextNodeDumper::VisitFunctionType (const FunctionType * T)
Definition at line 1433 of file TextNodeDumper.cpp.
References clang::FunctionType::getNameForCallConv().
Referenced by VisitFunctionProtoType().
VisitGenericSelectionExpr()
void TextNodeDumper::VisitGenericSelectionExpr (const GenericSelectionExpr * E)
Definition at line 1057 of file TextNodeDumper.cpp.
References clang::GenericSelectionExpr::isResultDependent().
VisitGotoStmt()
void TextNodeDumper::VisitGotoStmt (const GotoStmt * Node)
Definition at line 928 of file TextNodeDumper.cpp.
References dumpPointer(), and Node.
visitHTMLEndTagComment()
void TextNodeDumper::visitHTMLEndTagComment (const comments::HTMLEndTagComment * C, const comments::FullComment *)
Definition at line 764 of file TextNodeDumper.cpp.
References clang::C.
visitHTMLStartTagComment()
void TextNodeDumper::visitHTMLStartTagComment (const comments::HTMLStartTagComment * C, const comments::FullComment *)
Definition at line 750 of file TextNodeDumper.cpp.
References clang::C.
VisitIBOutletCollectionAttr()
void clang::TextNodeDumper::VisitIBOutletCollectionAttr (const IBOutletCollectionAttr * A) inline
Definition at line 278 of file TextNodeDumper.h.
VisitIfStmt()
void TextNodeDumper::VisitIfStmt (const IfStmt * Node)
Definition at line 903 of file TextNodeDumper.cpp.
References Node.
VisitIFuncAttr()
void clang::TextNodeDumper::VisitIFuncAttr (const IFuncAttr * A) inline
Definition at line 282 of file TextNodeDumper.h.
VisitImplicitCastExpr()
void TextNodeDumper::VisitImplicitCastExpr (const ImplicitCastExpr * Node)
Definition at line 971 of file TextNodeDumper.cpp.
References Node, and VisitCastExpr().
VisitImportDecl()
void TextNodeDumper::VisitImportDecl (const ImportDecl * D)
Definition at line 1730 of file TextNodeDumper.cpp.
References dumpDeclRef(), clang::Decl::getASTContext(), clang::Module::getFullModuleName(), clang::ImportDecl::getImportedModule(), and clang::ASTContext::getModuleInitializers().
VisitIndirectFieldDecl()
void TextNodeDumper::VisitIndirectFieldDecl (const IndirectFieldDecl * D)
Definition at line 1569 of file TextNodeDumper.cpp.
References clang::IndirectFieldDecl::chain(), dumpDeclRef(), dumpName(), dumpType(), and clang::ValueDecl::getType().
VisitInitListExpr()
void TextNodeDumper::VisitInitListExpr (const InitListExpr * ILE)
Definition at line 1050 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and clang::InitListExpr::getInitializedFieldInUnion().
VisitInitPriorityAttr()
void clang::TextNodeDumper::VisitInitPriorityAttr (const InitPriorityAttr * A) inline
Definition at line 286 of file TextNodeDumper.h.
VisitInitSegAttr()
void clang::TextNodeDumper::VisitInitSegAttr (const InitSegAttr * A) inline
Definition at line 290 of file TextNodeDumper.h.
VisitInjectedClassNameType()
void TextNodeDumper::VisitInjectedClassNameType (const InjectedClassNameType * T)
Definition at line 1518 of file TextNodeDumper.cpp.
References dumpDeclRef().
visitInlineCommandComment()
void TextNodeDumper::visitInlineCommandComment (const comments::InlineCommandComment * C, const comments::FullComment *)
Definition at line 725 of file TextNodeDumper.cpp.
References clang::C, clang::comments::InlineCommandComment::RenderAnchor, clang::comments::InlineCommandComment::RenderBold, clang::comments::InlineCommandComment::RenderEmphasized, clang::comments::InlineCommandComment::RenderMonospaced, and clang::comments::InlineCommandComment::RenderNormal.
VisitIntegerLiteral()
void TextNodeDumper::VisitIntegerLiteral (const IntegerLiteral * Node)
Definition at line 1028 of file TextNodeDumper.cpp.
References Node, and clang::ValueColor.
VisitIntegralTemplateArgument()
void TextNodeDumper::VisitIntegralTemplateArgument (const TemplateArgument & TA)
Definition at line 855 of file TextNodeDumper.cpp.
References clang::TemplateArgument::getAsIntegral().
VisitLabelDecl()
void TextNodeDumper::VisitLabelDecl (const LabelDecl * D)
Definition at line 1532 of file TextNodeDumper.cpp.
References dumpName().
VisitLabelStmt()
void TextNodeDumper::VisitLabelStmt (const LabelStmt * Node)
Definition at line 924 of file TextNodeDumper.cpp.
References Node.
VisitLayoutVersionAttr()
void clang::TextNodeDumper::VisitLayoutVersionAttr (const LayoutVersionAttr * A) inline
Definition at line 294 of file TextNodeDumper.h.
VisitLifetimeExtendedTemporaryDecl()
void TextNodeDumper::VisitLifetimeExtendedTemporaryDecl (const LifetimeExtendedTemporaryDecl * D)
Definition at line 1647 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), clang::LifetimeExtendedTemporaryDecl::getExtendingDecl(), clang::LifetimeExtendedTemporaryDecl::getManglingNumber(), and clang::ValueColor.
VisitLinkageSpecDecl()
void TextNodeDumper::VisitLinkageSpecDecl (const LinkageSpecDecl * D)
Definition at line 2101 of file TextNodeDumper.cpp.
References clang::LinkageSpecDecl::getLanguage(), clang::LinkageSpecDecl::lang_c, and clang::LinkageSpecDecl::lang_cxx.
VisitLoopHintAttr()
void clang::TextNodeDumper::VisitLoopHintAttr (const LoopHintAttr * A) inline
Definition at line 298 of file TextNodeDumper.h.
VisitMaterializeTemporaryExpr()
void TextNodeDumper::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * Node)
Definition at line 1212 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and Node.
VisitMaxFieldAlignmentAttr()
void clang::TextNodeDumper::VisitMaxFieldAlignmentAttr (const MaxFieldAlignmentAttr * A) inline
Definition at line 376 of file TextNodeDumper.h.
VisitMemberExpr()
void TextNodeDumper::VisitMemberExpr (const MemberExpr * Node)
Definition at line 1079 of file TextNodeDumper.cpp.
References dumpPointer(), Node, clang::NOUR_Constant, clang::NOUR_Discarded, clang::NOUR_None, and clang::NOUR_Unevaluated.
VisitMinVectorWidthAttr()
void clang::TextNodeDumper::VisitMinVectorWidthAttr (const MinVectorWidthAttr * A) inline
Definition at line 380 of file TextNodeDumper.h.
VisitMipsInterruptAttr()
void clang::TextNodeDumper::VisitMipsInterruptAttr (const MipsInterruptAttr * A) inline
Definition at line 384 of file TextNodeDumper.h.
VisitMipsLongCallAttr()
void clang::TextNodeDumper::VisitMipsLongCallAttr (const MipsLongCallAttr * A) inline
Definition at line 416 of file TextNodeDumper.h.
VisitMipsShortCallAttr()
void clang::TextNodeDumper::VisitMipsShortCallAttr (const MipsShortCallAttr * A) inline
Definition at line 419 of file TextNodeDumper.h.
VisitModeAttr()
void clang::TextNodeDumper::VisitModeAttr (const ModeAttr * A) inline
Definition at line 422 of file TextNodeDumper.h.
VisitMSInheritanceAttr()
void clang::TextNodeDumper::VisitMSInheritanceAttr (const MSInheritanceAttr * A) inline
Definition at line 363 of file TextNodeDumper.h.
VisitMSP430InterruptAttr()
void clang::TextNodeDumper::VisitMSP430InterruptAttr (const MSP430InterruptAttr * A) inline
Definition at line 368 of file TextNodeDumper.h.
VisitMSVtorDispAttr()
void clang::TextNodeDumper::VisitMSVtorDispAttr (const MSVtorDispAttr * A) inline
Definition at line 372 of file TextNodeDumper.h.
VisitNamespaceAliasDecl()
void TextNodeDumper::VisitNamespaceAliasDecl (const NamespaceAliasDecl * D)
Definition at line 1836 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), and clang::NamespaceAliasDecl::getAliasedNamespace().
VisitNamespaceDecl()
void TextNodeDumper::VisitNamespaceDecl (const NamespaceDecl * D)
Definition at line 1823 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::NamespaceDecl::getOriginalNamespace(), clang::NamespaceDecl::isInline(), and clang::NamespaceDecl::isOriginalNamespace().
VisitNoBuiltinAttr()
void clang::TextNodeDumper::VisitNoBuiltinAttr (const NoBuiltinAttr * A) inline
Definition at line 432 of file TextNodeDumper.h.
VisitNonNullAttr()
void clang::TextNodeDumper::VisitNonNullAttr (const NonNullAttr * A) inline
Definition at line 442 of file TextNodeDumper.h.
VisitNonTypeTemplateParmDecl()
void TextNodeDumper::VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl * D)
Definition at line 2030 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::ValueDecl::getType(), and clang::NonTypeTemplateParmDecl::isParameterPack().
VisitNoSanitizeAttr()
void clang::TextNodeDumper::VisitNoSanitizeAttr (const NoSanitizeAttr * A) inline
Definition at line 437 of file TextNodeDumper.h.
VisitNSErrorDomainAttr()
void clang::TextNodeDumper::VisitNSErrorDomainAttr (const NSErrorDomainAttr * A) inline
Definition at line 427 of file TextNodeDumper.h.
VisitNullPtrTemplateArgument()
void TextNodeDumper::VisitNullPtrTemplateArgument (const TemplateArgument & TA)
Definition at line 851 of file TextNodeDumper.cpp.
VisitNullTemplateArgument()
void TextNodeDumper::VisitNullTemplateArgument (const TemplateArgument & TA)
Definition at line 836 of file TextNodeDumper.cpp.
VisitObjCAtCatchStmt()
void TextNodeDumper::VisitObjCAtCatchStmt (const ObjCAtCatchStmt * Node)
Definition at line 1264 of file TextNodeDumper.cpp.
References Node.
VisitObjCBoolLiteralExpr()
void TextNodeDumper::VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr * Node)
Definition at line 1334 of file TextNodeDumper.cpp.
References Node.
VisitObjCBoxedExpr()
void TextNodeDumper::VisitObjCBoxedExpr (const ObjCBoxedExpr * Node)
Definition at line 1257 of file TextNodeDumper.cpp.
References Node.
VisitObjCBridgeAttr()
void clang::TextNodeDumper::VisitObjCBridgeAttr (const ObjCBridgeAttr * A) inline
Definition at line 529 of file TextNodeDumper.h.
VisitObjCBridgeMutableAttr()
void clang::TextNodeDumper::VisitObjCBridgeMutableAttr (const ObjCBridgeMutableAttr * A) inline
Definition at line 534 of file TextNodeDumper.h.
VisitObjCBridgeRelatedAttr()
void clang::TextNodeDumper::VisitObjCBridgeRelatedAttr (const ObjCBridgeRelatedAttr * A) inline
Definition at line 539 of file TextNodeDumper.h.
VisitObjCCategoryDecl()
void TextNodeDumper::VisitObjCCategoryDecl (const ObjCCategoryDecl * D)
Definition at line 2179 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCCategoryDecl::getImplementation(), clang::StmtVisitorBase< llvm::make_const_ptr, TextNodeDumper, void, ParamTys... >::P, and clang::ObjCCategoryDecl::protocols().
VisitObjCCategoryImplDecl()
void TextNodeDumper::VisitObjCCategoryImplDecl (const ObjCCategoryImplDecl * D)
Definition at line 2187 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::ObjCCategoryImplDecl::getCategoryDecl(), and clang::ObjCImplDecl::getClassInterface().
VisitObjCCompatibleAliasDecl()
void TextNodeDumper::VisitObjCCompatibleAliasDecl (const ObjCCompatibleAliasDecl * D)
Definition at line 2216 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), and clang::ObjCCompatibleAliasDecl::getClassInterface().
VisitObjCEncodeExpr()
void TextNodeDumper::VisitObjCEncodeExpr (const ObjCEncodeExpr * Node)
Definition at line 1269 of file TextNodeDumper.cpp.
References dumpType(), and Node.
VisitObjCGCAttr()
void clang::TextNodeDumper::VisitObjCGCAttr (const ObjCGCAttr * A) inline
Definition at line 548 of file TextNodeDumper.h.
VisitObjCImplementationDecl()
void TextNodeDumper::VisitObjCImplementationDecl (const ObjCImplementationDecl * D)
Definition at line 2209 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::ObjCImplDecl::getClassInterface(), and clang::ObjCImplementationDecl::getSuperClass().
VisitObjCInterfaceDecl()
void TextNodeDumper::VisitObjCInterfaceDecl (const ObjCInterfaceDecl * D)
Definition at line 2200 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::ObjCInterfaceDecl::getImplementation(), clang::ObjCInterfaceDecl::getSuperClass(), and clang::ObjCInterfaceDecl::protocols().
VisitObjCInterfaceType()
void TextNodeDumper::VisitObjCInterfaceType (const ObjCInterfaceType * T)
Definition at line 1523 of file TextNodeDumper.cpp.
References dumpDeclRef().
VisitObjCIvarDecl()
void TextNodeDumper::VisitObjCIvarDecl (const ObjCIvarDecl * D)
Definition at line 2122 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::ObjCIvarDecl::getAccessControl(), clang::ObjCIvarDecl::getSynthesize(), clang::ValueDecl::getType(), clang::ObjCIvarDecl::None, clang::ObjCIvarDecl::Package, clang::ObjCIvarDecl::Private, clang::ObjCIvarDecl::Protected, and clang::ObjCIvarDecl::Public.
VisitObjCIvarRefExpr()
void TextNodeDumper::VisitObjCIvarRefExpr (const ObjCIvarRefExpr * Node)
Definition at line 1008 of file TextNodeDumper.cpp.
References clang::DeclKindNameColor, dumpPointer(), and Node.
VisitObjCMessageExpr()
void TextNodeDumper::VisitObjCMessageExpr (const ObjCMessageExpr * Node)
Definition at line 1235 of file TextNodeDumper.cpp.
References clang::ObjCMessageExpr::Class, dumpBareType(), clang::ObjCMessageExpr::Instance, Node, clang::DynTypedNode::print(), clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
VisitObjCMethodDecl()
void TextNodeDumper::VisitObjCMethodDecl (const ObjCMethodDecl * D)
Definition at line 2147 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::isInstanceMethod(), and clang::ObjCMethodDecl::isVariadic().
VisitObjCMethodFamilyAttr()
void clang::TextNodeDumper::VisitObjCMethodFamilyAttr (const ObjCMethodFamilyAttr * A) inline
Definition at line 553 of file TextNodeDumper.h.
VisitObjCOwnershipAttr()
void clang::TextNodeDumper::VisitObjCOwnershipAttr (const ObjCOwnershipAttr * A) inline
Definition at line 576 of file TextNodeDumper.h.
VisitObjCPropertyDecl()
void TextNodeDumper::VisitObjCPropertyDecl (const ObjCPropertyDecl * D)
Definition at line 2222 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), dumpType(), clang::ObjCPropertyDecl::getGetterMethodDecl(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyDecl::getPropertyImplementation(), clang::ObjCPropertyDecl::getSetterMethodDecl(), clang::ObjCPropertyDecl::getType(), clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_class, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_direct, clang::ObjCPropertyAttribute::kind_getter, clang::ObjCPropertyAttribute::kind_noattr, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, clang::ObjCPropertyAttribute::kind_weak, clang::ObjCPropertyDecl::Optional, and clang::ObjCPropertyDecl::Required.
VisitObjCPropertyImplDecl()
void TextNodeDumper::VisitObjCPropertyImplDecl (const ObjCPropertyImplDecl * D)
Definition at line 2264 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyImplementation(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), and clang::ObjCPropertyImplDecl::Synthesize.
VisitObjCPropertyRefExpr()
void TextNodeDumper::VisitObjCPropertyRefExpr (const ObjCPropertyRefExpr * Node)
Definition at line 1282 of file TextNodeDumper.cpp.
References Node, and clang::DynTypedNode::print().
VisitObjCProtocolDecl()
void TextNodeDumper::VisitObjCProtocolDecl (const ObjCProtocolDecl * D)
Definition at line 2193 of file TextNodeDumper.cpp.
References dumpDeclRef(), dumpName(), and clang::ObjCProtocolDecl::protocols().
VisitObjCProtocolExpr()
void TextNodeDumper::VisitObjCProtocolExpr (const ObjCProtocolExpr * Node)
Definition at line 1278 of file TextNodeDumper.cpp.
References Node.
VisitObjCRuntimeNameAttr()
void clang::TextNodeDumper::VisitObjCRuntimeNameAttr (const ObjCRuntimeNameAttr * A) inline
Definition at line 581 of file TextNodeDumper.h.
VisitObjCSelectorExpr()
void TextNodeDumper::VisitObjCSelectorExpr (const ObjCSelectorExpr * Node)
Definition at line 1273 of file TextNodeDumper.cpp.
References Node, and clang::DynTypedNode::print().
VisitObjCSubscriptRefExpr()
void TextNodeDumper::VisitObjCSubscriptRefExpr (const ObjCSubscriptRefExpr * Node)
Definition at line 1313 of file TextNodeDumper.cpp.
References Node, and clang::DynTypedNode::print().
VisitObjCTypeParamDecl()
void TextNodeDumper::VisitObjCTypeParamDecl (const ObjCTypeParamDecl * D)
Definition at line 2159 of file TextNodeDumper.cpp.
References clang::Contravariant, clang::Covariant, dumpName(), dumpType(), clang::TypedefNameDecl::getUnderlyingType(), clang::ObjCTypeParamDecl::getVariance(), clang::ObjCTypeParamDecl::hasExplicitBound(), and clang::Invariant.
VisitOMPAllocateDeclAttr()
void clang::TextNodeDumper::VisitOMPAllocateDeclAttr (const OMPAllocateDeclAttr * A) inline
Definition at line 447 of file TextNodeDumper.h.
VisitOMPCapturedExprDecl()
void TextNodeDumper::VisitOMPCapturedExprDecl (const OMPCapturedExprDecl * D)
Definition at line 1818 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), and clang::ValueDecl::getType().
VisitOMPCaptureKindAttr()
void clang::TextNodeDumper::VisitOMPCaptureKindAttr (const OMPCaptureKindAttr * A) inline
Definition at line 482 of file TextNodeDumper.h.
VisitOMPDeclareReductionDecl()
void TextNodeDumper::VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl * D)
Definition at line 1775 of file TextNodeDumper.cpp.
References clang::OMPDeclareReductionDecl::CallInit, clang::OMPDeclareReductionDecl::CopyInit, clang::OMPDeclareReductionDecl::DirectInit, dumpName(), dumpPointer(), dumpType(), clang::OMPDeclareReductionDecl::getCombiner(), clang::OMPDeclareReductionDecl::getInitializer(), clang::OMPDeclareReductionDecl::getInitializerKind(), clang::ValueDecl::getType(), and clang::Initializer.
VisitOMPDeclareSimdDeclAttr()
void clang::TextNodeDumper::VisitOMPDeclareSimdDeclAttr (const OMPDeclareSimdDeclAttr * A) inline
Definition at line 486 of file TextNodeDumper.h.
VisitOMPDeclareTargetDeclAttr()
void clang::TextNodeDumper::VisitOMPDeclareTargetDeclAttr (const OMPDeclareTargetDeclAttr * A) inline
Definition at line 502 of file TextNodeDumper.h.
VisitOMPDeclareVariantAttr()
void clang::TextNodeDumper::VisitOMPDeclareVariantAttr (const OMPDeclareVariantAttr * A) inline
Definition at line 525 of file TextNodeDumper.h.
VisitOMPExecutableDirective()
void TextNodeDumper::VisitOMPExecutableDirective (const OMPExecutableDirective * D)
Definition at line 1769 of file TextNodeDumper.cpp.
References clang::OMPExecutableDirective::isStandaloneDirective().
VisitOMPIteratorExpr()
void TextNodeDumper::VisitOMPIteratorExpr (const OMPIteratorExpr * Node)
Definition at line 1338 of file TextNodeDumper.cpp.
References Node, and Visit().
VisitOMPRequiresDecl()
void TextNodeDumper::VisitOMPRequiresDecl (const OMPRequiresDecl * D)
Definition at line 1797 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::AttrColor, clang::C, clang::OMPRequiresDecl::clauselists(), dumpPointer(), dumpSourceRange(), and clang::NullColor.
VisitOpenCLAccessAttr()
void clang::TextNodeDumper::VisitOpenCLAccessAttr (const OpenCLAccessAttr * A) inline
Definition at line 585 of file TextNodeDumper.h.
VisitOpenCLConstantAddressSpaceAttr()
void clang::TextNodeDumper::VisitOpenCLConstantAddressSpaceAttr (const OpenCLConstantAddressSpaceAttr * A) inline
Definition at line 588 of file TextNodeDumper.h.
VisitOpenCLGenericAddressSpaceAttr()
void clang::TextNodeDumper::VisitOpenCLGenericAddressSpaceAttr (const OpenCLGenericAddressSpaceAttr * A) inline
Definition at line 591 of file TextNodeDumper.h.
VisitOpenCLGlobalAddressSpaceAttr()
void clang::TextNodeDumper::VisitOpenCLGlobalAddressSpaceAttr (const OpenCLGlobalAddressSpaceAttr * A) inline
Definition at line 594 of file TextNodeDumper.h.
VisitOpenCLIntelReqdSubGroupSizeAttr()
void clang::TextNodeDumper::VisitOpenCLIntelReqdSubGroupSizeAttr (const OpenCLIntelReqdSubGroupSizeAttr * A) inline
Definition at line 597 of file TextNodeDumper.h.
VisitOpenCLLocalAddressSpaceAttr()
void clang::TextNodeDumper::VisitOpenCLLocalAddressSpaceAttr (const OpenCLLocalAddressSpaceAttr * A) inline
Definition at line 601 of file TextNodeDumper.h.
VisitOpenCLPrivateAddressSpaceAttr()
void clang::TextNodeDumper::VisitOpenCLPrivateAddressSpaceAttr (const OpenCLPrivateAddressSpaceAttr * A) inline
Definition at line 604 of file TextNodeDumper.h.
VisitOpenCLUnrollHintAttr()
void clang::TextNodeDumper::VisitOpenCLUnrollHintAttr (const OpenCLUnrollHintAttr * A) inline
Definition at line 607 of file TextNodeDumper.h.
VisitOwnerAttr()
void clang::TextNodeDumper::VisitOwnerAttr (const OwnerAttr * A) inline
Definition at line 611 of file TextNodeDumper.h.
VisitOwnershipAttr()
void clang::TextNodeDumper::VisitOwnershipAttr (const OwnershipAttr * A) inline
Definition at line 615 of file TextNodeDumper.h.
VisitPackExpansionType()
void TextNodeDumper::VisitPackExpansionType (const PackExpansionType * T)
Definition at line 1527 of file TextNodeDumper.cpp.
References N.
VisitPackTemplateArgument()
void TextNodeDumper::VisitPackTemplateArgument (const TemplateArgument & TA)
Definition at line 874 of file TextNodeDumper.cpp.
visitParamCommandComment()
void TextNodeDumper::visitParamCommandComment (const comments::ParamCommandComment * C, const comments::FullComment * FC)
Definition at line 776 of file TextNodeDumper.cpp.
References clang::C, and clang::comments::ParamCommandComment::getDirectionAsString().
VisitParamTypestateAttr()
void clang::TextNodeDumper::VisitParamTypestateAttr (const ParamTypestateAttr * A) inline
Definition at line 623 of file TextNodeDumper.h.
VisitPassObjectSizeAttr()
void clang::TextNodeDumper::VisitPassObjectSizeAttr (const PassObjectSizeAttr * A) inline
Definition at line 637 of file TextNodeDumper.h.
VisitPatchableFunctionEntryAttr()
void clang::TextNodeDumper::VisitPatchableFunctionEntryAttr (const PatchableFunctionEntryAttr * A) inline
Definition at line 642 of file TextNodeDumper.h.
VisitPcsAttr()
void clang::TextNodeDumper::VisitPcsAttr (const PcsAttr * A) inline
Definition at line 647 of file TextNodeDumper.h.
VisitPointerAttr()
void clang::TextNodeDumper::VisitPointerAttr (const PointerAttr * A) inline
Definition at line 658 of file TextNodeDumper.h.
VisitPragmaClangBSSSectionAttr()
void clang::TextNodeDumper::VisitPragmaClangBSSSectionAttr (const PragmaClangBSSSectionAttr * A) inline
Definition at line 662 of file TextNodeDumper.h.
VisitPragmaClangDataSectionAttr()
void clang::TextNodeDumper::VisitPragmaClangDataSectionAttr (const PragmaClangDataSectionAttr * A) inline
Definition at line 666 of file TextNodeDumper.h.
VisitPragmaClangRelroSectionAttr()
void clang::TextNodeDumper::VisitPragmaClangRelroSectionAttr (const PragmaClangRelroSectionAttr * A) inline
Definition at line 670 of file TextNodeDumper.h.
VisitPragmaClangRodataSectionAttr()
void clang::TextNodeDumper::VisitPragmaClangRodataSectionAttr (const PragmaClangRodataSectionAttr * A) inline
Definition at line 674 of file TextNodeDumper.h.
VisitPragmaClangTextSectionAttr()
void clang::TextNodeDumper::VisitPragmaClangTextSectionAttr (const PragmaClangTextSectionAttr * A) inline
Definition at line 678 of file TextNodeDumper.h.
VisitPragmaCommentDecl()
void TextNodeDumper::VisitPragmaCommentDecl (const PragmaCommentDecl * D)
Definition at line 1738 of file TextNodeDumper.cpp.
References clang::PragmaCommentDecl::getArg(), clang::PragmaCommentDecl::getCommentKind(), clang::PCK_Compiler, clang::PCK_ExeStr, clang::PCK_Lib, clang::PCK_Linker, clang::PCK_Unknown, and clang::PCK_User.
VisitPragmaDetectMismatchDecl()
void TextNodeDumper::VisitPragmaDetectMismatchDecl (const PragmaDetectMismatchDecl * D)
Definition at line 1764 of file TextNodeDumper.cpp.
References clang::PragmaDetectMismatchDecl::getName(), and clang::PragmaDetectMismatchDecl::getValue().
VisitPredefinedExpr()
void TextNodeDumper::VisitPredefinedExpr (const PredefinedExpr * Node)
Definition at line 1019 of file TextNodeDumper.cpp.
References clang::PredefinedExpr::getIdentKindName(), and Node.
VisitPreferredNameAttr()
void clang::TextNodeDumper::VisitPreferredNameAttr (const PreferredNameAttr * A) inline
Definition at line 682 of file TextNodeDumper.h.
VisitRecordDecl()
void TextNodeDumper::VisitRecordDecl (const RecordDecl * D)
Definition at line 1555 of file TextNodeDumper.cpp.
References dumpName(), clang::TagDecl::getKindName(), clang::TagDecl::isCompleteDefinition(), and clang::NamedDecl::isModulePrivate().
Referenced by VisitCXXRecordDecl().
VisitReleaseCapabilityAttr()
void clang::TextNodeDumper::VisitReleaseCapabilityAttr (const ReleaseCapabilityAttr * A) inline
Definition at line 700 of file TextNodeDumper.h.
VisitReleaseHandleAttr()
void clang::TextNodeDumper::VisitReleaseHandleAttr (const ReleaseHandleAttr * A) inline
Definition at line 704 of file TextNodeDumper.h.
VisitReqdWorkGroupSizeAttr()
void clang::TextNodeDumper::VisitReqdWorkGroupSizeAttr (const ReqdWorkGroupSizeAttr * A) inline
Definition at line 708 of file TextNodeDumper.h.
VisitRequiresCapabilityAttr()
void clang::TextNodeDumper::VisitRequiresCapabilityAttr (const RequiresCapabilityAttr * A) inline
Definition at line 714 of file TextNodeDumper.h.
VisitRestrictAttr()
void clang::TextNodeDumper::VisitRestrictAttr (const RestrictAttr * A) inline
Definition at line 718 of file TextNodeDumper.h.
VisitReturnTypestateAttr()
void clang::TextNodeDumper::VisitReturnTypestateAttr (const ReturnTypestateAttr * A) inline
Definition at line 721 of file TextNodeDumper.h.
VisitRISCVInterruptAttr()
void clang::TextNodeDumper::VisitRISCVInterruptAttr (const RISCVInterruptAttr * A) inline
Definition at line 686 of file TextNodeDumper.h.
VisitRValueReferenceType()
void TextNodeDumper::VisitRValueReferenceType (const ReferenceType * T)
Definition at line 1361 of file TextNodeDumper.cpp.
VisitSectionAttr()
void clang::TextNodeDumper::VisitSectionAttr (const SectionAttr * A) inline
Definition at line 735 of file TextNodeDumper.h.
VisitSentinelAttr()
void clang::TextNodeDumper::VisitSentinelAttr (const SentinelAttr * A) inline
Definition at line 740 of file TextNodeDumper.h.
VisitSetTypestateAttr()
void clang::TextNodeDumper::VisitSetTypestateAttr (const SetTypestateAttr * A) inline
Definition at line 745 of file TextNodeDumper.h.
VisitSizeOfPackExpr()
void TextNodeDumper::VisitSizeOfPackExpr (const SizeOfPackExpr * Node)
Definition at line 1225 of file TextNodeDumper.cpp.
References dumpName(), dumpPointer(), and Node.
VisitStringLiteral()
void TextNodeDumper::VisitStringLiteral (const StringLiteral * Str)
Definition at line 1044 of file TextNodeDumper.cpp.
References clang::StringLiteral::outputString(), and clang::ValueColor.
VisitSuppressAttr()
void clang::TextNodeDumper::VisitSuppressAttr (const SuppressAttr * A) inline
Definition at line 759 of file TextNodeDumper.h.
VisitSwiftAsyncAttr()
void clang::TextNodeDumper::VisitSwiftAsyncAttr (const SwiftAsyncAttr * A) inline
Definition at line 764 of file TextNodeDumper.h.
VisitSwiftAsyncNameAttr()
void clang::TextNodeDumper::VisitSwiftAsyncNameAttr (const SwiftAsyncNameAttr * A) inline
Definition at line 780 of file TextNodeDumper.h.
VisitSwiftAttrAttr()
void clang::TextNodeDumper::VisitSwiftAttrAttr (const SwiftAttrAttr * A) inline
Definition at line 784 of file TextNodeDumper.h.
VisitSwiftBridgeAttr()
void clang::TextNodeDumper::VisitSwiftBridgeAttr (const SwiftBridgeAttr * A) inline
Definition at line 788 of file TextNodeDumper.h.
VisitSwiftErrorAttr()
void clang::TextNodeDumper::VisitSwiftErrorAttr (const SwiftErrorAttr * A) inline
Definition at line 792 of file TextNodeDumper.h.
VisitSwiftNameAttr()
void clang::TextNodeDumper::VisitSwiftNameAttr (const SwiftNameAttr * A) inline
Definition at line 812 of file TextNodeDumper.h.
VisitSwiftNewTypeAttr()
void clang::TextNodeDumper::VisitSwiftNewTypeAttr (const SwiftNewTypeAttr * A) inline
Definition at line 816 of file TextNodeDumper.h.
VisitSwitchStmt()
void TextNodeDumper::VisitSwitchStmt (const SwitchStmt * Node)
Definition at line 912 of file TextNodeDumper.cpp.
References Node.
VisitTagType()
void TextNodeDumper::VisitTagType (const TagType * T)
Definition at line 1487 of file TextNodeDumper.cpp.
References dumpDeclRef().
VisitTargetAttr()
void clang::TextNodeDumper::VisitTargetAttr (const TargetAttr * A) inline
Definition at line 832 of file TextNodeDumper.h.
VisitTemplateExpansionTemplateArgument()
void TextNodeDumper::VisitTemplateExpansionTemplateArgument (const TemplateArgument & TA)
Definition at line 864 of file TextNodeDumper.cpp.
References clang::TemplateName::dump(), and clang::TemplateArgument::getAsTemplateOrTemplatePattern().
VisitTemplateSpecializationType()
void TextNodeDumper::VisitTemplateSpecializationType (const TemplateSpecializationType * T)
Definition at line 1510 of file TextNodeDumper.cpp.
VisitTemplateTemplateArgument()
void TextNodeDumper::VisitTemplateTemplateArgument (const TemplateArgument & TA)
Definition at line 859 of file TextNodeDumper.cpp.
References clang::TemplateName::dump(), and clang::TemplateArgument::getAsTemplate().
VisitTemplateTemplateParmDecl()
void TextNodeDumper::VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl * D)
Definition at line 2039 of file TextNodeDumper.cpp.
References dumpName(), clang::TemplateTemplateParmDecl::getDepth(), clang::TemplateTemplateParmDecl::getIndex(), and clang::TemplateTemplateParmDecl::isParameterPack().
VisitTemplateTypeParmDecl()
void TextNodeDumper::VisitTemplateTypeParmDecl (const TemplateTypeParmDecl * D)
Definition at line 2011 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), dumpName(), clang::TemplateTypeParmDecl::getDepth(), clang::TemplateTypeParmDecl::getIndex(), clang::TemplateTypeParmDecl::getTypeConstraint(), clang::TemplateTypeParmDecl::isParameterPack(), and clang::TemplateTypeParmDecl::wasDeclaredWithTypename().
VisitTemplateTypeParmType()
void TextNodeDumper::VisitTemplateTypeParmType (const TemplateTypeParmType * T)
Definition at line 1491 of file TextNodeDumper.cpp.
References dumpDeclRef().
VisitTestTypestateAttr()
void clang::TextNodeDumper::VisitTestTypestateAttr (const TestTypestateAttr * A) inline
Definition at line 836 of file TextNodeDumper.h.
visitTextComment()
void TextNodeDumper::visitTextComment (const comments::TextComment * C, const comments::FullComment *)
Definition at line 720 of file TextNodeDumper.cpp.
References clang::C.
VisitTLSModelAttr()
void clang::TextNodeDumper::VisitTLSModelAttr (const TLSModelAttr * A) inline
Definition at line 828 of file TextNodeDumper.h.
visitTParamCommandComment()
void TextNodeDumper::visitTParamCommandComment (const comments::TParamCommandComment * C, const comments::FullComment * FC)
Definition at line 797 of file TextNodeDumper.cpp.
References clang::C.
VisitTryAcquireCapabilityAttr()
void clang::TextNodeDumper::VisitTryAcquireCapabilityAttr (const TryAcquireCapabilityAttr * A) inline
Definition at line 847 of file TextNodeDumper.h.
VisitTypeAliasDecl()
void TextNodeDumper::VisitTypeAliasDecl (const TypeAliasDecl * D)
Definition at line 1841 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), and clang::TypedefNameDecl::getUnderlyingType().
VisitTypeAliasTemplateDecl()
void TextNodeDumper::VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl * D)
Definition at line 1846 of file TextNodeDumper.cpp.
References dumpName().
VisitTypedefDecl()
void TextNodeDumper::VisitTypedefDecl (const TypedefDecl * D)
Definition at line 1534 of file TextNodeDumper.cpp.
References dumpName(), dumpType(), clang::TypedefNameDecl::getUnderlyingType(), and clang::NamedDecl::isModulePrivate().
VisitTypedefType()
void TextNodeDumper::VisitTypedefType (const TypedefType * T)
Definition at line 1475 of file TextNodeDumper.cpp.
References dumpDeclRef().
VisitTypeTagForDatatypeAttr()
void clang::TextNodeDumper::VisitTypeTagForDatatypeAttr (const TypeTagForDatatypeAttr * A) inline
Definition at line 851 of file TextNodeDumper.h.
VisitTypeTemplateArgument()
void TextNodeDumper::VisitTypeTemplateArgument (const TemplateArgument & TA)
Definition at line 840 of file TextNodeDumper.cpp.
References dumpType(), and clang::TemplateArgument::getAsType().
VisitTypeTraitExpr()
void TextNodeDumper::VisitTypeTraitExpr (const TypeTraitExpr * Node)
Definition at line 1200 of file TextNodeDumper.cpp.
References clang::getTraitSpelling(), and Node.
VisitTypeVisibilityAttr()
void clang::TextNodeDumper::VisitTypeVisibilityAttr (const TypeVisibilityAttr * A) inline
Definition at line 859 of file TextNodeDumper.h.
VisitUnaryExprOrTypeTraitExpr()
void TextNodeDumper::VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr * Node)
Definition at line 1071 of file TextNodeDumper.cpp.
References dumpType(), clang::getTraitSpelling(), and Node.
VisitUnaryOperator()
void TextNodeDumper::VisitUnaryOperator (const UnaryOperator * Node)
Definition at line 1062 of file TextNodeDumper.cpp.
References clang::UnaryOperator::getOpcodeStr(), and Node.
VisitUnaryTransformType()
void TextNodeDumper::VisitUnaryTransformType (const UnaryTransformType * T)
Definition at line 1479 of file TextNodeDumper.cpp.
References clang::UnaryTransformType::EnumUnderlyingType.
VisitUnavailableAttr()
void clang::TextNodeDumper::VisitUnavailableAttr (const UnavailableAttr * A) inline
Definition at line 873 of file TextNodeDumper.h.
VisitUnresolvedLookupExpr()
void TextNodeDumper::VisitUnresolvedLookupExpr (const UnresolvedLookupExpr * Node)
Definition at line 993 of file TextNodeDumper.cpp.
References dumpPointer(), and Node.
VisitUnresolvedUsingType()
void TextNodeDumper::VisitUnresolvedUsingType (const UnresolvedUsingType * T)
Definition at line 1471 of file TextNodeDumper.cpp.
References dumpDeclRef().
VisitUnresolvedUsingTypenameDecl()
void TextNodeDumper::VisitUnresolvedUsingTypenameDecl (const UnresolvedUsingTypenameDecl * D)
Definition at line 2054 of file TextNodeDumper.cpp.
References clang::Decl::getASTContext(), clang::NamedDecl::getDeclName(), clang::ASTContext::getPrintingPolicy(), clang::UnresolvedUsingTypenameDecl::getQualifier(), and clang::NestedNameSpecifier::print().
VisitUnresolvedUsingValueDecl()
void TextNodeDumper::VisitUnresolvedUsingValueDecl (const UnresolvedUsingValueDecl * D)
Definition at line 2062 of file TextNodeDumper.cpp.
References dumpType(), clang::Decl::getASTContext(), clang::NamedDecl::getDeclName(), clang::ASTContext::getPrintingPolicy(), clang::UnresolvedUsingValueDecl::getQualifier(), clang::ValueDecl::getType(), and clang::NestedNameSpecifier::print().
VisitUnusedAttr()
void clang::TextNodeDumper::VisitUnusedAttr (const UnusedAttr * A) inline
Definition at line 897 of file TextNodeDumper.h.
VisitUseHandleAttr()
void clang::TextNodeDumper::VisitUseHandleAttr (const UseHandleAttr * A) inline
Definition at line 900 of file TextNodeDumper.h.
VisitUsingDecl()
void TextNodeDumper::VisitUsingDecl (const UsingDecl * D)
Definition at line 2047 of file TextNodeDumper.cpp.
References clang::Decl::getASTContext(), clang::NamedDecl::getDeclName(), clang::ASTContext::getPrintingPolicy(), clang::UsingDecl::getQualifier(), and clang::NestedNameSpecifier::print().
VisitUsingDirectiveDecl()
void TextNodeDumper::VisitUsingDirectiveDecl (const UsingDirectiveDecl * D)
Definition at line 1831 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and clang::UsingDirectiveDecl::getNominatedNamespace().
VisitUsingShadowDecl()
void TextNodeDumper::VisitUsingShadowDecl (const UsingShadowDecl * D)
Definition at line 2071 of file TextNodeDumper.cpp.
References dumpBareDeclRef(), and clang::UsingShadowDecl::getTargetDecl().
VisitUuidAttr()
void clang::TextNodeDumper::VisitUuidAttr (const UuidAttr * A) inline
Definition at line 904 of file TextNodeDumper.h.
VisitVarDecl()
void TextNodeDumper::VisitVarDecl (const VarDecl * D)
Definition at line 1667 of file TextNodeDumper.cpp.
References clang::TextTreeStructure::AddChild(), clang::VarDecl::CallInit, clang::VarDecl::CInit, dumpName(), dumpType(), clang::VarDecl::evaluateValue(), clang::Decl::getASTContext(), clang::VarDecl::getInit(), clang::VarDecl::getInitStyle(), clang::VarDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::VarDecl::getTLSKind(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::VarDecl::hasInit(), clang::VarDecl::isConstexpr(), clang::VarDecl::isInline(), clang::NamedDecl::isModulePrivate(), clang::VarDecl::isNRVOVariable(), clang::VarDecl::isParameterPack(), clang::Expr::isValueDependent(), clang::VarDecl::ListInit, clang::VarDecl::needsDestruction(), clang::SC_None, clang::VarDecl::TLS_Dynamic, clang::VarDecl::TLS_None, clang::VarDecl::TLS_Static, and Visit().
VisitVariableArrayType()
void TextNodeDumper::VisitVariableArrayType (const VariableArrayType * T)
Definition at line 1385 of file TextNodeDumper.cpp.
References dumpSourceRange(), and VisitArrayType().
VisitVarTemplateDecl()
void TextNodeDumper::VisitVarTemplateDecl (const VarTemplateDecl * D)
Definition at line 2003 of file TextNodeDumper.cpp.
References dumpName().
VisitVectorType()
void TextNodeDumper::VisitVectorType (const VectorType * T)
Definition at line 1404 of file TextNodeDumper.cpp.
References clang::VectorType::AltiVecBool, clang::VectorType::AltiVecPixel, clang::VectorType::AltiVecVector, clang::VectorType::GenericVector, clang::VectorType::NeonPolyVector, clang::VectorType::NeonVector, clang::VectorType::SveFixedLengthDataVector, and clang::VectorType::SveFixedLengthPredicateVector.
VisitVecTypeHintAttr()
void clang::TextNodeDumper::VisitVecTypeHintAttr (const VecTypeHintAttr * A) inline
Definition at line 910 of file TextNodeDumper.h.
visitVerbatimBlockComment()
void TextNodeDumper::visitVerbatimBlockComment (const comments::VerbatimBlockComment * C, const comments::FullComment *)
Definition at line 817 of file TextNodeDumper.cpp.
References clang::C.
visitVerbatimBlockLineComment()
void TextNodeDumper::visitVerbatimBlockLineComment (const comments::VerbatimBlockLineComment * C, const comments::FullComment *)
Definition at line 825 of file TextNodeDumper.cpp.
References clang::C.
visitVerbatimLineComment()
void TextNodeDumper::visitVerbatimLineComment (const comments::VerbatimLineComment * C, const comments::FullComment *)
Definition at line 831 of file TextNodeDumper.cpp.
References clang::C.
VisitVisibilityAttr()
void clang::TextNodeDumper::VisitVisibilityAttr (const VisibilityAttr * A) inline
Definition at line 914 of file TextNodeDumper.h.
VisitWarnUnusedResultAttr()
void clang::TextNodeDumper::VisitWarnUnusedResultAttr (const WarnUnusedResultAttr * A) inline
Definition at line 928 of file TextNodeDumper.h.
VisitWeakRefAttr()
void clang::TextNodeDumper::VisitWeakRefAttr (const WeakRefAttr * A) inline
Definition at line 933 of file TextNodeDumper.h.
VisitWebAssemblyExportNameAttr()
void clang::TextNodeDumper::VisitWebAssemblyExportNameAttr (const WebAssemblyExportNameAttr * A) inline
Definition at line 937 of file TextNodeDumper.h.
VisitWebAssemblyImportModuleAttr()
void clang::TextNodeDumper::VisitWebAssemblyImportModuleAttr (const WebAssemblyImportModuleAttr * A) inline
Definition at line 941 of file TextNodeDumper.h.
VisitWebAssemblyImportNameAttr()
void clang::TextNodeDumper::VisitWebAssemblyImportNameAttr (const WebAssemblyImportNameAttr * A) inline
Definition at line 945 of file TextNodeDumper.h.
VisitWhileStmt()
void TextNodeDumper::VisitWhileStmt (const WhileStmt * Node)
Definition at line 919 of file TextNodeDumper.cpp.
References Node.
VisitWorkGroupSizeHintAttr()
void clang::TextNodeDumper::VisitWorkGroupSizeHintAttr (const WorkGroupSizeHintAttr * A) inline
Definition at line 949 of file TextNodeDumper.h.
VisitXRayInstrumentAttr()
void clang::TextNodeDumper::VisitXRayInstrumentAttr (const XRayInstrumentAttr * A) inline
Definition at line 955 of file TextNodeDumper.h.
VisitXRayLogArgsAttr()
void clang::TextNodeDumper::VisitXRayLogArgsAttr (const XRayLogArgsAttr * A) inline
Definition at line 958 of file TextNodeDumper.h.
The documentation for this class was generated from the following files:
include/clang/AST/TextNodeDumper.h
lib/AST/TextNodeDumper.cpp