clang: clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage > Class Template Reference
clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage > Class Template Reference
Represents a lazily-loaded vector of data.
#include "clang/AST/ExternalASTSource.h"
Classes
class iterator
Iteration over the elements in the vector.
Public Member Functions
iterator begin (Source *source, bool LocalOnly=false)
iterator end ()
void push_back (const T &LocalValue)
void erase (iterator From, iterator To)
Detailed Description
template<typename T, typename Source, void(Source::*)(SmallVectorImpl< T > &) Loader, unsigned LoadedStorage = 2, unsigned LocalStorage = 4>
class clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >
Represents a lazily-loaded vector of data.
The lazily-loaded vector of data contains data that is partially loaded from an external source and partially added by local translation. The items loaded from the external source are loaded lazily, when needed for iteration over the complete vector.
Definition at line 495 of file ExternalASTSource.h.
Member Function Documentation
begin()
template<typename T , typename Source , void(Source::*)(SmallVectorImpl< T > &) Loader, unsigned LoadedStorage = 2, unsigned LocalStorage = 4> iterator clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >::begin (Source * source, bool LocalOnly = false) inline
Definition at line 538 of file ExternalASTSource.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), and CheckExtVectorComponent().
end()
template<typename T , typename Source , void(Source::*)(SmallVectorImpl< T > &) Loader, unsigned LoadedStorage = 2, unsigned LocalStorage = 4> iterator clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >::end () inline
Definition at line 547 of file ExternalASTSource.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit(), and CheckExtVectorComponent().
erase()
template<typename T , typename Source , void(Source::*)(SmallVectorImpl< T > &) Loader, unsigned LoadedStorage = 2, unsigned LocalStorage = 4> void clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >::erase (iterator From, iterator To) inline
Definition at line 555 of file ExternalASTSource.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
push_back()
template<typename T , typename Source , void(Source::*)(SmallVectorImpl< T > &) Loader, unsigned LoadedStorage = 2, unsigned LocalStorage = 4> void clang::LazyVector< T, Source, Loader, LoadedStorage, LocalStorage >::push_back (const T & LocalValue) inline
Definition at line 551 of file ExternalASTSource.h.
Referenced by clang::Sema::ActOnUninitializedDecl(), and clang::Sema::MarkUnusedFileScopedDecl().
The documentation for this class was generated from the following file:
include/clang/AST/ExternalASTSource.h