clang: clang::analyze_format_string::FormatStringHandler Class Reference
clang::analyze_format_string::FormatStringHandler Class Reference
#include "clang/AST/FormatString.h"
Public Member Functions
FormatStringHandler ()
virtual ~FormatStringHandler ()
virtual void HandleNullChar (const char *nullCharacter)
virtual void HandlePosition (const char *startPos, unsigned posLen)
virtual void HandleInvalidPosition (const char *startPos, unsigned posLen, PositionContext p)
virtual void HandleZeroPosition (const char *startPos, unsigned posLen)
virtual void HandleIncompleteSpecifier (const char *startSpecifier, unsigned specifierLen)
virtual void HandleEmptyObjCModifierFlag (const char *startFlags, unsigned flagsLen)
virtual void HandleInvalidObjCModifierFlag (const char *startFlag, unsigned flagLen)
virtual void HandleObjCFlagsWithNonObjCConversion (const char *flagsStart, const char *flagsEnd, const char *conversionPosition)
virtual bool HandleInvalidPrintfConversionSpecifier (const analyze_printf::PrintfSpecifier &FS, const char *startSpecifier, unsigned specifierLen)
virtual bool HandlePrintfSpecifier (const analyze_printf::PrintfSpecifier &FS, const char *startSpecifier, unsigned specifierLen)
virtual void handleInvalidMaskType (StringRef MaskType)
Handle mask types whose sizes are not between one and eight bytes.
virtual bool HandleInvalidScanfConversionSpecifier (const analyze_scanf::ScanfSpecifier &FS, const char *startSpecifier, unsigned specifierLen)
virtual bool HandleScanfSpecifier (const analyze_scanf::ScanfSpecifier &FS, const char *startSpecifier, unsigned specifierLen)
virtual void HandleIncompleteScanList (const char *start, const char *end)
Detailed Description
Definition at line 692 of file FormatString.h.
Constructor & Destructor Documentation
FormatStringHandler()
clang::analyze_format_string::FormatStringHandler::FormatStringHandler () inline
Definition at line 694 of file FormatString.h.
~FormatStringHandler()
FormatStringHandler::~FormatStringHandler () virtual
Definition at line 29 of file FormatString.cpp.
Member Function Documentation
HandleEmptyObjCModifierFlag()
virtual void clang::analyze_format_string::FormatStringHandler::HandleEmptyObjCModifierFlag (const char * startFlags, unsigned flagsLen) inline virtual
Definition at line 709 of file FormatString.h.
Referenced by ParseObjCFlags().
HandleIncompleteScanList()
virtual void clang::analyze_format_string::FormatStringHandler::HandleIncompleteScanList (const char * start, const char * end) inline virtual
Definition at line 751 of file FormatString.h.
Referenced by ParseScanList().
HandleIncompleteSpecifier()
virtual void clang::analyze_format_string::FormatStringHandler::HandleIncompleteSpecifier (const char * startSpecifier, unsigned specifierLen) inline virtual
Definition at line 706 of file FormatString.h.
Referenced by clang::analyze_format_string::ParseArgPosition(), clang::analyze_format_string::ParsePositionAmount(), ParsePrintfSpecifier(), ParseScanfSpecifier(), and clang::analyze_format_string::ParseVectorModifier().
handleInvalidMaskType()
virtual void clang::analyze_format_string::FormatStringHandler::handleInvalidMaskType (StringRef MaskType) inline virtual
Handle mask types whose sizes are not between one and eight bytes.
Definition at line 734 of file FormatString.h.
Referenced by ParsePrintfSpecifier().
HandleInvalidObjCModifierFlag()
virtual void clang::analyze_format_string::FormatStringHandler::HandleInvalidObjCModifierFlag (const char * startFlag, unsigned flagLen) inline virtual
Definition at line 712 of file FormatString.h.
Referenced by ParseObjCFlags().
HandleInvalidPosition()
virtual void clang::analyze_format_string::FormatStringHandler::HandleInvalidPosition (const char * startPos, unsigned posLen, PositionContext p) inline virtual
Definition at line 701 of file FormatString.h.
Referenced by clang::analyze_format_string::ParsePositionAmount().
HandleInvalidPrintfConversionSpecifier()
virtual bool clang::analyze_format_string::FormatStringHandler::HandleInvalidPrintfConversionSpecifier (const analyze_printf::PrintfSpecifier & FS, const char * startSpecifier, unsigned specifierLen) inline virtual
Definition at line 720 of file FormatString.h.
Referenced by ParsePrintfSpecifier().
HandleInvalidScanfConversionSpecifier()
virtual bool clang::analyze_format_string::FormatStringHandler::HandleInvalidScanfConversionSpecifier (const analyze_scanf::ScanfSpecifier & FS, const char * startSpecifier, unsigned specifierLen) inline virtual
Definition at line 738 of file FormatString.h.
Referenced by ParseScanfSpecifier().
HandleNullChar()
virtual void clang::analyze_format_string::FormatStringHandler::HandleNullChar (const char * nullCharacter) inline virtual
Definition at line 697 of file FormatString.h.
Referenced by ParsePrintfSpecifier(), and ParseScanfSpecifier().
HandleObjCFlagsWithNonObjCConversion()
virtual void clang::analyze_format_string::FormatStringHandler::HandleObjCFlagsWithNonObjCConversion (const char * flagsStart, const char * flagsEnd, const char * conversionPosition) inline virtual
Definition at line 715 of file FormatString.h.
Referenced by ParsePrintfSpecifier().
HandlePosition()
virtual void clang::analyze_format_string::FormatStringHandler::HandlePosition (const char * startPos, unsigned posLen) inline virtual
Definition at line 699 of file FormatString.h.
Referenced by clang::analyze_format_string::ParseArgPosition().
HandlePrintfSpecifier()
virtual bool clang::analyze_format_string::FormatStringHandler::HandlePrintfSpecifier (const analyze_printf::PrintfSpecifier & FS, const char * startSpecifier, unsigned specifierLen) inline virtual
Definition at line 727 of file FormatString.h.
Referenced by clang::analyze_format_string::ParsePrintfString().
HandleScanfSpecifier()
virtual bool clang::analyze_format_string::FormatStringHandler::HandleScanfSpecifier (const analyze_scanf::ScanfSpecifier & FS, const char * startSpecifier, unsigned specifierLen) inline virtual
Definition at line 745 of file FormatString.h.
Referenced by clang::analyze_format_string::ParseScanfString().
HandleZeroPosition()
virtual void clang::analyze_format_string::FormatStringHandler::HandleZeroPosition (const char * startPos, unsigned posLen) inline virtual
Definition at line 704 of file FormatString.h.
Referenced by clang::analyze_format_string::ParseArgPosition(), and clang::analyze_format_string::ParsePositionAmount().
The documentation for this class was generated from the following files:
include/clang/AST/FormatString.h
lib/AST/FormatString.cpp