clang: clang::concepts::ExprRequirement::ReturnTypeRequirement Class Reference
clang::concepts::ExprRequirement::ReturnTypeRequirement Class Reference
#include "clang/AST/ExprConcepts.h"
Public Member Functions
ReturnTypeRequirement ()
No return type requirement was specified.
ReturnTypeRequirement (SubstitutionDiagnostic *SubstDiag)
A return type requirement was specified but it was a substitution failure.
ReturnTypeRequirement (TemplateParameterList *TPL)
A 'type constraint' style return type requirement.
bool isDependent () const
bool containsUnexpandedParameterPack () const
bool isEmpty () const
bool isSubstitutionFailure () const
bool isTypeConstraint () const
SubstitutionDiagnostic * getSubstitutionDiagnostic () const
const TypeConstraint * getTypeConstraint () const
TemplateParameterList * getTypeConstraintTemplateParameterList () const
Public Attributes
friend ASTStmtReader
friend ASTStmtWriter
Detailed Description
Definition at line 268 of file ExprConcepts.h.
Constructor & Destructor Documentation
ReturnTypeRequirement() [1/3]
clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement () inline
No return type requirement was specified.
Definition at line 278 of file ExprConcepts.h.
ReturnTypeRequirement() [2/3]
clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement (SubstitutionDiagnostic * SubstDiag) inline
A return type requirement was specified but it was a substitution failure.
Definition at line 282 of file ExprConcepts.h.
ReturnTypeRequirement() [3/3]
concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement (TemplateParameterList * TPL)
A 'type constraint' style return type requirement.
Parameters
TPL an invented template parameter list containing a single type parameter with a type-constraint.
Definition at line 1045 of file SemaConcept.cpp.
References clang::TemplateSpecializationType::anyInstantiationDependentTemplateArguments(), clang::cast(), clang::TypeConstraint::getImmediatelyDeclaredConstraint(), clang::TemplateParameterList::getParam(), and clang::TemplateParameterList::size().
Member Function Documentation
containsUnexpandedParameterPack()
bool clang::concepts::ExprRequirement::ReturnTypeRequirement::containsUnexpandedParameterPack () const inline
Definition at line 297 of file ExprConcepts.h.
References clang::TemplateParameterList::containsUnexpandedParameterPack(), getTypeConstraintTemplateParameterList(), and isTypeConstraint().
getSubstitutionDiagnostic()
SubstitutionDiagnostic * clang::concepts::ExprRequirement::ReturnTypeRequirement::getSubstitutionDiagnostic () const inline
Definition at line 318 of file ExprConcepts.h.
References isSubstitutionFailure().
Referenced by diagnoseUnsatisfiedRequirement().
getTypeConstraint()
const TypeConstraint * concepts::ExprRequirement::ReturnTypeRequirement::getTypeConstraint () const
Definition at line 136 of file ExprConcepts.cpp.
References clang::cast(), and isTypeConstraint().
getTypeConstraintTemplateParameterList()
TemplateParameterList * clang::concepts::ExprRequirement::ReturnTypeRequirement::getTypeConstraintTemplateParameterList () const inline
Definition at line 325 of file ExprConcepts.h.
References isTypeConstraint().
Referenced by clang::Sema::BuildExprRequirement(), and containsUnexpandedParameterPack().
isDependent()
bool clang::concepts::ExprRequirement::ReturnTypeRequirement::isDependent () const inline
Definition at line 293 of file ExprConcepts.h.
Referenced by clang::Sema::BuildExprRequirement().
isEmpty()
bool clang::concepts::ExprRequirement::ReturnTypeRequirement::isEmpty () const inline
Definition at line 304 of file ExprConcepts.h.
Referenced by clang::concepts::ExprRequirement::ExprRequirement(), clang::concepts::ExprRequirement::ExprRequirement(), isSubstitutionFailure(), and isTypeConstraint().
isSubstitutionFailure()
bool clang::concepts::ExprRequirement::ReturnTypeRequirement::isSubstitutionFailure () const inline
Definition at line 308 of file ExprConcepts.h.
References isEmpty().
Referenced by clang::Sema::BuildExprRequirement(), and getSubstitutionDiagnostic().
isTypeConstraint()
bool clang::concepts::ExprRequirement::ReturnTypeRequirement::isTypeConstraint () const inline
Definition at line 313 of file ExprConcepts.h.
References isEmpty().
Referenced by clang::Sema::BuildExprRequirement(), containsUnexpandedParameterPack(), clang::concepts::ExprRequirement::ExprRequirement(), getTypeConstraint(), and getTypeConstraintTemplateParameterList().
Member Data Documentation
ASTStmtReader
friend clang::concepts::ExprRequirement::ReturnTypeRequirement::ASTStmtReader
Definition at line 274 of file ExprConcepts.h.
ASTStmtWriter
friend clang::concepts::ExprRequirement::ReturnTypeRequirement::ASTStmtWriter
Definition at line 275 of file ExprConcepts.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExprConcepts.h
lib/AST/ExprConcepts.cpp
lib/Sema/SemaConcept.cpp