clang: clang::format::ContinuationIndenter Class Reference
clang::format::ContinuationIndenter Class Reference
#include "/root/llvm-project/clang/lib/Format/ContinuationIndenter.h"
Public Member Functions
ContinuationIndenter (const FormatStyle &Style, const AdditionalKeywords &Keywords, const SourceManager &SourceMgr, WhitespaceManager &Whitespaces, encoding::Encoding Encoding, bool BinPackInconclusiveFunctions)
Constructs a ContinuationIndenter to format Line starting in column FirstIndent.
LineState getInitialState (unsigned FirstIndent, unsigned FirstStartColumn, const AnnotatedLine *Line, bool DryRun)
Get the initial state, i.e.
bool canBreak (const LineState &State)
Returns true, if a line break after State is allowed.
bool mustBreak (const LineState &State)
Returns true, if a line break after State is mandatory.
unsigned addTokenToState (LineState &State, bool Newline, bool DryRun, unsigned ExtraSpaces=0)
Appends the next token to State and updates information necessary for indentation.
unsigned getColumnLimit (const LineState &State) const
Get the column limit for this line.
Detailed Description
Definition at line 50 of file ContinuationIndenter.h.
Constructor & Destructor Documentation
ContinuationIndenter()
clang::format::ContinuationIndenter::ContinuationIndenter (const FormatStyle & Style, const AdditionalKeywords & Keywords, const SourceManager & SourceMgr, WhitespaceManager & Whitespaces, encoding::Encoding Encoding, bool BinPackInconclusiveFunctions)
Constructs a ContinuationIndenter to format Line starting in column FirstIndent.
Definition at line 224 of file ContinuationIndenter.cpp.
Member Function Documentation
addTokenToState()
unsigned clang::format::ContinuationIndenter::addTokenToState (LineState & State, bool Newline, bool DryRun, unsigned ExtraSpaces = 0)
Appends the next token to State and updates information necessary for indentation.
Puts the token on the current line if Newline is false and adds a line break and necessary indentation otherwise.
If DryRun is false, also creates and stores the required Replacement.
Definition at line 525 of file ContinuationIndenter.cpp.
Referenced by clang::CommaSeparatedList::formatAfterToken().
canBreak()
bool clang::format::ContinuationIndenter::canBreak (const LineState & State)
Returns true, if a line break after State is allowed.
Definition at line 277 of file ContinuationIndenter.cpp.
References clang::format::BK_BracedInit, and Previous.
getColumnLimit()
unsigned clang::format::ContinuationIndenter::getColumnLimit (const LineState & State) const
Get the column limit for this line.
This is the style's column limit, potentially reduced for preprocessor definitions.
Definition at line 2356 of file ContinuationIndenter.cpp.
Referenced by mustBreak().
getInitialState()
LineState clang::format::ContinuationIndenter::getInitialState (unsigned FirstIndent, unsigned FirstStartColumn, const AnnotatedLine * Line, bool DryRun)
Get the initial state, i.e.
the state after placing Line's first token at FirstIndent. When reformatting a fragment of code, as in the case of formatting inside raw string literals, FirstStartColumn is the column at which the state of the parent formatter is.
Definition at line 235 of file ContinuationIndenter.cpp.
References clang::format::LineState::FirstIndent, clang::format::LT_ImportStatement, clang::format::LT_PreprocessorDirective, and State.
mustBreak()
bool clang::format::ContinuationIndenter::mustBreak (const LineState & State)
Returns true, if a line break after State is mandatory.
Definition at line 329 of file ContinuationIndenter.cpp.
References clang::prec::Assignment, clang::format::BK_Block, clang::prec::Equality, getColumnLimit(), clang::format::getLengthToMatchingParen(), clang::format::getLengthToNextOperator(), clang::format::FormatToken::is(), clang::AdditionalKeywords::kw_dollar, clang::format::opensProtoMessageField(), Previous, clang::prec::Relational, clang::prec::Spaceship, clang::format::startsNextParameter(), and clang::format::startsSegmentOfBuilderTypeCall().
The documentation for this class was generated from the following files:
lib/Format/ContinuationIndenter.h
lib/Format/ContinuationIndenter.cpp