clang: clang::Sema::SpecialMemberOverloadResult Class Reference
clang::Sema::SpecialMemberOverloadResult Class Reference
SpecialMemberOverloadResult - The overloading result for a special member function.
#include "clang/Sema/Sema.h"
Public Types
enum Kind { NoMemberOrDeleted , Ambiguous , Success }
Public Member Functions
SpecialMemberOverloadResult ()
SpecialMemberOverloadResult (CXXMethodDecl *MD)
CXXMethodDecl * getMethod () const
void setMethod (CXXMethodDecl *MD)
Kind getKind () const
void setKind (Kind K)
Detailed Description
SpecialMemberOverloadResult - The overloading result for a special member function.
This is basically a wrapper around PointerIntPair. The lowest bits of the integer are used to determine whether overload resolution succeeded.
Definition at line 1318 of file Sema.h.
Member Enumeration Documentation
Kind
enum clang::Sema::SpecialMemberOverloadResult::Kind
Enumerator
NoMemberOrDeleted
Ambiguous
Success
Definition at line 1320 of file Sema.h.
Constructor & Destructor Documentation
SpecialMemberOverloadResult() [1/2]
clang::Sema::SpecialMemberOverloadResult::SpecialMemberOverloadResult () inline
Definition at line 1330 of file Sema.h.
SpecialMemberOverloadResult() [2/2]
clang::Sema::SpecialMemberOverloadResult::SpecialMemberOverloadResult (CXXMethodDecl * MD) inline
Definition at line 1331 of file Sema.h.
Member Function Documentation
getKind()
Kind clang::Sema::SpecialMemberOverloadResult::getKind () const inline
Definition at line 1337 of file Sema.h.
Referenced by findTrivialSpecialMember().
getMethod()
CXXMethodDecl * clang::Sema::SpecialMemberOverloadResult::getMethod () const inline
Definition at line 1334 of file Sema.h.
Referenced by checkMoveAssignmentForRepeatedMove(), findTrivialSpecialMember(), clang::Sema::inferCUDATargetForImplicitSpecialMember(), and specialMemberIsConstexpr().
setKind()
void clang::Sema::SpecialMemberOverloadResult::setKind (Kind K) inline
Definition at line 1338 of file Sema.h.
setMethod()
void clang::Sema::SpecialMemberOverloadResult::setMethod (CXXMethodDecl * MD) inline
Definition at line 1335 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h