clang: clang::FileEntry Class Reference
clang::FileEntry Class Reference
Cached information about one file (either on disk or in the virtual file system).
#include "clang/Basic/FileEntry.h"
Public Member Functions
FileEntry ()
~FileEntry ()
FileEntry (const FileEntry &)=delete
FileEntry & operator= (const FileEntry &)=delete
StringRef getName () const
FileEntryRef getLastRef () const
StringRef tryGetRealPathName () const
bool isValid () const
off_t getSize () const
unsigned getUID () const
const llvm::sys::fs::UniqueID & getUniqueID () const
time_t getModificationTime () const
const DirectoryEntry * getDir () const
Return the directory the file lives in.
bool operator< (const FileEntry &RHS) const
bool isNamedPipe () const
Check whether the file is a named pipe (and thus can't be opened by the native FileManager methods).
void closeFile () const
Friends
class FileManager
Detailed Description
Cached information about one file (either on disk or in the virtual file system).
If the 'File' member is valid, then this FileEntry has an open file descriptor for the file.
Definition at line 331 of file FileEntry.h.
Constructor & Destructor Documentation
FileEntry() [1/2]
FileEntry::FileEntry ()
Definition at line 20 of file FileEntry.cpp.
~FileEntry()
FileEntry::~FileEntry () default
FileEntry() [2/2]
clang::FileEntry::FileEntry (const FileEntry &) delete
Member Function Documentation
closeFile()
void FileEntry::closeFile () const
Definition at line 24 of file FileEntry.cpp.
Referenced by clang::FileManager::getBufferForFile(), and clang::FileManager::getVirtualFileRef().
getDir()
const DirectoryEntry * clang::FileEntry::getDir () const inline
Return the directory the file lives in.
Definition at line 375 of file FileEntry.h.
Referenced by clang::ModuleMap::isHeaderUnavailableInModule(), and clang::Preprocessor::LookupFile().
getLastRef()
FileEntryRef clang::FileEntry::getLastRef () const inline
Definition at line 365 of file FileEntry.h.
Referenced by clang::SourceManager::createFileID(), and clang::SourceManager::overrideFileContents().
getModificationTime()
time_t clang::FileEntry::getModificationTime () const inline
Definition at line 372 of file FileEntry.h.
Referenced by clang::arcmt::FileRemapper::flushToFile(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), clang::ASTWriter::getTimestampForOutput(), and clang::Preprocessor::HandlePragmaDependency().
getName()
StringRef clang::FileEntry::getName () const inline
Definition at line 364 of file FileEntry.h.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_REGEX(), clang::tooling::AtomicChange::AtomicChange(), clang::FrontendAction::BeginSourceFile(), checkMSVCHeaderSearch(), compareCrossTUSourceLocs(), compileModule(), diagnoseFrameworkInclude(), clang::TextDiagnostic::emitDiagnosticLoc(), clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile(), clang::sema::SemaPPCallbacks::FileChanged(), clang::arcmt::FileRemapper::flushToFile(), clang::FileManager::getBufferForFile(), clang::SrcMgr::ContentCache::getBufferOrNone(), getFileName(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::ModuleMap::isHeaderUnavailableInModule(), clang::HeaderSearch::LookupSubframeworkHeader(), clang::Rewriter::overwriteChangedFiles(), clang::arcmt::FileRemapper::overwriteOriginal(), printLoc(), clang::index::SerializablePathCollection::tryStoreFilePath(), and clang::FixItRewriter::WriteFixedFiles().
getSize()
off_t clang::FileEntry::getSize () const inline
Definition at line 369 of file FileEntry.h.
Referenced by clang::HeaderMap::Create(), createArtifact(), clang::FileManager::getBufferForFile(), clang::SrcMgr::ContentCache::getBufferOrNone(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), clang::SrcMgr::ContentCache::getSize(), and clang::SourceManager::overrideFileContents().
getUID()
unsigned clang::FileEntry::getUID () const inline
Definition at line 370 of file FileEntry.h.
Referenced by clang::HeaderSearch::getExistingFileInfo(), clang::HeaderSearch::getFileInfo(), and clang::SourceManager::isMainFile().
getUniqueID()
const llvm::sys::fs::UniqueID & clang::FileEntry::getUniqueID () const inline
Definition at line 371 of file FileEntry.h.
isNamedPipe()
bool clang::FileEntry::isNamedPipe () const inline
Check whether the file is a named pipe (and thus can't be opened by the native FileManager methods).
Definition at line 381 of file FileEntry.h.
Referenced by clang::SourceManager::createFileID(), clang::FileManager::getBufferForFile(), and clang::SrcMgr::ContentCache::getBufferOrNone().
isValid()
bool clang::FileEntry::isValid () const inline
Definition at line 368 of file FileEntry.h.
Referenced by clang::TextDiagnostic::emitDiagnosticLoc(), clang::FileManager::getFileRef(), clang::FileManager::getVirtualFileRef(), and clang::LogDiagnosticPrinter::HandleDiagnostic().
operator<()
bool clang::FileEntry::operator< (const FileEntry & RHS) const inline
Definition at line 377 of file FileEntry.h.
operator=()
FileEntry & clang::FileEntry::operator= (const FileEntry &) delete
tryGetRealPathName()
StringRef clang::FileEntry::tryGetRealPathName () const inline
Definition at line 367 of file FileEntry.h.
Referenced by getFileName().
Friends And Related Symbol Documentation
FileManager
friend class FileManager friend
Definition at line 332 of file FileEntry.h.
The documentation for this class was generated from the following files:
include/clang/Basic/FileEntry.h
lib/Basic/FileEntry.cpp