clang: clang::OMPExecutableDirective Class Reference
clang::OMPExecutableDirective Class Reference
This is a basic class for representing single OpenMP executable directive.
#include "clang/AST/StmtOpenMP.h"
Classes
class specific_clause_iterator
Iterates over a filtered subrange of clauses applied to a directive.
class used_clauses_child_iterator
Iterates over expressions/statements used in the construct.
Public Member Functions
template<typename SpecificClause >
llvm::iterator_range< specific_clause_iterator< SpecificClause > > getClausesOfKind () const
template<typename SpecificClause >
const SpecificClause * getSingleClause () const
Gets a single clause of the specified kind associated with the current directive iff there is only one clause of this kind (and assertion is fired if there is more than one clause is associated with the directive).
template<typename SpecificClause >
bool hasClausesOfKind () const
Returns true if the current directive has one or more clauses of a specific kind.
SourceLocation getBeginLoc () const
Returns starting location of directive kind.
SourceLocation getEndLoc () const
Returns ending location of directive.
void setLocStart (SourceLocation Loc)
Set starting location of directive kind.
void setLocEnd (SourceLocation Loc)
Set ending location of directive.
unsigned getNumClauses () const
Get number of clauses.
OMPClause * getClause (unsigned I) const
Returns specified clause.
bool hasAssociatedStmt () const
Returns true if directive has associated statement.
const Stmt * getAssociatedStmt () const
Returns statement associated with the directive.
Stmt * getAssociatedStmt ()
const CapturedStmt * getCapturedStmt (OpenMPDirectiveKind RegionKind) const
Returns the captured statement associated with the component region within the (combined) directive.
CapturedStmt * getInnermostCapturedStmt ()
Get innermost captured statement for the construct.
const CapturedStmt * getInnermostCapturedStmt () const
OpenMPDirectiveKind getDirectiveKind () const
child_range children ()
const_child_range children () const
ArrayRef< OMPClause * > clauses () const
bool isStandaloneDirective () const
Returns whether or not this is a Standalone directive.
const Stmt * getStructuredBlock () const
Returns the AST node representing OpenMP structured-block of this OpenMP executable directive, Prerequisite: Executable Directive must not be Standalone directive.
Stmt * getStructuredBlock ()
const Stmt * getRawStmt () const
Stmt * getRawStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static llvm::iterator_range< used_clauses_child_iterator > used_clauses_children (ArrayRef< OMPClause * > Clauses)
template<typename SpecificClause >
static llvm::iterator_range< specific_clause_iterator< SpecificClause > > getClausesOfKind (ArrayRef< OMPClause * > Clauses)
static bool classof (const Stmt *S)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Protected Member Functions
OMPExecutableDirective (StmtClass SC, OpenMPDirectiveKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Build instance of directive of class K.
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Static Protected Member Functions
template<typename T , typename... Params>
static T * createDirective (const ASTContext &C, ArrayRef< OMPClause * > Clauses, Stmt *AssociatedStmt, unsigned NumChildren, Params &&... P)
template<typename T , typename... Params>
static T * createEmptyDirective (const ASTContext &C, unsigned NumClauses, bool HasAssociatedStmt, unsigned NumChildren, Params &&... P)
template<typename T >
static T * createEmptyDirective (const ASTContext &C, unsigned NumClauses, bool HasAssociatedStmt=false, unsigned NumChildren=0)
Protected Attributes
OMPChildren * Data = nullptr
Data, associated with the directive.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Friends
class ASTStmtReader
class ASTStmtWriter
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpessions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Detailed Description
This is a basic class for representing single OpenMP executable directive.
Definition at line 34 of file StmtOpenMP.h.
Constructor & Destructor Documentation
OMPExecutableDirective()
clang::OMPExecutableDirective::OMPExecutableDirective (StmtClass SC, OpenMPDirectiveKind K, SourceLocation StartLoc, SourceLocation EndLoc) inline protected
Build instance of directive of class K.
Parameters
SC Statement class.
K Kind of OpenMP directive.
StartLoc Starting location of the directive (directive keyword).
EndLoc Ending location of the directive.
Definition at line 63 of file StmtOpenMP.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPExecutableDirective::children () inline
Definition at line 325 of file StmtOpenMP.h.
References Data, and clang::OMPChildren::getAssociatedStmtAsRange().
Referenced by children().
children() [2/2]
const_child_range clang::OMPExecutableDirective::children () const inline
Definition at line 331 of file StmtOpenMP.h.
References children().
classof()
static bool clang::OMPExecutableDirective::classof (const Stmt * S) inline static
Definition at line 320 of file StmtOpenMP.h.
clauses()
ArrayRef< OMPClause * > clang::OMPExecutableDirective::clauses () const inline
Definition at line 335 of file StmtOpenMP.h.
References Data, and clang::OMPChildren::getClauses().
Referenced by getClause(), getClausesOfKind(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
createDirective()
template<typename T , typename... Params> static T * clang::OMPExecutableDirective::createDirective (const ASTContext & C, ArrayRef< OMPClause * > Clauses, Stmt * AssociatedStmt, unsigned NumChildren, Params &&... P) inline static protected
Definition at line 69 of file StmtOpenMP.h.
References clang::C, Data, and P.
Referenced by clang::OMPAtomicDirective::Create(), clang::OMPCancelDirective::Create(), clang::OMPCriticalDirective::Create(), clang::OMPDepobjDirective::Create(), clang::OMPDistributeDirective::Create(), clang::OMPDistributeParallelForDirective::Create(), clang::OMPDistributeParallelForSimdDirective::Create(), clang::OMPDistributeSimdDirective::Create(), clang::OMPFlushDirective::Create(), clang::OMPForDirective::Create(), clang::OMPForSimdDirective::Create(), clang::OMPMasterDirective::Create(), clang::OMPMasterTaskLoopDirective::Create(), clang::OMPMasterTaskLoopSimdDirective::Create(), clang::OMPOrderedDirective::Create(), clang::OMPParallelDirective::Create(), clang::OMPParallelForDirective::Create(), clang::OMPParallelForSimdDirective::Create(), clang::OMPParallelMasterDirective::Create(), clang::OMPParallelMasterTaskLoopDirective::Create(), clang::OMPParallelMasterTaskLoopSimdDirective::Create(), clang::OMPParallelSectionsDirective::Create(), clang::OMPScanDirective::Create(), clang::OMPSectionDirective::Create(), clang::OMPSectionsDirective::Create(), clang::OMPSimdDirective::Create(), clang::OMPSingleDirective::Create(), clang::OMPTargetDataDirective::Create(), clang::OMPTargetDirective::Create(), clang::OMPTargetEnterDataDirective::Create(), clang::OMPTargetExitDataDirective::Create(), clang::OMPTargetParallelDirective::Create(), clang::OMPTargetParallelForDirective::Create(), clang::OMPTargetParallelForSimdDirective::Create(), clang::OMPTargetSimdDirective::Create(), clang::OMPTargetTeamsDirective::Create(), clang::OMPTargetTeamsDistributeDirective::Create(), clang::OMPTargetTeamsDistributeParallelForDirective::Create(), clang::OMPTargetTeamsDistributeParallelForSimdDirective::Create(), clang::OMPTargetTeamsDistributeSimdDirective::Create(), clang::OMPTargetUpdateDirective::Create(), clang::OMPTaskDirective::Create(), clang::OMPTaskgroupDirective::Create(), clang::OMPTaskLoopDirective::Create(), clang::OMPTaskLoopSimdDirective::Create(), clang::OMPTeamsDirective::Create(), clang::OMPTeamsDistributeDirective::Create(), clang::OMPTeamsDistributeParallelForDirective::Create(), clang::OMPTeamsDistributeParallelForSimdDirective::Create(), and clang::OMPTeamsDistributeSimdDirective::Create().
createEmptyDirective() [1/2]
template<typename T , typename... Params> static T * clang::OMPExecutableDirective::createEmptyDirective (const ASTContext & C, unsigned NumClauses, bool HasAssociatedStmt, unsigned NumChildren, Params &&... P) inline static protected
Definition at line 85 of file StmtOpenMP.h.
References clang::C, Data, and P.
Referenced by clang::OMPAtomicDirective::CreateEmpty(), clang::OMPCancelDirective::CreateEmpty(), clang::OMPCriticalDirective::CreateEmpty(), clang::OMPDepobjDirective::CreateEmpty(), clang::OMPDistributeDirective::CreateEmpty(), clang::OMPDistributeParallelForDirective::CreateEmpty(), clang::OMPDistributeParallelForSimdDirective::CreateEmpty(), clang::OMPDistributeSimdDirective::CreateEmpty(), clang::OMPFlushDirective::CreateEmpty(), clang::OMPForDirective::CreateEmpty(), clang::OMPForSimdDirective::CreateEmpty(), clang::OMPMasterDirective::CreateEmpty(), clang::OMPMasterTaskLoopDirective::CreateEmpty(), clang::OMPMasterTaskLoopSimdDirective::CreateEmpty(), clang::OMPOrderedDirective::CreateEmpty(), clang::OMPParallelDirective::CreateEmpty(), clang::OMPParallelForDirective::CreateEmpty(), clang::OMPParallelForSimdDirective::CreateEmpty(), clang::OMPParallelMasterDirective::CreateEmpty(), clang::OMPParallelMasterTaskLoopDirective::CreateEmpty(), clang::OMPParallelMasterTaskLoopSimdDirective::CreateEmpty(), clang::OMPParallelSectionsDirective::CreateEmpty(), clang::OMPScanDirective::CreateEmpty(), clang::OMPSectionDirective::CreateEmpty(), clang::OMPSectionsDirective::CreateEmpty(), clang::OMPSimdDirective::CreateEmpty(), clang::OMPSingleDirective::CreateEmpty(), clang::OMPTargetDataDirective::CreateEmpty(), clang::OMPTargetDirective::CreateEmpty(), clang::OMPTargetEnterDataDirective::CreateEmpty(), clang::OMPTargetExitDataDirective::CreateEmpty(), clang::OMPTargetParallelDirective::CreateEmpty(), clang::OMPTargetParallelForDirective::CreateEmpty(), clang::OMPTargetParallelForSimdDirective::CreateEmpty(), clang::OMPTargetSimdDirective::CreateEmpty(), clang::OMPTargetTeamsDirective::CreateEmpty(), clang::OMPTargetTeamsDistributeDirective::CreateEmpty(), clang::OMPTargetTeamsDistributeParallelForDirective::CreateEmpty(), clang::OMPTargetTeamsDistributeParallelForSimdDirective::CreateEmpty(), clang::OMPTargetTeamsDistributeSimdDirective::CreateEmpty(), clang::OMPTargetUpdateDirective::CreateEmpty(), clang::OMPTaskDirective::CreateEmpty(), clang::OMPTaskgroupDirective::CreateEmpty(), clang::OMPTaskLoopDirective::CreateEmpty(), clang::OMPTaskLoopSimdDirective::CreateEmpty(), clang::OMPTeamsDirective::CreateEmpty(), clang::OMPTeamsDistributeDirective::CreateEmpty(), clang::OMPTeamsDistributeParallelForDirective::CreateEmpty(), clang::OMPTeamsDistributeParallelForSimdDirective::CreateEmpty(), and clang::OMPTeamsDistributeSimdDirective::CreateEmpty().
createEmptyDirective() [2/2]
template<typename T > static T * clang::OMPExecutableDirective::createEmptyDirective (const ASTContext & C, unsigned NumClauses, bool HasAssociatedStmt = false, unsigned NumChildren = 0) inline static protected
Definition at line 101 of file StmtOpenMP.h.
References clang::C, and Data.
getAssociatedStmt() [1/2]
Stmt * clang::OMPExecutableDirective::getAssociatedStmt () inline
Definition at line 286 of file StmtOpenMP.h.
References Data, clang::OMPChildren::getAssociatedStmt(), and hasAssociatedStmt().
getAssociatedStmt() [2/2]
const Stmt * clang::OMPExecutableDirective::getAssociatedStmt () const inline
Returns statement associated with the directive.
Definition at line 283 of file StmtOpenMP.h.
References getAssociatedStmt().
Referenced by getAssociatedStmt(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
getBeginLoc()
SourceLocation clang::OMPExecutableDirective::getBeginLoc () const inline
Returns starting location of directive kind.
Definition at line 251 of file StmtOpenMP.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitParallelOrTeamsOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunctionHelper(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
getCapturedStmt()
const CapturedStmt * clang::OMPExecutableDirective::getCapturedStmt (OpenMPDirectiveKind RegionKind) const inline
Returns the captured statement associated with the component region within the (combined) directive.
Parameters
RegionKind Component region kind.
Definition at line 296 of file StmtOpenMP.h.
References Data, clang::OMPChildren::getCapturedStmt(), getDirectiveKind(), clang::getOpenMPCaptureRegions(), and hasAssociatedStmt().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::emitParallelOutlinedFunction(), emitPrivatesInit(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunctionHelper(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitTeamsOutlinedFunction(), and clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction().
getClause()
OMPClause * clang::OMPExecutableDirective::getClause (unsigned I) const inline
Returns specified clause.
Parameters
I Number of clause.
Definition at line 277 of file StmtOpenMP.h.
References clauses().
getClausesOfKind() [1/2]
template<typename SpecificClause > llvm::iterator_range< specific_clause_iterator< SpecificClause > > clang::OMPExecutableDirective::getClausesOfKind () const inline
Definition at line 221 of file StmtOpenMP.h.
References clauses(), and getClausesOfKind().
Referenced by getClausesOfKind(), getCollapseNumberExpr(), getOrderedNumberExpr(), getSingleClause(), and hasClausesOfKind().
getClausesOfKind() [2/2]
template<typename SpecificClause > static llvm::iterator_range< specific_clause_iterator< SpecificClause > > clang::OMPExecutableDirective::getClausesOfKind (ArrayRef< OMPClause * > Clauses) inline static
Definition at line 213 of file StmtOpenMP.h.
Referenced by emitAlignedClause(), emitNumThreadsForTargetDirective(), emitPostUpdateForReductionClause(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunction(), getDistributeLastprivateVars(), getTeamsReductionVars(), and hasStaticScheduling().
getDirectiveKind()
OpenMPDirectiveKind clang::OMPExecutableDirective::getDirectiveKind () const inline
Definition at line 318 of file StmtOpenMP.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), emitPrivatesInit(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), getCapturedStmt(), clang::OMPLoopDirective::getCombinedCond(), clang::OMPLoopDirective::getCombinedDistCond(), clang::OMPLoopDirective::getCombinedEnsureUpperBound(), clang::OMPLoopDirective::getCombinedInit(), clang::OMPLoopDirective::getCombinedLowerBoundVariable(), clang::OMPLoopDirective::getCombinedNextLowerBound(), clang::OMPLoopDirective::getCombinedNextUpperBound(), clang::OMPLoopDirective::getCombinedParForInDistCond(), clang::OMPLoopDirective::getCombinedUpperBoundVariable(), clang::OMPLoopDirective::getDistInc(), getDistributeLastprivateVars(), clang::OMPLoopDirective::getEnsureUpperBound(), getInnermostCapturedStmt(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getLowerBoundVariable(), getNestedDistributeDirective(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getPrevEnsureUpperBound(), clang::OMPLoopDirective::getPrevLowerBoundVariable(), clang::OMPLoopDirective::getPrevUpperBoundVariable(), clang::OMPLoopDirective::getStrideVariable(), getTeamsReductionVars(), clang::OMPLoopDirective::getUpperBoundVariable(), hasNestedLightweightDirective(), hasNestedSPMDDirective(), hasStaticScheduling(), clang::OMPLoopDirective::setCombinedCond(), clang::OMPLoopDirective::setCombinedDistCond(), clang::OMPLoopDirective::setCombinedEnsureUpperBound(), clang::OMPLoopDirective::setCombinedInit(), clang::OMPLoopDirective::setCombinedLowerBoundVariable(), clang::OMPLoopDirective::setCombinedNextLowerBound(), clang::OMPLoopDirective::setCombinedNextUpperBound(), clang::OMPLoopDirective::setCombinedParForInDistCond(), clang::OMPLoopDirective::setCombinedUpperBoundVariable(), clang::OMPLoopDirective::setDistInc(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setPrevEnsureUpperBound(), clang::OMPLoopDirective::setPrevLowerBoundVariable(), clang::OMPLoopDirective::setPrevUpperBoundVariable(), clang::OMPLoopDirective::setStrideVariable(), clang::OMPLoopDirective::setUpperBoundVariable(), supportsLightweightRuntime(), supportsSPMDExecutionMode(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
getEndLoc()
SourceLocation clang::OMPExecutableDirective::getEndLoc () const inline
Returns ending location of directive.
Definition at line 253 of file StmtOpenMP.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
getInnermostCapturedStmt() [1/2]
CapturedStmt * clang::OMPExecutableDirective::getInnermostCapturedStmt () inline
Get innermost captured statement for the construct.
Definition at line 305 of file StmtOpenMP.h.
References Data, getDirectiveKind(), clang::OMPChildren::getInnermostCapturedStmt(), clang::getOpenMPCaptureRegions(), and hasAssociatedStmt().
Referenced by emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), getDistributeLastprivateVars(), getInnermostCapturedStmt(), getNestedDistributeDirective(), hasNestedLightweightDirective(), hasNestedSPMDDirective(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
getInnermostCapturedStmt() [2/2]
const CapturedStmt * clang::OMPExecutableDirective::getInnermostCapturedStmt () const inline
Definition at line 313 of file StmtOpenMP.h.
References getInnermostCapturedStmt().
getNumClauses()
unsigned clang::OMPExecutableDirective::getNumClauses () const inline
Get number of clauses.
Definition at line 267 of file StmtOpenMP.h.
References Data, and clang::OMPChildren::getNumClauses().
getRawStmt() [1/2]
Stmt * clang::OMPExecutableDirective::getRawStmt () inline
Definition at line 358 of file StmtOpenMP.h.
References Data, clang::OMPChildren::getRawStmt(), and hasAssociatedStmt().
getRawStmt() [2/2]
const Stmt * clang::OMPExecutableDirective::getRawStmt () const inline
Definition at line 355 of file StmtOpenMP.h.
References getRawStmt().
Referenced by getRawStmt(), and getStructuredBlock().
getSingleClause()
template<typename SpecificClause > const SpecificClause * clang::OMPExecutableDirective::getSingleClause () const inline
Gets a single clause of the specified kind associated with the current directive iff there is only one clause of this kind (and assertion is fired if there is more than one clause is associated with the directive).
Returns nullptr if no clause of this kind is associated with the directive.
Definition at line 231 of file StmtOpenMP.h.
References getClausesOfKind().
Referenced by emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), and emitSimdlenSafelenClause().
getStructuredBlock() [1/2]
Stmt * OMPExecutableDirective::getStructuredBlock ()
Definition at line 69 of file StmtOpenMP.cpp.
References getRawStmt(), and isStandaloneDirective().
getStructuredBlock() [2/2]
const Stmt * clang::OMPExecutableDirective::getStructuredBlock () const inline
Returns the AST node representing OpenMP structured-block of this OpenMP executable directive, Prerequisite: Executable Directive must not be Standalone directive.
Definition at line 350 of file StmtOpenMP.h.
References getStructuredBlock().
Referenced by getStructuredBlock().
hasAssociatedStmt()
bool clang::OMPExecutableDirective::hasAssociatedStmt () const inline
Returns true if directive has associated statement.
Definition at line 280 of file StmtOpenMP.h.
References Data, and clang::OMPChildren::hasAssociatedStmt().
Referenced by getAssociatedStmt(), getCapturedStmt(), getInnermostCapturedStmt(), getRawStmt(), isStandaloneDirective(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
hasClausesOfKind()
template<typename SpecificClause > bool clang::OMPExecutableDirective::hasClausesOfKind () const inline
Returns true if the current directive has one or more clauses of a specific kind.
Definition at line 245 of file StmtOpenMP.h.
References getClausesOfKind().
Referenced by emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), and hasStaticScheduling().
isStandaloneDirective()
bool OMPExecutableDirective::isStandaloneDirective () const
Returns whether or not this is a Standalone directive.
Stand-alone directives are executable directives that have no associated user code.
Definition at line 58 of file StmtOpenMP.cpp.
References hasAssociatedStmt().
Referenced by getStructuredBlock(), and clang::TextNodeDumper::VisitOMPExecutableDirective().
setLocEnd()
void clang::OMPExecutableDirective::setLocEnd (SourceLocation Loc) inline
Set ending location of directive.
Parameters
Loc New ending location of directive.
Definition at line 264 of file StmtOpenMP.h.
setLocStart()
void clang::OMPExecutableDirective::setLocStart (SourceLocation Loc) inline
Set starting location of directive kind.
Parameters
Loc New starting location of directive.
Definition at line 259 of file StmtOpenMP.h.
used_clauses_children()
static llvm::iterator_range< used_clauses_child_iterator > clang::OMPExecutableDirective::used_clauses_children (ArrayRef< OMPClause * > Clauses) inline static
Definition at line 169 of file StmtOpenMP.h.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 35 of file StmtOpenMP.h.
ASTStmtWriter
friend class ASTStmtWriter friend
Definition at line 36 of file StmtOpenMP.h.
Member Data Documentation
Data
OMPChildren* clang::OMPExecutableDirective::Data = nullptr protected
Data, associated with the directive.
Definition at line 54 of file StmtOpenMP.h.
Referenced by children(), clauses(), createDirective(), createEmptyDirective(), createEmptyDirective(), getAssociatedStmt(), clang::OMPLoopDirective::getBody(), clang::OMPLoopDirective::getCalcLastIteration(), getCapturedStmt(), clang::OMPLoopDirective::getCombinedCond(), clang::OMPLoopDirective::getCombinedDistCond(), clang::OMPLoopDirective::getCombinedEnsureUpperBound(), clang::OMPLoopDirective::getCombinedInit(), clang::OMPLoopDirective::getCombinedLowerBoundVariable(), clang::OMPLoopDirective::getCombinedNextLowerBound(), clang::OMPLoopDirective::getCombinedNextUpperBound(), clang::OMPLoopDirective::getCombinedParForInDistCond(), clang::OMPLoopDirective::getCombinedUpperBoundVariable(), clang::OMPLoopDirective::getCond(), clang::OMPLoopDirective::getDistInc(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::OMPAtomicDirective::getExpr(), clang::OMPAtomicDirective::getExpr(), clang::OMPLoopDirective::getInc(), clang::OMPLoopDirective::getInit(), getInnermostCapturedStmt(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getIterationVariable(), clang::OMPLoopDirective::getLastIteration(), clang::OMPLoopDirective::getLowerBoundVariable(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), getNumClauses(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getPreCond(), clang::OMPLoopDirective::getPreInits(), clang::OMPLoopDirective::getPreInits(), clang::OMPLoopDirective::getPrevEnsureUpperBound(), clang::OMPLoopDirective::getPrevLowerBoundVariable(), clang::OMPLoopDirective::getPrevUpperBoundVariable(), getRawStmt(), clang::OMPTaskgroupDirective::getReductionRef(), clang::OMPLoopDirective::getStrideVariable(), clang::OMPDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPForDirective::getTaskReductionRefExpr(), clang::OMPParallelDirective::getTaskReductionRefExpr(), clang::OMPParallelForDirective::getTaskReductionRefExpr(), clang::OMPParallelMasterDirective::getTaskReductionRefExpr(), clang::OMPParallelSectionsDirective::getTaskReductionRefExpr(), clang::OMPSectionsDirective::getTaskReductionRefExpr(), clang::OMPTargetParallelDirective::getTaskReductionRefExpr(), clang::OMPTargetParallelForDirective::getTaskReductionRefExpr(), clang::OMPTargetTeamsDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPTeamsDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPAtomicDirective::getUpdateExpr(), clang::OMPAtomicDirective::getUpdateExpr(), clang::OMPLoopDirective::getUpperBoundVariable(), clang::OMPAtomicDirective::getV(), clang::OMPAtomicDirective::getV(), clang::OMPAtomicDirective::getX(), clang::OMPAtomicDirective::getX(), hasAssociatedStmt(), clang::OMPLoopDirective::setCalcLastIteration(), clang::OMPLoopDirective::setCombinedCond(), clang::OMPLoopDirective::setCombinedDistCond(), clang::OMPLoopDirective::setCombinedEnsureUpperBound(), clang::OMPLoopDirective::setCombinedInit(), clang::OMPLoopDirective::setCombinedLowerBoundVariable(), clang::OMPLoopDirective::setCombinedNextLowerBound(), clang::OMPLoopDirective::setCombinedNextUpperBound(), clang::OMPLoopDirective::setCombinedParForInDistCond(), clang::OMPLoopDirective::setCombinedUpperBoundVariable(), clang::OMPLoopDirective::setCond(), clang::OMPLoopDirective::setDistInc(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setInc(), clang::OMPLoopDirective::setInit(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setIterationVariable(), clang::OMPLoopDirective::setLastIteration(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setPreCond(), clang::OMPLoopDirective::setPreInits(), clang::OMPLoopDirective::setPrevEnsureUpperBound(), clang::OMPLoopDirective::setPrevLowerBoundVariable(), clang::OMPLoopDirective::setPrevUpperBoundVariable(), clang::OMPLoopDirective::setStrideVariable(), and clang::OMPLoopDirective::setUpperBoundVariable().
The documentation for this class was generated from the following files:
include/clang/AST/StmtOpenMP.h
lib/AST/StmtOpenMP.cpp