clang: clang::ObjCObjectTypeLoc Class Reference
clang::ObjCObjectTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getTypeArgsLAngleLoc () const
void setTypeArgsLAngleLoc (SourceLocation Loc)
SourceLocation getTypeArgsRAngleLoc () const
void setTypeArgsRAngleLoc (SourceLocation Loc)
unsigned getNumTypeArgs () const
TypeSourceInfo * getTypeArgTInfo (unsigned i) const
void setTypeArgTInfo (unsigned i, TypeSourceInfo *TInfo)
SourceLocation getProtocolLAngleLoc () const
void setProtocolLAngleLoc (SourceLocation Loc)
SourceLocation getProtocolRAngleLoc () const
void setProtocolRAngleLoc (SourceLocation Loc)
unsigned getNumProtocols () const
SourceLocation getProtocolLoc (unsigned i) const
void setProtocolLoc (unsigned i, SourceLocation Loc)
ObjCProtocolDecl * getProtocol (unsigned i) const
ArrayRef< SourceLocation > getProtocolLocs () const
bool hasBaseTypeAsWritten () const
void setHasBaseTypeAsWritten (bool HasBaseType)
TypeLoc getBaseLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (ObjCObjectTypeLoc other)
TypeLoc getNextTypeLoc () const
const ObjCObjectType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
ObjCObjectTypeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Definition at line 908 of file TypeLoc.h.
Member Function Documentation
getBaseLoc()
TypeLoc clang::ObjCObjectTypeLoc::getBaseLoc () const inline
Definition at line 1002 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getInnerTypeLoc().
getExtraLocalDataAlignment()
unsigned clang::ObjCObjectTypeLoc::getExtraLocalDataAlignment () const inline
Definition at line 1023 of file TypeLoc.h.
getExtraLocalDataSize()
unsigned clang::ObjCObjectTypeLoc::getExtraLocalDataSize () const inline
Definition at line 1018 of file TypeLoc.h.
References getNumProtocols(), and getNumTypeArgs().
getInnerType()
QualType clang::ObjCObjectTypeLoc::getInnerType () const inline
Definition at line 1029 of file TypeLoc.h.
References clang::ObjCObjectType::getBaseType(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getTypePtr().
getLocalSourceRange()
SourceRange clang::ObjCObjectTypeLoc::getLocalSourceRange () const inline
Definition at line 1006 of file TypeLoc.h.
References getProtocolLAngleLoc(), getProtocolRAngleLoc(), getTypeArgsLAngleLoc(), getTypeArgsRAngleLoc(), and clang::SourceLocation::isInvalid().
getNumProtocols()
unsigned clang::ObjCObjectTypeLoc::getNumProtocols () const inline
Definition at line 970 of file TypeLoc.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getTypePtr().
Referenced by getExtraLocalDataSize(), getProtocol(), getProtocolLoc(), getProtocolLocs(), initializeLocal(), and setProtocolLoc().
getNumTypeArgs()
unsigned clang::ObjCObjectTypeLoc::getNumTypeArgs () const inline
Definition at line 940 of file TypeLoc.h.
References clang::ObjCObjectType::getTypeArgsAsWritten(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getTypePtr().
Referenced by getExtraLocalDataSize(), getTypeArgTInfo(), initializeLocal(), and setTypeArgTInfo().
getProtocol()
ObjCProtocolDecl * clang::ObjCObjectTypeLoc::getProtocol (unsigned i) const inline
Definition at line 984 of file TypeLoc.h.
References getNumProtocols(), clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getTypePtr(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
getProtocolLAngleLoc()
SourceLocation clang::ObjCObjectTypeLoc::getProtocolLAngleLoc () const inline
Definition at line 954 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::ProtocolLAngleLoc.
Referenced by getLocalSourceRange().
getProtocolLoc()
SourceLocation clang::ObjCObjectTypeLoc::getProtocolLoc (unsigned i) const inline
Definition at line 974 of file TypeLoc.h.
References getNumProtocols().
getProtocolLocs()
ArrayRef< SourceLocation > clang::ObjCObjectTypeLoc::getProtocolLocs () const inline
Definition at line 990 of file TypeLoc.h.
References getNumProtocols().
getProtocolRAngleLoc()
SourceLocation clang::ObjCObjectTypeLoc::getProtocolRAngleLoc () const inline
Definition at line 962 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::ProtocolRAngleLoc.
Referenced by getLocalSourceRange().
getTypeArgsLAngleLoc()
SourceLocation clang::ObjCObjectTypeLoc::getTypeArgsLAngleLoc () const inline
Definition at line 924 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::TypeArgsLAngleLoc.
Referenced by getLocalSourceRange().
getTypeArgsRAngleLoc()
SourceLocation clang::ObjCObjectTypeLoc::getTypeArgsRAngleLoc () const inline
Definition at line 932 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::TypeArgsRAngleLoc.
Referenced by getLocalSourceRange().
getTypeArgTInfo()
TypeSourceInfo * clang::ObjCObjectTypeLoc::getTypeArgTInfo (unsigned i) const inline
Definition at line 944 of file TypeLoc.h.
References getNumTypeArgs().
hasBaseTypeAsWritten()
bool clang::ObjCObjectTypeLoc::hasBaseTypeAsWritten () const inline
Definition at line 994 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::HasBaseTypeAsWritten.
initializeLocal()
void ObjCObjectTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc)
Definition at line 469 of file TypeLoc.cpp.
References getNumProtocols(), getNumTypeArgs(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getTypePtr(), setHasBaseTypeAsWritten(), setProtocolLAngleLoc(), setProtocolLoc(), setProtocolRAngleLoc(), setTypeArgsLAngleLoc(), setTypeArgsRAngleLoc(), and setTypeArgTInfo().
setHasBaseTypeAsWritten()
void clang::ObjCObjectTypeLoc::setHasBaseTypeAsWritten (bool HasBaseType) inline
Definition at line 998 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::HasBaseTypeAsWritten.
Referenced by clang::Sema::actOnObjCProtocolQualifierType(), clang::Sema::actOnObjCTypeArgsAndProtocolQualifiers(), and initializeLocal().
setProtocolLAngleLoc()
void clang::ObjCObjectTypeLoc::setProtocolLAngleLoc (SourceLocation Loc) inline
Definition at line 958 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::ProtocolLAngleLoc.
Referenced by initializeLocal().
setProtocolLoc()
void clang::ObjCObjectTypeLoc::setProtocolLoc (unsigned i, SourceLocation Loc) inline
Definition at line 979 of file TypeLoc.h.
References getNumProtocols().
Referenced by initializeLocal().
setProtocolRAngleLoc()
void clang::ObjCObjectTypeLoc::setProtocolRAngleLoc (SourceLocation Loc) inline
Definition at line 966 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::ProtocolRAngleLoc.
Referenced by initializeLocal().
setTypeArgsLAngleLoc()
void clang::ObjCObjectTypeLoc::setTypeArgsLAngleLoc (SourceLocation Loc) inline
Definition at line 928 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::TypeArgsLAngleLoc.
Referenced by initializeLocal().
setTypeArgsRAngleLoc()
void clang::ObjCObjectTypeLoc::setTypeArgsRAngleLoc (SourceLocation Loc) inline
Definition at line 936 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCObjectTypeLoc, ObjCObjectType, ObjCObjectTypeLocInfo >::getLocalData(), and clang::ObjCObjectTypeLocInfo::TypeArgsRAngleLoc.
Referenced by initializeLocal().
setTypeArgTInfo()
void clang::ObjCObjectTypeLoc::setTypeArgTInfo (unsigned i, TypeSourceInfo * TInfo) inline
Definition at line 949 of file TypeLoc.h.
References getNumTypeArgs().
Referenced by initializeLocal().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp