clang: clang::TraversalKindScope Class Reference
clang::TraversalKindScope Class Reference
#include "clang/AST/ParentMapContext.h"
Public Member Functions
TraversalKindScope (ASTContext &ASTCtx, llvm::Optional< TraversalKind > ScopeTK)
~TraversalKindScope ()
Detailed Description
Definition at line 74 of file ParentMapContext.h.
Constructor & Destructor Documentation
TraversalKindScope()
clang::TraversalKindScope::TraversalKindScope (ASTContext & ASTCtx, llvm::Optional< TraversalKind > ScopeTK) inline
Definition at line 79 of file ParentMapContext.h.
References clang::ParentMapContext::getTraversalKind(), and clang::ParentMapContext::setTraversalKind().
~TraversalKindScope()
clang::TraversalKindScope::~TraversalKindScope () inline
Definition at line 86 of file ParentMapContext.h.
References clang::ParentMapContext::setTraversalKind().
The documentation for this class was generated from the following file:
include/clang/AST/ParentMapContext.h