clang: clang::driver::tools::OffloadWrapper Class Reference
clang::driver::tools::OffloadWrapper Class Reference final
Offload wrapper tool.
#include "/root/llvm-project/clang/lib/Driver/ToolChains/Clang.h"
Public Member Functions
OffloadWrapper (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Offload wrapper tool.
Definition at line 160 of file Clang.h.
Constructor & Destructor Documentation
OffloadWrapper()
clang::driver::tools::OffloadWrapper::OffloadWrapper (const ToolChain & TC) inline
Definition at line 162 of file Clang.h.
Member Function Documentation
ConstructJob()
void OffloadWrapper::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 7472 of file Clang.cpp.
References clang::C, clang::driver::ToolChain::getEffectiveTriple(), clang::driver::InputInfo::getFilename(), clang::driver::Tool::getShortName(), clang::driver::Tool::getToolChain(), clang::driver::InputInfo::isFilename(), and clang::driver::ResponseFileSupport::None().
hasIntegratedCPP()
bool clang::driver::tools::OffloadWrapper::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 165 of file Clang.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Clang.h
lib/Driver/ToolChains/Clang.cpp