clang: clang::Sema::VerifyICEDiagnoser Class Reference
clang::Sema::VerifyICEDiagnoser Class Reference abstract
Abstract base class used for diagnosing integer constant expression violations.
#include "clang/Sema/Sema.h"
Public Member Functions
VerifyICEDiagnoser (bool Suppress=false)
virtual SemaDiagnosticBuilder diagnoseNotICEType (Sema &S, SourceLocation Loc, QualType T)
virtual SemaDiagnosticBuilder diagnoseNotICE (Sema &S, SourceLocation Loc)=0
virtual SemaDiagnosticBuilder diagnoseFold (Sema &S, SourceLocation Loc)
virtual ~VerifyICEDiagnoser ()
Public Attributes
bool Suppress
Detailed Description
Abstract base class used for diagnosing integer constant expression violations.
Definition at line 11824 of file Sema.h.
Constructor & Destructor Documentation
VerifyICEDiagnoser()
clang::Sema::VerifyICEDiagnoser::VerifyICEDiagnoser (bool Suppress = false) inline
Definition at line 11828 of file Sema.h.
~VerifyICEDiagnoser()
virtual clang::Sema::VerifyICEDiagnoser::~VerifyICEDiagnoser () inline virtual
Definition at line 11835 of file Sema.h.
Member Function Documentation
diagnoseFold()
Sema::SemaDiagnosticBuilder Sema::VerifyICEDiagnoser::diagnoseFold (Sema & S, SourceLocation Loc) virtual
Definition at line 16051 of file SemaExpr.cpp.
References clang::Sema::Diag(), and clang::Sema::LangOpts.
Referenced by clang::Sema::VerifyIntegerConstantExpression().
diagnoseNotICE()
virtual SemaDiagnosticBuilder clang::Sema::VerifyICEDiagnoser::diagnoseNotICE (Sema & S, SourceLocation Loc) pure virtual
Referenced by diagnoseNotICEType(), and clang::Sema::VerifyIntegerConstantExpression().
diagnoseNotICEType()
Sema::SemaDiagnosticBuilder Sema::VerifyICEDiagnoser::diagnoseNotICEType (Sema & S, SourceLocation Loc, QualType T) virtual
Definition at line 16045 of file SemaExpr.cpp.
References diagnoseNotICE().
Referenced by clang::Sema::VerifyIntegerConstantExpression().
Member Data Documentation
Suppress
bool clang::Sema::VerifyICEDiagnoser::Suppress
Definition at line 11826 of file Sema.h.
Referenced by clang::Sema::VerifyIntegerConstantExpression().
The documentation for this class was generated from the following files:
include/clang/Sema/Sema.h
lib/Sema/SemaExpr.cpp