clang: clang::ObjCDeclSpec Class Reference
clang::ObjCDeclSpec Class Reference
Captures information about "declaration specifiers" specific to Objective-C.
#include "clang/Sema/DeclSpec.h"
Public Types
enum ObjCDeclQualifier {
DQ_None = 0x0 , DQ_In = 0x1 , DQ_Inout = 0x2 , DQ_Out = 0x4 ,
DQ_Bycopy = 0x8 , DQ_Byref = 0x10 , DQ_Oneway = 0x20 , DQ_CSNullability = 0x40
}
ObjCDeclQualifier - Qualifier used on types in method declarations.
Public Member Functions
ObjCDeclSpec ()
ObjCDeclQualifier getObjCDeclQualifier () const
void setObjCDeclQualifier (ObjCDeclQualifier DQVal)
void clearObjCDeclQualifier (ObjCDeclQualifier DQVal)
ObjCPropertyAttribute::Kind getPropertyAttributes () const
void setPropertyAttributes (ObjCPropertyAttribute::Kind PRVal)
NullabilityKind getNullability () const
SourceLocation getNullabilityLoc () const
void setNullability (SourceLocation loc, NullabilityKind kind)
const IdentifierInfo * getGetterName () const
IdentifierInfo * getGetterName ()
SourceLocation getGetterNameLoc () const
void setGetterName (IdentifierInfo *name, SourceLocation loc)
const IdentifierInfo * getSetterName () const
IdentifierInfo * getSetterName ()
SourceLocation getSetterNameLoc () const
void setSetterName (IdentifierInfo *name, SourceLocation loc)
Detailed Description
Captures information about "declaration specifiers" specific to Objective-C.
Definition at line 822 of file DeclSpec.h.
Member Enumeration Documentation
ObjCDeclQualifier
enum clang::ObjCDeclSpec::ObjCDeclQualifier
ObjCDeclQualifier - Qualifier used on types in method declarations.
Not all combinations are sensible. Parameters can be one of { in, out, inout } with one of { bycopy, byref }. Returns can either be { oneway } or not.
This should be kept in sync with Decl::ObjCDeclQualifier.
Enumerator
DQ_None
DQ_In
DQ_Inout
DQ_Out
DQ_Bycopy
DQ_Byref
DQ_Oneway
DQ_CSNullability
Definition at line 830 of file DeclSpec.h.
Constructor & Destructor Documentation
ObjCDeclSpec()
clang::ObjCDeclSpec::ObjCDeclSpec () inline
Definition at line 841 of file DeclSpec.h.
Member Function Documentation
clearObjCDeclQualifier()
void clang::ObjCDeclSpec::clearObjCDeclQualifier (ObjCDeclQualifier DQVal) inline
Definition at line 852 of file DeclSpec.h.
getGetterName() [1/2]
IdentifierInfo * clang::ObjCDeclSpec::getGetterName () inline
Definition at line 890 of file DeclSpec.h.
getGetterName() [2/2]
const IdentifierInfo * clang::ObjCDeclSpec::getGetterName () const inline
Definition at line 889 of file DeclSpec.h.
getGetterNameLoc()
SourceLocation clang::ObjCDeclSpec::getGetterNameLoc () const inline
Definition at line 891 of file DeclSpec.h.
Referenced by clang::Sema::ActOnProperty().
getNullability()
NullabilityKind clang::ObjCDeclSpec::getNullability () const inline
Definition at line 864 of file DeclSpec.h.
References DQ_CSNullability, getObjCDeclQualifier(), getPropertyAttributes(), and clang::ObjCPropertyAttribute::kind_nullability.
Referenced by diagnoseRedundantPropertyNullability().
getNullabilityLoc()
SourceLocation clang::ObjCDeclSpec::getNullabilityLoc () const inline
Definition at line 872 of file DeclSpec.h.
References DQ_CSNullability, getObjCDeclQualifier(), getPropertyAttributes(), and clang::ObjCPropertyAttribute::kind_nullability.
Referenced by diagnoseRedundantPropertyNullability().
getObjCDeclQualifier()
ObjCDeclQualifier clang::ObjCDeclSpec::getObjCDeclQualifier () const inline
Definition at line 846 of file DeclSpec.h.
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::CodeCompleteObjCPassingType(), getNullability(), getNullabilityLoc(), and setNullability().
getPropertyAttributes()
ObjCPropertyAttribute::Kind clang::ObjCDeclSpec::getPropertyAttributes () const inline
Definition at line 856 of file DeclSpec.h.
Referenced by clang::Sema::ActOnProperty(), clang::Sema::CodeCompleteObjCPropertyFlags(), getNullability(), getNullabilityLoc(), and setNullability().
getSetterName() [1/2]
IdentifierInfo * clang::ObjCDeclSpec::getSetterName () inline
Definition at line 898 of file DeclSpec.h.
getSetterName() [2/2]
const IdentifierInfo * clang::ObjCDeclSpec::getSetterName () const inline
Definition at line 897 of file DeclSpec.h.
getSetterNameLoc()
SourceLocation clang::ObjCDeclSpec::getSetterNameLoc () const inline
Definition at line 899 of file DeclSpec.h.
Referenced by clang::Sema::ActOnProperty().
setGetterName()
void clang::ObjCDeclSpec::setGetterName (IdentifierInfo * name, SourceLocation loc) inline
Definition at line 892 of file DeclSpec.h.
setNullability()
void clang::ObjCDeclSpec::setNullability (SourceLocation loc, NullabilityKind kind) inline
Definition at line 880 of file DeclSpec.h.
References DQ_CSNullability, getObjCDeclQualifier(), getPropertyAttributes(), and clang::ObjCPropertyAttribute::kind_nullability.
setObjCDeclQualifier()
void clang::ObjCDeclSpec::setObjCDeclQualifier (ObjCDeclQualifier DQVal) inline
Definition at line 849 of file DeclSpec.h.
setPropertyAttributes()
void clang::ObjCDeclSpec::setPropertyAttributes (ObjCPropertyAttribute::Kind PRVal) inline
Definition at line 859 of file DeclSpec.h.
setSetterName()
void clang::ObjCDeclSpec::setSetterName (IdentifierInfo * name, SourceLocation loc) inline
Definition at line 900 of file DeclSpec.h.
The documentation for this class was generated from the following file:
include/clang/Sema/DeclSpec.h