clang: clang::FunctionType::ExtInfo Class Reference
clang::FunctionType::ExtInfo Class Reference
A class which abstracts out some details necessary for making a call.
#include "clang/AST/Type.h"
Public Member Functions
ExtInfo (bool noReturn, bool hasRegParm, unsigned regParm, CallingConv cc, bool producesResult, bool noCallerSavedRegs, bool NoCfCheck, bool cmseNSCall)
ExtInfo ()=default
ExtInfo (CallingConv CC)
bool getNoReturn () const
bool getProducesResult () const
bool getCmseNSCall () const
bool getNoCallerSavedRegs () const
bool getNoCfCheck () const
bool getHasRegParm () const
unsigned getRegParm () const
CallingConv getCC () const
bool operator== (ExtInfo Other) const
bool operator!= (ExtInfo Other) const
ExtInfo withNoReturn (bool noReturn) const
ExtInfo withProducesResult (bool producesResult) const
ExtInfo withCmseNSCall (bool cmseNSCall) const
ExtInfo withNoCallerSavedRegs (bool noCallerSavedRegs) const
ExtInfo withNoCfCheck (bool noCfCheck) const
ExtInfo withRegParm (unsigned RegParm) const
ExtInfo withCallingConv (CallingConv cc) const
void Profile (llvm::FoldingSetNodeID &ID) const
Friends
class FunctionType
Detailed Description
A class which abstracts out some details necessary for making a call.
It is not actually used directly for storing this information in a FunctionType, although FunctionType does currently use the same bit-pattern.
Definition at line 3649 of file Type.h.
Constructor & Destructor Documentation
ExtInfo() [1/3]
clang::FunctionType::ExtInfo::ExtInfo (bool noReturn, bool hasRegParm, unsigned regParm, CallingConv cc, bool producesResult, bool noCallerSavedRegs, bool NoCfCheck, bool cmseNSCall) inline
Definition at line 3677 of file Type.h.
ExtInfo() [2/3]
clang::FunctionType::ExtInfo::ExtInfo () default
Referenced by withCallingConv(), withCmseNSCall(), withNoCallerSavedRegs(), withNoCfCheck(), withNoReturn(), withProducesResult(), and withRegParm().
ExtInfo() [3/3]
clang::FunctionType::ExtInfo::ExtInfo (CallingConv CC) inline
Definition at line 3695 of file Type.h.
Member Function Documentation
getCC()
CallingConv clang::FunctionType::ExtInfo::getCC () const inline
Definition at line 3711 of file Type.h.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::areMultiversionVariantFunctionsCompatible(), clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), checkExtParameterInfos(), clang::CodeGen::CGFunctionInfo::create(), clang::FunctionType::getCallConv(), IsStructurallyEquivalent(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::CodeGen::CGFunctionInfo::Profile(), and clang::JSONNodeDumper::VisitFunctionType().
getCmseNSCall()
bool clang::FunctionType::ExtInfo::getCmseNSCall () const inline
Definition at line 3699 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), clang::FunctionType::getCmseNSCallAttr(), IsInvalidCmseNSCallConversion(), and clang::CodeGen::CGFunctionInfo::Profile().
getHasRegParm()
bool clang::FunctionType::ExtInfo::getHasRegParm () const inline
Definition at line 3702 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), clang::FunctionType::getHasRegParm(), IsStructurallyEquivalent(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::CodeGen::CGFunctionInfo::Profile(), and clang::JSONNodeDumper::VisitFunctionType().
getNoCallerSavedRegs()
bool clang::FunctionType::ExtInfo::getNoCallerSavedRegs () const inline
Definition at line 3700 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), IsStructurallyEquivalent(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), and clang::CodeGen::CGFunctionInfo::Profile().
getNoCfCheck()
bool clang::FunctionType::ExtInfo::getNoCfCheck () const inline
Definition at line 3701 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), IsStructurallyEquivalent(), clang::ASTContext::mergeFunctionTypes(), and clang::CodeGen::CGFunctionInfo::Profile().
getNoReturn()
bool clang::FunctionType::ExtInfo::getNoReturn () const inline
Definition at line 3697 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), clang::Sema::FindCompositePointerType(), clang::FunctionType::getNoReturnAttr(), clang::Sema::IsFunctionConversion(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::CodeGen::CGFunctionInfo::Profile(), and clang::JSONNodeDumper::VisitFunctionType().
getProducesResult()
bool clang::FunctionType::ExtInfo::getProducesResult () const inline
Definition at line 3698 of file Type.h.
Referenced by clang::Sema::BuildFunctionType(), clang::CodeGen::CGFunctionInfo::create(), IsStructurallyEquivalent(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::CodeGen::CGFunctionInfo::Profile(), and clang::JSONNodeDumper::VisitFunctionType().
getRegParm()
unsigned clang::FunctionType::ExtInfo::getRegParm () const inline
Definition at line 3704 of file Type.h.
Referenced by clang::CodeGen::CGFunctionInfo::create(), clang::FunctionType::getRegParmType(), IsStructurallyEquivalent(), clang::Sema::MergeFunctionDecl(), clang::ASTContext::mergeFunctionTypes(), clang::CodeGen::CGFunctionInfo::Profile(), and clang::JSONNodeDumper::VisitFunctionType().
operator!=()
bool clang::FunctionType::ExtInfo::operator!= (ExtInfo Other) const inline
Definition at line 3716 of file Type.h.
operator==()
bool clang::FunctionType::ExtInfo::operator== (ExtInfo Other) const inline
Definition at line 3713 of file Type.h.
Profile()
void clang::FunctionType::ExtInfo::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 3768 of file Type.h.
Referenced by clang::FunctionNoProtoType::Profile().
withCallingConv()
ExtInfo clang::FunctionType::ExtInfo::withCallingConv (CallingConv cc) const inline
Definition at line 3764 of file Type.h.
References ExtInfo().
Referenced by clang::Sema::adjustMemberFunctionCC(), clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), clang::Sema::CheckMain(), getImplicitMethodEPI(), clang::Sema::getLambdaConversionFunctionResultType(), LookupDirect(), and clang::Sema::MergeFunctionDecl().
withCmseNSCall()
ExtInfo clang::FunctionType::ExtInfo::withCmseNSCall (bool cmseNSCall) const inline
Definition at line 3737 of file Type.h.
References ExtInfo().
withNoCallerSavedRegs()
ExtInfo clang::FunctionType::ExtInfo::withNoCallerSavedRegs (bool noCallerSavedRegs) const inline
Definition at line 3744 of file Type.h.
References ExtInfo().
Referenced by clang::Sema::MergeFunctionDecl().
withNoCfCheck()
ExtInfo clang::FunctionType::ExtInfo::withNoCfCheck (bool noCfCheck) const inline
Definition at line 3751 of file Type.h.
References ExtInfo().
withNoReturn()
ExtInfo clang::FunctionType::ExtInfo::withNoReturn (bool noReturn) const inline
Definition at line 3723 of file Type.h.
References ExtInfo().
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::FindCompositePointerType(), clang::ASTContext::GetBuiltinType(), clang::Sema::IsFunctionConversion(), clang::Sema::MergeFunctionDecl(), and clang::ASTContext::mergeFunctionTypes().
withProducesResult()
ExtInfo clang::FunctionType::ExtInfo::withProducesResult (bool producesResult) const inline
Definition at line 3730 of file Type.h.
References ExtInfo().
Referenced by clang::CodeGen::CodeGenTypes::arrangeObjCMessageSendSignature(), and clang::Sema::MergeFunctionDecl().
withRegParm()
ExtInfo clang::FunctionType::ExtInfo::withRegParm (unsigned RegParm) const inline
Definition at line 3758 of file Type.h.
References ExtInfo().
Referenced by clang::Sema::MergeFunctionDecl().
Friends And Related Symbol Documentation
FunctionType
friend class FunctionType friend
Definition at line 3650 of file Type.h.
The documentation for this class was generated from the following file:
include/clang/AST/Type.h