clang: clang::AnalysisDeclContextManager Class Reference
clang::AnalysisDeclContextManager Class Reference
#include "clang/Analysis/AnalysisDeclContext.h"
Public Member Functions
AnalysisDeclContextManager (ASTContext &ASTCtx, bool useUnoptimizedCFG=false, bool addImplicitDtors=false, bool addInitializers=false, bool addTemporaryDtors=false, bool addLifetime=false, bool addLoopExit=false, bool addScopes=false, bool synthesizeBodies=false, bool addStaticInitBranches=false, bool addCXXNewAllocator=true, bool addRichCXXConstructors=true, bool markElidedCXXConstructors=true, bool addVirtualBaseBranches=true, CodeInjector *injector=nullptr)
AnalysisDeclContext * getContext (const Decl *D)
bool getUseUnoptimizedCFG () const
CFG::BuildOptions & getCFGBuildOptions ()
bool synthesizeBodies () const
const StackFrameContext * getStackFrame (const Decl *D)
Obtain the beginning context of the analysis.
const StackFrameContext * getStackFrame (AnalysisDeclContext *ADC, const LocationContext *Parent, const Stmt *S, const CFGBlock *Block, unsigned BlockCount, unsigned Index)
Obtain a context of the call stack using its parent context.
BodyFarm & getBodyFarm ()
void clear ()
Discard all previously created AnalysisDeclContexts.
Friends
class AnalysisDeclContext
Detailed Description
Definition at line 419 of file AnalysisDeclContext.h.
Constructor & Destructor Documentation
AnalysisDeclContextManager()
AnalysisDeclContextManager::AnalysisDeclContextManager (ASTContext & ASTCtx, bool useUnoptimizedCFG = false, bool addImplicitDtors = false, bool addInitializers = false, bool addTemporaryDtors = false, bool addLifetime = false, bool addLoopExit = false, bool addScopes = false, bool synthesizeBodies = false, bool addStaticInitBranches = false, bool addCXXNewAllocator = true, bool addRichCXXConstructors = true, bool markElidedCXXConstructors = true, bool addVirtualBaseBranches = true, CodeInjector * injector = nullptr)
Definition at line 68 of file AnalysisDeclContext.cpp.
References clang::CFG::BuildOptions::AddCXXNewAllocator, clang::CFG::BuildOptions::AddImplicitDtors, clang::CFG::BuildOptions::AddInitializers, clang::CFG::BuildOptions::AddLifetime, clang::CFG::BuildOptions::AddLoopExit, clang::CFG::BuildOptions::AddRichCXXConstructors, clang::CFG::BuildOptions::AddScopes, clang::CFG::BuildOptions::AddStaticInitBranches, clang::CFG::BuildOptions::AddTemporaryDtors, clang::CFG::BuildOptions::AddVirtualBaseBranches, clang::CFG::BuildOptions::MarkElidedCXXConstructors, and clang::CFG::BuildOptions::PruneTriviallyFalseEdges.
Member Function Documentation
clear()
void AnalysisDeclContextManager::clear ()
Discard all previously created AnalysisDeclContexts.
Definition at line 91 of file AnalysisDeclContext.cpp.
Referenced by clang::ento::AnalysisManager::ClearContexts().
getBodyFarm()
BodyFarm & AnalysisDeclContextManager::getBodyFarm ()
Definition at line 309 of file AnalysisDeclContext.cpp.
Referenced by clang::AnalysisDeclContext::getBody().
getCFGBuildOptions()
CFG::BuildOptions & clang::AnalysisDeclContextManager::getCFGBuildOptions () inline
Definition at line 456 of file AnalysisDeclContext.h.
Referenced by clang::ento::AnalysisManager::AnalysisManager().
getContext()
AnalysisDeclContext * AnalysisDeclContextManager::getContext (const Decl * D)
Definition at line 295 of file AnalysisDeclContext.cpp.
Referenced by clang::ento::AnalysisManager::getAnalysis(), clang::ento::AnalysisManager::getAnalysisDeclContext(), clang::ento::CallEvent::getCalleeAnalysisDeclContext(), clang::ento::AnalysisManager::getCFG(), clang::ento::AnalysisManager::getParentMap(), and getStackFrame().
getStackFrame() [1/2]
const StackFrameContext * clang::AnalysisDeclContextManager::getStackFrame (AnalysisDeclContext * ADC, const LocationContext * Parent, const Stmt * S, const CFGBlock * Block, unsigned BlockCount, unsigned Index) inline
Obtain a context of the call stack using its parent context.
Parameters
ADC The AnalysisDeclContext.
ParentLC The parent context of this newly created context.
S The call.
Block The basic block.
BlockCount The current count of entering into Blk.
Index The index of Blk.
Returns
The context for D with parent context ParentLC.
Definition at line 470 of file AnalysisDeclContext.h.
References clang::Block, clang::LocationContextManager::getStackFrame(), and Parent.
getStackFrame() [2/2]
const StackFrameContext * clang::AnalysisDeclContextManager::getStackFrame (const Decl * D) inline
Obtain the beginning context of the analysis.
Returns
The top level stack frame for D.
Definition at line 464 of file AnalysisDeclContext.h.
References getContext(), and clang::LocationContextManager::getStackFrame().
Referenced by clang::ento::CallEvent::getCalleeStackFrame().
getUseUnoptimizedCFG()
bool clang::AnalysisDeclContextManager::getUseUnoptimizedCFG () const inline
Definition at line 452 of file AnalysisDeclContext.h.
References clang::CFG::BuildOptions::PruneTriviallyFalseEdges.
synthesizeBodies()
bool clang::AnalysisDeclContextManager::synthesizeBodies () const inline
Returns
Whether faux bodies should be synthesized for known functions.
Definition at line 459 of file AnalysisDeclContext.h.
Referenced by clang::AnalysisDeclContext::getBody().
Friends And Related Symbol Documentation
AnalysisDeclContext
friend class AnalysisDeclContext friend
Definition at line 483 of file AnalysisDeclContext.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/AnalysisDeclContext.h
lib/Analysis/AnalysisDeclContext.cpp