clang: clang::HeaderMap Class Reference
clang::HeaderMap Class Reference
This class represents an Apple concept known as a 'header map'.
#include "clang/Lex/HeaderMap.h"
Public Member Functions
Optional< FileEntryRef > LookupFile (StringRef Filename, FileManager &FM) const
Check to see if the specified relative filename is located in this HeaderMap.
StringRef lookupFilename (StringRef Filename, SmallVectorImpl< char > &DestPath) const
If the specified relative filename is located in this HeaderMap return the filename it is mapped to, otherwise return an empty StringRef.
StringRef getFileName () const
Return the filename of the headermap.
void dump () const
Print the contents of this headermap to stderr.
Static Public Member Functions
static std::unique_ptr< HeaderMap > Create (const FileEntry *FE, FileManager &FM)
This attempts to load the specified file as a header map.
Detailed Description
This class represents an Apple concept known as a 'header map'.
To the #include file resolution process, it basically acts like a directory of symlinks to files. Its advantages are that it is dense and more efficient to create and process than a directory of symlinks.
Definition at line 65 of file HeaderMap.h.
Member Function Documentation
Create()
std::unique_ptr< HeaderMap > HeaderMap::Create (const FileEntry * FE, FileManager & FM) static
This attempts to load the specified file as a header map.
HeaderMap::Create - This attempts to load the specified file as a header map.
If it doesn't look like a HeaderMap, it gives up and returns null.
If it doesn't look like a HeaderMap, it gives up and returns null. If it looks like a HeaderMap but is obviously corrupted, it puts a reason into the string error argument and returns null.
Definition at line 50 of file HeaderMap.cpp.
References clang::HeaderMapImpl::checkHeader(), clang::FileManager::getBufferForFile(), and clang::FileEntry::getSize().
Referenced by clang::HeaderSearch::CreateHeaderMap().
dump()
LLVM_DUMP_METHOD void HeaderMapImpl::dump () const
Print the contents of this headermap to stderr.
dump - Print the contents of this headermap to stderr.
Definition at line 49 of file HeaderMap.cpp.
getFileName()
StringRef HeaderMapImpl::getFileName () const
Return the filename of the headermap.
getFileName - Return the filename of the headermap.
Definition at line 46 of file HeaderMap.cpp.
Referenced by clang::DirectoryLookup::getName().
LookupFile()
Optional< FileEntryRef > HeaderMap::LookupFile (StringRef Filename, FileManager & FM) const
Check to see if the specified relative filename is located in this HeaderMap.
LookupFile - Check to see if the specified relative filename is located in this HeaderMap.
If so, open it and return its FileEntry. If RawPath is not NULL and the file is found, RawPath will be set to the raw path at which the file was found in the file system. For example, for a search path ".." and a filename "../file.h" this would be "../../file.h".
If so, open it and return its FileEntry.
Definition at line 199 of file HeaderMap.cpp.
References Filename, clang::FileManager::getOptionalFileRef(), clang::HeaderMapImpl::lookupFilename(), and clang::None.
Referenced by clang::DirectoryLookup::LookupFile().
lookupFilename()
StringRef HeaderMapImpl::lookupFilename (StringRef Filename, SmallVectorImpl< char > & DestPath) const
If the specified relative filename is located in this HeaderMap return the filename it is mapped to, otherwise return an empty StringRef.
Definition at line 42 of file HeaderMap.cpp.
Referenced by clang::DirectoryLookup::LookupFile().
The documentation for this class was generated from the following files:
include/clang/Lex/HeaderMap.h
lib/Lex/HeaderMap.cpp