clang: clang::EnumDecl Class Reference
clang::EnumDecl Class Reference
Represents an enum.
#include "clang/AST/Decl.h"
Public Types
using enumerator_iterator = specific_decl_iterator<EnumConstantDecl>
using enumerator_range
Public Types inherited from clang::TagDecl
using TagKind = TagTypeKind
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned { Unowned , Visible , VisibleWhenImported , ModulePrivate }
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Types inherited from clang::DeclContext
using decl_range = llvm::iterator_range<decl_iterator>
using lookup_result = DeclContextLookupResult
using lookup_iterator = lookup_result::iterator
using lookups_range = llvm::iterator_range<all_lookups_iterator>
using udir_iterator_base
using udir_range = llvm::iterator_range<udir_iterator>
using ddiag_range = llvm::iterator_range<DeclContext::ddiag_iterator>
Public Types inherited from clang::Redeclarable< TagDecl >
using redecl_range
Public Member Functions
void setScoped (bool Scoped=true)
True if this tag declaration is a scoped enumeration.
void setScopedUsingClassTag (bool ScopedUCT=true)
If this tag declaration is a scoped enum, then this is true if the scoped enum was declared using the class tag, false if it was declared with the struct tag.
void setFixed (bool Fixed=true)
True if this is an Objective-C, C++11, or Microsoft-style enumeration with a fixed underlying type.
EnumDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const EnumDecl * getCanonicalDecl () const
EnumDecl * getPreviousDecl ()
const EnumDecl * getPreviousDecl () const
EnumDecl * getMostRecentDecl ()
const EnumDecl * getMostRecentDecl () const
EnumDecl * getDefinition () const
void completeDefinition (QualType NewType, QualType PromotionType, unsigned NumPositiveBits, unsigned NumNegativeBits)
When created, the EnumDecl corresponds to a forward-declared enum.
enumerator_range enumerators () const
enumerator_iterator enumerator_begin () const
enumerator_iterator enumerator_end () const
QualType getPromotionType () const
Return the integer type that enumerators should promote to.
void setPromotionType (QualType T)
Set the promotion type.
QualType getIntegerType () const
Return the integer type this enum decl corresponds to.
void setIntegerType (QualType T)
Set the underlying integer type.
void setIntegerTypeSourceInfo (TypeSourceInfo *TInfo)
Set the underlying integer type source info.
TypeSourceInfo * getIntegerTypeSourceInfo () const
Return the type source info for the underlying integer type, if no type source info exists, return 0.
SourceRange getIntegerTypeRange () const LLVM_READONLY
Retrieve the source range that covers the underlying type if specified.
unsigned getNumPositiveBits () const
Returns the width in bits required to store all the non-negative enumerators of this enum.
unsigned getNumNegativeBits () const
Returns the width in bits required to store all the negative enumerators of this enum.
bool isScoped () const
Returns true if this is a C++11 scoped enumeration.
bool isScopedUsingClassTag () const
Returns true if this is a C++11 scoped enumeration.
bool isFixed () const
Returns true if this is an Objective-C, C++11, or Microsoft-style enumeration with a fixed underlying type.
unsigned getODRHash ()
bool isComplete () const
Returns true if this can be considered a complete type.
bool isClosed () const
Returns true if this enum is either annotated with enum_extensibility(closed) or isn't annotated with enum_extensibility.
bool isClosedFlag () const
Returns true if this enum is annotated with flag_enum and isn't annotated with enum_extensibility(open).
bool isClosedNonFlag () const
Returns true if this enum is annotated with neither flag_enum nor enum_extensibility(open).
EnumDecl * getTemplateInstantiationPattern () const
Retrieve the enum definition from which this enumeration could be instantiated, if it is an instantiation (rather than a non-template).
EnumDecl * getInstantiatedFromMemberEnum () const
Returns the enumeration (declared within the template) from which this enumeration type was instantiated, or NULL if this enumeration was not instantiated from any template.
TemplateSpecializationKind getTemplateSpecializationKind () const
If this enumeration is a member of a specialization of a templated class, determine what kind of template specialization or instantiation this is.
void setTemplateSpecializationKind (TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation=SourceLocation())
For an enumeration member that was instantiated from a member enumeration of a templated class, set the template specialiation kind.
MemberSpecializationInfo * getMemberSpecializationInfo () const
If this enumeration is an instantiation of a member enumeration of a class template specialization, retrieves the member specialization information.
void setInstantiationOfMemberEnum (EnumDecl *ED, TemplateSpecializationKind TSK)
Specify that this enumeration is an instantiation of the member enumeration ED.
Public Member Functions inherited from clang::TagDecl
SourceRange getBraceRange () const
void setBraceRange (SourceRange R)
SourceLocation getInnerLocStart () const
Return SourceLocation representing start of source range ignoring outer template declarations.
SourceLocation getOuterLocStart () const
Return SourceLocation representing start of source range taking into account any outer template declarations.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
TagDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const TagDecl * getCanonicalDecl () const
bool isThisDeclarationADefinition () const
Return true if this declaration is a completion definition of the type.
bool isCompleteDefinition () const
Return true if this decl has its body fully specified.
void setCompleteDefinition (bool V=true)
True if this decl has its body fully specified.
bool isCompleteDefinitionRequired () const
Return true if this complete decl is required to be complete for some existing use.
void setCompleteDefinitionRequired (bool V=true)
True if this complete decl is required to be complete for some existing use.
bool isBeingDefined () const
Return true if this decl is currently being defined.
bool isEmbeddedInDeclarator () const
True if this tag declaration is "embedded" (i.e., defined or declared for the very first time) in the syntax of a declarator.
void setEmbeddedInDeclarator (bool isInDeclarator)
True if this tag declaration is "embedded" (i.e., defined or declared for the very first time) in the syntax of a declarator.
bool isFreeStanding () const
True if this tag is free standing, e.g. "struct foo;".
void setFreeStanding (bool isFreeStanding=true)
True if this tag is free standing, e.g. "struct foo;".
bool mayHaveOutOfDateDef () const
Indicates whether it is possible for declarations of this kind to have an out-of-date definition.
bool isDependentType () const
Whether this declaration declares a type that is dependent, i.e., a type that somehow depends on template parameters.
void startDefinition ()
Starts the definition of this tag declaration.
TagDecl * getDefinition () const
Returns the TagDecl that actually defines this struct/union/class/enum.
StringRef getKindName () const
TagKind getTagKind () const
void setTagKind (TagKind TK)
bool isStruct () const
bool isInterface () const
bool isClass () const
bool isUnion () const
bool isEnum () const
bool hasNameForLinkage () const
Is this tag type named, either directly or via being defined in a typedef of this type?
TypedefNameDecl * getTypedefNameForAnonDecl () const
void setTypedefNameForAnonDecl (TypedefNameDecl *TDD)
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned i) const
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
Public Member Functions inherited from clang::TypeDecl
const Type * getTypeForDecl () const
void setTypeForDecl (const Type *TD)
SourceLocation getBeginLoc () const LLVM_READONLY
void setLocStart (SourceLocation L)
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &os) const
Pretty-print the unqualified name of this declaration.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getQualifiedNameAsString () const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
Optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod () const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod ()
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl ()
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
Public Member Functions inherited from clang::DeclContext
~DeclContext ()
Decl::Kind getDeclKind () const
const char * getDeclKindName () const
DeclContext * getParent ()
getParent - Returns the containing DeclContext.
const DeclContext * getParent () const
DeclContext * getLexicalParent ()
getLexicalParent - Returns the containing lexical DeclContext.
const DeclContext * getLexicalParent () const
DeclContext * getLookupParent ()
Find the parent context of this context that will be used for unqualified name lookup.
const DeclContext * getLookupParent () const
ASTContext & getParentASTContext () const
bool isClosure () const
const BlockDecl * getInnermostBlockDecl () const
Return this DeclContext if it is a BlockDecl.
bool isObjCContainer () const
bool isFunctionOrMethod () const
bool isLookupContext () const
Test whether the context supports looking up names.
bool isFileContext () const
bool isTranslationUnit () const
bool isRecord () const
bool isNamespace () const
bool isStdNamespace () const
bool isInlineNamespace () const
bool isDependentContext () const
Determines whether this context is dependent on a template parameter.
bool isTransparentContext () const
isTransparentContext - Determines whether this context is a "transparent" context, meaning that the members declared in this context are semantically declared in the nearest enclosing non-transparent (opaque) context but are lexically declared in this context.
bool isExternCContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C linkage.
const LinkageSpecDecl * getExternCContext () const
Retrieve the nearest enclosing C linkage specification context.
bool isExternCXXContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C++ linkage.
bool Equals (const DeclContext *DC) const
Determine whether this declaration context is equivalent to the declaration context DC.
bool Encloses (const DeclContext *DC) const
Determine whether this declaration context encloses the declaration context DC.
Decl * getNonClosureAncestor ()
Find the nearest non-closure ancestor of this context, i.e.
const Decl * getNonClosureAncestor () const
DeclContext * getPrimaryContext ()
getPrimaryContext - There may be many different declarations of the same entity (including forward declarations of classes, multiple definitions of namespaces, etc.), each with a different set of declarations.
const DeclContext * getPrimaryContext () const
DeclContext * getRedeclContext ()
getRedeclContext - Retrieve the context in which an entity conflicts with other entities of the same name, or where it is a redeclaration if the two entities are compatible.
const DeclContext * getRedeclContext () const
DeclContext * getEnclosingNamespaceContext ()
Retrieve the nearest enclosing namespace context.
const DeclContext * getEnclosingNamespaceContext () const
RecordDecl * getOuterLexicalRecordContext ()
Retrieve the outermost lexically enclosing record context.
const RecordDecl * getOuterLexicalRecordContext () const
bool InEnclosingNamespaceSetOf (const DeclContext *NS) const
Test if this context is part of the enclosing namespace set of the context NS, as defined in C++0x [namespace.def]p9.
void collectAllContexts (SmallVectorImpl< DeclContext * > &Contexts)
Collects all of the declaration contexts that are semantically connected to this declaration context.
decl_range decls () const
decls_begin/decls_end - Iterate over the declarations stored in this context.
decl_iterator decls_begin () const
decl_iterator decls_end () const
bool decls_empty () const
decl_range noload_decls () const
noload_decls_begin/end - Iterate over the declarations stored in this context that are currently loaded; don't attempt to retrieve anything from an external source.
decl_iterator noload_decls_begin () const
decl_iterator noload_decls_end () const
void addDecl (Decl *D)
Add the declaration D into this context.
void addDeclInternal (Decl *D)
Add the declaration D into this context, but suppress searches for external declarations with the same name.
void addHiddenDecl (Decl *D)
Add the declaration D to this context without modifying any lookup tables.
void removeDecl (Decl *D)
Removes a declaration from this context.
bool containsDecl (Decl *D) const
Checks whether a declaration is in this context.
bool containsDeclAndLoad (Decl *D) const
Checks whether a declaration is in this context.
lookup_result lookup (DeclarationName Name) const
lookup - Find the declarations (if any) with the given Name in this context.
lookup_result noload_lookup (DeclarationName Name)
Find the declarations with the given name that are visible within this context; don't attempt to retrieve anything from an external source.
void localUncachedLookup (DeclarationName Name, SmallVectorImpl< NamedDecl * > &Results)
A simplistic name lookup mechanism that performs name lookup into this declaration context without consulting the external source.
void makeDeclVisibleInContext (NamedDecl *D)
Makes a declaration visible within this context.
lookups_range lookups () const
lookups_range noload_lookups (bool PreserveInternalState) const
all_lookups_iterator lookups_begin () const
Iterators over all possible lookups within this context.
all_lookups_iterator lookups_end () const
all_lookups_iterator noload_lookups_begin () const
Iterators over all possible lookups within this context that are currently loaded; don't attempt to retrieve anything from an external source.
all_lookups_iterator noload_lookups_end () const
udir_range using_directives () const
Returns iterator range [First, Last) of UsingDirectiveDecls stored within this context.
ddiag_range ddiags () const
void setMustBuildLookupTable ()
Mark that there are external lexical declarations that we need to include in our lookup table (and that are not available as external visible lookups).
StoredDeclsMap * getLookupPtr () const
Retrieve the internal representation of the lookup structure.
StoredDeclsMap * buildLookup ()
Ensure the lookup structure is fully-built and return it.
bool hasExternalLexicalStorage () const
Whether this DeclContext has external storage containing additional declarations that are lexically in this context.
void setHasExternalLexicalStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations lexically in this context.
bool hasExternalVisibleStorage () const
Whether this DeclContext has external storage containing additional declarations that are visible in this context.
void setHasExternalVisibleStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations visible in this context.
bool isDeclInLexicalTraversal (const Decl *D) const
Determine whether the given declaration is stored in the list of declarations lexically within this context.
bool setUseQualifiedLookup (bool use=true) const
bool shouldUseQualifiedLookup () const
void dumpDeclContext () const
void dumpLookups () const
void dumpLookups (llvm::raw_ostream &OS, bool DumpDecls=false, bool Deserialize=false) const
Public Member Functions inherited from clang::Redeclarable< TagDecl >
Redeclarable (const ASTContext &Ctx)
TagDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const TagDecl * getPreviousDecl () const
TagDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const TagDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
TagDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const TagDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (TagDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static EnumDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, EnumDecl *PrevDecl, bool IsScoped, bool IsScopedUsingClassTag, bool IsFixed)
static EnumDecl * CreateDeserialized (ASTContext &C, unsigned ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::TagDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const TagDecl *D)
static TagDecl * castFromDeclContext (const DeclContext *DC)
Static Public Member Functions inherited from clang::TypeDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Static Public Member Functions inherited from clang::DeclContext
static bool classof (const Decl *D)
static bool classof (const DeclContext *D)
Friends
class ASTDeclReader
Additional Inherited Members
Public Attributes inherited from clang::DeclContext
Protected Types inherited from clang::TagDecl
using redeclarable_base = Redeclarable<TagDecl>
Protected Member Functions inherited from clang::TagDecl
TagDecl (Kind DK, TagKind TK, const ASTContext &C, DeclContext *DC, SourceLocation L, IdentifierInfo *Id, TagDecl *PrevDecl, SourceLocation StartL)
TagDecl * getNextRedeclarationImpl () override
Returns the next redeclaration or itself if this is the only decl.
TagDecl * getPreviousDeclImpl () override
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
TagDecl * getMostRecentDeclImpl () override
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
void completeDefinition ()
Completes the definition of this tag declaration.
void setBeingDefined (bool V=true)
True if this decl is currently being defined.
void setMayHaveOutOfDateDef (bool V=true)
Indicates whether it is possible for declarations of this kind to have an out-of-date definition.
Protected Member Functions inherited from clang::TypeDecl
TypeDecl (Kind DK, DeclContext *DC, SourceLocation L, IdentifierInfo *Id, SourceLocation StartL=SourceLocation())
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::DeclContext
DeclContext (Decl::Kind K)
Protected Member Functions inherited from clang::Redeclarable< TagDecl >
TagDecl * getNextRedeclaration () const
Static Protected Member Functions inherited from clang::DeclContext
static std::pair< Decl *, Decl * > BuildDeclChain (ArrayRef< Decl * > Decls, bool FieldsAlreadyLoaded)
Build up a chain of declarations.
Static Protected Member Functions inherited from clang::Redeclarable< TagDecl >
static DeclLink PreviousDeclLink (TagDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 2, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::DeclContext
union {
DeclContextBitfields DeclContextBits
TagDeclBitfields TagDeclBits
EnumDeclBitfields EnumDeclBits
RecordDeclBitfields RecordDeclBits
OMPDeclareReductionDeclBitfields OMPDeclareReductionDeclBits
FunctionDeclBitfields FunctionDeclBits
CXXConstructorDeclBitfields CXXConstructorDeclBits
ObjCMethodDeclBitfields ObjCMethodDeclBits
ObjCContainerDeclBitfields ObjCContainerDeclBits
LinkageSpecDeclBitfields LinkageSpecDeclBits
BlockDeclBitfields BlockDeclBits
};
This anonymous union stores the bits belonging to DeclContext and classes deriving from it.
Decl * FirstDecl = nullptr
FirstDecl - The first declaration stored within this declaration context.
Decl * LastDecl = nullptr
LastDecl - The last declaration stored within this declaration context.
Protected Attributes inherited from clang::Redeclarable< TagDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
TagDecl * First
Detailed Description
Represents an enum.
In C++11, enums can be forward-declared with a fixed underlying type, and in C we allow them to be forward-declared with no underlying type as an extension.
Definition at line 3537 of file Decl.h.
Member Typedef Documentation
enumerator_iterator
using clang::EnumDecl::enumerator_iterator = specific_decl_iterator<EnumConstantDecl>
Definition at line 3662 of file Decl.h.
enumerator_range
using clang::EnumDecl::enumerator_range
Initial value:
      llvm::iterator_range<specific_decl_iterator<EnumConstantDecl>>
Definition at line 3663 of file Decl.h.
Member Function Documentation
classof()
static bool clang::EnumDecl::classof (const Decl * D) inline static
Definition at line 3798 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::EnumDecl::classofKind (Kind K) inline static
Definition at line 3799 of file Decl.h.
References Enum.
Referenced by classof().
completeDefinition()
void EnumDecl::completeDefinition (QualType NewType, QualType PromotionType, unsigned NumPositiveBits, unsigned NumNegativeBits)
When created, the EnumDecl corresponds to a forward-declared enum.
This method is used to mark the declaration as being defined; its enumerators have already been added (via DeclContext::addDecl). NewType is the new underlying type of the enumeration type.
Definition at line 4382 of file Decl.cpp.
References clang::TagDecl::completeDefinition(), clang::QualType::getTypePtr(), and clang::TagDecl::isCompleteDefinition().
Referenced by clang::ASTNodeImporter::ImportDefinition().
Create()
EnumDecl * EnumDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, EnumDecl * PrevDecl, bool IsScoped, bool IsScopedUsingClassTag, bool IsFixed) static
Definition at line 4356 of file Decl.cpp.
References clang::C, Enum, Id, and clang::TagDecl::setMayHaveOutOfDateDef().
Referenced by clang::Sema::ActOnTag(), and clang::Sema::DeclareGlobalNewDelete().
CreateDeserialized()
EnumDecl * EnumDecl::CreateDeserialized (ASTContext & C, unsigned ID) static
Definition at line 4368 of file Decl.cpp.
References clang::C, Enum, and clang::TagDecl::setMayHaveOutOfDateDef().
enumerator_begin()
enumerator_iterator clang::EnumDecl::enumerator_begin () const inline
Definition at line 3670 of file Decl.h.
References clang::DeclContext::decls_begin(), and getDefinition().
Referenced by enumerators(), and IsStructurallyEquivalent().
enumerator_end()
enumerator_iterator clang::EnumDecl::enumerator_end () const inline
Definition at line 3677 of file Decl.h.
References clang::DeclContext::decls_end(), and getDefinition().
Referenced by enumerators(), and IsStructurallyEquivalent().
enumerators()
enumerator_range clang::EnumDecl::enumerators () const inline
Definition at line 3666 of file Decl.h.
References enumerator_begin(), and enumerator_end().
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::DiagnoseAssignmentEnum(), clang::TemplateDeclInstantiator::InstantiateEnumDefinition(), clang::Sema::IsValueInFlagEnum(), and UseNSOptionsMacro().
getCanonicalDecl() [1/2]
const EnumDecl * clang::EnumDecl::getCanonicalDecl () const inline
Definition at line 3621 of file Decl.h.
References getCanonicalDecl().
getCanonicalDecl() [2/2]
EnumDecl * clang::EnumDecl::getCanonicalDecl () inline override virtual
Retrieves the "canonical" declaration of the given declaration.
Reimplemented from clang::Decl.
Definition at line 3618 of file Decl.h.
References clang::cast(), and clang::TagDecl::getCanonicalDecl().
Referenced by getCanonicalDecl(), isInstantiationOf(), and clang::ASTDeclReader::VisitEnumDecl().
getDefinition()
EnumDecl * clang::EnumDecl::getDefinition () const inline
Definition at line 3640 of file Decl.h.
References clang::TagDecl::getDefinition().
Referenced by appendEnumType(), clang::Sema::CodeCompleteCase(), enumerator_begin(), enumerator_end(), clang::ASTNodeImporter::ImportDefinition(), clang::Sema::InstantiateClassMembers(), clang::Sema::InstantiateEnum(), IsStructurallyEquivalent(), and clang::ASTNodeImporter::VisitEnumDecl().
getInstantiatedFromMemberEnum()
EnumDecl * EnumDecl::getInstantiatedFromMemberEnum () const
Returns the enumeration (declared within the template) from which this enumeration type was instantiated, or NULL if this enumeration was not instantiated from any template.
Definition at line 4442 of file Decl.cpp.
References clang::cast(), and clang::MemberSpecializationInfo::getInstantiatedFrom().
Referenced by adjustDeclToTemplate(), adjustTemplateImplicitInstantiation(), clang::Sema::CheckMemberSpecialization(), getTemplateInstantiationPattern(), clang::Sema::InstantiateEnum(), and clang::Sema::RequireCompleteDeclContext().
getIntegerType()
QualType clang::EnumDecl::getIntegerType () const inline
Return the integer type this enum decl corresponds to.
This returns a null QualType for an enum forward definition with no fixed underlying type.
Definition at line 3693 of file Decl.h.
References getType().
Referenced by clang::Sema::ActOnTag(), clang::Sema::BuildUnaryTransformType(), clang::Sema::CheckEnumRedeclaration(), clang::CodeGen::CodeGenTypes::ConvertType(), getIntegerTypeForEnum(), getRangeForType(), isLayoutCompatible(), mergeEnumWithInteger(), ObjCEncodingForEnumType(), rewriteToNSMacroDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::JSONNodeDumper::VisitEnumDecl(), and clang::TextNodeDumper::VisitEnumDecl().
getIntegerTypeRange()
SourceRange EnumDecl::getIntegerTypeRange () const
Retrieve the source range that covers the underlying type if specified.
Definition at line 4376 of file Decl.cpp.
References getIntegerTypeSourceInfo().
Referenced by clang::Sema::CheckEnumRedeclaration().
getIntegerTypeSourceInfo()
TypeSourceInfo * clang::EnumDecl::getIntegerTypeSourceInfo () const inline
Return the type source info for the underlying integer type, if no type source info exists, return 0.
Definition at line 3709 of file Decl.h.
Referenced by AnalyzeBitFieldAssignment(), getIntegerTypeRange(), and clang::ASTDeclWriter::VisitEnumDecl().
getMemberSpecializationInfo()
MemberSpecializationInfo * clang::EnumDecl::getMemberSpecializationInfo () const inline
If this enumeration is an instantiation of a member enumeration of a class template specialization, retrieves the member specialization information.
Definition at line 3787 of file Decl.h.
Referenced by clang::Sema::CheckMemberSpecialization(), getTemplateInstantiationPattern(), getTemplateSpecializationKind(), clang::Sema::InstantiateEnum(), setTemplateSpecializationKind(), clang::ASTDeclReader::VisitEnumDecl(), and clang::ASTDeclWriter::VisitEnumDecl().
getMostRecentDecl() [1/2]
EnumDecl * clang::EnumDecl::getMostRecentDecl () inline
Definition at line 3633 of file Decl.h.
References clang::cast(), and getMostRecentDecl().
Referenced by getMostRecentDecl(), getMostRecentDecl(), clang::ASTDeclWriter::VisitEnumDecl(), and clang::ASTNodeImporter::VisitEnumDecl().
getMostRecentDecl() [2/2]
const EnumDecl * clang::EnumDecl::getMostRecentDecl () const inline
Definition at line 3636 of file Decl.h.
References getMostRecentDecl().
getNumNegativeBits()
unsigned clang::EnumDecl::getNumNegativeBits () const inline
Returns the width in bits required to store all the negative enumerators of this enum.
These widths include the rightmost leading 1; that is:
MOST NEGATIVE ENUMERATOR PATTERN NUM NEGATIVE BITS
-1 1111111 1 -10 1110110 5 -101 1001011 8
Definition at line 3730 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by AnalyzeBitFieldAssignment(), getRangeForType(), clang::ASTNodeImporter::ImportDefinition(), and clang::ASTDeclWriter::VisitEnumDecl().
getNumPositiveBits()
unsigned clang::EnumDecl::getNumPositiveBits () const inline
Returns the width in bits required to store all the non-negative enumerators of this enum.
Definition at line 3719 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by AnalyzeBitFieldAssignment(), getRangeForType(), clang::ASTNodeImporter::ImportDefinition(), and clang::ASTDeclWriter::VisitEnumDecl().
getODRHash()
unsigned EnumDecl::getODRHash ()
Definition at line 4455 of file Decl.cpp.
References clang::ODRHash::AddEnumDecl(), and clang::ODRHash::CalculateHash().
Referenced by clang::ASTDeclReader::VisitEnumDecl(), and clang::ASTDeclWriter::VisitEnumDecl().
getPreviousDecl() [1/2]
EnumDecl * clang::EnumDecl::getPreviousDecl () inline
Definition at line 3625 of file Decl.h.
References getPreviousDecl().
Referenced by getPreviousDecl(), and getPreviousDecl().
getPreviousDecl() [2/2]
const EnumDecl * clang::EnumDecl::getPreviousDecl () const inline
Definition at line 3629 of file Decl.h.
References getPreviousDecl().
getPromotionType()
QualType clang::EnumDecl::getPromotionType () const inline
Return the integer type that enumerators should promote to.
Definition at line 3685 of file Decl.h.
Referenced by clang::ASTNodeImporter::ImportDefinition(), and clang::ASTDeclWriter::VisitEnumDecl().
getTemplateInstantiationPattern()
EnumDecl * EnumDecl::getTemplateInstantiationPattern () const
Retrieve the enum definition from which this enumeration could be instantiated, if it is an instantiation (rather than a non-template).
Definition at line 4427 of file Decl.cpp.
References getDefinitionOrSelf(), getInstantiatedFromMemberEnum(), getMemberSpecializationInfo(), getTemplateSpecializationKind(), and clang::isTemplateInstantiation().
Referenced by clang::Sema::InstantiateClassMembers().
getTemplateSpecializationKind()
TemplateSpecializationKind EnumDecl::getTemplateSpecializationKind () const
If this enumeration is a member of a specialization of a templated class, determine what kind of template specialization or instantiation this is.
Definition at line 4409 of file Decl.cpp.
References getMemberSpecializationInfo(), and clang::TSK_Undeclared.
Referenced by clang::Sema::FindInstantiatedDecl(), and getTemplateInstantiationPattern().
isClosed()
bool EnumDecl::isClosed () const
Returns true if this enum is either annotated with enum_extensibility(closed) or isn't annotated with enum_extensibility.
Definition at line 4395 of file Decl.cpp.
References clang::EnumExtensibilityAttr::Closed, and clang::Decl::getAttr().
Referenced by clang::Sema::DiagnoseAssignmentEnum(), isClosedFlag(), isClosedNonFlag(), and ShouldDiagnoseSwitchCaseNotInEnum().
isClosedFlag()
bool EnumDecl::isClosedFlag () const
Returns true if this enum is annotated with flag_enum and isn't annotated with enum_extensibility(open).
Definition at line 4401 of file Decl.cpp.
References clang::Decl::hasAttr(), and isClosed().
Referenced by clang::Sema::IsValueInFlagEnum().
isClosedNonFlag()
bool EnumDecl::isClosedNonFlag () const
Returns true if this enum is annotated with neither flag_enum nor enum_extensibility(open).
Definition at line 4405 of file Decl.cpp.
References clang::Decl::hasAttr(), and isClosed().
Referenced by clang::Sema::ActOnFinishSwitchStmt().
isComplete()
bool clang::EnumDecl::isComplete () const inline
Returns true if this can be considered a complete type.
Definition at line 3747 of file Decl.h.
References clang::TagDecl::isCompleteDefinition().
Referenced by clang::Sema::ActOnTag(), getIntegerTypeForEnum(), clang::IsEnumDeclComplete(), clang::Type::isIncompleteType(), and isLayoutCompatible().
isFixed()
bool clang::EnumDecl::isFixed () const inline
Returns true if this is an Objective-C, C++11, or Microsoft-style enumeration with a fixed underlying type.
Definition at line 3742 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::Sema::CheckEnumRedeclaration(), clang::CodeGen::CodeGenTypes::ConvertType(), getRangeForType(), clang::Sema::PerformImplicitConversion(), TryStaticCast(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::JSONNodeDumper::VisitEnumDecl(), and clang::TextNodeDumper::VisitEnumDecl().
isScoped()
bool clang::EnumDecl::isScoped () const inline
Returns true if this is a C++11 scoped enumeration.
Definition at line 3733 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::Sema::ActOnEnumConstant(), clang::Sema::CheckEnumRedeclaration(), getIntegerTypeForEnum(), clang::IsEnumDeclScoped(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::JSONNodeDumper::VisitEnumDecl(), and clang::TextNodeDumper::VisitEnumDecl().
isScopedUsingClassTag()
bool clang::EnumDecl::isScopedUsingClassTag () const inline
Returns true if this is a C++11 scoped enumeration.
Definition at line 3736 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTNodeImporter::VisitEnumDecl(), clang::JSONNodeDumper::VisitEnumDecl(), and clang::TextNodeDumper::VisitEnumDecl().
setFixed()
void clang::EnumDecl::setFixed (bool Fixed = true) inline
True if this is an Objective-C, C++11, or Microsoft-style enumeration with a fixed underlying type.
Definition at line 3608 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::ASTDeclReader::VisitEnumDecl().
setInstantiationOfMemberEnum()
void clang::EnumDecl::setInstantiationOfMemberEnum (EnumDecl * ED, TemplateSpecializationKind TSK) inline
Specify that this enumeration is an instantiation of the member enumeration ED.
Definition at line 3793 of file Decl.h.
References clang::Decl::getASTContext().
setIntegerType()
void clang::EnumDecl::setIntegerType (QualType T) inline
Set the underlying integer type.
Definition at line 3702 of file Decl.h.
Referenced by clang::Sema::ActOnTag(), clang::ASTDeclReader::VisitEnumDecl(), and clang::ASTNodeImporter::VisitEnumDecl().
setIntegerTypeSourceInfo()
void clang::EnumDecl::setIntegerTypeSourceInfo (TypeSourceInfo * TInfo) inline
Set the underlying integer type source info.
Definition at line 3705 of file Decl.h.
Referenced by clang::Sema::ActOnTag(), and clang::ASTDeclReader::VisitEnumDecl().
setPromotionType()
void clang::EnumDecl::setPromotionType (QualType T) inline
Set the promotion type.
Definition at line 3688 of file Decl.h.
Referenced by clang::Sema::ActOnTag(), and clang::ASTDeclReader::VisitEnumDecl().
setScoped()
void clang::EnumDecl::setScoped (bool Scoped = true) inline
True if this tag declaration is a scoped enumeration.
Only possible in C++11 mode.
Definition at line 3596 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::ASTDeclReader::VisitEnumDecl().
setScopedUsingClassTag()
void clang::EnumDecl::setScopedUsingClassTag (bool ScopedUCT = true) inline
If this tag declaration is a scoped enum, then this is true if the scoped enum was declared using the class tag, false if it was declared with the struct tag.
No meaning is associated if this tag declaration is not a scoped enum.
Definition at line 3602 of file Decl.h.
References clang::DeclContext::EnumDeclBits.
Referenced by clang::ASTDeclReader::VisitEnumDecl().
setTemplateSpecializationKind()
void EnumDecl::setTemplateSpecializationKind (TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation = SourceLocation())
For an enumeration member that was instantiated from a member enumeration of a templated class, set the template specialiation kind.
Definition at line 4416 of file Decl.cpp.
References getMemberSpecializationInfo(), clang::MemberSpecializationInfo::getPointOfInstantiation(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isValid(), clang::MemberSpecializationInfo::setPointOfInstantiation(), clang::MemberSpecializationInfo::setTemplateSpecializationKind(), and clang::TSK_ExplicitSpecialization.
Friends And Related Symbol Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 3616 of file Decl.h.
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp