clang: clang::index::CommentToXMLConverter Class Reference
clang::index::CommentToXMLConverter Class Reference
#include "clang/Index/CommentToXML.h"
Public Member Functions
CommentToXMLConverter ()
~CommentToXMLConverter ()
void convertCommentToHTML (const comments::FullComment *FC, SmallVectorImpl< char > &HTML, const ASTContext &Context)
void convertHTMLTagNodeToText (const comments::HTMLTagComment *HTC, SmallVectorImpl< char > &Text, const ASTContext &Context)
void convertCommentToXML (const comments::FullComment *FC, SmallVectorImpl< char > &XML, const ASTContext &Context)
Detailed Description
Definition at line 24 of file CommentToXML.h.
Constructor & Destructor Documentation
CommentToXMLConverter()
CommentToXMLConverter::CommentToXMLConverter ()
Definition at line 1126 of file CommentToXML.cpp.
~CommentToXMLConverter()
CommentToXMLConverter::~CommentToXMLConverter ()
Definition at line 1127 of file CommentToXML.cpp.
Member Function Documentation
convertCommentToHTML()
void CommentToXMLConverter::convertCommentToHTML (const comments::FullComment * FC, SmallVectorImpl< char > & HTML, const ASTContext & Context)
Definition at line 1129 of file CommentToXML.cpp.
References clang::ASTContext::getCommentCommandTraits().
convertCommentToXML()
void CommentToXMLConverter::convertCommentToXML (const comments::FullComment * FC, SmallVectorImpl< char > & XML, const ASTContext & Context)
Definition at line 1145 of file CommentToXML.cpp.
References clang::ASTContext::getCommentCommandTraits(), and clang::ASTContext::getSourceManager().
convertHTMLTagNodeToText()
void CommentToXMLConverter::convertHTMLTagNodeToText (const comments::HTMLTagComment * HTC, SmallVectorImpl< char > & Text, const ASTContext & Context)
Definition at line 1137 of file CommentToXML.cpp.
References clang::ASTContext::getCommentCommandTraits(), and Text.
The documentation for this class was generated from the following files:
include/clang/Index/CommentToXML.h
lib/Index/CommentToXML.cpp