clang: clang::driver::tools::darwin::Lipo Class Reference
clang::driver::tools::darwin::Lipo Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/Darwin.h"
Public Member Functions
Lipo (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::tools::darwin::MachOTool
MachOTool (const char *Name, const char *ShortName, const ToolChain &TC)
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Additional Inherited Members
Protected Member Functions inherited from clang::driver::tools::darwin::MachOTool
void AddMachOArch (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
const toolchains::MachO & getMachOToolChain () const
Detailed Description
Definition at line 81 of file Darwin.h.
Constructor & Destructor Documentation
Lipo()
clang::driver::tools::darwin::Lipo::Lipo (const ToolChain & TC) inline
Definition at line 83 of file Darwin.h.
Member Function Documentation
ConstructJob()
void darwin::Lipo::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 719 of file Darwin.cpp.
References clang::C, clang::driver::InputInfo::getFilename(), clang::driver::InputInfo::isFilename(), and clang::driver::ResponseFileSupport::None().
hasIntegratedCPP()
bool clang::driver::tools::darwin::Lipo::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 85 of file Darwin.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Darwin.h
lib/Driver/ToolChains/Darwin.cpp