clang: clang::APValue Class Reference
clang::APValue Class Reference
APValue - This class implements a discriminated union of [uninitialized] [APSInt] [APFloat], [Complex APSInt] [Complex APFloat], [Expr + Offset], [Vector: N * APValue], [Array: N * APValue].
#include "clang/AST/APValue.h"
Classes
struct LV
class LValueBase
class LValuePathEntry
A non-discriminated union of a base, field, or array index.
class LValuePathSerializationHelper
struct MemberPointerData
struct NoLValuePath
struct UninitArray
struct UninitStruct
Public Types
enum ValueKind {
None , Indeterminate , Int , Float ,
FixedPoint , ComplexInt , ComplexFloat , LValue ,
Vector , Array , Struct , Union ,
MemberPointer , AddrLabelDiff
}
typedef llvm::PointerIntPair< const Decl *, 1, bool > BaseOrMemberType
A FieldDecl or CXXRecordDecl, along with a flag indicating whether we mean a virtual or non-virtual base class subobject.
Public Member Functions
APValue ()
APValue (APSInt I)
APValue (APFloat F)
APValue (APFixedPoint FX)
APValue (const APValue *E, unsigned N)
APValue (APSInt R, APSInt I)
APValue (APFloat R, APFloat I)
APValue (const APValue &RHS)
APValue (APValue &&RHS)
APValue (LValueBase B, const CharUnits &O, NoLValuePath N, bool IsNullPtr=false)
APValue (LValueBase B, const CharUnits &O, ArrayRef< LValuePathEntry > Path, bool OnePastTheEnd, bool IsNullPtr=false)
APValue (UninitArray, unsigned InitElts, unsigned Size)
APValue (UninitStruct, unsigned B, unsigned M)
APValue (const FieldDecl *D, const APValue &V=APValue())
APValue (const ValueDecl *Member, bool IsDerivedMember, ArrayRef< const CXXRecordDecl * > Path)
APValue (const AddrLabelExpr *LHSExpr, const AddrLabelExpr *RHSExpr)
APValue & operator= (const APValue &RHS)
APValue & operator= (APValue &&RHS)
~APValue ()
bool needsCleanup () const
Returns whether the object performed allocations.
void swap (APValue &RHS)
Swaps the contents of this and the given APValue.
void Profile (llvm::FoldingSetNodeID &ID) const
profile this value.
ValueKind getKind () const
bool isAbsent () const
bool isIndeterminate () const
bool hasValue () const
bool isInt () const
bool isFloat () const
bool isFixedPoint () const
bool isComplexInt () const
bool isComplexFloat () const
bool isLValue () const
bool isVector () const
bool isArray () const
bool isStruct () const
bool isUnion () const
bool isMemberPointer () const
bool isAddrLabelDiff () const
void dump () const
void dump (raw_ostream &OS, const ASTContext &Context) const
void printPretty (raw_ostream &OS, const ASTContext &Ctx, QualType Ty) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy, QualType Ty, const ASTContext *Ctx=nullptr) const
std::string getAsString (const ASTContext &Ctx, QualType Ty) const
APSInt & getInt ()
const APSInt & getInt () const
bool toIntegralConstant (APSInt &Result, QualType SrcTy, const ASTContext &Ctx) const
Try to convert this value to an integral constant.
APFloat & getFloat ()
const APFloat & getFloat () const
APFixedPoint & getFixedPoint ()
const APFixedPoint & getFixedPoint () const
APSInt & getComplexIntReal ()
const APSInt & getComplexIntReal () const
APSInt & getComplexIntImag ()
const APSInt & getComplexIntImag () const
APFloat & getComplexFloatReal ()
const APFloat & getComplexFloatReal () const
APFloat & getComplexFloatImag ()
const APFloat & getComplexFloatImag () const
const LValueBase getLValueBase () const
CharUnits & getLValueOffset ()
const CharUnits & getLValueOffset () const
bool isLValueOnePastTheEnd () const
bool hasLValuePath () const
ArrayRef< LValuePathEntry > getLValuePath () const
unsigned getLValueCallIndex () const
unsigned getLValueVersion () const
bool isNullPointer () const
APValue & getVectorElt (unsigned I)
const APValue & getVectorElt (unsigned I) const
unsigned getVectorLength () const
APValue & getArrayInitializedElt (unsigned I)
const APValue & getArrayInitializedElt (unsigned I) const
bool hasArrayFiller () const
APValue & getArrayFiller ()
const APValue & getArrayFiller () const
unsigned getArrayInitializedElts () const
unsigned getArraySize () const
unsigned getStructNumBases () const
unsigned getStructNumFields () const
APValue & getStructBase (unsigned i)
APValue & getStructField (unsigned i)
const APValue & getStructBase (unsigned i) const
const APValue & getStructField (unsigned i) const
const FieldDecl * getUnionField () const
APValue & getUnionValue ()
const APValue & getUnionValue () const
const ValueDecl * getMemberPointerDecl () const
bool isMemberPointerToDerivedMember () const
ArrayRef< const CXXRecordDecl * > getMemberPointerPath () const
const AddrLabelExpr * getAddrLabelDiffLHS () const
const AddrLabelExpr * getAddrLabelDiffRHS () const
void setInt (APSInt I)
void setFloat (APFloat F)
void setFixedPoint (APFixedPoint FX)
void setVector (const APValue *E, unsigned N)
void setComplexInt (APSInt R, APSInt I)
void setComplexFloat (APFloat R, APFloat I)
void setLValue (LValueBase B, const CharUnits &O, NoLValuePath, bool IsNullPtr)
void setLValue (LValueBase B, const CharUnits &O, ArrayRef< LValuePathEntry > Path, bool OnePastTheEnd, bool IsNullPtr)
void setUnion (const FieldDecl *Field, const APValue &Value)
void setAddrLabelDiff (const AddrLabelExpr *LHSExpr, const AddrLabelExpr *RHSExpr)
Static Public Member Functions
static APValue IndeterminateValue ()
Friends
template<typename Impl >
class clang::serialization::BasicReaderBase
class ASTImporter
class ASTNodeImporter
Detailed Description
APValue - This class implements a discriminated union of [uninitialized] [APSInt] [APFloat], [Complex APSInt] [Complex APFloat], [Expr + Offset], [Vector: N * APValue], [Array: N * APValue].
Definition at line 122 of file APValue.h.
Member Typedef Documentation
BaseOrMemberType
llvm::PointerIntPair<const Decl *, 1, bool> clang::APValue::BaseOrMemberType
A FieldDecl or CXXRecordDecl, along with a flag indicating whether we mean a virtual or non-virtual base class subobject.
Definition at line 205 of file APValue.h.
Member Enumeration Documentation
ValueKind
enum clang::APValue::ValueKind
Enumerator
None
There is no such object (it's outside its lifetime).
Indeterminate
This object has an indeterminate value (C++ [basic.indet]).
Int
Float
FixedPoint
ComplexInt
ComplexFloat
LValue
Vector
Array
Struct
Union
MemberPointer
AddrLabelDiff
Definition at line 127 of file APValue.h.
Constructor & Destructor Documentation
APValue() [1/16]
clang::APValue::APValue () inline
Definition at line 309 of file APValue.h.
Referenced by operator=().
APValue() [2/16]
clang::APValue::APValue (APSInt I) inline explicit
Definition at line 310 of file APValue.h.
References setInt().
APValue() [3/16]
clang::APValue::APValue (APFloat F) inline explicit
Definition at line 313 of file APValue.h.
References setFloat().
APValue() [4/16]
clang::APValue::APValue (APFixedPoint FX) inline explicit
Definition at line 316 of file APValue.h.
APValue() [5/16]
clang::APValue::APValue (const APValue * E, unsigned N) inline explicit
Definition at line 319 of file APValue.h.
References N, and setVector().
APValue() [6/16]
clang::APValue::APValue (APSInt R, APSInt I) inline
Definition at line 322 of file APValue.h.
References setComplexInt().
APValue() [7/16]
clang::APValue::APValue (APFloat R, APFloat I) inline
Definition at line 325 of file APValue.h.
References setComplexFloat().
APValue() [8/16]
APValue::APValue (const APValue & RHS)
Definition at line 311 of file APValue.cpp.
References AddrLabelDiff, Array, ComplexFloat, ComplexInt, getAddrLabelDiffLHS(), getAddrLabelDiffRHS(), getArrayFiller(), getArrayInitializedElt(), getArrayInitializedElts(), getArraySize(), getComplexFloatImag(), getComplexFloatReal(), getComplexIntImag(), getComplexIntReal(), getKind(), getLValueBase(), getLValueOffset(), getLValuePath(), getMemberPointerDecl(), getMemberPointerPath(), getStructBase(), getStructField(), getStructNumBases(), getStructNumFields(), getUnionField(), getUnionValue(), getVectorLength(), hasArrayFiller(), hasLValuePath(), isLValueOnePastTheEnd(), isMemberPointerToDerivedMember(), isNullPointer(), LValue, MemberPointer, N, setAddrLabelDiff(), setComplexFloat(), setComplexInt(), setLValue(), setUnion(), setVector(), Struct, Union, and Vector.
APValue() [9/16]
APValue::APValue (APValue && RHS)
Definition at line 382 of file APValue.cpp.
References None.
APValue() [10/16]
clang::APValue::APValue (LValueBase B, const CharUnits & O, NoLValuePath N, bool IsNullPtr = false) inline
Definition at line 330 of file APValue.h.
References N, and setLValue().
APValue() [11/16]
clang::APValue::APValue (LValueBase B, const CharUnits & O, ArrayRef< LValuePathEntry > Path, bool OnePastTheEnd, bool IsNullPtr = false) inline
Definition at line 335 of file APValue.h.
References setLValue().
APValue() [12/16]
clang::APValue::APValue (UninitArray , unsigned InitElts, unsigned Size) inline
Definition at line 340 of file APValue.h.
APValue() [13/16]
clang::APValue::APValue (UninitStruct , unsigned B, unsigned M) inline
Definition at line 343 of file APValue.h.
APValue() [14/16]
clang::APValue::APValue (const FieldDecl * D, const APValue & V = APValue()) inline explicit
Definition at line 346 of file APValue.h.
References setUnion(), and V.
APValue() [15/16]
clang::APValue::APValue (const ValueDecl * Member, bool IsDerivedMember, ArrayRef< const CXXRecordDecl * > Path) inline
Definition at line 350 of file APValue.h.
References clang::Member.
APValue() [16/16]
clang::APValue::APValue (const AddrLabelExpr * LHSExpr, const AddrLabelExpr * RHSExpr) inline
Definition at line 354 of file APValue.h.
References setAddrLabelDiff().
~APValue()
clang::APValue::~APValue () inline
Definition at line 367 of file APValue.h.
References Indeterminate.
Member Function Documentation
dump() [1/2]
LLVM_DUMP_METHOD void APValue::dump () const
Definition at line 280 of file ASTDumper.cpp.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
dump() [2/2]
LLVM_DUMP_METHOD void APValue::dump (raw_ostream & OS, const ASTContext & Context) const
Definition at line 285 of file ASTDumper.cpp.
References clang::ASTContext::CharTy, clang::ASTContext::getDiagnostics(), clang::ASTContext::getPointerType(), clang::DiagnosticsEngine::getShowColors(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
getAddrLabelDiffLHS()
const AddrLabelExpr * clang::APValue::getAddrLabelDiffLHS () const inline
Definition at line 571 of file APValue.h.
References isAddrLabelDiff().
Referenced by APValue(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
getAddrLabelDiffRHS()
const AddrLabelExpr * clang::APValue::getAddrLabelDiffRHS () const inline
Definition at line 575 of file APValue.h.
References isAddrLabelDiff().
Referenced by APValue(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
getArrayFiller() [1/2]
APValue & clang::APValue::getArrayFiller () inline
Definition at line 513 of file APValue.h.
References getArrayInitializedElts(), hasArrayFiller(), and isArray().
Referenced by APValue(), expandArray(), findSubobject(), getArrayFiller(), and Profile().
getArrayFiller() [2/2]
const APValue & clang::APValue::getArrayFiller () const inline
Definition at line 518 of file APValue.h.
References getArrayFiller().
getArrayInitializedElt() [1/2]
APValue & clang::APValue::getArrayInitializedElt (unsigned I) inline
Definition at line 502 of file APValue.h.
References getArrayInitializedElts(), and isArray().
Referenced by APValue(), expandArray(), findSubobject(), getArrayInitializedElt(), clang::MSGuidDecl::getAsAPValue(), HandleDestructionImpl(), printPretty(), and Profile().
getArrayInitializedElt() [2/2]
const APValue & clang::APValue::getArrayInitializedElt (unsigned I) const inline
Definition at line 507 of file APValue.h.
References getArrayInitializedElt().
getArrayInitializedElts()
unsigned clang::APValue::getArrayInitializedElts () const inline
Definition at line 521 of file APValue.h.
References isArray().
Referenced by APValue(), findSubobject(), getArrayFiller(), getArrayInitializedElt(), hasArrayFiller(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
getArraySize()
unsigned clang::APValue::getArraySize () const inline
Definition at line 525 of file APValue.h.
References isArray().
Referenced by APValue(), hasArrayFiller(), clang::ASTNodeImporter::ImportAPValue(), and Profile().
getAsString()
std::string APValue::getAsString (const ASTContext & Ctx, QualType Ty) const
Definition at line 865 of file APValue.cpp.
References printPretty(), and clang::Result.
Referenced by CheckConvertedConstantExpression(), checkDynamicType(), checkThreeWayNarrowingConversion(), DiagnoseNarrowingInInitList(), findCompleteObject(), and HandleDestructionImpl().
getComplexFloatImag() [1/2]
APFloat & clang::APValue::getComplexFloatImag () inline
Definition at line 469 of file APValue.h.
References isComplexFloat().
Referenced by APValue(), findSubobject(), getComplexFloatImag(), HandleConversionToBool(), IsSameFloatAfterCast(), needsCleanup(), printPretty(), and Profile().
getComplexFloatImag() [2/2]
const APFloat & clang::APValue::getComplexFloatImag () const inline
Definition at line 473 of file APValue.h.
References getComplexFloatImag().
getComplexFloatReal() [1/2]
APFloat & clang::APValue::getComplexFloatReal () inline
Definition at line 461 of file APValue.h.
References isComplexFloat().
Referenced by APValue(), findSubobject(), getComplexFloatReal(), HandleConversionToBool(), IsSameFloatAfterCast(), needsCleanup(), printPretty(), and Profile().
getComplexFloatReal() [2/2]
const APFloat & clang::APValue::getComplexFloatReal () const inline
Definition at line 465 of file APValue.h.
References getComplexFloatReal().
getComplexIntImag() [1/2]
APSInt & clang::APValue::getComplexIntImag () inline
Definition at line 453 of file APValue.h.
References isComplexInt().
Referenced by APValue(), findSubobject(), getComplexIntImag(), GetValueRange(), HandleConversionToBool(), needsCleanup(), printPretty(), and Profile().
getComplexIntImag() [2/2]
const APSInt & clang::APValue::getComplexIntImag () const inline
Definition at line 457 of file APValue.h.
References getComplexIntImag().
getComplexIntReal() [1/2]
APSInt & clang::APValue::getComplexIntReal () inline
Definition at line 445 of file APValue.h.
References isComplexInt().
Referenced by APValue(), findSubobject(), getComplexIntReal(), GetValueRange(), HandleConversionToBool(), needsCleanup(), printPretty(), and Profile().
getComplexIntReal() [2/2]
const APSInt & clang::APValue::getComplexIntReal () const inline
Definition at line 449 of file APValue.h.
References getComplexIntReal().
getFixedPoint() [1/2]
APFixedPoint & clang::APValue::getFixedPoint () inline
Definition at line 437 of file APValue.h.
References isFixedPoint().
Referenced by EvaluateFixedPoint(), getFixedPoint(), HandleConversionToBool(), needsCleanup(), printPretty(), and Profile().
getFixedPoint() [2/2]
const APFixedPoint & clang::APValue::getFixedPoint () const inline
Definition at line 441 of file APValue.h.
References getFixedPoint().
getFloat() [1/2]
APFloat & clang::APValue::getFloat () inline
Definition at line 429 of file APValue.h.
References isFloat().
Referenced by EvalAndBitcastToAPInt(), getFloat(), clang::StandardConversionSequence::getNarrowingKind(), handleCompareOpForVector(), HandleConversionToBool(), handleLogicalOpForVector(), handleVectorVectorBinOp(), IsSameFloatAfterCast(), needsCleanup(), printPretty(), Profile(), and clang::CodeGen::ConstantEmitter::tryEmitPrivate().
getFloat() [2/2]
const APFloat & clang::APValue::getFloat () const inline
Definition at line 433 of file APValue.h.
References getFloat().
getInt() [1/2]
APSInt & clang::APValue::getInt () inline
Definition at line 415 of file APValue.h.
References isInt().
Referenced by clang::Sema::ActOnOMPArrayShapingExpr(), AnalyzeBitFieldAssignment(), calculateConstraintSatisfaction(), canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), clang::Sema::CheckAdditionOperands(), checkArrayExpressionDoesNotReferToUnitySize(), checkArrayExpressionDoesNotReferToWholeSize(), checkFormatStringExpr(), clang::Sema::CheckLogicalOperands(), checkOMPArraySectionConstantForReduction(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::Sema::CheckSubtractionOperands(), DiagnoseBadDivideOrRemainderValues(), DiagnoseBadShiftValues(), diagnoseWellFormedUnsatisfiedConstraintExpr(), EvalAndBitcastToAPInt(), EvaluateInteger(), clang::Sema::FillInlineAsmIdentifierInfo(), getInt(), clang::ConstantExpr::getResultAsAPSInt(), GetValueRange(), handleCompareOpForVector(), HandleConversionToBool(), handleLogicalOpForVector(), handleVectorVectorBinOp(), isInLoop(), needsCleanup(), clang::InitializationSequence::Perform(), printPretty(), Profile(), SemaBuiltinAlignment(), shouldAddCase(), toIntegralConstant(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), and clang::Sema::VerifyIntegerConstantExpression().
getInt() [2/2]
const APSInt & clang::APValue::getInt () const inline
Definition at line 419 of file APValue.h.
References getInt().
getKind()
ValueKind clang::APValue::getKind () const inline
Definition at line 387 of file APValue.h.
Referenced by APValue(), handleCompareOpForVector(), HandleConversionToBool(), handleLogicalOpForVector(), handleVectorVectorBinOp(), clang::ASTNodeImporter::ImportAPValue(), needsCleanup(), and printPretty().
getLValueBase()
const APValue::LValueBase APValue::getLValueBase () const
Definition at line 893 of file APValue.cpp.
References isLValue().
Referenced by APValue(), EvaluateBuiltinConstantPForLValue(), getLValueType(), clang::ASTNodeImporter::ImportAPValue(), clang::Expr::EvalResult::isGlobalLValue(), isNullPointerValueTemplateArgument(), printPretty(), Profile(), and toIntegralConstant().
getLValueCallIndex()
unsigned APValue::getLValueCallIndex () const
Definition at line 919 of file APValue.cpp.
References isLValue().
getLValueOffset() [1/2]
CharUnits & APValue::getLValueOffset ()
Definition at line 903 of file APValue.cpp.
References isLValue().
Referenced by addOrSubLValueAsInteger(), APValue(), EvaluateBuiltinConstantPForLValue(), getLValueOffset(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), Profile(), and toIntegralConstant().
getLValueOffset() [2/2]
const CharUnits & clang::APValue::getLValueOffset () const inline
Definition at line 479 of file APValue.h.
References getLValueOffset().
getLValuePath()
ArrayRef< APValue::LValuePathEntry > APValue::getLValuePath () const
Definition at line 913 of file APValue.cpp.
References clang::APValue::LV::getPath(), hasLValuePath(), and isLValue().
Referenced by APValue(), getLValueType(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
getLValueVersion()
unsigned APValue::getLValueVersion () const
Definition at line 924 of file APValue.cpp.
References isLValue().
getMemberPointerDecl()
const ValueDecl * APValue::getMemberPointerDecl () const
Definition at line 976 of file APValue.cpp.
References isMemberPointer().
Referenced by APValue(), clang::ASTContext::getMemberPointerPathAdjustment(), HandleConversionToBool(), clang::ASTNodeImporter::ImportAPValue(), isNullPointerValueTemplateArgument(), printPretty(), and Profile().
getMemberPointerPath()
ArrayRef< const CXXRecordDecl * > APValue::getMemberPointerPath () const
Definition at line 990 of file APValue.cpp.
References clang::APValue::MemberPointerData::getPath(), and isMemberPointer().
Referenced by APValue(), clang::ASTContext::getMemberPointerPathAdjustment(), clang::ASTNodeImporter::ImportAPValue(), and Profile().
getStructBase() [1/2]
APValue & clang::APValue::getStructBase (unsigned i) inline
Definition at line 538 of file APValue.h.
References getStructNumBases(), and isStruct().
Referenced by APValue(), findSubobject(), getStructBase(), HandleDestructionImpl(), printPretty(), and Profile().
getStructBase() [2/2]
const APValue & clang::APValue::getStructBase (unsigned i) const inline
Definition at line 548 of file APValue.h.
References getStructBase().
getStructField() [1/2]
APValue & clang::APValue::getStructField (unsigned i) inline
Definition at line 543 of file APValue.h.
References getStructNumBases(), getStructNumFields(), and isStruct().
Referenced by APValue(), findSubobject(), clang::MSGuidDecl::getAsAPValue(), getStructField(), HandleDestructionImpl(), printPretty(), and Profile().
getStructField() [2/2]
const APValue & clang::APValue::getStructField (unsigned i) const inline
Definition at line 551 of file APValue.h.
References getStructField().
getStructNumBases()
unsigned clang::APValue::getStructNumBases () const inline
Definition at line 530 of file APValue.h.
References isStruct().
Referenced by APValue(), getStructBase(), getStructField(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), Profile(), and clang::TextNodeDumper::Visit().
getStructNumFields()
unsigned clang::APValue::getStructNumFields () const inline
Definition at line 534 of file APValue.h.
References isStruct().
Referenced by APValue(), getStructField(), clang::ASTNodeImporter::ImportAPValue(), Profile(), and clang::TextNodeDumper::Visit().
getUnionField()
const FieldDecl * clang::APValue::getUnionField () const inline
Definition at line 555 of file APValue.h.
References isUnion().
Referenced by APValue(), findSubobject(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
getUnionValue() [1/2]
APValue & clang::APValue::getUnionValue () inline
Definition at line 559 of file APValue.h.
References isUnion().
Referenced by APValue(), findSubobject(), getUnionValue(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), Profile(), and clang::TextNodeDumper::Visit().
getUnionValue() [2/2]
const APValue & clang::APValue::getUnionValue () const inline
Definition at line 563 of file APValue.h.
References getUnionValue().
getVectorElt() [1/2]
APValue & clang::APValue::getVectorElt (unsigned I) inline
Definition at line 489 of file APValue.h.
References getVectorLength(), and isVector().
Referenced by EvalAndBitcastToAPInt(), GetValueRange(), getVectorElt(), handleVectorVectorBinOp(), IsSameFloatAfterCast(), printPretty(), Profile(), and clang::CodeGen::ConstantEmitter::tryEmitPrivate().
getVectorElt() [2/2]
const APValue & clang::APValue::getVectorElt (unsigned I) const inline
Definition at line 494 of file APValue.h.
References getVectorElt().
getVectorLength()
unsigned clang::APValue::getVectorLength () const inline
Definition at line 497 of file APValue.h.
References isVector().
Referenced by APValue(), EvalAndBitcastToAPInt(), GetValueRange(), getVectorElt(), handleVectorVectorBinOp(), clang::ASTNodeImporter::ImportAPValue(), IsSameFloatAfterCast(), printPretty(), and Profile().
hasArrayFiller()
bool clang::APValue::hasArrayFiller () const inline
Definition at line 510 of file APValue.h.
References getArrayInitializedElts(), and getArraySize().
Referenced by APValue(), expandArray(), getArrayFiller(), and Profile().
hasLValuePath()
bool APValue::hasLValuePath () const
Definition at line 908 of file APValue.cpp.
References isLValue().
Referenced by addOrSubLValueAsInteger(), APValue(), getLValuePath(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
hasValue()
bool clang::APValue::hasValue () const inline
Definition at line 391 of file APValue.h.
References Indeterminate.
Referenced by getBuiltinAlignArguments().
IndeterminateValue()
static APValue clang::APValue::IndeterminateValue () inline static
Definition at line 358 of file APValue.h.
References Indeterminate, and clang::Result.
Referenced by clang::ConstantExpr::getAPValueResult(), and getDefaultInitValue().
isAbsent()
bool clang::APValue::isAbsent () const inline
Definition at line 389 of file APValue.h.
References None.
Referenced by findSubobject(), and clang::MSGuidDecl::getAsAPValue().
isAddrLabelDiff()
bool clang::APValue::isAddrLabelDiff () const inline
Definition at line 404 of file APValue.h.
References AddrLabelDiff.
Referenced by getAddrLabelDiffLHS(), getAddrLabelDiffRHS(), and GetValueRange().
isArray()
bool clang::APValue::isArray () const inline
Definition at line 400 of file APValue.h.
References Array.
Referenced by getArrayFiller(), getArrayInitializedElt(), getArrayInitializedElts(), and getArraySize().
isComplexFloat()
bool clang::APValue::isComplexFloat () const inline
Definition at line 397 of file APValue.h.
References ComplexFloat.
Referenced by findSubobject(), getComplexFloatImag(), getComplexFloatReal(), IsSameFloatAfterCast(), and setComplexFloat().
isComplexInt()
bool clang::APValue::isComplexInt () const inline
Definition at line 396 of file APValue.h.
References ComplexInt.
Referenced by findSubobject(), getComplexIntImag(), getComplexIntReal(), GetValueRange(), and setComplexInt().
isFixedPoint()
bool clang::APValue::isFixedPoint () const inline
Definition at line 395 of file APValue.h.
References FixedPoint.
Referenced by EvaluateFixedPoint(), getFixedPoint(), and setFixedPoint().
isFloat()
bool clang::APValue::isFloat () const inline
Definition at line 394 of file APValue.h.
References Float.
Referenced by EvalAndBitcastToAPInt(), getFloat(), clang::StandardConversionSequence::getNarrowingKind(), IsSameFloatAfterCast(), setFloat(), and clang::CodeGen::ConstantEmitter::tryEmitPrivate().
isIndeterminate()
bool clang::APValue::isIndeterminate () const inline
Definition at line 390 of file APValue.h.
References Indeterminate.
Referenced by findSubobject().
isInt()
bool clang::APValue::isInt () const inline
Definition at line 393 of file APValue.h.
References Int.
Referenced by CheckConvertedConstantExpression(), CheckEvalInICE(), clang::Sema::diagnoseArgDependentDiagnoseIfAttrs(), EvalAndBitcastToAPInt(), EvaluateInteger(), getInt(), GetValueRange(), setInt(), shouldAddCase(), toIntegralConstant(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), and clang::Sema::VerifyIntegerConstantExpression().
isLValue()
bool clang::APValue::isLValue () const inline
Definition at line 398 of file APValue.h.
References LValue.
Referenced by getLValueBase(), getLValueCallIndex(), getLValueOffset(), getLValuePath(), getLValueVersion(), GetValueRange(), handleVectorVectorBinOp(), hasLValuePath(), clang::Expr::EvalResult::isGlobalLValue(), isLValueOnePastTheEnd(), isNullPointer(), isNullPointerValueTemplateArgument(), setLValue(), and toIntegralConstant().
isLValueOnePastTheEnd()
bool APValue::isLValueOnePastTheEnd () const
Definition at line 898 of file APValue.cpp.
References isLValue().
Referenced by APValue(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), and Profile().
isMemberPointer()
bool clang::APValue::isMemberPointer () const inline
Definition at line 403 of file APValue.h.
References MemberPointer.
Referenced by getMemberPointerDecl(), getMemberPointerPath(), isMemberPointerToDerivedMember(), and isNullPointerValueTemplateArgument().
isMemberPointerToDerivedMember()
bool APValue::isMemberPointerToDerivedMember () const
Definition at line 983 of file APValue.cpp.
References isMemberPointer().
Referenced by APValue(), clang::ASTContext::getMemberPointerPathAdjustment(), clang::ASTNodeImporter::ImportAPValue(), and Profile().
isNullPointer()
bool APValue::isNullPointer () const
Definition at line 929 of file APValue.cpp.
References isLValue().
Referenced by APValue(), clang::ASTNodeImporter::ImportAPValue(), printPretty(), Profile(), and toIntegralConstant().
isStruct()
bool clang::APValue::isStruct () const inline
Definition at line 401 of file APValue.h.
References Struct.
Referenced by getStructBase(), getStructField(), getStructNumBases(), and getStructNumFields().
isUnion()
bool clang::APValue::isUnion () const inline
Definition at line 402 of file APValue.h.
References Union.
Referenced by getUnionField(), getUnionValue(), and setUnion().
isVector()
bool clang::APValue::isVector () const inline
Definition at line 399 of file APValue.h.
References Vector.
Referenced by EvalAndBitcastToAPInt(), GetValueRange(), getVectorElt(), getVectorLength(), handleVectorVectorBinOp(), and IsSameFloatAfterCast().
needsCleanup()
bool APValue::needsCleanup () const
Returns whether the object performed allocations.
If APValues are constructed via placement new, needsCleanup() indicates whether the destructor must be called in order to correctly free all allocated memory.
Definition at line 429 of file APValue.cpp.
References AddrLabelDiff, Array, ComplexFloat, ComplexInt, FixedPoint, Float, getComplexFloatImag(), getComplexFloatReal(), getComplexIntImag(), getComplexIntReal(), getFixedPoint(), getFloat(), getInt(), getKind(), Indeterminate, Int, LValue, MemberPointer, needsCleanup(), None, Struct, Union, and Vector.
Referenced by needsCleanup().
operator=() [1/2]
APValue & APValue::operator= (APValue && RHS)
Definition at line 392 of file APValue.cpp.
References Indeterminate, and None.
operator=() [2/2]
APValue & APValue::operator= (const APValue & RHS)
Definition at line 386 of file APValue.cpp.
References APValue().
printPretty() [1/2]
void APValue::printPretty (raw_ostream & OS, const ASTContext & Ctx, QualType Ty) const
Definition at line 628 of file APValue.cpp.
References clang::ASTContext::getPrintingPolicy(), and printPretty().
Referenced by getAsString(), clang::TemplateParamObjectDecl::printAsInit(), printPretty(), and printPretty().
printPretty() [2/2]
void APValue::printPretty (raw_ostream & OS, const PrintingPolicy & Policy, QualType Ty, const ASTContext * Ctx = nullptr) const
Definition at line 633 of file APValue.cpp.
References AddrLabelDiff, Array, clang::CXXRecordDecl::bases_begin(), clang::CXXRecordDecl::bases_end(), clang::cast(), clang::Type::castAs(), clang::Type::castAsArrayTypeUnsafe(), ComplexFloat, ComplexInt, clang::RecordDecl::fields(), clang::First, FixedPoint, Float, getAddrLabelDiffLHS(), getAddrLabelDiffRHS(), GetApproxValue(), getArrayInitializedElt(), getArrayInitializedElts(), getComplexFloatImag(), getComplexFloatReal(), getComplexIntImag(), getComplexIntReal(), clang::ArrayType::getElementType(), getFixedPoint(), getFloat(), getInt(), getKind(), clang::AddrLabelExpr::getLabel(), getLValueBase(), getLValueOffset(), getLValuePath(), getMemberPointerDecl(), clang::NamedDecl::getName(), clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::CharUnits::getQuantity(), getStructBase(), getStructField(), getStructNumBases(), clang::CXXBaseSpecifier::getType(), clang::ValueDecl::getType(), clang::ASTContext::getTypeSizeInChars(), getUnionField(), getUnionValue(), getVectorElt(), getVectorLength(), hasLValuePath(), Indeterminate, Int, clang::Type::isBooleanType(), isLValueOnePastTheEnd(), clang::QualType::isNull(), isNullPointer(), clang::Type::isRecordType(), clang::Type::isReferenceType(), clang::Type::isVoidType(), clang::CharUnits::isZero(), LValue, MemberPointer, N, None, clang::PrintingPolicy::Nullptr, clang::CharUnits::One(), printPretty(), clang::Stmt::printPretty(), clang::QualType::stream(), Struct, Union, Vector, and clang::CharUnits::Zero().
Profile()
void APValue::Profile (llvm::FoldingSetNodeID & ID) const
profile this value.
There is no guarantee that values of different types will not produce the same profiled value, so the type should typically also be profiled if it's not implied by the context.
Definition at line 477 of file APValue.cpp.
References AddrLabelDiff, Array, ComplexFloat, ComplexInt, FixedPoint, Float, getAddrLabelDiffLHS(), getAddrLabelDiffRHS(), getArrayFiller(), getArrayInitializedElt(), getArrayInitializedElts(), getArraySize(), getCanonicalDecl(), getComplexFloatImag(), getComplexFloatReal(), getComplexIntImag(), getComplexIntReal(), getFixedPoint(), getFloat(), getInt(), getLValueBase(), getLValueOffset(), getLValuePath(), getMemberPointerDecl(), getMemberPointerPath(), getStructBase(), getStructField(), getStructNumBases(), getStructNumFields(), getUnionField(), getUnionValue(), getValue(), getVectorElt(), getVectorLength(), hasArrayFiller(), hasLValuePath(), Indeterminate, Int, isLValueOnePastTheEnd(), isMemberPointerToDerivedMember(), isNullPointer(), LValue, MemberPointer, N, None, clang::APValue::LValueBase::Profile(), Profile(), profileIntValue(), Struct, Union, and Vector.
Referenced by Profile().
setAddrLabelDiff()
void clang::APValue::setAddrLabelDiff (const AddrLabelExpr * LHSExpr, const AddrLabelExpr * RHSExpr) inline
Definition at line 617 of file APValue.h.
Referenced by APValue(), and APValue().
setComplexFloat()
void clang::APValue::setComplexFloat (APFloat R, APFloat I) inline
Definition at line 604 of file APValue.h.
References isComplexFloat().
Referenced by APValue(), and APValue().
setComplexInt()
void clang::APValue::setComplexInt (APSInt R, APSInt I) inline
Definition at line 597 of file APValue.h.
References isComplexInt().
Referenced by APValue(), and APValue().
setFixedPoint()
void clang::APValue::setFixedPoint (APFixedPoint FX) inline
Definition at line 588 of file APValue.h.
References isFixedPoint().
setFloat()
void clang::APValue::setFloat (APFloat F) inline
Definition at line 584 of file APValue.h.
References isFloat().
Referenced by APValue().
setInt()
void clang::APValue::setInt (APSInt I) inline
Definition at line 580 of file APValue.h.
References isInt().
Referenced by APValue().
setLValue() [1/2]
void APValue::setLValue (LValueBase B, const CharUnits & O, ArrayRef< LValuePathEntry > Path, bool OnePastTheEnd, bool IsNullPtr)
Definition at line 958 of file APValue.cpp.
References memcpy().
setLValue() [2/2]
void APValue::setLValue (LValueBase B, const CharUnits & O, NoLValuePath , bool IsNullPtr)
Definition at line 934 of file APValue.cpp.
References isLValue(), and clang::APValue::LV::resizePath().
Referenced by APValue(), APValue(), and APValue().
setUnion()
void APValue::setUnion (const FieldDecl * Field, const APValue & Value)
Definition at line 969 of file APValue.cpp.
References isUnion().
Referenced by APValue(), APValue(), and findSubobject().
setVector()
void clang::APValue::setVector (const APValue * E, unsigned N) inline
Definition at line 592 of file APValue.h.
References N.
Referenced by APValue(), and APValue().
swap()
void APValue::swap (APValue & RHS)
Swaps the contents of this and the given APValue.
Definition at line 466 of file APValue.cpp.
Referenced by expandArray().
toIntegralConstant()
bool APValue::toIntegralConstant (APSInt & Result, QualType SrcTy, const ASTContext & Ctx) const
Try to convert this value to an integral constant.
This works if it's an integer, null pointer, or offset from a null pointer. Returns true on success.
Definition at line 873 of file APValue.cpp.
References getInt(), getLValueBase(), getLValueOffset(), clang::ASTContext::getTargetNullPointerValue(), isInt(), isLValue(), isNullPointer(), clang::ASTContext::MakeIntValue(), and clang::Result.
Referenced by clang::Sema::ActOnGCCAsmStmt().
Friends And Related Symbol Documentation
ASTImporter
friend class ASTImporter friend
Definition at line 254 of file APValue.h.
ASTNodeImporter
friend class ASTNodeImporter friend
Definition at line 255 of file APValue.h.
clang::serialization::BasicReaderBase
template<typename Impl > friend class clang::serialization::BasicReaderBase friend
Definition at line 253 of file APValue.h.
The documentation for this class was generated from the following files:
include/clang/AST/APValue.h
lib/AST/APValue.cpp
lib/AST/ASTDumper.cpp