clang: clang::CommaSeparatedList Class Reference
clang::CommaSeparatedList Class Reference
#include "/root/llvm-project/clang/lib/Format/FormatToken.h"
Public Member Functions
CommaSeparatedList (const FormatStyle &Style)
void precomputeFormattingInfos (const FormatToken *Token) override
After the TokenAnnotator has finished annotating all the tokens, this function precomputes required information for formatting.
unsigned formatAfterToken (LineState &State, ContinuationIndenter *Indenter, bool DryRun) override
Same as formatFromToken, but assumes that the first token has already been set thereby deciding on the first line break.
unsigned formatFromToken (LineState &State, ContinuationIndenter *Indenter, bool DryRun) override
Apply the special formatting that the given role demands.
void CommaFound (const FormatToken *Token) override
Adds Token as the next comma to the CommaSeparated list.
const FormatToken * lastComma () override
Public Member Functions inherited from clang::TokenRole
TokenRole (const FormatStyle &Style)
virtual ~TokenRole ()
Additional Inherited Members
Protected Attributes inherited from clang::TokenRole
const FormatStyle & Style
Detailed Description
Definition at line 773 of file FormatToken.h.
Constructor & Destructor Documentation
CommaSeparatedList()
clang::CommaSeparatedList::CommaSeparatedList (const FormatStyle & Style) inline
Definition at line 775 of file FormatToken.h.
Member Function Documentation
CommaFound()
void clang::CommaSeparatedList::CommaFound (const FormatToken * Token) inline override virtual
Adds Token as the next comma to the CommaSeparated list.
Reimplemented from clang::TokenRole.
Definition at line 787 of file FormatToken.h.
formatAfterToken()
unsigned clang::format::CommaSeparatedList::formatAfterToken (LineState & State, ContinuationIndenter * Indenter, bool DryRun) override virtual
Same as formatFromToken, but assumes that the first token has already been set thereby deciding on the first line break.
Reimplemented from clang::TokenRole.
Definition at line 76 of file FormatToken.cpp.
References clang::format::ContinuationIndenter::addTokenToState(), clang::format::BK_Block, FormatToken(), Indenter, and NewLine.
formatFromToken()
unsigned clang::format::CommaSeparatedList::formatFromToken (LineState & State, ContinuationIndenter * Indenter, bool DryRun) override virtual
Apply the special formatting that the given role demands.
Assumes that the token having this role is already formatted.
Continues formatting from State leaving indentation to Indenter and returns the total penalty that this formatting incurs.
Reimplemented from clang::TokenRole.
Definition at line 135 of file FormatToken.cpp.
lastComma()
const FormatToken * clang::CommaSeparatedList::lastComma () inline override virtual
Reimplemented from clang::TokenRole.
Definition at line 791 of file FormatToken.h.
precomputeFormattingInfos()
void clang::format::CommaSeparatedList::precomputeFormattingInfos (const FormatToken * Token) override virtual
After the TokenAnnotator has finished annotating all the tokens, this function precomputes required information for formatting.
Reimplemented from clang::TokenRole.
Definition at line 153 of file FormatToken.cpp.
References clang::format::CodePointsBetween(), FormatToken(), clang::Token::is(), clang::Token::isOneOf(), and UINT_MAX.
The documentation for this class was generated from the following files:
lib/Format/FormatToken.h
lib/Format/FormatToken.cpp