clang: clang::driver::tools::freebsd::Assembler Class Reference
clang::driver::tools::freebsd::Assembler Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/FreeBSD.h"
Public Member Functions
Assembler (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 22 of file FreeBSD.h.
Constructor & Destructor Documentation
Assembler()
clang::driver::tools::freebsd::Assembler::Assembler (const ToolChain & TC) inline
Definition at line 24 of file FreeBSD.h.
Member Function Documentation
ConstructJob()
void freebsd::Assembler::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 27 of file FreeBSD.cpp.
References clang::driver::tools::AddAssemblerKPIC(), clang::driver::ResponseFileSupport::AtFileCurCP(), clang::C, clang::driver::tools::claimNoWarnArgs(), clang::driver::tools::arm::getARMFloatABI(), clang::driver::tools::getCPUName(), clang::driver::ToolChain::getDriver(), clang::driver::InputInfo::getFilename(), clang::driver::tools::mips::getGnuCompatibleMipsABIName(), clang::driver::tools::mips::getMipsCPUAndABI(), clang::driver::tools::sparc::getSparcAsmModeForCPU(), clang::driver::Tool::getToolChain(), clang::driver::tools::arm::Hard, and v.
hasIntegratedCPP()
bool clang::driver::tools::freebsd::Assembler::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 27 of file FreeBSD.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/FreeBSD.h
lib/Driver/ToolChains/FreeBSD.cpp