clang: clang::DeclGroupRef Class Reference
clang::DeclGroupRef Class Reference
#include "clang/AST/DeclGroup.h"
Public Types
using iterator = Decl **
using const_iterator = Decl * const *
Public Member Functions
DeclGroupRef ()=default
DeclGroupRef (Decl *d)
DeclGroupRef (DeclGroup *dg)
bool isNull () const
bool isSingleDecl () const
bool isDeclGroup () const
Decl * getSingleDecl ()
const Decl * getSingleDecl () const
DeclGroup & getDeclGroup ()
const DeclGroup & getDeclGroup () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void * getAsOpaquePtr () const
Static Public Member Functions
static DeclGroupRef Create (ASTContext &C, Decl **Decls, unsigned NumDecls)
static DeclGroupRef getFromOpaquePtr (void *Ptr)
Detailed Description
Definition at line 51 of file DeclGroup.h.
Member Typedef Documentation
const_iterator
using clang::DeclGroupRef::const_iterator = Decl * const *
Definition at line 77 of file DeclGroup.h.
iterator
using clang::DeclGroupRef::iterator = Decl **
Definition at line 76 of file DeclGroup.h.
Constructor & Destructor Documentation
DeclGroupRef() [1/3]
clang::DeclGroupRef::DeclGroupRef () default
Referenced by Create().
DeclGroupRef() [2/3]
clang::DeclGroupRef::DeclGroupRef (Decl * d) inline explicit
Definition at line 64 of file DeclGroup.h.
DeclGroupRef() [3/3]
clang::DeclGroupRef::DeclGroupRef (DeclGroup * dg) inline explicit
Definition at line 65 of file DeclGroup.h.
Member Function Documentation
begin() [1/2]
iterator clang::DeclGroupRef::begin () inline
Definition at line 99 of file DeclGroup.h.
References getDeclGroup(), and isSingleDecl().
Referenced by clang::Sema::ActOnAtEnd(), clang::DeclStmt::children(), clang::Sema::CodeCompleteObjCForCollection(), clang::DeclStmt::decl_begin(), clang::DeclStmt::decl_begin(), clang::BackendConsumer::HandleTopLevelDecl(), clang::ento::ModelConsumer::HandleTopLevelDecl(), clang::ASTNodeImporter::import(), and clang::index::IndexingContext::indexDeclGroupRef().
begin() [2/2]
const_iterator clang::DeclGroupRef::begin () const inline
Definition at line 112 of file DeclGroup.h.
References getDeclGroup(), and isSingleDecl().
Create()
static DeclGroupRef clang::DeclGroupRef::Create (ASTContext & C, Decl ** Decls, unsigned NumDecls) inline static
Definition at line 68 of file DeclGroup.h.
References clang::C, clang::DeclGroup::Create(), and DeclGroupRef().
Referenced by clang::Sema::ActOnOpenMPDeclareReductionDirectiveStart(), clang::Sema::BuildDeclaratorGroup(), buildPreInits(), clang::Sema::ConvertDeclToDeclGroup(), and clang::ASTNodeImporter::import().
end() [1/2]
iterator clang::DeclGroupRef::end () inline
Definition at line 105 of file DeclGroup.h.
References getDeclGroup(), isSingleDecl(), and clang::DeclGroup::size().
Referenced by clang::Sema::ActOnAtEnd(), clang::DeclStmt::children(), clang::Sema::CodeCompleteObjCForCollection(), clang::DeclStmt::decl_end(), clang::DeclStmt::decl_end(), clang::ento::ModelConsumer::HandleTopLevelDecl(), clang::ASTNodeImporter::import(), and clang::index::IndexingContext::indexDeclGroupRef().
end() [2/2]
const_iterator clang::DeclGroupRef::end () const inline
Definition at line 118 of file DeclGroup.h.
References getDeclGroup(), isSingleDecl(), and clang::DeclGroup::size().
getAsOpaquePtr()
void * clang::DeclGroupRef::getAsOpaquePtr () const inline
Definition at line 125 of file DeclGroup.h.
getDeclGroup() [1/2]
DeclGroup & clang::DeclGroupRef::getDeclGroup () inline
Definition at line 91 of file DeclGroup.h.
References isDeclGroup().
Referenced by begin(), begin(), end(), end(), and getDeclGroup().
getDeclGroup() [2/2]
const DeclGroup & clang::DeclGroupRef::getDeclGroup () const inline
Definition at line 95 of file DeclGroup.h.
References getDeclGroup().
getFromOpaquePtr()
static DeclGroupRef clang::DeclGroupRef::getFromOpaquePtr (void * Ptr) inline static
Definition at line 126 of file DeclGroup.h.
References X().
Referenced by llvm::PointerLikeTypeTraits< clang::DeclGroupRef >::getFromVoidPointer().
getSingleDecl() [1/2]
Decl * clang::DeclGroupRef::getSingleDecl () inline
Definition at line 83 of file DeclGroup.h.
References isSingleDecl().
Referenced by clang::Sema::ActOnForEachDeclStmt(), getSingleDecl(), clang::DeclStmt::getSingleDecl(), and clang::DeclStmt::getSingleDecl().
getSingleDecl() [2/2]
const Decl * clang::DeclGroupRef::getSingleDecl () const inline
Definition at line 87 of file DeclGroup.h.
References getSingleDecl().
isDeclGroup()
bool clang::DeclGroupRef::isDeclGroup () const inline
Definition at line 81 of file DeclGroup.h.
Referenced by getDeclGroup().
isNull()
bool clang::DeclGroupRef::isNull () const inline
Definition at line 79 of file DeclGroup.h.
Referenced by clang::Sema::ActOnDeclStmt(), clang::Sema::ActOnForEachDeclStmt(), and clang::ASTNodeImporter::import().
isSingleDecl()
bool clang::DeclGroupRef::isSingleDecl () const inline
Definition at line 80 of file DeclGroup.h.
Referenced by clang::Sema::ActOnForEachDeclStmt(), begin(), begin(), end(), end(), getSingleDecl(), and clang::DeclStmt::isSingleDecl().
The documentation for this class was generated from the following file:
include/clang/AST/DeclGroup.h