clang: clang::api_notes::VariableInfo Class Reference
clang::api_notes::VariableInfo Class Reference
API notes for a variable/property.
#include "clang/APINotes/Types.h"
Public Member Functions
VariableInfo ()
llvm::Optional< NullabilityKind > getNullability () const
void setNullabilityAudited (NullabilityKind kind)
const std::string & getType () const
void setType (const std::string &type)
VariableInfo & operator|= (const VariableInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Friends
bool operator== (const VariableInfo &LHS, const VariableInfo &RHS)
Additional Inherited Members
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Detailed Description
API notes for a variable/property.
Definition at line 300 of file Types.h.
Constructor & Destructor Documentation
VariableInfo()
clang::api_notes::VariableInfo::VariableInfo () inline
Definition at line 312 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::VariableInfo::dump (llvm::raw_ostream & OS) const
Definition at line 48 of file APINotesTypes.cpp.
References clang::api_notes::CommonEntityInfo::dump().
Referenced by clang::api_notes::ObjCPropertyInfo::dump(), and clang::api_notes::ParamInfo::dump().
getNullability()
llvm::Optional< NullabilityKind > clang::api_notes::VariableInfo::getNullability () const inline
Definition at line 314 of file Types.h.
Referenced by clang::api_notes::ObjCPropertyInfo::operator|=(), and operator|=().
getType()
const std::string & clang::api_notes::VariableInfo::getType () const inline
Definition at line 325 of file Types.h.
operator|=()
VariableInfo & clang::api_notes::VariableInfo::operator|= (const VariableInfo & RHS) inline
Definition at line 330 of file Types.h.
References getNullability(), and setNullabilityAudited().
setNullabilityAudited()
void clang::api_notes::VariableInfo::setNullabilityAudited (NullabilityKind kind) inline
Definition at line 320 of file Types.h.
Referenced by clang::api_notes::ObjCPropertyInfo::operator|=(), and operator|=().
setType()
void clang::api_notes::VariableInfo::setType (const std::string & type) inline
Definition at line 326 of file Types.h.
References clang::ast_matchers::type.
Friends And Related Symbol Documentation
operator==
bool operator== (const VariableInfo & LHS, const VariableInfo & RHS) friend
Definition at line 344 of file Types.h.
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp