clang: clang::NestedNameSpecifierLocBuilder Class Reference
clang::NestedNameSpecifierLocBuilder Class Reference
Class that aids in the construction of nested-name-specifiers along with source-location information for all of the components of the nested-name-specifier.
#include "clang/AST/NestedNameSpecifier.h"
Public Member Functions
NestedNameSpecifierLocBuilder ()=default
NestedNameSpecifierLocBuilder (const NestedNameSpecifierLocBuilder &Other)
NestedNameSpecifierLocBuilder & operator= (const NestedNameSpecifierLocBuilder &Other)
~NestedNameSpecifierLocBuilder ()
NestedNameSpecifier * getRepresentation () const
Retrieve the representation of the nested-name-specifier.
void Extend (ASTContext &Context, SourceLocation TemplateKWLoc, TypeLoc TL, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'type::'.
void Extend (ASTContext &Context, IdentifierInfo *Identifier, SourceLocation IdentifierLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'identifier::'.
void Extend (ASTContext &Context, NamespaceDecl *Namespace, SourceLocation NamespaceLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace::'.
void Extend (ASTContext &Context, NamespaceAliasDecl *Alias, SourceLocation AliasLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace-alias::'.
void MakeGlobal (ASTContext &Context, SourceLocation ColonColonLoc)
Turn this (empty) nested-name-specifier into the global nested-name-specifier '::'.
void MakeSuper (ASTContext &Context, CXXRecordDecl *RD, SourceLocation SuperLoc, SourceLocation ColonColonLoc)
Turns this (empty) nested-name-specifier into '__super' nested-name-specifier.
void MakeTrivial (ASTContext &Context, NestedNameSpecifier *Qualifier, SourceRange R)
Make a new nested-name-specifier from incomplete source-location information.
void Adopt (NestedNameSpecifierLoc Other)
Adopt an existing nested-name-specifier (with source-range information).
SourceRange getSourceRange () const LLVM_READONLY
Retrieve the source range covered by this nested-name-specifier.
NestedNameSpecifierLoc getWithLocInContext (ASTContext &Context) const
Retrieve a nested-name-specifier with location information, copied into the given AST context.
NestedNameSpecifierLoc getTemporary () const
Retrieve a nested-name-specifier with location information based on the information in this builder.
void Clear ()
Clear out this builder, and prepare it to build another nested-name-specifier with source-location information.
std::pair< char *, unsigned > getBuffer () const
Retrieve the underlying buffer.
Detailed Description
Class that aids in the construction of nested-name-specifiers along with source-location information for all of the components of the nested-name-specifier.
Definition at line 356 of file NestedNameSpecifier.h.
Constructor & Destructor Documentation
NestedNameSpecifierLocBuilder() [1/2]
clang::NestedNameSpecifierLocBuilder::NestedNameSpecifierLocBuilder () default
NestedNameSpecifierLocBuilder() [2/2]
NestedNameSpecifierLocBuilder::NestedNameSpecifierLocBuilder (const NestedNameSpecifierLocBuilder & Other)
Definition at line 503 of file NestedNameSpecifier.cpp.
References Append(), and clang::if().
~NestedNameSpecifierLocBuilder()
clang::NestedNameSpecifierLocBuilder::~NestedNameSpecifierLocBuilder () inline
Definition at line 384 of file NestedNameSpecifier.h.
Member Function Documentation
Adopt()
void NestedNameSpecifierLocBuilder::Adopt (NestedNameSpecifierLoc Other)
Adopt an existing nested-name-specifier (with source-range information).
Definition at line 669 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), and clang::NestedNameSpecifierLoc::getOpaqueData().
Clear()
void clang::NestedNameSpecifierLocBuilder::Clear () inline
Clear out this builder, and prepare it to build another nested-name-specifier with source-location information.
Definition at line 505 of file NestedNameSpecifier.h.
Extend() [1/4]
void NestedNameSpecifierLocBuilder::Extend (ASTContext & Context, IdentifierInfo * Identifier, SourceLocation IdentifierLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'identifier::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Identifier The identifier.
IdentifierLoc The location of the identifier.
ColonColonLoc The location of the trailing '::'.
Definition at line 573 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::Create(), Identifier, and SaveSourceLocation().
Extend() [2/4]
void NestedNameSpecifierLocBuilder::Extend (ASTContext & Context, NamespaceAliasDecl * Alias, SourceLocation AliasLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace-alias::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Alias The namespace alias.
AliasLoc The location of the namespace alias name.
ColonColonLoc The location of the trailing '::'.
Definition at line 597 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::Create(), and SaveSourceLocation().
Extend() [3/4]
void NestedNameSpecifierLocBuilder::Extend (ASTContext & Context, NamespaceDecl * Namespace, SourceLocation NamespaceLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Namespace The namespace.
NamespaceLoc The location of the namespace name.
ColonColonLoc The location of the trailing '::'.
Definition at line 585 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::Create(), and SaveSourceLocation().
Extend() [4/4]
void NestedNameSpecifierLocBuilder::Extend (ASTContext & Context, SourceLocation TemplateKWLoc, TypeLoc TL, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'type::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
TemplateKWLoc The location of the 'template' keyword, if present.
TL The TypeLoc that describes the type preceding the '::'.
ColonColonLoc The location of the trailing '::'.
Definition at line 560 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::Create(), clang::TypeLoc::getOpaqueData(), clang::TypeLoc::getTypePtr(), clang::SourceLocation::isValid(), SavePointer(), and SaveSourceLocation().
getBuffer()
std::pair< char *, unsigned > clang::NestedNameSpecifierLocBuilder::getBuffer () const inline
Retrieve the underlying buffer.
Returns
A pair containing a pointer to the buffer of source-location data and the size of the source-location data that resides in that buffer.
Definition at line 515 of file NestedNameSpecifier.h.
getRepresentation()
NestedNameSpecifier * clang::NestedNameSpecifierLocBuilder::getRepresentation () const inline
Retrieve the representation of the nested-name-specifier.
Definition at line 390 of file NestedNameSpecifier.h.
getSourceRange()
SourceRange clang::NestedNameSpecifierLocBuilder::getSourceRange () const inline
Retrieve the source range covered by this nested-name-specifier.
Definition at line 483 of file NestedNameSpecifier.h.
References clang::NestedNameSpecifierLoc::getSourceRange().
getTemporary()
NestedNameSpecifierLoc clang::NestedNameSpecifierLocBuilder::getTemporary () const inline
Retrieve a nested-name-specifier with location information based on the information in this builder.
This loc will contain references to the builder's internal data and may be invalidated by any change to the builder.
Definition at line 499 of file NestedNameSpecifier.h.
getWithLocInContext()
NestedNameSpecifierLoc NestedNameSpecifierLocBuilder::getWithLocInContext (ASTContext & Context) const
Retrieve a nested-name-specifier with location information, copied into the given AST context.
Parameters
Context The context into which this nested-name-specifier will be copied.
Definition at line 689 of file NestedNameSpecifier.cpp.
References clang::ASTContext::Allocate(), and memcpy().
Referenced by clang::Sema::ActOnMSVCUnknownTypeName(), clang::ASTImporter::Import(), and clang::ASTRecordReader::readNestedNameSpecifierLoc().
MakeGlobal()
void NestedNameSpecifierLocBuilder::MakeGlobal (ASTContext & Context, SourceLocation ColonColonLoc)
Turn this (empty) nested-name-specifier into the global nested-name-specifier '::'.
Definition at line 608 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::GlobalSpecifier(), and SaveSourceLocation().
MakeSuper()
void NestedNameSpecifierLocBuilder::MakeSuper (ASTContext & Context, CXXRecordDecl * RD, SourceLocation SuperLoc, SourceLocation ColonColonLoc)
Turns this (empty) nested-name-specifier into '__super' nested-name-specifier.
Parameters
Context The AST context in which this nested-name-specifier resides.
RD The declaration of the class in which nested-name-specifier appeared.
SuperLoc The location of the '__super' keyword. name.
ColonColonLoc The location of the trailing '::'.
Definition at line 617 of file NestedNameSpecifier.cpp.
References SaveSourceLocation(), and clang::NestedNameSpecifier::SuperSpecifier().
MakeTrivial()
void NestedNameSpecifierLocBuilder::MakeTrivial (ASTContext & Context, NestedNameSpecifier * Qualifier, SourceRange R)
Make a new nested-name-specifier from incomplete source-location information.
This routine should be used very, very rarely, in cases where we need to synthesize a nested-name-specifier. Most code should instead use Adopt() with a proper NestedNameSpecifierLoc.
Definition at line 628 of file NestedNameSpecifier.cpp.
References clang::NestedNameSpecifier::getAsType(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::NestedNameSpecifier::getKind(), clang::TypeLoc::getOpaqueData(), clang::NestedNameSpecifier::getPrefix(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::TypeSourceInfo::getTypeLoc(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, SavePointer(), SaveSourceLocation(), clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by clang::Sema::ActOnMSVCUnknownTypeName(), clang::Sema::BuildUsingDeclaration(), clang::DependentNameTypeLoc::initializeLocal(), clang::DependentTemplateSpecializationTypeLoc::initializeLocal(), and clang::ElaboratedTypeLoc::initializeLocal().
operator=()
NestedNameSpecifierLocBuilder & NestedNameSpecifierLocBuilder::operator= (const NestedNameSpecifierLocBuilder & Other)
Definition at line 522 of file NestedNameSpecifier.cpp.
References Append(), and memcpy().
The documentation for this class was generated from the following files:
include/clang/AST/NestedNameSpecifier.h
lib/AST/NestedNameSpecifier.cpp