clang: clang::format::AffectedRangeManager Class Reference
clang::format::AffectedRangeManager Class Reference
#include "/root/llvm-project/clang/lib/Format/AffectedRangeManager.h"
Public Member Functions
AffectedRangeManager (const SourceManager &SourceMgr, const ArrayRef< CharSourceRange > Ranges)
bool computeAffectedLines (SmallVectorImpl< AnnotatedLine * > &Lines)
bool affectsCharSourceRange (const CharSourceRange &Range)
Detailed Description
Definition at line 25 of file AffectedRangeManager.h.
Constructor & Destructor Documentation
AffectedRangeManager()
clang::format::AffectedRangeManager::AffectedRangeManager (const SourceManager & SourceMgr, const ArrayRef< CharSourceRange > Ranges) inline
Definition at line 27 of file AffectedRangeManager.h.
Member Function Documentation
affectsCharSourceRange()
bool clang::format::AffectedRangeManager::affectsCharSourceRange (const CharSourceRange & Range)
Definition at line 60 of file AffectedRangeManager.cpp.
computeAffectedLines()
bool clang::format::AffectedRangeManager::computeAffectedLines (SmallVectorImpl< AnnotatedLine * > & Lines)
Definition at line 22 of file AffectedRangeManager.cpp.
References clang::Last.
Referenced by clang::format::JavaScriptImportSorter::analyze(), clang::format::NamespaceEndCommentsFixer::analyze(), and clang::format::UsingDeclarationsSorter::analyze().
The documentation for this class was generated from the following files:
lib/Format/AffectedRangeManager.h
lib/Format/AffectedRangeManager.cpp