clang: clang::CodeGen::CallArgList Class Reference
clang::CodeGen::CallArgList Class Reference
CallArgList - Type for representing both the value and type of arguments in a call.
#include "/root/llvm-project/clang/lib/CodeGen/CGCall.h"
Classes
struct CallArgCleanup
struct Writeback
Public Types
typedef llvm::iterator_range< SmallVectorImpl< Writeback >::const_iterator > writeback_const_range
Public Member Functions
CallArgList ()
void add (RValue rvalue, QualType type)
void addUncopiedAggregate (LValue LV, QualType type)
void addFrom (const CallArgList &other)
Add all the arguments from another CallArgList to this one.
void addWriteback (LValue srcLV, Address temporary, llvm::Value *toUse)
bool hasWritebacks () const
writeback_const_range writebacks () const
void addArgCleanupDeactivation (EHScopeStack::stable_iterator Cleanup, llvm::Instruction *IsActiveIP)
ArrayRef< CallArgCleanup > getCleanupsToDeactivate () const
void allocateArgumentMemory (CodeGenFunction &CGF)
llvm::Instruction * getStackBase () const
void freeArgumentMemory (CodeGenFunction &CGF) const
bool isUsingInAlloca () const
Returns if we're using an inalloca struct to pass arguments in memory.
Detailed Description
CallArgList - Type for representing both the value and type of arguments in a call.
Definition at line 264 of file CGCall.h.
Member Typedef Documentation
writeback_const_range
llvm::iterator_range<SmallVectorImpl<Writeback>::const_iterator> clang::CodeGen::CallArgList::writeback_const_range
Definition at line 317 of file CGCall.h.
Constructor & Destructor Documentation
CallArgList()
clang::CodeGen::CallArgList::CallArgList () inline
Definition at line 266 of file CGCall.h.
Member Function Documentation
add()
void clang::CodeGen::CallArgList::add (RValue rvalue, QualType type) inline
Definition at line 288 of file CGCall.h.
Referenced by AddDirectArgument(), clang::CodeGen::CGCXXABI::addImplicitConstructorArgs(), commonEmitCXXMemberOrOperatorCall(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), emitStructGetterCall(), emitStructSetterCall(), and emitWritebackArg().
addArgCleanupDeactivation()
void clang::CodeGen::CallArgList::addArgCleanupDeactivation (EHScopeStack::stable_iterator Cleanup, llvm::Instruction * IsActiveIP) inline
Definition at line 323 of file CGCall.h.
References clang::CodeGen::CallArgList::CallArgCleanup::Cleanup, and clang::CodeGen::CallArgList::CallArgCleanup::IsActiveIP.
addFrom()
void clang::CodeGen::CallArgList::addFrom (const CallArgList & other) inline
Add all the arguments from another CallArgList to this one.
After doing this, the old CallArgList retains its list of arguments, but must not be used to emit a call.
Definition at line 297 of file CGCall.h.
Referenced by commonEmitCXXMemberOrOperatorCall().
addUncopiedAggregate()
void clang::CodeGen::CallArgList::addUncopiedAggregate (LValue LV, QualType type) inline
Definition at line 290 of file CGCall.h.
addWriteback()
void clang::CodeGen::CallArgList::addWriteback (LValue srcLV, Address temporary, llvm::Value * toUse) inline
Definition at line 309 of file CGCall.h.
Referenced by emitWritebackArg().
allocateArgumentMemory()
void CallArgList::allocateArgumentMemory (CodeGenFunction & CGF)
Definition at line 3818 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenModule::getIntrinsic().
freeArgumentMemory()
void CallArgList::freeArgumentMemory (CodeGenFunction & CGF) const
Definition at line 3826 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, and clang::CodeGen::CodeGenModule::getIntrinsic().
getCleanupsToDeactivate()
ArrayRef< CallArgCleanup > clang::CodeGen::CallArgList::getCleanupsToDeactivate () const inline
Definition at line 331 of file CGCall.h.
Referenced by deactivateArgCleanupsBeforeCall().
getStackBase()
llvm::Instruction * clang::CodeGen::CallArgList::getStackBase () const inline
Definition at line 336 of file CGCall.h.
hasWritebacks()
bool clang::CodeGen::CallArgList::hasWritebacks () const inline
Definition at line 314 of file CGCall.h.
isUsingInAlloca()
bool clang::CodeGen::CallArgList::isUsingInAlloca () const inline
Returns if we're using an inalloca struct to pass arguments in memory.
Definition at line 341 of file CGCall.h.
writebacks()
writeback_const_range clang::CodeGen::CallArgList::writebacks () const inline
Definition at line 319 of file CGCall.h.
Referenced by emitWritebacks().
The documentation for this class was generated from the following files:
lib/CodeGen/CGCall.h
lib/CodeGen/CGCall.cpp