clang: clang::ParmVarDecl Class Reference
clang::ParmVarDecl Class Reference
Represents a parameter to a function.
#include "clang/AST/Decl.h"
Public Types
enum { MaxFunctionScopeDepth = 255 }
enum { MaxFunctionScopeIndex = 255 }
Public Types inherited from clang::VarDecl
enum InitializationStyle { CInit , CallInit , ListInit }
Initialization styles.
enum TLSKind { TLS_None , TLS_Static , TLS_Dynamic }
Kinds of thread-local storage.
enum DefinitionKind { DeclarationOnly , TentativeDefinition , Definition }
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned { Unowned , Visible , VisibleWhenImported , ModulePrivate }
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range<attr_iterator>
using redecl_range = llvm::iterator_range<redecl_iterator>
Public Types inherited from clang::Redeclarable< VarDecl >
using redecl_range
Public Member Functions
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
void setObjCMethodScopeInfo (unsigned parameterIndex)
void setScopeInfo (unsigned scopeDepth, unsigned parameterIndex)
bool isObjCMethodParameter () const
bool isDestroyedInCallee () const
Determines whether this parameter is destroyed in the callee function.
unsigned getFunctionScopeDepth () const
unsigned getFunctionScopeIndex () const
Returns the index of this parameter in its prototype or method scope.
ObjCDeclQualifier getObjCDeclQualifier () const
void setObjCDeclQualifier (ObjCDeclQualifier QTVal)
bool isKNRPromoted () const
True if the value passed to this parameter must undergo K&R-style default argument promotion:
void setKNRPromoted (bool promoted)
Expr * getDefaultArg ()
const Expr * getDefaultArg () const
void setDefaultArg (Expr *defarg)
SourceRange getDefaultArgRange () const
Retrieve the source range that covers the entire default argument.
void setUninstantiatedDefaultArg (Expr *arg)
Expr * getUninstantiatedDefaultArg ()
const Expr * getUninstantiatedDefaultArg () const
bool hasDefaultArg () const
Determines whether this parameter has a default argument, either parsed or not.
bool hasUnparsedDefaultArg () const
Determines whether this parameter has a default argument that has not yet been parsed.
bool hasUninstantiatedDefaultArg () const
void setUnparsedDefaultArg ()
Specify that this parameter has an unparsed default argument.
bool hasInheritedDefaultArg () const
void setHasInheritedDefaultArg (bool I=true)
QualType getOriginalType () const
void setOwningFunction (DeclContext *FD)
Sets the function declaration that owns this ParmVarDecl.
Public Member Functions inherited from clang::VarDecl
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
StorageClass getStorageClass () const
Returns the storage class as written in the source.
void setStorageClass (StorageClass SC)
void setTSCSpec (ThreadStorageClassSpecifier TSC)
ThreadStorageClassSpecifier getTSCSpec () const
TLSKind getTLSKind () const
bool hasLocalStorage () const
Returns true if a variable with function scope is a non-static local variable.
bool isStaticLocal () const
Returns true if a variable with function scope is a static local variable.
bool hasExternalStorage () const
Returns true if a variable has extern or private_extern storage.
bool hasGlobalStorage () const
Returns true for all variables that do not have local storage.
StorageDuration getStorageDuration () const
Get the storage duration of this variable, per C++ [basic.stc].
LanguageLinkage getLanguageLinkage () const
Compute the language linkage.
bool isExternC () const
Determines whether this variable is a variable with external, C linkage.
bool isInExternCContext () const
Determines whether this variable's context is, or is nested within, a C++ extern "C" linkage spec.
bool isInExternCXXContext () const
Determines whether this variable's context is, or is nested within, a C++ extern "C++" linkage spec.
bool isLocalVarDecl () const
Returns true for local variable declarations other than parameters.
bool isLocalVarDeclOrParm () const
Similar to isLocalVarDecl but also includes parameters.
bool isFunctionOrMethodVarDecl () const
Similar to isLocalVarDecl, but excludes variables declared in blocks.
bool isStaticDataMember () const
Determines whether this is a static data member.
VarDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const VarDecl * getCanonicalDecl () const
DefinitionKind isThisDeclarationADefinition (ASTContext &) const
Check whether this declaration is a definition.
DefinitionKind isThisDeclarationADefinition () const
DefinitionKind hasDefinition (ASTContext &) const
Check whether this variable is defined in this translation unit.
DefinitionKind hasDefinition () const
VarDecl * getActingDefinition ()
Get the tentative definition that acts as the real definition in a TU.
const VarDecl * getActingDefinition () const
VarDecl * getDefinition (ASTContext &)
Get the real (not just tentative) definition for this declaration.
const VarDecl * getDefinition (ASTContext &C) const
VarDecl * getDefinition ()
const VarDecl * getDefinition () const
bool isOutOfLine () const override
Determine whether this is or was instantiated from an out-of-line definition of a static data member.
bool isFileVarDecl () const
Returns true for file scoped variable declaration.
const Expr * getAnyInitializer () const
Get the initializer for this variable, no matter which declaration it is attached to.
const Expr * getAnyInitializer (const VarDecl *&D) const
Get the initializer for this variable, no matter which declaration it is attached to.
bool hasInit () const
const Expr * getInit () const
Expr * getInit ()
Stmt ** getInitAddress ()
Retrieve the address of the initializer expression.
void setInit (Expr *I)
VarDecl * getInitializingDeclaration ()
Get the initializing declaration of this variable, if any.
const VarDecl * getInitializingDeclaration () const
bool mightBeUsableInConstantExpressions (const ASTContext &C) const
Determine whether this variable's value might be usable in a constant expression, according to the relevant language standard.
bool isUsableInConstantExpressions (const ASTContext &C) const
Determine whether this variable's value can be used in a constant expression, according to the relevant language standard, including checking whether it was initialized by a constant expression.
EvaluatedStmt * ensureEvaluatedStmt () const
Convert the initializer for this declaration to the elaborated EvaluatedStmt form, which contains extra information on the evaluated value of the initializer.
EvaluatedStmt * getEvaluatedStmt () const
APValue * evaluateValue () const
Attempt to evaluate the value of the initializer attached to this declaration, and produce notes explaining why it cannot be evaluated.
APValue * getEvaluatedValue () const
Return the already-evaluated value of this variable's initializer, or NULL if the value is not yet known.
bool evaluateDestruction (SmallVectorImpl< PartialDiagnosticAt > &Notes) const
Evaluate the destruction of this variable to determine if it constitutes constant destruction.
bool hasConstantInitialization () const
Determine whether this variable has constant initialization.
bool hasICEInitializer (const ASTContext &Context) const
Determine whether the initializer of this variable is an integer constant expression.
bool checkForConstantInitialization (SmallVectorImpl< PartialDiagnosticAt > &Notes) const
Evaluate the initializer of this variable to determine whether it's a constant initializer.
void setInitStyle (InitializationStyle Style)
InitializationStyle getInitStyle () const
The style of initialization for this declaration.
bool isDirectInit () const
Whether the initializer is a direct-initializer (list or call).
bool isThisDeclarationADemotedDefinition () const
If this definition should pretend to be a declaration.
void demoteThisDefinitionToDeclaration ()
This is a definition which should be demoted to a declaration.
bool isExceptionVariable () const
Determine whether this variable is the exception variable in a C++ catch statememt or an Objective-C @catch statement.
void setExceptionVariable (bool EV)
bool isNRVOVariable () const
Determine whether this local variable can be used with the named return value optimization (NRVO).
void setNRVOVariable (bool NRVO)
bool isCXXForRangeDecl () const
Determine whether this variable is the for-range-declaration in a C++0x for-range statement.
void setCXXForRangeDecl (bool FRD)
bool isObjCForDecl () const
Determine whether this variable is a for-loop declaration for a for-in statement in Objective-C.
void setObjCForDecl (bool FRD)
bool isARCPseudoStrong () const
Determine whether this variable is an ARC pseudo-__strong variable.
void setARCPseudoStrong (bool PS)
bool isInline () const
Whether this variable is (C++1z) inline.
bool isInlineSpecified () const
void setInlineSpecified ()
void setImplicitlyInline ()
bool isConstexpr () const
Whether this variable is (C++11) constexpr.
void setConstexpr (bool IC)
bool isInitCapture () const
Whether this variable is the implicit variable for a lambda init-capture.
void setInitCapture (bool IC)
bool isParameterPack () const
Determine whether this variable is actually a function parameter pack or init-capture pack.
bool isPreviousDeclInSameBlockScope () const
Whether this local extern variable declaration's previous declaration was declared in the same block scope.
void setPreviousDeclInSameBlockScope (bool Same)
bool isEscapingByref () const
Indicates the capture is a __block variable that is captured by a block that can potentially escape (a block for which BlockDecl::doesNotEscape returns false).
bool isNonEscapingByref () const
Indicates the capture is a __block variable that is never captured by an escaping block.
void setEscapingByref ()
VarDecl * getTemplateInstantiationPattern () const
Retrieve the variable declaration from which this variable could be instantiated, if it is an instantiation (rather than a non-template).
VarDecl * getInstantiatedFromStaticDataMember () const
If this variable is an instantiated static data member of a class template specialization, returns the templated static data member from which it was instantiated.
TemplateSpecializationKind getTemplateSpecializationKind () const
If this variable is an instantiation of a variable template or a static data member of a class template, determine what kind of template specialization or instantiation this is.
TemplateSpecializationKind getTemplateSpecializationKindForInstantiation () const
Get the template specialization kind of this variable for the purposes of template instantiation.
SourceLocation getPointOfInstantiation () const
If this variable is an instantiation of a variable template or a static data member of a class template, determine its point of instantiation.
MemberSpecializationInfo * getMemberSpecializationInfo () const
If this variable is an instantiation of a static data member of a class template specialization, retrieves the member specialization information.
void setTemplateSpecializationKind (TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation=SourceLocation())
For a static data member that was instantiated from a static data member of a class template, set the template specialiation kind.
void setInstantiationOfStaticDataMember (VarDecl *VD, TemplateSpecializationKind TSK)
Specify that this variable is an instantiation of the static data member VD.
VarTemplateDecl * getDescribedVarTemplate () const
Retrieves the variable template that is described by this variable declaration.
void setDescribedVarTemplate (VarTemplateDecl *Template)
bool isKnownToBeDefined () const
bool isNoDestroy (const ASTContext &) const
Is destruction of this variable entirely suppressed? If so, the variable need not have a usable destructor at all.
QualType::DestructionKind needsDestruction (const ASTContext &Ctx) const
Would the destruction of this variable have any effect, and if so, what kind?
Public Member Functions inherited from clang::DeclaratorDecl
TypeSourceInfo * getTypeSourceInfo () const
void setTypeSourceInfo (TypeSourceInfo *TI)
SourceLocation getInnerLocStart () const
Return start of source range ignoring outer template declarations.
void setInnerLocStart (SourceLocation L)
SourceLocation getOuterLocStart () const
Return start of source range taking into account any outer template declarations.
SourceLocation getBeginLoc () const LLVM_READONLY
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
Expr * getTrailingRequiresClause ()
Get the constraint-expression introduced by the trailing requires-clause in the function/member declaration, or null if no requires-clause was provided.
const Expr * getTrailingRequiresClause () const
void setTrailingRequiresClause (Expr *TrailingRequiresClause)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned index) const
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
SourceLocation getTypeSpecStartLoc () const
SourceLocation getTypeSpecEndLoc () const
Public Member Functions inherited from clang::ValueDecl
QualType getType () const
void setType (QualType newType)
bool isWeak () const
Determine whether this symbol is weakly-imported, or declared with the weak or weak-ref attr.
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &os) const
Pretty-print the unqualified name of this declaration.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getQualifiedNameAsString () const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
Optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod () const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod ()
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl ()
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
Public Member Functions inherited from clang::Redeclarable< VarDecl >
Redeclarable (const ASTContext &Ctx)
VarDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const VarDecl * getPreviousDecl () const
VarDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const VarDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
VarDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const VarDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (VarDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static ParmVarDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, StorageClass S, Expr *DefArg)
static ParmVarDecl * CreateDeserialized (ASTContext &C, unsigned ID)
static constexpr unsigned getMaxFunctionScopeDepth ()
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::VarDecl
static const char * getStorageClassSpecifierString (StorageClass SC)
Return the string used to specify the storage class SC.
static VarDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, StorageClass S)
static VarDecl * CreateDeserialized (ASTContext &C, unsigned ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::DeclaratorDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::ValueDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Protected Member Functions
ParmVarDecl (Kind DK, ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, StorageClass S, Expr *DefArg)
Protected Member Functions inherited from clang::VarDecl
VarDecl (Kind DK, ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, StorageClass SC)
VarDecl * getNextRedeclarationImpl () override
Returns the next redeclaration or itself if this is the only decl.
VarDecl * getPreviousDeclImpl () override
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
VarDecl * getMostRecentDeclImpl () override
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
Protected Member Functions inherited from clang::DeclaratorDecl
DeclaratorDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T, TypeSourceInfo *TInfo, SourceLocation StartL)
Protected Member Functions inherited from clang::ValueDecl
ValueDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T)
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::Redeclarable< VarDecl >
VarDecl * getNextRedeclaration () const
Additional Inherited Members
Public Attributes inherited from clang::VarDecl
Protected Types inherited from clang::VarDecl
enum { NumParameterIndexBits = 8 }
enum DefaultArgKind { DAK_None , DAK_Unparsed , DAK_Uninstantiated , DAK_Normal }
enum { NumScopeDepthOrObjCQualsBits = 7 }
using InitType = llvm::PointerUnion<Stmt *, EvaluatedStmt *>
using redeclarable_base = Redeclarable<VarDecl>
Static Protected Member Functions inherited from clang::Redeclarable< VarDecl >
static DeclLink PreviousDeclLink (VarDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::VarDecl
InitType Init
The initializer for this variable or, for a ParmVarDecl, the C++ default argument.
union {
unsigned AllBits
VarDeclBitfields VarDeclBits
ParmVarDeclBitfields ParmVarDeclBits
NonParmVarDeclBitfields NonParmVarDeclBits
};
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 2, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::Redeclarable< VarDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
VarDecl * First
Detailed Description
Represents a parameter to a function.
Definition at line 1620 of file Decl.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MaxFunctionScopeDepth
Definition at line 1622 of file Decl.h.
anonymous enum
anonymous enum
Enumerator
MaxFunctionScopeIndex
Definition at line 1623 of file Decl.h.
Constructor & Destructor Documentation
ParmVarDecl()
clang::ParmVarDecl::ParmVarDecl (Kind DK, ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, QualType T, TypeSourceInfo * TInfo, StorageClass S, Expr * DefArg) inline protected
Definition at line 1626 of file Decl.h.
References clang::VarDecl::DAK_None, clang::VarDecl::ParmVarDeclBits, and setDefaultArg().
Referenced by Create(), and CreateDeserialized().
Member Function Documentation
classof()
static bool clang::ParmVarDecl::classof (const Decl * D) inline static
Definition at line 1770 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::ParmVarDecl::classofKind (Kind K) inline static
Definition at line 1771 of file Decl.h.
Referenced by classof().
Create()
ParmVarDecl * ParmVarDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, QualType T, TypeSourceInfo * TInfo, StorageClass S, Expr * DefArg) static
Definition at line 2700 of file Decl.cpp.
References clang::C, Id, and ParmVarDecl().
Referenced by addFunctionPointerConversion(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildParmVarDeclForTypedef(), clang::Sema::CheckParameter(), clang::Sema::CreateBuiltin(), clang::Sema::DeclareGlobalAllocationFunction(), clang::Sema::DeclareImplicitCopyAssignment(), clang::Sema::DeclareImplicitCopyConstructor(), clang::Sema::DeclareImplicitMoveAssignment(), clang::Sema::DeclareImplicitMoveConstructor(), emitOutlinedFunctionPrologue(), clang::Sema::findInheritingConstructor(), getNSNumberFactoryMethod(), InsertOCLBuiltinDeclarationsFromTable(), clang::Sema::MergeFunctionDecl(), clang::Sema::ProcessPropertyDecl(), rewriteBuiltinFunctionDecl(), setPrototype(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), and clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter().
CreateDeserialized()
ParmVarDecl * ParmVarDecl::CreateDeserialized (ASTContext & C, unsigned ID) static
Definition at line 2717 of file Decl.cpp.
References clang::C, ParmVarDecl(), and clang::SC_None.
getDefaultArg() [1/2]
Expr * ParmVarDecl::getDefaultArg ()
Definition at line 2749 of file Decl.cpp.
References clang::VarDecl::getInit(), hasUninstantiatedDefaultArg(), and hasUnparsedDefaultArg().
Referenced by getDefaultArg(), clang::CXXDefaultArgExpr::getExpr(), clang::CXXDefaultArgExpr::getExpr(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::SubstParmVarDecl(), and clang::ASTNodeImporter::VisitCXXDefaultArgExpr().
getDefaultArg() [2/2]
const Expr * clang::ParmVarDecl::getDefaultArg () const inline
Definition at line 1709 of file Decl.h.
References getDefaultArg().
getDefaultArgRange()
SourceRange ParmVarDecl::getDefaultArgRange () const
Retrieve the source range that covers the entire default argument.
Definition at line 2766 of file Decl.cpp.
References clang::VarDecl::DAK_None, clang::VarDecl::DAK_Normal, clang::VarDecl::DAK_Uninstantiated, clang::VarDecl::DAK_Unparsed, clang::VarDecl::getInit(), clang::Stmt::getSourceRange(), getUninstantiatedDefaultArg(), and clang::VarDecl::ParmVarDeclBits.
Referenced by CheckOperatorNewDeclaration(), getSourceRange(), and clang::Sema::MergeCXXFunctionDecl().
getFunctionScopeDepth()
unsigned clang::ParmVarDecl::getFunctionScopeDepth () const inline
Definition at line 1670 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::ASTDeclWriter::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
getFunctionScopeIndex()
unsigned clang::ParmVarDecl::getFunctionScopeIndex () const inline
Returns the index of this parameter in its prototype or method scope.
Definition at line 1680 of file Decl.h.
Referenced by mergeParamDeclAttributes(), NoteLValueLocation(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::ASTDeclWriter::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
getMaxFunctionScopeDepth()
static constexpr unsigned clang::ParmVarDecl::getMaxFunctionScopeDepth () inline static constexpr
Definition at line 1675 of file Decl.h.
References clang::VarDecl::NumScopeDepthOrObjCQualsBits.
getObjCDeclQualifier()
ObjCDeclQualifier clang::ParmVarDecl::getObjCDeclQualifier () const inline
Definition at line 1684 of file Decl.h.
References clang::Decl::OBJC_TQ_None, and clang::VarDecl::ParmVarDeclBits.
Referenced by CheckMethodOverrideParam(), clang::ASTContext::getObjCEncodingForMethodDecl(), mergeInterfaceMethodToImpl(), mergeParamDeclTypes(), clang::ASTContext::ObjCMethodsAreEqual(), clang::ASTDeclWriter::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
getOriginalType()
QualType ParmVarDecl::getOriginalType () const
Definition at line 2709 of file Decl.cpp.
References clang::TypeSourceInfo::getType(), clang::ValueDecl::getType(), and clang::DeclaratorDecl::getTypeSourceInfo().
Referenced by clang::Sema::CheckParameter(), and clang::ASTContext::getObjCEncodingForMethodDecl().
getSourceRange()
SourceRange ParmVarDecl::getSourceRange () const override virtual
Source range that this declaration covers.
Reimplemented from clang::DeclaratorDecl.
Definition at line 2723 of file Decl.cpp.
References clang::DeclaratorDecl::getBeginLoc(), clang::Decl::getDeclContext(), getDefaultArgRange(), clang::SourceRange::getEnd(), clang::Decl::getLocation(), clang::DeclaratorDecl::getOuterLocStart(), clang::DeclaratorDecl::getSourceRange(), hasInheritedDefaultArg(), and clang::SourceRange::isValid().
Referenced by CheckConstexprParameterTypes(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::FunctionDecl::getParametersSourceRange(), and clang::Sema::SpecialMemberIsTrivial().
getUninstantiatedDefaultArg() [1/2]
Expr * ParmVarDecl::getUninstantiatedDefaultArg ()
Definition at line 2791 of file Decl.cpp.
References hasUninstantiatedDefaultArg(), and clang::VarDecl::Init.
Referenced by getDefaultArgRange(), getUninstantiatedDefaultArg(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitParmVarDecl().
getUninstantiatedDefaultArg() [2/2]
const Expr * clang::ParmVarDecl::getUninstantiatedDefaultArg () const inline
Definition at line 1720 of file Decl.h.
References getUninstantiatedDefaultArg().
hasDefaultArg()
bool ParmVarDecl::hasDefaultArg () const
Determines whether this parameter has a default argument, either parsed or not.
Definition at line 2797 of file Decl.cpp.
References hasUninstantiatedDefaultArg(), hasUnparsedDefaultArg(), and clang::VarDecl::Init.
Referenced by CheckOperatorNewDeclaration(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), and clang::Sema::MergeCXXFunctionDecl().
hasInheritedDefaultArg()
bool clang::ParmVarDecl::hasInheritedDefaultArg () const inline
Definition at line 1753 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by getSourceRange(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitParmVarDecl().
hasUninstantiatedDefaultArg()
bool clang::ParmVarDecl::hasUninstantiatedDefaultArg () const inline
Definition at line 1741 of file Decl.h.
References clang::VarDecl::DAK_Uninstantiated, and clang::VarDecl::ParmVarDeclBits.
Referenced by getDefaultArg(), getUninstantiatedDefaultArg(), hasDefaultArg(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitParmVarDecl().
hasUnparsedDefaultArg()
bool clang::ParmVarDecl::hasUnparsedDefaultArg () const inline
Determines whether this parameter has a default argument that has not yet been parsed.
This will occur during the processing of a C++ class whose member functions have default arguments, e.g.,
class X {
public:
  void f(int x = 17); // x has an unparsed default argument now
}; // x has a regular default argument now
Definition at line 1737 of file Decl.h.
References clang::VarDecl::DAK_Unparsed, and clang::VarDecl::ParmVarDeclBits.
Referenced by getDefaultArg(), hasDefaultArg(), clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), and clang::Sema::SubstParmVarDecl().
isDestroyedInCallee()
bool ParmVarDecl::isDestroyedInCallee () const
Determines whether this parameter is destroyed in the callee function.
Definition at line 2738 of file Decl.cpp.
References clang::Type::getAs(), clang::ValueDecl::getType(), and clang::Decl::hasAttr().
isKNRPromoted()
bool clang::ParmVarDecl::isKNRPromoted () const inline
True if the value passed to this parameter must undergo K&R-style default argument promotion:
C99 6.5.2.2. If the expression that denotes the called function has a type that does not include a prototype, the integer promotions are performed on each argument, and arguments that have type float are promoted to double.
Definition at line 1701 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), and clang::ASTDeclWriter::VisitParmVarDecl().
isObjCMethodParameter()
bool clang::ParmVarDecl::isObjCMethodParameter () const inline
Definition at line 1663 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTDeclWriter::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
setDefaultArg()
void ParmVarDecl::setDefaultArg (Expr * defarg)
Definition at line 2761 of file Decl.cpp.
References clang::VarDecl::DAK_Normal, clang::VarDecl::Init, and clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), and ParmVarDecl().
setHasInheritedDefaultArg()
void clang::ParmVarDecl::setHasInheritedDefaultArg (bool I = true) inline
Definition at line 1757 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), and clang::Sema::SubstParmVarDecl().
setKNRPromoted()
void clang::ParmVarDecl::setKNRPromoted (bool promoted) inline
Definition at line 1704 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl().
setObjCDeclQualifier()
void clang::ParmVarDecl::setObjCDeclQualifier (ObjCDeclQualifier QTVal) inline
Definition at line 1688 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::VisitParmVarDecl().
setObjCMethodScopeInfo()
void clang::ParmVarDecl::setObjCMethodScopeInfo (unsigned parameterIndex) inline
Definition at line 1648 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTDeclReader::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
setOwningFunction()
void clang::ParmVarDecl::setOwningFunction (DeclContext * FD) inline
Sets the function declaration that owns this ParmVarDecl.
Since ParmVarDecls are often created before the FunctionDecls that own them, this routine is required to update the DeclContext appropriately.
Definition at line 1767 of file Decl.h.
References clang::Decl::setDeclContext().
setScopeInfo()
void clang::ParmVarDecl::setScopeInfo (unsigned scopeDepth, unsigned parameterIndex) inline
Definition at line 1653 of file Decl.h.
References clang::VarDecl::ParmVarDeclBits.
Referenced by clang::Sema::ActOnParamDeclarator(), clang::Sema::CreateBuiltin(), clang::Sema::findInheritingConstructor(), InsertOCLBuiltinDeclarationsFromTable(), rewriteBuiltinFunctionDecl(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::ASTDeclReader::VisitParmVarDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
setUninstantiatedDefaultArg()
void ParmVarDecl::setUninstantiatedDefaultArg (Expr * arg)
Definition at line 2786 of file Decl.cpp.
References clang::VarDecl::DAK_Uninstantiated, clang::VarDecl::Init, and clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclReader::VisitParmVarDecl().
setUnparsedDefaultArg()
void clang::ParmVarDecl::setUnparsedDefaultArg () inline
Specify that this parameter has an unparsed default argument.
The argument will be replaced with a real default argument via setDefaultArg when the class definition enclosing the function declaration that owns this default argument is completed.
Definition at line 1749 of file Decl.h.
References clang::VarDecl::DAK_Unparsed, and clang::VarDecl::ParmVarDeclBits.
Referenced by clang::ASTNodeImporter::ImportDefaultArgOfParmVarDecl(), clang::Sema::MergeCXXFunctionDecl(), and clang::Sema::SubstParmVarDecl().
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp