clang: clang::StreamingDiagnostic Class Reference
clang::StreamingDiagnostic Class Reference
The streaming interface shared between DiagnosticBuilder and PartialDiagnostic.
#include "clang/Basic/Diagnostic.h"
Classes
class DiagStorageAllocator
An allocator for DiagnosticStorage objects, which uses a small cache to objects, used to reduce malloc()/free() traffic for partial diagnostics.
Public Member Functions
DiagnosticStorage * getStorage () const
Retrieve storage for this particular diagnostic.
void freeStorage ()
void freeStorageSlow ()
void AddTaggedVal (intptr_t V, DiagnosticsEngine::ArgumentKind Kind) const
void AddString (StringRef V) const
void AddSourceRange (const CharSourceRange &R) const
void AddFixItHint (const FixItHint &Hint) const
operator bool () const
Conversion of StreamingDiagnostic to bool always returns true.
Protected Member Functions
StreamingDiagnostic ()=default
StreamingDiagnostic (DiagnosticStorage *Storage)
Construct with an external storage not owned by itself.
StreamingDiagnostic (DiagStorageAllocator &Alloc)
Construct with a storage allocator which will manage the storage.
StreamingDiagnostic (const StreamingDiagnostic &Diag)=default
StreamingDiagnostic (StreamingDiagnostic &&Diag)=default
~StreamingDiagnostic ()
Protected Attributes
DiagnosticStorage * DiagStorage = nullptr
DiagStorageAllocator * Allocator = nullptr
Allocator used to allocate storage for this diagnostic.
Detailed Description
The streaming interface shared between DiagnosticBuilder and PartialDiagnostic.
This class is not intended to be constructed directly but only as base class of DiagnosticBuilder and PartialDiagnostic builder.
Any new type of argument accepted by DiagnosticBuilder and PartialDiagnostic should be implemented as a '<<' operator of StreamingDiagnostic, e.g.
const StreamingDiagnostic& operator<<(const StreamingDiagnostic&, NewArgType);
Definition at line 1066 of file Diagnostic.h.
Constructor & Destructor Documentation
StreamingDiagnostic() [1/5]
clang::StreamingDiagnostic::StreamingDiagnostic () protected default
StreamingDiagnostic() [2/5]
clang::StreamingDiagnostic::StreamingDiagnostic (DiagnosticStorage * Storage) inline explicit protected
Construct with an external storage not owned by itself.
The allocator is a null pointer in this case.
Definition at line 1192 of file Diagnostic.h.
StreamingDiagnostic() [3/5]
clang::StreamingDiagnostic::StreamingDiagnostic (DiagStorageAllocator & Alloc) inline explicit protected
Construct with a storage allocator which will manage the storage.
The allocator is not a null pointer in this case.
Definition at line 1197 of file Diagnostic.h.
StreamingDiagnostic() [4/5]
clang::StreamingDiagnostic::StreamingDiagnostic (const StreamingDiagnostic & Diag) protected default
StreamingDiagnostic() [5/5]
clang::StreamingDiagnostic::StreamingDiagnostic (StreamingDiagnostic && Diag) protected default
~StreamingDiagnostic()
clang::StreamingDiagnostic::~StreamingDiagnostic () inline protected
Definition at line 1203 of file Diagnostic.h.
References freeStorage().
Member Function Documentation
AddFixItHint()
void clang::StreamingDiagnostic::AddFixItHint (const FixItHint & Hint) const inline
Definition at line 1168 of file Diagnostic.h.
References DiagStorage, clang::DiagnosticStorage::FixItHints, getStorage(), and clang::FixItHint::isNull().
Referenced by clang::PartialDiagnostic::Emit(), clang::operator<<(), clang::operator<<(), and clang::PartialDiagnostic::PartialDiagnostic().
AddSourceRange()
void clang::StreamingDiagnostic::AddSourceRange (const CharSourceRange & R) const inline
Definition at line 1161 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagRanges, DiagStorage, and getStorage().
Referenced by clang::PartialDiagnostic::Emit(), clang::operator<<(), clang::operator<<(), clang::operator<<(), and clang::PartialDiagnostic::PartialDiagnostic().
AddString()
void clang::StreamingDiagnostic::AddString (StringRef V) const inline
Definition at line 1150 of file Diagnostic.h.
References clang::DiagnosticsEngine::ak_std_string, clang::DiagnosticStorage::DiagArgumentsKind, clang::DiagnosticStorage::DiagArgumentsStr, DiagStorage, getStorage(), clang::DiagnosticStorage::MaxArguments, clang::DiagnosticStorage::NumDiagArgs, and V.
Referenced by BitcodeInlineAsmDiagHandler(), clang::BackendConsumer::DiagnosticHandlerImpl(), clang::PartialDiagnostic::Emit(), clang::BackendConsumer::InlineAsmDiagHandler(), clang::BackendConsumer::InlineAsmDiagHandler2(), clang::operator<<(), clang::operator<<(), and clang::operator<<().
AddTaggedVal()
void clang::StreamingDiagnostic::AddTaggedVal (intptr_t V, DiagnosticsEngine::ArgumentKind Kind) const inline
Definition at line 1140 of file Diagnostic.h.
References clang::DiagnosticStorage::DiagArgumentsKind, clang::DiagnosticStorage::DiagArgumentsVal, DiagStorage, getStorage(), clang::DiagnosticStorage::MaxArguments, clang::DiagnosticStorage::NumDiagArgs, and V.
Referenced by clang::AcquireCapabilityAttr::AcquireCapabilityAttr(), clang::PartialDiagnostic::Emit(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), clang::operator<<(), and clang::operator<<().
freeStorage()
void clang::StreamingDiagnostic::freeStorage () inline
Definition at line 1120 of file Diagnostic.h.
References DiagStorage, and freeStorageSlow().
Referenced by clang::PartialDiagnostic::operator=(), clang::PartialDiagnostic::operator=(), clang::PartialDiagnostic::Reset(), and ~StreamingDiagnostic().
freeStorageSlow()
void clang::StreamingDiagnostic::freeStorageSlow () inline
Definition at line 1133 of file Diagnostic.h.
References Allocator, clang::StreamingDiagnostic::DiagStorageAllocator::Deallocate(), and DiagStorage.
Referenced by freeStorage().
getStorage()
DiagnosticStorage * clang::StreamingDiagnostic::getStorage () const inline
Retrieve storage for this particular diagnostic.
Definition at line 1111 of file Diagnostic.h.
References clang::StreamingDiagnostic::DiagStorageAllocator::Allocate(), Allocator, and DiagStorage.
Referenced by AddFixItHint(), AddSourceRange(), AddString(), AddTaggedVal(), and clang::PartialDiagnostic::operator=().
operator bool()
clang::StreamingDiagnostic::operator bool () const inline
Conversion of StreamingDiagnostic to bool always returns true.
This allows is to be used in boolean error contexts (where true is used to indicate that an error has occurred), like:
return Diag(...);
Definition at line 1185 of file Diagnostic.h.
Member Data Documentation
Allocator
DiagStorageAllocator* clang::StreamingDiagnostic::Allocator = nullptr protected
Allocator used to allocate storage for this diagnostic.
Definition at line 1107 of file Diagnostic.h.
Referenced by freeStorageSlow(), getStorage(), clang::PartialDiagnostic::operator=(), clang::PartialDiagnostic::PartialDiagnostic(), clang::PartialDiagnostic::PartialDiagnostic(), clang::PartialDiagnostic::PartialDiagnostic(), clang::PartialDiagnostic::PartialDiagnostic(), and clang::PartialDiagnostic::swap().
DiagStorage
DiagnosticStorage* clang::StreamingDiagnostic::DiagStorage = nullptr mutable protected
Definition at line 1104 of file Diagnostic.h.
Referenced by AddFixItHint(), AddSourceRange(), AddString(), AddTaggedVal(), clang::DiagnosticBuilder::DiagnosticBuilder(), clang::PartialDiagnostic::Emit(), freeStorage(), freeStorageSlow(), getStorage(), clang::PartialDiagnostic::getStringArg(), clang::PartialDiagnostic::hasStorage(), clang::PartialDiagnostic::operator=(), clang::PartialDiagnostic::operator=(), clang::PartialDiagnostic::PartialDiagnostic(), clang::PartialDiagnostic::PartialDiagnostic(), clang::PartialDiagnostic::PartialDiagnostic(), and clang::PartialDiagnostic::swap().
The documentation for this class was generated from the following file:
include/clang/Basic/Diagnostic.h