clang: clang::CapturedStmt::Capture Class Reference
clang::CapturedStmt::Capture Class Reference
Describes the capture of either a variable, or 'this', or variable-length array type.
#include "clang/AST/Stmt.h"
Public Member Functions
Capture (SourceLocation Loc, VariableCaptureKind Kind, VarDecl *Var=nullptr)
Create a new capture.
VariableCaptureKind getCaptureKind () const
Determine the kind of capture.
SourceLocation getLocation () const
Retrieve the source location at which the variable or 'this' was first used.
bool capturesThis () const
Determine whether this capture handles the C++ 'this' pointer.
bool capturesVariable () const
Determine whether this capture handles a variable (by reference).
bool capturesVariableByCopy () const
Determine whether this capture handles a variable by copy.
bool capturesVariableArrayType () const
Determine whether this capture handles a variable-length array type.
VarDecl * getCapturedVar () const
Retrieve the declaration of the variable being captured.
Friends
class ASTStmtReader
Detailed Description
Describes the capture of either a variable, or 'this', or variable-length array type.
Definition at line 3480 of file Stmt.h.
Constructor & Destructor Documentation
Capture()
CapturedStmt::Capture::Capture (SourceLocation Loc, VariableCaptureKind Kind, VarDecl * Var = nullptr)
Create a new capture.
Parameters
Loc The source location associated with this capture.
Kind The kind of capture (this, ByRef, ...).
Var The variable being captured, or null if capturing this.
Definition at line 1257 of file Stmt.cpp.
References clang::Type::castAs(), clang::ReferenceType::getPointeeType(), clang::ValueDecl::getType(), clang::Type::isReferenceType(), clang::Type::isScalarType(), clang::CapturedStmt::VCK_ByCopy, clang::CapturedStmt::VCK_ByRef, clang::CapturedStmt::VCK_This, and clang::CapturedStmt::VCK_VLAType.
Member Function Documentation
capturesThis()
bool clang::CapturedStmt::Capture::capturesThis () const inline
Determine whether this capture handles the C++ 'this' pointer.
Definition at line 3505 of file Stmt.h.
References getCaptureKind(), and clang::CapturedStmt::VCK_This.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
capturesVariable()
bool clang::CapturedStmt::Capture::capturesVariable () const inline
Determine whether this capture handles a variable (by reference).
Definition at line 3508 of file Stmt.h.
References getCaptureKind(), and clang::CapturedStmt::VCK_ByRef.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
capturesVariableArrayType()
bool clang::CapturedStmt::Capture::capturesVariableArrayType () const inline
Determine whether this capture handles a variable-length array type.
Definition at line 3517 of file Stmt.h.
References getCaptureKind(), and clang::CapturedStmt::VCK_VLAType.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
capturesVariableByCopy()
bool clang::CapturedStmt::Capture::capturesVariableByCopy () const inline
Determine whether this capture handles a variable by copy.
Definition at line 3511 of file Stmt.h.
References getCaptureKind(), and clang::CapturedStmt::VCK_ByCopy.
getCapturedVar()
VarDecl * CapturedStmt::Capture::getCapturedVar () const
Retrieve the declaration of the variable being captured.
This operation is only valid if this capture captures a variable.
Definition at line 1289 of file Stmt.cpp.
References clang::CapturedStmt::capturesVariable().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall().
getCaptureKind()
CapturedStmt::VariableCaptureKind CapturedStmt::Capture::getCaptureKind () const
Determine the kind of capture.
Definition at line 1285 of file Stmt.cpp.
Referenced by capturesThis(), capturesVariable(), capturesVariableArrayType(), and capturesVariableByCopy().
getLocation()
SourceLocation clang::CapturedStmt::Capture::getLocation () const inline
Retrieve the source location at which the variable or 'this' was first used.
Definition at line 3502 of file Stmt.h.
Friends And Related Symbol Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 3485 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp