clang: clang::SubstTemplateTemplateParmPackStorage Class Reference
clang::SubstTemplateTemplateParmPackStorage Class Reference
A structure for storing an already-substituted template template parameter pack.
#include "clang/AST/TemplateName.h"
Public Member Functions
SubstTemplateTemplateParmPackStorage (TemplateTemplateParmDecl *Parameter, unsigned Size, const TemplateArgument *Arguments)
TemplateTemplateParmDecl * getParameterPack () const
Retrieve the template template parameter pack being substituted.
TemplateArgument getArgumentPack () const
Retrieve the template template argument pack with which this parameter was substituted.
void Profile (llvm::FoldingSetNodeID &ID, ASTContext &Context)
Public Member Functions inherited from clang::UncommonTemplateNameStorage
unsigned size () const
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, ASTContext &Context, TemplateTemplateParmDecl *Parameter, const TemplateArgument &ArgPack)
Additional Inherited Members
Public Attributes inherited from clang::UncommonTemplateNameStorage
Protected Types inherited from clang::UncommonTemplateNameStorage
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions inherited from clang::UncommonTemplateNameStorage
UncommonTemplateNameStorage (Kind kind, unsigned size)
Protected Attributes inherited from clang::UncommonTemplateNameStorage
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
A structure for storing an already-substituted template template parameter pack.
This kind of template names occurs when the parameter pack has been provided with a template template argument pack in a context where its enclosing pack expansion could not be fully expanded.
Definition at line 135 of file TemplateName.h.
Constructor & Destructor Documentation
SubstTemplateTemplateParmPackStorage()
clang::SubstTemplateTemplateParmPackStorage::SubstTemplateTemplateParmPackStorage (TemplateTemplateParmDecl * Parameter, unsigned Size, const TemplateArgument * Arguments) inline
Definition at line 142 of file TemplateName.h.
References clang::Parameter.
Member Function Documentation
getArgumentPack()
TemplateArgument SubstTemplateTemplateParmPackStorage::getArgumentPack () const
Retrieve the template template argument pack with which this parameter was substituted.
Definition at line 36 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::size().
Referenced by clang::ASTContext::getCanonicalTemplateName(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and Profile().
getParameterPack()
TemplateTemplateParmDecl * clang::SubstTemplateTemplateParmPackStorage::getParameterPack () const inline
Retrieve the template template parameter pack being substituted.
Definition at line 149 of file TemplateName.h.
References clang::Parameter.
Referenced by clang::ASTContext::getCanonicalTemplateName(), clang::ASTContext::getNameForTemplate(), clang::ASTImporter::Import(), and IsStructurallyEquivalent().
Profile() [1/2]
void SubstTemplateTemplateParmPackStorage::Profile (llvm::FoldingSetNodeID & ID, ASTContext & Context)
Definition at line 51 of file TemplateName.cpp.
References getArgumentPack(), and Profile().
Referenced by clang::ASTContext::getSubstTemplateTemplateParmPack(), and Profile().
Profile() [2/2]
void SubstTemplateTemplateParmPackStorage::Profile (llvm::FoldingSetNodeID & ID, ASTContext & Context, TemplateTemplateParmDecl * Parameter, const TemplateArgument & ArgPack) static
Definition at line 56 of file TemplateName.cpp.
References clang::Parameter, and clang::TemplateArgument::Profile().
The documentation for this class was generated from the following files:
include/clang/AST/TemplateName.h
lib/AST/TemplateName.cpp