clang: clang::comments::ParamCommandComment Class Reference
clang::comments::ParamCommandComment Class Reference
Doxygen \param command.
#include "clang/AST/Comment.h"
Public Types
enum : unsigned { InvalidParamIndex = ~0U , VarArgParamIndex = ~0U - 1U }
enum PassDirection { In , Out , InOut }
Public Types inherited from clang::comments::Comment
enum CommentKind { NoCommentKind = 0 }
typedef Comment *const * child_iterator
Public Member Functions
ParamCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
PassDirection getDirection () const LLVM_READONLY
bool isDirectionExplicit () const LLVM_READONLY
void setDirection (PassDirection Direction, bool Explicit)
bool hasParamName () const
StringRef getParamName (const FullComment *FC) const
StringRef getParamNameAsWritten () const
SourceRange getParamNameRange () const
bool isParamIndexValid () const LLVM_READONLY
bool isVarArgParam () const LLVM_READONLY
void setIsVarArgParam ()
unsigned getParamIndex () const LLVM_READONLY
void setParamIndex (unsigned Index)
Public Member Functions inherited from clang::comments::BlockCommandComment
BlockCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
child_iterator child_begin () const
child_iterator child_end () const
unsigned getCommandID () const
StringRef getCommandName (const CommandTraits &Traits) const
SourceLocation getCommandNameBeginLoc () const
SourceRange getCommandNameRange (const CommandTraits &Traits) const
unsigned getNumArgs () const
StringRef getArgText (unsigned Idx) const
SourceRange getArgRange (unsigned Idx) const
void setArgs (ArrayRef< Argument > A)
ParagraphComment * getParagraph () const LLVM_READONLY
bool hasNonWhitespaceParagraph () const
void setParagraph (ParagraphComment *PC)
CommandMarkerKind getCommandMarker () const LLVM_READONLY
Public Member Functions inherited from clang::comments::Comment
Comment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
CommentKind getCommentKind () const
const char * getCommentKindName () const
void dump () const
void dumpColor () const
void dump (raw_ostream &OS, const ASTContext &Context) const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const LLVM_READONLY
child_iterator child_begin () const
child_iterator child_end () const
unsigned child_count () const
Static Public Member Functions
static bool classof (const Comment *C)
static const char * getDirectionAsString (PassDirection D)
Static Public Member Functions inherited from clang::comments::BlockCommandComment
static bool classof (const Comment *C)
Static Public Member Functions inherited from clang::comments::BlockContentComment
static bool classof (const Comment *C)
Additional Inherited Members
Public Attributes inherited from clang::comments::Comment
Protected Types inherited from clang::comments::Comment
enum { NumCommentBits = 8 }
enum { NumInlineContentCommentBits = NumCommentBits + 1 }
enum { NumTextCommentBits = NumInlineContentCommentBits + 2 }
enum { NumInlineCommandCommentBits }
enum { NumHTMLTagCommentBits = NumInlineContentCommentBits + 1 }
enum { NumHTMLStartTagCommentBits = NumHTMLTagCommentBits + 1 }
enum { NumParagraphCommentBits = NumCommentBits + 2 }
enum { NumBlockCommandCommentBits }
enum { NumParamCommandCommentBits = NumBlockCommandCommentBits + 3 }
Protected Member Functions inherited from clang::comments::BlockCommandComment
BlockCommandComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker)
Protected Member Functions inherited from clang::comments::BlockContentComment
BlockContentComment (CommentKind K, SourceLocation LocBegin, SourceLocation LocEnd)
Protected Member Functions inherited from clang::comments::Comment
void setSourceRange (SourceRange SR)
void setLocation (SourceLocation L)
Protected Attributes inherited from clang::comments::BlockCommandComment
ArrayRef< Argument > Args
Word-like arguments.
ParagraphComment * Paragraph
Paragraph argument.
Protected Attributes inherited from clang::comments::Comment
SourceLocation Loc
Preferred location to show caret.
SourceRange Range
Source range of this AST node.
union {
CommentBitfields CommentBits
InlineContentCommentBitfields InlineContentCommentBits
TextCommentBitfields TextCommentBits
InlineCommandCommentBitfields InlineCommandCommentBits
HTMLTagCommentBitfields HTMLTagCommentBits
HTMLStartTagCommentBitfields HTMLStartTagCommentBits
ParagraphCommentBitfields ParagraphCommentBits
BlockCommandCommentBitfields BlockCommandCommentBits
ParamCommandCommentBitfields ParamCommandCommentBits
};
Detailed Description
Doxygen \param command.
Definition at line 711 of file Comment.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
InvalidParamIndex
VarArgParamIndex
Definition at line 717 of file Comment.h.
PassDirection
enum clang::comments::ParamCommandComment::PassDirection
Enumerator
In
Out
InOut
Definition at line 737 of file Comment.h.
Constructor & Destructor Documentation
ParamCommandComment()
clang::comments::ParamCommandComment::ParamCommandComment (SourceLocation LocBegin, SourceLocation LocEnd, unsigned CommandID, CommandMarkerKind CommandMarker) inline
Definition at line 722 of file Comment.h.
References In, and clang::comments::Comment::ParamCommandCommentBits.
Member Function Documentation
classof()
static bool clang::comments::ParamCommandComment::classof (const Comment * C) inline static
Definition at line 733 of file Comment.h.
References clang::C.
getDirection()
PassDirection clang::comments::ParamCommandComment::getDirection () const inline
Definition at line 745 of file Comment.h.
References clang::comments::Comment::ParamCommandCommentBits.
getDirectionAsString()
const char * clang::comments::ParamCommandComment::getDirectionAsString (PassDirection D) static
Definition at line 192 of file Comment.cpp.
References In, InOut, and Out.
Referenced by clang::comments::Sema::actOnParamCommandDirectionArg(), and clang::TextNodeDumper::visitParamCommandComment().
getParamIndex()
unsigned clang::comments::ParamCommandComment::getParamIndex () const inline
Definition at line 785 of file Comment.h.
References isParamIndexValid(), and isVarArgParam().
Referenced by getParamName().
getParamName()
StringRef clang::comments::ParamCommandComment::getParamName (const FullComment * FC) const
Definition at line 371 of file Comment.cpp.
References clang::comments::FullComment::getDeclInfo(), getParamIndex(), isParamIndexValid(), isVarArgParam(), and clang::comments::DeclInfo::ParamVars.
getParamNameAsWritten()
StringRef clang::comments::ParamCommandComment::getParamNameAsWritten () const inline
Definition at line 764 of file Comment.h.
References clang::comments::BlockCommandComment::Args.
Referenced by clang::comments::Sema::resolveParamCommandIndexes().
getParamNameRange()
SourceRange clang::comments::ParamCommandComment::getParamNameRange () const inline
Definition at line 768 of file Comment.h.
References clang::comments::BlockCommandComment::Args.
Referenced by clang::comments::Sema::resolveParamCommandIndexes().
hasParamName()
bool clang::comments::ParamCommandComment::hasParamName () const inline
Definition at line 758 of file Comment.h.
References clang::comments::BlockCommandComment::getNumArgs().
Referenced by clang::comments::Sema::resolveParamCommandIndexes().
isDirectionExplicit()
bool clang::comments::ParamCommandComment::isDirectionExplicit () const inline
Definition at line 749 of file Comment.h.
References clang::comments::Comment::ParamCommandCommentBits.
Referenced by clang::comments::Sema::actOnParamCommandParamNameArg().
isParamIndexValid()
bool clang::comments::ParamCommandComment::isParamIndexValid () const inline
Definition at line 772 of file Comment.h.
References InvalidParamIndex.
Referenced by getParamIndex(), getParamName(), setIsVarArgParam(), and setParamIndex().
isVarArgParam()
bool clang::comments::ParamCommandComment::isVarArgParam () const inline
Definition at line 776 of file Comment.h.
References VarArgParamIndex.
Referenced by getParamIndex(), getParamName(), and setParamIndex().
setDirection()
void clang::comments::ParamCommandComment::setDirection (PassDirection Direction, bool Explicit) inline
Definition at line 753 of file Comment.h.
References clang::comments::Comment::ParamCommandCommentBits.
Referenced by clang::comments::Sema::actOnParamCommandDirectionArg(), and clang::comments::Sema::actOnParamCommandParamNameArg().
setIsVarArgParam()
void clang::comments::ParamCommandComment::setIsVarArgParam () inline
Definition at line 780 of file Comment.h.
References isParamIndexValid(), and VarArgParamIndex.
Referenced by clang::comments::Sema::resolveParamCommandIndexes().
setParamIndex()
void clang::comments::ParamCommandComment::setParamIndex (unsigned Index) inline
Definition at line 791 of file Comment.h.
References isParamIndexValid(), and isVarArgParam().
Referenced by clang::comments::Sema::resolveParamCommandIndexes().
The documentation for this class was generated from the following files:
include/clang/AST/Comment.h
lib/AST/Comment.cpp