clang: clang::ento::FindLastStoreBRVisitor Class Reference
clang::ento::FindLastStoreBRVisitor Class Reference final
Finds last store into the given region, which is different from a given symbolic value.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Public Member Functions
FindLastStoreBRVisitor (KnownSVal V, const MemRegion *R, bool InEnableNullFPSuppression, TrackingKind TKind, const StackFrameContext *OriginSFC=nullptr)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
virtual PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR)
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Additional Inherited Members
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
Finds last store into the given region, which is different from a given symbolic value.
Definition at line 125 of file BugReporterVisitors.h.
Constructor & Destructor Documentation
FindLastStoreBRVisitor()
clang::ento::FindLastStoreBRVisitor::FindLastStoreBRVisitor (KnownSVal V, const MemRegion * R, bool InEnableNullFPSuppression, TrackingKind TKind, const StackFrameContext * OriginSFC = nullptr) inline
Parameters
V We're searching for the store where R received this value.
R The region we're tracking.
TKind May limit the amount of notes added to the bug report.
OriginSFC Only adds notes when the last store happened in a different stackframe to this one. Disregarded if the tracking kind is thorough. This is useful, because for non-tracked regions, notes about changes to its value in a nested stackframe could be pruned, and this visitor can prevent that without polluting the bugpath too much.
Definition at line 149 of file BugReporterVisitors.h.
References V.
Member Function Documentation
Profile()
void FindLastStoreBRVisitor::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 1204 of file BugReporterVisitors.cpp.
References V.
VisitNode()
PathDiagnosticPieceRef FindLastStoreBRVisitor::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 1360 of file BugReporterVisitors.cpp.
References clang::ento::PathSensitiveBugReport::addVisitor(), clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::MemRegion::canPrintPretty(), clang::cast(), clang::ento::bugreporter::Condition, clang::ento::PathDiagnosticLocation::create(), clang::ProgramPoint::getAs(), clang::ento::CallEventManager::getCaller(), clang::ento::ProgramStateManager::getCallEventManager(), clang::ento::ExplodedNode::getFirstPred(), clang::ento::ExplodedNode::getLocation(), clang::ento::ExplodedNode::getLocationAs(), clang::ento::BugReporterContext::getSourceManager(), clang::ento::ExplodedNode::getStackFrame(), clang::ento::ExplodedNode::getState(), clang::ento::BugReporterContext::getStateManager(), clang::ento::ExplodedNode::getSVal(), hasVisibleUpdate(), clang::Expr::IgnoreParenCasts(), isInitializationOfVar(), clang::LocationContext::isParentOf(), clang::ento::PathDiagnosticLocation::isValid(), clang::SourceLocation::isValid(), P, showBRDefaultDiagnostics(), showBRDiagnostics(), showBRParamDiagnostics(), clang::ento::bugreporter::trackExpressionValue(), V, and WillBeUsedForACondition.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp