clang: clang::ASTNodeTraverser< Derived, NodeDelegateType > Class Template Reference
clang::ASTNodeTraverser< Derived, NodeDelegateType > Class Template Reference
ASTNodeTraverser traverses the Clang AST for dumping purposes.
#include "clang/AST/ASTNodeTraverser.h"
Public Member Functions
void setDeserialize (bool D)
bool getDeserialize () const
void SetTraversalKind (TraversalKind TK)
TraversalKind GetTraversalKind () const
void Visit (const Decl *D)
void Visit (const Stmt *Node, StringRef Label={})
void Visit (QualType T)
void Visit (const Type *T)
void Visit (const Attr *A)
void Visit (const CXXCtorInitializer *Init)
void Visit (const TemplateArgument &A, SourceRange R={}, const Decl *From=nullptr, const char *Label=nullptr)
void Visit (const BlockDecl::Capture &C)
void Visit (const OMPClause *C)
void Visit (const GenericSelectionExpr::ConstAssociation &A)
void Visit (const APValue &Value, QualType Ty)
void Visit (const comments::Comment *C, const comments::FullComment *FC)
void Visit (const DynTypedNode &N)
void dumpDeclContext (const DeclContext *DC)
void dumpTemplateParameters (const TemplateParameterList *TPL)
void dumpASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo *TALI)
void dumpTemplateArgumentLoc (const TemplateArgumentLoc &A, const Decl *From=nullptr, const char *Label=nullptr)
void dumpTemplateArgumentList (const TemplateArgumentList &TAL)
void dumpObjCTypeParamList (const ObjCTypeParamList *typeParams)
void VisitComplexType (const ComplexType *T)
void VisitLocInfoType (const LocInfoType *T)
void VisitPointerType (const PointerType *T)
void VisitBlockPointerType (const BlockPointerType *T)
void VisitReferenceType (const ReferenceType *T)
void VisitMemberPointerType (const MemberPointerType *T)
void VisitArrayType (const ArrayType *T)
void VisitVariableArrayType (const VariableArrayType *T)
void VisitDependentSizedArrayType (const DependentSizedArrayType *T)
void VisitDependentSizedExtVectorType (const DependentSizedExtVectorType *T)
void VisitVectorType (const VectorType *T)
void VisitFunctionType (const FunctionType *T)
void VisitFunctionProtoType (const FunctionProtoType *T)
void VisitTypeOfExprType (const TypeOfExprType *T)
void VisitDecltypeType (const DecltypeType *T)
void VisitUnaryTransformType (const UnaryTransformType *T)
void VisitAttributedType (const AttributedType *T)
void VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType *T)
void VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType *T)
void VisitTemplateSpecializationType (const TemplateSpecializationType *T)
void VisitObjCObjectPointerType (const ObjCObjectPointerType *T)
void VisitAtomicType (const AtomicType *T)
void VisitPipeType (const PipeType *T)
void VisitAdjustedType (const AdjustedType *T)
void VisitPackExpansionType (const PackExpansionType *T)
void VisitTypedefDecl (const TypedefDecl *D)
void VisitEnumConstantDecl (const EnumConstantDecl *D)
void VisitFunctionDecl (const FunctionDecl *D)
void VisitFieldDecl (const FieldDecl *D)
void VisitVarDecl (const VarDecl *D)
void VisitDecompositionDecl (const DecompositionDecl *D)
void VisitBindingDecl (const BindingDecl *D)
void VisitFileScopeAsmDecl (const FileScopeAsmDecl *D)
void VisitCapturedDecl (const CapturedDecl *D)
void VisitOMPThreadPrivateDecl (const OMPThreadPrivateDecl *D)
void VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl *D)
void VisitOMPDeclareMapperDecl (const OMPDeclareMapperDecl *D)
void VisitOMPCapturedExprDecl (const OMPCapturedExprDecl *D)
void VisitOMPAllocateDecl (const OMPAllocateDecl *D)
template<typename SpecializationDecl >
void dumpTemplateDeclSpecialization (const SpecializationDecl *D)
template<typename TemplateDecl >
void dumpTemplateDecl (const TemplateDecl *D)
void VisitTypeAliasDecl (const TypeAliasDecl *D)
void VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl *D)
void VisitStaticAssertDecl (const StaticAssertDecl *D)
void VisitFunctionTemplateDecl (const FunctionTemplateDecl *D)
void VisitClassTemplateDecl (const ClassTemplateDecl *D)
void VisitClassTemplateSpecializationDecl (const ClassTemplateSpecializationDecl *D)
void VisitClassTemplatePartialSpecializationDecl (const ClassTemplatePartialSpecializationDecl *D)
void VisitClassScopeFunctionSpecializationDecl (const ClassScopeFunctionSpecializationDecl *D)
void VisitVarTemplateDecl (const VarTemplateDecl *D)
void VisitBuiltinTemplateDecl (const BuiltinTemplateDecl *D)
void VisitVarTemplateSpecializationDecl (const VarTemplateSpecializationDecl *D)
void VisitVarTemplatePartialSpecializationDecl (const VarTemplatePartialSpecializationDecl *D)
void VisitTemplateTypeParmDecl (const TemplateTypeParmDecl *D)
void VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl *D)
void VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl *D)
void VisitConceptDecl (const ConceptDecl *D)
void VisitConceptSpecializationExpr (const ConceptSpecializationExpr *CSE)
void VisitUsingShadowDecl (const UsingShadowDecl *D)
void VisitFriendDecl (const FriendDecl *D)
void VisitObjCMethodDecl (const ObjCMethodDecl *D)
void VisitObjCCategoryDecl (const ObjCCategoryDecl *D)
void VisitObjCInterfaceDecl (const ObjCInterfaceDecl *D)
void VisitObjCImplementationDecl (const ObjCImplementationDecl *D)
void VisitBlockDecl (const BlockDecl *D)
void VisitDeclStmt (const DeclStmt *Node)
void VisitAttributedStmt (const AttributedStmt *Node)
void VisitCXXCatchStmt (const CXXCatchStmt *Node)
void VisitCapturedStmt (const CapturedStmt *Node)
void VisitOMPExecutableDirective (const OMPExecutableDirective *Node)
void VisitInitListExpr (const InitListExpr *ILE)
void VisitBlockExpr (const BlockExpr *Node)
void VisitOpaqueValueExpr (const OpaqueValueExpr *Node)
void VisitGenericSelectionExpr (const GenericSelectionExpr *E)
void VisitLambdaExpr (const LambdaExpr *Node)
void VisitSizeOfPackExpr (const SizeOfPackExpr *Node)
void VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr *E)
void VisitSubstNonTypeTemplateParmPackExpr (const SubstNonTypeTemplateParmPackExpr *E)
void VisitObjCAtCatchStmt (const ObjCAtCatchStmt *Node)
void VisitCXXForRangeStmt (const CXXForRangeStmt *Node)
void VisitCallExpr (const CallExpr *Node)
void VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator *Node)
void VisitExpressionTemplateArgument (const TemplateArgument &TA)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
void VisitAMDGPUFlatWorkGroupSizeAttr (const AMDGPUFlatWorkGroupSizeAttr *A)
void VisitAMDGPUWavesPerEUAttr (const AMDGPUWavesPerEUAttr *A)
void VisitAcquireCapabilityAttr (const AcquireCapabilityAttr *A)
void VisitAcquiredAfterAttr (const AcquiredAfterAttr *A)
void VisitAcquiredBeforeAttr (const AcquiredBeforeAttr *A)
void VisitAlignValueAttr (const AlignValueAttr *A)
void VisitAlignedAttr (const AlignedAttr *A)
void VisitAnnotateAttr (const AnnotateAttr *A)
void VisitAssertCapabilityAttr (const AssertCapabilityAttr *A)
void VisitAssertExclusiveLockAttr (const AssertExclusiveLockAttr *A)
void VisitAssertSharedLockAttr (const AssertSharedLockAttr *A)
void VisitAssumeAlignedAttr (const AssumeAlignedAttr *A)
void VisitCUDALaunchBoundsAttr (const CUDALaunchBoundsAttr *A)
void VisitDiagnoseIfAttr (const DiagnoseIfAttr *A)
void VisitEnableIfAttr (const EnableIfAttr *A)
void VisitExclusiveTrylockFunctionAttr (const ExclusiveTrylockFunctionAttr *A)
void VisitGuardedByAttr (const GuardedByAttr *A)
void VisitLockReturnedAttr (const LockReturnedAttr *A)
void VisitLocksExcludedAttr (const LocksExcludedAttr *A)
void VisitLoopHintAttr (const LoopHintAttr *A)
void VisitOMPAllocateDeclAttr (const OMPAllocateDeclAttr *A)
void VisitOMPDeclareSimdDeclAttr (const OMPDeclareSimdDeclAttr *A)
void VisitOMPDeclareVariantAttr (const OMPDeclareVariantAttr *A)
void VisitOMPReferencedVarAttr (const OMPReferencedVarAttr *A)
void VisitPtGuardedByAttr (const PtGuardedByAttr *A)
void VisitReleaseCapabilityAttr (const ReleaseCapabilityAttr *A)
void VisitRequiresCapabilityAttr (const RequiresCapabilityAttr *A)
void VisitSharedTrylockFunctionAttr (const SharedTrylockFunctionAttr *A)
void VisitTryAcquireCapabilityAttr (const TryAcquireCapabilityAttr *A)
Public Member Functions inherited from clang::declvisitor::Base< llvm::make_const_ptr, Derived, void >
void Visit (PTR(Decl) D)
void VisitDecl (PTR(Decl) D)
Public Member Functions inherited from clang::StmtVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Public Member Functions inherited from clang::comments::CommentVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
void visit (PTR(Comment) C, ParamTys... P)
void visitComment (PTR(Comment) C, ParamTys... P)
Public Member Functions inherited from clang::TypeVisitor< Derived >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::attrvisitor::Base< llvm::make_const_ptr, Derived, void, ParamTys... >
void Visit (PTR(Attr) A)
void VisitAttr (PTR(Attr))
Public Member Functions inherited from clang::templateargumentvisitor::Base< llvm::make_const_ref, Derived, void, ParamTys... >
void Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
void VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
ParamTys P
Detailed Description
template<typename Derived, typename NodeDelegateType>
class clang::ASTNodeTraverser< Derived, NodeDelegateType >
ASTNodeTraverser traverses the Clang AST for dumping purposes.
The Derived::doGetNodeDelegate() method is required to be an accessible member which returns a reference of type NodeDelegateType & which implements the following interface:
struct { template <typename Fn> void AddChild(Fn DoAddChild); template <typename Fn> void AddChild(StringRef Label, Fn DoAddChild);
void Visit(const comments::Comment *C, const comments::FullComment *FC); void Visit(const Attr *A); void Visit(const TemplateArgument &TA, SourceRange R = {}, const Decl *From = nullptr, StringRef Label = {}); void Visit(const Stmt *Node); void Visit(const Type *T); void Visit(QualType T); void Visit(const Decl *D); void Visit(const CXXCtorInitializer *Init); void Visit(const OMPClause *C); void Visit(const BlockDecl::Capture &C); void Visit(const GenericSelectionExpr::ConstAssociation &A); void Visit(const APValue &Value, QualType Ty); };
Definition at line 60 of file ASTNodeTraverser.h.
Member Function Documentation
dumpASTTemplateArgumentListInfo()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo * TALI) inline
Definition at line 289 of file ASTNodeTraverser.h.
References clang::ASTTemplateArgumentListInfo::arguments(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassScopeFunctionSpecializationDecl().
dumpDeclContext()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpDeclContext (const DeclContext * DC) inline
Definition at line 269 of file ASTNodeTraverser.h.
References clang::DeclContext::decls(), clang::DeclContext::noload_decls(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCMethodDecl().
dumpObjCTypeParamList()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpObjCTypeParamList (const ObjCTypeParamList * typeParams) inline
Definition at line 308 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCCategoryDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCInterfaceDecl().
dumpTemplateArgumentList()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList (const TemplateArgumentList & TAL) inline
Definition at line 303 of file ASTNodeTraverser.h.
References clang::TemplateArgumentList::size(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateSpecializationDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateSpecializationDecl().
dumpTemplateArgumentLoc()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc (const TemplateArgumentLoc & A, const Decl * From = nullptr, const char * Label = nullptr) inline
Definition at line 297 of file ASTNodeTraverser.h.
References clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgumentLoc::getSourceRange(), Label, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpASTTemplateArgumentListInfo(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTemplateParmDecl().
dumpTemplateDecl()
template<typename Derived , typename NodeDelegateType > template<typename TemplateDecl > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl (const TemplateDecl * D) inline
Definition at line 498 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDeclSpecialization(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::TemplateDecl::getTemplatedDecl(), clang::TemplateDecl::getTemplateParameters(), clang::TK_AsIs, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionTemplateDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateDecl().
dumpTemplateDeclSpecialization()
template<typename Derived , typename NodeDelegateType > template<typename SpecializationDecl > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDeclSpecialization (const SpecializationDecl * D) inline
Definition at line 479 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl().
dumpTemplateParameters()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters (const TemplateParameterList * TPL) inline
Definition at line 277 of file ASTNodeTraverser.h.
References clang::TemplateParameterList::getRequiresClause(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBuiltinTemplateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplatePartialSpecializationDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTemplateParmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasTemplateDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplatePartialSpecializationDecl().
getDeserialize()
template<typename Derived , typename NodeDelegateType > bool clang::ASTNodeTraverser< Derived, NodeDelegateType >::getDeserialize () const inline
Definition at line 82 of file ASTNodeTraverser.h.
GetTraversalKind()
template<typename Derived , typename NodeDelegateType > TraversalKind clang::ASTNodeTraverser< Derived, NodeDelegateType >::GetTraversalKind () const inline
Definition at line 85 of file ASTNodeTraverser.h.
References Traversal.
setDeserialize()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::setDeserialize (bool D) inline
Definition at line 81 of file ASTNodeTraverser.h.
SetTraversalKind()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::SetTraversalKind (TraversalKind TK) inline
Definition at line 84 of file ASTNodeTraverser.h.
References Traversal.
Visit() [1/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const APValue & Value, QualType Ty) inline
Definition at line 231 of file ASTNodeTraverser.h.
Visit() [2/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Attr * A) inline
Definition at line 182 of file ASTNodeTraverser.h.
References clang::attrvisitor::Base< llvm::make_const_ptr, ImplClass, void, ParamTys... >::Visit().
Visit() [3/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const BlockDecl::Capture & C) inline
Definition at line 206 of file ASTNodeTraverser.h.
References clang::C, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Visit() [4/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const comments::Comment * C, const comments::FullComment * FC) inline
Definition at line 235 of file ASTNodeTraverser.h.
References clang::C, clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::comments::CommentVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >::visit().
Visit() [5/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const CXXCtorInitializer * Init) inline
Definition at line 189 of file ASTNodeTraverser.h.
References clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Visit() [6/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Decl * D) inline
Definition at line 87 of file ASTNodeTraverser.h.
Referenced by clang::APValue::dump(), clang::APValue::dump(), clang::comments::Comment::dump(), clang::comments::Comment::dump(), clang::QualType::dump(), clang::QualType::dump(), clang::comments::Comment::dumpColor(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpDeclContext(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpObjCTypeParamList(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDeclSpecialization(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAdjustedType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitArrayType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAtomicType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBindingDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockPointerType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCallExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassScopeFunctionSpecializationDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitComplexType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXCatchStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXForRangeStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXRewrittenBinaryOperator(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDeclStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecltypeType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecompositionDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedArrayType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedExtVectorType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitEnumConstantDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitExpressionTemplateArgument(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFieldDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFileScopeAsmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFriendDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionProtoType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGenericSelectionExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitInitListExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLocInfoType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitMemberPointerType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitNonTypeTemplateParmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCAtCatchStmt(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCImplementationDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCMethodDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCObjectPointerType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPAllocateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPCapturedExprDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareMapperDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareReductionDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPExecutableDirective(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPThreadPrivateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOpaqueValueExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackExpansionType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackTemplateArgument(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPipeType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPointerType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitReferenceType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSizeOfPackExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitStaticAssertDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmPackExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmPackType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateSpecializationType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTypeParmDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasTemplateDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypedefDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeOfExprType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeTemplateArgument(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUnaryTransformType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUsingShadowDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVariableArrayType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVectorType().
Visit() [7/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const DynTypedNode & N) inline
Definition at line 251 of file ASTNodeTraverser.h.
References clang::C, N, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Visit() [8/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const GenericSelectionExpr::ConstAssociation & A) inline
Definition at line 222 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Visit() [9/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const OMPClause * C) inline
Definition at line 214 of file ASTNodeTraverser.h.
References clang::C, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Visit() [10/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Stmt * Node, StringRef Label = {}) inline
Definition at line 121 of file ASTNodeTraverser.h.
Visit() [11/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const TemplateArgument & A, SourceRange R = {}, const Decl * From = nullptr, const char * Label = nullptr) inline
Definition at line 198 of file ASTNodeTraverser.h.
Visit() [12/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Type * T) inline
Definition at line 168 of file ASTNodeTraverser.h.
References clang::Type::getLocallyUnqualifiedSingleStepDesugaredType(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::TypeVisitor< ImplClass, RetTy >::Visit().
Visit() [13/13]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (QualType T) inline
Definition at line 157 of file ASTNodeTraverser.h.
References clang::Qualifiers::hasQualifiers(), clang::SplitQualType::Quals, clang::SplitQualType::Ty, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitAcquireCapabilityAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAcquireCapabilityAttr (const AcquireCapabilityAttr * A) inline
Definition at line 20 of file ASTNodeTraverser.h.
VisitAcquiredAfterAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAcquiredAfterAttr (const AcquiredAfterAttr * A) inline
Definition at line 25 of file ASTNodeTraverser.h.
VisitAcquiredBeforeAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAcquiredBeforeAttr (const AcquiredBeforeAttr * A) inline
Definition at line 30 of file ASTNodeTraverser.h.
VisitAdjustedType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAdjustedType (const AdjustedType * T) inline
Definition at line 382 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitAlignedAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAlignedAttr (const AlignedAttr * A) inline
Definition at line 39 of file ASTNodeTraverser.h.
VisitAlignValueAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAlignValueAttr (const AlignValueAttr * A) inline
Definition at line 35 of file ASTNodeTraverser.h.
VisitAMDGPUFlatWorkGroupSizeAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAMDGPUFlatWorkGroupSizeAttr (const AMDGPUFlatWorkGroupSizeAttr * A) inline
Definition at line 10 of file ASTNodeTraverser.h.
VisitAMDGPUWavesPerEUAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAMDGPUWavesPerEUAttr (const AMDGPUWavesPerEUAttr * A) inline
Definition at line 15 of file ASTNodeTraverser.h.
VisitAnnotateAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAnnotateAttr (const AnnotateAttr * A) inline
Definition at line 44 of file ASTNodeTraverser.h.
VisitArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitArrayType (const ArrayType * T) inline
Definition at line 332 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVariableArrayType().
VisitAssertCapabilityAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAssertCapabilityAttr (const AssertCapabilityAttr * A) inline
Definition at line 49 of file ASTNodeTraverser.h.
VisitAssertExclusiveLockAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAssertExclusiveLockAttr (const AssertExclusiveLockAttr * A) inline
Definition at line 54 of file ASTNodeTraverser.h.
VisitAssertSharedLockAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAssertSharedLockAttr (const AssertSharedLockAttr * A) inline
Definition at line 59 of file ASTNodeTraverser.h.
VisitAssumeAlignedAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAssumeAlignedAttr (const AssumeAlignedAttr * A) inline
Definition at line 64 of file ASTNodeTraverser.h.
VisitAtomicType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAtomicType (const AtomicType * T) inline
Definition at line 380 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitAttributedStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedStmt (const AttributedStmt * Node) inline
Definition at line 650 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitAttributedType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedType (const AttributedType * T) inline
Definition at line 361 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitBindingDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBindingDecl (const BindingDecl * D) inline
Definition at line 440 of file ASTNodeTraverser.h.
References clang::BindingDecl::getBinding(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitBlockDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl (const BlockDecl * D) inline
Definition at line 636 of file ASTNodeTraverser.h.
References clang::BlockDecl::captures(), clang::BlockDecl::getBody(), clang::BlockDecl::parameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitBlockExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockExpr (const BlockExpr * Node) inline
Definition at line 674 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitBlockPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockPointerType (const BlockPointerType * T) inline
Definition at line 322 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitBuiltinTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBuiltinTemplateDecl (const BuiltinTemplateDecl * D) inline
Definition at line 549 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), and clang::TemplateDecl::getTemplateParameters().
VisitCallExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCallExpr (const CallExpr * Node) inline
Definition at line 739 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitCapturedDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedDecl (const CapturedDecl * D) inline
Definition at line 449 of file ASTNodeTraverser.h.
References clang::CapturedDecl::getBody(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitCapturedStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedStmt (const CapturedStmt * Node) inline
Definition at line 659 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitClassScopeFunctionSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassScopeFunctionSpecializationDecl (const ClassScopeFunctionSpecializationDecl * D) inline
Definition at line 542 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpASTTemplateArgumentListInfo(), clang::ClassScopeFunctionSpecializationDecl::getSpecialization(), clang::ClassScopeFunctionSpecializationDecl::getTemplateArgsAsWritten(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitClassTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateDecl (const ClassTemplateDecl * D) inline
Definition at line 527 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl().
VisitClassTemplatePartialSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplatePartialSpecializationDecl (const ClassTemplatePartialSpecializationDecl * D) inline
Definition at line 536 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::ClassTemplatePartialSpecializationDecl::getTemplateParameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateSpecializationDecl().
VisitClassTemplateSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateSpecializationDecl (const ClassTemplateSpecializationDecl * D) inline
Definition at line 531 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList(), and clang::ClassTemplateSpecializationDecl::getTemplateArgs().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplatePartialSpecializationDecl().
VisitComplexType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitComplexType (const ComplexType * T) inline
Definition at line 317 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitConceptDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptDecl (const ConceptDecl * D) inline
Definition at line 591 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::ConceptDecl::getConstraintExpr(), clang::TemplateDecl::getTemplateParameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitConceptSpecializationExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr (const ConceptSpecializationExpr * CSE) inline
Definition at line 596 of file ASTNodeTraverser.h.
References clang::ASTTemplateArgumentListInfo::arguments(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc(), clang::ConceptReference::getTemplateArgsAsWritten(), and clang::ConceptReference::hasExplicitTemplateArgs().
VisitCUDALaunchBoundsAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCUDALaunchBoundsAttr (const CUDALaunchBoundsAttr * A) inline
Definition at line 69 of file ASTNodeTraverser.h.
VisitCXXCatchStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXCatchStmt (const CXXCatchStmt * Node) inline
Definition at line 655 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitCXXForRangeStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXForRangeStmt (const CXXForRangeStmt * Node) inline
Definition at line 730 of file ASTNodeTraverser.h.
References Node, clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitCXXRewrittenBinaryOperator()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator * Node) inline
Definition at line 750 of file ASTNodeTraverser.h.
References Node, clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitDeclStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDeclStmt (const DeclStmt * Node) inline
Definition at line 645 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitDecltypeType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecltypeType (const DecltypeType * T) inline
Definition at line 355 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitDecompositionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecompositionDecl (const DecompositionDecl * D) inline
Definition at line 434 of file ASTNodeTraverser.h.
References clang::DecompositionDecl::bindings(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl().
VisitDependentSizedArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedArrayType (const DependentSizedArrayType * T) inline
Definition at line 337 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitDependentSizedExtVectorType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedExtVectorType (const DependentSizedExtVectorType * T) inline
Definition at line 341 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitDiagnoseIfAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDiagnoseIfAttr (const DiagnoseIfAttr * A) inline
Definition at line 74 of file ASTNodeTraverser.h.
VisitEnableIfAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitEnableIfAttr (const EnableIfAttr * A) inline
Definition at line 78 of file ASTNodeTraverser.h.
VisitEnumConstantDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitEnumConstantDecl (const EnumConstantDecl * D) inline
Definition at line 392 of file ASTNodeTraverser.h.
References clang::EnumConstantDecl::getInitExpr(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitExclusiveTrylockFunctionAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitExclusiveTrylockFunctionAttr (const ExclusiveTrylockFunctionAttr * A) inline
Definition at line 82 of file ASTNodeTraverser.h.
VisitExpressionTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitExpressionTemplateArgument (const TemplateArgument & TA) inline
Definition at line 759 of file ASTNodeTraverser.h.
References clang::TemplateArgument::getAsExpr(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitFieldDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFieldDecl (const FieldDecl * D) inline
Definition at line 419 of file ASTNodeTraverser.h.
References clang::FieldDecl::getBitWidth(), clang::FieldDecl::getInClassInitializer(), clang::FieldDecl::isBitField(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitFileScopeAsmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFileScopeAsmDecl (const FileScopeAsmDecl * D) inline
Definition at line 445 of file ASTNodeTraverser.h.
References clang::FileScopeAsmDecl::getAsmString(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitFriendDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFriendDecl (const FriendDecl * D) inline
Definition at line 607 of file ASTNodeTraverser.h.
References clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitFunctionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl (const FunctionDecl * D) inline
Definition at line 397 of file ASTNodeTraverser.h.
References clang::C, clang::FunctionDecl::doesThisDeclarationHaveABody(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList(), clang::FunctionDecl::getBody(), clang::FunctionDecl::getTemplateSpecializationInfo(), clang::DeclaratorDecl::getTrailingRequiresClause(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::param_begin(), clang::Parameter, clang::FunctionDecl::parameters(), clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitFunctionProtoType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionProtoType (const FunctionProtoType * T) inline
Definition at line 347 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionType().
VisitFunctionTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionTemplateDecl (const FunctionTemplateDecl * D) inline
Definition at line 523 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl().
VisitFunctionType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionType (const FunctionType * T) inline
Definition at line 346 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionProtoType().
VisitGenericSelectionExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGenericSelectionExpr (const GenericSelectionExpr * E) inline
Definition at line 681 of file ASTNodeTraverser.h.
References clang::GenericSelectionExpr::associations(), clang::GenericSelectionExpr::getControllingExpr(), clang::Expr::getType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitGuardedByAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGuardedByAttr (const GuardedByAttr * A) inline
Definition at line 88 of file ASTNodeTraverser.h.
VisitInitListExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitInitListExpr (const InitListExpr * ILE) inline
Definition at line 668 of file ASTNodeTraverser.h.
References clang::InitListExpr::getArrayFiller(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitLambdaExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr (const LambdaExpr * Node) inline
Definition at line 690 of file ASTNodeTraverser.h.
References clang::C, clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), N, Node, clang::StmtVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >::P, clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitLocInfoType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLocInfoType (const LocInfoType * T) inline
Definition at line 318 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitLockReturnedAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLockReturnedAttr (const LockReturnedAttr * A) inline
Definition at line 92 of file ASTNodeTraverser.h.
VisitLocksExcludedAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLocksExcludedAttr (const LocksExcludedAttr * A) inline
Definition at line 96 of file ASTNodeTraverser.h.
VisitLoopHintAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLoopHintAttr (const LoopHintAttr * A) inline
Definition at line 101 of file ASTNodeTraverser.h.
VisitMemberPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitMemberPointerType (const MemberPointerType * T) inline
Definition at line 328 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitNonTypeTemplateParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl * D) inline
Definition at line 574 of file ASTNodeTraverser.h.
References clang::NonTypeTemplateParmDecl::defaultArgumentWasInherited(), clang::NonTypeTemplateParmDecl::getDefaultArgStorage(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom(), clang::NonTypeTemplateParmDecl::getPlaceholderTypeConstraint(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitObjCAtCatchStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCAtCatchStmt (const ObjCAtCatchStmt * Node) inline
Definition at line 725 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitObjCCategoryDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCCategoryDecl (const ObjCCategoryDecl * D) inline
Definition at line 623 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpObjCTypeParamList(), and clang::ObjCCategoryDecl::getTypeParamList().
VisitObjCImplementationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCImplementationDecl (const ObjCImplementationDecl * D) inline
Definition at line 631 of file ASTNodeTraverser.h.
References clang::ObjCImplementationDecl::inits(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitObjCInterfaceDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCInterfaceDecl (const ObjCInterfaceDecl * D) inline
Definition at line 627 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpObjCTypeParamList(), and clang::ObjCInterfaceDecl::getTypeParamListAsWritten().
VisitObjCMethodDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCMethodDecl (const ObjCMethodDecl * D) inline
Definition at line 612 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpDeclContext(), clang::ObjCMethodDecl::getBody(), clang::ObjCMethodDecl::hasBody(), clang::ObjCMethodDecl::isThisDeclarationADefinition(), clang::Parameter, clang::ObjCMethodDecl::parameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitObjCObjectPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCObjectPointerType (const ObjCObjectPointerType * T) inline
Definition at line 377 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPAllocateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPAllocateDecl (const OMPAllocateDecl * D) inline
Definition at line 471 of file ASTNodeTraverser.h.
References clang::C, clang::OMPAllocateDecl::clauselists(), clang::OMPAllocateDecl::varlists(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPAllocateDeclAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPAllocateDeclAttr (const OMPAllocateDeclAttr * A) inline
Definition at line 105 of file ASTNodeTraverser.h.
References clang::TK_AsIs, and Traversal.
VisitOMPCapturedExprDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPCapturedExprDecl (const OMPCapturedExprDecl * D) inline
Definition at line 467 of file ASTNodeTraverser.h.
References clang::VarDecl::getInit(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPDeclareMapperDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareMapperDecl (const OMPDeclareMapperDecl * D) inline
Definition at line 462 of file ASTNodeTraverser.h.
References clang::C, clang::OMPDeclareMapperDecl::clauselists(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPDeclareReductionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl * D) inline
Definition at line 456 of file ASTNodeTraverser.h.
References clang::OMPDeclareReductionDecl::getCombiner(), clang::OMPDeclareReductionDecl::getInitializer(), clang::Initializer, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPDeclareSimdDeclAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareSimdDeclAttr (const OMPDeclareSimdDeclAttr * A) inline
Definition at line 109 of file ASTNodeTraverser.h.
VisitOMPDeclareVariantAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareVariantAttr (const OMPDeclareVariantAttr * A) inline
Definition at line 123 of file ASTNodeTraverser.h.
References Traversal.
VisitOMPExecutableDirective()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPExecutableDirective (const OMPExecutableDirective * Node) inline
Definition at line 663 of file ASTNodeTraverser.h.
References clang::C, Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOMPReferencedVarAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPReferencedVarAttr (const OMPReferencedVarAttr * A) inline
Definition at line 127 of file ASTNodeTraverser.h.
VisitOMPThreadPrivateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPThreadPrivateDecl (const OMPThreadPrivateDecl * D) inline
Definition at line 451 of file ASTNodeTraverser.h.
References clang::OMPThreadPrivateDecl::varlists(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitOpaqueValueExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOpaqueValueExpr (const OpaqueValueExpr * Node) inline
Definition at line 676 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitPackExpansionType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackExpansionType (const PackExpansionType * T) inline
Definition at line 383 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitPackTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackTemplateArgument (const TemplateArgument & TA) inline
Definition at line 767 of file ASTNodeTraverser.h.
References clang::TemplateArgument::pack_elements(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitPipeType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPipeType (const PipeType * T) inline
Definition at line 381 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPointerType (const PointerType * T) inline
Definition at line 321 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitPtGuardedByAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPtGuardedByAttr (const PtGuardedByAttr * A) inline
Definition at line 131 of file ASTNodeTraverser.h.
VisitReferenceType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitReferenceType (const ReferenceType * T) inline
Definition at line 325 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitReleaseCapabilityAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitReleaseCapabilityAttr (const ReleaseCapabilityAttr * A) inline
Definition at line 135 of file ASTNodeTraverser.h.
VisitRequiresCapabilityAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitRequiresCapabilityAttr (const RequiresCapabilityAttr * A) inline
Definition at line 140 of file ASTNodeTraverser.h.
VisitSharedTrylockFunctionAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSharedTrylockFunctionAttr (const SharedTrylockFunctionAttr * A) inline
Definition at line 145 of file ASTNodeTraverser.h.
VisitSizeOfPackExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSizeOfPackExpr (const SizeOfPackExpr * Node) inline
Definition at line 710 of file ASTNodeTraverser.h.
References Node, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitStaticAssertDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitStaticAssertDecl (const StaticAssertDecl * D) inline
Definition at line 518 of file ASTNodeTraverser.h.
References clang::StaticAssertDecl::getAssertExpr(), clang::StaticAssertDecl::getMessage(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitSubstNonTypeTemplateParmExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr * E) inline
Definition at line 716 of file ASTNodeTraverser.h.
References clang::SubstNonTypeTemplateParmExpr::getParameter(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitSubstNonTypeTemplateParmPackExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmPackExpr (const SubstNonTypeTemplateParmPackExpr * E) inline
Definition at line 719 of file ASTNodeTraverser.h.
References clang::SubstNonTypeTemplateParmPackExpr::getArgumentPack(), clang::SubstNonTypeTemplateParmPackExpr::getParameterPack(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitSubstTemplateTypeParmPackType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType * T) inline
Definition at line 369 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitSubstTemplateTypeParmType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType * T) inline
Definition at line 365 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTemplateSpecializationType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateSpecializationType (const TemplateSpecializationType * T) inline
Definition at line 373 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTemplateTemplateParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl * D) inline
Definition at line 583 of file ASTNodeTraverser.h.
References clang::TemplateTemplateParmDecl::defaultArgumentWasInherited(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::TemplateTemplateParmDecl::getDefaultArgStorage(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom(), clang::TemplateDecl::getTemplateParameters(), and clang::TemplateTemplateParmDecl::hasDefaultArgument().
VisitTemplateTypeParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTypeParmDecl (const TemplateTypeParmDecl * D) inline
Definition at line 565 of file ASTNodeTraverser.h.
References clang::TemplateTypeParmDecl::defaultArgumentWasInherited(), clang::TemplateTypeParmDecl::getDefaultArgStorage(), clang::TemplateTypeParmDecl::getDefaultArgument(), clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom(), clang::TemplateTypeParmDecl::getTypeConstraint(), clang::TemplateTypeParmDecl::hasDefaultArgument(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTryAcquireCapabilityAttr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTryAcquireCapabilityAttr (const TryAcquireCapabilityAttr * A) inline
Definition at line 151 of file ASTNodeTraverser.h.
VisitTypeAliasDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasDecl (const TypeAliasDecl * D) inline
Definition at line 509 of file ASTNodeTraverser.h.
References clang::TypedefNameDecl::getUnderlyingType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTypeAliasTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl * D) inline
Definition at line 513 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::TypeAliasTemplateDecl::getTemplatedDecl(), clang::TemplateDecl::getTemplateParameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTypedefDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypedefDecl (const TypedefDecl * D) inline
Definition at line 390 of file ASTNodeTraverser.h.
References clang::TypedefNameDecl::getUnderlyingType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTypeOfExprType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeOfExprType (const TypeOfExprType * T) inline
Definition at line 352 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitTypeTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeTemplateArgument (const TemplateArgument & TA) inline
Definition at line 763 of file ASTNodeTraverser.h.
References clang::TemplateArgument::getAsType(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitUnaryTransformType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUnaryTransformType (const UnaryTransformType * T) inline
Definition at line 358 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitUsingShadowDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUsingShadowDecl (const UsingShadowDecl * D) inline
Definition at line 602 of file ASTNodeTraverser.h.
References clang::NamedDecl::getUnderlyingDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
VisitVarDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl (const VarDecl * D) inline
Definition at line 426 of file ASTNodeTraverser.h.
References clang::VarDecl::getInit(), clang::VarDecl::hasInit(), clang::VarDecl::isCXXForRangeDecl(), clang::TK_IgnoreUnlessSpelledInSource, Traversal, and clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecompositionDecl(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateSpecializationDecl().
VisitVariableArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVariableArrayType (const VariableArrayType * T) inline
Definition at line 333 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitArrayType().
VisitVarTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateDecl (const VarTemplateDecl * D) inline
Definition at line 547 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl().
VisitVarTemplatePartialSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplatePartialSpecializationDecl (const VarTemplatePartialSpecializationDecl * D) inline
Definition at line 559 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters(), clang::VarTemplatePartialSpecializationDecl::getTemplateParameters(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateSpecializationDecl().
VisitVarTemplateSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateSpecializationDecl (const VarTemplateSpecializationDecl * D) inline
Definition at line 554 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList(), clang::VarTemplateSpecializationDecl::getTemplateArgs(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl().
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplatePartialSpecializationDecl().
VisitVectorType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVectorType (const VectorType * T) inline
Definition at line 345 of file ASTNodeTraverser.h.
References clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit().
The documentation for this class was generated from the following file:
include/clang/AST/ASTNodeTraverser.h