clang: clang::ento::CodeTextRegion Class Reference
clang::ento::CodeTextRegion Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
bool isBoundable () const override
Public Member Functions inherited from clang::ento::TypedRegion
virtual QualType getLocationType () const =0
QualType getDesugaredLocationType (ASTContext &Context) const
bool isBoundable () const override
Public Member Functions inherited from clang::ento::SubRegion
const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
virtual void Profile (llvm::FoldingSetNodeID &ID) const =0
const MemSpaceRegion * getMemorySpace () const
const MemRegion * getBaseRegion () const
const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasGlobalsOrParametersStorage () const
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
virtual void dumpToStream (raw_ostream &os) const
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Protected Member Functions
CodeTextRegion (const MemSpaceRegion *sreg, Kind k)
Protected Member Functions inherited from clang::ento::TypedRegion
TypedRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
Definition at line 553 of file MemRegion.h.
Constructor & Destructor Documentation
CodeTextRegion()
clang::ento::CodeTextRegion::CodeTextRegion (const MemSpaceRegion * sreg, Kind k) inline protected
Definition at line 557 of file MemRegion.h.
References classof().
Member Function Documentation
classof()
static bool clang::ento::CodeTextRegion::classof (const MemRegion * R) inline static
Definition at line 564 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
Referenced by CodeTextRegion().
isBoundable()
bool clang::ento::CodeTextRegion::isBoundable () const inline override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 562 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp