clang: clang::DeclContextLookupResult Class Reference
clang::DeclContextLookupResult Class Reference
The results of name lookup within a DeclContext.
#include "clang/AST/DeclBase.h"
Classes
class iterator
Public Types
using IteratorBase
using const_iterator = iterator
using pointer = iterator::pointer
using reference = iterator::reference
Public Member Functions
DeclContextLookupResult ()=default
DeclContextLookupResult (ArrayRef< NamedDecl * > Result)
DeclContextLookupResult (NamedDecl *Single)
iterator begin () const
iterator end () const
bool empty () const
pointer data () const
size_t size () const
reference front () const
reference back () const
reference operator[] (size_t N) const
DeclContextLookupResult slice (size_t N) const
Detailed Description
The results of name lookup within a DeclContext.
This is either a single result (with no stable storage) or a collection of results (with stable storage provided by the lookup table).
Definition at line 1227 of file DeclBase.h.
Member Typedef Documentation
const_iterator
using clang::DeclContextLookupResult::const_iterator = iterator
Definition at line 1263 of file DeclBase.h.
IteratorBase
using clang::DeclContextLookupResult::IteratorBase
Initial value:
      llvm::iterator_adaptor_base<iterator, ResultTy::iterator,
                                  std::random_access_iterator_tag, NamedDecl *>
Definition at line 1247 of file DeclBase.h.
pointer
using clang::DeclContextLookupResult::pointer = iterator::pointer
Definition at line 1264 of file DeclBase.h.
reference
using clang::DeclContextLookupResult::reference = iterator::reference
Definition at line 1265 of file DeclBase.h.
Constructor & Destructor Documentation
DeclContextLookupResult() [1/3]
clang::DeclContextLookupResult::DeclContextLookupResult () default
DeclContextLookupResult() [2/3]
clang::DeclContextLookupResult::DeclContextLookupResult (ArrayRef< NamedDecl * > Result) inline
Definition at line 1240 of file DeclBase.h.
DeclContextLookupResult() [3/3]
clang::DeclContextLookupResult::DeclContextLookupResult (NamedDecl * Single) inline
Definition at line 1242 of file DeclBase.h.
References clang::Single.
Member Function Documentation
back()
reference clang::DeclContextLookupResult::back () const inline
Definition at line 1274 of file DeclBase.h.
References clang::Single.
begin()
iterator clang::DeclContextLookupResult::begin () const inline
Definition at line 1267 of file DeclBase.h.
References clang::Single.
Referenced by clang::Sema::CheckCompletedCXXClass(), checkGlobalOrExternCConflict(), clang::Sema::DeclareGlobalAllocationFunction(), clang::ASTDumper::dumpLookups(), clang::Sema::FindHiddenVirtualMethods(), clang::Sema::FindInstantiatedDecl(), clang::ObjCPropertyDecl::findPropertyDecl(), clang::ObjCContainerDecl::getIvarDecl(), clang::ObjCContainerDecl::getMethod(), clang::ObjCContainerDecl::HasUserDeclaredSetterMethod(), clang::DeclContext::localUncachedLookup(), clang::Sema::LookupQualifiedName(), and clang::Sema::LookupSpecialMember().
data()
pointer clang::DeclContextLookupResult::data () const inline
Definition at line 1271 of file DeclBase.h.
References clang::Single.
empty()
bool clang::DeclContextLookupResult::empty () const inline
Definition at line 1270 of file DeclBase.h.
Referenced by clang::Sema::ActOnPropertyImplDecl(), findImplicitlyDeclaredEqualityComparisons(), clang::Sema::findLocallyScopedExternCDecl(), clang::CXXRecordDecl::getDestructor(), getLambdaCallOperatorHelper(), lookupCXXRecordDecl(), clang::Sema::LookupQualifiedName(), clang::Sema::LookupSpecialMember(), lookupStdNamespace(), and clang::TreeTransform< Derived >::RebuildShuffleVectorExpr().
end()
iterator clang::DeclContextLookupResult::end () const inline
Definition at line 1268 of file DeclBase.h.
References clang::Single.
Referenced by clang::Sema::CheckCompletedCXXClass(), checkGlobalOrExternCConflict(), clang::Sema::DeclareGlobalAllocationFunction(), clang::ASTDumper::dumpLookups(), clang::Sema::FindHiddenVirtualMethods(), clang::Sema::FindInstantiatedDecl(), clang::ObjCPropertyDecl::findPropertyDecl(), clang::ObjCContainerDecl::getIvarDecl(), clang::ObjCContainerDecl::getMethod(), clang::ObjCContainerDecl::HasUserDeclaredSetterMethod(), clang::DeclContext::localUncachedLookup(), clang::Sema::LookupQualifiedName(), and clang::Sema::LookupSpecialMember().
front()
reference clang::DeclContextLookupResult::front () const inline
Definition at line 1273 of file DeclBase.h.
References clang::Single.
Referenced by allLookupResultsAreTheSame(), clang::Sema::BuildBlockForLambdaConversion(), clang::CXXRecordDecl::getDestructor(), getLambdaCallOperatorHelper(), clang::Sema::InstantiateClassMembers(), lookupCXXRecordDecl(), lookupStdNamespace(), and clang::TreeTransform< Derived >::RebuildShuffleVectorExpr().
operator[]()
reference clang::DeclContextLookupResult::operator[] (size_t N) const inline
Definition at line 1275 of file DeclBase.h.
References N, and clang::Single.
size()
size_t clang::DeclContextLookupResult::size () const inline
Definition at line 1272 of file DeclBase.h.
References clang::Single.
Referenced by clang::Sema::ActOnProperty(), CheckPropertyAgainstProtocol(), ClassImplementsAllMethodsAndProperties(), and clang::NamedDecl::printNestedNameSpecifier().
slice()
DeclContextLookupResult clang::DeclContextLookupResult::slice (size_t N) const inline
Definition at line 1278 of file DeclBase.h.
References N, and clang::Single.
The documentation for this class was generated from the following files:
include/clang/AST/DeclBase.h
lib/AST/DeclBase.cpp