clang: clang::ento::StoreRef Class Reference
clang::ento::StoreRef Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/StoreRef.h"
Public Member Functions
StoreRef (Store store, StoreManager &smgr)
StoreRef (const StoreRef &sr)
StoreRef & operator= (StoreRef const &newStore)
~StoreRef ()
bool operator== (const StoreRef &x) const
bool operator!= (const StoreRef &x) const
Store getStore () const
const StoreManager & getStoreManager () const
Detailed Description
Definition at line 29 of file StoreRef.h.
Constructor & Destructor Documentation
StoreRef() [1/2]
clang::ento::StoreRef::StoreRef (Store store, StoreManager & smgr) inline
Definition at line 293 of file Store.h.
References clang::ento::StoreManager::incrementReferenceCount().
StoreRef() [2/2]
clang::ento::StoreRef::StoreRef (const StoreRef & sr) inline
Definition at line 299 of file Store.h.
References clang::ento::StoreManager::incrementReferenceCount().
~StoreRef()
clang::ento::StoreRef::~StoreRef () inline
Definition at line 306 of file Store.h.
References clang::ento::StoreManager::decrementReferenceCount().
Member Function Documentation
getStore()
Store clang::ento::StoreRef::getStore () const inline
Definition at line 46 of file StoreRef.h.
Referenced by clang::ento::LazyCompoundValData::getStore(), clang::ento::ProgramState::killBinding(), operator=(), and clang::ento::LazyCompoundValData::Profile().
getStoreManager()
const StoreManager & clang::ento::StoreRef::getStoreManager () const inline
Definition at line 47 of file StoreRef.h.
operator!=()
bool clang::ento::StoreRef::operator!= (const StoreRef & x) const inline
Definition at line 44 of file StoreRef.h.
References operator==().
operator=()
StoreRef & clang::ento::StoreRef::operator= (StoreRef const & newStore) inline
Definition at line 311 of file Store.h.
References clang::ento::StoreManager::decrementReferenceCount(), getStore(), and clang::ento::StoreManager::incrementReferenceCount().
operator==()
bool clang::ento::StoreRef::operator== (const StoreRef & x) const inline
Definition at line 39 of file StoreRef.h.
Referenced by operator!=().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/StoreRef.h
include/clang/StaticAnalyzer/Core/PathSensitive/Store.h