clang: clang::ento::EnvironmentManager Class Reference
clang::ento::EnvironmentManager Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/Environment.h"
Public Member Functions
EnvironmentManager (llvm::BumpPtrAllocator &Allocator)
Environment getInitialEnvironment ()
Environment bindExpr (Environment Env, const EnvironmentEntry &E, SVal V, bool Invalidate)
Bind a symbolic value to the given environment entry.
Environment removeDeadBindings (Environment Env, SymbolReaper &SymReaper, ProgramStateRef state)
Detailed Description
Definition at line 99 of file Environment.h.
Constructor & Destructor Documentation
EnvironmentManager()
clang::ento::EnvironmentManager::EnvironmentManager (llvm::BumpPtrAllocator & Allocator) inline
Definition at line 106 of file Environment.h.
Member Function Documentation
bindExpr()
Environment EnvironmentManager::bindExpr (Environment Env, const EnvironmentEntry & E, SVal V, bool Invalidate)
Bind a symbolic value to the given environment entry.
Definition at line 136 of file Environment.cpp.
References V.
Referenced by clang::ento::ProgramState::BindExpr().
getInitialEnvironment()
Environment clang::ento::EnvironmentManager::getInitialEnvironment () inline
Definition at line 108 of file Environment.h.
Referenced by clang::ento::ProgramStateManager::getInitialState(), and removeDeadBindings().
removeDeadBindings()
Environment EnvironmentManager::removeDeadBindings (Environment Env, SymbolReaper & SymReaper, ProgramStateRef state)
Definition at line 178 of file Environment.cpp.
References clang::ento::Environment::begin(), clang::ento::Environment::end(), getInitialEnvironment(), clang::ento::EnvironmentEntry::getLocationContext(), clang::ento::EnvironmentEntry::getStmt(), clang::ento::SymbolReaper::isLive(), clang::ento::ScanReachableSymbols::scan(), and X().
Referenced by clang::ento::ProgramStateManager::removeDeadBindingsFromEnvironmentAndStore().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/Environment.h
lib/StaticAnalyzer/Core/Environment.cpp