clang: clang::threadSafety::til::SimpleArray< T > Class Template Reference
clang::threadSafety::til::SimpleArray< T > Class Template Reference
#include "clang/Analysis/Analyses/ThreadSafetyUtil.h"
Public Types
using iterator = T *
using const_iterator = const T *
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
Public Member Functions
SimpleArray ()=default
SimpleArray (T *Dat, size_t Cp, size_t Sz=0)
SimpleArray (MemRegionRef A, size_t Cp)
SimpleArray (const SimpleArray< T > &A)=delete
SimpleArray (SimpleArray< T > &&A)
SimpleArray & operator= (SimpleArray &&RHS)
void reserve (size_t Ncp, MemRegionRef A)
void reserveCheck (size_t N, MemRegionRef A)
size_t size () const
size_t capacity () const
T & operator[] (unsigned i)
const T & operator[] (unsigned i) const
T & back ()
const T & back () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void push_back (const T &Elem)
void drop (unsigned n=0)
void setValues (unsigned Sz, const T &C)
template<class Iter >
unsigned append (Iter I, Iter E)
llvm::iterator_range< reverse_iterator > reverse ()
llvm::iterator_range< const_reverse_iterator > reverse () const
Detailed Description
template<class T>
class clang::threadSafety::til::SimpleArray< T >
Definition at line 84 of file ThreadSafetyUtil.h.
Member Typedef Documentation
const_iterator
template<class T > using clang::threadSafety::til::SimpleArray< T >::const_iterator = const T *
Definition at line 131 of file ThreadSafetyUtil.h.
const_reverse_iterator
template<class T > using clang::threadSafety::til::SimpleArray< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 133 of file ThreadSafetyUtil.h.
iterator
template<class T > using clang::threadSafety::til::SimpleArray< T >::iterator = T *
Definition at line 130 of file ThreadSafetyUtil.h.
reverse_iterator
template<class T > using clang::threadSafety::til::SimpleArray< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 132 of file ThreadSafetyUtil.h.
Constructor & Destructor Documentation
SimpleArray() [1/5]
template<class T > clang::threadSafety::til::SimpleArray< T >::SimpleArray () default
SimpleArray() [2/5]
template<class T > clang::threadSafety::til::SimpleArray< T >::SimpleArray (T * Dat, size_t Cp, size_t Sz = 0) inline
Definition at line 87 of file ThreadSafetyUtil.h.
SimpleArray() [3/5]
template<class T > clang::threadSafety::til::SimpleArray< T >::SimpleArray (MemRegionRef A, size_t Cp) inline
Definition at line 89 of file ThreadSafetyUtil.h.
SimpleArray() [4/5]
template<class T > clang::threadSafety::til::SimpleArray< T >::SimpleArray (const SimpleArray< T > & A) delete
SimpleArray() [5/5]
template<class T > clang::threadSafety::til::SimpleArray< T >::SimpleArray (SimpleArray< T > && A) inline
Definition at line 93 of file ThreadSafetyUtil.h.
Member Function Documentation
append()
template<class T > template<class Iter > unsigned clang::threadSafety::til::SimpleArray< T >::append (Iter I, Iter E) inline
Definition at line 197 of file ThreadSafetyUtil.h.
back() [1/2]
template<class T > T & clang::threadSafety::til::SimpleArray< T >::back () inline
Definition at line 148 of file ThreadSafetyUtil.h.
back() [2/2]
template<class T > const T & clang::threadSafety::til::SimpleArray< T >::back () const inline
Definition at line 153 of file ThreadSafetyUtil.h.
begin() [1/2]
template<class T > iterator clang::threadSafety::til::SimpleArray< T >::begin () inline
Definition at line 158 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::SCFG::begin(), clang::threadSafety::til::SimpleArray< T >::rend(), and clang::threadSafety::til::SimpleArray< T >::rend().
begin() [2/2]
template<class T > const_iterator clang::threadSafety::til::SimpleArray< T >::begin () const inline
Definition at line 161 of file ThreadSafetyUtil.h.
capacity()
template<class T > size_t clang::threadSafety::til::SimpleArray< T >::capacity () const inline
Definition at line 136 of file ThreadSafetyUtil.h.
cbegin()
template<class T > const_iterator clang::threadSafety::til::SimpleArray< T >::cbegin () const inline
Definition at line 164 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::SCFG::cbegin(), and clang::threadSafety::til::BasicBlock::findPredecessorIndex().
cend()
template<class T > const_iterator clang::threadSafety::til::SimpleArray< T >::cend () const inline
Definition at line 165 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::SCFG::cend().
drop()
template<class T > void clang::threadSafety::til::SimpleArray< T >::drop (unsigned n = 0) inline
Definition at line 184 of file ThreadSafetyUtil.h.
end() [1/2]
template<class T > iterator clang::threadSafety::til::SimpleArray< T >::end () inline
Definition at line 159 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::SCFG::end(), clang::threadSafety::til::SimpleArray< T >::rbegin(), and clang::threadSafety::til::SimpleArray< T >::rbegin().
end() [2/2]
template<class T > const_iterator clang::threadSafety::til::SimpleArray< T >::end () const inline
Definition at line 162 of file ThreadSafetyUtil.h.
operator=()
template<class T > SimpleArray & clang::threadSafety::til::SimpleArray< T >::operator= (SimpleArray< T > && RHS) inline
Definition at line 100 of file ThreadSafetyUtil.h.
operator[]() [1/2]
template<class T > T & clang::threadSafety::til::SimpleArray< T >::operator[] (unsigned i) inline
Definition at line 138 of file ThreadSafetyUtil.h.
operator[]() [2/2]
template<class T > const T & clang::threadSafety::til::SimpleArray< T >::operator[] (unsigned i) const inline
Definition at line 143 of file ThreadSafetyUtil.h.
push_back()
template<class T > void clang::threadSafety::til::SimpleArray< T >::push_back (const T & Elem) inline
Definition at line 178 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::SCFG::add(), clang::threadSafety::til::BasicBlock::addArgument(), clang::threadSafety::til::BasicBlock::addInstruction(), and clang::threadSafety::til::BasicBlock::addPredecessor().
rbegin() [1/2]
template<class T > reverse_iterator clang::threadSafety::til::SimpleArray< T >::rbegin () inline
Definition at line 167 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::end().
Referenced by clang::threadSafety::til::SimpleArray< T >::reverse(), and clang::threadSafety::til::SimpleArray< T >::reverse().
rbegin() [2/2]
template<class T > const_reverse_iterator clang::threadSafety::til::SimpleArray< T >::rbegin () const inline
Definition at line 170 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::end().
rend() [1/2]
template<class T > reverse_iterator clang::threadSafety::til::SimpleArray< T >::rend () inline
Definition at line 168 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::begin().
Referenced by clang::threadSafety::til::SimpleArray< T >::reverse(), and clang::threadSafety::til::SimpleArray< T >::reverse().
rend() [2/2]
template<class T > const_reverse_iterator clang::threadSafety::til::SimpleArray< T >::rend () const inline
Definition at line 174 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::begin().
reserve()
template<class T > void clang::threadSafety::til::SimpleArray< T >::reserve (size_t Ncp, MemRegionRef A) inline
Definition at line 113 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::MemRegionRef::allocateT(), and memcpy().
Referenced by clang::threadSafety::til::BasicBlock::reserveArguments(), clang::threadSafety::til::SimpleArray< T >::reserveCheck(), clang::threadSafety::til::BasicBlock::reserveInstructions(), and clang::threadSafety::til::BasicBlock::reservePredecessors().
reserveCheck()
template<class T > void clang::threadSafety::til::SimpleArray< T >::reserveCheck (size_t N, MemRegionRef A) inline
Definition at line 123 of file ThreadSafetyUtil.h.
References N, and clang::threadSafety::til::SimpleArray< T >::reserve().
Referenced by clang::threadSafety::til::SCFG::add(), clang::threadSafety::til::BasicBlock::addArgument(), clang::threadSafety::til::BasicBlock::addInstruction(), and clang::threadSafety::til::BasicBlock::addPredecessor().
reverse() [1/2]
template<class T > llvm::iterator_range< reverse_iterator > clang::threadSafety::til::SimpleArray< T >::reverse () inline
Definition at line 206 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::rbegin(), and clang::threadSafety::til::SimpleArray< T >::rend().
reverse() [2/2]
template<class T > llvm::iterator_range< const_reverse_iterator > clang::threadSafety::til::SimpleArray< T >::reverse () const inline
Definition at line 210 of file ThreadSafetyUtil.h.
References clang::threadSafety::til::SimpleArray< T >::rbegin(), and clang::threadSafety::til::SimpleArray< T >::rend().
setValues()
template<class T > void clang::threadSafety::til::SimpleArray< T >::setValues (unsigned Sz, const T & C) inline
Definition at line 189 of file ThreadSafetyUtil.h.
References clang::C.
size()
template<class T > size_t clang::threadSafety::til::SimpleArray< T >::size () const inline
Definition at line 135 of file ThreadSafetyUtil.h.
Referenced by clang::threadSafety::til::BasicBlock::addPredecessor(), clang::threadSafety::til::SCFG::numBlocks(), clang::threadSafety::til::BasicBlock::numPredecessors(), clang::threadSafety::til::simplifyIncompleteArg(), clang::threadSafety::til::BasicBlock::traverse(), clang::threadSafety::til::Phi::traverse(), clang::threadSafety::til::SCFG::traverse(), and clang::threadSafety::til::SCFG::valid().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyUtil.h