clang: clang::CompilerInvocation Class Reference
clang::CompilerInvocation Class Reference
Helper class for holding the data necessary to invoke the compiler.
#include "clang/Frontend/CompilerInvocation.h"
Public Member Functions
CompilerInvocation ()
Option Subgroups
AnalyzerOptionsRef getAnalyzerOpts () const
MigratorOptions & getMigratorOpts ()
const MigratorOptions & getMigratorOpts () const
CodeGenOptions & getCodeGenOpts ()
const CodeGenOptions & getCodeGenOpts () const
DependencyOutputOptions & getDependencyOutputOpts ()
const DependencyOutputOptions & getDependencyOutputOpts () const
FileSystemOptions & getFileSystemOpts ()
const FileSystemOptions & getFileSystemOpts () const
FrontendOptions & getFrontendOpts ()
const FrontendOptions & getFrontendOpts () const
PreprocessorOutputOptions & getPreprocessorOutputOpts ()
const PreprocessorOutputOptions & getPreprocessorOutputOpts () const
Public Member Functions inherited from clang::CompilerInvocationBase
CompilerInvocationBase ()
CompilerInvocationBase (const CompilerInvocationBase &X)
CompilerInvocationBase & operator= (const CompilerInvocationBase &)=delete
~CompilerInvocationBase ()
LangOptions * getLangOpts ()
const LangOptions * getLangOpts () const
TargetOptions & getTargetOpts ()
const TargetOptions & getTargetOpts () const
DiagnosticOptions & getDiagnosticOpts () const
HeaderSearchOptions & getHeaderSearchOpts ()
const HeaderSearchOptions & getHeaderSearchOpts () const
std::shared_ptr< HeaderSearchOptions > getHeaderSearchOptsPtr () const
std::shared_ptr< PreprocessorOptions > getPreprocessorOptsPtr ()
PreprocessorOptions & getPreprocessorOpts ()
const PreprocessorOptions & getPreprocessorOpts () const
Utility Methods
using StringAllocator = llvm::function_ref<const char *(const llvm::Twine &)>
std::string getModuleHash () const
Retrieve a module hash string that is suitable for uniquely identifying the conditions under which the module was built.
void generateCC1CommandLine (llvm::SmallVectorImpl< const char * > &Args, StringAllocator SA) const
Generate a cc1-compatible command line arguments from this instance.
static bool CreateFromArgs (CompilerInvocation &Res, ArrayRef< const char * > CommandLineArgs, DiagnosticsEngine &Diags, const char *Argv0=nullptr)
Create a compiler invocation from a list of input options.
static std::string GetResourcesPath (const char *Argv0, void *MainAddr)
Get the directory where the compiler headers reside, relative to the compiler binary (found by the passed in arguments).
static void setLangDefaults (LangOptions &Opts, InputKind IK, const llvm::Triple &T, std::vector< std::string > &Includes, LangStandard::Kind LangStd=LangStandard::lang_unspecified)
Set language defaults for the given input language and language standard in the given LangOptions object.
Additional Inherited Members
Public Attributes inherited from clang::CompilerInvocationBase
std::shared_ptr< LangOptions > LangOpts
Options controlling the language variant.
std::shared_ptr< TargetOptions > TargetOpts
Options controlling the target.
IntrusiveRefCntPtr< DiagnosticOptions > DiagnosticOpts
Options controlling the diagnostic engine.
std::shared_ptr< HeaderSearchOptions > HeaderSearchOpts
Options controlling the #include directive.
std::shared_ptr< PreprocessorOptions > PreprocessorOpts
Options controlling the preprocessor (aside from #include handling).
Detailed Description
Helper class for holding the data necessary to invoke the compiler.
This class is designed to represent an abstract "invocation" of the compiler, including data such as the include paths, the code generation options, the warning flags, and so on.
Definition at line 120 of file CompilerInvocation.h.
Member Typedef Documentation
StringAllocator
using clang::CompilerInvocation::StringAllocator = llvm::function_ref<const char *(const llvm::Twine &)>
Definition at line 190 of file CompilerInvocation.h.
Constructor & Destructor Documentation
CompilerInvocation()
clang::CompilerInvocation::CompilerInvocation () inline
Definition at line 142 of file CompilerInvocation.h.
Member Function Documentation
CreateFromArgs()
bool CompilerInvocation::CreateFromArgs (CompilerInvocation & Res, ArrayRef< const char * > CommandLineArgs, DiagnosticsEngine & Diags, const char * Argv0 = nullptr) static
Create a compiler invocation from a list of input options.
Returns
true on success.
false if an error was encountered while parsing the arguments and attempts to recover and continue parsing the rest of the arguments. The recovery is best-effort and only guarantees that Res will end up in one of the vaild-to-access (albeit arbitrary) states.
Parameters
[out] Res - The resulting invocation.
[in] CommandLineArgs - Array of argument strings, this must not contain "-cc1".
Definition at line 2850 of file CompilerInvocation.cpp.
References clang::CodeGenOptions::Argv0, clang::FrontendOptions::AuxTriple, clang::driver::options::CC1Option, clang::CodeGenOptions::CommandLineArgs, clang::SanitizerSet::empty(), FixupInvocation(), getAnalyzerOpts(), getCodeGenOpts(), getDependencyOutputOpts(), clang::CompilerInvocationBase::getDiagnosticOpts(), clang::driver::getDriverOptTable(), getFileSystemOpts(), clang::InputKind::getFormat(), getFrontendOpts(), clang::CompilerInvocationBase::getHeaderSearchOpts(), clang::CompilerInvocationBase::getLangOpts(), clang::InputKind::getLanguage(), clang::getLastArgIntValue(), clang::CompilerInvocationBase::getPreprocessorOpts(), getPreprocessorOutputOpts(), clang::CompilerInvocationBase::getTargetOpts(), clang::TargetOptions::HostTriple, clang::PreprocessorOptions::Includes, clang::InputKind::isPreprocessed(), clang::CompilerInvocationBase::LangOpts, clang::LLVM_IR, clang::DependencyOutputOptions::OutputFile, clang::FrontendOptions::OutputFile, ParseAnalyzerArgs(), ParseDependencyOutputArgs(), clang::ParseDiagnosticArgs(), ParseFrontendArgs(), ParseHeaderSearchArgs(), ParsePreprocessorArgs(), ParsePreprocessorOutputArgs(), parseSanitizerKinds(), ParseTargetArgs(), clang::InputKind::Precompiled, clang::FrontendOptions::ProgramAction, clang::DiagnosticsEngine::Report(), clang::frontend::RewriteObjC, clang::LangOptions::Sanitize, clang::DependencyOutputOptions::Targets, clang::TargetOptions::Triple, clang::DiagnosticOptions::Warnings, and clang::FileSystemOptions::WorkingDir.
Referenced by clang::createInvocationFromCommandLine(), and clang::tooling::newInvocation().
generateCC1CommandLine()
void CompilerInvocation::generateCC1CommandLine (llvm::SmallVectorImpl< const char * > & Args, StringAllocator SA) const
Generate a cc1-compatible command line arguments from this instance.
Parameters
[out] Args - The generated arguments. Note that the caller is responsible for inserting the path to the clang executable and "-cc1" if desired.
SA - A function that given a Twine can allocate storage for a given command line argument and return a pointer to the newly allocated string. The returned pointer is what gets appended to Args.
Definition at line 3090 of file CompilerInvocation.cpp.
References GenerateLangArgs(), and clang::CompilerInvocationBase::LangOpts.
getAnalyzerOpts()
AnalyzerOptionsRef clang::CompilerInvocation::getAnalyzerOpts () const inline
Definition at line 206 of file CompilerInvocation.h.
Referenced by CreateFromArgs().
getCodeGenOpts() [1/2]
CodeGenOptions & clang::CompilerInvocation::getCodeGenOpts () inline
Definition at line 211 of file CompilerInvocation.h.
Referenced by CreateFromArgs(), FixupInvocation(), getModuleHash(), and clang::tooling::newInvocation().
getCodeGenOpts() [2/2]
const CodeGenOptions & clang::CompilerInvocation::getCodeGenOpts () const inline
Definition at line 212 of file CompilerInvocation.h.
getDependencyOutputOpts() [1/2]
DependencyOutputOptions & clang::CompilerInvocation::getDependencyOutputOpts () inline
Definition at line 214 of file CompilerInvocation.h.
Referenced by CreateFromArgs().
getDependencyOutputOpts() [2/2]
const DependencyOutputOptions & clang::CompilerInvocation::getDependencyOutputOpts () const inline
Definition at line 218 of file CompilerInvocation.h.
getFileSystemOpts() [1/2]
FileSystemOptions & clang::CompilerInvocation::getFileSystemOpts () inline
Definition at line 222 of file CompilerInvocation.h.
Referenced by CreateFromArgs(), and createInvocationForMigration().
getFileSystemOpts() [2/2]
const FileSystemOptions & clang::CompilerInvocation::getFileSystemOpts () const inline
Definition at line 224 of file CompilerInvocation.h.
getFrontendOpts() [1/2]
FrontendOptions & clang::CompilerInvocation::getFrontendOpts () inline
Definition at line 228 of file CompilerInvocation.h.
Referenced by applyTransforms(), CreateFromArgs(), FixupInvocation(), getModuleHash(), and clang::tooling::newInvocation().
getFrontendOpts() [2/2]
const FrontendOptions & clang::CompilerInvocation::getFrontendOpts () const inline
Definition at line 229 of file CompilerInvocation.h.
getMigratorOpts() [1/2]
MigratorOptions & clang::CompilerInvocation::getMigratorOpts () inline
Definition at line 208 of file CompilerInvocation.h.
Referenced by applyTransforms(), and clang::arcmt::checkForManualIssues().
getMigratorOpts() [2/2]
const MigratorOptions & clang::CompilerInvocation::getMigratorOpts () const inline
Definition at line 209 of file CompilerInvocation.h.
getModuleHash()
std::string CompilerInvocation::getModuleHash () const
Retrieve a module hash string that is suitable for uniquely identifying the conditions under which the module was built.
Definition at line 2977 of file CompilerInvocation.cpp.
References clang::SanitizerSet::clear(), clang::PreprocessorOptions::DetailedRecord, clang::SanitizerSet::empty(), clang::getClangFullRepositoryVersion(), getCodeGenOpts(), clang::CompilerInvocationBase::getDiagnosticOpts(), getFrontendOpts(), clang::CompilerInvocationBase::getHeaderSearchOpts(), clang::getPPTransparentSanitizers(), clang::CompilerInvocationBase::getPreprocessorOpts(), clang::hash_value(), clang::CompilerInvocationBase::LangOpts, clang::SanitizerSet::Mask, clang::FrontendOptions::ModuleFileExtensions, clang::HeaderSearchOptions::ModuleFormat, clang::HeaderSearchOptions::ModulesIgnoreMacros, clang::HeaderSearchOptions::ModulesStrictContextHash, clang::HeaderSearchOptions::ModulesValidateDiagnosticOptions, clang::HeaderSearchOptions::ModuleUserBuildPath, clang::HeaderSearchOptions::ResourceDir, clang::HeaderSearchOptions::Sysroot, clang::HeaderSearchOptions::SystemHeaderPrefixes, clang::CompilerInvocationBase::TargetOpts, clang::HeaderSearchOptions::UseBuiltinIncludes, clang::HeaderSearchOptions::UseDebugInfo, clang::HeaderSearchOptions::UseLibcxx, clang::PreprocessorOptions::UsePredefines, clang::HeaderSearchOptions::UserEntries, clang::HeaderSearchOptions::UseStandardCXXIncludes, clang::HeaderSearchOptions::UseStandardSystemIncludes, clang::serialization::VERSION_MAJOR, and clang::serialization::VERSION_MINOR.
Referenced by clang::CompilerInstance::createPreprocessor(), and clang::tooling::dependencies::ModuleDepCollectorPP::FileChanged().
getPreprocessorOutputOpts() [1/2]
PreprocessorOutputOptions & clang::CompilerInvocation::getPreprocessorOutputOpts () inline
Definition at line 231 of file CompilerInvocation.h.
Referenced by CreateFromArgs().
getPreprocessorOutputOpts() [2/2]
const PreprocessorOutputOptions & clang::CompilerInvocation::getPreprocessorOutputOpts () const inline
Definition at line 235 of file CompilerInvocation.h.
GetResourcesPath()
std::string CompilerInvocation::GetResourcesPath (const char * Argv0, void * MainAddr) static
Get the directory where the compiler headers reside, relative to the compiler binary (found by the passed in arguments).
Parameters
Argv0 - The program path (from argv[0]), for finding the builtin compiler path.
MainAddr - The address of main (or some other function in the main executable), for finding the builtin compiler path.
Definition at line 1816 of file CompilerInvocation.cpp.
References clang::driver::Driver::GetResourcesPath().
Referenced by injectResourceDir().
setLangDefaults()
void CompilerInvocation::setLangDefaults (LangOptions & Opts, InputKind IK, const llvm::Triple & T, std::vector< std::string > & Includes, LangStandard::Kind LangStd = LangStandard::lang_unspecified) static
Set language defaults for the given input language and language standard in the given LangOptions object.
Parameters
Opts - The LangOptions object to set up.
IK - The input language.
T - The target triple.
Includes - The affected list of included files.
LangStd - The input language standard.
Definition at line 1940 of file CompilerInvocation.cpp.
References clang::Asm, clang::C, clang::CUDA, clang::CXX, clang::LangOptions::FPM_Fast, clang::LangOptions::FPM_FastHonorPragmas, clang::LangOptions::FPM_On, clang::LangStandard::getLangStandardForKind(), clang::InputKind::getLanguage(), clang::HIP, clang::InputKind::isObjectiveC(), clang::LangStandard::lang_unspecified, clang::LangOptions::LangStd, clang::LLVM_IR, clang::ObjC, clang::ObjCXX, clang::OpenCL, clang::RenderScript, Std, and clang::Unknown.
The documentation for this class was generated from the following files:
include/clang/Frontend/CompilerInvocation.h
lib/Frontend/CompilerInvocation.cpp