clang: clang::driver::toolchains::MSVCToolChain Class Reference
clang::driver::toolchains::MSVCToolChain Class Reference
#include "/root/llvm-project/clang/lib/Driver/ToolChains/MSVC.h"
Public Types
enum class SubDirectoryType { Bin , Include , Lib }
enum class ToolsetLayout { OlderVS , VS2017OrNewer , DevDivInternal }
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx , CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT , RLT_Libgcc }
enum UnwindLibType { UNW_None , UNW_CompilerRT , UNW_Libgcc }
enum RTTIMode { RM_Enabled , RM_Disabled }
enum FileType { FT_Object , FT_Static , FT_Shared }
using path_list = SmallVector<std::string, 16>
Public Member Functions
MSVCToolChain (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
bool IsIntegratedAssemblerDefault () const override
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const override
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault () const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
codegenoptions::DebugInfoFormat getDefaultDebugFormat () const override
Set CodeView as the default debug info format for non-MachO binary formats, and to DWARF otherwise.
llvm::DebuggerKind getDefaultDebuggerTuning () const override
Set the debugger tuning to "default", since we're definitely not tuning for GDB.
std::string getSubDirectoryPath (SubDirectoryType Type, llvm::StringRef SubdirParent, llvm::Triple::ArchType TargetArch) const
std::string getSubDirectoryPath (SubDirectoryType Type, llvm::StringRef SubdirParent="") const
bool getIsVS2017OrNewer () const
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific CUDA includes.
void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific HIP includes.
bool getWindowsSDKLibraryPath (std::string &path) const
bool getUniversalCRTLibraryPath (std::string &path) const
Check if Universal CRT should be used if available.
bool useUniversalCRT () const
VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const override
On Windows, returns the MSVC compatibility version.
std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType) const override
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
void printVerboseInfo (raw_ostream &OS) const override
Dispatch to the specific toolchain for verbose printing.
bool FoundMSVCInstall () const
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const Multilib & getMultilib () const
const SanitizerArgs & getSanitizerArgs () const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
virtual llvm::opt::DerivedArgList * TranslateOpenMPTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs) const
TranslateOpenMPTargetArgs - Create a new derived argument list for that contains the OpenMP target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val.
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr, bool *LinkerIsLLDDarwinNew=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual bool isCrossCompiling () const
Returns true if the toolchain is targeting a non-native architecture.
virtual bool HasNativeLLVMSupport () const
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool IsMathErrnoDefault () const
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual RuntimeLibType GetDefaultRuntimeLibType () const
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
virtual CXXStdlibType GetDefaultCXXStdlibType () const
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
virtual std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static, bool AddArch=true) const
virtual Optional< std::string > getRuntimePath () const
virtual Optional< std::string > getCXXStdlibPath () const
std::string getArchSpecificLibPath () const
virtual StringRef getOSLibName () const
virtual bool isNoExecStackDefault () const
Test whether this toolchaind defaults to non-executable stacks.
virtual bool SupportsProfiling () const
SupportsProfiling - Does this tool chain support -pg.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const
Add options that need to be passed to cc1 for this target.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
virtual void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Protected Member Functions
void AddSystemIncludeWithSubfolder (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const std::string &folder, const Twine &subfolder1, const Twine &subfolder2="", const Twine &subfolder3="") const
Tool * buildLinker () const override
Tool * buildAssembler () const override
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildStaticLibTool () const
virtual Tool * getTool (Action::ActionClass AC) const
Additional Inherited Members
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
Multilib SelectedMultilib
Detailed Description
Definition at line 64 of file MSVC.h.
Member Enumeration Documentation
SubDirectoryType
enum class clang::driver::toolchains::MSVCToolChain::SubDirectoryType strong
Enumerator
Bin
Include
Lib
Definition at line 93 of file MSVC.h.
ToolsetLayout
enum class clang::driver::toolchains::MSVCToolChain::ToolsetLayout strong
Enumerator
OlderVS
VS2017OrNewer
DevDivInternal
Definition at line 109 of file MSVC.h.
Constructor & Destructor Documentation
MSVCToolChain()
MSVCToolChain::MSVCToolChain (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Definition at line 761 of file MSVC.cpp.
References findVCToolChainViaCommandLine(), findVCToolChainViaEnvironment(), findVCToolChainViaRegistry(), findVCToolChainViaSetupConfig(), clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getProgramPaths().
Member Function Documentation
AddClangCXXStdlibIncludeArgs()
void MSVCToolChain::AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 1358 of file MSVC.cpp.
AddClangSystemIncludeArgs()
void MSVCToolChain::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented from clang::driver::ToolChain.
Definition at line 1268 of file MSVC.cpp.
References clang::driver::ToolChain::addSystemInclude(), clang::driver::ToolChain::addSystemIncludes(), AddSystemIncludeWithSubfolder(), clang::driver::ToolChain::getDriver(), getSubDirectoryPath(), getUniversalCRTSdkDir(), getWindowsSDKDir(), Include, and useUniversalCRT().
AddCudaIncludeArgs()
void MSVCToolChain::AddCudaIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use system-specific CUDA includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 818 of file MSVC.cpp.
References clang::driver::CudaInstallationDetector::AddCudaIncludeArgs().
AddHIPIncludeArgs()
void MSVCToolChain::AddHIPIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use system-specific HIP includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 823 of file MSVC.cpp.
References clang::driver::RocmInstallationDetector::AddHIPIncludeArgs().
AddSystemIncludeWithSubfolder()
void MSVCToolChain::AddSystemIncludeWithSubfolder (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, const std::string & folder, const Twine & subfolder1, const Twine & subfolder2 = "", const Twine & subfolder3 = "") const protected
Definition at line 1259 of file MSVC.cpp.
References clang::driver::ToolChain::addSystemInclude().
Referenced by AddClangSystemIncludeArgs().
buildAssembler()
Tool * MSVCToolChain::buildAssembler () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 783 of file MSVC.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getTriple().
buildLinker()
Tool * MSVCToolChain::buildLinker () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 779 of file MSVC.cpp.
ComputeEffectiveClangTriple()
std::string MSVCToolChain::ComputeEffectiveClangTriple (const llvm::opt::ArgList & Args, types::ID InputType) const override virtual
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
For example, on Darwin the -mmacosx-version-min= command line argument (which sets the deployment target) determines the version in the triple passed to Clang.
Reimplemented from clang::driver::ToolChain.
Definition at line 1381 of file MSVC.cpp.
References clang::driver::ToolChain::ComputeEffectiveClangTriple(), and computeMSVCVersion().
computeMSVCVersion()
VersionTuple MSVCToolChain::computeMSVCVersion (const Driver * D, const llvm::opt::ArgList & Args) const override virtual
On Windows, returns the MSVC compatibility version.
Reimplemented from clang::driver::ToolChain.
Definition at line 1363 of file MSVC.cpp.
References Bin, clang::driver::ToolChain::computeMSVCVersion(), getMSVCVersionFromExe(), getMSVCVersionFromTriple(), getSubDirectoryPath(), and clang::driver::ToolChain::getTriple().
Referenced by ComputeEffectiveClangTriple().
FoundMSVCInstall()
bool clang::driver::toolchains::MSVCToolChain::FoundMSVCInstall () const inline
Definition at line 143 of file MSVC.h.
getDefaultDebugFormat()
codegenoptions::DebugInfoFormat clang::driver::toolchains::MSVCToolChain::getDefaultDebugFormat () const inline override virtual
Set CodeView as the default debug info format for non-MachO binary formats, and to DWARF otherwise.
Users can use -gcodeview and -gdwarf to override the default.
Reimplemented from clang::driver::ToolChain.
Definition at line 82 of file MSVC.h.
getDefaultDebuggerTuning()
llvm::DebuggerKind clang::driver::toolchains::MSVCToolChain::getDefaultDebuggerTuning () const inline override virtual
Set the debugger tuning to "default", since we're definitely not tuning for GDB.
Reimplemented from clang::driver::ToolChain.
Definition at line 89 of file MSVC.h.
getIsVS2017OrNewer()
bool clang::driver::toolchains::MSVCToolChain::getIsVS2017OrNewer () const inline
Definition at line 114 of file MSVC.h.
getSubDirectoryPath() [1/2]
std::string MSVCToolChain::getSubDirectoryPath (SubDirectoryType Type, llvm::StringRef SubdirParent, llvm::Triple::ArchType TargetArch) const
Definition at line 893 of file MSVC.cpp.
References Bin, DevDivInternal, Include, Lib, llvmArchToDevDivInternalArch(), llvmArchToLegacyVCArch(), llvmArchToWindowsSDKArch(), OlderVS, and VS2017OrNewer.
Referenced by AddClangSystemIncludeArgs(), computeMSVCVersion(), and useUniversalCRT().
getSubDirectoryPath() [2/2]
std::string clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath (SubDirectoryType Type, llvm::StringRef SubdirParent = "") const inline
Definition at line 104 of file MSVC.h.
getSupportedSanitizers()
SanitizerMask MSVCToolChain::getSupportedSanitizers () const override virtual
Return sanitizers which are available in this toolchain.
Reimplemented from clang::driver::ToolChain.
Definition at line 1403 of file MSVC.cpp.
References clang::driver::ToolChain::getSupportedSanitizers().
getUniversalCRTLibraryPath()
bool MSVCToolChain::getUniversalCRTLibraryPath (std::string & path) const
Check if Universal CRT should be used if available.
Definition at line 1196 of file MSVC.cpp.
References clang::driver::ToolChain::getArch(), getUniversalCRTSdkDir(), and llvmArchToWindowsSDKArch().
getWindowsSDKLibraryPath()
bool MSVCToolChain::getWindowsSDKLibraryPath (std::string & path) const
Definition at line 1140 of file MSVC.cpp.
References clang::driver::ToolChain::getArch(), getWindowsSDKDir(), and llvmArchToWindowsSDKArch().
IsIntegratedAssemblerDefault()
bool MSVCToolChain::IsIntegratedAssemblerDefault () const override virtual
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 790 of file MSVC.cpp.
isPICDefault()
bool MSVCToolChain::isPICDefault () const override virtual
Test whether this toolchain defaults to PIC.
Implements clang::driver::ToolChain.
Definition at line 806 of file MSVC.cpp.
References clang::driver::ToolChain::getArch().
isPICDefaultForced()
bool MSVCToolChain::isPICDefaultForced () const override virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault() are used exclusively.
Implements clang::driver::ToolChain.
Definition at line 814 of file MSVC.cpp.
References clang::driver::ToolChain::getArch().
isPIEDefault()
bool MSVCToolChain::isPIEDefault () const override virtual
Test whether this toolchain defaults to PIE.
Implements clang::driver::ToolChain.
Definition at line 810 of file MSVC.cpp.
IsUnwindTablesDefault()
bool MSVCToolChain::IsUnwindTablesDefault (const llvm::opt::ArgList & Args) const override virtual
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 794 of file MSVC.cpp.
References clang::driver::ToolChain::getArch(), and clang::driver::ToolChain::getTriple().
printVerboseInfo()
void MSVCToolChain::printVerboseInfo (raw_ostream & OS) const override virtual
Dispatch to the specific toolchain for verbose printing.
This is used when handling the verbose option to print detailed, toolchain-specific information useful for understanding the behavior of the driver on a specific platform.
Reimplemented from clang::driver::ToolChain.
Definition at line 828 of file MSVC.cpp.
References clang::driver::CudaInstallationDetector::print(), and clang::driver::RocmInstallationDetector::print().
TranslateArgs()
llvm::opt::DerivedArgList * MSVCToolChain::TranslateArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override virtual
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
If DeviceOffloadKind is specified the translation specific for that offload kind is performed.
Parameters
BoundArch - The bound architecture name, or 0.
DeviceOffloadKind - The device offload kind used for the translation.
Reimplemented from clang::driver::ToolChain.
Definition at line 1527 of file MSVC.cpp.
References clang::driver::ToolChain::getArch(), clang::driver::ToolChain::getDriver(), clang::driver::Driver::getOpts(), clang::driver::Action::OFK_HIP, TranslateDArg(), and TranslateOptArg().
useUniversalCRT()
bool MSVCToolChain::useUniversalCRT () const
Definition at line 1178 of file MSVC.cpp.
References getSubDirectoryPath(), and Include.
Referenced by AddClangSystemIncludeArgs().
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/MSVC.h
lib/Driver/ToolChains/MSVC.cpp