clang: clang::CodeGen::CGBlockInfo Class Reference
clang::CodeGen::CGBlockInfo Class Reference
CGBlockInfo - Information to generate a block literal.
#include "/root/llvm-project/clang/lib/CodeGen/CGBlocks.h"
Classes
class Capture
Public Member Functions
const Capture & getCapture (const VarDecl *var) const
Capture & getCapture (const VarDecl *var)
const BlockDecl * getBlockDecl () const
const BlockExpr * getBlockExpr () const
CGBlockInfo (const BlockDecl *blockDecl, StringRef Name)
bool needsCopyDisposeHelpers () const
Public Attributes
StringRef Name
Name - The name of the block, kindof.
unsigned CXXThisIndex
The field index of 'this' within the block, if there is one.
bool CanBeGlobal: 1
CanBeGlobal - True if the block can be global, i.e.
bool NeedsCopyDispose: 1
True if the block has captures that would necessitate custom copy or dispose helper functions if the block were escaping.
bool HasCXXObject: 1
HasCXXObject - True if the block's custom copy/dispose functions need to be run even in GC mode.
bool UsesStret: 1
UsesStret : True if the block uses an stret return.
bool HasCapturedVariableLayout: 1
HasCapturedVariableLayout : True if block has captured variables and their layout meta-data has been generated.
bool CapturesNonExternalType: 1
Indicates whether an object of a non-external C++ class is captured.
llvm::DenseMap< const VarDecl *, Capture > Captures
The mapping of allocated indexes within the block.
Address LocalAddress
llvm::StructType * StructureType
const BlockDecl * Block
const BlockExpr * BlockExpression
CharUnits BlockSize
CharUnits BlockAlign
CharUnits CXXThisOffset
CharUnits BlockHeaderForcedGapOffset
CharUnits BlockHeaderForcedGapSize
CGBlockInfo * NextBlockInfo
The next block in the block-info chain.
Detailed Description
CGBlockInfo - Information to generate a block literal.
Definition at line 152 of file CGBlocks.h.
Constructor & Destructor Documentation
CGBlockInfo()
CGBlockInfo::CGBlockInfo (const BlockDecl * blockDecl, StringRef Name)
Definition at line 35 of file CGBlocks.cpp.
Member Function Documentation
getBlockDecl()
const BlockDecl * clang::CodeGen::CGBlockInfo::getBlockDecl () const inline
Definition at line 276 of file CGBlocks.h.
References Block.
Referenced by computeBlockInfo(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), and findBlockCapturedManagedEntities().
getBlockExpr()
const BlockExpr * clang::CodeGen::CGBlockInfo::getBlockExpr () const inline
Definition at line 277 of file CGBlocks.h.
References Block, BlockExpression, and clang::BlockExpr::getBlockDecl().
Referenced by buildBlockDescriptor(), buildGlobalBlock(), and getBlockDescriptorName().
getCapture() [1/2]
Capture & clang::CodeGen::CGBlockInfo::getCapture (const VarDecl * var) inline
Definition at line 269 of file CGBlocks.h.
References Captures.
getCapture() [2/2]
const Capture & clang::CodeGen::CGBlockInfo::getCapture (const VarDecl * var) const inline
Definition at line 266 of file CGBlocks.h.
References getCapture().
Referenced by clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockDeclRefVariable(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), findBlockCapturedManagedEntities(), getCapture(), and getCaptureFieldType().
needsCopyDisposeHelpers()
bool clang::CodeGen::CGBlockInfo::needsCopyDisposeHelpers () const inline
Definition at line 286 of file CGBlocks.h.
References Block, clang::BlockDecl::doesNotEscape(), and NeedsCopyDispose.
Referenced by buildBlockDescriptor(), and getBlockDescriptorName().
Member Data Documentation
Block
const BlockDecl* clang::CodeGen::CGBlockInfo::Block
Definition at line 246 of file CGBlocks.h.
Referenced by getBlockDecl(), getBlockExpr(), and needsCopyDisposeHelpers().
BlockAlign
CharUnits clang::CodeGen::CGBlockInfo::BlockAlign
Definition at line 249 of file CGBlocks.h.
Referenced by buildGlobalBlock(), computeBlockInfo(), getBlockDescriptorName(), and initializeForBlockHeader().
BlockExpression
const BlockExpr* clang::CodeGen::CGBlockInfo::BlockExpression
Definition at line 247 of file CGBlocks.h.
Referenced by buildGlobalBlock(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalBlock(), and getBlockExpr().
BlockHeaderForcedGapOffset
CharUnits clang::CodeGen::CGBlockInfo::BlockHeaderForcedGapOffset
Definition at line 255 of file CGBlocks.h.
Referenced by computeBlockInfo().
BlockHeaderForcedGapSize
CharUnits clang::CodeGen::CGBlockInfo::BlockHeaderForcedGapSize
Definition at line 258 of file CGBlocks.h.
Referenced by computeBlockInfo().
BlockSize
CharUnits clang::CodeGen::CGBlockInfo::BlockSize
Definition at line 248 of file CGBlocks.h.
Referenced by buildBlockDescriptor(), buildGlobalBlock(), computeBlockInfo(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), getBlockDescriptorName(), and initializeForBlockHeader().
CanBeGlobal
bool clang::CodeGen::CGBlockInfo::CanBeGlobal
CanBeGlobal - True if the block can be global, i.e.
it has no non-constant captures.
Definition at line 218 of file CGBlocks.h.
Referenced by buildGlobalBlock(), and computeBlockInfo().
Captures
llvm::DenseMap<const VarDecl*, Capture> clang::CodeGen::CGBlockInfo::Captures
The mapping of allocated indexes within the block.
Definition at line 242 of file CGBlocks.h.
Referenced by computeBlockInfo(), and getCapture().
CapturesNonExternalType
bool clang::CodeGen::CGBlockInfo::CapturesNonExternalType
Indicates whether an object of a non-external C++ class is captured.
This bit is used to determine the linkage of the block copy/destroy helper functions.
Definition at line 239 of file CGBlocks.h.
Referenced by computeBlockInfo().
CXXThisIndex
unsigned clang::CodeGen::CGBlockInfo::CXXThisIndex
The field index of 'this' within the block, if there is one.
Definition at line 158 of file CGBlocks.h.
Referenced by clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable().
CXXThisOffset
CharUnits clang::CodeGen::CGBlockInfo::CXXThisOffset
Definition at line 250 of file CGBlocks.h.
HasCapturedVariableLayout
bool clang::CodeGen::CGBlockInfo::HasCapturedVariableLayout
HasCapturedVariableLayout : True if block has captured variables and their layout meta-data has been generated.
Definition at line 234 of file CGBlocks.h.
Referenced by computeBlockInfo().
HasCXXObject
bool clang::CodeGen::CGBlockInfo::HasCXXObject
HasCXXObject - True if the block's custom copy/dispose functions need to be run even in GC mode.
Definition at line 226 of file CGBlocks.h.
Referenced by computeBlockInfo().
LocalAddress
Address clang::CodeGen::CGBlockInfo::LocalAddress
Definition at line 244 of file CGBlocks.h.
Name
StringRef clang::CodeGen::CGBlockInfo::Name
Name - The name of the block, kindof.
Definition at line 155 of file CGBlocks.h.
NeedsCopyDispose
bool clang::CodeGen::CGBlockInfo::NeedsCopyDispose
True if the block has captures that would necessitate custom copy or dispose helper functions if the block were escaping.
Definition at line 222 of file CGBlocks.h.
Referenced by computeBlockInfo(), and needsCopyDisposeHelpers().
NextBlockInfo
CGBlockInfo* clang::CodeGen::CGBlockInfo::NextBlockInfo
The next block in the block-info chain.
Invalid if this block info is not part of the CGF's block-info chain, which is true if it corresponds to a global block or a block whose expression has been encountered.
Definition at line 264 of file CGBlocks.h.
StructureType
llvm::StructType* clang::CodeGen::CGBlockInfo::StructureType
Definition at line 245 of file CGBlocks.h.
Referenced by computeBlockInfo(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockDeclRefVariable(), and clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable().
UsesStret
bool clang::CodeGen::CGBlockInfo::UsesStret mutable
UsesStret : True if the block uses an stret return.
Mutable because it gets set later in the block-creation process.
Definition at line 230 of file CGBlocks.h.
Referenced by buildGlobalBlock().
The documentation for this class was generated from the following files:
lib/CodeGen/CGBlocks.h
lib/CodeGen/CGBlocks.cpp