clang: clang::serialization::reader::ASTSelectorLookupTrait Class Reference
clang::serialization::reader::ASTSelectorLookupTrait Class Reference
Class that performs lookup for a selector's entries in the global method pool stored in an AST file.
#include "/root/llvm-project/clang/lib/Serialization/ASTReaderInternals.h"
Classes
struct data_type
Public Types
using external_key_type = Selector
using internal_key_type = external_key_type
using hash_value_type = unsigned
using offset_type = unsigned
Public Member Functions
ASTSelectorLookupTrait (ASTReader &Reader, ModuleFile &F)
internal_key_type ReadKey (const unsigned char *d, unsigned)
data_type ReadData (Selector, const unsigned char *d, unsigned DataLen)
Static Public Member Functions
static bool EqualKey (const internal_key_type &a, const internal_key_type &b)
static hash_value_type ComputeHash (Selector Sel)
static const internal_key_type & GetInternalKey (const external_key_type &x)
static std::pair< unsigned, unsigned > ReadKeyDataLength (const unsigned char *&d)
Detailed Description
Class that performs lookup for a selector's entries in the global method pool stored in an AST file.
Definition at line 191 of file ASTReaderInternals.h.
Member Typedef Documentation
external_key_type
using clang::serialization::reader::ASTSelectorLookupTrait::external_key_type = Selector
Definition at line 206 of file ASTReaderInternals.h.
hash_value_type
using clang::serialization::reader::ASTSelectorLookupTrait::hash_value_type = unsigned
Definition at line 208 of file ASTReaderInternals.h.
internal_key_type
using clang::serialization::reader::ASTSelectorLookupTrait::internal_key_type = external_key_type
Definition at line 207 of file ASTReaderInternals.h.
offset_type
using clang::serialization::reader::ASTSelectorLookupTrait::offset_type = unsigned
Definition at line 209 of file ASTReaderInternals.h.
Constructor & Destructor Documentation
ASTSelectorLookupTrait()
clang::serialization::reader::ASTSelectorLookupTrait::ASTSelectorLookupTrait (ASTReader & Reader, ModuleFile & F) inline
Definition at line 211 of file ASTReaderInternals.h.
Member Function Documentation
ComputeHash()
unsigned ASTSelectorLookupTrait::ComputeHash (Selector Sel) static
Definition at line 821 of file ASTReader.cpp.
References clang::serialization::ComputeHash().
EqualKey()
static bool clang::serialization::reader::ASTSelectorLookupTrait::EqualKey (const internal_key_type & a, const internal_key_type & b) inline static
Definition at line 214 of file ASTReaderInternals.h.
References b.
GetInternalKey()
static const internal_key_type & clang::serialization::reader::ASTSelectorLookupTrait::GetInternalKey (const external_key_type & x) inline static
Definition at line 222 of file ASTReaderInternals.h.
ReadData()
ASTSelectorLookupTrait::data_type ASTSelectorLookupTrait::ReadData (Selector , const unsigned char * d, unsigned DataLen)
Definition at line 857 of file ASTReader.cpp.
References clang::serialization::reader::ASTSelectorLookupTrait::data_type::ID, and clang::Result.
ReadKey()
ASTSelectorLookupTrait::internal_key_type ASTSelectorLookupTrait::ReadKey (const unsigned char * d, unsigned)
Definition at line 835 of file ASTReader.cpp.
References clang::SelectorTable::getNullarySelector(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), and N.
Referenced by clang::ASTReader::DecodeSelector().
ReadKeyDataLength()
std::pair< unsigned, unsigned > ASTSelectorLookupTrait::ReadKeyDataLength (const unsigned char *& d) static
Definition at line 826 of file ASTReader.cpp.
The documentation for this class was generated from the following files:
lib/Serialization/ASTReaderInternals.h
lib/Serialization/ASTReader.cpp