clang: clang::DependentDiagnostic Class Reference
clang::DependentDiagnostic Class Reference
A dependently-generated diagnostic.
#include "clang/AST/DependentDiagnostic.h"
Public Types
enum AccessNonce { Access = 0 }
Public Member Functions
unsigned getKind () const
bool isAccessToMember () const
AccessSpecifier getAccess () const
SourceLocation getAccessLoc () const
NamedDecl * getAccessTarget () const
NamedDecl * getAccessNamingClass () const
QualType getAccessBaseObjectType () const
const PartialDiagnostic & getDiagnostic () const
Static Public Member Functions
static DependentDiagnostic * Create (ASTContext &Context, DeclContext *Parent, AccessNonce _, SourceLocation Loc, bool IsMemberAccess, AccessSpecifier AS, NamedDecl *TargetDecl, CXXRecordDecl *NamingClass, QualType BaseObjectType, const PartialDiagnostic &PDiag)
Friends
class DeclContext::ddiag_iterator
class DependentStoredDeclsMap
Detailed Description
A dependently-generated diagnostic.
Definition at line 36 of file DependentDiagnostic.h.
Member Enumeration Documentation
AccessNonce
enum clang::DependentDiagnostic::AccessNonce
Enumerator
Access
Definition at line 38 of file DependentDiagnostic.h.
Member Function Documentation
Create()
static DependentDiagnostic * clang::DependentDiagnostic::Create (ASTContext & Context, DeclContext * Parent, AccessNonce _, SourceLocation Loc, bool IsMemberAccess, AccessSpecifier AS, NamedDecl * TargetDecl, CXXRecordDecl * NamingClass, QualType BaseObjectType, const PartialDiagnostic & PDiag) inline static
Definition at line 40 of file DependentDiagnostic.h.
References Access, BaseObjectType, Create(), IsMember, Loc, NamingClass, Parent, and TargetDecl.
Referenced by Create(), and DelayDependentAccess().
getAccess()
AccessSpecifier clang::DependentDiagnostic::getAccess () const inline
Definition at line 69 of file DependentDiagnostic.h.
References Access, and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
getAccessBaseObjectType()
QualType clang::DependentDiagnostic::getAccessBaseObjectType () const inline
Definition at line 89 of file DependentDiagnostic.h.
References Access, clang::QualType::getFromOpaquePtr(), and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
getAccessLoc()
SourceLocation clang::DependentDiagnostic::getAccessLoc () const inline
Definition at line 74 of file DependentDiagnostic.h.
References Access, and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
getAccessNamingClass()
NamedDecl * clang::DependentDiagnostic::getAccessNamingClass () const inline
Definition at line 84 of file DependentDiagnostic.h.
References Access, and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
getAccessTarget()
NamedDecl * clang::DependentDiagnostic::getAccessTarget () const inline
Definition at line 79 of file DependentDiagnostic.h.
References Access, and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
getDiagnostic()
const PartialDiagnostic & clang::DependentDiagnostic::getDiagnostic () const inline
Definition at line 94 of file DependentDiagnostic.h.
Referenced by clang::Sema::HandleDependentAccessCheck().
getKind()
unsigned clang::DependentDiagnostic::getKind () const inline
Definition at line 60 of file DependentDiagnostic.h.
References Access.
Referenced by getAccess(), getAccessBaseObjectType(), getAccessLoc(), getAccessNamingClass(), getAccessTarget(), and isAccessToMember().
isAccessToMember()
bool clang::DependentDiagnostic::isAccessToMember () const inline
Definition at line 64 of file DependentDiagnostic.h.
References Access, and getKind().
Referenced by clang::Sema::HandleDependentAccessCheck().
Friends And Related Symbol Documentation
DeclContext::ddiag_iterator
friend class DeclContext::ddiag_iterator friend
Definition at line 99 of file DependentDiagnostic.h.
DependentStoredDeclsMap
friend class DependentStoredDeclsMap friend
Definition at line 100 of file DependentDiagnostic.h.
Member Data Documentation
Access
unsigned clang::DependentDiagnostic::Access
Definition at line 116 of file DependentDiagnostic.h.
Referenced by Create(), DelayDependentAccess(), getAccess(), getAccessBaseObjectType(), getAccessLoc(), getAccessNamingClass(), getAccessTarget(), getKind(), isAccessToMember(), and clang::Sema::PerformDependentDiagnostics().
BaseObjectType
void* clang::DependentDiagnostic::BaseObjectType
Definition at line 120 of file DependentDiagnostic.h.
Referenced by Create().
IsMember
unsigned clang::DependentDiagnostic::IsMember
Definition at line 117 of file DependentDiagnostic.h.
Referenced by Create().
Loc
SourceLocation clang::DependentDiagnostic::Loc
Definition at line 115 of file DependentDiagnostic.h.
Referenced by Create().
NamingClass
CXXRecordDecl* clang::DependentDiagnostic::NamingClass
Definition at line 119 of file DependentDiagnostic.h.
Referenced by Create().
TargetDecl
NamedDecl* clang::DependentDiagnostic::TargetDecl
Definition at line 118 of file DependentDiagnostic.h.
Referenced by Create().
The documentation for this class was generated from the following files:
include/clang/AST/DependentDiagnostic.h
lib/AST/DeclBase.cpp