clang: clang::Sema::ConditionResult Class Reference
clang::Sema::ConditionResult Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
ConditionResult ()
bool isInvalid () const
std::pair< VarDecl *, Expr * > get () const
llvm::Optional< bool > getKnownValue () const
Friends
class Sema
Detailed Description
Definition at line 11726 of file Sema.h.
Constructor & Destructor Documentation
ConditionResult()
clang::Sema::ConditionResult::ConditionResult () inline
Definition at line 11746 of file Sema.h.
Member Function Documentation
get()
std::pair< VarDecl *, Expr * > clang::Sema::ConditionResult::get () const inline
Definition at line 11748 of file Sema.h.
References clang::Condition.
Referenced by clang::Sema::ActOnForStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnWhileStmt(), and clang::Sema::BuildIfStmt().
getKnownValue()
llvm::Optional< bool > clang::Sema::ConditionResult::getKnownValue () const inline
Definition at line 11752 of file Sema.h.
References clang::Sema::None.
isInvalid()
bool clang::Sema::ConditionResult::isInvalid () const inline
Definition at line 11747 of file Sema.h.
Referenced by clang::Sema::ActOnForStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnWhileStmt(), and clang::Sema::BuildIfStmt().
Friends And Related Symbol Documentation
Sema
friend class Sema friend
Definition at line 11733 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h