clang: clang::ObjCProtocolList Class Reference
clang::ObjCProtocolList Class Reference
A list of Objective-C protocols, along with the source locations at which they were referenced.
#include "clang/AST/DeclObjC.h"
Public Types
using loc_iterator = const SourceLocation *
Public Types inherited from clang::ObjCList< ObjCProtocolDecl >
using iterator
Public Member Functions
ObjCProtocolList ()=default
loc_iterator loc_begin () const
loc_iterator loc_end () const
void set (ObjCProtocolDecl *const *InList, unsigned Elts, const SourceLocation *Locs, ASTContext &Ctx)
Public Member Functions inherited from clang::ObjCList< ObjCProtocolDecl >
void set (ObjCProtocolDecl *const *InList, unsigned Elts, ASTContext &Ctx)
iterator begin () const
iterator end () const
ObjCProtocolDecl * operator[] (unsigned Idx) const
Public Member Functions inherited from clang::ObjCListBase
ObjCListBase ()=default
ObjCListBase (const ObjCListBase &)=delete
ObjCListBase & operator= (const ObjCListBase &)=delete
unsigned size () const
bool empty () const
Additional Inherited Members
Protected Member Functions inherited from clang::ObjCListBase
void set (void *const *InList, unsigned Elts, ASTContext &Ctx)
Protected Attributes inherited from clang::ObjCListBase
void ** List = nullptr
List is an array of pointers to objects that are not owned by this object.
unsigned NumElts = 0
Detailed Description
A list of Objective-C protocols, along with the source locations at which they were referenced.
Definition at line 102 of file DeclObjC.h.
Member Typedef Documentation
loc_iterator
using clang::ObjCProtocolList::loc_iterator = const SourceLocation *
Definition at line 110 of file DeclObjC.h.
Constructor & Destructor Documentation
ObjCProtocolList()
clang::ObjCProtocolList::ObjCProtocolList () default
Member Function Documentation
loc_begin()
loc_iterator clang::ObjCProtocolList::loc_begin () const inline
Definition at line 112 of file DeclObjC.h.
Referenced by clang::ObjCCategoryDecl::protocol_loc_begin(), clang::ObjCInterfaceDecl::protocol_loc_begin(), and clang::ObjCProtocolDecl::protocol_loc_begin().
loc_end()
loc_iterator clang::ObjCProtocolList::loc_end () const inline
Definition at line 113 of file DeclObjC.h.
References clang::ObjCListBase::size().
Referenced by clang::ObjCCategoryDecl::protocol_loc_end(), clang::ObjCInterfaceDecl::protocol_loc_end(), and clang::ObjCProtocolDecl::protocol_loc_end().
set()
void ObjCProtocolList::set (ObjCProtocolDecl *const * InList, unsigned Elts, const SourceLocation * Locs, ASTContext & Ctx)
Definition at line 54 of file DeclObjC.cpp.
References memcpy(), and set().
Referenced by set(), clang::ObjCCategoryDecl::setProtocolList(), clang::ObjCInterfaceDecl::setProtocolList(), and clang::ObjCProtocolDecl::setProtocolList().
The documentation for this class was generated from the following files:
include/clang/AST/DeclObjC.h
lib/AST/DeclObjC.cpp