clang: clang::LoopHintAttr Class Reference
clang::LoopHintAttr Class Reference
#include "clang/AST/Attr.h"
Public Types
enum OptionType {
Vectorize , VectorizeWidth , Interleave , InterleaveCount ,
Unroll , UnrollCount , UnrollAndJam , UnrollAndJamCount ,
PipelineDisabled , PipelineInitiationInterval , Distribute , VectorizePredicate
}
enum LoopHintState {
Enable , Disable , Numeric , FixedWidth ,
ScalableWidth , AssumeSafety , Full
}
enum Spelling {
Pragma_clang_loop = 0 , Pragma_unroll = 1 , Pragma_nounroll = 2 , Pragma_unroll_and_jam = 3 ,
Pragma_nounroll_and_jam = 4 , SpellingNotCalculated = 15
}
Public Types inherited from clang::AttributeCommonInfo
enum Syntax {
AS_GNU , AS_CXX11 , AS_C2x , AS_Declspec ,
AS_Microsoft , AS_Keyword , AS_Pragma , AS_ContextSensitiveKeyword
}
The style used to specify an attribute.
enum Kind { NoSemaHandlerAttribute , IgnoredAttribute , UnknownAttribute }
Public Member Functions
LoopHintAttr (ASTContext &Ctx, const AttributeCommonInfo &CommonInfo, OptionType Option, LoopHintState State, Expr *Value)
LoopHintAttr * clone (ASTContext &C) const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
const char * getSpelling () const
Spelling getSemanticSpelling () const
OptionType getOption () const
LoopHintState getState () const
Expr * getValue () const
void printPrettyPragma (raw_ostream &OS, const PrintingPolicy &Policy) const
std::string getValueString (const PrintingPolicy &Policy) const
std::string getDiagnosticName (const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::Attr
void * operator new (size_t Bytes, ASTContext &C, size_t Alignment=8) noexcept
void operator delete (void *Ptr, ASTContext &C, size_t Alignment) noexcept
attr::Kind getKind () const
unsigned getSpellingListIndex () const
const char * getSpelling () const
SourceLocation getLocation () const
bool isInherited () const
bool isImplicit () const
Returns true if the attribute has been implicitly created instead of explicitly written by the user.
void setImplicit (bool I)
void setPackExpansion (bool PE)
bool isPackExpansion () const
Attr * clone (ASTContext &C) const
bool isLateParsed () const
void printPretty (raw_ostream &OS, const PrintingPolicy &Policy) const
Public Member Functions inherited from clang::AttributeCommonInfo
AttributeCommonInfo (SourceRange AttrRange)
AttributeCommonInfo (SourceLocation AttrLoc)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed)
AttributeCommonInfo (const IdentifierInfo *AttrName, const IdentifierInfo *ScopeName, SourceRange AttrRange, SourceLocation ScopeLoc, Kind AttrKind, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (const IdentifierInfo *AttrName, SourceRange AttrRange, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed)
AttributeCommonInfo (SourceRange AttrRange, Kind K, Syntax SyntaxUsed, unsigned Spelling)
AttributeCommonInfo (AttributeCommonInfo &&)=default
AttributeCommonInfo (const AttributeCommonInfo &)=default
Kind getParsedKind () const
Syntax getSyntax () const
const IdentifierInfo * getAttrName () const
SourceLocation getLoc () const
SourceRange getRange () const
void setRange (SourceRange R)
bool hasScope () const
const IdentifierInfo * getScopeName () const
SourceLocation getScopeLoc () const
std::string getNormalizedFullName () const
Gets the normalized full name, which consists of both scope and name and with surrounding underscores removed as appropriate (e.g.
bool isDeclspecAttribute () const
bool isMicrosoftAttribute () const
bool isGNUScope () const
bool isAlignasAttribute () const
bool isCXX11Attribute () const
bool isC2xAttribute () const
bool isKeywordAttribute () const
bool isContextSensitiveKeywordAttribute () const
unsigned getAttributeSpellingListIndex () const
void setAttributeSpellingListIndex (unsigned V)
Static Public Member Functions
static LoopHintAttr * CreateImplicit (ASTContext &Ctx, OptionType Option, LoopHintState State, Expr *Value, const AttributeCommonInfo &CommonInfo={SourceRange{}})
static LoopHintAttr * Create (ASTContext &Ctx, OptionType Option, LoopHintState State, Expr *Value, const AttributeCommonInfo &CommonInfo)
static LoopHintAttr * CreateImplicit (ASTContext &Ctx, OptionType Option, LoopHintState State, Expr *Value, SourceRange Range, AttributeCommonInfo::Syntax Syntax, LoopHintAttr::Spelling S=static_cast< Spelling >(SpellingNotCalculated))
static LoopHintAttr * Create (ASTContext &Ctx, OptionType Option, LoopHintState State, Expr *Value, SourceRange Range, AttributeCommonInfo::Syntax Syntax, LoopHintAttr::Spelling S=static_cast< Spelling >(SpellingNotCalculated))
static bool ConvertStrToOptionType (StringRef Val, OptionType &Out)
static const char * ConvertOptionTypeToStr (OptionType Val)
static bool ConvertStrToLoopHintState (StringRef Val, LoopHintState &Out)
static const char * ConvertLoopHintStateToStr (LoopHintState Val)
static const char * getOptionName (int Option)
static bool classof (const Attr *A)
Static Public Member Functions inherited from clang::AttributeCommonInfo
static Kind getParsedKind (const IdentifierInfo *Name, const IdentifierInfo *Scope, Syntax SyntaxUsed)
Additional Inherited Members
Protected Member Functions inherited from clang::Attr
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Attr (ASTContext &Context, const AttributeCommonInfo &CommonInfo, attr::Kind AK, bool IsLateParsed)
Protected Member Functions inherited from clang::AttributeCommonInfo
bool isAttributeSpellingListCalculated () const
Protected Attributes inherited from clang::Attr
unsigned Inherited: 1
An index into the spelling list of an attribute defined in Attr.td file.
unsigned IsPackExpansion: 1
unsigned Implicit: 1
unsigned IsLateParsed: 1
unsigned InheritEvenIfAlreadyPresent: 1
Static Protected Attributes inherited from clang::AttributeCommonInfo
static constexpr unsigned SpellingNotCalculated = 0xf
Detailed Description
Definition at line 4590 of file Attr.h.
Member Enumeration Documentation
LoopHintState
enum clang::LoopHintAttr::LoopHintState
Enumerator
Enable
Disable
Numeric
FixedWidth
ScalableWidth
AssumeSafety
Full
Definition at line 4610 of file Attr.h.
OptionType
enum clang::LoopHintAttr::OptionType
Enumerator
Vectorize
VectorizeWidth
Interleave
InterleaveCount
Unroll
UnrollCount
UnrollAndJam
UnrollAndJamCount
PipelineDisabled
PipelineInitiationInterval
Distribute
VectorizePredicate
Definition at line 4592 of file Attr.h.
Spelling
enum clang::LoopHintAttr::Spelling
Enumerator
Pragma_clang_loop
Pragma_unroll
Pragma_nounroll
Pragma_unroll_and_jam
Pragma_nounroll_and_jam
SpellingNotCalculated
Definition at line 4625 of file Attr.h.
Constructor & Destructor Documentation
LoopHintAttr()
clang::LoopHintAttr::LoopHintAttr (ASTContext & Ctx, const AttributeCommonInfo & CommonInfo, OptionType Option, LoopHintState State, Expr * Value)
Member Function Documentation
classof()
static bool clang::LoopHintAttr::classof (const Attr * A) inline static
Definition at line 4698 of file Attr.h.
clone()
LoopHintAttr * clang::LoopHintAttr::clone (ASTContext & C) const
ConvertLoopHintStateToStr()
static const char * clang::LoopHintAttr::ConvertLoopHintStateToStr (LoopHintState Val) static
ConvertOptionTypeToStr()
static const char * clang::LoopHintAttr::ConvertOptionTypeToStr (OptionType Val) static
ConvertStrToLoopHintState()
static bool clang::LoopHintAttr::ConvertStrToLoopHintState (StringRef Val, LoopHintState & Out) static
ConvertStrToOptionType()
static bool clang::LoopHintAttr::ConvertStrToOptionType (StringRef Val, OptionType & Out) static
Create() [1/2]
static LoopHintAttr * clang::LoopHintAttr::Create (ASTContext & Ctx, OptionType Option, LoopHintState State, Expr * Value, const AttributeCommonInfo & CommonInfo) static
Create() [2/2]
static LoopHintAttr * clang::LoopHintAttr::Create (ASTContext & Ctx, OptionType Option, LoopHintState State, Expr * Value, SourceRange Range, AttributeCommonInfo::Syntax Syntax, LoopHintAttr::Spelling S = static_cast< Spelling >(SpellingNotCalculated)) static
CreateImplicit() [1/2]
static LoopHintAttr * clang::LoopHintAttr::CreateImplicit (ASTContext & Ctx, OptionType Option, LoopHintState State, Expr * Value, const AttributeCommonInfo & CommonInfo = {SourceRange{}}) static
Referenced by handleLoopHintAttr().
CreateImplicit() [2/2]
static LoopHintAttr * clang::LoopHintAttr::CreateImplicit (ASTContext & Ctx, OptionType Option, LoopHintState State, Expr * Value, SourceRange Range, AttributeCommonInfo::Syntax Syntax, LoopHintAttr::Spelling S = static_cast< Spelling >(SpellingNotCalculated)) static
getDiagnosticName()
std::string LoopHintAttr::getDiagnosticName (const PrintingPolicy & Policy) const
Definition at line 68 of file AttrImpl.cpp.
References clang::AttributeCommonInfo::getAttributeSpellingListIndex(), getOptionName(), getValueString(), Pragma_clang_loop, Pragma_nounroll, Pragma_nounroll_and_jam, Pragma_unroll, Pragma_unroll_and_jam, UnrollAndJamCount, and UnrollCount.
Referenced by CheckForIncompatibleAttributes().
getOption()
OptionType clang::LoopHintAttr::getOption () const inline
Definition at line 4653 of file Attr.h.
Referenced by CheckForIncompatibleAttributes().
getOptionName()
static const char * clang::LoopHintAttr::getOptionName (int Option) inline static
Definition at line 4670 of file Attr.h.
Referenced by getDiagnosticName(), and printPrettyPragma().
getSemanticSpelling()
Spelling clang::LoopHintAttr::getSemanticSpelling () const
getSpelling()
const char * clang::LoopHintAttr::getSpelling () const
getState()
LoopHintState clang::LoopHintAttr::getState () const inline
Definition at line 4659 of file Attr.h.
getValue()
Expr * clang::LoopHintAttr::getValue () const inline
Definition at line 4665 of file Attr.h.
getValueString()
std::string LoopHintAttr::getValueString (const PrintingPolicy & Policy) const
Definition at line 39 of file AttrImpl.cpp.
References AssumeSafety, Enable, FixedWidth, Full, Numeric, clang::Stmt::printPretty(), and ScalableWidth.
Referenced by getDiagnosticName(), and printPrettyPragma().
printPretty()
void clang::LoopHintAttr::printPretty (raw_ostream & OS, const PrintingPolicy & Policy) const
printPrettyPragma()
void LoopHintAttr::printPrettyPragma (raw_ostream & OS, const PrintingPolicy & Policy) const
Definition at line 19 of file AttrImpl.cpp.
References clang::AttributeCommonInfo::getAttributeSpellingListIndex(), getOptionName(), getValueString(), Pragma_clang_loop, Pragma_nounroll, Pragma_nounroll_and_jam, Pragma_unroll, and Pragma_unroll_and_jam.
The documentation for this class was generated from the following files:
include/clang/AST/Attr.h
lib/AST/AttrImpl.cpp