clang: clang::ExternalPreprocessorSource Class Reference
clang::ExternalPreprocessorSource Class Reference abstract
Abstract interface for external sources of preprocessor information.
#include "clang/Lex/ExternalPreprocessorSource.h"
Public Member Functions
virtual ~ExternalPreprocessorSource ()
virtual void ReadDefinedMacros ()=0
Read the set of macros defined by this external macro source.
virtual void updateOutOfDateIdentifier (IdentifierInfo &II)=0
Update an out-of-date identifier.
virtual IdentifierInfo * GetIdentifier (unsigned ID)=0
Return the identifier associated with the given ID number.
virtual Module * getModule (unsigned ModuleID)=0
Map a module ID to a module.
Detailed Description
Abstract interface for external sources of preprocessor information.
This abstract class allows an external sources (such as the ASTReader) to provide additional preprocessing information.
Definition at line 26 of file ExternalPreprocessorSource.h.
Constructor & Destructor Documentation
~ExternalPreprocessorSource()
ExternalPreprocessorSource::~ExternalPreprocessorSource () virtual default
Member Function Documentation
GetIdentifier()
virtual IdentifierInfo * clang::ExternalPreprocessorSource::GetIdentifier (unsigned ID) pure virtual
Return the identifier associated with the given ID number.
The ID 0 is associated with the NULL identifier.
getModule()
virtual Module * clang::ExternalPreprocessorSource::getModule (unsigned ModuleID) pure virtual
Map a module ID to a module.
Implemented in clang::ASTReader.
ReadDefinedMacros()
virtual void clang::ExternalPreprocessorSource::ReadDefinedMacros () pure virtual
Read the set of macros defined by this external macro source.
Implemented in clang::ASTReader.
Referenced by clang::Preprocessor::macro_begin(), and clang::Preprocessor::macro_end().
updateOutOfDateIdentifier()
virtual void clang::ExternalPreprocessorSource::updateOutOfDateIdentifier (IdentifierInfo & II) pure virtual
Update an out-of-date identifier.
Implemented in clang::ASTReader.
Referenced by isTrivialSingleTokenExpansion().
The documentation for this class was generated from the following files:
include/clang/Lex/ExternalPreprocessorSource.h
lib/Lex/Preprocessor.cpp