clang: clang::analyze_format_string::SpecifierResult< T > Class Template Reference
clang::analyze_format_string::SpecifierResult< T > Class Template Reference
#include "/root/llvm-project/clang/lib/AST/FormatStringParsing.h"
Public Member Functions
SpecifierResult (bool stop=false)
SpecifierResult (const char *start, const T &fs)
const char * getStart () const
bool shouldStop () const
bool hasValue () const
const T & getValue () const
const T & getValue ()
Detailed Description
template<typename T>
class clang::analyze_format_string::SpecifierResult< T >
Definition at line 72 of file FormatStringParsing.h.
Constructor & Destructor Documentation
SpecifierResult() [1/2]
template<typename T > clang::analyze_format_string::SpecifierResult< T >::SpecifierResult (bool stop = false) inline
Definition at line 77 of file FormatStringParsing.h.
SpecifierResult() [2/2]
template<typename T > clang::analyze_format_string::SpecifierResult< T >::SpecifierResult (const char * start, const T & fs) inline
Definition at line 79 of file FormatStringParsing.h.
Member Function Documentation
getStart()
template<typename T > const char * clang::analyze_format_string::SpecifierResult< T >::getStart () const inline
Definition at line 83 of file FormatStringParsing.h.
Referenced by clang::analyze_format_string::ParsePrintfString(), and clang::analyze_format_string::ParseScanfString().
getValue() [1/2]
template<typename T > const T & clang::analyze_format_string::SpecifierResult< T >::getValue () inline
Definition at line 90 of file FormatStringParsing.h.
getValue() [2/2]
template<typename T > const T & clang::analyze_format_string::SpecifierResult< T >::getValue () const inline
Definition at line 86 of file FormatStringParsing.h.
References clang::analyze_format_string::SpecifierResult< T >::hasValue().
Referenced by clang::analyze_format_string::ParseFormatStringHasSArg(), clang::analyze_format_string::ParsePrintfString(), and clang::analyze_format_string::ParseScanfString().
hasValue()
template<typename T > bool clang::analyze_format_string::SpecifierResult< T >::hasValue () const inline
Definition at line 85 of file FormatStringParsing.h.
Referenced by clang::analyze_format_string::SpecifierResult< T >::getValue(), clang::analyze_format_string::parseFormatStringHasFormattingSpecifiers(), clang::analyze_format_string::ParseFormatStringHasSArg(), clang::analyze_format_string::ParsePrintfString(), and clang::analyze_format_string::ParseScanfString().
shouldStop()
template<typename T > bool clang::analyze_format_string::SpecifierResult< T >::shouldStop () const inline
Definition at line 84 of file FormatStringParsing.h.
Referenced by clang::analyze_format_string::parseFormatStringHasFormattingSpecifiers(), clang::analyze_format_string::ParseFormatStringHasSArg(), clang::analyze_format_string::ParsePrintfString(), and clang::analyze_format_string::ParseScanfString().
The documentation for this class was generated from the following file:
lib/AST/FormatStringParsing.h