clang: clang::syntax::Tree Class Reference
clang::syntax::Tree Class Reference
A node that has children and represents a syntactic language construct.
#include "clang/Tooling/Syntax/Tree.h"
Classes
struct ChildIterator
child_iterator is not invalidated by mutations.
struct ConstChildIterator
Public Member Functions
Node * getFirstChild ()
const Node * getFirstChild () const
Node * getLastChild ()
const Node * getLastChild () const
const Leaf * findFirstLeaf () const
Leaf * findFirstLeaf ()
const Leaf * findLastLeaf () const
Leaf * findLastLeaf ()
llvm::iterator_range< ChildIterator > getChildren ()
llvm::iterator_range< ConstChildIterator > getChildren () const
const Node * findChild (NodeRole R) const
Find the first node with a corresponding role.
Node * findChild (NodeRole R)
Public Member Functions inherited from clang::syntax::Node
Node (const Node &)=delete
Nodes cannot simply be copied without violating tree invariants.
Node & operator= (const Node &)=delete
Node (Node &&)=delete
Idiomatically, nodes are allocated on an Arena and never moved.
Node & operator= (Node &&)=delete
NodeKind getKind () const
NodeRole getRole () const
bool isDetached () const
Whether the node is detached from a tree, i.e. does not have a parent.
bool isOriginal () const
Whether the node was created from the AST backed by the source code rather than added later through mutation APIs or created with factory functions.
bool canModify () const
If this function return false, the tree cannot be modified because there is no reasonable way to produce the corresponding textual replacements.
const Tree * getParent () const
Tree * getParent ()
const Node * getNextSibling () const
Node * getNextSibling ()
const Node * getPreviousSibling () const
Node * getPreviousSibling ()
std::string dump (const SourceManager &SM) const
Dumps the structure of a subtree. For debugging and testing purposes.
std::string dumpTokens (const SourceManager &SM) const
Dumps the tokens forming this subtree.
void assertInvariants () const
Asserts invariants on this node of the tree and its immediate children.
void assertInvariantsRecursive () const
Runs checkInvariants on all nodes in the subtree. No-op if NDEBUG is set.
Static Public Member Functions
static bool classof (const Node *N)
Protected Member Functions
Node (NodeKind Kind)
Newly created nodes are detached from a tree, parent and sibling links are set when the node is added as a child to another one.
Node (const Node &)=delete
Nodes cannot simply be copied without violating tree invariants.
Node (Node &&)=delete
Idiomatically, nodes are allocated on an Arena and never moved.
Protected Member Functions inherited from clang::syntax::Node
Node (NodeKind Kind)
Newly created nodes are detached from a tree, parent and sibling links are set when the node is added as a child to another one.
~Node ()=default
Nodes are allocated on Arenas; the destructor is never called.
Friends
class TreeBuilder
class FactoryImpl
class MutationsImpl
Detailed Description
A node that has children and represents a syntactic language construct.
Definition at line 169 of file Tree.h.
Member Function Documentation
classof()
static bool clang::syntax::Tree::classof (const Node * N) static
findChild() [1/2]
Node * clang::syntax::Tree::findChild (NodeRole R) inline
Definition at line 236 of file Tree.h.
References findChild().
findChild() [2/2]
const syntax::Node * syntax::Tree::findChild (NodeRole R) const
Find the first node with a corresponding role.
Definition at line 332 of file Tree.cpp.
References clang::C.
Referenced by findChild().
findFirstLeaf() [1/2]
Leaf * clang::syntax::Tree::findFirstLeaf () inline
Definition at line 207 of file Tree.h.
References findFirstLeaf().
findFirstLeaf() [2/2]
const syntax::Leaf * syntax::Tree::findFirstLeaf () const
Definition at line 312 of file Tree.cpp.
References clang::C.
Referenced by findFirstLeaf().
findLastLeaf() [1/2]
Leaf * clang::syntax::Tree::findLastLeaf () inline
Definition at line 212 of file Tree.h.
References findLastLeaf().
findLastLeaf() [2/2]
const syntax::Leaf * syntax::Tree::findLastLeaf () const
Definition at line 322 of file Tree.cpp.
References clang::C.
Referenced by findLastLeaf().
getChildren() [1/2]
llvm::iterator_range< ChildIterator > clang::syntax::Tree::getChildren () inline
Definition at line 227 of file Tree.h.
References getFirstChild().
getChildren() [2/2]
llvm::iterator_range< ConstChildIterator > clang::syntax::Tree::getChildren () const inline
Definition at line 230 of file Tree.h.
References getFirstChild().
getFirstChild() [1/2]
Node * clang::syntax::Tree::getFirstChild () inline
Definition at line 201 of file Tree.h.
Referenced by getChildren(), and getChildren().
getFirstChild() [2/2]
const Node * clang::syntax::Tree::getFirstChild () const inline
Definition at line 202 of file Tree.h.
getLastChild() [1/2]
Node * clang::syntax::Tree::getLastChild () inline
Definition at line 203 of file Tree.h.
getLastChild() [2/2]
const Node * clang::syntax::Tree::getLastChild () const inline
Definition at line 204 of file Tree.h.
Node() [1/3]
clang::syntax::Node::Node (const Node &) protected delete
Nodes cannot simply be copied without violating tree invariants.
Node() [2/3]
clang::syntax::Node::Node (Node &&) protected delete
Idiomatically, nodes are allocated on an Arena and never moved.
Node() [3/3]
syntax::Node::Node (NodeKind Kind) protected
Newly created nodes are detached from a tree, parent and sibling links are set when the node is added as a child to another one.
Definition at line 84 of file Tree.cpp.
Friends And Related Symbol Documentation
FactoryImpl
friend class FactoryImpl friend
Definition at line 257 of file Tree.h.
MutationsImpl
friend class MutationsImpl friend
Definition at line 266 of file Tree.h.
TreeBuilder
friend class TreeBuilder friend
Definition at line 256 of file Tree.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/Syntax/Tree.h
lib/Tooling/Syntax/Tree.cpp