clang: clang::LocationContextManager Class Reference
clang::LocationContextManager Class Reference
#include "clang/Analysis/AnalysisDeclContext.h"
Public Member Functions
~LocationContextManager ()
const StackFrameContext * getStackFrame (AnalysisDeclContext *ADC, const LocationContext *ParentLC, const Stmt *S, const CFGBlock *Block, unsigned BlockCount, unsigned Index)
Obtain a context of the call stack using its parent context.
const BlockInvocationContext * getBlockInvocationContext (AnalysisDeclContext *ADC, const LocationContext *ParentLC, const BlockDecl *BD, const void *Data)
Obtain a context of the block invocation using its parent context.
void clear ()
Discard all previously created LocationContext objects.
Detailed Description
Definition at line 381 of file AnalysisDeclContext.h.
Constructor & Destructor Documentation
~LocationContextManager()
LocationContextManager::~LocationContextManager ()
Definition at line 641 of file AnalysisDeclContext.cpp.
References clear().
Member Function Documentation
clear()
void LocationContextManager::clear ()
Discard all previously created LocationContext objects.
Definition at line 645 of file AnalysisDeclContext.cpp.
Referenced by ~LocationContextManager().
getBlockInvocationContext()
const BlockInvocationContext * LocationContextManager::getBlockInvocationContext (AnalysisDeclContext * ADC, const LocationContext * ParentLC, const BlockDecl * BD, const void * Data)
Obtain a context of the block invocation using its parent context.
Parameters
ADC The AnalysisDeclContext.
ParentLC The parent context of this newly created context.
BD The BlockDecl.
Data The raw data to store as part of the context.
Definition at line 390 of file AnalysisDeclContext.cpp.
References clang::BlockInvocationContext::Profile().
Referenced by clang::AnalysisDeclContext::getBlockInvocationContext().
getStackFrame()
const StackFrameContext * LocationContextManager::getStackFrame (AnalysisDeclContext * ADC, const LocationContext * ParentLC, const Stmt * S, const CFGBlock * Block, unsigned BlockCount, unsigned Index)
Obtain a context of the call stack using its parent context.
Parameters
ADC The AnalysisDeclContext.
ParentLC The parent context of this newly created context.
S The call.
Block The basic block.
BlockCount The current count of entering into Blk.
Index The index of Blk.
Returns
The context for D with parent context ParentLC.
Definition at line 375 of file AnalysisDeclContext.cpp.
References clang::StackFrameContext::Profile(), and s.
Referenced by clang::AnalysisDeclContext::getStackFrame(), clang::AnalysisDeclContextManager::getStackFrame(), and clang::AnalysisDeclContextManager::getStackFrame().
The documentation for this class was generated from the following files:
include/clang/Analysis/AnalysisDeclContext.h
lib/Analysis/AnalysisDeclContext.cpp