clang: clang::CoroutineBodyStmt Class Reference
clang::CoroutineBodyStmt Class Reference final
Represents the body of a coroutine.
#include "clang/AST/StmtCXX.h"
Classes
struct CtorArgs
Public Member Functions
bool hasDependentPromiseType () const
Stmt * getBody () const
Retrieve the body of the coroutine as written.
Stmt * getPromiseDeclStmt () const
VarDecl * getPromiseDecl () const
Stmt * getInitSuspendStmt () const
Stmt * getFinalSuspendStmt () const
Stmt * getExceptionHandler () const
Stmt * getFallthroughHandler () const
Expr * getAllocate () const
Expr * getDeallocate () const
Expr * getReturnValueInit () const
Stmt * getResultDecl () const
Stmt * getReturnStmt () const
Stmt * getReturnStmtOnAllocFailure () const
ArrayRef< Stmt const * > getParamMoves () const
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CoroutineBodyStmt * Create (const ASTContext &C, CtorArgs const &Args)
static CoroutineBodyStmt * Create (const ASTContext &C, EmptyShell, unsigned NumParams)
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
class ASTReader
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpessions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range<child_iterator>
using const_child_range = llvm::iterator_range<const_child_iterator>
Public Attributes inherited from clang::Stmt
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator<T, const T *const, const Stmt *const>
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator<Expr>
using ConstExprIterator = ConstCastIterator<Expr>
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
Represents the body of a coroutine.
This wraps the normal function body and holds the additional semantic context required to set up and tear down the coroutine frame.
Definition at line 317 of file StmtCXX.h.
Member Function Documentation
children() [1/2]
child_range clang::CoroutineBodyStmt::children () inline
Definition at line 429 of file StmtCXX.h.
children() [2/2]
const_child_range clang::CoroutineBodyStmt::children () const inline
Definition at line 434 of file StmtCXX.h.
classof()
static bool clang::CoroutineBodyStmt::classof (const Stmt * T) inline static
Definition at line 440 of file StmtCXX.h.
Create() [1/2]
CoroutineBodyStmt * CoroutineBodyStmt::Create (const ASTContext & C, CoroutineBodyStmt::CtorArgs const & Args) static
Definition at line 86 of file StmtCXX.cpp.
References clang::C, and clang::CoroutineBodyStmt::CtorArgs::ParamMoves.
Referenced by clang::Sema::BuildCoroutineBodyStmt(), and clang::Sema::CheckCompletedCoroutineBody().
Create() [2/2]
CoroutineBodyStmt * CoroutineBodyStmt::Create (const ASTContext & C, EmptyShell , unsigned NumParams) static
Definition at line 95 of file StmtCXX.cpp.
References clang::C, and clang::Result.
getAllocate()
Expr * clang::CoroutineBodyStmt::getAllocate () const inline
Definition at line 403 of file StmtCXX.h.
getBeginLoc()
SourceLocation clang::CoroutineBodyStmt::getBeginLoc () const inline
Definition at line 421 of file StmtCXX.h.
References clang::DeclaratorDecl::getBeginLoc(), clang::Stmt::getBeginLoc(), getBody(), and getPromiseDecl().
getBody()
Stmt * clang::CoroutineBodyStmt::getBody () const inline
Retrieve the body of the coroutine as written.
This will be either a CompoundStmt or a TryStmt.
Definition at line 378 of file StmtCXX.h.
Referenced by getBeginLoc(), and getEndLoc().
getDeallocate()
Expr * clang::CoroutineBodyStmt::getDeallocate () const inline
Definition at line 406 of file StmtCXX.h.
getEndLoc()
SourceLocation clang::CoroutineBodyStmt::getEndLoc () const inline
Definition at line 425 of file StmtCXX.h.
References getBody(), clang::Decl::getEndLoc(), clang::Stmt::getEndLoc(), and getPromiseDecl().
getExceptionHandler()
Stmt * clang::CoroutineBodyStmt::getExceptionHandler () const inline
Definition at line 396 of file StmtCXX.h.
getFallthroughHandler()
Stmt * clang::CoroutineBodyStmt::getFallthroughHandler () const inline
Definition at line 399 of file StmtCXX.h.
getFinalSuspendStmt()
Stmt * clang::CoroutineBodyStmt::getFinalSuspendStmt () const inline
Definition at line 392 of file StmtCXX.h.
getInitSuspendStmt()
Stmt * clang::CoroutineBodyStmt::getInitSuspendStmt () const inline
Definition at line 389 of file StmtCXX.h.
getParamMoves()
ArrayRef< Stmt const * > clang::CoroutineBodyStmt::getParamMoves () const inline
Definition at line 417 of file StmtCXX.h.
getPromiseDecl()
VarDecl * clang::CoroutineBodyStmt::getPromiseDecl () const inline
Definition at line 385 of file StmtCXX.h.
References clang::cast(), and getPromiseDeclStmt().
Referenced by getBeginLoc(), getEndLoc(), and hasDependentPromiseType().
getPromiseDeclStmt()
Stmt * clang::CoroutineBodyStmt::getPromiseDeclStmt () const inline
Definition at line 382 of file StmtCXX.h.
Referenced by getPromiseDecl().
getResultDecl()
Stmt * clang::CoroutineBodyStmt::getResultDecl () const inline
Definition at line 412 of file StmtCXX.h.
getReturnStmt()
Stmt * clang::CoroutineBodyStmt::getReturnStmt () const inline
Definition at line 413 of file StmtCXX.h.
getReturnStmtOnAllocFailure()
Stmt * clang::CoroutineBodyStmt::getReturnStmtOnAllocFailure () const inline
Definition at line 414 of file StmtCXX.h.
getReturnValueInit()
Expr * clang::CoroutineBodyStmt::getReturnValueInit () const inline
Definition at line 409 of file StmtCXX.h.
References clang::cast().
hasDependentPromiseType()
bool clang::CoroutineBodyStmt::hasDependentPromiseType () const inline
Definition at line 372 of file StmtCXX.h.
References getPromiseDecl(), clang::ValueDecl::getType(), and clang::Type::isDependentType().
Friends And Related Symbol Documentation
ASTReader
friend class ASTReader friend
Definition at line 338 of file StmtCXX.h.
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 337 of file StmtCXX.h.
The documentation for this class was generated from the following files:
include/clang/AST/StmtCXX.h
lib/AST/StmtCXX.cpp