clang: clang::analyze_format_string::OptionalFlag Class Reference
clang::analyze_format_string::OptionalFlag Class Reference
Class representing optional flags with location and representation information.
#include "clang/AST/FormatString.h"
Public Member Functions
OptionalFlag (const char *Representation)
bool isSet () const
void set ()
void clear ()
void setPosition (const char *position)
const char * getPosition () const
const char * toString () const
operator bool () const
OptionalFlag & operator= (const bool &rhs)
Detailed Description
Class representing optional flags with location and representation information.
Definition at line 33 of file FormatString.h.
Constructor & Destructor Documentation
OptionalFlag()
clang::analyze_format_string::OptionalFlag::OptionalFlag (const char * Representation) inline
Definition at line 35 of file FormatString.h.
Member Function Documentation
clear()
void clang::analyze_format_string::OptionalFlag::clear () inline
Definition at line 39 of file FormatString.h.
getPosition()
const char * clang::analyze_format_string::OptionalFlag::getPosition () const inline
Definition at line 45 of file FormatString.h.
isSet()
bool clang::analyze_format_string::OptionalFlag::isSet () const inline
Definition at line 37 of file FormatString.h.
operator bool()
clang::analyze_format_string::OptionalFlag::operator bool () const inline explicit
Definition at line 52 of file FormatString.h.
operator=()
OptionalFlag & clang::analyze_format_string::OptionalFlag::operator= (const bool & rhs) inline
Definition at line 53 of file FormatString.h.
set()
void clang::analyze_format_string::OptionalFlag::set () inline
Definition at line 38 of file FormatString.h.
setPosition()
void clang::analyze_format_string::OptionalFlag::setPosition (const char * position) inline
Definition at line 40 of file FormatString.h.
Referenced by clang::analyze_printf::PrintfSpecifier::setHasAlternativeForm(), clang::analyze_printf::PrintfSpecifier::setHasLeadingZeros(), clang::analyze_printf::PrintfSpecifier::setHasObjCTechnicalTerm(), clang::analyze_printf::PrintfSpecifier::setHasPlusPrefix(), clang::analyze_printf::PrintfSpecifier::setHasSpacePrefix(), clang::analyze_printf::PrintfSpecifier::setHasThousandsGrouping(), clang::analyze_printf::PrintfSpecifier::setIsLeftJustified(), clang::analyze_printf::PrintfSpecifier::setIsPrivate(), clang::analyze_printf::PrintfSpecifier::setIsPublic(), clang::analyze_printf::PrintfSpecifier::setIsSensitive(), and clang::analyze_scanf::ScanfSpecifier::setSuppressAssignment().
toString()
const char * clang::analyze_format_string::OptionalFlag::toString () const inline
Definition at line 49 of file FormatString.h.
The documentation for this class was generated from the following file:
include/clang/AST/FormatString.h