clang: clang::TextDiagnostic Class Reference
clang::TextDiagnostic Class Reference
Class to encapsulate the logic for formatting and printing a textual diagnostic message.
#include "clang/Frontend/TextDiagnostic.h"
Public Member Functions
TextDiagnostic (raw_ostream &OS, const LangOptions &LangOpts, DiagnosticOptions *DiagOpts)
~TextDiagnostic () override
Public Member Functions inherited from clang::DiagnosticRenderer
void emitDiagnostic (FullSourceLoc Loc, DiagnosticsEngine::Level Level, StringRef Message, ArrayRef< CharSourceRange > Ranges, ArrayRef< FixItHint > FixItHints, DiagOrStoredDiag D=(Diagnostic *) nullptr)
Emit a diagnostic.
void emitStoredDiagnostic (StoredDiagnostic &Diag)
Static Public Member Functions
static void printDiagnosticLevel (raw_ostream &OS, DiagnosticsEngine::Level Level, bool ShowColors, bool CLFallbackMode=false)
Print the diagonstic level to a raw_ostream.
static void printDiagnosticMessage (raw_ostream &OS, bool IsSupplemental, StringRef Message, unsigned CurrentColumn, unsigned Columns, bool ShowColors)
Pretty-print a diagnostic message to a raw_ostream.
Protected Member Functions
void emitDiagnosticMessage (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, StringRef Message, ArrayRef< CharSourceRange > Ranges, DiagOrStoredDiag D) override
void emitDiagnosticLoc (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, ArrayRef< CharSourceRange > Ranges) override
Print out the file/line/column information and include trace.
void emitCodeContext (FullSourceLoc Loc, DiagnosticsEngine::Level Level, SmallVectorImpl< CharSourceRange > &Ranges, ArrayRef< FixItHint > Hints) override
void emitIncludeLocation (FullSourceLoc Loc, PresumedLoc PLoc) override
void emitImportLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override
void emitBuildingModuleLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override
Protected Member Functions inherited from clang::DiagnosticRenderer
DiagnosticRenderer (const LangOptions &LangOpts, DiagnosticOptions *DiagOpts)
virtual ~DiagnosticRenderer ()
virtual void beginDiagnostic (DiagOrStoredDiag D, DiagnosticsEngine::Level Level)
virtual void endDiagnostic (DiagOrStoredDiag D, DiagnosticsEngine::Level Level)
Additional Inherited Members
Protected Attributes inherited from clang::DiagnosticRenderer
const LangOptions & LangOpts
IntrusiveRefCntPtr< DiagnosticOptions > DiagOpts
SourceLocation LastLoc
The location of the previous diagnostic if known.
SourceLocation LastIncludeLoc
The location of the last include whose stack was printed if known.
DiagnosticsEngine::Level LastLevel = DiagnosticsEngine::Ignored
The level of the last diagnostic emitted.
Detailed Description
Class to encapsulate the logic for formatting and printing a textual diagnostic message.
This class provides an interface for building and emitting a textual diagnostic, including all of the macro backtraces, caret diagnostics, FixIt Hints, and code snippets. In the presence of macros this involves a recursive process, synthesizing notes for each macro expansion.
The purpose of this class is to isolate the implementation of printing beautiful text diagnostics from any particular interfaces. The Clang DiagnosticClient is implemented through this class as is diagnostic printing coming out of libclang.
Definition at line 34 of file TextDiagnostic.h.
Constructor & Destructor Documentation
TextDiagnostic()
TextDiagnostic::TextDiagnostic (raw_ostream & OS, const LangOptions & LangOpts, DiagnosticOptions * DiagOpts)
Definition at line 666 of file TextDiagnostic.cpp.
~TextDiagnostic()
TextDiagnostic::~TextDiagnostic () override
Definition at line 671 of file TextDiagnostic.cpp.
Member Function Documentation
emitBuildingModuleLocation()
void TextDiagnostic::emitBuildingModuleLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override protected virtual
Implements clang::DiagnosticRenderer.
Definition at line 926 of file TextDiagnostic.cpp.
References clang::DiagnosticRenderer::DiagOpts, clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), and clang::PresumedLoc::isValid().
emitCodeContext()
void clang::TextDiagnostic::emitCodeContext (FullSourceLoc Loc, DiagnosticsEngine::Level Level, SmallVectorImpl< CharSourceRange > & Ranges, ArrayRef< FixItHint > Hints) inline override protected virtual
Implements clang::DiagnosticRenderer.
Definition at line 86 of file TextDiagnostic.h.
emitDiagnosticLoc()
void TextDiagnostic::emitDiagnosticLoc (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, ArrayRef< CharSourceRange > Ranges) override protected virtual
Print out the file/line/column information and include trace.
This method handlen the emission of the diagnostic location information. This includes extracting as much location information as is present for the diagnostic and printing it, as well as any include stack or source ranges necessary.
Implements clang::DiagnosticRenderer.
Definition at line 805 of file TextDiagnostic.cpp.
References clang::DiagnosticOptions::Clang, clang::DiagnosticRenderer::DiagOpts, clang::PresumedLoc::getColumn(), clang::FullSourceLoc::getColumnNumber(), clang::CharSourceRange::getEnd(), clang::FullSourceLoc::getExpansionLoc(), clang::FullSourceLoc::getFileEntry(), clang::FullSourceLoc::getFileID(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::FullSourceLoc::getLineNumber(), clang::FullSourceLoc::getManager(), clang::FileEntry::getName(), clang::LangOptions::isCompatibleWithMSVC(), clang::PresumedLoc::isInvalid(), clang::CharSourceRange::isTokenRange(), clang::FileEntry::isValid(), clang::FileID::isValid(), clang::DiagnosticRenderer::LangOpts, clang::Lexer::MeasureTokenLength(), clang::DiagnosticOptions::MSVC, clang::LangOptions::MSVC2012, clang::LangOptions::MSVC2015, savedColor, SM, and clang::DiagnosticOptions::Vi.
Referenced by emitDiagnosticMessage().
emitDiagnosticMessage()
void TextDiagnostic::emitDiagnosticMessage (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, StringRef Message, ArrayRef< CharSourceRange > Ranges, DiagOrStoredDiag D) override protected virtual
Implements clang::DiagnosticRenderer.
Definition at line 673 of file TextDiagnostic.cpp.
References clang::DiagnosticRenderer::DiagOpts, emitDiagnosticLoc(), clang::SourceLocation::isValid(), clang::DiagnosticsEngine::Note, printDiagnosticLevel(), and printDiagnosticMessage().
emitImportLocation()
void TextDiagnostic::emitImportLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override protected virtual
Implements clang::DiagnosticRenderer.
Definition at line 917 of file TextDiagnostic.cpp.
References clang::DiagnosticRenderer::DiagOpts, clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), and clang::PresumedLoc::isValid().
emitIncludeLocation()
void TextDiagnostic::emitIncludeLocation (FullSourceLoc Loc, PresumedLoc PLoc) override protected virtual
Implements clang::DiagnosticRenderer.
Definition at line 909 of file TextDiagnostic.cpp.
References clang::DiagnosticRenderer::DiagOpts, clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), and clang::PresumedLoc::isValid().
printDiagnosticLevel()
void TextDiagnostic::printDiagnosticLevel (raw_ostream & OS, DiagnosticsEngine::Level Level, bool ShowColors, bool CLFallbackMode = false) static
Print the diagonstic level to a raw_ostream.
This is a static helper that handles colorizing the level and formatting it into an arbitrary output stream. This is used internally by the TextDiagnostic emission code, but it can also be used directly by consumers that don't have a source manager or other state that the full TextDiagnostic logic requires.
Definition at line 696 of file TextDiagnostic.cpp.
References clang::DiagnosticsEngine::Error, errorColor, clang::DiagnosticsEngine::Fatal, fatalColor, clang::DiagnosticsEngine::Ignored, clang::DiagnosticsEngine::Note, noteColor, clang::DiagnosticsEngine::Remark, remarkColor, clang::DiagnosticsEngine::Warning, and warningColor.
Referenced by emitDiagnosticMessage(), and clang::TextDiagnosticPrinter::HandleDiagnostic().
printDiagnosticMessage()
void TextDiagnostic::printDiagnosticMessage (raw_ostream & OS, bool IsSupplemental, StringRef Message, unsigned CurrentColumn, unsigned Columns, bool ShowColors) static
Pretty-print a diagnostic message to a raw_ostream.
This is a static helper to handle the line wrapping, colorizing, and rendering of a diagnostic message to a particular ostream. It is publicly visible so that clients which do not have sufficient state to build a complete TextDiagnostic object can still get consistent formatting of their diagnostic messages.
Parameters
OS Where the message is printed
IsSupplemental true if this is a continuation note diagnostic
Message The text actually printed
CurrentColumn The starting column of the first line, accounting for any prefix.
Columns The number of columns to use in line-wrapping, 0 disables all line-wrapping.
ShowColors Enable colorizing of the message.
Definition at line 737 of file TextDiagnostic.cpp.
References applyTemplateHighlighting(), clang::Normal, printWordWrapped(), and savedColor.
Referenced by emitDiagnosticMessage(), and clang::TextDiagnosticPrinter::HandleDiagnostic().
The documentation for this class was generated from the following files:
include/clang/Frontend/TextDiagnostic.h
lib/Frontend/TextDiagnostic.cpp