clang: lib/Analysis/Consumed.cpp File Reference
Consumed.cpp File Reference
#include "clang/Analysis/Analyses/Consumed.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/Type.h"
#include "clang/Analysis/Analyses/PostOrderCFGView.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Analysis/CFG.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <memory>
#include <utility>
Classes
class clang::consumed::PropagationInfo
class clang::consumed::ConsumedStmtVisitor
Namespaces
namespace clang
Dataflow Directional Tag Classes.
namespace clang::consumed
Enumerations
enum clang::consumed::EffectiveOp { clang::consumed::EO_And , clang::consumed::EO_Or }
Functions
static SourceLocation getFirstStmtLoc (const CFGBlock *Block)
static SourceLocation getLastStmtLoc (const CFGBlock *Block)
static ConsumedState invertConsumedUnconsumed (ConsumedState State)
static bool isCallableInState (const CallableWhenAttr *CWAttr, ConsumedState State)
static bool isConsumableType (const QualType &QT)
static bool isAutoCastType (const QualType &QT)
static bool isSetOnReadPtrType (const QualType &QT)
static bool isKnownState (ConsumedState State)
static bool isRValueRef (QualType ParamType)
static bool isTestingFunction (const FunctionDecl *FunDecl)
static bool isPointerOrRef (QualType ParamType)
static ConsumedState mapConsumableAttrState (const QualType QT)
static ConsumedState mapParamTypestateAttrState (const ParamTypestateAttr *PTAttr)
static ConsumedState mapReturnTypestateAttrState (const ReturnTypestateAttr *RTSAttr)
static ConsumedState mapSetTypestateAttrState (const SetTypestateAttr *STAttr)
static StringRef stateToString (ConsumedState State)
static ConsumedState testsFor (const FunctionDecl *FunDecl)
static void setStateForVarOrTmp (ConsumedStateMap *StateMap, const PropagationInfo &PInfo, ConsumedState State)
static void splitVarStateForIf (const IfStmt *IfNode, const VarTestResult &Test, ConsumedStateMap *ThenStates, ConsumedStateMap *ElseStates)
static void splitVarStateForIfBinOp (const PropagationInfo &PInfo, ConsumedStateMap *ThenStates, ConsumedStateMap *ElseStates)
Function Documentation
getFirstStmtLoc()
static SourceLocation getFirstStmtLoc (const CFGBlock * Block) static
Definition at line 61 of file Consumed.cpp.
References clang::Block, and getFirstStmtLoc().
Referenced by getFirstStmtLoc(), and getLastStmtLoc().
getLastStmtLoc()
static SourceLocation getLastStmtLoc (const CFGBlock * Block) static
Definition at line 76 of file Consumed.cpp.
References clang::Block, getFirstStmtLoc(), getLastStmtLoc(), and clang::SourceLocation::isValid().
Referenced by getLastStmtLoc(), and clang::consumed::ConsumedStateMap::intersectAtLoopHead().
invertConsumedUnconsumed()
static ConsumedState invertConsumedUnconsumed (ConsumedState State) static
Definition at line 103 of file Consumed.cpp.
References clang::consumed::CS_Consumed, clang::consumed::CS_None, clang::consumed::CS_Unconsumed, and clang::consumed::CS_Unknown.
Referenced by clang::consumed::PropagationInfo::invertTest(), splitVarStateForIf(), and splitVarStateForIfBinOp().
isAutoCastType()
static bool isAutoCastType (const QualType & QT) static
Definition at line 153 of file Consumed.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
isCallableInState()
static bool isCallableInState (const CallableWhenAttr * CWAttr, ConsumedState State) static
Definition at line 117 of file Consumed.cpp.
References clang::CallableWhenAttr::callableStates(), clang::CallableWhenAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_None, clang::consumed::CS_Unconsumed, clang::consumed::CS_Unknown, clang::CallableWhenAttr::Unconsumed, and clang::CallableWhenAttr::Unknown.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability().
isConsumableType()
static bool isConsumableType (const QualType & QT) static
Definition at line 143 of file Consumed.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), mapConsumableAttrState(), clang::consumed::ConsumedStmtVisitor::VisitCXXConstructExpr(), clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl(), and clang::consumed::ConsumedStmtVisitor::VisitVarDecl().
isKnownState()
static bool isKnownState (ConsumedState State) static
Definition at line 169 of file Consumed.cpp.
References clang::consumed::CS_Consumed, clang::consumed::CS_None, clang::consumed::CS_Unconsumed, and clang::consumed::CS_Unknown.
Referenced by splitVarStateForIfBinOp().
isPointerOrRef()
static bool isPointerOrRef (QualType ParamType) static
Definition at line 189 of file Consumed.cpp.
References clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall().
isRValueRef()
static bool isRValueRef (QualType ParamType) static
Definition at line 181 of file Consumed.cpp.
References clang::Type::isRValueReferenceType().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), TryReferenceInitializationCore(), and clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl().
isSetOnReadPtrType()
static bool isSetOnReadPtrType (const QualType & QT) static
Definition at line 163 of file Consumed.cpp.
References clang::Type::getPointeeCXXRecordDecl().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), and clang::consumed::ConsumedStmtVisitor::VisitCXXConstructExpr().
isTestingFunction()
static bool isTestingFunction (const FunctionDecl * FunDecl) static
Definition at line 185 of file Consumed.cpp.
References clang::Decl::hasAttr().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), and testsFor().
mapConsumableAttrState()
static ConsumedState mapConsumableAttrState (const QualType QT) static
Definition at line 193 of file Consumed.cpp.
References clang::ConsumableAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_Unconsumed, clang::consumed::CS_Unknown, clang::Type::getAsCXXRecordDecl(), clang::Decl::getAttr(), clang::ConsumableAttr::getDefaultState(), isConsumableType(), clang::ConsumableAttr::Unconsumed, and clang::ConsumableAttr::Unknown.
Referenced by clang::consumed::ConsumedStmtVisitor::VisitCXXConstructExpr(), and clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl().
mapParamTypestateAttrState()
static ConsumedState mapParamTypestateAttrState (const ParamTypestateAttr * PTAttr) static
Definition at line 211 of file Consumed.cpp.
References clang::ParamTypestateAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_Unconsumed, clang::consumed::CS_Unknown, clang::ParamTypestateAttr::getParamState(), clang::ParamTypestateAttr::Unconsumed, and clang::ParamTypestateAttr::Unknown.
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall(), and clang::consumed::ConsumedStmtVisitor::VisitParmVarDecl().
mapReturnTypestateAttrState()
static ConsumedState mapReturnTypestateAttrState (const ReturnTypestateAttr * RTSAttr) static
Definition at line 224 of file Consumed.cpp.
References clang::ReturnTypestateAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_Unconsumed, clang::consumed::CS_Unknown, clang::ReturnTypestateAttr::getState(), clang::ReturnTypestateAttr::Unconsumed, and clang::ReturnTypestateAttr::Unknown.
Referenced by clang::consumed::ConsumedStateMap::checkParamsForReturnTypestate(), clang::consumed::ConsumedStmtVisitor::handleCall(), and clang::consumed::ConsumedStmtVisitor::VisitCXXConstructExpr().
mapSetTypestateAttrState()
static ConsumedState mapSetTypestateAttrState (const SetTypestateAttr * STAttr) static
Definition at line 236 of file Consumed.cpp.
References clang::SetTypestateAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_Unconsumed, clang::consumed::CS_Unknown, clang::SetTypestateAttr::getNewState(), clang::SetTypestateAttr::Unconsumed, and clang::SetTypestateAttr::Unknown.
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall().
setStateForVarOrTmp()
static void setStateForVarOrTmp (ConsumedStateMap * StateMap, const PropagationInfo & PInfo, ConsumedState State) static
Definition at line 446 of file Consumed.cpp.
References clang::consumed::PropagationInfo::getTmp(), clang::consumed::PropagationInfo::getVar(), clang::consumed::PropagationInfo::isTmp(), clang::consumed::PropagationInfo::isVar(), and clang::consumed::ConsumedStateMap::setState().
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall().
splitVarStateForIf()
static void splitVarStateForIf (const IfStmt * IfNode, const VarTestResult & Test, ConsumedStateMap * ThenStates, ConsumedStateMap * ElseStates) static
Definition at line 935 of file Consumed.cpp.
References clang::consumed::CS_Unknown, clang::consumed::ConsumedStateMap::getState(), invertConsumedUnconsumed(), clang::consumed::ConsumedStateMap::markUnreachable(), and clang::consumed::ConsumedStateMap::setState().
splitVarStateForIfBinOp()
static void splitVarStateForIfBinOp (const PropagationInfo & PInfo, ConsumedStateMap * ThenStates, ConsumedStateMap * ElseStates) static
Definition at line 950 of file Consumed.cpp.
References clang::consumed::CS_None, clang::consumed::CS_Unknown, clang::consumed::EO_And, clang::consumed::PropagationInfo::getLTest(), clang::consumed::PropagationInfo::getRTest(), clang::consumed::ConsumedStateMap::getState(), invertConsumedUnconsumed(), isKnownState(), clang::consumed::ConsumedStateMap::markUnreachable(), clang::consumed::ConsumedStateMap::setState(), and clang::consumed::PropagationInfo::testEffectiveOp().
stateToString()
static StringRef stateToString (ConsumedState State) static
Definition at line 248 of file Consumed.cpp.
References clang::consumed::CS_Consumed, clang::consumed::CS_None, clang::consumed::CS_Unconsumed, and clang::consumed::CS_Unknown.
Referenced by clang::consumed::ConsumedStmtVisitor::checkCallability(), clang::consumed::ConsumedStateMap::checkParamsForReturnTypestate(), clang::consumed::ConsumedStmtVisitor::handleCall(), and clang::consumed::ConsumedStmtVisitor::VisitReturnStmt().
testsFor()
static ConsumedState testsFor (const FunctionDecl * FunDecl) static
Definition at line 265 of file Consumed.cpp.
References clang::TestTypestateAttr::Consumed, clang::consumed::CS_Consumed, clang::consumed::CS_Unconsumed, clang::Decl::getAttr(), clang::TestTypestateAttr::getTestState(), isTestingFunction(), and clang::TestTypestateAttr::Unconsumed.
Referenced by clang::consumed::ConsumedStmtVisitor::handleCall().