clang: lib/AST/CXXInheritance.cpp File Reference
CXXInheritance.cpp File Reference
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/Basic/LLVM.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <utility>
#include <cassert>
#include <vector>
Functions
static bool isOrdinaryMember (const NamedDecl *ND)
static bool findOrdinaryMember (const CXXRecordDecl *RD, CXXBasePath &Path, DeclarationName Name)
static bool findOrdinaryMemberInDependentClasses (const CXXBaseSpecifier *Specifier, CXXBasePath &Path, DeclarationName Name)
static void AddIndirectPrimaryBases (const CXXRecordDecl *RD, ASTContext &Context, CXXIndirectPrimaryBaseSet &Bases)
Function Documentation
AddIndirectPrimaryBases()
static void AddIndirectPrimaryBases (const CXXRecordDecl * RD, ASTContext & Context, CXXIndirectPrimaryBaseSet & Bases) static
Definition at line 681 of file CXXInheritance.cpp.
References AddIndirectPrimaryBases(), clang::CXXRecordDecl::bases(), clang::cast(), clang::ASTContext::getASTRecordLayout(), clang::RecordType::getDecl(), clang::CXXRecordDecl::getNumVBases(), clang::ASTRecordLayout::getPrimaryBase(), and clang::ASTRecordLayout::isPrimaryBaseVirtual().
Referenced by AddIndirectPrimaryBases(), and clang::CXXRecordDecl::getIndirectPrimaryBases().
findOrdinaryMember()
static bool findOrdinaryMember (const CXXRecordDecl * RD, CXXBasePath & Path, DeclarationName Name) static
Definition at line 387 of file CXXInheritance.cpp.
References clang::CXXBasePath::Decls, isOrdinaryMember(), and clang::DeclContext::lookup().
Referenced by findOrdinaryMemberInDependentClasses(), and clang::CXXRecordDecl::hasMemberName().
findOrdinaryMemberInDependentClasses()
static bool findOrdinaryMemberInDependentClasses (const CXXBaseSpecifier * Specifier, CXXBasePath & Path, DeclarationName Name) static
Definition at line 412 of file CXXInheritance.cpp.
References findOrdinaryMember(), clang::Type::getAs(), clang::TemplateName::getAsTemplateDecl(), and clang::TemplateSpecializationType::getTemplateName().
Referenced by clang::CXXRecordDecl::lookupDependentName().
isOrdinaryMember()
static bool isOrdinaryMember (const NamedDecl * ND) static
Definition at line 382 of file CXXInheritance.cpp.
References clang::Decl::IDNS_Member, clang::Decl::IDNS_Ordinary, clang::Decl::IDNS_Tag, and clang::Decl::isInIdentifierNamespace().
Referenced by findOrdinaryMember(), and clang::CXXRecordDecl::lookupDependentName().