clang: lib/AST/Decl.cpp File Reference
Decl.cpp File Reference
#include "clang/AST/Decl.h"
#include "Linkage.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CanonicalType.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/ODRHash.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/Redeclarable.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Linkage.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SanitizerBlacklist.h"
#include "clang/Basic/Sanitizers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetCXXABI.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Visibility.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <memory>
#include <string>
#include <tuple>
#include <type_traits>
#include "clang/AST/DeclNodes.inc"
Macros
#define DECL(Type, Base)
#define ABSTRACT_DECL(DECL)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
Functions
static bool hasExplicitVisibilityAlready (LVComputationKind computation)
Does this computation kind permit us to consider additional visibility settings from attributes and the like?
static LVComputationKind withExplicitVisibilityAlready (LVComputationKind Kind)
Given an LVComputationKind, return one of the same type/value sort that records that it already has explicit visibility.
static Optional< Visibility > getExplicitVisibility (const NamedDecl *D, LVComputationKind kind)
static bool usesTypeVisibility (const NamedDecl *D)
Is the given declaration a "type" or a "value" for the purposes of visibility computation?
template<class T >
static std::enable_if<!std::is_base_of< RedeclarableTemplateDecl, T >::value, bool >::type isExplicitMemberSpecialization (const T *D)
Does the given declaration have member specialization information, and if so, is it an explicit specialization?
static bool isExplicitMemberSpecialization (const RedeclarableTemplateDecl *D)
For templates, this question is easier: a member template can't be explicitly instantiated, so there's a single bit indicating whether or not this is an explicit member specialization.
template<class T >
static Visibility getVisibilityFromAttr (const T *attr)
Given a visibility attribute, return the explicit visibility associated with it.
static Optional< Visibility > getVisibilityOf (const NamedDecl *D, NamedDecl::ExplicitVisibilityKind kind)
Return the explicit visibility of the given declaration.
static const Decl * getOutermostFuncOrBlockContext (const Decl *D)
static bool shouldConsiderTemplateVisibility (const FunctionDecl *fn, const FunctionTemplateSpecializationInfo *specInfo)
static bool hasDirectVisibilityAttribute (const NamedDecl *D, LVComputationKind computation)
Does the given declaration have a direct visibility attribute that would match the given rules?
static bool shouldConsiderTemplateVisibility (const ClassTemplateSpecializationDecl *spec, LVComputationKind computation)
Should we consider visibility associated with the template arguments and parameters of the given class template specialization?
static bool shouldConsiderTemplateVisibility (const VarTemplateSpecializationDecl *spec, LVComputationKind computation)
Should we consider visibility associated with the template arguments and parameters of the given variable template specialization? As usual, follow class template specialization logic up to initialization.
static bool useInlineVisibilityHidden (const NamedDecl *D)
template<typename T >
static bool isFirstInExternCContext (T *D)
static bool isSingleLineLanguageLinkage (const Decl &D)
static bool isInModulePurview (const NamedDecl *D)
Determine whether D is declared in the purview of a named module.
static bool isExportedFromModuleInterfaceUnit (const NamedDecl *D)
static LinkageInfo getInternalLinkageFor (const NamedDecl *D)
static LinkageInfo getExternalLinkageFor (const NamedDecl *D)
static StorageClass getStorageClass (const Decl *D)
static Optional< Visibility > getExplicitVisibilityAux (const NamedDecl *ND, NamedDecl::ExplicitVisibilityKind kind, bool IsMostRecent)
template<typename T >
static bool isRedeclarableImpl (Redeclarable< T > *)
static bool isRedeclarableImpl (...)
static bool isRedeclarable (Decl::Kind K)
template<typename DeclT >
static SourceLocation getTemplateOrInnerLocStart (const DeclT *decl)
static bool typeIsPostfix (QualType QT)
template<typename T >
static LanguageLinkage getDeclLanguageLinkage (const T &D)
template<typename T >
static bool isDeclExternC (const T &D)
template<typename DeclT >
static DeclT * getDefinitionOrSelf (DeclT *D)
template<std::size_t Len>
static bool isNamed (const NamedDecl *ND, const char(&Str)[Len])
static bool redeclForcesDefMSVC (const FunctionDecl *Redecl)
static bool RedeclForcesDefC99 (const FunctionDecl *Redecl)
static unsigned getNumModuleIdentifiers (Module *Mod)
Retrieve the number of module identifiers needed to name the given module.
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
ACCESSSPEC
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
BINDING
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BUILTINTEMPLATE
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CAPTURED
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CONCEPT
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONSTRUCTORUSINGSHADOW
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CXXCONSTRUCTOR
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDESTRUCTOR
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXMETHOD
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXRECORD
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
DECL
#define DECL (Type, Base)
Value:
  case Decl::Type: \
    return isRedeclarableImpl((Type##Decl *)nullptr);
DECL_CONTEXT
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_RANGE
#define DECL_RANGE (Base, First, Last)
DECLARATOR
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECOMPOSITION
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
EMPTY
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPORT
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
FIELD
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FRIEND
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FUNCTION
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONTEMPLATE
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
IMPLICITPARAM
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPORT
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
LABEL
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LAST_DECL_RANGE
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MSGUID
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
NAMED
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NONTYPETEMPLATEPARM
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
OBJCATDEFSFIELD
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCCATEGORY
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCIMPL
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINTERFACE
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIVAR
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCMETHOD
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROTOCOL
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCTYPEPARAM
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OMPALLOCATE
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPCAPTUREDEXPR
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPDECLAREMAPPER
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPREQUIRES
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
PARMVAR
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PRAGMACOMMENT
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
RECORD
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
REDECLARABLETEMPLATE
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPRBODY
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
TAG
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPEALIAS
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USING
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VALUE
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VAR
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
Function Documentation
getDeclLanguageLinkage()
template<typename T > static LanguageLinkage getDeclLanguageLinkage (const T & D) static
Definition at line 2044 of file Decl.cpp.
References clang::CLanguageLinkage, clang::CXXLanguageLinkage, clang::ASTContext::getLangOpts(), isFirstInExternCContext(), clang::DeclContext::isRecord(), and clang::NoLanguageLinkage.
Referenced by clang::FunctionDecl::getLanguageLinkage(), and clang::VarDecl::getLanguageLinkage().
getDefinitionOrSelf()
template<typename DeclT > static DeclT * getDefinitionOrSelf (DeclT * D) static
Definition at line 2497 of file Decl.cpp.
Referenced by clang::EnumDecl::getTemplateInstantiationPattern(), clang::FunctionDecl::getTemplateInstantiationPattern(), and clang::VarDecl::getTemplateInstantiationPattern().
getExplicitVisibility()
static Optional< Visibility > getExplicitVisibility (const NamedDecl * D, LVComputationKind kind) static
Definition at line 171 of file Decl.cpp.
References clang::NamedDecl::getExplicitVisibility().
getExplicitVisibilityAux()
static Optional< Visibility > getExplicitVisibilityAux (const NamedDecl * ND, NamedDecl::ExplicitVisibilityKind kind, bool IsMostRecent) static
Definition at line 1107 of file Decl.cpp.
References getExplicitVisibilityAux(), clang::CXXRecordDecl::getInstantiatedFromMemberClass(), clang::FunctionDecl::getInstantiatedFromMemberFunction(), clang::VarDecl::getInstantiatedFromStaticDataMember(), clang::NamedDecl::getMostRecentDecl(), clang::VarTemplateSpecializationDecl::getSpecializedTemplate(), clang::VarTemplateDecl::getTemplatedDecl(), clang::FunctionDecl::getTemplateSpecializationInfo(), getVisibilityOf(), clang::None, and V.
Referenced by clang::NamedDecl::getExplicitVisibility(), and getExplicitVisibilityAux().
getExternalLinkageFor()
static LinkageInfo getExternalLinkageFor (const NamedDecl * D) static
Definition at line 602 of file Decl.cpp.
References clang::DefaultVisibility, clang::LinkageInfo::external(), clang::Decl::getCanonicalDecl(), isExportedFromModuleInterfaceUnit(), isInModulePurview(), and clang::ModuleLinkage.
Referenced by clang::LinkageComputer::computeLVForDecl().
getInternalLinkageFor()
static LinkageInfo getInternalLinkageFor (const NamedDecl * D) static
Definition at line 591 of file Decl.cpp.
References clang::DefaultVisibility, clang::LinkageInfo::internal(), isInModulePurview(), and clang::ModuleInternalLinkage.
Referenced by clang::LinkageComputer::computeLVForDecl(), and clang::LinkageComputer::getLVForDecl().
getNumModuleIdentifiers()
static unsigned getNumModuleIdentifiers (Module * Mod) static
Retrieve the number of module identifiers needed to name the given module.
Definition at line 5029 of file Decl.cpp.
References clang::Module::Parent, and clang::Result.
Referenced by clang::ImportDecl::getIdentifierLocs().
getOutermostFuncOrBlockContext()
static const Decl * getOutermostFuncOrBlockContext (const Decl * D) static
Definition at line 302 of file Decl.cpp.
References clang::cast(), clang::Decl::getDeclContext(), clang::DeclContext::getDeclKind(), clang::DeclContext::getParent(), and Ret().
getStorageClass()
static StorageClass getStorageClass (const Decl * D) static
Definition at line 614 of file Decl.cpp.
References clang::SC_None.
getTemplateOrInnerLocStart()
template<typename DeclT > static SourceLocation getTemplateOrInnerLocStart (const DeclT * decl) static
Definition at line 1823 of file Decl.cpp.
References clang::ast_matchers::decl.
Referenced by clang::DeclaratorDecl::getOuterLocStart(), and clang::TagDecl::getOuterLocStart().
getVisibilityFromAttr()
template<class T > static Visibility getVisibilityFromAttr (const T * attr) static
Given a visibility attribute, return the explicit visibility associated with it.
Definition at line 208 of file Decl.cpp.
References clang::DefaultVisibility, clang::HiddenVisibility, and clang::ProtectedVisibility.
Referenced by getVisibilityOf().
getVisibilityOf()
static Optional< Visibility > getVisibilityOf (const NamedDecl * D, NamedDecl::ExplicitVisibilityKind kind) static
Return the explicit visibility of the given declaration.
Definition at line 221 of file Decl.cpp.
References clang::Decl::getAttr(), getVisibilityFromAttr(), clang::None, and clang::NamedDecl::VisibilityForType.
Referenced by getExplicitVisibilityAux().
hasDirectVisibilityAttribute()
static bool hasDirectVisibilityAttribute (const NamedDecl * D, LVComputationKind computation) static
Does the given declaration have a direct visibility attribute that would match the given rules?
Definition at line 408 of file Decl.cpp.
References clang::Decl::hasAttr(), clang::LVComputationKind::IgnoreAllVisibility, and clang::LVComputationKind::isTypeVisibility().
Referenced by shouldConsiderTemplateVisibility(), and shouldConsiderTemplateVisibility().
hasExplicitVisibilityAlready()
static bool hasExplicitVisibilityAlready (LVComputationKind computation) static
Does this computation kind permit us to consider additional visibility settings from attributes and the like?
Definition at line 159 of file Decl.cpp.
References clang::LVComputationKind::IgnoreExplicitVisibility.
Referenced by shouldConsiderTemplateVisibility(), and shouldConsiderTemplateVisibility().
isDeclExternC()
template<typename T > static bool isDeclExternC (const T & D) static
Definition at line 2072 of file Decl.cpp.
References clang::CLanguageLinkage, and clang::DeclContext::isRecord().
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnPragmaRedefineExtname(), clang::Sema::ActOnVariableDeclarator(), clang::FunctionDecl::isExternC(), and clang::VarDecl::isExternC().
isExplicitMemberSpecialization() [1/2]
static bool isExplicitMemberSpecialization (const RedeclarableTemplateDecl * D) static
For templates, this question is easier: a member template can't be explicitly instantiated, so there's a single bit indicating whether or not this is an explicit member specialization.
Definition at line 201 of file Decl.cpp.
References clang::RedeclarableTemplateDecl::isMemberSpecialization().
isExplicitMemberSpecialization() [2/2]
template<class T > static std::enable_if<!std::is_base_of< RedeclarableTemplateDecl, T >::value, bool >::type isExplicitMemberSpecialization (const T * D) static
Does the given declaration have member specialization information, and if so, is it an explicit specialization?
Definition at line 190 of file Decl.cpp.
isExportedFromModuleInterfaceUnit()
static bool isExportedFromModuleInterfaceUnit (const NamedDecl * D) static
Definition at line 578 of file Decl.cpp.
References clang::Decl::getModuleOwnershipKind(), isInModulePurview(), clang::Decl::ModulePrivate, clang::Decl::Unowned, clang::Decl::Visible, and clang::Decl::VisibleWhenImported.
Referenced by getExternalLinkageFor().
isFirstInExternCContext()
template<typename T > static bool isFirstInExternCContext (T * D) static
Definition at line 559 of file Decl.cpp.
References clang::First.
Referenced by getDeclLanguageLinkage().
isInModulePurview()
static bool isInModulePurview (const NamedDecl * D) static
Determine whether D is declared in the purview of a named module.
Definition at line 572 of file Decl.cpp.
References clang::Decl::getOwningModule().
Referenced by getExternalLinkageFor(), getInternalLinkageFor(), and isExportedFromModuleInterfaceUnit().
isNamed()
template<std::size_t Len> static bool isNamed (const NamedDecl * ND, const char(&) Str[Len]) static
Definition at line 3005 of file Decl.cpp.
References clang::NamedDecl::getIdentifier(), and clang::IdentifierInfo::isStr().
Referenced by clang::FunctionDecl::isMain().
isRedeclarable()
static bool isRedeclarable (Decl::Kind K) static
Definition at line 1698 of file Decl.cpp.
Referenced by clang::NamedDecl::declarationReplaces().
isRedeclarableImpl() [1/2]
static bool isRedeclarableImpl (...) static
Definition at line 1697 of file Decl.cpp.
isRedeclarableImpl() [2/2]
template<typename T > static bool isRedeclarableImpl (Redeclarable< T > *) static
Definition at line 1694 of file Decl.cpp.
isSingleLineLanguageLinkage()
static bool isSingleLineLanguageLinkage (const Decl & D) static
Definition at line 564 of file Decl.cpp.
References clang::Decl::getDeclContext().
Referenced by clang::VarDecl::isThisDeclarationADefinition().
RedeclForcesDefC99()
static bool RedeclForcesDefC99 (const FunctionDecl * Redecl) static
Definition at line 3398 of file Decl.cpp.
References clang::Decl::getLexicalDeclContext(), clang::FunctionDecl::getStorageClass(), clang::Decl::isImplicit(), clang::FunctionDecl::isInlineSpecified(), clang::DeclContext::isTranslationUnit(), and clang::SC_Extern.
Referenced by clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition(), and clang::FunctionDecl::isInlineDefinitionExternallyVisible().
redeclForcesDefMSVC()
static bool redeclForcesDefMSVC (const FunctionDecl * Redecl) static
Definition at line 3386 of file Decl.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl(), clang::FunctionDecl::getStorageClass(), and clang::SC_Extern.
Referenced by clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition().
shouldConsiderTemplateVisibility() [1/3]
static bool shouldConsiderTemplateVisibility (const ClassTemplateSpecializationDecl * spec, LVComputationKind computation) static
Should we consider visibility associated with the template arguments and parameters of the given class template specialization?
Definition at line 419 of file Decl.cpp.
References hasDirectVisibilityAttribute(), hasExplicitVisibilityAlready(), clang::ClassTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), and clang::ClassTemplateSpecializationDecl::isExplicitSpecialization().
shouldConsiderTemplateVisibility() [2/3]
static bool shouldConsiderTemplateVisibility (const FunctionDecl * fn, const FunctionTemplateSpecializationInfo * specInfo) static
Definition at line 368 of file Decl.cpp.
References clang::Decl::hasAttr(), and clang::FunctionTemplateSpecializationInfo::isExplicitInstantiationOrSpecialization().
shouldConsiderTemplateVisibility() [3/3]
static bool shouldConsiderTemplateVisibility (const VarTemplateSpecializationDecl * spec, LVComputationKind computation) static
Should we consider visibility associated with the template arguments and parameters of the given variable template specialization? As usual, follow class template specialization logic up to initialization.
Definition at line 483 of file Decl.cpp.
References hasDirectVisibilityAttribute(), hasExplicitVisibilityAlready(), clang::VarTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), and clang::VarTemplateSpecializationDecl::isExplicitSpecialization().
typeIsPostfix()
static bool typeIsPostfix (QualType QT) static
Definition at line 1897 of file Decl.cpp.
References clang::cast(), and clang::QualType::getTypePtr().
Referenced by clang::DeclaratorDecl::getSourceRange(), and clang::TypedefDecl::getSourceRange().
useInlineVisibilityHidden()
static bool useInlineVisibilityHidden (const NamedDecl * D) static
Definition at line 531 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::ASTContext::getLangOpts(), clang::VarDecl::getTemplateSpecializationKind(), clang::Decl::hasAttr(), clang::FunctionDecl::hasBody(), clang::FunctionDecl::isInlined(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, and clang::TSK_Undeclared.
usesTypeVisibility()
static bool usesTypeVisibility (const NamedDecl * D) static
Is the given declaration a "type" or a "value" for the purposes of visibility computation?
Definition at line 180 of file Decl.cpp.
References clang::isa().
Referenced by clang::LinkageComputer::getDeclLinkageAndVisibility().
withExplicitVisibilityAlready()
static LVComputationKind withExplicitVisibilityAlready (LVComputationKind Kind) static
Given an LVComputationKind, return one of the same type/value sort that records that it already has explicit visibility.
Definition at line 166 of file Decl.cpp.
References clang::LVComputationKind::IgnoreExplicitVisibility.