clang: lib/StaticAnalyzer/Checkers/DereferenceChecker.cpp File Reference
DereferenceChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerHelpers.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
Functions
static const Expr * getDereferenceExpr (const Stmt *S, bool IsBind=false)
static bool suppressReport (const Expr *E)
static bool isDeclRefExprToReference (const Expr *E)
Function Documentation
getDereferenceExpr()
static const Expr * getDereferenceExpr (const Stmt * S, bool IsBind = false) static
Definition at line 94 of file DereferenceChecker.cpp.
References clang::ast_matchers::expr, clang::Expr::IgnoreParenLValueCasts(), and clang::ento::parseAssignment().
isDeclRefExprToReference()
static bool isDeclRefExprToReference (const Expr * E) static
Definition at line 117 of file DereferenceChecker.cpp.
suppressReport()
static bool suppressReport (const Expr * E) static
Definition at line 112 of file DereferenceChecker.cpp.
References clang::Expr::getType(), and clang::QualType::hasAddressSpace().