clang: lib/Driver/ToolChains/Arch/RISCV.cpp File Reference
RISCV.cpp File Reference
#include "RISCV.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/ArgList.h"
#include "llvm/ADT/Optional.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/raw_ostream.h"
#include "ToolChains/CommonArgs.h"
Functions
static StringRef getExtensionTypeDesc (StringRef Ext)
static StringRef getExtensionType (StringRef Ext)
static Optional< RISCVExtensionVersion > isExperimentalExtension (StringRef Ext)
static bool isSupportedExtension (StringRef Ext)
static bool getExtensionVersion (const Driver &D, const ArgList &Args, StringRef MArch, StringRef Ext, StringRef In, std::string &Major, std::string &Minor)
static void getExtensionFeatures (const Driver &D, const ArgList &Args, std::vector< StringRef > &Features, StringRef &MArch, StringRef &Exts)
static bool getArchFeatures (const Driver &D, StringRef MArch, std::vector< StringRef > &Features, const ArgList &Args)
static void getRISCFeaturesFromMcpu (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, const llvm::opt::Arg *A, StringRef Mcpu, std::vector< StringRef > &Features)
Function Documentation
getArchFeatures()
static bool getArchFeatures (const Driver & D, StringRef MArch, std::vector< StringRef > & Features, const ArgList & Args) static
Definition at line 273 of file RISCV.cpp.
References c, clang::driver::Driver::Diag(), clang::Error, getExtensionFeatures(), getExtensionVersion(), and Next.
getExtensionFeatures()
static void getExtensionFeatures (const Driver & D, const ArgList & Args, std::vector< StringRef > & Features, StringRef & MArch, StringRef & Exts) static
Definition at line 171 of file RISCV.cpp.
References clang::driver::Driver::Diag(), getExtensionType(), getExtensionTypeDesc(), getExtensionVersion(), clang::isDigit(), isExperimentalExtension(), isSupportedExtension(), Split, and Type.
Referenced by getArchFeatures().
getExtensionType()
static StringRef getExtensionType (StringRef Ext) static
Definition at line 45 of file RISCV.cpp.
Referenced by getExtensionFeatures().
getExtensionTypeDesc()
static StringRef getExtensionTypeDesc (StringRef Ext) static
Definition at line 33 of file RISCV.cpp.
Referenced by getExtensionFeatures().
getExtensionVersion()
static bool getExtensionVersion (const Driver & D, const ArgList & Args, StringRef MArch, StringRef Ext, StringRef In, std::string & Major, std::string & Minor) static
Definition at line 86 of file RISCV.cpp.
References clang::driver::Driver::Diag(), clang::isDigit(), and isExperimentalExtension().
Referenced by getArchFeatures(), and getExtensionFeatures().
getRISCFeaturesFromMcpu()
static void getRISCFeaturesFromMcpu (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, const llvm::opt::Arg * A, StringRef Mcpu, std::vector< StringRef > & Features) static
Definition at line 468 of file RISCV.cpp.
References clang::driver::Driver::Diag().
isExperimentalExtension()
static Optional< RISCVExtensionVersion > isExperimentalExtension (StringRef Ext) static
Definition at line 60 of file RISCV.cpp.
References clang::None.
Referenced by getExtensionFeatures(), getExtensionVersion(), and isSupportedExtension().
isSupportedExtension()
static bool isSupportedExtension (StringRef Ext) static
Definition at line 72 of file RISCV.cpp.
References isExperimentalExtension().
Referenced by getExtensionFeatures().