clang: lib/AST/ExprConstant.cpp File Reference
ExprConstant.cpp File Reference
#include "Interp/Context.h"
#include "Interp/Frame.h"
#include "Interp/State.h"
#include "clang/AST/APValue.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/CurrentSourceLocExprScope.h"
#include "clang/AST/Expr.h"
#include "clang/AST/OSLog.h"
#include "clang/AST/OptionalDiagnostic.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/APFixedPoint.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <cstring>
#include <functional>
#include "clang/AST/TypeNodes.inc"
#include "clang/AST/BuiltinTypes.def"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/AST/StmtNodes.inc"
Classes
struct llvm::DenseMapInfo< ObjectUnderConstruction >
struct DynamicType
Namespaces
namespace llvm
Specialize PointerLikeTypeTraits to allow LazyGenerationalUpdatePtr to be placed into a PointerUnion.
Macros
#define DEBUG_TYPE "exprconstant"
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TYPE(ID, BASE)
#define DEPENDENT_TYPE(ID, BASE)
#define NON_CANONICAL_TYPE(ID, BASE)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(ID, BASE)
#define ABSTRACT_TYPE(Class, Base)
#define BUILTIN_TYPE(ID, SINGLETON_ID)
#define SIGNED_TYPE(ID, SINGLETON_ID)
#define FLOATING_TYPE(ID, SINGLETON_ID)
#define PLACEHOLDER_TYPE(ID, SINGLETON_ID)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define ABSTRACT_STMT(Node)
#define STMT(Node, Base)
#define EXPR(Node, Base)
#define STMT_RANGE(Base, First, Last)
#define LAST_STMT_RANGE(Base, First, Last)
#define ASMSTMT(Type, Base)
#define GCCASMSTMT(Type, Base)
#define MSASMSTMT(Type, Base)
#define BREAKSTMT(Type, Base)
#define CXXCATCHSTMT(Type, Base)
#define CXXFORRANGESTMT(Type, Base)
#define CXXTRYSTMT(Type, Base)
#define CAPTUREDSTMT(Type, Base)
#define COMPOUNDSTMT(Type, Base)
#define CONTINUESTMT(Type, Base)
#define CORETURNSTMT(Type, Base)
#define COROUTINEBODYSTMT(Type, Base)
#define DECLSTMT(Type, Base)
#define DOSTMT(Type, Base)
#define FORSTMT(Type, Base)
#define GOTOSTMT(Type, Base)
#define IFSTMT(Type, Base)
#define INDIRECTGOTOSTMT(Type, Base)
#define MSDEPENDENTEXISTSSTMT(Type, Base)
#define NULLSTMT(Type, Base)
#define OMPEXECUTABLEDIRECTIVE(Type, Base)
#define OMPATOMICDIRECTIVE(Type, Base)
#define OMPBARRIERDIRECTIVE(Type, Base)
#define OMPCANCELDIRECTIVE(Type, Base)
#define OMPCANCELLATIONPOINTDIRECTIVE(Type, Base)
#define OMPCRITICALDIRECTIVE(Type, Base)
#define OMPDEPOBJDIRECTIVE(Type, Base)
#define OMPFLUSHDIRECTIVE(Type, Base)
#define OMPLOOPDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPFORDIRECTIVE(Type, Base)
#define OMPFORSIMDDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELFORDIRECTIVE(Type, Base)
#define OMPPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPSIMDDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPTASKLOOPDIRECTIVE(Type, Base)
#define OMPTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPMASTERDIRECTIVE(Type, Base)
#define OMPORDEREDDIRECTIVE(Type, Base)
#define OMPPARALLELDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERDIRECTIVE(Type, Base)
#define OMPPARALLELSECTIONSDIRECTIVE(Type, Base)
#define OMPSCANDIRECTIVE(Type, Base)
#define OMPSECTIONDIRECTIVE(Type, Base)
#define OMPSECTIONSDIRECTIVE(Type, Base)
#define OMPSINGLEDIRECTIVE(Type, Base)
#define OMPTARGETDATADIRECTIVE(Type, Base)
#define OMPTARGETDIRECTIVE(Type, Base)
#define OMPTARGETENTERDATADIRECTIVE(Type, Base)
#define OMPTARGETEXITDATADIRECTIVE(Type, Base)
#define OMPTARGETPARALLELDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDIRECTIVE(Type, Base)
#define OMPTARGETUPDATEDIRECTIVE(Type, Base)
#define OMPTASKDIRECTIVE(Type, Base)
#define OMPTASKGROUPDIRECTIVE(Type, Base)
#define OMPTASKWAITDIRECTIVE(Type, Base)
#define OMPTASKYIELDDIRECTIVE(Type, Base)
#define OMPTEAMSDIRECTIVE(Type, Base)
#define OBJCATCATCHSTMT(Type, Base)
#define OBJCATFINALLYSTMT(Type, Base)
#define OBJCATSYNCHRONIZEDSTMT(Type, Base)
#define OBJCATTHROWSTMT(Type, Base)
#define OBJCATTRYSTMT(Type, Base)
#define OBJCAUTORELEASEPOOLSTMT(Type, Base)
#define OBJCFORCOLLECTIONSTMT(Type, Base)
#define RETURNSTMT(Type, Base)
#define SEHEXCEPTSTMT(Type, Base)
#define SEHFINALLYSTMT(Type, Base)
#define SEHLEAVESTMT(Type, Base)
#define SEHTRYSTMT(Type, Base)
#define SWITCHCASE(Type, Base)
#define CASESTMT(Type, Base)
#define DEFAULTSTMT(Type, Base)
#define SWITCHSTMT(Type, Base)
#define VALUESTMT(Type, Base)
#define ATTRIBUTEDSTMT(Type, Base)
#define ABSTRACTCONDITIONALOPERATOR(Type, Base)
#define BINARYCONDITIONALOPERATOR(Type, Base)
#define CONDITIONALOPERATOR(Type, Base)
#define ADDRLABELEXPR(Type, Base)
#define ARRAYINITINDEXEXPR(Type, Base)
#define ARRAYINITLOOPEXPR(Type, Base)
#define ARRAYSUBSCRIPTEXPR(Type, Base)
#define ARRAYTYPETRAITEXPR(Type, Base)
#define ASTYPEEXPR(Type, Base)
#define ATOMICEXPR(Type, Base)
#define BINARYOPERATOR(Type, Base)
#define COMPOUNDASSIGNOPERATOR(Type, Base)
#define BLOCKEXPR(Type, Base)
#define CXXBINDTEMPORARYEXPR(Type, Base)
#define CXXBOOLLITERALEXPR(Type, Base)
#define CXXCONSTRUCTEXPR(Type, Base)
#define CXXTEMPORARYOBJECTEXPR(Type, Base)
#define CXXDEFAULTARGEXPR(Type, Base)
#define CXXDEFAULTINITEXPR(Type, Base)
#define CXXDELETEEXPR(Type, Base)
#define CXXDEPENDENTSCOPEMEMBEREXPR(Type, Base)
#define CXXFOLDEXPR(Type, Base)
#define CXXINHERITEDCTORINITEXPR(Type, Base)
#define CXXNEWEXPR(Type, Base)
#define CXXNOEXCEPTEXPR(Type, Base)
#define CXXNULLPTRLITERALEXPR(Type, Base)
#define CXXPSEUDODESTRUCTOREXPR(Type, Base)
#define CXXREWRITTENBINARYOPERATOR(Type, Base)
#define CXXSCALARVALUEINITEXPR(Type, Base)
#define CXXSTDINITIALIZERLISTEXPR(Type, Base)
#define CXXTHISEXPR(Type, Base)
#define CXXTHROWEXPR(Type, Base)
#define CXXTYPEIDEXPR(Type, Base)
#define CXXUNRESOLVEDCONSTRUCTEXPR(Type, Base)
#define CXXUUIDOFEXPR(Type, Base)
#define CALLEXPR(Type, Base)
#define CUDAKERNELCALLEXPR(Type, Base)
#define CXXMEMBERCALLEXPR(Type, Base)
#define CXXOPERATORCALLEXPR(Type, Base)
#define USERDEFINEDLITERAL(Type, Base)
#define CASTEXPR(Type, Base)
#define EXPLICITCASTEXPR(Type, Base)
#define BUILTINBITCASTEXPR(Type, Base)
#define CSTYLECASTEXPR(Type, Base)
#define CXXFUNCTIONALCASTEXPR(Type, Base)
#define CXXNAMEDCASTEXPR(Type, Base)
#define CXXADDRSPACECASTEXPR(Type, Base)
#define CXXCONSTCASTEXPR(Type, Base)
#define CXXDYNAMICCASTEXPR(Type, Base)
#define CXXREINTERPRETCASTEXPR(Type, Base)
#define CXXSTATICCASTEXPR(Type, Base)
#define OBJCBRIDGEDCASTEXPR(Type, Base)
#define IMPLICITCASTEXPR(Type, Base)
#define CHARACTERLITERAL(Type, Base)
#define CHOOSEEXPR(Type, Base)
#define COMPOUNDLITERALEXPR(Type, Base)
#define CONCEPTSPECIALIZATIONEXPR(Type, Base)
#define CONVERTVECTOREXPR(Type, Base)
#define COROUTINESUSPENDEXPR(Type, Base)
#define COAWAITEXPR(Type, Base)
#define COYIELDEXPR(Type, Base)
#define DECLREFEXPR(Type, Base)
#define DEPENDENTCOAWAITEXPR(Type, Base)
#define DEPENDENTSCOPEDECLREFEXPR(Type, Base)
#define DESIGNATEDINITEXPR(Type, Base)
#define DESIGNATEDINITUPDATEEXPR(Type, Base)
#define EXPRESSIONTRAITEXPR(Type, Base)
#define EXTVECTORELEMENTEXPR(Type, Base)
#define FIXEDPOINTLITERAL(Type, Base)
#define FLOATINGLITERAL(Type, Base)
#define FULLEXPR(Type, Base)
#define CONSTANTEXPR(Type, Base)
#define EXPRWITHCLEANUPS(Type, Base)
#define FUNCTIONPARMPACKEXPR(Type, Base)
#define GNUNULLEXPR(Type, Base)
#define GENERICSELECTIONEXPR(Type, Base)
#define IMAGINARYLITERAL(Type, Base)
#define IMPLICITVALUEINITEXPR(Type, Base)
#define INITLISTEXPR(Type, Base)
#define INTEGERLITERAL(Type, Base)
#define LAMBDAEXPR(Type, Base)
#define MSPROPERTYREFEXPR(Type, Base)
#define MSPROPERTYSUBSCRIPTEXPR(Type, Base)
#define MATERIALIZETEMPORARYEXPR(Type, Base)
#define MATRIXSUBSCRIPTEXPR(Type, Base)
#define MEMBEREXPR(Type, Base)
#define NOINITEXPR(Type, Base)
#define OMPARRAYSECTIONEXPR(Type, Base)
#define OMPARRAYSHAPINGEXPR(Type, Base)
#define OMPITERATOREXPR(Type, Base)
#define OBJCARRAYLITERAL(Type, Base)
#define OBJCAVAILABILITYCHECKEXPR(Type, Base)
#define OBJCBOOLLITERALEXPR(Type, Base)
#define OBJCBOXEDEXPR(Type, Base)
#define OBJCDICTIONARYLITERAL(Type, Base)
#define OBJCENCODEEXPR(Type, Base)
#define OBJCINDIRECTCOPYRESTOREEXPR(Type, Base)
#define OBJCISAEXPR(Type, Base)
#define OBJCIVARREFEXPR(Type, Base)
#define OBJCMESSAGEEXPR(Type, Base)
#define OBJCPROPERTYREFEXPR(Type, Base)
#define OBJCPROTOCOLEXPR(Type, Base)
#define OBJCSELECTOREXPR(Type, Base)
#define OBJCSTRINGLITERAL(Type, Base)
#define OBJCSUBSCRIPTREFEXPR(Type, Base)
#define OFFSETOFEXPR(Type, Base)
#define OPAQUEVALUEEXPR(Type, Base)
#define OVERLOADEXPR(Type, Base)
#define UNRESOLVEDLOOKUPEXPR(Type, Base)
#define UNRESOLVEDMEMBEREXPR(Type, Base)
#define PACKEXPANSIONEXPR(Type, Base)
#define PARENEXPR(Type, Base)
#define PARENLISTEXPR(Type, Base)
#define PREDEFINEDEXPR(Type, Base)
#define PSEUDOOBJECTEXPR(Type, Base)
#define RECOVERYEXPR(Type, Base)
#define REQUIRESEXPR(Type, Base)
#define SHUFFLEVECTOREXPR(Type, Base)
#define SIZEOFPACKEXPR(Type, Base)
#define SOURCELOCEXPR(Type, Base)
#define STMTEXPR(Type, Base)
#define STRINGLITERAL(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMEXPR(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR(Type, Base)
#define TYPETRAITEXPR(Type, Base)
#define TYPOEXPR(Type, Base)
#define UNARYEXPRORTYPETRAITEXPR(Type, Base)
#define UNARYOPERATOR(Type, Base)
#define VAARGEXPR(Type, Base)
#define LABELSTMT(Type, Base)
#define WHILESTMT(Type, Base)
Typedefs
using CheckedTemporaries
Materialized temporaries that we've already checked to determine if they're initializsed by a constant expression.
Enumerations
enum class CheckEvaluationResultKind { ConstantExpression , FullyInitialized }
enum class GCCTypeClass {
None = -1 , Void = 0 , Integer = 1 , Enum = 3 ,
Bool = 4 , Pointer = 5 , PointerToDataMember = 7 , RealFloat = 8 ,
Complex = 9 , PointerToMemberFunction = 12 , ClassOrStruct = 12 , Union = 13
}
Values returned by __builtin_classify_type, chosen to match the values produced by GCC's builtin.
Functions
static bool HandleDestruction (EvalInfo &Info, const Expr *E, const LValue &This, QualType ThisType)
Perform a destructor or pseudo-destructor call on the given object, which might in general not be a complete object.
static bool HandleDestruction (EvalInfo &Info, SourceLocation Loc, APValue::LValueBase LVBase, APValue &Value, QualType T)
Destroy and end the lifetime of the given complete object.
static bool isRead (AccessKinds AK)
static bool isModification (AccessKinds AK)
static bool isAnyAccess (AccessKinds AK)
static bool isFormalAccess (AccessKinds AK)
Is this an access per the C++ definition?
static bool isValidIndeterminateAccess (AccessKinds AK)
Is this kind of axcess valid on an indeterminate object value?
static bool Evaluate (APValue &Result, EvalInfo &Info, const Expr *E)
static bool EvaluateInPlace (APValue &Result, EvalInfo &Info, const LValue &This, const Expr *E, bool AllowNonLiteralTypes)
EvaluateInPlace - Evaluate an expression in-place in an APValue. In some cases, the in-place evaluation is essential, since later initializers for an object can indirectly refer to subobjects which were initialized earlier.
static bool EvaluateLValue (const Expr *E, LValue &Result, EvalInfo &Info, bool InvalidBaseOK)
Evaluate an expression as an lvalue. This can be legitimately called on expressions which are not glvalues, in three cases:
static bool EvaluatePointer (const Expr *E, LValue &Result, EvalInfo &Info, bool InvalidBaseOK=false)
static bool EvaluateMemberPointer (const Expr *E, MemberPtr &Result, EvalInfo &Info)
static bool EvaluateTemporary (const Expr *E, LValue &Result, EvalInfo &Info)
Evaluate an expression of record type as a temporary.
static bool EvaluateInteger (const Expr *E, APSInt &Result, EvalInfo &Info)
static bool EvaluateIntegerOrLValue (const Expr *E, APValue &Result, EvalInfo &Info)
EvaluateIntegerOrLValue - Evaluate an rvalue integral-typed expression, and produce either the integer value or a pointer.
static bool EvaluateFloat (const Expr *E, APFloat &Result, EvalInfo &Info)
static bool EvaluateComplex (const Expr *E, ComplexValue &Res, EvalInfo &Info)
static bool EvaluateAtomic (const Expr *E, const LValue *This, APValue &Result, EvalInfo &Info)
static bool EvaluateAsRValue (EvalInfo &Info, const Expr *E, APValue &Result)
EvaluateAsRValue - Try to evaluate this expression, performing an implicit lvalue-to-rvalue cast if it is an lvalue.
static bool EvaluateFixedPointOrInteger (const Expr *E, APFixedPoint &Result, EvalInfo &Info)
Evaluate an integer or fixed point expression into an APResult.
static bool EvaluateFixedPoint (const Expr *E, APFixedPoint &Result, EvalInfo &Info)
Evaluate only a fixed point expression into an APResult.
static void negateAsSigned (APSInt &Int)
Negate an APSInt in place, converting it to a signed form if necessary, and preserving its value (by extending by up to one bit as needed).
static bool EvaluateIgnoredValue (EvalInfo &Info, const Expr *E)
Evaluate an expression to see if it had side-effects, and discard its result.
static bool IsStringLiteralCall (const CallExpr *E)
Should this call expression be treated as a string literal?
static bool IsGlobalLValue (APValue::LValueBase B)
static const ValueDecl * GetLValueBaseDecl (const LValue &LVal)
static bool IsLiteralLValue (const LValue &Value)
static bool IsWeakLValue (const LValue &Value)
static bool isZeroSized (const LValue &Value)
static bool HasSameBase (const LValue &A, const LValue &B)
static void NoteLValueLocation (EvalInfo &Info, APValue::LValueBase Base)
static bool CheckEvaluationResult (CheckEvaluationResultKind CERK, EvalInfo &Info, SourceLocation DiagLoc, QualType Type, const APValue &Value, ConstantExprKind Kind, SourceLocation SubobjectLoc, CheckedTemporaries &CheckedTemps)
static bool CheckLValueConstantExpression (EvalInfo &Info, SourceLocation Loc, QualType Type, const LValue &LVal, ConstantExprKind Kind, CheckedTemporaries &CheckedTemps)
Check that this reference or pointer core constant expression is a valid value for an address or reference constant expression.
static bool CheckMemberPointerConstantExpression (EvalInfo &Info, SourceLocation Loc, QualType Type, const APValue &Value, ConstantExprKind Kind)
Member pointers are constant expressions unless they point to a non-virtual dllimport member function.
static bool CheckLiteralType (EvalInfo &Info, const Expr *E, const LValue *This=nullptr)
Check that this core constant expression is of literal type, and if not, produce an appropriate diagnostic.
static bool CheckConstantExpression (EvalInfo &Info, SourceLocation DiagLoc, QualType Type, const APValue &Value, ConstantExprKind Kind)
Check that this core constant expression value is a valid value for a constant expression.
static bool CheckFullyInitialized (EvalInfo &Info, SourceLocation DiagLoc, QualType Type, const APValue &Value)
Check that this evaluated value is fully-initialized and can be loaded by an lvalue-to-rvalue conversion.
static bool CheckMemoryLeaks (EvalInfo &Info)
Enforce C++2a [expr.const]/4.17, which disallows new-expressions unless "the allocated storage is deallocated within the evaluation".
static bool EvalPointerValueAsBool (const APValue &Value, bool &Result)
static bool HandleConversionToBool (const APValue &Val, bool &Result)
static bool EvaluateAsBooleanCondition (const Expr *E, bool &Result, EvalInfo &Info)
template<typename T >
static bool HandleOverflow (EvalInfo &Info, const Expr *E, const T &SrcValue, QualType DestType)
static bool HandleFloatToIntCast (EvalInfo &Info, const Expr *E, QualType SrcType, const APFloat &Value, QualType DestType, APSInt &Result)
static llvm::RoundingMode getActiveRoundingMode (EvalInfo &Info, const Expr *E, bool &DynamicRM)
Get rounding mode used for evaluation of the specified expression.
static bool checkFloatingPointResult (EvalInfo &Info, const Expr *E, APFloat::opStatus St)
Check if the given evaluation result is allowed for constant evaluation.
static bool HandleFloatToFloatCast (EvalInfo &Info, const Expr *E, QualType SrcType, QualType DestType, APFloat &Result)
static APSInt HandleIntToIntCast (EvalInfo &Info, const Expr *E, QualType DestType, QualType SrcType, const APSInt &Value)
static bool HandleIntToFloatCast (EvalInfo &Info, const Expr *E, const FPOptions FPO, QualType SrcType, const APSInt &Value, QualType DestType, APFloat &Result)
static bool truncateBitfieldValue (EvalInfo &Info, const Expr *E, APValue &Value, const FieldDecl *FD)
static bool EvalAndBitcastToAPInt (EvalInfo &Info, const Expr *E, llvm::APInt &Res)
template<typename Operation >
static bool CheckedIntArithmetic (EvalInfo &Info, const Expr *E, const APSInt &LHS, const APSInt &RHS, unsigned BitWidth, Operation Op, APSInt &Result)
Perform the given integer operation, which is known to need at most BitWidth bits, and check for overflow in the original type (if that type was not an unsigned type).
static bool handleIntIntBinOp (EvalInfo &Info, const Expr *E, const APSInt &LHS, BinaryOperatorKind Opcode, APSInt RHS, APSInt &Result)
Perform the given binary integer operation.
static bool handleFloatFloatBinOp (EvalInfo &Info, const BinaryOperator *E, APFloat &LHS, BinaryOperatorKind Opcode, const APFloat &RHS)
Perform the given binary floating-point operation, in-place, on LHS.
static bool handleLogicalOpForVector (const APInt &LHSValue, BinaryOperatorKind Opcode, const APInt &RHSValue, APInt &Result)
static bool handleLogicalOpForVector (const APFloat &LHSValue, BinaryOperatorKind Opcode, const APFloat &RHSValue, APInt &Result)
static bool handleLogicalOpForVector (const APValue &LHSValue, BinaryOperatorKind Opcode, const APValue &RHSValue, APInt &Result)
template<typename APTy >
static bool handleCompareOpForVectorHelper (const APTy &LHSValue, BinaryOperatorKind Opcode, const APTy &RHSValue, APInt &Result)
static bool handleCompareOpForVector (const APValue &LHSValue, BinaryOperatorKind Opcode, const APValue &RHSValue, APInt &Result)
static bool handleVectorVectorBinOp (EvalInfo &Info, const BinaryOperator *E, BinaryOperatorKind Opcode, APValue &LHSValue, const APValue &RHSValue)
static bool CastToDerivedClass (EvalInfo &Info, const Expr *E, LValue &Result, const RecordDecl *TruncatedType, unsigned TruncatedElements)
Cast an lvalue referring to a base subobject to a derived class, by truncating the lvalue's path to the given length.
static bool HandleLValueDirectBase (EvalInfo &Info, const Expr *E, LValue &Obj, const CXXRecordDecl *Derived, const CXXRecordDecl *Base, const ASTRecordLayout *RL=nullptr)
static bool HandleLValueBase (EvalInfo &Info, const Expr *E, LValue &Obj, const CXXRecordDecl *DerivedDecl, const CXXBaseSpecifier *Base)
static bool HandleLValueBasePath (EvalInfo &Info, const CastExpr *E, QualType Type, LValue &Result)
static bool CastToBaseClass (EvalInfo &Info, const Expr *E, LValue &Result, const CXXRecordDecl *DerivedRD, const CXXRecordDecl *BaseRD)
Cast an lvalue referring to a derived class to a known base subobject.
static bool HandleLValueMember (EvalInfo &Info, const Expr *E, LValue &LVal, const FieldDecl *FD, const ASTRecordLayout *RL=nullptr)
Update LVal to refer to the given field, which must be a member of the type currently described by LVal.
static bool HandleLValueIndirectMember (EvalInfo &Info, const Expr *E, LValue &LVal, const IndirectFieldDecl *IFD)
Update LVal to refer to the given indirect field.
static bool HandleSizeof (EvalInfo &Info, SourceLocation Loc, QualType Type, CharUnits &Size)
Get the size of the given type in char units.
static bool HandleLValueArrayAdjustment (EvalInfo &Info, const Expr *E, LValue &LVal, QualType EltTy, APSInt Adjustment)
Update a pointer value to model pointer arithmetic.
static bool HandleLValueArrayAdjustment (EvalInfo &Info, const Expr *E, LValue &LVal, QualType EltTy, int64_t Adjustment)
static bool HandleLValueComplexElement (EvalInfo &Info, const Expr *E, LValue &LVal, QualType EltTy, bool Imag)
Update an lvalue to refer to a component of a complex number.
static bool evaluateVarDeclInit (EvalInfo &Info, const Expr *E, const VarDecl *VD, CallStackFrame *Frame, unsigned Version, APValue *&Result)
Try to evaluate the initializer for a variable declaration.
static unsigned getBaseIndex (const CXXRecordDecl *Derived, const CXXRecordDecl *Base)
Get the base index of the given base class within an APValue representing the given derived class.
static APSInt extractStringLiteralCharacter (EvalInfo &Info, const Expr *Lit, uint64_t Index)
Extract the value of a character from a string literal.
static void expandStringLiteral (EvalInfo &Info, const StringLiteral *S, APValue &Result, QualType AllocType=QualType())
static void expandArray (APValue &Array, unsigned Index)
static bool isReadByLvalueToRvalueConversion (const CXXRecordDecl *RD)
Determine whether a type would actually be read by an lvalue-to-rvalue conversion.
static bool isReadByLvalueToRvalueConversion (QualType T)
static bool diagnoseMutableFields (EvalInfo &Info, const Expr *E, AccessKinds AK, QualType T)
Diagnose an attempt to read from any unreadable field within the specified type, which might be a class type.
static bool lifetimeStartedInEvaluation (EvalInfo &Info, APValue::LValueBase Base, bool MutableSubobject=false)
static QualType getSubobjectType (QualType ObjType, QualType SubobjType, bool IsMutable=false)
template<typename SubobjectHandler >
SubobjectHandler::result_type findSubobject (EvalInfo &Info, const Expr *E, const CompleteObject &Obj, const SubobjectDesignator &Sub, SubobjectHandler &handler)
Find the designated sub-object of an rvalue.
static bool extractSubobject (EvalInfo &Info, const Expr *E, const CompleteObject &Obj, const SubobjectDesignator &Sub, APValue &Result, AccessKinds AK=AK_Read)
Extract the designated sub-object of an rvalue.
static bool modifySubobject (EvalInfo &Info, const Expr *E, const CompleteObject &Obj, const SubobjectDesignator &Sub, APValue &NewVal)
Update the designated sub-object of an rvalue to the given value.
static unsigned FindDesignatorMismatch (QualType ObjType, const SubobjectDesignator &A, const SubobjectDesignator &B, bool &WasArrayIndex)
Find the position where two subobject designators diverge, or equivalently the length of the common initial subsequence.
static bool AreElementsOfSameArray (QualType ObjType, const SubobjectDesignator &A, const SubobjectDesignator &B)
Determine whether the given subobject designators refer to elements of the same array object.
static CompleteObject findCompleteObject (EvalInfo &Info, const Expr *E, AccessKinds AK, const LValue &LVal, QualType LValType)
Find the complete object to which an LValue refers.
static bool handleLValueToRValueConversion (EvalInfo &Info, const Expr *Conv, QualType Type, const LValue &LVal, APValue &RVal, bool WantObjectRepresentation=false)
Perform an lvalue-to-rvalue conversion on the given glvalue.
static bool handleAssignment (EvalInfo &Info, const Expr *E, const LValue &LVal, QualType LValType, APValue &Val)
Perform an assignment of Val to LVal. Takes ownership of Val.
static bool handleCompoundAssignment (EvalInfo &Info, const CompoundAssignOperator *E, const LValue &LVal, QualType LValType, QualType PromotedLValType, BinaryOperatorKind Opcode, const APValue &RVal)
Perform a compound assignment of LVal <op>= RVal.
static bool handleIncDec (EvalInfo &Info, const Expr *E, const LValue &LVal, QualType LValType, bool IsIncrement, APValue *Old)
Perform an increment or decrement on LVal.
static bool EvaluateObjectArgument (EvalInfo &Info, const Expr *Object, LValue &This)
Build an lvalue for the object argument of a member function call.
static const ValueDecl * HandleMemberPointerAccess (EvalInfo &Info, QualType LVType, LValue &LV, const Expr *RHS, bool IncludeMember=true)
HandleMemberPointerAccess - Evaluate a member access operation and build an lvalue referring to the result.
static const ValueDecl * HandleMemberPointerAccess (EvalInfo &Info, const BinaryOperator *BO, LValue &LV, bool IncludeMember=true)
static bool HandleBaseToDerivedCast (EvalInfo &Info, const CastExpr *E, LValue &Result)
HandleBaseToDerivedCast - Apply the given base-to-derived cast operation on the provided lvalue, which currently refers to the base object.
static bool getDefaultInitValue (QualType T, APValue &Result)
Get the value to use for a default-initialized object of type T.
static bool EvaluateVarDecl (EvalInfo &Info, const VarDecl *VD)
static bool EvaluateDecl (EvalInfo &Info, const Decl *D)
static bool EvaluateDependentExpr (const Expr *E, EvalInfo &Info)
static bool EvaluateCond (EvalInfo &Info, const VarDecl *CondDecl, const Expr *Cond, bool &Result)
Evaluate a condition (either a variable declaration or an expression).
static EvalStmtResult EvaluateStmt (StmtResult &Result, EvalInfo &Info, const Stmt *S, const SwitchCase *SC=nullptr)
static EvalStmtResult EvaluateLoopBody (StmtResult &Result, EvalInfo &Info, const Stmt *Body, const SwitchCase *Case=nullptr)
Evaluate the body of a loop, and translate the result as appropriate.
static EvalStmtResult EvaluateSwitch (StmtResult &Result, EvalInfo &Info, const SwitchStmt *SS)
Evaluate a switch statement.
static bool CheckTrivialDefaultConstructor (EvalInfo &Info, SourceLocation Loc, const CXXConstructorDecl *CD, bool IsValueInitialization)
CheckTrivialDefaultConstructor - Check whether a constructor is a trivial default constructor.
static bool CheckConstexprFunction (EvalInfo &Info, SourceLocation CallLoc, const FunctionDecl *Declaration, const FunctionDecl *Definition, const Stmt *Body)
CheckConstexprFunction - Check that a function can be called in a constant expression.
static bool checkDynamicType (EvalInfo &Info, const Expr *E, const LValue &This, AccessKinds AK, bool Polymorphic)
Check that we can access the notional vptr of an object / determine its dynamic type.
static bool checkNonVirtualMemberCallThisPointer (EvalInfo &Info, const Expr *E, const LValue &This, const CXXMethodDecl *NamedMember)
Check that the pointee of the 'this' pointer in a member function call is either within its lifetime or in its period of construction or destruction.
static const CXXRecordDecl * getBaseClassType (SubobjectDesignator &Designator, unsigned PathLength)
static Optional< DynamicType > ComputeDynamicType (EvalInfo &Info, const Expr *E, LValue &This, AccessKinds AK)
Determine the dynamic type of an object.
static const CXXMethodDecl * HandleVirtualDispatch (EvalInfo &Info, const Expr *E, LValue &This, const CXXMethodDecl *Found, llvm::SmallVectorImpl< QualType > &CovariantAdjustmentPath)
Perform virtual dispatch.
static bool HandleCovariantReturnAdjustment (EvalInfo &Info, const Expr *E, APValue &Result, ArrayRef< QualType > Path)
Perform the adjustment from a value returned by a virtual function to a value of the statically expected type, which may be a pointer or reference to a base class of the returned type.
static bool isBaseClassPublic (const CXXRecordDecl *Derived, const CXXRecordDecl *Base)
Determine whether Base, which is known to be a direct base class of Derived, is a public base class.
static bool HandleDynamicCast (EvalInfo &Info, const ExplicitCastExpr *E, LValue &Ptr)
Apply the given dynamic cast operation on the provided lvalue.
static bool HandleUnionActiveMemberChange (EvalInfo &Info, const Expr *LHSExpr, const LValue &LHS)
Handle a builtin simple-assignment or a call to a trivial assignment operator whose left-hand side might involve a union member access.
static bool EvaluateCallArg (const ParmVarDecl *PVD, const Expr *Arg, CallRef Call, EvalInfo &Info, bool NonNull=false)
static bool EvaluateArgs (ArrayRef< const Expr * > Args, CallRef Call, EvalInfo &Info, const FunctionDecl *Callee, bool RightToLeft=false)
Evaluate the arguments to a function call.
static bool handleTrivialCopy (EvalInfo &Info, const ParmVarDecl *Param, const Expr *E, APValue &Result, bool CopyObjectRepresentation)
Perform a trivial copy from Param, which is the parameter of a copy or move constructor or assignment operator.
static bool HandleFunctionCall (SourceLocation CallLoc, const FunctionDecl *Callee, const LValue *This, ArrayRef< const Expr * > Args, CallRef Call, const Stmt *Body, EvalInfo &Info, APValue &Result, const LValue *ResultSlot)
Evaluate a function call.
static bool HandleConstructorCall (const Expr *E, const LValue &This, CallRef Call, const CXXConstructorDecl *Definition, EvalInfo &Info, APValue &Result)
Evaluate a constructor call.
static bool HandleConstructorCall (const Expr *E, const LValue &This, ArrayRef< const Expr * > Args, const CXXConstructorDecl *Definition, EvalInfo &Info, APValue &Result)
static bool HandleDestructionImpl (EvalInfo &Info, SourceLocation CallLoc, const LValue &This, APValue &Value, QualType T)
static bool HandleOperatorNewCall (EvalInfo &Info, const CallExpr *E, LValue &Result)
Perform a call to 'perator new' or to ‘__builtin_operator_new’.
static bool hasVirtualDestructor (QualType T)
static const FunctionDecl * getVirtualOperatorDelete (QualType T)
static Optional< DynAlloc * > CheckDeleteKind (EvalInfo &Info, const Expr *E, const LValue &Pointer, DynAlloc::Kind DeallocKind)
Check that the given object is a suitable pointer to a heap allocation that still exists and is of the right kind for the purpose of a deletion.
bool HandleOperatorDeleteCall (EvalInfo &Info, const CallExpr *E)
static bool getBytesReturnedByAllocSizeCall (const ASTContext &Ctx, const CallExpr *Call, llvm::APInt &Result)
Attempts to compute the number of bytes available at the pointer returned by a function with the alloc_size attribute. Returns true if we were successful. Places an unsigned number into Result.
static bool getBytesReturnedByAllocSizeCall (const ASTContext &Ctx, const LValue &LVal, llvm::APInt &Result)
Convenience function. LVal's base must be a call to an alloc_size function.
static bool evaluateLValueAsAllocSize (EvalInfo &Info, APValue::LValueBase Base, LValue &Result)
Attempts to evaluate the given LValueBase as the result of a call to a function with the alloc_size attribute. If it was possible to do so, this function will return true, make Result's Base point to said function call, and mark Result's Base as invalid.
static CharUnits GetAlignOfType (EvalInfo &Info, QualType T, UnaryExprOrTypeTrait ExprKind)
static CharUnits GetAlignOfExpr (EvalInfo &Info, const Expr *E, UnaryExprOrTypeTrait ExprKind)
static CharUnits getBaseAlignment (EvalInfo &Info, const LValue &Value)
static bool getAlignmentArgument (const Expr *E, QualType ForType, EvalInfo &Info, APSInt &Alignment)
Evaluate the value of the alignment argument to __builtin_align_{up,down}, __builtin_is_aligned and __builtin_assume_aligned.
static bool isOneByteCharacterType (QualType T)
static bool EvaluateArrayNewInitList (EvalInfo &Info, LValue &This, APValue &Result, const InitListExpr *ILE, QualType AllocType)
static bool EvaluateArrayNewConstructExpr (EvalInfo &Info, LValue &This, APValue &Result, const CXXConstructExpr *CCE, QualType AllocType)
static bool HandleClassZeroInitialization (EvalInfo &Info, const Expr *E, const RecordDecl *RD, const LValue &This, APValue &Result)
Perform zero-initialization on an object of non-union class type. C++11 [dcl.init]p5: To zero-initialize an object or reference of type T means: [...] – if T is a (possibly cv-qualified) non-union class type, each non-static data member and each base-class subobject is zero-initialized.
static bool EvaluateRecord (const Expr *E, const LValue &This, APValue &Result, EvalInfo &Info)
static bool EvaluateVector (const Expr *E, APValue &Result, EvalInfo &Info)
static bool EvaluateArray (const Expr *E, const LValue &This, APValue &Result, EvalInfo &Info)
static bool MaybeElementDependentArrayFiller (const Expr *FillerExpr)
static GCCTypeClass EvaluateBuiltinClassifyType (QualType T, const LangOptions &LangOpts)
EvaluateBuiltinClassifyType - Evaluate __builtin_classify_type the same way as GCC.
static GCCTypeClass EvaluateBuiltinClassifyType (const CallExpr *E, const LangOptions &LangOpts)
EvaluateBuiltinClassifyType - Evaluate __builtin_classify_type the same way as GCC.
static bool EvaluateBuiltinConstantPForLValue (const APValue &LV)
EvaluateBuiltinConstantPForLValue - Determine the result of __builtin_constant_p when applied to the given pointer.
static bool EvaluateBuiltinConstantP (EvalInfo &Info, const Expr *Arg)
EvaluateBuiltinConstantP - Evaluate __builtin_constant_p as similarly to GCC as we can manage.
static QualType getObjectType (APValue::LValueBase B)
Retrieves the "underlying object type" of the given expression, as used by __builtin_object_size.
static const Expr * ignorePointerCastsAndParens (const Expr *E)
A more selective version of E->IgnoreParenCasts for tryEvaluateBuiltinObjectSize. This ignores some casts/parens that serve only to change the type of E. Ex. For E = (short*)((char*)(&foo)), returns &foo
static bool isDesignatorAtObjectEnd (const ASTContext &Ctx, const LValue &LVal)
Checks to see if the given LValue's Designator is at the end of the LValue's record layout. e.g. struct { struct { int a, b; } fst, snd; } obj; obj.fst // no obj.snd // yes obj.fst.a // no obj.fst.b // no obj.snd.a // no obj.snd.b // yes.
static bool refersToCompleteObject (const LValue &LVal)
Tests to see if the LValue has a user-specified designator (that isn't necessarily valid). Note that this always returns 'true' if the LValue has an unsized array as its first designator entry, because there's currently no way to tell if the user typed *foo or foo[0].
static bool isUserWritingOffTheEnd (const ASTContext &Ctx, const LValue &LVal)
Attempts to detect a user writing into a piece of memory that's impossible to figure out the size of by just using types.
static bool convertUnsignedAPIntToCharUnits (const llvm::APInt &Int, CharUnits &Result)
Converts the given APInt to CharUnits, assuming the APInt is unsigned. Fails if the conversion would cause loss of precision.
static bool determineEndOffset (EvalInfo &Info, SourceLocation ExprLoc, unsigned Type, const LValue &LVal, CharUnits &EndOffset)
Helper for tryEvaluateBuiltinObjectSize – Given an LValue, this will determine how many bytes exist from the beginning of the object to either the end of the current subobject, or the end of the object itself, depending on what the LValue looks like + the value of Type.
static bool tryEvaluateBuiltinObjectSize (const Expr *E, unsigned Type, EvalInfo &Info, uint64_t &Size)
Tries to evaluate the __builtin_object_size for E. If successful, returns true and stores the result in Size.
static bool getBuiltinAlignArguments (const CallExpr *E, EvalInfo &Info, APValue &Val, APSInt &Alignment)
static bool isOnePastTheEndOfCompleteObject (const ASTContext &Ctx, const LValue &LV)
Determine whether this is a pointer past the end of the complete object referred to by the lvalue.
static void addOrSubLValueAsInteger (APValue &LVal, const APSInt &Index, bool IsSub)
template<class SuccessCB , class AfterCB >
static bool EvaluateComparisonBinaryOperator (EvalInfo &Info, const BinaryOperator *E, SuccessCB &&Success, AfterCB &&DoAfter)
static bool TryEvaluateBuiltinNaN (const ASTContext &Context, QualType ResultTy, const Expr *Arg, bool SNaN, llvm::APFloat &Result)
static bool EvaluateVoid (const Expr *E, EvalInfo &Info)
static bool FastEvaluateAsRValue (const Expr *Exp, Expr::EvalResult &Result, const ASTContext &Ctx, bool &IsConst)
static bool hasUnacceptableSideEffect (Expr::EvalStatus &Result, Expr::SideEffectsKind SEK)
static bool EvaluateAsRValue (const Expr *E, Expr::EvalResult &Result, const ASTContext &Ctx, EvalInfo &Info)
static bool EvaluateAsInt (const Expr *E, Expr::EvalResult &ExprResult, const ASTContext &Ctx, Expr::SideEffectsKind AllowSideEffects, EvalInfo &Info)
static bool EvaluateAsFixedPoint (const Expr *E, Expr::EvalResult &ExprResult, const ASTContext &Ctx, Expr::SideEffectsKind AllowSideEffects, EvalInfo &Info)
static bool EvaluateDestruction (const ASTContext &Ctx, APValue::LValueBase Base, APValue DestroyedValue, QualType Type, SourceLocation Loc, Expr::EvalStatus &EStatus, bool IsConstantDestruction)
static ICEDiag NoDiag ()
static ICEDiag Worst (ICEDiag A, ICEDiag B)
static ICEDiag CheckEvalInICE (const Expr *E, const ASTContext &Ctx)
static ICEDiag CheckICE (const Expr *E, const ASTContext &Ctx)
static bool EvaluateCPlusPlus11IntegralConstantExpr (const ASTContext &Ctx, const Expr *E, llvm::APSInt *Value, SourceLocation *Loc)
Evaluate an expression as a C++11 integral constant expression.
Macro Definition Documentation
ABSTRACT_STMT
#define ABSTRACT_STMT (Node)
ABSTRACT_TYPE [1/2]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [2/2]
#define ABSTRACT_TYPE (Class, Base)
ABSTRACTCONDITIONALOPERATOR
#define ABSTRACTCONDITIONALOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
ADDRLABELEXPR
#define ADDRLABELEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITINDEXEXPR
#define ARRAYINITINDEXEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITLOOPEXPR
#define ARRAYINITLOOPEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYSUBSCRIPTEXPR
#define ARRAYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYTYPETRAITEXPR
#define ARRAYTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
ASMSTMT
#define ASMSTMT (Type, Base)
Value:
STMT(Type, Base)
ASTYPEEXPR
#define ASTYPEEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATOMICEXPR
#define ATOMICEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATTRIBUTEDSTMT
#define ATTRIBUTEDSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
BINARYCONDITIONALOPERATOR
#define BINARYCONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
BINARYOPERATOR
#define BINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
BLOCKEXPR
#define BLOCKEXPR (Type, Base)
Value:
EXPR(Type, Base)
BREAKSTMT
#define BREAKSTMT (Type, Base)
Value:
STMT(Type, Base)
BUILTIN_TYPE
#define BUILTIN_TYPE (ID, SINGLETON_ID)
BUILTINBITCASTEXPR
#define BUILTINBITCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CALLEXPR
#define CALLEXPR (Type, Base)
Value:
EXPR(Type, Base)
CAPTUREDSTMT
#define CAPTUREDSTMT (Type, Base)
Value:
STMT(Type, Base)
CASESTMT
#define CASESTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
CASTEXPR
#define CASTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CHARACTERLITERAL
#define CHARACTERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
CHOOSEEXPR
#define CHOOSEEXPR (Type, Base)
Value:
EXPR(Type, Base)
COAWAITEXPR
#define COAWAITEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
COMPOUNDASSIGNOPERATOR
#define COMPOUNDASSIGNOPERATOR (Type, Base)
Value:
BINARYOPERATOR(Type, Base)
COMPOUNDLITERALEXPR
#define COMPOUNDLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
COMPOUNDSTMT
#define COMPOUNDSTMT (Type, Base)
Value:
STMT(Type, Base)
CONCEPTSPECIALIZATIONEXPR
#define CONCEPTSPECIALIZATIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
CONDITIONALOPERATOR
#define CONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
CONSTANTEXPR
#define CONSTANTEXPR (Type, Base)
Value:
FULLEXPR(Type, Base)
CONTINUESTMT
#define CONTINUESTMT (Type, Base)
Value:
STMT(Type, Base)
CONVERTVECTOREXPR
#define CONVERTVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CORETURNSTMT
#define CORETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINEBODYSTMT
#define COROUTINEBODYSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINESUSPENDEXPR
#define COROUTINESUSPENDEXPR (Type, Base)
Value:
EXPR(Type, Base)
COYIELDEXPR
#define COYIELDEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
CSTYLECASTEXPR
#define CSTYLECASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CUDAKERNELCALLEXPR
#define CUDAKERNELCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXADDRSPACECASTEXPR
#define CXXADDRSPACECASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXBINDTEMPORARYEXPR
#define CXXBINDTEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXBOOLLITERALEXPR
#define CXXBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXCATCHSTMT
#define CXXCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXCONSTCASTEXPR
#define CXXCONSTCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXCONSTRUCTEXPR
#define CXXCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTARGEXPR
#define CXXDEFAULTARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTINITEXPR
#define CXXDEFAULTINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDELETEEXPR
#define CXXDELETEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEPENDENTSCOPEMEMBEREXPR
#define CXXDEPENDENTSCOPEMEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDYNAMICCASTEXPR
#define CXXDYNAMICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXFOLDEXPR
#define CXXFOLDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXFORRANGESTMT
#define CXXFORRANGESTMT (Type, Base)
Value:
STMT(Type, Base)
CXXFUNCTIONALCASTEXPR
#define CXXFUNCTIONALCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXINHERITEDCTORINITEXPR
#define CXXINHERITEDCTORINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXMEMBERCALLEXPR
#define CXXMEMBERCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXNAMEDCASTEXPR
#define CXXNAMEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXNEWEXPR
#define CXXNEWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNOEXCEPTEXPR
#define CXXNOEXCEPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNULLPTRLITERALEXPR
#define CXXNULLPTRLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXOPERATORCALLEXPR
#define CXXOPERATORCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXPSEUDODESTRUCTOREXPR
#define CXXPSEUDODESTRUCTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXREINTERPRETCASTEXPR
#define CXXREINTERPRETCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXREWRITTENBINARYOPERATOR
#define CXXREWRITTENBINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
CXXSCALARVALUEINITEXPR
#define CXXSCALARVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXSTATICCASTEXPR
#define CXXSTATICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXSTDINITIALIZERLISTEXPR
#define CXXSTDINITIALIZERLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTEMPORARYOBJECTEXPR
#define CXXTEMPORARYOBJECTEXPR (Type, Base)
Value:
CXXCONSTRUCTEXPR(Type, Base)
CXXTHISEXPR
#define CXXTHISEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTHROWEXPR
#define CXXTHROWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTRYSTMT
#define CXXTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXTYPEIDEXPR
#define CXXTYPEIDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUNRESOLVEDCONSTRUCTEXPR
#define CXXUNRESOLVEDCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUUIDOFEXPR
#define CXXUUIDOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEBUG_TYPE
#define DEBUG_TYPE "exprconstant"
Definition at line 63 of file ExprConstant.cpp.
DECLREFEXPR
#define DECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECLSTMT
#define DECLSTMT (Type, Base)
Value:
STMT(Type, Base)
DEFAULTSTMT
#define DEFAULTSTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
DEPENDENT_TYPE [1/2]
#define DEPENDENT_TYPE (Class, Base)
Value:
  case Type::Class:                                                            \
    llvm_unreachable(                                                          \
        "dependent types aren't supported in the constant evaluator!");
DEPENDENT_TYPE [2/2]
#define DEPENDENT_TYPE (ID, BASE)
Value:
case Type::ID:
DEPENDENTCOAWAITEXPR
#define DEPENDENTCOAWAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEPENDENTSCOPEDECLREFEXPR
#define DEPENDENTSCOPEDECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITEXPR
#define DESIGNATEDINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITUPDATEEXPR
#define DESIGNATEDINITUPDATEEXPR (Type, Base)
Value:
EXPR(Type, Base)
DOSTMT
#define DOSTMT (Type, Base)
Value:
STMT(Type, Base)
EXPLICITCASTEXPR
#define EXPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
EXPR
#define EXPR (Node, Base)
EXPRESSIONTRAITEXPR
#define EXPRESSIONTRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
EXPRWITHCLEANUPS
#define EXPRWITHCLEANUPS (Type, Base)
Value:
FULLEXPR(Type, Base)
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
    case BuiltinType::Id:
EXTVECTORELEMENTEXPR
#define EXTVECTORELEMENTEXPR (Type, Base)
Value:
EXPR(Type, Base)
FIXEDPOINTLITERAL
#define FIXEDPOINTLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FLOATING_TYPE
#define FLOATING_TYPE (ID, SINGLETON_ID)
Value:
    case BuiltinType::ID: return GCCTypeClass::RealFloat;
FLOATINGLITERAL
#define FLOATINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FORSTMT
#define FORSTMT (Type, Base)
Value:
STMT(Type, Base)
FULLEXPR
#define FULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
FUNCTIONPARMPACKEXPR
#define FUNCTIONPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
GCCASMSTMT
#define GCCASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
GENERICSELECTIONEXPR
#define GENERICSELECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
GNUNULLEXPR
#define GNUNULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
GOTOSTMT
#define GOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
IFSTMT
#define IFSTMT (Type, Base)
Value:
STMT(Type, Base)
IMAGE_TYPE
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
    case BuiltinType::Id:
IMAGINARYLITERAL
#define IMAGINARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
IMPLICITCASTEXPR
#define IMPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
IMPLICITVALUEINITEXPR
#define IMPLICITVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
INDIRECTGOTOSTMT
#define INDIRECTGOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
INITLISTEXPR
#define INITLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
INTEGERLITERAL
#define INTEGERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
LABELSTMT
#define LABELSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
LAMBDAEXPR
#define LAMBDAEXPR (Type, Base)
Value:
EXPR(Type, Base)
LAST_STMT_RANGE
#define LAST_STMT_RANGE (Base, First, Last)
Value:
STMT_RANGE(Base, First, Last)
MATERIALIZETEMPORARYEXPR
#define MATERIALIZETEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
MATRIXSUBSCRIPTEXPR
#define MATRIXSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
MEMBEREXPR
#define MEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
MSASMSTMT
#define MSASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
MSDEPENDENTEXISTSSTMT
#define MSDEPENDENTEXISTSSTMT (Type, Base)
Value:
STMT(Type, Base)
MSPROPERTYREFEXPR
#define MSPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
MSPROPERTYSUBSCRIPTEXPR
#define MSPROPERTYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
NOINITEXPR
#define NOINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
NON_CANONICAL_TYPE [1/2]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
  case Type::Class:                                                            \
    llvm_unreachable("non-canonical type should be impossible!");
NON_CANONICAL_TYPE [2/2]
#define NON_CANONICAL_TYPE (ID, BASE)
Value:
case Type::ID:
NON_CANONICAL_UNLESS_DEPENDENT
#define NON_CANONICAL_UNLESS_DEPENDENT (Class, Base)
Value:
  case Type::Class:                                                            \
    llvm_unreachable("either dependent or not canonical!");
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [1/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [2/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (ID, BASE)
Value:
case Type::ID:
NULLSTMT
#define NULLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCARRAYLITERAL
#define OBJCARRAYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCATCATCHSTMT
#define OBJCATCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATFINALLYSTMT
#define OBJCATFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATSYNCHRONIZEDSTMT
#define OBJCATSYNCHRONIZEDSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTHROWSTMT
#define OBJCATTHROWSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTRYSTMT
#define OBJCATTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAUTORELEASEPOOLSTMT
#define OBJCAUTORELEASEPOOLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAVAILABILITYCHECKEXPR
#define OBJCAVAILABILITYCHECKEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOOLLITERALEXPR
#define OBJCBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOXEDEXPR
#define OBJCBOXEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBRIDGEDCASTEXPR
#define OBJCBRIDGEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
OBJCDICTIONARYLITERAL
#define OBJCDICTIONARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCENCODEEXPR
#define OBJCENCODEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCFORCOLLECTIONSTMT
#define OBJCFORCOLLECTIONSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCINDIRECTCOPYRESTOREEXPR
#define OBJCINDIRECTCOPYRESTOREEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCISAEXPR
#define OBJCISAEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCIVARREFEXPR
#define OBJCIVARREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCMESSAGEEXPR
#define OBJCMESSAGEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROPERTYREFEXPR
#define OBJCPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROTOCOLEXPR
#define OBJCPROTOCOLEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSELECTOREXPR
#define OBJCSELECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSTRINGLITERAL
#define OBJCSTRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCSUBSCRIPTREFEXPR
#define OBJCSUBSCRIPTREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OFFSETOFEXPR
#define OFFSETOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSECTIONEXPR
#define OMPARRAYSECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSHAPINGEXPR
#define OMPARRAYSHAPINGEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPATOMICDIRECTIVE
#define OMPATOMICDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPBARRIERDIRECTIVE
#define OMPBARRIERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELDIRECTIVE
#define OMPCANCELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELLATIONPOINTDIRECTIVE
#define OMPCANCELLATIONPOINTDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCRITICALDIRECTIVE
#define OMPCRITICALDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDEPOBJDIRECTIVE
#define OMPDEPOBJDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDISTRIBUTEDIRECTIVE
#define OMPDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTESIMDDIRECTIVE
#define OMPDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPEXECUTABLEDIRECTIVE
#define OMPEXECUTABLEDIRECTIVE (Type, Base)
Value:
STMT(Type, Base)
OMPFLUSHDIRECTIVE
#define OMPFLUSHDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPFORDIRECTIVE
#define OMPFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPFORSIMDDIRECTIVE
#define OMPFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPITERATOREXPR
#define OMPITERATOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPLOOPDIRECTIVE
#define OMPLOOPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERDIRECTIVE
#define OMPMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPDIRECTIVE
#define OMPMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPSIMDDIRECTIVE
#define OMPMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPORDEREDDIRECTIVE
#define OMPORDEREDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELDIRECTIVE
#define OMPPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELFORDIRECTIVE
#define OMPPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELFORSIMDDIRECTIVE
#define OMPPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERDIRECTIVE
#define OMPPARALLELMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPDIRECTIVE
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELSECTIONSDIRECTIVE
#define OMPPARALLELSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSCANDIRECTIVE
#define OMPSCANDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONDIRECTIVE
#define OMPSECTIONDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONSDIRECTIVE
#define OMPSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSIMDDIRECTIVE
#define OMPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPSINGLEDIRECTIVE
#define OMPSINGLEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDATADIRECTIVE
#define OMPTARGETDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDIRECTIVE
#define OMPTARGETDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETENTERDATADIRECTIVE
#define OMPTARGETENTERDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETEXITDATADIRECTIVE
#define OMPTARGETEXITDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELDIRECTIVE
#define OMPTARGETPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORDIRECTIVE
#define OMPTARGETPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORSIMDDIRECTIVE
#define OMPTARGETPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETSIMDDIRECTIVE
#define OMPTARGETSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDIRECTIVE
#define OMPTARGETTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETUPDATEDIRECTIVE
#define OMPTARGETUPDATEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKDIRECTIVE
#define OMPTASKDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKGROUPDIRECTIVE
#define OMPTASKGROUPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKLOOPDIRECTIVE
#define OMPTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKLOOPSIMDDIRECTIVE
#define OMPTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKWAITDIRECTIVE
#define OMPTASKWAITDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKYIELDDIRECTIVE
#define OMPTASKYIELDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDIRECTIVE
#define OMPTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEDIRECTIVE
#define OMPTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTESIMDDIRECTIVE
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OPAQUEVALUEEXPR
#define OPAQUEVALUEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OVERLOADEXPR
#define OVERLOADEXPR (Type, Base)
Value:
EXPR(Type, Base)
PACKEXPANSIONEXPR
#define PACKEXPANSIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENEXPR
#define PARENEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENLISTEXPR
#define PARENLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
PLACEHOLDER_TYPE
#define PLACEHOLDER_TYPE (ID, SINGLETON_ID)
Value:
    case BuiltinType::ID: break;
PPC_VECTOR_TYPE
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
    case BuiltinType::Id:
PREDEFINEDEXPR
#define PREDEFINEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
PSEUDOOBJECTEXPR
#define PSEUDOOBJECTEXPR (Type, Base)
Value:
EXPR(Type, Base)
RECOVERYEXPR
#define RECOVERYEXPR (Type, Base)
Value:
EXPR(Type, Base)
REQUIRESEXPR
#define REQUIRESEXPR (Type, Base)
Value:
EXPR(Type, Base)
RETURNSTMT
#define RETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHEXCEPTSTMT
#define SEHEXCEPTSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHFINALLYSTMT
#define SEHFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHLEAVESTMT
#define SEHLEAVESTMT (Type, Base)
Value:
STMT(Type, Base)
SEHTRYSTMT
#define SEHTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
SHUFFLEVECTOREXPR
#define SHUFFLEVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
SIGNED_TYPE
#define SIGNED_TYPE (ID, SINGLETON_ID)
Value:
    case BuiltinType::ID: return GCCTypeClass::Integer;
SIZEOFPACKEXPR
#define SIZEOFPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SOURCELOCEXPR
#define SOURCELOCEXPR (Type, Base)
Value:
EXPR(Type, Base)
STMT
#define STMT (Node, Base)
Value:
case Expr::Node##Class:
STMT_RANGE
#define STMT_RANGE (Base, First, Last)
STMTEXPR
#define STMTEXPR (Type, Base)
Value:
EXPR(Type, Base)
STRINGLITERAL
#define STRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMEXPR
#define SUBSTNONTYPETEMPLATEPARMEXPR (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMPACKEXPR
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SVE_TYPE
#define SVE_TYPE (Name, Id, SingletonId)
Value:
    case BuiltinType::Id:
SWITCHCASE
#define SWITCHCASE (Type, Base)
Value:
STMT(Type, Base)
SWITCHSTMT
#define SWITCHSTMT (Type, Base)
Value:
STMT(Type, Base)
TYPE [1/2]
#define TYPE (Class, Base)
Value:
  case Type::Class:                                                            \
    return visit(cast<Class##Type>(Can.getTypePtr()), Offset);
TYPE [2/2]
#define TYPE (ID, BASE)
TYPETRAITEXPR
#define TYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
TYPOEXPR
#define TYPOEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYEXPRORTYPETRAITEXPR
#define UNARYEXPRORTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYOPERATOR
#define UNARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
UNRESOLVEDLOOKUPEXPR
#define UNRESOLVEDLOOKUPEXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDMEMBEREXPR
#define UNRESOLVEDMEMBEREXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
USERDEFINEDLITERAL
#define USERDEFINEDLITERAL (Type, Base)
Value:
CALLEXPR(Type, Base)
VAARGEXPR
#define VAARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
VALUESTMT
#define VALUESTMT (Type, Base)
Value:
STMT(Type, Base)
WHILESTMT
#define WHILESTMT (Type, Base)
Value:
STMT(Type, Base)
Typedef Documentation
CheckedTemporaries
using CheckedTemporaries
Initial value:
    llvm::SmallPtrSet<const MaterializeTemporaryExpr *, 8>
Materialized temporaries that we've already checked to determine if they're initializsed by a constant expression.
Definition at line 2102 of file ExprConstant.cpp.
Enumeration Type Documentation
CheckEvaluationResultKind
enum class CheckEvaluationResultKind strong
Enumerator
ConstantExpression
FullyInitialized
Definition at line 2095 of file ExprConstant.cpp.
GCCTypeClass
enum class GCCTypeClass strong
Values returned by __builtin_classify_type, chosen to match the values produced by GCC's builtin.
Enumerator
None
Void
Integer
Enum
Bool
Pointer
PointerToDataMember
RealFloat
Complex
PointerToMemberFunction
ClassOrStruct
Union
Definition at line 10868 of file ExprConstant.cpp.
Function Documentation
addOrSubLValueAsInteger()
static void addOrSubLValueAsInteger (APValue & LVal, const APSInt & Index, bool IsSub) static
Definition at line 12307 of file ExprConstant.cpp.
References clang::CharUnits::fromQuantity(), clang::APValue::getLValueOffset(), clang::APValue::hasLValuePath(), and Offset.
AreElementsOfSameArray()
static bool AreElementsOfSameArray (QualType ObjType, const SubobjectDesignator & A, const SubobjectDesignator & B) static
Determine whether the given subobject designators refer to elements of the same array object.
Definition at line 3918 of file ExprConstant.cpp.
References FindDesignatorMismatch().
CastToBaseClass()
static bool CastToBaseClass (EvalInfo & Info, const Expr * E, LValue & Result, const CXXRecordDecl * DerivedRD, const CXXRecordDecl * BaseRD) static
Cast an lvalue referring to a derived class to a known base subobject.
Definition at line 3100 of file ExprConstant.cpp.
References HandleLValueBase(), and clang::CXXRecordDecl::isDerivedFrom().
Referenced by HandleCovariantReturnAdjustment().
CastToDerivedClass()
static bool CastToDerivedClass (EvalInfo & Info, const Expr * E, LValue & Result, const RecordDecl * TruncatedType, unsigned TruncatedElements) static
Cast an lvalue referring to a base subobject to a derived class, by truncating the lvalue's path to the given length.
Definition at line 3018 of file ExprConstant.cpp.
References clang::CSK_Derived, clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::Decl::isInvalidDecl(), and N.
Referenced by HandleBaseToDerivedCast(), HandleDynamicCast(), HandleLValueBase(), HandleMemberPointerAccess(), and HandleVirtualDispatch().
CheckConstantExpression()
static bool CheckConstantExpression (EvalInfo & Info, SourceLocation DiagLoc, QualType Type, const APValue & Value, ConstantExprKind Kind) static
Check that this core constant expression value is a valid value for a constant expression.
If not, report an appropriate diagnostic. Does not check that the expression is of literal type.
Definition at line 2409 of file ExprConstant.cpp.
References CheckEvaluationResult(), ConstantExpression, and clang::Type::isVoidType().
Referenced by clang::Expr::EvaluateAsConstantExpr(), clang::Expr::EvaluateAsInitializer(), and EvaluateAsRValue().
CheckConstexprFunction()
static bool CheckConstexprFunction (EvalInfo & Info, SourceLocation CallLoc, const FunctionDecl * Declaration, const FunctionDecl * Definition, const Stmt * Body) static
CheckConstexprFunction - Check that a function can be called in a constant expression.
Definition at line 5434 of file ExprConstant.cpp.
References bool, clang::Declaration, clang::Definition, clang::ASTContext::getLangOpts(), clang::Decl::getLocation(), and clang::FunctionDecl::isConstexpr().
Referenced by HandleDestructionImpl().
CheckDeleteKind()
static Optional< DynAlloc * > CheckDeleteKind (EvalInfo & Info, const Expr * E, const LValue & Pointer, DynAlloc::Kind DeallocKind) static
Check that the given object is a suitable pointer to a heap allocation that still exists and is of the right kind for the purpose of a deletion.
On success, returns the heap allocation to deallocate. On failure, produces a diagnostic and returns None.
Definition at line 6645 of file ExprConstant.cpp.
References clang::None, NoteLValueLocation(), Pointer, and clang::ASTContext::VoidPtrTy.
Referenced by HandleOperatorDeleteCall().
checkDynamicType()
static bool checkDynamicType (EvalInfo & Info, const Expr * E, const LValue & This, AccessKinds AK, bool Polymorphic) static
Check that we can access the notional vptr of an object / determine its dynamic type.
Definition at line 5509 of file ExprConstant.cpp.
References findCompleteObject(), findSubobject(), clang::APValue::getAsString(), and clang::ASTContext::getLValueReferenceType().
Referenced by checkNonVirtualMemberCallThisPointer(), and ComputeDynamicType().
CheckedIntArithmetic()
template<typename Operation > static bool CheckedIntArithmetic (EvalInfo & Info, const Expr * E, const APSInt & LHS, const APSInt & RHS, unsigned BitWidth, Operation Op, APSInt & Result) static
Perform the given integer operation, which is known to need at most BitWidth bits, and check for overflow in the original type (if that type was not an unsigned type).
Definition at line 2702 of file ExprConstant.cpp.
References clang::ASTContext::getDiagnostics(), clang::Expr::getExprLoc(), clang::Expr::getType(), HandleOverflow(), and clang::DiagnosticsEngine::Report().
Referenced by handleIntIntBinOp().
CheckEvalInICE()
static ICEDiag CheckEvalInICE (const Expr * E, const ASTContext & Ctx) static
Definition at line 15053 of file ExprConstant.cpp.
References EvaluateAsRValue(), clang::Stmt::getBeginLoc(), clang::Expr::EvalStatus::HasSideEffects, clang::APValue::isInt(), NoDiag(), and clang::Expr::EvalResult::Val.
Referenced by CheckICE().
CheckEvaluationResult()
static bool CheckEvaluationResult (CheckEvaluationResultKind CERK, EvalInfo & Info, SourceLocation DiagLoc, QualType Type, const APValue & Value, ConstantExprKind Kind, SourceLocation SubobjectLoc, CheckedTemporaries & CheckedTemps) static
Definition at line 2325 of file ExprConstant.cpp.
References clang::Type::castAs(), clang::Type::castAsArrayTypeUnsafe(), CheckEvaluationResult(), CheckLValueConstantExpression(), CheckMemberPointerConstantExpression(), ConstantExpression, clang::RecordDecl::fields(), clang::Type::getAs(), clang::ArrayType::getElementType(), clang::SourceLocation::isValid(), N, and Type.
Referenced by CheckConstantExpression(), CheckEvaluationResult(), CheckFullyInitialized(), and CheckLValueConstantExpression().
checkFloatingPointResult()
static bool checkFloatingPointResult (EvalInfo & Info, const Expr * E, APFloat::opStatus St) static
Check if the given evaluation result is allowed for constant evaluation.
Definition at line 2549 of file ExprConstant.cpp.
References clang::LangOptions::FPE_Ignore, clang::Expr::getFPFeaturesInEffect(), and clang::ASTContext::getLangOpts().
Referenced by handleFloatFloatBinOp(), and HandleFloatToFloatCast().
CheckFullyInitialized()
static bool CheckFullyInitialized (EvalInfo & Info, SourceLocation DiagLoc, QualType Type, const APValue & Value) static
Check that this evaluated value is fully-initialized and can be loaded by an lvalue-to-rvalue conversion.
Definition at line 2424 of file ExprConstant.cpp.
References CheckEvaluationResult(), and FullyInitialized.
CheckICE()
static ICEDiag CheckICE (const Expr * E, const ASTContext & Ctx) static
Definition at line 15066 of file ExprConstant.cpp.
References clang::cast(), CheckEvalInICE(), CheckICE(), clang::Expr::EvaluateKnownConstInt(), clang::Stmt::getBeginLoc(), clang::CallExpr::getBuiltinCallee(), clang::BinaryConditionalOperator::getCommon(), clang::ConditionalOperator::getCond(), clang::BinaryConditionalOperator::getFalseExpr(), clang::ConditionalOperator::getFalseExpr(), clang::ASTContext::getIntWidth(), clang::UnaryExprOrTypeTraitExpr::getKind(), clang::ASTContext::getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::UnaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Stmt::getStmtClass(), clang::UnaryOperator::getSubExpr(), clang::ConditionalOperator::getTrueExpr(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::UnaryExprOrTypeTraitExpr::getTypeOfArgument(), clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isIntegralOrEnumerationType(), clang::Type::isReferenceType(), clang::Expr::isRValue(), clang::Type::isSignedIntegerOrEnumerationType(), clang::VarDecl::isUsableInConstantExpressions(), clang::Expr::isValueDependent(), clang::Type::isVariableArrayType(), NoDiag(), and Worst().
Referenced by CheckICE(), clang::Expr::isCXX98IntegralConstantExpr(), and clang::Expr::isIntegerConstantExpr().
CheckLiteralType()
static bool CheckLiteralType (EvalInfo & Info, const Expr * E, const LValue * This = nullptr) static
Check that this core constant expression is of literal type, and if not, produce an appropriate diagnostic.
Definition at line 2295 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isLiteralType(), and clang::Expr::isRValue().
Referenced by CheckConstexprDeclStmt(), CheckConstexprParameterTypes(), CheckConstexprReturnType(), EvaluateAsRValue(), and EvaluateInPlace().
CheckLValueConstantExpression()
static bool CheckLValueConstantExpression (EvalInfo & Info, SourceLocation Loc, QualType Type, const LValue & LVal, ConstantExprKind Kind, CheckedTemporaries & CheckedTemps) static
Check that this reference or pointer core constant expression is a valid value for an address or reference constant expression.
Return true if we can fold this expression, whether or not it's a constant expression.
Definition at line 2115 of file ExprConstant.cpp.
References CheckEvaluationResult(), ConstantExpression, clang::FixItHint::CreateInsertion(), getType(), clang::Type::isAnyPointerType(), clang::QualType::isDestructedType(), IsGlobalLValue(), clang::Type::isReferenceType(), NoteLValueLocation(), and V.
Referenced by CheckEvaluationResult(), and clang::Expr::EvaluateAsLValue().
CheckMemberPointerConstantExpression()
static bool CheckMemberPointerConstantExpression (EvalInfo & Info, SourceLocation Loc, QualType Type, const APValue & Value, ConstantExprKind Kind) static
Member pointers are constant expressions unless they point to a non-virtual dllimport member function.
Definition at line 2275 of file ExprConstant.cpp.
References clang::Member.
Referenced by CheckEvaluationResult().
CheckMemoryLeaks()
static bool CheckMemoryLeaks (EvalInfo & Info) static
Enforce C++2a [expr.const]/4.17, which disallows new-expressions unless "the allocated storage is deallocated within the evaluation".
Definition at line 2434 of file ExprConstant.cpp.
Referenced by clang::Expr::EvaluateAsConstantExpr(), clang::Expr::EvaluateAsInitializer(), and EvaluateAsRValue().
checkNonVirtualMemberCallThisPointer()
static bool checkNonVirtualMemberCallThisPointer (EvalInfo & Info, const Expr * E, const LValue & This, const CXXMethodDecl * NamedMember) static
Check that the pointee of the 'this' pointer in a member function call is either within its lifetime or in its period of construction or destruction.
Definition at line 5551 of file ExprConstant.cpp.
References clang::AK_Destroy, clang::AK_MemberCall, and checkDynamicType().
CheckTrivialDefaultConstructor()
static bool CheckTrivialDefaultConstructor (EvalInfo & Info, SourceLocation Loc, const CXXConstructorDecl * CD, bool IsValueInitialization) static
CheckTrivialDefaultConstructor - Check whether a constructor is a trivial default constructor.
If so, we'll fold it whether or not it's marked as constexpr. If it is marked as constexpr, we will never implicitly define it, so we need special handling.
Definition at line 5409 of file ExprConstant.cpp.
References clang::Decl::getLocation(), clang::FunctionDecl::isConstexpr(), clang::CXXConstructorDecl::isDefaultConstructor(), and clang::FunctionDecl::isTrivial().
ComputeDynamicType()
static Optional< DynamicType > ComputeDynamicType (EvalInfo & Info, const Expr * E, LValue & This, AccessKinds AK) static
Determine the dynamic type of an object.
Definition at line 5576 of file ExprConstant.cpp.
References checkDynamicType(), getBaseClassType(), and clang::None.
Referenced by HandleDynamicCast(), and HandleVirtualDispatch().
convertUnsignedAPIntToCharUnits()
static bool convertUnsignedAPIntToCharUnits (const llvm::APInt & Int, CharUnits & Result) static
Converts the given APInt to CharUnits, assuming the APInt is unsigned. Fails if the conversion would cause loss of precision.
Definition at line 11297 of file ExprConstant.cpp.
References clang::CharUnits::fromQuantity().
Referenced by determineEndOffset().
determineEndOffset()
static bool determineEndOffset (EvalInfo & Info, SourceLocation ExprLoc, unsigned Type, const LValue & LVal, CharUnits & EndOffset) static
Helper for tryEvaluateBuiltinObjectSize – Given an LValue, this will determine how many bytes exist from the beginning of the object to either the end of the current subobject, or the end of the object itself, depending on what the LValue looks like + the value of Type.
If this returns false, the value of Result is undefined.
Definition at line 11312 of file ExprConstant.cpp.
References convertUnsignedAPIntToCharUnits(), getBytesReturnedByAllocSizeCall(), getObjectType(), HandleSizeof(), clang::Type::isFunctionType(), clang::Type::isIncompleteType(), clang::QualType::isNull(), isUserWritingOffTheEnd(), and refersToCompleteObject().
Referenced by tryEvaluateBuiltinObjectSize().
diagnoseMutableFields()
static bool diagnoseMutableFields (EvalInfo & Info, const Expr * E, AccessKinds AK, QualType T) static
Diagnose an attempt to read from any unreadable field within the specified type, which might be a class type.
Definition at line 3464 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases(), diagnoseMutableFields(), clang::RecordDecl::fields(), clang::Expr::getType(), clang::CXXRecordDecl::hasMutableFields(), isReadByLvalueToRvalueConversion(), and clang::TagDecl::isUnion().
Referenced by diagnoseMutableFields(), and findSubobject().
EvalAndBitcastToAPInt()
static bool EvalAndBitcastToAPInt (EvalInfo & Info, const Expr * E, llvm::APInt & Res) static
Definition at line 2651 of file ExprConstant.cpp.
References clang::Type::castAs(), Evaluate(), clang::APValue::getFloat(), clang::APValue::getInt(), clang::ASTContext::getTargetInfo(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::APValue::getVectorElt(), clang::APValue::getVectorLength(), clang::TargetInfo::isBigEndian(), clang::APValue::isFloat(), clang::APValue::isInt(), and clang::APValue::isVector().
EvalPointerValueAsBool()
static bool EvalPointerValueAsBool (const APValue & Value, bool & Result) static
Definition at line 2446 of file ExprConstant.cpp.
Referenced by HandleConversionToBool().
Evaluate()
static bool Evaluate (APValue & Result, EvalInfo & Info, const Expr * E) static
Definition at line 14490 of file ExprConstant.cpp.
References clang::C, EvaluateArray(), EvaluateAtomic(), EvaluateComplex(), EvaluateFloat(), EvaluateLValue(), EvaluateMemberPointer(), EvaluatePointer(), EvaluateRecord(), EvaluateVector(), EvaluateVoid(), clang::QualType::getAtomicUnqualifiedType(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Expr::isGLValue(), clang::Type::isRecordType(), clang::Expr::isValueDependent(), and P.
Referenced by EvalAndBitcastToAPInt(), EvaluateAsBooleanCondition(), EvaluateAsRValue(), EvaluateIgnoredValue(), EvaluateInPlace(), EvaluateStmt(), clang::Expr::EvaluateWithSubstitution(), handleLValueToRValueConversion(), and clang::Expr::isPotentialConstantExprUnevaluated().
EvaluateArgs()
static bool EvaluateArgs (ArrayRef< const Expr * > Args, CallRef Call, EvalInfo & Info, const FunctionDecl * Callee, bool RightToLeft = false) static
Evaluate the arguments to a function call.
Definition at line 6007 of file ExprConstant.cpp.
References EvaluateCallArg(), and clang::NonNull.
Referenced by HandleConstructorCall().
EvaluateArray()
static bool EvaluateArray (const Expr * E, const LValue & This, APValue & Result, EvalInfo & Info) static
Definition at line 10382 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isArrayType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), and EvaluateInPlace().
EvaluateArrayNewConstructExpr()
static bool EvaluateArrayNewConstructExpr (EvalInfo & Info, LValue & This, APValue & Result, const CXXConstructExpr * CCE, QualType AllocType) static
Definition at line 10399 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isArrayType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
EvaluateArrayNewInitList()
static bool EvaluateArrayNewInitList (EvalInfo & Info, LValue & This, APValue & Result, const InitListExpr * ILE, QualType AllocType) static
Definition at line 10389 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isArrayType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
EvaluateAsBooleanCondition()
static bool EvaluateAsBooleanCondition (const Expr * E, bool & Result, EvalInfo & Info) static
Definition at line 2499 of file ExprConstant.cpp.
References Evaluate(), HandleConversionToBool(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by EvaluateCond(), and EvaluateStmt().
EvaluateAsFixedPoint()
static bool EvaluateAsFixedPoint (const Expr * E, Expr::EvalResult & ExprResult, const ASTContext & Ctx, Expr::SideEffectsKind AllowSideEffects, EvalInfo & Info) static
Definition at line 14693 of file ExprConstant.cpp.
References EvaluateAsRValue(), clang::Expr::getType(), hasUnacceptableSideEffect(), clang::Type::isFixedPointType(), and clang::Expr::isValueDependent().
EvaluateAsInt()
static bool EvaluateAsInt (const Expr * E, Expr::EvalResult & ExprResult, const ASTContext & Ctx, Expr::SideEffectsKind AllowSideEffects, EvalInfo & Info) static
Definition at line 14677 of file ExprConstant.cpp.
References EvaluateAsRValue(), clang::Expr::getType(), hasUnacceptableSideEffect(), clang::Type::isIntegralOrEnumerationType(), and clang::Expr::isValueDependent().
Referenced by clang::Expr::getIntegerConstantExpr(), and isInLoop().
EvaluateAsRValue() [1/2]
static bool EvaluateAsRValue (const Expr * E, Expr::EvalResult & Result, const ASTContext & Ctx, EvalInfo & Info) static
Definition at line 14667 of file ExprConstant.cpp.
References EvaluateAsRValue(), FastEvaluateAsRValue(), and clang::Expr::isValueDependent().
EvaluateAsRValue() [2/2]
static bool EvaluateAsRValue (EvalInfo & Info, const Expr * E, APValue & Result) static
EvaluateAsRValue - Try to evaluate this expression, performing an implicit lvalue-to-rvalue cast if it is an lvalue.
Definition at line 14603 of file ExprConstant.cpp.
References CheckConstantExpression(), CheckLiteralType(), CheckMemoryLeaks(), Evaluate(), clang::interp::Context::evaluateAsRValue(), clang::Expr::getExprLoc(), clang::ASTContext::getInterpContext(), clang::Expr::getType(), handleLValueToRValueConversion(), clang::Expr::isGLValue(), clang::QualType::isNull(), and clang::Expr::isValueDependent().
Referenced by CheckEvalInICE(), clang::Expr::EvaluateAsBooleanCondition(), EvaluateAsFixedPoint(), clang::Expr::EvaluateAsFloat(), EvaluateAsInt(), EvaluateAsRValue(), EvaluateBuiltinConstantP(), clang::Expr::EvaluateForOverflow(), clang::Expr::EvaluateKnownConstInt(), clang::Expr::EvaluateKnownConstIntCheckOverflow(), clang::Expr::isCXX11ConstantExpr(), clang::Expr::isEvaluatable(), and tryEvaluateBuiltinObjectSize().
EvaluateAtomic()
static bool EvaluateAtomic (const Expr * E, const LValue * This, APValue & Result, EvalInfo & Info) static
Definition at line 14354 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isAtomicType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), and EvaluateInPlace().
EvaluateBuiltinClassifyType() [1/2]
static GCCTypeClass EvaluateBuiltinClassifyType (const CallExpr * E, const LangOptions & LangOpts) static
EvaluateBuiltinClassifyType - Evaluate __builtin_classify_type the same way as GCC.
Definition at line 11039 of file ExprConstant.cpp.
References EvaluateBuiltinClassifyType(), clang::CallExpr::getArg(), clang::CallExpr::getNumArgs(), clang::Expr::getType(), and None.
EvaluateBuiltinClassifyType() [2/2]
static GCCTypeClass EvaluateBuiltinClassifyType (QualType T, const LangOptions & LangOpts) static
EvaluateBuiltinClassifyType - Evaluate __builtin_classify_type the same way as GCC.
Definition at line 10899 of file ExprConstant.cpp.
References Bool, clang::Type::castAs(), ClassOrStruct, Complex, Enum, EvaluateBuiltinClassifyType(), clang::QualType::getCanonicalType(), clang::BuiltinType::getKind(), clang::Type::getTypeClass(), clang::AtomicType::getValueType(), Integer, clang::Type::isMemberDataPointerType(), clang::Type::isUnionType(), None, Pointer, PointerToDataMember, PointerToMemberFunction, Union, and Void.
Referenced by EvaluateBuiltinClassifyType(), and EvaluateBuiltinClassifyType().
EvaluateBuiltinConstantP()
static bool EvaluateBuiltinConstantP (EvalInfo & Info, const Expr * Arg) static
EvaluateBuiltinConstantP - Evaluate __builtin_constant_p as similarly to GCC as we can manage.
Definition at line 11077 of file ExprConstant.cpp.
References EvaluateAsRValue(), EvaluateBuiltinConstantPForLValue(), clang::Expr::getType(), clang::Expr::EvalStatus::HasSideEffects, clang::APValue::LValue, and V.
EvaluateBuiltinConstantPForLValue()
static bool EvaluateBuiltinConstantPForLValue (const APValue & LV) static
EvaluateBuiltinConstantPForLValue - Determine the result of __builtin_constant_p when applied to the given pointer.
A pointer is only "constant" if it is null (or a pointer cast to integer) or it points to the first character of a string literal.
Definition at line 11056 of file ExprConstant.cpp.
References clang::APValue::getLValueBase(), clang::APValue::getLValueOffset(), and clang::CharUnits::isZero().
Referenced by EvaluateBuiltinConstantP().
EvaluateCallArg()
static bool EvaluateCallArg (const ParmVarDecl * PVD, const Expr * Arg, CallRef Call, EvalInfo & Info, bool NonNull = false) static
Definition at line 5981 of file ExprConstant.cpp.
References EvaluateInPlace(), clang::Expr::getType(), clang::NonNull, and V.
Referenced by EvaluateArgs(), and clang::Expr::EvaluateWithSubstitution().
EvaluateComparisonBinaryOperator()
template<class SuccessCB , class AfterCB > static bool EvaluateComparisonBinaryOperator (EvalInfo & Info, const BinaryOperator * E, SuccessCB && Success, AfterCB && DoAfter) static
Definition at line 12491 of file ExprConstant.cpp.
References clang::Equal, EvaluateComplex(), EvaluateFixedPointOrInteger(), EvaluateFloat(), EvaluateInteger(), EvaluateLValue(), EvaluateMemberPointer(), EvaluatePointer(), FindDesignatorMismatch(), clang::Decl::getAccess(), clang::ASTContext::getFixedPointSemantics(), clang::BinaryOperator::getFPFeaturesInEffect(), clang::ASTContext::getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::FieldDecl::getParent(), clang::CharUnits::getQuantity(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::getTypeSizeInChars(), HasSameBase(), clang::Type::isAnyComplexType(), clang::BinaryOperator::isAssignmentOp(), clang::BinaryOperator::isComparisonOp(), clang::BinaryOperator::isEqualityOp(), clang::Type::isFixedPointType(), clang::FPOptions::isFPConstrained(), clang::Type::isIncompleteType(), clang::Type::isIntegralOrEnumerationType(), IsLiteralLValue(), clang::Type::isMemberPointerType(), clang::APValue::LValueBase::isNull(), clang::Type::isNullPtrType(), isOnePastTheEndOfCompleteObject(), clang::Type::isPointerType(), clang::Type::isRealFloatingType(), clang::BinaryOperator::isRelationalOp(), clang::TagDecl::isUnion(), clang::Expr::isValueDependent(), clang::Type::isVoidPointerType(), IsWeakLValue(), clang::CharUnits::isZero(), and isZeroSized().
EvaluateComplex()
static bool EvaluateComplex (const Expr * E, ComplexValue & Res, EvalInfo & Info) static
Definition at line 13827 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), and EvaluateComparisonBinaryOperator().
EvaluateCond()
static bool EvaluateCond (EvalInfo & Info, const VarDecl * CondDecl, const Expr * Cond, bool & Result) static
Evaluate a condition (either a variable declaration or an expression).
Definition at line 4842 of file ExprConstant.cpp.
References EvaluateAsBooleanCondition(), EvaluateDecl(), and clang::Expr::isValueDependent().
Referenced by EvaluateStmt().
EvaluateCPlusPlus11IntegralConstantExpr()
static bool EvaluateCPlusPlus11IntegralConstantExpr (const ASTContext & Ctx, const Expr * E, llvm::APSInt * Value, SourceLocation * Loc) static
Evaluate an expression as a C++11 integral constant expression.
Definition at line 15461 of file ExprConstant.cpp.
References clang::Expr::getExprLoc(), clang::Expr::getType(), clang::Expr::isCXX11ConstantExpr(), and clang::Type::isIntegralOrUnscopedEnumerationType().
Referenced by clang::Expr::getIntegerConstantExpr(), and clang::Expr::isIntegerConstantExpr().
EvaluateDecl()
static bool EvaluateDecl (EvalInfo & Info, const Decl * D) static
Definition at line 4818 of file ExprConstant.cpp.
References EvaluateDecl(), and EvaluateVarDecl().
Referenced by EvaluateCond(), EvaluateDecl(), EvaluateStmt(), and EvaluateSwitch().
EvaluateDependentExpr()
static bool EvaluateDependentExpr (const Expr * E, EvalInfo & Info) static
Definition at line 4832 of file ExprConstant.cpp.
References clang::Expr::containsErrors(), and clang::Expr::isValueDependent().
Referenced by EvaluateStmt(), and HandleConstructorCall().
EvaluateDestruction()
static bool EvaluateDestruction (const ASTContext & Ctx, APValue::LValueBase Base, APValue DestroyedValue, QualType Type, SourceLocation Loc, Expr::EvalStatus & EStatus, bool IsConstantDestruction) static
Definition at line 14793 of file ExprConstant.cpp.
References HandleDestruction(), and clang::Expr::EvalStatus::HasSideEffects.
Referenced by clang::Expr::EvaluateAsConstantExpr(), and clang::VarDecl::evaluateDestruction().
EvaluateFixedPoint()
static bool EvaluateFixedPoint (const Expr * E, APFixedPoint & Result, EvalInfo & Info) static
Evaluate only a fixed point expression into an APResult.
Definition at line 10807 of file ExprConstant.cpp.
References clang::APValue::getFixedPoint(), clang::Expr::getType(), clang::APValue::isFixedPoint(), clang::Type::isFixedPointType(), and clang::Expr::isValueDependent().
Referenced by EvaluateFixedPointOrInteger().
EvaluateFixedPointOrInteger()
static bool EvaluateFixedPointOrInteger (const Expr * E, APFixedPoint & Result, EvalInfo & Info) static
Evaluate an integer or fixed point expression into an APResult.
Definition at line 10823 of file ExprConstant.cpp.
References EvaluateFixedPoint(), EvaluateInteger(), clang::ASTContext::getFixedPointSemantics(), clang::Expr::getType(), clang::Type::isFixedPointType(), clang::Type::isIntegerType(), and clang::Expr::isValueDependent().
Referenced by EvaluateComparisonBinaryOperator().
EvaluateFloat()
static bool EvaluateFloat (const Expr * E, APFloat & Result, EvalInfo & Info) static
Definition at line 13575 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isRealFloatingType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), and EvaluateComparisonBinaryOperator().
EvaluateIgnoredValue()
static bool EvaluateIgnoredValue (EvalInfo & Info, const Expr * E) static
Evaluate an expression to see if it had side-effects, and discard its result.
Returns
true if the caller should keep evaluating.
Definition at line 1944 of file ExprConstant.cpp.
References Evaluate(), and clang::Expr::isValueDependent().
Referenced by EvaluateStmt(), HandleOperatorDeleteCall(), and HandleOperatorNewCall().
EvaluateInPlace()
static bool EvaluateInPlace (APValue & Result, EvalInfo & Info, const LValue & This, const Expr * E, bool AllowNonLiteralTypes = false) static
EvaluateInPlace - Evaluate an expression in-place in an APValue. In some cases, the in-place evaluation is essential, since later initializers for an object can indirectly refer to subobjects which were initialized earlier.
Definition at line 14575 of file ExprConstant.cpp.
References CheckLiteralType(), Evaluate(), EvaluateArray(), EvaluateAtomic(), EvaluateRecord(), clang::QualType::getAtomicUnqualifiedType(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Type::isRecordType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by clang::Expr::EvaluateAsConstantExpr(), clang::Expr::EvaluateAsInitializer(), EvaluateCallArg(), EvaluateStmt(), EvaluateVarDecl(), HandleClassZeroInitialization(), and HandleConstructorCall().
EvaluateInteger()
static bool EvaluateInteger (const Expr * E, APSInt & Result, EvalInfo & Info) static
Definition at line 10786 of file ExprConstant.cpp.
References EvaluateIntegerOrLValue(), clang::APValue::getInt(), clang::APValue::isInt(), and clang::Expr::isValueDependent().
Referenced by EvaluateComparisonBinaryOperator(), EvaluateFixedPointOrInteger(), EvaluateSwitch(), getAlignmentArgument(), getBuiltinAlignArguments(), and HandleOperatorNewCall().
EvaluateIntegerOrLValue()
static bool EvaluateIntegerOrLValue (const Expr * E, APValue & Result, EvalInfo & Info) static
EvaluateIntegerOrLValue - Evaluate an rvalue integral-typed expression, and produce either the integer value or a pointer.
GCC has a heinous extension which folds casts between pointer types and pointer-sized integral types. We support this by allowing the evaluation of an integer rvalue to produce a pointer (represented as an lvalue) instead. Some simple arithmetic on such values is supported (they are treated much like char*).
Definition at line 10779 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isIntegralOrEnumerationType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by EvaluateInteger().
EvaluateLoopBody()
static EvalStmtResult EvaluateLoopBody (StmtResult & Result, EvalInfo & Info, const Stmt * Body, const SwitchCase * Case = nullptr) static
Evaluate the body of a loop, and translate the result as appropriate.
Definition at line 4883 of file ExprConstant.cpp.
References EvaluateStmt().
Referenced by EvaluateStmt().
EvaluateLValue()
static bool EvaluateLValue (const Expr * E, LValue & Result, EvalInfo & Info, bool InvalidBaseOK) static
Evaluate an expression as an lvalue. This can be legitimately called on expressions which are not glvalues, in three cases:
function designators in C, and
"extern void" objects
@selector() expressions in Objective-C
Definition at line 8107 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isFunctionType(), clang::Expr::isGLValue(), clang::Expr::isValueDependent(), and clang::Type::isVoidType().
Referenced by Evaluate(), clang::Expr::EvaluateAsLValue(), EvaluateComparisonBinaryOperator(), and EvaluateObjectArgument().
evaluateLValueAsAllocSize()
static bool evaluateLValueAsAllocSize (EvalInfo & Info, APValue::LValueBase Base, LValue & Result) static
Attempts to evaluate the given LValueBase as the result of a call to a function with the alloc_size attribute. If it was possible to do so, this function will return true, make Result's Base point to said function call, and mark Result's Base as invalid.
Definition at line 8525 of file ExprConstant.cpp.
References clang::Type::castAs(), clang::VarDecl::getAnyInitializer(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::QualType::isConstQualified(), and clang::VarDecl::isLocalVarDecl().
EvaluateMemberPointer()
static bool EvaluateMemberPointer (const Expr * E, MemberPtr & Result, EvalInfo & Info) static
Definition at line 9556 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isMemberPointerType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), EvaluateComparisonBinaryOperator(), HandleMemberPointerAccess(), and HandleMemberPointerAccess().
EvaluateObjectArgument()
static bool EvaluateObjectArgument (EvalInfo & Info, const Expr * Object, LValue & This) static
Build an lvalue for the object argument of a member function call.
Definition at line 4564 of file ExprConstant.cpp.
References EvaluateLValue(), EvaluatePointer(), and EvaluateTemporary().
Referenced by clang::Expr::EvaluateWithSubstitution(), and HandleMemberPointerAccess().
EvaluatePointer()
static bool EvaluatePointer (const Expr * E, LValue & Result, EvalInfo & Info, bool InvalidBaseOK = false) static
Definition at line 8668 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::hasPointerRepresentation(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), EvaluateComparisonBinaryOperator(), EvaluateObjectArgument(), getBuiltinAlignArguments(), HandleOperatorDeleteCall(), and tryEvaluateBuiltinObjectSize().
EvaluateRecord()
static bool EvaluateRecord (const Expr * E, const LValue & This, APValue & Result, EvalInfo & Info) static
Definition at line 10039 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isRecordType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by Evaluate(), and EvaluateInPlace().
EvaluateStmt()
static EvalStmtResult EvaluateStmt (StmtResult & Result, EvalInfo & Info, const Stmt * S, const SwitchCase * SC = nullptr) static
Definition at line 4980 of file ExprConstant.cpp.
References clang::CompoundStmt::body(), clang::cast(), clang::DeclStmt::decls(), Evaluate(), EvaluateAsBooleanCondition(), EvaluateCond(), EvaluateDecl(), EvaluateDependentExpr(), EvaluateIgnoredValue(), EvaluateInPlace(), EvaluateLoopBody(), EvaluateStmt(), EvaluateSwitch(), EvaluateVarDecl(), clang::DoStmt::getBody(), clang::WhileStmt::getBody(), clang::DoStmt::getCond(), clang::IfStmt::getCond(), clang::WhileStmt::getCond(), clang::IfStmt::getConditionVariable(), clang::WhileStmt::getConditionVariable(), clang::IfStmt::getElse(), clang::IfStmt::getInit(), clang::IfStmt::getThen(), and clang::Expr::isValueDependent().
Referenced by EvaluateLoopBody(), EvaluateStmt(), EvaluateSwitch(), HandleConstructorCall(), HandleDestructionImpl(), and HandleFunctionCall().
EvaluateSwitch()
static EvalStmtResult EvaluateSwitch (StmtResult & Result, EvalInfo & Info, const SwitchStmt * SS) static
Evaluate a switch statement.
Definition at line 4907 of file ExprConstant.cpp.
References clang::cast(), EvaluateDecl(), EvaluateInteger(), clang::Expr::EvaluateKnownConstInt(), EvaluateStmt(), clang::SwitchCase::getBeginLoc(), clang::SwitchStmt::getBody(), clang::SwitchStmt::getCond(), clang::SwitchStmt::getConditionVariable(), clang::SwitchStmt::getInit(), clang::CaseStmt::getLHS(), clang::SwitchCase::getNextSwitchCase(), clang::CaseStmt::getRHS(), and clang::SwitchStmt::getSwitchCaseList().
Referenced by EvaluateStmt().
EvaluateTemporary()
static bool EvaluateTemporary (const Expr * E, LValue & Result, EvalInfo & Info) static
Evaluate an expression of record type as a temporary.
Definition at line 10096 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::isRecordType(), clang::Expr::isRValue(), and clang::Expr::isValueDependent().
Referenced by EvaluateObjectArgument().
EvaluateVarDecl()
static bool EvaluateVarDecl (EvalInfo & Info, const VarDecl * VD) static
Definition at line 4790 of file ExprConstant.cpp.
References EvaluateInPlace(), getDefaultInitValue(), clang::VarDecl::getInit(), clang::ValueDecl::getType(), clang::VarDecl::hasLocalStorage(), clang::Type::isDependentType(), and clang::Expr::isValueDependent().
Referenced by EvaluateDecl(), and EvaluateStmt().
evaluateVarDeclInit()
static bool evaluateVarDeclInit (EvalInfo & Info, const Expr * E, const VarDecl * VD, CallStackFrame * Frame, unsigned Version, APValue *& Result) static
Try to evaluate the initializer for a variable declaration.
Parameters
Info Information about the ongoing evaluation.
E An expression to be used when printing diagnostics.
VD The variable whose initializer should be obtained.
Version The version of the variable within the frame.
Frame The frame in which the variable was created. Must be null if this variable is not local to the evaluation.
Result Filled in with a pointer to the value of the variable.
Definition at line 3217 of file ExprConstant.cpp.
References clang::DeclContext::Equals(), clang::VarDecl::evaluateValue(), clang::VarDecl::getAnyInitializer(), clang::Stmt::getBeginLoc(), clang::Decl::getDeclContext(), clang::VarDecl::getEvaluatedValue(), clang::ValueDecl::getType(), clang::VarDecl::hasConstantInitialization(), clang::VarDecl::hasICEInitializer(), clang::VarDecl::isInitCapture(), clang::isLambdaCallOperator(), clang::ValueDecl::isWeak(), clang::VarDecl::mightBeUsableInConstantExpressions(), and NoteLValueLocation().
Referenced by findCompleteObject().
EvaluateVector()
static bool EvaluateVector (const Expr * E, APValue & Result, EvalInfo & Info) static
Definition at line 10139 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Expr::isRValue(), and clang::Type::isVectorType().
Referenced by Evaluate().
EvaluateVoid()
static bool EvaluateVoid (const Expr * E, EvalInfo & Info) static
Definition at line 14480 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Expr::isRValue(), clang::Expr::isValueDependent(), and clang::Type::isVoidType().
Referenced by Evaluate().
expandArray()
static void expandArray (APValue & Array, unsigned Index) static
Definition at line 3412 of file ExprConstant.cpp.
References clang::APValue::getArrayFiller(), clang::APValue::getArrayInitializedElt(), clang::APValue::hasArrayFiller(), and clang::APValue::swap().
Referenced by findSubobject(), and HandleDestructionImpl().
expandStringLiteral()
static void expandStringLiteral (EvalInfo & Info, const StringLiteral * S, APValue & Result, QualType AllocType = QualType()) static
Definition at line 3389 of file ExprConstant.cpp.
References clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getCharWidth(), clang::ArrayType::getElementType(), clang::ConstantArrayType::getSize(), clang::Type::isIntegerType(), clang::Type::isUnsignedIntegerType(), and N.
extractStringLiteralCharacter()
static APSInt extractStringLiteralCharacter (EvalInfo & Info, const Expr * Lit, uint64_t Index) static
Extract the value of a character from a string literal.
Definition at line 3356 of file ExprConstant.cpp.
References clang::cast(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getCharWidth(), clang::ArrayType::getElementType(), clang::ASTContext::getObjCEncodingForType(), clang::Type::isIntegerType(), and clang::Type::isUnsignedIntegerType().
Referenced by handleLValueToRValueConversion().
extractSubobject()
static bool extractSubobject (EvalInfo & Info, const Expr * E, const CompleteObject & Obj, const SubobjectDesignator & Sub, APValue & Result, AccessKinds AK = AK_Read) static
Extract the designated sub-object of an rvalue.
Definition at line 3813 of file ExprConstant.cpp.
References clang::AK_Read, clang::AK_ReadObjectRepresentation, and findSubobject().
Referenced by handleLValueToRValueConversion().
FastEvaluateAsRValue()
static bool FastEvaluateAsRValue (const Expr * Exp, Expr::EvalResult & Result, const ASTContext & Ctx, bool & IsConst) static
Definition at line 14632 of file ExprConstant.cpp.
References clang::ASTContext::getLangOpts(), clang::Expr::getType(), clang::Type::isArrayType(), clang::QualType::isNull(), clang::Type::isRecordType(), and clang::Expr::isRValue().
Referenced by EvaluateAsRValue(), and clang::Expr::EvaluateForOverflow().
findCompleteObject()
static CompleteObject findCompleteObject (EvalInfo & Info, const Expr * E, AccessKinds AK, const LValue & LVal, QualType LValType) static
Find the complete object to which an LValue refers.
Definition at line 3938 of file ExprConstant.cpp.
References clang::APValue::LValueBase::dyn_cast(), evaluateVarDeclInit(), clang::APValue::getAsString(), clang::VarDecl::getDefinition(), clang::APValue::LValueBase::getDynamicAllocType(), clang::Decl::getLocation(), clang::ASTContext::getLValueReferenceType(), clang::APValue::LValueBase::getType(), getType(), clang::APValue::LValueBase::getVersion(), clang::VarDecl::hasDefinition(), clang::Expr::EvalStatus::HasSideEffects, clang::APValue::LValueBase::is(), isAnyAccess(), clang::VarDecl::isConstexpr(), isFormalAccess(), clang::Decl::isInvalidDecl(), isModification(), clang::QualType::isVolatileQualified(), lifetimeStartedInEvaluation(), NoteLValueLocation(), clang::SD_Static, and V.
Referenced by checkDynamicType(), handleAssignment(), handleCompoundAssignment(), HandleDestruction(), handleIncDec(), handleLValueToRValueConversion(), and HandleUnionActiveMemberChange().
FindDesignatorMismatch()
static unsigned FindDesignatorMismatch (QualType ObjType, const SubobjectDesignator & A, const SubobjectDesignator & B, bool & WasArrayIndex) static
Find the position where two subobject designators diverge, or equivalently the length of the common initial subsequence.
Definition at line 3881 of file ExprConstant.cpp.
References clang::Type::castAs(), clang::Type::castAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), clang::Type::isAnyComplexType(), clang::Type::isArrayType(), clang::QualType::isNull(), and N.
Referenced by AreElementsOfSameArray(), and EvaluateComparisonBinaryOperator().
findSubobject()
template<typename SubobjectHandler > SubobjectHandler::result_type findSubobject (EvalInfo & Info, const Expr * E, const CompleteObject & Obj, const SubobjectDesignator & Sub, SubobjectHandler & handler)
Find the designated sub-object of an rvalue.
Definition at line 3589 of file ExprConstant.cpp.
References clang::AK_Construct, clang::Type::castAs(), diagnoseMutableFields(), clang::APValue::LValueBase::dyn_cast(), expandArray(), clang::APValue::getArrayFiller(), clang::APValue::getArrayInitializedElt(), clang::APValue::getArrayInitializedElts(), clang::ASTContext::getAsConstantArrayType(), clang::Type::getAsCXXRecordDecl(), getBaseIndex(), clang::FieldDecl::getCanonicalDecl(), clang::ASTContext::getCanonicalType(), clang::APValue::getComplexFloatImag(), clang::APValue::getComplexFloatReal(), clang::APValue::getComplexIntImag(), clang::APValue::getComplexIntReal(), clang::ArrayType::getElementType(), clang::ComplexType::getElementType(), clang::Expr::getExprLoc(), clang::Decl::getLocation(), clang::ASTContext::getRecordType(), clang::ConstantArrayType::getSize(), clang::APValue::getStructBase(), clang::APValue::getStructField(), getSubobjectType(), clang::APValue::getUnionField(), clang::APValue::getUnionValue(), clang::APValue::isAbsent(), clang::Type::isAnyComplexType(), clang::Type::isArrayType(), clang::FieldDecl::isBitField(), clang::APValue::isComplexFloat(), clang::APValue::isComplexInt(), clang::QualType::isConstQualified(), isFormalAccess(), clang::APValue::isIndeterminate(), isModification(), isRead(), clang::Type::isRecordType(), clang::TagDecl::isUnion(), isValidIndeterminateAccess(), clang::QualType::isVolatileQualified(), N, clang::QualType::removeLocalConst(), clang::QualType::removeLocalVolatile(), clang::APValue::setUnion(), and truncateBitfieldValue().
Referenced by checkDynamicType(), extractSubobject(), handleCompoundAssignment(), HandleDestruction(), handleIncDec(), HandleUnionActiveMemberChange(), and modifySubobject().
getActiveRoundingMode()
static llvm::RoundingMode getActiveRoundingMode (EvalInfo & Info, const Expr * E, bool & DynamicRM) static
Get rounding mode used for evaluation of the specified expression.
Parameters
[out] DynamicRM Is set to true is the requested rounding mode is dynamic. If rounding mode is unknown at compile time, still try to evaluate the expression. If the result is exact, it does not depend on rounding mode. So return "tonearest" mode instead of "dynamic".
Definition at line 2538 of file ExprConstant.cpp.
References clang::Expr::getFPFeaturesInEffect(), and clang::ASTContext::getLangOpts().
Referenced by handleFloatFloatBinOp(), and HandleFloatToFloatCast().
getAlignmentArgument()
static bool getAlignmentArgument (const Expr * E, QualType ForType, EvalInfo & Info, APSInt & Alignment) static
Evaluate the value of the alignment argument to __builtin_align_{up,down}, __builtin_is_aligned and __builtin_assume_aligned.
Definition at line 8892 of file ExprConstant.cpp.
References EvaluateInteger(), and clang::ASTContext::getIntWidth().
Referenced by getBuiltinAlignArguments().
GetAlignOfExpr()
static CharUnits GetAlignOfExpr (EvalInfo & Info, const Expr * E, UnaryExprOrTypeTrait ExprKind) static
Definition at line 8861 of file ExprConstant.cpp.
References GetAlignOfType(), clang::ASTContext::getDeclAlign(), clang::Expr::getType(), and clang::Expr::IgnoreParens().
Referenced by getBaseAlignment().
GetAlignOfType()
static CharUnits GetAlignOfType (EvalInfo & Info, QualType T, UnaryExprOrTypeTrait ExprKind) static
Definition at line 8834 of file ExprConstant.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::ASTContext::getPreferredTypeAlign(), clang::ASTContext::getTypeAlignInChars(), clang::CharUnits::One(), and clang::ASTContext::toCharUnitsFromBits().
Referenced by GetAlignOfExpr(), and getBaseAlignment().
getBaseAlignment()
static CharUnits getBaseAlignment (EvalInfo & Info, const LValue & Value) static
Definition at line 8882 of file ExprConstant.cpp.
References GetAlignOfExpr(), GetAlignOfType(), and clang::ASTContext::getDeclAlign().
getBaseClassType()
static const CXXRecordDecl * getBaseClassType (SubobjectDesignator & Designator, unsigned PathLength) static
Definition at line 5566 of file ExprConstant.cpp.
Referenced by ComputeDynamicType(), HandleDynamicCast(), and HandleVirtualDispatch().
getBaseIndex()
static unsigned getBaseIndex (const CXXRecordDecl * Derived, const CXXRecordDecl * Base) static
Get the base index of the given base class within an APValue representing the given derived class.
Definition at line 3342 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases_begin(), and clang::CXXRecordDecl::bases_end().
Referenced by findSubobject().
getBuiltinAlignArguments()
static bool getBuiltinAlignArguments (const CallExpr * E, EvalInfo & Info, APValue & Val, APSInt & Alignment) static
Definition at line 11444 of file ExprConstant.cpp.
References EvaluateInteger(), EvaluatePointer(), getAlignmentArgument(), clang::CallExpr::getArg(), clang::Expr::getType(), clang::APValue::hasValue(), clang::Type::isIntegralOrEnumerationType(), and clang::Type::isPointerType().
getBytesReturnedByAllocSizeCall() [1/2]
static bool getBytesReturnedByAllocSizeCall (const ASTContext & Ctx, const CallExpr * Call, llvm::APInt & Result) static
Attempts to compute the number of bytes available at the pointer returned by a function with the alloc_size attribute. Returns true if we were successful. Places an unsigned number into Result.
This expects the given CallExpr to be a call to a function with an alloc_size attribute.
Definition at line 8464 of file ExprConstant.cpp.
References clang::Expr::EvaluateAsInt(), clang::ParamIdx::getASTIndex(), clang::AllocSizeAttr::getElemSizeParam(), clang::AllocSizeAttr::getNumElemsParam(), clang::ASTContext::getSizeType(), clang::ASTContext::getTypeSize(), clang::ParamIdx::isValid(), and clang::Expr::SE_AllowSideEffects.
Referenced by determineEndOffset(), and getBytesReturnedByAllocSizeCall().
getBytesReturnedByAllocSizeCall() [2/2]
static bool getBytesReturnedByAllocSizeCall (const ASTContext & Ctx, const LValue & LVal, llvm::APInt & Result) static
Convenience function. LVal's base must be a call to an alloc_size function.
Definition at line 8511 of file ExprConstant.cpp.
References getBytesReturnedByAllocSizeCall().
getDefaultInitValue()
static bool getDefaultInitValue (QualType T, APValue & Result) static
Get the value to use for a default-initialized object of type T.
Return false if it encounters something invalid.
Definition at line 4730 of file ExprConstant.cpp.
References getDefaultInitValue(), and clang::APValue::IndeterminateValue().
Referenced by clang::VarDecl::evaluateDestruction(), EvaluateVarDecl(), getDefaultInitValue(), and HandleConstructorCall().
GetLValueBaseDecl()
static const ValueDecl * GetLValueBaseDecl (const LValue & LVal) static
Definition at line 2022 of file ExprConstant.cpp.
References clang::APValue::LValueBase::dyn_cast().
Referenced by IsWeakLValue(), and isZeroSized().
getObjectType()
static QualType getObjectType (APValue::LValueBase B) static
Retrieves the "underlying object type" of the given expression, as used by __builtin_object_size.
Definition at line 11126 of file ExprConstant.cpp.
References clang::APValue::LValueBase::dyn_cast(), clang::APValue::LValueBase::getDynamicAllocType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::APValue::LValueBase::getTypeInfoType(), and clang::APValue::LValueBase::is().
Referenced by clang::Sema::checkInitMethod(), and determineEndOffset().
getSubobjectType()
static QualType getSubobjectType (QualType ObjType, QualType SubobjType, bool IsMutable = false) static
Definition at line 3572 of file ExprConstant.cpp.
References clang::QualType::addConst(), clang::QualType::addVolatile(), clang::QualType::isConstQualified(), and clang::QualType::isVolatileQualified().
Referenced by findSubobject().
getVirtualOperatorDelete()
static const FunctionDecl * getVirtualOperatorDelete (QualType T) static
Definition at line 6633 of file ExprConstant.cpp.
handleAssignment()
static bool handleAssignment (EvalInfo & Info, const Expr * E, const LValue & LVal, QualType LValType, APValue & Val) static
Perform an assignment of Val to LVal. Takes ownership of Val.
Definition at line 4260 of file ExprConstant.cpp.
References clang::AK_Assign, findCompleteObject(), and modifySubobject().
Referenced by HandleFunctionCall().
HandleBaseToDerivedCast()
static bool HandleBaseToDerivedCast (EvalInfo & Info, const CastExpr * E, LValue & Result) static
HandleBaseToDerivedCast - Apply the given base-to-derived cast operation on the provided lvalue, which currently refers to the base object.
Definition at line 4692 of file ExprConstant.cpp.
References CastToDerivedClass(), clang::CSK_Derived, clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getCanonicalDecl(), clang::Type::getPointeeType(), clang::Expr::getType(), and clang::CastExpr::path_size().
HandleClassZeroInitialization()
static bool HandleClassZeroInitialization (EvalInfo & Info, const Expr * E, const RecordDecl * RD, const LValue & This, APValue & Result) static
Perform zero-initialization on an object of non-union class type. C++11 [dcl.init]p5: To zero-initialize an object or reference of type T means: [...] – if T is a (possibly cv-qualified) non-union class type, each non-static data member and each base-class subobject is zero-initialized.
Definition at line 9660 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::CXXRecordDecl::bases_end(), EvaluateInPlace(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::RecordDecl::fields(), clang::ASTContext::getASTRecordLayout(), clang::CXXRecordDecl::getNumBases(), HandleClassZeroInitialization(), HandleLValueDirectBase(), HandleLValueMember(), clang::Decl::isInvalidDecl(), and clang::TagDecl::isUnion().
Referenced by HandleClassZeroInitialization().
handleCompareOpForVector()
static bool handleCompareOpForVector (const APValue & LHSValue, BinaryOperatorKind Opcode, const APValue & RHSValue, APInt & Result) static
Definition at line 2934 of file ExprConstant.cpp.
References clang::APValue::Float, clang::APValue::getFloat(), clang::APValue::getInt(), clang::APValue::getKind(), handleCompareOpForVectorHelper(), and clang::APValue::Int.
Referenced by handleVectorVectorBinOp().
handleCompareOpForVectorHelper()
template<typename APTy > static bool handleCompareOpForVectorHelper (const APTy & LHSValue, BinaryOperatorKind Opcode, const APTy & RHSValue, APInt & Result) static
Definition at line 2906 of file ExprConstant.cpp.
Referenced by handleCompareOpForVector().
handleCompoundAssignment()
static bool handleCompoundAssignment (EvalInfo & Info, const CompoundAssignOperator * E, const LValue & LVal, QualType LValType, QualType PromotedLValType, BinaryOperatorKind Opcode, const APValue & RVal) static
Perform a compound assignment of LVal <op>= RVal.
Definition at line 4399 of file ExprConstant.cpp.
References clang::AK_Assign, findCompleteObject(), and findSubobject().
HandleConstructorCall() [1/2]
static bool HandleConstructorCall (const Expr * E, const LValue & This, ArrayRef< const Expr * > Args, const CXXConstructorDecl * Definition, EvalInfo & Info, APValue & Result) static
Definition at line 6336 of file ExprConstant.cpp.
References clang::Definition, EvaluateArgs(), and HandleConstructorCall().
HandleConstructorCall() [2/2]
static bool HandleConstructorCall (const Expr * E, const LValue & This, CallRef Call, const CXXConstructorDecl * Definition, EvalInfo & Info, APValue & Result) static
Evaluate a constructor call.
Definition at line 6123 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::C, clang::cast(), clang::declaresSameEntity(), clang::Definition, EvaluateDependentExpr(), EvaluateInPlace(), EvaluateStmt(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::ASTContext::getASTRecordLayout(), getDefaultInitValue(), clang::Expr::getExprLoc(), clang::FieldDecl::getFieldIndex(), clang::CXXRecordDecl::getNumBases(), clang::CXXRecordDecl::getNumVBases(), clang::DeclContext::getParent(), clang::FieldDecl::getParent(), clang::ASTContext::getRecordType(), clang::CXXBaseSpecifier::getType(), HandleLValueDirectBase(), HandleLValueMember(), handleTrivialCopy(), clang::ASTContext::hasSameType(), clang::FieldDecl::isBitField(), clang::Decl::isInvalidDecl(), isReadByLvalueToRvalueConversion(), clang::TagDecl::isUnion(), clang::CXXBaseSpecifier::isVirtual(), Ret(), and truncateBitfieldValue().
Referenced by HandleConstructorCall(), and clang::Expr::isPotentialConstantExpr().
HandleConversionToBool()
static bool HandleConversionToBool (const APValue & Val, bool & Result) static
Definition at line 2461 of file ExprConstant.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::APValue::ComplexFloat, clang::APValue::ComplexInt, EvalPointerValueAsBool(), clang::APValue::FixedPoint, clang::APValue::Float, clang::APValue::getComplexFloatImag(), clang::APValue::getComplexFloatReal(), clang::APValue::getComplexIntImag(), clang::APValue::getComplexIntReal(), clang::APValue::getFixedPoint(), clang::APValue::getFloat(), clang::APValue::getInt(), clang::APValue::getKind(), clang::APValue::getMemberPointerDecl(), clang::APValue::Indeterminate, clang::APValue::Int, clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, clang::APValue::Struct, clang::APValue::Union, and clang::APValue::Vector.
Referenced by clang::Expr::EvaluateAsBooleanCondition(), and EvaluateAsBooleanCondition().
HandleCovariantReturnAdjustment()
static bool HandleCovariantReturnAdjustment (EvalInfo & Info, const Expr * E, APValue & Result, ArrayRef< QualType > Path) static
Perform the adjustment from a value returned by a virtual function to a value of the statically expected type, which may be a pointer or reference to a base class of the returned type.
Definition at line 5696 of file ExprConstant.cpp.
References CastToBaseClass().
HandleDestruction() [1/2]
static bool HandleDestruction (EvalInfo & Info, const Expr * E, const LValue & This, QualType ThisType) static
Perform a destructor or pseudo-destructor call on the given object, which might in general not be a complete object.
Definition at line 6541 of file ExprConstant.cpp.
References clang::AK_Destroy, findCompleteObject(), and findSubobject().
Referenced by EvaluateDestruction().
HandleDestruction() [2/2]
static bool HandleDestruction (EvalInfo & Info, SourceLocation Loc, APValue::LValueBase LVBase, APValue & Value, QualType T) static
Destroy and end the lifetime of the given complete object.
Definition at line 6549 of file ExprConstant.cpp.
References HandleDestructionImpl(), and clang::Expr::EvalStatus::HasSideEffects.
HandleDestructionImpl()
static bool HandleDestructionImpl (EvalInfo & Info, SourceLocation CallLoc, const LValue & This, APValue & Value, QualType T) static
Definition at line 6349 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases(), CheckConstexprFunction(), clang::Definition, EvaluateStmt(), expandArray(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::APValue::getArrayInitializedElt(), clang::ASTContext::getAsConstantArrayType(), clang::APValue::getAsString(), clang::ASTContext::getASTRecordLayout(), clang::FunctionDecl::getBody(), clang::CXXRecordDecl::getDestructor(), clang::ArrayType::getElementType(), clang::ASTContext::getLValueReferenceType(), clang::CXXRecordDecl::getNumBases(), clang::CXXRecordDecl::getNumVBases(), clang::ConstantArrayType::getSize(), clang::APValue::getStructBase(), clang::APValue::getStructField(), HandleDestructionImpl(), HandleLValueArrayAdjustment(), HandleLValueDirectBase(), HandleLValueMember(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::ASTContext::IntTy, clang::RecordDecl::isAnonymousStructOrUnion(), clang::FunctionDecl::isTrivial(), clang::TagDecl::isUnion(), Ret(), and clang::VK_RValue.
Referenced by HandleDestruction(), and HandleDestructionImpl().
HandleDynamicCast()
static bool HandleDynamicCast (EvalInfo & Info, const ExplicitCastExpr * E, LValue & Ptr) static
Apply the given dynamic cast operation on the provided lvalue.
This implements the hard case of dynamic_cast, requiring a "runtime check" to find a suitable target subobject.
Definition at line 5737 of file ExprConstant.cpp.
References clang::AK_DynamicCast, clang::AS_public, clang::C, CastToDerivedClass(), ComputeDynamicType(), clang::declaresSameEntity(), getBaseClassType(), clang::ASTContext::getCanonicalType(), clang::Type::getPointeeCXXRecordDecl(), clang::ASTContext::getRecordType(), clang::Expr::getType(), clang::ExplicitCastExpr::getTypeAsWritten(), clang::QualType::getUnqualifiedType(), HandleLValueBase(), isBaseClassPublic(), clang::Expr::isGLValue(), and clang::Type::isVoidPointerType().
handleFloatFloatBinOp()
static bool handleFloatFloatBinOp (EvalInfo & Info, const BinaryOperator * E, APFloat & LHS, BinaryOperatorKind Opcode, const APFloat & RHS) static
Perform the given binary floating-point operation, in-place, on LHS.
Definition at line 2827 of file ExprConstant.cpp.
References checkFloatingPointResult(), and getActiveRoundingMode().
Referenced by handleVectorVectorBinOp().
HandleFloatToFloatCast()
static bool HandleFloatToFloatCast (EvalInfo & Info, const Expr * E, QualType SrcType, QualType DestType, APFloat & Result) static
Definition at line 2589 of file ExprConstant.cpp.
References checkFloatingPointResult(), getActiveRoundingMode(), and clang::ASTContext::getFloatTypeSemantics().
HandleFloatToIntCast()
static bool HandleFloatToIntCast (EvalInfo & Info, const Expr * E, QualType SrcType, const APFloat & Value, QualType DestType, APSInt & Result) static
Definition at line 2517 of file ExprConstant.cpp.
References clang::ASTContext::getIntWidth(), HandleOverflow(), and clang::Type::isSignedIntegerOrEnumerationType().
HandleFunctionCall()
static bool HandleFunctionCall (SourceLocation CallLoc, const FunctionDecl * Callee, const LValue * This, ArrayRef< const Expr * > Args, CallRef Call, const Stmt * Body, EvalInfo & Info, APValue & Result, const LValue * ResultSlot) static
Evaluate a function call.
Definition at line 6065 of file ExprConstant.cpp.
References EvaluateStmt(), clang::CXXRecordDecl::getCaptureFields(), clang::FunctionDecl::getParamDecl(), clang::CXXMethodDecl::getParent(), clang::CXXMethodDecl::getThisType(), handleAssignment(), handleTrivialCopy(), HandleUnionActiveMemberChange(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::FunctionDecl::isDefaulted(), clang::isLambdaCallOperator(), clang::CXXMethodDecl::isMoveAssignmentOperator(), isReadByLvalueToRvalueConversion(), clang::FunctionDecl::isTrivial(), clang::TagDecl::isUnion(), and Ret().
Referenced by clang::Expr::isPotentialConstantExpr().
handleIncDec()
static bool handleIncDec (EvalInfo & Info, const Expr * E, const LValue & LVal, QualType LValType, bool IsIncrement, APValue * Old) static
Perform an increment or decrement on LVal.
Definition at line 4547 of file ExprConstant.cpp.
References clang::AK_Decrement, clang::AK_Increment, clang::cast(), findCompleteObject(), and findSubobject().
handleIntIntBinOp()
static bool handleIntIntBinOp (EvalInfo & Info, const Expr * E, const APSInt & LHS, BinaryOperatorKind Opcode, APSInt RHS, APSInt & Result) static
Perform the given binary integer operation.
Definition at line 2725 of file ExprConstant.cpp.
References CheckedIntArithmetic(), clang::Expr::getType(), and HandleOverflow().
Referenced by handleVectorVectorBinOp().
HandleIntToFloatCast()
static bool HandleIntToFloatCast (EvalInfo & Info, const Expr * E, const FPOptions FPO, QualType SrcType, const APSInt & Value, QualType DestType, APFloat & Result) static
Definition at line 2615 of file ExprConstant.cpp.
References clang::ASTContext::getFloatTypeSemantics(), and clang::FPOptions::isFPConstrained().
HandleIntToIntCast()
static APSInt HandleIntToIntCast (EvalInfo & Info, const Expr * E, QualType DestType, QualType SrcType, const APSInt & Value) static
Definition at line 2602 of file ExprConstant.cpp.
References clang::ASTContext::getIntWidth(), clang::Type::isBooleanType(), and clang::Type::isUnsignedIntegerOrEnumerationType().
handleLogicalOpForVector() [1/3]
static bool handleLogicalOpForVector (const APFloat & LHSValue, BinaryOperatorKind Opcode, const APFloat & RHSValue, APInt & Result) static
Definition at line 2879 of file ExprConstant.cpp.
handleLogicalOpForVector() [2/3]
static bool handleLogicalOpForVector (const APInt & LHSValue, BinaryOperatorKind Opcode, const APInt & RHSValue, APInt & Result) static
Definition at line 2867 of file ExprConstant.cpp.
Referenced by handleLogicalOpForVector(), and handleVectorVectorBinOp().
handleLogicalOpForVector() [3/3]
static bool handleLogicalOpForVector (const APValue & LHSValue, BinaryOperatorKind Opcode, const APValue & RHSValue, APInt & Result) static
Definition at line 2892 of file ExprConstant.cpp.
References clang::APValue::Float, clang::APValue::getFloat(), clang::APValue::getInt(), clang::APValue::getKind(), handleLogicalOpForVector(), and clang::APValue::Int.
HandleLValueArrayAdjustment() [1/2]
static bool HandleLValueArrayAdjustment (EvalInfo & Info, const Expr * E, LValue & LVal, QualType EltTy, APSInt Adjustment) static
Update a pointer value to model pointer arithmetic.
Parameters
Info - Information about the ongoing evaluation.
E - The expression being evaluated, for diagnostic purposes.
LVal - The pointer value to be updated.
EltTy - The pointee type represented by LVal.
Adjustment - The adjustment, in objects of type EltTy, to add.
Definition at line 3172 of file ExprConstant.cpp.
References clang::Expr::getExprLoc(), and HandleSizeof().
Referenced by HandleDestructionImpl(), and HandleLValueArrayAdjustment().
HandleLValueArrayAdjustment() [2/2]
static bool HandleLValueArrayAdjustment (EvalInfo & Info, const Expr * E, LValue & LVal, QualType EltTy, int64_t Adjustment) static
Definition at line 3183 of file ExprConstant.cpp.
References HandleLValueArrayAdjustment().
HandleLValueBase()
static bool HandleLValueBase (EvalInfo & Info, const Expr * E, LValue & Obj, const CXXRecordDecl * DerivedDecl, const CXXBaseSpecifier * Base) static
Definition at line 3061 of file ExprConstant.cpp.
References CastToDerivedClass(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getVBaseClassOffset(), HandleLValueDirectBase(), and clang::Decl::isInvalidDecl().
Referenced by CastToBaseClass(), HandleDynamicCast(), and HandleLValueBasePath().
HandleLValueBasePath()
static bool HandleLValueBasePath (EvalInfo & Info, const CastExpr * E, QualType Type, LValue & Result) static
Definition at line 3086 of file ExprConstant.cpp.
References clang::Type::getAsCXXRecordDecl(), HandleLValueBase(), clang::CastExpr::path_begin(), and clang::CastExpr::path_end().
HandleLValueComplexElement()
static bool HandleLValueComplexElement (EvalInfo & Info, const Expr * E, LValue & LVal, QualType EltTy, bool Imag) static
Update an lvalue to refer to a component of a complex number.
Parameters
Info - Information about the ongoing evaluation.
LVal - The lvalue to be updated.
EltTy - The complex number's component type.
Imag - False for the real component, true for the imaginary.
Definition at line 3195 of file ExprConstant.cpp.
References clang::Expr::getExprLoc(), and HandleSizeof().
HandleLValueDirectBase()
static bool HandleLValueDirectBase (EvalInfo & Info, const Expr * E, LValue & Obj, const CXXRecordDecl * Derived, const CXXRecordDecl * Base, const ASTRecordLayout * RL = nullptr) static
Definition at line 3047 of file ExprConstant.cpp.
References clang::ASTContext::getASTRecordLayout(), and clang::Decl::isInvalidDecl().
Referenced by HandleClassZeroInitialization(), HandleConstructorCall(), HandleDestructionImpl(), HandleLValueBase(), and HandleMemberPointerAccess().
HandleLValueIndirectMember()
static bool HandleLValueIndirectMember (EvalInfo & Info, const Expr * E, LValue & LVal, const IndirectFieldDecl * IFD) static
Update LVal to refer to the given indirect field.
Definition at line 3131 of file ExprConstant.cpp.
References clang::C, clang::IndirectFieldDecl::chain(), and HandleLValueMember().
Referenced by HandleMemberPointerAccess().
HandleLValueMember()
static bool HandleLValueMember (EvalInfo & Info, const Expr * E, LValue & LVal, const FieldDecl * FD, const ASTRecordLayout * RL = nullptr) static
Update LVal to refer to the given field, which must be a member of the type currently described by LVal.
Definition at line 3116 of file ExprConstant.cpp.
References clang::ASTContext::getASTRecordLayout(), clang::FieldDecl::getFieldIndex(), clang::FieldDecl::getParent(), clang::Decl::isInvalidDecl(), and clang::ASTContext::toCharUnitsFromBits().
Referenced by HandleClassZeroInitialization(), HandleConstructorCall(), HandleDestructionImpl(), HandleLValueIndirectMember(), and HandleMemberPointerAccess().
handleLValueToRValueConversion()
static bool handleLValueToRValueConversion (EvalInfo & Info, const Expr * Conv, QualType Type, const LValue & LVal, APValue & RVal, bool WantObjectRepresentation = false) static
Perform an lvalue-to-rvalue conversion on the given glvalue.
This can also be used for 'lvalue-to-lvalue' conversions for looking up the glvalue referred to by an entity of reference type.
Parameters
Info - Information about the ongoing evaluation.
Conv - The expression for which we are performing the conversion. Used for diagnostics.
Type - The type of the glvalue (before stripping cv-qualifiers in the case of a non-class type).
LVal - The glvalue on which we are attempting to perform this action.
RVal - The produced value will be placed here.
WantObjectRepresentation - If true, we're looking for the object representation rather than the value, and in particular, there is no requirement that the result be fully initialized.
Definition at line 4204 of file ExprConstant.cpp.
References clang::AK_Read, clang::AK_ReadObjectRepresentation, clang::APValue::LValueBase::dyn_cast(), Evaluate(), extractStringLiteralCharacter(), extractSubobject(), and findCompleteObject().
Referenced by EvaluateAsRValue(), and handleTrivialCopy().
HandleMemberPointerAccess() [1/2]
static const ValueDecl * HandleMemberPointerAccess (EvalInfo & Info, const BinaryOperator * BO, LValue & LV, bool IncludeMember = true) static
Definition at line 4672 of file ExprConstant.cpp.
References EvaluateMemberPointer(), EvaluateObjectArgument(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), and HandleMemberPointerAccess().
HandleMemberPointerAccess() [2/2]
static const ValueDecl * HandleMemberPointerAccess (EvalInfo & Info, QualType LVType, LValue & LV, const Expr * RHS, bool IncludeMember = true) static
HandleMemberPointerAccess - Evaluate a member access operation and build an lvalue referring to the result.
Parameters
Info - Information about the ongoing evaluation.
LV - An lvalue referring to the base of the member pointer.
RHS - The member pointer expression.
IncludeMember - Specifies whether the member itself is included in the resulting LValue subobject designator. This is not possible when creating a bound member function.
Returns
The field or method declaration to which the member pointer refers, or 0 if evaluation fails.
Definition at line 4590 of file ExprConstant.cpp.
References CastToDerivedClass(), EvaluateMemberPointer(), clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getCanonicalDecl(), clang::Type::getPointeeType(), HandleLValueDirectBase(), HandleLValueIndirectMember(), HandleLValueMember(), and N.
Referenced by HandleMemberPointerAccess().
HandleOperatorDeleteCall()
bool HandleOperatorDeleteCall (EvalInfo & Info, const CallExpr * E)
Definition at line 6693 of file ExprConstant.cpp.
References CheckDeleteKind(), EvaluateIgnoredValue(), EvaluatePointer(), clang::CallExpr::getArg(), clang::Expr::getExprLoc(), clang::CallExpr::getNumArgs(), N, and Pointer.
HandleOperatorNewCall()
static bool HandleOperatorNewCall (EvalInfo & Info, const CallExpr * E, LValue & Result) static
Perform a call to 'perator new' or to ‘__builtin_operator_new’.
Definition at line 6563 of file ExprConstant.cpp.
References EvaluateIgnoredValue(), EvaluateInteger(), clang::CallExpr::getArg(), clang::ASTContext::getConstantArrayType(), clang::Expr::getExprLoc(), clang::ConstantArrayType::getMaxSizeBits(), clang::CallExpr::getNumArgs(), clang::CharUnits::getQuantity(), clang::Expr::getType(), HandleSizeof(), clang::Type::isFunctionType(), clang::Type::isIncompleteType(), clang::Type::isNothrowT(), N, and clang::ArrayType::Normal.
HandleOverflow()
template<typename T > static bool HandleOverflow (EvalInfo & Info, const Expr * E, const T & SrcValue, QualType DestType) static
Definition at line 2510 of file ExprConstant.cpp.
Referenced by CheckedIntArithmetic(), HandleFloatToIntCast(), and handleIntIntBinOp().
HandleSizeof()
static bool HandleSizeof (EvalInfo & Info, SourceLocation Loc, QualType Type, CharUnits & Size) static
Get the size of the given type in char units.
Definition at line 3141 of file ExprConstant.cpp.
References clang::ASTContext::getTypeSizeInChars(), clang::Type::isConstantSizeType(), clang::Type::isDependentType(), clang::Type::isFunctionType(), clang::Type::isVoidType(), and clang::CharUnits::One().
Referenced by determineEndOffset(), HandleLValueArrayAdjustment(), HandleLValueComplexElement(), and HandleOperatorNewCall().
handleTrivialCopy()
static bool handleTrivialCopy (EvalInfo & Info, const ParmVarDecl * Param, const Expr * E, APValue & Result, bool CopyObjectRepresentation) static
Perform a trivial copy from Param, which is the parameter of a copy or move constructor or assignment operator.
Definition at line 6045 of file ExprConstant.cpp.
References clang::QualType::getNonReferenceType(), clang::Expr::getType(), and handleLValueToRValueConversion().
Referenced by HandleConstructorCall(), and HandleFunctionCall().
HandleUnionActiveMemberChange()
static bool HandleUnionActiveMemberChange (EvalInfo & Info, const Expr * LHSExpr, const LValue & LHS) static
Handle a builtin simple-assignment or a call to a trivial assignment operator whose left-hand side might involve a union member access.
If it does, implicitly start the lifetime of any accessed union elements per C++20 [class.union]5.
Definition at line 5885 of file ExprConstant.cpp.
References clang::AK_Assign, clang::declaresSameEntity(), findCompleteObject(), findSubobject(), clang::UnaryOperator::getSubExpr(), and clang::Expr::getType().
Referenced by HandleFunctionCall().
handleVectorVectorBinOp()
static bool handleVectorVectorBinOp (EvalInfo & Info, const BinaryOperator * E, BinaryOperatorKind Opcode, APValue & LHSValue, const APValue & RHSValue) static
Definition at line 2947 of file ExprConstant.cpp.
References clang::Type::castAs(), clang::APValue::Float, clang::APValue::getFloat(), clang::APValue::getInt(), clang::ASTContext::getIntWidth(), clang::APValue::getKind(), clang::VectorType::getNumElements(), clang::Expr::getType(), clang::APValue::getVectorElt(), clang::APValue::getVectorLength(), handleCompareOpForVector(), handleFloatFloatBinOp(), handleIntIntBinOp(), handleLogicalOpForVector(), clang::BinaryOperator::isComparisonOp(), clang::Type::isFloatingType(), clang::Type::isIntegerType(), clang::BinaryOperator::isLogicalOp(), clang::APValue::isLValue(), clang::Type::isUnsignedIntegerType(), and clang::APValue::isVector().
HandleVirtualDispatch()
static const CXXMethodDecl * HandleVirtualDispatch (EvalInfo & Info, const Expr * E, LValue & This, const CXXMethodDecl * Found, llvm::SmallVectorImpl< QualType > & CovariantAdjustmentPath) static
Perform virtual dispatch.
Definition at line 5631 of file ExprConstant.cpp.
References clang::AK_Destroy, clang::AK_MemberCall, CastToDerivedClass(), ComputeDynamicType(), getBaseClassType(), clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), clang::FunctionDecl::getReturnType(), clang::ASTContext::hasSameUnqualifiedType(), and Next.
HasSameBase()
static bool HasSameBase (const LValue & A, const LValue & B) static
Definition at line 2049 of file ExprConstant.cpp.
Referenced by EvaluateComparisonBinaryOperator().
hasUnacceptableSideEffect()
static bool hasUnacceptableSideEffect (Expr::EvalStatus & Result, Expr::SideEffectsKind SEK) static
Definition at line 14661 of file ExprConstant.cpp.
References clang::Expr::SE_AllowSideEffects, and clang::Expr::SE_AllowUndefinedBehavior.
Referenced by EvaluateAsFixedPoint(), clang::Expr::EvaluateAsFloat(), EvaluateAsInt(), and clang::Expr::isEvaluatable().
hasVirtualDestructor()
static bool hasVirtualDestructor (QualType T) static
Definition at line 6626 of file ExprConstant.cpp.
ignorePointerCastsAndParens()
static const Expr * ignorePointerCastsAndParens (const Expr * E) static
A more selective version of E->IgnoreParenCasts for tryEvaluateBuiltinObjectSize. This ignores some casts/parens that serve only to change the type of E. Ex. For E = (short*)((char*)(&foo)), returns &foo
Always returns an RValue with a pointer representation.
Definition at line 11148 of file ExprConstant.cpp.
References clang::Expr::getType(), clang::Type::hasPointerRepresentation(), clang::Expr::IgnoreParens(), ignorePointerCastsAndParens(), and clang::Expr::isRValue().
Referenced by ignorePointerCastsAndParens(), and tryEvaluateBuiltinObjectSize().
isAnyAccess()
static bool isAnyAccess (AccessKinds AK) static
Definition at line 1468 of file ExprConstant.cpp.
References isModification(), and isRead().
Referenced by findCompleteObject(), and isFormalAccess().
isBaseClassPublic()
static bool isBaseClassPublic (const CXXRecordDecl * Derived, const CXXRecordDecl * Base) static
Determine whether Base, which is known to be a direct base class of Derived, is a public base class.
Definition at line 5723 of file ExprConstant.cpp.
References clang::AS_public, clang::CXXRecordDecl::bases(), and clang::declaresSameEntity().
Referenced by HandleDynamicCast().
isDesignatorAtObjectEnd()
static bool isDesignatorAtObjectEnd (const ASTContext & Ctx, const LValue & LVal) static
Checks to see if the given LValue's Designator is at the end of the LValue's record layout. e.g. struct { struct { int a, b; } fst, snd; } obj; obj.fst // no obj.snd // yes obj.fst.a // no obj.fst.b // no obj.snd.a // no obj.snd.b // yes.
Please note: this function is specialized for how __builtin_object_size views "objects".
If this encounters an invalid RecordDecl or otherwise cannot determine the correct result, it will always return true.
Definition at line 11184 of file ExprConstant.cpp.
References clang::cast(), clang::Type::castAs(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getASTRecordLayout(), clang::ArrayType::getElementType(), clang::ASTRecordLayout::getFieldCount(), clang::FieldDecl::getFieldIndex(), clang::FieldDecl::getParent(), clang::ConstantArrayType::getSize(), clang::ValueDecl::getType(), getType(), and Parent.
Referenced by isUserWritingOffTheEnd().
isFormalAccess()
static bool isFormalAccess (AccessKinds AK) static
Is this an access per the C++ definition?
Definition at line 1473 of file ExprConstant.cpp.
References clang::AK_Construct, clang::AK_Destroy, and isAnyAccess().
Referenced by findCompleteObject(), and findSubobject().
IsGlobalLValue()
static bool IsGlobalLValue (APValue::LValueBase B) static
Definition at line 1960 of file ExprConstant.cpp.
References clang::cast(), clang::APValue::LValueBase::dyn_cast(), clang::APValue::LValueBase::get(), clang::Stmt::getStmtClass(), clang::APValue::LValueBase::is(), clang::isa(), clang::CompoundLiteralExpr::isFileScope(), clang::Expr::isLValue(), IsStringLiteralCall(), and clang::SD_Static.
Referenced by CheckLValueConstantExpression(), and clang::Expr::EvalResult::isGlobalLValue().
IsLiteralLValue()
static bool IsLiteralLValue (const LValue & Value) static
Definition at line 2026 of file ExprConstant.cpp.
References clang::isa().
Referenced by EvaluateComparisonBinaryOperator().
isModification()
static bool isModification (AccessKinds AK) static
Definition at line 1450 of file ExprConstant.cpp.
References clang::AK_Assign, clang::AK_Construct, clang::AK_Decrement, clang::AK_Destroy, clang::AK_DynamicCast, clang::AK_Increment, clang::AK_MemberCall, clang::AK_Read, clang::AK_ReadObjectRepresentation, and clang::AK_TypeId.
Referenced by findCompleteObject(), findSubobject(), and isAnyAccess().
isOneByteCharacterType()
static bool isOneByteCharacterType (QualType T) static
Definition at line 8944 of file ExprConstant.cpp.
isOnePastTheEndOfCompleteObject()
static bool isOnePastTheEndOfCompleteObject (const ASTContext & Ctx, const LValue & LV) static
Determine whether this is a pointer past the end of the complete object referred to by the lvalue.
Definition at line 12124 of file ExprConstant.cpp.
References getType(), clang::ASTContext::getTypeSizeInChars(), and clang::Type::isIncompleteType().
Referenced by EvaluateComparisonBinaryOperator().
isRead()
static bool isRead (AccessKinds AK) static
Definition at line 1446 of file ExprConstant.cpp.
References clang::AK_Read, and clang::AK_ReadObjectRepresentation.
Referenced by findSubobject(), isAnyAccess(), clang::PipeType::isReadOnly(), and clang::PipeType::Profile().
isReadByLvalueToRvalueConversion() [1/2]
static bool isReadByLvalueToRvalueConversion (const CXXRecordDecl * RD) static
Determine whether a type would actually be read by an lvalue-to-rvalue conversion.
If it's of class type, we may assume that the copy operation is trivial. Note that this is never true for a union type with fields (because the copy always "reads" the active member) and always true for a non-class type.
Definition at line 3442 of file ExprConstant.cpp.
References clang::CXXRecordDecl::bases(), clang::RecordDecl::field_empty(), clang::RecordDecl::fields(), clang::CXXRecordDecl::isEmpty(), isReadByLvalueToRvalueConversion(), and clang::TagDecl::isUnion().
Referenced by diagnoseMutableFields(), HandleConstructorCall(), HandleFunctionCall(), isReadByLvalueToRvalueConversion(), and isReadByLvalueToRvalueConversion().
isReadByLvalueToRvalueConversion() [2/2]
static bool isReadByLvalueToRvalueConversion (QualType T) static
Definition at line 3438 of file ExprConstant.cpp.
References isReadByLvalueToRvalueConversion().
IsStringLiteralCall()
static bool IsStringLiteralCall (const CallExpr * E) static
Should this call expression be treated as a string literal?
Definition at line 1954 of file ExprConstant.cpp.
References clang::CallExpr::getBuiltinCallee().
Referenced by IsGlobalLValue().
isUserWritingOffTheEnd()
static bool isUserWritingOffTheEnd (const ASTContext & Ctx, const LValue & LVal) static
Attempts to detect a user writing into a piece of memory that's impossible to figure out the size of by just using types.
Definition at line 11276 of file ExprConstant.cpp.
References isDesignatorAtObjectEnd().
Referenced by determineEndOffset().
isValidIndeterminateAccess()
static bool isValidIndeterminateAccess (AccessKinds AK) static
Is this kind of axcess valid on an indeterminate object value?
Definition at line 1478 of file ExprConstant.cpp.
References clang::AK_Assign, clang::AK_Construct, clang::AK_Decrement, clang::AK_Destroy, clang::AK_DynamicCast, clang::AK_Increment, clang::AK_MemberCall, clang::AK_Read, clang::AK_ReadObjectRepresentation, and clang::AK_TypeId.
Referenced by findSubobject().
IsWeakLValue()
static bool IsWeakLValue (const LValue & Value) static
Definition at line 2033 of file ExprConstant.cpp.
References GetLValueBaseDecl().
Referenced by EvaluateComparisonBinaryOperator().
isZeroSized()
static bool isZeroSized (const LValue & Value) static
Definition at line 2038 of file ExprConstant.cpp.
References clang::Decl::getASTContext(), GetLValueBaseDecl(), clang::ASTContext::getTypeSize(), clang::Type::isArrayType(), and clang::Type::isIncompleteType().
Referenced by EvaluateComparisonBinaryOperator().
lifetimeStartedInEvaluation()
static bool lifetimeStartedInEvaluation (EvalInfo & Info, APValue::LValueBase Base, bool MutableSubobject = false) static
Definition at line 3497 of file ExprConstant.cpp.
References getType().
Referenced by findCompleteObject().
MaybeElementDependentArrayFiller()
static bool MaybeElementDependentArrayFiller (const Expr * FillerExpr) static
Definition at line 10411 of file ExprConstant.cpp.
References MaybeElementDependentArrayFiller().
Referenced by MaybeElementDependentArrayFiller().
modifySubobject()
static bool modifySubobject (EvalInfo & Info, const Expr * E, const CompleteObject & Obj, const SubobjectDesignator & Sub, APValue & NewVal) static
Update the designated sub-object of an rvalue to the given value.
Definition at line 3871 of file ExprConstant.cpp.
References findSubobject().
Referenced by handleAssignment().
negateAsSigned()
static void negateAsSigned (APSInt & Int) static
Negate an APSInt in place, converting it to a signed form if necessary, and preserving its value (by extending by up to one bit as needed).
Definition at line 1838 of file ExprConstant.cpp.
NoDiag()
static ICEDiag NoDiag () static
Definition at line 15049 of file ExprConstant.cpp.
Referenced by CheckEvalInICE(), CheckICE(), and ParseDirective().
NoteLValueLocation()
static void NoteLValueLocation (EvalInfo & Info, APValue::LValueBase Base) static
Definition at line 2063 of file ExprConstant.cpp.
References clang::Expr::getExprLoc(), clang::ParmVarDecl::getFunctionScopeIndex(), and clang::Decl::getLocation().
Referenced by CheckDeleteKind(), CheckLValueConstantExpression(), evaluateVarDeclInit(), and findCompleteObject().
refersToCompleteObject()
static bool refersToCompleteObject (const LValue & LVal) static
Tests to see if the LValue has a user-specified designator (that isn't necessarily valid). Note that this always returns 'true' if the LValue has an unsized array as its first designator entry, because there's currently no way to tell if the user typed *foo or foo[0].
Definition at line 11258 of file ExprConstant.cpp.
References clang::APValue::LValueBase::dyn_cast(), and clang::isa().
Referenced by determineEndOffset().
truncateBitfieldValue()
static bool truncateBitfieldValue (EvalInfo & Info, const Expr * E, APValue & Value, const FieldDecl * FD) static
Definition at line 2630 of file ExprConstant.cpp.
References clang::FieldDecl::getBitWidthValue(), and clang::FieldDecl::isBitField().
Referenced by findSubobject(), and HandleConstructorCall().
TryEvaluateBuiltinNaN()
static bool TryEvaluateBuiltinNaN (const ASTContext & Context, QualType ResultTy, const Expr * Arg, bool SNaN, llvm::APFloat & Result) static
Definition at line 13581 of file ExprConstant.cpp.
References clang::ASTContext::getFloatTypeSemantics(), clang::ASTContext::getTargetInfo(), clang::Expr::IgnoreParenCasts(), and clang::TargetInfo::isNan2008().
tryEvaluateBuiltinObjectSize()
static bool tryEvaluateBuiltinObjectSize (const Expr * E, unsigned Type, EvalInfo & Info, uint64_t & Size) static
Tries to evaluate the __builtin_object_size for E. If successful, returns true and stores the result in Size.
If WasError is non-null, this will report whether the failure to evaluate is to be treated as an Error in IntExprEvaluator.
Definition at line 11394 of file ExprConstant.cpp.
References determineEndOffset(), EvaluateAsRValue(), EvaluatePointer(), clang::Expr::getExprLoc(), ignorePointerCastsAndParens(), and clang::Expr::isGLValue().
Referenced by clang::Expr::tryEvaluateObjectSize().
Worst()
static ICEDiag Worst (ICEDiag A, ICEDiag B) static
Definition at line 15051 of file ExprConstant.cpp.
Referenced by CheckICE().