clang: lib/Index/IndexingContext.cpp File Reference
IndexingContext.cpp File Reference
#include "IndexingContext.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Index/IndexDataConsumer.h"
Functions
static bool isGeneratedDecl (const Decl *D)
static void reportModuleReferences (const Module *Mod, ArrayRef< SourceLocation > IdLocs, const ImportDecl *ImportD, IndexDataConsumer &DataConsumer)
static const CXXRecordDecl * getDeclContextForTemplateInstationPattern (const Decl *D)
static const Decl * adjustTemplateImplicitInstantiation (const Decl *D)
static bool isDeclADefinition (const Decl *D, const DeclContext *ContainerDC, ASTContext &Ctx)
static bool shouldSkipNamelessDecl (const NamedDecl *ND)
Whether the given NamedDecl should be skipped because it has no name.
static const Decl * adjustParent (const Decl *Parent)
static const Decl * getCanonicalDecl (const Decl *D)
static bool shouldReportOccurrenceForSystemDeclOnlyMode (bool IsRef, SymbolRoleSet Roles, ArrayRef< SymbolRelation > Relations)
Function Documentation
adjustParent()
static const Decl * adjustParent (const Decl * Parent) static
Definition at line 279 of file IndexingContext.cpp.
References clang::cast(), Parent, and shouldSkipNamelessDecl().
adjustTemplateImplicitInstantiation()
static const Decl * adjustTemplateImplicitInstantiation (const Decl * D) static
Definition at line 210 of file IndexingContext.cpp.
References clang::cast(), getDeclContextForTemplateInstationPattern(), and clang::EnumDecl::getInstantiatedFromMemberEnum().
getCanonicalDecl()
static const Decl * getCanonicalDecl (const Decl * D) static
Definition at line 301 of file IndexingContext.cpp.
References clang::Decl::getCanonicalDecl(), and clang::Decl::isCanonicalDecl().
Referenced by areSortedAndUniqued(), checkReductionClauses(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), getPrivateItem(), clang::Sema::isOpenMPCapturedDecl(), clang::APValue::Profile(), clang::TemplateArgument::Profile(), and clang::Sema::setOpenMPCaptureKind().
getDeclContextForTemplateInstationPattern()
static const CXXRecordDecl * getDeclContextForTemplateInstationPattern (const Decl * D) static
Definition at line 201 of file IndexingContext.cpp.
References clang::Decl::getDeclContext(), clang::CXXRecordDecl::getInstantiatedFromMemberClass(), and clang::CXXRecordDecl::getTemplateInstantiationPattern().
Referenced by adjustTemplateImplicitInstantiation().
isDeclADefinition()
static bool isDeclADefinition (const Decl * D, const DeclContext * ContainerDC, ASTContext & Ctx) static
Definition at line 249 of file IndexingContext.cpp.
References clang::isa().
isGeneratedDecl()
static bool isGeneratedDecl (const Decl * D) static
Definition at line 21 of file IndexingContext.cpp.
References clang::Decl::getAttr().
Referenced by clang::index::IndexingContext::shouldIndex().
reportModuleReferences()
static void reportModuleReferences (const Module * Mod, ArrayRef< SourceLocation > IdLocs, const ImportDecl * ImportD, IndexDataConsumer & DataConsumer) static
Definition at line 94 of file IndexingContext.cpp.
References clang::index::IndexDataConsumer::handleModuleOccurrence(), clang::Module::Parent, clang::index::Reference, and reportModuleReferences().
Referenced by clang::index::IndexingContext::importedModule(), and reportModuleReferences().
shouldReportOccurrenceForSystemDeclOnlyMode()
static bool shouldReportOccurrenceForSystemDeclOnlyMode (bool IsRef, SymbolRoleSet Roles, ArrayRef< SymbolRelation > Relations) static
Definition at line 313 of file IndexingContext.cpp.
References clang::index::AddressOf, clang::index::applyForEachSymbolRoleInterruptible(), clang::index::Call, clang::index::Declaration, clang::index::Definition, clang::index::Dynamic, clang::index::Implicit, clang::index::NameReference, clang::index::Read, clang::index::Reference, clang::index::RelationAccessorOf, clang::index::RelationBaseOf, clang::index::RelationCalledBy, clang::index::RelationChildOf, clang::index::RelationContainedBy, clang::index::RelationExtendedBy, clang::index::RelationIBTypeOf, clang::index::RelationOverrideOf, clang::index::RelationReceivedBy, clang::index::RelationSpecializationOf, clang::index::Undefinition, and clang::index::Write.
shouldSkipNamelessDecl()
static bool shouldSkipNamelessDecl (const NamedDecl * ND) static
Whether the given NamedDecl should be skipped because it has no name.
Definition at line 274 of file IndexingContext.cpp.
References clang::NamedDecl::getDeclName(), clang::isa(), and clang::DeclarationName::isEmpty().
Referenced by adjustParent().