clang: lib/AST/ItaniumMangle.cpp File Reference
ItaniumMangle.cpp File Reference
#include "clang/AST/Mangle.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/ABI.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "clang/AST/TypeNodes.inc"
#include "clang/AST/BuiltinTypes.def"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/AST/StmtNodes.inc"
Macros
#define ABSTRACT_TYPE(CLASS, PARENT)
#define NON_CANONICAL_TYPE(CLASS, PARENT)
#define TYPE(CLASS, PARENT)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(CLASS, PARENT)
#define NON_CANONICAL_TYPE(CLASS, PARENT)
#define TYPE(CLASS, PARENT)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define BUILTIN_TYPE(Id, SingletonId)
#define PLACEHOLDER_TYPE(Id, SingletonId)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_VECTOR_TYPE(InternalName, MangledName, Id, SingletonId, NumEls, ElBits, IsSigned, IsFP, IsBF)
#define SVE_PREDICATE_TYPE(InternalName, MangledName, Id, SingletonId, NumEls)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define ABSTRACT_STMT(Type)
#define EXPR(Type, Base)
#define STMT(Type, Base)
#define STMT_RANGE(Base, First, Last)
#define LAST_STMT_RANGE(Base, First, Last)
#define ASMSTMT(Type, Base)
#define GCCASMSTMT(Type, Base)
#define MSASMSTMT(Type, Base)
#define BREAKSTMT(Type, Base)
#define CXXCATCHSTMT(Type, Base)
#define CXXFORRANGESTMT(Type, Base)
#define CXXTRYSTMT(Type, Base)
#define CAPTUREDSTMT(Type, Base)
#define COMPOUNDSTMT(Type, Base)
#define CONTINUESTMT(Type, Base)
#define CORETURNSTMT(Type, Base)
#define COROUTINEBODYSTMT(Type, Base)
#define DECLSTMT(Type, Base)
#define DOSTMT(Type, Base)
#define FORSTMT(Type, Base)
#define GOTOSTMT(Type, Base)
#define IFSTMT(Type, Base)
#define INDIRECTGOTOSTMT(Type, Base)
#define MSDEPENDENTEXISTSSTMT(Type, Base)
#define NULLSTMT(Type, Base)
#define OMPEXECUTABLEDIRECTIVE(Type, Base)
#define OMPATOMICDIRECTIVE(Type, Base)
#define OMPBARRIERDIRECTIVE(Type, Base)
#define OMPCANCELDIRECTIVE(Type, Base)
#define OMPCANCELLATIONPOINTDIRECTIVE(Type, Base)
#define OMPCRITICALDIRECTIVE(Type, Base)
#define OMPDEPOBJDIRECTIVE(Type, Base)
#define OMPFLUSHDIRECTIVE(Type, Base)
#define OMPLOOPDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPFORDIRECTIVE(Type, Base)
#define OMPFORSIMDDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELFORDIRECTIVE(Type, Base)
#define OMPPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPSIMDDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPTASKLOOPDIRECTIVE(Type, Base)
#define OMPTASKLOOPSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE(Type, Base)
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE(Type, Base)
#define OMPMASTERDIRECTIVE(Type, Base)
#define OMPORDEREDDIRECTIVE(Type, Base)
#define OMPPARALLELDIRECTIVE(Type, Base)
#define OMPPARALLELMASTERDIRECTIVE(Type, Base)
#define OMPPARALLELSECTIONSDIRECTIVE(Type, Base)
#define OMPSCANDIRECTIVE(Type, Base)
#define OMPSECTIONDIRECTIVE(Type, Base)
#define OMPSECTIONSDIRECTIVE(Type, Base)
#define OMPSINGLEDIRECTIVE(Type, Base)
#define OMPTARGETDATADIRECTIVE(Type, Base)
#define OMPTARGETDIRECTIVE(Type, Base)
#define OMPTARGETENTERDATADIRECTIVE(Type, Base)
#define OMPTARGETEXITDATADIRECTIVE(Type, Base)
#define OMPTARGETPARALLELDIRECTIVE(Type, Base)
#define OMPTARGETPARALLELFORDIRECTIVE(Type, Base)
#define OMPTARGETTEAMSDIRECTIVE(Type, Base)
#define OMPTARGETUPDATEDIRECTIVE(Type, Base)
#define OMPTASKDIRECTIVE(Type, Base)
#define OMPTASKGROUPDIRECTIVE(Type, Base)
#define OMPTASKWAITDIRECTIVE(Type, Base)
#define OMPTASKYIELDDIRECTIVE(Type, Base)
#define OMPTEAMSDIRECTIVE(Type, Base)
#define OBJCATCATCHSTMT(Type, Base)
#define OBJCATFINALLYSTMT(Type, Base)
#define OBJCATSYNCHRONIZEDSTMT(Type, Base)
#define OBJCATTHROWSTMT(Type, Base)
#define OBJCATTRYSTMT(Type, Base)
#define OBJCAUTORELEASEPOOLSTMT(Type, Base)
#define OBJCFORCOLLECTIONSTMT(Type, Base)
#define RETURNSTMT(Type, Base)
#define SEHEXCEPTSTMT(Type, Base)
#define SEHFINALLYSTMT(Type, Base)
#define SEHLEAVESTMT(Type, Base)
#define SEHTRYSTMT(Type, Base)
#define SWITCHCASE(Type, Base)
#define CASESTMT(Type, Base)
#define DEFAULTSTMT(Type, Base)
#define SWITCHSTMT(Type, Base)
#define VALUESTMT(Type, Base)
#define ATTRIBUTEDSTMT(Type, Base)
#define ABSTRACTCONDITIONALOPERATOR(Type, Base)
#define BINARYCONDITIONALOPERATOR(Type, Base)
#define CONDITIONALOPERATOR(Type, Base)
#define ADDRLABELEXPR(Type, Base)
#define ARRAYINITINDEXEXPR(Type, Base)
#define ARRAYINITLOOPEXPR(Type, Base)
#define ARRAYSUBSCRIPTEXPR(Type, Base)
#define ARRAYTYPETRAITEXPR(Type, Base)
#define ASTYPEEXPR(Type, Base)
#define ATOMICEXPR(Type, Base)
#define BINARYOPERATOR(Type, Base)
#define COMPOUNDASSIGNOPERATOR(Type, Base)
#define BLOCKEXPR(Type, Base)
#define CXXBINDTEMPORARYEXPR(Type, Base)
#define CXXBOOLLITERALEXPR(Type, Base)
#define CXXCONSTRUCTEXPR(Type, Base)
#define CXXTEMPORARYOBJECTEXPR(Type, Base)
#define CXXDEFAULTARGEXPR(Type, Base)
#define CXXDEFAULTINITEXPR(Type, Base)
#define CXXDELETEEXPR(Type, Base)
#define CXXDEPENDENTSCOPEMEMBEREXPR(Type, Base)
#define CXXFOLDEXPR(Type, Base)
#define CXXINHERITEDCTORINITEXPR(Type, Base)
#define CXXNEWEXPR(Type, Base)
#define CXXNOEXCEPTEXPR(Type, Base)
#define CXXNULLPTRLITERALEXPR(Type, Base)
#define CXXPSEUDODESTRUCTOREXPR(Type, Base)
#define CXXREWRITTENBINARYOPERATOR(Type, Base)
#define CXXSCALARVALUEINITEXPR(Type, Base)
#define CXXSTDINITIALIZERLISTEXPR(Type, Base)
#define CXXTHISEXPR(Type, Base)
#define CXXTHROWEXPR(Type, Base)
#define CXXTYPEIDEXPR(Type, Base)
#define CXXUNRESOLVEDCONSTRUCTEXPR(Type, Base)
#define CXXUUIDOFEXPR(Type, Base)
#define CALLEXPR(Type, Base)
#define CUDAKERNELCALLEXPR(Type, Base)
#define CXXMEMBERCALLEXPR(Type, Base)
#define CXXOPERATORCALLEXPR(Type, Base)
#define USERDEFINEDLITERAL(Type, Base)
#define CASTEXPR(Type, Base)
#define EXPLICITCASTEXPR(Type, Base)
#define BUILTINBITCASTEXPR(Type, Base)
#define CSTYLECASTEXPR(Type, Base)
#define CXXFUNCTIONALCASTEXPR(Type, Base)
#define CXXNAMEDCASTEXPR(Type, Base)
#define CXXADDRSPACECASTEXPR(Type, Base)
#define CXXCONSTCASTEXPR(Type, Base)
#define CXXDYNAMICCASTEXPR(Type, Base)
#define CXXREINTERPRETCASTEXPR(Type, Base)
#define CXXSTATICCASTEXPR(Type, Base)
#define OBJCBRIDGEDCASTEXPR(Type, Base)
#define IMPLICITCASTEXPR(Type, Base)
#define CHARACTERLITERAL(Type, Base)
#define CHOOSEEXPR(Type, Base)
#define COMPOUNDLITERALEXPR(Type, Base)
#define CONCEPTSPECIALIZATIONEXPR(Type, Base)
#define CONVERTVECTOREXPR(Type, Base)
#define COROUTINESUSPENDEXPR(Type, Base)
#define COAWAITEXPR(Type, Base)
#define COYIELDEXPR(Type, Base)
#define DECLREFEXPR(Type, Base)
#define DEPENDENTCOAWAITEXPR(Type, Base)
#define DEPENDENTSCOPEDECLREFEXPR(Type, Base)
#define DESIGNATEDINITEXPR(Type, Base)
#define DESIGNATEDINITUPDATEEXPR(Type, Base)
#define EXPRESSIONTRAITEXPR(Type, Base)
#define EXTVECTORELEMENTEXPR(Type, Base)
#define FIXEDPOINTLITERAL(Type, Base)
#define FLOATINGLITERAL(Type, Base)
#define FULLEXPR(Type, Base)
#define CONSTANTEXPR(Type, Base)
#define EXPRWITHCLEANUPS(Type, Base)
#define FUNCTIONPARMPACKEXPR(Type, Base)
#define GNUNULLEXPR(Type, Base)
#define GENERICSELECTIONEXPR(Type, Base)
#define IMAGINARYLITERAL(Type, Base)
#define IMPLICITVALUEINITEXPR(Type, Base)
#define INITLISTEXPR(Type, Base)
#define INTEGERLITERAL(Type, Base)
#define LAMBDAEXPR(Type, Base)
#define MSPROPERTYREFEXPR(Type, Base)
#define MSPROPERTYSUBSCRIPTEXPR(Type, Base)
#define MATERIALIZETEMPORARYEXPR(Type, Base)
#define MATRIXSUBSCRIPTEXPR(Type, Base)
#define MEMBEREXPR(Type, Base)
#define NOINITEXPR(Type, Base)
#define OMPARRAYSECTIONEXPR(Type, Base)
#define OMPARRAYSHAPINGEXPR(Type, Base)
#define OMPITERATOREXPR(Type, Base)
#define OBJCARRAYLITERAL(Type, Base)
#define OBJCAVAILABILITYCHECKEXPR(Type, Base)
#define OBJCBOOLLITERALEXPR(Type, Base)
#define OBJCBOXEDEXPR(Type, Base)
#define OBJCDICTIONARYLITERAL(Type, Base)
#define OBJCENCODEEXPR(Type, Base)
#define OBJCINDIRECTCOPYRESTOREEXPR(Type, Base)
#define OBJCISAEXPR(Type, Base)
#define OBJCIVARREFEXPR(Type, Base)
#define OBJCMESSAGEEXPR(Type, Base)
#define OBJCPROPERTYREFEXPR(Type, Base)
#define OBJCPROTOCOLEXPR(Type, Base)
#define OBJCSELECTOREXPR(Type, Base)
#define OBJCSTRINGLITERAL(Type, Base)
#define OBJCSUBSCRIPTREFEXPR(Type, Base)
#define OFFSETOFEXPR(Type, Base)
#define OPAQUEVALUEEXPR(Type, Base)
#define OVERLOADEXPR(Type, Base)
#define UNRESOLVEDLOOKUPEXPR(Type, Base)
#define UNRESOLVEDMEMBEREXPR(Type, Base)
#define PACKEXPANSIONEXPR(Type, Base)
#define PARENEXPR(Type, Base)
#define PARENLISTEXPR(Type, Base)
#define PREDEFINEDEXPR(Type, Base)
#define PSEUDOOBJECTEXPR(Type, Base)
#define RECOVERYEXPR(Type, Base)
#define REQUIRESEXPR(Type, Base)
#define SHUFFLEVECTOREXPR(Type, Base)
#define SIZEOFPACKEXPR(Type, Base)
#define SOURCELOCEXPR(Type, Base)
#define STMTEXPR(Type, Base)
#define STRINGLITERAL(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMEXPR(Type, Base)
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR(Type, Base)
#define TYPETRAITEXPR(Type, Base)
#define TYPOEXPR(Type, Base)
#define UNARYEXPRORTYPETRAITEXPR(Type, Base)
#define UNARYOPERATOR(Type, Base)
#define VAARGEXPR(Type, Base)
#define LABELSTMT(Type, Base)
#define WHILESTMT(Type, Base)
Functions
static const DeclContext * IgnoreLinkageSpecDecls (const DeclContext *DC)
static bool isStd (const NamespaceDecl *NS)
Return whether a given namespace is the 'std' namespace.
static bool isStdNamespace (const DeclContext *DC)
static const GlobalDecl isTemplate (GlobalDecl GD, const TemplateArgumentList *&TemplateArgs)
static TemplateName asTemplateName (GlobalDecl GD)
static GlobalDecl getParentOfLocalEntity (const DeclContext *DC)
static bool isTypeSubstitutable (Qualifiers Quals, const Type *Ty, ASTContext &Ctx)
static StringRef mangleAArch64VectorBase (const BuiltinType *EltType)
static bool isParenthesizedADLCallee (const CallExpr *call)
Look at the callee of the given call expression and determine if it's a parenthesized id-expression which would have triggered ADL otherwise.
static bool isZeroInitialized (QualType T, const APValue &V)
Determine whether a given value is equivalent to zero-initialization for the purpose of discarding a trailing portion of a 'tl' mangling.
static QualType getLValueType (ASTContext &Ctx, const APValue &LV)
static bool hasMangledSubstitutionQualifiers (QualType T)
Determine whether the given type has any qualifiers that are relevant for substitutions.
static bool isCharType (QualType T)
static bool isCharSpecialization (QualType T, const char *Name)
Returns whether a given type is a template specialization of a given name with a single argument of type char.
template<std::size_t StrLen>
static bool isStreamCharSpecialization (const ClassTemplateSpecializationDecl *SD, const char(&Str)[StrLen])
Macro Definition Documentation
ABSTRACT_STMT
#define ABSTRACT_STMT (Type)
ABSTRACT_TYPE [1/2]
#define ABSTRACT_TYPE (CLASS, PARENT)
Definition at line 521 of file ItaniumMangle.cpp.
ABSTRACT_TYPE [2/2]
#define ABSTRACT_TYPE (CLASS, PARENT)
Definition at line 521 of file ItaniumMangle.cpp.
ABSTRACTCONDITIONALOPERATOR
#define ABSTRACTCONDITIONALOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
ADDRLABELEXPR
#define ADDRLABELEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITINDEXEXPR
#define ARRAYINITINDEXEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYINITLOOPEXPR
#define ARRAYINITLOOPEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYSUBSCRIPTEXPR
#define ARRAYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
ARRAYTYPETRAITEXPR
#define ARRAYTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
ASMSTMT
#define ASMSTMT (Type, Base)
Value:
STMT(Type, Base)
ASTYPEEXPR
#define ASTYPEEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATOMICEXPR
#define ATOMICEXPR (Type, Base)
Value:
EXPR(Type, Base)
ATTRIBUTEDSTMT
#define ATTRIBUTEDSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
BINARYCONDITIONALOPERATOR
#define BINARYCONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
BINARYOPERATOR
#define BINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
BLOCKEXPR
#define BLOCKEXPR (Type, Base)
Value:
EXPR(Type, Base)
BREAKSTMT
#define BREAKSTMT (Type, Base)
Value:
STMT(Type, Base)
BUILTIN_TYPE
#define BUILTIN_TYPE (Id, SingletonId)
BUILTINBITCASTEXPR
#define BUILTINBITCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CALLEXPR
#define CALLEXPR (Type, Base)
Value:
EXPR(Type, Base)
CAPTUREDSTMT
#define CAPTUREDSTMT (Type, Base)
Value:
STMT(Type, Base)
CASESTMT
#define CASESTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
CASTEXPR
#define CASTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CHARACTERLITERAL
#define CHARACTERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
CHOOSEEXPR
#define CHOOSEEXPR (Type, Base)
Value:
EXPR(Type, Base)
COAWAITEXPR
#define COAWAITEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
COMPOUNDASSIGNOPERATOR
#define COMPOUNDASSIGNOPERATOR (Type, Base)
Value:
BINARYOPERATOR(Type, Base)
COMPOUNDLITERALEXPR
#define COMPOUNDLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
COMPOUNDSTMT
#define COMPOUNDSTMT (Type, Base)
Value:
STMT(Type, Base)
CONCEPTSPECIALIZATIONEXPR
#define CONCEPTSPECIALIZATIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
CONDITIONALOPERATOR
#define CONDITIONALOPERATOR (Type, Base)
Value:
ABSTRACTCONDITIONALOPERATOR(Type, Base)
CONSTANTEXPR
#define CONSTANTEXPR (Type, Base)
Value:
FULLEXPR(Type, Base)
CONTINUESTMT
#define CONTINUESTMT (Type, Base)
Value:
STMT(Type, Base)
CONVERTVECTOREXPR
#define CONVERTVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CORETURNSTMT
#define CORETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINEBODYSTMT
#define COROUTINEBODYSTMT (Type, Base)
Value:
STMT(Type, Base)
COROUTINESUSPENDEXPR
#define COROUTINESUSPENDEXPR (Type, Base)
Value:
EXPR(Type, Base)
COYIELDEXPR
#define COYIELDEXPR (Type, Base)
Value:
COROUTINESUSPENDEXPR(Type, Base)
CSTYLECASTEXPR
#define CSTYLECASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CUDAKERNELCALLEXPR
#define CUDAKERNELCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXADDRSPACECASTEXPR
#define CXXADDRSPACECASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXBINDTEMPORARYEXPR
#define CXXBINDTEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXBOOLLITERALEXPR
#define CXXBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXCATCHSTMT
#define CXXCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXCONSTCASTEXPR
#define CXXCONSTCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXCONSTRUCTEXPR
#define CXXCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTARGEXPR
#define CXXDEFAULTARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEFAULTINITEXPR
#define CXXDEFAULTINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDELETEEXPR
#define CXXDELETEEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDEPENDENTSCOPEMEMBEREXPR
#define CXXDEPENDENTSCOPEMEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXDYNAMICCASTEXPR
#define CXXDYNAMICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXFOLDEXPR
#define CXXFOLDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXFORRANGESTMT
#define CXXFORRANGESTMT (Type, Base)
Value:
STMT(Type, Base)
CXXFUNCTIONALCASTEXPR
#define CXXFUNCTIONALCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXINHERITEDCTORINITEXPR
#define CXXINHERITEDCTORINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXMEMBERCALLEXPR
#define CXXMEMBERCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXNAMEDCASTEXPR
#define CXXNAMEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
CXXNEWEXPR
#define CXXNEWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNOEXCEPTEXPR
#define CXXNOEXCEPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXNULLPTRLITERALEXPR
#define CXXNULLPTRLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXOPERATORCALLEXPR
#define CXXOPERATORCALLEXPR (Type, Base)
Value:
CALLEXPR(Type, Base)
CXXPSEUDODESTRUCTOREXPR
#define CXXPSEUDODESTRUCTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXREINTERPRETCASTEXPR
#define CXXREINTERPRETCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXREWRITTENBINARYOPERATOR
#define CXXREWRITTENBINARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
CXXSCALARVALUEINITEXPR
#define CXXSCALARVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXSTATICCASTEXPR
#define CXXSTATICCASTEXPR (Type, Base)
Value:
CXXNAMEDCASTEXPR(Type, Base)
CXXSTDINITIALIZERLISTEXPR
#define CXXSTDINITIALIZERLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTEMPORARYOBJECTEXPR
#define CXXTEMPORARYOBJECTEXPR (Type, Base)
Value:
CXXCONSTRUCTEXPR(Type, Base)
CXXTHISEXPR
#define CXXTHISEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTHROWEXPR
#define CXXTHROWEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXTRYSTMT
#define CXXTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
CXXTYPEIDEXPR
#define CXXTYPEIDEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUNRESOLVEDCONSTRUCTEXPR
#define CXXUNRESOLVEDCONSTRUCTEXPR (Type, Base)
Value:
EXPR(Type, Base)
CXXUUIDOFEXPR
#define CXXUUIDOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECLREFEXPR
#define DECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DECLSTMT
#define DECLSTMT (Type, Base)
Value:
STMT(Type, Base)
DEFAULTSTMT
#define DEFAULTSTMT (Type, Base)
Value:
SWITCHCASE(Type, Base)
DEPENDENT_TYPE [1/2]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
DEPENDENT_TYPE [2/2]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
DEPENDENTCOAWAITEXPR
#define DEPENDENTCOAWAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DEPENDENTSCOPEDECLREFEXPR
#define DEPENDENTSCOPEDECLREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITEXPR
#define DESIGNATEDINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
DESIGNATEDINITUPDATEEXPR
#define DESIGNATEDINITUPDATEEXPR (Type, Base)
Value:
EXPR(Type, Base)
DOSTMT
#define DOSTMT (Type, Base)
Value:
STMT(Type, Base)
EXPLICITCASTEXPR
#define EXPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
EXPR
#define EXPR (Type, Base)
EXPRESSIONTRAITEXPR
#define EXPRESSIONTRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
EXPRWITHCLEANUPS
#define EXPRWITHCLEANUPS (Type, Base)
Value:
FULLEXPR(Type, Base)
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id: \
    type_name = "ocl_" #ExtType; \
    Out << type_name.size() << type_name; \
    break;
EXTVECTORELEMENTEXPR
#define EXTVECTORELEMENTEXPR (Type, Base)
Value:
EXPR(Type, Base)
FIXEDPOINTLITERAL
#define FIXEDPOINTLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FLOATINGLITERAL
#define FLOATINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
FORSTMT
#define FORSTMT (Type, Base)
Value:
STMT(Type, Base)
FULLEXPR
#define FULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
FUNCTIONPARMPACKEXPR
#define FUNCTIONPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
GCCASMSTMT
#define GCCASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
GENERICSELECTIONEXPR
#define GENERICSELECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
GNUNULLEXPR
#define GNUNULLEXPR (Type, Base)
Value:
EXPR(Type, Base)
GOTOSTMT
#define GOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
IFSTMT
#define IFSTMT (Type, Base)
Value:
STMT(Type, Base)
IMAGE_TYPE
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id: \
    type_name = "ocl_" #ImgType "_" #Suffix; \
    Out << type_name.size() << type_name; \
    break;
IMAGINARYLITERAL
#define IMAGINARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
IMPLICITCASTEXPR
#define IMPLICITCASTEXPR (Type, Base)
Value:
CASTEXPR(Type, Base)
IMPLICITVALUEINITEXPR
#define IMPLICITVALUEINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
INDIRECTGOTOSTMT
#define INDIRECTGOTOSTMT (Type, Base)
Value:
STMT(Type, Base)
INITLISTEXPR
#define INITLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
INTEGERLITERAL
#define INTEGERLITERAL (Type, Base)
Value:
EXPR(Type, Base)
LABELSTMT
#define LABELSTMT (Type, Base)
Value:
VALUESTMT(Type, Base)
LAMBDAEXPR
#define LAMBDAEXPR (Type, Base)
Value:
EXPR(Type, Base)
LAST_STMT_RANGE
#define LAST_STMT_RANGE (Base, First, Last)
Value:
STMT_RANGE(Base, First, Last)
MATERIALIZETEMPORARYEXPR
#define MATERIALIZETEMPORARYEXPR (Type, Base)
Value:
EXPR(Type, Base)
MATRIXSUBSCRIPTEXPR
#define MATRIXSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
MEMBEREXPR
#define MEMBEREXPR (Type, Base)
Value:
EXPR(Type, Base)
MSASMSTMT
#define MSASMSTMT (Type, Base)
Value:
ASMSTMT(Type, Base)
MSDEPENDENTEXISTSSTMT
#define MSDEPENDENTEXISTSSTMT (Type, Base)
Value:
STMT(Type, Base)
MSPROPERTYREFEXPR
#define MSPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
MSPROPERTYSUBSCRIPTEXPR
#define MSPROPERTYSUBSCRIPTEXPR (Type, Base)
Value:
EXPR(Type, Base)
NOINITEXPR
#define NOINITEXPR (Type, Base)
Value:
EXPR(Type, Base)
NON_CANONICAL_TYPE [1/2]
#define NON_CANONICAL_TYPE (CLASS, PARENT)
Definition at line 522 of file ItaniumMangle.cpp.
NON_CANONICAL_TYPE [2/2]
#define NON_CANONICAL_TYPE (CLASS, PARENT)
Value:
    case Type::CLASS: \
      llvm_unreachable("can't mangle non-canonical type " #CLASS "Type"); \
      return;
Definition at line 522 of file ItaniumMangle.cpp.
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [1/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [2/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NULLSTMT
#define NULLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCARRAYLITERAL
#define OBJCARRAYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCATCATCHSTMT
#define OBJCATCATCHSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATFINALLYSTMT
#define OBJCATFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATSYNCHRONIZEDSTMT
#define OBJCATSYNCHRONIZEDSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTHROWSTMT
#define OBJCATTHROWSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCATTRYSTMT
#define OBJCATTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAUTORELEASEPOOLSTMT
#define OBJCAUTORELEASEPOOLSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCAVAILABILITYCHECKEXPR
#define OBJCAVAILABILITYCHECKEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOOLLITERALEXPR
#define OBJCBOOLLITERALEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBOXEDEXPR
#define OBJCBOXEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCBRIDGEDCASTEXPR
#define OBJCBRIDGEDCASTEXPR (Type, Base)
Value:
EXPLICITCASTEXPR(Type, Base)
OBJCDICTIONARYLITERAL
#define OBJCDICTIONARYLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCENCODEEXPR
#define OBJCENCODEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCFORCOLLECTIONSTMT
#define OBJCFORCOLLECTIONSTMT (Type, Base)
Value:
STMT(Type, Base)
OBJCINDIRECTCOPYRESTOREEXPR
#define OBJCINDIRECTCOPYRESTOREEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCISAEXPR
#define OBJCISAEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCIVARREFEXPR
#define OBJCIVARREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCMESSAGEEXPR
#define OBJCMESSAGEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROPERTYREFEXPR
#define OBJCPROPERTYREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCPROTOCOLEXPR
#define OBJCPROTOCOLEXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSELECTOREXPR
#define OBJCSELECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OBJCSTRINGLITERAL
#define OBJCSTRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
OBJCSUBSCRIPTREFEXPR
#define OBJCSUBSCRIPTREFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OFFSETOFEXPR
#define OFFSETOFEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSECTIONEXPR
#define OMPARRAYSECTIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPARRAYSHAPINGEXPR
#define OMPARRAYSHAPINGEXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPATOMICDIRECTIVE
#define OMPATOMICDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPBARRIERDIRECTIVE
#define OMPBARRIERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELDIRECTIVE
#define OMPCANCELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCANCELLATIONPOINTDIRECTIVE
#define OMPCANCELLATIONPOINTDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPCRITICALDIRECTIVE
#define OMPCRITICALDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDEPOBJDIRECTIVE
#define OMPDEPOBJDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPDISTRIBUTEDIRECTIVE
#define OMPDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPDISTRIBUTESIMDDIRECTIVE
#define OMPDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPEXECUTABLEDIRECTIVE
#define OMPEXECUTABLEDIRECTIVE (Type, Base)
Value:
STMT(Type, Base)
OMPFLUSHDIRECTIVE
#define OMPFLUSHDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPFORDIRECTIVE
#define OMPFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPFORSIMDDIRECTIVE
#define OMPFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPITERATOREXPR
#define OMPITERATOREXPR (Type, Base)
Value:
EXPR(Type, Base)
OMPLOOPDIRECTIVE
#define OMPLOOPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERDIRECTIVE
#define OMPMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPDIRECTIVE
#define OMPMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPMASTERTASKLOOPSIMDDIRECTIVE
#define OMPMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPORDEREDDIRECTIVE
#define OMPORDEREDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELDIRECTIVE
#define OMPPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELFORDIRECTIVE
#define OMPPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELFORSIMDDIRECTIVE
#define OMPPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERDIRECTIVE
#define OMPPARALLELMASTERDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPDIRECTIVE
#define OMPPARALLELMASTERTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE
#define OMPPARALLELMASTERTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPPARALLELSECTIONSDIRECTIVE
#define OMPPARALLELSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSCANDIRECTIVE
#define OMPSCANDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONDIRECTIVE
#define OMPSECTIONDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSECTIONSDIRECTIVE
#define OMPSECTIONSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPSIMDDIRECTIVE
#define OMPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPSINGLEDIRECTIVE
#define OMPSINGLEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDATADIRECTIVE
#define OMPTARGETDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETDIRECTIVE
#define OMPTARGETDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETENTERDATADIRECTIVE
#define OMPTARGETENTERDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETEXITDATADIRECTIVE
#define OMPTARGETEXITDATADIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELDIRECTIVE
#define OMPTARGETPARALLELDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORDIRECTIVE
#define OMPTARGETPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETPARALLELFORSIMDDIRECTIVE
#define OMPTARGETPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETSIMDDIRECTIVE
#define OMPTARGETSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDIRECTIVE
#define OMPTARGETTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE
#define OMPTARGETTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTARGETUPDATEDIRECTIVE
#define OMPTARGETUPDATEDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKDIRECTIVE
#define OMPTASKDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKGROUPDIRECTIVE
#define OMPTASKGROUPDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKLOOPDIRECTIVE
#define OMPTASKLOOPDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKLOOPSIMDDIRECTIVE
#define OMPTASKLOOPSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTASKWAITDIRECTIVE
#define OMPTASKWAITDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTASKYIELDDIRECTIVE
#define OMPTASKYIELDDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDIRECTIVE
#define OMPTEAMSDIRECTIVE (Type, Base)
Value:
OMPEXECUTABLEDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEDIRECTIVE
#define OMPTEAMSDISTRIBUTEDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE
#define OMPTEAMSDISTRIBUTEPARALLELFORDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE
#define OMPTEAMSDISTRIBUTEPARALLELFORSIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OMPTEAMSDISTRIBUTESIMDDIRECTIVE
#define OMPTEAMSDISTRIBUTESIMDDIRECTIVE (Type, Base)
Value:
OMPLOOPDIRECTIVE(Type, Base)
OPAQUEVALUEEXPR
#define OPAQUEVALUEEXPR (Type, Base)
Value:
EXPR(Type, Base)
OVERLOADEXPR
#define OVERLOADEXPR (Type, Base)
Value:
EXPR(Type, Base)
PACKEXPANSIONEXPR
#define PACKEXPANSIONEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENEXPR
#define PARENEXPR (Type, Base)
Value:
EXPR(Type, Base)
PARENLISTEXPR
#define PARENLISTEXPR (Type, Base)
Value:
EXPR(Type, Base)
PLACEHOLDER_TYPE
#define PLACEHOLDER_TYPE (Id, SingletonId)
Value:
  case BuiltinType::Id:
PPC_VECTOR_TYPE
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
  case BuiltinType::Id: \
    type_name = #Name; \
    Out << 'u' << type_name.size() << type_name; \
    break;
PREDEFINEDEXPR
#define PREDEFINEDEXPR (Type, Base)
Value:
EXPR(Type, Base)
PSEUDOOBJECTEXPR
#define PSEUDOOBJECTEXPR (Type, Base)
Value:
EXPR(Type, Base)
RECOVERYEXPR
#define RECOVERYEXPR (Type, Base)
Value:
EXPR(Type, Base)
REQUIRESEXPR
#define REQUIRESEXPR (Type, Base)
Value:
EXPR(Type, Base)
RETURNSTMT
#define RETURNSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHEXCEPTSTMT
#define SEHEXCEPTSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHFINALLYSTMT
#define SEHFINALLYSTMT (Type, Base)
Value:
STMT(Type, Base)
SEHLEAVESTMT
#define SEHLEAVESTMT (Type, Base)
Value:
STMT(Type, Base)
SEHTRYSTMT
#define SEHTRYSTMT (Type, Base)
Value:
STMT(Type, Base)
SHUFFLEVECTOREXPR
#define SHUFFLEVECTOREXPR (Type, Base)
Value:
EXPR(Type, Base)
SIZEOFPACKEXPR
#define SIZEOFPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SOURCELOCEXPR
#define SOURCELOCEXPR (Type, Base)
Value:
EXPR(Type, Base)
STMT
#define STMT (Type, Base)
Value:
  case Expr::Type##Class:
STMT_RANGE
#define STMT_RANGE (Base, First, Last)
STMTEXPR
#define STMTEXPR (Type, Base)
Value:
EXPR(Type, Base)
STRINGLITERAL
#define STRINGLITERAL (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMEXPR
#define SUBSTNONTYPETEMPLATEPARMEXPR (Type, Base)
Value:
EXPR(Type, Base)
SUBSTNONTYPETEMPLATEPARMPACKEXPR
#define SUBSTNONTYPETEMPLATEPARMPACKEXPR (Type, Base)
Value:
EXPR(Type, Base)
SVE_PREDICATE_TYPE
#define SVE_PREDICATE_TYPE (InternalName, MangledName, Id, SingletonId, NumEls)
Value:
  case BuiltinType::Id:                                                        \
    type_name = MangledName;                                                   \
    Out << (type_name == InternalName ? "u" : "") << type_name.size()          \
        << type_name;                                                          \
    break;
SVE_VECTOR_TYPE
#define SVE_VECTOR_TYPE (InternalName, MangledName, Id, SingletonId, NumEls, ElBits, IsSigned, IsFP, IsBF)
Value:
  case BuiltinType::Id:                                                        \
    type_name = MangledName;                                                   \
    Out << (type_name == InternalName ? "u" : "") << type_name.size()          \
        << type_name;                                                          \
    break;
SWITCHCASE
#define SWITCHCASE (Type, Base)
Value:
STMT(Type, Base)
SWITCHSTMT
#define SWITCHSTMT (Type, Base)
Value:
STMT(Type, Base)
TYPE [1/2]
#define TYPE (CLASS, PARENT)
Value:
void mangleType(const CLASS##Type *T);
Definition at line 523 of file ItaniumMangle.cpp.
TYPE [2/2]
#define TYPE (CLASS, PARENT)
Value:
    case Type::CLASS: \
      mangleType(static_cast<const CLASS##Type*>(ty)); \
      break;
Definition at line 523 of file ItaniumMangle.cpp.
TYPETRAITEXPR
#define TYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
TYPOEXPR
#define TYPOEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYEXPRORTYPETRAITEXPR
#define UNARYEXPRORTYPETRAITEXPR (Type, Base)
Value:
EXPR(Type, Base)
UNARYOPERATOR
#define UNARYOPERATOR (Type, Base)
Value:
EXPR(Type, Base)
UNRESOLVEDLOOKUPEXPR
#define UNRESOLVEDLOOKUPEXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
UNRESOLVEDMEMBEREXPR
#define UNRESOLVEDMEMBEREXPR (Type, Base)
Value:
OVERLOADEXPR(Type, Base)
USERDEFINEDLITERAL
#define USERDEFINEDLITERAL (Type, Base)
Value:
CALLEXPR(Type, Base)
VAARGEXPR
#define VAARGEXPR (Type, Base)
Value:
EXPR(Type, Base)
VALUESTMT
#define VALUESTMT (Type, Base)
Value:
STMT(Type, Base)
WHILESTMT
#define WHILESTMT (Type, Base)
Value:
STMT(Type, Base)
Function Documentation
asTemplateName()
static TemplateName asTemplateName (GlobalDecl GD) static
Definition at line 843 of file ItaniumMangle.cpp.
References clang::GlobalDecl::getDecl().
getLValueType()
static QualType getLValueType (ASTContext & Ctx, const APValue & LV) static
Definition at line 5289 of file ItaniumMangle.cpp.
References clang::ASTContext::getAsArrayType(), clang::APValue::getLValueBase(), clang::APValue::getLValuePath(), clang::ASTContext::getRecordType(), clang::APValue::LValueBase::getType(), and clang::ValueDecl::getType().
getParentOfLocalEntity()
static GlobalDecl getParentOfLocalEntity (const DeclContext * DC) static
Definition at line 1617 of file ItaniumMangle.cpp.
References clang::Ctor_Complete, and clang::Dtor_Complete.
hasMangledSubstitutionQualifiers()
static bool hasMangledSubstitutionQualifiers (QualType T) static
Determine whether the given type has any qualifiers that are relevant for substitutions.
Definition at line 5720 of file ItaniumMangle.cpp.
References clang::Qualifiers::getCVRQualifiers(), clang::Qualifiers::hasAddressSpace(), and clang::Qualifiers::hasUnaligned().
IgnoreLinkageSpecDecls()
static const DeclContext * IgnoreLinkageSpecDecls (const DeclContext * DC) static
Definition at line 788 of file ItaniumMangle.cpp.
Referenced by isStd().
isCharSpecialization()
static bool isCharSpecialization (QualType T, const char * Name) static
Returns whether a given type is a template specialization of a given name with a single argument of type char.
Definition at line 5767 of file ItaniumMangle.cpp.
References clang::Type::getAs(), clang::RecordType::getDecl(), clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::ClassTemplateSpecializationDecl::getTemplateArgs(), isCharType(), isStdNamespace(), and clang::TemplateArgumentList::size().
Referenced by isStreamCharSpecialization().
isCharType()
static bool isCharType (QualType T) static
Definition at line 5757 of file ItaniumMangle.cpp.
Referenced by isCharSpecialization(), and isStreamCharSpecialization().
isParenthesizedADLCallee()
static bool isParenthesizedADLCallee (const CallExpr * call) static
Look at the callee of the given call expression and determine if it's a parenthesized id-expression which would have triggered ADL otherwise.
Definition at line 3855 of file ItaniumMangle.cpp.
References clang::OverloadExpr::decls_begin(), clang::CallExpr::getCallee(), clang::OverloadExpr::getNumDecls(), clang::OverloadExpr::getQualifier(), clang::Expr::IgnoreParens(), and clang::UnresolvedLookupExpr::requiresADL().
isStd()
static bool isStd (const NamespaceDecl * NS) static
Return whether a given namespace is the 'std' namespace.
Definition at line 797 of file ItaniumMangle.cpp.
References clang::NamedDecl::getIdentifier(), clang::NamespaceDecl::getOriginalNamespace(), IgnoreLinkageSpecDecls(), and clang::IdentifierInfo::isStr().
Referenced by isStdNamespace().
isStdNamespace()
static bool isStdNamespace (const DeclContext * DC) static
Definition at line 808 of file ItaniumMangle.cpp.
References clang::DeclContext::isNamespace(), and isStd().
Referenced by isCharSpecialization().
isStreamCharSpecialization()
template<std::size_t StrLen> static bool isStreamCharSpecialization (const ClassTemplateSpecializationDecl * SD, const char(&) Str[StrLen]) static
Definition at line 5794 of file ItaniumMangle.cpp.
References clang::NamedDecl::getIdentifier(), clang::ClassTemplateSpecializationDecl::getTemplateArgs(), isCharSpecialization(), isCharType(), clang::IdentifierInfo::isStr(), and clang::TemplateArgumentList::size().
isTemplate()
static const GlobalDecl isTemplate (GlobalDecl GD, const TemplateArgumentList *& TemplateArgs) static
Definition at line 816 of file ItaniumMangle.cpp.
References clang::cast(), clang::GlobalDecl::getDecl(), clang::FunctionDecl::getPrimaryTemplate(), clang::FunctionDecl::getTemplateSpecializationArgs(), and clang::GlobalDecl::getWithDecl().
Referenced by clang::Sema::isAcceptableTagRedeclaration().
isTypeSubstitutable()
static bool isTypeSubstitutable (Qualifiers Quals, const Type * Ty, ASTContext & Ctx) static
Definition at line 2535 of file ItaniumMangle.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::Type::isBuiltinType(), clang::Type::isOpenCLSpecificType(), and clang::Type::isSpecificBuiltinType().
isZeroInitialized()
static bool isZeroInitialized (QualType T, const APValue & V) static
Determine whether a given value is equivalent to zero-initialization for the purpose of discarding a trailing portion of a 'tl' mangling.
Note that this is not in general equivalent to determining whether the value has an all-zeroes bit pattern.
Definition at line 5204 of file ItaniumMangle.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::CXXRecordDecl::bases(), clang::Type::castAs(), clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::declaresSameEntity(), clang::RecordDecl::fields(), clang::APValue::FixedPoint, clang::APValue::Float, clang::VectorType::getElementType(), clang::ValueDecl::getType(), clang::APValue::Indeterminate, clang::APValue::Int, isZeroInitialized(), clang::APValue::LValue, clang::APValue::MemberPointer, N, clang::APValue::None, clang::APValue::Struct, clang::APValue::Union, V, and clang::APValue::Vector.
Referenced by isZeroInitialized().
mangleAArch64VectorBase()
static StringRef mangleAArch64VectorBase (const BuiltinType * EltType) static
Definition at line 3280 of file ItaniumMangle.cpp.
References clang::BuiltinType::getKind().