clang: lib/Driver/ToolChains/MSVC.cpp File Reference
MSVC.cpp File Reference
#include "MSVC.h"
#include "CommonArgs.h"
#include "Darwin.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Version.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include <cstdio>
Functions
static bool getSystemRegistryString (const char *keyPath, const char *valueName, std::string &value, std::string *phValue)
Read registry string.
static bool findVCToolChainViaCommandLine (const ArgList &Args, std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaEnvironment (std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaSetupConfig (std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaRegistry (std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static std::string FindVisualStudioExecutable (const ToolChain &TC, const char *Exe)
static const char * llvmArchToWindowsSDKArch (llvm::Triple::ArchType Arch)
static const char * llvmArchToLegacyVCArch (llvm::Triple::ArchType Arch)
static const char * llvmArchToDevDivInternalArch (llvm::Triple::ArchType Arch)
static bool getWindows10SDKVersionFromPath (const std::string &SDKPath, std::string &SDKVersion)
static bool getWindowsSDKDir (std::string &Path, int &Major, std::string &WindowsSDKIncludeVersion, std::string &WindowsSDKLibVersion)
Get Windows SDK installation directory.
static bool getUniversalCRTSdkDir (std::string &Path, std::string &UCRTVersion)
static VersionTuple getMSVCVersionFromTriple (const llvm::Triple &Triple)
static VersionTuple getMSVCVersionFromExe (const std::string &BinDir)
static void TranslateOptArg (Arg *A, llvm::opt::DerivedArgList &DAL, bool SupportsForcingFramePointer, const char *ExpandChar, const OptTable &Opts)
static void TranslateDArg (Arg *A, llvm::opt::DerivedArgList &DAL, const OptTable &Opts)
Function Documentation
findVCToolChainViaCommandLine()
static bool findVCToolChainViaCommandLine (const ArgList & Args, std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 72 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaEnvironment()
static bool findVCToolChainViaEnvironment (std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 85 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaRegistry()
static bool findVCToolChainViaRegistry (std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 288 of file MSVC.cpp.
References getSystemRegistryString().
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaSetupConfig()
static bool findVCToolChainViaSetupConfig (std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 197 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
FindVisualStudioExecutable()
static std::string FindVisualStudioExecutable (const ToolChain & TC, const char * Exe) static
Definition at line 312 of file MSVC.cpp.
Referenced by clang::driver::tools::visualstudio::Linker::ConstructJob(), and clang::driver::tools::visualstudio::Compiler::GetCommand().
getMSVCVersionFromExe()
static VersionTuple getMSVCVersionFromExe (const std::string & BinDir) static
Definition at line 1223 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::computeMSVCVersion().
getMSVCVersionFromTriple()
static VersionTuple getMSVCVersionFromTriple (const llvm::Triple & Triple) static
Definition at line 1215 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::computeMSVCVersion().
getSystemRegistryString()
static bool getSystemRegistryString (const char * keyPath, const char * valueName, std::string & value, std::string * phValue) static
Read registry string.
This also supports a means to look for high-versioned keys by use of a $VERSION placeholder in the key path. $VERSION in the key path is a placeholder for the version number, causing the highest value path to be searched for and used. I.e. "SOFTWARE\\Microsoft\\VisualStudio\\$VERSION". There can be additional characters in the component. Only the numeric characters are compared. This function only searches HKLM.
Definition at line 980 of file MSVC.cpp.
References clang::isDigit(), and NULL.
Referenced by findVCToolChainViaRegistry(), getUniversalCRTSdkDir(), and getWindowsSDKDir().
getUniversalCRTSdkDir()
static bool getUniversalCRTSdkDir (std::string & Path, std::string & UCRTVersion) static
Definition at line 1185 of file MSVC.cpp.
References getSystemRegistryString(), and getWindows10SDKVersionFromPath().
Referenced by clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath().
getWindows10SDKVersionFromPath()
static bool getWindows10SDKVersionFromPath (const std::string & SDKPath, std::string & SDKVersion) static
Definition at line 1071 of file MSVC.cpp.
Referenced by getUniversalCRTSdkDir(), and getWindowsSDKDir().
getWindowsSDKDir()
static bool getWindowsSDKDir (std::string & Path, int & Major, std::string & WindowsSDKIncludeVersion, std::string & WindowsSDKLibVersion) static
Get Windows SDK installation directory.
Definition at line 1096 of file MSVC.cpp.
References getSystemRegistryString(), and getWindows10SDKVersionFromPath().
Referenced by clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath().
llvmArchToDevDivInternalArch()
static const char * llvmArchToDevDivInternalArch (llvm::Triple::ArchType Arch) static
Definition at line 872 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath().
llvmArchToLegacyVCArch()
static const char * llvmArchToLegacyVCArch (llvm::Triple::ArchType Arch) static
Definition at line 853 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath().
llvmArchToWindowsSDKArch()
static const char * llvmArchToWindowsSDKArch (llvm::Triple::ArchType Arch) static
Definition at line 836 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath(), clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath(), and clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath().
TranslateDArg()
static void TranslateDArg (Arg * A, llvm::opt::DerivedArgList & DAL, const OptTable & Opts) static
Definition at line 1510 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().
TranslateOptArg()
static void TranslateOptArg (Arg * A, llvm::opt::DerivedArgList & DAL, bool SupportsForcingFramePointer, const char * ExpandChar, const OptTable & Opts) static
Definition at line 1414 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().