clang: clang::format Namespace Reference
clang::format Namespace Reference
Namespaces
namespace encoding
namespace internal
Classes
class AffectedRangeManager
class AnnotatedLine
class BreakableBlockComment
class BreakableComment
class BreakableLineCommentSection
class BreakableStringLiteral
class BreakableToken
Base class for tokens / ranges of tokens that can allow breaking within the tokens - for example, to avoid whitespace beyond the column limit, or to reflow text.
class CompoundStatementIndenter
class ContinuationIndenter
class Environment
struct FormatToken
A wrapper around a Token storing information about the whitespace characters preceding it.
class FormatTokenLexer
class FormatTokenSource
class JavaScriptImportSorter
struct JsImportedSymbol
struct JsModuleReference
struct LineState
The current state when indenting a unwrapped line.
class MacroExpander
Takes a set of macro definitions as strings and allows expanding calls to those macros.
struct MacroExpansion
Contains information on the token's role in a macro expansion.
class NamespaceEndCommentsFixer
struct ParenState
class ParseErrorCategory
struct RawStringFormatStyleManager
class ScopedLineState
class TokenAnalyzer
class TokenAnnotator
Determines extra information about the tokens comprising an UnwrappedLine.
struct UnwrappedLine
An unwrapped line is a sequence of Token, that we would like to put on a single line if there was no column limit.
class UnwrappedLineConsumer
class UnwrappedLineFormatter
struct UnwrappedLineNode
class UnwrappedLineParser
class UsingDeclarationsSorter
class WhitespaceManager
Manages the whitespaces around tokens and their replacements.
Enumerations
enum class ParseError { Success = 0 , Error , Unsuitable , BinPackTrailingCommaConflict }
enum TokenType : uint8_t { NUM_TOKEN_TYPES }
Determines the semantic type of a syntactic token, e.g.
enum BraceBlockKind { BK_Unknown , BK_Block , BK_BracedInit }
enum ParameterPackingKind { PPK_BinPacked , PPK_OnePerLine , PPK_Inconclusive }
enum FormatDecision { FD_Unformatted , FD_Continue , FD_Break }
enum MacroRole { MR_ExpandedArg , MR_UnexpandedArg , MR_Hidden }
Roles a token can take in a configured macro expansion.
enum LexerState { NORMAL , TEMPLATE_STRING , TOKEN_STASHED }
enum LineType {
LT_Invalid , LT_ImportStatement , LT_ObjCDecl , LT_ObjCMethodDecl ,
LT_ObjCProperty , LT_Other , LT_PreprocessorDirective , LT_VirtualFunctionDecl
}
Functions
const std::error_category & getParseCategory ()
std::error_code make_error_code (ParseError e)
StringRef getLanguageName (FormatStyle::LanguageKind Language)
The FormatStyle is used to configure the formatting to follow / specific guidelines.
static bool IsBlank (char C)
static StringRef getLineCommentIndentPrefix (StringRef Comment, const FormatStyle &Style)
static BreakableToken::Split getCommentSplit (StringRef Text, unsigned ContentStartColumn, unsigned ColumnLimit, unsigned TabWidth, encoding::Encoding Encoding, const FormatStyle &Style, bool DecorationEndsWithStar=false)
static BreakableToken::Split getStringSplit (StringRef Text, unsigned UsedColumns, unsigned ColumnLimit, unsigned TabWidth, encoding::Encoding Encoding)
bool switchesFormatting (const FormatToken &Token)
Checks if Token switches formatting, like /* clang-format off *‍/.
static bool mayReflowContent (StringRef Content)
static bool shouldIndentWrappedSelectorName (const FormatStyle &Style, LineType LineType)
static unsigned getLengthToMatchingParen (const FormatToken &Tok, const std::vector< ParenState > &Stack)
static unsigned getLengthToNextOperator (const FormatToken &Tok)
static bool startsSegmentOfBuilderTypeCall (const FormatToken &Tok)
static bool startsNextParameter (const FormatToken &Current, const FormatStyle &Style)
static bool opensProtoMessageField (const FormatToken &LessTok, const FormatStyle &Style)
static llvm::Optional< StringRef > getRawStringDelimiter (StringRef TokenText)
static StringRef getCanonicalRawStringDelimiter (const FormatStyle &Style, FormatStyle::LanguageKind Language)
static bool hasNestedBlockInlined (const FormatToken *Previous, const FormatToken &Current, const FormatStyle &Style)
static unsigned getLastLineEndColumn (StringRef Text, unsigned StartColumn, unsigned TabWidth, encoding::Encoding Encoding)
static StringRef getEnclosingFunctionName (const FormatToken &Current)
llvm::Error make_string_error (const llvm::Twine &Message)
static FormatStyle expandPresets (const FormatStyle &Style)
FormatStyle getLLVMStyle (FormatStyle::LanguageKind Language)
FormatStyle getGoogleStyle (FormatStyle::LanguageKind Language)
FormatStyle getChromiumStyle (FormatStyle::LanguageKind Language)
FormatStyle getMozillaStyle ()
FormatStyle getWebKitStyle ()
FormatStyle getGNUStyle ()
FormatStyle getMicrosoftStyle (FormatStyle::LanguageKind Language)
FormatStyle getNoStyle ()
bool getPredefinedStyle (StringRef Name, FormatStyle::LanguageKind Language, FormatStyle *Style)
std::error_code parseConfiguration (llvm::MemoryBufferRef Config, FormatStyle *Style, bool AllowUnknownOptions)
std::string configurationAsText (const FormatStyle &Style)
static bool affectsRange (ArrayRef< tooling::Range > Ranges, unsigned Start, unsigned End)
static std::pair< unsigned, unsigned > FindCursorIndex (const SmallVectorImpl< IncludeDirective > &Includes, const SmallVectorImpl< unsigned > &Indices, unsigned Cursor)
std::string replaceCRLF (const std::string &Code)
static void sortCppIncludes (const FormatStyle &Style, const SmallVectorImpl< IncludeDirective > &Includes, ArrayRef< tooling::Range > Ranges, StringRef FileName, StringRef Code, tooling::Replacements &Replaces, unsigned *Cursor)
tooling::Replacements sortCppIncludes (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, tooling::Replacements &Replaces, unsigned *Cursor)
static unsigned findJavaImportGroup (const FormatStyle &Style, StringRef ImportIdentifier)
static void sortJavaImports (const FormatStyle &Style, const SmallVectorImpl< JavaImportDirective > &Imports, ArrayRef< tooling::Range > Ranges, StringRef FileName, StringRef Code, tooling::Replacements &Replaces)
tooling::Replacements sortJavaImports (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, tooling::Replacements &Replaces)
bool isMpegTS (StringRef Code)
bool isLikelyXml (StringRef Code)
tooling::Replacements sortIncludes (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, unsigned *Cursor)
template<typename T >
static llvm::Expected< tooling::Replacements > processReplacements (T ProcessFunc, StringRef Code, const tooling::Replacements &Replaces, const FormatStyle &Style)
llvm::Expected< tooling::Replacements > formatReplacements (StringRef Code, const tooling::Replacements &Replaces, const FormatStyle &Style)
llvm::Expected< tooling::Replacements > cleanupAroundReplacements (StringRef Code, const tooling::Replacements &Replaces, const FormatStyle &Style)
tooling::Replacements reformat (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, FormattingAttemptStatus *Status)
tooling::Replacements cleanup (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
tooling::Replacements reformat (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, bool *IncompleteFormat)
tooling::Replacements fixNamespaceEndComments (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
tooling::Replacements sortUsingDeclarations (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
LangOptions getFormattingLangOpts (const FormatStyle &Style)
static FormatStyle::LanguageKind getLanguageByFileName (StringRef FileName)
FormatStyle::LanguageKind guessLanguage (StringRef FileName, StringRef Code)
llvm::Expected< FormatStyle > getStyle (StringRef StyleName, StringRef FileName, StringRef FallbackStyleName, StringRef Code, llvm::vfs::FileSystem *FS, bool AllowUnknownOptions)
const char * getTokenTypeName (TokenType Type)
Determines the name of a token type.
static unsigned CodePointsBetween (const FormatToken *Begin, const FormatToken *End)
struct clang::format::FormatToken getPreviousNonComment () const
Returns the previous token ignoring comments.
const FormatToken * getNextNonComment () const
Returns the next token ignoring comments.
bool opensBlockOrBlockTypeList (const FormatStyle &Style) const
Returns true if this tokens starts a block-type list, i.e. a list that should be indented with a block indent.
bool isCppStructuredBinding (const FormatStyle &Style) const
Returns whether the token is the left square bracket of a C++ structured binding declaration.
bool closesBlockOrBlockTypeList (const FormatStyle &Style) const
Same as opensBlockOrBlockTypeList, but for the closing token.
const FormatToken * getNamespaceToken () const
Return the actual namespace token, if this token starts a namespace block.
void copyFrom (const FormatToken &Tok)
const FormatToken * getNamespaceToken (const AnnotatedLine *Line, const SmallVectorImpl< AnnotatedLine * > &AnnotatedLines)
StringRef getNamespaceTokenText (const AnnotatedLine *Line, const SmallVectorImpl< AnnotatedLine * > &AnnotatedLines)
bool operator< (const JsModuleReference &LHS, const JsModuleReference &RHS)
tooling::Replacements sortJavaScriptImports (const FormatStyle &Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
static unsigned maxNestingDepth (const AnnotatedLine &Line)
static bool isFunctionDeclarationName (const FormatToken &Current, const AnnotatedLine &Line)
static bool isAllmanBrace (const FormatToken &Tok)
static bool IsFunctionArgument (const FormatToken &Tok)
static bool isItAnEmptyLambdaAllowed (const FormatToken &Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption)
static bool isItAInlineLambdaAllowed (const FormatToken &Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption)
static bool isOneChildWithoutMustBreakBefore (const FormatToken &Tok)
static bool isAllmanLambdaBrace (const FormatToken &Tok)
static bool isAllmanBraceIncludedBreakableLambda (const FormatToken &Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption)
template<class T >
static void hash_combine (std::size_t &seed, const T &v)
static bool isGoogScope (const UnwrappedLine &Line)
static bool isIIFE (const UnwrappedLine &Line, const AdditionalKeywords &Keywords)
static bool ShouldBreakBeforeBrace (const FormatStyle &Style, const FormatToken &InitialToken)
static bool tokenCanStartNewLine (const FormatToken &Tok)
static bool mustBeJSIdent (const AdditionalKeywords &Keywords, const FormatToken *FormatTok)
static bool mustBeJSIdentOrValue (const AdditionalKeywords &Keywords, const FormatToken *FormatTok)
static bool isJSDeclOrStmt (const AdditionalKeywords &Keywords, const FormatToken *FormatTok)
static LLVM_ATTRIBUTE_UNUSED void printDebugInfo (const UnwrappedLine &Line, StringRef Prefix="")
static bool continuesLineCommentSection (const FormatToken &FormatTok, const UnwrappedLine &Line, const llvm::Regex &CommentPragmasRegex)
template<typename F >
static void AlignTokenSequence (unsigned Start, unsigned End, unsigned Column, F &&Matches, SmallVector< WhitespaceManager::Change, 16 > &Changes)
template<typename F >
static unsigned AlignTokens (const FormatStyle &Style, F &&Matches, SmallVector< WhitespaceManager::Change, 16 > &Changes, unsigned StartAt, const FormatStyle::AlignConsecutiveStyle &ACS=FormatStyle::ACS_None)
static void AlignMacroSequence (unsigned &StartOfSequence, unsigned &EndOfSequence, unsigned &MinColumn, unsigned &MaxColumn, bool &FoundMatchOnLine, std::function< bool(const WhitespaceManager::Change &C)> AlignMacrosMatches, SmallVector< WhitespaceManager::Change, 16 > &Changes)
Variables
static constexpr StringRef Blanks = " \t\v\f\r"
const char * StyleOptionHelpDescription
const char * DefaultFormatStyle = "file"
const char * DefaultFallbackStyle = "LLVM"
Enumeration Type Documentation
BraceBlockKind
enum clang::format::BraceBlockKind
Enumerator
BK_Unknown
BK_Block
BK_BracedInit
Definition at line 137 of file FormatToken.h.
FormatDecision
enum clang::format::FormatDecision
Enumerator
FD_Unformatted
FD_Continue
FD_Break
Definition at line 142 of file FormatToken.h.
LexerState
enum clang::format::LexerState
Enumerator
NORMAL
TEMPLATE_STRING
TOKEN_STASHED
Definition at line 32 of file FormatTokenLexer.h.
LineType
enum clang::format::LineType
Enumerator
LT_Invalid
LT_ImportStatement
LT_ObjCDecl
LT_ObjCMethodDecl
LT_ObjCProperty
LT_Other
LT_PreprocessorDirective
LT_VirtualFunctionDecl
Definition at line 26 of file TokenAnnotator.h.
MacroRole
enum clang::format::MacroRole
Roles a token can take in a configured macro expansion.
Enumerator
MR_ExpandedArg
The token was expanded from a macro argument when formatting the expanded token sequence.
MR_UnexpandedArg
The token is part of a macro argument that was previously formatted as expansion when formatting the unexpanded macro call.
MR_Hidden
The token was expanded from a macro definition, and is not visible as part of the macro call.
Definition at line 145 of file FormatToken.h.
ParameterPackingKind
enum clang::format::ParameterPackingKind
Enumerator
PPK_BinPacked
PPK_OnePerLine
PPK_Inconclusive
Definition at line 140 of file FormatToken.h.
ParseError
enum class clang::format::ParseError strong
Enumerator
Success
Error
Unsuitable
BinPackTrailingCommaConflict
Definition at line 38 of file Format.h.
TokenType
enum clang::format::TokenType : uint8_t
Determines the semantic type of a syntactic token, e.g.
whether "<" is a template opener or binary operator.
Enumerator
NUM_TOKEN_TYPES
Definition at line 126 of file FormatToken.h.
Function Documentation
affectsRange()
static bool clang::format::affectsRange (ArrayRef< tooling::Range > Ranges, unsigned Start, unsigned End) static
Definition at line 2129 of file Format.cpp.
Referenced by sortCppIncludes(), and sortJavaImports().
AlignMacroSequence()
static void clang::format::AlignMacroSequence (unsigned & StartOfSequence, unsigned & EndOfSequence, unsigned & MinColumn, unsigned & MaxColumn, bool & FoundMatchOnLine, std::function< bool(const WhitespaceManager::Change &C)> AlignMacrosMatches, SmallVector< WhitespaceManager::Change, 16 > & Changes) static
Definition at line 505 of file WhitespaceManager.cpp.
References NewlinesBefore, and UINT_MAX.
AlignTokens()
template<typename F > static unsigned clang::format::AlignTokens (const FormatStyle & Style, F && Matches, SmallVector< WhitespaceManager::Change, 16 > & Changes, unsigned StartAt, const FormatStyle::AlignConsecutiveStyle & ACS = FormatStyle::ACS_None) static
Definition at line 364 of file WhitespaceManager.cpp.
References AlignTokens(), AlignTokenSequence(), NewlinesBefore, Tok, and UINT_MAX.
Referenced by AlignTokens().
AlignTokenSequence()
template<typename F > static void clang::format::AlignTokenSequence (unsigned Start, unsigned End, unsigned Column, F && Matches, SmallVector< WhitespaceManager::Change, 16 > & Changes) static
Definition at line 265 of file WhitespaceManager.cpp.
References NewlinesBefore, and Tok.
Referenced by AlignTokens().
cleanup()
tooling::Replacements clang::format::cleanup (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
Definition at line 2776 of file Format.cpp.
Referenced by cleanupAroundReplacements().
cleanupAroundReplacements()
llvm::Expected< tooling::Replacements > clang::format::cleanupAroundReplacements (StringRef Code, const tooling::Replacements & Replaces, const FormatStyle & Style)
Definition at line 2676 of file Format.cpp.
References cleanup(), and processReplacements().
Referenced by clang::tooling::applyAtomicChanges().
closesBlockOrBlockTypeList()
bool clang::format::closesBlockOrBlockTypeList (const FormatStyle & Style) const
Same as opensBlockOrBlockTypeList, but for the closing token.
Definition at line 677 of file FormatToken.h.
References clang::format::FormatToken::is().
CodePointsBetween()
static unsigned clang::format::CodePointsBetween (const FormatToken * Begin, const FormatToken * End) static
Definition at line 147 of file FormatToken.cpp.
References Begin.
Referenced by clang::CommaSeparatedList::precomputeFormattingInfos().
configurationAsText()
std::string clang::format::configurationAsText (const FormatStyle & Style)
Definition at line 1426 of file Format.cpp.
References expandPresets(), and Text.
continuesLineCommentSection()
static bool clang::format::continuesLineCommentSection (const FormatToken & FormatTok, const UnwrappedLine & Line, const llvm::Regex & CommentPragmasRegex) static
Definition at line 2997 of file UnwrappedLineParser.cpp.
References clang::format::FormatToken::is(), Node, and clang::format::FormatToken::TokenText.
copyFrom()
void clang::format::copyFrom (const FormatToken & Tok)
Definition at line 698 of file FormatToken.h.
References clang::format::FormatToken::Tok.
expandPresets()
static FormatStyle clang::format::expandPresets (const FormatStyle & Style) static
Definition at line 775 of file Format.cpp.
Referenced by configurationAsText(), and clang::format::internal::reformat().
FindCursorIndex()
static std::pair< unsigned, unsigned > clang::format::FindCursorIndex (const SmallVectorImpl< IncludeDirective > & Includes, const SmallVectorImpl< unsigned > & Indices, unsigned Cursor) static
Definition at line 2147 of file Format.cpp.
References Text, and UINT_MAX.
Referenced by sortCppIncludes().
findJavaImportGroup()
static unsigned clang::format::findJavaImportGroup (const FormatStyle & Style, StringRef ImportIdentifier) static
Definition at line 2365 of file Format.cpp.
References UINT_MAX.
Referenced by sortJavaImports().
fixNamespaceEndComments()
tooling::Replacements clang::format::fixNamespaceEndComments (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
Definition at line 2795 of file Format.cpp.
References clang::format::TokenAnalyzer::process().
formatReplacements()
llvm::Expected< tooling::Replacements > clang::format::formatReplacements (StringRef Code, const tooling::Replacements & Replaces, const FormatStyle & Style)
Definition at line 2566 of file Format.cpp.
References processReplacements(), reformat(), and sortIncludes().
Referenced by clang::tooling::formatAndApplyAllReplacements().
getCanonicalRawStringDelimiter()
static StringRef clang::format::getCanonicalRawStringDelimiter (const FormatStyle & Style, FormatStyle::LanguageKind Language) static
Definition at line 174 of file ContinuationIndenter.cpp.
getChromiumStyle()
FormatStyle clang::format::getChromiumStyle (FormatStyle::LanguageKind Language)
Definition at line 1176 of file Format.cpp.
References getGoogleStyle(), and clang::tooling::IncludeStyle::IBS_Preserve.
Referenced by getPredefinedStyle().
getCommentSplit()
static BreakableToken::Split clang::format::getCommentSplit (StringRef Text, unsigned ContentStartColumn, unsigned ColumnLimit, unsigned TabWidth, encoding::Encoding Encoding, const FormatStyle & Style, bool DecorationEndsWithStar = false) static
Definition at line 68 of file BreakableToken.cpp.
References Blanks, clang::format::encoding::columnWidthWithTabs(), clang::format::encoding::getCodePointNumBytes(), and Text.
Referenced by clang::format::BreakableBlockComment::getSplit(), and clang::format::BreakableComment::getSplit().
getEnclosingFunctionName()
static StringRef clang::format::getEnclosingFunctionName (const FormatToken & Current) static
Definition at line 1868 of file ContinuationIndenter.cpp.
References Tok, and clang::format::FormatToken::TokenText.
getFormattingLangOpts()
LangOptions clang::format::getFormattingLangOpts (const FormatStyle & Style)
Definition at line 2813 of file Format.cpp.
Referenced by clang::format::TokenAnalyzer::process().
getGNUStyle()
FormatStyle clang::format::getGNUStyle ()
Definition at line 1285 of file Format.cpp.
References getLLVMStyle().
Referenced by getPredefinedStyle().
getGoogleStyle()
FormatStyle clang::format::getGoogleStyle (FormatStyle::LanguageKind Language)
Definition at line 1036 of file Format.cpp.
References getGoogleStyle(), getLLVMStyle(), clang::tooling::IncludeStyle::IBS_Preserve, and clang::tooling::IncludeStyle::IBS_Regroup.
Referenced by getChromiumStyle(), getGoogleStyle(), and getPredefinedStyle().
getLanguageByFileName()
static FormatStyle::LanguageKind clang::format::getLanguageByFileName (StringRef FileName) static
Definition at line 2850 of file Format.cpp.
Referenced by guessLanguage().
getLanguageName()
StringRef clang::format::getLanguageName (FormatStyle::LanguageKind Language) inline
The FormatStyle is used to configure the formatting to follow / specific guidelines.
struct FormatStyle { / The extra indent or outdent of access modifiers, e.g. public:. int AccessModifierOffset;
/ Different styles for aligning after open brackets. enum BracketAlignmentStyle : unsigned char { / Align parameters on the open bracket, e.g.: /
///   someLongFunction(argument1,
///                    argument2);
///
BAS_Align, / Don't align, instead use ContinuationIndentWidth, e.g.: /
///   someLongFunction(argument1,
///       argument2);
///
BAS_DontAlign, / Always break after an open bracket, if the parameters don't fit / on a single line, e.g.: /
///   someLongFunction(
///       argument1, argument2);
///
BAS_AlwaysBreak, };
/ If true, horizontally aligns arguments after an open bracket. / / This applies to round brackets (parentheses), angle brackets and square / brackets. BracketAlignmentStyle AlignAfterOpenBracket;
/ Styles for alignment of consecutive tokens. Tokens can be assignment signs / (see / AlignConsecutiveAssignments), bitfield member separators (see / AlignConsecutiveBitFields), names in declarations (see / AlignConsecutiveDeclarations) or macro definitions (see / AlignConsecutiveMacros). enum AlignConsecutiveStyle { ACS_None, ACS_Consecutive, ACS_AcrossEmptyLines, ACS_AcrossComments, ACS_AcrossEmptyLinesAndComments };
/ Style of aligning consecutive macro definitions. / / Consecutive will result in formattings like: /
///   #define SHORT_NAME       42
///   #define LONGER_NAME      0x007f
///   #define EVEN_LONGER_NAME (2)
///   #define foo(x)           (x * x)
///   #define bar(y, z)        (y + z)
///
/ / Possible values: / / * ACS_None (in configuration: None) / Do not align macro definitions on consecutive lines. / / * ACS_Consecutive (in configuration: Consecutive) / Align macro definitions on consecutive lines. This will result in / formattings like: /
///      #define SHORT_NAME       42
///      #define LONGER_NAME      0x007f
///      #define EVEN_LONGER_NAME (2)
///
///      #define foo(x) (x * x)
///      /* some comment */
///      #define bar(y, z) (y + z)
///
/ / * ACS_AcrossEmptyLines (in configuration: AcrossEmptyLines) / Same as ACS_Consecutive, but also spans over empty lines, e.g. /
///      #define SHORT_NAME       42
///      #define LONGER_NAME      0x007f
///      #define EVEN_LONGER_NAME (2)
///
///      #define foo(x)           (x * x)
///      /* some comment */
///      #define bar(y, z) (y + z)
///
/ / * ACS_AcrossComments (in configuration: AcrossComments) / Same as ACS_Consecutive, but also spans over lines only containing / comments, e.g. /
///      #define SHORT_NAME       42
///      #define LONGER_NAME      0x007f
///      #define EVEN_LONGER_NAME (2)
///
///      #define foo(x)    (x * x)
///      /* some comment */
///      #define bar(y, z) (y + z)
///
/ / * ACS_AcrossEmptyLinesAndComments / (in configuration: AcrossEmptyLinesAndComments) / / Same as ACS_Consecutive, but also spans over lines only containing / comments and empty lines, e.g. /
///      #define SHORT_NAME       42
///      #define LONGER_NAME      0x007f
///      #define EVEN_LONGER_NAME (2)
///
///      #define foo(x)           (x * x)
///      /* some comment */
///      #define bar(y, z)        (y + z)
///
AlignConsecutiveStyle AlignConsecutiveMacros;
/ Style of aligning consecutive assignments. / / Consecutive will result in formattings like: /
///   int a            = 1;
///   int somelongname = 2;
///   double c         = 3;
///
/ / Possible values: / / * ACS_None (in configuration: None) / Do not align assignments on consecutive lines. / / * ACS_Consecutive (in configuration: Consecutive) / Align assignments on consecutive lines. This will result in / formattings like: /
///      int a            = 1;
///      int somelongname = 2;
///      double c         = 3;
///
///      int d = 3;
///      /* A comment. */
///      double e = 4;
///
/ / * ACS_AcrossEmptyLines (in configuration: AcrossEmptyLines) / Same as ACS_Consecutive, but also spans over empty lines, e.g. /
///      int a            = 1;
///      int somelongname = 2;
///      double c         = 3;
///
///      int d            = 3;
///      /* A comment. */
///      double e = 4;
///
/ / * ACS_AcrossComments (in configuration: AcrossComments) / Same as ACS_Consecutive, but also spans over lines only containing / comments, e.g. /
///      int a            = 1;
///      int somelongname = 2;
///      double c         = 3;
///
///      int d    = 3;
///      /* A comment. */
///      double e = 4;
///
/ / * ACS_AcrossEmptyLinesAndComments / (in configuration: AcrossEmptyLinesAndComments) / / Same as ACS_Consecutive, but also spans over lines only containing / comments and empty lines, e.g. /
///      int a            = 1;
///      int somelongname = 2;
///      double c         = 3;
///
///      int d            = 3;
///      /* A comment. */
///      double e         = 4;
///
AlignConsecutiveStyle AlignConsecutiveAssignments;
/ Style of aligning consecutive bit field. / / Consecutive will align the bitfield separators of consecutive lines. / This will result in formattings like: /
///   int aaaa : 1;
///   int b    : 12;
///   int ccc  : 8;
///
/ / Possible values: / / * ACS_None (in configuration: None) / Do not align bit fields on consecutive lines. / / * ACS_Consecutive (in configuration: Consecutive) / Align bit fields on consecutive lines. This will result in / formattings like: /
///      int aaaa : 1;
///      int b    : 12;
///      int ccc  : 8;
///
///      int d : 2;
///      /* A comment. */
///      int ee : 3;
///
/ / * ACS_AcrossEmptyLines (in configuration: AcrossEmptyLines) / Same as ACS_Consecutive, but also spans over empty lines, e.g. /
///      int aaaa : 1;
///      int b    : 12;
///      int ccc  : 8;
///
///      int d    : 2;
///      /* A comment. */
///      int ee : 3;
///
/ / * ACS_AcrossComments (in configuration: AcrossComments) / Same as ACS_Consecutive, but also spans over lines only containing / comments, e.g. /
///      int aaaa : 1;
///      int b    : 12;
///      int ccc  : 8;
///
///      int d  : 2;
///      /* A comment. */
///      int ee : 3;
///
/ / * ACS_AcrossEmptyLinesAndComments / (in configuration: AcrossEmptyLinesAndComments) / / Same as ACS_Consecutive, but also spans over lines only containing / comments and empty lines, e.g. /
///      int aaaa : 1;
///      int b    : 12;
///      int ccc  : 8;
///
///      int d    : 2;
///      /* A comment. */
///      int ee   : 3;
///
AlignConsecutiveStyle AlignConsecutiveBitFields;
/ Style of aligning consecutive declarations. / / Consecutive will align the declaration names of consecutive lines. / This will result in formattings like: /
///   int         aaaa = 12;
///   float       b = 23;
///   std::string ccc;
///
/ / Possible values: / / * ACS_None (in configuration: None) / Do not align bit declarations on consecutive lines. / / * ACS_Consecutive (in configuration: Consecutive) / Align declarations on consecutive lines. This will result in / formattings like: /
///      int         aaaa = 12;
///      float       b = 23;
///      std::string ccc;
///
///      int a = 42;
///      /* A comment. */
///      bool c = false;
///
/ / * ACS_AcrossEmptyLines (in configuration: AcrossEmptyLines) / Same as ACS_Consecutive, but also spans over empty lines, e.g. /
///      int         aaaa = 12;
///      float       b = 23;
///      std::string ccc;
///
///      int         a = 42;
///      /* A comment. */
///      bool c = false;
///
/ / * ACS_AcrossComments (in configuration: AcrossComments) / Same as ACS_Consecutive, but also spans over lines only containing / comments, e.g. /
///      int         aaaa = 12;
///      float       b = 23;
///      std::string ccc;
///
///      int  a = 42;
///      /* A comment. */
///      bool c = false;
///
/ / * ACS_AcrossEmptyLinesAndComments / (in configuration: AcrossEmptyLinesAndComments) / / Same as ACS_Consecutive, but also spans over lines only containing / comments and empty lines, e.g. /
///      int         aaaa = 12;
///      float       b = 23;
///      std::string ccc;
///
///      int         a = 42;
///      /* A comment. */
///      bool        c = false;
///
AlignConsecutiveStyle AlignConsecutiveDeclarations;
/ Different styles for aligning escaped newlines. enum EscapedNewlineAlignmentStyle : unsigned char { / Don't align escaped newlines. /
///   #define A \
///     int aaaa; \
///     int b; \
///     int dddddddddd;
///
ENAS_DontAlign, / Align escaped newlines as far left as possible. /
///   true:
///   #define A   \
///     int aaaa; \
///     int b;    \
///     int dddddddddd;
///
///   false:
///
ENAS_Left, / Align escaped newlines in the right-most column. /
///   #define A                                                                      \
///     int aaaa;                                                                    \
///     int b;                                                                       \
///     int dddddddddd;
///
ENAS_Right, };
/ Options for aligning backslashes in escaped newlines. EscapedNewlineAlignmentStyle AlignEscapedNewlines;
/ Different styles for aligning operands. enum OperandAlignmentStyle : unsigned char { / Do not align operands of binary and ternary expressions. / The wrapped lines are indented ContinuationIndentWidth spaces from / the start of the line. OAS_DontAlign, / Horizontally align operands of binary and ternary expressions. / / Specifically, this aligns operands of a single expression that needs / to be split over multiple lines, e.g.: /
///   int aaa = bbbbbbbbbbbbbbb +
///             ccccccccccccccc;
///
/ / When BreakBeforeBinaryOperators is set, the wrapped operator is / aligned with the operand on the first line. /
///   int aaa = bbbbbbbbbbbbbbb
///             + ccccccccccccccc;
///
OAS_Align, / Horizontally align operands of binary and ternary expressions. / / This is similar to AO_Align, except when / BreakBeforeBinaryOperators is set, the operator is un-indented so / that the wrapped operand is aligned with the operand on the first line. /
///   int aaa = bbbbbbbbbbbbbbb
///           + ccccccccccccccc;
///
OAS_AlignAfterOperator, };
/ If true, horizontally align operands of binary and ternary / expressions. OperandAlignmentStyle AlignOperands;
/ If true, aligns trailing comments. /
///   true:                                   false:
///   int a;     // My comment a      vs.     int a; // My comment a
///   int b = 2; // comment  b                int b = 2; // comment about b
///
bool AlignTrailingComments;
/ If a function call or braced initializer list doesn't fit on a / line, allow putting all arguments onto the next line, even if / BinPackArguments is false. /
///   true:
///   callFunction(
///       a, b, c, d);
///
///   false:
///   callFunction(a,
///                b,
///                c,
///                d);
///
bool AllowAllArgumentsOnNextLine;
/ If a constructor definition with a member initializer list doesn't / fit on a single line, allow putting all member initializers onto the next / line, if ConstructorInitializerAllOnOneLineOrOnePerLine is true. / Note that this parameter has no effect if / ConstructorInitializerAllOnOneLineOrOnePerLine is false. /
///   true:
///   MyClass::MyClass() :
///       member0(0), member1(2) {}
///
///   false:
///   MyClass::MyClass() :
///       member0(0),
///       member1(2) {}
bool AllowAllConstructorInitializersOnNextLine;
/// If the function declaration doesn't fit on a line,
/// allow putting all parameters of a function declaration onto
/// the next line even if ``BinPackParameters`` is ``false``.
/// \code
///   true:
///   void myFunction(
///       int a, int b, int c, int d, int e);
///
///   false:
///   void myFunction(int a,
///                   int b,
///                   int c,
///                   int d,
///                   int e);
///
bool AllowAllParametersOfDeclarationOnNextLine;
/ Allow short enums on a single line. /
///   true:
///   enum { A, B } myEnum;
///
///   false:
///   enum
///   {
///     A,
///     B
///   } myEnum;
///
bool AllowShortEnumsOnASingleLine;
/ Different styles for merging short blocks containing at most one / statement. enum ShortBlockStyle : unsigned char { / Never merge blocks into a single line. /
///   while (true) {
///   }
///   while (true) {
///     continue;
///   }
///
SBS_Never, / Only merge empty blocks. /
///   while (true) {}
///   while (true) {
///     continue;
///   }
///
SBS_Empty, / Always merge short blocks into a single line. /
///   while (true) {}
///   while (true) { continue; }
///
SBS_Always, };
/ Dependent on the value, while (true) { continue; } can be put on a / single line. ShortBlockStyle AllowShortBlocksOnASingleLine;
/ If true, short case labels will be contracted to a single line. /
///   true:                                   false:
///   switch (a) {                    vs.     switch (a) {
///   case 1: x = 1; break;                   case 1:
///   case 2: return;                           x = 1;
///   }                                         break;
///                                           case 2:
///                                             return;
///                                           }
///
bool AllowShortCaseLabelsOnASingleLine;
/ Different styles for merging short functions containing at most one / statement. enum ShortFunctionStyle : unsigned char { / Never merge functions into a single line. SFS_None, / Only merge functions defined inside a class. Same as "inline", / except it does not implies "empty": i.e. top level empty functions / are not merged either. /
///   class Foo {
///     void f() { foo(); }
///   };
///   void f() {
///     foo();
///   }
///   void f() {
///   }
///
SFS_InlineOnly, / Only merge empty functions. /
///   void f() {}
///   void f2() {
///     bar2();
///   }
///
SFS_Empty, / Only merge functions defined inside a class. Implies "empty". /
///   class Foo {
///     void f() { foo(); }
///   };
///   void f() {
///     foo();
///   }
///   void f() {}
///
SFS_Inline, / Merge all functions fitting on a single line. /
///   class Foo {
///     void f() { foo(); }
///   };
///   void f() { bar(); }
///
SFS_All, };
/ Dependent on the value, int f() { return 0; } can be put on a / single line. ShortFunctionStyle AllowShortFunctionsOnASingleLine;
/ Different styles for handling short if lines enum ShortIfStyle : unsigned char { / Never put short ifs on the same line. /
///   if (a)
///     return ;
///   else {
///     return;
///   }
///
SIS_Never, / Without else put short ifs on the same line only if / the else is not a compound statement. /
///   if (a) return;
///   else
///     return;
///
SIS_WithoutElse, / Always put short ifs on the same line if / the else is not a compound statement or not. /
///   if (a) return;
///   else {
///     return;
///   }
///
SIS_Always, };
/ If true, if (a) return; can be put on a single line. ShortIfStyle AllowShortIfStatementsOnASingleLine;
/ Different styles for merging short lambdas containing at most one / statement. enum ShortLambdaStyle : unsigned char { / Never merge lambdas into a single line. SLS_None, / Only merge empty lambdas. /
///   auto lambda = [](int a) {}
///   auto lambda2 = [](int a) {
///       return a;
///   };
///
SLS_Empty, / Merge lambda into a single line if argument of a function. /
///   auto lambda = [](int a) {
///       return a;
///   };
///   sort(a.begin(), a.end(), ()[] { return x < y; })
///
SLS_Inline, / Merge all lambdas fitting on a single line. /
///   auto lambda = [](int a) {}
///   auto lambda2 = [](int a) { return a; };
///
SLS_All, };
/ Dependent on the value, auto lambda []() { return 0; } can be put on a / single line. ShortLambdaStyle AllowShortLambdasOnASingleLine;
/ If true, while (true) continue; can be put on a single / line. bool AllowShortLoopsOnASingleLine;
/ Different ways to break after the function definition return type. / This option is deprecated and is retained for backwards compatibility. enum DefinitionReturnTypeBreakingStyle : unsigned char { / Break after return type automatically. / PenaltyReturnTypeOnItsOwnLine is taken into account. DRTBS_None, / Always break after the return type. DRTBS_All, / Always break after the return types of top-level functions. DRTBS_TopLevel, };
/ Different ways to break after the function definition or / declaration return type. enum ReturnTypeBreakingStyle : unsigned char { / Break after return type automatically. / PenaltyReturnTypeOnItsOwnLine is taken into account. /
///   class A {
///     int f() { return 0; };
///   };
///   int f();
///   int f() { return 1; }
///
RTBS_None, / Always break after the return type. /
///   class A {
///     int
///     f() {
///       return 0;
///     };
///   };
///   int
///   f();
///   int
///   f() {
///     return 1;
///   }
///
RTBS_All, / Always break after the return types of top-level functions. /
///   class A {
///     int f() { return 0; };
///   };
///   int
///   f();
///   int
///   f() {
///     return 1;
///   }
///
RTBS_TopLevel, / Always break after the return type of function definitions. /
///   class A {
///     int
///     f() {
///       return 0;
///     };
///   };
///   int f();
///   int
///   f() {
///     return 1;
///   }
///
RTBS_AllDefinitions, / Always break after the return type of top-level definitions. /
///   class A {
///     int f() { return 0; };
///   };
///   int f();
///   int
///   f() {
///     return 1;
///   }
///
RTBS_TopLevelDefinitions, };
/ The function definition return type breaking style to use. This / option is deprecated and is retained for backwards compatibility. DefinitionReturnTypeBreakingStyle AlwaysBreakAfterDefinitionReturnType;
/ The function declaration return type breaking style to use. ReturnTypeBreakingStyle AlwaysBreakAfterReturnType;
/ If true, always break before multiline string literals. / / This flag is mean to make cases where there are multiple multiline strings / in a file look more consistent. Thus, it will only take effect if wrapping / the string at that point leads to it being indented / ContinuationIndentWidth spaces from the start of the line. /
///    true:                                  false:
///    aaaa =                         vs.     aaaa = "bbbb"
///        "bbbb"                                    "cccc";
///        "cccc";
///
bool AlwaysBreakBeforeMultilineStrings;
/ Different ways to break after the template declaration. enum BreakTemplateDeclarationsStyle : unsigned char { / Do not force break before declaration. / PenaltyBreakTemplateDeclaration is taken into account. /
///    template <typename T> T foo() {
///    }
///    template <typename T> T foo(int aaaaaaaaaaaaaaaaaaaaa,
///                                int bbbbbbbbbbbbbbbbbbbbb) {
///    }
///
BTDS_No, / Force break after template declaration only when the following / declaration spans multiple lines. /
///    template <typename T> T foo() {
///    }
///    template <typename T>
///    T foo(int aaaaaaaaaaaaaaaaaaaaa,
///          int bbbbbbbbbbbbbbbbbbbbb) {
///    }
///
BTDS_MultiLine, / Always break after template declaration. /
///    template <typename T>
///    T foo() {
///    }
///    template <typename T>
///    T foo(int aaaaaaaaaaaaaaaaaaaaa,
///          int bbbbbbbbbbbbbbbbbbbbb) {
///    }
///
BTDS_Yes };
/ The template declaration breaking style to use. BreakTemplateDeclarationsStyle AlwaysBreakTemplateDeclarations;
/ A vector of strings that should be interpreted as attributes/qualifiers / instead of identifiers. This can be useful for language extensions or / static analyzer annotations. / / For example: /
///   x = (char *__capability)&y;
///   int function(void) __ununsed;
///   void only_writes_to_buffer(char *__output buffer);
///
/ / In the .clang-format configuration file, this can be configured like: /
///   AttributeMacros: ['__capability', '__output', '__ununsed']
///
/ std::vector<std::string> AttributeMacros;
/ If false, a function call's arguments will either be all on the / same line or will have one line each. /
///   true:
///   void f() {
///     f(aaaaaaaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaaaa,
///       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa);
///   }
///
///   false:
///   void f() {
///     f(aaaaaaaaaaaaaaaaaaaa,
///       aaaaaaaaaaaaaaaaaaaa,
///       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa);
///   }
///
bool BinPackArguments;
/ The style of inserting trailing commas into container literals. enum TrailingCommaStyle : unsigned char { / Do not insert trailing commas. TCS_None, / Insert trailing commas in container literals that were wrapped over / multiple lines. Note that this is conceptually incompatible with / bin-packing, because the trailing comma is used as an indicator / that a container should be formatted one-per-line (i.e. not bin-packed). / So inserting a trailing comma counteracts bin-packing. TCS_Wrapped, };
/ If set to TCS_Wrapped will insert trailing commas in container / literals (arrays and objects) that wrap across multiple lines. / It is currently only available for JavaScript / and disabled by default TCS_None. / InsertTrailingCommas cannot be used together with BinPackArguments / as inserting the comma disables bin-packing. /
///   TSC_Wrapped:
///   const someArray = [
///   aaaaaaaaaaaaaaaaaaaaaaaaaa,
///   aaaaaaaaaaaaaaaaaaaaaaaaaa,
///   aaaaaaaaaaaaaaaaaaaaaaaaaa,
///   //                        ^ inserted
///   ]
///
TrailingCommaStyle InsertTrailingCommas;
/ If false, a function declaration's or function definition's / parameters will either all be on the same line or will have one line each. /
///   true:
///   void f(int aaaaaaaaaaaaaaaaaaaa, int aaaaaaaaaaaaaaaaaaaa,
///          int aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) {}
///
///   false:
///   void f(int aaaaaaaaaaaaaaaaaaaa,
///          int aaaaaaaaaaaaaaaaaaaa,
///          int aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) {}
///
bool BinPackParameters;
/ The style of wrapping parameters on the same line (bin-packed) or / on one line each. enum BinPackStyle : unsigned char { / Automatically determine parameter bin-packing behavior. BPS_Auto, / Always bin-pack parameters. BPS_Always, / Never bin-pack parameters. BPS_Never, };
/ The style of breaking before or after binary operators. enum BinaryOperatorStyle : unsigned char { / Break after operators. /
///    LooooooooooongType loooooooooooooooooooooongVariable =
///        someLooooooooooooooooongFunction();
///
///    bool value = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa +
///                         aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ==
///                     aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa &&
///                 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa >
///                     ccccccccccccccccccccccccccccccccccccccccc;
///
BOS_None, / Break before operators that aren't assignments. /
///    LooooooooooongType loooooooooooooooooooooongVariable =
///        someLooooooooooooooooongFunction();
///
///    bool value = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                         + aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                     == aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                 && aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                        > ccccccccccccccccccccccccccccccccccccccccc;
///
BOS_NonAssignment, / Break before operators. /
///    LooooooooooongType loooooooooooooooooooooongVariable
///        = someLooooooooooooooooongFunction();
///
///    bool value = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                         + aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                     == aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                 && aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
///                        > ccccccccccccccccccccccccccccccccccccccccc;
///
BOS_All, };
/ The way to wrap binary operators. BinaryOperatorStyle BreakBeforeBinaryOperators;
/ Different ways to attach braces to their surrounding context. enum BraceBreakingStyle : unsigned char { / Always attach braces to surrounding context. /
///   namespace N {
///   enum E {
///     E1,
///     E2,
///   };
///
///   class C {
///   public:
///     C();
///   };
///
///   bool baz(int i) {
///     try {
///       do {
///         switch (i) {
///         case 1: {
///           foobar();
///           break;
///         }
///         default: {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     } catch (...) {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b) {
///     if (b) {
///       baz(2);
///     } else {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_Attach, / Like Attach, but break before braces on function, namespace and / class definitions. /
///   namespace N
///   {
///   enum E {
///     E1,
///     E2,
///   };
///
///   class C
///   {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try {
///       do {
///         switch (i) {
///         case 1: {
///           foobar();
///           break;
///         }
///         default: {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     } catch (...) {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b)
///   {
///     if (b) {
///       baz(2);
///     } else {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_Linux, / Like Attach, but break before braces on enum, function, and record / definitions. /
///   namespace N {
///   enum E
///   {
///     E1,
///     E2,
///   };
///
///   class C
///   {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try {
///       do {
///         switch (i) {
///         case 1: {
///           foobar();
///           break;
///         }
///         default: {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     } catch (...) {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b)
///   {
///     if (b) {
///       baz(2);
///     } else {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_Mozilla, / Like Attach, but break before function definitions, catch, and / else. /
///   namespace N {
///   enum E {
///     E1,
///     E2,
///   };
///
///   class C {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try {
///       do {
///         switch (i) {
///         case 1: {
///           foobar();
///           break;
///         }
///         default: {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     }
///     catch (...) {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b)
///   {
///     if (b) {
///       baz(2);
///     }
///     else {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_Stroustrup, / Always break before braces. /
///   namespace N
///   {
///   enum E
///   {
///     E1,
///     E2,
///   };
///
///   class C
///   {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try
///     {
///       do
///       {
///         switch (i)
///         {
///         case 1:
///         {
///           foobar();
///           break;
///         }
///         default:
///         {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     }
///     catch (...)
///     {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b)
///   {
///     if (b)
///     {
///       baz(2);
///     }
///     else
///     {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_Allman, / Like Allman but always indent braces and line up code with braces. /
///   namespace N
///     {
///   enum E
///     {
///     E1,
///     E2,
///     };
///
///   class C
///     {
///   public:
///     C();
///     };
///
///   bool baz(int i)
///     {
///     try
///       {
///       do
///         {
///         switch (i)
///           {
///           case 1:
///           {
///           foobar();
///           break;
///           }
///           default:
///           {
///           break;
///           }
///           }
///         } while (--i);
///       return true;
///       }
///     catch (...)
///       {
///       handleError();
///       return false;
///       }
///     }
///
///   void foo(bool b)
///     {
///     if (b)
///       {
///       baz(2);
///       }
///     else
///       {
///       baz(5);
///       }
///     }
///
///   void bar() { foo(true); }
///     } // namespace N
///
BS_Whitesmiths, / Always break before braces and add an extra level of indentation to / braces of control statements, not to those of class, function / or other definitions. /
///   namespace N
///   {
///   enum E
///   {
///     E1,
///     E2,
///   };
///
///   class C
///   {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try
///       {
///         do
///           {
///             switch (i)
///               {
///               case 1:
///                 {
///                   foobar();
///                   break;
///                 }
///               default:
///                 {
///                   break;
///                 }
///               }
///           }
///         while (--i);
///         return true;
///       }
///     catch (...)
///       {
///         handleError();
///         return false;
///       }
///   }
///
///   void foo(bool b)
///   {
///     if (b)
///       {
///         baz(2);
///       }
///     else
///       {
///         baz(5);
///       }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_GNU, / Like Attach, but break before functions. /
///   namespace N {
///   enum E {
///     E1,
///     E2,
///   };
///
///   class C {
///   public:
///     C();
///   };
///
///   bool baz(int i)
///   {
///     try {
///       do {
///         switch (i) {
///         case 1: {
///           foobar();
///           break;
///         }
///         default: {
///           break;
///         }
///         }
///       } while (--i);
///       return true;
///     } catch (...) {
///       handleError();
///       return false;
///     }
///   }
///
///   void foo(bool b)
///   {
///     if (b) {
///       baz(2);
///     } else {
///       baz(5);
///     }
///   }
///
///   void bar() { foo(true); }
///   } // namespace N
///
BS_WebKit, / Configure each individual brace in BraceWrapping. BS_Custom };
/ The brace breaking style to use. BraceBreakingStyle BreakBeforeBraces;
/ Different ways to wrap braces after control statements. enum BraceWrappingAfterControlStatementStyle : unsigned char { / Never wrap braces after a control statement. /
///   if (foo()) {
///   } else {
///   }
///   for (int i = 0; i < 10; ++i) {
///   }
///
BWACS_Never, / Only wrap braces after a multi-line control statement. /
///   if (foo && bar &&
///       baz)
///   {
///     quux();
///   }
///   while (foo || bar) {
///   }
///
BWACS_MultiLine, / Always wrap braces after a control statement. /
///   if (foo())
///   {
///   } else
///   {}
///   for (int i = 0; i < 10; ++i)
///   {}
///
BWACS_Always };
/ Precise control over the wrapping of braces. /
///   # Should be declared this way:
///   BreakBeforeBraces: Custom
///   BraceWrapping:
///       AfterClass: true
///
struct BraceWrappingFlags { / Wrap case labels. /
///   false:                                true:
///   switch (foo) {                vs.     switch (foo) {
///     case 1: {                             case 1:
///       bar();                              {
///       break;                                bar();
///     }                                       break;
///     default: {                            }
///       plop();                             default:
///     }                                     {
///   }                                         plop();
///                                           }
///                                         }
///
bool AfterCaseLabel; / Wrap class definitions. /
///   true:
///   class foo {};
///
///   false:
///   class foo
///   {};
///
bool AfterClass;
/ Wrap control statements (if/for/while/switch/..). BraceWrappingAfterControlStatementStyle AfterControlStatement; / Wrap enum definitions. /
///   true:
///   enum X : int
///   {
///     B
///   };
///
///   false:
///   enum X : int { B };
///
bool AfterEnum; / Wrap function definitions. /
///   true:
///   void foo()
///   {
///     bar();
///     bar2();
///   }
///
///   false:
///   void foo() {
///     bar();
///     bar2();
///   }
///
bool AfterFunction; / Wrap namespace definitions. /
///   true:
///   namespace
///   {
///   int foo();
///   int bar();
///   }
///
///   false:
///   namespace {
///   int foo();
///   int bar();
///   }
///
bool AfterNamespace; / Wrap ObjC definitions (interfaces, implementations...). /
Note
@autoreleasepool and @synchronized blocks are wrapped / according to AfterControlStatement flag. bool AfterObjCDeclaration; / Wrap struct definitions. /
///   true:
///   struct foo
///   {
///     int x;
///   };
///
///   false:
///   struct foo {
///     int x;
///   };
///
bool AfterStruct; / Wrap union definitions. /
///   true:
///   union foo
///   {
///     int x;
///   }
///
///   false:
///   union foo {
///     int x;
///   }
///
bool AfterUnion; / Wrap extern blocks. /
///   true:
///   extern "C"
///   {
///     int foo();
///   }
///
///   false:
///   extern "C" {
///   int foo();
///   }
///
bool AfterExternBlock; // Partially superseded by IndentExternBlock / Wrap before catch. /
///   true:
///   try {
///     foo();
///   }
///   catch () {
///   }
///
///   false:
///   try {
///     foo();
///   } catch () {
///   }
///
bool BeforeCatch; / Wrap before else. /
///   true:
///   if (foo()) {
///   }
///   else {
///   }
///
///   false:
///   if (foo()) {
///   } else {
///   }
///
bool BeforeElse; / Wrap lambda block. /
///   true:
///   connect(
///     []()
///     {
///       foo();
///       bar();
///     });
///
///   false:
///   connect([]() {
///     foo();
///     bar();
///   });
///
bool BeforeLambdaBody; / Wrap before while. /
///   true:
///   do {
///     foo();
///   }
///   while (1);
///
///   false:
///   do {
///     foo();
///   } while (1);
///
bool BeforeWhile; / Indent the wrapped braces themselves. bool IndentBraces; / If false, empty function body can be put on a single line. / This option is used only if the opening brace of the function has / already been wrapped, i.e. the AfterFunction brace wrapping mode is / set, and the function could/should not be put on a single line (as per / AllowShortFunctionsOnASingleLine and constructor formatting options). /
///   int f()   vs.   int f()
///   {}              {
///                   }
///
/ bool SplitEmptyFunction; / If false, empty record (e.g. class, struct or union) body / can be put on a single line. This option is used only if the opening / brace of the record has already been wrapped, i.e. the AfterClass / (for classes) brace wrapping mode is set. /
///   class Foo   vs.  class Foo
///   {}               {
///                    }
///
/ bool SplitEmptyRecord; / If false, empty namespace body can be put on a single line. / This option is used only if the opening brace of the namespace has / already been wrapped, i.e. the AfterNamespace brace wrapping mode is / set. /
///   namespace Foo   vs.  namespace Foo
///   {}                   {
///                        }
///
/ bool SplitEmptyNamespace; };
/ Control of individual brace wrapping cases. / / If BreakBeforeBraces is set to BS_Custom, use this to specify how / each individual brace case should be handled. Otherwise, this is ignored. /
///   # Example of usage:
///   BreakBeforeBraces: Custom
///   BraceWrapping:
///     AfterEnum: true
///     AfterStruct: false
///     SplitEmptyFunction: false
///
BraceWrappingFlags BraceWrapping;
/ If true, concept will be placed on a new line. /
///   true:
///    template<typename T>
///    concept ...
///
///   false:
///    template<typename T> concept ...
///
bool BreakBeforeConceptDeclarations;
/ If true, ternary operators will be placed after line breaks. /
///    true:
///    veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongDescription
///        ? firstValue
///        : SecondValueVeryVeryVeryVeryLong;
///
///    false:
///    veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongDescription ?
///        firstValue :
///        SecondValueVeryVeryVeryVeryLong;
///
bool BreakBeforeTernaryOperators;
/ Different ways to break initializers. enum BreakConstructorInitializersStyle : unsigned char { / Break constructor initializers before the colon and after the commas. /
///    Constructor()
///        : initializer1(),
///          initializer2()
///
BCIS_BeforeColon, / Break constructor initializers before the colon and commas, and align / the commas with the colon. /
///    Constructor()
///        : initializer1()
///        , initializer2()
///
BCIS_BeforeComma, / Break constructor initializers after the colon and commas. /
///    Constructor() :
///        initializer1(),
///        initializer2()
///
BCIS_AfterColon };
/ The constructor initializers style to use. BreakConstructorInitializersStyle BreakConstructorInitializers;
/ Break after each annotation on a field in Java files. /
///    true:                                  false:
///    @Partial                       vs.     @Partial @Mock DataLoad loader;
///    @Mock
///    DataLoad loader;
///
bool BreakAfterJavaFieldAnnotations;
/ Allow breaking string literals when formatting. /
///    true:
///    const char* x = "veryVeryVeryVeryVeryVe"
///                    "ryVeryVeryVeryVeryVery"
///                    "VeryLongString";
///
///    false:
///    const char* x =
///      "veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString";
///
bool BreakStringLiterals;
/ The column limit. / / A column limit of 0 means that there is no column limit. In this case, / clang-format will respect the input's line breaking decisions within / statements unless they contradict other rules. unsigned ColumnLimit;
/ A regular expression that describes comments with special meaning, / which should not be split into lines or otherwise changed. /
///    // CommentPragmas: '^ FOOBAR pragma:'
///    // Will leave the following line unaffected
///    #include <vector> // FOOBAR pragma: keep
///
std::string CommentPragmas;
/ Different ways to break inheritance list. enum BreakInheritanceListStyle : unsigned char { / Break inheritance list before the colon and after the commas. /
///    class Foo
///        : Base1,
///          Base2
///    {};
///
BILS_BeforeColon, / Break inheritance list before the colon and commas, and align / the commas with the colon. /
///    class Foo
///        : Base1
///        , Base2
///    {};
///
BILS_BeforeComma, / Break inheritance list after the colon and commas. /
///    class Foo :
///        Base1,
///        Base2
///    {};
///
BILS_AfterColon };
/ The inheritance list style to use. BreakInheritanceListStyle BreakInheritanceList;
/ If true, consecutive namespace declarations will be on the same / line. If false, each namespace is declared on a new line. /
///   true:
///   namespace Foo { namespace Bar {
///   }}
///
///   false:
///   namespace Foo {
///   namespace Bar {
///   }
///   }
///
/ / If it does not fit on a single line, the overflowing namespaces get / wrapped: /
///   namespace Foo { namespace Bar {
///   namespace Extra {
///   }}}
///
bool CompactNamespaces;
clang-format off / If the constructor initializers don't fit on a line, put each / initializer on its own line. /
///   true:
///   SomeClass::Constructor()
///       : aaaaaaaa(aaaaaaaa), aaaaaaaa(aaaaaaaa), aaaaaaaa(aaaaaaaaaaaaaaaaaaaaaaaaa) {
///     return 0;
///   }
///
///   false:
///   SomeClass::Constructor()
///       : aaaaaaaa(aaaaaaaa), aaaaaaaa(aaaaaaaa),
///         aaaaaaaa(aaaaaaaaaaaaaaaaaaaaaaaaa) {
///     return 0;
///   }
///
bool ConstructorInitializerAllOnOneLineOrOnePerLine; clang-format on
/ The number of characters to use for indentation of constructor / initializer lists as well as inheritance lists. unsigned ConstructorInitializerIndentWidth;
/ Indent width for line continuations. /
///    ContinuationIndentWidth: 2
///
///    int i =         //  VeryVeryVeryVeryVeryLongComment
///      longFunction(// Again a long comment
///        arg);
///
unsigned ContinuationIndentWidth;
/ If true, format braced lists as best suited for C++11 braced / lists. / / Important differences: / - No spaces inside the braced list. / - No line break before the closing brace. / - Indentation with the continuation indent, not with the block indent. / / Fundamentally, C++11 braced lists are formatted exactly like function / calls would be formatted in their place. If the braced list follows a name / (e.g. a type or variable name), clang-format formats as if the {} were / the parentheses of a function call with that name. If there is no name, / a zero-length name is assumed. /
///    true:                                  false:
///    vector<int> x{1, 2, 3, 4};     vs.     vector<int> x{ 1, 2, 3, 4 };
///    vector<T> x{{}, {}, {}, {}};           vector<T> x{ {}, {}, {}, {} };
///    f(MyMap[{composite, key}]);            f(MyMap[{ composite, key }]);
///    new int[3]{1, 2, 3};                   new int[3]{ 1, 2, 3 };
///
bool Cpp11BracedListStyle;
/ Analyze the formatted file for the most used line ending (\r\n / or \n). UseCRLF is only used as a fallback if none can be derived. bool DeriveLineEnding;
/ If true, analyze the formatted file for the most common / alignment of & and *. / Pointer and reference alignment styles are going to be updated according / to the preferences found in the file. / PointerAlignment is then used only as fallback. bool DerivePointerAlignment;
/ Disables formatting completely. bool DisableFormat;
/ Different styles for empty line before access modifiers. enum EmptyLineBeforeAccessModifierStyle : unsigned char { / Remove all empty lines before access modifiers. /
///   struct foo {
///   private:
///     int i;
///   protected:
///     int j;
///     /* comment */
///   public:
///     foo() {}
///   private:
///   protected:
///   };
///
ELBAMS_Never, / Keep existing empty lines before access modifiers. ELBAMS_Leave, / Add empty line only when access modifier starts a new logical block. / Logical block is a group of one or more member fields or functions. /
///   struct foo {
///   private:
///     int i;
///
///   protected:
///     int j;
///     /* comment */
///   public:
///     foo() {}
///
///   private:
///   protected:
///   };
///
ELBAMS_LogicalBlock, / Always add empty line before access modifiers unless access modifier / is at the start of struct or class definition. /
///   struct foo {
///   private:
///     int i;
///
///   protected:
///     int j;
///     /* comment */
///
///   public:
///     foo() {}
///
///   private:
///
///   protected:
///   };
///
ELBAMS_Always, };
/ Defines in which cases to put empty line before access modifiers. EmptyLineBeforeAccessModifierStyle EmptyLineBeforeAccessModifier;
/ If true, clang-format detects whether function calls and / definitions are formatted with one parameter per line. / / Each call can be bin-packed, one-per-line or inconclusive. If it is / inconclusive, e.g. completely on one line, but a decision needs to be / made, clang-format analyzes whether there are other bin-packed cases in / the input file and act accordingly. / / NOTE: This is an experimental flag, that might go away or be renamed. Do / not use this in config files, etc. Use at your own risk. bool ExperimentalAutoDetectBinPacking;
/ If true, clang-format adds missing namespace end comments and / fixes invalid existing ones. /
///    true:                                  false:
///    namespace a {                  vs.     namespace a {
///    foo();                                 foo();
///    } // namespace a                       }
///
bool FixNamespaceComments;
/ A vector of macros that should be interpreted as foreach loops / instead of as function calls. / / These are expected to be macros of the form: /
///   FOREACH(<variable-declaration>, ...)
///     <loop-body>
///
/ / In the .clang-format configuration file, this can be configured like: /
///   ForEachMacros: ['RANGES_FOR', 'FOREACH']
///
/ / For example: BOOST_FOREACH. std::vector<std::string> ForEachMacros;
/ A vector of macros that should be interpreted as type declarations / instead of as function calls. / / These are expected to be macros of the form: /
///   STACK_OF(...)
///
/ / In the .clang-format configuration file, this can be configured like: /
///   TypenameMacros: ['STACK_OF', 'LIST']
///
/ / For example: OpenSSL STACK_OF, BSD LIST_ENTRY. std::vector<std::string> TypenameMacros;
/ A vector of macros that should be interpreted as complete / statements. / / Typical macros are expressions, and require a semi-colon to be / added; sometimes this is not the case, and this allows to make / clang-format aware of such cases. / / For example: Q_UNUSED std::vector<std::string> StatementMacros;
/ A vector of macros which are used to open namespace blocks. / / These are expected to be macros of the form: /
///   NAMESPACE(<namespace-name>, ...) {
///     <namespace-content>
///   }
///
/ / For example: TESTSUITE std::vector<std::string> NamespaceMacros;
/ A vector of macros which are whitespace-sensitive and should not / be touched. / / These are expected to be macros of the form: /
///   STRINGIZE(...)
///
/ / In the .clang-format configuration file, this can be configured like: /
///   WhitespaceSensitiveMacros: ['STRINGIZE', 'PP_STRINGIZE']
///
/ / For example: BOOST_PP_STRINGIZE std::vector<std::string> WhitespaceSensitiveMacros;
tooling::IncludeStyle IncludeStyle;
/ Indent case labels one level from the switch statement. / / When false, use the same indentation level as for the switch / statement. Switch statement body is always indented one level more than / case labels (except the first block following the case label, which / itself indents the code - unless IndentCaseBlocks is enabled). /
///    false:                                 true:
///    switch (fool) {                vs.     switch (fool) {
///    case 1:                                  case 1:
///      bar();                                   bar();
///      break;                                   break;
///    default:                                 default:
///      plop();                                  plop();
///    }                                      }
///
bool IndentCaseLabels;
/ Indent case label blocks one level from the case label. / / When false, the block following the case label uses the same / indentation level as for the case label, treating the case label the same / as an if-statement. / When true, the block gets indented as a scope block. /
///    false:                                 true:
///    switch (fool) {                vs.     switch (fool) {
///    case 1: {                              case 1:
///      bar();                                 {
///    } break;                                   bar();
///    default: {                               }
///      plop();                                break;
///    }                                      default:
///    }                                        {
///                                               plop();
///                                             }
///                                           }
///
bool IndentCaseBlocks;
/ Indent goto labels. / / When false, goto labels are flushed left. /
///    true:                                  false:
///    int f() {                      vs.     int f() {
///      if (foo()) {                           if (foo()) {
///      label1:                              label1:
///        bar();                                 bar();
///      }                                      }
///    label2:                                label2:
///      return 1;                              return 1;
///    }                                      }
///
bool IndentGotoLabels;
/ Options for indenting preprocessor directives. enum PPDirectiveIndentStyle : unsigned char { / Does not indent any directives. /
///    #if FOO
///    #if BAR
///    #include <foo>
///    #endif
///    #endif
///
PPDIS_None, / Indents directives after the hash. /
///    #if FOO
///    #  if BAR
///    #    include <foo>
///    #  endif
///    #endif
///
PPDIS_AfterHash, / Indents directives before the hash. /
///    #if FOO
///      #if BAR
///        #include <foo>
///      #endif
///    #endif
///
PPDIS_BeforeHash };
/ The preprocessor directive indenting style to use. PPDirectiveIndentStyle IndentPPDirectives;
/ Indents extern blocks enum IndentExternBlockStyle : unsigned char { / Backwards compatible with AfterExternBlock's indenting. /
///    IndentExternBlock: AfterExternBlock
///    BraceWrapping.AfterExternBlock: true
///    extern "C"
///    {
///        void foo();
///    }
///
/ /
///    IndentExternBlock: AfterExternBlock
///    BraceWrapping.AfterExternBlock: false
///    extern "C" {
///    void foo();
///    }
///
IEBS_AfterExternBlock, / Does not indent extern blocks. /
///     extern "C" {
///     void foo();
///     }
///
IEBS_NoIndent, / Indents extern blocks. /
///     extern "C" {
///       void foo();
///     }
///
IEBS_Indent, };
/ IndentExternBlockStyle is the type of indenting of extern blocks. IndentExternBlockStyle IndentExternBlock;
/ Indent the requires clause in a template /
///    true:
///    template <typename It>
///      requires Iterator<It>
///    void sort(It begin, It end) {
///      //....
///    }
///
///    false:
///    template <typename It>
///    requires Iterator<It>
///    void sort(It begin, It end) {
///      //....
///    }
///
bool IndentRequires;
/ The number of columns to use for indentation. /
///    IndentWidth: 3
///
///    void f() {
///       someFunction();
///       if (true, false) {
///          f();
///       }
///    }
///
unsigned IndentWidth;
/ Indent if a function definition or declaration is wrapped after the / type. /
///    true:
///    LoooooooooooooooooooooooooooooooooooooooongReturnType
///        LoooooooooooooooooooooooooooooooongFunctionDeclaration();
///
///    false:
///    LoooooooooooooooooooooooooooooooooooooooongReturnType
///    LoooooooooooooooooooooooooooooooongFunctionDeclaration();
///
bool IndentWrappedFunctionNames;
/ A vector of prefixes ordered by the desired groups for Java imports. / / One group's prefix can be a subset of another - the longest prefix is / always matched. Within a group, the imports are ordered lexicographically. / Static imports are grouped separately and follow the same group rules. / By default, static imports are placed before non-static imports, / but this behavior is changed by another option, / SortJavaStaticImport. / / In the .clang-format configuration file, this can be configured like / in the following yaml example. This will result in imports being / formatted as in the Java example below. /
///   JavaImportGroups: ['com.example', 'com', 'org']
///
/ /
///    import static com.example.function1;
///
///    import static com.test.function2;
///
///    import static org.example.function3;
///
///    import com.example.ClassA;
///    import com.example.Test;
///    import com.example.a.ClassB;
///
///    import com.test.ClassC;
///
///    import org.example.ClassD;
///
std::vector<std::string> JavaImportGroups;
/ Quotation styles for JavaScript strings. Does not affect template / strings. enum JavaScriptQuoteStyle : unsigned char { / Leave string quotes as they are. /
///    string1 = "foo";
///    string2 = 'bar';
///
JSQS_Leave, / Always use single quotes. /
///    string1 = 'foo';
///    string2 = 'bar';
///
JSQS_Single, / Always use double quotes. /
///    string1 = "foo";
///    string2 = "bar";
///
JSQS_Double };
/ The JavaScriptQuoteStyle to use for JavaScript strings. JavaScriptQuoteStyle JavaScriptQuotes;
clang-format off / Whether to wrap JavaScript import/export statements. /
///    true:
///    import {
///        VeryLongImportsAreAnnoying,
///        VeryLongImportsAreAnnoying,
///        VeryLongImportsAreAnnoying,
///    } from 'some/module.js'
///
///    false:
///    import {VeryLongImportsAreAnnoying, VeryLongImportsAreAnnoying, VeryLongImportsAreAnnoying,} from "some/module.js"
///
bool JavaScriptWrapImports; clang-format on
/ If true, the empty line at the start of blocks is kept. /
///    true:                                  false:
///    if (foo) {                     vs.     if (foo) {
///                                             bar();
///      bar();                               }
///    }
///
bool KeepEmptyLinesAtTheStartOfBlocks;
/ Supported languages. / / When stored in a configuration file, specifies the language, that the / configuration targets. When passed to the reformat() function, enables / syntax features specific to the language. enum LanguageKind : unsigned char { / Do not use. LK_None, / Should be used for C, C++. LK_Cpp, / Should be used for C#. LK_CSharp, / Should be used for Java. LK_Java, / Should be used for JavaScript. LK_JavaScript, / Should be used for Objective-C, Objective-C++. LK_ObjC, / Should be used for Protocol Buffers / (https://developers.google.com/protocol-buffers/). LK_Proto, / Should be used for TableGen code. LK_TableGen, / Should be used for Protocol Buffer messages in text format / (https://developers.google.com/protocol-buffers/). LK_TextProto }; bool isCpp() const { return Language == LK_Cpp || Language == LK_ObjC; } bool isCSharp() const { return Language == LK_CSharp; }
/ Language, this format style is targeted at. LanguageKind Language;
/ A regular expression matching macros that start a block. /
///    # With:
///    MacroBlockBegin: "^NS_MAP_BEGIN|\
///    NS_TABLE_HEAD$"
///    MacroBlockEnd: "^\
///    NS_MAP_END|\
///    NS_TABLE_.*_END$"
///
///    NS_MAP_BEGIN
///      foo();
///    NS_MAP_END
///
///    NS_TABLE_HEAD
///      bar();
///    NS_TABLE_FOO_END
///
///    # Without:
///    NS_MAP_BEGIN
///    foo();
///    NS_MAP_END
///
///    NS_TABLE_HEAD
///    bar();
///    NS_TABLE_FOO_END
///
std::string MacroBlockBegin;
/ A regular expression matching macros that end a block. std::string MacroBlockEnd;
/ The maximum number of consecutive empty lines to keep. /
///    MaxEmptyLinesToKeep: 1         vs.     MaxEmptyLinesToKeep: 0
///    int f() {                              int f() {
///      int = 1;                                 int i = 1;
///                                               i = foo();
///      i = foo();                               return i;
///                                           }
///      return i;
///    }
///
unsigned MaxEmptyLinesToKeep;
/ Different ways to indent namespace contents. enum NamespaceIndentationKind : unsigned char { / Don't indent in namespaces. /
///    namespace out {
///    int i;
///    namespace in {
///    int i;
///    }
///    }
///
NI_None, / Indent only in inner namespaces (nested in other namespaces). /
///    namespace out {
///    int i;
///    namespace in {
///      int i;
///    }
///    }
///
NI_Inner, / Indent in all namespaces. /
///    namespace out {
///      int i;
///      namespace in {
///        int i;
///      }
///    }
///
NI_All };
/ The indentation used for namespaces. NamespaceIndentationKind NamespaceIndentation;
/ Controls bin-packing Objective-C protocol conformance list / items into as few lines as possible when they go over ColumnLimit. / / If Auto (the default), delegates to the value in / BinPackParameters. If that is true, bin-packs Objective-C / protocol conformance list items into as few lines as possible / whenever they go over ColumnLimit. / / If Always, always bin-packs Objective-C protocol conformance / list items into as few lines as possible whenever they go over / ColumnLimit. / / If Never, lays out Objective-C protocol conformance list items / onto individual lines whenever they go over ColumnLimit. / /
///    Always (or Auto, if BinPackParameters=true):
///    @interface ccccccccccccc () <
///        ccccccccccccc, ccccccccccccc,
///        ccccccccccccc, ccccccccccccc> {
///    }
///
///    Never (or Auto, if BinPackParameters=false):
///    @interface ddddddddddddd () <
///        ddddddddddddd,
///        ddddddddddddd,
///        ddddddddddddd,
///        ddddddddddddd> {
///    }
///
BinPackStyle ObjCBinPackProtocolList;
/ The number of characters to use for indentation of ObjC blocks. /
///    ObjCBlockIndentWidth: 4
///
///    [operation setCompletionBlock:^{
///        [self onOperationDone];
///    }];
///
unsigned ObjCBlockIndentWidth;
/ Add a space after @property in Objective-C, i.e. use / @property (readonly) instead of @property(readonly). bool ObjCSpaceAfterProperty;
/ Break parameters list into lines when there is nested block / parameters in a function call. /
///   false:
///    - (void)_aMethod
///    {
///        [self.test1 t:self w:self callback:^(typeof(self) self, NSNumber
///        *u, NSNumber *v) {
///            u = c;
///        }]
///    }
///    true:
///    - (void)_aMethod
///    {
///       [self.test1 t:self
///                    w:self
///           callback:^(typeof(self) self, NSNumber *u, NSNumber *v) {
///                u = c;
///            }]
///    }
///
bool ObjCBreakBeforeNestedBlockParam;
/ Add a space in front of an Objective-C protocol list, i.e. use / Foo <Protocol> instead of Foo<Protocol>. bool ObjCSpaceBeforeProtocolList;
/ The penalty for breaking around an assignment operator. unsigned PenaltyBreakAssignment;
/ The penalty for breaking a function call after call(. unsigned PenaltyBreakBeforeFirstCallParameter;
/ The penalty for each line break introduced inside a comment. unsigned PenaltyBreakComment;
/ The penalty for breaking before the first <<. unsigned PenaltyBreakFirstLessLess;
/ The penalty for each line break introduced inside a string literal. unsigned PenaltyBreakString;
/ The penalty for breaking after template declaration. unsigned PenaltyBreakTemplateDeclaration;
/ The penalty for each character outside of the column limit. unsigned PenaltyExcessCharacter;
/ Penalty for putting the return type of a function onto its own / line. unsigned PenaltyReturnTypeOnItsOwnLine;
/ Penalty for each character of whitespace indentation / (counted relative to leading non-whitespace column). unsigned PenaltyIndentedWhitespace;
/ The & and * alignment style. enum PointerAlignmentStyle : unsigned char { / Align pointer to the left. /
///   int* a;
///
PAS_Left, / Align pointer to the right. /
///   int *a;
///
PAS_Right, / Align pointer in the middle. /
///   int * a;
///
PAS_Middle };
/ Pointer and reference alignment style. PointerAlignmentStyle PointerAlignment;
/ See documentation of RawStringFormats. struct RawStringFormat { / The language of this raw string. LanguageKind Language; / A list of raw string delimiters that match this language. std::vector<std::string> Delimiters; / A list of enclosing function names that match this language. std::vector<std::string> EnclosingFunctions; / The canonical delimiter for this language. std::string CanonicalDelimiter; / The style name on which this raw string format is based on. / If not specified, the raw string format is based on the style that this / format is based on. std::string BasedOnStyle; bool operator==(const RawStringFormat &Other) const { return Language == Other.Language && Delimiters == Other.Delimiters && EnclosingFunctions == Other.EnclosingFunctions && CanonicalDelimiter == Other.CanonicalDelimiter && BasedOnStyle == Other.BasedOnStyle; } };
/ Defines hints for detecting supported languages code blocks in raw / strings. / / A raw string with a matching delimiter or a matching enclosing function / name will be reformatted assuming the specified language based on the / style for that language defined in the .clang-format file. If no style has / been defined in the .clang-format file for the specific language, a / predefined style given by 'BasedOnStyle' is used. If 'BasedOnStyle' is not / found, the formatting is based on llvm style. A matching delimiter takes / precedence over a matching enclosing function name for determining the / language of the raw string contents. / / If a canonical delimiter is specified, occurrences of other delimiters for / the same language will be updated to the canonical if possible. / / There should be at most one specification per language and each delimiter / and enclosing function should not occur in multiple specifications. / / To configure this in the .clang-format file, use: /
///   RawStringFormats:
///     - Language: TextProto
///         Delimiters:
///           - 'pb'
///           - 'proto'
///         EnclosingFunctions:
///           - 'PARSE_TEXT_PROTO'
///         BasedOnStyle: google
///     - Language: Cpp
///         Delimiters:
///           - 'cc'
///           - 'cpp'
///         BasedOnStyle: llvm
///         CanonicalDelimiter: 'cc'
///
std::vector<RawStringFormat> RawStringFormats;
clang-format off / If true, clang-format will attempt to re-flow comments. /
///    false:
///    // veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongComment with plenty of information
///    /* second veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongComment with plenty of information */
///
///    true:
///    // veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongComment with plenty of
///    // information
///    /* second veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongComment with plenty of
///     * information */
///
bool ReflowComments; clang-format on
/ If true, clang-format will sort #includes. /
///    false:                                 true:
///    #include "b.h"                 vs.     #include "a.h"
///    #include "a.h"                         #include "b.h"
///
bool SortIncludes;
/ Position for Java Static imports. enum SortJavaStaticImportOptions : unsigned char { / Static imports are placed before non-static imports. /
///   import static org.example.function1;
///
///   import org.example.ClassA;
///
SJSIO_Before, / Static imports are placed after non-static imports. /
///   import org.example.ClassA;
///
///   import static org.example.function1;
///
SJSIO_After, };
/ When sorting Java imports, by default static imports are placed before / non-static imports. If JavaStaticImportAfterImport is After, / static imports are placed after non-static imports. SortJavaStaticImportOptions SortJavaStaticImport;
/ If true, clang-format will sort using declarations. / / The order of using declarations is defined as follows: / Split the strings by "::" and discard any initial empty strings. The last / element of each list is a non-namespace name; all others are namespace / names. Sort the lists of names lexicographically, where the sort order of / individual names is that all non-namespace names come before all namespace / names, and within those groups, names are in case-insensitive / lexicographic order. /
///    false:                                 true:
///    using std::cout;               vs.     using std::cin;
///    using std::cin;                        using std::cout;
///
bool SortUsingDeclarations;
/ If true, a space is inserted after C style casts. /
///    true:                                  false:
///    (int) i;                       vs.     (int)i;
///
bool SpaceAfterCStyleCast;
/ If true, a space is inserted after the logical not operator (!). /
///    true:                                  false:
///    ! someExpression();            vs.     !someExpression();
///
bool SpaceAfterLogicalNot;
/ If true, a space will be inserted after the 'template' keyword. /
///    true:                                  false:
///    template <int> void foo();     vs.     template<int> void foo();
///
bool SpaceAfterTemplateKeyword;
/ Different ways to put a space before opening parentheses. enum SpaceAroundPointerQualifiersStyle : unsigned char { / Don't ensure spaces around pointer qualifiers and use PointerAlignment / instead. /
///    PointerAlignment: Left                 PointerAlignment: Right
///    void* const* x = NULL;         vs.     void *const *x = NULL;
///
SAPQ_Default, / Ensure that there is a space before pointer qualifiers. /
///    PointerAlignment: Left                 PointerAlignment: Right
///    void* const* x = NULL;         vs.     void * const *x = NULL;
///
SAPQ_Before, / Ensure that there is a space after pointer qualifiers. /
///    PointerAlignment: Left                 PointerAlignment: Right
///    void* const * x = NULL;         vs.     void *const *x = NULL;
///
SAPQ_After, / Ensure that there is a space both before and after pointer qualifiers. /
///    PointerAlignment: Left                 PointerAlignment: Right
///    void* const * x = NULL;         vs.     void * const *x = NULL;
///
SAPQ_Both, };
/ Defines in which cases to put a space before or after pointer qualifiers SpaceAroundPointerQualifiersStyle SpaceAroundPointerQualifiers;
/ If false, spaces will be removed before assignment operators. /
///    true:                                  false:
///    int a = 5;                     vs.     int a= 5;
///    a += 42;                               a+= 42;
///
bool SpaceBeforeAssignmentOperators;
/ If false, spaces will be removed before case colon. /
///   true:                                   false
///   switch (x) {                    vs.     switch (x) {
///     case 1 : break;                         case 1: break;
///   }                                       }
///
bool SpaceBeforeCaseColon;
/ If true, a space will be inserted before a C++11 braced list / used to initialize an object (after the preceding identifier or type). /
///    true:                                  false:
///    Foo foo { bar };               vs.     Foo foo{ bar };
///    Foo {};                                Foo{};
///    vector<int> { 1, 2, 3 };               vector<int>{ 1, 2, 3 };
///    new int[3] { 1, 2, 3 };                new int[3]{ 1, 2, 3 };
///
bool SpaceBeforeCpp11BracedList;
/ If false, spaces will be removed before constructor initializer / colon. /
///    true:                                  false:
///    Foo::Foo() : a(a) {}                   Foo::Foo(): a(a) {}
///
bool SpaceBeforeCtorInitializerColon;
/ If false, spaces will be removed before inheritance colon. /
///    true:                                  false:
///    class Foo : Bar {}             vs.     class Foo: Bar {}
///
bool SpaceBeforeInheritanceColon;
/ Different ways to put a space before opening parentheses. enum SpaceBeforeParensOptions : unsigned char { / Never put a space before opening parentheses. /
///    void f() {
///      if(true) {
///        f();
///      }
///    }
///
SBPO_Never, / Put a space before opening parentheses only after control statement / keywords (for/if/while...). /
///    void f() {
///      if (true) {
///        f();
///      }
///    }
///
SBPO_ControlStatements, / Same as SBPO_ControlStatements except this option doesn't apply to / ForEach macros. This is useful in projects where ForEach macros are / treated as function calls instead of control statements. /
///    void f() {
///      Q_FOREACH(...) {
///        f();
///      }
///    }
///
SBPO_ControlStatementsExceptForEachMacros, / Put a space before opening parentheses only if the parentheses are not / empty i.e. '()' /
///   void() {
///     if (true) {
///       f();
///       g (x, y, z);
///     }
///   }
///
SBPO_NonEmptyParentheses, / Always put a space before opening parentheses, except when it's / prohibited by the syntax rules (in function-like macro definitions) or / when determined by other style rules (after unary operators, opening / parentheses, etc.) /
///    void f () {
///      if (true) {
///        f ();
///      }
///    }
///
SBPO_Always };
/ Defines in which cases to put a space before opening parentheses. SpaceBeforeParensOptions SpaceBeforeParens;
/ If false, spaces will be removed before range-based for loop / colon. /
///    true:                                  false:
///    for (auto v : values) {}       vs.     for(auto v: values) {}
///
bool SpaceBeforeRangeBasedForLoopColon;
/ If true, spaces will be inserted into {}. /
///    true:                                false:
///    void f() { }                   vs.   void f() {}
///    while (true) { }                     while (true) {}
///
bool SpaceInEmptyBlock;
/ If true, spaces may be inserted into (). /
///    true:                                false:
///    void f() {                    vs.   void f() {
///      int x[] = {foo(), bar()};          int x[] = {foo(), bar()};
///      if (true) {                          if (true) {
///        f();                                f();
///      }                                    }
///    }                                    }
///
bool SpaceInEmptyParentheses;
/ The number of spaces before trailing line comments / (// - comments). / / This does not affect trailing block comments (/* - comments) as / those commonly have different usage patterns and a number of special / cases. /
///    SpacesBeforeTrailingComments: 3
///    void f() {
///      if (true) {   // foo1
///        f();        // bar
///      }             // foo
///    }
///
unsigned SpacesBeforeTrailingComments;
/ If true, spaces will be inserted after < and before > / in template argument lists. /
///    true:                                  false:
///    static_cast< int >(arg);       vs.     static_cast<int>(arg);
///    std::function< void(int) > fct;        std::function<void(int)> fct;
///
bool SpacesInAngles;
/ If true, spaces will be inserted around if/for/switch/while / conditions. /
///    true:                                  false:
///    if (a)  { ... }              vs.     if (a) { ... }
///    while (i < 5)  { ... }               while (i < 5) { ... }
///
bool SpacesInConditionalStatement;
/ If true, spaces are inserted inside container literals (e.g. / ObjC and Javascript array and dict literals). /
///    true:                                  false:
///    var arr = [ 1, 2, 3 ];         vs.     var arr = [1, 2, 3];
///    f({a : 1, b : 2, c : 3});              f({a: 1, b: 2, c: 3});
///
bool SpacesInContainerLiterals;
/ If true, spaces may be inserted into C style casts. /
///    true:                                  false:
///    x = (int32)y                 vs.     x = (int32)y
///
bool SpacesInCStyleCastParentheses;
/ If true, spaces will be inserted after (and before). /
///    true:                                  false:
///    t f(Deleted &) & = delete;   vs.     t f(Deleted &) & = delete;
///
bool SpacesInParentheses;
/ If true, spaces will be inserted after [ and before ]. / Lambdas without arguments or unspecified size array declarations will not / be affected. /
///    true:                                  false:
///    int a[ 5 ];                    vs.     int a[5];
///    std::unique_ptr<int[]> foo() {} // Won't be affected
///
bool SpacesInSquareBrackets;
/ If true, spaces will be before [. / Lambdas will not be affected. Only the first [ will get a space added. /
///    true:                                  false:
///    int a [5];                    vs.      int a[5];
///    int a [5][5];                 vs.      int a[5][5];
///
bool SpaceBeforeSquareBrackets;
/ Styles for adding spacing around : in bitfield definitions. enum BitFieldColonSpacingStyle : unsigned char { / Add one space on each side of the : /
///   unsigned bf : 2;
///
BFCS_Both, / Add no space around the : (except when needed for / AlignConsecutiveBitFields). /
///   unsigned bf:2;
///
BFCS_None, / Add space before the : only /
///   unsigned bf :2;
///
BFCS_Before, / Add space after the : only (space may be added before if / needed for AlignConsecutiveBitFields). /
///   unsigned bf: 2;
///
BFCS_After }; / The BitFieldColonSpacingStyle to use for bitfields. BitFieldColonSpacingStyle BitFieldColonSpacing;
/ Supported language standards for parsing and formatting C++ constructs. /
///    Latest:                                vector<set<int>>
///    c++03                          vs.     vector<set<int> >
///
/ / The correct way to spell a specific language version is e.g. c++11. / The historical aliases Cpp03 and Cpp11 are deprecated. enum LanguageStandard : unsigned char { / Parse and format as C++03. / Cpp03 is a deprecated alias for c++03 LS_Cpp03, // c++03 / Parse and format as C++11. LS_Cpp11, // c++11 / Parse and format as C++14. LS_Cpp14, // c++14 / Parse and format as C++17. LS_Cpp17, // c++17 / Parse and format as C++20. LS_Cpp20, // c++20 / Parse and format using the latest supported language version. / Cpp11 is a deprecated alias for Latest LS_Latest, / Automatic detection based on the input. LS_Auto, };
/ Parse and format C++ constructs compatible with this standard. /
///    c++03:                                 latest:
///    vector<set<int> > x;           vs.     vector<set<int>> x;
///
LanguageStandard Standard;
/ Macros which are ignored in front of a statement, as if they were an / attribute. So that they are not parsed as identifier, for example for Qts / emit. /
///   AlignConsecutiveDeclarations: true
///   StatementAttributeLikeMacros: []
///   unsigned char data = 'x';
///   emit          signal(data); // This is parsed as variable declaration.
///
///   AlignConsecutiveDeclarations: true
///   StatementAttributeLikeMacros: [emit]
///   unsigned char data = 'x';
///   emit signal(data); // Now it's fine again.
///
std::vector<std::string> StatementAttributeLikeMacros;
/ The number of columns used for tab stops. unsigned TabWidth;
/ Different ways to use tab in formatting. enum UseTabStyle : unsigned char { / Never use tab. UT_Never, / Use tabs only for indentation. UT_ForIndentation, / Fill all leading whitespace with tabs, and use spaces for alignment that / appears within a line (e.g. consecutive assignments and declarations). UT_ForContinuationAndIndentation, / Use tabs for line continuation and indentation, and spaces for / alignment. UT_AlignWithSpaces, / Use tabs whenever we need to fill whitespace that spans at least from / one tab stop to the next one. UT_Always };
/ Use \r\n instead of \n for line breaks. / Also used as fallback if DeriveLineEnding is true. bool UseCRLF;
/ The way to use tab characters in the resulting file. UseTabStyle UseTab;
bool operator==(const FormatStyle &R) const { return AccessModifierOffset == R.AccessModifierOffset && AlignAfterOpenBracket == R.AlignAfterOpenBracket && AlignConsecutiveAssignments == R.AlignConsecutiveAssignments && AlignConsecutiveBitFields == R.AlignConsecutiveBitFields && AlignConsecutiveDeclarations == R.AlignConsecutiveDeclarations && AlignConsecutiveMacros == R.AlignConsecutiveMacros && AlignEscapedNewlines == R.AlignEscapedNewlines && AlignOperands == R.AlignOperands && AlignTrailingComments == R.AlignTrailingComments && AllowAllArgumentsOnNextLine == R.AllowAllArgumentsOnNextLine && AllowAllConstructorInitializersOnNextLine == R.AllowAllConstructorInitializersOnNextLine && AllowAllParametersOfDeclarationOnNextLine == R.AllowAllParametersOfDeclarationOnNextLine && AllowShortEnumsOnASingleLine == R.AllowShortEnumsOnASingleLine && AllowShortBlocksOnASingleLine == R.AllowShortBlocksOnASingleLine && AllowShortCaseLabelsOnASingleLine == R.AllowShortCaseLabelsOnASingleLine && AllowShortFunctionsOnASingleLine == R.AllowShortFunctionsOnASingleLine && AllowShortIfStatementsOnASingleLine == R.AllowShortIfStatementsOnASingleLine && AllowShortLambdasOnASingleLine == R.AllowShortLambdasOnASingleLine && AllowShortLoopsOnASingleLine == R.AllowShortLoopsOnASingleLine && AlwaysBreakAfterReturnType == R.AlwaysBreakAfterReturnType && AlwaysBreakBeforeMultilineStrings == R.AlwaysBreakBeforeMultilineStrings && AlwaysBreakTemplateDeclarations == R.AlwaysBreakTemplateDeclarations && AttributeMacros == R.AttributeMacros && BinPackArguments == R.BinPackArguments && BinPackParameters == R.BinPackParameters && BreakBeforeBinaryOperators == R.BreakBeforeBinaryOperators && BreakBeforeBraces == R.BreakBeforeBraces && BreakBeforeConceptDeclarations == R.BreakBeforeConceptDeclarations && BreakBeforeTernaryOperators == R.BreakBeforeTernaryOperators && BreakConstructorInitializers == R.BreakConstructorInitializers && CompactNamespaces == R.CompactNamespaces && BreakAfterJavaFieldAnnotations == R.BreakAfterJavaFieldAnnotations && BreakStringLiterals == R.BreakStringLiterals && ColumnLimit == R.ColumnLimit && CommentPragmas == R.CommentPragmas && BreakInheritanceList == R.BreakInheritanceList && ConstructorInitializerAllOnOneLineOrOnePerLine == R.ConstructorInitializerAllOnOneLineOrOnePerLine && ConstructorInitializerIndentWidth == R.ConstructorInitializerIndentWidth && ContinuationIndentWidth == R.ContinuationIndentWidth && Cpp11BracedListStyle == R.Cpp11BracedListStyle && DeriveLineEnding == R.DeriveLineEnding && DerivePointerAlignment == R.DerivePointerAlignment && DisableFormat == R.DisableFormat && EmptyLineBeforeAccessModifier == R.EmptyLineBeforeAccessModifier && ExperimentalAutoDetectBinPacking == R.ExperimentalAutoDetectBinPacking && FixNamespaceComments == R.FixNamespaceComments && ForEachMacros == R.ForEachMacros && IncludeStyle.IncludeBlocks == R.IncludeStyle.IncludeBlocks && IncludeStyle.IncludeCategories == R.IncludeStyle.IncludeCategories && IncludeStyle.IncludeIsMainRegex == R.IncludeStyle.IncludeIsMainRegex && IncludeStyle.IncludeIsMainSourceRegex == R.IncludeStyle.IncludeIsMainSourceRegex && IndentCaseLabels == R.IndentCaseLabels && IndentCaseBlocks == R.IndentCaseBlocks && IndentGotoLabels == R.IndentGotoLabels && IndentPPDirectives == R.IndentPPDirectives && IndentExternBlock == R.IndentExternBlock && IndentRequires == R.IndentRequires && IndentWidth == R.IndentWidth && Language == R.Language && IndentWrappedFunctionNames == R.IndentWrappedFunctionNames && JavaImportGroups == R.JavaImportGroups && JavaScriptQuotes == R.JavaScriptQuotes && JavaScriptWrapImports == R.JavaScriptWrapImports && KeepEmptyLinesAtTheStartOfBlocks == R.KeepEmptyLinesAtTheStartOfBlocks && MacroBlockBegin == R.MacroBlockBegin && MacroBlockEnd == R.MacroBlockEnd && MaxEmptyLinesToKeep == R.MaxEmptyLinesToKeep && NamespaceIndentation == R.NamespaceIndentation && NamespaceMacros == R.NamespaceMacros && ObjCBinPackProtocolList == R.ObjCBinPackProtocolList && ObjCBlockIndentWidth == R.ObjCBlockIndentWidth && ObjCBreakBeforeNestedBlockParam == R.ObjCBreakBeforeNestedBlockParam && ObjCSpaceAfterProperty == R.ObjCSpaceAfterProperty && ObjCSpaceBeforeProtocolList == R.ObjCSpaceBeforeProtocolList && PenaltyBreakAssignment == R.PenaltyBreakAssignment && PenaltyBreakBeforeFirstCallParameter == R.PenaltyBreakBeforeFirstCallParameter && PenaltyBreakComment == R.PenaltyBreakComment && PenaltyBreakFirstLessLess == R.PenaltyBreakFirstLessLess && PenaltyBreakString == R.PenaltyBreakString && PenaltyExcessCharacter == R.PenaltyExcessCharacter && PenaltyReturnTypeOnItsOwnLine == R.PenaltyReturnTypeOnItsOwnLine && PenaltyBreakTemplateDeclaration == R.PenaltyBreakTemplateDeclaration && PointerAlignment == R.PointerAlignment && RawStringFormats == R.RawStringFormats && SortJavaStaticImport == R.SortJavaStaticImport && SpaceAfterCStyleCast == R.SpaceAfterCStyleCast && SpaceAfterLogicalNot == R.SpaceAfterLogicalNot && SpaceAfterTemplateKeyword == R.SpaceAfterTemplateKeyword && SpaceBeforeAssignmentOperators == R.SpaceBeforeAssignmentOperators && SpaceBeforeCaseColon == R.SpaceBeforeCaseColon && SpaceBeforeCpp11BracedList == R.SpaceBeforeCpp11BracedList && SpaceBeforeCtorInitializerColon == R.SpaceBeforeCtorInitializerColon && SpaceBeforeInheritanceColon == R.SpaceBeforeInheritanceColon && SpaceBeforeParens == R.SpaceBeforeParens && SpaceAroundPointerQualifiers == R.SpaceAroundPointerQualifiers && SpaceBeforeRangeBasedForLoopColon == R.SpaceBeforeRangeBasedForLoopColon && SpaceInEmptyBlock == R.SpaceInEmptyBlock && SpaceInEmptyParentheses == R.SpaceInEmptyParentheses && SpacesBeforeTrailingComments == R.SpacesBeforeTrailingComments && SpacesInAngles == R.SpacesInAngles && SpacesInConditionalStatement == R.SpacesInConditionalStatement && SpacesInContainerLiterals == R.SpacesInContainerLiterals && SpacesInCStyleCastParentheses == R.SpacesInCStyleCastParentheses && SpacesInParentheses == R.SpacesInParentheses && SpacesInSquareBrackets == R.SpacesInSquareBrackets && SpaceBeforeSquareBrackets == R.SpaceBeforeSquareBrackets && BitFieldColonSpacing == R.BitFieldColonSpacing && Standard == R.Standard && StatementAttributeLikeMacros == R.StatementAttributeLikeMacros && StatementMacros == R.StatementMacros && TabWidth == R.TabWidth && UseTab == R.UseTab && UseCRLF == R.UseCRLF && TypenameMacros == R.TypenameMacros; }
llvm::Optional<FormatStyle> GetLanguageStyle(LanguageKind Language) const;
Stores per-language styles. A FormatStyle instance inside has an empty StyleSet. A FormatStyle instance returned by the Get method has its StyleSet set to a copy of the originating StyleSet, effectively keeping the internal representation of that StyleSet alive.
The memory management and ownership reminds of a birds nest: chicks leaving the nest take photos of the nest with them. struct FormatStyleSet { typedef std::map<FormatStyle::LanguageKind, FormatStyle> MapType;
llvm::Optional<FormatStyle> Get(FormatStyle::LanguageKind Language) const;
Adds Style to this FormatStyleSet. Style must not have an associated FormatStyleSet. Style.Language should be different than LK_None. If this FormatStyleSet already contains an entry for Style.Language, that gets replaced with the passed Style. void Add(FormatStyle Style);
Clears this FormatStyleSet. void Clear();
private: std::shared_ptr<MapType> Styles; };
static FormatStyleSet BuildStyleSetFromConfiguration(const FormatStyle &MainStyle, const std::vector<FormatStyle> &ConfigurationStyles);
private: FormatStyleSet StyleSet;
friend std::error_code parseConfiguration(llvm::MemoryBufferRef Config, FormatStyle *Style, bool AllowUnknownOptions); };
/ Returns a format style complying with the LLVM coding standards: / http://llvm.org/docs/CodingStandards.html. FormatStyle getLLVMStyle(FormatStyle::LanguageKind Language = FormatStyle::LanguageKind::LK_Cpp);
/ Returns a format style complying with one of Google's style guides: / http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml. / http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml. / https://developers.google.com/protocol-buffers/docs/style. FormatStyle getGoogleStyle(FormatStyle::LanguageKind Language);
/ Returns a format style complying with Chromium's style guide: / http://www.chromium.org/developers/coding-style. FormatStyle getChromiumStyle(FormatStyle::LanguageKind Language);
/ Returns a format style complying with Mozilla's style guide: / https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style. FormatStyle getMozillaStyle();
/ Returns a format style complying with Webkit's style guide: / http://www.webkit.org/coding/coding-style.html FormatStyle getWebKitStyle();
/ Returns a format style complying with GNU Coding Standards: / http://www.gnu.org/prep/standards/standards.html FormatStyle getGNUStyle();
/ Returns a format style complying with Microsoft style guide: / https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017 FormatStyle getMicrosoftStyle(FormatStyle::LanguageKind Language);
/ Returns style indicating formatting should be not applied at all. FormatStyle getNoStyle();
/ Gets a predefined style for the specified language by name. / / Currently supported names: LLVM, Google, Chromium, Mozilla. Names are / compared case-insensitively. / / Returns true if the Style has been set. bool getPredefinedStyle(StringRef Name, FormatStyle::LanguageKind Language, FormatStyle *Style);
/ Parse configuration from YAML-formatted text. / / Style->Language is used to get the base style, if the BasedOnStyle / option is present. / / The FormatStyleSet of Style is reset. / / When BasedOnStyle is not present, options not present in the YAML / document, are retained in Style. / / If AllowUnknownOptions is true, no errors are emitted if unknown / format options are occured. std::error_code parseConfiguration(llvm::MemoryBufferRef Config, FormatStyle *Style, bool AllowUnknownOptions = false);
/ Like above but accepts an unnamed buffer. inline std::error_code parseConfiguration(StringRef Config, FormatStyle *Style, bool AllowUnknownOptions = false) { return parseConfiguration(llvm::MemoryBufferRef(Config, "YAML"), Style, AllowUnknownOptions); }
/ Gets configuration in a YAML string. std::string configurationAsText(const FormatStyle &Style);
/ Returns the replacements necessary to sort all #include blocks / that are affected by Ranges. tooling::Replacements sortIncludes(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName, unsigned *Cursor = nullptr);
/ Returns the replacements corresponding to applying and formatting / Replaces on success; otheriwse, return an llvm::Error carrying / llvm::StringError. llvm::Expected<tooling::Replacements> formatReplacements(StringRef Code, const tooling::Replacements &Replaces, const FormatStyle &Style);
/ Returns the replacements corresponding to applying Replaces and / cleaning up the code after that on success; otherwise, return an llvm::Error / carrying llvm::StringError. / This also supports inserting/deleting C++ #include directives: / - If a replacement has offset UINT_MAX, length 0, and a replacement text / that is an #include directive, this will insert the #include into the / correct block in the Code. / - If a replacement has offset UINT_MAX, length 1, and a replacement text / that is the name of the header to be removed, the header will be removed / from Code if it exists. / The include manipulation is done via tooling::HeaderInclude, see its / documentation for more details on how include insertion points are found and / what edits are produced. llvm::Expected<tooling::Replacements> cleanupAroundReplacements(StringRef Code, const tooling::Replacements &Replaces, const FormatStyle &Style);
/ Represents the status of a formatting attempt. struct FormattingAttemptStatus { / A value of false means that any of the affected ranges were not / formatted due to a non-recoverable syntax error. bool FormatComplete = true;
/ If FormatComplete is false, Line records a one-based / original line number at which a syntax error might have occurred. This is / based on a best-effort analysis and could be imprecise. unsigned Line = 0; };
/ Reformats the given Ranges in Code. / / Each range is extended on either end to its next bigger logic unit, i.e. / everything that might influence its formatting or might be influenced by its / formatting. / / Returns the Replacements necessary to make all Ranges comply with / Style. / / If Status is non-null, its value will be populated with the status of / this formatting attempt. See FormattingAttemptStatus. tooling::Replacements reformat(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName = "<stdin>", FormattingAttemptStatus *Status = nullptr);
/ Same as above, except if IncompleteFormat is non-null, its value / will be set to true if any of the affected ranges were not formatted due to / a non-recoverable syntax error. tooling::Replacements reformat(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName, bool *IncompleteFormat);
/ Clean up any erroneous/redundant code in the given Ranges in / Code. / / Returns the Replacements that clean up all Ranges in Code. tooling::Replacements cleanup(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName = "<stdin>");
/ Fix namespace end comments in the given Ranges in Code. / / Returns the Replacements that fix the namespace comments in all / Ranges in Code. tooling::Replacements fixNamespaceEndComments(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName = "<stdin>");
/ Sort consecutive using declarations in the given Ranges in / Code. / / Returns the Replacements that sort the using declarations in all / Ranges in Code. tooling::Replacements sortUsingDeclarations(const FormatStyle &Style, StringRef Code, ArrayRef<tooling::Range> Ranges, StringRef FileName = "<stdin>");
/ Returns the LangOpts that the formatter expects you to set. / /
Parameters
Style determines specific settings for lexing mode. LangOptions getFormattingLangOpts(const FormatStyle &Style = getLLVMStyle());
/ Description to be used for help text for a llvm::cl option for / specifying format style. The description is closely related to the operation / of getStyle(). extern const char *StyleOptionHelpDescription;
/ The suggested format style to use by default. This allows tools using / getStyle to have a consistent default style. / Different builds can modify the value to the preferred styles. extern const char *DefaultFormatStyle;
/ The suggested predefined style to use as the fallback style in getStyle. / Different builds can modify the value to the preferred styles. extern const char *DefaultFallbackStyle;
/ Construct a FormatStyle based on StyleName. / / StyleName can take several forms: / * "{<key>: <value>, ...}" - Set specic style parameters. / * "<style name>" - One of the style names supported by / getPredefinedStyle(). / * "file" - Load style configuration from a file called .clang-format / located in one of the parent directories of FileName or the current / directory if FileName is empty. / /
Parameters
[in] StyleName Style name to interpret according to the description / above. /
[in] FileName Path to start search for .clang-format if StyleName / == "file". /
[in] FallbackStyle The name of a predefined style used to fallback to / in case StyleName is "file" and no file can be found. /
[in] Code The actual code to be formatted. Used to determine the / language if the filename isn't sufficient. /
[in] FS The underlying file system, in which the file resides. By / default, the file system is the real file system. /
[in] AllowUnknownOptions If true, unknown format options only / emit a warning. If false, errors are emitted on unknown format / options. / /
Returns
FormatStyle as specified by StyleName. If StyleName is / "file" and no file is found, returns FallbackStyle. If no style could be / determined, returns an Error. llvm::Expected<FormatStyle> getStyle(StringRef StyleName, StringRef FileName, StringRef FallbackStyle, StringRef Code = "", llvm::vfs::FileSystem *FS = nullptr, bool AllowUnknownOptions = false);
Guesses the language from the FileName and Code to be formatted. Defaults to FormatStyle::LK_Cpp. FormatStyle::LanguageKind guessLanguage(StringRef FileName, StringRef Code);
Returns a string representation of Language.
Definition at line 3414 of file Format.h.
Referenced by getStyle(), and clang::format::TokenAnalyzer::TokenAnalyzer().
getLastLineEndColumn()
static unsigned clang::format::getLastLineEndColumn (StringRef Text, unsigned StartColumn, unsigned TabWidth, encoding::Encoding Encoding) static
Definition at line 1634 of file ContinuationIndenter.cpp.
References clang::format::encoding::columnWidthWithTabs(), and Text.
getLengthToMatchingParen()
static unsigned clang::format::getLengthToMatchingParen (const FormatToken & Tok, const std::vector< ParenState > & Stack) static
Definition at line 37 of file ContinuationIndenter.cpp.
References Tok.
Referenced by clang::format::ContinuationIndenter::mustBreak().
getLengthToNextOperator()
static unsigned clang::format::getLengthToNextOperator (const FormatToken & Tok) static
Definition at line 107 of file ContinuationIndenter.cpp.
References Tok.
Referenced by clang::format::ContinuationIndenter::mustBreak().
getLineCommentIndentPrefix()
static StringRef clang::format::getLineCommentIndentPrefix (StringRef Comment, const FormatStyle & Style) static
Definition at line 42 of file BreakableToken.cpp.
Referenced by clang::format::BreakableLineCommentSection::BreakableLineCommentSection().
getLLVMStyle()
FormatStyle clang::format::getLLVMStyle (FormatStyle::LanguageKind Language)
Definition at line 881 of file Format.cpp.
References clang::prec::Assignment, clang::tooling::IncludeStyle::IBS_Preserve, and clang::prec::Relational.
Referenced by getGNUStyle(), getGoogleStyle(), getMicrosoftStyle(), getMozillaStyle(), getNoStyle(), getPredefinedStyle(), getStyle(), getWebKitStyle(), guessLanguage(), and clang::format::RawStringFormatStyleManager::RawStringFormatStyleManager().
getMicrosoftStyle()
FormatStyle clang::format::getMicrosoftStyle (FormatStyle::LanguageKind Language)
Definition at line 1300 of file Format.cpp.
References getLLVMStyle().
Referenced by getPredefinedStyle().
getMozillaStyle()
FormatStyle clang::format::getMozillaStyle ()
Definition at line 1236 of file Format.cpp.
References getLLVMStyle().
Referenced by getPredefinedStyle().
getNamespaceToken() [1/2]
const FormatToken * clang::format::getNamespaceToken () const
Return the actual namespace token, if this token starts a namespace block.
Definition at line 685 of file FormatToken.h.
Referenced by clang::format::NamespaceEndCommentsFixer::analyze(), and getNamespaceTokenText().
getNamespaceToken() [2/2]
const FormatToken * clang::format::getNamespaceToken (const AnnotatedLine * Line, const SmallVectorImpl< AnnotatedLine * > & AnnotatedLines)
Definition at line 173 of file NamespaceEndCommentsFixer.cpp.
References clang::format::AnnotatedLine::Affected, clang::format::AnnotatedLine::InPPDirective, clang::format::FormatToken::is(), clang::format::UnwrappedLine::kInvalidIndex, clang::format::AnnotatedLine::MatchingOpeningBlockLineIndex, and clang::format::AnnotatedLine::startsWith().
getNamespaceTokenText()
StringRef clang::format::getNamespaceTokenText (const AnnotatedLine * Line, const SmallVectorImpl< AnnotatedLine * > & AnnotatedLines)
Definition at line 192 of file NamespaceEndCommentsFixer.cpp.
References getNamespaceToken(), and clang::format::FormatToken::TokenText.
Referenced by clang::format::NamespaceEndCommentsFixer::analyze().
getNextNonComment()
const FormatToken * clang::format::getNextNonComment () const
Returns the next token ignoring comments.
Definition at line 640 of file FormatToken.h.
References clang::Token::is(), clang::format::FormatToken::Next, and clang::format::FormatToken::Tok.
getNoStyle()
FormatStyle clang::format::getNoStyle ()
Definition at line 1330 of file Format.cpp.
References getLLVMStyle().
Referenced by getPredefinedStyle(), and getStyle().
getParseCategory()
const std::error_category & clang::format::getParseCategory ()
Definition at line 744 of file Format.cpp.
References clang::C.
Referenced by make_error_code().
getPredefinedStyle()
bool clang::format::getPredefinedStyle (StringRef Name, FormatStyle::LanguageKind Language, FormatStyle * Style)
Definition at line 1338 of file Format.cpp.
References getChromiumStyle(), getGNUStyle(), getGoogleStyle(), getLLVMStyle(), getMicrosoftStyle(), getMozillaStyle(), getNoStyle(), and getWebKitStyle().
Referenced by getStyle(), and clang::format::RawStringFormatStyleManager::RawStringFormatStyleManager().
getPreviousNonComment()
struct clang::format::FormatToken clang::format::getPreviousNonComment () const
Returns the previous token ignoring comments.
Definition at line 134 of file FormatToken.h.
getRawStringDelimiter()
static llvm::Optional< StringRef > clang::format::getRawStringDelimiter (StringRef TokenText) static
Definition at line 149 of file ContinuationIndenter.cpp.
References clang::None, and TokenText.
getStringSplit()
static BreakableToken::Split clang::format::getStringSplit (StringRef Text, unsigned UsedColumns, unsigned ColumnLimit, unsigned TabWidth, encoding::Encoding Encoding) static
Definition at line 171 of file BreakableToken.cpp.
References clang::format::encoding::columnWidthWithTabs(), clang::format::encoding::getCodePointNumBytes(), clang::format::encoding::getEscapeSequenceLength(), clang::isAlphanumeric(), IsBlank(), and Text.
Referenced by clang::format::BreakableStringLiteral::getSplit().
getStyle()
llvm::Expected< FormatStyle > clang::format::getStyle (StringRef StyleName, StringRef FileName, StringRef FallbackStyleName, StringRef Code, llvm::vfs::FileSystem * FS, bool AllowUnknownOptions)
Definition at line 2895 of file Format.cpp.
References getLanguageName(), getLLVMStyle(), getNoStyle(), getPredefinedStyle(), guessLanguage(), make_string_error(), parseConfiguration(), Text, and Unsuitable.
Referenced by clang::tooling::formatAndApplyAllReplacements().
getTokenTypeName()
const char * clang::format::getTokenTypeName (TokenType Type)
Determines the name of a token type.
Definition at line 24 of file FormatToken.cpp.
References LIST_TOKEN_TYPES, NUM_TOKEN_TYPES, TokNames, and Type.
getWebKitStyle()
FormatStyle clang::format::getWebKitStyle ()
Definition at line 1262 of file Format.cpp.
References getLLVMStyle().
Referenced by getPredefinedStyle().
guessLanguage()
FormatStyle::LanguageKind clang::format::guessLanguage (StringRef FileName, StringRef Code)
Definition at line 2873 of file Format.cpp.
References getLanguageByFileName(), and getLLVMStyle().
Referenced by getStyle().
hash_combine()
template<class T > static void clang::format::hash_combine (std::size_t & seed, const T & v) inline static
Definition at line 568 of file UnwrappedLineParser.cpp.
References v.
hasNestedBlockInlined()
static bool clang::format::hasNestedBlockInlined (const FormatToken * Previous, const FormatToken & Current, const FormatStyle & Style) static
Definition at line 1162 of file ContinuationIndenter.cpp.
References clang::format::FormatToken::is(), clang::format::FormatToken::isNot(), clang::format::FormatToken::ParameterCount, and Previous.
isAllmanBrace()
static bool clang::format::isAllmanBrace (const FormatToken & Tok) static
Definition at line 3459 of file TokenAnnotator.cpp.
References BK_Block, and Tok.
isAllmanBraceIncludedBreakableLambda()
static bool clang::format::isAllmanBraceIncludedBreakableLambda (const FormatToken & Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption) static
Definition at line 3500 of file TokenAnnotator.cpp.
References isAllmanLambdaBrace(), isItAInlineLambdaAllowed(), isItAnEmptyLambdaAllowed(), isOneChildWithoutMustBreakBefore(), and Tok.
isAllmanLambdaBrace()
static bool clang::format::isAllmanLambdaBrace (const FormatToken & Tok) static
Definition at line 3495 of file TokenAnnotator.cpp.
References BK_Block, and Tok.
Referenced by isAllmanBraceIncludedBreakableLambda().
IsBlank()
static bool clang::format::IsBlank (char C) static
Definition at line 29 of file BreakableToken.cpp.
References clang::C.
Referenced by getStringSplit().
isCppStructuredBinding()
bool clang::format::isCppStructuredBinding (const FormatStyle & Style) const
Returns whether the token is the left square bracket of a C++ structured binding declaration.
Definition at line 665 of file FormatToken.h.
References clang::format::FormatToken::isNot().
IsFunctionArgument()
static bool clang::format::IsFunctionArgument (const FormatToken & Tok) static
Definition at line 3465 of file TokenAnnotator.cpp.
References Tok.
Referenced by isItAInlineLambdaAllowed().
isFunctionDeclarationName()
static bool clang::format::isFunctionDeclarationName (const FormatToken & Current, const AnnotatedLine & Line) static
Definition at line 2355 of file TokenAnnotator.cpp.
References clang::format::FormatToken::is(), clang::format::FormatToken::isOneOf(), clang::format::AnnotatedLine::Last, clang::format::FormatToken::MatchingParen, clang::format::FormatToken::NestingLevel, clang::format::FormatToken::Next, Next, clang::format::FormatToken::Previous, and Tok.
Referenced by clang::format::TokenAnnotator::calculateFormattingInformation().
isGoogScope()
static bool clang::format::isGoogScope (const UnwrappedLine & Line) static
Definition at line 664 of file UnwrappedLineParser.cpp.
isIIFE()
static bool clang::format::isIIFE (const UnwrappedLine & Line, const AdditionalKeywords & Keywords) static
Definition at line 682 of file UnwrappedLineParser.cpp.
isItAInlineLambdaAllowed()
static bool clang::format::isItAInlineLambdaAllowed (const FormatToken & Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption) static
Definition at line 3477 of file TokenAnnotator.cpp.
References IsFunctionArgument(), and Tok.
Referenced by isAllmanBraceIncludedBreakableLambda().
isItAnEmptyLambdaAllowed()
static bool clang::format::isItAnEmptyLambdaAllowed (const FormatToken & Tok, FormatStyle::ShortLambdaStyle ShortLambdaOption) static
Definition at line 3471 of file TokenAnnotator.cpp.
References Tok.
Referenced by isAllmanBraceIncludedBreakableLambda().
isJSDeclOrStmt()
static bool clang::format::isJSDeclOrStmt (const AdditionalKeywords & Keywords, const FormatToken * FormatTok) static
Definition at line 977 of file UnwrappedLineParser.cpp.
References clang::format::FormatToken::isOneOf().
isLikelyXml()
bool clang::format::isLikelyXml (StringRef Code)
Definition at line 2524 of file Format.cpp.
Referenced by clang::format::internal::reformat(), and sortIncludes().
isMpegTS()
bool clang::format::isMpegTS (StringRef Code)
Definition at line 2517 of file Format.cpp.
Referenced by clang::format::internal::reformat(), and sortIncludes().
isOneChildWithoutMustBreakBefore()
static bool clang::format::isOneChildWithoutMustBreakBefore (const FormatToken & Tok) static
Definition at line 3484 of file TokenAnnotator.cpp.
References clang::format::FormatToken::Children, clang::format::FormatToken::MustBreakBefore, clang::format::FormatToken::Next, and Tok.
Referenced by isAllmanBraceIncludedBreakableLambda().
make_error_code()
std::error_code clang::format::make_error_code (ParseError e)
Definition at line 748 of file Format.cpp.
References getParseCategory().
Referenced by parseConfiguration().
make_string_error()
llvm::Error clang::format::make_string_error (const llvm::Twine & Message) inline
Definition at line 752 of file Format.cpp.
Referenced by getStyle().
maxNestingDepth()
static unsigned clang::format::maxNestingDepth (const AnnotatedLine & Line) static
Definition at line 2313 of file TokenAnnotator.cpp.
References clang::format::AnnotatedLine::First, clang::format::FormatToken::Next, clang::Result, and Tok.
Referenced by clang::format::TokenAnnotator::annotate().
mayReflowContent()
static bool clang::format::mayReflowContent (StringRef Content) static
Definition at line 336 of file BreakableToken.cpp.
References Blanks, and clang::isPunctuation().
Referenced by clang::format::BreakableBlockComment::mayReflow(), and clang::format::BreakableLineCommentSection::mayReflow().
mustBeJSIdent()
static bool clang::format::mustBeJSIdent (const AdditionalKeywords & Keywords, const FormatToken * FormatTok) static
Definition at line 953 of file UnwrappedLineParser.cpp.
References clang::Token::getIdentifierInfo(), clang::format::FormatToken::is(), clang::format::FormatToken::isOneOf(), and clang::format::FormatToken::Tok.
Referenced by mustBeJSIdentOrValue().
mustBeJSIdentOrValue()
static bool clang::format::mustBeJSIdentOrValue (const AdditionalKeywords & Keywords, const FormatToken * FormatTok) static
Definition at line 968 of file UnwrappedLineParser.cpp.
References clang::Token::isLiteral(), clang::format::FormatToken::isOneOf(), mustBeJSIdent(), and clang::format::FormatToken::Tok.
opensBlockOrBlockTypeList()
bool clang::format::opensBlockOrBlockTypeList (const FormatStyle & Style) const
Returns true if this tokens starts a block-type list, i.e. a list that should be indented with a block indent.
Definition at line 649 of file FormatToken.h.
References BK_BracedInit, clang::format::FormatToken::getBlockKind(), and clang::format::FormatToken::is().
opensProtoMessageField()
static bool clang::format::opensProtoMessageField (const FormatToken & LessTok, const FormatStyle & Style) static
Definition at line 136 of file ContinuationIndenter.cpp.
References clang::format::FormatToken::is(), clang::format::FormatToken::isNot(), clang::format::FormatToken::NestingLevel, and clang::format::FormatToken::Previous.
Referenced by clang::format::ContinuationIndenter::mustBreak().
operator<()
bool clang::format::operator< (const JsModuleReference & LHS, const JsModuleReference & RHS)
Definition at line 93 of file SortJavaScriptImports.cpp.
References clang::format::JsModuleReference::Category, clang::format::JsModuleReference::IsExport, clang::format::JsModuleReference::Prefix, clang::format::JsModuleReference::SIDE_EFFECT, and clang::format::JsModuleReference::URL.
parseConfiguration()
std::error_code clang::format::parseConfiguration (llvm::MemoryBufferRef Config, FormatStyle * Style, bool AllowUnknownOptions)
Definition at line 1364 of file Format.cpp.
References BinPackTrailingCommaConflict, Error, make_error_code(), Success, and Unsuitable.
Referenced by getStyle().
printDebugInfo()
static LLVM_ATTRIBUTE_UNUSED void clang::format::printDebugInfo (const UnwrappedLine & Line, StringRef Prefix = "") static
Definition at line 2928 of file UnwrappedLineParser.cpp.
References clang::format::AnnotatedLine::FirstStartColumn, clang::format::AnnotatedLine::InPPDirective, clang::format::AnnotatedLine::Level, Node, and printDebugInfo().
Referenced by printDebugInfo().
processReplacements()
template<typename T > static llvm::Expected< tooling::Replacements > clang::format::processReplacements (T ProcessFunc, StringRef Code, const tooling::Replacements & Replaces, const FormatStyle & Style) static
Definition at line 2547 of file Format.cpp.
References clang::tooling::Replacements::begin(), clang::tooling::Replacements::empty(), clang::tooling::Replacements::getAffectedRanges(), and clang::tooling::Replacements::merge().
Referenced by cleanupAroundReplacements(), and formatReplacements().
reformat() [1/2]
tooling::Replacements clang::format::reformat (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, bool * IncompleteFormat)
Definition at line 2785 of file Format.cpp.
References reformat(), and clang::Result.
reformat() [2/2]
tooling::Replacements clang::format::reformat (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, FormattingAttemptStatus * Status)
Definition at line 2765 of file Format.cpp.
References clang::format::internal::reformat().
Referenced by clang::tooling::applyAtomicChanges(), formatReplacements(), and reformat().
replaceCRLF()
std::string clang::format::replaceCRLF (const std::string & Code)
Definition at line 2168 of file Format.cpp.
Referenced by sortCppIncludes(), and sortJavaImports().
ShouldBreakBeforeBrace()
static bool clang::format::ShouldBreakBeforeBrace (const FormatStyle & Style, const FormatToken & InitialToken) static
Definition at line 700 of file UnwrappedLineParser.cpp.
References clang::format::FormatToken::is(), and clang::format::FormatToken::isOneOf().
shouldIndentWrappedSelectorName()
static bool clang::format::shouldIndentWrappedSelectorName (const FormatStyle & Style, LineType LineType) static
Definition at line 30 of file ContinuationIndenter.cpp.
References LT_ObjCMethodDecl.
sortCppIncludes() [1/2]
static void clang::format::sortCppIncludes (const FormatStyle & Style, const SmallVectorImpl< IncludeDirective > & Includes, ArrayRef< tooling::Range > Ranges, StringRef FileName, StringRef Code, tooling::Replacements & Replaces, unsigned * Cursor) static
Definition at line 2196 of file Format.cpp.
References clang::tooling::Replacements::add(), affectsRange(), Filename, FindCursorIndex(), clang::tooling::IncludeStyle::IBS_Preserve, clang::tooling::IncludeStyle::IBS_Regroup, and replaceCRLF().
Referenced by sortCppIncludes(), and sortIncludes().
sortCppIncludes() [2/2]
tooling::Replacements clang::format::sortCppIncludes (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, tooling::Replacements & Replaces, unsigned * Cursor)
Definition at line 2283 of file Format.cpp.
References Category, clang::tooling::IncludeCategoryManager::getIncludePriority(), clang::tooling::IncludeCategoryManager::getSortIncludePriority(), clang::tooling::IncludeStyle::IBS_Merge, clang::tooling::IncludeStyle::IBS_Regroup, and sortCppIncludes().
sortIncludes()
tooling::Replacements clang::format::sortIncludes (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, unsigned * Cursor)
Definition at line 2526 of file Format.cpp.
References isLikelyXml(), isMpegTS(), sortCppIncludes(), sortJavaImports(), and sortJavaScriptImports().
Referenced by clang::tooling::applyAtomicChanges(), and formatReplacements().
sortJavaImports() [1/2]
static void clang::format::sortJavaImports (const FormatStyle & Style, const SmallVectorImpl< JavaImportDirective > & Imports, ArrayRef< tooling::Range > Ranges, StringRef FileName, StringRef Code, tooling::Replacements & Replaces) static
Definition at line 2385 of file Format.cpp.
References clang::tooling::Replacements::add(), affectsRange(), AssociatedCommentLines, findJavaImportGroup(), Identifier, IsStatic, and replaceCRLF().
Referenced by sortIncludes(), and sortJavaImports().
sortJavaImports() [2/2]
tooling::Replacements clang::format::sortJavaImports (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName, tooling::Replacements & Replaces)
Definition at line 2464 of file Format.cpp.
References AssociatedCommentLines, Identifier, IsStatic, and sortJavaImports().
sortJavaScriptImports()
tooling::Replacements clang::format::sortJavaScriptImports (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
Definition at line 440 of file SortJavaScriptImports.cpp.
References clang::format::TokenAnalyzer::process().
Referenced by sortIncludes().
sortUsingDeclarations()
tooling::Replacements clang::format::sortUsingDeclarations (const FormatStyle & Style, StringRef Code, ArrayRef< tooling::Range > Ranges, StringRef FileName)
Definition at line 2804 of file Format.cpp.
References clang::format::TokenAnalyzer::process().
startsNextParameter()
static bool clang::format::startsNextParameter (const FormatToken & Current, const FormatStyle & Style) static
Definition at line 120 of file ContinuationIndenter.cpp.
References clang::format::FormatToken::is(), clang::format::FormatToken::isNot(), clang::format::FormatToken::Previous, and Previous.
Referenced by clang::format::ContinuationIndenter::mustBreak().
startsSegmentOfBuilderTypeCall()
static bool clang::format::startsSegmentOfBuilderTypeCall (const FormatToken & Tok) static
Definition at line 115 of file ContinuationIndenter.cpp.
References Tok.
Referenced by clang::format::ContinuationIndenter::mustBreak().
switchesFormatting()
bool clang::format::switchesFormatting (const FormatToken & Token)
Checks if Token switches formatting, like /* clang-format off *‍/.
Token must be a comment.
Definition at line 219 of file BreakableToken.cpp.
References clang::Token::is().
Referenced by clang::format::BreakableBlockComment::mayReflow(), and clang::format::BreakableLineCommentSection::mayReflow().
tokenCanStartNewLine()
static bool clang::format::tokenCanStartNewLine (const FormatToken & Tok) static
Definition at line 927 of file UnwrappedLineParser.cpp.
References Tok.
Variable Documentation
Blanks
StringRef clang::format::Blanks = " \t\v\f\r" static constexpr
Definition at line 28 of file BreakableToken.cpp.
Referenced by clang::format::BreakableBlockComment::adaptStartOfLine(), clang::format::BreakableLineCommentSection::BreakableLineCommentSection(), getCommentSplit(), clang::format::BreakableBlockComment::getContentIndent(), clang::format::BreakableBlockComment::getReflowSplit(), clang::format::BreakableLineCommentSection::getReflowSplit(), clang::format::BreakableBlockComment::getSplitAfterLastLine(), clang::format::BreakableBlockComment::introducesBreakBeforeToken(), clang::format::BreakableBlockComment::mayReflow(), mayReflowContent(), and clang::format::BreakableBlockComment::reflow().
DefaultFallbackStyle
const char* clang::format::DefaultFallbackStyle = "LLVM"
Definition at line 2893 of file Format.cpp.
DefaultFormatStyle
const char* clang::format::DefaultFormatStyle = "file"
Definition at line 2891 of file Format.cpp.
StyleOptionHelpDescription
const char* clang::format::StyleOptionHelpDescription
Initial value:
=
    "Coding style, currently supports:\n"
    "  LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.\n"
    "Use -style=file to load style configuration from\n"
    ".clang-format file located in one of the parent\n"
    "directories of the source file (or current\n"
    "directory for stdin).\n"
    "Use -style=\"{key: value, ...}\" to set specific\n"
    "parameters, e.g.:\n"
    "  -style=\"{BasedOnStyle: llvm, IndentWidth: 8}\""
Definition at line 2839 of file Format.cpp.