clang: clang::diff Namespace Reference
clang::diff Namespace Reference
Classes
class ASTDiff
struct ComparisonOptions
struct Node
Represents a Clang AST node, alongside some additional information.
struct NodeId
Within a tree, this identifies a node by its preorder offset.
struct SNodeId
Identifies a node in a subtree by its postorder offset, starting at 1.
class Subtree
class SyntaxTree
SyntaxTree objects represent subtrees of the AST.
class ZhangShashaMatcher
Implementation of Zhang and Shasha's Algorithm for tree edit distance.
Typedefs
using DynTypedNode = DynTypedNode
Enumerations
enum ChangeKind {
None , Delete , Update , Insert ,
Move , UpdateMove
}
Functions
static bool isSpecializedNodeExcluded (const Decl *D)
static bool isSpecializedNodeExcluded (const Stmt *S)
static bool isSpecializedNodeExcluded (CXXCtorInitializer *I)
template<class T >
static bool isNodeExcluded (const SourceManager &SrcMgr, T *N)
static std::vector< NodeId > getSubtreePostorder (const SyntaxTree::Impl &Tree, NodeId Root)
static std::vector< NodeId > getSubtreeBfs (const SyntaxTree::Impl &Tree, NodeId Root)
static const DeclContext * getEnclosingDeclContext (ASTContext &AST, const Stmt *S)
static std::string getInitializerValue (const CXXCtorInitializer *Init, const PrintingPolicy &TypePP)
Typedef Documentation
DynTypedNode
using clang::diff::DynTypedNode = DynTypedNode
Definition at line 18 of file ASTDiffInternal.h.
Enumeration Type Documentation
ChangeKind
enum clang::diff::ChangeKind
Enumerator
None
Delete
Update
Insert
Move
UpdateMove
Definition at line 27 of file ASTDiff.h.
Function Documentation
getEnclosingDeclContext()
static const DeclContext * clang::diff::getEnclosingDeclContext (ASTContext & AST, const Stmt * S) static
Definition at line 384 of file ASTDiff.cpp.
References clang::Decl::getDeclContext(), clang::ASTContext::getParents(), and P.
Referenced by clang::diff::SyntaxTree::Impl::getStmtValue().
getInitializerValue()
static std::string clang::diff::getInitializerValue (const CXXCtorInitializer * Init, const PrintingPolicy & TypePP) static
Definition at line 398 of file ASTDiff.cpp.
References clang::QualType::getAsString().
Referenced by clang::diff::SyntaxTree::Impl::getNodeValue().
getSubtreeBfs()
static std::vector< NodeId > clang::diff::getSubtreeBfs (const SyntaxTree::Impl & Tree, NodeId Root) static
Definition at line 294 of file ASTDiff.cpp.
References Tree.
getSubtreePostorder()
static std::vector< NodeId > clang::diff::getSubtreePostorder (const SyntaxTree::Impl & Tree, NodeId Root) static
Definition at line 281 of file ASTDiff.cpp.
References Id, N, and Tree.
Referenced by clang::diff::Subtree::Subtree().
isNodeExcluded()
template<class T > static bool clang::diff::isNodeExcluded (const SourceManager & SrcMgr, T * N) static
Definition at line 173 of file ASTDiff.cpp.
References clang::SourceManager::getSpellingLoc(), clang::SourceManager::isInMainFile(), isSpecializedNodeExcluded(), clang::SourceLocation::isValid(), and N.
isSpecializedNodeExcluded() [1/3]
static bool clang::diff::isSpecializedNodeExcluded (const Decl * D) static
Definition at line 166 of file ASTDiff.cpp.
References clang::Decl::isImplicit().
Referenced by isNodeExcluded().
isSpecializedNodeExcluded() [2/3]
static bool clang::diff::isSpecializedNodeExcluded (const Stmt * S) static
Definition at line 167 of file ASTDiff.cpp.
isSpecializedNodeExcluded() [3/3]
static bool clang::diff::isSpecializedNodeExcluded (CXXCtorInitializer * I) static
Definition at line 168 of file ASTDiff.cpp.
References clang::CXXCtorInitializer::isWritten().