clang: clang::ento::iterator Namespace Reference
clang::ento::iterator Namespace Reference
Classes
struct ContainerData
class ContainerMap
struct IteratorPosition
class IteratorRegionMap
class IteratorSymbolMap
Typedefs
using IteratorSymbolMapTy
using IteratorRegionMapTy
using ContainerMapTy
Functions
bool isIteratorType (const QualType &Type)
bool isIterator (const CXXRecordDecl *CRD)
bool isComparisonOperator (OverloadedOperatorKind OK)
bool isInsertCall (const FunctionDecl *Func)
bool isEmplaceCall (const FunctionDecl *Func)
bool isEraseCall (const FunctionDecl *Func)
bool isEraseAfterCall (const FunctionDecl *Func)
bool isAccessOperator (OverloadedOperatorKind OK)
bool isAccessOperator (UnaryOperatorKind OK)
bool isAccessOperator (BinaryOperatorKind OK)
bool isDereferenceOperator (OverloadedOperatorKind OK)
bool isDereferenceOperator (UnaryOperatorKind OK)
bool isDereferenceOperator (BinaryOperatorKind OK)
bool isIncrementOperator (OverloadedOperatorKind OK)
bool isIncrementOperator (UnaryOperatorKind OK)
bool isDecrementOperator (OverloadedOperatorKind OK)
bool isDecrementOperator (UnaryOperatorKind OK)
bool isRandomIncrOrDecrOperator (OverloadedOperatorKind OK)
bool isRandomIncrOrDecrOperator (BinaryOperatorKind OK)
const ContainerData * getContainerData (ProgramStateRef State, const MemRegion *Cont)
const IteratorPosition * getIteratorPosition (ProgramStateRef State, const SVal &Val)
ProgramStateRef setIteratorPosition (ProgramStateRef State, const SVal &Val, const IteratorPosition &Pos)
ProgramStateRef createIteratorPosition (ProgramStateRef State, const SVal &Val, const MemRegion *Cont, const Stmt *S, const LocationContext *LCtx, unsigned blockCount)
ProgramStateRef advancePosition (ProgramStateRef State, const SVal &Iter, OverloadedOperatorKind Op, const SVal &Distance)
ProgramStateRef assumeNoOverflow (ProgramStateRef State, SymbolRef Sym, long Scale)
bool compare (ProgramStateRef State, SymbolRef Sym1, SymbolRef Sym2, BinaryOperator::Opcode Opc)
bool compare (ProgramStateRef State, NonLoc NL1, NonLoc NL2, BinaryOperator::Opcode Opc)
Typedef Documentation
ContainerMapTy
using clang::ento::iterator::ContainerMapTy
Initial value:
  CLANG_ENTO_PROGRAMSTATE_MAP(const MemRegion *, ContainerData)
Definition at line 122 of file Iterator.h.
IteratorRegionMapTy
using clang::ento::iterator::IteratorRegionMapTy
Initial value:
  CLANG_ENTO_PROGRAMSTATE_MAP(const MemRegion *, IteratorPosition)
Definition at line 120 of file Iterator.h.
IteratorSymbolMapTy
using clang::ento::iterator::IteratorSymbolMapTy
Initial value:
  CLANG_ENTO_PROGRAMSTATE_MAP(SymbolRef, IteratorPosition)
Definition at line 118 of file Iterator.h.
Function Documentation
advancePosition()
ProgramStateRef clang::ento::iterator::advancePosition (ProgramStateRef State, const SVal & Iter, OverloadedOperatorKind Op, const SVal & Distance)
Definition at line 224 of file Iterator.cpp.
References clang::ento::SVal::getAs(), getIteratorPosition(), clang::ento::nonloc::ConcreteInt::getValue(), and setIteratorPosition().
assumeNoOverflow()
ProgramStateRef clang::ento::iterator::assumeNoOverflow (ProgramStateRef State, SymbolRef Sym, long Scale)
Definition at line 265 of file Iterator.cpp.
References clang::ento::SValBuilder::evalBinOpNN(), clang::ento::BasicValueFactory::getAPSIntType(), clang::ento::SVal::getAs(), clang::ento::SValBuilder::getBasicValueFactory(), clang::ento::SValBuilder::getConditionType(), clang::ento::APSIntType::getMaxValue(), clang::ento::SValBuilder::getStateManager(), clang::ento::ProgramStateManager::getSValBuilder(), clang::ento::SymExpr::getType(), clang::ento::APSIntType::getValue(), and State.
Referenced by createIteratorPosition().
compare() [1/2]
bool clang::ento::iterator::compare (ProgramStateRef State, NonLoc NL1, NonLoc NL2, BinaryOperator::Opcode Opc)
Definition at line 304 of file Iterator.cpp.
compare() [2/2]
bool clang::ento::iterator::compare (ProgramStateRef State, SymbolRef Sym1, SymbolRef Sym2, BinaryOperator::Opcode Opc)
Definition at line 299 of file Iterator.cpp.
References compare().
Referenced by compare().
createIteratorPosition()
ProgramStateRef clang::ento::iterator::createIteratorPosition (ProgramStateRef State, const SVal & Val, const MemRegion * Cont, const Stmt * S, const LocationContext * LCtx, unsigned blockCount)
Definition at line 210 of file Iterator.cpp.
References assumeNoOverflow(), clang::ento::iterator::IteratorPosition::getPosition(), and setIteratorPosition().
getContainerData()
const ContainerData * clang::ento::iterator::getContainerData (ProgramStateRef State, const MemRegion * Cont)
Definition at line 179 of file Iterator.cpp.
getIteratorPosition()
const IteratorPosition * clang::ento::iterator::getIteratorPosition (ProgramStateRef State, const SVal & Val)
Definition at line 184 of file Iterator.cpp.
References clang::ento::SVal::getAs(), clang::ento::SVal::getAsRegion(), and clang::ento::SVal::getAsSymbol().
Referenced by advancePosition().
isAccessOperator() [1/3]
bool clang::ento::iterator::isAccessOperator (BinaryOperatorKind OK)
Definition at line 136 of file Iterator.cpp.
References isDereferenceOperator(), and isRandomIncrOrDecrOperator().
isAccessOperator() [2/3]
bool clang::ento::iterator::isAccessOperator (OverloadedOperatorKind OK)
Definition at line 126 of file Iterator.cpp.
References isDecrementOperator(), isDereferenceOperator(), isIncrementOperator(), and isRandomIncrOrDecrOperator().
isAccessOperator() [3/3]
bool clang::ento::iterator::isAccessOperator (UnaryOperatorKind OK)
Definition at line 131 of file Iterator.cpp.
References isDecrementOperator(), isDereferenceOperator(), and isIncrementOperator().
isComparisonOperator()
bool clang::ento::iterator::isComparisonOperator (OverloadedOperatorKind OK)
Definition at line 71 of file Iterator.cpp.
isDecrementOperator() [1/2]
bool clang::ento::iterator::isDecrementOperator (OverloadedOperatorKind OK)
Definition at line 161 of file Iterator.cpp.
Referenced by isAccessOperator(), and isAccessOperator().
isDecrementOperator() [2/2]
bool clang::ento::iterator::isDecrementOperator (UnaryOperatorKind OK)
Definition at line 165 of file Iterator.cpp.
isDereferenceOperator() [1/3]
bool clang::ento::iterator::isDereferenceOperator (BinaryOperatorKind OK)
Definition at line 149 of file Iterator.cpp.
isDereferenceOperator() [2/3]
bool clang::ento::iterator::isDereferenceOperator (OverloadedOperatorKind OK)
Definition at line 140 of file Iterator.cpp.
Referenced by isAccessOperator(), isAccessOperator(), and isAccessOperator().
isDereferenceOperator() [3/3]
bool clang::ento::iterator::isDereferenceOperator (UnaryOperatorKind OK)
Definition at line 145 of file Iterator.cpp.
isEmplaceCall()
bool clang::ento::iterator::isEmplaceCall (const FunctionDecl * Func)
Definition at line 87 of file Iterator.cpp.
References clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), and isIteratorType().
isEraseAfterCall()
bool clang::ento::iterator::isEraseAfterCall (const FunctionDecl * Func)
Definition at line 112 of file Iterator.cpp.
References clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), and isIteratorType().
isEraseCall()
bool clang::ento::iterator::isEraseCall (const FunctionDecl * Func)
Definition at line 98 of file Iterator.cpp.
References clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), and isIteratorType().
isIncrementOperator() [1/2]
bool clang::ento::iterator::isIncrementOperator (OverloadedOperatorKind OK)
Definition at line 153 of file Iterator.cpp.
Referenced by isAccessOperator(), and isAccessOperator().
isIncrementOperator() [2/2]
bool clang::ento::iterator::isIncrementOperator (UnaryOperatorKind OK)
Definition at line 157 of file Iterator.cpp.
isInsertCall()
bool clang::ento::iterator::isInsertCall (const FunctionDecl * Func)
Definition at line 76 of file Iterator.cpp.
References clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ValueDecl::getType(), and isIteratorType().
isIterator()
bool clang::ento::iterator::isIterator (const CXXRecordDecl * CRD)
Definition at line 27 of file Iterator.cpp.
References clang::AS_public, clang::NamedDecl::getName(), and clang::CXXRecordDecl::methods().
Referenced by isIteratorType().
isIteratorType()
bool clang::ento::iterator::isIteratorType (const QualType & Type)
Definition at line 19 of file Iterator.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Type::getUnqualifiedDesugaredType(), isIterator(), and clang::Type::isPointerType().
Referenced by isEmplaceCall(), isEraseAfterCall(), isEraseCall(), and isInsertCall().
isRandomIncrOrDecrOperator() [1/2]
bool clang::ento::iterator::isRandomIncrOrDecrOperator (BinaryOperatorKind OK)
Definition at line 174 of file Iterator.cpp.
isRandomIncrOrDecrOperator() [2/2]
bool clang::ento::iterator::isRandomIncrOrDecrOperator (OverloadedOperatorKind OK)
Definition at line 169 of file Iterator.cpp.
Referenced by isAccessOperator(), and isAccessOperator().
setIteratorPosition()
ProgramStateRef clang::ento::iterator::setIteratorPosition (ProgramStateRef State, const SVal & Val, const IteratorPosition & Pos)
Definition at line 197 of file Iterator.cpp.
References clang::ento::SVal::getAs(), clang::ento::SVal::getAsRegion(), and clang::ento::SVal::getAsSymbol().
Referenced by advancePosition(), and createIteratorPosition().