clang: clang::sema Namespace Reference
clang::sema Namespace Reference
Classes
class AccessedEntity
A declaration being accessed, together with information about how it was accessed.
class AnalysisBasedWarnings
class BlockScopeInfo
Retains information about a block that is currently being parsed.
class Capture
class CapturedRegionScopeInfo
Retains information about a captured region.
class CapturingScopeInfo
class CompoundScopeInfo
Contains information about the compound statement currently being parsed.
class DelayedDiagnostic
A diagnostic message which has been conditionally emitted pending the complete parsing of the current declaration.
class DelayedDiagnosticPool
A collection of diagnostics which were delayed.
class FunctionScopeInfo
Retains information about a function, method, or block that is currently being parsed.
class LambdaScopeInfo
class PossiblyUnreachableDiag
class SemaPPCallbacks
class TemplateDeductionInfo
Provides information about an attempted template argument deduction, whose success or failure was described by a TemplateDeductionResult value.
Functions
Attr * instantiateTemplateAttribute (const Attr *At, ASTContext &C, Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs)
Attr * instantiateTemplateAttributeForDecl (const Attr *At, ASTContext &C, Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs)
Function Documentation
instantiateTemplateAttribute()
Attr * clang::sema::instantiateTemplateAttribute (const Attr * At, ASTContext & C, Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs)
Referenced by clang::Sema::InstantiateAttrs(), and clang::Sema::InstantiateClass().
instantiateTemplateAttributeForDecl()
Attr * clang::sema::instantiateTemplateAttributeForDecl (const Attr * At, ASTContext & C, Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs)
Referenced by clang::Sema::InstantiateAttrsForDecl().