clang: clang Namespace Reference
clang Namespace Reference
Dataflow Directional Tag Classes.
Namespaces
namespace AArch64
AArch64 builtins.
namespace AMDGPU
AMDGPU builtins.
namespace analyze_format_string
Common components of both fprintf and fscanf format strings.
namespace analyze_os_log
namespace analyze_printf
Pieces specific to fprintf format strings.
namespace analyze_scanf
Pieces specific to fscanf format strings.
namespace api_notes
namespace arcmt
namespace ARM
ARM builtins.
namespace ast_matchers
namespace attr
namespace attrvisitor
namespace BPF
BPF builtins.
namespace Builtin
namespace charinfo
namespace CodeGen
namespace codegenoptions
namespace comments
namespace concepts
namespace consumed
namespace cross_tu
namespace data_collection
namespace dataflow
namespace declvisitor
namespace detail
namespace diag
namespace diff
namespace driver
namespace edit
namespace ento
namespace FileMgr
namespace format
namespace frontend
namespace Hexagon
Hexagon builtins.
namespace html
namespace index
namespace interp
namespace Le64
Le64 builtins.
namespace markup
namespace minimize_source_to_dependency_directives
namespace Mips
MIPS builtins.
namespace NEON
namespace NVPTX
NVPTX builtins.
namespace ObjCPropertyAttribute
ObjCPropertyAttribute::Kind - list of property attributes.
namespace PPC
PPC builtins.
namespace prec
PrecedenceLevels - These are precedences for the binary/ternary operators in the C99 grammar.
namespace reachable_code
namespace sema
namespace serialization
namespace serialized_diags
namespace SrcMgr
Public enums and private classes that are part of the SourceManager implementation.
namespace SVE
namespace syntax
namespace SystemZ
SystemZ builtins.
namespace targets
namespace templateargumentvisitor
namespace threadSafety
namespace tok
namespace tooling
namespace transformer
namespace TypeName
namespace VE
VE builtins.
namespace WebAssembly
WebAssembly builtins.
namespace X86
X86 builtins.
namespace XCore
XCore builtins.
namespace XRayInstrKind
Classes
class AArch64VectorPcsAttr
class AbiTagAttr
class AbstractConditionalOperator
AbstractConditionalOperator - An abstract base class for ConditionalOperator and BinaryConditionalOperator.
class AccessSpecDecl
Represents an access specifier followed by colon ':'.
class AcquireCapabilityAttr
class AcquiredAfterAttr
class AcquiredBeforeAttr
class AcquireHandleAttr
class ActionResult
ActionResult - This structure is used while parsing/acting on expressions, stmts, etc.
class ActionResult< PtrTy, true >
struct AddFlagValue
struct AdditionalKeywords
Encapsulates keywords that are context sensitive or for languages not properly supported by Clang's lexer.
class AddressSpaceAttr
class AddrLabelExpr
AddrLabelExpr - The GNU address of label extension, representing &&label.
struct AdjustedLocInfo
class AdjustedType
Represents a type which was implicitly adjusted by the semantic engine for arbitrary reasons.
class AdjustedTypeLoc
class ADLResult
A class for storing results from argument-dependent lookup.
class AliasAttr
class AlignedAttr
class AlignMac68kAttr
class AlignNaturalAttr
class AlignValueAttr
class AllocAlignAttr
class AllocSizeAttr
class AlwaysDestroyAttr
class AlwaysInlineAttr
struct AmbiguousConversionSequence
Represents an ambiguous user-defined conversion sequence.
class AMDGPUFlatWorkGroupSizeAttr
class AMDGPUNumSGPRAttr
class AMDGPUNumVGPRAttr
class AMDGPUWavesPerEUAttr
class AnalysisDeclContext
AnalysisDeclContext contains the context data for the function, method or block under analysis.
class AnalysisDeclContextManager
class AnalyzerNoReturnAttr
class AnalyzerOptions
Stores options for the analyzer from the command line.
class AnnotateAttr
class AnyX86InterruptAttr
class AnyX86NoCallerSavedRegistersAttr
class AnyX86NoCfCheckAttr
class APFloatStorage
class APIntStorage
class APNumericStorage
Used by IntegerLiteral/FloatingLiteral to store the numeric without leaking memory.
class APValue
APValue - This class implements a discriminated union of [uninitialized] [APSInt] [APFloat], [Complex APSInt] [Complex APFloat], [Expr + Offset], [Vector: N * APValue], [Array: N * APValue].
class ArcWeakrefUnavailableAttr
class ArgumentConstructionContext
class ArgumentWithTypeTagAttr
class ArmBuiltinAliasAttr
class ARMInterruptAttr
class ArmMveStrictPolymorphismAttr
class ArrayInitIndexExpr
Represents the index of the current element of an array being initialized by an ArrayInitLoopExpr.
class ArrayInitLoopExpr
Represents a loop initializing the elements of an array.
struct ArrayLocInfo
class ArraySubscriptExpr
ArraySubscriptExpr - [C99 6.5.2.1] Array Subscripting.
class ArrayType
Represents an array type, per C99 6.7.5.2 - Array Declarators.
class ArrayTypeLoc
Wrapper for source info for arrays.
class ArrayTypeTraitExpr
An Embarcadero array type trait, as used in the implementation of __array_rank and __array_extent.
class ArtificialAttr
class AsmLabelAttr
class AsmStmt
AsmStmt is the base class for GCCAsmStmt and MSAsmStmt.
class AssertCapabilityAttr
class AssertExclusiveLockAttr
class AssertSharedLockAttr
class AssumeAlignedAttr
class AssumedTemplateStorage
A structure for storing the information associated with a name that has been assumed to be a template name (despite finding no TemplateDecls).
class AssumptionAttr
struct ASTConstraintSatisfaction
The result of a constraint satisfaction check, containing the necessary information to diagnose an unsatisfied constraint.
class ASTConsumer
ASTConsumer - This is an abstract interface that should be implemented by clients that read ASTs.
class ASTContext
Holds long-lived AST nodes (such as types and decls) that can be referred to throughout the semantic analysis of a file.
class ASTDeclListAction
class ASTDeclReader
class ASTDeclWriter
class ASTDeserializationListener
class ASTDumpAction
class ASTDumper
struct ASTFileSignature
The signature of a module, which is a hash of the AST content.
class ASTFrontendAction
Abstract base class to use for AST consumer-based frontend actions.
class ASTIdentifierIterator
An identifier-lookup iterator that enumerates all of the identifiers stored within a set of AST files.
class ASTImporter
Imports selected nodes from one AST context into another context, merging AST nodes where appropriate.
class ASTImporterLookupTable
class ASTImporterSharedState
Importer specific state, which may be shared amongst several ASTImporter objects.
class ASTMergeAction
Frontend action adaptor that merges ASTs together.
class ASTMutationListener
An abstract interface that should be implemented by listeners that want to be notified when an AST entity gets modified after its initial creation.
class ASTNameGenerator
class ASTNodeImporter
class ASTNodeKind
Kind identifier.
class ASTNodeTraverser
ASTNodeTraverser traverses the Clang AST for dumping purposes.
class ASTPrintAction
class ASTReader
Reads an AST files chain containing the contents of a translation unit.
class ASTReaderListener
Abstract interface for callback invocations by the ASTReader.
class ASTRecordLayout
ASTRecordLayout - This class contains layout information for one RecordDecl, which is a struct/union/class.
class ASTRecordReader
An object for streaming information from a record.
class ASTRecordWriter
An object for streaming information to a record.
class ASTSourceDescriptor
Abstracts clang modules and precompiled header files and holds everything needed to generate debug info for an imported module or PCH.
class ASTStmtReader
class ASTStmtWriter
struct ASTTemplateArgumentListInfo
Represents an explicit template argument list in C++, e.g., the "<int>" in "sort<int>".
struct ASTTemplateKWAndArgsInfo
Represents an explicit template argument list in C++, e.g., the "<int>" in "sort<int>".
class ASTUnit
Utility class for loading a ASTContext from an AST file.
class ASTUnresolvedSet
An UnresolvedSet-like class which uses the ASTContext's allocator.
class ASTVector
class ASTViewAction
class ASTWriter
Writes an AST file containing the contents of a translation unit.
class AsTypeExpr
AsTypeExpr - Clang builtin function __builtin_astype [OpenCL 6.2.4.2] This AST node provides support for reinterpreting a type to another type of the same size.
struct AtomicConstraint
class AtomicExpr
AtomicExpr - Variadic atomic builtins: __atomic_exchange, __atomic_fetch_*, __atomic_load, __atomic_store, and __atomic_compare_exchange_*, for the similarly-named C++11 instructions, and __c11 variants for <stdatomic.h>, and corresponding __opencl_atomic_* for OpenCL 2.0.
class AtomicScopeModel
Defines the interface for synch scope model.
class AtomicScopeOpenCLModel
Defines the synch scope model for OpenCL.
class AtomicType
class AtomicTypeLoc
struct AtomicTypeLocInfo
class Attr
Attr - This represents one attribute.
class AttributeCommonInfo
struct AttributedLocInfo
class AttributedStmt
Represents an attribute applied to a statement.
class AttributedType
An attributed type is a type to which a type attribute has been applied.
class AttributedTypeLoc
Type source information for an attributed type.
class AttributeFactory
A factory, from which one makes pools, from which one creates individual attributes which are deallocated with the pool.
class AttributePool
class AttrVisitor
A simple visitor class that helps create attribute visitors.
class AutoType
Represents a C++11 auto or C++14 decltype(auto) type, possibly constrained by a type-constraint.
class AutoTypeLoc
struct AutoTypeLocInfo
class AvailabilityAttr
struct AvailabilityChange
Represents information about a change in availability for an entity, which is part of the encoding of the 'availability' attribute.
class AvailabilitySpec
One specifier in an @available expression.
class AVRInterruptAttr
class AVRSignalAttr
class BackendConsumer
struct BackwardDataflowWorklist
A worklist implementation for backward dataflow analysis.
struct BadConversionSequence
BadConversionSequence - Records information about an invalid conversion sequence.
class BalancedDelimiterTracker
RAII class that helps handle the parsing of an open/close delimiter pair, such as braces { ... } or parentheses (...).
class BaseSubobject
class BeforeThanCompare
Comparison function object.
class BeforeThanCompare< SourceLocation >
Compare two source locations.
class BeforeThanCompare< SourceRange >
Compare two non-overlapping source ranges.
class BinaryConditionalOperator
BinaryConditionalOperator - The GNU extension to the conditional operator which allows the middle operand to be omitted.
class BinaryOperator
A builtin binary operation expression such as "x + y" or "x <= y".
class BindingDecl
A binding in a decomposition declaration.
class BlockDecl
Represents a block literal declaration, which is like an unnamed FunctionDecl.
class BlockEdge
class BlockEntrance
class BlockExit
class BlockExpr
BlockExpr - Adaptor class for mixing a BlockDecl with expressions.
class BlockInvocationContext
It represents a block invocation (based on BlockCall).
class BlockPointerType
Pointer to a block type.
class BlockPointerTypeLoc
Wrapper for source info for block pointers.
class BlocksAttr
struct BlockVarCopyInit
Copy initialization expr of a __block variable and a boolean flag that indicates whether the expression can throw.
class BodyFarm
class BPFPreserveAccessIndexAttr
class BreakStmt
BreakStmt - This represents a break.
class BuildPreambleErrorCategory
class BuiltinAttr
class BuiltinBitCastExpr
Represents a C++2a __builtin_bit_cast(T, v) expression.
struct BuiltinLocInfo
class BuiltinTemplateDecl
Represents the builtin template declaration which is used to implement __make_integer_seq and other builtin templates.
class BuiltinType
This class is used for builtin types like 'int'.
class BuiltinTypeLoc
Wrapper for source info for builtin types.
class BumpVector
class BumpVectorContext
class C11NoReturnAttr
class CallableWhenAttr
class CallbackAttr
class CalledOnceAttr
class CalledOnceCheckHandler
class CallEnter
Represents a point when we begin processing an inlined call.
class CallExitBegin
Represents a point when we start the call exit sequence (for inlined call).
class CallExitEnd
Represents a point when we finish the call exit sequence (for inlined call).
class CallExpr
CallExpr - Represents a function call (C99 6.5.2.2, C++ [expr.call]).
class CallGraph
The AST-based call graph.
class CallGraphNode
class CanonicalDeclPtr
A wrapper class around a pointer that always points to its canonical declaration.
class CanProxy
Canonical proxy type returned when retrieving the members of a canonical type or as the result of the CanQual<T>::getAs member function.
struct CanProxyAdaptor
Replaceable canonical proxy adaptor class that provides the link between a canonical type and the accessors of the type.
struct CanProxyAdaptor< BlockPointerType >
struct CanProxyAdaptor< ComplexType >
struct CanProxyAdaptor< DecltypeType >
struct CanProxyAdaptor< DependentSizedExtVectorType >
struct CanProxyAdaptor< EnumType >
struct CanProxyAdaptor< ExtVectorType >
struct CanProxyAdaptor< FunctionNoProtoType >
struct CanProxyAdaptor< FunctionProtoType >
struct CanProxyAdaptor< FunctionType >
struct CanProxyAdaptor< LValueReferenceType >
struct CanProxyAdaptor< MemberPointerType >
struct CanProxyAdaptor< ObjCObjectPointerType >
struct CanProxyAdaptor< ObjCObjectType >
struct CanProxyAdaptor< PointerType >
struct CanProxyAdaptor< RecordType >
struct CanProxyAdaptor< ReferenceType >
struct CanProxyAdaptor< RValueReferenceType >
struct CanProxyAdaptor< TagType >
struct CanProxyAdaptor< TemplateTypeParmType >
struct CanProxyAdaptor< TypeOfType >
struct CanProxyAdaptor< UnaryTransformType >
struct CanProxyAdaptor< VectorType >
class CanProxyBase
Base class of all canonical proxy types, which is responsible for storing the underlying canonical type and providing basic conversions.
class CanQual
Represents a canonical, potentially-qualified type.
struct CanTypeIterator
Iterator adaptor that turns an iterator over canonical QualTypes into an iterator over CanQualTypes.
class CapabilityAttr
class CapturedDecl
Represents the body of a CapturedStmt, and serves as its DeclContext.
class CapturedRecordAttr
class CapturedStmt
This captures a statement into a function.
class CarriesDependencyAttr
class CaseStmt
CaseStmt - Represent a case statement.
struct cast_convert_decl_context
struct cast_convert_decl_context< ToTy, true >
class CastExpr
CastExpr - Base class for type casts, including both implicit casts (ImplicitCastExpr) and explicit casts that have some representation in the source code (ExplicitCastExpr's derived classes).
class CDeclAttr
class CFAuditedTransferAttr
class CFConsumedAttr
class CFG
Represents a source-level, intra-procedural CFG that represents the control-flow of a Stmt.
class CFGAutomaticObjDtor
Represents C++ object destructor implicitly generated for automatic object or temporary bound to const reference at the point of leaving its local scope.
class CFGBaseDtor
Represents C++ object destructor implicitly generated for base object in destructor.
class CFGBlock
Represents a single basic block in a source-level CFG.
class CFGCallback
CFGCallback defines methods that should be called when a logical operator error is found when building the CFG.
class CFGConstructor
Represents C++ constructor call.
class CFGCXXRecordTypedCall
Represents a function call that returns a C++ object by value.
class CFGDeleteDtor
Represents C++ object destructor generated from a call to delete.
class CFGDominatorTreeImpl
Dominator tree builder for Clang's CFG based on llvm::DominatorTreeBase.
class CFGElement
Represents a top-level expression in a basic block.
class CFGImplicitDtor
Represents C++ object destructor implicitly generated by compiler on various occasions.
class CFGInitializer
Represents C++ base or member initializer from constructor's initialization list.
class CFGLifetimeEnds
Represents the point where the lifetime of an automatic object ends.
class CFGLoopExit
Represents the point where a loop ends.
class CFGMemberDtor
Represents C++ object destructor implicitly generated for member object in destructor.
class CFGNewAllocator
Represents C++ allocator call.
class CFGReverseBlockReachabilityAnalysis
class CFGScopeBegin
Represents beginning of a scope implicitly generated by the compiler on encountering a CompoundStmt.
class CFGScopeEnd
Represents end of a scope implicitly generated by the compiler after the last Stmt in a CompoundStmt's body.
class CFGStmt
class CFGStmtMap
class CFGTemporaryDtor
Represents C++ object destructor implicitly generated at the end of full expression for temporary object.
class CFGTerminator
Represents CFGBlock terminator statement.
class CFGuardAttr
class CFICanonicalJumpTableAttr
class CFReturnsNotRetainedAttr
class CFReturnsRetainedAttr
class CFUnknownTransferAttr
class ChainedASTReaderListener
Simple wrapper class for chaining listeners.
class ChainedDiagnosticConsumer
ChainedDiagnosticConsumer - Chain two diagnostic clients so that diagnostics go to the first client and then the second.
class CharacterLiteral
class CharLiteralParser
CharLiteralParser - Perform interpretation and semantic analysis of a character literal.
class CharSourceRange
Represents a character-granular source range.
class CharUnits
CharUnits - This is an opaque type for sizes expressed in character units.
class ChooseExpr
ChooseExpr - GNU builtin-in function __builtin_choose_expr.
class ClangDiagnosticHandler
class ClassScopeFunctionSpecializationDecl
Declaration of a function specialization at template class scope.
class ClassTemplateDecl
Declaration of a class template.
class ClassTemplatePartialSpecializationDecl
class ClassTemplateSpecializationDecl
Represents a class template specialization, which refers to a class template with a given set of template arguments.
class CleanupAttr
class CleanupInfo
class CloneConstraint
This class is a utility class that contains utility functions for building custom constraints.
class CloneDetector
Searches for similar subtrees in the AST.
class CmseNSCallAttr
class CmseNSEntryAttr
class CoawaitExpr
Represents a 'co_await' expression.
class CodeCompleteConsumer
Abstract interface for a consumer of code-completion information.
class CodeCompleteOptions
Options controlling the behavior of code completion.
class CodeCompletionAllocator
An allocator used specifically for the purpose of code completion.
class CodeCompletionBuilder
A builder class used to construct new code-completion strings.
class CodeCompletionContext
The context in which code completion occurred, so that the code-completion consumer can process the results accordingly.
class CodeCompletionHandler
Callback handler that receives notifications when performing code completion within the preprocessor.
class CodeCompletionResult
Captures a result of code completion.
class CodeCompletionString
A "string" used to describe how code completion can be performed for an entity.
class CodeCompletionTUInfo
class CodeGenAction
class CodeGenerator
The primary public interface to the Clang code generator.
class CodeGenOptions
CodeGenOptions - Track various options which control how the code is optimized and passed to the backend.
class CodeGenOptionsBase
Bitfields of CodeGenOptions, split out from CodeGenOptions to ensure that this large collection of bitfields is a trivial class type.
class CodeInjector
CodeInjector is an interface which is responsible for injecting AST of function definitions that may not be available in the original source.
class CodeSegAttr
class ColdAttr
class ColonProtectionRAIIObject
ColonProtectionRAIIObject - This sets the Parser::ColonIsSacred bool and restores it when destroyed.
class ColorScope
class CommaSeparatedList
class CommentHandler
Abstract base class that describes a handler that will receive source ranges for each of the comments encountered in the source file.
struct CommentOptions
Options for controlling comment parsing.
class CommonAttr
class ComparisonCategories
class ComparisonCategoryInfo
class CompilerInstance
CompilerInstance - Helper class for managing a single instance of the Clang compiler.
class CompilerInvocation
Helper class for holding the data necessary to invoke the compiler.
class CompilerInvocationBase
class ComplexType
Complex values, per C99 6.2.5p11.
class ComplexTypeLoc
class CompoundAssignOperator
CompoundAssignOperator - For compound assignments (e.g.
class CompoundLiteralExpr
CompoundLiteralExpr - [C99 6.5.2.5].
class CompoundStmt
CompoundStmt - This represents a group of statements like { stmt stmt }.
class ConceptDecl
Declaration of a C++2a concept.
class ConceptReference
Common data class for constructs that reference concepts with template arguments.
class ConceptSpecializationExpr
Represents the specialization of a concept - evaluates to a prvalue of type bool.
class ConcreteTypeLoc
A metaprogramming base class for TypeLoc classes which correspond to a particular Type subclass.
class ConditionalOperator
ConditionalOperator - The ?: ternary operator.
class ConstantArrayType
Represents the canonical version of C arrays with a specified constant size.
class ConstantArrayTypeLoc
class ConstantExpr
ConstantExpr - An expression that occurs in a constant context and optionally the result of evaluating the expression.
class ConstantMatrixType
Represents a concrete matrix type with constant number of rows and columns.
class ConstantMatrixTypeLoc
class ConstAttr
class ConstAttrVisitor
A simple visitor class that helps create attribute visitors.
class ConstDeclVisitor
A simple visitor class that helps create declaration visitors.
class ConstEvaluatedExprVisitor
ConstEvaluatedExprVisitor - This class visits 'const Expr *'s.
class ConstInitAttr
class ConstOMPClauseVisitor
class ConstraintSatisfaction
The result of a constraint satisfaction check, containing the necessary information to diagnose an unsatisfied constraint.
class ConstructionContext
ConstructionContext's subclasses describe different ways of constructing an object in C++.
class ConstructionContextItem
Represents a single point (AST node) in the program that requires attention during construction of an object.
class ConstructionContextLayer
Construction context can be seen as a linked list of multiple layers.
class ConstructorAttr
struct ConstructorInfo
class ConstructorInitializerConstructionContext
class ConstructorUsingShadowDecl
Represents a shadow constructor declaration introduced into a class by a C++11 using-declaration that names a constructor.
struct ConstStmtIterator
class ConstStmtVisitor
ConstStmtVisitor - This class implements a simple visitor for Stmt subclasses.
class ConstTemplateArgumentVisitor
A simple visitor class that helps create template argument visitors.
class ConsumableAttr
class ConsumableAutoCastAttr
class ConsumableSetOnReadAttr
class ContinueStmt
ContinueStmt - This represents a continue.
class ContinuousRangeMap
A map from continuous integer ranges to some value, with a very specialized interface.
class ControlDependencyCalculator
class ConvergentAttr
struct ConversionFixItGenerator
The class facilities generation and storage of conversion FixIts.
class ConvertVectorExpr
ConvertVectorExpr - Clang builtin function __builtin_convertvector This AST node provides support for converting a vector type to another vector type of the same arity.
struct CopiedTypeVisitor
class CoreturnStmt
Represents a 'co_return' statement in the C++ Coroutines TS.
class CoroutineBodyStmt
Represents the body of a coroutine.
class CoroutineStmtBuilder
class CoroutineSuspendExpr
Represents an expression that might suspend coroutine execution; either a co_await or co_yield expression.
class CorrectionCandidateCallback
Base class for callback objects used by Sema::CorrectTypo to check the validity of a potential typo correction.
class CoverageSourceInfo
Stores additional source code information like skipped ranges which is required by the coverage mapping generator and is obtained from the preprocessor.
class CoyieldExpr
Represents a 'co_yield' expression.
class CPUDispatchAttr
class CPUSpecificAttr
class CStyleCastExpr
CStyleCastExpr - An explicit cast in C (C99 6.5.4) or a C-style cast in C++ (C++ [expr.cast]), which uses the syntax (Type)expr.
struct CudaArchToStringMap
class CUDAConstantAttr
class CUDADeviceAttr
class CUDADeviceBuiltinSurfaceTypeAttr
class CUDADeviceBuiltinTextureTypeAttr
class CUDAGlobalAttr
class CUDAHostAttr
class CUDAInvalidTargetAttr
class CUDAKernelCallExpr
Represents a call to a CUDA kernel function.
class CUDALaunchBoundsAttr
class CUDASharedAttr
class CurrentSourceLocExprScope
Represents the current source location and context used to determine the value of the source location builtins (ex.
class CXX11NoReturnAttr
class CXX17ElidedCopyConstructorInitializerConstructionContext
Represents construction into a field or a base class within a bigger object via a constructor initializer, with a single constructor, eg.
class CXX17ElidedCopyReturnedValueConstructionContext
Represents a temporary object that is being immediately returned from a function by value, eg.
class CXX17ElidedCopyVariableConstructionContext
Represents construction into a simple variable with an initializer syntax, with a single constructor, eg.
class CXXABI
Implements C++ ABI-specific semantic analysis functions.
class CXXAddrspaceCastExpr
A C++ addrspace_cast expression (currently only enabled for OpenCL).
class CXXBasePath
Represents a path from a specific derived class (which is not represented as part of the path) to a particular (direct or indirect) base class subobject.
struct CXXBasePathElement
Represents an element in a path from a derived class to a base class.
class CXXBasePaths
BasePaths - Represents the set of paths from a derived class to one of its (direct or indirect) bases.
class CXXBaseSpecifier
Represents a base class of a C++ class.
class CXXBindTemporaryExpr
Represents binding an expression to a temporary.
class CXXBoolLiteralExpr
A boolean literal, per ([C++ lex.bool] Boolean literals).
class CXXCatchStmt
CXXCatchStmt - This represents a C++ catch block.
class CXXConstCastExpr
A C++ const_cast expression (C++ [expr.const.cast]).
class CXXConstructExpr
Represents a call to a C++ constructor.
class CXXConstructorDecl
Represents a C++ constructor within a class.
class CXXConversionDecl
Represents a C++ conversion function within a class.
class CXXCtorInitializer
Represents a C++ base or member initializer.
class CXXDeductionGuideDecl
Represents a C++ deduction guide declaration.
class CXXDefaultArgExpr
A default argument (C++ [dcl.fct.default]).
class CXXDefaultInitExpr
A use of a default initializer in a constructor or in aggregate initialization.
class CXXDeleteExpr
Represents a delete expression for memory deallocation and destructor calls, e.g.
class CXXDependentScopeMemberExpr
Represents a C++ member access expression where the actual member referenced could not be resolved because the base expression or the member name was dependent.
class CXXDestructorDecl
Represents a C++ destructor within a class.
class CXXDynamicCastExpr
A C++ dynamic_cast expression (C++ [expr.dynamic.cast]).
class CXXFieldCollector
CXXFieldCollector - Used to keep track of CXXFieldDecls during parsing of C++ classes.
class CXXFinalOverriderMap
A mapping from each virtual member function to its set of final overriders.
class CXXFoldExpr
Represents a folding of a pack over an operator.
class CXXForRangeStmt
CXXForRangeStmt - This represents C++0x [stmt.ranged]'s ranged for statement, represented as 'for (range-declarator : range-expression)' or 'for (init-statement range-declarator : range-expression)'.
class CXXFunctionalCastExpr
Represents an explicit C++ type conversion that uses "functional" notation (C++ [expr.type.conv]).
class CXXIndirectPrimaryBaseSet
A set of all the primary bases for a class.
class CXXInheritedCtorInitExpr
Represents a call to an inherited base class constructor from an inheriting constructor.
class CXXMemberCallExpr
Represents a call to a member function that may be written either with member call syntax (e.g., "obj.func()" or "objptr->func()") or with normal function-call syntax ("func()") within a member function that ends up calling a member function.
class CXXMethodDecl
Represents a static or instance method of a struct/union/class.
class CXXNamedCastExpr
Abstract class common to all of the C++ "named"/"keyword" casts.
class CXXNewExpr
Represents a new-expression for memory allocation and constructor calls, e.g: "new CXXNewExpr(foo)".
class CXXNoexceptExpr
Represents a C++11 noexcept expression (C++ [expr.unary.noexcept]).
class CXXNullPtrLiteralExpr
The null pointer literal (C++11 [lex.nullptr])
class CXXOperatorCallExpr
A call to an overloaded operator written using operator syntax.
class CXXPseudoDestructorExpr
Represents a C++ pseudo-destructor (C++ [expr.pseudo]).
class CXXRecordDecl
Represents a C++ struct/union/class.
class CXXReinterpretCastExpr
A C++ reinterpret_cast expression (C++ [expr.reinterpret.cast]).
class CXXRewrittenBinaryOperator
A rewritten comparison expression that was originally written using operator syntax.
class CXXScalarValueInitExpr
An expression "T()" which creates a value-initialized rvalue of type T, which is a non-class type.
class CXXScopeSpec
Represents a C++ nested-name-specifier or a global scope specifier.
class CXXStaticCastExpr
A C++ static_cast expression (C++ [expr.static.cast]).
class CXXStdInitializerListExpr
Implicit construction of a std::initializer_list<T> object from an array temporary within list-initialization (C++11 [dcl.init.list]p5).
class CXXTemporary
Represents a C++ temporary.
class CXXTemporaryObjectExpr
Represents a C++ functional cast expression that builds a temporary object.
class CXXThisExpr
Represents the this expression in C++.
class CXXThrowExpr
A C++ throw-expression (C++ [except.throw]).
class CXXTryStmt
CXXTryStmt - A C++ try block, including all handlers.
class CXXTypeidExpr
A C++ typeid expression (C++ [expr.typeid]), which gets the type_info that corresponds to the supplied type, or the (possibly dynamic) type of the supplied expression.
class CXXUnresolvedConstructExpr
Describes an explicit type conversion that uses functional notion but could not be resolved because one or more arguments are type-dependent.
class CXXUuidofExpr
A Microsoft C++ __uuidof expression, which gets the _GUID that corresponds to the supplied type or expression.
class DataflowValues
DataflowValues. Container class to store dataflow values for a CFG.
class DataflowWorklistBase
A worklist implementation where the enqueued blocks will be dequeued based on the order defined by 'Comp'.
class DecayedType
Represents a pointer type decayed from an array or function type.
class DecayedTypeLoc
Wrapper for source info for pointers decayed from arrays and functions.
class Decl
Decl - This represents one declaration (or definition), e.g.
class DeclAccessPair
A POD class for pairing a NamedDecl* with an access specifier.
class DeclarationName
The name of a declaration.
struct DeclarationNameInfo
DeclarationNameInfo - A collector data type for bundling together a DeclarationName and the correspnding source/type location info.
struct DeclarationNameLoc
DeclarationNameLoc - Additional source/type location info for a declaration name.
class DeclarationNameTable
DeclarationNameTable is used to store and retrieve DeclarationName instances for the various kinds of declaration names, e.g., normal identifiers, C++ constructor names, etc.
class Declarator
Information about one declarator, including the parsed type information and the identifier.
struct DeclaratorChunk
One instance of this struct is used for each type in a declarator that is parsed.
class DeclaratorDecl
Represents a ValueDecl that came out of a declarator.
class DeclContext
DeclContext - This is used only as base class of specific decl types that can act as declaration contexts.
class DeclContextLookupResult
The results of name lookup within a DeclContext.
class DeclFilterCCC
Simple template class for restricting typo correction candidates to ones having a single Decl* of the given type.
class DeclGroup
class DeclGroupRef
class DeclOrStmtAttr
class DeclRefExpr
A reference to a declared variable, function, enum, etc.
class DeclSpec
Captures information about "declaration specifiers".
class DeclStmt
DeclStmt - Adaptor class for mixing declarations with statements and expressions.
class DecltypeType
Represents the type decltype(expr) (C++11).
class DecltypeTypeLoc
class DeclVisitor
A simple visitor class that helps create declaration visitors.
class DecompositionDecl
A decomposition declaration.
class DecompositionDeclarator
A parsed C++17 decomposition declarator of the form '[' identifier-list ']'.
struct DeducedPack
A pack that we're currently deducing.
class DeducedTemplateArgument
Captures a template argument whose value has been deduced via c++ template argument deduction.
class DeducedTemplateSpecializationType
Represents a C++17 deduced template specialization type.
class DeducedTemplateSpecializationTypeLoc
class DeducedType
Common base class for placeholders for types that get replaced by placeholder type deduction: C++11 auto, C++14 decltype(auto), C++17 deduced class template types, and constrained type names.
class DeducedTypeLoc
struct DeductionFailureInfo
A structure used to record information about a failed template argument deduction, for diagnosis.
class DefaultArgStorage
Storage for a default argument.
class DefaultFilterCCC
struct DefaultInitializedTypeVisitor
class DefaultStmt
class DefMacroDirective
A directive for a defined macro or a macro imported from a module.
class DeltaTree
DeltaTree - a multiway search tree (BTree) structure with some fancy features.
class Dependence
class DependencyCollector
An interface for collecting the dependencies of a compilation.
class DependencyFileGenerator
Builds a dependency file when attached to a Preprocessor (for includes) and ASTReader (for module imports), and writes it out at the end of processing a source file.
class DependencyOutputOptions
DependencyOutputOptions - Options for controlling the compiler dependency file generation.
struct DependentAddressSpaceLocInfo
class DependentAddressSpaceType
Represents an extended address space qualifier where the input address space value is dependent.
class DependentAddressSpaceTypeLoc
class DependentCoawaitExpr
Represents a 'co_await' expression while the type of the promise is dependent.
class DependentDecltypeType
Internal representation of canonical, dependent decltype(expr) types.
class DependentDiagnostic
A dependently-generated diagnostic.
class DependentExtIntType
class DependentExtIntTypeLoc
class DependentFunctionTemplateSpecializationInfo
Provides information about a dependent function-template specialization declaration.
struct DependentNameLocInfo
class DependentNameType
Represents a qualified type name for which the type name is dependent.
class DependentNameTypeLoc
class DependentScopeDeclRefExpr
A qualified reference to a name whose declaration cannot yet be resolved.
class DependentSizedArrayType
Represents an array type in C++ whose size is a value-dependent expression.
class DependentSizedArrayTypeLoc
class DependentSizedExtVectorType
Represents an extended vector type where either the type or size is dependent.
class DependentSizedExtVectorTypeLoc
class DependentSizedMatrixType
Represents a matrix type where the type and the number of rows and columns is dependent on a template.
class DependentSizedMatrixTypeLoc
class DependentStoredDeclsMap
class DependentTemplateName
Represents a dependent template name that cannot be resolved prior to template instantiation.
struct DependentTemplateSpecializationLocInfo
class DependentTemplateSpecializationType
Represents a template specialization type whose template cannot be resolved, e.g.
class DependentTemplateSpecializationTypeLoc
class DependentTypeOfExprType
Internal representation of canonical, dependent typeof(expr) types.
class DependentUnaryTransformType
Internal representation of canonical, dependent __underlying_type(type) types.
class DependentVectorType
Represents a vector type where either the type or size is dependent.
class DependentVectorTypeLoc
class DeprecatedAttr
class DesignatedInitExpr
Represents a C99 designated initializer expression.
class DesignatedInitUpdateExpr
class Designation
Designation - Represent a full designation, which is a sequence of designators.
class Designator
Designator - A designator in a C99 designated initializer.
struct DestructedTypeVisitor
class DestructorAttr
class DiagnoseIfAttr
class Diagnostic
A little helper class (which is basically a smart pointer that forwards info from DiagnosticsEngine) that allows clients to enquire about the currently in-flight diagnostic.
class DiagnosticBuilder
A little helper class used to produce diagnostics.
class DiagnosticConsumer
Abstract interface, implemented by clients of the front-end, which formats and prints fully processed diagnostics.
class DiagnosticError
Carries a Clang diagnostic in an llvm::Error.
class DiagnosticErrorTrap
RAII class that determines when any errors have occurred between the time the instance was created and the time it was queried.
class DiagnosticIDs
Used for handling and querying diagnostic IDs.
class DiagnosticMapping
class DiagnosticNoteRenderer
Subclass of DiagnosticRender that turns all subdiagostics into explicit notes.
class DiagnosticOptions
Options for controlling the compiler diagnostics engine.
class DiagnosticRenderer
Class to encapsulate the logic for formatting a diagnostic message.
class DiagnosticsEngine
Concrete class used by the front-end to report problems and issues.
struct DiagnosticStorage
class DirectoryEntry
Cached information about one directory (either on disk or in the virtual file system).
class DirectoryEntryRef
A reference to a DirectoryEntry that includes the name of the directory as it was accessed by the FileManager's client.
class DirectoryLookup
DirectoryLookup - This class represents one entry in the search list that specifies the search order for directories in #include directives.
class DirectoryWatcher
Provides notifications for file changes in a directory.
class DisableTailCallsAttr
class DLLExportAttr
class DLLExportStaticLocalAttr
class DLLImportAttr
class DLLImportStaticLocalAttr
class DoStmt
DoStmt - This represents a 'do/while' stmt.
class DumpCompilerOptionsAction
class DumpModuleInfoAction
Dump information about the given module file, to be used for basic debugging and discovery.
class DumpRawTokensAction
class DumpTokensAction
class DynamicAllocLValue
Symbolic representation of a dynamic allocation.
class DynTypedNode
A dynamically typed AST node container.
class DynTypedNodeList
Container for either a single DynTypedNode or for an ArrayRef to DynTypedNode.
struct ElaboratedLocInfo
class ElaboratedType
Represents a type that was referred to using an elaborated type keyword, e.g., struct S, or via a qualified name, e.g., N::M::type, or both.
class ElaboratedTypeLoc
class ElidedTemporaryObjectConstructionContext
Represents a temporary object that is constructed for the sole purpose of being immediately copied by an elidable copy/move constructor.
class EmitAssemblyAction
class EmitBCAction
class EmitCodeGenOnlyAction
class EmitLLVMAction
class EmitLLVMOnlyAction
class EmitObjAction
class EmptyBasesAttr
class EmptyDecl
Represents an empty-declaration.
class EmptylineHandler
Abstract base class that describes a handler that will receive source ranges for empty lines encountered in the source file.
class EmptyPragmaHandler
EmptyPragmaHandler - A pragma handler which takes no action, which can be used to ignore particular pragmas.
class EnableIfAttr
class EnforceTCBAttr
class EnforceTCBLeafAttr
class EnterExpressionEvaluationContext
RAII object that enters a new expression evaluation context.
class EnumConstantDecl
An instance of this object exists for each enum constant that is defined.
class EnumDecl
Represents an enum.
class EnumExtensibilityAttr
class EnumType
A helper class that allows the use of isa/cast/dyncast to detect TagType objects of enums.
class EnumTypeLoc
Wrapper for source info for enum types.
class EpsilonPoint
This is a meta program point, which should be skipped by all the diagnostic reasoning etc.
class EvaluatedExprVisitor
EvaluatedExprVisitor - This class visits 'Expr *'s.
class EvaluatedExprVisitorBase
Given a potentially-evaluated expression, this visitor visits all of its potentially-evaluated subexpressions, recursively.
struct EvaluatedStmt
Structure used to store a statement, the constant value to which it was evaluated (if any), and whether or not the statement is an integral constant expression (if known).
class ExcludeFromExplicitInstantiationAttr
class ExclusiveTrylockFunctionAttr
class ExplicitCastExpr
ExplicitCastExpr - An explicit cast written in the source code.
class ExplicitSpecifier
Store information needed for an explicit specifier.
class ExportDecl
Represents a C++ Modules TS module export declaration.
class Expr
This represents one expression.
struct ExprDependenceScope
class ExpressionTraitExpr
An expression trait intrinsic.
class ExprMutationAnalyzer
Analyzes whether any mutative operations are applied to an expression within a given statement.
class ExprWithCleanups
Represents an expression – generally a full-expression – that introduces cleanups to be run at the end of the sub-expression's evaluation.
class ExtensionRAIIObject
ExtensionRAIIObject - This saves the state of extension warnings when constructed and disables them.
class ExternalASTMerger
ExternalASTSource implementation that merges information from several ASTContexts.
class ExternalASTSource
Abstract interface for external sources of AST nodes.
class ExternalHeaderFileInfoSource
An external source of header file information, which may supply information about header files already included.
class ExternalPreprocessingRecordSource
An abstract class that should be subclassed by any external source of preprocessing record entries.
class ExternalPreprocessorSource
Abstract interface for external sources of preprocessor information.
class ExternalSemaSource
An abstract interface that should be implemented by external AST sources that also provide information for semantic analysis.
class ExternalSLocEntrySource
External source of source location entries.
class ExternalSourceSymbolAttr
struct ExternalVTableUse
A simple structure that captures a vtable use for the purposes of the ExternalSemaSource.
class ExternCContextDecl
Declaration context for names declared as extern "C" in C++.
class ExtIntType
A fixed int type of a specified bitwidth.
class ExtIntTypeLoc
class ExtQuals
We can encode up to four bits in the low bits of a type pointer, but there are many more type qualifiers that we want to be able to apply to an arbitrary type.
class ExtQualsTypeCommonBase
Base class that is common to both the ExtQuals and Type classes, which allows QualType to access the common fields between the two.
class ExtVectorElementExpr
ExtVectorElementExpr - This represents access to specific elements of a vector, and may occur on the left hand side or right hand side.
class ExtVectorType
ExtVectorType - Extended vector type.
class ExtVectorTypeLoc
class FallThroughAttr
class FastCallAttr
class FieldDecl
Represents a member of a struct/union/class.
struct FieldDeclarator
This little struct is used to capture information about structure field declarators, which is basically just a bitfield size.
class FileEntry
Cached information about one file (either on disk or in the virtual file system).
class FileEntryRef
A reference to a FileEntry that includes the name of the file as it was accessed by the FileManager's client.
class FileID
An opaque identifier used by SourceManager which refers to a source file (MemoryBuffer) along with its #include path and #line data.
class FileManager
Implements support for file system lookup, file system caching, and directory search management.
struct FilenamePatternConstraint
struct FileNullability
Describes whether we've seen any nullability information for the given file.
class FileNullabilityMap
A mapping from file IDs to a record of whether we've seen nullability information in that file.
class FileScopeAsmDecl
class FileSystemOptions
Keeps track of options that affect how file operations are performed.
class FileSystemStatCache
Abstract interface for introducing a FileManager cache for 'stat' system calls, which is used by precompiled and pretokenized headers to improve performance.
class FinalAttr
class FixedPointLiteral
class FixedSizeTemplateParameterListStorage
Stores a list of template parameters and the associated requires-clause (if any) for a TemplateDecl and its derived classes.
class FixItAction
class FixItHint
Annotates a diagnostic with some code that should be inserted, removed, or replaced to fix the problem.
class FixItOptions
class FixItRecompile
Emits changes to temporary files and uses them for the original frontend action.
class FixItRewriter
class FlagEnumAttr
class FlattenAttr
class FloatingLiteral
class FormatArgAttr
class FormatAttr
class ForStmt
ForStmt - This represents a 'for (init;cond;inc)' stmt.
struct ForwardDataflowWorklist
A worklist implementation for forward dataflow analysis.
class ForwardingDiagnosticConsumer
Diagnostic consumer that forwards diagnostics along to an existing, already-initialized diagnostic consumer.
class FPOptions
class FPOptionsOverride
Represents difference between two FPOptions values.
struct FrameworkCacheEntry
This structure is used to record entries in our framework cache.
class FriendDecl
FriendDecl - Represents the declaration of a friend entity, which can be a function, a type, or a templated function or type.
class FriendTemplateDecl
Declaration of a friend template.
class FrontendAction
Abstract base class for actions which can be performed by the frontend.
class FrontendInputFile
An input file for the front end.
class FrontendOptions
FrontendOptions - Options for controlling the behavior of the frontend.
class FullExpr
FullExpr - Represents a "full-expression" node.
class FullSourceLoc
A SourceLocation and its associated SourceManager.
class FunctionCallFilterCCC
class FunctionDecl
Represents a function declaration or definition.
class FunctionExitPoint
struct FunctionLocInfo
class FunctionNoProtoType
Represents a K&R-style 'int foo()' function, which has no information available about its arguments.
class FunctionNoProtoTypeLoc
class FunctionParmMutationAnalyzer
class FunctionParmPackExpr
Represents a reference to a function parameter pack or init-capture pack that has been substituted but not yet expanded.
class FunctionProtoType
Represents a prototype with parameter type info, e.g.
class FunctionProtoTypeLoc
class FunctionTemplateDecl
Declaration of a template function.
class FunctionTemplateSpecializationInfo
Provides information about a function template specialization, which is a FunctionDecl that has been explicitly specialization or instantiated from a function template.
class FunctionType
FunctionType - C99 6.7.5.3 - Function Declarators.
class FunctionTypeLoc
Wrapper for source info for functions.
class GCCAsmStmt
This represents a GCC inline-assembly statement extension.
class GenerateHeaderModuleAction
class GenerateInterfaceStubsAction
class GenerateModuleAction
class GenerateModuleFromModuleMapAction
class GenerateModuleInterfaceAction
class GeneratePCHAction
class GenericSelectionExpr
Represents a C11 generic selection.
class GlobalCodeCompletionAllocator
Allocator for a cached set of global code completions.
class GlobalDecl
GlobalDecl - represents a global declaration.
class GlobalModuleIndex
A global index for a set of module files, providing information about the identifiers within those module files.
class GNUInlineAttr
class GNUNullExpr
GNUNullExpr - Implements the GNU __null extension, which is a name for a null pointer constant that has integral type (e.g., int or long) and is the same size and alignment as a pointer.
class GotoStmt
GotoStmt - This represents a direct goto.
class GreaterThanIsOperatorScope
RAII object that makes '>' behave either as an operator or as the closing angle bracket for a template argument list.
class GuardedByAttr
class GuardedVarAttr
struct HeaderFileInfo
The preprocessor keeps track of this information for each file that is #included.
class HeaderMap
This class represents an Apple concept known as a 'header map'.
class HeaderMapImpl
Implementation for HeaderMap that doesn't depend on FileManager.
class HeaderSearch
Encapsulates the information needed to find the file referenced by a #include or #include_next, (sub-)framework lookup, etc.
class HeaderSearchOptions
HeaderSearchOptions - Helper class for storing options related to the initialization of the HeaderSearch object.
class HIPManagedAttr
struct HMapBucket
struct HMapHeader
class HotAttr
class HTMLPrintAction
class IBActionAttr
class IBOutletAttr
class IBOutletCollectionAttr
class IdentifierInfo
One of these records is kept for each identifier that is lexed.
class IdentifierInfoLookup
Provides lookups to, and iteration over, IdentiferInfo objects.
class IdentifierIterator
An iterator that walks over all of the known identifiers in the lookup table.
struct IdentifierLoc
Wraps an identifier and optional source location for the identifier.
class IdentifierResolver
IdentifierResolver - Keeps track of shadowed decls on enclosing scopes.
class IdentifierTable
Implements an efficient mapping from strings to IdentifierInfo nodes.
class IfStmt
IfStmt - This represents an if/then/else.
class IFuncAttr
class IgnoringDiagConsumer
A diagnostic client that ignores all diagnostics.
class ImaginaryLiteral
ImaginaryLiteral - We support imaginary integer and floating point literals, like "1.0i".
class ImplicitCallPoint
Represents an implicit call event.
class ImplicitCastExpr
ImplicitCastExpr - Allows us to explicitly represent implicit type conversions, which have no direct representation in the original source code.
class ImplicitConversionSequence
ImplicitConversionSequence - Represents an implicit conversion sequence, which may be a standard conversion sequence (C++ 13.3.3.1.1), user-defined conversion sequence (C++ 13.3.3.1.2), or an ellipsis conversion sequence (C++ 13.3.3.1.3).
class ImplicitParamDecl
class ImplicitValueInitExpr
Represents an implicitly-generated value initialization of an object of a given type.
class ImportDecl
Describes a module import declaration, which makes the contents of the named module visible in the current translation unit.
class ImportError
class InBeforeInTUCacheEntry
Holds the cache used by isBeforeInTranslationUnit.
class InclusionDirective
Record the location of an inclusion directive, such as an #include or #import statement.
class IncompleteArrayType
Represents a C array with an unspecified size.
class IncompleteArrayTypeLoc
class IndirectFieldDecl
Represents a field injected from an anonymous union/struct into the parent scope.
class IndirectGotoStmt
IndirectGotoStmt - This represents an indirect goto.
class InheritableAttr
class InheritableParamAttr
class InheritedConstructor
Description of a constructor that was inherited from a base class.
class InheritingConcreteTypeLoc
A metaprogramming class designed for concrete subtypes of abstract types where all subtypes share equivalently-structured source information.
class InitializationKind
Describes the kind of initialization being performed, along with location information for tokens related to the initialization (equal sign, parentheses).
class InitializationSequence
Describes the sequence of initializations required to initialize a given object or reference with a set of arguments.
class InitializedEntity
Describes an entity that is being initialized.
class InitListExpr
Describes an C or C++ initializer list.
class InitOnlyAction
class InitPriorityAttr
class InitSegAttr
class InjectedClassNameType
The injected class name of a C++ class template or class template partial specialization.
class InjectedClassNameTypeLoc
Wrapper for source info for injected class names of class templates.
class InMemoryModuleCache
In-memory cache for modules.
class InMessageExpressionRAIIObject
class InputKind
The kind of a file that we've been handed as an input.
class IntegerLiteral
class IntelOclBiccAttr
class InternalLinkageAttr
struct InventedTemplateParameterInfo
struct IsResultPtrLowBitFree
struct IsResultPtrLowBitFree< CXXBaseSpecifier * >
struct IsResultPtrLowBitFree< CXXCtorInitializer * >
struct IsResultPtrLowBitFree< Expr * >
struct IsResultPtrLowBitFree< Stmt * >
class ItaniumMangleContext
class ItaniumVTableContext
class JSONDumper
class JSONNodeDumper
class LabelDecl
Represents the declaration of a label.
class LabelStmt
LabelStmt - Represents a label, which has a substatement.
class LambdaCapture
Describes the capture of a variable or of this, or of a C++1y init-capture.
class LambdaExpr
A C++ lambda expression, which produces a function object (of unspecified type) that can be invoked later.
struct LambdaIntroducer
Represents a complete lambda introducer.
class LangOptions
Keeps track of the various options that can be enabled, which controls the dialect of C or C++ that is accepted.
class LangOptionsBase
Bitfields of LangOptions, split out from LangOptions in order to ensure that this large collection of bitfields is a trivial class type.
struct LangStandard
LangStandard - Information about the properties of a particular language standard.
struct LateParsedTemplate
Contains a late templated function.
class LayoutOverrideSource
An external AST source that overrides the layout of a specified set of record types.
class LayoutVersionAttr
class LazyASTUnresolvedSet
An UnresolvedSet-like class that might not have been loaded from the external AST source yet.
struct LazyGenerationalUpdatePtr
A lazy value (of type T) that is within an AST node of type Owner, where the value might change in later generations of the external AST source.
struct LazyOffsetPtr
A lazy pointer to an AST node (of base type T) that resides within an external AST source.
class LazyVector
Represents a lazily-loaded vector of data.
class LeafAttr
class Lexer
Lexer - This provides a simple interface that turns a text buffer into a stream of tokens.
class LexicallyOrderedRecursiveASTVisitor
A RecursiveASTVisitor subclass that guarantees that AST traversal is performed in a lexical order (i.e.
class LifetimeBoundAttr
class LifetimeExtendedTemporaryDecl
Implicit declaration of a temporary that was materialized by a MaterializeTemporaryExpr and lifetime-extended by a declaration.
class LikelyAttr
struct LineEntry
class LineTableInfo
Used to hold and unique data used to represent #line information.
class LinkageComputer
class LinkageInfo
class LinkageSpecDecl
Represents a linkage specification.
class LiveVariables
class LoaderUninitializedAttr
class LocalInstantiationScope
A stack-allocated class that identifies which local variable declaration instantiations are present in this scope.
class LocationCheck
class LocationContext
It wraps the AnalysisDeclContext to represent both the call stack with the help of StackFrameContext and inside the function calls the BlockInvocationContext.
class LocationContextManager
class LocInfoType
Holds a QualType and a TypeSourceInfo* that came out of a declarator parsing.
class LockReturnedAttr
class LocksExcludedAttr
class LogDiagnosticPrinter
class LookupResult
Represents the results of name lookup.
class LoopExit
Represents a point when we exit a loop.
struct LoopHint
Loop optimization hint for loop and unroll pragmas.
class LoopHintAttr
class LTOVisibilityPublicAttr
class LValueReferenceType
An lvalue reference type, per C++11 [dcl.ref].
class LValueReferenceTypeLoc
struct LVComputationKind
Kinds of LV computation.
class MacroArgs
MacroArgs - An instance of this class captures information about the formal arguments specified to a function-like macro invocation.
class MacroBuilder
class MacroDefinition
A description of the current definition of a macro.
class MacroDefinitionRecord
Record the location of a macro definition.
class MacroDirective
Encapsulates changes to the "macros namespace" (the location where the macro name became active, the location where it was undefined, etc.).
class MacroExpansion
Records the location of a macro expansion.
class MacroInfo
Encapsulates the data about a macro definition (e.g.
class MacroPPCallbacks
struct MacroQualifiedLocInfo
class MacroQualifiedType
Sugar type that represents a type that was qualified by a qualifier written as a macro invocation.
class MacroQualifiedTypeLoc
class ManagedAnalysis
The base class of a hierarchy of objects representing analyses tied to AnalysisDeclContext.
class MangleContext
MangleContext - Context for tracking state which persists across multiple calls to the C++ name mangler.
class MangleNumberingContext
Keeps track of the mangled names of lambda expressions and block literals within a particular context.
struct MatchingVariablePatternConstraint
Ensures that all clones reference variables in the same pattern.
class MaterializeTemporaryExpr
Represents a prvalue temporary that is written into memory so that a reference can bind to it.
class MatrixSubscriptExpr
MatrixSubscriptExpr - Matrix subscript expression for the MatrixType extension.
class MatrixType
Represents a matrix type, as defined in the Matrix Types clang extensions.
class MatrixTypeLoc
struct MatrixTypeLocInfo
class MaxFieldAlignmentAttr
class MayAliasAttr
class MemberExpr
MemberExpr - [C99 6.5.2.3] Structure and Union Members.
struct MemberExprNameQualifier
Extra data stored in some MemberExpr objects.
struct MemberPointerLocInfo
class MemberPointerType
A pointer to member type per C++ 8.3.3 - Pointers to members.
class MemberPointerTypeLoc
Wrapper for source info for member pointers.
class MemberSpecializationInfo
Provides information a specialization of a member of a class template, which may be a member function, static data member, member class or member enumeration.
class MemorizeStatCalls
A stat "cache" that can be used by FileManager to keep track of the results of stat() calls that occur throughout the execution of the front end.
class Mergeable
Provides common interface for the Decls that cannot be redeclared, but can be merged if the same declaration is brought in from multiple modules.
struct MethodVFTableLocation
class MicroMipsAttr
class MicrosoftMangleContext
class MicrosoftVTableContext
class MigratorOptions
class MIGServerRoutineAttr
class MinComplexityConstraint
Ensures that every clone has at least the given complexity.
class MinGroupSizeConstraint
Ensures that all clone groups contain at least the given amount of clones.
class MinSizeAttr
class MinVectorWidthAttr
class Mips16Attr
class MipsInterruptAttr
class MipsLongCallAttr
class MipsShortCallAttr
struct MMToken
A token in a module map file.
class ModeAttr
class Module
Describes a module or submodule.
class ModuleDependencyCollector
Collects the dependencies for imported modules into a directory.
class ModuleFileExtension
An abstract superclass that describes a custom extension to the module/precompiled header file format.
struct ModuleFileExtensionMetadata
Metadata for a module file extension.
class ModuleFileExtensionReader
Abstract base class that reads a module file extension block from a module file.
class ModuleFileExtensionWriter
Abstract base class that writes a module file extension block into a module file.
class ModuleLoader
Abstract interface for a module loader.
class ModuleLoadResult
Describes the result of attempting to load a module.
class ModuleMacro
Represents a macro directive exported by a module.
class ModuleMap
class ModuleMapCallbacks
A mechanism to observe the actions of the module map parser as it reads module map files.
class ModuleMapParser
class MSABIAttr
class MSAllocatorAttr
class MSAsmStmt
This represents a Microsoft inline-assembly statement extension.
class MSDependentExistsStmt
Representation of a Microsoft __if_exists or __if_not_exists statement with a dependent name.
class MSGuidDecl
A global _GUID constant.
struct MSGuidDeclParts
Parts of a decomposed MSGuidDecl.
class MSInheritanceAttr
class MSNoVTableAttr
class MSP430InterruptAttr
class MSPropertyDecl
An instance of this class represents the declaration of a property member.
class MSPropertyRefExpr
A member reference to an MSPropertyDecl.
class MSPropertySubscriptExpr
MS property subscript expression.
class MSStructAttr
class MSVtorDispAttr
class MultiKeywordSelector
One of these variable length records is kept for each selector containing more than one keyword.
class MultiLevelTemplateArgumentList
Data structure that captures multiple levels of template argument lists for use in template instantiation.
class MultipleIncludeOpt
Implements the simple state machine that the Lexer class uses to detect files subject to the 'multiple-include' optimization.
class MultiplexASTDeserializationListener
class MultiplexASTMutationListener
class MultiplexConsumer
class MultiplexExternalSemaSource
An abstract interface that should be implemented by external AST sources that also provide information for semantic analysis.
class NakedAttr
class NamedDecl
This represents a decl that may have a name.
class NamespaceAliasDecl
Represents a C++ namespace alias.
class NamespaceDecl
Represent a C++ namespace.
class NeonTypeFlags
Flags to identify the types for overloaded Neon builtins.
class NestedNameSpecifier
Represents a C++ nested name specifier, such as "\::std::vector<int>::".
class NestedNameSpecifierLoc
A C++ nested-name-specifier augmented with source location information.
class NestedNameSpecifierLocBuilder
Class that aids in the construction of nested-name-specifiers along with source-location information for all of the components of the nested-name-specifier.
class NewAllocatedObjectConstructionContext
Represents immediate initialization of memory allocated by operator new, eg.
class NoAliasAttr
class NoBuiltinAttr
class NoCommonAttr
class NoDebugAttr
class NoDerefAttr
class NodeStreamer
class NoDestroyAttr
class NoDuplicateAttr
class NoEscapeAttr
class NoInitExpr
Represents a place-holder for an object not to be initialized by anything.
class NoInlineAttr
class NoInstrumentFunctionAttr
class NoMergeAttr
class NoMicroMipsAttr
class NoMips16Attr
class NonNullAttr
class NonTypeTemplateParmDecl
NonTypeTemplateParmDecl - Declares a non-type template parameter, e.g., "Size" in.
class NoReturnAttr
struct NormalizedConstraint
A normalized constraint, as defined in C++ [temp.constr.normal], is either an atomic constraint, a conjunction of normalized constraints or a disjunction of normalized constraints.
class NoSanitizeAttr
class NoSpeculativeLoadHardeningAttr
class NoSplitStackAttr
class NoStackProtectorAttr
class NoThreadSafetyAnalysisAttr
class NoThrowAttr
class NotTailCalledAttr
class NoTypoCorrectionCCC
class NoUniqueAddressAttr
class NSAPI
class NSConsumedAttr
class NSConsumesSelfAttr
class NSErrorDomainAttr
class NSReturnsAutoreleasedAttr
class NSReturnsNotRetainedAttr
class NSReturnsRetainedAttr
class NullStmt
NullStmt - This is the null statement ";": C99 6.8.3p3.
class NumericLiteralParser
NumericLiteralParser - This performs strict semantic analysis of the content of a ppnumber, classifying it as either integer, floating, or erroneous, determines the radix of the value and can convert it to a useful value.
class ObjCArrayLiteral
ObjCArrayLiteral - used for objective-c array containers; as in: @["Hello", NSApp, [NSNumber numberWithInt:42]];.
class ObjCAtCatchStmt
Represents Objective-C's @catch statement.
class ObjCAtDefsFieldDecl
Represents a field declaration created by an @defs(...).
class ObjCAtFinallyStmt
Represents Objective-C's @finally statement.
class ObjCAtSynchronizedStmt
Represents Objective-C's @synchronized statement.
class ObjCAtThrowStmt
Represents Objective-C's @throw statement.
class ObjCAtTryStmt
Represents Objective-C's @try ... @catch ... @finally statement.
class ObjCAutoreleasePoolStmt
Represents Objective-C's @autoreleasepool Statement.
class ObjCAvailabilityCheckExpr
A runtime availability query.
class ObjCBoolLiteralExpr
ObjCBoolLiteralExpr - Objective-C Boolean Literal.
class ObjCBoxableAttr
class ObjCBoxedExpr
ObjCBoxedExpr - used for generalized expression boxing.
class ObjCBridgeAttr
class ObjCBridgedCastExpr
An Objective-C "bridged" cast expression, which casts between Objective-C pointers and C pointers, transferring ownership in the process.
class ObjCBridgeMutableAttr
class ObjCBridgeRelatedAttr
class ObjCCategoryDecl
ObjCCategoryDecl - Represents a category declaration.
class ObjCCategoryImplDecl
ObjCCategoryImplDecl - An object of this class encapsulates a category @implementation declaration.
class ObjCClassStubAttr
class ObjCCompatibleAliasDecl
ObjCCompatibleAliasDecl - Represents alias of a class.
class ObjCContainerDecl
ObjCContainerDecl - Represents a container for method declarations.
class ObjCDeclSpec
Captures information about "declaration specifiers" specific to Objective-C.
class ObjCDesignatedInitializerAttr
struct ObjCDictionaryElement
An element in an Objective-C dictionary literal.
class ObjCDictionaryLiteral
ObjCDictionaryLiteral - AST node to represent objective-c dictionary literals; as in:"name" : NSUserName(), @"date" : [NSDate date] };.
struct ObjCDictionaryLiteral_ExpansionData
Internal struct to describes an element that is a pack expansion, used if any of the elements in the dictionary literal are pack expansions.
struct ObjCDictionaryLiteral_KeyValuePair
Internal struct for storing Key/value pair.
class ObjCDirectAttr
class ObjCDirectMembersAttr
class ObjCEncodeExpr
ObjCEncodeExpr, used for @encode in Objective-C.
class ObjCExceptionAttr
class ObjCExplicitProtocolImplAttr
class ObjCExternallyRetainedAttr
class ObjCForCollectionStmt
Represents Objective-C's collection statement.
class ObjCGCAttr
class ObjCImplDecl
class ObjCImplementationDecl
ObjCImplementationDecl - Represents a class definition - this is where method definitions are specified.
class ObjCIndependentClassAttr
class ObjCIndirectCopyRestoreExpr
ObjCIndirectCopyRestoreExpr - Represents the passing of a function argument by indirect copy-restore in ARC.
class ObjCInertUnsafeUnretainedAttr
class ObjCInterfaceDecl
Represents an ObjC class declaration.
struct ObjCInterfaceLocInfo
class ObjCInterfaceType
Interfaces are the core concept in Objective-C for object oriented design.
class ObjCInterfaceTypeLoc
Wrapper for source info for ObjC interfaces.
class ObjCIsaExpr
ObjCIsaExpr - Represent X->isa and X.isa when X is an ObjC 'id' type.
class ObjCIvarDecl
ObjCIvarDecl - Represents an ObjC instance variable.
class ObjCIvarRefExpr
ObjCIvarRefExpr - A reference to an ObjC instance variable.
class ObjCKindOfAttr
class ObjCList
ObjCList - This is a simple template class used to hold various lists of decls etc, which is heavily used by the ObjC front-end.
class ObjCListBase
class ObjCMessageExpr
An expression that sends a message to the given Objective-C object or class.
class ObjCMethodDecl
ObjCMethodDecl - Represents an instance or class method declaration.
class ObjCMethodFamilyAttr
struct ObjCMethodList
a linked list of methods with the same selector name but different signatures.
class ObjCNonLazyClassAttr
class ObjCNonRuntimeProtocolAttr
class ObjCNoReturn
class ObjCNSObjectAttr
class ObjCObjectPointerType
Represents a pointer to an Objective C object.
class ObjCObjectPointerTypeLoc
Wraps an ObjCPointerType with source location information.
class ObjCObjectType
Represents a class type in Objective C.
class ObjCObjectTypeImpl
A class providing a concrete implementation of ObjCObjectType, so as to not increase the footprint of ObjCInterfaceType.
class ObjCObjectTypeLoc
struct ObjCObjectTypeLocInfo
class ObjCOwnershipAttr
class ObjCPreciseLifetimeAttr
class ObjCPropertyDecl
Represents one property declaration in an Objective-C interface.
class ObjCPropertyImplDecl
ObjCPropertyImplDecl - Represents implementation declaration of a property in a class or category implementation block.
class ObjCPropertyRefExpr
ObjCPropertyRefExpr - A dot-syntax expression to access an ObjC property.
class ObjCProtocolDecl
Represents an Objective-C protocol declaration.
class ObjCProtocolExpr
ObjCProtocolExpr used for protocol expression in Objective-C.
class ObjCProtocolList
A list of Objective-C protocols, along with the source locations at which they were referenced.
class ObjCProtocolQualifiers
This class wraps the list of protocol qualifiers.
class ObjCRequiresPropertyDefsAttr
class ObjCRequiresSuperAttr
class ObjCReturnsInnerPointerAttr
class ObjCRootClassAttr
class ObjCRuntime
The basic abstraction for the target Objective-C runtime.
class ObjCRuntimeNameAttr
class ObjCRuntimeVisibleAttr
class ObjCSelectorExpr
ObjCSelectorExpr used for @selector in Objective-C.
class ObjCStringLiteral
ObjCStringLiteral, used for Objective-C string literals i.e.
class ObjCSubclassingRestrictedAttr
class ObjCSubscriptRefExpr
ObjCSubscriptRefExpr - used for array and dictionary subscripting.
class ObjCTypeParamDecl
Represents the declaration of an Objective-C type parameter.
class ObjCTypeParamList
Stores a list of Objective-C type parameters for a parameterized class or a category/extension thereof.
class ObjCTypeParamType
Represents a type parameter type in Objective C.
class ObjCTypeParamTypeLoc
ProtocolLAngleLoc, ProtocolRAngleLoc, and the source locations for protocol qualifiers are stored after Info.
struct ObjCTypeParamTypeLocInfo
class ObjectFilePCHContainerReader
A PCHContainerReader implementation that uses LLVM to wraps Clang modules inside a COFF, ELF, or Mach-O container.
class ObjectFilePCHContainerWriter
A PCHContainerWriter implementation that uses LLVM to wraps Clang modules inside a COFF, ELF, or Mach-O container.
class ODRHash
class OffsetOfExpr
OffsetOfExpr - [C99 7.17] - This represents an expression of the form offsetof(record-type, member-designator).
class OffsetOfNode
Helper class for OffsetOfExpr.
class OMPAcqRelClause
This represents 'acq_rel' clause in the '#pragma omp atomic|flush' directives.
class OMPAcquireClause
This represents 'acquire' clause in the '#pragma omp atomic|flush' directives.
class OMPAffinityClause
This represents clause 'affinity' in the '#pragma omp task'-based directives.
class OMPAlignedClause
This represents clause 'aligned' in the '#pragma omp ...' directives.
class OMPAllocateClause
This represents clause 'allocate' in the '#pragma omp ...' directives.
class OMPAllocateDecl
This represents '#pragma omp allocate ...' directive.
class OMPAllocateDeclAttr
class OMPAllocatorClause
This represents 'allocator' clause in the '#pragma omp ...' directive.
class OMPArraySectionExpr
OpenMP 5.0 [2.1.5, Array Sections].
class OMPArrayShapingExpr
An explicit cast in C or a C-style cast in C++, which uses the syntax ([s1][s2]...[sn])expr.
class OMPAtomicDefaultMemOrderClause
This represents 'atomic_default_mem_order' clause in the '#pragma omp requires' directive.
class OMPAtomicDirective
This represents '#pragma omp atomic' directive.
class OMPBarrierDirective
This represents '#pragma omp barrier' directive.
class OMPCancelDirective
This represents '#pragma omp cancel' directive.
class OMPCancellationPointDirective
This represents '#pragma omp cancellation point' directive.
class OMPCaptureClause
This represents 'capture' clause in the '#pragma omp atomic' directive.
class OMPCapturedExprDecl
Pseudo declaration for capturing expressions.
class OMPCaptureKindAttr
class OMPCaptureNoInitAttr
class OMPChildren
Contains data for OpenMP directives: clauses, children expressions/statements (helpers for codegen) and associated statement, if any.
class OMPClause
This is a basic class for representing single OpenMP clause.
class OMPClauseMappableExprCommon
Struct that defines common infrastructure to handle mappable expressions used in OpenMP clauses.
class OMPClausePrinter
class OMPClauseReader
class OMPClauseVisitor
class OMPClauseVisitorBase
This class implements a simple visitor for OMPClause subclasses.
class OMPClauseWithPostUpdate
Class that handles post-update expression for some clauses, like 'lastprivate', 'reduction' etc.
class OMPClauseWithPreInit
Class that handles pre-initialization statement for some clauses, like 'shedule', 'firstprivate' etc.
class OMPCollapseClause
This represents 'collapse' clause in the '#pragma omp ...' directive.
class OMPCopyinClause
This represents clause 'copyin' in the '#pragma omp ...' directives.
class OMPCopyprivateClause
This represents clause 'copyprivate' in the '#pragma omp ...' directives.
class OMPCriticalDirective
This represents '#pragma omp critical' directive.
class OMPDeclarativeDirective
This is a basic class for representing single OpenMP declarative directive.
class OMPDeclareMapperDecl
This represents '#pragma omp declare mapper ...' directive.
class OMPDeclareReductionDecl
This represents '#pragma omp declare reduction ...' directive.
class OMPDeclareSimdDeclAttr
class OMPDeclareTargetDeclAttr
class OMPDeclareVariantAttr
class OMPDefaultClause
This represents 'default' clause in the '#pragma omp ...' directive.
class OMPDefaultmapClause
This represents 'defaultmap' clause in the '#pragma omp ...' directive.
class OMPDependClause
This represents implicit clause 'depend' for the '#pragma omp task' directive.
class OMPDepobjClause
This represents implicit clause 'depobj' for the '#pragma omp depobj' directive.
class OMPDepobjDirective
This represents '#pragma omp depobj' directive.
class OMPDestroyClause
This represents 'destroy' clause in the '#pragma omp depobj' directive.
class OMPDetachClause
This represents 'detach' clause in the '#pragma omp task' directive.
class OMPDeviceClause
This represents 'device' clause in the '#pragma omp ...' directive.
class OMPDistributeDirective
This represents '#pragma omp distribute' directive.
class OMPDistributeParallelForDirective
This represents '#pragma omp distribute parallel for' composite directive.
class OMPDistributeParallelForSimdDirective
This represents '#pragma omp distribute parallel for simd' composite directive.
class OMPDistributeSimdDirective
This represents '#pragma omp distribute simd' composite directive.
class OMPDistScheduleClause
This represents 'dist_schedule' clause in the '#pragma omp ...' directive.
class OMPDynamicAllocatorsClause
This represents 'dynamic_allocators' clause in the '#pragma omp requires' directive.
class OMPExclusiveClause
This represents clause 'exclusive' in the '#pragma omp scan' directive.
class OMPExecutableDirective
This is a basic class for representing single OpenMP executable directive.
class OMPFinalClause
This represents 'final' clause in the '#pragma omp ...' directive.
class OMPFirstprivateClause
This represents clause 'firstprivate' in the '#pragma omp ...' directives.
class OMPFlushClause
This represents implicit clause 'flush' for the '#pragma omp flush' directive.
class OMPFlushDirective
This represents '#pragma omp flush' directive.
class OMPForDirective
This represents '#pragma omp for' directive.
class OMPForSimdDirective
This represents '#pragma omp for simd' directive.
class OMPFromClause
This represents clause 'from' in the '#pragma omp ...' directives.
class OMPGrainsizeClause
This represents 'grainsize' clause in the '#pragma omp ...' directive.
class OMPHintClause
This represents 'hint' clause in the '#pragma omp ...' directive.
class OMPIfClause
This represents 'if' clause in the '#pragma omp ...' directive.
class OMPInclusiveClause
This represents clause 'inclusive' in the '#pragma omp scan' directive.
class OMPInReductionClause
This represents clause 'in_reduction' in the '#pragma omp task' directives.
class OMPIsDevicePtrClause
This represents clause 'is_device_ptr' in the '#pragma omp ...' directives.
class OMPIteratorExpr
OpenMP 5.0 [2.1.6 Iterators] Iterators are identifiers that expand to multiple values in the clause on which they appear.
struct OMPIteratorHelperData
Helper expressions and declaration for OMPIteratorExpr class for each iteration space.
class OMPLastprivateClause
This represents clause 'lastprivate' in the '#pragma omp ...' directives.
class OMPLinearClause
This represents clause 'linear' in the '#pragma omp ...' directives.
class OMPLoopDirective
This is a common base class for loop directives ('omp simd', 'omp for', 'omp for simd' etc.).
class OMPMapClause
This represents clause 'map' in the '#pragma omp ...' directives.
class OMPMappableExprListClause
This represents clauses with a list of expressions that are mappable.
struct OMPMappableExprListSizeTy
This structure contains all sizes needed for by an OMPMappableExprListClause.
class OMPMasterDirective
This represents '#pragma omp master' directive.
class OMPMasterTaskLoopDirective
This represents '#pragma omp master taskloop' directive.
class OMPMasterTaskLoopSimdDirective
This represents '#pragma omp master taskloop simd' directive.
class OMPMergeableClause
This represents 'mergeable' clause in the '#pragma omp ...' directive.
class OMPNogroupClause
This represents 'nogroup' clause in the '#pragma omp ...' directive.
class OMPNontemporalClause
This represents clause 'nontemporal' in the '#pragma omp ...' directives.
class OMPNowaitClause
This represents 'nowait' clause in the '#pragma omp ...' directive.
class OMPNumTasksClause
This represents 'num_tasks' clause in the '#pragma omp ...' directive.
class OMPNumTeamsClause
This represents 'num_teams' clause in the '#pragma omp ...' directive.
class OMPNumThreadsClause
This represents 'num_threads' clause in the '#pragma omp ...' directive.
class OMPOrderClause
This represents 'order' clause in the '#pragma omp ...' directive.
class OMPOrderedClause
This represents 'ordered' clause in the '#pragma omp ...' directive.
class OMPOrderedDirective
This represents '#pragma omp ordered' directive.
class OMPParallelDirective
This represents '#pragma omp parallel' directive.
class OMPParallelForDirective
This represents '#pragma omp parallel for' directive.
class OMPParallelForSimdDirective
This represents '#pragma omp parallel for simd' directive.
class OMPParallelMasterDirective
This represents '#pragma omp parallel master' directive.
class OMPParallelMasterTaskLoopDirective
This represents '#pragma omp parallel master taskloop' directive.
class OMPParallelMasterTaskLoopSimdDirective
This represents '#pragma omp parallel master taskloop simd' directive.
class OMPParallelSectionsDirective
This represents '#pragma omp parallel sections' directive.
class OMPPriorityClause
This represents 'priority' clause in the '#pragma omp ...' directive.
class OMPPrivateClause
This represents clause 'private' in the '#pragma omp ...' directives.
class OMPProcBindClause
This represents 'proc_bind' clause in the '#pragma omp ...' directive.
class OMPReadClause
This represents 'read' clause in the '#pragma omp atomic' directive.
class OMPReductionClause
This represents clause 'reduction' in the '#pragma omp ...' directives.
class OMPReferencedVarAttr
class OMPRelaxedClause
This represents 'relaxed' clause in the '#pragma omp atomic' directives.
class OMPReleaseClause
This represents 'release' clause in the '#pragma omp atomic|flush' directives.
class OMPRequiresDecl
This represents '#pragma omp requires...' directive.
class OMPReverseOffloadClause
This represents 'reverse_offload' clause in the '#pragma omp requires' directive.
class OMPSafelenClause
This represents 'safelen' clause in the '#pragma omp ...' directive.
class OMPScanDirective
This represents '#pragma omp scan' directive.
class OMPScheduleClause
This represents 'schedule' clause in the '#pragma omp ...' directive.
class OMPSectionDirective
This represents '#pragma omp section' directive.
class OMPSectionsDirective
This represents '#pragma omp sections' directive.
class OMPSeqCstClause
This represents 'seq_cst' clause in the '#pragma omp atomic' directive.
class OMPSharedClause
This represents clause 'shared' in the '#pragma omp ...' directives.
class OMPSIMDClause
This represents 'simd' clause in the '#pragma omp ...' directive.
class OMPSimdDirective
This represents '#pragma omp simd' directive.
class OMPSimdlenClause
This represents 'simdlen' clause in the '#pragma omp ...' directive.
class OMPSingleDirective
This represents '#pragma omp single' directive.
class OMPTargetDataDirective
This represents '#pragma omp target data' directive.
class OMPTargetDirective
This represents '#pragma omp target' directive.
class OMPTargetEnterDataDirective
This represents '#pragma omp target enter data' directive.
class OMPTargetExitDataDirective
This represents '#pragma omp target exit data' directive.
class OMPTargetParallelDirective
This represents '#pragma omp target parallel' directive.
class OMPTargetParallelForDirective
This represents '#pragma omp target parallel for' directive.
class OMPTargetParallelForSimdDirective
This represents '#pragma omp target parallel for simd' directive.
class OMPTargetSimdDirective
This represents '#pragma omp target simd' directive.
class OMPTargetTeamsDirective
This represents '#pragma omp target teams' directive.
class OMPTargetTeamsDistributeDirective
This represents '#pragma omp target teams distribute' combined directive.
class OMPTargetTeamsDistributeParallelForDirective
This represents '#pragma omp target teams distribute parallel for' combined directive.
class OMPTargetTeamsDistributeParallelForSimdDirective
This represents '#pragma omp target teams distribute parallel for simd' combined directive.
class OMPTargetTeamsDistributeSimdDirective
This represents '#pragma omp target teams distribute simd' combined directive.
class OMPTargetUpdateDirective
This represents '#pragma omp target update' directive.
class OMPTaskDirective
This represents '#pragma omp task' directive.
class OMPTaskgroupDirective
This represents '#pragma omp taskgroup' directive.
class OMPTaskLoopDirective
This represents '#pragma omp taskloop' directive.
class OMPTaskLoopSimdDirective
This represents '#pragma omp taskloop simd' directive.
class OMPTaskReductionClause
This represents clause 'task_reduction' in the '#pragma omp taskgroup' directives.
class OMPTaskwaitDirective
This represents '#pragma omp taskwait' directive.
class OMPTaskyieldDirective
This represents '#pragma omp taskyield' directive.
class OMPTeamsDirective
This represents '#pragma omp teams' directive.
class OMPTeamsDistributeDirective
This represents '#pragma omp teams distribute' directive.
class OMPTeamsDistributeParallelForDirective
This represents '#pragma omp teams distribute parallel for' composite directive.
class OMPTeamsDistributeParallelForSimdDirective
This represents '#pragma omp teams distribute parallel for simd' composite directive.
class OMPTeamsDistributeSimdDirective
This represents '#pragma omp teams distribute simd' combined directive.
class OMPThreadLimitClause
This represents 'thread_limit' clause in the '#pragma omp ...' directive.
class OMPThreadPrivateDecl
This represents '#pragma omp threadprivate ...' directive.
class OMPThreadPrivateDeclAttr
class OMPThreadsClause
This represents 'threads' clause in the '#pragma omp ...' directive.
class OMPToClause
This represents clause 'to' in the '#pragma omp ...' directives.
class OMPTraitInfo
Helper data structure representing the traits in a match clause of an declare variant or metadirective.
struct OMPTraitProperty
struct OMPTraitSelector
struct OMPTraitSet
class OMPUnifiedAddressClause
This represents 'unified_address' clause in the '#pragma omp requires' directive.
class OMPUnifiedSharedMemoryClause
This represents 'unified_shared_memory' clause in the '#pragma omp requires' directive.
class OMPUntiedClause
This represents 'untied' clause in the '#pragma omp ...' directive.
class OMPUpdateClause
This represents 'update' clause in the '#pragma omp atomic' directive.
class OMPUseDeviceAddrClause
This represents clause 'use_device_addr' in the '#pragma omp ...' directives.
class OMPUseDevicePtrClause
This represents clause 'use_device_ptr' in the '#pragma omp ...' directives.
class OMPUsesAllocatorsClause
This represents clause 'uses_allocators' in the '#pragma omp target'-based directives.
class OMPVarListClause
This represents clauses with the list of variables like 'private', 'firstprivate', 'copyin', 'shared', or 'reduction' clauses in the '#pragma omp ...' directives.
struct OMPVarListLocTy
This structure contains most locations needed for by an OMPVarListClause.
class OMPWriteClause
This represents 'write' clause in the '#pragma omp atomic' directive.
struct OnlyLargestCloneConstraint
Ensures that no clone group fully contains another clone group.
class OpaquePtr
Wrapper for void* pointer.
class OpaqueValueExpr
OpaqueValueExpr - An expression referring to an opaque object of a fixed type and value class.
class OpenCLAccessAttr
class OpenCLConstantAddressSpaceAttr
class OpenCLGenericAddressSpaceAttr
class OpenCLGlobalAddressSpaceAttr
class OpenCLGlobalDeviceAddressSpaceAttr
class OpenCLGlobalHostAddressSpaceAttr
class OpenCLIntelReqdSubGroupSizeAttr
class OpenCLKernelAttr
class OpenCLLocalAddressSpaceAttr
class OpenCLOptions
OpenCL supported extensions and optional core features.
class OpenCLPrivateAddressSpaceAttr
class OpenCLUnrollHintAttr
struct OpenMPScheduleTy
Scheduling data for loop-based OpenMP directives.
class OptimizeNoneAttr
class OptionalDiagnostic
A partial diagnostic which we might know in advance that we are not going to emit.
class OptionalDirectoryEntryRefDegradesToDirectoryEntryPtr
Wrapper around Optional<DirectoryEntryRef> that degrades to 'const DirectoryEntry*', facilitating incremental patches to propagate DirectoryEntryRef.
class OptionalFileEntryRefDegradesToFileEntryPtr
Wrapper around Optional<FileEntryRef> that degrades to 'const FileEntry*', facilitating incremental patches to propagate FileEntryRef.
class OSConsumedAttr
class OSConsumesThisAttr
class OSReturnsNotRetainedAttr
class OSReturnsRetainedAttr
class OSReturnsRetainedOnNonZeroAttr
class OSReturnsRetainedOnZeroAttr
class OverloadableAttr
struct OverloadCandidate
OverloadCandidate - A single candidate in an overload set (C++ 13.3).
class OverloadCandidateSet
OverloadCandidateSet - A set of overload candidates, used in C++ overload resolution (C++ 13.3).
class OverloadedTemplateStorage
A structure for storing the information associated with an overloaded template name.
class OverloadExpr
A reference to an overloaded function set, either an UnresolvedLookupExpr or an UnresolvedMemberExpr.
class OverrideAttr
class OverridingMethods
The set of methods that override a given virtual method in each subobject where it occurs.
class OwnerAttr
class OwnershipAttr
class PackedAttr
class PackExpansionExpr
Represents a C++11 pack expansion that produces a sequence of expressions.
class PackExpansionType
Represents a pack expansion of types.
class PackExpansionTypeLoc
struct PackExpansionTypeLocInfo
class ParameterABIAttr
A parameter attribute which changes the argument-passing ABI rule for the parameter.
class ParamIdx
A single parameter index whose accessors require each use to make explicit the parameter index encoding needed.
class ParamTypestateAttr
class ParenBraceBracketBalancer
RAII object that makes sure paren/bracket/brace count is correct after declaration/statement parsing, even when there's a parsing error.
class ParenExpr
ParenExpr - This represents a parethesized expression, e.g.
class ParenListExpr
struct ParenLocInfo
class ParentMap
class ParentMapContext
class ParenType
Sugar for parentheses used when specifying types.
class ParenTypeLoc
class ParmVarDecl
Represents a parameter to a function.
class ParsedAttr
ParsedAttr - Represents a syntactic attribute.
class ParsedAttributes
ParsedAttributes - A collection of parsed attributes.
class ParsedAttributesView
struct ParsedAttrInfo
struct ParsedSourceLocation
A source location that has been parsed on the command line.
struct ParsedSourceRange
A source range that has been parsed on the command line.
struct ParsedTargetAttr
Contains information gathered from parsing the contents of TargetAttr.
class ParsedTemplateArgument
Represents the parsed form of a C++ template argument.
class Parser
Parser - This implements a parser for the C family of languages.
class ParsingDeclarator
A class for parsing a declarator.
class ParsingDeclRAIIObject
RAII object used to inform the actions that we're currently parsing a declaration.
class ParsingDeclSpec
A class for parsing a DeclSpec.
class ParsingFieldDeclarator
A class for parsing a field declarator.
class ParsingOpenMPDirectiveRAII
Activates OpenMP parsing mode to preseve OpenMP specific annotation tokens.
class PartialDiagnostic
class PascalAttr
class PassObjectSizeAttr
class PatchableFunctionEntryAttr
struct PCHBuffer
class PCHContainerOperations
A registry of PCHContainerWriter and -Reader objects for different formats.
class PCHContainerReader
This abstract interface provides operations for unwrapping containers for serialized ASTs (precompiled headers and clang modules).
class PCHContainerWriter
This abstract interface provides operations for creating containers for serialized ASTs (precompiled headers and clang modules).
class PCHGenerator
AST and semantic-analysis consumer that generates a precompiled header from the parsed source code.
class PCHValidator
ASTReaderListener implementation to validate the information of the PCH file against an initialized Preprocessor.
class PcsAttr
class PipeType
PipeType - OpenCL20.
class PipeTypeLoc
struct PipeTypeLocInfo
class PluginASTAction
class PointerAttr
struct PointerLikeLocInfo
class PointerLikeTypeLoc
A base class for.
class PointerType
PointerType - C99 6.7.5.1 - Pointer Declarators.
class PointerTypeLoc
Wrapper for source info for pointers.
class PoisonIdentifierRAIIObject
An RAII object for [un]poisoning an identifier within a scope.
class PoisonSEHIdentifiersRAIIObject
class PostAllocatorCall
class PostCondition
class PostImplicitCall
Represents a program point just after an implicit call event.
class PostInitializer
class PostLoad
class PostLValue
class PostOrderCFGView
class PostStmt
class PostStmtPurgeDeadSymbols
Represents a point after we ran remove dead bindings AFTER processing the given statement.
class PostStore
Represents a program point after a store evaluation.
class PPCallbacks
This interface provides a way to observe the actions of the preprocessor as it does its thing.
class PPChainedCallbacks
Simple wrapper class for chaining callbacks.
class PPConditionalDirectiveRecord
Records preprocessor conditional directive regions and allows querying in which region source locations belong to.
struct PPConditionalInfo
Information about the conditional stack (#if directives) currently active.
class PragmaClangBSSSectionAttr
class PragmaClangDataSectionAttr
class PragmaClangRelroSectionAttr
class PragmaClangRodataSectionAttr
class PragmaClangTextSectionAttr
class PragmaCommentDecl
Represents a #pragma comment line.
class PragmaDetectMismatchDecl
Represents a #pragma detect_mismatch line.
class PragmaHandler
PragmaHandler - Instances of this interface defined to handle the various pragmas that the language front-end uses.
struct PragmaIntroducer
Describes how and where the pragma was introduced.
class PragmaNamespace
PragmaNamespace - This PragmaHandler subdivides the namespace of pragmas, allowing hierarchical pragmas to be defined.
struct PreambleBounds
Describes the bounds (start, size) of the preamble and a flag required by PreprocessorOptions::PrecompiledPreambleBytes.
class PreambleCallbacks
A set of callbacks to gather useful information while building a preamble.
class PrecompiledPreamble
A class holding a PCH and all information to check whether it is valid to reuse the PCH for the subsequent runs.
class PredefinedExpr
[C99 6.4.2.2] - A predefined identifier such as func.
class PreferredNameAttr
class PreferredTypeBuilder
Keeps track of expected type during expression parsing.
class PreImplicitCall
Represents a program point just before an implicit call event.
class PreLoad
class PreprocessedEntity
Base class that describes a preprocessed entity, which may be a preprocessor directive or macro expansion.
class PreprocessingDirective
Records the presence of a preprocessor directive.
class PreprocessingRecord
A record of the steps taken while preprocessing a source file, including the various preprocessing directives processed, macros expanded, etc.
class PreprocessOnlyAction
class Preprocessor
Engages in a tight little dance with the lexer to efficiently preprocess tokens.
class PreprocessorFrontendAction
Abstract base class to use for preprocessor-based frontend actions.
class PreprocessorLexer
class PreprocessorOptions
PreprocessorOptions - This class is used for passing the various options used in preprocessor initialization to InitializePreprocessor().
class PreprocessorOutputOptions
PreprocessorOutputOptions - Options for controlling the C preprocessor output (e.g., -E).
class PreserveAllAttr
class PreserveMostAttr
class PreStmt
class PreStmtPurgeDeadSymbols
Represents a point after we ran remove dead bindings BEFORE processing the given statement.
class PreStore
class PresumedLoc
Represents an unpacked "presumed" location which can be presented to the user.
class PrettyDeclStackTraceEntry
PrettyDeclStackTraceEntry - If a crash occurs in the parser while parsing something related to a declaration, include that declaration in the stack trace.
class PrettyStackTraceDecl
PrettyStackTraceDecl - If a crash occurs, indicate that it happened when doing something to a specific decl.
class PrettyStackTraceLoc
If a crash happens while one of these objects are live, the message is printed out along with the specified source location.
class PrintDependencyDirectivesSourceMinimizerAction
class PrinterHelper
class PrintingCallbacks
Callbacks to use to customize the behavior of the pretty-printer.
class PrintingCodeCompleteConsumer
A simple code-completion consumer that prints the results it receives in a simple format.
struct PrintingPolicy
Describes how types, statements, expressions, and declarations should be printed.
class PrintPreambleAction
class PrintPreprocessedAction
class ProfileList
class ProfileSpecialCaseList
class ProgramPoint
class ProgramPointTag
ProgramPoints can be "tagged" as representing points specific to a given analysis entity.
class PseudoDestructorTypeStorage
Stores the type being destroyed by a pseudo-destructor expression.
class PseudoObjectExpr
PseudoObjectExpr - An expression which accesses a pseudo-object l-value.
class PtGuardedByAttr
class PtGuardedVarAttr
class Ptr32Attr
class Ptr64Attr
class PureAttr
class QualifiedTemplateName
Represents a template name that was expressed as a qualified name.
class QualifiedTypeLoc
Wrapper of type source information for a type with non-trivial direct qualifiers.
class QualifierCollector
A qualifier set is used to build a set of qualifiers.
struct QualifierInfo
A struct with extended info about a syntactic name qualifier, to be used for the case of out-of-line declarations.
class Qualifiers
The collection of all-type qualifiers we support.
class QualType
A (possibly-)qualified type.
struct QualTypeOrdering
Function object that provides a total ordering on QualType values.
class RawComment
class RawCommentList
This class represents all comments included in the translation unit, sorted in order of appearance in the translation unit.
class RawPCHContainerReader
Implements read operations for a raw pass-through PCH container.
class RawPCHContainerWriter
Implements write operations for a raw pass-through PCH container.
class RecordDecl
Represents a struct/union/class.
class RecordType
A helper class that allows the use of isa/cast/dyncast to detect TagType objects of structs/unions/classes.
class RecordTypeLoc
Wrapper for source info for record types.
class RecoveryExpr
Frontend produces RecoveryExprs on semantic errors that prevent creating other well-formed expressions.
class RecursiveASTVisitor
A class that does preorder or postorder depth-first traversal on the entire Clang AST and visits each node.
class RecursiveCloneTypeIIHashConstraint
This constraint moves clones into clone groups of type II via hashing.
class RecursiveCloneTypeIIVerifyConstraint
This constraint moves clones into clone groups of type II by comparing them.
class Redeclarable
Provides common interface for the Decls that can be redeclared.
class RedeclarableTemplateDecl
Declaration of a redeclarable template.
class ReferenceType
Base for LValueReferenceType and RValueReferenceType.
class ReferenceTypeLoc
class RegCallAttr
class ReinitializesAttr
class RelaxedLiveVariables
class ReleaseCapabilityAttr
class ReleaseHandleAttr
class RenderScriptKernelAttr
class ReqdWorkGroupSizeAttr
class RequiresCapabilityAttr
class RequiresExpr
C++2a [expr.prim.req]: A requires-expression provides a concise way to express requirements on template arguments.
class RequiresExprBodyDecl
Represents the body of a requires-expression.
class RestrictAttr
struct ReturnAdjustment
A return adjustment.
class ReturnedValueConstructionContext
class ReturnsNonNullAttr
class ReturnStmt
ReturnStmt - This represents a return, optionally of an expression: return; return 4;.
class ReturnsTwiceAttr
class ReturnTypestateAttr
struct ReversePostOrderCompare
class RewriteBuffer
RewriteBuffer - As code is rewritten, SourceBuffer's from the original input with modifications get a new RewriteBuffer associated with them.
class RewriteIncludesAction
class RewriteMacrosAction
class RewriteObjCAction
class Rewriter
Rewriter - This is the main interface to the rewrite buffers.
class RewriteRope
RewriteRope - A powerful string class.
class RewriteTestAction
class RISCVInterruptAttr
struct RopePiece
RopePiece - This class represents a view into a RopeRefCountString object.
class RopePieceBTree
class RopePieceBTreeIterator
RopePieceBTreeIterator - This class provides read-only forward iteration over bytes that are in a RopePieceBTree.
struct RopeRefCountString
RopeRefCountString - This struct is allocated with 'new char[]' from the heap, and represents a reference counted chunk of string data.
class RValueReferenceType
An rvalue reference type, per C++11 [dcl.ref].
class RValueReferenceTypeLoc
class SanitizerBlacklist
struct SanitizerKind
class SanitizerMask
struct SanitizerSet
class SanitizerSpecialCaseList
struct SavedStreamPosition
Helper class that saves the current stream position and then restores it when destroyed.
class Scope
Scope - A scope is a transient data structure that is used while parsing the program.
class ScopedLockableAttr
class ScratchBuffer
ScratchBuffer - This class exposes a simple interface for the dynamic construction of tokens.
class SectionAttr
class SEHExceptStmt
class SEHFinallyStmt
class SEHLeaveStmt
Represents a __leave statement.
class SEHTryStmt
class SelectAnyAttr
class Selector
Smart pointer class that efficiently represents Objective-C method names.
class SelectorTable
This table allows us to fully hide how we implement multi-keyword caching.
class Sema
Sema - This implements semantic analysis and AST building for C.
class SemaConsumer
An abstract interface that should be implemented by clients that read ASTs and then require further semantic analysis of the entities in those ASTs.
class SentinelAttr
class SetTypestateAttr
class SharedTrylockFunctionAttr
class ShuffleVectorExpr
ShuffleVectorExpr - clang-specific builtin-in function __builtin_shufflevector.
class SimpleASTReaderListener
ASTReaderListenter implementation to set SuggestedPredefines of ASTReader which is required to use a pch file.
class SimpleConstructorInitializerConstructionContext
Represents construction into a field or a base class within a bigger object via a constructor initializer, eg.
class SimpleProgramPointTag
class SimpleReturnedValueConstructionContext
Represents a temporary object that is being immediately returned from a function by value, eg.
class SimpleTemporaryObjectConstructionContext
Represents a temporary object that is not constructed for the purpose of being immediately copied/moved by an elidable copy/move-constructor.
class SimpleVariableConstructionContext
Represents construction into a simple local variable, eg.
class SizeOfPackExpr
Represents an expression that computes the length of a parameter pack.
struct SkippedRange
class SourceLocation
Encodes a location in the source.
class SourceLocExpr
Represents a function call to one of __builtin_LINE(), __builtin_COLUMN(), __builtin_FUNCTION(), or __builtin_FILE().
class SourceManager
This class handles loading and caching of source files into memory.
class SourceManagerForFile
SourceManager and necessary depdencies (e.g.
class SourceRange
A trivial tuple used to represent a source range.
class specific_attr_iterator
specific_attr_iterator - Iterates over a subrange of an AttrVec, only providing attributes that are of a specific type.
class SpeculativeLoadHardeningAttr
struct SplitQualType
A std::pair-like structure for storing a qualified type split into its local qualifiers and its locally-unqualified type.
class SPtrAttr
class StackFrameContext
It represents a stack frame of the call stack (based on CallEvent).
class StandardConversionSequence
StandardConversionSequence - represents a standard conversion sequence (C++ 13.3.3.1.1).
class StaticAssertDecl
Represents a C++11 static_assert declaration.
class StdCallAttr
class Stmt
Stmt - This represents one statement.
class StmtAttr
class StmtExpr
StmtExpr - This is the GNU Statement Expression extension: ({int X=4; X;}).
struct StmtIterator
class StmtIteratorBase
class StmtIteratorImpl
class StmtPoint
class StmtSequence
Identifies a list of statements.
class StmtVisitor
StmtVisitor - This class implements a simple visitor for Stmt subclasses.
class StmtVisitorBase
StmtVisitorBase - This class implements a simple visitor for Stmt subclasses.
struct StoredDeclsList
An array of decls optimized for the common case of only containing one entry.
class StoredDeclsMap
class StoredDiagnostic
Represents a diagnostic in a form that can be retained until its corresponding source manager is destroyed.
class StreamingDiagnostic
The streaming interface shared between DiagnosticBuilder and PartialDiagnostic.
class StrictFPAttr
class StringLiteral
StringLiteral - This represents a string literal expression, e.g.
class StringLiteralParser
StringLiteralParser - This decodes string escape characters and performs wide string analysis and Translation Phase #6 (concatenation of string literals) (C99 5.1.1.2p1).
class StringSizerHelper
struct StructuralEquivalenceContext
struct SubobjectAdjustment
An adjustment to be made to the temporary created when emitting a reference binding, which accesses a particular subobject of that temporary.
class SubstNonTypeTemplateParmExpr
Represents a reference to a non-type template parameter that has been substituted with a template argument.
class SubstNonTypeTemplateParmPackExpr
Represents a reference to a non-type template parameter pack that has been substituted with a non-template argument pack.
class SubstTemplateTemplateParmPackStorage
A structure for storing an already-substituted template template parameter pack.
class SubstTemplateTemplateParmStorage
A structure for storing the information associated with a substituted template template parameter.
class SubstTemplateTypeParmPackType
Represents the result of substituting a set of types for a template type parameter pack.
class SubstTemplateTypeParmPackTypeLoc
Wrapper for substituted template type parameters.
class SubstTemplateTypeParmType
Represents the result of substituting a type for a template type parameter.
class SubstTemplateTypeParmTypeLoc
Wrapper for substituted template type parameters.
class SuppressAccessChecks
A RAII object used to temporarily suppress access-like checking.
class SuppressAttr
class SVETypeFlags
Flags to identify the types for overloaded SVE builtins.
class SwiftAsyncAttr
class SwiftAsyncNameAttr
class SwiftAttrAttr
class SwiftBridgeAttr
class SwiftBridgedTypedefAttr
class SwiftCallAttr
class SwiftContextAttr
class SwiftErrorAttr
class SwiftErrorResultAttr
class SwiftIndirectResultAttr
class SwiftNameAttr
class SwiftNewTypeAttr
class SwiftObjCMembersAttr
class SwiftPrivateAttr
class SwitchCase
class SwitchStmt
SwitchStmt - This represents a 'switch' stmt.
class SYCLKernelAttr
class SyntaxOnlyAction
class SysVABIAttr
class TagDecl
Represents the declaration of a struct/union/class/enum.
class TagType
class TagTypeLoc
Wrapper for source info for tag types.
class TargetAttr
class TargetCXXABI
The basic abstraction for the target C++ ABI.
class TargetInfo
Exposes information about the current target.
struct TargetOMPContext
Clang specific specialization of the OMPContext to lookup target features.
class TargetOptions
Options for controlling the target.
class TemplateArgument
Represents a template argument.
class TemplateArgumentList
A template argument list.
class TemplateArgumentListInfo
A convenient class for passing around template argument information.
class TemplateArgumentLoc
Location wrapper for a TemplateArgument.
class TemplateArgumentLocContainerIterator
Simple iterator that traverses the template arguments in a container that provides a getArgLoc() member function.
struct TemplateArgumentLocInfo
Location information for a TemplateArgument.
class TemplateArgumentLocInventIterator
Iterator adaptor that invents template argument location information for each of the template arguments in its underlying iterator.
class TemplateArgumentVisitor
A simple visitor class that helps create template argument visitors.
class TemplateDecl
The base class of all kinds of template declarations (e.g., class, function, etc.).
class TemplateDeclInstantiator
struct TemplateDiffTypes
struct TemplateIdAnnotation
Information about a template-id annotation token.
class TemplateInstantiationCallback
This is a base class for callbacks that will be notified at every template instantiation.
class TemplateName
Represents a C++ template name within the type system.
struct TemplateNameLocInfo
class TemplateParameterList
Stores a list of template parameters for a TemplateDecl and its derived classes.
class TemplateParamObjectDecl
A template parameter object.
class TemplateParmPosition
Defines the position of a template parameter within a template parameter list.
class TemplatePartialOrderingContext
struct TemplateSpecCandidate
TemplateSpecCandidate - This is a generalization of OverloadCandidate which keeps track of template argument deduction failure info, when handling explicit specializations (and instantiations) of templates beyond function overloading.
class TemplateSpecCandidateSet
TemplateSpecCandidateSet - A set of generalized overload candidates, used in template specializations.
struct TemplateSpecializationLocInfo
class TemplateSpecializationType
Represents a type template specialization; the template must be a class template, a type alias template, or a template template parameter.
class TemplateSpecializationTypeLoc
class TemplateTemplateParmDecl
TemplateTemplateParmDecl - Declares a template template parameter, e.g., "T" in.
class TemplateTypeParmDecl
Declaration of a template type parameter.
class TemplateTypeParmType
class TemplateTypeParmTypeLoc
Wrapper for template type parameters.
class TemplightDumpAction
class TemporaryObjectConstructionContext
Represents a temporary object, eg.
struct TerminalColor
struct TestClangConfig
A Clang configuration for end-to-end tests that can be converted to command line arguments for the driver.
class TestModuleFileExtension
A module file extension used for testing purposes.
class TestTypestateAttr
class TextDiagnostic
Class to encapsulate the logic for formatting and printing a textual diagnostic message.
class TextDiagnosticBuffer
class TextDiagnosticPrinter
class TextNodeDumper
class TextTreeStructure
struct ThisAdjustment
A this pointer adjustment.
class ThisCallAttr
class ThreadAttr
struct ThunkInfo
The this pointer adjustment as well as an optional return adjustment for a thunk.
class TLSModelAttr
class Token
Token - This structure provides full information about a lexed token.
class TokenConcatenation
TokenConcatenation class, which answers the question of "Is it safe to emit two tokens without a whitespace between them, or would that cause implicit concatenation of the tokens?".
class TokenLexer
TokenLexer - This implements a lexer that returns tokens from a macro body or token stream instead of lexing from a character buffer.
class TokenRewriter
class TokenRole
class TokenValue
Stores token information for comparing actual tokens with predefined values.
struct TransferrableTargetInfo
Fields controlling how types are laid out in memory; these may need to be copied for targets like AMDGPU that base their ABIs on an auxiliary CPU target.
class TranslationUnitDecl
The top declaration context.
class TransparentUnionAttr
class TraversalKindScope
class TreeTransform
A semantic tree transformation that allows one to transform one abstract syntax tree into another.
class TrivialABIAttr
class TrivialModuleLoader
A module loader that doesn't know how to create or load modules.
class TryAcquireCapabilityAttr
class Type
The base class of the type hierarchy.
class TypeAliasDecl
Represents the declaration of a typedef-name via a C++11 alias-declaration.
class TypeAliasTemplateDecl
Declaration of an alias template.
class TypeAttr
class TypeConstraint
class TypeDecl
Represents a declaration of a type.
class TypedefDecl
Represents the declaration of a typedef-name via the 'typedef' type specifier.
class TypedefNameDecl
Base class for declarations which introduce a typedef-name.
class TypedefType
class TypedefTypeLoc
Wrapper for source info for typedefs.
struct TypeDependenceScope
struct TypeInfo
struct TypeInfoChars
class TypeInfoLValue
Symbolic representation of typeid(T) for some type T.
class TypeLoc
Base wrapper for a particular "section" of type source info.
class TypeLocBuilder
class TypeLocReader
class TypeLocVisitor
class TypeNonNullAttr
class TypeNullableAttr
class TypeNullableResultAttr
class TypeNullUnspecifiedAttr
class TypeOfExprType
Represents a typeof (or typeof) expression (a GCC extension).
class TypeOfExprTypeLoc
struct TypeOfExprTypeLocInfo
class TypeofLikeTypeLoc
struct TypeofLocInfo
class TypeOfType
Represents typeof(type), a GCC extension.
class TypeOfTypeLoc
struct TypeOfTypeLocInfo
class TypePropertyCache
The type-property cache.
class TypeSourceInfo
A container of type source information.
struct TypeSpecLocInfo
class TypeSpecTypeLoc
A reasonable base class for TypeLocs that correspond to types that are written as a type-specifier.
class TypeTagForDatatypeAttr
class TypeTraitExpr
A type trait used in the implementation of various C++11 and Library TR1 trait templates.
class TypeVisibilityAttr
class TypeVisitor
An operation on a type.
class TypeWithKeyword
A helper class for Type nodes having an ElaboratedTypeKeyword.
class TypoCorrection
Simple class containing the result of Sema::CorrectTypo.
class TypoCorrectionConsumer
class TypoExpr
TypoExpr - Internal placeholder for expressions where typo correction still needs to be performed and/or an error diagnostic emitted.
class UnaryExprOrTypeTraitExpr
UnaryExprOrTypeTraitExpr - expression with either a type or (unevaluated) expression operand.
class UnaryOperator
UnaryOperator - This represents the unary-expression's (except sizeof and alignof), the postinc/postdec operators from postfix-expression, and various extensions.
class UnaryTransformType
A unary type transform, which is a type constructed from another.
class UnaryTransformTypeLoc
struct UnaryTransformTypeLocInfo
class UnavailableAttr
class UncommonTemplateNameStorage
Implementation class used to describe either a set of overloaded template names or an already-substituted template template parameter pack.
class UndefMacroDirective
A directive for an undefined macro.
class UninitializedAttr
class UninitUse
A use of a variable, which might be uninitialized.
struct UninitVariablesAnalysisStats
class UninitVariablesHandler
struct UnionOpaquePtr
UnionOpaquePtr - A version of OpaquePtr suitable for membership in a union.
struct UniqueVirtualMethod
Uniquely identifies a virtual method within a class hierarchy by the method itself and a class subobject number.
class UnlikelyAttr
class UnqualifiedId
Represents a C++ unqualified-id that has been parsed.
class UnqualTypeLoc
Wrapper of type source information for a type with no direct qualifiers.
class UnresolvedLookupExpr
A reference to a name which we were able to look up during parsing but could not resolve to a specific declaration.
class UnresolvedMemberExpr
Represents a C++ member access expression for which lookup produced a set of overloaded functions.
class UnresolvedSet
A set of unresolved declarations.
class UnresolvedSetImpl
A set of unresolved declarations.
class UnresolvedSetIterator
The iterator over UnresolvedSets.
class UnresolvedUsingType
Represents the dependent type named by a dependently-scoped typename using declaration, e.g.
class UnresolvedUsingTypeLoc
Wrapper for source info for unresolved typename using decls.
class UnresolvedUsingTypenameDecl
Represents a dependent using declaration which was marked with typename.
class UnresolvedUsingValueDecl
Represents a dependent using declaration which was not marked with typename.
class UnusedAttr
class UpdateOnReturn
class UPtrAttr
class UsedAttr
class UsedDeclVisitor
class UseHandleAttr
struct UserDefinedConversionSequence
UserDefinedConversionSequence - Represents a user-defined conversion sequence (C++ 13.3.3.1.2).
class UserDefinedLiteral
A call to a literal operator (C++11 [over.literal]) written as a user-defined literal (C++11 [lit.ext]).
class UsingDecl
Represents a C++ using-declaration.
class UsingDirectiveDecl
Represents C++ using-directive.
class UsingPackDecl
Represents a pack of using declarations that a single using-declarator pack-expanded into.
class UsingShadowDecl
Represents a shadow declaration introduced into a scope by a (resolved) using declaration.
class UuidAttr
class VAArgExpr
Represents a call to the builtin function __builtin_va_arg.
class ValueDecl
Represent the declaration of a variable (in which case it is an lvalue) a function (in which case it is a function designator) or an enum constant.
class ValueStmt
Represents a statement that could possibly have a value and type.
class VAOptDefinitionContext
A class for tracking whether we're inside a VA_OPT during a traversal of the tokens of a variadic macro definition.
class VAOptExpansionContext
A class for tracking whether we're inside a VA_OPT during a traversal of the tokens of a macro during macro expansion.
class VarDecl
Represents a variable declaration or definition.
class VariableArrayType
Represents a C array with a specified size that is not an integer-constant-expression.
class VariableArrayTypeLoc
class VariableConstructionContext
An abstract base class for local variable constructors.
class VariablePattern
Analyzes the pattern of the referenced variables in a statement.
class VariadicMacroScopeGuard
An RAII class that tracks when the Preprocessor starts and stops lexing the definition of a (ISO C/C++) variadic macro.
class VarTemplateDecl
Declaration of a variable template.
class VarTemplatePartialSpecializationDecl
class VarTemplateSpecializationDecl
Represents a variable template specialization, which refers to a variable template with a given set of template arguments.
class VecReturnAttr
class VectorCallAttr
class VectorType
Represents a GCC generic vector type.
class VectorTypeLoc
struct VectorTypeLocInfo
class VecTypeHintAttr
class VerifyDiagnosticConsumer
VerifyDiagnosticConsumer - Create a diagnostic client which will use markers in the input source to check that all the emitted diagnostics match those expected.
class VerifyPCHAction
class VirtSpecifiers
Represents a C++11 virt-specifier-seq.
struct VirtualBaseInfo
All virtual base related information about a given record decl.
class VisibilityAttr
class VisibilityMacroDirective
A directive for setting the module visibility of a macro.
class VisibleDeclConsumer
Consumes visible declarations found when searching for all visible names within a given scope or context.
class VisibleModuleSet
A set of visible modules.
struct VPtrInfo
Holds information about the inheritance path to a virtual base or function table pointer.
class VTableComponent
Represents a single component in a vtable.
class VTableContextBase
class VTableLayout
class VTTBuilder
Class for building VTT layout information.
struct VTTComponent
class VTTVTable
class WarnUnusedAttr
class WarnUnusedResultAttr
class WeakAttr
class WeakImportAttr
class WeakInfo
Captures information about a #pragma weak directive.
class WeakRefAttr
class WebAssemblyExportNameAttr
class WebAssemblyImportModuleAttr
class WebAssemblyImportNameAttr
class WhileStmt
WhileStmt - This represents a 'while' stmt.
class WorkGroupSizeHintAttr
class WrapperFrontendAction
A frontend action which simply wraps some other runtime-specified frontend action.
struct WrittenBuiltinSpecs
Structure that packs information about the type specifiers that were written in a particular type specifier sequence.
class X86ForceAlignArgPointerAttr
class XRayFunctionFilter
struct XRayInstrSet
class XRayInstrumentAttr
class XRayLogArgsAttr
Typedefs
using DomTreeNode = llvm::DomTreeNodeBase<CFGBlock>
using CFGDomTree = CFGDominatorTreeImpl< false>
using CFGPostDomTree = CFGDominatorTreeImpl< true>
using UnsatisfiedConstraintRecord
Pairs of unsatisfied atomic constraint expressions along with the substituted constraint expr, if the template arguments could be substituted into them, or a diagnostic if substitution resulted in an invalid expression.
using AttrVec = SmallVector<Attr *, 4>
AttrVec - A vector of Attr, which is how they are stored on the AST.
using CanQualType = CanQual<Type>
Represents a canonical, potentially-qualified type.
using TemplateParameter
Stores a template parameter of any kind.
using ExprDependence = ExprDependenceScope::ExprDependence
using TypeDependence = TypeDependenceScope::TypeDependence
typedef SmallVector< CXXBaseSpecifier *, 4 > CXXCastPath
A simple array of base specifiers.
using ConstantExprKind = Expr::ConstantExprKind
using LazyDeclStmtPtr
A lazy pointer to a statement.
using LazyDeclPtr
A lazy pointer to a declaration.
using LazyCXXCtorInitializersPtr
A lazy pointer to a set of CXXCtorInitializers.
using LazyCXXBaseSpecifiersPtr
A lazy pointer to a set of CXXBaseSpecifiers.
template<typename T >
using const_ptr = std::add_pointer_t<std::add_const_t<T>>
template<typename T >
using TypeIsArrayType
typedef SmallVector< std::unique_ptr< VPtrInfo >, 2 > VPtrInfoVector
using LangASMap = unsigned[(unsigned)LangAS::FirstTargetAddressSpace]
The type of a lookup table which maps from language-specific address spaces to target-specific ones.
using DiagNullabilityKind = std::pair<NullabilityKind, bool>
A nullability kind paired with a bit indicating whether it used a context-sensitive keyword.
using TextDiagnosticFormat = DiagnosticOptions::TextDiagnosticFormat
using IdentifierLocPair = std::pair<IdentifierInfo *, SourceLocation>
A simple pair of identifier info and location.
using ModuleId = SmallVector<std::pair<std::string, SourceLocation>, 2>
Describes the name of a module.
using OpenMPDirectiveKind = llvm::omp::Directive
OpenMP directives.
using OpenMPClauseKind = llvm::omp::Clause
OpenMP clauses.
using PartialDiagnosticAt = std::pair<SourceLocation, PartialDiagnostic>
A partial diagnostic along with the source location where this diagnostic occurs.
using ModuleBuildStack = ArrayRef<std::pair<std::string, FullSourceLoc>>
The stack used when building modules on demand, which is used to provide a link between the source managers of the different compiler instances.
using XRayInstrMask = uint32_t
using DiagOrStoredDiag
using FrontendPluginRegistry = llvm::Registry<PluginASTAction>
The frontend plugin registry.
using ModuleIdPath = ArrayRef<std::pair<IdentifierInfo *, SourceLocation>>
A sequence of identifier/location pairs used to describe a particular module or submodule, e.g., std.vector.
using PragmaHandlerRegistry = llvm::Registry<PragmaHandler>
Registry of pragma handlers added by plugins.
using PreprocessorSkippedRangeMapping = llvm::DenseMap<unsigned, unsigned>
A mapping from an offset into a buffer to the number of bytes that can be skipped by the preprocessor when skipping over excluded conditional directive ranges.
using ExcludedPreprocessorDirectiveSkipMapping
The datastructure that holds the mapping between the active memory buffers and the individual skip mappings.
typedef SmallVector< Token, 4 > CachedTokens
A set of tokens that has been cached for later parsing.
using ConversionSequenceList
A list of implicit conversion sequences for the arguments of an OverloadCandidate.
using ParsedType = OpaquePtr<QualType>
An opaque type for threading parsed type information through the parser.
using UnionParsedType = UnionOpaquePtr<QualType>
using ExprResult = ActionResult<Expr *>
using StmtResult = ActionResult<Stmt *>
using TypeResult = ActionResult<ParsedType>
using BaseResult = ActionResult<CXXBaseSpecifier *>
using MemInitResult = ActionResult<CXXCtorInitializer *>
using DeclResult = ActionResult<Decl *>
using ParsedTemplateTy = OpaquePtr<TemplateName>
using UnionParsedTemplateTy = UnionOpaquePtr<TemplateName>
using MultiExprArg = MutableArrayRef<Expr *>
using MultiStmtArg = MutableArrayRef<Stmt *>
using ASTTemplateArgsPtr = MutableArrayRef<ParsedTemplateArgument>
using MultiTypeArg = MutableArrayRef<ParsedType>
using MultiTemplateParamsArg = MutableArrayRef<TemplateParameterList *>
typedef llvm::Registry< ParsedAttrInfo > ParsedAttrInfoRegistry
using ArgsUnion = llvm::PointerUnion<Expr *, IdentifierLoc *>
A union of the various pointer types that can be passed to an ParsedAttr as an argument.
using ArgsVector = llvm::SmallVector<ArgsUnion, 12U>
typedef std::pair< llvm::PointerUnion< const TemplateTypeParmType *, NamedDecl * >, SourceLocation > UnexpandedParameterPack
using AnalyzerOptionsRef = IntrusiveRefCntPtr<AnalyzerOptions>
using ExpectedType = llvm::Expected<QualType>
using ExpectedStmt = llvm::Expected<Stmt *>
using ExpectedExpr = llvm::Expected<Expr *>
using ExpectedDecl = llvm::Expected<Decl *>
using ExpectedSLoc = llvm::Expected<SourceLocation>
using ExpectedName = llvm::Expected<DeclarationName>
Enumerations
enum class NeverCalledReason {
IfThen , IfElse , Switch , SwitchSkipped ,
LoopEntered , LoopSkipped , FallbackReason , LARGEST_VALUE = FallbackReason
}
enum ASTDumpOutputFormat { ADOF_Default , ADOF_JSON }
Used to specify the format for printing AST dump information.
enum class StructuralEquivalenceKind { Default , Minimal }
Whether to perform a normal or minimal equivalence check.
enum TraversalKind { TK_AsIs , TK_IgnoreUnlessSpelledInSource }
Defines how we descend a level in the AST when we pass through expressions.
enum class ComparisonCategoryType : unsigned char {
PartialOrdering , WeakOrdering , StrongOrdering , First = PartialOrdering ,
Last = StrongOrdering
}
An enumeration representing the different comparison categories types.
enum class ComparisonCategoryResult : unsigned char {
Equal , Equivalent , Less , Greater ,
Unordered , Last = Unordered
}
An enumeration representing the possible results of a three-way comparison.
enum class MultiVersionKind { None , Target , CPUSpecific , CPUDispatch }
enum AvailabilityResult { AR_Available = 0 , AR_NotYetIntroduced , AR_Deprecated , AR_Unavailable }
Captures the result of checking the availability of a declaration.
enum class ObjCTypeParamVariance : uint8_t { Invariant , Covariant , Contravariant }
Describes the variance of a given generic parameter.
enum class ObjCPropertyQueryKind : uint8_t { OBJC_PR_query_unknown = 0x00 , OBJC_PR_query_instance , OBJC_PR_query_class }
enum { NumObjCPropertyAttrsBits = 16 }
enum class DynamicInitKind : unsigned { NoStub = 0 , Initializer , AtExit , GlobalArrayDestructor }
enum class KernelReferenceKind : unsigned { Kernel = 0 , Stub = 1 }
enum CastKind
CastKind - The kind of operation required for a conversion.
enum BinaryOperatorKind
enum UnaryOperatorKind
enum ObjCBridgeCastKind { OBC_Bridge , OBC_BridgeTransfer , OBC_BridgeRetained }
The kind of bridging performed by the Objective-C bridge cast.
enum SelectorLocationsKind { SelLoc_NonStandard = 0 , SelLoc_StandardNoSpace = 1 , SelLoc_StandardWithSpace = 2 }
Whether all locations of the selector identifiers are in a "standard" position.
enum { TypeAlignmentInBits = 4 , TypeAlignment = 1 << TypeAlignmentInBits }
enum class ObjCSubstitutionContext {
Ordinary , Result , Parameter , Property ,
Superclass
}
The kind of type we are substituting Objective-C type arguments into.
enum RefQualifierKind { RQ_None = 0 , RQ_LValue , RQ_RValue }
The kind of C++11 ref-qualifier associated with a function type.
enum class AutoTypeKeyword { Auto , DecltypeAuto , GNUAutoType }
Which keyword(s) were used to create an AutoType.
enum TagTypeKind {
TTK_Struct , TTK_Interface , TTK_Union , TTK_Class ,
TTK_Enum
}
The kind of a tag type.
enum ElaboratedTypeKeyword {
ETK_Struct , ETK_Interface , ETK_Union , ETK_Class ,
ETK_Enum , ETK_Typename , ETK_None
}
The elaboration keyword that precedes a qualified type name or introduces an elaborated-type-specifier.
enum CXXCtorType {
Ctor_Complete , Ctor_Base , Ctor_Comdat , Ctor_CopyingClosure ,
Ctor_DefaultClosure
}
C++ constructor types.
enum CXXDtorType { Dtor_Deleting , Dtor_Complete , Dtor_Base , Dtor_Comdat }
C++ destructor types.
enum class LangAS : unsigned {
Default = 0 , opencl_global , opencl_local , opencl_constant ,
opencl_private , opencl_generic , opencl_global_device , opencl_global_host ,
cuda_device , cuda_constant , cuda_shared , ptr32_sptr ,
ptr32_uptr , ptr64 , FirstTargetAddressSpace
}
Defines the address space values used by the address space qualifier of QualType.
enum class AttrSyntax {
GNU , Declspec , Microsoft , CXX ,
C , Pragma
}
enum LanguageID {
GNU_LANG = 0x1 , C_LANG = 0x2 , CXX_LANG = 0x4 , OBJC_LANG = 0x8 ,
MS_LANG = 0x10 , OCLC20_LANG = 0x20 , OCLC1X_LANG = 0x40 , OMP_LANG = 0x80 ,
ALL_LANGUAGES = C_LANG | CXX_LANG | OBJC_LANG , ALL_GNU_LANGUAGES = ALL_LANGUAGES | GNU_LANG , ALL_MS_LANGUAGES = ALL_LANGUAGES | MS_LANG , ALL_OCLC_LANGUAGES = OCLC1X_LANG | OCLC20_LANG
}
enum BuiltinTemplateKind : int { BTK__make_integer_seq , BTK__type_pack_element }
Kinds of BuiltinTemplateDecl.
enum CapturedRegionKind { CR_Default , CR_ObjCAtFinally , CR_OpenMP }
The different kinds of captured statement.
enum class CudaVersion {
UNKNOWN , CUDA_70 , CUDA_75 , CUDA_80 ,
CUDA_90 , CUDA_91 , CUDA_92 , CUDA_100 ,
CUDA_101 , CUDA_102 , CUDA_110 , LATEST = CUDA_110 ,
LATEST_SUPPORTED = CUDA_101
}
enum class CudaArch {
UNUSED , UNKNOWN , SM_20 , SM_21 ,
SM_30 , SM_32 , SM_35 , SM_37 ,
SM_50 , SM_52 , SM_53 , SM_60 ,
SM_61 , SM_62 , SM_70 , SM_72 ,
SM_75 , SM_80 , GFX600 , GFX601 ,
GFX602 , GFX700 , GFX701 , GFX702 ,
GFX703 , GFX704 , GFX705 , GFX801 ,
GFX802 , GFX803 , GFX805 , GFX810 ,
GFX900 , GFX902 , GFX904 , GFX906 ,
GFX908 , GFX909 , GFX90c , GFX1010 ,
GFX1011 , GFX1012 , GFX1030 , GFX1031 ,
GFX1032 , GFX1033 , LAST
}
enum class CudaFeature { CUDA_USES_NEW_LAUNCH , CUDA_USES_FATBIN_REGISTER_END }
enum OverloadsShown : unsigned { Ovl_All , Ovl_Best }
Specifies which overload candidates to display when overload resolution fails.
enum class DiagnosticLevelMask : unsigned {
None = 0 , Note = 1 << 0 , Remark = 1 << 1 , Warning = 1 << 2 ,
Error = 1 << 3 , All = Note | Remark | Warning | Error
}
A bitmask representing the diagnostic levels used by VerifyDiagnosticConsumer.
enum ExceptionSpecificationType {
EST_None , EST_DynamicNone , EST_Dynamic , EST_MSAny ,
EST_NoThrow , EST_BasicNoexcept , EST_DependentNoexcept , EST_NoexceptFalse ,
EST_NoexceptTrue , EST_Unevaluated , EST_Uninstantiated , EST_Unparsed
}
The various types of exception specifications that exist in C++11.
enum CanThrowResult { CT_Cannot , CT_Dependent , CT_Can }
Possible results from evaluation of a noexcept expression.
enum ExpressionTrait { ET_Last }
enum { IdentifierInfoAlignment = 8 }
IdentifierInfo and other related classes are aligned to 8 bytes so that DeclarationName can use the lower 3 bits of a pointer to one of these classes.
enum ObjCMethodFamily {
OMF_None , OMF_alloc , OMF_copy , OMF_init ,
OMF_mutableCopy , OMF_new , OMF_autorelease , OMF_dealloc ,
OMF_finalize , OMF_release , OMF_retain , OMF_retainCount ,
OMF_self , OMF_initialize , OMF_performSelector
}
A family of Objective-C methods.
enum { ObjCMethodFamilyBitWidth = 4 }
Enough bits to store any enumerator in ObjCMethodFamily or InvalidObjCMethodFamily.
enum { InvalidObjCMethodFamily = (1 << ObjCMethodFamilyBitWidth) - 1 }
An invalid value of ObjCMethodFamily.
enum ObjCInstanceTypeFamily {
OIT_None , OIT_Array , OIT_Dictionary , OIT_Singleton ,
OIT_Init , OIT_ReturnsSelf
}
A family of Objective-C methods.
enum ObjCStringFormatFamily { SFF_None , SFF_NSString , SFF_CFString }
enum LambdaCaptureDefault { LCD_None , LCD_ByCopy , LCD_ByRef }
The default, if any, capture method for a lambda expression.
enum LambdaCaptureKind {
LCK_This , LCK_StarThis , LCK_ByCopy , LCK_ByRef ,
LCK_VLAType
}
The different capture forms in a lambda introducer.
enum class MSVtorDispMode { Never , ForVBaseOverride , ForVFTable }
In the Microsoft ABI, this controls the placement of virtual displacement members used to implement virtual inheritance.
enum TranslationUnitKind { TU_Complete , TU_Prefix , TU_Module }
Describes the kind of translation unit being processed.
enum class Language : uint8_t {
Unknown , Asm , LLVM_IR , C ,
CXX , ObjC , ObjCXX , OpenCL ,
CUDA , RenderScript , HIP
}
The language for the input, used to select and validate the language standard and possible actions.
enum LangFeatures {
LineComment = (1 << 0) , C99 = (1 << 1) , C11 = (1 << 2) , C17 = (1 << 3) ,
C2x = (1 << 4) , CPlusPlus = (1 << 5) , CPlusPlus11 = (1 << 6) , CPlusPlus14 = (1 << 7) ,
CPlusPlus17 = (1 << 8) , CPlusPlus20 = (1 << 9) , CPlusPlus2b = (1 << 10) , Digraphs = (1 << 11) ,
GNUMode = (1 << 12) , HexFloat = (1 << 13) , ImplicitInt = (1 << 14) , OpenCL = (1 << 15)
}
enum Linkage : unsigned char {
NoLinkage = 0 , InternalLinkage , UniqueExternalLinkage , VisibleNoLinkage ,
ModuleInternalLinkage , ModuleLinkage , ExternalLinkage
}
Describes the different kinds of linkage (C++ [basic.link], C99 6.2.2) that an entity may have.
enum LanguageLinkage { CLanguageLinkage , CXXLanguageLinkage , NoLanguageLinkage }
Describes the different kinds of language linkage (C++ [dcl.link]) that an entity may have.
enum GVALinkage {
GVA_Internal , GVA_AvailableExternally , GVA_DiscardableODR , GVA_StrongExternal ,
GVA_StrongODR
}
A more specific kind of linkage than enum Linkage.
enum OpenMPScheduleClauseKind { OMPC_SCHEDULE_unknown }
OpenMP attributes for 'schedule' clause.
enum OpenMPScheduleClauseModifier { OMPC_SCHEDULE_MODIFIER_unknown = OMPC_SCHEDULE_unknown , OMPC_SCHEDULE_MODIFIER_last }
OpenMP modifiers for 'schedule' clause.
enum OpenMPDeviceClauseModifier { OMPC_DEVICE_unknown }
OpenMP modifiers for 'device' clause.
enum OpenMPDependClauseKind { OMPC_DEPEND_unknown }
OpenMP attributes for 'depend' clause.
enum OpenMPLinearClauseKind { OMPC_LINEAR_unknown }
OpenMP attributes for 'linear' clause.
enum OpenMPMapClauseKind { OMPC_MAP_unknown }
OpenMP mapping kind for 'map' clause.
enum OpenMPMapModifierKind { OMPC_MAP_MODIFIER_unknown = OMPC_MAP_unknown , OMPC_MAP_MODIFIER_last }
OpenMP modifier kind for 'map' clause.
enum OpenMPMotionModifierKind { OMPC_MOTION_MODIFIER_unknown }
OpenMP modifier kind for 'to' or 'from' clause.
enum OpenMPDistScheduleClauseKind { OMPC_DIST_SCHEDULE_unknown }
OpenMP attributes for 'dist_schedule' clause.
enum OpenMPDefaultmapClauseKind { OMPC_DEFAULTMAP_unknown }
OpenMP attributes for 'defaultmap' clause.
enum OpenMPDefaultmapClauseModifier { OMPC_DEFAULTMAP_MODIFIER_unknown = OMPC_DEFAULTMAP_unknown , OMPC_DEFAULTMAP_MODIFIER_last }
OpenMP modifiers for 'defaultmap' clause.
enum OpenMPAtomicDefaultMemOrderClauseKind { OMPC_ATOMIC_DEFAULT_MEM_ORDER_unknown }
OpenMP attributes for 'atomic_default_mem_order' clause.
enum OpenMPDeviceType { OMPC_DEVICE_TYPE_unknown }
OpenMP device type for 'device_type' clause.
enum OpenMPLastprivateModifier { OMPC_LASTPRIVATE_unknown }
OpenMP 'lastprivate' clause modifier.
enum OpenMPOrderClauseKind { OMPC_ORDER_unknown }
OpenMP attributes for 'order' clause.
enum OpenMPReductionClauseModifier { OMPC_REDUCTION_unknown }
OpenMP modifiers for 'reduction' clause.
enum OverloadedOperatorKind : int { OO_None , NUM_OVERLOADED_OPERATORS }
Enumeration specifying the different kinds of C++ overloaded operators.
enum PragmaMSCommentKind {
PCK_Unknown , PCK_Linker , PCK_Lib , PCK_Compiler ,
PCK_ExeStr , PCK_User
}
enum PragmaMSStructKind { PMSST_OFF , PMSST_ON }
enum PragmaFloatControlKind {
PFC_Unknown , PFC_Precise , PFC_NoPrecise , PFC_Except ,
PFC_NoExcept , PFC_Push , PFC_Pop
}
enum class ExplicitSpecKind : unsigned { ResolvedFalse , ResolvedTrue , Unresolved }
Define the meaning of possible values of the kind in ExplicitSpecifier.
enum class ConstexprSpecKind { Unspecified , Constexpr , Consteval , Constinit }
Define the kind of constexpr specifier.
enum class TypeSpecifierWidth { Unspecified , Short , Long , LongLong }
Specifies the width of a type, e.g., short, long, or long long.
enum class TypeSpecifierSign { Unspecified , Signed , Unsigned }
Specifies the signedness of a type, e.g., signed or unsigned.
enum class TypeSpecifiersPipe { Unspecified , Pipe }
enum TypeSpecifierType {
TST_unspecified , TST_void , TST_char , TST_wchar ,
TST_char8 , TST_char16 , TST_char32 , TST_int ,
TST_int128 , TST_extint , TST_half , TST_Float16 ,
TST_Accum , TST_Fract , TST_BFloat16 , TST_float ,
TST_double , TST_float128 , TST_bool , TST_decimal32 ,
TST_decimal64 , TST_decimal128 , TST_enum , TST_union ,
TST_struct , TST_class , TST_interface , TST_typename ,
TST_typeofType , TST_typeofExpr , TST_decltype , TST_underlyingType ,
TST_auto , TST_decltype_auto , TST_auto_type , TST_unknown_anytype ,
TST_atomic , TST_error
}
Specifies the kind of type.
enum AccessSpecifier { AS_public , AS_protected , AS_private , AS_none }
A C++ access specifier (public, private, protected), plus the special value "none" which means different things in different contexts.
enum ExprValueKind { VK_RValue , VK_LValue , VK_XValue }
The categorization of expression values, currently following the C++11 scheme.
enum ExprObjectKind {
OK_Ordinary , OK_BitField , OK_VectorComponent , OK_ObjCProperty ,
OK_ObjCSubscript , OK_MatrixComponent
}
A further classification of the kind of object referenced by an l-value or x-value.
enum NonOdrUseReason { NOUR_None = 0 , NOUR_Unevaluated , NOUR_Constant , NOUR_Discarded }
The reason why a DeclRefExpr does not constitute an odr-use.
enum TemplateSpecializationKind {
TSK_Undeclared = 0 , TSK_ImplicitInstantiation , TSK_ExplicitSpecialization , TSK_ExplicitInstantiationDeclaration ,
TSK_ExplicitInstantiationDefinition
}
Describes the kind of template specialization that a particular template specialization declaration represents.
enum ThreadStorageClassSpecifier { TSCS_unspecified , TSCS___thread , TSCS_thread_local , TSCS__Thread_local }
Thread storage-class-specifier.
enum StorageClass {
SC_None , SC_Extern , SC_Static , SC_PrivateExtern ,
SC_Auto , SC_Register
}
Storage classes.
enum InClassInitStyle { ICIS_NoInit , ICIS_CopyInit , ICIS_ListInit }
In-class initialization styles for non-static data members.
enum CallingConv {
CC_C , CC_X86StdCall , CC_X86FastCall , CC_X86ThisCall ,
CC_X86VectorCall , CC_X86Pascal , CC_Win64 , CC_X86_64SysV ,
CC_X86RegCall , CC_AAPCS , CC_AAPCS_VFP , CC_IntelOclBicc ,
CC_SpirFunction , CC_OpenCLKernel , CC_Swift , CC_PreserveMost ,
CC_PreserveAll , CC_AArch64VectorCall
}
CallingConv - Specifies the calling convention that a function uses.
enum StorageDuration {
SD_FullExpression , SD_Automatic , SD_Thread , SD_Static ,
SD_Dynamic
}
The storage duration for an object (per C++ [basic.stc]).
enum class NullabilityKind : uint8_t { NonNull = 0 , Nullable , Unspecified , NullableResult }
Describes the nullability of a particular type.
enum class ParameterABI { Ordinary , SwiftIndirectResult , SwiftErrorResult , SwiftContext }
Kinds of parameter ABI.
enum class MSInheritanceModel { Single = 0 , Multiple = 1 , Virtual = 2 , Unspecified = 3 }
Assigned inheritance model for a class in the MS C++ ABI.
enum class SyncScope {
OpenCLWorkGroup , OpenCLDevice , OpenCLAllSVMDevices , OpenCLSubGroup ,
Last = OpenCLSubGroup
}
Defines synch scope values used internally by clang.
enum class AtomicScopeModelKind { None , OpenCL }
Defines the kind of atomic scope models.
enum OpenCLTypeKind : uint8_t {
OCLTK_Default , OCLTK_ClkEvent , OCLTK_Event , OCLTK_Image ,
OCLTK_Pipe , OCLTK_Queue , OCLTK_ReserveID , OCLTK_Sampler
}
OpenCL type kinds.
enum TemplateNameKind {
TNK_Non_template = 0 , TNK_Function_template , TNK_Type_template , TNK_Var_template ,
TNK_Dependent_template_name , TNK_Undeclared_template , TNK_Concept_template
}
Specifies the kind of template name that an identifier refers to.
enum TypeTrait { UTT_Last , BTT_Last , TT_Last }
Names for traits that operate specifically on types.
enum ArrayTypeTrait { ATT_Last }
Names for the array type traits.
enum UnaryExprOrTypeTrait { UETT_Last }
Names for the "expression or type" traits.
enum Visibility { HiddenVisibility , ProtectedVisibility , DefaultVisibility }
Describes the different kinds of visibility that a declaration may have.
enum BackendAction {
Backend_EmitAssembly , Backend_EmitBC , Backend_EmitLL , Backend_EmitNothing ,
Backend_EmitMCNull , Backend_EmitObj
}
enum class SkipFunctionBodiesScope { None , Preamble , PreambleAndMainFile }
Enumerates the available scopes for skipping function bodies.
enum class CaptureDiagsKind { None , All , AllWithoutNonErrorsFromIncludes }
Enumerates the available kinds for capturing diagnostics.
enum class ShowIncludesDestination { None , Stdout , Stderr }
ShowIncludesDestination - Destination for /showIncludes output.
enum class DependencyOutputFormat { Make , NMake }
DependencyOutputFormat - Format for the compiler dependency file.
enum class BuildPreambleError {
CouldntCreateTempFile = 1 , CouldntCreateTargetInfo , BeginSourceFileFailed , CouldntEmitPCH ,
BadInputs
}
enum { HMAP_HeaderMagicNumber = ('h' << 24) | ('m' << 16) | ('a' << 8) | 'p' , HMAP_HeaderVersion = 1 , HMAP_EmptyBucketKey = 0 }
enum ConflictMarkerKind { CMK_None , CMK_Normal , CMK_Perforce }
ConflictMarkerKind - Kinds of conflict marker which the lexer might be recovering from.
enum PragmaIntroducerKind { PIK_HashPragma , PIK__Pragma , PIK___pragma }
Describes how the pragma was introduced, e.g., with #pragma, _Pragma, or __pragma.
enum MacroUse { MU_Other = 0 , MU_Define = 1 , MU_Undef = 2 }
Context in which macro name is used.
enum ObjCXXARCStandardLibraryKind { ARCXX_nolib , ARCXX_libcxx , ARCXX_libstdcxx }
Enumerate the kinds of standard library that.
enum class DisableValidationForModuleKind { None = 0 , PCH = 0x1 , Module = 0x2 , All = PCH | Module }
Whether to disable the normal validation performed on precompiled headers and module files when they are loaded.
enum {
CCP_NextInitializer = 7 , CCP_EnumInCase = 7 , CCP_SuperCompletion = 20 , CCP_LocalDeclaration = 34 ,
CCP_MemberDeclaration = 35 , CCP_Keyword = 40 , CCP_CodePattern = 40 , CCP_Declaration = 50 ,
CCP_Type = CCP_Declaration , CCP_Constant = 65 , CCP_Macro = 70 , CCP_NestedNameSpecifier = 75 ,
CCP_Unlikely = 80 , CCP_ObjC_cmd = CCP_Unlikely
}
Default priority values for code-completion results based on their kind.
enum {
CCD_InBaseClass = 2 , CCD_ObjectQualifierMatch = -1 , CCD_SelectorMatch = -3 , CCD_bool_in_ObjC = 1 ,
CCD_ProbablyNotObjCCollection = 15 , CCD_MethodAsProperty = 2 , CCD_BlockPropertySetter = 3
}
Priority value deltas that are added to code-completion results based on the context of the result.
enum { CCF_ExactTypeMatch = 4 , CCF_SimilarTypeMatch = 2 }
Priority value factors by which we will divide or multiply the priority of a code-completion result.
enum SimplifiedTypeClass {
STC_Arithmetic , STC_Array , STC_Block , STC_Function ,
STC_ObjectiveC , STC_Other , STC_Pointer , STC_Record ,
STC_Void
}
A simplified classification of types used when determining "similar" types for code completion.
enum class UnqualifiedIdKind {
IK_Identifier , IK_OperatorFunctionId , IK_ConversionFunctionId , IK_LiteralOperatorId ,
IK_ConstructorName , IK_ConstructorTemplateId , IK_DestructorName , IK_TemplateId ,
IK_ImplicitSelfParam , IK_DeductionGuideName
}
Describes the kind of unqualified-id parsed.
enum class FunctionDefinitionKind { Declaration , Definition , Defaulted , Deleted }
Described the kind of function definition (if any) provided for a function.
enum class DeclaratorContext {
File , Prototype , ObjCResult , ObjCParameter ,
KNRTypeList , TypeName , FunctionalCast , Member ,
Block , ForInit , SelectionInit , Condition ,
TemplateParam , CXXNew , CXXCatch , ObjCCatch ,
BlockLiteral , LambdaExpr , LambdaExprParameter , ConversionId ,
TrailingReturn , TrailingReturnVar , TemplateArg , TemplateTypeArg ,
AliasDecl , AliasTemplate , RequiresExpr
}
enum class LambdaCaptureInitKind { NoInit , CopyInit , DirectInit , ListInit }
enum OverloadingResult { OR_Success , OR_No_Viable_Function , OR_Ambiguous , OR_Deleted }
OverloadingResult - Capture the result of performing overload resolution.
enum OverloadCandidateDisplayKind { OCD_AllCandidates , OCD_ViableCandidates , OCD_AmbiguousCandidates }
enum class OverloadCandidateParamOrder : char { Normal , Reversed }
The parameter ordering that will be used for the candidate.
enum OverloadCandidateRewriteKind : unsigned { CRK_None = 0x0 , CRK_DifferentOperator = 0x1 , CRK_Reversed = 0x2 }
The kinds of rewrite we perform on overload candidates.
enum ImplicitConversionKind {
ICK_Identity = 0 , ICK_Lvalue_To_Rvalue , ICK_Array_To_Pointer , ICK_Function_To_Pointer ,
ICK_Function_Conversion , ICK_Qualification , ICK_Integral_Promotion , ICK_Floating_Promotion ,
ICK_Complex_Promotion , ICK_Integral_Conversion , ICK_Floating_Conversion , ICK_Complex_Conversion ,
ICK_Floating_Integral , ICK_Pointer_Conversion , ICK_Pointer_Member , ICK_Boolean_Conversion ,
ICK_Compatible_Conversion , ICK_Derived_To_Base , ICK_Vector_Conversion , ICK_SVE_Vector_Conversion ,
ICK_Vector_Splat , ICK_Complex_Real , ICK_Block_Pointer_Conversion , ICK_TransparentUnionConversion ,
ICK_Writeback_Conversion , ICK_Zero_Event_Conversion , ICK_Zero_Queue_Conversion , ICK_C_Only_Conversion ,
ICK_Incompatible_Pointer_Conversion , ICK_Num_Conversion_Kinds
}
ImplicitConversionKind - The kind of implicit conversion used to convert an argument to a parameter's type.
enum ImplicitConversionRank {
ICR_Exact_Match = 0 , ICR_Promotion , ICR_Conversion , ICR_OCL_Scalar_Widening ,
ICR_Complex_Real_Conversion , ICR_Writeback_Conversion , ICR_C_Conversion , ICR_C_Conversion_Extension
}
ImplicitConversionRank - The rank of an implicit conversion kind.
enum NarrowingKind {
NK_Not_Narrowing , NK_Type_Narrowing , NK_Constant_Narrowing , NK_Variable_Narrowing ,
NK_Dependent_Narrowing
}
NarrowingKind - The kind of narrowing conversion being performed by a standard conversion sequence according to C++11 [dcl.init.list]p7.
enum OverloadFailureKind {
ovl_fail_too_many_arguments , ovl_fail_too_few_arguments , ovl_fail_bad_conversion , ovl_fail_bad_deduction ,
ovl_fail_trivial_conversion , ovl_fail_illegal_constructor , ovl_fail_bad_final_conversion , ovl_fail_final_conversion_not_exact ,
ovl_fail_bad_target , ovl_fail_enable_if , ovl_fail_explicit , ovl_fail_addr_not_available ,
ovl_fail_ext_disabled , ovl_fail_inhctor_slice , ovl_non_default_multiversion_function , ovl_fail_object_addrspace_mismatch ,
ovl_fail_constraints_not_satisfied
}
enum AttributeArgumentNType {
AANT_ArgumentIntOrBool , AANT_ArgumentIntegerConstant , AANT_ArgumentString , AANT_ArgumentIdentifier ,
AANT_ArgumentConstantExpr
}
These constants match the enumerated choices of err_attribute_argument_n_type and err_attribute_argument_type.
enum AttributeDeclKind {
ExpectedFunction , ExpectedUnion , ExpectedVariableOrFunction , ExpectedFunctionOrMethod ,
ExpectedFunctionMethodOrBlock , ExpectedFunctionMethodOrParameter , ExpectedVariable , ExpectedVariableOrField ,
ExpectedVariableFieldOrTag , ExpectedTypeOrNamespace , ExpectedFunctionVariableOrClass , ExpectedKernelFunction ,
ExpectedFunctionWithProtoType
}
These constants match the enumerated choices of warn_attribute_wrong_decl_type and err_attribute_wrong_decl_type.
enum OverloadFixItKind {
OFIK_Undefined = 0 , OFIK_Dereference , OFIK_TakeAddress , OFIK_RemoveDereference ,
OFIK_RemoveTakeAddress
}
enum class TemplateSubstitutionKind : char { Specialization , Rewrite }
The kind of template substitution being performed.
enum TPOC { TPOC_Call , TPOC_Conversion , TPOC_Other }
The context in which partial ordering of function templates occurs.
enum Analyses { NumAnalyses }
Analysis - Set of available source code analyses.
enum AnalysisStores { NumStores }
AnalysisStores - Set of available analysis store models.
enum AnalysisConstraints { NumConstraints }
AnalysisConstraints - Set of available constraint models.
enum AnalysisDiagClients { PD_NONE , NUM_ANALYSIS_DIAG_CLIENTS }
AnalysisDiagClients - Set of available diagnostic clients for rendering analysis results.
enum AnalysisPurgeMode { NumPurgeModes }
AnalysisPurgeModes - Set of available strategies for dead symbol removal.
enum AnalysisInliningMode { NumInliningModes }
AnalysisInlineFunctionSelection - Set of inlining function selection heuristics.
enum CXXInlineableMemberKind { CIMK_None , CIMK_MemberFunctions , CIMK_Constructors , CIMK_Destructors }
Describes the different kinds of C++ member functions which can be considered for inlining by the analyzer.
enum IPAKind {
IPAK_None = 1 , IPAK_BasicInlining = 2 , IPAK_Inlining = 3 , IPAK_DynamicDispatch = 4 ,
IPAK_DynamicDispatchBifurcate = 5
}
Describes the different modes of inter-procedural analysis.
enum class ExplorationStrategyKind {
DFS , BFS , UnexploredFirst , UnexploredFirstQueue ,
UnexploredFirstLocationQueue , BFSBlockDFSContents
}
enum UserModeKind { UMK_Shallow = 1 , UMK_Deep = 2 }
Describes the kinds for high-level analyzer mode.
enum TestLanguage {
Lang_C89 , Lang_C99 , Lang_CXX03 , Lang_CXX11 ,
Lang_CXX14 , Lang_CXX17 , Lang_CXX20 , Lang_OpenCL ,
Lang_OBJCXX
}
enum AccessKinds {
AK_Read , AK_ReadObjectRepresentation , AK_Assign , AK_Increment ,
AK_Decrement , AK_MemberCall , AK_DynamicCast , AK_TypeId ,
AK_Construct , AK_Destroy
}
Kinds of access we can perform on an object, for diagnostics.
enum CheckSubobjectKind {
CSK_Base , CSK_Derived , CSK_Field , CSK_ArrayToPointer ,
CSK_ArrayIndex , CSK_Real , CSK_Imag
}
enum TemplateDeductionFlags {
TDF_None = 0 , TDF_ParamWithReferenceType = 0x1 , TDF_IgnoreQualifiers = 0x02 , TDF_DerivedClass = 0x04 ,
TDF_SkipNonDependent = 0x08 , TDF_TopLevelParameterTypeList = 0x10 , TDF_AllowCompatibleFunctionType = 0x20 , TDF_ArgWithReferenceType = 0x40
}
Various flags that control template argument deduction.
Functions
void checkCalledOnceParameters (AnalysisDeclContext &AC, CalledOnceCheckHandler &Handler, bool CheckConventionalParameters)
Check given CFG for 'called once' parameter violations.
void runUninitializedVariablesAnalysis (const DeclContext &dc, const CFG &cfg, AnalysisDeclContext &ac, UninitVariablesHandler &handler, UninitVariablesAnalysisStats &stats)
bool operator== (const CallGraphNode::CallRecord &LHS, const CallGraphNode::CallRecord &RHS)
llvm::SmallString< 32 > getIssueHash (const FullSourceLoc &IssueLoc, llvm::StringRef CheckerName, llvm::StringRef WarningMessage, const Decl *IssueDecl, const LangOptions &LangOpts)
Returns an opaque identifier for a diagnostic.
std::string getIssueString (const FullSourceLoc &IssueLoc, llvm::StringRef CheckerName, llvm::StringRef WarningMessage, const Decl *IssueDecl, const LangOptions &LangOpts)
Get the unhashed string representation of the V1 issue hash.
template<typename... IdentifierInfos>
static Selector getKeywordSelector (ASTContext &Ctx, IdentifierInfos *... IIs)
template<typename... IdentifierInfos>
static void lazyInitKeywordSelector (Selector &Sel, ASTContext &Ctx, IdentifierInfos *... IIs)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const ASTContext::SectionInfo &Section)
Insertion operator for diagnostics.
Selector GetNullarySelector (StringRef name, ASTContext &Ctx)
Utility function for constructing a nullary selector.
Selector GetUnarySelector (StringRef name, ASTContext &Ctx)
Utility function for constructing an unary selector.
void FormatASTNodeDiagnosticArgument (DiagnosticsEngine::ArgumentKind Kind, intptr_t Val, StringRef Modifier, StringRef Argument, ArrayRef< DiagnosticsEngine::ArgumentValue > PrevArgs, SmallVectorImpl< char > &Output, void *Cookie, ArrayRef< intptr_t > QualTypeVals)
DiagnosticsEngine argument formatting function for diagnostics that involve AST nodes.
llvm::SmallVector< Decl *, 2 > getCanonicalForwardRedeclChain (Decl *D)
StringRef getLambdaStaticInvokerName ()
bool isLambdaCallOperator (const CXXMethodDecl *MD)
bool isLambdaCallOperator (const DeclContext *DC)
bool isGenericLambdaCallOperatorSpecialization (const CXXMethodDecl *MD)
bool isLambdaConversionOperator (CXXConversionDecl *C)
bool isLambdaConversionOperator (Decl *D)
bool isGenericLambdaCallOperatorSpecialization (DeclContext *DC)
bool isGenericLambdaCallOperatorOrStaticInvokerSpecialization (DeclContext *DC)
DeclContext * getLambdaAwareParentOfDeclContext (DeclContext *DC)
raw_ostream & operator<< (raw_ostream &OS, ASTNodeKind K)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const Attr *At)
template<typename SpecificAttr , typename Container >
specific_attr_iterator< SpecificAttr, Container > specific_attr_begin (const Container &container)
template<typename SpecificAttr , typename Container >
specific_attr_iterator< SpecificAttr, Container > specific_attr_end (const Container &container)
template<typename SpecificAttr , typename Container >
bool hasSpecificAttr (const Container &container)
template<typename SpecificAttr , typename Container >
SpecificAttr * getSpecificAttr (const Container &container)
template<typename T , typename U >
bool operator== (CanQual< T > x, CanQual< U > y)
template<typename T , typename U >
bool operator!= (CanQual< T > x, CanQual< U > y)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, CanQualType T)
ComparisonCategoryType commonComparisonType (ComparisonCategoryType A, ComparisonCategoryType B)
Determine the common comparison type, as defined in C++2a [class.spaceship]p4.
Optional< ComparisonCategoryType > getComparisonCategoryForBuiltinCmp (QualType T)
Get the comparison category that should be used when comparing values of type T.
ExprDependence computeDependence (FullExpr *E)
ExprDependence computeDependence (OpaqueValueExpr *E)
ExprDependence computeDependence (ParenExpr *E)
ExprDependence computeDependence (UnaryOperator *E, const ASTContext &Ctx)
ExprDependence computeDependence (UnaryExprOrTypeTraitExpr *E)
ExprDependence computeDependence (ArraySubscriptExpr *E)
ExprDependence computeDependence (MatrixSubscriptExpr *E)
ExprDependence computeDependence (CompoundLiteralExpr *E)
ExprDependence computeDependence (CastExpr *E)
ExprDependence computeDependence (BinaryOperator *E)
ExprDependence computeDependence (ConditionalOperator *E)
ExprDependence computeDependence (BinaryConditionalOperator *E)
ExprDependence computeDependence (StmtExpr *E, unsigned TemplateDepth)
ExprDependence computeDependence (ConvertVectorExpr *E)
ExprDependence computeDependence (VAArgExpr *E)
ExprDependence computeDependence (ChooseExpr *E)
ExprDependence computeDependence (NoInitExpr *E)
ExprDependence computeDependence (ArrayInitLoopExpr *E)
ExprDependence computeDependence (ImplicitValueInitExpr *E)
ExprDependence computeDependence (InitListExpr *E)
ExprDependence computeDependence (ExtVectorElementExpr *E)
ExprDependence computeDependence (BlockExpr *E)
ExprDependence computeDependence (AsTypeExpr *E)
ExprDependence computeDependence (DeclRefExpr *E, const ASTContext &Ctx)
Compute the type-, value-, and instantiation-dependence of a declaration reference based on the declaration being referenced.
ExprDependence computeDependence (RecoveryExpr *E)
ExprDependence computeDependence (CXXRewrittenBinaryOperator *E)
ExprDependence computeDependence (CXXStdInitializerListExpr *E)
ExprDependence computeDependence (CXXTypeidExpr *E)
ExprDependence computeDependence (MSPropertyRefExpr *E)
ExprDependence computeDependence (MSPropertySubscriptExpr *E)
ExprDependence computeDependence (CXXUuidofExpr *E)
ExprDependence computeDependence (CXXThisExpr *E)
ExprDependence computeDependence (CXXThrowExpr *E)
ExprDependence computeDependence (CXXBindTemporaryExpr *E)
ExprDependence computeDependence (CXXScalarValueInitExpr *E)
ExprDependence computeDependence (CXXDeleteExpr *E)
ExprDependence computeDependence (ArrayTypeTraitExpr *E)
ExprDependence computeDependence (ExpressionTraitExpr *E)
ExprDependence computeDependence (CXXNoexceptExpr *E, CanThrowResult CT)
ExprDependence computeDependence (PackExpansionExpr *E)
ExprDependence computeDependence (SubstNonTypeTemplateParmExpr *E)
ExprDependence computeDependence (CoroutineSuspendExpr *E)
ExprDependence computeDependence (DependentCoawaitExpr *E)
ExprDependence computeDependence (CXXNewExpr *E)
ExprDependence computeDependence (CXXPseudoDestructorExpr *E)
ExprDependence computeDependence (OverloadExpr *E, bool KnownDependent, bool KnownInstantiationDependent, bool KnownContainsUnexpandedParameterPack)
ExprDependence computeDependence (DependentScopeDeclRefExpr *E)
ExprDependence computeDependence (CXXConstructExpr *E)
ExprDependence computeDependence (CXXDefaultInitExpr *E)
ExprDependence computeDependence (LambdaExpr *E, bool ContainsUnexpandedParameterPack)
ExprDependence computeDependence (CXXUnresolvedConstructExpr *E)
ExprDependence computeDependence (CXXDependentScopeMemberExpr *E)
ExprDependence computeDependence (MaterializeTemporaryExpr *E)
ExprDependence computeDependence (CXXFoldExpr *E)
ExprDependence computeDependence (TypeTraitExpr *E)
ExprDependence computeDependence (ConceptSpecializationExpr *E, bool ValueDependent)
ExprDependence computeDependence (PredefinedExpr *E)
ExprDependence computeDependence (CallExpr *E, llvm::ArrayRef< Expr * > PreArgs)
ExprDependence computeDependence (OffsetOfExpr *E)
ExprDependence computeDependence (MemberExpr *E)
ExprDependence computeDependence (ShuffleVectorExpr *E)
ExprDependence computeDependence (GenericSelectionExpr *E, bool ContainsUnexpandedPack)
ExprDependence computeDependence (DesignatedInitExpr *E)
ExprDependence computeDependence (ParenListExpr *E)
ExprDependence computeDependence (PseudoObjectExpr *E)
ExprDependence computeDependence (AtomicExpr *E)
ExprDependence computeDependence (OMPArraySectionExpr *E)
ExprDependence computeDependence (OMPArrayShapingExpr *E)
ExprDependence computeDependence (OMPIteratorExpr *E)
ExprDependence computeDependence (ObjCArrayLiteral *E)
ExprDependence computeDependence (ObjCDictionaryLiteral *E)
ExprDependence computeDependence (ObjCBoxedExpr *E)
ExprDependence computeDependence (ObjCEncodeExpr *E)
ExprDependence computeDependence (ObjCIvarRefExpr *E)
ExprDependence computeDependence (ObjCPropertyRefExpr *E)
ExprDependence computeDependence (ObjCSubscriptRefExpr *E)
ExprDependence computeDependence (ObjCIsaExpr *E)
ExprDependence computeDependence (ObjCIndirectCopyRestoreExpr *E)
ExprDependence computeDependence (ObjCMessageExpr *E)
bool inheritanceModelHasVBPtrOffsetField (MSInheritanceModel Inheritance)
bool inheritanceModelHasNVOffsetField (bool IsMemberFunction, MSInheritanceModel Inheritance)
bool inheritanceModelHasVBTableOffsetField (MSInheritanceModel Inheritance)
bool inheritanceModelHasOnlyOneField (bool IsMemberFunction, MSInheritanceModel Inheritance)
raw_ostream & operator<< (raw_ostream &OS, const NamedDecl &ND)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &PD, const NamedDecl *ND)
Insertion operator for diagnostics.
bool IsEnumDeclComplete (EnumDecl *ED)
Check if the given decl is complete.
bool IsEnumDeclScoped (EnumDecl *ED)
Check if the given decl is scoped.
static constexpr StringRef getOpenMPVariantManglingSeparatorStr ()
OpenMP variants are mangled early based on their OpenMP context selector.
raw_ostream & operator<< (raw_ostream &OS, DeclarationName N)
bool operator< (DeclarationName LHS, DeclarationName RHS)
Ordering on two declaration names.
bool operator> (DeclarationName LHS, DeclarationName RHS)
Ordering on two declaration names.
bool operator<= (DeclarationName LHS, DeclarationName RHS)
Ordering on two declaration names.
bool operator>= (DeclarationName LHS, DeclarationName RHS)
Ordering on two declaration names.
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &PD, DeclarationName N)
Insertion operator for partial diagnostics.
raw_ostream & operator<< (raw_ostream &OS, DeclarationNameInfo DNInfo)
bool declaresSameEntity (const Decl *D1, const Decl *D2)
Determine whether two declarations declare the same entity.
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, AccessSpecifier AS)
Insertion operator for diagnostics.
raw_ostream & operator<< (raw_ostream &OS, const ObjCCategoryImplDecl &CID)
raw_ostream & operator<< (raw_ostream &OS, const ObjCImplementationDecl &ID)
NamedDecl * getAsNamedDecl (TemplateParameter P)
void * allocateDefaultArgStorageChain (const ASTContext &C)
TemplateDecl * getAsTypeTemplateDecl (Decl *D)
Optional< unsigned > getExpandedPackSize (const NamedDecl *Param)
Check whether the template parameter is a pack expansion, and if so, determine the number of parameters produced by that expansion.
ExprDependence toExprDependence (TemplateArgumentDependence TA)
Computes dependencies of a reference with the name having template arguments with TA dependencies.
ExprDependence toExprDependence (TypeDependence D)
ExprDependence toExprDependence (NestedNameSpecifierDependence D)
ExprDependence turnTypeToValueDependence (ExprDependence D)
ExprDependence turnValueToTypeDependence (ExprDependence D)
TypeDependence toTypeDependence (ExprDependence D)
TypeDependence toTypeDependence (NestedNameSpecifierDependence D)
TypeDependence toTypeDependence (TemplateNameDependence D)
TypeDependence toTypeDependence (TemplateArgumentDependence D)
NestedNameSpecifierDependence toNestedNameSpecifierDependendence (TypeDependence D)
TemplateArgumentDependence toTemplateArgumentDependence (TypeDependence D)
TemplateArgumentDependence toTemplateArgumentDependence (TemplateNameDependence D)
TemplateArgumentDependence toTemplateArgumentDependence (ExprDependence D)
TemplateNameDependence toTemplateNameDependence (NestedNameSpecifierDependence D)
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
template<typename... FnTys>
Expr * IgnoreExprNodes (Expr *E, FnTys &&... Fns)
Given an expression E and functions Fn_1,...,Fn_n : Expr * -> Expr *, Recursively apply each of the functions to E until reaching a fixed point.
template<typename... FnTys>
const Expr * IgnoreExprNodes (const Expr *E, FnTys &&...Fns)
Expr * IgnoreImplicitCastsSingleStep (Expr *E)
Expr * IgnoreImplicitCastsExtraSingleStep (Expr *E)
Expr * IgnoreCastsSingleStep (Expr *E)
Expr * IgnoreLValueCastsSingleStep (Expr *E)
Expr * IgnoreBaseCastsSingleStep (Expr *E)
Expr * IgnoreImplicitSingleStep (Expr *E)
Expr * IgnoreImplicitAsWrittenSingleStep (Expr *E)
Expr * IgnoreParensOnlySingleStep (Expr *E)
Expr * IgnoreParensSingleStep (Expr *E)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, NestedNameSpecifier *NNS)
Insertion operator for diagnostics.
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const OMPTraitInfo &TI)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const OMPTraitInfo *TI)
DEF_TRAVERSE_TYPE (ComplexType, { TRY_TO(TraverseType(T->getElementType()));}) DEF_TRAVERSE_TYPE(PointerType
DEF_TRAVERSE_TYPE (BlockPointerType, { TRY_TO(TraverseType(T->getPointeeType()));}) DEF_TRAVERSE_TYPE(LValueReferenceType
DEF_TRAVERSE_TYPE (RValueReferenceType, { TRY_TO(TraverseType(T->getPointeeType()));}) DEF_TRAVERSE_TYPE(MemberPointerType
TRY_TO (TraverseType(T->getPointeeType()))
DEF_TRAVERSE_TYPE (AdjustedType, { TRY_TO(TraverseType(T->getOriginalType()));}) DEF_TRAVERSE_TYPE(DecayedType
DEF_TRAVERSE_TYPE (ConstantArrayType, { TRY_TO(TraverseType(T->getElementType()));if(T->getSizeExpr()) TRY_TO(TraverseStmt(const_cast< Expr * >(T->getSizeExpr())));}) DEF_TRAVERSE_TYPE(IncompleteArrayType
DEF_TRAVERSE_TYPE (VariableArrayType, { TRY_TO(TraverseType(T->getElementType()));TRY_TO(TraverseStmt(T->getSizeExpr()));}) DEF_TRAVERSE_TYPE(DependentSizedArrayType
if (T->getSizeExpr()) TRY_TO(TraverseStmt(T -> getSizeExpr()))
DEF_TRAVERSE_TYPE (DependentAddressSpaceType, { TRY_TO(TraverseStmt(T->getAddrSpaceExpr()));TRY_TO(TraverseType(T->getPointeeType()));}) DEF_TRAVERSE_TYPE(DependentVectorType
TRY_TO (TraverseType(T->getElementType()))
DEF_TRAVERSE_TYPE (DependentSizedExtVectorType, { if(T->getSizeExpr()) TRY_TO(TraverseStmt(T->getSizeExpr()));TRY_TO(TraverseType(T->getElementType()));}) DEF_TRAVERSE_TYPE(VectorType
DEF_TRAVERSE_TYPE (ExtVectorType, { TRY_TO(TraverseType(T->getElementType()));}) DEF_TRAVERSE_TYPE(ConstantMatrixType
DEF_TRAVERSE_TYPE (DependentSizedMatrixType, { if(T->getRowExpr()) TRY_TO(TraverseStmt(T->getRowExpr()));if(T->getColumnExpr()) TRY_TO(TraverseStmt(T->getColumnExpr()));TRY_TO(TraverseType(T->getElementType()));}) DEF_TRAVERSE_TYPE(FunctionNoProtoType
DEF_TRAVERSE_TYPE (FunctionProtoType, { TRY_TO(TraverseType(T->getReturnType()));for(const auto &A :T->param_types()) { TRY_TO(TraverseType(A));} for(const auto &E :T->exceptions()) { TRY_TO(TraverseType(E));} if(Expr *NE=T->getNoexceptExpr()) TRY_TO(TraverseStmt(NE));}) DEF_TRAVERSE_TYPE(TypeOfExprType
DEF_TRAVERSE_TYPE (TypeOfType, { TRY_TO(TraverseType(T->getUnderlyingType()));}) DEF_TRAVERSE_TYPE(DecltypeType
DEF_TRAVERSE_TYPE (UnaryTransformType, { TRY_TO(TraverseType(T->getBaseType()));TRY_TO(TraverseType(T->getUnderlyingType()));}) DEF_TRAVERSE_TYPE(AutoType
DEF_TRAVERSE_TYPE (DeducedTemplateSpecializationType, { TRY_TO(TraverseTemplateName(T->getTemplateName()));TRY_TO(TraverseType(T->getDeducedType()));}) DEF_TRAVERSE_TYPE(SubstTemplateTypeParmType
DEF_TRAVERSE_TYPE (SubstTemplateTypeParmPackType, { TRY_TO(TraverseTemplateArgument(T->getArgumentPack()));}) DEF_TRAVERSE_TYPE(TemplateSpecializationType
TRY_TO (TraverseTemplateArguments(T->getArgs(), T->getNumArgs()))
DEF_TRAVERSE_TYPE (AttributedType, { TRY_TO(TraverseType(T->getModifiedType()));}) DEF_TRAVERSE_TYPE(ParenType
DEF_TRAVERSE_TYPE (MacroQualifiedType, { TRY_TO(TraverseType(T->getUnderlyingType()));}) DEF_TRAVERSE_TYPE(ElaboratedType
DEF_TRAVERSE_TYPE (DependentNameType, { TRY_TO(TraverseNestedNameSpecifier(T->getQualifier()));}) DEF_TRAVERSE_TYPE(DependentTemplateSpecializationType
DEF_TRAVERSE_TYPE (PackExpansionType, { TRY_TO(TraverseType(T->getPattern()));}) DEF_TRAVERSE_TYPE(ObjCObjectType
for (auto typeArg :T->getTypeArgsAsWritten())
DEF_TRAVERSE_TYPE (ObjCObjectPointerType, { TRY_TO(TraverseType(T->getPointeeType()));}) DEF_TRAVERSE_TYPE(AtomicType
DEF_TRAVERSE_TYPE (PipeType, { TRY_TO(TraverseType(T->getElementType()));}) DEF_TRAVERSE_TYPE(DependentExtIntType
DEF_TRAVERSE_TYPELOC (ComplexType, { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));}) DEF_TRAVERSE_TYPELOC(PointerType
DEF_TRAVERSE_TYPELOC (BlockPointerType, { TRY_TO(TraverseTypeLoc(TL.getPointeeLoc()));}) DEF_TRAVERSE_TYPELOC(LValueReferenceType
DEF_TRAVERSE_TYPELOC (RValueReferenceType, { TRY_TO(TraverseTypeLoc(TL.getPointeeLoc()));}) DEF_TRAVERSE_TYPELOC(MemberPointerType
else TRY_TO (TraverseType(QualType(TL.getTypePtr() ->getClass(), 0)))
TRY_TO (TraverseTypeLoc(TL.getPointeeLoc()))
DEF_TRAVERSE_TYPELOC (AdjustedType, { TRY_TO(TraverseTypeLoc(TL.getOriginalLoc()));}) DEF_TRAVERSE_TYPELOC(DecayedType
DEF_TRAVERSE_TYPELOC (ConstantArrayType, { TRY_TO(TraverseTypeLoc(TL.getElementLoc()));TRY_TO(TraverseArrayTypeLocHelper(TL));}) DEF_TRAVERSE_TYPELOC(IncompleteArrayType
TRY_TO (TraverseArrayTypeLocHelper(TL))
DEF_TRAVERSE_TYPELOC (VariableArrayType, { TRY_TO(TraverseTypeLoc(TL.getElementLoc()));TRY_TO(TraverseArrayTypeLocHelper(TL));}) DEF_TRAVERSE_TYPELOC(DependentSizedArrayType
DEF_TRAVERSE_TYPELOC (DependentAddressSpaceType, { TRY_TO(TraverseStmt(TL.getTypePtr() ->getAddrSpaceExpr()));TRY_TO(TraverseType(TL.getTypePtr() ->getPointeeType()));}) DEF_TRAVERSE_TYPELOC(DependentSizedExtVectorType
TRY_TO (TraverseType(TL.getTypePtr() ->getElementType()))
DEF_TRAVERSE_TYPELOC (VectorType, { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));}) DEF_TRAVERSE_TYPELOC(DependentVectorType
DEF_TRAVERSE_TYPELOC (ExtVectorType, { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));}) DEF_TRAVERSE_TYPELOC(ConstantMatrixType
TRY_TO (TraverseStmt(TL.getAttrColumnOperand()))
DEF_TRAVERSE_TYPELOC (DependentSizedMatrixType, { TRY_TO(TraverseStmt(TL.getAttrRowOperand()));TRY_TO(TraverseStmt(TL.getAttrColumnOperand()));TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));}) DEF_TRAVERSE_TYPELOC(FunctionNoProtoType
DEF_TRAVERSE_TYPELOC (FunctionProtoType, { TRY_TO(TraverseTypeLoc(TL.getReturnLoc()));const FunctionProtoType *T=TL.getTypePtr();for(unsigned I=0, E=TL.getNumParams();I !=E;++I) { if(TL.getParam(I)) { TRY_TO(TraverseDecl(TL.getParam(I)));} else if(I< T->getNumParams()) { TRY_TO(TraverseType(T->getParamType(I)));} } for(const auto &E :T->exceptions()) { TRY_TO(TraverseType(E));} if(Expr *NE=T->getNoexceptExpr()) TRY_TO(TraverseStmt(NE));}) DEF_TRAVERSE_TYPELOC(TypeOfExprType
DEF_TRAVERSE_TYPELOC (TypeOfType, { TRY_TO(TraverseTypeLoc(TL.getUnderlyingTInfo() ->getTypeLoc()));}) DEF_TRAVERSE_TYPELOC(DecltypeType
DEF_TRAVERSE_TYPELOC (UnaryTransformType, { TRY_TO(TraverseTypeLoc(TL.getUnderlyingTInfo() ->getTypeLoc()));}) DEF_TRAVERSE_TYPELOC(AutoType
if (TL.isConstrained())
DEF_TRAVERSE_TYPELOC (DeducedTemplateSpecializationType, { TRY_TO(TraverseTemplateName(TL.getTypePtr() ->getTemplateName()));TRY_TO(TraverseType(TL.getTypePtr() ->getDeducedType()));}) DEF_TRAVERSE_TYPELOC(SubstTemplateTypeParmType
DEF_TRAVERSE_TYPELOC (SubstTemplateTypeParmPackType, { TRY_TO(TraverseTemplateArgument(TL.getTypePtr() ->getArgumentPack()));}) DEF_TRAVERSE_TYPELOC(TemplateSpecializationType
for (unsigned I=0, E=TL.getNumArgs();I !=E;++I)
DEF_TRAVERSE_TYPELOC (ParenType, { TRY_TO(TraverseTypeLoc(TL.getInnerLoc()));}) DEF_TRAVERSE_TYPELOC(MacroQualifiedType
DEF_TRAVERSE_TYPELOC (AttributedType, { TRY_TO(TraverseTypeLoc(TL.getModifiedLoc()));}) DEF_TRAVERSE_TYPELOC(ElaboratedType
DEF_TRAVERSE_TYPELOC (DependentNameType, { TRY_TO(TraverseNestedNameSpecifierLoc(TL.getQualifierLoc()));}) DEF_TRAVERSE_TYPELOC(DependentTemplateSpecializationType
Decl * getPrimaryMergedDecl (Decl *D)
Get the primary declaration for a declaration from an AST file.
SelectorLocationsKind hasStandardSelectorLocs (Selector Sel, ArrayRef< SourceLocation > SelLocs, ArrayRef< Expr * > Args, SourceLocation EndLoc)
Returns true if all SelLocs are in a "standard" location.
SourceLocation getStandardSelectorLoc (unsigned Index, Selector Sel, bool WithArgSpace, ArrayRef< Expr * > Args, SourceLocation EndLoc)
Get the "standard" location of a selector identifier, e.g: For nullary selectors, immediately before ']': "[foo release]".
SelectorLocationsKind hasStandardSelectorLocs (Selector Sel, ArrayRef< SourceLocation > SelLocs, ArrayRef< ParmVarDecl * > Args, SourceLocation EndLoc)
Returns true if all SelLocs are in a "standard" location.
SourceLocation getStandardSelectorLoc (unsigned Index, Selector Sel, bool WithArgSpace, ArrayRef< ParmVarDecl * > Args, SourceLocation EndLoc)
Get the "standard" location of a selector identifier, e.g: For nullary selectors, immediately before ']': "[foo release]".
StmtIterator cast_away_const (const ConstStmtIterator &RHS)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const TemplateArgument &Arg)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, TemplateName N)
Insertion operator for diagnostics.
void printTemplateArgumentList (raw_ostream &OS, ArrayRef< TemplateArgument > Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL=nullptr)
Print a template argument list, including the '<' and '>' enclosing the template arguments.
void printTemplateArgumentList (raw_ostream &OS, ArrayRef< TemplateArgumentLoc > Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL=nullptr)
void printTemplateArgumentList (raw_ostream &OS, const TemplateArgumentListInfo &Args, const PrintingPolicy &Policy, const TemplateParameterList *TPL=nullptr)
FunctionType::ExtInfo getFunctionExtInfo (const Type &t)
FunctionType::ExtInfo getFunctionExtInfo (QualType t)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &PD, LangAS AS)
Insertion operator for partial diagnostics.
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &PD, Qualifiers Q)
Insertion operator for partial diagnostics.
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &PD, QualType T)
Insertion operator for partial diagnostics.
void FixedPointValueToString (SmallVectorImpl< char > &Str, llvm::APSInt Val, unsigned Scale)
bool isTargetAddressSpace (LangAS AS)
unsigned toTargetAddressSpace (LangAS AS)
LangAS getLangASFromTargetAS (unsigned TargetAS)
bool isPtrSizeAddressSpace (LangAS AS)
llvm::VersionTuple alignedAllocMinVersion (llvm::Triple::OSType OS)
int hasAttribute (AttrSyntax Syntax, const IdentifierInfo *Scope, const IdentifierInfo *Attr, const TargetInfo &Target, const LangOptions &LangOpts)
Return the version number associated with the attribute if we recognize and implement the attribute specified by the given information.
LLVM_READNONE bool isASCII (char c)
Returns true if this is an ASCII character.
LLVM_READONLY bool isIdentifierHead (unsigned char c, bool AllowDollar=false)
Returns true if this is a valid first character of a C identifier, which is [a-zA-Z_].
LLVM_READONLY bool isIdentifierBody (unsigned char c, bool AllowDollar=false)
Returns true if this is a body character of a C identifier, which is [a-zA-Z0-9_].
LLVM_READONLY bool isHorizontalWhitespace (unsigned char c)
Returns true if this character is horizontal ASCII whitespace: ' ', '\t', '\f', '\v'.
LLVM_READONLY bool isVerticalWhitespace (unsigned char c)
Returns true if this character is vertical ASCII whitespace: '\n', '\r'.
LLVM_READONLY bool isWhitespace (unsigned char c)
Return true if this character is horizontal or vertical ASCII whitespace: ' ', '\t', '\f', '\v', '\n', '\r'.
LLVM_READONLY bool isDigit (unsigned char c)
Return true if this character is an ASCII digit: [0-9].
LLVM_READONLY bool isLowercase (unsigned char c)
Return true if this character is a lowercase ASCII letter: [a-z].
LLVM_READONLY bool isUppercase (unsigned char c)
Return true if this character is an uppercase ASCII letter: [A-Z].
LLVM_READONLY bool isLetter (unsigned char c)
Return true if this character is an ASCII letter: [a-zA-Z].
LLVM_READONLY bool isAlphanumeric (unsigned char c)
Return true if this character is an ASCII letter or digit: [a-zA-Z0-9].
LLVM_READONLY bool isHexDigit (unsigned char c)
Return true if this character is an ASCII hex digit: [0-9a-fA-F].
LLVM_READONLY bool isPunctuation (unsigned char c)
Return true if this character is an ASCII punctuation character.
LLVM_READONLY bool isPrintable (unsigned char c)
Return true if this character is an ASCII printable character; that is, a character that should take exactly one column to print in a fixed-width terminal.
LLVM_READONLY bool isPreprocessingNumberBody (unsigned char c)
Return true if this is the body character of a C preprocessing number, which is [a-zA-Z0-9_.
LLVM_READONLY bool isRawStringDelimBody (unsigned char c)
Return true if this is the body character of a C++ raw string delimiter.
LLVM_READONLY char toLowercase (char c)
Converts the given ASCII character to its lowercase equivalent.
LLVM_READONLY char toUppercase (char c)
Converts the given ASCII character to its uppercase equivalent.
LLVM_READONLY bool isValidIdentifier (StringRef S, bool AllowDollar=false)
Return true if this is a valid ASCII identifier.
const char * CudaVersionToString (CudaVersion V)
CudaVersion CudaStringToVersion (const llvm::Twine &S)
static bool IsNVIDIAGpuArch (CudaArch A)
static bool IsAMDGpuArch (CudaArch A)
const char * CudaArchToString (CudaArch A)
const char * CudaArchToVirtualArchString (CudaArch A)
CudaArch StringToCudaArch (llvm::StringRef S)
CudaVersion MinVersionForCudaArch (CudaArch A)
Get the earliest CudaVersion that supports the given CudaArch.
CudaVersion MaxVersionForCudaArch (CudaArch A)
Get the latest CudaVersion that supports the given CudaArch.
CudaVersion ToCudaVersion (llvm::VersionTuple)
bool CudaFeatureEnabled (llvm::VersionTuple, CudaFeature)
bool CudaFeatureEnabled (CudaVersion, CudaFeature)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const AddFlagValue V)
Register a value for the flag in the current diagnostic.
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, StringRef S)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const char *Str)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, int I)
template<typename T >
std::enable_if_t< std::is_same< T, bool >::value, const StreamingDiagnostic & > operator<< (const StreamingDiagnostic &DB, T I)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, unsigned I)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, tok::TokenKind I)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const IdentifierInfo *II)
template<typename T >
std::enable_if_t< std::is_same< std::remove_const_t< T >, DeclContext >::value, const StreamingDiagnostic & > operator<< (const StreamingDiagnostic &DB, T *DC)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, SourceRange R)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, ArrayRef< SourceRange > Ranges)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const CharSourceRange &R)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const FixItHint &Hint)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, ArrayRef< FixItHint > Hints)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const llvm::Optional< SourceRange > &Opt)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const llvm::Optional< CharSourceRange > &Opt)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const llvm::Optional< FixItHint > &Opt)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, DiagNullabilityKind nullability)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, llvm::Error &&E)
void ProcessWarningOptions (DiagnosticsEngine &Diags, const DiagnosticOptions &Opts, bool ReportDiags=true)
ProcessWarningOptions - Initialize the diagnostic client and process the warning options specified on the command line.
DiagnosticLevelMask operator~ (DiagnosticLevelMask M)
DiagnosticLevelMask operator| (DiagnosticLevelMask LHS, DiagnosticLevelMask RHS)
DiagnosticLevelMask operator& (DiagnosticLevelMask LHS, DiagnosticLevelMask RHS)
raw_ostream & operator<< (raw_ostream &Out, DiagnosticLevelMask M)
bool isDynamicExceptionSpec (ExceptionSpecificationType ESpecType)
bool isComputedNoexcept (ExceptionSpecificationType ESpecType)
bool isNoexceptExceptionSpec (ExceptionSpecificationType ESpecType)
bool isUnresolvedExceptionSpec (ExceptionSpecificationType ESpecType)
CanThrowResult mergeCanThrow (CanThrowResult CT1, CanThrowResult CT2)
const char * getTraitName (ExpressionTrait T) LLVM_READONLY
Return the internal name of type trait T. Never null.
const char * getTraitSpelling (ExpressionTrait T) LLVM_READONLY
Return the spelling of the type trait TT. Never null.
raw_ostream & Indent (raw_ostream &Out, const unsigned int Space, bool IsDot)
std::string JsonFormat (StringRef RawSR, bool AddQuotes)
void printSourceLocationAsJson (raw_ostream &Out, SourceLocation Loc, const SourceManager &SM, bool AddBraces=true)
bool isDiscardableGVALinkage (GVALinkage L)
bool isUniqueGVALinkage (GVALinkage L)
Do we know that this will be the only definition of this symbol (excluding inlining-only definitions)?
bool isExternallyVisible (Linkage L)
Linkage getFormalLinkage (Linkage L)
bool isExternalFormalLinkage (Linkage L)
Linkage minLinkage (Linkage L1, Linkage L2)
Compute the minimum linkage given two linkages.
raw_ostream & operator<< (raw_ostream &out, const ObjCRuntime &value)
unsigned getOpenMPSimpleClauseType (OpenMPClauseKind Kind, llvm::StringRef Str, unsigned OpenMPVersion)
const char * getOpenMPSimpleClauseTypeName (OpenMPClauseKind Kind, unsigned Type)
bool isOpenMPLoopDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a directive with an associated loop construct.
bool isOpenMPWorksharingDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a worksharing directive.
bool isOpenMPTaskLoopDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a taskloop directive.
bool isOpenMPParallelDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a parallel-kind directive.
bool isOpenMPTargetExecutionDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a target code offload directive.
bool isOpenMPTargetDataManagementDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a target data offload directive.
bool isOpenMPNestingTeamsDirective (OpenMPDirectiveKind DKind)
Checks if the specified composite/combined directive constitutes a teams directive in the outermost nest.
bool isOpenMPTeamsDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a teams-kind directive.
bool isOpenMPSimdDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a simd directive.
bool isOpenMPDistributeDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a distribute directive.
bool isOpenMPNestingDistributeDirective (OpenMPDirectiveKind DKind)
Checks if the specified composite/combined directive constitutes a distribute directive in the outermost nest.
bool isOpenMPPrivate (OpenMPClauseKind Kind)
Checks if the specified clause is one of private clauses like 'private', 'firstprivate', 'reduction' etc.
bool isOpenMPThreadPrivate (OpenMPClauseKind Kind)
Checks if the specified clause is one of threadprivate clauses like 'threadprivate', 'copyin' or 'copyprivate'.
bool isOpenMPTaskingDirective (OpenMPDirectiveKind Kind)
Checks if the specified directive kind is one of tasking directives - task, taskloop, taksloop simd, master taskloop, parallel master taskloop, master taskloop simd, or parallel master taskloop simd.
bool isOpenMPLoopBoundSharingDirective (OpenMPDirectiveKind Kind)
Checks if the specified directive kind is one of the composite or combined directives that need loop bound sharing across loops outlined in nested functions.
void getOpenMPCaptureRegions (llvm::SmallVectorImpl< OpenMPDirectiveKind > &CaptureRegions, OpenMPDirectiveKind DKind)
Return the captured regions of an OpenMP directive.
const char * getOperatorSpelling (OverloadedOperatorKind Operator)
Retrieve the spelling of the given overloaded operator, without the preceding "operator" keyword.
OverloadedOperatorKind getRewrittenOverloadedOperator (OverloadedOperatorKind Kind)
Get the other overloaded operator that the given operator can be rewritten into, if any such operator exists.
bool isCompoundAssignmentOperator (OverloadedOperatorKind Kind)
Determine if this is a compound assignment operator.
prec::Level getBinOpPrecedence (tok::TokenKind Kind, bool GreaterThanIsOperator, bool CPlusPlus11)
Return the precedence of the specified binary operator token.
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const PartialDiagnostic &PD)
llvm::hash_code hash_value (const clang::SanitizerMask &Arg)
SanitizerMask parseSanitizerValue (StringRef Value, bool AllowGroups)
Parse a single value from a -fsanitize= or -fno-sanitize= value list.
SanitizerMask expandSanitizerGroups (SanitizerMask Kinds)
For each sanitizer group bit set in Kinds, set the bits for sanitizers this group enables.
SanitizerMask getPPTransparentSanitizers ()
Return the sanitizers which do not affect preprocessing.
bool operator== (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator!= (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator< (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator> (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator<= (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator>= (const SourceLocation &LHS, const SourceLocation &RHS)
bool operator< (const LineEntry &lhs, const LineEntry &rhs)
bool operator< (const LineEntry &E, unsigned Offset)
bool operator< (unsigned Offset, const LineEntry &E)
bool isTemplateInstantiation (TemplateSpecializationKind Kind)
Determine whether this template specialization kind refers to an instantiation of an entity (as opposed to a non-template or an explicit specialization).
bool isTemplateExplicitInstantiationOrSpecialization (TemplateSpecializationKind Kind)
True if this template specialization kind is an explicit specialization, explicit instantiation declaration, or explicit instantiation definition.
bool isLegalForFunction (StorageClass SC)
Checks whether the given storage class is legal for functions.
bool isLegalForVariable (StorageClass SC)
Checks whether the given storage class is legal for variables.
bool supportsVariadicCall (CallingConv CC)
Checks whether the given calling convention supports variadic calls.
bool hasWeakerNullability (NullabilityKind L, NullabilityKind R)
Return true if L has a weaker nullability annotation than R.
llvm::StringRef getNullabilitySpelling (NullabilityKind kind, bool isContextSensitive=false)
Retrieve the spelling of the given nullability kind.
llvm::StringRef getParameterABISpelling (ParameterABI kind)
llvm::StringRef getAccessSpelling (AccessSpecifier AS)
void noteBottomOfStack ()
Call this once on each thread, as soon after starting the thread as feasible, to note the approximate address of the bottom of the stack.
bool isStackNearlyExhausted ()
Determine whether the stack is nearly exhausted.
void runWithSufficientStackSpaceSlow (llvm::function_ref< void()> Diag, llvm::function_ref< void()> Fn)
void runWithSufficientStackSpace (llvm::function_ref< void()> Diag, llvm::function_ref< void()> Fn)
Run a given function on a stack with "sufficient" space.
llvm::StringRef getAsString (SyncScope S)
const llvm::SmallVector< llvm::StringRef, 4 > getAllPossibleTargetIDFeatures (const llvm::Triple &T, llvm::StringRef Processor)
Get all feature strings that can be used in target ID for Processor.
llvm::StringRef getProcessorFromTargetID (const llvm::Triple &T, llvm::StringRef OffloadArch)
Get processor name from target ID.
llvm::Optional< llvm::StringRef > parseTargetID (const llvm::Triple &T, llvm::StringRef OffloadArch, llvm::StringMap< bool > *FeatureMap)
Parse a target ID to get processor and feature map.
std::string getCanonicalTargetID (llvm::StringRef Processor, const llvm::StringMap< bool > &Features)
Returns canonical target ID, assuming Processor is canonical and all entries in Features are valid.
llvm::Optional< std::pair< llvm::StringRef, llvm::StringRef > > getConflictTargetIDCombination (const std::set< llvm::StringRef > &TargetIDs)
Get the conflicted pair of target IDs for a compilation or a bundled code object, assuming TargetIDs are canonicalized.
const char * getTraitName (TypeTrait T) LLVM_READONLY
Return the internal name of type trait T. Never null.
const char * getTraitName (ArrayTypeTrait T) LLVM_READONLY
const char * getTraitName (UnaryExprOrTypeTrait T) LLVM_READONLY
const char * getTraitSpelling (TypeTrait T) LLVM_READONLY
Return the spelling of the type trait TT. Never null.
const char * getTraitSpelling (ArrayTypeTrait T) LLVM_READONLY
const char * getTraitSpelling (UnaryExprOrTypeTrait T) LLVM_READONLY
std::string getClangRepositoryPath ()
Retrieves the repository path (e.g., Subversion path) that identifies the particular Clang branch, tag, or trunk from which this Clang was built.
std::string getLLVMRepositoryPath ()
Retrieves the repository path from which LLVM was built.
std::string getClangRevision ()
Retrieves the repository revision number (or identifier) from which this Clang was built.
std::string getLLVMRevision ()
Retrieves the repository revision number (or identifier) from which LLVM was built.
std::string getClangFullRepositoryVersion ()
Retrieves the full repository version that is an amalgamation of the information in getClangRepositoryPath() and getClangRevision().
std::string getClangFullVersion ()
Retrieves a string representing the complete clang version, which includes the clang version number, the repository version, and the vendor tag.
std::string getClangToolFullVersion (llvm::StringRef ToolName)
Like getClangFullVersion(), but with a custom tool name.
std::string getClangFullCPPVersion ()
Retrieves a string representing the complete clang version suitable for use in the CPP VERSION macro, which includes the clang version number, the repository version, and the vendor tag.
Visibility minVisibility (Visibility L, Visibility R)
XRayInstrMask parseXRayInstrValue (StringRef Value)
void EmitBackendOutput (DiagnosticsEngine &Diags, const HeaderSearchOptions &, const CodeGenOptions &CGOpts, const TargetOptions &TOpts, const LangOptions &LOpts, const llvm::DataLayout &TDesc, llvm::Module *M, BackendAction Action, std::unique_ptr< raw_pwrite_stream > OS)
void EmbedBitcode (llvm::Module *M, const CodeGenOptions &CGOpts, llvm::MemoryBufferRef Buf)
CodeGenerator * CreateLLVMCodeGen (DiagnosticsEngine &Diags, llvm::StringRef ModuleName, const HeaderSearchOptions &HeaderSearchOpts, const PreprocessorOptions &PreprocessorOpts, const CodeGenOptions &CGO, llvm::LLVMContext &C, CoverageSourceInfo *CoverageInfo=nullptr)
CreateLLVMCodeGen - Create a CodeGenerator instance.
int getLastArgIntValue (const llvm::opt::ArgList &Args, llvm::opt::OptSpecifier Id, int Default, DiagnosticsEngine *Diags=nullptr, unsigned Base=0)
Return the value of the last argument as an integer, or a default.
int getLastArgIntValue (const llvm::opt::ArgList &Args, llvm::opt::OptSpecifier Id, int Default, DiagnosticsEngine &Diags, unsigned Base=0)
uint64_t getLastArgUInt64Value (const llvm::opt::ArgList &Args, llvm::opt::OptSpecifier Id, uint64_t Default, DiagnosticsEngine *Diags=nullptr, unsigned Base=0)
uint64_t getLastArgUInt64Value (const llvm::opt::ArgList &Args, llvm::opt::OptSpecifier Id, uint64_t Default, DiagnosticsEngine &Diags, unsigned Base=0)
std::unique_ptr< ASTConsumer > CreateASTPrinter (std::unique_ptr< raw_ostream > OS, StringRef FilterString)
std::unique_ptr< ASTConsumer > CreateASTDumper (std::unique_ptr< raw_ostream > OS, StringRef FilterString, bool DumpDecls, bool Deserialize, bool DumpLookups, bool DumpDeclTypes, ASTDumpOutputFormat Format)
std::unique_ptr< ASTConsumer > CreateASTDeclNodeLister ()
std::unique_ptr< ASTConsumer > CreateASTViewer ()
bool ParseDiagnosticArgs (DiagnosticOptions &Opts, llvm::opt::ArgList &Args, clang::DiagnosticsEngine *Diags=nullptr, bool DefaultDiagColor=true)
Fill out Opts based on the options given in Args.
IntrusiveRefCntPtr< llvm::vfs::FileSystem > createVFSFromCompilerInvocation (const CompilerInvocation &CI, DiagnosticsEngine &Diags)
IntrusiveRefCntPtr< llvm::vfs::FileSystem > createVFSFromCompilerInvocation (const CompilerInvocation &CI, DiagnosticsEngine &Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > BaseFS)
PreambleBounds ComputePreambleBounds (const LangOptions &LangOpts, const llvm::MemoryBufferRef &Buffer, unsigned MaxLines)
Runs lexer to compute suggested preamble bounds.
std::error_code make_error_code (BuildPreambleError Error)
void ApplyHeaderSearchOptions (HeaderSearch &HS, const HeaderSearchOptions &HSOpts, const LangOptions &Lang, const llvm::Triple &triple)
Apply the header search options to get given HeaderSearch object.
void InitializePreprocessor (Preprocessor &PP, const PreprocessorOptions &PPOpts, const PCHContainerReader &PCHContainerRdr, const FrontendOptions &FEOpts)
InitializePreprocessor - Initialize the preprocessor getting it and the environment ready to process a single file.
void DoPrintPreprocessedInput (Preprocessor &PP, raw_ostream *OS, const PreprocessorOutputOptions &Opts)
DoPrintPreprocessedInput - Implement -E mode.
void AttachDependencyGraphGen (Preprocessor &PP, StringRef OutputFile, StringRef SysRoot)
AttachDependencyGraphGen - Create a dependency graph generator, and attach it to the given preprocessor.
void AttachHeaderIncludeGen (Preprocessor &PP, const DependencyOutputOptions &DepOpts, bool ShowAllHeaders=false, StringRef OutputPath={}, bool ShowDepth=true, bool MSStyle=false)
AttachHeaderIncludeGen - Create a header include list generator, and attach it to the given preprocessor.
IntrusiveRefCntPtr< ExternalSemaSource > createChainedIncludesSource (CompilerInstance &CI, IntrusiveRefCntPtr< ExternalSemaSource > &Reader)
The ChainedIncludesSource class converts headers to chained PCHs in memory, mainly for testing.
std::unique_ptr< CompilerInvocation > createInvocationFromCommandLine (ArrayRef< const char * > Args, IntrusiveRefCntPtr< DiagnosticsEngine > Diags=IntrusiveRefCntPtr< DiagnosticsEngine >(), IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS=nullptr, bool ShouldRecoverOnErrors=false, std::vector< std::string > *CC1Args=nullptr)
createInvocationFromCommandLine - Construct a compiler invocation object for a command line argument vector.
std::unique_ptr< FrontendAction > CreateFrontendAction (CompilerInstance &CI)
Construct the FrontendAction of a compiler invocation based on the options specified for the compiler invocation.
bool ExecuteCompilerInvocation (CompilerInstance *Clang)
ExecuteCompilerInvocation - Execute the given actions described by the compiler invocation object in the given compiler instance.
bool minimizeSourceToDependencyDirectives (llvm::StringRef Input, llvm::SmallVectorImpl< char > &Output, llvm::SmallVectorImpl< minimize_source_to_dependency_directives::Token > &Tokens, DiagnosticsEngine *Diags=nullptr, SourceLocation InputSourceLoc=SourceLocation())
Minimize the input down to the preprocessor directives that might have an effect on the dependencies for a compilation unit.
llvm::hash_code hash_value (const HeaderSearchOptions::Entry &E)
llvm::hash_code hash_value (const HeaderSearchOptions::SystemHeaderPrefix &SHP)
void expandUCNs (SmallVectorImpl< char > &Buf, StringRef Input)
Copy characters from Input to Buf, expanding any UCNs.
void ParseAST (Preprocessor &pp, ASTConsumer *C, ASTContext &Ctx, bool PrintStats=false, TranslationUnitKind TUKind=TU_Complete, CodeCompleteConsumer *CompletionConsumer=nullptr, bool SkipFunctionBodies=false)
Parse the entire file specified, notifying the ASTConsumer as the file is parsed.
void ParseAST (Sema &S, bool PrintStats=false, bool SkipFunctionBodies=false)
Parse the main file known to the preprocessor, producing an abstract syntax tree.
std::unique_ptr< ASTConsumer > CreateObjCRewriter (const std::string &InFile, std::unique_ptr< raw_ostream > OS, DiagnosticsEngine &Diags, const LangOptions &LOpts, bool SilenceRewriteMacroWarning)
std::unique_ptr< ASTConsumer > CreateModernObjCRewriter (const std::string &InFile, std::unique_ptr< raw_ostream > OS, DiagnosticsEngine &Diags, const LangOptions &LOpts, bool SilenceRewriteMacroWarning, bool LineInfo)
std::unique_ptr< ASTConsumer > CreateHTMLPrinter (std::unique_ptr< raw_ostream > OS, Preprocessor &PP, bool SyntaxHighlight=true, bool HighlightMacros=true)
CreateHTMLPrinter - Create an AST consumer which rewrites source code to HTML with syntax highlighting suitable for viewing in a web-browser.
void RewriteMacrosInInput (Preprocessor &PP, raw_ostream *OS)
RewriteMacrosInInput - Implement -rewrite-macros mode.
void DoRewriteTest (Preprocessor &PP, raw_ostream *OS)
DoRewriteTest - A simple test for the TokenRewriter class.
void RewriteIncludesInInput (Preprocessor &PP, raw_ostream *OS, const PreprocessorOutputOptions &Opts)
RewriteIncludesInInput - Implement -frewrite-includes mode.
SimplifiedTypeClass getSimplifiedTypeClass (CanQualType T)
Determine the simplified type class of the given canonical type.
QualType getDeclUsageType (ASTContext &C, const NamedDecl *ND)
Determine the type that this declaration will have if it is used as a type or in an expression.
unsigned getMacroUsagePriority (StringRef MacroName, const LangOptions &LangOpts, bool PreferredTypeIsPointer=false)
Determine the priority to be given to a macro code completion result with the given name.
CXCursorKind getCursorKindForDecl (const Decl *D)
Determine the libclang cursor kind associated with the given declaration.
llvm::StringRef getCompletionKindString (CodeCompletionContext::Kind Kind)
Get string representation of Kind, useful for for debugging.
bool operator< (const CodeCompletionResult &X, const CodeCompletionResult &Y)
bool operator> (const CodeCompletionResult &X, const CodeCompletionResult &Y)
bool operator<= (const CodeCompletionResult &X, const CodeCompletionResult &Y)
bool operator>= (const CodeCompletionResult &X, const CodeCompletionResult &Y)
const RawComment * getCompletionComment (const ASTContext &Ctx, const NamedDecl *Decl)
Get the documentation comment used to produce CodeCompletionString::BriefComment for RK_Declaration.
const RawComment * getPatternCompletionComment (const ASTContext &Ctx, const NamedDecl *Decl)
Get the documentation comment used to produce CodeCompletionString::BriefComment for RK_Pattern.
const RawComment * getParameterComment (const ASTContext &Ctx, const CodeCompleteConsumer::OverloadCandidate &Result, unsigned ArgIndex)
Get the documentation comment used to produce CodeCompletionString::BriefComment for OverloadCandidate.
ImplicitConversionRank GetConversionRank (ImplicitConversionKind Kind)
GetConversionRank - Retrieve the implicit conversion rank corresponding to the given implicit conversion kind.
bool isBetterOverloadCandidate (Sema &S, const OverloadCandidate &Cand1, const OverloadCandidate &Cand2, SourceLocation Loc, OverloadCandidateSet::CandidateSetKind Kind)
isBetterOverloadCandidate - Determines whether the first overload candidate is a better candidate than the second (C++ 13.3.3p1).
ConstructorInfo getConstructorInfo (NamedDecl *ND)
ExprResult ExprError ()
StmtResult StmtError ()
TypeResult TypeError ()
ExprResult ExprError (const StreamingDiagnostic &)
StmtResult StmtError (const StreamingDiagnostic &)
ExprResult ExprEmpty ()
StmtResult StmtEmpty ()
Expr * AssertSuccess (ExprResult R)
Stmt * AssertSuccess (StmtResult R)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const ParsedAttr &At)
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const ParsedAttr *At)
template<typename ACI , typename std::enable_if_t< std::is_same< ACI, AttributeCommonInfo >::value, int > = 0>
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const ACI &CI)
AttributeCommonInfo has a non-explicit constructor which takes an SourceRange as its only argument, this constructor has many uses so making it explicit is hard.
template<typename ACI , typename std::enable_if_t< std::is_same< ACI, AttributeCommonInfo >::value, int > = 0>
const StreamingDiagnostic & operator<< (const StreamingDiagnostic &DB, const ACI *CI)
SourceRange getTemplateParamsRange (TemplateParameterList const *const *Params, unsigned NumParams)
Retrieves the range of the given template parameter lists.
DeductionFailureInfo MakeDeductionFailureInfo (ASTContext &Context, Sema::TemplateDeductionResult TDK, sema::TemplateDeductionInfo &Info)
Convert from Sema's representation of template deduction information to the form used in overload-candidate information.
bool FTIHasSingleVoidParameter (const DeclaratorChunk::FunctionTypeInfo &FTI)
bool FTIHasNonVoidParameters (const DeclaratorChunk::FunctionTypeInfo &FTI)
bool DeclAttrsMatchCUDAMode (const LangOptions &LangOpts, Decl *D)
InheritableAttr * getDLLAttr (Decl *D)
Return a DLL attribute from the declaration.
std::pair< unsigned, unsigned > getDepthAndIndex (NamedDecl *ND)
Retrieve the depth and index of a template parameter.
std::pair< unsigned, unsigned > getDepthAndIndex (UnexpandedParameterPack UPP)
Retrieve the depth and index of an unexpanded parameter pack.
Optional< unsigned > getStackIndexOfNearestEnclosingCaptureCapableLambda (ArrayRef< const sema::FunctionScopeInfo * > FunctionScopes, VarDecl *VarToCapture, Sema &S)
Examines the FunctionScopeInfo stack to determine the nearest enclosing lambda (to the current lambda) that is 'capture-capable' for the variable referenced in the current lambda (i.e.
template<class TemplateInstantiationCallbackPtrs >
void initialize (TemplateInstantiationCallbackPtrs &Callbacks, const Sema &TheSema)
template<class TemplateInstantiationCallbackPtrs >
void finalize (TemplateInstantiationCallbackPtrs &Callbacks, const Sema &TheSema)
template<class TemplateInstantiationCallbackPtrs >
void atTemplateBegin (TemplateInstantiationCallbackPtrs &Callbacks, const Sema &TheSema, const Sema::CodeSynthesisContext &Inst)
template<class TemplateInstantiationCallbackPtrs >
void atTemplateEnd (TemplateInstantiationCallbackPtrs &Callbacks, const Sema &TheSema, const Sema::CodeSynthesisContext &Inst)
std::vector< std::string > getCommandLineArgsForTesting (TestLanguage Lang)
StringRef getFilenameForTesting (TestLanguage Lang)
bool operator== (const APValue::LValueBase &LHS, const APValue::LValueBase &RHS)
llvm::hash_code hash_value (const APValue::LValueBase &Base)
template<class T >
SmallVector< Decl *, 2 > getCanonicalForwardRedeclChain (Redeclarable< T > *D)
void updateFlags (const Decl *From, Decl *To)
static bool isWhitespace (llvm::StringRef S)
CXXABI * CreateItaniumCXXABI (ASTContext &Ctx)
Creates an instance of a C++ ABI class.
CXXABI * CreateMicrosoftCXXABI (ASTContext &Ctx)
std::unique_ptr< MangleNumberingContext > createItaniumNumberingContext (MangleContext *)
static const llvm::SmallVector< llvm::StringRef, 4 > getAllPossibleAMDGPUTargetIDFeatures (const llvm::Triple &T, llvm::StringRef Proc)
static llvm::StringRef getCanonicalProcessorName (const llvm::Triple &T, llvm::StringRef Processor)
Returns canonical processor name or empty string if Processor is invalid.
static llvm::Optional< llvm::StringRef > parseTargetIDWithFormatCheckingOnly (llvm::StringRef TargetID, llvm::StringMap< bool > *FeatureMap)
std::string getClangToolFullVersion (StringRef ToolName)
template<class U >
U cast (CodeGen::Address addr)
template<class U >
bool isa (CodeGen::Address addr)
static void reportOptRecordError (Error E, DiagnosticsEngine &Diags, const CodeGenOptions CodeGenOpts)
llvm::fp::ExceptionBehavior ToConstrainedExceptMD (LangOptions::FPExceptionModeKind Kind)
Optional< sys::fs::file_status > getFileStatus (StringRef Path)
std::vector< std::string > scanDirectory (StringRef Path)
std::vector< DirectoryWatcher::Event > getAsFileEvents (const std::vector< std::string > &Scan)
Create event with EventKind::Added for every element in Scan.
std::vector< std::string > scanDirectory (llvm::StringRef Path)
Gets names (filenames) of items in directory at Path.
llvm::Optional< llvm::sys::fs::file_status > getFileStatus (llvm::StringRef Path)
Gets status of file (or directory) at Path.
int getLastArgIntValue (const ArgList &Args, OptSpecifier Id, int Default, DiagnosticsEngine *Diags, unsigned Base)
uint64_t getLastArgUInt64Value (const ArgList &Args, OptSpecifier Id, uint64_t Default, DiagnosticsEngine *Diags, unsigned Base)
static std::unique_ptr< FrontendAction > CreateFrontendBaseAction (CompilerInstance &CI)
static const FunctionProtoType * GetUnderlyingFunction (QualType T)
static bool exceptionSpecNotKnownYet (const FunctionDecl *FD)
static bool CheckEquivalentExceptionSpecImpl (Sema &S, const PartialDiagnostic &DiagID, const PartialDiagnostic &NoteID, const FunctionProtoType *Old, SourceLocation OldLoc, const FunctionProtoType *New, SourceLocation NewLoc, bool *MissingExceptionSpecification, bool *MissingEmptyExceptionSpecification, bool AllowNoexceptAllMatchWithNoSpec, bool IsOperatorNew)
CheckEquivalentExceptionSpec - Check if the two types have compatible exception specifications.
static bool hasImplicitExceptionSpec (FunctionDecl *Decl)
Determine whether a function has an implicitly-generated exception specification.
static bool CheckSpecForTypesEquivalent (Sema &S, const PartialDiagnostic &DiagID, const PartialDiagnostic &NoteID, QualType Target, SourceLocation TargetLoc, QualType Source, SourceLocation SourceLoc)
static CanThrowResult canSubStmtsThrow (Sema &Self, const Stmt *S)
static CanThrowResult canVarDeclThrow (Sema &Self, const VarDecl *VD)
static CanThrowResult canDynamicCastThrow (const CXXDynamicCastExpr *DC)
static CanThrowResult canTypeidThrow (Sema &S, const CXXTypeidExpr *DC)
template<class TyLoc >
static QualType TransformTypeSpecType (TypeLocBuilder &TLB, TyLoc T)
template<typename Derived , class T >
bool transformOMPMappableExprListClause (TreeTransform< Derived > &TT, OMPMappableExprListClause< T > *C, llvm::SmallVectorImpl< Expr * > &Vars, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperIdInfo, llvm::SmallVectorImpl< Expr * > &UnresolvedMappers)
static bool isUndeducedReturnType (QualType T)
std::pair< const Expr *, bool > tryToFindPtrOrigin (const clang::Expr *E, bool StopAtFirstRefCountedObj)
This function de-facto defines a set of transformations that we consider safe (in heuristical sense).
bool isASafeCallArg (const clang::Expr *E)
For E referring to a ref-countable/-counted pointer/reference we return whether it's a safe call argument.
template<typename T >
std::string safeGetName (const T *ASTNode)
template<typename NamedDeclDerivedT >
void printQuotedQualifiedName (llvm::raw_ostream &Os, const NamedDeclDerivedT &D)
template<typename NamedDeclDerivedT >
void printQuotedName (llvm::raw_ostream &Os, const NamedDeclDerivedT &D)
llvm::Optional< const clang::CXXRecordDecl * > isRefCountable (const CXXBaseSpecifier *Base)
llvm::Optional< bool > isRefCountable (const CXXRecordDecl *R)
bool isCtorOfRefCounted (const clang::FunctionDecl *F)
llvm::Optional< bool > isUncounted (const CXXRecordDecl *Class)
llvm::Optional< bool > isUncountedPtr (const Type *T)
Optional< bool > isGetterOfRefCounted (const CXXMethodDecl *M)
bool isRefCounted (const CXXRecordDecl *R)
bool isPtrConversion (const FunctionDecl *F)
Variables
static const TerminalColor DeclKindNameColor = {llvm::raw_ostream::GREEN, true}
static const TerminalColor AttrColor = {llvm::raw_ostream::BLUE, true}
static const TerminalColor StmtColor = {llvm::raw_ostream::MAGENTA, true}
static const TerminalColor CommentColor = {llvm::raw_ostream::BLUE, false}
static const TerminalColor TypeColor = {llvm::raw_ostream::GREEN, false}
static const TerminalColor AddressColor = {llvm::raw_ostream::YELLOW, false}
static const TerminalColor LocationColor = {llvm::raw_ostream::YELLOW, false}
static const TerminalColor ValueKindColor = {llvm::raw_ostream::CYAN, false}
static const TerminalColor ObjectKindColor = {llvm::raw_ostream::CYAN, false}
static const TerminalColor ErrorsColor = {llvm::raw_ostream::RED, true}
static const TerminalColor NullColor = {llvm::raw_ostream::BLUE, false}
static const TerminalColor UndeserializedColor
static const TerminalColor CastColor = {llvm::raw_ostream::RED, false}
static const TerminalColor ValueColor = {llvm::raw_ostream::CYAN, true}
static const TerminalColor DeclNameColor = {llvm::raw_ostream::CYAN, true}
static const TerminalColor IndentColor = {llvm::raw_ostream::BLUE, false}
const char ToggleHighlight = 127
Special character that the diagnostic printer will use to toggle the bold attribute.
static constexpr int ObjCOrBuiltinIDBits = 15
static constexpr unsigned NumberOfOMPMapClauseModifiers
Number of allowed map-type-modifiers.
static constexpr unsigned NumberOfOMPMotionModifiers
Number of allowed motion-modifiers.
constexpr size_t DesiredStackSize = 8 << 20
The amount of stack space that Clang would like to be provided with.
static constexpr uint64_t LargestBuiltinID
CudaArchToStringMap arch_names []
Detailed Description
Dataflow Directional Tag Classes.
This header contains the declarations of functions which are used to widen loops which do not otherwise exit.
This header contains the declarations of functions which are used to decide which loops should be completely unrolled and mark their corresponding CFGBlocks.
These are used for tag dispatching within the dataflow solver/transfer functions to determine what direction a dataflow analysis flows.
It is done by tracking a stack of loops in the ProgramState. This way specific loops can be marked as completely unrolled. For considering a loop to be completely unrolled it has to fulfill the following requirements:
Currently only forStmts can be considered.
The bound has to be known.
The counter variable has not escaped before/in the body of the loop and changed only in the increment statement corresponding to the loop. It also has to be initialized by a literal in the corresponding initStmt.
Does not contain goto, switch and returnStmt.
The widening is done by invalidating anything which might be modified by the body of the loop.
Typedef Documentation
AnalyzerOptionsRef
using clang::AnalyzerOptionsRef = IntrusiveRefCntPtr<AnalyzerOptions>
Definition at line 405 of file AnalyzerOptions.h.
ArgsUnion
using clang::ArgsUnion = llvm::PointerUnion<Expr *, IdentifierLoc *>
A union of the various pointer types that can be passed to an ParsedAttr as an argument.
Definition at line 184 of file ParsedAttr.h.
ArgsVector
using clang::ArgsVector = llvm::SmallVector<ArgsUnion, 12U>
Definition at line 185 of file ParsedAttr.h.
ASTTemplateArgsPtr
using clang::ASTTemplateArgsPtr = MutableArrayRef<ParsedTemplateArgument>
Definition at line 274 of file Ownership.h.
AttrVec
using clang::AttrVec = SmallVector<Attr *, 4>
AttrVec - A vector of Attr, which is how they are stored on the AST.
Definition at line 29 of file AttrIterator.h.
BaseResult
using clang::BaseResult = ActionResult<CXXBaseSpecifier *>
Definition at line 265 of file Ownership.h.
CachedTokens
typedef SmallVector<Token, 4> clang::CachedTokens
A set of tokens that has been cached for later parsing.
Definition at line 1167 of file DeclSpec.h.
CanQualType
typedef CanQual< Type > clang::CanQualType = CanQual<Type>
Represents a canonical, potentially-qualified type.
Definition at line 212 of file CanonicalType.h.
CFGDomTree
using clang::CFGDomTree = CFGDominatorTreeImpl< false>
Definition at line 182 of file Dominators.h.
CFGPostDomTree
using clang::CFGPostDomTree = CFGDominatorTreeImpl< true>
Definition at line 183 of file Dominators.h.
const_ptr
template<typename T > using clang::const_ptr = std::add_pointer_t<std::add_const_t<T>>
Definition at line 7785 of file OpenMPClause.h.
ConstantExprKind
using clang::ConstantExprKind = Expr::ConstantExprKind
Definition at line 987 of file Expr.h.
ConversionSequenceList
typedef MutableArrayRef< ImplicitConversionSequence > clang::ConversionSequenceList
Initial value:
      llvm::MutableArrayRef<ImplicitConversionSequence>
A list of implicit conversion sequences for the arguments of an OverloadCandidate.
Definition at line 786 of file Overload.h.
CXXCastPath
typedef SmallVector< CXXBaseSpecifier *, 4 > clang::CXXCastPath
A simple array of base specifiers.
Definition at line 60 of file Expr.h.
DeclResult
using clang::DeclResult = ActionResult<Decl *>
Definition at line 268 of file Ownership.h.
DiagNullabilityKind
using clang::DiagNullabilityKind = std::pair<NullabilityKind, bool>
A nullability kind paired with a bit indicating whether it used a context-sensitive keyword.
Definition at line 1464 of file Diagnostic.h.
DiagOrStoredDiag
using clang::DiagOrStoredDiag
Initial value:
    llvm::PointerUnion<const Diagnostic *, const StoredDiagnostic *>
Definition at line 32 of file DiagnosticRenderer.h.
DomTreeNode
using clang::DomTreeNode = llvm::DomTreeNodeBase<CFGBlock>
Definition at line 38 of file Dominators.h.
ExcludedPreprocessorDirectiveSkipMapping
using clang::ExcludedPreprocessorDirectiveSkipMapping
Initial value:
    llvm::DenseMap<const char *, const PreprocessorSkippedRangeMapping *>
The datastructure that holds the mapping between the active memory buffers and the individual skip mappings.
Definition at line 25 of file PreprocessorExcludedConditionalDirectiveSkipMapping.h.
ExpectedDecl
using clang::ExpectedDecl = llvm::Expected<Decl *>
Definition at line 82 of file ASTImporter.cpp.
ExpectedExpr
using clang::ExpectedExpr = llvm::Expected<Expr *>
Definition at line 81 of file ASTImporter.cpp.
ExpectedName
using clang::ExpectedName = llvm::Expected<DeclarationName>
Definition at line 84 of file ASTImporter.cpp.
ExpectedSLoc
using clang::ExpectedSLoc = llvm::Expected<SourceLocation>
Definition at line 83 of file ASTImporter.cpp.
ExpectedStmt
using clang::ExpectedStmt = llvm::Expected<Stmt *>
Definition at line 80 of file ASTImporter.cpp.
ExpectedType
using clang::ExpectedType = llvm::Expected<QualType>
Definition at line 79 of file ASTImporter.cpp.
ExprDependence
using clang::ExprDependence = ExprDependenceScope::ExprDependence
Definition at line 49 of file DependenceFlags.h.
ExprResult
using clang::ExprResult = ActionResult<Expr *>
Definition at line 262 of file Ownership.h.
FrontendPluginRegistry
using clang::FrontendPluginRegistry = llvm::Registry<PluginASTAction>
The frontend plugin registry.
Definition at line 22 of file FrontendPluginRegistry.h.
IdentifierLocPair
using clang::IdentifierLocPair = std::pair<IdentifierInfo *, SourceLocation>
A simple pair of identifier info and location.
Definition at line 44 of file IdentifierTable.h.
LangASMap
using clang::LangASMap = unsigned[(unsigned)LangAS::FirstTargetAddressSpace]
The type of a lookup table which maps from language-specific address spaces to target-specific ones.
Definition at line 60 of file AddressSpaces.h.
LazyCXXBaseSpecifiersPtr
using clang::LazyCXXBaseSpecifiersPtr
Initial value:
    LazyOffsetPtr<CXXBaseSpecifier, uint64_t,
                  &ExternalASTSource::GetExternalCXXBaseSpecifiers>
A lazy pointer to a set of CXXBaseSpecifiers.
Definition at line 584 of file ExternalASTSource.h.
LazyCXXCtorInitializersPtr
using clang::LazyCXXCtorInitializersPtr
Initial value:
    LazyOffsetPtr<CXXCtorInitializer *, uint64_t,
                  &ExternalASTSource::GetExternalCXXCtorInitializers>
A lazy pointer to a set of CXXCtorInitializers.
Definition at line 579 of file ExternalASTSource.h.
LazyDeclPtr
using clang::LazyDeclPtr
Initial value:
    LazyOffsetPtr<Decl, uint32_t, &ExternalASTSource::GetExternalDecl>
A lazy pointer to a declaration.
Definition at line 575 of file ExternalASTSource.h.
LazyDeclStmtPtr
using clang::LazyDeclStmtPtr
Initial value:
    LazyOffsetPtr<Stmt, uint64_t, &ExternalASTSource::GetExternalDeclStmt>
A lazy pointer to a statement.
Definition at line 571 of file ExternalASTSource.h.
MemInitResult
using clang::MemInitResult = ActionResult<CXXCtorInitializer *>
Definition at line 266 of file Ownership.h.
ModuleBuildStack
using clang::ModuleBuildStack = ArrayRef<std::pair<std::string, FullSourceLoc>>
The stack used when building modules on demand, which is used to provide a link between the source managers of the different compiler instances.
Definition at line 610 of file SourceManager.h.
ModuleId
using clang::ModuleId = SmallVector<std::pair<std::string, SourceLocation>, 2>
Describes the name of a module.
Definition at line 53 of file Module.h.
ModuleIdPath
typedef ArrayRef< std::pair< IdentifierInfo *, SourceLocation > > clang::ModuleIdPath = ArrayRef<std::pair<IdentifierInfo *, SourceLocation>>
A sequence of identifier/location pairs used to describe a particular module or submodule, e.g., std.vector.
Definition at line 32 of file ModuleLoader.h.
MultiExprArg
using clang::MultiExprArg = MutableArrayRef<Expr *>
Definition at line 272 of file Ownership.h.
MultiStmtArg
using clang::MultiStmtArg = MutableArrayRef<Stmt *>
Definition at line 273 of file Ownership.h.
MultiTemplateParamsArg
using clang::MultiTemplateParamsArg = MutableArrayRef<TemplateParameterList *>
Definition at line 276 of file Ownership.h.
MultiTypeArg
using clang::MultiTypeArg = MutableArrayRef<ParsedType>
Definition at line 275 of file Ownership.h.
OpenMPClauseKind
using clang::OpenMPClauseKind = llvm::omp::Clause
OpenMP clauses.
Definition at line 26 of file OpenMPKinds.h.
OpenMPDirectiveKind
using clang::OpenMPDirectiveKind = llvm::omp::Directive
OpenMP directives.
Definition at line 23 of file OpenMPKinds.h.
ParsedAttrInfoRegistry
typedef llvm::Registry<ParsedAttrInfo> clang::ParsedAttrInfoRegistry
Definition at line 118 of file ParsedAttr.h.
ParsedTemplateTy
using clang::ParsedTemplateTy = OpaquePtr<TemplateName>
Definition at line 269 of file Ownership.h.
ParsedType
using clang::ParsedType = OpaquePtr<QualType>
An opaque type for threading parsed type information through the parser.
Definition at line 243 of file Ownership.h.
PartialDiagnosticAt
using clang::PartialDiagnosticAt = std::pair<SourceLocation, PartialDiagnostic>
A partial diagnostic along with the source location where this diagnostic occurs.
Definition at line 208 of file PartialDiagnostic.h.
PragmaHandlerRegistry
using clang::PragmaHandlerRegistry = llvm::Registry<PragmaHandler>
Registry of pragma handlers added by plugins.
Definition at line 2413 of file Preprocessor.h.
PreprocessorSkippedRangeMapping
using clang::PreprocessorSkippedRangeMapping = llvm::DenseMap<unsigned, unsigned>
A mapping from an offset into a buffer to the number of bytes that can be skipped by the preprocessor when skipping over excluded conditional directive ranges.
Definition at line 21 of file PreprocessorExcludedConditionalDirectiveSkipMapping.h.
StmtResult
using clang::StmtResult = ActionResult<Stmt *>
Definition at line 263 of file Ownership.h.
TemplateParameter
using clang::TemplateParameter
Initial value:
    llvm::PointerUnion<TemplateTypeParmDecl *, NonTypeTemplateParmDecl *,
                       TemplateTemplateParmDecl *>
Stores a template parameter of any kind.
Definition at line 61 of file DeclTemplate.h.
TextDiagnosticFormat
using clang::TextDiagnosticFormat = DiagnosticOptions::TextDiagnosticFormat
Definition at line 140 of file DiagnosticOptions.h.
TypeDependence
using clang::TypeDependence = TypeDependenceScope::TypeDependence
Definition at line 80 of file DependenceFlags.h.
TypeIsArrayType
template<typename T > using clang::TypeIsArrayType
Initial value:
    std::integral_constant<bool, std::is_same<T, ArrayType>::value ||
                                     std::is_base_of<ArrayType, T>::value>
Definition at line 7140 of file Type.h.
TypeResult
using clang::TypeResult = ActionResult<ParsedType>
Definition at line 264 of file Ownership.h.
UnexpandedParameterPack
typedef std::pair<llvm::PointerUnion<const TemplateTypeParmType*, NamedDecl*>, SourceLocation> clang::UnexpandedParameterPack
Definition at line 239 of file Sema.h.
UnionParsedTemplateTy
using clang::UnionParsedTemplateTy = UnionOpaquePtr<TemplateName>
Definition at line 270 of file Ownership.h.
UnionParsedType
using clang::UnionParsedType = UnionOpaquePtr<QualType>
Definition at line 244 of file Ownership.h.
UnsatisfiedConstraintRecord
using clang::UnsatisfiedConstraintRecord
Initial value:
    std::pair<const Expr *,
              llvm::PointerUnion<Expr *,
                                 std::pair<SourceLocation, StringRef> *>>
Pairs of unsatisfied atomic constraint expressions along with the substituted constraint expr, if the template arguments could be substituted into them, or a diagnostic if substitution resulted in an invalid expression.
Definition at line 68 of file ASTConcept.h.
VPtrInfoVector
typedef SmallVector<std::unique_ptr<VPtrInfo>, 2> clang::VPtrInfoVector
Definition at line 494 of file VTableBuilder.h.
XRayInstrMask
using clang::XRayInstrMask = uint32_t
Definition at line 25 of file XRayInstr.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TypeAlignmentInBits
TypeAlignment
Definition at line 67 of file Type.h.
anonymous enum
anonymous enum
IdentifierInfo and other related classes are aligned to 8 bytes so that DeclarationName can use the lower 3 bits of a pointer to one of these classes.
Enumerator
IdentifierInfoAlignment
Definition at line 49 of file IdentifierTable.h.
anonymous enum
anonymous enum
Enough bits to store any enumerator in ObjCMethodFamily or InvalidObjCMethodFamily.
Enumerator
ObjCMethodFamilyBitWidth
Definition at line 653 of file IdentifierTable.h.
anonymous enum
anonymous enum
An invalid value of ObjCMethodFamily.
Enumerator
InvalidObjCMethodFamily
Definition at line 656 of file IdentifierTable.h.
anonymous enum
anonymous enum
Enumerator
HMAP_HeaderMagicNumber
HMAP_HeaderVersion
HMAP_EmptyBucketKey
Definition at line 16 of file HeaderMapTypes.h.
anonymous enum
anonymous enum
Default priority values for code-completion results based on their kind.
Enumerator
CCP_NextInitializer
Priority for the next initialization in a constructor initializer list.
CCP_EnumInCase
Priority for an enumeration constant inside a switch whose condition is of the enumeration type.
CCP_SuperCompletion
Priority for a send-to-super completion.
CCP_LocalDeclaration
Priority for a declaration that is in the local scope.
CCP_MemberDeclaration
Priority for a member declaration found from the current method or member function.
CCP_Keyword
Priority for a language keyword (that isn't any of the other categories).
CCP_CodePattern
Priority for a code pattern.
CCP_Declaration
Priority for a non-type declaration.
CCP_Type
Priority for a type.
CCP_Constant
Priority for a constant value (e.g., enumerator).
CCP_Macro
Priority for a preprocessor macro.
CCP_NestedNameSpecifier
Priority for a nested-name-specifier.
CCP_Unlikely
Priority for a result that isn't likely to be what the user wants, but is included for completeness.
CCP_ObjC_cmd
Priority for the Objective-C "_cmd" implicit parameter.
Definition at line 54 of file CodeCompleteConsumer.h.
anonymous enum
anonymous enum
Priority value deltas that are added to code-completion results based on the context of the result.
Enumerator
CCD_InBaseClass
The result is in a base class.
CCD_ObjectQualifierMatch
The result is a C++ non-static member function whose qualifiers exactly match the object type on which the member function can be called.
CCD_SelectorMatch
The selector of the given message exactly matches the selector of the current method, which might imply that some kind of delegation is occurring.
CCD_bool_in_ObjC
Adjustment to the "bool" type in Objective-C, where the typedef "BOOL" is preferred.
CCD_ProbablyNotObjCCollection
Adjustment for KVC code pattern priorities when it doesn't look like the.
CCD_MethodAsProperty
An Objective-C method being used as a property.
CCD_BlockPropertySetter
An Objective-C block property completed as a setter with a block placeholder.
Definition at line 105 of file CodeCompleteConsumer.h.
anonymous enum
anonymous enum
Priority value factors by which we will divide or multiply the priority of a code-completion result.
Enumerator
CCF_ExactTypeMatch
Divide by this factor when a code-completion result's type exactly matches the type we expect.
CCF_SimilarTypeMatch
Divide by this factor when a code-completion result's type is similar to the type we expect (e.g., both arithmetic types, both Objective-C object pointer types).
Definition at line 136 of file CodeCompleteConsumer.h.
anonymous enum
anonymous enum
Enumerator
NumObjCPropertyAttrsBits
Number of bits fitting all the property attributes.
Definition at line 48 of file DeclObjCCommon.h.
AccessKinds
enum clang::AccessKinds
Kinds of access we can perform on an object, for diagnostics.
Note that we consider a member function call to be a kind of access, even though it is not formally an access of the object, because it has (largely) the same set of semantic restrictions.
Enumerator
AK_Read
AK_ReadObjectRepresentation
AK_Assign
AK_Increment
AK_Decrement
AK_MemberCall
AK_DynamicCast
AK_TypeId
AK_Construct
AK_Destroy
Definition at line 26 of file State.h.
AccessSpecifier
enum clang::AccessSpecifier
A C++ access specifier (public, private, protected), plus the special value "none" which means different things in different contexts.
Enumerator
AS_public
AS_protected
AS_private
AS_none
Definition at line 98 of file Specifiers.h.
Analyses
enum clang::Analyses
Analysis - Set of available source code analyses.
Enumerator
NumAnalyses
Definition at line 37 of file AnalyzerOptions.h.
AnalysisConstraints
enum clang::AnalysisConstraints
AnalysisConstraints - Set of available constraint models.
Enumerator
NumConstraints
Definition at line 51 of file AnalyzerOptions.h.
AnalysisDiagClients
enum clang::AnalysisDiagClients
AnalysisDiagClients - Set of available diagnostic clients for rendering analysis results.
Enumerator
PD_NONE
NUM_ANALYSIS_DIAG_CLIENTS
Definition at line 59 of file AnalyzerOptions.h.
AnalysisInliningMode
enum clang::AnalysisInliningMode
AnalysisInlineFunctionSelection - Set of inlining function selection heuristics.
Enumerator
NumInliningModes
Definition at line 74 of file AnalyzerOptions.h.
AnalysisPurgeMode
enum clang::AnalysisPurgeMode
AnalysisPurgeModes - Set of available strategies for dead symbol removal.
Enumerator
NumPurgeModes
Definition at line 67 of file AnalyzerOptions.h.
AnalysisStores
enum clang::AnalysisStores
AnalysisStores - Set of available analysis store models.
Enumerator
NumStores
Definition at line 44 of file AnalyzerOptions.h.
ArrayTypeTrait
enum clang::ArrayTypeTrait
Names for the array type traits.
Enumerator
ATT_Last
Definition at line 42 of file TypeTraits.h.
ASTDumpOutputFormat
enum clang::ASTDumpOutputFormat
Used to specify the format for printing AST dump information.
Enumerator
ADOF_Default
ADOF_JSON
Definition at line 21 of file ASTDumperUtils.h.
AtomicScopeModelKind
enum class clang::AtomicScopeModelKind strong
Defines the kind of atomic scope models.
Enumerator
None
OpenCL
Definition at line 65 of file SyncScope.h.
AttributeArgumentNType
enum clang::AttributeArgumentNType
These constants match the enumerated choices of err_attribute_argument_n_type and err_attribute_argument_type.
Enumerator
AANT_ArgumentIntOrBool
AANT_ArgumentIntegerConstant
AANT_ArgumentString
AANT_ArgumentIdentifier
AANT_ArgumentConstantExpr
Definition at line 1022 of file ParsedAttr.h.
AttributeDeclKind
enum clang::AttributeDeclKind
These constants match the enumerated choices of warn_attribute_wrong_decl_type and err_attribute_wrong_decl_type.
Enumerator
ExpectedFunction
ExpectedUnion
ExpectedVariableOrFunction
ExpectedFunctionOrMethod
ExpectedFunctionMethodOrBlock
ExpectedFunctionMethodOrParameter
ExpectedVariable
ExpectedVariableOrField
ExpectedVariableFieldOrTag
ExpectedTypeOrNamespace
ExpectedFunctionVariableOrClass
ExpectedKernelFunction
ExpectedFunctionWithProtoType
Definition at line 1032 of file ParsedAttr.h.
AttrSyntax
enum class clang::AttrSyntax strong
Enumerator
GNU
Is the identifier known as a GNU-style attribute?
Declspec
Is the identifier known as a __declspec-style attribute?
Microsoft
Is the identifier known as a [] Microsoft-style attribute?
CXX
C
Pragma
Definition at line 19 of file Attributes.h.
AutoTypeKeyword
enum class clang::AutoTypeKeyword strong
Which keyword(s) were used to create an AutoType.
Enumerator
Auto
auto
DecltypeAuto
decltype(auto)
GNUAutoType
__auto_type (GNU extension)
Definition at line 1441 of file Type.h.
AvailabilityResult
enum clang::AvailabilityResult
Captures the result of checking the availability of a declaration.
Enumerator
AR_Available
AR_NotYetIntroduced
AR_Deprecated
AR_Unavailable
Definition at line 75 of file DeclBase.h.
BackendAction
enum clang::BackendAction
Enumerator
Backend_EmitAssembly
Emit native assembly files.
Backend_EmitBC
Emit LLVM bitcode files.
Backend_EmitLL
Emit human-readable LLVM assembly.
Backend_EmitNothing
Don't emit anything (benchmarking mode)
Backend_EmitMCNull
Run CodeGen, but don't emit anything.
Backend_EmitObj
Emit native object files.
Definition at line 30 of file BackendUtil.h.
BinaryOperatorKind
enum clang::BinaryOperatorKind
Definition at line 25 of file OperationKinds.h.
BuildPreambleError
enum class clang::BuildPreambleError strong
Enumerator
CouldntCreateTempFile
CouldntCreateTargetInfo
BeginSourceFileFailed
CouldntEmitPCH
BadInputs
Definition at line 304 of file PrecompiledPreamble.h.
BuiltinTemplateKind
enum clang::BuiltinTemplateKind : int
Kinds of BuiltinTemplateDecl.
Enumerator
BTK__make_integer_seq
This names the __make_integer_seq BuiltinTemplateDecl.
BTK__type_pack_element
This names the __type_pack_element BuiltinTemplateDecl.
Definition at line 253 of file Builtins.h.
CallingConv
enum clang::CallingConv
CallingConv - Specifies the calling convention that a function uses.
Enumerator
CC_C
CC_X86StdCall
CC_X86FastCall
CC_X86ThisCall
CC_X86VectorCall
CC_X86Pascal
CC_Win64
CC_X86_64SysV
CC_X86RegCall
CC_AAPCS
CC_AAPCS_VFP
CC_IntelOclBicc
CC_SpirFunction
CC_OpenCLKernel
CC_Swift
CC_PreserveMost
CC_PreserveAll
CC_AArch64VectorCall
Definition at line 253 of file Specifiers.h.
CanThrowResult
enum clang::CanThrowResult
Possible results from evaluation of a noexcept expression.
Enumerator
CT_Cannot
CT_Dependent
CT_Can
Definition at line 54 of file ExceptionSpecificationType.h.
CaptureDiagsKind
enum class clang::CaptureDiagsKind strong
Enumerates the available kinds for capturing diagnostics.
Enumerator
None
All
AllWithoutNonErrorsFromIncludes
Definition at line 86 of file ASTUnit.h.
CapturedRegionKind
enum clang::CapturedRegionKind
The different kinds of captured statement.
Enumerator
CR_Default
CR_ObjCAtFinally
CR_OpenMP
Definition at line 16 of file CapturedStmt.h.
CastKind
enum clang::CastKind
CastKind - The kind of operation required for a conversion.
Definition at line 20 of file OperationKinds.h.
CheckSubobjectKind
enum clang::CheckSubobjectKind
Enumerator
CSK_Base
CSK_Derived
CSK_Field
CSK_ArrayToPointer
CSK_ArrayIndex
CSK_Real
CSK_Imag
Definition at line 40 of file State.h.
ComparisonCategoryResult
enum class clang::ComparisonCategoryResult : unsigned char strong
An enumeration representing the possible results of a three-way comparison.
These values map onto instances of comparison category types defined in the standard library. e.g. 'std::strong_ordering::less'.
Enumerator
Equal
Equivalent
Less
Greater
Unordered
Last
Definition at line 65 of file ComparisonCategories.h.
ComparisonCategoryType
enum class clang::ComparisonCategoryType : unsigned char strong
An enumeration representing the different comparison categories types.
C++2a [cmp.categories.pre] The types weak_equality, strong_equality, partial_ordering, weak_ordering, and strong_ordering are collectively termed the comparison category types.
Enumerator
PartialOrdering
WeakOrdering
StrongOrdering
First
Last
Definition at line 43 of file ComparisonCategories.h.
ConflictMarkerKind
enum clang::ConflictMarkerKind
ConflictMarkerKind - Kinds of conflict marker which the lexer might be recovering from.
Enumerator
CMK_None
Not within a conflict marker.
CMK_Normal
A normal or diff3 conflict marker, initiated by at least 7 "<"s, separated by at least 7 "="s or "|"s, and terminated by at least 7 ">"s.
CMK_Perforce
A Perforce-style conflict marker, initiated by 4 ">"s, separated by 4 "="s, and terminated by 4 "<"s.
Definition at line 42 of file Lexer.h.
ConstexprSpecKind
enum class clang::ConstexprSpecKind strong
Define the kind of constexpr specifier.
Enumerator
Unspecified
Constexpr
Consteval
Constinit
Definition at line 32 of file Specifiers.h.
CudaArch
enum class clang::CudaArch strong
Enumerator
UNUSED
UNKNOWN
SM_20
SM_21
SM_30
SM_32
SM_35
SM_37
SM_50
SM_52
SM_53
SM_60
SM_61
SM_62
SM_70
SM_72
SM_75
SM_80
GFX600
GFX601
GFX602
GFX700
GFX701
GFX702
GFX703
GFX704
GFX705
GFX801
GFX802
GFX803
GFX805
GFX810
GFX900
GFX902
GFX904
GFX906
GFX908
GFX909
GFX90c
GFX1010
GFX1011
GFX1012
GFX1030
GFX1031
GFX1032
GFX1033
LAST
Definition at line 39 of file Cuda.h.
CudaFeature
enum class clang::CudaFeature strong
Enumerator
CUDA_USES_NEW_LAUNCH
CUDA_USES_FATBIN_REGISTER_END
Definition at line 110 of file Cuda.h.
CudaVersion
enum class clang::CudaVersion strong
Enumerator
UNKNOWN
CUDA_70
CUDA_75
CUDA_80
CUDA_90
CUDA_91
CUDA_92
CUDA_100
CUDA_101
CUDA_102
CUDA_110
LATEST
LATEST_SUPPORTED
Definition at line 20 of file Cuda.h.
CXXCtorType
enum clang::CXXCtorType
C++ constructor types.
Enumerator
Ctor_Complete
Complete object ctor.
Ctor_Base
Base object ctor.
Ctor_Comdat
The COMDAT used for ctors.
Ctor_CopyingClosure
Copying closure variant of a ctor.
Ctor_DefaultClosure
Default closure variant of a ctor.
Definition at line 24 of file ABI.h.
CXXDtorType
enum clang::CXXDtorType
C++ destructor types.
Enumerator
Dtor_Deleting
Deleting dtor.
Dtor_Complete
Complete object dtor.
Dtor_Base
Base object dtor.
Dtor_Comdat
The COMDAT used for dtors.
Definition at line 33 of file ABI.h.
CXXInlineableMemberKind
enum clang::CXXInlineableMemberKind
Describes the different kinds of C++ member functions which can be considered for inlining by the analyzer.
These options are cumulative; enabling one kind of member function will enable all kinds with lower enum values.
Enumerator
CIMK_None
A dummy mode in which no C++ inlining is enabled.
CIMK_MemberFunctions
Refers to regular member function and operator calls.
CIMK_Constructors
Refers to constructors (implicit or explicit).
Note that a constructor will not be inlined if the corresponding destructor is non-trivial.
CIMK_Destructors
Refers to destructors (implicit or explicit).
Definition at line 85 of file AnalyzerOptions.h.
DeclaratorContext
enum class clang::DeclaratorContext strong
Enumerator
File
Prototype
ObjCResult
ObjCParameter
KNRTypeList
TypeName
FunctionalCast
Member
Block
ForInit
SelectionInit
Condition
TemplateParam
CXXNew
CXXCatch
ObjCCatch
BlockLiteral
LambdaExpr
LambdaExprParameter
ConversionId
TrailingReturn
TrailingReturnVar
TemplateArg
TemplateTypeArg
AliasDecl
AliasTemplate
RequiresExpr
Definition at line 1761 of file DeclSpec.h.
DependencyOutputFormat
enum class clang::DependencyOutputFormat strong
DependencyOutputFormat - Format for the compiler dependency file.
Enumerator
Make
NMake
Definition at line 21 of file DependencyOutputOptions.h.
DiagnosticLevelMask
enum class clang::DiagnosticLevelMask : unsigned strong
A bitmask representing the diagnostic levels used by VerifyDiagnosticConsumer.
Enumerator
None
Note
Remark
Warning
Error
All
Definition at line 39 of file DiagnosticOptions.h.
DisableValidationForModuleKind
enum class clang::DisableValidationForModuleKind strong
Whether to disable the normal validation performed on precompiled headers and module files when they are loaded.
Enumerator
None
Perform validation, don't disable it.
PCH
Disable validation for a precompiled header and the modules it depends on.
Module
Disable validation for module files.
All
Disable validation for all kinds.
Definition at line 46 of file PreprocessorOptions.h.
DynamicInitKind
enum class clang::DynamicInitKind : unsigned strong
Enumerator
NoStub
Initializer
AtExit
GlobalArrayDestructor
Definition at line 31 of file GlobalDecl.h.
ElaboratedTypeKeyword
enum clang::ElaboratedTypeKeyword
The elaboration keyword that precedes a qualified type name or introduces an elaborated-type-specifier.
Enumerator
ETK_Struct
The "struct" keyword introduces the elaborated-type-specifier.
ETK_Interface
The "__interface" keyword introduces the elaborated-type-specifier.
ETK_Union
The "union" keyword introduces the elaborated-type-specifier.
ETK_Class
The "class" keyword introduces the elaborated-type-specifier.
ETK_Enum
The "enum" keyword introduces the elaborated-type-specifier.
ETK_Typename
The "typename" keyword precedes the qualified type name, e.g., typename T::type.
ETK_None
No keyword precedes the qualified type name.
Definition at line 5319 of file Type.h.
ExceptionSpecificationType
enum clang::ExceptionSpecificationType
The various types of exception specifications that exist in C++11.
Enumerator
EST_None
no exception specification
EST_DynamicNone
throw()
EST_Dynamic
throw(T1, T2)
EST_MSAny
Microsoft throw(...) extension.
EST_NoThrow
Microsoft __declspec(nothrow) extension.
EST_BasicNoexcept
noexcept
EST_DependentNoexcept
noexcept(expression), value-dependent
EST_NoexceptFalse
noexcept(expression), evals to 'false'
EST_NoexceptTrue
noexcept(expression), evals to 'true'
EST_Unevaluated
not evaluated yet, for special member function
EST_Uninstantiated
not instantiated yet
EST_Unparsed
not parsed yet
Definition at line 20 of file ExceptionSpecificationType.h.
ExplicitSpecKind
enum class clang::ExplicitSpecKind : unsigned strong
Define the meaning of possible values of the kind in ExplicitSpecifier.
Enumerator
ResolvedFalse
ResolvedTrue
Unresolved
Definition at line 25 of file Specifiers.h.
ExplorationStrategyKind
enum class clang::ExplorationStrategyKind strong
Enumerator
DFS
BFS
UnexploredFirst
UnexploredFirstQueue
UnexploredFirstLocationQueue
BFSBlockDFSContents
Definition at line 123 of file AnalyzerOptions.h.
ExpressionTrait
enum clang::ExpressionTrait
Enumerator
ET_Last
Definition at line 21 of file ExpressionTraits.h.
ExprObjectKind
enum clang::ExprObjectKind
A further classification of the kind of object referenced by an l-value or x-value.
Enumerator
OK_Ordinary
An ordinary object is located at an address in memory.
OK_BitField
A bitfield object is a bitfield on a C or C++ record.
OK_VectorComponent
A vector component is an element or range of elements on a vector.
OK_ObjCProperty
An Objective-C property is a logical field of an Objective-C object which is read and written via Objective-C method calls.
OK_ObjCSubscript
An Objective-C array/dictionary subscripting which reads an object or writes at the subscripted array/dictionary element via Objective-C method calls.
OK_MatrixComponent
A matrix component is a single element of a matrix.
Definition at line 124 of file Specifiers.h.
ExprValueKind
enum clang::ExprValueKind
The categorization of expression values, currently following the C++11 scheme.
Enumerator
VK_RValue
An r-value expression (a pr-value in the C++11 taxonomy) produces a temporary value.
VK_LValue
An l-value expression is a reference to an object with independent storage.
VK_XValue
An x-value expression is a reference to an object with independent storage but which can be "moved", i.e.
efficiently cannibalized for its resources.
Definition at line 107 of file Specifiers.h.
FunctionDefinitionKind
enum class clang::FunctionDefinitionKind strong
Described the kind of function definition (if any) provided for a function.
Enumerator
Declaration
Definition
Defaulted
Deleted
Definition at line 1754 of file DeclSpec.h.
GVALinkage
enum clang::GVALinkage
A more specific kind of linkage than enum Linkage.
This is relevant to CodeGen and AST file reading.
Enumerator
GVA_Internal
GVA_AvailableExternally
GVA_DiscardableODR
GVA_StrongExternal
GVA_StrongODR
Definition at line 73 of file Linkage.h.
ImplicitConversionKind
enum clang::ImplicitConversionKind
ImplicitConversionKind - The kind of implicit conversion used to convert an argument to a parameter's type.
The enumerator values match with the table titled 'Conversions' in [over.ics.scs] and are listed such that better conversion kinds have smaller values.
Enumerator
ICK_Identity
Identity conversion (no conversion)
ICK_Lvalue_To_Rvalue
Lvalue-to-rvalue conversion (C++ [conv.lval])
ICK_Array_To_Pointer
Array-to-pointer conversion (C++ [conv.array])
ICK_Function_To_Pointer
Function-to-pointer (C++ [conv.array])
ICK_Function_Conversion
Function pointer conversion (C++17 [conv.fctptr])
ICK_Qualification
Qualification conversions (C++ [conv.qual])
ICK_Integral_Promotion
Integral promotions (C++ [conv.prom])
ICK_Floating_Promotion
Floating point promotions (C++ [conv.fpprom])
ICK_Complex_Promotion
Complex promotions (Clang extension)
ICK_Integral_Conversion
Integral conversions (C++ [conv.integral])
ICK_Floating_Conversion
Floating point conversions (C++ [conv.double].
ICK_Complex_Conversion
Complex conversions (C99 6.3.1.6)
ICK_Floating_Integral
Floating-integral conversions (C++ [conv.fpint])
ICK_Pointer_Conversion
Pointer conversions (C++ [conv.ptr])
ICK_Pointer_Member
Pointer-to-member conversions (C++ [conv.mem])
ICK_Boolean_Conversion
Boolean conversions (C++ [conv.bool])
ICK_Compatible_Conversion
Conversions between compatible types in C99.
ICK_Derived_To_Base
Derived-to-base (C++ [over.best.ics])
ICK_Vector_Conversion
Vector conversions.
ICK_SVE_Vector_Conversion
Arm SVE Vector conversions.
ICK_Vector_Splat
A vector splat from an arithmetic type.
ICK_Complex_Real
Complex-real conversions (C99 6.3.1.7)
ICK_Block_Pointer_Conversion
Block Pointer conversions.
ICK_TransparentUnionConversion
Transparent Union Conversions.
ICK_Writeback_Conversion
Objective-C ARC writeback conversion.
ICK_Zero_Event_Conversion
Zero constant to event (OpenCL1.2 6.12.10)
ICK_Zero_Queue_Conversion
Zero constant to queue.
ICK_C_Only_Conversion
Conversions allowed in C, but not C++.
ICK_Incompatible_Pointer_Conversion
C-only conversion between pointers with incompatible types.
ICK_Num_Conversion_Kinds
The number of conversion kinds.
Definition at line 105 of file Overload.h.
ImplicitConversionRank
enum clang::ImplicitConversionRank
ImplicitConversionRank - The rank of an implicit conversion kind.
The enumerator values match with Table 9 of (C++ 13.3.3.1.1) and are listed such that better conversion ranks have smaller values.
Enumerator
ICR_Exact_Match
Exact Match.
ICR_Promotion
Promotion.
ICR_Conversion
Conversion.
ICR_OCL_Scalar_Widening
OpenCL Scalar Widening.
ICR_Complex_Real_Conversion
Complex <-> Real conversion.
ICR_Writeback_Conversion
ObjC ARC writeback conversion.
ICR_C_Conversion
Conversion only allowed in the C standard (e.g. void* to char*).
ICR_C_Conversion_Extension
Conversion not allowed by the C standard, but that we accept as an extension anyway.
Definition at line 201 of file Overload.h.
InClassInitStyle
enum clang::InClassInitStyle
In-class initialization styles for non-static data members.
Enumerator
ICIS_NoInit
No in-class initializer.
ICIS_CopyInit
Copy initialization.
ICIS_ListInit
Direct list-initialization.
Definition at line 246 of file Specifiers.h.
IPAKind
enum clang::IPAKind
Describes the different modes of inter-procedural analysis.
Enumerator
IPAK_None
Perform only intra-procedural analysis.
IPAK_BasicInlining
Inline C functions and blocks when their definitions are available.
IPAK_Inlining
Inline callees(C, C++, ObjC) when their definitions are available.
IPAK_DynamicDispatch
Enable inlining of dynamically dispatched methods.
IPAK_DynamicDispatchBifurcate
Enable inlining of dynamically dispatched methods, bifurcate paths when exact type info is unavailable.
Definition at line 105 of file AnalyzerOptions.h.
KernelReferenceKind
enum class clang::KernelReferenceKind : unsigned strong
Enumerator
Kernel
Stub
Definition at line 38 of file GlobalDecl.h.
LambdaCaptureDefault
enum clang::LambdaCaptureDefault
The default, if any, capture method for a lambda expression.
Enumerator
LCD_None
LCD_ByCopy
LCD_ByRef
Definition at line 22 of file Lambda.h.
LambdaCaptureInitKind
enum class clang::LambdaCaptureInitKind strong
Enumerator
NoInit
[a]
CopyInit
[a = b], [a = {b}]
DirectInit
[a(b)]
ListInit
[a{b}]
Definition at line 2657 of file DeclSpec.h.
LambdaCaptureKind
enum clang::LambdaCaptureKind
The different capture forms in a lambda introducer.
C++11 allows capture of this, or of local variables by copy or by reference. C++1y also allows "init-capture", where the initializer is an expression.
Enumerator
LCK_This
Capturing the *this object by reference.
LCK_StarThis
LCK_ByCopy
< Capturing the *this object by copy
Capturing by copy (a.k.a., by value)
LCK_ByRef
Capturing by reference.
LCK_VLAType
Capturing variable-length array type.
Definition at line 33 of file Lambda.h.
LangAS
enum class clang::LangAS : unsigned strong
Defines the address space values used by the address space qualifier of QualType.
Enumerator
Default
opencl_global
opencl_local
opencl_constant
opencl_private
opencl_generic
opencl_global_device
opencl_global_host
cuda_device
cuda_constant
cuda_shared
ptr32_sptr
ptr32_uptr
ptr64
FirstTargetAddressSpace
Definition at line 25 of file AddressSpaces.h.
LangFeatures
enum clang::LangFeatures
Enumerator
LineComment
C99
C11
C17
C2x
CPlusPlus
CPlusPlus11
CPlusPlus14
CPlusPlus17
CPlusPlus20
CPlusPlus2b
Digraphs
GNUMode
HexFloat
ImplicitInt
OpenCL
Definition at line 41 of file LangStandard.h.
Language
enum class clang::Language : uint8_t strong
The language for the input, used to select and validate the language standard and possible actions.
Enumerator
Unknown
Asm
Assembly: we accept this only so that we can preprocess it.
LLVM_IR
LLVM IR: we accept this so that we can run the optimizer on it, and compile it to assembly or object code.
C
Languages that the frontend can parse and compile.
CXX
ObjC
ObjCXX
OpenCL
CUDA
RenderScript
HIP
Definition at line 19 of file LangStandard.h.
LanguageID
enum clang::LanguageID
Enumerator
GNU_LANG
C_LANG
CXX_LANG
OBJC_LANG
MS_LANG
OCLC20_LANG
OCLC1X_LANG
OMP_LANG
ALL_LANGUAGES
ALL_GNU_LANGUAGES
ALL_MS_LANGUAGES
ALL_OCLC_LANGUAGES
Definition at line 30 of file Builtins.h.
LanguageLinkage
enum clang::LanguageLinkage
Describes the different kinds of language linkage (C++ [dcl.link]) that an entity may have.
Enumerator
CLanguageLinkage
CXXLanguageLinkage
NoLanguageLinkage
Definition at line 64 of file Linkage.h.
Linkage
enum clang::Linkage : unsigned char
Describes the different kinds of linkage (C++ [basic.link], C99 6.2.2) that an entity may have.
Enumerator
NoLinkage
No linkage, which means that the entity is unique and can only be referred to from within its scope.
InternalLinkage
Internal linkage, which indicates that the entity can be referred to from within the translation unit (but not other translation units).
UniqueExternalLinkage
External linkage within a unique namespace.
From the language perspective, these entities have external linkage. However, since they reside in an anonymous namespace, their names are unique to this translation unit, which is equivalent to having internal linkage from the code-generation point of view.
VisibleNoLinkage
No linkage according to the standard, but is visible from other translation units because of types defined in a inline function.
ModuleInternalLinkage
Internal linkage according to the Modules TS, but can be referred to from other translation units indirectly through inline functions and templates in the module interface.
ModuleLinkage
Module linkage, which indicates that the entity can be referred to from other translation units within the same module, and indirectly from arbitrary other translation units through inline functions and templates in the module interface.
ExternalLinkage
External linkage, which indicates that the entity can be referred to from other translation units.
Definition at line 23 of file Linkage.h.
MacroUse
enum clang::MacroUse
Context in which macro name is used.
Enumerator
MU_Other
MU_Define
MU_Undef
Definition at line 112 of file Preprocessor.h.
MSInheritanceModel
enum class clang::MSInheritanceModel strong
Assigned inheritance model for a class in the MS C++ ABI.
Must match order of spellings in MSInheritanceAttr.
Enumerator
Single
Multiple
Virtual
Unspecified
Definition at line 352 of file Specifiers.h.
MSVtorDispMode
enum class clang::MSVtorDispMode strong
In the Microsoft ABI, this controls the placement of virtual displacement members used to implement virtual inheritance.
Enumerator
Never
ForVBaseOverride
ForVFTable
Definition at line 54 of file LangOptions.h.
MultiVersionKind
enum class clang::MultiVersionKind strong
Enumerator
None
Target
CPUSpecific
CPUDispatch
Definition at line 1794 of file Decl.h.
NarrowingKind
enum clang::NarrowingKind
NarrowingKind - The kind of narrowing conversion being performed by a standard conversion sequence according to C++11 [dcl.init.list]p7.
Enumerator
NK_Not_Narrowing
Not a narrowing conversion.
NK_Type_Narrowing
A narrowing conversion by virtue of the source and destination types.
NK_Constant_Narrowing
A narrowing conversion, because a constant expression got narrowed.
NK_Variable_Narrowing
A narrowing conversion, because a non-constant-expression variable might have got narrowed.
NK_Dependent_Narrowing
Cannot tell whether this is a narrowing conversion because the expression is value-dependent.
Definition at line 232 of file Overload.h.
NeverCalledReason
enum class clang::NeverCalledReason strong
Enumerator
IfThen
IfElse
Switch
SwitchSkipped
LoopEntered
LoopSkipped
FallbackReason
LARGEST_VALUE
Definition at line 36 of file CalledOnceCheck.h.
NonOdrUseReason
enum clang::NonOdrUseReason
The reason why a DeclRefExpr does not constitute an odr-use.
Enumerator
NOUR_None
This is an odr-use.
NOUR_Unevaluated
This name appears in an unevaluated operand.
NOUR_Constant
This name appears as a potential result of an lvalue-to-rvalue conversion that is a constant expression.
NOUR_Discarded
This name appears as a potential result of a discarded value expression.
Definition at line 148 of file Specifiers.h.
NullabilityKind
enum class clang::NullabilityKind : uint8_t strong
Describes the nullability of a particular type.
Enumerator
NonNull
Values of this type can never be null.
Nullable
Values of this type can be null.
Unspecified
Whether values of this type can be null is (explicitly) unspecified.
This captures a (fairly rare) case where we can't conclude anything about the nullability of the type even though it has been considered.
NullableResult
Definition at line 303 of file Specifiers.h.
ObjCBridgeCastKind
enum clang::ObjCBridgeCastKind
The kind of bridging performed by the Objective-C bridge cast.
Enumerator
OBC_Bridge
Bridging via __bridge, which does nothing but reinterpret the bits.
OBC_BridgeTransfer
Bridging via __bridge_transfer, which transfers ownership of an Objective-C pointer into ARC.
OBC_BridgeRetained
Bridging via __bridge_retain, which makes an ARC object available as a +1 C pointer.
Definition at line 36 of file OperationKinds.h.
ObjCInstanceTypeFamily
enum clang::ObjCInstanceTypeFamily
A family of Objective-C methods.
These are family of methods whose result type is initially 'id', but but are candidate for the result type to be changed to 'instancetype'.
Enumerator
OIT_None
OIT_Array
OIT_Dictionary
OIT_Singleton
OIT_Init
OIT_ReturnsSelf
Definition at line 662 of file IdentifierTable.h.
ObjCMethodFamily
enum clang::ObjCMethodFamily
A family of Objective-C methods.
These families have no inherent meaning in the language, but are nonetheless central enough in the existing implementations to merit direct AST support. While, in theory, arbitrary methods can be considered to form families, we focus here on the methods involving allocation and retain-count management, as these are the most "core" and the most likely to be useful to diverse clients without extra information.
Both selectors and actual method declarations may be classified into families. Method families may impose additional restrictions beyond their selector name; for example, a method called '_init' that returns void is not considered to be in the 'init' family (but would be if it returned 'id'). It is also possible to explicitly change or remove a method's family. Therefore the method's family should be considered the single source of truth.
Enumerator
OMF_None
No particular method family.
OMF_alloc
OMF_copy
OMF_init
OMF_mutableCopy
OMF_new
OMF_autorelease
OMF_dealloc
OMF_finalize
OMF_release
OMF_retain
OMF_retainCount
OMF_self
OMF_initialize
OMF_performSelector
Definition at line 622 of file IdentifierTable.h.
ObjCPropertyQueryKind
enum class clang::ObjCPropertyQueryKind : uint8_t strong
Enumerator
OBJC_PR_query_unknown
OBJC_PR_query_instance
OBJC_PR_query_class
Definition at line 717 of file DeclObjC.h.
ObjCStringFormatFamily
enum clang::ObjCStringFormatFamily
Enumerator
SFF_None
SFF_NSString
SFF_CFString
Definition at line 671 of file IdentifierTable.h.
ObjCSubstitutionContext
enum class clang::ObjCSubstitutionContext strong
The kind of type we are substituting Objective-C type arguments into.
The kind of substitution affects the replacement of type parameters when no concrete type information is provided, e.g., when dealing with an unspecialized type.
Enumerator
Ordinary
An ordinary type.
Result
The result type of a method or function.
Parameter
The parameter type of a method or function.
Property
The type of a property.
Superclass
The superclass of a type.
Definition at line 630 of file Type.h.
ObjCTypeParamVariance
enum class clang::ObjCTypeParamVariance : uint8_t strong
Describes the variance of a given generic parameter.
Enumerator
Invariant
The parameter is invariant: must match exactly.
Covariant
The parameter is covariant, e.g., X<T> is a subtype of X when the type parameter is covariant and T is a subtype of U.
Contravariant
The parameter is contravariant, e.g., X<T> is a subtype of X when the type parameter is covariant and U is a subtype of T.
Definition at line 554 of file DeclObjC.h.
ObjCXXARCStandardLibraryKind
enum clang::ObjCXXARCStandardLibraryKind
Enumerate the kinds of standard library that.
Enumerator
ARCXX_nolib
ARCXX_libcxx
libc++
ARCXX_libstdcxx
libstdc++
Definition at line 34 of file PreprocessorOptions.h.
OpenCLTypeKind
enum clang::OpenCLTypeKind : uint8_t
OpenCL type kinds.
Enumerator
OCLTK_Default
OCLTK_ClkEvent
OCLTK_Event
OCLTK_Image
OCLTK_Pipe
OCLTK_Queue
OCLTK_ReserveID
OCLTK_Sampler
Definition at line 166 of file TargetInfo.h.
OpenMPAtomicDefaultMemOrderClauseKind
enum clang::OpenMPAtomicDefaultMemOrderClauseKind
OpenMP attributes for 'atomic_default_mem_order' clause.
Enumerator
OMPC_ATOMIC_DEFAULT_MEM_ORDER_unknown
Definition at line 126 of file OpenMPKinds.h.
OpenMPDefaultmapClauseKind
enum clang::OpenMPDefaultmapClauseKind
OpenMP attributes for 'defaultmap' clause.
Enumerator
OMPC_DEFAULTMAP_unknown
Definition at line 109 of file OpenMPKinds.h.
OpenMPDefaultmapClauseModifier
enum clang::OpenMPDefaultmapClauseModifier
OpenMP modifiers for 'defaultmap' clause.
Enumerator
OMPC_DEFAULTMAP_MODIFIER_unknown
OMPC_DEFAULTMAP_MODIFIER_last
Definition at line 117 of file OpenMPKinds.h.
OpenMPDependClauseKind
enum clang::OpenMPDependClauseKind
OpenMP attributes for 'depend' clause.
Enumerator
OMPC_DEPEND_unknown
Definition at line 53 of file OpenMPKinds.h.
OpenMPDeviceClauseModifier
enum clang::OpenMPDeviceClauseModifier
OpenMP modifiers for 'device' clause.
Enumerator
OMPC_DEVICE_unknown
Definition at line 46 of file OpenMPKinds.h.
OpenMPDeviceType
enum clang::OpenMPDeviceType
OpenMP device type for 'device_type' clause.
Enumerator
OMPC_DEVICE_TYPE_unknown
Definition at line 134 of file OpenMPKinds.h.
OpenMPDistScheduleClauseKind
enum clang::OpenMPDistScheduleClauseKind
OpenMP attributes for 'dist_schedule' clause.
Enumerator
OMPC_DIST_SCHEDULE_unknown
Definition at line 102 of file OpenMPKinds.h.
OpenMPLastprivateModifier
enum clang::OpenMPLastprivateModifier
OpenMP 'lastprivate' clause modifier.
Enumerator
OMPC_LASTPRIVATE_unknown
Definition at line 142 of file OpenMPKinds.h.
OpenMPLinearClauseKind
enum clang::OpenMPLinearClauseKind
OpenMP attributes for 'linear' clause.
Enumerator
OMPC_LINEAR_unknown
Definition at line 61 of file OpenMPKinds.h.
OpenMPMapClauseKind
enum clang::OpenMPMapClauseKind
OpenMP mapping kind for 'map' clause.
Enumerator
OMPC_MAP_unknown
Definition at line 69 of file OpenMPKinds.h.
OpenMPMapModifierKind
enum clang::OpenMPMapModifierKind
OpenMP modifier kind for 'map' clause.
Enumerator
OMPC_MAP_MODIFIER_unknown
OMPC_MAP_MODIFIER_last
Definition at line 77 of file OpenMPKinds.h.
OpenMPMotionModifierKind
enum clang::OpenMPMotionModifierKind
OpenMP modifier kind for 'to' or 'from' clause.
Enumerator
OMPC_MOTION_MODIFIER_unknown
Definition at line 90 of file OpenMPKinds.h.
OpenMPOrderClauseKind
enum clang::OpenMPOrderClauseKind
OpenMP attributes for 'order' clause.
Enumerator
OMPC_ORDER_unknown
Definition at line 149 of file OpenMPKinds.h.
OpenMPReductionClauseModifier
enum clang::OpenMPReductionClauseModifier
OpenMP modifiers for 'reduction' clause.
Enumerator
OMPC_REDUCTION_unknown
Definition at line 163 of file OpenMPKinds.h.
OpenMPScheduleClauseKind
enum clang::OpenMPScheduleClauseKind
OpenMP attributes for 'schedule' clause.
Enumerator
OMPC_SCHEDULE_unknown
Definition at line 29 of file OpenMPKinds.h.
OpenMPScheduleClauseModifier
enum clang::OpenMPScheduleClauseModifier
OpenMP modifiers for 'schedule' clause.
Enumerator
OMPC_SCHEDULE_MODIFIER_unknown
OMPC_SCHEDULE_MODIFIER_last
Definition at line 37 of file OpenMPKinds.h.
OverloadCandidateDisplayKind
enum clang::OverloadCandidateDisplayKind
Enumerator
OCD_AllCandidates
Requests that all candidates be shown.
Viable candidates will be printed first.
OCD_ViableCandidates
Requests that only viable candidates be shown.
OCD_AmbiguousCandidates
Requests that only tied-for-best candidates be shown.
Definition at line 65 of file Overload.h.
OverloadCandidateParamOrder
enum class clang::OverloadCandidateParamOrder : char strong
The parameter ordering that will be used for the candidate.
This is used to represent C++20 binary operator rewrites that reverse the order of the arguments. If the parameter ordering is Reversed, the Args list is reversed (but obviously the ParamDecls for the function are not).
After forming an OverloadCandidate with reversed parameters, the list of conversions will (as always) be indexed by argument, so will be in reverse parameter order.
Enumerator
Normal
Reversed
Definition at line 85 of file Overload.h.
OverloadCandidateRewriteKind
enum clang::OverloadCandidateRewriteKind : unsigned
The kinds of rewrite we perform on overload candidates.
Note that the values here are chosen to serve as both bitflags and as a rank (lower values are preferred by overload resolution).
Enumerator
CRK_None
Candidate is not a rewritten candidate.
CRK_DifferentOperator
Candidate is a rewritten candidate with a different operator name.
CRK_Reversed
Candidate is a rewritten candidate with a reversed order of parameters.
Definition at line 90 of file Overload.h.
OverloadedOperatorKind
enum clang::OverloadedOperatorKind : int
Enumeration specifying the different kinds of C++ overloaded operators.
Enumerator
OO_None
Not an overloaded operator.
NUM_OVERLOADED_OPERATORS
Definition at line 21 of file OperatorKinds.h.
OverloadFailureKind
enum clang::OverloadFailureKind
Enumerator
ovl_fail_too_many_arguments
ovl_fail_too_few_arguments
ovl_fail_bad_conversion
ovl_fail_bad_deduction
ovl_fail_trivial_conversion
This conversion candidate was not considered because it duplicates the work of a trivial or derived-to-base conversion.
ovl_fail_illegal_constructor
This conversion candidate was not considered because it is an illegal instantiation of a constructor temploid: it is callable with one argument, we only have one argument, and its first parameter type is exactly the type of the class.
Defining such a constructor directly is illegal, and template-argument deduction is supposed to ignore such instantiations, but we can still get one with the right kind of implicit instantiation.
ovl_fail_bad_final_conversion
This conversion candidate is not viable because its result type is not implicitly convertible to the desired type.
ovl_fail_final_conversion_not_exact
This conversion function template specialization candidate is not viable because the final conversion was not an exact match.
ovl_fail_bad_target
(CUDA) This candidate was not viable because the callee was not accessible from the caller's target (i.e.
host->device, global->host, device->host).
ovl_fail_enable_if
This candidate function was not viable because an enable_if attribute disabled it.
ovl_fail_explicit
This candidate constructor or conversion function is explicit but the context doesn't permit explicit functions.
ovl_fail_addr_not_available
This candidate was not viable because its address could not be taken.
ovl_fail_ext_disabled
This candidate was not viable because its OpenCL extension is disabled.
ovl_fail_inhctor_slice
This inherited constructor is not viable because it would slice the argument.
ovl_non_default_multiversion_function
This candidate was not viable because it is a non-default multiversioned function.
ovl_fail_object_addrspace_mismatch
This constructor/conversion candidate fail due to an address space mismatch between the object being constructed and the overload candidate.
ovl_fail_constraints_not_satisfied
This candidate was not viable because its associated constraints were not satisfied.
Definition at line 717 of file Overload.h.
OverloadFixItKind
enum clang::OverloadFixItKind
Enumerator
OFIK_Undefined
OFIK_Dereference
OFIK_TakeAddress
OFIK_RemoveDereference
OFIK_RemoveTakeAddress
Definition at line 19 of file SemaFixItUtils.h.
OverloadingResult
enum clang::OverloadingResult
OverloadingResult - Capture the result of performing overload resolution.
Enumerator
OR_Success
Overload resolution succeeded.
OR_No_Viable_Function
No viable function found.
OR_Ambiguous
Ambiguous candidates found.
OR_Deleted
Succeeded, but refers to a deleted function.
Definition at line 51 of file Overload.h.
OverloadsShown
enum clang::OverloadsShown : unsigned
Specifies which overload candidates to display when overload resolution fails.
Enumerator
Ovl_All
Show all overloads.
Ovl_Best
Show just the "best" overload candidates.
Definition at line 29 of file DiagnosticOptions.h.
ParameterABI
enum class clang::ParameterABI strong
Kinds of parameter ABI.
Enumerator
Ordinary
This parameter uses ordinary ABI rules for its type.
SwiftIndirectResult
This parameter (which must have pointer type) is a Swift indirect result parameter.
SwiftErrorResult
This parameter (which must have pointer-to-pointer type) uses the special Swift error-result ABI treatment.
There can be at most one parameter on a given function that uses this treatment.
SwiftContext
This parameter (which must have pointer type) uses the special Swift context-pointer ABI treatment.
There can be at most one parameter on a given function that uses this treatment.
Definition at line 331 of file Specifiers.h.
PragmaFloatControlKind
enum clang::PragmaFloatControlKind
Enumerator
PFC_Unknown
PFC_Precise
PFC_NoPrecise
PFC_Except
PFC_NoExcept
PFC_Push
PFC_Pop
Definition at line 28 of file PragmaKinds.h.
PragmaIntroducerKind
enum clang::PragmaIntroducerKind
Describes how the pragma was introduced, e.g., with #pragma, _Pragma, or __pragma.
Enumerator
PIK_HashPragma
The pragma was introduced via #pragma.
PIK__Pragma
The pragma was introduced via the C99 _Pragma(string-literal).
PIK___pragma
The pragma was introduced via the Microsoft __pragma(token-string).
Definition at line 32 of file Pragma.h.
PragmaMSCommentKind
enum clang::PragmaMSCommentKind
Enumerator
PCK_Unknown
PCK_Linker
PCK_Lib
PCK_Compiler
PCK_ExeStr
PCK_User
Definition at line 14 of file PragmaKinds.h.
PragmaMSStructKind
enum clang::PragmaMSStructKind
Enumerator
PMSST_OFF
PMSST_ON
Definition at line 23 of file PragmaKinds.h.
RefQualifierKind
enum clang::RefQualifierKind
The kind of C++11 ref-qualifier associated with a function type.
This determines whether a member function's "this" object can be an lvalue, rvalue, or neither.
Enumerator
RQ_None
No ref-qualifier was provided.
RQ_LValue
An lvalue ref-qualifier was provided (&).
RQ_RValue
An rvalue ref-qualifier was provided (&&).
Definition at line 1429 of file Type.h.
SelectorLocationsKind
enum clang::SelectorLocationsKind
Whether all locations of the selector identifiers are in a "standard" position.
Enumerator
SelLoc_NonStandard
Non-standard.
SelLoc_StandardNoSpace
For nullary selectors, immediately before the end: "[foo release]" / "-(void)release;" Or immediately before the arguments: "[foo first:1 second:2]" / "-(id)first:(int)x second:(int)y;.
SelLoc_StandardWithSpace
For nullary selectors, immediately before the end: "[foo release]" / "-(void)release;" Or with a space between the arguments: "[foo first: 1 second: 2]" / "-(id)first: (int)x second: (int)y;.
Definition at line 27 of file SelectorLocationsKind.h.
ShowIncludesDestination
enum class clang::ShowIncludesDestination strong
ShowIncludesDestination - Destination for /showIncludes output.
Enumerator
None
Stdout
Stderr
Definition at line 18 of file DependencyOutputOptions.h.
SimplifiedTypeClass
enum clang::SimplifiedTypeClass
A simplified classification of types used when determining "similar" types for code completion.
Enumerator
STC_Arithmetic
STC_Array
STC_Block
STC_Function
STC_ObjectiveC
STC_Other
STC_Pointer
STC_Record
STC_Void
Definition at line 149 of file CodeCompleteConsumer.h.
SkipFunctionBodiesScope
enum class clang::SkipFunctionBodiesScope strong
Enumerates the available scopes for skipping function bodies.
Enumerator
None
Preamble
PreambleAndMainFile
Definition at line 83 of file ASTUnit.h.
StorageClass
enum clang::StorageClass
Storage classes.
Enumerator
SC_None
SC_Extern
SC_Static
SC_PrivateExtern
SC_Auto
SC_Register
Definition at line 223 of file Specifiers.h.
StorageDuration
enum clang::StorageDuration
The storage duration for an object (per C++ [basic.stc]).
Enumerator
SD_FullExpression
Full-expression storage duration (for temporaries).
SD_Automatic
Automatic storage duration (most local variables).
SD_Thread
Thread storage duration.
SD_Static
Static storage duration.
SD_Dynamic
Dynamic storage duration.
Definition at line 294 of file Specifiers.h.
StructuralEquivalenceKind
enum class clang::StructuralEquivalenceKind strong
Whether to perform a normal or minimal equivalence check.
In case of Minimal, we do not perform a recursive check of decls with external storage.
Enumerator
Default
Minimal
Definition at line 36 of file ASTStructuralEquivalence.h.
SyncScope
enum class clang::SyncScope strong
Defines synch scope values used internally by clang.
The enum values start from 0 and are contiguous. They are mainly used for enumerating all supported synch scope values and mapping them to LLVM synch scopes. Their numerical values may be different from the corresponding synch scope enums used in source languages.
In atomic builtin and expressions, language-specific synch scope enums are used. Currently only OpenCL memory scope enums are supported and assumed to be used by all languages. However, in the future, other languages may define their own set of synch scope enums. The language-specific synch scope values are represented by class AtomicScopeModel and its derived classes.
To add a new enum value: Add the enum value to enum class SyncScope. Update enum value Last if necessary. Update getAsString.
Enumerator
OpenCLWorkGroup
OpenCLDevice
OpenCLAllSVMDevices
OpenCLSubGroup
Last
Definition at line 42 of file SyncScope.h.
TagTypeKind
enum clang::TagTypeKind
The kind of a tag type.
Enumerator
TTK_Struct
The "struct" keyword.
TTK_Interface
The "__interface" keyword.
TTK_Union
The "union" keyword.
TTK_Class
The "class" keyword.
TTK_Enum
The "enum" keyword.
Definition at line 5300 of file Type.h.
TemplateDeductionFlags
enum clang::TemplateDeductionFlags
Various flags that control template argument deduction.
These flags can be bitwise-OR'd together.
Enumerator
TDF_None
No template argument deduction flags, which indicates the strictest results for template argument deduction (as used for, e.g., matching class template partial specializations).
TDF_ParamWithReferenceType
Within template argument deduction from a function call, we are matching with a parameter type for which the original parameter was a reference.
TDF_IgnoreQualifiers
Within template argument deduction from a function call, we are matching in a case where we ignore cv-qualifiers.
TDF_DerivedClass
Within template argument deduction from a function call, we are matching in a case where we can perform template argument deduction from a template-id of a derived class of the argument type.
TDF_SkipNonDependent
Allow non-dependent types to differ, e.g., when performing template argument deduction from a function call where conversions may apply.
TDF_TopLevelParameterTypeList
Whether we are performing template argument deduction for parameters and arguments in a top-level template argument.
TDF_AllowCompatibleFunctionType
Within template argument deduction from overload resolution per C++ [over.over] allow matching function types that are compatible in terms of noreturn and default calling convention adjustments, or similarly matching a declared template specialization against a possible template, per C++ [temp.deduct.decl].
In either case, permit deduction where the parameter is a function type that can be converted to the argument type.
TDF_ArgWithReferenceType
Within template argument deduction for a conversion function, we are matching with an argument type for which the original argument was a reference.
Definition at line 65 of file SemaTemplateDeduction.cpp.
TemplateNameKind
enum clang::TemplateNameKind
Specifies the kind of template name that an identifier refers to.
Be careful when changing this: this enumeration is used in diagnostics.
Enumerator
TNK_Non_template
The name does not refer to a template.
TNK_Function_template
The name refers to a function template or a set of overloaded functions that includes at least one function template, or (in C++20) refers to a set of non-template functions but is followed by a '<'.
TNK_Type_template
The name refers to a template whose specialization produces a type.
The template itself could be a class template, template template parameter, or template alias.
TNK_Var_template
The name refers to a variable template whose specialization produces a variable.
TNK_Dependent_template_name
The name refers to a dependent template name:
template<typename MetaFun, typename T1, typename T2> struct apply2 {
  typedef typename MetaFun::template apply<T1, T2>::type type;
};
Here, "apply" is a dependent template name within the typename specifier in the typedef. "apply" is a nested template, and whether the template name is assumed to refer to a type template or a function template depends on the context in which the template name occurs.
TNK_Undeclared_template
Lookup for the name failed, but we're assuming it was a template name anyway.
In C++20, this is mandatory in order to parse ADL-only function template specialization calls.
TNK_Concept_template
The name refers to a concept.
Definition at line 20 of file TemplateKinds.h.
TemplateSpecializationKind
enum clang::TemplateSpecializationKind
Describes the kind of template specialization that a particular template specialization declaration represents.
Enumerator
TSK_Undeclared
This template specialization was formed from a template-id but has not yet been declared, defined, or instantiated.
TSK_ImplicitInstantiation
This template specialization was implicitly instantiated from a template.
(C++ [temp.inst]).
TSK_ExplicitSpecialization
This template specialization was declared or defined by an explicit specialization (C++ [temp.expl.spec]) or partial specialization (C++ [temp.class.spec]).
TSK_ExplicitInstantiationDeclaration
This template specialization was instantiated from a template due to an explicit instantiation declaration request (C++11 [temp.explicit]).
TSK_ExplicitInstantiationDefinition
This template specialization was instantiated from a template due to an explicit instantiation definition request (C++ [temp.explicit]).
Definition at line 163 of file Specifiers.h.
TemplateSubstitutionKind
enum class clang::TemplateSubstitutionKind : char strong
The kind of template substitution being performed.
Enumerator
Specialization
We are substituting template parameters for template arguments in order to form a template specialization.
Rewrite
We are substituting template parameters for (typically) other template parameters in order to rewrite a declaration as a different declaration (for example, when forming a deduction guide from a constructor).
Definition at line 46 of file Template.h.
TestLanguage
enum clang::TestLanguage
Enumerator
Lang_C89
Lang_C99
Lang_CXX03
Lang_CXX11
Lang_CXX14
Lang_CXX17
Lang_CXX20
Lang_OpenCL
Lang_OBJCXX
Definition at line 23 of file CommandLineArgs.h.
ThreadStorageClassSpecifier
enum clang::ThreadStorageClassSpecifier
Thread storage-class-specifier.
Enumerator
TSCS_unspecified
TSCS___thread
GNU __thread.
TSCS_thread_local
C++11 thread_local.
Implies 'static' at block scope, but not at class scope.
TSCS__Thread_local
C11 _Thread_local.
Must be combined with either 'static' or 'extern' if used at block scope.
Definition at line 210 of file Specifiers.h.
TPOC
enum clang::TPOC
The context in which partial ordering of function templates occurs.
Enumerator
TPOC_Call
Partial ordering of function templates for a function call.
TPOC_Conversion
Partial ordering of function templates for a call to a conversion function.
TPOC_Other
Partial ordering of function templates in other contexts, e.g., taking the address of a function template or matching a function template specialization to a function template.
Definition at line 203 of file Template.h.
TranslationUnitKind
enum clang::TranslationUnitKind
Describes the kind of translation unit being processed.
Enumerator
TU_Complete
The translation unit is a complete translation unit.
TU_Prefix
The translation unit is a prefix to a translation unit, and is not complete.
TU_Module
The translation unit is a module.
Definition at line 647 of file LangOptions.h.
TraversalKind
enum clang::TraversalKind
Defines how we descend a level in the AST when we pass through expressions.
Enumerator
TK_AsIs
Will traverse all child nodes.
TK_IgnoreUnlessSpelledInSource
Ignore AST nodes not written in the source.
Definition at line 39 of file ASTTypeTraits.h.
TypeSpecifierSign
enum class clang::TypeSpecifierSign strong
Specifies the signedness of a type, e.g., signed or unsigned.
Enumerator
Unspecified
Signed
Unsigned
Definition at line 38 of file Specifiers.h.
TypeSpecifiersPipe
enum class clang::TypeSpecifiersPipe strong
Enumerator
Unspecified
Pipe
Definition at line 40 of file Specifiers.h.
TypeSpecifierType
enum clang::TypeSpecifierType
Specifies the kind of type.
Enumerator
TST_unspecified
TST_void
TST_char
TST_wchar
TST_char8
TST_char16
TST_char32
TST_int
TST_int128
TST_extint
TST_half
TST_Float16
TST_Accum
TST_Fract
TST_BFloat16
TST_float
TST_double
TST_float128
TST_bool
TST_decimal32
TST_decimal64
TST_decimal128
TST_enum
TST_union
TST_struct
TST_class
TST_interface
TST_typename
TST_typeofType
TST_typeofExpr
TST_decltype
TST_underlyingType
TST_auto
TST_decltype_auto
TST_auto_type
TST_unknown_anytype
TST_atomic
TST_error
Definition at line 43 of file Specifiers.h.
TypeSpecifierWidth
enum class clang::TypeSpecifierWidth strong
Specifies the width of a type, e.g., short, long, or long long.
Enumerator
Unspecified
Short
Long
LongLong
Definition at line 35 of file Specifiers.h.
TypeTrait
enum clang::TypeTrait
Names for traits that operate specifically on types.
Enumerator
UTT_Last
BTT_Last
TT_Last
Definition at line 21 of file TypeTraits.h.
UnaryExprOrTypeTrait
enum clang::UnaryExprOrTypeTrait
Names for the "expression or type" traits.
Enumerator
UETT_Last
Definition at line 51 of file TypeTraits.h.
UnaryOperatorKind
enum clang::UnaryOperatorKind
Definition at line 30 of file OperationKinds.h.
UnqualifiedIdKind
enum class clang::UnqualifiedIdKind strong
Describes the kind of unqualified-id parsed.
Enumerator
IK_Identifier
An identifier.
IK_OperatorFunctionId
An overloaded operator name, e.g., operator+.
IK_ConversionFunctionId
A conversion function name, e.g., operator int.
IK_LiteralOperatorId
A user-defined literal name, e.g., operator "" _i.
IK_ConstructorName
A constructor name.
IK_ConstructorTemplateId
A constructor named via a template-id.
IK_DestructorName
A destructor name.
IK_TemplateId
A template-id, e.g., f<int>.
IK_ImplicitSelfParam
An implicit 'self' parameter.
IK_DeductionGuideName
A deduction-guide name (a template-name)
Definition at line 926 of file DeclSpec.h.
UserModeKind
enum clang::UserModeKind
Describes the kinds for high-level analyzer mode.
Enumerator
UMK_Shallow
Perform shallow but fast analyzes.
UMK_Deep
Perform deep analyzes.
Definition at line 133 of file AnalyzerOptions.h.
Visibility
enum clang::Visibility
Describes the different kinds of visibility that a declaration may have.
Visibility determines how a declaration interacts with the dynamic linker. It may also affect whether the symbol can be found by runtime symbol lookup APIs.
Visibility is not described in any language standard and (nonetheless) sometimes has odd behavior. Not all platforms support all visibility kinds.
Enumerator
HiddenVisibility
Objects with "hidden" visibility are not seen by the dynamic linker.
ProtectedVisibility
Objects with "protected" visibility are seen by the dynamic linker but always dynamically resolve to an object within this shared object.
DefaultVisibility
Objects with "default" visibility are seen by the dynamic linker and act like normal objects.
Definition at line 33 of file Visibility.h.
Function Documentation
alignedAllocMinVersion()
llvm::VersionTuple clang::alignedAllocMinVersion (llvm::Triple::OSType OS) inline
Definition at line 24 of file AlignedAllocation.h.
Referenced by clang::Sema::diagnoseUnavailableAlignedAllocation(), and clang::driver::toolchains::Darwin::isAlignedAllocationUnavailable().
allocateDefaultArgStorageChain()
void * clang::allocateDefaultArgStorageChain (const ASTContext & C)
Definition at line 172 of file DeclTemplate.cpp.
References C.
Referenced by clang::DefaultArgStorage< ParmDecl, ArgType >::setInherited().
ApplyHeaderSearchOptions()
void clang::ApplyHeaderSearchOptions (HeaderSearch & HS, const HeaderSearchOptions & HSOpts, const LangOptions & Lang, const llvm::Triple & triple)
Apply the header search options to get given HeaderSearch object.
Definition at line 621 of file InitHeaderSearch.cpp.
References clang::FileManager::getDirectory(), clang::HeaderSearch::getFileMgr(), clang::HeaderSearch::getModuleMap(), clang::HeaderSearchOptions::Entry::Group, clang::HeaderSearchOptions::Entry::IgnoreSysRoot, clang::HeaderSearchOptions::Entry::IsFramework, P, clang::HeaderSearchOptions::Entry::Path, clang::HeaderSearchOptions::ResourceDir, clang::ModuleMap::setBuiltinIncludeDir(), clang::HeaderSearchOptions::Sysroot, clang::HeaderSearchOptions::SystemHeaderPrefixes, clang::HeaderSearchOptions::UseBuiltinIncludes, clang::HeaderSearchOptions::UserEntries, and clang::HeaderSearchOptions::Verbose.
Referenced by clang::CompilerInstance::createPreprocessor().
AssertSuccess() [1/2]
Expr * clang::AssertSuccess (ExprResult R) inline
Definition at line 292 of file Ownership.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
AssertSuccess() [2/2]
Stmt * clang::AssertSuccess (StmtResult R) inline
Definition at line 297 of file Ownership.h.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
AttachDependencyGraphGen()
void clang::AttachDependencyGraphGen (Preprocessor & PP, StringRef OutputFile, StringRef SysRoot)
AttachDependencyGraphGen - Create a dependency graph generator, and attach it to the given preprocessor.
Definition at line 62 of file DependencyGraph.cpp.
References clang::Preprocessor::addPPCallbacks().
Referenced by clang::CompilerInstance::createPreprocessor().
AttachHeaderIncludeGen()
void clang::AttachHeaderIncludeGen (Preprocessor & PP, const DependencyOutputOptions & DepOpts, bool ShowAllHeaders = false, StringRef OutputPath = {}, bool ShowDepth = true, bool MSStyle = false)
AttachHeaderIncludeGen - Create a header include list generator, and attach it to the given preprocessor.
Parameters
DepOpts - Options controlling the output.
ShowAllHeaders - If true, show all header information instead of just headers following the predefines buffer. This is useful for making sure includes mentioned on the command line are also reported, but differs from the default behavior used by -H.
OutputPath - If non-empty, a path to write the header include information to, instead of writing to stderr.
ShowDepth - Whether to indent to show the nesting of the includes.
MSStyle - Whether to print in cl.exe /showIncludes style.
Definition at line 78 of file HeaderIncludeGen.cpp.
References clang::Preprocessor::addPPCallbacks(), clang::DependencyOutputOptions::ExtraDeps, clang::Preprocessor::getDiagnostics(), PrintHeaderInfo(), clang::DiagnosticsEngine::Report(), and clang::DependencyOutputOptions::ShowIncludesDest.
Referenced by clang::CompilerInstance::createPreprocessor().
atTemplateBegin()
template<class TemplateInstantiationCallbackPtrs > void clang::atTemplateBegin (TemplateInstantiationCallbackPtrs & Callbacks, const Sema & TheSema, const Sema::CodeSynthesisContext & Inst)
Definition at line 61 of file TemplateInstCallback.h.
References C.
Referenced by clang::TemplateDeclInstantiator::InitFunctionInstantiation().
atTemplateEnd()
template<class TemplateInstantiationCallbackPtrs > void clang::atTemplateEnd (TemplateInstantiationCallbackPtrs & Callbacks, const Sema & TheSema, const Sema::CodeSynthesisContext & Inst)
Definition at line 71 of file TemplateInstCallback.h.
References C.
Referenced by clang::Sema::InstantiatingTemplate::Clear(), and clang::TemplateDeclInstantiator::InitFunctionInstantiation().
canDynamicCastThrow()
static CanThrowResult clang::canDynamicCastThrow (const CXXDynamicCastExpr * DC) static
Definition at line 1083 of file SemaExceptionSpec.cpp.
References CT_Can, CT_Cannot, CT_Dependent, clang::CastExpr::getCastKind(), clang::CastExpr::getSubExpr(), clang::ExplicitCastExpr::getTypeAsWritten(), clang::Type::isReferenceType(), and clang::Expr::isTypeDependent().
Referenced by clang::Sema::canThrow().
canSubStmtsThrow()
static CanThrowResult clang::canSubStmtsThrow (Sema & Self, const Stmt * S) static
Definition at line 988 of file SemaExceptionSpec.cpp.
References clang::Sema::canThrow(), CT_Can, CT_Cannot, and mergeCanThrow().
Referenced by clang::Sema::canThrow().
canTypeidThrow()
static CanThrowResult clang::canTypeidThrow (Sema & S, const CXXTypeidExpr * DC) static
Definition at line 1096 of file SemaExceptionSpec.cpp.
References clang::Expr::Classify(), clang::Sema::Context, CT_Can, CT_Cannot, CT_Dependent, clang::Type::getAs(), clang::RecordType::getDecl(), clang::CXXTypeidExpr::getExprOperand(), clang::Expr::getType(), clang::Expr::Classification::isPRValue(), clang::Expr::isTypeDependent(), and clang::CXXTypeidExpr::isTypeOperand().
Referenced by clang::Sema::canThrow().
canVarDeclThrow()
static CanThrowResult clang::canVarDeclThrow (Sema & Self, const VarDecl * VD) static
Definition at line 1055 of file SemaExceptionSpec.cpp.
References clang::Sema::canCalleeThrow(), clang::Sema::canThrow(), canVarDeclThrow(), clang::Sema::Context, CT_Cannot, clang::QualType::DK_cxx_destructor, clang::Type::getAsCXXRecordDecl(), clang::Type::getBaseElementTypeUnsafe(), clang::VarDecl::getInit(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::VarDecl::isUsableInConstantExpressions(), mergeCanThrow(), and clang::VarDecl::needsDestruction().
Referenced by clang::Sema::canThrow(), and canVarDeclThrow().
cast()
template<class U > U clang::cast (CodeGen::Address addr) inline
Definition at line 108 of file Address.h.
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCapturedRegionEnd(), clang::Sema::ActOnCapturedRegionError(), clang::Sema::ActOnCaseStmtBody(), clang::Sema::ActOnClassTemplateSpecialization(), clang::Sema::ActOnCompoundStmt(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXFoldExpr(), clang::Sema::ActOnCXXForRangeIdentifier(), clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnCXXTryBlock(), clang::Sema::ActOnDefs(), clang::Sema::ActOnDelayedCXXMethodParameter(), clang::Sema::ActOnDependentIdExpression(), clang::Sema::ActOnEndOfTranslationUnit(), clang::Sema::ActOnEnumBody(), clang::Sema::ActOnEnumConstant(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFields(), clang::Sema::ActOnFileScopeAsmDecl(), clang::Sema::ActOnFinishDelayedCXXMethodDeclaration(), clang::Sema::ActOnFinishedFunctionDefinitionInOpenMPAssumeScope(), clang::Sema::ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnFinishExportDecl(), clang::Sema::ActOnFinishLinkageSpecification(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnInitList(), clang::Sema::ActOnIvar(), clang::Sema::ActOnLambdaError(), clang::Sema::ActOnLambdaExpr(), clang::Sema::ActOnLastBitfield(), clang::Sema::ActOnMethodDeclaration(), clang::Sema::ActOnModuleBegin(), clang::Sema::ActOnModuleEnd(), clang::Sema::ActOnNameClassifiedAsOverloadSet(), clang::Sema::ActOnObjCContainerStartDefinition(), clang::Sema::ActOnObjCForCollectionStmt(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPAllocateDirective(), clang::Sema::ActOnOpenMPCall(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnOpenMPDeclareMapperDirective(), clang::Sema::ActOnOpenMPDeclareReductionCombinerEnd(), clang::Sema::ActOnOpenMPDeclareReductionCombinerStart(), clang::Sema::ActOnOpenMPDeclareReductionDirectiveStart(), clang::Sema::ActOnOpenMPDeclareReductionInitializerEnd(), clang::Sema::ActOnOpenMPDeclareReductionInitializerStart(), clang::Sema::ActOnOpenMPDeclareTargetName(), clang::Sema::ActOnOpenMPDistributeParallelForDirective(), clang::Sema::ActOnOpenMPDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPDistributeSimdDirective(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFlushDirective(), clang::Sema::ActOnOpenMPLoopInitialization(), clang::Sema::ActOnOpenMPOrderedDirective(), clang::Sema::ActOnOpenMPParallelDirective(), clang::Sema::ActOnOpenMPParallelForDirective(), clang::Sema::ActOnOpenMPParallelForSimdDirective(), clang::Sema::ActOnOpenMPParallelMasterDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPParallelSectionsDirective(), clang::Sema::ActOnOpenMPRegionEnd(), clang::Sema::ActOnOpenMPSectionsDirective(), clang::Sema::ActOnOpenMPTargetDirective(), clang::Sema::ActOnOpenMPTargetEnterDataDirective(), clang::Sema::ActOnOpenMPTargetExitDataDirective(), clang::Sema::ActOnOpenMPTargetParallelDirective(), clang::Sema::ActOnOpenMPTargetParallelForDirective(), clang::Sema::ActOnOpenMPTargetParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTargetUpdateDirective(), clang::Sema::ActOnOpenMPTaskDirective(), clang::Sema::ActOnOpenMPTeamsDirective(), clang::Sema::ActOnOpenMPTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPUsesAllocatorClause(), clang::Sema::ActOnParamDefaultArgument(), clang::Sema::ActOnParamDefaultArgumentError(), clang::Sema::ActOnParamUnparsedDefaultArgument(), clang::Sema::ActOnPopScope(), clang::Sema::ActOnProperty(), clang::Sema::ActOnStartCXXMemberDeclarations(), clang::Sema::ActOnStartDelayedMemberDeclarations(), clang::Sema::ActOnStartLinkageSpecification(), clang::Sema::ActOnStartNamespaceDef(), clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), clang::Sema::ActOnStartTrailingRequiresClause(), clang::Sema::ActOnStaticAssertDeclaration(), clang::Sema::ActOnSuperScopeSpecifier(), clang::Sema::ActOnTag(), clang::Sema::ActOnTagDefinitionError(), clang::Sema::ActOnTagFinishDefinition(), clang::Sema::ActOnTagStartDefinition(), clang::Sema::ActOnTagStartSkippedDefinition(), clang::Sema::ActOnTemplatedFriendTag(), clang::Sema::ActOnTypeConstraint(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::ActOnVariableDeclarator(), clang::Sema::AddArgumentDependentLookupCandidates(), addAssociatedClassesAndNamespaces(), addAssociatedClassesAndNamespaces(), addCastTransition(), clang::Sema::SynthesizedFunctionScope::addContextNote(), clang::Sema::AddConversionCandidate(), clang::Sema::AddFunctionCandidates(), AddIndirectPrimaryBases(), clang::Sema::AddMethodCandidate(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddNonMemberOperatorCandidates(), AddOverloadedCallCandidate(), AddTemplateParameterChunks(), AddTypedNameChunk(), addX86InterruptAttrs(), adjustCVQualifiersForCXXThisWithinLambda(), clang::ASTContext::adjustFunctionType(), clang::Sema::adjustMemberFunctionCC(), clang::ASTContext::adjustObjCTypeParamBoundType(), adjustParent(), adjustTemplateImplicitInstantiation(), AnalyzeCompoundAssignment(), areExprTypesCompatible(), clang::Sema::areMultiversionVariantFunctionsCompatible(), clang::Sema::ArgumentDependentLookup(), ARMMVEConstantSplat(), clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), clang::CodeGen::CodeGenTypes::arrangeGlobalDeclaration(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P_OVERLOAD(), clang::Sema::AttachBaseSpecifiers(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::ASTDeclReader::attachPreviousDeclImpl(), AvailabilityAttrsMatch(), clang::StmtSequence::begin(), BitsContainNoUserData(), clang::Sema::BuildAnonymousStructUnionMemberReference(), buildBlockDescriptor(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), buildCapture(), clang::Sema::buildCoroutineParameterMoves(), clang::Sema::buildCoroutinePromise(), BuildCXXCastArgument(), clang::Sema::BuildCXXDefaultInitExpr(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildExprRequirement(), clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::BuildLambdaExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMicrosoftCAnonymousStruct(), clang::Sema::BuildOverloadedArrowExpr(), BuildParentMap(), clang::Sema::BuildReturnStmt(), buildSingleCopyAssignRecursively(), clang::Sema::BuildStmtExpr(), clang::CodeGen::CGCXXABI::buildThisParam(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::BuildUsingShadowDecl(), clang::Sema::BuildVariableInstantiation(), clang::Sema::BuildVectorLiteral(), calculateOffset(), clang::Sema::canCalleeThrow(), canEmitInitWithFewStoresAfterBZero(), canonicalizeImmediatelyDeclaredConstraint(), clang::Sema::canThrow(), CanUseSingleInheritance(), captureVariablyModifiedType(), clang::ento::MemRegion::castAs(), clang::Type::castAs(), clang::Type::castAsArrayTypeUnsafe(), clang::ento::StoreManager::castRegion(), CheckAbstractClassUsage(), clang::Sema::CheckAddressOfOperand(), CheckAggExprForMemSetUse(), checkAllocateClauses(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), checkAtomicPropertyMismatch(), clang::Sema::CheckBaseClassAccess(), clang::Sema::CheckBaseSpecifier(), checkBlockPointerTypesForAssignment(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckClassTemplate(), clang::Sema::CheckCompleteVariableDeclaration(), CheckConstexprDeclStmt(), CheckConstexprFunctionStmt(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckConstructorAccess(), clang::Sema::CheckCXXThisCapture(), checkDeclInTargetContext(), clang::Sema::checkDeviceDecl(), checkElementNonNil(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::CheckFieldDecl(), CheckForDuplicateEnumValues(), checkFormatStringExpr(), CheckForModifiableLvalue(), clang::Sema::CheckFriendAccess(), clang::Sema::CheckFunctionDeclaration(), clang::Sema::CheckFunctionTemplateSpecialization(), checkGlobalOrExternCConflict(), CheckICE(), CheckIdentityFieldAssignment(), CheckImplicitConversion(), clang::Sema::CheckInheritingConstructorUsingDecl(), clang::Sema::checkInitializerLifetime(), checkIsValidOpenCLKernelParameter(), clang::Sema::CheckLiteralKind(), clang::Sema::CheckMain(), CheckMemaccessSize(), clang::Sema::CheckMemberOperatorAccess(), clang::Sema::CheckMemberSpecialization(), checkNewAttributesAfterDef(), CheckNonNullArguments(), clang::Sema::CheckNontrivialField(), checkNoThrow(), CheckObjCBridgeCFCast(), CheckObjCBridgeNSCast(), clang::Sema::checkObjCBridgeRelatedComponents(), clang::Sema::CheckObjCPropertyAttributes(), clang::Sema::CheckOMPThreadPrivateDecl(), checkOpenCLBlockArgs(), checkOpenCLEnqueueVariadicArgs(), checkOpenCLPipePacketType(), checkOpenMPLoop(), checkOrderedOrderSpecified(), clang::Sema::CheckOverload(), clang::consumed::ConsumedStateMap::checkParamsForReturnTypestate(), clang::Sema::CheckPlaceholderExpr(), checkPointerTypesForAssignment(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::Sema::CheckQualifiedMemberReference(), checkReductionClauses(), clang::Sema::CheckShadow(), clang::Sema::CheckShadowingDeclModification(), checkSimdlenSafelenSpecified(), clang::Sema::CheckStaticLocalForDllExport(), CheckStringInit(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTemplateArgumentList(), CheckTemplateArgumentPointerToMember(), clang::Sema::CheckTemplateIdType(), clang::Sema::CheckTemplateParameterList(), CheckTemplateSpecializationScope(), checkUndefinedButUsed(), clang::Sema::CheckUsingDeclQualifier(), clang::Sema::CheckUsingShadowDecl(), clang::Sema::CheckVarTemplateId(), ClassifyImplicitMemberAccess(), ClassifyInternal(), clang::Sema::ClassifyName(), clang::ento::CallEvent::cloneWithState(), clang::Sema::CodeCompleteObjCPropertySynthesizeIvar(), clang::CodeGen::CodeGenModule::codegenCXXStructor(), collectViableConversionCandidates(), CollectVisibleConversions(), CollectVRQualifiers(), clang::Sema::CompleteMemberSpecialization(), clang::ASTReader::CompleteRedeclChain(), clang::ExternalASTMerger::CompleteType(), clang::ExternalASTMerger::CompleteType(), clang::ASTReader::completeVisibleDeclsMap(), computeBlockInfo(), computeCachedProperties(), ComputeDefaultedComparisonExceptionSpec(), computeImplicitExceptionSpec(), clang::LinkageComputer::computeLVForDecl(), clang::CodeGen::CodeGenModule::computeNonVirtualBaseClassOffset(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::analyze_os_log::computeOSLogBufferLayout(), clang::LinkageComputer::computeTypeLinkageInfo(), ComputeVMIClassTypeInfoFlags(), configureBlocksRuntimeObject(), clang::ento::SymbolManager::conjureSymbol(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), constStructWithPadding(), ContainsIncompleteClassType(), clang::Sema::containsUnexpandedParameterPacks(), convertArgsForAvailabilityChecks(), clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), CopyObject(), clang::FriendDecl::Create(), clang::ObjCIvarDecl::Create(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), createConstantGlobalStructAndAddToParent(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32(), clang::syntax::createEmptyStatement(), clang::ConstructionContext::createFromLayers(), createGlobalStruct(), createInvocationFromCommandLine(), CreateNewFunctionDecl(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::Sema::DeclareImplicitDeductionGuides(), DeclHasAttr(), clang::ASTContext::DeclMustBeEmitted(), DeduceNonTypeTemplateArgument(), clang::Sema::DeduceReturnType(), clang::Sema::DeduceTemplateArguments(), DeduceTemplateArgumentsByTypeMatch(), DeduceTemplateBases(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::syntax::deepCopyExpandingMacros(), defaultedSpecialMemberIsConstexpr(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineUsedVTables(), DelegatingCycleHelper(), describeUninitializedArgumentInCall(), destroyOptimisticNormalEntry(), clang::InitializationSequence::Diagnose(), diagnoseAmbiguousConversion(), clang::Sema::diagnoseARCUnbridgedCast(), DiagnoseArityMismatch(), DiagnoseBadConversion(), DiagnoseBadDeduction(), diagnoseBadDirectAccess(), DiagnoseBadTarget(), clang::Sema::DiagnoseEmptyLookup(), DiagnoseForRangeReferenceVariableCopies(), diagnoseMissingArgument(), diagnoseNoescape(), diagnoseNoViableConversion(), clang::Sema::diagnoseQualifiedDeclaration(), DiagnoseSelfAssignment(), clang::Sema::DiagnoseSentinelCalls(), clang::Sema::DiagnoseTemplateParameterShadow(), DiagnoseUninitializedUse(), clang::Sema::DiagnoseUseOfDecl(), DiagUninitUse(), clang::Sema::DiscardMisalignedMemberAddress(), clang::ASTImporterLookupTable::dump(), dumpBasePath(), clang::DeclContext::dumpDeclContext(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), emitAlignedClause(), clang::CodeGen::CodeGenModule::EmitAnnotationArgs(), EmitAvailabilityWarning(), EmitBaseInitializer(), EmitBitCastOfLValueToProperType(), emitBody(), clang::CodeGen::ReductionCodeGen::emitCleanups(), emitConstructorDestructorAlias(), emitCopyprivateCopyFunction(), EmitCXXNewAllocSize(), clang::CodeGen::CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), emitDepobjElements(), emitDepobjElementsSizes(), emitDestructorsFunction(), EmitDirectCallee(), emitDispatchForLoopBounds(), emitDistributeParallelForDispatchBounds(), emitDistributeParallelForDistributeInnerBoundParams(), emitDistributeParallelForInnerBounds(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitForLoopBounds(), EmitFunctionDeclLValue(), EmitFunctionDeclPointer(), EmitGEPOffsetInBytes(), clang::CodeGen::CodeGenModule::EmitGlobal(), emitGlobalDtorWithCXAAtExit(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), clang::CodeGen::ReductionCodeGen::emitInitialization(), emitInitWithReductionInitializer(), clang::CodeGen::CGDebugInfo::EmitInlineFunctionStart(), clang::CodeGen::CGDebugInfo::EmitLabel(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), clang::CodeGen::CGCXXABI::EmitLoadOfMemberFunctionPointer(), clang::CodeGen::CGDebugInfo::EmitNamespaceAlias(), clang::CodeGen::CodeGenModule::EmitNullConstant(), EmitNullConstant(), EmitObjectDelete(), emitOMPAtomicCaptureExpr(), emitOMPAtomicUpdateExpr(), EmitOMPHelperVar(), emitOMPSimdRegion(), clang::CodeGen::CodeGenModule::EmitOMPThreadPrivateDecl(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelOutlinedFunction(), emitPointerArithmetic(), emitPreCond(), emitPrivatesInit(), emitProxyTaskFunction(), emitReduceCombFunction(), clang::CodeGen::CGOpenMPRuntime::emitReduction(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), EmitScalarFMAExpr(), emitScanBasedDirective(), emitSimdlenSafelenClause(), clang::CodeGen::CGOpenMPRuntime::emitSingleReductionCombiner(), EmitSpecialRegisterBuiltin(), emitStoresForConstant(), emitStoresForInitAfterBZero(), clang::CodeGen::CGOpenMPRuntime::emitTargetFunctions(), clang::CodeGen::CGOpenMPRuntime::emitTargetGlobalVariable(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), emitTaskPrivateMappingFunction(), clang::CodeGen::CodeGenVTables::EmitThunks(), clang::CodeGen::CodeGenModule::EmitTopLevelDecl(), clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper(), emitWritebackArg(), EmitX86CompressExpand(), EmitX86CompressStore(), EmitX86ConvertIntToFp(), EmitX86CvtF16ToFloatExpr(), EmitX86ExpandLoad(), EmitX86FunnelShift(), EmitX86MaskedCompare(), EmitX86SExtMask(), EmitX86vpcom(), clang::StmtSequence::end(), clang::Sema::EndOpenMPDSABlock(), eraseUnusedBitCasts(), EvaluateAndDiagnoseImmediateInvocation(), EvaluateBinaryTypeTrait(), EvaluateStmt(), EvaluateSwitch(), EvaluateUnaryTypeTrait(), clang::driver::Driver::ExecuteCompilation(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), extractStringLiteralCharacter(), FieldHasTrivialDestructorBody(), clang::comments::DeclInfo::fill(), clang::CodeGen::CGDebugInfo::finalize(), clang::Sema::FinalizeDeclaration(), clang::Sema::FinalizeVarWithDestructor(), clang::OverloadExpr::find(), findAcceptableDecl(), findAcceptableDecl(), clang::Sema::FindAllocationFunctions(), findBackingIvar(), FindCaseStatementsForValue(), FindConversionForRefInit(), clang::Sema::FindDeallocationFunction(), FindDeclaringClass(), findDefiningRedecl(), findEnclosingDeclToAnnotate(), findEnumForBlockReturn(), clang::ASTReader::FindExternalVisibleDeclsByName(), clang::ExternalASTMerger::FindExternalVisibleDeclsByName(), clang::OpaqueValueExpr::findInCopyConstruct(), clang::Sema::findInheritingConstructor(), clang::Sema::FindInstantiatedDecl(), findInstantiationOf(), clang::ObjCMethodDecl::findPropertyDecl(), clang::ObjCContainerDecl::FindPropertyDeclaration(), findRetainCycleOwner(), FindTypeTagExpr(), clang::Sema::FinishCXXForRangeStmt(), clang::Sema::FinishObjCForCollectionStmt(), FinishOpenMPLinearClause(), FormatASTNodeDiagnosticArgument(), ForwardPrebranchedFallthrough(), FTIHasSingleVoidParameter(), clang::CodeGen::CodeGenVTables::GenerateConstructionVTable(), generateUniqueName(), clang::ento::ObjCMethodCall::getAccessedProperty(), clang::CodeGen::CodeGenModule::getAddrAndTypeOfCXXStructor(), clang::CodeGen::CGOpenMPRuntime::getAddrOfArtificialThreadPrivate(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), clang::CodeGen::CodeGenModule::getAddrOfCXXStructor(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalTemporary(), clang::CodeGen::CodeGenVTables::GetAddrOfVTT(), clang::ASTNameGenerator::Implementation::getAllManglings(), clang::IndirectFieldDecl::getAnonField(), clang::CXXDeleteExpr::getArgument(), clang::CXXDeleteExpr::getArgument(), clang::Type::getArrayElementTypeNoTypeQual(), clang::ArrayInitLoopExpr::getArraySize(), clang::Type::getAs(), clang::ASTContext::getAsArrayType(), clang::Type::getAsArrayTypeUnsafe(), clang::Type::getAsStructureType(), clang::Sema::getAsTemplateNameDecl(), clang::Type::getAsUnionType(), clang::CXXDependentScopeMemberExpr::getBase(), clang::CXXPseudoDestructorExpr::getBase(), clang::DesignatedInitUpdateExpr::getBase(), clang::ExtVectorElementExpr::getBase(), clang::ExtVectorElementExpr::getBase(), clang::MatrixSubscriptExpr::getBase(), clang::MatrixSubscriptExpr::getBase(), clang::MemberExpr::getBase(), clang::MSPropertySubscriptExpr::getBase(), clang::MSPropertySubscriptExpr::getBase(), clang::ObjCIsaExpr::getBase(), clang::ObjCIvarRefExpr::getBase(), clang::ObjCIvarRefExpr::getBase(), clang::ObjCPropertyRefExpr::getBase(), clang::ObjCPropertyRefExpr::getBase(), clang::OMPArraySectionExpr::getBase(), clang::OMPArraySectionExpr::getBase(), clang::UnresolvedMemberExpr::getBase(), clang::UnresolvedMemberExpr::getBase(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), clang::sema::AccessedEntity::getBaseClass(), getBaseDecl(), getBaseDecl(), clang::ObjCSubscriptRefExpr::getBaseExpr(), clang::ento::MemRegion::getBaseRegion(), clang::CallExpr::getBeginLoc(), clang::CXXConstructExpr::getBeginLoc(), clang::Expr::getBestDynamicClassType(), getBestNamespaceSubstr(), clang::SEHExceptStmt::getBlock(), clang::SEHFinallyStmt::getBlock(), getBlockExpr(), clang::OMPLoopDirective::getBody(), clang::CodeGen::CodeGenModule::getBuiltinLibFunction(), clang::OMPLoopDirective::getCalcLastIteration(), clang::CallExpr::getCallee(), clang::CallExpr::getCallee(), clang::ento::CallEventManager::getCaller(), clang::ClassTemplateDecl::getCanonicalDecl(), clang::ClassTemplateDecl::getCanonicalDecl(), clang::CXXConstructorDecl::getCanonicalDecl(), clang::CXXConversionDecl::getCanonicalDecl(), clang::CXXDestructorDecl::getCanonicalDecl(), clang::CXXMethodDecl::getCanonicalDecl(), clang::CXXRecordDecl::getCanonicalDecl(), clang::EnumDecl::getCanonicalDecl(), clang::FunctionTemplateDecl::getCanonicalDecl(), clang::FunctionTemplateDecl::getCanonicalDecl(), clang::ObjCMethodDecl::getCanonicalDecl(), clang::TypeAliasTemplateDecl::getCanonicalDecl(), clang::TypeAliasTemplateDecl::getCanonicalDecl(), clang::VarTemplateDecl::getCanonicalDecl(), clang::VarTemplateDecl::getCanonicalDecl(), clang::ASTContext::getCanonicalTemplateArgument(), clang::ento::BlockDataRegion::referenced_vars_iterator::getCapturedRegion(), clang::OMPChildren::getCapturedStmt(), clang::ento::SwitchNodeBuilder::iterator::getCase(), clang::ento::SymbolManager::getCastSymbol(), getCC1Arguments(), getCCTypeAttr(), getClangCallTerminateFn(), getCodegenToUse(), clang::CodeGen::ABIArgInfo::getCoerceAndExpandType(), clang::MatrixSubscriptExpr::getColumnIdx(), clang::OMPLoopDirective::getCombinedCond(), clang::OMPLoopDirective::getCombinedDistCond(), clang::OMPLoopDirective::getCombinedEnsureUpperBound(), clang::OMPLoopDirective::getCombinedInit(), clang::OMPLoopDirective::getCombinedLowerBoundVariable(), clang::OMPLoopDirective::getCombinedNextLowerBound(), clang::OMPLoopDirective::getCombinedNextUpperBound(), clang::OMPLoopDirective::getCombinedParForInDistCond(), clang::OMPLoopDirective::getCombinedUpperBoundVariable(), clang::BinaryConditionalOperator::getCommon(), clang::ArrayInitLoopExpr::getCommonExpr(), getComplexType(), clang::LambdaExpr::getCompoundStmtBody(), clang::AbstractConditionalOperator::getCond(), clang::BinaryConditionalOperator::getCond(), clang::ChooseExpr::getCond(), clang::ConditionalOperator::getCond(), clang::OMPLoopDirective::getCond(), clang::ForStmt::getConditionVariable(), clang::IfStmt::getConditionVariable(), clang::SwitchStmt::getConditionVariable(), clang::WhileStmt::getConditionVariable(), clang::CodeGen::CodeGenModule::GetConstantArrayFromStringLiteral(), clang::ento::SValBuilder::getConstantVal(), clang::ConstructorUsingShadowDecl::getConstructedBaseClass(), clang::ObjCIvarDecl::getContainingInterface(), clang::GenericSelectionExpr::getControllingExpr(), clang::GenericSelectionExpr::getControllingExpr(), clang::CastExpr::getConversionFunction(), clang::analyze_printf::PrintfSpecifier::getConversionSpecifier(), clang::analyze_scanf::ScanfSpecifier::getConversionSpecifier(), GetConversionType(), getCoroutineSuspendExprReturnType(), clang::CXXMethodDecl::getCorrespondingMethodInClass(), clang::Sema::getCurFunctionOrMethodDecl(), getCurrentInstantiationOf(), getCursorKindForDecl(), clang::ento::MemRegionManager::getCXXBaseObjectRegion(), clang::DeclarationNameTable::getCXXDeductionGuideName(), getCXXRecord(), clang::ento::AnyFunctionCall::getDecl(), clang::InjectedClassNameType::getDecl(), clang::StmtIteratorBase::GetDeclExpr(), getDeclForLocalLookup(), GetDeclSpecTypeForDeclarator(), clang::MacroDirective::getDefinition(), getDepthAndIndex(), clang::ento::SymbolManager::getDerivedSymbol(), clang::Sema::getDestructorName(), clang::OMPDeviceClause::getDevice(), clang::OMPDeviceClause::getDevice(), clang::OMPLoopDirective::getDistInc(), clang::syntax::List::getElementsAsNodesAndDelimiters(), getEnclosingStmtLocation(), clang::CallExpr::getEndLoc(), clang::CXXConstructExpr::getEndLoc(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::ObjCPropertyRefExpr::getExplicitProperty(), clang::ShuffleVectorExpr::getExpr(), clang::ShuffleVectorExpr::getExpr(), clang::ento::SymbolManager::getExtentSymbol(), clang::DeclContext::getExternCContext(), clang::AbstractConditionalOperator::getFalseExpr(), clang::BinaryConditionalOperator::getFalseExpr(), clang::ConditionalOperator::getFalseExpr(), clang::ASTContext::getFieldOffset(), clang::Mergeable< decl_type >::getFirstDecl(), clang::Mergeable< decl_type >::getFirstDecl(), getFriendCountAndPosition(), clang::ExplicitSpecifier::getFromDecl(), GetFullTypeForDeclarator(), clang::TypeName::getFullyQualifiedType(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), getFunctionOrMethodNumParams(), getFunctionOrMethodParamType(), getFunctionOrMethodResultType(), clang::BlockExpr::getFunctionType(), clang::CodeGen::CodeGenTypes::GetFunctionTypeForVTable(), clang::CXXTryStmt::getHandler(), clang::CXXTryStmt::getHandler(), clang::BindingDecl::getHoldingVar(), clang::MSPropertySubscriptExpr::getIdx(), clang::MSPropertySubscriptExpr::getIdx(), getImplicitObjectParamType(), clang::OMPLoopDirective::getInc(), clang::CXXRecordDecl::getIndirectPrimaryBases(), clang::ento::CXXInheritedConstructorCall::getInheritingConstructor(), clang::DesignatedInitExpr::getInit(), clang::OMPLoopDirective::getInit(), clang::VarDecl::getInit(), clang::CompoundLiteralExpr::getInitializer(), clang::CompoundLiteralExpr::getInitializer(), clang::CXXNewExpr::getInitializer(), clang::CXXNewExpr::getInitializer(), clang::ento::AnyCXXConstructorCall::getInitialStackFrameContents(), clang::ento::AnyFunctionCall::getInitialStackFrameContents(), clang::ento::BlockCall::getInitialStackFrameContents(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ClassTemplatePartialSpecializationDecl::getInjectedSpecializationType(), clang::ASTContext::getInjectedTemplateArg(), clang::InjectedClassNameType::getInjectedTST(), clang::CodeGen::EHScopeStack::getInnermostActiveNormalCleanup(), clang::DeclContext::getInnermostBlockDecl(), clang::OMPChildren::getInnermostCapturedStmt(), clang::GCCAsmStmt::getInputExpr(), clang::MSAsmStmt::getInputExpr(), clang::ClassTemplatePartialSpecializationDecl::getInstantiatedFromMember(), clang::VarTemplatePartialSpecializationDecl::getInstantiatedFromMember(), clang::CXXRecordDecl::getInstantiatedFromMemberClass(), clang::EnumDecl::getInstantiatedFromMemberEnum(), clang::FunctionDecl::getInstantiatedFromMemberFunction(), clang::VarDecl::getInstantiatedFromStaticDataMember(), clang::ento::SymbolManager::getIntSymExpr(), getInvokerAsMethod(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::CodeGen::CodeGenVTables::getItaniumVTableContext(), clang::OMPLoopDirective::getIterationVariable(), clang::ObjCSubscriptRefExpr::getKeyExpr(), clang::ento::IndirectGotoNodeBuilder::iterator::getLabel(), clang::GCCAsmStmt::getLabelExpr(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::CXXRecordDecl::getLambdaStaticInvoker(), clang::CFGBlock::getLastCondition(), clang::OMPLoopDirective::getLastIteration(), clang::DeclContext::getLexicalParent(), clang::ArraySubscriptExpr::getLHS(), clang::ArraySubscriptExpr::getLHS(), clang::BinaryOperator::getLHS(), clang::ChooseExpr::getLHS(), clang::ConditionalOperator::getLHS(), clang::UserDefinedLiteral::getLiteralOperatorKind(), getLoopCondition(), clang::CXXForRangeStmt::getLoopVariable(), clang::CXXForRangeStmt::getLoopVarStmt(), clang::CXXForRangeStmt::getLoopVarStmt(), clang::OMPLoopDirective::getLowerBoundVariable(), clang::ento::StoreManager::getLValueElement(), clang::LinkageComputer::getLVForDecl(), clang::CodeGen::CodeGenModule::getMangledName(), clang::CodeGen::CodeGenModule::getMemberPointerConstant(), clang::ASTContext::getMemberPointerPathAdjustment(), clang::Sema::getMessageSendResultType(), clang::ento::SymbolManager::getMetadataSymbol(), clang::CXXMemberCallExpr::getMethodDecl(), clang::MicrosoftVTableContext::getMethodVFTableLocation(), clang::ItaniumVTableContext::getMethodVTableIndex(), clang::CodeGen::CodeGenVTables::getMicrosoftVTableContext(), clang::MacroQualifiedType::getModifiedType(), clang::ClassTemplateDecl::getMostRecentDecl(), clang::ClassTemplatePartialSpecializationDecl::getMostRecentDecl(), clang::ClassTemplateSpecializationDecl::getMostRecentDecl(), clang::CXXMethodDecl::getMostRecentDecl(), clang::CXXRecordDecl::getMostRecentDecl(), clang::EnumDecl::getMostRecentDecl(), clang::FunctionTemplateDecl::getMostRecentDecl(), clang::NamedDecl::getMostRecentDecl(), clang::RecordDecl::getMostRecentDecl(), clang::VarTemplateDecl::getMostRecentDecl(), clang::VarTemplatePartialSpecializationDecl::getMostRecentDecl(), clang::VarTemplateSpecializationDecl::getMostRecentDecl(), clang::Sema::getMostSpecialized(), clang::NamespaceAliasDecl::getNamespace(), clang::TemplateName::getNameToSubstitute(), clang::OverloadExpr::getNamingClass(), clang::OMPLoopDirective::getNextLowerBound(), clang::ento::ExplodedNode::getNextStmtForDiagnostics(), clang::OMPLoopDirective::getNextUpperBound(), getNonClosureContext(), clang::Sema::getNumArgumentsInExpansion(), clang::OMPLoopDirective::getNumIterations(), clang::CodeGen::CodeGenFunction::AbstractCallee::getNumParams(), clang::FunctionTypeLoc::getNumParams(), clang::OMPNumTeamsClause::getNumTeams(), clang::OMPNumTeamsClause::getNumTeams(), clang::ASTContext::getObjCImplementation(), clang::ASTContext::getObjCImplementation(), clang::Expr::getObjCProperty(), clang::ASTContext::getObjCPropertyImplDeclForPropertyDecl(), clang::Sema::getOpenMPDeclareMapperVarName(), clang::DependentCoawaitExpr::getOperand(), clang::DependentCoawaitExpr::getOperatorCoawaitLookup(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::AtomicExpr::getOrder(), clang::AtomicExpr::getOrderFail(), clang::ento::BlockDataRegion::referenced_vars_iterator::getOriginalRegion(), clang::ento::BlockCall::getOriginExpr(), clang::ento::CXXAllocatorCall::getOriginExpr(), clang::ento::CXXConstructorCall::getOriginExpr(), clang::ento::CXXDeallocatorCall::getOriginExpr(), clang::ento::CXXInheritedConstructorCall::getOriginExpr(), clang::ento::CXXMemberCall::getOriginExpr(), clang::ento::CXXMemberOperatorCall::getOriginExpr(), clang::ento::ObjCMethodCall::getOriginExpr(), clang::ento::SimpleFunctionCall::getOriginExpr(), clang::DeclContext::getOuterLexicalRecordContext(), getOutermostFuncOrBlockContext(), clang::GCCAsmStmt::getOutputExpr(), clang::MSAsmStmt::getOutputExpr(), clang::ObjCMethodDecl::getOverriddenMethods(), clang::TemplateArgument::getPackExpansionPattern(), clang::CodeGen::CodeGenFunction::AbstractCallee::getParamDecl(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::ConstructorUsingShadowDecl::getParent(), clang::ConstructorUsingShadowDecl::getParent(), clang::CXXMethodDecl::getParent(), clang::CXXMethodDecl::getParent(), clang::DeclContext::getParent(), clang::DeclContext::getParentASTContext(), clang::DecayedType::getPointeeType(), clang::OMPLoopDirective::getPreCond(), getPreferredArgumentTypeForMessageSend(), clang::OMPLoopDirective::getPrevEnsureUpperBound(), clang::OMPLoopDirective::getPrevLowerBoundVariable(), clang::OMPLoopDirective::getPrevUpperBoundVariable(), clang::DeclContext::getPrimaryContext(), getPrimaryDecl(), clang::OMPPriorityClause::getPriority(), clang::OMPPriorityClause::getPriority(), clang::CoroutineBodyStmt::getPromiseDecl(), clang::AtomicExpr::getPtr(), clang::CXXForRangeStmt::getRangeStmt(), clang::CXXForRangeStmt::getRangeStmt(), clang::ento::SymbolManager::getRegionValueSymbol(), clang::SubstNonTypeTemplateParmExpr::getReplacement(), clang::GenericSelectionExpr::getResultExpr(), clang::GenericSelectionExpr::getResultExpr(), clang::CoroutineBodyStmt::getReturnValueInit(), clang::ArraySubscriptExpr::getRHS(), clang::ArraySubscriptExpr::getRHS(), clang::BinaryOperator::getRHS(), clang::ChooseExpr::getRHS(), clang::ConditionalOperator::getRHS(), clang::MatrixSubscriptExpr::getRowIdx(), clang::MatrixSubscriptExpr::getRowIdx(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::AtomicExpr::getScope(), clang::CXXRewrittenBinaryOperator::getSemanticForm(), clang::CXXRewrittenBinaryOperator::getSemanticForm(), clang::threadSafety::getSourceLiteralString(), clang::ClassTemplateSpecializationDecl::getSourceRange(), clang::AsTypeExpr::getSrcExpr(), clang::ConvertVectorExpr::getSrcExpr(), getStackIndexOfNearestEnclosingCaptureCapableLambda(), getStackIndexOfNearestEnclosingCaptureReadyLambda(), getStackOrCaptureRegionForDeclContext(), getStaticDeclName(), clang::ento::MemRegionManager::getStaticSize(), clang::ento::ExplodedNode::getStmtForDiagnostics(), clang::LifetimeExtendedTemporaryDecl::getStorageDuration(), clang::OMPLoopDirective::getStrideVariable(), clang::ObjCStringLiteral::getString(), clang::ObjCStringLiteral::getString(), clang::ArrayInitLoopExpr::getSubExpr(), clang::CastExpr::getSubExpr(), clang::CastExpr::getSubExpr(), clang::CXXBindTemporaryExpr::getSubExpr(), clang::CXXBindTemporaryExpr::getSubExpr(), clang::DesignatedInitExpr::getSubExpr(), clang::FullExpr::getSubExpr(), clang::FullExpr::getSubExpr(), clang::ImaginaryLiteral::getSubExpr(), clang::ImaginaryLiteral::getSubExpr(), clang::MaterializeTemporaryExpr::getSubExpr(), clang::ObjCBoxedExpr::getSubExpr(), clang::ObjCBoxedExpr::getSubExpr(), clang::ObjCIndirectCopyRestoreExpr::getSubExpr(), clang::ObjCIndirectCopyRestoreExpr::getSubExpr(), clang::ParenExpr::getSubExpr(), clang::ParenExpr::getSubExpr(), clang::UnaryOperator::getSubExpr(), clang::VAArgExpr::getSubExpr(), clang::VAArgExpr::getSubExpr(), clang::StmtExpr::getSubStmt(), clang::StmtExpr::getSubStmt(), clang::ento::Environment::getSVal(), getSwiftABIInfo(), clang::ento::SwitchNodeBuilder::getSwitch(), getSymbolicOffsetFields(), clang::index::getSymbolInfo(), clang::ento::SymbolManager::getSymIntExpr(), clang::ento::SymbolManager::getSymSymExpr(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::Decl::getTemplateDepth(), clang::Sema::getTemplateInstantiationArgs(), clang::LifetimeExtendedTemporaryDecl::getTemporaryExpr(), clang::LifetimeExtendedTemporaryDecl::getTemporaryExpr(), clang::CFGBlock::getTerminatorCondition(), clang::OMPThreadLimitClause::getThreadLimit(), clang::OMPThreadLimitClause::getThreadLimit(), clang::VTableContextBase::getThunkInfo(), clang::OverloadExpr::getTrailingASTTemplateKWAndArgsInfo(), clang::OverloadExpr::getTrailingResults(), clang::OverloadExpr::getTrailingTemplateArgumentLoc(), clang::Decl::getTranslationUnitDecl(), clang::AbstractConditionalOperator::getTrueExpr(), clang::BinaryConditionalOperator::getTrueExpr(), clang::ConditionalOperator::getTrueExpr(), clang::CXXTryStmt::getTryBlock(), clang::CXXTryStmt::getTryBlock(), clang::SEHTryStmt::getTryBlock(), clang::concepts::ExprRequirement::ReturnTypeRequirement::getTypeConstraint(), getTypeInfoLinkage(), clang::CanQual< typename >::getTypePtr(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), clang::InheritingConcreteTypeLoc< Base, Derived, TypeClass >::getTypePtr(), clang::UserDefinedLiteral::getUDSuffix(), clang::Sema::getUndefinedButUsed(), clang::OMPClauseMappableExprCommon::getUniqueDeclarationsTotalNumber(), clang::ASTContext::getUnqualifiedArrayType(), GetUnreachableLoc(), clang::DesignatedInitUpdateExpr::getUpdater(), clang::OMPLoopDirective::getUpperBoundVariable(), clang::UsingShadowDecl::getUsingDecl(), clang::AtomicExpr::getVal1(), clang::AtomicExpr::getVal2(), clang::ASTContext::getVariableArrayDecayedType(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::AtomicExpr::getWeak(), clang::CodeGen::CodeGenModule::GetWeakRefReference(), HandleConstructorCall(), clang::index::IndexingContext::handleDecl(), clang::Sema::HandleDelayedAccessCheck(), clang::Sema::HandleDependentAccessCheck(), HandleImmediateInvocations(), handleIncDec(), handleIntegerToComplexFloatConversion(), clang::Sema::HandlePropertyInClassExtension(), clang::CodeGen::CodeGenModule::HasLTOVisibilityPublicStd(), HasNoThrowOperator(), clang::Expr::HasSideEffects(), clang::DeclSpec::hasTagDefinition(), HasTrivialDestructorBody(), hasVisibleDeclarationImpl(), clang::CodeGen::CodeGenFunction::hasVolatileMember(), clang::Sema::HideUsingShadowDecl(), ignoreTransparentExprs(), clang::Expr::IgnoreUnlessSpelledInSource(), clang::Sema::ImplicitlyDefineFunction(), clang::ASTImporter::Import(), clang::ASTImporter::Import(), clang::ASTNodeImporter::ImportAPValue(), clang::ASTImporter::ImportContext(), clang::ASTImporter::ImportDefinition(), clang::ASTNodeImporter::ImportDefinition(), clang::Sema::inferCUDATargetForImplicitSpecialMember(), inheritDefaultTemplateArgument(), InitCatchParam(), clang::ASTReader::InitializeSema(), InjectAnonymousStructOrUnionMembers(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), clang::ADLResult::insert(), clang::threadSafety::BeforeSet::insertAttrExprs(), clang::CodeGen::LoopInfoStack::InsertHelper(), clang::Sema::InstantiateAttrs(), clang::Sema::InstantiateClassMembers(), clang::Sema::InstantiateClassTemplateSpecialization(), instantiateOMPDeclareSimdDeclAttr(), instantiateOMPDeclareVariantAttr(), clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), clang::Sema::InstantiateVariableDefinition(), isAccessedBy(), clang::CXXDynamicCastExpr::isAlwaysNull(), isBetterOverloadCandidate(), isConditionForTerminator(), isConfigurationValue(), clang::Expr::isConstantInitializer(), clang::ParentMap::isConsumedExpr(), clang::NamedDecl::isCXXInstanceMember(), isDeclWithinFunction(), isDependentContextAtLevel(), IsDerivedFromInclusive(), isDesignatorAtObjectEnd(), clang::Sema::isEquivalentInternalLinkageDeclaration(), clang::Sema::IsFunctionConversion(), isFunctionOrMethodVariadic(), isFunctionOrVarDeclExternC(), IsGlobalLValue(), isIdenticalStmt(), clang::CXXDependentScopeMemberExpr::isImplicitAccess(), clang::UnresolvedMemberExpr::isImplicitAccess(), clang::Type::isIncompleteType(), IsInitializerListConstructorConversion(), isInitializerOfDynamicClass(), clang::RecordDecl::isInjectedClassName(), clang::DeclContext::isInlineNamespace(), isInLoopBody(), isInstantiationOf(), isInstantiationOf(), clang::AnalysisDeclContext::isInStdNamespace(), isLayoutCompatibleStruct(), isLibstdcxxPointerReturnFalseHack(), isLinkageSpecContext(), clang::ClassTemplatePartialSpecializationDecl::isMemberSpecialization(), clang::VarTemplatePartialSpecializationDecl::isMemberSpecialization(), clang::Sema::isMicrosoftMissingTypename(), isNonEHScope(), clang::Expr::isOBJCGCCandidate(), clang::Sema::isOpenMPCapturedByRef(), clang::Sema::isOpenMPCapturedDecl(), clang::Sema::IsOverload(), IsPartOfAST(), isPreferredLookupResult(), isRelevantAttr(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), isSafeForCXXConstantCapture(), clang::Expr::isSameComparisonOperand(), isSameEntity(), isSameTemplateParameter(), clang::DeclContext::isStdNamespace(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalent(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), isTemplate(), clang::Sema::isTemplateName(), clang::DeclContext::isTransparentContext(), clang::Expr::isUnusedResultAWarning(), IsUsedAsNormalCleanup(), IsUserDefinedConversion(), isValidVectorForConditionalCondition(), clang::FieldDecl::isZeroSize(), LandingPadHasOnlyCXXUses(), clang::CodeGen::swiftcall::legalizeVectorType(), clang::Sema::LookupDestructor(), LookupDirect(), clang::CXXRecordDecl::lookupInBases(), clang::Sema::LookupInSuper(), LookupMemberExpr(), LookupMethodInReceiverType(), clang::Sema::LookupOrCreateLabel(), clang::MangleContext::mangleName(), mapParam(), clang::CodeGen::CGOpenMPRuntime::markAsGlobalTarget(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkFunctionReferenced(), MarkUsedTemplateParameters(), clang::Sema::MarkVirtualBaseDestructorsReferenced(), clang::Sema::MarkVirtualMembersReferenced(), MatchesFriend(), MatchesFriend(), MatchTemplateParameterKind(), clang::CXXRecordDecl::mayBeAbstract(), clang::Sema::MaybeBindToTemporary(), maybeRecoverWithZeroInitialization(), maybeUndoReclaimObject(), clang::ASTContext::mayExternalizeStaticVar(), mergeDeclAttribute(), clang::Sema::mergeDeclAttributes(), clang::ASTContext::mergeDefinitionIntoModule(), clang::Sema::MergeFunctionDecl(), clang::ASTDeclReader::mergeInheritableAttributes(), clang::ASTContext::mergeObjCGCQualifiers(), mergeParamDeclAttributes(), clang::ASTDeclReader::mergeTemplatePattern(), clang::Sema::MergeTypedefNameDecl(), MVEImmediateShr(), clang::analyze_format_string::FormatSpecifier::namedTypeToLengthModifier(), clang::CodeGen::ReductionCodeGen::needCleanups(), NeedsInjectedClassNameType(), clang::CodeGen::DominatingLLVMValue::needsSaving(), clang::CodeGen::CGOpenMPRuntime::NontemporalDeclsRAII::NontemporalDeclsRAII(), notePlausibleOverloads(), clang::CodeGen::CodeGenFunction::OpaqueValueMapping::OpaqueValueMapping(), clang::Decl::operator new(), clang::DeclContext::filtered_decl_iterator< SpecificDecl, Acceptable >::operator*(), clang::DeclContext::specific_decl_iterator< SpecificDecl >::operator*(), clang::DeclContext::udir_iterator::operator*(), clang::OMPExecutableDirective::specific_clause_iterator< SpecificClause >::operator*(), clang::OMPMappableExprListClause< T >::const_component_lists_iterator::operator*(), clang::specific_attr_iterator< SpecificAttr, Container >::operator*(), clang::DeclContext::filtered_decl_iterator< SpecificDecl, Acceptable >::operator->(), clang::specific_attr_iterator< SpecificAttr, Container >::operator->(), packTBLDVectorList(), clang::ento::parseAssignment(), clang::comments::Parser::parseBlockCommand(), clang::Sema::ParsedFreeStandingDeclSpec(), clang::Sema::ParseObjCStringLiteral(), clang::Sema::ParseTypedefDecl(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformPendingInstantiations(), clang::CodeGen::EHScopeStack::popCatch(), clang::CodeGen::EHScopeStack::popCleanup(), clang::CodeGen::EHScopeStack::popFilter(), clang::CodeGen::EHScopeStack::popNullFixups(), clang::CodeGen::EHScopeStack::popTerminate(), print_construction_context(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr(), clang::Sema::PrintInstantiationStack(), clang::APValue::printPretty(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::Sema::ProcessPropertyDecl(), ProfileTemplateParameterList(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), pushTemporaryCleanup(), clang::ASTReader::ReadLateParsedTemplates(), clang::ASTReader::ReadMismatchingDeleteExpressions(), clang::ASTReader::ReadPendingInstantiations(), clang::ASTReader::ReadPreprocessedEntity(), clang::ASTReader::ReadUndefinedButUsed(), clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr(), clang::TreeTransform< Derived >::RebuildObjCIvarRefExpr(), rebuildPotentialResultsAsNonOdrUsed(), clang::TreeTransform< Derived >::RebuildShuffleVectorExpr(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::TreeTransform< Derived >::RebuildUnresolvedUsingType(), recordConversion(), clang::Sema::recreateSyntacticForm(), RefersToRValueRef(), REGISTER_MAP_WITH_PROGRAMSTATE(), REGISTER_MAP_WITH_PROGRAMSTATE(), REGISTER_TRAIT_WITH_PROGRAMSTATE(), clang::CodeGen::CGOpenMPRuntime::registerTargetFirstprivateCopy(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), clang::DeclContext::removeDecl(), removeRedundantMsgs(), clang::UsingDecl::removeShadowDecl(), removeUnneededCalls(), replaceManagedVar(), clang::tooling::replaceNestedName(), replaceUndef(), replaceUsesOfNonProtoConstant(), clang::Sema::RequireLiteralType(), requiresAMDGPUProtectedVisibility(), resolveAllocationOverload(), resolveBuiltinNewDeleteOverload(), ResolveConstructorOverload(), clang::LookupResult::resolveKind(), ResolveOverloadForDeduction(), clang::Sema::ResolveSingleFunctionTemplateSpecialization(), clang::CodeGen::DominatingLLVMValue::restore(), clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement(), rewriteBuiltinFunctionDecl(), clang::RopePieceBTreeIterator::RopePieceBTreeIterator(), SemaBuiltinCallWithStaticChain(), SemaBuiltinCpuIs(), SemaBuiltinCpuSupports(), SemaBuiltinSEHScopeCheck(), SemaOpenCLBuiltinEnqueueKernel(), clang::CodeGen::EHCleanupScope::setActiveFlag(), clang::CXXRecordDecl::setBases(), clang::ASTContext::setCFConstantStringType(), clang::CodeGen::CodeGenModule::SetCommonAttributes(), clang::Sema::SetDeclDefaulted(), clang::ASTReader::SetGloballyVisibleDecls(), clang::ClassTemplatePartialSpecializationDecl::setInstantiatedFromMember(), clang::VarTemplatePartialSpecializationDecl::setInstantiatedFromMember(), clang::Sema::SetIvarInitializers(), clang::CodeGen::CGDebugInfo::setLocation(), clang::ClassTemplatePartialSpecializationDecl::setMemberSpecialization(), clang::VarTemplatePartialSpecializationDecl::setMemberSpecialization(), setObjCGCLValueClass(), clang::CXXDestructorDecl::setOperatorDelete(), SetupCleanupBlockActivation(), clang::Sema::shouldSkipAnonEnumBody(), shouldSkipNotingLambdaConversionDecl(), ShouldUseExternalRTTIDescriptor(), showBRDiagnostics(), showBRParamDiagnostics(), clang::Expr::skipRValueSubobjectAdjustments(), clang::CodeGen::swiftcall::splitLegalVectorType(), clang::TagDecl::startDefinition(), clang::Sema::stripARCUnbridgedCast(), clang::ento::MemRegion::StripCasts(), stripOpaqueValuesFromPseudoObjectRef(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::Sema::SubstParmVarDecl(), clang::threadSafety::til::Terminator::successors(), clang::TreeTransform< Derived >::TransformOMPExecutableDirective(), transformOMPMappableExprListClause(), clang::TreeTransform< Derived >::TransformOverloadExprDecls(), TransitionToCleanupSwitch(), clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter(), clang::Sema::tryCaptureVariable(), TryConstructorInitialization(), clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias(), tryEmitFusedAutoreleaseOfResult(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), tryMatchRecordTypes(), TryRefInitWithConversionFunction(), TryStaticMemberPointerUpcast(), TryUserDefinedConversion(), typeIsPostfix(), UnwrapTypeForDebugInfo(), clang::CodeGen::CodeGenTypes::UpdateCompletedType(), clang::ASTDeclReader::UpdateDecl(), clang::ento::ExprEngine::updateObjectsUnderConstruction(), clang::Sema::UseArgumentDependentLookup(), clang::FunctionCallFilterCCC::ValidateCandidate(), VariableCanNeverBeAConstantExpression(), VectorUnzip(), VectorZip(), clang::ASTDeclReader::Visit(), clang::ento::ExprEngine::Visit(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), clang::ASTDeclReader::VisitClassTemplateSpecializationDeclImpl(), clang::UsedDeclVisitor< Derived >::VisitCXXDeleteExpr(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeImporter::VisitExplicitCastExpr(), clang::ASTNodeImporter::VisitFriendDecl(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), clang::ento::ExprEngine::VisitGuardedExpr(), visitLifetimeBoundArguments(), visitLocalsRetainedByInitializer(), visitLocalsRetainedByReferenceBinding(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ASTNodeImporter::VisitMaterializeTemporaryExpr(), clang::ento::ExprEngine::VisitMemberExpr(), clang::ASTDeclReader::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitNamespaceDecl(), clang::ASTNodeImporter::VisitNamespaceDecl(), clang::ento::FindLastStoreBRVisitor::VisitNode(), clang::ento::ExprEngine::VisitObjCForCollectionStmt(), clang::ASTNodeImporter::VisitObjCPropertyImplDecl(), clang::ASTNodeImporter::VisitRecordDecl(), clang::ASTNodeImporter::VisitSubstTemplateTypeParmType(), clang::ASTNodeImporter::VisitTypedefNameDecl(), and clang::ASTDeclReader::VisitVarTemplateSpecializationDeclImpl().
cast_away_const()
StmtIterator clang::cast_away_const (const ConstStmtIterator & RHS) inline
Definition at line 152 of file StmtIterator.h.
Referenced by clang::InitListExpr::children(), clang::PseudoObjectExpr::children(), and clang::UnaryExprOrTypeTraitExpr::children().
checkCalledOnceParameters()
void clang::checkCalledOnceParameters (AnalysisDeclContext & AC, CalledOnceCheckHandler & Handler, bool CheckConventionalParameters)
Check given CFG for 'called once' parameter violations.
It traverses the function and tracks how such parameters are used. It detects two main violations:
parameter is called twice
parameter is not called
Parameters
AC – context.
Handler – a handler for found violations.
CheckConventionalParameters – true, if we want to check parameters not explicitly marked as 'called once', but having the same requirements according to conventions.
Definition at line 1520 of file CalledOnceCheck.cpp.
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
CheckEquivalentExceptionSpecImpl()
static bool clang::CheckEquivalentExceptionSpecImpl (Sema & S, const PartialDiagnostic & DiagID, const PartialDiagnostic & NoteID, const FunctionProtoType * Old, SourceLocation OldLoc, const FunctionProtoType * New, SourceLocation NewLoc, bool * MissingExceptionSpecification, bool * MissingEmptyExceptionSpecification, bool AllowNoexceptAllMatchWithNoSpec, bool IsOperatorNew) static
CheckEquivalentExceptionSpec - Check if the two types have compatible exception specifications.
See C++ [except.spec]p3.
Returns
false if the exception specifications match, true if there is a problem. If true is returned, either a diagnostic has already been produced or *MissingExceptionSpecification is set to true.
Definition at line 508 of file SemaExceptionSpec.cpp.
References clang::FunctionProtoType::canThrow(), clang::Sema::Context, CT_Can, CT_Cannot, clang::Sema::Diag(), EST_DependentNoexcept, EST_Dynamic, EST_NoexceptFalse, EST_None, clang::FunctionProtoType::exception_begin(), clang::FunctionProtoType::exceptions(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getCanonicalType(), clang::PartialDiagnostic::getDiagID(), clang::FunctionProtoType::getExceptionSpecType(), clang::Sema::getLangOpts(), clang::FunctionProtoType::getNoexceptExpr(), clang::FunctionProtoType::getNumExceptions(), clang::CanQual< typename >::getUnqualifiedType(), isUnresolvedExceptionSpec(), clang::SourceLocation::isValid(), clang::Stmt::Profile(), and clang::Sema::ResolveExceptionSpec().
Referenced by clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckEquivalentExceptionSpec(), and clang::Sema::CheckEquivalentExceptionSpec().
CheckSpecForTypesEquivalent()
static bool clang::CheckSpecForTypesEquivalent (Sema & S, const PartialDiagnostic & DiagID, const PartialDiagnostic & NoteID, QualType Target, SourceLocation TargetLoc, QualType Source, SourceLocation SourceLoc) static
Definition at line 863 of file SemaExceptionSpec.cpp.
References clang::Sema::CheckEquivalentExceptionSpec(), and GetUnderlyingFunction().
Referenced by clang::Sema::CheckParamExceptionSpec().
commonComparisonType()
ComparisonCategoryType clang::commonComparisonType (ComparisonCategoryType A, ComparisonCategoryType B) inline
Determine the common comparison type, as defined in C++2a [class.spaceship]p4.
Definition at line 53 of file ComparisonCategories.h.
computeDependence() [1/79]
ExprDependence clang::computeDependence (ArrayInitLoopExpr * E)
Definition at line 220 of file ComputeDependence.cpp.
References clang::ArrayInitLoopExpr::getCommonExpr(), clang::Expr::getDependence(), clang::ArrayInitLoopExpr::getSubExpr(), clang::Expr::getType(), clang::Type::isInstantiationDependentType(), and turnTypeToValueDependence().
computeDependence() [2/79]
ExprDependence clang::computeDependence (ArraySubscriptExpr * E)
Definition at line 112 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::ArraySubscriptExpr::getLHS(), and clang::ArraySubscriptExpr::getRHS().
computeDependence() [3/79]
ExprDependence clang::computeDependence (ArrayTypeTraitExpr * E)
Definition at line 318 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::ArrayTypeTraitExpr::getDimensionExpression(), clang::ArrayTypeTraitExpr::getQueriedType(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [4/79]
ExprDependence clang::computeDependence (AsTypeExpr * E)
Definition at line 244 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::AsTypeExpr::getSrcExpr(), clang::Expr::getType(), clang::Type::isDependentType(), toExprDependence(), and Type.
computeDependence() [5/79]
ExprDependence clang::computeDependence (AtomicExpr * E)
Definition at line 657 of file ComputeDependence.cpp.
References clang::AtomicExpr::getNumSubExprs(), and clang::AtomicExpr::getSubExprs().
computeDependence() [6/79]
ExprDependence clang::computeDependence (BinaryConditionalOperator * E)
Definition at line 156 of file ComputeDependence.cpp.
References clang::BinaryConditionalOperator::getCommon(), clang::Expr::getDependence(), and clang::BinaryConditionalOperator::getFalseExpr().
computeDependence() [7/79]
ExprDependence clang::computeDependence (BinaryOperator * E)
Definition at line 143 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::BinaryOperator::getLHS(), and clang::BinaryOperator::getRHS().
computeDependence() [8/79]
ExprDependence clang::computeDependence (BlockExpr * E)
Definition at line 237 of file ComputeDependence.cpp.
References clang::BlockExpr::getBlockDecl(), clang::Type::getDependence(), clang::Expr::getType(), clang::DeclContext::isDependentContext(), and toExprDependence().
computeDependence() [9/79]
ExprDependence clang::computeDependence (CallExpr * E, llvm::ArrayRef< Expr * > PreArgs)
Definition at line 564 of file ComputeDependence.cpp.
References clang::CallExpr::getArgs(), clang::CallExpr::getCallee(), clang::Expr::getDependence(), and clang::CallExpr::getNumArgs().
computeDependence() [10/79]
ExprDependence clang::computeDependence (CastExpr * E)
Definition at line 127 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Stmt::getStmtClass(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), toExprDependence(), and Type.
computeDependence() [11/79]
ExprDependence clang::computeDependence (ChooseExpr * E)
Definition at line 184 of file ComputeDependence.cpp.
References clang::ChooseExpr::getCond(), clang::Expr::getDependence(), clang::ChooseExpr::getLHS(), clang::ChooseExpr::getRHS(), clang::ChooseExpr::isConditionDependent(), and clang::ChooseExpr::isConditionTrue().
computeDependence() [12/79]
ExprDependence clang::computeDependence (CompoundLiteralExpr * E)
Definition at line 122 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::CompoundLiteralExpr::getInitializer(), clang::TypeSourceInfo::getType(), clang::CompoundLiteralExpr::getTypeSourceInfo(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [13/79]
ExprDependence clang::computeDependence (ConceptSpecializationExpr * E, bool ValueDependent)
Definition at line 797 of file ComputeDependence.cpp.
References clang::ASTTemplateArgumentListInfo::arguments(), clang::ConceptReference::getTemplateArgsAsWritten(), and toExprDependence().
computeDependence() [14/79]
ExprDependence clang::computeDependence (ConditionalOperator * E)
Definition at line 147 of file ComputeDependence.cpp.
References clang::ConditionalOperator::getCond(), clang::Expr::getDependence(), clang::ConditionalOperator::getLHS(), and clang::ConditionalOperator::getRHS().
computeDependence() [15/79]
ExprDependence clang::computeDependence (ConvertVectorExpr * E)
Definition at line 176 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::ConvertVectorExpr::getSrcExpr(), clang::Expr::getType(), clang::Type::isDependentType(), toExprDependence(), and Type.
computeDependence() [16/79]
ExprDependence clang::computeDependence (CoroutineSuspendExpr * E)
Definition at line 350 of file ComputeDependence.cpp.
References clang::CoroutineSuspendExpr::getCommonExpr(), clang::Expr::getDependence(), and clang::CoroutineSuspendExpr::getResumeExpr().
computeDependence() [17/79]
ExprDependence clang::computeDependence (CXXBindTemporaryExpr * E)
Definition at line 305 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::CXXBindTemporaryExpr::getSubExpr().
computeDependence() [18/79]
ExprDependence clang::computeDependence (CXXConstructExpr * E)
Definition at line 736 of file ComputeDependence.cpp.
References clang::CXXConstructExpr::arguments(), clang::Type::getDependence(), clang::Expr::getType(), toExprDependence(), and Type.
computeDependence() [19/79]
ExprDependence clang::computeDependence (CXXDefaultInitExpr * E)
Definition at line 743 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::CXXDefaultInitExpr::getExpr().
computeDependence() [20/79]
ExprDependence clang::computeDependence (CXXDeleteExpr * E)
Definition at line 314 of file ComputeDependence.cpp.
References clang::CXXDeleteExpr::getArgument(), clang::Expr::getDependence(), and turnTypeToValueDependence().
computeDependence() [21/79]
ExprDependence clang::computeDependence (CXXDependentScopeMemberExpr * E)
Definition at line 764 of file ComputeDependence.cpp.
References clang::CXXDependentScopeMemberExpr::getBase(), clang::Expr::getDependence(), getDependenceInExpr(), clang::CXXDependentScopeMemberExpr::getMemberNameInfo(), clang::CXXDependentScopeMemberExpr::getQualifier(), clang::CXXDependentScopeMemberExpr::isImplicitAccess(), clang::CXXDependentScopeMemberExpr::template_arguments(), and toExprDependence().
computeDependence() [22/79]
ExprDependence clang::computeDependence (CXXFoldExpr * E)
Definition at line 780 of file ComputeDependence.cpp.
References C, clang::CXXFoldExpr::getLHS(), and clang::CXXFoldExpr::getRHS().
computeDependence() [23/79]
ExprDependence clang::computeDependence (CXXNewExpr * E)
Definition at line 664 of file ComputeDependence.cpp.
References clang::CXXNewExpr::getArraySize(), clang::Type::getDependence(), clang::CXXNewExpr::getInitializer(), clang::Expr::getType(), clang::CXXNewExpr::placement_arguments(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [24/79]
ExprDependence clang::computeDependence (CXXNoexceptExpr * E, CanThrowResult CT)
Definition at line 334 of file ComputeDependence.cpp.
References CT_Dependent, clang::Expr::getDependence(), and clang::CXXNoexceptExpr::getOperand().
computeDependence() [25/79]
ExprDependence clang::computeDependence (CXXPseudoDestructorExpr * E)
Definition at line 676 of file ComputeDependence.cpp.
References clang::CXXPseudoDestructorExpr::getBase(), clang::Expr::getDependence(), clang::Type::getDependence(), clang::CXXPseudoDestructorExpr::getDestroyedType(), clang::CXXPseudoDestructorExpr::getQualifier(), clang::CXXPseudoDestructorExpr::getScopeTypeInfo(), clang::QualType::isNull(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [26/79]
ExprDependence clang::computeDependence (CXXRewrittenBinaryOperator * E)
Definition at line 252 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::CXXRewrittenBinaryOperator::getSemanticForm().
computeDependence() [27/79]
ExprDependence clang::computeDependence (CXXScalarValueInitExpr * E)
Definition at line 309 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [28/79]
ExprDependence clang::computeDependence (CXXStdInitializerListExpr * E)
Definition at line 256 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::CXXStdInitializerListExpr::getSubExpr(), clang::Expr::getType(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [29/79]
ExprDependence clang::computeDependence (CXXThisExpr * E)
Definition at line 290 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [30/79]
ExprDependence clang::computeDependence (CXXThrowExpr * E)
Definition at line 298 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::CXXThrowExpr::getSubExpr().
computeDependence() [31/79]
ExprDependence clang::computeDependence (CXXTypeidExpr * E)
Definition at line 263 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::CXXTypeidExpr::getExprOperand(), clang::TypeSourceInfo::getType(), clang::CXXTypeidExpr::getTypeOperandSourceInfo(), clang::CXXTypeidExpr::isTypeOperand(), toExprDependence(), turnTypeToValueDependence(), and Type.
computeDependence() [32/79]
ExprDependence clang::computeDependence (CXXUnresolvedConstructExpr * E)
Definition at line 755 of file ComputeDependence.cpp.
References clang::CXXUnresolvedConstructExpr::arguments(), clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [33/79]
ExprDependence clang::computeDependence (CXXUuidofExpr * E)
Definition at line 282 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::CXXUuidofExpr::getExprOperand(), clang::TypeSourceInfo::getType(), clang::CXXUuidofExpr::getTypeOperandSourceInfo(), clang::CXXUuidofExpr::isTypeOperand(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [34/79]
ExprDependence clang::computeDependence (DeclRefExpr * E, const ASTContext & Ctx)
Compute the type-, value-, and instantiation-dependence of a declaration reference based on the declaration being referenced.
Definition at line 436 of file ComputeDependence.cpp.
References clang::DeclarationName::CXXConversionFunctionName, First, clang::DeclRefExpr::getDecl(), clang::Decl::getDeclContext(), clang::Type::getDependence(), clang::Redeclarable< decl_type >::getFirstDecl(), clang::DeclRefExpr::getNumTemplateArgs(), clang::DeclRefExpr::getQualifier(), clang::DeclRefExpr::getTemplateArgs(), clang::Expr::getType(), clang::TypeSourceInfo::getType(), clang::DeclContext::isDependentContext(), clang::Type::isDependentType(), clang::Type::isIncompleteArrayType(), clang::Type::isInstantiationDependentType(), clang::Decl::isParameterPack(), and toExprDependence().
computeDependence() [35/79]
ExprDependence clang::computeDependence (DependentCoawaitExpr * E)
Definition at line 359 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::DependentCoawaitExpr::getOperand().
computeDependence() [36/79]
ExprDependence clang::computeDependence (DependentScopeDeclRefExpr * E)
Definition at line 726 of file ComputeDependence.cpp.
References getDependenceInExpr(), clang::DependentScopeDeclRefExpr::getNameInfo(), clang::DependentScopeDeclRefExpr::getQualifier(), clang::DependentScopeDeclRefExpr::template_arguments(), and toExprDependence().
computeDependence() [37/79]
ExprDependence clang::computeDependence (DesignatedInitExpr * E)
Definition at line 634 of file ComputeDependence.cpp.
References clang::DesignatedInitExpr::designators(), clang::DesignatedInitExpr::getArrayIndex(), clang::DesignatedInitExpr::getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeStart(), clang::Expr::getDependence(), and clang::DesignatedInitExpr::getInit().
computeDependence() [38/79]
ExprDependence clang::computeDependence (ExpressionTraitExpr * E)
Definition at line 325 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::ExpressionTraitExpr::getQueriedExpression(), clang::Expr::isTypeDependent(), and Type.
computeDependence() [39/79]
ExprDependence clang::computeDependence (ExtVectorElementExpr * E)
Definition at line 233 of file ComputeDependence.cpp.
References clang::ExtVectorElementExpr::getBase(), and clang::Expr::getDependence().
computeDependence() [40/79]
ExprDependence clang::computeDependence (FullExpr * E)
Definition at line 24 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::FullExpr::getSubExpr().
Referenced by clang::ArrayInitLoopExpr::ArrayInitLoopExpr(), clang::ArraySubscriptExpr::ArraySubscriptExpr(), clang::ArrayTypeTraitExpr::ArrayTypeTraitExpr(), clang::AsTypeExpr::AsTypeExpr(), clang::AtomicExpr::AtomicExpr(), clang::BinaryConditionalOperator::BinaryConditionalOperator(), clang::BinaryOperator::BinaryOperator(), clang::BinaryOperator::BinaryOperator(), clang::BlockExpr::BlockExpr(), clang::CallExpr::CallExpr(), clang::CastExpr::CastExpr(), clang::ChooseExpr::ChooseExpr(), clang::CompoundLiteralExpr::CompoundLiteralExpr(), clang::ConceptSpecializationExpr::ConceptSpecializationExpr(), clang::ConditionalOperator::ConditionalOperator(), clang::ConvertVectorExpr::ConvertVectorExpr(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::CoroutineSuspendExpr::CoroutineSuspendExpr(), clang::CXXConstructExpr::CXXConstructExpr(), clang::CXXDeleteExpr::CXXDeleteExpr(), clang::CXXFoldExpr::CXXFoldExpr(), clang::CXXNoexceptExpr::CXXNoexceptExpr(), clang::CXXPseudoDestructorExpr::CXXPseudoDestructorExpr(), clang::CXXRewrittenBinaryOperator::CXXRewrittenBinaryOperator(), clang::CXXScalarValueInitExpr::CXXScalarValueInitExpr(), clang::CXXStdInitializerListExpr::CXXStdInitializerListExpr(), clang::CXXThisExpr::CXXThisExpr(), clang::CXXThrowExpr::CXXThrowExpr(), clang::CXXTypeidExpr::CXXTypeidExpr(), clang::CXXTypeidExpr::CXXTypeidExpr(), clang::CXXUuidofExpr::CXXUuidofExpr(), clang::CXXUuidofExpr::CXXUuidofExpr(), clang::DeclRefExpr::DeclRefExpr(), clang::DependentCoawaitExpr::DependentCoawaitExpr(), clang::ExpressionTraitExpr::ExpressionTraitExpr(), clang::ExtVectorElementExpr::ExtVectorElementExpr(), clang::FullExpr::FullExpr(), clang::ImplicitValueInitExpr::ImplicitValueInitExpr(), clang::InitListExpr::InitListExpr(), clang::MaterializeTemporaryExpr::MaterializeTemporaryExpr(), clang::MatrixSubscriptExpr::MatrixSubscriptExpr(), clang::MSPropertyRefExpr::MSPropertyRefExpr(), clang::MSPropertySubscriptExpr::MSPropertySubscriptExpr(), clang::NoInitExpr::NoInitExpr(), clang::ObjCBoxedExpr::ObjCBoxedExpr(), clang::ObjCEncodeExpr::ObjCEncodeExpr(), clang::ObjCIndirectCopyRestoreExpr::ObjCIndirectCopyRestoreExpr(), clang::ObjCIsaExpr::ObjCIsaExpr(), clang::ObjCIvarRefExpr::ObjCIvarRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCPropertyRefExpr::ObjCPropertyRefExpr(), clang::ObjCSubscriptRefExpr::ObjCSubscriptRefExpr(), clang::OMPArraySectionExpr::OMPArraySectionExpr(), clang::OpaqueValueExpr::OpaqueValueExpr(), clang::OverloadExpr::OverloadExpr(), clang::PackExpansionExpr::PackExpansionExpr(), clang::ParenExpr::ParenExpr(), clang::DeclRefExpr::setDecl(), clang::MemberExpr::setMemberDecl(), clang::ShuffleVectorExpr::ShuffleVectorExpr(), clang::StmtExpr::StmtExpr(), clang::SubstNonTypeTemplateParmExpr::SubstNonTypeTemplateParmExpr(), clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr(), clang::UnaryExprOrTypeTraitExpr::UnaryExprOrTypeTraitExpr(), clang::UnaryOperator::UnaryOperator(), and clang::VAArgExpr::VAArgExpr().
computeDependence() [41/79]
ExprDependence clang::computeDependence (GenericSelectionExpr * E, bool ContainsUnexpandedPack)
Definition at line 620 of file ComputeDependence.cpp.
References clang::GenericSelectionExpr::getAssocExprs(), clang::GenericSelectionExpr::getControllingExpr(), clang::Expr::getDependence(), clang::GenericSelectionExpr::getResultExpr(), and clang::GenericSelectionExpr::isResultDependent().
computeDependence() [42/79]
ExprDependence clang::computeDependence (ImplicitValueInitExpr * E)
Definition at line 228 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [43/79]
ExprDependence clang::computeDependence (InitListExpr * E)
Definition at line 606 of file ComputeDependence.cpp.
References clang::InitListExpr::inits().
computeDependence() [44/79]
ExprDependence clang::computeDependence (LambdaExpr * E, bool ContainsUnexpandedParameterPack)
Definition at line 747 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [45/79]
ExprDependence clang::computeDependence (MaterializeTemporaryExpr * E)
Definition at line 776 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::MaterializeTemporaryExpr::getSubExpr().
computeDependence() [46/79]
ExprDependence clang::computeDependence (MatrixSubscriptExpr * E)
Definition at line 116 of file ComputeDependence.cpp.
References clang::MatrixSubscriptExpr::getBase(), clang::MatrixSubscriptExpr::getColumnIdx(), clang::Expr::getDependence(), and clang::MatrixSubscriptExpr::getRowIdx().
computeDependence() [47/79]
ExprDependence clang::computeDependence (MemberExpr * E)
Definition at line 584 of file ComputeDependence.cpp.
References clang::MemberExpr::getBase(), clang::Expr::getDependence(), clang::MemberExpr::getMemberDecl(), clang::Expr::getType(), clang::CXXRecordDecl::isCurrentInstantiation(), clang::DeclContext::isDependentContext(), clang::Type::isDependentType(), and Type.
computeDependence() [48/79]
ExprDependence clang::computeDependence (MSPropertyRefExpr * E)
Definition at line 274 of file ComputeDependence.cpp.
References clang::MSPropertyRefExpr::getBaseExpr(), clang::Expr::getDependence(), and Type.
computeDependence() [49/79]
ExprDependence clang::computeDependence (MSPropertySubscriptExpr * E)
Definition at line 278 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::MSPropertySubscriptExpr::getIdx().
computeDependence() [50/79]
ExprDependence clang::computeDependence (NoInitExpr * E)
Definition at line 215 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [51/79]
ExprDependence clang::computeDependence (ObjCArrayLiteral * E)
Definition at line 814 of file ComputeDependence.cpp.
References clang::ObjCArrayLiteral::getElements(), clang::ObjCArrayLiteral::getNumElements(), N, and turnTypeToValueDependence().
computeDependence() [52/79]
ExprDependence clang::computeDependence (ObjCBoxedExpr * E)
Definition at line 364 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::ObjCBoxedExpr::getSubExpr().
computeDependence() [53/79]
ExprDependence clang::computeDependence (ObjCDictionaryLiteral * E)
Definition at line 822 of file ComputeDependence.cpp.
References clang::ObjCDictionaryLiteral::getKeyValueElement(), clang::ObjCDictionaryLiteral::getNumElements(), N, and turnTypeToValueDependence().
computeDependence() [54/79]
ExprDependence clang::computeDependence (ObjCEncodeExpr * E)
Definition at line 368 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::ObjCEncodeExpr::getEncodedType(), and toExprDependence().
computeDependence() [55/79]
ExprDependence clang::computeDependence (ObjCIndirectCopyRestoreExpr * E)
Definition at line 395 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::ObjCIndirectCopyRestoreExpr::getSubExpr().
computeDependence() [56/79]
ExprDependence clang::computeDependence (ObjCIsaExpr * E)
Definition at line 390 of file ComputeDependence.cpp.
References clang::ObjCIsaExpr::getBase(), and clang::Expr::getDependence().
computeDependence() [57/79]
ExprDependence clang::computeDependence (ObjCIvarRefExpr * E)
Definition at line 372 of file ComputeDependence.cpp.
References clang::ObjCIvarRefExpr::getBase(), clang::Expr::getDependence(), and turnTypeToValueDependence().
computeDependence() [58/79]
ExprDependence clang::computeDependence (ObjCMessageExpr * E)
Definition at line 835 of file ComputeDependence.cpp.
References clang::ObjCMessageExpr::arguments(), clang::Type::getDependence(), clang::ObjCMessageExpr::getInstanceReceiver(), clang::Expr::getType(), and toExprDependence().
computeDependence() [59/79]
ExprDependence clang::computeDependence (ObjCPropertyRefExpr * E)
Definition at line 376 of file ComputeDependence.cpp.
References clang::ObjCPropertyRefExpr::getBase(), clang::Expr::getDependence(), clang::Type::getDependence(), clang::ObjCPropertyRefExpr::getSuperReceiverType(), clang::ObjCPropertyRefExpr::isClassReceiver(), clang::ObjCPropertyRefExpr::isObjectReceiver(), clang::ObjCPropertyRefExpr::isSuperReceiver(), toExprDependence(), and Type.
computeDependence() [60/79]
ExprDependence clang::computeDependence (ObjCSubscriptRefExpr * E)
Definition at line 386 of file ComputeDependence.cpp.
References clang::ObjCSubscriptRefExpr::getBaseExpr(), clang::Expr::getDependence(), and clang::ObjCSubscriptRefExpr::getKeyExpr().
computeDependence() [61/79]
ExprDependence clang::computeDependence (OffsetOfExpr * E)
Definition at line 576 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::Type::getDependence(), clang::OffsetOfExpr::getIndexExpr(), clang::OffsetOfExpr::getNumExpressions(), clang::TypeSourceInfo::getType(), clang::OffsetOfExpr::getTypeSourceInfo(), N, toExprDependence(), and turnTypeToValueDependence().
computeDependence() [62/79]
ExprDependence clang::computeDependence (OMPArraySectionExpr * E)
Definition at line 399 of file ComputeDependence.cpp.
References clang::OMPArraySectionExpr::getBase(), clang::Expr::getDependence(), clang::OMPArraySectionExpr::getLength(), and clang::OMPArraySectionExpr::getLowerBound().
computeDependence() [63/79]
ExprDependence clang::computeDependence (OMPArrayShapingExpr * E)
Definition at line 408 of file ComputeDependence.cpp.
References clang::OMPArrayShapingExpr::getBase(), clang::Expr::getDependence(), clang::Type::getDependence(), clang::OMPArrayShapingExpr::getDimensions(), clang::Expr::getType(), and toExprDependence().
computeDependence() [64/79]
ExprDependence clang::computeDependence (OMPIteratorExpr * E)
Definition at line 417 of file ComputeDependence.cpp.
References clang::OMPIteratorExpr::IteratorRange::Begin, clang::OMPIteratorExpr::IteratorRange::End, clang::Type::getDependence(), clang::OMPIteratorExpr::getIteratorDecl(), clang::OMPIteratorExpr::getIteratorRange(), clang::Expr::getType(), clang::OMPIteratorExpr::numOfIterators(), clang::OMPIteratorExpr::IteratorRange::Step, and toExprDependence().
computeDependence() [65/79]
ExprDependence clang::computeDependence (OpaqueValueExpr * E)
Definition at line 28 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::OpaqueValueExpr::getSourceExpr(), clang::Expr::getType(), and toExprDependence().
computeDependence() [66/79]
ExprDependence clang::computeDependence (OverloadExpr * E, bool KnownDependent, bool KnownInstantiationDependent, bool KnownContainsUnexpandedParameterPack)
Definition at line 699 of file ComputeDependence.cpp.
References clang::OverloadExpr::decls(), getDependenceInExpr(), clang::OverloadExpr::getNameInfo(), clang::OverloadExpr::getQualifier(), clang::OverloadExpr::template_arguments(), and toExprDependence().
computeDependence() [67/79]
ExprDependence clang::computeDependence (PackExpansionExpr * E)
Definition at line 341 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::PackExpansionExpr::getPattern().
computeDependence() [68/79]
ExprDependence clang::computeDependence (ParenExpr * E)
Definition at line 36 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::ParenExpr::getSubExpr().
computeDependence() [69/79]
ExprDependence clang::computeDependence (ParenListExpr * E)
Definition at line 201 of file ComputeDependence.cpp.
References P.
computeDependence() [70/79]
ExprDependence clang::computeDependence (PredefinedExpr * E)
Definition at line 559 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), and toExprDependence().
computeDependence() [71/79]
ExprDependence clang::computeDependence (PseudoObjectExpr * E)
Definition at line 650 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), clang::PseudoObjectExpr::getSyntacticForm(), and clang::PseudoObjectExpr::semantics().
computeDependence() [72/79]
ExprDependence clang::computeDependence (RecoveryExpr * E)
Definition at line 543 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::Expr::getType(), clang::RecoveryExpr::subExpressions(), and toExprDependence().
computeDependence() [73/79]
ExprDependence clang::computeDependence (ShuffleVectorExpr * E)
Definition at line 613 of file ComputeDependence.cpp.
References C, clang::Type::getDependence(), clang::ShuffleVectorExpr::getNumSubExprs(), clang::ShuffleVectorExpr::getSubExprs(), clang::Expr::getType(), and toExprDependence().
computeDependence() [74/79]
ExprDependence clang::computeDependence (StmtExpr * E, unsigned TemplateDepth)
Definition at line 160 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::ValueStmt::getExprStmt(), clang::CompoundStmt::getStmtExprResult(), clang::StmtExpr::getSubStmt(), clang::Expr::getType(), and toExprDependence().
computeDependence() [75/79]
ExprDependence clang::computeDependence (SubstNonTypeTemplateParmExpr * E)
Definition at line 346 of file ComputeDependence.cpp.
References clang::Expr::getDependence(), and clang::SubstNonTypeTemplateParmExpr::getReplacement().
computeDependence() [76/79]
ExprDependence clang::computeDependence (TypeTraitExpr * E)
Definition at line 789 of file ComputeDependence.cpp.
References clang::TypeTraitExpr::getArgs(), toExprDependence(), and Type.
computeDependence() [77/79]
ExprDependence clang::computeDependence (UnaryExprOrTypeTraitExpr * E)
Definition at line 75 of file ComputeDependence.cpp.
References clang::UnaryExprOrTypeTraitExpr::getArgumentExpr(), clang::UnaryExprOrTypeTraitExpr::getArgumentType(), clang::Expr::getDependence(), clang::Type::getDependence(), clang::UnaryExprOrTypeTraitExpr::getKind(), clang::Expr::IgnoreParens(), clang::UnaryExprOrTypeTraitExpr::isArgumentType(), clang::Decl::specific_attrs(), toExprDependence(), and turnTypeToValueDependence().
computeDependence() [78/79]
ExprDependence clang::computeDependence (UnaryOperator * E, const ASTContext & Ctx)
Definition at line 40 of file ComputeDependence.cpp.
References Diag(), clang::Expr::EvaluateAsConstantExpr(), clang::Expr::getDependence(), clang::Type::getDependence(), clang::ASTContext::getLangOpts(), clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), Result, and toExprDependence().
computeDependence() [79/79]
ExprDependence clang::computeDependence (VAArgExpr * E)
Definition at line 208 of file ComputeDependence.cpp.
References clang::Type::getDependence(), clang::VAArgExpr::getSubExpr(), clang::TypeSourceInfo::getType(), clang::VAArgExpr::getWrittenTypeInfo(), and toExprDependence().
ComputePreambleBounds()
PreambleBounds clang::ComputePreambleBounds (const LangOptions & LangOpts, const llvm::MemoryBufferRef & Buffer, unsigned MaxLines)
Runs lexer to compute suggested preamble bounds.
Definition at line 305 of file PrecompiledPreamble.cpp.
References clang::Lexer::ComputePreamble().
Referenced by clang::PrecompiledPreamble::OverridePreamble().
CreateASTDeclNodeLister()
std::unique_ptr< ASTConsumer > clang::CreateASTDeclNodeLister ()
Definition at line 175 of file ASTConsumers.cpp.
Referenced by clang::ASTDeclListAction::CreateASTConsumer().
CreateASTDumper()
std::unique_ptr< ASTConsumer > clang::CreateASTDumper (std::unique_ptr< raw_ostream > OS, StringRef FilterString, bool DumpDecls, bool Deserialize, bool DumpLookups, bool DumpDeclTypes, ASTDumpOutputFormat Format)
Definition at line 164 of file ASTConsumers.cpp.
Referenced by clang::ASTDumpAction::CreateASTConsumer().
CreateASTPrinter()
std::unique_ptr< ASTConsumer > clang::CreateASTPrinter (std::unique_ptr< raw_ostream > OS, StringRef FilterString)
Definition at line 157 of file ASTConsumers.cpp.
References ADOF_Default.
Referenced by clang::ASTPrintAction::CreateASTConsumer().
CreateASTViewer()
std::unique_ptr< ASTConsumer > clang::CreateASTViewer ()
Definition at line 212 of file ASTConsumers.cpp.
Referenced by clang::ASTViewAction::CreateASTConsumer().
createChainedIncludesSource()
IntrusiveRefCntPtr< ExternalSemaSource > clang::createChainedIncludesSource (CompilerInstance & CI, IntrusiveRefCntPtr< ExternalSemaSource > & Reader)
The ChainedIncludesSource class converts headers to chained PCHs in memory, mainly for testing.
Definition at line 113 of file ChainedIncludesSource.cpp.
References clang::PreprocessorOptions::ChainedIncludes, createASTReader(), clang::TargetInfo::CreateTargetInfo(), clang::Preprocessor::getBuiltinInfo(), clang::CompilerInstance::getDiagnosticOpts(), clang::CompilerInstance::getFrontendOpts(), clang::Preprocessor::getIdentifierTable(), clang::CompilerInstance::getInvocation(), clang::Preprocessor::getLangOpts(), clang::CompilerInstance::getPCHContainerOperations(), clang::CompilerInstance::getPreprocessorOpts(), clang::Builtin::Context::initializeBuiltins(), clang::FrontendOptions::Inputs, ParseAST(), and TU_Prefix.
Referenced by clang::FrontendAction::BeginSourceFile().
CreateFrontendAction()
std::unique_ptr< FrontendAction > clang::CreateFrontendAction (CompilerInstance & CI)
Construct the FrontendAction of a compiler invocation based on the options specified for the compiler invocation.
Returns
- The created FrontendAction object
Definition at line 137 of file ExecuteCompilerInvocation.cpp.
References clang::FrontendOptions::ARCMT_Check, clang::FrontendOptions::ARCMT_Migrate, clang::FrontendOptions::ARCMT_Modify, clang::FrontendOptions::ARCMT_None, clang::FrontendOptions::ARCMTAction, clang::FrontendOptions::ARCMTMigrateEmitARCErrors, clang::FrontendOptions::ARCMTMigrateReportOut, clang::FrontendOptions::ASTMergeFiles, CreateFrontendBaseAction(), clang::FrontendOptions::FixAndRecompile, clang::frontend::GeneratePCH, clang::CompilerInstance::getFrontendOpts(), clang::frontend::MigrateSource, clang::FrontendOptions::MTMigrateDir, clang::FrontendOptions::ObjCMT_None, clang::FrontendOptions::ObjCMTAction, and clang::FrontendOptions::ProgramAction.
Referenced by ExecuteCompilerInvocation().
CreateFrontendBaseAction()
static std::unique_ptr< FrontendAction > clang::CreateFrontendBaseAction (CompilerInstance & CI) static
Definition at line 39 of file ExecuteCompilerInvocation.cpp.
References clang::FrontendOptions::ActionName, clang::PluginASTAction::Cmdline, clang::CompilerInstance::getDiagnostics(), clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getPreprocessorOutputOpts(), P, clang::FrontendOptions::PluginArgs, clang::FrontendOptions::ProgramAction, clang::PluginASTAction::ReplaceAction, clang::DiagnosticsEngine::Report(), clang::PreprocessorOutputOptions::RewriteImports, and clang::PreprocessorOutputOptions::RewriteIncludes.
Referenced by CreateFrontendAction().
CreateHTMLPrinter()
std::unique_ptr< ASTConsumer > clang::CreateHTMLPrinter (std::unique_ptr< raw_ostream > OS, Preprocessor & PP, bool SyntaxHighlight = true, bool HighlightMacros = true)
CreateHTMLPrinter - Create an AST consumer which rewrites source code to HTML with syntax highlighting suitable for viewing in a web-browser.
Definition at line 49 of file HTMLPrint.cpp.
Referenced by clang::HTMLPrintAction::CreateASTConsumer().
createInvocationFromCommandLine()
std::unique_ptr< CompilerInvocation > clang::createInvocationFromCommandLine (ArrayRef< const char * > Args, IntrusiveRefCntPtr< DiagnosticsEngine > Diags = IntrusiveRefCntPtr<DiagnosticsEngine>(), IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS = nullptr, bool ShouldRecoverOnErrors = false, std::vector< std::string > * CC1Args = nullptr)
createInvocationFromCommandLine - Construct a compiler invocation object for a command line argument vector.
Parameters
ShouldRecoverOnErrors - whether we should attempt to return a non-null (and possibly incorrect) CompilerInvocation if any errors were encountered. When this flag is false, always return null on errors.
CC1Args - if non-null, will be populated with the args to cc1 expanded from Args. May be set even if nullptr is returned.
Returns
A CompilerInvocation, or nullptr if none was built for the given argument vector.
Definition at line 27 of file CreateInvocationFromCommandLine.cpp.
References clang::driver::JobList::begin(), clang::driver::Driver::BuildCompilation(), C, cast(), Cmd, clang::CompilerInstance::createDiagnostics(), clang::CompilerInvocation::CreateFromArgs(), clang::driver::JobList::getJobs(), clang::driver::JobList::Print(), clang::driver::Driver::setCheckInputsExist(), and clang::driver::JobList::size().
Referenced by clang::ASTUnit::LoadFromCommandLine().
CreateItaniumCXXABI()
CXXABI * clang::CreateItaniumCXXABI (ASTContext & Ctx)
Creates an instance of a C++ ABI class.
Definition at line 258 of file ItaniumCXXABI.cpp.
Referenced by createCXXABI().
createItaniumNumberingContext()
std::unique_ptr< MangleNumberingContext > clang::createItaniumNumberingContext (MangleContext * Mangler)
Definition at line 263 of file ItaniumCXXABI.cpp.
CreateLLVMCodeGen()
CodeGenerator * clang::CreateLLVMCodeGen (DiagnosticsEngine & Diags, llvm::StringRef ModuleName, const HeaderSearchOptions & HeaderSearchOpts, const PreprocessorOptions & PreprocessorOpts, const CodeGenOptions & CGO, llvm::LLVMContext & C, CoverageSourceInfo * CoverageInfo = nullptr)
CreateLLVMCodeGen - Create a CodeGenerator instance.
It is the responsibility of the caller to call delete on the allocated CodeGenerator instance.
Definition at line 339 of file ModuleBuilder.cpp.
References C.
CreateMicrosoftCXXABI()
CXXABI * clang::CreateMicrosoftCXXABI (ASTContext & Ctx)
Definition at line 296 of file MicrosoftCXXABI.cpp.
Referenced by createCXXABI().
CreateModernObjCRewriter()
std::unique_ptr< ASTConsumer > clang::CreateModernObjCRewriter (const std::string & InFile, std::unique_ptr< raw_ostream > OS, DiagnosticsEngine & Diags, const LangOptions & LOpts, bool SilenceRewriteMacroWarning, bool LineInfo)
CreateObjCRewriter()
std::unique_ptr< ASTConsumer > clang::CreateObjCRewriter (const std::string & InFile, std::unique_ptr< raw_ostream > OS, DiagnosticsEngine & Diags, const LangOptions & LOpts, bool SilenceRewriteMacroWarning)
createVFSFromCompilerInvocation() [1/2]
IntrusiveRefCntPtr< llvm::vfs::FileSystem > clang::createVFSFromCompilerInvocation (const CompilerInvocation & CI, DiagnosticsEngine & Diags)
Definition at line 3135 of file CompilerInvocation.cpp.
References createVFSFromCompilerInvocation().
Referenced by clang::PrecompiledPreamble::Build(), clang::ASTUnit::create(), clang::CompilerInstance::createFileManager(), createVFSFromCompilerInvocation(), and clang::ASTUnit::LoadFromCommandLine().
createVFSFromCompilerInvocation() [2/2]
IntrusiveRefCntPtr< llvm::vfs::FileSystem > clang::createVFSFromCompilerInvocation (const CompilerInvocation & CI, DiagnosticsEngine & Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > BaseFS)
Definition at line 3142 of file CompilerInvocation.cpp.
References File, clang::CompilerInvocationBase::getHeaderSearchOpts(), clang::DiagnosticsEngine::Report(), Result, and clang::HeaderSearchOptions::VFSOverlayFiles.
CudaArchToString()
const char * clang::CudaArchToString (CudaArch A)
Definition at line 109 of file Cuda.cpp.
References clang::CudaArchToStringMap::arch, and arch_names.
Referenced by clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::CudaInstallationDetector::CudaInstallationDetector(), clang::targets::NVPTXTargetInfo::fillValidCPUList(), clang::targets::NVPTXTargetInfo::initFeatureMap(), and clang::CodeGen::CGOpenMPRuntimeGPU::processRequiresDirective().
CudaArchToVirtualArchString()
const char * clang::CudaArchToVirtualArchString (CudaArch A)
Definition at line 118 of file Cuda.cpp.
References clang::CudaArchToStringMap::arch, and arch_names.
Referenced by clang::driver::tools::NVPTX::Linker::ConstructJob().
CudaFeatureEnabled() [1/2]
bool clang::CudaFeatureEnabled (CudaVersion Version, CudaFeature Feature)
Definition at line 221 of file Cuda.cpp.
References CUDA_101, CUDA_92, CUDA_USES_FATBIN_REGISTER_END, and CUDA_USES_NEW_LAUNCH.
CudaFeatureEnabled() [2/2]
bool clang::CudaFeatureEnabled (llvm::VersionTuple Version, CudaFeature Feature)
Definition at line 217 of file Cuda.cpp.
References CudaFeatureEnabled(), and ToCudaVersion().
Referenced by CudaFeatureEnabled(), and clang::Sema::getCudaConfigureFuncName().
CudaStringToVersion()
CudaVersion clang::CudaStringToVersion (const llvm::Twine & S)
Definition at line 39 of file Cuda.cpp.
References CUDA_100, CUDA_101, CUDA_102, CUDA_110, CUDA_70, CUDA_75, CUDA_80, CUDA_90, CUDA_91, CUDA_92, and UNKNOWN.
CudaVersionToString()
const char * clang::CudaVersionToString (CudaVersion V)
Definition at line 11 of file Cuda.cpp.
References CUDA_100, CUDA_101, CUDA_102, CUDA_110, CUDA_70, CUDA_75, CUDA_80, CUDA_90, CUDA_91, CUDA_92, UNKNOWN, and V.
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch(), clang::driver::tools::Clang::ConstructJob(), clang::driver::CudaInstallationDetector::print(), and clang::driver::CudaInstallationDetector::WarnIfUnsupportedVersion().
declaresSameEntity()
bool clang::declaresSameEntity (const Decl * D1, const Decl * D2) inline
Determine whether two declarations declare the same entity.
Definition at line 1198 of file DeclBase.h.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::ActOnPropertyImplDecl(), clang::Sema::ActOnStartClassImplementation(), clang::Sema::ActOnSuperClassOfClassInterface(), allLookupResultsAreTheSame(), clang::ASTContext::areCommonBaseCompatible(), clang::Sema::BuildCXXConstructExpr(), clang::ASTContext::canAssignObjCInterfaces(), clang::Sema::CheckDestructor(), clang::Sema::CheckForFunctionRedefinition(), CheckRelatedResultTypeCompatibility(), clang::Sema::CheckTypenameType(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::DiagnoseUnexpandedParameterPacks(), EmitObjectDelete(), clang::Sema::findInheritingConstructor(), clang::CXXMethodDecl::getCorrespondingMethodInClass(), clang::Sema::getTypeName(), HandleConstructorCall(), HandleDynamicCast(), HandleUnionActiveMemberChange(), haveSameParameterTypes(), clang::ASTNodeImporter::ImportDefinition(), isBaseClassPublic(), isInstantiationOf(), isInstantiationOf(), isInstantiationOf(), isInstantiationOfUnresolvedUsingDecl(), isOrIsDerivedFromSpecializationOf(), isRelevantAttr(), clang::Expr::isSameComparisonOperand(), isSameEntity(), clang::Sema::IsSimplyAccessible(), clang::ObjCInterfaceDecl::isSuperClassOf(), isZeroInitialized(), clang::ASTContext::lookupFieldBitOffset(), clang::Sema::LookupIvarInObjCMethod(), LookupMemberExpr(), clang::ASTContext::ProtocolCompatibleWithProtocol(), and clang::ASTNodeImporter::VisitObjCImplementationDecl().
DeclAttrsMatchCUDAMode()
bool clang::DeclAttrsMatchCUDAMode (const LangOptions & LangOpts, Decl * D) inline
Definition at line 44 of file SemaInternal.h.
References clang::Decl::hasAttr().
Referenced by clang::Sema::ActOnVariableDeclarator().
DEF_TRAVERSE_TYPE() [1/21]
clang::DEF_TRAVERSE_TYPE (AdjustedType , { TRY_TO(TraverseType(T->getOriginalType()));})
DEF_TRAVERSE_TYPE() [2/21]
clang::DEF_TRAVERSE_TYPE (AttributedType , { TRY_TO(TraverseType(T->getModifiedType()));})
DEF_TRAVERSE_TYPE() [3/21]
clang::DEF_TRAVERSE_TYPE (BlockPointerType , { TRY_TO(TraverseType(T->getPointeeType()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [4/21]
clang::DEF_TRAVERSE_TYPE (ComplexType , { TRY_TO(TraverseType(T->getElementType()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [5/21]
clang::DEF_TRAVERSE_TYPE (ConstantArrayType , { TRY_TO(TraverseType(T->getElementType()));if(T->getSizeExpr()) TRY_TO(TraverseStmt(const_cast< Expr * >(T->getSizeExpr())));})
DEF_TRAVERSE_TYPE() [6/21]
clang::DEF_TRAVERSE_TYPE (DeducedTemplateSpecializationType , { TRY_TO(TraverseTemplateName(T->getTemplateName()));TRY_TO(TraverseType(T->getDeducedType()));})
DEF_TRAVERSE_TYPE() [7/21]
clang::DEF_TRAVERSE_TYPE (DependentAddressSpaceType , { TRY_TO(TraverseStmt(T->getAddrSpaceExpr()));TRY_TO(TraverseType(T->getPointeeType()));})
DEF_TRAVERSE_TYPE() [8/21]
clang::DEF_TRAVERSE_TYPE (DependentNameType , { TRY_TO(TraverseNestedNameSpecifier(T->getQualifier()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [9/21]
clang::DEF_TRAVERSE_TYPE (DependentSizedExtVectorType , { if(T->getSizeExpr()) TRY_TO(TraverseStmt(T->getSizeExpr()));TRY_TO(TraverseType(T->getElementType()));})
DEF_TRAVERSE_TYPE() [10/21]
clang::DEF_TRAVERSE_TYPE (DependentSizedMatrixType , { if(T->getRowExpr()) TRY_TO(TraverseStmt(T->getRowExpr()));if(T->getColumnExpr()) TRY_TO(TraverseStmt(T->getColumnExpr()));TRY_TO(TraverseType(T->getElementType()));})
DEF_TRAVERSE_TYPE() [11/21]
clang::DEF_TRAVERSE_TYPE (ExtVectorType , { TRY_TO(TraverseType(T->getElementType()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [12/21]
clang::DEF_TRAVERSE_TYPE (FunctionProtoType , { TRY_TO(TraverseType(T->getReturnType()));for(const auto &A :T->param_types()) { TRY_TO(TraverseType(A));} for(const auto &E :T->exceptions()) { TRY_TO(TraverseType(E));} if(Expr *NE=T->getNoexceptExpr()) TRY_TO(TraverseStmt(NE));})
DEF_TRAVERSE_TYPE() [13/21]
clang::DEF_TRAVERSE_TYPE (MacroQualifiedType , { TRY_TO(TraverseType(T->getUnderlyingType()));})
DEF_TRAVERSE_TYPE() [14/21]
clang::DEF_TRAVERSE_TYPE (ObjCObjectPointerType , { TRY_TO(TraverseType(T->getPointeeType()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [15/21]
clang::DEF_TRAVERSE_TYPE (PackExpansionType , { TRY_TO(TraverseType(T->getPattern()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [16/21]
clang::DEF_TRAVERSE_TYPE (PipeType , { TRY_TO(TraverseType(T->getElementType()));})
References TRY_TO.
DEF_TRAVERSE_TYPE() [17/21]
clang::DEF_TRAVERSE_TYPE (RValueReferenceType , { TRY_TO(TraverseType(T->getPointeeType()));})
DEF_TRAVERSE_TYPE() [18/21]
clang::DEF_TRAVERSE_TYPE (SubstTemplateTypeParmPackType , { TRY_TO(TraverseTemplateArgument(T->getArgumentPack()));})
DEF_TRAVERSE_TYPE() [19/21]
clang::DEF_TRAVERSE_TYPE (TypeOfType , { TRY_TO(TraverseType(T->getUnderlyingType()));})
DEF_TRAVERSE_TYPE() [20/21]
clang::DEF_TRAVERSE_TYPE (UnaryTransformType , { TRY_TO(TraverseType(T->getBaseType()));TRY_TO(TraverseType(T->getUnderlyingType()));})
DEF_TRAVERSE_TYPE() [21/21]
clang::DEF_TRAVERSE_TYPE (VariableArrayType , { TRY_TO(TraverseType(T->getElementType()));TRY_TO(TraverseStmt(T->getSizeExpr()));})
DEF_TRAVERSE_TYPELOC() [1/18]
clang::DEF_TRAVERSE_TYPELOC (AdjustedType , { TRY_TO(TraverseTypeLoc(TL.getOriginalLoc()));})
DEF_TRAVERSE_TYPELOC() [2/18]
clang::DEF_TRAVERSE_TYPELOC (AttributedType , { TRY_TO(TraverseTypeLoc(TL.getModifiedLoc()));})
DEF_TRAVERSE_TYPELOC() [3/18]
clang::DEF_TRAVERSE_TYPELOC (BlockPointerType , { TRY_TO(TraverseTypeLoc(TL.getPointeeLoc()));})
References TRY_TO.
DEF_TRAVERSE_TYPELOC() [4/18]
clang::DEF_TRAVERSE_TYPELOC (ComplexType , { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));})
DEF_TRAVERSE_TYPELOC() [5/18]
clang::DEF_TRAVERSE_TYPELOC (ConstantArrayType , { TRY_TO(TraverseTypeLoc(TL.getElementLoc()));TRY_TO(TraverseArrayTypeLocHelper(TL));})
References clang::ArrayTypeLoc::getElementLoc(), and TRY_TO.
DEF_TRAVERSE_TYPELOC() [6/18]
clang::DEF_TRAVERSE_TYPELOC (DeducedTemplateSpecializationType , { TRY_TO(TraverseTemplateName(TL.getTypePtr() ->getTemplateName()));TRY_TO(TraverseType(TL.getTypePtr() ->getDeducedType()));})
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and TRY_TO.
DEF_TRAVERSE_TYPELOC() [7/18]
clang::DEF_TRAVERSE_TYPELOC (DependentAddressSpaceType , { TRY_TO(TraverseStmt(TL.getTypePtr() ->getAddrSpaceExpr()));TRY_TO(TraverseType(TL.getTypePtr() ->getPointeeType()));})
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr(), and TRY_TO.
DEF_TRAVERSE_TYPELOC() [8/18]
clang::DEF_TRAVERSE_TYPELOC (DependentNameType , { TRY_TO(TraverseNestedNameSpecifierLoc(TL.getQualifierLoc()));})
References TRY_TO.
DEF_TRAVERSE_TYPELOC() [9/18]
clang::DEF_TRAVERSE_TYPELOC (DependentSizedMatrixType , { TRY_TO(TraverseStmt(TL.getAttrRowOperand()));TRY_TO(TraverseStmt(TL.getAttrColumnOperand()));TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));})
References TRY_TO.
DEF_TRAVERSE_TYPELOC() [10/18]
clang::DEF_TRAVERSE_TYPELOC (ExtVectorType , { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));})
DEF_TRAVERSE_TYPELOC() [11/18]
clang::DEF_TRAVERSE_TYPELOC (FunctionProtoType , { TRY_TO(TraverseTypeLoc(TL.getReturnLoc()));const FunctionProtoType *T=TL.getTypePtr();for(unsigned I=0, E=TL.getNumParams();I !=E;++I) { if(TL.getParam(I)) { TRY_TO(TraverseDecl(TL.getParam(I)));} else if(I< T->getNumParams()) { TRY_TO(TraverseType(T->getParamType(I)));} } for(const auto &E :T->exceptions()) { TRY_TO(TraverseType(E));} if(Expr *NE=T->getNoexceptExpr()) TRY_TO(TraverseStmt(NE));})
DEF_TRAVERSE_TYPELOC() [12/18]
clang::DEF_TRAVERSE_TYPELOC (ParenType , { TRY_TO(TraverseTypeLoc(TL.getInnerLoc()));})
References TRY_TO.
DEF_TRAVERSE_TYPELOC() [13/18]
clang::DEF_TRAVERSE_TYPELOC (RValueReferenceType , { TRY_TO(TraverseTypeLoc(TL.getPointeeLoc()));})
DEF_TRAVERSE_TYPELOC() [14/18]
clang::DEF_TRAVERSE_TYPELOC (SubstTemplateTypeParmPackType , { TRY_TO(TraverseTemplateArgument(TL.getTypePtr() ->getArgumentPack()));})
DEF_TRAVERSE_TYPELOC() [15/18]
clang::DEF_TRAVERSE_TYPELOC (TypeOfType , { TRY_TO(TraverseTypeLoc(TL.getUnderlyingTInfo() ->getTypeLoc()));})
DEF_TRAVERSE_TYPELOC() [16/18]
clang::DEF_TRAVERSE_TYPELOC (UnaryTransformType , { TRY_TO(TraverseTypeLoc(TL.getUnderlyingTInfo() ->getTypeLoc()));})
DEF_TRAVERSE_TYPELOC() [17/18]
clang::DEF_TRAVERSE_TYPELOC (VariableArrayType , { TRY_TO(TraverseTypeLoc(TL.getElementLoc()));TRY_TO(TraverseArrayTypeLocHelper(TL));})
DEF_TRAVERSE_TYPELOC() [18/18]
clang::DEF_TRAVERSE_TYPELOC (VectorType , { TRY_TO(TraverseType(TL.getTypePtr() ->getElementType()));})
DoPrintPreprocessedInput()
void clang::DoPrintPreprocessedInput (Preprocessor & PP, raw_ostream * OS, const PreprocessorOutputOptions & Opts)
DoPrintPreprocessedInput - Implement -E mode.
DoPrintPreprocessedInput - This implements -E mode.
Definition at line 858 of file PrintPreprocessedOutput.cpp.
References clang::Preprocessor::addPPCallbacks(), clang::Preprocessor::AddPragmaHandler(), DoPrintMacros(), clang::Preprocessor::EnterMainSourceFile(), clang::PresumedLoc::getFilename(), clang::Preprocessor::getLangOpts(), clang::Token::getLocation(), clang::Preprocessor::getSourceManager(), clang::Token::is(), clang::SourceLocation::isFileID(), clang::PresumedLoc::isInvalid(), clang::Preprocessor::Lex(), PrintPreprocessedTokens(), clang::Preprocessor::RemovePragmaHandler(), clang::Preprocessor::SetCommentRetentionState(), clang::PreprocessorOutputOptions::ShowComments, clang::PreprocessorOutputOptions::ShowCPP, clang::PreprocessorOutputOptions::ShowIncludeDirectives, clang::PreprocessorOutputOptions::ShowLineMarkers, clang::PreprocessorOutputOptions::ShowMacroComments, clang::PreprocessorOutputOptions::ShowMacros, Tok, and clang::PreprocessorOutputOptions::UseLineDirectives.
Referenced by clang::PrintPreprocessedAction::ExecuteAction().
DoRewriteTest()
void clang::DoRewriteTest (Preprocessor & PP, raw_ostream * OS)
DoRewriteTest - A simple test for the TokenRewriter class.
Definition at line 18 of file RewriteTest.cpp.
References clang::Preprocessor::getLangOpts(), clang::Preprocessor::getSourceManager(), clang::Preprocessor::getSpelling(), and SM.
Referenced by clang::RewriteTestAction::ExecuteAction().
EmbedBitcode()
void clang::EmbedBitcode (llvm::Module * M, const CodeGenOptions & CGOpts, llvm::MemoryBufferRef Buf)
Definition at line 1615 of file BackendUtil.cpp.
References clang::CodeGenOptions::CmdArgs, clang::CodeGenOptions::Embed_Bitcode, clang::CodeGenOptions::Embed_Marker, and clang::CodeGenOptions::Embed_Off.
Referenced by clang::CodeGenAction::ExecuteAction(), and clang::BackendConsumer::HandleTranslationUnit().
EmitBackendOutput()
void clang::EmitBackendOutput (DiagnosticsEngine & Diags, const HeaderSearchOptions & , const CodeGenOptions & CGOpts, const TargetOptions & TOpts, const LangOptions & LOpts, const llvm::DataLayout & TDesc, llvm::Module * M, BackendAction Action, std::unique_ptr< raw_pwrite_stream > OS)
Referenced by clang::CodeGenAction::ExecuteAction(), and clang::BackendConsumer::HandleTranslationUnit().
exceptionSpecNotKnownYet()
static bool clang::exceptionSpecNotKnownYet (const FunctionDecl * FD) static
Definition at line 247 of file SemaExceptionSpec.cpp.
References EST_Unevaluated, and EST_Unparsed.
Referenced by clang::Sema::CheckEquivalentExceptionSpec(), and clang::Sema::CheckOverridingFunctionExceptionSpec().
ExecuteCompilerInvocation()
bool clang::ExecuteCompilerInvocation (CompilerInstance * Clang)
ExecuteCompilerInvocation - Execute the given actions described by the compiler invocation object in the given compiler instance.
Returns
- True on success.
Definition at line 187 of file ExecuteCompilerInvocation.cpp.
References clang::FrontendOptions::ActionName, clang::driver::options::CC1Option, CreateFrontendAction(), clang::FrontendOptions::DisableFree, Error, clang::CompilerInstance::ExecuteAction(), clang::CompilerInstance::getAnalyzerOpts(), clang::CompilerInstance::getDiagnostics(), clang::driver::getDriverOptTable(), clang::CompilerInstance::getFrontendOpts(), clang::DiagnosticsEngine::hasErrorOccurred(), clang::FrontendOptions::LLVMArgs, P, clang::frontend::PluginAction, clang::FrontendOptions::Plugins, clang::ento::printAnalyzerConfigList(), clang::ento::printCheckerConfigList(), clang::ento::printCheckerHelp(), clang::ento::printEnabledCheckerList(), clang::FrontendOptions::ProgramAction, clang::PluginASTAction::ReplaceAction, clang::DiagnosticsEngine::Report(), clang::AnalyzerOptions::ShowCheckerHelp, clang::AnalyzerOptions::ShowCheckerHelpAlpha, clang::AnalyzerOptions::ShowCheckerHelpDeveloper, clang::AnalyzerOptions::ShowCheckerOptionAlphaList, clang::AnalyzerOptions::ShowCheckerOptionDeveloperList, clang::AnalyzerOptions::ShowCheckerOptionList, clang::AnalyzerOptions::ShowConfigOptionsList, clang::AnalyzerOptions::ShowEnabledCheckerList, clang::FrontendOptions::ShowHelp, and clang::FrontendOptions::ShowVersion.
expandSanitizerGroups()
SanitizerMask clang::expandSanitizerGroups (SanitizerMask Kinds)
For each sanitizer group bit set in Kinds, set the bits for sanitizers this group enables.
Definition at line 37 of file Sanitizers.cpp.
Referenced by describeSanitizeArg(), lastArgumentForMask(), parseSanitizeTrapArgs(), and clang::driver::SanitizerArgs::SanitizerArgs().
expandUCNs()
void clang::expandUCNs (SmallVectorImpl< char > & Buf, StringRef Input)
Copy characters from Input to Buf, expanding any UCNs.
Definition at line 240 of file LiteralSupport.cpp.
References appendCodePoint().
Referenced by clang::CharLiteralParser::CharLiteralParser(), clang::Preprocessor::LookUpIdentifierInfo(), and clang::NumericLiteralParser::NumericLiteralParser().
ExprEmpty()
ExprResult clang::ExprEmpty () inline
Definition at line 289 of file Ownership.h.
Referenced by clang::Sema::buildCoroutinePromise(), buildDeclareReductionRef(), clang::Sema::BuildQualifiedDeclarationNameExpr(), buildUserDefinedMapperRef(), calculateConstraintSatisfaction(), instantiateOMPDeclareSimdDeclAttr(), rebuildPotentialResultsAsNonOdrUsed(), and clang::TreeTransform< Derived >::TransformInitializer().
ExprError() [1/2]
ExprResult clang::ExprError () inline
Definition at line 278 of file Ownership.h.
Referenced by clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnAsTypeExpr(), clang::Sema::ActOnBuiltinBitCastExpr(), clang::Sema::ActOnBuiltinOffsetOf(), clang::Sema::ActOnCaseExpr(), clang::Sema::ActOnCastExpr(), clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnClassMessage(), clang::Sema::ActOnClassPropertyRefExpr(), clang::Sema::ActOnCoawaitExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnCoyieldExpr(), clang::Sema::ActOnCUDAExecConfigExpr(), clang::Sema::ActOnCXXDelete(), clang::Sema::ActOnCXXFoldExpr(), clang::Sema::ActOnCXXNamedCast(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnCXXTypeConstructExpr(), clang::Sema::ActOnCXXTypeid(), clang::Sema::ActOnCXXUuidof(), clang::Sema::ActOnDecltypeExpression(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnDesignatedInitializer(), clang::Sema::ActOnExpressionTrait(), clang::Sema::ActOnFinishFullExpr(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnInstanceMessage(), clang::Sema::ActOnMemberAccessExpr(), clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnObjCAtSynchronizedOperand(), clang::Sema::ActOnOMPArraySectionExpr(), clang::Sema::ActOnOMPArrayShapingExpr(), clang::Sema::ActOnOMPIteratorExpr(), clang::Sema::ActOnOpenMPIdExpression(), clang::Sema::ActOnPostfixUnaryOp(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnPseudoDestructorExpr(), clang::Sema::ActOnRequiresClause(), clang::Sema::ActOnRequiresExpr(), clang::Sema::ActOnSizeofParameterPackExpr(), clang::Sema::ActOnStartCXXMemberReference(), clang::Sema::ActOnStmtExprResult(), clang::Sema::ActOnStringLiteral(), clang::Sema::ActOnSuperMessage(), clang::Sema::ActOnUnaryExprOrTypeTraitExpr(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildAnonymousStructUnionMemberReference(), clang::Sema::BuildAtomicExpr(), clang::Sema::BuildBinOp(), clang::Sema::BuildBlockForLambdaConversion(), clang::Sema::BuildBuiltinBitCastExpr(), clang::Sema::BuildBuiltinOffsetOf(), clang::Sema::BuildCallExpr(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildCallToObjectOfClassType(), buildCapture(), clang::Sema::BuildCaptureInit(), clang::Sema::BuildClassMessage(), clang::Sema::BuildCompoundLiteralExpr(), BuildCookedLiteralOperatorCall(), buildCoroutineHandle(), buildCounterInit(), buildCounterUpdate(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildCStyleCastExpr(), BuildCXXCastArgument(), clang::Sema::BuildCXXConstructExpr(), clang::Sema::BuildCXXConstructExpr(), clang::Sema::BuildCXXDefaultArgExpr(), clang::Sema::BuildCXXDefaultInitExpr(), clang::Sema::BuildCXXFunctionalCastExpr(), clang::Sema::BuildCXXMemberCallExpr(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXNew(), clang::Sema::BuildCXXNoexceptExpr(), clang::Sema::BuildCXXThrow(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildCXXTypeId(), clang::Sema::BuildCXXUuidof(), clang::Sema::BuildCXXUuidof(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildDeclarationNameExpr(), buildDeclareReductionRef(), clang::Sema::BuildDependentDeclRefExpr(), clang::Sema::BuildExpressionFromDeclTemplateArgument(), clang::Sema::BuildExpressionTrait(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildForRangeBeginEndCall(), clang::Sema::BuildInstanceMessage(), clang::Sema::BuildIvarRefExpr(), clang::Sema::BuildLambdaExpr(), clang::Sema::BuildLiteralOperatorCall(), buildMemberCall(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::BuildObjCDictionaryLiteral(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildObjCSubscriptExpression(), buildOperatorCoawaitCall(), clang::Sema::BuildOverloadedArrowExpr(), clang::Sema::buildOverloadedCallSet(), clang::Sema::BuildPossibleImplicitMemberExpr(), buildPromiseCall(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), BuildRecoveryCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildResolvedCoawaitExpr(), clang::Sema::BuildSynthesizedThreeWayComparison(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildTypeTrait(), clang::Sema::BuildUnaryOp(), clang::Sema::BuildUnresolvedCoawaitExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildVAArgExpr(), clang::Sema::BuildVectorLiteral(), calculateConstraintSatisfaction(), clang::Sema::CallExprUnaryConversions(), checkArrayLikeDecomposition(), clang::Sema::CheckBooleanCondition(), clang::Sema::CheckConceptTemplateId(), clang::Sema::CheckConditionVariable(), CheckConvertedConstantExpression(), clang::Sema::CheckExtVectorCast(), clang::Sema::CheckLValueToRValueConversionOperand(), CheckObjCCollectionLiteralElement(), clang::Sema::CheckObjCForCollectionOperand(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::checkPseudoObjectAssignment(), clang::Sema::checkPseudoObjectIncDec(), clang::Sema::CheckSwitchCondition(), clang::Sema::CheckTemplateArgument(), clang::Sema::checkUnknownAnyArg(), clang::Sema::checkUnknownAnyCast(), clang::Sema::CheckVarTemplateId(), CopyObject(), CorrectDelayedTyposInBinOp(), clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CreateBuiltinMatrixSubscriptExpr(), clang::Sema::CreateBuiltinUnaryOp(), CreateFunctionRefExpr(), clang::Sema::CreateGenericSelectionExpr(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::CreateRecoveryExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DefaultFunctionArrayConversion(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::DefaultVariadicArgumentPromotion(), diagnoseAmbiguousConversion(), diagnoseUnknownAnyExpr(), ExprError(), FinishOverloadedCallExpr(), clang::Sema::getOpenMPCapturedExpr(), clang::Sema::HandleExprEvaluationContextForTypeof(), clang::Sema::HandleExprPropertyRefExpr(), clang::Sema::ImpCastExprToType(), clang::Sema::LookupInlineAsmIdentifier(), clang::Sema::LookupInObjCMethod(), LookupMemberExpr(), clang::Sema::MaybeBindToTemporary(), clang::Sema::MaybeConvertParenListExprToParenExpr(), clang::Sema::MaybeCreateExprWithCleanups(), clang::Parser::ParseAssignmentExpression(), clang::Parser::ParseConstraintExpression(), clang::Parser::ParseConstraintLogicalAndExpression(), clang::Parser::ParseConstraintLogicalOrExpression(), clang::Parser::ParseOpenMPParensExpr(), clang::InitializationSequence::Perform(), PerformConstructorInitialization(), clang::Sema::PerformContextualImplicitConversion(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformContextuallyConvertToObjCPointer(), clang::Sema::PerformCopyInitialization(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformImplicitConversion(), clang::Sema::PerformMoveOrCopyInitialization(), clang::Sema::PerformObjectArgumentInitialization(), clang::Sema::PerformObjectMemberConversion(), clang::Sema::PerformOpenMPImplicitIntegerConversion(), clang::Sema::prepareVectorSplat(), clang::TreeTransform< Derived >::RebuildConceptSpecializationExpr(), clang::TreeTransform< Derived >::RebuildCXXConstructExpr(), clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), clang::TreeTransform< Derived >::RebuildDesignatedInitExpr(), clang::TreeTransform< Derived >::RebuildMemberExpr(), rebuildPotentialResultsAsNonOdrUsed(), clang::TreeTransform< Derived >::RebuildUnaryExprOrTypeTrait(), rebuildUnknownAnyFunction(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), SemaBuiltinLaunder(), clang::Sema::SemaBuiltinShuffleVector(), clang::Sema::SemaConvertVectorExpr(), SubstDefaultTemplateArgument(), clang::Sema::TemporaryMaterializationConversion(), clang::TreeTransform< Derived >::TransformCXXNamedCastExpr(), clang::TreeTransform< Derived >::TransformInitializer(), TryReinterpretCast(), TryStaticCast(), clang::Sema::tryToRecoverWithCall(), clang::Sema::UsualUnaryConversions(), clang::Sema::VerifyBitField(), clang::Sema::VerifyIntegerConstantExpression(), and widenIterationCount().
ExprError() [2/2]
ExprResult clang::ExprError (const StreamingDiagnostic &) inline
Definition at line 282 of file Ownership.h.
References ExprError().
finalize()
template<class TemplateInstantiationCallbackPtrs > void clang::finalize (TemplateInstantiationCallbackPtrs & Callbacks, const Sema & TheSema)
Definition at line 52 of file TemplateInstCallback.h.
References C.
Referenced by ParseAST().
FixedPointValueToString()
void clang::FixedPointValueToString (SmallVectorImpl< char > & Str, llvm::APSInt Val, unsigned Scale)
Definition at line 4371 of file Type.cpp.
Referenced by clang::FixedPointLiteral::getValueAsString().
for() [1/2]
clang::for (auto typeArg :T-> getTypeArgsAsWritten())
Definition at line 1057 of file RecursiveASTVisitor.h.
Referenced by clang::driver::Command::Command(), clang::interp::DeadBlock::DeadBlock(), clang::tooling::HeaderIncludes::HeaderIncludes(), clang::driver::OffloadAction::OffloadAction(), clang::driver::OffloadAction::OffloadAction(), clang::PartialDiagnostic::PartialDiagnostic(), and REGISTER_MAP_FACTORY_WITH_PROGRAMSTATE().
for() [2/2]
clang::for (unsigned I = 0, E = TL.getNumArgs(); I != E; ++I)
Definition at line 1296 of file RecursiveASTVisitor.h.
FormatASTNodeDiagnosticArgument()
void clang::FormatASTNodeDiagnosticArgument (DiagnosticsEngine::ArgumentKind Kind, intptr_t Val, StringRef Modifier, StringRef Argument, ArrayRef< DiagnosticsEngine::ArgumentValue > PrevArgs, SmallVectorImpl< char > & Output, void * Cookie, ArrayRef< intptr_t > QualTypeVals)
DiagnosticsEngine argument formatting function for diagnostics that involve AST nodes.
This function formats diagnostic arguments for various AST nodes, including types, declaration names, nested name specifiers, and declaration contexts, into strings that can be printed as part of diagnostics. It is meant to be used as the argument to DiagnosticsEngine::SetArgToStringFn(), where the cookie is an ASTContext pointer.
Definition at line 323 of file ASTDiagnostic.cpp.
References clang::DiagnosticsEngine::ak_addrspace, clang::DiagnosticsEngine::ak_attr, clang::DiagnosticsEngine::ak_declarationname, clang::DiagnosticsEngine::ak_declcontext, clang::DiagnosticsEngine::ak_nameddecl, clang::DiagnosticsEngine::ak_nestednamespec, clang::DiagnosticsEngine::ak_qual, clang::DiagnosticsEngine::ak_qualtype, clang::DiagnosticsEngine::ak_qualtype_pair, cast(), ConvertTypeToDiagnosticString(), clang::TemplateDiffTypes::ElideType, FormatTemplateTypeDiff(), clang::Qualifiers::fromOpaqueValue(), clang::TemplateDiffTypes::FromType, clang::Qualifiers::getAddrSpaceAsString(), clang::Qualifiers::getAsString(), clang::DeclarationName::getFromOpaqueInteger(), clang::QualType::getFromOpaquePtr(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getNameForDiagnostic(), clang::ASTContext::getPrintingPolicy(), clang::Attr::getSpelling(), clang::ASTContext::getTypeDeclType(), clang::DeclContext::isClosure(), isLambdaCallOperator(), clang::DeclContext::isTranslationUnit(), OpenCL, clang::NestedNameSpecifier::print(), clang::TemplateDiffTypes::PrintFromType, clang::TemplateDiffTypes::PrintTree, clang::TemplateDiffTypes::ShowColors, clang::TemplateDiffTypes::TemplateDiffUsed, and clang::TemplateDiffTypes::ToType.
Referenced by clang::ASTMergeAction::ExecuteAction(), and clang::Sema::Sema().
FTIHasNonVoidParameters()
bool clang::FTIHasNonVoidParameters (const DeclaratorChunk::FunctionTypeInfo & FTI) inline
Definition at line 36 of file SemaInternal.h.
References FTIHasSingleVoidParameter(), and clang::DeclaratorChunk::FunctionTypeInfo::NumParams.
Referenced by clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnStartOfLambdaDefinition(), and clang::Sema::CheckDestructorDeclarator().
FTIHasSingleVoidParameter()
bool clang::FTIHasSingleVoidParameter (const DeclaratorChunk::FunctionTypeInfo & FTI) inline
Definition at line 29 of file SemaInternal.h.
References cast(), clang::DeclaratorChunk::ParamInfo::Ident, clang::DeclaratorChunk::FunctionTypeInfo::isVariadic, clang::DeclaratorChunk::FunctionTypeInfo::NumParams, clang::DeclaratorChunk::ParamInfo::Param, and clang::DeclaratorChunk::FunctionTypeInfo::Params.
Referenced by FTIHasNonVoidParameters().
getAccessSpelling()
llvm::StringRef clang::getAccessSpelling (AccessSpecifier AS) inline
Definition at line 361 of file Specifiers.h.
References AS_none, AS_private, AS_protected, and AS_public.
Referenced by clang::TextNodeDumper::dumpAccessSpecifier().
getAllPossibleAMDGPUTargetIDFeatures()
static const llvm::SmallVector< llvm::StringRef, 4 > clang::getAllPossibleAMDGPUTargetIDFeatures (const llvm::Triple & T, llvm::StringRef Proc) static
Definition at line 19 of file TargetID.cpp.
References Ret().
Referenced by getAllPossibleTargetIDFeatures().
getAllPossibleTargetIDFeatures()
const llvm::SmallVector< llvm::StringRef, 4 > clang::getAllPossibleTargetIDFeatures (const llvm::Triple & T, llvm::StringRef Processor)
Get all feature strings that can be used in target ID for Processor.
Target ID is a processor name with optional feature strings postfixed by a plus or minus sign delimited by colons, e.g. gfx908:xnack+:sramecc-. Each processor have a limited number of predefined features when showing up in a target ID.
Definition at line 37 of file TargetID.cpp.
References getAllPossibleAMDGPUTargetIDFeatures(), and Ret().
Referenced by clang::driver::tools::amdgpu::getAMDGPUTargetFeatures(), clang::targets::AMDGPUTargetInfo::getTargetDefines(), clang::targets::AMDGPUTargetInfo::handleTargetFeatures(), and parseTargetID().
getAsFileEvents()
std::vector< DirectoryWatcher::Event > clang::getAsFileEvents (const std::vector< std::string > & Scan)
Create event with EventKind::Added for every element in Scan.
Definition at line 43 of file DirectoryScanner.cpp.
References File, clang::DirectoryWatcher::Event::Modified, and Scan().
getAsNamedDecl()
NamedDecl * clang::getAsNamedDecl (TemplateParameter P) inline
Definition at line 3338 of file DeclTemplate.h.
References P.
getAsString()
llvm::StringRef clang::getAsString (SyncScope S) inline
Definition at line 50 of file SyncScope.h.
References OpenCLAllSVMDevices, OpenCLDevice, OpenCLSubGroup, and OpenCLWorkGroup.
Referenced by clang::TypoCorrectionConsumer::addCorrection(), EmitAtomicOp(), clang::Qualifiers::getAsString(), clang::QualType::getAsString(), and IsLLVMStringRef().
getAsTypeTemplateDecl()
TemplateDecl * clang::getAsTypeTemplateDecl (Decl * D) inline
Definition at line 3346 of file DeclTemplate.h.
References isa().
Referenced by clang::Sema::CheckTypenameType(), clang::Sema::DiagnoseEmptyLookup(), clang::Sema::getTypeName(), clang::Sema::isDeductionGuideName(), clang::Sema::resolveAssumedTemplateNameAsType(), and clang::FunctionCallFilterCCC::ValidateCandidate().
getBinOpPrecedence()
prec::Level clang::getBinOpPrecedence (tok::TokenKind Kind, bool GreaterThanIsOperator, bool CPlusPlus11)
Return the precedence of the specified binary operator token.
Definition at line 17 of file OperatorPrecedence.cpp.
References clang::prec::Additive, clang::prec::And, clang::prec::Assignment, clang::prec::Comma, clang::prec::Conditional, CPlusPlus11, clang::prec::Equality, clang::prec::ExclusiveOr, clang::prec::InclusiveOr, clang::prec::LogicalAnd, clang::prec::LogicalOr, clang::prec::Multiplicative, clang::prec::PointerToMember, clang::prec::Relational, clang::prec::Shift, clang::prec::Spaceship, and clang::prec::Unknown.
Referenced by clang::Sema::CheckConstraintExpression(), and clang::Parser::ParseConstraintLogicalAndExpression().
getCanonicalForwardRedeclChain() [1/2]
SmallVector< Decl *, 2 > clang::getCanonicalForwardRedeclChain (Decl * D)
Definition at line 123 of file ASTImporter.cpp.
References getCanonicalForwardRedeclChain().
Referenced by getCanonicalForwardRedeclChain(), clang::ASTNodeImporter::VisitFunctionDecl(), clang::ASTNodeImporter::VisitRecordDecl(), and clang::ASTNodeImporter::VisitVarDecl().
getCanonicalForwardRedeclChain() [2/2]
template<class T > SmallVector< Decl *, 2 > clang::getCanonicalForwardRedeclChain (Redeclarable< T > * D)
Definition at line 112 of file ASTImporter.cpp.
References clang::Redeclarable< decl_type >::getFirstDecl().
getCanonicalProcessorName()
static llvm::StringRef clang::getCanonicalProcessorName (const llvm::Triple & T, llvm::StringRef Processor) static
Returns canonical processor name or empty string if Processor is invalid.
Definition at line 46 of file TargetID.cpp.
Referenced by getProcessorFromTargetID(), and parseTargetID().
getCanonicalTargetID()
std::string clang::getCanonicalTargetID (llvm::StringRef Processor, const llvm::StringMap< bool > & Features)
Returns canonical target ID, assuming Processor is canonical and all entries in Features are valid.
Definition at line 130 of file TargetID.cpp.
Referenced by clang::targets::AMDGPUTargetInfo::getTargetID().
getClangFullCPPVersion()
std::string clang::getClangFullCPPVersion ()
Retrieves a string representing the complete clang version suitable for use in the CPP VERSION macro, which includes the clang version number, the repository version, and the vendor tag.
Definition at line 108 of file Version.cpp.
References getClangFullRepositoryVersion().
Referenced by InitializePredefinedMacros().
getClangFullRepositoryVersion()
std::string clang::getClangFullRepositoryVersion ()
Retrieves the full repository version that is an amalgamation of the information in getClangRepositoryPath() and getClangRevision().
Definition at line 60 of file Version.cpp.
References getClangRepositoryPath(), getClangRevision(), getLLVMRepositoryPath(), and getLLVMRevision().
Referenced by getClangFullCPPVersion(), getClangToolFullVersion(), clang::CompilerInvocation::getModuleHash(), InitializePredefinedMacros(), and clang::ASTReaderListener::ReadFullVersionInformation().
getClangFullVersion()
std::string clang::getClangFullVersion ()
Retrieves a string representing the complete clang version, which includes the clang version number, the repository version, and the vendor tag.
Definition at line 88 of file Version.cpp.
References getClangToolFullVersion().
Referenced by clang::driver::tools::ClangAs::ConstructJob(), createTool(), clang::driver::Driver::generateCompilationDiagnostics(), and clang::driver::Driver::PrintVersion().
getClangRepositoryPath()
std::string clang::getClangRepositoryPath ()
Retrieves the repository path (e.g., Subversion path) that identifies the particular Clang branch, tag, or trunk from which this Clang was built.
Definition at line 24 of file Version.cpp.
Referenced by getClangFullRepositoryVersion().
getClangRevision()
std::string clang::getClangRevision ()
Retrieves the repository revision number (or identifier) from which this Clang was built.
Definition at line 44 of file Version.cpp.
Referenced by getClangFullRepositoryVersion().
getClangToolFullVersion() [1/2]
std::string clang::getClangToolFullVersion (llvm::StringRef ToolName)
Like getClangFullVersion(), but with a custom tool name.
Referenced by getClangFullVersion(), and clang::driver::Driver::PrintVersion().
getClangToolFullVersion() [2/2]
std::string clang::getClangToolFullVersion (StringRef ToolName)
Definition at line 92 of file Version.cpp.
References getClangFullRepositoryVersion().
getCommandLineArgsForTesting()
std::vector< std::string > clang::getCommandLineArgsForTesting (TestLanguage Lang)
Definition at line 14 of file CommandLineArgs.cpp.
References Lang_C89, Lang_C99, Lang_CXX03, Lang_CXX11, Lang_CXX14, Lang_CXX17, Lang_CXX20, Lang_OBJCXX, and Lang_OpenCL.
Referenced by clang::TestClangConfig::getCommandLineArgs().
getComparisonCategoryForBuiltinCmp()
Optional< ComparisonCategoryType > clang::getComparisonCategoryForBuiltinCmp (QualType T)
Get the comparison category that should be used when comparing values of type T.
Definition at line 24 of file ComparisonCategories.cpp.
Referenced by checkArithmeticOrEnumeralThreeWayCompare(), and clang::Sema::CheckCompareOperands().
getCompletionComment()
const RawComment * clang::getCompletionComment (const ASTContext & Ctx, const NamedDecl * Decl)
Get the documentation comment used to produce CodeCompletionString::BriefComment for RK_Declaration.
Definition at line 3611 of file SemaCodeComplete.cpp.
References clang::ObjCPropertyDecl::findPropertyDecl(), and clang::ASTContext::getRawCommentForAnyRedecl().
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForDecl().
getCompletionKindString()
StringRef clang::getCompletionKindString (CodeCompletionContext::Kind Kind)
Get string representation of Kind, useful for for debugging.
Definition at line 91 of file CodeCompleteConsumer.cpp.
getConflictTargetIDCombination()
llvm::Optional< std::pair< llvm::StringRef, llvm::StringRef > > clang::getConflictTargetIDCombination (const std::set< llvm::StringRef > & TargetIDs)
Get the conflicted pair of target IDs for a compilation or a bundled code object, assuming TargetIDs are canonicalized.
If there is no conflicts, returns None.
Definition at line 145 of file TargetID.cpp.
References parseTargetIDWithFormatCheckingOnly().
getConstructorInfo()
ConstructorInfo clang::getConstructorInfo (NamedDecl * ND) inline
Definition at line 1174 of file Overload.h.
References clang::ConstructorInfo::Constructor, clang::ConstructorInfo::ConstructorTmpl, clang::Decl::getAccess(), clang::FunctionTemplateDecl::getTemplatedDecl(), clang::NamedDecl::getUnderlyingDecl(), and clang::DeclAccessPair::make().
Referenced by IsInitializerListConstructorConversion(), IsUserDefinedConversion(), clang::Sema::LookupSpecialMember(), PerformConstructorInitialization(), ResolveConstructorOverload(), TryRefInitWithConversionFunction(), and TryUserDefinedConversion().
GetConversionRank()
ImplicitConversionRank clang::GetConversionRank (ImplicitConversionKind Kind)
GetConversionRank - Retrieve the implicit conversion rank corresponding to the given implicit conversion kind.
Definition at line 118 of file SemaOverload.cpp.
References ICK_Num_Conversion_Kinds, ICR_C_Conversion, ICR_C_Conversion_Extension, ICR_Complex_Real_Conversion, ICR_Conversion, ICR_Exact_Match, ICR_OCL_Scalar_Widening, ICR_Promotion, ICR_Writeback_Conversion, and int.
Referenced by clang::Sema::AddConversionCandidate(), and clang::StandardConversionSequence::getRank().
getCursorKindForDecl()
CXCursorKind clang::getCursorKindForDecl (const Decl * D)
Determine the libclang cursor kind associated with the given declaration.
Definition at line 3807 of file SemaCodeComplete.cpp.
References cast(), CXCursor_ClassDecl, CXCursor_ClassTemplate, CXCursor_ClassTemplatePartialSpecialization, CXCursor_Constructor, CXCursor_ConversionFunction, CXCursor_CXXAccessSpecifier, CXCursor_CXXMethod, CXCursor_Destructor, CXCursor_EnumConstantDecl, CXCursor_EnumDecl, CXCursor_FieldDecl, CXCursor_FriendDecl, CXCursor_FunctionDecl, CXCursor_FunctionTemplate, CXCursor_ModuleImportDecl, CXCursor_Namespace, CXCursor_NamespaceAlias, CXCursor_NonTypeTemplateParameter, CXCursor_ObjCCategoryDecl, CXCursor_ObjCCategoryImplDecl, CXCursor_ObjCClassMethodDecl, CXCursor_ObjCDynamicDecl, CXCursor_ObjCImplementationDecl, CXCursor_ObjCInstanceMethodDecl, CXCursor_ObjCInterfaceDecl, CXCursor_ObjCIvarDecl, CXCursor_ObjCPropertyDecl, CXCursor_ObjCProtocolDecl, CXCursor_ObjCSynthesizeDecl, CXCursor_ParmDecl, CXCursor_StaticAssert, CXCursor_StructDecl, CXCursor_TemplateTemplateParameter, CXCursor_TemplateTypeParameter, CXCursor_TranslationUnit, CXCursor_TypeAliasDecl, CXCursor_TypeAliasTemplateDecl, CXCursor_TypedefDecl, CXCursor_UnexposedDecl, CXCursor_UnionDecl, CXCursor_UsingDeclaration, CXCursor_UsingDirective, CXCursor_VarDecl, clang::ObjCPropertyImplDecl::Dynamic, clang::Decl::getKind(), clang::ObjCPropertyImplDecl::Synthesize, TTK_Class, TTK_Enum, TTK_Interface, TTK_Struct, and TTK_Union.
Referenced by clang::Sema::CodeCompleteConstructorInitializer().
getDeclUsageType()
QualType clang::getDeclUsageType (ASTContext & C, const NamedDecl * ND)
Determine the type that this declaration will have if it is used as a type or in an expression.
Get the type that a given expression will have if this declaration is used as an expression in its "typical" code-completion form.
Definition at line 881 of file SemaCodeComplete.cpp.
References Block, C, clang::Decl::getAsFunction(), clang::NamedDecl::getUnderlyingDecl(), and Pointer.
getDepthAndIndex() [1/2]
std::pair< unsigned, unsigned > clang::getDepthAndIndex (NamedDecl * ND) inline
Retrieve the depth and index of a template parameter.
Definition at line 65 of file SemaInternal.h.
References cast().
Referenced by clang::Sema::CheckParameterPacksForExpansion(), getDepthAndIndex(), and clang::Sema::getNumArgumentsInExpansion().
getDepthAndIndex() [2/2]
std::pair< unsigned, unsigned > clang::getDepthAndIndex (UnexpandedParameterPack UPP) inline
Retrieve the depth and index of an unexpanded parameter pack.
Definition at line 78 of file SemaInternal.h.
References getDepthAndIndex().
getDLLAttr()
InheritableAttr * clang::getDLLAttr (Decl * D) inline
Return a DLL attribute from the declaration.
Definition at line 54 of file SemaInternal.h.
References clang::Decl::getAttr(), and clang::Decl::hasAttr().
Referenced by clang::Sema::ActOnExplicitInstantiation(), checkAttributesAfterMerging(), clang::Sema::CheckBaseSpecifier(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckStaticLocalForDllExport(), dllExportImportClassTemplateSpecialization(), clang::Sema::FinalizeDeclaration(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), ReferenceDllExportedMembers(), and clang::Sema::SetDeclDeleted().
getExpandedPackSize()
Optional< unsigned > clang::getExpandedPackSize (const NamedDecl * Param) inline
Check whether the template parameter is a pack expansion, and if so, determine the number of parameters produced by that expansion.
For instance:
template<typename ...Ts> struct A {
  template<Ts ...NTs, template<Ts> class ...TTs, typename ...Us> struct B;
};
In A<int,int>::B, NTs and TTs have expanded pack size 2, and Us is not a pack expansion, so returns an empty Optional.
Definition at line 3367 of file DeclTemplate.h.
References None.
Referenced by clang::Sema::CheckTemplateArgumentList(), and clang::Sema::SubstituteExplicitTemplateArguments().
getFilenameForTesting()
StringRef clang::getFilenameForTesting (TestLanguage Lang)
Definition at line 48 of file CommandLineArgs.cpp.
References Lang_C89, Lang_C99, Lang_CXX03, Lang_CXX11, Lang_CXX14, Lang_CXX17, Lang_CXX20, Lang_OBJCXX, and Lang_OpenCL.
getFileStatus() [1/2]
llvm::Optional< llvm::sys::fs::file_status > clang::getFileStatus (llvm::StringRef Path)
Gets status of file (or directory) at Path.
Returns
llvm::None if Path doesn't exist or can't get the status.
getFileStatus() [2/2]
Optional< sys::fs::file_status > clang::getFileStatus (StringRef Path)
Definition at line 17 of file DirectoryScanner.cpp.
References None.
Referenced by scanDirectory().
getFormalLinkage()
Linkage clang::getFormalLinkage (Linkage L) inline
Definition at line 95 of file Linkage.h.
References ExternalLinkage, InternalLinkage, ModuleInternalLinkage, NoLinkage, UniqueExternalLinkage, and VisibleNoLinkage.
Referenced by clang::NamedDecl::getFormalLinkage(), and isExternalFormalLinkage().
getFunctionExtInfo() [1/2]
FunctionType::ExtInfo clang::getFunctionExtInfo (const Type & t) inline
Definition at line 6560 of file Type.h.
References clang::Type::getAs().
Referenced by getFunctionExtInfo(), and clang::ASTContext::mergeObjCGCQualifiers().
getFunctionExtInfo() [2/2]
FunctionType::ExtInfo clang::getFunctionExtInfo (QualType t) inline
Definition at line 6570 of file Type.h.
References getFunctionExtInfo().
getIssueHash()
llvm::SmallString< 32 > clang::getIssueHash (const FullSourceLoc & IssueLoc, llvm::StringRef CheckerName, llvm::StringRef WarningMessage, const Decl * IssueDecl, const LangOptions & LangOpts)
Returns an opaque identifier for a diagnostic.
This opaque identifier is intended to be stable even when the source code is changed. It allows to track diagnostics in the long term, for example, find which diagnostics are "new", maintain a database of suppressed diagnostics etc.
We may introduce more variants of issue hashes in the future but older variants will still be available for compatibility.
This hash is based on the following information:
Name of the checker that emitted the diagnostic.
Warning message.
Name of the enclosing declaration.
Contents of the line of code with the issue, excluding whitespace.
Column number (but not the line number! - which makes it stable).
getIssueString()
std::string clang::getIssueString (const FullSourceLoc & IssueLoc, llvm::StringRef CheckerName, llvm::StringRef WarningMessage, const Decl * IssueDecl, const LangOptions & LangOpts)
Get the unhashed string representation of the V1 issue hash.
When hashed, it becomes the actual issue hash. Useful for testing. See GetIssueHashV1() for more information.
getKeywordSelector()
template<typename... IdentifierInfos> static Selector clang::getKeywordSelector (ASTContext & Ctx, IdentifierInfos *... IIs) inline static
Definition at line 17 of file SelectorExtras.h.
References clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::ASTContext::Idents, and clang::ASTContext::Selectors.
Referenced by lazyInitKeywordSelector().
getLambdaAwareParentOfDeclContext()
DeclContext * clang::getLambdaAwareParentOfDeclContext (DeclContext * DC) inline
Definition at line 81 of file ASTLambda.h.
References clang::DeclContext::getParent(), and isLambdaCallOperator().
Referenced by adjustCVQualifiersForCXXThisWithinLambda(), clang::Sema::CheckShadow(), getParentOfCapturingContextOrNull(), getStackIndexOfNearestEnclosingCaptureReadyLambda(), and clang::Sema::tryCaptureVariable().
getLambdaStaticInvokerName()
StringRef clang::getLambdaStaticInvokerName () inline
Definition at line 22 of file ASTLambda.h.
Referenced by addFunctionPointerConversion(), getLambdaStaticInvokers(), and clang::CXXMethodDecl::isLambdaStaticInvoker().
getLangASFromTargetAS()
LangAS clang::getLangASFromTargetAS (unsigned TargetAS) inline
Definition at line 73 of file AddressSpaces.h.
References FirstTargetAddressSpace.
Referenced by BuildAddressSpaceIndex(), clang::targets::AMDGPUTargetInfo::getConstantAddressSpace(), clang::TargetInfo::getCUDABuiltinAddressSpace(), clang::ASTContext::getLangASForBuiltinAddressSpace(), clang::TargetInfo::getOpenCLBuiltinAddressSpace(), clang::targets::AMDGPUTargetInfo::getOpenCLBuiltinAddressSpace(), and clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter().
getLastArgIntValue() [1/3]
int clang::getLastArgIntValue (const ArgList & Args, OptSpecifier Id, int Default, DiagnosticsEngine * Diags, unsigned Base)
Definition at line 36 of file OptionUtils.cpp.
References Default, and Id.
getLastArgIntValue() [2/3]
int clang::getLastArgIntValue (const llvm::opt::ArgList & Args, llvm::opt::OptSpecifier Id, int Default, DiagnosticsEngine & Diags, unsigned Base = 0) inline
Definition at line 37 of file OptionUtils.h.
References Default, getLastArgIntValue(), and Id.
getLastArgIntValue() [3/3]
int clang::getLastArgIntValue (const llvm::opt::ArgList & Args, llvm::opt::OptSpecifier Id, int Default, DiagnosticsEngine * Diags = nullptr, unsigned Base = 0)
Return the value of the last argument as an integer, or a default.
If Diags is non-null, emits an error if the argument is given, but non-integral.
Referenced by clang::CompilerInvocation::CreateFromArgs(), getLastArgIntValue(), and getOptimizationLevel().
getLastArgUInt64Value() [1/3]
uint64_t clang::getLastArgUInt64Value (const ArgList & Args, OptSpecifier Id, uint64_t Default, DiagnosticsEngine * Diags, unsigned Base)
Definition at line 41 of file OptionUtils.cpp.
References Default, and Id.
getLastArgUInt64Value() [2/3]
uint64_t clang::getLastArgUInt64Value (const llvm::opt::ArgList & Args, llvm::opt::OptSpecifier Id, uint64_t Default, DiagnosticsEngine & Diags, unsigned Base = 0) inline
Definition at line 48 of file OptionUtils.h.
References Default, getLastArgUInt64Value(), and Id.
getLastArgUInt64Value() [3/3]
uint64_t clang::getLastArgUInt64Value (const llvm::opt::ArgList & Args, llvm::opt::OptSpecifier Id, uint64_t Default, DiagnosticsEngine * Diags = nullptr, unsigned Base = 0)
Referenced by getLastArgUInt64Value().
getLLVMRepositoryPath()
std::string clang::getLLVMRepositoryPath ()
Retrieves the repository path from which LLVM was built.
This supports LLVM residing in a separate repository from clang.
Definition at line 36 of file Version.cpp.
Referenced by getClangFullRepositoryVersion().
getLLVMRevision()
std::string clang::getLLVMRevision ()
Retrieves the repository revision number (or identifier) from which LLVM was built.
If Clang and LLVM are in the same repository, this returns the same string as getClangRevision.
Definition at line 52 of file Version.cpp.
Referenced by getClangFullRepositoryVersion().
getMacroUsagePriority()
unsigned clang::getMacroUsagePriority (StringRef MacroName, const LangOptions & LangOpts, bool PreferredTypeIsPointer = false)
Determine the priority to be given to a macro code completion result with the given name.
Parameters
MacroName The name of the macro.
LangOpts Options describing the current language dialect.
PreferredTypeIsPointer Whether the preferred type for the context of this macro is a pointer type.
Definition at line 3784 of file SemaCodeComplete.cpp.
References CCD_bool_in_ObjC, CCF_SimilarTypeMatch, CCP_Constant, CCP_Macro, CCP_Type, and Priority.
Referenced by AddMacroResults().
getNullabilitySpelling()
StringRef clang::getNullabilitySpelling (NullabilityKind kind, bool isContextSensitive = false)
Retrieve the spelling of the given nullability kind.
Definition at line 708 of file IdentifierTable.cpp.
References NonNull, Nullable, NullableResult, and Unspecified.
Referenced by checkNullabilityTypeSpecifier(), and fixItNullability().
GetNullarySelector()
Selector clang::GetNullarySelector (StringRef name, ASTContext & Ctx) inline
Utility function for constructing a nullary selector.
Definition at line 3130 of file ASTContext.h.
References clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::ASTContext::Idents, and clang::ASTContext::Selectors.
Referenced by clang::Sema::WarnExactTypedMethods().
getOpenMPCaptureRegions()
void clang::getOpenMPCaptureRegions (llvm::SmallVectorImpl< OpenMPDirectiveKind > & CaptureRegions, OpenMPDirectiveKind DKind)
Return the captured regions of an OpenMP directive.
Definition at line 576 of file OpenMPKinds.cpp.
Referenced by clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPRegionEnd(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::OMPExecutableDirective::getCapturedStmt(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::Sema::getOpenMPCaptureLevels(), clang::Sema::isOpenMPCapturedDecl(), clang::Sema::isOpenMPPrivateDecl(), and clang::Sema::isOpenMPTargetCapturedDecl().
getOpenMPSimpleClauseType()
unsigned clang::getOpenMPSimpleClauseType (OpenMPClauseKind Kind, llvm::StringRef Str, unsigned OpenMPVersion)
Referenced by isMapModifier(), isMapType(), parseOpenMPSimpleClause(), and clang::Parser::ParseOpenMPVarList().
getOpenMPSimpleClauseTypeName()
const char * clang::getOpenMPSimpleClauseTypeName (OpenMPClauseKind Kind, unsigned Type)
Definition at line 190 of file OpenMPKinds.cpp.
References OMPC_ATOMIC_DEFAULT_MEM_ORDER_unknown, OMPC_DEFAULTMAP_MODIFIER_last, OMPC_DEFAULTMAP_unknown, OMPC_DEPEND_unknown, OMPC_DEVICE_TYPE_unknown, OMPC_DEVICE_unknown, OMPC_DIST_SCHEDULE_unknown, OMPC_LASTPRIVATE_unknown, OMPC_LINEAR_unknown, OMPC_MAP_MODIFIER_last, OMPC_MAP_unknown, OMPC_MOTION_MODIFIER_unknown, OMPC_ORDER_unknown, OMPC_REDUCTION_unknown, OMPC_SCHEDULE_MODIFIER_last, and OMPC_SCHEDULE_unknown.
Referenced by clang::Sema::ActOnOpenMPDefaultmapClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPRegionEnd(), clang::Sema::ActOnOpenMPScheduleClause(), checkMappableExpressionList(), clang::Sema::CheckOpenMPLinearDecl(), checkOrderedOrderSpecified(), clang::Sema::finalizeOpenMPDelayedAnalysis(), getListOfPossibleValues(), and clang::OMPDeclareSimdDeclAttr::printPrettyPragma().
getOpenMPVariantManglingSeparatorStr()
static constexpr StringRef clang::getOpenMPVariantManglingSeparatorStr () static constexpr
OpenMP variants are mangled early based on their OpenMP context selector.
The new name looks likes this: <name> + OpenMPVariantManglingSeparatorStr + <mangled OpenMP context>
Definition at line 4598 of file Decl.h.
Referenced by clang::Sema::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope(), and clang::DeclarationName::print().
getOperatorSpelling()
const char * clang::getOperatorSpelling (OverloadedOperatorKind Operator)
Retrieve the spelling of the given overloaded operator, without the preceding "operator" keyword.
Definition at line 694 of file IdentifierTable.cpp.
References NUM_OVERLOADED_OPERATORS, and OO_None.
Referenced by clang::Sema::CreateOverloadedBinOp(), clang::DeclarationName::print(), clang::TemplateName::print(), printMemFnName(), and clang::TextNodeDumper::VisitCXXOperatorCallExpr().
getParameterABISpelling()
StringRef clang::getParameterABISpelling (ParameterABI kind)
Definition at line 843 of file TypePrinter.cpp.
Referenced by checkExtParameterInfos().
getParameterComment()
const RawComment * clang::getParameterComment (const ASTContext & Ctx, const CodeCompleteConsumer::OverloadCandidate & Result, unsigned ArgIndex)
Get the documentation comment used to produce CodeCompletionString::BriefComment for OverloadCandidate.
Definition at line 3652 of file SemaCodeComplete.cpp.
References clang::ASTContext::getRawCommentForAnyRedecl(), and Result.
Referenced by clang::CodeCompleteConsumer::OverloadCandidate::CreateSignatureString().
getPatternCompletionComment()
const RawComment * clang::getPatternCompletionComment (const ASTContext & Ctx, const NamedDecl * Decl)
Get the documentation comment used to produce CodeCompletionString::BriefComment for RK_Pattern.
Definition at line 3629 of file SemaCodeComplete.cpp.
References clang::ObjCPropertyDecl::findPropertyDecl(), clang::ObjCPropertyDecl::getGetterName(), clang::NamedDecl::getIdentifier(), and clang::ASTContext::getRawCommentForAnyRedecl().
Referenced by clang::CodeCompletionResult::CreateCodeCompletionString().
getPPTransparentSanitizers()
SanitizerMask clang::getPPTransparentSanitizers () inline
Return the sanitizers which do not affect preprocessing.
Definition at line 186 of file Sanitizers.h.
Referenced by checkLanguageOptions(), and clang::CompilerInvocation::getModuleHash().
getPrimaryMergedDecl()
Decl * clang::getPrimaryMergedDecl (Decl * D)
Get the primary declaration for a declaration from an AST file.
That will be the first-loaded declaration.
Definition at line 76 of file Decl.cpp.
References clang::Decl::getASTContext(), and clang::ASTContext::getPrimaryMergedDecl().
Referenced by clang::Mergeable< decl_type >::getFirstDecl(), and clang::Mergeable< decl_type >::getFirstDecl().
getProcessorFromTargetID()
llvm::StringRef clang::getProcessorFromTargetID (const llvm::Triple & T, llvm::StringRef OffloadArch)
Get processor name from target ID.
Returns canonical processor name or empty if the processor name is invalid.
Definition at line 53 of file TargetID.cpp.
References getCanonicalProcessorName(), and Split.
Referenced by getAMDGPUTargetGPU(), clang::driver::toolchains::AMDGPUToolChain::getDefaultDenormalModeForType(), and clang::driver::toolchains::AMDGPUToolChain::getGPUArch().
getRewrittenOverloadedOperator()
OverloadedOperatorKind clang::getRewrittenOverloadedOperator (OverloadedOperatorKind Kind) inline
Get the other overloaded operator that the given operator can be rewritten into, if any such operator exists.
Definition at line 36 of file OperatorKinds.h.
References OO_None.
Referenced by clang::OverloadCandidateSet::OperatorRewriteInfo::isAcceptableCandidate(), clang::OverloadCandidateSet::OperatorRewriteInfo::isReversible(), clang::Sema::LookupBinOp(), lookupOperatorsForDefaultedComparison(), and clang::Sema::LookupOverloadedBinOp().
getSimplifiedTypeClass()
SimplifiedTypeClass clang::getSimplifiedTypeClass (CanQualType T)
Determine the simplified type class of the given canonical type.
A simplified classification of types used to determine whether two types are "similar enough" when adjusting priorities.
Definition at line 812 of file SemaCodeComplete.cpp.
References getKind(), clang::ReferenceType::getPointeeType(), getSimplifiedTypeClass(), STC_Arithmetic, STC_Array, STC_Block, STC_Function, STC_ObjectiveC, STC_Other, STC_Pointer, STC_Record, and STC_Void.
Referenced by getSimplifiedTypeClass().
getSpecificAttr()
template<typename SpecificAttr , typename Container > SpecificAttr * clang::getSpecificAttr (const Container & container) inline
Definition at line 117 of file AttrIterator.h.
References specific_attr_begin(), and specific_attr_end().
getStackIndexOfNearestEnclosingCaptureCapableLambda()
Optional< unsigned > clang::getStackIndexOfNearestEnclosingCaptureCapableLambda (ArrayRef< const sema::FunctionScopeInfo * > FunctionScopes, VarDecl * VarToCapture, Sema & S)
Examines the FunctionScopeInfo stack to determine the nearest enclosing lambda (to the current lambda) that is 'capture-capable' for the variable referenced in the current lambda (i.e.
VarToCapture). If successful, returns the index into Sema's FunctionScopeInfo stack of the capture-capable lambda's LambdaScopeInfo. See Implementation for more detailed comments.
VarToCapture). If successful, returns the index into Sema's FunctionScopeInfo stack of the capture-capable lambda's LambdaScopeInfo.
Given the current stack of lambdas being processed by Sema and the variable of interest, to identify the nearest enclosing lambda (to the current lambda at the top of the stack) that can truly capture a variable, it has to have the following two properties: a) 'capture-ready' - be the innermost lambda that is 'capture-ready':
climb down the stack (i.e. starting from the innermost and examining each outer lambda step by step) checking if each enclosing lambda can either implicitly or explicitly capture the variable. Record the first such lambda that is enclosed in a non-dependent context. If no such lambda currently exists return failure. b) 'capture-capable' - make sure the 'capture-ready' lambda can truly capture the variable by checking all its enclosing lambdas:
check if all outer lambdas enclosing the 'capture-ready' lambda identified above in 'a' can also capture the variable (this is done via tryCaptureVariable for variables and CheckCXXThisCapture for 'this' by passing in the index of the Lambda identified in step 'a')
Parameters
FunctionScopes - Sema's stack of nested FunctionScopeInfo's (which a LambdaScopeInfo inherits from). The current/deepest/innermost lambda is at the top of the stack.
VarToCapture - the variable to capture. If NULL, capture 'this'.
Returns
An Optional<unsigned> Index that if evaluates to 'true' contains the index (into Sema's FunctionScopeInfo stack) of the innermost lambda which is capture-capable. If the return value evaluates to 'false' then no lambda is capture-capable for VarToCapture.
Definition at line 173 of file SemaLambda.cpp.
References cast(), clang::Sema::CheckCXXThisCapture(), clang::Sema::getCurGenericLambda(), getStackIndexOfNearestEnclosingCaptureReadyLambda(), clang::sema::LambdaScopeInfo::PotentialThisCaptureLocation, clang::Sema::TryCapture_Implicit, and clang::Sema::tryCaptureVariable().
Referenced by CheckIfAnyEnclosingLambdasMustCaptureAnyPotentialCaptures().
getStandardSelectorLoc() [1/2]
SourceLocation clang::getStandardSelectorLoc (unsigned Index, Selector Sel, bool WithArgSpace, ArrayRef< Expr * > Args, SourceLocation EndLoc)
Get the "standard" location of a selector identifier, e.g: For nullary selectors, immediately before ']': "[foo release]".
Parameters
WithArgSpace if true the standard location is with a space apart before arguments: "[foo first: 1 second: 2]" If false: "[foo first:1 second:2]"
Definition at line 103 of file SelectorLocationsKind.cpp.
References getStandardSelLoc().
Referenced by clang::ObjCMessageExpr::getSelectorLoc(), and clang::ObjCMethodDecl::getSelectorLoc().
getStandardSelectorLoc() [2/2]
SourceLocation clang::getStandardSelectorLoc (unsigned Index, Selector Sel, bool WithArgSpace, ArrayRef< ParmVarDecl * > Args, SourceLocation EndLoc)
Get the "standard" location of a selector identifier, e.g: For nullary selectors, immediately before ']': "[foo release]".
Parameters
WithArgSpace if true the standard location is with a space apart before arguments: "-(id)first: (int)x second: (int)y;" If false: "-(id)first:(int)x second:(int)y;"
Definition at line 120 of file SelectorLocationsKind.cpp.
References getStandardSelLoc().
getTemplateParamsRange()
SourceRange clang::getTemplateParamsRange (TemplateParameterList const *const * Params, unsigned NumParams)
Retrieves the range of the given template parameter lists.
Definition at line 44 of file SemaTemplate.cpp.
References N.
getTraitName() [1/4]
const char * clang::getTraitName (ArrayTypeTrait T)
Definition at line 63 of file TypeTraits.cpp.
References ArrayTypeTraitNames, and ATT_Last.
getTraitName() [2/4]
const char * clang::getTraitName (ExpressionTrait T)
Return the internal name of type trait T. Never null.
Definition at line 28 of file ExpressionTraits.cpp.
References ET_Last, and ExpressionTraitNames.
getTraitName() [3/4]
const char * clang::getTraitName (TypeTrait T)
Return the internal name of type trait T. Never null.
Definition at line 58 of file TypeTraits.cpp.
References TT_Last, and TypeTraitNames.
getTraitName() [4/4]
const char * clang::getTraitName (UnaryExprOrTypeTrait T)
Definition at line 68 of file TypeTraits.cpp.
References UETT_Last, and UnaryExprOrTypeTraitNames.
getTraitSpelling() [1/4]
const char * clang::getTraitSpelling (ArrayTypeTrait T)
Definition at line 78 of file TypeTraits.cpp.
References ArrayTypeTraitSpellings, and ATT_Last.
getTraitSpelling() [2/4]
const char * clang::getTraitSpelling (ExpressionTrait T)
Return the spelling of the type trait TT. Never null.
Definition at line 33 of file ExpressionTraits.cpp.
References ET_Last, and ExpressionTraitSpellings.
Referenced by CheckExtensionTraitOperandType(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::TextNodeDumper::VisitArrayTypeTraitExpr(), clang::TextNodeDumper::VisitExpressionTraitExpr(), clang::TextNodeDumper::VisitTypeTraitExpr(), clang::JSONNodeDumper::VisitUnaryExprOrTypeTraitExpr(), and clang::TextNodeDumper::VisitUnaryExprOrTypeTraitExpr().
getTraitSpelling() [3/4]
const char * clang::getTraitSpelling (TypeTrait T)
Return the spelling of the type trait TT. Never null.
Definition at line 73 of file TypeTraits.cpp.
References TT_Last, and TypeTraitSpellings.
getTraitSpelling() [4/4]
const char * clang::getTraitSpelling (UnaryExprOrTypeTrait T)
Definition at line 83 of file TypeTraits.cpp.
References UETT_Last, and UnaryExprOrTypeTraitSpellings.
GetUnarySelector()
Selector clang::GetUnarySelector (StringRef name, ASTContext & Ctx) inline
Utility function for constructing an unary selector.
Definition at line 3136 of file ASTContext.h.
References clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::ASTContext::Idents, and clang::ASTContext::Selectors.
GetUnderlyingFunction()
static const FunctionProtoType * clang::GetUnderlyingFunction (QualType T) static
Definition at line 27 of file SemaExceptionSpec.cpp.
References clang::Type::getAs(), and clang::Type::getPointeeType().
Referenced by clang::Sema::CheckExceptionSpecCompatibility(), and CheckSpecForTypesEquivalent().
hasAttribute()
int clang::hasAttribute (AttrSyntax Syntax, const IdentifierInfo * Scope, const IdentifierInfo * Attr, const TargetInfo & Target, const LangOptions & LangOpts)
Return the version number associated with the attribute if we recognize and implement the attribute specified by the given information.
Definition at line 8 of file Attributes.cpp.
Referenced by checkNewAttributesAfterDef().
hash_value() [1/4]
llvm::hash_code clang::hash_value (const APValue::LValueBase & Base)
Definition at line 202 of file APValue.cpp.
hash_value() [2/4]
llvm::hash_code clang::hash_value (const clang::SanitizerMask & Arg)
Definition at line 51 of file Sanitizers.cpp.
References clang::SanitizerMask::hash_value().
Referenced by llvm::DenseMapInfo< clang::APValue::LValueBase >::getHashValue(), llvm::DenseMapInfo< ObjectUnderConstruction >::getHashValue(), and clang::CompilerInvocation::getModuleHash().
hash_value() [3/4]
llvm::hash_code clang::hash_value (const HeaderSearchOptions::Entry & E) inline
Definition at line 255 of file HeaderSearchOptions.h.
References clang::HeaderSearchOptions::Entry::Group, clang::HeaderSearchOptions::Entry::IgnoreSysRoot, clang::HeaderSearchOptions::Entry::IsFramework, and clang::HeaderSearchOptions::Entry::Path.
hash_value() [4/4]
llvm::hash_code clang::hash_value (const HeaderSearchOptions::SystemHeaderPrefix & SHP) inline
Definition at line 260 of file HeaderSearchOptions.h.
References clang::HeaderSearchOptions::SystemHeaderPrefix::IsSystemHeader, and clang::HeaderSearchOptions::SystemHeaderPrefix::Prefix.
hasImplicitExceptionSpec()
static bool clang::hasImplicitExceptionSpec (FunctionDecl * Decl) static
Determine whether a function has an implicitly-generated exception specification.
Definition at line 267 of file SemaExceptionSpec.cpp.
References clang::FunctionProtoType::hasExceptionSpec(), and isa().
Referenced by clang::Sema::CheckEquivalentExceptionSpec().
hasSpecificAttr()
template<typename SpecificAttr , typename Container > bool clang::hasSpecificAttr (const Container & container) inline
Definition at line 112 of file AttrIterator.h.
References specific_attr_begin(), and specific_attr_end().
Referenced by clang::Decl::hasAttr().
hasStandardSelectorLocs() [1/2]
SelectorLocationsKind clang::hasStandardSelectorLocs (Selector Sel, ArrayRef< SourceLocation > SelLocs, ArrayRef< Expr * > Args, SourceLocation EndLoc)
Returns true if all SelLocs are in a "standard" location.
Definition at line 96 of file SelectorLocationsKind.cpp.
Referenced by clang::ObjCMethodDecl::setMethodParams().
hasStandardSelectorLocs() [2/2]
SelectorLocationsKind clang::hasStandardSelectorLocs (Selector Sel, ArrayRef< SourceLocation > SelLocs, ArrayRef< ParmVarDecl * > Args, SourceLocation EndLoc)
Returns true if all SelLocs are in a "standard" location.
Definition at line 113 of file SelectorLocationsKind.cpp.
hasWeakerNullability()
bool clang::hasWeakerNullability (NullabilityKind L, NullabilityKind R) inline
Return true if L has a weaker nullability annotation than R.
The ordering is: Unspecified < Nullable < NonNull.
Definition at line 322 of file Specifiers.h.
Referenced by clang::Sema::deduceClosureReturnType().
if() [1/2]
clang::if (T-> getSizeExpr()) -> getSizeExpr()))
Initial value:
{
  TRY_TO(TraverseType(T->getDeducedType()))
Definition at line 996 of file RecursiveASTVisitor.h.
Referenced by clang::targets::AArch64TargetInfo::AArch64TargetInfo(), clang::CodeGen::ApplyDebugLocation::ApplyDebugLocation(), clang::targets::ARMTargetInfo::ARMTargetInfo(), clang::ASTSourceDescriptor::ASTSourceDescriptor(), clang::driver::toolchains::AVRToolChain::AVRToolChain(), clang::format::CompoundStatementIndenter::CompoundStatementIndenter(), clang::CoroutineStmtBuilder::CoroutineStmtBuilder(), getSelfFlags(), clang::tooling::HeaderIncludes::HeaderIncludes(), clang::tooling::IncludeCategoryManager::IncludeCategoryManager(), clang::Sema::InheritedConstructorInfo::InheritedConstructorInfo(), clang::MultiplexConsumer::MultiplexConsumer(), clang::NestedNameSpecifierLocBuilder::NestedNameSpecifierLocBuilder(), clang::driver::OffloadAction::OffloadAction(), clang::driver::toolchains::PS4CPU::PS4CPU(), clang::driver::RocmInstallationDetector::RocmInstallationDetector(), clang::format::ScopedLineState::ScopedLineState(), clang::driver::ToolChain::ToolChain(), and clang::sema::FunctionScopeInfo::WeakObjectProfileTy::WeakObjectProfileTy().
if() [2/2]
clang::if (TL. isConstrained())
Definition at line 1270 of file RecursiveASTVisitor.h.
References TRY_TO.
IgnoreBaseCastsSingleStep()
Expr * clang::IgnoreBaseCastsSingleStep (Expr * E) inline
Definition at line 100 of file IgnoreExpr.h.
Referenced by clang::Expr::IgnoreParenBaseCasts().
IgnoreCastsSingleStep()
Expr * clang::IgnoreCastsSingleStep (Expr * E) inline
Definition at line 74 of file IgnoreExpr.h.
Referenced by clang::Expr::IgnoreCasts(), IgnoreLValueCastsSingleStep(), and clang::Expr::IgnoreParenCasts().
IgnoreExprNodes() [1/2]
template<typename... FnTys> const Expr * clang::IgnoreExprNodes (const Expr * E, FnTys &&... Fns)
Definition at line 43 of file IgnoreExpr.h.
References IgnoreExprNodes().
IgnoreExprNodes() [2/2]
template<typename... FnTys> Expr * clang::IgnoreExprNodes (Expr * E, FnTys &&... Fns)
Given an expression E and functions Fn_1,...,Fn_n : Expr * -> Expr *, Recursively apply each of the functions to E until reaching a fixed point.
Note that a null E is valid; in this case nothing is done.
Definition at line 33 of file IgnoreExpr.h.
References clang::detail::IgnoreExprNodesImpl().
Referenced by clang::Expr::IgnoreCasts(), IgnoreExprNodes(), clang::Expr::IgnoreImpCasts(), clang::Expr::IgnoreImplicit(), IgnoreImplicit(), clang::Expr::IgnoreImplicitAsWritten(), clang::Expr::IgnoreParenBaseCasts(), clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenImpCasts(), clang::Expr::IgnoreParenLValueCasts(), clang::Expr::IgnoreParenNoopCasts(), clang::Expr::IgnoreParens(), and clang::Expr::IgnoreUnlessSpelledInSource().
IgnoreImplicitAsWrittenSingleStep()
Expr * clang::IgnoreImplicitAsWrittenSingleStep (Expr * E) inline
Definition at line 124 of file IgnoreExpr.h.
References IgnoreImplicitSingleStep().
Referenced by clang::Expr::IgnoreImplicitAsWritten().
IgnoreImplicitCastsExtraSingleStep()
Expr * clang::IgnoreImplicitCastsExtraSingleStep (Expr * E) inline
Definition at line 57 of file IgnoreExpr.h.
References IgnoreImplicitCastsSingleStep().
Referenced by clang::Expr::IgnoreParenImpCasts(), and clang::Expr::IgnoreUnlessSpelledInSource().
IgnoreImplicitCastsSingleStep()
Expr * clang::IgnoreImplicitCastsSingleStep (Expr * E) inline
Definition at line 47 of file IgnoreExpr.h.
Referenced by clang::Expr::IgnoreImpCasts(), IgnoreImplicitCastsExtraSingleStep(), and IgnoreImplicitSingleStep().
IgnoreImplicitSingleStep()
Expr * clang::IgnoreImplicitSingleStep (Expr * E) inline
Definition at line 110 of file IgnoreExpr.h.
References IgnoreImplicitCastsSingleStep().
Referenced by clang::Expr::IgnoreImplicit(), IgnoreImplicit(), IgnoreImplicitAsWrittenSingleStep(), and clang::Expr::IgnoreUnlessSpelledInSource().
IgnoreLValueCastsSingleStep()
Expr * clang::IgnoreLValueCastsSingleStep (Expr * E) inline
Definition at line 90 of file IgnoreExpr.h.
References IgnoreCastsSingleStep().
Referenced by clang::Expr::IgnoreParenLValueCasts().
IgnoreParensOnlySingleStep()
Expr * clang::IgnoreParensOnlySingleStep (Expr * E) inline
Definition at line 131 of file IgnoreExpr.h.
Referenced by clang::Expr::IgnoreUnlessSpelledInSource().
IgnoreParensSingleStep()
Expr * clang::IgnoreParensSingleStep (Expr * E) inline
Definition at line 137 of file IgnoreExpr.h.
Referenced by clang::Expr::IgnoreParenBaseCasts(), clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenImpCasts(), clang::Expr::IgnoreParenLValueCasts(), clang::Expr::IgnoreParenNoopCasts(), and clang::Expr::IgnoreParens().
Indent()
raw_ostream & clang::Indent (raw_ostream & Out, const unsigned int Space, bool IsDot) inline
Definition at line 20 of file JsonSupport.h.
inheritanceModelHasNVOffsetField()
bool clang::inheritanceModelHasNVOffsetField (bool IsMemberFunction, MSInheritanceModel Inheritance) inline
Definition at line 372 of file CXXInheritance.h.
References Multiple.
Referenced by getMSMemberPointerSlots().
inheritanceModelHasOnlyOneField()
bool clang::inheritanceModelHasOnlyOneField (bool IsMemberFunction, MSInheritanceModel Inheritance) inline
Definition at line 382 of file CXXInheritance.h.
References Multiple, and Single.
Referenced by clang::CXXRecordDecl::nullFieldOffsetIsZero().
inheritanceModelHasVBPtrOffsetField()
bool clang::inheritanceModelHasVBPtrOffsetField (MSInheritanceModel Inheritance) inline
Definition at line 366 of file CXXInheritance.h.
References Unspecified.
Referenced by getMSMemberPointerSlots().
inheritanceModelHasVBTableOffsetField()
bool clang::inheritanceModelHasVBTableOffsetField (MSInheritanceModel Inheritance) inline
Definition at line 378 of file CXXInheritance.h.
References Virtual.
Referenced by getMSMemberPointerSlots().
initialize()
template<class TemplateInstantiationCallbackPtrs > void clang::initialize (TemplateInstantiationCallbackPtrs & Callbacks, const Sema & TheSema)
Definition at line 43 of file TemplateInstCallback.h.
References C.
Referenced by ParseAST().
InitializePreprocessor()
void clang::InitializePreprocessor (Preprocessor & PP, const PreprocessorOptions & InitOpts, const PCHContainerReader & PCHContainerRdr, const FrontendOptions & FEOpts)
InitializePreprocessor - Initialize the preprocessor getting it and the environment ready to process a single file.
This returns true on error.
Definition at line 1144 of file InitPreprocessor.cpp.
References AddImplicitInclude(), AddImplicitIncludeMacros(), AddImplicitIncludePCH(), AddObjCXXARCLibstdcxxDefines(), ARCXX_libcxx, ARCXX_libstdcxx, ARCXX_nolib, DefineBuiltinMacro(), clang::Preprocessor::getAuxTargetInfo(), clang::Preprocessor::getDiagnostics(), clang::Preprocessor::getLangOpts(), clang::Preprocessor::getPreprocessorOpts(), clang::Preprocessor::getTargetInfo(), clang::PreprocessorOptions::ImplicitPCHInclude, clang::PreprocessorOptions::Includes, InitializePredefinedMacros(), InitializeStandardPredefinedMacros(), clang::PreprocessorOptions::MacroIncludes, clang::PreprocessorOptions::Macros, clang::PreprocessorOptions::ObjCXXARCStandardLibrary, clang::PreprocessorOptions::PrecompiledPreambleBytes, clang::Preprocessor::setPredefines(), clang::Preprocessor::setSkipMainFilePreamble(), and clang::PreprocessorOptions::UsePredefines.
Referenced by clang::CompilerInstance::createPreprocessor().
isa()
template<class U > bool clang::isa (CodeGen::Address addr) inline
Definition at line 111 of file Address.h.
Referenced by clang::Sema::ActOnAtEnd(), clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnCompoundStmt(), clang::Sema::ActOnCXXNestedNameSpecifier(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnNamespaceAliasDef(), clang::Sema::ActOnOpenMPDeclareSimdDirective(), clang::Sema::ActOnOpenMPTargetDirective(), clang::Sema::ActOnPragmaRedefineExtname(), clang::Sema::AddTemplateOverloadCandidate(), clang::Sema::adjustMemberFunctionCC(), adornObjCBoolConversionDiagWithTernaryFixit(), AnalyzeImplicitConversions(), clang::ento::StoreManager::attemptDownCast(), attemptRecovery(), clang::Sema::BuildCallToMemberFunction(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildVariableInstantiation(), canHideTag(), canPerformArrayCopy(), checkArithmeticNull(), checkAttributesAfterMerging(), CheckConstexprDeclStmt(), CheckConstexprFunctionBody(), clang::Sema::CheckConstexprFunctionDefinition(), CheckConstexprFunctionStmt(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::checkDeviceDecl(), clang::Sema::CheckExplicitlyDefaultedComparison(), clang::Sema::checkInitializerLifetime(), checkInitIsRequired(), CheckMemaccessSize(), checkMoreSpecializedThanPrimary(), clang::Sema::CheckNonDependentConversions(), CheckObjCCollectionLiteralElement(), clang::Sema::CheckObjCMethodDirectOverrides(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckTemplateArgumentList(), checkTemplatePartialSpecialization(), checkUndefinedButUsed(), clang::Sema::CheckUsingDeclRedeclaration(), clang::Sema::CheckUsingShadowDecl(), clang::Sema::checkVariadicArgument(), ClassifyConditional(), ClassifyDecl(), ClassifyImplicitMemberAccess(), ClassifyInternal(), clang::Sema::ClassifyName(), clang::Sema::CodeCompleteNamespaceDecl(), commonEmitCXXMemberOrOperatorCall(), computeShadowedDeclKind(), clang::driver::tools::Clang::ConstructJob(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::deduceClosureReturnType(), clang::Sema::deduceVarTypeFromInitializer(), clang::Sema::DiagnoseAlwaysNonNullPointer(), diagnoseDeprecatedCopyOperation(), clang::Sema::DiagnoseEmptyLookup(), clang::Sema::DiagnoseEmptyLoopBody(), DiagnoseFloatingImpCast(), DiagnoseIndirectOrAsmJumpStmt(), diagnoseInstanceReference(), DiagnoseObjCImplementedDeprecations(), diagnoseUncapturableValueReference(), DiagnoseUnimplementedAccessor(), clang::Sema::DiagnoseUseOfDecl(), clang::Decl::dropAttr(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::Sema::emitAndClearUnusedLocalTypedefWarnings(), EmitDiagForCXXThrowInNonThrowingFunc(), clang::CodeGen::CGDebugInfo::emitFunctionStart(), emitStoresForConstant(), endsWithReturn(), clang::Sema::FillInlineAsmIdentifierInfo(), clang::Sema::FinalizeDeclaration(), clang::Sema::FindInstantiatedDecl(), FormatFunctionParameter(), getAsTypeTemplateDecl(), GetFullTypeForDeclarator(), clang::TypeName::getFullyQualifiedType(), clang::NestedNameSpecifier::getKind(), clang::driver::Driver::GetNamedOutputPath(), clang::Sema::getShadowedDeclaration(), clang::Sema::getShadowedDeclaration(), clang::ASTContext::getTemplateSpecializationType(), clang::ento::MemRegionManager::getVarRegion(), hasCXXMangling(), hasDeclarator(), hasFunctionProto(), clang::ento::MemRegion::hasGlobalsOrParametersStorage(), hasImplicitExceptionSpec(), clang::ento::MemRegion::hasStackNonParametersStorage(), clang::ento::MemRegion::hasStackParametersStorage(), clang::ento::MemRegion::hasStackStorage(), clang::ASTNodeImporter::ImportDeclContext(), InNamespace(), clang::Type::isAggregateType(), clang::Type::isAnyComplexType(), clang::comments::Sema::isAnyFunctionDecl(), clang::Type::isArithmeticType(), clang::Type::isArrayType(), isASafeCallArg(), clang::Type::isAtomicType(), isBadDeallocationArgument(), isBetterOverloadCandidate(), clang::Type::isBlockPointerType(), clang::Type::isBuiltinType(), clang::ento::CallEvent::isCalled(), clang::ento::CallEvent::isCallStmt(), clang::QualType::isCanonicalAsParam(), clang::ClassTemplateSpecializationDecl::isClassScopeExplicitSpecialization(), clang::VarTemplateSpecializationDecl::isClassScopeExplicitSpecialization(), clang::comments::Sema::isClassTemplateDecl(), clang::CodeGen::CodeGenFunction::isCleanupPadScope(), clang::Type::isConstantArrayType(), clang::Type::isConstantMatrixType(), clang::Type::isConstantSizeType(), clang::VarDecl::isConstexpr(), clang::interp::Function::isConstructor(), isConstructor(), clang::ParentMap::isConsumedExpr(), clang::TemplateSpecializationType::isCurrentInstantiation(), clang::VarDecl::isCXXForRangeDecl(), isDeclADefinition(), clang::Type::isDecltypeType(), clang::Expr::isDefaultArgument(), isDeletingDtor(), clang::Type::isDependentAddressSpaceType(), clang::Type::isDependentSizedArrayType(), isEnumConstant(), isEnumConstant(), clang::Type::isEnumeralType(), clang::VarDecl::isExceptionVariable(), clang::ento::nonloc::SymbolVal::isExpression(), clang::Type::isExtIntType(), clang::Type::isExtVectorType(), isFunctionLikeDeclaration(), isFunctionOrMethod(), isFunctionOrMethodOrBlock(), clang::comments::Sema::isFunctionTemplateDecl(), clang::Type::isFunctionType(), IsGlobalLValue(), clang::Sema::isImplicitlyDeleted(), clang::Sema::isIncompatibleTypedef(), clang::Type::isIncompleteArrayType(), clang::VarDecl::isInitCapture(), clang::VarDecl::isInline(), clang::VarDecl::isInlineSpecified(), IsIntegerLiteralConstantExpr(), clang::ento::ExplodedGraph::isInterestingLValueExpr(), clang::threadSafety::CapabilityExpr::isInvalid(), isLibstdcxxPointerReturnFalseHack(), IsLiteralLValue(), clang::ento::isLoopStmt(), clang::Type::isLValueReferenceType(), clang::Type::isMatrixType(), clang::Type::isMemberPointerType(), isMSPropertySubscriptExpr(), clang::VarDecl::isNRVOVariable(), isNumericLiteralExpression(), clang::IfStmt::isObjCAvailabilityCheck(), clang::comments::Sema::isObjCInterfaceDecl(), clang::comments::Sema::isObjCMethodDecl(), clang::Sema::isObjCMethodDecl(), clang::Type::isObjCObjectOrInterfaceType(), clang::Type::isObjCObjectPointerType(), clang::Type::isObjCObjectType(), clang::comments::Sema::isObjCProtocolDecl(), clang::Sema::isOpenMPCapturedByRef(), clang::TemplateArgument::isPackExpansion(), clang::VarDecl::isParameterPack(), clang::Type::isPipeType(), clang::Type::isPointerType(), clang::ento::isPossiblyEscaped(), isPreferredLookupResult(), clang::VarDecl::isPreviousDeclInSameBlockScope(), isProvablyNull(), clang::Type::isRecordType(), clang::Type::isReferenceType(), clang::Type::isRValueReferenceType(), clang::Type::isScalarType(), isSelfDecl(), clang::LookupResult::isSingleTagDecl(), clang::InitListExpr::isStringLiteralInit(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), clang::Decl::isTemplateDecl(), clang::index::IndexingContext::isTemplateImplicitInstantiation(), clang::Sema::isTemplateName(), clang::Type::isTemplateTypeParmType(), clang::VarDecl::isThisDeclarationADemotedDefinition(), isTrivialExpression(), clang::ConceptDecl::isTypeConcept(), clang::Type::isUndeducedAutoType(), clang::threadSafety::CapabilityExpr::isUniversal(), isUsingDecl(), clang::Type::isVariableArrayType(), isVariableCapturable(), clang::Type::isVectorType(), clang::MangleContext::mangleBlock(), clang::threadSafety::sx::matches(), MatchTemplateParameterKind(), matchTypes(), clang::ASTContext::mayExternalizeStaticVar(), clang::Sema::mergeDeclAttributes(), clang::Sema::mergeObjCMethodDecls(), clang::serialization::needsAnonymousDeclarationNumber(), clang::Sema::NoteAllFoundTemplates(), clang::BinaryOperator::offsetOfTrailingStorage(), clang::Sema::PrintInstantiationStack(), pushTemporaryCleanup(), refersToCompleteObject(), clang::tooling::replaceNestedName(), requiresAMDGPUProtectedVisibility(), requiresMemberFunctionPointerTypeMetadata(), clang::Sema::setTagNameForLinkagePurposes(), shouldSkipNamelessDecl(), clang::TreeTransform< Derived >::TransformOverloadExprDecls(), TryDiagnoseProtectedAccess(), tryTransformToIntOrEnumConstant(), usesTypeVisibility(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::tooling::RecursiveSymbolVisitor< T >::VisitNamedDecl().
isAlphanumeric()
LLVM_READONLY bool clang::isAlphanumeric (unsigned char c) inline
Return true if this character is an ASCII letter or digit: [a-zA-Z0-9].
Definition at line 117 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::format::BreakableLineCommentSection::BreakableLineCommentSection(), checkVerifyPrefixes(), clang::CompilerInstance::createModuleFromSource(), and clang::format::getStringSplit().
IsAMDGpuArch()
static bool clang::IsAMDGpuArch (CudaArch A) inline static
Definition at line 93 of file Cuda.h.
References GFX600, and LAST.
Referenced by MaxVersionForCudaArch(), and MinVersionForCudaArch().
isASafeCallArg()
bool clang::isASafeCallArg (const clang::Expr * E)
For E referring to a ref-countable/-counted pointer/reference we return whether it's a safe call argument.
Examples: function parameter or this-pointer. The logic relies on the set of recursive rules we enforce for WebKit codebase.
Returns
Whether E is a safe call arugment.
Definition at line 82 of file ASTUtils.cpp.
References isa().
isASCII()
LLVM_READNONE bool clang::isASCII (char c) inline
Returns true if this is an ASCII character.
Definition at line 42 of file CharInfo.h.
References c.
Referenced by consumeWhitespace(), clang::StringLiteral::containsNonAscii(), clang::StringLiteral::containsNonAsciiOrNull(), and parseId().
isBetterOverloadCandidate()
bool clang::isBetterOverloadCandidate (Sema & S, const OverloadCandidate & Cand1, const OverloadCandidate & Cand2, SourceLocation Loc, OverloadCandidateSet::CandidateSetKind Kind)
isBetterOverloadCandidate - Determines whether the first overload candidate is a better candidate than the second (C++ 13.3.3p1).
Definition at line 9539 of file SemaOverload.cpp.
References clang::ImplicitConversionSequence::Better, cast(), clang::Sema::CFP_Never, clang::Sema::CFP_WrongSide, compareConversionFunctions(), compareEnableIfAttrs(), CompareImplicitConversionSequences(), CompareStandardConversionSequences(), clang::Sema::Context, clang::OverloadCandidate::Conversions, clang::OverloadCandidateSet::CSK_InitByConstructor, clang::OverloadCandidateSet::CSK_InitByUserDefinedConversion, clang::Sema::CurContext, clang::OverloadCandidate::ExplicitCallArguments, clang::OverloadCandidate::FinalConversion, clang::OverloadCandidate::FoundDecl, clang::OverloadCandidate::Function, functionHasPassObjectSizeParams(), clang::Sema::FunctionParamTypesAreEqual(), clang::DeclAccessPair::getDecl(), clang::Decl::getDeclContext(), clang::Decl::getFunctionType(), clang::Sema::getLangOpts(), clang::Sema::getMoreSpecializedTemplate(), clang::FunctionDecl::getPrimaryTemplate(), clang::DeclaratorDecl::getTrailingRequiresClause(), hasDeprecatedStringLiteralToCharPtrConversion(), clang::FunctionDecl::hasPrototype(), haveSameParameterTypes(), ICK_Incompatible_Pointer_Conversion, clang::Sema::IdentifyCUDAPreference(), clang::OverloadCandidate::IgnoreObjectArgument, clang::ImplicitConversionSequence::Indistinguishable, isa(), clang::Sema::IsAtLeastAsConstrained(), isBetterMultiversionCandidate(), clang::Sema::isCUDAImplicitHostDeviceFunction(), clang::OverloadCandidate::isReversed(), Result, clang::OverloadCandidate::RewriteKind, TPOC_Call, TPOC_Conversion, clang::OverloadCandidate::Viable, and clang::ImplicitConversionSequence::Worse.
Referenced by clang::OverloadCandidateSet::BestViableFunction(), and mergeCandidatesWithResults().
isCompoundAssignmentOperator()
bool clang::isCompoundAssignmentOperator (OverloadedOperatorKind Kind) inline
Determine if this is a compound assignment operator.
Definition at line 53 of file OperatorKinds.h.
Referenced by implicitObjectParamIsLifetimeBound().
isComputedNoexcept()
bool clang::isComputedNoexcept (ExceptionSpecificationType ESpecType) inline
Definition at line 39 of file ExceptionSpecificationType.h.
References EST_DependentNoexcept, and EST_NoexceptTrue.
Referenced by clang::Sema::checkExceptionSpecification(), clang::Sema::containsUnexpandedParameterPacks(), clang::FunctionProtoType::getExceptionSpecInfo(), clang::Sema::ImplicitExceptionSpecification::getExceptionSpecType(), GetFullTypeForDeclarator(), clang::FunctionProtoType::getNoexceptExpr(), IsEquivalentExceptionSpec(), isNoexceptExceptionSpec(), clang::FunctionProtoType::printExceptionSpecification(), and clang::TreeTransform< Derived >::TransformExceptionSpec().
isCtorOfRefCounted()
bool clang::isCtorOfRefCounted (const clang::FunctionDecl * F)
Returns
true if F creates ref-countable object from uncounted parameter, false if not.
Definition at line 98 of file PtrTypesSemantics.cpp.
References safeGetName().
Referenced by isPtrConversion(), and tryToFindPtrOrigin().
isDigit()
LLVM_READONLY bool clang::isDigit (unsigned char c) inline
Return true if this character is an ASCII digit: [0-9].
Definition at line 93 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::GCCAsmStmt::AnalyzeAsmString(), clang::TokenConcatenation::AvoidConcat(), clang::Diagnostic::FormatDiagnostic(), getExtensionFeatures(), getExtensionVersion(), GetLineValue(), clang::TargetInfo::getNormalizedGCCRegisterName(), getSystemRegistryString(), clang::comments::isHTMLDecimalCharacterReferenceCharacter(), clang::TargetInfo::isValidGCCRegisterName(), clang::LayoutOverrideSource::LayoutOverrideSource(), sanitizeFilenameAsIdentifier(), and ScanFormat().
isDiscardableGVALinkage()
bool clang::isDiscardableGVALinkage (GVALinkage L) inline
Definition at line 81 of file Linkage.h.
References GVA_DiscardableODR.
Referenced by clang::ASTContext::DeclMustBeEmitted(), and clang::Sema::getEmissionStatus().
isDynamicExceptionSpec()
bool clang::isDynamicExceptionSpec (ExceptionSpecificationType ESpecType) inline
Definition at line 35 of file ExceptionSpecificationType.h.
References EST_DynamicNone, and EST_MSAny.
Referenced by clang::FunctionProtoType::hasDynamicExceptionSpec().
IsEnumDeclComplete()
bool clang::IsEnumDeclComplete (EnumDecl * ED) inline
Check if the given decl is complete.
We use this function to break a cycle between the inline definitions in Type.h and Decl.h.
Definition at line 4583 of file Decl.h.
References clang::EnumDecl::isComplete().
Referenced by clang::Type::isIntegerType(), clang::Type::isIntegralOrEnumerationType(), and clang::Type::isScalarType().
IsEnumDeclScoped()
bool clang::IsEnumDeclScoped (EnumDecl * ED) inline
Check if the given decl is scoped.
We use this function to break a cycle between the inline definitions in Type.h and Decl.h.
Definition at line 4591 of file Decl.h.
References clang::EnumDecl::isScoped().
Referenced by clang::Type::isIntegerType().
isExternalFormalLinkage()
bool clang::isExternalFormalLinkage (Linkage L) inline
Definition at line 108 of file Linkage.h.
References ExternalLinkage, and getFormalLinkage().
Referenced by clang::NamedDecl::hasExternalFormalLinkage(), and clang::Sema::isExternalWithNoLinkageType().
isExternallyVisible()
bool clang::isExternallyVisible (Linkage L) inline
Definition at line 91 of file Linkage.h.
References VisibleNoLinkage.
Referenced by clang::Sema::checkClassLevelDLLAttribute(), checkUndefinedButUsed(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::NamedDecl::isExternallyVisible(), clang::LinkageInfo::mergeExternalVisibility(), and setLinkageForGV().
isGenericLambdaCallOperatorOrStaticInvokerSpecialization()
bool clang::isGenericLambdaCallOperatorOrStaticInvokerSpecialization (DeclContext * DC) inline
Definition at line 67 of file ASTLambda.h.
References clang::CXXMethodDecl::getParent(), clang::FunctionDecl::isFunctionTemplateSpecialization(), clang::CXXRecordDecl::isGenericLambda(), isLambdaCallOperator(), and clang::CXXMethodDecl::isLambdaStaticInvoker().
Referenced by clang::Sema::getTemplateInstantiationArgs().
isGenericLambdaCallOperatorSpecialization() [1/2]
bool clang::isGenericLambdaCallOperatorSpecialization (const CXXMethodDecl * MD) inline
Definition at line 38 of file ASTLambda.h.
References clang::CXXMethodDecl::getParent(), clang::FunctionDecl::isFunctionTemplateSpecialization(), clang::CXXRecordDecl::isGenericLambda(), and isLambdaCallOperator().
Referenced by clang::Sema::ActOnStartOfFunctionDef(), adjustCVQualifiersForCXXThisWithinLambda(), clang::Sema::CheckCXXThisCapture(), clang::FunctionDecl::getTemplateInstantiationPattern(), isGenericLambdaCallOperatorSpecialization(), and clang::Sema::tryCaptureVariable().
isGenericLambdaCallOperatorSpecialization() [2/2]
bool clang::isGenericLambdaCallOperatorSpecialization (DeclContext * DC) inline
Definition at line 62 of file ASTLambda.h.
References isGenericLambdaCallOperatorSpecialization().
isGetterOfRefCounted()
llvm::Optional< bool > clang::isGetterOfRefCounted (const clang::CXXMethodDecl * Method)
Returns
true if M is getter of a ref-counted class, false if not.
Definition at line 138 of file PtrTypesSemantics.cpp.
References clang::CXXMethodDecl::getParent(), isUncountedPtr(), and safeGetName().
Referenced by tryToFindPtrOrigin().
isHexDigit()
LLVM_READONLY bool clang::isHexDigit (unsigned char c) inline
Return true if this character is an ASCII hex digit: [0-9a-fA-F].
Definition at line 123 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::comments::isHTMLHexCharacterReferenceCharacter(), ProcessCharEscape(), and ProcessUCNEscape().
isHorizontalWhitespace()
LLVM_READONLY bool clang::isHorizontalWhitespace (unsigned char c) inline
Returns true if this character is horizontal ASCII whitespace: ' ', '\t', '\f', '\v'.
Note that this returns false for '\0'.
Definition at line 70 of file CharInfo.h.
References c, and InfoTable.
Referenced by findFirstTrailingSpace(), findLastNonSpace(), clang::Lexer::findLocationAfterToken(), isEndOfBlockCommentWithEscapedNewLine(), clang::Lexer::isNewLineEscaped(), onlyWhitespaceOnLineBefore(), skipOverSpaces(), and skipWhitespaceAndNewline().
isIdentifierBody()
LLVM_READONLY bool clang::isIdentifierBody (unsigned char c, bool AllowDollar = false) inline
Returns true if this is a body character of a C identifier, which is [a-zA-Z0-9_].
Definition at line 58 of file CharInfo.h.
References c, and InfoTable.
Referenced by fixItNullability(), getIdentifierContinuation(), clang::Lexer::isIdentifierBodyChar(), isQuoteCppDigitSeparator(), isRawStringLiteral(), isValidIdentifier(), lexRawIdentifier(), parseId(), parseName(), and sanitizeFilenameAsIdentifier().
isIdentifierHead()
LLVM_READONLY bool clang::isIdentifierHead (unsigned char c, bool AllowDollar = false) inline
Returns true if this is a valid first character of a C identifier, which is [a-zA-Z_].
Definition at line 48 of file CharInfo.h.
References c, and InfoTable.
Referenced by IsValidIdentifier(), isValidIdentifier(), and parseName().
isLambdaCallOperator() [1/2]
bool clang::isLambdaCallOperator (const CXXMethodDecl * MD) inline
Definition at line 27 of file ASTLambda.h.
References clang::FunctionDecl::getOverloadedOperator(), clang::CXXMethodDecl::getParent(), and clang::CXXRecordDecl::isLambda().
Referenced by clang::Sema::ActOnFinishFullExpr(), clang::Sema::ActOnFinishFunctionBody(), clang::Sema::ActOnStartOfFunctionDef(), adjustCVQualifiersForCXXThisWithinLambda(), clang::Sema::buildCoroutinePromise(), clang::Sema::CheckShadow(), evaluateVarDeclInit(), FormatASTNodeDiagnosticArgument(), clang::Sema::getCurrentThisType(), getLambdaAwareParentOfDeclContext(), clang::DeclContext::getLookupParent(), getParentOfCapturingContextOrNull(), getStackIndexOfNearestEnclosingCaptureReadyLambda(), HandleFunctionCall(), isGenericLambdaCallOperatorOrStaticInvokerSpecialization(), isGenericLambdaCallOperatorSpecialization(), and isLambdaCallOperator().
isLambdaCallOperator() [2/2]
bool clang::isLambdaCallOperator (const DeclContext * DC) inline
Definition at line 33 of file ASTLambda.h.
References isLambdaCallOperator().
isLambdaConversionOperator() [1/2]
bool clang::isLambdaConversionOperator (CXXConversionDecl * C) inline
Definition at line 47 of file ASTLambda.h.
References C.
Referenced by clang::Sema::DeduceFunctionTypeFromReturnExpr(), clang::Sema::DeduceReturnType(), and isLambdaConversionOperator().
isLambdaConversionOperator() [2/2]
bool clang::isLambdaConversionOperator (Decl * D) inline
Definition at line 51 of file ASTLambda.h.
References isLambdaConversionOperator().
isLegalForFunction()
bool clang::isLegalForFunction (StorageClass SC) inline
Checks whether the given storage class is legal for functions.
Definition at line 236 of file Specifiers.h.
References SC_PrivateExtern.
isLegalForVariable()
bool clang::isLegalForVariable (StorageClass SC) inline
Checks whether the given storage class is legal for variables.
Definition at line 241 of file Specifiers.h.
Referenced by clang::VarDecl::setStorageClass().
isLetter()
LLVM_READONLY bool clang::isLetter (unsigned char c) inline
Return true if this character is an ASCII letter: [a-zA-Z].
Definition at line 111 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::GCCAsmStmt::AnalyzeAsmString(), checkVerifyPrefixes(), clang::ento::coreFoundation::followsCreateRule(), clang::GCCAsmStmt::AsmStringPiece::getModifier(), and clang::comments::isHTMLNamedCharacterReferenceCharacter().
isLowercase()
LLVM_READONLY bool clang::isLowercase (unsigned char c) inline
Return true if this character is a lowercase ASCII letter: [a-z].
Definition at line 99 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::ento::coreFoundation::followsCreateRule(), isSetterLikeSelector(), startsWithWord(), and toUppercase().
isNoexceptExceptionSpec()
bool clang::isNoexceptExceptionSpec (ExceptionSpecificationType ESpecType) inline
Definition at line 44 of file ExceptionSpecificationType.h.
References EST_BasicNoexcept, EST_NoThrow, and isComputedNoexcept().
Referenced by clang::FunctionProtoType::hasNoexceptExceptionSpec(), memberCallExpressionCanThrow(), and clang::FunctionProtoType::printExceptionSpecification().
IsNVIDIAGpuArch()
static bool clang::IsNVIDIAGpuArch (CudaArch A) inline static
Definition at line 89 of file Cuda.h.
References GFX600, and SM_20.
Referenced by clang::driver::CudaInstallationDetector::CudaInstallationDetector().
isOpenMPDistributeDirective()
bool clang::isOpenMPDistributeDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a distribute directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a distribute-directive like 'omp distribute', otherwise - false.
Definition at line 541 of file OpenMPKinds.cpp.
References isOpenMPNestingDistributeDirective().
Referenced by clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLoopInitialization(), checkNestingOfRegions(), checkOpenMPIterationSpace(), checkOpenMPLoop(), clang::CodeGen::CGOpenMPRuntime::emitForStaticFinish(), emitNumThreadsForTargetDirective(), emitOMPSimdRegion(), FinishOpenMPLinearClause(), clang::OMPLoopDirective::getArraysOffset(), getDistributeLastprivateVars(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getLowerBoundVariable(), getNestedDistributeDirective(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getStrideVariable(), clang::OMPLoopDirective::getUpperBoundVariable(), clang::Parser::ParseOpenMPVarList(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setStrideVariable(), and clang::OMPLoopDirective::setUpperBoundVariable().
isOpenMPLoopBoundSharingDirective()
bool clang::isOpenMPLoopBoundSharingDirective (OpenMPDirectiveKind Kind)
Checks if the specified directive kind is one of the composite or combined directives that need loop bound sharing across loops outlined in nested functions.
Definition at line 567 of file OpenMPKinds.cpp.
Referenced by checkOpenMPLoop(), clang::OMPLoopDirective::getArraysOffset(), clang::OMPLoopDirective::getCombinedCond(), clang::OMPLoopDirective::getCombinedDistCond(), clang::OMPLoopDirective::getCombinedEnsureUpperBound(), clang::OMPLoopDirective::getCombinedInit(), clang::OMPLoopDirective::getCombinedLowerBoundVariable(), clang::OMPLoopDirective::getCombinedNextLowerBound(), clang::OMPLoopDirective::getCombinedNextUpperBound(), clang::OMPLoopDirective::getCombinedParForInDistCond(), clang::OMPLoopDirective::getCombinedUpperBoundVariable(), clang::OMPLoopDirective::getDistInc(), clang::OMPLoopDirective::getPrevEnsureUpperBound(), clang::OMPLoopDirective::getPrevLowerBoundVariable(), clang::OMPLoopDirective::getPrevUpperBoundVariable(), clang::OMPLoopDirective::setCombinedCond(), clang::OMPLoopDirective::setCombinedDistCond(), clang::OMPLoopDirective::setCombinedEnsureUpperBound(), clang::OMPLoopDirective::setCombinedInit(), clang::OMPLoopDirective::setCombinedLowerBoundVariable(), clang::OMPLoopDirective::setCombinedNextLowerBound(), clang::OMPLoopDirective::setCombinedNextUpperBound(), clang::OMPLoopDirective::setCombinedParForInDistCond(), clang::OMPLoopDirective::setCombinedUpperBoundVariable(), clang::OMPLoopDirective::setDistInc(), clang::OMPLoopDirective::setPrevEnsureUpperBound(), clang::OMPLoopDirective::setPrevLowerBoundVariable(), and clang::OMPLoopDirective::setPrevUpperBoundVariable().
isOpenMPLoopDirective()
bool clang::isOpenMPLoopDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a directive with an associated loop construct.
Parameters
DKind Specified directive.
Returns
true - the directive is a loop-associated directive like 'omp simd' or 'omp for' directive, otherwise - false.
Definition at line 430 of file OpenMPKinds.cpp.
Referenced by clang::Sema::ActOnOpenMPLoopInitialization(), checkOpenMPIterationSpace(), clang::CodeGen::CGOpenMPRuntime::emitForStaticFinish(), clang::CodeGen::CGOpenMPRuntime::emitForStaticInit(), hasNestedLightweightDirective(), hasStaticScheduling(), clang::Sema::isOpenMPPrivateDecl(), clang::Sema::startOpenMPCXXRangeFor(), and clang::Sema::startOpenMPLoop().
isOpenMPNestingDistributeDirective()
bool clang::isOpenMPNestingDistributeDirective (OpenMPDirectiveKind DKind)
Checks if the specified composite/combined directive constitutes a distribute directive in the outermost nest.
For example, 'omp distribute parallel for' or 'omp distribute'.
Parameters
DKind Specified directive.
Returns
true - the directive has distribute on the outermost nest. otherwise - false.
Definition at line 534 of file OpenMPKinds.cpp.
Referenced by checkNestingOfRegions(), and isOpenMPDistributeDirective().
isOpenMPNestingTeamsDirective()
bool clang::isOpenMPNestingTeamsDirective (OpenMPDirectiveKind DKind)
Checks if the specified composite/combined directive constitutes a teams directive in the outermost nest.
For example 'omp teams distribute' or 'omp teams distribute parallel for'.
Parameters
DKind Specified directive.
Returns
true - the directive has teams on the outermost nest, otherwise - false.
Definition at line 505 of file OpenMPKinds.cpp.
Referenced by checkNestingOfRegions(), and isOpenMPTeamsDirective().
isOpenMPParallelDirective()
bool clang::isOpenMPParallelDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a parallel-kind directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a parallel-like directive like 'omp parallel', otherwise - false.
Definition at line 474 of file OpenMPKinds.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), checkNestingOfRegions(), checkReductionClauses(), emitNumTeamsForTargetDirective(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), getNumThreads(), hasNestedLightweightDirective(), and hasNestedSPMDDirective().
isOpenMPPrivate()
bool clang::isOpenMPPrivate (OpenMPClauseKind Kind)
Checks if the specified clause is one of private clauses like 'private', 'firstprivate', 'reduction' etc.
Parameters
Kind Clause kind.
Returns
true - the clause is a private clause, otherwise - false.
Definition at line 552 of file OpenMPKinds.cpp.
Referenced by clang::Sema::ActOnOpenMPIsDevicePtrClause(), clang::Sema::ActOnOpenMPRegionEnd(), checkAllocateClauses(), checkMappableExpressionList(), and clang::Sema::isOpenMPCapturedDecl().
isOpenMPSimdDirective()
bool clang::isOpenMPSimdDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a simd directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a simd directive like 'omp simd', otherwise - false.
Definition at line 520 of file OpenMPKinds.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPLoopInitialization(), clang::Sema::ActOnOpenMPOrderedDirective(), clang::Sema::ActOnOpenMPRegionEnd(), checkNestingOfRegions(), checkReductionClauses(), emitCommonSimdLoop(), emitInnerParallelForWhenCombined(), emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), emitOMPSimdRegion(), FinishOpenMPLinearClause(), getNumThreads(), and clang::Sema::isOpenMPPrivateDecl().
isOpenMPTargetDataManagementDirective()
bool clang::isOpenMPTargetDataManagementDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a target data offload directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a target data offload directive like 'omp target data', 'omp target update', 'omp target enter data', 'omp target exit data' otherwise - false.
Definition at line 500 of file OpenMPKinds.cpp.
Referenced by clang::Sema::ActOnOpenMPExecutableDirective(), checkNestingOfRegions(), emitPrivatesInit(), and clang::Sema::tryCaptureOpenMPLambdas().
isOpenMPTargetExecutionDirective()
bool clang::isOpenMPTargetExecutionDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a target code offload directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a target code offload directive like 'omp target', 'omp target parallel', 'omp target xxx' otherwise - false.
Definition at line 490 of file OpenMPKinds.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::CodeGen::CGOpenMPRuntime::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), checkAllocateClauses(), checkMappableExpressionList(), checkNestingOfRegions(), emitCommonOMPTargetDirective(), emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), emitOMPSimdRegion(), emitPrivatesInit(), emitTargetParallelRegion(), emitTargetRegion(), emitTargetTeamsRegion(), clang::Sema::isInOpenMPTargetExecutionDirective(), clang::Sema::isOpenMPCapturedByRef(), clang::Sema::isOpenMPPrivateDecl(), clang::Sema::isOpenMPTargetCapturedDecl(), clang::Sema::setOpenMPCaptureKind(), and clang::Sema::tryCaptureOpenMPLambdas().
isOpenMPTaskingDirective()
bool clang::isOpenMPTaskingDirective (OpenMPDirectiveKind Kind)
Checks if the specified directive kind is one of tasking directives - task, taskloop, taksloop simd, master taskloop, parallel master taskloop, master taskloop simd, or parallel master taskloop simd.
Definition at line 563 of file OpenMPKinds.cpp.
References isOpenMPTaskLoopDirective().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::ActOnOpenMPRegionEnd(), checkAllocateClauses(), checkNestingOfRegions(), clang::Sema::isOpenMPPrivateDecl(), and reportOriginalDsa().
isOpenMPTaskLoopDirective()
bool clang::isOpenMPTaskLoopDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a taskloop directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a worksharing directive like 'omp taskloop', otherwise - false.
Definition at line 467 of file OpenMPKinds.cpp.
Referenced by clang::Sema::ActOnOpenMPExecutableDirective(), checkOpenMPIterationSpace(), checkOpenMPLoop(), createKmpTaskTRecordDecl(), emitOMPSimdRegion(), emitPrivatesInit(), emitProxyTaskFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), clang::OMPLoopDirective::getArraysOffset(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getLowerBoundVariable(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getStrideVariable(), clang::OMPLoopDirective::getUpperBoundVariable(), clang::Sema::isOpenMPPrivateDecl(), isOpenMPTaskingDirective(), clang::Parser::ParseOpenMPVarList(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setStrideVariable(), and clang::OMPLoopDirective::setUpperBoundVariable().
isOpenMPTeamsDirective()
bool clang::isOpenMPTeamsDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a teams-kind directive.
For example, 'omp teams distribute' or 'omp target teams'.
Parameters
DKind Specified directive.
Returns
true - the directive is a teams-like directive, otherwise - false.
Definition at line 512 of file OpenMPKinds.cpp.
References isOpenMPNestingTeamsDirective().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPTargetDirective(), checkNestingOfRegions(), emitNumTeamsForTargetDirective(), emitNumThreadsForTargetDirective(), clang::CodeGen::CGOpenMPRuntimeGPU::emitReduction(), getDistributeLastprivateVars(), and getTeamsReductionVars().
isOpenMPThreadPrivate()
bool clang::isOpenMPThreadPrivate (OpenMPClauseKind Kind)
Checks if the specified clause is one of threadprivate clauses like 'threadprivate', 'copyin' or 'copyprivate'.
Parameters
Kind Clause kind.
Returns
true - the clause is a threadprivate clause, otherwise - false.
Definition at line 559 of file OpenMPKinds.cpp.
Referenced by clang::Sema::isOpenMPCapturedDecl().
isOpenMPWorksharingDirective()
bool clang::isOpenMPWorksharingDirective (OpenMPDirectiveKind DKind)
Checks if the specified directive is a worksharing directive.
Parameters
DKind Specified directive.
Returns
true - the directive is a worksharing directive like 'omp for', otherwise - false.
Definition at line 452 of file OpenMPKinds.cpp.
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLoopInitialization(), clang::Sema::ActOnOpenMPRegionEnd(), checkNestingOfRegions(), checkOpenMPIterationSpace(), checkOpenMPLoop(), checkReductionClauses(), clang::CodeGen::CGOpenMPRuntime::emitForStaticInit(), emitOMPSimdRegion(), clang::OMPLoopDirective::getArraysOffset(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getLowerBoundVariable(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getStrideVariable(), clang::OMPLoopDirective::getUpperBoundVariable(), hasNestedLightweightDirective(), hasStaticScheduling(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setStrideVariable(), and clang::OMPLoopDirective::setUpperBoundVariable().
isPreprocessingNumberBody()
LLVM_READONLY bool clang::isPreprocessingNumberBody (unsigned char c) inline
Return true if this is the body character of a C preprocessing number, which is [a-zA-Z0-9_.
].
Definition at line 147 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::TokenConcatenation::AvoidConcat(), getTransformedFileName(), isQuoteCppDigitSeparator(), and clang::NumericLiteralParser::NumericLiteralParser().
isPrintable()
LLVM_READONLY bool clang::isPrintable (unsigned char c) inline
Return true if this character is an ASCII printable character; that is, a character that should take exactly one column to print in a fixed-width terminal.
Definition at line 139 of file CharInfo.h.
References c, and InfoTable.
Referenced by outputPrintable(), clang::StringLiteral::outputString(), and ProcessCharEscape().
isPtrConversion()
bool clang::isPtrConversion (const FunctionDecl * F)
Returns
true if F is a conversion between ref-countable or ref-counted pointer types.
Definition at line 178 of file PtrTypesSemantics.cpp.
References isCtorOfRefCounted(), and safeGetName().
Referenced by tryToFindPtrOrigin().
isPtrSizeAddressSpace()
bool clang::isPtrSizeAddressSpace (LangAS AS) inline
Definition at line 78 of file AddressSpaces.h.
References ptr32_sptr, ptr32_uptr, and ptr64.
Referenced by clang::Qualifiers::isAddressSpaceSupersetOf(), and clang::ASTContext::removePtrSizeAddrSpace().
isPunctuation()
LLVM_READONLY bool clang::isPunctuation (unsigned char c) inline
Return true if this character is an ASCII punctuation character.
Note that '_' is both a punctuation character and an identifier character!
Definition at line 131 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::Diagnostic::FormatDiagnostic(), clang::format::mayReflowContent(), and ScanFormat().
isRawStringDelimBody()
LLVM_READONLY bool clang::isRawStringDelimBody (unsigned char c) inline
Return true if this is the body character of a C++ raw string delimiter.
Definition at line 154 of file CharInfo.h.
References c, and InfoTable.
isRefCountable() [1/2]
llvm::Optional< const clang::CXXRecordDecl * > clang::isRefCountable (const clang::CXXBaseSpecifier * Base)
Returns
CXXRecordDecl of the base if the type is ref-countable, nullptr if not, None if inconclusive.
Definition at line 49 of file PtrTypesSemantics.cpp.
References clang::CXXRecordDecl::hasDefinition().
Referenced by isRefCountable(), and isUncounted().
isRefCountable() [2/2]
llvm::Optional< bool > clang::isRefCountable (const clang::CXXRecordDecl * Class)
Returns
true if Class is ref-countable, false if not, None if inconclusive.
Definition at line 65 of file PtrTypesSemantics.cpp.
References clang::CXXRecordDecl::getDefinition(), isRefCountable(), and clang::CXXRecordDecl::lookupInBases().
isRefCounted()
bool clang::isRefCounted (const clang::CXXRecordDecl * Class)
Returns
true if Class is ref-counted, false if not.
Definition at line 168 of file PtrTypesSemantics.cpp.
References clang::CXXRecordDecl::getTemplateInstantiationPattern(), and safeGetName().
Referenced by isUncounted().
isStackNearlyExhausted()
bool clang::isStackNearlyExhausted ()
Determine whether the stack is nearly exhausted.
Definition at line 46 of file Stack.cpp.
References std::abs(), BottomOfStack, DesiredStackSize, and getStackPointer().
Referenced by clang::Sema::pushCodeSynthesisContext(), and runWithSufficientStackSpace().
isTargetAddressSpace()
bool clang::isTargetAddressSpace (LangAS AS) inline
Returns
whether AS is a target-specific address space rather than a clang AST address space
Definition at line 64 of file AddressSpaces.h.
References FirstTargetAddressSpace.
Referenced by clang::ASTContext::addressSpaceMapManglingFor(), CheckForNullPointerDereference(), DeduceTemplateArgumentsByTypeMatch(), clang::ASTContext::getTargetAddressSpace(), clang::Qualifiers::hasTargetSpecificAddressSpace(), clang::Qualifiers::print(), and toTargetAddressSpace().
isTemplateExplicitInstantiationOrSpecialization()
bool clang::isTemplateExplicitInstantiationOrSpecialization (TemplateSpecializationKind Kind) inline
True if this template specialization kind is an explicit specialization, explicit instantiation declaration, or explicit instantiation definition.
Definition at line 194 of file Specifiers.h.
References TSK_ExplicitInstantiationDeclaration, TSK_ExplicitInstantiationDefinition, TSK_ExplicitSpecialization, TSK_ImplicitInstantiation, and TSK_Undeclared.
Referenced by clang::ClassTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), clang::FunctionTemplateSpecializationInfo::isExplicitInstantiationOrSpecialization(), and clang::VarTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization().
isTemplateInstantiation()
bool clang::isTemplateInstantiation (TemplateSpecializationKind Kind) inline
Determine whether this template specialization kind refers to an instantiation of an entity (as opposed to a non-template or an explicit specialization).
Definition at line 187 of file Specifiers.h.
References TSK_ExplicitSpecialization, and TSK_Undeclared.
Referenced by clang::Sema::AddInitializerToDecl(), clang::Sema::BuildCXXDefaultInitExpr(), clang::Sema::CheckCompleteVariableDeclaration(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::completeExprArrayBound(), DoMarkVarDeclReferenced(), clang::ClassTemplateSpecializationDecl::getInstantiatedFrom(), clang::VarTemplateSpecializationDecl::getInstantiatedFrom(), clang::CXXRecordDecl::getTemplateInstantiationPattern(), clang::EnumDecl::getTemplateInstantiationPattern(), clang::FunctionDecl::getTemplateInstantiationPattern(), clang::VarDecl::getTemplateInstantiationPattern(), clang::serialization::isPartOfPerModuleInitializer(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), and clang::FunctionDecl::isTemplateInstantiation().
isUncounted()
llvm::Optional< bool > clang::isUncounted (const clang::CXXRecordDecl * Class)
Returns
true if Class is ref-countable AND not ref-counted, false if not, None if inconclusive.
Definition at line 115 of file PtrTypesSemantics.cpp.
References isRefCountable(), and isRefCounted().
Referenced by isUncountedPtr().
isUncountedPtr()
llvm::Optional< bool > clang::isUncountedPtr (const clang::Type * T)
Returns
true if T is either a raw pointer or reference to an uncounted class, false if not, None if inconclusive.
Definition at line 127 of file PtrTypesSemantics.cpp.
References isUncounted().
Referenced by isGetterOfRefCounted().
isUndeducedReturnType()
static bool clang::isUndeducedReturnType (QualType T) static
Definition at line 3583 of file ASTReaderDecl.cpp.
Referenced by clang::ASTDeclReader::attachPreviousDeclImpl().
isUniqueGVALinkage()
bool clang::isUniqueGVALinkage (GVALinkage L) inline
Do we know that this will be the only definition of this symbol (excluding inlining-only definitions)?
Definition at line 87 of file Linkage.h.
References GVA_Internal, and GVA_StrongExternal.
isUnresolvedExceptionSpec()
bool clang::isUnresolvedExceptionSpec (ExceptionSpecificationType ESpecType) inline
Definition at line 49 of file ExceptionSpecificationType.h.
References EST_Unevaluated, and EST_Uninstantiated.
Referenced by AddAttributesFromFunctionProtoType(), clang::ASTDeclReader::attachPreviousDeclImpl(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildMemberExpr(), CanThrow(), CheckEquivalentExceptionSpecImpl(), clang::Sema::CheckExceptionSpecSubset(), completeFunctionType(), CreateFunctionRefExpr(), clang::Sema::DeduceTemplateArguments(), IsEquivalentExceptionSpec(), isSameEntity(), clang::Sema::MarkFunctionReferenced(), clang::Sema::ResolveExceptionSpec(), clang::ASTDeclReader::UpdateDecl(), and clang::Sema::UpdateExceptionSpec().
isUppercase()
LLVM_READONLY bool clang::isUppercase (unsigned char c) inline
Return true if this character is an uppercase ASCII letter: [A-Z].
Definition at line 105 of file CharInfo.h.
References c, and InfoTable.
Referenced by isInStlNamespace(), isReservedId(), rewriteToObjCProperty(), and toLowercase().
isValidIdentifier()
LLVM_READONLY bool clang::isValidIdentifier (StringRef S, bool AllowDollar = false) inline
Return true if this is a valid ASCII identifier.
Note that this is a very simple check; it does not accept UCNs as valid identifier characters.
Definition at line 184 of file CharInfo.h.
References isIdentifierBody(), and isIdentifierHead().
Referenced by printModuleId(), sanitizeFilenameAsIdentifier(), tryParseObjCMethodName(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
isVerticalWhitespace()
LLVM_READONLY bool clang::isVerticalWhitespace (unsigned char c) inline
Returns true if this character is vertical ASCII whitespace: '\n', '\r'.
Note that this returns false for '\0'.
Definition at line 78 of file CharInfo.h.
References c, and InfoTable.
Referenced by atOrBeforeSeparation(), findBeginningOfLine(), getIdentifierContinuation(), isEOL(), clang::Lexer::isNewLineEscaped(), onlyWhitespaceOnLineBefore(), skipLine(), skipNewline(), skipString(), skipWhitespace(), skipWhitespaceAndNewline(), and startsWithNewline().
isWhitespace() [1/2]
static bool clang::isWhitespace (llvm::StringRef S) inline static
Definition at line 19 of file CommentParser.cpp.
References isWhitespace().
isWhitespace() [2/2]
LLVM_READONLY bool clang::isWhitespace (unsigned char c) inline
Return true if this character is horizontal or vertical ASCII whitespace: ' ', '\t', '\f', '\v', '\n', '\r'.
Note that this returns false for '\0'.
Definition at line 87 of file CharInfo.h.
References c, and InfoTable.
Referenced by clang::Sema::ActOnFinishFunctionBody(), clang::comments::Sema::actOnParamCommandDirectionArg(), atOrBeforeSeparation(), canRemoveWhitespace(), consumeWhitespace(), findEndOfWord(), fixItNullability(), clang::Lexer::getRawToken(), isWhitespace(), clang::LayoutOverrideSource::LayoutOverrideSource(), clang::comments::TextTokenRetokenizer::lexWord(), MacroBodyEndsInBackslash(), clang::comments::BriefParser::Parse(), clang::comments::Parser::parseParagraphOrBlockCommand(), selectInterestingSourceRegion(), skipString(), and skipWhitespace().
JsonFormat()
std::string clang::JsonFormat (StringRef RawSR, bool AddQuotes) inline
Definition at line 27 of file JsonSupport.h.
Referenced by clang::ento::SVal::printJson(), clang::Stmt::printJson(), and clang::CFGBlock::printTerminatorJson().
lazyInitKeywordSelector()
template<typename... IdentifierInfos> static void clang::lazyInitKeywordSelector (Selector & Sel, ASTContext & Ctx, IdentifierInfos *... IIs) inline static
Definition at line 27 of file SelectorExtras.h.
References getKeywordSelector(), and clang::Selector::isNull().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
clang::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
make_error_code()
std::error_code clang::make_error_code (BuildPreambleError Error)
Definition at line 868 of file PrecompiledPreamble.cpp.
References BuildPreambleErrCategory.
Referenced by getDirectoryFromFile().
MakeDeductionFailureInfo()
DeductionFailureInfo clang::MakeDeductionFailureInfo (ASTContext & Context, Sema::TemplateDeductionResult TDK, sema::TemplateDeductionInfo & Info)
Convert from Sema's representation of template deduction information to the form used in overload-candidate information.
Definition at line 613 of file SemaOverload.cpp.
References clang::sema::TemplateDeductionInfo::AssociatedConstraintsSatisfaction, clang::sema::TemplateDeductionInfo::CallArgIndex, Diag(), clang::sema::TemplateDeductionInfo::FirstArg, clang::sema::TemplateDeductionInfo::hasSFINAEDiagnostic(), clang::sema::TemplateDeductionInfo::Param, clang::DeductionFailureInfo::Result, Result, clang::sema::TemplateDeductionInfo::SecondArg, clang::sema::TemplateDeductionInfo::take(), clang::sema::TemplateDeductionInfo::takeSFINAEDiagnostic(), clang::Sema::TDK_ConstraintsNotSatisfied, clang::Sema::TDK_CUDATargetMismatch, clang::Sema::TDK_DeducedMismatch, clang::Sema::TDK_DeducedMismatchNested, clang::Sema::TDK_Incomplete, clang::Sema::TDK_IncompletePack, clang::Sema::TDK_Inconsistent, clang::Sema::TDK_InstantiationDepth, clang::Sema::TDK_Invalid, clang::Sema::TDK_InvalidExplicitArguments, clang::Sema::TDK_MiscellaneousDeductionFailure, clang::Sema::TDK_NonDeducedMismatch, clang::Sema::TDK_NonDependentConversionFailure, clang::Sema::TDK_SubstitutionFailure, clang::Sema::TDK_Success, clang::Sema::TDK_TooFewArguments, clang::Sema::TDK_TooManyArguments, and clang::Sema::TDK_Underqualified.
Referenced by clang::Sema::ActOnExplicitInstantiation(), clang::Sema::AddMethodTemplateCandidate(), clang::Sema::AddTemplateConversionCandidate(), clang::Sema::AddTemplateOverloadCandidate(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckVarTemplateId(), getPatternForClassTemplateSpecialization(), and clang::Sema::ResolveSingleFunctionTemplateSpecialization().
MaxVersionForCudaArch()
CudaVersion clang::MaxVersionForCudaArch (CudaArch A)
Get the latest CudaVersion that supports the given CudaArch.
Definition at line 172 of file Cuda.cpp.
References CUDA_80, IsAMDGpuArch(), LATEST, SM_20, SM_21, and UNKNOWN.
Referenced by clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch().
mergeCanThrow()
CanThrowResult clang::mergeCanThrow (CanThrowResult CT1, CanThrowResult CT2) inline
Definition at line 60 of file ExceptionSpecificationType.h.
Referenced by canSubStmtsThrow(), clang::Sema::canThrow(), and canVarDeclThrow().
minimizeSourceToDependencyDirectives()
bool clang::minimizeSourceToDependencyDirectives (llvm::StringRef Input, llvm::SmallVectorImpl< char > & Output, llvm::SmallVectorImpl< minimize_source_to_dependency_directives::Token > & Tokens, DiagnosticsEngine * Diags = nullptr, SourceLocation InputSourceLoc = SourceLocation())
Minimize the input down to the preprocessor directives that might have an effect on the dependencies for a compilation unit.
This function deletes all non-preprocessor code, and strips anything that can't affect what gets included. It canonicalizes whitespace where convenient to stabilize the output against formatting changes in the input.
Clears the output vectors at the beginning of the call.
Returns
false on success, true on error. If the diagnostic engine is not null, an appropriate error is reported using the given input location with the offset that corresponds to the minimizer's current buffer offset.
Referenced by clang::tooling::dependencies::CachedFileSystemEntry::createFileEntry(), and clang::PrintDependencyDirectivesSourceMinimizerAction::ExecuteAction().
minLinkage()
Linkage clang::minLinkage (Linkage L1, Linkage L2) inline
Compute the minimum linkage given two linkages.
The linkage can be interpreted as a pair formed by the formal linkage and a boolean for external visibility. This is just what getFormalLinkage and isExternallyVisible return. We want the minimum of both components. The Linkage enum is defined in an order that makes this simple, we just need special cases for when VisibleNoLinkage would lose the visible bit and become NoLinkage.
Definition at line 120 of file Linkage.h.
References InternalLinkage, NoLinkage, UniqueExternalLinkage, and VisibleNoLinkage.
Referenced by clang::LinkageInfo::mergeLinkage().
MinVersionForCudaArch()
CudaVersion clang::MinVersionForCudaArch (CudaArch A)
Get the earliest CudaVersion that supports the given CudaArch.
Definition at line 136 of file Cuda.cpp.
References CUDA_100, CUDA_110, CUDA_70, CUDA_80, CUDA_90, CUDA_91, IsAMDGpuArch(), SM_20, SM_21, SM_30, SM_32, SM_35, SM_37, SM_50, SM_52, SM_53, SM_60, SM_61, SM_62, SM_70, SM_72, SM_75, SM_80, and UNKNOWN.
Referenced by clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch().
minVisibility()
Visibility clang::minVisibility (Visibility L, Visibility R) inline
Definition at line 48 of file Visibility.h.
noteBottomOfStack()
void clang::noteBottomOfStack ()
Call this once on each thread, as soon after starting the thread as feasible, to note the approximate address of the bottom of the stack.
Definition at line 41 of file Stack.cpp.
References BottomOfStack, and getStackPointer().
Referenced by clang::CompilerInstance::ExecuteAction(), and runWithSufficientStackSpaceSlow().
operator!=() [1/2]
template<typename T , typename U > bool clang::operator!= (CanQual< T > x, CanQual< U > y) inline
Definition at line 207 of file CanonicalType.h.
operator!=() [2/2]
bool clang::operator!= (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 192 of file SourceLocation.h.
operator&()
DiagnosticLevelMask clang::operator& (DiagnosticLevelMask LHS, DiagnosticLevelMask RHS) inline
Definition at line 60 of file DiagnosticOptions.h.
operator<() [1/6]
bool clang::operator< (const CodeCompletionResult & X, const CodeCompletionResult & Y)
Definition at line 753 of file CodeCompleteConsumer.cpp.
References clang::CodeCompletionResult::getOrderedName(), and X().
operator<() [2/6]
bool clang::operator< (const LineEntry & E, unsigned Offset) inline
Definition at line 71 of file SourceManagerInternals.h.
References clang::LineEntry::FileOffset, and Offset.
operator<() [3/6]
bool clang::operator< (const LineEntry & lhs, const LineEntry & rhs) inline
Definition at line 66 of file SourceManagerInternals.h.
References clang::LineEntry::FileOffset.
operator<() [4/6]
bool clang::operator< (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 198 of file SourceLocation.h.
References clang::SourceLocation::getRawEncoding().
operator<() [5/6]
bool clang::operator< (DeclarationName LHS, DeclarationName RHS) inline
Ordering on two declaration names.
If both names are identifiers, this provides a lexicographical ordering.
Definition at line 540 of file DeclarationName.h.
References operator<().
Referenced by maybeDiagnoseUTF8Homoglyph(), and operator<().
operator<() [6/6]
bool clang::operator< (unsigned Offset, const LineEntry & E) inline
Definition at line 75 of file SourceManagerInternals.h.
References clang::LineEntry::FileOffset, and Offset.
operator<<() [1/46]
const DiagnosticBuilder & clang::operator<< (const DiagnosticBuilder & DB, const AddFlagValue V) inline
Register a value for the flag in the current diagnostic.
This value will be shown as the suffix "=value" after the flag name. It is useful in cases where the diagnostic flag accepts values (e.g., -Rpass or -Wframe-larger-than).
Definition at line 1338 of file Diagnostic.h.
References clang::DiagnosticBuilder::addFlagValue(), and V.
operator<<() [2/46]
const DiagnosticBuilder & clang::operator<< (const DiagnosticBuilder & DB, const PartialDiagnostic & PD) inline
Definition at line 200 of file PartialDiagnostic.h.
References clang::PartialDiagnostic::Emit().
operator<<() [3/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, AccessSpecifier AS)
Insertion operator for diagnostics.
This allows sending an AccessSpecifier into a diagnostic with <<.
Definition at line 3368 of file DeclCXX.cpp.
References getAccessName().
operator<<() [4/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, ArrayRef< FixItHint > Hints) inline
Definition at line 1431 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddFixItHint().
operator<<() [5/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, ArrayRef< SourceRange > Ranges) inline
Definition at line 1412 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddSourceRange(), and clang::CharSourceRange::getTokenRange().
operator<<() [6/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, CanQualType T) inline
Definition at line 218 of file CanonicalType.h.
operator<<() [7/46]
template<typename ACI , typename std::enable_if_t< std::is_same< ACI, AttributeCommonInfo >::value, int > = 0> const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const ACI & CI) inline
AttributeCommonInfo has a non-explicit constructor which takes an SourceRange as its only argument, this constructor has many uses so making it explicit is hard.
This constructor causes ambiguity with DiagnosticBuilder &operator<<(const DiagnosticBuilder &DB, SourceRange R). We use SFINAE to disable any conversion and remove any ambiguity.
Definition at line 1070 of file ParsedAttr.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_identifierinfo.
operator<<() [8/46]
template<typename ACI , typename std::enable_if_t< std::is_same< ACI, AttributeCommonInfo >::value, int > = 0> const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const ACI * CI) inline
Definition at line 1080 of file ParsedAttr.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_identifierinfo.
operator<<() [9/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const ASTContext::SectionInfo & Section)
Insertion operator for diagnostics.
Definition at line 11430 of file ASTContext.cpp.
References clang::ASTContext::SectionInfo::Decl.
operator<<() [10/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const Attr * At) inline
Definition at line 371 of file Attr.h.
operator<<() [11/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const char * Str) inline
Definition at line 1350 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_c_string.
operator<<() [12/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const CharSourceRange & R) inline
Definition at line 1419 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddSourceRange().
operator<<() [13/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const FixItHint & Hint) inline
Definition at line 1425 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddFixItHint().
operator<<() [14/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const IdentifierInfo * II) inline
Definition at line 1385 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_identifierinfo.
operator<<() [15/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const llvm::Optional< CharSourceRange > & Opt) inline
Definition at line 1446 of file Diagnostic.h.
operator<<() [16/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const llvm::Optional< FixItHint > & Opt) inline
Definition at line 1454 of file Diagnostic.h.
operator<<() [17/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const llvm::Optional< SourceRange > & Opt) inline
Definition at line 1438 of file Diagnostic.h.
operator<<() [18/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const ParsedAttr & At) inline
Definition at line 1048 of file ParsedAttr.h.
References clang::StreamingDiagnostic::AddTaggedVal(), clang::DiagnosticsEngine::ak_identifierinfo, and clang::AttributeCommonInfo::getAttrName().
operator<<() [19/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const ParsedAttr * At) inline
Definition at line 1055 of file ParsedAttr.h.
References clang::StreamingDiagnostic::AddTaggedVal(), clang::DiagnosticsEngine::ak_identifierinfo, and clang::AttributeCommonInfo::getAttrName().
operator<<() [20/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, const TemplateArgument & Arg)
Definition at line 516 of file TemplateBase.cpp.
References DiagTemplateArg().
operator<<() [21/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, DiagNullabilityKind nullability)
Definition at line 43 of file Diagnostic.cpp.
References clang::StreamingDiagnostic::AddString().
operator<<() [22/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, int I) inline
Definition at line 1357 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_sint.
operator<<() [23/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, llvm::Error && E)
Definition at line 70 of file Diagnostic.cpp.
References clang::StreamingDiagnostic::AddString(), and toString().
operator<<() [24/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, NestedNameSpecifier * NNS) inline
Insertion operator for diagnostics.
This allows sending NestedNameSpecifiers into a diagnostic with <<.
Definition at line 522 of file NestedNameSpecifier.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_nestednamespec.
operator<<() [25/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, SourceRange R) inline
Definition at line 1406 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddSourceRange(), and clang::CharSourceRange::getTokenRange().
operator<<() [26/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, StringRef S) inline
Definition at line 1344 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddString().
operator<<() [27/46]
template<typename T > std::enable_if_t< std::is_same< std::remove_const_t< T >, DeclContext >::value, const StreamingDiagnostic & > clang::operator<< (const StreamingDiagnostic & DB, T * DC) inline
Definition at line 1385 of file Diagnostic.h.
operator<<() [28/46]
template<typename T > std::enable_if_t< std::is_same< T, bool >::value, const StreamingDiagnostic & > clang::operator<< (const StreamingDiagnostic & DB, T I) inline
Definition at line 1357 of file Diagnostic.h.
operator<<() [29/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, TemplateName N)
Insertion operator for diagnostics.
This allows sending TemplateName's into a diagnostic with <<.
Definition at line 257 of file TemplateName.cpp.
References N.
operator<<() [30/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, tok::TokenKind I) inline
Definition at line 1379 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_tokenkind.
operator<<() [31/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & DB, unsigned I) inline
Definition at line 1373 of file Diagnostic.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_uint.
operator<<() [32/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & PD, const NamedDecl * ND) inline
Insertion operator for diagnostics.
This allows sending NamedDecl's into a diagnostic with <<.
Definition at line 4537 of file Decl.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_nameddecl.
operator<<() [33/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & PD, DeclarationName N) inline
Insertion operator for partial diagnostics.
This allows binding DeclarationName's into a partial diagnostic with <<.
Definition at line 816 of file DeclarationName.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and N.
operator<<() [34/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & PD, LangAS AS) inline
Insertion operator for partial diagnostics.
This allows sending adress spaces into a diagnostic with <<.
Definition at line 7112 of file Type.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_addrspace.
operator<<() [35/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & PD, Qualifiers Q) inline
Insertion operator for partial diagnostics.
This allows sending Qualifiers into a diagnostic with <<.
Definition at line 7121 of file Type.h.
References clang::StreamingDiagnostic::AddTaggedVal(), clang::DiagnosticsEngine::ak_qual, and clang::Qualifiers::getAsOpaqueValue().
operator<<() [36/46]
const StreamingDiagnostic & clang::operator<< (const StreamingDiagnostic & PD, QualType T) inline
Insertion operator for partial diagnostics.
This allows sending QualType's into a diagnostic with <<.
Definition at line 7130 of file Type.h.
References clang::StreamingDiagnostic::AddTaggedVal(), and clang::DiagnosticsEngine::ak_qualtype.
operator<<() [37/46]
llvm::raw_ostream & clang::operator<< (llvm::raw_ostream & OS, const OMPTraitInfo & TI)
Definition at line 2287 of file OpenMPClause.cpp.
References clang::OMPTraitInfo::print().
operator<<() [38/46]
llvm::raw_ostream & clang::operator<< (llvm::raw_ostream & OS, const OMPTraitInfo * TI)
Definition at line 2294 of file OpenMPClause.cpp.
operator<<() [39/46]
raw_ostream & clang::operator<< (raw_ostream & OS, ASTNodeKind K) inline
Definition at line 216 of file ASTTypeTraits.h.
References clang::ASTNodeKind::asStringRef().
operator<<() [40/46]
raw_ostream & clang::operator<< (raw_ostream & OS, const NamedDecl & ND) inline
Definition at line 456 of file Decl.h.
References clang::NamedDecl::printName().
operator<<() [41/46]
raw_ostream & clang::operator<< (raw_ostream & OS, const ObjCCategoryImplDecl & CID)
Definition at line 2191 of file DeclObjC.cpp.
References clang::NamedDecl::getName().
operator<<() [42/46]
raw_ostream & clang::operator<< (raw_ostream & OS, const ObjCImplementationDecl & ID)
Definition at line 2242 of file DeclObjC.cpp.
operator<<() [43/46]
raw_ostream & clang::operator<< (raw_ostream & OS, DeclarationName N)
Definition at line 214 of file DeclarationName.cpp.
References N.
operator<<() [44/46]
raw_ostream & clang::operator<< (raw_ostream & OS, DeclarationNameInfo DNInfo)
Definition at line 467 of file DeclarationName.cpp.
References clang::DeclarationNameInfo::printName().
operator<<() [45/46]
raw_ostream & clang::operator<< (raw_ostream & out, const ObjCRuntime & value)
Definition at line 32 of file ObjCRuntime.cpp.
References clang::ObjCRuntime::FragileMacOSX, clang::ObjCRuntime::GCC, clang::ObjCRuntime::getKind(), clang::ObjCRuntime::getVersion(), clang::ObjCRuntime::GNUstep, clang::ObjCRuntime::iOS, clang::ObjCRuntime::MacOSX, clang::ObjCRuntime::ObjFW, and clang::ObjCRuntime::WatchOS.
operator<<() [46/46]
raw_ostream & clang::operator<< (raw_ostream & Out, DiagnosticLevelMask M)
Definition at line 19 of file DiagnosticOptions.cpp.
operator<=() [1/3]
bool clang::operator<= (const CodeCompletionResult & X, const CodeCompletionResult & Y) inline
Definition at line 985 of file CodeCompleteConsumer.h.
References X().
operator<=() [2/3]
bool clang::operator<= (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 204 of file SourceLocation.h.
References clang::SourceLocation::getRawEncoding().
operator<=() [3/3]
bool clang::operator<= (DeclarationName LHS, DeclarationName RHS) inline
Ordering on two declaration names.
If both names are identifiers, this provides a lexicographical ordering.
Definition at line 552 of file DeclarationName.h.
References operator<=().
Referenced by operator<=().
operator==() [1/4]
template<typename T , typename U > bool clang::operator== (CanQual< T > x, CanQual< U > y) inline
Definition at line 202 of file CanonicalType.h.
operator==() [2/4]
bool clang::operator== (const APValue::LValueBase & LHS, const APValue::LValueBase & RHS)
Definition at line 136 of file APValue.cpp.
operator==() [3/4]
bool clang::operator== (const CallGraphNode::CallRecord & LHS, const CallGraphNode::CallRecord & RHS) inline
Definition at line 207 of file CallGraph.h.
References clang::CallGraphNode::CallRecord::Callee.
operator==() [4/4]
bool clang::operator== (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 188 of file SourceLocation.h.
References clang::SourceLocation::getRawEncoding().
operator>() [1/3]
bool clang::operator> (const CodeCompletionResult & X, const CodeCompletionResult & Y) inline
Definition at line 980 of file CodeCompleteConsumer.h.
References X().
operator>() [2/3]
bool clang::operator> (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 201 of file SourceLocation.h.
References clang::SourceLocation::getRawEncoding().
operator>() [3/3]
bool clang::operator> (DeclarationName LHS, DeclarationName RHS) inline
Ordering on two declaration names.
If both names are identifiers, this provides a lexicographical ordering.
Definition at line 546 of file DeclarationName.h.
References operator>().
Referenced by operator>().
operator>=() [1/3]
bool clang::operator>= (const CodeCompletionResult & X, const CodeCompletionResult & Y) inline
Definition at line 990 of file CodeCompleteConsumer.h.
References X().
operator>=() [2/3]
bool clang::operator>= (const SourceLocation & LHS, const SourceLocation & RHS) inline
Definition at line 207 of file SourceLocation.h.
References clang::SourceLocation::getRawEncoding().
operator>=() [3/3]
bool clang::operator>= (DeclarationName LHS, DeclarationName RHS) inline
Ordering on two declaration names.
If both names are identifiers, this provides a lexicographical ordering.
Definition at line 558 of file DeclarationName.h.
References operator>=().
Referenced by operator>=().
operator|()
DiagnosticLevelMask clang::operator| (DiagnosticLevelMask LHS, DiagnosticLevelMask RHS) inline
Definition at line 53 of file DiagnosticOptions.h.
operator~()
DiagnosticLevelMask clang::operator~ (DiagnosticLevelMask M) inline
Definition at line 48 of file DiagnosticOptions.h.
ParseAST() [1/2]
void clang::ParseAST (Preprocessor & PP, ASTConsumer * Consumer, ASTContext & Ctx, bool PrintStats = false, TranslationUnitKind TUKind = TU_Complete, CodeCompleteConsumer * CompletionConsumer = nullptr, bool SkipFunctionBodies = false)
Parse the entire file specified, notifying the ASTConsumer as the file is parsed.
ParseAST - Parse the entire file specified, notifying the ASTConsumer as the file is parsed.
This operation inserts the parsed decls into the translation unit held by Ctx.
Parameters
PrintStats Whether to print LLVM statistics related to parsing.
TUKind The kind of translation unit being parsed.
CompletionConsumer If given, an object to consume code completion results.
SkipFunctionBodies Whether to skip parsing of function bodies. This option can be used, for example, to speed up searches for declarations/definitions when indexing.
This inserts the parsed decls into the translation unit held by Ctx.
Definition at line 99 of file ParseAST.cpp.
References ParseAST().
Referenced by createChainedIncludesSource(), clang::ASTFrontendAction::ExecuteAction(), and ParseAST().
ParseAST() [2/2]
void clang::ParseAST (Sema & S, bool PrintStats = false, bool SkipFunctionBodies = false)
Parse the main file known to the preprocessor, producing an abstract syntax tree.
Definition at line 114 of file ParseAST.cpp.
References clang::Sema::CollectStats, clang::Decl::EnableStatistics(), clang::Stmt::EnableStatistics(), clang::Preprocessor::EnterMainSourceFile(), finalize(), clang::OpaquePtr< PtrTy >::get(), clang::Sema::getASTConsumer(), clang::Sema::getASTContext(), clang::Preprocessor::getCurrentLexer(), clang::ASTContext::getExternalSource(), clang::Sema::getPreprocessor(), clang::ASTConsumer::HandleTopLevelDecl(), clang::ASTConsumer::HandleTranslationUnit(), initialize(), P, clang::ASTConsumer::PrintStats(), clang::ASTContext::PrintStats(), clang::Decl::PrintStats(), clang::Stmt::PrintStats(), clang::ExternalASTSource::StartTranslationUnit(), clang::Sema::TemplateInstCallbacks, and clang::Sema::WeakTopLevelDecls().
ParseDiagnosticArgs()
bool clang::ParseDiagnosticArgs (DiagnosticOptions & Opts, llvm::opt::ArgList & Args, clang::DiagnosticsEngine * Diags = nullptr, bool DefaultDiagColor = true)
Fill out Opts based on the options given in Args.
Args must have been created from the OptTable returned by createCC1OptTable().
When errors are encountered, return false and, if Diags is non-null, report the error(s).
Referenced by clang::CompilerInvocation::CreateFromArgs(), and clang::tooling::ToolInvocation::run().
parseSanitizerValue()
SanitizerMask clang::parseSanitizerValue (StringRef Value, bool AllowGroups)
Parse a single value from a -fsanitize= or -fno-sanitize= value list.
Returns a non-zero SanitizerMask, or 0 if Value is not known.
Definition at line 27 of file Sanitizers.cpp.
Referenced by describeSanitizeArg(), parseArgValues(), and parseSanitizerKinds().
parseTargetID()
llvm::Optional< llvm::StringRef > clang::parseTargetID (const llvm::Triple & T, llvm::StringRef OffloadArch, llvm::StringMap< bool > * FeatureMap)
Parse a target ID to get processor and feature map.
Returns canonicalized processor name or None if the target ID is invalid. Returns target ID features in FeatureMap if it is not null pointer. This function assumes OffloadArch is a valid target ID. If the target ID contains feature+, map it to true. If the target ID contains feature-, map it to false. If the target ID does not contain a feature (default), do not map it.
Definition at line 104 of file TargetID.cpp.
References getAllPossibleTargetIDFeatures(), getCanonicalProcessorName(), and parseTargetIDWithFormatCheckingOnly().
Referenced by clang::driver::toolchains::AMDGPUToolChain::checkTargetID(), and clang::driver::tools::amdgpu::getAMDGPUTargetFeatures().
parseTargetIDWithFormatCheckingOnly()
static llvm::Optional< llvm::StringRef > clang::parseTargetIDWithFormatCheckingOnly (llvm::StringRef TargetID, llvm::StringMap< bool > * FeatureMap) static
Definition at line 66 of file TargetID.cpp.
References Split.
Referenced by getConflictTargetIDCombination(), and parseTargetID().
parseXRayInstrValue()
XRayInstrMask clang::parseXRayInstrValue (StringRef Value)
Definition at line 18 of file XRayInstr.cpp.
References clang::XRayInstrKind::All, clang::XRayInstrKind::Custom, clang::XRayInstrKind::FunctionEntry, clang::XRayInstrKind::FunctionExit, clang::XRayInstrKind::None, and clang::XRayInstrKind::Typed.
Referenced by parseXRayInstrumentationBundle(), and clang::driver::XRayArgs::XRayArgs().
printQuotedName()
template<typename NamedDeclDerivedT > void clang::printQuotedName (llvm::raw_ostream & Os, const NamedDeclDerivedT & D)
Definition at line 27 of file DiagOutputUtils.h.
printQuotedQualifiedName()
template<typename NamedDeclDerivedT > void clang::printQuotedQualifiedName (llvm::raw_ostream & Os, const NamedDeclDerivedT & D)
Definition at line 18 of file DiagOutputUtils.h.
printSourceLocationAsJson()
void clang::printSourceLocationAsJson (raw_ostream & Out, SourceLocation Loc, const SourceManager & SM, bool AddBraces = true) inline
Definition at line 81 of file JsonSupport.h.
References clang::PresumedLoc::getColumn(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::SourceLocation::isFileID(), clang::PresumedLoc::isInvalid(), clang::SourceLocation::isValid(), printSourceLocationAsJson(), and SM.
Referenced by clang::LocationContext::printJson(), clang::ProgramPoint::printJson(), and printSourceLocationAsJson().
printTemplateArgumentList() [1/3]
void clang::printTemplateArgumentList (raw_ostream & OS, ArrayRef< TemplateArgument > Args, const PrintingPolicy & Policy, const TemplateParameterList * TPL = nullptr)
Print a template argument list, including the '<' and '>' enclosing the template arguments.
Definition at line 2062 of file TypePrinter.cpp.
References printTo().
Referenced by clang::ClassTemplateSpecializationDecl::getNameForDiagnostic(), clang::FunctionDecl::getNameForDiagnostic(), clang::VarTemplateSpecializationDecl::getNameForDiagnostic(), clang::NestedNameSpecifier::print(), clang::Sema::PrintInstantiationStack(), clang::NamedDecl::printNestedNameSpecifier(), and printTemplateArgumentList().
printTemplateArgumentList() [2/3]
void clang::printTemplateArgumentList (raw_ostream & OS, ArrayRef< TemplateArgumentLoc > Args, const PrintingPolicy & Policy, const TemplateParameterList * TPL = nullptr)
Definition at line 2069 of file TypePrinter.cpp.
References printTo().
printTemplateArgumentList() [3/3]
void clang::printTemplateArgumentList (raw_ostream & OS, const TemplateArgumentListInfo & Args, const PrintingPolicy & Policy, const TemplateParameterList * TPL = nullptr)
Definition at line 2055 of file TypePrinter.cpp.
References clang::TemplateArgumentListInfo::arguments(), and printTemplateArgumentList().
ProcessWarningOptions()
void clang::ProcessWarningOptions (DiagnosticsEngine & Diags, const DiagnosticOptions & Opts, bool ReportDiags = true)
ProcessWarningOptions - Initialize the diagnostic client and process the warning options specified on the command line.
Definition at line 44 of file Warnings.cpp.
References EmitUnknownDiagWarning(), clang::DiagnosticsEngine::getDiagnosticIDs(), clang::DiagnosticOptions::Remarks, clang::DiagnosticsEngine::Report(), clang::DiagnosticsEngine::setConstexprBacktraceLimit(), clang::DiagnosticsEngine::setDiagnosticGroupErrorAsFatal(), clang::DiagnosticsEngine::setDiagnosticGroupWarningAsError(), clang::DiagnosticsEngine::setElideType(), clang::DiagnosticsEngine::setEnableAllWarnings(), clang::DiagnosticsEngine::setErrorLimit(), clang::DiagnosticsEngine::setErrorsAsFatal(), clang::DiagnosticsEngine::setExtensionHandlingBehavior(), clang::DiagnosticsEngine::setIgnoreAllWarnings(), clang::DiagnosticsEngine::setPrintTemplateTree(), clang::DiagnosticsEngine::setSeverityForAll(), clang::DiagnosticsEngine::setSeverityForGroup(), clang::DiagnosticsEngine::setShowColors(), clang::DiagnosticsEngine::setShowOverloads(), clang::DiagnosticsEngine::setSuppressSystemWarnings(), clang::DiagnosticsEngine::setTemplateBacktraceLimit(), clang::DiagnosticsEngine::setWarningsAsErrors(), Specifier, and clang::DiagnosticOptions::Warnings.
Referenced by clang::PrecompiledPreamble::Build(), clang::ASTUnit::CodeComplete(), clang::CompilerInstance::createDiagnostics(), clang::ASTUnit::LoadFromCompilerInvocationAction(), clang::PCHValidator::ReadDiagnosticOptions(), and clang::ASTUnit::Reparse().
reportOptRecordError()
static void clang::reportOptRecordError (Error E, DiagnosticsEngine & Diags, const CodeGenOptions CodeGenOpts) static
Definition at line 86 of file CodeGenAction.cpp.
References clang::CodeGenOptions::OptRecordFile, clang::CodeGenOptions::OptRecordFormat, clang::CodeGenOptions::OptRecordPasses, and clang::DiagnosticsEngine::Report().
Referenced by clang::CodeGenAction::ExecuteAction(), and clang::BackendConsumer::HandleTranslationUnit().
RewriteIncludesInInput()
void clang::RewriteIncludesInInput (Preprocessor & PP, raw_ostream * OS, const PreprocessorOutputOptions & Opts)
RewriteIncludesInInput - Implement -frewrite-includes mode.
InclusionRewriterInInput - Implement -frewrite-includes mode.
Definition at line 536 of file InclusionRewriter.cpp.
References clang::Preprocessor::addPPCallbacks(), clang::SrcMgr::C_User, clang::Preprocessor::EnterMainSourceFile(), clang::Preprocessor::getPredefinesFileID(), clang::Preprocessor::getSourceManager(), clang::Preprocessor::IgnorePragmas(), clang::Token::is(), clang::Token::isNot(), clang::Preprocessor::Lex(), Rewrite, clang::Preprocessor::SetMacroExpansionOnlyInDirectives(), clang::PreprocessorOutputOptions::ShowLineMarkers, SM, Tok, and clang::PreprocessorOutputOptions::UseLineDirectives.
Referenced by clang::RewriteIncludesAction::ExecuteAction().
RewriteMacrosInInput()
void clang::RewriteMacrosInInput (Preprocessor & PP, raw_ostream * OS)
RewriteMacrosInInput - Implement -rewrite-macros mode.
Definition at line 89 of file RewriteMacros.cpp.
References clang::Preprocessor::EnterMainSourceFile(), clang::Preprocessor::getLangOpts(), clang::Token::getLength(), clang::Token::getLocation(), clang::IdentifierInfo::getName(), GetNextRawTok(), clang::Preprocessor::getSourceManager(), clang::Preprocessor::getSpelling(), clang::Token::hasLeadingSpace(), clang::RewriteBuffer::InsertTextAfter(), clang::RewriteBuffer::InsertTextBefore(), clang::Token::is(), is(), clang::Token::isAtStartOfLine(), clang::Token::isNot(), isSameToken(), clang::Preprocessor::Lex(), LexRawTokensFromMainFile(), Rewrite, clang::Rewriter::setSourceMgr(), and SM.
Referenced by clang::RewriteMacrosAction::ExecuteAction().
runUninitializedVariablesAnalysis()
void clang::runUninitializedVariablesAnalysis (const DeclContext & dc, const CFG & cfg, AnalysisDeclContext & ac, UninitVariablesHandler & handler, UninitVariablesAnalysisStats & stats)
Definition at line 909 of file UninitializedValues.cpp.
References clang::DataflowWorklistBase< Comp, QueueSize >::dequeue(), clang::ForwardDataflowWorklist::enqueueSuccessors(), clang::CFGBlock::getBlockID(), clang::CFG::getEntry(), clang::CFG::getNumBlockIDs(), clang::UninitVariablesAnalysisStats::NumBlockVisits, clang::UninitVariablesAnalysisStats::NumVariablesAnalyzed, runOnBlock(), Uninitialized, and clang::CFG::VisitBlockStmts().
Referenced by clang::sema::AnalysisBasedWarnings::IssueWarnings().
runWithSufficientStackSpace()
void clang::runWithSufficientStackSpace (llvm::function_ref< void()> Diag, llvm::function_ref< void()> Fn) inline
Run a given function on a stack with "sufficient" space.
If stack space is insufficient, calls Diag to emit a diagnostic before calling Fn.
Definition at line 40 of file Stack.h.
References Diag(), isStackNearlyExhausted(), and runWithSufficientStackSpaceSlow().
Referenced by clang::Sema::runWithSufficientStackSpace().
runWithSufficientStackSpaceSlow()
void clang::runWithSufficientStackSpaceSlow (llvm::function_ref< void()> Diag, llvm::function_ref< void()> Fn)
Definition at line 67 of file Stack.cpp.
References DesiredStackSize, Diag(), and noteBottomOfStack().
Referenced by runWithSufficientStackSpace().
safeGetName()
template<typename T > std::string clang::safeGetName (const T * ASTNode)
Returns
name of AST node or empty string.
Definition at line 69 of file ASTUtils.h.
Referenced by isCtorOfRefCounted(), isGetterOfRefCounted(), isPtrConversion(), and isRefCounted().
scanDirectory() [1/2]
std::vector< std::string > clang::scanDirectory (llvm::StringRef Path)
Gets names (filenames) of items in directory at Path.
Returns
empty vector if Path is not a directory, doesn't exist or can't be read from.
scanDirectory() [2/2]
std::vector< std::string > clang::scanDirectory (StringRef Path)
Definition at line 25 of file DirectoryScanner.cpp.
References getFileStatus(), and Result.
specific_attr_begin()
template<typename SpecificAttr , typename Container > specific_attr_iterator< SpecificAttr, Container > clang::specific_attr_begin (const Container & container) inline
Definition at line 102 of file AttrIterator.h.
Referenced by getSpecificAttr(), and hasSpecificAttr().
specific_attr_end()
template<typename SpecificAttr , typename Container > specific_attr_iterator< SpecificAttr, Container > clang::specific_attr_end (const Container & container) inline
Definition at line 107 of file AttrIterator.h.
Referenced by getSpecificAttr(), and hasSpecificAttr().
StmtEmpty()
StmtResult clang::StmtEmpty () inline
Definition at line 290 of file Ownership.h.
StmtError() [1/2]
StmtResult clang::StmtError () inline
Definition at line 279 of file Ownership.h.
Referenced by clang::Sema::ActOnBreakStmt(), clang::Sema::ActOnCapScopeReturnStmt(), clang::Sema::ActOnCapturedRegionEnd(), clang::Sema::ActOnCaseStmt(), clang::Sema::ActOnContinueStmt(), clang::Sema::ActOnCoreturnStmt(), clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCXXForRangeStmt(), clang::Sema::ActOnCXXTryBlock(), clang::Sema::ActOnDeclStmt(), clang::Sema::ActOnDoStmt(), clang::Sema::ActOnExprStmt(), clang::Sema::ActOnExprStmtError(), clang::Sema::ActOnFinishFullStmt(), clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::ActOnForEachLValueExpr(), clang::Sema::ActOnForStmt(), clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnIndirectGotoStmt(), clang::Sema::ActOnMSAsmStmt(), clang::Sema::ActOnObjCAtCatchStmt(), clang::Sema::ActOnObjCAtThrowStmt(), clang::Sema::ActOnObjCForCollectionStmt(), clang::Sema::ActOnOpenMPAtomicDirective(), clang::Sema::ActOnOpenMPCancelDirective(), clang::Sema::ActOnOpenMPCancellationPointDirective(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnOpenMPDepobjDirective(), clang::Sema::ActOnOpenMPDistributeDirective(), clang::Sema::ActOnOpenMPDistributeParallelForDirective(), clang::Sema::ActOnOpenMPDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPDistributeSimdDirective(), clang::Sema::ActOnOpenMPExecutableDirective(), clang::Sema::ActOnOpenMPFlushDirective(), clang::Sema::ActOnOpenMPForDirective(), clang::Sema::ActOnOpenMPForSimdDirective(), clang::Sema::ActOnOpenMPMasterDirective(), clang::Sema::ActOnOpenMPMasterTaskLoopDirective(), clang::Sema::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPOrderedDirective(), clang::Sema::ActOnOpenMPParallelDirective(), clang::Sema::ActOnOpenMPParallelForDirective(), clang::Sema::ActOnOpenMPParallelForSimdDirective(), clang::Sema::ActOnOpenMPParallelMasterDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::Sema::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPParallelSectionsDirective(), clang::Sema::ActOnOpenMPRegionEnd(), clang::Sema::ActOnOpenMPScanDirective(), clang::Sema::ActOnOpenMPSectionDirective(), clang::Sema::ActOnOpenMPSectionsDirective(), clang::Sema::ActOnOpenMPSimdDirective(), clang::Sema::ActOnOpenMPSingleDirective(), clang::Sema::ActOnOpenMPTargetDataDirective(), clang::Sema::ActOnOpenMPTargetDirective(), clang::Sema::ActOnOpenMPTargetEnterDataDirective(), clang::Sema::ActOnOpenMPTargetExitDataDirective(), clang::Sema::ActOnOpenMPTargetParallelDirective(), clang::Sema::ActOnOpenMPTargetParallelForDirective(), clang::Sema::ActOnOpenMPTargetParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::Sema::ActOnOpenMPTargetUpdateDirective(), clang::Sema::ActOnOpenMPTaskDirective(), clang::Sema::ActOnOpenMPTaskgroupDirective(), clang::Sema::ActOnOpenMPTaskLoopDirective(), clang::Sema::ActOnOpenMPTaskLoopSimdDirective(), clang::Sema::ActOnOpenMPTeamsDirective(), clang::Sema::ActOnOpenMPTeamsDistributeDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::Sema::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::Sema::ActOnOpenMPTeamsDistributeSimdDirective(), clang::Sema::ActOnReturnStmt(), clang::Sema::ActOnSEHExceptBlock(), clang::Sema::ActOnSEHLeaveStmt(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnWhileStmt(), clang::Sema::BuildCoreturnStmt(), clang::Sema::BuildCoroutineBodyStmt(), clang::Sema::BuildCXXForRangeStmt(), clang::Sema::BuildIfStmt(), buildMemcpyForAssignmentOp(), clang::Sema::BuildObjCAtThrowStmt(), clang::Sema::BuildReturnStmt(), buildSingleCopyAssignRecursively(), clang::Sema::FinishCXXForRangeStmt(), clang::Sema::FinishObjCForCollectionStmt(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildObjCForCollectionStmt(), clang::TreeTransform< Derived >::SkipLambdaBody(), StmtError(), and clang::TreeTransform< Derived >::TransformOMPExecutableDirective().
StmtError() [2/2]
StmtResult clang::StmtError (const StreamingDiagnostic &) inline
Definition at line 285 of file Ownership.h.
References StmtError().
StringToCudaArch()
CudaArch clang::StringToCudaArch (llvm::StringRef S)
Definition at line 127 of file Cuda.cpp.
References clang::CudaArchToStringMap::arch_name, arch_names, and UNKNOWN.
Referenced by clang::driver::toolchains::CudaToolChain::AddCudaIncludeArgs(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::NVPTX::Linker::ConstructJob(), getCudaArch(), clang::targets::NVPTXTargetInfo::isValidCPUName(), and clang::targets::NVPTXTargetInfo::setCPU().
supportsVariadicCall()
bool clang::supportsVariadicCall (CallingConv CC) inline
Checks whether the given calling convention supports variadic calls.
Unprototyped calls also use the variadic call rules.
Definition at line 276 of file Specifiers.h.
References CC_OpenCLKernel, CC_SpirFunction, CC_Swift, CC_X86FastCall, CC_X86Pascal, CC_X86RegCall, CC_X86StdCall, CC_X86ThisCall, and CC_X86VectorCall.
Referenced by clang::Sema::ActOnFunctionDeclarator(), getCCForDeclaratorChunk(), and handleFunctionTypeAttr().
ToConstrainedExceptMD()
llvm::fp::ExceptionBehavior clang::ToConstrainedExceptMD (LangOptions::FPExceptionModeKind Kind)
Definition at line 101 of file CodeGenFunction.cpp.
References clang::LangOptions::FPE_Ignore, clang::LangOptions::FPE_MayTrap, and clang::LangOptions::FPE_Strict.
ToCudaVersion()
CudaVersion clang::ToCudaVersion (llvm::VersionTuple Version)
Definition at line 188 of file Cuda.cpp.
References CUDA_100, CUDA_101, CUDA_102, CUDA_110, CUDA_70, CUDA_75, CUDA_80, CUDA_90, CUDA_91, CUDA_92, and UNKNOWN.
Referenced by CudaFeatureEnabled().
toExprDependence() [1/3]
ExprDependence clang::toExprDependence (NestedNameSpecifierDependence D) inline
Definition at line 230 of file DependenceFlags.h.
References clang::Dependence::expr().
toExprDependence() [2/3]
ExprDependence clang::toExprDependence (TemplateArgumentDependence TA) inline
Computes dependencies of a reference with the name having template arguments with TA dependencies.
Definition at line 221 of file DependenceFlags.h.
References clang::Dependence::expr().
Referenced by computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), and computeDependence().
toExprDependence() [3/3]
ExprDependence clang::toExprDependence (TypeDependence D) inline
Definition at line 224 of file DependenceFlags.h.
References clang::Dependence::expr().
toLowercase()
LLVM_READONLY char clang::toLowercase (char c) inline
Converts the given ASCII character to its lowercase equivalent.
If the character is not an uppercase character, it is returned as is.
Definition at line 164 of file CharInfo.h.
References c, and isUppercase().
Referenced by clang::SelectorTable::getPropertyNameFromSetterSelector(), HashHMapKey(), IsValidIdentifier(), rewriteToObjCProperty(), and UseNSOptionsMacro().
toNestedNameSpecifierDependendence()
NestedNameSpecifierDependence clang::toNestedNameSpecifierDependendence (TypeDependence D) inline
Definition at line 260 of file DependenceFlags.h.
References clang::Dependence::nestedNameSpecifier().
Referenced by clang::NestedNameSpecifier::getDependence().
toTargetAddressSpace()
unsigned clang::toTargetAddressSpace (LangAS AS) inline
Definition at line 68 of file AddressSpaces.h.
References FirstTargetAddressSpace, and isTargetAddressSpace().
Referenced by CheckForNullPointerDereference(), DeduceTemplateArgumentsByTypeMatch(), clang::Qualifiers::getAddressSpaceAttributePrintValue(), clang::Qualifiers::getAddrSpaceAsString(), and clang::ASTContext::getTargetAddressSpace().
toTemplateArgumentDependence() [1/3]
TemplateArgumentDependence clang::toTemplateArgumentDependence (ExprDependence D) inline
Definition at line 273 of file DependenceFlags.h.
References clang::Dependence::templateArgument().
toTemplateArgumentDependence() [2/3]
TemplateArgumentDependence clang::toTemplateArgumentDependence (TemplateNameDependence D) inline
Definition at line 269 of file DependenceFlags.h.
References clang::Dependence::templateArgument().
toTemplateArgumentDependence() [3/3]
TemplateArgumentDependence clang::toTemplateArgumentDependence (TypeDependence D) inline
Definition at line 265 of file DependenceFlags.h.
References clang::Dependence::templateArgument().
Referenced by clang::TemplateArgument::getDependence().
toTemplateNameDependence()
TemplateNameDependence clang::toTemplateNameDependence (NestedNameSpecifierDependence D) inline
Definition at line 278 of file DependenceFlags.h.
References clang::Dependence::templateName().
Referenced by clang::TemplateName::getDependence().
toTypeDependence() [1/4]
TypeDependence clang::toTypeDependence (ExprDependence D) inline
Definition at line 246 of file DependenceFlags.h.
References clang::Dependence::type().
toTypeDependence() [2/4]
TypeDependence clang::toTypeDependence (NestedNameSpecifierDependence D) inline
Definition at line 249 of file DependenceFlags.h.
References clang::Dependence::type().
toTypeDependence() [3/4]
TypeDependence clang::toTypeDependence (TemplateArgumentDependence D) inline
Definition at line 255 of file DependenceFlags.h.
References clang::Dependence::type().
toTypeDependence() [4/4]
TypeDependence clang::toTypeDependence (TemplateNameDependence D) inline
Definition at line 252 of file DependenceFlags.h.
References clang::Dependence::type().
toUppercase()
LLVM_READONLY char clang::toUppercase (char c) inline
Converts the given ASCII character to its uppercase equivalent.
If the character is not a lowercase character, it is returned as is.
Definition at line 173 of file CharInfo.h.
References c, and isLowercase().
Referenced by AddObjCKeyValueCompletions(), clang::SelectorTable::constructSetterName(), and isCaseSensitivePath().
transformOMPMappableExprListClause()
template<typename Derived , class T > bool clang::transformOMPMappableExprListClause (TreeTransform< Derived > & TT, OMPMappableExprListClause< T > * C, llvm::SmallVectorImpl< Expr * > & Vars, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperIdInfo, llvm::SmallVectorImpl< Expr * > & UnresolvedMappers)
Definition at line 9580 of file TreeTransform.h.
References clang::UnresolvedSetImpl::addDecl(), clang::CXXScopeSpec::Adopt(), clang::UnresolvedSetImpl::begin(), C, cast(), clang::Sema::Context, clang::UnresolvedLookupExpr::Create(), clang::UnresolvedSetImpl::end(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Decl::getAccess(), clang::TreeTransform< Derived >::getDerived(), clang::DeclarationNameInfo::getName(), clang::TreeTransform< Derived >::getSema(), clang::CXXScopeSpec::getWithLocInContext(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
TransformTypeSpecType()
template<class TyLoc > static QualType clang::TransformTypeSpecType (TypeLocBuilder & TLB, TyLoc T) inline static
Definition at line 4795 of file TreeTransform.h.
References clang::TypeLocBuilder::push().
TRY_TO() [1/8]
clang::TRY_TO (TraverseArrayTypeLocHelper(TL))
Initial value:
{
  TRY_TO(TraverseTypeLoc(TL.getElementLoc()))
TRY_TO() [2/8]
clang::TRY_TO (TraverseStmt(TL.getAttrColumnOperand()))
TRY_TO() [3/8]
clang::TRY_TO (TraverseTemplateArguments(T->getArgs(), T->getNumArgs()))
Initial value:
{
  TRY_TO(TraverseNestedNameSpecifier(T->getQualifier()))
TRY_TO() [4/8]
else clang::TRY_TO (TraverseType(QualType(TL.getTypePtr() ->getClass(), 0)))
TRY_TO() [5/8]
clang::TRY_TO (TraverseType(T->getElementType()))
TRY_TO() [6/8]
clang::TRY_TO (TraverseType(T->getPointeeType()))
TRY_TO() [7/8]
clang::TRY_TO (TraverseType(TL.getTypePtr() ->getElementType()))
Initial value:
{
  if (TL.getTypePtr()->getSizeExpr())
    TRY_TO(TraverseStmt(TL.getTypePtr()->getSizeExpr()))
TRY_TO() [8/8]
clang::TRY_TO (TraverseTypeLoc(TL.getPointeeLoc()))
tryToFindPtrOrigin()
std::pair< const clang::Expr *, bool > clang::tryToFindPtrOrigin (const clang::Expr * E, bool StopAtFirstRefCountedObj)
This function de-facto defines a set of transformations that we consider safe (in heuristical sense).
These transformation if passed a safe value as an input should provide a safe value (or an object that provides safe values).
For more context see Static Analyzer checkers documentation - specifically webkit.UncountedCallArgsChecker checker. Whitelist of transformations:
constructors of ref-counted types (including factory methods)
getters of ref-counted types
member overloaded operators
casts
unary operators like & or *
If passed expression is of type uncounted pointer/reference we try to find the "origin" of the pointer value. Origin can be for example a local variable, nullptr, constant or this-pointer.
Certain subexpression nodes represent transformations that don't affect where the memory address originates from. We try to traverse such subexpressions to get to the relevant child nodes. Whenever we encounter a subexpression that either can't be ignored, we don't model its semantics or that has multiple children we stop.
E is an expression of uncounted pointer/reference type. If StopAtFirstRefCountedObj is true and we encounter a subexpression that represents ref-counted object during the traversal we return relevant sub-expression and true.
Returns
subexpression that we traversed to and if StopAtFirstRefCountedObj is true we also return whether we stopped early.
Definition at line 20 of file ASTUtils.cpp.
References isCtorOfRefCounted(), isGetterOfRefCounted(), and isPtrConversion().
turnTypeToValueDependence()
ExprDependence clang::turnTypeToValueDependence (ExprDependence D) inline
Definition at line 233 of file DependenceFlags.h.
References Type.
Referenced by computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), computeDependence(), and computeDependence().
turnValueToTypeDependence()
ExprDependence clang::turnValueToTypeDependence (ExprDependence D) inline
Definition at line 238 of file DependenceFlags.h.
TypeError()
TypeResult clang::TypeError () inline
Definition at line 280 of file Ownership.h.
Referenced by clang::Parser::getTypeAnnotation(), clang::Sema::SemaDiagnosticBuilder::operator TypeResult(), and clang::Parser::TryAnnotateTypeOrScopeToken().
updateFlags()
void clang::updateFlags (const Decl * From, Decl * To)
Definition at line 133 of file ASTImporter.cpp.
References clang::Decl::isUsed(), and clang::Decl::setIsUsed().
Referenced by clang::ASTImporter::Import().
Variable Documentation
AddressColor
const TerminalColor clang::AddressColor = {llvm::raw_ostream::YELLOW, false} static
Definition at line 57 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpPointer().
arch_names
CudaArchToStringMap clang::arch_names[]
Definition at line 65 of file Cuda.cpp.
Referenced by CudaArchToString(), CudaArchToVirtualArchString(), and StringToCudaArch().
AttrColor
const TerminalColor clang::AttrColor = {llvm::raw_ostream::BLUE, true} static
Definition at line 47 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), and clang::TextNodeDumper::VisitOMPRequiresDecl().
CastColor
const TerminalColor clang::CastColor = {llvm::raw_ostream::RED, false} static
Definition at line 76 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::VisitCastExpr().
CommentColor
const TerminalColor clang::CommentColor = {llvm::raw_ostream::BLUE, false} static
Definition at line 51 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit().
DeclKindNameColor
const TerminalColor clang::DeclKindNameColor = {llvm::raw_ostream::GREEN, true} static
Definition at line 45 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpBareDeclRef(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::VisitCXXRecordDecl(), and clang::TextNodeDumper::VisitObjCIvarRefExpr().
DeclNameColor
const TerminalColor clang::DeclNameColor = {llvm::raw_ostream::CYAN, true} static
Definition at line 81 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpBareDeclRef(), clang::ASTDumper::dumpLookups(), and clang::TextNodeDumper::dumpName().
DesiredStackSize
size_t clang::DesiredStackSize = 8 << 20 constexpr
The amount of stack space that Clang would like to be provided with.
If less than this much is available, we may be unable to reach our template instantiation depth limit and other similar limits.
Definition at line 26 of file Stack.h.
Referenced by isStackNearlyExhausted(), and runWithSufficientStackSpaceSlow().
ErrorsColor
const TerminalColor clang::ErrorsColor = {llvm::raw_ostream::RED, true} static
Definition at line 66 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
IndentColor
const TerminalColor clang::IndentColor = {llvm::raw_ostream::BLUE, false} static
Definition at line 84 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::VisitArgumentWithTypeTagAttr().
LargestBuiltinID
uint64_t clang::LargestBuiltinID static constexpr
Initial value:
= std::max<uint64_t>(
      {NEON::FirstTSBuiltin, ARM::LastTSBuiltin, SVE::FirstTSBuiltin,
       AArch64::LastTSBuiltin, BPF::LastTSBuiltin, PPC::LastTSBuiltin,
       NVPTX::LastTSBuiltin, AMDGPU::LastTSBuiltin, X86::LastTSBuiltin,
       Hexagon::LastTSBuiltin, Mips::LastTSBuiltin, XCore::LastTSBuiltin,
       Le64::LastTSBuiltin, SystemZ::LastTSBuiltin,
       WebAssembly::LastTSBuiltin})
Definition at line 323 of file TargetBuiltins.h.
LocationColor
const TerminalColor clang::LocationColor = {llvm::raw_ostream::YELLOW, false} static
Definition at line 59 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpLocation().
NullColor
const TerminalColor clang::NullColor = {llvm::raw_ostream::BLUE, false} static
Definition at line 69 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpBareDeclRef(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), clang::TextNodeDumper::Visit(), and clang::TextNodeDumper::VisitOMPRequiresDecl().
NumberOfOMPMapClauseModifiers
unsigned clang::NumberOfOMPMapClauseModifiers static constexpr
Initial value:
=
    OMPC_MAP_MODIFIER_last - OMPC_MAP_MODIFIER_unknown - 1
Number of allowed map-type-modifiers.
Definition at line 86 of file OpenMPKinds.h.
Referenced by clang::Sema::ActOnOpenMPMapClause(), clang::OMPMapClause::getMapTypeModifier(), and clang::OMPMapClause::getMapTypeModifierLoc().
NumberOfOMPMotionModifiers
unsigned clang::NumberOfOMPMotionModifiers static constexpr
Initial value:
=
    OMPC_MOTION_MODIFIER_unknown
Number of allowed motion-modifiers.
Definition at line 98 of file OpenMPKinds.h.
Referenced by clang::Sema::ActOnOpenMPFromClause(), clang::Sema::ActOnOpenMPToClause(), clang::OMPFromClause::getMotionModifier(), clang::OMPToClause::getMotionModifier(), clang::OMPFromClause::getMotionModifierLoc(), and clang::OMPToClause::getMotionModifierLoc().
ObjCOrBuiltinIDBits
int clang::ObjCOrBuiltinIDBits = 15 static constexpr
Definition at line 51 of file IdentifierTable.h.
ObjectKindColor
const TerminalColor clang::ObjectKindColor = {llvm::raw_ostream::CYAN, false} static
Definition at line 64 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit().
StmtColor
const TerminalColor clang::StmtColor = {llvm::raw_ostream::MAGENTA, true} static
Definition at line 49 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpCleanupObject(), and clang::TextNodeDumper::Visit().
ToggleHighlight
const char clang::ToggleHighlight = 127
Special character that the diagnostic printer will use to toggle the bold attribute.
The character itself will be not be printed.
Definition at line 1764 of file Diagnostic.h.
Referenced by applyTemplateHighlighting().
TypeColor
const TerminalColor clang::TypeColor = {llvm::raw_ostream::GREEN, false} static
Definition at line 54 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::dumpBareType(), and clang::TextNodeDumper::Visit().
UndeserializedColor
const TerminalColor clang::UndeserializedColor static
Initial value:
= {llvm::raw_ostream::GREEN,
                                                  true}
Definition at line 72 of file ASTDumperUtils.h.
Referenced by clang::ASTDumper::dumpLookups(), and clang::TextNodeDumper::Visit().
ValueColor
const TerminalColor clang::ValueColor = {llvm::raw_ostream::CYAN, true} static
Definition at line 79 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit(), clang::TextNodeDumper::VisitCharacterLiteral(), clang::TextNodeDumper::VisitFixedPointLiteral(), clang::TextNodeDumper::VisitFloatingLiteral(), clang::TextNodeDumper::VisitIntegerLiteral(), clang::TextNodeDumper::VisitLifetimeExtendedTemporaryDecl(), and clang::TextNodeDumper::VisitStringLiteral().
ValueKindColor
const TerminalColor clang::ValueKindColor = {llvm::raw_ostream::CYAN, false} static
Definition at line 62 of file ASTDumperUtils.h.
Referenced by clang::TextNodeDumper::Visit(), and clang::TextNodeDumper::Visit().