clang: clang::reachable_code Namespace Reference
clang::reachable_code Namespace Reference
Classes
class Callback
Enumerations
enum UnreachableKind { UK_Return , UK_Break , UK_Loop_Increment , UK_Other }
Classifications of unreachable code.
Functions
unsigned ScanReachableFromBlock (const CFGBlock *Start, llvm::BitVector &Reachable)
ScanReachableFromBlock - Mark all blocks reachable from Start.
void FindUnreachableCode (AnalysisDeclContext &AC, Preprocessor &PP, Callback &CB)
Enumeration Type Documentation
UnreachableKind
enum clang::reachable_code::UnreachableKind
Classifications of unreachable code.
Enumerator
UK_Return
UK_Break
UK_Loop_Increment
UK_Other
Definition at line 40 of file ReachableCode.h.
Function Documentation
FindUnreachableCode()
void clang::reachable_code::FindUnreachableCode (AnalysisDeclContext & AC, Preprocessor & PP, Callback & CB)
Definition at line 679 of file ReachableCode.cpp.
References clang::CFG::BuildOptions::AddEHEdges, clang::CFG::begin(), clang::CFG::end(), FindUnreachableCode(), clang::AnalysisDeclContext::getASTContext(), clang::CFGBlock::getBlockID(), clang::AnalysisDeclContext::getCFG(), clang::AnalysisDeclContext::getCFGBuildOptions(), clang::CFG::getEntry(), clang::CFG::getNumBlockIDs(), scanMaybeReachableFromBlock(), clang::CFG::try_blocks_begin(), and clang::CFG::try_blocks_end().
Referenced by CheckUnreachable(), and FindUnreachableCode().
ScanReachableFromBlock()
unsigned clang::reachable_code::ScanReachableFromBlock (const CFGBlock * Start, llvm::BitVector & Reachable)
ScanReachableFromBlock - Mark all blocks reachable from Start.
Returns the total number of blocks that were marked reachable.
Definition at line 674 of file ReachableCode.cpp.
References scanFromBlock(), and ScanReachableFromBlock().
Referenced by CheckFallThrough(), ScanReachableFromBlock(), and visitReachableThrows().