clang: lib/AST/ParentMap.cpp File Reference
ParentMap.cpp File Reference
#include "clang/AST/ParentMap.h"
#include "clang/AST/Decl.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/StmtObjC.h"
#include "llvm/ADT/DenseMap.h"
Typedefs
typedef llvm::DenseMap< Stmt *, Stmt * > MapTy
Enumerations
enum OpaqueValueMode { OV_Transparent , OV_Opaque }
Functions
static void BuildParentMap (MapTy &M, Stmt *S, OpaqueValueMode OVMode=OV_Transparent)
Typedef Documentation
MapTy
typedef llvm::DenseMap<Stmt*, Stmt*> MapTy
Definition at line 22 of file ParentMap.cpp.
Enumeration Type Documentation
OpaqueValueMode
enum OpaqueValueMode
Enumerator
OV_Transparent
OV_Opaque
Definition at line 24 of file ParentMap.cpp.
Function Documentation
BuildParentMap()
static void BuildParentMap (MapTy & M, Stmt * S, OpaqueValueMode OVMode = OV_Transparent) static
Definition at line 29 of file ParentMap.cpp.
References BuildParentMap(), clang::cast(), clang::BinaryConditionalOperator::getCommon(), clang::BinaryConditionalOperator::getCond(), clang::BinaryConditionalOperator::getFalseExpr(), clang::OpaqueValueExpr::getSourceExpr(), clang::PseudoObjectExpr::getSyntacticForm(), clang::BinaryConditionalOperator::getTrueExpr(), OV_Opaque, OV_Transparent, clang::PseudoObjectExpr::semantics_begin(), and clang::PseudoObjectExpr::semantics_end().
Referenced by clang::ParentMap::addStmt(), BuildParentMap(), and clang::ParentMap::ParentMap().