clang: lib/Tooling/Transformer/Parsing.cpp File Reference
Parsing.cpp File Reference
#include "clang/Tooling/Transformer/Parsing.h"
#include "clang/AST/Expr.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Lex/Lexer.h"
#include "clang/Tooling/Transformer/RangeSelector.h"
#include "clang/Tooling/Transformer/SourceCode.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include <string>
#include <utility>
#include <vector>
Functions
static const llvm::StringMap< RangeSelectorOp< std::string > > & getUnaryStringSelectors ()
static const llvm::StringMap< RangeSelectorOp< RangeSelector > > & getUnaryRangeSelectors ()
static const llvm::StringMap< RangeSelectorOp< std::string, std::string > > & getBinaryStringSelectors ()
static const llvm::StringMap< RangeSelectorOp< RangeSelector, RangeSelector > > & getBinaryRangeSelectors ()
template<typename Element >
llvm::Optional< Element > findOptional (const llvm::StringMap< Element > &Map, llvm::StringRef Key)
template<typename ResultType >
ParseProgress< ResultType > makeParseProgress (ParseState State, ResultType Result)
static llvm::Error makeParseError (const ParseState &S, std::string ErrorMsg)
static ParseState advance (ParseState S, size_t N)
static StringRef consumeWhitespace (StringRef S)
static ExpectedProgress< llvm::NoneType > parseChar (char c, ParseState State)
static ExpectedProgress< std::string > parseId (ParseState State)
static ExpectedProgress< std::string > parseStringId (ParseState State)
template<typename T >
ExpectedProgress< RangeSelector > parseSingle (ParseFunction< T > ParseElement, RangeSelectorOp< T > Op, ParseState State)
template<typename T >
ExpectedProgress< RangeSelector > parsePair (ParseFunction< T > ParseElement, RangeSelectorOp< T, T > Op, ParseState State)
static ExpectedProgress< RangeSelector > parseRangeSelectorImpl (ParseState State)
Function Documentation
advance()
static ParseState advance (ParseState S, size_t N) static
Definition at line 145 of file Parsing.cpp.
References N.
Referenced by TokenCollector::Builder::build(), parseChar(), parseId(), and parseStringId().
consumeWhitespace()
static StringRef consumeWhitespace (StringRef S) static
Definition at line 150 of file Parsing.cpp.
References c, clang::isASCII(), and clang::isWhitespace().
Referenced by parseChar(), parseId(), clang::transformer::parseRangeSelector(), and parseStringId().
findOptional()
template<typename Element > llvm::Optional< Element > findOptional (const llvm::StringMap< Element > & Map, llvm::StringRef Key)
Definition at line 124 of file Parsing.cpp.
Referenced by parseRangeSelectorImpl().
getBinaryRangeSelectors()
static const llvm::StringMap< RangeSelectorOp< RangeSelector, RangeSelector > > & getBinaryRangeSelectors () static
Definition at line 117 of file Parsing.cpp.
References clang::transformer::between(), and clang::transformer::enclose().
Referenced by parseRangeSelectorImpl().
getBinaryStringSelectors()
static const llvm::StringMap< RangeSelectorOp< std::string, std::string > > & getBinaryStringSelectors () static
Definition at line 110 of file Parsing.cpp.
References clang::transformer::encloseNodes().
Referenced by parseRangeSelectorImpl().
getUnaryRangeSelectors()
static const llvm::StringMap< RangeSelectorOp< RangeSelector > > & getUnaryRangeSelectors () static
Definition at line 103 of file Parsing.cpp.
References clang::transformer::after(), clang::transformer::before(), and clang::transformer::expansion().
Referenced by parseRangeSelectorImpl().
getUnaryStringSelectors()
static const llvm::StringMap< RangeSelectorOp< std::string > > & getUnaryStringSelectors () static
Definition at line 89 of file Parsing.cpp.
References clang::transformer::callArgs(), clang::transformer::elseBranch(), clang::transformer::initListElements(), clang::transformer::member(), clang::transformer::name(), clang::transformer::node(), clang::transformer::statement(), and clang::transformer::statements().
Referenced by parseRangeSelectorImpl().
makeParseError()
static llvm::Error makeParseError (const ParseState & S, std::string ErrorMsg) static
Definition at line 138 of file Parsing.cpp.
Referenced by parseChar(), parseId(), clang::transformer::parseRangeSelector(), parseRangeSelectorImpl(), and parseStringId().
makeParseProgress()
template<typename ResultType > ParseProgress< ResultType > makeParseProgress (ParseState State, ResultType Result)
Definition at line 133 of file Parsing.cpp.
References clang::Result, and State.
Referenced by parseChar(), parseId(), parsePair(), parseSingle(), and parseStringId().
parseChar()
static ExpectedProgress< llvm::NoneType > parseChar (char c, ParseState State) static
Definition at line 156 of file Parsing.cpp.
References advance(), c, consumeWhitespace(), makeParseError(), and makeParseProgress().
Referenced by parsePair(), and parseSingle().
parseId()
static ExpectedProgress< std::string > parseId (ParseState State) static
Definition at line 165 of file Parsing.cpp.
References advance(), c, consumeWhitespace(), Id, clang::isASCII(), clang::isIdentifierBody(), makeParseError(), and makeParseProgress().
Referenced by parseRangeSelectorImpl().
parsePair()
template<typename T > ExpectedProgress< RangeSelector > parsePair (ParseFunction< T > ParseElement, RangeSelectorOp< T, T > Op, ParseState State)
Definition at line 216 of file Parsing.cpp.
References makeParseProgress(), P, and parseChar().
Referenced by parseRangeSelectorImpl().
parseRangeSelectorImpl()
static ExpectedProgress< RangeSelector > parseRangeSelectorImpl (ParseState State) static
Definition at line 247 of file Parsing.cpp.
References findOptional(), getBinaryRangeSelectors(), getBinaryStringSelectors(), getUnaryRangeSelectors(), getUnaryStringSelectors(), Id, makeParseError(), parseId(), parsePair(), parseRangeSelectorImpl(), parseSingle(), and parseStringId().
Referenced by clang::transformer::parseRangeSelector(), and parseRangeSelectorImpl().
parseSingle()
template<typename T > ExpectedProgress< RangeSelector > parseSingle (ParseFunction< T > ParseElement, RangeSelectorOp< T > Op, ParseState State)
Definition at line 195 of file Parsing.cpp.
References makeParseProgress(), P, and parseChar().
Referenced by parseRangeSelectorImpl().
parseStringId()
static ExpectedProgress< std::string > parseStringId (ParseState State) static
Definition at line 176 of file Parsing.cpp.
References advance(), c, consumeWhitespace(), Id, makeParseError(), and makeParseProgress().
Referenced by parseRangeSelectorImpl().