clang: lib/Analysis/PathDiagnostic.cpp File Reference
PathDiagnostic.cpp File Reference
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/Type.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Analysis/CFG.h"
#include "clang/Analysis/ProgramPoint.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstring>
#include <memory>
#include <utility>
#include <vector>
Functions
static StringRef StripTrailingDots (StringRef s)
static Optional< bool > comparePath (const PathPieces &X, const PathPieces &Y)
static Optional< bool > compareControlFlow (const PathDiagnosticControlFlowPiece &X, const PathDiagnosticControlFlowPiece &Y)
static Optional< bool > compareMacro (const PathDiagnosticMacroPiece &X, const PathDiagnosticMacroPiece &Y)
static Optional< bool > compareCall (const PathDiagnosticCallPiece &X, const PathDiagnosticCallPiece &Y)
static Optional< bool > comparePiece (const PathDiagnosticPiece &X, const PathDiagnosticPiece &Y)
static bool compareCrossTUSourceLocs (FullSourceLoc XL, FullSourceLoc YL)
static bool compare (const PathDiagnostic &X, const PathDiagnostic &Y)
static PathDiagnosticLocation getLocationForCaller (const StackFrameContext *SFC, const LocationContext *CallerCtx, const SourceManager &SM)
static void describeTemplateParameters (raw_ostream &Out, const ArrayRef< TemplateArgument > TAList, const LangOptions &LO, StringRef Prefix=StringRef(), StringRef Postfix=StringRef())
static void describeTemplateParameter (raw_ostream &Out, const TemplateArgument &TArg, const LangOptions &LO)
static void describeClass (raw_ostream &Out, const CXXRecordDecl *D, StringRef Prefix=StringRef())
static bool describeCodeDecl (raw_ostream &Out, const Decl *D, bool ExtendedDescription, StringRef Prefix=StringRef())
static void compute_path_size (const PathPieces &pieces, unsigned &size)
Function Documentation
compare()
static bool compare (const PathDiagnostic & X, const PathDiagnostic & Y) static
Definition at line 351 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), b, compareCrossTUSourceLocs(), comparePath(), clang::ento::PathDiagnostic::getBugType(), clang::ento::PathDiagnostic::getCategory(), clang::ento::PathDiagnostic::getDeclWithIssue(), clang::Decl::getLocation(), clang::ento::PathDiagnostic::getLocation(), clang::FullSourceLoc::getManager(), clang::ento::PathDiagnostic::getShortDescription(), clang::ento::PathDiagnostic::getUniqueingDecl(), clang::ento::PathDiagnostic::getUniqueingLoc(), clang::ento::PathDiagnostic::getVerboseDescription(), clang::SourceLocation::isValid(), clang::ento::PathDiagnostic::meta_begin(), clang::ento::PathDiagnostic::meta_end(), clang::None, clang::ento::PathDiagnostic::path, clang::Result, SM, and X().
Referenced by clang::ento::PathDiagnosticConsumer::FlushDiagnostics(), and clang::ASTContext::ObjCQualifiedIdTypesAreCompatible().
compareCall()
static Optional< bool > compareCall (const PathDiagnosticCallPiece & X, const PathDiagnosticCallPiece & Y) static
Definition at line 250 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::PathDiagnosticCallPiece::callEnter, clang::ento::PathDiagnosticCallPiece::callEnterWithin, clang::ento::PathDiagnosticCallPiece::callReturn, comparePath(), clang::FullSourceLoc::isBeforeInTranslationUnitThan(), clang::ento::PathDiagnosticCallPiece::path, and X().
Referenced by comparePiece().
compareControlFlow()
static Optional< bool > compareControlFlow (const PathDiagnosticControlFlowPiece & X, const PathDiagnosticControlFlowPiece & Y) static
Definition at line 232 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::PathDiagnosticControlFlowPiece::getEndLocation(), clang::ento::PathDiagnosticControlFlowPiece::getStartLocation(), clang::FullSourceLoc::isBeforeInTranslationUnitThan(), clang::None, and X().
Referenced by comparePiece().
compareCrossTUSourceLocs()
static bool compareCrossTUSourceLocs (FullSourceLoc XL, FullSourceLoc YL) static
Definition at line 329 of file PathDiagnostic.cpp.
References clang::FullSourceLoc::getDecomposedLoc(), clang::FullSourceLoc::getFileID(), clang::FullSourceLoc::getManager(), clang::FileEntry::getName(), clang::FullSourceLoc::getSpellingLoc(), clang::FullSourceLoc::isBeforeInTranslationUnitThan(), clang::SourceManager::isInTheSameTranslationUnit(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isValid(), and SM.
Referenced by compare().
compareMacro()
static Optional< bool > compareMacro (const PathDiagnosticMacroPiece & X, const PathDiagnosticMacroPiece & Y) static
Definition at line 245 of file PathDiagnostic.cpp.
References comparePath(), clang::ento::PathDiagnosticMacroPiece::subPieces, and X().
Referenced by comparePiece().
comparePath()
static Optional< bool > comparePath (const PathPieces & X, const PathPieces & Y) static
Definition at line 313 of file PathDiagnostic.cpp.
References b, comparePiece(), clang::None, and X().
Referenced by compare(), compareCall(), and compareMacro().
comparePiece()
static Optional< bool > comparePiece (const PathDiagnosticPiece & X, const PathDiagnosticPiece & Y) static
Definition at line 267 of file PathDiagnostic.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::PathDiagnosticPiece::Call, compareCall(), compareControlFlow(), compareMacro(), clang::ento::PathDiagnosticPiece::ControlFlow, clang::ento::PathDiagnosticPiece::Event, clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::ento::PathDiagnosticPiece::getKind(), clang::ento::PathDiagnosticPiece::getLocation(), clang::FullSourceLoc::getManager(), clang::ento::PathDiagnosticPiece::getRanges(), clang::ento::PathDiagnosticPiece::getString(), clang::FullSourceLoc::isBeforeInTranslationUnitThan(), clang::ento::PathDiagnosticPiece::Macro, clang::None, clang::ento::PathDiagnosticPiece::Note, clang::ento::PathDiagnosticPiece::PopUp, SM, and X().
Referenced by comparePath().
compute_path_size()
static void compute_path_size (const PathPieces & pieces, unsigned & size) static
Definition at line 1065 of file PathDiagnostic.cpp.
References compute_path_size().
Referenced by compute_path_size(), and clang::ento::PathDiagnostic::full_size().
describeClass()
static void describeClass (raw_ostream & Out, const CXXRecordDecl * D, StringRef Prefix = StringRef()) static
Definition at line 921 of file PathDiagnostic.cpp.
References describeTemplateParameters(), and clang::NamedDecl::getIdentifier().
Referenced by describeCodeDecl().
describeCodeDecl()
static bool describeCodeDecl (raw_ostream & Out, const Decl * D, bool ExtendedDescription, StringRef Prefix = StringRef()) static
Definition at line 933 of file PathDiagnostic.cpp.
References describeClass(), and describeTemplateParameters().
Referenced by clang::ento::PathDiagnosticCallPiece::getCallEnterEvent(), clang::ento::PathDiagnosticCallPiece::getCallEnterWithinCallerEvent(), and clang::ento::PathDiagnosticCallPiece::getCallExitEvent().
describeTemplateParameter()
static void describeTemplateParameter (raw_ostream & Out, const TemplateArgument & TArg, const LangOptions & LO) static
Definition at line 894 of file PathDiagnostic.cpp.
References describeTemplateParameters(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getPackAsArray(), clang::TemplateArgument::Pack, and clang::TemplateArgument::print().
Referenced by describeTemplateParameters().
describeTemplateParameters()
static void describeTemplateParameters (raw_ostream & Out, const ArrayRef< TemplateArgument > TAList, const LangOptions & LO, StringRef Prefix = StringRef(), StringRef Postfix = StringRef()) static
Definition at line 905 of file PathDiagnostic.cpp.
References describeTemplateParameter(), and clang::Last.
Referenced by describeClass(), describeCodeDecl(), and describeTemplateParameter().
getLocationForCaller()
static PathDiagnosticLocation getLocationForCaller (const StackFrameContext * SFC, const LocationContext * CallerCtx, const SourceManager & SM) static
Definition at line 523 of file PathDiagnostic.cpp.
References clang::CFGElement::AutomaticObjectDtor, clang::CFGElement::BaseDtor, clang::Block, clang::CFGElement::castAs(), clang::CFGElement::Constructor, clang::ento::PathDiagnosticLocation::create(), clang::ento::PathDiagnosticLocation::createEnd(), clang::CFGElement::CXXRecordTypedCall, clang::CFGElement::DeleteDtor, clang::CFGNewAllocator::getAllocatorExpr(), clang::LocationContext::getAnalysisDeclContext(), clang::AnalysisDeclContext::getBody(), clang::StackFrameContext::getCallSiteBlock(), clang::AnalysisDeclContext::getDecl(), clang::CFGDeleteDtor::getDeleteExpr(), clang::StackFrameContext::getIndex(), clang::CFGStmt::getStmt(), clang::CFGAutomaticObjDtor::getTriggerStmt(), clang::CFGElement::Initializer, clang::CFGElement::LifetimeEnds, clang::CFGElement::LoopExit, clang::CFGElement::MemberDtor, clang::CFGElement::NewAllocator, clang::CFGElement::ScopeBegin, clang::CFGElement::ScopeEnd, SM, clang::CFGElement::Statement, and clang::CFGElement::TemporaryDtor.
Referenced by clang::ento::PathDiagnosticCallPiece::construct(), clang::ento::PathDiagnosticLocation::create(), and clang::ento::PathDiagnosticCallPiece::setCallee().
StripTrailingDots()
static StringRef StripTrailingDots (StringRef s) static
Definition at line 54 of file PathDiagnostic.cpp.
References s.