clang: lib/Lex/PPExpressions.cpp File Reference
PPExpressions.cpp File Reference
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Lex/CodeCompletionHandler.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/Token.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include <cassert>
Classes
struct DefinedTracker
DefinedTracker - This struct is used while parsing expressions to keep track of whether !defined(X) has been seen.
Functions
static bool EvaluateDirectiveSubExpr (PPValue &LHS, unsigned MinPrec, Token &PeekTok, bool ValueLive, bool &IncludedUndefinedIds, Preprocessor &PP)
EvaluateDirectiveSubExpr - Evaluate the subexpression whose first token is PeekTok, and whose precedence is PeekPrec.
static bool EvaluateDefined (PPValue &Result, Token &PeekTok, DefinedTracker &DT, bool ValueLive, Preprocessor &PP)
EvaluateDefined - Process a 'defined(sym)' expression.
static bool EvaluateValue (PPValue &Result, Token &PeekTok, DefinedTracker &DT, bool ValueLive, Preprocessor &PP)
EvaluateValue - Evaluate the token PeekTok (and any others needed) and return the computed value in Result.
static unsigned getPrecedence (tok::TokenKind Kind)
getPrecedence - Return the precedence of the specified binary operator token.
static void diagnoseUnexpectedOperator (Preprocessor &PP, PPValue &LHS, Token &Tok)
Function Documentation
diagnoseUnexpectedOperator()
static void diagnoseUnexpectedOperator (Preprocessor & PP, PPValue & LHS, Token & Tok) static
Definition at line 547 of file PPExpressions.cpp.
References clang::Preprocessor::Diag(), clang::Token::getLocation(), clang::Token::is(), and Tok.
Referenced by EvaluateDirectiveSubExpr().
EvaluateDefined()
static bool EvaluateDefined (PPValue & Result, Token & PeekTok, DefinedTracker & DT, bool ValueLive, Preprocessor & PP) static
EvaluateDefined - Process a 'defined(sym)' expression.
Definition at line 102 of file PPExpressions.cpp.
References clang::Preprocessor::CheckMacroName(), clang::CodeCompletionHandler::CodeCompleteMacroName(), DefinedTracker::DefinedMacro, clang::Preprocessor::Diag(), clang::Preprocessor::getCodeCompletionHandler(), clang::SrcMgr::SLocEntry::getExpansion(), clang::SourceManager::getFileID(), clang::Token::getIdentifierInfo(), clang::Token::getLocation(), clang::Preprocessor::getMacroDefinition(), clang::Preprocessor::getPPCallbacks(), clang::SourceManager::getSLocEntry(), clang::Preprocessor::getSourceManager(), DefinedTracker::IncludedUndefinedIds, clang::Token::is(), clang::SrcMgr::ExpansionInfo::isFunctionMacroExpansion(), clang::SourceLocation::isMacroID(), clang::Token::isNot(), clang::SourceLocation::isValid(), clang::Preprocessor::LexNonComment(), clang::Preprocessor::LexUnexpandedNonComment(), clang::Preprocessor::markMacroAsUsed(), clang::MU_Other, clang::Result, clang::Preprocessor::setCodeCompletionReached(), DefinedTracker::State, and DefinedTracker::TheMacro.
Referenced by EvaluateValue().
EvaluateDirectiveSubExpr()
static bool EvaluateDirectiveSubExpr (PPValue & LHS, unsigned MinPrec, Token & PeekTok, bool ValueLive, bool & IncludedUndefinedIds, Preprocessor & PP) static
EvaluateDirectiveSubExpr - Evaluate the subexpression whose first token is PeekTok, and whose precedence is PeekPrec.
This returns the result in LHS.
If ValueLive is false, then this value is being evaluated in a context where the result is not used. As such, avoid diagnostics that relate to evaluation, such as division by zero warnings.
Definition at line 563 of file PPExpressions.cpp.
References clang::Preprocessor::Diag(), diagnoseUnexpectedOperator(), EvaluateDirectiveSubExpr(), EvaluateValue(), clang::Token::getKind(), clang::Preprocessor::getLangOpts(), clang::Token::getLocation(), getPrecedence(), DefinedTracker::IncludedUndefinedIds, clang::Token::isNot(), and clang::Preprocessor::LexNonComment().
Referenced by EvaluateDirectiveSubExpr(), and EvaluateValue().
EvaluateValue()
static bool EvaluateValue (PPValue & Result, Token & PeekTok, DefinedTracker & DT, bool ValueLive, Preprocessor & PP) static
EvaluateValue - Evaluate the token PeekTok (and any others needed) and return the computed value in Result.
Return true if there was an error parsing. This function also returns information about the form of the expression in DT. See above for information on what DT means.
If ValueLive is false, then this value is being evaluated in a context where the result is not used. As such, avoid diagnostics that relate to evaluation.
Definition at line 229 of file PPExpressions.cpp.
References clang::CodeCompletionHandler::CodeCompletePreprocessorExpression(), DefinedTracker::DefinedMacro, clang::Preprocessor::Diag(), EvaluateDefined(), EvaluateDirectiveSubExpr(), EvaluateValue(), clang::TargetInfo::getChar16Width(), clang::TargetInfo::getChar32Width(), clang::TargetInfo::getCharWidth(), clang::Preprocessor::getCodeCompletionHandler(), clang::DiagnosticsEngine::getDiagnosticOptions(), clang::Preprocessor::getDiagnostics(), clang::Token::getIdentifierInfo(), clang::NumericLiteralParser::GetIntegerValue(), clang::TargetInfo::getIntWidth(), clang::Token::getKind(), clang::Preprocessor::getLangOpts(), clang::Token::getLocation(), clang::IdentifierInfo::getName(), clang::NumericLiteralParser::getRadix(), clang::Preprocessor::getSourceManager(), clang::Preprocessor::getSpelling(), clang::Preprocessor::getTargetInfo(), clang::CharLiteralParser::getValue(), clang::TargetInfo::getWCharType(), clang::TargetInfo::getWCharWidth(), clang::CharLiteralParser::hadError(), clang::NumericLiteralParser::hadError, clang::NumericLiteralParser::hasUDSuffix(), clang::Token::hasUDSuffix(), DefinedTracker::IncludedUndefinedIds, clang::Token::is(), clang::IdentifierInfo::isCPlusPlusOperatorKeyword(), clang::NumericLiteralParser::isFloatingLiteral(), clang::DiagnosticsEngine::isIgnored(), clang::NumericLiteralParser::isImaginary, clang::NumericLiteralParser::isIntegerLiteral(), clang::NumericLiteralParser::isLongLong, clang::CharLiteralParser::isMultiChar(), clang::Token::isNot(), clang::IdentifierInfo::isStr(), clang::TargetInfo::isTypeSigned(), clang::NumericLiteralParser::isUnsigned, clang::CharLiteralParser::isUTF16(), clang::CharLiteralParser::isUTF32(), clang::CharLiteralParser::isWide(), clang::Preprocessor::LexNonComment(), DefinedTracker::NotDefinedMacro, clang::Result, clang::Preprocessor::setCodeCompletionReached(), DefinedTracker::State, clang::DiagnosticOptions::UndefPrefixes, and DefinedTracker::Unknown.
Referenced by EvaluateDirectiveSubExpr(), and EvaluateValue().
getPrecedence()
static unsigned getPrecedence (tok::TokenKind Kind) static
getPrecedence - Return the precedence of the specified binary operator token.
This returns: ~0 - Invalid token. 14 -> 3 - various operators. 0 - 'eod' or ')'
Definition at line 518 of file PPExpressions.cpp.
Referenced by EvaluateDirectiveSubExpr().