clang: lib/Lex/PPMacroExpansion.cpp File Reference
PPMacroExpansion.cpp File Reference
#include "clang/Basic/Attributes.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/CodeCompletionHandler.h"
#include "clang/Lex/DirectoryLookup.h"
#include "clang/Lex/ExternalPreprocessorSource.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/MacroArgs.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/PreprocessorLexer.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Lex/Token.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <ctime>
#include <string>
#include <tuple>
#include <utility>
#include "clang/Basic/Features.def"
Macros
#define FEATURE(Name, Predicate)
#define EXTENSION(Name, Predicate)
Enumerations
enum Bracket { Brace , Paren }
Functions
static IdentifierInfo * RegisterBuiltinMacro (Preprocessor &PP, const char *Name)
RegisterBuiltinMacro - Register the specified identifier in the identifier table and mark it as a builtin macro to be expanded.
static bool isTrivialSingleTokenExpansion (const MacroInfo *MI, const IdentifierInfo *MacroIdent, Preprocessor &PP)
isTrivialSingleTokenExpansion - Return true if MI, which has a single token in its expansion, currently expands to that token literally.
static bool CheckMatchedBrackets (const SmallVectorImpl< Token > &Tokens)
CheckMatchedBrackets - Returns true if the braces and parentheses in the token vector are properly nested.
static bool GenerateNewArgTokens (Preprocessor &PP, SmallVectorImpl< Token > &OldTokens, SmallVectorImpl< Token > &NewTokens, unsigned &NumArgs, SmallVectorImpl< SourceRange > &ParenHints, SmallVectorImpl< SourceRange > &InitLists)
GenerateNewArgTokens - Returns true if OldTokens can be converted to a new vector of tokens in NewTokens.
static void ComputeDATE_TIME (SourceLocation &DATELoc, SourceLocation &TIMELoc, Preprocessor &PP)
ComputeDATE_TIME - Compute the current time, enter it into the specified scratch buffer, then return DATELoc/TIMELoc locations with the position of the identifier tokens inserted.
static bool HasFeature (const Preprocessor &PP, StringRef Feature)
HasFeature - Return true if we recognize and implement the feature specified by the identifier as a standard language feature.
static bool HasExtension (const Preprocessor &PP, StringRef Extension)
HasExtension - Return true if we recognize and implement the feature specified by the identifier, either as an extension or a standard language feature.
static bool EvaluateHasIncludeCommon (Token &Tok, IdentifierInfo *II, Preprocessor &PP, const DirectoryLookup *LookupFrom, const FileEntry *LookupFromFile)
EvaluateHasIncludeCommon - Process a '__has_include("path")' or '__has_include_next("path")' expression.
static bool EvaluateHasInclude (Token &Tok, IdentifierInfo *II, Preprocessor &PP)
EvaluateHasInclude - Process a '__has_include("path")' expression.
static bool EvaluateHasIncludeNext (Token &Tok, IdentifierInfo *II, Preprocessor &PP)
EvaluateHasIncludeNext - Process '__has_include_next("path")' expression.
static void EvaluateFeatureLikeBuiltinMacro (llvm::raw_svector_ostream &OS, Token &Tok, IdentifierInfo *II, Preprocessor &PP, llvm::function_ref< int(Token &Tok, bool &HasLexedNextTok)> Op)
Process single-argument builtin feature-like macros that return integer values.
static IdentifierInfo * ExpectFeatureIdentifierInfo (Token &Tok, Preprocessor &PP, signed DiagID)
Helper function to return the IdentifierInfo structure of a Token or generate a diagnostic if none available.
static bool isTargetArch (const TargetInfo &TI, const IdentifierInfo *II)
Implements the __is_target_arch builtin macro.
static bool isTargetVendor (const TargetInfo &TI, const IdentifierInfo *II)
Implements the __is_target_vendor builtin macro.
static bool isTargetOS (const TargetInfo &TI, const IdentifierInfo *II)
Implements the __is_target_os builtin macro.
static bool isTargetEnvironment (const TargetInfo &TI, const IdentifierInfo *II)
Implements the __is_target_environment builtin macro.
static void remapMacroPath (SmallString< 256 > &Path, const std::map< std::string, std::string, std::greater< std::string > > &MacroPrefixMap)
Macro Definition Documentation
EXTENSION
#define EXTENSION (Name, Predicate)
Value:
.Case(#Name, Predicate)
FEATURE
#define FEATURE (Name, Predicate)
Value:
.Case(#Name, Predicate)
Enumeration Type Documentation
Bracket
enum Bracket
Enumerator
Brace
Paren
Definition at line 627 of file PPMacroExpansion.cpp.
Function Documentation
CheckMatchedBrackets()
static bool CheckMatchedBrackets (const SmallVectorImpl< Token > & Tokens) static
CheckMatchedBrackets - Returns true if the braces and parentheses in the token vector are properly nested.
Definition at line 634 of file PPMacroExpansion.cpp.
References Brace, and Paren.
Referenced by GenerateNewArgTokens().
ComputeDATE_TIME()
static void ComputeDATE_TIME (SourceLocation & DATELoc, SourceLocation & TIMELoc, Preprocessor & PP) static
ComputeDATE_TIME - Compute the current time, enter it into the specified scratch buffer, then return DATELoc/TIMELoc locations with the position of the identifier tokens inserted.
Definition at line 1075 of file PPMacroExpansion.cpp.
References clang::Preprocessor::CreateString(), clang::Token::getLocation(), and clang::Token::startToken().
EvaluateFeatureLikeBuiltinMacro()
static void EvaluateFeatureLikeBuiltinMacro (llvm::raw_svector_ostream & OS, Token & Tok, IdentifierInfo * II, Preprocessor & PP, llvm::function_ref< int(Token &Tok, bool &HasLexedNextTok)> Op) static
Process single-argument builtin feature-like macros that return integer values.
Definition at line 1286 of file PPMacroExpansion.cpp.
References clang::Preprocessor::Diag(), Diag(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), clang::Token::getLocation(), clang::Token::isNot(), clang::Token::isOneOf(), clang::Preprocessor::LexUnexpandedToken(), clang::Result, clang::Token::setKind(), and Tok.
EvaluateHasInclude()
static bool EvaluateHasInclude (Token & Tok, IdentifierInfo * II, Preprocessor & PP) static
EvaluateHasInclude - Process a '__has_include("path")' expression.
Returns true if successful.
Definition at line 1245 of file PPMacroExpansion.cpp.
References EvaluateHasIncludeCommon(), and Tok.
EvaluateHasIncludeCommon()
static bool EvaluateHasIncludeCommon (Token & Tok, IdentifierInfo * II, Preprocessor & PP, const DirectoryLookup * LookupFrom, const FileEntry * LookupFromFile) static
EvaluateHasIncludeCommon - Process a '__has_include("path")' or '__has_include_next("path")' expression.
Returns true if successful.
Definition at line 1155 of file PPMacroExpansion.cpp.
References clang::SrcMgr::C_User, clang::Preprocessor::Diag(), clang::File, Filename, clang::HeaderSearch::getFileDirFlavor(), clang::Preprocessor::getHeaderSearchInfo(), clang::Preprocessor::GetIncludeFilenameSpelling(), clang::Token::getKind(), clang::Token::getLocation(), clang::Preprocessor::getLocForEndOfToken(), clang::Preprocessor::getPPCallbacks(), clang::Preprocessor::getSpelling(), clang::Token::is(), clang::Token::isNot(), clang::Preprocessor::isParsingIfOrElifDirective(), clang::Preprocessor::LexHeaderName(), clang::Preprocessor::LexNonComment(), clang::Preprocessor::LookupFile(), clang::Token::setIdentifierInfo(), and Tok.
Referenced by EvaluateHasInclude(), and EvaluateHasIncludeNext().
EvaluateHasIncludeNext()
static bool EvaluateHasIncludeNext (Token & Tok, IdentifierInfo * II, Preprocessor & PP) static
EvaluateHasIncludeNext - Process '__has_include_next("path")' expression.
Returns true if successful.
Definition at line 1252 of file PPMacroExpansion.cpp.
References clang::Preprocessor::Diag(), EvaluateHasIncludeCommon(), clang::Preprocessor::GetCurDirLookup(), clang::Preprocessor::getCurrentLexer(), clang::Preprocessor::getCurrentLexerSubmodule(), clang::PreprocessorLexer::getFileEntry(), clang::Preprocessor::getLangOpts(), clang::LangOptions::IsHeaderFile, clang::Preprocessor::isInPrimaryFile(), and Tok.
ExpectFeatureIdentifierInfo()
static IdentifierInfo * ExpectFeatureIdentifierInfo (Token & Tok, Preprocessor & PP, signed DiagID) static
Helper function to return the IdentifierInfo structure of a Token or generate a diagnostic if none available.
Definition at line 1393 of file PPMacroExpansion.cpp.
References clang::Preprocessor::Diag(), clang::Token::getIdentifierInfo(), clang::Token::getLocation(), clang::Token::isAnnotation(), and Tok.
GenerateNewArgTokens()
static bool GenerateNewArgTokens (Preprocessor & PP, SmallVectorImpl< Token > & OldTokens, SmallVectorImpl< Token > & NewTokens, unsigned & NumArgs, SmallVectorImpl< SourceRange > & ParenHints, SmallVectorImpl< SourceRange > & InitLists) static
GenerateNewArgTokens - Returns true if OldTokens can be converted to a new vector of tokens in NewTokens.
The new number of arguments will be placed in NumArgs and the ranges which need to surrounded in parentheses will be in ParenHints. Returns false if the token stream cannot be changed. If this is because of an initializer list starting a macro argument, the range of those initializer lists will be place in InitLists.
Definition at line 663 of file PPMacroExpansion.cpp.
References CheckMatchedBrackets(), clang::Preprocessor::getLocForEndOfToken(), clang::Token::setKind(), clang::Token::setLength(), clang::Token::setLocation(), and clang::Token::startToken().
HasExtension()
static bool HasExtension (const Preprocessor & PP, StringRef Extension) static
HasExtension - Return true if we recognize and implement the feature specified by the identifier, either as an extension or a standard language feature.
Definition at line 1126 of file PPMacroExpansion.cpp.
References clang::diag::Error, clang::Preprocessor::getDiagnostics(), clang::DiagnosticsEngine::getExtensionHandlingBehavior(), clang::Preprocessor::getLangOpts(), and HasFeature().
HasFeature()
static bool HasFeature (const Preprocessor & PP, StringRef Feature) static
HasFeature - Return true if we recognize and implement the feature specified by the identifier as a standard language feature.
Definition at line 1109 of file PPMacroExpansion.cpp.
References clang::Preprocessor::getLangOpts().
Referenced by HasExtension(), and hasFeature().
isTargetArch()
static bool isTargetArch (const TargetInfo & TI, const IdentifierInfo * II) static
Implements the __is_target_arch builtin macro.
Definition at line 1405 of file PPMacroExpansion.cpp.
References clang::IdentifierInfo::getName(), and clang::TargetInfo::getTriple().
isTargetEnvironment()
static bool isTargetEnvironment (const TargetInfo & TI, const IdentifierInfo * II) static
Implements the __is_target_environment builtin macro.
Definition at line 1447 of file PPMacroExpansion.cpp.
References clang::IdentifierInfo::getName(), and clang::TargetInfo::getTriple().
isTargetOS()
static bool isTargetOS (const TargetInfo & TI, const IdentifierInfo * II) static
Implements the __is_target_os builtin macro.
Definition at line 1435 of file PPMacroExpansion.cpp.
References clang::IdentifierInfo::getName(), and clang::TargetInfo::getTriple().
isTargetVendor()
static bool isTargetVendor (const TargetInfo & TI, const IdentifierInfo * II) static
Implements the __is_target_vendor builtin macro.
Definition at line 1427 of file PPMacroExpansion.cpp.
References clang::IdentifierInfo::getName(), and clang::TargetInfo::getTriple().
isTrivialSingleTokenExpansion()
static bool isTrivialSingleTokenExpansion (const MacroInfo * MI, const IdentifierInfo * MacroIdent, Preprocessor & PP) static
isTrivialSingleTokenExpansion - Return true if MI, which has a single token in its expansion, currently expands to that token literally.
Definition at line 400 of file PPMacroExpansion.cpp.
References clang::Preprocessor::getExternalSource(), clang::Token::getIdentifierInfo(), clang::Preprocessor::getMacroInfo(), clang::MacroInfo::getReplacementToken(), clang::MacroInfo::isObjectLike(), clang::IdentifierInfo::isOutOfDate(), clang::MacroInfo::param_begin(), clang::MacroInfo::param_end(), and clang::ExternalPreprocessorSource::updateOutOfDateIdentifier().
RegisterBuiltinMacro()
static IdentifierInfo * RegisterBuiltinMacro (Preprocessor & PP, const char * Name) static
RegisterBuiltinMacro - Register the specified identifier in the identifier table and mark it as a builtin macro to be expanded.
Definition at line 326 of file PPMacroExpansion.cpp.
References clang::Preprocessor::AllocateMacroInfo(), clang::Preprocessor::appendDefMacroDirective(), clang::Preprocessor::getIdentifierInfo(), Id, and clang::MacroInfo::setIsBuiltinMacro().
remapMacroPath()
static void remapMacroPath (SmallString< 256 > & Path, const std::map< std::string, std::string, std::greater< std::string > > & MacroPrefixMap) static
Definition at line 1454 of file PPMacroExpansion.cpp.