clang: lib/Frontend/PrintPreprocessedOutput.cpp File Reference
PrintPreprocessedOutput.cpp File Reference
#include "clang/Frontend/Utils.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Frontend/PreprocessorOutputOptions.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Pragma.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/TokenConcatenation.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdio>
Typedefs
typedef std::pair< const IdentifierInfo *, MacroInfo * > id_macro_pair
Functions
static void PrintMacroDefinition (const IdentifierInfo &II, const MacroInfo &MI, Preprocessor &PP, raw_ostream &OS)
PrintMacroDefinition - Print a macro definition in a form that will be properly accepted back as a definition.
static void outputPrintable (raw_ostream &OS, StringRef Str)
static void PrintPreprocessedTokens (Preprocessor &PP, Token &Tok, PrintPPOutputPPCallbacks *Callbacks, raw_ostream &OS)
static int MacroIDCompare (const id_macro_pair *LHS, const id_macro_pair *RHS)
static void DoPrintMacros (Preprocessor &PP, raw_ostream *OS)
Typedef Documentation
id_macro_pair
typedef std::pair<const IdentifierInfo *, MacroInfo *> id_macro_pair
Definition at line 820 of file PrintPreprocessedOutput.cpp.
Function Documentation
DoPrintMacros()
static void DoPrintMacros (Preprocessor & PP, raw_ostream * OS) static
Definition at line 825 of file PrintPreprocessedOutput.cpp.
References clang::Preprocessor::EnterMainSourceFile(), clang::MacroDefinition::getMacroInfo(), clang::Preprocessor::IgnorePragmas(), clang::MacroInfo::isBuiltinMacro(), clang::Token::isNot(), clang::Preprocessor::Lex(), clang::Preprocessor::macro_begin(), clang::Preprocessor::macro_end(), MacroIDCompare(), PrintMacroDefinition(), and Tok.
Referenced by clang::DoPrintPreprocessedInput().
MacroIDCompare()
static int MacroIDCompare (const id_macro_pair * LHS, const id_macro_pair * RHS) static
Definition at line 821 of file PrintPreprocessedOutput.cpp.
Referenced by DoPrintMacros().
outputPrintable()
static void outputPrintable (raw_ostream & OS, StringRef Str) static
Definition at line 433 of file PrintPreprocessedOutput.cpp.
References clang::isPrintable().
PrintMacroDefinition()
static void PrintMacroDefinition (const IdentifierInfo & II, const MacroInfo & MI, Preprocessor & PP, raw_ostream & OS) static
PrintMacroDefinition - Print a macro definition in a form that will be properly accepted back as a definition.
Definition at line 34 of file PrintPreprocessedOutput.cpp.
References clang::IdentifierInfo::getName(), clang::Preprocessor::getSpelling(), clang::MacroInfo::isFunctionLike(), clang::MacroInfo::isGNUVarargs(), clang::MacroInfo::param_begin(), clang::MacroInfo::param_empty(), clang::MacroInfo::param_end(), clang::MacroInfo::tokens(), clang::MacroInfo::tokens_begin(), and clang::MacroInfo::tokens_empty().
Referenced by DoPrintMacros().
PrintPreprocessedTokens()
static void PrintPreprocessedTokens (Preprocessor & PP, Token & Tok, PrintPPOutputPPCallbacks * Callbacks, raw_ostream & OS) static
Definition at line 712 of file PrintPreprocessedOutput.cpp.
References clang::Token::getAnnotationValue(), clang::Preprocessor::getCommentRetentionState(), clang::Module::getFullModuleName(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), clang::Preprocessor::getLangOpts(), clang::Token::getLength(), clang::Token::getLiteralData(), clang::Token::getLocation(), clang::SourceLocation::getLocWithOffset(), clang::Preprocessor::getSpelling(), clang::Token::hasLeadingSpace(), clang::Token::is(), clang::Token::isAnnotation(), clang::Token::isAtStartOfLine(), clang::Token::isLiteral(), clang::Preprocessor::Lex(), clang::Token::needsCleaning(), clang::Token::startToken(), and Tok.
Referenced by clang::DoPrintPreprocessedInput().