clang: lib/AST/SelectorLocationsKind.cpp File Reference
SelectorLocationsKind.cpp File Reference
#include "clang/AST/SelectorLocationsKind.h"
#include "clang/AST/Expr.h"
Functions
static SourceLocation getStandardSelLoc (unsigned Index, Selector Sel, bool WithArgSpace, SourceLocation ArgLoc, SourceLocation EndLoc)
Function Documentation
getStandardSelLoc()
static SourceLocation getStandardSelLoc (unsigned Index, Selector Sel, bool WithArgSpace, SourceLocation ArgLoc, SourceLocation EndLoc) static
Definition at line 19 of file SelectorLocationsKind.cpp.
References clang::Selector::getIdentifierInfoForSlot(), clang::IdentifierInfo::getLength(), clang::SourceLocation::getLocWithOffset(), clang::Selector::getNumArgs(), and clang::SourceLocation::isInvalid().
Referenced by clang::getStandardSelectorLoc(), and clang::getStandardSelectorLoc().