clang: lib/Sema/SemaCoroutine.cpp File Reference
SemaCoroutine.cpp File Reference
#include "CoroutineStmtBuilder.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/Decl.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Basic/Builtins.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/SmallSet.h"
Classes
struct ReadySuspendResumeResult
Functions
static LookupResult lookupMember (Sema &S, const char *Name, CXXRecordDecl *RD, SourceLocation Loc, bool &Res)
static bool lookupMember (Sema &S, const char *Name, CXXRecordDecl *RD, SourceLocation Loc)
static QualType lookupPromiseType (Sema &S, const FunctionDecl *FD, SourceLocation KwLoc)
Look up the std::coroutine_traits<...>::promise_type for the given function type.
static QualType lookupCoroutineHandleType (Sema &S, QualType PromiseType, SourceLocation Loc)
Look up the std::experimental::coroutine_handle<PromiseType>.
static bool isValidCoroutineContext (Sema &S, SourceLocation Loc, StringRef Keyword)
static ExprResult buildOperatorCoawaitLookupExpr (Sema &SemaRef, Scope *S, SourceLocation Loc)
static ExprResult buildOperatorCoawaitCall (Sema &SemaRef, SourceLocation Loc, Expr *E, UnresolvedLookupExpr *Lookup)
Build a call to 'operator co_await' if there is a suitable operator for the given expression.
static ExprResult buildOperatorCoawaitCall (Sema &SemaRef, Scope *S, SourceLocation Loc, Expr *E)
static Expr * buildBuiltinCall (Sema &S, SourceLocation Loc, Builtin::ID Id, MultiExprArg CallArgs)
static ExprResult buildCoroutineHandle (Sema &S, QualType PromiseType, SourceLocation Loc)
static ExprResult buildMemberCall (Sema &S, Expr *Base, SourceLocation Loc, StringRef Name, MultiExprArg Args)
static Expr * maybeTailCall (Sema &S, QualType RetType, Expr *E, SourceLocation Loc)
static ReadySuspendResumeResult buildCoawaitCalls (Sema &S, VarDecl *CoroPromise, SourceLocation Loc, Expr *E)
Build calls to await_ready, await_suspend, and await_resume for a co_await expression.
static ExprResult buildPromiseCall (Sema &S, VarDecl *Promise, SourceLocation Loc, StringRef Name, MultiExprArg Args)
static FunctionScopeInfo * checkCoroutineContext (Sema &S, SourceLocation Loc, StringRef Keyword, bool IsImplicit=false)
Check that this is a context in which a coroutine suspension can appear.
static void checkNoThrow (Sema &S, const Stmt *E, llvm::SmallPtrSetImpl< const Decl * > &ThrowingDecls)
Recursively check E and all its children to see if any call target (including constructor call) is declared noexcept.
static bool isWithinCatchScope (Scope *S)
static void checkSuspensionContext (Sema &S, SourceLocation Loc, StringRef Keyword)
static Expr * buildStdNoThrowDeclRef (Sema &S, SourceLocation Loc)
Look up the std::nothrow object.
static FunctionDecl * findDeleteForPromise (Sema &S, SourceLocation Loc, QualType PromiseType)
static bool diagReturnOnAllocFailure (Sema &S, Expr *E, CXXRecordDecl *PromiseRecordDecl, FunctionScopeInfo &Fn)
static void noteMemberDeclaredHere (Sema &S, Expr *E, FunctionScopeInfo &Fn)
static Expr * castForMoving (Sema &S, Expr *E, QualType T=QualType())
static VarDecl * buildVarDecl (Sema &S, SourceLocation Loc, QualType Type, IdentifierInfo *II)
Build a variable declaration for move parameter.
Function Documentation
buildBuiltinCall()
static Expr * buildBuiltinCall (Sema & S, SourceLocation Loc, Builtin::ID Id, MultiExprArg CallArgs) static
Definition at line 294 of file SemaCoroutine.cpp.
References clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclRefExpr(), clang::ASTContext::BuiltinInfo, clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::IdentifierTable::get(), clang::LookupResult::getAsSingle(), clang::Builtin::Context::getName(), Id, clang::ASTContext::Idents, clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::Sema::LookupName(), clang::Sema::LookupOrdinaryName, clang::Sema::TUScope, and clang::VK_LValue.
Referenced by buildCoroutineHandle(), and maybeTailCall().
buildCoawaitCalls()
static ReadySuspendResumeResult buildCoawaitCalls (Sema & S, VarDecl * CoroPromise, SourceLocation Loc, Expr * E) static
Build calls to await_ready, await_suspend, and await_resume for a co_await expression.
The generated AST tries to clean up temporary objects as early as possible so that they don't live across suspension points if possible. Having temporary objects living across suspension points unnecessarily can lead to large frame size, and also lead to memory corruptions if the coroutine frame is destroyed after coming back from suspension. This is done by wrapping both the await_ready call and the await_suspend call with ExprWithCleanups. In the end of this function, we also need to explicitly set cleanup state so that the CoawaitExpr is also wrapped with an ExprWithCleanups to clean up the awaiter associated with the co_await expression.
Definition at line 423 of file SemaCoroutine.cpp.
References buildCoroutineHandle(), buildMemberCall(), clang::Sema::Cleanup, clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::DeclaratorDecl::getBeginLoc(), clang::CallExpr::getCalleeDecl(), clang::CallExpr::getCallReturnType(), clang::CallExpr::getDirectCallee(), clang::Decl::getLocation(), clang::Expr::getObjectKind(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::Type::isBooleanType(), clang::Type::isDependentType(), ReadySuspendResumeResult::IsInvalid, clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isReferenceType(), clang::Type::isVoidType(), clang::Sema::MaybeCreateExprWithCleanups(), maybeTailCall(), clang::Sema::PerformContextuallyConvertToBool(), clang::Result, ReadySuspendResumeResult::Results, clang::CleanupInfo::setExprNeedsCleanups(), and clang::VK_LValue.
Referenced by clang::Sema::BuildCoyieldExpr(), and clang::Sema::BuildResolvedCoawaitExpr().
buildCoroutineHandle()
static ExprResult buildCoroutineHandle (Sema & S, QualType PromiseType, SourceLocation Loc) static
Definition at line 314 of file SemaCoroutine.cpp.
References buildBuiltinCall(), clang::Sema::BuildCallExpr(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::computeDeclContext(), clang::Sema::Diag(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::QualType::isNull(), lookupCoroutineHandleType(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), and clang::Sema::PP.
Referenced by buildCoawaitCalls().
buildMemberCall()
static ExprResult buildMemberCall (Sema & S, Expr * Base, SourceLocation Loc, StringRef Name, MultiExprArg Args) static
Definition at line 348 of file SemaCoroutine.cpp.
References clang::Sema::BuildCallExpr(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::clearDelayedTypo(), clang::Sema::Diag(), clang::ExprError(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::DeclarationNameInfo::getName(), clang::Sema::PP, and clang::Result.
Referenced by buildCoawaitCalls(), buildPromiseCall(), and maybeTailCall().
buildOperatorCoawaitCall() [1/2]
static ExprResult buildOperatorCoawaitCall (Sema & SemaRef, Scope * S, SourceLocation Loc, Expr * E) static
Definition at line 285 of file SemaCoroutine.cpp.
References buildOperatorCoawaitCall(), buildOperatorCoawaitLookupExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), and clang::ActionResult< PtrTy, CompressInvalid >::isInvalid().
buildOperatorCoawaitCall() [2/2]
static ExprResult buildOperatorCoawaitCall (Sema & SemaRef, SourceLocation Loc, Expr * E, UnresolvedLookupExpr * Lookup) static
Build a call to 'operator co_await' if there is a suitable operator for the given expression.
Definition at line 277 of file SemaCoroutine.cpp.
References clang::UnresolvedSetImpl::append(), clang::Sema::CreateOverloadedUnaryOp(), clang::OverloadExpr::decls_begin(), and clang::OverloadExpr::decls_end().
Referenced by clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCoyieldExpr(), buildOperatorCoawaitCall(), and clang::Sema::BuildUnresolvedCoawaitExpr().
buildOperatorCoawaitLookupExpr()
static ExprResult buildOperatorCoawaitLookupExpr (Sema & SemaRef, Scope * S, SourceLocation Loc) static
Definition at line 254 of file SemaCoroutine.cpp.
References clang::LookupResult::asUnresolvedSet(), clang::Sema::Context, clang::UnresolvedLookupExpr::Create(), clang::ASTContext::DeclarationNames, clang::DeclarationNameTable::getCXXOperatorName(), clang::LookupResult::isAmbiguous(), IsOverloaded(), clang::Sema::LookupName(), and clang::Sema::LookupOperatorName.
Referenced by clang::Sema::ActOnCoawaitExpr(), and buildOperatorCoawaitCall().
buildPromiseCall()
static ExprResult buildPromiseCall (Sema & S, VarDecl * Promise, SourceLocation Loc, StringRef Name, MultiExprArg Args) static
Definition at line 515 of file SemaCoroutine.cpp.
References clang::Sema::BuildDeclRefExpr(), buildMemberCall(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::VK_LValue.
Referenced by clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::ActOnCoyieldExpr(), clang::Sema::BuildCoreturnStmt(), and clang::Sema::BuildUnresolvedCoawaitExpr().
buildStdNoThrowDeclRef()
static Expr * buildStdNoThrowDeclRef (Sema & S, SourceLocation Loc) static
Look up the std::nothrow object.
Definition at line 1031 of file SemaCoroutine.cpp.
References clang::Sema::BuildDeclRefExpr(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::Decl::getLocation(), clang::Sema::getStdNamespace(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::Sema::PP, clang::Result, Std, and clang::VK_LValue.
buildVarDecl()
static VarDecl * buildVarDecl (Sema & S, SourceLocation Loc, QualType Type, IdentifierInfo * II) static
Build a variable declaration for move parameter.
Definition at line 1644 of file SemaCoroutine.cpp.
References clang::Sema::Context, clang::VarDecl::Create(), clang::Sema::CurContext, clang::ASTContext::getTrivialTypeSourceInfo(), clang::SC_None, and clang::Decl::setImplicit().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCopyinClause(), clang::Sema::ActOnOpenMPCopyprivateClause(), clang::Sema::ActOnOpenMPDeclareReductionCombinerStart(), clang::Sema::ActOnOpenMPDeclareReductionInitializerStart(), clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnOpenMPLastprivateClause(), clang::Sema::ActOnOpenMPLinearClause(), clang::Sema::ActOnOpenMPPrivateClause(), clang::Sema::ActOnOpenMPUseDevicePtrClause(), clang::Sema::buildCoroutineParameterMoves(), checkOpenMPLoop(), and clang::Sema::EndOpenMPDSABlock().
castForMoving()
static Expr * castForMoving (Sema & S, Expr * E, QualType T = QualType()) static
Definition at line 1628 of file SemaCoroutine.cpp.
References clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildReferenceType(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), clang::ASTContext::getTrivialTypeSourceInfo(), and clang::Expr::getType().
Referenced by clang::Sema::buildCoroutineParameterMoves().
checkCoroutineContext()
static FunctionScopeInfo * checkCoroutineContext (Sema & S, SourceLocation Loc, StringRef Keyword, bool IsImplicit = false) static
Check that this is a context in which a coroutine suspension can appear.
Definition at line 628 of file SemaCoroutine.cpp.
References clang::Sema::buildCoroutineParameterMoves(), clang::Sema::buildCoroutinePromise(), clang::Sema::CurContext, clang::Sema::getCurFunction(), and isValidCoroutineContext().
Referenced by clang::Sema::ActOnCoroutineBodyStart(), clang::Sema::BuildCoreturnStmt(), clang::Sema::BuildCoyieldExpr(), clang::Sema::BuildResolvedCoawaitExpr(), and clang::Sema::BuildUnresolvedCoawaitExpr().
checkNoThrow()
static void checkNoThrow (Sema & S, const Stmt * E, llvm::SmallPtrSetImpl< const Decl * > & ThrowingDecls) static
Recursively check E and all its children to see if any call target (including constructor call) is declared noexcept.
Also any value returned from the call has a noexcept destructor.
Definition at line 658 of file SemaCoroutine.cpp.
References clang::Sema::canCalleeThrow(), clang::cast(), checkNoThrow(), clang::Stmt::children(), clang::Sema::CurContext, clang::Sema::Diag(), clang::QualType::DK_cxx_destructor, clang::Sema::getASTContext(), and clang::Stmt::getStmtClass().
Referenced by clang::Sema::checkFinalSuspendNoThrow(), and checkNoThrow().
checkSuspensionContext()
static void checkSuspensionContext (Sema & S, SourceLocation Loc, StringRef Keyword) static
Definition at line 809 of file SemaCoroutine.cpp.
References clang::Sema::Diag(), clang::Sema::getCurScope(), clang::Sema::isUnevaluatedContext(), and isWithinCatchScope().
Referenced by clang::Sema::ActOnCoawaitExpr(), and clang::Sema::ActOnCoyieldExpr().
diagReturnOnAllocFailure()
static bool diagReturnOnAllocFailure (Sema & S, Expr * E, CXXRecordDecl * PromiseRecordDecl, FunctionScopeInfo & Fn) static
Definition at line 1180 of file SemaCoroutine.cpp.
References clang::Sema::Diag(), clang::sema::FunctionScopeInfo::FirstCoroutineStmtLoc, clang::Expr::getExprLoc(), clang::sema::FunctionScopeInfo::getFirstCoroutineStmtKeyword(), and clang::Decl::getLocation().
findDeleteForPromise()
static FunctionDecl * findDeleteForPromise (Sema & S, SourceLocation Loc, QualType PromiseType) static
Definition at line 1062 of file SemaCoroutine.cpp.
References clang::Sema::Context, clang::ASTContext::DeclarationNames, clang::Sema::FindDeallocationFunction(), clang::Sema::FindUsualDeallocationFunction(), clang::Type::getAsCXXRecordDecl(), clang::DeclarationNameTable::getCXXOperatorName(), clang::Sema::isCompleteType(), and clang::Sema::MarkFunctionReferenced().
isValidCoroutineContext()
static bool isValidCoroutineContext (Sema & S, SourceLocation Loc, StringRef Keyword) static
Definition at line 188 of file SemaCoroutine.cpp.
References clang::Sema::CurContext, and clang::Sema::Diag().
Referenced by checkCoroutineContext().
isWithinCatchScope()
static bool isWithinCatchScope (Scope * S) static
Definition at line 781 of file SemaCoroutine.cpp.
References clang::Scope::CatchScope, and clang::Scope::FnScope.
Referenced by checkSuspensionContext().
lookupCoroutineHandleType()
static QualType lookupCoroutineHandleType (Sema & S, QualType PromiseType, SourceLocation Loc) static
Look up the std::experimental::coroutine_handle<PromiseType>.
Definition at line 145 of file SemaCoroutine.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::Sema::CheckTemplateIdType(), clang::Sema::Context, clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Preprocessor::getIdentifierTable(), clang::Decl::getLocation(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::QualType::isNull(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::Sema::lookupStdExperimentalNamespace(), clang::Sema::PP, clang::Sema::RequireCompleteType(), and clang::Result.
Referenced by buildCoroutineHandle().
lookupMember() [1/2]
static bool lookupMember (Sema & S, const char * Name, CXXRecordDecl * RD, SourceLocation Loc) static
Definition at line 43 of file SemaCoroutine.cpp.
References lookupMember().
lookupMember() [2/2]
static LookupResult lookupMember (Sema & S, const char * Name, CXXRecordDecl * RD, SourceLocation Loc, bool & Res) static
Definition at line 32 of file SemaCoroutine.cpp.
References clang::Preprocessor::getIdentifierInfo(), clang::Sema::LookupMemberName, clang::Sema::LookupQualifiedName(), clang::Sema::PP, and clang::LookupResult::suppressDiagnostics().
Referenced by clang::Sema::BuildUnresolvedCoawaitExpr(), and lookupMember().
lookupPromiseType()
static QualType lookupPromiseType (Sema & S, const FunctionDecl * FD, SourceLocation KwLoc) static
Look up the std::coroutine_traits<...>::promise_type for the given function type.
Definition at line 52 of file SemaCoroutine.cpp.
References clang::TemplateArgumentListInfo::addArgument(), clang::Type::castAs(), clang::Sema::CheckTemplateIdType(), clang::Sema::Context, clang::NestedNameSpecifier::Create(), clang::Sema::Diag(), clang::ETK_None, clang::IdentifierTable::get(), clang::Type::getAsCXXRecordDecl(), clang::LookupResult::getAsSingle(), clang::ASTContext::getElaboratedType(), clang::Preprocessor::getIdentifierTable(), clang::Decl::getLocation(), clang::ASTContext::getLValueReferenceType(), clang::FunctionProtoType::getParamTypes(), clang::FunctionProtoType::getRefQualifier(), clang::FunctionType::getReturnType(), clang::ASTContext::getRValueReferenceType(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ValueDecl::getType(), clang::ASTContext::getTypeDeclType(), clang::QualType::getTypePtr(), clang::QualType::isNull(), clang::Sema::lookupCoroutineTraits(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupQualifiedName(), clang::Sema::lookupStdExperimentalNamespace(), clang::Sema::PP, clang::Sema::RequireCompleteType(), and clang::RQ_RValue.
Referenced by clang::Sema::buildCoroutinePromise().
maybeTailCall()
static Expr * maybeTailCall (Sema & S, QualType RetType, Expr * E, SourceLocation Loc) static
Definition at line 377 of file SemaCoroutine.cpp.
References buildBuiltinCall(), buildMemberCall(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Expr::getType(), clang::QualType::getTypePtr(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isReferenceType(), clang::Type::isVoidPointerType(), and clang::Sema::MaybeCreateExprWithCleanups().
Referenced by buildCoawaitCalls().
noteMemberDeclaredHere()
static void noteMemberDeclaredHere (Sema & S, Expr * E, FunctionScopeInfo & Fn) static
Definition at line 1535 of file SemaCoroutine.cpp.
References clang::Sema::Diag(), clang::sema::FunctionScopeInfo::FirstCoroutineStmtLoc, and clang::sema::FunctionScopeInfo::getFirstCoroutineStmtKeyword().