clang: lib/Sema/SemaExpr.cpp File Reference
SemaExpr.cpp File Reference
#include "TreeTransform.h"
#include "UsedDeclVisitor.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/AnalysisBasedWarnings.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Designator.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaFixItUtils.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/Template.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/SaveAndRestore.h"
#include "clang/AST/DeclNodes.inc"
#include "clang/AST/TypeNodes.inc"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/AST/BuiltinTypes.def"
Macros
#define ABSTRACT_DECL(kind)
#define VALUE(type, base)
#define DECL(type, base)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define PLACEHOLDER_TYPE(ID, SINGLETON_ID)
#define BUILTIN_TYPE(ID, SINGLETON_ID)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define BUILTIN_TYPE(Id, SingletonId)
#define PLACEHOLDER_TYPE(Id, SingletonId)
Typedefs
typedef ExprResult PerformCastFn(Sema &S, Expr *operand, QualType toType)
Enumerations
enum NonConstCaptureKind { NCCK_None , NCCK_Block , NCCK_Lambda }
Is the given expression (which must be 'const') a reference to a variable which was originally non-const, but which has become 'const' due to being captured within a block?
enum {
ConstFunction , ConstVariable , ConstMember , ConstMethod ,
NestedConstMember , ConstUnknown
}
enum OriginalExprKind { OEK_Variable , OEK_Member , OEK_LValue }
Functions
static void DiagnoseUnusedOfDecl (Sema &S, NamedDecl *D, SourceLocation Loc)
static bool hasAnyExplicitStorageClass (const FunctionDecl *D)
Determine whether a FunctionDecl was ever declared with an explicit storage class.
static void diagnoseUseOfInternalDeclInInlineFunction (Sema &S, const NamedDecl *D, SourceLocation Loc)
Check whether we're in an extern inline function and referring to a variable or function with internal linkage (C11 6.7.4p3).
static void CheckForNullPointerDereference (Sema &S, Expr *E)
static void DiagnoseDirectIsaAccess (Sema &S, const ObjCIvarRefExpr *OIRE, SourceLocation AssignLoc, const Expr *RHS)
static bool handleIntegerToComplexFloatConversion (Sema &S, ExprResult &IntExpr, ExprResult &ComplexExpr, QualType IntTy, QualType ComplexTy, bool SkipCast)
Converts an integer to complex float type.
static QualType handleComplexFloatConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle arithmetic conversion with complex types.
static QualType handleIntToFloatConversion (Sema &S, ExprResult &FloatExpr, ExprResult &IntExpr, QualType FloatTy, QualType IntTy, bool ConvertFloat, bool ConvertInt)
Handle arithmetic conversion from integer to float.
static QualType handleFloatConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle arithmethic conversion with floating point types.
static bool unsupportedTypeConversion (const Sema &S, QualType LHSType, QualType RHSType)
Diagnose attempts to convert between __float128 and long double if there is no support for such conversion.
template<PerformCastFn doLHSCast, PerformCastFn doRHSCast>
static QualType handleIntegerConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle integer arithmetic conversions.
static QualType handleComplexIntConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle conversions with GCC complex int extension.
static unsigned GetFixedPointRank (QualType Ty)
Return the rank of a given fixed point or integer type.
static QualType handleFixedPointConversion (Sema &S, QualType LHSTy, QualType RHSTy)
handleFixedPointConversion - Fixed point operations between fixed point types and integers or other fixed point types do not fall under usual arithmetic conversion since these conversions could result in loss of precsision (N1169 4.1.4).
static void checkEnumArithmeticConversions (Sema &S, Expr *LHS, Expr *RHS, SourceLocation Loc, Sema::ArithConvKind ACK)
Check that the usual arithmetic conversions can be performed on this pair of expressions that might be of enumeration type.
static SourceLocation getUDSuffixLoc (Sema &S, SourceLocation TokLoc, unsigned Offset)
getUDSuffixLoc - Create a SourceLocation for a ud-suffix, given the location of the token and the offset of the ud-suffix within it.
static ExprResult BuildCookedLiteralOperatorCall (Sema &S, Scope *Scope, IdentifierInfo *UDSuffix, SourceLocation UDSuffixLoc, ArrayRef< Expr * > Args, SourceLocation LitEndLoc)
BuildCookedLiteralOperatorCall - A user-defined literal was found.
static bool isCapturingReferenceToHostVarInCUDADeviceLambda (const Sema &S, VarDecl *VD)
static void emitEmptyLookupTypoDiagnostic (const TypoCorrection &TC, Sema &SemaRef, const CXXScopeSpec &SS, DeclarationName Typo, SourceLocation TypoLoc, ArrayRef< Expr * > Args, unsigned DiagnosticID, unsigned DiagnosticSuggestID)
static Expr * recoverFromMSUnqualifiedLookup (Sema &S, ASTContext &Context, DeclarationNameInfo &NameInfo, SourceLocation TemplateKWLoc, const TemplateArgumentListInfo *TemplateArgs)
In Microsoft mode, if we are inside a template class whose parent class has dependent base classes, and we can't resolve an unqualified identifier, then assume the identifier is a member of a dependent base class.
static bool CheckDeclInExpr (Sema &S, SourceLocation Loc, NamedDecl *D)
Diagnoses obvious problems with the use of the given declaration as an expression.
static bool ShouldLookupResultBeMultiVersionOverload (const LookupResult &R)
static void diagnoseUncapturableValueReference (Sema &S, SourceLocation loc, ValueDecl *var, DeclContext *DC)
static void ConvertUTF8ToWideString (unsigned CharByteWidth, StringRef Source, SmallString< 32 > &Target)
static Expr * BuildFloatingLiteral (Sema &S, NumericLiteralParser &Literal, QualType Ty, SourceLocation Loc)
static bool CheckVecStepTraitOperandType (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange)
static bool CheckExtensionTraitOperandType (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind)
static bool CheckObjCTraitOperandConstraints (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind)
static void warnOnSizeofOnArrayDecay (Sema &S, SourceLocation Loc, QualType T, Expr *E)
Check whether E is a pointer from a decayed array type (the decayed pointer type is equal to T) and emit a warning if it is.
static bool CheckAlignOfExpr (Sema &S, Expr *E, UnaryExprOrTypeTrait ExprKind)
static void captureVariablyModifiedType (ASTContext &Context, QualType T, CapturingScopeInfo *CSI)
static QualType CheckRealImagOperand (Sema &S, ExprResult &V, SourceLocation Loc, bool IsReal)
static bool checkArithmeticOnObjCPointer (Sema &S, SourceLocation opLoc, Expr *op)
Diagnose if arithmetic on the given ObjC pointer is illegal.
static bool isMSPropertySubscriptExpr (Sema &S, Expr *Base)
static TypoCorrection TryTypoCorrectionForCall (Sema &S, Expr *Fn, FunctionDecl *FDecl, ArrayRef< Expr * > Args)
static void DiagnoseCalleeStaticArrayParam (Sema &S, ParmVarDecl *PVD)
static ExprResult rebuildUnknownAnyFunction (Sema &S, Expr *fn)
Given a function expression of unknown-any type, try to rebuild it to have a function type.
static bool isPlaceholderToRemoveAsArg (QualType type)
Is the given type a placeholder that we need to lower out immediately during argument processing?
static bool checkArgsForPlaceholders (Sema &S, MultiExprArg args)
Check an argument list for placeholders that we won't try to handle later.
static FunctionDecl * rewriteBuiltinFunctionDecl (Sema *Sema, ASTContext &Context, FunctionDecl *FDecl, MultiExprArg ArgExprs)
If a builtin function has a pointer argument with no explicit address space, then it should be able to accept a pointer to any address space as input.
static void checkDirectCallValidity (Sema &S, const Expr *Fn, FunctionDecl *Callee, MultiExprArg ArgExprs)
static bool enclosingClassIsRelatedToClassInWhichMembersWereFound (const UnresolvedMemberExpr *const UME, Sema &S)
static void tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs (Sema &S, const UnresolvedMemberExpr *const UME, SourceLocation CallLoc)
static bool breakDownVectorType (QualType type, uint64_t &len, QualType &eltType)
static bool checkCondition (Sema &S, Expr *Cond, SourceLocation QuestionLoc)
Return false if the condition expression is valid, true otherwise.
static QualType checkConditionalVoidType (Sema &S, ExprResult &LHS, ExprResult &RHS)
Handle when one or both operands are void type.
static bool checkConditionalNullPointer (Sema &S, ExprResult &NullExpr, QualType PointerTy)
Return false if the NullExpr can be promoted to PointerTy, true otherwise.
static QualType checkConditionalPointerCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Checks compatibility between two pointers and return the resulting type.
static QualType checkConditionalBlockPointerCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Return the resulting type when the operands are both block pointers.
static QualType checkConditionalObjectPointersCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Return the resulting type when the operands are both pointers.
static bool checkPointerIntegerMismatch (Sema &S, ExprResult &Int, Expr *PointerExpr, SourceLocation Loc, bool IsIntFirstExpr)
Return false if the first expression is not an integer and the second expression is not a pointer, true otherwise.
static QualType OpenCLArithmeticConversions (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation QuestionLoc)
Simple conversion between integer and floating point types.
static QualType OpenCLConvertScalarsToVectors (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType CondTy, SourceLocation QuestionLoc)
Convert scalar operands to a vector that matches the condition in length.
static bool checkOpenCLConditionVector (Sema &S, Expr *Cond, SourceLocation QuestionLoc)
Return false if this is a valid OpenCL condition vector.
static bool checkVectorResult (Sema &S, QualType CondTy, QualType VecResTy, SourceLocation QuestionLoc)
Return false if the vector condition type and the vector result type are compatible.
static QualType OpenCLCheckVectorConditional (Sema &S, ExprResult &Cond, ExprResult &LHS, ExprResult &RHS, SourceLocation QuestionLoc)
Return the resulting type for the conditional operator in OpenCL (aka "ternary selection operator", OpenCL v1.1 s6.3.i) when the condition is a vector type.
static bool checkBlockType (Sema &S, const Expr *E)
Return true if the Expr is block type.
static void SuggestParentheses (Sema &Self, SourceLocation Loc, const PartialDiagnostic &Note, SourceRange ParenRange)
SuggestParentheses - Emit a note with a fixit hint that wraps ParenRange in parentheses.
static bool IsArithmeticOp (BinaryOperatorKind Opc)
static bool IsArithmeticBinaryExpr (Expr *E, BinaryOperatorKind *Opcode, Expr **RHSExprs)
IsArithmeticBinaryExpr - Returns true if E is an arithmetic binary expression, either using a built-in or overloaded operator, and sets *OpCode to the opcode and *RHSExprs to the right-hand side expression.
static bool ExprLooksBoolean (Expr *E)
ExprLooksBoolean - Returns true if E looks boolean, i.e.
static void DiagnoseConditionalPrecedence (Sema &Self, SourceLocation OpLoc, Expr *Condition, Expr *LHSExpr, Expr *RHSExpr)
DiagnoseConditionalPrecedence - Emit a warning when a conditional operator and binary operator are mixed in a way that suggests the programmer assumed the conditional operator has higher precedence, for example: "int x = a + someBinaryCondition ? 1 : 2".
static QualType computeConditionalNullability (QualType ResTy, bool IsBin, QualType LHSTy, QualType RHSTy, ASTContext &Ctx)
Compute the nullability of a conditional expression.
static bool IsInvalidCmseNSCallConversion (Sema &S, QualType FromType, QualType ToType)
static Sema::AssignConvertType checkPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType)
static Sema::AssignConvertType checkBlockPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType)
checkBlockPointerTypesForAssignment - This routine determines whether two block pointer types are compatible or whether a block and normal pointer are compatible.
static Sema::AssignConvertType checkObjCPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType)
checkObjCPointerTypesForAssignment - Compares two objective-c pointer types for assignment compatibility.
static bool isVector (QualType QT, QualType ElementType)
This helper function returns true if QT is a vector type that has element type ElementType.
static void ConstructTransparentUnion (Sema &S, ASTContext &C, ExprResult &EResult, QualType UnionType, FieldDecl *Field)
Constructs a transparent union from an expression that is used to initialize the transparent union.
static bool tryVectorConvertAndSplat (Sema &S, ExprResult *scalar, QualType scalarTy, QualType vectorEltTy, QualType vectorTy, unsigned &DiagID)
Try to convert a value of non-vector type to a vector type by converting the type to the element type of the vector and then performing a splat.
static ExprResult convertVector (Expr *E, QualType ElementType, Sema &S)
Convert vector E to a vector with the same number of elements but different element type.
static bool canConvertIntToOtherIntTy (Sema &S, ExprResult *Int, QualType OtherIntTy)
Test if a (constant) integer Int can be casted to another integer type IntTy without losing precision.
static bool canConvertIntTyToFloatTy (Sema &S, ExprResult *Int, QualType FloatTy)
Test if a (constant) integer Int can be casted to floating point type FloatTy without losing precision.
static bool tryGCCVectorConvertAndSplat (Sema &S, ExprResult *Scalar, ExprResult *Vector)
Attempt to convert and splat Scalar into a vector whose types matches Vector following GCC conversion rules.
static void checkArithmeticNull (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsCompare)
static void DiagnoseDivisionSizeofPointerOrArray (Sema &S, Expr *LHS, Expr *RHS, SourceLocation Loc)
static void DiagnoseBadDivideOrRemainderValues (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsDiv)
static void diagnoseArithmeticOnTwoVoidPointers (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Diagnose invalid arithmetic on two void pointers.
static void diagnoseArithmeticOnVoidPointer (Sema &S, SourceLocation Loc, Expr *Pointer)
Diagnose invalid arithmetic on a void pointer.
static void diagnoseArithmeticOnNullPointer (Sema &S, SourceLocation Loc, Expr *Pointer, bool IsGNUIdiom)
Diagnose invalid arithmetic on a null pointer.
static void diagnoseArithmeticOnTwoFunctionPointers (Sema &S, SourceLocation Loc, Expr *LHS, Expr *RHS)
Diagnose invalid arithmetic on two function pointers.
static void diagnoseArithmeticOnFunctionPointer (Sema &S, SourceLocation Loc, Expr *Pointer)
Diagnose invalid arithmetic on a function pointer.
static bool checkArithmeticIncompletePointerType (Sema &S, SourceLocation Loc, Expr *Operand)
Emit error if Operand is incomplete pointer type.
static bool checkArithmeticOpPointerOperand (Sema &S, SourceLocation Loc, Expr *Operand)
Check the validity of an arithmetic pointer operand.
static bool checkArithmeticBinOpPointerOperands (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Check the validity of a binary arithmetic operation w.r.t.
static void diagnoseStringPlusInt (Sema &Self, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
diagnoseStringPlusInt - Emit a warning when adding an integer to a string literal.
static void diagnoseStringPlusChar (Sema &Self, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Emit a warning when adding a char literal to a string.
static void diagnosePointerIncompatibility (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Emit error when two pointers are incompatible.
static bool isScopedEnumerationType (QualType T)
static void DiagnoseBadShiftValues (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc, QualType LHSType)
static QualType checkVectorShift (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsCompAssign)
Return the resulting type when a vector is shifted by a scalar or vector shift amount.
static void diagnoseDistinctPointerComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, bool IsError)
Diagnose bad pointer comparisons.
static bool convertPointersToCompositeType (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS)
Returns false if the pointers are converted to a composite type, true otherwise.
static void diagnoseFunctionPointerToVoidComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, bool IsError)
static bool isObjCObjectLiteral (ExprResult &E)
static bool hasIsEqualMethod (Sema &S, const Expr *LHS, const Expr *RHS)
static void diagnoseObjCLiteralComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, BinaryOperator::Opcode Opc)
static void diagnoseLogicalNotOnLHSofCheck (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc)
Warns on !x < y, !x & y where !(x < y), !(x & y) was probably intended.
static bool checkForArray (const Expr *E)
static void diagnoseTautologicalComparison (Sema &S, SourceLocation Loc, Expr *LHS, Expr *RHS, BinaryOperatorKind Opc)
Diagnose some forms of syntactically-obvious tautological comparison.
static ImplicitConversionKind castKindToImplicitConversionKind (CastKind CK)
static bool checkThreeWayNarrowingConversion (Sema &S, QualType ToType, Expr *E, QualType FromType, SourceLocation Loc)
static QualType checkArithmeticOrEnumeralThreeWayCompare (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
static QualType checkArithmeticOrEnumeralCompare (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc)
static void diagnoseXorMisusedAsPow (Sema &S, const ExprResult &XorLHS, const ExprResult &XorRHS, const SourceLocation Loc)
static bool IsReadonlyMessage (Expr *E, Sema &S)
static NonConstCaptureKind isReferenceToNonConstCapture (Sema &S, Expr *E)
static bool IsTypeModifiable (QualType Ty, bool IsDereference)
static void DiagnoseConstAssignment (Sema &S, const Expr *E, SourceLocation Loc)
Emit the "read-only variable not assignable" error and print notes to give more information about why the variable is not assignable, such as pointing to the declaration of a const variable, showing that a method is const, or that the function is returning a const reference.
static void DiagnoseRecursiveConstFields (Sema &S, const ValueDecl *VD, const RecordType *Ty, SourceLocation Loc, SourceRange Range, OriginalExprKind OEK, bool &DiagnosticEmitted)
static void DiagnoseRecursiveConstFields (Sema &S, const Expr *E, SourceLocation Loc)
Emit an error for the case where a record we are trying to assign to has a const-qualified field somewhere in its hierarchy.
static bool CheckForModifiableLvalue (Expr *E, SourceLocation Loc, Sema &S)
CheckForModifiableLvalue - Verify that E is a modifiable lvalue.
static void CheckIdentityFieldAssignment (Expr *LHSExpr, Expr *RHSExpr, SourceLocation Loc, Sema &Sema)
static bool IgnoreCommaOperand (const Expr *E)
static QualType CheckCommaOperands (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
static QualType CheckIncrementDecrementOperand (Sema &S, Expr *Op, ExprValueKind &VK, ExprObjectKind &OK, SourceLocation OpLoc, bool IsInc, bool IsPrefix)
CheckIncrementDecrementOperand - unlike most "Check" methods, this routine doesn't need to call UsualUnaryConversions or UsualArithmeticConversions.
static ValueDecl * getPrimaryDecl (Expr *E)
getPrimaryDecl - Helper function for CheckAddressOfOperand().
static void diagnoseAddressOfInvalidType (Sema &S, SourceLocation Loc, Expr *E, unsigned Type)
Diagnose invalid operand for address of operations.
static void RecordModifiableNonNullParam (Sema &S, const Expr *Exp)
static QualType CheckIndirectionOperand (Sema &S, Expr *Op, ExprValueKind &VK, SourceLocation OpLoc)
CheckIndirectionOperand - Type check unary indirection (prefix '*').
static UnaryOperatorKind ConvertTokenKindToUnaryOpcode (tok::TokenKind Kind)
static void DiagnoseSelfAssignment (Sema &S, Expr *LHSExpr, Expr *RHSExpr, SourceLocation OpLoc, bool IsBuiltin)
DiagnoseSelfAssignment - Emits a warning if a value is assigned to itself.
static void checkObjCPointerIntrospection (Sema &S, ExprResult &L, ExprResult &R, SourceLocation OpLoc)
Check if a bitwise-& is performed on an Objective-C pointer.
static NamedDecl * getDeclFromExpr (Expr *E)
static ExprResult convertHalfVecBinOp (Sema &S, ExprResult LHS, ExprResult RHS, BinaryOperatorKind Opc, QualType ResultTy, ExprValueKind VK, ExprObjectKind OK, bool IsCompAssign, SourceLocation OpLoc, FPOptionsOverride FPFeatures)
static std::pair< ExprResult, ExprResult > CorrectDelayedTyposInBinOp (Sema &S, BinaryOperatorKind Opc, Expr *LHSExpr, Expr *RHSExpr)
static bool needsConversionOfHalfVec (bool OpRequiresConversion, ASTContext &Ctx, Expr *E0, Expr *E1=nullptr)
Returns true if conversion between vectors of halfs and vectors of floats is needed.
static void DiagnoseBitwisePrecedence (Sema &Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
DiagnoseBitwisePrecedence - Emit a warning when bitwise and comparison operators are mixed in a way that suggests that the programmer forgot that comparison operators have higher precedence.
static void EmitDiagnosticForLogicalAndInLogicalOr (Sema &Self, SourceLocation OpLoc, BinaryOperator *Bop)
It accepts a '&&' expr that is inside a '||' one.
static bool EvaluatesAsTrue (Sema &S, Expr *E)
Returns true if the given expression can be evaluated as a constant 'true'.
static bool EvaluatesAsFalse (Sema &S, Expr *E)
Returns true if the given expression can be evaluated as a constant 'false'.
static void DiagnoseLogicalAndInLogicalOrLHS (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Look for '&&' in the left hand of a '||' expr.
static void DiagnoseLogicalAndInLogicalOrRHS (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Look for '&&' in the right hand of a '||' expr.
static void DiagnoseBitwiseOpInBitwiseOp (Sema &S, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *SubExpr)
Look for bitwise op in the left or right hand of a bitwise op with lower precedence and emit a diagnostic together with a fixit hint that wraps the '&' expression in parentheses.
static void DiagnoseAdditionInShift (Sema &S, SourceLocation OpLoc, Expr *SubExpr, StringRef Shift)
static void DiagnoseShiftCompare (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
static void DiagnoseBinOpPrecedence (Sema &Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
DiagnoseBinOpPrecedence - Emit warnings for expressions with tricky precedence.
static ExprResult BuildOverloadedBinOp (Sema &S, Scope *Sc, SourceLocation OpLoc, BinaryOperatorKind Opc, Expr *LHS, Expr *RHS)
Build an overloaded binary operator expression in the given scope.
static bool isOverflowingIntegerType (ASTContext &Ctx, QualType T)
static bool maybeDiagnoseAssignmentToFunction (Sema &S, QualType DstType, const Expr *SrcExpr)
static void EvaluateAndDiagnoseImmediateInvocation (Sema &SemaRef, Sema::ImmediateInvocationCandidate Candidate)
static void RemoveNestedImmediateInvocation (Sema &SemaRef, Sema::ExpressionEvaluationContextRecord &Rec, SmallVector< Sema::ImmediateInvocationCandidate, 4 >::reverse_iterator It)
static void HandleImmediateInvocations (Sema &SemaRef, Sema::ExpressionEvaluationContextRecord &Rec)
static bool isPotentiallyConstantEvaluatedContext (Sema &SemaRef)
Are we in a context that is potentially constant evaluated per C++20 [expr.const]p12?
static bool funcHasParameterSizeMangling (Sema &S, FunctionDecl *FD)
Return true if this function has a calling convention that requires mangling in the size of the parameter pack.
static void CheckCompleteParameterTypesForMangler (Sema &S, FunctionDecl *FD, SourceLocation Loc)
Require that all of the parameter types of function be complete.
static OdrUseContext isOdrUseContext (Sema &SemaRef)
Are we within a context in which references to resolved functions or to variables result in odr-use?
static bool isImplicitlyDefinableConstexprFunction (FunctionDecl *Func)
static void MarkVarDeclODRUsed (VarDecl *Var, SourceLocation Loc, Sema &SemaRef, const unsigned *const FunctionScopeIndexToStopAt=nullptr)
Directly mark a variable odr-used.
static bool isVariableAlreadyCapturedInScopeInfo (CapturingScopeInfo *CSI, VarDecl *Var, bool &SubCapturesAreNested, QualType &CaptureType, QualType &DeclRefType)
static DeclContext * getParentOfCapturingContextOrNull (DeclContext *DC, VarDecl *Var, SourceLocation Loc, const bool Diagnose, Sema &S)
static bool isVariableCapturable (CapturingScopeInfo *CSI, VarDecl *Var, SourceLocation Loc, const bool Diagnose, Sema &S)
static bool captureInBlock (BlockScopeInfo *BSI, VarDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool Nested, Sema &S, bool Invalid)
static bool captureInCapturedRegion (CapturedRegionScopeInfo *RSI, VarDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool RefersToCapturedVariable, Sema &S, bool Invalid)
Capture the given variable in the captured region.
static bool captureInLambda (LambdaScopeInfo *LSI, VarDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool RefersToCapturedVariable, const Sema::TryCaptureKind Kind, SourceLocation EllipsisLoc, const bool IsTopScope, Sema &S, bool Invalid)
Capture the given variable in the lambda.
static ExprResult rebuildPotentialResultsAsNonOdrUsed (Sema &S, Expr *E, NonOdrUseReason NOUR)
Walk the set of potential results of an expression and mark them all as non-odr-uses if they satisfy the side-conditions of the NonOdrUseReason.
static void DoMarkVarDeclReferenced (Sema &SemaRef, SourceLocation Loc, VarDecl *Var, Expr *E)
static void MarkExprReferenced (Sema &SemaRef, SourceLocation Loc, Decl *D, Expr *E, bool MightBeOdrUse)
static ExprResult diagnoseUnknownAnyExpr (Sema &S, Expr *E)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (kind)
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Base)
ACCESSSPEC
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
BINDING
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BUILTIN_TYPE [1/2]
#define BUILTIN_TYPE (ID, SINGLETON_ID)
Value:
case BuiltinType::ID:
BUILTIN_TYPE [2/2]
#define BUILTIN_TYPE (Id, SingletonId)
Value:
case BuiltinType::Id:
BUILTINTEMPLATE
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CAPTURED
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CONCEPT
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONSTRUCTORUSINGSHADOW
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CXXCONSTRUCTOR
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDESTRUCTOR
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXMETHOD
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXRECORD
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
DECL
#define DECL (type, base)
Value:
    case Decl::type:
DECL_CONTEXT
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_RANGE
#define DECL_RANGE (Base, First, Last)
DECLARATOR
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECOMPOSITION
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
DEPENDENT_TYPE
#define DEPENDENT_TYPE (Class, Base)
Value:
case Type::Class:
EMPTY
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPORT
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXT_OPAQUE_TYPE [1/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id:
EXT_OPAQUE_TYPE [2/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id:
EXTERNCCONTEXT
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
FIELD
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FRIEND
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FUNCTION
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONTEMPLATE
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
IMAGE_TYPE [1/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id:
IMAGE_TYPE [2/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id:
IMPLICITPARAM
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPORT
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
LABEL
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LAST_DECL_RANGE
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MSGUID
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
NAMED
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NON_CANONICAL_TYPE
#define NON_CANONICAL_TYPE (Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
NONTYPETEMPLATEPARM
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
OBJCATDEFSFIELD
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCCATEGORY
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCIMPL
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINTERFACE
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIVAR
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCMETHOD
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROTOCOL
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCTYPEPARAM
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OMPALLOCATE
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPCAPTUREDEXPR
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPDECLAREMAPPER
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPREQUIRES
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
PARMVAR
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PLACEHOLDER_TYPE [1/2]
#define PLACEHOLDER_TYPE (ID, SINGLETON_ID)
PLACEHOLDER_TYPE [2/2]
#define PLACEHOLDER_TYPE (Id, SingletonId)
PPC_VECTOR_TYPE [1/2]
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
  case BuiltinType::Id:
PPC_VECTOR_TYPE [2/2]
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
  case BuiltinType::Id:
PRAGMACOMMENT
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
RECORD
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
REDECLARABLETEMPLATE
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPRBODY
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
SVE_TYPE [1/2]
#define SVE_TYPE (Name, Id, SingletonId)
Value:
  case BuiltinType::Id:
SVE_TYPE [2/2]
#define SVE_TYPE (Name, Id, SingletonId)
Value:
  case BuiltinType::Id:
TAG
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE [1/2]
#define TYPE (Class, Base)
TYPE [2/2]
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPEALIAS
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USING
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VALUE
#define VALUE (type, base)
VAR
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
Typedef Documentation
PerformCastFn
typedef ExprResult PerformCastFn(Sema &S, Expr *operand, QualType toType)
Definition at line 1229 of file SemaExpr.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ConstFunction
ConstVariable
ConstMember
ConstMethod
NestedConstMember
ConstUnknown
Definition at line 12513 of file SemaExpr.cpp.
NonConstCaptureKind
enum NonConstCaptureKind
Is the given expression (which must be 'const') a reference to a variable which was originally non-const, but which has become 'const' due to being captured within a block?
Enumerator
NCCK_None
NCCK_Block
NCCK_Lambda
Definition at line 12467 of file SemaExpr.cpp.
OriginalExprKind
enum OriginalExprKind
Enumerator
OEK_Variable
OEK_Member
OEK_LValue
Definition at line 12645 of file SemaExpr.cpp.
Function Documentation
breakDownVectorType()
static bool breakDownVectorType (QualType type, uint64_t & len, QualType & eltType) static
Definition at line 7251 of file SemaExpr.cpp.
References clang::Type::getAs(), clang::Type::isScalarType(), and clang::ast_matchers::type.
Referenced by clang::Sema::areLaxCompatibleVectorTypes().
BuildCookedLiteralOperatorCall()
static ExprResult BuildCookedLiteralOperatorCall (Sema & S, Scope * Scope, IdentifierInfo * UDSuffix, SourceLocation UDSuffixLoc, ArrayRef< Expr * > Args, SourceLocation LitEndLoc) static
BuildCookedLiteralOperatorCall - A user-defined literal was found.
Look up the corresponding cooked (non-raw) literal operator, and build a call to it.
Definition at line 1757 of file SemaExpr.cpp.
References clang::Sema::BuildLiteralOperatorCall(), clang::Sema::Context, clang::ASTContext::DeclarationNames, clang::ExprError(), clang::ASTContext::getArrayDecayedType(), clang::DeclarationNameTable::getCXXLiteralOperatorName(), clang::Sema::LOLR_Error, clang::Sema::LookupLiteralOperator(), clang::Sema::LookupOrdinaryName, and clang::DeclarationNameInfo::setCXXLiteralOperatorNameLoc().
Referenced by clang::Sema::ActOnCharacterConstant().
BuildFloatingLiteral()
static Expr * BuildFloatingLiteral (Sema & S, NumericLiteralParser & Literal, QualType Ty, SourceLocation Loc) static
Definition at line 3592 of file SemaExpr.cpp.
References clang::Sema::Context, clang::FloatingLiteral::Create(), clang::Sema::Diag(), clang::ASTContext::getFloatTypeSemantics(), and clang::NumericLiteralParser::GetFloatValue().
Referenced by clang::Sema::ActOnNumericConstant().
BuildOverloadedBinOp()
static ExprResult BuildOverloadedBinOp (Sema & S, Scope * Sc, SourceLocation OpLoc, BinaryOperatorKind Opc, Expr * LHS, Expr * RHS) static
Build an overloaded binary operator expression in the given scope.
Definition at line 14346 of file SemaExpr.cpp.
References CheckIdentityFieldAssignment(), clang::Sema::CreateOverloadedBinOp(), DiagnoseSelfAssignment(), and clang::Sema::LookupBinOp().
Referenced by clang::Sema::BuildBinOp().
canConvertIntToOtherIntTy()
static bool canConvertIntToOtherIntTy (Sema & S, ExprResult * Int, QualType OtherIntTy) static
Test if a (constant) integer Int can be casted to another integer type IntTy without losing precision.
Definition at line 9702 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Expr::EvaluateAsInt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::APValue::getInt(), clang::ASTContext::getIntegerTypeOrder(), clang::ASTContext::getIntWidth(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::Type::hasSignedIntegerRepresentation(), clang::Result, and clang::Expr::EvalResult::Val.
Referenced by tryGCCVectorConvertAndSplat().
canConvertIntTyToFloatTy()
static bool canConvertIntTyToFloatTy (Sema & S, ExprResult * Int, QualType FloatTy) static
Test if a (constant) integer Int can be casted to floating point type FloatTy without losing precision.
Definition at line 9740 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Expr::EvaluateAsInt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getFloatTypeSemantics(), clang::APValue::getInt(), clang::ASTContext::getIntWidth(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::QualType::getUnqualifiedType(), clang::Type::hasSignedIntegerRepresentation(), clang::Result, and clang::Expr::EvalResult::Val.
Referenced by tryGCCVectorConvertAndSplat().
captureInBlock()
static bool captureInBlock (BlockScopeInfo * BSI, VarDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool Nested, Sema & S, bool Invalid) static
Definition at line 17194 of file SemaExpr.cpp.
References clang::sema::CapturingScopeInfo::addCapture(), clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), clang::QualType::getObjCLifetime(), clang::Type::getPointeeType(), clang::Decl::hasAttr(), clang::ASTContext::hasDirectOwnershipQualifier(), clang::Type::isArrayType(), clang::Sema::isOpenMPCapturedDecl(), clang::Type::isReferenceType(), clang::Qualifiers::OCL_Autoreleasing, and clang::QualType::withConst().
Referenced by clang::Sema::tryCaptureVariable().
captureInCapturedRegion()
static bool captureInCapturedRegion (CapturedRegionScopeInfo * RSI, VarDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool RefersToCapturedVariable, Sema & S, bool Invalid) static
Capture the given variable in the captured region.
Definition at line 17266 of file SemaExpr.cpp.
References clang::sema::CapturingScopeInfo::addCapture(), clang::QualType::addConst(), clang::sema::CapturedRegionScopeInfo::CapRegionKind, clang::Sema::Context, clang::CR_OpenMP, clang::Sema::getLangOpts(), clang::ASTContext::getLValueReferenceType(), clang::QualType::getUnqualifiedType(), clang::QualType::isConstQualified(), clang::Sema::isOpenMPCapturedByRef(), clang::Sema::isOpenMPCapturedDecl(), clang::Sema::isOpenMPPrivateDecl(), clang::sema::CapturedRegionScopeInfo::OpenMPCaptureLevel, and clang::sema::CapturedRegionScopeInfo::OpenMPLevel.
Referenced by clang::Sema::tryCaptureVariable().
captureInLambda()
static bool captureInLambda (LambdaScopeInfo * LSI, VarDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool RefersToCapturedVariable, const Sema::TryCaptureKind Kind, SourceLocation EllipsisLoc, const bool IsTopScope, Sema & S, bool Invalid) static
Capture the given variable in the lambda.
Definition at line 17307 of file SemaExpr.cpp.
References clang::sema::CapturingScopeInfo::addCapture(), clang::QualType::addConst(), clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::ASTContext::getLValueReferenceType(), clang::QualType::getNonReferenceType(), clang::QualType::getObjCLifetime(), clang::Type::getPointeeType(), clang::sema::CapturingScopeInfo::ImpCaptureStyle, clang::Type::isDependentType(), clang::Type::isReferenceType(), clang::sema::LambdaScopeInfo::Mutable, clang::Qualifiers::OCL_Autoreleasing, clang::Sema::RequireCompleteSizedType(), clang::Sema::RequireNonAbstractType(), clang::Sema::TryCapture_ExplicitByRef, and clang::Sema::TryCapture_Implicit.
Referenced by clang::Sema::tryCaptureVariable().
captureVariablyModifiedType()
static void captureVariablyModifiedType (ASTContext & Context, QualType T, CapturingScopeInfo * CSI) static
Definition at line 4306 of file SemaExpr.cpp.
References clang::sema::CapturingScopeInfo::addVLATypeCapture(), clang::cast(), clang::ArrayType::getElementType(), clang::VariableArrayType::getSizeExpr(), clang::ASTContext::getSizeType(), clang::Type::getTypeClass(), and clang::sema::CapturingScopeInfo::isVLATypeCaptured().
Referenced by clang::Sema::CreateBuiltinArraySubscriptExpr(), clang::Sema::CreateUnaryExprOrTypeTraitExpr(), and clang::Sema::tryCaptureVariable().
castKindToImplicitConversionKind()
static ImplicitConversionKind castKindToImplicitConversionKind (CastKind CK) static
Definition at line 11348 of file SemaExpr.cpp.
References clang::CastExpr::getCastKindName(), clang::ICK_Array_To_Pointer, clang::ICK_Complex_Conversion, clang::ICK_Complex_Real, clang::ICK_Floating_Conversion, clang::ICK_Floating_Integral, clang::ICK_Function_To_Pointer, clang::ICK_Identity, clang::ICK_Integral_Conversion, and clang::ICK_Lvalue_To_Rvalue.
Referenced by checkThreeWayNarrowingConversion().
CheckAlignOfExpr()
static bool CheckAlignOfExpr (Sema & S, Expr * E, UnaryExprOrTypeTrait ExprKind) static
Definition at line 4240 of file SemaExpr.cpp.
References clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::Diag(), clang::Expr::getExprLoc(), clang::Expr::getObjectKind(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParens(), clang::Expr::isTypeDependent(), and clang::OK_BitField.
Referenced by clang::Sema::CreateUnaryExprOrTypeTraitExpr().
checkArgsForPlaceholders()
static bool checkArgsForPlaceholders (Sema & S, MultiExprArg args) static
Check an argument list for placeholders that we won't try to handle later.
Definition at line 6103 of file SemaExpr.cpp.
References clang::Sema::CheckPlaceholderExpr(), clang::ActionResult< PtrTy, CompressInvalid >::get(), getType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and isPlaceholderToRemoveAsArg().
Referenced by clang::Sema::BuildCallExpr().
checkArithmeticBinOpPointerOperands()
static bool checkArithmeticBinOpPointerOperands (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Check the validity of a binary arithmetic operation w.r.t.
pointer operands.
This routine will diagnose any invalid arithmetic on pointer operands much like
See also
checkArithmeticOpPointerOperand. However, it has special logic for emitting a single diagnostic even for operations where both LHS and RHS are (potentially problematic) pointers.
Returns
True when the operand is valid to use (even if as an extension).
Definition at line 10355 of file SemaExpr.cpp.
References checkArithmeticIncompletePointerType(), clang::Sema::Diag(), diagnoseArithmeticOnFunctionPointer(), diagnoseArithmeticOnTwoFunctionPointers(), diagnoseArithmeticOnTwoVoidPointers(), diagnoseArithmeticOnVoidPointer(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::QualType::isAddressSpaceOverlapping(), clang::Type::isAnyPointerType(), clang::Type::isFunctionType(), and clang::Type::isVoidType().
Referenced by clang::Sema::CheckSubtractionOperands().
checkArithmeticIncompletePointerType()
static bool checkArithmeticIncompletePointerType (Sema & S, SourceLocation Loc, Expr * Operand) static
Emit error if Operand is incomplete pointer type.
Returns
True if pointer has incomplete type
Definition at line 10301 of file SemaExpr.cpp.
References clang::Type::getAs(), clang::Type::getPointeeType(), clang::Type::isAnyPointerType(), clang::Type::isDependentType(), and clang::Sema::RequireCompleteSizedType().
Referenced by checkArithmeticBinOpPointerOperands(), checkArithmeticOpPointerOperand(), and CheckIncrementDecrementOperand().
checkArithmeticNull()
static void checkArithmeticNull (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsCompare) static
Definition at line 10085 of file SemaExpr.cpp.
References clang::Type::canDecayToPointerType(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::isa(), clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), clang::Type::isFunctionType(), and clang::Type::isMemberPointerType().
Referenced by clang::Sema::CheckAdditionOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOnObjCPointer()
static bool checkArithmeticOnObjCPointer (Sema & S, SourceLocation opLoc, Expr * op) static
Diagnose if arithmetic on the given ObjC pointer is illegal.
Returns
true on error
Definition at line 4576 of file SemaExpr.cpp.
References clang::ObjCRuntime::allowsPointerArithmetic(), clang::Type::castAs(), clang::Sema::Diag(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isObjCObjectPointerType(), clang::Sema::LangOpts, and clang::LangOptions::ObjCRuntime.
Referenced by clang::Sema::CheckAdditionOperands(), CheckIncrementDecrementOperand(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOpPointerOperand()
static bool checkArithmeticOpPointerOperand (Sema & S, SourceLocation Loc, Expr * Operand) static
Check the validity of an arithmetic pointer operand.
If the operand has pointer type, this code will check for pointer types which are invalid in arithmetic operations. These will be diagnosed appropriately, including whether or not the use is supported as an extension.
Returns
True when the operand is valid to use (even if as an extension).
Definition at line 10323 of file SemaExpr.cpp.
References checkArithmeticIncompletePointerType(), diagnoseArithmeticOnFunctionPointer(), diagnoseArithmeticOnVoidPointer(), clang::Type::getAs(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::Type::isAnyPointerType(), clang::Type::isFunctionType(), and clang::Type::isVoidType().
Referenced by clang::Sema::CheckAdditionOperands(), CheckIncrementDecrementOperand(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOrEnumeralCompare()
static QualType checkArithmeticOrEnumeralCompare (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc) static
Definition at line 11510 of file SemaExpr.cpp.
References clang::Sema::ACK_Comparison, checkArithmeticOrEnumeralThreeWayCompare(), clang::Sema::CheckFloatComparison(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getLogicalOperationType(), clang::Type::hasFloatingRepresentation(), clang::Sema::InvalidOperands(), clang::Type::isAnyComplexType(), clang::Type::isArithmeticType(), clang::Type::isEnumeralType(), clang::BinaryOperator::isEqualityOp(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::BinaryOperator::isRelationalOp(), and clang::Sema::UsualArithmeticConversions().
Referenced by clang::Sema::CheckCompareOperands().
checkArithmeticOrEnumeralThreeWayCompare()
static QualType checkArithmeticOrEnumeralThreeWayCompare (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Definition at line 11428 of file SemaExpr.cpp.
References clang::Sema::ACK_Comparison, clang::Type::castAs(), clang::Sema::CheckComparisonCategoryType(), checkThreeWayNarrowingConversion(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::getComparisonCategoryForBuiltinCmp(), clang::ASTContext::getPromotedIntegerType(), clang::Expr::getType(), clang::Type::hasFloatingRepresentation(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::ImpCastExprToType(), int, clang::Sema::InvalidOperands(), clang::Type::isBooleanType(), clang::Type::isEnumeralType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Sema::OperatorInExpression, and clang::Sema::UsualArithmeticConversions().
Referenced by checkArithmeticOrEnumeralCompare().
checkBlockPointerTypesForAssignment()
static Sema::AssignConvertType checkBlockPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType) static
checkBlockPointerTypesForAssignment - This routine determines whether two block pointer types are compatible or whether a block and normal pointer are compatible.
It is more restrict than comparing two function pointer
Definition at line 8885 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::Compatible, clang::Sema::CompatiblePointerDiscardsQualifiers, clang::Sema::Context, clang::Sema::getLangOpts(), clang::QualType::getLocalQualifiers(), clang::ASTContext::getQualifiedType(), clang::QualType::getUnqualifiedType(), clang::Sema::IncompatibleBlockPointer, clang::QualType::isCanonical(), clang::Qualifiers::removeAddressSpace(), and clang::ASTContext::typesAreBlockPointerCompatible().
Referenced by clang::Sema::CheckAssignmentConstraints().
checkBlockType()
static bool checkBlockType (Sema & S, const Expr * E) static
Return true if the Expr is block type.
Definition at line 8106 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Expr::getExprLoc(), and clang::Type::isBlockPointerType().
Referenced by clang::Sema::CheckConditionalOperands().
CheckCommaOperands()
static QualType CheckCommaOperands (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Definition at line 13091 of file SemaExpr.cpp.
References clang::Sema::CheckPlaceholderExpr(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::DiagnoseCommaOperator(), clang::Sema::DiagnoseUnusedExprResult(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getDiagnostics(), clang::Sema::getLangOpts(), clang::Expr::getType(), clang::Sema::IgnoredValueConversions(), clang::DiagnosticsEngine::isIgnored(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isVoidType(), and clang::Sema::RequireCompleteType().
Referenced by clang::Sema::CreateBuiltinBinOp().
CheckCompleteParameterTypesForMangler()
static void CheckCompleteParameterTypesForMangler (Sema & S, FunctionDecl * FD, SourceLocation Loc) static
Require that all of the parameter types of function be complete.
Normally, parameter types are only required to be complete when a function is called or defined, but to mangle functions with certain calling conventions, the mangler needs to know the size of the parameter list. In this situation, MSVC doesn't emit an error or instantiate templates. Instead, MSVC mangles the function as _foo@0, i.e. zero bytes of parameters, which will usually result in a linker error. Clang doesn't implement this behavior, and instead attempts to error at compile time.
Definition at line 16666 of file SemaExpr.cpp.
References clang::Type::castAs(), clang::CC_X86FastCall, clang::CC_X86StdCall, clang::CC_X86VectorCall, clang::Sema::Diag(), clang::NamedDecl::getDeclName(), clang::ValueDecl::getType(), clang::FunctionDecl::parameters(), and clang::Sema::RequireCompleteType().
Referenced by clang::Sema::MarkFunctionReferenced().
checkCondition()
static bool checkCondition (Sema & S, Expr * Cond, SourceLocation QuestionLoc) static
Return false if the condition expression is valid, true otherwise.
Definition at line 7663 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isFloatingType(), and clang::Type::isScalarType().
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalBlockPointerCompatibility()
static QualType checkConditionalBlockPointerCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Return the resulting type when the operands are both block pointers.
Definition at line 7842 of file SemaExpr.cpp.
References checkConditionalPointerCompatibility(), clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Sema::ImpCastExprToType(), clang::Type::isBlockPointerType(), clang::Type::isVoidPointerType(), and clang::ASTContext::VoidTy.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalNullPointer()
static bool checkConditionalNullPointer (Sema & S, ExprResult & NullExpr, QualType PointerTy) static
Return false if the NullExpr can be promoted to PointerTy, true otherwise.
Definition at line 7700 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::ImpCastExprToType(), clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), clang::Expr::isNullPointerConstant(), and clang::Expr::NPC_ValueDependentIsNull.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalObjectPointersCompatibility()
static QualType checkConditionalObjectPointersCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Return the resulting type when the operands are both pointers.
Definition at line 7868 of file SemaExpr.cpp.
References clang::Type::castAs(), checkConditionalPointerCompatibility(), clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getPointerType(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::Sema::ImpCastExprToType(), clang::Type::isIncompleteOrObjectType(), and clang::Type::isVoidType().
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalPointerCompatibility()
static QualType checkConditionalPointerCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Checks compatibility between two pointers and return the resulting type.
Definition at line 7713 of file SemaExpr.cpp.
References clang::Type::castAs(), clang::Sema::Context, clang::Default, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Qualifiers::getAddressSpace(), clang::ASTContext::getAddrSpaceQualType(), clang::Type::getAs(), clang::ASTContext::getBlockPointerType(), clang::Qualifiers::getCVRQualifiers(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::ASTContext::hasSameType(), clang::Sema::ImpCastExprToType(), clang::Qualifiers::isAddressSpaceSupersetOf(), clang::QualType::isNull(), clang::ASTContext::mergeTypes(), clang::Qualifiers::removeAddressSpace(), clang::Qualifiers::removeCVRQualifiers(), clang::Qualifiers::setAddressSpace(), clang::ASTContext::VoidTy, and clang::QualType::withCVRQualifiers().
Referenced by checkConditionalBlockPointerCompatibility(), and checkConditionalObjectPointersCompatibility().
checkConditionalVoidType()
static QualType checkConditionalVoidType (Sema & S, ExprResult & LHS, ExprResult & RHS) static
Handle when one or both operands are void type.
Definition at line 7682 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Sema::ImpCastExprToType(), clang::Type::isVoidType(), and clang::ASTContext::VoidTy.
Referenced by clang::Sema::CheckConditionalOperands().
CheckDeclInExpr()
static bool CheckDeclInExpr (Sema & S, SourceLocation Loc, NamedDecl * D) static
Diagnoses obvious problems with the use of the given declaration as an expression.
This is only actually called for lookups that were not overloaded, and it doesn't promise that the declaration will in fact be used.
Definition at line 3124 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::NamedDecl::getDeclName(), and clang::Decl::isInvalidDecl().
Referenced by clang::Sema::BuildDeclarationNameExpr(), and clang::Sema::BuildDeclarationNameExpr().
checkDirectCallValidity()
static void checkDirectCallValidity (Sema & S, const Expr * Fn, FunctionDecl * Callee, MultiExprArg ArgExprs) static
Definition at line 6203 of file SemaExpr.cpp.
References clang::Sema::CheckEnableIf(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), and clang::Sema::TooManyArguments().
Referenced by clang::Sema::BuildCallExpr().
checkEnumArithmeticConversions()
static void checkEnumArithmeticConversions (Sema & S, Expr * LHS, Expr * RHS, SourceLocation Loc, Sema::ArithConvKind ACK) static
Check that the usual arithmetic conversions can be performed on this pair of expressions that might be of enumeration type.
Definition at line 1429 of file SemaExpr.cpp.
References clang::Sema::ACK_Comparison, clang::Sema::ACK_CompAssign, clang::Sema::ACK_Conditional, clang::Type::castAs(), clang::Sema::Context, clang::Sema::Diag(), clang::EnumType::getDecl(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::TagDecl::hasNameForLinkage(), clang::ASTContext::hasSameUnqualifiedType(), int, clang::Type::isFloatingType(), and clang::Type::isUnscopedEnumerationType().
Referenced by clang::Sema::UsualArithmeticConversions().
CheckExtensionTraitOperandType()
static bool CheckExtensionTraitOperandType (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind) static
Definition at line 4013 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::getTraitSpelling(), and clang::Sema::LangOpts.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand(), and clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkForArray()
static bool checkForArray (const Expr * E) static
Definition at line 11207 of file SemaExpr.cpp.
References clang::ValueDecl::getType(), clang::Type::isArrayType(), and clang::ValueDecl::isWeak().
Referenced by diagnoseTautologicalComparison().
CheckForModifiableLvalue()
static bool CheckForModifiableLvalue (Expr * E, SourceLocation Loc, Sema & S) static
CheckForModifiableLvalue - Verify that E is a modifiable lvalue.
If not, emit an error and return true. If so, return false.
Definition at line 12715 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::CheckShadowingDeclModification(), clang::Sema::Context, clang::Sema::Diag(), DiagnoseConstAssignment(), DiagnoseRecursiveConstFields(), clang::Sema::getCurMethodDecl(), clang::DeclRefExpr::getDecl(), clang::Sema::getLangOpts(), clang::ObjCMethodDecl::getSelfDecl(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::TypeSourceInfo::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::Decl::hasAttr(), clang::Expr::hasPlaceholderType(), clang::Expr::IgnoreParenCasts(), clang::VarDecl::isARCPseudoStrong(), clang::ObjCMethodDecl::isClassMethod(), clang::QualType::isConstQualified(), clang::Expr::isModifiableLvalue(), IsReadonlyMessage(), isReferenceToNonConstCapture(), clang::Expr::MLV_ArrayTemporary, clang::Expr::MLV_ArrayType, clang::Expr::MLV_ClassTemporary, clang::Expr::MLV_ConstAddrSpace, clang::Expr::MLV_ConstQualified, clang::Expr::MLV_ConstQualifiedField, clang::Expr::MLV_DuplicateVectorComponents, clang::Expr::MLV_IncompleteType, clang::Expr::MLV_IncompleteVoidType, clang::Expr::MLV_InvalidExpression, clang::Expr::MLV_InvalidMessageExpression, clang::Expr::MLV_LValueCast, clang::Expr::MLV_MemberFunction, clang::Expr::MLV_NoSetterProperty, clang::Expr::MLV_NotObjectType, clang::Expr::MLV_SubObjCPropertySetting, clang::Expr::MLV_Valid, NCCK_Block, and clang::Sema::RequireCompleteType().
Referenced by clang::Sema::BuildVAArgExpr(), clang::Sema::CheckAssignmentOperands(), and CheckIncrementDecrementOperand().
CheckForNullPointerDereference()
static void CheckForNullPointerDereference (Sema & S, Expr * E) static
Definition at line 541 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::DiagRuntimeBehavior(), clang::Expr::IgnoreParenCasts(), clang::isTargetAddressSpace(), clang::Expr::NPC_ValueDependentIsNotNull, clang::Sema::PDiag(), and clang::toTargetAddressSpace().
Referenced by clang::Sema::CheckAssignmentOperands(), clang::Sema::DefaultLvalueConversion(), and clang::InitializationSequence::Perform().
CheckIdentityFieldAssignment()
static void CheckIdentityFieldAssignment (Expr * LHSExpr, Expr * RHSExpr, SourceLocation Loc, Sema & Sema) static
Definition at line 12843 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::Diag(), clang::Type::getAs(), clang::MemberExpr::getBase(), clang::ObjCIvarRefExpr::getBase(), clang::Decl::getCanonicalDecl(), clang::DeclRefExpr::getDecl(), clang::ObjCIvarRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::MemberExpr::getMemberDecl(), clang::ValueDecl::getType(), clang::Expr::IgnoreImpCasts(), clang::Sema::inTemplateInstantiation(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), clang::Sema::isUnevaluatedContext(), and clang::QualType::isVolatileQualified().
Referenced by BuildOverloadedBinOp(), and clang::Sema::CheckAssignmentOperands().
CheckIncrementDecrementOperand()
static QualType CheckIncrementDecrementOperand (Sema & S, Expr * Op, ExprValueKind & VK, ExprObjectKind & OK, SourceLocation OpLoc, bool IsInc, bool IsPrefix) static
CheckIncrementDecrementOperand - unlike most "Check" methods, this routine doesn't need to call UsualUnaryConversions or UsualArithmeticConversions.
Definition at line 13127 of file SemaExpr.cpp.
References clang::VectorType::AltiVecBool, clang::Type::castAs(), checkArithmeticIncompletePointerType(), checkArithmeticOnObjCPointer(), checkArithmeticOpPointerOperand(), CheckForModifiableLvalue(), CheckIncrementDecrementOperand(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::Context, clang::ASTContext::DependentTy, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::VectorType::getElementType(), clang::Sema::getLangOpts(), clang::Expr::getObjectKind(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::VectorType::getVectorKind(), int, clang::Type::isAnyComplexType(), clang::Type::isBooleanType(), clang::Type::isEnumeralType(), clang::Type::isIntegerType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::QualType::isNull(), clang::Type::isObjCObjectPointerType(), clang::Type::isPlaceholderType(), clang::Type::isPointerType(), clang::Type::isRealType(), clang::Expr::isTypeDependent(), clang::Type::isVectorType(), clang::QualType::isVolatileQualified(), clang::VK_LValue, and clang::VK_RValue.
Referenced by CheckIncrementDecrementOperand(), and clang::Sema::CreateBuiltinUnaryOp().
CheckIndirectionOperand()
static QualType CheckIndirectionOperand (Sema & S, Expr * Op, ExprValueKind & VK, SourceLocation OpLoc) static
CheckIndirectionOperand - Type check unary indirection (prefix '*').
Definition at line 13542 of file SemaExpr.cpp.
References clang::Sema::CheckCompatibleReinterpretCast(), CheckIndirectionOperand(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::Context, clang::ASTContext::DependentTy, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Expr::isTypeDependent(), clang::Result, clang::Sema::UsualUnaryConversions(), clang::VK_LValue, and clang::VK_RValue.
Referenced by CheckIndirectionOperand(), and clang::Sema::CreateBuiltinUnaryOp().
checkObjCPointerIntrospection()
static void checkObjCPointerIntrospection (Sema & S, ExprResult & L, ExprResult & R, SourceLocation OpLoc) static
Check if a bitwise-& is performed on an Objective-C pointer.
This is usually indicative of introspection within the Objective-C pointer.
Definition at line 13702 of file SemaExpr.cpp.
References clang::Sema::Diag(), Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), and clang::Type::isObjCObjectPointerType().
Referenced by clang::Sema::CreateBuiltinBinOp().
checkObjCPointerTypesForAssignment()
static Sema::AssignConvertType checkObjCPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType) static
checkObjCPointerTypesForAssignment - Compares two objective-c pointer types for assignment compatibility.
Definition at line 8936 of file SemaExpr.cpp.
References clang::Type::castAs(), clang::Sema::Compatible, clang::Sema::CompatiblePointerDiscardsQualifiers, clang::Sema::Context, clang::Sema::IncompatibleObjCQualifiedId, clang::Sema::IncompatiblePointer, clang::QualType::isAtLeastAsQualifiedAs(), clang::QualType::isCanonical(), clang::Type::isObjCBuiltinType(), clang::Type::isObjCClassType(), clang::Type::isObjCQualifiedClassType(), clang::Type::isObjCQualifiedIdType(), and clang::ASTContext::typesAreCompatible().
Referenced by clang::Sema::CheckAssignmentConstraints().
CheckObjCTraitOperandConstraints()
static bool CheckObjCTraitOperandConstraints (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind) static
Definition at line 4043 of file SemaExpr.cpp.
References clang::ObjCRuntime::allowsSizeofAlignof(), clang::Sema::Diag(), clang::Sema::LangOpts, and clang::LangOptions::ObjCRuntime.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand(), and clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkOpenCLConditionVector()
static bool checkOpenCLConditionVector (Sema & S, Expr * Cond, SourceLocation QuestionLoc) static
Return false if this is a valid OpenCL condition vector.
Definition at line 8026 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Type::getAs(), clang::VectorType::getElementType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), and clang::Type::isIntegerType().
Referenced by OpenCLCheckVectorConditional().
checkPointerIntegerMismatch()
static bool checkPointerIntegerMismatch (Sema & S, ExprResult & Int, Expr * PointerExpr, SourceLocation Loc, bool IsIntFirstExpr) static
Return false if the first expression is not an integer and the second expression is not a pointer, true otherwise.
Definition at line 7907 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Sema::ImpCastExprToType(), clang::Type::isIntegerType(), and clang::Type::isPointerType().
Referenced by clang::Sema::CheckConditionalOperands().
checkPointerTypesForAssignment()
static Sema::AssignConvertType checkPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType) static
Definition at line 8743 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::Compatible, clang::Sema::CompatiblePointerDiscardsQualifiers, clang::Qualifiers::compatiblyIncludes(), clang::Qualifiers::compatiblyIncludesObjCLifetime(), clang::Sema::Context, clang::Sema::FunctionVoidPointer, clang::Qualifiers::getAddressSpace(), clang::ASTContext::getCorrespondingUnsignedType(), clang::Sema::getLangOpts(), clang::Qualifiers::getObjCLifetime(), clang::Type::hasSignedIntegerRepresentation(), clang::Sema::IncompatibleFunctionPointer, clang::Sema::IncompatibleNestedPointerAddressSpaceMismatch, clang::Sema::IncompatibleNestedPointerQualifiers, clang::Sema::IncompatiblePointer, clang::Sema::IncompatiblePointerDiscardsQualifiers, clang::Sema::IncompatiblePointerSign, clang::Qualifiers::isAddressSpaceSupersetOf(), clang::QualType::isCanonical(), clang::Type::isCharType(), clang::Sema::IsFunctionConversion(), clang::Type::isFunctionPointerType(), clang::Type::isFunctionType(), clang::Type::isIncompleteOrObjectType(), IsInvalidCmseNSCallConversion(), clang::Type::isVoidType(), clang::Qualifiers::removeObjCLifetime(), clang::ASTContext::typesAreCompatible(), clang::ASTContext::UnsignedCharTy, clang::Qualifiers::withoutObjCGCAttr(), and clang::Qualifiers::withoutObjCLifetime().
Referenced by clang::Sema::CheckAssignmentConstraints().
CheckRealImagOperand()
static QualType CheckRealImagOperand (Sema & S, ExprResult & V, SourceLocation Loc, bool IsReal) static
Definition at line 4519 of file SemaExpr.cpp.
References clang::Sema::CheckPlaceholderExpr(), CheckRealImagOperand(), clang::Sema::Context, clang::Sema::DefaultLvalueConversion(), clang::ASTContext::DependentTy, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::OK_Ordinary, and V.
Referenced by CheckRealImagOperand(), and clang::Sema::CreateBuiltinUnaryOp().
checkThreeWayNarrowingConversion()
static bool checkThreeWayNarrowingConversion (Sema & S, QualType ToType, Expr * E, QualType FromType, SourceLocation Loc) static
Definition at line 11385 of file SemaExpr.cpp.
References castKindToImplicitConversionKind(), clang::Sema::Context, clang::Sema::Diag(), clang::APValue::getAsString(), clang::Stmt::getBeginLoc(), clang::StandardConversionSequence::getNarrowingKind(), clang::NK_Constant_Narrowing, clang::NK_Dependent_Narrowing, clang::NK_Not_Narrowing, clang::NK_Type_Narrowing, clang::NK_Variable_Narrowing, clang::StandardConversionSequence::Second, clang::StandardConversionSequence::setAsIdentityConversion(), and clang::StandardConversionSequence::setToType().
Referenced by checkArithmeticOrEnumeralThreeWayCompare().
CheckVecStepTraitOperandType()
static bool CheckVecStepTraitOperandType (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange) static
Definition at line 3995 of file SemaExpr.cpp.
References clang::Sema::Diag().
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand(), and clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkVectorResult()
static bool checkVectorResult (Sema & S, QualType CondTy, QualType VecResTy, SourceLocation QuestionLoc) static
Return false if the vector condition type and the vector result type are compatible.
OpenCL v1.1 s6.11.6 requires that both vector types have the same number of elements, and their element types have the same number of bits.
Definition at line 8046 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::VectorType::getElementType(), clang::VectorType::getNumElements(), and clang::ASTContext::getTypeSize().
Referenced by OpenCLCheckVectorConditional().
checkVectorShift()
static QualType checkVectorShift (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsCompAssign) static
Return the resulting type when a vector is shifted by a scalar or vector shift amount.
Definition at line 10817 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::VectorType::getElementType(), clang::ASTContext::getExtVectorType(), clang::VectorType::getNumElements(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::Sema::ImpCastExprToType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Type::isVectorType(), clang::Sema::LangOpts, and clang::Sema::UsualUnaryConversions().
Referenced by clang::Sema::CheckShiftOperands().
computeConditionalNullability()
static QualType computeConditionalNullability (QualType ResTy, bool IsBin, QualType LHSTy, QualType RHSTy, ASTContext & Ctx) static
Compute the nullability of a conditional expression.
Definition at line 8562 of file SemaExpr.cpp.
References clang::ASTContext::getAttributedType(), clang::Type::getNullability(), clang::AttributedType::getNullabilityAttrKind(), clang::QualType::getSingleStepDesugaredType(), clang::Type::isAnyPointerType(), clang::NonNull, clang::Nullable, clang::NullableResult, and clang::Unspecified.
Referenced by clang::Sema::ActOnConditionalOp().
ConstructTransparentUnion()
static void ConstructTransparentUnion (Sema & S, ASTContext & C, ExprResult & EResult, QualType UnionType, FieldDecl * Field) static
Constructs a transparent union from an expression that is used to initialize the transparent union.
Definition at line 9330 of file SemaExpr.cpp.
References clang::C, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Initializer, clang::Expr::setType(), and clang::VK_RValue.
Referenced by clang::Sema::CheckTransparentUnionArgumentConstraints().
convertHalfVecBinOp()
static ExprResult convertHalfVecBinOp (Sema & S, ExprResult LHS, ExprResult RHS, BinaryOperatorKind Opc, QualType ResultTy, ExprValueKind VK, ExprObjectKind OK, bool IsCompAssign, SourceLocation OpLoc, FPOptionsOverride FPFeatures) static
Definition at line 13758 of file SemaExpr.cpp.
References clang::Type::castAs(), convertVector(), clang::BinaryOperator::Create(), clang::CompoundAssignOperator::Create(), clang::ASTContext::FloatTy, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getASTContext(), clang::VectorType::getElementType(), clang::Sema::GetSignedVectorType(), clang::Expr::getType(), clang::ASTContext::HalfTy, isVector(), and clang::ASTContext::ShortTy.
Referenced by clang::Sema::CreateBuiltinBinOp().
convertPointersToCompositeType()
static bool convertPointersToCompositeType (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS) static
Returns false if the pointers are converted to a composite type, true otherwise.
Definition at line 10975 of file SemaExpr.cpp.
References diagnoseDistinctPointerComparison(), clang::Sema::FindCompositePointerType(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Expr::getType(), clang::Sema::InvalidOperands(), clang::Type::isAnyPointerType(), clang::Type::isMemberPointerType(), and clang::Type::isPointerType().
Referenced by clang::Sema::CheckCompareOperands().
ConvertTokenKindToUnaryOpcode()
static UnaryOperatorKind ConvertTokenKindToUnaryOpcode (tok::TokenKind Kind) inline static
Definition at line 13644 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnUnaryOp().
ConvertUTF8ToWideString()
static void ConvertUTF8ToWideString (unsigned CharByteWidth, StringRef Source, SmallString< 32 > & Target) static
Definition at line 3447 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildPredefinedExpr().
convertVector()
static ExprResult convertVector (Expr * E, QualType ElementType, Sema & S) static
Convert vector E to a vector with the same number of elements but different element type.
Definition at line 9683 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Type::getAs(), clang::Expr::getType(), clang::ASTContext::getVectorType(), clang::Sema::ImpCastExprToType(), and clang::Type::isIntegerType().
Referenced by convertHalfVecBinOp(), and clang::Sema::CreateBuiltinUnaryOp().
CorrectDelayedTyposInBinOp()
static std::pair< ExprResult, ExprResult > CorrectDelayedTyposInBinOp (Sema & S, BinaryOperatorKind Opc, Expr * LHSExpr, Expr * RHSExpr) static
Definition at line 13791 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::CorrectDelayedTyposInExpr(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), getDeclFromExpr(), and clang::ASTContext::isDependenceAllowed().
Referenced by clang::Sema::BuildBinOp(), and clang::Sema::CreateBuiltinBinOp().
DiagnoseAdditionInShift()
static void DiagnoseAdditionInShift (Sema & S, SourceLocation OpLoc, Expr * SubExpr, StringRef Shift) static
Definition at line 14242 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by DiagnoseBinOpPrecedence().
diagnoseAddressOfInvalidType()
static void diagnoseAddressOfInvalidType (Sema & S, SourceLocation Loc, Expr * E, unsigned Type) static
Diagnose invalid operand for address of operations.
Parameters
Type The type of operand which cannot have its address taken.
Definition at line 13292 of file SemaExpr.cpp.
References clang::Sema::Diag(), and clang::Stmt::getSourceRange().
Referenced by clang::Sema::CheckAddressOfOperand().
diagnoseArithmeticOnFunctionPointer()
static void diagnoseArithmeticOnFunctionPointer (Sema & S, SourceLocation Loc, Expr * Pointer) static
Diagnose invalid arithmetic on a function pointer.
Definition at line 10287 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), and Pointer.
Referenced by checkArithmeticBinOpPointerOperands(), and checkArithmeticOpPointerOperand().
diagnoseArithmeticOnNullPointer()
static void diagnoseArithmeticOnNullPointer (Sema & S, SourceLocation Loc, Expr * Pointer, bool IsGNUIdiom) static
Diagnose invalid arithmetic on a null pointer.
If IsGNUIdiom is true, the operation is using the 'p = (i8*)nullptr + n' idiom, which we recognize as a GNU extension.
Definition at line 10260 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), and Pointer.
Referenced by clang::Sema::CheckAdditionOperands(), and clang::Sema::CheckSubtractionOperands().
diagnoseArithmeticOnTwoFunctionPointers()
static void diagnoseArithmeticOnTwoFunctionPointers (Sema & S, SourceLocation Loc, Expr * LHS, Expr * RHS) static
Diagnose invalid arithmetic on two function pointers.
Definition at line 10271 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::hasSameUnqualifiedType(), and clang::Type::isAnyPointerType().
Referenced by checkArithmeticBinOpPointerOperands().
diagnoseArithmeticOnTwoVoidPointers()
static void diagnoseArithmeticOnTwoVoidPointers (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Diagnose invalid arithmetic on two void pointers.
Definition at line 10237 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), and clang::Stmt::getSourceRange().
Referenced by checkArithmeticBinOpPointerOperands().
diagnoseArithmeticOnVoidPointer()
static void diagnoseArithmeticOnVoidPointer (Sema & S, SourceLocation Loc, Expr * Pointer) static
Diagnose invalid arithmetic on a void pointer.
Definition at line 10247 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), and Pointer.
Referenced by checkArithmeticBinOpPointerOperands(), and checkArithmeticOpPointerOperand().
DiagnoseBadDivideOrRemainderValues()
static void DiagnoseBadDivideOrRemainderValues (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsDiv) static
Definition at line 10169 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::DiagRuntimeBehavior(), clang::Expr::EvaluateAsInt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::APValue::getInt(), clang::Stmt::getSourceRange(), clang::Expr::isValueDependent(), clang::Sema::PDiag(), and clang::Expr::EvalResult::Val.
Referenced by clang::Sema::CheckMultiplyDivideOperands(), and clang::Sema::CheckRemainderOperands().
DiagnoseBadShiftValues()
static void DiagnoseBadShiftValues (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc, QualType LHSType) static
Definition at line 10721 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagRuntimeBehavior(), clang::Expr::EvaluateAsInt(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getFixedPointSemantics(), clang::APValue::getInt(), clang::ASTContext::getIntWidth(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::Type::hasUnsignedIntegerRepresentation(), clang::Type::isExtIntType(), clang::Type::isFixedPointType(), clang::LangOptions::isSignedOverflowDefined(), clang::Expr::isValueDependent(), clang::Sema::PDiag(), clang::Result, and clang::Expr::EvalResult::Val.
Referenced by clang::Sema::CheckShiftOperands().
DiagnoseBinOpPrecedence()
static void DiagnoseBinOpPrecedence (Sema & Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
DiagnoseBinOpPrecedence - Emit warnings for expressions with tricky precedence.
Definition at line 14284 of file SemaExpr.cpp.
References DiagnoseAdditionInShift(), DiagnoseBitwiseOpInBitwiseOp(), DiagnoseBitwisePrecedence(), DiagnoseLogicalAndInLogicalOrLHS(), DiagnoseLogicalAndInLogicalOrRHS(), DiagnoseShiftCompare(), clang::Sema::getASTContext(), clang::BinaryOperator::getOpcodeStr(), clang::Expr::getType(), clang::BinaryOperator::isBitwiseOp(), clang::BinaryOperator::isComparisonOp(), clang::Type::isIntegralType(), and clang::SourceLocation::isMacroID().
Referenced by clang::Sema::ActOnBinOp().
DiagnoseBitwiseOpInBitwiseOp()
static void DiagnoseBitwiseOpInBitwiseOp (Sema & S, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * SubExpr) static
Look for bitwise op in the left or right hand of a bitwise op with lower precedence and emit a diagnostic together with a fixit hint that wraps the '&' expression in parentheses.
Definition at line 14227 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::BinaryOperator::getOpcodeStr(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by DiagnoseBinOpPrecedence().
DiagnoseBitwisePrecedence()
static void DiagnoseBitwisePrecedence (Sema & Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
DiagnoseBitwisePrecedence - Emit a warning when bitwise and comparison operators are mixed in a way that suggests that the programmer forgot that comparison operators have higher precedence.
The most typical example of such code is "flags & 0x0020 != 0", which is equivalent to "flags & 1".
Definition at line 14117 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getRHS(), clang::BinaryOperator::isBitwiseOp(), clang::BinaryOperator::isComparisonOp(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by DiagnoseBinOpPrecedence().
DiagnoseCalleeStaticArrayParam()
static void DiagnoseCalleeStaticArrayParam (Sema & S, ParmVarDecl * PVD) static
Definition at line 5967 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::TypeLoc::getAs(), clang::Decl::getLocation(), clang::TypeSourceInfo::getTypeLoc(), and clang::DeclaratorDecl::getTypeSourceInfo().
Referenced by clang::Sema::CheckStaticArrayArgument().
DiagnoseConditionalPrecedence()
static void DiagnoseConditionalPrecedence (Sema & Self, SourceLocation OpLoc, Expr * Condition, Expr * LHSExpr, Expr * RHSExpr) static
DiagnoseConditionalPrecedence - Emit a warning when a conditional operator and binary operator are mixed in a way that suggests the programmer assumed the conditional operator has higher precedence, for example: "int x = a + someBinaryCondition ? 1 : 2".
Definition at line 8526 of file SemaExpr.cpp.
References clang::Condition, clang::Sema::Diag(), ExprLooksBoolean(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::BinaryOperator::getOpcodeStr(), IsArithmeticBinaryExpr(), clang::BinaryOperator::isBitwiseOp(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by clang::Sema::ActOnConditionalOp().
DiagnoseConstAssignment()
static void DiagnoseConstAssignment (Sema & S, const Expr * E, SourceLocation Loc) static
Emit the "read-only variable not assignable" error and print notes to give more information about why the variable is not assignable, such as pointing to the declaration of a const variable, showing that a method is const, or that the function is returning a const reference.
Definition at line 12526 of file SemaExpr.cpp.
References ConstFunction, ConstMember, ConstMethod, ConstUnknown, ConstVariable, clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::Sema::getFunctionLevelDeclContext(), clang::Decl::getLocation(), clang::FunctionDecl::getReturnType(), clang::FunctionDecl::getReturnTypeSourceRange(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreImplicit(), clang::Expr::IgnoreParenImpCasts(), and IsTypeModifiable().
Referenced by CheckForModifiableLvalue(), and DiagnoseRecursiveConstFields().
DiagnoseDirectIsaAccess()
static void DiagnoseDirectIsaAccess (Sema & S, const ObjCIvarRefExpr * OIRE, SourceLocation AssignLoc, const Expr * RHS) static
Definition at line 566 of file SemaExpr.cpp.
References clang::Sema::Context, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Type::getAs(), clang::DeclarationName::getAsIdentifierInfo(), clang::ObjCIvarRefExpr::getBase(), clang::ObjCIvarRefExpr::getBeginLoc(), clang::ObjCIvarRefExpr::getDecl(), clang::NamedDecl::getDeclName(), clang::ObjCIvarRefExpr::getEndLoc(), clang::Stmt::getEndLoc(), clang::Expr::getExprLoc(), clang::Decl::getLocation(), clang::ObjCIvarRefExpr::getLocation(), clang::Sema::getLocForEndOfToken(), clang::ObjCIvarRefExpr::getOpLoc(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ASTContext::Idents, clang::ObjCIvarRefExpr::isArrow(), clang::ObjCInterfaceDecl::ivar_begin(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupSingleName(), clang::Member, and clang::Sema::TUScope.
Referenced by clang::Sema::CreateBuiltinBinOp(), and clang::Sema::DefaultLvalueConversion().
diagnoseDistinctPointerComparison()
static void diagnoseDistinctPointerComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, bool IsError) static
Diagnose bad pointer comparisons.
Definition at line 10964 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getSourceRange(), and clang::Expr::getType().
Referenced by clang::Sema::CheckCompareOperands(), and convertPointersToCompositeType().
DiagnoseDivisionSizeofPointerOrArray()
static void DiagnoseDivisionSizeofPointerOrArray (Sema & S, Expr * LHS, Expr * RHS, SourceLocation Loc) static
Definition at line 10121 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getBaseElementType(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::ASTContext::hasSameUnqualifiedType(), clang::Expr::IgnoreParens(), clang::Type::isCharType(), clang::Type::isDependentType(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by clang::Sema::CheckMultiplyDivideOperands().
diagnoseFunctionPointerToVoidComparison()
static void diagnoseFunctionPointerToVoidComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, bool IsError) static
Definition at line 11004 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getSourceRange(), and clang::Expr::getType().
Referenced by clang::Sema::CheckCompareOperands().
DiagnoseLogicalAndInLogicalOrLHS()
static void DiagnoseLogicalAndInLogicalOrLHS (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Look for '&&' in the left hand of a '||' expr.
Definition at line 14188 of file SemaExpr.cpp.
References EmitDiagnosticForLogicalAndInLogicalOr(), EvaluatesAsFalse(), and EvaluatesAsTrue().
Referenced by DiagnoseBinOpPrecedence().
DiagnoseLogicalAndInLogicalOrRHS()
static void DiagnoseLogicalAndInLogicalOrRHS (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Look for '&&' in the right hand of a '||' expr.
Definition at line 14210 of file SemaExpr.cpp.
References EmitDiagnosticForLogicalAndInLogicalOr(), EvaluatesAsFalse(), and EvaluatesAsTrue().
Referenced by DiagnoseBinOpPrecedence().
diagnoseLogicalNotOnLHSofCheck()
static void diagnoseLogicalNotOnLHSofCheck (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc) static
Warns on !x < y, !x & y where !(x < y), !(x & y) was probably intended.
Definition at line 11165 of file SemaExpr.cpp.
References clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Sema::getLocForEndOfToken(), clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getOperatorLoc(), clang::UnaryOperator::getSubExpr(), clang::Expr::IgnoreImpCasts(), clang::SourceLocation::isInvalid(), and clang::Expr::isKnownToHaveBooleanValue().
Referenced by clang::Sema::CheckBitwiseOperands(), and clang::Sema::CheckCompareOperands().
diagnoseObjCLiteralComparison()
static void diagnoseObjCLiteralComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, BinaryOperator::Opcode Opc) static
Definition at line 11115 of file SemaExpr.cpp.
References clang::Sema::CheckLiteralKind(), clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getASTContext(), clang::Stmt::getBeginLoc(), clang::CharSourceRange::getCharRange(), clang::Stmt::getEndLoc(), clang::Sema::getLocForEndOfToken(), clang::Stmt::getSourceRange(), hasIsEqualMethod(), clang::Expr::IgnoreParenCasts(), clang::BinaryOperator::isEqualityOp(), clang::Expr::isNullPointerConstant(), isObjCObjectLiteral(), clang::Sema::LK_Block, clang::Sema::LK_None, clang::Sema::LK_String, and clang::Expr::NPC_ValueDependentIsNotNull.
Referenced by clang::Sema::CheckCompareOperands().
diagnosePointerIncompatibility()
static void diagnosePointerIncompatibility (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Emit error when two pointers are incompatible.
Definition at line 10489 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Stmt::getSourceRange(), clang::Expr::getType(), and clang::Type::isAnyPointerType().
Referenced by clang::Sema::CheckSubtractionOperands().
DiagnoseRecursiveConstFields() [1/2]
static void DiagnoseRecursiveConstFields (Sema & S, const Expr * E, SourceLocation Loc) static
Emit an error for the case where a record we are trying to assign to has a const-qualified field somewhere in its hierarchy.
Definition at line 12692 of file SemaExpr.cpp.
References DiagnoseConstAssignment(), DiagnoseRecursiveConstFields(), clang::Type::getAs(), clang::QualType::getCanonicalType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isRecordType(), OEK_LValue, OEK_Member, and OEK_Variable.
DiagnoseRecursiveConstFields() [2/2]
static void DiagnoseRecursiveConstFields (Sema & S, const ValueDecl * VD, const RecordType * Ty, SourceLocation Loc, SourceRange Range, OriginalExprKind OEK, bool & DiagnosticEmitted) static
Definition at line 12651 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Type::getAs(), clang::QualType::getCanonicalType(), clang::QualType::isConstQualified(), and NestedConstMember.
Referenced by CheckForModifiableLvalue(), and DiagnoseRecursiveConstFields().
DiagnoseSelfAssignment()
static void DiagnoseSelfAssignment (Sema & S, Expr * LHSExpr, Expr * RHSExpr, SourceLocation OpLoc, bool IsBuiltin) static
DiagnoseSelfAssignment - Emits a warning if a value is assigned to itself.
This warning suppressed in the event of macro expansions.
Definition at line 13666 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::Diag(), clang::Type::getAs(), clang::Decl::getCanonicalDecl(), clang::DeclRefExpr::getDecl(), clang::DeclRefExpr::getLocation(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::inTemplateInstantiation(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), clang::Sema::isUnevaluatedContext(), and clang::QualType::isVolatileQualified().
Referenced by BuildOverloadedBinOp(), and clang::Sema::CreateBuiltinBinOp().
DiagnoseShiftCompare()
static void DiagnoseShiftCompare (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Definition at line 14256 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::Stmt::getEndLoc(), clang::CXXOperatorCallExpr::getOperatorLoc(), clang::FunctionDecl::getOverloadedOperator(), clang::CXXOperatorCallExpr::getSourceRange(), clang::Stmt::getSourceRange(), clang::FunctionDecl::isOverloadedOperator(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by DiagnoseBinOpPrecedence().
diagnoseStringPlusChar()
static void diagnoseStringPlusChar (Sema & Self, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Emit a warning when adding a char literal to a string.
Definition at line 10438 of file SemaExpr.cpp.
References clang::ASTContext::CharTy, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Sema::getASTContext(), clang::Stmt::getBeginLoc(), clang::ASTContext::getCharWidth(), clang::Stmt::getEndLoc(), clang::Sema::getLocForEndOfToken(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::CharacterLiteral::getValue(), clang::Expr::IgnoreImpCasts(), clang::Type::isAnyCharacterType(), clang::Type::isAnyPointerType(), and clang::Type::isIntegerType().
Referenced by clang::Sema::CheckAdditionOperands().
diagnoseStringPlusInt()
static void diagnoseStringPlusInt (Sema & Self, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
diagnoseStringPlusInt - Emit a warning when adding an integer to a string literal.
Definition at line 10408 of file SemaExpr.cpp.
References clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Sema::getLocForEndOfToken(), clang::Expr::getType(), clang::Expr::IgnoreImpCasts(), clang::Type::isIntegralOrUnscopedEnumerationType(), and clang::Expr::isValueDependent().
Referenced by clang::Sema::CheckAdditionOperands().
diagnoseTautologicalComparison()
static void diagnoseTautologicalComparison (Sema & S, SourceLocation Loc, Expr * LHS, Expr * RHS, BinaryOperatorKind Opc) static
Diagnose some forms of syntactically-obvious tautological comparison.
Definition at line 11221 of file SemaExpr.cpp.
References checkForArray(), clang::Sema::Context, clang::Sema::Diag(), clang::Sema::DiagRuntimeBehavior(), clang::Stmt::getBeginLoc(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::hasFloatingRepresentation(), clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenImpCasts(), clang::Sema::inTemplateInstantiation(), clang::Type::isArrayType(), clang::Type::isBlockPointerType(), clang::BinaryOperator::isEqualityOp(), clang::SourceLocation::isMacroID(), clang::Expr::isNullPointerConstant(), clang::Expr::isSameComparisonOperand(), clang::Expr::NPC_ValueDependentIsNull, clang::Sema::PDiag(), and clang::Result.
Referenced by clang::Sema::CheckCompareOperands(), and clang::Sema::CheckVectorCompareOperands().
diagnoseUncapturableValueReference()
static void diagnoseUncapturableValueReference (Sema & S, SourceLocation loc, ValueDecl * var, DeclContext * DC) static
Definition at line 17043 of file SemaExpr.cpp.
References clang::Sema::CurContext, clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::DeclContext::getParent(), clang::isa(), and clang::DeclContext::isFunctionOrMethod().
Referenced by clang::Sema::BuildDeclarationNameExpr(), getParentOfCapturingContextOrNull(), and clang::Sema::tryCaptureVariable().
diagnoseUnknownAnyExpr()
static ExprResult diagnoseUnknownAnyExpr (Sema & S, Expr * E) static
Definition at line 19204 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::ExprError(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), and clang::Expr::IgnoreParenImpCasts().
Referenced by clang::Sema::CheckPlaceholderExpr().
DiagnoseUnusedOfDecl()
static void DiagnoseUnusedOfDecl (Sema & S, NamedDecl * D, SourceLocation Loc) static
Definition at line 88 of file SemaExpr.cpp.
References clang::UnusedAttr::C2x_maybe_unused, clang::UnusedAttr::CXX11_maybe_unused, clang::Sema::Diag(), clang::Decl::getAttr(), clang::Sema::getCurObjCLexicalContext(), and clang::Decl::hasAttr().
Referenced by clang::Sema::DiagnoseUseOfDecl().
diagnoseUseOfInternalDeclInInlineFunction()
static void diagnoseUseOfInternalDeclInInlineFunction (Sema & S, const NamedDecl * D, SourceLocation Loc) static
Check whether we're in an extern inline function and referring to a variable or function with internal linkage (C11 6.7.4p3).
This is only a warning because we used to silently accept this code, but in many cases it will not behave correctly. This is not enabled in C++ mode because the restriction language is a bit weaker (C++11 [basic.def.odr]p6) and so while there may still be user mistakes, most of the time we can't prove that there are errors.
Definition at line 143 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Decl::getCanonicalDecl(), clang::Sema::getCurFunctionDecl(), clang::NamedDecl::getFormalLinkage(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::Sema::getSourceManager(), clang::Decl::hasAttr(), clang::InternalLinkage, clang::FunctionDecl::isInlined(), clang::SourceManager::isInMainFile(), and clang::Sema::MaybeSuggestAddingStaticToDecl().
Referenced by clang::Sema::DiagnoseUseOfDecl().
diagnoseXorMisusedAsPow()
static void diagnoseXorMisusedAsPow (Sema & S, const ExprResult & XorLHS, const ExprResult & XorRHS, const SourceLocation Loc) static
Definition at line 12096 of file SemaExpr.cpp.
References clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CharSourceRange::getCharRange(), clang::Sema::getLangOpts(), clang::Sema::getLocForEndOfToken(), clang::Sema::getPreprocessor(), clang::Sema::getSourceManager(), clang::Lexer::getSourceText(), clang::CharSourceRange::getTokenRange(), clang::Preprocessor::isMacroDefined(), and clang::SourceLocation::isMacroID().
Referenced by clang::Sema::CheckBitwiseOperands().
DoMarkVarDeclReferenced()
static void DoMarkVarDeclReferenced (Sema & SemaRef, SourceLocation Loc, VarDecl * Var, Expr * E) static
Definition at line 18082 of file SemaExpr.cpp.
References clang::sema::LambdaScopeInfo::addPotentialCapture(), clang::sema::LambdaScopeInfo::CallOperator, clang::Sema::checkSpecializationVisibility(), clang::Sema::Context, clang::ASTContext::CUDAStaticDeviceVarReferencedByHost, clang::Sema::CurContext, clang::DeclContext::Encloses(), clang::Sema::getASTContext(), clang::Sema::getCurLambda(), clang::Decl::getDeclContext(), clang::VarDecl::getMemberSpecializationInfo(), clang::VarDecl::getPointOfInstantiation(), clang::MemberSpecializationInfo::getTemplateSpecializationKind(), clang::VarDecl::getTemplateSpecializationKind(), clang::ValueDecl::getType(), hasAttr(), clang::VarDecl::hasLocalStorage(), clang::Expr::IgnoreParens(), clang::Sema::InstantiateVariableDefinition(), clang::DeclContext::isFunctionOrMethod(), clang::SourceLocation::isInvalid(), clang::Decl::isInvalidDecl(), isOdrUseContext(), isPotentiallyConstantEvaluatedContext(), clang::Type::isReferenceType(), clang::isTemplateInstantiation(), clang::VarDecl::isUsableInConstantExpressions(), MarkVarDeclODRUsed(), clang::Sema::MaybeODRUseExprs, clang::ASTContext::mayExternalizeStaticVar(), clang::VarDecl::mightBeUsableInConstantExpressions(), clang::Sema::PendingInstantiations, clang::Sema::runWithSufficientStackSpace(), clang::Decl::setReferenced(), clang::VarDecl::setTemplateSpecializationKind(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ImplicitInstantiation, and clang::TSK_Undeclared.
Referenced by MarkExprReferenced(), and clang::Sema::MarkVariableReferenced().
EmitDiagnosticForLogicalAndInLogicalOr()
static void EmitDiagnosticForLogicalAndInLogicalOr (Sema & Self, SourceLocation OpLoc, BinaryOperator * Bop) static
It accepts a '&&' expr that is inside a '||' one.
Emit a diagnostic together with a fixit hint that wraps the '&&' expression in parentheses.
Definition at line 14160 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getOperatorLoc(), clang::Stmt::getSourceRange(), clang::Sema::PDiag(), and SuggestParentheses().
Referenced by DiagnoseLogicalAndInLogicalOrLHS(), and DiagnoseLogicalAndInLogicalOrRHS().
emitEmptyLookupTypoDiagnostic()
static void emitEmptyLookupTypoDiagnostic (const TypoCorrection & TC, Sema & SemaRef, const CXXScopeSpec & SS, DeclarationName Typo, SourceLocation TypoLoc, ArrayRef< Expr * > Args, unsigned DiagnosticID, unsigned DiagnosticSuggestID) static
Definition at line 2104 of file SemaExpr.cpp.
References clang::Sema::computeDeclContext(), clang::Sema::Diag(), clang::Sema::diagnoseTypo(), clang::TypoCorrection::getAsString(), clang::TypoCorrection::getCorrectionDeclAs(), clang::Sema::getLangOpts(), clang::CXXScopeSpec::getRange(), clang::CXXScopeSpec::isEmpty(), clang::Sema::PDiag(), and clang::TypoCorrection::WillReplaceSpecifier().
enclosingClassIsRelatedToClassInWhichMembersWereFound()
static bool enclosingClassIsRelatedToClassInWhichMembersWereFound (const UnresolvedMemberExpr *const UME, Sema & S) static
Definition at line 6230 of file SemaExpr.cpp.
References clang::CXXRecordDecl::getCanonicalDecl(), clang::Sema::getFunctionLevelDeclContext(), clang::UnresolvedMemberExpr::getNamingClass(), clang::DeclContext::getParent(), and clang::CXXRecordDecl::isDerivedFrom().
Referenced by tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs().
EvaluateAndDiagnoseImmediateInvocation()
static void EvaluateAndDiagnoseImmediateInvocation (Sema & SemaRef, Sema::ImmediateInvocationCandidate Candidate) static
Definition at line 16362 of file SemaExpr.cpp.
References clang::cast(), clang::Expr::EvalStatus::Diag, clang::Sema::Diag(), clang::Expr::EvaluateAsConstantExpr(), clang::FunctionalCast, clang::Sema::getASTContext(), clang::ConstantExpr::getBeginLoc(), clang::FullExpr::getSubExpr(), clang::Expr::IgnoreImplicit(), clang::FunctionDecl::isConsteval(), clang::ConstantExpr::MoveIntoResult(), clang::Note, clang::Result, and clang::Expr::EvalResult::Val.
Referenced by HandleImmediateInvocations().
EvaluatesAsFalse()
static bool EvaluatesAsFalse (Sema & S, Expr * E) static
Returns true if the given expression can be evaluated as a constant 'false'.
Definition at line 14181 of file SemaExpr.cpp.
References clang::Expr::EvaluateAsBooleanCondition(), clang::Sema::getASTContext(), and clang::Expr::isValueDependent().
Referenced by DiagnoseLogicalAndInLogicalOrLHS(), and DiagnoseLogicalAndInLogicalOrRHS().
EvaluatesAsTrue()
static bool EvaluatesAsTrue (Sema & S, Expr * E) static
Returns true if the given expression can be evaluated as a constant 'true'.
Definition at line 14173 of file SemaExpr.cpp.
References clang::Expr::EvaluateAsBooleanCondition(), clang::Sema::getASTContext(), and clang::Expr::isValueDependent().
Referenced by DiagnoseLogicalAndInLogicalOrLHS(), and DiagnoseLogicalAndInLogicalOrRHS().
ExprLooksBoolean()
static bool ExprLooksBoolean (Expr * E) static
ExprLooksBoolean - Returns true if E looks boolean, i.e.
it has boolean type or is a logical expression such as (x==y) which has int type, but is commonly interpreted as boolean.
Definition at line 8505 of file SemaExpr.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isBooleanType(), and clang::Type::isPointerType().
Referenced by DiagnoseConditionalPrecedence().
funcHasParameterSizeMangling()
static bool funcHasParameterSizeMangling (Sema & S, FunctionDecl * FD) static
Return true if this function has a calling convention that requires mangling in the size of the parameter pack.
Definition at line 16632 of file SemaExpr.cpp.
References clang::Type::castAs(), clang::CC_X86FastCall, clang::CC_X86StdCall, clang::CC_X86VectorCall, clang::Sema::Context, clang::Sema::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ValueDecl::getType(), and clang::FunctionDecl::isExternC().
Referenced by clang::Sema::MarkFunctionReferenced().
getDeclFromExpr()
static NamedDecl * getDeclFromExpr (Expr * E) static
Definition at line 13743 of file SemaExpr.cpp.
Referenced by CorrectDelayedTyposInBinOp().
GetFixedPointRank()
static unsigned GetFixedPointRank (QualType Ty) static
Return the rank of a given fixed point or integer type.
The value itself doesn't matter, but the values must be increasing with proper increasing rank as described in N1169 4.1.1.
Definition at line 1343 of file SemaExpr.cpp.
References clang::Type::getAs().
Referenced by handleFixedPointConversion().
getParentOfCapturingContextOrNull()
static DeclContext * getParentOfCapturingContextOrNull (DeclContext * DC, VarDecl * Var, SourceLocation Loc, const bool Diagnose, Sema & S) static
Definition at line 17116 of file SemaExpr.cpp.
References clang::Sema::Diagnose, diagnoseUncapturableValueReference(), clang::getLambdaAwareParentOfDeclContext(), clang::VarDecl::hasLocalStorage(), and clang::isLambdaCallOperator().
Referenced by clang::Sema::tryCaptureVariable().
getPrimaryDecl()
static ValueDecl * getPrimaryDecl (Expr * E) static
getPrimaryDecl - Helper function for CheckAddressOfOperand().
This routine allows us to typecheck complex/recursive expressions where the declaration is needed for type checking. We only need to handle cases when the expression references a function designator or is an lvalue. Here are some examples:
&(x) => x
&*****f => f for f a function designator.
&s.xx => s
&s.zz[1].yy -> s, if zz is an array
*(x + 1) -> x, if x is an array
&"123"[2] -> 0
& real x -> x
FIXME: We don't recurse to the RHS of a comma, nor handle pointers to members.
Definition at line 13232 of file SemaExpr.cpp.
References clang::cast(), clang::UnaryOperator::getOpcode(), getPrimaryDecl(), clang::Stmt::getStmtClass(), and clang::UnaryOperator::getSubExpr().
Referenced by clang::Sema::CheckAddressOfOperand(), and getPrimaryDecl().
getUDSuffixLoc()
static SourceLocation getUDSuffixLoc (Sema & S, SourceLocation TokLoc, unsigned Offset) static
getUDSuffixLoc - Create a SourceLocation for a ud-suffix, given the location of the token and the offset of the ud-suffix within it.
Definition at line 1749 of file SemaExpr.cpp.
References clang::Lexer::AdvanceToTokenCharacter(), clang::Sema::getLangOpts(), clang::Sema::getSourceManager(), and Offset.
Referenced by clang::Sema::ActOnCharacterConstant(), clang::Sema::ActOnNumericConstant(), and clang::Sema::ActOnStringLiteral().
handleComplexFloatConversion()
static QualType handleComplexFloatConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle arithmetic conversion with complex types.
Helper function of UsualArithmeticConversions()
Definition at line 1054 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getComplexType(), clang::ASTContext::getFloatingTypeOrder(), handleIntegerToComplexFloatConversion(), and clang::Sema::ImpCastExprToType().
Referenced by clang::Sema::UsualArithmeticConversions().
handleComplexIntConversion()
static QualType handleComplexIntConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle conversions with GCC complex int extension.
Helper function of UsualArithmeticConversions()
Definition at line 1297 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAsComplexIntegerType(), clang::ASTContext::getComplexType(), clang::ComplexType::getElementType(), handleIntegerConversion(), and clang::Sema::ImpCastExprToType().
Referenced by clang::Sema::UsualArithmeticConversions().
handleFixedPointConversion()
static QualType handleFixedPointConversion (Sema & S, QualType LHSTy, QualType RHSTy) static
handleFixedPointConversion - Fixed point operations between fixed point types and integers or other fixed point types do not fall under usual arithmetic conversion since these conversions could result in loss of precsision (N1169 4.1.4).
These operations should be calculated with the full precision of their result type (N1169 4.1.6.2.1).
Definition at line 1390 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ASTContext::getCorrespondingSaturatedType(), clang::ASTContext::getCorrespondingSignedFixedPointType(), GetFixedPointRank(), clang::Type::isFixedPointOrIntegerType(), clang::Type::isFixedPointType(), clang::Type::isSaturatedFixedPointType(), clang::Type::isSignedFixedPointType(), and clang::Type::isUnsignedFixedPointType().
Referenced by clang::Sema::UsualArithmeticConversions().
handleFloatConversion()
static QualType handleFloatConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle arithmethic conversion with floating point types.
Helper function of UsualArithmeticConversions()
Definition at line 1141 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ASTContext::FloatTy, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getFloatingTypeOrder(), clang::Sema::getLangOpts(), handleIntToFloatConversion(), clang::Sema::ImpCastExprToType(), clang::Type::isFixedPointType(), clang::Type::isHalfType(), and clang::Type::isRealFloatingType().
Referenced by OpenCLArithmeticConversions(), and clang::Sema::UsualArithmeticConversions().
HandleImmediateInvocations()
static void HandleImmediateInvocations (Sema & SemaRef, Sema::ExpressionEvaluationContextRecord & Rec) static
When we have more then 1 ImmediateInvocationCandidates we need to check for nested ImmediateInvocationCandidates. when we have only 1 we only need to remove ReferenceToConsteval in the immediate invocation.
Prevent sema calls during the tree transform from adding pointers that are already in the sets.
Prevent diagnostic during tree transfrom as they are duplicates
Definition at line 16469 of file SemaExpr.cpp.
References clang::cast(), clang::Sema::Diag(), EvaluateAndDiagnoseImmediateInvocation(), clang::Sema::ExpressionEvaluationContextRecord::ImmediateInvocationCandidates, clang::Sema::RebuildingImmediateInvocation, clang::Sema::ExpressionEvaluationContextRecord::ReferenceToConsteval, and RemoveNestedImmediateInvocation().
Referenced by clang::Sema::PopExpressionEvaluationContext().
handleIntegerConversion()
template<PerformCastFn doLHSCast, PerformCastFn doRHSCast> static QualType handleIntegerConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle integer arithmetic conversions.
Helper function of UsualArithmeticConversions()
Definition at line 1247 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getCorrespondingUnsignedType(), clang::ASTContext::getIntegerTypeOrder(), clang::ASTContext::getIntWidth(), and clang::Type::hasSignedIntegerRepresentation().
Referenced by handleComplexIntConversion(), OpenCLArithmeticConversions(), and clang::Sema::UsualArithmeticConversions().
handleIntegerToComplexFloatConversion()
static bool handleIntegerToComplexFloatConversion (Sema & S, ExprResult & IntExpr, ExprResult & ComplexExpr, QualType IntTy, QualType ComplexTy, bool SkipCast) static
Converts an integer to complex float type.
Helper function of UsualArithmeticConversions()
Returns
false if the integer expression is an integer type and is successfully converted to the complex type.
Definition at line 1032 of file SemaExpr.cpp.
References clang::cast(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::ImpCastExprToType(), clang::Type::isComplexIntegerType(), clang::Type::isComplexType(), clang::Type::isIntegerType(), and clang::Type::isRealFloatingType().
Referenced by handleComplexFloatConversion().
handleIntToFloatConversion()
static QualType handleIntToFloatConversion (Sema & S, ExprResult & FloatExpr, ExprResult & IntExpr, QualType FloatTy, QualType IntTy, bool ConvertFloat, bool ConvertInt) static
Handle arithmetic conversion from integer to float.
Helper function of UsualArithmeticConversions()
Definition at line 1110 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getComplexType(), clang::Sema::ImpCastExprToType(), clang::Type::isComplexIntegerType(), and clang::Type::isIntegerType().
Referenced by handleFloatConversion().
hasAnyExplicitStorageClass()
static bool hasAnyExplicitStorageClass (const FunctionDecl * D) static
Determine whether a FunctionDecl was ever declared with an explicit storage class.
Definition at line 127 of file SemaExpr.cpp.
References clang::Redeclarable< decl_type >::redecls(), and clang::SC_None.
Referenced by clang::Sema::MaybeSuggestAddingStaticToDecl().
hasIsEqualMethod()
static bool hasIsEqualMethod (Sema & S, const Expr * LHS, const Expr * RHS) static
Definition at line 11027 of file SemaExpr.cpp.
References clang::Type::getAs(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::Type::isObjCIdType(), clang::Type::isObjCObjectPointerType(), clang::Type::isScalarType(), clang::Sema::LookupInstanceMethodInGlobalPool(), clang::Sema::LookupMethodInObjectType(), clang::Sema::LookupMethodInQualifiedType(), and clang::Sema::NSAPIObj.
Referenced by diagnoseObjCLiteralComparison().
IgnoreCommaOperand()
static bool IgnoreCommaOperand (const Expr * E) static
Definition at line 13021 of file SemaExpr.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParens(), and clang::Type::isVoidType().
Referenced by clang::Sema::DiagnoseCommaOperator().
IsArithmeticBinaryExpr()
static bool IsArithmeticBinaryExpr (Expr * E, BinaryOperatorKind * Opcode, Expr ** RHSExprs) static
IsArithmeticBinaryExpr - Returns true if E is an arithmetic binary expression, either using a built-in or overloaded operator, and sets *OpCode to the opcode and *RHSExprs to the right-hand side expression.
Definition at line 8459 of file SemaExpr.cpp.
References clang::BinaryOperator::getOverloadedOpcode(), clang::Expr::IgnoreConversionOperatorSingleStep(), clang::Expr::IgnoreImpCasts(), and IsArithmeticOp().
Referenced by DiagnoseConditionalPrecedence().
IsArithmeticOp()
static bool IsArithmeticOp (BinaryOperatorKind Opc) static
Definition at line 8444 of file SemaExpr.cpp.
References clang::BinaryOperator::isAdditiveOp(), clang::BinaryOperator::isMultiplicativeOp(), and clang::BinaryOperator::isShiftOp().
Referenced by IsArithmeticBinaryExpr().
isCapturingReferenceToHostVarInCUDADeviceLambda()
static bool isCapturingReferenceToHostVarInCUDADeviceLambda (const Sema & S, VarDecl * VD) static
Definition at line 1957 of file SemaExpr.cpp.
References clang::Sema::CurContext, clang::Decl::getDeclContext(), clang::VarDecl::getInit(), clang::Sema::getLangOpts(), clang::ValueDecl::getType(), clang::VarDecl::hasInit(), and clang::Type::isReferenceType().
Referenced by clang::Sema::getNonOdrUseReasonInCurrentContext().
isImplicitlyDefinableConstexprFunction()
static bool isImplicitlyDefinableConstexprFunction (FunctionDecl * Func) static
Definition at line 16751 of file SemaExpr.cpp.
References clang::FunctionDecl::isConstexpr(), clang::FunctionDecl::isImplicitlyInstantiable(), and clang::FunctionDecl::isUserProvided().
Referenced by clang::Sema::MarkFunctionReferenced().
IsInvalidCmseNSCallConversion()
static bool IsInvalidCmseNSCallConversion (Sema & S, QualType FromType, QualType ToType) static
Definition at line 8722 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ASTContext::getCanonicalType(), and clang::FunctionType::ExtInfo::getCmseNSCall().
Referenced by checkPointerTypesForAssignment().
isMSPropertySubscriptExpr()
static bool isMSPropertySubscriptExpr (Sema & S, Expr * Base) static
Definition at line 4590 of file SemaExpr.cpp.
References clang::isa().
Referenced by clang::Sema::ActOnArraySubscriptExpr().
isObjCObjectLiteral()
static bool isObjCObjectLiteral (ExprResult & E) static
Definition at line 11014 of file SemaExpr.cpp.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Stmt::getStmtClass(), and clang::Expr::IgnoreParenImpCasts().
Referenced by clang::Sema::CheckCompareOperands(), and diagnoseObjCLiteralComparison().
isOdrUseContext()
static OdrUseContext isOdrUseContext (Sema & SemaRef) static
Are we within a context in which references to resolved functions or to variables result in odr-use?
Definition at line 16720 of file SemaExpr.cpp.
References clang::Sema::ConstantEvaluated, clang::Sema::CurContext, clang::Sema::DiscardedStatement, clang::Sema::ExprEvalContexts, clang::DeclContext::isDependentContext(), clang::Sema::PotentiallyEvaluated, clang::Sema::PotentiallyEvaluatedIfUsed, clang::Result, clang::Sema::Unevaluated, clang::Sema::UnevaluatedAbstract, and clang::Sema::UnevaluatedList.
Referenced by DoMarkVarDeclReferenced(), and clang::Sema::MarkFunctionReferenced().
isOverflowingIntegerType()
static bool isOverflowingIntegerType (ASTContext & Ctx, QualType T) static
Definition at line 14520 of file SemaExpr.cpp.
References clang::ASTContext::getIntWidth(), and clang::ASTContext::IntTy.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
isPlaceholderToRemoveAsArg()
static bool isPlaceholderToRemoveAsArg (QualType type) static
Is the given type a placeholder that we need to lower out immediately during argument processing?
Definition at line 6043 of file SemaExpr.cpp.
References clang::BuiltinType::getKind().
Referenced by checkArgsForPlaceholders().
isPotentiallyConstantEvaluatedContext()
static bool isPotentiallyConstantEvaluatedContext (Sema & SemaRef) static
Are we in a context that is potentially constant evaluated per C++20 [expr.const]p12?
C++2a [expr.const]p12:
Definition at line 16603 of file SemaExpr.cpp.
References clang::Sema::ConstantEvaluated, clang::Sema::DiscardedStatement, clang::Sema::ExprEvalContexts, clang::Sema::PotentiallyEvaluated, clang::Sema::PotentiallyEvaluatedIfUsed, clang::Sema::Unevaluated, clang::Sema::UnevaluatedAbstract, and clang::Sema::UnevaluatedList.
Referenced by DoMarkVarDeclReferenced(), and clang::Sema::MarkFunctionReferenced().
IsReadonlyMessage()
static bool IsReadonlyMessage (Expr * E, Sema & S) static
Definition at line 12454 of file SemaExpr.cpp.
References clang::MemberExpr::getBase(), clang::MemberExpr::getMemberDecl(), clang::Expr::IgnoreImplicit(), and clang::Expr::IgnoreParenImpCasts().
Referenced by CheckForModifiableLvalue().
isReferenceToNonConstCapture()
static NonConstCaptureKind isReferenceToNonConstCapture (Sema & S, Expr * E) static
Definition at line 12468 of file SemaExpr.cpp.
References clang::Sema::CurContext, clang::DeclRefExpr::getDecl(), clang::Decl::getDeclContext(), clang::DeclContext::getParent(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::VarDecl::hasLocalStorage(), clang::Expr::IgnoreParens(), clang::QualType::isConstQualified(), clang::VarDecl::isInitCapture(), clang::Expr::isLValue(), NCCK_Block, NCCK_Lambda, NCCK_None, and clang::DeclRefExpr::refersToEnclosingVariableOrCapture().
Referenced by CheckForModifiableLvalue().
isScopedEnumerationType()
static bool isScopedEnumerationType (QualType T) static
Definition at line 10715 of file SemaExpr.cpp.
References clang::Type::getAs().
Referenced by clang::Sema::CheckShiftOperands(), and clang::Sema::CreateBuiltinUnaryOp().
IsTypeModifiable()
static bool IsTypeModifiable (QualType Ty, bool IsDereference) static
Definition at line 12504 of file SemaExpr.cpp.
References clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::QualType::isConstQualified(), and clang::Type::isPointerType().
Referenced by DiagnoseConstAssignment().
isVariableAlreadyCapturedInScopeInfo()
static bool isVariableAlreadyCapturedInScopeInfo (CapturingScopeInfo * CSI, VarDecl * Var, bool & SubCapturesAreNested, QualType & CaptureType, QualType & DeclRefType) static
Definition at line 17085 of file SemaExpr.cpp.
References clang::QualType::addConst(), clang::sema::CapturingScopeInfo::CaptureMap, clang::CR_OpenMP, clang::sema::CapturingScopeInfo::getCapture(), clang::sema::Capture::getCaptureType(), clang::QualType::getNonReferenceType(), and clang::sema::Capture::isCopyCapture().
Referenced by clang::Sema::tryCaptureVariable().
isVariableCapturable()
static bool isVariableCapturable (CapturingScopeInfo * CSI, VarDecl * Var, SourceLocation Loc, const bool Diagnose, Sema & S) static
Definition at line 17131 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::Sema::Diagnose, clang::Type::getAs(), clang::NamedDecl::getDeclName(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::isa(), clang::Type::isBlockPointerType(), and clang::Type::isVariablyModifiedType().
Referenced by clang::Sema::tryCaptureVariable().
isVector()
static bool isVector (QualType QT, QualType ElementType) static
This helper function returns true if QT is a vector type that has element type ElementType.
Definition at line 8985 of file SemaExpr.cpp.
References clang::Type::getAs().
Referenced by convertHalfVecBinOp(), and clang::Sema::CreateBuiltinBinOp().
MarkExprReferenced()
static void MarkExprReferenced (Sema & SemaRef, SourceLocation Loc, Decl * D, Expr * E, bool MightBeOdrUse) static
Definition at line 18276 of file SemaExpr.cpp.
References clang::Sema::checkDeclIsAllowedInOpenMPTarget(), DoMarkVarDeclReferenced(), clang::MemberExpr::getBase(), clang::CXXMethodDecl::getDevirtualizedMethod(), clang::Sema::getLangOpts(), clang::MemberExpr::getMemberDecl(), clang::Sema::isInOpenMPDeclareTargetContext(), clang::CXXMethodDecl::isVirtual(), clang::Sema::MarkAnyDeclReferenced(), and clang::MemberExpr::performsVirtualDispatch().
Referenced by clang::Sema::MarkDeclRefReferenced(), clang::Sema::MarkFunctionParmPackReferenced(), and clang::Sema::MarkMemberReferenced().
MarkVarDeclODRUsed()
static void MarkVarDeclODRUsed (VarDecl * Var, SourceLocation Loc, Sema & SemaRef, const unsigned *const FunctionScopeIndexToStopAt = nullptr) static
Directly mark a variable odr-used.
Given a choice, prefer to use MarkVariableReferenced since it does additional checks and then calls MarkVarDeclODRUsed. If the variable must be captured:
if FunctionScopeIndexToStopAt is null, capture it in the CurContext
else capture it in the DeclContext that maps to the *FunctionScopeIndexToStopAt on the FunctionScopeInfo stack.
Definition at line 17012 of file SemaExpr.cpp.
References clang::Sema::Context, clang::VarDecl::DeclarationOnly, clang::VarDecl::getCanonicalDecl(), clang::VarDecl::hasDefinition(), clang::VarDecl::hasInit(), clang::NamedDecl::isExternallyVisible(), clang::Sema::isExternalWithNoLinkageType(), clang::VarDecl::isInline(), clang::SourceLocation::isInvalid(), clang::VarDecl::isStaticDataMember(), clang::Sema::LangOpts, clang::Decl::markUsed(), clang::Sema::TryCapture_Implicit, clang::Sema::tryCaptureOpenMPLambdas(), clang::Sema::tryCaptureVariable(), and clang::Sema::UndefinedButUsed.
Referenced by clang::Sema::CleanupVarDeclMarking(), DoMarkVarDeclReferenced(), and clang::Sema::MarkCaptureUsedInEnclosingContext().
maybeDiagnoseAssignmentToFunction()
static bool maybeDiagnoseAssignmentToFunction (Sema & S, QualType DstType, const Expr * SrcExpr) static
Definition at line 15711 of file SemaExpr.cpp.
References clang::Sema::checkAddressOfFunctionIsAvailable(), clang::Stmt::getBeginLoc(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isFunctionPointerType(), and clang::Type::isFunctionType().
Referenced by clang::Sema::DiagnoseAssignmentResult().
needsConversionOfHalfVec()
static bool needsConversionOfHalfVec (bool OpRequiresConversion, ASTContext & Ctx, Expr * E0, Expr * E1 = nullptr) static
Returns true if conversion between vectors of halfs and vectors of floats is needed.
Definition at line 13814 of file SemaExpr.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::Expr::getType(), clang::ASTContext::HalfTy, clang::Expr::IgnoreImplicit(), clang::VectorType::NeonVector, and clang::TargetInfo::useFP16ConversionIntrinsics().
Referenced by clang::Sema::CreateBuiltinBinOp(), and clang::Sema::CreateBuiltinUnaryOp().
OpenCLArithmeticConversions()
static QualType OpenCLArithmeticConversions (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation QuestionLoc) static
Simple conversion between integer and floating point types.
Used when handling the OpenCL conditional operator where the condition is a vector while the other operands are scalar.
OpenCL v1.1 s6.3.i and s6.11.6 together require that the scalar types are either integer or floating type. Between the two operands, the type with the higher rank is defined as the "result type". The other operand needs to be promoted to the same type. No other type promotion is allowed. We cannot use UsualArithmeticConversions() for this purpose, since it always promotes promotable types.
Definition at line 7937 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getCanonicalType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::CanQual< typename >::getUnqualifiedType(), handleFloatConversion(), handleIntegerConversion(), clang::Type::isIntegerType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), and clang::Type::isRealFloatingType().
Referenced by OpenCLConvertScalarsToVectors().
OpenCLCheckVectorConditional()
static QualType OpenCLCheckVectorConditional (Sema & S, ExprResult & Cond, ExprResult & LHS, ExprResult & RHS, SourceLocation QuestionLoc) static
Return the resulting type for the conditional operator in OpenCL (aka "ternary selection operator", OpenCL v1.1 s6.3.i) when the condition is a vector type.
Definition at line 8074 of file SemaExpr.cpp.
References checkOpenCLConditionVector(), clang::Sema::CheckVectorOperands(), checkVectorResult(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Expr::getType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::QualType::isNull(), clang::Type::isVectorType(), and OpenCLConvertScalarsToVectors().
Referenced by clang::Sema::CheckConditionalOperands().
OpenCLConvertScalarsToVectors()
static QualType OpenCLConvertScalarsToVectors (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType CondTy, SourceLocation QuestionLoc) static
Convert scalar operands to a vector that matches the condition in length.
Used when handling the OpenCL conditional operator where the condition is a vector while the other operands are scalar.
We first compute the "result type" for the scalar operands according to OpenCL v1.1 s6.3.i. Both operands are then converted into a vector of that type where the length matches the condition vector type. s6.11.6 requires that the element types of the result and the condition must have the same number of bits.
Definition at line 7992 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::QualType::getAsString(), clang::VectorType::getElementType(), clang::ASTContext::getExtVectorType(), clang::VectorType::getNumElements(), clang::ASTContext::getTypeSize(), clang::QualType::getUnqualifiedType(), clang::Sema::ImpCastExprToType(), clang::QualType::isNull(), and OpenCLArithmeticConversions().
Referenced by OpenCLCheckVectorConditional().
rebuildPotentialResultsAsNonOdrUsed()
static ExprResult rebuildPotentialResultsAsNonOdrUsed (Sema & S, Expr * E, NonOdrUseReason NOUR) static
Walk the set of potential results of an expression and mark them all as non-odr-uses if they satisfy the side-conditions of the NonOdrUseReason.
Returns
A new expression if we found any potential results, ExprEmpty() if not, and ExprError() if we diagnosed an error.
Definition at line 17703 of file SemaExpr.cpp.
References clang::Sema::ActOnArraySubscriptExpr(), clang::Sema::ActOnChooseExpr(), clang::Sema::ActOnConditionalOp(), clang::Sema::ActOnParenExpr(), clang::Sema::BuildBinOp(), clang::Sema::BuildUnaryOp(), clang::cast(), clang::Sema::Context, clang::ConstantExpr::Create(), clang::DeclRefExpr::Create(), clang::MemberExpr::Create(), clang::Sema::CreateGenericSelectionExpr(), clang::ExprEmpty(), clang::ExprError(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Sema::getCurLambda(), clang::Stmt::getStmtClass(), clang::Expr::getType(), clang::Expr::IgnoreImplicit(), clang::Sema::ImpCastExprToType(), clang::Type::isArrayType(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::Sema::MaybeODRUseExprs, clang::NOUR_Constant, clang::NOUR_Discarded, clang::NOUR_None, clang::NOUR_Unevaluated, and rebuildPotentialResultsAsNonOdrUsed().
Referenced by clang::Sema::CheckLValueToRValueConversionOperand(), and rebuildPotentialResultsAsNonOdrUsed().
rebuildUnknownAnyFunction()
static ExprResult rebuildUnknownAnyFunction (Sema & S, Expr * fn) static
Given a function expression of unknown-any type, try to rebuild it to have a function type.
Definition at line 18803 of file SemaExpr.cpp.
References clang::Sema::DefaultFunctionArrayConversion(), clang::ExprError(), and clang::Result.
Referenced by clang::Sema::BuildCallExpr(), and clang::Sema::BuildResolvedCallExpr().
RecordModifiableNonNullParam()
static void RecordModifiableNonNullParam (Sema & S, const Expr * Exp) static
Definition at line 13523 of file SemaExpr.cpp.
References clang::Sema::getCurFunction(), and clang::DeclRefExpr::getDecl().
Referenced by clang::Sema::CreateBuiltinBinOp(), and clang::Sema::CreateBuiltinUnaryOp().
recoverFromMSUnqualifiedLookup()
static Expr * recoverFromMSUnqualifiedLookup (Sema & S, ASTContext & Context, DeclarationNameInfo & NameInfo, SourceLocation TemplateKWLoc, const TemplateArgumentListInfo * TemplateArgs) static
In Microsoft mode, if we are inside a template class whose parent class has dependent base classes, and we can't resolve an unqualified identifier, then assume the identifier is a member of a dependent base class.
We can only recover successfully in static methods, instance methods, and other contexts where 'this' is available. This doesn't precisely match MSVC's instantiation model, but it's close enough.
Definition at line 2380 of file SemaExpr.cpp.
References clang::CXXDependentScopeMemberExpr::Create(), clang::DependentScopeDeclRefExpr::Create(), clang::NestedNameSpecifier::Create(), clang::FixItHint::CreateInsertion(), clang::Sema::CurContext, clang::Sema::Diag(), clang::Type::getAsCXXRecordDecl(), clang::Sema::getCurrentThisType(), clang::DeclarationNameInfo::getLoc(), clang::DeclarationNameInfo::getName(), clang::DeclContext::getParent(), clang::Type::getPointeeType(), clang::TypeDecl::getTypeForDecl(), clang::CXXScopeSpec::getWithLocInContext(), clang::CXXRecordDecl::hasAnyDependentBases(), clang::QualType::isNull(), and clang::CXXScopeSpec::MakeTrivial().
Referenced by clang::Sema::ActOnIdExpression().
RemoveNestedImmediateInvocation()
static void RemoveNestedImmediateInvocation (Sema & SemaRef, Sema::ExpressionEvaluationContextRecord & Rec, SmallVector< Sema::ImmediateInvocationCandidate, 4 >::reverse_iterator It) static
Base::TransfromCXXOperatorCallExpr doesn't traverse the callee so we need to remove its DeclRefExpr from the DRSet.
Base::TransformInitializer skip ConstantExpr so we need to visit them here.
ConstantExpr are the first layer of implicit node to be removed so if Init isn't a ConstantExpr, no ConstantExpr will be skipped.
CXXConstructExpr with a single argument are getting skipped by TreeTransform in some situtation because they could be implicit. This can only occur for the top-level CXXConstructExpr because it is used nowhere in the expression being transformed therefore will not be rebuilt. Setting AllowSkippingFirstCXXConstructExpr to false will prevent from skipping the first CXXConstructExpr.
Definition at line 16390 of file SemaExpr.cpp.
References clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::CallExpr::getCallee(), clang::FullExpr::getSubExpr(), clang::Expr::IgnoreImplicit(), clang::Sema::ExpressionEvaluationContextRecord::ImmediateInvocationCandidates, clang::ConstantExpr::isImmediateInvocation(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::Sema::MaybeCreateExprWithCleanups(), and clang::Sema::ExpressionEvaluationContextRecord::ReferenceToConsteval.
Referenced by HandleImmediateInvocations().
rewriteBuiltinFunctionDecl()
static FunctionDecl * rewriteBuiltinFunctionDecl (Sema * Sema, ASTContext & Context, FunctionDecl * FDecl, MultiExprArg ArgExprs) static
If a builtin function has a pointer argument with no explicit address space, then it should be able to accept a pointer to any address space as input.
In order to do this, we need to replace the standard builtin declaration with one that uses the same address space as the call.
Returns
nullptr If this builtin is not a candidate for a rewrite i.e. it does not contain any pointer arguments without an address space qualifer. Otherwise the rewritten FunctionDecl is returned. TODO: Handle pointer return types.
Definition at line 6128 of file SemaExpr.cpp.
References clang::ASTContext::BuiltinInfo, clang::cast(), clang::FunctionDecl::Create(), clang::ParmVarDecl::Create(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getAddrSpaceQualType(), clang::FunctionDecl::getBuiltinID(), clang::ASTContext::getFunctionType(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::getParamType(), clang::DeclContext::getParent(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::FunctionType::getReturnType(), clang::Expr::getType(), clang::ValueDecl::getType(), clang::QualType::hasAddressSpace(), clang::Builtin::Context::hasPtrArgsOrResult(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::FunctionProtoType::isVariadic(), clang::Sema::mergeDeclAttributes(), clang::FunctionProtoType::param_types(), Parent, clang::SC_Extern, clang::SC_None, clang::ParmVarDecl::setScopeInfo(), and clang::FunctionProtoType::ExtProtoInfo::Variadic.
Referenced by clang::Sema::BuildCallExpr().
ShouldLookupResultBeMultiVersionOverload()
static bool ShouldLookupResultBeMultiVersionOverload (const LookupResult & R) static
Definition at line 3148 of file SemaExpr.cpp.
References clang::LookupResult::getFoundDecl(), and clang::LookupResult::isSingleResult().
Referenced by clang::Sema::BuildDeclarationNameExpr().
SuggestParentheses()
static void SuggestParentheses (Sema & Self, SourceLocation Loc, const PartialDiagnostic & Note, SourceRange ParenRange) static
SuggestParentheses - Emit a note with a fixit hint that wraps ParenRange in parentheses.
Definition at line 8429 of file SemaExpr.cpp.
References clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::Sema::getLocForEndOfToken(), clang::SourceLocation::isFileID(), clang::SourceLocation::isValid(), and clang::Note.
Referenced by DiagnoseAdditionInShift(), DiagnoseBitwiseOpInBitwiseOp(), DiagnoseBitwisePrecedence(), DiagnoseConditionalPrecedence(), DiagnoseShiftCompare(), and EmitDiagnosticForLogicalAndInLogicalOr().
tryGCCVectorConvertAndSplat()
static bool tryGCCVectorConvertAndSplat (Sema & S, ExprResult * Scalar, ExprResult * Vector) static
Attempt to convert and splat Scalar into a vector whose types matches Vector following GCC conversion rules.
The rule is that implicit conversion can occur when Scalar can be casted to match Vector's element type without causing truncation of Scalar.
Definition at line 9784 of file SemaExpr.cpp.
References canConvertIntToOtherIntTy(), canConvertIntTyToFloatTy(), clang::Sema::Context, clang::Expr::EvaluateAsFloat(), clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::Type::getAs(), clang::VectorType::getElementType(), clang::ASTContext::getFloatingTypeOrder(), clang::ASTContext::getFloatTypeSemantics(), clang::ASTContext::getIntegerTypeOrder(), clang::Expr::getType(), clang::ASTContext::getTypeSize(), clang::QualType::getUnqualifiedType(), clang::Sema::ImpCastExprToType(), clang::Type::isArithmeticType(), clang::Type::isEnumeralType(), clang::Type::isIntegralType(), clang::Type::isRealFloatingType(), clang::Expr::isValueDependent(), and clang::Result.
Referenced by clang::Sema::CheckVectorOperands().
tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs()
static void tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs (Sema & S, const UnresolvedMemberExpr *const UME, SourceLocation CallLoc) static
Definition at line 6272 of file SemaExpr.cpp.
References clang::sema::LambdaScopeInfo::addPotentialThisCapture(), clang::Sema::CheckCXXThisCapture(), clang::Sema::CurContext, enclosingClassIsRelatedToClassInWhichMembersWereFound(), clang::Sema::getCurLambda(), clang::DeclContext::getParent(), clang::sema::CapturingScopeInfo::ImpCap_None, clang::sema::CapturingScopeInfo::ImpCaptureStyle, clang::sema::CapturingScopeInfo::isCXXThisCaptured(), clang::DeclContext::isDependentContext(), and clang::UnresolvedMemberExpr::isImplicitAccess().
Referenced by clang::Sema::BuildCallExpr().
TryTypoCorrectionForCall()
static TypoCorrection TryTypoCorrectionForCall (Sema & S, Expr * Fn, FunctionDecl * FDecl, ArrayRef< Expr * > Args) static
Definition at line 5703 of file SemaExpr.cpp.
References clang::Sema::AddOverloadCandidate(), clang::AS_none, clang::OverloadCandidateSet::BestViableFunction(), clang::Sema::CorrectTypo(), clang::OverloadCandidateSet::CSK_Normal, clang::Sema::CTK_ErrorRecovery, clang::Sema::CurContext, clang::DeclarationName::getAsIdentifierInfo(), clang::Stmt::getBeginLoc(), clang::NamedDecl::getDeclName(), clang::MemberExpr::getMemberLoc(), clang::Sema::getScopeForContext(), clang::Sema::LookupOrdinaryName, clang::DeclAccessPair::make(), and clang::OR_Success.
Referenced by clang::Sema::ConvertArgumentsForCall().
tryVectorConvertAndSplat()
static bool tryVectorConvertAndSplat (Sema & S, ExprResult * scalar, QualType scalarTy, QualType vectorEltTy, QualType vectorTy, unsigned & DiagID) static
Try to convert a value of non-vector type to a vector type by converting the type to the element type of the vector and then performing a splat.
If the language is OpenCL, we only use conversions that promote scalar rank; for C, Obj-C, and C++ we allow any real scalar conversion except for float->int.
OpenCL V2.0 6.2.6.p2: An error shall occur if any scalar operand type has greater rank than the type of the vector element.
Parameters
scalar - if non-null, actually perform the conversions
Returns
true if the operation fails (but without diagnosing the failure)
Definition at line 9636 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::ASTContext::getFloatingTypeOrder(), clang::ASTContext::getIntegerTypeOrder(), clang::Sema::getLangOpts(), clang::Sema::ImpCastExprToType(), clang::Type::isIntegerType(), clang::Type::isIntegralType(), and clang::Type::isRealFloatingType().
Referenced by clang::Sema::CheckVectorOperands().
unsupportedTypeConversion()
static bool unsupportedTypeConversion (const Sema & S, QualType LHSType, QualType RHSType) static
Diagnose attempts to convert between __float128 and long double if there is no support for such conversion.
Helper function of UsualArithmeticConversions().
Definition at line 1191 of file SemaExpr.cpp.
References clang::Sema::Context, clang::ASTContext::Float128Ty, clang::Type::getAs(), clang::ComplexType::getElementType(), clang::ASTContext::getFloatingTypeOrder(), clang::ASTContext::getFloatTypeSemantics(), clang::Type::isFloatingType(), and clang::ASTContext::LongDoubleTy.
Referenced by clang::Sema::CheckAssignmentConstraints(), clang::Sema::CheckConditionalOperands(), and clang::Sema::UsualArithmeticConversions().
warnOnSizeofOnArrayDecay()
static void warnOnSizeofOnArrayDecay (Sema & S, SourceLocation Loc, QualType T, Expr * E) static
Check whether E is a pointer from a decayed array type (the decayed pointer type is equal to T) and emit a warning if it is.
Definition at line 4061 of file SemaExpr.cpp.
References clang::Sema::Diag(), clang::CastExpr::getCastKind(), clang::Stmt::getSourceRange(), clang::CastExpr::getSubExpr(), and clang::Expr::getType().
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().