clang: lib/Sema/SemaDeclObjC.cpp File Reference
SemaDeclObjC.cpp File Reference
#include "TypeLocBuilder.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "clang/AST/DeclNodes.inc"
Macros
#define OBJCCONTAINER(type, base)
#define ABSTRACT_DECL(expansion)
#define DECL(type, base)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
Typedefs
typedef llvm::DenseSet< IdentifierInfo * > ProtocolNameSet
FIXME: Type hierarchies in Objective-C can be deep.
typedef std::unique_ptr< ProtocolNameSet > LazyProtocolNameSet
Functions
static bool diagnoseNoescape (const ParmVarDecl *NewD, const ParmVarDecl *OldD, Sema &S)
Issue a warning if the parameter of the overridden method is non-escaping but the parameter of the overriding method is not.
static void diagnoseNoescape (const ParmVarDecl *NewD, const ParmVarDecl *OldD, const ObjCCategoryDecl *CD, const ObjCProtocolDecl *PD, Sema &S)
Produce additional diagnostics if a category conforms to a protocol that defines a method taking a non-escaping parameter.
static void DiagnoseObjCImplementedDeprecations (Sema &S, const NamedDecl *ND, SourceLocation ImplLoc)
static bool HasExplicitOwnershipAttr (Sema &S, ParmVarDecl *Param)
HasExplicitOwnershipAttr - returns true when pointer to ObjC pointer has explicit ownership attribute; false otherwise.
static void diagnoseUseOfProtocols (Sema &TheSema, ObjCContainerDecl *CD, ObjCProtocolDecl *const *ProtoRefs, unsigned NumProtoRefs, const SourceLocation *ProtoLocs)
static bool checkTypeParamListConsistency (Sema &S, ObjCTypeParamList *prevTypeParams, ObjCTypeParamList *newTypeParams, TypeParamListContext newContext)
Check consistency between two Objective-C type parameter lists, e.g., between a category/extension and an @interface or between an @class and an @interface.
static bool NestedProtocolHasNoDefinition (ObjCProtocolDecl *PDecl, ObjCProtocolDecl *&UndefinedProtocol)
static void WarnUndefinedMethod (Sema &S, SourceLocation ImpLoc, ObjCMethodDecl *method, bool &IncompleteImpl, unsigned DiagID, NamedDecl *NeededFor=nullptr)
static bool isObjCTypeSubstitutable (ASTContext &Context, const ObjCObjectPointerType *A, const ObjCObjectPointerType *B, bool rejectId)
Determines if type B can be substituted for type A.
static SourceRange getTypeRange (TypeSourceInfo *TSI)
static bool objcModifiersConflict (Decl::ObjCDeclQualifier x, Decl::ObjCDeclQualifier y)
Determine whether two set of Objective-C declaration qualifiers conflict.
static bool CheckMethodOverrideReturn (Sema &S, ObjCMethodDecl *MethodImpl, ObjCMethodDecl *MethodDecl, bool IsProtocolMethodDecl, bool IsOverridingMode, bool Warn)
static bool CheckMethodOverrideParam (Sema &S, ObjCMethodDecl *MethodImpl, ObjCMethodDecl *MethodDecl, ParmVarDecl *ImplVar, ParmVarDecl *IfaceVar, bool IsProtocolMethodDecl, bool IsOverridingMode, bool Warn)
static bool checkMethodFamilyMismatch (Sema &S, ObjCMethodDecl *impl, ObjCMethodDecl *decl)
In ARC, check whether the conventional meanings of the two methods match.
static void findProtocolsWithExplicitImpls (const ObjCProtocolDecl *PDecl, ProtocolNameSet &PNS)
static void findProtocolsWithExplicitImpls (const ObjCInterfaceDecl *Super, ProtocolNameSet &PNS)
Recursively populates a set with all conformed protocols in a class hierarchy that have the 'objc_protocol_requires_explicit_implementation' attribute.
static void CheckProtocolMethodDefs (Sema &S, SourceLocation ImpLoc, ObjCProtocolDecl *PDecl, bool &IncompleteImpl, const Sema::SelectorSet &InsMap, const Sema::SelectorSet &ClsMap, ObjCContainerDecl *CDecl, LazyProtocolNameSet &ProtocolsExplictImpl)
CheckProtocolMethodDefs - This routine checks unimplemented methods Declared in protocol, and those referenced by it.
static bool tryMatchRecordTypes (ASTContext &Context, Sema::MethodMatchStrategy strategy, const Type *left, const Type *right)
static bool matchTypes (ASTContext &Context, Sema::MethodMatchStrategy strategy, QualType leftQT, QualType rightQT)
static bool isMethodContextSameForKindofLookup (ObjCMethodDecl *Method, ObjCMethodDecl *MethodInList)
static bool isAcceptableMethodMismatch (ObjCMethodDecl *chosen, ObjCMethodDecl *other)
Determines if this is an "acceptable" loose mismatch in the global method pool.
static bool FilterMethodsByTypeBound (ObjCMethodDecl *Method, const ObjCObjectType *TypeBound)
Return true if the given method is wthin the type bound.
static void HelperSelectorsForTypoCorrection (SmallVectorImpl< const ObjCMethodDecl * > &BestMethod, StringRef Typo, const ObjCMethodDecl *Method)
static bool HelperIsMethodInObjCType (Sema &S, Selector Sel, QualType ObjectType)
static void DiagnoseWeakIvars (Sema &S, ObjCImplementationDecl *ID)
Diagnose attempts to define ARC-__weak ivars when __weak is disabled.
static void DiagnoseRetainableFlexibleArrayMember (Sema &S, ObjCInterfaceDecl *ID)
Diagnose attempts to use flexible array member with retainable object type.
static bool IsVariableSizedType (QualType T)
static void DiagnoseVariableSizedIvars (Sema &S, ObjCContainerDecl *OCD)
static void DiagnoseCategoryDirectMembersProtocolConformance (Sema &S, ObjCProtocolDecl *PDecl, ObjCCategoryDecl *CDecl)
static void DiagnoseCategoryDirectMembersProtocolConformance (Sema &S, ObjCCategoryDecl *CDecl, const llvm::iterator_range< ObjCProtocolList::iterator > &Protocols)
static Decl::ObjCDeclQualifier CvtQTToAstBitMask (ObjCDeclSpec::ObjCDeclQualifier PQTVal)
CvtQTToAstBitMask - utility routine to produce an AST bitmask for objective-c's type qualifier from the parser version of the same info.
static Sema::ResultTypeCompatibilityKind CheckRelatedResultTypeCompatibility (Sema &S, ObjCMethodDecl *Method, ObjCInterfaceDecl *CurrentClass)
Check whether the declared result type of the given Objective-C method declaration is compatible with the method's class.
static QualType mergeTypeNullabilityForRedecl (Sema &S, SourceLocation loc, QualType type, bool usesCSKeyword, SourceLocation prevLoc, QualType prevType, bool prevUsesCSKeyword)
Merge type nullability from for a redeclaration of the same entity, producing the updated type of the redeclared entity.
static void mergeInterfaceMethodToImpl (Sema &S, ObjCMethodDecl *method, ObjCMethodDecl *prevMethod)
Merge information from the declaration of a method in the @interface (or a category/extension) into the corresponding method in the @implementation (for a class or category).
static void checkObjCMethodX86VectorTypes (Sema &SemaRef, const ObjCMethodDecl *Method)
Verify that the method parameters/return value have types that are supported by the x86 target.
static void mergeObjCDirectMembers (Sema &S, Decl *CD, ObjCMethodDecl *Method)
static void checkObjCDirectMethodClashes (Sema &S, ObjCInterfaceDecl *IDecl, ObjCMethodDecl *Method, ObjCImplDecl *ImpDecl=nullptr)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (expansion)
ACCESSSPEC
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
BINDING
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BUILTINTEMPLATE
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CAPTURED
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CONCEPT
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONSTRUCTORUSINGSHADOW
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CXXCONSTRUCTOR
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDESTRUCTOR
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXMETHOD
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXRECORD
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
DECL
#define DECL (type, base)
Value:
    case Decl::type:
DECL_CONTEXT
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_RANGE
#define DECL_RANGE (Base, First, Last)
DECLARATOR
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECOMPOSITION
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
EMPTY
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPORT
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
FIELD
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FRIEND
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FUNCTION
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONTEMPLATE
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
IMPLICITPARAM
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPORT
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
LABEL
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LAST_DECL_RANGE
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MSGUID
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
NAMED
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NONTYPETEMPLATEPARM
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
OBJCATDEFSFIELD
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCCATEGORY
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER
#define OBJCCONTAINER (type, base)
Value:
    case Decl::type: \
      searchFrom(cast<type##Decl>(container)); \
      break;
OBJCIMPL
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINTERFACE
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIVAR
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCMETHOD
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROTOCOL
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCTYPEPARAM
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OMPALLOCATE
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPCAPTUREDEXPR
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPDECLAREMAPPER
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPREQUIRES
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
PARMVAR
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PRAGMACOMMENT
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
RECORD
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
REDECLARABLETEMPLATE
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPRBODY
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
TAG
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPEALIAS
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USING
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VALUE
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VAR
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
Typedef Documentation
LazyProtocolNameSet
typedef std::unique_ptr<ProtocolNameSet> LazyProtocolNameSet
Definition at line 2656 of file SemaDeclObjC.cpp.
ProtocolNameSet
typedef llvm::DenseSet<IdentifierInfo*> ProtocolNameSet
FIXME: Type hierarchies in Objective-C can be deep.
We could most likely improve the efficiency of selector lookups and type checking by associating with each protocol / interface / category the flattened instance tables. If we used an immutable set to keep the table then it wouldn't add significant memory cost and it would be handy for lookups.
Definition at line 2655 of file SemaDeclObjC.cpp.
Function Documentation
checkMethodFamilyMismatch()
static bool checkMethodFamilyMismatch (Sema & S, ObjCMethodDecl * impl, ObjCMethodDecl * decl) static
In ARC, check whether the conventional meanings of the two methods match.
If they don't, it's a hard error.
Definition at line 2487 of file SemaDeclObjC.cpp.
References clang::ast_matchers::decl, clang::Sema::Diag(), clang::Decl::getLocation(), clang::ObjCMethodDecl::getMethodFamily(), clang::ObjCMethodDecl::getReturnType(), int, clang::Decl::isInvalidDecl(), clang::Type::isObjCObjectPointerType(), clang::OMF_alloc, clang::OMF_autorelease, clang::OMF_copy, clang::OMF_dealloc, clang::OMF_finalize, clang::OMF_init, clang::OMF_initialize, clang::OMF_mutableCopy, clang::OMF_new, clang::OMF_None, clang::OMF_performSelector, clang::OMF_release, clang::OMF_retain, clang::OMF_retainCount, and clang::OMF_self.
Referenced by clang::Sema::WarnConflictingTypedMethods().
CheckMethodOverrideParam()
static bool CheckMethodOverrideParam (Sema & S, ObjCMethodDecl * MethodImpl, ObjCMethodDecl * MethodDecl, ParmVarDecl * ImplVar, ParmVarDecl * IfaceVar, bool IsProtocolMethodDecl, bool IsOverridingMode, bool Warn) static
Definition at line 2402 of file SemaDeclObjC.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::Type::getNullability(), clang::ParmVarDecl::getObjCDeclQualifier(), clang::ValueDecl::getType(), getTypeRange(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTContext::hasSameNullabilityTypeQualifier(), clang::ASTContext::hasSameUnqualifiedType(), isObjCTypeSubstitutable(), clang::Decl::OBJC_TQ_CSNullability, and objcModifiersConflict().
Referenced by clang::Sema::CheckConflictingOverridingMethod(), clang::Sema::WarnConflictingTypedMethods(), and clang::Sema::WarnExactTypedMethods().
CheckMethodOverrideReturn()
static bool CheckMethodOverrideReturn (Sema & S, ObjCMethodDecl * MethodImpl, ObjCMethodDecl * MethodDecl, bool IsProtocolMethodDecl, bool IsOverridingMode, bool Warn) static
Definition at line 2318 of file SemaDeclObjC.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAs(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::Type::getNullability(), clang::ObjCMethodDecl::getObjCDeclQualifier(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getReturnTypeSourceRange(), clang::ASTContext::hasSameNullabilityTypeQualifier(), clang::ASTContext::hasSameUnqualifiedType(), isObjCTypeSubstitutable(), clang::Decl::OBJC_TQ_CSNullability, and objcModifiersConflict().
Referenced by clang::Sema::CheckConflictingOverridingMethod(), clang::Sema::WarnConflictingTypedMethods(), and clang::Sema::WarnExactTypedMethods().
checkObjCDirectMethodClashes()
static void checkObjCDirectMethodClashes (Sema & S, ObjCInterfaceDecl * IDecl, ObjCMethodDecl * Method, ObjCImplDecl * ImpDecl = nullptr) static
Definition at line 4651 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), clang::ObjCInterfaceDecl::getImplementation(), clang::ObjCContainerDecl::getMethod(), and clang::ObjCInterfaceDecl::visible_categories().
Referenced by clang::Sema::ActOnMethodDeclaration().
checkObjCMethodX86VectorTypes()
static void checkObjCMethodX86VectorTypes (Sema & SemaRef, const ObjCMethodDecl * Method) static
Verify that the method parameters/return value have types that are supported by the x86 target.
Definition at line 4602 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), clang::Sema::getASTContext(), clang::TargetInfo::getPlatformMinVersion(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::SourceLocation::isInvalid(), and P.
Referenced by clang::Sema::ActOnMethodDeclaration().
CheckProtocolMethodDefs()
static void CheckProtocolMethodDefs (Sema & S, SourceLocation ImpLoc, ObjCProtocolDecl * PDecl, bool & IncompleteImpl, const Sema::SelectorSet & InsMap, const Sema::SelectorSet & ClsMap, ObjCContainerDecl * CDecl, LazyProtocolNameSet & ProtocolsExplictImpl) static
CheckProtocolMethodDefs - This routine checks unimplemented methods Declared in protocol, and those referenced by it.
Definition at line 2682 of file SemaDeclObjC.cpp.
References clang::C, CheckProtocolMethodDefs(), clang::ObjCContainerDecl::class_methods(), clang::Sema::Context, DIAG, clang::Sema::Diags, findProtocolsWithExplicitImpls(), clang::IdentifierTable::get(), clang::ObjCProtocolDecl::getDefinition(), clang::NamedDecl::getIdentifier(), clang::Sema::getLangOpts(), clang::SelectorTable::getSelector(), clang::ObjCInterfaceDecl::getSuperClass(), clang::Decl::hasAttr(), clang::ASTContext::Idents, clang::ObjCContainerDecl::instance_methods(), clang::DiagnosticsEngine::isIgnored(), clang::ObjCRuntime::isNeXTFamily(), clang::ObjCProtocolDecl::isThisDeclarationADefinition(), clang::ObjCInterfaceDecl::lookupInheritedClass(), clang::ObjCInterfaceDecl::lookupMethod(), clang::LangOptions::ObjCRuntime, clang::ObjCMethodDecl::Optional, clang::ObjCProtocolDecl::protocols(), clang::ASTContext::Selectors, and WarnUndefinedMethod().
Referenced by CheckProtocolMethodDefs(), and clang::Sema::ImplMethodsVsClassMethods().
CheckRelatedResultTypeCompatibility()
static Sema::ResultTypeCompatibilityKind CheckRelatedResultTypeCompatibility (Sema & S, ObjCMethodDecl * Method, ObjCInterfaceDecl * CurrentClass) static
Check whether the declared result type of the given Objective-C method declaration is compatible with the method's class.
Definition at line 4225 of file SemaDeclObjC.cpp.
References clang::declaresSameEntity(), clang::Type::getAs(), clang::Sema::RTC_Compatible, clang::Sema::RTC_Incompatible, and clang::Sema::RTC_Unknown.
Referenced by clang::Sema::ActOnMethodDeclaration().
checkTypeParamListConsistency()
static bool checkTypeParamListConsistency (Sema & S, ObjCTypeParamList * prevTypeParams, ObjCTypeParamList * newTypeParams, TypeParamListContext newContext) static
Check consistency between two Objective-C type parameter lists, e.g., between a category/extension and an @interface or between an @class and an @interface.
Definition at line 828 of file SemaDeclObjC.cpp.
References clang::ASTContext::adjustObjCTypeParamBoundType(), clang::ObjCTypeParamList::back(), clang::ObjCTypeParamList::begin(), clang::Sema::Context, clang::Contravariant, clang::Covariant, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateRemoval(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), clang::QualType::getAsString(), clang::SourceRange::getBegin(), clang::TypeDecl::getBeginLoc(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Decl::getEndLoc(), clang::Decl::getLocation(), clang::Sema::getLocForEndOfToken(), clang::ASTContext::getPrintingPolicy(), clang::TypeLoc::getSourceRange(), clang::TypeSourceInfo::getTypeLoc(), clang::TypedefNameDecl::getTypeSourceInfo(), clang::TypedefNameDecl::getUnderlyingType(), clang::ObjCTypeParamDecl::getVariance(), clang::ObjCTypeParamDecl::getVarianceLoc(), clang::ObjCTypeParamDecl::hasExplicitBound(), clang::ASTContext::hasSameType(), clang::Invariant, clang::SourceLocation::isInvalid(), clang::ObjCTypeParamDecl::setVariance(), and clang::ObjCTypeParamList::size().
Referenced by clang::Sema::ActOnForwardClassDeclaration(), clang::Sema::ActOnStartCategoryInterface(), and clang::Sema::ActOnStartClassInterface().
CvtQTToAstBitMask()
static Decl::ObjCDeclQualifier CvtQTToAstBitMask (ObjCDeclSpec::ObjCDeclQualifier PQTVal) static
CvtQTToAstBitMask - utility routine to produce an AST bitmask for objective-c's type qualifier from the parser version of the same info.
Definition at line 4217 of file SemaDeclObjC.cpp.
Referenced by clang::Sema::ActOnMethodDeclaration().
DiagnoseCategoryDirectMembersProtocolConformance() [1/2]
static void DiagnoseCategoryDirectMembersProtocolConformance (Sema & S, ObjCCategoryDecl * CDecl, const llvm::iterator_range< ObjCProtocolList::iterator > & Protocols) static
Definition at line 3918 of file SemaDeclObjC.cpp.
References DiagnoseCategoryDirectMembersProtocolConformance().
DiagnoseCategoryDirectMembersProtocolConformance() [2/2]
static void DiagnoseCategoryDirectMembersProtocolConformance (Sema & S, ObjCProtocolDecl * PDecl, ObjCCategoryDecl * CDecl) static
Definition at line 3925 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), DiagnoseCategoryDirectMembersProtocolConformance(), clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCProtocolDecl::getDefinition(), clang::Decl::getLocation(), clang::ObjCCategoryDecl::IsClassExtension(), clang::ObjCProtocolDecl::isThisDeclarationADefinition(), clang::ObjCContainerDecl::methods(), clang::OBJC_PR_query_class, clang::OBJC_PR_query_instance, clang::ObjCContainerDecl::properties(), and clang::ObjCProtocolDecl::protocols().
Referenced by clang::Sema::ActOnAtEnd(), DiagnoseCategoryDirectMembersProtocolConformance(), and DiagnoseCategoryDirectMembersProtocolConformance().
diagnoseNoescape() [1/2]
static void diagnoseNoescape (const ParmVarDecl * NewD, const ParmVarDecl * OldD, const ObjCCategoryDecl * CD, const ObjCProtocolDecl * PD, Sema & S) static
Produce additional diagnostics if a category conforms to a protocol that defines a method taking a non-escaping parameter.
Definition at line 127 of file SemaDeclObjC.cpp.
References clang::cast(), clang::Sema::Diag(), diagnoseNoescape(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), and clang::ObjCCategoryDecl::IsClassExtension().
diagnoseNoescape() [2/2]
static bool diagnoseNoescape (const ParmVarDecl * NewD, const ParmVarDecl * OldD, Sema & S) static
Issue a warning if the parameter of the overridden method is non-escaping but the parameter of the overriding method is not.
Definition at line 114 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), clang::Decl::getLocation(), and clang::Decl::hasAttr().
Referenced by clang::Sema::ActOnMethodDeclaration(), clang::Sema::CheckObjCMethodOverride(), and diagnoseNoescape().
DiagnoseObjCImplementedDeprecations()
static void DiagnoseObjCImplementedDeprecations (Sema & S, const NamedDecl * ND, SourceLocation ImplLoc) static
Definition at line 282 of file SemaDeclObjC.cpp.
References clang::AR_Deprecated, clang::AR_Unavailable, clang::Sema::Context, clang::Sema::Diag(), clang::Decl::getAvailability(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::TargetInfo::getPlatformName(), clang::ASTContext::getTargetInfo(), and clang::isa().
Referenced by clang::Sema::ActOnStartCategoryImplementation(), clang::Sema::ActOnStartClassImplementation(), and clang::Sema::ActOnStartOfObjCMethodDef().
DiagnoseRetainableFlexibleArrayMember()
static void DiagnoseRetainableFlexibleArrayMember (Sema & S, ObjCInterfaceDecl * ID) static
Diagnose attempts to use flexible array member with retainable object type.
Definition at line 3786 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::QualType::getObjCLifetime(), clang::Type::isIncompleteArrayType(), clang::Type::isObjCLifetimeType(), and clang::Qualifiers::OCL_ExplicitNone.
Referenced by clang::Sema::ActOnAtEnd().
diagnoseUseOfProtocols()
static void diagnoseUseOfProtocols (Sema & TheSema, ObjCContainerDecl * CD, ObjCProtocolDecl *const * ProtoRefs, unsigned NumProtoRefs, const SourceLocation * ProtoLocs) static
Definition at line 525 of file SemaDeclObjC.cpp.
References clang::Sema::DiagnoseUseOfDecl().
Referenced by clang::Sema::ActOnStartCategoryInterface(), clang::Sema::ActOnStartClassInterface(), and clang::Sema::ActOnStartProtocolInterface().
DiagnoseVariableSizedIvars()
static void DiagnoseVariableSizedIvars (Sema & S, ObjCContainerDecl * OCD) static
Definition at line 3832 of file SemaDeclObjC.cpp.
References clang::ObjCInterfaceDecl::all_declared_ivar_begin(), clang::Sema::Diag(), clang::Type::getAs(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::ObjCIvarDecl::getNextIvar(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ValueDecl::getType(), clang::Type::isIncompleteArrayType(), IsVariableSizedType(), clang::ObjCInterfaceDecl::ivar_begin(), clang::ObjCInterfaceDecl::ivar_empty(), clang::ObjCInterfaceDecl::ivar_size(), clang::ObjCInterfaceDecl::ivars(), and clang::TTK_Class.
Referenced by clang::Sema::ActOnAtEnd().
DiagnoseWeakIvars()
static void DiagnoseWeakIvars (Sema & S, ObjCImplementationDecl * ID) static
Diagnose attempts to define ARC-__weak ivars when __weak is disabled.
Definition at line 3769 of file SemaDeclObjC.cpp.
References clang::Sema::Diag(), clang::Sema::getLangOpts(), and clang::Qualifiers::OCL_Weak.
Referenced by clang::Sema::ActOnAtEnd().
FilterMethodsByTypeBound()
static bool FilterMethodsByTypeBound (ObjCMethodDecl * Method, const ObjCObjectType * TypeBound) static
Return true if the given method is wthin the type bound.
Definition at line 3462 of file SemaDeclObjC.cpp.
References clang::ObjCObjectType::getInterface(), and clang::ObjCObjectType::isObjCId().
Referenced by clang::Sema::CollectMultipleMethodsInGlobalPool().
findProtocolsWithExplicitImpls() [1/2]
static void findProtocolsWithExplicitImpls (const ObjCInterfaceDecl * Super, ProtocolNameSet & PNS) static
Recursively populates a set with all conformed protocols in a class hierarchy that have the 'objc_protocol_requires_explicit_implementation' attribute.
Definition at line 2669 of file SemaDeclObjC.cpp.
References clang::ObjCInterfaceDecl::all_referenced_protocols(), findProtocolsWithExplicitImpls(), and clang::ObjCInterfaceDecl::getSuperClass().
findProtocolsWithExplicitImpls() [2/2]
static void findProtocolsWithExplicitImpls (const ObjCProtocolDecl * PDecl, ProtocolNameSet & PNS) static
Definition at line 2658 of file SemaDeclObjC.cpp.
References findProtocolsWithExplicitImpls(), clang::NamedDecl::getIdentifier(), clang::Decl::hasAttr(), and clang::ObjCProtocolDecl::protocols().
Referenced by CheckProtocolMethodDefs(), findProtocolsWithExplicitImpls(), and findProtocolsWithExplicitImpls().
getTypeRange()
static SourceRange getTypeRange (TypeSourceInfo * TSI) static
Definition at line 2307 of file SemaDeclObjC.cpp.
References clang::TypeLoc::getSourceRange(), and clang::TypeSourceInfo::getTypeLoc().
Referenced by CheckMethodOverrideParam().
HasExplicitOwnershipAttr()
static bool HasExplicitOwnershipAttr (Sema & S, ParmVarDecl * Param) static
HasExplicitOwnershipAttr - returns true when pointer to ObjC pointer has explicit ownership attribute; false otherwise.
Definition at line 344 of file SemaDeclObjC.cpp.
References clang::Type::getAs().
Referenced by clang::Sema::ActOnStartOfObjCMethodDef().
HelperIsMethodInObjCType()
static bool HelperIsMethodInObjCType (Sema & S, Selector Sel, QualType ObjectType) static
Definition at line 3679 of file SemaDeclObjC.cpp.
References clang::QualType::isNull(), and clang::Sema::LookupMethodInObjectType().
Referenced by clang::Sema::SelectorsForTypoCorrection().
HelperSelectorsForTypoCorrection()
static void HelperSelectorsForTypoCorrection (SmallVectorImpl< const ObjCMethodDecl * > & BestMethod, StringRef Typo, const ObjCMethodDecl * Method) static
Definition at line 3657 of file SemaDeclObjC.cpp.
References abs().
Referenced by clang::Sema::SelectorsForTypoCorrection().
isAcceptableMethodMismatch()
static bool isAcceptableMethodMismatch (ObjCMethodDecl * chosen, ObjCMethodDecl * other) static
Determines if this is an "acceptable" loose mismatch in the global method pool.
This exists mostly as a hack to get around certain global mismatches which we can't afford to make warnings / errors. Really, what we want is a way to take a method out of the global method pool.
Definition at line 3444 of file SemaDeclObjC.cpp.
References clang::Selector::getNameForSlot(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::isDirectMethod(), clang::ObjCMethodDecl::isInstanceMethod(), clang::Type::isIntegerType(), and clang::Selector::isUnarySelector().
Referenced by clang::Sema::DiagnoseMultipleMethodInGlobalPool().
isMethodContextSameForKindofLookup()
static bool isMethodContextSameForKindofLookup (ObjCMethodDecl * Method, ObjCMethodDecl * MethodInList) static
Definition at line 3283 of file SemaDeclObjC.cpp.
References clang::ObjCMethodDecl::getClassInterface(), and clang::Decl::getDeclContext().
Referenced by clang::Sema::addMethodToGlobalList().
isObjCTypeSubstitutable()
static bool isObjCTypeSubstitutable (ASTContext & Context, const ObjCObjectPointerType * A, const ObjCObjectPointerType * B, bool rejectId) static
Determines if type B can be substituted for type A.
Returns true if we can guarantee that anything that the user will do to an object of type A can also be done to an object of type B. This is trivially true if the two types are the same, or if B is a subclass of A. It becomes more complex in cases where protocols are involved.
Object types in Objective-C describe the minimum requirements for an object, rather than providing a complete description of a type. For example, if A is a subclass of B, then B* may refer to an instance of A. The principle of substitutability means that we may use an instance of A anywhere that we may use an instance of B - it will implement all of the ivars of B and all of the methods of B.
This substitutability is important when type checking methods, because the implementation may have stricter type definitions than the interface. The interface specifies minimum requirements, but the implementation may have more accurate ones. For example, a method may privately accept instances of B, but only publish that it accepts instances of A. Any object passed to it will be type checked against B, and so will implicitly by a valid A*. Similarly, a method may return a subclass of the class that it is declared as returning.
This is most important when considering subclassing. A method in a subclass must accept any object as an argument that its superclass's implementation accepts. It may, however, accept a more general type without breaking substitutability (i.e. you can still use the subclass anywhere that you can use the superclass, but not vice versa). The converse requirement applies to return types: the return type for a subclass method must be a valid object of the kind that the superclass advertises, but it may be specified more accurately. This avoids the need for explicit down-casting by callers.
Note: This is a stricter requirement than for assignment.
Definition at line 2275 of file SemaDeclObjC.cpp.
References clang::ASTContext::canAssignObjCInterfaces(), clang::ObjCObjectPointerType::isObjCIdType(), clang::ObjCObjectPointerType::isObjCQualifiedIdType(), and clang::ASTContext::ObjCQualifiedIdTypesAreCompatible().
Referenced by CheckMethodOverrideParam(), and CheckMethodOverrideReturn().
IsVariableSizedType()
static bool IsVariableSizedType (QualType T) static
Definition at line 3825 of file SemaDeclObjC.cpp.
Referenced by DiagnoseVariableSizedIvars().
matchTypes()
static bool matchTypes (ASTContext & Context, Sema::MethodMatchStrategy strategy, QualType leftQT, QualType rightQT) static
Definition at line 3148 of file SemaDeclObjC.cpp.
References clang::TypeInfo::Align, clang::ASTContext::getCanonicalType(), clang::Type::getScalarTypeKind(), clang::ASTContext::getTypeInfo(), clang::CanQual< typename >::getTypePtr(), clang::CanQual< typename >::getUnqualifiedType(), clang::isa(), clang::Type::isIncompleteType(), clang::Type::isScalarType(), clang::Sema::MMS_strict, clang::Type::STK_BlockPointer, clang::Type::STK_Bool, clang::Type::STK_CPointer, clang::Type::STK_Integral, clang::Type::STK_ObjCObjectPointer, tryMatchRecordTypes(), and clang::TypeInfo::Width.
Referenced by clang::Sema::MatchTwoMethodDeclarations(), and tryMatchRecordTypes().
mergeInterfaceMethodToImpl()
static void mergeInterfaceMethodToImpl (Sema & S, ObjCMethodDecl * method, ObjCMethodDecl * prevMethod) static
Merge information from the declaration of a method in the @interface (or a category/extension) into the corresponding method in the @implementation (for a class or category).
Definition at line 4559 of file SemaDeclObjC.cpp.
References clang::Decl::addAttr(), clang::Sema::Context, clang::ObjCRequiresSuperAttr::CreateImplicit(), clang::SourceRange::getBegin(), clang::Decl::getLocation(), clang::ObjCMethodDecl::getObjCDeclQualifier(), clang::ParmVarDecl::getObjCDeclQualifier(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getReturnTypeSourceRange(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), mergeTypeNullabilityForRedecl(), clang::Decl::OBJC_TQ_CSNullability, clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_size(), clang::ObjCMethodDecl::setReturnType(), and clang::ValueDecl::setType().
Referenced by clang::Sema::ActOnMethodDeclaration().
mergeObjCDirectMembers()
static void mergeObjCDirectMembers (Sema & S, Decl * CD, ObjCMethodDecl * Method) static
Definition at line 4643 of file SemaDeclObjC.cpp.
References clang::Sema::Context, clang::ObjCDirectAttr::CreateImplicit(), and clang::Decl::hasAttr().
Referenced by clang::Sema::ActOnMethodDeclaration().
mergeTypeNullabilityForRedecl()
static QualType mergeTypeNullabilityForRedecl (Sema & S, SourceLocation loc, QualType type, bool usesCSKeyword, SourceLocation prevLoc, QualType prevType, bool prevUsesCSKeyword) static
Merge type nullability from for a redeclaration of the same entity, producing the updated type of the redeclared entity.
Definition at line 4519 of file SemaDeclObjC.cpp.
References clang::Sema::Context, clang::Sema::Diag(), clang::ASTContext::getAttributedType(), clang::Type::getNullability(), clang::AttributedType::getNullabilityAttrKind(), and clang::ast_matchers::type.
Referenced by mergeInterfaceMethodToImpl().
NestedProtocolHasNoDefinition()
static bool NestedProtocolHasNoDefinition (ObjCProtocolDecl * PDecl, ObjCProtocolDecl *& UndefinedProtocol) static
Definition at line 1278 of file SemaDeclObjC.cpp.
References clang::ObjCProtocolDecl::getDefinition(), clang::ObjCProtocolDecl::hasDefinition(), clang::Decl::isUnconditionallyVisible(), NestedProtocolHasNoDefinition(), and clang::ObjCProtocolDecl::protocols().
Referenced by clang::Sema::actOnObjCTypeArgsOrProtocolQualifiers(), clang::Sema::FindProtocolDeclaration(), and NestedProtocolHasNoDefinition().
objcModifiersConflict()
static bool objcModifiersConflict (Decl::ObjCDeclQualifier x, Decl::ObjCDeclQualifier y) static
Determine whether two set of Objective-C declaration qualifiers conflict.
Definition at line 2312 of file SemaDeclObjC.cpp.
References clang::Decl::OBJC_TQ_CSNullability.
Referenced by CheckMethodOverrideParam(), and CheckMethodOverrideReturn().
tryMatchRecordTypes()
static bool tryMatchRecordTypes (ASTContext & Context, Sema::MethodMatchStrategy strategy, const Type * left, const Type * right) static
Definition at line 3205 of file SemaDeclObjC.cpp.
References clang::TypeInfo::Align, clang::cast(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::ASTContext::getTypeInfo(), clang::TagDecl::isUnion(), matchTypes(), and clang::TypeInfo::Width.
Referenced by matchTypes().
WarnUndefinedMethod()
static void WarnUndefinedMethod (Sema & S, SourceLocation ImpLoc, ObjCMethodDecl * method, bool & IncompleteImpl, unsigned DiagID, NamedDecl * NeededFor = nullptr) static
Definition at line 2215 of file SemaDeclObjC.cpp.
References clang::AR_Unavailable, clang::Sema::Diag(), clang::Decl::getAvailability(), clang::ObjCMethodDecl::getBeginLoc(), and clang::SourceLocation::isValid().
Referenced by CheckProtocolMethodDefs(), and clang::Sema::MatchAllMethodDeclarations().