clang: lib/Sema/SemaExprObjC.cpp File Reference
SemaExprObjC.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Analysis/DomainSpecific/CocoaConventions.h"
#include "clang/Basic/Builtins.h"
#include "clang/Edit/Commit.h"
#include "clang/Edit/Rewriters.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/ConvertUTF.h"
Functions
static bool validateBoxingMethod (Sema &S, SourceLocation Loc, const ObjCInterfaceDecl *Class, Selector Sel, const ObjCMethodDecl *Method)
Emits an error if the given method does not exist, or if the return type is not an Objective-C object.
static NSAPI::NSClassIdKindKind ClassKindFromLiteralKind (Sema::ObjCLiteralKind LiteralKind)
Maps ObjCLiteralKind to NSClassIdKindKind.
static bool ValidateObjCLiteralInterfaceDecl (Sema &S, ObjCInterfaceDecl *Decl, SourceLocation Loc, Sema::ObjCLiteralKind LiteralKind)
Validates ObjCInterfaceDecl availability.
enum ARCConversionTypeClass {
ACTC_none , ACTC_retainable , ACTC_indirectRetainable , ACTC_voidPtr ,
ACTC_coreFoundation
}
static ObjCInterfaceDecl * LookupObjCInterfaceDeclForLiteral (Sema &S, SourceLocation Loc, Sema::ObjCLiteralKind LiteralKind)
Looks up ObjCInterfaceDecl of a given NSClassIdKindKind.
static ObjCMethodDecl * getNSNumberFactoryMethod (Sema &S, SourceLocation Loc, QualType NumberType, bool isLiteral=false, SourceRange R=SourceRange())
Retrieve the NSNumber factory method that should be used to create an Objective-C literal for the given type.
static ExprResult CheckObjCCollectionLiteralElement (Sema &S, Expr *Element, QualType T, bool ArrayLiteral=false)
Check that the given expression is a valid element of an Objective-C collection literal.
static void CheckObjCDictionaryLiteralDuplicateKeys (Sema &S, ObjCDictionaryLiteral *Literal)
Check for duplicate keys in an ObjC dictionary literal.
static bool HelperToDiagnoseMismatchedMethodsInGlobalPool (Sema &S, SourceLocation AtLoc, SourceLocation LParenLoc, SourceLocation RParenLoc, ObjCMethodDecl *Method, ObjCMethodList &MethList)
static void DiagnoseMismatchedSelectors (Sema &S, SourceLocation AtLoc, ObjCMethodDecl *Method, SourceLocation LParenLoc, SourceLocation RParenLoc, bool WarnMultipleSelectors)
static ObjCMethodDecl * LookupDirectMethodInMethodList (Sema &S, Selector Sel, ObjCMethodList &MethList, bool &onlyDirect, bool &anyDirect)
static ObjCMethodDecl * LookupDirectMethodInGlobalPool (Sema &S, Selector Sel, bool &onlyDirect, bool &anyDirect)
static ObjCMethodDecl * findMethodInCurrentClass (Sema &S, Selector Sel)
static QualType stripObjCInstanceType (ASTContext &Context, QualType T)
static QualType getBaseMessageSendResultType (Sema &S, QualType ReceiverType, ObjCMethodDecl *Method, bool isClassMessage, bool isSuperMessage)
Determine the result type of a message send based on the receiver type, method, and the kind of message send.
static const ObjCMethodDecl * findExplicitInstancetypeDeclarer (const ObjCMethodDecl *MD, QualType instancetype)
Look for an ObjC method whose result type exactly matches the given type.
static void applyCocoaAPICheck (Sema &S, const ObjCMessageExpr *Msg, unsigned DiagID, bool(*refactor)(const ObjCMessageExpr *, const NSAPI &, edit::Commit &))
static void checkCocoaAPI (Sema &S, const ObjCMessageExpr *Msg)
static void checkFoundationAPI (Sema &S, SourceLocation Loc, const ObjCMethodDecl *Method, ArrayRef< Expr * > Args, QualType ReceiverType, bool IsClassObjectCall)
static void DiagnoseCStringFormatDirectiveInObjCAPI (Sema &S, ObjCMethodDecl *Method, Selector Sel, Expr **Args, unsigned NumArgs)
Diagnose use of s directive in an NSString which is being passed as formatting string to formatting method.
static bool isMethodDeclaredInRootProtocol (Sema &S, const ObjCMethodDecl *M)
static void RemoveSelectorFromWarningCache (Sema &S, Expr *Arg)
static bool isAnyRetainable (ARCConversionTypeClass ACTC)
static bool isAnyCLike (ARCConversionTypeClass ACTC)
static ARCConversionTypeClass classifyTypeForARCConversion (QualType type)
template<typename DiagBuilderT >
static void addFixitForObjCARCConversion (Sema &S, DiagBuilderT &DiagB, Sema::CheckedConversionKind CCK, SourceLocation afterLParen, QualType castType, Expr *castExpr, Expr *realCast, const char *bridgeKeyword, const char *CFBridgeName)
template<typename T >
static T * getObjCBridgeAttr (const TypedefType *TD)
static ObjCBridgeRelatedAttr * ObjCBridgeRelatedAttrFromType (QualType T, TypedefNameDecl *&TDNDecl)
static void diagnoseObjCARCConversion (Sema &S, SourceRange castRange, QualType castType, ARCConversionTypeClass castACTC, Expr *castExpr, Expr *realCast, ARCConversionTypeClass exprACTC, Sema::CheckedConversionKind CCK)
template<typename TB >
static bool CheckObjCBridgeNSCast (Sema &S, QualType castType, Expr *castExpr, bool &HadTheAttribute, bool warn)
template<typename TB >
static bool CheckObjCBridgeCFCast (Sema &S, QualType castType, Expr *castExpr, bool &HadTheAttribute, bool warn)
static Expr * maybeUndoReclaimObject (Expr *e)
Look for an ObjCReclaimReturnedObject cast and destroy it.
Enumeration Type Documentation
ARCConversionTypeClass
enum ARCConversionTypeClass
Enumerator
ACTC_none
int, void, struct A
ACTC_retainable
id, void (^)()
ACTC_indirectRetainable
id*, id***, void (^*)(),
ACTC_voidPtr
void* might be a normal C type, or it might a CF type.
ACTC_coreFoundation
struct A*
Definition at line 3445 of file SemaExprObjC.cpp.
Function Documentation
addFixitForObjCARCConversion()
template<typename DiagBuilderT > static void addFixitForObjCARCConversion (Sema & S, DiagBuilderT & DiagB, Sema::CheckedConversionKind CCK, SourceLocation afterLParen, QualType castType, Expr * castExpr, Expr * realCast, const char * bridgeKeyword, const char * CFBridgeName) static
Definition at line 3750 of file SemaExprObjC.cpp.
References clang::ast_matchers::castExpr, clang::Sema::CCK_CStyleCast, clang::Sema::CCK_ForBuiltinOverloadedOp, clang::Sema::CCK_FunctionalCast, clang::Sema::CCK_ImplicitConversion, clang::Sema::CCK_OtherCast, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::QualType::getAsString(), clang::SourceManager::getCharacterData(), clang::Sema::getLangOpts(), clang::Sema::getLocForEndOfToken(), clang::Sema::getSourceManager(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreImpCasts(), clang::Lexer::isIdentifierBodyChar(), and SM.
Referenced by diagnoseObjCARCConversion().
applyCocoaAPICheck()
static void applyCocoaAPICheck (Sema & S, const ObjCMessageExpr * Msg, unsigned DiagID, bool(* refactor)(const ObjCMessageExpr *, const NSAPI &, edit::Commit &)) static
Definition at line 2448 of file SemaExprObjC.cpp.
References clang::edit::Commit::Act_Insert, clang::edit::Commit::Act_InsertFromRange, clang::edit::Commit::Act_Remove, clang::edit::Commit::Edit::BeforePrev, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateInsertionFromRange(), clang::FixItHint::CreateRemoval(), clang::Sema::Diag(), clang::Sema::Diags, clang::edit::Commit::edit_begin(), clang::edit::Commit::edit_end(), clang::Expr::getExprLoc(), clang::edit::Commit::Edit::getFileRange(), clang::edit::Commit::Edit::getInsertFromRange(), clang::ObjCMessageExpr::getSelector(), clang::Stmt::getSourceRange(), clang::edit::Commit::isCommitable(), clang::DiagnosticsEngine::isIgnored(), clang::edit::Commit::Edit::Kind, clang::Sema::LangOpts, clang::Sema::NSAPIObj, clang::edit::Commit::Edit::OrigLoc, SM, clang::Sema::SourceMgr, and clang::edit::Commit::Edit::Text.
Referenced by checkCocoaAPI().
checkCocoaAPI()
static void checkCocoaAPI (Sema & S, const ObjCMessageExpr * Msg) static
Definition at line 2487 of file SemaExprObjC.cpp.
References applyCocoaAPICheck(), and clang::edit::rewriteObjCRedundantCallWithLiteral().
Referenced by clang::Sema::BuildClassMessage(), and clang::Sema::BuildInstanceMessage().
checkFoundationAPI()
static void checkFoundationAPI (Sema & S, SourceLocation Loc, const ObjCMethodDecl * Method, ArrayRef< Expr * > Args, QualType ReceiverType, bool IsClassObjectCall) static
Definition at line 2492 of file SemaExprObjC.cpp.
References clang::Sema::Diag(), clang::Type::getAs(), clang::ObjCMethodDecl::getBeginLoc(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::OMF_performSelector, and Ret().
Referenced by clang::Sema::BuildClassMessage(), and clang::Sema::BuildInstanceMessage().
CheckObjCBridgeCFCast()
template<typename TB > static bool CheckObjCBridgeCFCast (Sema & S, QualType castType, Expr * castExpr, bool & HadTheAttribute, bool warn) static
Definition at line 4068 of file SemaExprObjC.cpp.
References clang::cast(), clang::ast_matchers::castExpr, clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAsObjCInterfacePointerType(), clang::TypeDecl::getBeginLoc(), clang::LookupResult::getFoundDecl(), getObjCBridgeAttr(), clang::TypedefNameDecl::getUnderlyingType(), clang::ObjCInterfaceDecl::isSuperClassOf(), clang::Sema::LookupName(), clang::Sema::LookupOrdinaryName, clang::ASTContext::QIdProtocolsAdoptObjCObjectProtocols(), and clang::Sema::TUScope.
Referenced by clang::Sema::CheckTollFreeBridgeCast().
CheckObjCBridgeNSCast()
template<typename TB > static bool CheckObjCBridgeNSCast (Sema & S, QualType castType, Expr * castExpr, bool & HadTheAttribute, bool warn) static
Definition at line 4002 of file SemaExprObjC.cpp.
References clang::cast(), clang::ast_matchers::castExpr, clang::Sema::Context, clang::Sema::Diag(), clang::Type::getAsObjCInterfacePointerType(), clang::TypeDecl::getBeginLoc(), clang::LookupResult::getFoundDecl(), getObjCBridgeAttr(), clang::Type::getPointeeType(), clang::TypedefNameDecl::getUnderlyingType(), clang::Type::isObjCIdType(), clang::ObjCInterfaceDecl::isSuperClassOf(), clang::Sema::LookupName(), clang::Sema::LookupOrdinaryName, clang::ASTContext::ObjCObjectAdoptsQTypeProtocols(), and clang::Sema::TUScope.
Referenced by clang::Sema::CheckTollFreeBridgeCast().
CheckObjCCollectionLiteralElement()
static ExprResult CheckObjCCollectionLiteralElement (Sema & S, Expr * Element, QualType T, bool ArrayLiteral = false) static
Check that the given expression is a valid element of an Objective-C collection literal.
Definition at line 386 of file SemaExprObjC.cpp.
References clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildObjCStringLiteral(), clang::Sema::CheckPlaceholderExpr(), clang::Sema::Context, clang::InitializationKind::CreateCopy(), clang::FixItHint::CreateInsertion(), clang::Sema::DefaultLvalueConversion(), clang::Sema::Diag(), clang::ExprError(), clang::InitializationSequence::Failed(), clang::Stmt::getBeginLoc(), clang::Sema::getLangOpts(), clang::Stmt::getSourceRange(), clang::StringLiteral::getString(), clang::Expr::getType(), clang::InitializedEntity::InitializeParameter(), clang::isa(), clang::Type::isBlockPointerType(), clang::Type::isObjCObjectPointerType(), clang::Type::isRecordType(), clang::Expr::isTypeDependent(), clang::Sema::NSAPIObj, clang::InitializationSequence::Perform(), clang::Sema::PerformCopyInitialization(), and clang::Result.
Referenced by clang::Sema::BuildObjCArrayLiteral(), and clang::Sema::BuildObjCDictionaryLiteral().
CheckObjCDictionaryLiteralDuplicateKeys()
static void CheckObjCDictionaryLiteralDuplicateKeys (Sema & S, ObjCDictionaryLiteral * Literal) static
Check for duplicate keys in an ObjC dictionary literal.
For instance: NSDictionary *nd = "foo" : @"bar", @"foo" : @"baz" };
Definition at line 900 of file SemaExprObjC.cpp.
References clang::Sema::Diag(), clang::Expr::EvaluateAsInt(), clang::Sema::getASTContext(), clang::ObjCDictionaryLiteral::getKeyValueElement(), clang::ObjCDictionaryLiteral::getNumElements(), clang::Expr::IgnoreParenImpCasts(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::ObjCDictionaryElement::Key, clang::Result, and clang::Expr::SE_AllowSideEffects.
Referenced by clang::Sema::BuildObjCDictionaryLiteral().
classifyTypeForARCConversion()
static ARCConversionTypeClass classifyTypeForARCConversion (QualType type) static
Definition at line 3474 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_indirectRetainable, ACTC_none, ACTC_retainable, ACTC_voidPtr, clang::Type::getAs(), and clang::Type::getAsArrayTypeUnsafe().
Referenced by clang::Sema::CheckObjCBridgeRelatedCast(), clang::Sema::CheckObjCBridgeRelatedConversions(), clang::Sema::CheckObjCConversion(), clang::Sema::CheckTollFreeBridgeCast(), clang::Sema::CheckTollFreeBridgeStaticCast(), and clang::Sema::diagnoseARCUnbridgedCast().
ClassKindFromLiteralKind()
static NSAPI::NSClassIdKindKind ClassKindFromLiteralKind (Sema::ObjCLiteralKind LiteralKind) static
Maps ObjCLiteralKind to NSClassIdKindKind.
Definition at line 170 of file SemaExprObjC.cpp.
References clang::NSAPI::ClassId_NSArray, clang::NSAPI::ClassId_NSDictionary, clang::NSAPI::ClassId_NSNumber, clang::NSAPI::ClassId_NSString, clang::NSAPI::ClassId_NSValue, clang::Sema::LK_Array, clang::Sema::LK_Block, clang::Sema::LK_Boxed, clang::Sema::LK_Dictionary, clang::Sema::LK_None, clang::Sema::LK_Numeric, and clang::Sema::LK_String.
Referenced by LookupObjCInterfaceDeclForLiteral(), and ValidateObjCLiteralInterfaceDecl().
DiagnoseCStringFormatDirectiveInObjCAPI()
static void DiagnoseCStringFormatDirectiveInObjCAPI (Sema & S, ObjCMethodDecl * Method, Selector Sel, Expr ** Args, unsigned NumArgs) static
Diagnose use of s directive in an NSString which is being passed as formatting string to formatting method.
Definition at line 2541 of file SemaExprObjC.cpp.
References clang::Sema::Diag(), clang::Sema::FormatStringHasSArg(), clang::Expr::getExprLoc(), clang::Sema::GetFormatNSStringIdx(), clang::StringLiteral::getString(), clang::Selector::getStringFormatFamily(), clang::Expr::IgnoreParenImpCasts(), and clang::SFF_NSString.
Referenced by clang::Sema::BuildClassMessage(), and clang::Sema::BuildInstanceMessage().
DiagnoseMismatchedSelectors()
static void DiagnoseMismatchedSelectors (Sema & S, SourceLocation AtLoc, ObjCMethodDecl * Method, SourceLocation LParenLoc, SourceLocation RParenLoc, bool WarnMultipleSelectors) static
Definition at line 1206 of file SemaExprObjC.cpp.
References b, clang::Sema::Diags, HelperToDiagnoseMismatchedMethodsInGlobalPool(), clang::DiagnosticsEngine::isIgnored(), and clang::Sema::MethodPool.
Referenced by clang::Sema::ParseObjCSelectorExpression().
diagnoseObjCARCConversion()
static void diagnoseObjCARCConversion (Sema & S, SourceRange castRange, QualType castType, ARCConversionTypeClass castACTC, Expr * castExpr, Expr * realCast, ARCConversionTypeClass exprACTC, Sema::CheckedConversionKind CCK) static
Definition at line 3870 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_indirectRetainable, ACTC_none, ACTC_retainable, ACTC_voidPtr, addFixitForObjCARCConversion(), clang::ast_matchers::castExpr, clang::Sema::CCK_OtherCast, clang::Sema::Context, clang::Sema::Diag(), clang::SourceRange::getBegin(), clang::Sema::getLocForEndOfToken(), clang::UnavailableAttr::IR_ARCForbiddenConversion, isAnyRetainable(), clang::Type::isBlockPointerType(), clang::Sema::isCast(), clang::Sema::isKnownName(), clang::Type::isPointerType(), clang::SourceLocation::isValid(), clang::SourceRange::isValid(), clang::Sema::makeUnavailableInSystemHeader(), and ObjCBridgeRelatedAttrFromType().
Referenced by clang::Sema::CheckObjCConversion(), and clang::Sema::diagnoseARCUnbridgedCast().
findExplicitInstancetypeDeclarer()
static const ObjCMethodDecl * findExplicitInstancetypeDeclarer (const ObjCMethodDecl * MD, QualType instancetype) static
Look for an ObjC method whose result type exactly matches the given type.
Definition at line 1624 of file SemaExprObjC.cpp.
References findExplicitInstancetypeDeclarer(), clang::Decl::getDeclContext(), clang::ObjCContainerDecl::getMethod(), clang::ObjCMethodDecl::getOverriddenMethods(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), and clang::ObjCMethodDecl::isInstanceMethod().
Referenced by clang::Sema::EmitRelatedResultTypeNoteForReturn(), and findExplicitInstancetypeDeclarer().
findMethodInCurrentClass()
static ObjCMethodDecl * findMethodInCurrentClass (Sema & S, Selector Sel) static
Definition at line 1272 of file SemaExprObjC.cpp.
References clang::Sema::getCurMethodDecl(), clang::ObjCInterfaceDecl::lookupMethod(), and clang::ObjCInterfaceDecl::lookupPrivateMethod().
Referenced by clang::Sema::ParseObjCSelectorExpression().
getBaseMessageSendResultType()
static QualType getBaseMessageSendResultType (Sema & S, QualType ReceiverType, ObjCMethodDecl * Method, bool isClassMessage, bool isSuperMessage) static
Determine the result type of a message send based on the receiver type, method, and the kind of message send.
This is the "base" result type, which will still need to be adjusted to account for nullability.
Definition at line 1454 of file SemaExprObjC.cpp.
References clang::Sema::Context, clang::Type::getAsObjCInterfaceType(), clang::ASTContext::getAttributedType(), clang::Sema::getCurMethodDecl(), clang::AttributedType::getNullabilityAttrKind(), clang::ASTContext::getObjCInterfaceType(), clang::ASTContext::getObjCObjectPointerType(), clang::Type::isObjCClassType(), clang::Type::isObjCQualifiedClassType(), stripObjCInstanceType(), clang::AttributedType::stripOuterNullability(), and clang::ast_matchers::type.
Referenced by clang::Sema::getMessageSendResultType().
getNSNumberFactoryMethod()
static ObjCMethodDecl * getNSNumberFactoryMethod (Sema & S, SourceLocation Loc, QualType NumberType, bool isLiteral = false, SourceRange R = SourceRange()) static
Retrieve the NSNumber factory method that should be used to create an Objective-C literal for the given type.
Definition at line 242 of file SemaExprObjC.cpp.
References clang::Sema::Context, clang::ObjCMethodDecl::Create(), clang::ParmVarDecl::Create(), clang::Sema::Diag(), clang::IdentifierTable::get(), clang::Sema::getLangOpts(), clang::ASTContext::getObjCInterfaceType(), clang::ASTContext::getObjCObjectPointerType(), clang::ASTContext::Idents, clang::QualType::isNull(), clang::Sema::LK_Numeric, clang::ObjCInterfaceDecl::lookupClassMethod(), LookupObjCInterfaceDeclForLiteral(), clang::Sema::NSAPIObj, clang::Sema::NSNumberDecl, clang::Sema::NSNumberLiteralMethods, clang::Sema::NSNumberPointer, clang::ObjCMethodDecl::Required, clang::SC_None, and validateBoxingMethod().
Referenced by clang::Sema::BuildObjCBoxedExpr(), and clang::Sema::BuildObjCNumericLiteral().
getObjCBridgeAttr()
template<typename T > static T * getObjCBridgeAttr (const TypedefType * TD) inline static
Definition at line 3845 of file SemaExprObjC.cpp.
References clang::Type::getAs(), clang::TypedefType::getDecl(), clang::RecordDecl::getMostRecentDecl(), clang::Type::getPointeeType(), clang::TypedefNameDecl::getUnderlyingType(), and clang::Type::isPointerType().
Referenced by CheckObjCBridgeCFCast(), CheckObjCBridgeNSCast(), and ObjCBridgeRelatedAttrFromType().
HelperToDiagnoseMismatchedMethodsInGlobalPool()
static bool HelperToDiagnoseMismatchedMethodsInGlobalPool (Sema & S, SourceLocation AtLoc, SourceLocation LParenLoc, SourceLocation RParenLoc, ObjCMethodDecl * Method, ObjCMethodList & MethList) static
Definition at line 1175 of file SemaExprObjC.cpp.
References clang::FixItHint::CreateInsertion(), clang::Sema::Diag(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), clang::ObjCMethodList::getMethod(), clang::ObjCMethodList::getNext(), clang::ObjCMethodDecl::getSelector(), clang::Sema::MatchTwoMethodDeclarations(), and clang::Sema::MMS_loose.
Referenced by DiagnoseMismatchedSelectors().
isAnyCLike()
static bool isAnyCLike (ARCConversionTypeClass ACTC) static
Definition at line 3468 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_none, and ACTC_voidPtr.
Referenced by clang::Sema::CheckObjCConversion().
isAnyRetainable()
static bool isAnyRetainable (ARCConversionTypeClass ACTC) static
Definition at line 3462 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_retainable, and ACTC_voidPtr.
Referenced by clang::Sema::CheckObjCConversion(), and diagnoseObjCARCConversion().
isMethodDeclaredInRootProtocol()
static bool isMethodDeclaredInRootProtocol (Sema & S, const ObjCMethodDecl * M) static
Definition at line 2792 of file SemaExprObjC.cpp.
References clang::NSAPI::ClassId_NSObject, clang::Decl::getDeclContext(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupSingleName(), clang::Sema::NSAPIObj, P, and clang::Sema::TUScope.
Referenced by clang::Sema::BuildInstanceMessage().
LookupDirectMethodInGlobalPool()
static ObjCMethodDecl * LookupDirectMethodInGlobalPool (Sema & S, Selector Sel, bool & onlyDirect, bool & anyDirect) static
Definition at line 1257 of file SemaExprObjC.cpp.
References LookupDirectMethodInMethodList(), and clang::Sema::MethodPool.
Referenced by clang::Sema::ParseObjCSelectorExpression().
LookupDirectMethodInMethodList()
static ObjCMethodDecl * LookupDirectMethodInMethodList (Sema & S, Selector Sel, ObjCMethodList & MethList, bool & onlyDirect, bool & anyDirect) static
Definition at line 1231 of file SemaExprObjC.cpp.
References clang::ObjCMethodList::getMethod(), and clang::ObjCMethodList::getNext().
Referenced by LookupDirectMethodInGlobalPool().
LookupObjCInterfaceDeclForLiteral()
static ObjCInterfaceDecl * LookupObjCInterfaceDeclForLiteral (Sema & S, SourceLocation Loc, Sema::ObjCLiteralKind LiteralKind) static
Looks up ObjCInterfaceDecl of a given NSClassIdKindKind.
Used to create ObjC literals, such as NSDictionary (}), NSArray (@[]) and Boxed Expressions (@())
Definition at line 218 of file SemaExprObjC.cpp.
References ClassKindFromLiteralKind(), clang::Sema::Context, clang::ObjCInterfaceDecl::Create(), clang::Sema::getLangOpts(), clang::ASTContext::getTranslationUnitDecl(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupSingleName(), clang::Sema::NSAPIObj, clang::Sema::TUScope, and ValidateObjCLiteralInterfaceDecl().
Referenced by clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), and getNSNumberFactoryMethod().
maybeUndoReclaimObject()
static Expr * maybeUndoReclaimObject (Expr * e) static
Look for an ObjCReclaimReturnedObject cast and destroy it.
Definition at line 4598 of file SemaExprObjC.cpp.
References clang::cast().
Referenced by clang::Sema::BuildObjCBridgedCast().
ObjCBridgeRelatedAttrFromType()
static ObjCBridgeRelatedAttr * ObjCBridgeRelatedAttrFromType (QualType T, TypedefNameDecl *& TDNDecl) static
Definition at line 3857 of file SemaExprObjC.cpp.
References getObjCBridgeAttr(), and clang::TypedefNameDecl::getUnderlyingType().
Referenced by clang::Sema::checkObjCBridgeRelatedComponents(), and diagnoseObjCARCConversion().
RemoveSelectorFromWarningCache()
static void RemoveSelectorFromWarningCache (Sema & S, Expr * Arg) static
Definition at line 3401 of file SemaExprObjC.cpp.
References clang::Expr::IgnoreParenCasts(), and clang::Sema::ReferencedSelectors.
Referenced by clang::Sema::ActOnInstanceMessage().
stripObjCInstanceType()
static QualType stripObjCInstanceType (ASTContext & Context, QualType T) static
Definition at line 1430 of file SemaExprObjC.cpp.
References clang::ASTContext::getAttributedType(), clang::AttributedType::getNullabilityAttrKind(), clang::ASTContext::getObjCIdType(), clang::ASTContext::getObjCInstanceType(), and clang::AttributedType::stripOuterNullability().
Referenced by getBaseMessageSendResultType().
validateBoxingMethod()
static bool validateBoxingMethod (Sema & S, SourceLocation Loc, const ObjCInterfaceDecl * Class, Selector Sel, const ObjCMethodDecl * Method) static
Emits an error if the given method does not exist, or if the return type is not an Objective-C object.
Definition at line 147 of file SemaExprObjC.cpp.
References clang::Sema::Diag(), and clang::Type::isObjCObjectPointerType().
Referenced by clang::Sema::BuildObjCArrayLiteral(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCDictionaryLiteral(), and getNSNumberFactoryMethod().
ValidateObjCLiteralInterfaceDecl()
static bool ValidateObjCLiteralInterfaceDecl (Sema & S, ObjCInterfaceDecl * Decl, SourceLocation Loc, Sema::ObjCLiteralKind LiteralKind) static
Validates ObjCInterfaceDecl availability.
ObjCInterfaceDecl, used to create ObjC literals, should be defined if clang not in a debugger mode.
Definition at line 196 of file SemaExprObjC.cpp.
References ClassKindFromLiteralKind(), clang::Sema::Diag(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::IdentifierInfo::getName(), and clang::Sema::NSAPIObj.
Referenced by LookupObjCInterfaceDeclForLiteral().