clang: lib/Sema/SemaAvailability.cpp File Reference
SemaAvailability.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Basic/DiagnosticSema.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/Sema.h"
Functions
static const AvailabilityAttr * getAttrForPlatform (ASTContext &Context, const Decl *D)
static std::pair< AvailabilityResult, const NamedDecl * > ShouldDiagnoseAvailabilityOfDecl (Sema &S, const NamedDecl *D, std::string *Message, ObjCInterfaceDecl *ClassReceiver)
The diagnostic we should emit for D, and the declaration that originated it, or AR_Available.
static bool ShouldDiagnoseAvailabilityInContext (Sema &S, AvailabilityResult K, VersionTuple DeclVersion, Decl *Ctx, const NamedDecl *OffendingDecl)
whether we should emit a diagnostic for K and DeclVersion in the context of Ctx.
static bool shouldDiagnoseAvailabilityByDefault (const ASTContext &Context, const VersionTuple &DeploymentVersion, const VersionTuple &DeclVersion)
static NamedDecl * findEnclosingDeclToAnnotate (Decl *OrigCtx)
static Optional< unsigned > tryParseObjCMethodName (StringRef Name, SmallVectorImpl< StringRef > &SlotNames, const LangOptions &LangOpts)
Tries to parse a string as ObjC method name.
static Optional< AttributeInsertion > createAttributeInsertion (const NamedDecl *D, const SourceManager &SM, const LangOptions &LangOpts)
Returns a source location in which it's appropriate to insert a new attribute for the given declaration \D.
static void DoEmitAvailabilityWarning (Sema &S, AvailabilityResult K, Decl *Ctx, const NamedDecl *ReferringDecl, const NamedDecl *OffendingDecl, StringRef Message, ArrayRef< SourceLocation > Locs, const ObjCInterfaceDecl *UnknownObjCClass, const ObjCPropertyDecl *ObjCProperty, bool ObjCPropertyAccess)
Actually emit an availability diagnostic for a reference to an unavailable decl.
static void EmitAvailabilityWarning (Sema &S, AvailabilityResult AR, const NamedDecl *ReferringDecl, const NamedDecl *OffendingDecl, StringRef Message, ArrayRef< SourceLocation > Locs, const ObjCInterfaceDecl *UnknownObjCClass, const ObjCPropertyDecl *ObjCProperty, bool ObjCPropertyAccess)
Function Documentation
createAttributeInsertion()
static Optional< AttributeInsertion > createAttributeInsertion (const NamedDecl * D, const SourceManager & SM, const LangOptions & LangOpts) static
Returns a source location in which it's appropriate to insert a new attribute for the given declaration \D.
Definition at line 280 of file SemaAvailability.cpp.
References clang::Lexer::getLocForEndOfToken(), clang::SourceLocation::isInvalid(), clang::None, and SM.
Referenced by DoEmitAvailabilityWarning().
DoEmitAvailabilityWarning()
static void DoEmitAvailabilityWarning (Sema & S, AvailabilityResult K, Decl * Ctx, const NamedDecl * ReferringDecl, const NamedDecl * OffendingDecl, StringRef Message, ArrayRef< SourceLocation > Locs, const ObjCInterfaceDecl * UnknownObjCClass, const ObjCPropertyDecl * ObjCProperty, bool ObjCPropertyAccess) static
Actually emit an availability diagnostic for a reference to an unavailable decl.
Parameters
Ctx The context that the reference occurred in
ReferringDecl The exact declaration that was referenced.
OffendingDecl A related decl to ReferringDecl that has an availability attribute corresponding to K attached to it. Note that this may not be the same as ReferringDecl, i.e. if an EnumDecl is annotated and we refer to a member EnumConstantDecl, ReferringDecl is the EnumConstantDecl and OffendingDecl is the EnumDecl.
Definition at line 310 of file SemaAvailability.cpp.
References clang::AR_Available, clang::AR_Deprecated, clang::AR_NotYetIntroduced, clang::AR_Unavailable, clang::Sema::Context, createAttributeInsertion(), clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Sema::Diag(), findEnclosingDeclToAnnotate(), clang::Sema::getASTContext(), clang::Decl::getAttr(), getAttrForPlatform(), clang::CharSourceRange::getCharRange(), clang::NamedDecl::getDeclName(), clang::AvailabilityAttr::getIntroduced(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::Sema::getLocForEndOfToken(), clang::NamedDecl::getMostRecentDecl(), clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::TargetInfo::getPlatformMinVersion(), clang::TargetInfo::getPlatformName(), clang::AvailabilityAttr::getPlatformNameSourceSpelling(), clang::Sema::getPreprocessor(), clang::AvailabilityAttr::getPrettyPlatformName(), clang::Decl::getPreviousDecl(), clang::Sema::getSourceManager(), clang::ASTContext::getTargetInfo(), clang::Decl::getVersionIntroduced(), clang::UnavailableAttr::IR_ARCFieldWithOwnership, clang::UnavailableAttr::IR_ARCForbiddenConversion, clang::UnavailableAttr::IR_ARCForbiddenType, clang::UnavailableAttr::IR_ARCInitReturnsUnrelated, clang::UnavailableAttr::IR_ForbiddenWeak, clang::UnavailableAttr::IR_None, clang::Attr::isInherited(), clang::SourceManager::isInSystemHeader(), clang::Preprocessor::isMacroDefined(), clang::CharSourceRange::isValid(), shouldDiagnoseAvailabilityByDefault(), ShouldDiagnoseAvailabilityInContext(), tryParseObjCMethodName(), and clang::Warning.
Referenced by EmitAvailabilityWarning(), and clang::Sema::handleDelayedAvailabilityCheck().
EmitAvailabilityWarning()
static void EmitAvailabilityWarning (Sema & S, AvailabilityResult AR, const NamedDecl * ReferringDecl, const NamedDecl * OffendingDecl, StringRef Message, ArrayRef< SourceLocation > Locs, const ObjCInterfaceDecl * UnknownObjCClass, const ObjCPropertyDecl * ObjCProperty, bool ObjCPropertyAccess) static
Definition at line 554 of file SemaAvailability.cpp.
References clang::Sema::DelayedDiagnostics::add(), clang::cast(), clang::Sema::DelayedDiagnostics, DoEmitAvailabilityWarning(), clang::Sema::getCurLexicalContext(), clang::sema::DelayedDiagnostic::makeAvailability(), and clang::Sema::DelayedDiagnostics::shouldDelayDiagnostics().
Referenced by clang::Sema::DiagnoseAvailabilityOfDecl().
findEnclosingDeclToAnnotate()
static NamedDecl * findEnclosingDeclToAnnotate (Decl * OrigCtx) static
Definition at line 203 of file SemaAvailability.cpp.
References clang::cast().
Referenced by DoEmitAvailabilityWarning().
getAttrForPlatform()
static const AvailabilityAttr * getAttrForPlatform (ASTContext & Context, const Decl * D) static
Definition at line 26 of file SemaAvailability.cpp.
References clang::Decl::attrs(), clang::ASTContext::getLangOpts(), clang::TargetInfo::getPlatformName(), and clang::ASTContext::getTargetInfo().
Referenced by DoEmitAvailabilityWarning(), and ShouldDiagnoseAvailabilityInContext().
shouldDiagnoseAvailabilityByDefault()
static bool shouldDiagnoseAvailabilityByDefault (const ASTContext & Context, const VersionTuple & DeploymentVersion, const VersionTuple & DeclVersion) static
Definition at line 178 of file SemaAvailability.cpp.
References clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
Referenced by DoEmitAvailabilityWarning().
ShouldDiagnoseAvailabilityInContext()
static bool ShouldDiagnoseAvailabilityInContext (Sema & S, AvailabilityResult K, VersionTuple DeclVersion, Decl * Ctx, const NamedDecl * OffendingDecl) static
whether we should emit a diagnostic for K and DeclVersion in the context of Ctx.
For example, we should emit an unavailable diagnostic in a deprecated context, but not the other way around.
Definition at line 120 of file SemaAvailability.cpp.
References clang::AR_Available, clang::AR_Deprecated, clang::AR_NotYetIntroduced, clang::AR_Unavailable, clang::C, clang::Sema::Context, getAttrForPlatform(), and clang::Decl::getDeclContext().
Referenced by DoEmitAvailabilityWarning().
ShouldDiagnoseAvailabilityOfDecl()
static std::pair< AvailabilityResult, const NamedDecl * > ShouldDiagnoseAvailabilityOfDecl (Sema & S, const NamedDecl * D, std::string * Message, ObjCInterfaceDecl * ClassReceiver) static
The diagnostic we should emit for D, and the declaration that originated it, or AR_Available.
Parameters
D The declaration to check.
Message If non-null, this will be populated with the message from the availability attribute that is selected.
ClassReceiver If we're checking the the method of a class message send, the class. Otherwise nullptr.
Definition at line 63 of file SemaAvailability.cpp.
References clang::AR_Available, clang::Sema::getASTContext(), clang::Decl::getAvailability(), clang::ObjCInterfaceDecl::lookupInstanceMethod(), clang::Sema::NSAPIObj, and clang::Result.
Referenced by clang::Sema::DiagnoseAvailabilityOfDecl().
tryParseObjCMethodName()
static Optional< unsigned > tryParseObjCMethodName (StringRef Name, SmallVectorImpl< StringRef > & SlotNames, const LangOptions & LangOpts) static
Tries to parse a string as ObjC method name.
Parameters
Name The string to parse. Expected to originate from availability attribute argument.
SlotNames The vector that will be populated with slot names. In case of unsuccessful parsing can contain invalid data.
Returns
A number of method parameters if parsing was successful, None otherwise.
Definition at line 247 of file SemaAvailability.cpp.
References clang::isValidIdentifier(), and clang::None.
Referenced by DoEmitAvailabilityWarning().