clang: lib/Basic/SourceLocation.cpp File Reference
SourceLocation.cpp File Reference
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/PrettyStackTrace.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <string>
#include <utility>
Functions
static PresumedLoc PrintDifference (raw_ostream &OS, const SourceManager &SM, SourceLocation Loc, PresumedLoc Previous)
Function Documentation
PrintDifference()
static PresumedLoc PrintDifference (raw_ostream & OS, const SourceManager & SM, SourceLocation Loc, PresumedLoc Previous) static
Definition at line 106 of file SourceLocation.cpp.
References clang::PresumedLoc::getColumn(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::SourceLocation::isFileID(), clang::PresumedLoc::isInvalid(), Previous, PrintDifference(), and SM.
Referenced by clang::SourceRange::print(), and PrintDifference().