clang: clang::ObjCMethodList Struct Reference
clang::ObjCMethodList Struct Reference
a linked list of methods with the same selector name but different signatures.
#include "clang/Sema/ObjCMethodList.h"
Public Member Functions
ObjCMethodList ()
ObjCMethodList (ObjCMethodDecl *M)
ObjCMethodList (const ObjCMethodList &L)
ObjCMethodList & operator= (const ObjCMethodList &L)
ObjCMethodList * getNext () const
unsigned getBits () const
void setNext (ObjCMethodList *L)
void setBits (unsigned B)
ObjCMethodDecl * getMethod () const
void setMethod (ObjCMethodDecl *M)
bool hasMoreThanOneDecl () const
void setHasMoreThanOneDecl (bool B)
Public Attributes
llvm::PointerIntPair< ObjCMethodDecl *, 1 > MethodAndHasMoreThanOneDecl
If there is more than one decl with this signature.
llvm::PointerIntPair< ObjCMethodList *, 2 > NextAndExtraBits
The next list object and 2 bits for extra info.
Detailed Description
a linked list of methods with the same selector name but different signatures.
Definition at line 25 of file ObjCMethodList.h.
Constructor & Destructor Documentation
ObjCMethodList() [1/3]
clang::ObjCMethodList::ObjCMethodList () inline
Definition at line 32 of file ObjCMethodList.h.
ObjCMethodList() [2/3]
clang::ObjCMethodList::ObjCMethodList (ObjCMethodDecl * M) inline
Definition at line 33 of file ObjCMethodList.h.
ObjCMethodList() [3/3]
clang::ObjCMethodList::ObjCMethodList (const ObjCMethodList & L) inline
Definition at line 35 of file ObjCMethodList.h.
Member Function Documentation
getBits()
unsigned clang::ObjCMethodList::getBits () const inline
Definition at line 46 of file ObjCMethodList.h.
References NextAndExtraBits.
getMethod()
ObjCMethodDecl * clang::ObjCMethodList::getMethod () const inline
Definition at line 50 of file ObjCMethodList.h.
References MethodAndHasMoreThanOneDecl.
Referenced by HelperToDiagnoseMismatchedMethodsInGlobalPool(), and LookupDirectMethodInMethodList().
getNext()
ObjCMethodList * clang::ObjCMethodList::getNext () const inline
Definition at line 45 of file ObjCMethodList.h.
References NextAndExtraBits.
Referenced by clang::Sema::CollectMultipleMethodsInGlobalPool(), HelperToDiagnoseMismatchedMethodsInGlobalPool(), LookupDirectMethodInMethodList(), and clang::Sema::SelectorsForTypoCorrection().
hasMoreThanOneDecl()
bool clang::ObjCMethodList::hasMoreThanOneDecl () const inline
Definition at line 57 of file ObjCMethodList.h.
References MethodAndHasMoreThanOneDecl.
Referenced by clang::Sema::AreMultipleMethodsInGlobalPool().
operator=()
ObjCMethodList & clang::ObjCMethodList::operator= (const ObjCMethodList & L) inline
Definition at line 39 of file ObjCMethodList.h.
References MethodAndHasMoreThanOneDecl, and NextAndExtraBits.
setBits()
void clang::ObjCMethodList::setBits (unsigned B) inline
Definition at line 48 of file ObjCMethodList.h.
References NextAndExtraBits.
setHasMoreThanOneDecl()
void clang::ObjCMethodList::setHasMoreThanOneDecl (bool B) inline
Definition at line 60 of file ObjCMethodList.h.
References MethodAndHasMoreThanOneDecl.
setMethod()
void clang::ObjCMethodList::setMethod (ObjCMethodDecl * M) inline
Definition at line 53 of file ObjCMethodList.h.
References MethodAndHasMoreThanOneDecl.
Referenced by clang::Sema::addMethodToGlobalList().
setNext()
void clang::ObjCMethodList::setNext (ObjCMethodList * L) inline
Definition at line 47 of file ObjCMethodList.h.
References NextAndExtraBits.
Referenced by clang::Sema::addMethodToGlobalList().
Member Data Documentation
MethodAndHasMoreThanOneDecl
llvm::PointerIntPair<ObjCMethodDecl *, 1> clang::ObjCMethodList::MethodAndHasMoreThanOneDecl
If there is more than one decl with this signature.
Definition at line 28 of file ObjCMethodList.h.
Referenced by getMethod(), hasMoreThanOneDecl(), operator=(), setHasMoreThanOneDecl(), and setMethod().
NextAndExtraBits
llvm::PointerIntPair<ObjCMethodList *, 2> clang::ObjCMethodList::NextAndExtraBits
The next list object and 2 bits for extra info.
Definition at line 30 of file ObjCMethodList.h.
Referenced by getBits(), getNext(), operator=(), setBits(), and setNext().
The documentation for this struct was generated from the following file:
include/clang/Sema/ObjCMethodList.h