clang: clang::CopiedTypeVisitor< Derived, IsMove, RetTy > Struct Template Reference
clang::CopiedTypeVisitor< Derived, IsMove, RetTy > Struct Template Reference
#include "clang/AST/NonTrivialTypeVisitor.h"
Public Member Functions
template<class... Ts>
RetTy visit (QualType FT, Ts &&... Args)
template<class... Ts>
RetTy visitWithKind (QualType::PrimitiveCopyKind PCK, QualType FT, Ts &&... Args)
Derived & asDerived ()
Detailed Description
template<class Derived, bool IsMove, class RetTy = void>
struct clang::CopiedTypeVisitor< Derived, IsMove, RetTy >
Definition at line 78 of file NonTrivialTypeVisitor.h.
Member Function Documentation
asDerived()
template<class Derived , bool IsMove, class RetTy = void> Derived & clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::asDerived () inline
Definition at line 107 of file NonTrivialTypeVisitor.h.
Referenced by clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visit(), and clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visitWithKind().
visit()
template<class Derived , bool IsMove, class RetTy = void> template<class... Ts> RetTy clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visit (QualType FT, Ts &&... Args) inline
Definition at line 79 of file NonTrivialTypeVisitor.h.
References clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::asDerived(), clang::QualType::isNonTrivialToPrimitiveCopy(), and clang::QualType::isNonTrivialToPrimitiveDestructiveMove().
visitWithKind()
template<class Derived , bool IsMove, class RetTy = void> template<class... Ts> RetTy clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::visitWithKind (QualType::PrimitiveCopyKind PCK, QualType FT, Ts &&... Args) inline
Definition at line 87 of file NonTrivialTypeVisitor.h.
References clang::CopiedTypeVisitor< Derived, IsMove, RetTy >::asDerived(), clang::QualType::PCK_ARCStrong, clang::QualType::PCK_ARCWeak, clang::QualType::PCK_Struct, clang::QualType::PCK_Trivial, and clang::QualType::PCK_VolatileTrivial.
The documentation for this struct was generated from the following file:
include/clang/AST/NonTrivialTypeVisitor.h