clang: LoopState Struct Reference
LoopState Struct Reference
Public Member Functions
bool isUnrolled () const
unsigned getMaxStep () const
const Stmt * getLoopStmt () const
const LocationContext * getLocationContext () const
bool operator== (const LoopState &X) const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static LoopState getNormal (const Stmt *S, const LocationContext *L, unsigned N)
static LoopState getUnrolled (const Stmt *S, const LocationContext *L, unsigned N)
Detailed Description
Definition at line 27 of file LoopUnrolling.cpp.
Member Function Documentation
getLocationContext()
const LocationContext * LoopState::getLocationContext () const inline
Definition at line 48 of file LoopUnrolling.cpp.
getLoopStmt()
const Stmt * LoopState::getLoopStmt () const inline
Definition at line 47 of file LoopUnrolling.cpp.
getMaxStep()
unsigned LoopState::getMaxStep () const inline
Definition at line 46 of file LoopUnrolling.cpp.
getNormal()
static LoopState LoopState::getNormal (const Stmt * S, const LocationContext * L, unsigned N) inline static
Definition at line 37 of file LoopUnrolling.cpp.
References N.
Referenced by clang::ento::updateLoopStack().
getUnrolled()
static LoopState LoopState::getUnrolled (const Stmt * S, const LocationContext * L, unsigned N) inline static
Definition at line 41 of file LoopUnrolling.cpp.
References N.
Referenced by clang::ento::updateLoopStack().
isUnrolled()
bool LoopState::isUnrolled () const inline
Definition at line 45 of file LoopUnrolling.cpp.
operator==()
bool LoopState::operator== (const LoopState & X) const inline
Definition at line 49 of file LoopUnrolling.cpp.
References X().
Profile()
void LoopState::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 52 of file LoopUnrolling.cpp.
The documentation for this struct was generated from the following file:
lib/StaticAnalyzer/Core/LoopUnrolling.cpp