clang: clang::NormalizedConstraint Struct Reference
clang::NormalizedConstraint Struct Reference
A normalized constraint, as defined in C++ [temp.constr.normal], is either an atomic constraint, a conjunction of normalized constraints or a disjunction of normalized constraints.
#include "clang/Sema/SemaConcept.h"
Public Types
enum CompoundConstraintKind { CCK_Conjunction , CCK_Disjunction }
using CompoundConstraint
Public Member Functions
NormalizedConstraint (AtomicConstraint *C)
NormalizedConstraint (ASTContext &C, NormalizedConstraint LHS, NormalizedConstraint RHS, CompoundConstraintKind Kind)
NormalizedConstraint (ASTContext &C, const NormalizedConstraint &Other)
NormalizedConstraint (NormalizedConstraint &&Other)
NormalizedConstraint & operator= (const NormalizedConstraint &Other)=delete
NormalizedConstraint & operator= (NormalizedConstraint &&Other)
CompoundConstraintKind getCompoundKind () const
bool isAtomic () const
NormalizedConstraint & getLHS () const
NormalizedConstraint & getRHS () const
AtomicConstraint * getAtomicConstraint () const
Public Attributes
llvm::PointerUnion< AtomicConstraint *, CompoundConstraint > Constraint
Friends
class Sema
Detailed Description
A normalized constraint, as defined in C++ [temp.constr.normal], is either an atomic constraint, a conjunction of normalized constraints or a disjunction of normalized constraints.
Definition at line 82 of file SemaConcept.h.
Member Typedef Documentation
CompoundConstraint
using clang::NormalizedConstraint::CompoundConstraint
Initial value:
 llvm::PointerIntPair<
      std::pair<NormalizedConstraint, NormalizedConstraint> *, 1,
      CompoundConstraintKind>
Definition at line 87 of file SemaConcept.h.
Member Enumeration Documentation
CompoundConstraintKind
enum clang::NormalizedConstraint::CompoundConstraintKind
Enumerator
CCK_Conjunction
CCK_Disjunction
Definition at line 85 of file SemaConcept.h.
Constructor & Destructor Documentation
NormalizedConstraint() [1/4]
clang::NormalizedConstraint::NormalizedConstraint (AtomicConstraint * C) inline
Definition at line 93 of file SemaConcept.h.
NormalizedConstraint() [2/4]
clang::NormalizedConstraint::NormalizedConstraint (ASTContext & C, NormalizedConstraint LHS, NormalizedConstraint RHS, CompoundConstraintKind Kind) inline
Definition at line 94 of file SemaConcept.h.
NormalizedConstraint() [3/4]
clang::NormalizedConstraint::NormalizedConstraint (ASTContext & C, const NormalizedConstraint & Other) inline
Definition at line 100 of file SemaConcept.h.
References getAtomicConstraint(), getCompoundKind(), getLHS(), getRHS(), and isAtomic().
NormalizedConstraint() [4/4]
clang::NormalizedConstraint::NormalizedConstraint (NormalizedConstraint && Other) inline
Definition at line 111 of file SemaConcept.h.
Member Function Documentation
getAtomicConstraint()
AtomicConstraint * clang::NormalizedConstraint::getAtomicConstraint () const inline
Definition at line 141 of file SemaConcept.h.
Referenced by makeCNF(), makeDNF(), and NormalizedConstraint().
getCompoundKind()
CompoundConstraintKind clang::NormalizedConstraint::getCompoundKind () const inline
Definition at line 124 of file SemaConcept.h.
Referenced by makeCNF(), makeDNF(), and NormalizedConstraint().
getLHS()
NormalizedConstraint & clang::NormalizedConstraint::getLHS () const inline
Definition at line 131 of file SemaConcept.h.
Referenced by makeCNF(), makeDNF(), and NormalizedConstraint().
getRHS()
NormalizedConstraint & clang::NormalizedConstraint::getRHS () const inline
Definition at line 136 of file SemaConcept.h.
Referenced by makeCNF(), makeDNF(), and NormalizedConstraint().
isAtomic()
bool clang::NormalizedConstraint::isAtomic () const inline
Definition at line 129 of file SemaConcept.h.
Referenced by makeCNF(), makeDNF(), and NormalizedConstraint().
operator=() [1/2]
NormalizedConstraint & clang::NormalizedConstraint::operator= (const NormalizedConstraint & Other) delete
operator=() [2/2]
NormalizedConstraint & clang::NormalizedConstraint::operator= (NormalizedConstraint && Other) inline
Definition at line 116 of file SemaConcept.h.
References Constraint.
Friends And Related Symbol Documentation
Sema
friend class Sema friend
Definition at line 83 of file SemaConcept.h.
Member Data Documentation
Constraint
llvm::PointerUnion<AtomicConstraint *, CompoundConstraint> clang::NormalizedConstraint::Constraint
Definition at line 91 of file SemaConcept.h.
Referenced by operator=().
The documentation for this struct was generated from the following files:
include/clang/Sema/SemaConcept.h
lib/Sema/SemaConcept.cpp