clang: clang::DeclaratorChunk::MemberPointerTypeInfo Struct Reference
clang::DeclaratorChunk::MemberPointerTypeInfo Struct Reference
#include "clang/Sema/DeclSpec.h"
Public Member Functions
CXXScopeSpec & Scope ()
const CXXScopeSpec & Scope () const
void destroy ()
Public Attributes
unsigned TypeQuals: 5
The type qualifiers: const/volatile/restrict/__unaligned/_Atomic.
SourceLocation StarLoc
Location of the '*' token.
char ScopeMem [sizeof(CXXScopeSpec)]
Detailed Description
Definition at line 1522 of file DeclSpec.h.
Member Function Documentation
destroy()
void clang::DeclaratorChunk::MemberPointerTypeInfo::destroy () inline
Definition at line 1536 of file DeclSpec.h.
References Scope().
Referenced by clang::DeclaratorChunk::destroy().
Scope() [1/2]
CXXScopeSpec & clang::DeclaratorChunk::MemberPointerTypeInfo::Scope () inline
Definition at line 1530 of file DeclSpec.h.
References ScopeMem.
Referenced by clang::Sema::containsUnexpandedParameterPacks(), destroy(), GetFullTypeForDeclarator(), and RebuildDeclaratorInCurrentInstantiation().
Scope() [2/2]
const CXXScopeSpec & clang::DeclaratorChunk::MemberPointerTypeInfo::Scope () const inline
Definition at line 1533 of file DeclSpec.h.
References ScopeMem.
Member Data Documentation
ScopeMem
char clang::DeclaratorChunk::MemberPointerTypeInfo::ScopeMem[sizeof(CXXScopeSpec)]
Definition at line 1529 of file DeclSpec.h.
Referenced by clang::DeclaratorChunk::getMemberPointer(), Scope(), and Scope().
StarLoc
SourceLocation clang::DeclaratorChunk::MemberPointerTypeInfo::StarLoc
Location of the '*' token.
Definition at line 1526 of file DeclSpec.h.
Referenced by clang::DeclaratorChunk::getMemberPointer().
TypeQuals
unsigned clang::DeclaratorChunk::MemberPointerTypeInfo::TypeQuals
The type qualifiers: const/volatile/restrict/__unaligned/_Atomic.
Definition at line 1524 of file DeclSpec.h.
Referenced by GetFullTypeForDeclarator(), and clang::DeclaratorChunk::getMemberPointer().
The documentation for this struct was generated from the following file:
include/clang/Sema/DeclSpec.h