clang: clang::ASTTemplateArgumentListInfo Struct Reference
clang::ASTTemplateArgumentListInfo Struct Reference final
Represents an explicit template argument list in C++, e.g., the "<int>" in "sort<int>".
#include "clang/AST/TemplateBase.h"
Public Member Functions
SourceLocation getLAngleLoc () const
SourceLocation getRAngleLoc () const
const TemplateArgumentLoc * getTemplateArgs () const
Retrieve the template arguments.
unsigned getNumTemplateArgs () const
llvm::ArrayRef< TemplateArgumentLoc > arguments () const
const TemplateArgumentLoc & operator[] (unsigned I) const
Static Public Member Functions
static const ASTTemplateArgumentListInfo * Create (const ASTContext &C, const TemplateArgumentListInfo &List)
Public Attributes
SourceLocation LAngleLoc
The source location of the left angle bracket ('<').
SourceLocation RAngleLoc
The source location of the right angle bracket ('>').
unsigned NumTemplateArgs
The number of template arguments in TemplateArgs.
Friends
class ASTNodeImporter
Detailed Description
Represents an explicit template argument list in C++, e.g., the "<int>" in "sort<int>".
This is safe to be used inside an AST node, in contrast with TemplateArgumentListInfo.
Definition at line 611 of file TemplateBase.h.
Member Function Documentation
arguments()
llvm::ArrayRef< TemplateArgumentLoc > clang::ASTTemplateArgumentListInfo::arguments () const inline
Definition at line 639 of file TemplateBase.h.
References getNumTemplateArgs(), and getTemplateArgs().
Referenced by clang::computeDependence(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpASTTemplateArgumentListInfo(), clang::TypeConstraint::print(), substituteParameterMappings(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr().
Create()
const ASTTemplateArgumentListInfo * ASTTemplateArgumentListInfo::Create (const ASTContext & C, const TemplateArgumentListInfo & List) static
Definition at line 533 of file TemplateBase.cpp.
References clang::C.
Referenced by clang::Sema::AttachTypeConstraint(), clang::Sema::CheckConceptTemplateId(), clang::ClassScopeFunctionSpecializationDecl::Create(), clang::ClassTemplatePartialSpecializationDecl::Create(), clang::FunctionTemplateSpecializationInfo::Create(), clang::VarTemplatePartialSpecializationDecl::Create(), clang::ASTRecordReader::readASTTemplateArgumentListInfo(), and clang::ASTNodeImporter::VisitTemplateTypeParmDecl().
getLAngleLoc()
SourceLocation clang::ASTTemplateArgumentListInfo::getLAngleLoc () const inline
Definition at line 630 of file TemplateBase.h.
References LAngleLoc.
getNumTemplateArgs()
unsigned clang::ASTTemplateArgumentListInfo::getNumTemplateArgs () const inline
Definition at line 637 of file TemplateBase.h.
References NumTemplateArgs.
Referenced by arguments().
getRAngleLoc()
SourceLocation clang::ASTTemplateArgumentListInfo::getRAngleLoc () const inline
Definition at line 631 of file TemplateBase.h.
References RAngleLoc.
getTemplateArgs()
const TemplateArgumentLoc * clang::ASTTemplateArgumentListInfo::getTemplateArgs () const inline
Retrieve the template arguments.
Definition at line 634 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), arguments(), FinishTemplateArgumentDeduction(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), operator[](), and clang::Sema::SubstParmVarDecl().
operator[]()
const TemplateArgumentLoc & clang::ASTTemplateArgumentListInfo::operator[] (unsigned I) const inline
Definition at line 643 of file TemplateBase.h.
References getTemplateArgs().
Friends And Related Symbol Documentation
ASTNodeImporter
friend class ASTNodeImporter friend
Definition at line 615 of file TemplateBase.h.
Member Data Documentation
LAngleLoc
SourceLocation clang::ASTTemplateArgumentListInfo::LAngleLoc
The source location of the left angle bracket ('<').
Definition at line 622 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), FinishTemplateArgumentDeduction(), getLAngleLoc(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
NumTemplateArgs
unsigned clang::ASTTemplateArgumentListInfo::NumTemplateArgs
The number of template arguments in TemplateArgs.
Definition at line 628 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), diagnoseUnsatisfiedRequirement(), FinishTemplateArgumentDeduction(), getNumTemplateArgs(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), substituteParameterMappings(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
RAngleLoc
SourceLocation clang::ASTTemplateArgumentListInfo::RAngleLoc
The source location of the right angle bracket ('>').
Definition at line 625 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), FinishTemplateArgumentDeduction(), clang::ConceptSpecializationExpr::getEndLoc(), getRAngleLoc(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::Sema::SubstParmVarDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
The documentation for this struct was generated from the following files:
include/clang/AST/TemplateBase.h
lib/AST/TemplateBase.cpp