clang: clang::ento::iterator::IteratorPosition Struct Reference
clang::ento::iterator::IteratorPosition Struct Reference
#include "/root/llvm-project/clang/lib/StaticAnalyzer/Checkers/Iterator.h"
Public Member Functions
const MemRegion * getContainer () const
bool isValid () const
SymbolRef getOffset () const
IteratorPosition invalidate () const
IteratorPosition setTo (SymbolRef NewOf) const
IteratorPosition reAssign (const MemRegion *NewCont) const
bool operator== (const IteratorPosition &X) const
bool operator!= (const IteratorPosition &X) const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static IteratorPosition getPosition (const MemRegion *C, SymbolRef Of)
Detailed Description
Definition at line 26 of file Iterator.h.
Member Function Documentation
getContainer()
const MemRegion * clang::ento::iterator::IteratorPosition::getContainer () const inline
Definition at line 42 of file Iterator.h.
getOffset()
SymbolRef clang::ento::iterator::IteratorPosition::getOffset () const inline
Definition at line 44 of file Iterator.h.
References Offset.
getPosition()
static IteratorPosition clang::ento::iterator::IteratorPosition::getPosition (const MemRegion * C, SymbolRef Of) inline static
Definition at line 50 of file Iterator.h.
References clang::C.
Referenced by clang::ento::iterator::createIteratorPosition().
invalidate()
IteratorPosition clang::ento::iterator::IteratorPosition::invalidate () const inline
Definition at line 46 of file Iterator.h.
References Offset.
isValid()
bool clang::ento::iterator::IteratorPosition::isValid () const inline
Definition at line 43 of file Iterator.h.
operator!=()
bool clang::ento::iterator::IteratorPosition::operator!= (const IteratorPosition & X) const inline
Definition at line 66 of file Iterator.h.
References Offset, and X().
operator==()
bool clang::ento::iterator::IteratorPosition::operator== (const IteratorPosition & X) const inline
Definition at line 62 of file Iterator.h.
References Offset, and X().
Profile()
void clang::ento::iterator::IteratorPosition::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 70 of file Iterator.h.
References Offset.
reAssign()
IteratorPosition clang::ento::iterator::IteratorPosition::reAssign (const MemRegion * NewCont) const inline
Definition at line 58 of file Iterator.h.
References Offset.
setTo()
IteratorPosition clang::ento::iterator::IteratorPosition::setTo (SymbolRef NewOf) const inline
Definition at line 54 of file Iterator.h.
The documentation for this struct was generated from the following file:
lib/StaticAnalyzer/Checkers/Iterator.h