clang: clang::CodeGen::CodeGenFunction::JumpDest Struct Reference
clang::CodeGen::CodeGenFunction::JumpDest Struct Reference
A jump destination is an abstract label, branching to which may require a jump out through normal cleanups.
#include "/root/llvm-project/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
JumpDest ()
JumpDest (llvm::BasicBlock *Block, EHScopeStack::stable_iterator Depth, unsigned Index)
bool isValid () const
llvm::BasicBlock * getBlock () const
EHScopeStack::stable_iterator getScopeDepth () const
unsigned getDestIndex () const
void setScopeDepth (EHScopeStack::stable_iterator depth)
Detailed Description
A jump destination is an abstract label, branching to which may require a jump out through normal cleanups.
Definition at line 242 of file CodeGenFunction.h.
Constructor & Destructor Documentation
JumpDest() [1/2]
clang::CodeGen::CodeGenFunction::JumpDest::JumpDest () inline
Definition at line 243 of file CodeGenFunction.h.
JumpDest() [2/2]
clang::CodeGen::CodeGenFunction::JumpDest::JumpDest (llvm::BasicBlock * Block, EHScopeStack::stable_iterator Depth, unsigned Index) inline
Definition at line 244 of file CodeGenFunction.h.
References clang::Block.
Member Function Documentation
getBlock()
llvm::BasicBlock * clang::CodeGen::CodeGenFunction::JumpDest::getBlock () const inline
Definition at line 250 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt().
getDestIndex()
unsigned clang::CodeGen::CodeGenFunction::JumpDest::getDestIndex () const inline
Definition at line 252 of file CodeGenFunction.h.
getScopeDepth()
EHScopeStack::stable_iterator clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth () const inline
Definition at line 251 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels().
isValid()
bool clang::CodeGen::CodeGenFunction::JumpDest::isValid () const inline
Definition at line 249 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGObjCRuntime::EmitTryCatchStmt().
setScopeDepth()
void clang::CodeGen::CodeGenFunction::JumpDest::setScopeDepth (EHScopeStack::stable_iterator depth) inline
Definition at line 255 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h