clang: clang::DeclarationNameInfo Struct Reference
clang::DeclarationNameInfo Struct Reference
DeclarationNameInfo - A collector data type for bundling together a DeclarationName and the correspnding source/type location info.
#include "clang/AST/DeclarationName.h"
Public Member Functions
DeclarationNameInfo ()=default
DeclarationNameInfo (DeclarationName Name, SourceLocation NameLoc)
DeclarationNameInfo (DeclarationName Name, SourceLocation NameLoc, DeclarationNameLoc LocInfo)
DeclarationName getName () const
getName - Returns the embedded declaration name.
void setName (DeclarationName N)
setName - Sets the embedded declaration name.
SourceLocation getLoc () const
getLoc - Returns the main location of the declaration name.
void setLoc (SourceLocation L)
setLoc - Sets the main location of the declaration name.
const DeclarationNameLoc & getInfo () const
DeclarationNameLoc & getInfo ()
void setInfo (const DeclarationNameLoc &Info)
TypeSourceInfo * getNamedTypeInfo () const
getNamedTypeInfo - Returns the source type info associated to the name.
void setNamedTypeInfo (TypeSourceInfo *TInfo)
setNamedTypeInfo - Sets the source type info associated to the name.
SourceRange getCXXOperatorNameRange () const
getCXXOperatorNameRange - Gets the range of the operator name (without the operator keyword).
void setCXXOperatorNameRange (SourceRange R)
setCXXOperatorNameRange - Sets the range of the operator name (without the operator keyword).
SourceLocation getCXXLiteralOperatorNameLoc () const
getCXXLiteralOperatorNameLoc - Returns the location of the literal operator name (not the operator keyword).
void setCXXLiteralOperatorNameLoc (SourceLocation Loc)
setCXXLiteralOperatorNameLoc - Sets the location of the literal operator name (not the operator keyword).
bool isInstantiationDependent () const
Determine whether this name involves a template parameter.
bool containsUnexpandedParameterPack () const
Determine whether this name contains an unexpanded parameter pack.
std::string getAsString () const
getAsString - Retrieve the human-readable string for this name.
void printName (raw_ostream &OS, PrintingPolicy Policy) const
printName - Print the human-readable name to a stream.
SourceLocation getBeginLoc () const
getBeginLoc - Retrieve the location of the first token.
SourceRange getSourceRange () const LLVM_READONLY
getSourceRange - The range of the declaration name.
SourceLocation getEndLoc () const LLVM_READONLY
Detailed Description
DeclarationNameInfo - A collector data type for bundling together a DeclarationName and the correspnding source/type location info.
Definition at line 690 of file DeclarationName.h.
Constructor & Destructor Documentation
DeclarationNameInfo() [1/3]
clang::DeclarationNameInfo::DeclarationNameInfo () default
DeclarationNameInfo() [2/3]
clang::DeclarationNameInfo::DeclarationNameInfo (DeclarationName Name, SourceLocation NameLoc) inline
Definition at line 705 of file DeclarationName.h.
DeclarationNameInfo() [3/3]
clang::DeclarationNameInfo::DeclarationNameInfo (DeclarationName Name, SourceLocation NameLoc, DeclarationNameLoc LocInfo) inline
Definition at line 708 of file DeclarationName.h.
Member Function Documentation
containsUnexpandedParameterPack()
bool DeclarationNameInfo::containsUnexpandedParameterPack () const
Determine whether this name contains an unexpanded parameter pack.
Definition at line 414 of file DeclarationName.cpp.
References clang::Type::containsUnexpandedParameterPack(), clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::getCXXNameType(), clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, clang::DeclarationNameLoc::NamedType, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, and clang::DeclarationNameLoc::NT::TInfo.
Referenced by clang::Sema::ActOnUsingDeclaration().
getAsString()
std::string DeclarationNameInfo::getAsString () const
getAsString - Retrieve the human-readable string for this name.
Definition at line 460 of file DeclarationName.cpp.
References clang::Result.
Referenced by buildUserDefinedMapperRef().
getBeginLoc()
SourceLocation clang::DeclarationNameInfo::getBeginLoc () const inline
getBeginLoc - Retrieve the location of the first token.
Definition at line 798 of file DeclarationName.h.
Referenced by clang::Sema::ActOnFriendFunctionDecl(), actOnOMPReductionKindClause(), clang::Sema::diagnoseExprIntendedAsTemplateName(), clang::ConceptSpecializationExpr::getBeginLoc(), clang::CXXDependentScopeMemberExpr::getBeginLoc(), clang::DeclRefExpr::getBeginLoc(), clang::UnresolvedLookupExpr::getBeginLoc(), clang::UnresolvedMemberExpr::getBeginLoc(), and clang::FunctionDecl::getReturnTypeSourceRange().
getCXXLiteralOperatorNameLoc()
SourceLocation clang::DeclarationNameInfo::getCXXLiteralOperatorNameLoc () const inline
getCXXLiteralOperatorNameLoc - Returns the location of the literal operator name (not the operator keyword).
Assumes it is a literal operator.
Definition at line 769 of file DeclarationName.h.
References clang::DeclarationNameLoc::CXXLiteralOperatorName, and clang::DeclarationNameLoc::CXXLitOpName::OpNameLoc.
Referenced by clang::Sema::BuildLiteralOperatorCall(), and clang::ASTNodeImporter::ImportDeclarationNameLoc().
getCXXOperatorNameRange()
SourceRange clang::DeclarationNameInfo::getCXXOperatorNameRange () const inline
getCXXOperatorNameRange - Gets the range of the operator name (without the operator keyword).
Assumes it is a (non-literal) operator.
Definition at line 749 of file DeclarationName.h.
References clang::DeclarationNameLoc::CXXOpName::BeginOpNameLoc, clang::DeclarationNameLoc::CXXOperatorName, and clang::DeclarationNameLoc::CXXOpName::EndOpNameLoc.
Referenced by clang::ASTNodeImporter::ImportDeclarationNameLoc(), and RebuildLambdaScopeInfo().
getEndLoc()
SourceLocation clang::DeclarationNameInfo::getEndLoc () const inline
Definition at line 805 of file DeclarationName.h.
References clang::SourceLocation::isValid().
Referenced by actOnOMPReductionKindClause(), clang::Sema::ActOnUsingDeclaration(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::CheckUsingDeclQualifier(), clang::ConceptSpecializationExpr::getEndLoc(), clang::CXXDependentScopeMemberExpr::getEndLoc(), clang::DeclRefExpr::getEndLoc(), clang::MemberExpr::getEndLoc(), clang::UnresolvedLookupExpr::getEndLoc(), and clang::UnresolvedMemberExpr::getEndLoc().
getInfo() [1/2]
DeclarationNameLoc & clang::DeclarationNameInfo::getInfo () inline
Definition at line 725 of file DeclarationName.h.
getInfo() [2/2]
const DeclarationNameLoc & clang::DeclarationNameInfo::getInfo () const inline
Definition at line 724 of file DeclarationName.h.
Referenced by clang::ASTRecordWriter::AddDeclarationNameInfo(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildLiteralOperatorCall(), and clang::Sema::GetNameFromUnqualifiedId().
getLoc()
SourceLocation clang::DeclarationNameInfo::getLoc () const inline
getLoc - Returns the main location of the declaration name.
Definition at line 719 of file DeclarationName.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnIdExpression(), clang::ASTRecordWriter::AddDeclarationNameInfo(), clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildFieldReferenceExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildMemberExpr(), clang::Sema::BuildMemberReferenceExpr(), BuildMSPropertyRefExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckConceptTemplateId(), clang::Sema::CheckTemplateTypeArgument(), clang::Sema::CheckVarTemplateId(), clang::Sema::CorrectTypo(), clang::Sema::CorrectTypoDelayed(), clang::Sema::DiagnoseClassNameShadow(), clang::Sema::diagnoseExprIntendedAsTemplateName(), diagnoseInstanceReference(), DiagnoseQualifiedMemberReference(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::ConceptReference::getConceptNameLoc(), clang::DependentScopeDeclRefExpr::getLocation(), clang::CXXDependentScopeMemberExpr::getMemberLoc(), clang::LookupResult::getNameLoc(), clang::OverloadExpr::getNameLoc(), recoverFromMSUnqualifiedLookup(), clang::Sema::SubstDeclarationNameInfo(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), clang::ASTNodeImporter::VisitDependentScopeDeclRefExpr(), clang::ASTNodeImporter::VisitMemberExpr(), clang::ASTNodeImporter::VisitUnresolvedUsingValueDecl(), and clang::ASTNodeImporter::VisitUsingDecl().
getName()
DeclarationName clang::DeclarationNameInfo::getName () const inline
getName - Returns the embedded declaration name.
Definition at line 713 of file DeclarationName.h.
Referenced by clang::Sema::ActOnCXXMemberDeclarator(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnExplicitInstantiation(), clang::Sema::ActOnFriendFunctionDecl(), clang::Sema::ActOnFunctionDeclarator(), clang::Sema::ActOnIdExpression(), clang::Sema::ActOnMemberAccessExpr(), actOnOMPReductionKindClause(), clang::Sema::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnTemplateName(), clang::Sema::ActOnUsingDeclaration(), clang::Sema::ActOnVariableDeclarator(), clang::ASTRecordWriter::AddDeclarationNameInfo(), buildMemberCall(), clang::Sema::BuildMemberReferenceExpr(), clang::Sema::BuildPossibleImplicitMemberExpr(), clang::Sema::BuildQualifiedDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), buildUserDefinedMapperRef(), clang::Sema::BuildUsingDeclaration(), clang::Sema::CheckFunctionOrTemplateParamDeclarator(), checkMappableExpressionList(), clang::Sema::CheckMicrosoftIfExistsSymbol(), checkNestingOfRegions(), clang::Sema::CheckTemplateTypeArgument(), clang::Sema::CheckUsingDeclQualifier(), clang::Sema::ClassifyName(), clang::Sema::CorrectTypo(), clang::Sema::CorrectTypoDelayed(), clang::CXXConstructorDecl::Create(), clang::CXXConversionDecl::Create(), clang::CXXDestructorDecl::Create(), CreateNewFunctionDecl(), clang::Sema::DiagnoseClassNameShadow(), clang::Sema::diagnoseExprIntendedAsTemplateName(), diagnoseInstanceReference(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::Sema::FindInstantiatedDecl(), clang::DependentScopeDeclRefExpr::getDeclName(), clang::LookupResult::getLookupName(), clang::CXXDependentScopeMemberExpr::getMember(), clang::OverloadExpr::getName(), clang::Sema::HandleDeclarator(), clang::ASTNodeImporter::ImportDeclarationNameLoc(), clang::ASTRecordReader::readDeclarationNameInfo(), recoverFromMSUnqualifiedLookup(), clang::Sema::SubstDeclarationNameInfo(), clang::TreeTransform< Derived >::TransformDeclarationNameInfo(), clang::transformOMPMappableExprListClause(), clang::ASTNodeImporter::VisitMemberExpr(), and clang::RecursiveASTVisitor< Derived >::VisitOMPDeclareSimdDeclAttr().
getNamedTypeInfo()
TypeSourceInfo * clang::DeclarationNameInfo::getNamedTypeInfo () const inline
getNamedTypeInfo - Returns the source type info associated to the name.
Assumes it is a constructor, destructor or conversion.
Definition at line 730 of file DeclarationName.h.
References clang::DeclarationNameLoc::NamedType, and clang::DeclarationNameLoc::NT::TInfo.
Referenced by clang::Sema::DiagnoseUnexpandedParameterPack(), clang::ASTNodeImporter::ImportDeclarationNameLoc(), and clang::TreeTransform< Derived >::TransformDeclarationNameInfo().
getSourceRange()
SourceRange clang::DeclarationNameInfo::getSourceRange () const inline
getSourceRange - The range of the declaration name.
Definition at line 801 of file DeclarationName.h.
Referenced by clang::Sema::ActOnDependentMemberExpr(), clang::Sema::CheckFriendAccess(), clang::Sema::CheckInheritingConstructorUsingDecl(), and clang::TypoCorrection::setCorrectionRange().
isInstantiationDependent()
bool DeclarationNameInfo::isInstantiationDependent () const
Determine whether this name involves a template parameter.
Definition at line 437 of file DeclarationName.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::getCXXNameType(), clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, clang::Type::isInstantiationDependentType(), clang::DeclarationNameLoc::NamedType, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, and clang::DeclarationNameLoc::NT::TInfo.
printName()
void DeclarationNameInfo::printName (raw_ostream & OS, PrintingPolicy Policy) const
printName - Print the human-readable name to a stream.
Definition at line 473 of file DeclarationName.cpp.
References clang::PrintingPolicy::adjustForCPlusPlus(), clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, clang::DeclarationNameLoc::NamedType, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, clang::DeclarationName::ObjCZeroArgSelector, clang::DeclarationName::print(), clang::PrintingPolicy::SuppressScope, and clang::DeclarationNameLoc::NT::TInfo.
Referenced by clang::operator<<(), and clang::TypeConstraint::print().
setCXXLiteralOperatorNameLoc()
void clang::DeclarationNameInfo::setCXXLiteralOperatorNameLoc (SourceLocation Loc) inline
setCXXLiteralOperatorNameLoc - Sets the location of the literal operator name (not the operator keyword).
Assumes it is a literal operator.
Definition at line 779 of file DeclarationName.h.
References clang::DeclarationNameLoc::CXXLiteralOperatorName, clang::SourceLocation::getRawEncoding(), and clang::DeclarationNameLoc::CXXLitOpName::OpNameLoc.
Referenced by clang::Sema::ActOnNumericConstant(), clang::Sema::ActOnStringLiteral(), BuildCookedLiteralOperatorCall(), clang::Sema::GetNameFromUnqualifiedId(), and clang::ASTNodeImporter::ImportDeclarationNameLoc().
setCXXOperatorNameRange()
void clang::DeclarationNameInfo::setCXXOperatorNameRange (SourceRange R) inline
setCXXOperatorNameRange - Sets the range of the operator name (without the operator keyword).
Assumes it is a C++ operator.
Definition at line 760 of file DeclarationName.h.
References clang::DeclarationNameLoc::CXXOpName::BeginOpNameLoc, clang::DeclarationNameLoc::CXXOperatorName, clang::DeclarationNameLoc::CXXOpName::EndOpNameLoc, clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), and clang::SourceLocation::getRawEncoding().
Referenced by clang::Sema::BuildCallToObjectOfClassType(), clang::Sema::CreateOverloadedArraySubscriptExpr(), and clang::ASTNodeImporter::ImportDeclarationNameLoc().
setInfo()
void clang::DeclarationNameInfo::setInfo (const DeclarationNameLoc & Info) inline
Definition at line 726 of file DeclarationName.h.
Referenced by clang::ASTRecordReader::readDeclarationNameInfo().
setLoc()
void clang::DeclarationNameInfo::setLoc (SourceLocation L) inline
setLoc - Sets the main location of the declaration name.
Definition at line 722 of file DeclarationName.h.
Referenced by checkMappableExpressionList(), clang::Sema::GetNameFromUnqualifiedId(), clang::Sema::LookupInlineAsmVarDeclField(), and clang::ASTRecordReader::readDeclarationNameInfo().
setName()
void clang::DeclarationNameInfo::setName (DeclarationName N) inline
setName - Sets the embedded declaration name.
Definition at line 716 of file DeclarationName.h.
References N.
Referenced by clang::TemplateDeclInstantiator::adjustForRewrite(), clang::Sema::BuildUsingDeclaration(), checkMappableExpressionList(), clang::Sema::GetNameFromUnqualifiedId(), clang::Sema::LookupInlineAsmVarDeclField(), clang::ASTRecordReader::readDeclarationNameInfo(), clang::LookupResult::setLookupName(), and clang::TreeTransform< Derived >::TransformDeclarationNameInfo().
setNamedTypeInfo()
void clang::DeclarationNameInfo::setNamedTypeInfo (TypeSourceInfo * TInfo) inline
setNamedTypeInfo - Sets the source type info associated to the name.
Assumes it is a constructor, destructor or conversion.
Definition at line 740 of file DeclarationName.h.
References clang::DeclarationNameLoc::NamedType, and clang::DeclarationNameLoc::NT::TInfo.
Referenced by clang::Sema::BuildUsingDeclaration(), clang::Sema::GetNameFromUnqualifiedId(), clang::ASTNodeImporter::ImportDeclarationNameLoc(), clang::TreeTransform< Derived >::RebuildCXXPseudoDestructorExpr(), and clang::TreeTransform< Derived >::TransformDeclarationNameInfo().
The documentation for this struct was generated from the following files:
include/clang/AST/DeclarationName.h
lib/AST/DeclarationName.cpp