clang: lib/AST/TextNodeDumper.cpp File Reference
TextNodeDumper.cpp File Reference
#include "clang/AST/TextNodeDumper.h"
#include "clang/AST/APValue.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/LocInfoType.h"
#include "clang/AST/Type.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TypeTraits.h"
#include <algorithm>
#include <utility>
#include "clang/AST/DeclNodes.inc"
#include "clang/Basic/AttrList.inc"
#include "clang/Basic/FPOptions.def"
Macros
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define DECL_RANGE(Base, First, Last)
#define LAST_DECL_RANGE(Base, First, Last)
#define ACCESSSPEC(Type, Base)
#define BLOCK(Type, Base)
#define CAPTURED(Type, Base)
#define CLASSSCOPEFUNCTIONSPECIALIZATION(Type, Base)
#define EMPTY(Type, Base)
#define EXPORT(Type, Base)
#define EXTERNCCONTEXT(Type, Base)
#define FILESCOPEASM(Type, Base)
#define FRIEND(Type, Base)
#define FRIENDTEMPLATE(Type, Base)
#define IMPORT(Type, Base)
#define LIFETIMEEXTENDEDTEMPORARY(Type, Base)
#define LINKAGESPEC(Type, Base)
#define NAMED(Type, Base)
#define LABEL(Type, Base)
#define NAMESPACE(Type, Base)
#define NAMESPACEALIAS(Type, Base)
#define OBJCCOMPATIBLEALIAS(Type, Base)
#define OBJCCONTAINER(Type, Base)
#define OBJCCATEGORY(Type, Base)
#define OBJCIMPL(Type, Base)
#define OBJCCATEGORYIMPL(Type, Base)
#define OBJCIMPLEMENTATION(Type, Base)
#define OBJCINTERFACE(Type, Base)
#define OBJCPROTOCOL(Type, Base)
#define OBJCMETHOD(Type, Base)
#define OBJCPROPERTY(Type, Base)
#define TEMPLATE(Type, Base)
#define BUILTINTEMPLATE(Type, Base)
#define CONCEPT(Type, Base)
#define REDECLARABLETEMPLATE(Type, Base)
#define CLASSTEMPLATE(Type, Base)
#define FUNCTIONTEMPLATE(Type, Base)
#define TYPEALIASTEMPLATE(Type, Base)
#define VARTEMPLATE(Type, Base)
#define TEMPLATETEMPLATEPARM(Type, Base)
#define TYPE(Type, Base)
#define TAG(Type, Base)
#define ENUM(Type, Base)
#define RECORD(Type, Base)
#define CXXRECORD(Type, Base)
#define CLASSTEMPLATESPECIALIZATION(Type, Base)
#define CLASSTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define TEMPLATETYPEPARM(Type, Base)
#define TYPEDEFNAME(Type, Base)
#define OBJCTYPEPARAM(Type, Base)
#define TYPEALIAS(Type, Base)
#define TYPEDEF(Type, Base)
#define UNRESOLVEDUSINGTYPENAME(Type, Base)
#define USING(Type, Base)
#define USINGDIRECTIVE(Type, Base)
#define USINGPACK(Type, Base)
#define USINGSHADOW(Type, Base)
#define CONSTRUCTORUSINGSHADOW(Type, Base)
#define VALUE(Type, Base)
#define BINDING(Type, Base)
#define DECLARATOR(Type, Base)
#define FIELD(Type, Base)
#define OBJCATDEFSFIELD(Type, Base)
#define OBJCIVAR(Type, Base)
#define FUNCTION(Type, Base)
#define CXXDEDUCTIONGUIDE(Type, Base)
#define CXXMETHOD(Type, Base)
#define CXXCONSTRUCTOR(Type, Base)
#define CXXCONVERSION(Type, Base)
#define CXXDESTRUCTOR(Type, Base)
#define MSPROPERTY(Type, Base)
#define NONTYPETEMPLATEPARM(Type, Base)
#define VAR(Type, Base)
#define DECOMPOSITION(Type, Base)
#define IMPLICITPARAM(Type, Base)
#define OMPCAPTUREDEXPR(Type, Base)
#define PARMVAR(Type, Base)
#define VARTEMPLATESPECIALIZATION(Type, Base)
#define VARTEMPLATEPARTIALSPECIALIZATION(Type, Base)
#define ENUMCONSTANT(Type, Base)
#define INDIRECTFIELD(Type, Base)
#define MSGUID(Type, Base)
#define OMPDECLAREMAPPER(Type, Base)
#define OMPDECLAREREDUCTION(Type, Base)
#define TEMPLATEPARAMOBJECT(Type, Base)
#define UNRESOLVEDUSINGVALUE(Type, Base)
#define OMPALLOCATE(Type, Base)
#define OMPREQUIRES(Type, Base)
#define OMPTHREADPRIVATE(Type, Base)
#define OBJCPROPERTYIMPL(Type, Base)
#define PRAGMACOMMENT(Type, Base)
#define PRAGMADETECTMISMATCH(Type, Base)
#define REQUIRESEXPRBODY(Type, Base)
#define STATICASSERT(Type, Base)
#define TRANSLATIONUNIT(Type, Base)
#define DECL_CONTEXT(DECL)
#define DECL_CONTEXT_BASE(DECL)
#define ATTR(X)
#define TYPE_ATTR(NAME)
#define STMT_ATTR(NAME)
#define DECL_OR_STMT_ATTR(NAME)
#define INHERITABLE_ATTR(NAME)
#define DECL_OR_TYPE_ATTR(NAME)
#define INHERITABLE_PARAM_ATTR(NAME)
#define PARAMETER_ABI_ATTR(NAME)
#define PRAGMA_SPELLING_ATTR(NAME)
#define OPTION(NAME, TYPE, WIDTH, PREVIOUS)
#define FLAG(fn, name)
Functions
static void dumpPreviousDeclImpl (raw_ostream &OS,...)
template<typename T >
static void dumpPreviousDeclImpl (raw_ostream &OS, const Mergeable< T > *D)
template<typename T >
static void dumpPreviousDeclImpl (raw_ostream &OS, const Redeclarable< T > *D)
static void dumpPreviousDecl (raw_ostream &OS, const Decl *D)
Dump the previous declaration in the redeclaration chain for a declaration, if any.
static double GetApproxValue (const llvm::APFloat &F)
static bool isSimpleAPValue (const APValue &Value)
True if the APValue Value can be folded onto the current line.
static void dumpBasePath (raw_ostream &OS, const CastExpr *Node)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
ACCESSSPEC
#define ACCESSSPEC (Type, Base)
Value:
DECL(Type, Base)
ATTR
#define ATTR (X)
Value:
  case attr::X:                                                                \
    OS << #X;                                                                  \
    break;
BINDING
#define BINDING (Type, Base)
Value:
VALUE(Type, Base)
BLOCK
#define BLOCK (Type, Base)
Value:
DECL(Type, Base)
BUILTINTEMPLATE
#define BUILTINTEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
CAPTURED
#define CAPTURED (Type, Base)
Value:
DECL(Type, Base)
CLASSSCOPEFUNCTIONSPECIALIZATION
#define CLASSSCOPEFUNCTIONSPECIALIZATION (Type, Base)
Value:
DECL(Type, Base)
CLASSTEMPLATE
#define CLASSTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
CLASSTEMPLATEPARTIALSPECIALIZATION
#define CLASSTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
CLASSTEMPLATESPECIALIZATION(Type, Base)
CLASSTEMPLATESPECIALIZATION
#define CLASSTEMPLATESPECIALIZATION (Type, Base)
Value:
CXXRECORD(Type, Base)
CONCEPT
#define CONCEPT (Type, Base)
Value:
TEMPLATE(Type, Base)
CONSTRUCTORUSINGSHADOW
#define CONSTRUCTORUSINGSHADOW (Type, Base)
Value:
USINGSHADOW(Type, Base)
CXXCONSTRUCTOR
#define CXXCONSTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXCONVERSION
#define CXXCONVERSION (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXDEDUCTIONGUIDE
#define CXXDEDUCTIONGUIDE (Type, Base)
Value:
FUNCTION(Type, Base)
CXXDESTRUCTOR
#define CXXDESTRUCTOR (Type, Base)
Value:
CXXMETHOD(Type, Base)
CXXMETHOD
#define CXXMETHOD (Type, Base)
Value:
FUNCTION(Type, Base)
CXXRECORD
#define CXXRECORD (Type, Base)
Value:
RECORD(Type, Base)
DECL
#define DECL (DERIVED, BASE)
Value:
  case Decl::DERIVED:                                                          \
    return dumpPreviousDeclImpl(OS, cast<DERIVED##Decl>(D));
DECL_CONTEXT
#define DECL_CONTEXT (DECL)
DECL_CONTEXT_BASE
#define DECL_CONTEXT_BASE (DECL)
Value:
DECL_CONTEXT(DECL)
DECL_OR_STMT_ATTR
#define DECL_OR_STMT_ATTR (NAME)
Value:
INHERITABLE_ATTR(NAME)
DECL_OR_TYPE_ATTR
#define DECL_OR_TYPE_ATTR (NAME)
Value:
INHERITABLE_ATTR(NAME)
DECL_RANGE
#define DECL_RANGE (Base, First, Last)
DECLARATOR
#define DECLARATOR (Type, Base)
Value:
VALUE(Type, Base)
DECOMPOSITION
#define DECOMPOSITION (Type, Base)
Value:
VAR(Type, Base)
EMPTY
#define EMPTY (Type, Base)
Value:
DECL(Type, Base)
ENUM
#define ENUM (Type, Base)
Value:
TAG(Type, Base)
ENUMCONSTANT
#define ENUMCONSTANT (Type, Base)
Value:
VALUE(Type, Base)
EXPORT
#define EXPORT (Type, Base)
Value:
DECL(Type, Base)
EXTERNCCONTEXT
#define EXTERNCCONTEXT (Type, Base)
Value:
DECL(Type, Base)
FIELD
#define FIELD (Type, Base)
Value:
DECLARATOR(Type, Base)
FILESCOPEASM
#define FILESCOPEASM (Type, Base)
Value:
DECL(Type, Base)
FLAG
#define FLAG (fn, name)
Value:
  if (D->fn())                                                                 \
    OS << " " #name;
Referenced by clang::TextNodeDumper::VisitCXXRecordDecl().
FRIEND
#define FRIEND (Type, Base)
Value:
DECL(Type, Base)
FRIENDTEMPLATE
#define FRIENDTEMPLATE (Type, Base)
Value:
DECL(Type, Base)
FUNCTION
#define FUNCTION (Type, Base)
Value:
DECLARATOR(Type, Base)
FUNCTIONTEMPLATE
#define FUNCTIONTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
IMPLICITPARAM
#define IMPLICITPARAM (Type, Base)
Value:
VAR(Type, Base)
IMPORT
#define IMPORT (Type, Base)
Value:
DECL(Type, Base)
INDIRECTFIELD
#define INDIRECTFIELD (Type, Base)
Value:
VALUE(Type, Base)
INHERITABLE_ATTR
#define INHERITABLE_ATTR (NAME)
Value:
ATTR(NAME)
INHERITABLE_PARAM_ATTR
#define INHERITABLE_PARAM_ATTR (NAME)
Value:
INHERITABLE_ATTR(NAME)
LABEL
#define LABEL (Type, Base)
Value:
NAMED(Type, Base)
LAST_DECL_RANGE
#define LAST_DECL_RANGE (Base, First, Last)
Value:
DECL_RANGE(Base, First, Last)
LIFETIMEEXTENDEDTEMPORARY
#define LIFETIMEEXTENDEDTEMPORARY (Type, Base)
Value:
DECL(Type, Base)
LINKAGESPEC
#define LINKAGESPEC (Type, Base)
Value:
DECL(Type, Base)
MSGUID
#define MSGUID (Type, Base)
Value:
VALUE(Type, Base)
MSPROPERTY
#define MSPROPERTY (Type, Base)
Value:
DECLARATOR(Type, Base)
NAMED
#define NAMED (Type, Base)
Value:
DECL(Type, Base)
NAMESPACE
#define NAMESPACE (Type, Base)
Value:
NAMED(Type, Base)
NAMESPACEALIAS
#define NAMESPACEALIAS (Type, Base)
Value:
NAMED(Type, Base)
NONTYPETEMPLATEPARM
#define NONTYPETEMPLATEPARM (Type, Base)
Value:
DECLARATOR(Type, Base)
OBJCATDEFSFIELD
#define OBJCATDEFSFIELD (Type, Base)
Value:
FIELD(Type, Base)
OBJCCATEGORY
#define OBJCCATEGORY (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCCATEGORYIMPL
#define OBJCCATEGORYIMPL (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCCOMPATIBLEALIAS
#define OBJCCOMPATIBLEALIAS (Type, Base)
Value:
NAMED(Type, Base)
OBJCCONTAINER
#define OBJCCONTAINER (Type, Base)
Value:
NAMED(Type, Base)
OBJCIMPL
#define OBJCIMPL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIMPLEMENTATION
#define OBJCIMPLEMENTATION (Type, Base)
Value:
OBJCIMPL(Type, Base)
OBJCINTERFACE
#define OBJCINTERFACE (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCIVAR
#define OBJCIVAR (Type, Base)
Value:
FIELD(Type, Base)
OBJCMETHOD
#define OBJCMETHOD (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTY
#define OBJCPROPERTY (Type, Base)
Value:
NAMED(Type, Base)
OBJCPROPERTYIMPL
#define OBJCPROPERTYIMPL (Type, Base)
Value:
DECL(Type, Base)
OBJCPROTOCOL
#define OBJCPROTOCOL (Type, Base)
Value:
OBJCCONTAINER(Type, Base)
OBJCTYPEPARAM
#define OBJCTYPEPARAM (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
OMPALLOCATE
#define OMPALLOCATE (Type, Base)
Value:
DECL(Type, Base)
OMPCAPTUREDEXPR
#define OMPCAPTUREDEXPR (Type, Base)
Value:
VAR(Type, Base)
OMPDECLAREMAPPER
#define OMPDECLAREMAPPER (Type, Base)
Value:
VALUE(Type, Base)
OMPDECLAREREDUCTION
#define OMPDECLAREREDUCTION (Type, Base)
Value:
VALUE(Type, Base)
OMPREQUIRES
#define OMPREQUIRES (Type, Base)
Value:
DECL(Type, Base)
OMPTHREADPRIVATE
#define OMPTHREADPRIVATE (Type, Base)
Value:
DECL(Type, Base)
OPTION
#define OPTION (NAME, TYPE, WIDTH, PREVIOUS)
Value:
  if (FPO.has##NAME##Override())                                               \
    OS << " " #NAME "=" << FPO.get##NAME##Override();
PARAMETER_ABI_ATTR
#define PARAMETER_ABI_ATTR (NAME)
Value:
INHERITABLE_PARAM_ATTR(NAME)
PARMVAR
#define PARMVAR (Type, Base)
Value:
VAR(Type, Base)
PRAGMA_SPELLING_ATTR
#define PRAGMA_SPELLING_ATTR (NAME)
PRAGMACOMMENT
#define PRAGMACOMMENT (Type, Base)
Value:
DECL(Type, Base)
PRAGMADETECTMISMATCH
#define PRAGMADETECTMISMATCH (Type, Base)
Value:
DECL(Type, Base)
RECORD
#define RECORD (Type, Base)
Value:
TAG(Type, Base)
REDECLARABLETEMPLATE
#define REDECLARABLETEMPLATE (Type, Base)
Value:
TEMPLATE(Type, Base)
REQUIRESEXPRBODY
#define REQUIRESEXPRBODY (Type, Base)
Value:
DECL(Type, Base)
STATICASSERT
#define STATICASSERT (Type, Base)
Value:
DECL(Type, Base)
STMT_ATTR
#define STMT_ATTR (NAME)
Value:
ATTR(NAME)
TAG
#define TAG (Type, Base)
Value:
TYPE(Type, Base)
TEMPLATE
#define TEMPLATE (Type, Base)
Value:
NAMED(Type, Base)
TEMPLATEPARAMOBJECT
#define TEMPLATEPARAMOBJECT (Type, Base)
Value:
VALUE(Type, Base)
TEMPLATETEMPLATEPARM
#define TEMPLATETEMPLATEPARM (Type, Base)
Value:
TEMPLATE(Type, Base)
TEMPLATETYPEPARM
#define TEMPLATETYPEPARM (Type, Base)
Value:
TYPE(Type, Base)
TRANSLATIONUNIT
#define TRANSLATIONUNIT (Type, Base)
Value:
DECL(Type, Base)
TYPE
#define TYPE (Type, Base)
Value:
NAMED(Type, Base)
TYPE_ATTR
#define TYPE_ATTR (NAME)
Value:
ATTR(NAME)
TYPEALIAS
#define TYPEALIAS (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEALIASTEMPLATE
#define TYPEALIASTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
TYPEDEF
#define TYPEDEF (Type, Base)
Value:
TYPEDEFNAME(Type, Base)
TYPEDEFNAME
#define TYPEDEFNAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGTYPENAME
#define UNRESOLVEDUSINGTYPENAME (Type, Base)
Value:
TYPE(Type, Base)
UNRESOLVEDUSINGVALUE
#define UNRESOLVEDUSINGVALUE (Type, Base)
Value:
VALUE(Type, Base)
USING
#define USING (Type, Base)
Value:
NAMED(Type, Base)
USINGDIRECTIVE
#define USINGDIRECTIVE (Type, Base)
Value:
NAMED(Type, Base)
USINGPACK
#define USINGPACK (Type, Base)
Value:
NAMED(Type, Base)
USINGSHADOW
#define USINGSHADOW (Type, Base)
Value:
NAMED(Type, Base)
VALUE
#define VALUE (Type, Base)
Value:
NAMED(Type, Base)
VAR
#define VAR (Type, Base)
Value:
DECLARATOR(Type, Base)
VARTEMPLATE
#define VARTEMPLATE (Type, Base)
Value:
REDECLARABLETEMPLATE(Type, Base)
VARTEMPLATEPARTIALSPECIALIZATION
#define VARTEMPLATEPARTIALSPECIALIZATION (Type, Base)
Value:
VARTEMPLATESPECIALIZATION(Type, Base)
VARTEMPLATESPECIALIZATION
#define VARTEMPLATESPECIALIZATION (Type, Base)
Value:
VAR(Type, Base)
Function Documentation
dumpBasePath()
static void dumpBasePath (raw_ostream & OS, const CastExpr * Node) static
Definition at line 878 of file TextNodeDumper.cpp.
References clang::cast(), clang::First, clang::RecordType::getDecl(), and Node.
Referenced by clang::TextNodeDumper::VisitCastExpr(), and clang::TextNodeDumper::VisitCXXNamedCastExpr().
dumpPreviousDecl()
static void dumpPreviousDecl (raw_ostream & OS, const Decl * D) static
Dump the previous declaration in the redeclaration chain for a declaration, if any.
Definition at line 48 of file TextNodeDumper.cpp.
References clang::Decl::getKind().
Referenced by clang::TextNodeDumper::Visit().
dumpPreviousDeclImpl() [1/3]
template<typename T > static void dumpPreviousDeclImpl (raw_ostream & OS, const Mergeable< T > * D) static
Definition at line 33 of file TextNodeDumper.cpp.
References clang::First, and clang::Mergeable< decl_type >::getFirstDecl().
dumpPreviousDeclImpl() [2/3]
template<typename T > static void dumpPreviousDeclImpl (raw_ostream & OS, const Redeclarable< T > * D) static
Definition at line 40 of file TextNodeDumper.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl().
dumpPreviousDeclImpl() [3/3]
static void dumpPreviousDeclImpl (raw_ostream & OS, ...) static
Definition at line 30 of file TextNodeDumper.cpp.
GetApproxValue()
static double GetApproxValue (const llvm::APFloat & F) static
Definition at line 358 of file TextNodeDumper.cpp.
References V.
isSimpleAPValue()
static bool isSimpleAPValue (const APValue & Value) static
True if the APValue Value can be folded onto the current line.
Definition at line 367 of file TextNodeDumper.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::APValue::FixedPoint, clang::APValue::Float, clang::APValue::Indeterminate, clang::APValue::Int, isSimpleAPValue(), clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, clang::APValue::Struct, clang::APValue::Union, and clang::APValue::Vector.
Referenced by isSimpleAPValue(), and clang::TextNodeDumper::Visit().