clang: lib/AST/TypePrinter.cpp File Reference
TypePrinter.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <string>
#include "clang/AST/TypeNodes.inc"
#include "clang/Basic/AttrList.inc"
Macros
#define ABSTRACT_TYPE(CLASS, PARENT)
#define TYPE(CLASS, PARENT)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(CLASS, PARENT)
#define TYPE(CLASS, PARENT)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(CLASS, PARENT)
#define TYPE(CLASS, PARENT)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TYPE_ATTR(NAME)
#define DECL_OR_TYPE_ATTR(NAME)
#define ATTR(NAME)
#define STMT_ATTR(NAME)
#define DECL_OR_STMT_ATTR(NAME)
#define INHERITABLE_ATTR(NAME)
#define INHERITABLE_PARAM_ATTR(NAME)
#define PARAMETER_ABI_ATTR(NAME)
#define PRAGMA_SPELLING_ATTR(NAME)
Functions
static void AppendTypeQualList (raw_ostream &OS, unsigned TypeQuals, bool HasRestrictKeyword)
static SplitQualType splitAccordingToPolicy (QualType QT, const PrintingPolicy &Policy)
static QualType skipTopLevelReferences (QualType T)
static const TemplateArgument & getArgument (const TemplateArgument &A)
static const TemplateArgument & getArgument (const TemplateArgumentLoc &A)
static void printArgument (const TemplateArgument &A, const PrintingPolicy &PP, llvm::raw_ostream &OS)
static void printArgument (const TemplateArgumentLoc &A, const PrintingPolicy &PP, llvm::raw_ostream &OS)
static bool isSubstitutedTemplateArgument (ASTContext &Ctx, TemplateArgument Arg, TemplateArgument Pattern, ArrayRef< TemplateArgument > Args, unsigned Depth)
static bool isSubstitutedType (ASTContext &Ctx, QualType T, QualType Pattern, ArrayRef< TemplateArgument > Args, unsigned Depth)
static bool isSubstitutedDefaultArgument (ASTContext &Ctx, TemplateArgument Arg, const NamedDecl *Param, ArrayRef< TemplateArgument > Args, unsigned Depth)
Make a best-effort determination of whether the type T can be produced by substituting Args into the default argument of Param.
template<typename TA >
static void printTo (raw_ostream &OS, ArrayRef< TA > Args, const PrintingPolicy &Policy, bool SkipBrackets, const TemplateParameterList *TPL)
Macro Definition Documentation
ABSTRACT_TYPE [1/3]
#define ABSTRACT_TYPE (CLASS, PARENT)
Definition at line 128 of file TypePrinter.cpp.
ABSTRACT_TYPE [2/3]
#define ABSTRACT_TYPE (CLASS, PARENT)
Definition at line 128 of file TypePrinter.cpp.
ABSTRACT_TYPE [3/3]
#define ABSTRACT_TYPE (CLASS, PARENT)
Definition at line 128 of file TypePrinter.cpp.
ATTR
#define ATTR (NAME)
Value:
case attr::NAME:
DECL_OR_STMT_ATTR
#define DECL_OR_STMT_ATTR (NAME)
Value:
INHERITABLE_ATTR(NAME)
DECL_OR_TYPE_ATTR
#define DECL_OR_TYPE_ATTR (NAME)
DEPENDENT_TYPE [1/3]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
DEPENDENT_TYPE [2/3]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
DEPENDENT_TYPE [3/3]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
INHERITABLE_ATTR
#define INHERITABLE_ATTR (NAME)
Value:
ATTR(NAME)
INHERITABLE_PARAM_ATTR
#define INHERITABLE_PARAM_ATTR (NAME)
Value:
INHERITABLE_ATTR(NAME)
NON_CANONICAL_TYPE [1/3]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [2/3]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [3/3]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [1/3]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [2/3]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [3/3]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
PARAMETER_ABI_ATTR
#define PARAMETER_ABI_ATTR (NAME)
Value:
INHERITABLE_PARAM_ATTR(NAME)
PRAGMA_SPELLING_ATTR
#define PRAGMA_SPELLING_ATTR (NAME)
STMT_ATTR
#define STMT_ATTR (NAME)
Value:
ATTR(NAME)
TYPE [1/3]
#define TYPE (CLASS, PARENT)
Value:
    void print##CLASS##Before(const CLASS##Type *T, raw_ostream &OS); \
    void print##CLASS##After(const CLASS##Type *T, raw_ostream &OS);
Definition at line 129 of file TypePrinter.cpp.
TYPE [2/3]
#define TYPE (CLASS, PARENT)
Value:
    case Type::CLASS: \
    print##CLASS##Before(cast<CLASS##Type>(T), OS); \
    break;
Definition at line 129 of file TypePrinter.cpp.
TYPE [3/3]
#define TYPE (CLASS, PARENT)
Value:
    case Type::CLASS: \
    print##CLASS##After(cast<CLASS##Type>(T), OS); \
    break;
Definition at line 129 of file TypePrinter.cpp.
TYPE_ATTR
#define TYPE_ATTR (NAME)
Function Documentation
AppendTypeQualList()
static void AppendTypeQualList (raw_ostream & OS, unsigned TypeQuals, bool HasRestrictKeyword) static
Definition at line 141 of file TypePrinter.cpp.
References clang::Qualifiers::Const, clang::Qualifiers::Restrict, and clang::Qualifiers::Volatile.
Referenced by clang::Qualifiers::print().
getArgument() [1/2]
static const TemplateArgument & getArgument (const TemplateArgument & A) static
Definition at line 1838 of file TypePrinter.cpp.
Referenced by clang::Sema::CheckTemplateArgumentList(), clang::ASTContext::getDependentTemplateSpecializationType(), clang::AtomicConstraint::hasMatchingParameterMapping(), and printTo().
getArgument() [2/2]
static const TemplateArgument & getArgument (const TemplateArgumentLoc & A) static
Definition at line 1840 of file TypePrinter.cpp.
References clang::TemplateArgumentLoc::getArgument().
isSubstitutedDefaultArgument()
static bool isSubstitutedDefaultArgument (ASTContext & Ctx, TemplateArgument Arg, const NamedDecl * Param, ArrayRef< TemplateArgument > Args, unsigned Depth) static
Make a best-effort determination of whether the type T can be produced by substituting Args into the default argument of Param.
Definition at line 1967 of file TypePrinter.cpp.
References clang::TemplateArgument::getKind(), isSubstitutedTemplateArgument(), clang::TemplateArgument::Pack, and clang::TemplateArgument::pack_size().
Referenced by printTo().
isSubstitutedTemplateArgument()
static bool isSubstitutedTemplateArgument (ASTContext & Ctx, TemplateArgument Arg, TemplateArgument Pattern, ArrayRef< TemplateArgument > Args, unsigned Depth) static
Definition at line 1928 of file TypePrinter.cpp.
References clang::TemplateArgument::Expression, clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsTemplate(), clang::TemplateName::getAsTemplateDecl(), clang::TemplateArgument::getAsType(), clang::ASTContext::getCanonicalTemplateArgument(), clang::TemplateArgument::getKind(), clang::Expr::IgnoreParenImpCasts(), isSubstitutedType(), clang::TemplateArgument::structurallyEquals(), clang::TemplateArgument::Template, and clang::TemplateArgument::Type.
Referenced by isSubstitutedDefaultArgument(), and isSubstitutedType().
isSubstitutedType()
static bool isSubstitutedType (ASTContext & Ctx, QualType T, QualType Pattern, ArrayRef< TemplateArgument > Args, unsigned Depth) static
Definition at line 1862 of file TypePrinter.cpp.
References clang::Type::getAs(), clang::QualType::getCanonicalType(), clang::Type::getPointeeType(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::Type::getTypeClass(), clang::ASTContext::getUnqualifiedArrayType(), clang::ASTContext::hasSameType(), clang::QualType::isNull(), isSubstitutedTemplateArgument(), isSubstitutedType(), N, and clang::TemplateArgument::Type.
Referenced by isSubstitutedTemplateArgument(), and isSubstitutedType().
printArgument() [1/2]
static void printArgument (const TemplateArgument & A, const PrintingPolicy & PP, llvm::raw_ostream & OS) static
Definition at line 1844 of file TypePrinter.cpp.
References clang::TemplateArgument::print().
Referenced by printTo().
printArgument() [2/2]
static void printArgument (const TemplateArgumentLoc & A, const PrintingPolicy & PP, llvm::raw_ostream & OS) static
Definition at line 1849 of file TypePrinter.cpp.
References clang::TemplateArgumentLoc::getArgument(), clang::TemplateArgument::getKind(), clang::TypeSourceInfo::getType(), clang::TemplateArgumentLoc::getTypeSourceInfo(), clang::QualType::print(), and clang::TemplateArgument::print().
printTo()
template<typename TA > static void printTo (raw_ostream & OS, ArrayRef< TA > Args, const PrintingPolicy & Policy, bool SkipBrackets, const TemplateParameterList * TPL) static
Definition at line 1992 of file TypePrinter.cpp.
References getArgument(), clang::Decl::getASTContext(), clang::TemplateParameterList::getDepth(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getPackAsArray(), clang::TemplateParameterList::getParam(), isSubstitutedDefaultArgument(), clang::PrintingPolicy::MSVCFormatting, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_size(), printArgument(), clang::PrintingPolicy::PrintCanonicalTypes, printTo(), clang::TemplateParameterList::size(), clang::PrintingPolicy::SplitTemplateClosers, and clang::PrintingPolicy::SuppressDefaultTemplateArgs.
Referenced by clang::printTemplateArgumentList(), clang::printTemplateArgumentList(), and printTo().
skipTopLevelReferences()
static QualType skipTopLevelReferences (QualType T) static
Definition at line 414 of file TypePrinter.cpp.
References skipTopLevelReferences().
Referenced by skipTopLevelReferences().
splitAccordingToPolicy()
static SplitQualType splitAccordingToPolicy (QualType QT, const PrintingPolicy & Policy) static
Definition at line 168 of file TypePrinter.cpp.
References clang::QualType::getCanonicalType(), clang::PrintingPolicy::PrintCanonicalTypes, and clang::QualType::split().
Referenced by clang::QualType::getAsStringInternal(), and clang::QualType::print().