clang: lib/AST/Type.cpp File Reference
Type.cpp File Reference
#include "clang/AST/Type.h"
#include "Linkage.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DependenceFlags.h"
#include "clang/AST/Expr.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/NonTrivialTypeVisitor.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/TypeVisitor.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Linkage.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetCXXABI.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Visibility.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <type_traits>
#include "clang/AST/TypeNodes.inc"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/AST/BuiltinTypes.def"
Classes
class clang::TypePropertyCache< Private >
The type-property cache.
Namespaces
namespace clang
Dataflow Directional Tag Classes.
Macros
#define TYPE(CLASS, BASE)
#define TYPE(CLASS, BASE)
#define ABSTRACT_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TRIVIAL_TYPE_CLASS(Class)
#define SUGARED_TYPE_CLASS(Class)
#define SVE_TYPE(Name, Id, SingletonId)
#define ABSTRACT_TYPE(Derived, Base)
#define TYPE(Derived, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
#define TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Parent)
#define TYPE(Class, Parent)
#define ABSTRACT_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define SIGNED_TYPE(Id, SingletonId)
#define UNSIGNED_TYPE(Id, SingletonId)
#define FLOATING_TYPE(Id, SingletonId)
#define BUILTIN_TYPE(Id, SingletonId)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId)
#define PPC_VECTOR_TYPE(Name, Id, Size)
Typedefs
using Cache = TypePropertyCache<Private>
Functions
template<typename T >
static const T * getAsSugar (const Type *Cur)
This will check for a T (which should be a Type which can act as sugar, such as a TypedefType) by removing any existing sugar until it reaches a T or a non-sugared type.
static TagDecl * getInterestingTagDecl (TagDecl *decl)
static CachedProperties computeCachedProperties (const Type *T)
Macro Definition Documentation
ABSTRACT_TYPE [1/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [2/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [3/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [4/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [5/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [6/12]
#define ABSTRACT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
ABSTRACT_TYPE [7/12]
#define ABSTRACT_TYPE (Class, Parent)
ABSTRACT_TYPE [8/12]
#define ABSTRACT_TYPE (Class, Parent)
ABSTRACT_TYPE [9/12]
#define ABSTRACT_TYPE (Class, Parent)
ABSTRACT_TYPE [10/12]
#define ABSTRACT_TYPE (Class, Parent)
ABSTRACT_TYPE [11/12]
#define ABSTRACT_TYPE (Class, Parent)
ABSTRACT_TYPE [12/12]
#define ABSTRACT_TYPE (Derived, Base)
BUILTIN_TYPE
#define BUILTIN_TYPE (Id, SingletonId)
DEPENDENT_TYPE [1/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [2/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [3/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [4/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [5/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [6/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [7/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [8/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [9/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [10/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
  QualType Visit##Class##Type(const Class##Type *T) { return QualType(T, 0); }
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [11/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
case Type::Class:
Definition at line 861 of file Type.cpp.
DEPENDENT_TYPE [12/12]
#define DEPENDENT_TYPE (Class, Base)
Value:
case Type::Class:
Definition at line 861 of file Type.cpp.
EXT_OPAQUE_TYPE [1/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case Id: \
    return #ExtType;
EXT_OPAQUE_TYPE [2/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
    case BuiltinType::Id:
FLOATING_TYPE
#define FLOATING_TYPE (Id, SingletonId)
Value:
case BuiltinType::Id:
IMAGE_TYPE [1/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case Id: \
    return "__" #Access " " #ImgType "_t";
IMAGE_TYPE [2/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
    case BuiltinType::Id:
NON_CANONICAL_TYPE [1/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [2/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [3/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [4/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [5/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [6/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [7/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [8/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [9/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_TYPE [10/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
case Type::Class:
NON_CANONICAL_TYPE [11/12]
#define NON_CANONICAL_TYPE (Class, Base)
Value:
case Type::Class:
NON_CANONICAL_TYPE [12/12]
#define NON_CANONICAL_TYPE (Class, Parent)
Value:
  case Type::Class:                             \
    llvm_unreachable("non-canonical type");
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [1/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [2/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [3/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [4/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [5/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [6/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [7/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [8/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [9/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [10/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
TYPE(Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [11/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
case Type::Class:
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [12/12]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
Value:
case Type::Class:
PPC_VECTOR_TYPE [1/2]
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
  case Id: \
    return #Name;
PPC_VECTOR_TYPE [2/2]
#define PPC_VECTOR_TYPE (Name, Id, Size)
Value:
    case BuiltinType::Id:
SIGNED_TYPE
#define SIGNED_TYPE (Id, SingletonId)
Value:
case BuiltinType::Id:
SUGARED_TYPE_CLASS
#define SUGARED_TYPE_CLASS (Class)
Value:
  QualType Visit##Class##Type(const Class##Type *T) { \
    if (!T->isSugared()) \
      return QualType(T, 0); \
    QualType desugaredType = recurse(T->desugar()); \
    if (desugaredType.isNull()) \
      return {}; \
    if (desugaredType.getAsOpaquePtr() == T->desugar().getAsOpaquePtr()) \
      return QualType(T, 0); \
    return desugaredType; \
  }
Definition at line 867 of file Type.cpp.
SVE_TYPE [1/3]
#define SVE_TYPE (Name, Id, SingletonId)
Value:
case BuiltinType::Id:
SVE_TYPE [2/3]
#define SVE_TYPE (Name, Id, SingletonId)
Value:
  case Id: \
    return Name;
SVE_TYPE [3/3]
#define SVE_TYPE (Name, Id, SingletonId)
Value:
    case BuiltinType::Id:
TRIVIAL_TYPE_CLASS
#define TRIVIAL_TYPE_CLASS (Class)
Value:
  QualType Visit##Class##Type(const Class##Type *T) { return QualType(T, 0); }
Definition at line 865 of file Type.cpp.
TYPE [1/14]
#define TYPE (CLASS, BASE)
Value:
  static_assert(!std::is_polymorphic<CLASS##Type>::value, \
                #CLASS "Type should not be polymorphic!");
Definition at line 405 of file Type.cpp.
TYPE [2/14]
#define TYPE (CLASS, BASE)
Value:
  static_assert(std::is_trivially_destructible<CLASS##Type>::value ||          \
                    std::is_same<CLASS##Type, ConstantArrayType>::value,       \
                #CLASS "Type should be trivially destructible!");
Definition at line 405 of file Type.cpp.
TYPE [3/14]
#define TYPE (Class, Base)
Definition at line 405 of file Type.cpp.
TYPE [4/14]
#define TYPE (Class, Base)
Definition at line 405 of file Type.cpp.
TYPE [5/14]
#define TYPE (Class, Base)
Definition at line 405 of file Type.cpp.
TYPE [6/14]
#define TYPE (Class, Base)
Definition at line 405 of file Type.cpp.
TYPE [7/14]
#define TYPE (Class, Base)
Definition at line 405 of file Type.cpp.
TYPE [8/14]
#define TYPE (Class, Parent)
Value:
  case Type::Class: { \
    const auto *ty = cast<Class##Type>(this); \
    if (!ty->isSugared()) return QualType(ty, 0); \
    return ty->desugar(); \
  }
Definition at line 405 of file Type.cpp.
TYPE [9/14]
#define TYPE (Class, Parent)
Value:
    case Type::Class: { \
      const auto *Ty = cast<Class##Type>(CurTy); \
      if (!Ty->isSugared()) \
        return SplitQualType(Ty, Qs); \
      Cur = Ty->desugar(); \
      break; \
    }
Definition at line 405 of file Type.cpp.
TYPE [10/14]
#define TYPE (Class, Parent)
Value:
    case Type::Class: { \
      const auto *ty = cast<Class##Type>(split.Ty); \
      if (!ty->isSugared()) goto done; \
      next = ty->desugar(); \
      break; \
    }
Definition at line 405 of file Type.cpp.
TYPE [11/14]
#define TYPE (Class, Parent)
Value:
    case Type::Class: { \
      const auto *Ty = cast<Class##Type>(Cur); \
      if (!Ty->isSugared()) return 0; \
      Cur = Ty->desugar().getTypePtr(); \
      break; \
    }
Definition at line 405 of file Type.cpp.
TYPE [12/14]
#define TYPE (Class, Parent)
Value:
    case Class: { \
      const auto *Ty = cast<Class##Type>(Cur); \
      if (!Ty->isSugared()) return Cur; \
      Cur = Ty->desugar().getTypePtr(); \
      break; \
    }
Definition at line 405 of file Type.cpp.
TYPE [13/14]
#define TYPE (Class, Parent)
Definition at line 405 of file Type.cpp.
TYPE [14/14]
#define TYPE (Derived, Base)
Value:
case Derived: return #Derived;
Definition at line 405 of file Type.cpp.
UNSIGNED_TYPE
#define UNSIGNED_TYPE (Id, SingletonId)
Value:
case BuiltinType::Id:
Typedef Documentation
Cache
using Cache = TypePropertyCache<Private>
Definition at line 3807 of file Type.cpp.
Function Documentation
computeCachedProperties()
static CachedProperties computeCachedProperties (const Type * T) static
Definition at line 3809 of file Type.cpp.
References clang::cast(), clang::ExternalLinkage, and clang::TypePropertyCache< Private >::get().
Referenced by clang::TypePropertyCache< Private >::ensure().
getAsSugar()
template<typename T > static const T * getAsSugar (const Type * Cur) static
This will check for a T (which should be a Type which can act as sugar, such as a TypedefType) by removing any existing sugar until it reaches a T or a non-sugared type.
Definition at line 506 of file Type.cpp.
References clang::Type::getTypeClass().
Referenced by clang::Type::getAs().
getInterestingTagDecl()
static TagDecl * getInterestingTagDecl (TagDecl * decl) static
Definition at line 3466 of file Type.cpp.
References clang::ast_matchers::decl.
Referenced by clang::InjectedClassNameType::getDecl(), and clang::TagType::getDecl().