LLVM: lib/Target/AArch64/MCTargetDesc/AArch64MCExpr.cpp File Reference
AArch64MCExpr.cpp File Reference
#include "AArch64MCExpr.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "aarch64symbolrefexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64symbolrefexpr"
Definition at line 25 of file AArch64MCExpr.cpp.
Function Documentation
fixELFSymbolsInTLSFixupsImpl()
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 115 of file AArch64MCExpr.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, fixELFSymbolsInTLSFixupsImpl(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::AArch64MCExpr::fixELFSymbolsInTLSFixups(), llvm::CSKYMCExpr::fixELFSymbolsInTLSFixups(), llvm::HexagonMCExpr::fixELFSymbolsInTLSFixups(), llvm::MipsMCExpr::fixELFSymbolsInTLSFixups(), llvm::RISCVMCExpr::fixELFSymbolsInTLSFixups(), llvm::SparcMCExpr::fixELFSymbolsInTLSFixups(), llvm::VEMCExpr::fixELFSymbolsInTLSFixups(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), and fixELFSymbolsInTLSFixupsImpl().