LLVM: lib/Target/AArch64/AArch64TargetTransformInfo.cpp File Reference
AArch64TargetTransformInfo.cpp File Reference
#include "AArch64TargetTransformInfo.h"
#include "AArch64ExpandImm.h"
#include "AArch64PerfectShuffle.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Vectorize/LoopVectorizationLegality.h"
#include <algorithm>
Classes
class TailFoldingKind
Macros
#define DEBUG_TYPE "aarch64tti"
Functions
static Optional< Instruction * > processPhiNode (InstCombiner &IC, IntrinsicInst &II)
The function will remove redundant reinterprets casting in the presence of the control flow.
static Optional< Instruction * > tryCombineFromSVBoolBinOp (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineConvertFromSVBool (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVESel (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEDup (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEDupX (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVECmpNE (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVELast (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVECondLast (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineRDFFR (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVECntElts (InstCombiner &IC, IntrinsicInst &II, unsigned NumElts)
static Optional< Instruction * > instCombineSVEPTest (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEVectorFMLA (InstCombiner &IC, IntrinsicInst &II)
static bool isAllActivePredicate (Value *Pred)
static Optional< Instruction * > instCombineSVELD1 (InstCombiner &IC, IntrinsicInst &II, const DataLayout &DL)
static Optional< Instruction * > instCombineSVEST1 (InstCombiner &IC, IntrinsicInst &II, const DataLayout &DL)
static Instruction::BinaryOps intrinsicIDToBinOpCode (unsigned Intrinsic)
static Optional< Instruction * > instCombineSVEVectorBinOp (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEVectorFAdd (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEVectorMul (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEUnpack (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVETBL (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVETupleGet (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVEZip (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineLD1GatherIndex (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineST1ScatterIndex (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVESDIV (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineMaxMinNM (InstCombiner &IC, IntrinsicInst &II)
static Optional< Instruction * > instCombineSVESrshl (InstCombiner &IC, IntrinsicInst &II)
static unsigned getSVEGatherScatterOverhead (unsigned Opcode)
static void getFalkorUnrollingPreferences (Loop *L, ScalarEvolution &SE, TargetTransformInfo::UnrollingPreferences &UP)
Variables
static cl::opt< bool > EnableFalkorHWPFUnrollFix ("enable-falkor-hwpf-unroll-fix", cl::init(true), cl::Hidden)
static cl::opt< unsigned > SVEGatherOverhead ("sve-gather-overhead", cl::init(10), cl::Hidden)
static cl::opt< unsigned > SVEScatterOverhead ("sve-scatter-overhead", cl::init(10), cl::Hidden)
TailFoldingKind TailFoldingKindLoc
cl::opt< TailFoldingKind, true, cl::parser< std::string > > SVETailFolding ("sve-tail-folding", cl::desc("Control the use of vectorisation using tail-folding for SVE:" "\ndisabled No loop types will vectorize using tail-folding" "\ndefault Uses the default tail-folding settings for the target " "CPU" "\nall All legal loop types will vectorize using tail-folding" "\nsimple Use tail-folding for simple loops (not reductions or " "recurrences)" "\nreductions Use tail-folding for loops containing reductions" "\nrecurrences Use tail-folding for loops containing first order " "recurrences"), cl::location(TailFoldingKindLoc))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64tti"
Definition at line 30 of file AArch64TargetTransformInfo.cpp.
Function Documentation
getFalkorUnrollingPreferences()
static void getFalkorUnrollingPreferences (Loop * L, ScalarEvolution & SE, TargetTransformInfo::UnrollingPreferences & UP) static
Definition at line 2367 of file AArch64TargetTransformInfo.cpp.
References llvm::dbgs(), llvm::dyn_cast(), llvm::LoadInst::getPointerOperand(), llvm::ScalarEvolution::getSCEV(), I, llvm::SCEVAddRecExpr::isAffine(), LLVM_DEBUG, llvm::Log2_32(), and llvm::TargetTransformInfo::UnrollingPreferences::MaxCount.
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences().
getSVEGatherScatterOverhead()
static unsigned getSVEGatherScatterOverhead (unsigned Opcode) static
Definition at line 2224 of file AArch64TargetTransformInfo.cpp.
References SVEGatherOverhead, and SVEScatterOverhead.
Referenced by llvm::AArch64TTIImpl::getGatherScatterOpCost().
instCombineConvertFromSVBool()
static Optional< Instruction * > instCombineConvertFromSVBool (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 599 of file AArch64TargetTransformInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::User::getOperand(), llvm::Value::getType(), llvm::SmallVectorImpl< T >::insert(), llvm::isa(), llvm::None, processPhiNode(), llvm::InstCombiner::replaceInstUsesWith(), and tryCombineFromSVBoolBinOp().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineLD1GatherIndex()
static Optional< Instruction * > instCombineLD1GatherIndex (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1240 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::ConstantAggregateZero::get(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineMaxMinNM()
static Optional< Instruction * > instCombineMaxMinNM (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1340 of file AArch64TargetTransformInfo.cpp.
References A, B, llvm::CallBase::getArgOperand(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineRDFFR()
static Optional< Instruction * > instCombineRDFFR (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 912 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineST1ScatterIndex()
static Optional< Instruction * > instCombineST1ScatterIndex (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1273 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::InstCombiner::eraseInstFromFunction(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::None.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECmpNE()
static Optional< Instruction * > instCombineSVECmpNE (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 691 of file AArch64TargetTransformInfo.cpp.
References Arg, Builder, llvm::cast(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantInt::get(), llvm::ScalableVectorType::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Constant::getNullValue(), llvm::getSplatValue(), llvm::Value::getType(), I, llvm::isa(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), and llvm::AArch64::SVEBitsPerBlock.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECntElts()
static Optional< Instruction * > instCombineSVECntElts (InstCombiner & IC, IntrinsicInst & II, unsigned NumElts) static
Definition at line 930 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::getNumElementsFromSVEPredPattern(), llvm::Value::getType(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECondLast()
static Optional< Instruction * > instCombineSVECondLast (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 868 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::VectorType::get(), llvm::CallBase::getArgOperand(), getBitWidth(), llvm::Value::getContext(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getType(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEDup()
static Optional< Instruction * > instCombineSVEDup (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 655 of file AArch64TargetTransformInfo.cpp.
References llvm::cast(), llvm::InsertElementInst::Create(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEDupX()
static Optional< Instruction * > instCombineSVEDupX (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 679 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Value::getType(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVELast()
static Optional< Instruction * > instCombineSVELast (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 792 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::CallingConv::C, llvm::cast(), llvm::ExtractElementInst::Create(), llvm::BinaryOperator::CreateWithCopiedFlags(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getNumElementsFromSVEPredPattern(), llvm::getSplatValue(), llvm::Value::getType(), llvm::isSplatValue(), LHS, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), and RHS.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVELD1()
static Optional< Instruction * > instCombineSVELD1 (InstCombiner & IC, IntrinsicInst & II, const DataLayout & DL) static
Definition at line 1024 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Instruction::copyMetadata(), DL, llvm::ConstantAggregateZero::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerTo(), llvm::Value::getType(), isAllActivePredicate(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEPTest()
static Optional< Instruction * > instCombineSVEPTest (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 952 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getType(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESDIV()
static Optional< Instruction * > instCombineSVESDIV (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1306 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::dyn_cast_or_null(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::getSplatValue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Int32Ty, llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::APInt::negate(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESel()
static Optional< Instruction * > instCombineSVESel (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 647 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::User::getOperand(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESrshl()
static Optional< Instruction * > instCombineSVESrshl (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1350 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::User::getOperand(), llvm::Value::getType(), llvm::isa(), isAllActivePredicate(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEST1()
static Optional< Instruction * > instCombineSVEST1 (InstCombiner & IC, IntrinsicInst & II, const DataLayout & DL) static
Definition at line 1047 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Instruction::copyMetadata(), DL, llvm::InstCombiner::eraseInstFromFunction(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerTo(), llvm::Value::getType(), and isAllActivePredicate().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVETBL()
static Optional< Instruction * > instCombineSVETBL (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1174 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::dyn_cast_or_null(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::getSplatValue(), llvm::Value::getType(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVETupleGet()
static Optional< Instruction * > instCombineSVETupleGet (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1199 of file AArch64TargetTransformInfo.cpp.
References llvm::CallBase::getArgOperand(), llvm::Value::getType(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), and SetValue().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEUnpack()
static Optional< Instruction * > instCombineSVEUnpack (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1152 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getSplatValue(), llvm::Value::getType(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEVectorBinOp()
static Optional< Instruction * > instCombineSVEVectorBinOp (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1082 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Value::getContext(), llvm::Instruction::getFastMathFlags(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), intrinsicIDToBinOpCode(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::match(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic(), instCombineSVEVectorFAdd(), and instCombineSVEVectorMul().
instCombineSVEVectorFAdd()
static Optional< Instruction * > instCombineSVEVectorFAdd (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1098 of file AArch64TargetTransformInfo.cpp.
References instCombineSVEVectorBinOp(), and instCombineSVEVectorFMLA().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEVectorFMLA()
static Optional< Instruction * > instCombineSVEVectorFMLA (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 977 of file AArch64TargetTransformInfo.cpp.
References A, llvm::FastMathFlags::allowContract(), B, Builder, llvm::CallingConv::C, llvm::cast(), llvm::FMul, llvm::Value::getContext(), llvm::Instruction::getFastMathFlags(), llvm::User::getOperand(), llvm::Value::getType(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, P, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineSVEVectorFAdd().
instCombineSVEVectorMul()
static Optional< Instruction * > instCombineSVEVectorMul (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1105 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::dyn_cast(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::getSplatValue(), I, instCombineSVEVectorBinOp(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_One(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEZip()
static Optional< Instruction * > instCombineSVEZip (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1225 of file AArch64TargetTransformInfo.cpp.
References A, B, llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
intrinsicIDToBinOpCode()
static Instruction::BinaryOps intrinsicIDToBinOpCode (unsigned Intrinsic) static
Definition at line 1069 of file AArch64TargetTransformInfo.cpp.
Referenced by instCombineSVEVectorBinOp().
isAllActivePredicate()
static bool isAllActivePredicate (Value * Pred) static
Definition at line 1007 of file AArch64TargetTransformInfo.cpp.
References llvm::cast(), llvm::Value::getType(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
processPhiNode()
static Optional< Instruction * > processPhiNode (InstCombiner & IC, IntrinsicInst & II) static
The function will remove redundant reinterprets casting in the presence of the control flow.
Definition at line 500 of file AArch64TargetTransformInfo.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, llvm::cast(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), I, llvm::None, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineConvertFromSVBool().
tryCombineFromSVBoolBinOp()
static Optional< Instruction * > tryCombineFromSVBoolBinOp (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 547 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::cast(), llvm::dyn_cast(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getType(), llvm::None, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineConvertFromSVBool().
Variable Documentation
EnableFalkorHWPFUnrollFix
cl::opt< bool > EnableFalkorHWPFUnrollFix("enable-falkor-hwpf-unroll-fix", cl::init(true), cl::Hidden) ("enable-falkor-hwpf-unroll-fix" , cl::init(true) , cl::Hidden) static
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences().
SVEGatherOverhead
cl::opt< unsigned > SVEGatherOverhead("sve-gather-overhead", cl::init(10), cl::Hidden) ("sve-gather-overhead" , cl::init(10) , cl::Hidden) static
Referenced by getSVEGatherScatterOverhead().
SVEScatterOverhead
cl::opt< unsigned > SVEScatterOverhead("sve-scatter-overhead", cl::init(10), cl::Hidden) ("sve-scatter-overhead" , cl::init(10) , cl::Hidden) static
Referenced by getSVEGatherScatterOverhead().
SVETailFolding
cl::opt< TailFoldingKind, true, cl::parser< std::string > > SVETailFolding("sve-tail-folding", cl::desc("Control the use of vectorisation using tail-folding for SVE:" "\ndisabled No loop types will vectorize using tail-folding" "\ndefault Uses the default tail-folding settings for the target " "CPU" "\nall All legal loop types will vectorize using tail-folding" "\nsimple Use tail-folding for simple loops (not reductions or " "recurrences)" "\nreductions Use tail-folding for loops containing reductions" "\nrecurrences Use tail-folding for loops containing first order " "recurrences"), cl::location(TailFoldingKindLoc)) ("sve-tail-folding" , cl::desc("Control the use of vectorisation using tail-folding for SVE:" "\ndisabled No loop types will vectorize using tail-folding" "\ndefault Uses the default tail-folding settings for the target " "CPU" "\nall All legal loop types will vectorize using tail-folding" "\nsimple Use tail-folding for simple loops (not reductions or " "recurrences)" "\nreductions Use tail-folding for loops containing reductions" "\nrecurrences Use tail-folding for loops containing first order " "recurrences") , cl::location(TailFoldingKindLoc))
TailFoldingKindLoc
TailFoldingKind TailFoldingKindLoc
Definition at line 92 of file AArch64TargetTransformInfo.cpp.
Referenced by llvm::AArch64TTIImpl::preferPredicateOverEpilogue().