LLVM: lib/Target/AArch64/AArch64PerfectShuffle.h File Reference
AArch64PerfectShuffle.h File Reference
#include "llvm/ADT/ArrayRef.h"
Functions
static unsigned getPerfectShuffleCost (llvm::ArrayRef< int > M)
Variables
static const unsigned PerfectShuffleTable [6561+1]
Function Documentation
getPerfectShuffleCost()
static unsigned getPerfectShuffleCost (llvm::ArrayRef< int > M) static
Definition at line 6589 of file AArch64PerfectShuffle.h.
References llvm::all_of(), assert(), E, llvm::enumerate(), and PerfectShuffleTable.
Referenced by llvm::AArch64TTIImpl::getShuffleCost(), and llvm::AArch64TargetLowering::isShuffleMaskLegal().
Variable Documentation
PerfectShuffleTable
const unsigned PerfectShuffleTable[6561+1] static
Definition at line 25 of file AArch64PerfectShuffle.h.
Referenced by GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), getPerfectShuffleCost(), llvm::ARMTargetLowering::isShuffleMaskLegal(), and LowerVECTOR_SHUFFLE().