LLVM: lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp File Reference
AArch64LegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for AArch64.
#include "AArch64LegalizerInfo.h"
#include "AArch64RegisterBankInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/MathExtras.h"
#include <initializer_list>
Macros
#define DEBUG_TYPE "aarch64-legalinfo"
Functions
static void extractParts (Register Reg, MachineRegisterInfo &MRI, MachineIRBuilder &MIRBuilder, LLT Ty, int NumParts, SmallVectorImpl< Register > &VRegs)
static void matchLDPSTPAddrMode (Register Root, Register &Base, int &Offset, MachineRegisterInfo &MRI)
Detailed Description
This file implements the targeting of the Machinelegalizer class for AArch64.
Todo
This should be generated by TableGen.
Definition in file AArch64LegalizerInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-legalinfo"
Definition at line 33 of file AArch64LegalizerInfo.cpp.
Function Documentation
extractParts()
static void extractParts (Register Reg, MachineRegisterInfo & MRI, MachineIRBuilder & MIRBuilder, LLT Ty, int NumParts, SmallVectorImpl< Register > & VRegs) static
Definition at line 885 of file AArch64LegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildUnmerge(), I, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
matchLDPSTPAddrMode()
static void matchLDPSTPAddrMode (Register Root, Register & Base, int & Offset, MachineRegisterInfo & MRI) static
Definition at line 1057 of file AArch64LegalizerInfo.cpp.
References llvm::sampleprof::Base, llvm::isShiftedInt(), llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), MRI, and Offset.