LLVM: lib/Transforms/Scalar/AlignmentFromAssumptions.cpp File Reference
AlignmentFromAssumptions.cpp File Reference
#include "llvm/Transforms/Scalar/AlignmentFromAssumptions.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
Macros
#define AA_NAME "alignment-from-assumptions"
#define DEBUG_TYPE AA_NAME
Functions
STATISTIC (NumLoadAlignChanged, "Number of loads changed by alignment assumptions")
STATISTIC (NumStoreAlignChanged, "Number of stores changed by alignment assumptions")
STATISTIC (NumMemIntAlignChanged, "Number of memory intrinsics changed by alignment assumptions")
INITIALIZE_PASS_BEGIN (AlignmentFromAssumptions, AA_NAME, aip_name, false, false) INITIALIZE_PASS_END(AlignmentFromAssumptions
static MaybeAlign getNewAlignmentDiff (const SCEV *DiffSCEV, const SCEV *AlignSCEV, ScalarEvolution *SE)
static Align getNewAlignment (const SCEV *AASCEV, const SCEV *AlignSCEV, const SCEV *OffSCEV, Value *Ptr, ScalarEvolution *SE)
Variables
static const char aip_name [] = "Alignment from assumptions"
AA_NAME
false
Macro Definition Documentation
AA_NAME
#define AA_NAME "alignment-from-assumptions"
Definition at line 36 of file AlignmentFromAssumptions.cpp.
DEBUG_TYPE
#define DEBUG_TYPE AA_NAME
Definition at line 37 of file AlignmentFromAssumptions.cpp.
Function Documentation
getNewAlignment()
static Align getNewAlignment (const SCEV * AASCEV, const SCEV * AlignSCEV, const SCEV * OffSCEV, Value * Ptr, ScalarEvolution * SE) static
Definition at line 125 of file AlignmentFromAssumptions.cpp.
References Align, assert(), llvm::dbgs(), llvm::DebugStr(), llvm::dyn_cast(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::ScalarEvolution::getMinusSCEV(), getNewAlignmentDiff(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getSCEV(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), llvm::SCEV::getType(), llvm::isa(), and LLVM_DEBUG.
Referenced by llvm::AlignmentFromAssumptionsPass::processAssumption().
getNewAlignmentDiff()
static MaybeAlign getNewAlignmentDiff (const SCEV * DiffSCEV, const SCEV * AlignSCEV, ScalarEvolution * SE) static
Definition at line 93 of file AlignmentFromAssumptions.cpp.
References Align, llvm::cast(), llvm::dbgs(), llvm::dyn_cast(), llvm::ScalarEvolution::getURemExpr(), llvm::isPowerOf2_64(), LLVM_DEBUG, and llvm::None.
Referenced by getNewAlignment().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AlignmentFromAssumptions , AA_NAME , aip_name , false , false)
STATISTIC() [1/3]
STATISTIC (NumLoadAlignChanged , "Number of loads changed by alignment assumptions")
STATISTIC() [2/3]
STATISTIC (NumMemIntAlignChanged , "Number of memory intrinsics changed by alignment assumptions")
STATISTIC() [3/3]
STATISTIC (NumStoreAlignChanged , "Number of stores changed by alignment assumptions")
Variable Documentation
AA_NAME
AA_NAME
Definition at line 80 of file AlignmentFromAssumptions.cpp.
aip_name
aip_name = "Alignment from assumptions" static
Definition at line 74 of file AlignmentFromAssumptions.cpp.
false
false
Definition at line 81 of file AlignmentFromAssumptions.cpp.