LLVM: lib/Target/AMDGPU/AMDGPUPromoteKernelArguments.cpp File Reference
AMDGPUPromoteKernelArguments.cpp File Reference
#include "AMDGPU.h"
#include "Utils/AMDGPUMemoryUtils.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "amdgpu-promote-kernel-arguments"
Functions
static BasicBlock::iterator getInsertPt (BasicBlock &BB)
INITIALIZE_PASS_BEGIN (AMDGPUPromoteKernelArguments, DEBUG_TYPE, "AMDGPU Promote Kernel Arguments", false, false) INITIALIZE_PASS_END(AMDGPUPromoteKernelArguments
Variables
DEBUG_TYPE
AMDGPU Promote Kernel Arguments
AMDGPU Promote Kernel false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-promote-kernel-arguments"
Definition at line 26 of file AMDGPUPromoteKernelArguments.cpp.
Function Documentation
getInsertPt()
static BasicBlock::iterator getInsertPt (BasicBlock & BB) static
Definition at line 139 of file AMDGPUPromoteKernelArguments.cpp.
References llvm::dyn_cast(), E, llvm::BasicBlock::end(), llvm::BasicBlock::getFirstInsertionPt(), and llvm::AllocaInst::isStaticAlloca().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUPromoteKernelArguments , DEBUG_TYPE , "AMDGPU Promote Kernel Arguments" , false , false)
Variable Documentation
Arguments
AMDGPU Promote Kernel Arguments
Definition at line 199 of file AMDGPUPromoteKernelArguments.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 198 of file AMDGPUPromoteKernelArguments.cpp.
false
AMDGPU Promote Kernel false
Definition at line 199 of file AMDGPUPromoteKernelArguments.cpp.