LLVM: lib/Target/AMDGPU/AMDGPUInstCombineIntrinsic.cpp File Reference
AMDGPUInstCombineIntrinsic.cpp File Reference
#include "AMDGPUInstrInfo.h"
#include "AMDGPUTargetTransformInfo.h"
#include "GCNSubtarget.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "InstCombineTables.inc"
Macros
#define DEBUG_TYPE "AMDGPUtti"
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Functions
static APFloat fmed3AMDGCN (const APFloat &Src0, const APFloat &Src1, const APFloat &Src2)
static bool canSafelyConvertTo16Bit (Value &V, bool IsFloat)
static Value * convertTo16Bit (Value &V, InstCombiner::BuilderTy &Builder)
static Optional< Instruction * > modifyIntrinsicCall (IntrinsicInst &OldIntr, Instruction &InstToReplace, unsigned NewIntr, InstCombiner &IC, std::function< void(SmallVectorImpl< Value * > &, SmallVectorImpl< Type * > &)> Func)
Applies Func(OldIntr.Args, OldIntr.ArgTys), creates intrinsic call with modified arguments (based on OldIntr) and replaces InstToReplace with this newly created intrinsic call.
static Optional< Instruction * > simplifyAMDGCNImageIntrinsic (const GCNSubtarget *ST, const AMDGPU::ImageDimIntrinsicInfo *ImageDimIntr, IntrinsicInst &II, InstCombiner &IC)
static Value * simplifyAMDGCNMemoryIntrinsicDemanded (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, int DMaskIdx=-1)
Implement SimplifyDemandedVectorElts for amdgcn buffer and image intrinsics.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "AMDGPUtti"
Definition at line 25 of file AMDGPUInstCombineIntrinsic.cpp.
GET_AMDGPUImageDMaskIntrinsicTable_IMPL
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Definition at line 33 of file AMDGPUInstCombineIntrinsic.cpp.
Function Documentation
canSafelyConvertTo16Bit()
static bool canSafelyConvertTo16Bit (Value & V, bool IsFloat) static
Definition at line 63 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::APFloat::convert(), llvm::dyn_cast(), llvm::APInt::getActiveBits(), llvm::Value::getType(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), and llvm::PatternMatch::match().
Referenced by simplifyAMDGCNImageIntrinsic().
convertTo16Bit()
static Value * convertTo16Bit (Value & V, InstCombiner::BuilderTy & Builder) static
Definition at line 101 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::cast(), llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm_unreachable.
fmed3AMDGCN()
static APFloat fmed3AMDGCN (const APFloat & Src0, const APFloat & Src1, const APFloat & Src2) static
Definition at line 42 of file AMDGPUInstCombineIntrinsic.cpp.
References assert(), llvm::APFloat::compare(), and llvm::maxnum().
Referenced by llvm::GCNTTIImpl::instCombineIntrinsic().
modifyIntrinsicCall()
static Optional< Instruction * > modifyIntrinsicCall (IntrinsicInst & OldIntr, Instruction & InstToReplace, unsigned NewIntr, InstCombiner & IC, std::function< void(SmallVectorImpl< Value * > &, SmallVectorImpl< Type * > &)> Func) static
Applies Func(OldIntr.Args, OldIntr.ArgTys), creates intrinsic call with modified arguments (based on OldIntr) and replaces InstToReplace with this newly created intrinsic call.
Definition at line 116 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::CallBase::args(), llvm::InstCombiner::Builder, llvm::Instruction::copyFastMathFlags(), llvm::Instruction::copyMetadata(), llvm::IRBuilderBase::CreateCall(), llvm::InstCombiner::eraseInstFromFunction(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::Intrinsic::getIntrinsicSignature(), llvm::Instruction::getModule(), llvm::Value::getType(), I, llvm::isa(), llvm::Type::isVoidTy(), llvm::None, llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by simplifyAMDGCNImageIntrinsic().
simplifyAMDGCNImageIntrinsic()
static Optional< Instruction * > simplifyAMDGCNImageIntrinsic (const GCNSubtarget * ST, const AMDGPU::ImageDimIntrinsicInfo * ImageDimIntr, IntrinsicInst & II, InstCombiner & IC) static
Definition at line 152 of file AMDGPUInstCombineIntrinsic.cpp.
References assert(), llvm::AMDGPU::ImageDimIntrinsicInfo::BaseOpcode, llvm::AMDGPU::ImageDimIntrinsicInfo::BiasIndex, canSafelyConvertTo16Bit(), llvm::AMDGPU::ImageDimIntrinsicInfo::CoordStart, llvm::AMDGPU::ImageDimIntrinsicInfo::Dim, llvm::dyn_cast(), for(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::AMDGPU::ImageDimIntrinsicInfo::GradientStart, llvm::AMDGPU::MIMGBaseOpcodeInfo::HasD16, llvm::Value::hasOneUse(), if(), llvm::AMDGPU::ImageDimIntrinsicInfo::Intr, llvm::Type::isFloatingPointTy(), llvm::Type::isHalfTy(), llvm::AMDGPU::ImageDimIntrinsicInfo::LodIndex, llvm::AMDGPU::ImageDimIntrinsicInfo::MipIndex, modifyIntrinsicCall(), llvm::None, llvm::AMDGPU::ImageDimIntrinsicInfo::NumBiasArgs, llvm::AMDGPU::ImageDimIntrinsicInfo::OffsetIndex, llvm::Instruction::user_back(), and llvm::AMDGPU::ImageDimIntrinsicInfo::VAddrEnd.
Referenced by llvm::GCNTTIImpl::instCombineIntrinsic().
simplifyAMDGCNMemoryIntrinsicDemanded()
static Value * simplifyAMDGCNMemoryIntrinsicDemanded (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, int DMaskIdx = -1) static
Implement SimplifyDemandedVectorElts for amdgcn buffer and image intrinsics.
Note: This only supports non-TFE/LWE image intrinsic calls; those have struct returns.
Definition at line 1085 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::CallBase::args(), llvm::InstCombiner::Builder, llvm::cast(), llvm::Instruction::copyMetadata(), llvm::APInt::countPopulation(), llvm::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateCall(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::ConstantInt::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::APInt::getActiveBits(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::InstCombiner::getDataLayout(), llvm::Intrinsic::getDeclaration(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Intrinsic::getIntrinsicSignature(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Type::getScalarType(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::ConstantInt::getZExtValue(), llvm::APInt::isMask(), Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::CallBase::setArgOperand(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::Value::takeName().
Referenced by llvm::GCNTTIImpl::simplifyDemandedVectorEltsIntrinsic().