LLVM: lib/Target/ARC/ARCFrameLowering.cpp File Reference
ARCFrameLowering.cpp File Reference
#include "ARCFrameLowering.h"
#include "ARCMachineFunctionInfo.h"
#include "ARCSubtarget.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "arc-frame-lowering"
Functions
static void generateStackAdjustment (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const ARCInstrInfo &TII, DebugLoc dl, int Amount, int StackPtr)
static unsigned determineLastCalleeSave (ArrayRef< CalleeSavedInfo > CSI)
static std::vector< CalleeSavedInfo >::iterator getSavedReg (std::vector< CalleeSavedInfo > &V, unsigned reg)
static void emitRegUpdate (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, DebugLoc dl, unsigned Reg, int NumBytes, bool IsAdd, const ARCInstrInfo *TII)
Variables
static cl::opt< bool > UseSaveRestoreFunclet ("arc-save-restore-funclet", cl::Hidden, cl::desc("Use arc callee save/restore functions"), cl::init(true))
static const char * store_funclet_name []
static const char * load_funclet_name []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-frame-lowering"
Definition at line 23 of file ARCFrameLowering.cpp.
Function Documentation
determineLastCalleeSave()
static unsigned determineLastCalleeSave (ArrayRef< CalleeSavedInfo > CSI) static
Definition at line 77 of file ARCFrameLowering.cpp.
References assert(), and llvm::Last.
Referenced by llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARCFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARCFrameLowering::restoreCalleeSavedRegisters(), and llvm::ARCFrameLowering::spillCalleeSavedRegisters().
emitRegUpdate()
static void emitRegUpdate (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, DebugLoc dl, unsigned Reg, int NumBytes, bool IsAdd, const ARCInstrInfo * TII) static
Definition at line 450 of file ARCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::isInt(), llvm::isUInt(), llvm::RegState::Kill, MBB, MBBI, and TII.
Referenced by llvm::ARCFrameLowering::eliminateCallFramePseudoInstr().
generateStackAdjustment()
static void generateStackAdjustment (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const ARCInstrInfo & TII, DebugLoc dl, int Amount, int StackPtr) static
Definition at line 44 of file ARCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::dbgs(), llvm::isInt(), llvm::isUInt(), LLVM_DEBUG, MBB, MBBI, and TII.
Referenced by llvm::ARCFrameLowering::emitPrologue().
getSavedReg()
static std::vector< CalleeSavedInfo >::iterator getSavedReg (std::vector< CalleeSavedInfo > & V, unsigned reg) static
Definition at line 337 of file ARCFrameLowering.cpp.
References E, and I.
Referenced by llvm::ARCFrameLowering::assignCalleeSavedSpillSlots().
Variable Documentation
load_funclet_name
const char* load_funclet_name[] static
Initial value:
= {
    "__ld_r13_to_r15", "__ld_r13_to_r16", "__ld_r13_to_r17", "__ld_r13_to_r18",
    "__ld_r13_to_r19", "__ld_r13_to_r20", "__ld_r13_to_r21", "__ld_r13_to_r22",
    "__ld_r13_to_r23", "__ld_r13_to_r24", "__ld_r13_to_r25",
}
Definition at line 38 of file ARCFrameLowering.cpp.
Referenced by llvm::ARCFrameLowering::emitEpilogue().
store_funclet_name
const char* store_funclet_name[] static
Initial value:
= {
    "__st_r13_to_r15", "__st_r13_to_r16", "__st_r13_to_r17", "__st_r13_to_r18",
    "__st_r13_to_r19", "__st_r13_to_r20", "__st_r13_to_r21", "__st_r13_to_r22",
    "__st_r13_to_r23", "__st_r13_to_r24", "__st_r13_to_r25",
}
Definition at line 32 of file ARCFrameLowering.cpp.
Referenced by llvm::ARCFrameLowering::emitPrologue().
UseSaveRestoreFunclet
cl::opt< bool > UseSaveRestoreFunclet("arc-save-restore-funclet", cl::Hidden, cl::desc("Use arc callee save/restore functions"), cl::init(true)) ("arc-save-restore-funclet" , cl::Hidden , cl::desc("Use arc callee save/restore functions") , cl::init(true)) static
Referenced by llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARCFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARCFrameLowering::restoreCalleeSavedRegisters(), and llvm::ARCFrameLowering::spillCalleeSavedRegisters().