LLVM: lib/Target/ARM/ARMMachineFunctionInfo.cpp File Reference
ARMMachineFunctionInfo.cpp File Reference
#include "ARMMachineFunctionInfo.h"
#include "ARMSubtarget.h"
Functions
static bool GetBranchTargetEnforcement (MachineFunction &MF)
static std::pair< bool, bool > GetSignReturnAddress (const Function &F)
Function Documentation
GetBranchTargetEnforcement()
static bool GetBranchTargetEnforcement (MachineFunction & MF) static
Definition at line 16 of file ARMMachineFunctionInfo.cpp.
References assert(), llvm::StringRef::equals_insensitive(), llvm::mdconst::extract_or_null(), F, llvm::MachineFunction::getFunction(), and llvm::MachineFunction::getSubtarget().
GetSignReturnAddress()
static std::pair< bool, bool > GetSignReturnAddress (const Function & F) static
Definition at line 38 of file ARMMachineFunctionInfo.cpp.
References llvm::All, assert(), llvm::mdconst::extract_or_null(), and F.