LLVM: lib/Analysis/AssumeBundleQueries.cpp File Reference
AssumeBundleQueries.cpp File Reference
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/DebugCounter.h"
Macros
#define DEBUG_TYPE "assume-queries"
Functions
STATISTIC (NumAssumeQueries, "Number of Queries into an assume assume bundles")
STATISTIC (NumUsefullAssumeQueries, "Number of Queries into an assume assume bundles that were satisfied")
DEBUG_COUNTER (AssumeQueryCounter, "assume-queries-counter", "Controls which assumes gets created")
static bool bundleHasArgument (const CallBase::BundleOpInfo &BOI, unsigned Idx)
static Value * getValueFromBundleOpInfo (AssumeInst &Assume, const CallBase::BundleOpInfo &BOI, unsigned Idx)
static CallInst::BundleOpInfo * getBundleFromUse (const Use *U)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "assume-queries"
Definition at line 19 of file AssumeBundleQueries.cpp.
Function Documentation
bundleHasArgument()
static bool bundleHasArgument (const CallBase::BundleOpInfo & BOI, unsigned Idx) static
Definition at line 32 of file AssumeBundleQueries.cpp.
References llvm::CallBase::BundleOpInfo::Begin, and llvm::CallBase::BundleOpInfo::End.
Referenced by llvm::fillMapFromAssume(), llvm::getKnowledgeFromBundle(), and getValueFromBundleOpInfo().
DEBUG_COUNTER()
DEBUG_COUNTER (AssumeQueryCounter , "assume-queries-counter" , "Controls which assumes gets created")
getBundleFromUse()
static CallInst::BundleOpInfo * getBundleFromUse (const Use * U) static
Definition at line 132 of file AssumeBundleQueries.cpp.
References llvm::cast(), Intr, llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Unless(), and llvm::PatternMatch::match().
Referenced by llvm::getKnowledgeForValue(), and llvm::getKnowledgeFromUse().
getValueFromBundleOpInfo()
static Value * getValueFromBundleOpInfo (AssumeInst & Assume, const CallBase::BundleOpInfo & BOI, unsigned Idx) static
Definition at line 36 of file AssumeBundleQueries.cpp.
References assert(), llvm::CallBase::BundleOpInfo::Begin, bundleHasArgument(), and llvm::User::op_begin().
Referenced by llvm::fillMapFromAssume(), llvm::getKnowledgeFromBundle(), and llvm::hasAttributeInAssume().
STATISTIC() [1/2]
STATISTIC (NumAssumeQueries , "Number of Queries into an assume assume bundles")
STATISTIC() [2/2]
STATISTIC (NumUsefullAssumeQueries , "Number of Queries into an assume assume bundles that were satisfied")