LLVM: lib/BinaryFormat/MachO.cpp File Reference
MachO.cpp File Reference
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/ARMTargetParser.h"
Functions
static MachO::CPUSubTypeX86 getX86SubType (const Triple &T)
static MachO::CPUSubTypeARM getARMSubType (const Triple &T)
static MachO::CPUSubTypeARM64 getARM64SubType (const Triple &T)
static MachO::CPUSubTypePowerPC getPowerPCSubType (const Triple &T)
static Error unsupported (const char *Str, const Triple &T)
Function Documentation
getARM64SubType()
static MachO::CPUSubTypeARM64 getARM64SubType (const Triple & T) static
Definition at line 57 of file MachO.cpp.
References assert(), llvm::MachO::CPU_SUBTYPE_ARM64_32_V8, llvm::MachO::CPU_SUBTYPE_ARM64_ALL, and llvm::MachO::CPU_SUBTYPE_ARM64E.
Referenced by llvm::MachO::getCPUSubType().
getARMSubType()
static MachO::CPUSubTypeARM getARMSubType (const Triple & T) static
Definition at line 26 of file MachO.cpp.
References assert(), llvm::MachO::CPU_SUBTYPE_ARM_V4T, llvm::MachO::CPU_SUBTYPE_ARM_V5, llvm::MachO::CPU_SUBTYPE_ARM_V6, llvm::MachO::CPU_SUBTYPE_ARM_V6M, llvm::MachO::CPU_SUBTYPE_ARM_V7, llvm::MachO::CPU_SUBTYPE_ARM_V7EM, llvm::MachO::CPU_SUBTYPE_ARM_V7K, llvm::MachO::CPU_SUBTYPE_ARM_V7M, llvm::MachO::CPU_SUBTYPE_ARM_V7S, and llvm::ARM::parseArch().
Referenced by llvm::MachO::getCPUSubType().
getPowerPCSubType()
static MachO::CPUSubTypePowerPC getPowerPCSubType (const Triple & T) static
Definition at line 67 of file MachO.cpp.
References llvm::MachO::CPU_SUBTYPE_POWERPC_ALL.
Referenced by llvm::MachO::getCPUSubType().
getX86SubType()
static MachO::CPUSubTypeX86 getX86SubType (const Triple & T) static
Definition at line 15 of file MachO.cpp.
References assert(), llvm::MachO::CPU_SUBTYPE_I386_ALL, llvm::MachO::CPU_SUBTYPE_X86_64_ALL, and llvm::MachO::CPU_SUBTYPE_X86_64_H.
Referenced by llvm::MachO::getCPUSubType().
unsupported()
static Error unsupported (const char * Str, const Triple & T) static
Definition at line 71 of file MachO.cpp.
References llvm::createStringError().
Referenced by llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::MachO::getCPUSubType(), llvm::MachO::getCPUType(), and llvm::getLibcallSignature().