LLVM: lib/Target/BPF/BPFTargetMachine.cpp File Reference
BPFTargetMachine.cpp File Reference
#include "BPFTargetMachine.h"
#include "BPF.h"
#include "BPFTargetTransformInfo.h"
#include "MCTargetDesc/BPFMCAsmInfo.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/SimplifyCFG.h"
#include "llvm/Transforms/Utils/SimplifyCFGOptions.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTarget ()
static std::string computeDataLayout (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
Variables
static cl::opt< bool > DisableMIPeephole ("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF"))
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 54 of file BPFTargetMachine.cpp.
References llvm::Triple::bpfeb.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 61 of file BPFTargetMachine.cpp.
References llvm::Reloc::PIC_.
LLVMInitializeBPFTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTarget ()
Definition at line 37 of file BPFTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), llvm::initializeBPFAbstractMemberAccessLegacyPassPass(), llvm::initializeBPFAdjustOptPass(), llvm::initializeBPFCheckAndAdjustIRPass(), llvm::initializeBPFIRPeepholePass(), llvm::initializeBPFMIPeepholePass(), llvm::initializeBPFMIPeepholeTruncElimPass(), llvm::initializeBPFPreserveDITypePass(), X, Y, and llvm::Z.
Variable Documentation
DisableMIPeephole
cl::opt< bool > DisableMIPeephole("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF")) ("disable-bpf-peephole" , cl::Hidden , cl::desc("Disable machine peepholes for BPF")) static