LLVM: llvm::WasmException Class Reference
llvm::WasmException Class Reference
#include "CodeGen/AsmPrinter/WasmException.h"
Public Member Functions
WasmException (AsmPrinter *A)
void endModule () override
Emit all sections that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void markFunctionEnd () override
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void endFragment ()
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginBasicBlock (const MachineBasicBlock &MBB)
Process beginning of a basic block during basic block sections.
virtual void endBasicBlock (const MachineBasicBlock &MBB)
Process end of a basic block during basic block sections.
Protected Member Functions
void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, SmallVectorImpl< CallSiteRange > &CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > &LandingPads, const SmallVectorImpl< unsigned > &FirstActions) override
Compute the call-site table and the call-site ranges.
Protected Member Functions inherited from llvm::EHStreamer
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, RangeMapType &PadMap)
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Additional Inherited Members
Static Public Member Functions inherited from llvm::EHStreamer
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Protected Types inherited from llvm::EHStreamer
using RangeMapType = DenseMap<MCSymbol *, PadRange>
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 25 of file WasmException.h.
Constructor & Destructor Documentation
WasmException()
llvm::WasmException::WasmException (AsmPrinter * A) inline
Definition at line 27 of file WasmException.h.
Member Function Documentation
beginFunction()
void llvm::WasmException::beginFunction (const MachineFunction * MF) inline override virtual
Gather pre-function debug information.
Every beginFunction(MF) call should be followed by an endFunction(MF) call.
Implements llvm::AsmPrinterHandler.
Definition at line 30 of file WasmException.h.
computeCallSiteTable()
void WasmException::computeCallSiteTable (SmallVectorImpl< CallSiteEntry > & CallSites, SmallVectorImpl< CallSiteRange > & CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > & LandingPads, const SmallVectorImpl< unsigned > & FirstActions) override protected virtual
Compute the call-site table and the call-site ranges.
Compute the call-site table.
The entry for an invoke has a try-range containing the call, a non-zero landing pad and an appropriate action. The entry for an ordinary call has a try-range containing the call and zero for the landing pad and the action. Calls marked 'nounwind' have no entry and must not be contained in the try-range of any entry - they form gaps in the table. Entries must be ordered by try-range address. CallSiteRanges vector is only populated for Itanium exception handling.
The entry for an invoke has a try-range containing the call, a non-zero landing pad, and an appropriate action. The entry for an ordinary call has a try-range containing the call and zero for the landing pad and the action. Calls marked 'nounwind' have no entry and must not be contained in the try-range of any entry - they form gaps in the table. Entries must be ordered by try-range address.
Call-sites are split into one or more call-site ranges associated with different sections of the function.
Without -basic-block-sections, all call-sites are grouped into one call-site-range corresponding to the function section.
With -basic-block-sections, one call-site range is created for each section, with its FragmentBeginLabel and FragmentEndLabel respectively
Reimplemented from llvm::EHStreamer.
Definition at line 88 of file WasmException.cpp.
References llvm::EHStreamer::Asm, llvm::MachineFunction::getWasmLandingPadIndex(), llvm::MachineFunction::hasWasmLandingPadIndex(), I, Info, llvm::AsmPrinter::MF, N, llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase< Size_T >::size().
endFunction()
void WasmException::endFunction (const MachineFunction * MF) override virtual
Gather post-function debug information.
Please note that some AsmPrinter implementations may not call beginFunction at all.
Implements llvm::AsmPrinterHandler.
Definition at line 55 of file WasmException.cpp.
References llvm::EHStreamer::Asm, assert(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::createTempSymbol(), llvm::EHStreamer::emitExceptionTable(), llvm::MachineFunction::getLandingPads(), llvm::MachineFunction::hasWasmLandingPadIndex(), and llvm::AsmPrinter::OutStreamer.
endModule()
void WasmException::endModule () override virtual
Emit all sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 22 of file WasmException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::Mangler::getNameWithPrefix(), llvm::AsmPrinter::isPositionIndependent(), llvm::MCContext::lookupSymbol(), llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
markFunctionEnd()
void WasmException::markFunctionEnd () override virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 45 of file WasmException.cpp.
References llvm::EHStreamer::Asm, llvm::MachineFunction::getLandingPads(), llvm::AsmPrinter::MF, and llvm::MachineFunction::tidyLandingPads().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/WasmException.h
lib/CodeGen/AsmPrinter/WasmException.cpp