LLVM: llvm::DwarfCFIExceptionBase Class Reference
llvm::DwarfCFIExceptionBase Class Reference
#include "CodeGen/AsmPrinter/DwarfException.h"
Protected Member Functions
DwarfCFIExceptionBase (AsmPrinter *A)
void markFunctionEnd () override
void endFragment () override
Protected Member Functions inherited from llvm::EHStreamer
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, RangeMapType &PadMap)
virtual void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, SmallVectorImpl< CallSiteRange > &CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > &LandingPads, const SmallVectorImpl< unsigned > &FirstActions)
Compute the call-site table and the call-site ranges.
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Protected Attributes
bool shouldEmitCFI = false
Per-function flag to indicate if frame CFI info should be emitted.
bool hasEmittedCFISections = false
Per-module flag to indicate if .cfi_section has beeen emitted.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Additional Inherited Members
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void endModule ()=0
Emit all sections that should come after the content.
virtual void beginFunction (const MachineFunction *MF)=0
Gather pre-function debug information.
virtual void endFunction (const MachineFunction *MF)=0
Gather post-function debug information.
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginBasicBlock (const MachineBasicBlock &MBB)
Process beginning of a basic block during basic block sections.
virtual void endBasicBlock (const MachineBasicBlock &MBB)
Process end of a basic block during basic block sections.
Static Public Member Functions inherited from llvm::EHStreamer
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Protected Types inherited from llvm::EHStreamer
using RangeMapType = DenseMap<MCSymbol *, PadRange>
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Detailed Description
Definition at line 24 of file DwarfException.h.
Constructor & Destructor Documentation
DwarfCFIExceptionBase()
DwarfCFIExceptionBase::DwarfCFIExceptionBase (AsmPrinter * A) protected
Definition at line 26 of file DwarfCFIException.cpp.
Member Function Documentation
endFragment()
void DwarfCFIExceptionBase::endFragment () override protected virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 38 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::MachineFunction::hasBBSections(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, and shouldEmitCFI.
Referenced by llvm::AIXException::markFunctionEnd(), and markFunctionEnd().
markFunctionEnd()
void DwarfCFIExceptionBase::markFunctionEnd () override protected virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 28 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, endFragment(), llvm::MachineFunction::getLandingPads(), llvm::AsmPrinter::MF, and llvm::MachineFunction::tidyLandingPads().
Member Data Documentation
hasEmittedCFISections
bool llvm::DwarfCFIExceptionBase::hasEmittedCFISections = false protected
Per-module flag to indicate if .cfi_section has beeen emitted.
Definition at line 31 of file DwarfException.h.
Referenced by llvm::DwarfCFIException::beginFragment(), and llvm::ARMException::beginFunction().
shouldEmitCFI
bool llvm::DwarfCFIExceptionBase::shouldEmitCFI = false protected
Per-function flag to indicate if frame CFI info should be emitted.
Definition at line 29 of file DwarfException.h.
Referenced by llvm::DwarfCFIException::beginFragment(), llvm::ARMException::beginFunction(), llvm::DwarfCFIException::beginFunction(), llvm::DwarfCFIException::endBasicBlock(), and endFragment().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfException.h
lib/CodeGen/AsmPrinter/DwarfCFIException.cpp