LLVM: llvm::PointerUnion< PTs > Class Template Reference
llvm::PointerUnion< PTs > Class Template Reference
A discriminated union of two or more pointer types, with the discriminator in the low bit of the pointer.
#include "llvm/ADT/PointerUnion.h"
Public Member Functions
PointerUnion ()=default
PointerUnion (std::nullptr_t)
bool isNull () const
Test if the pointer held in the union is null, regardless of which type it is.
operator bool () const
template<typename T >
bool is () const
Test if the Union currently holds the type matching T.
template<typename T >
T get () const
Returns the value of the specified pointer type.
template<typename T >
T dyn_cast () const
Returns the current pointer if it is of the specified pointer type, otherwise returns null.
First const * getAddrOfPtr1 () const
If the union is set to the first pointer type get an address pointing to it.
First * getAddrOfPtr1 ()
If the union is set to the first pointer type get an address pointing to it.
const PointerUnion & operator= (std::nullptr_t)
Assignment from nullptr which just clears the union.
void * getOpaqueValue () const
Static Public Member Functions
static PointerUnion getFromOpaqueValue (void *VP)
Friends
struct CastInfoPointerUnionImpl< PTs... >
This is needed to give the CastInfo implementation below access to protected members.
Detailed Description
template<typename... PTs>
class llvm::PointerUnion< PTs >
A discriminated union of two or more pointer types, with the discriminator in the low bit of the pointer.
This implementation is extremely efficient in space due to leveraging the low bits of the pointer, while exposing a natural and type-safe API.
Common use patterns would be something like this: PointerUnion<int*, float*> P; P = (int*)0; printf("%d %d", P.is<int*>(), P.is<float*>()); // prints "1 0" X = P.get<int*>(); // ok. Y = P.get<float*>(); // runtime assertion failure. Z = P.get<double*>(); // compile time failure. P = (float*)0; Y = P.get<float*>(); // ok. X = P.get<int*>(); // runtime assertion failure. PointerUnion<int*, int*> Q; // compile time failure.
Definition at line 112 of file PointerUnion.h.
Constructor & Destructor Documentation
PointerUnion() [1/2]
template<typename... PTs> llvm::PointerUnion< PTs >::PointerUnion () default
PointerUnion() [2/2]
template<typename... PTs> llvm::PointerUnion< PTs >::PointerUnion (std::nullptr_t) inline
Definition at line 137 of file PointerUnion.h.
Member Function Documentation
dyn_cast()
template<typename... PTs> template<typename T > T llvm::PointerUnion< PTs >::dyn_cast () const inline
Returns the current pointer if it is of the specified pointer type, otherwise returns null.
Definition at line 162 of file PointerUnion.h.
References llvm::dyn_cast().
Referenced by llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), getMemcpyLoadsAndStores(), llvm::RegisterBankInfo::getRegBank(), llvm::MachineRegisterInfo::getRegBankOrNull(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::LTOModule::hasCtorDtor(), and llvm::inferAlignFromPtrInfo().
get()
template<typename... PTs> template<typename T > T llvm::PointerUnion< PTs >::get () const inline
Returns the value of the specified pointer type.
If the specified pointer type is incorrect, assert.
Definition at line 155 of file PointerUnion.h.
References assert(), llvm::cast(), and llvm::isa().
Referenced by llvm::DIBuilder::createArrayType(), llvm::DwarfStringPoolEntryRef::DwarfStringPoolEntryRef(), llvm::PointerUnion< PTs >::getAddrOfPtr1(), llvm::ReplaceableMetadataImpl::getAllArgListUsers(), llvm::ContextAndReplaceableUses::getContext(), llvm::DwarfStringPoolEntryRef::getEntry(), llvm::ContextAndReplaceableUses::getReplaceableUses(), llvm::DwarfStringPoolEntryRef::getString(), llvm::ModuleSymbolTable::getSymbolFlags(), llvm::MachineMemOperand::MachineMemOperand(), llvm::MachineSDNode::memoperands(), llvm::ModuleSymbolTable::printSymbolName(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::ReplaceableMetadataImpl::SalvageDebugInfo(), and llvm::FunctionLoweringInfo::set().
getAddrOfPtr1() [1/2]
template<typename... PTs> First * llvm::PointerUnion< PTs >::getAddrOfPtr1 () inline
If the union is set to the first pointer type get an address pointing to it.
Definition at line 174 of file PointerUnion.h.
References assert(), llvm::PointerUnion< PTs >::get(), and llvm::PointerUnion< PTs >::is().
getAddrOfPtr1() [2/2]
template<typename... PTs> First const * llvm::PointerUnion< PTs >::getAddrOfPtr1 () const inline
If the union is set to the first pointer type get an address pointing to it.
Definition at line 168 of file PointerUnion.h.
References llvm::PointerUnion< PTs >::getAddrOfPtr1().
Referenced by llvm::TinyPtrVector< EltTy >::begin(), llvm::PointerUnion< PTs >::getAddrOfPtr1(), llvm::MachineSDNode::memoperands(), llvm::TinyPtrVector< EltTy >::operator ArrayRef< EltTy >(), and llvm::TinyPtrVector< EltTy >::operator MutableArrayRef< EltTy >().
getFromOpaqueValue()
template<typename... PTs> static PointerUnion llvm::PointerUnion< PTs >::getFromOpaqueValue (void * VP) inline static
Definition at line 194 of file PointerUnion.h.
References llvm::PointerUnion< PTs >::getFromOpaqueValue().
Referenced by llvm::PointerUnion< PTs >::getFromOpaqueValue(), and llvm::PointerLikeTypeTraits< PointerUnion< PTs... > >::getFromVoidPointer().
getOpaqueValue()
template<typename... PTs> void * llvm::PointerUnion< PTs >::getOpaqueValue () const inline
Definition at line 193 of file PointerUnion.h.
Referenced by llvm::DenseMapInfo< PointerUnion< PTs... > >::getHashValue(), llvm::DwarfStringPoolEntryRef::operator!=(), llvm::operator!=(), llvm::operator<(), llvm::DwarfStringPoolEntryRef::operator==(), and llvm::operator==().
is()
template<typename... PTs> template<typename T > bool llvm::PointerUnion< PTs >::is () const inline
Test if the Union currently holds the type matching T.
Definition at line 150 of file PointerUnion.h.
References llvm::isa().
Referenced by llvm::DIBuilder::createArrayType(), llvm::PointerUnion< PTs >::getAddrOfPtr1(), llvm::ReplaceableMetadataImpl::getAllArgListUsers(), llvm::DwarfStringPoolEntryRef::getEntry(), llvm::DwarfStringPoolEntryRef::getString(), llvm::ModuleSymbolTable::getSymbolFlags(), llvm::ContextAndReplaceableUses::hasReplaceableUses(), llvm::MachineMemOperand::MachineMemOperand(), llvm::ModuleSymbolTable::printSymbolName(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), and llvm::ReplaceableMetadataImpl::SalvageDebugInfo().
isNull()
template<typename... PTs> bool llvm::PointerUnion< PTs >::isNull () const inline
Test if the pointer held in the union is null, regardless of which type it is.
Definition at line 142 of file PointerUnion.h.
Referenced by llvm::TinyPtrVector< EltTy >::empty(), llvm::TinyPtrVector< EltTy >::end(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::TinyPtrVector< EltTy >::insert(), llvm::TinyPtrVector< EltTy >::insert(), llvm::MachineMemOperand::MachineMemOperand(), llvm::TinyPtrVector< EltTy >::operator ArrayRef< EltTy >(), llvm::DwarfStringPoolEntryRef::operator bool(), llvm::PointerUnion< PTs >::operator bool(), llvm::TinyPtrVector< EltTy >::operator MutableArrayRef< EltTy >(), llvm::TinyPtrVector< EltTy >::operator[](), and llvm::TinyPtrVector< EltTy >::push_back().
operator bool()
template<typename... PTs> llvm::PointerUnion< PTs >::operator bool () const inline explicit
Definition at line 144 of file PointerUnion.h.
References llvm::PointerUnion< PTs >::isNull().
operator=()
template<typename... PTs> const PointerUnion & llvm::PointerUnion< PTs >::operator= (std::nullptr_t) inline
Assignment from nullptr which just clears the union.
Definition at line 185 of file PointerUnion.h.
Friends And Related Symbol Documentation
CastInfoPointerUnionImpl< PTs... >
template<typename... PTs> friend struct CastInfoPointerUnionImpl< PTs... > friend
This is needed to give the CastInfo implementation below access to protected members.
Refer to its definition for further details.
Definition at line 119 of file PointerUnion.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/PointerUnion.h