LLVM: llvm::PPCSubtarget Class Reference
llvm::PPCSubtarget Class Reference
#include "Target/PowerPC/PPCSubtarget.h"
Public Types
enum POPCNTDKind { POPCNTD_Unavailable , POPCNTD_Slow , POPCNTD_Fast }
Public Member Functions
PPCSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const PPCTargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Align getStackAlignment () const
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getCPUDirective () const
getCPUDirective - Returns the -m directive specified for the cpu.
const InstrItineraryData * getInstrItineraryData () const override
getInstrItins - Return the instruction itineraries based on subtarget selection.
const PPCFrameLowering * getFrameLowering () const override
const PPCInstrInfo * getInstrInfo () const override
const PPCTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
const PPCRegisterInfo * getRegisterInfo () const override
const PPCTargetMachine & getTargetMachine () const
PPCSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
bool isPPC64 () const
isPPC64 - Return true if we are generating code for 64-bit pointer mode.
bool has64BitSupport () const
has64BitSupport - Return true if the selected CPU supports 64-bit instructions, regardless of whether we are in 32-bit or 64-bit mode.
bool useSoftFloat () const
bool use64BitRegs () const
use64BitRegs - Return true if in 64-bit mode or if we should use 64-bit registers in 32-bit mode when possible.
bool useCRBits () const
useCRBits - Return true if we should store and manipulate i1 values in the individual condition register bits.
bool isLittleEndian () const
bool hasFCPSGN () const
bool hasFSQRT () const
bool hasFRE () const
bool hasFRES () const
bool hasFRSQRTE () const
bool hasFRSQRTES () const
bool hasRecipPrec () const
bool hasSTFIWX () const
bool hasLFIWAX () const
bool hasFPRND () const
bool hasFPCVT () const
bool hasAltivec () const
bool hasSPE () const
bool hasEFPU2 () const
bool hasFPU () const
bool hasVSX () const
bool needsTwoConstNR () const
bool hasP8Vector () const
bool hasP8Altivec () const
bool hasP8Crypto () const
bool hasP9Vector () const
bool hasP9Altivec () const
bool hasP10Vector () const
bool hasPrefixInstrs () const
bool hasPCRelativeMemops () const
bool hasMMA () const
bool hasROPProtect () const
bool hasPrivileged () const
bool pairedVectorMemops () const
bool hasMFOCRF () const
bool hasISEL () const
bool hasBPERMD () const
bool hasExtDiv () const
bool hasCMPB () const
bool hasLDBRX () const
bool isBookE () const
bool hasOnlyMSYNC () const
bool isPPC4xx () const
bool isPPC6xx () const
bool isSecurePlt () const
bool vectorsUseTwoUnits () const
bool isE500 () const
bool isFeatureMFTB () const
bool allowsUnalignedFPAccess () const
bool isDeprecatedDST () const
bool hasICBT () const
bool hasInvariantFunctionDescriptors () const
bool usePPCPreRASchedStrategy () const
bool usePPCPostRASchedStrategy () const
bool hasPartwordAtomics () const
bool hasQuadwordAtomics () const
bool hasDirectMove () const
Align getPlatformStackAlignment () const
unsigned getRedZoneSize () const
bool hasHTM () const
bool hasFloat128 () const
bool isISA2_06 () const
bool isISA2_07 () const
bool isISA3_0 () const
bool isISA3_1 () const
bool isISAFuture () const
bool useLongCalls () const
bool hasFusion () const
bool hasStoreFusion () const
bool hasAddiLoadFusion () const
bool hasAddisLoadFusion () const
bool hasArithAddFusion () const
bool hasAddLogicalFusion () const
bool hasLogicalAddFusion () const
bool hasLogicalFusion () const
bool hasCompareFusion () const
bool hasWideImmFusion () const
bool hasSha3Fusion () const
bool hasZeroMoveFusion () const
bool hasBack2BackFusion () const
bool needsSwapsForVSXMemOps () const
POPCNTDKind hasPOPCNTD () const
const Triple & getTargetTriple () const
bool isTargetELF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isAIXABI () const
bool isSVR4ABI () const
bool isELFv2ABI () const
bool is64BitELFABI () const
bool is32BitELFABI () const
bool isUsingPCRelativeCalls () const
bool enableEarlyIfConversion () const override
Originally, this function return hasISEL().
bool enableMachineScheduler () const override
Scheduling customization.
bool enableMachinePipeliner () const override
Pipeliner customization.
bool useDFAforSMS () const override
Machine Pipeliner customization.
bool enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
AntiDepBreakMode getAntiDepBreakMode () const override
void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, unsigned NumRegionInstrs) const override
bool useAA () const override
bool enableSubRegLiveness () const override
bool isGVIndirectSymbol (const GlobalValue *GV) const
True if the GV will be accessed via an indirect symbol.
bool usesFunctionDescriptors () const
True if the ABI is descriptor based.
unsigned descriptorTOCAnchorOffset () const
unsigned descriptorEnvironmentPointerOffset () const
MCRegister getEnvironmentPointerRegister () const
MCRegister getTOCPointerRegister () const
MCRegister getStackPointerRegister () const
bool isXRaySupported () const override
bool isPredictableSelectIsExpensive () const
unsigned getGPRAllocationOrderIdx () const
const CallLowering * getCallLowering () const override
const RegisterBankInfo * getRegBankInfo () const override
const LegalizerInfo * getLegalizerInfo () const override
InstructionSelector * getInstructionSelector () const override
Protected Attributes
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
Align StackAlignment
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
InstrItineraryData InstrItins
Selected instruction itineraries (one entry per itinerary class.)
unsigned CPUDirective
Which cpu directive was used.
bool HasMFOCRF
Used by the ISel to turn in optimizations for POWER4-derived architectures.
bool Has64BitSupport
bool Use64BitRegs
bool UseCRBits
bool HasHardFloat
bool IsPPC64
bool HasAltivec
bool HasFPU
bool HasSPE
bool HasEFPU2
bool HasVSX
bool NeedsTwoConstNR
bool HasP8Vector
bool HasP8Altivec
bool HasP8Crypto
bool HasP9Vector
bool HasP9Altivec
bool HasP10Vector
bool HasPrefixInstrs
bool HasPCRelativeMemops
bool HasMMA
bool HasROPProtect
bool HasPrivileged
bool HasFCPSGN
bool HasFSQRT
bool HasFRE
bool HasFRES
bool HasFRSQRTE
bool HasFRSQRTES
bool HasRecipPrec
bool HasSTFIWX
bool HasLFIWAX
bool HasFPRND
bool HasFPCVT
bool HasISEL
bool HasBPERMD
bool HasExtDiv
bool HasCMPB
bool HasLDBRX
bool IsBookE
bool HasOnlyMSYNC
bool IsE500
bool IsPPC4xx
bool IsPPC6xx
bool FeatureMFTB
bool AllowsUnalignedFPAccess
bool DeprecatedDST
bool IsLittleEndian
bool HasICBT
bool HasInvariantFunctionDescriptors
bool HasPartwordAtomics
bool HasQuadwordAtomics
bool HasDirectMove
bool HasHTM
bool HasFloat128
bool HasFusion
bool HasStoreFusion
bool HasAddiLoadFusion
bool HasAddisLoadFusion
bool HasArithAddFusion
bool HasAddLogicalFusion
bool HasLogicalAddFusion
bool HasLogicalFusion
bool HasSha3Fusion
bool HasCompareFusion
bool HasWideImmFusion
bool HasZeroMoveFusion
bool HasBack2BackFusion
bool IsISA2_06
bool IsISA2_07
bool IsISA3_0
bool IsISA3_1
bool IsISAFuture
bool UseLongCalls
bool SecurePlt
bool VectorsUseTwoUnits
bool UsePPCPreRASchedStrategy
bool UsePPCPostRASchedStrategy
bool PairedVectorMemops
bool PredictableSelectIsExpensive
bool HasModernAIXAs
bool IsAIX
POPCNTDKind HasPOPCNTD
const PPCTargetMachine & TM
PPCFrameLowering FrameLowering
PPCInstrInfo InstrInfo
PPCTargetLowering TLInfo
SelectionDAGTargetInfo TSInfo
std::unique_ptr< CallLowering > CallLoweringInfo
GlobalISel related APIs.
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
std::unique_ptr< InstructionSelector > InstSelector
Detailed Description
Definition at line 71 of file PPCSubtarget.h.
Member Enumeration Documentation
POPCNTDKind
enum llvm::PPCSubtarget::POPCNTDKind
Enumerator
POPCNTD_Unavailable
POPCNTD_Slow
POPCNTD_Fast
Definition at line 73 of file PPCSubtarget.h.
Constructor & Destructor Documentation
PPCSubtarget()
PPCSubtarget::PPCSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const PPCTargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 55 of file PPCSubtarget.cpp.
References CallLoweringInfo, llvm::createPPCInstructionSelector(), getRegisterInfo(), getTargetLowering(), InstSelector, RegBankInfo, and TM.
Member Function Documentation
allowsUnalignedFPAccess()
bool llvm::PPCSubtarget::allowsUnalignedFPAccess () const inline
Definition at line 308 of file PPCSubtarget.h.
References AllowsUnalignedFPAccess.
Referenced by llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses().
descriptorEnvironmentPointerOffset()
unsigned llvm::PPCSubtarget::descriptorEnvironmentPointerOffset () const inline
Definition at line 412 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by prepareDescriptorIndirectCall().
descriptorTOCAnchorOffset()
unsigned llvm::PPCSubtarget::descriptorTOCAnchorOffset () const inline
Definition at line 406 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by prepareDescriptorIndirectCall().
enableEarlyIfConversion()
bool llvm::PPCSubtarget::enableEarlyIfConversion () const inline override
Originally, this function return hasISEL().
Now we always enable it, but may expand the ISEL instruction later.
Definition at line 377 of file PPCSubtarget.h.
enableMachinePipeliner()
bool PPCSubtarget::enableMachinePipeliner () const override
Pipeliner customization.
Definition at line 205 of file PPCSubtarget.cpp.
References EnableMachinePipeliner.
enableMachineScheduler()
bool PPCSubtarget::enableMachineScheduler () const override
Scheduling customization.
Definition at line 203 of file PPCSubtarget.cpp.
Referenced by llvm::PPCTargetLowering::getSchedulingPreference(), and llvm::PPCTargetLowering::PPCTargetLowering().
enablePostRAScheduler()
bool PPCSubtarget::enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
Definition at line 212 of file PPCSubtarget.cpp.
enableSubRegLiveness()
bool PPCSubtarget::enableSubRegLiveness () const override
Definition at line 241 of file PPCSubtarget.cpp.
References UseSubRegLiveness.
getAntiDepBreakMode()
PPCGenSubtargetInfo::AntiDepBreakMode PPCSubtarget::getAntiDepBreakMode () const override
Definition at line 214 of file PPCSubtarget.cpp.
getCallLowering()
const CallLowering * PPCSubtarget::getCallLowering () const override
Definition at line 263 of file PPCSubtarget.cpp.
References CallLoweringInfo.
getCPUDirective()
unsigned llvm::PPCSubtarget::getCPUDirective () const inline
getCPUDirective - Returns the -m directive specified for the cpu.
Definition at line 206 of file PPCSubtarget.h.
References CPUDirective.
Referenced by llvm::PPCTTIImpl::enableAggressiveInterleaving(), llvm::PPCTTIImpl::getCacheLineSize(), llvm::PPCTTIImpl::getMaxInterleaveFactor(), llvm::PPCInstrInfo::getOperandLatency(), llvm::PPCTargetLowering::getPrefLoopAlignment(), llvm::PPCTTIImpl::getUnrollingPreferences(), llvm::PPCTTIImpl::getVPMemoryOpCost(), llvm::PPCInstrInfo::insertNoop(), and llvm::PPCTargetLowering::PPCTargetLowering().
getCriticalPathRCs()
void PPCSubtarget::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const override
Definition at line 218 of file PPCSubtarget.cpp.
References isPPC64().
getEnvironmentPointerRegister()
MCRegister llvm::PPCSubtarget::getEnvironmentPointerRegister () const inline
Definition at line 418 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by buildCallOperands(), and prepareDescriptorIndirectCall().
getFrameLowering()
const PPCFrameLowering * llvm::PPCSubtarget::getFrameLowering () const inline override
Definition at line 214 of file PPCSubtarget.h.
References FrameLowering.
Referenced by buildCallOperands(), EmitTailCallStoreFPAndRetAddr(), llvm::PPCTargetLowering::getStackProbeSize(), llvm::PPCInstrInfo::isTOCSaveMI(), and needStackSlotPassParameters().
getGPRAllocationOrderIdx()
unsigned llvm::PPCSubtarget::getGPRAllocationOrderIdx () const inline
Definition at line 442 of file PPCSubtarget.h.
References is64BitELFABI(), and isAIXABI().
getInstrInfo()
const PPCInstrInfo * llvm::PPCSubtarget::getInstrInfo () const inline override
Definition at line 217 of file PPCSubtarget.h.
References InstrInfo.
Referenced by llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCTargetLowering::getPrefLoopAlignment(), getRegisterInfo(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
getInstrItineraryData()
const InstrItineraryData * llvm::PPCSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 210 of file PPCSubtarget.h.
References InstrItins.
getInstructionSelector()
InstructionSelector * PPCSubtarget::getInstructionSelector () const override
Definition at line 275 of file PPCSubtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * PPCSubtarget::getLegalizerInfo () const override
Definition at line 271 of file PPCSubtarget.cpp.
getPlatformStackAlignment()
Align llvm::PPCSubtarget::getPlatformStackAlignment () const inline
Definition at line 320 of file PPCSubtarget.h.
References Align.
getRedZoneSize()
unsigned llvm::PPCSubtarget::getRedZoneSize () const inline
Definition at line 324 of file PPCSubtarget.h.
References isAIXABI(), and isPPC64().
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), and llvm::PPCFrameLowering::inlineStackProbe().
getRegBankInfo()
const RegisterBankInfo * PPCSubtarget::getRegBankInfo () const override
Definition at line 267 of file PPCSubtarget.cpp.
References RegBankInfo.
getRegisterInfo()
const PPCRegisterInfo * llvm::PPCSubtarget::getRegisterInfo () const inline override
Definition at line 224 of file PPCSubtarget.h.
References getInstrInfo(), and llvm::PPCInstrInfo::getRegisterInfo().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), buildCallOperands(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), PPCSubtarget(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::PPCFrameLowering::replaceFPWithRealFP().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::PPCSubtarget::getSelectionDAGInfo () const inline override
Definition at line 221 of file PPCSubtarget.h.
References TSInfo.
getStackAlignment()
Align llvm::PPCSubtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 202 of file PPCSubtarget.h.
References StackAlignment.
getStackPointerRegister()
MCRegister llvm::PPCSubtarget::getStackPointerRegister () const inline
Definition at line 430 of file PPCSubtarget.h.
References IsPPC64.
Referenced by buildCallOperands(), and llvm::PPCRegisterInfo::isCallerPreservedPhysReg().
getTargetLowering()
const PPCTargetLowering * llvm::PPCSubtarget::getTargetLowering () const inline override
Definition at line 218 of file PPCSubtarget.h.
References TLInfo.
Referenced by llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), and PPCSubtarget().
getTargetMachine()
const PPCTargetMachine & llvm::PPCSubtarget::getTargetMachine () const inline
Definition at line 227 of file PPCSubtarget.h.
References TM.
Referenced by computeBasePointerSaveOffset(), llvm::PPCInstrInfo::getMachineCombinerPatterns(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isUsingPCRelativeCalls(), llvm::PPCTTIImpl::shouldBuildRelLookupTables(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), and transformCallee().
getTargetTriple()
const Triple & llvm::PPCSubtarget::getTargetTriple () const inline
Definition at line 361 of file PPCSubtarget.h.
References TargetTriple.
Referenced by llvm::PPCTargetLowering::shouldInlineQuadwordAtomics().
getTOCPointerRegister()
MCRegister llvm::PPCSubtarget::getTOCPointerRegister () const inline
Definition at line 424 of file PPCSubtarget.h.
References assert(), is64BitELFABI(), isAIXABI(), and IsPPC64.
Referenced by buildCallOperands(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), and prepareDescriptorIndirectCall().
has64BitSupport()
bool llvm::PPCSubtarget::has64BitSupport () const inline
has64BitSupport - Return true if the selected CPU supports 64-bit instructions, regardless of whether we are in 32-bit or 64-bit mode.
Definition at line 244 of file PPCSubtarget.h.
References Has64BitSupport.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasAddiLoadFusion()
bool llvm::PPCSubtarget::hasAddiLoadFusion () const inline
Definition at line 344 of file PPCSubtarget.h.
References HasAddiLoadFusion.
hasAddisLoadFusion()
bool llvm::PPCSubtarget::hasAddisLoadFusion () const inline
Definition at line 345 of file PPCSubtarget.h.
References HasAddisLoadFusion.
hasAddLogicalFusion()
bool llvm::PPCSubtarget::hasAddLogicalFusion () const inline
Definition at line 347 of file PPCSubtarget.h.
References HasAddLogicalFusion.
hasAltivec()
bool llvm::PPCSubtarget::hasAltivec () const inline
Definition at line 276 of file PPCSubtarget.h.
References HasAltivec.
Referenced by llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTTIImpl::getRegisterBitWidth(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTargetLowering::PerformDAGCombine(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasArithAddFusion()
bool llvm::PPCSubtarget::hasArithAddFusion () const inline
Definition at line 346 of file PPCSubtarget.h.
References HasArithAddFusion.
hasBack2BackFusion()
bool llvm::PPCSubtarget::hasBack2BackFusion () const inline
Definition at line 354 of file PPCSubtarget.h.
References HasBack2BackFusion.
hasBPERMD()
bool llvm::PPCSubtarget::hasBPERMD () const inline
Definition at line 296 of file PPCSubtarget.h.
References HasBPERMD.
hasCMPB()
bool llvm::PPCSubtarget::hasCMPB () const inline
Definition at line 298 of file PPCSubtarget.h.
References HasCMPB.
hasCompareFusion()
bool llvm::PPCSubtarget::hasCompareFusion () const inline
Definition at line 350 of file PPCSubtarget.h.
References HasCompareFusion.
hasDirectMove()
bool llvm::PPCSubtarget::hasDirectMove () const inline
Definition at line 318 of file PPCSubtarget.h.
References HasDirectMove.
Referenced by llvm::PPCInstrInfo::copyPhysReg(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::PPCTargetLowering::shouldExpandBuildVectorWithShuffles().
hasEFPU2()
bool llvm::PPCSubtarget::hasEFPU2 () const inline
Definition at line 278 of file PPCSubtarget.h.
References HasEFPU2.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasExtDiv()
bool llvm::PPCSubtarget::hasExtDiv () const inline
Definition at line 297 of file PPCSubtarget.h.
References HasExtDiv.
hasFCPSGN()
bool llvm::PPCSubtarget::hasFCPSGN () const inline
Definition at line 265 of file PPCSubtarget.h.
References HasFCPSGN.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFloat128()
bool llvm::PPCSubtarget::hasFloat128 () const inline
Definition at line 335 of file PPCSubtarget.h.
References HasFloat128.
hasFPCVT()
bool llvm::PPCSubtarget::hasFPCVT () const inline
Definition at line 275 of file PPCSubtarget.h.
References HasFPCVT.
Referenced by convertFPToInt(), convertIntToFP(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasFPRND()
bool llvm::PPCSubtarget::hasFPRND () const inline
Definition at line 274 of file PPCSubtarget.h.
References HasFPRND.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFPU()
bool llvm::PPCSubtarget::hasFPU () const inline
Definition at line 279 of file PPCSubtarget.h.
References HasFPU.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFRE()
bool llvm::PPCSubtarget::hasFRE () const inline
Definition at line 267 of file PPCSubtarget.h.
References HasFRE.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFRES()
bool llvm::PPCSubtarget::hasFRES () const inline
Definition at line 268 of file PPCSubtarget.h.
References HasFRES.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFRSQRTE()
bool llvm::PPCSubtarget::hasFRSQRTE () const inline
Definition at line 269 of file PPCSubtarget.h.
References HasFRSQRTE.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFRSQRTES()
bool llvm::PPCSubtarget::hasFRSQRTES () const inline
Definition at line 270 of file PPCSubtarget.h.
References HasFRSQRTES.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFSQRT()
bool llvm::PPCSubtarget::hasFSQRT () const inline
Definition at line 266 of file PPCSubtarget.h.
References HasFSQRT.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasFusion()
bool llvm::PPCSubtarget::hasFusion () const inline
Definition at line 342 of file PPCSubtarget.h.
References HasFusion.
hasHTM()
bool llvm::PPCSubtarget::hasHTM () const inline
Definition at line 334 of file PPCSubtarget.h.
References HasHTM.
hasICBT()
bool llvm::PPCSubtarget::hasICBT () const inline
Definition at line 310 of file PPCSubtarget.h.
References HasICBT.
hasInvariantFunctionDescriptors()
bool llvm::PPCSubtarget::hasInvariantFunctionDescriptors () const inline
Definition at line 311 of file PPCSubtarget.h.
References HasInvariantFunctionDescriptors.
Referenced by prepareDescriptorIndirectCall().
hasISEL()
bool llvm::PPCSubtarget::hasISEL () const inline
Definition at line 295 of file PPCSubtarget.h.
References HasISEL.
hasLDBRX()
bool llvm::PPCSubtarget::hasLDBRX () const inline
Definition at line 299 of file PPCSubtarget.h.
References HasLDBRX.
Referenced by llvm::PPCTargetLowering::PerformDAGCombine().
hasLFIWAX()
bool llvm::PPCSubtarget::hasLFIWAX () const inline
Definition at line 273 of file PPCSubtarget.h.
References HasLFIWAX.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
hasLogicalAddFusion()
bool llvm::PPCSubtarget::hasLogicalAddFusion () const inline
Definition at line 348 of file PPCSubtarget.h.
References HasLogicalAddFusion.
hasLogicalFusion()
bool llvm::PPCSubtarget::hasLogicalFusion () const inline
Definition at line 349 of file PPCSubtarget.h.
References HasLogicalFusion.
hasMFOCRF()
bool llvm::PPCSubtarget::hasMFOCRF () const inline
Definition at line 294 of file PPCSubtarget.h.
References HasMFOCRF.
hasMMA()
bool llvm::PPCSubtarget::hasMMA () const inline
Definition at line 290 of file PPCSubtarget.h.
References HasMMA.
Referenced by llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasOnlyMSYNC()
bool llvm::PPCSubtarget::hasOnlyMSYNC () const inline
Definition at line 301 of file PPCSubtarget.h.
References HasOnlyMSYNC.
hasP10Vector()
bool llvm::PPCSubtarget::hasP10Vector () const inline
Definition at line 287 of file PPCSubtarget.h.
References HasP10Vector.
Referenced by llvm::PPCTTIImpl::hasActiveVectorLength(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasP8Altivec()
bool llvm::PPCSubtarget::hasP8Altivec () const inline
Definition at line 283 of file PPCSubtarget.h.
References HasP8Altivec.
Referenced by getVectorCompareInfo(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasP8Crypto()
bool llvm::PPCSubtarget::hasP8Crypto () const inline
Definition at line 284 of file PPCSubtarget.h.
References HasP8Crypto.
hasP8Vector()
bool llvm::PPCSubtarget::hasP8Vector () const inline
Definition at line 282 of file PPCSubtarget.h.
References HasP8Vector.
Referenced by llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
hasP9Altivec()
bool llvm::PPCSubtarget::hasP9Altivec () const inline
Definition at line 286 of file PPCSubtarget.h.
References HasP9Altivec.
Referenced by getVectorCompareInfo(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCTargetLowering::PerformDAGCombine(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasP9Vector()
bool llvm::PPCSubtarget::hasP9Vector () const inline
Definition at line 285 of file PPCSubtarget.h.
References HasP9Vector.
Referenced by llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::PPCInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::PPCInstrInfo::instrHasImmForm(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isLegalAddressingMode(), needsSwapsForVSXMemOps(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
hasPartwordAtomics()
bool llvm::PPCSubtarget::hasPartwordAtomics () const inline
Definition at line 316 of file PPCSubtarget.h.
References HasPartwordAtomics.
Referenced by llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), and llvm::PPCTargetLowering::EmitPartwordAtomicBinary().
hasPCRelativeMemops()
bool llvm::PPCSubtarget::hasPCRelativeMemops () const inline
Definition at line 289 of file PPCSubtarget.h.
References HasPCRelativeMemops.
Referenced by isUsingPCRelativeCalls().
hasPOPCNTD()
POPCNTDKind llvm::PPCSubtarget::hasPOPCNTD () const inline
Definition at line 359 of file PPCSubtarget.h.
References HasPOPCNTD.
Referenced by llvm::PPCTTIImpl::getPopcntSupport(), and llvm::PPCTargetLowering::PPCTargetLowering().
hasPrefixInstrs()
bool llvm::PPCSubtarget::hasPrefixInstrs () const inline
Definition at line 288 of file PPCSubtarget.h.
References HasPrefixInstrs.
Referenced by llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::isFPImmLegal(), and selectI64Imm().
hasPrivileged()
bool llvm::PPCSubtarget::hasPrivileged () const inline
Definition at line 292 of file PPCSubtarget.h.
References HasPrivileged.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), and llvm::PPCFrameLowering::emitPrologue().
hasQuadwordAtomics()
bool llvm::PPCSubtarget::hasQuadwordAtomics () const inline
Definition at line 317 of file PPCSubtarget.h.
References HasQuadwordAtomics.
Referenced by llvm::PPCTargetLowering::shouldInlineQuadwordAtomics().
hasRecipPrec()
bool llvm::PPCSubtarget::hasRecipPrec () const inline
Definition at line 271 of file PPCSubtarget.h.
References HasRecipPrec.
Referenced by getEstimateRefinementSteps().
hasROPProtect()
bool llvm::PPCSubtarget::hasROPProtect () const inline
Definition at line 291 of file PPCSubtarget.h.
References HasROPProtect.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), and llvm::PPCRegisterInfo::requiresVirtualBaseRegisters().
hasSha3Fusion()
bool llvm::PPCSubtarget::hasSha3Fusion () const inline
Definition at line 352 of file PPCSubtarget.h.
References HasSha3Fusion.
hasSPE()
bool llvm::PPCSubtarget::hasSPE () const inline
Definition at line 277 of file PPCSubtarget.h.
References HasSPE.
Referenced by llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), getPredicateForSetCC(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::hasSPE(), llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
hasSTFIWX()
bool llvm::PPCSubtarget::hasSTFIWX () const inline
Definition at line 272 of file PPCSubtarget.h.
References HasSTFIWX.
hasStoreFusion()
bool llvm::PPCSubtarget::hasStoreFusion () const inline
Definition at line 343 of file PPCSubtarget.h.
References HasStoreFusion.
hasVSX()
bool llvm::PPCSubtarget::hasVSX () const inline
Definition at line 280 of file PPCSubtarget.h.
References HasVSX.
Referenced by llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getNumberOfRegisters(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTTIImpl::getRegisterClassForType(), getVectorCompareInfo(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCTargetLowering::isFPImmLegal(), isValidSplatLoad(), needsSwapsForVSXMemOps(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCTargetLowering::shouldExpandBuildVectorWithShuffles(), and llvm::PPCInstrInfo::updatedRC().
hasWideImmFusion()
bool llvm::PPCSubtarget::hasWideImmFusion () const inline
Definition at line 351 of file PPCSubtarget.h.
References HasWideImmFusion.
hasZeroMoveFusion()
bool llvm::PPCSubtarget::hasZeroMoveFusion () const inline
Definition at line 353 of file PPCSubtarget.h.
References HasZeroMoveFusion.
initializeSubtargetDependencies()
PPCSubtarget & PPCSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
Definition at line 48 of file PPCSubtarget.cpp.
is32BitELFABI()
bool llvm::PPCSubtarget::is32BitELFABI () const inline
Definition at line 372 of file PPCSubtarget.h.
References isPPC64(), and isSVR4ABI().
Referenced by buildCallOperands(), computeBasePointerSaveOffset(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), and transformCallee().
is64BitELFABI()
bool llvm::PPCSubtarget::is64BitELFABI () const inline
Definition at line 371 of file PPCSubtarget.h.
References isPPC64(), and isSVR4ABI().
Referenced by buildCallOperands(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCallOpcode(), getGPRAllocationOrderIdx(), getTOCPointerRegister(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), isTOCSaveRestoreRequired(), needStackSlotPassParameters(), llvm::PPCTargetLowering::PPCTargetLowering(), and usesFunctionDescriptors().
isAIXABI()
bool llvm::PPCSubtarget::isAIXABI () const inline
Definition at line 367 of file PPCSubtarget.h.
References llvm::Triple::isOSAIX(), and TargetTriple.
Referenced by buildCallOperands(), computeCRSaveOffset(), computeLinkageSize(), computeReturnSaveOffset(), computeTOCSaveOffset(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCallOpcode(), llvm::PPCRegisterInfo::getCallPreservedMask(), getGPRAllocationOrderIdx(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), getRedZoneSize(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTargetLowering::getSDagStackGuard(), getTOCPointerRegister(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCTargetLowering::insertSSPDeclarations(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::PPCTargetLowering::isJumpTableRelative(), isSVR4ABI(), isTOCSaveRestoreRequired(), prepareDescriptorIndirectCall(), transformCallee(), usesFunctionDescriptors(), and useSoftFloat().
isBookE()
bool llvm::PPCSubtarget::isBookE () const inline
Definition at line 300 of file PPCSubtarget.h.
References IsBookE.
isDeprecatedDST()
bool llvm::PPCSubtarget::isDeprecatedDST () const inline
Definition at line 309 of file PPCSubtarget.h.
References DeprecatedDST.
isE500()
bool llvm::PPCSubtarget::isE500 () const inline
Definition at line 306 of file PPCSubtarget.h.
References IsE500.
isELFv2ABI()
bool PPCSubtarget::isELFv2ABI () const
Definition at line 254 of file PPCSubtarget.cpp.
References llvm::PPCTargetMachine::isELFv2ABI(), and TM.
Referenced by computeLinkageSize(), computeTOCSaveOffset(), llvm::PPCFrameLowering::emitPrologue(), GetInitialOffset(), isIndirectCall(), isUsingPCRelativeCalls(), transformCallee(), and usesFunctionDescriptors().
isFeatureMFTB()
bool llvm::PPCSubtarget::isFeatureMFTB () const inline
Definition at line 307 of file PPCSubtarget.h.
References FeatureMFTB.
isGVIndirectSymbol()
bool PPCSubtarget::isGVIndirectSymbol (const GlobalValue * GV) const
True if the GV will be accessed via an indirect symbol.
Definition at line 245 of file PPCSubtarget.cpp.
References llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::getParent(), llvm::CodeModel::Large, llvm::TargetMachine::shouldAssumeDSOLocal(), and TM.
Referenced by llvm::PPCTargetLowering::isAccessedAsGotIndirect().
isISA2_06()
bool llvm::PPCSubtarget::isISA2_06 () const inline
Definition at line 336 of file PPCSubtarget.h.
References IsISA2_06.
isISA2_07()
bool llvm::PPCSubtarget::isISA2_07 () const inline
Definition at line 337 of file PPCSubtarget.h.
References IsISA2_07.
isISA3_0()
bool llvm::PPCSubtarget::isISA3_0 () const inline
Definition at line 338 of file PPCSubtarget.h.
References IsISA3_0.
Referenced by llvm::PPCRegisterInfo::lowerCRBitSpilling(), and llvm::PPCTargetLowering::PPCTargetLowering().
isISA3_1()
bool llvm::PPCSubtarget::isISA3_1 () const inline
Definition at line 339 of file PPCSubtarget.h.
References IsISA3_1.
Referenced by getVectorCompareInfo(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), and llvm::PPCTargetLowering::PPCTargetLowering().
isISAFuture()
bool llvm::PPCSubtarget::isISAFuture () const inline
Definition at line 340 of file PPCSubtarget.h.
References IsISAFuture.
isLittleEndian()
bool llvm::PPCSubtarget::isLittleEndian () const inline
Definition at line 262 of file PPCSubtarget.h.
References IsLittleEndian.
Referenced by llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), fixupShuffleMaskForPermutedSToV(), getSToVPermuted(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), needsSwapsForVSXMemOps(), and llvm::PPCTargetLowering::PerformDAGCombine().
isPPC4xx()
bool llvm::PPCSubtarget::isPPC4xx () const inline
Definition at line 302 of file PPCSubtarget.h.
References IsPPC4xx.
isPPC64()
bool PPCSubtarget::isPPC64 () const
isPPC64 - Return true if we are generating code for 64-bit pointer mode.
Definition at line 255 of file PPCSubtarget.cpp.
References llvm::PPCTargetMachine::isPPC64(), and TM.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCInstrInfo::analyzeBranch(), buildCallOperands(), llvm::PPCTargetLowering::BuildSDIVPow2(), CC_AIX(), combineADDToADDZE(), computeBasePointerSaveOffset(), computeCRSaveOffset(), computeFramePointerSaveOffset(), computeLinkageSize(), computeReturnSaveOffset(), computeTOCSaveOffset(), llvm::PPC::createFastISel(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), EmitTailCallStoreFPAndRetAddr(), llvm::PPCTargetLowering::emitTrailingFence(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::findLoopInstr(), llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCriticalPathRCs(), llvm::PPCTargetLowering::getExceptionPointerRegister(), llvm::PPCTargetLowering::getExceptionSelectorRegister(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), getRedZoneSize(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTTIImpl::getRegisterBitWidth(), llvm::PPCTargetLowering::getRegisterByName(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCInstrInfo::insertBranch(), is32BitELFABI(), is64BitELFABI(), llvm::PPCInstrInfo::isBDNZ(), llvm::PPCTargetLowering::isJumpTableRelative(), llvm::PPCInstrInfo::isTOCSaveMI(), isUsingPCRelativeCalls(), llvm::PPCTargetLowering::isZExtFree(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::PPCInstrInfo::onlyFoldImmediate(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCInstrInfo::PredicateInstruction(), prepareDescriptorIndirectCall(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), llvm::PPCTargetLowering::SelectForceXFormMode(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::PPCTargetLowering::shouldInlineQuadwordAtomics(), and llvm::PPCInstrInfo::shouldReduceRegisterPressure().
isPPC6xx()
bool llvm::PPCSubtarget::isPPC6xx () const inline
Definition at line 303 of file PPCSubtarget.h.
References IsPPC6xx.
isPredictableSelectIsExpensive()
bool llvm::PPCSubtarget::isPredictableSelectIsExpensive () const inline
Definition at line 436 of file PPCSubtarget.h.
References PredictableSelectIsExpensive.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
isSecurePlt()
bool llvm::PPCSubtarget::isSecurePlt () const inline
Definition at line 304 of file PPCSubtarget.h.
References SecurePlt.
Referenced by GetSymbolRef().
isSVR4ABI()
bool llvm::PPCSubtarget::isSVR4ABI () const inline
Definition at line 368 of file PPCSubtarget.h.
References isAIXABI().
Referenced by llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCFrameLowering::inlineStackProbe(), is32BitELFABI(), is64BitELFABI(), llvm::PPCInstrInfo::isSignOrZeroExtended(), and llvm::PPCTargetLowering::ReplaceNodeResults().
isTargetELF()
bool llvm::PPCSubtarget::isTargetELF () const inline
Definition at line 363 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
isTargetLinux()
bool llvm::PPCSubtarget::isTargetLinux () const inline
Definition at line 365 of file PPCSubtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCTargetLowering::insertSSPDeclarations(), and llvm::PPCTargetLowering::useLoadStackGuardNode().
isTargetMachO()
bool llvm::PPCSubtarget::isTargetMachO () const inline
Definition at line 364 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
isUsingPCRelativeCalls()
bool PPCSubtarget::isUsingPCRelativeCalls () const
Definition at line 257 of file PPCSubtarget.cpp.
References llvm::TargetMachine::getCodeModel(), getTargetMachine(), hasPCRelativeMemops(), isELFv2ABI(), isPPC64(), and llvm::CodeModel::Medium.
Referenced by buildCallOperands(), callsShareTOCBase(), combineADDToMAT_PCREL_ADDR(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), getCallOpcode(), GetSymbolRef(), isTOCSaveRestoreRequired(), and llvm::PPCTargetLowering::SelectOptimalAddrMode().
isXRaySupported()
bool llvm::PPCSubtarget::isXRaySupported () const inline override
Definition at line 434 of file PPCSubtarget.h.
References IsLittleEndian, and IsPPC64.
needsSwapsForVSXMemOps()
bool llvm::PPCSubtarget::needsSwapsForVSXMemOps () const inline
Definition at line 355 of file PPCSubtarget.h.
References hasP9Vector(), hasVSX(), and isLittleEndian().
Referenced by llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
needsTwoConstNR()
bool llvm::PPCSubtarget::needsTwoConstNR () const inline
Definition at line 281 of file PPCSubtarget.h.
References NeedsTwoConstNR.
overrideSchedPolicy()
void PPCSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, unsigned NumRegionInstrs) const override
Definition at line 224 of file PPCSubtarget.cpp.
References llvm::MachineSchedPolicy::OnlyBottomUp, and llvm::MachineSchedPolicy::ShouldTrackPressure.
pairedVectorMemops()
bool llvm::PPCSubtarget::pairedVectorMemops () const inline
Definition at line 293 of file PPCSubtarget.h.
References PairedVectorMemops.
Referenced by llvm::PPCInstrInfo::copyPhysReg(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::PPCTargetLowering::PPCTargetLowering().
ParseSubtargetFeatures()
void llvm::PPCSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
use64BitRegs()
bool llvm::PPCSubtarget::use64BitRegs () const inline
use64BitRegs - Return true if in 64-bit mode or if we should use 64-bit registers in 32-bit mode when possible.
This can only true if has64BitSupport() returns true.
Definition at line 255 of file PPCSubtarget.h.
References Use64BitRegs.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
useAA()
bool PPCSubtarget::useAA () const override
Definition at line 237 of file PPCSubtarget.cpp.
useCRBits()
bool llvm::PPCSubtarget::useCRBits () const inline
useCRBits - Return true if we should store and manipulate i1 values in the individual condition register bits.
Definition at line 259 of file PPCSubtarget.h.
References UseCRBits.
Referenced by llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getSetCCResultType(), and llvm::PPCTargetLowering::PPCTargetLowering().
useDFAforSMS()
bool PPCSubtarget::useDFAforSMS () const override
Machine Pipeliner customization.
Definition at line 209 of file PPCSubtarget.cpp.
useLongCalls()
bool llvm::PPCSubtarget::useLongCalls () const inline
Definition at line 341 of file PPCSubtarget.h.
References UseLongCalls.
usePPCPostRASchedStrategy()
bool llvm::PPCSubtarget::usePPCPostRASchedStrategy () const inline
Definition at line 315 of file PPCSubtarget.h.
References UsePPCPostRASchedStrategy.
usePPCPreRASchedStrategy()
bool llvm::PPCSubtarget::usePPCPreRASchedStrategy () const inline
Definition at line 314 of file PPCSubtarget.h.
References UsePPCPreRASchedStrategy.
usesFunctionDescriptors()
bool llvm::PPCSubtarget::usesFunctionDescriptors () const inline
True if the ABI is descriptor based.
Definition at line 400 of file PPCSubtarget.h.
References is64BitELFABI(), isAIXABI(), and isELFv2ABI().
Referenced by buildCallOperands(), descriptorEnvironmentPointerOffset(), descriptorTOCAnchorOffset(), getEnvironmentPointerRegister(), isIndirectCall(), and transformCallee().
useSoftFloat()
bool llvm::PPCSubtarget::useSoftFloat () const inline
Definition at line 246 of file PPCSubtarget.h.
References HasHardFloat, isAIXABI(), and llvm::report_fatal_error().
Referenced by llvm::PPCTargetLowering::useSoftFloat().
vectorsUseTwoUnits()
bool llvm::PPCSubtarget::vectorsUseTwoUnits () const inline
Definition at line 305 of file PPCSubtarget.h.
References VectorsUseTwoUnits.
Referenced by llvm::PPCTTIImpl::vectorCostAdjustmentFactor().
Member Data Documentation
AllowsUnalignedFPAccess
bool llvm::PPCSubtarget::AllowsUnalignedFPAccess protected
Definition at line 136 of file PPCSubtarget.h.
Referenced by allowsUnalignedFPAccess().
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::PPCSubtarget::CallLoweringInfo protected
GlobalISel related APIs.
Definition at line 183 of file PPCSubtarget.h.
Referenced by getCallLowering(), and PPCSubtarget().
CPUDirective
unsigned llvm::PPCSubtarget::CPUDirective protected
Which cpu directive was used.
Definition at line 91 of file PPCSubtarget.h.
Referenced by getCPUDirective().
DeprecatedDST
bool llvm::PPCSubtarget::DeprecatedDST protected
Definition at line 137 of file PPCSubtarget.h.
Referenced by isDeprecatedDST().
FeatureMFTB
bool llvm::PPCSubtarget::FeatureMFTB protected
Definition at line 135 of file PPCSubtarget.h.
Referenced by isFeatureMFTB().
FrameLowering
PPCFrameLowering llvm::PPCSubtarget::FrameLowering protected
Definition at line 177 of file PPCSubtarget.h.
Referenced by getFrameLowering().
Has64BitSupport
bool llvm::PPCSubtarget::Has64BitSupport protected
Definition at line 95 of file PPCSubtarget.h.
Referenced by has64BitSupport().
HasAddiLoadFusion
bool llvm::PPCSubtarget::HasAddiLoadFusion protected
Definition at line 148 of file PPCSubtarget.h.
Referenced by hasAddiLoadFusion().
HasAddisLoadFusion
bool llvm::PPCSubtarget::HasAddisLoadFusion protected
Definition at line 149 of file PPCSubtarget.h.
Referenced by hasAddisLoadFusion().
HasAddLogicalFusion
bool llvm::PPCSubtarget::HasAddLogicalFusion protected
Definition at line 151 of file PPCSubtarget.h.
Referenced by hasAddLogicalFusion().
HasAltivec
bool llvm::PPCSubtarget::HasAltivec protected
Definition at line 100 of file PPCSubtarget.h.
Referenced by hasAltivec().
HasArithAddFusion
bool llvm::PPCSubtarget::HasArithAddFusion protected
Definition at line 150 of file PPCSubtarget.h.
Referenced by hasArithAddFusion().
HasBack2BackFusion
bool llvm::PPCSubtarget::HasBack2BackFusion protected
Definition at line 158 of file PPCSubtarget.h.
Referenced by hasBack2BackFusion().
HasBPERMD
bool llvm::PPCSubtarget::HasBPERMD protected
Definition at line 126 of file PPCSubtarget.h.
Referenced by hasBPERMD().
HasCMPB
bool llvm::PPCSubtarget::HasCMPB protected
Definition at line 128 of file PPCSubtarget.h.
Referenced by hasCMPB().
HasCompareFusion
bool llvm::PPCSubtarget::HasCompareFusion protected
Definition at line 155 of file PPCSubtarget.h.
Referenced by hasCompareFusion().
HasDirectMove
bool llvm::PPCSubtarget::HasDirectMove protected
Definition at line 143 of file PPCSubtarget.h.
Referenced by hasDirectMove().
HasEFPU2
bool llvm::PPCSubtarget::HasEFPU2 protected
Definition at line 103 of file PPCSubtarget.h.
Referenced by hasEFPU2().
HasExtDiv
bool llvm::PPCSubtarget::HasExtDiv protected
Definition at line 127 of file PPCSubtarget.h.
Referenced by hasExtDiv().
HasFCPSGN
bool llvm::PPCSubtarget::HasFCPSGN protected
Definition at line 117 of file PPCSubtarget.h.
Referenced by hasFCPSGN().
HasFloat128
bool llvm::PPCSubtarget::HasFloat128 protected
Definition at line 145 of file PPCSubtarget.h.
Referenced by hasFloat128().
HasFPCVT
bool llvm::PPCSubtarget::HasFPCVT protected
Definition at line 124 of file PPCSubtarget.h.
Referenced by hasFPCVT().
HasFPRND
bool llvm::PPCSubtarget::HasFPRND protected
Definition at line 123 of file PPCSubtarget.h.
Referenced by hasFPRND().
HasFPU
bool llvm::PPCSubtarget::HasFPU protected
Definition at line 101 of file PPCSubtarget.h.
Referenced by hasFPU().
HasFRE
bool llvm::PPCSubtarget::HasFRE protected
Definition at line 119 of file PPCSubtarget.h.
Referenced by hasFRE().
HasFRES
bool llvm::PPCSubtarget::HasFRES protected
Definition at line 119 of file PPCSubtarget.h.
Referenced by hasFRES().
HasFRSQRTE
bool llvm::PPCSubtarget::HasFRSQRTE protected
Definition at line 119 of file PPCSubtarget.h.
Referenced by hasFRSQRTE().
HasFRSQRTES
bool llvm::PPCSubtarget::HasFRSQRTES protected
Definition at line 119 of file PPCSubtarget.h.
Referenced by hasFRSQRTES().
HasFSQRT
bool llvm::PPCSubtarget::HasFSQRT protected
Definition at line 118 of file PPCSubtarget.h.
Referenced by hasFSQRT().
HasFusion
bool llvm::PPCSubtarget::HasFusion protected
Definition at line 146 of file PPCSubtarget.h.
Referenced by hasFusion().
HasHardFloat
bool llvm::PPCSubtarget::HasHardFloat protected
Definition at line 98 of file PPCSubtarget.h.
Referenced by useSoftFloat().
HasHTM
bool llvm::PPCSubtarget::HasHTM protected
Definition at line 144 of file PPCSubtarget.h.
Referenced by hasHTM().
HasICBT
bool llvm::PPCSubtarget::HasICBT protected
Definition at line 139 of file PPCSubtarget.h.
Referenced by hasICBT().
HasInvariantFunctionDescriptors
bool llvm::PPCSubtarget::HasInvariantFunctionDescriptors protected
Definition at line 140 of file PPCSubtarget.h.
Referenced by hasInvariantFunctionDescriptors().
HasISEL
bool llvm::PPCSubtarget::HasISEL protected
Definition at line 125 of file PPCSubtarget.h.
Referenced by hasISEL().
HasLDBRX
bool llvm::PPCSubtarget::HasLDBRX protected
Definition at line 129 of file PPCSubtarget.h.
Referenced by hasLDBRX().
HasLFIWAX
bool llvm::PPCSubtarget::HasLFIWAX protected
Definition at line 122 of file PPCSubtarget.h.
Referenced by hasLFIWAX().
HasLogicalAddFusion
bool llvm::PPCSubtarget::HasLogicalAddFusion protected
Definition at line 152 of file PPCSubtarget.h.
Referenced by hasLogicalAddFusion().
HasLogicalFusion
bool llvm::PPCSubtarget::HasLogicalFusion protected
Definition at line 153 of file PPCSubtarget.h.
Referenced by hasLogicalFusion().
HasMFOCRF
bool llvm::PPCSubtarget::HasMFOCRF protected
Used by the ISel to turn in optimizations for POWER4-derived architectures.
Definition at line 94 of file PPCSubtarget.h.
Referenced by hasMFOCRF().
HasMMA
bool llvm::PPCSubtarget::HasMMA protected
Definition at line 114 of file PPCSubtarget.h.
Referenced by hasMMA().
HasModernAIXAs
bool llvm::PPCSubtarget::HasModernAIXAs protected
Definition at line 171 of file PPCSubtarget.h.
HasOnlyMSYNC
bool llvm::PPCSubtarget::HasOnlyMSYNC protected
Definition at line 131 of file PPCSubtarget.h.
Referenced by hasOnlyMSYNC().
HasP10Vector
bool llvm::PPCSubtarget::HasP10Vector protected
Definition at line 111 of file PPCSubtarget.h.
Referenced by hasP10Vector().
HasP8Altivec
bool llvm::PPCSubtarget::HasP8Altivec protected
Definition at line 107 of file PPCSubtarget.h.
Referenced by hasP8Altivec().
HasP8Crypto
bool llvm::PPCSubtarget::HasP8Crypto protected
Definition at line 108 of file PPCSubtarget.h.
Referenced by hasP8Crypto().
HasP8Vector
bool llvm::PPCSubtarget::HasP8Vector protected
Definition at line 106 of file PPCSubtarget.h.
Referenced by hasP8Vector().
HasP9Altivec
bool llvm::PPCSubtarget::HasP9Altivec protected
Definition at line 110 of file PPCSubtarget.h.
Referenced by hasP9Altivec().
HasP9Vector
bool llvm::PPCSubtarget::HasP9Vector protected
Definition at line 109 of file PPCSubtarget.h.
Referenced by hasP9Vector().
HasPartwordAtomics
bool llvm::PPCSubtarget::HasPartwordAtomics protected
Definition at line 141 of file PPCSubtarget.h.
Referenced by hasPartwordAtomics().
HasPCRelativeMemops
bool llvm::PPCSubtarget::HasPCRelativeMemops protected
Definition at line 113 of file PPCSubtarget.h.
Referenced by hasPCRelativeMemops().
HasPOPCNTD
POPCNTDKind llvm::PPCSubtarget::HasPOPCNTD protected
Definition at line 174 of file PPCSubtarget.h.
Referenced by hasPOPCNTD().
HasPrefixInstrs
bool llvm::PPCSubtarget::HasPrefixInstrs protected
Definition at line 112 of file PPCSubtarget.h.
Referenced by hasPrefixInstrs().
HasPrivileged
bool llvm::PPCSubtarget::HasPrivileged protected
Definition at line 116 of file PPCSubtarget.h.
Referenced by hasPrivileged().
HasQuadwordAtomics
bool llvm::PPCSubtarget::HasQuadwordAtomics protected
Definition at line 142 of file PPCSubtarget.h.
Referenced by hasQuadwordAtomics().
HasRecipPrec
bool llvm::PPCSubtarget::HasRecipPrec protected
Definition at line 120 of file PPCSubtarget.h.
Referenced by hasRecipPrec().
HasROPProtect
bool llvm::PPCSubtarget::HasROPProtect protected
Definition at line 115 of file PPCSubtarget.h.
Referenced by hasROPProtect().
HasSha3Fusion
bool llvm::PPCSubtarget::HasSha3Fusion protected
Definition at line 154 of file PPCSubtarget.h.
Referenced by hasSha3Fusion().
HasSPE
bool llvm::PPCSubtarget::HasSPE protected
Definition at line 102 of file PPCSubtarget.h.
Referenced by hasSPE().
HasSTFIWX
bool llvm::PPCSubtarget::HasSTFIWX protected
Definition at line 121 of file PPCSubtarget.h.
Referenced by hasSTFIWX().
HasStoreFusion
bool llvm::PPCSubtarget::HasStoreFusion protected
Definition at line 147 of file PPCSubtarget.h.
Referenced by hasStoreFusion().
HasVSX
bool llvm::PPCSubtarget::HasVSX protected
Definition at line 104 of file PPCSubtarget.h.
Referenced by hasVSX().
HasWideImmFusion
bool llvm::PPCSubtarget::HasWideImmFusion protected
Definition at line 156 of file PPCSubtarget.h.
Referenced by hasWideImmFusion().
HasZeroMoveFusion
bool llvm::PPCSubtarget::HasZeroMoveFusion protected
Definition at line 157 of file PPCSubtarget.h.
Referenced by hasZeroMoveFusion().
InstrInfo
PPCInstrInfo llvm::PPCSubtarget::InstrInfo protected
Definition at line 178 of file PPCSubtarget.h.
Referenced by getInstrInfo().
InstrItins
InstrItineraryData llvm::PPCSubtarget::InstrItins protected
Selected instruction itineraries (one entry per itinerary class.)
Definition at line 88 of file PPCSubtarget.h.
Referenced by getInstrItineraryData().
InstSelector
std::unique_ptr<InstructionSelector> llvm::PPCSubtarget::InstSelector protected
Definition at line 186 of file PPCSubtarget.h.
Referenced by getInstructionSelector(), and PPCSubtarget().
IsAIX
bool llvm::PPCSubtarget::IsAIX protected
Definition at line 172 of file PPCSubtarget.h.
IsBookE
bool llvm::PPCSubtarget::IsBookE protected
Definition at line 130 of file PPCSubtarget.h.
Referenced by isBookE().
IsE500
bool llvm::PPCSubtarget::IsE500 protected
Definition at line 132 of file PPCSubtarget.h.
Referenced by isE500().
IsISA2_06
bool llvm::PPCSubtarget::IsISA2_06 protected
Definition at line 159 of file PPCSubtarget.h.
Referenced by isISA2_06().
IsISA2_07
bool llvm::PPCSubtarget::IsISA2_07 protected
Definition at line 160 of file PPCSubtarget.h.
Referenced by isISA2_07().
IsISA3_0
bool llvm::PPCSubtarget::IsISA3_0 protected
Definition at line 161 of file PPCSubtarget.h.
Referenced by isISA3_0().
IsISA3_1
bool llvm::PPCSubtarget::IsISA3_1 protected
Definition at line 162 of file PPCSubtarget.h.
Referenced by isISA3_1().
IsISAFuture
bool llvm::PPCSubtarget::IsISAFuture protected
Definition at line 163 of file PPCSubtarget.h.
Referenced by isISAFuture().
IsLittleEndian
bool llvm::PPCSubtarget::IsLittleEndian protected
Definition at line 138 of file PPCSubtarget.h.
Referenced by isLittleEndian(), and isXRaySupported().
IsPPC4xx
bool llvm::PPCSubtarget::IsPPC4xx protected
Definition at line 133 of file PPCSubtarget.h.
Referenced by isPPC4xx().
IsPPC64
bool llvm::PPCSubtarget::IsPPC64 protected
Definition at line 99 of file PPCSubtarget.h.
Referenced by descriptorEnvironmentPointerOffset(), descriptorTOCAnchorOffset(), getEnvironmentPointerRegister(), getStackPointerRegister(), getTOCPointerRegister(), and isXRaySupported().
IsPPC6xx
bool llvm::PPCSubtarget::IsPPC6xx protected
Definition at line 134 of file PPCSubtarget.h.
Referenced by isPPC6xx().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::PPCSubtarget::Legalizer protected
Definition at line 184 of file PPCSubtarget.h.
NeedsTwoConstNR
bool llvm::PPCSubtarget::NeedsTwoConstNR protected
Definition at line 105 of file PPCSubtarget.h.
Referenced by needsTwoConstNR().
PairedVectorMemops
bool llvm::PPCSubtarget::PairedVectorMemops protected
Definition at line 169 of file PPCSubtarget.h.
Referenced by pairedVectorMemops().
PredictableSelectIsExpensive
bool llvm::PPCSubtarget::PredictableSelectIsExpensive protected
Definition at line 170 of file PPCSubtarget.h.
Referenced by isPredictableSelectIsExpensive().
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::PPCSubtarget::RegBankInfo protected
Definition at line 185 of file PPCSubtarget.h.
Referenced by getRegBankInfo(), and PPCSubtarget().
SecurePlt
bool llvm::PPCSubtarget::SecurePlt protected
Definition at line 165 of file PPCSubtarget.h.
Referenced by isSecurePlt().
StackAlignment
Align llvm::PPCSubtarget::StackAlignment protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 85 of file PPCSubtarget.h.
Referenced by getStackAlignment().
TargetTriple
Triple llvm::PPCSubtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 81 of file PPCSubtarget.h.
Referenced by getTargetTriple(), isAIXABI(), isTargetELF(), isTargetLinux(), and isTargetMachO().
TLInfo
PPCTargetLowering llvm::PPCSubtarget::TLInfo protected
Definition at line 179 of file PPCSubtarget.h.
Referenced by getTargetLowering().
TM
const PPCTargetMachine& llvm::PPCSubtarget::TM protected
Definition at line 176 of file PPCSubtarget.h.
Referenced by getTargetMachine(), isELFv2ABI(), isGVIndirectSymbol(), isPPC64(), and PPCSubtarget().
TSInfo
SelectionDAGTargetInfo llvm::PPCSubtarget::TSInfo protected
Definition at line 180 of file PPCSubtarget.h.
Referenced by getSelectionDAGInfo().
Use64BitRegs
bool llvm::PPCSubtarget::Use64BitRegs protected
Definition at line 96 of file PPCSubtarget.h.
Referenced by use64BitRegs().
UseCRBits
bool llvm::PPCSubtarget::UseCRBits protected
Definition at line 97 of file PPCSubtarget.h.
Referenced by useCRBits().
UseLongCalls
bool llvm::PPCSubtarget::UseLongCalls protected
Definition at line 164 of file PPCSubtarget.h.
Referenced by useLongCalls().
UsePPCPostRASchedStrategy
bool llvm::PPCSubtarget::UsePPCPostRASchedStrategy protected
Definition at line 168 of file PPCSubtarget.h.
Referenced by usePPCPostRASchedStrategy().
UsePPCPreRASchedStrategy
bool llvm::PPCSubtarget::UsePPCPreRASchedStrategy protected
Definition at line 167 of file PPCSubtarget.h.
Referenced by usePPCPreRASchedStrategy().
VectorsUseTwoUnits
bool llvm::PPCSubtarget::VectorsUseTwoUnits protected
Definition at line 166 of file PPCSubtarget.h.
Referenced by vectorsUseTwoUnits().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCSubtarget.h
lib/Target/PowerPC/PPCSubtarget.cpp