LLVM: llvm::InitialScheduleStage Class Reference
llvm::InitialScheduleStage Class Reference
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
void finalizeGCNRegion () override
bool shouldRevertScheduling (unsigned WavesAfter) override
InitialScheduleStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Public Member Functions inherited from llvm::GCNSchedStage
virtual bool initGCNSchedStage ()
virtual void finalizeGCNSchedStage ()
virtual bool initGCNRegion ()
void setupNewBlock ()
void checkScheduling ()
bool mayCauseSpilling (unsigned WavesAfter)
void revertScheduling ()
void advanceRegion ()
virtual ~GCNSchedStage ()=default
Additional Inherited Members
Protected Member Functions inherited from llvm::GCNSchedStage
GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Protected Attributes inherited from llvm::GCNSchedStage
GCNScheduleDAGMILive & DAG
GCNMaxOccupancySchedStrategy & S
MachineFunction & MF
SIMachineFunctionInfo & MFI
const GCNSubtarget & ST
const GCNSchedStageID StageID
MachineBasicBlock * CurrentMBB = nullptr
unsigned RegionIdx = 0
std::vector< MachineInstr * > Unsched
GCNRegPressure PressureBefore
GCNRegPressure PressureAfter
Detailed Description
Definition at line 242 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
InitialScheduleStage()
llvm::InitialScheduleStage::InitialScheduleStage (GCNSchedStageID StageID, GCNScheduleDAGMILive & DAG) inline
Definition at line 248 of file GCNSchedStrategy.h.
Member Function Documentation
finalizeGCNRegion()
void InitialScheduleStage::finalizeGCNRegion () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 670 of file GCNSchedStrategy.cpp.
References assert(), llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::finalizeGCNRegion(), llvm::GCNMaxOccupancySchedStrategy::HasClusteredNodes, llvm::nextStage(), llvm::GCNSchedStage::RegionIdx, llvm::GCNSchedStage::S, llvm::GCNSchedStage::StageID, and llvm::UnclusteredReschedule.
shouldRevertScheduling()
bool InitialScheduleStage::shouldRevertScheduling (unsigned WavesAfter) override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 754 of file GCNSchedStrategy.cpp.
References assert(), llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::mayCauseSpilling(), llvm::nextStage(), llvm::GCNSchedStage::RegionIdx, llvm::GCNSchedStage::shouldRevertScheduling(), llvm::GCNSchedStage::StageID, and llvm::UnclusteredReschedule.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp