LLVM: llvm::MCDecodedPseudoProbeInlineTree Class Reference
llvm::MCDecodedPseudoProbeInlineTree Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCDecodedPseudoProbeInlineTree ()=default
MCDecodedPseudoProbeInlineTree (const InlineSite &Site)
bool hasInlineSite () const
Public Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >
bool isRoot () const
InlinedProbeTreeMap & getChildren ()
const InlinedProbeTreeMap & getChildren () const
std::vector< MCDecodedPseudoProbe * > & getProbes ()
void addProbes (MCDecodedPseudoProbe *Probe)
MCDecodedPseudoProbeInlineTree * getOrAddNode (const InlineSite &Site)
Public Attributes
InlineSite ISite
uint32_t ChildrenToProcess = 0
Public Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >
uint64_t Guid
MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree > * Parent
Additional Inherited Members
Protected Types inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >
using InlinedProbeTreeMap
Protected Member Functions inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >
MCPseudoProbeInlineTreeBase ()
Protected Attributes inherited from llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >
InlinedProbeTreeMap Children
std::vector< MCDecodedPseudoProbe * > Probes
Detailed Description
Definition at line 262 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCDecodedPseudoProbeInlineTree() [1/2]
llvm::MCDecodedPseudoProbeInlineTree::MCDecodedPseudoProbeInlineTree () default
MCDecodedPseudoProbeInlineTree() [2/2]
llvm::MCDecodedPseudoProbeInlineTree::MCDecodedPseudoProbeInlineTree (const InlineSite & Site) inline
Definition at line 271 of file MCPseudoProbe.h.
Member Function Documentation
hasInlineSite()
bool llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite () const inline
Definition at line 274 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::isRoot(), llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >::isRoot(), and llvm::MCPseudoProbeInlineTreeBase< MCDecodedPseudoProbe *, MCDecodedPseudoProbeInlineTree >::Parent.
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext(), and llvm::MCPseudoProbeDecoder::getInlinerDescForProbe().
Member Data Documentation
ChildrenToProcess
uint32_t llvm::MCDecodedPseudoProbeInlineTree::ChildrenToProcess = 0
Definition at line 268 of file MCPseudoProbe.h.
ISite
InlineSite llvm::MCDecodedPseudoProbeInlineTree::ISite
Definition at line 266 of file MCPseudoProbe.h.
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext().
The documentation for this class was generated from the following file:
include/llvm/MC/MCPseudoProbe.h