LLVM: llvm::MipsAsmPrinter Class Reference
llvm::MipsAsmPrinter Class Reference
#include "Target/Mips/MipsAsmPrinter.h"
Public Member Functions
void LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr &MI)
void LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr &MI)
void LowerPATCHABLE_TAIL_CALL (const MachineInstr &MI)
MipsAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void emitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void emitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void printSavedRegsBitmask ()
void emitFrameDirective ()
Frame Directive.
const char * getCurrentABIString () const
Emit Set directives.
void emitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void emitFunctionBodyStart () override
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
void emitFunctionBodyEnd () override
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
void emitBasicBlockEnd (const MachineBasicBlock &MBB) override
Targets can override this to emit stuff at the end of a basic block.
bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const override
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
void printOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperandEA (const MachineInstr *MI, int opNum, raw_ostream &O)
void printFCCOperand (const MachineInstr *MI, int opNum, raw_ostream &O, const char *Modifier=nullptr)
void printRegisterList (const MachineInstr *MI, int opNum, raw_ostream &O)
void emitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void emitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void PrintDebugValueComment (const MachineInstr *MI, raw_ostream &OS)
void emitDebugValue (const MCExpr *Value, unsigned Size) const override
Emit the directive and value for debug thread local expression.
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isDwarf64 () const
unsigned int getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
unsigned int getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
dwarf::FormParams getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getMBBExceptionSym (const MachineBasicBlock &MBB)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitStackUsage (const MachineFunction &MF)
void emitBBAddrMapSection (const MachineFunction &MF)
void emitPseudoProbe (const MachineInstr &MI)
void emitRemarksSection (remarks::RemarkStreamer &RS)
CFISection getFunctionCFISectionType (const Function &F) const
Get the CFISection type for a function.
CFISection getFunctionCFISectionType (const MachineFunction &MF) const
Get the CFISection type for a function.
CFISection getModuleCFISectionType () const
Get the CFISection type for the module.
bool needsSEHMoves ()
bool needsCFIForDebug () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for debugging purpose when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
virtual void emitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
virtual void emitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void preprocessXXStructorList (const DataLayout &DL, const Constant *List, SmallVector< Structor, 8 > &Structors)
This method gathers an array of Structors and then sorts them out by Priority.
virtual void emitXXStructorList (const DataLayout &DL, const Constant *List, bool IsCtor)
This method emits llvm.global_ctors or llvm.global_dtors list.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr, unsigned MaxBytesToEmit=0) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV, AliasMapTy *AliasList=nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps (StackMaps &SM)
Emit the stack maps.
void addAsmPrinterHandler (HandlerInfo Handler)
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void emitFunctionDescriptor ()
virtual void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void emitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
virtual void emitTTypeReference (const GlobalValue *GV, unsigned Encoding)
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-or 8-byte offset of a string from the start of its section.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
void emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
void emitDwarfUnitLength (uint64_t Length, const Twine &Comment) const
Emit a unit length field.
MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment) const
Emit a unit length field.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, StringRef Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &OS)
Print the MachineOperand as a symbol.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Public Attributes
const MipsSubtarget * Subtarget
const MipsFunctionInfo * MipsFI
MipsMCInstLower MCInstLowering
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< unsigned, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum class CFISection : unsigned { None = 0 , EH = 1 , Debug = 2 }
enum class SledKind : uint8_t {
FUNCTION_ENTER = 0 , FUNCTION_EXIT = 1 , TAIL_CALL = 2 , LOG_ARGS_ENTER = 3 ,
CUSTOM_EVENT = 4 , TYPED_EVENT = 5
}
using GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
using AliasMapTy = DenseMap<uint64_t, SmallVector<const GlobalAlias *, 1>>
Print a general LLVM constant to the .s file.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
virtual bool shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
std::vector< HandlerInfo > Handlers
A vector of all debug/EH info emitters we should use.
size_t NumUserHandlers = 0
Detailed Description
Definition at line 42 of file MipsAsmPrinter.h.
Constructor & Destructor Documentation
MipsAsmPrinter()
llvm::MipsAsmPrinter::MipsAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) inline explicit
Definition at line 121 of file MipsAsmPrinter.h.
Member Function Documentation
emitBasicBlockEnd()
void MipsAsmPrinter::emitBasicBlockEnd (const MachineBasicBlock & MBB) override virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented from llvm::AsmPrinter.
Definition at line 467 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::emitBasicBlockEnd(), llvm::MipsTargetStreamer::emitDirectiveInsn(), llvm::MachineBasicBlock::empty(), and MBB.
emitConstantPool()
void llvm::MipsAsmPrinter::emitConstantPool () inline override virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 129 of file MipsAsmPrinter.h.
References llvm::AsmPrinter::emitConstantPool(), llvm::MipsSubtarget::inMips16Mode(), and llvm::MipsSubtarget::useConstantIslands().
emitDebugValue()
void MipsAsmPrinter::emitDebugValue (const MCExpr * Value, unsigned Size) const override virtual
Emit the directive and value for debug thread local expression.
Value - The value to emit. Size - The size of the integer (in bytes) to emit.
Reimplemented from llvm::AsmPrinter.
Definition at line 1257 of file MipsAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::AsmPrinter::emitDebugValue(), llvm_unreachable, llvm::MipsMCExpr::MEK_DTPREL, llvm::AsmPrinter::OutStreamer, and Size.
emitEndOfAsmFile()
void MipsAsmPrinter::emitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 1124 of file MipsAsmPrinter.cpp.
References llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
emitFrameDirective()
void MipsAsmPrinter::emitFrameDirective ()
Frame Directive.
Definition at line 380 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitFrame(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MCRegisterInfo::getRARegister(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), and llvm::AsmPrinter::MF.
Referenced by emitFunctionBodyStart().
emitFunctionBodyEnd()
void MipsAsmPrinter::emitFunctionBodyEnd () override virtual
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 447 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::MipsTargetStreamer::emitDirectiveEnd(), llvm::MipsTargetStreamer::emitDirectiveSetAt(), llvm::MipsTargetStreamer::emitDirectiveSetMacro(), llvm::MipsTargetStreamer::emitDirectiveSetReorder(), llvm::MCSymbol::getName(), llvm::MipsSubtarget::inMips16Mode(), llvm::MCDR_DataRegionEnd, llvm::AsmPrinter::OutStreamer, and Subtarget.
emitFunctionBodyStart()
void MipsAsmPrinter::emitFunctionBodyStart () override virtual
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 426 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoAt(), llvm::MipsTargetStreamer::emitDirectiveSetNoMacro(), llvm::MipsTargetStreamer::emitDirectiveSetNoReorder(), emitFrameDirective(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFunction(), llvm::Function::hasFnAttribute(), llvm::MipsMCInstLower::Initialize(), llvm::MipsSubtarget::inMips16Mode(), MCInstLowering, llvm::AsmPrinter::MF, printSavedRegsBitmask(), and Subtarget.
emitFunctionEntryLabel()
void MipsAsmPrinter::emitFunctionEntryLabel () override virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 400 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::emitAlignment(), llvm::MipsTargetStreamer::emitDirectiveEnt(), llvm::MipsTargetStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetMips16(), llvm::MipsTargetStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetNoMips16(), llvm::MachineFunction::getAlignment(), llvm::MipsSubtarget::inMicroMipsMode(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), llvm::AsmPrinter::MF, llvm::MIPS_NACL_BUNDLE_ALIGN, llvm::AsmPrinter::OutStreamer, llvm::MipsTargetStreamer::setUsesMicroMips(), Subtarget, and llvm::MipsTargetStreamer::updateABIInfo().
emitInstruction()
void MipsAsmPrinter::emitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 183 of file MipsAsmPrinter.cpp.
References llvm::MachineConstantPoolEntry::ConstVal, E, emitDirectiveRelocJalr(), llvm::AsmPrinter::emitGlobalConstant(), EmitJalrReloc, llvm::AsmPrinter::emitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineFunction::getDataLayout(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm_unreachable, llvm::MipsMCInstLower::Lower(), LowerPATCHABLE_FUNCTION_ENTER(), LowerPATCHABLE_FUNCTION_EXIT(), LowerPATCHABLE_TAIL_CALL(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, MCInstLowering, llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, PrintDebugValueComment(), Subtarget, llvm::AsmPrinter::TM, and llvm::MachineConstantPoolEntry::Val.
emitStartOfAsmFile()
void MipsAsmPrinter::emitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 772 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetStreamer::emitDirectiveModuleFP(), llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetStreamer::emitDirectiveNaN2008(), llvm::MipsTargetStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetMachine::getABI(), getCurrentABIString(), llvm::MCContext::getELFSection(), llvm::MCContext::getObjectFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getTargetCPU(), llvm::TargetMachine::getTargetFeatureString(), llvm::TargetMachine::getTargetTriple(), llvm::MipsSubtarget::hasSym32(), llvm::MipsSubtarget::isABI_FPXX(), llvm::MipsSubtarget::isABICalls(), llvm::MipsSubtarget::isFP64bit(), llvm::MipsTargetMachine::isLittleEndian(), llvm::MipsSubtarget::isNaN2008(), llvm::AsmPrinter::isPositionIndependent(), llvm::MCObjectFileInfo::isPositionIndependent(), llvm::AsmPrinter::None, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MIPS_MC::selectMipsCPU(), llvm::MipsTargetStreamer::setPic(), llvm::ELF::SHT_PROGBITS, llvm::AsmPrinter::TM, llvm::MipsTargetStreamer::updateABIInfo(), llvm::MipsSubtarget::useOddSPReg(), and llvm::MipsSubtarget::useSoftFloat().
getCurrentABIString()
const char * MipsAsmPrinter::getCurrentABIString () const
Emit Set directives.
Definition at line 391 of file MipsAsmPrinter.cpp.
References llvm_unreachable, llvm::MipsABIInfo::N32, llvm::MipsABIInfo::N64, llvm::MipsABIInfo::O32, and llvm::AsmPrinter::TM.
Referenced by emitStartOfAsmFile().
getPassName()
StringRef llvm::MipsAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 125 of file MipsAsmPrinter.h.
isBlockOnlyReachableByFallthrough()
bool MipsAsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const override virtual
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented from llvm::AsmPrinter.
Definition at line 477 of file MipsAsmPrinter.cpp.
References I, llvm::isa(), llvm::MachineBasicBlock::isEHPad(), MBB, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), and llvm::MachineBasicBlock::pred_end().
LowerPATCHABLE_FUNCTION_ENTER()
void MipsAsmPrinter::LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr & MI)
Definition at line 1238 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::FUNCTION_ENTER, and MI.
Referenced by emitInstruction().
LowerPATCHABLE_FUNCTION_EXIT()
void MipsAsmPrinter::LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr & MI)
Definition at line 1242 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::FUNCTION_EXIT, and MI.
Referenced by emitInstruction().
LowerPATCHABLE_TAIL_CALL()
void MipsAsmPrinter::LowerPATCHABLE_TAIL_CALL (const MachineInstr & MI)
Definition at line 1246 of file MipsAsmPrinter.cpp.
References MI, and llvm::AsmPrinter::TAIL_CALL.
Referenced by emitInstruction().
PrintAsmMemoryOperand()
bool MipsAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 622 of file MipsAsmPrinter.cpp.
References assert(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::MachineOperand::isImm(), llvm::MipsSubtarget::isLittle(), llvm::MachineOperand::isReg(), MI, Offset, and Subtarget.
PrintAsmOperand()
bool MipsAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented from llvm::AsmPrinter.
Definition at line 517 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::MipsSubtarget::isGP64bit(), llvm::MachineOperand::isImm(), llvm::MipsSubtarget::isLittle(), llvm::isPowerOf2_64(), llvm::MachineOperand::isReg(), llvm::Log2_64(), MI, llvm::AsmPrinter::PrintAsmOperand(), printOperand(), Subtarget, and llvm::Twine::utohexstr().
PrintDebugValueComment()
void MipsAsmPrinter::PrintDebugValueComment (const MachineInstr * MI, raw_ostream & OS)
Definition at line 1250 of file MipsAsmPrinter.cpp.
Referenced by emitInstruction().
printFCCOperand()
void MipsAsmPrinter::printFCCOperand (const MachineInstr * MI, int opNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 757 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), MI, and llvm::Mips::MipsFCCToString().
printMemOperand()
void MipsAsmPrinter::printMemOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 725 of file MipsAsmPrinter.cpp.
References MI, and printOperand().
printMemOperandEA()
void MipsAsmPrinter::printMemOperandEA (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 748 of file MipsAsmPrinter.cpp.
References MI, and printOperand().
printOperand()
void MipsAsmPrinter::printOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 660 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MCSymbol::getName(), llvm::MachineOperand::getOffset(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::StringRef::lower(), llvm::AsmPrinter::MAI, MI, llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MipsII::MO_GOT, llvm::MipsII::MO_GOT_CALL, llvm::MipsII::MO_GOT_DISP, llvm::MipsII::MO_GOT_OFST, llvm::MipsII::MO_GOT_PAGE, llvm::MipsII::MO_GOTTPREL, llvm::MipsII::MO_GPOFF_HI, llvm::MipsII::MO_GPOFF_LO, llvm::MipsII::MO_GPREL, llvm::MipsII::MO_HIGHER, llvm::MipsII::MO_HIGHEST, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MipsII::MO_TLSGD, llvm::MipsII::MO_TPREL_HI, llvm::MipsII::MO_TPREL_LO, llvm::MCSymbol::print(), and llvm::AsmPrinter::PrintSymbolOperand().
Referenced by PrintAsmOperand(), printMemOperand(), printMemOperandEA(), and printRegisterList().
printRegisterList()
void MipsAsmPrinter::printRegisterList (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 764 of file MipsAsmPrinter.cpp.
References MI, and printOperand().
printSavedRegsBitmask()
void MipsAsmPrinter::printSavedRegsBitmask ()
Definition at line 327 of file MipsAsmPrinter.cpp.
References contains(), llvm::MipsTargetStreamer::emitFMask(), llvm::MipsTargetStreamer::emitMask(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::AsmPrinter::MF, and TRI.
Referenced by emitFunctionBodyStart().
runOnMachineFunction()
bool MipsAsmPrinter::runOnMachineFunction (MachineFunction & MF) override virtual
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 78 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::emitXRayTable(), llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), llvm::AsmPrinter::MF, MipsFI, llvm::AsmPrinter::runOnMachineFunction(), llvm::MipsFunctionInfo::StubsNeeded, and Subtarget.
Member Data Documentation
MCInstLowering
MipsMCInstLower llvm::MipsAsmPrinter::MCInstLowering
Definition at line 119 of file MipsAsmPrinter.h.
Referenced by emitFunctionBodyStart(), and emitInstruction().
MipsFI
const MipsFunctionInfo* llvm::MipsAsmPrinter::MipsFI
Definition at line 118 of file MipsAsmPrinter.h.
Referenced by runOnMachineFunction().
Subtarget
const MipsSubtarget* llvm::MipsAsmPrinter::Subtarget
Definition at line 117 of file MipsAsmPrinter.h.
Referenced by emitFunctionBodyEnd(), emitFunctionBodyStart(), emitFunctionEntryLabel(), emitInstruction(), PrintAsmMemoryOperand(), PrintAsmOperand(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsAsmPrinter.h
lib/Target/Mips/MipsAsmPrinter.cpp