LLVM: llvm::MachineFunctionPassManager Class Reference
llvm::MachineFunctionPassManager Class Reference
MachineFunctionPassManager adds/removes below features to/from the base PassManager template instantiation.
#include "llvm/CodeGen/MachinePassManager.h"
Public Member Functions
MachineFunctionPassManager (bool DebugLogging=false, bool RequireCodeGenSCCOrder=false, bool VerifyMachineFunction=false)
MachineFunctionPassManager (MachineFunctionPassManager &&)=default
MachineFunctionPassManager & operator= (MachineFunctionPassManager &&)=default
Error run (Module &M, MachineFunctionAnalysisManager &MFAM)
Run machine passes for a Module.
template<typename PassT >
void addPass (PassT &&Pass)
Public Member Functions inherited from llvm::PassManager< MachineFunction, MachineFunctionAnalysisManager >
PassManager ()=default
Construct a pass manager.
PassManager (PassManager &&Arg)
PassManager & operator= (PassManager &&RHS)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
PreservedAnalyses run (MachineFunction &IR, MachineFunctionAnalysisManager &AM, ExtraArgTs... ExtraArgs)
Run all of the passes in this manager over the given unit of IR.
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &G, CGSCCUpdateResult &UR)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &G, CGSCCUpdateResult &UR)
Explicitly specialize the pass manager run method to handle call graph updates.
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!std::is_same< PassT, PassManager >::value > addPass (PassT &&Pass)
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t< std::is_same< PassT, PassManager >::value > addPass (PassT &&Pass)
When adding a pass manager pass that has the same type as this pass manager, simply move the passes over.
bool isEmpty () const
Returns if the pass manager contains any passes.
Public Member Functions inherited from llvm::PassInfoMixin< PassManager< MachineFunction, MachineFunctionAnalysisManager, ExtraArgTs... > >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassManager< MachineFunction, MachineFunctionAnalysisManager >
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PassManager< MachineFunction, MachineFunctionAnalysisManager, ExtraArgTs... > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Protected Types inherited from llvm::PassManager< MachineFunction, MachineFunctionAnalysisManager >
using PassConceptT
Protected Attributes inherited from llvm::PassManager< MachineFunction, MachineFunctionAnalysisManager >
std::vector< std::unique_ptr< PassConceptT > > Passes
Detailed Description
MachineFunctionPassManager adds/removes below features to/from the base PassManager template instantiation.
Support passes that implement doInitialization/doFinalization. This is for machine function passes to work on module level constructs. One such pass is AsmPrinter.
Support machine module pass which runs over the module (for example, MachineOutliner). A machine module pass needs to define the method:
Error run(Module &, MachineFunctionAnalysisManager &)
FIXME: machine module passes still need to define the usual machine function pass interface, namely, PreservedAnalyses run(MachineFunction &, / MachineFunctionAnalysisManager &) But this interface wouldn't be executed. It is just a placeholder to satisfy the pass manager type-erased inteface. This special-casing of machine module pass is due to its limited use cases and the unnecessary complexity it may bring to the machine pass manager.
The base class run method is replaced by an alternative run method. See details below.
Support codegening in the SCC order. Users include interprocedural register allocation (IPRA).
Definition at line 132 of file MachinePassManager.h.
Constructor & Destructor Documentation
MachineFunctionPassManager() [1/2]
llvm::MachineFunctionPassManager::MachineFunctionPassManager (bool DebugLogging = false, bool RequireCodeGenSCCOrder = false, bool VerifyMachineFunction = false) inline
Definition at line 137 of file MachinePassManager.h.
MachineFunctionPassManager() [2/2]
llvm::MachineFunctionPassManager::MachineFunctionPassManager (MachineFunctionPassManager &&) default
Member Function Documentation
addPass()
template<typename PassT > void llvm::MachineFunctionPassManager::addPass (PassT && Pass) inline
Definition at line 155 of file MachinePassManager.h.
References P, and Passes.
operator=()
MachineFunctionPassManager & llvm::MachineFunctionPassManager::operator= (MachineFunctionPassManager &&) default
run()
Error llvm::MachineFunctionPassManager::run (Module & M, MachineFunctionAnalysisManager & MFAM)
Run machine passes for a Module.
The intended use is to start the codegen pipeline for a Module. The base class's run method is deliberately hidden by this due to the observation that we don't yet have the use cases of compositing two instances of machine pass managers, or compositing machine pass managers with other types of pass managers.
Definition at line 25 of file MachinePassManager.cpp.
References llvm::any_cast(), llvm::any_isa(), assert(), E, F, llvm::MachineFunctionAnalysisManager::getResult(), I, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), IR, P, llvm::PassManager< MachineFunction, MachineFunctionAnalysisManager >::Passes, llvm::PassInstrumentation::pushBeforeNonSkippedPassCallback(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runBeforePass(), Size, llvm::Error::success(), and llvm::verifyMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePassManager.h
lib/CodeGen/MachinePassManager.cpp