LLVM: llvm::CSKYTargetELFStreamer Class Reference
llvm::CSKYTargetELFStreamer Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYELFStreamer.h"
Public Member Functions
MCELFStreamer & getStreamer ()
CSKYTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
Public Member Functions inherited from llvm::CSKYTargetStreamer
CSKYTargetStreamer (MCStreamer &S)
const MCExpr * addConstantPoolEntry (const MCExpr *, SMLoc Loc, const MCExpr *AdjustExpr=nullptr)
Add a new entry to the constant pool for the current section and return an MCExpr that can be used to refer to the constant pool location.
void emitCurrentConstantPool ()
void finish () override
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Protected Attributes inherited from llvm::CSKYTargetStreamer
std::unique_ptr< CSKYConstantPool > ConstantPool
DenseMap< SymbolIndex, const MCExpr * > ConstantMap
unsigned ConstantCounter = 0
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 19 of file CSKYELFStreamer.h.
Constructor & Destructor Documentation
CSKYTargetELFStreamer()
CSKYTargetELFStreamer::CSKYTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 31 of file CSKYELFStreamer.cpp.
References llvm::ELF::EF_CSKY_801, llvm::ELF::EF_CSKY_802, llvm::ELF::EF_CSKY_803, llvm::ELF::EF_CSKY_805, llvm::ELF::EF_CSKY_807, llvm::ELF::EF_CSKY_810, llvm::ELF::EF_CSKY_860, llvm::ELF::EF_CSKY_ABIV2, llvm::ELF::EF_CSKY_EFV1, llvm::ELF::EF_CSKY_FLOAT, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
Member Function Documentation
getStreamer()
MCELFStreamer & CSKYTargetELFStreamer::getStreamer ()
Definition at line 68 of file CSKYELFStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by CSKYTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYELFStreamer.h
lib/Target/CSKY/MCTargetDesc/CSKYELFStreamer.cpp