LLVM: llvm::AddressRangesMap< T > Class Template Reference
llvm::AddressRangesMap< T > Class Template Reference
AddressRangesMap class maps values to the address ranges.
#include "llvm/ADT/AddressRanges.h"
Public Member Functions
void clear ()
bool empty () const
bool contains (uint64_t Addr) const
bool contains (AddressRange Range) const
void insert (AddressRange Range, T Value)
size_t size () const
Optional< std::pair< AddressRange, T > > getRangeValueThatContains (uint64_t Addr) const
std::pair< AddressRange, T > operator[] (size_t Idx) const
Protected Types
using ValuesCollection = SmallVector<T>
Protected Types inherited from llvm::AddressRanges
using Collection = SmallVector<AddressRange>
Protected Attributes
ValuesCollection Values
Protected Attributes inherited from llvm::AddressRanges
Collection Ranges
Additional Inherited Members
Protected Member Functions inherited from llvm::AddressRanges
Collection::const_iterator find (uint64_t Addr) const
Collection::const_iterator find (AddressRange Range) const
void clear ()
bool empty () const
bool contains (uint64_t Addr) const
bool contains (AddressRange Range) const
Optional< AddressRange > getRangeThatContains (uint64_t Addr) const
Collection::const_iterator insert (AddressRange Range)
void reserve (size_t Capacity)
size_t size () const
bool operator== (const AddressRanges &RHS) const
const AddressRange & operator[] (size_t i) const
Collection::const_iterator begin () const
Collection::const_iterator end () const
Detailed Description
template<typename T>
class llvm::AddressRangesMap< T >
AddressRangesMap class maps values to the address ranges.
It keeps address ranges and corresponding values. If ranges are combined during insertion, then combined range keeps newly inserted value.
Definition at line 95 of file AddressRanges.h.
Member Typedef Documentation
ValuesCollection
template<typename T > using llvm::AddressRangesMap< T >::ValuesCollection = SmallVector<T> protected
Definition at line 141 of file AddressRanges.h.
Member Function Documentation
clear()
template<typename T > void llvm::AddressRangesMap< T >::clear () inline
Definition at line 97 of file AddressRanges.h.
References llvm::SmallVectorImpl< T >::clear(), llvm::AddressRanges::Ranges, and llvm::AddressRangesMap< T >::Values.
contains() [1/2]
template<typename T > bool llvm::AddressRangesMap< T >::contains (AddressRange Range) const inline
Definition at line 103 of file AddressRanges.h.
References llvm::AddressRanges::contains().
contains() [2/2]
template<typename T > bool llvm::AddressRangesMap< T >::contains (uint64_t Addr) const inline
Definition at line 102 of file AddressRanges.h.
References Addr, and llvm::AddressRanges::contains().
empty()
template<typename T > bool llvm::AddressRangesMap< T >::empty () const inline
Definition at line 101 of file AddressRanges.h.
References llvm::AddressRanges::empty().
getRangeValueThatContains()
template<typename T > Optional< std::pair< AddressRange, T > > llvm::AddressRangesMap< T >::getRangeValueThatContains (uint64_t Addr) const inline
Definition at line 129 of file AddressRanges.h.
References Addr, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::AddressRanges::find(), llvm::None, llvm::AddressRanges::Ranges, and llvm::AddressRangesMap< T >::Values.
insert()
template<typename T > void llvm::AddressRangesMap< T >::insert (AddressRange Range, T Value) inline
Definition at line 106 of file AddressRanges.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::AddressRanges::insert(), llvm::AddressRanges::Ranges, llvm::SmallVectorBase< Size_T >::size(), T, llvm::Value, and llvm::AddressRangesMap< T >::Values.
Referenced by llvm::CompileUnit::addFunctionRange().
operator[]()
template<typename T > std::pair< AddressRange, T > llvm::AddressRangesMap< T >::operator[] (size_t Idx) const inline
Definition at line 136 of file AddressRanges.h.
References llvm::AddressRanges::Ranges, and llvm::AddressRangesMap< T >::Values.
size()
template<typename T > size_t llvm::AddressRangesMap< T >::size () const inline
Definition at line 124 of file AddressRanges.h.
References assert(), llvm::AddressRanges::Ranges, llvm::AddressRanges::size(), llvm::SmallVectorBase< Size_T >::size(), and llvm::AddressRangesMap< T >::Values.
Referenced by llvm::DwarfStreamer::emitUnitRangesEntries().
Member Data Documentation
Values
template<typename T > ValuesCollection llvm::AddressRangesMap< T >::Values protected
Definition at line 142 of file AddressRanges.h.
Referenced by llvm::AddressRangesMap< T >::clear(), llvm::AddressRangesMap< T >::getRangeValueThatContains(), llvm::AddressRangesMap< T >::insert(), llvm::AddressRangesMap< T >::operator[](), and llvm::AddressRangesMap< T >::size().
The documentation for this class was generated from the following file:
include/llvm/ADT/AddressRanges.h