LLVM: llvm::Pass Class Reference
llvm::Pass Class Reference abstract
Pass interface - Implemented by all 'passes'.
#include "llvm/Pass.h"
Public Member Functions
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Pass interface - Implemented by all 'passes'.
Subclass this if you are an interprocedural optimization or you do not fit into any of the more constrained passes described below.
Definition at line 91 of file Pass.h.
Constructor & Destructor Documentation
Pass() [1/2]
llvm::Pass::Pass (PassKind K, char & pid) inline explicit
Definition at line 97 of file Pass.h.
Pass() [2/2]
llvm::Pass::Pass (const Pass &) delete
~Pass()
Pass::~Pass () virtual
Definition at line 43 of file Pass.cpp.
Member Function Documentation
assignPassManager()
virtual void llvm::Pass::assignPassManager (PMStack & , PassManagerType) inline virtual
Each pass is responsible for assigning a pass manager to itself.
PMS is the stack of available pass manager.
Reimplemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
Definition at line 139 of file Pass.h.
Referenced by llvm::FunctionPass::assignPassManager(), and llvm::PMTopLevelManager::schedulePass().
createPass()
Pass * Pass::createPass (AnalysisID ID) static
Definition at line 194 of file Pass.cpp.
References llvm::PassInfo::createPass(), llvm::PassRegistry::getPassInfo(), and llvm::PassRegistry::getPassRegistry().
Referenced by llvm::TargetPassConfig::addPass().
createPrinterPass()
virtual Pass * llvm::Pass::createPrinterPass (raw_ostream & OS, const std::string & Banner) const pure virtual
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
Implemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
Referenced by llvm::PMTopLevelManager::schedulePass().
doFinalization()
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented in llvm::AAEvalLegacyPass, llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfo, llvm::AMDGPUAsmPrinter, llvm::AsmPrinter, llvm::AssumptionCacheTracker, llvm::AVRAsmPrinter, llvm::FPPassManager, llvm::GlobalsAAWrapperPass, llvm::IRSimilarityIdentifierWrapperPass, llvm::legacy::FunctionPassManagerImpl, llvm::MachineModuleInfoWrapperPass, llvm::ModuleSummaryIndexWrapperPass, llvm::NVPTXAsmPrinter, llvm::objcarc::ObjCARCAAWrapperPass, llvm::PhysicalRegisterUsageInfo, llvm::ProfileSummaryInfoWrapperPass, llvm::ScopedNoAliasAAWrapperPass, and llvm::TypeBasedAAWrapperPass.
Definition at line 120 of file Pass.h.
Referenced by llvm::FPPassManager::doFinalization(), INITIALIZE_PASS(), and llvm::RGPassManager::runOnFunction().
doInitialization()
virtual bool llvm::Pass::doInitialization (Module &) inline virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented in llvm::AAEvalLegacyPass, llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfo, llvm::AMDGPUResourceUsageAnalysis, llvm::AsmPrinter, llvm::FPPassManager, llvm::IRSimilarityIdentifierWrapperPass, llvm::legacy::FunctionPassManagerImpl, llvm::MachineFunctionPass, llvm::MachineModuleInfoWrapperPass, llvm::NVPTXAsmPrinter, llvm::objcarc::ObjCARCAAWrapperPass, llvm::PhysicalRegisterUsageInfo, llvm::ProfileSummaryInfoWrapperPass, llvm::ScopedNoAliasAAWrapperPass, llvm::SystemZAsmPrinter, llvm::TypeBasedAAWrapperPass, and llvm::X86AsmPrinter.
Definition at line 116 of file Pass.h.
Referenced by llvm::AMDGPUResourceUsageAnalysis::doInitialization(), llvm::FPPassManager::doInitialization(), and INITIALIZE_PASS().
dump()
LLVM_DUMP_METHOD void Pass::dump () const
Definition at line 135 of file Pass.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::HexagonPacketizerList::cleanUpDotCur(), llvm::PPCInstrInfo::combineRLWINM(), llvm::AArch64TargetLowering::EmitInstrWithCustomInserter(), llvm::SystemZPostRASchedStrategy::enterMBB(), estimateRSStackSizeLimit(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::HexagonInstrInfo::reversePredSense(), llvm::LiveIntervals::runOnMachineFunction(), and llvm::RAGreedy::runOnMachineFunction().
dumpPassStructure()
void Pass::dumpPassStructure (unsigned Offset = 0) virtual
Reimplemented in llvm::FPPassManager, llvm::legacy::FunctionPassManagerImpl, llvm::LPPassManager, and llvm::RGPassManager.
Definition at line 73 of file Pass.cpp.
References llvm::dbgs(), getPassName(), llvm::raw_ostream::indent(), and Offset.
getAdjustedAnalysisPointer()
void * Pass::getAdjustedAnalysisPointer (AnalysisID ID) virtual
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
If needed, it should override this to adjust the this pointer as needed for the specified pass info.
Definition at line 109 of file Pass.cpp.
Referenced by getAnalysisID(), getAnalysisID(), and getAnalysisIfAvailable().
getAnalysis() [1/2]
template<typename AnalysisType > AnalysisType & llvm::Pass::getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
Definition at line 230 of file PassAnalysisSupport.h.
References assert(), and getAnalysisID().
Referenced by llvm::SIRegisterInfo::findReachingDef(), llvm::CFLAndersAAWrapperPass::initializePass(), llvm::CFLSteensAAWrapperPass::initializePass(), llvm::LegacyInlinerBase::inlineCalls(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SITargetLowering::passSpecialInputs(), llvm::AAEvalLegacyPass::runOnFunction(), llvm::AAResultsWrapperPass::runOnFunction(), llvm::BasicAAWrapperPass::runOnFunction(), llvm::BlockFrequencyInfoWrapperPass::runOnFunction(), llvm::DemandedBitsWrapperPass::runOnFunction(), llvm::DependenceAnalysisWrapperPass::runOnFunction(), llvm::DominanceFrontierWrapperPass::runOnFunction(), llvm::DOTGraphTraitsPrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::GVNHoistLegacyPass::runOnFunction(), llvm::InjectTLIMappingsLegacy::runOnFunction(), llvm::InstructionCombiningPass::runOnFunction(), llvm::LazyBlockFrequencyInfoPass::runOnFunction(), llvm::LazyBranchProbabilityInfoPass::runOnFunction(), llvm::LazyValueInfoWrapperPass::runOnFunction(), llvm::LegacyDivergenceAnalysis::runOnFunction(), llvm::LoopAccessLegacyAnalysis::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::MemoryDependenceWrapperPass::runOnFunction(), llvm::MemorySSAPrinterLegacyPass::runOnFunction(), llvm::MemorySSAWrapperPass::runOnFunction(), llvm::OptimizationRemarkEmitterWrapperPass::runOnFunction(), llvm::PredicateInfoPrinterLegacyPass::runOnFunction(), llvm::RegionInfoPass::runOnFunction(), llvm::ReplaceWithVeclibLegacy::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::ScalarEvolutionWrapperPass::runOnFunction(), llvm::SCEVAAWrapperPass::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::StackSafetyInfoWrapperPass::runOnFunction(), llvm::IVUsersWrapperPass::runOnLoop(), AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::BreakFalseDeps::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::MachineBlockFrequencyInfo::runOnMachineFunction(), llvm::MachineDominanceFrontier::runOnMachineFunction(), llvm::MachineOptimizationRemarkEmitterPass::runOnMachineFunction(), llvm::MachineRegionInfoPass::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::RAGreedy::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), MachineCycleInfoPrinterPass::runOnMachineFunction(), llvm::AMDGPUResourceUsageAnalysis::runOnModule(), llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::GlobalsAAWrapperPass::runOnModule(), llvm::ModuleSummaryIndexWrapperPass::runOnModule(), llvm::SPIRVModuleAnalysis::runOnModule(), llvm::StackSafetyGlobalInfoWrapperPass::runOnModule(), llvm::SwingSchedulerDAG::schedule(), and llvm::AsmPrinter::SetupMachineFunction().
getAnalysis() [2/2]
template<typename AnalysisType > AnalysisType & llvm::Pass::getAnalysis (Function & F, bool * Changed = nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
If as part of the dependencies, an IR transformation is triggered (e.g. because the analysis requires BreakCriticalEdges), and Changed is non null, *Changed is updated.
Definition at line 260 of file PassAnalysisSupport.h.
References assert(), Changed, F, and getAnalysisID().
getAnalysisID() [1/2]
template<typename AnalysisType > AnalysisType & llvm::Pass::getAnalysisID (AnalysisID PI) const
Definition at line 236 of file PassAnalysisSupport.h.
References assert(), and getAdjustedAnalysisPointer().
Referenced by getAnalysis(), and getAnalysis().
getAnalysisID() [2/2]
template<typename AnalysisType > AnalysisType & llvm::Pass::getAnalysisID (AnalysisID PI, Function & F, bool * Changed = nullptr)
Definition at line 267 of file PassAnalysisSupport.h.
References assert(), Changed, F, and getAdjustedAnalysisPointer().
getAnalysisIfAvailable()
template<typename AnalysisType > AnalysisType * llvm::Pass::getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
This is different than getAnalysis in that it can fail (if the analysis results haven't been computed), so should only be used if you can handle the case when the analysis is not available. This method is often used by transformation APIs to update analysis results for a pass automatically as the transform is performed.
Definition at line 211 of file PassAnalysisSupport.h.
References assert(), and getAdjustedAnalysisPointer().
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::doInitialization(), llvm::AsmPrinter::emitFunctionBody(), llvm::AsmPrinter::emitStackMaps(), llvm::RegBankSelect::EdgeInsertPoint::frequency(), llvm::RegBankSelect::InstrInsertPoint::frequency(), llvm::RegBankSelect::MBBInsertPoint::frequency(), llvm::AAResultsWrapperPass::runOnFunction(), llvm::BasicAAWrapperPass::runOnFunction(), llvm::InstructionCombiningPass::runOnFunction(), llvm::LegacyDivergenceAnalysis::runOnFunction(), llvm::LoopAccessLegacyAnalysis::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUResourceUsageAnalysis::runOnModule(), llvm::StackSafetyGlobalInfoWrapperPass::runOnModule(), llvm::AMDGPUPerfHintAnalysis::runOnSCC(), and llvm::MachineBasicBlock::SplitCriticalEdge().
getAnalysisUsage()
void Pass::getAnalysisUsage (AnalysisUsage &) const virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented in AMDGPUDAGToDAGISel, llvm::AAEvalLegacyPass, llvm::AAResultsWrapperPass, llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfo, llvm::AMDGPUAsmPrinter, llvm::AMDGPUPerfHintAnalysis, llvm::AMDGPUResourceUsageAnalysis, llvm::ARMBlockPlacement, llvm::AsmPrinter, llvm::BasicAAWrapperPass, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::BreakFalseDeps, llvm::CallGraphSCCPass, llvm::CallGraphWrapperPass, llvm::CFIFixup, llvm::CFLAndersAAWrapperPass, llvm::CFLSteensAAWrapperPass, llvm::CycleInfoWrapperPass, llvm::DemandedBitsWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsPrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DummyCGSCCPass, llvm::ExecutionDomainFix, llvm::ExternalAAWrapperPass, llvm::FPPassManager, llvm::GISelCSEAnalysisWrapperPass, llvm::GISelKnownBitsAnalysis, llvm::GlobalsAAWrapperPass, llvm::gvn::GVNLegacyPass, llvm::GVNHoistLegacyPass, llvm::ImmutableModuleSummaryIndexWrapperPass, llvm::InjectTLIMappingsLegacy, llvm::InstructionCombiningPass, llvm::InstructionSelect, llvm::IntervalPartition, llvm::IRSimilarityIdentifierWrapperPass, llvm::IRTranslator, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LazyMachineBlockFrequencyInfoPass, llvm::LazyValueInfoWrapperPass, llvm::LCSSAVerificationPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LegacyDivergenceAnalysis, llvm::LegacyInlinerBase, llvm::Legalizer, llvm::LiveIntervals, llvm::LiveStacks, llvm::LiveVariables, llvm::LoadStoreOpt, llvm::Localizer, llvm::LoopAccessLegacyAnalysis, llvm::LPPassManager, llvm::MachineBlockFrequencyInfo, llvm::MachineBranchProbabilityInfo, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominanceFrontier, llvm::MachineDominatorTree, llvm::MachineFunctionPass, llvm::MachineLoopInfo, llvm::MachineOptimizationRemarkEmitterPass, llvm::MachinePipeliner, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MachineTraceMetrics, llvm::MemoryDependenceWrapperPass, llvm::MemorySSAPrinterLegacyPass, llvm::MemorySSAWrapperPass, llvm::MipsDAGToDAGISel, llvm::ModuleSummaryIndexWrapperPass, llvm::NVPTXAsmPrinter, llvm::objcarc::ObjCARCAAWrapperPass, llvm::OptimizationRemarkEmitterWrapperPass, llvm::PhiValuesWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::PredicateInfoPrinterLegacyPass, llvm::ProfileSummaryInfoWrapperPass, llvm::RAGreedy, llvm::ReachingDefAnalysis, llvm::RegAllocEvictionAdvisorAnalysis, llvm::RegAllocScoring, llvm::RegBankSelect, llvm::RegionInfoPass, llvm::ReplaceWithVeclibLegacy, llvm::RGPassManager, llvm::ScalarEvolutionWrapperPass, llvm::SCEVAAWrapperPass, llvm::ScopedNoAliasAAWrapperPass, llvm::SelectionDAGISel, llvm::SlotIndexes, llvm::SPIRVModuleAnalysis, llvm::sroa::SROALegacyPass, llvm::StackProtector, llvm::StackSafetyGlobalInfoWrapperPass, llvm::StackSafetyInfoWrapperPass, llvm::TypeBasedAAWrapperPass, llvm::UnifyFunctionExitNodesLegacyPass, llvm::VirtRegMap, llvm::WebAssemblyExceptionInfo, and MachineCycleInfoPrinterPass.
Definition at line 97 of file Pass.cpp.
Referenced by llvm::MachineFunctionPass::getAnalysisUsage().
getAsImmutablePass()
ImmutablePass * Pass::getAsImmutablePass () virtual
Reimplemented in llvm::ImmutablePass.
Definition at line 113 of file Pass.cpp.
getAsPMDataManager()
PMDataManager * Pass::getAsPMDataManager () virtual
Reimplemented in llvm::FPPassManager, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LPPassManager, and llvm::RGPassManager.
Definition at line 117 of file Pass.cpp.
getPassID()
AnalysisID llvm::Pass::getPassID () const inline
getPassID - Return the PassID number that corresponds to this pass.
Definition at line 110 of file Pass.h.
Referenced by getPassName(), and llvm::TargetPassConfig::insertPass().
getPassKind()
PassKind llvm::Pass::getPassKind () const inline
Definition at line 102 of file Pass.h.
getPassName()
StringRef Pass::getPassName () const virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented in AMDGPUDAGToDAGISel, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::AVRAsmPrinter, llvm::AVRDAGToDAGISel, llvm::AVRFrameAnalyzer, llvm::BasicBlockSectionsProfileReader, llvm::CSKYAsmPrinter, llvm::DetectRoundChange, llvm::FixAllFDIVSQRT, llvm::FPPassManager, llvm::HexagonAsmPrinter, llvm::HexagonDAGToDAGISel, llvm::InsertNOPLoad, llvm::InstructionSelect, llvm::IRTranslator, llvm::Legalizer, llvm::LoadStoreOpt, llvm::Localizer, llvm::LoongArchAsmPrinter, llvm::LoongArchDAGToDAGISel, llvm::LPPassManager, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::MipsDAGToDAGISel, llvm::MIRAddFSDiscriminators, llvm::MIRProfileLoaderPass, llvm::NVPTXDAGToDAGISel, llvm::R600AsmPrinter, llvm::RAGreedy, llvm::RegAllocScoring, llvm::RegBankSelect, llvm::RGPassManager, llvm::RISCVDAGToDAGISel, llvm::sroa::SROALegacyPass, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::X86AsmPrinter, and X86ReturnThunks.
Definition at line 80 of file Pass.cpp.
References getPassID(), llvm::PassRegistry::getPassInfo(), llvm::PassInfo::getPassName(), and llvm::PassRegistry::getPassRegistry().
Referenced by llvm::PMDataManager::addLowerLevelRequiredPass(), dumpPassStructure(), print(), llvm::PassManagerPrettyStackEntry::print(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::PMTopLevelManager::schedulePass(), llvm::FunctionPass::skipFunction(), llvm::LoopPass::skipLoop(), and llvm::RegionPass::skipRegion().
getPotentialPassManagerType()
PassManagerType Pass::getPotentialPassManagerType () const virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
Definition at line 92 of file Pass.cpp.
References llvm::PMT_Unknown.
Referenced by llvm::PMTopLevelManager::schedulePass().
getResolver()
AnalysisResolver * llvm::Pass::getResolver () const inline
Definition at line 150 of file Pass.h.
Referenced by llvm::PMTopLevelManager::setLastUser().
lookupPassInfo() [1/2]
const PassInfo * Pass::lookupPassInfo (const void * TI) static
Definition at line 186 of file Pass.cpp.
References llvm::PassRegistry::getPassInfo(), and llvm::PassRegistry::getPassRegistry().
Referenced by llvm::AnalysisUsage::addPreserved().
lookupPassInfo() [2/2]
const PassInfo * Pass::lookupPassInfo (StringRef Arg) static
Definition at line 190 of file Pass.cpp.
References Arg, llvm::PassRegistry::getPassInfo(), and llvm::PassRegistry::getPassRegistry().
mustPreserveAnalysisID()
bool Pass::mustPreserveAnalysisID (char & AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
This obviously cannot give you a properly typed instance of the class if you don't have the class name available (use getAnalysisIfAvailable if you do), but it can tell you if you need to preserve the pass at least.
Definition at line 68 of file Pass.cpp.
Referenced by llvm::LPPassManager::runOnFunction().
operator=()
Pass & llvm::Pass::operator= (const Pass &) delete
preparePassManager()
void Pass::preparePassManager (PMStack &) virtual
Check if available pass managers are suitable for this pass or not.
Reimplemented in llvm::LoopPass, and llvm::RegionPass.
Definition at line 88 of file Pass.cpp.
print()
void Pass::print (raw_ostream & OS, const Module * M) const virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented in llvm::AMDGPUArgumentUsageInfo, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::CallGraphWrapperPass, llvm::CycleInfoWrapperPass, llvm::DemandedBitsWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::IntervalPartition, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LazyMachineBlockFrequencyInfoPass, llvm::LegacyDivergenceAnalysis, llvm::LiveIntervals, llvm::LiveStacks, llvm::LoopAccessLegacyAnalysis, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominatorTree, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MemorySSAWrapperPass, llvm::PhysicalRegisterUsageInfo, llvm::PostDominatorTreeWrapperPass, llvm::RegionInfoPass, llvm::ScalarEvolutionWrapperPass, llvm::StackSafetyGlobalInfoWrapperPass, llvm::StackSafetyInfoWrapperPass, llvm::VirtRegMap, and llvm::WebAssemblyExceptionInfo.
Definition at line 129 of file Pass.cpp.
References getPassName().
Referenced by llvm::A57ChainingConstraint::apply(), llvm::LiveDebugVariables::dump(), dump(), llvm::SpillPlacement::BlockConstraint::dump(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::HexagonLowerToMC(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::DiagnosticInfoMIROptimization::MachineArgument::MachineArgument(), llvm::operator<<(), llvm::operator<<(), llvm::LazyMachineBlockFrequencyInfoPass::print(), llvm::MachineBasicBlock::print(), llvm::AArch64InstPrinter::printAdrpLabel(), llvm::AArch64InstPrinter::printAlignedLabel(), llvm::AArch64InstPrinter::printInst(), and llvm::X86IntelInstPrinter::printU8Imm().
releaseMemory()
void Pass::releaseMemory () virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented in llvm::AssumptionCacheTracker, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::CallGraphWrapperPass, llvm::CycleInfoWrapperPass, llvm::DemandedBitsWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::GISelCSEAnalysisWrapperPass, llvm::GISelKnownBitsAnalysis, llvm::IntervalPartition, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LazyMachineBlockFrequencyInfoPass, llvm::LazyValueInfoWrapperPass, llvm::LiveIntervals, llvm::LiveStacks, llvm::LiveVariables, llvm::LoopAccessLegacyAnalysis, llvm::MachineBlockFrequencyInfo, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominanceFrontier, llvm::MachineDominatorTree, llvm::MachineLoopInfo, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MachineTraceMetrics, llvm::MemoryDependenceWrapperPass, llvm::MemorySSAWrapperPass, llvm::PhiValuesWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::RAGreedy, llvm::ReachingDefAnalysis, llvm::RegionInfoPass, llvm::ScalarEvolutionWrapperPass, llvm::SlotIndexes, and llvm::WebAssemblyExceptionInfo.
Definition at line 101 of file Pass.cpp.
Referenced by llvm::legacy::FunctionPassManagerImpl::releaseMemoryOnTheFly().
setResolver()
void Pass::setResolver (AnalysisResolver * AR)
Definition at line 121 of file Pass.cpp.
References assert().
Referenced by llvm::legacy::FunctionPassManager::FunctionPassManager().
verifyAnalysis()
void Pass::verifyAnalysis () const virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented in llvm::AssumptionCacheTracker, llvm::DominatorTreeWrapperPass, llvm::MachineDominatorTree, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MachineTraceMetrics, llvm::MemorySSAWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::RegionInfoPass, and llvm::ScalarEvolutionWrapperPass.
Definition at line 105 of file Pass.cpp.
The documentation for this class was generated from the following files:
include/llvm/Pass.h
include/llvm/PassAnalysisSupport.h
lib/IR/Pass.cpp