LLVM: llvm::SPIRVGlobalRegistry Class Reference
llvm::SPIRVGlobalRegistry Class Reference
#include "Target/SPIRV/SPIRVGlobalRegistry.h"
Public Member Functions
SPIRVGlobalRegistry (unsigned PointerSize)
void add (const Constant *C, MachineFunction *MF, Register R)
void add (const GlobalVariable *GV, MachineFunction *MF, Register R)
void add (const Function *F, MachineFunction *MF, Register R)
void add (const Argument *Arg, MachineFunction *MF, Register R)
Register find (const Constant *C, MachineFunction *MF)
Register find (const GlobalVariable *GV, MachineFunction *MF)
Register find (const Function *F, MachineFunction *MF)
void buildDepsGraph (std::vector< SPIRV::DTSortableEntry * > &Graph, MachineModuleInfo *MMI=nullptr)
SPIRVType * assignTypeToVReg (const Type *Type, Register VReg, MachineIRBuilder &MIRBuilder, SPIRV::AccessQualifier AQ=SPIRV::AccessQualifier::ReadWrite, bool EmitIR=true)
SPIRVType * assignIntTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * assignVectTypeToVReg (SPIRVType *BaseType, unsigned NumElements, Register VReg, MachineInstr &I, const SPIRVInstrInfo &TII)
void assignSPIRVTypeToVReg (SPIRVType *Type, Register VReg, MachineFunction &MF)
SPIRVType * getOrCreateSPIRVType (const Type *Type, MachineIRBuilder &MIRBuilder, SPIRV::AccessQualifier AQ=SPIRV::AccessQualifier::ReadWrite, bool EmitIR=true)
const Type * getTypeForSPIRVType (const SPIRVType *Ty) const
SPIRVType * getSPIRVTypeForVReg (Register VReg) const
bool hasSPIRVTypeForVReg (Register VReg) const
Register getSPIRVTypeID (const SPIRVType *SpirvType) const
void setCurrentFunc (MachineFunction &MF)
bool isScalarOfType (Register VReg, unsigned TypeOpcode) const
bool isScalarOrVectorOfType (Register VReg, unsigned TypeOpcode) const
unsigned getScalarOrVectorBitWidth (const SPIRVType *Type) const
bool isScalarOrVectorSigned (const SPIRVType *Type) const
SPIRV::StorageClass getPointerStorageClass (Register VReg) const
unsigned getPointerSize () const
Register buildConstantInt (uint64_t Val, MachineIRBuilder &MIRBuilder, SPIRVType *SpvType=nullptr, bool EmitIR=true)
Register getOrCreateConstInt (uint64_t Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII)
Register buildConstantFP (APFloat Val, MachineIRBuilder &MIRBuilder, SPIRVType *SpvType=nullptr)
Register getOrCreateConsIntVector (uint64_t Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII)
Register getOrCreateUndef (MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII)
Register buildGlobalVariable (Register Reg, SPIRVType *BaseType, StringRef Name, const GlobalValue *GV, SPIRV::StorageClass Storage, const MachineInstr *Init, bool IsConst, bool HasLinkageTy, SPIRV::LinkageType LinkageType, MachineIRBuilder &MIRBuilder, bool IsInstSelector)
SPIRVType * getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVBoolType (MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateSPIRVBoolType (MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVVectorType (SPIRVType *BaseType, unsigned NumElements, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateSPIRVVectorType (SPIRVType *BaseType, unsigned NumElements, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVPointerType (SPIRVType *BaseType, MachineIRBuilder &MIRBuilder, SPIRV::StorageClass SClass=SPIRV::StorageClass::Function)
SPIRVType * getOrCreateSPIRVPointerType (SPIRVType *BaseType, MachineInstr &I, const SPIRVInstrInfo &TII, SPIRV::StorageClass SClass=SPIRV::StorageClass::Function)
SPIRVType * getOrCreateOpTypeFunctionWithArgs (const Type *Ty, SPIRVType *RetType, const SmallVectorImpl< SPIRVType * > &ArgTypes, MachineIRBuilder &MIRBuilder)
Public Attributes
MachineFunction * CurMF
Detailed Description
Definition at line 27 of file SPIRVGlobalRegistry.h.
Constructor & Destructor Documentation
SPIRVGlobalRegistry()
SPIRVGlobalRegistry::SPIRVGlobalRegistry (unsigned PointerSize)
Definition at line 24 of file SPIRVGlobalRegistry.cpp.
Member Function Documentation
add() [1/4]
void llvm::SPIRVGlobalRegistry::add (const Argument * Arg, MachineFunction * MF, Register R) inline
Definition at line 78 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::add(), and Arg.
add() [2/4]
void llvm::SPIRVGlobalRegistry::add (const Constant * C, MachineFunction * MF, Register R) inline
Definition at line 66 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::add(), and llvm::CallingConv::C.
Referenced by addConstantsToTrack(), and llvm::SPIRVCallLowering::lowerFormalArguments().
add() [3/4]
void llvm::SPIRVGlobalRegistry::add (const Function * F, MachineFunction * MF, Register R) inline
Definition at line 74 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::add(), and F.
add() [4/4]
void llvm::SPIRVGlobalRegistry::add (const GlobalVariable * GV, MachineFunction * MF, Register R) inline
Definition at line 70 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::add().
assignIntTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignIntTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 27 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), llvm::BitWidth, CurMF, getOrCreateSPIRVIntegerType(), I, and TII.
assignSPIRVTypeToVReg()
void SPIRVGlobalRegistry::assignSPIRVTypeToVReg (SPIRVType * Type, Register VReg, MachineFunction & MF)
Definition at line 55 of file SPIRVGlobalRegistry.cpp.
Referenced by assignIntTypeToVReg(), assignTypeToVReg(), assignVectTypeToVReg(), buildGlobalVariable(), convertPtrToInt(), getOrCreateUndef(), insertAssignInstr(), processSwitches(), and propagateSPIRVType().
assignTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignTypeToVReg (const Type * Type, Register VReg, MachineIRBuilder & MIRBuilder, SPIRV::AccessQualifier AQ = SPIRV::AccessQualifier::ReadWrite, bool EmitIR = true)
Definition at line 45 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
Referenced by buildConstantFP(), buildConstantInt(), llvm::SPIRVCallLowering::lowerCall(), and llvm::SPIRVCallLowering::lowerFormalArguments().
assignVectTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignVectTypeToVReg (SPIRVType * BaseType, unsigned NumElements, Register VReg, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 36 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), CurMF, getOrCreateSPIRVVectorType(), I, and TII.
Referenced by getOrCreateConsIntVector().
buildConstantFP()
Register SPIRVGlobalRegistry::buildConstantFP (APFloat Val, MachineIRBuilder & MIRBuilder, SPIRVType * SpvType = nullptr)
Definition at line 222 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::add(), assert(), assignTypeToVReg(), llvm::BitWidth, llvm::MachineIRBuilder::buildFConstant(), llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::ConstantFP::get(), llvm::Type::getContext(), llvm::Type::getFloatTy(), llvm::MachineIRBuilder::getMF(), getScalarOrVectorBitWidth(), getTypeForSPIRVType(), llvm::Type::isFloatingPointTy(), llvm::Register::isValid(), and llvm::LLT::scalar().
buildConstantInt()
Register SPIRVGlobalRegistry::buildConstantInt (uint64_t Val, MachineIRBuilder & MIRBuilder, SPIRVType * SpvType = nullptr, bool EmitIR = true)
Definition at line 176 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::MachineInstrBuilder::addDef(), addNumImm(), llvm::MachineInstrBuilder::addUse(), assert(), assignTypeToVReg(), llvm::BitWidth, llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::cast(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::MachineIRBuilder::getMF(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), llvm::Register::isValid(), llvm::SPIRV::ReadWrite, and llvm::LLT::scalar().
buildDepsGraph()
void llvm::SPIRVGlobalRegistry::buildDepsGraph (std::vector< SPIRV::DTSortableEntry * > & Graph, MachineModuleInfo * MMI = nullptr) inline
Definition at line 94 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph().
buildGlobalVariable()
Register SPIRVGlobalRegistry::buildGlobalVariable (Register Reg, SPIRVType * BaseType, StringRef Name, const GlobalValue * GV, SPIRV::StorageClass Storage, const MachineInstr * Init, bool IsConst, bool HasLinkageTy, SPIRV::LinkageType LinkageType, MachineIRBuilder & MIRBuilder, bool IsInstSelector)
Definition at line 297 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::SPIRV::Alignment, assert(), assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstr(), buildOpDecorate(), buildOpName(), llvm::cast(), llvm::SPIRV::Constant, llvm::constrainSelectedInstRegOperands(), CurMF, llvm::GlobalValue::ExternalLinkage, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::GlobalObject::getAlign(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::Value::getName(), llvm::MachineInstr::getOperand(), llvm::GlobalValue::getParent(), llvm::MachineOperand::getReg(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), llvm::Value::hasName(), llvm::SPIRV::LinkageAttributes, MRI, Name, llvm::LLT::pointer(), Reg, llvm::Align::value(), and llvm::MaybeAlign::valueOrOne().
find() [1/3]
Register llvm::SPIRVGlobalRegistry::find (const Constant * C, MachineFunction * MF) inline
Definition at line 82 of file SPIRVGlobalRegistry.h.
References llvm::CallingConv::C, and llvm::SPIRVGeneralDuplicatesTracker::find().
Referenced by addConstantsToTrack(), and llvm::SPIRVCallLowering::lowerCall().
find() [2/3]
Register llvm::SPIRVGlobalRegistry::find (const Function * F, MachineFunction * MF) inline
Definition at line 90 of file SPIRVGlobalRegistry.h.
References F, and llvm::SPIRVGeneralDuplicatesTracker::find().
find() [3/3]
Register llvm::SPIRVGlobalRegistry::find (const GlobalVariable * GV, MachineFunction * MF) inline
Definition at line 86 of file SPIRVGlobalRegistry.h.
References llvm::SPIRVGeneralDuplicatesTracker::find().
getOrCreateConsIntVector()
Register SPIRVGlobalRegistry::getOrCreateConsIntVector (uint64_t Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII)
Definition at line 247 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), assignVectTypeToVReg(), llvm::BitWidth, llvm::BuildMI(), llvm::cast(), llvm::constrainSelectedInstRegOperands(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::ConstantInt::get(), llvm::VectorType::getElementCount(), llvm::VectorType::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), getOrCreateConstInt(), getOrCreateSPIRVIntegerType(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::ConstantVector::getSplat(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), I, llvm::Register::isValid(), llvm::Type::isVectorTy(), llvm::LLT::scalar(), and TII.
getOrCreateConstInt()
Register SPIRVGlobalRegistry::getOrCreateConstInt (uint64_t Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII)
Definition at line 145 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), addNumImm(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::BuildMI(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::MachineBasicBlock::getParent(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), I, and TII.
Referenced by getOrCreateConsIntVector().
getOrCreateOpTypeFunctionWithArgs()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs (const Type * Ty, SPIRVType * RetType, const SmallVectorImpl< SPIRVType * > & ArgTypes, MachineIRBuilder & MIRBuilder)
Definition at line 473 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::MachineIRBuilder::getMF(), and getSPIRVTypeForVReg().
Referenced by llvm::SPIRVCallLowering::lowerFormalArguments().
getOrCreateSPIRVBoolType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVBoolType (MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 725 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeForVReg(), I, and TII.
getOrCreateSPIRVBoolType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVBoolType (MachineIRBuilder & MIRBuilder)
Definition at line 718 of file SPIRVGlobalRegistry.cpp.
References llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
getOrCreateSPIRVIntegerType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 703 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::BitWidth, llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeForVReg(), I, and TII.
getOrCreateSPIRVIntegerType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineIRBuilder & MIRBuilder)
Definition at line 687 of file SPIRVGlobalRegistry.cpp.
References llvm::BitWidth, llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
Referenced by assignIntTypeToVReg(), and getOrCreateConsIntVector().
getOrCreateSPIRVPointerType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVPointerType (SPIRVType * BaseType, MachineInstr & I, const SPIRVInstrInfo & TII, SPIRV::StorageClass SClass = SPIRV::StorageClass::Function)
Definition at line 771 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::PointerType::get(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeForVReg(), getSPIRVTypeID(), getTypeForSPIRVType(), I, storageClassToAddressSpace(), and TII.
getOrCreateSPIRVPointerType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVPointerType (SPIRVType * BaseType, MachineIRBuilder & MIRBuilder, SPIRV::StorageClass SClass = SPIRV::StorageClass::Function)
Definition at line 762 of file SPIRVGlobalRegistry.cpp.
References llvm::PointerType::get(), getOrCreateSPIRVType(), getTypeForSPIRVType(), and storageClassToAddressSpace().
getOrCreateSPIRVType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVType (const Type * Type, MachineIRBuilder & MIRBuilder, SPIRV::AccessQualifier AQ = SPIRV::AccessQualifier::ReadWrite, bool EmitIR = true)
Definition at line 608 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::MachineIRBuilder::getMF(), and getSPIRVTypeForVReg().
Referenced by assignTypeToVReg(), getOrCreateSPIRVBoolType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVVectorType(), insertAssignInstr(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::SPIRVCallLowering::lowerFormalArguments(), processSwitches(), and propagateSPIRVType().
getOrCreateSPIRVVectorType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVVectorType (SPIRVType * BaseType, unsigned NumElements, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 745 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::FixedVectorType::get(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeForVReg(), getSPIRVTypeID(), getTypeForSPIRVType(), I, and TII.
getOrCreateSPIRVVectorType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVVectorType (SPIRVType * BaseType, unsigned NumElements, MachineIRBuilder & MIRBuilder)
Definition at line 737 of file SPIRVGlobalRegistry.cpp.
References llvm::FixedVectorType::get(), getOrCreateSPIRVType(), and getTypeForSPIRVType().
Referenced by assignVectTypeToVReg().
getOrCreateUndef()
Register SPIRVGlobalRegistry::getOrCreateUndef (MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII)
Definition at line 788 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVGeneralDuplicatesTracker::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), assignSPIRVTypeToVReg(), llvm::BuildMI(), llvm::constrainSelectedInstRegOperands(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), CurMF, llvm::SPIRVGeneralDuplicatesTracker::find(), llvm::UndefValue::get(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), I, llvm::Register::isValid(), llvm::LLT::scalar(), and TII.
getPointerSize()
unsigned llvm::SPIRVGlobalRegistry::getPointerSize () const inline
Definition at line 165 of file SPIRVGlobalRegistry.h.
getPointerStorageClass()
SPIRV::StorageClass SPIRVGlobalRegistry::getPointerStorageClass (Register VReg) const
Definition at line 679 of file SPIRVGlobalRegistry.cpp.
References assert(), and getSPIRVTypeForVReg().
getScalarOrVectorBitWidth()
unsigned SPIRVGlobalRegistry::getScalarOrVectorBitWidth (const SPIRVType * Type) const
Definition at line 653 of file SPIRVGlobalRegistry.cpp.
References assert(), getSPIRVTypeForVReg(), and llvm_unreachable.
Referenced by buildConstantFP(), buildConstantInt(), getOrCreateConsIntVector(), and getOrCreateConstInt().
getSPIRVTypeForVReg()
SPIRVType * SPIRVGlobalRegistry::getSPIRVTypeForVReg (Register VReg) const
Definition at line 598 of file SPIRVGlobalRegistry.cpp.
References CurMF.
Referenced by createNewIdReg(), getOrCreateOpTypeFunctionWithArgs(), getOrCreateSPIRVBoolType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVType(), getOrCreateSPIRVVectorType(), getPointerStorageClass(), getScalarOrVectorBitWidth(), hasSPIRVTypeForVReg(), isScalarOfType(), isScalarOrVectorOfType(), isScalarOrVectorSigned(), llvm::SPIRVLegalizerInfo::legalizeCustom(), processSwitches(), and propagateSPIRVType().
getSPIRVTypeID()
Register SPIRVGlobalRegistry::getSPIRVTypeID (const SPIRVType * SpirvType) const
Definition at line 496 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::MachineInstr::defs(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::uses().
Referenced by buildConstantInt(), buildGlobalVariable(), getOrCreateConsIntVector(), getOrCreateConstInt(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVVectorType(), getOrCreateUndef(), insertAssignInstr(), llvm::SPIRVCallLowering::lowerCall(), and llvm::SPIRVCallLowering::lowerFormalArguments().
getTypeForSPIRVType()
const Type * llvm::SPIRVGlobalRegistry::getTypeForSPIRVType (const SPIRVType * Ty) const inline
Definition at line 126 of file SPIRVGlobalRegistry.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by buildConstantFP(), buildConstantInt(), buildGlobalVariable(), getOrCreateConsIntVector(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVVectorType(), getOrCreateSPIRVVectorType(), and getOrCreateUndef().
hasSPIRVTypeForVReg()
bool llvm::SPIRVGlobalRegistry::hasSPIRVTypeForVReg (Register VReg) const inline
Definition at line 137 of file SPIRVGlobalRegistry.h.
References getSPIRVTypeForVReg().
isScalarOfType()
bool SPIRVGlobalRegistry::isScalarOfType (Register VReg, unsigned TypeOpcode) const
Definition at line 631 of file SPIRVGlobalRegistry.cpp.
References assert(), and getSPIRVTypeForVReg().
isScalarOrVectorOfType()
bool SPIRVGlobalRegistry::isScalarOrVectorOfType (Register VReg, unsigned TypeOpcode) const
Definition at line 638 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::MachineInstr::getOpcode(), and getSPIRVTypeForVReg().
isScalarOrVectorSigned()
bool SPIRVGlobalRegistry::isScalarOrVectorSigned (const SPIRVType * Type) const
Definition at line 667 of file SPIRVGlobalRegistry.cpp.
References assert(), getSPIRVTypeForVReg(), and llvm_unreachable.
setCurrentFunc()
void llvm::SPIRVGlobalRegistry::setCurrentFunc (MachineFunction & MF) inline
Definition at line 144 of file SPIRVGlobalRegistry.h.
References CurMF.
Referenced by llvm::SPIRVCallLowering::lowerCall(), and llvm::SPIRVCallLowering::lowerFormalArguments().
Member Data Documentation
CurMF
MachineFunction* llvm::SPIRVGlobalRegistry::CurMF
Definition at line 64 of file SPIRVGlobalRegistry.h.
Referenced by assignIntTypeToVReg(), assignVectTypeToVReg(), buildConstantInt(), buildGlobalVariable(), getOrCreateConsIntVector(), getOrCreateConstInt(), getOrCreateSPIRVBoolType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVVectorType(), getOrCreateUndef(), getSPIRVTypeForVReg(), and setCurrentFunc().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVGlobalRegistry.h
lib/Target/SPIRV/SPIRVGlobalRegistry.cpp