LLVM: llvm::AVRDAGToDAGISel Class Reference
llvm::AVRDAGToDAGISel Class Reference
Lowers LLVM IR (in DAG form) to AVR MC instructions (in DAG form).
Public Member Functions
AVRDAGToDAGISel (AVRTargetMachine &TM, CodeGenOpt::Level OptLevel)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
bool SelectAddr (SDNode *Op, SDValue N, SDValue &Base, SDValue &Disp)
bool selectIndexedLoad (SDNode *N)
unsigned selectIndexedProgMemLoad (const LoadSDNode *LD, MVT VT, int Bank)
bool SelectInlineAsmMemoryOperand (const SDValue &Op, unsigned ConstraintCode, std::vector< SDValue > &OutOps) override
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
Public Member Functions inherited from llvm::SelectionDAGISel
SelectionDAGISel (TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
~SelectionDAGISel () override
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
virtual void emitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
virtual void PostprocessISelDAG ()
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
virtual bool CheckPatternPredicate (unsigned PredNo) const
CheckPatternPredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
CheckNodePredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicateWithOperands (SDNode *N, unsigned PredNo, const SmallVectorImpl< SDValue > &Operands) const
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
void SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
bool mayRaiseFPException (SDNode *Node) const
Return whether the node may raise an FP exception.
bool isOrEquivalentToAdd (const SDNode *N) const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Additional Inherited Members
Public Types inherited from llvm::SelectionDAGISel
enum BuiltinOpcodes {
OPC_Scope , OPC_RecordNode , OPC_RecordChild0 , OPC_RecordChild1 ,
OPC_RecordChild2 , OPC_RecordChild3 , OPC_RecordChild4 , OPC_RecordChild5 ,
OPC_RecordChild6 , OPC_RecordChild7 , OPC_RecordMemRef , OPC_CaptureGlueInput ,
OPC_MoveChild , OPC_MoveChild0 , OPC_MoveChild1 , OPC_MoveChild2 ,
OPC_MoveChild3 , OPC_MoveChild4 , OPC_MoveChild5 , OPC_MoveChild6 ,
OPC_MoveChild7 , OPC_MoveParent , OPC_CheckSame , OPC_CheckChild0Same ,
OPC_CheckChild1Same , OPC_CheckChild2Same , OPC_CheckChild3Same , OPC_CheckPatternPredicate ,
OPC_CheckPredicate , OPC_CheckPredicateWithOperands , OPC_CheckOpcode , OPC_SwitchOpcode ,
OPC_CheckType , OPC_CheckTypeRes , OPC_SwitchType , OPC_CheckChild0Type ,
OPC_CheckChild1Type , OPC_CheckChild2Type , OPC_CheckChild3Type , OPC_CheckChild4Type ,
OPC_CheckChild5Type , OPC_CheckChild6Type , OPC_CheckChild7Type , OPC_CheckInteger ,
OPC_CheckChild0Integer , OPC_CheckChild1Integer , OPC_CheckChild2Integer , OPC_CheckChild3Integer ,
OPC_CheckChild4Integer , OPC_CheckCondCode , OPC_CheckChild2CondCode , OPC_CheckValueType ,
OPC_CheckComplexPat , OPC_CheckAndImm , OPC_CheckOrImm , OPC_CheckImmAllOnesV ,
OPC_CheckImmAllZerosV , OPC_CheckFoldableChainNode , OPC_EmitInteger , OPC_EmitStringInteger ,
OPC_EmitRegister , OPC_EmitRegister2 , OPC_EmitConvertToTarget , OPC_EmitMergeInputChains ,
OPC_EmitMergeInputChains1_0 , OPC_EmitMergeInputChains1_1 , OPC_EmitMergeInputChains1_2 , OPC_EmitCopyToReg ,
OPC_EmitCopyToReg2 , OPC_EmitNodeXForm , OPC_EmitNode , OPC_EmitNode0 ,
OPC_EmitNode1 , OPC_EmitNode2 , OPC_MorphNodeTo , OPC_MorphNodeTo0 ,
OPC_MorphNodeTo1 , OPC_MorphNodeTo2 , OPC_CompleteMatch , OPC_Coverage
}
enum {
OPFL_None = 0 , OPFL_Chain = 1 , OPFL_GlueInput = 2 , OPFL_GlueOutput = 4 ,
OPFL_MemRefs = 8 , OPFL_Variadic0 = 1<<4 , OPFL_Variadic1 = 2<<4 , OPFL_Variadic2 = 3<<4 ,
OPFL_Variadic3 = 4<<4 , OPFL_Variadic4 = 5<<4 , OPFL_Variadic5 = 6<<4 , OPFL_Variadic6 = 7<<4 ,
OPFL_VariadicInfo = OPFL_Variadic6
}
Static Public Member Functions inherited from llvm::SelectionDAGISel
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
static void InvalidateNodeId (SDNode *N)
static int getUninvalidatedNodeId (SDNode *N)
static void EnforceNodeIdInvariant (SDNode *N)
static int getNumFixedFromVariadicInfo (unsigned Flags)
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::SelectionDAGISel
TargetMachine & TM
const TargetLibraryInfo * LibInfo
std::unique_ptr< FunctionLoweringInfo > FuncInfo
SwiftErrorValueTracking * SwiftError
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
std::unique_ptr< SelectionDAGBuilder > SDB
AAResults * AA = nullptr
GCFunctionInfo * GFI = nullptr
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
bool FastISelFailed
SmallPtrSet< const Instruction *, 4 > ElidedArgCopyInstrs
bool UseInstrRefDebugInfo = false
std::unique_ptr< OptimizationRemarkEmitter > ORE
Current optimization remark emitter.
Static Public Attributes inherited from llvm::SelectionDAGISel
static char ID = 0
Protected Member Functions inherited from llvm::SelectionDAGISel
void ReplaceUses (SDValue F, SDValue T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
void ReplaceUses (SDNode *F, SDNode *T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceNode (SDNode *F, SDNode *T)
Replace all uses of F with T, then remove F from the DAG.
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops, const SDLoc &DL)
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
virtual StringRef getPatternForIndex (unsigned index)
getPatternForIndex - Patterns selected by tablegen during ISEL
virtual StringRef getIncludePathForIndex (unsigned index)
getIncludePathForIndex - get the td source location of pattern instantiation
bool shouldOptForSize (const MachineFunction *MF) const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::SelectionDAGISel
unsigned DAGSize = 0
DAGSize - Size of DAG being instruction selected.
Detailed Description
Lowers LLVM IR (in DAG form) to AVR MC instructions (in DAG form).
Definition at line 27 of file AVRISelDAGToDAG.cpp.
Constructor & Destructor Documentation
AVRDAGToDAGISel()
llvm::AVRDAGToDAGISel::AVRDAGToDAGISel (AVRTargetMachine & TM, CodeGenOpt::Level OptLevel) inline
Definition at line 29 of file AVRISelDAGToDAG.cpp.
Member Function Documentation
getPassName()
StringRef llvm::AVRDAGToDAGISel::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 32 of file AVRISelDAGToDAG.cpp.
runOnMachineFunction()
bool llvm::AVRDAGToDAGISel::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 59 of file AVRISelDAGToDAG.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::SelectionDAGISel::MF, and llvm::SelectionDAGISel::runOnMachineFunction().
SelectAddr()
bool llvm::AVRDAGToDAGISel::SelectAddr (SDNode * Op, SDValue N, SDValue & Base, SDValue & Disp)
Definition at line 64 of file AVRISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::sampleprof::Base, llvm::cast(), llvm::SelectionDAGISel::CurDAG, DL, llvm::dyn_cast(), llvm::ISD::FrameIndex, llvm::SelectionDAG::getDataLayout(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SelectionDAGISel::getTargetLowering(), llvm::MVT::i16, llvm::MVT::i8, llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::isUInt(), N, and llvm::ISD::SUB.
Referenced by SelectInlineAsmMemoryOperand().
selectIndexedLoad()
bool llvm::AVRDAGToDAGISel::selectIndexedLoad (SDNode * N)
Definition at line 121 of file AVRISelDAGToDAG.cpp.
References llvm::cast(), llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAGISel::getTargetLowering(), llvm::MVT::i16, llvm::MVT::i8, N, llvm::ISD::NON_EXTLOAD, llvm::MVT::Other, llvm::ISD::POST_INC, llvm::ISD::PRE_DEC, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAGISel::ReplaceUses(), and llvm::MVT::SimpleTy.
selectIndexedProgMemLoad()
unsigned llvm::AVRDAGToDAGISel::selectIndexedProgMemLoad (const LoadSDNode * LD, MVT VT, int Bank)
Definition at line 168 of file AVRISelDAGToDAG.cpp.
References assert(), llvm::cast(), llvm::AVRSubtarget::hasELPM(), llvm::MVT::i16, llvm::MVT::i8, llvm::ISD::NON_EXTLOAD, llvm::ISD::POST_INC, and llvm::MVT::SimpleTy.
SelectInlineAsmMemoryOperand()
bool llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, unsigned ConstraintID, std::vector< SDValue > & OutOps) override virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 198 of file AVRISelDAGToDAG.cpp.
References llvm::ISD::ADD, assert(), llvm::sampleprof::Base, llvm::cast(), llvm::InlineAsm::Constraint_m, llvm::InlineAsm::Constraint_Q, llvm::ISD::CopyFromReg, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SelectionDAGISel::CurDAG, DL, llvm::dyn_cast(), llvm::ISD::FrameIndex, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::AVRSubtarget::getTargetLowering(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::MVT::i8, llvm::Register::isVirtualRegister(), llvm::SelectionDAGISel::MF, Reg, SelectAddr(), llvm::ISD::SUB, and llvm::APInt::ult().
The documentation for this class was generated from the following file:
lib/Target/AVR/AVRISelDAGToDAG.cpp