LLVM: TransferTracker Class Reference
TransferTracker Class Reference
Tracker for converting machine value locations and variable values into variable locations (the output of LiveDebugValues), recorded as DBG_VALUEs specifying block live-in locations and transfers within blocks.
Classes
struct LocAndProperties
struct Transfer
Record of all changes in variable locations at a block position.
struct UseBeforeDef
Record of a use-before-def: created when a value that's live-in to the current block isn't available in any machine location, but it will be defined in this block.
Public Member Functions
TransferTracker (const TargetInstrInfo *TII, MLocTracker *MTracker, MachineFunction &MF, const TargetRegisterInfo &TRI, const BitVector &CalleeSavedRegs, const TargetPassConfig &TPC)
void loadInlocs (MachineBasicBlock &MBB, ValueTable &MLocs, const SmallVectorImpl< std::pair< DebugVariable, DbgValue > > &VLocs, unsigned NumLocs)
Load object with live-in variable values.
void addUseBeforeDef (const DebugVariable &Var, const DbgValueProperties &Properties, ValueIDNum ID)
Record that Var has value ID, a value that becomes available later in the function.
void checkInstForNewValues (unsigned Inst, MachineBasicBlock::iterator pos)
After the instruction at index Inst and position pos has been processed, check whether it defines a variable value in a use-before-def.
void flushDbgValues (MachineBasicBlock::iterator Pos, MachineBasicBlock *MBB)
Helper to move created DBG_VALUEs into Transfers collection.
bool isEntryValueVariable (const DebugVariable &Var, const DIExpression *Expr) const
bool isEntryValueValue (const ValueIDNum &Val) const
bool recoverAsEntryValue (const DebugVariable &Var, const DbgValueProperties &Prop, const ValueIDNum &Num)
void redefVar (const MachineInstr &MI)
Change a variable value after encountering a DBG_VALUE inside a block.
void redefVar (const MachineInstr &MI, const DbgValueProperties &Properties, Optional< LocIdx > OptNewLoc)
Handle a change in variable location within a block.
void clobberMloc (LocIdx MLoc, MachineBasicBlock::iterator Pos, bool MakeUndef=true)
Account for a location mloc being clobbered.
void clobberMloc (LocIdx MLoc, ValueIDNum OldValue, MachineBasicBlock::iterator Pos, bool MakeUndef=true)
Overload that takes an explicit value OldValue for when the value in MLoc has changed and the TransferTracker's locations have not been updated yet.
void transferMlocs (LocIdx Src, LocIdx Dst, MachineBasicBlock::iterator Pos)
Transfer variables based on Src to be based on Dst.
MachineInstrBuilder emitMOLoc (const MachineOperand &MO, const DebugVariable &Var, const DbgValueProperties &Properties)
Public Attributes
const TargetInstrInfo * TII
const TargetLowering * TLI
MLocTracker * MTracker
This machine location tracker is assumed to always contain the up-to-date value mapping for all machine locations.
MachineFunction & MF
bool ShouldEmitDebugEntryValues
SmallVector< Transfer, 32 > Transfers
Collection of transfers (DBG_VALUEs) to be inserted.
SmallVector< ValueIDNum, 32 > VarLocs
Local cache of what-value-is-in-what-LocIdx.
DenseMap< LocIdx, SmallSet< DebugVariable, 4 > > ActiveMLocs
Map from LocIdxes to which DebugVariables are based that location.
DenseMap< DebugVariable, LocAndProperties > ActiveVLocs
Map from DebugVariable to it's current location and qualifying meta information.
SmallVector< MachineInstr *, 4 > PendingDbgValues
Temporary cache of DBG_VALUEs to be entered into the Transfers collection.
DenseMap< unsigned, SmallVector< UseBeforeDef, 1 > > UseBeforeDefs
Map from instruction index (within the block) to the set of UseBeforeDefs that become defined at that instruction.
DenseSet< DebugVariable > UseBeforeDefVariables
The set of variables that are in UseBeforeDefs and can become a location once the relevant value is defined.
const TargetRegisterInfo & TRI
const BitVector & CalleeSavedRegs
Detailed Description
Tracker for converting machine value locations and variable values into variable locations (the output of LiveDebugValues), recorded as DBG_VALUEs specifying block live-in locations and transfers within blocks.
Operating on a per-block basis, this class takes a (pre-loaded) MLocTracker and must be initialized with the set of variable values that are live-in to the block. The caller then repeatedly calls process(). TransferTracker picks out variable locations for the live-in variable values (if there is a location) and creates the corresponding DBG_VALUEs. Then, as the block is stepped through, transfers of values between machine locations are identified and if profitable, a DBG_VALUE created.
This is where debug use-before-defs would be resolved: a variable with an unavailable value could materialize in the middle of a block, when the value becomes available. Or, we could detect clobbers and re-specify the variable in a backup location. (XXX these are unimplemented).
Definition at line 174 of file InstrRefBasedImpl.cpp.
Constructor & Destructor Documentation
TransferTracker()
TransferTracker::TransferTracker (const TargetInstrInfo * TII, MLocTracker * MTracker, MachineFunction & MF, const TargetRegisterInfo & TRI, const BitVector & CalleeSavedRegs, const TargetPassConfig & TPC) inline
Definition at line 245 of file InstrRefBasedImpl.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::TargetPassConfig::getTM(), MF, ShouldEmitDebugEntryValues, TLI, and TM.
Member Function Documentation
addUseBeforeDef()
void TransferTracker::addUseBeforeDef (const DebugVariable & Var, const DbgValueProperties & Properties, ValueIDNum ID) inline
Record that Var has value ID, a value that becomes available later in the function.
Definition at line 354 of file InstrRefBasedImpl.cpp.
References UseBeforeDefs, and UseBeforeDefVariables.
Referenced by loadInlocs().
checkInstForNewValues()
void TransferTracker::checkInstForNewValues (unsigned Inst, MachineBasicBlock::iterator pos) inline
After the instruction at index Inst and position pos has been processed, check whether it defines a variable value in a use-before-def.
If so, and the variable value hasn't changed since the start of the block, create a DBG_VALUE.
Definition at line 365 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::MLocTracker::emitLoc(), flushDbgValues(), MTracker, PendingDbgValues, llvm::SmallVectorTemplateBase< T, bool >::push_back(), LiveDebugValues::MLocTracker::readMLoc(), UseBeforeDefs, and UseBeforeDefVariables.
clobberMloc() [1/2]
void TransferTracker::clobberMloc (LocIdx MLoc, MachineBasicBlock::iterator Pos, bool MakeUndef = true) inline
Account for a location mloc being clobbered.
Examine the variable locations that will be terminated: and try to recover them by using another location. Optionally, given MakeUndef, emit a DBG_VALUE to explicitly terminate a location if it can't be recovered.
Definition at line 531 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, LiveDebugValues::LocIdx::asU64(), clobberMloc(), and VarLocs.
Referenced by clobberMloc().
clobberMloc() [2/2]
void TransferTracker::clobberMloc (LocIdx MLoc, ValueIDNum OldValue, MachineBasicBlock::iterator Pos, bool MakeUndef = true) inline
Overload that takes an explicit value OldValue for when the value in MLoc has changed and the TransferTracker's locations have not been updated yet.
Definition at line 544 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, ActiveVLocs, LiveDebugValues::LocIdx::asU64(), LiveDebugValues::MLocTracker::emitLoc(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), LiveDebugValues::ValueIDNum::EmptyValue, flushDbgValues(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LiveDebugValues::MLocTracker::locations(), MTracker, llvm::None, PendingDbgValues, llvm::SmallVectorTemplateBase< T, bool >::push_back(), recoverAsEntryValue(), and VarLocs.
emitMOLoc()
MachineInstrBuilder TransferTracker::emitMOLoc (const MachineOperand & MO, const DebugVariable & Var, const DbgValueProperties & Properties) inline
Definition at line 644 of file InstrRefBasedImpl.cpp.
References llvm::BuildMI(), LiveDebugValues::DbgValueProperties::DIExpr, DL, llvm::MCInstrInfo::get(), llvm::MDNode::getContext(), llvm::DebugVariable::getInlinedAt(), llvm::DILocalVariable::getScope(), llvm::DebugVariable::getVariable(), LiveDebugValues::DbgValueProperties::Indirect, MF, and TII.
Referenced by loadInlocs(), and recoverAsEntryValue().
flushDbgValues()
void TransferTracker::flushDbgValues (MachineBasicBlock::iterator Pos, MachineBasicBlock * MBB) inline
Helper to move created DBG_VALUEs into Transfers collection.
Definition at line 391 of file InstrRefBasedImpl.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::getBundleStart(), llvm::MachineBasicBlock::instr_begin(), MBB, PendingDbgValues, llvm::SmallVectorBase< Size_T >::size(), and Transfers.
Referenced by checkInstForNewValues(), clobberMloc(), loadInlocs(), and transferMlocs().
isEntryValueValue()
bool TransferTracker::isEntryValueValue (const ValueIDNum & Val) const inline
Definition at line 420 of file InstrRefBasedImpl.cpp.
References FP, LiveDebugValues::ValueIDNum::getBlock(), llvm::TargetRegisterInfo::getFrameRegister(), LiveDebugValues::ValueIDNum::getLoc(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), LiveDebugValues::ValueIDNum::isPHI(), LiveDebugValues::MLocTracker::isSpill(), LiveDebugValues::MLocTracker::LocIdxToLocID, MF, MTracker, TLI, and TRI.
Referenced by recoverAsEntryValue().
isEntryValueVariable()
bool TransferTracker::isEntryValueVariable (const DebugVariable & Var, const DIExpression * Expr) const inline
Definition at line 406 of file InstrRefBasedImpl.cpp.
References llvm::DebugVariable::getInlinedAt(), llvm::DIExpression::getNumElements(), llvm::DebugVariable::getVariable(), and llvm::DILocalVariable::isParameter().
Referenced by recoverAsEntryValue().
loadInlocs()
void TransferTracker::loadInlocs (MachineBasicBlock & MBB, ValueTable & MLocs, const SmallVectorImpl< std::pair< DebugVariable, DbgValue > > & VLocs, unsigned NumLocs) inline
Load object with live-in variable values.
mlocs contains the live-in values in each machine location, while vlocs the live-in variable values. This method picks variable locations for the live-in variables, creates DBG_VALUEs and puts them in Transfers, then prepares the other object fields to track variable locations as we step through the block. FIXME: could just examine mloctracker instead of passing in mlocs?
Definition at line 262 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, ActiveVLocs, addUseBeforeDef(), LiveDebugValues::LocIdx::asU64(), llvm::MachineBasicBlock::begin(), CalleeSavedRegs, LiveDebugValues::DbgValue::Const, LiveDebugValues::DbgValue::Def, LiveDebugValues::MLocTracker::emitLoc(), emitMOLoc(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), flushDbgValues(), LiveDebugValues::ValueIDNum::getBlock(), llvm::MachineBasicBlock::getNumber(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LiveDebugValues::LocIdx::isIllegal(), LiveDebugValues::ValueIDNum::isPHI(), LiveDebugValues::MLocTracker::isSpill(), llvm::MCRegAliasIterator::isValid(), LiveDebugValues::MLocTracker::locations(), LiveDebugValues::MLocTracker::LocIdxToLocID, LiveDebugValues::LocIdx::MakeIllegalLoc(), MBB, MTracker, LiveDebugValues::MLocTracker::NumRegs, PendingDbgValues, llvm::SmallVectorTemplateBase< T, bool >::push_back(), recoverAsEntryValue(), llvm::BitVector::test(), TRI, UseBeforeDefs, UseBeforeDefVariables, and VarLocs.
recoverAsEntryValue()
bool TransferTracker::recoverAsEntryValue (const DebugVariable & Var, const DbgValueProperties & Prop, const ValueIDNum & Num) inline
Definition at line 435 of file InstrRefBasedImpl.cpp.
References llvm::MachineOperand::CreateReg(), LiveDebugValues::DbgValueProperties::DIExpr, emitMOLoc(), llvm::DIExpression::EntryValue, LiveDebugValues::ValueIDNum::getLoc(), LiveDebugValues::DbgValueProperties::Indirect, isEntryValueValue(), isEntryValueVariable(), LiveDebugValues::MLocTracker::LocIdxToLocID, MTracker, PendingDbgValues, llvm::DIExpression::prepend(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and ShouldEmitDebugEntryValues.
Referenced by clobberMloc(), and loadInlocs().
redefVar() [1/2]
void TransferTracker::redefVar (const MachineInstr & MI) inline
Change a variable value after encountering a DBG_VALUE inside a block.
Definition at line 462 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, ActiveVLocs, llvm::MachineOperand::getReg(), LiveDebugValues::MLocTracker::getRegMLoc(), llvm::MachineOperand::isReg(), MI, MTracker, redefVar(), and UseBeforeDefVariables.
Referenced by redefVar().
redefVar() [2/2]
void TransferTracker::redefVar (const MachineInstr & MI, const DbgValueProperties & Properties, Optional< LocIdx > OptNewLoc) inline
Handle a change in variable location within a block.
Terminate the variables current location, and record the value it now refers to, so that we can detect location transfers later on.
Definition at line 489 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, ActiveVLocs, LiveDebugValues::LocIdx::asU64(), MI, MTracker, P, LiveDebugValues::MLocTracker::readMLoc(), UseBeforeDefVariables, and VarLocs.
transferMlocs()
void TransferTracker::transferMlocs (LocIdx Src, LocIdx Dst, MachineBasicBlock::iterator Pos) inline
Transfer variables based on Src to be based on Dst.
This handles both register copies as well as spills and restores. Creates DBG_VALUEs describing the movement.
Definition at line 611 of file InstrRefBasedImpl.cpp.
References ActiveMLocs, ActiveVLocs, assert(), LiveDebugValues::MLocTracker::emitLoc(), LiveDebugValues::ValueIDNum::EmptyValue, EmulateOldLDV, flushDbgValues(), MI, MTracker, PendingDbgValues, llvm::SmallVectorTemplateBase< T, bool >::push_back(), LiveDebugValues::MLocTracker::readMLoc(), and VarLocs.
Member Data Documentation
ActiveMLocs
DenseMap<LocIdx, SmallSet<DebugVariable, 4> > TransferTracker::ActiveMLocs
Map from LocIdxes to which DebugVariables are based that location.
Mantained while stepping through the block. Not accurate if VarLocs[Idx] != MTracker->LocIdxToIDNum[Idx].
Definition at line 211 of file InstrRefBasedImpl.cpp.
Referenced by clobberMloc(), clobberMloc(), loadInlocs(), redefVar(), redefVar(), and transferMlocs().
ActiveVLocs
DenseMap<DebugVariable, LocAndProperties> TransferTracker::ActiveVLocs
Map from DebugVariable to it's current location and qualifying meta information.
To be used in conjunction with ActiveMLocs to construct enough information for the DBG_VALUEs for a particular LocIdx.
Definition at line 216 of file InstrRefBasedImpl.cpp.
Referenced by clobberMloc(), loadInlocs(), redefVar(), redefVar(), and transferMlocs().
CalleeSavedRegs
const BitVector& TransferTracker::CalleeSavedRegs
Definition at line 243 of file InstrRefBasedImpl.cpp.
Referenced by loadInlocs().
MF
MachineFunction& TransferTracker::MF
Definition at line 182 of file InstrRefBasedImpl.cpp.
Referenced by emitMOLoc(), isEntryValueValue(), and TransferTracker().
MTracker
MLocTracker* TransferTracker::MTracker
This machine location tracker is assumed to always contain the up-to-date value mapping for all machine locations.
TransferTracker only reads information from it. (XXX make it const?)
Definition at line 181 of file InstrRefBasedImpl.cpp.
Referenced by checkInstForNewValues(), clobberMloc(), isEntryValueValue(), loadInlocs(), recoverAsEntryValue(), redefVar(), redefVar(), and transferMlocs().
PendingDbgValues
SmallVector<MachineInstr *, 4> TransferTracker::PendingDbgValues
Temporary cache of DBG_VALUEs to be entered into the Transfers collection.
Definition at line 219 of file InstrRefBasedImpl.cpp.
Referenced by checkInstForNewValues(), clobberMloc(), flushDbgValues(), loadInlocs(), recoverAsEntryValue(), and transferMlocs().
ShouldEmitDebugEntryValues
bool TransferTracker::ShouldEmitDebugEntryValues
Definition at line 183 of file InstrRefBasedImpl.cpp.
Referenced by recoverAsEntryValue(), and TransferTracker().
TII
const TargetInstrInfo* TransferTracker::TII
Definition at line 176 of file InstrRefBasedImpl.cpp.
Referenced by emitMOLoc().
TLI
const TargetLowering* TransferTracker::TLI
Definition at line 177 of file InstrRefBasedImpl.cpp.
Referenced by isEntryValueValue(), and TransferTracker().
Transfers
SmallVector<Transfer, 32> TransferTracker::Transfers
Collection of transfers (DBG_VALUEs) to be inserted.
Definition at line 200 of file InstrRefBasedImpl.cpp.
Referenced by flushDbgValues().
TRI
const TargetRegisterInfo& TransferTracker::TRI
Definition at line 242 of file InstrRefBasedImpl.cpp.
Referenced by isEntryValueValue(), and loadInlocs().
UseBeforeDefs
DenseMap<unsigned, SmallVector<UseBeforeDef, 1> > TransferTracker::UseBeforeDefs
Map from instruction index (within the block) to the set of UseBeforeDefs that become defined at that instruction.
Definition at line 235 of file InstrRefBasedImpl.cpp.
Referenced by addUseBeforeDef(), checkInstForNewValues(), and loadInlocs().
UseBeforeDefVariables
DenseSet<DebugVariable> TransferTracker::UseBeforeDefVariables
The set of variables that are in UseBeforeDefs and can become a location once the relevant value is defined.
An element being erased from this collection prevents the use-before-def materializing.
Definition at line 240 of file InstrRefBasedImpl.cpp.
Referenced by addUseBeforeDef(), checkInstForNewValues(), loadInlocs(), redefVar(), and redefVar().
VarLocs
SmallVector<ValueIDNum, 32> TransferTracker::VarLocs
Local cache of what-value-is-in-what-LocIdx.
Used to identify differences between TransferTrackers view of variable locations and MLocTrackers. For example, MLocTracker observes all clobbers, but TransferTracker lazily does not.
Definition at line 206 of file InstrRefBasedImpl.cpp.
Referenced by clobberMloc(), clobberMloc(), loadInlocs(), redefVar(), and transferMlocs().
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp