LLVM: llvm::DWARFUnitVector Class Reference
llvm::DWARFUnitVector Class Reference final
Describe a collection of units.
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
Public Types
using UnitVector = SmallVectorImpl<std::unique_ptr<DWARFUnit>>
using iterator = typename UnitVector::iterator
using iterator_range = llvm::iterator_range<typename UnitVector::iterator>
using compile_unit_range
Public Types inherited from llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >
using iterator
using const_iterator
using reference
using size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >
using size_type
using difference_type
using value_type
using iterator
using const_iterator
using const_reverse_iterator
using reverse_iterator
using reference
using const_reference
using pointer
using const_pointer
Public Member Functions
DWARFUnit * getUnitForOffset (uint64_t Offset) const
DWARFUnit * getUnitForIndexEntry (const DWARFUnitIndex::Entry &E)
void addUnitsForSection (DWARFContext &C, const DWARFSection &Section, DWARFSectionKind SectionKind)
Read units from a .debug_info or .debug_types section.
void addUnitsForDWOSection (DWARFContext &C, const DWARFSection &DWOSection, DWARFSectionKind SectionKind, bool Lazy=false)
Read units from a .debug_info.dwo or .debug_types.dwo section.
DWARFUnit * addUnit (std::unique_ptr< DWARFUnit > Unit)
Add an existing DWARFUnit to this UnitVector.
unsigned getNumUnits () const
Returns number of all units held by this instance.
unsigned getNumInfoUnits () const
Returns number of units from all .debug_info[.dwo] sections.
unsigned getNumTypesUnits () const
Returns number of units from all .debug_types[.dwo] sections.
void finishedInfoUnits ()
Indicate that parsing .debug_info[.dwo] is done, and remaining units will be from .debug_types[.dwo].
Public Member Functions inherited from llvm::SmallVector< std::unique_ptr< DWARFUnit >, 1 >
SmallVector ()
SmallVector (size_t Size, const std::unique_ptr< DWARFUnit > &Value=std::unique_ptr< DWARFUnit >())
SmallVector (ItTy S, ItTy E)
SmallVector (const iterator_range< RangeTy > &R)
SmallVector (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
SmallVector (const SmallVector &RHS)
SmallVector (SmallVector &&RHS)
SmallVector (SmallVectorImpl< std::unique_ptr< DWARFUnit > > &&RHS)
~SmallVector ()
SmallVector & operator= (const SmallVector &RHS)
SmallVector & operator= (SmallVector &&RHS)
SmallVector & operator= (SmallVectorImpl< std::unique_ptr< DWARFUnit > > &&RHS)
SmallVector & operator= (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
Public Member Functions inherited from llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >
SmallVectorImpl (const SmallVectorImpl &)=delete
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize (size_type N, ValueParamT NV)
void resize_for_overwrite (size_type N)
Like resize, but T is POD, the new values won't be initialized.
void truncate (size_type N)
Like resize, but requires that N is less than size().
void reserve (size_type N)
void pop_back_n (size_type NumItems)
LLVM_NODISCARD std::unique_ptr< DWARFUnit > pop_back_val ()
void swap (SmallVectorImpl &RHS)
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, ValueParamT Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
void append (const SmallVectorImpl &RHS)
void assign (size_type NumElts, ValueParamT Elt)
void assign (in_iter in_start, in_iter in_end)
void assign (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
void assign (const SmallVectorImpl &RHS)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, std::unique_ptr< DWARFUnit > &&Elt)
iterator insert (iterator I, const std::unique_ptr< DWARFUnit > &Elt)
iterator insert (iterator I, size_type NumToInsert, ValueParamT Elt)
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
bool operator> (const SmallVectorImpl &RHS) const
bool operator<= (const SmallVectorImpl &RHS) const
bool operator>= (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >
void push_back (const std::unique_ptr< DWARFUnit > &Elt)
void push_back (std::unique_ptr< DWARFUnit > &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< std::unique_ptr< DWARFUnit > > >
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
Additional Inherited Members
Protected Types inherited from llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >
using ValueParamT
Protected Types inherited from llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >
using ValueParamT
Protected Member Functions inherited from llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >
SmallVectorImpl (unsigned N)
void assignRemote (SmallVectorImpl &&RHS)
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
std::unique_ptr< DWARFUnit > * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (std::unique_ptr< DWARFUnit > *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (std::unique_ptr< DWARFUnit > *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const std::unique_ptr< DWARFUnit > * reserveForParamAndGetAddress (const std::unique_ptr< DWARFUnit > &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
std::unique_ptr< DWARFUnit > * reserveForParamAndGetAddress (std::unique_ptr< DWARFUnit > &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const std::unique_ptr< DWARFUnit > &Elt)
std::unique_ptr< DWARFUnit > & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const std::unique_ptr< DWARFUnit > *From, const std::unique_ptr< DWARFUnit > *To)
Check whether any part of the range will be invalidated by clearing.
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const std::unique_ptr< DWARFUnit > *From, const std::unique_ptr< DWARFUnit > *To)
Check whether any part of the range will be invalidated by growing.
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< std::unique_ptr< DWARFUnit > > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >
static void destroy_range (std::unique_ptr< DWARFUnit > *S, std::unique_ptr< DWARFUnit > *E)
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static std::unique_ptr< DWARFUnit > && forward_value_param (std::unique_ptr< DWARFUnit > &&V)
static const std::unique_ptr< DWARFUnit > & forward_value_param (const std::unique_ptr< DWARFUnit > &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >
static const std::unique_ptr< DWARFUnit > * reserveForParamAndGetAddressImpl (U *This, const std::unique_ptr< DWARFUnit > &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< std::unique_ptr< DWARFUnit > > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< std::unique_ptr< DWARFUnit > > >
void * BeginX
SmallVectorSizeType< std::unique_ptr< DWARFUnit > > Size
SmallVectorSizeType< std::unique_ptr< DWARFUnit > > Capacity
Static Protected Attributes inherited from llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >
static constexpr bool TakesParamByValue
Detailed Description
Describe a collection of units.
Intended to hold all units either from .debug_info and .debug_types, or from .debug_info.dwo and .debug_types.dwo.
Definition at line 124 of file DWARFUnit.h.
Member Typedef Documentation
compile_unit_range
using llvm::DWARFUnitVector::compile_unit_range
Initial value:
      decltype(make_filter_range(std::declval<iterator_range>(), isCompileUnit))
Definition at line 136 of file DWARFUnit.h.
iterator
using llvm::DWARFUnitVector::iterator = typename UnitVector::iterator
Definition at line 133 of file DWARFUnit.h.
iterator_range
using llvm::DWARFUnitVector::iterator_range = llvm::iterator_range<typename UnitVector::iterator>
Definition at line 134 of file DWARFUnit.h.
UnitVector
using llvm::DWARFUnitVector::UnitVector = SmallVectorImpl<std::unique_ptr<DWARFUnit>>
Definition at line 132 of file DWARFUnit.h.
Member Function Documentation
addUnit()
DWARFUnit * DWARFUnitVector::addUnit (std::unique_ptr< DWARFUnit > Unit)
Add an existing DWARFUnit to this UnitVector.
This is used by the DWARF verifier to process unit separately.
Definition at line 136 of file DWARFUnit.cpp.
References llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >::begin(), llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >::end(), I, and llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >::insert().
addUnitsForDWOSection()
void DWARFUnitVector::addUnitsForDWOSection (DWARFContext & C, const DWARFSection & DWOSection, DWARFSectionKind SectionKind, bool Lazy = false)
Read units from a .debug_info.dwo or .debug_types.dwo section.
Calls made before finishedInfoUnits() are assumed to be for .debug_info.dwo sections, calls after finishedInfoUnits() are for .debug_types.dwo sections. Caller must not mix calls to addUnitsForSection and addUnitsForDWOSection.
Definition at line 53 of file DWARFUnit.cpp.
References llvm::CallingConv::C, and D.
addUnitsForSection()
void DWARFUnitVector::addUnitsForSection (DWARFContext & C, const DWARFSection & Section, DWARFSectionKind SectionKind)
Read units from a .debug_info or .debug_types section.
Calls made before finishedInfoUnits() are assumed to be for .debug_info sections, calls after finishedInfoUnits() are for .debug_types sections. Caller must not mix calls to addUnitsForSection and addUnitsForDWOSection.
Definition at line 42 of file DWARFUnit.cpp.
References llvm::CallingConv::C, and D.
finishedInfoUnits()
void llvm::DWARFUnitVector::finishedInfoUnits () inline
Indicate that parsing .debug_info[.dwo] is done, and remaining units will be from .debug_types[.dwo].
Definition at line 170 of file DWARFUnit.h.
References size().
getNumInfoUnits()
unsigned llvm::DWARFUnitVector::getNumInfoUnits () const inline
Returns number of units from all .debug_info[.dwo] sections.
Definition at line 163 of file DWARFUnit.h.
References size().
Referenced by llvm::DWARFContext::dwo_info_section_units(), llvm::DWARFContext::dwo_types_section_units(), llvm::DWARFContext::getNumCompileUnits(), llvm::DWARFContext::getNumDWOCompileUnits(), getUnitForIndexEntry(), getUnitForOffset(), llvm::DWARFContext::info_section_units(), and llvm::DWARFContext::types_section_units().
getNumTypesUnits()
unsigned llvm::DWARFUnitVector::getNumTypesUnits () const inline
Returns number of units from all .debug_types[.dwo] sections.
Definition at line 167 of file DWARFUnit.h.
References size().
Referenced by llvm::DWARFContext::getNumDWOTypeUnits(), and llvm::DWARFContext::getNumTypeUnits().
getNumUnits()
unsigned llvm::DWARFUnitVector::getNumUnits () const inline
Returns number of all units held by this instance.
Definition at line 161 of file DWARFUnit.h.
References size().
getUnitForIndexEntry()
DWARFUnit * DWARFUnitVector::getUnitForIndexEntry (const DWARFUnitIndex::Entry & E)
Definition at line 158 of file DWARFUnit.cpp.
References llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >::begin(), E, getNumInfoUnits(), llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >::insert(), and Offset.
Referenced by llvm::DWARFContext::getDWOCompileUnitForHash(), and llvm::DWARFContext::getTypeUnitForHash().
getUnitForOffset()
DWARFUnit * DWARFUnitVector::getUnitForOffset (uint64_t Offset) const
Definition at line 145 of file DWARFUnit.cpp.
References llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >::begin(), getNumInfoUnits(), and Offset.
Referenced by llvm::DWARFContext::getCompileUnitForOffset(), and llvm::DWARFContext::getDIEForOffset().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnit.h
lib/DebugInfo/DWARF/DWARFUnit.cpp