LLVM: llvm::SPIRVInstPrinter Class Reference
llvm::SPIRVInstPrinter Class Reference
#include "Target/SPIRV/MCTargetDesc/SPIRVInstPrinter.h"
Public Member Functions
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS) override
Print the specified MCInst to the specified raw_ostream.
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printStringImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printOpDecorate (const MCInst *MI, raw_ostream &O)
void printOpExtInst (const MCInst *MI, raw_ostream &O)
void printRemainingVariableOps (const MCInst *MI, unsigned StartIndex, raw_ostream &O, bool SkipFirstSpace=false, bool SkipImmediates=false)
void printOpConstantVarOps (const MCInst *MI, unsigned StartIndex, raw_ostream &O)
void printExtInst (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printCapability (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSourceLanguage (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printExecutionModel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printAddressingModel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemoryModel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printExecutionMode (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printStorageClass (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDim (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSamplerAddressingMode (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSamplerFilterMode (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printImageFormat (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printImageChannelOrder (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printImageChannelDataType (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printImageOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printFPFastMathMode (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printFPRoundingMode (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLinkageType (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printAccessQualifier (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printFunctionParameterAttribute (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDecoration (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printBuiltIn (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSelectionControl (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLoopControl (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printFunctionControl (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemorySemantics (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemoryOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printScope (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printGroupOperation (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printKernelEnqueueFlags (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printKernelProfilingInfo (const MCInst *MI, unsigned OpNo, raw_ostream &O)
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 19 of file SPIRVInstPrinter.h.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::SPIRVInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char * llvm::SPIRVInstPrinter::getRegisterName (unsigned RegNo) static
MCInstPrinter()
llvm::MCInstPrinter::MCInstPrinter (const MCAsmInfo & mai, const MCInstrInfo & mii, const MCRegisterInfo & mri) inline
Definition at line 82 of file MCInstPrinter.h.
printAccessQualifier()
void SPIRVInstPrinter::printAccessQualifier (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 456 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getAccessQualifierName(), and MI.
Referenced by printInst().
printAddressingModel()
void SPIRVInstPrinter::printAddressingModel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 331 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getAddressingModelName(), and MI.
printBuiltIn()
void SPIRVInstPrinter::printBuiltIn (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 485 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getBuiltInName(), and MI.
Referenced by printOpDecorate().
printCapability()
void SPIRVInstPrinter::printCapability (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 304 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getCapabilityName(), and MI.
printDecoration()
void SPIRVInstPrinter::printDecoration (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 476 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getDecorationName(), and MI.
printDim()
void SPIRVInstPrinter::printDim (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 367 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getDimName(), and MI.
printExecutionMode()
void SPIRVInstPrinter::printExecutionMode (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 349 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getExecutionModeName(), and MI.
printExecutionModel()
void SPIRVInstPrinter::printExecutionModel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 322 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getExecutionModelName(), and MI.
printExtInst()
void SPIRVInstPrinter::printExtInst (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 299 of file SPIRVInstPrinter.cpp.
References llvm_unreachable.
printFPFastMathMode()
void SPIRVInstPrinter::printFPFastMathMode (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 430 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getFPFastMathModeName(), and MI.
Referenced by printOpDecorate().
printFPRoundingMode()
void SPIRVInstPrinter::printFPRoundingMode (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 438 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getFPRoundingModeName(), and MI.
Referenced by printOpDecorate().
printFunctionControl()
void SPIRVInstPrinter::printFunctionControl (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 510 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getFunctionControlName(), and MI.
printFunctionParameterAttribute()
void SPIRVInstPrinter::printFunctionParameterAttribute (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 465 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getFunctionParameterAttributeName(), and MI.
Referenced by printOpDecorate().
printGroupOperation()
void SPIRVInstPrinter::printGroupOperation (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 542 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getGroupOperationName(), and MI.
printImageChannelDataType()
void SPIRVInstPrinter::printImageChannelDataType (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 412 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getImageChannelDataTypeName(), and MI.
printImageChannelOrder()
void SPIRVInstPrinter::printImageChannelOrder (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 403 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getImageChannelOrderName(), and MI.
printImageFormat()
void SPIRVInstPrinter::printImageFormat (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 394 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getImageFormatName(), and MI.
printImageOperand()
void SPIRVInstPrinter::printImageOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 422 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getImageOperandName(), and MI.
Referenced by printInst().
printInst()
void SPIRVInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 65 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::Aligned, assert(), llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInstrDesc::isVariadic(), MI, llvm::MCInstPrinter::MII, llvm::MCOI::OPERAND_UNKNOWN, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, printAccessQualifier(), llvm::MCInstPrinter::printAnnotation(), printImageOperand(), printInstruction(), printMemoryOperand(), printOpConstantVarOps(), printOpDecorate(), printOperand(), printOpExtInst(), and printRemainingVariableOps().
printInstruction()
void llvm::SPIRVInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst().
printKernelEnqueueFlags()
void SPIRVInstPrinter::printKernelEnqueueFlags (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 551 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getKernelEnqueueFlagsName(), and MI.
printKernelProfilingInfo()
void SPIRVInstPrinter::printKernelProfilingInfo (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 560 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getKernelProfilingInfoName(), and MI.
printLinkageType()
void SPIRVInstPrinter::printLinkageType (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 447 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getLinkageTypeName(), and MI.
Referenced by printStringImm().
printLoopControl()
void SPIRVInstPrinter::printLoopControl (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 502 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getLoopControlName(), and MI.
printMemoryModel()
void SPIRVInstPrinter::printMemoryModel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 340 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getMemoryModelName(), and MI.
printMemoryOperand()
void SPIRVInstPrinter::printMemoryOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 526 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getMemoryOperandName(), and MI.
Referenced by printInst().
printMemorySemantics()
void SPIRVInstPrinter::printMemorySemantics (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 518 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getMemorySemanticsName(), and MI.
printOpConstantVarOps()
void SPIRVInstPrinter::printOpConstantVarOps (const MCInst * MI, unsigned StartIndex, raw_ostream & O)
Definition at line 48 of file SPIRVInstPrinter.cpp.
References MI, and printRemainingVariableOps().
Referenced by printInst().
printOpDecorate()
void SPIRVInstPrinter::printOpDecorate (const MCInst * MI, raw_ostream & O)
Definition at line 193 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::BuiltIn, llvm::SPIRV::FPFastMathMode, llvm::SPIRV::FPRoundingMode, llvm::SPIRV::FuncParamAttr, llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getNumOperands(), llvm::SPIRV::LinkageAttributes, MI, llvm::MCInstPrinter::MII, printBuiltIn(), printFPFastMathMode(), printFPRoundingMode(), printFunctionParameterAttribute(), printRemainingVariableOps(), printScope(), printStringImm(), llvm::SPIRV::UniformId, and llvm::SPIRV::UserSemantic.
Referenced by printInst().
printOperand()
void SPIRVInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 248 of file SPIRVInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatImm(), llvm_unreachable, MI, printExpr(), and llvm::Register::virtReg2Index().
Referenced by printInst(), and printRemainingVariableOps().
printOpExtInst()
void SPIRVInstPrinter::printOpExtInst (const MCInst * MI, raw_ostream & O)
Definition at line 178 of file SPIRVInstPrinter.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getNumOperands(), MI, llvm::MCInstPrinter::MII, and printRemainingVariableOps().
Referenced by printInst().
printRemainingVariableOps()
void SPIRVInstPrinter::printRemainingVariableOps (const MCInst * MI, unsigned StartIndex, raw_ostream & O, bool SkipFirstSpace = false, bool SkipImmediates = false)
Definition at line 33 of file SPIRVInstPrinter.cpp.
References MI, and printOperand().
Referenced by printInst(), printOpConstantVarOps(), printOpDecorate(), and printOpExtInst().
printSamplerAddressingMode()
void SPIRVInstPrinter::printSamplerAddressingMode (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 375 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getSamplerAddressingModeName(), and MI.
printSamplerFilterMode()
void SPIRVInstPrinter::printSamplerFilterMode (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 385 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getSamplerFilterModeName(), and MI.
printScope()
void SPIRVInstPrinter::printScope (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 534 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getScopeName(), and MI.
Referenced by printOpDecorate().
printSelectionControl()
void SPIRVInstPrinter::printSelectionControl (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 494 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getSelectionControlName(), and MI.
printSourceLanguage()
void SPIRVInstPrinter::printSourceLanguage (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 313 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getSourceLanguageName(), and MI.
printStorageClass()
void SPIRVInstPrinter::printStorageClass (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 358 of file SPIRVInstPrinter.cpp.
References llvm::SPIRV::getStorageClassName(), and MI.
printStringImm()
void SPIRVInstPrinter::printStringImm (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 266 of file SPIRVInstPrinter.cpp.
References getSPIRVStringOperand(), llvm::SPIRV::LinkageAttributes, MI, and printLinkageType().
Referenced by printOpDecorate().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/MCTargetDesc/SPIRVInstPrinter.h
lib/Target/SPIRV/MCTargetDesc/SPIRVInstPrinter.cpp