LLVM: llvm::PMDataManager Class Reference
llvm::PMDataManager Class Reference abstract
PMDataManager provides the common place to manage the analysis data used by pass managers.
#include "llvm/IR/LegacyPassManagers.h"
Public Member Functions
PMDataManager ()
virtual ~PMDataManager ()
virtual Pass * getAsPass ()=0
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
Add pass P into the PassVector.
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
Add RequiredPass into list of lower level passes required by pass P.
virtual std::tuple< Pass *, bool > getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAndUsedAnalyses (SmallVectorImpl< Pass * > &UsedPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
Populate UsedPasses with analysis pass that are used or required by pass P and are available.
void initializeAnalysisImpl (Pass *P)
All Required analyses should be available to the pass as it runs! Here we fill in the AnalysisImpls member of the pass so that it can successfully use the getAnalysis() method to retrieve the implementations it needs.
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
Find the pass that implements Analysis AID.
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
void dumpUsedSet (const Pass *P) const
unsigned getNumContainedPasses () const
virtual PassManagerType getPassManagerType () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
unsigned initSizeRemarkInfo (Module &M, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount)
Set the initial size of the module if the user has specified that they want remarks for size.
void emitInstrCountChangedRemark (Pass *P, Module &M, int64_t Delta, unsigned CountBefore, StringMap< std::pair< unsigned, unsigned > > &FunctionToInstrCount, Function *F=nullptr)
Emit a remark signifying that the number of IR instructions in the module changed.
Protected Member Functions
bool isPassDebuggingExecutionsOrMore () const
isPassDebuggingExecutionsOrMore - Return true if -debug-pass=Executions or higher is specified.
Protected Attributes
PMTopLevelManager * TPM = nullptr
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Detailed Description
PMDataManager provides the common place to manage the analysis data used by pass managers.
Definition at line 295 of file LegacyPassManagers.h.
Constructor & Destructor Documentation
PMDataManager()
llvm::PMDataManager::PMDataManager () inline explicit
Definition at line 297 of file LegacyPassManagers.h.
References initializeAnalysisInfo().
~PMDataManager()
PMDataManager::~PMDataManager () virtual
Definition at line 1298 of file LegacyPassManager.cpp.
References P, and PassVector.
Member Function Documentation
add()
void PMDataManager::add (Pass * P, bool ProcessAnalysis = true)
Add pass P into the PassVector.
Update AvailableAnalysis appropriately if ProcessAnalysis is true.
Definition at line 1019 of file LegacyPassManager.cpp.
References addLowerLevelRequiredPass(), assert(), llvm::SmallVectorImpl< T >::clear(), collectRequiredAndUsedAnalyses(), llvm::PassInfo::createPass(), DM, llvm::SmallVectorBase< Size_T >::empty(), llvm::PMTopLevelManager::findAnalysisPassInfo(), getAsPass(), getDepth(), llvm_unreachable, P, PassVector, llvm::SmallVectorTemplateBase< T, bool >::push_back(), recordAvailableAnalysis(), removeNotPreservedAnalysis(), llvm::PMTopLevelManager::setLastUser(), and TPM.
Referenced by llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::ModulePass::assignPassManager(), and llvm::RegionPass::assignPassManager().
addLowerLevelRequiredPass()
void PMDataManager::addLowerLevelRequiredPass (Pass * P, Pass * RequiredPass) virtual
Add RequiredPass into list of lower level passes required by pass P.
RequiredPass is run on the fly by Pass Manager when P requests it through getAnalysis interface.
RequiredPass is run on the fly by Pass Manager when P requests it through getAnalysis interface. This should be handled by specific pass manager.
Definition at line 1270 of file LegacyPassManager.cpp.
References llvm::dbgs(), llvm::PMTopLevelManager::dumpArguments(), llvm::PMTopLevelManager::dumpPasses(), llvm::Pass::getPassName(), llvm_unreachable, P, and TPM.
Referenced by add().
collectRequiredAndUsedAnalyses()
void PMDataManager::collectRequiredAndUsedAnalyses (SmallVectorImpl< Pass * > & UP, SmallVectorImpl< AnalysisID > & RP_NotAvail, Pass * P)
Populate UsedPasses with analysis pass that are used or required by pass P and are available.
Populate UP with analysis pass that are used or required by pass P and are available.
Populate ReqPassNotAvailable with analysis pass that are required by pass P but are not available.
Populate RP_NotAvail with analysis pass that are required by pass P but are not available.
Definition at line 1094 of file LegacyPassManager.cpp.
References findAnalysisPass(), llvm::PMTopLevelManager::findAnalysisUsage(), llvm::AnalysisUsage::getRequiredSet(), llvm::AnalysisUsage::getUsedSet(), P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and TPM.
Referenced by add().
dumpLastUses()
void PMDataManager::dumpLastUses (Pass * P, unsigned Offset) const
Definition at line 1148 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::collectLastUses(), llvm::dbgs(), Offset, P, PassDebugging, and TPM.
Referenced by llvm::FPPassManager::dumpPassStructure(), llvm::LPPassManager::dumpPassStructure(), and llvm::RGPassManager::dumpPassStructure().
dumpPassArguments()
void PMDataManager::dumpPassArguments () const
Definition at line 1166 of file LegacyPassManager.cpp.
References llvm::dbgs(), llvm::PMTopLevelManager::findAnalysisPassInfo(), P, PassVector, and TPM.
dumpPassInfo()
void PMDataManager::dumpPassInfo (Pass * P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
Definition at line 1178 of file LegacyPassManager.cpp.
References llvm::dbgs(), llvm::EXECUTION_MSG, llvm::FREEING_MSG, getDepth(), llvm::MODIFICATION_MSG, llvm::ON_CG_MSG, llvm::ON_FUNCTION_MSG, llvm::ON_LOOP_MSG, llvm::ON_MODULE_MSG, llvm::ON_REGION_MSG, P, and PassDebugging.
Referenced by freePass(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
dumpPreservedSet()
void PMDataManager::dumpPreservedSet (const Pass * P) const
Definition at line 1228 of file LegacyPassManager.cpp.
References llvm::AnalysisUsage::getPreservedSet(), P, and PassDebugging.
Referenced by llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
dumpRequiredSet()
void PMDataManager::dumpRequiredSet (const Pass * P) const
Definition at line 1219 of file LegacyPassManager.cpp.
References llvm::AnalysisUsage::getRequiredSet(), P, and PassDebugging.
Referenced by llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
dumpUsedSet()
void PMDataManager::dumpUsedSet (const Pass * P) const
Definition at line 1237 of file LegacyPassManager.cpp.
References llvm::AnalysisUsage::getUsedSet(), P, and PassDebugging.
Referenced by llvm::FPPassManager::runOnFunction().
emitInstrCountChangedRemark()
void PMDataManager::emitInstrCountChangedRemark (Pass * P, Module & M, int64_t Delta, unsigned CountBefore, StringMap< std::pair< unsigned, unsigned > > & FunctionToInstrCount, Function * F = nullptr)
Emit a remark signifying that the number of IR instructions in the module changed.
F is optionally passed by passes which run on Functions, and thus always know whether or not a non-empty function is available.
FunctionToInstrCount maps the name of a Function to a pair. The first member of the pair is the IR count of the Function before running P, and the second member is the IR count of the Function after running P.
Definition at line 87 of file LegacyPassManager.cpp.
References llvm::BasicBlock::begin(), llvm::Function::empty(), F, llvm::find_if(), P, and PassName.
Referenced by llvm::FPPassManager::runOnFunction(), and llvm::LPPassManager::runOnFunction().
findAnalysisPass()
Pass * PMDataManager::findAnalysisPass (AnalysisID AID, bool SearchParent)
Find the pass that implements Analysis AID.
If desired pass is not found then return NULL.
Definition at line 1132 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::findAnalysisPass(), I, and TPM.
Referenced by collectRequiredAndUsedAnalyses(), llvm::AnalysisResolver::getAnalysisIfAvailable(), initializeAnalysisImpl(), and verifyPreservedAnalysis().
freePass()
void PMDataManager::freePass (Pass * P, StringRef Msg, enum PassDebuggingString DBG_STR)
Remove P.
Definition at line 989 of file LegacyPassManager.cpp.
References dumpPassInfo(), llvm::PMTopLevelManager::findAnalysisPassInfo(), llvm::FREEING_MSG, llvm::getPassTimer(), P, TPM, and X.
Referenced by removeDeadPasses(), and llvm::LPPassManager::runOnFunction().
getAsPass()
virtual Pass * llvm::PMDataManager::getAsPass () pure virtual
Implemented in llvm::FPPassManager, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LPPassManager, and llvm::RGPassManager.
Referenced by add().
getAvailableAnalysis()
DenseMap< AnalysisID, Pass * > * llvm::PMDataManager::getAvailableAnalysis () inline
Definition at line 385 of file LegacyPassManagers.h.
getDepth()
unsigned llvm::PMDataManager::getDepth () const inline
Definition at line 364 of file LegacyPassManagers.h.
Referenced by add(), dumpPassInfo(), llvm::PMStack::push(), and llvm::PMTopLevelManager::setLastUser().
getNumContainedPasses()
unsigned llvm::PMDataManager::getNumContainedPasses () const inline
Definition at line 376 of file LegacyPassManagers.h.
References PassVector.
Referenced by llvm::FPPassManager::cleanup(), llvm::FPPassManager::doFinalization(), llvm::FPPassManager::doInitialization(), llvm::FPPassManager::dumpPassStructure(), llvm::LPPassManager::dumpPassStructure(), llvm::RGPassManager::dumpPassStructure(), llvm::legacy::FunctionPassManagerImpl::releaseMemoryOnTheFly(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
getOnTheFlyPass()
std::tuple< Pass *, bool > PMDataManager::getOnTheFlyPass (Pass * P, AnalysisID PI, Function & F) virtual
Definition at line 1292 of file LegacyPassManager.cpp.
References llvm_unreachable.
Referenced by llvm::AnalysisResolver::findImplPass().
getPassManagerType()
virtual PassManagerType llvm::PMDataManager::getPassManagerType () const inline virtual
Reimplemented in llvm::FPPassManager, llvm::LPPassManager, and llvm::RGPassManager.
Definition at line 380 of file LegacyPassManagers.h.
References assert(), and llvm::PMT_Unknown.
Referenced by llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), llvm::RegionPass::preparePassManager(), and llvm::PMStack::push().
getTopLevelManager()
PMTopLevelManager * llvm::PMDataManager::getTopLevelManager () inline
Definition at line 361 of file LegacyPassManagers.h.
References TPM.
Referenced by llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::RegionPass::assignPassManager(), and llvm::PMStack::push().
initializeAnalysisImpl()
void PMDataManager::initializeAnalysisImpl (Pass * P)
All Required analyses should be available to the pass as it runs! Here we fill in the AnalysisImpls member of the pass so that it can successfully use the getAnalysis() method to retrieve the implementations it needs.
Definition at line 1115 of file LegacyPassManager.cpp.
References llvm::AnalysisResolver::addAnalysisImplsPair(), assert(), findAnalysisPass(), llvm::PMTopLevelManager::findAnalysisUsage(), llvm::AnalysisUsage::getRequiredSet(), P, and TPM.
Referenced by llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
initializeAnalysisInfo()
void llvm::PMDataManager::initializeAnalysisInfo () inline
Initialize available analysis information.
Definition at line 333 of file LegacyPassManagers.h.
References InheritedAnalysis.
Referenced by PMDataManager(), and llvm::PMStack::pop().
initSizeRemarkInfo()
unsigned PMDataManager::initSizeRemarkInfo (Module & M, StringMap< std::pair< unsigned, unsigned > > & FunctionToInstrCount)
Set the initial size of the module if the user has specified that they want remarks for size.
Returns 0 if the remark was not requested.
Definition at line 65 of file LegacyPassManager.cpp.
References F, and InstrCount.
Referenced by llvm::FPPassManager::runOnFunction(), and llvm::LPPassManager::runOnFunction().
isPassDebuggingExecutionsOrMore()
bool PMDataManager::isPassDebuggingExecutionsOrMore () const protected
isPassDebuggingExecutionsOrMore - Return true if -debug-pass=Executions or higher is specified.
Definition at line 61 of file LegacyPassManager.cpp.
References PassDebugging.
Referenced by llvm::RGPassManager::runOnFunction().
populateInheritedAnalysis()
void llvm::PMDataManager::populateInheritedAnalysis (PMStack & PMS) inline
Definition at line 390 of file LegacyPassManagers.h.
References InheritedAnalysis.
Referenced by llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
preserveHigherLevelAnalysis()
bool PMDataManager::preserveHigherLevelAnalysis (Pass * P)
Definition at line 888 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::findAnalysisUsage(), llvm::AnalysisUsage::getPreservedSet(), llvm::AnalysisUsage::getPreservesAll(), llvm::is_contained(), P, and TPM.
Referenced by llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
recordAvailableAnalysis()
void PMDataManager::recordAvailableAnalysis (Pass * P)
Augment AvailableAnalysis by adding analysis made available by pass P.
Augement AvailableAnalysis by adding analysis made available by pass P.
Definition at line 871 of file LegacyPassManager.cpp.
References assert(), llvm::PMTopLevelManager::findAnalysisPassInfo(), llvm::PassInfo::getInterfacesImplemented(), P, and TPM.
Referenced by add(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
removeDeadPasses()
void PMDataManager::removeDeadPasses (Pass * P, StringRef Msg, enum PassDebuggingString DBG_STR)
Remove dead passes used by P.
Remove analysis passes that are not used any longer.
Definition at line 968 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::collectLastUses(), llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), freePass(), P, PassDebugging, and TPM.
Referenced by llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
removeNotPreservedAnalysis()
void PMDataManager::removeNotPreservedAnalysis (Pass * P)
Remove Analysis that is not preserved by the pass.
Remove Analysis not preserved by Pass P.
Definition at line 922 of file LegacyPassManager.cpp.
References llvm::dbgs(), E, llvm::PMTopLevelManager::findAnalysisUsage(), llvm::Pass::getPassName(), llvm::AnalysisUsage::getPreservedSet(), llvm::AnalysisUsage::getPreservesAll(), I, InheritedAnalysis, llvm::is_contained(), P, PassDebugging, and TPM.
Referenced by add(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
setDepth()
void llvm::PMDataManager::setDepth (unsigned newDepth) inline
Definition at line 365 of file LegacyPassManagers.h.
Referenced by llvm::PMStack::push().
setTopLevelManager()
void llvm::PMDataManager::setTopLevelManager (PMTopLevelManager * T) inline
Definition at line 362 of file LegacyPassManagers.h.
References T, and TPM.
Referenced by llvm::legacy::FunctionPassManager::FunctionPassManager(), llvm::legacy::PassManager::PassManager(), llvm::PMTopLevelManager::PMTopLevelManager(), and llvm::PMStack::push().
verifyPreservedAnalysis()
void PMDataManager::verifyPreservedAnalysis (Pass * P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
verifyPreservedAnalysis – Verify analysis preserved by pass P.
Definition at line 904 of file LegacyPassManager.cpp.
References findAnalysisPass(), llvm::PMTopLevelManager::findAnalysisUsage(), llvm::getPassTimer(), llvm::AnalysisUsage::getPreservedSet(), P, and TPM.
Referenced by llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and llvm::RGPassManager::runOnFunction().
Member Data Documentation
InheritedAnalysis
DenseMap<AnalysisID, Pass *>* llvm::PMDataManager::InheritedAnalysis[PMT_Last] protected
Definition at line 427 of file LegacyPassManagers.h.
Referenced by initializeAnalysisInfo(), populateInheritedAnalysis(), and removeNotPreservedAnalysis().
PassVector
SmallVector<Pass *, 16> llvm::PMDataManager::PassVector protected
Definition at line 422 of file LegacyPassManagers.h.
Referenced by add(), dumpPassArguments(), llvm::FPPassManager::getContainedPass(), llvm::LPPassManager::getContainedPass(), llvm::RGPassManager::getContainedPass(), getNumContainedPasses(), and ~PMDataManager().
TPM
PMTopLevelManager* llvm::PMDataManager::TPM = nullptr protected
Definition at line 419 of file LegacyPassManagers.h.
Referenced by add(), addLowerLevelRequiredPass(), collectRequiredAndUsedAnalyses(), dumpLastUses(), dumpPassArguments(), findAnalysisPass(), freePass(), getTopLevelManager(), initializeAnalysisImpl(), preserveHigherLevelAnalysis(), recordAvailableAnalysis(), removeDeadPasses(), removeNotPreservedAnalysis(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), setTopLevelManager(), and verifyPreservedAnalysis().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManagers.h
lib/IR/LegacyPassManager.cpp