LLVM: llvm::OrderedChangedData< T > Class Template Reference
llvm::OrderedChangedData< T > Class Template Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
std::vector< std::string > & getOrder ()
const std::vector< std::string > & getOrder () const
StringMap< T > & getData ()
const StringMap< T > & getData () const
bool operator== (const OrderedChangedData< T > &That) const
Static Public Member Functions
static void report (const OrderedChangedData &Before, const OrderedChangedData &After, function_ref< void(const T *, const T *)> HandlePair)
Protected Attributes
std::vector< std::string > Order
StringMap< T > Data
Detailed Description
template<typename T>
class llvm::OrderedChangedData< T >
Definition at line 289 of file StandardInstrumentations.h.
Member Function Documentation
getData() [1/2]
template<typename T > StringMap< T > & llvm::OrderedChangedData< T >::getData () inline
Definition at line 296 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< T >::Data.
Referenced by llvm::IRComparer< T >::compare(), llvm::IRComparer< T >::generateFunctionData(), llvm::OrderedChangedData< T >::operator==(), and llvm::OrderedChangedData< T >::report().
getData() [2/2]
template<typename T > const StringMap< T > & llvm::OrderedChangedData< T >::getData () const inline
Definition at line 297 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< T >::Data.
getOrder() [1/2]
template<typename T > std::vector< std::string > & llvm::OrderedChangedData< T >::getOrder () inline
Definition at line 292 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< T >::Order.
Referenced by llvm::IRComparer< T >::generateFunctionData(), and llvm::OrderedChangedData< T >::report().
getOrder() [2/2]
template<typename T > const std::vector< std::string > & llvm::OrderedChangedData< T >::getOrder () const inline
Definition at line 293 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< T >::Order.
operator==()
template<typename T > bool llvm::OrderedChangedData< T >::operator== (const OrderedChangedData< T > & That) const inline
Definition at line 299 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< T >::Data, and llvm::OrderedChangedData< T >::getData().
report()
template<typename T > void OrderedChangedData::report (const OrderedChangedData< T > & Before, const OrderedChangedData< T > & After, function_ref< void(const T *, const T *)> HandlePair) static
Definition at line 571 of file StandardInstrumentations.cpp.
References llvm::OrderedChangedData< T >::getData(), and llvm::OrderedChangedData< T >::getOrder().
Member Data Documentation
Data
template<typename T > StringMap<T> llvm::OrderedChangedData< T >::Data protected
Definition at line 314 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< T >::getData(), llvm::OrderedChangedData< T >::getData(), and llvm::OrderedChangedData< T >::operator==().
Order
template<typename T > std::vector<std::string> llvm::OrderedChangedData< T >::Order protected
Definition at line 313 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< T >::getOrder(), and llvm::OrderedChangedData< T >::getOrder().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp