LLVM: llvm::AddressRanges Class Reference
llvm::AddressRanges Class Reference
The AddressRanges class helps normalize address range collections.
#include "llvm/ADT/AddressRanges.h"
Public Member Functions
void clear ()
bool empty () const
bool contains (uint64_t Addr) const
bool contains (AddressRange Range) const
Optional< AddressRange > getRangeThatContains (uint64_t Addr) const
Collection::const_iterator insert (AddressRange Range)
void reserve (size_t Capacity)
size_t size () const
bool operator== (const AddressRanges &RHS) const
const AddressRange & operator[] (size_t i) const
Collection::const_iterator begin () const
Collection::const_iterator end () const
Protected Types
using Collection = SmallVector<AddressRange>
Protected Member Functions
Collection::const_iterator find (uint64_t Addr) const
Collection::const_iterator find (AddressRange Range) const
Protected Attributes
Collection Ranges
Detailed Description
The AddressRanges class helps normalize address range collections.
This class keeps a sorted vector of AddressRange objects and can perform insertions and searches efficiently. The address ranges are always sorted and never contain any invalid or empty address ranges. Intersecting([100,200), [150,300)) and adjacent([100,200), [200,300)) address ranges are combined during insertion.
Definition at line 54 of file AddressRanges.h.
Member Typedef Documentation
Collection
using llvm::AddressRanges::Collection = SmallVector<AddressRange> protected
Definition at line 56 of file AddressRanges.h.
Member Function Documentation
begin()
Collection::const_iterator llvm::AddressRanges::begin () const inline
Definition at line 83 of file AddressRanges.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and Ranges.
clear()
void llvm::AddressRanges::clear () inline
Definition at line 60 of file AddressRanges.h.
References llvm::SmallVectorImpl< T >::clear(), and Ranges.
Referenced by llvm::gsym::InlineInfo::clear(), and llvm::gsym::decodeRanges().
contains() [1/2]
bool llvm::AddressRanges::contains (AddressRange Range) const inline
Definition at line 63 of file AddressRanges.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), find(), and Ranges.
contains() [2/2]
bool llvm::AddressRanges::contains (uint64_t Addr) const inline
Definition at line 62 of file AddressRanges.h.
References Addr, llvm::SmallVectorTemplateCommon< T, typename >::end(), find(), and Ranges.
Referenced by llvm::AddressRangesMap< T >::contains(), llvm::AddressRangesMap< T >::contains(), llvm::gsym::InlineInfo::encode(), getInlineStackHelper(), and llvm::gsym::GsymCreator::hasFunctionInfoForAddress().
empty()
bool llvm::AddressRanges::empty () const inline
Definition at line 61 of file AddressRanges.h.
References llvm::SmallVectorBase< Size_T >::empty(), and Ranges.
Referenced by llvm::AddressRangesMap< T >::empty(), llvm::gsym::encodeRanges(), llvm::gsym::InlineInfo::isValid(), and parseInlineInfo().
end()
Collection::const_iterator llvm::AddressRanges::end () const inline
Definition at line 84 of file AddressRanges.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and Ranges.
find() [1/2]
AddressRanges::Collection::const_iterator AddressRanges::find (AddressRange Range) const protected
Definition at line 54 of file AddressRanges.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::AddressRange::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), Ranges, and llvm::AddressRange::size().
find() [2/2]
AddressRanges::Collection::const_iterator AddressRanges::find (uint64_t Addr) const protected
Definition at line 38 of file AddressRanges.cpp.
References Addr, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and Ranges.
Referenced by contains(), contains(), getRangeThatContains(), and llvm::AddressRangesMap< T >::getRangeValueThatContains().
getRangeThatContains()
Optional< AddressRange > llvm::AddressRanges::getRangeThatContains (uint64_t Addr) const inline
Definition at line 66 of file AddressRanges.h.
References Addr, llvm::SmallVectorTemplateCommon< T, typename >::end(), find(), llvm::None, and Ranges.
insert()
AddressRanges::Collection::const_iterator AddressRanges::insert (AddressRange Range)
Definition at line 16 of file AddressRanges.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::AddressRange::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SmallVectorImpl< T >::insert(), Ranges, llvm::AddressRange::size(), llvm::AddressRange::start(), and llvm::upper_bound().
Referenced by llvm::gsym::GsymCreator::addFunctionInfo(), llvm::gsym::decodeRanges(), llvm::AddressRangesMap< T >::insert(), and parseInlineInfo().
operator==()
bool llvm::AddressRanges::operator== (const AddressRanges & RHS) const inline
Definition at line 76 of file AddressRanges.h.
References Ranges.
operator[]()
const AddressRange & llvm::AddressRanges::operator[] (size_t i) const inline
Definition at line 79 of file AddressRanges.h.
References assert(), Ranges, and llvm::SmallVectorBase< Size_T >::size().
reserve()
void llvm::AddressRanges::reserve (size_t Capacity) inline
Definition at line 74 of file AddressRanges.h.
References Ranges, and llvm::SmallVectorImpl< T >::reserve().
Referenced by llvm::gsym::decodeRanges().
size()
size_t llvm::AddressRanges::size () const inline
Definition at line 75 of file AddressRanges.h.
References Ranges, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::gsym::encodeRanges(), llvm::operator<<(), and llvm::AddressRangesMap< T >::size().
Member Data Documentation
Ranges
Collection llvm::AddressRanges::Ranges protected
Definition at line 57 of file AddressRanges.h.
Referenced by begin(), clear(), llvm::AddressRangesMap< T >::clear(), contains(), contains(), empty(), end(), find(), find(), getRangeThatContains(), llvm::AddressRangesMap< T >::getRangeValueThatContains(), insert(), llvm::AddressRangesMap< T >::insert(), operator==(), operator[](), llvm::AddressRangesMap< T >::operator[](), reserve(), size(), and llvm::AddressRangesMap< T >::size().
The documentation for this class was generated from the following files:
include/llvm/ADT/AddressRanges.h
lib/Support/AddressRanges.cpp