LLVM: llvm::cl::bits< DataType, Storage, ParserClass > Class Template Reference
llvm::cl::bits< DataType, Storage, ParserClass > Class Template Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
bits (const bits &)=delete
bits & operator= (const bits &)=delete
ParserClass & getParser ()
unsigned getPosition (unsigned optnum) const
template<class... Mods>
bits (const Mods &... Ms)
void setCallback (std::function< void(const typename ParserClass::parser_data_type &)> CB)
Public Member Functions inherited from llvm::cl::Option
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
bool isPositional () const
bool isSink () const
bool isDefaultOption () const
bool isConsumeAfter () const
bool isInAllSubCommands () const
void setArgStr (StringRef S)
void setDescription (StringRef S)
void setValueStr (StringRef S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void addCategory (OptionCategory &C)
void addSubCommand (SubCommand &S)
virtual ~Option ()=default
void addArgument ()
void removeArgument ()
Unregisters this option from the CommandLine system.
virtual bool addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
bool error (const Twine &Message, StringRef ArgName=StringRef(), raw_ostream &Errs=llvm::errs())
bool error (const Twine &Message, raw_ostream &Errs)
int getNumOccurrences () const
void reset ()
Public Member Functions inherited from llvm::cl::bits_storage< DataType, bool >
template<class T >
void addValue (const T &V)
unsigned getBits ()
void clear ()
template<class T >
bool isSet (const T &V)
Public Attributes
std::function< void(const typename ParserClass::parser_data_type &)> Callback
Public Attributes inherited from llvm::cl::Option
StringRef ArgStr
StringRef HelpStr
StringRef ValueStr
SmallVector< OptionCategory *, 1 > Categories
SmallPtrSet< SubCommand *, 1 > Subs
Additional Inherited Members
Static Public Member Functions inherited from llvm::cl::Option
static void printHelpStr (StringRef HelpStr, size_t Indent, size_t FirstLineIndentedBy)
static void printEnumValHelpStr (StringRef HelpStr, size_t Indent, size_t FirstLineIndentedBy)
Protected Member Functions inherited from llvm::cl::Option
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Detailed Description
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>>
class llvm::cl::bits< DataType, Storage, ParserClass >
Definition at line 1762 of file CommandLine.h.
Constructor & Destructor Documentation
bits() [1/2]
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const bits< DataType, Storage, ParserClass > &) delete
bits() [2/2]
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> template<class... Mods> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const Mods &... Ms) inline explicit
Definition at line 1820 of file CommandLine.h.
References llvm::cl::apply().
Member Function Documentation
getParser()
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> ParserClass & llvm::cl::bits< DataType, Storage, ParserClass >::getParser () inline
Definition at line 1812 of file CommandLine.h.
getPosition()
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> unsigned llvm::cl::bits< DataType, Storage, ParserClass >::getPosition (unsigned optnum) const inline
Definition at line 1814 of file CommandLine.h.
References assert(), and size().
operator=()
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> bits & llvm::cl::bits< DataType, Storage, ParserClass >::operator= (const bits< DataType, Storage, ParserClass > &) delete
setCallback()
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> void llvm::cl::bits< DataType, Storage, ParserClass >::setCallback (std::function< void(const typename ParserClass::parser_data_type &)> CB) inline
Definition at line 1826 of file CommandLine.h.
References llvm::cl::bits< DataType, Storage, ParserClass >::Callback.
Member Data Documentation
Callback
template<class DataType , class Storage = bool, class ParserClass = parser<DataType>> std::function<void(const typename ParserClass::parser_data_type &)> llvm::cl::bits< DataType, Storage, ParserClass >::Callback
Initial value:
=
      [](const typename ParserClass::parser_data_type &) {}
Definition at line 1831 of file CommandLine.h.
Referenced by llvm::cl::bits< DataType, Storage, ParserClass >::setCallback().
The documentation for this class was generated from the following file:
include/llvm/Support/CommandLine.h