LLVM: llvm::StringMapEntry< T > Class Template Reference
llvm::StringMapEntry< T > Class Template Reference
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
#include "llvm/ADT/StringMapEntry.h"
Public Member Functions
StringRef getKey () const
const char * getKeyData () const
getKeyData - Return the start of the string data that is the key for this value.
StringRef first () const
template<typename AllocatorTy >
void Destroy (AllocatorTy &allocator)
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
Public Member Functions inherited from llvm::StringMapEntryStorage< ValueTy >
StringMapEntryStorage (size_t keyLength)
template<typename... InitTy>
StringMapEntryStorage (size_t keyLength, InitTy &&... initVals)
StringMapEntryStorage (StringMapEntryStorage &e)=delete
const ValueTy & getValue () const
ValueTy & getValue ()
void setValue (const ValueTy &V)
Public Member Functions inherited from llvm::StringMapEntryBase
StringMapEntryBase (size_t keyLength)
size_t getKeyLength () const
Static Public Member Functions
template<typename AllocatorTy , typename... InitTy>
static StringMapEntry * Create (StringRef key, AllocatorTy &allocator, InitTy &&... initVals)
Create a StringMapEntry for the specified key construct the value using InitiVals.
static StringMapEntry & GetStringMapEntryFromKeyData (const char *keyData)
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Additional Inherited Members
Public Attributes inherited from llvm::StringMapEntryStorage< ValueTy >
ValueTy second
Static Protected Member Functions inherited from llvm::StringMapEntryBase
template<typename AllocatorTy >
static void * allocateWithKey (size_t EntrySize, size_t EntryAlign, StringRef Key, AllocatorTy &Allocator)
Helper to tail-allocate Key.
Detailed Description
template<typename T>
class llvm::StringMapEntry< T >
StringMapEntry - This is used to represent one value that is inserted into a StringMap.
It contains the Value itself and the key: the string length and data.
Definition at line 71 of file LLVMContextImpl.h.
Member Function Documentation
Create()
template<typename T > template<typename AllocatorTy , typename... InitTy> static StringMapEntry * llvm::StringMapEntry< T >::Create (StringRef key, AllocatorTy & allocator, InitTy &&... initVals) inline static
Create a StringMapEntry for the specified key construct the value using InitiVals.
Definition at line 123 of file StringMapEntry.h.
References llvm::StringMapEntryBase::allocateWithKey(), allocator, and llvm::StringRef::size().
Referenced by llvm::StringMap< ValueTy, AllocatorTy >::StringMap(), and llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
Destroy()
template<typename T > template<typename AllocatorTy > void llvm::StringMapEntry< T >::Destroy (AllocatorTy & allocator) inline
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
Definition at line 139 of file StringMapEntry.h.
References allocator, and llvm::StringMapEntryBase::getKeyLength().
first()
template<typename T > StringRef llvm::StringMapEntry< T >::first () const inline
Definition at line 116 of file StringMapEntry.h.
References llvm::StringMapEntry< T >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
Referenced by llvm::orc::SymbolStringPtr::operator*().
getKey()
template<typename T > StringRef llvm::StringMapEntry< T >::getKey () const inline
Definition at line 105 of file StringMapEntry.h.
References llvm::StringMapEntry< T >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
Referenced by llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::getKnowledgeFromBundle(), llvm::Value::getName(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), and llvm::StringSet< AllocatorTy >::insert().
getKeyData()
template<typename T > const char * llvm::StringMapEntry< T >::getKeyData () const inline
getKeyData - Return the start of the string data that is the key for this value.
The string data is always stored immediately after the StringMapEntry object.
Definition at line 112 of file StringMapEntry.h.
Referenced by llvm::StringMapEntry< T >::first(), llvm::TargetIntrinsicInfo::getIntrinsicID(), and llvm::StringMapEntry< T >::getKey().
GetStringMapEntryFromKeyData()
template<typename T > static StringMapEntry & llvm::StringMapEntry< T >::GetStringMapEntryFromKeyData (const char * keyData) inline static
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Definition at line 132 of file StringMapEntry.h.
The documentation for this class was generated from the following files:
include/llvm/ADT/StringMapEntry.h
include/llvm/IR/Comdat.h
include/llvm/IR/LLVMContext.h
include/llvm/IR/Metadata.h
include/llvm/IR/Value.h
lib/IR/LLVMContextImpl.h