LLVM: lib/Object/COFFObjectFile.cpp File Reference
COFFObjectFile.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBufferRef.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstddef>
#include <cstring>
#include <limits>
#include <memory>
#include <system_error>
Macros
#define LLVM_COFF_SWITCH_RELOC_TYPE_NAME(reloc_type)
#define RETURN_IF_ERROR(Expr)
Functions
static bool checkSize (MemoryBufferRef M, std::error_code &EC, uint64_t Size)
template<typename T >
static Error getObject (const T *&Obj, MemoryBufferRef M, const void *Ptr, const uint64_t Size=sizeof(T))
static bool decodeBase64StringEntry (StringRef Str, uint32_t &Result)
static uint32_t getNumberOfRelocations (const coff_section *Sec, MemoryBufferRef M, const uint8_t *base)
static const coff_relocation * getFirstReloc (const coff_section *Sec, MemoryBufferRef M, const uint8_t *Base)
static Error ignoreStrippedErrors (Error E)
static imported_symbol_iterator makeImportedSymbolIterator (const COFFObjectFile *Object, uintptr_t Ptr, int Index)
static imported_symbol_iterator importedSymbolBegin (uint32_t RVA, const COFFObjectFile *Object)
static imported_symbol_iterator importedSymbolEnd (uint32_t RVA, const COFFObjectFile *Object)
Macro Definition Documentation
LLVM_COFF_SWITCH_RELOC_TYPE_NAME
#define LLVM_COFF_SWITCH_RELOC_TYPE_NAME (reloc_type)
Value:
  case COFF::reloc_type:                                                       \
    return #reloc_type;
Definition at line 1264 of file COFFObjectFile.cpp.
Referenced by llvm::object::COFFObjectFile::getRelocationTypeName().
RETURN_IF_ERROR
#define RETURN_IF_ERROR (Expr)
Value:
  do {                                                                         \
    Error E = (Expr);                                                          \
    if (E)                                                                     \
      return std::move(E);                                                     \
  } while (0)
Definition at line 1752 of file COFFObjectFile.cpp.
Referenced by llvm::object::ResourceEntryRef::moveNext(), llvm::object::WindowsResourceParser::parse(), and llvm::object::readStringOrId().
Function Documentation
checkSize()
static bool checkSize (MemoryBufferRef M, std::error_code & EC, uint64_t Size) static
Definition at line 47 of file COFFObjectFile.cpp.
References Size.
decodeBase64StringEntry()
static bool decodeBase64StringEntry (StringRef Str, uint32_t & Result) static
Definition at line 69 of file COFFObjectFile.cpp.
References assert(), and llvm::Value.
Referenced by llvm::object::COFFObjectFile::getSectionName().
getFirstReloc()
static const coff_relocation * getFirstReloc (const coff_section * Sec, MemoryBufferRef M, const uint8_t * Base) static
Definition at line 377 of file COFFObjectFile.cpp.
References llvm::sampleprof::Base, llvm::object::Binary::checkOffset(), llvm::consumeError(), E, getNumberOfRelocations(), llvm::object::coff_section::hasExtendedRelocations(), and llvm::object::coff_section::PointerToRelocations.
Referenced by llvm::object::COFFObjectFile::getRelocations(), llvm::object::COFFObjectFile::section_rel_begin(), and llvm::object::COFFObjectFile::section_rel_end().
getNumberOfRelocations()
static uint32_t getNumberOfRelocations (const coff_section * Sec, MemoryBufferRef M, const uint8_t * base) static
Definition at line 356 of file COFFObjectFile.cpp.
References llvm::consumeError(), E, llvm::object::getObject(), llvm::object::coff_section::hasExtendedRelocations(), llvm::object::coff_section::NumberOfRelocations, llvm::object::coff_section::PointerToRelocations, and llvm::object::coff_relocation::VirtualAddress.
Referenced by getFirstReloc(), llvm::object::COFFObjectFile::getRelocations(), and llvm::object::COFFObjectFile::section_rel_end().
getObject()
template<typename T > static Error getObject (const T *& Obj, MemoryBufferRef M, const void * Ptr, const uint64_t Size = sizeof(T)) static
Definition at line 58 of file COFFObjectFile.cpp.
References Addr, llvm::object::Binary::checkOffset(), E, Size, and llvm::Error::success().
ignoreStrippedErrors()
static Error ignoreStrippedErrors (Error E) static
Definition at line 778 of file COFFObjectFile.cpp.
References llvm::consumeError(), E, and llvm::Error::success().
importedSymbolBegin()
static imported_symbol_iterator importedSymbolBegin (uint32_t RVA, const COFFObjectFile * Object) static
Definition at line 1411 of file COFFObjectFile.cpp.
References llvm::cantFail(), makeImportedSymbolIterator(), and llvm::Object.
Referenced by llvm::object::DelayImportDirectoryEntryRef::imported_symbol_begin(), llvm::object::ImportDirectoryEntryRef::imported_symbol_begin(), and llvm::object::ImportDirectoryEntryRef::lookup_table_begin().
importedSymbolEnd()
static imported_symbol_iterator importedSymbolEnd (uint32_t RVA, const COFFObjectFile * Object) static
Definition at line 1419 of file COFFObjectFile.cpp.
References llvm::cantFail(), makeImportedSymbolIterator(), and llvm::Object.
Referenced by llvm::object::DelayImportDirectoryEntryRef::imported_symbol_end(), llvm::object::ImportDirectoryEntryRef::imported_symbol_end(), and llvm::object::ImportDirectoryEntryRef::lookup_table_end().
makeImportedSymbolIterator()
static imported_symbol_iterator makeImportedSymbolIterator (const COFFObjectFile * Object, uintptr_t Ptr, int Index) static
Definition at line 1400 of file COFFObjectFile.cpp.
References llvm::Object, and P.
Referenced by importedSymbolBegin(), and importedSymbolEnd().