LLVM: lib/Transforms/Coroutines/CoroFrame.cpp File Reference
CoroFrame.cpp File Reference
#include "CoroInternal.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Analysis/PtrUseVisitor.h"
#include "llvm/Analysis/StackLifetime.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/OptimizedStructLayout.h"
#include "llvm/Support/circular_raw_ostream.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/PromoteMemToReg.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "coro-suspend-crossing"
#define DEBUG_TYPE "coro-frame"
Typedefs
typedef SmallPtrSet< BasicBlock *, 8 > VisitedBlocksSet
Enumerations
enum { SmallVectorThreshold = 32 }
Functions
static void dumpSpills (StringRef Title, const SpillInfo &Spills)
static void dumpAllocas (const SmallVectorImpl< AllocaInfo > &Allocas)
static void cacheDIVar (FrameDataInfo &FrameData, DenseMap< Value *, DILocalVariable * > &DIVarCache)
static StringRef solveTypeName (Type *Ty)
Create name for Type.
static DIType * solveDIType (DIBuilder &Builder, Type *Ty, const DataLayout &Layout, DIScope *Scope, unsigned LineNum, DenseMap< Type *, DIType * > &DITypeCache)
static void buildFrameDebugInfo (Function &F, coro::Shape &Shape, FrameDataInfo &FrameData)
Build artificial debug info for C++ coroutine frames to allow users to inspect the contents of the frame directly.
static StructType * buildFrameType (Function &F, coro::Shape &Shape, FrameDataInfo &FrameData)
static Instruction * splitBeforeCatchSwitch (CatchSwitchInst *CatchSwitch)
static void createFramePtr (coro::Shape &Shape)
static void insertSpills (const FrameDataInfo &FrameData, coro::Shape &Shape)
static void movePHIValuesToInsertedBlock (BasicBlock *SuccBB, BasicBlock *InsertedBB, BasicBlock *PredBB, PHINode *UntilPHI=nullptr)
static void rewritePHIsForCleanupPad (BasicBlock *CleanupPadBB, CleanupPadInst *CleanupPad)
static void cleanupSinglePredPHIs (Function &F)
static void rewritePHIs (BasicBlock &BB)
static void rewritePHIs (Function &F)
static bool materializable (Instruction &V)
static bool isCoroutineStructureIntrinsic (Instruction &I)
static void rewriteMaterializableInstructions (IRBuilder<> &IRB, const SpillInfo &Spills)
static BasicBlock * splitBlockIfNotFirst (Instruction *I, const Twine &Name)
static void splitAround (Instruction *I, const Twine &Name)
static bool isSuspendBlock (BasicBlock *BB)
static bool isSuspendReachableFrom (BasicBlock *From, VisitedBlocksSet &VisitedOrFreeBBs)
Does control flow starting at the given block ever reach a suspend instruction before reaching a block in VisitedOrFreeBBs?
static bool isLocalAlloca (CoroAllocaAllocInst *AI)
Is the given alloca "local", i.e.
static bool willLeaveFunctionImmediatelyAfter (BasicBlock *BB, unsigned depth=3)
After we split the coroutine, will the given basic block be along an obvious exit path for the resumption function?
static bool localAllocaNeedsStackSave (CoroAllocaAllocInst *AI)
static void lowerLocalAllocas (ArrayRef< CoroAllocaAllocInst * > LocalAllocas, SmallVectorImpl< Instruction * > &DeadInsts)
Turn each of the given local allocas into a normal (dynamic) alloca instruction.
static Instruction * lowerNonLocalAlloca (CoroAllocaAllocInst *AI, coro::Shape &Shape, SmallVectorImpl< Instruction * > &DeadInsts)
Turn the given coro.alloca.alloc call into a dynamic allocation.
static Value * emitGetSwiftErrorValue (IRBuilder<> &Builder, Type *ValueTy, coro::Shape &Shape)
Get the current swifterror value.
static Value * emitSetSwiftErrorValue (IRBuilder<> &Builder, Value *V, coro::Shape &Shape)
Set the given value as the current swifterror value.
static Value * emitSetAndGetSwiftErrorValueAround (Instruction *Call, AllocaInst *Alloca, coro::Shape &Shape)
Set the swifterror value from the given alloca before a call, then put in back in the alloca afterwards.
static void eliminateSwiftErrorAlloca (Function &F, AllocaInst *Alloca, coro::Shape &Shape)
Eliminate a formerly-swifterror alloca by inserting the get/set intrinsics and attempting to MemToReg the alloca away.
static void eliminateSwiftErrorArgument (Function &F, Argument &Arg, coro::Shape &Shape, SmallVectorImpl< AllocaInst * > &AllocasToPromote)
"Eliminate" a swifterror argument by reducing it to the alloca case and then loading and storing in the prologue and epilog.
static void eliminateSwiftError (Function &F, coro::Shape &Shape)
Eliminate all problematic uses of swifterror arguments and allocas from the function.
static void sinkSpillUsesAfterCoroBegin (Function &F, const FrameDataInfo &FrameData, CoroBeginInst *CoroBegin)
retcon and retcon.once conventions assume that all spill uses can be sunk after the coro.begin intrinsic.
static void sinkLifetimeStartMarkers (Function &F, coro::Shape &Shape, SuspendCrossingInfo &Checker)
For each local variable that all of its user are only used inside one of suspended region, we sink their lifetime.start markers to the place where after the suspend block.
static void collectFrameAllocas (Function &F, coro::Shape &Shape, const SuspendCrossingInfo &Checker, SmallVectorImpl< AllocaInfo > &Allocas)
Macro Definition Documentation
DEBUG_TYPE [1/2]
#define DEBUG_TYPE "coro-suspend-crossing"
Definition at line 45 of file CoroFrame.cpp.
DEBUG_TYPE [2/2]
#define DEBUG_TYPE "coro-frame"
Definition at line 45 of file CoroFrame.cpp.
Typedef Documentation
VisitedBlocksSet
typedef SmallPtrSet<BasicBlock*, 8> VisitedBlocksSet
Definition at line 2085 of file CoroFrame.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SmallVectorThreshold
Definition at line 47 of file CoroFrame.cpp.
Function Documentation
buildFrameDebugInfo()
static void buildFrameDebugInfo (Function & F, coro::Shape & Shape, FrameDataInfo & FrameData) static
Build artificial debug info for C++ coroutine frames to allow users to inspect the contents of the frame directly.
Create Debug information for coroutine frame with debug name "__coro_frame". The debug information for the fields of coroutine frame is constructed from the following way:
For all the value in the Frame, we search the use of dbg.declare to find the corresponding debug variables for the value. If we can find the debug variable, we can get full and accurate debug information.
If we can't get debug information in step 1 and 2, we could only try to build the DIType by Type. We did this in solveDIType. We only handle integer, float, double, integer type and struct type for now.
FIXME: If we fill the field SizeInBits with the actual size of __coro_index in bits, then __coro_index wouldn't show in the debugger.
Definition at line 950 of file CoroFrame.cpp.
References llvm::coro::Shape::ABI, assert(), cacheDIVar(), llvm::DIBuilder::createAutoVariable(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createExpression(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createStructType(), llvm::coro::Shape::SwitchFieldIndex::Destroy, llvm::dyn_cast(), llvm::TinyPtrVector< EltTy >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::FindDbgDeclareUses(), llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameSize, llvm::coro::Shape::FrameTy, llvm::TinyPtrVector< EltTy >::front(), llvm::DebugLoc::get(), llvm::MDTuple::get(), llvm::Instruction::getDebugLoc(), llvm::StructType::getElementType(), llvm::DIScope::getFile(), llvm::TypeSize::getFixedSize(), llvm::coro::Shape::getInsertPtAfterFramePtr(), llvm::DIVariable::getLine(), llvm::DIType::getName(), llvm::StructType::getNumElements(), llvm::DIBuilder::getOrCreateArray(), llvm::coro::Shape::getPromiseAlloca(), llvm::DILocalVariable::getScope(), llvm::DILocalScope::getSubprogram(), llvm::DataLayout::getTypeSizeInBits(), llvm::DbgVariableIntrinsic::getVariable(), llvm::coro::Shape::SwitchLoweringStorage::IndexAlign, llvm::coro::Shape::SwitchLoweringStorage::IndexField, llvm::coro::Shape::SwitchLoweringStorage::IndexOffset, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::dwarf::isCPlusPlus(), Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DIBuilder::replaceArrays(), llvm::coro::Shape::SwitchFieldIndex::Resume, solveDIType(), llvm::StringRef::str(), llvm::Twine::str(), llvm::coro::Shape::SwitchLowering, and llvm::Align::value().
Referenced by llvm::coro::buildCoroutineFrame().
buildFrameType()
static StructType * buildFrameType (Function & F, coro::Shape & Shape, FrameDataInfo & FrameData) static
Definition at line 1123 of file CoroFrame.cpp.
References A, llvm::coro::Shape::ABI, llvm::alignTo(), assert(), llvm::coro::Shape::AsyncLowering, B, llvm::CallingConv::C, llvm::coro::Shape::AsyncLoweringStorage::ContextHeaderSize, llvm::coro::Shape::AsyncLoweringStorage::ContextSize, llvm::coro::Shape::CoroSuspends, llvm::StructType::create(), DL, llvm::dyn_cast(), F, llvm::coro::Shape::FrameAlign, llvm::coro::Shape::AsyncLoweringStorage::FrameOffset, llvm::coro::Shape::FrameSize, llvm::coro::Shape::AsyncLoweringStorage::getContextAlignment(), llvm::MachineFunction::getDataLayout(), llvm::MachineBasicBlock::getParent(), llvm::Type::getPointerTo(), llvm::coro::Shape::getPromiseAlloca(), llvm::coro::Shape::getRetconCoroId(), llvm::coro::Shape::SwitchLoweringStorage::IndexAlign, llvm::coro::Shape::SwitchLoweringStorage::IndexField, llvm::coro::Shape::SwitchLoweringStorage::IndexOffset, llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::Log2_64_Ceil(), Name, llvm::None, llvm::report_fatal_error(), llvm::coro::Shape::RetconLowering, and llvm::coro::Shape::SwitchLowering.
Referenced by llvm::coro::buildCoroutineFrame().
cacheDIVar()
static void cacheDIVar (FrameDataInfo & FrameData, DenseMap< Value *, DILocalVariable * > & DIVarCache) static
Definition at line 799 of file CoroFrame.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::find_if(), llvm::FindDbgDeclareUses(), llvm::DbgVariableIntrinsic::getExpression(), llvm::DIExpression::getNumElements(), I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by buildFrameDebugInfo().
cleanupSinglePredPHIs()
static void cleanupSinglePredPHIs (Function & F) static
Definition at line 1910 of file CoroFrame.cpp.
References llvm::SmallVectorBase< Size_T >::empty(), F, llvm::BasicBlock::phis(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::coro::buildCoroutineFrame().
collectFrameAllocas()
static void collectFrameAllocas (Function & F, coro::Shape & Shape, const SuspendCrossingInfo & Checker, SmallVectorImpl< AllocaInfo > & Allocas) static
Definition at line 2526 of file CoroFrame.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroBegin, llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), F, I, instructions, llvm::coro::Shape::SwitchLoweringStorage::PromiseAlloca, and llvm::coro::Shape::SwitchLowering.
Referenced by llvm::coro::buildCoroutineFrame().
createFramePtr()
static void createFramePtr (coro::Shape & Shape) static
Definition at line 1520 of file CoroFrame.cpp.
References Builder, llvm::cast(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::Type::getPointerTo().
Referenced by llvm::coro::buildCoroutineFrame().
dumpAllocas()
static void dumpAllocas (const SmallVectorImpl< AllocaInfo > & Allocas) static
Definition at line 408 of file CoroFrame.cpp.
References A, and llvm::dbgs().
Referenced by llvm::coro::buildCoroutineFrame().
dumpSpills()
static void dumpSpills (StringRef Title, const SpillInfo & Spills) static
Definition at line 398 of file CoroFrame.cpp.
References llvm::dbgs(), E, and I.
Referenced by llvm::coro::buildCoroutineFrame().
eliminateSwiftError()
static void eliminateSwiftError (Function & F, coro::Shape & Shape) static
Eliminate all problematic uses of swifterror arguments and allocas from the function.
We'll fix them up later when splitting the function.
Definition at line 2361 of file CoroFrame.cpp.
References Arg, llvm::dyn_cast(), eliminateSwiftErrorAlloca(), eliminateSwiftErrorArgument(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::AllocaInst::isSwiftError(), llvm::PromoteMemToReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::AllocaInst::setSwiftError().
Referenced by llvm::coro::buildCoroutineFrame().
eliminateSwiftErrorAlloca()
static void eliminateSwiftErrorAlloca (Function & F, AllocaInst * Alloca, coro::Shape & Shape) static
Eliminate a formerly-swifterror alloca by inserting the get/set intrinsics and attempting to MemToReg the alloca away.
Definition at line 2295 of file CoroFrame.cpp.
References Addr, assert(), Call, llvm::cast(), emitSetAndGetSwiftErrorValueAround(), llvm::Use::getUser(), llvm::isa(), llvm::isAllocaPromotable(), llvm::make_early_inc_range(), llvm::Use::set(), and llvm::Value::uses().
Referenced by eliminateSwiftError(), and eliminateSwiftErrorArgument().
eliminateSwiftErrorArgument()
static void eliminateSwiftErrorArgument (Function & F, Argument & Arg, coro::Shape & Shape, SmallVectorImpl< AllocaInst * > & AllocasToPromote) static
"Eliminate" a swifterror argument by reducing it to the alloca case and then loading and storing in the prologue and epilog.
The argument keeps the swifterror flag.
Definition at line 2321 of file CoroFrame.cpp.
References Arg, Builder, llvm::cast(), llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, eliminateSwiftErrorAlloca(), emitSetAndGetSwiftErrorValueAround(), emitSetSwiftErrorValue(), F, llvm::Constant::getNullValue(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by eliminateSwiftError().
emitGetSwiftErrorValue()
static Value * emitGetSwiftErrorValue (IRBuilder<> & Builder, Type * ValueTy, coro::Shape & Shape) static
Get the current swifterror value.
Definition at line 2232 of file CoroFrame.cpp.
References Call, llvm::ConstantPointerNull::get(), and llvm::coro::Shape::SwiftErrorOps.
Referenced by emitSetAndGetSwiftErrorValueAround().
emitSetAndGetSwiftErrorValueAround()
static Value * emitSetAndGetSwiftErrorValueAround (Instruction * Call, AllocaInst * Alloca, coro::Shape & Shape) static
Set the swifterror value from the given alloca before a call, then put in back in the alloca afterwards.
Returns an address that will stand in for the swifterror slot until splitting.
Definition at line 2265 of file CoroFrame.cpp.
References Addr, Builder, Call, llvm::cast(), emitGetSwiftErrorValue(), emitSetSwiftErrorValue(), llvm::AllocaInst::getAllocatedType(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::isa().
Referenced by eliminateSwiftErrorAlloca(), and eliminateSwiftErrorArgument().
emitSetSwiftErrorValue()
static Value * emitSetSwiftErrorValue (IRBuilder<> & Builder, Value * V, coro::Shape & Shape) static
Set the given value as the current swifterror value.
Returns a slot that can be used as a swifterror slot.
Definition at line 2247 of file CoroFrame.cpp.
References Call, llvm::ConstantPointerNull::get(), and llvm::coro::Shape::SwiftErrorOps.
Referenced by eliminateSwiftErrorArgument(), and emitSetAndGetSwiftErrorValueAround().
insertSpills()
static void insertSpills (const FrameDataInfo & FrameData, coro::Shape & Shape) static
Definition at line 1551 of file CoroFrame.cpp.
References A, llvm::coro::Shape::ABI, Align, llvm::coro::Shape::AllocaSpillBlock, Arg, assert(), Builder, llvm::CallingConv::C, llvm::cast(), llvm::SmallVectorImpl< T >::clear(), llvm::coro::Shape::CoroBegin, llvm::Count, llvm::DominatorTree::dominates(), llvm::dyn_cast(), E, llvm::SmallVectorBase< Size_T >::empty(), llvm::Instruction::eraseFromParent(), llvm::FindDbgDeclareUses(), llvm::findDbgUsers(), FramePtr, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::BasicBlock::front(), G, GEP, llvm::ConstantInt::get(), llvm::IntegerType::get(), llvm::AllocaInst::getAlign(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::StructType::getElementType(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHI(), llvm::Instruction::getFunction(), llvm::coro::Shape::getInsertPtAfterFramePtr(), llvm::DataLayout::getIntPtrType(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getSingleSuccessor(), llvm::BasicBlock::getTerminator(), llvm::AllocaInst::getType(), I, llvm::isa(), llvm::AllocaInst::isArrayAllocation(), llvm::coro::Shape::OptimizeFrame, P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::report_fatal_error(), llvm::coro::salvageDebugInfo(), llvm::BasicBlock::splitBasicBlock(), splitBeforeCatchSwitch(), llvm::SplitEdge(), llvm::Value::users(), and llvm::Align::value().
Referenced by llvm::coro::buildCoroutineFrame().
isCoroutineStructureIntrinsic()
static bool isCoroutineStructureIntrinsic (Instruction & I) static
Definition at line 2018 of file CoroFrame.cpp.
References I, and llvm::isa().
Referenced by llvm::coro::buildCoroutineFrame().
isLocalAlloca()
static bool isLocalAlloca (CoroAllocaAllocInst * AI) static
Is the given alloca "local", i.e.
bounded in lifetime to not cross a suspend point?
Definition at line 2112 of file CoroFrame.cpp.
References llvm::dyn_cast(), llvm::Instruction::getParent(), llvm::SmallPtrSetImpl< PtrType >::insert(), isSuspendReachableFrom(), and llvm::Value::users().
Referenced by llvm::coro::buildCoroutineFrame().
isSuspendBlock()
static bool isSuspendBlock (BasicBlock * BB) static
Definition at line 2081 of file CoroFrame.cpp.
References llvm::BasicBlock::front(), and llvm::isa().
Referenced by isSuspendReachableFrom(), sinkLifetimeStartMarkers(), and willLeaveFunctionImmediatelyAfter().
isSuspendReachableFrom()
static bool isSuspendReachableFrom (BasicBlock * From, VisitedBlocksSet & VisitedOrFreeBBs) static
Does control flow starting at the given block ever reach a suspend instruction before reaching a block in VisitedOrFreeBBs?
Definition at line 2089 of file CoroFrame.cpp.
References From, llvm::SmallPtrSetImpl< PtrType >::insert(), isSuspendBlock(), isSuspendReachableFrom(), and llvm::successors().
Referenced by isLocalAlloca(), and isSuspendReachableFrom().
localAllocaNeedsStackSave()
static bool localAllocaNeedsStackSave (CoroAllocaAllocInst * AI) static
Definition at line 2145 of file CoroFrame.cpp.
References llvm::dyn_cast(), llvm::Value::users(), and willLeaveFunctionImmediatelyAfter().
Referenced by lowerLocalAllocas().
lowerLocalAllocas()
static void lowerLocalAllocas (ArrayRef< CoroAllocaAllocInst * > LocalAllocas, SmallVectorImpl< Instruction * > & DeadInsts) static
Turn each of the given local allocas into a normal (dynamic) alloca instruction.
Definition at line 2163 of file CoroFrame.cpp.
References Builder, llvm::cast(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::isa(), localAllocaNeedsStackSave(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AllocaInst::setAlignment(), and llvm::Value::users().
Referenced by llvm::coro::buildCoroutineFrame().
lowerNonLocalAlloca()
static Instruction * lowerNonLocalAlloca (CoroAllocaAllocInst * AI, coro::Shape & Shape, SmallVectorImpl< Instruction * > & DeadInsts) static
Turn the given coro.alloca.alloc call into a dynamic allocation.
This happens during the all-instructions iteration, so it must not delete the call.
Definition at line 2207 of file CoroFrame.cpp.
References Builder, llvm::cast(), llvm::coro::Shape::emitAlloc(), llvm::coro::Shape::emitDealloc(), llvm::CoroAllocaAllocInst::getSize(), llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::users().
Referenced by llvm::coro::buildCoroutineFrame().
materializable()
static bool materializable (Instruction & V) static
Definition at line 2011 of file CoroFrame.cpp.
References llvm::isa().
Referenced by llvm::coro::buildCoroutineFrame().
movePHIValuesToInsertedBlock()
static void movePHIValuesToInsertedBlock (BasicBlock * SuccBB, BasicBlock * InsertedBB, BasicBlock * PredBB, PHINode * UntilPHI = nullptr) static
Definition at line 1817 of file CoroFrame.cpp.
References llvm::PHINode::addIncoming(), llvm::cast(), llvm::PHINode::Create(), llvm::dyn_cast(), llvm::BasicBlock::front(), and llvm::Value::getName().
Referenced by rewritePHIs(), and rewritePHIsForCleanupPad().
rewriteMaterializableInstructions()
static void rewriteMaterializableInstructions (IRBuilder<> & IRB, const SpillInfo & Spills) static
Definition at line 2025 of file CoroFrame.cpp.
References assert(), llvm::cast(), llvm::Instruction::clone(), llvm::dyn_cast(), E, llvm::BasicBlock::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::Instruction::insertBefore(), llvm::isa(), and llvm::Value::setName().
Referenced by llvm::coro::buildCoroutineFrame().
rewritePHIs() [1/2]
static void rewritePHIs (BasicBlock & BB) static
Definition at line 1927 of file CoroFrame.cpp.
References assert(), llvm::PHINode::Create(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ehAwareSplitEdge(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getFirstNonPHI(), llvm::Value::getName(), llvm::Value::getType(), movePHIValuesToInsertedBlock(), llvm::predecessors(), llvm::Value::replaceAllUsesWith(), rewritePHIsForCleanupPad(), and llvm::Value::takeName().
Referenced by llvm::coro::buildCoroutineFrame(), and rewritePHIs().
rewritePHIs() [2/2]
static void rewritePHIs (Function & F) static
Definition at line 1997 of file CoroFrame.cpp.
References llvm::dyn_cast(), F, llvm::BasicBlock::front(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and rewritePHIs().
rewritePHIsForCleanupPad()
static void rewritePHIsForCleanupPad (BasicBlock * CleanupPadBB, CleanupPadInst * CleanupPad) static
Definition at line 1835 of file CoroFrame.cpp.
References Builder, llvm::BasicBlock::Create(), llvm::ConstantInt::get(), llvm::BasicBlock::getContext(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::Instruction::insertAfter(), movePHIValuesToInsertedBlock(), llvm::pred_size(), llvm::predecessors(), llvm::Instruction::removeFromParent(), llvm::setUnwindEdgeTo(), and llvm::updatePhiNodes().
Referenced by rewritePHIs().
sinkLifetimeStartMarkers()
static void sinkLifetimeStartMarkers (Function & F, coro::Shape & Shape, SuspendCrossingInfo & Checker) static
For each local variable that all of its user are only used inside one of suspended region, we sink their lifetime.start markers to the place where after the suspend block.
Doing so minimizes the lifetime of each variable, hence minimizing the amount of data we end up putting on the frame.
Definition at line 2441 of file CoroFrame.cpp.
References assert(), llvm::cast(), llvm::coro::Shape::CoroSuspends, llvm::CastInst::Create(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), F, llvm::IntrinsicInst::getIntrinsicID(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getSingleSuccessor(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), instructions, llvm::isa(), isLifetimeStart(), isSuspendBlock(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), and llvm::Value::users().
Referenced by llvm::coro::buildCoroutineFrame().
sinkSpillUsesAfterCoroBegin()
static void sinkSpillUsesAfterCoroBegin (Function & F, const FrameDataInfo & FrameData, CoroBeginInst * CoroBegin) static
retcon and retcon.once conventions assume that all spill uses can be sunk after the coro.begin intrinsic.
Definition at line 2394 of file CoroFrame.cpp.
References A, B, llvm::SetVector< T, Vector, Set >::begin(), llvm::cast(), llvm::DominatorTree::dominates(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SetVector< T, Vector, Set >::end(), F, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), llvm::SetVector< T, Vector, Set >::insert(), llvm::Instruction::moveBefore(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by llvm::coro::buildCoroutineFrame().
solveDIType()
static DIType * solveDIType (DIBuilder & Builder, Type * Ty, const DataLayout & Layout, DIScope * Scope, unsigned LineNum, DenseMap< Type *, DIType * > & DITypeCache) static
Definition at line 864 of file CoroFrame.cpp.
References assert(), llvm::BitWidth, llvm::cast(), llvm::dbgs(), llvm::TypeSize::Fixed(), llvm::DataLayout::getABITypeAlignment(), llvm::DIType::getAlignInBits(), llvm::StructLayout::getElementOffsetInBits(), llvm::DIType::getName(), llvm::DataLayout::getPrefTypeAlign(), llvm::DataLayout::getPrefTypeAlignment(), llvm::DIType::getSizeInBits(), llvm::DataLayout::getStructLayout(), llvm::DataLayout::getTypeSizeInBits(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), Name, llvm::None, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, solveDIType(), solveTypeName(), and llvm::Align::value().
Referenced by buildFrameDebugInfo(), and solveDIType().
solveTypeName()
static StringRef solveTypeName (Type * Ty) static
Create name for Type.
It uses MDString to store new created string to avoid memory leak.
Definition at line 816 of file CoroFrame.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::MDString::get(), llvm::Type::getNonOpaquePointerElementType(), Name, solveTypeName(), llvm::raw_svector_ostream::str(), llvm::SmallString< N >::str(), and llvm::Twine::toStringRef().
Referenced by solveDIType(), and solveTypeName().
splitAround()
static void splitAround (Instruction * I, const Twine & Name) static
Definition at line 2076 of file CoroFrame.cpp.
References I, Name, and splitBlockIfNotFirst().
Referenced by llvm::coro::buildCoroutineFrame().
splitBeforeCatchSwitch()
static Instruction * splitBeforeCatchSwitch (CatchSwitchInst * CatchSwitch) static
Definition at line 1508 of file CoroFrame.cpp.
References llvm::CleanupPadInst::Create(), llvm::CleanupReturnInst::Create(), llvm::Instruction::eraseFromParent(), llvm::Instruction::getParent(), llvm::CatchSwitchInst::getParentPad(), llvm::BasicBlock::getTerminator(), and llvm::BasicBlock::splitBasicBlock().
Referenced by insertSpills().
splitBlockIfNotFirst()
static BasicBlock * splitBlockIfNotFirst (Instruction * I, const Twine & Name) static
Definition at line 2063 of file CoroFrame.cpp.
References llvm::BasicBlock::front(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getSinglePredecessor(), I, Name, llvm::Value::setName(), and llvm::BasicBlock::splitBasicBlock().
Referenced by splitAround().
willLeaveFunctionImmediatelyAfter()
static bool willLeaveFunctionImmediatelyAfter (BasicBlock * BB, unsigned depth = 3) static
After we split the coroutine, will the given basic block be along an obvious exit path for the resumption function?
Definition at line 2126 of file CoroFrame.cpp.
References isSuspendBlock(), llvm::successors(), and willLeaveFunctionImmediatelyAfter().
Referenced by localAllocaNeedsStackSave(), and willLeaveFunctionImmediatelyAfter().