LLVM: lib/Target/CSKY/MCTargetDesc/CSKYMCExpr.cpp File Reference
CSKYMCExpr.cpp File Reference
#include "CSKYMCExpr.h"
#include "CSKYFixupKinds.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/Support/Casting.h"
Macros
#define DEBUG_TYPE "csky-mc-expr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-mc-expr"
Definition at line 20 of file CSKYMCExpr.cpp.
Function Documentation
fixELFSymbolsInTLSFixupsImpl()
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 70 of file CSKYMCExpr.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, fixELFSymbolsInTLSFixupsImpl(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.