LLVM: lib/DebugInfo/PDB/DIA/DIAFrameData.cpp File Reference
DIAFrameData.cpp File Reference
#include "llvm/DebugInfo/PDB/DIA/DIAFrameData.h"
#include "llvm/DebugInfo/PDB/DIA/DIASession.h"
#include "llvm/DebugInfo/PDB/DIA/DIAUtils.h"
Functions
template<typename ArgType >
ArgType PrivateGetDIAValue (IDiaFrameData *FrameData, HRESULT(__stdcall IDiaFrameData::*Method)(ArgType *))
Function Documentation
PrivateGetDIAValue()
template<typename ArgType > ArgType PrivateGetDIAValue (IDiaFrameData * FrameData, HRESULT(__stdcall IDiaFrameData::* Method)(ArgType *))
Definition at line 20 of file DIAFrameData.cpp.
References llvm::pdb::FrameData, and llvm::Value.
Referenced by llvm::pdb::DIARawSymbol::getAccess(), llvm::pdb::DIAFrameData::getAddressOffset(), llvm::pdb::DIARawSymbol::getAddressOffset(), llvm::pdb::DIASectionContrib::getAddressOffset(), llvm::pdb::DIAFrameData::getAddressSection(), llvm::pdb::DIARawSymbol::getAddressSection(), llvm::pdb::DIASectionContrib::getAddressSection(), llvm::pdb::DIARawSymbol::getAddressTaken(), llvm::pdb::DIARawSymbol::getAge(), llvm::pdb::DIARawSymbol::getArrayIndexTypeId(), llvm::pdb::DIARawSymbol::getBackEndVersion(), llvm::pdb::DIARawSymbol::getBaseDataOffset(), llvm::pdb::DIARawSymbol::getBaseDataSlot(), llvm::pdb::DIARawSymbol::getBaseSymbolId(), llvm::pdb::DIARawSymbol::getBitPosition(), llvm::pdb::DIARawSymbol::getBuiltinType(), llvm::pdb::DIARawSymbol::getCallingConvention(), llvm::pdb::DIARawSymbol::getClassParentId(), llvm::pdb::DIASectionContrib::getCompilandId(), llvm::pdb::DIARawSymbol::getCompilerName(), llvm::pdb::DIARawSymbol::getCount(), llvm::pdb::DIARawSymbol::getCountLiveRanges(), llvm::pdb::DIASectionContrib::getDataCrc32(), llvm::pdb::DIARawSymbol::getDataKind(), llvm::pdb::DIARawSymbol::getFrontEndVersion(), llvm::pdb::DIARawSymbol::getGuid(), llvm::pdb::DIARawSymbol::getLanguage(), llvm::pdb::DIARawSymbol::getLength(), llvm::pdb::DIASectionContrib::getLength(), llvm::pdb::DIAFrameData::getLengthBlock(), llvm::pdb::DIARawSymbol::getLexicalParentId(), llvm::pdb::DIARawSymbol::getLibraryName(), llvm::pdb::DIARawSymbol::getLiveRangeLength(), llvm::pdb::DIARawSymbol::getLiveRangeStartAddressOffset(), llvm::pdb::DIARawSymbol::getLiveRangeStartAddressSection(), llvm::pdb::DIARawSymbol::getLiveRangeStartRelativeVirtualAddress(), llvm::pdb::DIARawSymbol::getLocalBasePointerRegisterId(), llvm::pdb::DIARawSymbol::getLocationType(), llvm::pdb::DIARawSymbol::getLowerBoundId(), llvm::pdb::DIARawSymbol::getMachineType(), llvm::pdb::DIARawSymbol::getMemorySpaceKind(), llvm::pdb::DIARawSymbol::getName(), llvm::pdb::DIARawSymbol::getNoStackOrdering(), llvm::pdb::DIARawSymbol::getNumberOfAcceleratorPointerTags(), llvm::pdb::DIARawSymbol::getNumberOfColumns(), llvm::pdb::DIARawSymbol::getNumberOfModifiers(), llvm::pdb::DIARawSymbol::getNumberOfRegisterIndices(), llvm::pdb::DIARawSymbol::getNumberOfRows(), llvm::pdb::DIARawSymbol::getObjectFileName(), llvm::pdb::DIARawSymbol::getOemId(), llvm::pdb::DIARawSymbol::getOemSymbolId(), llvm::pdb::DIARawSymbol::getOffset(), llvm::pdb::DIARawSymbol::getOffsetInUdt(), llvm::pdb::DIARawSymbol::getPlatform(), llvm::pdb::DIARawSymbol::getRank(), llvm::pdb::DIARawSymbol::getRegisterId(), llvm::pdb::DIARawSymbol::getRegisterType(), llvm::pdb::DIAFrameData::getRelativeVirtualAddress(), llvm::pdb::DIARawSymbol::getRelativeVirtualAddress(), llvm::pdb::DIASectionContrib::getRelativeVirtualAddress(), llvm::pdb::DIASectionContrib::getRelocationsCrc32(), llvm::pdb::DIARawSymbol::getSamplerSlot(), llvm::pdb::DIARawSymbol::getSignature(), llvm::pdb::DIARawSymbol::getSizeInUdt(), llvm::pdb::DIARawSymbol::getSlot(), llvm::pdb::DIARawSymbol::getSourceFileName(), llvm::pdb::DIARawSymbol::getStride(), llvm::pdb::DIARawSymbol::getSubTypeId(), llvm::pdb::DIARawSymbol::getSymbolsFileName(), llvm::pdb::DIARawSymbol::getSymIndexId(), llvm::pdb::DIARawSymbol::getSymTag(), llvm::pdb::DIARawSymbol::getTargetOffset(), llvm::pdb::DIARawSymbol::getTargetRelativeVirtualAddress(), llvm::pdb::DIARawSymbol::getTargetSection(), llvm::pdb::DIARawSymbol::getTargetVirtualAddress(), llvm::pdb::DIARawSymbol::getTextureSlot(), llvm::pdb::DIARawSymbol::getThisAdjust(), llvm::pdb::DIARawSymbol::getThunkOrdinal(), llvm::pdb::DIARawSymbol::getTimeStamp(), llvm::pdb::DIARawSymbol::getToken(), llvm::pdb::DIARawSymbol::getTypeId(), llvm::pdb::DIARawSymbol::getUavSlot(), llvm::pdb::DIARawSymbol::getUdtKind(), llvm::pdb::DIARawSymbol::getUndecoratedName(), llvm::pdb::DIARawSymbol::getUnmodifiedTypeId(), llvm::pdb::DIARawSymbol::getUnused(), llvm::pdb::DIARawSymbol::getUpperBoundId(), llvm::pdb::DIAFrameData::getVirtualAddress(), llvm::pdb::DIARawSymbol::getVirtualAddress(), llvm::pdb::DIASectionContrib::getVirtualAddress(), llvm::pdb::DIARawSymbol::getVirtualBaseDispIndex(), llvm::pdb::DIARawSymbol::getVirtualBaseOffset(), llvm::pdb::DIARawSymbol::getVirtualBasePointerOffset(), llvm::pdb::DIARawSymbol::getVirtualTableShapeId(), llvm::pdb::DIARawSymbol::hasAlloca(), llvm::pdb::DIARawSymbol::hasAssignmentOperator(), llvm::pdb::DIARawSymbol::hasCastOperator(), llvm::pdb::DIASectionContrib::hasCode(), llvm::pdb::DIASectionContrib::hasCode16Bit(), llvm::pdb::DIASectionContrib::hasComdat(), llvm::pdb::DIARawSymbol::hasConstructor(), llvm::pdb::DIARawSymbol::hasCTypes(), llvm::pdb::DIARawSymbol::hasCustomCallingConvention(), llvm::pdb::DIARawSymbol::hasDebugInfo(), llvm::pdb::DIARawSymbol::hasEH(), llvm::pdb::DIARawSymbol::hasEHa(), llvm::pdb::DIARawSymbol::hasFarReturn(), llvm::pdb::DIARawSymbol::hasFramePointer(), llvm::pdb::DIASectionContrib::hasInitializedData(), llvm::pdb::DIARawSymbol::hasInlAsm(), llvm::pdb::DIARawSymbol::hasInlineAttribute(), llvm::pdb::DIARawSymbol::hasInterruptReturn(), llvm::pdb::DIARawSymbol::hasLongJump(), llvm::pdb::DIARawSymbol::hasManagedCode(), llvm::pdb::DIARawSymbol::hasNestedTypes(), llvm::pdb::DIARawSymbol::hasNoInlineAttribute(), llvm::pdb::DIARawSymbol::hasNoReturnAttribute(), llvm::pdb::DIARawSymbol::hasOptimizedCodeDebugInfo(), llvm::pdb::DIARawSymbol::hasOverloadedOperator(), llvm::pdb::DIARawSymbol::hasPrivateSymbols(), llvm::pdb::DIARawSymbol::hasSecurityChecks(), llvm::pdb::DIARawSymbol::hasSEH(), llvm::pdb::DIARawSymbol::hasSetJump(), llvm::pdb::DIARawSymbol::hasStrictGSCheck(), llvm::pdb::DIASectionContrib::hasUninitializedData(), llvm::pdb::DIARawSymbol::isAcceleratorGroupSharedLocal(), llvm::pdb::DIARawSymbol::isAcceleratorPointerTagLiveRange(), llvm::pdb::DIARawSymbol::isAcceleratorStubFunction(), llvm::pdb::DIARawSymbol::isAggregated(), llvm::pdb::DIARawSymbol::isCode(), llvm::pdb::DIARawSymbol::isCompilerGenerated(), llvm::pdb::DIARawSymbol::isConstructorVirtualBase(), llvm::pdb::DIARawSymbol::isConstType(), llvm::pdb::DIARawSymbol::isCVTCIL(), llvm::pdb::DIARawSymbol::isCxxReturnUdt(), llvm::pdb::DIARawSymbol::isDataAligned(), llvm::pdb::DIASectionContrib::isDiscardable(), llvm::pdb::DIARawSymbol::isEditAndContinueEnabled(), llvm::pdb::DIASectionContrib::isExecutable(), llvm::pdb::DIARawSymbol::isFunction(), llvm::pdb::DIARawSymbol::isHLSLData(), llvm::pdb::DIARawSymbol::isHotpatchable(), llvm::pdb::DIARawSymbol::isIndirectVirtualBaseClass(), llvm::pdb::DIARawSymbol::isInterfaceUdt(), llvm::pdb::DIARawSymbol::isIntrinsic(), llvm::pdb::DIARawSymbol::isIntroVirtualFunction(), llvm::pdb::DIARawSymbol::isLocationControlFlowDependent(), llvm::pdb::DIARawSymbol::isLTCG(), llvm::pdb::DIARawSymbol::isManagedCode(), llvm::pdb::DIARawSymbol::isMatrixRowMajor(), llvm::pdb::DIARawSymbol::isMSILCode(), llvm::pdb::DIARawSymbol::isMSILNetmodule(), llvm::pdb::DIARawSymbol::isMultipleInheritance(), llvm::pdb::DIARawSymbol::isNaked(), llvm::pdb::DIARawSymbol::isNested(), llvm::pdb::DIASectionContrib::isNotCached(), llvm::pdb::DIASectionContrib::isNotPaged(), llvm::pdb::DIARawSymbol::isOptimizedAway(), llvm::pdb::DIARawSymbol::isPacked(), llvm::pdb::DIARawSymbol::isPointerBasedOnSymbolValue(), llvm::pdb::DIARawSymbol::isPointerToDataMember(), llvm::pdb::DIARawSymbol::isPointerToMemberFunction(), llvm::pdb::DIARawSymbol::isPureVirtual(), llvm::pdb::DIASectionContrib::isReadable(), llvm::pdb::DIARawSymbol::isReference(), llvm::pdb::DIARawSymbol::isRefUdt(), llvm::pdb::DIASectionContrib::isRemoved(), llvm::pdb::DIARawSymbol::isRestrictedType(), llvm::pdb::DIARawSymbol::isReturnValue(), llvm::pdb::DIARawSymbol::isRValueReference(), llvm::pdb::DIARawSymbol::isSafeBuffers(), llvm::pdb::DIARawSymbol::isScoped(), llvm::pdb::DIARawSymbol::isSdl(), llvm::pdb::DIASectionContrib::isShared(), llvm::pdb::DIARawSymbol::isSingleInheritance(), llvm::pdb::DIARawSymbol::isSplitted(), llvm::pdb::DIARawSymbol::isStatic(), llvm::pdb::DIARawSymbol::isUnalignedType(), llvm::pdb::DIARawSymbol::isUnreached(), llvm::pdb::DIARawSymbol::isValueUdt(), llvm::pdb::DIARawSymbol::isVirtual(), llvm::pdb::DIARawSymbol::isVirtualBaseClass(), llvm::pdb::DIARawSymbol::isVirtualInheritance(), llvm::pdb::DIARawSymbol::isVolatileType(), llvm::pdb::DIASectionContrib::isWritable(), and llvm::pdb::DIARawSymbol::wasInlined().