LLVM: lib/DebugInfo/DWARF/DWARFVerifier.cpp File Reference
DWARFVerifier.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFVerifier.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
#include "llvm/DebugInfo/DWARF/DWARFAttribute.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDataExtractor.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFLocationExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFObject.h"
#include "llvm/DebugInfo/DWARF/DWARFSection.h"
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/DJB.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
#include <set>
#include <vector>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static SmallVector< StringRef, 2 > getNames (const DWARFDie &DIE, bool IncludeLinkageName=true)
static bool isVariableIndexable (const DWARFDie &Die, DWARFContext &DCtx)
Function Documentation
getNames()
static SmallVector< StringRef, 2 > getNames (const DWARFDie & DIE, bool IncludeLinkageName = true) static
Definition at line 1338 of file DWARFVerifier.cpp.
References llvm::DIE::getTag().
isVariableIndexable()
static bool isVariableIndexable (const DWARFDie & Die, DWARFContext & DCtx) static
Definition at line 1438 of file DWARFVerifier.cpp.
References llvm::any_of(), llvm::consumeError(), llvm::Data, llvm::DWARFDie::getDwarfUnit(), llvm::DWARFDie::getLocations(), llvm::DWARFContext::isLittleEndian(), and llvm::dwarf::toStringRef().