LLVM: lib/Transforms/IPO/FunctionSpecialization.cpp File Reference
FunctionSpecialization.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueLattice.h"
#include "llvm/Analysis/ValueLatticeUtils.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Transforms/Scalar/SCCP.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/SCCPSolver.h"
#include "llvm/Transforms/Utils/SizeOpts.h"
#include <cmath>
Macros
#define DEBUG_TYPE "function-specialization"
Typedefs
using FuncList = SmallVectorImpl<Function *>
using CallArgBinding = std::pair<CallBase *, Constant *>
using CallSpecBinding = std::pair<CallBase *, SpecializationInfo>
using SpecializationMap = SmallMapVector<CallBase *, SpecializationInfo, 8>
Functions
STATISTIC (NumFuncSpecialized, "Number of functions specialized")
static bool isConstant (const ValueLatticeElement &LV)
static bool isOverdefined (const ValueLatticeElement &LV)
static Constant * getPromotableAlloca (AllocaInst *Alloca, CallInst *Call)
static Constant * getConstantStackValue (CallInst *Call, Value *Val, SCCPSolver &Solver)
static void constantArgPropagation (FuncList &WorkList, Module &M, SCCPSolver &Solver)
static void removeSSACopy (Function &F)
static void removeSSACopy (Module &M)
Variables
static cl::opt< bool > ForceFunctionSpecialization ("force-function-specialization", cl::init(false), cl::Hidden, cl::desc("Force function specialization for every call site with a " "constant argument"))
static cl::opt< unsigned > FuncSpecializationMaxIters ("func-specialization-max-iters", cl::Hidden, cl::desc("The maximum number of iterations function specialization is run"), cl::init(1))
static cl::opt< unsigned > MaxClonesThreshold ("func-specialization-max-clones", cl::Hidden, cl::desc("The maximum number of clones allowed for a single function " "specialization"), cl::init(3))
static cl::opt< unsigned > SmallFunctionThreshold ("func-specialization-size-threshold", cl::Hidden, cl::desc("Don't specialize functions that have less than this theshold " "number of instructions"), cl::init(100))
static cl::opt< unsigned > AvgLoopIterationCount ("func-specialization-avg-iters-cost", cl::Hidden, cl::desc("Average loop iteration count cost"), cl::init(10))
static cl::opt< bool > SpecializeOnAddresses ("func-specialization-on-address", cl::init(false), cl::Hidden, cl::desc("Enable function specialization on the address of global values"))
static cl::opt< bool > EnableSpecializationForLiteralConstant ("function-specialization-for-literal-constant", cl::init(false), cl::Hidden, cl::desc("Enable specialization of functions that take a literal constant " "as an argument."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "function-specialization"
Definition at line 64 of file FunctionSpecialization.cpp.
Typedef Documentation
CallArgBinding
using CallArgBinding = std::pair<CallBase *, Constant *>
Definition at line 121 of file FunctionSpecialization.cpp.
CallSpecBinding
using CallSpecBinding = std::pair<CallBase *, SpecializationInfo>
Definition at line 122 of file FunctionSpecialization.cpp.
FuncList
using FuncList = SmallVectorImpl<Function *>
Definition at line 120 of file FunctionSpecialization.cpp.
SpecializationMap
using SpecializationMap = SmallMapVector<CallBase *, SpecializationInfo, 8>
Definition at line 125 of file FunctionSpecialization.cpp.
Function Documentation
constantArgPropagation()
static void constantArgPropagation (FuncList & WorkList, Module & M, SCCPSolver & Solver) static
Definition at line 204 of file FunctionSpecialization.cpp.
References llvm::CallBase::args(), Call, llvm::cast(), Changed, llvm::dyn_cast(), F, llvm::CallBase::getArgOperand(), llvm::CallBase::getArgOperandNo(), llvm::ConstantExpr::getBitCast(), getConstantStackValue(), llvm::Value::getType(), llvm::GlobalValue::InternalLinkage, llvm::Type::isPointerTy(), llvm::CallBase::onlyReadsMemory(), llvm::CallBase::setArgOperand(), llvm::Value::users(), and llvm::SCCPSolver::visitCall().
Referenced by llvm::runFunctionSpecialization().
getConstantStackValue()
static Constant * getConstantStackValue (CallInst * Call, Value * Val, SCCPSolver & Solver) static
Definition at line 170 of file FunctionSpecialization.cpp.
References Call, llvm::dyn_cast(), getPromotableAlloca(), and llvm::Value::stripPointerCasts().
Referenced by constantArgPropagation().
getPromotableAlloca()
static Constant * getPromotableAlloca (AllocaInst * Alloca, CallInst * Call) static
Definition at line 141 of file FunctionSpecialization.cpp.
References Call, llvm::dyn_cast(), llvm::dyn_cast_or_null(), and llvm::Value::users().
Referenced by getConstantStackValue().
isConstant()
static bool isConstant (const ValueLatticeElement & LV) static
Definition at line 131 of file FunctionSpecialization.cpp.
References llvm::ValueLatticeElement::getConstantRange(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), and llvm::ConstantRange::isSingleElement().
Referenced by isOverdefined().
isOverdefined()
static bool isOverdefined (const ValueLatticeElement & LV) static
Definition at line 137 of file FunctionSpecialization.cpp.
References isConstant(), and llvm::ValueLatticeElement::isUnknownOrUndef().
Referenced by findReturnsToZap(), llvm::runIPSCCP(), and llvm::SCCPInstVisitor::solve().
removeSSACopy() [1/2]
static void removeSSACopy (Function & F) static
Definition at line 249 of file FunctionSpecialization.cpp.
References llvm::dyn_cast(), F, and llvm::make_early_inc_range().
Referenced by removeSSACopy(), and llvm::runFunctionSpecialization().
removeSSACopy() [2/2]
static void removeSSACopy (Module & M) static
Definition at line 263 of file FunctionSpecialization.cpp.
References F, and removeSSACopy().
STATISTIC()
STATISTIC (NumFuncSpecialized , "Number of functions specialized")
Variable Documentation
AvgLoopIterationCount
cl::opt< unsigned > AvgLoopIterationCount("func-specialization-avg-iters-cost", cl::Hidden, cl::desc("Average loop iteration count cost"), cl::init(10)) ("func-specialization-avg-iters-cost" , cl::Hidden , cl::desc("Average loop iteration count cost") , cl::init(10)) static
EnableSpecializationForLiteralConstant
cl::opt< bool > EnableSpecializationForLiteralConstant("function-specialization-for-literal-constant", cl::init(false), cl::Hidden, cl::desc("Enable specialization of functions that take a literal constant " "as an argument.")) ("function-specialization-for-literal-constant" , cl::init(false) , cl::Hidden , cl::desc("Enable specialization of functions that take a literal constant " "as an argument.")) static
ForceFunctionSpecialization
cl::opt< bool > ForceFunctionSpecialization("force-function-specialization", cl::init(false), cl::Hidden, cl::desc("Force function specialization for every call site with a " "constant argument")) ("force-function-specialization" , cl::init(false) , cl::Hidden , cl::desc("Force function specialization for every call site with a " "constant argument")) static
FuncSpecializationMaxIters
cl::opt< unsigned > FuncSpecializationMaxIters("func-specialization-max-iters", cl::Hidden, cl::desc("The maximum number of iterations function specialization is run"), cl::init(1)) ("func-specialization-max-iters" , cl::Hidden , cl::desc("The maximum number of iterations function specialization is run") , cl::init(1)) static
Referenced by llvm::runFunctionSpecialization().
MaxClonesThreshold
cl::opt< unsigned > MaxClonesThreshold("func-specialization-max-clones", cl::Hidden, cl::desc("The maximum number of clones allowed for a single function " "specialization"), cl::init(3)) ("func-specialization-max-clones" , cl::Hidden , cl::desc("The maximum number of clones allowed for a single function " "specialization") , cl::init(3)) static
SmallFunctionThreshold
cl::opt< unsigned > SmallFunctionThreshold("func-specialization-size-threshold", cl::Hidden, cl::desc("Don't specialize functions that have less than this theshold " "number of instructions"), cl::init(100)) ("func-specialization-size-threshold" , cl::Hidden , cl::desc("Don't specialize functions that have less than this theshold " "number of instructions") , cl::init(100)) static
SpecializeOnAddresses
cl::opt< bool > SpecializeOnAddresses("func-specialization-on-address", cl::init(false), cl::Hidden, cl::desc("Enable function specialization on the address of global values")) ("func-specialization-on-address" , cl::init(false) , cl::Hidden , cl::desc("Enable function specialization on the address of global values")) static