LLVM: lib/DebugInfo/PDB/Native/GlobalsStream.cpp File Reference
GlobalsStream.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/Native/Hash.h"
#include "llvm/DebugInfo/PDB/Native/RawError.h"
#include "llvm/DebugInfo/PDB/Native/SymbolStream.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Error.h"
#include <algorithm>
Functions
static Error checkHashHdrVersion (const GSIHashHeader *HashHdr)
static Error readGSIHashHeader (const GSIHashHeader *&HashHdr, BinaryStreamReader &Reader)
static Error readGSIHashRecords (FixedStreamArray< PSHashRecord > &HashRecords, const GSIHashHeader *HashHdr, BinaryStreamReader &Reader)
static Error readGSIHashBuckets (FixedStreamArray< support::ulittle32_t > &HashBuckets, FixedStreamArray< support::ulittle32_t > &HashBitmap, const GSIHashHeader *HashHdr, MutableArrayRef< int32_t > BucketMap, BinaryStreamReader &Reader)
Function Documentation
checkHashHdrVersion()
static Error checkHashHdrVersion (const GSIHashHeader * HashHdr) static
Definition at line 85 of file GlobalsStream.cpp.
References llvm::pdb::feature_unsupported, llvm::pdb::GSIHashHeader::HdrVersion, llvm::make_error(), llvm::Error::success(), and llvm::pdb::GSIHashHeader::VerHdr.
Referenced by readGSIHashBuckets(), and readGSIHashRecords().
readGSIHashBuckets()
static Error readGSIHashBuckets (FixedStreamArray< support::ulittle32_t > & HashBuckets, FixedStreamArray< support::ulittle32_t > & HashBitmap, const GSIHashHeader * HashHdr, MutableArrayRef< int32_t > BucketMap, BinaryStreamReader & Reader) static
Definition at line 129 of file GlobalsStream.cpp.
References llvm::alignTo(), B, checkHashHdrVersion(), llvm::pdb::corrupt_file, llvm::countPopulation(), I, llvm::pdb::IPHR_HASH, llvm::joinErrors(), llvm::make_error(), llvm::BinaryStreamReader::readArray(), and llvm::Error::success().
Referenced by llvm::pdb::GSIHashTable::read().
readGSIHashHeader()
static Error readGSIHashHeader (const GSIHashHeader *& HashHdr, BinaryStreamReader & Reader) static
Definition at line 94 of file GlobalsStream.cpp.
References llvm::pdb::corrupt_file, llvm::pdb::feature_unsupported, llvm::pdb::GSIHashHeader::HdrSignature, llvm::make_error(), llvm::BinaryStreamReader::readObject(), llvm::Error::success(), and llvm::pdb::GSIHashHeader::VerSignature.
Referenced by llvm::pdb::GSIHashTable::read().
readGSIHashRecords()
static Error readGSIHashRecords (FixedStreamArray< PSHashRecord > & HashRecords, const GSIHashHeader * HashHdr, BinaryStreamReader & Reader) static
Definition at line 108 of file GlobalsStream.cpp.
References checkHashHdrVersion(), llvm::pdb::corrupt_file, llvm::pdb::GSIHashHeader::HrSize, llvm::joinErrors(), llvm::make_error(), llvm::BinaryStreamReader::readArray(), and llvm::Error::success().
Referenced by llvm::pdb::GSIHashTable::read().