LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCExpr.cpp File Reference
HexagonMCExpr.cpp File Reference
#include "HexagonMCExpr.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "hexagon-mcexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-mcexpr"
Definition at line 21 of file HexagonMCExpr.cpp.
Function Documentation
fixELFSymbolsInTLSFixupsImpl()
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 41 of file HexagonMCExpr.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, fixELFSymbolsInTLSFixupsImpl(), llvm::MCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, llvm::MCSymbolRefExpr::VK_Hexagon_GD_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_GD_PLT, llvm::MCSymbolRefExpr::VK_Hexagon_IE, llvm::MCSymbolRefExpr::VK_Hexagon_IE_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_LD_GOT, llvm::MCSymbolRefExpr::VK_Hexagon_LD_PLT, and llvm::MCSymbolRefExpr::VK_TPREL.