LLVM: lib/Transforms/InstCombine/InstCombineMulDivRem.cpp File Reference
InstCombineMulDivRem.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include <cassert>
#include "llvm/Transforms/Utils/InstructionWorklist.h"
Macros
#define DEBUG_TYPE "instcombine"
Functions
static Value * simplifyValueKnownNonZero (Value *V, InstCombinerImpl &IC, Instruction &CxtI)
The specific integer value is used in a context where it is known to be non-zero.
static Value * foldMulSelectToNegate (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static bool multiplyOverflows (const APInt &C1, const APInt &C2, APInt &Product, bool IsSigned)
True if the multiply can not be expressed in an int this size.
static bool isMultiple (const APInt &C1, const APInt &C2, APInt &Quotient, bool IsSigned)
True if C1 is a multiple of C2. Quotient contains C1/C2.
static Value * takeLog2 (IRBuilderBase &Builder, Value *Op, unsigned Depth, bool DoFold)
static Instruction * narrowUDivURem (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
If we have zero-extended operands of an unsigned div or rem, we may be able to narrow the operation (sink the zext below the math).
static Instruction * foldFDivConstantDivisor (BinaryOperator &I)
Remove negation and try to convert division into multiplication.
static Instruction * foldFDivConstantDividend (BinaryOperator &I)
Remove negation and try to reassociate constant math.
static Instruction * foldFDivPowDivisor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Negate the exponent of pow/exp to fold division-by-pow() into multiply.
Variables
static const unsigned MaxDepth = 6
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 36 of file InstCombineMulDivRem.cpp.
Function Documentation
foldFDivConstantDividend()
static Instruction * foldFDivConstantDividend (BinaryOperator & I) static
Remove negation and try to reassociate constant math.
Definition at line 1253 of file InstCombineMulDivRem.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::CreateFDivFMF(), DL, llvm::ConstantExpr::getFNeg(), I, llvm::Constant::isNormalFP(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::visitFDiv().
foldFDivConstantDivisor()
static Instruction * foldFDivConstantDivisor (BinaryOperator & I) static
Remove negation and try to convert division into multiplication.
Definition at line 1222 of file InstCombineMulDivRem.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), DL, llvm::ConstantFP::get(), llvm::ConstantExpr::getFNeg(), I, llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::visitFDiv().
foldFDivPowDivisor()
static Instruction * foldFDivPowDivisor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Negate the exponent of pow/exp to fold division-by-pow() into multiply.
Definition at line 1287 of file InstCombineMulDivRem.cpp.
References llvm::BinaryOperator::CreateFMulFMF(), llvm::dyn_cast(), and I.
Referenced by llvm::InstCombinerImpl::visitFDiv().
foldMulSelectToNegate()
static Value * foldMulSelectToNegate (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 98 of file InstCombineMulDivRem.cpp.
References Cond, I, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitFMul(), and llvm::InstCombinerImpl::visitMul().
isMultiple()
static bool isMultiple (const APInt & C1, const APInt & C2, APInt & Quotient, bool IsSigned) static
True if C1 is a multiple of C2. Quotient contains C1/C2.
Definition at line 755 of file InstCombineMulDivRem.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::isAllOnes(), llvm::APInt::isMinSignedValue(), llvm::APInt::isMinValue(), llvm::APInt::isZero(), llvm::APInt::sdivrem(), and llvm::APInt::udivrem().
Referenced by llvm::InstCombinerImpl::commonIDivTransforms().
multiplyOverflows()
static bool multiplyOverflows (const APInt & C1, const APInt & C2, APInt & Product, bool IsSigned) static
True if the multiply can not be expressed in an int this size.
Definition at line 747 of file InstCombineMulDivRem.cpp.
References llvm::APInt::smul_ov(), and llvm::APInt::umul_ov().
Referenced by llvm::InstCombinerImpl::commonIDivTransforms().
narrowUDivURem()
static Instruction * narrowUDivURem (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
If we have zero-extended operands of an unsigned div or rem, we may be able to narrow the operation (sink the zext below the math).
Definition at line 994 of file InstCombineMulDivRem.cpp.
References llvm::CallingConv::C, D, llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getZExt(), I, llvm::isa(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), N, X, and Y.
Referenced by llvm::InstCombinerImpl::visitUDiv(), and llvm::InstCombinerImpl::visitURem().
simplifyValueKnownNonZero()
static Value * simplifyValueKnownNonZero (Value * V, InstCombinerImpl & IC, Instruction & CxtI) static
The specific integer value is used in a context where it is known to be non-zero.
If this allows us to simplify the computation, do so and return the new operand, otherwise return null.
Definition at line 45 of file InstCombineMulDivRem.cpp.
References A, B, llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateSub(), llvm::dyn_cast(), I, llvm::InstCombinerImpl::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombinerImpl::replaceOperand(), and simplifyValueKnownNonZero().
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonIRemTransforms(), and simplifyValueKnownNonZero().
takeLog2()
static Value * takeLog2 (IRBuilderBase & Builder, Value * Op, unsigned Depth, bool DoFold) static
Definition at line 930 of file InstCombineMulDivRem.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::Depth, llvm::dyn_cast(), llvm::ConstantExpr::getExactLogBase2(), llvm_unreachable, llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), MaxDepth, SI, takeLog2(), X, and Y.
Referenced by takeLog2(), and llvm::InstCombinerImpl::visitUDiv().
Variable Documentation
MaxDepth
const unsigned MaxDepth = 6 static
Definition at line 925 of file InstCombineMulDivRem.cpp.
Referenced by llvm::SUnit::biasCriticalPath(), combineX86ShufflesRecursively(), directlyImpliesPoison(), llvm::MachineInstr::dumpr(), impliesPoison(), llvm::SITargetLowering::isCanonicalized(), llvm::SITargetLowering::isCanonicalized(), isDereferenceableAndAlignedPointer(), llvm::NodeSet::print(), and takeLog2().