LLVM: lib/Transforms/Instrumentation/InstrProfiling.cpp File Reference
InstrProfiling.cpp File Reference
#include "llvm/Transforms/Instrumentation/InstrProfiling.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/InstrProfCorrelator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <string>
#include "llvm/ProfileData/InstrProfData.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "instrprof"
#define VALUE_PROF_FUNC_PARAM(ParamType, ParamName, ParamLLVMType)
#define INSTR_PROF_VISIBILITY
#define INSTR_PROF_DATA(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_VALUE_NODE(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_RAW_HEADER(Type, Name, Initializer)
#define INSTR_PROF_DATA_DEFINED
#define INSTR_PROF_COMMA ,
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Initializer)
#define COVMAP_HEADER(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_DATA(Type, LLVMType, Name, Init)
#define INSTR_PROF_DATA_DEFINED
#define INSTR_PROF_VALUE_NODE(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_RAW_HEADER(Type, Name, Initializer)
#define VALUE_PROF_FUNC_PARAM(ArgType, ArgName, ArgLLVMType)
#define INSTR_PROF_COMMA
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Initializer)
#define COVMAP_HEADER(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_DATA(Type, LLVMType, Name, Init)
#define INSTR_PROF_DATA_DEFINED
#define INSTR_PROF_VALUE_NODE(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_RAW_HEADER(Type, Name, Initializer)
#define VALUE_PROF_FUNC_PARAM(ArgType, ArgName, ArgLLVMType)
#define INSTR_PROF_COMMA
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Initializer)
#define COVMAP_HEADER(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_MIN_VAL_COUNTS 10
#define INSTR_PROF_VALUE_NODE(Type, LLVMType, Name, Init)
#define INSTR_PROF_DATA(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_DATA_DEFINED
#define INSTR_PROF_RAW_HEADER(Type, Name, Initializer)
#define VALUE_PROF_FUNC_PARAM(ArgType, ArgName, ArgLLVMType)
#define INSTR_PROF_COMMA
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Initializer)
#define COVMAP_HEADER(Type, LLVMType, Name, Initializer)
Functions
static bool needsRuntimeHookUnconditionally (const Triple &TT)
static bool containsProfilingIntrinsics (Module &M)
Check if the module contains uses of any profiling intrinsics.
static FunctionCallee getOrInsertValueProfilingCall (Module &M, const TargetLibraryInfo &TLI, ValueProfilingCallType CallType=ValueProfilingCallType::Default)
static std::string getVarName (InstrProfInstBase *Inc, StringRef Prefix, bool &Renamed)
Get the name of a profiling variable for a particular function.
static uint64_t getIntModuleFlagOrZero (const Module &M, StringRef Flag)
static bool enablesValueProfiling (const Module &M)
static bool profDataReferencedByCode (const Module &M)
static bool shouldRecordFunctionAddr (Function *F)
static bool needsRuntimeRegistrationOfSectionRange (const Triple &TT)
Variables
cl::opt< bool > llvm::DebugInfoCorrelate ("debug-info-correlate", cl::desc("Use debug info to correlate profiles."), cl::init(false))
Macro Definition Documentation
COVMAP_FUNC_RECORD [1/4]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Initializer)
COVMAP_FUNC_RECORD [2/4]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Initializer)
COVMAP_FUNC_RECORD [3/4]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Initializer)
COVMAP_FUNC_RECORD [4/4]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Initializer)
COVMAP_HEADER [1/4]
#define COVMAP_HEADER (Type, LLVMType, Name, Initializer)
COVMAP_HEADER [2/4]
#define COVMAP_HEADER (Type, LLVMType, Name, Initializer)
COVMAP_HEADER [3/4]
#define COVMAP_HEADER (Type, LLVMType, Name, Initializer)
COVMAP_HEADER [4/4]
#define COVMAP_HEADER (Type, LLVMType, Name, Initializer)
DEBUG_TYPE
#define DEBUG_TYPE "instrprof"
Definition at line 59 of file InstrProfiling.cpp.
INSTR_PROF_COMMA [1/4]
#define INSTR_PROF_COMMA
INSTR_PROF_COMMA [2/4]
#define INSTR_PROF_COMMA
INSTR_PROF_COMMA [3/4]
#define INSTR_PROF_COMMA
INSTR_PROF_COMMA [4/4]
#define INSTR_PROF_COMMA ,
INSTR_PROF_DATA [1/4]
#define INSTR_PROF_DATA (Type, LLVMType, Name, Init)
Value:
LLVMType,
INSTR_PROF_DATA [2/4]
#define INSTR_PROF_DATA (Type, LLVMType, Name, Init)
Value:
Init,
INSTR_PROF_DATA [3/4]
#define INSTR_PROF_DATA (Type, LLVMType, Name, Initializer)
INSTR_PROF_DATA [4/4]
#define INSTR_PROF_DATA (Type, LLVMType, Name, Initializer)
INSTR_PROF_DATA_DEFINED [1/4]
#define INSTR_PROF_DATA_DEFINED
INSTR_PROF_DATA_DEFINED [2/4]
#define INSTR_PROF_DATA_DEFINED
INSTR_PROF_DATA_DEFINED [3/4]
#define INSTR_PROF_DATA_DEFINED
INSTR_PROF_DATA_DEFINED [4/4]
#define INSTR_PROF_DATA_DEFINED
INSTR_PROF_MIN_VAL_COUNTS
#define INSTR_PROF_MIN_VAL_COUNTS 10
INSTR_PROF_RAW_HEADER [1/4]
#define INSTR_PROF_RAW_HEADER (Type, Name, Initializer)
INSTR_PROF_RAW_HEADER [2/4]
#define INSTR_PROF_RAW_HEADER (Type, Name, Initializer)
INSTR_PROF_RAW_HEADER [3/4]
#define INSTR_PROF_RAW_HEADER (Type, Name, Initializer)
INSTR_PROF_RAW_HEADER [4/4]
#define INSTR_PROF_RAW_HEADER (Type, Name, Initializer)
INSTR_PROF_VALUE_NODE [1/4]
#define INSTR_PROF_VALUE_NODE (Type, LLVMType, Name, Init)
Value:
LLVMType,
INSTR_PROF_VALUE_NODE [2/4]
#define INSTR_PROF_VALUE_NODE (Type, LLVMType, Name, Initializer)
INSTR_PROF_VALUE_NODE [3/4]
#define INSTR_PROF_VALUE_NODE (Type, LLVMType, Name, Initializer)
INSTR_PROF_VALUE_NODE [4/4]
#define INSTR_PROF_VALUE_NODE (Type, LLVMType, Name, Initializer)
INSTR_PROF_VISIBILITY
#define INSTR_PROF_VISIBILITY
VALUE_PROF_FUNC_PARAM [1/4]
#define VALUE_PROF_FUNC_PARAM (ArgType, ArgName, ArgLLVMType)
VALUE_PROF_FUNC_PARAM [2/4]
#define VALUE_PROF_FUNC_PARAM (ArgType, ArgName, ArgLLVMType)
VALUE_PROF_FUNC_PARAM [3/4]
#define VALUE_PROF_FUNC_PARAM (ArgType, ArgName, ArgLLVMType)
VALUE_PROF_FUNC_PARAM [4/4]
#define VALUE_PROF_FUNC_PARAM (ParamType, ParamName, ParamLLVMType)
Value:
ParamLLVMType
VALUE_PROF_KIND [1/4]
#define VALUE_PROF_KIND (Enumerator, Value, Descr)
VALUE_PROF_KIND [2/4]
#define VALUE_PROF_KIND (Enumerator, Value, Descr)
VALUE_PROF_KIND [3/4]
#define VALUE_PROF_KIND (Enumerator, Value, Descr)
VALUE_PROF_KIND [4/4]
#define VALUE_PROF_KIND (Enumerator, Value, Descr)
Function Documentation
containsProfilingIntrinsics()
static bool containsProfilingIntrinsics (Module & M) static
Check if the module contains uses of any profiling intrinsics.
Definition at line 504 of file InstrProfiling.cpp.
References F, and llvm::Intrinsic::getName().
Referenced by llvm::InstrProfiling::run().
enablesValueProfiling()
static bool enablesValueProfiling (const Module & M) static
Definition at line 772 of file InstrProfiling.cpp.
References getIntModuleFlagOrZero(), and llvm::isIRPGOFlagSet().
Referenced by profDataReferencedByCode().
getIntModuleFlagOrZero()
static uint64_t getIntModuleFlagOrZero (const Module & M, StringRef Flag) static
Definition at line 762 of file InstrProfiling.cpp.
References llvm::cast(), and llvm::dyn_cast_or_null().
Referenced by enablesValueProfiling().
getOrInsertValueProfilingCall()
static FunctionCallee getOrInsertValueProfilingCall (Module & M, const TargetLibraryInfo & TLI, ValueProfilingCallType CallType = ValueProfilingCallType::Default) static
Definition at line 577 of file InstrProfiling.cpp.
References assert(), llvm::FunctionType::get(), llvm::TargetLibraryInfo::getExtAttrForI32Param(), llvm::getInstrProfValueProfFuncName(), llvm::getInstrProfValueProfMemOpFuncName(), llvm::Type::getVoidTy(), and llvm::makeArrayRef().
getVarName()
static std::string getVarName (InstrProfInstBase * Inc, StringRef Prefix, bool & Renamed) static
Get the name of a profiling variable for a particular function.
Definition at line 743 of file InstrProfiling.cpp.
References llvm::canRenameComdatFunc(), F, llvm::FuncHash, llvm::InstrProfInstBase::getHash(), llvm::getInstrProfNameVarPrefix(), llvm::InstrProfInstBase::getName(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::ConstantInt::getZExtValue(), llvm::isIRPGOFlagSet(), Name, llvm::StringRef::size(), llvm::StringRef::substr(), and llvm::dwarf::toStringRef().
needsRuntimeHookUnconditionally()
static bool needsRuntimeHookUnconditionally (const Triple & TT) static
Definition at line 495 of file InstrProfiling.cpp.
Referenced by llvm::InstrProfiling::run().
needsRuntimeRegistrationOfSectionRange()
static bool needsRuntimeRegistrationOfSectionRange (const Triple & TT) static
Definition at line 819 of file InstrProfiling.cpp.
profDataReferencedByCode()
static bool profDataReferencedByCode (const Module & M) static
Definition at line 778 of file InstrProfiling.cpp.
References enablesValueProfiling().
Referenced by shouldRecordFunctionAddr().
shouldRecordFunctionAddr()
static bool shouldRecordFunctionAddr (Function * F) inline static
Definition at line 782 of file InstrProfiling.cpp.
References F, and profDataReferencedByCode().