LLVM: lib/IR/Instructions.cpp File Reference
Instructions.cpp File Reference
#include "llvm/IR/Instructions.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TypeSize.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>
Functions
static bool IsConstantOne (Value *val)
IsConstantOne - Return true only if val is constant int 1.
static Instruction * createMalloc (Instruction *InsertBefore, BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize, ArrayRef< OperandBundleDef > OpB, Function *MallocF, const Twine &Name)
static Instruction * createFree (Value *Source, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertBefore, BasicBlock *InsertAtEnd)
static Value * getAISize (LLVMContext &Context, Value *Amt)
static Align computeAllocaDefaultAlign (Type *Ty, BasicBlock *BB)
static Align computeAllocaDefaultAlign (Type *Ty, Instruction *I)
static Align computeLoadStoreDefaultAlign (Type *Ty, BasicBlock *BB)
static Align computeLoadStoreDefaultAlign (Type *Ty, Instruction *I)
template<typename IndexTy >
static Type * getIndexedTypeInternal (Type *Ty, ArrayRef< IndexTy > IdxList)
static Value * createPlaceholderForShuffleVector (Value *V)
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF)
Variables
static cl::opt< bool > DisableI2pP2iOpt ("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization"))
Function Documentation
computeAllocaDefaultAlign() [1/2]
static Align computeAllocaDefaultAlign (Type * Ty, BasicBlock * BB) static
Definition at line 1350 of file Instructions.cpp.
References assert(), DL, llvm::Module::getDataLayout(), llvm::BasicBlock::getModule(), and llvm::BasicBlock::getParent().
Referenced by computeAllocaDefaultAlign().
computeAllocaDefaultAlign() [2/2]
static Align computeAllocaDefaultAlign (Type * Ty, Instruction * I) static
Definition at line 1358 of file Instructions.cpp.
References assert(), computeAllocaDefaultAlign(), and I.
computeLoadStoreDefaultAlign() [1/2]
static Align computeLoadStoreDefaultAlign (Type * Ty, BasicBlock * BB) static
Definition at line 1432 of file Instructions.cpp.
References assert(), DL, llvm::Module::getDataLayout(), llvm::BasicBlock::getModule(), and llvm::BasicBlock::getParent().
Referenced by computeLoadStoreDefaultAlign().
computeLoadStoreDefaultAlign() [2/2]
static Align computeLoadStoreDefaultAlign (Type * Ty, Instruction * I) static
Definition at line 1440 of file Instructions.cpp.
References assert(), computeLoadStoreDefaultAlign(), and I.
createFree()
static Instruction * createFree (Value * Source, ArrayRef< OperandBundleDef > Bundles, Instruction * InsertBefore, BasicBlock * InsertAtEnd) static
Definition at line 792 of file Instructions.cpp.
References assert(), llvm::CallInst::Create(), llvm::dyn_cast(), F, llvm::FunctionCallee::getCallee(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), and llvm::Type::getVoidTy().
Referenced by llvm::CallInst::CreateFree(), llvm::CallInst::CreateFree(), llvm::CallInst::CreateFree(), and llvm::CallInst::CreateFree().
createMalloc()
static Instruction * createMalloc (Instruction * InsertBefore, BasicBlock * InsertAtEnd, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize, ArrayRef< OperandBundleDef > OpB, Function * MallocF, const Twine & Name) static
Definition at line 662 of file Instructions.cpp.
References assert(), llvm::cast(), llvm::CallInst::Create(), llvm::CastInst::CreateIntegerCast(), llvm::dyn_cast(), F, llvm::ConstantInt::get(), llvm::FunctionCallee::getCallee(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getInstList(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getIntegerCast(), llvm::ConstantExpr::getMul(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::PointerType::getUnqual(), IsConstantOne(), llvm::Type::isVoidTy(), Name, llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back(), llvm::CallBase::setCallingConv(), and llvm::CallInst::setTailCall().
Referenced by llvm::CallInst::CreateMalloc(), llvm::CallInst::CreateMalloc(), llvm::CallInst::CreateMalloc(), and llvm::CallInst::CreateMalloc().
createPlaceholderForShuffleVector()
static Value * createPlaceholderForShuffleVector (Value * V) static
Definition at line 1943 of file Instructions.cpp.
References assert(), and llvm::PoisonValue::get().
getAISize()
static Value * getAISize (LLVMContext & Context, Value * Amt) static
Definition at line 1338 of file Instructions.cpp.
References assert(), llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::Value::getType(), llvm::isa(), and llvm::Type::isIntegerTy().
getIndexedTypeInternal()
template<typename IndexTy > static Type * getIndexedTypeInternal (Type * Ty, ArrayRef< IndexTy > IdxList) static
Definition at line 1782 of file Instructions.cpp.
References llvm::ArrayRef< T >::empty(), llvm::GetElementPtrInst::getTypeAtIndex(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::GetElementPtrInst::getIndexedType(), llvm::GetElementPtrInst::getIndexedType(), and llvm::GetElementPtrInst::getIndexedType().
IsConstantOne()
static bool IsConstantOne (Value * val) static
IsConstantOne - Return true only if val is constant int 1.
Definition at line 656 of file Instructions.cpp.
References assert(), llvm::dyn_cast(), and llvm::ConstantInt::isOne().
Referenced by createMalloc().
isIdentityMaskImpl()
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 2201 of file Instructions.cpp.
References isSingleSourceMaskImpl().
Referenced by llvm::ShuffleVectorInst::isConcat(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::ShuffleVectorInst::isIdentityWithExtract(), llvm::ShuffleVectorInst::isIdentityWithPadding(), and llvm::ShuffleVectorInst::isInsertSubvectorMask().
isReplicationMaskWithParams()
static bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF) static
Definition at line 2465 of file Instructions.cpp.
References llvm::all_of(), assert(), llvm::seq(), llvm::ArrayRef< T >::size(), and llvm::UndefMaskElem.
Referenced by llvm::ShuffleVectorInst::isReplicationMask(), and llvm::ShuffleVectorInst::isReplicationMask().
isSingleSourceMaskImpl()
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 2177 of file Instructions.cpp.
References assert(), and I.
Referenced by llvm::ShuffleVectorInst::isExtractSubvectorMask(), isIdentityMaskImpl(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), and llvm::ShuffleVectorInst::isSingleSourceMask().
Variable Documentation
DisableI2pP2iOpt
cl::opt< bool > DisableI2pP2iOpt("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization")) ("disable-i2p-p2i-opt" , cl::init(false) , cl::desc("Disables inttoptr/ptrtoint roundtrip optimization")) static
Referenced by llvm::CastInst::isEliminableCastPair().