LLVM: lib/Transforms/InstCombine/InstCombinePHI.cpp File Reference
InstCombinePHI.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Utils/Local.h"
Classes
struct llvm::DenseMapInfo< LoweredPHIRecord >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "instcombine"
Functions
STATISTIC (NumPHIsOfInsertValues, "Number of phi-of-insertvalue turned into insertvalue-of-phis")
STATISTIC (NumPHIsOfExtractValues, "Number of phi-of-extractvalue turned into extractvalue-of-phi")
STATISTIC (NumPHICSEs, "Number of PHI's that got CSE'd")
static bool isSafeAndProfitableToSinkLoad (LoadInst *L)
Return true if we know that it is safe to sink the load out of the block that defines it.
static bool isDeadPHICycle (PHINode *PN, SmallPtrSetImpl< PHINode * > &PotentiallyDeadPHIs)
Return true if this PHI node is only used by a PHI node cycle that is dead.
static bool PHIsEqualValue (PHINode *PN, Value *NonPhiInVal, SmallPtrSetImpl< PHINode * > &ValueEqualPHIs)
Return true if this phi node is always equal to NonPhiInVal.
static ConstantInt * getAnyNonZeroConstInt (PHINode &PN)
Return an existing non-zero constant if this phi node has one, otherwise return constant 1.
static Value * simplifyUsingControlFlow (InstCombiner &Self, PHINode &PN, const DominatorTree &DT)
Variables
static cl::opt< unsigned > MaxNumPhis ("instcombine-max-num-phis", cl::init(512), cl::desc("Maximum number phis to handle in intptr/ptrint folding"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 27 of file InstCombinePHI.cpp.
Function Documentation
getAnyNonZeroConstInt()
static ConstantInt * getAnyNonZeroConstInt (PHINode & PN) static
Return an existing non-zero constant if this phi node has one, otherwise return constant 1.
Definition at line 1016 of file InstCombinePHI.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::Value::getType(), llvm::isa(), and llvm::User::operands().
Referenced by llvm::InstCombinerImpl::visitPHINode().
isDeadPHICycle()
static bool isDeadPHICycle (PHINode * PN, SmallPtrSetImpl< PHINode * > & PotentiallyDeadPHIs) static
Return true if this PHI node is only used by a PHI node cycle that is dead.
Definition at line 969 of file InstCombinePHI.cpp.
References llvm::dyn_cast(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), isDeadPHICycle(), llvm::SmallPtrSetImplBase::size(), llvm::Value::use_empty(), and llvm::Instruction::user_back().
Referenced by isDeadPHICycle(), and llvm::InstCombinerImpl::visitPHINode().
isSafeAndProfitableToSinkLoad()
static bool isSafeAndProfitableToSinkLoad (LoadInst * L) static
Return true if we know that it is safe to sink the load out of the block that defines it.
This means that it must be obvious the value of the load is not changed from the point of the load to the end of the block it is in.
Finally, it is safe, but not profitable, to sink a load targeting a non-address-taken alloca. Doing so will cause us to not promote the alloca to a register.
Definition at line 614 of file InstCombinePHI.cpp.
References llvm::dyn_cast(), E, llvm::BasicBlock::end(), GEP, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::isa(), SI, and llvm::Value::users().
Referenced by llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI().
PHIsEqualValue()
static bool PHIsEqualValue (PHINode * PN, Value * NonPhiInVal, SmallPtrSetImpl< PHINode * > & ValueEqualPHIs) static
Return true if this phi node is always equal to NonPhiInVal.
This happens with mutually cyclic phi nodes like: z = some value; x = phi (y, z); y = phi (x, z)
Definition at line 991 of file InstCombinePHI.cpp.
References llvm::dyn_cast(), llvm::PHINode::incoming_values(), llvm::SmallPtrSetImpl< PtrType >::insert(), PHIsEqualValue(), and llvm::SmallPtrSetImplBase::size().
Referenced by PHIsEqualValue(), and llvm::InstCombinerImpl::visitPHINode().
simplifyUsingControlFlow()
static Value * simplifyUsingControlFlow (InstCombiner & Self, PHINode & PN, const DominatorTree & DT) static
Definition at line 1271 of file InstCombinePHI.cpp.
References llvm::all_of(), llvm::PHINode::blocks(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), Cond, llvm::IRBuilderBase::CreateNot(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), llvm::BasicBlock::getFirstInsertionPt(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::ConstantExpr::getNot(), llvm::Instruction::getParent(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::PHINode::incoming_values(), llvm::DominatorTree::isReachableFromEntry(), llvm::User::operands(), llvm::IRBuilderBase::SetInsertPoint(), SI, and llvm::zip().
Referenced by llvm::InstCombinerImpl::visitPHINode().
STATISTIC() [1/3]
STATISTIC (NumPHICSEs , "Number of PHI's that got CSE'd")
STATISTIC() [2/3]
STATISTIC (NumPHIsOfExtractValues , "Number of phi-of-extractvalue turned into extractvalue-of-phi")
STATISTIC() [3/3]
STATISTIC (NumPHIsOfInsertValues , "Number of phi-of-insertvalue turned into insertvalue-of-phis")
Variable Documentation
MaxNumPhis
cl::opt< unsigned > MaxNumPhis("instcombine-max-num-phis", cl::init(512), cl::desc("Maximum number phis to handle in intptr/ptrint folding")) ("instcombine-max-num-phis" , cl::init(512) , cl::desc("Maximum number phis to handle in intptr/ptrint folding")) static
Referenced by llvm::InstCombinerImpl::foldIntegerTypedPHI().