LLVM: lib/IR/IRBuilder.cpp File Reference
IRBuilder.cpp File Reference
#include "llvm/IR/IRBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <cstdint>
#include <vector>
#include "llvm/IR/ConstrainedOps.def"
Macros
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
Functions
static CallInst * createCallHelper (Function *Callee, ArrayRef< Value * > Ops, IRBuilderBase *Builder, const Twine &Name="", Instruction *FMFSource=nullptr, ArrayRef< OperandBundleDef > OpBundles={})
static CallInst * getReductionIntrinsic (IRBuilderBase *Builder, Intrinsic::ID ID, Value *Src)
template<typename T0 >
static std::vector< Value * > getStatepointArgs (IRBuilderBase &B, uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs)
template<typename T1 , typename T2 , typename T3 >
static std::vector< OperandBundleDef > getStatepointBundles (Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static CallInst * CreateGCStatepointCallCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static InvokeInst * CreateGCStatepointInvokeCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
Macro Definition Documentation
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
Function Documentation
createCallHelper()
static CallInst * createCallHelper (Function * Callee, ArrayRef< Value * > Ops, IRBuilderBase * Builder, const Twine & Name = "", Instruction * FMFSource = nullptr, ArrayRef< OperandBundleDef > OpBundles = {}) static
Definition at line 87 of file IRBuilder.cpp.
Referenced by llvm::IRBuilderBase::CreateAssumption(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::IRBuilderBase::CreateGCGetPointerBase(), llvm::IRBuilderBase::CreateGCGetPointerOffset(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpyInline(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateMemSetInline(), llvm::IRBuilderBase::CreateMemTransferInst(), llvm::IRBuilderBase::CreateNoAliasScopeDeclaration(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::IRBuilderBase::CreateVScale(), and getReductionIntrinsic().
CreateGCStatepointCallCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static CallInst * CreateGCStatepointCallCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 718 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), llvm::Attribute::get(), llvm::FunctionCallee::getCallee(), llvm::Intrinsic::getDeclaration(), llvm::FunctionCallee::getFunctionType(), getStatepointArgs(), getStatepointBundles(), llvm::Value::getType(), and Name.
Referenced by llvm::IRBuilderBase::CreateGCStatepointCall(), llvm::IRBuilderBase::CreateGCStatepointCall(), and llvm::IRBuilderBase::CreateGCStatepointCall().
CreateGCStatepointInvokeCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static InvokeInst * CreateGCStatepointInvokeCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 770 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), llvm::Attribute::get(), llvm::FunctionCallee::getCallee(), llvm::Intrinsic::getDeclaration(), llvm::FunctionCallee::getFunctionType(), getStatepointArgs(), getStatepointBundles(), llvm::Value::getType(), and Name.
Referenced by llvm::IRBuilderBase::CreateGCStatepointInvoke(), llvm::IRBuilderBase::CreateGCStatepointInvoke(), and llvm::IRBuilderBase::CreateGCStatepointInvoke().
getReductionIntrinsic()
static CallInst * getReductionIntrinsic (IRBuilderBase * Builder, Intrinsic::ID ID, Value * Src) static
Definition at line 414 of file IRBuilder.cpp.
References createCallHelper(), and llvm::Intrinsic::getDeclaration().
Referenced by llvm::IRBuilderBase::CreateAddReduce(), llvm::IRBuilderBase::CreateAndReduce(), llvm::IRBuilderBase::CreateFPMaxReduce(), llvm::IRBuilderBase::CreateFPMinReduce(), llvm::IRBuilderBase::CreateIntMaxReduce(), llvm::IRBuilderBase::CreateIntMinReduce(), llvm::IRBuilderBase::CreateMulReduce(), llvm::IRBuilderBase::CreateOrReduce(), and llvm::IRBuilderBase::CreateXorReduce().
getStatepointArgs()
template<typename T0 > static std::vector< Value * > getStatepointArgs (IRBuilderBase & B, uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs) static
Definition at line 676 of file IRBuilder.cpp.
References llvm::append_range(), B, and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().
getStatepointBundles()
template<typename T1 , typename T2 , typename T3 > static std::vector< OperandBundleDef > getStatepointBundles (Optional< ArrayRef< T1 > > TransitionArgs, Optional< ArrayRef< T2 > > DeoptArgs, ArrayRef< T3 > GCArgs) static
Definition at line 695 of file IRBuilder.cpp.
References llvm::append_range(), and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().