LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.h File Reference
JITLoaderGDB.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include <cstdint>
Functions
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char *Data, size_t Size)
Function Documentation
llvm_orc_registerJITLoaderGDBAllocAction()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char * Data, size_t Size)
Definition at line 104 of file JITLoaderGDB.cpp.
References llvm::Data, registerJITLoaderGDBImpl(), llvm::release, Size, and llvm::Error::success().
llvm_orc_registerJITLoaderGDBWrapper()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char * Data, uint64_t Size)
Definition at line 117 of file JITLoaderGDB.cpp.
References llvm::Data, registerJITLoaderGDBImpl(), llvm::release, Size, and llvm::Error::success().