LLVM: lib/Support/KnownBits.cpp File Reference
KnownBits.cpp File Reference
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, bool CarryZero, bool CarryOne)
Function Documentation
computeForAddCarry()
static KnownBits computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, bool CarryZero, bool CarryOne) static
Definition at line 21 of file KnownBits.cpp.
References assert(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::move(), llvm::KnownBits::One, and llvm::KnownBits::Zero.