LLVM: lib/Target/Lanai/LanaiRegisterInfo.cpp File Reference
LanaiRegisterInfo.cpp File Reference
#include "LanaiRegisterInfo.h"
#include "LanaiAluCode.h"
#include "LanaiCondCode.h"
#include "LanaiFrameLowering.h"
#include "LanaiInstrInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/ErrorHandling.h"
#include "LanaiGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static bool isALUArithLoOpcode (unsigned Opcode)
static unsigned getOppositeALULoOpcode (unsigned Opcode)
static unsigned getRRMOpcodeVariant (unsigned Opcode)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 30 of file LanaiRegisterInfo.cpp.
Function Documentation
getOppositeALULoOpcode()
static unsigned getOppositeALULoOpcode (unsigned Opcode) static
Definition at line 85 of file LanaiRegisterInfo.cpp.
References llvm_unreachable.
Referenced by llvm::LanaiRegisterInfo::eliminateFrameIndex().
getRRMOpcodeVariant()
static unsigned getRRMOpcodeVariant (unsigned Opcode) static
Definition at line 108 of file LanaiRegisterInfo.cpp.
References llvm_unreachable.
Referenced by llvm::LanaiRegisterInfo::eliminateFrameIndex().
isALUArithLoOpcode()
static bool isALUArithLoOpcode (unsigned Opcode) static
Definition at line 69 of file LanaiRegisterInfo.cpp.
Referenced by llvm::LanaiRegisterInfo::eliminateFrameIndex().