LLVM: lib/Target/Lanai/LanaiTargetObjectFile.cpp File Reference
LanaiTargetObjectFile.cpp File Reference
#include "LanaiTargetObjectFile.h"
#include "LanaiSubtarget.h"
#include "LanaiTargetMachine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
Functions
static bool isInSmallSection (uint64_t Size)
Variables
static cl::opt< unsigned > SSThreshold ("lanai-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=0)"), cl::init(0))
Function Documentation
isInSmallSection()
static bool isInSmallSection (uint64_t Size) static
Definition at line 41 of file LanaiTargetObjectFile.cpp.
References Size, and SSThreshold.
Referenced by llvm::LanaiTargetObjectFile::isConstantInSmallSection().
Variable Documentation
SSThreshold
cl::opt< unsigned > SSThreshold("lanai-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=0)"), cl::init(0)) ("lanai-ssection-threshold" , cl::Hidden , cl::desc("Small data and bss section threshold size (default=0)") , cl::init(0)) static
Referenced by IsInSmallSection(), and isInSmallSection().