LLVM: lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp File Reference
LegalizeIntegerTypes.cpp File Reference
#include "LegalizeTypes.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "legalize-types"
Functions
static SDValue SaturateWidenedDIVFIX (SDValue V, SDLoc &dl, unsigned SatW, bool Signed, const TargetLowering &TLI, SelectionDAG &DAG)
static SDValue earlyExpandDIVFIX (SDNode *N, SDValue LHS, SDValue RHS, unsigned Scale, const TargetLowering &TLI, SelectionDAG &DAG, unsigned SatW=0)
static unsigned getExtendForIntVecReduction (SDNode *N)
static std::pair< ISD::CondCode, ISD::NodeType > getExpandedMinMaxOps (int Op)
static SDValue ExpandExtIntRes_DIVREM (const TargetLowering &TLI, const RTLIB::Libcall &LC, SelectionDAG &DAG, SDNode *N, const SDLoc &DL, const EVT &VT)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalize-types"
Definition at line 30 of file LegalizeIntegerTypes.cpp.
Function Documentation
earlyExpandDIVFIX()
static SDValue earlyExpandDIVFIX (SDNode * N, SDValue LHS, SDValue RHS, unsigned Scale, const TargetLowering & TLI, SelectionDAG & DAG, unsigned SatW = 0) static
Definition at line 1002 of file LegalizeIntegerTypes.cpp.
References assert(), llvm::TargetLowering::expandFixedPointDiv(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::EVT::isVector(), N, SaturateWidenedDIVFIX(), llvm::ISD::SDIVFIX, llvm::ISD::SDIVFIXSAT, Signed, and llvm::ISD::UDIVFIXSAT.
ExpandExtIntRes_DIVREM()
static SDValue ExpandExtIntRes_DIVREM (const TargetLowering & TLI, const RTLIB::Libcall & LC, SelectionDAG & DAG, SDNode * N, const SDLoc & DL, const EVT & VT) static
Definition at line 4053 of file LegalizeIntegerTypes.cpp.
References assert(), Callee, llvm::SelectionDAG::CreateStackTemporary(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::Type::getInt32Ty(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getLoad(), llvm::Type::getPointerTo(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::EVT::getTypeForEVT(), llvm::Type::getVoidTy(), llvm::EVT::isInteger(), llvm::TargetLowering::LowerCallTo(), N, llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), and llvm::TargetLowering::CallLoweringInfo::setLibCallee().
getExpandedMinMaxOps()
static std::pair< ISD::CondCode, ISD::NodeType > getExpandedMinMaxOps (int Op) static
Definition at line 2847 of file LegalizeIntegerTypes.cpp.
References llvm_unreachable, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, and llvm::ISD::UMIN.
getExtendForIntVecReduction()
static unsigned getExtendForIntVecReduction (SDNode * N) static
Definition at line 2224 of file LegalizeIntegerTypes.cpp.
References llvm::ISD::ANY_EXTEND, llvm_unreachable, N, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
SaturateWidenedDIVFIX()
static SDValue SaturateWidenedDIVFIX (SDValue V, SDLoc & dl, unsigned SatW, bool Signed, const TargetLowering & TLI, SelectionDAG & DAG) static
Definition at line 974 of file LegalizeIntegerTypes.cpp.
References llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), Signed, llvm::ISD::SMAX, llvm::ISD::SMIN, and llvm::ISD::UMIN.
Referenced by earlyExpandDIVFIX().