LLVM: lib/Transforms/Scalar/LowerExpectIntrinsic.cpp File Reference
LowerExpectIntrinsic.cpp File Reference
#include "llvm/Transforms/Scalar/LowerExpectIntrinsic.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/MisExpect.h"
Macros
#define DEBUG_TYPE "lower-expect-intrinsic"
Functions
STATISTIC (ExpectIntrinsicsHandled, "Number of 'expect' intrinsic instructions handled")
static std::tuple< uint32_t, uint32_t > getBranchWeight (Intrinsic::ID IntrinsicID, CallInst *CI, int BranchCount)
static bool handleSwitchExpect (SwitchInst &SI)
static void handlePhiDef (CallInst *Expect)
Handler for PHINodes that define the value argument to an @llvm.expect call.
template<class BrSelInst >
static bool handleBrSelExpect (BrSelInst &BSI)
static bool handleBranchExpect (BranchInst &BI)
static bool lowerExpectIntrinsic (Function &F)
INITIALIZE_PASS (LowerExpectIntrinsic, "lower-expect", "Lower 'expect' Intrinsics", false, false) FunctionPass *llvm
Variables
static cl::opt< uint32_t > LikelyBranchWeight ("likely-branch-weight", cl::Hidden, cl::init(2000), cl::desc("Weight of the branch likely to be taken (default = 2000)"))
static cl::opt< uint32_t > UnlikelyBranchWeight ("unlikely-branch-weight", cl::Hidden, cl::init(1), cl::desc("Weight of the branch unlikely to be taken (default = 1)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-expect-intrinsic"
Definition at line 32 of file LowerExpectIntrinsic.cpp.
Function Documentation
getBranchWeight()
static std::tuple< uint32_t, uint32_t > getBranchWeight (Intrinsic::ID IntrinsicID, CallInst * CI, int BranchCount) static
Definition at line 57 of file LowerExpectIntrinsic.cpp.
References assert(), llvm::cast(), llvm::CallBase::getArgOperand(), llvm::User::getNumOperands(), LikelyBranchWeight, and UnlikelyBranchWeight.
Referenced by handleBrSelExpect(), handlePhiDef(), and handleSwitchExpect().
handleBranchExpect()
static bool handleBranchExpect (BranchInst & BI) static
Definition at line 343 of file LowerExpectIntrinsic.cpp.
References handleBrSelExpect(), and llvm::BranchInst::isUnconditional().
Referenced by lowerExpectIntrinsic().
handleBrSelExpect()
template<class BrSelInst > static bool handleBrSelExpect (BrSelInst & BSI) static
Definition at line 262 of file LowerExpectIntrinsic.cpp.
References llvm::misexpect::checkFrontendInstrumentation(), llvm::MDBuilder::createBranchWeights(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::ConstantInt::getBitWidth(), getBranchWeight(), llvm::CallBase::getCalledFunction(), llvm::Value::getContext(), llvm::Function::getIntrinsicID(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, and llvm::User::setOperand().
Referenced by handleBranchExpect(), and lowerExpectIntrinsic().
handlePhiDef()
static void handlePhiDef (CallInst * Expect) static
Handler for PHINodes that define the value argument to an @llvm.expect call.
If the operand of the phi has a constant value and it 'contradicts' with the expected value of phi def, then the corresponding incoming edge of the phi is unlikely to be taken. Using that information, the branch probability info for the originating branch can be inferred.
Definition at line 120 of file LowerExpectIntrinsic.cpp.
References Arg, llvm::cast(), llvm::MDBuilder::createBranchWeights(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), getBranchWeight(), llvm::CallBase::getCalledFunction(), llvm::Function::getIntrinsicID(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getValue(), llvm::isa(), llvm::BranchInst::isConditional(), llvm::BranchInst::isUnconditional(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::Instruction::setMetadata(), and llvm::Value.
Referenced by lowerExpectIntrinsic().
handleSwitchExpect()
static bool handleSwitchExpect (SwitchInst & SI) static
Definition at line 77 of file LowerExpectIntrinsic.cpp.
References llvm::misexpect::checkExpectAnnotations(), llvm::MDBuilder::createBranchWeights(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), getBranchWeight(), llvm::CallBase::getCalledFunction(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseIndex(), llvm::Value::getContext(), llvm::Function::getIntrinsicID(), and SI.
Referenced by lowerExpectIntrinsic().
INITIALIZE_PASS()
INITIALIZE_PASS (LowerExpectIntrinsic , "lower-expect" , "Lower 'expect' Intrinsics" , false , false)
Definition at line 421 of file LowerExpectIntrinsic.cpp.
lowerExpectIntrinsic()
static bool lowerExpectIntrinsic (Function & F) static
Definition at line 350 of file LowerExpectIntrinsic.cpp.
References Changed, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), F, llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::Function::getIntrinsicID(), handleBranchExpect(), handleBrSelExpect(), handlePhiDef(), handleSwitchExpect(), llvm::make_early_inc_range(), llvm::Value::replaceAllUsesWith(), llvm::reverse(), and SI.
Referenced by llvm::LowerExpectIntrinsicPass::run().
STATISTIC()
STATISTIC (ExpectIntrinsicsHandled , "Number of 'expect' intrinsic instructions handled")
Variable Documentation
LikelyBranchWeight
cl::opt< uint32_t > LikelyBranchWeight("likely-branch-weight", cl::Hidden, cl::init(2000), cl::desc("Weight of the branch likely to be taken (default = 2000)")) ("likely-branch-weight" , cl::Hidden , cl::init(2000) , cl::desc("Weight of the branch likely to be taken (default = 2000)")) static
Referenced by getBranchWeight(), and llvm::misexpect::verifyMisExpect().
UnlikelyBranchWeight
cl::opt< uint32_t > UnlikelyBranchWeight("unlikely-branch-weight", cl::Hidden, cl::init(1), cl::desc("Weight of the branch unlikely to be taken (default = 1)")) ("unlikely-branch-weight" , cl::Hidden , cl::init(1) , cl::desc("Weight of the branch unlikely to be taken (default = 1)")) static
Referenced by getBranchWeight(), and llvm::misexpect::verifyMisExpect().