LLVM: lib/LTO/LTO.cpp File Reference
LTO.cpp File Reference
#include "llvm/LTO/LTO.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/StackSafetyAnalysis.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/LTO/LTOBackend.h"
#include "llvm/LTO/SummaryBasedOptimizations.h"
#include "llvm/Linker/IRMover.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SHA1.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/VCSRevision.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
#include "llvm/Transforms/Utils/SplitModule.h"
#include <set>
#include "llvm/IR/RuntimeLibcalls.def"
Classes
class llvm::lto::ThinBackendProc
This class defines the interface to the ThinLTO backend.
Macros
#define DEBUG_TYPE "lto"
#define HANDLE_LIBCALL(code, name)
Functions
static void thinLTOResolvePrevailingGUID (const Config &C, ValueInfo VI, DenseSet< GlobalValueSummary * > &GlobalInvolvedWithAlias, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing, function_ref< void(StringRef, GlobalValue::GUID, GlobalValue::LinkageTypes)> recordNewLinkage, const DenseSet< GlobalValue::GUID > &GUIDPreservedSymbols)
static bool isWeakObjectWithRWAccess (GlobalValueSummary *GVS)
static void thinLTOInternalizeAndPromoteGUID (ValueInfo VI, function_ref< bool(StringRef, ValueInfo)> isExported, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing)
static void writeToResolutionFile (raw_ostream &OS, InputFile *Input, ArrayRef< SymbolResolution > Res)
static void handleNonPrevailingComdat (GlobalValue &GV, std::set< const Comdat * > &NonPrevailingComdats)
Variables
static cl::opt< bool > DumpThinCGSCCs ("dump-thin-cg-sccs", cl::init(false), cl::Hidden, cl::desc("Dump the SCCs in the ThinLTO index's callgraph"))
cl::opt< bool > EnableLTOInternalization ("enable-lto-internalization", cl::init(true), cl::Hidden, cl::desc("Enable global value internalization in LTO"))
Enable global value internalization in LTO.
static const char * libcallRoutineNames []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lto"
Definition at line 66 of file LTO.cpp.
HANDLE_LIBCALL
#define HANDLE_LIBCALL (code, name)
Value:
name,
Function Documentation
handleNonPrevailingComdat()
static void handleNonPrevailingComdat (GlobalValue & GV, std::set< const Comdat * > & NonPrevailingComdats) static
Definition at line 688 of file LTO.cpp.
References llvm::GlobalValue::AvailableExternallyLinkage, llvm::CallingConv::C, llvm::dyn_cast(), llvm::GlobalValue::getComdat(), llvm::GlobalValue::hasLocalLinkage(), and llvm::GlobalValue::setLinkage().
isWeakObjectWithRWAccess()
static bool isWeakObjectWithRWAccess (GlobalValueSummary * GVS) static
Definition at line 421 of file LTO.cpp.
References llvm::dyn_cast(), llvm::GlobalValueSummary::getBaseObject(), llvm::GlobalValue::LinkOnceODRLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by thinLTOInternalizeAndPromoteGUID().
thinLTOInternalizeAndPromoteGUID()
static void thinLTOInternalizeAndPromoteGUID (ValueInfo VI, function_ref< bool(StringRef, ValueInfo)> isExported, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing) static
Definition at line 429 of file LTO.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, EnableLTOInternalization, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isInterposableLinkage(), llvm::GlobalValue::isLocalLinkage(), and isWeakObjectWithRWAccess().
Referenced by llvm::thinLTOInternalizeAndPromoteInIndex().
thinLTOResolvePrevailingGUID()
static void thinLTOResolvePrevailingGUID (const Config & C, ValueInfo VI, DenseSet< GlobalValueSummary * > & GlobalInvolvedWithAlias, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing, function_ref< void(StringRef, GlobalValue::GUID, GlobalValue::LinkageTypes)> recordNewLinkage, const DenseSet< GlobalValue::GUID > & GUIDPreservedSymbols) static
Definition at line 322 of file LTO.cpp.
References llvm::GlobalValue::AvailableExternallyLinkage, llvm::CallingConv::C, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::GlobalValue::DefaultVisibility, llvm::lto::Config::ELF, llvm::lto::Config::FromPrevailing, llvm::GlobalValue::getWeakLinkage(), llvm::isa(), llvm::GlobalValue::isAppendingLinkage(), llvm::GlobalValue::isLinkOnceLinkage(), llvm::GlobalValue::isLinkOnceODRLinkage(), and llvm::GlobalValue::isLocalLinkage().
Referenced by llvm::thinLTOResolvePrevailingInIndex().
writeToResolutionFile()
static void writeToResolutionFile (raw_ostream & OS, InputFile * Input, ArrayRef< SymbolResolution > Res) static
Definition at line 589 of file LTO.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::lto::SymbolResolution::FinalDefinitionInLinkageUnit, llvm::raw_ostream::flush(), llvm::lto::SymbolResolution::LinkerRedefined, llvm::lto::SymbolResolution::Prevailing, and llvm::lto::SymbolResolution::VisibleToRegularObj.
Referenced by llvm::lto::LTO::add().
Variable Documentation
DumpThinCGSCCs
cl::opt< bool > DumpThinCGSCCs("dump-thin-cg-sccs", cl::init(false), cl::Hidden, cl::desc("Dump the SCCs in the ThinLTO index's callgraph")) ("dump-thin-cg-sccs" , cl::init(false) , cl::Hidden , cl::desc("Dump the SCCs in the ThinLTO index's callgraph")) static
EnableLTOInternalization
cl::opt< bool > EnableLTOInternalization("enable-lto-internalization", cl::init(true), cl::Hidden, cl::desc("Enable global value internalization in LTO")) ("enable-lto-internalization" , cl::init(true) , cl::Hidden , cl::desc("Enable global value internalization in LTO"))
Enable global value internalization in LTO.
Referenced by thinLTOInternalizeAndPromoteGUID().
libcallRoutineNames
const char* libcallRoutineNames[] static
Initial value:
= {
#define HANDLE_LIBCALL(code, name)
}
Definition at line 1150 of file LTO.cpp.
Referenced by llvm::lto::LTO::getRuntimeLibcallSymbols().