LLVM: lib/Target/M68k/M68kRegisterInfo.cpp File Reference
M68kRegisterInfo.cpp File Reference
This file contains the CPU0 implementation of the TargetRegisterInfo class.
#include "M68kRegisterInfo.h"
#include "M68k.h"
#include "M68kMachineFunction.h"
#include "M68kSubtarget.h"
#include "MCTargetDesc/M68kMCTargetDesc.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "M68kGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
#define DEBUG_TYPE "m68k-reg-info"
Functions
static bool CantUseSP (const MachineFrameInfo &MFI)
Variables
static cl::opt< bool > EnableBasePointer ("m68k-use-base-pointer", cl::Hidden, cl::init(true), cl::desc("Enable use of a base pointer for complex stack frames"))
Detailed Description
This file contains the CPU0 implementation of the TargetRegisterInfo class.
Definition in file M68kRegisterInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "m68k-reg-info"
Definition at line 34 of file M68kRegisterInfo.cpp.
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 31 of file M68kRegisterInfo.cpp.
Function Documentation
CantUseSP()
static bool CantUseSP (const MachineFrameInfo & MFI) static
Definition at line 223 of file M68kRegisterInfo.cpp.
References llvm::MachineFrameInfo::hasOpaqueSPAdjustment(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::M68kRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), llvm::M68kRegisterInfo::hasBasePointer(), and llvm::X86RegisterInfo::hasBasePointer().
Variable Documentation
EnableBasePointer
cl::opt< bool > EnableBasePointer("m68k-use-base-pointer", cl::Hidden, cl::init(true), cl::desc("Enable use of a base pointer for complex stack frames")) ("m68k-use-base-pointer" , cl::Hidden , cl::init(true) , cl::desc("Enable use of a base pointer for complex stack frames")) static
Referenced by llvm::M68kRegisterInfo::hasBasePointer(), llvm::PPCRegisterInfo::hasBasePointer(), and llvm::X86RegisterInfo::hasBasePointer().