LLVM: lib/ObjCopy/MachO/MachOObject.cpp File Reference
MachOObject.cpp File Reference
#include "MachOObject.h"
#include "llvm/ADT/SmallPtrSet.h"
#include <unordered_set>
Functions
template<typename SegmentType >
static void constructSegment (SegmentType &Seg, llvm::MachO::LoadCommandType CmdType, StringRef SegName, uint64_t SegVMAddr, uint64_t SegVMSize)
static StringRef extractSegmentName (const char *SegName)
Extracts a segment name from a string which is possibly non-null-terminated.
Function Documentation
constructSegment()
template<typename SegmentType > static void constructSegment (SegmentType & Seg, llvm::MachO::LoadCommandType CmdType, StringRef SegName, uint64_t SegVMAddr, uint64_t SegVMSize) static
Definition at line 158 of file MachOObject.cpp.
References assert(), llvm::StringRef::data(), llvm::StringRef::size(), llvm::MachO::VM_PROT_EXECUTE, llvm::MachO::VM_PROT_READ, and llvm::MachO::VM_PROT_WRITE.
Referenced by llvm::objcopy::macho::Object::addSegment().
extractSegmentName()
static StringRef extractSegmentName (const char * SegName) static
Extracts a segment name from a string which is possibly non-null-terminated.
Definition at line 187 of file MachOObject.cpp.
References llvm::MachO::segment_command::segname.
Referenced by llvm::objcopy::macho::LoadCommand::getSegmentName().