LLVM: lib/Object/MachOUniversalWriter.cpp File Reference
MachOUniversalWriter.cpp File Reference
#include "llvm/Object/MachOUniversalWriter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/raw_ostream.h"
Typedefs
using MachoCPUTy = std::pair<unsigned, unsigned>
Functions
static uint32_t calculateFileAlignment (const MachOObjectFile &O)
static uint32_t calculateAlignment (const MachOObjectFile &ObjectFile)
static Expected< MachoCPUTy > getMachoCPUFromTriple (Triple TT)
static Expected< MachoCPUTy > getMachoCPUFromTriple (StringRef TT)
static Expected< SmallVector< MachO::fat_arch, 2 > > buildFatArchList (ArrayRef< Slice > Slices)
Typedef Documentation
MachoCPUTy
using MachoCPUTy = std::pair<unsigned, unsigned>
Definition at line 103 of file MachOUniversalWriter.cpp.
Function Documentation
buildFatArchList()
static Expected< SmallVector< MachO::fat_arch, 2 > > buildFatArchList (ArrayRef< Slice > Slices) static
Definition at line 244 of file MachOUniversalWriter.cpp.
References llvm::MachO::fat_arch::align, llvm::alignTo(), llvm::MachO::fat_arch::cpusubtype, llvm::MachO::fat_arch::cputype, llvm::createStringError(), Offset, llvm::MachO::fat_arch::offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ArrayRef< T >::size(), and llvm::MachO::fat_arch::size.
Referenced by llvm::object::writeUniversalBinaryToStream().
calculateAlignment()
static uint32_t calculateAlignment (const MachOObjectFile & ObjectFile) static
Definition at line 69 of file MachOUniversalWriter.cpp.
References calculateFileAlignment(), llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, and llvm::MachO::CPU_TYPE_X86_64.
calculateFileAlignment()
static uint32_t calculateFileAlignment (const MachOObjectFile & O) static
Definition at line 37 of file MachOUniversalWriter.cpp.
References llvm::countTrailingZeros(), llvm::object::MachOUniversalBinary::MaxSectionAlignment, llvm::MachO::MH_OBJECT, and SI.
Referenced by calculateAlignment().
getMachoCPUFromTriple() [1/2]
static Expected< MachoCPUTy > getMachoCPUFromTriple (StringRef TT) static
Definition at line 116 of file MachOUniversalWriter.cpp.
References getMachoCPUFromTriple().
getMachoCPUFromTriple() [2/2]
static Expected< MachoCPUTy > getMachoCPUFromTriple (Triple TT) static
Definition at line 105 of file MachOUniversalWriter.cpp.
References llvm::MachO::getCPUSubType(), and llvm::MachO::getCPUType().
Referenced by llvm::object::Slice::create(), llvm::object::Slice::create(), and getMachoCPUFromTriple().