LLVM: lib/CodeGen/MachineFrameInfo.cpp File Reference
MachineFrameInfo.cpp File Reference
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Macros
#define DEBUG_TYPE "codegen"
Functions
static Align clampStackAlignment (bool ShouldClamp, Align Alignment, Align StackAlignment)
Clamp the alignment if requested and emit a warning.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "codegen"
Definition at line 27 of file MachineFrameInfo.cpp.
Function Documentation
clampStackAlignment()
static Align clampStackAlignment (bool ShouldClamp, Align Alignment, Align StackAlignment) inline static
Clamp the alignment if requested and emit a warning.
Definition at line 40 of file MachineFrameInfo.cpp.
References llvm::dbgs(), llvm::DebugStr(), and LLVM_DEBUG.
Referenced by llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateFixedSpillStackObject(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::MachineFrameInfo::CreateStackObject(), and llvm::MachineFrameInfo::CreateVariableSizedObject().