LLVM: lib/MC/MCWin64EH.cpp File Reference
MCWin64EH.cpp File Reference
#include "llvm/MC/MCWin64EH.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Win64EH.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static uint8_t CountOfUnwindCodes (std::vector< WinEH::Instruction > &Insns)
static void EmitAbsDifference (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS)
static void EmitUnwindCode (MCStreamer &streamer, const MCSymbol *begin, WinEH::Instruction &inst)
static void EmitSymbolRefWithOfs (MCStreamer &streamer, const MCSymbol *Base, const MCSymbol *Other)
static void EmitRuntimeFunction (MCStreamer &streamer, const WinEH::FrameInfo *info)
static void EmitUnwindInfo (MCStreamer &streamer, WinEH::FrameInfo *info)
static const MCExpr * GetSubDivExpr (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS, int Div)
static Optional< int64_t > GetOptionalAbsDifference (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS)
static int64_t GetAbsDifference (MCStreamer &Streamer, const MCSymbol *LHS, const MCSymbol *RHS)
static uint32_t ARM64CountOfUnwindCodes (ArrayRef< WinEH::Instruction > Insns)
static void ARM64EmitUnwindCode (MCStreamer &streamer, const WinEH::Instruction &inst)
static MCSymbol * FindMatchingEpilog (const std::vector< WinEH::Instruction > &EpilogInstrs, const std::vector< MCSymbol * > &Epilogs, const WinEH::FrameInfo *info)
static void simplifyARM64Opcodes (std::vector< WinEH::Instruction > &Instructions, bool Reverse)
static int getARM64OffsetInProlog (const std::vector< WinEH::Instruction > &Prolog, const std::vector< WinEH::Instruction > &Epilog)
static int checkARM64PackedEpilog (MCStreamer &streamer, WinEH::FrameInfo *info, int PrologCodeBytes)
static bool tryARM64PackedUnwind (WinEH::FrameInfo *info, uint32_t FuncLength, int PackedEpilogOffset)
static void ARM64EmitUnwindInfo (MCStreamer &streamer, WinEH::FrameInfo *info, bool TryPacked=true)
static uint32_t ARMCountOfUnwindCodes (ArrayRef< WinEH::Instruction > Insns)
static uint32_t ARMCountOfInstructionBytes (ArrayRef< WinEH::Instruction > Insns, bool *HasCustom=nullptr)
static void checkARMInstructions (MCStreamer &Streamer, ArrayRef< WinEH::Instruction > Insns, const MCSymbol *Begin, const MCSymbol *End, StringRef Name, StringRef Type)
static bool isARMTerminator (const WinEH::Instruction &inst)
static void ARMEmitUnwindCode (MCStreamer &streamer, const WinEH::Instruction &inst)
static int getARMOffsetInProlog (const std::vector< WinEH::Instruction > &Prolog, const std::vector< WinEH::Instruction > &Epilog, bool CanTweakProlog)
static int checkARMPackedEpilog (MCStreamer &streamer, WinEH::FrameInfo *info, int PrologCodeBytes)
static bool parseRegMask (unsigned Mask, bool &HasLR, bool &HasR11, unsigned &Folded, int &IntRegs)
static bool tryARMPackedUnwind (MCStreamer &streamer, WinEH::FrameInfo *info, uint32_t FuncLength)
static void ARMEmitUnwindInfo (MCStreamer &streamer, WinEH::FrameInfo *info, bool TryPacked=true)
static void ARMEmitRuntimeFunction (MCStreamer &streamer, const WinEH::FrameInfo *info)
Function Documentation
ARM64CountOfUnwindCodes()
static uint32_t ARM64CountOfUnwindCodes (ArrayRef< WinEH::Instruction > Insns) static
Definition at line 291 of file MCWin64EH.cpp.
References llvm::Count, I, llvm_unreachable, llvm::Win64EH::UOP_AddFP, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_ClearUnwoundToCall, llvm::Win64EH::UOP_Context, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveFReg, llvm::Win64EH::UOP_SaveFRegP, llvm::Win64EH::UOP_SaveFRegPX, llvm::Win64EH::UOP_SaveFRegX, llvm::Win64EH::UOP_SaveLRPair, llvm::Win64EH::UOP_SaveNext, llvm::Win64EH::UOP_SaveR19R20X, llvm::Win64EH::UOP_SaveReg, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, llvm::Win64EH::UOP_SaveRegX, llvm::Win64EH::UOP_SetFP, and llvm::Win64EH::UOP_TrapFrame.
Referenced by ARM64EmitUnwindInfo(), checkARM64PackedEpilog(), and getARM64OffsetInProlog().
ARM64EmitUnwindCode()
static void ARM64EmitUnwindCode (MCStreamer & streamer, const WinEH::Instruction & inst) static
Definition at line 376 of file MCWin64EH.cpp.
References assert(), llvm::MCStreamer::emitInt8(), llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AddFP, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_ClearUnwoundToCall, llvm::Win64EH::UOP_Context, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveFReg, llvm::Win64EH::UOP_SaveFRegP, llvm::Win64EH::UOP_SaveFRegPX, llvm::Win64EH::UOP_SaveFRegX, llvm::Win64EH::UOP_SaveLRPair, llvm::Win64EH::UOP_SaveNext, llvm::Win64EH::UOP_SaveR19R20X, llvm::Win64EH::UOP_SaveReg, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, llvm::Win64EH::UOP_SaveRegX, llvm::Win64EH::UOP_SetFP, and llvm::Win64EH::UOP_TrapFrame.
Referenced by ARM64EmitUnwindInfo().
ARM64EmitUnwindInfo()
static void ARM64EmitUnwindInfo (MCStreamer & streamer, WinEH::FrameInfo * info, bool TryPacked = true) static
Definition at line 928 of file MCWin64EH.cpp.
References ARM64CountOfUnwindCodes(), ARM64EmitUnwindCode(), assert(), checkARM64PackedEpilog(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), FindMatchingEpilog(), GetAbsDifference(), getARM64OffsetInProlog(), llvm::MCStreamer::getContext(), I, info, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), llvm::report_fatal_error(), llvm::MCContext::reportError(), simplifyARM64Opcodes(), tryARM64PackedUnwind(), and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::ARM64UnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo().
ARMCountOfInstructionBytes()
static uint32_t ARMCountOfInstructionBytes (ArrayRef< WinEH::Instruction > Insns, bool * HasCustom = nullptr) static
Definition at line 1200 of file MCWin64EH.cpp.
References llvm::Count, I, llvm_unreachable, llvm::Win64EH::UOP_AllocHuge, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_Custom, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFRegD0D15, llvm::Win64EH::UOP_SaveFRegD16D31, llvm::Win64EH::UOP_SaveFRegD8D15, llvm::Win64EH::UOP_SaveLR, llvm::Win64EH::UOP_SaveRegMask, llvm::Win64EH::UOP_SaveRegsR4R7LR, llvm::Win64EH::UOP_SaveSP, llvm::Win64EH::UOP_WideAllocHuge, llvm::Win64EH::UOP_WideAllocLarge, llvm::Win64EH::UOP_WideAllocMedium, llvm::Win64EH::UOP_WideEndNop, llvm::Win64EH::UOP_WideNop, llvm::Win64EH::UOP_WideSaveRegMask, and llvm::Win64EH::UOP_WideSaveRegsR4R11LR.
Referenced by checkARMInstructions(), checkARMPackedEpilog(), and tryARMPackedUnwind().
ARMCountOfUnwindCodes()
static uint32_t ARMCountOfUnwindCodes (ArrayRef< WinEH::Instruction > Insns) static
Definition at line 1129 of file MCWin64EH.cpp.
References llvm::Count, I, llvm_unreachable, llvm::Win64EH::UOP_AllocHuge, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_Custom, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFRegD0D15, llvm::Win64EH::UOP_SaveFRegD16D31, llvm::Win64EH::UOP_SaveFRegD8D15, llvm::Win64EH::UOP_SaveLR, llvm::Win64EH::UOP_SaveRegMask, llvm::Win64EH::UOP_SaveRegsR4R7LR, llvm::Win64EH::UOP_SaveSP, llvm::Win64EH::UOP_WideAllocHuge, llvm::Win64EH::UOP_WideAllocLarge, llvm::Win64EH::UOP_WideAllocMedium, llvm::Win64EH::UOP_WideEndNop, llvm::Win64EH::UOP_WideNop, llvm::Win64EH::UOP_WideSaveRegMask, and llvm::Win64EH::UOP_WideSaveRegsR4R11LR.
Referenced by ARMEmitUnwindInfo(), checkARMPackedEpilog(), and getARMOffsetInProlog().
ARMEmitRuntimeFunction()
static void ARMEmitRuntimeFunction (MCStreamer & streamer, const WinEH::FrameInfo * info) static
Definition at line 2208 of file MCWin64EH.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCStreamer::emitInt32(), EmitSymbolRefWithOfs(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MCStreamer::getContext(), info, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::ARM64UnwindEmitter::Emit(), and llvm::Win64EH::ARMUnwindEmitter::Emit().
ARMEmitUnwindCode()
static void ARMEmitUnwindCode (MCStreamer & streamer, const WinEH::Instruction & inst) static
Definition at line 1297 of file MCWin64EH.cpp.
References assert(), llvm::MCStreamer::emitInt8(), llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AllocHuge, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_Custom, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFRegD0D15, llvm::Win64EH::UOP_SaveFRegD16D31, llvm::Win64EH::UOP_SaveFRegD8D15, llvm::Win64EH::UOP_SaveLR, llvm::Win64EH::UOP_SaveRegMask, llvm::Win64EH::UOP_SaveRegsR4R7LR, llvm::Win64EH::UOP_SaveSP, llvm::Win64EH::UOP_WideAllocHuge, llvm::Win64EH::UOP_WideAllocLarge, llvm::Win64EH::UOP_WideAllocMedium, llvm::Win64EH::UOP_WideEndNop, llvm::Win64EH::UOP_WideNop, llvm::Win64EH::UOP_WideSaveRegMask, and llvm::Win64EH::UOP_WideSaveRegsR4R11LR.
Referenced by ARMEmitUnwindInfo().
ARMEmitUnwindInfo()
static void ARMEmitUnwindInfo (MCStreamer & streamer, WinEH::FrameInfo * info, bool TryPacked = true) static
Definition at line 1968 of file MCWin64EH.cpp.
References ARMCountOfUnwindCodes(), ARMEmitUnwindCode(), assert(), checkARMInstructions(), checkARMPackedEpilog(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createOr(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), Epilog, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), FindMatchingEpilog(), getARMOffsetInProlog(), llvm::MCStreamer::getContext(), llvm::MCSymbol::getName(), GetOptionalAbsDifference(), GetSubDivExpr(), I, info, isARMTerminator(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), llvm::report_fatal_error(), llvm::MCContext::reportError(), tryARMPackedUnwind(), and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::ARMUnwindEmitter::Emit(), and llvm::Win64EH::ARMUnwindEmitter::EmitUnwindInfo().
checkARM64PackedEpilog()
static int checkARM64PackedEpilog (MCStreamer & streamer, WinEH::FrameInfo * info, int PrologCodeBytes) static
Definition at line 652 of file MCWin64EH.cpp.
References ARM64CountOfUnwindCodes(), Epilog, GetAbsDifference(), getARM64OffsetInProlog(), info, and Offset.
Referenced by ARM64EmitUnwindInfo().
checkARMInstructions()
static void checkARMInstructions (MCStreamer & Streamer, ArrayRef< WinEH::Instruction > Insns, const MCSymbol * Begin, const MCSymbol * End, StringRef Name, StringRef Type) static
Definition at line 1259 of file MCWin64EH.cpp.
References ARMCountOfInstructionBytes(), llvm::MCStreamer::getContext(), GetOptionalAbsDifference(), Name, and llvm::MCContext::reportError().
Referenced by ARMEmitUnwindInfo().
checkARMPackedEpilog()
static int checkARMPackedEpilog (MCStreamer & streamer, WinEH::FrameInfo * info, int PrologCodeBytes) static
Definition at line 1469 of file MCWin64EH.cpp.
References ARMCountOfInstructionBytes(), ARMCountOfUnwindCodes(), llvm::WinEH::FrameInfo::Epilog::Condition, Epilog, getARMOffsetInProlog(), GetOptionalAbsDifference(), info, llvm::WinEH::FrameInfo::Epilog::Instructions, and Offset.
Referenced by ARMEmitUnwindInfo().
CountOfUnwindCodes()
static uint8_t CountOfUnwindCodes (std::vector< WinEH::Instruction > & Insns) static
Definition at line 26 of file MCWin64EH.cpp.
References llvm::Count, I, llvm_unreachable, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_PushNonVol, llvm::Win64EH::UOP_SaveNonVol, llvm::Win64EH::UOP_SaveNonVolBig, llvm::Win64EH::UOP_SaveXMM128, llvm::Win64EH::UOP_SaveXMM128Big, and llvm::Win64EH::UOP_SetFPReg.
Referenced by EmitUnwindInfo().
EmitAbsDifference()
static void EmitAbsDifference (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS) static
Definition at line 54 of file MCWin64EH.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::emitValue(), and llvm::MCStreamer::getContext().
Referenced by EmitUnwindCode(), and EmitUnwindInfo().
EmitRuntimeFunction()
static void EmitRuntimeFunction (MCStreamer & streamer, const WinEH::FrameInfo * info) static
Definition at line 144 of file MCWin64EH.cpp.
References llvm::MCSymbolRefExpr::create(), EmitSymbolRefWithOfs(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MCStreamer::getContext(), info, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and EmitUnwindInfo().
EmitSymbolRefWithOfs()
static void EmitSymbolRefWithOfs (MCStreamer & streamer, const MCSymbol * Base, const MCSymbol * Other) static
Definition at line 131 of file MCWin64EH.cpp.
References llvm::sampleprof::Base, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::getContext(), llvm::Other, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by ARMEmitRuntimeFunction(), and EmitRuntimeFunction().
EmitUnwindCode()
static void EmitUnwindCode (MCStreamer & streamer, const MCSymbol * begin, WinEH::Instruction & inst) static
Definition at line 63 of file MCWin64EH.cpp.
References EmitAbsDifference(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt8(), llvm::WinEH::Instruction::Label, llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_PushMachFrame, llvm::Win64EH::UOP_PushNonVol, llvm::Win64EH::UOP_SaveNonVol, llvm::Win64EH::UOP_SaveNonVolBig, llvm::Win64EH::UOP_SaveXMM128, llvm::Win64EH::UOP_SaveXMM128Big, and llvm::Win64EH::UOP_SetFPReg.
Referenced by EmitUnwindInfo().
EmitUnwindInfo()
static void EmitUnwindInfo (MCStreamer & streamer, WinEH::FrameInfo * info) static
Definition at line 156 of file MCWin64EH.cpp.
References assert(), CountOfUnwindCodes(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), EmitAbsDifference(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), EmitRuntimeFunction(), EmitUnwindCode(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MCStreamer::getContext(), info, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UNW_ChainInfo, llvm::Win64EH::UNW_ExceptionHandler, llvm::Win64EH::UNW_TerminateHandler, llvm::Win64EH::UOP_SetFPReg, and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
Referenced by llvm::Win64EH::UnwindEmitter::EmitUnwindInfo().
FindMatchingEpilog()
static MCSymbol * FindMatchingEpilog (const std::vector< WinEH::Instruction > & EpilogInstrs, const std::vector< MCSymbol * > & Epilogs, const WinEH::FrameInfo * info) static
Definition at line 543 of file MCWin64EH.cpp.
References assert(), info, and llvm::Match.
Referenced by ARM64EmitUnwindInfo(), and ARMEmitUnwindInfo().
GetAbsDifference()
static int64_t GetAbsDifference (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS) static
Definition at line 283 of file MCWin64EH.cpp.
References GetOptionalAbsDifference(), and llvm::report_fatal_error().
Referenced by ARM64EmitUnwindInfo(), and checkARM64PackedEpilog().
getARM64OffsetInProlog()
static int getARM64OffsetInProlog (const std::vector< WinEH::Instruction > & Prolog, const std::vector< WinEH::Instruction > & Epilog) static
Definition at line 632 of file MCWin64EH.cpp.
References ARM64CountOfUnwindCodes(), Epilog, I, and Prolog.
Referenced by ARM64EmitUnwindInfo(), and checkARM64PackedEpilog().
getARMOffsetInProlog()
static int getARMOffsetInProlog (const std::vector< WinEH::Instruction > & Prolog, const std::vector< WinEH::Instruction > & Epilog, bool CanTweakProlog) static
Definition at line 1433 of file MCWin64EH.cpp.
References ARMCountOfUnwindCodes(), Epilog, I, Prolog, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, and llvm::Win64EH::UOP_WideEndNop.
Referenced by ARMEmitUnwindInfo(), and checkARMPackedEpilog().
GetOptionalAbsDifference()
static Optional< int64_t > GetOptionalAbsDifference (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS) static
Definition at line 266 of file MCWin64EH.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), and llvm::None.
Referenced by ARMEmitUnwindInfo(), checkARMInstructions(), checkARMPackedEpilog(), GetAbsDifference(), and tryARMPackedUnwind().
GetSubDivExpr()
static const MCExpr * GetSubDivExpr (MCStreamer & Streamer, const MCSymbol * LHS, const MCSymbol * RHS, int Div) static
Definition at line 254 of file MCWin64EH.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createDiv(), llvm::MCBinaryExpr::createSub(), and llvm::MCStreamer::getContext().
Referenced by ARMEmitUnwindInfo().
isARMTerminator()
static bool isARMTerminator (const WinEH::Instruction & inst) static
Definition at line 1284 of file MCWin64EH.cpp.
References llvm::WinEH::Instruction::Operation, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, and llvm::Win64EH::UOP_WideEndNop.
Referenced by ARMEmitUnwindInfo().
parseRegMask()
static bool parseRegMask (unsigned Mask, bool & HasLR, bool & HasR11, unsigned & Folded, int & IntRegs) static
Definition at line 1526 of file MCWin64EH.cpp.
References IntRegs, and N.
Referenced by tryARMPackedUnwind().
simplifyARM64Opcodes()
static void simplifyARM64Opcodes (std::vector< WinEH::Instruction > & Instructions, bool Reverse) static
Definition at line 568 of file MCWin64EH.cpp.
References llvm::Win64EH::UOP_AddFP, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveNext, llvm::Win64EH::UOP_SaveR19R20X, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, and llvm::Win64EH::UOP_SetFP.
Referenced by ARM64EmitUnwindInfo().
tryARM64PackedUnwind()
static bool tryARM64PackedUnwind (WinEH::FrameInfo * info, uint32_t FuncLength, int PackedEpilogOffset) static
Definition at line 693 of file MCWin64EH.cpp.
References assert(), FloatRegs, H, info, IntRegs, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AllocMedium, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFPLR, llvm::Win64EH::UOP_SaveFPLRX, llvm::Win64EH::UOP_SaveFReg, llvm::Win64EH::UOP_SaveFRegP, llvm::Win64EH::UOP_SaveFRegPX, llvm::Win64EH::UOP_SaveFRegX, llvm::Win64EH::UOP_SaveLRPair, llvm::Win64EH::UOP_SaveNext, llvm::Win64EH::UOP_SaveR19R20X, llvm::Win64EH::UOP_SaveReg, llvm::Win64EH::UOP_SaveRegP, llvm::Win64EH::UOP_SaveRegPX, llvm::Win64EH::UOP_SaveRegX, and llvm::Win64EH::UOP_SetFP.
Referenced by ARM64EmitUnwindInfo().
tryARMPackedUnwind()
static bool tryARMPackedUnwind (MCStreamer & streamer, WinEH::FrameInfo * info, uint32_t FuncLength) static
Definition at line 1566 of file MCWin64EH.cpp.
References ARMCountOfInstructionBytes(), assert(), llvm::CallingConv::C, llvm::WinEH::FrameInfo::Epilog::Condition, Epilog, FloatRegs, GetOptionalAbsDifference(), H, info, llvm::WinEH::FrameInfo::Epilog::Instructions, IntRegs, LLVM_FALLTHROUGH, llvm_unreachable, llvm::WinEH::Instruction::Offset, llvm::WinEH::Instruction::Operation, parseRegMask(), Reg, llvm::WinEH::Instruction::Register, llvm::Win64EH::UOP_AllocHuge, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocSmall, llvm::Win64EH::UOP_Custom, llvm::Win64EH::UOP_End, llvm::Win64EH::UOP_EndNop, llvm::Win64EH::UOP_Nop, llvm::Win64EH::UOP_SaveFRegD0D15, llvm::Win64EH::UOP_SaveFRegD16D31, llvm::Win64EH::UOP_SaveFRegD8D15, llvm::Win64EH::UOP_SaveLR, llvm::Win64EH::UOP_SaveRegMask, llvm::Win64EH::UOP_SaveRegsR4R7LR, llvm::Win64EH::UOP_SaveSP, llvm::Win64EH::UOP_WideAllocHuge, llvm::Win64EH::UOP_WideAllocLarge, llvm::Win64EH::UOP_WideAllocMedium, llvm::Win64EH::UOP_WideEndNop, llvm::Win64EH::UOP_WideNop, llvm::Win64EH::UOP_WideSaveRegMask, and llvm::Win64EH::UOP_WideSaveRegsR4R11LR.
Referenced by ARMEmitUnwindInfo().