LLVM: lib/Analysis/MemoryProfileInfo.cpp File Reference
MemoryProfileInfo.cpp File Reference
#include "llvm/Analysis/MemoryProfileInfo.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "memory-profile-info"
Functions
static std::string getAllocTypeAttributeString (AllocationType Type)
static void addAllocTypeAttribute (LLVMContext &Ctx, CallBase *CI, AllocationType AllocType)
static bool hasSingleAllocType (uint8_t AllocTypes)
static MDNode * createMIBNode (LLVMContext &Ctx, std::vector< uint64_t > &MIBCallStack, AllocationType AllocType)
Variables
cl::opt< float > MemProfAccessesPerByteColdThreshold ("memprof-accesses-per-byte-cold-threshold", cl::init(10.0), cl::Hidden, cl::desc("The threshold the accesses per byte must be under to consider " "an allocation cold"))
cl::opt< unsigned > MemProfMinLifetimeColdThreshold ("memprof-min-lifetime-cold-threshold", cl::init(200), cl::Hidden, cl::desc("The minimum lifetime (s) for an allocation to be considered " "cold"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memory-profile-info"
Definition at line 19 of file MemoryProfileInfo.cpp.
Function Documentation
addAllocTypeAttribute()
static void addAllocTypeAttribute (LLVMContext & Ctx, CallBase * CI, AllocationType AllocType) static
Definition at line 87 of file MemoryProfileInfo.cpp.
References A, llvm::CallBase::addFnAttr(), llvm::Attribute::get(), and getAllocTypeAttributeString().
Referenced by llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().
createMIBNode()
static MDNode * createMIBNode (LLVMContext & Ctx, std::vector< uint64_t > & MIBCallStack, AllocationType AllocType) static
Definition at line 146 of file MemoryProfileInfo.cpp.
References llvm::memprof::buildCallstackMetadata(), llvm::MDNode::get(), llvm::MDString::get(), and getAllocTypeAttributeString().
getAllocTypeAttributeString()
static std::string getAllocTypeAttributeString (AllocationType Type) static
Definition at line 73 of file MemoryProfileInfo.cpp.
References assert(), and llvm_unreachable.
Referenced by addAllocTypeAttribute(), and createMIBNode().
hasSingleAllocType()
static bool hasSingleAllocType (uint8_t AllocTypes) static
Definition at line 94 of file MemoryProfileInfo.cpp.
References assert(), and llvm::countPopulation().
Referenced by llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().
Variable Documentation
MemProfAccessesPerByteColdThreshold
cl::opt< float > MemProfAccessesPerByteColdThreshold("memprof-accesses-per-byte-cold-threshold", cl::init(10.0), cl::Hidden, cl::desc("The threshold the accesses per byte must be under to consider " "an allocation cold")) ("memprof-accesses-per-byte-cold-threshold" , cl::init(10.0) , cl::Hidden , cl::desc("The threshold the accesses per byte must be under to consider " "an allocation cold"))
Referenced by llvm::memprof::getAllocType().
MemProfMinLifetimeColdThreshold
cl::opt< unsigned > MemProfMinLifetimeColdThreshold("memprof-min-lifetime-cold-threshold", cl::init(200), cl::Hidden, cl::desc("The minimum lifetime (s) for an allocation to be considered " "cold")) ("memprof-min-lifetime-cold-threshold" , cl::init(200) , cl::Hidden , cl::desc("The minimum lifetime (s) for an allocation to be considered " "cold"))
Referenced by llvm::memprof::getAllocType().