LLVM: lib/Target/Mips/MipsOs16.cpp File Reference
MipsOs16.cpp File Reference
#include "Mips.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "mips-os16"
Functions
static bool needsFPFromSig (Function &F)
static bool needsFP (Function &F)
Variables
static cl::opt< std::string > Mips32FunctionMask ("mips32-function-mask", cl::init(""), cl::desc("Force function to be mips32"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-os16"
Definition at line 23 of file MipsOs16.cpp.
Function Documentation
needsFP()
static bool needsFP (Function & F) static
Definition at line 74 of file MipsOs16.cpp.
References llvm::dbgs(), llvm::dyn_cast(), E, F, llvm::Instruction::getOpcode(), I, LLVM_DEBUG, and needsFPFromSig().
needsFPFromSig()
static bool needsFPFromSig (Function & F) static
Definition at line 50 of file MipsOs16.cpp.
References Arg, F, and llvm::Type::getTypeID().
Referenced by needsFP().
Variable Documentation
Mips32FunctionMask
cl::opt< std::string > Mips32FunctionMask("mips32-function-mask", cl::init(""), cl::desc("Force function to be mips32"), cl::Hidden) ("mips32-function-mask" , cl::init("") , cl::desc("Force function to be mips32") , cl::Hidden) static