LLVM: lib/Target/Mips/MipsMachineFunction.cpp File Reference
MipsMachineFunction.cpp File Reference
#include "MipsMachineFunction.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
Functions
static const TargetRegisterClass & getGlobalBaseRegClass (MachineFunction &MF)
Variables
static cl::opt< bool > FixGlobalBaseReg ("mips-fix-global-base-reg", cl::Hidden, cl::init(true), cl::desc("Always use $gp as the global base register."))
Function Documentation
getGlobalBaseRegClass()
static const TargetRegisterClass & getGlobalBaseRegClass (MachineFunction & MF) static
Definition at line 38 of file MipsMachineFunction.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), and TM.
Referenced by llvm::MipsFunctionInfo::getGlobalBaseReg().
Variable Documentation
FixGlobalBaseReg
cl::opt< bool > FixGlobalBaseReg("mips-fix-global-base-reg", cl::Hidden, cl::init(true), cl::desc("Always use $gp as the global base register.")) ("mips-fix-global-base-reg" , cl::Hidden , cl::init(true) , cl::desc("Always use $gp as the global base register.")) static