LLVM: lib/Target/Mips/MipsSERegisterInfo.cpp File Reference
MipsSERegisterInfo.cpp File Reference
#include "MipsSERegisterInfo.h"
#include "Mips.h"
#include "MipsMachineFunction.h"
#include "MipsSEInstrInfo.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
Macros
#define DEBUG_TYPE "mips-reg-info"
Functions
static unsigned getLoadStoreOffsetSizeInBits (const unsigned Opcode, MachineOperand MO)
Get the size of the offset supported by the given load/store/inline asm.
static unsigned getLoadStoreOffsetAlign (const unsigned Opcode)
Get the scale factor applied to the immediate in the given load/store.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-reg-info"
Definition at line 39 of file MipsSERegisterInfo.cpp.
Function Documentation
getLoadStoreOffsetAlign()
static unsigned getLoadStoreOffsetAlign (const unsigned Opcode) inline static
Get the scale factor applied to the immediate in the given load/store.
Definition at line 129 of file MipsSERegisterInfo.cpp.
getLoadStoreOffsetSizeInBits()
static unsigned getLoadStoreOffsetSizeInBits (const unsigned Opcode, MachineOperand MO) inline static
Get the size of the offset supported by the given load/store/inline asm.
The result includes the effects of any scale factors applied to the instruction immediate.
Definition at line 65 of file MipsSERegisterInfo.cpp.
References llvm::InlineAsm::Constraint_ZC, llvm::MachineOperand::getImm(), llvm::InlineAsm::getMemoryConstraintID(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MipsSubtarget::hasMips32r6(), and llvm::MipsSubtarget::inMicroMipsMode().