LLVM: lib/Target/Mips/MipsSEFrameLowering.cpp File Reference
MipsSEFrameLowering.cpp File Reference
#include "MipsSEFrameLowering.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MipsMachineFunction.h"
#include "MipsRegisterInfo.h"
#include "MipsSEInstrInfo.h"
#include "MipsSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include <cstdint>
#include <utility>
#include <vector>
Functions
static std::pair< unsigned, unsigned > getMFHiLoOpc (unsigned Src)
static void setAliasRegs (MachineFunction &MF, BitVector &SavedRegs, unsigned Reg)
Mark Reg and all registers aliasing it in the bitset.
Function Documentation
getMFHiLoOpc()
static std::pair< unsigned, unsigned > getMFHiLoOpc (unsigned Src) static
Definition at line 49 of file MipsSEFrameLowering.cpp.
References contains().
setAliasRegs()
static void setAliasRegs (MachineFunction & MF, BitVector & SavedRegs, unsigned Reg) static
Mark Reg and all registers aliasing it in the bitset.
Definition at line 851 of file MipsSEFrameLowering.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MCRegAliasIterator::isValid(), llvm::BitVector::set(), and TRI.
Referenced by llvm::MipsSEFrameLowering::determineCalleeSaves().