LLVM: lib/DebugInfo/MSF/MSFBuilder.cpp File Reference
MSFBuilder.cpp File Reference
#include "llvm/DebugInfo/MSF/MSFBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/DebugInfo/MSF/MSFError.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileOutputBuffer.h"
#include "llvm/Support/FormatVariadic.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <memory>
#include <utility>
#include <vector>
Functions
static void commitFpm (WritableBinaryStream &MsfBuffer, const MSFLayout &Layout, BumpPtrAllocator &Allocator)
Variables
static const uint32_t kSuperBlockBlock = 0
static const uint32_t kFreePageMap0Block = 1
static const uint32_t kFreePageMap1Block = 2
static const uint32_t kNumReservedPages = 3
static const uint32_t kDefaultFreePageMap = kFreePageMap1Block
static const uint32_t kDefaultBlockMapAddr = kNumReservedPages
Function Documentation
commitFpm()
static void commitFpm (WritableBinaryStream & MsfBuffer, const MSFLayout & Layout, BumpPtrAllocator & Allocator) static
Definition at line 312 of file MSFBuilder.cpp.
References assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::cantFail(), llvm::msf::WritableMappedBlockStream::createFpmStream(), llvm::msf::MSFLayout::FreePageMap, I, llvm::msf::SuperBlock::NumBlocks, llvm::msf::MSFLayout::SB, llvm::BitVector::test(), and llvm::BinaryStreamWriter::writeObject().
Referenced by llvm::msf::MSFBuilder::commit().
Variable Documentation
kDefaultBlockMapAddr
const uint32_t kDefaultBlockMapAddr = kNumReservedPages static
Definition at line 37 of file MSFBuilder.cpp.
kDefaultFreePageMap
const uint32_t kDefaultFreePageMap = kFreePageMap1Block static
Definition at line 36 of file MSFBuilder.cpp.
kFreePageMap0Block
const uint32_t kFreePageMap0Block = 1 static
Definition at line 32 of file MSFBuilder.cpp.
kFreePageMap1Block
const uint32_t kFreePageMap1Block = 2 static
Definition at line 33 of file MSFBuilder.cpp.
kNumReservedPages
const uint32_t kNumReservedPages = 3 static
Definition at line 34 of file MSFBuilder.cpp.
kSuperBlockBlock
const uint32_t kSuperBlockBlock = 0 static
Definition at line 31 of file MSFBuilder.cpp.