LLVM: lib/DebugInfo/PDB/Native/NativeExeSymbol.cpp File Reference
NativeExeSymbol.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/NativeExeSymbol.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/PDB/IPDBEnumChildren.h"
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/DebugInfo/PDB/Native/InfoStream.h"
#include "llvm/DebugInfo/PDB/Native/NativeEnumModules.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/SymbolCache.h"
Functions
static DbiStream * getDbiStreamPtr (NativeSession &Session)
Function Documentation
getDbiStreamPtr()
static DbiStream * getDbiStreamPtr (NativeSession & Session) static
Definition at line 23 of file NativeExeSymbol.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), llvm::pdb::PDBFile::getPDBDbiStream(), llvm::pdb::NativeSession::getPDBFile(), and llvm::Expected< T >::takeError().
Referenced by llvm::pdb::NativeSession::getModuleDebugStream(), and llvm::pdb::NativeSession::getRVAFromSectOffset().