LLVM: lib/Target/NVPTX/NVPTXPeephole.cpp File Reference
NVPTXPeephole.cpp File Reference
#include "NVPTX.h"
#include "NVPTXRegisterInfo.h"
#include "NVPTXSubtarget.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "nvptx-peephole"
Functions
void llvm::initializeNVPTXPeepholePass (PassRegistry &)
static bool isCVTAToLocalCombinationCandidate (MachineInstr &Root)
static void CombineCVTAToLocal (MachineInstr &Root)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-peephole"
Definition at line 45 of file NVPTXPeephole.cpp.
Function Documentation
CombineCVTAToLocal()
static void CombineCVTAToLocal (MachineInstr & Root) static
Definition at line 109 of file NVPTXPeephole.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::NVPTXRegisterInfo::getFrameLocalRegister(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineBasicBlock::insert(), MBB, MRI, and TII.
isCVTAToLocalCombinationCandidate()
static bool isCVTAToLocalCombinationCandidate (MachineInstr & Root) static
Definition at line 75 of file NVPTXPeephole.cpp.
References llvm::MachineBasicBlock::getParent(), llvm::NVPTXSubtarget::getRegisterInfo(), if(), MBB, and MRI.