LLVM: lib/Target/NVPTX/NVPTXLowerArgs.cpp File Reference
NVPTXLowerArgs.cpp File Reference
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "NVPTX.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include <queue>
Classes
struct IP
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "nvptx-lower-args"
Functions
void llvm::initializeNVPTXLowerArgsPass (PassRegistry &)
INITIALIZE_PASS (NVPTXLowerArgs, "nvptx-lower-args", "Lower arguments (NVPTX)", false, false) static void convertToParamAS(Value *OldUser
assert (I &&"OldUser must be an instruction")
while (!ItemsToConvert.empty())
for (Instruction *I :llvm::reverse(InstructionsToDelete)) I -> eraseFromParent()
static void adjustByValArgAlignment (Argument *Arg, Value *ArgInParamAS, const NVPTXTargetLowering *TLI)
Variables
Value * Param
SmallVector< IP > ItemsToConvert = {{I, Param}}
SmallVector< Instruction * > InstructionsToDelete
auto CloneInstInParamAS
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-lower-args"
Definition at line 103 of file NVPTXLowerArgs.cpp.
Function Documentation
adjustByValArgAlignment()
static void adjustByValArgAlignment (Argument * Arg, Value * ArgInParamAS, const NVPTXTargetLowering * TLI) static
Definition at line 234 of file NVPTXLowerArgs.cpp.
References llvm::ADDRESS_SPACE_PARAM, Arg, assert(), llvm::dbgs(), DL, llvm::dyn_cast(), llvm::NVPTXTargetLowering::getFunctionParamOptimizedAlign(), llvm::APInt::getLimitedValue(), llvm::APInt::getZero(), llvm::greatestCommonDivisor(), I, LLVM_DEBUG, llvm_unreachable, Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::users(), and llvm::Align::value().
assert()
assert (I &&"OldUser must be an instruction")
Referenced by adjustByValArgAlignment().
for()
for (Instruction *I :llvm::reverseInstructionsToDelete) -> eraseFromParent()
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXLowerArgs , "nvptx-lower-args" , "Lower arguments (NVPTX)" , false , false)
while()
while (!ItemsToConvert. empty())
Definition at line 202 of file NVPTXLowerArgs.cpp.
References llvm::cast(), CloneInstInParamAS, I, InstructionsToDelete, ItemsToConvert, and llvm::Value::users().
Referenced by INITIALIZE_PASS().
Variable Documentation
CloneInstInParamAS
auto CloneInstInParamAS
Initial value:
= [](const IP &I) -> Value * {
    if (auto *LI = dyn_cast<LoadInst>(I.OldInstruction)) {
      LI->setOperand(0, I.NewParam);
      return LI;
    }
    if (auto *GEP = dyn_cast<GetElementPtrInst>(I.OldInstruction)) {
      SmallVector<Value *, 4> Indices(GEP->indices());
      auto *NewGEP = GetElementPtrInst::Create(GEP->getSourceElementType(),
                                               I.NewParam, Indices,
                                               GEP->getName(), GEP);
      NewGEP->setIsInBounds(GEP->isInBounds());
      return NewGEP;
    }
    if (auto *BC = dyn_cast<BitCastInst>(I.OldInstruction)) {
      auto *NewBCType = PointerType::getWithSamePointeeType(
          cast<PointerType>(BC->getType()), ADDRESS_SPACE_PARAM);
      return BitCastInst::Create(BC->getOpcode(), I.NewParam, NewBCType,
                                 BC->getName(), BC);
    }
    if (auto *ASC = dyn_cast<AddrSpaceCastInst>(I.OldInstruction)) {
      assert(ASC->getDestAddressSpace() == ADDRESS_SPACE_PARAM);
      (void)ASC;
      return I.NewParam;
    }
    llvm_unreachable("Unsupported instruction");
  }
Definition at line 174 of file NVPTXLowerArgs.cpp.
Referenced by while().
InstructionsToDelete
SmallVector<Instruction *> InstructionsToDelete
Definition at line 172 of file NVPTXLowerArgs.cpp.
Referenced by while().
ItemsToConvert
SmallVector<IP> ItemsToConvert = {{I, Param}}
Definition at line 171 of file NVPTXLowerArgs.cpp.
Referenced by while().
Param
Value* Param
Initial value:
{
  Instruction *I = dyn_cast<Instruction>(OldUser)
Definition at line 164 of file NVPTXLowerArgs.cpp.