LLVM: lib/Transforms/Scalar/PartiallyInlineLibCalls.cpp File Reference
PartiallyInlineLibCalls.cpp File Reference
#include "llvm/Transforms/Scalar/PartiallyInlineLibCalls.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "partially-inline-libcalls"
Functions
DEBUG_COUNTER (PILCounter, "partially-inline-libcalls-transform", "Controls transformations in partially-inline-libcalls")
static bool optimizeSQRT (CallInst *Call, Function *CalledFunc, BasicBlock &CurrBB, Function::iterator &BB, const TargetTransformInfo *TTI, DomTreeUpdater *DTU)
static bool runPartiallyInlineLibCalls (Function &F, TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, DominatorTree *DT)
INITIALIZE_PASS_BEGIN (PartiallyInlineLibCallsLegacyPass, "partially-inline-libcalls", "Partially inline calls to library functions", false, false) INITIALIZE_PASS_END(PartiallyInlineLibCallsLegacyPass
Variables
partially inline libcalls
partially inline Partially calls to library functions
partially inline Partially calls to library false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "partially-inline-libcalls"
Definition at line 28 of file PartiallyInlineLibCalls.cpp.
Function Documentation
DEBUG_COUNTER()
DEBUG_COUNTER (PILCounter , "partially-inline-libcalls-transform" , "Controls transformations in partially-inline-libcalls")
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PartiallyInlineLibCallsLegacyPass , "partially-inline-libcalls" , "Partially inline calls to library functions" , false , false)
optimizeSQRT()
static bool optimizeSQRT (CallInst * Call, Function * CalledFunc, BasicBlock & CurrBB, Function::iterator & BB, const TargetTransformInfo * TTI, DomTreeUpdater * DTU) static
Definition at line 33 of file PartiallyInlineLibCalls.cpp.
References llvm::CallBase::addFnAttr(), llvm::PHINode::addIncoming(), llvm::BasicBlock::begin(), Builder, Call, llvm::cast(), llvm::Instruction::clone(), llvm::ConstantFP::get(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Instruction::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::TargetTransformInfo::isFCmpOrdCheaperThanFCmpZero(), llvm::CallBase::onlyReadsMemory(), llvm::CallBase::removeFnAttr(), llvm::Value::replaceAllUsesWith(), llvm::Value::setName(), llvm::DebugCounter::shouldExecute(), and llvm::SplitBlockAndInsertIfThen().
Referenced by runPartiallyInlineLibCalls().
runPartiallyInlineLibCalls()
static bool runPartiallyInlineLibCalls (Function & F, TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, DominatorTree * DT) static
Definition at line 104 of file PartiallyInlineLibCalls.cpp.
References Call, Changed, llvm::dyn_cast(), llvm::Optional< T >::emplace(), F, llvm::CallBase::getCalledFunction(), llvm::TargetLibraryInfo::getLibFunc(), llvm::Optional< T >::getPointer(), llvm::Value::getType(), llvm::TargetLibraryInfo::has(), llvm::GlobalValue::hasLocalLinkage(), llvm::TargetTransformInfo::haveFastSqrt(), llvm::CallInst::isMustTailCall(), llvm::CallBase::isNoBuiltin(), llvm::CallBase::isStrictFP(), and optimizeSQRT().
Referenced by llvm::PartiallyInlineLibCallsPass::run().
Variable Documentation
false
partially inline Partially calls to library false
Definition at line 213 of file PartiallyInlineLibCalls.cpp.
functions
partially inline Partially calls to library functions inline
Definition at line 213 of file PartiallyInlineLibCalls.cpp.
libcalls
partially inline libcalls
Definition at line 212 of file PartiallyInlineLibCalls.cpp.