LLVM: lib/Analysis/PHITransAddr.cpp File Reference
PHITransAddr.cpp File Reference
#include "llvm/Analysis/PHITransAddr.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool CanPHITrans (Instruction *Inst)
static bool VerifySubExpr (Value *Expr, SmallVectorImpl< Instruction * > &InstInputs)
static void RemoveInstInputs (Value *V, SmallVectorImpl< Instruction * > &InstInputs)
Variables
static cl::opt< bool > EnableAddPhiTranslation ("gvn-add-phi-translation", cl::init(false), cl::Hidden, cl::desc("Enable phi-translation of add instructions"))
Function Documentation
CanPHITrans()
static bool CanPHITrans (Instruction * Inst) static
Definition at line 28 of file PHITransAddr.cpp.
References llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::isa(), and llvm::isSafeToSpeculativelyExecute().
Referenced by llvm::PHITransAddr::IsPotentiallyPHITranslatable(), and VerifySubExpr().
RemoveInstInputs()
static void RemoveInstInputs (Value * V, SmallVectorImpl< Instruction * > & InstInputs) static
Definition at line 122 of file PHITransAddr.cpp.
References assert(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::find(), I, llvm::isa(), and RemoveInstInputs().
Referenced by RemoveInstInputs().
VerifySubExpr()
static bool VerifySubExpr (Value * Expr, SmallVectorImpl< Instruction * > & InstInputs) static
Definition at line 57 of file PHITransAddr.cpp.
References CanPHITrans(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::errs(), llvm::find(), I, llvm_unreachable, and VerifySubExpr().
Referenced by llvm::PHITransAddr::Verify(), and VerifySubExpr().
Variable Documentation
EnableAddPhiTranslation
cl::opt< bool > EnableAddPhiTranslation("gvn-add-phi-translation", cl::init(false), cl::Hidden, cl::desc("Enable phi-translation of add instructions")) ("gvn-add-phi-translation" , cl::init(false) , cl::Hidden , cl::desc("Enable phi-translation of add instructions")) static