LLVM: lib/Target/PowerPC/PPCCTRLoopsVerify.cpp File Reference
PPCCTRLoopsVerify.cpp File Reference
#include <vector>
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "PPC.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/ilist_iterator.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBundleIterator.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/Register.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/PassRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GenericDomTreeConstruction.h"
#include "llvm/Support/Printable.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "ppc-ctrloops-verify"
Functions
INITIALIZE_PASS_BEGIN (PPCCTRLoopsVerify, "ppc-ctr-loops-verify", "PowerPC CTR Loops Verify", false, false) INITIALIZE_PASS_END(PPCCTRLoopsVerify
static bool clobbersCTR (const MachineInstr &MI)
static bool verifyCTRBranch (MachineBasicBlock *MBB, MachineBasicBlock::iterator I)
Variables
ppc ctr loops verify
ppc ctr loops PowerPC CTR Loops Verify
ppc ctr loops PowerPC CTR Loops false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-ctrloops-verify"
Definition at line 47 of file PPCCTRLoopsVerify.cpp.
Function Documentation
clobbersCTR()
static bool clobbersCTR (const MachineInstr & MI) static
Definition at line 83 of file PPCCTRLoopsVerify.cpp.
References MI.
Referenced by verifyCTRBranch().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PPCCTRLoopsVerify , "ppc-ctr-loops-verify" , "PowerPC CTR Loops Verify" , false , false)
verifyCTRBranch()
static bool verifyCTRBranch (MachineBasicBlock * MBB, MachineBasicBlock::iterator I) static
Definition at line 97 of file PPCCTRLoopsVerify.cpp.
References llvm::append_range(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), clobbersCTR(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFullName(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineBasicBlock::getParent(), I, llvm::SmallSet< T, N, C >::insert(), LLVM_DEBUG, MBB, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::predecessors(), and llvm::printMBBReference().
Variable Documentation
false
ppc ctr loops PowerPC CTR Loops false
Definition at line 77 of file PPCCTRLoopsVerify.cpp.
Verify
static void Verify
Definition at line 77 of file PPCCTRLoopsVerify.cpp.
Referenced by llvm::TargetPassConfig::addVerifyPass(), llvm::GVNPass::ValueTable::lookup(), llvm::SafepointIRVerifierPass::run(), llvm::DWARFLinker::setVerifyInputDWARF(), llvm::EngineBuilder::setVerifyModules(), and llvm::ExecutionEngine::setVerifyModules().
verify
ppc ctr loops verify
Definition at line 76 of file PPCCTRLoopsVerify.cpp.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::ARMLegalizerInfo::ARMLegalizerInfo(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::end(), llvm::AMDGPU::HSAMD::MetadataStreamerV3::end(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LazyCallGraph::RefSCC::insertInternalRefEdge(), llvm::LazyCallGraph::RefSCC::insertOutgoingEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), llvm::DWARFLinker::link(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::LazyCallGraph::RefSCC::removeOutgoingEdge(), llvm::LazyCallGraph::RefSCC::replaceNodeFunction(), llvm::ScalarEvolutionVerifierPass::run(), llvm::SPIRVLegalizerInfo::SPIRVLegalizerInfo(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToRef(), llvm::LazyCallGraph::RefSCC::switchTrivialInternalEdgeToRef(), and llvm::X86LegalizerInfo::X86LegalizerInfo().