LLVM: lib/Target/PowerPC/PPCMachineScheduler.cpp File Reference
PPCMachineScheduler.cpp File Reference
#include "PPCMachineScheduler.h"
#include "MCTargetDesc/PPCMCTargetDesc.h"
Functions
static bool isADDIInstr (const GenericScheduler::SchedCandidate &Cand)
Variables
static cl::opt< bool > DisableAddiLoadHeuristic ("disable-ppc-sched-addi-load", cl::desc("Disable scheduling addi instruction before" "load for ppc"), cl::Hidden)
static cl::opt< bool > EnableAddiHeuristic ("ppc-postra-bias-addi", cl::desc("Enable scheduling addi instruction as early" "as possible post ra"), cl::Hidden, cl::init(true))
Function Documentation
isADDIInstr()
static bool isADDIInstr (const GenericScheduler::SchedCandidate & Cand) static
Definition at line 24 of file PPCMachineScheduler.cpp.
References llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), and llvm::GenericSchedulerBase::SchedCandidate::SU.
Referenced by llvm::PPCPostRASchedStrategy::biasAddiCandidate().
Variable Documentation
DisableAddiLoadHeuristic
cl::opt< bool > DisableAddiLoadHeuristic("disable-ppc-sched-addi-load", cl::desc("Disable scheduling addi instruction before" "load for ppc"), cl::Hidden) ("disable-ppc-sched-addi-load" , cl::desc("Disable scheduling addi instruction before" "load for ppc") , cl::Hidden) static
EnableAddiHeuristic
cl::opt< bool > EnableAddiHeuristic("ppc-postra-bias-addi", cl::desc("Enable scheduling addi instruction as early" "as possible post ra"), cl::Hidden, cl::init(true)) ("ppc-postra-bias-addi" , cl::desc("Enable scheduling addi instruction as early" "as possible post ra") , cl::Hidden , cl::init(true)) static
Referenced by llvm::PPCPostRASchedStrategy::biasAddiCandidate().