LLVM: lib/Analysis/ProfileSummaryInfo.cpp File Reference
ProfileSummaryInfo.cpp File Reference
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/InitializePasses.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/Support/CommandLine.h"
Functions
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass, "profile-summary-info", "Profile summary info", false, true) ProfileSummaryInfoWrapperPass
Variables
cl::opt< int > ProfileSummaryCutoffHot
cl::opt< int > ProfileSummaryCutoffCold
cl::opt< unsigned > ProfileSummaryHugeWorkingSetSizeThreshold
cl::opt< unsigned > ProfileSummaryLargeWorkingSetSizeThreshold
cl::opt< int > ProfileSummaryHotCount
cl::opt< int > ProfileSummaryColdCount
static cl::opt< bool > PartialProfile ("partial-profile", cl::Hidden, cl::init(false), cl::desc("Specify the current profile is used as a partial profile."))
cl::opt< bool > ScalePartialSampleProfileWorkingSetSize ("scale-partial-sample-profile-working-set-size", cl::Hidden, cl::init(true), cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled."))
static cl::opt< double > PartialSampleProfileWorkingSetSizeScaleFactor ("partial-sample-profile-working-set-size-scale-factor", cl::Hidden, cl::init(0.008), cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO."))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass , "profile-summary-info" , "Profile summary info" , false , true)
Definition at line 380 of file ProfileSummaryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeProfileSummaryInfoWrapperPassPass().
Variable Documentation
PartialProfile
cl::opt< bool > PartialProfile("partial-profile", cl::Hidden, cl::init(false), cl::desc("Specify the current profile is used as a partial profile.")) ("partial-profile" , cl::Hidden , cl::init(false) , cl::desc("Specify the current profile is used as a partial profile.")) static
Referenced by llvm::ProfileSummaryInfo::hasPartialSampleProfile().
PartialSampleProfileWorkingSetSizeScaleFactor
cl::opt< double > PartialSampleProfileWorkingSetSizeScaleFactor("partial-sample-profile-working-set-size-scale-factor", cl::Hidden, cl::init(0.008), cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO.")) ("partial-sample-profile-working-set-size-scale-factor" , cl::Hidden , cl::init(0.008) , cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO.")) static
ProfileSummaryColdCount
cl::opt<int> ProfileSummaryColdCount extern
Referenced by llvm::ProfileSummaryBuilder::getColdCountThreshold().
ProfileSummaryCutoffCold
cl::opt<int> ProfileSummaryCutoffCold extern
Referenced by llvm::ProfileSummaryBuilder::getColdCountThreshold().
ProfileSummaryCutoffHot
cl::opt<int> ProfileSummaryCutoffHot extern
Referenced by llvm::ProfileSummaryBuilder::getHotCountThreshold().
ProfileSummaryHotCount
cl::opt<int> ProfileSummaryHotCount extern
Referenced by llvm::ProfileSummaryBuilder::getHotCountThreshold().
ProfileSummaryHugeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryHugeWorkingSetSizeThreshold extern
ProfileSummaryLargeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryLargeWorkingSetSizeThreshold extern
ScalePartialSampleProfileWorkingSetSize
cl::opt< bool > ScalePartialSampleProfileWorkingSetSize("scale-partial-sample-profile-working-set-size", cl::Hidden, cl::init(true), cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled.")) ("scale-partial-sample-profile-working-set-size" , cl::Hidden , cl::init(true) , cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled."))