LLVM: lib/Transforms/ObjCARC/ProvenanceAnalysisEvaluator.cpp File Reference
ProvenanceAnalysisEvaluator.cpp File Reference
#include "ProvenanceAnalysis.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Functions
static StringRef getName (Value *V)
static void insertIfNamed (SetVector< Value * > &Values, Value *V)
INITIALIZE_PASS_BEGIN (PAEval, "pa-eval", "Evaluate ProvenanceAnalysis on all pairs", false, true) INITIALIZE_PASS_END(PAEval
Variables
pa eval
pa Evaluate ProvenanceAnalysis on all pairs
pa Evaluate ProvenanceAnalysis on all false
Function Documentation
getName()
static StringRef getName (Value * V) static
Definition at line 42 of file ProvenanceAnalysisEvaluator.cpp.
References Name, and llvm::StringRef::substr().
Referenced by llvm::SSAUpdaterBulk::AddUse(), llvm::Attributor::createShallowWrapper(), DEFINE_SIMPLE_CONVERSION_FUNCTIONS(), llvm::VPBasicBlock::execute(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::AArch64::getArchName(), llvm::ARM::getArchName(), llvm::CSKY::getArchName(), llvm::Intrinsic::getDeclaration(), llvm::object::Archive::Child::getFullName(), llvm::ItaniumPartialDemangler::getFunctionBaseName(), llvm::ItaniumPartialDemangler::getFunctionDeclContextName(), llvm::ItaniumPartialDemangler::getFunctionName(), llvm::object::Archive::Child::getMemoryBufferRef(), llvm::RegionBase< Tr >::getNameStr(), llvm::object::Archive::Child::getNext(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::ItaniumPartialDemangler::isCtorOrDtor(), ObjCProtoName::isObjCObject(), llvm::HexagonInstrInfo::isValidOffset(), LLVMGetSectionName(), LLVMGetSymbolName(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), llvm::AbstractAttribute::print(), llvm::Comdat::print(), llvm::MachineTraceMetrics::Ensemble::print(), llvm::VPBasicBlock::print(), llvm::VPRegionBlock::print(), llvm::RuntimeDyldImpl::reassignSectionAddress(), llvm::VPBasicBlock::splitAt(), and llvm::SelectionDAG::viewGraph().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PAEval , "pa-eval" , "Evaluate ProvenanceAnalysis on all pairs" , false , true)
insertIfNamed()
static void insertIfNamed (SetVector< Value * > & Values, Value * V) static
Definition at line 49 of file ProvenanceAnalysisEvaluator.cpp.
References llvm::SetVector< T, Vector, Set >::insert().
Variable Documentation
eval
pa eval
Definition at line 93 of file ProvenanceAnalysisEvaluator.cpp.
false
pa Evaluate ProvenanceAnalysis on all false
Definition at line 94 of file ProvenanceAnalysisEvaluator.cpp.
pairs
pa Evaluate ProvenanceAnalysis on all pairs
Definition at line 94 of file ProvenanceAnalysisEvaluator.cpp.