LLVM: lib/Support/regfree.c File Reference
regfree.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include "regex_impl.h"
#include "regutils.h"
#include "regex2.h"
Functions
void llvm_regfree (llvm_regex_t *preg)
Function Documentation
llvm_regfree()
void llvm_regfree (llvm_regex_t * preg)
Definition at line 50 of file regfree.c.
References g(), MAGIC1, MAGIC2, llvm_regex::re_g, and llvm_regex::re_magic.
Referenced by llvm_regcomp(), and llvm::Regex::~Regex().