LLVM: lib/Analysis/RegionPass.cpp File Reference
RegionPass.cpp File Reference
#include "llvm/Analysis/RegionPass.h"
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/IR/OptBisect.h"
#include "llvm/IR/PassTimingInfo.h"
#include "llvm/IR/PrintPasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "regionpassmgr"
Functions
static void addRegionIntoQueue (Region &R, std::deque< Region * > &RQ)
static std::string getDescription (const Region &R)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regionpassmgr"
Definition at line 27 of file RegionPass.cpp.
Function Documentation
addRegionIntoQueue()
static void addRegionIntoQueue (Region & R, std::deque< Region * > & RQ) static
Definition at line 41 of file RegionPass.cpp.
References addRegionIntoQueue(), and E.
Referenced by addRegionIntoQueue(), addRegionIntoQueue(), llvm::StructurizeCFGPass::run(), and llvm::RGPassManager::runOnFunction().
getDescription()
static std::string getDescription (const Region & R) static
Definition at line 279 of file RegionPass.cpp.