LLVM: lib/Target/RISCV/MCTargetDesc/RISCVMCExpr.cpp File Reference
RISCVMCExpr.cpp File Reference
#include "RISCVMCExpr.h"
#include "MCTargetDesc/RISCVAsmBackend.h"
#include "RISCVFixupKinds.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "riscvmcexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscvmcexpr"
Definition at line 29 of file RISCVMCExpr.cpp.
Function Documentation
fixELFSymbolsInTLSFixupsImpl()
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 162 of file RISCVMCExpr.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, fixELFSymbolsInTLSFixupsImpl(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.