LLVM: lib/Target/RISCV/RISCVSubtarget.cpp File Reference
RISCVSubtarget.cpp File Reference
#include "RISCVSubtarget.h"
#include "RISCV.h"
#include "RISCVCallLowering.h"
#include "RISCVFrameLowering.h"
#include "RISCVLegalizerInfo.h"
#include "RISCVMacroFusion.h"
#include "RISCVRegisterBankInfo.h"
#include "RISCVTargetMachine.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "RISCVGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "riscv-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Variables
static cl::opt< bool > EnableSubRegLiveness ("riscv-enable-subreg-liveness", cl::init(false), cl::Hidden)
static cl::opt< int > RVVVectorBitsMax ("riscv-v-vector-bits-max", cl::desc("Assume V extension vector registers are at most this big, " "with zero meaning no maximum size is assumed."), cl::init(0), cl::Hidden)
static cl::opt< int > RVVVectorBitsMin ("riscv-v-vector-bits-min", cl::desc("Assume V extension vector registers are at least this big, " "with zero meaning no minimum size is assumed. A value of -1 " "means use Zvl*b extension. This is primarily used to enable " "autovectorization with fixed width vectors."), cl::init(0), cl::Hidden)
static cl::opt< unsigned > RVVVectorLMULMax ("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden)
static cl::opt< bool > RISCVDisableUsingConstantPoolForLargeInts ("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden)
static cl::opt< unsigned > RISCVMaxBuildIntsCost ("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-subtarget"
Definition at line 26 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 29 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 28 of file RISCVSubtarget.cpp.
Variable Documentation
EnableSubRegLiveness
cl::opt< bool > EnableSubRegLiveness("riscv-enable-subreg-liveness", cl::init(false), cl::Hidden) ("riscv-enable-subreg-liveness" , cl::init(false) , cl::Hidden) static
RISCVDisableUsingConstantPoolForLargeInts
cl::opt< bool > RISCVDisableUsingConstantPoolForLargeInts("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden) ("riscv-disable-using-constant-pool-for-large-ints" , cl::desc("Disable using constant pool for large integers.") , cl::init(false) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::useConstantPoolForLargeInts().
RISCVMaxBuildIntsCost
cl::opt< unsigned > RISCVMaxBuildIntsCost("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden) ("riscv-max-build-ints-cost" , cl::desc("The maximum cost used for building integers.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxBuildIntsCost().
RVVVectorBitsMax
cl::opt< int > RVVVectorBitsMax("riscv-v-vector-bits-max", cl::desc("Assume V extension vector registers are at most this big, " "with zero meaning no maximum size is assumed."), cl::init(0), cl::Hidden) ("riscv-v-vector-bits-max" , cl::desc("Assume V extension vector registers are at most this big, " "with zero meaning no maximum size is assumed.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxRVVVectorSizeInBits(), and llvm::RISCVSubtarget::getMinRVVVectorSizeInBits().
RVVVectorBitsMin
cl::opt< int > RVVVectorBitsMin("riscv-v-vector-bits-min", cl::desc("Assume V extension vector registers are at least this big, " "with zero meaning no minimum size is assumed. A value of -1 " "means use Zvl*b extension. This is primarily used to enable " "autovectorization with fixed width vectors."), cl::init(0), cl::Hidden) ("riscv-v-vector-bits-min" , cl::desc("Assume V extension vector registers are at least this big, " "with zero meaning no minimum size is assumed. A value of -1 " "means use Zvl*b extension. This is primarily used to enable " "autovectorization with fixed width vectors.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxRVVVectorSizeInBits(), and llvm::RISCVSubtarget::getMinRVVVectorSizeInBits().
RVVVectorLMULMax
cl::opt< unsigned > RVVVectorLMULMax("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden) ("riscv-v-fixed-length-vector-lmul-max" , cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported.") , cl::init(8) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxLMULForFixedLengthVectors().