LLVM: lib/Target/RISCV/MCTargetDesc/RISCVMatInt.cpp File Reference
RISCVMatInt.cpp File Reference
#include "RISCVMatInt.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "llvm/ADT/APInt.h"
#include "llvm/Support/MathExtras.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCVMatInt
Functions
static int getInstSeqCost (RISCVMatInt::InstSeq &Res, bool HasRVC)
static void generateInstSeqImpl (int64_t Val, const FeatureBitset &ActiveFeatures, RISCVMatInt::InstSeq &Res)
static unsigned extractRotateInfo (int64_t Val)
InstSeq llvm::RISCVMatInt::generateInstSeq (int64_t Val, const FeatureBitset &ActiveFeatures)
int llvm::RISCVMatInt::getIntMatCost (const APInt &Val, unsigned Size, const FeatureBitset &ActiveFeatures, bool CompressionCost)
Function Documentation
extractRotateInfo()
static unsigned extractRotateInfo (int64_t Val) static
Definition at line 157 of file RISCVMatInt.cpp.
References llvm::countLeadingOnes(), llvm::countTrailingOnes(), llvm::Hi_32(), and llvm::Lo_32().
Referenced by llvm::RISCVMatInt::generateInstSeq().
generateInstSeqImpl()
static void generateInstSeqImpl (int64_t Val, const FeatureBitset & ActiveFeatures, RISCVMatInt::InstSeq & Res) static
Definition at line 48 of file RISCVMatInt.cpp.
References assert(), llvm::findFirstSet(), generateInstSeqImpl(), llvm::isInt(), llvm::isInt< 32 >(), llvm::isPowerOf2_64(), llvm::isUInt< 32 >(), llvm::Log2_64(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SignExtend64(), and Unsigned.
Referenced by llvm::RISCVMatInt::generateInstSeq(), and generateInstSeqImpl().
getInstSeqCost()
static int getInstSeqCost (RISCVMatInt::InstSeq & Res, bool HasRVC) static
Definition at line 15 of file RISCVMatInt.cpp.
References llvm::isInt(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::RISCVMatInt::getIntMatCost().