LLVM: lib/Analysis/ScopedNoAliasAA.cpp File Reference
ScopedNoAliasAA.cpp File Reference
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
Functions
static void collectMDInDomain (const MDNode *List, const MDNode *Domain, SmallPtrSetImpl< const MDNode * > &Nodes)
INITIALIZE_PASS (ScopedNoAliasAAWrapperPass, "scoped-noalias-aa", "Scoped NoAlias Alias Analysis", false, true) ImmutablePass *llvm
Variables
static cl::opt< bool > EnableScopedNoAlias ("enable-scoped-noalias", cl::init(true), cl::Hidden)
Function Documentation
collectMDInDomain()
static void collectMDInDomain (const MDNode * List, const MDNode * Domain, SmallPtrSetImpl< const MDNode * > & Nodes) static
Definition at line 109 of file ScopedNoAliasAA.cpp.
References llvm::dyn_cast(), getDomain(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::List.
INITIALIZE_PASS()
INITIALIZE_PASS (ScopedNoAliasAAWrapperPass , "scoped-noalias-aa" , "Scoped NoAlias Alias Analysis" , false , true)
Definition at line 157 of file ScopedNoAliasAA.cpp.
Variable Documentation
EnableScopedNoAlias
cl::opt< bool > EnableScopedNoAlias("enable-scoped-noalias", cl::init(true), cl::Hidden) ("enable-scoped-noalias" , cl::init(true) , cl::Hidden) static
Referenced by llvm::ScopedNoAliasAAResult::alias(), llvm::ScopedNoAliasAAResult::getModRefInfo(), and llvm::ScopedNoAliasAAResult::getModRefInfo().