LLVM: lib/Transforms/Utils/SplitModule.cpp File Reference
SplitModule.cpp File Reference
#include "llvm/Transforms/Utils/SplitModule.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <memory>
#include <queue>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "split-module"
Functions
static void addNonConstUser (ClusterMapType &GVtoClusterMap, const GlobalValue *GV, const User *U)
static void addAllGlobalValueUsers (ClusterMapType &GVtoClusterMap, const GlobalValue *GV, const Value *V)
static const GlobalObject * getGVPartitioningRoot (const GlobalValue *GV)
static void findPartitions (Module &M, ClusterIDMapType &ClusterIDMap, unsigned N)
static void externalize (GlobalValue *GV)
static bool isInPartition (const GlobalValue *GV, unsigned I, unsigned N)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "split-module"
Definition at line 50 of file SplitModule.cpp.
Function Documentation
addAllGlobalValueUsers()
static void addAllGlobalValueUsers (ClusterMapType & GVtoClusterMap, const GlobalValue * GV, const Value * V) static
Definition at line 75 of file SplitModule.cpp.
References addNonConstUser(), llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorBase< Size_T >::empty(), llvm::isa(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by findPartitions().
addNonConstUser()
static void addNonConstUser (ClusterMapType & GVtoClusterMap, const GlobalValue * GV, const User * U) static
Definition at line 60 of file SplitModule.cpp.
References assert(), llvm::dyn_cast(), F, llvm::GlobalValue::getParent(), I, llvm::isa(), and llvm_unreachable.
Referenced by addAllGlobalValueUsers().
externalize()
static void externalize (GlobalValue * GV) static
Definition at line 218 of file SplitModule.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::GlobalValue::HiddenVisibility, llvm::GlobalValue::setLinkage(), llvm::Value::setName(), and llvm::GlobalValue::setVisibility().
Referenced by llvm::SplitModule().
findPartitions()
static void findPartitions (Module & M, ClusterIDMapType & ClusterIDMap, unsigned N) static
Definition at line 103 of file SplitModule.cpp.
References addAllGlobalValueUsers(), llvm::CallingConv::C, llvm::dbgs(), llvm::dyn_cast(), E, F, llvm::for_each(), getGVPartitioningRoot(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Constant::isConstantUsed(), LLVM_DEBUG, llvm::BlockAddress::lookup(), MI, N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by llvm::SplitModule().
getGVPartitioningRoot()
static const GlobalObject * getGVPartitioningRoot (const GlobalValue * GV) static
Definition at line 92 of file SplitModule.cpp.
References llvm::dyn_cast_or_null(), and llvm::GlobalValue::getAliaseeObject().
Referenced by findPartitions(), and isInPartition().
isInPartition()
static bool isInPartition (const GlobalValue * GV, unsigned I, unsigned N) static
Definition at line 231 of file SplitModule.cpp.
References llvm::CallingConv::C, llvm::GlobalValue::getComdat(), getGVPartitioningRoot(), llvm::Value::getName(), H, I, N, and Name.
Referenced by llvm::SplitModule().