LLVM: llvm::memprof::IndexedAllocationInfo Struct Reference
llvm::memprof::IndexedAllocationInfo Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
IndexedAllocationInfo ()=default
IndexedAllocationInfo (ArrayRef< FrameId > CS, const MemInfoBlock &MB)
size_t serializedSize () const
bool operator== (const IndexedAllocationInfo &Other) const
bool operator!= (const IndexedAllocationInfo &Other) const
Public Attributes
llvm::SmallVector< FrameId > CallStack
PortableMemInfoBlock Info
Detailed Description
Definition at line 253 of file MemProf.h.
Constructor & Destructor Documentation
IndexedAllocationInfo() [1/2]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo () default
IndexedAllocationInfo() [2/2]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo (ArrayRef< FrameId > CS, const MemInfoBlock & MB) inline
Definition at line 261 of file MemProf.h.
Member Function Documentation
operator!=()
bool llvm::memprof::IndexedAllocationInfo::operator!= (const IndexedAllocationInfo & Other) const inline
Definition at line 285 of file MemProf.h.
References operator==(), and llvm::Other.
operator==()
bool llvm::memprof::IndexedAllocationInfo::operator== (const IndexedAllocationInfo & Other) const inline
Definition at line 271 of file MemProf.h.
References CallStack, and llvm::Other.
Referenced by operator!=().
serializedSize()
size_t llvm::memprof::IndexedAllocationInfo::serializedSize () const inline
Definition at line 265 of file MemProf.h.
References CallStack, and llvm::memprof::PortableMemInfoBlock::serializedSize().
Member Data Documentation
CallStack
llvm::SmallVector<FrameId> llvm::memprof::IndexedAllocationInfo::CallStack
Definition at line 256 of file MemProf.h.
Referenced by llvm::memprof::AllocationInfo::AllocationInfo(), operator==(), and serializedSize().
Info
PortableMemInfoBlock llvm::memprof::IndexedAllocationInfo::Info
Definition at line 258 of file MemProf.h.
Referenced by llvm::memprof::AllocationInfo::AllocationInfo().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h