LLVM: llvm::DOTGraphTraits< MachineBlockFrequencyInfo * > Struct Reference
llvm::DOTGraphTraits< MachineBlockFrequencyInfo * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const MachineBasicBlock *Node, const MachineBlockFrequencyInfo *Graph)
std::string getNodeAttributes (const MachineBasicBlock *Node, const MachineBlockFrequencyInfo *Graph)
std::string getEdgeAttributes (const MachineBasicBlock *Node, EdgeIter EI, const MachineBlockFrequencyInfo *MBFI)
Public Member Functions inherited from llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >
BFIDOTGraphTraitsBase (bool isSimple=false)
std::string getNodeAttributes (NodeRef Node, const BlockFrequencyInfoT *Graph, unsigned HotPercentThreshold=0)
std::string getNodeLabel (NodeRef Node, const BlockFrequencyInfoT *Graph, GVDAGType GType, int layout_order=-1)
std::string getEdgeAttributes (NodeRef Node, EdgeIter EI, const BlockFrequencyInfoT *BFI, const BranchProbabilityInfoT *BPI, unsigned HotPercentThreshold=0)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Public Attributes
const MachineFunction * CurFunc = nullptr
DenseMap< const MachineBasicBlock *, int > LayoutOrderMap
Public Attributes inherited from llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >
uint64_t MaxFrequency = 0
Additional Inherited Members
Public Types inherited from llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >
using GTraits = GraphTraits<BlockFrequencyInfoT *>
using NodeRef = typename GTraits::NodeRef
using EdgeIter = typename GTraits::ChildIteratorType
using NodeIter = typename GTraits::nodes_iterator
Static Public Member Functions inherited from llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >
static StringRef getGraphName (const BlockFrequencyInfoT *G)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
template<typename GraphType >
static bool isNodeHidden (const void *, const GraphType &)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
static bool renderNodesUsingHTML ()
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 119 of file MachineBlockFrequencyInfo.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::DOTGraphTraits (bool isSimple = false) inline explicit
Definition at line 124 of file MachineBlockFrequencyInfo.cpp.
Member Function Documentation
getEdgeAttributes()
std::string llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getEdgeAttributes (const MachineBasicBlock * Node, EdgeIter EI, const MachineBlockFrequencyInfo * MBFI) inline
Definition at line 155 of file MachineBlockFrequencyInfo.cpp.
References llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::MachineBlockFrequencyInfo::getMBPI(), and llvm::ViewHotFreqPercent.
getNodeAttributes()
std::string llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeAttributes (const MachineBasicBlock * Node, const MachineBlockFrequencyInfo * Graph) inline
Definition at line 149 of file MachineBlockFrequencyInfo.cpp.
References llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), and llvm::ViewHotFreqPercent.
getNodeLabel()
std::string llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel (const MachineBasicBlock * Node, const MachineBlockFrequencyInfo * Graph) inline
Definition at line 127 of file MachineBlockFrequencyInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), F, llvm::getGVDT(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeLabel(), and isSimple().
Member Data Documentation
CurFunc
const MachineFunction* llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::CurFunc = nullptr
Definition at line 121 of file MachineBlockFrequencyInfo.cpp.
LayoutOrderMap
DenseMap<const MachineBasicBlock *, int> llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::LayoutOrderMap
Definition at line 122 of file MachineBlockFrequencyInfo.cpp.
The documentation for this struct was generated from the following file:
lib/CodeGen/MachineBlockFrequencyInfo.cpp