LLVM: llvm::rdf::FuncNode Struct Reference
llvm::rdf::FuncNode Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
MachineFunction * getCode () const
NodeAddr< BlockNode * > findBlock (const MachineBasicBlock *BB, const DataFlowGraph &G) const
NodeAddr< BlockNode * > getEntryBlock (const DataFlowGraph &G)
Public Member Functions inherited from llvm::rdf::CodeNode
template<typename T >
T getCode () const
void setCode (void *C)
NodeAddr< NodeBase * > getFirstMember (const DataFlowGraph &G) const
NodeAddr< NodeBase * > getLastMember (const DataFlowGraph &G) const
void addMember (NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
void addMemberAfter (NodeAddr< NodeBase * > MA, NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
void removeMember (NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
NodeList members (const DataFlowGraph &G) const
template<typename Predicate >
NodeList members_if (Predicate P, const DataFlowGraph &G) const
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (NodeAddr< NodeBase * > NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Public Attributes inherited from llvm::rdf::NodeBase
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct Ref
Code_struct Code
};
Detailed Description
Definition at line 634 of file RDFGraph.h.
Member Function Documentation
findBlock()
NodeAddr< BlockNode * > FuncNode::findBlock (const MachineBasicBlock * BB, const DataFlowGraph & G) const
Definition at line 574 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::SmallVectorBase< Size_T >::empty(), G, and llvm::rdf::CodeNode::members_if().
Referenced by getEntryBlock().
getCode()
MachineFunction * llvm::rdf::FuncNode::getCode () const inline
Definition at line 635 of file RDFGraph.h.
References llvm::rdf::CodeNode::getCode().
Referenced by getEntryBlock().
getEntryBlock()
NodeAddr< BlockNode * > FuncNode::getEntryBlock (const DataFlowGraph & G)
Definition at line 586 of file RDFGraph.cpp.
References findBlock(), llvm::MachineFunction::front(), G, and getCode().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp