LLVM: llvm::VFRange Struct Reference
llvm::VFRange Struct Reference
A range of powers-of-2 vectorization factors with fixed start and adjustable end.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
bool isEmpty () const
VFRange (const ElementCount &Start, const ElementCount &End)
Public Attributes
const ElementCount Start
ElementCount End
Detailed Description
A range of powers-of-2 vectorization factors with fixed start and adjustable end.
The range includes start and excludes end, e.g.,: [1, 9) = {1, 2, 4, 8}
Definition at line 79 of file VPlan.h.
Constructor & Destructor Documentation
VFRange()
llvm::VFRange::VFRange (const ElementCount & Start, const ElementCount & End) inline
Definition at line 90 of file VPlan.h.
References assert(), End, llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::isPowerOf2_32(), llvm::LinearPolySize< LeafTy >::isScalable(), and Start.
Member Function Documentation
isEmpty()
bool llvm::VFRange::isEmpty () const inline
Definition at line 86 of file VPlan.h.
References End, llvm::LinearPolySize< LeafTy >::getKnownMinValue(), and Start.
Referenced by llvm::LoopVectorizationPlanner::getDecisionAndClampRange().
Member Data Documentation
End
ElementCount llvm::VFRange::End
Definition at line 84 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::buildVPlans(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), isEmpty(), and VFRange().
Start
const ElementCount llvm::VFRange::Start
Definition at line 81 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::VPRecipeBuilder::handleReplication(), isEmpty(), and VFRange().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h