LLVM: llvm::OpenMPIRBuilder::OutlineInfo Struct Reference
llvm::OpenMPIRBuilder::OutlineInfo Struct Reference
Helper that contains information about regions we need to outline during finalization.
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Public Types
using PostOutlineCBTy = std::function<void(Function &)>
Public Member Functions
void collectBlocks (SmallPtrSetImpl< BasicBlock * > &BlockSet, SmallVectorImpl< BasicBlock * > &BlockVector)
Collect all blocks in between EntryBB and ExitBB in both the given vector and set.
Function * getFunction () const
Return the function that contains the region to be outlined.
Public Attributes
PostOutlineCBTy PostOutlineCB
BasicBlock * EntryBB
BasicBlock * ExitBB
BasicBlock * OuterAllocaBB
SmallVector< Value *, 2 > ExcludeArgsFromAggregate
Detailed Description
Helper that contains information about regions we need to outline during finalization.
Definition at line 910 of file OMPIRBuilder.h.
Member Typedef Documentation
PostOutlineCBTy
using llvm::OpenMPIRBuilder::OutlineInfo::PostOutlineCBTy = std::function<void(Function &)>
Definition at line 911 of file OMPIRBuilder.h.
Member Function Documentation
collectBlocks()
void OpenMPIRBuilder::OutlineInfo::collectBlocks (SmallPtrSetImpl< BasicBlock * > & BlockSet, SmallVectorImpl< BasicBlock * > & BlockVector)
Collect all blocks in between EntryBB and ExitBB in both the given vector and set.
Definition at line 4404 of file OMPIRBuilder.cpp.
References llvm::SmallVectorBase< Size_T >::empty(), EntryBB, ExitBB, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::successors().
Referenced by llvm::OpenMPIRBuilder::createParallel().
getFunction()
Function * llvm::OpenMPIRBuilder::OutlineInfo::getFunction () const inline
Return the function that contains the region to be outlined.
Definition at line 922 of file OMPIRBuilder.h.
References EntryBB, and llvm::BasicBlock::getParent().
Member Data Documentation
EntryBB
BasicBlock* llvm::OpenMPIRBuilder::OutlineInfo::EntryBB
Definition at line 913 of file OMPIRBuilder.h.
Referenced by collectBlocks(), llvm::OpenMPIRBuilder::createParallel(), llvm::OpenMPIRBuilder::createTask(), and getFunction().
ExcludeArgsFromAggregate
SmallVector<Value *, 2> llvm::OpenMPIRBuilder::OutlineInfo::ExcludeArgsFromAggregate
Definition at line 914 of file OMPIRBuilder.h.
Referenced by llvm::OpenMPIRBuilder::createParallel().
ExitBB
BasicBlock * llvm::OpenMPIRBuilder::OutlineInfo::ExitBB
Definition at line 913 of file OMPIRBuilder.h.
Referenced by collectBlocks(), llvm::OpenMPIRBuilder::createParallel(), and llvm::OpenMPIRBuilder::createTask().
OuterAllocaBB
BasicBlock * llvm::OpenMPIRBuilder::OutlineInfo::OuterAllocaBB
Definition at line 913 of file OMPIRBuilder.h.
Referenced by llvm::OpenMPIRBuilder::createParallel(), and llvm::OpenMPIRBuilder::createTask().
PostOutlineCB
PostOutlineCBTy llvm::OpenMPIRBuilder::OutlineInfo::PostOutlineCB
Definition at line 912 of file OMPIRBuilder.h.
Referenced by llvm::OpenMPIRBuilder::createParallel(), and llvm::OpenMPIRBuilder::createTask().
The documentation for this struct was generated from the following files:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h
lib/Frontend/OpenMP/OMPIRBuilder.cpp