LLVM: llvm::SGPRSpillBuilder Struct Reference
llvm::SGPRSpillBuilder Struct Reference
Classes
struct PerVGPRData
Public Member Functions
SGPRSpillBuilder (const SIRegisterInfo &TRI, const SIInstrInfo &TII, bool IsWave32, MachineBasicBlock::iterator MI, int Index, RegScavenger *RS)
SGPRSpillBuilder (const SIRegisterInfo &TRI, const SIInstrInfo &TII, bool IsWave32, MachineBasicBlock::iterator MI, Register Reg, bool IsKill, int Index, RegScavenger *RS)
PerVGPRData getPerVGPRData ()
void prepare ()
void restore ()
void readWriteTmpVGPR (unsigned Offset, bool IsLoad)
void setMI (MachineBasicBlock *NewMBB, MachineBasicBlock::iterator NewMI)
Public Attributes
Register SuperReg
MachineBasicBlock::iterator MI
ArrayRef< int16_t > SplitParts
unsigned NumSubRegs
bool IsKill
const DebugLoc & DL
Register TmpVGPR = AMDGPU::NoRegister
int TmpVGPRIndex = 0
bool TmpVGPRLive = false
Register SavedExecReg = AMDGPU::NoRegister
int Index
unsigned EltSize = 4
RegScavenger * RS
MachineBasicBlock * MBB
MachineFunction & MF
SIMachineFunctionInfo & MFI
const SIInstrInfo & TII
const SIRegisterInfo & TRI
bool IsWave32
Register ExecReg
unsigned MovOpc
unsigned NotOpc
Detailed Description
Definition at line 72 of file SIRegisterInfo.cpp.
Constructor & Destructor Documentation
SGPRSpillBuilder() [1/2]
llvm::SGPRSpillBuilder::SGPRSpillBuilder (const SIRegisterInfo & TRI, const SIInstrInfo & TII, bool IsWave32, MachineBasicBlock::iterator MI, int Index, RegScavenger * RS) inline
Definition at line 112 of file SIRegisterInfo.cpp.
SGPRSpillBuilder() [2/2]
llvm::SGPRSpillBuilder::SGPRSpillBuilder (const SIRegisterInfo & TRI, const SIInstrInfo & TII, bool IsWave32, MachineBasicBlock::iterator MI, Register Reg, bool IsKill, int Index, RegScavenger * RS) inline
Definition at line 118 of file SIRegisterInfo.cpp.
References assert(), EltSize, llvm::ArrayRef< T >::empty(), ExecReg, llvm::SIRegisterInfo::getPhysRegClass(), llvm::SIRegisterInfo::getRegSplitParts(), if(), IsWave32, MovOpc, NotOpc, NumSubRegs, llvm::ArrayRef< T >::size(), SplitParts, SuperReg, and TRI.
Member Function Documentation
getPerVGPRData()
PerVGPRData llvm::SGPRSpillBuilder::getPerVGPRData () inline
Definition at line 144 of file SIRegisterInfo.cpp.
References llvm::Data, IsWave32, and NumSubRegs.
Referenced by prepare(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
prepare()
void llvm::SGPRSpillBuilder::prepare () inline
Definition at line 165 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::RegScavenger::assignRegToScavengingIndex(), llvm::BuildMI(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), DL, ExecReg, llvm::MachineFunction::getFrameInfo(), llvm::MachineInstr::getOperand(), getPerVGPRData(), llvm::SIMachineFunctionInfo::getScavengeFI(), I, llvm::RegState::ImplicitDefine, llvm::RegScavenger::isRegUsed(), IsWave32, MBB, MF, MFI, MI, MovOpc, NotOpc, RS, SavedExecReg, llvm::RegScavenger::scavengeRegister(), llvm::MachineOperand::setIsDead(), llvm::RegScavenger::setRegUsed(), SuperReg, TII, TmpVGPR, TmpVGPRIndex, TmpVGPRLive, TRI, and llvm::SGPRSpillBuilder::PerVGPRData::VGPRLanes.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
readWriteTmpVGPR()
void llvm::SGPRSpillBuilder::readWriteTmpVGPR (unsigned Offset, bool IsLoad) inline
Definition at line 287 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), DL, ExecReg, llvm::MachineInstr::getOperand(), llvm::RegScavenger::isRegUsed(), MBB, MI, NotOpc, Offset, RS, SavedExecReg, llvm::MachineOperand::setIsDead(), TII, and TRI.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), and llvm::SIRegisterInfo::spillSGPR().
restore()
void llvm::SGPRSpillBuilder::restore () inline
Definition at line 246 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::RegScavenger::assignRegToScavengingIndex(), llvm::BuildMI(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), DL, ExecReg, llvm::MachineInstr::getOperand(), I, llvm::RegState::ImplicitKill, llvm::RegState::Kill, MBB, MI, MovOpc, NotOpc, RS, SavedExecReg, llvm::MachineOperand::setIsDead(), TII, TmpVGPR, TmpVGPRIndex, TmpVGPRLive, and TRI.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
setMI()
void llvm::SGPRSpillBuilder::setMI (MachineBasicBlock * NewMBB, MachineBasicBlock::iterator NewMI) inline
Definition at line 310 of file SIRegisterInfo.cpp.
References assert(), llvm::MachineBasicBlock::getParent(), MBB, MF, and MI.
Referenced by llvm::SIRegisterInfo::spillEmergencySGPR().
Member Data Documentation
DL
const DebugLoc& llvm::SGPRSpillBuilder::DL
Definition at line 85 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), readWriteTmpVGPR(), restore(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
EltSize
unsigned llvm::SGPRSpillBuilder::EltSize = 4
Definition at line 99 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), and SGPRSpillBuilder().
ExecReg
Register llvm::SGPRSpillBuilder::ExecReg
Definition at line 108 of file SIRegisterInfo.cpp.
Referenced by prepare(), readWriteTmpVGPR(), restore(), and SGPRSpillBuilder().
Index
int llvm::SGPRSpillBuilder::Index
Definition at line 98 of file SIRegisterInfo.cpp.
IsKill
bool llvm::SGPRSpillBuilder::IsKill
Definition at line 84 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
IsWave32
bool llvm::SGPRSpillBuilder::IsWave32
Definition at line 107 of file SIRegisterInfo.cpp.
Referenced by getPerVGPRData(), prepare(), and SGPRSpillBuilder().
MBB
MachineBasicBlock* llvm::SGPRSpillBuilder::MBB
Definition at line 102 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), readWriteTmpVGPR(), restore(), llvm::SIRegisterInfo::restoreSGPR(), setMI(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
MF
MachineFunction& llvm::SGPRSpillBuilder::MF
Definition at line 103 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), and setMI().
MFI
SIMachineFunctionInfo& llvm::SGPRSpillBuilder::MFI
Definition at line 104 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
MI
MachineBasicBlock::iterator llvm::SGPRSpillBuilder::MI
Definition at line 81 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), readWriteTmpVGPR(), restore(), and setMI().
MovOpc
unsigned llvm::SGPRSpillBuilder::MovOpc
Definition at line 109 of file SIRegisterInfo.cpp.
Referenced by prepare(), restore(), and SGPRSpillBuilder().
NotOpc
unsigned llvm::SGPRSpillBuilder::NotOpc
Definition at line 110 of file SIRegisterInfo.cpp.
Referenced by prepare(), readWriteTmpVGPR(), restore(), and SGPRSpillBuilder().
NumSubRegs
unsigned llvm::SGPRSpillBuilder::NumSubRegs
Definition at line 83 of file SIRegisterInfo.cpp.
Referenced by getPerVGPRData(), llvm::SIRegisterInfo::restoreSGPR(), SGPRSpillBuilder(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
RS
RegScavenger* llvm::SGPRSpillBuilder::RS
Definition at line 101 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), readWriteTmpVGPR(), and restore().
SavedExecReg
Register llvm::SGPRSpillBuilder::SavedExecReg = AMDGPU::NoRegister
Definition at line 96 of file SIRegisterInfo.cpp.
Referenced by prepare(), readWriteTmpVGPR(), and restore().
SplitParts
ArrayRef<int16_t> llvm::SGPRSpillBuilder::SplitParts
Definition at line 82 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), SGPRSpillBuilder(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
SuperReg
Register llvm::SGPRSpillBuilder::SuperReg
Definition at line 80 of file SIRegisterInfo.cpp.
Referenced by prepare(), llvm::SIRegisterInfo::restoreSGPR(), SGPRSpillBuilder(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
TII
const SIInstrInfo& llvm::SGPRSpillBuilder::TII
Definition at line 105 of file SIRegisterInfo.cpp.
Referenced by prepare(), readWriteTmpVGPR(), restore(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
TmpVGPR
Register llvm::SGPRSpillBuilder::TmpVGPR = AMDGPU::NoRegister
Definition at line 90 of file SIRegisterInfo.cpp.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), prepare(), restore(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
TmpVGPRIndex
int llvm::SGPRSpillBuilder::TmpVGPRIndex = 0
Definition at line 92 of file SIRegisterInfo.cpp.
Referenced by prepare(), and restore().
TmpVGPRLive
bool llvm::SGPRSpillBuilder::TmpVGPRLive = false
Definition at line 94 of file SIRegisterInfo.cpp.
Referenced by prepare(), and restore().
TRI
const SIRegisterInfo& llvm::SGPRSpillBuilder::TRI
Definition at line 106 of file SIRegisterInfo.cpp.
Referenced by prepare(), readWriteTmpVGPR(), restore(), and SGPRSpillBuilder().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/SIRegisterInfo.cpp