LLVM: llvm::AMDGPU::HSAMD::Kernel::Metadata Struct Reference
llvm::AMDGPU::HSAMD::Kernel::Metadata Struct Reference final
In-memory representation of kernel metadata.
#include "llvm/Support/AMDGPUMetadata.h"
Public Member Functions
Metadata ()=default
Default constructor.
Public Attributes
std::string mName = std::string()
Kernel source name. Required.
std::string mSymbolName = std::string()
Kernel descriptor name. Required.
std::string mLanguage = std::string()
Language. Optional.
std::vector< uint32_t > mLanguageVersion = std::vector<uint32_t>()
Language version. Optional.
Attrs::Metadata mAttrs = Attrs::Metadata()
Attributes metadata. Optional.
std::vector< Arg::Metadata > mArgs = std::vector<Arg::Metadata>()
Arguments metadata. Optional.
CodeProps::Metadata mCodeProps = CodeProps::Metadata()
Code properties metadata. Optional.
DebugProps::Metadata mDebugProps = DebugProps::Metadata()
Debug properties metadata. Optional.
Detailed Description
In-memory representation of kernel metadata.
Definition at line 402 of file AMDGPUMetadata.h.
Constructor & Destructor Documentation
Metadata()
llvm::AMDGPU::HSAMD::Kernel::Metadata::Metadata () default
Default constructor.
Member Data Documentation
mArgs
std::vector<Arg::Metadata> llvm::AMDGPU::HSAMD::Kernel::Metadata::mArgs = std::vector<Arg::Metadata>()
Arguments metadata. Optional.
Definition at line 414 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mAttrs
Attrs::Metadata llvm::AMDGPU::HSAMD::Kernel::Metadata::mAttrs = Attrs::Metadata()
Attributes metadata. Optional.
Definition at line 412 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mCodeProps
CodeProps::Metadata llvm::AMDGPU::HSAMD::Kernel::Metadata::mCodeProps = CodeProps::Metadata()
Code properties metadata. Optional.
Definition at line 416 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mDebugProps
DebugProps::Metadata llvm::AMDGPU::HSAMD::Kernel::Metadata::mDebugProps = DebugProps::Metadata()
Debug properties metadata. Optional.
Definition at line 418 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mLanguage
std::string llvm::AMDGPU::HSAMD::Kernel::Metadata::mLanguage = std::string()
Language. Optional.
Definition at line 408 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mLanguageVersion
std::vector<uint32_t> llvm::AMDGPU::HSAMD::Kernel::Metadata::mLanguageVersion = std::vector<uint32_t>()
Language version. Optional.
Definition at line 410 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mName
std::string llvm::AMDGPU::HSAMD::Kernel::Metadata::mName = std::string()
Kernel source name. Required.
Definition at line 404 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
mSymbolName
std::string llvm::AMDGPU::HSAMD::Kernel::Metadata::mSymbolName = std::string()
Kernel descriptor name. Required.
Definition at line 406 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/Support/AMDGPUMetadata.h