LLVM: llvm::BasicAAResult::DecomposedGEP Struct Reference
llvm::BasicAAResult::DecomposedGEP Struct Reference
Public Member Functions
void dump () const
void print (raw_ostream &OS) const
Public Attributes
const Value * Base
APInt Offset
SmallVector< VariableGEPIndex, 4 > VarIndices
Optional< bool > InBounds
Detailed Description
Definition at line 483 of file BasicAliasAnalysis.cpp.
Member Function Documentation
dump()
void llvm::BasicAAResult::DecomposedGEP::dump () const inline
Definition at line 494 of file BasicAliasAnalysis.cpp.
References llvm::dbgs(), and llvm::BasicAAResult::DecomposedGEP::print().
print()
void llvm::BasicAAResult::DecomposedGEP::print (raw_ostream & OS) const inline
Definition at line 498 of file BasicAliasAnalysis.cpp.
References llvm::BasicAAResult::DecomposedGEP::Base, llvm::Value::getName(), llvm::BasicAAResult::DecomposedGEP::Offset, llvm::SmallVectorBase< Size_T >::size(), and llvm::BasicAAResult::DecomposedGEP::VarIndices.
Referenced by llvm::BasicAAResult::DecomposedGEP::dump().
Member Data Documentation
Base
const Value* llvm::BasicAAResult::DecomposedGEP::Base
Definition at line 485 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
InBounds
Optional<bool> llvm::BasicAAResult::DecomposedGEP::InBounds
Definition at line 492 of file BasicAliasAnalysis.cpp.
Offset
APInt llvm::BasicAAResult::DecomposedGEP::Offset
Definition at line 487 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
VarIndices
SmallVector<VariableGEPIndex, 4> llvm::BasicAAResult::DecomposedGEP::VarIndices
Definition at line 489 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
The documentation for this struct was generated from the following file:
lib/Analysis/BasicAliasAnalysis.cpp