LLVM: llvm::ms_demangle::IdentifierNode Struct Reference
llvm::ms_demangle::IdentifierNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
IdentifierNode (NodeKind K)
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputBuffer &OB, OutputFlags Flags) const =0
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
NodeArrayNode * TemplateParams = nullptr
Protected Member Functions
void outputTemplateParameters (OutputBuffer &OB, OutputFlags Flags) const
Detailed Description
Definition at line 354 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
IdentifierNode()
llvm::ms_demangle::IdentifierNode::IdentifierNode (NodeKind K) inline explicit
Definition at line 355 of file MicrosoftDemangleNodes.h.
Member Function Documentation
outputTemplateParameters()
void IdentifierNode::outputTemplateParameters (OutputBuffer & OB, OutputFlags Flags) const protected
Definition at line 222 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::NodeArrayNode::output(), and TemplateParams.
Referenced by llvm::ms_demangle::ConversionOperatorIdentifierNode::output(), llvm::ms_demangle::IntrinsicFunctionIdentifierNode::output(), llvm::ms_demangle::LiteralOperatorIdentifierNode::output(), llvm::ms_demangle::NamedIdentifierNode::output(), and llvm::ms_demangle::StructorIdentifierNode::output().
Member Data Documentation
TemplateParams
NodeArrayNode* llvm::ms_demangle::IdentifierNode::TemplateParams = nullptr
Definition at line 357 of file MicrosoftDemangleNodes.h.
Referenced by outputTemplateParameters().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp