LLVM: llvm::remarks::YAMLMetaSerializer Struct Reference
llvm::remarks::YAMLMetaSerializer Struct Reference
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLMetaSerializer (raw_ostream &OS, Optional< StringRef > ExternalFilename)
void emit () override
Public Member Functions inherited from llvm::remarks::MetaSerializer
MetaSerializer (raw_ostream &OS)
virtual ~MetaSerializer ()=default
This is just an interface.
Public Attributes
Optional< StringRef > ExternalFilename
Public Attributes inherited from llvm::remarks::MetaSerializer
raw_ostream & OS
The open raw_ostream that the metadata is emitted to.
Detailed Description
Definition at line 55 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLMetaSerializer()
llvm::remarks::YAMLMetaSerializer::YAMLMetaSerializer (raw_ostream & OS, Optional< StringRef > ExternalFilename) inline
Definition at line 58 of file YAMLRemarkSerializer.h.
Member Function Documentation
emit()
void YAMLMetaSerializer::emit () override virtual
Implements llvm::remarks::MetaSerializer.
Reimplemented in llvm::remarks::YAMLStrTabMetaSerializer.
Definition at line 241 of file YAMLRemarkSerializer.cpp.
References emitExternalFile(), emitMagic(), emitStrTab(), emitVersion(), ExternalFilename, llvm::None, and llvm::remarks::MetaSerializer::OS.
Member Data Documentation
ExternalFilename
Optional<StringRef> llvm::remarks::YAMLMetaSerializer::ExternalFilename
Definition at line 56 of file YAMLRemarkSerializer.h.
Referenced by emit(), and llvm::remarks::YAMLStrTabMetaSerializer::emit().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp