LLVM: llvm::SystemZVectorConstantInfo Struct Reference
llvm::SystemZVectorConstantInfo Struct Reference
#include "Target/SystemZ/SystemZISelLowering.h"
Public Member Functions
SystemZVectorConstantInfo (APInt IntImm)
SystemZVectorConstantInfo (APFloat FPImm)
SystemZVectorConstantInfo (BuildVectorSDNode *BVN)
bool isVectorConstantLegal (const SystemZSubtarget &Subtarget)
Public Attributes
unsigned Opcode = 0
SmallVector< unsigned, 2 > OpVals
MVT VecVT
Detailed Description
Definition at line 770 of file SystemZISelLowering.h.
Constructor & Destructor Documentation
SystemZVectorConstantInfo() [1/3]
SystemZVectorConstantInfo::SystemZVectorConstantInfo (APInt IntImm)
Definition at line 795 of file SystemZISelLowering.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::getZExtValue(), llvm::APInt::isSingleWord(), llvm::APInt::lshr(), llvm::APInt::trunc(), and llvm::SystemZ::VectorBits.
SystemZVectorConstantInfo() [2/3]
llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo (APFloat FPImm) inline
Definition at line 782 of file SystemZISelLowering.h.
References llvm::APFloat::getSemantics(), and llvm::APFloatBase::IEEEquad().
SystemZVectorConstantInfo() [3/3]
SystemZVectorConstantInfo::SystemZVectorConstantInfo (BuildVectorSDNode * BVN)
Definition at line 822 of file SystemZISelLowering.cpp.
References assert(), llvm::BuildVectorSDNode::isConstant(), and llvm::BuildVectorSDNode::isConstantSplat().
Member Function Documentation
isVectorConstantLegal()
bool SystemZVectorConstantInfo::isVectorConstantLegal (const SystemZSubtarget & Subtarget)
Definition at line 720 of file SystemZISelLowering.cpp.
References llvm::SystemZISD::BYTE_MASK, llvm::findFirstSet(), llvm::findLastSet(), llvm::SystemZSubtarget::getInstrInfo(), llvm::MVT::getIntegerVT(), llvm::MVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::SystemZSubtarget::hasVector(), llvm::SystemZSubtarget::hasVectorEnhancements1(), I, llvm::isInt< 16 >(), llvm::Lower, llvm::APInt::lshr(), Opcode, OpVals, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SystemZISD::REPLICATE, llvm::SystemZISD::ROTATE_MASK, llvm::SignExtend64(), TII, llvm::APInt::trunc(), llvm::Upper, llvm::Value, llvm::SystemZ::VectorBits, llvm::SystemZ::VectorBytes, and VecVT.
Referenced by llvm::SystemZTargetLowering::isFPImmLegal().
Member Data Documentation
Opcode
unsigned llvm::SystemZVectorConstantInfo::Opcode = 0
Definition at line 778 of file SystemZISelLowering.h.
Referenced by isVectorConstantLegal().
OpVals
SmallVector<unsigned, 2> llvm::SystemZVectorConstantInfo::OpVals
Definition at line 779 of file SystemZISelLowering.h.
Referenced by isVectorConstantLegal().
VecVT
MVT llvm::SystemZVectorConstantInfo::VecVT
Definition at line 780 of file SystemZISelLowering.h.
Referenced by isVectorConstantLegal().
The documentation for this struct was generated from the following files:
lib/Target/SystemZ/SystemZISelLowering.h
lib/Target/SystemZ/SystemZISelLowering.cpp