LLVM: llvm::coverage::CovMapFunctionRecordV1< IntPtrT > Struct Template Reference
llvm::coverage::CovMapFunctionRecordV1< IntPtrT > Struct Template Reference
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Types
using ThisT = CovMapFunctionRecordV1<IntPtrT>
Public Member Functions
INSTR_PROF_DATA (const uint64_t, llvm::Type::getInt64Ty(Ctx), NameRef, ConstantInt::get(llvm::Type::getInt64Ty(Ctx), IndexedInstrProf::ComputeHash(getPGOFuncNameVarInitializer(Inc->getName())))) INSTR_PROF_DATA(const uint64_t
llvm::Type::getInt64Ty (Ctx)
ConstantInt::get (llvm::Type::getInt64Ty(Ctx), Inc->getHash() ->getZExtValue())) INSTR_PROF_DATA(const IntPtrT
llvm::Type::getInt8PtrTy (Ctx)
FunctionAddr INSTR_PROF_DATA (IntPtrT, llvm::Type::getInt8PtrTy(Ctx), Values, ValuesPtrExpr) INSTR_PROF_DATA(const uint32_t
FunctionAddr llvm::Type::getInt32Ty (Ctx)
FunctionAddr ConstantInt::get (llvm::Type::getInt32Ty(Ctx), NumCounters)) INSTR_PROF_DATA(const uint16_t
FunctionAddr ConstantArray::get (Int16ArrayTy, Int16ArrayVals)) INSTR_PROF_VALUE_NODE(uint64_t
FunctionAddr llvm::Type::getInt64Ty (Ctx)
FunctionAddr ConstantInt::get (llvm::Type::GetInt64Ty(Ctx), 0)) INSTR_PROF_VALUE_NODE(uint64_t
FunctionAddr llvm::Type::getInt64Ty (Ctx)
FunctionAddr ConstantInt::get (llvm::Type::GetInt64Ty(Ctx), 0)) INSTR_PROF_VALUE_NODE(PtrToNodeT
FunctionAddr llvm::Type::getInt8PtrTy (Ctx)
FunctionAddr ConstantInt::get (llvm::Type::GetInt8PtrTy(Ctx), 0)) INSTR_PROF_RAW_HEADER(uint64_t
FunctionAddr uintptr_t CountersBegin (uintptr_t) DataBegin) VALUE_PROF_FUNC_PARAM(uint64_t
FunctionAddr uintptr_t Type::getInt64Ty (Ctx)) INSTR_PROF_COMMA VALUE_PROF_FUNC_PARAM(void *
FunctionAddr uintptr_t Type::getInt8PtrTy (Ctx)) INSTR_PROF_COMMA COVMAP_FUNC_RECORD(const IntPtrT
FunctionAddr uintptr_t llvm::Type::getInt8PtrTy (Ctx)
FunctionAddr uintptr_t llvm::ConstantExpr::getBitCast (NamePtr, llvm::Type::getInt8PtrTy(Ctx))) COVMAP_FUNC_RECORD(const uint32_t
FunctionAddr uintptr_t llvm::Type::getInt32Ty (Ctx)
FunctionAddr uintptr_t llvm::ConstantInt::get (llvm::Type::getInt32Ty(Ctx), NameValue.size())) COVMAP_FUNC_RECORD(const uint32_t
FunctionAddr uintptr_t llvm::Type::getInt32Ty (Ctx)
FunctionAddr uintptr_t llvm::ConstantInt::get (llvm::Type::getInt32Ty(Ctx), CoverageMapping.size())) COVMAP_FUNC_RECORD(const uint64_t
FunctionAddr uintptr_t llvm::Type::getInt64Ty (Ctx)
FunctionAddr uintptr_t llvm::ConstantInt::get (llvm::Type::getInt64Ty(Ctx), FuncHash)) COVMAP_HEADER(uint32_t
FunctionAddr uintptr_t llvm::ConstantInt::get (Int32Ty, NRecords)) COVMAP_HEADER(uint32_t
FunctionAddr uintptr_t llvm::ConstantInt::get (Int32Ty, FilenamesSize)) COVMAP_HEADER(uint32_t
FunctionAddr uintptr_t llvm::ConstantInt::get (Int32Ty, CoverageMappingSize)) COVMAP_HEADER(uint32_t
FunctionAddr uintptr_t llvm::ConstantInt::get (Int32Ty, CovMapVersion::CurrentVersion)) CovMapFunctionRecordV1()=delete
template<support::endianness Endian>
uint64_t getFuncHash () const
template<support::endianness Endian>
uint64_t getDataSize () const
template<support::endianness Endian>
IntPtrT getFuncNameRef () const
Return function lookup key. The value is consider opaque.
template<support::endianness Endian>
Error getFuncName (InstrProfSymtab &ProfileNames, StringRef &FuncName) const
Return the PGO name of the function.
template<support::endianness Endian>
std::pair< const char *, const ThisT * > advanceByOne (const char *MappingBuf) const
template<support::endianness Endian>
uint64_t getFilenamesRef () const
template<support::endianness Endian>
StringRef getCoverageMapping (const char *MappingBuf) const
Public Attributes
FuncHash
FunctionPointer
FunctionAddr NumCounters
FunctionAddr Int16ArrayTy
FunctionAddr NumValueSites [IPVK_Last+1]
FunctionAddr Value
FunctionAddr Count
FunctionAddr Next
FunctionAddr CountersDelta
FunctionAddr uintptr_t TargetValue
FunctionAddr uintptr_t Data
FunctionAddr uintptr_t NamePtr
FunctionAddr uintptr_t NameSize
FunctionAddr uintptr_t DataSize
FunctionAddr uintptr_t FuncHash
FunctionAddr uintptr_t Int32Ty
FunctionAddr uintptr_t NRecords
FunctionAddr uintptr_t FilenamesSize
FunctionAddr uintptr_t CoverageSize
FunctionAddr uintptr_t Version
Detailed Description
template<class IntPtrT>
struct llvm::coverage::CovMapFunctionRecordV1< IntPtrT >
Definition at line 820 of file CoverageMapping.h.
Member Typedef Documentation
ThisT
template<class IntPtrT > using llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ThisT = CovMapFunctionRecordV1<IntPtrT>
Definition at line 821 of file CoverageMapping.h.
Member Function Documentation
advanceByOne()
template<class IntPtrT > template<support::endianness Endian> std::pair< const char *, const ThisT * > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::advanceByOne (const char * MappingBuf) const inline
Definition at line 939 of file CoverageMapping.h.
ConstantArray::get()
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantArray::get (Int16ArrayTy , Int16ArrayVals)
ConstantInt::get() [1/5]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get (llvm::Type::getInt32Ty(Ctx) , NumCounters) const
ConstantInt::get() [2/5]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get (llvm::Type::GetInt64Ty(Ctx) , 0)
ConstantInt::get() [3/5]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get (llvm::Type::GetInt64Ty(Ctx) , 0)
References llvm::coverage::Counter::Expression.
ConstantInt::get() [4/5]
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get (llvm::Type::getInt64Ty(Ctx) , Inc-> getHash) ->getZExtValue() const
ConstantInt::get() [5/5]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ConstantInt::get (llvm::Type::GetInt8PtrTy(Ctx) , 0)
CountersBegin()
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::CountersBegin (uintptr_t)
getCoverageMapping()
template<class IntPtrT > template<support::endianness Endian> StringRef llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getCoverageMapping (const char * MappingBuf) const inline
Definition at line 948 of file CoverageMapping.h.
References llvm::coverage::CovMapFunctionRecordV3::getDataSize().
getDataSize()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getDataSize () const inline
Definition at line 917 of file CoverageMapping.h.
getFilenamesRef()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFilenamesRef () const inline
Definition at line 943 of file CoverageMapping.h.
getFuncHash()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncHash () const inline
Definition at line 913 of file CoverageMapping.h.
getFuncName()
template<class IntPtrT > template<support::endianness Endian> Error llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncName (InstrProfSymtab & ProfileNames, StringRef & FuncName) const inline
Return the PGO name of the function.
Definition at line 928 of file CoverageMapping.h.
getFuncNameRef()
template<class IntPtrT > template<support::endianness Endian> IntPtrT llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncNameRef () const inline
Return function lookup key. The value is consider opaque.
Definition at line 922 of file CoverageMapping.h.
References llvm::coverage::accessors::getFuncHash().
INSTR_PROF_DATA() [1/2]
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::INSTR_PROF_DATA (const uint64_t , llvm::Type::getInt64Ty(Ctx) , NameRef , ConstantInt::get(llvm::Type::getInt64Ty(Ctx), IndexedInstrProf::ComputeHash(getPGOFuncNameVarInitializer(Inc->getName())))) const
INSTR_PROF_DATA() [2/2]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::INSTR_PROF_DATA (IntPtrT , llvm::Type::getInt8PtrTy(Ctx) , Values , ValuesPtrExpr) const
llvm::ConstantExpr::getBitCast()
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantExpr::getBitCast (NamePtr , llvm::Type::getInt8PtrTy(Ctx)) const
llvm::ConstantInt::get() [1/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (Int32Ty , CoverageMappingSize)
llvm::ConstantInt::get() [2/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (Int32Ty , CovMapVersion::CurrentVersion) delete
References llvm::coverage::CounterMappingRegion::CodeRegion, llvm::coverage::CounterMappingRegion::ColumnEnd, llvm::coverage::CounterMappingRegion::ColumnStart, llvm::coverage::CounterMappingRegion::Count, llvm::coverage::CounterMappingRegion::CounterMappingRegion(), llvm::coverage::CounterMappingRegion::FileID, llvm::coverage::CounterMappingRegion::LineEnd, and llvm::coverage::CounterMappingRegion::LineStart.
llvm::ConstantInt::get() [3/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (Int32Ty , FilenamesSize)
llvm::ConstantInt::get() [4/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (Int32Ty , NRecords)
llvm::ConstantInt::get() [5/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (llvm::Type::getInt32Ty(Ctx) , CoverageMapping. size()) const
llvm::ConstantInt::get() [6/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (llvm::Type::getInt32Ty(Ctx) , NameValue. size()) const
llvm::ConstantInt::get() [7/7]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::ConstantInt::get (llvm::Type::getInt64Ty(Ctx) , FuncHash)
llvm::Type::getInt32Ty() [1/3]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt32Ty (Ctx)
llvm::Type::getInt32Ty() [2/3]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt32Ty (Ctx)
llvm::Type::getInt32Ty() [3/3]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt32Ty (Ctx)
llvm::Type::getInt64Ty() [1/4]
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty (Ctx)
llvm::Type::getInt64Ty() [2/4]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty (Ctx)
llvm::Type::getInt64Ty() [3/4]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty (Ctx)
llvm::Type::getInt64Ty() [4/4]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt64Ty (Ctx)
llvm::Type::getInt8PtrTy() [1/3]
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt8PtrTy (Ctx)
llvm::Type::getInt8PtrTy() [2/3]
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt8PtrTy (Ctx)
llvm::Type::getInt8PtrTy() [3/3]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::llvm::Type::getInt8PtrTy (Ctx)
Type::getInt64Ty()
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Type::getInt64Ty (Ctx)
Type::getInt8PtrTy()
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Type::getInt8PtrTy (Ctx) const
Member Data Documentation
Count
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Count
Definition at line 115 of file CoverageMapping.h.
CountersDelta
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::CountersDelta
Definition at line 139 of file CoverageMapping.h.
CoverageSize
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::CoverageSize
Definition at line 257 of file CoverageMapping.h.
Data
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Data
Definition at line 159 of file CoverageMapping.h.
DataSize
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::DataSize
Definition at line 224 of file CoverageMapping.h.
FilenamesSize
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::FilenamesSize
Definition at line 255 of file CoverageMapping.h.
FuncHash [1/2]
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::FuncHash
Definition at line 76 of file CoverageMapping.h.
FuncHash [2/2]
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::FuncHash
Definition at line 227 of file CoverageMapping.h.
FunctionPointer
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::FunctionPointer
Definition at line 84 of file CoverageMapping.h.
Int16ArrayTy
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Int16ArrayTy
Definition at line 90 of file CoverageMapping.h.
Int32Ty
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Int32Ty
Definition at line 253 of file CoverageMapping.h.
NamePtr
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::NamePtr
Definition at line 213 of file CoverageMapping.h.
NameSize
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::NameSize
Definition at line 215 of file CoverageMapping.h.
Next
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Next
Definition at line 117 of file CoverageMapping.h.
NRecords
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::NRecords
Definition at line 253 of file CoverageMapping.h.
NumCounters
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::NumCounters
Definition at line 88 of file CoverageMapping.h.
NumValueSites
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::NumValueSites[IPVK_Last+1]
Definition at line 90 of file CoverageMapping.h.
TargetValue
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::TargetValue
Definition at line 157 of file CoverageMapping.h.
Value
template<class IntPtrT > FunctionAddr llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Value
Definition at line 113 of file CoverageMapping.h.
Version
template<class IntPtrT > FunctionAddr uintptr_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::Version
Definition at line 259 of file CoverageMapping.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h