LLVM: llvm::BlockFrequencyInfoImplBase::LoopData Struct Reference
llvm::BlockFrequencyInfoImplBase::LoopData Struct Reference
Data about a loop.
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
Public Types
using ExitMap = SmallVector<std::pair<BlockNode, BlockMass>, 4>
using NodeList = SmallVector<BlockNode, 4>
using HeaderMassList = SmallVector<BlockMass, 1>
Public Member Functions
LoopData (LoopData *Parent, const BlockNode &Header)
template<class It1 , class It2 >
LoopData (LoopData *Parent, It1 FirstHeader, It1 LastHeader, It2 FirstOther, It2 LastOther)
bool isHeader (const BlockNode &Node) const
BlockNode getHeader () const
bool isIrreducible () const
HeaderMassList::difference_type getHeaderIndex (const BlockNode &B)
NodeList::const_iterator members_begin () const
NodeList::const_iterator members_end () const
iterator_range< NodeList::const_iterator > members () const
Public Attributes
LoopData * Parent
The parent loop.
bool IsPackaged = false
Whether this has been packaged.
uint32_t NumHeaders = 1
Number of headers.
ExitMap Exits
Successor edges (and weights).
NodeList Nodes
Header and the members of the loop.
HeaderMassList BackedgeMass
Mass returned to each loop header.
BlockMass Mass
Scaled64 Scale
Detailed Description
Data about a loop.
Contains the data necessary to represent a loop as a pseudo-node once it's packaged.
Definition at line 223 of file BlockFrequencyInfoImpl.h.
Member Typedef Documentation
ExitMap
using llvm::BlockFrequencyInfoImplBase::LoopData::ExitMap = SmallVector<std::pair<BlockNode, BlockMass>, 4>
Definition at line 224 of file BlockFrequencyInfoImpl.h.
HeaderMassList
using llvm::BlockFrequencyInfoImplBase::LoopData::HeaderMassList = SmallVector<BlockMass, 1>
Definition at line 226 of file BlockFrequencyInfoImpl.h.
NodeList
using llvm::BlockFrequencyInfoImplBase::LoopData::NodeList = SmallVector<BlockNode, 4>
Definition at line 225 of file BlockFrequencyInfoImpl.h.
Constructor & Destructor Documentation
LoopData() [1/2]
llvm::BlockFrequencyInfoImplBase::LoopData::LoopData (LoopData * Parent, const BlockNode & Header) inline
Definition at line 237 of file BlockFrequencyInfoImpl.h.
LoopData() [2/2]
template<class It1 , class It2 > llvm::BlockFrequencyInfoImplBase::LoopData::LoopData (LoopData * Parent, It1 FirstHeader, It1 LastHeader, It2 FirstOther, It2 LastOther) inline
Definition at line 241 of file BlockFrequencyInfoImpl.h.
References BackedgeMass, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::insert(), Nodes, NumHeaders, llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase< Size_T >::size().
Member Function Documentation
getHeader()
BlockNode llvm::BlockFrequencyInfoImplBase::LoopData::getHeader () const inline
Definition at line 256 of file BlockFrequencyInfoImpl.h.
References Nodes.
Referenced by llvm::BlockFrequencyInfoImplBase::addLoopSuccessorsToDist(), llvm::bfi_detail::IrreducibleGraph::addNodesInLoop(), and llvm::BlockFrequencyInfoImplBase::getLoopName().
getHeaderIndex()
HeaderMassList::difference_type llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex (const BlockNode & B) inline
Definition at line 259 of file BlockFrequencyInfoImpl.h.
References assert(), B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), isHeader(), isIrreducible(), Nodes, and NumHeaders.
Referenced by llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), and llvm::BlockFrequencyInfoImplBase::distributeMass().
isHeader()
bool llvm::BlockFrequencyInfoImplBase::LoopData::isHeader (const BlockNode & Node) const inline
Definition at line 249 of file BlockFrequencyInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), isIrreducible(), Nodes, and NumHeaders.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge(), llvm::BlockFrequencyInfoImplBase::addToDist(), getHeaderIndex(), llvm::BlockFrequencyInfoImplBase::WorkingData::isDoubleLoopHeader(), and llvm::BlockFrequencyInfoImplBase::WorkingData::isLoopHeader().
isIrreducible()
bool llvm::BlockFrequencyInfoImplBase::LoopData::isIrreducible () const inline
Definition at line 257 of file BlockFrequencyInfoImpl.h.
References NumHeaders.
Referenced by llvm::BlockFrequencyInfoImplBase::addToDist(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), getHeaderIndex(), llvm::BlockFrequencyInfoImplBase::getLoopName(), llvm::BlockFrequencyInfoImplBase::WorkingData::isDoubleLoopHeader(), and isHeader().
members()
iterator_range< NodeList::const_iterator > llvm::BlockFrequencyInfoImplBase::LoopData::members () const inline
Definition at line 272 of file BlockFrequencyInfoImpl.h.
References llvm::make_range(), members_begin(), and members_end().
members_begin()
NodeList::const_iterator llvm::BlockFrequencyInfoImplBase::LoopData::members_begin () const inline
Definition at line 267 of file BlockFrequencyInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), Nodes, and NumHeaders.
Referenced by members().
members_end()
NodeList::const_iterator llvm::BlockFrequencyInfoImplBase::LoopData::members_end () const inline
Definition at line 271 of file BlockFrequencyInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and Nodes.
Referenced by members().
Member Data Documentation
BackedgeMass
HeaderMassList llvm::BlockFrequencyInfoImplBase::LoopData::BackedgeMass
Mass returned to each loop header.
Definition at line 233 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::computeLoopScale(), llvm::BlockFrequencyInfoImplBase::distributeMass(), LoopData(), and llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible().
Exits
ExitMap llvm::BlockFrequencyInfoImplBase::LoopData::Exits
Successor edges (and weights).
Definition at line 231 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::addLoopSuccessorsToDist(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::BlockFrequencyInfoImplBase::packageLoop(), and llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible().
IsPackaged
bool llvm::BlockFrequencyInfoImplBase::LoopData::IsPackaged = false
Whether this has been packaged.
Definition at line 229 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::WorkingData::getPackagedLoop(), llvm::BlockFrequencyInfoImplBase::WorkingData::isADoublePackage(), llvm::BlockFrequencyInfoImplBase::WorkingData::isAPackage(), and llvm::BlockFrequencyInfoImplBase::packageLoop().
Mass
BlockMass llvm::BlockFrequencyInfoImplBase::LoopData::Mass
Definition at line 234 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::WorkingData::getMass().
Nodes
NodeList llvm::BlockFrequencyInfoImplBase::LoopData::Nodes
Header and the members of the loop.
Definition at line 232 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addNodesInLoop(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), getHeader(), getHeaderIndex(), llvm::bfi_detail::IrreducibleGraph::initialize(), isHeader(), LoopData(), members_begin(), members_end(), llvm::BlockFrequencyInfoImplBase::packageLoop(), and llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible().
NumHeaders
uint32_t llvm::BlockFrequencyInfoImplBase::LoopData::NumHeaders = 1
Number of headers.
Definition at line 230 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), getHeaderIndex(), isHeader(), isIrreducible(), LoopData(), and members_begin().
Parent
LoopData* llvm::BlockFrequencyInfoImplBase::LoopData::Parent
The parent loop.
Definition at line 228 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::WorkingData::getContainingLoop(), llvm::BlockFrequencyInfoImplBase::WorkingData::getMass(), llvm::BlockFrequencyInfoImplBase::WorkingData::getPackagedLoop(), llvm::BlockFrequencyInfoImplBase::WorkingData::isADoublePackage(), and llvm::BlockFrequencyInfoImplBase::WorkingData::isDoubleLoopHeader().
Scale
Scaled64 llvm::BlockFrequencyInfoImplBase::LoopData::Scale
Definition at line 235 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::computeLoopScale().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/BlockFrequencyInfoImpl.h