LLVM: llvm::FixedScalableVFPair Struct Reference
llvm::FixedScalableVFPair Struct Reference
A class that represents two vectorization factors (initialized with 0 by default).
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Public Member Functions
FixedScalableVFPair ()
FixedScalableVFPair (const ElementCount &Max)
FixedScalableVFPair (const ElementCount &FixedVF, const ElementCount &ScalableVF)
operator bool () const
bool hasVector () const
Static Public Member Functions
static FixedScalableVFPair getNone ()
Public Attributes
ElementCount FixedVF
ElementCount ScalableVF
Detailed Description
A class that represents two vectorization factors (initialized with 0 by default).
One for fixed-width vectorization and one for scalable vectorization. This can be used by the vectorizer to choose from a range of fixed and/or scalable VFs in order to find the most cost-effective VF to vectorize with.
Definition at line 224 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
FixedScalableVFPair() [1/3]
llvm::FixedScalableVFPair::FixedScalableVFPair () inline
Definition at line 228 of file LoopVectorizationPlanner.h.
Referenced by getNone().
FixedScalableVFPair() [2/3]
llvm::FixedScalableVFPair::FixedScalableVFPair (const ElementCount & Max) inline
Definition at line 231 of file LoopVectorizationPlanner.h.
References FixedVF, and ScalableVF.
FixedScalableVFPair() [3/3]
llvm::FixedScalableVFPair::FixedScalableVFPair (const ElementCount & FixedVF, const ElementCount & ScalableVF) inline
Definition at line 234 of file LoopVectorizationPlanner.h.
References assert(), FixedVF, llvm::LinearPolySize< LeafTy >::isScalable(), and ScalableVF.
Member Function Documentation
getNone()
static FixedScalableVFPair llvm::FixedScalableVFPair::getNone () inline static
Definition at line 241 of file LoopVectorizationPlanner.h.
References FixedScalableVFPair().
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF().
hasVector()
bool llvm::FixedScalableVFPair::hasVector () const inline
Returns
true if either fixed- or scalable VF is a valid vector VF.
Definition at line 247 of file LoopVectorizationPlanner.h.
References FixedVF, llvm::ElementCount::isVector(), and ScalableVF.
Referenced by llvm::LoopVectorizationPlanner::plan().
operator bool()
llvm::FixedScalableVFPair::operator bool () const inline explicit
Returns
true if either fixed- or scalable VF is non-zero.
Definition at line 244 of file LoopVectorizationPlanner.h.
References FixedVF, and ScalableVF.
Member Data Documentation
FixedVF
ElementCount llvm::FixedScalableVFPair::FixedVF
Definition at line 225 of file LoopVectorizationPlanner.h.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), FixedScalableVFPair(), FixedScalableVFPair(), hasVector(), operator bool(), and llvm::LoopVectorizationPlanner::plan().
ScalableVF
ElementCount llvm::FixedScalableVFPair::ScalableVF
Definition at line 226 of file LoopVectorizationPlanner.h.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), FixedScalableVFPair(), FixedScalableVFPair(), hasVector(), operator bool(), and llvm::LoopVectorizationPlanner::plan().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h