LLVM: llvm::rdf::PhiUseNode Struct Reference
llvm::rdf::PhiUseNode Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
NodeId getPredecessor () const
void setPredecessor (NodeId B)
Public Member Functions inherited from llvm::rdf::UseNode
void linkToDef (NodeId Self, NodeAddr< DefNode * > DA)
Public Member Functions inherited from llvm::rdf::RefNode
RefNode ()=default
RegisterRef getRegRef (const DataFlowGraph &G) const
MachineOperand & getOp ()
void setRegRef (RegisterRef RR, DataFlowGraph &G)
void setRegRef (MachineOperand *Op, DataFlowGraph &G)
NodeId getReachingDef () const
void setReachingDef (NodeId RD)
NodeId getSibling () const
void setSibling (NodeId Sib)
bool isUse () const
bool isDef () const
template<typename Predicate >
NodeAddr< RefNode * > getNextRef (RegisterRef RR, Predicate P, bool NextOnly, const DataFlowGraph &G)
NodeAddr< NodeBase * > getOwner (const DataFlowGraph &G)
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (NodeAddr< NodeBase * > NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Public Attributes inherited from llvm::rdf::NodeBase
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct Ref
Code_struct Code
};
Detailed Description
Definition at line 579 of file RDFGraph.h.
Member Function Documentation
getPredecessor()
NodeId llvm::rdf::PhiUseNode::getPredecessor () const inline
Definition at line 580 of file RDFGraph.h.
References assert(), llvm::rdf::NodeBase::getFlags(), llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::NodeBase::Ref_struct::PhiU, llvm::rdf::NodeBase::PhiU_struct::PredB, and llvm::rdf::NodeBase::Ref.
setPredecessor()
void llvm::rdf::PhiUseNode::setPredecessor (NodeId B) inline
Definition at line 584 of file RDFGraph.h.
References assert(), B, llvm::rdf::NodeBase::getFlags(), llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::NodeBase::Ref_struct::PhiU, llvm::rdf::NodeBase::PhiU_struct::PredB, and llvm::rdf::NodeBase::Ref.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RDFGraph.h