LLVM: llvm::objcopy::ELFConfig Struct Reference
llvm::objcopy::ELFConfig Struct Reference
#include "llvm/ObjCopy/ELF/ELFConfig.h"
Public Attributes
uint8_t NewSymbolVisibility = (uint8_t)ELF::STV_DEFAULT
std::function< uint64_t(uint64_t)> EntryExpr
bool AllowBrokenLinks = false
bool KeepFileSymbols = false
bool LocalizeHidden = false
Detailed Description
Definition at line 21 of file ELFConfig.h.
Member Data Documentation
AllowBrokenLinks
bool llvm::objcopy::ELFConfig::AllowBrokenLinks = false
Definition at line 30 of file ELFConfig.h.
Referenced by handleArgs(), and replaceAndRemoveSections().
EntryExpr
std::function<uint64_t(uint64_t)> llvm::objcopy::ELFConfig::EntryExpr
Definition at line 28 of file ELFConfig.h.
Referenced by handleArgs().
KeepFileSymbols
bool llvm::objcopy::ELFConfig::KeepFileSymbols = false
Definition at line 31 of file ELFConfig.h.
Referenced by replaceAndRemoveSections(), and updateAndRemoveSymbols().
LocalizeHidden
bool llvm::objcopy::ELFConfig::LocalizeHidden = false
Definition at line 32 of file ELFConfig.h.
Referenced by updateAndRemoveSymbols().
NewSymbolVisibility
uint8_t llvm::objcopy::ELFConfig::NewSymbolVisibility = (uint8_t)ELF::STV_DEFAULT
Definition at line 22 of file ELFConfig.h.
Referenced by llvm::objcopy::elf::executeObjcopyOnRawBinary(), and handleArgs().
The documentation for this struct was generated from the following file:
include/llvm/ObjCopy/ELF/ELFConfig.h