LLVM: AA::PointerInfo::State::Accesses Struct Reference
AA::PointerInfo::State::Accesses Struct Reference
We store accesses in a set with the instruction as key.
Public Types
using vec_iterator = decltype(Accesses)::iterator
using iterator = decltype(Map)::const_iterator
Public Member Functions
unsigned size () const
vec_iterator begin ()
vec_iterator end ()
iterator find (AAPointerInfo::Access &Acc)
iterator find_end ()
AAPointerInfo::Access & get (iterator &It)
void insert (AAPointerInfo::Access &Acc)
Public Attributes
SmallVector< AAPointerInfo::Access, 4 > Accesses
DenseMap< const Instruction *, unsigned > Map
Detailed Description
We store accesses in a set with the instruction as key.
Definition at line 822 of file AttributorAttributes.cpp.
Member Typedef Documentation
iterator
using AA::PointerInfo::State::Accesses::iterator = decltype(Map)::const_iterator
Definition at line 832 of file AttributorAttributes.cpp.
vec_iterator
using AA::PointerInfo::State::Accesses::vec_iterator = decltype(Accesses)::iterator
Definition at line 828 of file AttributorAttributes.cpp.
Member Function Documentation
begin()
vec_iterator AA::PointerInfo::State::Accesses::begin () inline
Definition at line 829 of file AttributorAttributes.cpp.
References begin().
Referenced by begin().
end()
vec_iterator AA::PointerInfo::State::Accesses::end () inline
Definition at line 830 of file AttributorAttributes.cpp.
References end().
Referenced by end().
find()
iterator AA::PointerInfo::State::Accesses::find (AAPointerInfo::Access & Acc) inline
Definition at line 833 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::AAPointerInfo::Access::getRemoteInst(), and Map.
find_end()
iterator AA::PointerInfo::State::Accesses::find_end () inline
Definition at line 836 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and Map.
get()
AAPointerInfo::Access & AA::PointerInfo::State::Accesses::get (iterator & It) inline
Definition at line 838 of file AttributorAttributes.cpp.
insert()
void AA::PointerInfo::State::Accesses::insert (AAPointerInfo::Access & Acc) inline
Definition at line 842 of file AttributorAttributes.cpp.
References llvm::AAPointerInfo::Access::getRemoteInst(), Map, and size().
size()
unsigned AA::PointerInfo::State::Accesses::size () const inline
Definition at line 826 of file AttributorAttributes.cpp.
References size().
Referenced by insert(), and size().
Member Data Documentation
Accesses
SmallVector<AAPointerInfo::Access, 4> AA::PointerInfo::State::Accesses::Accesses
Definition at line 823 of file AttributorAttributes.cpp.
Map
DenseMap<const Instruction *, unsigned> AA::PointerInfo::State::Accesses::Map
Definition at line 824 of file AttributorAttributes.cpp.
Referenced by find(), find_end(), and insert().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp