LLVM: llvm::omp::VariantMatchInfo Struct Reference
llvm::omp::VariantMatchInfo Struct Reference
Variant match information describes the required traits and how they are scored (via the ScoresMap).
#include "llvm/Frontend/OpenMP/OMPContext.h"
Public Member Functions
void addTrait (TraitProperty Property, StringRef RawString, APInt *Score=nullptr)
Add the trait Property to the required trait set.
void addTrait (TraitSet Set, TraitProperty Property, StringRef RawString, APInt *Score=nullptr)
Add the trait Property which is in set Set to the required trait set.
Public Attributes
BitVector RequiredTraits = BitVector(unsigned(TraitProperty::Last) + 1)
SmallVector< StringRef, 8 > ISATraits
SmallVector< TraitProperty, 8 > ConstructTraits
SmallDenseMap< TraitProperty, APInt > ScoreMap
Detailed Description
Variant match information describes the required traits and how they are scored (via the ScoresMap).
In addition, the required consturct nesting is decribed as well.
Definition at line 119 of file OMPContext.h.
Member Function Documentation
addTrait() [1/2]
void llvm::omp::VariantMatchInfo::addTrait (TraitProperty Property, StringRef RawString, APInt * Score = nullptr) inline
Add the trait Property to the required trait set.
RawString is the string we parsed and derived Property from. If Score is not null, it recorded as well. If Property is in the construct set it is recorded in-order in the ConstructTraits as well.
Definition at line 124 of file OMPContext.h.
References addTrait(), and llvm::omp::getOpenMPContextTraitSetForProperty().
Referenced by addTrait().
addTrait() [2/2]
void llvm::omp::VariantMatchInfo::addTrait (TraitSet Set, TraitProperty Property, StringRef RawString, APInt * Score = nullptr) inline
Add the trait Property which is in set Set to the required trait set.
RawString is the string we parsed and derived Property from. If Score is not null, it recorded as well. If Set is the construct set it is recorded in-order in the ConstructTraits as well.
Definition at line 133 of file OMPContext.h.
References ConstructTraits, ISATraits, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RequiredTraits, ScoreMap, and llvm::BitVector::set().
Member Data Documentation
ConstructTraits
SmallVector<TraitProperty, 8> llvm::omp::VariantMatchInfo::ConstructTraits
Definition at line 150 of file OMPContext.h.
Referenced by addTrait(), getVariantMatchScore(), isStrictSubset(), and isVariantApplicableInContextHelper().
ISATraits
SmallVector<StringRef, 8> llvm::omp::VariantMatchInfo::ISATraits
Definition at line 149 of file OMPContext.h.
Referenced by addTrait(), and isVariantApplicableInContextHelper().
RequiredTraits
BitVector llvm::omp::VariantMatchInfo::RequiredTraits = BitVector(unsigned(TraitProperty::Last) + 1)
Definition at line 148 of file OMPContext.h.
Referenced by addTrait(), getVariantMatchScore(), isStrictSubset(), and isVariantApplicableInContextHelper().
ScoreMap
SmallDenseMap<TraitProperty, APInt> llvm::omp::VariantMatchInfo::ScoreMap
Definition at line 151 of file OMPContext.h.
Referenced by addTrait(), and getVariantMatchScore().
The documentation for this struct was generated from the following file:
include/llvm/Frontend/OpenMP/OMPContext.h