LLVM: llvm::MCDwarfLineTableHeader Struct Reference
llvm::MCDwarfLineTableHeader Struct Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineTableHeader ()=default
Expected< unsigned > tryGetFile (StringRef &Directory, StringRef &FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber=0)
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, Optional< MCDwarfLineStr > &LineStr) const
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, Optional< MCDwarfLineStr > &LineStr) const
void resetMD5Usage ()
void trackMD5Usage (bool MD5Used)
bool isMD5UsageConsistent () const
void setRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source)
void resetFileTable ()
Public Attributes
MCSymbol * Label = nullptr
SmallVector< std::string, 3 > MCDwarfDirs
SmallVector< MCDwarfFile, 3 > MCDwarfFiles
StringMap< unsigned > SourceIdMap
std::string CompilationDir
MCDwarfFile RootFile
bool HasSource = false
Detailed Description
Definition at line 257 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineTableHeader()
llvm::MCDwarfLineTableHeader::MCDwarfLineTableHeader () default
Member Function Documentation
Emit() [1/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, Optional< MCDwarfLineStr > & LineStr) const
Definition at line 482 of file MCDwarf.cpp.
References llvm::MCContext::createTempSymbol(), DWARF2_LINE_DEFAULT_IS_STMT, llvm::MCDwarfLineTableParams::DWARF2LineBase, llvm::MCDwarfLineTableParams::DWARF2LineRange, llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitDwarfLineStartLabel(), llvm::MCStreamer::emitDwarfUnitLength(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MCContext::getDwarfVersion(), llvm::MCAsmInfo::getMinInstAlignment(), Label, and llvm::ArrayRef< T >::size().
Emit() [2/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, Optional< MCDwarfLineStr > & LineStr) const
Definition at line 293 of file MCDwarf.cpp.
References llvm::array_lengthof(), assert(), llvm::MCDwarfLineTableParams::DWARF2LineOpcodeBase, Emit(), and llvm::makeArrayRef().
Referenced by llvm::MCDwarfDwoLineTable::Emit(), Emit(), and llvm::MCDwarfLineTable::emitCU().
isMD5UsageConsistent()
bool llvm::MCDwarfLineTableHeader::isMD5UsageConsistent () const inline
Definition at line 292 of file MCDwarf.h.
References MCDwarfFiles.
Referenced by llvm::MCDwarfLineTable::isMD5UsageConsistent().
resetFileTable()
void llvm::MCDwarfLineTableHeader::resetFileTable () inline
Definition at line 308 of file MCDwarf.h.
References llvm::SmallVectorImpl< T >::clear(), HasSource, MCDwarfDirs, MCDwarfFiles, llvm::MCDwarfFile::Name, resetMD5Usage(), and RootFile.
Referenced by llvm::MCDwarfLineTable::resetFileTable().
resetMD5Usage()
void llvm::MCDwarfLineTableHeader::resetMD5Usage () inline
Definition at line 284 of file MCDwarf.h.
Referenced by resetFileTable().
setRootFile()
void llvm::MCDwarfLineTableHeader::setRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source) inline
Definition at line 296 of file MCDwarf.h.
References llvm::MCDwarfFile::Checksum, CompilationDir, llvm::MCDwarfFile::DirIndex, llvm::Optional< T >::has_value(), HasSource, llvm::MCDwarfFile::Name, RootFile, llvm::MCDwarfFile::Source, and trackMD5Usage().
Referenced by llvm::MCDwarfDwoLineTable::maybeSetRootFile().
trackMD5Usage()
void llvm::MCDwarfLineTableHeader::trackMD5Usage (bool MD5Used) inline
Definition at line 288 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::setRootFile(), setRootFile(), and tryGetFile().
tryGetFile()
Expected< unsigned > MCDwarfLineTableHeader::tryGetFile (StringRef & Directory, StringRef & FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber = 0)
Definition at line 580 of file MCDwarf.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), CompilationDir, llvm::StringRef::empty(), llvm::sys::path::filename(), llvm::find(), llvm::Optional< T >::has_value(), HasSource, llvm::inconvertibleErrorCode(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), isRootFile(), llvm::make_error(), MCDwarfDirs, MCDwarfFiles, llvm::None, llvm::sys::path::parent_path(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RootFile, llvm::SmallVectorBase< Size_T >::size(), SourceIdMap, llvm::dwarf::toStringRef(), and trackMD5Usage().
Referenced by llvm::MCDwarfDwoLineTable::getFile(), and llvm::MCDwarfLineTable::tryGetFile().
Member Data Documentation
CompilationDir
std::string llvm::MCDwarfLineTableHeader::CompilationDir
Definition at line 262 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::setRootFile(), setRootFile(), and tryGetFile().
HasSource
bool llvm::MCDwarfLineTableHeader::HasSource = false
Definition at line 264 of file MCDwarf.h.
Referenced by resetFileTable(), llvm::MCDwarfLineTable::setRootFile(), setRootFile(), and tryGetFile().
Label
MCSymbol* llvm::MCDwarfLineTableHeader::Label = nullptr
Definition at line 258 of file MCDwarf.h.
Referenced by Emit(), llvm::MCDwarfLineTable::getLabel(), and llvm::MCDwarfLineTable::setLabel().
MCDwarfDirs
SmallVector<std::string, 3> llvm::MCDwarfLineTableHeader::MCDwarfDirs
Definition at line 259 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::getMCDwarfDirs(), llvm::MCDwarfLineTable::getMCDwarfDirs(), resetFileTable(), and tryGetFile().
MCDwarfFiles
SmallVector<MCDwarfFile, 3> llvm::MCDwarfLineTableHeader::MCDwarfFiles
Definition at line 260 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::getMCDwarfFiles(), llvm::MCDwarfLineTable::getMCDwarfFiles(), isMD5UsageConsistent(), resetFileTable(), and tryGetFile().
RootFile
MCDwarfFile llvm::MCDwarfLineTableHeader::RootFile
Definition at line 263 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::getRootFile(), llvm::MCDwarfLineTable::getRootFile(), llvm::MCDwarfLineTable::hasRootFile(), llvm::MCDwarfDwoLineTable::maybeSetRootFile(), resetFileTable(), llvm::MCDwarfLineTable::setRootFile(), setRootFile(), and tryGetFile().
SourceIdMap
StringMap<unsigned> llvm::MCDwarfLineTableHeader::SourceIdMap
Definition at line 261 of file MCDwarf.h.
Referenced by tryGetFile().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp