LLVM: llvm::slpvectorizer::BoUpSLP::EdgeInfo Struct Reference
llvm::slpvectorizer::BoUpSLP::EdgeInfo Struct Reference
This structure holds any data we need about the edges being traversed during buildTree_rec().
Public Member Functions
EdgeInfo ()=default
EdgeInfo (TreeEntry *UserTE, unsigned EdgeIdx)
void dump (raw_ostream &OS) const
Debug print.
LLVM_DUMP_METHOD void dump () const
Public Attributes
TreeEntry * UserTE = nullptr
The user TreeEntry.
unsigned EdgeIdx = UINT_MAX
The operand index of the use.
Friends
raw_ostream & operator<< (raw_ostream &OS, const BoUpSLP::EdgeInfo &EI)
Detailed Description
This structure holds any data we need about the edges being traversed during buildTree_rec().
We keep track of: (i) the user TreeEntry index, and (ii) the index of the edge.
Definition at line 1030 of file SLPVectorizer.cpp.
Constructor & Destructor Documentation
EdgeInfo() [1/2]
llvm::slpvectorizer::BoUpSLP::EdgeInfo::EdgeInfo () default
EdgeInfo() [2/2]
llvm::slpvectorizer::BoUpSLP::EdgeInfo::EdgeInfo (TreeEntry * UserTE, unsigned EdgeIdx) inline
Definition at line 1032 of file SLPVectorizer.cpp.
Member Function Documentation
dump() [1/2]
LLVM_DUMP_METHOD void llvm::slpvectorizer::BoUpSLP::EdgeInfo::dump () const inline
Definition at line 1049 of file SLPVectorizer.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::slpvectorizer::BoUpSLP::EdgeInfo::dump (raw_ostream & OS) const inline
Debug print.
Definition at line 1045 of file SLPVectorizer.cpp.
References EdgeIdx, and UserTE.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const BoUpSLP::EdgeInfo & EI) friend
Definition at line 1039 of file SLPVectorizer.cpp.
Member Data Documentation
EdgeIdx
unsigned llvm::slpvectorizer::BoUpSLP::EdgeInfo::EdgeIdx = UINT_MAX
The operand index of the use.
Definition at line 1037 of file SLPVectorizer.cpp.
Referenced by dump(), and llvm::slpvectorizer::BoUpSLP::reorderBottomToTop().
UserTE
TreeEntry* llvm::slpvectorizer::BoUpSLP::EdgeInfo::UserTE = nullptr
The user TreeEntry.
Definition at line 1035 of file SLPVectorizer.cpp.
Referenced by dump(), and llvm::slpvectorizer::BoUpSLP::reorderBottomToTop().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp