LLVM: llvm::ELFYAML::Object Struct Reference
llvm::ELFYAML::Object Struct Reference
#include "llvm/ObjectYAML/ELFYAML.h"
Public Member Functions
std::vector< Section * > getSections ()
const SectionHeaderTable & getSectionHeaderTable () const
ELF_ELFOSABI getOSAbi () const
unsigned getMachine () const
Public Attributes
FileHeader Header
std::vector< ProgramHeader > ProgramHeaders
std::vector< std::unique_ptr< Chunk > > Chunks
Optional< std::vector< Symbol > > Symbols
Optional< std::vector< Symbol > > DynamicSymbols
Optional< DWARFYAML::Data > DWARF
Detailed Description
Definition at line 694 of file ELFYAML.h.
Member Function Documentation
getMachine()
unsigned llvm::ELFYAML::Object::getMachine () const
Definition at line 34 of file ELFYAML.cpp.
References llvm::ELF::EM_NONE, Header, and llvm::ELFYAML::FileHeader::Machine.
Referenced by isMips64EL().
getOSAbi()
ELF_ELFOSABI llvm::ELFYAML::Object::getOSAbi () const
Definition at line 32 of file ELFYAML.cpp.
References Header, and llvm::ELFYAML::FileHeader::OSABI.
getSectionHeaderTable()
const SectionHeaderTable & llvm::ELFYAML::Object::getSectionHeaderTable () const inline
Definition at line 718 of file ELFYAML.h.
References llvm::CallingConv::C, Chunks, llvm::dyn_cast(), and llvm_unreachable.
getSections()
std::vector< Section * > llvm::ELFYAML::Object::getSections () inline
Definition at line 710 of file ELFYAML.h.
References Chunks, and llvm::dyn_cast().
Member Data Documentation
Chunks
std::vector<std::unique_ptr<Chunk> > llvm::ELFYAML::Object::Chunks
Definition at line 700 of file ELFYAML.h.
Referenced by getSectionHeaderTable(), and getSections().
DWARF
Optional<DWARFYAML::Data> llvm::ELFYAML::Object::DWARF
Definition at line 708 of file ELFYAML.h.
DynamicSymbols
Optional<std::vector<Symbol> > llvm::ELFYAML::Object::DynamicSymbols
Definition at line 707 of file ELFYAML.h.
Header
FileHeader llvm::ELFYAML::Object::Header
Definition at line 695 of file ELFYAML.h.
Referenced by getMachine(), getOSAbi(), isMips64EL(), and llvm::yaml::yaml2elf().
ProgramHeaders
std::vector<ProgramHeader> llvm::ELFYAML::Object::ProgramHeaders
Definition at line 696 of file ELFYAML.h.
Symbols
Optional<std::vector<Symbol> > llvm::ELFYAML::Object::Symbols
Definition at line 706 of file ELFYAML.h.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/ELFYAML.h
lib/ObjectYAML/ELFYAML.cpp