LLVM: FlattenInfo Struct Reference
FlattenInfo Struct Reference
Public Member Functions
FlattenInfo (Loop *OL, Loop *IL)
bool isNarrowInductionPhi (PHINode *Phi)
bool isInnerLoopIncrement (User *U)
bool isOuterLoopIncrement (User *U)
bool isInnerLoopTest (User *U)
bool checkOuterInductionPhiUsers (SmallPtrSet< Value *, 4 > &ValidOuterPHIUses)
bool matchLinearIVUser (User *U, Value *InnerTripCount, SmallPtrSet< Value *, 4 > &ValidOuterPHIUses)
bool checkInnerInductionPhiUsers (SmallPtrSet< Value *, 4 > &ValidOuterPHIUses)
Public Attributes
Loop * OuterLoop = nullptr
Loop * InnerLoop = nullptr
PHINode * InnerInductionPHI = nullptr
PHINode * OuterInductionPHI = nullptr
Value * InnerTripCount = nullptr
Value * OuterTripCount = nullptr
SmallPtrSet< Value *, 4 > LinearIVUses
BinaryOperator * InnerIncrement = nullptr
BinaryOperator * OuterIncrement = nullptr
BranchInst * InnerBranch = nullptr
BranchInst * OuterBranch = nullptr
SmallPtrSet< PHINode *, 4 > InnerPHIsToTransform
bool Widened = false
PHINode * NarrowInnerInductionPHI = nullptr
PHINode * NarrowOuterInductionPHI = nullptr
Detailed Description
Definition at line 110 of file LoopFlatten.cpp.
Constructor & Destructor Documentation
FlattenInfo()
FlattenInfo::FlattenInfo (Loop * OL, Loop * IL) inline
Definition at line 145 of file LoopFlatten.cpp.
Member Function Documentation
checkInnerInductionPhiUsers()
bool FlattenInfo::checkInnerInductionPhiUsers (SmallPtrSet< Value *, 4 > & ValidOuterPHIUses) inline
Definition at line 236 of file LoopFlatten.cpp.
References llvm::cast(), InnerInductionPHI, InnerTripCount, llvm::isa(), isInnerLoopIncrement(), isInnerLoopTest(), matchLinearIVUser(), llvm::Value::users(), and Widened.
Referenced by checkIVUsers().
checkOuterInductionPhiUsers()
bool FlattenInfo::checkOuterInductionPhiUsers (SmallPtrSet< Value *, 4 > & ValidOuterPHIUses) inline
Definition at line 163 of file LoopFlatten.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::dyn_cast(), isOuterLoopIncrement(), LLVM_DEBUG, OuterInductionPHI, and llvm::Value::users().
Referenced by checkIVUsers().
isInnerLoopIncrement()
bool FlattenInfo::isInnerLoopIncrement (User * U) inline
Definition at line 153 of file LoopFlatten.cpp.
References InnerIncrement.
Referenced by checkInnerInductionPhiUsers().
isInnerLoopTest()
bool FlattenInfo::isInnerLoopTest (User * U) inline
Definition at line 159 of file LoopFlatten.cpp.
References llvm::BranchInst::getCondition(), and InnerBranch.
Referenced by checkInnerInductionPhiUsers().
isNarrowInductionPhi()
bool FlattenInfo::isNarrowInductionPhi (PHINode * Phi) inline
Definition at line 147 of file LoopFlatten.cpp.
References NarrowInnerInductionPHI, NarrowOuterInductionPHI, and Widened.
Referenced by checkPHIs().
isOuterLoopIncrement()
bool FlattenInfo::isOuterLoopIncrement (User * U) inline
Definition at line 156 of file LoopFlatten.cpp.
References OuterIncrement.
Referenced by checkOuterInductionPhiUsers().
matchLinearIVUser()
bool FlattenInfo::matchLinearIVUser (User * U, Value * InnerTripCount, SmallPtrSet< Value *, 4 > & ValidOuterPHIUses) inline
Definition at line 192 of file LoopFlatten.cpp.
References assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::Value::getType(), InnerInductionPHI, InnerTripCount, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), LinearIVUses, LLVM_DEBUG, llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), OuterInductionPHI, and Widened.
Referenced by checkInnerInductionPhiUsers().
Member Data Documentation
InnerBranch
BranchInst* FlattenInfo::InnerBranch = nullptr
Definition at line 130 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), and isInnerLoopTest().
InnerIncrement
BinaryOperator* FlattenInfo::InnerIncrement = nullptr
Definition at line 128 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), and isInnerLoopIncrement().
InnerInductionPHI
PHINode* FlattenInfo::InnerInductionPHI = nullptr
Definition at line 114 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), CanWidenIV(), checkInnerInductionPhiUsers(), checkPHIs(), DoFlattenLoopPair(), and matchLinearIVUser().
InnerLoop
Loop* FlattenInfo::InnerLoop = nullptr
Definition at line 112 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), CanWidenIV(), checkOuterLoopInsts(), checkOverflow(), checkPHIs(), DoFlattenLoopPair(), and FlattenLoopPair().
InnerPHIsToTransform
SmallPtrSet<PHINode *, 4> FlattenInfo::InnerPHIsToTransform
Definition at line 135 of file LoopFlatten.cpp.
Referenced by CanWidenIV(), checkPHIs(), and DoFlattenLoopPair().
InnerTripCount
Value* FlattenInfo::InnerTripCount = nullptr
Definition at line 119 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), checkInnerInductionPhiUsers(), checkOuterLoopInsts(), checkOverflow(), DoFlattenLoopPair(), and matchLinearIVUser().
LinearIVUses
SmallPtrSet<Value *, 4> FlattenInfo::LinearIVUses
Definition at line 124 of file LoopFlatten.cpp.
Referenced by checkIVUsers(), checkOverflow(), DoFlattenLoopPair(), and matchLinearIVUser().
NarrowInnerInductionPHI
PHINode* FlattenInfo::NarrowInnerInductionPHI = nullptr
Definition at line 140 of file LoopFlatten.cpp.
Referenced by CanWidenIV(), and isNarrowInductionPhi().
NarrowOuterInductionPHI
PHINode* FlattenInfo::NarrowOuterInductionPHI = nullptr
Definition at line 141 of file LoopFlatten.cpp.
Referenced by CanWidenIV(), and isNarrowInductionPhi().
OuterBranch
BranchInst* FlattenInfo::OuterBranch = nullptr
Definition at line 132 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), and DoFlattenLoopPair().
OuterIncrement
BinaryOperator* FlattenInfo::OuterIncrement = nullptr
Definition at line 129 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), and isOuterLoopIncrement().
OuterInductionPHI
PHINode* FlattenInfo::OuterInductionPHI = nullptr
Definition at line 115 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), CanWidenIV(), checkOuterInductionPhiUsers(), checkOuterLoopInsts(), checkPHIs(), DoFlattenLoopPair(), and matchLinearIVUser().
OuterLoop
Loop* FlattenInfo::OuterLoop = nullptr
Definition at line 111 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), checkOuterLoopInsts(), checkOverflow(), checkPHIs(), DoFlattenLoopPair(), and FlattenLoopPair().
OuterTripCount
Value* FlattenInfo::OuterTripCount = nullptr
Definition at line 120 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), checkOverflow(), and DoFlattenLoopPair().
Widened
bool FlattenInfo::Widened = false
Definition at line 137 of file LoopFlatten.cpp.
Referenced by CanFlattenLoopPair(), CanWidenIV(), checkInnerInductionPhiUsers(), DoFlattenLoopPair(), FlattenLoopPair(), isNarrowInductionPhi(), and matchLinearIVUser().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopFlatten.cpp