LLVM: llvm::TargetMachineBuilder Struct Reference
llvm::TargetMachineBuilder Struct Reference
Helper to gather options relevant to the target machine creation.
#include "llvm/LTO/legacy/ThinLTOCodeGenerator.h"
Public Member Functions
std::unique_ptr< TargetMachine > create () const
Public Attributes
Triple TheTriple
std::string MCpu
std::string MAttr
TargetOptions Options
Optional< Reloc::Model > RelocModel
CodeGenOpt::Level CGOptLevel = CodeGenOpt::Aggressive
Detailed Description
Helper to gather options relevant to the target machine creation.
Definition at line 35 of file ThinLTOCodeGenerator.h.
Member Function Documentation
create()
std::unique_ptr< TargetMachine > TargetMachineBuilder::create () const
Definition at line 606 of file ThinLTOCodeGenerator.cpp.
References assert(), CGOptLevel, llvm::Target::createTargetMachine(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::SubtargetFeatures::getString(), llvm::TargetRegistry::lookupTarget(), MAttr, MCpu, llvm::None, Options, RelocModel, llvm::report_fatal_error(), llvm::Triple::str(), TheTriple, and TM.
Referenced by llvm::ThinLTOCodeGenerator::optimize(), and llvm::ThinLTOCodeGenerator::run().
Member Data Documentation
CGOptLevel
CodeGenOpt::Level llvm::TargetMachineBuilder::CGOptLevel = CodeGenOpt::Aggressive
Definition at line 41 of file ThinLTOCodeGenerator.h.
Referenced by create(), and llvm::ThinLTOCodeGenerator::setCodeGenOptLevel().
MAttr
std::string llvm::TargetMachineBuilder::MAttr
Definition at line 38 of file ThinLTOCodeGenerator.h.
Referenced by create(), and llvm::ThinLTOCodeGenerator::setAttr().
MCpu
std::string llvm::TargetMachineBuilder::MCpu
Definition at line 37 of file ThinLTOCodeGenerator.h.
Referenced by create(), and llvm::ThinLTOCodeGenerator::setCpu().
Options
TargetOptions llvm::TargetMachineBuilder::Options
Definition at line 39 of file ThinLTOCodeGenerator.h.
Referenced by create(), and llvm::ThinLTOCodeGenerator::setTargetOptions().
RelocModel
Optional<Reloc::Model> llvm::TargetMachineBuilder::RelocModel
Definition at line 40 of file ThinLTOCodeGenerator.h.
Referenced by create(), and llvm::ThinLTOCodeGenerator::setCodePICModel().
TheTriple
Triple llvm::TargetMachineBuilder::TheTriple
Definition at line 36 of file ThinLTOCodeGenerator.h.
Referenced by llvm::ThinLTOCodeGenerator::addModule(), create(), llvm::ThinLTOCodeGenerator::internalize(), llvm::ThinLTOCodeGenerator::run(), and llvm::ThinLTOCodeGenerator::writeGeneratedObject().
The documentation for this struct was generated from the following files:
include/llvm/LTO/legacy/ThinLTOCodeGenerator.h
lib/LTO/ThinLTOCodeGenerator.cpp