LLVM: lib/DebugInfo/CodeView/SymbolRecordHelpers.cpp File Reference
SymbolRecordHelpers.cpp File Reference
#include "llvm/DebugInfo/CodeView/SymbolRecordHelpers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
Functions
template<typename RecordT >
static RecordT createRecord (const CVSymbol &sym)
Function Documentation
createRecord()
template<typename RecordT > static RecordT createRecord (const CVSymbol & sym) static
Definition at line 17 of file SymbolRecordHelpers.cpp.
References llvm::cantFail(), llvm::codeview::SymbolDeserializer::deserializeAs(), and llvm::codeview::CVRecord< Kind >::kind().
Referenced by llvm::codeview::getScopeEndOffset(), and llvm::codeview::getScopeParentOffset().