LLVM: lib/CodeGen/TargetPassConfig.cpp File Reference
TargetPassConfig.cpp File Reference
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CFLAndersAliasAnalysis.h"
#include "llvm/Analysis/CFLSteensAliasAnalysis.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/CodeGen/BasicBlockSectionsProfileReader.h"
#include "llvm/CodeGen/CSEConfigBase.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachinePassRegistry.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassInstrumentation.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Pass.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Discriminator.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/Threading.h"
#include "llvm/Target/CGPassBuilderOption.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include <cassert>
#include <string>
Classes
struct INITIALIZE_PASS::InsertedPass
class llvm::PassConfigImpl
Namespaces
namespace INITIALIZE_PASS
TargetPassConfig.
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define SET_OPTION(Option)
#define SET_BOOLEAN_OPTION(Option)
#define DISABLE_PASS(Option, Name)
Functions
static IdentifyingPassPtr applyDisable (IdentifyingPassPtr PassID, bool Override)
Allow standard passes to be disabled by command line options.
static IdentifyingPassPtr overridePass (AnalysisID StandardID, IdentifyingPassPtr TargetID)
Allow standard passes to be disabled by the command line, regardless of who is adding the pass.
static std::string getFSProfileFile (const TargetMachine *TM)
static std::string getFSRemappingFile (const TargetMachine *TM)
static const PassInfo * getPassInfo (StringRef PassName)
static AnalysisID getPassIDFromName (StringRef PassName)
static std::pair< StringRef, unsigned > getPassNameAndInstanceNum (StringRef PassName)
static void registerPartialPipelineCallback (PassInstrumentationCallbacks &PIC, LLVMTargetMachine &LLVMTM)
static FunctionPass * useDefaultRegisterAllocator ()
-regalloc=... command line option.
static void initializeDefaultRegisterAllocatorOnce ()
Variables
static cl::opt< bool > EnableIPRA ("enable-ipra", cl::init(false), cl::Hidden, cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls."))
static cl::opt< bool > DisablePostRASched ("disable-post-ra", cl::Hidden, cl::desc("Disable Post Regalloc Scheduler"))
static cl::opt< bool > DisableBranchFold ("disable-branch-fold", cl::Hidden, cl::desc("Disable branch folding"))
static cl::opt< bool > DisableTailDuplicate ("disable-tail-duplicate", cl::Hidden, cl::desc("Disable tail duplication"))
static cl::opt< bool > DisableEarlyTailDup ("disable-early-taildup", cl::Hidden, cl::desc("Disable pre-register allocation tail duplication"))
static cl::opt< bool > DisableBlockPlacement ("disable-block-placement", cl::Hidden, cl::desc("Disable probability-driven block placement"))
static cl::opt< bool > EnableBlockPlacementStats ("enable-block-placement-stats", cl::Hidden, cl::desc("Collect probability-driven block placement stats"))
static cl::opt< bool > DisableSSC ("disable-ssc", cl::Hidden, cl::desc("Disable Stack Slot Coloring"))
static cl::opt< bool > DisableMachineDCE ("disable-machine-dce", cl::Hidden, cl::desc("Disable Machine Dead Code Elimination"))
static cl::opt< bool > DisableEarlyIfConversion ("disable-early-ifcvt", cl::Hidden, cl::desc("Disable Early If-conversion"))
static cl::opt< bool > DisableMachineLICM ("disable-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM"))
static cl::opt< bool > DisableMachineCSE ("disable-machine-cse", cl::Hidden, cl::desc("Disable Machine Common Subexpression Elimination"))
static cl::opt< cl::boolOrDefault > OptimizeRegAlloc ("optimize-regalloc", cl::Hidden, cl::desc("Enable optimized register allocation compilation path."))
static cl::opt< bool > DisablePostRAMachineLICM ("disable-postra-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM"))
static cl::opt< bool > DisableMachineSink ("disable-machine-sink", cl::Hidden, cl::desc("Disable Machine Sinking"))
static cl::opt< bool > DisablePostRAMachineSink ("disable-postra-machine-sink", cl::Hidden, cl::desc("Disable PostRA Machine Sinking"))
static cl::opt< bool > DisableLSR ("disable-lsr", cl::Hidden, cl::desc("Disable Loop Strength Reduction Pass"))
static cl::opt< bool > DisableConstantHoisting ("disable-constant-hoisting", cl::Hidden, cl::desc("Disable ConstantHoisting"))
static cl::opt< bool > DisableCGP ("disable-cgp", cl::Hidden, cl::desc("Disable Codegen Prepare"))
static cl::opt< bool > DisableCopyProp ("disable-copyprop", cl::Hidden, cl::desc("Disable Copy Propagation pass"))
static cl::opt< bool > DisablePartialLibcallInlining ("disable-partial-libcall-inlining", cl::Hidden, cl::desc("Disable Partial Libcall Inlining"))
static cl::opt< bool > EnableImplicitNullChecks ("enable-implicit-null-checks", cl::desc("Fold null checks into faulting memory operations"), cl::init(false), cl::Hidden)
static cl::opt< bool > DisableMergeICmps ("disable-mergeicmps", cl::desc("Disable MergeICmps Pass"), cl::init(false), cl::Hidden)
static cl::opt< bool > PrintLSR ("print-lsr-output", cl::Hidden, cl::desc("Print LLVM IR produced by the loop-reduce pass"))
static cl::opt< bool > PrintISelInput ("print-isel-input", cl::Hidden, cl::desc("Print LLVM IR input to isel pass"))
static cl::opt< bool > PrintGCInfo ("print-gc", cl::Hidden, cl::desc("Dump garbage collector data"))
static cl::opt< cl::boolOrDefault > VerifyMachineCode ("verify-machineinstrs", cl::Hidden, cl::desc("Verify generated machine code"))
static cl::opt< cl::boolOrDefault > DebugifyAndStripAll ("debugify-and-strip-all-safe", cl::Hidden, cl::desc("Debugify MIR before and Strip debug after " "each pass except those known to be unsafe " "when debug info is present"))
static cl::opt< cl::boolOrDefault > DebugifyCheckAndStripAll ("debugify-check-and-strip-all-safe", cl::Hidden, cl::desc("Debugify MIR before, by checking and stripping the debug info after, " "each pass except those known to be unsafe when debug info is " "present"))
static cl::opt< RunOutliner > EnableMachineOutliner ("enable-machine-outliner", cl::desc("Enable the machine outliner"), cl::Hidden, cl::ValueOptional, cl::init(RunOutliner::TargetDefault), cl::values(clEnumValN(RunOutliner::AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(RunOutliner::NeverOutline, "never", "Disable all outlining"), clEnumValN(RunOutliner::AlwaysOutline, "", "")))
static cl::opt< bool > DisableCFIFixup ("disable-cfi-fixup", cl::Hidden, cl::desc("Disable the CFI fixup pass"))
static cl::opt< cl::boolOrDefault > EnableFastISelOption ("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector"))
static cl::opt< cl::boolOrDefault > EnableGlobalISelOption ("global-isel", cl::Hidden, cl::desc("Enable the \"global\" instruction selector"))
static cl::opt< bool > PrintAfterISel ("print-after-isel", cl::init(false), cl::Hidden, cl::desc("Print machine instrs after ISel"))
static cl::opt< GlobalISelAbortMode > EnableGlobalISelAbort ("global-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction"), cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure")))
static cl::opt< bool > FSNoFinalDiscrim ("fs-no-final-discrim", cl::init(false), cl::Hidden, cl::desc("Do not insert FS-AFDO discriminators before " "emit."))
static cl::opt< bool > DisableRAFSProfileLoader ("disable-ra-fsprofile-loader", cl::init(false), cl::Hidden, cl::desc("Disable MIRProfileLoader before RegAlloc"))
static cl::opt< bool > DisableLayoutFSProfileLoader ("disable-layout-fsprofile-loader", cl::init(false), cl::Hidden, cl::desc("Disable MIRProfileLoader before BlockPlacement"))
static cl::opt< std::string > FSProfileFile ("fs-profile-file", cl::init(""), cl::value_desc("filename"), cl::desc("Flow Sensitive profile file name."), cl::Hidden)
static cl::opt< std::string > FSRemappingFile ("fs-remapping-file", cl::init(""), cl::value_desc("filename"), cl::desc("Flow Sensitive profile remapping file name."), cl::Hidden)
static cl::opt< bool > MISchedPostRA ("misched-postra", cl::Hidden, cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)"))
static cl::opt< bool > EarlyLiveIntervals ("early-live-intervals", cl::Hidden, cl::desc("Run live interval analysis earlier in the pipeline"))
static cl::opt< CFLAAType > UseCFLAA ("use-cfl-aa-in-codegen", cl::init(CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis in CodeGen"), cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA")))
static const char StartAfterOptName [] = "start-after"
Option names for limiting the codegen pipeline.
static const char StartBeforeOptName [] = "start-before"
static const char StopAfterOptName [] = "stop-after"
static const char StopBeforeOptName [] = "stop-before"
static cl::opt< std::string > StartAfterOpt (StringRef(StartAfterOptName), cl::desc("Resume compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StartBeforeOpt (StringRef(StartBeforeOptName), cl::desc("Resume compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StopAfterOpt (StringRef(StopAfterOptName), cl::desc("Stop compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< std::string > StopBeforeOpt (StringRef(StopBeforeOptName), cl::desc("Stop compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden)
static cl::opt< bool > EnableMachineFunctionSplitter ("enable-split-machine-functions", cl::Hidden, cl::desc("Split out cold blocks from machine functions based on profile " "information."))
Enable the machine function splitter pass.
static cl::opt< bool > DisableExpandReductions ("disable-expand-reductions", cl::init(false), cl::Hidden, cl::desc("Disable the expand reduction intrinsics pass from running"))
Disable the expand reductions pass for testing.
static cl::opt< bool > DisableSelectOptimize ("disable-select-optimize", cl::init(true), cl::Hidden, cl::desc("Disable the select-optimization pass from running"))
Disable the select optimization pass.
static cl::opt< RegisterRegAlloc::FunctionPassCtor, false, RegisterPassParser< RegisterRegAlloc > > RegAlloc ("regalloc", cl::Hidden, cl::init(&useDefaultRegisterAllocator), cl::desc("Register allocator to use"))
static llvm::once_flag InitializeDefaultRegisterAllocatorFlag
A dummy default pass factory indicates whether the register allocator is overridden on the command line.
static RegisterRegAlloc defaultRegAlloc ("default", "pick register allocator based on -O option", useDefaultRegisterAllocator)
Macro Definition Documentation
DISABLE_PASS
#define DISABLE_PASS (Option, Name)
Value:
  if (Option && P.contains(#Name))                                             \
    return false;
Referenced by llvm::registerCodeGenCallback().
SET_BOOLEAN_OPTION
#define SET_BOOLEAN_OPTION (Option)
Value:
Opt.Option = Option;
Referenced by llvm::getCGPassBuilderOption().
SET_OPTION
#define SET_OPTION (Option)
Value:
  if (Option.getNumOccurrences())                                              \
    Opt.Option = Option;
Referenced by llvm::getCGPassBuilderOption().
Function Documentation
applyDisable()
static IdentifyingPassPtr applyDisable (IdentifyingPassPtr PassID, bool Override) static
Allow standard passes to be disabled by command line options.
This supports simple binary flags that either suppress the pass or do nothing. i.e. -disable-mypass=false has no effect. These should be converted to boolOrDefault in order to use applyOverride.
Definition at line 271 of file TargetPassConfig.cpp.
Referenced by overridePass().
getFSProfileFile()
static std::string getFSProfileFile (const TargetMachine * TM) static
Definition at line 339 of file TargetPassConfig.cpp.
References FSProfileFile, llvm::None, llvm::PGOOptions::SampleUse, and TM.
Referenced by llvm::TargetPassConfig::addBlockPlacement(), and llvm::TargetPassConfig::addMachinePasses().
getFSRemappingFile()
static std::string getFSRemappingFile (const TargetMachine * TM) static
Definition at line 350 of file TargetPassConfig.cpp.
References FSRemappingFile, llvm::None, llvm::PGOOptions::SampleUse, and TM.
Referenced by llvm::TargetPassConfig::addBlockPlacement(), and llvm::TargetPassConfig::addMachinePasses().
getPassIDFromName()
static AnalysisID getPassIDFromName (StringRef PassName) static
Definition at line 427 of file TargetPassConfig.cpp.
References getPassInfo(), llvm::PassInfo::getTypeInfo(), and PassName.
getPassInfo()
static const PassInfo * getPassInfo (StringRef PassName) static
Definition at line 415 of file TargetPassConfig.cpp.
References llvm::PassRegistry::getPassInfo(), llvm::PassRegistry::getPassRegistry(), PassName, and llvm::report_fatal_error().
Referenced by llvm::PMTopLevelManager::findAnalysisPassInfo(), and getPassIDFromName().
getPassNameAndInstanceNum()
static std::pair< StringRef, unsigned > getPassNameAndInstanceNum (StringRef PassName) static
Definition at line 433 of file TargetPassConfig.cpp.
References llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), Name, PassName, and llvm::report_fatal_error().
Referenced by registerPartialPipelineCallback().
initializeDefaultRegisterAllocatorOnce()
static void initializeDefaultRegisterAllocatorOnce () static
Definition at line 1366 of file TargetPassConfig.cpp.
References llvm::RegisterRegAllocBase< RegisterRegAlloc >::getDefault(), RegAlloc, and llvm::RegisterRegAllocBase< RegisterRegAlloc >::setDefault().
Referenced by llvm::TargetPassConfig::createRegAllocPass().
overridePass()
static IdentifyingPassPtr overridePass (AnalysisID StandardID, IdentifyingPassPtr TargetID) static
Allow standard passes to be disabled by the command line, regardless of who is adding the pass.
StandardID is the pass identified in the standard pass pipeline and provided to addPass(). It may be a target-specific ID in the case that the target directly adds its own pass, but in that case we harmlessly fall through.
TargetID is the pass that the target has configured to override StandardID.
StandardID may be a pseudo ID. In that case TargetID is the name of the real pass to run. This allows multiple options to control a single pass depending on where in the pipeline that pass is added.
Definition at line 290 of file TargetPassConfig.cpp.
References applyDisable(), llvm::BranchFolderPassID, llvm::DeadMachineInstructionElimID, DisableBlockPlacement, DisableBranchFold, DisableCopyProp, DisableEarlyIfConversion, DisableEarlyTailDup, DisableMachineCSE, DisableMachineDCE, DisableMachineLICM, DisableMachineSink, DisablePostRAMachineLICM, DisablePostRAMachineSink, DisablePostRASched, DisableSSC, DisableTailDuplicate, llvm::EarlyIfConverterID, llvm::EarlyMachineLICMID, llvm::EarlyTailDuplicateID, llvm::MachineBlockPlacementID, llvm::MachineCopyPropagationID, llvm::MachineCSEID, llvm::MachineLICMID, llvm::MachineSinkingID, llvm::PostRAMachineSinkingID, llvm::PostRASchedulerID, llvm::StackSlotColoringID, and llvm::TailDuplicateID.
Referenced by llvm::TargetPassConfig::addPass(), and llvm::TargetPassConfig::isPassSubstitutedOrOverridden().
registerPartialPipelineCallback()
static void registerPartialPipelineCallback (PassInstrumentationCallbacks & PIC, LLVMTargetMachine & LLVMTM) static
Definition at line 509 of file TargetPassConfig.cpp.
References assert(), llvm::StringRef::empty(), getPassNameAndInstanceNum(), llvm::LLVMTargetMachine::getPassNameFromLegacyName(), if(), P, PIC, llvm::PassInstrumentationCallbacks::registerShouldRunOptionalPassCallback(), llvm::report_fatal_error(), StartAfterOpt, StartAfterOptName, StartBeforeOpt, StartBeforeOptName, StopAfterOpt, StopAfterOptName, StopBeforeOpt, and StopBeforeOptName.
Referenced by llvm::registerCodeGenCallback().
useDefaultRegisterAllocator()
static FunctionPass * useDefaultRegisterAllocator () static
-regalloc=... command line option.
Definition at line 1125 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::addRegAssignAndRewriteFast(), llvm::TargetPassConfig::createRegAllocPass(), and llvm::TargetPassConfig::isCustomizedRegAlloc().
Variable Documentation
DebugifyAndStripAll
cl::opt< cl::boolOrDefault > DebugifyAndStripAll("debugify-and-strip-all-safe", cl::Hidden, cl::desc("Debugify MIR before and Strip debug after " "each pass except those known to be unsafe " "when debug info is present")) ("debugify-and-strip-all-safe" , cl::Hidden , cl::desc("Debugify MIR before and Strip debug after " "each pass except those known to be unsafe " "when debug info is present")) static
Referenced by llvm::TargetPassConfig::addMachinePostPasses(), and llvm::TargetPassConfig::addMachinePrePasses().
DebugifyCheckAndStripAll
cl::opt< cl::boolOrDefault > DebugifyCheckAndStripAll("debugify-check-and-strip-all-safe", cl::Hidden, cl::desc("Debugify MIR before, by checking and stripping the debug info after, " "each pass except those known to be unsafe when debug info is " "present")) ("debugify-check-and-strip-all-safe" , cl::Hidden , cl::desc("Debugify MIR before, by checking and stripping the debug info after, " "each pass except those known to be unsafe when debug info is " "present")) static
Referenced by llvm::TargetPassConfig::addMachinePostPasses(), and llvm::TargetPassConfig::addMachinePrePasses().
defaultRegAlloc
RegisterRegAlloc defaultRegAlloc("default", "pick register allocator based on -O option", useDefaultRegisterAllocator) ("default" , "pick register allocator based on -O option" , useDefaultRegisterAllocator) static
DisableBlockPlacement
cl::opt< bool > DisableBlockPlacement("disable-block-placement", cl::Hidden, cl::desc("Disable probability-driven block placement")) ("disable-block-placement" , cl::Hidden , cl::desc("Disable probability-driven block placement")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableBranchFold
cl::opt< bool > DisableBranchFold("disable-branch-fold", cl::Hidden, cl::desc("Disable branch folding")) ("disable-branch-fold" , cl::Hidden , cl::desc("Disable branch folding")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableCFIFixup
cl::opt< bool > DisableCFIFixup("disable-cfi-fixup", cl::Hidden, cl::desc("Disable the CFI fixup pass")) ("disable-cfi-fixup" , cl::Hidden , cl::desc("Disable the CFI fixup pass")) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
DisableCGP
cl::opt< bool > DisableCGP("disable-cgp", cl::Hidden, cl::desc("Disable Codegen Prepare")) ("disable-cgp" , cl::Hidden , cl::desc("Disable Codegen Prepare")) static
Referenced by llvm::TargetPassConfig::addCodeGenPrepare(), and llvm::getCGPassBuilderOption().
DisableConstantHoisting
cl::opt< bool > DisableConstantHoisting("disable-constant-hoisting", cl::Hidden, cl::desc("Disable ConstantHoisting")) ("disable-constant-hoisting" , cl::Hidden , cl::desc("Disable ConstantHoisting")) static
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
DisableCopyProp
cl::opt< bool > DisableCopyProp("disable-copyprop", cl::Hidden, cl::desc("Disable Copy Propagation pass")) ("disable-copyprop" , cl::Hidden , cl::desc("Disable Copy Propagation pass")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableEarlyIfConversion
cl::opt< bool > DisableEarlyIfConversion("disable-early-ifcvt", cl::Hidden, cl::desc("Disable Early If-conversion")) ("disable-early-ifcvt" , cl::Hidden , cl::desc("Disable Early If-conversion")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableEarlyTailDup
cl::opt< bool > DisableEarlyTailDup("disable-early-taildup", cl::Hidden, cl::desc("Disable pre-register allocation tail duplication")) ("disable-early-taildup" , cl::Hidden , cl::desc("Disable pre-register allocation tail duplication")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableExpandReductions
cl::opt< bool > DisableExpandReductions("disable-expand-reductions", cl::init(false), cl::Hidden, cl::desc("Disable the expand reduction intrinsics pass from running")) ("disable-expand-reductions" , cl::init(false) , cl::Hidden , cl::desc("Disable the expand reduction intrinsics pass from running")) static
Disable the expand reductions pass for testing.
Referenced by llvm::TargetPassConfig::addIRPasses().
DisableLayoutFSProfileLoader
cl::opt< bool > DisableLayoutFSProfileLoader("disable-layout-fsprofile-loader", cl::init(false), cl::Hidden, cl::desc("Disable MIRProfileLoader before BlockPlacement")) ("disable-layout-fsprofile-loader" , cl::init(false) , cl::Hidden , cl::desc("Disable MIRProfileLoader before BlockPlacement")) static
Referenced by llvm::TargetPassConfig::addBlockPlacement().
DisableLSR
cl::opt< bool > DisableLSR("disable-lsr", cl::Hidden, cl::desc("Disable Loop Strength Reduction Pass")) ("disable-lsr" , cl::Hidden , cl::desc("Disable Loop Strength Reduction Pass")) static
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
DisableMachineCSE
cl::opt< bool > DisableMachineCSE("disable-machine-cse", cl::Hidden, cl::desc("Disable Machine Common Subexpression Elimination")) ("disable-machine-cse" , cl::Hidden , cl::desc("Disable Machine Common Subexpression Elimination")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableMachineDCE
cl::opt< bool > DisableMachineDCE("disable-machine-dce", cl::Hidden, cl::desc("Disable Machine Dead Code Elimination")) ("disable-machine-dce" , cl::Hidden , cl::desc("Disable Machine Dead Code Elimination")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableMachineLICM
cl::opt< bool > DisableMachineLICM("disable-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM")) ("disable-machine-licm" , cl::Hidden , cl::desc("Disable Machine LICM")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableMachineSink
cl::opt< bool > DisableMachineSink("disable-machine-sink", cl::Hidden, cl::desc("Disable Machine Sinking")) ("disable-machine-sink" , cl::Hidden , cl::desc("Disable Machine Sinking")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableMergeICmps
cl::opt< bool > DisableMergeICmps("disable-mergeicmps", cl::desc("Disable MergeICmps Pass"), cl::init(false), cl::Hidden) ("disable-mergeicmps" , cl::desc("Disable MergeICmps Pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
DisablePartialLibcallInlining
cl::opt< bool > DisablePartialLibcallInlining("disable-partial-libcall-inlining", cl::Hidden, cl::desc("Disable Partial Libcall Inlining")) ("disable-partial-libcall-inlining" , cl::Hidden , cl::desc("Disable Partial Libcall Inlining")) static
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
DisablePostRAMachineLICM
cl::opt< bool > DisablePostRAMachineLICM("disable-postra-machine-licm", cl::Hidden, cl::desc("Disable Machine LICM")) ("disable-postra-machine-licm" , cl::Hidden , cl::desc("Disable Machine LICM")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisablePostRAMachineSink
cl::opt< bool > DisablePostRAMachineSink("disable-postra-machine-sink", cl::Hidden, cl::desc("Disable PostRA Machine Sinking")) ("disable-postra-machine-sink" , cl::Hidden , cl::desc("Disable PostRA Machine Sinking")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisablePostRASched
cl::opt< bool > DisablePostRASched("disable-post-ra", cl::Hidden, cl::desc("Disable Post Regalloc Scheduler")) ("disable-post-ra" , cl::Hidden , cl::desc("Disable Post Regalloc Scheduler")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableRAFSProfileLoader
cl::opt< bool > DisableRAFSProfileLoader("disable-ra-fsprofile-loader", cl::init(false), cl::Hidden, cl::desc("Disable MIRProfileLoader before RegAlloc")) ("disable-ra-fsprofile-loader" , cl::init(false) , cl::Hidden , cl::desc("Disable MIRProfileLoader before RegAlloc")) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
DisableSelectOptimize
cl::opt< bool > DisableSelectOptimize("disable-select-optimize", cl::init(true), cl::Hidden, cl::desc("Disable the select-optimization pass from running")) ("disable-select-optimize" , cl::init(true) , cl::Hidden , cl::desc("Disable the select-optimization pass from running")) static
Disable the select optimization pass.
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
DisableSSC
cl::opt< bool > DisableSSC("disable-ssc", cl::Hidden, cl::desc("Disable Stack Slot Coloring")) ("disable-ssc" , cl::Hidden , cl::desc("Disable Stack Slot Coloring")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
DisableTailDuplicate
cl::opt< bool > DisableTailDuplicate("disable-tail-duplicate", cl::Hidden, cl::desc("Disable tail duplication")) ("disable-tail-duplicate" , cl::Hidden , cl::desc("Disable tail duplication")) static
Referenced by overridePass(), and llvm::registerCodeGenCallback().
EarlyLiveIntervals
cl::opt< bool > EarlyLiveIntervals("early-live-intervals", cl::Hidden, cl::desc("Run live interval analysis earlier in the pipeline")) ("early-live-intervals" , cl::Hidden , cl::desc("Run live interval analysis earlier in the pipeline")) static
Referenced by llvm::TargetPassConfig::addOptimizedRegAlloc(), and llvm::getCGPassBuilderOption().
EnableBlockPlacementStats
cl::opt< bool > EnableBlockPlacementStats("enable-block-placement-stats", cl::Hidden, cl::desc("Collect probability-driven block placement stats")) ("enable-block-placement-stats" , cl::Hidden , cl::desc("Collect probability-driven block placement stats")) static
Referenced by llvm::TargetPassConfig::addBlockPlacement(), and llvm::getCGPassBuilderOption().
EnableFastISelOption
cl::opt< cl::boolOrDefault > EnableFastISelOption("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector")) ("fast-isel" , cl::Hidden , cl::desc("Enable the \"fast\" instruction selector")) static
Referenced by llvm::TargetPassConfig::addCoreISelPasses(), and llvm::getCGPassBuilderOption().
EnableGlobalISelAbort
cl::opt< GlobalISelAbortMode > EnableGlobalISelAbort("global-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction"), cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure"))) ("global-isel-abort" , cl::Hidden , cl::desc("Enable abort calls when \"global\" instruction selection " "fails to lower/select an instruction") , cl::values(clEnumValN(GlobalISelAbortMode::Disable, "0", "Disable the abort"), clEnumValN(GlobalISelAbortMode::Enable, "1", "Enable the abort"), clEnumValN(GlobalISelAbortMode::DisableWithDiag, "2", "Disable the abort but emit a diagnostic on failure"))) static
Referenced by llvm::getCGPassBuilderOption(), and llvm::TargetPassConfig::TargetPassConfig().
EnableGlobalISelOption
cl::opt< cl::boolOrDefault > EnableGlobalISelOption("global-isel", cl::Hidden, cl::desc("Enable the \"global\" instruction selector")) ("global-isel" , cl::Hidden , cl::desc("Enable the \"global\" instruction selector")) static
Referenced by llvm::TargetPassConfig::addCoreISelPasses(), and llvm::getCGPassBuilderOption().
EnableImplicitNullChecks
cl::opt< bool > EnableImplicitNullChecks("enable-implicit-null-checks", cl::desc("Fold null checks into faulting memory operations"), cl::init(false), cl::Hidden) ("enable-implicit-null-checks" , cl::desc("Fold null checks into faulting memory operations") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::getCGPassBuilderOption().
EnableIPRA
cl::opt< bool > EnableIPRA("enable-ipra", cl::init(false), cl::Hidden, cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls.")) ("enable-ipra" , cl::init(false) , cl::Hidden , cl::desc("Enable interprocedural register allocation " "to reduce load/store at procedure calls.")) static
Referenced by llvm::getCGPassBuilderOption(), and llvm::TargetPassConfig::TargetPassConfig().
EnableMachineFunctionSplitter
cl::opt< bool > EnableMachineFunctionSplitter("enable-split-machine-functions", cl::Hidden, cl::desc("Split out cold blocks from machine functions based on profile " "information.")) ("enable-split-machine-functions" , cl::Hidden , cl::desc("Split out cold blocks from machine functions based on profile " "information.")) static
Enable the machine function splitter pass.
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::codegen::RegisterCodeGenFlags::RegisterCodeGenFlags().
EnableMachineOutliner
cl::opt< RunOutliner > EnableMachineOutliner("enable-machine-outliner", cl::desc("Enable the machine outliner"), cl::Hidden, cl::ValueOptional, cl::init(RunOutliner::TargetDefault), cl::values(clEnumValN(RunOutliner::AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(RunOutliner::NeverOutline, "never", "Disable all outlining"), clEnumValN(RunOutliner::AlwaysOutline, "", ""))) ("enable-machine-outliner" , cl::desc("Enable the machine outliner") , cl::Hidden , cl::ValueOptional , cl::init(RunOutliner::TargetDefault) , cl::values(clEnumValN(RunOutliner::AlwaysOutline, "always", "Run on all functions guaranteed to be beneficial"), clEnumValN(RunOutliner::NeverOutline, "never", "Disable all outlining"), clEnumValN(RunOutliner::AlwaysOutline, "", ""))) static
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::getCGPassBuilderOption().
FSNoFinalDiscrim
cl::opt< bool > FSNoFinalDiscrim("fs-no-final-discrim", cl::init(false), cl::Hidden, cl::desc("Do not insert FS-AFDO discriminators before " "emit.")) ("fs-no-final-discrim" , cl::init(false) , cl::Hidden , cl::desc("Do not insert FS-AFDO discriminators before " "emit.")) static
Referenced by llvm::TargetPassConfig::addMachinePasses().
FSProfileFile
cl::opt< std::string > FSProfileFile("fs-profile-file", cl::init(""), cl::value_desc("filename"), cl::desc("Flow Sensitive profile file name."), cl::Hidden) ("fs-profile-file" , cl::init("") , cl::value_desc("filename") , cl::desc("Flow Sensitive profile file name.") , cl::Hidden) static
Referenced by getFSProfileFile().
FSRemappingFile
cl::opt< std::string > FSRemappingFile("fs-remapping-file", cl::init(""), cl::value_desc("filename"), cl::desc("Flow Sensitive profile remapping file name."), cl::Hidden) ("fs-remapping-file" , cl::init("") , cl::value_desc("filename") , cl::desc("Flow Sensitive profile remapping file name.") , cl::Hidden) static
Referenced by getFSRemappingFile().
InitializeDefaultRegisterAllocatorFlag
llvm::once_flag InitializeDefaultRegisterAllocatorFlag static
A dummy default pass factory indicates whether the register allocator is overridden on the command line.
Definition at line 1359 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::createRegAllocPass().
MISchedPostRA
cl::opt< bool > MISchedPostRA("misched-postra", cl::Hidden, cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)")) ("misched-postra" , cl::Hidden , cl::desc("Run MachineScheduler post regalloc (independent of preRA sched)")) static
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::getCGPassBuilderOption().
OptimizeRegAlloc
cl::opt< cl::boolOrDefault > OptimizeRegAlloc("optimize-regalloc", cl::Hidden, cl::desc("Enable optimized register allocation compilation path.")) ("optimize-regalloc" , cl::Hidden , cl::desc("Enable optimized register allocation compilation path.")) static
Referenced by llvm::getCGPassBuilderOption(), and llvm::TargetPassConfig::getOptimizeRegAlloc().
PrintAfterISel
cl::opt< bool > PrintAfterISel("print-after-isel", cl::init(false), cl::Hidden, cl::desc("Print machine instrs after ISel")) ("print-after-isel" , cl::init(false) , cl::Hidden , cl::desc("Print machine instrs after ISel")) static
Referenced by llvm::TargetPassConfig::addPrintPass().
PrintGCInfo
cl::opt< bool > PrintGCInfo("print-gc", cl::Hidden, cl::desc("Dump garbage collector data")) ("print-gc" , cl::Hidden , cl::desc("Dump garbage collector data")) static
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::getCGPassBuilderOption().
PrintISelInput
cl::opt< bool > PrintISelInput("print-isel-input", cl::Hidden, cl::desc("Print LLVM IR input to isel pass")) ("print-isel-input" , cl::Hidden , cl::desc("Print LLVM IR input to isel pass")) static
Referenced by llvm::TargetPassConfig::addISelPrepare(), and llvm::getCGPassBuilderOption().
PrintLSR
cl::opt< bool > PrintLSR("print-lsr-output", cl::Hidden, cl::desc("Print LLVM IR produced by the loop-reduce pass")) ("print-lsr-output" , cl::Hidden , cl::desc("Print LLVM IR produced by the loop-reduce pass")) static
Referenced by llvm::TargetPassConfig::addIRPasses(), and llvm::getCGPassBuilderOption().
RegAlloc
cl::opt< RegisterRegAlloc::FunctionPassCtor, false, RegisterPassParser< RegisterRegAlloc > > RegAlloc("regalloc", cl::Hidden, cl::init(&useDefaultRegisterAllocator), cl::desc("Register allocator to use")) ("regalloc" , cl::Hidden , cl::init & useDefaultRegisterAllocator, cl::desc("Register allocator to use")) static
Referenced by llvm::TargetPassConfig::addRegAssignAndRewriteFast(), initializeDefaultRegisterAllocatorOnce(), llvm::TargetPassConfig::isCustomizedRegAlloc(), and llvm::TargetPassConfig::usingDefaultRegAlloc().
StartAfterOpt
cl::opt< std::string > StartAfterOpt(StringRef(StartAfterOptName), cl::desc("Resume compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StartAfterOptName) , cl::desc("Resume compilation after a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), llvm::TargetPassConfig::hasLimitedCodeGenPipeline(), and registerPartialPipelineCallback().
StartAfterOptName
const char StartAfterOptName[] = "start-after" static
Option names for limiting the codegen pipeline.
Those are used in error reporting and we didn't want to duplicate their names all over the place.
Definition at line 226 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and registerPartialPipelineCallback().
StartBeforeOpt
cl::opt< std::string > StartBeforeOpt(StringRef(StartBeforeOptName), cl::desc("Resume compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StartBeforeOptName) , cl::desc("Resume compilation before a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), llvm::TargetPassConfig::hasLimitedCodeGenPipeline(), and registerPartialPipelineCallback().
StartBeforeOptName
const char StartBeforeOptName[] = "start-before" static
Definition at line 227 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and registerPartialPipelineCallback().
StopAfterOpt
cl::opt< std::string > StopAfterOpt(StringRef(StopAfterOptName), cl::desc("Stop compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StopAfterOptName) , cl::desc("Stop compilation after a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), registerPartialPipelineCallback(), and llvm::TargetPassConfig::willCompleteCodeGenPipeline().
StopAfterOptName
const char StopAfterOptName[] = "stop-after" static
Definition at line 228 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and registerPartialPipelineCallback().
StopBeforeOpt
cl::opt< std::string > StopBeforeOpt(StringRef(StopBeforeOptName), cl::desc("Stop compilation before a specific pass"), cl::value_desc("pass-name"), cl::init(""), cl::Hidden) (StringRef(StopBeforeOptName) , cl::desc("Stop compilation before a specific pass") , cl::value_desc("pass-name") , cl::init("") , cl::Hidden) static
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), registerPartialPipelineCallback(), and llvm::TargetPassConfig::willCompleteCodeGenPipeline().
StopBeforeOptName
const char StopBeforeOptName[] = "stop-before" static
Definition at line 229 of file TargetPassConfig.cpp.
Referenced by llvm::TargetPassConfig::getLimitedCodeGenPipelineReason(), and registerPartialPipelineCallback().
UseCFLAA
cl::opt< CFLAAType > UseCFLAA("use-cfl-aa-in-codegen", cl::init(CFLAAType::None), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis in CodeGen"), cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) ("use-cfl-aa-in-codegen" , cl::init(CFLAAType::None) , cl::Hidden , cl::desc("Enable the new, experimental CFL alias analysis in CodeGen") , cl::values(clEnumValN(CFLAAType::None, "none", "Disable CFL-AA"), clEnumValN(CFLAAType::Steensgaard, "steens", "Enable unification-based CFL-AA"), clEnumValN(CFLAAType::Andersen, "anders", "Enable inclusion-based CFL-AA"), clEnumValN(CFLAAType::Both, "both", "Enable both variants of CFL-AA"))) static
VerifyMachineCode
cl::opt< cl::boolOrDefault > VerifyMachineCode("verify-machineinstrs", cl::Hidden, cl::desc("Verify generated machine code")) ("verify-machineinstrs" , cl::Hidden , cl::desc("Verify generated machine code")) static
Referenced by llvm::TargetPassConfig::addVerifyPass(), and llvm::getCGPassBuilderOption().