LLVM: lib/TableGen/TGParser.cpp File Reference
TGParser.cpp File Reference
#include "TGParser.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <limits>
Classes
struct llvm::SubClassReference
struct llvm::SubMultiClassReference
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static bool checkBitsConcrete (Record &R, const RecordVal &RV)
static void checkConcrete (Record &R)
static Init * QualifyName (Record &CurRec, MultiClass *CurMultiClass, Init *Name, StringRef Scoper)
Return an Init with a qualifier prefix referring to CurRec's name.
static Init * QualifiedNameOfImplicitName (Record &Rec, MultiClass *MC=nullptr)
Return the qualified version of the implicit 'NAME' template argument.
static Init * QualifiedNameOfImplicitName (MultiClass *MC)
static bool isObjectStart (tgtok::TokKind K)
isObjectStart - Return true if this is a valid first token for a statement.
Function Documentation
checkBitsConcrete()
static bool checkBitsConcrete (Record & R, const RecordVal & RV) static
Definition at line 72 of file TGParser.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::BitsInit::getBit(), llvm::BitsInit::getNumBits(), llvm::RecordVal::getValue(), and llvm::isa().
Referenced by checkConcrete().
checkConcrete()
static void checkConcrete (Record & R) static
Definition at line 91 of file TGParser.cpp.
References checkBitsConcrete(), llvm::isa(), and llvm::PrintError().
isObjectStart()
static bool isObjectStart (tgtok::TokKind K) static
isObjectStart - Return true if this is a valid first token for a statement.
Definition at line 516 of file TGParser.cpp.
References llvm::tgtok::Assert, llvm::tgtok::Class, llvm::tgtok::Def, llvm::tgtok::Defm, llvm::tgtok::Defset, llvm::tgtok::Defvar, llvm::tgtok::Foreach, llvm::tgtok::If, llvm::tgtok::Let, and llvm::tgtok::MultiClass.
QualifiedNameOfImplicitName() [1/2]
static Init * QualifiedNameOfImplicitName (MultiClass * MC) static
Definition at line 139 of file TGParser.cpp.
References QualifiedNameOfImplicitName(), and llvm::MultiClass::Rec.
QualifiedNameOfImplicitName() [2/2]
static Init * QualifiedNameOfImplicitName (Record & Rec, MultiClass * MC = nullptr) static
Return the qualified version of the implicit 'NAME' template argument.
Definition at line 133 of file TGParser.cpp.
References llvm::StringInit::get(), llvm::Record::getRecords(), and QualifyName().
Referenced by QualifiedNameOfImplicitName().
QualifyName()
static Init * QualifyName (Record & CurRec, MultiClass * CurMultiClass, Init * Name, StringRef Scoper) static
Return an Init with a qualifier prefix referring to CurRec's name.
Definition at line 115 of file TGParser.cpp.
References llvm::dyn_cast(), llvm::StringInit::get(), llvm::Record::getNameInit(), llvm::Record::getRecords(), llvm::BinOpInit::getStrConcat(), Name, and llvm::MultiClass::Rec.
Referenced by QualifiedNameOfImplicitName().