LLVM: lib/Target/ARM/Thumb2SizeReduction.cpp File Reference
Thumb2SizeReduction.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "Thumb2InstrInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <functional>
#include <iterator>
#include <utility>
Macros
#define DEBUG_TYPE "thumb2-reduce-size"
#define THUMB2_SIZE_REDUCE_NAME "Thumb2 instruction size reduce pass"
Functions
STATISTIC (NumNarrows, "Number of 32-bit instrs reduced to 16-bit ones")
STATISTIC (Num2Addrs, "Number of 32-bit instrs reduced to 2addr 16-bit ones")
STATISTIC (NumLdSts, "Number of 32-bit load / store reduced to 16-bit ones")
INITIALIZE_PASS (Thumb2SizeReduce, DEBUG_TYPE, THUMB2_SIZE_REDUCE_NAME, false, false) Thumb2SizeReduce
static bool HasImplicitCPSRDef (const MCInstrDesc &MCID)
static bool isHighLatencyCPSR (MachineInstr *Def)
static bool VerifyLowRegs (MachineInstr *MI)
static bool UpdateCPSRDef (MachineInstr &MI, bool LiveCPSR, bool &DefCPSR)
static bool UpdateCPSRUse (MachineInstr &MI, bool LiveCPSR)
Variables
static cl::opt< int > ReduceLimit ("t2-reduce-limit", cl::init(-1), cl::Hidden)
static cl::opt< int > ReduceLimit2Addr ("t2-reduce-limit2", cl::init(-1), cl::Hidden)
static cl::opt< int > ReduceLimitLdSt ("t2-reduce-limit3", cl::init(-1), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "thumb2-reduce-size"
Definition at line 47 of file Thumb2SizeReduction.cpp.
THUMB2_SIZE_REDUCE_NAME
#define THUMB2_SIZE_REDUCE_NAME "Thumb2 instruction size reduce pass"
Definition at line 48 of file Thumb2SizeReduction.cpp.
Function Documentation
HasImplicitCPSRDef()
static bool HasImplicitCPSRDef (const MCInstrDesc & MCID) static
Definition at line 255 of file Thumb2SizeReduction.cpp.
References llvm::MCInstrDesc::getImplicitDefs().
INITIALIZE_PASS()
INITIALIZE_PASS (Thumb2SizeReduce , DEBUG_TYPE , THUMB2_SIZE_REDUCE_NAME , false , false)
Definition at line 242 of file Thumb2SizeReduction.cpp.
References llvm::array_lengthof(), and llvm_unreachable.
isHighLatencyCPSR()
static bool isHighLatencyCPSR (MachineInstr * Def) static
Definition at line 263 of file Thumb2SizeReduction.cpp.
STATISTIC() [1/3]
STATISTIC (Num2Addrs , "Number of 32-bit instrs reduced to 2addr 16-bit ones")
STATISTIC() [2/3]
STATISTIC (NumLdSts , "Number of 32-bit load / store reduced to 16-bit ones")
STATISTIC() [3/3]
STATISTIC (NumNarrows , "Number of 32-bit instrs reduced to 16-bit ones")
UpdateCPSRDef()
static bool UpdateCPSRDef (MachineInstr & MI, bool LiveCPSR, bool & DefCPSR) static
Definition at line 983 of file Thumb2SizeReduction.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), and MI.
UpdateCPSRUse()
static bool UpdateCPSRUse (MachineInstr & MI, bool LiveCPSR) static
Definition at line 999 of file Thumb2SizeReduction.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), and MI.
VerifyLowRegs()
static bool VerifyLowRegs (MachineInstr * MI) static
Definition at line 375 of file Thumb2SizeReduction.cpp.
References llvm::MachineOperand::getReg(), llvm::isARMLowRegister(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), and MI.
Variable Documentation
ReduceLimit
cl::opt< int > ReduceLimit("t2-reduce-limit", cl::init(-1), cl::Hidden) ("t2-reduce-limit" , cl::init(-1) , cl::Hidden) static
ReduceLimit2Addr
cl::opt< int > ReduceLimit2Addr("t2-reduce-limit2", cl::init(-1), cl::Hidden) ("t2-reduce-limit2" , cl::init(-1) , cl::Hidden) static
ReduceLimitLdSt
cl::opt< int > ReduceLimitLdSt("t2-reduce-limit3", cl::init(-1), cl::Hidden) ("t2-reduce-limit3" , cl::init(-1) , cl::Hidden) static