LLVM: lib/Target/ARM/Thumb2InstrInfo.cpp File Reference
Thumb2InstrInfo.cpp File Reference
#include "Thumb2InstrInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
Functions
static unsigned negativeOffsetOpcode (unsigned opcode)
static unsigned positiveOffsetOpcode (unsigned opcode)
static unsigned immediateOffsetOpcode (unsigned opcode)
Variables
static cl::opt< bool > OldT2IfCvt ("old-thumb2-ifcvt", cl::Hidden, cl::desc("Use old-style Thumb2 if-conversion heuristics"), cl::init(false))
static cl::opt< bool > PreferNoCSEL ("prefer-no-csel", cl::Hidden, cl::desc("Prefer predicated Move to CSEL"), cl::init(false))
Function Documentation
immediateOffsetOpcode()
static unsigned immediateOffsetOpcode (unsigned opcode) static
Definition at line 486 of file Thumb2InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::rewriteT2FrameIndex().
negativeOffsetOpcode()
static unsigned negativeOffsetOpcode (unsigned opcode) static
Definition at line 418 of file Thumb2InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::rewriteT2FrameIndex().
positiveOffsetOpcode()
static unsigned positiveOffsetOpcode (unsigned opcode) static
Definition at line 452 of file Thumb2InstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::rewriteT2FrameIndex().
Variable Documentation
OldT2IfCvt
cl::opt< bool > OldT2IfCvt("old-thumb2-ifcvt", cl::Hidden, cl::desc("Use old-style Thumb2 if-conversion heuristics"), cl::init(false)) ("old-thumb2-ifcvt" , cl::Hidden , cl::desc("Use old-style Thumb2 if-conversion heuristics") , cl::init(false)) static
PreferNoCSEL
cl::opt< bool > PreferNoCSEL("prefer-no-csel", cl::Hidden, cl::desc("Prefer predicated Move to CSEL"), cl::init(false)) ("prefer-no-csel" , cl::Hidden , cl::desc("Prefer predicated Move to CSEL") , cl::init(false)) static
Referenced by llvm::Thumb2InstrInfo::optimizeSelect().