LLVM: lib/DebugInfo/PDB/UDTLayout.cpp File Reference
UDTLayout.cpp File Reference
#include "llvm/DebugInfo/PDB/UDTLayout.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/PDB/IPDBEnumChildren.h"
#include "llvm/DebugInfo/PDB/IPDBLineNumber.h"
#include "llvm/DebugInfo/PDB/IPDBRawSymbol.h"
#include "llvm/DebugInfo/PDB/IPDBSession.h"
#include "llvm/DebugInfo/PDB/PDBSymbol.h"
#include "llvm/DebugInfo/PDB/PDBSymbolData.h"
#include "llvm/DebugInfo/PDB/PDBSymbolFunc.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeBaseClass.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeBuiltin.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeFunctionSig.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypePointer.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeUDT.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeVTable.h"
#include "llvm/DebugInfo/PDB/PDBTypes.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
Functions
static std::unique_ptr< PDBSymbol > getSymbolType (const PDBSymbol &Symbol)
static uint32_t getTypeLength (const PDBSymbol &Symbol)
Function Documentation
getSymbolType()
static std::unique_ptr< PDBSymbol > getSymbolType (const PDBSymbol & Symbol) static
Definition at line 36 of file UDTLayout.cpp.
References llvm::pdb::IPDBSession::getSymbolById(), and llvm::pdb::IPDBRawSymbol::getTypeId().
Referenced by getTypeLength(), and llvm::object::XCOFFCsectAuxRef::isLabel().
getTypeLength()
static uint32_t getTypeLength (const PDBSymbol & Symbol) static
Definition at line 43 of file UDTLayout.cpp.
References llvm::pdb::IPDBRawSymbol::getLength(), and getSymbolType().