LLVM: include/llvm/Demangle/Utility.h File Reference
Utility.h File Reference
#include "StringView.h"
#include <array>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <limits>
Classes
class OutputBuffer
class ScopedOverride< T >
Functions
bool initializeOutputBuffer (char *Buf, size_t *N, OutputBuffer &OB, size_t InitSize)
Function Documentation
initializeOutputBuffer()
bool initializeOutputBuffer (char * Buf, size_t * N, OutputBuffer & OB, size_t InitSize) inline
Definition at line 201 of file Utility.h.
References N.
Referenced by llvm::dlangDemangle(), llvm::ms_demangle::Demangler::dumpBackReferences(), llvm::ItaniumPartialDemangler::getFunctionDeclContextName(), llvm::ItaniumPartialDemangler::getFunctionParameters(), llvm::ItaniumPartialDemangler::getFunctionReturnType(), llvm::itaniumDemangle(), llvm::microsoftDemangle(), printNode(), llvm::rustDemangle(), and llvm::ms_demangle::Node::toString().