LLVM: lib/Transforms/Utils/ValueMapper.cpp File Reference
ValueMapper.cpp File Reference
#include "llvm/Transforms/Utils/ValueMapper.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include <cassert>
#include <limits>
#include <memory>
#include <utility>
Macros
#define DEBUG_TYPE "value-mapper"
Functions
static ConstantAsMetadata * wrapConstantAsMetadata (const ConstantAsMetadata &CMD, Value *MappedV)
static Mapper * getAsMapper (void *pImpl)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "value-mapper"
Definition at line 49 of file ValueMapper.cpp.
Function Documentation
getAsMapper()
static Mapper * getAsMapper (void * pImpl) static
Definition at line 1121 of file ValueMapper.cpp.
Referenced by llvm::ValueMapper::registerAlternateMappingContext(), llvm::ValueMapper::scheduleMapAppendingVariable(), llvm::ValueMapper::scheduleMapGlobalAlias(), llvm::ValueMapper::scheduleMapGlobalIFunc(), llvm::ValueMapper::scheduleMapGlobalInitializer(), llvm::ValueMapper::scheduleRemapFunction(), and llvm::ValueMapper::~ValueMapper().
wrapConstantAsMetadata()
static ConstantAsMetadata * wrapConstantAsMetadata (const ConstantAsMetadata & CMD, Value * MappedV) static
Definition at line 602 of file ValueMapper.cpp.
References llvm::ValueAsMetadata::getConstant(), and llvm::ConstantAsMetadata::getValue().