LLVM: lib/Transforms/Vectorize/VPlanVerifier.cpp File Reference
VPlanVerifier.cpp File Reference
This file defines the class VPlanVerifier, which contains utility functions to check the consistency and invariants of a VPlan.
#include "VPlanVerifier.h"
#include "VPlan.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "loop-vectorize"
Functions
static bool hasDuplicates (const SmallVectorImpl< VPBlockBase * > &VPBlockVec)
Utility function that checks whether VPBlockVec has duplicate VPBlockBases.
static void verifyBlocksInRegion (const VPRegionBlock *Region)
Helper function that verifies the CFG invariants of the VPBlockBases within Region.
static void verifyRegion (const VPRegionBlock *Region)
Verify the CFG invariants of VPRegionBlock Region and its nested VPBlockBases.
static void verifyRegionRec (const VPRegionBlock *Region)
Verify the CFG invariants of VPRegionBlock Region and its nested VPBlockBases.
static bool verifyVPBasicBlock (const VPBasicBlock *VPBB, DenseMap< const VPBlockBase *, unsigned > &BlockNumbering)
Variables
static cl::opt< bool > EnableHCFGVerifier ("vplan-verify-hcfg", cl::init(false), cl::Hidden, cl::desc("Verify VPlan H-CFG."))
Detailed Description
This file defines the class VPlanVerifier, which contains utility functions to check the consistency and invariants of a VPlan.
Definition in file VPlanVerifier.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-vectorize"
Definition at line 20 of file VPlanVerifier.cpp.
Function Documentation
hasDuplicates()
static bool hasDuplicates (const SmallVectorImpl< VPBlockBase * > & VPBlockVec) static
Utility function that checks whether VPBlockVec has duplicate VPBlockBases.
Definition at line 31 of file VPlanVerifier.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by verifyBlocksInRegion().
verifyBlocksInRegion()
static void verifyBlocksInRegion (const VPRegionBlock * Region) static
Helper function that verifies the CFG invariants of the VPBlockBases within Region.
Checks in this function are generic for VPBlockBases. They are not specific for VPBasicBlocks or VPRegionBlocks.
Definition at line 45 of file VPlanVerifier.cpp.
References assert(), llvm::dyn_cast(), llvm::RegionBase< Tr >::getEntry(), hasDuplicates(), llvm::is_contained(), and llvm::make_range().
Referenced by verifyRegion().
verifyRegion()
static void verifyRegion (const VPRegionBlock * Region) static
Verify the CFG invariants of VPRegionBlock Region and its nested VPBlockBases.
Do not recurse inside nested VPRegionBlocks.
Definition at line 98 of file VPlanVerifier.cpp.
References assert(), llvm::RegionBase< Tr >::getEntry(), llvm::VPBlockBase::getNumSuccessors(), and verifyBlocksInRegion().
Referenced by verifyRegionRec().
verifyRegionRec()
static void verifyRegionRec (const VPRegionBlock * Region) static
Verify the CFG invariants of VPRegionBlock Region and its nested VPBlockBases.
Recurse inside nested VPRegionBlocks.
Definition at line 114 of file VPlanVerifier.cpp.
References llvm::dyn_cast(), llvm::RegionBase< Tr >::getEntry(), llvm::make_range(), verifyRegion(), and verifyRegionRec().
Referenced by llvm::VPlanVerifier::verifyHierarchicalCFG(), and verifyRegionRec().
verifyVPBasicBlock()
static bool verifyVPBasicBlock (const VPBasicBlock * VPBB, DenseMap< const VPBlockBase *, unsigned > & BlockNumbering) static
Definition at line 137 of file VPlanVerifier.cpp.
References llvm::VPBasicBlock::begin(), llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::VPBasicBlock::end(), llvm::errs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::VPBlockBase::getParent(), I, and llvm::isa().
Referenced by llvm::VPlanVerifier::verifyPlanIsValid().
Variable Documentation
EnableHCFGVerifier
cl::opt< bool > EnableHCFGVerifier("vplan-verify-hcfg", cl::init(false), cl::Hidden, cl::desc("Verify VPlan H-CFG.")) ("vplan-verify-hcfg" , cl::init(false) , cl::Hidden , cl::desc("Verify VPlan H-CFG.")) static
Referenced by llvm::VPlanVerifier::verifyHierarchicalCFG().