LLVM: lib/Target/WebAssembly/WebAssemblyPeephole.cpp File Reference
WebAssemblyPeephole.cpp File Reference
Late peephole optimizations for WebAssembly.
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "Utils/WebAssemblyUtilities.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblySubtarget.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Macros
#define DEBUG_TYPE "wasm-peephole"
Functions
INITIALIZE_PASS (WebAssemblyPeephole, DEBUG_TYPE, "WebAssembly peephole optimizations", false, false) FunctionPass *llvm
static bool maybeRewriteToDrop (unsigned OldReg, unsigned NewReg, MachineOperand &MO, WebAssemblyFunctionInfo &MFI, MachineRegisterInfo &MRI)
If desirable, rewrite NewReg to a drop register.
static bool maybeRewriteToFallthrough (MachineInstr &MI, MachineBasicBlock &MBB, const MachineFunction &MF, WebAssemblyFunctionInfo &MFI, MachineRegisterInfo &MRI, const WebAssemblyInstrInfo &TII)
Variables
static cl::opt< bool > DisableWebAssemblyFallthroughReturnOpt ("disable-wasm-fallthrough-return-opt", cl::Hidden, cl::desc("WebAssembly: Disable fallthrough-return optimizations."), cl::init(false))
Detailed Description
Late peephole optimizations for WebAssembly.
Definition in file WebAssemblyPeephole.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-peephole"
Definition at line 25 of file WebAssemblyPeephole.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblyPeephole , DEBUG_TYPE , "WebAssembly peephole optimizations" , false , false)
Definition at line 53 of file WebAssemblyPeephole.cpp.
maybeRewriteToDrop()
static bool maybeRewriteToDrop (unsigned OldReg, unsigned NewReg, MachineOperand & MO, WebAssemblyFunctionInfo & MFI, MachineRegisterInfo & MRI) static
If desirable, rewrite NewReg to a drop register.
Definition at line 61 of file WebAssemblyPeephole.cpp.
References Changed, MRI, llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setReg(), and llvm::WebAssemblyFunctionInfo::stackifyVReg().
maybeRewriteToFallthrough()
static bool maybeRewriteToFallthrough (MachineInstr & MI, MachineBasicBlock & MBB, const MachineFunction & MF, WebAssemblyFunctionInfo & MFI, MachineRegisterInfo & MRI, const WebAssemblyInstrInfo & TII) static
Definition at line 75 of file WebAssemblyPeephole.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineFunction::back(), llvm::BuildMI(), DisableWebAssemblyFallthroughReturnOpt, llvm::MachineBasicBlock::end(), llvm::WebAssembly::getCopyOpcodeForRegClass(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), MBB, MI, MRI, llvm::WebAssemblyFunctionInfo::stackifyVReg(), and TII.
Variable Documentation
DisableWebAssemblyFallthroughReturnOpt
cl::opt< bool > DisableWebAssemblyFallthroughReturnOpt("disable-wasm-fallthrough-return-opt", cl::Hidden, cl::desc("WebAssembly: Disable fallthrough-return optimizations."), cl::init(false)) ("disable-wasm-fallthrough-return-opt" , cl::Hidden , cl::desc("WebAssembly: Disable fallthrough-return optimizations.") , cl::init(false)) static
Referenced by maybeRewriteToFallthrough().