LLVM: lib/Target/WebAssembly/MCTargetDesc/WebAssemblyWasmObjectWriter.cpp File Reference
WebAssemblyWasmObjectWriter.cpp File Reference
This file handles Wasm-specific object emission, converting LLVM's internal fixups into the appropriate relocations.
#include "MCTargetDesc/WebAssemblyFixupKinds.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWasmObjectWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static const MCSection * getTargetSection (const MCExpr *Expr)
Detailed Description
This file handles Wasm-specific object emission, converting LLVM's internal fixups into the appropriate relocations.
Definition in file WebAssemblyWasmObjectWriter.cpp.
Function Documentation
getTargetSection()
static const MCSection * getTargetSection (const MCExpr * Expr) static
Definition at line 47 of file WebAssemblyWasmObjectWriter.cpp.
References llvm::dyn_cast(), and getTargetSection().
Referenced by getTargetSection().