LLVM: lib/Target/X86/MCA/X86CustomBehaviour.cpp File Reference
X86CustomBehaviour.cpp File Reference
This file implements methods from the X86CustomBehaviour class.
#include "X86CustomBehaviour.h"
#include "TargetInfo/X86TargetInfo.h"
#include "X86InstrInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/WithColor.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::mca
Functions
static InstrPostProcess * createX86InstrPostProcess (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeX86TargetMCA ()
Extern function to initialize the targets for the X86 backend.
Detailed Description
This file implements methods from the X86CustomBehaviour class.
Definition in file X86CustomBehaviour.cpp.
Function Documentation
createX86InstrPostProcess()
static InstrPostProcess * createX86InstrPostProcess (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) static
Definition at line 52 of file X86CustomBehaviour.cpp.
Referenced by LLVMInitializeX86TargetMCA().
LLVMInitializeX86TargetMCA()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeX86TargetMCA ()
Extern function to initialize the targets for the X86 backend.
Definition at line 59 of file X86CustomBehaviour.cpp.
References createX86InstrPostProcess(), llvm::getTheX86_32Target(), llvm::getTheX86_64Target(), and llvm::TargetRegistry::RegisterInstrPostProcess().