LLVM: lib/Target/X86/X86LegalizerInfo.cpp File Reference
X86LegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for X86.
#include "X86LegalizerInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Type.h"
Functions
static void addAndInterleaveWithUnsupported (LegacyLegalizerInfo::SizeAndActionsVec &result, const LegacyLegalizerInfo::SizeAndActionsVec &v)
FIXME: The following static functions are SizeChangeStrategy functions that are meant to temporarily mimic the behaviour of the old legalization based on doubling/halving non-legal types as closely as possible.
static LegacyLegalizerInfo::SizeAndActionsVec widen_1 (const LegacyLegalizerInfo::SizeAndActionsVec &v)
Detailed Description
This file implements the targeting of the Machinelegalizer class for X86.
Todo
This should be generated by TableGen.
Definition in file X86LegalizerInfo.cpp.
Function Documentation
addAndInterleaveWithUnsupported()
static void addAndInterleaveWithUnsupported (LegacyLegalizerInfo::SizeAndActionsVec & result, const LegacyLegalizerInfo::SizeAndActionsVec & v) static
FIXME: The following static functions are SizeChangeStrategy functions that are meant to temporarily mimic the behaviour of the old legalization based on doubling/halving non-legal types as closely as possible.
This is not entirly possible as only legalizing the types that are exactly a power of 2 times the size of the legal types would require specifying all those sizes explicitly. In practice, not specifying those isn't a problem, and the below functions should disappear quickly as we add support for legalizing non-power-of-2 sized types further.
Definition at line 35 of file X86LegalizerInfo.cpp.
References llvm::LegacyLegalizeActions::Unsupported.
Referenced by widen_1().
widen_1()
static LegacyLegalizerInfo::SizeAndActionsVec widen_1 (const LegacyLegalizerInfo::SizeAndActionsVec & v) static
Definition at line 47 of file X86LegalizerInfo.cpp.
References addAndInterleaveWithUnsupported(), assert(), llvm::LegacyLegalizeActions::Unsupported, and llvm::LegacyLegalizeActions::WidenScalar.
Referenced by llvm::X86LegalizerInfo::X86LegalizerInfo().