LLVM: lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp File Reference
X86MCTargetDesc.cpp File Reference
#include "X86MCTargetDesc.h"
#include "TargetInfo/X86TargetInfo.h"
#include "X86ATTInstPrinter.h"
#include "X86BaseInfo.h"
#include "X86IntelInstPrinter.h"
#include "X86MCAsmInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Triple.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "X86GenRegisterInfo.inc"
#include "X86GenInstrInfo.inc"
#include "X86GenSubtargetInfo.inc"
Classes
class llvm::X86_MC::X86MCInstrAnalysis
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::X86_MC
Macros
#define GET_REGINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_HELPERS
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_STIPREDICATE_DECLS_FOR_MC_ANALYSIS
#define GET_STIPREDICATE_DEFS_FOR_MC_ANALYSIS
Functions
static bool isMemOperand (const MCInst &MI, unsigned Op, unsigned RegClassID)
static MCInstrInfo * createX86MCInstrInfo ()
static MCRegisterInfo * createX86MCRegisterInfo (const Triple &TT)
static MCAsmInfo * createX86MCAsmInfo (const MCRegisterInfo &MRI, const Triple &TheTriple, const MCTargetOptions &Options)
static MCInstPrinter * createX86MCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRelocationInfo * createX86MCRelocationInfo (const Triple &TheTriple, MCContext &Ctx)
static std::vector< std::pair< uint64_t, uint64_t > > llvm::X86_MC::findX86PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents, uint64_t GotPltSectionVA)
static std::vector< std::pair< uint64_t, uint64_t > > llvm::X86_MC::findX86_64PltEntries (uint64_t PltSectionVA, ArrayRef< uint8_t > PltContents)
static MCInstrAnalysis * createX86MCInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeX86TargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 40 of file X86MCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 38 of file X86MCTargetDesc.cpp.
GET_INSTRINFO_MC_HELPERS
#define GET_INSTRINFO_MC_HELPERS
Definition at line 39 of file X86MCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 35 of file X86MCTargetDesc.cpp.
GET_STIPREDICATE_DECLS_FOR_MC_ANALYSIS
#define GET_STIPREDICATE_DECLS_FOR_MC_ANALYSIS
Definition at line 496 of file X86MCTargetDesc.cpp.
GET_STIPREDICATE_DEFS_FOR_MC_ANALYSIS
#define GET_STIPREDICATE_DEFS_FOR_MC_ANALYSIS
Definition at line 517 of file X86MCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 43 of file X86MCTargetDesc.cpp.
Function Documentation
createX86MCAsmInfo()
static MCAsmInfo * createX86MCAsmInfo (const MCRegisterInfo & MRI, const Triple & TheTriple, const MCTargetOptions & Options) static
Definition at line 420 of file X86MCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCCFIInstruction::createOffset(), llvm::Triple::getArch(), is64Bit(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSCygMing(), llvm::Triple::isWindowsCoreCLREnvironment(), llvm::Triple::isWindowsItaniumEnvironment(), llvm::Triple::isWindowsMSVCEnvironment(), MRI, Options, and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
createX86MCInstPrinter()
static MCInstPrinter * createX86MCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 467 of file X86MCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeX86TargetMC().
createX86MCInstrAnalysis()
static MCInstrAnalysis * createX86MCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 692 of file X86MCTargetDesc.cpp.
Referenced by LLVMInitializeX86TargetMC().
createX86MCInstrInfo()
static MCInstrInfo * createX86MCInstrInfo () static
Definition at line 402 of file X86MCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeX86TargetMC().
createX86MCRegisterInfo()
static MCRegisterInfo * createX86MCRegisterInfo (const Triple & TT) static
Definition at line 408 of file X86MCTargetDesc.cpp.
References llvm::X86_MC::getDwarfRegFlavour(), llvm::X86_MC::initLLVMToSEHAndCVRegMapping(), RA, X, and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
createX86MCRelocationInfo()
static MCRelocationInfo * createX86MCRelocationInfo (const Triple & TheTriple, MCContext & Ctx) static
Definition at line 479 of file X86MCTargetDesc.cpp.
References llvm::createMCRelocationInfo().
Referenced by LLVMInitializeX86TargetMC().
isMemOperand()
static bool isMemOperand (const MCInst & MI, unsigned Op, unsigned RegClassID) static
Definition at line 76 of file X86MCTargetDesc.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::sampleprof::Base, llvm::MCRegisterClass::contains(), and MI.
Referenced by llvm::X86_MC::is16BitMemOperand(), llvm::X86_MC::is32BitMemOperand(), and llvm::X86_MC::is64BitMemOperand().
LLVMInitializeX86TargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeX86TargetMC ()
Definition at line 697 of file X86MCTargetDesc.cpp.
References llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::createX86AsmTargetStreamer(), createX86MCAsmInfo(), llvm::createX86MCCodeEmitter(), createX86MCInstPrinter(), createX86MCInstrAnalysis(), createX86MCInstrInfo(), createX86MCRegisterInfo(), createX86MCRelocationInfo(), llvm::X86_MC::createX86MCSubtargetInfo(), llvm::createX86ObjectTargetStreamer(), llvm::createX86WinCOFFStreamer(), llvm::getTheX86_32Target(), llvm::getTheX86_64Target(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterCOFFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.